### PR TITLE
drivers: wifi: simplelink: fix Coverity issue in getaddrinfo()

### LINKED ISSUE #11090: [Coverity CID :189516]Null pointer dereferences in /drivers/wifi/simplelink/simplelink_sockets.c
Static code scan issues seen in File: /drivers/wifi/simplelink/simplelink_sockets.c
 Category: Null pointer dereferences
 Function: simplelink_getaddrinfo
 Component: Drivers
 CID: 189516
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by GAnthony**
Check for case where host == NULL but service != NULL
could have resulted later in a NULL dereference.

Fixes #11090

Signed-off-by: Gil Pitney <gil.pitney@linaro.org>

### CODE REVIEW

File: drivers/wifi/simplelink/simplelink_sockets.c [hunk 1]
```diff
@@ -518,7 +518,7 @@ static ssize_t simplelink_sendto(int sd, const void *buf, size_t len,
 /*
  * Later SimpleLink SDK versions implement the full getaddrinfo semantics,
  * returning potentially multiple IP addresses.
- * This version implements a simple gethostbyname() API.
+ * This version implements a simple gethostbyname() API for client only.
```
Comment (pfalcon) [inline drivers/wifi/simplelink/simplelink_sockets.c]: Not sure about this change.

**Review by pfalcon — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by himanshujha199640** [comment]
Nit: I think we should add `Coverity-CID: <number>` in commit log for two reasons:

* give credits to coverity static analysis system.
* I'm also a member of coverity scan for linux kernel and coverity regularly greps commit logs to ensure
if a particular bugs has been fixed or not. Though admins of coverity usually fill up the triage history
to mark it as fixed but not others have the permission to fill up the triage(like myself).

**Comment by jukkar** [comment]
> I think we should add `Coverity-CID: <number>` in commit log for two reasons:

That is a good point, @GAnthony can you add that and re-submit.

File: drivers/wifi/simplelink/simplelink_sockets.c (hunk 1 above)
Comment (GAnthony) [reply drivers/wifi/simplelink/simplelink_sockets.c]: Well, it's true it's not specifically required for the coverity bug fix, but some indication that the implementation is naive, just sufficient for its current usage in Zephyr.

**Comment by GAnthony** [comment]
OK.  I'll add the Coverity ID to the commit message.  Good idea.
