### PR TITLE
drivers: clock_control: nrf: Fix error during initialization

### LINKED ISSUE #25568: nrf: clock_control: Fatal error during initialization
**Describe the bug**
Having a combination of `CONFIG_POLL=y`, a large mbedtls heap and using the RC oscillator as K32SRC causes a fatal error during initialization.

Changing anyone of these and the problem seem to go away. Another way to make the problem go away is to change the init prio of mbedtls where the heap initialization happens. (`modules/crypto/mbedtls/zephyr_init.c`)

**To Reproduce**
I used a `nrf52840dk_nrf52840` board and the following `prj.conf` in `samples/hello_world`

```
CONFIG_POLL=y

CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=100000

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
```

**Screenshots or console output**
Here is a backtrace from @carlescufi 

```
(gdb) bt
#0  arch_system_halt (reason=reason@entry=0) at /home/carles/src/zephyr/zephyr/kernel/fatal.c:31
#1  0x00003f7c in k_sys_fatal_error_handler (reason=reason@entry=0,
    esf=esf@entry=0x20019b88 <z_interrupt_stacks+1888>) at /home/carles/src/zephyr/zephyr/kernel/fatal.c:43
#2  0x00003fa0 in z_fatal_error (reason=reason@entry=0, esf=esf@entry=0x20019b88 <z_interrupt_stacks+1888>)
    at /home/carles/src/zephyr/zephyr/kernel/fatal.c:123
#3  0x00003bdc in z_arm_fatal_error (reason=reason@entry=0, esf=esf@entry=0x20019b88 <z_interrupt_stacks+1888>)
    at /home/carles/src/zephyr/zephyr/arch/arm/core/aarch32/fatal.c:47
#4  0x00001130 in z_arm_fault (msp=<optimized out>, psp=<optimized out>, exc_return=<optimized out>)
    at /home/carles/src/zephyr/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:969
#5  0x00000ffc in z_arm_usage_fault () at /home/carles/src/zephyr/zephyr/arch/arm/core/aarch32/cortex_m/fault_s.S:85
#6  <signal handler called>
#7  0x00004718 in sys_dlist_remove (node=0x0 <z_finalize_fd>) at ../include/sys/dlist.h:518
#8  sys_dlist_get (list=list@entry=0x200003b0 <k_sys_work_q+8>) at ../include/sys/dlist.h:518
#9  z_handle_obj_poll_events (events=events@entry=0x200003b0 <k_sys_work_q+8>, state=state@entry=4)
    at /home/carles/src/zephyr/zephyr/kernel/poll.c:406
#10 0x00004030 in handle_poll_events (state=4, queue=0x200003a8 <k_sys_work_q>)
    at /home/carles/src/zephyr/zephyr/kernel/queue.c:179
#11 queue_insert (queue=0x200003a8 <k_sys_work_q>, prev=0x0 <z_finalize_fd>, data=<optimized out>,
    alloc=<optimized out>) at /home/carles/src/zephyr/zephyr/kernel/queue.c:179
#12 0x000008cc in clkstarted_handle (type=<optimized out>, dev=0x2000005c <__device_clock_nrf>)
    at /home/carles/src/zephyr/zephyr/drivers/clock_control/nrf_power_clock.c:366
#13 0x000008fe in nrf_power_clock_isr (arg=<optimized out>)
    at /home/carles/src/zephyr/zephyr/drivers/clock_control/nrf_power_clock.c:421
#14 0x00000fa6 in _isr_wrapper () at /home/carles/src/zephyr/zephyr/arch/arm/core/aarch32/isr_wrapper.S:195
```

**Environment:**
Commit 1a89ca1238f08610c0fca59ef70b43c8bbfe3c95

### PR DESCRIPTION
**Pull request by nordic-krch**
In certain configurations, calibration may be started before kernel is
up and running. That lead to error because calibration is using kernel
api (work queue). Issue was observed if low frequency clock was started
before kernel initialization.

Moved calibration initialization to application phase because system
work queue is initialized in post kernel phase.

Fixes #25568.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

File: drivers/clock_control/nrf_power_clock.c [hunk 1]
```diff
@@ -424,11 +420,11 @@ void nrf_power_clock_isr(void *arg)
 
 	if (clock_event_check_and_clean(NRF_CLOCK_EVENT_LFCLKSTARTED,
 					NRF_CLOCK_INT_LF_STARTED_MASK)) {
+		clkstarted_handle(dev, CLOCK_CONTROL_NRF_TYPE_LFCLK);
 		if (IS_ENABLED(
 			CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION)) {
 			z_nrf_clock_calibration_lfclk_started();
 		}
-		clkstarted_handle(dev, CLOCK_CONTROL_NRF_TYPE_LFCLK);
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c:431]: I don't entirely understand the motivation of this change. I thought the calibration was to be started ASAP after the LF clock gets running, before any user callbacks. Why was the order inverted?

Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c:431]: the problem is that calibration is using system work queue which is initialized in post kernel so when LF clock is started before system work queue is ready then error occurs. Configuration provided in the issue was provoking this case.

I don't like this solution and it would be better to not rely on work queue but for that #21667 would need to be merged and that won't happen for that release.

Comment (anangl) [reply drivers/clock_control/nrf_power_clock.c:431]: Yes, I understand the issue and the idea behind this PR.
My comment was only about moving `clkstarted_handle(dev, CLOCK_CONTROL_NRF_TYPE_LFCLK)` before `z_nrf_clock_calibration_lfclk_started()`. Is that actually needed?

**Review by pabigot — COMMENTED** [review]
If the only thing we need the work queue for during calibration is the temperature, why not just delay initializing `temp_sensor` until we reach the `APPLICATION` init level?  From what I can tell that will prevent entering a code path that requires the kernel.

Then we can have the clock calibration start early, if not as early as proposed in #22758.

**Comment by carlescufi** [comment]
@nordic-krch and @anangl ping on this one.

**Comment by nordic-krch** [comment]
@pabigot 

> If the only thing we need the work queue for during calibration is the temperature, why not just delay initializing temp_sensor until we reach the APPLICATION init level? From what I can tell that will prevent entering a code path that requires the kernel.

That will not delay usage of `k_work_queue` since it is only skipped if `temp_sensor` handle is null and fetching device handle before it is being initialized will return valid handle.

File: drivers/clock_control/nrf_power_clock.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c:431]: handling of lfclk started event changes state of the clock. If `z_nrf_clock_calibration_lfclk_started` is called earlier then it won't start calibration because clock is not yet started. If init was executed earlier then calibration will never be started.

**Comment by pabigot** [comment]
> That will not delay usage of `k_work_queue` since it is only skipped if `temp_sensor` handle is null and fetching device handle before it is being initialized will return valid handle.

That's exactly my point.  Move:
```
        if (CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP != 0) {
                temp_sensor = temp_device();
        }
```
from `z_nrf_clock_calibration_init()` to a `SYS_INIT` function that runs after this one from `kernel/system_work_q.c`:

    SYS_INIT(k_sys_work_q_init, POST_KERNEL, CONFIG_KERNEL_INIT_PRIORITY_DEFAULT);

File: drivers/clock_control/nrf_power_clock.c (hunk 1 above)
Comment (anangl) [reply drivers/clock_control/nrf_power_clock.c:431]: But `z_nrf_clock_calibration_lfclk_started` does not check the state of the clock. It only needs the `clock_dev` pointer to start the calibration. And this pointer is set in `z_nrf_clock_calibration_init` regardless of whether the clock is running or not. So I still don't see the need of this inversion of the order.

**Comment by nordic-krch** [comment]
@pabigot applied your suggestion.

**Review by carlescufi — APPROVED** [review]
Very nice solution.

**Review by pabigot — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Comment by carlescufi** [comment]
Note: I also verified that this runs correctly with the sample that was provided in #25568.
