### PR TITLE
Bluetooth: L2CAP: Add check to see if device is not disconnecting

### LINKED ISSUE #48813: Bluetooth: bt_conn_disconnect randomly gives error "bt_conn: not connected!"
**Describe the bug**
Platform: nRF52840
When calling bt_conn_disconnect() in a BLE-characteristic write-callback I get randomly returned the following error:

```
[00:00:22.404,479] <inf> main: Data cleared. Disconnecting...
[00:00:22.454,803] <err> bt_conn: not connected!
[00:00:22.455,139] <wrn> bt_hci_core: opcode 0x2013 status 0x02
[00:00:22.455,535] <inf> main: Disconnected: C5:DC:C7:91:04:9B (random) (reason 0x16)
```

Stripped down function where I call bt_conn_disconnect():
```
static void on_data_reset_cb(struct bt_prx_client *prx_c,
									 int err)
{
	if (err)
	{
		LOG_ERR("Failed to reset data in callback.");
		bt_conn_disconnect(prx_c->conn, BT_HCI_ERR_REMOTE_USER_TERM_CONN);
	}
	else
	{

			LOG_INF("Data cleared. Disconnecting...");
			bt_conn_disconnect(prx_c->conn, BT_HCI_ERR_REMOTE_USER_TERM_CONN);
	}
}
```

When enabling debug logs using the below prj.conf options the error seems to dissapear. This makes me believe that there is some sort of timing-issue.
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_DEBUG_CONN=y

The call-stack of the "bt_conn: not connected!" error-print in OZone is the following: 
image

Using OZone I can see that in the code below (responsible for printing the connection-error) the connection state is currently `BT_CONN_DISCONNECTING`
```
if (conn->state != BT_CONN_CONNECTED) {
    BT_ERR("not connected!");
    return -ENOTCONN;
  }
```

At first glance it seems like the application is trying to update the connection parameters when the connection is currently disconnecting and thus giving an error. Not entirely sure why that is happening, I have `CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n` set

I noticed the same ble_hci_core warning in issue https://github.com/zephyrproject-rtos/zephyr/issues/48505 . Not sure if they are related?

**Impact**
Currently the error seems to be harmless and can be ignored, although we have not run this application for a considerable amount of time.

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: NCS - Zephyr
 - Zephyr OS build v3.0.99-ncs1

### PR DESCRIPTION
**Pull request by Klievan**
Currently, if a bluetooth peripheral sends a connection parameter update
request to a Zephyr central while the central is in the process of
disconnecting and has sent a connection terminate command in the same
connection interval, the central will try to reply, resulting in an
error being printed in the console.

This commit adds a check in le_conn_param_update_req that catches this
state before the central considers this request, preventing the unneeded
error being printed.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/48813

Signed-off-by: Ivan Herrera Olivares <ivan.herreraolivares@uantwerpen.be>

### CODE REVIEW

File: subsys/bluetooth/host/l2cap.c [hunk 1]
```diff
@@ -701,6 +701,11 @@ static void le_conn_param_update_req(struct bt_l2cap *l2cap, uint8_t ident,
 		return;
 	}
 
+	if (conn->state == BT_CONN_DISCONNECTING) {
+		BT_WARN("Device is disconnecting");
```
Comment (jori-nordic) [inline subsys/bluetooth/host/l2cap.c:705]: can you rather do `!= BT_CONN_STATE_CONNECTED` and say `Not connected` in the message?

Comment (Klievan) [reply subsys/bluetooth/host/l2cap.c]: Should be resolved in https://github.com/zephyrproject-rtos/zephyr/pull/48942/commits/acc95d5c4b49f23b2bddeddd75c62ba700d69e73

**Review by alwa-nordic — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

**Comment by Klievan** [comment]
Had to recommit as the commit title wasn't following patch series compliance. Code is identical.

**Review by jori-nordic — DISMISSED** [review]

**Comment by jori-nordic** [comment]
Could you squash the two commits? What's the difference between the two values?

**Comment by Klievan** [comment]
> Could you squash the two commits? What's the difference between the two values?

Squashed. I was having build-errors in some tests due to some warnings against comparing the enums. I noticed this version of the enum was being used in `conn.c` in `bt_conn_send_cb`

**Review by jhedberg — APPROVED** [review]

**Comment by Klievan** [comment]
@jori-nordic Somehow the enum type used switched during a rebase to address your initial comments. (https://github.com/zephyrproject-rtos/zephyr/commit/3d7bef0b276ee47daa3c27a2c149360e91a5c17a to https://github.com/zephyrproject-rtos/zephyr/commit/acc95d5c4b49f23b2bddeddd75c62ba700d69e73). This was causing some tests including the bluetooth tests to fail. `BT_CONN_CONNECTED` seems to be the correct enum and all tests are passing again.

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]
