### PR TITLE
drivers: eth_enc424j600: explicitly disable INTIE after reset

### LINKED ISSUE #35091: enc424j600 does not work
**Describe the bug**
We are using a enc424j600 device with our BL5340 board (nRF5340-based) and running the sample apps for network (e.g. dumb_http_server) results in a failed networking start up. There is a strange way to get it working however, if the module is booted with the enc424j600's interrupt line disconnect and then connected after a bootup

**To Reproduce**
Build dumb_http_server for enc424j600 and run it

**Expected behavior**
With the changes made:
```
*** Booting Zephyr OS build zephyr-v2.4.0-3426-g70ec734b87c3  ***
[00:00:00.368,804] <dbg> ethdrv.enc424j600_init_filters: ERXFCON: 0x005b
[00:00:00.369,140] <dbg> ethdrv.enc424j600_init_phy: PHANA: 0x05e1
[00:00:00.369,354] <dbg> ethdrv.enc424j600_init_phy: PHCON1: 0x1200
[00:00:00.369,537] <dbg> ethdrv.enc424j600_init: EIE: 0x8850
[00:00:00.369,598] <dbg> ethdrv.enc424j600_init: ECON1: 0x0001
[00:00:00.369,659] <inf> ethdrv: ENC424J600 Initialized
[00:00:00.375,549] <inf> net_config: Initializing network
[00:00:00.375,549] <inf> net_config: Waiting interface 1 (0x20000f0c) to be up...
Single-threaded dumb HTTP server waits for a connection on port 8080...
[00:00:05.609,771] <err> ethdrv: handling int
[00:00:05.609,893] <dbg> ethdrv.enc424j600_rx_thread: ESTAT: 0xdf00
[00:00:05.609,924] <inf> ethdrv: Link up
[00:00:05.610,137] <dbg> ethdrv.enc424j600_setup_mac: PHANLPA: 0x85e1
[00:00:05.610,321] <inf> ethdrv: 100Mbps
[00:00:05.610,321] <inf> ethdrv: full duplex
[00:00:05.610,473] <dbg> ethdrv.enc424j600_setup_mac: MACON2: 0x40b3
[00:00:05.610,504] <dbg> ethdrv.enc424j600_setup_mac: MAMXFL (maximum frame length): 1518
[00:00:05.610,534] <inf> ethdrv: Not suspended
[00:00:05.610,565] <inf> net_config: Interface 1 (0x20000f0c) coming up
[00:00:05.610,656] <inf> net_config: IPv4 address: 192.168.1.55
```

**Impact**
Driver is useless, network is useless, showstopper

**Logs and console output**
Output with interrupt line connected as normal:
```
*** Booting Zephyr OS build zephyr-v2.4.0-3426-g70ec734b87c3  ***
[00:00:00.629,699] <dbg> ethdrv.enc424j600_init_filters: ERXFCON: 0x005b
[00:00:00.630,035] <dbg> ethdrv.enc424j600_init_phy: PHANA: 0x05e1
[00:00:00.630,218] <dbg> ethdrv.enc424j600_init_phy: PHCON1: 0x1200
[00:00:00.630,432] <dbg> ethdrv.enc424j600_init: EIE: 0x8850
[00:00:00.630,493] <dbg> ethdrv.enc424j600_init: ECON1: 0x0001
[00:00:00.630,523] <err> ethdrv: handling int
[00:00:00.630,615] <inf> ethdrv: ENC424J600 Initialized
[00:00:00.630,676] <dbg> ethdrv.enc424j600_rx_thread: ESTAT: 0xda00
[00:00:00.630,706] <inf> ethdrv: Link down
[00:00:00.630,737] <err> ethdrv: handling int
[00:00:00.630,859] <dbg> ethdrv.enc424j600_rx_thread: ESTAT: 0x5a00
[00:00:00.630,859] <err> ethdrv: Unknown Interrupt, EIR: 0x0700
[00:00:00.636,718] <inf> net_config: Initializing network
[00:00:00.636,749] <inf> net_config: Waiting interface 1 (0x20000f0c) to be up...
Single-threaded dumb HTTP server waits for a connection on port 8080...
[00:00:24.637,725] <err> net_config: Timeout while waiting network interface
[00:00:24.637,725] <err> net_config: Network initialization failed (-115)
```

**Environment (please complete the following information):**
 - OS: Windows 10 64-bit
 - Toolchain: GNU ARM GCC
 - Commit SHA: From nRF connect SDK 1.5.99

### PR DESCRIPTION
**Pull request by jfischer-no**
After system reset (SETETHRST) interrupt enable register (EIE)
has the default value 0x8010 and global interrupt enable flag (INTIE)
is set. This is not desired and the INTIE flag should be set only at
the end of the initialization.
Disable INTIE flag and set desired interrupts sources in
a single write command just right after system reset.

Also clarify how unknown interrupt source should be handled.

Alternative fix for #35091
Fixes #35091

### CODE REVIEW

File: drivers/ethernet/eth_enc424j600.c [hunk 1]
```diff
@@ -484,7 +484,11 @@ static void enc424j600_rx_thread(struct enc424j600_runtime *context)
 			}
 		} else {
 			LOG_ERR("Unknown Interrupt, EIR: 0x%04x", eir);
-			continue;
+			/*
+			 * Terminate interrupt handling thread because
+			 * the integrity of the driver is no longer given.
+			 */
+			k_oops();
```
Comment (lairdjm) [inline drivers/ethernet/eth_enc424j600.c:491]: I do not accept this, the linux kernel driver ignores any unknown interrupts, no other zephyr ethernet driver does this. This k_oops and the continue needs to go entirely.

**Review by nordicjm — CHANGES_REQUESTED** [review]

File: drivers/ethernet/eth_enc424j600.c (hunk 1 above)
Comment (jukkar) [reply drivers/ethernet/eth_enc424j600.c:491]: I am not a big fan of `k_oops()`, the device stop running after that which might not be desirable in embedded device.
Is it so that getting into this branch should not be possible after the changes in second commit?

**Review by jukkar — COMMENTED** [review]
Looks good, just wondering about the use of k_oops

File: drivers/ethernet/eth_enc424j600.c (hunk 1 above)
Comment (jfischer-no) [reply drivers/ethernet/eth_enc424j600.c:491]: > Is it so that getting into this branch should not be possible after the changes in second commit?

It should never be the case. The second commit fixes a bug that was found thanks to this brunch. Faulty driver should not just keep running. AFAIK we do not have any possibilities to tell the stack or application about an error from driver thread. I might be exaggerating, I could probably live with hiding it behind LOG_LEVEL_DBG, and it would also fit the style of the driver. But logging is for developer, in the field such an error would remains undetected.

```diff c
diff --git a/drivers/ethernet/eth_enc424j600.c b/drivers/ethernet/eth_enc424j600.c
index 417b66ae07..f86718f319 100644
--- a/drivers/ethernet/eth_enc424j600.c
+++ b/drivers/ethernet/eth_enc424j600.c
@@ -484,7 +484,9 @@ static void enc424j600_rx_thread(struct enc424j600_runtime *context)
                        }
                } else {
                        LOG_ERR("Unknown Interrupt, EIR: 0x%04x", eir);
-                       continue;
+                       if (CONFIG_ETHERNET_LOG_LEVEL == LOG_LEVEL_DBG) {
+                               k_oops();
+                       }
                }
 
                enc424j600_set_sfru(context->dev, ENC424J600_SFR3_EIEL,
```

Comment (lairdjm) [reply drivers/ethernet/eth_enc424j600.c:491]: The issue that this bug fixed wouldn't have been an issue at all had the continue/k_oops not been there, the driver would have ignore the first spurious interrupt and then continued to process the second valid interrupt and functioned properly. Having just a log output with no continue/k_oops is fine with me.

Comment (jukkar) [reply drivers/ethernet/eth_enc424j600.c:491]: > I could probably live with hiding it behind LOG_LEVEL_DBG

Your proposal looks like a good tradeoff :+1: 

About the error happening in the field, that is certainly possible, but in that case perhaps it is better to ignore/skip the issue than to halt.

Comment (jfischer-no) [reply drivers/ethernet/eth_enc424j600.c:491]: > The issue that this bug fixed wouldn't have been an issue at all had the continue/k_oops not been there, the driver would have ignore the first spurious interrupt and then continued to process the second valid interrupt and functioned properly. Having just a log output with no continue/k_oops is fine with me.

So you mean that there is no other bug except the one suspected in line 487? So is it okay for your products that there is an interrupt in the Ethernet driver firing for no reason?

Comment (lairdjm) [reply drivers/ethernet/eth_enc424j600.c:491]: Drivers and applications are designed to cope with simplistic errors, e.g. a false interrupt, which could be caused by many things including a error in the silicon (of which Microchip note there is a bug in the enc424j600 silicon which causes a spurious interrupt), an error in the MCU silicon or firmware or even from an external source e.g. by a motor. You show me where in the linux kernel (which is used in thousands of embedded devices) whereby a network or modem driver will kill the system if it receives an unexpected interrupt or command:

**Review by jukkar — APPROVED** [review]
Thanks Johann :+1: LGTM

**Review by nordicjm — APPROVED** [review]
Still not happy with the k_oops, no way should that be this code at all, but it's excluded by default so I'm done trying to explain driver development
