### PR TITLE
ethernet: phy: add dt prop for default speed

### LINKED ISSUE #85050: drivers: ethernet: eth_stm32_hal.c Configure Link According to configuration
**Describe the bug**
If auto-negotiation is disabled, the driver should take speed from the build configuration (kconfig). But if the speed is configured to be 10M, the system still advertises 100M. This causes the peer to establish a 100M link, that does not work.
For example the following configuration:
```
CONFIG_ETH_STM32_SPEED_10M=y
CONFIG_ETH_STM32_AUTO_NEGOTIATION_ENABLE=n
```

The reason for this is, that `phy_mii.c` configures all speed at init.
```C
		/* Advertise all speeds */
		phy_mii_cfg_link(dev, LINK_HALF_10BASE_T |
				      LINK_FULL_10BASE_T |
				      LINK_HALF_100BASE_T |
				      LINK_FULL_100BASE_T |
				      LINK_HALF_1000BASE_T |
				      LINK_FULL_1000BASE_T
				      );
```
And the `stm32_hal`-driver never rectifies that.

**To Reproduce**
Build with above configuration. A 100Mbit Link will be "established", even though this should not be possible.

**Workaround**
This fixes:
```C
		/* Advertise all speeds */
		phy_mii_cfg_link(dev, LINK_HALF_10BASE_T |
				      LINK_FULL_10BASE_T //|
				      //LINK_HALF_100BASE_T |
				      //LINK_FULL_100BASE_T |
				      //LINK_HALF_1000BASE_T |
				      //LINK_FULL_1000BASE_T
				      );
```
For a proper solution, `eth_stm32_hal.c` should probably call `cfg_link` on the `ethphy_driver_api` with the correct `enum phy_link_speed` after/during initialization.

**Expected behavior**
Only 10Mbit Links are possible under above configuration.

**Impact**
As there is currently a bug with auto-negotiation in this driver (fix in progress, see for example https://github.com/zephyrproject-rtos/zephyr/issues/81847), it is very likely, that user want to disable it in favor of fixed configuration. It would be great if fixed configuration would work.

**Logs and console output**
TBD

**Environment (please complete the following information):**
TBD

**Additional context**
TBD

### PR DESCRIPTION
**Pull request by maass-hamburg**
add dt prop for default speeds, that the phy is
configured on init by default.

Contains:  https://github.com/zephyrproject-rtos/zephyr/pull/88411 (all commits before drivers: ethernet: phy: add dt prop for default speeds)

### CODE REVIEW

File: drivers/ethernet/phy/phy_mii.c [hunk 1]
```diff
@@ -548,12 +549,7 @@ static int phy_mii_initialize(const struct device *dev)
 		data->gigabit_supported = is_gigabit_supported(dev);
 
 		/* Advertise all speeds */
-		phy_mii_cfg_link(dev, LINK_HALF_10BASE |
-				      LINK_FULL_10BASE |
-				      LINK_HALF_100BASE |
-				      LINK_FULL_100BASE |
-				      LINK_HALF_1000BASE |
-				      LINK_FULL_1000BASE);
+		phy_mii_cfg_link(dev, cfg->default_speeds);
```
Comment (clamattia) [inline drivers/ethernet/phy/phy_mii.c:552]: I like, that it does not advertise all speeds now. Please also adjust the comment.

Comment (maass-hamburg) [reply drivers/ethernet/phy/phy_mii.c:552]: By default we will still do, but it now can be changed by the user in the dt. We mostly want to preserve default behavior.

Comment (maass-hamburg) [reply drivers/ethernet/phy/phy_mii.c]: changed it now

**Review by ghost — DISMISSED** [review]
I can not judge the DT-changes. Rest looks good to me.

**Review by rruuaanng — DISMISSED** [review]

**Comment by rruuaanng** [comment]
I hope to receive more suggestions.

**Review by decsny — DISMISSED** [review]

File: doc/releases/migration-guide-4.2.rst [hunk 2]
```diff
@@ -108,6 +108,12 @@ DAI
 * Renamed the devicetree property ``quad_ch`` to ``quad-ch``.
 * Renamed the devicetree property ``int_odd`` to ``int-odd``.
 
+Devicetree
+==========
```
[the remark this answers is not in the document]
Comment (maass-hamburg) [reply doc/releases/migration-guide-4.2.rst]: changed it

**Comment by maass-hamburg** [comment]
rebased to current main and changed entry in migration guide

**Comment by maass-hamburg** [comment]
rebased due to unrelated problem with ci runner

**Review by decsny — DISMISSED** [review]

**Comment by maass-hamburg** [comment]
rebased due to conflicts

**Review by ghost — DISMISSED** [review]
Nice, work.
We would need this.
@maass-hamburg could you rebase?
Are there any known blockers?

**Comment by maass-hamburg** [comment]
rebased due to conflicts

**Review by ghost — APPROVED** [review]

**Review by rruuaanng — APPROVED** [review]
I don't have a problem with this, but I think it might make some existing code that assumes `idx=0` by default look a little weird. :(
