### PR TITLE
drivers: usb: udc: stm32: driver cleanup and EP MPS fixes

### LINKED ISSUE #95514: USB sample not working on STM32
### Describe the bug

Compiling the sample/subsys/usb/testusb sample for an STM32L412 platform on a custom board.
It fails with:
```
*** Booting Zephyr OS build v4.2.0-2937-gac8d17955223 ***
[00:00:00.000,000] <inf> usbd_init: interface 0 alternate 0
[00:00:00.000,000] <inf> usbd_init:     ep 0x81 mps 0x0040 interface ep-bm 0x00020000
[00:00:00.000,000] <inf> usbd_init:     ep 0x01 mps 0x0040 interface ep-bm 0x00020002
[00:00:00.000,000] <inf> usbd_init: interface 1 alternate 0
[00:00:00.000,000] <inf> usbd_init:     ep 0x82 mps 0x0040 interface ep-bm 0x00040000
[00:00:00.000,000] <inf> usbd_init:     ep 0x02 mps 0x0040 interface ep-bm 0x00040004
[00:00:00.000,000] <inf> usbd_init: interface 2 alternate 0
[00:00:00.000,000] <inf> usbd_init:     ep 0x83 mps 0x0000 interface ep-bm 0x00080000
[00:00:00.000,000] <inf> usbd_init:     ep 0x03 mps 0x0000 interface ep-bm 0x00080008
[00:00:00.000,000] <inf> usbd_init: interface 2 alternate 1
[00:00:00.000,000] <inf> usbd_init:     ep 0x83 mps 0x0100 interface ep-bm 0x00080000
[00:00:00.000,000] <err> usbd_init: Failed to assign endpoint addresses
[00:00:00.000,000] <err> usbd_init: Failed to init FS configuration 1
[00:00:00.000,000] <err> main: Failed to initialize device support
```

- It works with Zephyr 3.5, but fails on current 4.2.99 main
- Some samples are still working (like sample/subsys/usb/midi)

### Regression

- [x] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mathieuchopstm**
Cleans up various parts of the STM32 UDC shim driver while also fixing issues related to endpoint sizes.

### CODE REVIEW

**Review by tmon-nordic — DISMISSED** [review]

File: drivers/usb/udc/udc_stm32.c [hunk 1]
```diff
@@ -608,7 +607,12 @@ static inline void udc_stm32_mem_init(const struct device *dev)
 	struct udc_stm32_data *priv = udc_get_private(dev);
 	const struct udc_stm32_config *cfg = dev->config;
 
-	priv->occupied_mem = cfg->pma_offset;
+	/**
+	 * Endpoint configuration table is placed at the
+	 * beginning of Private Memory Area and consumes
+	 * 8 bytes for each endpoint.
+	 */
+	priv->occupied_mem = (8 * cfg->num_endpoints);
```
Comment (etienne-lms) [inline drivers/usb/udc/udc_stm32.c]: Nitpicking: could drop parentheses.

File: drivers/usb/udc/udc_stm32.c [hunk 2]
```diff
@@ -121,6 +121,17 @@ LOG_MODULE_REGISTER(udc_stm32, CONFIG_UDC_DRIVER_LOG_LEVEL);
...
+ * Returns max packet size allowed for endpoints of 'usb_node'
+ *
+ * Hardware always supports the maximal value allowed
+ * by the USB Specification at a given operating speed:
+ * 1024 bytes in High-Speed, 1023 bytes in Full-Speed
+ */
+#define UDC_STM32_NODE_EP_MPS(node_id)					\
+	((UDC_STM32_NODE_SPEED(node_id) == PCD_SPEED_HIGH) ? 1024U : 1023U)
+
+
```
Comment (etienne-lms) [inline drivers/usb/udc/udc_stm32.c]: Nitpicking: could you remove this extra empty line?

File: drivers/usb/udc/udc_stm32.c [hunk 3]
```diff
@@ -1070,18 +1082,7 @@ static const struct udc_api udc_stm32_api = {
  * Kconfig system.
  */
```
Comment (etienne-lms) [inline drivers/usb/udc/udc_stm32.c:1093]: Are these inline comment still useful? (non-blocking, liekly a bit outside the scope of this P-R)

**Review by etienne-lms — COMMENTED** [review]
LGTM. Some minor comments.

File: drivers/usb/udc/udc_stm32.c (hunk 3 above)
Comment (mathieuchopstm) [reply drivers/usb/udc/udc_stm32.c:1093]: IMO the comment still applies because there is some usage remaining of the Cube macros (see L1115 in new file). But eventually it should be removed yes.

File: drivers/usb/udc/udc_stm32.c (hunk 1 above)
Comment (mathieuchopstm) [reply drivers/usb/udc/udc_stm32.c]: My bad, copy-paste artifact from expanding `USB_BTABLE_SIZE` = `(8 * USB_NUM_BIDIR_ENDPOINTS)`.

**Comment by mathieuchopstm** [comment]
I am seeing a regression on `b_u585i_iot02a` (`st,stm32-otgfs`) because of the following:
https://github.com/zephyrproject-rtos/zephyr/blob/8940344e4a0cdffb6f2550ec5a2bd9db4c4335ba/drivers/usb/udc/udc_stm32.c#L667-L670

This SoC has only 1280 bytes of DRAM. Beforehand, `cfg->ep_mps` was a small value (`USB_OTG_FS_MAX_PACKET_SIZE` = 64) so the result of `MAX(160, cfg->ep_mps / 4)` was 160 words = 640 bytes allocated for the RX FIFO. Now that `cfg->ep_mps = 1023`, the result of `MAX(160, DIV_ROUND_UP(cfg->ep_mps, 4U))` is ((1023 + 3) / 4) = 256 words and 1024 bytes are allocated for the RX FIFO.

In addition, 64 bytes are reserved for EP0-OUT TX FIFO, so the RAM usage after initialization is now 1088 bytes (192 bytes free) instead of 708 (576 bytes free).

The `testusb` sample seems to create three endpoints that require FIFO allocation: two with `mps=64`, one with `mps=0`. Combine this with the mysterious line[1]:
https://github.com/zephyrproject-rtos/zephyr/blob/36bc2f38b7e25104cfb70a1d1ab23a4a5ecdb7a4/drivers/usb/udc/udc_stm32.c#L682

This means that `(64 + 64) * 2` = 256 bytes will be request for endpoint TX FIFOs... which is over the new budget of 192 bytes free! And thus, `-ENOMEM` is returned and bubbles up, leading to the sample failing miserably:
```
*** Booting Zephyr OS build v4.2.0-4890-g19f9377b9c1f ***
[00:00:02.480,000] <err> udc_stm32: Unable to allocate FIFO for 0x82
[00:00:02.487,000] <err> usbd_iface: Failed to handle op 1, ep 0x82, bm 0x00020002, -12
[00:00:02.495,000] <err> usbd_ch9: Failed to set configuration 1, -12
[00:00:02.502,000] <err> usbd_core: unrecoverable error -12, ep 0x00, buf 0x2000cef8
```

[1] I suspect the "mysterious line" is here to increase TX FIFO sizes as recommended in RefMan: "More space allocated in the transmit IN endpoint FIFO results in better performance on the
USB"

----- 

I will modify the driver to implement similar logic to the DWC2 driver:
* take an hardcoded baseline value (I'll keep the historic 160 words)
* add a small quantity based on endpoint count (as per RefMan)
* limit to a certain percentage of the USB SRAM (previously, we appeared to use ~55% so limiting to half sounds acceptable)

**Comment by mathieuchopstm** [comment]
Went for a different solution which allows tweaking RxFIFO size via Kconfig. This is acceptable for now since the driver is single-instance anyways, and more flexible than hardcoding a value in the driver.

Testing will be done at a later time to confirm no regression is observed...

**Comment by everedero** [comment]
I tested it on the apex_pro_mini / stm32l412 target and it works! :partying_face:. The exact test being: checking that lsusb gives me a "NordicSemiconductor Zephyr testusb sample", and also verifying that the testusb enumeration disappears when I disconnect the device.

**Comment by mathieuchopstm** [comment]
With the usual cherry-pick from 94001, I see one regression compared to https://github.com/zephyrproject-rtos/zephyr/pull/96028#issuecomment-3339349890: test 13 no longer passes on `nucleo_l552ze_q` (error 22, `verify_not_halted failed status -110` as usual)

This is surprising given that the board uses the ST USB IP which (should!) see 0 functional change (it isn't affected by the `RxFIFO` stuff). I'll try to see if error is present in `main`, but either way this is a non-issue to me since test 13 also fails on all boards in HS mode regardless.

Note: I did not re-test N6 since it should be almost identical to U5A5 (same IP, only PHY differs).

**Comment by tmon-nordic** [comment]
> Went for a different solution which allows tweaking RxFIFO size via Kconfig. This is acceptable for now since the driver is single-instance anyways, and more flexible than hardcoding a value in the driver.

This approach is essentially similar to what is proposed in #96206. The underlying issue is the same (need to divide memory between endpoints), and the easiest approach is to come with some sensible default and just let the user decide.

**Comment by mathieuchopstm** [comment]
> With the usual cherry-pick from 94001, I see one regression compared to [#96028 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/96028#issuecomment-3339349890): test 13 no longer passes on `nucleo_l552ze_q` (error 22, `verify_not_halted failed status -110` as usual)
> 
> This is surprising given that the board uses the ST USB IP which (should!) see 0 functional change (it isn't affected by the `RxFIFO` stuff). I'll try to see if error is present in `main`, but either way this is a non-issue to me since test 13 also fails on all boards in HS mode regardless.
> 
> Note: I did not re-test N6 since it should be almost identical to U5A5 (same IP, only PHY differs).

I also see the test 13 failure on `nucleo_l552ze_q` without these commits; something else on `main` must be causing the failures...

:arrow_right: **PR does not bring a regression** :arrow_right: OK to merge as-is

<details><summary>test details</summary>

```
$ git log --oneline
4ad0abc1578 (HEAD -> TMP__usb) [TMP] EP size patch
7eb0909f999 drivers: usb: stm32: Fix data out on control ep
0520dfe8ff9 (upstream/main, upstream/HEAD) Bluetooth: Tester: Fixed read_multiple_var
eb931d425f9 kernel/Kconfig.init: update description of SOC_RESET_HOOK
418eed0f907 arch/arm: introduce the pre-stack/RAM init hook
3d12e18b40a tests: arch: arm: irq_vector_table: don't printk from ISRs
$ ^-- cherry picked commit from #94001

$ git diff HEAD~1..HEAD
diff --git a/drivers/usb/udc/udc_stm32.c b/drivers/usb/udc/udc_stm32.c
index 7b831086c3f..f03f94350f3 100644
--- a/drivers/usb/udc/udc_stm32.c
+++ b/drivers/usb/udc/udc_stm32.c
@@ -1128,7 +1128,7 @@ static const struct udc_api udc_stm32_api = {
 
 #if defined(USB) || defined(USB_DRD_FS)
 #define EP0_MPS 64U
-#define EP_MPS 64U
+#define EP_MPS 512U
 #define USB_BTABLE_SIZE  (8 * USB_NUM_BIDIR_ENDPOINTS)
 #define USB_RAM_SIZE   DT_INST_PROP(0, ram_size)
 #else /* USB_OTG_FS */
$ ^-- mini patch to allow testusb sample to run

$ west build -b nucleo_l552ze_q samples/subsys/usb/testusb -DCONFIG_LOG_MODE_IMMEDIATE=y -DCONFIG_UDC_BUF_POOL_SIZE=16384 -DCONFIG_UDC_STM32_STACK_SIZE=16384 -DCONFIG_USBD_THREAD_STACK_SIZE=8192 -DCONFIG_ISR_STACK_SIZE=4096 -DCONFIG_HW_STACK_PROTECTION=y && west flash

$ sudo testusb -v 512 -D /dev/bus/usb/003/038 -t 13
./testusb: /dev/bus/usb/003/038 may see only control tests
full speed	/dev/bus/usb/003/038	0
running test 13
/dev/bus/usb/003/038 test 13 --> 22 (error 22)

$ sudo dmesg
[100468.649723] usbtest 3-5.3.1:1.0: TEST 13:  set/clear 1000 halts
[100478.657559] usb 3-5.3.1: verify_not_halted failed, iterations left 0, status -110 (not 0)
[100478.657568] usbtest 3-5.3.1:1.0: halts failed, iterations left 999
```

</details>

> This approach is essentially similar to what is proposed in #96206. The underlying issue is the same (need to divide memory between endpoints), and the easiest approach is to come with some sensible default and just let the user decide.

Interesting reference. There is some similarity but this seems to be a slightly different issue: issue author's instance has fixed FIFO sizes (and so their proposal describes HW parameters) whereas ST's instances have configurable FIFOs (and so our DT would be _configuration_ parameters). To be clear, I'm not against such a solution though :slightly_smiling_face:

The default for now is the historic value of 160 words(ish), though we could use Kconfig preprocessor to automatically compute e.g. `default /* 50% of zephyr_udc0 ram-size */`. (I didn't do it to minimize changes)

**Comment by tmon-nordic** [comment]
> > This approach is essentially similar to what is proposed in #96206. The underlying issue is the same (need to divide memory between endpoints), and the easiest approach is to come with some sensible default and just let the user decide.
> 
> Interesting reference. There is some similarity but this seems to be a slightly different issue: issue author's instance has fixed FIFO sizes (and so their proposal describes HW parameters) whereas ST's instances have configurable FIFOs (and so our DT would be _configuration_ parameters). To be clear, I'm not against such a solution though 🙂

The FIFO in the referenced issue are also configurable, but not freely (both starting address and maximum length of TxFIFO is capped differently based on TxFIFO number). If the fifos were not dynamically configurable then describing the sizes in devicetree wouldn't be much useful. The whole idea behind configuring the fifo sizes at compile time is to avoid the problem of doing it dynamic at runtime (which is not trivial when there are multiple interfaces with alternate settings).

**Comment by mathieuchopstm** [comment]
Addressed comments from @etienne-lms.

**Review by etienne-lms — APPROVED** [review]
Looks consistent to me.

**Review by erwango — APPROVED** [review]
