### PR TITLE
drivers: video: ov5640: add support to QVGA and QQVGA in CSI mode

### LINKED ISSUE #86519: video: ov5640 support for vga , qvga and qqvga not there
**Describe the bug**

The current driver for 0v5640 does not support vga , qvga or qqvga resolutions

**Impact**
The ov5640 camera supports the above mentioned resolutions but the driver does not support so using this driver with microcontrollers which have ram lesser than 614.4kB in its current state is not possible

**Environment (please complete the following information):**

 - Windows 11
 - Zephyr SDK release version 4.0

### PR DESCRIPTION
**Pull request by caiohbm**
The ov5640 driver already supports QVGA and QQVGA in dvp mode but not in csi mode. This PR adds support for these resolutions in csi mode.

### CODE REVIEW

File: drivers/video/ov5640.c [hunk 1]
```diff
@@ -486,12 +500,36 @@ static const struct ov5640_mipi_frmrate_config mipi_hd_frmrate_params[] = {
 static const struct ov5640_mipi_frmrate_config mipi_vga_frmrate_params[] = {
 	{15, 0x22, 0x38, 24000000}, {30, 0x14, 0x38, 24000000}, {60, 0x14, 0x70, 48000000}};
 
+static const struct ov5640_mipi_frmrate_config mipi_qvga_frmrate_params[] = {
+	{15, 0x22, 0x30, 24000000}, {30, 0x14, 0x30, 24000000}, {60, 0x14, 0x60, 24000000}};
```
Comment (ngphibang) [inline drivers/video/ov5640.c:504]: Maybe with low resolutions like qvga and qqvga, we can support higher framerate, e.g. 75 fps, 120 fps (with higher pixel clock if needed)

Comment (caiohbm) [reply drivers/video/ov5640.c]: I have tried to tweak the PLL1 and PLL2 control parameters but that didn't quite work out, leading to glitches or simply not working. This fps limitation (beyond 60 fps) is most likely linked to the MIPI CSI 2RX driver, but to properly resolve this issue, a deeper investigation would be required, which we could do in the future.

**Review by ngphibang — APPROVED** [review]

**Review by loicpoulain — APPROVED** [review]
LGTM
