### PR TITLE
net: lib: sntp: Fix transmit timestamp

### LINKED ISSUE #97632: SNTP client request uses wrong timestamp
### Describe the bug

When using the sntp client the transmit timestamp is filled with the elapsed time from booting.
Instead the system time should be sent via sntp.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Run the [sample sntp client](https://docs.zephyrproject.org/latest/samples/net/sockets/sntp_client/README.html).
Log the network traffic and look at the Transmit Timestamp.
The raw value are elapsed seconds from booting. A calculated value can be something like 7th Febuary 2036.

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

Ubuntu 24.04.3 LTS
Zephyr SDK 0.17.1
Zephyr 4.2.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rlubos**
Fix the transmit timestamp value sent in SNTP queries:

 * Use sys clock as a time source instead of the uptime,
 * As NTP epoch is different from Unix epoch (starts in 1900), adjust the seconds value with appropriate offset,
 * Finally, adjust the fraction calculation to the nanoseconds value from struct timespec. Do the math in 64-bit to avoid overflows and do the division at the end for more accurate results.

Fixes #97632

### CODE REVIEW

File: subsys/net/lib/sntp/sntp.c [hunk 1]
```diff
@@ -185,15 +186,21 @@ int sntp_init(struct sntp_ctx *ctx, struct sockaddr *addr, socklen_t addr_len)
...
+	}
 
 	/* prepare request pkt */
 	tx_pkt.li = 0;
 	tx_pkt.vn = SNTP_VERSION_NUMBER;
 	tx_pkt.mode = SNTP_MODE_CLIENT;
-	ts_us = k_ticks_to_us_near64(k_uptime_ticks());
-	ctx->expected_orig_ts.seconds = ts_us / USEC_PER_SEC;
-	ctx->expected_orig_ts.fraction = (ts_us % USEC_PER_SEC) * (UINT32_MAX / USEC_PER_SEC);
+	ctx->expected_orig_ts.seconds = ts.tv_sec + OFFSET_1970_JAN_1;
```
Comment (lgreine) [inline subsys/net/lib/sntp/sntp.c]: What happens when we hit February 7, 2036?
At that point, the NTP epoch rolls over, and the seconds counter should be reset.

Comment (rlubos) [reply subsys/net/lib/sntp/sntp.c]: As the seconds value encoded in the packet is 32-bit, it'd just overflow and it starts counting from 0 again. However there seems to be an issue here with the fact that the `expected_orig_ts.seconds` type is 64-bit (which won't overflow), because of this the response is rejected due to this check:
https://github.com/zephyrproject-rtos/zephyr/blob/bcc4689cd01620c1a5408986085343e656ec5a71/subsys/net/lib/sntp/sntp.c#L69-L75
Not sure why is it 64-bit, but it seems we need to handle overflow when storing the TX timestamp in `expected_orig_ts.seconds`, a simple cast to uint32_t seems to do the job, I'll update the PR.

Thanks for bringing this to attention

**Review by pdgendt — APPROVED** [review]

File: subsys/net/lib/sntp/sntp.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/lib/sntp/sntp.c]: Seems to work fine now, I've manually initialized the sys clock just before the rollover and sent queries every second, the packet just before:
image
And after:
image
And the response is accepted just fine.

**Review by jukkar — APPROVED** [review]

File: subsys/net/lib/sntp/sntp.c (hunk 1 above)
Comment (lgreine) [reply subsys/net/lib/sntp/sntp.c]: My test is working now as well. Thank you for your support.

**Review by maass-hamburg — APPROVED** [review]
