### PR TITLE
Bluetooth: controller: Fix accept scan en/disable if already en/disabled

### LINKED ISSUE #31019: Bluetooth: Mesh: Thread competition leads to failure to open or close the scanning.
**Describe the bug**
Bluetooth Mesh unable to start scanning or disable scanning, as a result, the provisioning procedure failed.

Use NRF52DK as Controller attach to Linux OS, Run Zephyr Bluetooth Host on Qemu.

**To Reproduce**
`/* Controller */`
1. west build -b nrf52dk_nrf52832 zephyr/samples/bluetooth/hci_uart/
2. west flash
3. sudo btattach -B /dev/ttyACM1 -S 115200 -R and Expecting Manufacturer: 1521.
4. sudo btproxy -u -z -i 1

`/* Host */`
1. west build -b qemu_cortex_m3 zephyr/tests/bluetooth/tester/
2. west build -t menuconfig -> enable console to uart print, enable logging, enable mesh debug and disable pb-gatt & proxy.
``` C
	struct bt_le_scan_param scan_param = {
			.type       = BT_HCI_LE_SCAN_PASSIVE,
			.filter_dup = BT_LE_SCAN_OPT_NONE,
			.interval   = MESH_SCAN_INTERVAL,
			.window     = MESH_SCAN_WINDOW };
	int err;

	BT_INFO("");
```
3. I adjusted the scanned log in the adv.c file in the mesh directory from DEBUG to INFO
4. west build

`/* auto-pts */`
1. ./autoptsclient-zephyr.py "PATH\NAME.pqw6" ~/zephyrproject/build/zephyr/zephyr.elf -i 192.168.120.1 -l 192.168.109.133 -c MESH/NODE/PROV/BV-12-C

**Logs and console output**
Attachment has been submitted, see iut-zephyr.zip
[iut-zephyr.zip](https://github.com/zephyrproject-rtos/zephyr/files/5746104/iut-zephyr.zip)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used : zephyr-v2.4.0-1367-g7d16ab50d738

**Additional context**
Add any other context about the problem here. relate or similar to #30808

### PR DESCRIPTION
**Pull request by cvinayak**
Conform to Bluetooth Specification, if the LE_Scan_Enable
parameter is set to 0x01 and scanning is already enabled,
any change to the Filter_Duplicates setting shall take
effect. Disabling scanning when it is disabled has no
effect.

Fixes #31019.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

File: subsys/bluetooth/controller/hci/hci.c [hunk 1]
```diff
@@ -1502,6 +1502,11 @@ static void le_set_scan_enable(struct net_buf *buf, struct net_buf **evt)
 	status = ll_scan_enable(cmd->enable);
 #endif /* !CONFIG_BT_CTLR_ADV_EXT */
 
+	if (!IS_ENABLED(CONFIG_BT_CTLR_SCAN_ENABLE_STRICT) &&
+	    (status == BT_HCI_ERR_CMD_DISALLOWED)) {
```
Comment (jhedberg) [inline subsys/bluetooth/controller/hci/hci.c:1506]: Is it certain that the only reason `ll_scan_enable()` might return CMD_DISALLOWED is that the current state was already what was requested as the target state?

Comment (cvinayak) [reply subsys/bluetooth/controller/hci/hci.c:1506]: yes. By implementation, Command Disallowed is only returned for failure to start/stop and already started/stopped scanning state. Only other error code returned by ll_scan_enable function is Invalid HCI Command Parameters.

**Review by jhedberg — APPROVED** [review]
