### PR TITLE
net: lwm2m: firmware_pull: fix multiple last_block notifications

### LINKED ISSUE #16158: LwM2M: Fix incorrect last_block handling in the firmware write callback
At least using a coap to http proxy (I never manager to trigger the callback otherwise) the _last_block_ parameter provided though the callback function (implemented through _firmware_block_received_cb_ in the LWM2M client example) is never set to true although the firmware is fully downloaded. 

**To Reproduce**
- Build and run a firmware distribution point along with the Leshan demo server using _docker-compose_ (adjust the host-side directory of the volume mounted on /usr/share/nginx/html):
```bash
version: '3'

services:
  cf-proxy-coap-http:
    image: linarotechnologies/cf-proxy-coap-http:latest
    container_name: coap-proxy
    restart: unless-stopped
    ports:
      - "5682:5682/udp"
  nginx:
    image: opensourcefoundries/nginx:latest
    container_name: firmware-server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /home/admin-local/data:/usr/share/nginx/html
  leshan-server:
    image: linarotechnologies/leshan:latest
    read_only: true
    container_name: leshan
    restart: unless-stopped
    ports:
      - "5683:5683/udp"
      - "5684:5684/udp"
      - "8081:8080"
    tmpfs:
      - /tmp
```
- Add support for firmware pull using COAP proxy to the LWM2M client example:
```C
CONFIG_LWM2M_FIRMWARE_UPDATE_PULL_SUPPORT=y
CONFIG_LWM2M_FIRMWARE_UPDATE_OBJ_SUPPORT=y
CONFIG_LWM2M_FIRMWARE_UPDATE_PULL_COAP_PROXY_SUPPORT=y
CONFIG_LWM2M_FIRMWARE_UPDATE_PULL_COAP_PROXY_ADDR="coap://FIRMWARE_IP_ADDRESS:5682"
CONFIG_LWM2M_COAP_BLOCK_SIZE=1024
```
and monitor _last_block_.

- Place a file named _update.bin_ in the directory mounted on _/usr/share/nginx/html_ (see docker-compose configuration above) and write _http://FIRMWARE_IP_ADDRESS:8080/update.bin_ to _/5/0/1_ (_Firmware Update/Instance 0/Package URI_)

The download should go fine but _last_block_ is never set to to true.

### PR DESCRIPTION
**Pull request by mike-scott**
When the firmware_pull mechansim sends the callback to notify the
sample of a new firmware block, the user supplied buffer can be
smaller than the CoAP BLOCK_SIZE setting.  To handle this case,
we loop through the payload and fill the user supplied buffer with
smaller chunks.

Unfortunately, the last_block calculation is done outside this loop
which causes several callbacks (while in this loop) to have
last_block true.   Let's fix this by adding a small check to make
sure we're at the end of the current payload block before notifying
the user of a last_block.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/16158

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

File: subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c [hunk 1]
```diff
@@ -336,7 +336,8 @@ do_firmware_transfer_reply_cb(const struct coap_packet *response,
 				}
 
 				ret = write_cb(0, 0, 0,
-					       write_buf, len, last_block,
+					       write_buf, len,
+					       last_block && payload_len == 0U,
```
Comment (ioannisg) [inline subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c]: @mike-scott can you add brackets around the == expression?

**Comment by mike-scott** [comment]
@ioannisg updated the patch.  Here's the diff:
```
diff --git a/subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c b/subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c
index a779dfde59..75029ab1f8 100644
--- a/subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c
+++ b/subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c
@@ -337,7 +337,8 @@ do_firmware_transfer_reply_cb(const struct coap_packet *response,
 
                                ret = write_cb(0, 0, 0,
                                               write_buf, len,
-                                              last_block && payload_len == 0U,
+                                              last_block &&
+                                                       (payload_len == 0U),
                                               firmware_block_ctx.total_size);
                                if (ret < 0) {
                                        goto error;
```

**Review by MaureenHelm — APPROVED** [review]
