### PR TITLE
console: uart_mux: uart_mux_send to return number of bytes sent

### LINKED ISSUE #48470: Inconsistent return value of uart_mux_fifo_fill when called inside/outside of an ISR
**Describe the bug**
Calling uart_fifo_fill on a GSM Mux UART device results in inconsistent return values, dependent on whether the function is called from an ISR or outside of it.

According to documentation uart_fifo_fill should return the number of bytes sent. This happens correctly when called on a UART Mux outside of an ISR. If called inside of an ISR, uart_mux_fifo_fill calls gsm_dlci_send which returns 0 on success, as opposed to number of bytes sent. 

**To Reproduce**

1. Allocate muxing UART device
2. Attach the muxing UART to a real UART device
3. Call uart_fifo_fill outside of an ISR to send data
4. The function will now return 0 on success, instead of number of bytes sent

**Expected behavior**
uart_fifo_fill should return the number of bytes sent according to documentation.

**Impact**
Low impact

**Environment (please complete the following information):**
OS: MacOS
Commit 0a904d0c176acf67ab10285e42f4d1924bc5bb79 tag: v3.0.99-ncs1

### PR DESCRIPTION
**Pull request by dcpleung**
This changes the return value of uart_mux_send() to return
how many bytes sent instead of simply zero for any bytes sent.
This would make it consistent with other UART send commands where
they return number of bytes sent.

Fixes #48470

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

File: drivers/console/uart_mux.c [hunk 1]
```diff
@@ -812,7 +812,7 @@ int uart_mux_send(const struct device *uart, const uint8_t *buf, size_t size)
 
 	k_mutex_unlock(&dev_data->real_uart->lock);
 
-	return 0;
+	return size;
```
Comment (stephanosio) [inline drivers/console/uart_mux.c:815]: but this will always return zero because of `while (--size)` above

**Review by stephanosio — CHANGES_REQUESTED** [review]

File: drivers/console/uart_mux.c (hunk 1 above)
Comment (dcpleung) [reply drivers/console/uart_mux.c:816]: err.. sorry... didn't have enough caffeine in my brain. fixed.

**Review by stephanosio — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
