### PR TITLE
Bluetooth: CAP: Add support for doing just disable for unicast stop

### LINKED ISSUE #70818: LE Audio: Invalid behavior bt_cap_initiator_unicast_audio_stop for some remote devices
**Describe the bug**
`bt_cap_initiator_unicast_audio_stop` has been implemented to release a stream, and when the stream goes into the idle or codec configured state (as per ASCS) then the next stream is released. 

Several remote platforms does not allow fully releasing a stream that still connected to a CIS, such as the case where 2 streams (sink and source) share a single ASE. This behavior is based on the following test from BAP:

> The Unicast Client should not initiate the Release operation for an ASE that is in the Enabling state or the Streaming state if the CIS_ID and CIG_ID parameters are identical to other ASEs exposed by the Unicast Server that are in the Enabling state or the Streaming state; the Unicast Client should instead disable the ASE.

And the text

> The Unicast Client shall terminate any CIS established for that ASE by following the Connected
Isochronous Stream Terminate procedure defined in Volume 3, Part C, Section 9.3.15 in [1], when the
Unicast Client has determined that the ASE is in the Releasing state.

So by the BAP spec, it's clearly hinted (and somewhat required) that the CIS is terminated as part of releasing a stream, which is not what we do when we release streams as part of `bt_cap_initiator_unicast_audio_stop`. 

The CAP spec allows the initiator to use either disable or release for the unicast audio stop procedure: 

> An Initiator shall execute the BAP Unicast ASE Control operation - Disabling an ASE (see Section 5.6.5 in [2]) or the BAP Unicast ASE Control operation - Releasing an ASE (see Section 5.6.6 in [2]) on all ASEs in the use case in the Enabling or Streaming state.

So the issue may be fixed by simply using `disable` instead of `release`. This would also fix another issue which is that once a stream goes from e.g. enabling -> codec configured, then it cannot go back into QoS Configured, as the BAP spec requires all streams in the CIG to be QoS Configured at the same time, which is not possible if one is in the e.g. streaming state and the other in the Codec Configured state. 

**To Reproduce**
Cannot be locally produced in Zephyr as we allow it (unless rejected by the application). 
Information about the products that does not allow it cannot be disclosed either, as this was found during a Bluetooth SIG UPF event. 

**Expected behavior**
The `bt_cap_initiator_unicast_audio_stop` should use the `disable` operation instead of the `release`. We then either need to add an additional `bt_cap_initiator_unicast_audio_release` to allow for releasing streams that do not have a CIS, or do `release` after `disable` for streams that can be released. This could be part of the `stop` parameters so it can be controlled by the application. 

In the end the result should be that we never attempt to release a stream that will end up in the `releasing` state because the CIS cannot be disconnected. 

The `bt_cap_initiator_unicast_audio_start` also need to be updated to support streams in other states, such as QoS Configured (the resulting state of `disable`) so it's possible to do `bt_cap_initiator_unicast_audio_start` after a `bt_cap_initiator_unicast_audio_stop`.

**Impact**
It can be worked around by the application by using the BAP API, but that is less than ideal, and from a CAP perspective this is can be a showstopper. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 98aa10d6eab8df6938c0dc949bd12bc244bb52e1

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
The unicast_stop function is changed to primarily do a
BAP disable instead of a release, with optional
support for releasing the streams once they have been disabled.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/70818

### CODE REVIEW

File: subsys/bluetooth/audio/cap_initiator.c [hunk 1]
```diff
@@ -1692,34 +1748,259 @@ int bt_cap_initiator_unicast_audio_stop(const struct bt_cap_unicast_audio_stop_p
...
+		if (can_stop_stream(bap_stream)) {
+			can_disable = true;
+		}
 
+		if (param->release && can_release_stream(bap_stream)) {
+			can_release = true;
+		}
+	}
+
+	if (!can_disable && !can_stop && !can_release) {
```
Comment (fredrikdanebjer) [inline subsys/bluetooth/audio/cap_initiator.c:1772]: Does -EALREADY make sense here?

The GNU spec. states it as:
'EALREADY
The socket socket is non-blocking and already has a pending connection in progress (see EINPROGRESS above).'

And while its true that we "already has a pending connection in progress", I think the intent of the wording is when we try to connect a new one.

Could EBUSY make more sense here?

Comment (Thalley) [reply subsys/bluetooth/audio/cap_initiator.c:1772]: The case is here is that all streams are already stopped, and thus `-EBUSY` doesn't make any sense. 

The alternative is that we return `0`, but then it's hard for an application to determine whether a request was successfully sent, or if nothing was done. 

We need a way to tell the caller that no request was sent because it would not result in any state changes

Comment (fredrikdanebjer) [reply subsys/bluetooth/audio/cap_initiator.c:1772]: I guess this make sense. In regardless, I certainly think '0' would be wrong here :D

File: tests/bluetooth/audio/cap_initiator/uut/bap_unicast_client.c [hunk 2]
```diff
@@ -184,18 +184,105 @@ int bt_bap_unicast_client_start(struct bt_bap_stream *stream)
...
+
 	return 0;
 }
 
 int bt_bap_unicast_client_stop(struct bt_bap_stream *stream)
 {
-	zassert_unreachable("Unexpected call to '%s()' occurred", __func__);
+	printk("%s %p\n", __func__, stream);
+
+	/* As per the ASCS spec, only source streams can be started by the client */
```
Comment (fredrikdanebjer) [inline tests/bluetooth/audio/cap_initiator/uut/bap_unicast_client.c:236]: I think you mean `stopped by the client`

**Review by fredrikdanebjer — DISMISSED** [review]

**Review by kruithofa — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/cap_initiator.c [hunk 3]
```diff
@@ -1692,34 +1748,259 @@ int bt_cap_initiator_unicast_audio_stop(const struct bt_cap_unicast_audio_stop_p
...
+		bt_cap_stream_ops_register_bap(cap_stream);
 
 		active_proc->proc_param.initiator[i].stream = cap_stream;
-	}
+		active_proc->proc_param.initiator[i].stop.release = param->release;
 
-	bt_cap_common_start_proc(BT_CAP_COMMON_PROC_TYPE_STOP, param->count);
+		if (can_disable_stream(bap_stream)) {
+			can_disable = true;
+		}
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/audio/cap_initiator.c:1761]: Looking at the code again it's because it's in a loop. 

If any stream can be disabled/stopped/released we set the variable. Doing `can_disable = can_disable_stream(bap_stream);` would set the value based on the last stream we iterate on.

File: subsys/bluetooth/audio/cap_initiator.c [hunk 4]
```diff
@@ -1692,34 +1748,259 @@ int bt_cap_initiator_unicast_audio_stop(const struct bt_cap_unicast_audio_stop_p
...
+
+		/* Ensure that ops are registered before any procedures are started */
+		bt_cap_stream_ops_register_bap(cap_stream);
 
 		active_proc->proc_param.initiator[i].stream = cap_stream;
-	}
+		active_proc->proc_param.initiator[i].stop.release = param->release;
 
-	bt_cap_common_start_proc(BT_CAP_COMMON_PROC_TYPE_STOP, param->count);
+		if (!can_disable && can_disable_stream(bap_stream)) {
```
Comment (kruithofa) [inline subsys/bluetooth/audio/cap_initiator.c:1759]: Somehow missing the link to my original comment. Anyway good point that this is in a loop.
It still could be rewritten as

'''
 can_disable = can_disable || can_disable_stream(bap_stream);
'''

which still would do the short circuiting, but I am not sure if that's more readable than what you have now

**Review by kruithofa — APPROVED** [review]

**Review by fredrikdanebjer — APPROVED** [review]

File: subsys/bluetooth/audio/cap_initiator.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/audio/cap_initiator.c:1759]: Hmm, I think the current version is more explicit. Not sure if there's any performance changes between the two, but I think `can_disable = can_disable || can_disable_stream(bap_stream)` might be worth as it always does 1 assign and 1 compare, whereas the current version always do 1 comparison and optionally an assign.

**Comment by Thalley** [comment]
Investigating a possible issue

**Comment by Thalley** [comment]
> Investigating a possible issue

There is indeed an issue, but it's not caused by this PR nor easily fixable by this PR, and will be fixed in https://github.com/zephyrproject-rtos/zephyr/pull/79014
