### PR TITLE
net: if: Add IPv4 support to multicast monitor

### LINKED ISSUE #26585: IPv4 multicast datagrams can't be received for mimxrt1064_evk board (missing ethernet API)
**Describe the bug**
IPv4 multicast datagrams can't be received for mimxrt1064_evk board (missing ethernet API).
In order to support IPv4 multicast datagrams, it is necessary to modify the mimxrt1064_evk ethernet driver API to join a multicast group.
For mimxrt1064, it is the file eth_mcux.c, which could provide the configuration function set_config to add or remove a multicast source adress filter to the interface.

1) Open the file $ ZEPHYR_BASE / zephyr / drivers / ethernet / eth_mcux.c
2) the following static function could be defined

```
static int set_config (struct device * dev,
                           enum ethernet_config_type type,
                           const struct ethernet_config * config)
{
    int result = -1;
    switch (type)
    {
    ETHERNET_CONFIG_TYPE_FILTER box:
    {
        switch (config-> filter.type)
        {
        ETHERNET_FILTER_TYPE_SRC_MAC_ADDRESS box:
        {
            / * Adds or leaves the ENET device to a multicast group. * /
            uint8_t multicastMacAddr [6];
            for (uint32_t i = 0; i <6; i ++)
            {
                multicastMacAddr [i] = config-> filter.mac_address.addr [i];
                if (config-> filter.set)
                {
                    printk ("\ r \ nENET_AddMulticastGroup \ r \ n");
                    ENET_AddMulticastGroup (ENET, multicastMacAddr);
                }
                else
                {
                    printk ("\ r \ nENET_LeaveMulticastGroup \ r \ n");
                    ENET_LeaveMulticastGroup (ENET, multicastMacAddr);
                }
                result = 0;
            }
        }
        break;
        default:
        {
            // Nothing
        }
        break;
        }
        break;
        default:
        {
            // Nothing
        }
        break;
    }
    }
    return result;
}
```
3) ... and added to the api by modifying the api_funcs structure:

```
static const struct ethernet_api api_funcs = {
    .iface_api.init = eth_iface_init,
    .get_capabilities = eth_mcux_get_capabilities,
    .send = eth_tx,
    .set_config = set_config, / * Adding the set config function to the API * /
};
```
**To Reproduce**
Try to receive UDP ipv4 multicast datagrams.

**Environment (please complete the following information):**
 - OS: linux
 - Toolchain: zephyr sdk v0.1.13
 - board: mimxrt1064_evk
 - SHA: 979e124e21fb05cfedf8ed12078983d40e2f0b6c

### PR DESCRIPTION
**Pull request by mrfuchs**
Make multicast group join/leave monitor support both IPv6 and IPv4 addresses.

Fixes #26585

Signed-off-by: Markus Fuchs <markus.fuchs@ch.sauter-bc.com>

### CODE REVIEW

File: subsys/net/ip/ipv6_mld.c [hunk 1]
```diff
@@ -201,8 +201,6 @@ int net_ipv6_mld_join(struct net_if *iface, const struct in6_addr *addr)
 
 	net_if_ipv6_maddr_join(maddr);
 
-	net_if_mcast_monitor(iface, addr, true);
```
Comment (jukkar) [inline subsys/net/ip/ipv6_mld.c:204]: Why this change? I think we should start to monitor multicast addresses only when the user wants to join the multicast group, and not when a multicast address is added to the network interface.

**Review by jukkar — COMMENTED** [review]
The `drivers/can/can_net.c` is also using the multicast monitor API, you need to change that too.

File: drivers/ethernet/eth_mcux.c [hunk 2]
```diff
@@ -1029,14 +1029,18 @@ static int eth_init(const struct device *dev)
...
-			    const struct in6_addr *addr,
+			    const struct net_addr *addr,
 			    bool is_joined)
 {
 	const struct device *dev = net_if_get_device(iface);
 	struct eth_context *context = dev->data;
 	struct net_eth_addr mac_addr;
 
-	net_eth_ipv6_mcast_to_mac_addr(addr, &mac_addr);
+	if (addr->family != AF_INET6) {
```
Comment (rlubos) [inline drivers/ethernet/eth_mcux.c:1039]: I'd be good to move the Ethernet driver changes to a separate commit, they don't seem to be cover in the commit message (and are not related to the core IP stack changes).

Comment (mrfuchs) [reply drivers/ethernet/eth_mcux.c:1039]: Done. Thanks!

**Comment by mrfuchs** [comment]
> The `drivers/can/can_net.c` is also using the multicast monitor API, you need to change that too.

I somehow missed that. Thanks for the hint.

File: subsys/net/ip/ipv6_mld.c (hunk 1 above)
Comment (mrfuchs) [reply subsys/net/ip/ipv6_mld.c:204]: I wanted the `net_if_ipv*_maddr_add()` and `net_if_ipv*_maddr_rm()` functions to behave the same way for IPv4 and IPv6 as the mcast monitor is going to be used by Ethernet drivers to adjust their multicast address filters.
However, you are right, the existing behavior should be maintained (not only because it's the _multicast group join/leave monitor_). I reverted this change.

**Review by rlubos — APPROVED** [review]

**Review by alexanderwachter — APPROVED** [review]
CAN part LGTM

File: subsys/net/ip/ipv6_mld.c (hunk 1 above)
Comment (jukkar) [reply subsys/net/ip/ipv6_mld.c:204]: Note that we currently support also IPv4 IGMP (so similar API as for IPv6 MLD). There exists `net_ipv4_igmp_join()` and `net_ipv4_igmp_leave()` functions are you should tweak those for IPv4 support.

**Review by jukkar — CHANGES_REQUESTED** [review]
This is an API change (although very minor and probably does not affect any component outside current drivers), so we should document this in release note.

File: subsys/net/ip/ipv6_mld.c (hunk 1 above)
Comment (mrfuchs) [reply subsys/net/ip/ipv6_mld.c:204]: These functions make use of `net_if_ipv4_maddr_add()` and `net_if_ipv4_maddr_rm()` which now call `net_if_mcast_monitor()`. How should these functions be tweaked?

https://github.com/zephyrproject-rtos/zephyr/blob/8dcfa913d0f2d0675b4427bbc7d14302a9f13903/subsys/net/ip/igmp.c#L264-L275
https://github.com/zephyrproject-rtos/zephyr/blob/8dcfa913d0f2d0675b4427bbc7d14302a9f13903/subsys/net/ip/igmp.c#L294-L304

Comment (jukkar) [reply subsys/net/ip/ipv6_mld.c:204]: You would need to remove the code you added to `net_if_ipv4_maddr_add/rm` and just have something like this
```
diff --git a/subsys/net/ip/igmp.c b/subsys/net/ip/igmp.c
index a36444acab..0398f324ae 100644
--- a/subsys/net/ip/igmp.c
+++ b/subsys/net/ip/igmp.c
@@ -285,6 +285,8 @@ int net_ipv4_igmp_join(struct net_if *iface, const struct in_addr *addr)
 
        net_if_ipv4_maddr_join(maddr);
 
+       net_if_mcast_monitor(iface, addr, true);
+
        net_mgmt_event_notify_with_info(NET_EVENT_IPV4_MCAST_JOIN, iface,
                                        &maddr->address.in_addr,
                                        sizeof(struct in_addr));
@@ -312,6 +314,8 @@ int net_ipv4_igmp_leave(struct net_if *iface, const struct in_addr *addr)
 
        net_if_ipv4_maddr_leave(maddr);
 
+       net_if_mcast_monitor(iface, addr, false);
+
        net_mgmt_event_notify_with_info(NET_EVENT_IPV4_MCAST_LEAVE, iface,
                                        &maddr->address.in_addr,
                                        sizeof(struct in_addr));
```

Comment (mrfuchs) [reply subsys/net/ip/ipv6_mld.c:204]: Got it, but with these changes my patch would implement something different than I had in mind. My intention was to allow Ethernet drivers to fit their multicast filters to the actual requirements (dynamically and at runtime). At the moment, they are either using Kconfig like eth_mcux.c...

https://github.com/zephyrproject-rtos/zephyr/blob/417647f05715cc183df43ffd841e895c03a486ad/drivers/ethernet/eth_mcux.c#L915-L918
https://github.com/zephyrproject-rtos/zephyr/blob/417647f05715cc183df43ffd841e895c03a486ad/drivers/ethernet/eth_mcux.c#L973-L975

... or - even worse - disable the multicast filter completely like eth_stm32_hal.c (cf. ad8f837):

https://github.com/zephyrproject-rtos/zephyr/blob/417647f05715cc183df43ffd841e895c03a486ad/drivers/ethernet/eth_stm32_hal.c#L135-L147

Staying at mDNS as an example, removing my code from `net_if_ipv4_maddr_add()` would make it impossible for the Ethernet driver to use the mcast monitor to adjust its multicast address filter as the mDNS module is calling `net_if_ipv4_maddr_add()` (in case of IPv4 and `net_ipv6_mld_join()` in case of IPv6 - thus my first approach):

https://github.com/zephyrproject-rtos/zephyr/blob/417647f05715cc183df43ffd841e895c03a486ad/subsys/net/lib/dns/mdns_responder.c#L537-L547

As a STM32 and Ethernet stack user struggling with the heavy load that the disabled multicast filters bring, I might better follow the design of the eth_mcux.c driver...

Comment (jukkar) [reply subsys/net/ip/ipv6_mld.c:204]: For the multicast to work properly in all cases, the application needs to join the multicast group, it is not enough just to add the multicast address to the network interface. For mDNS, this probably does not matter too much but it does not harm to join the group in that case too. So it might be needed for the mDNS library to join the group instead of just adding the multicast address to the interface. This would require some code changes in mDNS to make it work properly.

File: drivers/ethernet/eth_mcux.c [hunk 3]
```diff
@@ -1029,14 +1029,18 @@ static int eth_init(const struct device *dev)
 
 #if defined(CONFIG_NET_IPV6)
```
Comment (hakehuang) [inline drivers/ethernet/eth_mcux.c:1030]: looks like in driver level this feature is not enabled for ipv4. see below, and above macro is limited to ipv6
```
static void eth_iface_init(struct net_if *iface)
{
	const struct device *dev = net_if_get_device(iface);
	struct eth_context *context = dev->data;

#if defined(CONFIG_NET_IPV6)
	static struct net_if_mcast_monitor mon;

	net_if_mcast_mon_register(&mon, iface, net_if_mcast_cb);
#endif /* CONFIG_NET_IPV6 */
```

**Review by hakehuang — COMMENTED** [review]
seems not enable ipv4 multicast in driver level, do we plan to do it in another PR?

File: subsys/net/ip/ipv6_mld.c (hunk 1 above)
Comment (mrfuchs) [reply subsys/net/ip/ipv6_mld.c:204]: > You would need to remove the code you added to `net_if_ipv4_maddr_add/rm` and just have something like this [...]

Followed your advice. Thanks.

**Comment by mrfuchs** [comment]
> seems not enable ipv4 multicast in driver level, do we plan to do it in another PR?

Yes, that should be done in other PRs. I'll take care of the STM32 Ethernet driver as that's the hardware I have at hand.

> looks like in driver level this feature is not enabled for ipv4. see below, and above macro is limited to ipv6

As for the drivers that are currently making use of the mcast monitor, I just tried to make sure that their functionality is preserved.

File: drivers/ethernet/eth_mcux.c (hunk 3 above)
Comment (mrfuchs) [reply drivers/ethernet/eth_mcux.c:1030]: As for the drivers that are currently making use of the mcast monitor, I just tried to make sure that their functionality is preserved.

File: subsys/net/ip/ipv6_mld.c (hunk 1 above)
Comment (mrfuchs) [reply subsys/net/ip/ipv6_mld.c:204]: > So it might be needed for the mDNS library to join the group instead of just adding the multicast address to the interface. This would require some code changes in mDNS to make it work properly.

I changed that in an additional commit.

**Comment by mrfuchs** [comment]
> This is an API change (although very minor and probably does not affect any component outside current drivers), so we should document this in release note.

@jukkar, added a short description to the release notes.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by hakehuang — APPROVED** [review]

File: doc/releases/release-notes-2.7.rst [hunk 4]
```diff
@@ -117,6 +117,12 @@ Stable API changes in this release
     structure contains two members: ``handles``, which was moved from
     :c:struct:`bt_gatt_read_params`, and ``variable``.
 
+* Networking
```
Comment (cfriedt) [inline doc/releases/release-notes-2.7.rst:120]: since this has been converted from a bug to an enhancement, does that mean it can no longer go in for v2.7.0 @nashif ?
