### PR TITLE
Bluetooth: L2CAP: Fix inverting of SCID and DCID on disconnect

### LINKED ISSUE #16799: Bluetooth: L2CAP: Interpretation of SCID and DCID in Disconnect is wrong
On the request the spec has the following decription:

• Destination CID - DCID (2 octets)
This field specifies the endpoint of the channel to be disconnected on the
device receiving this request.
• Source CID - SCID (2 octets)
This field specifies the endpoint of the channel to be disconnected on the
device sending this request.

So the DCID should map to rx.cid while the SCID should map to tx.cid.

On the Disconnect Response it is the opposite when receiving:

• Destination CID - DCID (2 octets)
This field identifies the channel endpoint on the device sending the
response.
• Source CID - SCID (2 octets)
This field identifies the channel endpoint on the device receiving the
response.

### PR DESCRIPTION
**Pull request by Vudentz**
For the Request:

DCID shall map to rx.cid:
  'This field specifies the endpoint of the channel to be disconnected
  on the device receiving this request.'

SCID shall map to tx.cid:
  'This field specifies the endpoint of the channel to be disconnected
  on the device sending this request.'

For the response when receiving the roles are inverted.

Fixes #16799

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

File: subsys/bluetooth/host/l2cap.c [hunk 1]
```diff
@@ -913,18 +913,18 @@ static void le_disconn_req(struct bt_l2cap *l2cap, u8_t ident,
...
 	}
 
-	scid = sys_le16_to_cpu(req->scid);
+	dcid = sys_le16_to_cpu(req->dcid);
 
-	BT_DBG("scid 0x%04x dcid 0x%04x", scid, sys_le16_to_cpu(req->dcid));
+	BT_DBG("dcid 0x%04x scid 0x%04x", dcid, sys_le16_to_cpu(req->scid));
 
-	chan = l2cap_remove_tx_cid(conn, scid);
+	chan = l2cap_remove_tx_cid(conn, dcid);
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: I think this particular bug may be because of the function naming. Why is it called `l2cap_remove_tx_cid()` if it's operating on `BT_L2CAP_LE_CHAN(chan)->rx.cid`?

Also, do we have a bug in `le_disconn_rsp()` since it also uses `l2cap_remove_tx_cid()`? The L2CAP spec says this about the disconnect response: "Destination CID - DCID (2 octets)
This field identifies the channel endpoint on the device sending the response." However in our current implementation the association is made between the DCID and rx.cid.

**Review by jhedberg — CHANGES_REQUESTED** [review]
I'm surprised it's taken this long to find this issue, assuming there's an issue. Have you looked at what the Linux L2CAP code does?

File: subsys/bluetooth/host/l2cap.c (hunk 1 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: I fixed the le_disconn_rsp and renamed remove_tx_cid to remove_rx_cid since we are always removing by the local endpoint not the remote one.

I guess we didn't capture this before becuase the cid were the same, but the Linux side does seems to be right and with this changes we have similar logic:

Disconnect request:
https://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git/tree/net/bluetooth/l2cap_core.c#n4320

Disconnect response:
https://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git/tree/net/bluetooth/l2cap_core.c#n4366

File: subsys/bluetooth/host/l2cap.c [hunk 2]
```diff
@@ -1053,18 +1053,18 @@ static void le_disconn_rsp(struct bt_l2cap *l2cap, u8_t ident,
...
-	u16_t dcid;
+	u16_t scid;
 
 	if (buf->len < sizeof(*rsp)) {
 		BT_ERR("Too small LE disconn rsp packet size");
 		return;
 	}
 
-	dcid = sys_le16_to_cpu(rsp->dcid);
+	scid = sys_le16_to_cpu(rsp->dcid);
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: As I said in my earlier comment, rsp->dcid according to the spec is  the channel endpoint on the device sending the response", i.e. since we're *receiving* the response (not sending it) rsp->dcid is the remote endpoint, not the local one. So I think you should be looking up `rsp->scid` and not `rsp->dcid` (the `scid` local variable name is appropriate however).

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/l2cap.c (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: yep, I forgot to change the to rsp->scid.

**Review by jhedberg — APPROVED** [review]

**Review by joerchan — APPROVED** [review]
