### PR TITLE
cpu_load: rename conflicting API

### LINKED ISSUE #97845: multiple and conflicting implementation of cpu_load_get
### Describe the bug

we have two conflicting implementations of cpu_load_get:

```
include/zephyr/cpu_load/cpu_load.h:int cpu_load_get(int cpu_id);
include/zephyr/debug/cpu_load.h:int cpu_load_get(bool reset);
```

The recent one added to support cpu_freq expands hw support and also supports multicore, the original one we had is tied into tracing and very limited in HW support.

### Regression

- [ ] This is a regression.

### Steps to reproduce

git grep cpu_load_get

### Relevant log output

```shell
include/zephyr/cpu_load/cpu_load.h:int cpu_load_get(int cpu_id);
include/zephyr/debug/cpu_load.h:int cpu_load_get(bool reset);
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

We should just have one. My preference is to remove the one under subsys/debug and see how we can enhance the new interface with some of the features that came with the debug variant, i.e. reset and counter support...

### PR DESCRIPTION
**Pull request by nashif**
We have two places defining cpu_load_get() and trying to the same thing,
one is a core kernel feature supported on all architecture, the other is
part of debug, requires tracing and supported only on a subset of
architectures. Both deliver different results and accuracy.

While we figure our how to merge those into one API and with the
advanatges of both, rename the API so there is no confusion about what
is being used.

Fixes #97845

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by JarmouniA — APPROVED** [review]

**Comment by dcpleung** [comment]
migration guide?

**Comment by JarmouniA** [comment]
> migration guide?

API was introduced in this cycle.

**Review by seankyer — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]

File: include/zephyr/sys/cpu_load.h [hunk 1]
```diff
@@ -34,7 +34,7 @@ extern "C" {
  * @retval -errno code in case of failure.
  *
  */
-int cpu_load_get(int cpu_id);
+int cpu_load_metric_get(int cpu_id);
```
Comment (kartben) [inline include/zephyr/sys/cpu_load.h:37]: since we now have namespacing rules, this should start with `sys_...`
https://docs.zephyrproject.org/latest/contribute/style/naming.html#public-symbol-prefixes
