### PR TITLE
sensor: icm42688: Fix broken streaming, add tests and enable in sensor_shell sample.

### LINKED ISSUE #84833: sensor: icm42688: No longer builds and does not provide correct values
**Describe the bug**
The icm42688 no longer builds since the addition of https://github.com/zephyrproject-rtos/zephyr/pull/80189
Furthermore, after you fix that bug the values that come out of the icm42688 are also order of magnitudes wrong.
Lastly the register map is not fully correct.

**To Reproduce**
Build the driver with whatever application you want.

**Expected behavior**
Should build and give correct data.

**Impact**
Doesn't even compile.

**Logs and console output**
```bash
zephyr/drivers/sensor/tdk/icm42688/icm42688_rtio_stream.c:305:61: error: 'err' undeclared (first use in this function)
  305 |                 rtio_iodev_sqe_err(drv_data->streaming_sqe, err);
      |                                                             ^~~           
```

**Environment:**

 - OS: Linux
 - Toolchain Zephyr SDK
 - main

### PR DESCRIPTION
**Pull request by bperseghetti**
This fixes the broken streaming values we were getting from icm42688 in high res and normal modes.

Also adds a test to make sure the values never blow up again by using real hardware (including the vmu_rt1176). 

fixes #84833

### CODE REVIEW

File: drivers/sensor/tdk/icm42688/icm42688_common.c [hunk 1]
```diff
@@ -255,8 +255,11 @@ int icm42688_configure(const struct device *dev, struct icm42688_cfg *cfg)
 		 * temp/accel/gyro en fields in cfg
 		 */
 		uint8_t fifo_cfg1 =
-			FIELD_PREP(BIT_FIFO_TEMP_EN, 1) | FIELD_PREP(BIT_FIFO_GYRO_EN, 1) |
-			FIELD_PREP(BIT_FIFO_ACCEL_EN, 1) | FIELD_PREP(BIT_FIFO_TMST_FSYNC_EN, 1);
+			FIELD_PREP(BIT_FIFO_TEMP_EN, 1) |
+			FIELD_PREP(BIT_FIFO_GYRO_EN, 1) |
+			FIELD_PREP(BIT_FIFO_ACCEL_EN, 1) |
+			FIELD_PREP(BIT_FIFO_TMST_FSYNC_EN, 1) |
+			FIELD_PREP(BIT_FIFO_HIRES_EN, 1);
```
Comment (teburd) [inline drivers/sensor/tdk/icm42688/icm42688_common.c:262]: hires should probably be a config option, would be fine to set this in DT statically imho.

File: drivers/sensor/tdk/icm42688/icm42688_decoder.c [hunk 2]
```diff
@@ -234,81 +234,33 @@ static inline q31_t icm42688_read_temperature_from_packet(const uint8_t *pkt)
...
-			scale = 10486;
-			break;
-		case ICM42688_DT_GYRO_FS_15_625:
-			scale = 20972;
-			break;
-		}
-	}
+	const uint32_t scale[2][2] = {
+		/* low-res,	hi-res */
+		{35744,		8936}, /* gyro */
```
Comment (teburd) [inline drivers/sensor/tdk/icm42688/icm42688_decoder.c:244]: Having the scales precalculated in a table is great, but at least a formula for how these are calculated should be in a comment here

File: drivers/sensor/tdk/icm42688/icm42688_decoder.c [hunk 3]
```diff
@@ -234,81 +234,33 @@ static inline q31_t icm42688_read_temperature_from_packet(const uint8_t *pkt)
...
 	} else {
-		if (value <= -32767) {
-			/* Invalid 16 bit value */
-			return -ENODATA;
-		}
+		signed_value = unsigned_value | (0 - (unsigned_value & BIT(16)));
 	}
 
-	*out = (q31_t)(value * scale / max);
+	*out = (q31_t)(signed_value * scale[is_accel][is_hires]);
```
Comment (teburd) [inline drivers/sensor/tdk/icm42688/icm42688_decoder.c:263]: I like that a lot of the math here comes down to a simple multiply of a constant. That's actually quite nice.

The constants do need to be documented as to how they are calculated though, or better be calculated at compile time by the compiler.

**Review by teburd — COMMENTED** [review]
The test needs a testcase.yaml and likely a fixture assigned to it

File: drivers/sensor/tdk/icm42688/icm42688_decoder.c (hunk 2 above)
Comment (teburd) [reply drivers/sensor/tdk/icm42688/icm42688_decoder.c:244]: Really, I think I think a macro could be useful here for computing a scaling factor

E.g.

SENSOR_Q31_SCALER(sensitivity, shift) is half the battle, e.g. getting the math for most sensor conversions looking like the simple integer multiplier math that it should be, could be done simpler I think in most cases. Better still I love const table here, though sadly C doesn't let us do const math expressions like the following even if the compiler will do it at compile time.

```c
const sensitivity = SENSITIVITIES[drv_cfg->fs];
const shift = SHIFTS[drv_cfg->fs];
const int32_t scaler = (1/sensitivity)*(pow(2,31)/pow(2,shift));
q31_t scaled = sample*scaler;
```

There's also occasionally the unit conversion involved, e.g. converting G to m/s^2 would involve another multiplier of 9.81 m/s^2. But clearly it was wrong here and needed to be rectified.

File: drivers/sensor/tdk/icm42688/icm42688_common.c (hunk 1 above)
Comment (bperseghetti) [reply drivers/sensor/tdk/icm42688/icm42688_common.c:262]: It is now.

**Review by PetervdPerk-NXP — DISMISSED** [review]

**Review by PetervdPerk-NXP — DISMISSED** [review]

**Comment by bperseghetti** [comment]
After this gets merged I plan to open a PR for some more features that we have been using regularly they are in this post-merge branch, and here is what it adds (note I will split it out into better commits). [This is the planned post-merge additions as a compare.](https://github.com/CogniPilot/zephyr/compare/pr-fix-icm42688-stream...CogniPilot:zephyr:pr-post-merge-icm42688-stream-fix?expand=1)

**Review by PetervdPerk-NXP — APPROVED** [review]

**Review by teburd — APPROVED** [review]
Approving as its fixing the driver.

Realistically the scale values are under-documented and specific to a particular predefined accel/gyro scale which isn't quite right. It should be a table of scaling factors dependent on the sensor scale (e.g. 2g, 4g, 16g, etc). It would be great to see this fixed in a follow up.
