### PR TITLE
net: Fix solicited-node multicast group handling for IPv6 address resolution

### LINKED ISSUE #5282: net: IPv6 DAD is incorrect, wouldn't work ("always succeed") on mcast medium like Ethernet
Splitting off https://github.com/zephyrproject-rtos/zephyr/issues/3127.

https://tools.ietf.org/html/rfc4862#section-5.4.2 states:

> Before sending a Neighbor Solicitation, an interface MUST join the
   all-nodes multicast address and the solicited-node multicast address
   of the tentative address.  The former ensures that the node receives
   Neighbor Advertisements from other nodes already using the address;
   the latter ensures that two nodes attempting to use the same address
   simultaneously should detect each other's presence.

Instead, current source joins these mcast groups *after* "successful" DAD: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/ip/net_if.c#L478 . For a true multicasting medium like Ethernet, DAD will always "succeed", because the node simply won't be able to receive any DAD related replies or messages.

### PR DESCRIPTION
**Pull request by pfalcon**
~~~

net: if: Join solicited-node multicast addr for each unicast addr  …
https://tools.ietf.org/html/rfc4862#section-5.4.2 :

"""
Before sending a Neighbor Solicitation, an interface MUST join the
all-nodes multicast address and the solicited-node multicast address
of the tentative address.
"""

So, joining should happen before sending DAD packets, and it should
happen for each unicast address added. This is achieved by joining
from net_if_ipv6_addr_add() call. Note that we already leave
solicited-node group from net_if_ipv6_addr_rm(). In particular, we
leave it if DAD fails (as that function is called in this case).

Fixes #5282.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>
~~~

### CODE REVIEW

**Comment by pfalcon** [comment]
Also includes patch to finally disabled promisc mode on frdm_k64f, so adding @MaureenHelm and @dleach02 to reviewers.

File: subsys/net/ip/net_if.c [hunk 1]
```diff
@@ -707,6 +696,17 @@ struct net_if_addr *net_if_ipv6_addr_add(struct net_if *iface,
 			net_sprint_ipv6_addr(addr),
 			net_addr_type2str(addr_type));
 
+		/* RFC 4862 5.4.2
+		 * "Before sending a Neighbor Solicitation, an interface
+		 * MUST join the all-nodes multicast address and the
+		 * solicited-node multicast address of the tentative address."
+		 */
+		/* The allnodes multicast group is only joined once as
```
Comment (tbursztyka) [inline subsys/net/ip/net_if.c]: you can merge the 2 comments

File: subsys/net/ip/net_if.c [hunk 2]
```diff
@@ -461,17 +461,6 @@ static void dad_timeout(struct k_work *work)
...
-		/* We join the allnodes group from here so that we have
-		 * a link local address defined. If done from ifup(),
-		 * we would only get unspecified address as a source
-		 * address. The allnodes multicast group is only joined
-		 * once in this case as the net_ipv6_mcast_join() checks
-		 * if we have already joined.
-		 */
-		join_mcast_allnodes(iface);
-
-		join_mcast_solicit_node(iface, &ifaddr->address.in6_addr);
```
Comment (tbursztyka) [inline subsys/net/ip/net_if.c]: Sounds fine to me, but maybe you'll need to address the case when DAD is a failure: what to do with the mcast then? (or is it relevant actually).
Before, because it was joining mcast only on success, failure case did not have to handle any of it, but now it's different.

**Review by tbursztyka — CHANGES_REQUESTED** [review]

File: subsys/net/ip/net_if.c (hunk 1 above)
Comment (pfalcon) [reply subsys/net/ip/net_if.c]: In principle yes, but those are two *different* comments, of different levels. To emphasize the difference, it's better to treat them as "annotations". First is normative reference annotation, applying to whole block of code (2 lines). 2nd is behavior-descriptive annotation, applying to just single statement. Merging two doesn't make much sense, and could lead to decreased clarity of plain confusion.

File: subsys/net/ip/net_if.c (hunk 2 above)
Comment (pfalcon) [reply subsys/net/ip/net_if.c]: That's addressed in the commit message:

> This is achieved by joining
from net_if_ipv6_addr_add() call. Note that we already leave
solicited-node group from net_if_ipv6_addr_rm(). In particular, we
leave it if DAD fails (as that function is called in this case).

Comment (tbursztyka) [reply subsys/net/ip/net_if.c]: indeed line 745 yes

File: subsys/net/ip/net_if.c (hunk 1 above)
Comment (tbursztyka) [reply subsys/net/ip/net_if.c]: true

**Review by askawu — APPROVED** [review]

**Comment by pfalcon** [comment]
Now the build passes. @tbursztyka, please re-review.

**Review by tbursztyka — APPROVED** [review]
