### PR TITLE
tests: watchdog: fixed incorrect skip statement

### LINKED ISSUE #101028: tests: tests/drivers/watchdog/wdt_basic_api: frdm_mcxc444/mcxc444: failed: Unknown Error
**Describe the bug**
below case are failed
drivers.watchdog.wdt_basic_test_suite.wdt

test is failed on v4.3.0-2350-gbbff45f1c4cf on frdm_mcxc444/mcxc444
testcase path is tests/drivers/watchdog/wdt_basic_api

2ea83f42c92e12d82db60fe0889bc5496a745eaf fails after enable watchdog in this platform

### Regression

- [ ] This is a regression.

see logs for details

**To Reproduce**
1. 
```
scripts/twister -p frdm_mcxc444/mcxc444  -T tests/drivers/watchdog/wdt_basic_api -s tests/drivers/watchdog/wdt_basic_api
```
or
```
# west twister -p frdm_mcxc444/mcxc444 -T tests/drivers/watchdog/wdt_basic_api --sub-test tests/drivers/watchdog/wdt_basic_api
```
2. See error

```
Unknown Error
```

**Expected behavior**
test pass

**Impact**

**Logs and console output**

```
Running TESTSUITE wdt_basic_test_suite
===================================================================
START - test_wdt
Testcase: test_wdt_no_callback
Waiting to restart MCU


```

**Environment (please complete the following information):**
 - OS: (e.g. Linux ): Linux
 - Toolchain (e.g Zephyr SDK): zephyr
 - Commit SHA or Version used: v4.3.0-2350-gbbff45f1c4cf

### PR DESCRIPTION
**Pull request by yvesll**
Fix #101028
- Remove ztest_test_skip in sub testcase because it will skip all following code in the testcase.
- Print sub testcase name at the case begining.
- Wrap bad window and wait mode test with macros.
- For nxp,cop, need disable it when the testcase ends.

### CODE REVIEW

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c [hunk 1]
```diff
@@ -449,8 +457,7 @@ static int test_wdt_enable_wait_mode(void)
 	err = wdt_setup(wdt, (WDT_OPT_PAUSE_HALTED_BY_DBG | WDT_OPT_PAUSE_IN_SLEEP));
 	if (err < 0) {
 		printk("Watchdog setup error\n");
-		ztest_test_skip();
```
Comment (Holt-Sun) [inline tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:452]: Upgrade return value will cause many test cases run failed.

Comment (yvesll) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:452]: IMO, setup error shall get a fail instead of skip.
The case added in  #94593 seems only for rt1060, cc @hakehuang

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c [hunk 2]
```diff
@@ -70,8 +70,8 @@
 #if DT_NODE_HAS_STATUS_OKAY(DT_ALIAS(watchdog0))
 #define WDT_NODE DT_ALIAS(watchdog0)
 #elif DT_HAS_COMPAT_STATUS_OKAY(st_stm32_window_watchdog)
-#define WDT_NODE DT_INST(0, st_stm32_window_watchdog)
-#define TIMEOUTS 0
+#define WDT_NODE            DT_INST(0, st_stm32_window_watchdog)
+#define TIMEOUTS            0
```
Comment (hakehuang) [inline tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:74]: do not change this

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c [hunk 3]
```diff
@@ -105,41 +105,52 @@
 #define WDT_NODE DT_INST(0, nuvoton_numaker_wwdt)
 #define TIMEOUTS 1
 #elif DT_HAS_COMPAT_STATUS_OKAY(andestech_atcwdt200)
-#define WDT_NODE DT_INST(0, andestech_atcwdt200)
-#define TIMEOUTS 0
+#define WDT_NODE            DT_INST(0, andestech_atcwdt200)
+#define TIMEOUTS            0
```
Comment (hakehuang) [inline tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:109]: same as above

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c [hunk 4]
```diff
@@ -105,41 +105,52 @@
...
 #define WDT_TEST_MAX_WINDOW 200U
 #endif
 #if DT_HAS_COMPAT_STATUS_OKAY(raspberrypi_pico_watchdog)
 #define WDT_TEST_MAX_WINDOW 8000U
-#define TIMEOUTS 0
+#define TIMEOUTS            0
```
Comment (hakehuang) [inline tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:114]: as above

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c [hunk 5]
```diff
@@ -105,41 +105,52 @@
...
 #endif
 #if DT_HAS_COMPAT_STATUS_OKAY(intel_tco_wdt)
-#define TIMEOUTS 0
+#define TIMEOUTS            0
```
Comment (hakehuang) [inline tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:117]: as above

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c [hunk 6]
```diff
@@ -405,28 +416,25 @@ static int test_wdt_bad_window_max(void)
...
 
+#if TEST_WDT_WAIT_MODE
 static int test_wdt_enable_wait_mode(void)
 {
-#ifndef CONFIG_PM
-	TC_PRINT("Testcase: %s\n", __func__);
-	ztest_test_skip();
-	m_state = WDT_TEST_STATE_IDLE;
-	return TC_SKIP;
-#else
```
Comment (hakehuang) [inline tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: why remove this?

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 2 above)
Comment (yvesll) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:74]: It's from `clang-format`, would it cause any issue?

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 1 above)
Comment (hakehuang) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:452]: @yvesll , I do not agree with you on this, please check below wdt_setup
```
 * @brief Set up watchdog instance.
 *
 * This function is used for configuring global watchdog settings that
 * affect all timeouts. It should be called after installing timeouts.
 * After successful return, all installed timeouts are valid and must be
 * serviced periodically by calling wdt_feed().
 *
 * @param dev Watchdog device instance.
 * @param options Configuration options (see @ref WDT_OPT).
 *
 * @retval 0 If successful.
 * @retval -ENOTSUP If any of the set options is not supported.
 * @retval -EBUSY If watchdog instance has been already setup.
 * @retval -errno In case of any other failure.
```
it will return `ENOTSUP`, if it is not supported, so return with skip is the right operation.

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 6 above)
Comment (yvesll) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: `ztest_test_skip()` will immediate end the whole testcase.

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 2 above)
Comment (hakehuang) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:74]: it will make the commit mess with `format`, if you want, you can use another commit to do this.

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 1 above)
Comment (yvesll) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:452]: So, it would be better to return `TC_SKIP` for `ENOTSUP` and `TC_FAIL` for other negative retval.

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 2 above)
Comment (yvesll) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:74]: Yes, it was already in a separate commit https://github.com/zephyrproject-rtos/zephyr/pull/101179/changes/9233bf525ec5fac0e97f6fd39509c472e8dd567f

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 6 above)
Comment (hakehuang) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: do not test this without CONFIG_PM is the purpose. it is not about skip

Comment (yvesll) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: The function was not wrapped before, so if it jumps into this branch, the variables in NOINIT_SECTION will not be updated.

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 1 above)
Comment (hakehuang) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:452]: yes, you can update this way.

File: tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c (hunk 6 above)
Comment (hakehuang) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: what do you mean wrapped? what is the relation with NOINIT_SECTION? we are talking about the CONFIG_PM

Comment (yvesll) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: The statements after `ztest_test_skip` in the testcase will not be performed.

Comment (hakehuang) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: ok, there are two things here. CONFIG_PM need keep, and need remove m_state = WDT_TEST_STATE_IDLE; and return skip, which is no use at all.

Comment (yvesll) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: It was kept. Please see line 147, 421, 507.
m_state will be updated in 
```c
if (m_testcase_index > 4) {
	m_state = WDT_TEST_STATE_IDLE;
}
```

Comment (hakehuang) [reply tests/drivers/watchdog/wdt_basic_api/src/test_wdt.c:416]: the problem is that the case has not effect without CONFIG_PM, it is designed to work with CONFIG_PM

**Review by hakehuang — APPROVED** [review]
regression test pass on v4.3.0-934-gaf04b317e9a7

**Review by Holt-Sun — APPROVED** [review]
