### PR TITLE
Bluetooth: Mesh: Use BT_MESH_SUSPENDED flag in the legacy advertiser thread

### LINKED ISSUE #80910: Bluetooth: Mesh: Legacy advertiser may advertise after stack is suspended before advertiser is finally stopped
**Describe the bug**
When using the legacy advertiser and suspending the stack through `bt_mesh_suspend` function, the first step that mesh does is trying to stop scanner. The Bluetooth host will send an hci command to the controller and sleep waiting for the response. This can wake up the advertiser thread. If there is an advertisement thread in the pool, the mesh will send it. This we would like to avoid.

**To Reproduce**
Fill up the advertising pool and call `bt_mesh_suspend` function. The advertiser will be woken up and will try to send an adv packet.

**Expected behavior**
We should not let the advertiser thread advertise anything as soon as `BT_MESH_SUSPENDED` flag is set.

**Impact**
Failing test in https://github.com/zephyrproject-rtos/zephyr/pull/79931

### PR DESCRIPTION
**Pull request by PavelVPV**
Instead of checking the `enabled` flag, check if BT_MESH_SUSPENDED is set in the legacy advertiser thread. BT_MESH_SUSPENDED is set earlier than advertiser is stopped and will prevent the advertiser send anything earlier.

This PR also replaces `k_sleep` with semaphore before suspending mesh as  k_sleep may not be enough to let advertiser send the message. Instead we should rely on the bt_mesh_send_cb.

This PR fixes mesh suspend tests in #79931 
Fixes #80910

### CODE REVIEW

File: subsys/bluetooth/mesh/adv_legacy.c [hunk 1]
```diff
@@ -234,7 +235,11 @@ void bt_mesh_adv_init(void)
 
 int bt_mesh_adv_enable(void)
 {
-	enabled = true;
+	/* The advertiser thread relies on BT_MESH_SUSPENDED flag. No point in starting the
+	 * advertiser thread if the flag is not set.
+	 */
+	__ASSERT_NO_MSG(ADV_ENABLED);
```
Comment (omkar3141) [inline subsys/bluetooth/mesh/adv_legacy.c:241]: Why assert here (considering asserts can be disabled), may be better to return -EADV?

File: subsys/bluetooth/mesh/adv_legacy.c [hunk 2]
```diff
@@ -243,7 +248,11 @@ int bt_mesh_adv_disable(void)
 {
 	int err;
 
-	enabled = false;
+	/* k_thread_join will sleep forever if BT_MESH_SUSPENDED flag is not set. The advertiser
+	 * thread will exit once the flag is set. The flag is set by the higher layer function. Here
+	 * we need to check that the flag is dropped and ensure that the thread is stopped.
+	 */
+	__ASSERT_NO_MSG(!ADV_ENABLED);
```
Comment (omkar3141) [inline subsys/bluetooth/mesh/adv_legacy.c:255]: This 'ensure' works only when asserts are enabled, otherwise this can cause locking, better to return error code to let higher layer handle it.

File: subsys/bluetooth/mesh/adv_legacy.c (hunk 1 above)
Comment (PavelVPV) [reply subsys/bluetooth/mesh/adv_legacy.c:241]: Why ever use asserts if they can be disabled?

Comment (alxelax) [reply subsys/bluetooth/mesh/adv_legacy.c:241]: I guess the main purpose of assertion in assertion post action that is `weak` in Zephyr and customer is able to implement it on its own purpose. Generally, assertion is changed on hardware reset in final product as the only way for recovering device workability from unknown and unpredictable situation.
https://docs.zephyrproject.org/latest/kernel/services/other/fatal.html

Is this the real place where device requires hardware reset in "fields"? 

It seems @omkar3141 suggestion is more suitable. Since functional prototype returns operation status, it is better to return error code.

File: subsys/bluetooth/mesh/adv_legacy.c [hunk 3]
```diff
@@ -243,7 +248,11 @@ int bt_mesh_adv_disable(void)
 {
 	int err;
```
Comment (alxelax) [inline subsys/bluetooth/mesh/adv_legacy.c:249]: btw. function just ignores returned thread status and always notifies caller about success. Doesn't seem correct.

**Review by alxelax — DISMISSED** [review]

**Review by omkar3141 — DISMISSED** [review]

File: subsys/bluetooth/mesh/adv_legacy.c [hunk 4]
```diff
@@ -35,10 +35,11 @@ LOG_MODULE_REGISTER(bt_mesh_adv_legacy);
 #define ADV_INT_DEFAULT_MS 100
 #define ADV_INT_FAST_MS    20
 
+#define ADV_ENABLED (!atomic_test_bit(bt_mesh.flags, BT_MESH_SUSPENDED))
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/adv_legacy.c:38]: I'd suggest to add an input parameter to this macro (either `bt_mesh` or `bt_mesh.flags`). Without it you get the impression that this macro evaluates to a build-time constant, which is not true.

**Review by alxelax — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
