### PR TITLE
net: tcp: Decouple TCP context from pkt pools

### LINKED ISSUE #95456: Zephyr Netstack buffer leaks
### Describe the bug

Hi,

This issue follows a discussion I had with @jukkar and @jacob-wienecke-nxp in [95276](https://github.com/zephyrproject-rtos/zephyr/discussions/95276).

I have a TCP server application running on Zephyr v4.2-branch. When I overwhelm the server with traffic for some time, I can observe that even after stopping the traffic, the board becomes unresponsive.

The problem I see is that in some cases the Zephyr netstack does not release RX/TX pkts and RX bufs. Once they are consumed, they remain allocated indefinitely.

To reproduce, I created a patch for the TCP echo server sample:
[echo_server.patch](https://github.com/user-attachments/files/22135357/echo_server.patch)

Against that server, I run the following Python stress script:
```
import socket
import multiprocessing as mp
import time
import random
import os

SERVER_IP = "172.18.170.52"   
SERVER_PORT = 4242            
NUM_CLIENTS = 100             
PAYLOAD_SIZE = 512            
HOLD_TIME = 0.2               
LOOPS = 50                   
WORKERS = os.cpu_count() or 4 

def client_task(id):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(2.0)
        s.connect((SERVER_IP, SERVER_PORT))

        # Send a payload (could be garbage)
        payload = bytes([id % 256]) * PAYLOAD_SIZE
        s.sendall(payload)

        time.sleep(HOLD_TIME)

        if random.random() < 0.3:
            s.shutdown(socket.SHUT_RDWR)
        s.close()
    except Exception as e:
        print(f"[Client {id}] exception: {e}")

def run_batch(batch):
    with mp.Pool(processes=WORKERS) as pool:
        ids = [batch * NUM_CLIENTS + i for i in range(NUM_CLIENTS)]
        pool.map(client_task, ids)

if __name__ == "__main__":
    for batch in range(LOOPS):
        print(f"=== Batch {batch+1}/{LOOPS} ===")
        run_batch(batch)
        time.sleep(0.5)
```

When running this script and later stopping it, I see the following logs and memory stats on the Zephyr side:
```

[00:03:03.52,000] <err> main: Failed to accept incoming connection; errno = 113
[00:03:04.103,000] <err> net_tcp: Cannot allocate recv queue for conn 0x20040590
[00:03:04.103,000] <err> net_tcp: net_context_get(): -2
[00:03:04.103,000] <err> net_tcp: Cannot allocate a new TCP connection
...
[00:03:29.541,000] <err> net_tcp: Cannot allocate recv queue for conn 0x20040340
[00:03:29.541,000] <err> net_tcp: net_context_get(): -2
[00:03:29.541,000] <err> net_tcp: Cannot allocate a new TCP connection

uart:~$ net mem
Fragment length 256 bytes
Network buffer pools:
Address         Total   Avail   MaxUsed Name
0x20005000      64      0       -       RX
0x20005038      64      28      -       TX
0x200051ac      160     90      71      RX DATA (rx_bufs)
0x200051e4      160     160     42      TX DATA (tx_bufs)
uart:~$ net allocs
Network memory allocations
```

The bad news is that the available RX packets never get freed, even after the Python stress script stops. This leaves the system unable to accept new connections or recover without a manual power cycle which is very bad.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Apply the patch above:
   git apply echo_server.patch
2. Build the echo server (adjust ip settings accordingly):
   west build -b <board> zephyr/samples/net/sockets/echo_server
3. Run the Python stress script shown above against the board

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

Zephyr SDK 0.17.4
Zephyr v4.2-branch

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rlubos**
Do not allocate net_pkt's for TCP context from the common packet pools. This improves the overall behavior with multiple TCP connections open, as the TCP stack won't consume packets from the common pools, which in extreme could incapacitate the overall TCP stack operation (i.e. when running out of packets).
* For the out-of-order TCP recv queue, net_pkt was not really needed/used as it mostly served as a container for the `net_buf` pointer, therefore use the net_buf pointer directly,
* For the send data queue, preallocate the net_pkt as a part of the TCP context. The TCP cannot work without this packet anyway, so at least this gives explicit information about the TCP stack memory usage. This increases the TCP context size by 64 bytes, but if that's a concern, the TX pkt count can be lowered in exchange.

Fixes #95456

### CODE REVIEW

File: include/zephyr/net/net_pkt.h [hunk 1]
```diff
@@ -2689,6 +2689,13 @@ static inline int net_pkt_acknowledge_data(struct net_pkt *pkt,
 	return net_pkt_skip(pkt, access->size);
 }
 
+/**
+ * Initialize externally allocated TX packet.
+ *
+ * @param pkt The network packet to initialize.
+ */
+void net_pkt_tx_init(struct net_pkt *pkt);
+
```
Comment (jukkar) [inline include/zephyr/net/net_pkt.h]: Should this be internal function (placed to `net_private.h`), I mean there should be no need application calling this one, or is there?

Comment (rlubos) [reply include/zephyr/net/net_pkt.h]: Yeah there's likely no need to expose this function publicly, I will move the declaration.

Comment (rlubos) [reply include/zephyr/net/net_pkt.h]: Done

**Review by jukkar — DISMISSED** [review]

**Comment by carlescufi** [comment]
@ofirshe can you test this PR please?

**Comment by rlubos** [comment]
Rebased the PR to resolve conflict.

**Review by jukkar — APPROVED** [review]

**Comment by ofirshe** [comment]
@rlubos @carlescufi This looks much more stable now, thank you for the PR. I’d love to see it backported.

**Review by pdgendt — APPROVED** [review]
