### PR TITLE
device: refactor to aggregate common dynamic state for devices

### LINKED ISSUE #28873: z_device_ready() lies
#28369 was merged in the late days of 2.4 development to fix a problem where device drivers with incorrect/conflicting dependencies used `device_get_binding()` to identify a driver they depend on before that driver was initialized.  Consequently `z_device_ready()` will succeed for devices that have not yet been initialized.

This really needs to get fixed as there are limited checks that a successfully obtained device pointer remains valid when it's actually  used.

### PR DESCRIPTION
**Pull request by pabigot**
This PR adds a common state structure to devices, and refactors so that this holds not only the device initialization status but also all device power management state.  The refactoring reduces flash usage by changing initialization to allow the kernel to initialize the state without having a per-device backing value in flash.  It increases RAM but some of the increase will go away with device PM refactoring, and there's space in other memory so that new enhancements won't incur an additional cost.

Fixes #28873

### CODE REVIEW

**Comment by pabigot** [comment]
Added to dev-review to introduce this to the community.

**Review by galak — APPROVED** [review]

File: include/device.h [hunk 1]
```diff
@@ -296,6 +296,20 @@ struct device_pm {
...
  */
 struct device_state {
+	/** Non-negative result of initializing the device.
+	 *
+	 * The absolute value returned when the device initialization
+	 * function was invoked, or `UINT8_MAX` if the value exceeds
+	 * an 8-bit integer.  If initialized is also set, a zero value
+	 * indicates initialization succeeded.
+	 */
+	unsigned int init_res : 8;
```
Comment (ceolin) [inline include/device.h:314]: I have the impression that initialization functions in general return a negative value in case of error, and we will end up always with `0` when it succeed or `255` on error  ... That means that use one bit would give the same info, We should probably keep it signed.

Comment (ceolin) [reply include/device.h:314]: nevermind, you invert the signal later

**Review by ceolin — APPROVED** [review]
it looks good for me

**Review by nashif — APPROVED** [review]
