### PR TITLE
drivers: nordic: usb: USBD event handling rework

### LINKED ISSUE #12016: Crash while disconnecting device from USB
**Describe the bug**
Device starts as connected, disconnect it promptly.
```
ASSERTION FAIL [m_drv_state == NRFX_DRV_STATE_POWERED_ON] @ /home/padu/work/fw-nrfconnect-zephyr/ext/hal/nordic/nrfx/drivers/src/nrfx_usbd.c:1865:
```

**To Reproduce**
This is a race. Will add more info in the comment.
Start with the device connected. Just after booting up disconnect the device.

**Expected behavior**
Device must not crash.

**Impact**
Probably showstopper although it is not easy to replicate (so far happened once).

**Screenshots or console output**
Assert above.

**Environment (please complete the following information):**
 rev:{{e21d7cc72d09275bbe3c8baa1e50709e625ca7a0}}
Replicated using older revision but the bug is still there.

### PR DESCRIPTION
**Pull request by pawelzadrozniak**
Some of the events from USBD peripheral (i.e. cable disconnect)
were handled in IRQ context and some of them (i.e. ep r/w events) in
system workqueue (inherited from initial driver implementation).
This may lead to race condition in some specific situations.
Currently, all of the events are enqueued in ISR and processed in
workqueue.

Fixes #12016

Signed-off-by: Paweł Zadrożniak <pawel.zadrozniak@nordicsemi.no>

### CODE REVIEW

File: drivers/usb/device/usb_dc_nrfx.c [hunk 1]
```diff
@@ -68,13 +65,22 @@ enum usbd_periph_state {
...
 };
 
+/**
+ * @brief USBD peripheral event types.
+ */
+enum usbd_event_type {
+	USBD_EVT_POWER,
+	USBD_EVT_EP,
+	USBD_EVT_RESET,
+	USBD_EVT_SOF
```
Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: SOF?

File: drivers/usb/device/usb_dc_nrfx.c [hunk 2]
```diff
@@ -126,25 +132,43 @@ struct nrf_usbd_ep_ctx {
 	volatile bool write_in_progress;
 };
 
+/**
+ * @brief Endpoint event structure
+ *
+ * @param ep		Endpoint convtrol block pointer
```
Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: Is this the correct documentation of structures? I thought we use Doxygen. This looks more like copy paste of Linux documentation style.

Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: s/convtrol/control

File: drivers/usb/device/usb_dc_nrfx.c [hunk 3]
```diff
@@ -441,25 +442,30 @@ static inline void usbd_evt_flush(void)
...
-		LOG_DBG("Unknown USB power event");
+		LOG_ERR("Unknown USB power event");
 		return;
 	}
 
-	ctx->flags |= BIT(NRF_USB_STATE_CHANGE);
-	k_work_submit(&ctx->usb_work);
+	struct usbd_event *ev = usbd_evt_alloc();
+
+	ev->evt_type = USBD_EVT_POWER;
```
Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: what if allocation fails?

File: drivers/usb/device/usb_dc_nrfx.c [hunk 4]
```diff
@@ -773,59 +766,81 @@ static inline void usbd_work_process_recvreq(struct nrf_usbd_ctx *ctx,
...
-	ctx = CONTAINER_OF(item, struct nrf_usbd_ctx, usb_work);
+	__ASSERT_NO_MSG(ep_ctx);
 
-	if (ctx->flags) {
-		if (ctx->flags & BIT(NRF_USB_STATE_CHANGE)) {
-			usbd_handle_state_change(ctx);
-			ctx->flags &= ~BIT(NRF_USB_STATE_CHANGE);
-		}
+	switch (ep_evt->evt_type) {
+	case EP_EVT_SETUP_RECV: {
```
Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: curly brackets not needed

File: drivers/usb/device/usb_dc_nrfx.c [hunk 5]
```diff
@@ -773,59 +766,81 @@ static inline void usbd_work_process_recvreq(struct nrf_usbd_ctx *ctx,
...
+		ep_ctx->cfg.cb(ep_ctx->cfg.addr,
+			       USB_DC_EP_DATA_OUT);
+		break;
 
-		if (ctx->flags & BIT(NRF_USB_STATUS_CHANGE)) {
-			usbd_handle_status_change(ctx);
-			ctx->flags &= ~BIT(NRF_USB_STATUS_CHANGE);
+	case EP_EVT_WRITE_COMPLETE:
+		if (ep_ctx->cfg.type == USB_DC_EP_CONTROL) {
+			k_mutex_lock(&ctx->drv_lock, K_FOREVER);
```
Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: this one is tricky

The drv_lock is taken when data is send (`usb_dc_ep_write`) which can be called from any thread, possibly with priority lower then workqueue thread. It can happen then that workqueue will take over the CPU while lock is held and system will deadlock.

File: drivers/usb/device/usb_dc_nrfx.c [hunk 6]
```diff
@@ -773,59 +766,81 @@ static inline void usbd_work_process_recvreq(struct nrf_usbd_ctx *ctx,
...
-			default:
-				break;
+			break;
+		case USBD_EVT_SOF:
+			if (ctx->status_cb) {
+				ctx->status_cb(USB_DC_SOF, NULL);
 			}
+			break;
+		default:
+			LOG_ERR("Unknown USBD event: %d.", (u32_t)ev->evt_type);
```
Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: please do not cast to `u32_t`
First default argument type is int so you type will be cast to it anyway, second if specific width is used you should use appropriate formatting modifier (in this case `PRIu32`)

File: drivers/usb/device/usb_dc_nrfx.c [hunk 7]
```diff
@@ -849,12 +864,13 @@ static void usbd_event_transfer_ctrl(nrfx_usbd_evt_t const *const p_event)
 	if (NRF_USBD_EPIN_CHECK(p_event->data.eptransfer.ep)) {
 		switch (p_event->data.eptransfer.status) {
 		case NRFX_USBD_EP_OK: {
-			struct usbd_ep_event *ev = usbd_evt_alloc();
-
-			ev->ep = ep_ctx;
-			ev->evt = EP_EVT_WRITE_COMPLETE;
+			struct usbd_event *ev = usbd_evt_alloc();
```
Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: allocation can fail (also in other cases)

**Review by pdunaj — CHANGES_REQUESTED** [review]

File: drivers/usb/device/usb_dc_nrfx.c (hunk 5 above)
Comment (pdunaj) [reply drivers/usb/device/usb_dc_nrfx.c]: Discussed offline. I think this is not a problem (at least deadlock) as worqueue thread will loose the CPU and low priority task will be able to finish.
Please ignore this one.

File: drivers/usb/device/usb_dc_nrfx.c (hunk 1 above)
Comment (masz-nordic) [reply drivers/usb/device/usb_dc_nrfx.c]: Start of Frame

**Comment by carlescufi** [comment]
@pawelzadrozniak will you rework this?

File: drivers/usb/device/usb_dc_nrfx.c (hunk 7 above)
Comment (pawelzadrozniak) [reply drivers/usb/device/usb_dc_nrfx.c]: Changes applied.
Queue size is now configurable. If allocation fails then the drivers is reinitialized and queue is flushed with an error message in log. Device can still be re-enumerated - a "soft" form of a failure instead of device reset as it was before.

**Review by masz-nordic — APPROVED** [review]

File: drivers/usb/device/usb_dc_nrfx.c (hunk 2 above)
Comment (pdunaj) [reply drivers/usb/device/usb_dc_nrfx.c]: @b-gent can you tell?

**Review by pdunaj — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
