### PR TITLE
kernel: poll: remove unreachable code

### LINKED ISSUE #31282: Kernel: Poll: Code Suspected Logic Problem
I found that there is a bug in the poll source code, the code as below:
static inline int register_events()
{
	int events_registered = 0;

	for (int ii = 0; ii < num_events; ii++) {
		k_spinlock_key_t key;
		uint32_t state;

		key = k_spin_lock(&lock);
		if (is_condition_met(&events[ii], &state)) {
			set_event_ready(&events[ii], state);
			poller->is_polling = false;
		} else if (!just_check && poller->is_polling) {
			int rc = register_event(&events[ii], poller);
			**if (rc == 0) {
				events_registered += 1;
			} else {
				__ASSERT(false, "unexpected return code\n");
			}**
		}
		k_spin_unlock(&lock, key);
	}

	return events_registered;
}

register_event function code as below:
static inline int register_event()
{
	switch (event->type) {
	case K_POLL_TYPE_SEM_AVAILABLE:
		__ASSERT(event->sem != NULL, "invalid semaphore\n");
		add_event(&event->sem->poll_events, event, poller);
		break;
	case K_POLL_TYPE_DATA_AVAILABLE:
		__ASSERT(event->queue != NULL, "invalid queue\n");
		add_event(&event->queue->poll_events, event, poller);
		break;
	case K_POLL_TYPE_SIGNAL:
		__ASSERT(event->signal != NULL, "invalid poll signal\n");
		add_event(&event->signal->poll_events, event, poller);
		break;
	case K_POLL_TYPE_IGNORE:
		/* nothing to do */
		break;
	default:
		__ASSERT(false, "invalid event type\n");
		break;
	}

	event->poller = poller;

	**return 0;**
}

As you can see, rc is the return value of the function register_event. The judgment condition is whether rc is equal to 0. Analysis of the function register_event code shows that the function has only one return value 0, so if the function runs without an ASSERT error, the return value must be 0, so I think logic of this code is a bug and needs to be fixed.

### PR DESCRIPTION
**Pull request by Zhaoningx**
register_event always returns 0, so the conditional will always take
the first branch and code in the else statement is never reached.

Fixes #31282 
 
Signed-off-by: Ningx Zhao <ningx.zhao@intel.com>

### CODE REVIEW

File: kernel/poll.c [hunk 1]
```diff
@@ -213,12 +213,9 @@ static inline int register_events(struct k_poll_event *events,
 			set_event_ready(&events[ii], state);
 			poller->is_polling = false;
 		} else if (!just_check && poller->is_polling) {
-			int rc = register_event(&events[ii], poller);
-			if (rc == 0) {
-				events_registered += 1;
-			} else {
-				__ASSERT(false, "unexpected return code\n");
-			}
+			register_event(&events[ii], poller);
```
Comment (nashif) [inline kernel/poll.c:216]: this will fail static analysis checks, return code shall be checked.

**Review by nashif — CHANGES_REQUESTED** [review]

**Comment by nashif** [comment]
You need to rebase your tree, you are applying this change on a code base from last year.

**Comment by Zhaoningx** [comment]
Hi @nashif , I have rebased my tree and modify the poll.c code, could you take a look at this again?

**Review by LeiW000 — APPROVED** [review]

File: kernel/poll.c [hunk 2]
```diff
@@ -213,12 +213,10 @@ static inline int register_events(struct k_poll_event *events,
...
 			poller->is_polling = false;
 		} else if (!just_check && poller->is_polling) {
-			int rc = register_event(&events[ii], poller);
-			if (rc == 0) {
-				events_registered += 1;
-			} else {
-				__ASSERT(false, "unexpected return code\n");
-			}
+
+			__ASSERT(register_event(&events[ii], poller) == 0, "unexpected return code\n");
```
Comment (chrta) [inline kernel/poll.c:217]: If assertions are disabled, register_event() is not called at all, see https://github.com/zephyrproject-rtos/zephyr/blob/master/include/sys/__assert.h#L111

Or am i missing something?

**Review by chrta — CHANGES_REQUESTED** [review]

File: kernel/poll.c (hunk 2 above)
Comment (nashif) [inline kernel/poll.c:217]: You can't do that. Asserts also can be disabled.

**Review by nashif — CHANGES_REQUESTED** [review]

**Comment by enjiamai** [comment]
@LeiW000  @Zhaoningx  For descriptions from Anas and chrta22. I think if it is better to keep them? Just write down the justification for it?

**Comment by LeiW000** [comment]
> @LeiW000 @Zhaoningx For descriptions from Anas and chrta22. I think if it is better to keep them? Just write down the justification for it?

Their comments are for Ning's previous change, not for the latest change.

**Review by enjiamai — APPROVED** [review]
@steven Oh, got it,  thanks! @Zhaoningx  It looks fine for me.

File: kernel/poll.c [hunk 3]
```diff
@@ -214,10 +214,9 @@ static inline int register_events(struct k_poll_event *events,
 			poller->is_polling = false;
 		} else if (!just_check && poller->is_polling) {
 			int rc = register_event(&events[ii], poller);
```
Comment (chrta) [inline kernel/poll.c:216]: Now that i look at the implementation of `register_event`, see https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/poll.c#L121 It always returns 0.

I think the proper solution here would be:
1. change `static inline int register_event()` into `static inline void register_event()` and remove the `return 0` inside the function.
2. In this line (line 216) remove the variable rc, so you have here sth like:
```
register_event(&events[ii], poller);
events_registered += 1;
```

@nashif What do you think? Or should `register_event()` actually return a value?

**Review by chrta — CHANGES_REQUESTED** [review]

File: kernel/poll.c (hunk 3 above)
Comment (nashif) [reply kernel/poll.c:216]: yes, that works.

**Comment by nashif** [comment]
Also, please fix the commit message. Be specific in the commit subject (Simplified code is not enough) and explain what you are doing in the body, right now it is very generic wording.

**Comment by Zhaoningx** [comment]
Hi @chrta @nashif , thanks for your comments, I have updated the PR, could you take a look at this?

**Review by chrta — APPROVED** [review]

**Review by nashif — APPROVED** [review]
