### PR TITLE
Bluetooth: service: HRM: fix control point write callback missing

### LINKED ISSUE #77596: Bluetooth: services: HRS write fails with error code
Spin-off from https://github.com/zephyrproject-rtos/zephyr/issues/73503

Write to the heart-rate characteristic does not work.

> HRM Write:
Write operation is not successful with error message.
Error Message
Android - Error occurred in writing data. Error Code : 3. Please Try again
iOS - Error occurred in writing data. Error : Writing is not Permitted. Please Try again

https://github.com/zephyrproject-rtos/zephyr/issues/73503#issuecomment-2309989048 says a write callback is missing in the characteristic definition.

### PR DESCRIPTION
**Pull request by cx-anuj-pathak**
`BT_UUID_HRS_CONTROL_POINT` characteristic was included in Heart Rate service definition with write permissions.
But characteristic write handler is not defined.
This PR add and define control point characteristic write handler, which passes the command to application using callback for further handling.

Fixes: #77596

### CODE REVIEW

File: samples/bluetooth/peripheral/src/main.c [hunk 1]
```diff
@@ -350,6 +350,17 @@ static void hrs_notify(void)
 	bt_hrs_notify(heartrate);
 }
 
+int bt_hrs_ctrl_point_write(uint8_t value)
+{
+	printk("HRS Control point write: %d\n", value);
+
+	return 0;
+}
```
Comment (Thalley) [inline samples/bluetooth/peripheral/src/main.c:358]: I think it would be helpful if this could demonstrate some behavior related to the control point. 

I would also suggest to add an `enum` or `#define`s for the possible values here (or a union of structs if the control points have parameters).

File: subsys/bluetooth/services/hrs.c [hunk 2]
```diff
@@ -79,6 +79,29 @@ static ssize_t read_blsc(struct bt_conn *conn, const struct bt_gatt_attr *attr,
...
+	LOG_INF("HRS CTRL Point Written %d", len);
+
+	SYS_SLIST_FOR_EACH_CONTAINER(&hrs_cbs, listener, _node) {
+		if (listener->ctrl_point_write) {
+			err = listener->ctrl_point_write(*((uint8_t *)buf));
+			if (err) {
+				break;
+			}
+		}
+	}
```
Comment (Thalley) [inline subsys/bluetooth/services/hrs.c:97]: This seems a bit tricky. 

So there are multiple listeners and it's just whomever returns a non-0 value first that gets to control the flow?

File: include/zephyr/bluetooth/services/hrs.h [hunk 3]
```diff
@@ -34,6 +34,12 @@ struct bt_hrs_cb {
 	 */
 	void (*ntf_changed)(bool enabled);
 
+	/** @brief Heart rate control point write callback
+	 *
+	 * @param value value written to corresponding attribute
+	 */
+	int (*ctrl_point_write)(uint8_t value);
```
Comment (Thalley) [inline include/zephyr/bluetooth/services/hrs.h:41]: Missing documentation of the return value

File: samples/bluetooth/peripheral/src/main.c (hunk 1 above)
Comment (cx-anuj-pathak) [reply samples/bluetooth/peripheral/src/main.c]: added reset_request demo.

I can only find one request in HRS_SPEC_V10.pdf, that is Reset Energy Expanded. and nRF Connect app too only writes 1 to this characteristic. thus used a macro only.

File: include/zephyr/bluetooth/services/hrs.h [hunk 4]
```diff
@@ -25,6 +25,8 @@
 extern "C" {
 #endif
 
+#define BT_HRS_CONTROL_POINT_RESET_REQ 0x01
```
Comment (Thalley) [inline include/zephyr/bluetooth/services/hrs.h:28]: This should have  doxygen documentation string

File: include/zephyr/bluetooth/services/hrs.h [hunk 5]
```diff
@@ -34,6 +36,15 @@ struct bt_hrs_cb {
...
 	void (*ntf_changed)(bool enabled);
 
+	/** @brief Heart rate control point write callback
+	 *
+	 * @param request control point request code
+	 *
+	 * @return int 0 on successful handling of control point request
+	 *             negative error codes
+	 */
+	int (*ctrl_point_write)(uint8_t request);
```
Comment (Thalley) [inline include/zephyr/bluetooth/services/hrs.h:46]: Please add reference to `BT_HRS_CONTROL_POINT_RESET_REQ` so that users can relate `request` to the possible value(s)

File: samples/bluetooth/peripheral/src/main.c [hunk 6]
```diff
@@ -337,19 +337,34 @@ static void bas_notify(void)
 	bt_bas_set_battery_level(battery_level);
 }
 
+static uint8_t bt_heartrate = 90U;
```
Comment (Thalley) [inline samples/bluetooth/peripheral/src/main.c:340]: Minor suggestion: Suggest to introduce a `#define HEARTRATE_DEFAULT 90U` and use that instead of 3 literal ints

File: samples/bluetooth/peripheral/src/main.c [hunk 7]
```diff
@@ -337,19 +337,34 @@ static void bas_notify(void)
...
+	if (request != BT_HRS_CONTROL_POINT_RESET_REQ) {
+		return -ENOTSUP;
 	}
 
-	bt_hrs_notify(heartrate);
+	bt_heartrate = 90;
+	return 0;
 }
 
+struct bt_hrs_cb hrs_cb = {
```
Comment (Thalley) [inline samples/bluetooth/peripheral/src/main.c:364]:
```suggestion
static struct bt_hrs_cb hrs_cb = {
```

File: samples/bluetooth/peripheral/src/main.c [hunk 8]
```diff
@@ -337,19 +337,34 @@ static void bas_notify(void)
...
-		heartrate = 90U;
+	bt_heartrate++;
+	if (bt_heartrate == 160U) {
+		bt_heartrate = 90U;
+	}
+
+	bt_hrs_notify(bt_heartrate);
+}
+
+int bt_hrs_ctrl_point_write(uint8_t request)
```
Comment (Thalley) [inline samples/bluetooth/peripheral/src/main.c:353]:
```suggestion
static int bt_hrs_ctrl_point_write(uint8_t request)
```

File: samples/bluetooth/peripheral/src/main.c [hunk 9]
```diff
@@ -337,19 +337,34 @@ static void bas_notify(void)
...
+{
+	printk("HRS Control point request: %d\n", request);
+	if (request != BT_HRS_CONTROL_POINT_RESET_REQ) {
+		return -ENOTSUP;
```
Comment (Thalley) [inline samples/bluetooth/peripheral/src/main.c:357]: And this illustrates the issue mentioned in https://github.com/zephyrproject-rtos/zephyr/pull/77598/files#r1732584303

If there are multiple listeners to this callback and this application does not support opcode X but another does, then the other application will never get the request.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: samples/bluetooth/peripheral/src/main.c (hunk 9 above)
Comment (cx-anuj-pathak) [reply samples/bluetooth/peripheral/src/main.c:357]: Yup i realized it while implementing the example code. I have planned to use -ENOTSUP as a pass thru error,
Which will continue handling of this requests with other listeners.

**Review by Thalley — CHANGES_REQUESTED** [review]

**Review by Thalley — CHANGES_REQUESTED** [review]

File: include/zephyr/bluetooth/services/hrs.h [hunk 10]
```diff
@@ -34,6 +39,22 @@ struct bt_hrs_cb {
...
+	 *
+	 * @note if Server supports supports the Energy Expended feature then application
+	 * must implement and support @ref BT_HRS_CONTROL_POINT_RESET_ENERGY_EXPANDED_REQ
+	 * request code
+	 *
+	 * @param request control point request code
+	 *
+	 * @return 0 on successful handling of control point request
+	 * @return -ENOTSUP if not supported. It can be used to pass handling to other
+	 *         listeners in case of multiple listeners
```
[the remark this answers is not in the document]
Comment (cx-anuj-pathak) [reply include/zephyr/bluetooth/services/hrs.h]: updated let me know if it is more clear now

**Review by Thalley — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

**Comment by cx-anuj-pathak** [comment]
Rebased branch due to merge conflicts after getting https://github.com/zephyrproject-rtos/zephyr/pull/77394 merge.

**Review by jhedberg — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

File: samples/bluetooth/peripheral/src/main.c [hunk 11]
```diff
@@ -394,6 +396,21 @@ const struct bt_cts_cb cts_cb = {
 	.notification_changed = bt_cts_notification_changed,
 	.cts_time_write = bt_cts_cts_time_write,
 	.fill_current_cts_time = bt_cts_fill_current_cts_time,
+}
```
Comment (Thalley) [inline samples/bluetooth/peripheral/src/main.c:399]:
```suggestion
};
```

**Review by Thalley — CHANGES_REQUESTED** [review]

**Review by Thalley — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]
