### PR TITLE
Fixes in ring buffer tests

### LINKED ISSUE #37768: tests/lib/ringbuffer/libraries.data_structures fails to build on number of platforms due to CONFIG_SYS_CLOCK_TICKS_PER_SEC=100000
`/scripts/twister -s tests/lib/ringbuffer/libraries.data_structures -l`

gets:

```
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c: In function 'sys_clock_set_timeout':
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:85:30: error: division by zero [-Werror=div-by-zero]
   85 | #define MAX_TICKS (TIMER_MAX / CYCLES_PER_TICK)
      |                              ^
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:205:44: note: in expansion of macro 'MAX_TICKS'
  205 |  } else if ((n == K_TICKS_FOREVER) || (n > MAX_TICKS)) {
      |                                            ^~~~~~~~~
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:85:30: error: division by zero [-Werror=div-by-zero]
   85 | #define MAX_TICKS (TIMER_MAX / CYCLES_PER_TICK)
      |                              ^
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:206:16: note: in expansion of macro 'MAX_TICKS'
  206 |   full_ticks = MAX_TICKS - 1;
      |                ^~~~~~~~~
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:227:51: error: division by zero [-Werror=div-by-zero]
  227 |  partial_cycles = CYCLES_PER_TICK - (total_cycles % CYCLES_PER_TICK);
      |                                                   ^
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c: In function 'sys_clock_elapsed':
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:262:8: error: division by zero [-Werror=div-by-zero]
  262 |  ticks /= CYCLES_PER_TICK;
      |        ^~
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c: In function 'xec_rtos_timer_isr':
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:85:30: error: division by zero [-Werror=div-by-zero]
   85 | #define MAX_TICKS (TIMER_MAX / CYCLES_PER_TICK)
      |                              ^
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:282:16: note: in expansion of macro 'MAX_TICKS'
  282 |  timer_restart(MAX_TICKS * CYCLES_PER_TICK);
      |                ^~~~~~~~~
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:85:30: error: division by zero [-Werror=div-by-zero]
   85 | #define MAX_TICKS (TIMER_MAX / CYCLES_PER_TICK)
      |                              ^
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:285:15: note: in expansion of macro 'MAX_TICKS'
  285 |  cached_icr = MAX_TICKS * CYCLES_PER_TICK;
      |               ^~~~~~~~~
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:293:8: error: division by zero [-Werror=div-by-zero]
  293 |  ticks /= CYCLES_PER_TICK;
      |        ^~
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c: In function 'sys_clock_driver_init':
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:85:30: error: division by zero [-Werror=div-by-zero]
   85 | #define MAX_TICKS (TIMER_MAX / CYCLES_PER_TICK)
      |                              ^
/home/galak/git/zephyr/drivers/timer/mchp_xec_rtos_timer.c:374:15: note: in expansion of macro 'MAX_TICKS'
  374 |  cached_icr = MAX_TICKS;
      |         
```

### LINKED ISSUE #37861: tests/lib/ringbuffer failed on ARC boards
**Describe the bug**
tests/lib/ringbuffer failed on ARC boards: hsdk, qemu_arc_hs, nsim_hs_smp

**To Reproduce**
1. west build -b hsdk -d build tests/lib/ringbuffer
2. west -v flash  -r mdb-hw  --cores=4
3. See error

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.6.0-2360-gc94e53c9f5b6  ***
Running test suite test_ringbuffer_api
===================================================================
START - test_ringbuffer_init
 PASS - test_ringbuffer_init in 0.1 seconds
===================================================================
START - test_ringbuffer_declare_pow2
 PASS - test_ringbuffer_declare_pow2 in 0.1 seconds
===================================================================
START - test_ringbuffer_declare_size
 PASS - test_ringbuffer_declare_size in 0.1 seconds
===================================================================
START - test_ringbuffer_put_get_thread
 PASS - test_ringbuffer_put_get_thread in 0.4 seconds
===================================================================
START - test_ringbuffer_put_get_isr
 PASS - test_ringbuffer_put_get_isr in 0.1 seconds
===================================================================
START - test_ringbuffer_put_get_thread_isr
 PASS - test_ringbuffer_put_get_thread_isr in 0.1 seconds
===================================================================
START - test_ringbuffer_put_get_discard
 PASS - test_ringbuffer_put_get_discard in 0.1 seconds
===================================================================
START - test_ringbuffer_pow2_put_get_thread_isr
 PASS - test_ringbuffer_pow2_put_get_thread_isr in 0.1 seconds
===================================================================
START - test_ringbuffer_size_put_get_thread_isr
 PASS - test_ringbuffer_size_put_get_thread_isr in 0.1 seconds
===================================================================
START - test_ringbuffer_array_perf
 PASS - test_ringbuffer_array_perf in 0.1 seconds
===================================================================
START - test_ringbuffer_partial_putting
 PASS - test_ringbuffer_partial_putting in 0.1 seconds
===================================================================
START - test_ringbuffer_partial_getting
 PASS - test_ringbuffer_partial_getting in 0.1 seconds
===================================================================
START - test_ring_buffer_main
 PASS - test_ring_buffer_main in 0.1 seconds
===================================================================
START - test_ringbuffer_raw
 PASS - test_ringbuffer_raw in 0.1 seconds
===================================================================
START - test_ringbuffer_alloc_put
 PASS - test_ringbuffer_alloc_put in 0.1 seconds
===================================================================
START - test_byte_put_free
 PASS - test_byte_put_free in 0.1 seconds
===================================================================
START - test_ringbuffer_equal_bufs
 PASS - test_ringbuffer_equal_bufs in 0.1 seconds
===================================================================
START - test_capacity
 PASS - test_capacity in 0.1 seconds
===================================================================
START - test_size
 PASS - test_size in 0.1 seconds
===================================================================
START - test_peek
 PASS - test_peek in 0.1 seconds
===================================================================
START - test_reset
 PASS - test_reset in 0.1 seconds
===================================================================
START - test_ringbuffer_performance
1 byte put-get, avg cycles: 264
4 byte put-get, avg cycles: 310
1 byte put claim-finish, avg cycles: 217
5 byte put claim-finish, avg cycles: 261
5 byte get claim-finish, avg cycles: 258
 PASS - test_ringbuffer_performance in 0.19 seconds
===================================================================
START - test_ringbuffer_concurrent

    Assertion failed at WEST_TOPDIR/zephyr/tests/lib/ringbuffer/src/concurrent.c:72: data_read: memcmp(outpu0

 FAIL - test_ringbuffer_concurrent in 0.14 seconds
===================================================================
START - test_ringbuffer_shpsc
preempted: 1152

    Assertion failed at WEST_TOPDIR/zephyr/tests/lib/ringbuffer/src/concurrent.c:373: thread_entry_spsc: (pr)
If thread operation was not preempted multiple times then we cannot have confidance that it validated the moe
 FAIL - test_ringbuffer_shpsc in 5.27 seconds
===================================================================
START - test_ringbuffer_spshc
preempted: 1734
 PASS - test_ringbuffer_spshc in 5.2 seconds
===================================================================
START - test_ringbuffer_cpy_shpsc
preempted: 2552
 PASS - test_ringbuffer_cpy_shpsc in 5.2 seconds
===================================================================
START - test_ringbuffer_cpy_spshc
preempted: 3076
 PASS - test_ringbuffer_cpy_spshc in 5.1 seconds
===================================================================
START - test_ringbuffer_item_shpsc
preempted: 3595
 PASS - test_ringbuffer_item_shpsc in 5.1 seconds
===================================================================
START - test_ringbuffer_item_spshc
preempted: 3948
 PASS - test_ringbuffer_item_spshc in 5.1 seconds
===================================================================
Test suite test_ringbuffer_api failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK)
 - Commit SHA (c94e53c9f5b6be29ce42b3cc8b50c6a27a487246)

### LINKED ISSUE #38093: preempt_cnt not reset in each test case in tests/lib/ringbuffer/libraries.data_structures
**Describe the bug**
why `preempt_cnt` not reset in each test case in tests/lib/ringbuffer/libraries.data_structures ?

we will assert `preempt_cnt > 1500`, so some test cases will always true.

https://github.com/zephyrproject-rtos/zephyr/blob/e7436ea862b293927b189fb77de1808d45fb9e4b/tests/lib/ringbuffer/src/concurrent.c#L40

https://github.com/zephyrproject-rtos/zephyr/blob/e7436ea862b293927b189fb77de1808d45fb9e4b/tests/lib/ringbuffer/src/concurrent.c#L291

https://github.com/zephyrproject-rtos/zephyr/blob/e7436ea862b293927b189fb77de1808d45fb9e4b/tests/lib/ringbuffer/src/concurrent.c#L302

https://github.com/zephyrproject-rtos/zephyr/blob/e7436ea862b293927b189fb77de1808d45fb9e4b/tests/lib/ringbuffer/src/concurrent.c#L372-L376

### PR DESCRIPTION
**Pull request by nordic-krch**
Fixing failing tests for multiple platforms.

Fixes #38093.
Fixes #37768.

### CODE REVIEW

File: include/sys/ring_buffer.h [hunk 1]
```diff
@@ -128,7 +128,7 @@ struct ring_buf {
 #define RING_BUF_DECLARE(name, size8) \
 	BUILD_ASSERT(size8 < RING_BUFFER_MAX_SIZE,\
 		RING_BUFFER_SIZE_ASSERT_MSG); \
-	static uint8_t __noinit _ring_buffer_data_##name[size8]; \
+	static uint8_t __noinit _ring_buffer_data_##name[size8] __aligned(sizeof(int)); \
```
Comment (evgeniy-paltsev) [inline include/sys/ring_buffer.h:131]: Hmm, as we need alignment here - are you sure that `__aligned(sizeof(int))` is enough on all platforms, especially 64 bit ones? Probably it would be better to use something like `uintptr_t` instead of `int` here?

PS: do we use `__aligned(sizeof(x))`  instead of `__alignof__` intentionally here?

Comment (nordic-krch) [reply include/sys/ring_buffer.h:131]: actually, it looks like an issue with noinit section in arc platform. If i add
```
uint8_t __noinit t;
void main(void)
{
  printk("%d\n", t);
}
```
it hangs on `qemu_arc_hs`

Comment (nordic-krch) [reply include/sys/ring_buffer.h:131]: Adding `__aligned(sizeof(int))` fixes it.  Given that i will remove this alignment from ring buffer and will open an issue.

**Review by cfriedt — APPROVED** [review]
LGTM

**Comment by cfriedt** [comment]
@evgeniy-paltsev  - please revisit as soon as possible.

**Review by carlescufi — APPROVED** [review]
