### PR TITLE
Bluetooth: Mesh: Fix adhering to the configured Friend Queue size

### LINKED ISSUE #18090: [zephyr 1.14][MESH/NODE/FRND/FN/BV-08-C] Mesh Friend queues more messages than indicates it's Friend Cache
**Describe the bug**
This is causing MESH/NODE/FRND/FN/BV-08-C qualification test case fail.
Zephyr Friend Cache Size is set to 16.
In the first step, PTS_1 sends 14 messages to Zephyr, that are queued and later polled by PTS_2.
In the second step, PTS_1 sends 19 messages to Zephyr. PTS_2 polls the messages and receives 19 packets instead of 15 or 16 as PTS states. 

According to Mesh Profile 1.0.1 3.5.5 Friend Queue
```
If the Friend Queue is full and a new message needs to be stored that is not a Friend Update message,
the oldest entries other than a Friend Update message shall be discarded to make room for the new
message.
Note: An implementation may have to discard multiple messages to fit the new message into the
Friend Queue.
```

**To Reproduce**
1. Run MESH/NODE/FRND/FN/BV-08-C test case

**Impact**
MESH/NODE/FRND/FN/BV-08-C

**Screenshots or console output**
[mesh_node_frnd_fv_bv-08-c.log](https://github.com/zephyrproject-rtos/zephyr/files/3477320/mesh_node_frnd_fv_bv-08-c.log)

### PR DESCRIPTION
**Pull request by jhedberg**
Qualification test case MESH/NODE/FRND/FN/BV-08-C requires that we do
not store more messages than the reported Friend Queue size. The
implementation was so far opportunistic and stored more if it could
(it would later discard if necessary to make sure all queues can store
the required amount). The spec also requires the queues to have new
messages overwrite old ones (in the style of a circular buffer), so we
have to keep track of which buffers are part of the same segmented
message (so we discard all buffers belonging to the same message).
    
To pass the test case, add APIs to check for space in the Friend
queue, and track the number of buffers for each incoming segmented
message.
    
Fixes #18090

### CODE REVIEW

**Comment by jhedberg** [comment]
Note I'm not generally happy about the way the spec and test spec deals with Friend Queue overflow handling wrt segmented messages. If you read the spec it uses the term "message" to indicate how many entities the Friend Queue Size indicates will fit the Friend Queue. If we interpret this strictly it means an implementation should be able to cache the worst case scenario, i.e. if it's able to receive up to 32 segments per message, the queue must be able to hold 32 * friend_queue_size buffers. This would be incredibly wasteful for a small-footprint implementation like Zephyr. The curious thing is that there's a single test case for this in the test spec (the one referenced in #18090), however that one *only* uses unsegmented messages, meaning we get no hints from the test spec on how to interpret the spec.

Since we don't need to take the "wasteful" interpretation to pass qualification (at least currently) this PR takes the approach that the Friend Queue Size indicates the number of *buffers* (Network PDUs) the Friend Queue can store. When discarding buffers to make space for new PDUs we do go and make sure to discard the entire message, i.e. all segments of it.

@trond-snekvik how is this implemented in Nordic's Mesh SDK?

**Comment by trond-snekvik** [comment]
In the Nordic Mesh SDK, we use the number of buffers as queue size, with no buffer sharing trickery. We attach a single byte TID to each buffer, and assign the same TID to all segments in the same SAR message. When making room for new buffers, we keep deleting the oldest buffer until we encounter a new TID.

**Comment by jhedberg** [comment]
> In the Nordic Mesh SDK, we use the number of buffers as queue size, with no buffer sharing trickery.

@trond-snekvik I might go for this in the long run as well. It has the downside of consuming more memory (the net_buf pool context per supported LPN), but it'll likely make the code simpler.

As for TID, we're using source address + SeqAuth, which consumes more memory but that's what the transport layer knows about. If we went for a shorter TID then friend.c would need to return this to transport.c.

**Comment by trond-snekvik** [comment]
> As for TID, we're using source address + SeqAuth, which consumes more memory but that's what the transport layer knows about. If we went for a shorter TID then friend.c would need to return this to transport.c.

That works too. Our TIDs are just sequential numbers, since we only really need this info for deletion. We could have used a flag, really, but as far as I can remember, we wouldn't save any space by doing so. We can pick out the acks from the queue by looking at the buffer contents, as buffers are queued up unencrypted (looks like this is not the case in Zephyr. I think that is problematic, but I'll go through the code and create a separate issue).

File: subsys/bluetooth/mesh/friend.c [hunk 1]
```diff
@@ -962,6 +937,10 @@ static void enqueue_friend_pdu(struct bt_mesh_friend *frnd,
 		}
 
 		sys_slist_merge_slist(&frnd->queue, &seg->queue);
+		seg->seg_count = 0U;
+	} else {
+		/* Mark the buffer as having more to come after it */
+		buf->flags |= NET_BUF_FRAGS;
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/friend.c]: Wouldn't this create a NULL pointer reference net_buf_slist_get if we purge the queue before more segments can be added? The for loop in net/buf.c:472 seems to trust this flag enough to not do null checks

Comment (jhedberg) [reply subsys/bluetooth/mesh/friend.c]: @trond-snekvik yes, that's a good catch. Didn't think about this when I started taking advantage of the net_buf fragmentation feature (which really is almost the same thing as the segments, except that the segments come gradually and we might end up with an incomplete set as you point out).

Comment (jhedberg) [reply subsys/bluetooth/mesh/friend.c]: I'm now wondering should we move to something else than NET_BUF_FRAGS or should we fix buf.c to handle incomplete data in the FIFO.

Comment (jhedberg) [reply subsys/bluetooth/mesh/friend.c]: This really only affects the segment list, and not the friend queue, since we only move complete messages to the friend queue. I'm thinking since we mess around with what's essentially an net_buf-internal flag, we should just do the purging ourselves rather than using net_buf helpers.

Comment (jhedberg) [reply subsys/bluetooth/mesh/friend.c]: @trond-snekvik so I'm thinking to just do this:
```
--- a/subsys/bluetooth/mesh/friend.c
+++ b/subsys/bluetooth/mesh/friend.c
@@ -110,7 +110,14 @@ struct bt_mesh_friend *bt_mesh_friend_find(u16_t net_idx, u16_t lpn_addr,
 static void purge_buffers(sys_slist_t *list)
 {
        while (!sys_slist_is_empty(list)) {
-               net_buf_unref(net_buf_slist_get(list));
+               struct net_buf *buf;
+
+               buf = (void *)sys_slist_get_not_empty(&frnd->queue);
+
+               buf->frags = NULL;
+               buf->flags |= ~NET_BUF_FRAGS;
+
+               net_buf_unref(buf);
        }
 }
```

**Review by MariuszSkamra — APPROVED** [review]
All the mesh friend related test cases pass with this PR

File: subsys/bluetooth/mesh/transport.c [hunk 2]
```diff
@@ -140,17 +140,32 @@ static int send_unseg(struct bt_mesh_net_tx *tx, struct net_buf_simple *sdu,
...
+						    tx->src, tx->ctx->addr,
+						    NULL, 1)) {
+			if (BT_MESH_ADDR_IS_UNICAST(tx->ctx->addr)) {
+				BT_ERR("Not enough space in Friend Queue");
+				net_buf_unref(buf);
+				return -ENOBUFS;
+			} else {
+				BT_WARN("No space in Friend Queue");
+				goto send;
+			}
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/transport.c]: Hold on, I don't think I get this part. As far as I can tell, this'll make us discard incoming messages for the friend queue once it's full, but we should remove the oldest message in the friend queue to make room for new ones. What am I missing?

Comment (jhedberg) [reply subsys/bluetooth/mesh/transport.c]: `bt_mesh_friend_queue_has_space()` only checks if too many buffers are already allocated for other pending segmented messages that we're receiving. That's the only case where we don't go and free up messages to make space for a new one in the queue.

Comment (jhedberg) [reply subsys/bluetooth/mesh/transport.c]: @trond-snekvik meaning, if we've committed to receiving a segmented message and are in the process of receiving it then another new message may get discarded.

Comment (jhedberg) [reply subsys/bluetooth/mesh/transport.c]: @trond-snekvik see also the code comment at the end of the static `friend_queue_has_space()` function that `bt_mesh_friend_queue_has_space()` calls

Comment (jhedberg) [reply subsys/bluetooth/mesh/transport.c]: @trond-snekvik we can argue whether a mechanism to abort pending segmented messages should be implemented, however I don't think either way is prohibited by the spec since neither the old nor the new message has yet reached the friend queue.

Comment (trond-snekvik) [reply subsys/bluetooth/mesh/transport.c]: Riiiight, that's what I was missing 😄 Thanks, that makes sense!

**Review by trond-snekvik — APPROVED** [review]

File: subsys/bluetooth/mesh/transport.c (hunk 2 above)
Comment (trond-snekvik) [reply subsys/bluetooth/mesh/transport.c]: I think I did the same choice with SAR sessions in the Nordic Mesh SDK, better to finish the sessions we've already started.
