### PR TITLE
display: ssd1306: add some init delay

### LINKED ISSUE #53800: Raspberry Pi Pico - ssd1306 display attempts to initialize before i2c bus is ready for communication
**Describe the bug**

Hi, I am working on a Raspberry Pi Pico connected to a ssd1306 based o-led display: https://www.adafruit.com/product/938
I used `zephyr/boards/shields/ssd1306/ssd1306_128x32.overlay` as a basis:

```
&i2c0 {
	status = "okay";

	ssd1306_ssd1306_128x64: ssd1306@3c {
		compatible = "solomon,ssd1306fb";
		reg = <0x3d>;
		width = <128>;
		height = <64>;
		segment-offset = <0>;
		page-offset = <0>;
		display-offset = <0>;
		multiplex-ratio = <31>;
		segment-remap;
		com-invdir;
		com-sequential;
		prechargep = <0x22>;
	};
};
```

When I run any of the display sample applications (e.g. `zephyr/samples/subsys/display/cfb`), the application will just work (as the device is just soft-resets before running the code and not disconnected from power). However, I noticed that when I unplug the RPI Pico and re-plug it again, the display stays black.

To me it appears, that the i2c is not immediately ready after power-on to actually be usable for the communication to the display IC when Zypher tries to initialize it. If I add a delay of about 170ms in the `ssd1306_init_device` function the app works correctly and the display is initialized. (Please note that there is no other modification of the sample code. I just attempted to flash the sample using the SHIELD define on a stock Raspberry Pi Pico.)

Also the console prints that node ssd1306@3c is not ready, before even initializing i2c.

**To Reproduce**
1. build cfb sample
2. flash on a rpi_pico with a ssd1306 display connected
4. See black display

**Expected behavior**
See application working as expected.

**Impact**
Delaying the initialization works for me but this might have other effects too.

**Logs and console output**
```
Device ssd1306@3c not ready
[00:00:00.000,000] <inf> i2c_dw: I2C: i2c_dw_initialize > start        # dbg output added by me
[00:00:00.000,000] <inf> i2c_dw: I2C: i2c_dw_runtime_configure > 1        # dbg output added by me
[00:00:00.000,000] <inf> i2c_dw: I2C: i2c_dw_runtime_configure > 2        # dbg output added by me
[00:00:00.000,000] <inf> i2c_dw: I2C: i2c_dw_initialize > end        # dbg output added by me
[00:00:00.000,000] <inf> i2c_dw: I2C: i2c_dw_initialize > start         # dbg output added by me
[00:00:00.000,000] <inf> i2c_dw: I2C: i2c_dw_runtime_configure > 1         # dbg output added by me
[00:00:00.000,000] <inf> i2c_dw: I2C: i2c_dw_runtime_configure > 2         # dbg output added by me
[00:00:00.000,000] <inf> i2c_dw: I2C: i2c_dw_initialize > end         # dbg output added by me
[00:00:00.000,000] <inf> ssd1306: ssd1306_init > start         # dbg output added by me
[00:00:00.001,000] <err> ssd1306: Failed to initialize device!
*** Booting Zephyr OS build zephyr-v3.2.0-3446-g2017ed50bf9a ***
```

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Toolchain: Zephyr SDK
 - master

**Additional context**
-

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Seems like the SSD1306 controller needs a bit of time after power up before it can take i2c commands. This causes problems with microcontrollers that have no other delays in the startup sequence, like rpi_pico.

There's currently no good way of modeling this in Zephyr right now, and there's also no clear indication of how much time the device needs in the datasheet that I could find, but it seems like 10ms is enough for that to start reliably so add a delay in the ssd1306 init function to ensure that at least that time has passed from system power up.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/53800

### CODE REVIEW

**Comment by thedjnK** [comment]
@gmarull

File: drivers/display/ssd1306.c [hunk 1]
```diff
@@ -48,6 +48,8 @@ LOG_MODULE_REGISTER(ssd1306, CONFIG_DISPLAY_LOG_LEVEL);
 #define SSD1306_ADDRESSING_MODE		(SSD1306_SET_MEM_ADDRESSING_HORIZONTAL)
 #endif
 
+#define POWER_UP_DELAY_MS 10
```
Comment (JordanYates) [inline drivers/display/ssd1306.c:51]: Adding the comment from the PR around how this value was chosen and why the `init` function is blocking would be useful for the future.

**Review by jfischer-no — CHANGES_REQUESTED** [review]
10ms is a relatively long time. I worked with various panels that use this controller, but I have never observed this problem. Can you please check again.

**Comment by fabiobaltieri** [comment]
> 10ms is a relatively long time. I worked with various panels that use this controller, but I have never observed this problem. Can you please check again.

I initially had the same thought but then tried to print the cycle count on an nrf52dk and realized that by the time it hits this function it's already more than 150ms into it, then I checked other drivers and there's load of displays that sleeps for much much longer (hundreds of ms) in their init function, typically after reset but at the end of the day it's still the same, delays the system startup. Plus this becomes a no-op for platforms that already started for a while which I bet it's most of them.

I tried a handful of values, 5ms was not enough, 10ms seems to be fine, I'd still like to hear from @doctorseus for some extra test runs on a different setup.

File: drivers/display/ssd1306.c (hunk 1 above)
Comment (fabiobaltieri) [reply drivers/display/ssd1306.c:54]: Yeah fair enough, added a couple lines, happy to change them if it turns out I missed it from the device datasheet.

**Review by jfischer-no — DISMISSED** [review]

**Comment by yonsch** [comment]
This might be enough as a hotfix, but in the long run I think we need a better solution. A few problems I can think of:
1. If you have N displays your boot time will increase by N * 10ms, when 10ms would have been sufficient for all displays. This also applies if you have two different devices with different boot times.
2. Depending on the application, you might have a critical task that needs to start ASAP, and the display is low priority and could be initialized later on. In that case you wouldn't want the critical task to wait 10ms for the display to boot.
3. As far as I know, all drivers assume that the device they're initializing is ready. If it isn't, an error is returned and the boot fails. Evidently this is usually true, but theoretically we can run into undefined behavior if the device and SoC's boot times get too close. Perhaps if we had some delay and retry mechanism the device could have recovered.

In the short term, I would suggest changing the boot stage from `POST_KERNEL` to `APPLICATION`.

**Comment by yonsch** [comment]
Also, I think the delay duration should be a Kconfig with a default value, to allow anyone to override it

**Comment by fabiobaltieri** [comment]
> This might be enough as a hotfix, but in the long run I think we need a better solution. A few problems I can think of:
> 
>     1. If you have N displays your boot time will increase by N * 10ms, when 10ms would have been sufficient for all displays. This also applies if you have two different devices with different boot times.

The delay is relative to the boot time so this would work as you described: the first one would wait up to 10ms and the other ones would go through with no wait, that's what `K_TIMEOUT_ABS_MS` does.

Other display reset code has that problem though but not much you can do about it.

>     2. Depending on the application, you might have a critical task that needs to start ASAP, and the display is low priority and could be initialized later on. In that case you wouldn't want the critical task to wait 10ms for the display to boot.

Then the task would have to be setup to start at higher priority and that whole story be handled at application level.

>     3. As far as I know, all drivers assume that the device they're initializing is ready. If it isn't, an error is returned and the boot fails. Evidently this is usually true, but theoretically we can run into undefined behavior if the device and SoC's boot times get too close. Perhaps if we had some delay and retry mechanism the device could have recovered.
> 
> 
> In the short term, I would suggest changing the boot stage from `POST_KERNEL` to `APPLICATION`.

Don't think that's a good idea, it'll mess up with the init level of the graphical framework (cfb, lvgl) and then the application would have to be initialize after the application, then we'll have a POST_APPLICATON or something. :-)

**Comment by fabiobaltieri** [comment]
> Also, I think the delay duration should be a Kconfig with a default value, to allow anyone to override it

Kconfig should be for application specific things, if anything this could be a binding property, but no reason to do that if we don't expect it to change from device to device.

**Comment by yonsch** [comment]
> that's what K_TIMEOUT_ABS_MS does.

Right, missed that one.

> Kconfig should be for application specific things, if anything this could be a binding property

You're probably right, though in practice Kconfig is used for such things in Zephyr, which is probably not the best practice but is somewhat more convenient for setting defaults in my opinion.

> but no reason to do that if we don't expect it to change from device to device.

I'm unfamiliar with that display controller so I can't tell if it has any variants or multiple manufacturers or if the boot time may be affected by hardware factors. Since this is undocumented and the best we have is trial and error, it seems reasonable that someone might want to change it. (Also, is the uptime measured from power on or from when the image boots? Because if it's the latter, and if a bootloader is present, the delay may not be necessary).

I agree with you on the rest, and in any case I don't think a few milliseconds would mind anyone, especially in applications with a display :) .

**Comment by fabiobaltieri** [comment]
> I agree with you on the rest, and in any case I don't think a few milliseconds would mind anyone, especially in applications with a display :) .

Yeah in fairness I'd expect this to be a noop in many cases, which explains why no one bumped into it until now. Anyway, converted to to a property, somewhat copied it from https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/auxdisplay/auxdisplay_hd44780.c#L207.

File: dts/bindings/display/solomon,ssd1306fb-common.yaml [hunk 2]
```diff
@@ -48,3 +48,9 @@ properties:
       The RESET pin of SSD1306 is active low.
       If connected directly the MCU pin should be configured
       as active low.
+
+  boot-delay-ms:
+    type: int
+    default: 10
```
Comment (gmarull) [inline dts/bindings/display/solomon,ssd1306fb-common.yaml:54]: nit: default needs justification

Comment (fabiobaltieri) [reply dts/bindings/display/solomon,ssd1306fb-common.yaml:54]: Cool, mentioned it in the description.

File: dts/bindings/display/solomon,ssd1306fb-common.yaml [hunk 3]
```diff
@@ -48,3 +48,10 @@ properties:
       The RESET pin of SSD1306 is active low.
       If connected directly the MCU pin should be configured
       as active low.
+
+  boot-delay-ms:
```
Comment (gmarull) [inline dts/bindings/display/solomon,ssd1306fb-common.yaml:52]: I wonder if this really belongs to DT or Kconfig, because of the way it is described. If part of hw description, maybe it should be named more like `ready-time-ms`, and described as "time it takes for the device to become ready/responsive", then, drivers can use such info to insert a boot delay. _being a purist here_

Comment (fabiobaltieri) [reply dts/bindings/display/solomon,ssd1306fb-common.yaml:52]: If it changes I'd expect it to change depending on the specific part number so I'd say DT is fine here (honestly I think hardcoding it could have been good enough). Don't mind renaming it and, let's go with yours.

**Review by gmarull — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@jfischer-no ping

**Review by soburi — APPROVED** [review]
