### PR TITLE
lorawan: notify MAC layer of new datarates

### LINKED ISSUE #31551: lorawan: setting datarate does not allow sending larger packets
**Describe the bug**

Increasing the datarate through `lorawan_set_datarate` does not allow larger packets to be sent.
`REGION_AS923` defaults to `DR_2`, with a maximum payload of 11 bytes. `DR_5` has a maximum payload of 242 bytes.
After increasing the datarate, it should be possible to send more than 11 bytes in a packet. This is not the case.

**To Reproduce**

Modify `zephyr/samples/lorawan/class_a` with:
 * `CONFIG_REGION_AS923`
 * `char data[] = { 'h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd', '!', '!', '!', '!', '!' }` (>11 bytes)
 * `lorawan_set_datarate(LORAWAN_DR_5);`

Results in a permanent loop of the following logs:
```
*** Booting Zephyr OS build zephyr-v2.4.0-28-g7fb028123213  ***
[00:00:00.365,722] <inf> lorawan_class_a: Joining network over OTAA
[00:00:06.142,578] <inf> lorawan: Joined network! DevAddr: 0161be3a
[00:00:06.142,639] <inf> lorawan_class_a: Sending data...
[00:00:06.142,669] <err> lorawan: LoRaWAN Query Tx Possible Failed: Length error
[00:00:06.164,916] <err> lorawan_class_a: lorawan_send failed: -11. Continuing...
[00:00:16.164,978] <err> lorawan: LoRaWAN Query Tx Possible Failed: Length error
[00:00:16.188,171] <err> lorawan_class_a: lorawan_send failed: -11. Continuing...
[00:00:26.188,232] <err> lorawan: LoRaWAN Query Tx Possible Failed: Length error
[00:00:26.211,212] <err> lorawan_class_a: lorawan_send failed: -11. Continuing...
```

**Expected behavior**

Increasing the datarate should result in larger payload sizes.

**Additional context**

The problem is that `lorawan_set_datarate` only modifies local variables, it does not notify the MAC layer of the requested datarate. As a result, when `lorawan_send` runs `LoRaMacQueryTxPossible`, the MAC layer uses the default datarate, which cannot fit the larger payload.

This issue only appears when the first packet on the new datarate would not have fit on the previous datarate.

### PR DESCRIPTION
**Pull request by JordanYates**
Notify the MAC layer when application code calls `lorawan_set_datarate`.
This must occur because it is the MAC layer cached datarate that is used by `LoRaMacQueryTxPossible` in `lorawan_send`.
Failing to notify the MAC layer results in large packets being discarded, even if the requested datarate could support the length.
This also necessitates an additional call to the MAC layer after joining, as the set datarate is overwritten when joining for some regions.

Fixes #31551

### CODE REVIEW

File: subsys/lorawan/lorawan.c [hunk 1]
```diff
@@ -261,6 +261,21 @@ int lorawan_join(const struct lorawan_join_config *join_cfg)
 	}
 
 out:
+	/* Several regions (AS923, AU915, US915) overwrite the datarate as part
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/lorawan.c:264]: Nit: Please use below format for multi line comments:

```
/*
  Several regions (AS923, AU915, US915) overwrite the datarate as part...
*/
```

**Review by Mani-Sadhasivam — APPROVED** [review]

**Review by nashif — APPROVED** [review]
