### PR TITLE
sd: sdmmc: wait before sending second OCR

### LINKED ISSUE #47238: SD Card init issue when CONFIG_SPEED_OPTIMIZATIONS=y
**Describe the bug**

When I'm turning on `CONFIG_SPEED_OPTIMIZATIONS=y` I'm getting  `sd:Card never left busy state` error.  

**To Reproduce**
prj.conf
```
CONFIG_STDOUT_CONSOLE=y

CONFIG_CPLUSPLUS=y
CONFIG_STD_CPP20=y
CONFIG_NEWLIB_LIBC=y
CONFIG_LIB_CPLUSPLUS=y

CONFIG_MAIN_STACK_SIZE=90000

CONFIG_DEBUG=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y

CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_SPI=y

CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_PWM_LOG_LEVEL_DBG=y

CONFIG_FS_LITTLEFS_BLK_DEV=y
CONFIG_APP_LITTLEFS_STORAGE_BLK_SDMMC=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

CONFIG_TIMING_FUNCTIONS=y

CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_FS_FATFS_NUM_FILES=10
```

```
            if (disk_access_init(disk_pdrv) != 0) {
                LOG_ERR("Storage init ERROR!");
                break;
            }
```

1. west flash 

I don't have this problem when i setup comment out `CONFIG_SPEED_OPTIMIZATIONS=y` from my config file. 

**Expected behavior**
I'm able to read from SD card files with `CONFIG_SPEED_OPTIMIZATIONS=y`

**Impact**
I can't use `CONFIG_SPEED_OPTIMIZATIONS=y`

**Logs and console output**
image

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 3.1.99

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

### PR DESCRIPTION
**Pull request by danieldegrasse**
introduce a small wait between probing and initialization OCR. This
delay fixes a failure to initialize seen on some SD cards

Fixes #47238

Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@asarbs Can you test this PR with your SD card? I was able to reproduce the failure you saw on a card I've got, but want to make sure this fixes your issue

**Comment by asarbs** [comment]
I will try tomorrow

**Review by jfischer-no — APPROVED** [review]

File: subsys/sd/sdmmc.c [hunk 1]
```diff
@@ -998,6 +998,11 @@ int sdmmc_card_init(struct sd_card *card)
 			ocr_arg |= SD_OCR_VDD29_30FLAG;
 		}
 		ocr_arg |= (SD_OCR_VDD32_33FLAG | SD_OCR_VDD33_34FLAG);
+		/* Momentary delay before initialization OCR. Some cards will
+		 * never leave busy state if init OCR is sent too soon after
+		 * probing OCR
+		 */
+		k_busy_wait(100);
```
Comment (jfischer-no) [inline subsys/sd/sdmmc.c:1005]: Can you archive the same using `k_usleep(int32_t us);`?

Comment (danieldegrasse) [reply subsys/sd/sdmmc.c:1005]: We probably could using `k_usleep`, yes. In my mind the delay here is short enough that k_busy_wait is acceptable, and we don't really want to yield to another thread here, hence why I chose `k_busy_wait`

**Comment by danieldegrasse** [comment]
@asarbs have you been able to test this fix?

**Comment by asarbs** [comment]
Sorry I forgot about this I will take a look on that.

**Comment by asarbs** [comment]
It seams to work in my case

**Review by carlescufi — APPROVED** [review]
