### PR TITLE
net: icmpv4: Drop ICMPv4 packet if ICMP header is NULL

### LINKED ISSUE #6081: echo server crash from corrupt ICMPv4 packet
Defensics test case 7: ICMPv4.Request.RFC792-Echo-Request.ICMP-Echo-Request.icmp-echo-request.element 0x2c0d71f3e7d5dd93

This test case crashes echo server in QEMU.

### PR DESCRIPTION
**Pull request by rmstoi**
This commit fixes the crash of echo_server from malformed ICMPv4 packet.

Fixes #6081

Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>

### CODE REVIEW

File: subsys/net/ip/ipv4.c [hunk 1]
```diff
@@ -143,6 +143,11 @@ static inline enum net_verdict process_icmpv4_pkt(struct net_pkt *pkt,
 
 	icmp_hdr = net_icmpv4_get_hdr(pkt, &hdr);
```
Comment (jukkar) [inline subsys/net/ip/ipv4.c]: Usually we do not have empty line after setting the var and then checking it, so you could remove this extra line here.

**Review by jukkar — CHANGES_REQUESTED** [review]
Looks good, minor nit pick.

File: subsys/net/ip/ipv4.c (hunk 1 above)
Comment (rmstoi) [reply subsys/net/ip/ipv4.c]: Thanks for info. Updated patch pushed.

**Comment by rmstoi** [comment]
Patch amended by removing empty line and pushed.

**Review by jukkar — APPROVED** [review]
