### PR TITLE
Bluetooth: Mesh: Fix various storage clearing related issues

### LINKED ISSUE #12574: Bluetooth: Mesh: 2nd time commissioning configuration details (APP Key) not get saved on SoC flash
Board used for testing : nRF52840_PCA10056
App : samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app

Description:

Let firmware has flash using following commands ...

> nrfjprog --eraseall -f nrf52
> nrfjprog --program zephyr.hex -f nrf52
> nrfjprog --reset -f nrf52

After this. if we do provision & configuration of such Bluetooth Mesh DEVICE then here
everything works fine. Even after reset or power reset firmware could retrieve Mesh
configuration details from persistent storage.

But after this if we do un-provisioning of NODE using smartphone App or
by executing bt_mesh_reset(), then next time onward after device get
newly provision & configure, it does not retrieve all configuration parameters
from SoC persistent storage after device get reset.

(Note: After 2nd time Provisioning & Configuration and before reset everything works perfectly normal)

After power reset, we have to reconnect with every NODE with Provisioner App & reassign App key
to Models. Sometimes even have to reassign Subscription Group address.

### PR DESCRIPTION
**Pull request by jhedberg**
There were several things broken with the clearing of mesh storage, both with redundant "cleared" entries being stored as well as a failure to store proper "cleared" entries for model subscriptions and bindings. This set of patches fixes these things, and also cleans up a bit related logging (which was necessary for successful debugging of this issue).

Fixes #12574

### CODE REVIEW

**Comment by jhedberg** [comment]
@vikrant8051 please test this PR!

File: subsys/bluetooth/host/mesh/cfg_srv.c [hunk 1]
```diff
@@ -1428,6 +1428,7 @@ static void mod_sub_add(struct bt_mesh_model *model,
 
 	if (bt_mesh_model_find_group(mod, sub_addr)) {
 		/* Tried to add existing subscription */
+		BT_DBG("found exisitng subscription");
```
Comment (Vudentz) [inline subsys/bluetooth/host/mesh/cfg_srv.c]: typo: existing

**Review by Vudentz — COMMENTED** [review]
Other than the typo it looks good to me.

File: subsys/bluetooth/host/mesh/cfg_srv.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/mesh/cfg_srv.c]: fixed

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]
LGTM

**Comment by vikrant8051** [comment]
@jhedberg 
Sorry for late replying. I have been on outdoor duty from last few days.
I will back on Saturday. So surely, I will test this PR impact asap because
eagerly waiting for it.

Thanks for considering the mentioned issue.

**Comment by jhedberg** [comment]
@vikrant8051 thanks. Note that I already merged it since I'm confident with my own test results, however it will be good if you can also confirm them. So it's probably most convenient if you just test with latest master branch.
