### PR TITLE
tests: fix unchecked return value in test_net_pkt_basics_of_rw

### LINKED ISSUE #15776: [Coverity CID :198003]Error handling issues in /tests/net/net_pkt/src/main.c
Static code scan issues seen in File: /tests/net/net_pkt/src/main.c
 Category: Error handling issues
 Function: test_net_pkt_basics_of_rw
 Component: Tests
 CID: 198003
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by maxxlife**
Inside function test_net_pkt_basics_of_rw result of function call
net_pkt_read_be16 is not checked which might result performance
of the program and cause errors.

Coverity-CID 198003
Fixes #15776
Signed-off-by: Maksim Masalski maxxliferobot@gmail.com

### CODE REVIEW

File: tests/net/net_pkt/src/main.c [hunk 1]
```diff
@@ -259,7 +259,11 @@ static void test_net_pkt_basics_of_rw(void)
 	/* And re-read the value again */
 	net_pkt_cursor_init(pkt);
 	net_pkt_skip(pkt, 1);
-	net_pkt_read_be16(pkt, &value16);
+	if (net_pkt_read_be16(pkt, &value16) != 0) {
```
Comment (jukkar) [inline tests/net/net_pkt/src/main.c]: Just use proper zassert variant here instead of this check + printk.

**Review by jukkar — CHANGES_REQUESTED** [review]

File: tests/net/net_pkt/src/main.c (hunk 1 above)
Comment (maxxlife) [reply tests/net/net_pkt/src/main.c]: Maybe I'm not clear understand you, but please check my changes again.

Comment (pfalcon) [reply tests/net/net_pkt/src/main.c]: @maxxlife, using zassert_equal() would be even better. Just see the line below for example usage.

**Review by pfalcon — APPROVED** [review]
LGTM, though using zassert_equal() would be better.

**Review by jukkar — APPROVED** [review]
