### PR TITLE
drivers: rtc: pcf8563: Fix year offset conversion

### LINKED ISSUE #103971: drivers: pcf8563: Wrong year offset when setting time.
### Describe the bug

Currently, `tm_hour` in `struct rtc_time` is defined as offset from 1900. But in the pcf8563, when setting time, it convert this offset into raw data directly and send to the RTC chip, but the RTC stores actual year, not the offset.
```
	/* Set weekdays */
	raw_time[5] = timeptr->tm_wday;

	/*Set month */
	raw_time[6] = bin2bcd(timeptr->tm_mon);

	/* Set year */
	raw_time[7] = bin2bcd(timeptr->tm_year);

	/* Write to device */
	ret = i2c_write_dt(&config->i2c, raw_time, sizeof(raw_time));
```

### Steps to reproduce

Call `rtc_set_time()` with approriate value when using PCF8563 rtc.

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by anujpaude1**
The PCF8563 stores years as 2-digit BCD (00-99 for years 2000-2099) as specified in the datasheet (Table 17, section 8.4.7): https://www.nxp.com/docs/en/data-sheet/PCF8563.pdf

However, struct rtc_time uses tm_year as years since 1900 (100-199 for years 2000-2099).

The driver was incorrectly passing tm_year directly to bin2bcd() without conversion, causing:
1. Invalid BCD values to be written (e.g., 0x7E for year 2026)
2. 100-year offset when reading back (year 2026 read as 1926)

Fix by:
- SET: Use modulo 100 to convert tm_year to chip format
- GET: Add 100 to convert chip value back to tm_year

This follows the same pattern as the DS1307 driver (drivers/rtc/rtc_ds1307.c).

Tested in Renode simulation with custom PCF8563 peripheral. All test years (2000, 2026, 2050, 2099) pass with valid BCD values.

Fixes #103971

### CODE REVIEW

**Review by Holt-Sun — APPROVED** [review]

File: drivers/rtc/rtc_pcf8563.c [hunk 1]
```diff
@@ -136,7 +136,7 @@ static int pcf8563_set_time(const struct device *dev, const struct rtc_time *tim
 	raw_time[6] = bin2bcd(timeptr->tm_mon);
 
 	/* Set year */
-	raw_time[7] = bin2bcd(timeptr->tm_year);
+	raw_time[7] = bin2bcd(timeptr->tm_year % 100);
```
Comment (bjarki-andreasen) [inline drivers/rtc/rtc_pcf8563.c:139]: though mathematically correct, `timeptr->tm_year - 100` is computationally faster, since we know the value will be between 100 and 199 (for the lifetime of this rtc atleast). Just like with adding 100 later in the get function

**Review by bjarki-andreasen — APPROVED** [review]

File: drivers/rtc/rtc_pcf8563.c (hunk 1 above)
Comment (anujpaude1) [reply drivers/rtc/rtc_pcf8563.c:139]: My initial thought was also to use `tm_year - 100` since the expected range is 100 to 199. However, after checking other RTC drivers, I noticed they use `% 100`. It seems like a more defensive choice and might help accommodate users who handle the year offset differently, whether using 1900, 2000, or no explicit offset, by simply keeping the last two digits.

This is my first merge, so I really appreciate the feedback and the learning opportunity.
