### PR TITLE
drivers: i2c: mcux: lpi2c: add bus recovery support

### LINKED ISSUE #42574: i2c: No support for bus recovery imx.rt and or timeout on bus busy
**Describe the bug**
Running a simple main loop program that reads out i2c sensor values or controlling an i2c GPIO extender in a loop, causes the i2c peripheral at a non-deterministic time interval to become unresponsive.

Please also mention any information which could help others to understand
the problem you're facing:
 - Target platform teensy41
 - After the bus becomes unresponsive i2c function returns -EIO (-5 Error Input Output) and never recovers from this

**To Reproduce**
1. Simple main loop with the retrieval of sensor values e.g. BME280 or
2. Simple main loop with the writing of outputs of the MCP23017

**Expected behavior**
In theory a perfect working I2C peripheral with no hanging/unresponsive busses. If it still becomes unresponsive a way to recover. E.g. bus recovery function, currently not implemented for the imx.rt.

**Impact**
A none robust working I2C bus is a show stopper

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain GCC GNU 10.3.1
 - Commit tag version 2.7.1

**Additional context**
Only a kernel reboot warm/cold recovers the bus. Not e.g. the shell command i2c recover, since it is not implemented in the imx rt driver.

Issues that are related to this issue:
#4040 with reference to #27715.

The main question is what is the overall structure that is preferred with respect to bus recovery?

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add I2C bus recovery support to the NXP MCUX LPI2C driver. Since the LPI2C peripheral block does not natively support I2C bus recovery, recovery is performed using GPIO bitbanging.

Enable I2C bus recovery for LPI2C4 on the NXP i.MX RT1024 Evaluation Kit and TWR-KE18F development boards to get code coverage.
    
Fixes: #42574

### CODE REVIEW

File: drivers/i2c/Kconfig [hunk 1]
```diff
@@ -107,6 +107,13 @@ config I2C_MCUX_LPI2C
 	help
 	  Enable the mcux LPI2C driver.
 
+config I2C_MCUX_LPI2C_BUS_RECOVERY
+	bool "Bus recovery support"
+	depends on I2C_MCUX_LPI2C && PINCTRL
+	select I2C_BITBANG
+	help
+	  Enable LPI2C driver bus recovery support via GPIO bitbanging.
+
```
Comment (henrikbrixandersen) [inline drivers/i2c/Kconfig:116]: I guess this could be derived from the devicetree as well (if a node has the `scl-gpios` and `sda-gpios` properties and the correct `compatible` we enable the code). What do people think? Kconfig or automatic derived from devicetree?

Comment (trentp-igor) [reply drivers/i2c/Kconfig:116]: Would the dts for most dev kits have these properties added for their default expansion port i2c pinmux?  If it was automatic, there wouldn't be a good way to turn it off.

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 2]
```diff
@@ -202,6 +212,89 @@ static int mcux_lpi2c_transfer(const struct device *dev, struct i2c_msg *msgs,
...
+
+static int mcux_lpi2c_bitbang_get_sda(void *io_context)
+{
+	const struct mcux_lpi2c_config *config = io_context;
+
+	return (gpio_pin_get_dt(&config->sda) != 0);
+}
+
+static int mcux_lpi2c_recover_bus(const struct device *dev)
+{
```
[the remark this answers is not in the document]
Comment (galak) [reply drivers/i2c/i2c_mcux_lpi2c.c:238]: I was wondering if it made sense to pull this into a common place.

File: dts/bindings/i2c/nxp,imx-lpi2c.yaml [hunk 3]
```diff
@@ -18,3 +18,15 @@ properties:
       required: false
       type: int
       description: Bus idle timeout in nanoseconds
+
```
Comment (galak) [inline dts/bindings/i2c/nxp,imx-lpi2c.yaml:21]: Wonder about putting these in a `i2c/gpio-bus-recovery.yaml` so they can be included and common across a number of i2c controllers.

Comment (henrikbrixandersen) [reply dts/bindings/i2c/nxp,imx-lpi2c.yaml:21]: It would be nice to standardize across I2C controller bindings, agreed. The Linux kernel devicetree bindings have these on the top-level: https://www.kernel.org/doc/Documentation/devicetree/bindings/i2c/i2c.txt

How about adding them directly to `i2c-controller.yaml`? That would allow re-using them for `gpio-i2c.yaml` as well. We can exclude them from I2C controller bindings not supporting them, but having them in the top-level forces developers to consider them? I am not sure which would be the best option.

File: drivers/i2c/Kconfig (hunk 1 above)
Comment (henrikbrixandersen) [reply drivers/i2c/Kconfig:116]: The only way to turn it off would then be using an overlay for removing those properties.

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 4]
```diff
@@ -202,6 +212,89 @@ static int mcux_lpi2c_transfer(const struct device *dev, struct i2c_msg *msgs,
...
+	int error = 0;
+
+	if (config->scl.port == NULL || !device_is_ready(config->scl.port)) {
+		LOG_ERR("SCL GPIO not available");
+		return -EIO;
+	}
+
+	if (config->sda.port == NULL || !device_is_ready(config->sda.port)) {
+		LOG_ERR("SDA GPIO not available");
+		return -EIO;
```
Comment (gmarull) [inline drivers/i2c/i2c_mcux_lpi2c.c:257]: nit: maybe `-ENODEV` here

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 5]
```diff
@@ -202,6 +212,89 @@ static int mcux_lpi2c_transfer(const struct device *dev, struct i2c_msg *msgs,
...
+	const struct mcux_lpi2c_config *config = io_context;
+
+	gpio_pin_set_dt(&config->sda, state);
+}
+
+static int mcux_lpi2c_bitbang_get_sda(void *io_context)
+{
+	const struct mcux_lpi2c_config *config = io_context;
+
+	return (gpio_pin_get_dt(&config->sda) != 0);
```
Comment (gmarull) [inline drivers/i2c/i2c_mcux_lpi2c.c:234]: nit: call return type is `int`, but this evaluates to a boolean

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 6]
```diff
@@ -202,6 +212,89 @@ static int mcux_lpi2c_transfer(const struct device *dev, struct i2c_msg *msgs,
...
+	k_sem_take(&data->lock, K_FOREVER);
+
+	error = gpio_pin_configure_dt(&config->scl, GPIO_OUTPUT_HIGH);
+	if (error) {
+		LOG_ERR("failed to configure SCL GPIO (err %d)", error);
+		goto restore;
+	}
+
+	error = gpio_pin_configure_dt(&config->sda, GPIO_OUTPUT_HIGH);
+	if (error != 0) {
```
Comment (gmarull) [inline drivers/i2c/i2c_mcux_lpi2c.c:269]: nit: better be consistent here, `error != 0` or `error < 0` in all cases

File: dts/bindings/i2c/nxp,imx-lpi2c.yaml (hunk 3 above)
Comment (gmarull) [reply dts/bindings/i2c/nxp,imx-lpi2c.yaml:21]: agreed, would be nice to make them to `i2c-controller.yaml`

**Review by gmarull — COMMENTED** [review]
lgtm, please check my comments

File: drivers/i2c/i2c_mcux_lpi2c.c (hunk 4 above)
Comment (henrikbrixandersen) [reply drivers/i2c/i2c_mcux_lpi2c.c:257]: Yeah, except that's not a valid return code for `i2c_recover_bus()`.

File: drivers/i2c/i2c_mcux_lpi2c.c (hunk 5 above)
Comment (henrikbrixandersen) [reply drivers/i2c/i2c_mcux_lpi2c.c]: Fixed, thanks.

File: drivers/i2c/i2c_mcux_lpi2c.c (hunk 6 above)
Comment (henrikbrixandersen) [reply drivers/i2c/i2c_mcux_lpi2c.c]: Fixed, thanks.

File: drivers/i2c/i2c_mcux_lpi2c.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (henrikbrixandersen) [reply drivers/i2c/i2c_mcux_lpi2c.c:238]: Perhaps we could move the GPIO bitbang helper functions to `drivers/i2c/i2c_bitbang.{c,h}` and use them from both `drivers/i2c/i2c_gpio.c` and I2C controller drivers utilizing GPIOs for bus recovery?

File: dts/bindings/i2c/nxp,imx-lpi2c.yaml (hunk 3 above)
Comment (henrikbrixandersen) [reply dts/bindings/i2c/nxp,imx-lpi2c.yaml:21]: Should we use `property-blocklist` for I2C controllers not using them (yet) if we pull them into `i2c-controller.yaml`?

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen interested to know, how are you testing bus recovery with this PR?

You will need to stop an I2C transaction half-way on the bus (typically caused by CPU soft-reboots during an I2C transaction e.g. due to a watchdog timeout), causing an I2C target device to be addressed but without ever seeing a STOP condition. One can manually introduce a START condition and address setup on the I2C bus (external to the controller) and verify that a bus recovery allows communicating with the I2C target again. This is not trivial. We have previously (during verification of 6aa8a836821140614e0a66abb318e2e7c65afd2b) tested this with a buss recovery sequence identical to what is being used here.

An easy way to verify that the bitbanging is working is just to use e.g. the `sensor` shell to communicate with an onboard I2C sensor while monitoring the I2C bus using a logic analyser. Then use the `i2c` shell for triggering a bus recovery, still monitoring the bus, and last - communicate with the sensor again to verify the I2C controller bus function was restored. This will not introduce a situation actually requiring a bus recovery, but it will verify that the bus recovery can be executed correctly without breaking I2C functionality afterwards.

**Review by danieldegrasse — DISMISSED** [review]
@henrikbrixandersen Thanks for the explanation- implementation here looks good to me.

**Review by teburd — DISMISSED** [review]

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 7]
```diff
@@ -202,6 +212,89 @@ static int mcux_lpi2c_transfer(const struct device *dev, struct i2c_msg *msgs,
...
+	struct i2c_bitbang bitbang_ctx;
+	struct i2c_bitbang_io bitbang_io = {
+		.set_scl = mcux_lpi2c_bitbang_set_scl,
+		.set_sda = mcux_lpi2c_bitbang_set_sda,
+		.get_sda = mcux_lpi2c_bitbang_get_sda,
+	};
+	uint32_t bitrate_cfg;
+	int error = 0;
+
+	if (config->scl.port == NULL || !device_is_ready(config->scl.port)) {
```
Comment (gmarull) [inline drivers/i2c/i2c_mcux_lpi2c.c:250]: note: device_is_ready handles a `NULL` input, since this code is not making any distinction, the NULL check here is redundant.

Comment (henrikbrixandersen) [reply drivers/i2c/i2c_mcux_lpi2c.c]: Right, I keep forgetting that. Fixed.

**Review by gmarull — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Review by teburd — APPROVED** [review]
