### PR TITLE
drivers: crypto: crypto_ataes132a fix missing count check

### LINKED ISSUE #81951: [Coverity CID: 434625] Untrusted loop bound in drivers/crypto/crypto_ataes132a.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/drivers/crypto/crypto_ataes132a.c#L122

Category: Insecure data handling
Function: `ataes132a_send_command`
Component: Drivers
CID: [434625](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434625)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/drivers/crypto/crypto_ataes132a.c

```
116    
117      LOG_DBG("COMMAND CRC %x%x", data->command_buffer[count - 2],
118                   data->command_buffer[count - 1]);
119      LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
120    
121      /* If CRC fails retry reading MAX RETRIES times */
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 1" as an index into an array "data->command_buffer".
122      while (crc[0] != data->command_buffer[count - 2] ||
123             crc[1] != data->command_buffer[count - 1]) {
124              if (retry_count > MAX_RETRIES - 1) {
125                      LOG_ERR("response crc validation rebase"
126                                  " max retries");
127                      return -EINVAL;
116    
117      LOG_DBG("COMMAND CRC %x%x", data->command_buffer[count - 2],
118                   data->command_buffer[count - 1]);
119      LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
120    
121      /* If CRC fails retry reading MAX RETRIES times */
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 1" as an index into an array "data->command_buffer".
122      while (crc[0] != data->command_buffer[count - 2] ||
123             crc[1] != data->command_buffer[count - 1]) {
124              if (retry_count > MAX_RETRIES - 1) {
125                      LOG_ERR("response crc validation rebase"
126                                  " max retries");
127                      return -EINVAL;
132              count = data->command_buffer[0];
133    
134              ataes132a_atmel_crc(data->command_buffer, count -  2, crc);
135              retry_count++;
136    
137              LOG_DBG("COMMAND RETRY %d", retry_count);
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 1" as an index into an array "data->command_buffer".
138              LOG_DBG("COMMAND CRC %x%x",
139                          data->command_buffer[count - 2],
140                          data->command_buffer[count - 1]);
141              LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
142              }
143    
111    
112      count = data->command_buffer[0];
113    
114      /* Calculate and validate response CRC */
115      ataes132a_atmel_crc(data->command_buffer, count - 2, crc);
116    
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 1" as an index into an array "data->command_buffer".
117      LOG_DBG("COMMAND CRC %x%x", data->command_buffer[count - 2],
118                   data->command_buffer[count - 1]);
119      LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
120    
121      /* If CRC fails retry reading MAX RETRIES times */
122      while (crc[0] != data->command_buffer[count - 2] ||
132              count = data->command_buffer[0];
133    
134              ataes132a_atmel_crc(data->command_buffer, count -  2, crc);
135              retry_count++;
136    
137              LOG_DBG("COMMAND RETRY %d", retry_count);
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 2" as an index into an array "data->command_buffer".
138              LOG_DBG("COMMAND CRC %x%x",
139                          data->command_buffer[count - 2],
140                          data->command_buffer[count - 1]);
141              LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
142              }
143    
146                          data->command_buffer[1]);
147              return -EIO;
148      }
149    
150      LOG_DBG("Read the response count: %d", count);
151    
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 3" as a loop boundary.
152      for (i = 0; i < count - 3; i++) {
153              response[i] = data->command_buffer[i + 1];
154      }
155    
156      *nresponse = count - 3;
157    
128              }
129    
130              burst_read_i2c(&cfg->i2c, ATAES_COMMAND_MEM_ADDR, data->command_buffer, 64);
131    
132              count = data->command_buffer[0];
133    
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Passing tainted expression "count - 2" to "ataes132a_atmel_crc", which uses it as a loop boundary.
134              ataes132a_atmel_crc(data->command_buffer, count -  2, crc);
135              retry_count++;
136    
137              LOG_DBG("COMMAND RETRY %d", retry_count);
138              LOG_DBG("COMMAND CRC %x%x",
139                          data->command_buffer[count - 2],
116    
117      LOG_DBG("COMMAND CRC %x%x", data->command_buffer[count - 2],
118                   data->command_buffer[count - 1]);
119      LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
120    
121      /* If CRC fails retry reading MAX RETRIES times */
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 2" as an index into an array "data->command_buffer".
122      while (crc[0] != data->command_buffer[count - 2] ||
123             crc[1] != data->command_buffer[count - 1]) {
124              if (retry_count > MAX_RETRIES - 1) {
125                      LOG_ERR("response crc validation rebase"
126                                  " max retries");
127                      return -EINVAL;
128              }
129    
130              burst_read_i2c(&cfg->i2c, ATAES_COMMAND_MEM_ADDR, data->command_buffer, 64);
131    
132              count = data->command_buffer[0];
133    
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Passing tainted expression "count - 2" to "ataes132a_atmel_crc", which uses it as a loop boundary.
134              ataes132a_atmel_crc(data->command_buffer, count -  2, crc);
135              retry_count++;
136    
137              LOG_DBG("COMMAND RETRY %d", retry_count);
138              LOG_DBG("COMMAND CRC %x%x",
139                          data->command_buffer[count - 2],
109      /* Read the response */
110      burst_read_i2c(&cfg->i2c, ATAES_COMMAND_MEM_ADDR, data->command_buffer, 64);
111    
112      count = data->command_buffer[0];
113    
114      /* Calculate and validate response CRC */
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Passing tainted expression "count - 2" to "ataes132a_atmel_crc", which uses it as a loop boundary.
115      ataes132a_atmel_crc(data->command_buffer, count - 2, crc);
116    
117      LOG_DBG("COMMAND CRC %x%x", data->command_buffer[count - 2],
118                   data->command_buffer[count - 1]);
119      LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
120    
111    
112      count = data->command_buffer[0];
113    
114      /* Calculate and validate response CRC */
115      ataes132a_atmel_crc(data->command_buffer, count - 2, crc);
116    
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 2" as an index into an array "data->command_buffer".
117      LOG_DBG("COMMAND CRC %x%x", data->command_buffer[count - 2],
118                   data->command_buffer[count - 1]);
119      LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
120    
121      /* If CRC fails retry reading MAX RETRIES times */
122      while (crc[0] != data->command_buffer[count - 2] ||
128              }
129    
130              burst_read_i2c(&cfg->i2c, ATAES_COMMAND_MEM_ADDR, data->command_buffer, 64);
131    
132              count = data->command_buffer[0];
133    
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Passing tainted expression "count - 2" to "ataes132a_atmel_crc", which uses it as a loop boundary.
134              ataes132a_atmel_crc(data->command_buffer, count -  2, crc);
135              retry_count++;
136    
137              LOG_DBG("COMMAND RETRY %d", retry_count);
138              LOG_DBG("COMMAND CRC %x%x",
139                          data->command_buffer[count - 2],
146                          data->command_buffer[1]);
147              return -EIO;
148      }
149    
150      LOG_DBG("Read the response count: %d", count);
151    
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 3" as a loop boundary.
152      for (i = 0; i < count - 3; i++) {
153              response[i] = data->command_buffer[i + 1];
154      }
155    
156      *nresponse = count - 3;
157    
146                          data->command_buffer[1]);
147              return -EIO;
148      }
149    
150      LOG_DBG("Read the response count: %d", count);
151    
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 3" as a loop boundary.
152      for (i = 0; i < count - 3; i++) {
153              response[i] = data->command_buffer[i + 1];
154      }
155    
156      *nresponse = count - 3;
157    
116    
117      LOG_DBG("COMMAND CRC %x%x", data->command_buffer[count - 2],
118                   data->command_buffer[count - 1]);
119      LOG_DBG("CALCULATED CRC %x%x", crc[0], crc[1]);
120    
121      /* If CRC fails retry reading MAX RETRIES times */
>>>     CID 434625:    (TAINTED_SCALAR)
>>>     Using tainted variable "count - 2" as an index into an array "data->command_buffer".
122      while (crc[0] != data->command_buffer[count - 2] ||
123             crc[1] != data->command_buffer[count - 1]) {
124              if (retry_count > MAX_RETRIES - 1) {
125                      LOG_ERR("response crc validation rebase"
126                                  " max retries");
127                      return -EINVAL;
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_TAINTED_SCALAR). ([CWE-606](http://cwe.mitre.org/data/definitions/606.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434625

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by ljd42**
Coverity reported an untrusted loop bound caused by a missing check on the count value in ataes132a_send_command() for the response received from the device.  As per datasheet section 6.1, count should be at least 3 bytes (1 byte for count, and 2 bytes for the 16 bits CRC).

While I'm expecting this condition to be very rare, it doesn't hurt to implement a proper checking and report an error if count<3.

Coverity CID: 434625

Fixes: #81951

### CODE REVIEW

File: drivers/crypto/crypto_ataes132a.c [hunk 1]
```diff
@@ -110,6 +110,12 @@ static int ataes132a_send_command(const struct device *dev, uint8_t opcode,
 	burst_read_i2c(&cfg->i2c, ATAES_COMMAND_MEM_ADDR, data->command_buffer, 64);
 
 	count = data->command_buffer[0];
+	/* validate count: at least 3 bytes (1 for count, 2 for CRC) */
+	if (count < 3) {
+		LOG_ERR("invalid packet received: count=%d"
+			" , expects count>=3", count);
+		return -EINVAL;
+	}
```
Comment (valeriosetti) [inline drivers/crypto/crypto_ataes132a.c:118]: there is a pretty similar count reading at [line 138](https://github.com/zephyrproject-rtos/zephyr/blob/2d1ef5f1e2fff5623cabbaa8570dba7b225474c6/drivers/crypto/crypto_ataes132a.c#L138C3-L138C35). Shouldn't we add/replicate the check also there?

**Review by valeriosetti — CHANGES_REQUESTED** [review]

File: drivers/crypto/crypto_ataes132a.c (hunk 1 above)
Comment (ceolin) [reply drivers/crypto/crypto_ataes132a.c:118]: It seems ...

Comment (ljd42) [reply drivers/crypto/crypto_ataes132a.c:118]: @valeriosetti , @ceolin : yes, correct.

**Review by valeriosetti — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
