### PR TITLE
libc: minimal: add missing ctype.h functions

### LINKED ISSUE #99452: libc: minimal: missing ctype.h functions `isblank()`, `islower()`, and `ispunct()`
### Describe the bug

The minimal libc is missing `isblank()` (C99), `islower()` (C89), and `ispunct()` (C89).

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. apply the following diff
```diff
diff --git a/samples/hello_world/src/main.c b/samples/hello_world/src/main.c
index c550ab461cb..d0f1f87de30 100644
--- a/samples/hello_world/src/main.c
+++ b/samples/hello_world/src/main.c
@@ -4,11 +4,12 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
+#include <ctype.h>
 #include <stdio.h>
 
 int main(void)
 {
        printf("Hello World! %s\n", CONFIG_BOARD_TARGET);
 
-       return 0;
+       return isblank('x') || islower('X') || ispunct('x');
 }
```
2. `west build -p auto -b qemu_riscv64 samples/hello_world -- -DCONFIG_MINIMAL_LIBC=y -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y`
3. See error

### Relevant log output

```shell
ZEPHYR_BASE/samples/hello_world/src/main.c:14:16: error: implicit declaration of function 'isblank' [-Werror=implicit-function-declaration]
   14 |         return isblank('x') || islower('X') || ispunct('x');
      |                ^~~~~~~
ZEPHYR_BASE/samples/hello_world/src/main.c:14:32: error: implicit declaration of function 'islower'; did you mean 'tolower'? [-Werror=implicit-function-declaration]
   14 |         return isblank('x') || islower('X') || ispunct('x');
      |                                ^~~~~~~
      |                                tolower
ZEPHYR_BASE/samples/hello_world/src/main.c:14:48: error: implicit declaration of function 'ispunct' [-Werror=implicit-function-declaration]
   14 |         return isblank('x') || islower('X') || ispunct('x');
      |                                                ^~~~
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- OS: any
- Toolchain: Zephyr SDK v0.17.4
- Commit SHA or Version used: `v4.3.0`

### Additional Context

Blocks #97400 (in terms of testing), #55186

### PR DESCRIPTION
**Pull request by cfriedt**
Add the functions below to the minimal libc `ctype.h` since they are missing, and are required as of C89 (C99 for `isblank()`)

* `isblank()`
* `islower()`
* `ispunct()`

Fixes #99452

### CODE REVIEW

**Comment by cfriedt** [comment]
* Added `Compliance: False Positive` because the coding style follows what is currently in the file

File: lib/libc/minimal/include/ctype.h [hunk 1]
```diff
@@ -23,6 +23,11 @@ static inline int isalpha(int c)
 	return (int)((((unsigned)c|32u)-(unsigned)'a') < 26U);
 }
 
+static inline int isblank(int c)
+{
+	return (int)((c == (int)' ') || (c == (int)'\t'));
+}
+
 static inline int isspace(int c)
```
Comment (keith-packard) [inline lib/libc/minimal/include/ctype.h:34]: I'd let the compiler do something cute if it likes, but express these in a direct fashion.
```
static inline int isspace (int c)
{
    return c == ' ' || ('\t' <= c && c <= '\r');
}
```
Similarly for the other functions. There's no reason to obscure what these functions do; having to check that there are 5 'blank' values between `'\t'` and `'\r'` is something the compiler should do, not us.

**Review by keith-packard — CHANGES_REQUESTED** [review]
Please express these directly rather than using arithmetic.

File: lib/libc/minimal/include/ctype.h (hunk 1 above)
Comment (cfriedt) [reply lib/libc/minimal/include/ctype.h:34]: I'll prepend a commit for that, since it's technically not related to the bugfix.

Comment (cfriedt) [reply lib/libc/minimal/include/ctype.h:34]: I could also prepend a commit that would eliminate linter issues as well (and fix up the commit I added).

File: lib/libc/minimal/include/ctype.h [hunk 2]
```diff
@@ -15,42 +15,57 @@ extern "C" {
 
 static inline int isupper(int a)
 {
-	return (int)(((unsigned)(a)-(unsigned)'A') < 26U);
+	return (int)(((int)'A' <= a) && (a <= (int)'Z'));
```
Comment (keith-packard) [inline lib/libc/minimal/include/ctype.h]: You don't need any casts in this expression -- character constants are of type int, the relational operators result is of type int and the logical AND operator result is of type int. This should be just `return 'A' <= a && a <= 'Z';`
Feel free to add parentheses if you like, they aren't required as the precedence works correctly for this case.

File: lib/libc/minimal/include/ctype.h [hunk 3]
```diff
@@ -15,42 +15,57 @@ extern "C" {
...
 
 static inline int isxdigit(int a)
 {
-	unsigned int ua = (unsigned int)a;
+	if (isdigit(a) != 0) {
+		return 1;
+	}
+
+	/* force to lowercase */
+	a |= 32U;
```
Comment (keith-packard) [inline lib/libc/minimal/include/ctype.h]: tolower uses addition instead of bitwise OR; I'd be consistent here.

**Review by keith-packard — CHANGES_REQUESTED** [review]
Please remove all of the unnecessary casts; C is at least semi-reasonable for these cases.

File: lib/libc/minimal/include/ctype.h (hunk 2 above)
Comment (cfriedt) [reply lib/libc/minimal/include/ctype.h]: Some casts were added a years ago for misra compliance.

https://github.com/zephyrproject-rtos/zephyr/commit/1556fce8454136afeb0f55c7f506cd903ff10842

@ceolin do you know if there was a diversity associated with this?

I also wonder if there was some concern over C++ char literals being implicitly cast to int.

File: lib/libc/minimal/include/ctype.h (hunk 3 above)
Comment (cfriedt) [reply lib/libc/minimal/include/ctype.h]: Sure - I'm fine to use addition.

Comment (cfriedt) [reply lib/libc/minimal/include/ctype.h]: Scratch that - it causes tests to fail.
https://github.com/zephyrproject-rtos/zephyr/actions/runs/19507606132/job/55838595241?pr=99451

Specifically because addition will not force an already lowercase value to be lowercase, but it moves it out of the range of lowercase characters. Bitwise OR will cause an uppercase value to be lowercase and does not modify already-lowercase characters.

Reproducible with
```shell
twister -c -i -p native_sim -s libraries.libc.common.minimal
```

File: lib/libc/minimal/include/ctype.h (hunk 2 above)
Comment (cfriedt) [reply lib/libc/minimal/include/ctype.h]: I tested with several invocations of gcc g++ clang and clang++ as well as building with west and twister, and did not encounter any warnings.

I don't have access to coverity, and it's unclear what tool caused issues that triggered the flags reported in 1556fce8454136afeb0f55c7f506cd903ff10842.

My assumption is that @keith-packard's change request will not trigger MISRA warnings.

I have left brackets in, since that is a pretty typical practice to adhere to [Rule 14.4](https://gitlab.com/MISRA/MISRA-C/MISRA-C-2012/Example-Suite/-/blob/master/R_14_04.c).

**Review by keith-packard — APPROVED** [review]

**Review by aescolar — COMMENTED** [review]
The code is ok, but minimallibc is not meant to be complete
https://docs.zephyrproject.org/latest/develop/languages/c/minimal_libc.html
only to have this subset:
https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#rule-a-4-c-standard-library-usage-restrictions-in-zephyr-kernel
Anyhow, I'm not specially against adding these. 
@stephanosio can decide.

**Review by jhedberg — APPROVED** [review]
