### PR TITLE
bluetooth: host: Save id when allocating CCC cfg slot

### LINKED ISSUE #15508: No space to store CCC cfg
**Describe the bug**
When using multiple identities device can experience `No space to store CCC cfg` after reconnection.
When CCC cfg lookup is done address and id (identity) is checked. The problem is when `bt_gatt_attr_write_ccc` obtains a new slot it is not storing information about the identity. This quickly leads to draining the available slots when switching between peers connected using different identities.

**To Reproduce**
1. Build with multiple identities.
2. On each identity connect to one peer.
3. Switch between peers.

**Expected behavior**
There should be enough CCC cfg slots to handle all connections.

**Impact**
Showstopper for the projects using multiple identities and gatt.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
ncs zephyr: `a288e8b8ab54c667c6ed9776042200411710a9cf` (from `06ab394` upstream)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pdunaj**
Make sure that along with address identity is saved too.

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

Fixes: #15508

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1094,6 +1094,7 @@ ssize_t bt_gatt_attr_write_ccc(struct bt_conn *conn,
 		}
 
 		bt_addr_le_copy(&cfg->peer, &conn->le.dst);
+		cfg->id = conn->id;
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c]: We might need to update ccc_find_cfg since that apparently don't match the id.

Comment (pdunaj) [reply subsys/bluetooth/host/gatt.c]: Possibly. This will require more changes as `ccc_save` does not carry id.

Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: It is encoded in the key, check bt_gatt_store_ccc

Comment (pdunaj) [reply subsys/bluetooth/host/gatt.c]: I will try to add changes needed. Will update PR when done.

Comment (pdunaj) [reply subsys/bluetooth/host/gatt.c]: Should be done

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -3147,8 +3154,12 @@ static int bt_gatt_clear_ccc(u8_t id, const bt_addr_le_t *addr)
 				       (bt_addr_le_t *)addr, NULL);
 	}
 
+	struct addr_with_id addr_with_id = {
+		.addr = addr,
+		.id = id,
+	};
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c]: iirc it is against the codying style to declare a variable in the middle of a function/statement scope, at least in Bluetooth we don't do that.

File: subsys/bluetooth/host/gatt.c [hunk 3]
```diff
@@ -1553,6 +1553,7 @@ static u8_t disconnected_cb(const struct bt_gatt_attr *attr, void *user_data)
 			/* Clear value if not paired */
 			if (!bt_addr_le_is_bonded(conn->id, &conn->le.dst)) {
 				bt_addr_le_copy(&cfg->peer, BT_ADDR_LE_ANY);
+				cfg->id = 0U;
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c]: I suggest we move these to something like:
static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
{
    	bt_addr_le_copy(&cfg->peer, BT_ADDR_LE_ANY);
	cfg->id = 0U;
	cfg->value = 0U;
        memset(cfg->data, 0, sizeof(cfg->data));
}

Or just memset the entire thing since that appear to do the same thing.

File: subsys/bluetooth/host/gatt.c (hunk 2 above)
Comment (pdunaj) [reply subsys/bluetooth/host/gatt.c]: I checked it before and there is no coding standard that would forbid it. I will however change it if you like to match the style of other files in bluetooth.

Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Id prefer we keep the declaration in the beginning, at least I don't see anything against doing it and we keep the code a little bit more 'organized'.

Comment (pdunaj) [reply subsys/bluetooth/host/gatt.c]: Fixed

File: subsys/bluetooth/host/gatt.c (hunk 3 above)
Comment (pdunaj) [reply subsys/bluetooth/host/gatt.c]: Fixed

File: subsys/bluetooth/host/gatt.c [hunk 4]
```diff
@@ -3373,8 +3393,7 @@ static int cf_set(int argc, char **argv, void *val_ctx)
 
 		BT_DBG("Read CF: len %d", len);
 	} else {
-		bt_addr_le_copy(&cfg->peer, BT_ADDR_LE_ANY);
-		memset(cfg->data, 0, sizeof(cfg->data));
+		clear_cf_cfg(cfg);
```
Comment (pdunaj) [inline subsys/bluetooth/host/gatt.c]: it seems to be clear of `cf_cfg` so I am calling the right clear function

File: subsys/bluetooth/host/gatt.c (hunk 3 above)
Comment (pdunaj) [reply subsys/bluetooth/host/gatt.c]: I used `clear_ccc_cfg` as `BT_ADDR_LE_ANY` is defined outside and may change in the future.

**Comment by jhedberg** [comment]
Is this something you'd want backported to the 1.14 branch?

**Comment by pdunaj** [comment]
> Is this something you'd want backported to the 1.14 branch?

Hi @jhedberg , from our point of view this is not important. We use the current master.

**Review by jhedberg — APPROVED** [review]

**Comment by pdunaj** [comment]
Hi @Vudentz , @carlescufi , could we merge this and do the upmerge to ncs?

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]
