### PR TITLE
Bluetooth: Shell: Fix off-by-one in address length validation

### LINKED ISSUE #45072: [Coverity CID: 248346] Copy into fixed size buffer in /subsys/bluetooth/shell/bt.c
Static code scan issues seen in File: /subsys/bluetooth/shell/bt.c
Category: Copy into fixed size buffer
Function: cmd_scan_filter_set_addr
Component: Bluetooth
CID: 248346
Please fix or provide comments to square it off in Coverity in the link: https://scan9.scan.coverity.com/reports.htm#v45144/p12996/fileInstanceId=90886360&defectInstanceId=8695719&mergedDefectId=248346

### PR DESCRIPTION
**Pull request by alwa-nordic**
Fixes Coverity defect id 248346.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/45072.

Signed-off-by: Aleksander Wasaznik <aleksander.wasaznik@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/shell/bt.c [hunk 1]
```diff
@@ -1048,8 +1048,8 @@ static int cmd_scan_filter_set_addr(const struct shell *sh, size_t argc,
 {
 	const char *addr_arg = argv[1];
 
-	/* Validate length */
-	if (strlen(addr_arg) > sizeof(scan_filter.addr)) {
+	/* Validate length including null terminator. */
+	if ((strlen(addr_arg) + 1) != sizeof(scan_filter.addr)) {
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:1052]:
```suggestion
	if ((strlen(addr_arg) >= sizeof(scan_filter.addr)) {
```

It should not be `!=` as the filter supports partial address, e.g. you can use `aa:bb:cc` as your address filter

**Review by Thalley — CHANGES_REQUESTED** [review]
Can you post the issue reported by coverity?

**Comment by alwa-nordic** [comment]
I manually created an issue: https://github.com/zephyrproject-rtos/zephyr/issues/45072. I could not find one by zephyrbot.

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
