### PR TITLE
openthread/drivers: ieee802154: nRF 5: network subsystem unified timestamps

### LINKED ISSUE #59245: net: l2: ieee802154: radio: inconsistent/non-standard definition of RX/TX timestamp
**Describe the bug**

The current IEEE 802.15.4 driver API and OpenThread define the RX/TX timestamps as "the first symbol of the MAC Header" (net_pkt.h, line 102).

But **this point in time is not what the standard suggests as RX/TX timestamp** (see IEEE 802.15.4-2020, section 8.3.4, table 8-90, Timestamp) - see details below in "Expected Behavior". Such a point in time cannot be used for synchronization purposes outside L2 without leaking implementation details of the PHY, see OpenThread workaround below as an example.

**The two current drivers supporting RX timestamps implement this timestamp inconsistently:**
* nRF5 calculates a non-standard timestamp at the beginning of the MHR header internally from the end of the packet timestamp.
* DW1000 uses the standard's well-defined synchronization anchor (end of SFD aka RMARKER)

The **OpenThread** platform API historically used the start of MAC as its RX timestamp (see @edmont's comment below) but has since turned to the standard definition (see include/openthread/platform/radio.h) "The value SHALL be the time when the SFD was received" (line 209f) and uses it in practice **precisely as the standard would define it with a value of macSyncSymbolOffset == 0**, see radio.c, line 189: "OpenThread expects the timestamp to point to the end of SFD".

The IEEE 802.15.4 driver API is based on OpenThread's previous definition, which is not used anywhere anymore. A workaround in radio.c had to be implemented that assumes a specific PHY (which is ok for Open Thread due to its limited choice of PHYs but not for other protocols built above L2 with arbitrary PHYs). The workaround in radio.c can easily be fixed (see below) to improve PHY/MAC encapsulation of the OT stack plus turn to the standard definition for all drivers and other L2 stacks.

**To Reproduce**

n/a (architecture issue)

**Expected behavior**

**All drivers and call sites should use a common standard conforming concept of RX/TX timestamp.**

The IEEE 802.15.4 standard (and OpenThread) define as time synchronization anchor for all PHYs (equivalently):
* the end of the start-of-frame delimiter (SFD) field
* the end of the synchronization header (SHR)
* the start of the PHY header
* the RMARKER (IEEE 802.15.4-2020, section 6.9.1)

This is to be measured at the exact moment when this signal is present at the local antenna. Signal propagation delays between the antenna and the timestamp counter must be corrected for by the hardware and/or firmware.

This unique synchronization anchor is then referred to everywhere in the standard (e.g. synchronization with beacons, RSSI measurements, timestamping of received and transmitted frames, synchronization of CCA, ranging, etc.).

More specifically: RX and TX timestamps are defined to be measured relative to the end of the SFD, offset by a hardware specific constant parameter macSyncSymbolOffset (section 8.4.3.1, table 8-94) which L2 requests from the driver to calculate the exact synchronization point if required.

As the current radio API does not report the driver's macSyncSymbolOffset constant, **the most obvious definition for any RX or TX timestamp would be the end of the SFD** (i.e. drivers correct for their own offset as if their macSyncSymbolOffset was zero). This is the same definition that has been chosen by the OpenThread platform API.

**The implementation of this for the RX timestamp is simple (and will be provided as PR by myself if the solution is accepted)**:
* Move the nRF5/PHY-specific workaround in radio.c into the nRF5 driver where it belongs architecturally.
* Change the documentation in net_pkt.h so that the timestamp is defined as in the standard assuming macSyncSymbolOffset == 0.

Alternatively macSyncSymbolOffset would have to be reported as a constant attribute by drivers implementing any of the \*TIME\* capabilities. As macSyncSymbolOffset does not have much use other than saving a few cycles on RX, I would go with the OpenThread solution for now to keep it simple.

**TX timestamping must be analyzed separately and is not in scope for this bug report.**

**Impact**

A common concept of timestamping on the RX and TX path is required for TSCH (and other timing sensitive features in the IEEE 802.15.4 standard, like CSL, ranging, etc.) no matter the PHY, band, channel, etc. chosen.

So fixing this is a pre-condition for TSCH implementation.

**Logs and console output**

n/a

**Environment (please complete the following information):**

n/a

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by ghost**
Hi @edmont, @jciupis, here comes the change set that corresponds to the changes proposed in OpenThread (https://github.com/openthread/openthread/pull/9322) as well as the recent additions to the nRF5 HAL/driver (https://github.com/zephyrproject-rtos/hal_nordic/commit/0d68181c95c749a41cc81e1d858072313887583d and https://github.com/zephyrproject-rtos/hal_nordic/pull/136).

This PR closes #59245.

~~TODO: This change set must include the corresponding openthread/hal_nordic commit SHAs in west.yml which are not yet known, therefore DNM in its current state but already may be reviewed.~~

~~@jciupis Please let me know which SHA I should include for the nRF5 HAL (if any), I think you made more additions there in the meantime and maybe nothing needs to be changed in west.yaml at all as far as nRF5 HAL is concerned as the changes needed for this PR have already made it into zephyr?~~

UPDATE: nRF5 HAL is already at the right version - no need to change west.yml, see comments below.

UPDATE: The changes depending on OpenThread have been isolated in another PR, see #61430 so that this PR can be merged.

@edmont You've already tested this on hardware and I've not changed anything since except for rebases. Threfore I assume that the CSL TX timestamps and RX windows are still correct, but I hope you can do a last review anyways once the final version (with the openthread SHA in west.yml) is ready so we're really sure.

~~@vaishnavachath The only change I made to the CC13/26xx driver is that I moved a generally useful constant to the general header file so it becomes available to the nRF5 driver as well.~~

UPDATE: The change to CC13/26xx turned out to be unnecessary and was reverted, see comments below.

### CODE REVIEW

File: modules/openthread/platform/radio.c [hunk 1]
```diff
@@ -237,6 +237,84 @@ void handle_radio_event(const struct device *dev, enum ieee802154_event evt,
...
+	 * overdue as well. In order to determine what's the case and correctly
+	 * set the absolute (non-wrapped) target time, it's necessary to compare
+	 * the least significant 32 bits of the current 64-bit network subsystem
+	 * time with the provided 32-bit target time. Let's assume that half of
+	 * the 32-bit range can be used for specifying target times in the
+	 * future, and the other half - in the past.
+	 */
+	uint64_t now_us = otPlatTimeGet();
+	uint32_t now_us_wrapped = (uint32_t)now_us;
+	uint32_t time_diff = target_time_us_wrapped - now_us_wrapped;
```
Comment (ssharks) [inline modules/openthread/platform/radio.c:268]: Maybe convert to int32_t here for making the further comparisons easier

**Review by ssharks — COMMENTED** [review]
There is a lot of fiddling with time and values that are prone to overflowing. It is hard to spot all the corner cases. Please attempt to make them functions wherever possible, so there are fewer places where coding errors can be wrong. Preferably test the known corner cases in a unit test. This might rewriting the functions a bit in order to make them unit testable.

File: modules/openthread/platform/radio.c (hunk 1 above)
Comment (fgrandel) [reply modules/openthread/platform/radio.c:268]: @edmont @jciupis I think @ssharks suggestions are probably more in your direction as I'm just moving over existing code and wouldn't be able to write unit tests or refactor that code as I'm not 100% sure about the detailed requirements driving that function.

**Comment by fgrandel** [comment]
> Preferably test the known corner cases in a unit test.

@ssharks Many thanks for your review! I actually did add a lot of coverage and preparative work before touching this code, see the changes prefixed with "test" in this preparative PR: https://github.com/zephyrproject-rtos/zephyr/pull/60401/commits I agree that we could have even more test coverage, especially unit tests for corner cases. Unfortunately I couldn't do more, time wouldn't allow. But at least we do have some coverage for these features now. :-)

File: modules/openthread/platform/radio.c (hunk 1 above)
Comment (ssharks) [reply modules/openthread/platform/radio.c:268]: To me more precise
```suggestion
	int32_t time_diff = (int32_t)(target_time_us_wrapped - now_us_wrapped);
```

File: modules/openthread/platform/radio.c [hunk 2]
```diff
@@ -237,6 +237,84 @@ void handle_radio_event(const struct device *dev, enum ieee802154_event evt,
...
+	uint64_t result = UINT64_C(0);
+
+	if (time_diff < 0x80000000) {
```
Comment (ssharks) [inline modules/openthread/platform/radio.c:271]: Then here you can use:
```suggestion
	if (time_diff > 0) {
```

Comment (fgrandel) [reply modules/openthread/platform/radio.c]: Thanks @ssharks , added as https://github.com/zephyrproject-rtos/zephyr/pull/60946/commits/305c9b398f13e3a5fb7864fb271fa7e4c9eb6104 so that the suggestions can be reviewed.

File: drivers/ieee802154/ieee802154_nrf5.c [hunk 3]
```diff
@@ -598,8 +527,13 @@ static bool nrf5_tx_at(struct nrf5_802154_data *nrf5_radio, struct net_pkt *pkt,
...
 #endif
 	};
-	uint64_t tx_at = target_time_convert_to_64_bits(net_ptp_time_to_ns(net_pkt_timestamp(pkt)));
 
+	/* The timestamp points to the start of PHR but `nrf_802154_transmit_raw_at`
+	 * expects a timestamp pointing to start of SHR.
+	 */
+	uint64_t tx_at = net_ptp_time_to_ns(net_pkt_timestamp(pkt)) / NSEC_PER_USEC;
+
+	tx_at -= NRF5_SHR_DURATION_US;
```
Comment (jciupis) [inline drivers/ieee802154/ieee802154_nrf5.c:536]: No need to add this symbol. I think [this function](https://github.com/zephyrproject-rtos/hal_nordic/blob/master/drivers/nrf_802154/driver/include/nrf_802154.h#L451) can be used instead.

**Review by jciupis — COMMENTED** [review]
@fgrandel there's no need to update hal_nordic revision in west.yml, the necessary changes are already on main.

File: drivers/ieee802154/ieee802154_nrf5.c (hunk 3 above)
Comment (fgrandel) [reply drivers/ieee802154/ieee802154_nrf5.c:536]: Doh! Of course - sorry, that was some leftover from prior iterations. Fixed.

**Review by rlubos — COMMENTED** [review]
Looks reasonable

**Review by cfriedt — DISMISSED** [review]
Nice! Looking forward to we can see network precision time making its way into Zephyr and applications 😁

**Comment by fgrandel** [comment]
@edmont @jciupis As the OT community seems to take considerable time to make up their mind whether consistent TX/RX timestamps are a good thing on their side, I now prepared this PR as an intermediate step that isolates the inconsistent timestamp definition in the OT adaptation layer on the Zephyr side. I also prepared a second PR (#61430) that will synchronize with OT iif they decide to move to consistent timestamps as well.

File: modules/openthread/platform/radio.c [hunk 4]
```diff
@@ -58,6 +58,8 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME, CONFIG_OPENTHREAD_L2_LOG_LEVEL);
 
 #define CHANNEL_COUNT OT_RADIO_2P4GHZ_OQPSK_CHANNEL_MAX - OT_RADIO_2P4GHZ_OQPSK_CHANNEL_MIN + 1
 
+#define PHY_SHR_DURATION 160; /* duration of SHR in us */
```
Comment (edmont) [inline modules/openthread/platform/radio.c:61]:
```suggestion
#define PHY_SHR_DURATION 160 /* duration of SHR in us */
```

**Review by edmont — APPROVED** [review]

File: modules/openthread/platform/radio.c (hunk 4 above)
Comment (fgrandel) [reply modules/openthread/platform/radio.c]: Fixed. Thanks for your review!

**Review by jciupis — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
LGTM
