### PR TITLE
STM32WB55  BLE not working

### LINKED ISSUE #75318: Zephyr 3.7 RC2 BLE on  STM32 Nucleo WB55 does not work
**Describe the bug**
I am using Zephyr 3.7 RC2 but the issue is vissible also with 3.7 RC1.
I am trying if everything still works for the STM32WB55 device. I am using STM32 Nucleo WB55. 
I checked radio firmware stm32wb5x_BLE_HCILayer_fw.bin in version 1.18.0 from STM32WB Copro Wireless Binaries.
The issue is visible with the radio version 1.19.1 and also with the firmware file stm32wb5x_BLE_HCILayer_extended_fw.bin.
Demos with BLE do not work on STM32 Nucleo WB55. I have also my own application but also demo iBeacon does not work.

The issue seems coming from the bt_ipm_ble_init function.

It was working with Zephyr 3.4 when I last checked. 

**To Reproduce**
Have radio firmware loaded with radio fw.
Build the "zephyr/samples/bluetooth/ibeacon" demo for -DBOARD=nucleo_wb55rg flash and run.

**Expected behavior**
Working demo and visible iBeacon node on BLE scanner. 

**Impact**
BLE on STM32 Nucleo WB55 does not work.

**Logs and console output**
When I read the log I got the below report:

```
*** Booting Zephyr OS build v3.7.0-rc1-588-g40810983ead2 ***
Starting iBeacon Demo
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x080094f4  r1/a2:  0x20002ac8  r2/a3:  0x00080000
E: r3/a4:  0x00000000 r12/ip:  0x20000224 r14/lr:  0x080035b1
E:  xpsr:  0x20000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 35: Unknown error on CPU 0
E: Current thread: 0x20000490 (unknown)
E: Halting system
```

**Environment (please complete the following information):**
Linux Debian 11
CMake version: 3.21.0
Zephyr version: 3.7.0-rc2
west 1.2.0
host-tools: zephyr 0.16.1 
toolchain: zephyr 0.16.1

### PR DESCRIPTION
**Pull request by asm5878**
Implementing and enabling HCI setup function to have a correct and proper
initialization procedure to fix #75318 issue

### CODE REVIEW

File: drivers/bluetooth/hci/Kconfig [hunk 1]
```diff
@@ -63,6 +63,7 @@ config BT_STM32_IPM
 	depends on DT_HAS_ST_STM32WB_RF_ENABLED
 	select USE_STM32_HAL_CORTEX
 	select HAS_STM32LIB
+	select BT_HCI_SET_PUBLIC_ADDR
```
Comment (jhedberg) [inline drivers/bluetooth/hci/Kconfig:66]: Shouldn't this be `select BT_HCI_SETUP`? I don't see you taking advantage of `setup_params.public_addr` anywhere in the driver.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 2]
```diff
@@ -68,6 +68,10 @@ struct aci_set_ble_addr {
 	uint8_t value[6];
 } __packed;
 
+#if defined(CONFIG_BT_HCI_SETUP)
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c:71]: Since you're unconditionally selecting this option (currently indirectly by selecting `BT_HCI_SET_PUBLIC_ADDR`), there's no way that the driver could get built without it, i.e. you should be able to remove all the `#if defined(CONFIG_BT_HCI_SETUP)` stuff.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Looks generally fine - just a few fine-tuning proposals.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 3]
```diff
@@ -68,6 +68,10 @@ struct aci_set_ble_addr {
...
+static int bt_ipm_setup(const struct device *dev, const struct bt_hci_setup_params *params);
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c:72]: It doesn't look like you need this forward declaration. The calls to the function seem to be after the function definition anyway.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 4]
```diff
@@ -565,16 +569,26 @@ static int bt_ipm_open(const struct device *dev, bt_hci_recv_t recv)
...
+
+	LOG_DBG("IPM Channel Open Completed");
+
+	return 0;
+}
+
+static int bt_ipm_setup(const struct device *dev, const struct bt_hci_setup_params *params)
+{
+	ARG_UNUSED(params);
+	int err;
```
Comment (erwango) [inline drivers/bluetooth/hci/ipm_stm32wb.c:582]:
```suggestion
	int err;

	ARG_UNUSED(params);
	ARG_UNUSED(dev);
```

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 3 above)
Comment (erwango) [inline drivers/bluetooth/hci/ipm_stm32wb.c:72]: Is this forward declaration actually required ?

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 5]
```diff
@@ -613,6 +627,9 @@ static const struct bt_hci_driver_api drv = {
 	.close          = bt_ipm_close,
 #endif
 	.send           = bt_ipm_send,
+#if defined(CONFIG_BT_HCI_SETUP)
+	.setup = bt_ipm_setup,
```
Comment (erwango) [inline drivers/bluetooth/hci/ipm_stm32wb.c:631]: Please follow structure indentation scheme.

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/Kconfig (hunk 1 above)
Comment (asm5878) [reply drivers/bluetooth/hci/Kconfig:66]: Agree with you

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 2 above)
Comment (asm5878) [reply drivers/bluetooth/hci/ipm_stm32wb.c:71]: Indeed, good remark

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 3 above)
Comment (asm5878) [reply drivers/bluetooth/hci/ipm_stm32wb.c:72]: Yes, indeed it's useless

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 4 above)
Comment (asm5878) [reply drivers/bluetooth/hci/ipm_stm32wb.c:582]: Yes, Let's do it for all the unused params

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 3 above)
Comment (asm5878) [reply drivers/bluetooth/hci/ipm_stm32wb.c:72]: no, useless, indeed

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 5 above)
Comment (asm5878) [reply drivers/bluetooth/hci/ipm_stm32wb.c:631]: yes, thanks

**Review by jhedberg — APPROVED** [review]

**Comment by asm5878** [comment]
Thanks a lot for your comments.
PR updated.

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
