### PR TITLE
drivers: ethernet: nxp_enet: Handle -ENOTSUP for fixed-link in phy_co…

### LINKED ISSUE #87237: NXP_ENET driver initialization fails with fixed link phy_mii
**Describe the bug**
On our custom board with the NXP RT1061 microcontroller, we use `ENET2` as the Ethernet controller. The board includes a switch that requires no additional configuration, so I set the `fixed-link` property in the device tree as follow:
```
&enet2_mac {
	status = "okay";
	pinctrl-0 = <&pinmux_enet2>;
	pinctrl-names = "default";
	phy-handle = <&phy>;
	phy-connection-type = "rmii";
	zephyr,random-mac-address;
};

&enet2_mdio {
	status = "okay";
	pinctrl-0 = <&pinmux_enet2_mdio>;
	pinctrl-names = "default";
	phy: phy@0 {
		compatible = "ethernet-phy";
		reg = <0>;
		status = "okay";
		fixed-link = "100BASE-T Full-Duplex";
	};
};
```

However, during initialization, `eth_nxp_enet_init` calls `nxp_enet_phy_init`, which executes `phy_mii_cfg_link`, attempting MDIO read/write operations despite the `fixed-link` configuration. This results in an `EIO` error, causing the `NXP_ENET` driver to fail.

**Expected behavior**
The Ethernet driver should successfully initialize without attempting MDIO operations when the link is configured as a fixed link.

**Impact**
The Ethernet initialization fails, preventing the board from using the Ethernet connection, which impacts network functionality.

**Environment (please complete the following information):**

 - OS: Windows
 - Toolchain: Zephyr SDK
 - Branch `v4.1`

### PR DESCRIPTION
**Pull request by ofirshe**
Modified nxp_enet_phy_configure to handle -ENOTSUP returned by the PHY driver, indicating a fixed-link setup. If -ENOTSUP is returned, a warning is logged, and PHY configuration is skipped without causing initialization to fail.

depends on [87238](https://github.com/zephyrproject-rtos/zephyr/pull/87238)
Fixes [87237](https://github.com/zephyrproject-rtos/zephyr/issues/87237)

### CODE REVIEW

File: drivers/ethernet/eth_nxp_enet.c [hunk 1]
```diff
@@ -461,14 +461,23 @@ static int nxp_enet_phy_configure(const struct device *phy, uint8_t phy_mode)
...
 	   (phy_mode == NXP_ENET_RGMII_MODE), (0))) {
 		speeds |= (LINK_HALF_1000BASE_T | LINK_FULL_1000BASE_T);
 	}
 
 	/* Configure the PHY */
-	return phy_configure_link(phy, speeds);
+	ret = phy_configure_link(phy, speeds);
+
+	if (ret == -ENOTSUP) {
+		LOG_WRN("PHY driver returned -ENOTSUP, fixed-link detected.");
```
Comment (decsny) [inline drivers/ethernet/eth_nxp_enet.c:475]: I think we don't assume why did the phy return not supported, instead maybe the logic here in the case of not supported should get the link state, and if it is up, log that something unusual happened and maybe report link state /speed, and if it is down, treat it like an error

Comment (ofirshe) [reply drivers/ethernet/eth_nxp_enet.c]: Done

File: drivers/ethernet/eth_nxp_enet.c [hunk 2]
```diff
@@ -461,14 +461,37 @@ static int nxp_enet_phy_configure(const struct device *phy, uint8_t phy_mode)
...
+
+	if (ret == -ENOTSUP) {
+		phy_get_link_state(phy, &state);
+
+		if (state.is_up) {
+			LOG_WRN("phy_configure_link returned -ENOTSUP, but link is up. "
+				"Speed: %s, %s-duplex",
+				PHY_LINK_IS_SPEED_1000M(state.speed) ? "1 Gbits" :
+				PHY_LINK_IS_SPEED_100M(state.speed) ? "100 Mbits" :
+													  "10 Mbits",
```
Comment (maass-hamburg) [inline drivers/ethernet/eth_nxp_enet.c:483]:
```suggestion
				PHY_LINK_IS_SPEED_100M(state.speed) ? "100 Mbits" : "10 Mbits",
```

Comment (ofirshe) [reply drivers/ethernet/eth_nxp_enet.c]: Fixed

**Review by maass-hamburg — APPROVED** [review]

File: drivers/ethernet/eth_nxp_enet.c [hunk 3]
```diff
@@ -461,14 +461,36 @@ static int nxp_enet_phy_configure(const struct device *phy, uint8_t phy_mode)
...
+				PHY_LINK_IS_SPEED_100M(state.speed) ? "100 Mbits" : "10 Mbits",
+				PHY_LINK_IS_FULL_DUPLEX(state.speed) ? "full" : "half");
+		} else {
+			LOG_ERR("phy_configure_link returned -ENOTSUP and link is down.");
+			return -ENETDOWN;
+		}
+	} else if (ret) {
+		LOG_ERR("phy_configure_link failed with error: %d", ret);
+		return ret;
+	}
```
Comment (decsny) [inline drivers/ethernet/eth_nxp_enet.c:491]: this is a final nitpick but I prefer to see code that has lest nesting like:

```c
if (ret == -ENOTSUP && !state.is_up) {
...
} else if (ret == -ENOTSUP) {
..
} else  if (ret) {
...
}

return 0;
```

maybe it doesn't seem like a big deal here but in general I just think it's more understandable and easy to read through

Comment (ofirshe) [reply drivers/ethernet/eth_nxp_enet.c:491]: If I follow your approach, it would require always reading the link state, whereas in the current solution, phy_get_link_state is only invoked when ret == -ENOTSUP. This means adding unnecessary latency in most drivers, except for phy_mii with a fixed link. In most cases, this issue won't occur, so the current approach keeps overhead minimal.

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet.c:491]: okay, it's fine in this case I think anyways

**Review by decsny — APPROVED** [review]
