### PR TITLE
Bluetooth: host: don't fragment ISO if len <= MTU

### LINKED ISSUE #56749: Bluetooth: Host: SDU fragmented when ISO Tx MTU equals Controller's ISO Tx Buffer Size
**Describe the bug**
> Observations
To allow 251 bytes of ISO payload over the HCI interface the CONFIG_BT_CTLR_ISO_TX_BUFFER_SIZE needs to be set to a value higher than 251 bytes (as that is the value returned in read_buffer_size_v2). but the name suggests the HCI buffer limit is also used as ISO TX limit, which seems odd and wrong - the MAX ISO TX PDU is 251 bytes.
If this value is set to 251 it forces the host to fragment the 251 byte ISO data payload and thereby use 2 credits per ISO PDU.

Refer to https://github.com/zephyrproject-rtos/zephyr/issues/52055#issue-1439858139

Using a `CONFIG_BT_ISO_TX_MTU=40` and `CONFIG_BT_CTLR_ISO_TX_BUFFER_SIZE=40`, after couple PDUs transmitted over air, no more PDUs are transmitted. SDU is fragment into multiple HCI ISO Data.

In the HCI specification, Data_Total_Length, which can be less than or equal to ISO_Data_Packet_Length returned by the controller, excludes the packet header. Hence, ISO Tx MTU size of 40 bytes shall not be fragmented when ISO Tx buffer size returned by Controller is 40 bytes.

image

**To Reproduce**
1. mkdir -p build/broadcast_audio_source; cd build/broadcast_audio_source
2. cmake -GNinja -DBOARD=nrf52_bsim -DCONFIG_BT_ISO_TX_MTU=40 -DCONFIG_BT_CTLR_ISO_TX_BUFFER_SIZE=40 -DCONFIG_BT_CTLR_ADV_ISO_PDU_LEN_MAX=40 -DCONFIG_BT_CTLR_ADV_ISO_STREAM_MAX=2 -DCONFIG_BT_CTLR_ISOAL_SOURCES=2 ../../samples/bluetooth/broadcast_audio_source
3. ninja
4. ./zephyr/zephyr.exe -s=iso -d=0 &
5. ~/bsim/bin/bs_2G4_phy_v1 -s=iso -D=1 -sim_length=2e6
6. Observe the PDUs transmitted by analysing the babblesim exported trace

**Expected behavior**
SDU shall not be fragmented when ISO Tx MTU equals Controller's ISO Tx Buffer Size.

**Impact**
showstopper

**Logs and console output**

[Broadcast_audio_source_40_40.zip](https://github.com/zephyrproject-rtos/zephyr/files/11208195/Broadcast_audio_source_40_40.zip)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: b76bd15

**Additional context**
None

### PR DESCRIPTION
**Pull request by jori-nordic**
MTU doesn't count against the ISO and ISO data headers.

Then a config with CONFIG_BT_ISO_TX_MTU ==
CONFIG_BT_CTLR_ISO_TX_BUFFER_SIZE should not fragment SDUs over HCI.

Also set the TS_Flag bit if a timestamp is present.

Fixes #56749

### CODE REVIEW

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -681,6 +713,24 @@ static struct net_buf *create_frag(struct bt_conn *conn, struct net_buf *buf)
...
+{
+	size_t iso_hdr;
+
+	if (IS_ENABLED(CONFIG_BT_ISO) && conn->type == BT_CONN_TYPE_ISO) {
+		if (tx_data(buf)->iso_has_ts) {
+			iso_hdr = BT_HCI_ISO_TS_DATA_HDR_SIZE;
+		} else {
+			iso_hdr = BT_HCI_ISO_DATA_HDR_SIZE;
+		}
+		return (buf->len - iso_hdr) <= conn_mtu(conn);
```
Comment (cvinayak) [inline subsys/bluetooth/host/conn.c:726]:
```suggestion
		}

		return (buf->len - iso_hdr) <= conn_mtu(conn);
```

File: subsys/bluetooth/host/conn.c [hunk 2]
```diff
@@ -690,7 +740,7 @@ static int send_buf(struct bt_conn *conn, struct net_buf *buf)
 	LOG_DBG("conn %p buf %p len %u", conn, buf, buf->len);
 
 	/* Send directly if the packet fits the ACL MTU */
-	if (buf->len <= conn_mtu(conn) && !tx_data(buf)->is_cont) {
+	if (fits_single_ctlr_buf(buf, conn) && !tx_data(buf)->is_cont) {
```
Comment (cvinayak) [inline subsys/bluetooth/host/conn.c:743]: should `while (buf->len > conn_mtu(conn)) {` below in line 758 be fixed?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/conn.c (hunk 2 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/conn.c:743]: actually I think it should be fine: it's only the first fragment that has the data header (that doesn't count against the conn_mtu). 
So as long as the controller doesn't set its TX size to 0 (ie the mtu >= data hdr size) then this will work as expected.

But you're right that something is awry: the length of the data copied in `send_frag` doesn't take the header into account, now I fixed it too.

File: subsys/bluetooth/host/conn.c [hunk 3]
```diff
@@ -410,6 +412,28 @@ static struct bt_conn_tx *conn_tx_alloc(void)
...
+	int err = bt_conn_send_cb(conn, buf, cb, NULL);
+
+	if (err) {
+		return err;
+	}
+
+	/* We need a tx context to do the op below. We always allocate one if
+	 * `cb` is set.
+	 */
+	__ASSERT_NO_MSG(cb);
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/conn.c:427]: Isn't it better to check for the stated requirement?

```suggestion
	__ASSERT_NO_MSG(tx_data(buf)->tx);
```

Also, the comment does not make sense to me. What is the "the op below"? (Preemptive argument: It seems to me that the new code in this PR only cares about `tx_data(buf)->iso_has_ts`. That is valid memory even if `tx_data(buf)->tx` is `NULL`, so the requirement commented/asserted here is not true, right?)

**Review by alwa-nordic — DISMISSED** [review]

File: samples/bluetooth/unicast_audio_client/src/main.c [hunk 4]
```diff
@@ -28,7 +28,8 @@ static struct audio_sink {
 } sinks[CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT];
 static struct bt_bap_ep *sources[CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SRC_COUNT];
 NET_BUF_POOL_FIXED_DEFINE(tx_pool, CONFIG_BT_BAP_UNICAST_CLIENT_ASE_SNK_COUNT,
-			  CONFIG_BT_ISO_TX_MTU + BT_ISO_CHAN_SEND_RESERVE, 8, NULL);
+			  CONFIG_BT_ISO_TX_MTU + BT_ISO_CHAN_SEND_RESERVE,
```
Comment (Thalley) [inline samples/bluetooth/unicast_audio_client/src/main.c:31]: Outside the scope of this PR, but as far as I can tell, `BT_ISO_SDU_BUF_SIZE(CONFIG_BT_ISO_TX_MTU)` and `CONFIG_BT_ISO_TX_MTU + BT_ISO_CHAN_SEND_RESERVE` is the same, and should probably be updated to use `BT_ISO_SDU_BUF_SIZE(CONFIG_BT_ISO_TX_MTU)` everywhere :)

File: subsys/bluetooth/host/conn.c [hunk 5]
```diff
@@ -52,6 +52,8 @@ struct tx_meta {
 	 * continuations).
 	 */
 	bool is_cont;
+	/* Indicates whether the ISO PDU contains a timestamp */
+	bool iso_has_ts;
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:56]: Should guard with `CONFIG_BT_ISO`

File: subsys/bluetooth/host/conn.c [hunk 6]
```diff
@@ -512,8 +535,12 @@ static int send_iso(struct bt_conn *conn, struct net_buf *buf, uint8_t flags)
 	}
 
 	hdr = net_buf_push(buf, sizeof(*hdr));
-	hdr->handle = sys_cpu_to_le16(bt_iso_handle_pack(conn->handle, flags,
-							 0));
+
+	ts = tx_data(buf)->iso_has_ts &&
+		(flags == BT_ISO_START || flags == BT_ISO_SINGLE);
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:540]: Is there any spec requirements that state that we cannot send the TS to the controller for e.g. `BT_ISO_CONT`?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/conn.c (hunk 5 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/conn.c:56]: yeah I did that previously, then had to litter the code with ifdefs and IS_ENABLED because of the stone-age language that we use.

Then I noticed that the struct size doesn't actually change, so I left it always in.
An alternative would be converting both to be bits in a bitfield.

File: subsys/bluetooth/host/conn.c (hunk 6 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/conn.c:540]: yes
image

File: samples/bluetooth/unicast_audio_client/src/main.c (hunk 4 above)
Comment (jori-nordic) [reply samples/bluetooth/unicast_audio_client/src/main.c:31]: I only found two, if you know of other places, I can change them too.

File: subsys/bluetooth/host/conn.c (hunk 5 above)
Comment (Thalley) [reply subsys/bluetooth/host/conn.c:56]: > Then I noticed that the struct size doesn't actually change, so I left it always in.

That's a fair argument for now, but if someone later needs to add more, then at some point it will increase in size, and then someone with no knowledge of ISO may have to start guarding all the accesses for ISO. I won't block the PR based on this, but this may end up being some technical debt if we don't do it now. 

> An alternative would be converting both to be bits in a bitfield.

That would be a good approach, as we can more easily expand this without increasing size.

**Review by Thalley — DISMISSED** [review]
No blocking comments

**Comment by jori-nordic** [comment]
@cvinayak could you take another look?

File: subsys/bluetooth/audio/shell/bap.c [hunk 7]
```diff
@@ -168,7 +168,7 @@ static uint16_t get_next_seq_num(uint32_t interval_us)
 
 #if defined(CONFIG_LIBLC3)
 NET_BUF_POOL_FIXED_DEFINE(sine_tx_pool, CONFIG_BT_ISO_TX_BUF_COUNT,
-			  CONFIG_BT_ISO_TX_MTU + BT_ISO_CHAN_SEND_RESERVE,
+			  BT_ISO_SDU_BUF_SIZE(CONFIG_BT_ISO_TX_MTU),
 			  8, NULL);
```
Comment (cvinayak) [inline subsys/bluetooth/audio/shell/bap.c:172]:
```suggestion
			  BT_ISO_SDU_BUF_SIZE(CONFIG_BT_ISO_TX_MTU),
			  CONFIG_BT_CONN_TX_USER_DATA_SIZE, NULL);
```

**Review by cvinayak — CHANGES_REQUESTED** [review]
Would you change `CONFIG_BT_CTLR_ISO_TX_BUFFER_SIZE` that has +8 in samples and tests have the +8 removed?

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/audio/shell/bap.c (hunk 7 above)
Comment (jori-nordic) [reply subsys/bluetooth/audio/shell/bap.c:172]: done, can you take another look?

Comment (cvinayak) [reply subsys/bluetooth/audio/shell/bap.c:172]: Did you push? i till see use of `8`...

Comment (jori-nordic) [reply subsys/bluetooth/audio/shell/bap.c]: dang I did all of the others and this one slipped. Should be changed now

**Review by alwa-nordic — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
