### PR TITLE
userspace: reduce CI userspace testing to tests that use it and fix some network tests

### LINKED ISSUE #15103: nrf52810_pca10040 SRAM space not enough
**Describe the bug**
it seems nrf52810_pca10040 SRAM space is not enough for current version. It fails on link stage. 

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52810_pca10040  ..
3. ninja

**Screenshots or console output**

for case tests/kernel/sched/preempt on platform nrf52810_pca10040
Memory region         Used Size  Region Size  %age Used
           FLASH:       63104 B       192 KB     32.10%
            SRAM:         25 KB        24 KB    104.17%
        IDT_LIST:          56 B         2 KB      2.73/opt/zephyr-sdk-0.10/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: zephyr/zephyr_prebuilt.elf section `priv_stacks_noinit' will not fit in region `SRAM'
/opt/zephyr-sdk-0.10/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: section .intList VMA [0000000020006000,0000000020006037] overlaps section priv_stacks_noinit VMA [0000000020003800,00000000200063ff]
/opt/zephyr-sdk-0.10/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: region `SRAM' overflowed by 1024 bytes
collect2: error: ld returned 1 exit status

for case tests/kernel/poll on platform nrf52810_pca10040
-sdk-0.10/arm-zephyr-eabi/bin/arm-zephyr-eabi-objdump -S zephyr.elf > zephyr.lst && /opt/zephyr-sdk-0.10/arm-zephyr-eabi/bin/arm-zephyr-eabi-readelf -e zephyr.elf > zephyr.stat
/opt/zephyr-sdk-0.10/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: zephyr/zephyr.elf section `priv_stacks_noinit' will not fit in region `SRAM'
/opt/zephyr-sdk-0.10/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: region `SRAM' overflowed by 2048 bytes

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain (Zephyr SDK, 0.10.0)
 - Commit SHA 193fb971c24f827464982307b5b3bb34de0fa98d

### LINKED ISSUE #15227: sockets: no syscall for gethostname()
the test tests/net/socket/misc test has userspace intentionally disabled and crashes if you turn it on.
all BSD socket APIs must be runnable from user mode.

### LINKED ISSUE #15228: tests: getnameinfo runs with user mode disabled
tests/net/socket/getnameinfo has CONFIG_TEST_USERSPACE=n set in its prj.conf

This is despite the fact that it tries to run the test in user mode, and works just fine.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
- CONFIG_TEST_USERSPACE is now off by default. It should be enabled for any test that tries to put a thread in user mode (K_USER option to k_thread_create()). A special assertion has been added to enforce this. This should *greatly* decrease CI build times.

- Missing system call for gethostname() added.

- The getnameinfo() test case now runs in user mode as intended.

- tests/kernel/poll uses a lot less RAM by recycling stack/thread objects

Fixes: #15228 
Fixes: #15227 
Partial fix for: #8559 (we eventually need to look into making gen_kobject_list.py faster)
Fixes: #15103

### CODE REVIEW

File: tests/kernel/poll/src/test_poll.c [hunk 1]
```diff
@@ -15,11 +15,16 @@ struct fifo_msg {
 
 #define SIGNAL_RESULT 0x1ee7d00d
 #define FIFO_MSG_VALUE 0xdeadbeef
+#define STACK_SIZE (1024 + CONFIG_TEST_EXTRA_STACKSIZE)
```
Comment (andyross) [inline tests/kernel/poll/src/test_poll.c]: I've done similar stuff in other tests to fold stacks together.  Maybe we should have some kind of ztest framework for this or something.

File: kernel/thread.c [hunk 2]
```diff
@@ -433,6 +433,12 @@ k_tid_t z_impl_k_thread_create(struct k_thread *new_thread,
 {
 	__ASSERT(!z_is_in_isr(), "Threads may not be created in ISRs");
 
+	/* Special case, only for unit tests */
+#if defined(CONFIG_TEST) && defined(CONFIG_ARCH_HAS_USERSPACE) && !defined(CONFIG_USERSPACE)
+	__ASSERT((options & K_USER) == 0,
+		 "Platform is capable of user mode, and test thread created with K_USER option, but CONFIG_TEST_USERSPACE or CONFIG_USERSPACE is not set\n");
```
Comment (andyross) [inline kernel/thread.c]: Wouldn't it be cleaner to just make it a general assertion if the caller asks for K_USER but the kernel can't accommodate?  Or do we document that as a valid noop?  Seems like there's nothing really test-specific about this validation other than the reason it was added.

**Review by andyross — APPROVED** [review]
Makes sense.  A few nitpicks.

File: kernel/thread.c (hunk 2 above)
Comment (andrewboie) [reply kernel/thread.c]: For general usage, it's valid to disable userspace and still use things like K_USER or other related APIs. They are no-ops.

However, just for tests, we want to tighten this up as if someone is dropping a test to user mode in a test case, but forgets to set CONFIG_TEST_USERSPACE, it will not silently just run everything in user mode.

We could consider making this a general assertion, but I am hesitant to do this here.

**Review by nashif — APPROVED** [review]

**Review by ulfalizer — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by marc-hb** [comment]
Some tests have `CONFIG_TEST_USERSPACE=y` but no `userspace` sanitycheck tag.
For other tests it's the other way round.
Should they be in sync?

Because they're in unrelated locations (`prj.conf` versus sanitycheck's .yaml file) it's unrealistic to keep them in sync all the time. On the other hand it should be easy for sanitycheck to automagically set CONFIG_TEST_USERSPACE=y  when the userspace tag is set. Would that be acceptable? "Reverse" demo:
```shell
   sanitycheck --extra-args=CONFIG_TEST_USERSPACE=n \
    -p qemu_x86 -T tests/kernel/mem_protect/stackprot/
```

Random "out of sync" examples found with `git grep` + a fair amount of elbow grease:
```
test_build_gpio
test_build_sensors_*
getaddrinfo/net.socket
tests/kernel/lifo/lifo_usage/kernel.lifo.usage
tests/kernel/mem_protect/mem_protect/kernel.memory_protection
...
```

**Comment by andrewboie** [comment]
> CONFIG_TEST_USERSPACE=y when the userspace tag is set. Would that be acceptable? 

NACK

the test will not function if you run it outside of sanitycheck, do not split the the configuration like this

**Comment by marc-hb** [comment]
I found another, semi-automated way to check for inconsistencies between CONFIG_TEST_USERSPACE and "userspace". See PR #16466
