### PR TITLE
drivers: udc_nrf: Do not submit buffer more than once

### LINKED ISSUE #84664: USB: device_next: `buf_release_cb` may be called with `NULL` buffer
Rarely, when `usbd_uac2_send` is called, the `uac2_ops.buf_release_cb` may be called an additional time with the buffer set to `NULL`. If an application implements the callback like 

```c
static void uac2_buf_release_cb(const struct device *dev, uint8_t terminal, void *buf,
				void *user_data)
{
	k_mem_slab_free(&usb_out_buf_pool, buf);
}
```

Then this will fail as calling `k_mem_slab_free` with `NULL` is invalid behavior. The callback is not described as ever giving a `NULL` buffer, but what is more odd is that it is called an additional time with NULL. 

**To Reproduce**
1. Build and flash the sample from https://github.com/zephyrproject-rtos/zephyr/pull/84359 for `nrf5340_audio_dk/nrf5340/cpuapp` with `CONFIG_ASSERT=y`
2. Build and flash the sample from https://github.com/zephyrproject-rtos/zephyr/pull/84553 for `nrf5340_audio_dk/nrf5340/cpuapp`
3. See error (usually in the first few seconds). 

Step 1 can alternatively also be done on the nRF52840DK, and built as 
```
west build -b nrf52840dk/nrf52840 -- -DEXTRA_CONF_FILE=overlay-bt_ll_sw_split.conf -DCONFIG_ASSERT=y
```

**Expected behavior**
Expect `uac2_ops.buf_release_cb` to never be called with `NULL`, or that is documented to happened for some reason. 

**Impact**
Easy workaround is to add checks in the application for `NULL`

**Logs and console output**
`uac2_sof_cb` logs the address of the buffer before calling `usbd_uac2_send` and `uac2_buf_release_cb` logs the address of the buffer from the callback arguments. 

It can be seen that `uac2_sof_cb` calls `usbd_uac2_send` 2 times, but `uac2_buf_release_cb` is called 3 times; 2 times with the expected buffer addresses and once with `0`/`NULL`. 
```
[00:00:13.711,608] <err> usb: uac2_sof_cb: 0x20012020
[00:00:13.711,730] <err> udc_nrf: udc_event_xfer_in_next: ep 0x88 nrfx error: bad000b
[00:00:13.711,822] <err> usb: uac2_buf_release_cb: 0x20011f60
[00:00:13.711,914] <err> usb: uac2_sof_cb: 0x20011f60
[00:00:13.712,005] <err> usbd_uac2: uac2_request: request ep 0x88, len 192 failed
[00:00:13.712,005] <err> usb: uac2_buf_release_cb: 0x20012020
[00:00:13.712,127] <err> usb: uac2_buf_release_cb: 0
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/kernel/mem_slab.c:273
        Invalid memory pointer provided
[00:00:13.712,219] <err> os: esf_dump: r0/a1:  0x00000004  r1/a2:  0x00000111  r2/a3:  0x0000012a
[00:00:13.712,249] <err> os: esf_dump: r3/a4:  0x00000004 r12/ip:  0x00000014 r14/lr:  0x00027c91
[00:00:13.712,280] <err> os: esf_dump:  xpsr:  0x01000000
[00:00:13.712,341] <err> os: esf_dump: s[ 0]:  0x20001928  s[ 1]:  0x00000000  s[ 2]:  0x2000ecb0  s[ 3]:  0x20009ff0
[00:00:13.712,371] <err> os: esf_dump: s[ 4]:  0x2000ecb0  s[ 5]:  0x00000088  s[ 6]:  0x00033b5c  s[ 7]:  0x00002959
[00:00:13.712,402] <err> os: esf_dump: s[ 8]:  0x200136fc  s[ 9]:  0x00002929  s[10]:  0x2000ecc8  s[11]:  0x0000b80d
[00:00:13.712,432] <err> os: esf_dump: s[12]:  0x00000000  s[13]:  0xe000ed00  s[14]:  0x20004d30  s[15]:  0xffffff88
[00:00:13.712,463] <err> os: esf_dump: fpscr:  0x000000c0
[00:00:13.712,493] <err> os: esf_dump: Faulting instruction address (r15/pc): 0x0002cfb0
[00:00:13.712,524] <err> os: z_fatal_error: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:13.712,585] <err> os: z_fatal_error: Current thread: 0x20004180 (usbd)
[00:00:15.541,870] <err> os: k_sys_fatal_error_handler: Halting system
```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows): Arch Linux
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.17.0
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/84359 on 4455cd7351ba2990aa6cb44bc09803b154d4a3f5

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by tmon-nordic**
When the UDC buffer gets submitted it should no longer reside in the endpoint queue. While this commit does not address the underlying issue of not being able to start transfer for whatever reason, it prevents the problem from cascading into buffer double completion (e.g. receive buffer double free in UAC2).

Fix: #84664

### CODE REVIEW

**Review by Thalley — APPROVED** [review]

File: drivers/usb/udc/udc_nrf.c [hunk 1]
```diff
@@ -116,7 +116,6 @@ static void udc_event_xfer_in_next(const struct device *dev, const uint8_t ep)
 		if (err != NRFX_SUCCESS) {
 			LOG_ERR("ep 0x%02x nrfx error: %x", ep, err);
 			/* REVISE: remove from endpoint queue? ASSERT? */
-			udc_submit_ep_event(dev, buf, -ECONNREFUSED);
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_nrf.c:119]: As noted in the comment above, remove the buffer from the endpoint queue and return it to the stack. Do not remove `udc_submit_ep_event(dev, buf, -ECONNREFUSED);`. The same goes for the line below.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/udc/udc_nrf.c (hunk 1 above)
Comment (tmon-nordic) [reply drivers/usb/udc/udc_nrf.c:119]: The problem is that this code path happens because there is no proper synchronization. The buffer is in fact used by the DMA when this problem happens.

**Review by jfischer-no — APPROVED** [review]
