### PR TITLE
Zephyr 2.0.0 rc1 coverity fixes for tests/arch/arm

### LINKED ISSUE #18353: [Coverity CID :203522]Null pointer dereferences in /arch/arm/core/cortex_m/fault.c
Static code scan issues seen in File: /arch/arm/core/cortex_m/fault.c
 Category: Null pointer dereferences
 Function: FaultHandle
 Component: Architectures
 CID: 203522
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #18426: [Coverity CID :203455]Incorrect expression in /tests/arch/arm/arm_ramfunc/src/arm_ramfunc.c
Static code scan issues seen in File: /tests/arch/arm/arm_ramfunc/src/arm_ramfunc.c
 Category: Incorrect expression
 Function: test_arm_ramfunc
 Component: Tests
 CID: 203455
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #18427: [Coverity CID :203392]Incorrect expression in /tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c
Static code scan issues seen in File: /tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c
 Category: Incorrect expression
 Function: alt_thread_entry
 Component: Tests
 CID: 203392
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #18428: [Coverity CID :203479]Incorrect expression in /tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c
Static code scan issues seen in File: /tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c
 Category: Incorrect expression
 Function: test_arm_thread_swap
 Component: Tests
 CID: 203479
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #18429: [Coverity CID :203525]Incorrect expression in /tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c
Static code scan issues seen in File: /tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c
 Category: Incorrect expression
 Function: alt_thread_entry
 Component: Tests
 CID: 203525
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #18430: [Coverity CID :203540]Incorrect expression in /tests/arch/arm/arm_zero_latency_irqs/src/arm_zero_latency_irqs.c
Static code scan issues seen in File: /tests/arch/arm/arm_zero_latency_irqs/src/arm_zero_latency_irqs.c
 Category: Incorrect expression
 Function: test_arm_zero_latency_irqs
 Component: Tests
 CID: 203540
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by ioannisg**
Coverity fixes for tests/arch/arm (minor) and one relatively important fix on arch/arm/core/cortex_m/fault.c

Fixes #18426
Fixes #18430
Fixes #18429 
Fixes #18427 
Fixes #18428 
Fixes #18353

### CODE REVIEW

File: tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c [hunk 1]
```diff
@@ -231,7 +234,7 @@ static void alt_thread_entry(void)
 	 * later, that it is populated properly.
 	 */
 	memset(&ztest_thread_fp_callee_saved_regs,
-		0, sizeof(_callee_saved_t));
+		0, sizeof(struct _preempt_float));
```
Comment (pabigot) [inline tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c]: Why not `sizeof(ztest_thread_fp_callee_saved_regs)` so everybody knows what's going on, and it's robust against changes at the definition?

**Review by pabigot — COMMENTED** [review]
I'm not adamant about the proposed change, but it would be more clear.

**Review by MaureenHelm — APPROVED** [review]

File: tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c (hunk 1 above)
Comment (ioannisg) [reply tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c]: Sure. I've updated that, now, @pabigot 
Thanks

**Review by pabigot — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
