### PR TITLE
samples: Bluetooth: Add CAP AD for TMAP peripheral

### LINKED ISSUE #59687: samples: Bluetooth: TMAP peripheral missing CAP service data
**Describe the bug**
The https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/tmap_peripheral sample does not advertise CAP Acceptor service data, which is mandatory to be spec compliant. 

**To Reproduce**
N/A

**Expected behavior**
The sample should be spec compliant and advertise the CAP Acceptor service data as defined by CAP v1.0 table 8.1

**Impact**
None

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: e216dcfc3d430a42bf71d97a5f60d8756d67ec7a

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
The TMAP peripheral sample was missing the CAP announcement service data.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/59687

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

File: samples/bluetooth/tmap_peripheral/src/main.c [hunk 1]
```diff
@@ -12,6 +12,7 @@
 #include <zephyr/sys/byteorder.h>
 
 #include <zephyr/bluetooth/bluetooth.h>
+#include <zephyr/bluetooth/byteorder.h>
```
Comment (cvinayak) [inline samples/bluetooth/tmap_peripheral/src/main.c:15]: Hmmm... @jhedberg @Thalley we have an explicit `byteorder.h` under Bluetooth? How different is it from `<zephyr/sys/byteorder.h>` ?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: samples/bluetooth/tmap_peripheral/src/main.c (hunk 1 above)
Comment (cvinayak) [reply samples/bluetooth/tmap_peripheral/src/main.c:15]: nevermind.

**Review by cvinayak — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
