### PR TITLE
[Backport v4.4-branch] net: dns: Enhance DNS packet forwarding mechanism

### LINKED ISSUE #107589: net: dns: Forward all DNS packets if callback is installed still not functional
### Describe the bug

Issue is already described in #106783, an attempt to fix this was done in #106810, but this was incomplete.

While debugging, I have found out that when `dns_header_rcode(dns_msg->msg) == DNS_HEADER_REFUSED` or `dns_header_ancount(dns_msg->msg) < 1` and `*dns_id > 0` (DNS packet), function will jump to quit, and dns_id and query_hash are not even computed.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Cristib05**
There are situations where internal DNS resolver will reject the packet, and in this case, query index is not calculated.
This may break forwarding mechanism;
If DNS packet forwarding is enabled, and internal validation fails, some checks are done and an attempt to calculate query index is performed, so the packet can be forwarded and used.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/107589

### CODE REVIEW

**Comment by Cristib05** [comment]
Fixes #107589

File: subsys/net/lib/dns/resolve.c [hunk 1]
```diff
@@ -1506,7 +1506,19 @@ static int dns_read(struct dns_resolve_context *ctx,
...
+	 *(DNS_HEADER_REFUSED, or ANCOUNT < 1). Applications that install this callback
+	 * might require such packets, so try to update query_idx and forward them.
+	 */
+		if (ret != 0 && dns_msg.msg_size > DNS_MSG_HEADER_SIZE &&
+		    dns_header_qdcount(dns_msg.msg) > 0 && *dns_id > 0 &&
+		    dns_unpack_response_query(&dns_msg) == 0 ) {
+			update_query_idx(ctx, &dns_msg, dns_id, &query_idx, query_hash);
+		}
+		/* Make sure that query index is in a valid range */
+		if (query_idx > 0 && query_idx < CONFIG_DNS_NUM_CONCUR_QUERIES) {
```
Comment (rlubos) [inline subsys/net/lib/dns/resolve.c]: Should be `query_idx >= 0` I think? 0 is still a valid array index.

File: subsys/net/lib/dns/resolve.c [hunk 2]
```diff
@@ -1506,7 +1506,19 @@ static int dns_read(struct dns_resolve_context *ctx,
 
 #if defined(CONFIG_DNS_RESOLVER_PACKET_FORWARDING)
 	if (ctx->pkt_fw_cb != NULL) {
-		ctx->pkt_fw_cb(dns_data, data_len, ctx->queries[query_idx].user_data);
+	/* Some packets are discared by dns_validate_msg function
```
Comment (rlubos) [inline subsys/net/lib/dns/resolve.c]: One more tab to indent this comment please.

**Review by rlubos — COMMENTED** [review]
Should be fine I think. Please check the compliance issue

**Review by rlubos — DISMISSED** [review]

File: subsys/net/lib/dns/resolve.c [hunk 3]
```diff
@@ -1506,7 +1506,19 @@ static int dns_read(struct dns_resolve_context *ctx,
...
-		ctx->pkt_fw_cb(dns_data, data_len, ctx->queries[query_idx].user_data);
+		/* Some packets are discared by dns_validate_msg function
+		 *(DNS_HEADER_REFUSED, or ANCOUNT < 1). Applications that install this callback
+		 * might require such packets, so try to update query_idx and forward them.
+		 */
+		if (ret != 0 && dns_msg.msg_size > DNS_MSG_HEADER_SIZE &&
+		    dns_header_qdcount(dns_msg.msg) > 0 && *dns_id > 0 &&
+		    dns_unpack_response_query(&dns_msg) == 0) {
+			update_query_idx(ctx, &dns_msg, dns_id, &query_idx, query_hash);
+		}
```
[the remark this answers is not in the document]
Comment (rlubos) [reply subsys/net/lib/dns/resolve.c]: True, the function does not return 0 on success... Good suggeston to check for `query_idx < 0 ` instead.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
