### PR TITLE
drivers: timer: arm_arch_timer fix tick-less bug

### LINKED ISSUE #26476: ARM Cortex-A: architecture timer continuously firing in tick-less mode
arm architecture timer interrupt is PPI to GIC cpu interface and level sensitive.
the interrupt request is cleared from IP upon 1- disabling the timer Or 2- updating the compare value Or 3-masking the interrupt.

In current driver we update the compare value to Next tick value in Tick mode.  This is working fine.
In Tick-less mode the next value should be updated as well. And that happens in` z_clock_announce().`
Still there is continuous firing of timer interrupt in tick-less mode. So in this path the timer interrupt clear is
no happening Or the compare value is not updated.  I need to check that.

If we configure the interrupt to edge sensitive the issue will not be seen on Qemu.

### PR DESCRIPTION
**Pull request by sandeepbrcm**
Calculation of compare value was getting clipped due to '32b' and 'signed'
typecasts. This resulted in very short next cycle compare value instead
of maximum possible ticks.
  
fixes: #26476
Signed-off-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com>

### CODE REVIEW

**Comment by sandeepbrcm** [comment]
I see. It has more to fix in case of 64b counter. elapsed time and many places rollover logic to be handled. (outof scope for this PR now)
I will fix the current issue at hand as part of this PR.

The same implementation is present in RISC-V as well.  So as of now will not convert it to 64b.
The effect is:  there will be timeouts even in case of tick-less kernel at a higher cycles as provided by MAX_WAIT.
If we use 64b its practically 'forever tick-less'.

File: drivers/timer/arm_arch_timer.c [hunk 1]
```diff
@@ -10,10 +10,9 @@
 #include <spinlock.h>
 #include <arch/cpu.h>
 
-#define CYC_PER_TICK	((uint32_t)((uint64_t)sys_clock_hw_cycles_per_sec() \
-			       / (uint64_t)CONFIG_SYS_CLOCK_TICKS_PER_SEC))
-
-#define MAX_TICKS	((0xffffffffu - CYC_PER_TICK) / CYC_PER_TICK)
+#define CYC_PER_TICK	(((uint64_t)sys_clock_hw_cycles_per_sec() \
+			/ (uint64_t)CONFIG_SYS_CLOCK_TICKS_PER_SEC))
```
[the remark this answers is not in the document]
Comment (sandeepbrcm) [reply drivers/timer/arm_arch_timer.c:14]: ACK

File: drivers/timer/arm_arch_timer.c [hunk 2]
```diff
@@ -10,10 +10,9 @@
...
+#define MAX_TICKS	(ULONG_MAX / CYC_PER_TICK)
```
[the remark this answers is not in the document]
Comment (sandeepbrcm) [reply drivers/timer/arm_arch_timer.c:15]: ACK

**Review by pabigot — APPROVED** [review]
Updated version makes sense as far as I can see, and clearly fixes problems.

Only questionable 32/64 thing I see remaining is the 32-bit `delta_ticks` truncation in `arm_arch_timer_compare_isr()`.  I don't know whether the tick configuration is such that an overflow is possible, but if it was this could cause problems with maintaining `last_cycle`.  Though the subsequent `z_clock_announce()` would be wrong, so maybe it's better to be wrong consistently.

**Comment by sandeepbrcm** [comment]
>  whether the tick configuration is such that an overflow is possible
a-
Since in this case `MAX_TICKS` is not capped at `INT_MAX/UINT_MAX`  It is possible to go beyond `32b`  in ~5days (unlikely as other timer usage will be there to have the timeout) in case of `K_FOREVER`.
And subsequently have `last_count `wrong. This can be fixed by not truncating the delta_ticks calculation. Thanks! this truncation 
was unnecessary. But do we assume max ticks to be 32b  see  `uint32_t z_clock_elapsed() `  Or
b-
Now I am wondering should I cap platform `MAX_TICKS` to `INT_MAX`. ie `K_FOREVER` is about  `~59` hours  (default ticks per sec is `10000` for `tick-less`) . Because  `z_clock_elapsed() ` assumes max value to be `INT_MAX` ?  This will have everything under control. But even with K_FOREVER  timer interrupt will fire in couple of days which is quite acceptable I think.

  I am actually not sure why the MAX_WAIT calculation in `kernel/timeout.c` is differentiating `K_FOREVER`.
```
#define MAX_WAIT (IS_ENABLED(CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE) \
                  ? K_TICKS_FOREVER : INT_MAX)
```
I should do one of  'a' or 'b'

**Comment by pabigot** [comment]
Good points; this probably isn't right yet.

> I am actually not sure why the MAX_WAIT calculation in `kernel/timeout.c` is differentiating `K_FOREVER`.

I can answer this part, though perhaps not correctly.  `SYSTEM_CLOCK_SLOPPY_IDLE` is an under-defined feature that allows the system clock to become non-linear in tickless mode when there's no next timeout available.  One use case for this is to turn off the timer to save power.

AFAICT it's receipt of `K_TICKS_FOREVER` as the `ticks` parameter to that triggers this feature: in at least some configurations its value can be distinguished from `INT_MAX`.  A couple drivers including `arcv2_timer0` and `cortex_m_systick` seem to do this, though neither condition it on `SYSTEM_CLOCK_SLOPPY_IDLE`.

> I should do one of 'a' or 'b'

On further thought I'm pretty sure Zephyr needs to be notified with tick counts that won't wrap, and since `z_clock_announce()` takes an `int32_t` the value of `MAX_TICKS` should be capped at `INT32_MAX` for all platforms.  Or maybe a little less, in case the announcement gets delayed and the internal calculation wraps, though I don't think anybody does that.  So, 'b'.

**Comment by sandeepbrcm** [comment]
> On further thought I'm pretty sure Zephyr needs to be notified with tick counts that won't wrap

That can potentially achieve ~59h of silence on ticks. Acceptable for all practical purpose. I am going ahead with the capping of MAX_TICKS to INT_MAX. Thanks a lot for the inputs.

File: drivers/timer/arm_arch_timer.c [hunk 3]
```diff
@@ -10,10 +10,9 @@
 #include <spinlock.h>
 #include <arch/cpu.h>
 
-#define CYC_PER_TICK	((uint32_t)((uint64_t)sys_clock_hw_cycles_per_sec() \
-			       / (uint64_t)CONFIG_SYS_CLOCK_TICKS_PER_SEC))
-
-#define MAX_TICKS	((0xffffffffu - CYC_PER_TICK) / CYC_PER_TICK)
+#define CYC_PER_TICK	((uint64_t)sys_clock_hw_cycles_per_sec() \
+			/ (uint64_t)CONFIG_SYS_CLOCK_TICKS_PER_SEC)
+#define MAX_TICKS	INT_MAX
```
Comment (pabigot) [inline drivers/timer/arm_arch_timer.c:15]: Please make this `INT32_MAX` since we really do need it the duration it provides to fit in the `int32_t` argument to clock announce.

**Review by pabigot — CHANGES_REQUESTED** [review]

File: drivers/timer/arm_arch_timer.c [hunk 4]
```diff
@@ -10,10 +10,9 @@
 #include <spinlock.h>
 #include <arch/cpu.h>
 
-#define CYC_PER_TICK	((uint32_t)((uint64_t)sys_clock_hw_cycles_per_sec() \
-			       / (uint64_t)CONFIG_SYS_CLOCK_TICKS_PER_SEC))
-
-#define MAX_TICKS	((0xffffffffu - CYC_PER_TICK) / CYC_PER_TICK)
+#define CYC_PER_TICK	((uint64_t)sys_clock_hw_cycles_per_sec() \
+			/ (uint64_t)CONFIG_SYS_CLOCK_TICKS_PER_SEC)
```
Comment (andyross) [inline drivers/timer/arm_arch_timer.c:14]: FWIW: sys_clock_hw_cycles_per_sec() is a C API that is identical to CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC on all platforms except the hpet driver on x86.  There's not a lot of value to using it here, it probably got cut-and-pasted from another timer driver, which was itself probably modified via a script when the wrapper API was introduced.

Really hardware frequency values like this want to be coming from devicetree anyway.

**Review by andyross — APPROVED** [review]
Math changes look good.  One note/nitpick on the frequency API that isn't really relevant to this patch.

File: drivers/timer/arm_arch_timer.c (hunk 3 above)
Comment (sandeepbrcm) [reply drivers/timer/arm_arch_timer.c:15]: ACK

File: drivers/timer/arm_arch_timer.c (hunk 4 above)
Comment (sandeepbrcm) [reply drivers/timer/arm_arch_timer.c:14]: Noted. 
Typically we would read the counter frequency from Cortex-A core register cntfrq which is expected to be programmed by EL3 stage. ie. It could be pre-boot firmware or arch code in zephyr it self.  Maybe another PR someday.

**Review by pabigot — APPROVED** [review]
