### PR TITLE
Bluetooth: controller: Fix data length calculation in adv report

### LINKED ISSUE #35344: [Coverity CID: 236075] Out-of-bounds access in subsys/bluetooth/controller/hci/hci.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/21d1ad3762302b3e461953df59430c77e0709274/subsys/bluetooth/controller/hci/hci.c#L5154

Category: Memory - corruptions
Function: `le_ext_adv_report`
Component: Bluetooth
CID: [236075](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=236075)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/21d1ad3762302b3e461953df59430c77e0709274/subsys/bluetooth/controller/hci/hci.c#L5154

```
5148             } else {
5149                     adv_info->direct_addr.type = 0U;
5150                     memset(&adv_info->direct_addr.a.val[0], 0, sizeof(bt_addr_t));
5151             }
5152     
5153             adv_info->length = data_len;
>>>     CID 236075:  Memory - corruptions  (OVERRUN)
>>>     Overrunning buffer pointed to by "data" of 253 bytes by passing it to a function which accesses it at byte offset 256 using argument "data_len" (which evaluates to 230). [Note: The source code implementation of the function has been overridden by a builtin model.]
5154             memcpy(&adv_info->data[0], data, data_len);
5155     
5156             node_rx_extra_list_release(node_rx->hdr.rx_ftr.extra);
5157     }
5158     
5159     static void le_adv_ext_report(struct pdu_data *pdu_data,
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by andrzej-kaczmarek**
Max data length has to be adjusted for subevent code, otherwise we'll
hit an assert when trying to add data to event due to insufficient
free space.

Fixes #35344.

Signed-off-by: Andrzej Kaczmarek <andrzej.kaczmarek@codecoup.pl>

### CODE REVIEW

File: subsys/bluetooth/controller/hci/hci.c [hunk 1]
```diff
@@ -5070,8 +5070,9 @@ static void le_ext_adv_report(struct pdu_data *pdu_data,
 	if (!data_status) {
 		uint8_t data_max_len;
 
-		data_max_len = ADV_REPORT_EVT_MAX_LEN - sizeof(*sep) -
-			       sizeof(*adv_info);
+		data_max_len = ADV_REPORT_EVT_MAX_LEN -
+			       sizeof(struct bt_hci_evt_le_meta_event) -
+			       sizeof(*sep) - sizeof(*adv_info);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/hci/hci.c:5075]: Please add my commits from https://github.com/zephyrproject-rtos/zephyr/pull/35451 to this PR, and correct it (that one can be closed with merging, thereafter). So that periodic advertising report too is fixed, if required?

**Review by cvinayak — CHANGES_REQUESTED** [review]

**Review by cvinayak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
