### PR TITLE
boards: Make GPIO pin config default for LEDs instead of PWM

### LINKED ISSUE #25337: LED pins always configured as PWM outputs
**Describe the bug**
I have come across an issue with the recent devicetree changes. For several boards, the `pinmux.c` logic previously decided whether to configure LED pins as GPIOs or PWMs based on Kconfig. Now they decide based on `DT_NODE_HAS_COMPAT_STATUS(…, okay)` on the PWM controller, which - at least for some boards - leads to always configuring the LED pins as PWMs, thus breaking samples using the LEDs as GPIOs.

This is definitely an issue with several NXP boards, but similar issues may exist on other boards.

**To Reproduce**
1. cd samples/basic/blinky; mkdir build; cd build
2. cmake -DBOARD=twr\_ke18f
3. make flash
4. Observe no blinking LED

**Expected behavior**
Amber LED (led0, D9) should blink.

**Impact**
Unable to control LEDs using GPIOs.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr SDK
 - Commit SHA: v2.3.0-rc1-99-ga0ae53410e

### PR DESCRIPTION
**Pull request by galak**
Add an additional check for CONFIG_PWM to decide if pins associated with
LED are configured for GPIO or PWM.

Fixes #25337

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

File: boards/arm/frdm_kw41z/pinmux.c [hunk 1]
```diff
@@ -28,7 +28,7 @@ static int frdm_kw41z_pinmux_init(struct device *dev)
 	/* Red, green, blue LEDs. Note the red LED and accel INT1 are both
 	 * wired to PTC1.
 	 */
-#if defined(CONFIG_PWM) && DT_NODE_HAS_STATUS(DT_NODELABEL(pwm0), okay)
+#if defined(CONFIG_PWM) && DT_NODE_HAS_STATUS(DT_NODELABEL(pwm0), okay) && CONFIG_PWM
```
Comment (MaureenHelm) [inline boards/arm/frdm_kw41z/pinmux.c:31]: this one is already covered

Comment (galak) [reply boards/arm/frdm_kw41z/pinmux.c]: fixed.

File: boards/arm/twr_ke18f/pinmux.c [hunk 2]
```diff
@@ -34,7 +34,7 @@ static int twr_ke18f_pinmux_init(struct device *dev)
 		device_get_binding(CONFIG_PINMUX_MCUX_PORTE_NAME);
 #endif
 
-#if DT_NODE_HAS_COMPAT_STATUS(DT_NODELABEL(ftm0), nxp_kinetis_ftm_pwm, okay)
+#if DT_NODE_HAS_COMPAT_STATUS(DT_NODELABEL(ftm0), nxp_kinetis_ftm_pwm, okay) && CONFIG_PWM
```
Comment (henrikbrixandersen) [inline boards/arm/twr_ke18f/pinmux.c:37]: For the twr_ke18f, you’re missing a guard for the user LEDs further down pinmux.c.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]

File: boards/arm/twr_ke18f/pinmux.c (hunk 2 above)
Comment (galak) [reply boards/arm/twr_ke18f/pinmux.c:37]: fixed

**Review by henrikbrixandersen — APPROVED** [review]
LGTM, thanks.

**Review by MaureenHelm — APPROVED** [review]
