### PR TITLE
Bluetooth: Host: Doc `bt_conn_foreach` includes disconnected

### LINKED ISSUE #53996: bt_conn_foreach() includes invalid connection while advertising
**Describe the bug**

When advertising is active (testing on Nordic nRF52840 Dongle), `bt_conn_foreach()` appears to include a connection that's not yet established with address matching `BT_ADDR_LE_NONE`.

**To Reproduce**

```
static void example_callback(struct bt_conn *conn, void *data) {
	const bt_addr_le_t *addr = bt_conn_get_dst(conn);
	if (!bt_addr_le_cmp(addr, BT_ADDR_LE_NONE)) {
		LOG_ERR("addr none");
	} else {
		LOG_INF("addr valid");
	}
}

...
	bt_conn_foreach(BT_CONN_TYPE_LE, example_callback, NULL);
...
```

**Expected behavior**

It's not clear from the documentation whether this is the expected behavior or if there's is a missing check within `bt_conn_foreach()`.

**Impact**

Workaround involves checking the address in the callback.

### PR DESCRIPTION
**Pull request by alwa-nordic**
A user reported confusion about whether disconnected `bt_conn` are meant to be found by `bt_conn_foreach`. The confusion likely stems from the inprecise wording "existing connections".

This commit doucments `bt_conn_foreach` as it is: A low-level API for iterating trough all `bt_conn` objects, connected or not.

This commit also includes a warning about possibly unintutive behavior in preemptible threads.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/53996

### CODE REVIEW

File: include/zephyr/bluetooth/conn.h [hunk 1]
```diff
@@ -216,7 +216,17 @@ struct bt_conn *bt_conn_ref(struct bt_conn *conn);
  */
 void bt_conn_unref(struct bt_conn *conn);
 
-/** @brief Iterate through all existing connections.
+/** @brief Iterate through all bt_conn objects.
+ *
+ * Iterates trough all #bt_conn objects that are alive in the Host allocator.
```
Comment (Thalley) [inline include/zephyr/bluetooth/conn.h:221]: A doxygen question:  What do the `#` in `#bt_conn` do? Is it shorthand for `@ref bt_conn`?

Comment (alwa-nordic) [reply include/zephyr/bluetooth/conn.h:221]: Yes. Shall I change it to `@ref`?

Comment (Thalley) [reply include/zephyr/bluetooth/conn.h:221]: Personally I kind of like the `#`, but on other hand `@ref` is what we use everywhere else, and it would be nice to be consistent, right? If someone went ahead and used `\ref` I'd probably also suggest to use `@ref` instead.

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
