### PR TITLE
STM32 ADC: support prescaler from RCC

### LINKED ISSUE #97881: STM32H7 MCO select and prescaler masks are incorrect
## Describe the bug

https://github.com/zephyrproject-rtos/zephyr/blob/8a72d776c5af6522478155adc91a5f4edb2794e3/include/zephyr/dt-bindings/clock/stm32_common_clocks.h#L46-L50

https://github.com/zephyrproject-rtos/zephyr/blob/8a72d776c5af6522478155adc91a5f4edb2794e3/include/zephyr/dt-bindings/clock/stm32h7_clock.h#L114-L117

Image

I believe the masks for these macros should be swapped (SEL vs PRE)... can someone confirm or deny this?

```c
#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 0x7, 22, CFGR_REG)
#define MCO1_PRE(val)           STM32_DT_CLOCK_SELECT((val), 0xF, 18, CFGR_REG)
#define MCO2_SEL(val)           STM32_DT_CLOCK_SELECT((val), 0x7, 29, CFGR_REG)
#define MCO2_PRE(val)           STM32_DT_CLOCK_SELECT((val), 0xF, 25, CFGR_REG)
```

## Steps to reproduce

Untested / unverified at the moment...

## Relevant log output

None

## Impact

Functional Limitation - Some features not working as expected, but system usable.

## Environment

- Linux fef609931a42 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- arm-none-eabi-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009
- Zephyr 90cd350c5a4, still present in 8a72d776c5af6522478155adc91a5f4edb2794e3

## Additional context

I'm using STM32H753, and luckily I don't think this will affect me, as I'm not using MCO2 (so the LSB of MCO2PRE won't be clobbered), and have low values for MCO1 prescaler (so MSB won't be masked off).

I've not verified values for the other families.

I'll try to set a large prescaler on MCO1 to confirm this if nobody else can confirm.

### PR DESCRIPTION
**Pull request by gautierg-st**
The goal of this PR is to add the support of the ADC prescaler located in RCC for some series (F1, F3, N6, U3).
Though already supported in F1 and F3, it was through a specific property of the RCC. To avoid increasing the complexity on this end, the prescaler is configured the same way as for a kernel clock, in the ADC `clocks` property in device tree.
This allows to remove the RCC specificities of F1 and F3.

This led to changes in the STM32 clock defines due to the fact that the N6 prescaler register field is 8-bit long, so the macros needed to be reworked to make it fit.

Lastly, since we can now have up to three different clocks in the `clocks` properties, instead of relying on ordering, the `clock-names` property is mandatory for all ADC instances. Names have been added in existing dtsi, dts and overlay files, but it shall be redefined if a clock source or a prescaler is added.

### CODE REVIEW

File: drivers/adc/adc_stm32.c [hunk 1]
```diff
@@ -1550,14 +1553,23 @@ static int adc_stm32_set_clock(const struct device *dev)
...
 		if (clock_control_configure(clk,
-					    (clock_control_subsys_t) &config->pclken[1],
+					    (clock_control_subsys_t) &config->pclken_ker,
+					    NULL) != 0) {
+			return -EIO;
+		}
+	}
+
+	if (config->has_pclken_pre) {
+		/* Set ADC RCC prescaler */
```
Comment (mathieuchopstm) [inline drivers/adc/adc_stm32.c]: nit:
```suggestion
		/* Configure ADC prescaler (at RCC level) */
```

File: drivers/adc/adc_stm32.c [hunk 2]
```diff
@@ -1963,14 +1975,21 @@ ADC_STM32_CHECK_DT_CLOCK(index);					\
...
-static const struct stm32_pclken pclken_##index[] =			\
-				 STM32_DT_INST_CLOCKS(index);		\
-									\
 static const struct adc_stm32_cfg adc_stm32_cfg_##index = {		\
 	.base = (ADC_TypeDef *)DT_INST_REG_ADDR(index),			\
 	ADC_STM32_IRQ_FUNC(index)					\
-	.pclken = pclken_##index,					\
-	.pclk_len = DT_INST_NUM_CLOCKS(index),				\
+	.pclken = {.bus = DT_INST_CLOCKS_CELL_BY_NAME(index, adcx, bus),			\
+		   .enr = DT_INST_CLOCKS_CELL_BY_NAME(index, adcx, bits)},			\
```
Comment (mathieuchopstm) [inline drivers/adc/adc_stm32.c:1966]: Nit: I would make a STM32-level macro for this. Basically all drivers are "wrong" today (`div` field left uninitialized) because they don't use the shared macro.

File: drivers/adc/adc_stm32.c [hunk 3]
```diff
@@ -1963,14 +1975,21 @@ ADC_STM32_CHECK_DT_CLOCK(index);					\
...
+	COND_CODE_1(DT_INST_CLOCKS_HAS_NAME(index, adc_ker),					\
+	(.pclken_ker = {.bus = DT_INST_CLOCKS_CELL_BY_NAME(index, adc_ker, bus),		\
+			.enr = DT_INST_CLOCKS_CELL_BY_NAME(index, adc_ker, bits)},		\
+	 .has_pclken_ker = true,),								\
+	(.has_pclken_ker = false,))								\
```
Comment (mathieuchopstm) [inline drivers/adc/adc_stm32.c:1971]: Nit: could be `IF_ENABLED()` and leave `has_pclken_ker` not initialized => default to false.

But I don't mind the extra verbosity.

File: include/zephyr/drivers/clock_control/stm32_clock_control.h
Comment (mathieuchopstm) [inline include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: Nits on commit `include: zephyr: dt-bindings: clock: stm32: use width instead of bitmask`:
1. commit title is not very intuitive. prefer the simpler `rework STM32_DT_CLOCK_SELECT details`?
2. Since we're breaking `STM32_DT_CLOCK_SELECT`, I would suggest the new prototype to be instead `STM32_DT_CLOCK_SELECT(val, high_bit, low_bit, reg)`

[1] `low_bit` is merely a rename; `high_bit` would be the bitfield's MSB index - `width` would be computed internally as `(high_bit - low_bit + 1)`. When copying RefMan, this would avoid the hurdle of computing bitfield width.

File: include/zephyr/dt-bindings/clock/stm32f3_clock.h [hunk 4]
```diff
@@ -66,4 +71,25 @@
...
+#define ADCxx_PRE_DIV_32	0x18
+#define ADCxx_PRE_DIV_64	0x19
+#define ADCxx_PRE_DIV_128	0x1A
+#define ADCxx_PRE_DIV_256	0x1B
+
+/* ADC prescaler for F37x: division factor */
+#define ADC_PRE_DIV_2		0
+#define ADC_PRE_DIV_4		1
+#define ADC_PRE_DIV_6		2
+#define ADC_PRE_DIV_8		3
```
Comment (mathieuchopstm) [inline include/zephyr/dt-bindings/clock/stm32f3_clock.h]: Maybe a separate `stm32f37x_clock.h` (as done for other series) should be introduced. This would allow for more consistency across series.

The definitions in this file can be gated behind a symbol that only it defines such that it overrides them cleanly, i.e.:
```diff
+#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_STM32F37X_CLOCK_H_
+ /* STM32F37x has specific ADC prescaler definitions */
...
```

File: dts/bindings/adc/st,stm32-adc.yaml [hunk 5]
```diff
@@ -15,6 +15,14 @@ properties:
   clocks:
     required: true
 
+  clock-names:
+    required: true
+    description: |
+      Expected names are the following:
+      - "adcx" for the enabling the register clock (mandatory)
+      - "adc_ker" for configuring the kernel clock (if applicable)
+      - "adc_pre" for configuring the prescaler (if applicable)
```
Comment (mathieuchopstm) [inline dts/bindings/adc/st,stm32-adc.yaml:29]: It should be mentioned somewhere that one prescaler may be shared by several ADCs.

File: include/zephyr/dt-bindings/clock/stm32f1_clock.h [hunk 6]
```diff
@@ -38,14 +38,22 @@
...
 /** BDCR devices */
-#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 8, BDCR_REG)
+#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 2, 8, BDCR_REG)
 
 /** CFGR1 devices */
-#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 0x7, 24, CFGR1_REG)
+#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 3, 24, CFGR1_REG)
 /* No MCO prescaler support on STM32F1 series. */
 
+/* ADC prescaler : division factor */
```
Comment (mathieuchopstm) [inline include/zephyr/dt-bindings/clock/stm32f1_clock.h]:
```suggestion
/* ADC prescaler: division factor */
```

But IDK if columns are very useful here?
```suggestion
/* ADC prescaler division factor */
```
ditto all

File: dts/bindings/adc/st,stm32-adc.yaml [hunk 7]
```diff
@@ -66,8 +66,7 @@ properties:
       Some of the values may not apply to some series, and may depend on the
       selected clock source. Refer to the RefMan.
       On STM32F3x (except STM32F37x), this configures only the synchronous
-      prescaler (see properties adcXX-prescaler in st,stm32f3-rcc bindings to
-      set asynchronous prescaler).
+      prescaler (use the clock property to set asynchronous prescaler).
```
Comment (mathieuchopstm) [inline dts/bindings/adc/st,stm32-adc.yaml]: The STM32F37x also have a clock property for `ADC_PRE`, so isn't this incorrect? Or are *both* prescalers applied in that instance? The comment could use some additional clarification.

**Review by mathieuchopstm — COMMENTED** [review]
Maybe the `STM32_DT_CLOCK_SELECT` update should be done in a separate PR. Not too blocking for me though.

File: drivers/adc/adc_stm32.c (hunk 2 above)
Comment (gautierg-st) [reply drivers/adc/adc_stm32.c:1966]: This is a change for another PR. As you say, all drivers are impacted, so I'm not going to introduce such a change in this one. There are enough as it is.

File: include/zephyr/drivers/clock_control/stm32_clock_control.h
Comment (gautierg-st) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: Ok with changing the commit title, but disagree with your prototype proposition. The rework was needed to gain space, make the macro more compact so that N6 prescaler could fit into it. Width is only 3-bit long, using another bit_pos would be 5-bit long. Reg would have to be reduced (not currently blocking since no reg are that long, but still, it could be needed one day).

Besides, I don't think it's a hurdle to "calculate" the width of the bitfield from RefMan (most are under 4-bit long, that's pretty easy to read).

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 7 above)
Comment (gautierg-st) [reply dts/bindings/adc/st,stm32-adc.yaml]: STM32F37x has the same ADC as STM32F1 and uses the "stm32f1-adc" compatible which removes this property and the "st,adc-clock-source" property since they are not applicable for them.
So maybe "(except STM32F37x)" is not even worth mentioning since it doesn't use this compatible anyway.

Comment (mathieuchopstm) [reply dts/bindings/adc/st,stm32-adc.yaml]: That is what I would have suggested. (removing `(except STM32F37x)`)

File: include/zephyr/drivers/clock_control/stm32_clock_control.h
Comment (mathieuchopstm) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: > Ok with changing the commit title, but disagree with your prototype proposition. The rework was needed to gain space, make the macro more compact so that N6 prescaler could fit into it. Width is only 3-bit long, using another bit_pos would be 5-bit long. Reg would have to be reduced (not currently blocking since no reg are that long, but still, it could be needed one day).

I am not suggesting to change the storage format but merely how the macro accepts parameters. When I said:
> `width` would be computed internally as `(high_bit - low_bit + 1)`

I meant that it would be computed internally *as part of the macro* (storage format is unchanged and contains `width`)

Comment (gautierg-st) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: Oh, ok, my bad, I misunderstood your proposition.
I don't have strong opinions on either choice, but I'll wait for other opinions before making any potential changes. @etienne-lms, @erwango ?

Comment (erwango) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: What would be the benefit of ` high_bit, low_bit` ? Readability ?

Comment (etienne-lms) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: I think having the lowest and highest bit position as macro argument make sense, but I'm quite used the `GENMASK()` like macros. No strong opinion here.

Comment (mathieuchopstm) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: > What would be the benefit of ` high_bit, low_bit` ? Readability ?

Basically yes. Gives the information directly from reading RefMan:

image

==> `((val), 31, 30, CCIPR)` instead of having to derive size (as @gautierg-st said, it is often 1/2 bits so not too much of a hurdle, but still more error-prone than copy-paste from RM, and we're starting to see more and more "large" fields)

> I think having the lowest and highest bit position as macro argument make sense, but I'm quite used the `GENMASK()` like macros. No strong opinion here.

`GENMASK()` takes a high/low argument as well so I don't understand your point :thinking: https://github.com/zephyrproject-rtos/zephyr/blob/169fd6a4a98eafcee0212242b0ad5ee533bbb883/include/zephyr/sys/util.h#L76-L80

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 5 above)
Comment (gautierg-st) [reply dts/bindings/adc/st,stm32-adc.yaml:29]: It's also the case for the kernel clock (at least sometimes, and it can even be shared with DAC), so it should be mentioned too.

File: include/zephyr/drivers/clock_control/stm32_clock_control.h
Comment (etienne-lms) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: > GENMASK() takes a high/low argument as well so I don't understand your point 🤔

I meant I'm fine with such API but there maybe other point of view hence no strong opinion of mine on which of high-bit/low-bit or bit-offset/bit-size couple is to be preferred as argument.

**Comment by gautierg-st** [comment]
Rebased to fix conflicts, and comments taken into account.

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 7 above)
Comment (gautierg-st) [reply dts/bindings/adc/st,stm32-adc.yaml]: Done

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 5 above)
Comment (gautierg-st) [reply dts/bindings/adc/st,stm32-adc.yaml:29]: Done

File: include/zephyr/dt-bindings/clock/stm32f3_clock.h (hunk 4 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32f3_clock.h]: To be consistent with the other files, I used `#undef` to undefine all previous ADC symbols.

File: include/zephyr/drivers/clock_control/stm32_clock_control.h
Comment (gautierg-st) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:1]: The macro now uses MSB and LSB, all clock fields have been updated. Hopefully without error.

File: drivers/adc/adc_stm32.c (hunk 1 above)
Comment (gautierg-st) [reply drivers/adc/adc_stm32.c]: Done

File: dts/bindings/adc/st,stm32-adc.yaml [hunk 8]
```diff
@@ -57,9 +68,8 @@ properties:
       st,adc-clock-source.
       Some of the values may not apply to some series, and may depend on the
       selected clock source. Refer to the RefMan.
-      On STM32F3x (except STM32F37x), this configures only the synchronous
-      prescaler (see properties adcXX-prescaler in st,stm32f3-rcc bindings to
-      set asynchronous prescaler).
+      On STM32F3x, this configures only the synchronous prescaler
+      (use the clock property to set asynchronous prescaler).
```
Comment (mathieuchopstm) [inline dts/bindings/adc/st,stm32-adc.yaml]: Nit:
```suggestion
      (use the clocks property to set asynchronous prescaler).
```
or even
```suggestion
      (use the "clocks" property to set asynchronous prescaler).
```

File: dts/bindings/adc/st,stm32-adc.yaml [hunk 9]
```diff
@@ -15,6 +16,16 @@ properties:
...
 
+  clock-names:
+    required: true
+    description: |
+      Expected names are the following:
+      - "adcx" for the enabling the register clock (mandatory)
+      - "adc_ker" for configuring the kernel clock (if applicable)
+      - "adc_pre" for configuring the prescaler (if applicable)
+      Kernel clock and prescaler may be shared between several ADC instances.
+      In that case, it must be ensured that there aren't any conflicts.
```
Comment (mathieuchopstm) [inline dts/bindings/adc/st,stm32-adc.yaml]: Maybe:
```suggestion
      In that case, the same kernel/prescaler Device Tree configuration
      must be used on all instances that share the kernel clock/prescaler
      to avoid conflicts.
```

File: include/zephyr/dt-bindings/clock/stm32_common_clocks.h [hunk 10]
```diff
@@ -23,30 +23,31 @@
...
+ * @note 'width' range:  0~7          [ 21 : 23 ]
+ * @note 'val' range:    0x00~0x1F    [ 24 : 31 ]
  */
-#define STM32_DT_CLOCK_SELECT(val, mask, shift, reg)					\
+#define STM32_DT_CLOCK_SELECT(val, msb, lsb, reg)					\
 	((((reg) & STM32_DT_CLKSEL_REG_MASK) << STM32_DT_CLKSEL_REG_SHIFT) |		\
-	 (((shift) & STM32_DT_CLKSEL_SHIFT_MASK) << STM32_DT_CLKSEL_SHIFT_SHIFT) |	\
-	 (((mask) & STM32_DT_CLKSEL_MASK_MASK) << STM32_DT_CLKSEL_MASK_SHIFT) |		\
+	 (((lsb) & STM32_DT_CLKSEL_SHIFT_MASK) << STM32_DT_CLKSEL_SHIFT_SHIFT) |	\
+	 (((msb - lsb) & STM32_DT_CLKSEL_WIDTH_MASK) << STM32_DT_CLKSEL_WIDTH_SHIFT) |	\
```
Comment (mathieuchopstm) [inline include/zephyr/dt-bindings/clock/stm32_common_clocks.h]: Nit:
```suggestion
	 ((((msb) - (lsb)) & STM32_DT_CLKSEL_WIDTH_MASK) << STM32_DT_CLKSEL_WIDTH_SHIFT) |	\
```
(I think you did not add `+1` on purpose because the "width" is stored as "field width - 1"?)

File: include/zephyr/dt-bindings/clock/stm32f37x_clock.h [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_STM32F37X_CLOCK_H_
+#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_STM32F37X_CLOCK_H_
+
+#include "stm32f3_clock.h"
+
+/* On STM32F37x the ADC prescaler is located in CFGR1 and the prescaler values are more limited */
+#undef ADC12_PRE(val)
+#undef ADC34_PRE(val)
```
Comment (mathieuchopstm) [inline include/zephyr/dt-bindings/clock/stm32f37x_clock.h]: I'm pretty sure that this should be
```suggestion
#undef ADC12_PRE
#undef ADC34_PRE
```

File: include/zephyr/dt-bindings/clock/stm32f37x_clock.h [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+ * Copyright (c) 2025 STMicroelectronics
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_STM32F37X_CLOCK_H_
+#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_STM32F37X_CLOCK_H_
+
+#include "stm32f3_clock.h"
+
+/* On STM32F37x the ADC prescaler is located in CFGR1 and the prescaler values are more limited */
```
Comment (mathieuchopstm) [inline include/zephyr/dt-bindings/clock/stm32f37x_clock.h]: Nit:
```suggestion
/* On STM32F37x, the ADC prescaler is located in CFGR1 and the prescaler values are more limited */
```

File: include/zephyr/dt-bindings/clock/stm32f3_clock.h [hunk 13]
```diff
@@ -36,34 +36,53 @@
...
+#define USART3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 19, 18, CFGR3_REG)
+#define USART4_SEL(val)		STM32_DT_CLOCK_SELECT((val), 21, 20, CFGR3_REG)
+#define USART5_SEL(val)		STM32_DT_CLOCK_SELECT((val), 23, 22, CFGR3_REG)
+#define TIM2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 24, 24, CFGR3_REG)
+#define TIM3_4_SEL(val)		STM32_DT_CLOCK_SELECT((val), 25, 25, CFGR3_REG)
 /** BDCR devices */
-#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 8, BDCR_REG)
+#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 9, 8, BDCR_REG)
+
+/* ADC prescaler division factor for all F3 but F37x */
```
Comment (mathieuchopstm) [inline include/zephyr/dt-bindings/clock/stm32f3_clock.h]: Nit:
```suggestion
/* ADC prescaler division factor for all F3 except F37x */
```

**Review by mathieuchopstm — COMMENTED** [review]
I'll do a second pass to make sure no selector has been broken but otherwise LGTM, minus a few points

File: include/zephyr/dt-bindings/clock/stm32_common_clocks.h [hunk 14]
```diff
@@ -23,30 +23,31 @@
...
+ * @param lsb    Field LSB's index
  * @param reg    Offset to target clock configuration register in RCC
  *
+ * @note Internally, the data are stored as follows
  * @note 'reg' range:    0x0~0xFFFF   [ 00 : 15 ]
- * @note 'shift' range:  0~63         [ 16 : 21 ]
- * @note 'mask' range:   0x00~0x1F    [ 22 : 26 ]
- * @note 'val' range:    0x00~0x1F    [ 27 : 31 ]
+ * @note 'shift' range:  0~31         [ 16 : 20 ]
+ * @note 'width' range:  0~7          [ 21 : 23 ]
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32_common_clocks.h]:
```suggestion
 * @note 'width' range:  0~7          [ 21 : 23 ]  Value encodes bit fields width minus 1
```
Would explicitly address extra comment from https://github.com/zephyrproject-rtos/zephyr/pull/97725/commits/e29ae439b835f26f1315533d1812f6ffb13670d6#r2451959811.

File: include/zephyr/dt-bindings/clock/stm32f1_clock.h [hunk 15]
```diff
@@ -39,13 +39,13 @@
...
-#define I2S3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 1, 18, CFGR2_REG)
+#define I2S2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 17, 17, CFGR2_REG)
+#define I2S3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 18, 18, CFGR2_REG)
 /** BDCR devices */
-#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 8, BDCR_REG)
+#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 9, 8, BDCR_REG)
 
 /** CFGR1 devices */
-#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 0x7, 24, CFGR1_REG)
+#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 27, 24, CFGR1_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32f1_clock.h]:
```suggestion
#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 26, 24, CFGR1_REG)

File: include/zephyr/dt-bindings/clock/stm32f10x_clock.h [hunk 16]
```diff
@@ -19,7 +19,7 @@
 
 /** CFGR1 devices */
 #undef MCO1_SEL /* Need to redefine generic F1 MCO_SEL for connectivity line devices. */
-#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 0xF, 24, CFGR1_REG)
+#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 27, 24, CFGR1_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32f10x_clock.h:22]: According o the refman, I think the right values here are:
```c
#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 26, 24, CFGR1_REG)
```
I think this should be fixed in a specific appended commit, that said, there are other already existing wrong values that this commit fixes. Maybe a sentence in the commit message could mention that.

File: include/zephyr/dt-bindings/clock/stm32f7_clock.h [hunk 17]
```diff
@@ -71,31 +71,31 @@
...
+#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 9, 8, BDCR_REG)
 
 /** @brief RCC_DKCFGR register offset */
 #define DCKCFGR1_REG		0x8C
 #define DCKCFGR2_REG		0x90
 
 /** @brief Dedicated clocks configuration register selection helpers */
 /** DKCFGR2 devices */
-#define USART1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 0, DCKCFGR2_REG)
+#define USART1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 4, 0, DCKCFGR2_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32f7_clock.h]:
```suggestion
#define USART1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 1, 0, DCKCFGR2_REG)

File: include/zephyr/dt-bindings/clock/stm32h5_clock.h [hunk 18]
```diff
@@ -68,67 +68,67 @@
...
+#define USART1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 2, 0, CCIPR1_REG)
+#define USART2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 5, 3, CCIPR1_REG)
+#define USART3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 8, 6, CCIPR1_REG)
+#define USART4_SEL(val)		STM32_DT_CLOCK_SELECT((val), 11, 9, CCIPR1_REG)
+#define USART5_SEL(val)		STM32_DT_CLOCK_SELECT((val), 14, 12, CCIPR1_REG)
+#define USART6_SEL(val)		STM32_DT_CLOCK_SELECT((val), 17, 15, CCIPR1_REG)
+#define USART7_SEL(val)		STM32_DT_CLOCK_SELECT((val), 20, 18, CCIPR1_REG)
+#define USART8_SEL(val)		STM32_DT_CLOCK_SELECT((val), 23, 21, CCIPR1_REG)
+#define USART9_SEL(val)		STM32_DT_CLOCK_SELECT((val), 26, 24, CCIPR1_REG)
+#define USART10_SEL(val)	STM32_DT_CLOCK_SELECT((val), 30, 27, CCIPR1_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32h5_clock.h]:
```suggestion
#define USART10_SEL(val)	STM32_DT_CLOCK_SELECT((val), 29, 27, CCIPR1_REG)

File: include/zephyr/dt-bindings/clock/stm32h7rs_clock.h [hunk 19]
```diff
@@ -78,44 +78,43 @@
...
-#define I2C1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 12, D2CCIPR_REG)
-#define I3C1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 12, D2CCIPR_REG)
-#define LPTIM1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 7, 16, D2CCIPR_REG)
-#define FDCAN_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 22, D2CCIPR_REG)
+#define USART234578_SEL(val)	STM32_DT_CLOCK_SELECT((val), 2, 0, D2CCIPR_REG)
+#define SPI23_SEL(val)		STM32_DT_CLOCK_SELECT((val), 6, 4, D2CCIPR_REG)
+#define I2C23_SEL(val)		STM32_DT_CLOCK_SELECT((val), 9, 8, D2CCIPR_REG)
+#define I2C1_I3C1_SEL(val)	STM32_DT_CLOCK_SELECT((val), 13, 12, D2CCIPR_REG)
+#define LPTIM1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 18, 16, D2CCIPR_REG)
+#define FDCAN_SEL(val)		STM32_DT_CLOCK_SELECT((val), 24, 22, D2CCIPR_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32h7rs_clock.h]:
```suggestion
#define FDCAN_SEL(val)		STM32_DT_CLOCK_SELECT((val), 23, 22, D2CCIPR_REG)

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 20]
```diff
@@ -59,35 +59,35 @@
...
+#define SDMMC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 14, 14, CCIPR2_REG)
+#define OSPI_SEL(val)		STM32_DT_CLOCK_SELECT((val), 21, 20, CCIPR2_REG)
 /** BDCR devices */
-#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 8, BDCR_REG)
+#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 9, 8, BDCR_REG)
 /** CFGR devices */
-#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 0xF, 24, CFGR_REG)
-#define MCO1_PRE(val)           STM32_DT_CLOCK_SELECT((val), 0x7, 28, CFGR_REG)
+#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 17, 24, CFGR_REG)
+#define MCO1_PRE(val)           STM32_DT_CLOCK_SELECT((val), 31, 28, CFGR_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h]:
```suggestion
#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 27, 24, CFGR_REG)
#define MCO1_PRE(val)           STM32_DT_CLOCK_SELECT((val), 30, 28, CFGR_REG)

File: include/zephyr/dt-bindings/clock/stm32l5_clock.h [hunk 21]
```diff
@@ -59,34 +59,34 @@
...
+#define UART4_SEL(val)		STM32_DT_CLOCK_SELECT((val), 7, 6, CCIPR_REG)
+#define UART5_SEL(val)		STM32_DT_CLOCK_SELECT((val), 9, 8, CCIPR_REG)
+#define LPUART1_SEL(val)	STM32_DT_CLOCK_SELECT((val), 11, 10, CCIPR_REG)
+#define I2C1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 13, 12, CCIPR_REG)
+#define I2C2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 15, 14, CCIPR_REG)
+#define I2C3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 17, 16, CCIPR_REG)
+#define LPTIM1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 19, 18, CCIPR_REG)
+#define LPTIM2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 21, 20, CCIPR_REG)
+#define LPTIM3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 23, 22, CCIPR_REG)
+#define FDCAN_SEL(val)		STM32_DT_CLOCK_SELECT((val), 22, 24, CCIPR_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32l5_clock.h]:
```suggestion
#define FDCAN_SEL(val)		STM32_DT_CLOCK_SELECT((val), 25, 24, CCIPR_REG)

File: include/zephyr/dt-bindings/clock/stm32l5_clock.h [hunk 22]
```diff
@@ -59,34 +59,34 @@
...
+#define OSPI_SEL(val)		STM32_DT_CLOCK_SELECT((val), 21, 20, CCIPR2_REG)
 
 /** BDCR devices */
-#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 8, BDCR_REG)
+#define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 9, 8, BDCR_REG)
 /** CFGR devices */
-#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 0xF, 24, CFGR_REG)
-#define MCO1_PRE(val)           STM32_DT_CLOCK_SELECT((val), 0x7, 28, CFGR_REG)
+#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 27, 24, CFGR_REG)
+#define MCO1_PRE(val)           STM32_DT_CLOCK_SELECT((val), 31, 28, CFGR_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32l5_clock.h]:
```suggestion
#define MCO1_PRE(val)           STM32_DT_CLOCK_SELECT((val), 30, 28, CFGR_REG)

File: include/zephyr/dt-bindings/clock/stm32mp13_clock.h [hunk 23]
```diff
@@ -115,41 +115,41 @@
...
-#define QSPI_SEL(val)		STM32_DT_CLOCK_SELECT((val), 0x3, 0, QSPICKSELR_REG)
-#define FMC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 0x3, 0, FMCCKSELR_REG)
-#define RNG1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 0x3, 0, RNG1CKSELR_REG)
-#define STGEN_SEL(val)		STM32_DT_CLOCK_SELECT((val), 0x3, 0, STGENCKSELR_REG)
-#define DCMIPP_SEL(val)		STM32_DT_CLOCK_SELECT((val), 0x3, 0, DCMIPPCKSELR_REG)
-#define SAES_SEL(val)		STM32_DT_CLOCK_SELECT((val), 0x3, 0, SAESCKSELR_REG)
+#define I2C12_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 0, I2C12CKSELR_REG)
+#define I2C3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 0, I2C345CKSELR_REG)
+#define I2C4_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 3, I2C345CKSELR_REG)
+#define I2C5_SEL(val)		STM32_DT_CLOCK_SELECT((val), 3, 6, I2C345CKSELR_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32mp13_clock.h]:
```suggestion
#define I2C12_SEL(val)		STM32_DT_CLOCK_SELECT((val), 2, 0, I2C12CKSELR_REG)
#define I2C3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 2, 0, I2C345CKSELR_REG)
#define I2C4_SEL(val)		STM32_DT_CLOCK_SELECT((val), 5, 3, I2C345CKSELR_REG)
#define I2C5_SEL(val)		STM32_DT_CLOCK_SELECT((val), 8, 6, I2C345CKSELR_REG)
```
Actaully, al the list below use a bitfield width value whereas the MSbit position is expected.

File: include/zephyr/dt-bindings/clock/stm32n6_clock.h [hunk 24]
```diff
@@ -96,85 +96,87 @@
...
+#define I3C2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 22, 20, CCIPR4_REG)
+#define LTDC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 25, 24, CCIPR4_REG)
 /** CCIPR5 devices */
-#define MCO1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 7, 0, CCIPR5_REG)
-#define MCO2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 7, 8, CCIPR5_REG)
-#define MDF1SEL(val)		STM32_DT_CLOCK_SELECT((val), 7, 16, CCIPR5_REG)
+#define MCO1_SEL(val)		STM32_DT_CLOCK_SELECT((val), 2, 0, CCIPR5_REG)
+#define MCO1_PRE(val)		STM32_DT_CLOCK_SELECT((val), 7, 4, CCIPR5_REG)
+#define MCO2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 10, 8, CCIPR5_REG)
+#define MCO2_PRE(val)		STM32_DT_CLOCK_SELECT((val), 15, 12, CCIPR5_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32n6_clock.h:124]: MCOx_PRE is added: mention in commit message or add in a dedicated commit?

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 8 above)
Comment (gautierg-st) [reply dts/bindings/adc/st,stm32-adc.yaml]: Done

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 9 above)
Comment (gautierg-st) [reply dts/bindings/adc/st,stm32-adc.yaml]: Done

File: include/zephyr/dt-bindings/clock/stm32_common_clocks.h (hunk 10 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32_common_clocks.h]: Done. Yes width is stored on 3 bits, possible values are 0-7 which corresponds to real width of 1-8.

File: include/zephyr/dt-bindings/clock/stm32f37x_clock.h (hunk 11 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32f37x_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32f37x_clock.h (hunk 12 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32f37x_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32f3_clock.h (hunk 13 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32f3_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32f1_clock.h [hunk 25]
```diff
@@ -38,14 +38,22 @@
...
+#define ADC_PRE(val)		STM32_DT_CLOCK_SELECT((val), 15, 14, CFGR1_REG)
 /** CFGR2 devices */
 #define I2S2_SEL(val)		STM32_DT_CLOCK_SELECT((val), 17, 17, CFGR2_REG)
 #define I2S3_SEL(val)		STM32_DT_CLOCK_SELECT((val), 18, 18, CFGR2_REG)
 /** BDCR devices */
 #define RTC_SEL(val)		STM32_DT_CLOCK_SELECT((val), 9, 8, BDCR_REG)
 
 /** CFGR1 devices */
-#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 27, 24, CFGR1_REG)
+#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 26, 24, CFGR1_REG)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32f1_clock.h:50]: Could you move this fixup from commit "include: dt-bindings: clock: stm32: add adc prescaler for f1, f3, n6 ..."
to the 1st commit "include: dt-bindings: clock: stm32: rework STM32_DT_CLOCK_SELECT details"?

File: include/zephyr/dt-bindings/clock/stm32n6_clock.h [hunk 26]
```diff
@@ -179,4 +180,7 @@
 /** @brief CPU clock switch selection */
 #define CPU_SEL(val)		STM32_DT_CLOCK_SELECT((val), 17, 16, CFGR1_REG)
 
+/* ADC prescaler division factor helper */
+#define ADC_PRE_DIV(pres) ((pres - 1) & 0xFFU)
```
Comment (etienne-lms) [inline include/zephyr/dt-bindings/clock/stm32n6_clock.h]:
```suggestion
#define ADC_PRE_DIV(pres)	(((pres) - 1) & 0xFFU)

File: dts/bindings/adc/st,stm32-adc.yaml [hunk 27]
```diff
@@ -15,6 +16,18 @@ properties:
...
+    required: true
+    description: |
+      Expected names are the following:
+      - "adcx" for the enabling the register clock (mandatory)
+      - "adc_ker" for configuring the kernel clock (if applicable)
+      - "adc_pre" for configuring the prescaler (if applicable)
+      Kernel clock and prescaler may be shared between several ADC instances.
+      In that case, the same kernel clock/prescaler Device Tree configuration
+      must be used on all instances that share the kernel clock/prescaler
+      to avoid conflicts.
```
Comment (etienne-lms) [inline dts/bindings/adc/st,stm32-adc.yaml:33]: I would suggest to add an enumerated list for the supported values.

File: drivers/adc/adc_stm32.c [hunk 28]
```diff
@@ -1550,14 +1553,23 @@ static int adc_stm32_set_clock(const struct device *dev)
 	int ret = 0;
 
 	if (clock_control_on(clk,
-		(clock_control_subsys_t) &config->pclken[0]) != 0) {
+		(clock_control_subsys_t) &config->pclken) != 0) {
```
Comment (etienne-lms) [inline drivers/adc/adc_stm32.c]: Worth to move into a single line?

File: drivers/adc/adc_stm32.c (hunk 2 above)
Comment (etienne-lms) [reply drivers/adc/adc_stm32.c:1966]: My 2 cents. `div` is not left uninitialized, It's 0 which is fine if division is not used (as per the various  `stm32_clock_control_get_subsys_rate()` implemenations), no?
That said, I agree using an STM32 helper macro for these would be worth it.

File: dts/bindings/adc/st,stm32-adc.yaml [hunk 29]
```diff
@@ -45,7 +45,7 @@ properties:
       - "SYNC": derived from the bus clock.
       - "ASYNC" : independent and asynchronous with the bus clock
       One of the two values may not apply to some series. Refer to the RefMan.
-      If an asynchronous clock is selected, a domain clock in the clock property
+      If an asynchronous clock is selected, a domain clock in the "clocks" property
```
Comment (etienne-lms) [inline dts/bindings/adc/st,stm32-adc.yaml]: The description above mentions a "kernel" clock, not a "domain" clock. Sync the 2 wordings?

**Review by etienne-lms — COMMENTED** [review]
For commit "dts: bindings: adc: update binding description", could you mention stm32 in the header line, e.g.:
`dts: bindings: adc: update STM32 binding description`

File: include/zephyr/dt-bindings/clock/stm32f1_clock.h (hunk 15 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32f1_clock.h]: Already fixed.

File: include/zephyr/dt-bindings/clock/stm32f10x_clock.h (hunk 16 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32f10x_clock.h:22]: No, 27 is the correct value for "Connectivity-lines" F1x (RM0008, §8 Connectivity line devices: reset and clock control
(RCC))

File: include/zephyr/dt-bindings/clock/stm32f1_clock.h (hunk 15 above)
Comment (etienne-lms) [reply include/zephyr/dt-bindings/clock/stm32f1_clock.h]: Expected MSBit value here is 26 or 27?
From reading the reference manuals, it's 26.

File: include/zephyr/dt-bindings/clock/stm32f10x_clock.h (hunk 16 above)
Comment (etienne-lms) [reply include/zephyr/dt-bindings/clock/stm32f10x_clock.h:22]: Ok. My mistake.
Maybe an explicit inline comment like the one used in WB0 binding file would prevent one from questioning on this value. E.g:
```c
/* Need to redefine generic F10x MCO_SEL for connectivity line devices where bit filed range is [24..27] */
#undef MCO1_SEL
#define MCO1_SEL(val)           STM32_DT_CLOCK_SELECT((val), 27, 24, CFGR1_REG)

File: include/zephyr/dt-bindings/clock/stm32_common_clocks.h (hunk 14 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32_common_clocks.h]: Done

File: include/zephyr/dt-bindings/clock/stm32f7_clock.h (hunk 17 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32f7_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32h5_clock.h (hunk 18 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32h5_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32h7rs_clock.h (hunk 19 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32h7rs_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h (hunk 20 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32l4_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32l5_clock.h (hunk 21 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32l5_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32l5_clock.h (hunk 22 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32l5_clock.h]: Done

File: include/zephyr/dt-bindings/clock/stm32n6_clock.h (hunk 24 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32n6_clock.h:124]: Done

File: include/zephyr/dt-bindings/clock/stm32f1_clock.h (hunk 25 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32f1_clock.h:50]: Done

File: include/zephyr/dt-bindings/clock/stm32n6_clock.h (hunk 26 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32n6_clock.h]: Done

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 27 above)
Comment (gautierg-st) [reply dts/bindings/adc/st,stm32-adc.yaml:33]: Done

File: drivers/adc/adc_stm32.c (hunk 28 above)
Comment (gautierg-st) [reply drivers/adc/adc_stm32.c]: Done

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 29 above)
Comment (gautierg-st) [reply dts/bindings/adc/st,stm32-adc.yaml]: Done

File: include/zephyr/dt-bindings/clock/stm32mp13_clock.h (hunk 23 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32mp13_clock.h]: I apparently missed to update that one. Fixed.

File: drivers/adc/adc_stm32.c [hunk 30]
```diff
@@ -1549,15 +1552,23 @@ static int adc_stm32_set_clock(const struct device *dev)
...
 	int ret = 0;
 
-	if (clock_control_on(clk,
-		(clock_control_subsys_t) &config->pclken[0]) != 0) {
+	if (clock_control_on(clk, (clock_control_subsys_t)&config->pclken) != 0) {
 		return -EIO;
 	}
 
-	if (IS_ENABLED(STM32_ADC_DOMAIN_CLOCK_SUPPORT) && (config->pclk_len > 1)) {
+	if (config->has_pclken_ker) {
```
Comment (etienne-lms) [inline drivers/adc/adc_stm32.c]: Now `STM32_ADC_DOMAIN_CLOCK_SUPPORT` is unused. Would you mind removing it?

File: drivers/adc/adc_stm32.c [hunk 31]
```diff
@@ -1549,15 +1552,23 @@ static int adc_stm32_set_clock(const struct device *dev)
...
 		/* Enable ADC clock source */
 		if (clock_control_configure(clk,
-					    (clock_control_subsys_t) &config->pclken[1],
+					    (clock_control_subsys_t)&config->pclken_ker,
+					    NULL) != 0) {
+			return -EIO;
+		}
+	}
```
Comment (etienne-lms) [inline drivers/adc/adc_stm32.c:1554]: Suggestion:
```c
	if (config->has_pclken_ker &&
	    clock_control_configure(clk, (clock_control_subsys_t)&config->pclken_ker, NULL) != 0) {
		return -EIO;
	}
```
Ditto below:
```c
	/* Configure ADC prescaler (at RCC level) if applicable */
	if (config->has_pclken_pre &&
	    clock_control_configure(clk, (clock_control_subsys_t)&config->pclken_pre, NULL) != 0) {
		return -EIO;
	}

**Review by etienne-lms — DISMISSED** [review]

File: drivers/adc/adc_stm32.c (hunk 30 above)
Comment (gautierg-st) [reply drivers/adc/adc_stm32.c]: Good point. Removed

File: drivers/adc/adc_stm32.c (hunk 31 above)
Comment (gautierg-st) [reply drivers/adc/adc_stm32.c:1554]: Done

File: dts/bindings/adc/st,stm32-adc.yaml [hunk 32]
```diff
@@ -49,7 +49,7 @@ properties:
       - "SYNC": derived from the bus clock.
       - "ASYNC" : independent and asynchronous with the bus clock
       One of the two values may not apply to some series. Refer to the RefMan.
-      If an asynchronous clock is selected, a domain clock in the clock property
+      If an asynchronous clock is selected, a kernel clock in the "clocks" property
```
Comment (erwango) [inline dts/bindings/adc/st,stm32-adc.yaml:52]: I won't block but "domain clock" are all over the place and we need to be consistent. We'll need to fix this one way or the other.
(Note that we've already moved from "kernel" to "domain" once)

**Review by erwango — DISMISSED** [review]

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 32 above)
Comment (etienne-lms) [reply dts/bindings/adc/st,stm32-adc.yaml:52]: Nice story. Maybe reword like: 
```
If an asynchronous clock is selected, a domain clock in the "clocks" property
has to be defined explicitly using the kernel clock name "adc_ker".

File: drivers/adc/adc_stm32.c [hunk 33]
```diff
@@ -1534,33 +1536,27 @@ static int adc_stm32h7_setup_boost(const struct adc_stm32_cfg *config, ADC_TypeD
...
 
-	if (IS_ENABLED(STM32_ADC_DOMAIN_CLOCK_SUPPORT) && (config->pclk_len > 1)) {
-		/* Enable ADC clock source */
-		if (clock_control_configure(clk,
-					    (clock_control_subsys_t) &config->pclken[1],
-					    NULL) != 0) {
-			return -EIO;
-		}
+	/* Enable ADC clock source if applicable */
+	if ((config->has_pclken_ker) &&
```
Comment (etienne-lms) [inline drivers/adc/adc_stm32.c]: Can remove inner parentheses.
Ditto below.

Comment (gautierg-st) [reply drivers/adc/adc_stm32.c]: Done

**Comment by etienne-lms** [comment]
LGTM but you need to rebase your series.

**Comment by gautierg-st** [comment]
> LGTM but you need to rebase your series.

Thanks, done.

**Comment by erwango** [comment]
@kylebonnici Seems linter is wrong here: https://github.com/zephyrproject-rtos/zephyr/actions/runs/18772147196/job/53558655897?pr=97725#step:13:176:. It reports failure and proposes the following:
```diff
 			dmas = <&gpdma1 0 7 (STM32_DMA_PERIPH_TX | STM32_DMA_16BITS |
-					     STM32_DMA_PRIORITY_HIGH)>,
+				STM32_DMA_PRIORITY_HIGH)>,
 			       <&gpdma1 1 6 (STM32_DMA_PERIPH_RX | STM32_DMA_16BI
```

**Comment by gautierg-st** [comment]
> @kylebonnici Seems linter is wrong here: https://github.com/zephyrproject-rtos/zephyr/actions/runs/18772147196/job/53558655897?pr=97725#step:13:176:. It reports failure and proposes the following:
> 
> ```diff
>  			dmas = <&gpdma1 0 7 (STM32_DMA_PERIPH_TX | STM32_DMA_16BITS |
> -					     STM32_DMA_PRIORITY_HIGH)>,
> +				STM32_DMA_PRIORITY_HIGH)>,
>  			       <&gpdma1 1 6 (STM32_DMA_PERIPH_RX | STM32_DMA_16BI
> ```

I've fixed the other issues reported by linter, but I'm waiting for feedback on this one.

File: drivers/adc/adc_stm32.c (hunk 2 above)
Comment (mathieuchopstm) [reply drivers/adc/adc_stm32.c:1966]: > My 2 cents. `div` is not left uninitialized, It's 0

By `uninitialized`, I meant that it doesn't take its value from DT :slightly_smiling_face:

File: dts/bindings/adc/st,stm32-adc.yaml (hunk 32 above)
Comment (mathieuchopstm) [reply dts/bindings/adc/st,stm32-adc.yaml:52]: IMO we should stick to `kernel clock` as it is the name used in RefMan.

File: include/zephyr/dt-bindings/clock/stm32_common_clocks.h [hunk 34]
```diff
@@ -23,30 +23,31 @@
...
  * @param reg    Offset to target clock configuration register in RCC
  *
+ * @note Internally, the data are stored as follows
  * @note 'reg' range:    0x0~0xFFFF   [ 00 : 15 ]
- * @note 'shift' range:  0~63         [ 16 : 21 ]
- * @note 'mask' range:   0x00~0x1F    [ 22 : 26 ]
- * @note 'val' range:    0x00~0x1F    [ 27 : 31 ]
+ * @note 'shift' range:  0~31         [ 16 : 20 ]
+ * @note 'width' range:  0~7          [ 21 : 23 ] Value encodes bit fields width minus 1
+ * @note 'val' range:    0x00~0x1F    [ 24 : 31 ]
```
Comment (mathieuchopstm) [inline include/zephyr/dt-bindings/clock/stm32_common_clocks.h]: I think that now:
```suggestion
 * @note 'val' range:    0x00~0xFF    [ 24 : 31 ]
```

**Comment by kylebonnici** [comment]
@gautierg-st 

> > @kylebonnici Seems linter is wrong here: https://github.com/zephyrproject-rtos/zephyr/actions/runs/18772147196/job/53558655897?pr=97725#step:13:176:. It reports failure and proposes the following:
> > ```diff
> >  			dmas = <&gpdma1 0 7 (STM32_DMA_PERIPH_TX | STM32_DMA_16BITS |
> > -					     STM32_DMA_PRIORITY_HIGH)>,
> > +				STM32_DMA_PRIORITY_HIGH)>,
> >  			       <&gpdma1 1 6 (STM32_DMA_PERIPH_RX | STM32_DMA_16BI
> > ```
> 
> I've fixed the other issues reported by linter, but I'm waiting for feedback on this one.

is question s why it is aligning `STM32_DMA_PRIORITY_HIGH ` with `dmas = <` and not `dmas = <&gpdma1 0 7 (`?

**Comment by gautierg-st** [comment]
> is question s why it is aligning `STM32_DMA_PRIORITY_HIGH ` with `dmas = <` and not `dmas = <&gpdma1 0 7 (`?

Yes, that's the question.

File: include/zephyr/dt-bindings/clock/stm32u3_clock.h [hunk 35]
```diff
@@ -100,4 +101,16 @@
...
+#define ADCDAC_PRE_DIV_1	0
+#define ADCDAC_PRE_DIV_2	1
+#define ADCDAC_PRE_DIV_4	8
+#define ADCDAC_PRE_DIV_8	9
+#define ADCDAC_PRE_DIV_16	10
+#define ADCDAC_PRE_DIV_32	11
+#define ADCDAC_PRE_DIV_64	12
+#define ADCDAC_PRE_DIV_128	13
+#define ADCDAC_PRE_DIV_256	14
+#define ADCDAC_PRE_DIV_512	15
```
Comment (mathieuchopstm) [inline include/zephyr/dt-bindings/clock/stm32u3_clock.h]: Nit: in another file, you used hex for a similar kind of definitions (non-contiguous range), so we could do the same for consistency:
```suggestion
#define ADCDAC_PRE_DIV_1	0x0
#define ADCDAC_PRE_DIV_2	0x1
#define ADCDAC_PRE_DIV_4	0x8
#define ADCDAC_PRE_DIV_8	0x9
#define ADCDAC_PRE_DIV_16	0xA
#define ADCDAC_PRE_DIV_32	0xB
#define ADCDAC_PRE_DIV_64	0xC
#define ADCDAC_PRE_DIV_128	0xD
#define ADCDAC_PRE_DIV_256	0xE
#define ADCDAC_PRE_DIV_512	0xF
```

**Review by mathieuchopstm — COMMENTED** [review]
Otherwise LGTM

File: include/zephyr/dt-bindings/clock/stm32_common_clocks.h (hunk 34 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32_common_clocks.h]: Fixed

File: include/zephyr/dt-bindings/clock/stm32u3_clock.h (hunk 35 above)
Comment (gautierg-st) [reply include/zephyr/dt-bindings/clock/stm32u3_clock.h]: Done

**Comment by gautierg-st** [comment]
I've fixed the linter warnings since I'd like this PR to be merged for v4.3.

**Comment by kylebonnici** [comment]
> > is question s why it is aligning `STM32_DMA_PRIORITY_HIGH ` with `dmas = <` and not `dmas = <&gpdma1 0 7 (`?
> 
> Yes, that's the question.

This was discussed [here](https://github.com/zephyrproject-rtos/zephyr/pull/92803#discussion_r2335981978):

TLDR;

the linter will always format with `dmas = <` and will not take the expression group level into consideration yet but I am open to have a discussion on this!

Solution for your use case.
Move the whole expression down... 
```diff
 			dmas = <&gpdma1 0 7
-					     STM32_DMA_PRIORITY_HIGH)>,
+				(STM32_DMA_PERIPH_TX | STM32_DMA_16BITS | STM32_DMA_PRIORITY_HIGH)>,
 			       <&gpdma1 1 6 (STM32_DMA_PERIPH_RX | STM32_DMA_16BI
```

in some cases this may still be too long .... 

in such case consider 
```diff
 			dmas = <&gpdma1 0 7
-					     STM32_DMA_PRIORITY_HIGH)>,
+				(STM32_DMA_PERIPH_TX | STM32_DMA_16BITS |
+				STM32_DMA_PRIORITY_HIGH)>,
 			       <&gpdma1 1 6 (STM32_DMA_PERIPH_RX | STM32_DMA_16BI
```

Do post an issue on the linter repo and a suggestion and I am happy to consider adding this. FYI this will come into play when we add auto splitting lines that exceed 100 chars. In such a case the linter would opt to move the whole groups to a new line to reduce need to split line again.

**Review by etienne-lms — APPROVED** [review]

**Review by mathieuchopstm — APPROVED** [review]

**Review by erwango — APPROVED** [review]
