### PR TITLE
tests: add new tests for memory partitions

### LINKED ISSUE #26621: System can't recover after assertion failed in kernel/mem_domain.c
**Describe the bug**
I wrote tests for the mem_domain and find out that assertion in line 171 of the `zephyr/kernel/mem_domain.c` makes system unrecoverable after assertion was executed.

**To Reproduce**
1. Go to https://github.com/zephyrproject-rtos/zephyr/pull/25535
2. Setup my branch
3. Run the memory protection
`west build -t run -p -b qemu_x86 tests/kernel/mem_protect/mem_protect/`
5. If you will place `test_mem_part_assert_add_overmax` to run the last one (in that case run it after `test_create_new_invalid_prio_thread_from_user`) in file `tests/kernel/mem_protect/mem_protect/src/main.`c Then test `test_mem_part_assert_add_overmax` will be passed successfully.

**Expected behavior**
I expect that after kernel assertion in user application next parts of the application's code must continue running without any errors

**Impact**
Testing vulnerabilities of the memory protection in Zephyr

**Logs and console output**
```
ASSERTION FAIL [z_spin_lock_valid(l)] @ ../include/spinlock.h:92
        Recursive spinlock 0x0013237c
E: EAX: 0x00000008, EBX: 0x001320a0, ECX: 0x0000000a, EDX: 0x0013237c
E: ESI: 0x00131f80, EDI: 0x00000246, EBP: 0x001862f0, ESP: 0x001862d4
E: EFLAGS: 0x00000097 CS: 0x0008 CR3: 0x00131f60
E: call trace:
E: EIP: 0x0010377b
E:      0x0010a806 (0x131f80)
E:      0x0010a8a4 (0x1320a0)
E:      0x00105d5a (0x1320a0)
E:      0x00101484 (0x10f3f5)
E:      0x00105ea1 (0x18f12c)
E:      0x00106817 (0x1863e4)
E:      0x00103115 (0x0)
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x001321e0 (main)
Caught system error -- reason 4 0
fatal error was unexpected, aborting
FAILED: zephyr/CMakeFiles/run
cd /home/maksim/zephyrproject/zephyr/build && /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/qemu-system-i386 -m 9 -cpu qemu32,+nx,+pae -device isa-debug-exit,iobase=0xf4,iosize=0x04 -no-reboot -nographic -net none -pidfile qemu.pid -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -icount shift=5,align=off,sleep=off -rtc clock=vm -kernel /home/maksim/zephyrproject/zephyr/build/zephyr/zephyr.elf
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/maksim/zephyrproject/zephyr/build --target run
```

**Environment (please complete the following information):**
 - OS: Lunix Fedora
 - Toolchain Zephyr SDK 0.11.3
 - maksimmasalski:14_6_add_new_memory_tests
My branch already rebased and contains new master changes from the upstream

### PR DESCRIPTION
**Pull request by maksimmasalski**
Add new tests to improve of the Zephyr QA testing of the memory protection for memory domains and partitions.
I created new tests for memory protection->memory partitions for the requirements which I think necessary to be tested. I added Doxygen tag for each test to make it clear
to understand what each test is doing and how.

**New tests for memory domains and partitions:**
1.  test_mem_domain_api_kernel_thread_only()
By creating that test I wanted to prove that access to memory domain APIs must be restricted only to supervisor threads. At the same time I wanted to prove that system can support the definition of memory domains.

2. test_mem_part_auto_determ_size()
By creating that test I want to prove that system can automatically determine application memory partition base addresses and sizes at build time, determined by its contents. Also system can support definition of memory partitions. At the same time test proves that OS supports adding and removing a thread from its memory domain assignment.

3. test_mem_part_auto_determ_size_per_mmu()
That test is very important and it proves that memory partitions are automatically sized and aligned per the constraints of the platform's memory management hardware.

4. test_mem_part_inheirt_by_child_thr() 
Prove that child thread inherits memory domain assignment of its parent.

5. test_macros_obtain_names_data_bss()
Test system provides tools to obtain the names of the data and BSS sections related to a particular application memory partition at build time.

6. test_mem_part_assign_bss_vars_zero()
Test that global data and BSS values can be assigned to application memory partitions using macros at build time. Test that BSS values will be zeroed at the build time.

Signed-off-by: Maksim Masalski <maksim.masalski@intel.com>

### CODE REVIEW

**Comment by maksimmasalski** [comment]
@nashif @andrewboie @andyross I'm looking for code review of that PR.

File: tests/kernel/mem_protect/mem_protect/src/mem_domain.c [hunk 1]
```diff
@@ -594,3 +625,229 @@ void test_mem_domain_destroy(void)
...
+					user_handler_func,
+					NULL, NULL, NULL,
+					PRIORITY,
+					K_USER, K_NO_WAIT);
+	k_mem_domain_add_thread(&domain1, usr_tid0);
+	k_sem_take(&sync_sem, K_FOREVER);
+}
+
+/**
+ * @brief Test partitions sized per the constraints of the MMU hardware
```
Comment (andrewboie) [inline tests/kernel/mem_protect/mem_protect/src/mem_domain.c:706]: MMU and MPU are different hardware. MMU is not an appropriate noun to describe both.

File: tests/kernel/mem_protect/mem_protect/src/mem_domain.c [hunk 2]
```diff
@@ -594,3 +625,229 @@ void test_mem_domain_destroy(void)
...
+ *
+ * @details
+ * - Test that system automatically determine memory partition size according
+ *   to the constraints of the platform's MMU hardware.
+ * - Different platforms like x86, ARM and ARC have different MMU hardware for
```
Comment (andrewboie) [inline tests/kernel/mem_protect/mem_protect/src/mem_domain.c:711]: No, ARC and some ARM do not have MMU at all, they have MPU instead.

File: tests/kernel/mem_protect/mem_protect/src/mem_domain.c [hunk 3]
```diff
@@ -14,6 +15,36 @@ K_THREAD_STACK_DEFINE(mem_domain_1_stack, MEM_DOMAIN_STACK_SIZE);
...
+u8_t __aligned(MEM_REGION_ALLOC) buf0[MEM_REGION_ALLOC];
+K_MEM_PARTITION_DEFINE(part0, buf0, sizeof(buf0),
+		K_MEM_PARTITION_P_RW_U_RW);
+
+K_APPMEM_PARTITION_DEFINE(part1);
+K_APP_BMEM(part1) u8_t __aligned(MEM_REGION_ALLOC) buf1[MEM_REGION_ALLOC];
+struct k_mem_partition *app1_parts[] = {
+	&part1
+};
+K_APPMEM_PARTITION_DEFINE(part_arc);
```
Comment (andrewboie) [inline tests/kernel/mem_protect/mem_protect/src/mem_domain.c:38]: why is this called `part_arc`?

File: tests/kernel/mem_protect/mem_protect/src/main.c [hunk 4]
```diff
@@ -90,7 +107,12 @@ void test_main(void)
 			 ztest_unit_test(test_create_new_supervisor_thread_from_user),
 			 ztest_unit_test(test_create_new_essential_thread_from_user),
 			 ztest_unit_test(test_create_new_higher_prio_thread_from_user),
-			 ztest_unit_test(test_create_new_invalid_prio_thread_from_user)
+			 ztest_unit_test(
+				 test_create_new_invalid_prio_thread_from_user),
+			 /* Due to the generated assertion error, test
+			  * test_mem_part_assert_add_overmax must be in the end
+			  */
+			 ztest_unit_test(test_mem_part_assert_add_overmax)
```
Comment (andrewboie) [inline tests/kernel/mem_protect/mem_protect/src/main.c:115]: don't test against asserts. file a bug instead.

File: tests/kernel/mem_protect/mem_protect/src/mem_domain.c (hunk 3 above)
Comment (maksimmasalski) [reply tests/kernel/mem_protect/mem_protect/src/mem_domain.c:38]: Maybe it is some legacy when I had different partition names for each architecture.

File: tests/kernel/mem_protect/mem_protect/src/mem_domain.c (hunk 1 above)
Comment (maksimmasalski) [reply tests/kernel/mem_protect/mem_protect/src/mem_domain.c:706]: I will change and replace with "MPU".

File: tests/kernel/mem_protect/mem_protect/src/mem_domain.c (hunk 2 above)
Comment (maksimmasalski) [reply tests/kernel/mem_protect/mem_protect/src/mem_domain.c:711]: I will change comment and replace with "MPU".

**Review by maksimmasalski — COMMENTED** [review]
I will make changes.

File: tests/kernel/mem_protect/mem_protect/src/main.c (hunk 4 above)
Comment (maksimmasalski) [reply tests/kernel/mem_protect/mem_protect/src/main.c:115]: Seems that there is no bug, I put that test before the last one and assertion works correctly. That test verifies that assertion in zephyr/kernel/mem_domain.c L171 works as expected.

Comment (maksimmasalski) [reply tests/kernel/mem_protect/mem_protect/src/main.c]: https://github.com/zephyrproject-rtos/zephyr/issues/26621 I submitted an issue.

File: tests/kernel/mem_protect/mem_protect/src/mem_domain.c (hunk 3 above)
Comment (maksimmasalski) [reply tests/kernel/mem_protect/mem_protect/src/mem_domain.c]: It should be `part_arch` (architecture)

File: tests/kernel/mem_protect/mem_protect/src/mem_domain.c [hunk 5]
```diff
@@ -528,3 +559,214 @@ void test_mem_domain_remove_partitions(void)
...
+ * - Run that test in kernel mode -no errors should happen.
+ * - Run that test in user mode -Zephyr fatal error will happen (reason 0),
+ *   because user threads can't use memory domain APIs.
+ * - At the same time test that system support the definition of memory domains.
+ *
+ * @ingroup kernel_memprotect_tests
+ *
+ * @see k_mem_domain_init(), k_mem_domain_add_partition()
+ */
+void test_mem_domain_api_kernel_thread_only(void)
```
Comment (LeiW000) [inline tests/kernel/mem_protect/mem_protect/src/mem_domain.c:578]: I'm wondering how sanitycheck can detect if the test case fails？ I don't see any zassert in the code.

Comment (maksimmasalski) [reply tests/kernel/mem_protect/mem_protect/src/mem_domain.c:578]: Necessary to use flag `valid_fault = true;` or use like `set_fault_valid(true);`

**Review by LeiW000 — APPROVED** [review]

**Review by enjiamai — APPROVED** [review]
