### PR TITLE
kernel: timer_api: more tweaks for inexact conversions and poor clock tolerance

### LINKED ISSUE #24001: tests/kernel/timer/timer_api failed on reel_board and mec15xxevb_assy6853.
**Describe the bug**
for mec15xxevb_assy6853, it was the same error log as reel_board.

**To Reproduce**
1.  west build -b reel_board -p auto tests/kernel/timer/timer_api/
2.  west flash
3. See error

**Screenshots or console output**
*** Booting Zephyr OS build zephyr-v2.2.0-1006-g41712204059e  ***
Running test suite timer_api

starting test - test_time_conversions
PASS - test_time_conversions

starting test - test_timer_duration_period
PASS - test_timer_duration_period

starting test - test_timer_period_0
PASS - test_timer_period_0

starting test - test_timer_expirefn_null
PASS - test_timer_expirefn_null

starting test - test_timer_periodicity
PASS - test_timer_periodicity

starting test - test_timer_status_get
PASS - test_timer_status_get

starting test - test_timer_status_get_anytime
PASS - test_timer_status_get_anytime

starting test - test_timer_status_sync
PASS - test_timer_status_sync

starting test - test_timer_k_define
**Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:64: duration_expire: interval >= 100 is false**
FAIL - test_timer_k_define

starting test - test_timer_user_data
PASS - test_timer_user_data

starting test - test_timer_remaining
**Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:548: test_timer_remaining: (exp_ticks - now) <= dur_ticks / 2 is false**
FAIL - test_timer_remaining

starting test - test_timeout_abs
**Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:561: test_timeout_abs: t2.ticks == t.ticks is false**
FAIL - test_timeout_abs

Test suite timer_api failed.

PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.1
 - Commit ID: 4171220405

### LINKED ISSUE #24784: nRF: Busy wait clock is skewed vs. timer clock
On nRF5 SoCs, the integration uses CONFIG_ARCH_HAS_CUSTOM_BUSY_WAIT=y to forward k_busy_wait() calls to a HAL-defined nrfx_coredep_delay_us() function (which presumably works at CPU cycle precision) instead of using the default Zephyr one (which is limited to the 32kHz cycle rate).

Unfortunately, these clocks don't match.  The HAL timer is consistently about .5-.6% too fast, meaning that k_busy_wait() will return earlier than users expect.

This is causing a test failure on at least nrf52840 devices, where tests/kernel/timer/timer_api has a few long delays that it expects to be correct relative to the tick/cycle timer.  This got unmasked by the timer API changes (which fixed a double-round-up in the k_timer_remaining_*() paths), but it seems like the problem is definitely at the platform layer.

The code below does a bunch of busy waits at different delays and compares them to the times reported by the existing timer driver.  It produces the following log on my nrf52840dk_nrf52840.  Note that as the delays increase the error settles down to a consistent asymptote, implying that it's the clock rates that are skewed and not just an offset or aliased conversion somewhere:

(Note also that as I iterate the test, the deltas are jumping around quite a bit to the tune of 5-10 32kHz cycles per half-second busy wait.  300us of jitter seems like **way** too much to me given the clock rates involved.)

```
*** Booting Zephyr OS build zephyr-v2.2.0-2044-g315cba1c40fc  ***
                eff   err
   us    cyc     us   ppm
 ===== ====== ====== =====
     1      0      0 1000000
     2      0      0 1000000
     4      0      0 1000000
     8      0      0 1000000
    16      1     30     0
    32      1     30 500000
    64      2     61 333333
   128      5    152     0
   256      8    244 111111
   512     16    488 58823
  1024     33   1007 29411
  2048     67   2044 14705
  4096    134   4089  7407
  8192    267   8148  7434
 16384    535  16326  3724
 32768   1070  32653  3724
 65536   2141  65338  3258
131072   4275 130462  4656
262144   8542 260681  5587
524288  17080 521240  5820
```

```c
#include <zephyr.h>
#include <stdlib.h>

void main(void)
{
	printk("                eff   err\n");
	printk("   us    cyc     us   ppm\n");
	printk(" ===== ====== ====== =====\n");
	for (int us = 1; us < 1000000; us *= 2) {

		/* Busy Wait */
		int t0 = k_cycle_get_32();
		k_busy_wait(us);
		int t1 = k_cycle_get_32();

		/* Effective us waited: floor, because we want to wait
		 * at least this long and this is the longest duration
		 * we can prove.
		 */
		int eff_us = k_cyc_to_us_floor32(t1 - t0);

		/* Error, in parts per million */
		int exp_cyc = k_us_to_cyc_ceil32(us);
		int err_ppm = (int)(1000000ull
				    * abs((t1 - t0) - exp_cyc) / exp_cyc);

		printk("%6d %6d %6d %5d\n", us, t1-t0, eff_us, err_ppm);
	}
}
```

### PR DESCRIPTION
**Pull request by pabigot**
A couple failures observed in #24001 are a consequence of precision loss converting between milliseconds and 32 KiHz ticks, compounded by clock rate variation.  Other failures are due to skew between the clock used for busywait and the clock used for system time.  Also asynchronous updates to the tick counter can occur before or after the value it's compared with has been captured.

In short, tweak the test until it runs reliably on problematic hardware identified in #24001 (where "reliably" means >100 consecutive runs without failure using `CONFIG_ZTEST_RETEST_IF_PASSED=y`).

Fixes #24001
Fixes #24784 through a documentation fix clarifying that `k_busy_wait()` delays are not necessarily aligned to sysclock.

### CODE REVIEW

**Comment by pabigot** [comment]
This passed 2160 consecutive runs before failing with:
```
    Assertion failed at ../src/main.c:571: test_timer_remaining: abs((s32_t)(rem_ticks - target_rem_tic
ks)) <= 3 is false
```
on a board that had a fairly accurate (< 1000 ppm error) HFINT (64 MHz internal oscillator).

On another board with -7200 ppm HFINT error and +61 ppm LFXO error the tick error on that test is -13 (expected tick duration is 1640) consistently.  I don't see any point in increasing the threshold higher: some boards will simply be out of tolerance.

File: tests/kernel/timer/timer_api/src/main.c [hunk 1]
```diff
@@ -18,6 +19,7 @@ struct timer_data {
 #define EXPIRE_TIMES 4
 #define WITHIN_ERROR(var, target, epsilon)       \
 		(((var) >= (target)) && ((var) <= (target) + (epsilon)))
+#define INEXACT_MS_CONVERT (k_ticks_to_ms_ceil64(k_ms_to_ticks_ceil64(1)) != 1)
```
Comment (andyross) [inline tests/kernel/timer/timer_api/src/main.c:22]: This might be a little more robust if you checked that they weren't divisible directly.  Something like:

```c
#define INEXACT_MS_CONVERT                       \
    (MAX(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC,     \
         CONFIG_SYS_CLOCK_TICKS_PER_SEC) %       \
     MIN(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC,     \
         CONFIG_SYS_CLOCK_TICKS_PER_SEC) == 0)   \
```

Honestly I had to think really hard to figure out if that double conversion was guaranteed to detect the case you want, and I'm still not completely convinced it does for all non-divisible rates.

File: tests/kernel/timer/timer_api/src/main.c [hunk 2]
```diff
@@ -61,9 +63,13 @@ static void duration_expire(struct k_timer *timer)
 
 	tdata.expire_cnt++;
 	if (tdata.expire_cnt == 1) {
-		TIMER_ASSERT(interval >= DURATION, timer);
+		TIMER_ASSERT((interval >= DURATION)
+			     || (INEXACT_MS_CONVERT
+				 && (interval == DURATION - 1)), timer);
```
Comment (andyross) [inline tests/kernel/timer/timer_api/src/main.c:68]: The inexact version is a tighter bound (looking for an exact interval value) than the old one (make sure it's higher than or equal to duration).  That seems wrong.  It's OK to add slop where needed, but we should be testing the same behavior on all platforms.

File: tests/kernel/timer/timer_api/src/main.c [hunk 3]
```diff
@@ -270,10 +277,14 @@ void test_timer_periodicity(void)
...
+		 *
+		 * In the case of inexact conversion the delta will
+		 * occasionally be one less than the expected number.
 		 */
-		TIMER_ASSERT(WITHIN_ERROR(delta,
-				k_ticks_to_ms_floor64(k_ms_to_ticks_ceil32(PERIOD)), 1),
-				&periodicity_timer);
+		TIMER_ASSERT(WITHIN_ERROR(delta, period_ms, 1)
+			     || (INEXACT_MS_CONVERT
+				 && (delta == period_ms - 1)),
```
Comment (andyross) [inline tests/kernel/timer/timer_api/src/main.c:286]: Similar deal: it used to allow slop, now it doesn't.  We should do the same thing with a selectable offset so we don't end up accidentally testing different behavior on different systems.

File: tests/kernel/timer/timer_api/src/main.c [hunk 4]
```diff
@@ -544,7 +556,19 @@ void test_timer_remaining(void)
...
+	 * half DURATION in ticks, when DURATION/2 is not an integer
+	 * multiple of ticks, so target_rem_ticks is used rather than
+	 * dur_ticks/2.
+	 *
+	 * Also if the tick clock is faster or slower than the
+	 * busywait clock the remaining time in ticks will be larger
+	 * or smaller than expected, so relax the tolerance.  3 ticks
+	 * variance has been observed on hardware where the busywait
+	 * clock is 0.7% slow and the 32 KiHz tick clock is 60 ppm
+	 * fast relative to a stable external clock.
```
Comment (andyross) [inline tests/kernel/timer/timer_api/src/main.c:569]: Hm... what this does is basically change the Zephyr tested promise that the busy wait and system clock times are compatible.  I think if we're going to do this as policy it needs to be spelled out in the docs explicitly somewhere, not just silently waved away in a test.

**Review by andyross — CHANGES_REQUESTED** [review]
Some nitpicks.   The only issue I feel strongly about is that we can't change documented behavior via a tweak to a test.  If the clocks are now allowed to be skewed by policy now, then we should document that in the k_busy_wait() definition.

**Comment by carlescufi** [comment]
@andyross Perhaps we could discuss the relationship between the system timer and `k_busy_wait()` also in the context of #24784, and settle this as part of this release. I added a recent comment there:
https://github.com/zephyrproject-rtos/zephyr/issues/24784#issuecomment-632060703

**Comment by andyross** [comment]
Honestly I'd be happy with a documentation fix.  Right now the clear implication of the way k_timer and k_busy_wait are defined is that they work in the same units.  If they're allowed to be different, we should **say** they can be different (and maybe for extra credit have a framework for characterizing that skew, etc...).

But we can't just patch a test.  Real users are not unlikely to make the same assumption the test author did.

**Comment by carlescufi** [comment]
> Honestly I'd be happy with a documentation fix. Right now the clear implication of the way k_timer and k_busy_wait are defined is that they work in the same units. If they're allowed to be different, we should **say** they can be different (and maybe for extra credit have a framework for characterizing that skew, etc...).
> 
> But we can't just patch a test. Real users are not unlikely to make the same assumption the test author did.

I agree. @pabigot how about proposing a documentation patch in this very PR, and deal with #24784 at the same time?

File: tests/kernel/timer/timer_api/src/main.c (hunk 2 above)
Comment (pabigot) [reply tests/kernel/timer/timer_api/src/main.c:75]: I don't understand this statement.  If the original test passes nothing changes.  If it fails, then if we know we might have an error in converting ms to ticks, and in that case we relax the lower bound to account for a tick that wasn't added because accumulated error exceeded a tick.

File: tests/kernel/timer/timer_api/src/main.c (hunk 4 above)
Comment (pabigot) [reply tests/kernel/timer/timer_api/src/main.c:576]: Done.

**Review by andyross — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
