### PR TITLE
usb: Fix ACL data tx stalling

### LINKED ISSUE #14899: Bluetooth controller ACL data packets stall
**My test setup** 
nRF52840_pca10059, hci_usb sample. Proprietary host stack and application (fuzzer) in Linux
Peer: csr8510, Linux kernel

Proprietary application is used for Bluetooth SMP fuzzing. Test target is running also linux.

**Describe the bug**
After certain test cases Zephyr controller goes to the state that it does not send HCI ACL packets out. Control packets are still working fine: i.e. connection can be created. When controller is in bad state, host stack sends HCI ACL packets to controller until controller tx buffer is full but host never receives Number of completed packets events. Dongle needs to be unplugged and plugged again to recover.

Configuring `CONFIG_BT_CTLR_TX_BUFFERS=1` makes this problem not reproducible.

Hci logs and sniffer captures as attachment: [zephyr_captures.zip](https://github.com/zephyrproject-rtos/zephyr/files/3006734/zephyr_captures.zip)

**To Reproduce**
I can reproduce this reliably. Requires proprietary application. 

Test sequence consists of sending 1024 bytes of 0xff, valid public key, pairing random, dhkey check and trying to start encryption. This is done many times until ACL packets are stalling.

**Expected behavior**
Controller is expected to send ACL packets out normally.

**Impact**
Stopper.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit 972221423cde92639f685542b10a8caa35793ec5

### PR DESCRIPTION
**Pull request by mkarhumaa**
This patch increases size of acl_tx_pool and makes sure that acl_read_cb
waits for available buffers.

Previously it was possible to run out of buffers and in that case
acl_read_cb returned. This caused ACL data TX to stall because device
did not read data from HCI out endpoint.

Fixes #14899

Signed-off-by: Matias Karhumaa <matias.karhumaa@gmail.com>

### CODE REVIEW

File: subsys/usb/class/bluetooth.c [hunk 1]
```diff
@@ -38,7 +38,7 @@ NET_BUF_POOL_DEFINE(tx_pool, CONFIG_BT_HCI_CMD_COUNT, CMD_BUF_SIZE,
 #define BT_L2CAP_MTU 64
 /* Data size needed for ACL buffers */
 #define BT_BUF_ACL_SIZE BT_L2CAP_BUF_SIZE(BT_L2CAP_MTU)
-NET_BUF_POOL_DEFINE(acl_tx_pool, 2, BT_BUF_ACL_SIZE, sizeof(u8_t), NULL);
+NET_BUF_POOL_DEFINE(acl_tx_pool, 4, BT_BUF_ACL_SIZE, sizeof(u8_t), NULL);
```
Comment (jhedberg) [inline subsys/usb/class/bluetooth.c]: Would it make sense to sync this up with `CONFIG_BT_CTLR_TX_BUFFERS`?

File: subsys/usb/class/bluetooth.c [hunk 2]
```diff
@@ -188,7 +188,7 @@ static void acl_read_cb(u8_t ep, int size, void *priv)
 		net_buf_unref(buf);
 	}
 
-	buf = net_buf_alloc(&acl_tx_pool, K_NO_WAIT);
+	buf = net_buf_alloc(&acl_tx_pool, K_FOREVER);
```
Comment (cvinayak) [inline subsys/usb/class/bluetooth.c]: instead of logging error, use __ASSERT_NO_MSG, that is how it is done in bluetooth subsystem.

File: subsys/usb/class/bluetooth.c (hunk 1 above)
Comment (mkarhumaa) [reply subsys/usb/class/bluetooth.c]: Ok, sounds feasible. I will fix it.

Comment (cvinayak) [reply subsys/usb/class/bluetooth.c]: is increase to 4 or to CONFIG_BT_CTLR_TX_BUFFERS justified?  implicit flow control by use of K_FOREVER should be enough to throttle ACL packet into controller, hence the original double buffer should suffice?

Comment (jhedberg) [reply subsys/usb/class/bluetooth.c]: @mkarhumaa note that `CONFIG_BT_CTLR_TX_BUFFERS` will not be available in some "exotic" configurations, i.e. when you're using USB to proxy a controller that's behind some physical transport rather than the native controller. So you'll probably want hci_usb to have it's own define something along the lines of:

```
#if defined(CONFIG_BT_CTLR_TX_BUFFERS)
#define ACL_BUF_COUNT CONFIG_BT_CTLR_TX_BUFFERS
#else
#define ACL_BUF_COUNT 4
#endif
```

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/usb/class/bluetooth.c (hunk 1 above)
Comment (jhedberg) [reply subsys/usb/class/bluetooth.c]: > is increase to 4 or to CONFIG_BT_CTLR_TX_BUFFERS justified? 

@cvinayak that's a fair question. I was just thinking that if one sets `CONFIG_BT_CTLR_TX_BUFFERS` to a considerably higher value, then hci_usb will become a bottleneck if its own pool doesn't grow dynamically.

Comment (mkarhumaa) [reply subsys/usb/class/bluetooth.c]: > is increase to 4 or to CONFIG_BT_CTLR_TX_BUFFERS justified? implicit flow control by use of K_FOREVER should be enough to throttle ACL packet into controller, hence the original double buffer should suffice?

This was suggested by Johann F. at #usb channel in Slack. I think increasing acl_tx_pool should make sure that it will not become bottleneck and stall on host side.

File: subsys/usb/class/bluetooth.c (hunk 2 above)
Comment (mkarhumaa) [reply subsys/usb/class/bluetooth.c]: Will fix this.

Comment (jhedberg) [reply subsys/usb/class/bluetooth.c]: Yep. Assert should be used for things which indicate a bug somewhere, and getting NULL when you have K_FOREVER is definitely a bug.

File: subsys/usb/class/bluetooth.c (hunk 1 above)
Comment (cvinayak) [reply subsys/usb/class/bluetooth.c]: ok, its the speed of USB+DMA vs the memcpy into controller's tx buffers. I would use a low buffer count, and users can be instructed in the form of comment to increase the buffer count upto the CTLR_TX_BUFFERS if degraded throughput is observed. (lets try to keep low RAM usage in our samples).

**Review by finikorg — APPROVED** [review]
LGTM

File: subsys/usb/class/bluetooth.c (hunk 1 above)
Comment (jhedberg) [reply subsys/usb/class/bluetooth.c]: @cvinayak isn't also USB+DMA vs how fast the packets are sent over air and the buffers consequently freed up in the controller? I'd imagine the memcpy to be negligible there.

Comment (mkarhumaa) [reply subsys/usb/class/bluetooth.c]: @cvinayak So you prefer keeping acl_tx_pool size in 2 and just adding comment? To my understanding CONFIG_BT_CTLS_RX_BUFFERS defaults to 7 if BT_HCI_RAW is enabled and 3 if not.

Keeping it in 2 is fine for me.

**Comment by mkarhumaa** [comment]
I have force-pushed a version addressing the comments. I ended up using `CONFIG_BT_CTLR_TX_BUFFERS` to configure size of `acl_tx_pool`. Let me know if there is anything else that should be fixed.

**Review by cvinayak — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
