### PR TITLE
drivers: i2c: mcux_lpi2c: remove using of kLPI2C_TransferRepeatedStartFlag

### LINKED ISSUE #99479: NXP RT1061 LPI2C read capped at 1024 bytes
### Describe the bug

NXP RT1061 LPI2C can’t perform read requests larger than 1024 bytes. When I tried to read 4096 bytes from an I2C slave (EEPROM) on LPI2C2
```
&lpi2c2 {
    status = "okay";
	pinctrl-0 = <&pinmux_lpi2c2>;
	pinctrl-names = "default";
	eeprom0: eeprom@50 {
		/* M24512-RMN6TP (512 kbit eeprom in) */
		compatible = "st,m24512", "st,m24xxx", "atmel,at24";
		reg = <0x50>;
		size = <DT_SIZE_K(64)>;
		pagesize = <128>;
		address-width = <16>;
		timeout = <5>;
	};
```
in a single call, `eeprom_read()` returned `-EIO`. Using a debugger, I found that the failure occurs in [(fsl_lpi2c.c line 1612)](https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/mcux-sdk-ng/drivers/lpi2c/fsl_lpi2c.c#L1612), where the HAL limits I2C read transactions to 1024 bytes. This limitation is not mentioned in Zephyr’s I2C API, and application code should not need to handle target-specific restrictions. The driver or HAL layer should encapsulate this limitation by automatically chunking the transfer rather than forcing user code to be aware of hardware-dependent limits. Every transaction of 1024 bytes or less works as expected. By the way, it seems that this file does not account for `kStatus_InvalidArgument` in the documentation when listing the possible return codes.

Zephyr 4.2.1

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MichalChromecNXP**
The enum kLPI2C_TransferRepeatedStartFlag is not used in fsl_lpi2c.c, so it shouldn't be used in mcux_lpi2c drivers.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/99479

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@MichalChromecNXP, please rebase

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 1]
```diff
@@ -141,10 +141,6 @@ static uint32_t mcux_lpi2c_convert_flags(int msg_flags)
 		flags |= kLPI2C_TransferNoStopFlag;
 	}
 
-	if (msg_flags & I2C_MSG_RESTART) {
-		flags |= kLPI2C_TransferRepeatedStartFlag;
```
Comment (mmahadevan108) [inline drivers/i2c/i2c_mcux_lpi2c.c:145]: I still see instances of using this inside `drivers/dsc_lpi2c/fsl_lpi2c.c`. What should we do about this?

Comment (MichalChromecNXP) [reply drivers/i2c/i2c_mcux_lpi2c.c:145]: Hello @mmahadevan108, I found the enum is used only under block #if I2C_SMBUS_ENABLE, which is by default set to 0 and I didn't find definition to other value for zephyr projects (samples, tests), so it looks it is currently not used in zephyr.

**Review by ZhaoxiangJin — DISMISSED** [review]

File: drivers/i2c/i2c_mcux_lpi2c.c
Comment (hakehuang) [inline drivers/i2c/i2c_mcux_lpi2c.c:1]: This looks incomplete: `drivers/i2c/i2c_rv32m1_lpi2c.c` still uses `kLPI2C_TransferRepeatedStartFlag` in `rv32m1_lpi2c_convert_flags()`. Since this PR updates the HAL and removes the usage from the MCUX LPI2C drivers, should RV32M1 be updated too?

I checked the tree and this doesn't look like dead code: `dts/riscv/openisa/rv32m1.dtsi` defines LPI2C instances and `boards/openisa/rv32m1_vega/rv32m1_vega_openisa_rv32m1.dtsi` enables at least `lpi2c0` and `lpi2c3`. Please either fix that driver in this PR or explain why it is unaffected.

**Review by hakehuang — CHANGES_REQUESTED** [review]
I found one likely missed in-tree user of the removed repeated-start handling. Please address the RV32M1 LPI2C driver as noted in the review comment, or clarify why it is unaffected by the HAL update.

File: drivers/i2c/i2c_mcux_lpi2c.c
Comment (MichalChromecNXP) [reply drivers/i2c/i2c_mcux_lpi2c.c:1]: Hi @hakehuang, I also updated the i2c_rv32m1_lpi2c.c, which mentions "Based on the i2c_mcux_lpi2c.c".

**Review by hakehuang — APPROVED** [review]
Thanks for the update.

regression test pass on v4.4.0-rc1-67-g2700aeeb4db4

**Review by mmahadevan108 — APPROVED** [review]
