### PR TITLE
soc: st: stm32U5/L5 series also have SWO line

### LINKED ISSUE #80479: HAS_SWO not getting selected by STM32U5 series
**Describe the bug**

I'm developing a custom board based on the STM32U5A5 and wanted to debug it through SWO.
When selecting 'CONFIG_LOG_BACKEND_SWO' i get the error that HAS_SWO (=n).
Tried builtin Boards but those have the same issue.

**To Reproduce**

```bash
west build -p -b nucleo_u5a5zj_q samples/hello_world/ -DCONFIG_LOG_BACKEND_SWO=y -DCONFIG_LOG=y
```

**Expected behavior**

I would expect to be able to log to SWO.

**Impact**

Console output through SWO on STM32U5x not possible.

**Environment (please complete the following information):**

 - OS: Windows
 - Toolchain: Zephyr SDK 0.17.0
 - g26603cefaf41 (main at time of creation) and v3.7.0

**Additional context**

### PR DESCRIPTION
**Pull request by FRASTM**
Add the SWO trace output to the stm32U5/L5/H7RS series

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/80479

### CODE REVIEW

File: soc/st/stm32/common/soc_config.c [hunk 1]
```diff
@@ -28,15 +28,16 @@ static int st_stm32_common_config(void)
 {
 #ifdef CONFIG_LOG_BACKEND_SWO
 	/* Enable SWO trace asynchronous mode */
-#if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_SOC_SERIES_STM32H5X)
+#if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_SOC_SERIES_STM32H5X) ||                  \
+	defined(CONFIG_SOC_SERIES_STM32H7RSX) || defined(CONFIG_SOC_SERIES_STM32U5X) ||            \
+	defined(CONFIG_SOC_SERIES_STM32L5X)
```
Comment (gautierg-st) [inline soc/st/stm32/common/soc_config.c:33]: Nit: it would be better to have the series by alphabetical order (and maybe one per line for easier potential additions later)

**Review by gautierg-st — CHANGES_REQUESTED** [review]

File: soc/st/stm32/common/soc_config.c (hunk 1 above)
Comment (FRASTM) [reply soc/st/stm32/common/soc_config.c]: changed to alphanum order

**Review by mniestroj — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by mathieuchopstm — APPROVED** [review]
