### PR TITLE
scripts: checkpatch: fix missing blank line detection after declarations

### LINKED ISSUE #98976: checkpatch: Missing line after declaration not enforced if line is removed
### Describe the bug

If a user attempts to add something like 

```c
void foo(void)
{
	int a = 0;
	if (a == 0) {
		return;
	}
}
```

then `checkpatch.pl` would return an error like

```
WARNING : Test Checkpatch warning: 
LINE_SPACING: Missing a blank line after declarations
```

as it should be
```c
void foo(void)
{
	int a = 0;

	if (a == 0) {
		return;
	}
}
```

However if the existing code is 
```c
void foo(void)
{
	int a = 0;

	if (a == 0) {
		return;
	}
}
```

and a commit removes the newline so that it becomes

```c
void foo(void)
{
	int a = 0;
	if (a == 0) {
		return;
	}
}
```

Then the missing newline is not captured by checkpatch.pl, and it passes CI. 

### Regression

- [ ] This is a regression.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

8b2c75a2fbe4eef38a99f0a050d9d1d268d1bb69

### Additional Context

It has been seen in a few PRs (e.g. https://github.com/zephyrproject-rtos/zephyr/pull/98406), so it's valid issue, but it's fairly harmless.

### PR DESCRIPTION
**Pull request by vignesh-aerlync**
Fix checkpatch not warning when blank line after declaration
is removed. Updated regexes to also handle context lines,
ensuring consistent detection.
    
Fixes: #98976

### CODE REVIEW

**Review by Thalley — DISMISSED** [review]
Does not seem to fix the issue

**Review by Thalley — DISMISSED** [review]
The PR seems to fix the issue (after doing proper testing). Not sure whether the changes are valid though, so someone who is more familiar with this should review

**Comment by vignesh-aerlync** [comment]
> @vignesh-aerlync I tried cherry-picking the offending commit from #98406 that caused me to create the reference issue, and then cherry-picked your commit here, but checkpatch.pl still does not fail. How did you test your changes?


Thanks for pointing that out . I tested in https://github.com/zephyrproject-rtos/zephyr/pull/98406  ,my patch missed handling that particular case you mentioned. I’ll update my change accordingly.

File: scripts/checkpatch.pl [hunk 1]
```diff
@@ -1,11 +1,13 @@
 #!/usr/bin/env perl
-# SPDX-License-Identifier: GPL-2.0
+# SPDX-License-Identifier: Apache-2.0
```
Comment (keith-zephyr) [inline scripts/checkpatch.pl]: You shouldn't drop the original license.

**Review by Thalley — DISMISSED** [review]
I can approve based on that it fixes the issue that I raised. Not sure if the changes in the file are as expected (especially in terms of the license-related changes).

File: scripts/checkpatch.pl (hunk 1 above)
Comment (keith-zephyr) [reply scripts/checkpatch.pl]: You also cannot add a new license without approval from the original copyright owner(s). 
This file is explicitly called out as being allowed because it is not linked into the firmware.
https://docs.zephyrproject.org/latest/LICENSING.html#zephyr-licensing

It's permitted to extend the copyright, but in general you should never change the license type.

**Review by keith-zephyr — CHANGES_REQUESTED** [review]

**Review by keith-zephyr — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
