### PR TITLE
Remove host API dependency in Bluetooth driver close and setup on stm32wba

### LINKED ISSUE #103594: drivers: bluetooth: stm32wba: Linker error in host-less (HCI_RAW) build
### Describe the bug

Since commit 034220c08ec5dfc871c31f1233aea64e287a922d, the function `bt_hci_stm32wba_close` calls `bt_hci_cmd_alloc` and `bt_hci_cmd_send_sync`, which are not available when `CONFIG_BT_HCI_RAW=y`, i.e. builds without host.

For example, you have a linker error when you compile the sample `hci_uart`.

A possible fix is to guard the offending calls with a check CONFIG_BT_HCI_HOST or directly call the link layer function which perform ACI_RESET.

### Regression

- [x] This is a regression.

### Steps to reproduce

`west build -b nucleo_wba55cg -d test_build zephyr/samples/bluetooth/hci_uart`

### Relevant log output

```shell
/storage/zephyr-sdk-0.17.4/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/bluetooth/libdrivers__bluetooth.a(hci_stm32wba.c.obj): in function `bt_hci_stm32wba_close':
/storage/zephyrproject/zephyr/drivers/bluetooth/hci/hci_stm32wba.c:495: undefined reference to `bt_hci_cmd_alloc'
/storage/zephyr-sdk-0.17.4/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /storage/zephyrproject/zephyr/drivers/bluetooth/hci/hci_stm32wba.c:504: undefined reference to `bt_hci_cmd_send_sync'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

All

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vtardy-st**
In the close() and setup() driver function, the host HSI APIs calls are removed.

This PR also fix issue : https://github.com/zephyrproject-rtos/zephyr/issues/103594

FYI: @asm5878, @msmttchr, @Chastillon

### CODE REVIEW

File: drivers/bluetooth/hci/hci_stm32wba.c [hunk 1]
```diff
@@ -402,25 +402,44 @@ static int bt_hci_stm32wba_open(const struct device *dev, bt_hci_recv_t recv)
...
+		aci_reset_cmd[1] = (uint8_t)ACI_RESET;
+		aci_reset_cmd[2] = (uint8_t)(ACI_RESET >> 8);
+		aci_reset_cmd[3] = 5;
+		aci_reset_cmd[4] = 0;
+		aci_reset_cmd[5] = (uint8_t)CFG_BLE_OPTIONS;
+		aci_reset_cmd[6] = (uint8_t)(CFG_BLE_OPTIONS >> 8);
+		aci_reset_cmd[7] = (uint8_t)(CFG_BLE_OPTIONS >> 16);
+		aci_reset_cmd[8] = (uint8_t)(CFG_BLE_OPTIONS >> 24);
+
+		BleStack_Request(aci_reset_cmd);
```
Comment (jhedberg) [inline drivers/bluetooth/hci/hci_stm32wba.c]: I'd consider keeping only the code in this branch. The host will not do any HCI processing after callilng `close()`, so there's no need to add a dependency to the host HCI APIs here (which is bad from a circular dependency perspective)

Comment (vtardy-st) [reply drivers/bluetooth/hci/hci_stm32wba.c]: Do you mean we should remove the bt_hci_cmd_alloc(), net_buf_add() and bt_hci_cmd_send_sync() calls in the bt_hci_stm32wba_close() function ?
Just keep the lines you highlight ?

Comment (jhedberg) [reply drivers/bluetooth/hci/hci_stm32wba.c]: Yes

Comment (jhedberg) [reply drivers/bluetooth/hci/hci_stm32wba.c]: I didn't look closer at the driver, but if you have other places (like in `setup()`) doing similar things, consider creating a helper for this.

Comment (vtardy-st) [reply drivers/bluetooth/hci/hci_stm32wba.c]: Changes have been done to remove Host HCI APis in the driver close() and setup()

**Review by asm5878 — DISMISSED** [review]

**Review by asm5878 — APPROVED** [review]

**Review by mathieuchopstm — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
