### PR TITLE
usb: Stop reversing the hardware identifier

### LINKED ISSUE #24103: USB Serial Number reverses bytes in hw identifier
Why does the default encoding of the USB serial number string descriptor reverse the byte order of the value returned by `hwinfo_get_device_id()`?  This seems wrong.

* hwid: `f7 78 63 d5 6c ae 9a 5a`
* serial number: `5A9AAE6CD56378F7`

### PR DESCRIPTION
**Pull request by carlescufi**
Now that the hardware identifier obtained with the hwinfo API is stored
in the correct order based on the platform, there is no longer the need
to reverse its bytes when populating the serial number in the
corresponding USB descriptor.

Fixes #24103

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

File: subsys/usb/usb_descriptor.c [hunk 1]
```diff
@@ -313,8 +313,8 @@ __weak u8_t *usb_update_sn_string_descriptor(void)
 	if (hwinfo_get_device_id(hwid, sizeof(hwid)) > 0) {
 		LOG_HEXDUMP_DBG(hwid, sizeof(hwid), "Serial Number");
 		for (int i = 0; i < sizeof(hwid); i++) {
-			sn[i * 2] = hex[hwid[(sizeof(hwid) - 1) - i] >> 4];
-			sn[i * 2 + 1] = hex[hwid[(sizeof(hwid) - 1) - i] & 0xF];
+			sn[i * 2] = hex[hwid[i] >> 4];
+			sn[i * 2 + 1] = hex[hwid[i] & 0xF];
```
Comment (alexanderwachter) [inline subsys/usb/usb_descriptor.c:317]: `hwinfo_get_device_id(sn, sizeof(sn));` woudl do the job right?

**Review by alexanderwachter — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Review by eobalski — APPROVED** [review]
