### PR TITLE
[RFC] stm32: clock_control: Enable device clock source selection

### LINKED ISSUE #41650: STM32H7 SPI123 incorrect clock source used for prescaler calculation
## Describe the bug
In the STM32H7 series the assumed clock source is incorrect when using SPI1, 2 or 3. This incorrect clock source is then used to calculate the clock prescaler (`SPI_CFG:MBR`), which can then potentially be calculated incorrectly. More specifically, it assumes the SCK clock source is, for example `APB2`, while it's by actually by default `PLL1Q`. This resulted that our custom STM32H743 implementation is outputting an incorrect SPI clock frequency.

This is because for the H7 series the SPI1, 2, and 3 has a _seperate_ clock domain that governs the SCK speed. See the following snippet from RM0433 Figure 609. 

image

Here `spi_ker_ck` is the `SCLK` source, not `PCLK` (f.i. `APB2`). The value of the `spi_ker_ck` is set by `RCC_D2CCIP1R : SPI123SEL`, which is `pll1_q_ck` by default.

## To Reproduce
We can slightly adjust the `nucleo_h743zi` DTS and abuse the `led_ws2812` app to easily see this behaviour.
1. I'm running this commit from the main branch `e2588d6a42`
2. Slightly adjust your code by either:
  a. Checking out [this branch](https://github.com/fancom/zephyr/tree/spi123-incorrect-clock)
  b. Applying the patch `nucleo-configuration-patch` supplied below.
    - [Optional] Add `print-clocks-output` patch to print out debugging clock information
4. `west build -p auto -b nucleo_h743zi samples/drivers/led_ws2812/`
5. `west flash` onto a `nucleo_h743zi`
6. Probe `CN7:10` (`D13` or `SPI_A_SCK` or `SPI_1_SCK`) with an oscilloscope
7. Witness the `SCK` frequency incorrectly being 6MHz instead of the desired and calculated 3MHz.

It will also output the following with the optional logging patch 
```
[00:00:00.005,000] <err> spi_ll_stm32: Is this SPI1? 1
[00:00:00.005,000] <err> spi_ll_stm32: spi clock bus: STM32_CLOCK_BUS_APB2
[00:00:00.005,000] <err> spi_ll_stm32: STM32_CLOCK_BUS_APB2 freq: 96000000
[00:00:00.005,000] <err> spi_ll_stm32: LL_RCC_SPI123_CLKSOURCE: LL_RCC_SPI123_CLKSOURCE_PLL1Q
[00:00:00.005,000] <err> spi_ll_stm32: pllq freq: 192000000
[00:00:00.005,000] <err> spi_ll_stm32: Desired frequency: 3000000
[00:00:00.005,000] <err> spi_ll_stm32: BR: 5 should create clock of freq: 3000000
[00:00:00.005,000] <err> spi_ll_stm32: Resulting actual clock clock with PLL: 6000000
````

## Expected behavior
Expect the prescaler calculation to use the correct clock source to output the desired frequency.

## Impact
Hard to notice issues with incorrect SPI frequencies meaning devices run slower/faster than designed for.

## Environment (please complete the following information):
 - OS: Linux
 - Toolchain: Zephyr SDK 0.13.2
 - Commit SHA: `e2588d6a42`

## Additional Context
I created #40998 to attempt to fix this issue, but ABOSTM found a showstopping flaw in my implementation. We then proposed a new sollution would be to:

- Use the default `spi_ker_ck` value, since it's not possible to set two clocks the DTS. This means SCK source will always be `PLL1Q`.
- When calculating the prescaler use PLL1Q clock value.
- Add checks to ensure `PPL1Q` is enabled and `#error` if not.

I will try to create a fix for this implementation soon. However, I'm not sure yet what would be the best way to calculate the `PLL1Q` frequency, and would like some thoughts on that. The way I did it in the patch below is quite ugly.

It's coincidance that this has gone unnoticed during previous SPI driver testing. If I understand correctly then the Nucleo H743zi is popular for STM32H7 testing, and the `PLL1 Q` divider usually sets the clock up by chance that `PLL1Q == APB2`. Therefore I had to change the dts in the patch below to change `pll1_q` divisor from `4` to `1` to highlight this issue.

### **nucleo-configuration-patch**
```
From 21c48a1f7ec70e773cf7639c3d0a3175ab390ff3 Mon Sep 17 00:00:00 2001
From: Hein Wessels <hein.wessels@nobleo.nl>
Date: Fri, 7 Jan 2022 14:19:30 +0100
Subject: [PATCH] nucleo config

---
 .../led_ws2812/boards/nucleo_h743.conf        |  2 +
 .../led_ws2812/boards/nucleo_h743zi.overlay   | 39 +++++++++++++++++++
 2 files changed, 41 insertions(+)
 create mode 100644 samples/drivers/led_ws2812/boards/nucleo_h743.conf
 create mode 100644 samples/drivers/led_ws2812/boards/nucleo_h743zi.overlay

diff --git a/samples/drivers/led_ws2812/boards/nucleo_h743.conf b/samples/drivers/led_ws2812/boards/nucleo_h743.conf
new file mode 100644
index 0000000000..319a42ce98
--- /dev/null
+++ b/samples/drivers/led_ws2812/boards/nucleo_h743.conf
@@ -0,0 +1,2 @@
+CONFIG_WS2812_STRIP_SPI=y
+CONFIG_SPI=y
diff --git a/samples/drivers/led_ws2812/boards/nucleo_h743zi.overlay b/samples/drivers/led_ws2812/boards/nucleo_h743zi.overlay
new file mode 100644
index 0000000000..0d1fba0ac4
--- /dev/null
+++ b/samples/drivers/led_ws2812/boards/nucleo_h743zi.overlay
@@ -0,0 +1,39 @@
+/*
+ * Copyright (c) 2021, STMicroelectronics
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <dt-bindings/led/led.h>
+
+arduino_spi: &spi1 {};
+
+
+&arduino_spi {
+	led_strip: ws2812@0 {
+		compatible = "worldsemi,ws2812-spi";
+		label = "WS2812";
+
+		/* SPI */
+		reg = <0>; /* ignored, but necessary for SPI bindings */
+		spi-max-frequency = <3000000>;
+
+		/* WS2812 */
+		chain-length = <16>; /* arbitrary; change at will */
+		spi-one-frame = <0x70>;
+		spi-zero-frame = <0x40>;
+		color-mapping = <LED_COLOR_ID_GREEN
+				 LED_COLOR_ID_RED
+				 LED_COLOR_ID_BLUE>;
+	};
+};
+
+/ {
+	aliases {
+		led-strip = &led_strip;
+	};
+};
+
+&pll{
+	div-q = <1>;
+};
\ No newline at end of file
-- 
2.25.1

```
### **print-clocks-output**

```
From e376b740607da0f007265748cdae4defbb02bc1e Mon Sep 17 00:00:00 2001
From: Hein Wessels <hein.wessels@nobleo.nl>
Date: Fri, 7 Jan 2022 14:46:26 +0100
Subject: [PATCH] Add log output

---
 drivers/spi/spi_ll_stm32.c | 94 ++++++++++++++++++++++++++++++++++++++
 1 file changed, 94 insertions(+)

diff --git a/drivers/spi/spi_ll_stm32.c b/drivers/spi/spi_ll_stm32.c
index 47a5ae01d6..d779329ca0 100644
--- a/drivers/spi/spi_ll_stm32.c
+++ b/drivers/spi/spi_ll_stm32.c
@@ -451,6 +451,72 @@ static void spi_stm32_isr(const struct device *dev)
 }
 #endif
 
+#include <stm32_ll_rcc.h>
+
+#define PLLQ_FREQ(pllsrc_freq, divm, divn, divq)	(((pllsrc_freq)*\
+							(divn))/((divm)*(divq)))
+
+static inline uint32_t get_pllsrc_frequency(void)
+{
+	switch (LL_RCC_PLL_GetSource()) {
+	case LL_RCC_PLLSOURCE_HSI:
+		return HSI_VALUE;
+	case LL_RCC_PLLSOURCE_CSI:
+		return CSI_VALUE;
+	case LL_RCC_PLLSOURCE_HSE:
+		return HSE_VALUE;
+	case LL_RCC_PLLSOURCE_NONE:
+	default:
+		return 0;
+	}
+}
+
+static uint32_t get_pllq_frequency(void)
+{
+	uint32_t sysclk = 0;
+	uint32_t hpre = 0;
+	uint32_t hsidiv = 0;
+
+	/* Get the current HSI divider */
+	switch (LL_RCC_HSI_GetDivider()) {
+	case LL_RCC_HSI_DIV2:
+		hsidiv = 2;
+		break;
+	case LL_RCC_HSI_DIV4:
+		hsidiv = 4;
+		break;
+	case LL_RCC_HSI_DIV8:
+		hsidiv = 8;
+		break;
+	case LL_RCC_HSI_DIV1:
+	default:
+		hsidiv = 1;
+		break;
+	}
+
+	/* Get the current system clock source */
+	switch (LL_RCC_GetSysClkSource()) {
+	case LL_RCC_SYS_CLKSOURCE_STATUS_HSI:
+		sysclk = HSI_VALUE/hsidiv;
+		break;
+	case LL_RCC_SYS_CLKSOURCE_STATUS_CSI:
+		sysclk = CSI_VALUE;
+		break;
+	case LL_RCC_SYS_CLKSOURCE_STATUS_HSE:
+		sysclk = HSE_VALUE;
+		break;
+	case LL_RCC_SYS_CLKSOURCE_STATUS_PLL1:
+		sysclk = PLLQ_FREQ(get_pllsrc_frequency(),
+				   LL_RCC_PLL1_GetM(),
+				   LL_RCC_PLL1_GetN(),
+				   LL_RCC_PLL1_GetQ());
+		break;
+	}
+
+	return sysclk;
+
+}
+
 static int spi_stm32_configure(const struct device *dev,
 			       const struct spi_config *config)
 {
@@ -486,13 +552,41 @@ static int spi_stm32_configure(const struct device *dev,
 		return -EIO;
 	}
 
+	LOG_ERR("Is this SPI1? %d", spi == SPI1);
+	LOG_ERR("spi clock bus: %s", cfg->pclken.bus == 3 ? "STM32_CLOCK_BUS_APB2" : "something else" );
+	LOG_ERR("STM32_CLOCK_BUS_APB2 freq: %d", clock);
+
+	switch(LL_RCC_GetSPIClockSource(LL_RCC_SPI123_CLKSOURCE)){
+		case LL_RCC_SPI123_CLKSOURCE_PLL1Q:
+			LOG_ERR("LL_RCC_SPI123_CLKSOURCE: %s", "LL_RCC_SPI123_CLKSOURCE_PLL1Q");
+			break;
+		case LL_RCC_SPI123_CLKSOURCE_PLL2P:
+			LOG_ERR("LL_RCC_SPI123_CLKSOURCE: %s", "LL_RCC_SPI123_CLKSOURCE_PLL2P");
+			break;
+		case LL_RCC_SPI123_CLKSOURCE_PLL3P:
+			LOG_ERR("LL_RCC_SPI123_CLKSOURCE: %s", "LL_RCC_SPI123_CLKSOURCE_PLL3P");
+			break;
+		case LL_RCC_SPI123_CLKSOURCE_I2S_CKIN:
+			LOG_ERR("LL_RCC_SPI123_CLKSOURCE: %s", "LL_RCC_SPI123_CLKSOURCE_I2S_CKIN");
+			break;
+		case LL_RCC_SPI123_CLKSOURCE_CLKP:
+			LOG_ERR("LL_RCC_SPI123_CLKSOURCE: %s", "LL_RCC_SPI123_CLKSOURCE_CLKP");
+			break;			
+	}	
+	LOG_ERR("pllq freq: %d", get_pllq_frequency());
+
+	LOG_ERR("Desired frequency: %d", config->frequency);
+
 	for (br = 1 ; br <= ARRAY_SIZE(scaler) ; ++br) {
 		uint32_t clk = clock >> br;
 
 		if (clk <= config->frequency) {
+			LOG_ERR("BR: %d should create clock of freq: %d", br, clk);
 			break;
 		}
 	}
+	
+	LOG_ERR("Resulting actual clock clock with PLL: %d", get_pllq_frequency() >> br);	
 
 	if (br > ARRAY_SIZE(scaler)) {
 		LOG_ERR("Unsupported frequency %uHz, max %uHz, min %uHz",
-- 
2.25.1
```

### PR DESCRIPTION
**Pull request by erwango**
**EDIT 08'22:** 
This PR was some time ago and is now largely in use. But I can now see that "alternative/alternate/optional" wording is confusing and "domain" clock would have better a better choice. If you read these lines, please keep this in mind. Follow up change: https://github.com/zephyrproject-rtos/zephyr/pull/48679

## TL;DR ##
STM32 clock_control driver update to provide a way to configure alternate clocks on peripherals that support it:
```
    clocks = <&rcc STM32_CLOCK_BUS_APB2 0x00001000>,  <- Existing, bus driven, "register" clock
             <&rcc STM32_SRC_PLL3_P SPI123_SEL(2)>;   <- Newly added alternate clock (PLL3_P output here)
```
This alternate clock source could be selected in peripheral driver thanks to new `clock_control_configure()` API:
```
	if (IS_ENABLED(STM32_SPI_OPT_CLOCK_SUPPORT) && (cfg->pclk_len > 1)) {
		if (clock_control_configure(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
					    (clock_control_subsys_t) &cfg->pclken[1],
					    NULL) != 0) {
			LOG_ERR("Could not select alternate SPI source clock");
			return -EIO;
		}
	}
```

Follow up of https://github.com/zephyrproject-rtos/zephyr/pull/42097 which was limited to H7.

## Goal
Aim of this work is to enable the use of an optional clock in a device configuration.
This is particularly required in case of STM32H7 based platform on which device clock configuration is usually based on 2 different clocks (Fixes #41650).
- A register clock, required for device configuration, usually coming from APB/AHB bus.
- A kernel clock, which will be used to clock the hardware block (and hence is the one driving the device frequency), typically derived from an alternate clck source (PLL output, fixed clock, ..)

On other STM32 series, provide the possibility to provide an alternate clock to a peripheral. For instance, configuring LSE as the LPUART or LPTIM clock, or HSI48 as the USB clock.

## Update of clock_control API (03/14):
 
Reworked to make use of new `clock_control_configure()` API, cf https://github.com/zephyrproject-rtos/zephyr/pull/43790

### Alternate clocks bindings
Additional/Alternate clocks could be fixed clocks (HSI, HSE, ..), PLL outputs (PLLX_P/Q/R), sysclock, ....
For all these clocks, I've decided to keep existing RCC device driver as the clock controller. As a consequence, the dt binding used to select a specific clock looks to:
```
	clocks = <&rcc STM32_CLOCK_BUS_APB2 0x00001000>,  <- Existing, bus driven, "register" clock
		 <&rcc STM32_SRC_PLL3_P SPI123_SEL(2)>;   <- Newly added alternate clock (PLL3_P output here)
```
Another way to support this would have been to set up each potential clock source as a clock controler on its own and use the following binding:
```
	clocks = <&rcc STM32_CLOCK_BUS_APB2 0x00001000>,  <- Existing, bus driven, "register" clock
		 <&pll3 pll_p_output SPI123_SEL(2)>;      <- Discarded binding option
```
I've discarded this second option because, to be consistent with the binding, this second option would require to instantiate each potential source clock as a device driver, each one implementing clock_control API. This would have had negative impact on code footprint, which could have been considered ok for STM32H7 series but problematic on "smaller" STM32 series.

### Use of clock-names
In #42097, I tried to comply with H7 reference manuals (`clock-names = "reg", "kernel";`). But extending to other series this was hard to find a single nomenclature matching all series. Besides, usage of `clock-names` didn't show any benefit of code simplification.
As a consequence, in this PR, I'm setting the use of `clock-names` property to optional. It is consumer driver responsibility to access and correctly use clock source cell.

### Clock mux bindings
Complete solution requires to find a way to configure clock mux (as per_ck).

First option is to add a dedicated node descibing  the clock mux. Its only property is to configure its clock input
```
&perck {
	clocks = <&rcc STM32_SRC_HSI_KER CKPER_SEL(0)>;
	status = "okay";
};
```
Works fine, main drawback is the cost (~220 bytes of flash)

A much simpler alternative was to add clock configuration directly to the clock consumer end node:
```
	clocks = <&rcc STM32_CLOCK_BUS_APB2 0x00001000>,
		 <&rcc STM32_SRC_HSI_KER CKPER_SEL(0)>,
		 <&rcc STM32_SRC_CKPER SPI123_SEL(4)>;
```
Though, this proposal has 2 main drawbacks:
- If board dts is poorly configured, 2 consumers of the same internal clock (per_ck here) could set conflicting configurations
- This adds complexity on the consumers driver implementation side that should be able to differentiate between all these clocks 

In the end the addition of a clock mux node device felt saner.

### Limitations and next steps:
- Only STM32 SPI driver is made aware of this. All STM32 drivers should be updated to take this new clock config into account.
- It is not possible today to `clock_off` supplementary clocks as they potentially clocks multiple peripherals (or even the core itself). So, this most likely requires the use of power-domains
- On some series using "common driver" some source clocks are not yet implemented (specifically the sources based on a specific PLL output, like PLL_P, this is left as a future work). For this series, I'm focusing on a common subset of source clocks: HSE, HIS, MSI, LSE, LSI, "main" PLL output and SYSCLK.

### CODE REVIEW

**Comment by erwango** [comment]
CI reported issues are not related:
```
/__w/zephyr/zephyr/tests/drivers/spi/spi_loopback/src/spi.c: In function 'cs_ctrl_gpio_config':
/__w/zephyr/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:109:2: error: 'gpio_dev' is deprecated [-Werror=deprecated-declarations]
  109 |  spi_cs.gpio_dev = device_get_binding(CS_CTRL_GPIO_DRV_NAME);
      |  ^~~~~~
```

**Comment by erwango** [comment]
@benediktibk, @r2r0, @abxy, @lmajewski, @GeorgeCGV, @ycsin, @heinwessels, @nfaurant

**Comment by lmajewski** [comment]
I'm just wondering if this approach to configure clocks in a generic way for STM32 MCU series is somewhat standard approach for other SoCs from this manufacturer?

In other words - is it only one off for STM32 or can it be applied to other M3/M4 ARM CPUs from other manufacturers (like e.g. NXP) ?

**Comment by erwango** [comment]
> I'm just wondering if this approach to configure clocks in a generic way for STM32 MCU series is somewhat standard approach for other SoCs from this manufacturer?

The change is based on a new clock_control API which is generic and proposed in standalone [here](https://github.com/zephyrproject-rtos/zephyr/pull/43790). I guess the feature itself is also generic as alternate clock source is also something common across vendors (with some exceptions).
This being said, the binding proposal is STM32 specific. It also differs from STM32 Linux bindings (which also differs from STM32 uboot bindings). Aim is to make a first step in direction of a more flexible clock framework as the lack of this feature is blocking in some cases (cf https://github.com/zephyrproject-rtos/zephyr/issues/41650 but also wake-up pin selection) and has to be implemented today per driver (cf https://github.com/zephyrproject-rtos/zephyr/pull/44988), which has limitations.

**Comment by erwango** [comment]
EDIT: I'm finding some test issues, it might not work on some cases.

File: include/zephyr/drivers/clock_control.h [hunk 1]
```diff
@@ -92,13 +92,18 @@ typedef int (*clock_control_set)(const struct device *dev,
 				 clock_control_subsys_t sys,
 				 clock_control_subsys_rate_t rate);
 
+typedef int (*clock_control_configure_fn)(const struct device *dev,
+				       clock_control_subsys_t sys,
```
Comment (GeorgeCGV) [inline include/zephyr/drivers/clock_control.h:96]: Minor, incorrectly formatted.

File: include/zephyr/dt-bindings/clock/stm32f0_clock.h [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+#define STM32_CLOCK_VAL_MASK    0x7U
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CFGRx register offset (RM0008.pdf) */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32f0_clock.h:63]: I guess it shall be `RM0091.pdf` here and below.
The `RM0008.pdf` (doesn't contain `CFGR3` register) and `RM0399.pdf` is for H7.

File: include/zephyr/dt-bindings/clock/stm32f3_clock.h [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+#define USART1_SEL(val)		STM32_CLOCK(val, 3, 0, CFGR3_REG)
+#define I2C1_SEL(val)		STM32_CLOCK(val, 1, 4, CFGR3_REG)
+#define I2C2_SEL(val)		STM32_CLOCK(val, 1, 5, CFGR3_REG)
+#define I2C3_SEL(val)		STM32_CLOCK(val, 1, 6, CFGR3_REG)
+#define TIM1_SEL(val)		STM32_CLOCK(val, 1, 8, CFGR3_REG)
+#define TIM8_SEL(val)		STM32_CLOCK(val, 1, 9, CFGR3_REG)
+#define TIM15_SEL(val)		STM32_CLOCK(val, 1, 10, CFGR3_REG)
+#define TIM16_SEL(val)		STM32_CLOCK(val, 1, 11, CFGR3_REG)
+#define TIM17_SEL(val)		STM32_CLOCK(val, 1, 13, CFGR3_REG)
+#define TIM20_SEL(val)		STM32_CLOCK(val, 1, 5, CFGR3_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32f3_clock.h:77]: The shift shall be `15` instead of `5` (based on `RM0316.pdf`).

File: include/zephyr/dt-bindings/clock/stm32f3_clock.h [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+#define STM32_CLOCK_VAL_MASK    0x7U
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CFGRx register offset */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32f3_clock.h:63]: Could be great to add the RM document in the comment like `(RM0316.pdf)`.

File: include/zephyr/dt-bindings/clock/stm32g0_clock.h [hunk 5]
```diff
@@ -17,4 +15,79 @@
...
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
+#define CCIPR_REG		0x88
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32g0_clock.h:66]: Missing `CCIPR2_REG` or?
Based on `RM0444.pdf` and `RM0454.pdf` the `CCIPR_REG` is `0x54` and `CCIPR2_REG` is `0x58`.

File: include/zephyr/dt-bindings/clock/stm32g0_clock.h [hunk 6]
```diff
@@ -17,4 +15,79 @@
...
+
+/** @brief Device clk sources selection helpers */
+/** CCIPR devices */
+#define USART1_SEL(val)		STM32_CLOCK(val, 3, 0, CCIPR_REG)
+#define USART2_SEL(val)		STM32_CLOCK(val, 3, 2, CCIPR_REG)
+#define USART3_SEL(val)		STM32_CLOCK(val, 3, 4, CCIPR_REG)
+#define CEC_SEL(val)		STM32_CLOCK(val, 1, 5, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32g0_clock.h:73]: Based on `RM0444.pdf`  the shift shall be `6` instead of `5`.

File: include/zephyr/dt-bindings/clock/stm32g4_clock.h [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
+#define CCIPR_REG		0x88
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32g4_clock.h:70]: Based on `RM0440.pdf` the address is `0x98`.

File: include/zephyr/dt-bindings/clock/stm32g4_clock.h [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+#define CCIPR_REG		0x9C
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32g4_clock.h:71]: Shall be `CCIPR_REG2` instead of `CCIPR_REG`.

File: include/zephyr/dt-bindings/clock/stm32l0_clock.h [hunk 9]
```diff
@@ -17,4 +15,62 @@
...
+
+/** @brief Device clk sources selection helpers */
+/** CCIPR1 devices */
+#define USART1_SEL(val)		STM32_CLOCK(val, 3, 0, CCIPR_REG)
+#define USART2_SEL(val)		STM32_CLOCK(val, 3, 2, CCIPR_REG)
+#define LPUART1_SEL(val)	STM32_CLOCK(val, 3, 10, CCIPR_REG)
+#define I2C1_SEL(val)		STM32_CLOCK(val, 3, 12, CCIPR_REG)
+#define I2C3_SEL(val)		STM32_CLOCK(val, 3, 16, CCIPR_REG)
+#define LPTIM1_SEL(val)		STM32_CLOCK(val, 3, 18, CCIPR_REG)
+#define HSI48_SEL(val)		STM32_CLOCK(val, 3, 26, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l0_clock.h:74]: Based on `RM0376.pdf` the mask shall be `1`.

> `Bit26`:
> 
> - `0`: PLL USB clock selected as HSI48 clock
> - `1`: RC48 clock selected as HSI48 clock

File: include/zephyr/dt-bindings/clock/stm32l1_clock.h [hunk 10]
```diff
@@ -6,14 +6,57 @@
...
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
+#define CSR_REG		0x34
+
+#define RTC_SEL(val)		STM32_CLOCK(val, 3, 16, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l1_clock.h:60]: The register shall be `CSR_REG` instead of `CCIPR_REG`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 11]
```diff
@@ -19,4 +17,86 @@
...
+#define CCIPR_REG		0x88
+#define CCIPR_REG2		0x9C
+
+/** @brief Device clk sources selection helpers */
+/** CCIPR devices */
+#define USART1_SEL(val)		STM32_CLOCK(val, 3, 0, CCIPR_REG)
+#define USART2_SEL(val)		STM32_CLOCK(val, 3, 2, CCIPR_REG)
+#define USART3_SEL(val)		STM32_CLOCK(val, 3, 4, CCIPR_REG)
+#define USART4_SEL(val)		STM32_CLOCK(val, 3, 6, CCIPR_REG)
+#define LPUART1_SEL(val)	STM32_CLOCK(val, 3, 8, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:79]: Based on `RM0351.pdf`, that shall be `USART5_SEL` not `LPUART1_SEL`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 12]
```diff
@@ -19,4 +17,86 @@
...
+#define I2C1_SEL(val)		STM32_CLOCK(val, 3, 10, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:80]: Based on `RM0351.pdf`, that shall be `LPUART1_SEL` not `I2C2_SEL`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 13]
```diff
@@ -19,4 +17,86 @@
...
+#define I2C2_SEL(val)		STM32_CLOCK(val, 3, 12, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:81]: Based on `RM0351.pdf`, that shall be `I2C1_SEL` not `I2C2_SEL`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 14]
```diff
@@ -19,4 +17,86 @@
...
+#define I2C3_SEL(val)		STM32_CLOCK(val, 3, 14, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:82]: Based on `RM0351.pdf`, that shall be `I2C2_SEL`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 15]
```diff
@@ -19,4 +17,86 @@
...
+#define LPTIM1_SEL(val)		STM32_CLOCK(val, 3, 16, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:83]: Based on `RM0351.pdf`, that shall be `I2C3_SEL`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 16]
```diff
@@ -19,4 +17,86 @@
...
+#define LPTIM2_SEL(val)		STM32_CLOCK(val, 3, 18, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:84]: Based on `RM0351.pdf`, that shall be `LPTIM1_SEL`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 17]
```diff
@@ -19,4 +17,86 @@
...
+#define LPTIM3_SEL(val)		STM32_CLOCK(val, 3, 20, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:85]: Based on `RM0351.pdf`, that shall be `LPTIM2_SEL`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 18]
```diff
@@ -19,4 +17,86 @@
...
+#define SAI1_SEL(val)		STM32_CLOCK(val, 3, 22, CCIPR_REG)
+#define SAI2_SEL(val)		STM32_CLOCK(val, 3, 24, CCIPR_REG)
+#define CLK48_SEL(val)		STM32_CLOCK(val, 3, 26, CCIPR_REG)
+#define ADC_SEL(val)		STM32_CLOCK(val, 3, 28, CCIPR_REG)
+#define SWPMI1_SEL(val)		STM32_CLOCK(val, 1, 30, CCIPR_REG)
+#define DFSDM1_SEL(val)		STM32_CLOCK(val, 1, 31, CCIPR_REG)
+/** CCIPR2 devices */
+#define I2C4_SEL(val)		STM32_CLOCK(val, 3, 0, CCIPR_REG2)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:93]: `RM0351.pdf` and `RM0394.pdf` contain information only about `I2C4_SEL`, every other bit of `CCIPR_REG2` is reserved.

In what document did you find the `DFSDM_SEL`, `ADFSDM_SEL`, `DSI_SEL`, `SDMMC_SEL`, and `OSPI_SEL` in `CCIPR_REG2` of the L4?

File: include/zephyr/dt-bindings/clock/stm32u5_clock.h [hunk 19]
```diff
@@ -21,4 +50,73 @@
...
+#define MDF1_SEL(val)		STM32_CLOCK(val, 7, 0, CCIPR2_REG)
+#define SAI1_SEL(val)		STM32_CLOCK(val, 7, 5, CCIPR2_REG)
+#define SAI2_SEL(val)		STM32_CLOCK(val, 7, 8, CCIPR2_REG)
+#define SAE_SEL(val)		STM32_CLOCK(val, 1, 11, CCIPR2_REG)
+#define RNG_SEL(val)		STM32_CLOCK(val, 3, 12, CCIPR2_REG)
+#define SDMMC_SEL(val)		STM32_CLOCK(val, 1, 14, CCIPR2_REG)
+#define OCTOSPI_SEL(val)	STM32_CLOCK(val, 3, 20, CCIPR2_REG)
+/** CCIPR3 devices */
+
 #endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_STM32U5_CLOCK_H_ */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32u5_clock.h:114]: Shall be moved to the end of the file, otherwise selectors of `CCIPR3_REG` are redefined.

Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32u5_clock.h:114]: Shall be moved to the end of the file, otherwise selectors of CCIPR3_REG are redefined.

File: include/zephyr/dt-bindings/clock/stm32wb_clock.h [hunk 20]
```diff
@@ -0,0 +1,91 @@
...
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
+#define CCIPR_REG		0x88
+
+/** @brief Device clk sources selection helpers */
+/** CCIPR devices */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32wb_clock.h:73]: Based on `RM0434.pdf`:

- There is no `USART2SEL`, `USART3SEL`, `USART4SEL`, `I2C2_SEL`, `LPTIM3_SEL`, and `SAI2_SEL`.
- `LPUART1_SEL` shift shall be `10`.
- `I2C1_SEL`  shift shall be `12`.
- `I2C3_SEL`  shift shall be `16`.
- `LPTIM1_SEL`  shift shall be `18`, `LPTIM2_SEL`  `20`.

File: include/zephyr/dt-bindings/clock/stm32wb_clock.h [hunk 21]
```diff
@@ -0,0 +1,91 @@
...
+#define STM32_CLOCK_VAL_MASK    0x7U
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32wb_clock.h:69]: Comment references `RCC_CSR` but related to `RCC_CCIPR`.

The `RCC_CSR` has `RFWKP_SEL` that might be added later on.

File: include/zephyr/dt-bindings/clock/stm32wl_clock.h [hunk 22]
```diff
@@ -20,4 +18,68 @@
...
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
+#define CCIPR_REG		0x54
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32wl_clock.h:68]: Based on `RM0453.pdf` and `RM0461.pdf` the address is `0x88`.

File: include/zephyr/dt-bindings/clock/stm32wl_clock.h [hunk 23]
```diff
@@ -20,4 +18,68 @@
...
+#define USART2_SEL(val)		STM32_CLOCK(val, 3, 2, CCIPR_REG)
+#define SPI2_I2S2_SEL(val)	STM32_CLOCK(val, 3, 8, CCIPR_REG)
+#define LPUART1_SEL(val)	STM32_CLOCK(val, 3, 10, CCIPR_REG)
+#define I2C1_SEL(val)		STM32_CLOCK(val, 3, 12, CCIPR_REG)
+#define I2C2_SEL(val)		STM32_CLOCK(val, 3, 14, CCIPR_REG)
+#define I2C3_SEL(val)		STM32_CLOCK(val, 3, 16, CCIPR_REG)
+#define LPTIM1_SEL(val)		STM32_CLOCK(val, 3, 18, CCIPR_REG)
+#define LPTIM2_SEL(val)		STM32_CLOCK(val, 3, 20, CCIPR_REG)
+#define LPTIM3_SEL(val)		STM32_CLOCK(val, 3, 22, CCIPR_REG)
+#define RNG_SEL(val)		STM32_CLOCK(val, 3, 26, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32wl_clock.h:82]: Shall be `ADC_SEL` instead of `RNG_SEL`.

File: include/zephyr/dt-bindings/clock/stm32wl_clock.h [hunk 24]
```diff
@@ -20,4 +18,68 @@
...
+#define ADC_SEL(val)		STM32_CLOCK(val, 3, 30, CCIPR_REG)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32wl_clock.h:83]: Shall be `RNG_SEL` instead of `ADC_SEL`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 25]
```diff
@@ -19,4 +17,86 @@
...
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
+#define CCIPR_REG		0x88
+#define CCIPR_REG2		0x9C
+
+/** @brief Device clk sources selection helpers */
+/** CCIPR devices */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:74]: I suggest to go over the `REG_CCIPR` in `RM0351.pdf` once more.
Many defines are incorrect.

File: include/zephyr/dt-bindings/clock/stm32g4_clock.h [hunk 26]
```diff
@@ -0,0 +1,95 @@
...
+#define STM32_CLOCK_VAL_MASK    0x7U
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32g4_clock.h:69]: Comment references `RCC_CSR` but relates to `RCC_CCIPR`.

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h [hunk 27]
```diff
@@ -19,4 +17,86 @@
...
+#define STM32_CLOCK_VAL_MASK    0x7U
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32l4_clock.h:69]: Comment references `RCC_CSR` but relates to `RCC_CCIPR`.

File: include/zephyr/dt-bindings/clock/stm32wl_clock.h [hunk 28]
```diff
@@ -20,4 +18,68 @@
...
+#define STM32_CLOCK_VAL_MASK    0x7U
+#define STM32_CLOCK_VAL_SHIFT   16U
+
+#define STM32_CLOCK(val, mask, shift, reg)					\
+	((((reg) & STM32_CLOCK_REG_MASK) << STM32_CLOCK_REG_SHIFT) |		\
+	 (((shift) & STM32_CLOCK_SHIFT_MASK) << STM32_CLOCK_SHIFT_SHIFT) |	\
+	 (((mask) & STM32_CLOCK_MASK_MASK) << STM32_CLOCK_MASK_SHIFT) |		\
+	 (((val) & STM32_CLOCK_VAL_MASK) << STM32_CLOCK_VAL_SHIFT))
+
+/** @brief RCC_CSR register offset */
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32wl_clock.h:67]: Comment references `RCC_CSR` but relates to `RCC_CCIPR`.

File: dts/bindings/clock/st,stm32-clock-mux.yaml [hunk 29]
```diff
@@ -0,0 +1,43 @@
...
+        The only property of this node is to select a clock input.
+        For instance:
+                &perck {
+                        clocks = <&rcc STM32_SRC_HSI_KER CKPER_SEL(0)>;
+                        status = "okay";
+                };
+
+compatible: "st,stm32-clock-mux"
+
+properties:
```
Comment (GeorgeCGV) [inline dts/bindings/clock/st,stm32-clock-mux.yaml:17]: Most properties are available within the `base.yaml`.
Shouldn't the bindings be based on it?

File: drivers/spi/spi_ll_stm32.c [hunk 30]
```diff
@@ -861,11 +869,20 @@ static int spi_stm32_init(const struct device *dev)
...
+			       (clock_control_subsys_t) &cfg->pclken[0]) != 0) {
 		LOG_ERR("Could not enable SPI clock");
 		return -EIO;
 	}
 
+	if (IS_ENABLED(STM32_SPI_OPT_CLOCK_SUPPORT) && (cfg->pclk_len > 1)) {
+		if (clock_control_configure(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
+					    (clock_control_subsys_t) &cfg->pclken[1],
+					    NULL) != 0) {
+			LOG_ERR("Could not select SPI soutce clock");
```
Comment (GeorgeCGV) [inline drivers/spi/spi_ll_stm32.c:881]: > `LOG_ERR("Could not select SPI soutce clock");`

Typo in `soutce`, shall be `source`.

File: drivers/clock_control/clock_stm32g4.c [hunk 31]
```diff
@@ -25,37 +24,69 @@
...
  * @brief Set up pll configuration
  */
+__unused
 int config_pll_sysclock(void)
 {
-	uint32_t pll_source, pll_m, pll_n, pll_r;
+	uint32_t pll_source;
+
+	pll_source = get_pll_source();
+	if (pll_source < 0) {
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32g4.c:52]: `get_pll_source()` returns `uint32_t`.

Therefore, `if (pll_source < 0)` is always `false`.

File: drivers/clock_control/clock_stm32g4.c [hunk 32]
```diff
@@ -25,37 +24,69 @@
...
+
+/**
+ * @brief Return pllout frequency
+ */
+__unused
+uint32_t get_pllout_frequency(void)
+{
+	uint32_t pll_source;
+
+	pll_source = get_pll_source();
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32g4.c:79]: `get_pll_source()` returns `uint32_t`.
Therefore, `if (pll_source < 0)` is always `false`.

File: drivers/clock_control/clock_stm32g0.c [hunk 33]
```diff
@@ -27,31 +26,64 @@
...
+/**
+ * @brief Set up pll configuration
+ */
+__unused
+int config_pll_sysclock(void)
+{
+	uint32_t pll_source;
+
+	pll_source = get_pll_source();
+	if (pll_source < 0) {
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32g0.c:53]: `get_pll_source()` returns `uint32_t`.
Therefore, `if (pll_source < 0)` is always `false`.

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 34]
```diff
@@ -25,30 +24,61 @@
...
+/**
+ * @brief Return pllout frequency
+ */
+__unused
+uint32_t get_pllout_frequency(void)
+{
+	uint32_t pll_source;
+
+	pll_source = get_pll_source();
+	if (pll_source < 0) {
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32f2_f4_f7.c:72]: `get_pll_source()` returns `uint32_t`.
Therefore, `if (pll_source < 0)` is always `false`.

File: drivers/clock_control/clock_stm32f0_f3.c [hunk 35]
```diff
@@ -79,6 +79,67 @@ int config_pll_sysclock(void)
...
+	 * cf Reference manual for more details
+	 */
+
+	/* Configure PLL source */
+	if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
+		pll_input_freq = STM32_HSE_FREQ;
+	} else if (IS_ENABLED(STM32_PLL_SRC_HSI)) {
+		pll_input_freq = STM32_HSI_FREQ;
+	} else {
+		return -ENOTSUP;
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32f0_f3.c:124]: it is not correct to return `-ENOTSUP` as return type is `uint32_t`.

File: drivers/clock_control/clock_stm32f0_f3.c [hunk 36]
```diff
@@ -79,6 +79,67 @@ int config_pll_sysclock(void)
...
+
+	return __LL_RCC_CALC_PLLCLK_FREQ(pll_input_freq, pll_mul, pll_div);
+#else
+	/* Configure PLL source */
+	if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
+		pll_input_freq = STM32_HSE_FREQ;
+	} else if (IS_ENABLED(STM32_PLL_SRC_HSI)) {
+		pll_input_freq = STM32_HSI_FREQ / 2;
+	}  else {
+		return -ENOTSUP;
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32f0_f3.c:135]: it is not correct to return `-ENOTSUP` as return type is `uint32_t`.

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 37]
```diff
@@ -25,30 +24,61 @@
...
+__unused
+static uint32_t get_pll_source(void)
+{
+	if (IS_ENABLED(STM32_PLL_SRC_HSI)) {
+		return LL_RCC_PLLSOURCE_HSI;
+	} else if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
+		return LL_RCC_PLLSOURCE_HSE;
+	}
+
+	return -ENOTSUP;
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32f2_f4_f7.c:39]: it is not correct to return `-ENOTSUP` as return type is `uint32_t`.

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 38]
```diff
@@ -25,30 +24,61 @@
...
-	pll_p = pllp(STM32_PLL_P_DIVISOR);
+	uint32_t pll_source;
 
-	/* Configure PLL source */
-	if (IS_ENABLED(STM32_PLL_SRC_HSI)) {
-		pll_source = LL_RCC_PLLSOURCE_HSI;
-	} else if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
-		pll_source = LL_RCC_PLLSOURCE_HSE;
-	} else {
+	pll_source = get_pll_source();
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32f2_f4_f7.c:50]: `get_pll_source()` returns `uint32_t`.
Therefore, `if (pll_source < 0)` is always `false`.

File: drivers/clock_control/clock_stm32g0.c [hunk 39]
```diff
@@ -27,31 +26,64 @@
...
 	if (IS_ENABLED(STM32_PLL_SRC_HSI)) {
-		pll_source = LL_RCC_PLLSOURCE_HSI;
+		return LL_RCC_PLLSOURCE_HSI;
 	} else if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
-		pll_source = LL_RCC_PLLSOURCE_HSE;
-	} else {
+		return LL_RCC_PLLSOURCE_HSE;
+	}
+
+	return -ENOTSUP;
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32g0.c:41]: it is not correct to return `-ENOTSUP` as return type is `uint32_t`.

File: drivers/clock_control/clock_stm32g4.c [hunk 40]
```diff
@@ -25,37 +24,69 @@
...
+static uint32_t get_pll_source(void)
+{
+	/* Configure PLL source */
+	if (IS_ENABLED(STM32_PLL_SRC_HSI)) {
+		return LL_RCC_PLLSOURCE_HSI;
+	} else if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
+		return LL_RCC_PLLSOURCE_HSE;
+	}
+
+	return -ENOTSUP;
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32g4.c:40]: it is not correct to return `-ENOTSUP` as return type is `uint32_t`.

Maybe `#ifdef` and `#error` combination is better?

File: drivers/clock_control/clock_stm32l0_l1.c [hunk 41]
```diff
@@ -26,29 +25,59 @@
...
 	if (IS_ENABLED(STM32_PLL_SRC_HSI)) {
-		pll_source = LL_RCC_PLLSOURCE_HSI;
+		return LL_RCC_PLLSOURCE_HSI;
 	} else if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
-		pll_source = LL_RCC_PLLSOURCE_HSE;
-	} else {
+		return LL_RCC_PLLSOURCE_HSE;
+	}
+
+	return -ENOTSUP;
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32l0_l1.c:40]: it is not correct to return -ENOTSUP as return type is uint32_t.
Maybe #ifdef and #error combination is better?

File: drivers/clock_control/clock_stm32l0_l1.c [hunk 42]
```diff
@@ -26,29 +25,59 @@
...
+/**
+ * @brief Return pllout frequency
+ */
+__unused
+uint32_t get_pllout_frequency(void)
+{
+	uint32_t pll_source;
+
+	pll_source = get_pll_source();
+	if (pll_source < 0) {
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32l0_l1.c:72]: `get_pll_source()` returns `uint32_t`.
Therefore, `if (pll_source < 0)` is always `false`.

File: drivers/clock_control/clock_stm32l4_l5_wb_wl.c [hunk 43]
```diff
@@ -26,12 +25,35 @@
...
 /**
  * @brief Set up pll configuration
  */
 int config_pll_sysclock(void)
 {
-	uint32_t pll_source, pll_m, pll_n, pll_r;
+	uint32_t pll_source;
+
+	pll_source = get_pll_source();
+	if (pll_source < 0) {
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32l4_l5_wb_wl.c:54]: `get_pll_source()` returns `uint32_t`.
Therefore, `if (pll_source < 0)` is always `false`.

File: drivers/clock_control/clock_stm32l4_l5_wb_wl.c [hunk 44]
```diff
@@ -26,12 +25,35 @@
...
+	/* Configure PLL source */
+	if (IS_ENABLED(STM32_PLL_SRC_HSI)) {
+		return LL_RCC_PLLSOURCE_HSI;
+	} else if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
+		return LL_RCC_PLLSOURCE_HSE;
+	} else if (IS_ENABLED(STM32_PLL_SRC_MSI)) {
+		return LL_RCC_PLLSOURCE_MSI;
+	}
+
+	return -ENOTSUP;
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32l4_l5_wb_wl.c:43]: it is not correct to return `-ENOTSUP` as return type is `uint32_t`.
Maybe `#ifdef` and `#error` combination is better?

File: drivers/clock_control/clock_stm32l4_l5_wb_wl.c [hunk 45]
```diff
@@ -40,27 +62,35 @@ int config_pll_sysclock(void)
...
+/**
+ * @brief Return pllout frequency
+ */
+__unused
+uint32_t get_pllout_frequency(void)
+{
+	uint32_t pll_source;
+
+	pll_source = get_pll_source();
+	if (pll_source < 0) {
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32l4_l5_wb_wl.c:84]: `get_pll_source()` returns `uint32_t`.
Therefore, `if (pll_source < 0)` is always `false`.

File: include/zephyr/dt-bindings/clock/stm32f3_clock.h (hunk 4 above)
Comment (erwango) [reply include/zephyr/dt-bindings/clock/stm32f3_clock.h:63]: Well, I actually removed them to simplify things. One should be able to find them if needed (I do advise to use STM32McuFinder for this purpose).

File: dts/bindings/clock/st,stm32-clock-mux.yaml (hunk 29 above)
Comment (erwango) [reply dts/bindings/clock/st,stm32-clock-mux.yaml:17]: I intentionally didn't use base.yaml in order to limit the number of properties, as this kind of device has only one  purpose which is to set a clk source.

File: drivers/clock_control/clock_stm32l0_l1.c (hunk 41 above)
Comment (erwango) [reply drivers/clock_control/clock_stm32l0_l1.c]: This is indeed one part that requires more thinking.
Switched to asserts

**Comment by erwango** [comment]
@GeorgeCGV Thanks for the review. I hope I fixed most of the comments. I also took care to fix tests, so it should now be fully functional (at least close to).

File: drivers/clock_control/clock_stm32g0.c [hunk 46]
```diff
@@ -27,31 +26,56 @@
...
+/**
+ * @brief Return pllout frequency
+ */
+__unused
+uint32_t get_pllout_frequency(void)
+{
+	uint32_t pll_source;
+
+	pll_source = get_pll_source();
+	if (pll_source < 0) {
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32g0.c:69]: `if (pll_source < 0)` is always `false`.
Better to use `if (pll_source == 0)`.

Also, L4 and L5 define `LL_RCC_PLLSOURCE_NONE` that is `0`.

File: include/zephyr/dt-bindings/clock/stm32g4_clock.h [hunk 47]
```diff
@@ -0,0 +1,95 @@
...
+#define LPTIM2_SEL(val)		STM32_CLOCK(val, 3, 18, CCIPR_REG)
+#define LPTIM3_SEL(val)		STM32_CLOCK(val, 3, 20, CCIPR_REG)
+#define SAI1_SEL(val)		STM32_CLOCK(val, 3, 22, CCIPR_REG)
+#define SAI2_SEL(val)		STM32_CLOCK(val, 3, 24, CCIPR_REG)
+#define CLK48_SEL(val)		STM32_CLOCK(val, 3, 26, CCIPR_REG)
+#define ADC12_SEL(val)		STM32_CLOCK(val, 3, 28, CCIPR_REG)
+#define ADC34_SEL(val)		STM32_CLOCK(val, 3, 30, CCIPR_REG)
+/** CCIPR2 devices */
+#define I2C4_SEL(val)		STM32_CLOCK(val, 3, 0, CCIPR_REG2)
+#define QSPI_SEL(val)		STM32_CLOCK(val, 3, 20, CCIPR_REG2)
```
Comment (GeorgeCGV) [inline include/zephyr/dt-bindings/clock/stm32g4_clock.h:93]:
```
#define I2C4_SEL(val)		STM32_CLOCK(val, 3, 0, CCIPR_REG2)
#define QSPI_SEL(val)		STM32_CLOCK(val, 3, 20, CCIPR_REG2)
```

Shall use `CCIPR2_REG` defined above.

**Comment by GeorgeCGV** [comment]
> @GeorgeCGV Thanks for the review. I hope I fixed most of the comments. I also took care to fix tests, so it should now be fully functional (at least close to).

The `stm32wl_clock.h` has some critical issues: cl https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r859509619.

File: include/zephyr/dt-bindings/clock/stm32g4_clock.h (hunk 47 above)
Comment (erwango) [reply include/zephyr/dt-bindings/clock/stm32g4_clock.h:93]: Txs. I wonder how this doesn't trigger compilation issue...
There should be something I'm missing.

File: drivers/clock_control/clock_stm32g0.c (hunk 46 above)
Comment (erwango) [reply drivers/clock_control/clock_stm32g0.c]: Fixed

**Comment by erwango** [comment]
> The `stm32wl_clock.h` has some critical issues: [#45053 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r859509619).

Fixed

File: drivers/clock_control/clock_stm32_ll_u5.c [hunk 48]
```diff
@@ -71,6 +71,97 @@ static uint32_t get_startup_frequency(void)
...
+					STM32_PLL_N_MULTIPLIER,
+					STM32_PLL_R_DIVISOR);
+#elif defined(STM32_SYSCLK_SRC_MSIS)
+	return get_msis_frequency();
+#elif defined(STM32_SYSCLK_SRC_HSE
+	return STM32_HSE_FREQ;
+#elif defined(STM32_SYSCLK_SRC_HSI)) {
+	return STM32_HSI_FREQ;
+#else
+	__ASSERT(0, "No SYSCLK Source configured");
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32_ll_u5.c:100]: Missing `return 0;`

File: drivers/clock_control/clock_stm32_mux.c [hunk 49]
```diff
@@ -0,0 +1,48 @@
...
+
+struct stm32_clk_mux_config {
+	const struct stm32_pclken pclken;
+};
+
+static int stm32_clk_mux_init(const struct device *dev)
+{
+	const struct stm32_clk_mux_config *cfg = dev->config;
+
+	if (clock_control_on(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32_mux.c:28]: The formatting of arguments is a bit off.

File: drivers/clock_control/clock_stm32_mux.c [hunk 50]
```diff
@@ -0,0 +1,48 @@
...
+}
+
+#define STM32_MUX_CLK_INIT(id)						\
+									\
+static const struct stm32_clk_mux_config stm32_clk_mux_cfg_##id = {	\
+	.pclken = STM32_INST_CLOCK_INFO(id, 0)				\
+};									\
+									\
+DEVICE_DT_INST_DEFINE(id, &stm32_clk_mux_init, NULL,			\
+		    NULL, &stm32_clk_mux_cfg_##id,			\
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32_mux.c:44]: The formatting is a bit off.

File: drivers/clock_control/clock_stm32l0_l1.c [hunk 51]
```diff
@@ -26,29 +25,44 @@
...
 	} else if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
-		pll_source = LL_RCC_PLLSOURCE_HSE;
-	} else {
-		return -ENOTSUP;
+		return LL_RCC_PLLSOURCE_HSE;
 	}
 
-	LL_RCC_PLL_ConfigDomain_SYS(pll_source, pll_mul, pll_div);
-
+	__ASSERT(0, "Invalid source");
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32l0_l1.c:40]: Minor.

Some `__ASSERT(0, "Invalid source");` use uppercase for `Invalid`, while others (i.e.  `clock_stm32g4.c` line `40`) use lowercase `invalid source`.

Would be better to use single format approach.

File: drivers/spi/spi_ll_stm32.c [hunk 52]
```diff
@@ -489,10 +489,18 @@ static int spi_stm32_configure(const struct device *dev,
 #endif
 }
```
Comment (GeorgeCGV) [inline drivers/spi/spi_ll_stm32.c:491]: Formatting is a bit off at lines:
- `494`
- `500`
- `872`

Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:491]: Suggestion?

**Review by GeorgeCGV — COMMENTED** [review]
Open Questions

- https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r859475801

Minor

- Not corrected, but marked as fixed: https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r859564584
- https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r860631293
- https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r859427966
- https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r860619407
- https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r860620003
- https://github.com/zephyrproject-rtos/zephyr/pull/45053#discussion_r860635835

*edited: fixed links*

File: drivers/spi/spi_ll_stm32.c (hunk 52 above)
Comment (GeorgeCGV) [reply drivers/spi/spi_ll_stm32.c:491]: 494:
Added <kbd>Tab</kbd> and 2x <kbd>Space</kbd>.
```c
		if (clock_control_get_rate(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
					  (clock_control_subsys_t) &cfg->pclken[1], &clock) < 0) {
			LOG_ERR("Failed call clock_control_get_rate(pclk[1])");
			return -EIO;
		}
```

500:
Added <kbd>Tab</kbd> and 2x <kbd>Space</kbd>.
```c
		if (clock_control_get_rate(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
					  (clock_control_subsys_t) &cfg->pclken[0], &clock) < 0) {
			LOG_ERR("Failed call clock_control_get_rate(pclk[0])");
			return -EIO;
		}
```

872:
Removed 3x <kbd>Space</kbd>.
```c
	if (clock_control_on(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
			    (clock_control_subsys_t) &cfg->pclken[0]) != 0) {
		LOG_ERR("Could not enable SPI clock");
		return -EIO;
	}
```

File: include/zephyr/dt-bindings/clock/stm32l4_clock.h (hunk 18 above)
Comment (erwango) [reply include/zephyr/dt-bindings/clock/stm32l4_clock.h]: RM0432

File: drivers/clock_control/clock_stm32l0_l1.c (hunk 51 above)
Comment (erwango) [reply drivers/clock_control/clock_stm32l0_l1.c:40]: Done

File: drivers/spi/spi_ll_stm32.c (hunk 52 above)
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:491]: Done

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 53]
```diff
@@ -26,29 +25,44 @@
...
 	} else if (IS_ENABLED(STM32_PLL_SRC_HSE)) {
-		pll_source = LL_RCC_PLLSOURCE_HSE;
-	} else {
-		return -ENOTSUP;
+		return LL_RCC_PLLSOURCE_HSE;
 	}
 
-	LL_RCC_PLL_ConfigDomain_SYS(pll_source, pll_m, pll_n, pll_p);
+	__ASSERT(0, "invalid source");
+}
```
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:41]: Done

File: dts/bindings/clock/st,stm32-clock-mux.yaml (hunk 29 above)
Comment (GeorgeCGV) [reply dts/bindings/clock/st,stm32-clock-mux.yaml:17]: Makes sense. 

I don't know if there is any policy regarding bindings and using shared inclusions. Shared properties need to be kept in sync. That increases the error possibility in the future.

Comment (erwango) [reply dts/bindings/clock/st,stm32-clock-mux.yaml:17]: This is right. Fixed

File: drivers/clock_control/clock_stm32_ll_common.c [hunk 54]
```diff
@@ -106,6 +169,38 @@ static inline int stm32_clock_control_off(const struct device *dev,
...
+					STM32_CLOCK_SHIFT_GET(pclken->enr);
+	reg = (uint32_t *)(DT_REG_ADDR(DT_NODELABEL(rcc)) +
+					STM32_CLOCK_REG_GET(pclken->enr));
+	reg_val = *reg;
+	reg_val |= dt_val;
+	*reg = reg_val;
+
+	return 0;
+#else
+	/* No srce clock available: Not supported */
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32_ll_common.c:200]: > srce

minor, typo

File: drivers/clock_control/clock_stm32_ll_common.c [hunk 55]
```diff
@@ -106,6 +169,38 @@ static inline int stm32_clock_control_off(const struct device *dev,
...
+	/* At least one alt srce clock available */
+	struct stm32_pclken *pclken = (struct stm32_pclken *)(sub_system);
+	volatile uint32_t *reg;
+	uint32_t reg_val, dt_val;
+
+	ARG_UNUSED(dev);
+	ARG_UNUSED(data);
+
+	if (enabled_clock(pclken->bus) < 0) {
+		/* Attemp to configure a src clock not available or not valid */
```
Comment (GeorgeCGV) [inline drivers/clock_control/clock_stm32_ll_common.c:186]: > Attemp

Minor, missing `t`.

File: drivers/clock_control/clock_stm32_ll_u5.c [hunk 56]
```diff
@@ -115,6 +207,33 @@ static inline int stm32_clock_control_off(const struct device *dev,
...
+{
+	struct stm32_pclken *pclken = (struct stm32_pclken *)(sub_system);
+	volatile uint32_t *reg;
+	uint32_t reg_val, dt_val;
+
+	ARG_UNUSED(dev);
+	ARG_UNUSED(data);
+
+	if (enabled_clock(pclken->bus) < 0) {
+		/* Attemp to configure a src clock not available or not valid */
```
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/clock_control/clock_stm32_ll_u5.c]: Fixed, thanks for the review

**Review by microbuilder — DISMISSED** [review]
Can't comment on every detail of specific ST clock config being unfamiliar with some of the devices, and have to rely on CI somewhat given the size of the PR, but the general approach of specifying multiple clocks in DT seems sane to me:

```
clocks = <&rcc STM32_CLOCK_BUS_APB2 0x00001000>,
	<&rcc STM32_SRC_PLL3_P SPI123_SEL(2)>;
```

File: drivers/clock_control/clock_stm32_ll_h7.c [hunk 57]
```diff
@@ -321,6 +322,66 @@ static uint32_t get_vco_output_range(uint32_t vco_input_range)
...
+	case STM32_SRC_HSE:
+		if (!IS_ENABLED(STM32_HSE_ENABLED)) {
+			r = -ENOTSUP;
+		}
+		break;
+	case STM32_SRC_LSE:
+		if (!IS_ENABLED(STM32_LSE_ENABLED)) {
+			r = -ENOTSUP;
+		}
+		break;
```
Comment (gmarull) [inline drivers/clock_control/clock_stm32_ll_h7.c:357]: suggestion here, maybe this would be more compact

```c
	if ((src_clk == STM32_SRC_SYSCLK) ||
	    ((src_clk == STM32_SRC_HSE) && IS_ENABLED(STM32_HSE_ENABLED)) ||
	    ((src_clk == STM32_SRC_LSE) && IS_ENABLED(STM32_LSE_ENABLED)) ||
	    ...
	    ((src_clk == STM32_SRC_PLL3_R) && IS_ENABLED(STM32_PLL3_R_ENABLED))){
		return 0;
	}

	return -ENOTSUP;
```

File: drivers/clock_control/clock_stm32_ll_h7.c [hunk 58]
```diff
@@ -321,6 +322,66 @@ static uint32_t get_vco_output_range(uint32_t vco_input_range)
 
 #endif /* ! CONFIG_CPU_CORTEX_M4 */
 
+/** @Brief Verifies clock is part of actve clock configuration */
```
Comment (gmarull) [inline drivers/clock_control/clock_stm32_ll_h7.c:325]: `@brief`

File: drivers/clock_control/clock_stm32_ll_h7.c [hunk 59]
```diff
@@ -373,6 +434,38 @@ static inline int stm32_clock_control_off(const struct device *dev,
...
+	struct stm32_pclken *pclken = (struct stm32_pclken *)(sub_system);
+	volatile uint32_t *reg;
+	uint32_t reg_val, dt_val;
+
+	ARG_UNUSED(dev);
+	ARG_UNUSED(data);
+
+	if (enabled_clock(pclken->bus) < 0) {
+		/* Attemp to configure a src clock not available or not valid */
+		return -ENOTSUP;
```
Comment (gmarull) [inline drivers/clock_control/clock_stm32_ll_h7.c:465]: better propagate error code

File: drivers/spi/spi_ll_stm32.c [hunk 60]
```diff
@@ -861,11 +869,20 @@ static int spi_stm32_init(const struct device *dev)
...
 		LOG_ERR("Could not enable SPI clock");
 		return -EIO;
 	}
 
+	if (IS_ENABLED(STM32_SPI_OPT_CLOCK_SUPPORT) && (cfg->pclk_len > 1)) {
+		if (clock_control_configure(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
+					    (clock_control_subsys_t) &cfg->pclken[1],
+					    NULL) != 0) {
+			LOG_ERR("Could not select SPI source clock");
+			return -EIO;
```
Comment (gmarull) [inline drivers/spi/spi_ll_stm32.c:882]: nit: propagate error code here

File: drivers/spi/spi_ll_stm32.c [hunk 61]
```diff
@@ -971,17 +988,20 @@ static void spi_stm32_irq_config_func_##id(const struct device *dev)		\
...
+					       STM32_DT_INST_CLOCKS(id);\
+									\
 static const struct spi_stm32_config spi_stm32_cfg_##id = {		\
 	.spi = (SPI_TypeDef *) DT_INST_REG_ADDR(id),			\
-	.pclken = {							\
-		.enr = DT_INST_CLOCKS_CELL(id, bits),			\
-		.bus = DT_INST_CLOCKS_CELL(id, bus)			\
-	},								\
+	.pclken = pclken_##id,						\
+	.pclk_len = DT_INST_NUM_CLOCKS(id),				\
```
Comment (gmarull) [inline drivers/spi/spi_ll_stm32.c:1004]: one suggestion here:

similar to what we do in pinctrl, I'd create another struct that contains the array and size, so that drivers can simply do:

```
STM32_DT_INST_CLOCKS_DEFINE(id);
```

Then device stores a reference to the defined structure.

**Review by gmarull — COMMENTED** [review]
in general lgtm, a few minor suggestions

**Comment by erwango** [comment]
Rebased to take into account migration to <zephyr/...> and fix related conflicts.

File: drivers/clock_control/clock_stm32_ll_h7.c (hunk 57 above)
Comment (erwango) [reply drivers/clock_control/clock_stm32_ll_h7.c]: Indeed. Done. I've converted U5 as well. 
On `_common.c` there are intermixed `#ifdef FOO` that don't show up well in the `if` format. Maybe that's a matter of taste, but anyway I've kept as is.

File: drivers/spi/spi_ll_stm32.c (hunk 61 above)
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:1004]: Indeed. I though about it but wanted to see how the whole feature is used across drivers before that.
Would it be fine to deploy in a second step. I agree it makes the transition a little bit 'harder' tough.

**Comment by erwango** [comment]
@gmarull Thanks for the review. I've taken into account the comments and pushed once more. Agreed on the pinctrl like macro, but I prefer to introduce it in a second step.

**Review by gmarull — APPROVED** [review]
I haven't gone into implementation details, but the overall approach looks reasonable to me. Improvements can be made later, e.g. clocks definition.

**Review by microbuilder — APPROVED** [review]
