### PR TITLE
NXP LPSPI: Fix some regressions

### LINKED ISSUE #86145: tests: tests/drivers/spi/spi_loopback: frdm_mcxn236/mcxn236: failed: Failed harness:'Testsuite failed'
**Describe the bug**
below case are failed
drivers.spi.loopback.spi_loopback.spi_loopback

test is failed on v4.1.0-rc1-207-gad845fd12c02 on frdm_mcxn236/mcxn236
testcase path is tests/drivers/spi/spi_loopback

see logs for details

**To Reproduce**
1. 
```
scripts/twister -p frdm_mcxn236/mcxn236  -T tests/drivers/spi/spi_loopback --sub-test drivers.spi.loopback
```
or
```
# west twister -p frdm_mcxn236/mcxn236 -T tests/drivers/spi/spi_loopback --sub-test drivers.spi.loopback
```
2. See error

```
Failed harness:'Testsuite failed'
```

**Expected behavior**
test pass

**Impact**

**Logs and console output**

```
START - test_spi_loopback
I: SPI test on buffers TX/RX 0x30004260/0x30004240, frame size = 8
I: SPI test slow config
I: Start complete multiple
E: Buffer contents are different: 0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x39,0x61,0x62,0x63,0x64,0x65,0x66,0x2d,0x00,
E:                            vs: 0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x2d,0x00,0x54,0x68,0x65,0x71,0x75,0x69,0x63,
Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:145: spi_complete_multiple: (1 is true)
Buffer contents are different
FAIL - test_spi_loopback in 0.048 seconds

    
```

```
*** Booting Zeph*** Booting Zephyr OS build v4.1.0-rc1-207-gad845fd12c02 ***
Running TESTSUITE spi_loopback
===================================================================
START - test_spi_loopback
I: SPI test on buffers TX/RX 0x30004260/0x30004240, frame size = 8
I: SPI test slow config
I: Start complete multiple
E: Buffer contents are different: 0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x39,0x61,0x62,0x63,0x64,0x65,0x66,0x2d,0x00,
E:                            vs: 0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x2d,0x00,0x54,0x68,0x65,0x71,0x75,0x69,0x63,

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:145: spi_complete_multiple: (1 is true)
Buffer contents are different
 FAIL - test_spi_loopback in 0.048 seconds
===================================================================
TESTSUITE spi_loopback failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -   0.00% [spi_loopback]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.048 seconds
 - FAIL - [spi_loopback.test_spi_loopback] duration = 0.048 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: 19fafad7d3909f3c183219257651200d
PROJECT EXECUTION FAILED


```

**Environment (please complete the following information):**
 - OS: (e.g. Linux ): posix
 - Toolchain (e.g Zephyr SDK): zephyr
 - Commit SHA or Version used: v4.1.0-rc1-207-gad845fd12c02

### LINKED ISSUE #86148: tests: tests/drivers/spi/spi_loopback/drivers: spi:  test Timeout
**Describe the bug**
 test is Timeout on v4.1.0-rc1-207-gad845fd12c02 on frdm_ke17z/mke17z7
testcase path is tests/drivers/spi/spi_loopback/drivers/spi/loopback

see logs for details

git bisect found below pr introduce this issue
```
https://github.com/zephyrproject-rtos/zephyr/pull/85529
```

**To Reproduce**
1. 
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p frdm_ke17z/mke17z7  --sub-test drivers.spi.loopback
```
or
```
# cd tests/tests/drivers/spi/spi_loopback/drivers/spi/loopback
# west build -b frdm_ke17z/mke17z7
# west flash
```
2. See error

**Expected behavior**
test pass

**Impact**

**Logs and console output**

```
*** Booting Zephyr OS build v4.1.0-rc1-207-gad845fd12c02 ***
Running TESTSUITE spi_loopback
===================================================================
START - test_spi_loopback
I: SPI test on buffers TX/RX 0x20004220/0x20004200, frame size = 8, DMA enabled (without CONFIG_NOCACHE_MEMORY)
I: SPI test slow config
I: Start complete multiple
E: ***** HARD FAULT *****
E: r0/a1:  0x00000000  r1/a2:  0x00007928  r2/a3:  0x400650b0
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x000039b1
E:  xpsr:  0x61000000
E: Faulting instruction address (r15/pc): 0x00002d76
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20004440 (test_spi_loopback)
E: Halting system

    
```
**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: v4.1.0-rc1-207-gad845fd12c02

### PR DESCRIPTION
**Pull request by decsny**
Fixes #86148
Fixes #86145

see commit message for detail, fixes fault on ke17z, fixes DT of mcxn236, and fixes high latency regression of repeated spi transfers

### CODE REVIEW

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 1]
```diff
@@ -57,22 +62,23 @@ int spi_mcux_configure(const struct device *dev, const struct spi_config *spi_cf
...
+
 		while ((base->CR & LPSPI_CR_MEN_MASK) != 0U) {
 			/* Wait until LPSPI is disabled. Datasheet:
 			 * After writing 0, MEN (Module Enable) remains set until the LPSPI has
 			 * completed the current transfer and is idle.
 			 */
 		}
+
+		base->CR |= LPSPI_CR_RST_MASK;
+		base->CR |= LPSPI_CR_RRF_MASK | LPSPI_CR_RTF_MASK;
```
Comment (Raymond0225) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:80]: I think you can remove these lines as they have already initialized in LPSPI_MasterInit

Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:80]: actually, I just realized, they are still in the wrong place

Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: @Raymond0225  I updated the PR to do an alternative workaround but I still need to test on S32 hardware, so it will remain on draft still

**Review by tbursztyka — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
