### PR TITLE
tests: net: Fix conn_mgr_monitor tests 

### LINKED ISSUE #85816: tests: tests/net/conn_mgr_monitor/net.conn_mgr.dad failed with W5500
**Describe the bug**

The `tests/net/conn_mgr_monitor/net.conn_mgr.dad` fails on `w5500_evb_pico` (and `w5500_evb_pico2`).

This occurred with w5500_evb_pico2, which I am currently creating, but it seems the same problem is occurring with w5500_evb_pico, so I filed an error report.

https://github.com/zephyrproject-rtos/zephyr/pull/84834#issuecomment-2645731473

**To Reproduce**

```
west twister --device-testing --device-serial /dev/ttyACM0 -p w5500_evb_pico2/rp2350a/m33 -s tests/net/conn_mgr_monitor/net.conn_mgr.dad -xOPENOCD=/usr/local/bin/openocd
```

This occurred to me with the w5500_evb_pico2 that I am currently creating, but it seems that the same problem is also occurring with the w5500_evb_pico.

**Expected behavior**

Pass the test.

**Impact**

Partially inoperable

**Logs and console output**
```
(.venv) $ cat twister-out/w5500_evb_pico2_rp2350a_m33/zephyr/tests/net/conn_mgr_monitor/net.conn_mgr.dad/handler.log
*** Booting Zephyr OS build v4.0.0-4998-g290416ef5a78 ***
Running TESTSUITE conn_mgr_monitor
===================================================================
START - test_DAD
 PASS - test_DAD in 0.162 seconds
===================================================================
START - test_cycle_ready_CC
 PASS - test_cycle_ready_CC in 0.103 seconds
===================================================================
START - test_cycle_ready_CIC
cycle_ignored_iface
Expect no events.
 PASS - test_cycle_ready_CIC in 0.679 seconds
===================================================================
START - test_cycle_ready_CINC
cycle_ignored_iface
Expect no events.
 PASS - test_cycle_ready_CINC in 0.679 seconds
===================================================================
START - test_cycle_ready_CNC
 PASS - test_cycle_ready_CNC in 0.104 seconds
===================================================================
START - test_cycle_ready_NCC
 PASS - test_cycle_ready_NCC in 0.103 seconds
===================================================================
START - test_cycle_ready_NCIC
cycle_ignored_iface
Expect no events.
 PASS - test_cycle_ready_NCIC in 0.679 seconds
===================================================================
START - test_cycle_ready_NCINC
cycle_ignored_iface
Expect no events.
 PASS - test_cycle_ready_NCINC in 0.679 seconds
===================================================================
START - test_cycle_ready_NCNC
 PASS - test_cycle_ready_NCNC in 0.103 seconds
===================================================================
START - test_cycle_states_connected_ipv46

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/conn_mgr_monitor/src/main.c:881: cycle_iface_states: (stats.conn_count_ipv6 not equal to 1)
NET_EVENT_L4_IPV6_CONNECTED should be fired when IPv6 connectivity is gained.
 FAIL - test_cycle_states_connected_ipv46 in 0.652 seconds
===================================================================
START - test_cycle_states_connected_ipv64

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/conn_mgr_monitor/src/main.c:881: cycle_iface_states: (stats.conn_count_ipv6 not equal to 1)
NET_EVENT_L4_IPV6_CONNECTED should be fired when IPv6 connectivity is gained.
 FAIL - test_cycle_states_connected_ipv64 in 0.652 seconds
===================================================================
START - test_cycle_states_simple_ipv46

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/conn_mgr_monitor/src/main.c:881: cycle_iface_states: (stats.conn_count_ipv6 not equal to 1)
NET_EVENT_L4_IPV6_CONNECTED should be fired when IPv6 connectivity is gained.
 FAIL - test_cycle_states_simple_ipv46 in 0.652 seconds
===================================================================
START - test_cycle_states_simple_ipv64

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/conn_mgr_monitor/src/main.c:881: cycle_iface_states: (stats.conn_count_ipv6 not equal to 1)
NET_EVENT_L4_IPV6_CONNECTED should be fired when IPv6 connectivity is gained.
 FAIL - test_cycle_states_simple_ipv64 in 0.652 seconds
===================================================================
START - test_ignore_while_ready

    Assertion failed at WEST_TOPDIR/zephyr/tests/net/conn_mgr_monitor/src/main.c:1085: conn_mgr_monitor_test_ignore_while_ready: (stats.conn_count_ipv6 not equal to 1)
NET_EVENT_L4_IPV6_CONNECTED should be fired when online iface is watched.
 FAIL - test_ignore_while_ready in 0.391 seconds
===================================================================
START - test_ignores
 PASS - test_ignores in 0.051 seconds
===================================================================
TESTSUITE conn_mgr_monitor failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  66.67% [conn_mgr_monitor]: pass = 10, fail = 5, skip = 0, total = 15 duration = 6.341 seconds
 - PASS - [conn_mgr_monitor.test_DAD] duration = 0.162 seconds
 - PASS - [conn_mgr_monitor.test_cycle_ready_CC] duration = 0.103 seconds
 - PASS - [conn_mgr_monitor.test_cycle_ready_CIC] duration = 0.679 seconds
 - PASS - [conn_mgr_monitor.test_cycle_ready_CINC] duration = 0.679 seconds
 - PASS - [conn_mgr_monitor.test_cycle_ready_CNC] duration = 0.104 seconds
 - PASS - [conn_mgr_monitor.test_cycle_ready_NCC] duration = 0.103 seconds
 - PASS - [conn_mgr_monitor.test_cycle_ready_NCIC] duration = 0.679 seconds
 - PASS - [conn_mgr_monitor.test_cycle_ready_NCINC] duration = 0.679 seconds
 - PASS - [conn_mgr_monitor.test_cycle_ready_NCNC] duration = 0.103 seconds
 - FAIL - [conn_mgr_monitor.test_cycle_states_connected_ipv46] duration = 0.652 seconds
 - FAIL - [conn_mgr_monitor.test_cycle_states_connected_ipv64] duration = 0.652 seconds
 - FAIL - [conn_mgr_monitor.test_cycle_states_simple_ipv46] duration = 0.652 seconds
 - FAIL - [conn_mgr_monitor.test_cycle_states_simple_ipv64] duration = 0.652 seconds
 - FAIL - [conn_mgr_monitor.test_ignore_while_ready] duration = 0.391 seconds
 - PASS - [conn_mgr_monitor.test_ignores] duration = 0.051 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: ffb7f7944fd0fb4e237d657e32bd8709
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**

- OS: Ubuntu (WSL2)
- Toolchain Zephyr SDK
- Commit SHA or Version used

The head of https://github.com/zephyrproject-rtos/zephyr/pull/84834 and applying following patch.

```
diff --git a/boards/wiznet/w5500_evb_pico2/w5500_evb_pico2_rp2350a_m33.yaml b/boards/wiznet/w5500_evb_pico2/w5500_evb_pico2_rp2350a_m33.yaml
index aea485945f3..a541d3ef036 100644
--- a/boards/wiznet/w5500_evb_pico2/w5500_evb_pico2_rp2350a_m33.yaml
+++ b/boards/wiznet/w5500_evb_pico2/w5500_evb_pico2_rp2350a_m33.yaml
@@ -19,3 +19,4 @@ supported:
   - spi
   - uart
   - watchdog
+  - netif:eth
```

### PR DESCRIPTION
**Pull request by rlubos**
Fix the root cause behind the test suite failure on `qemu_cortex_m3` (invalid L2 address used in tests).

Fix 2 other issues identified along the way:
 * clearing neighbor cache on IPv6 address removal
 * setting up DAD timer in case of NS sending failures

Fixes #85816

### CODE REVIEW

File: subsys/net/ip/net_if.c [hunk 1]
```diff
@@ -1298,21 +1298,25 @@ void net_if_ipv6_start_dad(struct net_if *iface,
...
+		k_mutex_lock(&lock, K_FOREVER);
+		sys_slist_find_and_remove(&active_dad_timers,
+					  &ifaddr->dad_node);
+		sys_slist_append(&active_dad_timers, &ifaddr->dad_node);
+		k_mutex_unlock(&lock);
+
+		/* FUTURE: use schedule, not reschedule. */
+		if (!k_work_delayable_remaining_get(&dad_timer)) {
+			k_work_reschedule(&dad_timer,
+						K_MSEC(DAD_TIMEOUT));
```
Comment (jukkar) [inline subsys/net/ip/net_if.c:1319]: We could probably place these to one line after the indentation change.

**Review by jukkar — DISMISSED** [review]
Looks great. I wonder if we should remove the earlier tweaks for timeouts that were done for conn_mgr tests? On the other hand if things work ok now, the timeouts should not matter at all. Anyway, just a thought.

**Review by pdgendt — DISMISSED** [review]
Backport needed?

File: subsys/net/ip/net_if.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/ip/net_if.c]: Fixed

**Comment by rlubos** [comment]
Backport labels added. @jukkar As you say, the earlier timeout changes weren't too invasive and tests seem pretty stable now so I'd keep them as is.

**Review by jukkar — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
