### PR TITLE
tests: kernel: fix unhandled return values.

### LINKED ISSUE #18443: [Coverity CID :203454]Error handling issues in /tests/kernel/mem_protect/sys_sem/src/main.c
Static code scan issues seen in File: /tests/kernel/mem_protect/sys_sem/src/main.c
 Category: Error handling issues
 Function: sem_multiple_threads_wait_helper
 Component: Tests
 CID: 203454
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by wentongwu**
Fix coverity issue 203454 and 203507. Fix unhandled return values as most other places of the same function handled in this file.

Fixes: #18443 and #18445.

### CODE REVIEW

File: tests/kernel/mutex/sys_mutex/src/main.c [hunk 1]
```diff
@@ -429,7 +431,11 @@ void test_main(void)
 	k_mem_domain_add_thread(&ztest_mem_domain, THREAD_09);
 	k_mem_domain_add_thread(&ztest_mem_domain, THREAD_11);
 #endif
-	sys_mutex_lock(&not_my_mutex, K_NO_WAIT);
+	rv = sys_mutex_lock(&not_my_mutex, K_NO_WAIT);
+	if (rv != 0) {
+		TC_ERROR("Failed to take mutex %p\n", &not_my_mutex);
```
Comment (aescolar) [inline tests/kernel/mutex/sys_mutex/src/main.c]: Is it intended that this will not fail the testcase?
If this ever fails, sanitycheck will not detect this as a failure..
i.e. hacking the condition to `if(1) {` you'd get
```
***** Booting Zephyr OS build zephyr-v1.14.0-3283-g62fa472919a7 *****
FAIL - test_main@436. Failed to take mutex 0x5660f1b4
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Review by aescolar — CHANGES_REQUESTED** [review]

File: tests/kernel/mem_protect/sys_sem/src/main.c [hunk 2]
```diff
@@ -116,8 +116,12 @@ void sem_take_multiple_high_prio_helper(void *p1, void *p2, void *p3)
 
 void sem_multiple_threads_wait_helper(void *p1, void *p2, void *p3)
 {
+	s32_t ret_value;
```
Comment (aescolar) [inline tests/kernel/mem_protect/sys_sem/src/main.c]: By the way, if you are changing things, maybe it would be better to set this as int to match the sys_sem_take return type

**Comment by aescolar** [comment]
@wentongwu Side issue: Could you correct your machine time? The commits time is several hours ahead of reality, which can confuse others quite a bit.

**Review by nashif — CHANGES_REQUESTED** [review]
@wentongwu please fix your commit messages: "fix coverity issue " is not a proper commit message, please specify what you have fixed in details, nobody cares if this from coverity or not.

**Comment by nashif** [comment]
and fix your system time.

File: tests/kernel/mutex/sys_mutex/src/main.c (hunk 1 above)
Comment (wentongwu) [reply tests/kernel/mutex/sys_mutex/src/main.c]: @aescolar Thanks. I will change it.

**Review by aescolar — DISMISSED** [review]
Seems you forgot the TC_ERROR part? or is that intended?

**Comment by wentongwu** [comment]
> Seems you forgot the TC_ERROR part? or is that intended?

that is intended, if lock the mutex failed, unlock will tell the case failed. And this print doesn't change the original execution path. @aescolar

**Review by aescolar — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
@nashif could you revisit this one?

**Review by nashif — APPROVED** [review]
