### PR TITLE
kernel: fix default z_arch_cpu_halt()

### LINKED ISSUE #18973: z_arch_system_halt() does not block interrupts
**Describe the bug**
The `z_arch_system_halt()` is implemented in the following way:
```
FUNC_NORETURN __weak void z_arch_system_halt(unsigned int reason)
{
        ARG_UNUSED(reason);

        /* TODO: What's the best way to totally halt the system if SMP
         * is enabled?
         */

        (void)z_arch_irq_lock();
        for (;;) {
                k_cpu_idle();
        }
}
```

This function seems to block all interrupts and halt the CPU, which is intention here.
However the `k_cpu_idle()` unconditionally enable interrupts. As result, the interrupts
can be executed.

**Expected behavior**
The ` z_arch_system_halt()` should completely halt the system.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
k_cpu_idle() re-enables interrupts. Just spin
instead.

Fixes: #18973

Signed-off-by: Andrew Boie <andrewboie@gmail.com>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@cvinayak @joakimtoe @jhedberg I've been keeping a patch like this for a long time now, never realized it was a real bug...

**Review by galak — APPROVED** [review]

**Review by andyross — APPROVED** [review]

File: kernel/fatal.c [hunk 1]
```diff
@@ -26,7 +26,7 @@ FUNC_NORETURN __weak void z_arch_system_halt(unsigned int reason)
 
 	(void)z_arch_irq_lock();
 	for (;;) {
-		k_cpu_idle();
```
Comment (pizi-nordic) [inline kernel/fatal.c]: Are we assuming that power consumption does not matter here?
