### PR TITLE
net: websockets: Fix send with large payload

### LINKED ISSUE #40256: websocket: the size of a websocket payload is limited
**Description**
I try to send a websocket payload larger than 1444 bytes. The websocket log doesn't return any error but the data never arrives at the receiver. The whole content of the payload seems to reach the ./sys/socket.h sendmsg(...) function. 

A payload with a size up to 1444 bytes is transmitted flawlessly.

My receiver is a FastAPI app running on an ASGI web server. Receiving the same websocket payload larger than 1444 bytes sent with Python websockets works without any problems.

**Expected behavior**
Sending payloads larger than 1444 bytes.

**Impact**
Cannot send payload larger than 1444 bytes.

**Logs and console output**
When the payload is larger than 1444 bytes :
<dbg> net_websocket.websocket_send_msg: (): [0x200182e0] Len 1445 TEXT/1/final

When the payload is not larger than 1444 bytes :
<dbg> net_websocket.websocket_send_msg: (): [0x200182e0] Len 1444 TEXT/1/final  

**Environment**
    OS: Ubuntu 20.04LTS
    Toolchain Zephyr SDK
    Zephyr version : 2.7.0

**Hardware**
    nucleo_f746zg

### PR DESCRIPTION
**Pull request by rlubos**
In case the payload and header size exceeded the network MTU size,
`websocket_send_msg()` would only send a part of the payload,
effectively leading to erronous results if called again to send the
rest. Fix the issue, by calling `sendmsg()` in a loop internally in case
it did not manage to send the entire websocket message in a single call.

Fixes #40256

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
CC @gitificial

File: subsys/net/lib/websocket/websocket.c [hunk 1]
```diff
@@ -518,6 +518,46 @@ static int websocket_ioctl_vmeth(void *obj, unsigned int request, va_list args)
...
+	int ret, i;
+	size_t offset = 0;
+	size_t total_len = 0;
+
+	for (i = 0; i < message->msg_iovlen; i++) {
+		total_len += message->msg_iov[i].iov_len;
+	}
+
+	while (offset < total_len) {
+		ret = zsock_sendmsg(sock, message, 0);
```
Comment (jukkar) [inline subsys/net/lib/websocket/websocket.c:533]: We need to pass the flags to `sendmsg()` call. The timeout will be checked internally in sendmsg implementation so we do not need to do it here.

**Review by jukkar — COMMENTED** [review]
Looks good, one minor tweak needed.

File: subsys/net/lib/websocket/websocket.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/lib/websocket/websocket.c]: Right, fixed now.

**Review by mniestroj — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
