### PR TITLE
Bluetooth: drivers: userchan: Fix gcc 13 overflow warning

### LINKED ISSUE #76912: drivers/bluetooth/hci/userchan.c build waring w gcc13
**Describe the bug**
drivers/bluetooth/hci/userchan.c builds with a warning w gcc13,
as it seems to believe the number of read bytes may overflow the frame_size type.

Note gcc 13 is the default w Ubuntu 24.04

**To Reproduce**
Steps to reproduce the behavior (w gcc 13)
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=native_sim ../samples/hello_world/ -DCONFIG_BT=y
3. ninja

**Expected behavior**
No build warning

**Impact**
Failing twister tests (~20), build warning when using this driver

**Logs and console output**
```
In file included from ...
                 from zephyr/include/zephyr/types.h:11,
                 from zephyr/include/zephyr/kernel_includes.h:21,
                 from zephyr/include/zephyr/kernel.h:17,
                 from zephyr/drivers/bluetooth/hci/userchan.c:9:
In function ‘read’,
    inlined from ‘rx_thread’ at drivers/bluetooth/hci/userchan.c:201:9: /usr/include/i386-linux-gnu/bits/unistd.h:28:10: warning: ‘__read_alias’ specified size between 4294902273 and 4294967295 exceeds maximum object size 2147483647 [-Wstringop-overflow=]
   28 |   return __glibc_fortify (read, __nbytes, sizeof (char),
      |          ^~~~~~~~~~~~~~~
drivers/bluetooth/hci/userchan.c: In function ‘rx_thread’: drivers/bluetooth/hci/userchan.c:187:32: note: destination object allocated here
  187 |                 static uint8_t frame[512];
      |                                ^~~~~
/usr/include/i386-linux-gnu/bits/unistd-decl.h:29:16: note: in a call to function ‘__read_alias’ declared with attribute ‘access (write_only, 2, 3)’
   29 | extern ssize_t __REDIRECT_FORTIFY (__read_alias, (int __fd, void *__buf,
      |                ^~~~~~~~~~~~~~~~~~
```

**Environment (please complete the following information):**

 - OS: Linux, Ubuntu 24.04
 - Toolchain: Host gcc 13
 - Commit SHA or Version used: main as of now a747d1a747eed85cca29a3b4961eeb18aea5d70e

### PR DESCRIPTION
**Pull request by aescolar**
gcc 13 produces a build warning (see below), as it seems to believe the number of read bytes may overflow the frame_size type.
Let's increase the frame_size bitwidth to avoid this. (Any 32bit type, signed or unsigned, avoids this warning)

The build warning:
```
In file included from /usr/include/features.h:502,
                 from /usr/include/i386-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-linux-gnu/13/include/stdint.h:9,
                 from zephyr/include/zephyr/types.h:11,
                 from zephyr/include/zephyr/kernel_includes.h:21,
                 from zephyr/include/zephyr/kernel.h:17,
                 from zephyr/drivers/bluetooth/hci/userchan.c:9:
In function ‘read’,
    inlined from ‘rx_thread’ at drivers/bluetooth/hci/userchan.c:201:9:
/usr/include/i386-linux-gnu/bits/unistd.h:28:10: warning: ‘__read_alias’ specified size
between 4294902273 and 4294967295 exceeds maximum object size 2147483647
[-Wstringop-overflow=]
   28 |   return __glibc_fortify (read, __nbytes, sizeof (char),
      |          ^~~~~~~~~~~~~~~
drivers/bluetooth/hci/userchan.c: In function ‘rx_thread’:
drivers/bluetooth/hci/userchan.c:187:32: note: destination object allocated here
  187 |                 static uint8_t frame[512];
      |                                ^~~~~
/usr/include/i386-linux-gnu/bits/unistd-decl.h:29:16: note: in a call to function
‘__read_alias’ declared with attribute ‘access (write_only, 2, 3)’
   29 | extern ssize_t __REDIRECT_FORTIFY (__read_alias, (int __fd, void *__buf,
      |                ^~~~~~~~~~~~~~~~~~
```

Fixes #76912

### CODE REVIEW

File: drivers/bluetooth/hci/userchan.c [hunk 1]
```diff
@@ -181,7 +181,7 @@ static void rx_thread(void *p1, void *p2, void *p3)
 
 	LOG_DBG("started");
 
-	uint16_t frame_size = 0;
+	int frame_size = 0;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:184]: Wouldn't `ssize_t` be a better type, considering the usage (e.g. doing operations together with other `ssize_t` variables like `len`)?

That said, there's `int32_t decoded_len` later in the function which might be better updated to `ssize_t` too.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/userchan.c (hunk 1 above)
Comment (aescolar) [reply drivers/bluetooth/hci/userchan.c]: changed :)

**Review by jhedberg — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]
