### PR TITLE
net: mqtt-sn: Wait for SUBACK and REGACK

### LINKED ISSUE #84644: MQTT-SN doesn't not wait for SUBACK or REGACK befor sending the next SUBSCRIBE or REGISTER packet
**Describe the bug**
The MQTT-SN spec says:

> 6.5 Topic Name Registration Procedur
> ...
> At any point in time a client may have only one REGISTER message outstanding, i.e. it has to wait for a
REGACK message before it can register another topic name.
> ...
> 6.9 Client’s Topic Subscribe/Un-subscribe Procedure
> ...
> As for the REGISTER procedure, a client may have only one SUBSCRIBE or one UNSUBCRIBE transaction
open at a time.
> ...

The provided MQTT-SN library does not wait for  either SUBACK or REGACK before sending the next subscribe or register packet nor does it provide an event to let the library user handle that. 

**To Reproduce**

Just add a second call to `mqtt_sn_subscribe` in the https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/net/mqtt_sn_publisher/src/udp.c

**Expected behavior**

The MQTT-SN client should send the first packet, wait for the SUBACK or REGACK then continue processing the topic list.

**Impact**

I'm not sure how MQTT-SN gateway will behave regarding this. At the moment I'm prototyping and there's no actual MQTT GW or server, so I'm handling that. I'm not sure how an actual SN GW or MQTT broker implementation` wouldl handle that.

**Logs and console output**

N/A

**Environment (please complete the following information):**

I'm on 6c5454b22ee under linux developing on a nrf5340 dev board.

**Additional context**

This could probably be easily implemented in the by just having two flags in the client so that it knows it's waiting for a SUBACK/REGACK.

### PR DESCRIPTION
**Pull request by BeckmaR**
Closes #84644 

Signed-off-by: Rene Beckmann <rene.bckmnn@gmail.com>

### CODE REVIEW

File: subsys/net/lib/mqtt_sn/mqtt_sn.c [hunk 1]
```diff
@@ -725,7 +746,19 @@ static int process_topics(struct mqtt_sn_client *client, int64_t *next_cycle)
...
+				if (subscribing) {
+					/*
+					 * Only one topic can be subscribing or unsubscribing
+					 * at the same time
+					 */
+					break;
+				}
+				topic->state = MQTT_SN_TOPIC_STATE_SUBSCRIBING;
+				LOG_INF("Topic subscription now in progress");
+				/* fallthrough */
```
Comment (jukkar) [inline subsys/net/lib/mqtt_sn/mqtt_sn.c:759]: The fallthrough should be marked as
```
__fallthrough;
```

Comment (BeckmaR) [reply subsys/net/lib/mqtt_sn/mqtt_sn.c]: fixed

Comment (BeckmaR) [reply subsys/net/lib/mqtt_sn/mqtt_sn.c]: ooc, I assume that's a hint for the compiler. Why does it not complain about the `__fallthrough` missing?

Comment (jukkar) [reply subsys/net/lib/mqtt_sn/mqtt_sn.c]: The compiler will accept also `/* fallthrough */` as zephyr code used that earlier (and there seems to be still code that uses the old way), but at some point the code base was changed to use `__fallthrough` which is the preferred way.

File: subsys/net/lib/mqtt_sn/mqtt_sn.c [hunk 2]
```diff
@@ -743,6 +820,12 @@ static int process_ping(struct mqtt_sn_client *client, int64_t *next_cycle)
 	return 0;
 }
 
+/**
+ * @brief Housekeeping task for the gateway search
+ *
+ * @param next_cycle will be set to the time when the next action is required
+ * @retval 0 on success
+ */
 static int process_search(struct mqtt_sn_client *client, int64_t *next_cycle)
```
Comment (rlubos) [inline subsys/net/lib/mqtt_sn/mqtt_sn.c:883]: Just for the sake of completness - the `client` line is missing in doxygen. Although we don't render docs from `*.c` files anyway.

**Review by rlubos — DISMISSED** [review]
Looks reasonable, thanks!

File: subsys/net/lib/mqtt_sn/mqtt_sn.c (hunk 2 above)
Comment (jukkar) [reply subsys/net/lib/mqtt_sn/mqtt_sn.c:883]: I think we should fix the missing parameter even if we do not render these docs, people could still read the source file and it is helpful if the documentation is correct.

Comment (BeckmaR) [reply subsys/net/lib/mqtt_sn/mqtt_sn.c:884]: Done - even though there is no deeper explanation still

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
