### PR TITLE
drivers: counter: Fix references in the doxygen comment

### LINKED ISSUE #17176: deprecated counter_set_alarm is referenced in documentation
`counter_set_alarm` has been deprecated since before the API was updated in master, but there are at least two functions where the documentation references it instead of its functional replacement, `counter_set_channel_alarm`, which is not referenced anywhere.

Personally I'd prefer if the documentation comment for the deprecated function included a pointer to the new way to do what it did (which in this case is `counter_set_top_value` not `counter_set_channel_alarm`).  Last I looked Zephyr's deprecation process did not clearly describe how deprecated functions should be documented, but since the replacement for the original semantics is not the obvious expected replacement for the name, it could be worth adding some detail.

### PR DESCRIPTION
**Pull request by nordic-krch**
Doxygen comment was referencing deprecated function counter_set_alarm
when the intention was to reference counter_set_channel_alarm.

Fixes #17176.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Review by anangl — APPROVED** [review]

File: include/drivers/counter.h [hunk 1]
```diff
@@ -444,7 +444,7 @@ static inline u32_t z_impl_counter_get_top_value(struct device *dev)
 
 /**
  * @brief Function to retrieve maximum relative value that can be set by
- *        counter_set_alarm.
+ *        counter_set_channel_alarm.
```
Comment (ioannisg) [inline include/drivers/counter.h]: would you add a "@ref" here, too, @nordic-krch ?

**Review by ioannisg — APPROVED** [review]
