### PR TITLE
sched: timeout: Do not miss slice timeouts

### LINKED ISSUE #29705: reel_board: tests/kernel/sched/schedule_api/ fails on multiple boards
EDIT: Affects multiple Nordic boards and mec15xxevb_assy6853

**Describe the bug**
Running tests/kernel/sched/schedule_api/ on reel board. Assertion in test_slice_reset failed in both kernel.scheduler and kernel.scheduler.multiq testcases. 

**To Reproduce**
1. west build -p auto -b reel_board tests/kernel/sched/schedule_api/
2. west flash

**Expected behavior**
Test should pass.

**Impact**
Test suite fails.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.4.0-1133-ge4e3ab3cc315  ***
Running test suite threads_scheduling
===================================================================
START - test_bad_priorities
PASS - test_bad_priorities
===================================================================
START - test_priority_cooperative
PASS - test_priority_cooperative
===================================================================
START - test_priority_preemptible
PASS - test_priority_preemptible
===================================================================
START - test_priority_preemptible_wait_prio
PASS - test_priority_preemptible_wait_prio
===================================================================
START - test_yield_cooperative
PASS - test_yield_cooperative
===================================================================
START - test_sleep_cooperative
PASS - test_sleep_cooperative
===================================================================
START - test_sleep_wakeup_preemptible
PASS - test_sleep_wakeup_preemptible
===================================================================
START - test_pending_thread_wakeup
PASS - test_pending_thread_wakeup
===================================================================
START - test_time_slicing_preemptible
PASS - test_time_slicing_preemptible
===================================================================
START - test_time_slicing_disable_preemptible
PASS - test_time_slicing_disable_preemptible
===================================================================
START - test_lock_preemptible
PASS - test_lock_preemptible
===================================================================
START - test_unlock_preemptible
PASS - test_unlock_preemptible
===================================================================
START - test_unlock_nested_sched_lock
PASS - test_unlock_nested_sched_lock
===================================================================
START - test_sched_is_preempt_thread
PASS - test_sched_is_preempt_thread
===================================================================
START - test_slice_reset
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:91: thread_time_slice: (t <= expected_slice_max is false)
timeslice too big, expected 6555 got 7208
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c:88: thread_time_slice: (t >= expected_slice_min is false)
timeslice too small, expected 6553 got 617
FAIL - test_slice_reset
===================================================================
START - test_slice_scheduling
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
PASS - test_slice_scheduling
===================================================================
START - test_priority_scheduling
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
PASS - test_priority_scheduling
===================================================================
START - test_wakeup_expired_timer_thread
PASS - test_wakeup_expired_timer_thread
===================================================================
START - test_user_k_wakeup
PASS - test_user_k_wakeup
===================================================================
START - test_user_k_is_preempt
PASS - test_user_k_is_preempt
===================================================================
Test suite threads_scheduling failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS
 - Toolchain Zephyr SDK 0.11.2
 - Zephyr version zephyr-v2.4.0-1133-ge4e3ab3cc315

### PR DESCRIPTION
**Pull request by ceolin**
Time slices don't have a timeout struct associated and stored in
timeout_list. Time slice timeout is direct programmed in the system
clock and tracked in _current_cpu->slice_ticks.

There is one issue where the time slice timeout can be missed because
the system clock is re-programmed to a longer timeout. To this happens,
it is only necessary that the timeout_list is empty (any timeout set)
and a new timeout longer than remaining time slice is set. This is cause
because z_add_timeout does not check for the slice ticks.

Fixes #29705

### CODE REVIEW

File: kernel/timeout.c [hunk 1]
```diff
@@ -127,7 +127,22 @@ void z_add_timeout(struct _timeout *to, _timeout_func_t fn,
 		}
 
 		if (to == first()) {
+#if CONFIG_TIMESLICING
+			/*
+			 * This is not ideal, since it does not
+			 * account the time elapsed since the the
+			 * last announcement, and slice_ticks is based
```
Comment (andyross) [inline kernel/timeout.c:134]: The elapsed() predicate in this file does exactly that, the driver is required to provide it.  It's a wrapper around z_clock_elapsed() that also handles the case where a timeout is submitted from inside the handler for another timeout (where we want to use the time the timeout was scheduled as "now" and not the potentially later current time -- long bikeshed about that from a few years back).

Comment (ceolin) [reply kernel/timeout.c:134]: Have you looked the sample I put in the commit message ? That code is failing without this fix because the drivers are unconditionally overriding the current timeout in the function `z_clock_set_timeout` if I remember correctly. Though if there is a contract with the drivers about it we should fix them.

I honestly don't remember all details of this fix, but the problem exists, this test systematically fails, the first slice runs for a longer period.

Comment (ceolin) [reply kernel/timeout.c:134]: @andy the problem is that if the next timeout is `current_cpu->slice_ticks ` returned by `next_timeout()` the timer should not being set again, since it is already configured. If we call `z_clock_set_timeout` with this value we lost the time between the last announcement and *now*.

**Comment by andyross** [comment]
I'm getting more and more confused as I look at this.  As I see it, the logic you're adding already exists in next_timeout(): https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/timeout.c#L79  The calculation of the next timeout to schedule is already being clamped to be no higher than an in-progress timeslice.

Why is the older code not working?  Presumably you should remove it while moving it, but I still don't think I completely understand the fix.

**Comment by ceolin** [comment]
> I'm getting more and more confused as I look at this. As I see it, the logic you're adding already exists in next_timeout(): https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/timeout.c#L79 The calculation of the next timeout to schedule is already being clamped to be no higher than an in-progress timeslice.
> 
> Why is the older code not working? Presumably you should remove it while moving it, but I still don't think I completely understand the fix.

This is clear:
```
			/* timeout  */
			int32_t timeout = next_timeout();
			if (_current_cpu->slice_ticks != timeout) {
				z_clock_set_timeout(timeout, false);
			}
```
Imagine that ` current_cpu->slice_tick` is 10, and the last number of ticks that happened since the last announcement and *now* is 5. The current code will call `z_clock_set_timeout(next_timeout(), false)`. In this case, next_timeout() will return 10 and consequently `z_clock_set_timeout()` will program the timer to 10 ticks from *now*, ignoring that has elapsed 5 ticks since the last announcement  causing the timeslice be bigger than it should.
What we have to do is, if `next_timeout()` == `_current_cpu->slice_ticks` no programming the timer to `_current_cpu->slice_ticks`

File: kernel/timeout.c (hunk 1 above)
Comment (ceolin) [reply kernel/timeout.c:134]: Having this comparison here is annoying me, but next_timeout() can not simply return a negative value in this case because negative value can mean `K_FOREVER`, can add a parameter in that function though, but not sure if this would be clear.

File: kernel/timeout.c [hunk 2]
```diff
@@ -127,7 +127,22 @@ void z_add_timeout(struct _timeout *to, _timeout_func_t fn,
...
+			 * on that. It means the that time remaining for
+			 * the next announcement can be lesser than
+			 * slice_ticks.
+			 */
+			if (_current_cpu->slice_ticks <= 0 ||
+			    next_timeout() < _current_cpu->slice_ticks) {
+				z_clock_set_timeout(next_timeout(), false);
+			}
```
Comment (andyross) [inline kernel/timeout.c:142]: Coming back to look super-carefully...

OK, I think I understand what you're saying.  The logic here is indeed duplicating effectively identical code inside next_timeout().  But next_timeout() has a bug where it will return "slice_ticks" as its result, **forgetting** that elapsed() may not be zero due to unannounced ticks.

Are you sure you can't fix this inside next_timeout() by just subtracting ticks_elapsed from the result?  That would seem cleaner.  Absent that, you should be able to remove the older code entirely, I don't see why we need both.

**Review by andyross — APPROVED** [review]
OK, I think I get it now.  Giving this a +1 so we can get it merged.  If the collision with the older clamp logic continues to bug me we can always fix it via a cleanup patch later.

**Comment by ceolin** [comment]
@nashif would you mind take a look ? The failing test happens in upstream code, I believe that platform has other issues.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by jenmwms — APPROVED** [review]

**Comment by nashif** [comment]
CI failure unrelated and already on master
