### PR TITLE
Bluetooth: Controller: Fix timings for Tx test

### LINKED ISSUE #42534: BLE Testing functions do not work properly
I am using Nordic nRF5340DK with Zephyr 2.7.0 LTS SDK. I am using built in j-link and SES(Segger Embedded Studio) to debug. I also use emptyapp from nordic on the application core and example HCI uart from /samples/bluetooth/hci_uart and set CONFIG_BT_CTLR_DTM_HCI=y in prj.conf

I am using nrf testing applications like RSSI Viewer and DTM test demos on Windows and code for nRF5340DK is being build in linux Debian enviroment. 

**The issue:**
When I use HCI command LE Transmitter Test the test packets stop transmitting after certain time or packet count(around ~4000).
I cant find any workaround to this issue, yet it is needed for Bluetooth hardware testing. 
The DTM sample app from nRF Connect SDK works as expected but they are not compatible with Bluetooth stack.

**To Reproduce**
Build an Empty Application Core from Nordic, to give control for network core, from their repository. 
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/nrf5340/empty_app_core/README.html

Build an HCI-UART application with setting:  **CONFIG_BT_CTLR_DTM_HCI=y** 

1.Run SES and load HCI-UART example application to the network core,
2.load empty application core to the network core,
3.connect the UART of nrf5340 to rtt-uart output of NRF5340DK to proceed with attaching HCI-BLE to linux
4. On linux(debian in my case) run as su : _btattach -B /dev/ttyACM1 -S 1000000 -P h4 &_
5. now open the RSSI Viewer application on another Nordic developement kit and start it to watch the BLE radio spectrum.
6. now on the linux run the hci tool and send command: _hcitool -i hci1 cmd 0x08 0x1e 0x02 0x20 0x00 0x00_ (HCI_LE_Transmitter_Test 
[v2] from specification BLE 5.2 Vol 4, Part E) It should start sending packets with PRBS9 at channel 2 with length of 32 bytes, until issuance of the command hcitool -i hci1 cmd 0x08 0x1f (LE_Test_End)

**Expected behavior**
The Bluetooth stack should transmit test packets continuously until receiving LE_Test_End command from HCI interface, yet it spontaneously stops transmitting sooner than the command LE_Test_End.

**Additional info**
The same issue happens when in network core app directly is being called ll_test_tx() function from subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c - the packets suddenly stop transmitting after some time.

### PR DESCRIPTION
**Pull request by KAGA164**
The Tx interval is now calculated once per each
Tx test and the next transmission is triggerd by
the switch timer instead of event timer. This
fixes a corner case issue when timer rollover.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/42534.

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c [hunk 1]
```diff
@@ -187,38 +204,24 @@ static void isr_tx(void *param)
...
-	/* TODO: check for probable stale timer capture being set */
+	radio_tmr_end_capture();
 
 #if defined(HAL_RADIO_GPIO_HAVE_PA_PIN)
 	radio_gpio_pa_setup();
-	radio_gpio_pa_lna_enable(t + radio_tx_ready_delay_get(test_phy,
-							      test_phy_flags) -
+	radio_gpio_pa_lna_enable(radio_tmr_tifs_base_get() +
+				 tx_tifs +
+				 radio_tx_ready_delay_get(test_phy, test_phy_flags) -
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:224]:
```suggestion
	radio_gpio_pa_lna_enable(radio_tmr_tifs_base_get() +
				 tx_tifs -
				 radio_tx_ready_delay_get(test_phy, test_phy_flags) -
```

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c [hunk 2]
```diff
@@ -634,7 +639,12 @@ uint8_t ll_test_tx(uint8_t chan, uint8_t len, uint8_t type, uint8_t phy,
 	test_cte_len = cte_len;
 #endif /* CONFIG_BT_CTLR_DF_CTE_TX */
 
-	radio_switch_complete_and_disable();
+	/* Set the initial value of the TIFS. It will be tuned up after
+	 * the first packet transmission.
+	 */
+	radio_tmr_tifs_set(SCAN_INT_UNIT_US);
+	radio_switch_complete_and_b2b_tx(test_phy, test_phy_flags, test_phy, test_phy_flags);
+
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:647]: The second PDU will not be at a multiple of 625us slot, this is not correct.

Instead modify `calculate_tifs()` to calculate the tIFS using the PDU length and PHY used, use it here and in `isr_tx` so that first and consecutive PDUs will all be at 625us slot multiples.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c [hunk 3]
```diff
@@ -168,10 +169,26 @@ static int create_iq_report(bool crc_ok)
...
+	l = radio_tmr_end_get() - radio_tmr_ready_get();
+
+#if defined(CONFIG_BT_CTLR_DF_CTE_TX)
+	interval = ceiling_fraction((l + CTE_LEN_US(test_cte_len) + 249), SCAN_INT_UNIT_US) *
+		   SCAN_INT_UNIT_US;
+#else
+	interval = ceiling_fraction((l + 249), SCAN_INT_UNIT_US) * SCAN_INT_UNIT_US;
+#endif /* CONFIG_BT_CTLR_DF_CTE_TX */
 
+	return interval - l;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:187]: Here `l` is (ready delay + PDU len), calculation is missing substracting the `radio_tx_ready_delay_get(test_phy, test_phy_flags);`

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c [hunk 4]
```diff
@@ -698,6 +708,7 @@ uint8_t ll_test_rx(uint8_t chan, uint8_t phy, uint8_t mod_idx, uint8_t expected_
 #endif /* CONFIG_BT_CTLR_DTM_HCI_DF_IQ_REPORT */
 
 	radio_pkt_rx_set(radio_pkt_scratch_get());
+	radio_tmr_tifs_set(EVENT_IFS_US);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:711]: Have this unrelated change in separate commit.

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c (hunk 1 above)
Comment (KAGA164) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c]: Fixed

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c (hunk 4 above)
Comment (KAGA164) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:699]: It is related, because tifs was set previously in init function for both Tx and Rx tests. However now we start use a tifs for Tx test with different value so I needed to move it here for Rx test.

**Review by cvinayak — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c [hunk 5]
```diff
@@ -482,6 +460,24 @@ static bool check_rx_cte(bool cte_ready)
...
+
+#if defined(CONFIG_BT_CTLR_DF_CTE_TX)
+	/* Include additional byte for the CTEInfo field and CTE length in microseconds. */
+	transmit_time = PDU_US((test_cte_len > 0) ? (len + 1) : len, 0, test_phy, test_phy_flags) +
+			CTE_LEN_US(test_cte_len);
+#else
+	transmit_time = PDU_US(len, 0, test_phy, test_phy_flags);
+#endif /* CONFIG_BT_CTLR_DF_CTE_TX */
+
+	interval = ceiling_fraction((transmit_time + 249), SCAN_INT_UNIT_US) * SCAN_INT_UNIT_US;
```
Comment (grochu) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:476]: It would be good to document the magic number, though I know it comes from the original code.

**Review by grochu — COMMENTED** [review]
The changes look good, please find 1 minor comment.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c (hunk 5 above)
Comment (KAGA164) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:480]: I like this idea. Done

**Review by grochu — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
