### PR TITLE
Handle SYS_CLOCK_TICKS_PER_SEC != 100 in tests

### LINKED ISSUE #15983: Kernel tests assume SYS_CLOCK_TICKS_PER_SEC=100
Merging https://github.com/zephyrproject-rtos/zephyr/pull/15707
and in particular this commit:
https://github.com/zephyrproject-rtos/zephyr/commit/c76dd1edb75001f853cfc0e23ed627f49889b2c6

Made the following tests start failing:

```
nrf52840_pca10056         tests/kernel/tickless/tickless_concept/kernel.tickless FAILED: failed
    see: sanity-out/nrf52840_pca10056/tests/kernel/tickless/tickless_concept/kernel.tickless/handler.log

total complete:    1/   3  33%  failed:    1

nrf52840_pca10056         tests/kernel/sched/schedule_api/kernel.sched       FAILED: failed
    see: sanity-out/nrf52840_pca10056/tests/kernel/sched/schedule_api/kernel.sched/handler.log

total complete:    2/   3  66%  failed:    2

nrf52840_pca10056         tests/kernel/timer/timer_api/kernel.timer          FAILED: failed
    see: sanity-out/nrf52840_pca10056/tests/kernel/timer/timer_api/kernel.timer/handler.log
```

### PR DESCRIPTION
**Pull request by pizi-nordic**
This PR updates tests to properly handle the SYS_CLOCK_TICKS_PER_SEC != 100 by taking under account effect of tick granularity in tested API. Also, as the measurement become more precise, the timing requirements were tightened.

Details are available in code and description of the commits.

Fixes: #15983
Introduces workaround for #16195

### CODE REVIEW

File: tests/kernel/tickless/tickless_concept/src/main.c [hunk 1]
```diff
@@ -108,13 +126,23 @@ void test_tickless_slice(void)
 	/*enable time slice*/
 	k_sched_time_slice_set(SLICE_SIZE, K_PRIO_PREEMPT(0));
 
+	/*synchronize to tick boundary*/
+	k_sleep(1);
```
Comment (andyross) [inline tests/kernel/tickless/tickless_concept/src/main.c]: FWIW: you could consider k_sleep(0) instead, which is guaranteed to synchronize to the "next" tick boundary and doesn't try to sleep for a full millisecond first.   Not particularly relevant here, but in situations where you want to do a bunch of tick synchronization in a tight loop on systems where the tick rate is more than 1khz it might save some time running the test.

File: tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c [hunk 2]
```diff
@@ -19,29 +19,53 @@ BUILD_ASSERT(NUM_THREAD <= MAX_NUM_THREAD);
 #define BUSY_MS (SLICE_SIZE + 20)
 /* a half timeslice*/
 #define HALF_SLICE_SIZE (SLICE_SIZE >> 1)
+#define HALF_SLICE_SIZE_CYCLES \
+	((u64_t)(HALF_SLICE_SIZE) * sys_clock_hw_cycles_per_sec() / 1000)
 
 K_SEM_DEFINE(sema, 0, NUM_THREAD);
 /*elapsed_slice taken by last thread*/
-static s64_t elapsed_slice;
+static u32_t elapsed_slice;
```
Comment (andyross) [inline tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c]: This looks dangerous.  Time values should almost always be signed, or else the rollover condition will produce incorrect results for time values that are "near" each other (i.e. "just a few cycles ago" can look like a delta of 2^32).   Alternatively: making time unsigned means that you can **never** use a ">"or "<" operator on the resulting value (to mean "later" or "before"), and that's dangerous..

Stated a third way: unsigned times don't have clean definitons for "later" or "before" and you need to know a-priori which time is the one that comes later.  That's indeed the way it works here in your new code (i.e. it's computing a delta and assuming that current k_cycle_get_32() is after the argument), and a quick audit of my own seems to show that there aren't any other legacy uses of that elapsed_since value.  So this is all local to the test and correct.   Still: I strongly recommend never using an unsigned value for a time.

Changing it to a 32 bit word seems fine, I'm just quibbling about the sign.

**Review by andyross — APPROVED** [review]
This looks good to me.  There's a nitpick in there about signedness choice in time values, but it's correctly implemented and local to a test, so not worth a -1.

**Review by tyrantlizard77 — APPROVED** [review]

File: tests/kernel/tickless/tickless_concept/src/main.c (hunk 1 above)
Comment (pizi-nordic) [reply tests/kernel/tickless/tickless_concept/src/main.c]: Good hint. Thank you. Fixed.

File: tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c (hunk 2 above)
Comment (pizi-nordic) [reply tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c]: My goal here is to have full range of u32 as we do not have k_cycle_get_64.

File: tests/kernel/tickless/tickless_concept/src/main.c (hunk 1 above)
Comment (pizi-nordic) [reply tests/kernel/tickless/tickless_concept/src/main.c]: I changed the code, run the test and it failed.
The k_sleep(0) does not synchronize to tick due to:
```
        /* wait of 0 ms is treated as a 'yield' */
        if (duration == 0) {
                k_yield();
                return 0;
        }
```
I kept k_sleep(1) in the code in order to perform synchronization.
