### PR TITLE
Bluetooth: host: Fix peripheral conn param update ignored

### LINKED ISSUE #28870: Peripheral initiated connection parameter update is ignored
**Describe the bug**
If a peripheral initiates a connection parameter update before the first conn param update timer has expired, its requested parameters are ignored (no error code return from `bt_conn_le_param_update()`). If `CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n` nothing will happen when the timer eventually does expire

**To Reproduce**
1. Checkout https://github.com/thomasstenersen/zephyr/commit/9a9e240f76a4910fbdbd510b0bda40234c84be62
2. Build and run the peripheral_hr sample (example `west build -b nrf5284dk_nrf52840 -d build samples/bluetooth/peripheral_hr`)
3. Connect to the peripheral and observe that the first connection parameter update request only comes after >5 seconds.

**Expected behavior**
I would expect `bt_conn_le_param_update()` to either
1. Return an error if it is not ready to handle the request yet, or
2. Execute the connection parameter update request as possible.

**Logs and console output**
nRF Sniffer/Wireshark log: [conn-update-delay.zip](https://github.com/zephyrproject-rtos/zephyr/files/5318380/conn-update-delay.zip)
Sample log output:

```
<snip>
Connected
Called conn update
Called conn update
Called conn update
Called conn update
Called conn update
Called conn update
Called conn update
</snip>
```

### PR DESCRIPTION
**Pull request by joerchan**
Fix application conn param update submitted before the timeout of
CONFIG_BT_CONN_PARAM_UPDATE has expired being ignored when
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n.

Document the behavior of the bt_conn_le_conn_update API when the
local device is the peripheral role.

Fixes: #28870

### CODE REVIEW

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -341,9 +344,9 @@ static void tx_complete_work(struct k_work *work)
 	tx_notify(conn);
 }
 
-static void conn_update_timeout(struct k_work *work)
+static void deferred_work(struct k_work *work)
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:347]: I was wondering why this function was renamed, but I see that it handles much more than just connection parameter update. 

I was wondering if it would make more sense to split this into multiple functions, as it now has been become more difficult finding the function that deals with the automatic parameter update (something I personally have spend more than enough time on finding in the first place when I started working with Zephyr).

**Review by Thalley — APPROVED** [review]
The changes looks alright to me. One concern about the generic naming used.

File: subsys/bluetooth/host/conn.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/conn.c:347]: Renaming because it is a more accurate name for what it is doing.

Also moved some of the code so that it is now contained in a single source file.

I don't see the need for improving it beyond that, splitting it up might increase the RAM usage, which is something I would prefer not do unless absolutely required.

**Review by jhedberg — APPROVED** [review]
