### PR TITLE
Fix drivers: ieee802154: mcxw71 echo_client and echo_server compilation

### LINKED ISSUE #90290: drivers: ieee802154: mcxw71 echo_client and echo_server don't compile
The NXP mcxw71 echo_client and echo_server don't currently compile on latest main [369f15d8c](https://github.com/zephyrproject-rtos/zephyr/commit/369f15d8c914d69d799ff7f8f3c091208f523926).

- No such file or directory 20 | #include "fsl_spc.h"
- undefined reference to `__device_dts_ord_59' / ieee802154 device

Compiled with command:
`west build -p always -b frdm_mcxw71 samples/net/sockets/echo_server -- -DCONF_FILE="prj.conf overlay-ot.conf" `

### PR DESCRIPTION
**Pull request by andrei-menzopol**
## Description

Fix #90290

- soc: nxp: mcxw: update macro in Kconfig.defconfig
- modules: hal_nxp: update mcux-sdk-ng compoments.cmake
 - drivers: ieee802154: fix mcxw ieee802154 driver

## Testing 

- Compiled echo_server/echo_client with: west build -p always -b frdm_mcxw71 samples/net/sockets/echo_client -- -DEXTRA_CONF_FILE=overlay-ot.conf
- Created a thread network with it and joined another thread device
- Checked that the thread communication is working (with a 15.4 thread wireshark capture)
- Was able to see the neighbors and ping

### CODE REVIEW

**Review by George-Stefan — APPROVED** [review]

**Review by decsny — DISMISSED** [review]

**Comment by dleach02** [comment]
Merged HAL and fixed up your PR

**Review by dleach02 — DISMISSED** [review]

**Comment by dleach02** [comment]
closed/reopen to clear compliance meta data issue

File: soc/nxp/mcx/mcxw/Kconfig.defconfig [hunk 1]
```diff
@@ -49,13 +49,13 @@ config HCI_NXP_RX_THREAD
 
 endif # BT
 
-if NET_L2_IEEE802154 || NET_L2_OPENTHREAD
+if IEEE802154
```
Comment (jukkar) [inline soc/nxp/mcx/mcxw/Kconfig.defconfig:52]: The symbols are meant for different purposes
* `CONFIG_NET_L2_IEEE802154` and `CONFIG_NET_L2_OPENTHREAD` are set if IEEE 802.15.4 L2 layer is enabled
* `CONFIG_IEEE80154` is set if IEEE 802.15.4 driver support is enabled. One can have driver support enabled without L2 support or have a custom L2 support in which case the configs in previous line are not enabled

Not sure what is the purpose of this change, but at first glance it does not look it is really needed.

Comment (andrei-menzopol) [reply soc/nxp/mcx/mcxw/Kconfig.defconfig:52]: Thank you.
It was wrong to use the NET_L2 macros to begin with. NXP_RF_IMU enables the communication with the RF core so it should be guarded by a lower level driver define as CONFIG_IEEE80154.

**Review by George-Stefan — APPROVED** [review]

**Review by jukkar — DISMISSED** [review]

File: drivers/ieee802154/ieee802154_mcxw.c [hunk 2]
```diff
@@ -862,7 +862,7 @@ static int mcxw_cca(const struct device *dev)
 
 	k_sem_take(&mcxw_radio->cca_wait, K_FOREVER);
 
-	return (mcxw_radio->tx_status == OT_ERROR_CHANNEL_ACCESS_FAILURE) ? -EBUSY : 0;
+	return mcxw_radio->tx_status ? -EBUSY : 0;
```
Comment (cfriedt) [inline drivers/ieee802154/ieee802154_mcxw.c:865]: just a heads-up this violates a misra rule about branch conditions being bool

**Review by cfriedt — DISMISSED** [review]
looks ok to me as well, just one observation about a misra rule violation. Fix that if you like or if e.g. @dleach02 requires it. 

The CI issues seems to be unrelated.

File: drivers/ieee802154/ieee802154_mcxw.c (hunk 2 above)
Comment (andrei-menzopol) [reply drivers/ieee802154/ieee802154_mcxw.c]: Fixed. Thank you

**Review by George-Stefan — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
