### PR TITLE
drivers: adc: nxp_sar_adc: Add compatibility for SoCs without ADCLKSEL

### LINKED ISSUE #101936: tests: adc: imx93_evk/mimx9352/m33 : build failure
### Describe the bug

- imx93_evk/mimx9352/m33

commit e7d24c80884fc4fda99c378b7b57551196de73e5
Author: Zhaoxiang Jin <Zhaoxiang.Jin_1@nxp.com>
Date:   Fri Dec 26 13:28:16 2025 +0800

    drivers: adc: add clock frequency selection for SAR ADC
    
    This commit enhances the SAR ADC driver by adding
    support for clock frequency selection. The clock
    frequency can now be configured via the devicetree,
    allowing for better optimization of ADC performance
    based on application requirements.
    
    Signed-off-by: Zhaoxiang Jin <Zhaoxiang.Jin_1@nxp.com>

 drivers/adc/adc_nxp_sar_adc.c     | 11 ++++++++---
 dts/bindings/adc/nxp,sar-adc.yaml | 12 ++++++++++++
 2 files changed, 20 insertions(+), 3 deletions(-)

### Regression

- [x] This is a regression.

### Steps to reproduce

west build -b imx93_evk/mimx9352/m33 tests/drivers/adc/adc_api -T drivers.adc.b_u585i_iot02a_adc4

### Relevant log output

```shell
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/adc/adc_nxp_sar_adc.c:468:23: error: 'ADC_MCR_ADCLKSEL_MASK' undeclared (first use in this function); did you mean 'ADC_MCR_ADCLKSE_MASK'?
  468 |                       ADC_MCR_ADCLKSEL_MASK)) | ADC_MCR_OWREN(config->overwrite ? 1U : 0U) |
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       ADC_MCR_ADCLKSE_MASK
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/adc/adc_nxp_sar_adc.c:468:23: note: each undeclared identifier is reported only once for each function it appears in
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/adc/adc_nxp_sar_adc.c:470:23: error: implicit declaration of function 'ADC_MCR_ADCLKSEL'; did you mean 'ADC_MCR_ADCLKSE'? [-Werror=implicit-function-declaration]
  470 |                       ADC_MCR_ADCLKSEL(config->conv_clk_freq_div_factor));
      |                       ^~~~~~~~~~~~~~~~
      |                       ADC_MCR_ADCLKSE
cc1: all warnings being treated as errors
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: ubuntu
- toolchain: zephyr
- version: v4.3.0-3362-g1428bc537a39

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ZhaoxiangJin**
Some NXP SAR ADC variants don't implement the `MCR[ADCLKSEL]` field. Add conditional compilation guards to define compatibility macros that evaluate to 0 when `ADCLKSEL` is not available, allowing the driver to compile across different NXP SoCs.

fix https://github.com/zephyrproject-rtos/zephyr/issues/101936

### CODE REVIEW

File: drivers/adc/adc_nxp_sar_adc.c [hunk 1]
```diff
@@ -31,6 +31,17 @@ LOG_MODULE_REGISTER(nxp_sar_adc, CONFIG_ADC_LOG_LEVEL);
...
+/* Some NXP SAR ADC variants don't implement MCR[ADCLKSEL].
+ * Guard both the mask and the value macro so the driver can compile across SoCs.
+ */
+#if defined(ADC_MCR_ADCLKSEL_MASK) && defined(ADC_MCR_ADCLKSEL)
+#define NXP_SAR_ADC_MCR_ADCLKSEL_MASK ADC_MCR_ADCLKSEL_MASK
+#define NXP_SAR_ADC_MCR_ADCLKSEL(x)   ADC_MCR_ADCLKSEL(x)
+#else
+#define NXP_SAR_ADC_MCR_ADCLKSEL_MASK 0U
+#define NXP_SAR_ADC_MCR_ADCLKSEL(x)   0U
+#endif
```
Comment (butok) [inline drivers/adc/adc_nxp_sar_adc.c:43]: Simpler way:

```
#ifndef ADC_MCR_ADCLKSEL_MASK
#define ADC_MCR_ADCLKSEL_MASK        0
#endif

#ifndef ADC_MCR_ADCLKSEL
#define ADC_MCR_ADCLKSEL(x)          0
#endif
```
no additional code change is needed.

Comment (ZhaoxiangJin) [reply drivers/adc/adc_nxp_sar_adc.c:43]: Thanks for the suggestion, but I’d prefer to keep the driver-local wrapper.
Defining `ADC_MCR_ADCLKSEL_MASK / ADC_MCR_ADCLKSEL()` here changes the meaning of `is this SoC feature available?` from `not present` to `present but zero` for the whole translation unit, which can affect other conditional paths and is harder to reason about. The current `NXP_SAR_ADC_MCR_ADCLKSEL_*` guard avoids polluting global macros while still compiling cleanly across SoCs.

**Review by Holt-Sun — APPROVED** [review]

File: drivers/adc/adc_nxp_sar_adc.c (hunk 1 above)
Comment (JiafeiPan) [inline drivers/adc/adc_nxp_sar_adc.c:43]: In some platform, it doen't define ADC_MCR_ADCLKSEL_MASK, but defines ADC_MCR_ADCLKSE_MASK,  not sure they are same field in the register?
for example:
```
mcux-sdk-ng/devices/i.MX/i.MX93$ git grep ADC_MCR_ADCLKSE
periph/PERI_ADC.h:#define ADC_MCR_ADCLKSE_MASK                     (0x100U)
periph/PERI_ADC.h:#define ADC_MCR_ADCLKSE_SHIFT                    (8U)
periph/PERI_ADC.h:#define ADC_MCR_ADCLKSE(x)                       (((uint32_t)(((uint32_t)(x)) << ADC_MCR_ADCLKSE_SHIFT)) & ADC_MCR_ADCLKSE_MASK)
```

Comment (ZhaoxiangJin) [reply drivers/adc/adc_nxp_sar_adc.c:43]: They are different bits, but they function somewhat similarly. Currently, this driver does not configure ADCLKSE.

**Review by JiafeiPan — APPROVED** [review]

**Review by zejiang0jason — APPROVED** [review]
