### PR TITLE
drivers: clock_control: stm32: enable PWR clock unconditionally

### LINKED ISSUE #37781: nucleo_l496zg lpuart1 driver not working
**Describe the bug**
In Zephyr v2.6.0 when running the hello_world sample printk output is not printed to the console.
printk does print to the console in v2.5.0

I did a git bisect and found commit 888a24f76d2e5fd3bff313f3551af08973940ad6 breaks this functionality.

**To Reproduce**
Steps to reproduce the behaviour:
1. Checkout v2.6.0-branch or main
2. Connect terminal to serial port
3. west build -p -b nucleo_l496zg zephyr/samples/hello_world
4. west flash
5. Observe "Hello World! nucleo_l496zg" is not printed in terminal

**Expected behavior**
"Hello World! nucleo_l496zg" is printed in terminal

**Impact**
annoyance

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain ARM GNU 7.3.1

**Additional context**
@ABOSTM and I discussed this issue briefly on slack

### PR DESCRIPTION
**Pull request by erwango**
Enable PWR clock unconditionally for L4, L5 and WB/L
like it is done on other stm32 series

Fixes #37781

Signed-off-by: Alexandre Bourdiol <alexandre.bourdiol@st.com>

### CODE REVIEW

**Comment by erwango** [comment]
Manual backport after bot failure ( Fixes https://github.com/zephyrproject-rtos/zephyr/issues/38145)

**Review by FRASTM — APPROVED** [review]

File: drivers/clock_control/clock_stm32l4_l5_wb_wl.c [hunk 1]
```diff
@@ -48,6 +48,11 @@ void config_pll_init(LL_UTILS_PLLInitTypeDef *pllinit)
  */
 void config_enable_default_clocks(void)
 {
+#ifdef LL_APB1_GRP1_PERIPH_PWR
+	/* Enable the power interface clock */
+	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);
```
Comment (FRASTM) [inline drivers/clock_control/clock_stm32l4_l5_wb_wl.c:53]: For the stm32U5x5, the PWREN is on the RCC_AHB3ENR register

**Review by ABOSTM — APPROVED** [review]
LGTM
