### PR TITLE
Bluetooth: Host: Use custom settings API for Bluetooth subsystem

### LINKED ISSUE #55475: Bluetooth: settings: Possible Bluetooth settings leftovers
**Describe the bug**
Zephyr Bluetooth settings stores multiple records related to the same bond (e.g. keys, CCC, SC, CF).
In some edge cases, Zephyr Bluetooth settings may contain unused leftovers which would pollute settings area forever without notifying the application (the application may be completely unaware of the problem).
There seem to be no documented way to remove such settings leftovers in application once they appear.

Apart from this, the CCC, SC and CF leftovers may be improperly reused e.g. if the same peer bonds again (the peer could "inherit" the leftover settings data; the settings data are linked to peer relying only on peer's Bluetooth address and used Bluetooth local identity).
The leftover data also occupies space in the RAM arrays (e.g. `sc_cfg` and `struct _bt_gatt_ccc` configurations) after settings are loaded. This could make device unable to store new, valid data for a connected peer (number of records could exceed predefined limits because of the leftovers).

**To Reproduce**

The issue replicates for example if  `bt_unpair` is interrupted by a spurious power down - keys may already be removed, but CCC, SC and CF data could remain.

1. Use a sample that enables Bluetooth settings.
    For example, you can replicate the issue with `samples/bluetooth/peripheral_lbs` sample from  https://github.com/nrfconnect/sdk-nrf running on `nrf52840dk_nrf52840`.
2. Add the `sys_reboot` call during `bt_unpair` (right before `bt_gatt_clear` is called in `unpair` function, so that keys are removed and GATT settings data persists).
3. Add `bt_unpair` call to the button press handler - append the following code to the `button_changed` function to trigger bond erase using button 2 from DK:
```
        if (has_changed & button_state & DK_BTN2_MSK) {
                int err = bt_unpair(BT_ID_DEFAULT, NULL);

                if (err) {
                        printk("Unpair operation failed\n");
                } else {
                        printk("Successfully unpaired\n");
                }
        }
```
4. You can use the following code to print the settings leftover data in the sample:
```
static int log_cb(const char *key, size_t len, settings_read_cb read_cb, void *cb_arg, void *param)
{
        printk("k: %s len: %zu\n", key, len);
        /* Sleep is added to prevent flooding logs. */
        k_msleep(100);

        return 0;
}

static int settings_log(void)
{
         return settings_load_subtree_direct(NULL, log_cb, NULL);
}
```
5. Run the sample, connect and bond with a Bluetooth Central and then trigger `bt_unpair` (pressing Button 2 on the DK).
    See that settings contains leftover data after the reboot.

**Expected behavior**
Application needs a way to make sure that Bluetooth settings data is consistent and contains no leftovers:

1. We could introduce an API to let application trigger the Bluetooth settings cleanup or retrieve information about all of the the leftover records (for example get all of the related settings keys).
   Application could manually delete the leftovers.
2. The leftovers may be automatically removed while settings are loaded (for example settings `set` callback could remember the leftovers and we may remove it in the settings `commit` callback).
3. We could introduce a mechanism ensuring that set of related settings records is always modified together.
   For example, we may store an additional settings record informing that the unpair operation for given bond is started and delete it as soon as operation is complete.
   If the operation is interrupted by e.g. a power down, it could be properly finalized on subsequent boot (e.g. when settings are loaded).

I would suggest to follow the 1st proposed approach.
If the leftovers are caused only by some edge cases that are not likely to happen, an application API to trigger settings data cleanup may be a reasonable approach I think (if an application does not use it, there would be no additional memory overhead too).

**Impact**
Leftovers in the settings may lead to issues where there is no space to store new data (both in the settings partition and in the RAM arrays).
"Inheriting" settings data from previously bonded peers may lead to various unexpected behaviors (e.g. receiving spurious indications/notifications).

**Environment:**
Used main (`f68bcdf5b3ea479268593459aa4770059058780e`) branch from https://github.com/nrfconnect/sdk-nrf repository.

### PR DESCRIPTION
**Pull request by theob-pro**
The first commit wrap the `settings_set_one` and `settings_delete` functions in `bt_settings_store_one` and `bt_settings_delete`. By doing that the Bluetooth settings can be managed in a single place.

This commit also introduce a new API to manage Bluetooth storage with `bt_settings_store_*` and `bt_settings_delete_*` functions. Each Bluetooth settings key have their own store and delete functions. Doing that so custom behavior for key can be done if necessary.

This change is motivated by a need of keeping track of different persistently stored settings inside the Bluetooth subsystem. This will allow a better management of the settings that the Bluetooth subsystem is responsible of.

The second commit update some tests to use this new API.

This is a first step to fix https://github.com/zephyrproject-rtos/zephyr/issues/55475

### CODE REVIEW

File: subsys/bluetooth/host/settings.c [hunk 1]
```diff
@@ -323,3 +297,179 @@ int bt_settings_init(void)
...
+		}
+
+		bt_settings_encode_key(key_str, sizeof(key_str), key, addr, (id ? id_str : NULL));
+	} else {
+		if (strlen(key) > BT_SETTINGS_KEY_MAX - 4) {
+			return -EINVAL;
+		}
+
+		strcpy(&key_str[0], "bt/");
+		strcpy(&key_str[3], key);
```
Comment (jhedberg) [inline subsys/bluetooth/host/settings.c:319]: There's a risk that static analysers like Coverity might trip over the use of strcpy instead of its safe strncpy variant. However, using just `snprintk()` is likely the simplest here:
```c
snprintk(key_str, sizeof(key_str), "bt/%s", key);
```

**Review by jhedberg — CHANGES_REQUESTED** [review]

**Review by jori-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by theob-pro** [comment]
Rebased on main because of documentation build failure.

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]
