### PR TITLE
lib/p4wq: Fix race with completed work items

### LINKED ISSUE #32052: p4wq has a race with work item re-use
The p4wq code, to handle the case where a work item was re-submitted, needs to inspect the thread field of the work item after the user callback has returned.  But this will race with the case where the user code needs to (in some other context, on some other CPU) re-use that work item (for example by freeing it into the heap, or filling it out again for resubmission).

In the case where the item was not resubmitted, the p4wq code must never touch the memory of a work item after its callback has returned.

(In practice, we just need one bit for "was resubmitted", which we can track per-thread somewhere I guess.  Needs a little thought, but shouldn't be difficult.)

### PR DESCRIPTION
**Pull request by andyross**
Work items can be legally resubmitted from within their own handler.
Currently the p4wq detects this case by checking their thread field to
see if it's been set to NULL.  But that's a race, because if the item
was NOT resubmitted then it no longer belongs to the queue and may
have been freed or reused or otherwise clobbered legally by user code.

Instead, steal a single bit in the thread struct for this purpose.
This patch adds a K_CALLBACK_STATE bit in user_options and documents
it in such a way (as being intended for "callback manager" utilities)
that it can't be used recursively or otherwise collide.

Fixes #32052

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Comment by andyross** [comment]
Definitely not the cleanest API design for that bit, but it's tiny and zero-cost and stays out of the way.

**Review by dcpleung — APPROVED** [review]

File: lib/os/p4wq.c [hunk 1]
```diff
@@ -70,6 +84,7 @@ static FUNC_NORETURN void p4wq_loop(void *p0, void *p1, void *p2)
 			w->thread = _current;
 			sys_dlist_append(&queue->active, &w->dlnode);
 			set_prio(_current, w);
+			thread_set_requeued(_current, false);
```
Comment (lyakh) [inline lib/os/p4wq.c:87]: nitpicking: I'm not a huge fan of functions, whose complete body is checking a condition like
```
void f(bool x)
{
	if (x)
		do_one_thing();
	else
		do_another_thing();
}
```
if they're ever only called with `x` being constant, i.e. as `f(true)` or `f(false)`. In such cases I find having two functions `f_true()` and `f_false()`. In this case we could have `thread_set_requeued()` and `thread_clear_requeued()` maybe as 2 macros.

**Review by lyakh — CHANGES_REQUESTED** [review]
Do you think allocating a copy of the work struct internally would be too slow? This would have an added benefit of allowing the user to use a struct on stack. I've implemented it locally, I can send a PR if you like.

File: lib/os/p4wq.c (hunk 1 above)
Comment (andyross) [reply lib/os/p4wq.c:87]: Ah, but you can't put it on the stack[1], because the stack is incoherent memory and the work item by definition needs to be shared between threads.  And making an internal copy would work, but would require a heap or mem_slab or some other allocator, which Zephyr doesn't assume to be present.  The idiom where the user manages memory for things like this is pervasive in our utilities.

I can change the API though, sure.  Honestly I like the single call for clarity and trust the compiler to eliminate the dead branch via inlining, but that's a taste thing.

[1] Not naively, anyway.  But you could do it in SOF by making sure it lives entirely within its own 64-byte cache line, munging the pointer to reference the uncached mapping, and then passing that to the queue.  But that would be CAVS-specific code, obviously.

**Comment by andyross** [comment]
Adjusted the flag API per request.

**Review by lyakh — APPROVED** [review]

File: lib/os/p4wq.c [hunk 2]
```diff
@@ -78,7 +94,7 @@ static FUNC_NORETURN void p4wq_loop(void *p0, void *p1, void *p2)
 			/* Remove from the active list only if it
 			 * wasn't resubmitted already
 			 */
-			if (w->thread == _current) {
+			if (!thread_was_requeued(_current)) {
 				sys_dlist_remove(&w->dlnode);
 				w->thread = NULL;
```
Comment (lyakh) [inline lib/os/p4wq.c:99]: @andyross but this is still a problem, isn't it?
