### PR TITLE
tests: portability: cmsis_rtos_v1: Increase clock tolerance

### LINKED ISSUE #26280: test_kernel_systicks from tests/portability/cmsis_rtos_v1 fails on nrf platforms
**Describe the bug**
The test case _test_kernel_systicks_ from tests/portability/cmsis_rtos_v1 test suite fails consistently at nrf platforms: (nrf52dk_nrf52832, nrf52840dk_nrf52840 and nrf9160dk_nrf9160)

**To Reproduce**
1. run in zephyr dir ./scripts/sanitycheck --testcase-root ./tests/portability/cmsis_rtos_v1 --device-testing -p nrf52dk_nrf52832 -v -v --device-serial /dev/ttyACM0
2. See error

**Expected behavior**
The test case test_kernel_systicks passes on nrf platforms

**Impact**
not clear

**Screenshots or console output**
```
DEBUG   - DEVICE: Assertion failed at CMAKE_SOURCE_DIR/src/kernel_apis.c:58: test_kernel_systick: (diff <= max && diff >= min is false)
DEBUG   - DEVICE: start 991 stop 34848 (diff 1033233) wait 1000000
DEBUG   - DEVICE: 
DEBUG   - DEVICE: FAIL - test_kernel_systick
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: starting test - test_thread_apis
DEBUG   - DEVICE: PASS - test_thread_apis
DEBUG   - DEVICE: ===================================================================
[...]
DEBUG   - DEVICE: Test suite test_cmsis_apis failed.
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
INFO    - 1/1 nrf52dk_nrf52832          tests/portability/cmsis_rtos_v1/portability.cmsis_rtos_v1 FAILED Failed (device 15.061s)
ERROR   - see: /home/maciej/zephyrproject2/zephyr/sanity-out/nrf52dk_nrf52832/tests/portability/cmsis_rtos_v1/portability.cmsis_rtos_v1/handler.log

INFO    - 0 of 1 tests passed (0.00%), 1 failed, 0 skipped with 0 warnings in 20.19 seconds
INFO    - In total 1 test cases were executed on 1 out of total 255 platforms (0.39%)
INFO    - 1 tests executed on platforms, 0 tests were only built.

Hardware distribution summary:

| Board            | ID   |   Counter |
|------------------|------|-----------|
| nrf52dk_nrf52832 |      |         1 |
```

**Environment:**
 - OS:  Linux, 
 - Toolchain Zephyr SDK
 - Commit SHA b5764f9902

**Additional context**
The test seems to pass on other platforms (https://testing.zephyrproject.org/daily_tests/v2.3.0-rc2/report/index.html). The value for `diff` supposed to be between `min 990000` and `max 1010000`
 From running it 3 times per platform I've got diff eq. to:
nrf52dk_nrf52832: 1032470, 1033355 and 1033843
nrf52840dk_nrf52840: 981140, 980743 and 981384 
nrf9160dk_nrf9160: 1127929, 1121948 and 1121459

### PR DESCRIPTION
**Pull request by nordic-krch**
Increased accepted difference between system clock and
k_busy_wait clock. Some platforms (e.g. Nordic SoC) are using
different clocks for system clock (low frequency) and k_busy_wait
(high frequency). If those clocks are driven from low accuracy
source like RC oscillator then difference may be significant.

Fixes #26280. 
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by nordic-krch** [comment]
Note that i have seen same test failing on other qemu platform. Not sure how clocks are handled on `qemu_arc_hs` platform and if fix will help there.

``` 
Sanitycheck / qemu_arc_hs:tests/portability/cmsis_rtos_v1/portability.cmsis_rtos_v1 / tests/portability/cmsis_rtos_v1/portability.cmsis_rtos_v1
 failure: Failed

*** Booting Zephyr OS build zephyr-v2.3.0-522-g78c4937ba99a  ***
Running test suite test_cmsis_apis
===================================================================
START - test_kernel_start
 PASS - test_kernel_start
===================================================================
START - test_kernel_systick

    Assertion failed at WEST_TOPDIR/zephyr/tests/portability/cmsis_rtos_v1/src/kernel_apis.c:58: test_kernel_systick: (diff <= max && diff >= min is false)
start 72218 stop 1083124 (diff 1010906) wait 1000000

 FAIL - test_kernel_systick
```

File: tests/portability/cmsis_rtos_v1/src/kernel_apis.c [hunk 1]
```diff
@@ -48,12 +48,12 @@ void test_kernel_systick(void)
 	diff = (uint32_t)k_cyc_to_ns_floor64(stop_time -
 					 start_time) / NSEC_PER_USEC;
 
-	/* Check that it's within 1%.  On some Zephyr platforms
+	/* Check that it's within 10%.  On some Zephyr platforms
```
Comment (pabigot) [inline tests/portability/cmsis_rtos_v1/src/kernel_apis.c:51]: I don't think increasing tolerance globally is the best approach, if only Nordic's timer has this problem.  Instead a generic tolerance should be defaulted, with an override on platforms that can't meet it for good reasons.

```
#if CONFIG_NRF_RTC_TIMER
#define TOLERANCE_PPC 10
#else
#define TOLERANCE_PPC 1
#endif

...
max = WAIT_TIME_US + (TOLERANCE_PPC * WAIT_TIME_US / 100);
```

**Review by pabigot — CHANGES_REQUESTED** [review]

File: tests/portability/cmsis_rtos_v1/src/kernel_apis.c (hunk 1 above)
Comment (nordic-krch) [reply tests/portability/cmsis_rtos_v1/src/kernel_apis.c]: done

File: tests/portability/cmsis_rtos_v1/src/kernel_apis.c [hunk 2]
```diff
@@ -10,6 +10,12 @@
 
 #define WAIT_TIME_US 1000000
 
+#if CONFIG_NRF_RTC_TIMER
```
Comment (pabigot) [inline tests/portability/cmsis_rtos_v1/src/kernel_apis.c:13]: Some documentation here would be good.  Moving the comment block from the use of `TOLERANCE_PPC` up to here should cover it.

**Review by pabigot — CHANGES_REQUESTED** [review]

File: tests/portability/cmsis_rtos_v1/src/kernel_apis.c [hunk 3]
```diff
@@ -48,12 +58,12 @@ void test_kernel_systick(void)
 	diff = (uint32_t)k_cyc_to_ns_floor64(stop_time -
 					 start_time) / NSEC_PER_USEC;
 
-	/* Check that it's within 1%.  On some Zephyr platforms
+	/* Check that it's within accepted tolerance. On some Zephyr platforms
 	 * (e.g. nRF5x) the busy wait loop and the system timer are
```
Comment (pabigot) [inline tests/portability/cmsis_rtos_v1/src/kernel_apis.c:62]: The split documentation is not what I had in mind.

Everything in this comment should be up at the point where `TOLERANCE_PPC` is defined: why we need tolerance at all (historically, because Nordic clocks had slew that became visible when clock rates exceeded 100 Hz 33c64c2578d13bd5f63a777077f85a44f966d86e), and why Nordic needs an insanely lax tolerance to pass reliably.

Once `TOLERANCE_PPC` is described it's obvious that we're checking for tolerance and there's no need for a comment here repeating that information.

Comment (nordic-krch) [reply tests/portability/cmsis_rtos_v1/src/kernel_apis.c]: pls check again

**Review by pabigot — APPROVED** [review]
