### PR TITLE
driver: uart: esp32: get port number from reg address

### LINKED ISSUE #69973: tests/drivers/uart/uart_async_api fails to compile for esp32c3_luatos_core/esp32c3/usb
**Describe the bug**
Test fails to compile. Seen on PR: https://github.com/zephyrproject-rtos/zephyr/pull/68630/checks?check_run_id=22383148242
Reproduced locally on main as well.

**To Reproduce**
1. `west build -p -b esp32c3_luatos_core/esp32c3/usb tests/drivers/uart/uart_async_api/`

**Expected behavior**
Test shall build or be filtered out for that board.

**Impact**
CI failures

**Environment (please complete the following information):**
 - 9412ad306f64e3dcd9f37eb6c3cb3c17dbcebc67

### PR DESCRIPTION
**Pull request by sylvioalves**
ESP32 uart driver requires uart port number to its low level calls.

In case uart0 is disabled and uart1 is enabled, driver will set default port num to 0 when it should be 1. This fixes this scenario by retrieving uart pot number based on periphral address.

Fixes #69973

### CODE REVIEW

**Review by marekmatej — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

File: drivers/serial/uart_esp32.c [hunk 1]
```diff
@@ -971,8 +970,7 @@ static const DRAM_ATTR struct uart_driver_api uart_esp32_api = {
 #define ESP_UART_DMA_INIT(n)                                                                       \
 	.dma_dev = ESP32_DT_INST_DMA_CTLR(n, tx),                                                  \
 	.tx_dma_channel = ESP32_DT_INST_DMA_CELL(n, tx, channel),                                  \
-	.rx_dma_channel = ESP32_DT_INST_DMA_CELL(n, rx, channel),                                  \
-	.uart_id = (DEVICE_DT_GET(DT_NODELABEL(uart0)) != DEVICE_DT_INST_GET(n)),
+	.rx_dma_channel = ESP32_DT_INST_DMA_CELL(n, rx, channel)
```
Comment (fabiobaltieri) [inline drivers/serial/uart_esp32.c:973]: nit: it's usually a good idea to leave the trailing `,` on the last element so you don't get this odd diffs where nothing really changed
