### PR TITLE
Bluetooth: controller: enable missing RSSI while periodic adv sync

### LINKED ISSUE #40215: RSSI in periodic adv. callbacks always -127 (sync_recv and cte_report_cb)
**Describe the bug**
The RSSI in `bt_le_per_adv_sync_recv_info` and  `bt_df_per_adv_sync_iq_samples_report` is always -127.

**To Reproduce**
1. Build direction_finding_connectionless_tx sample as an advertiser.
2. Build direction_finding_connectionless_rx sample as a scanned.
3. Run both.
4. Check RSSI printed on receiver side.

**Expected behavior**
A valid RSSI value that is not constant.

**Impact**
Moderate, only affects periodic advertising.

**Logs and console output**
*** Booting Zephyr OS build v2.7.99-1230-gf94144ebe712  ***
```
Starting Connectionless Locator Demo
Bluetooth initialization...success
Scan callbacks register...success.
Periodic Advertising callbacks register...success.
Start scanning...success
Waiting for periodic advertising...success. Found periodic advertising.
Creating Periodic Advertising Sync...success.
Waiting for periodic sync...
PER_ADV_SYNC[0]: [DEVICE]: 07:EE:DD:D6:CD:0E (random) synced, Interval 0x00f0 (300 ms), PHY LE 1M
PER_ADV_SYNC[0]: [DEVICE]: 07:EE:DD:D6:CD:0E (random), tx_power 127, RSSI -127, CTE AOA, data length 0, data:
success. Periodic sync established.
Enable receiving of CTE...
success. CTE receive enabled.
Scan disable...Success.
Waiting for periodic sync lost...
PER_ADV_SYNC[0]: [DEVICE]: 07:EE:DD:D6:CD:0E (random), tx_power 127, RSSI -127, CTE AOA, data length 0, data:
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -1270
PER_ADV_SYNC[0]: [DEVICE]: 07:EE:DD:D6:CD:0E (random), tx_power 127, RSSI -127, CTE AOA, data length 0, data:
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -1270
PER_ADV_SYNC[0]: [DEVICE]: 07:EE:DD:D6:CD:0E (random), tx_power 127, RSSI -127, CTE AOA, data length 0, data:
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -1270
PER_ADV_SYNC[0]: [DEVICE]: 07:EE:DD:D6:CD:0E (random), tx_power 127, RSSI -127, CTE AOA, data length 0, data:
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -1270
PER_ADV_SYNC[0]: [DEVICE]: 07:EE:DD:D6:CD:0E (random), tx_power 127, RSSI -127, CTE AOA, data length 0, data:
CTE[0]: samples count 45, cte type AOA, slot durations: 2 [us], packet status CRC OK, RSSI -1270
...
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Windows
 - Toolchain (e.g Zephyr SDK, ...): Zephyr
 - Commit SHA or Version used: a08e6e1d9ad22920b7a08a366b3d66eaef7440f1

### PR DESCRIPTION
**Pull request by ppryga-nordic**
The RSSI measurement was not enabled while receiving periodic advertising.
The function responsible for enable the feature in radio was called, but it was done too early.
It was overwritten by `radio_switch_XXX` function that assigns a value to `RADIO->SHORTS` register.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/40215

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c [hunk 1]
```diff
@@ -295,6 +295,11 @@ static int create_prepare_cb(struct lll_prepare_param *p)
 		radio_switch_complete_and_disable();
 	}
 
+	/* RSSI enable must be called after radio_switch_XXX function because it clears
+	 * RADIO->SHORTS register, thus disables all other shortcuts.
+	 */
+	radio_rssi_measure();
+
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:302]: Is this always true? If so, would it make sense to move `radio_rssi_measure` to the `radio_switch_*` functions?

Comment (ppryga) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:302]: Well I would not put it into `radio_switch_*` to do not violate single responsibility principle. Besides that it isn't always enabled e.g.
https://github.com/zephyrproject-rtos/zephyr/blob/4f2762d7dabe076252cb3cfa31c1f9a1ab1322d3/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv.c#L1116-L1119

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:302]: That makes sense, but it could also be argued that if you do X, then you shall always do Y, then perhaps that should be a single function Z, e.g.

```
static void foo(void)
{
    /* Do foo */
}

static void barvoid)
{
    /* Do bar */
}

static void foobar(void)
{
    /* foo shall always be called before bar, and bar shall always be called after foo */
    foo();
    bar();
}
```

Comment (ppryga) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:302]: Yes, that is of course true. I read your suggestion a bit too strictly as move `radio_rssi_measure` into `radio_switch_*` but without change of name of latter one.

I think that suggested change should be considered as an enhancement to whole LLL and more than `radio_rssi_measure` could be moved into some kind of `radio_configure_rx` or `radio_configure_tx`.

**Review by cvinayak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
