### PR TITLE
video: ov5640: fix out of bounds control initialization by setting the control array first.

### LINKED ISSUE #90508: [Coverity CID: 520281] Out-of-bounds access in drivers/video/ov5640.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/265cfb45a818f39cf03c3527b5d1b21027d3cac1/drivers/video/ov5640.c

Category: Memory - corruptions
Function: `ov5640_init_controls`
Component: Drivers
CID: [520281](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=520281)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/265cfb45a818f39cf03c3527b5d1b21027d3cac1/drivers/video/ov5640.c#L1258

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=520281

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_OVERRUN). ([CWE-119](http://cwe.mitre.org/data/definitions/119.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by uLipe**
fixes: #90508

### CODE REVIEW

File: drivers/video/ov5640.c
Comment (josuah) [inline drivers/video/ov5640.c:159]: The alternative would have been to name the struct:

```suggestion
	struct {
		struct video_ctrl auto;
		struct video_ctrl manual;
	} gain;
```

Then `gain` effectively holds two `struct video_ctrl`, but then it needs a `(struct video_ctrl *)` cast.

**Review by josuah — APPROVED** [review]
This "address past struct" is how V4L2 builds Linux API and how Zephyr Video APIs are built, considering a struct of only one type as an array.

If you frown upon this, a proposed alternative is proposed, but current workaround LGTM.

Thank you!

**Comment by uLipe** [comment]
Thank you @josuah , I just sent because my local Zephyr that I use in a private project was failling, happy this is helpful

File: drivers/video/ov5640.c [hunk 1]
```diff
@@ -1182,7 +1183,7 @@ static int ov5640_init_controls(const struct device *dev)
 		return ret;
 	}
 
-	video_auto_cluster_ctrl(&ctrls->auto_gain, 2, true);
+	video_auto_cluster_ctrl(auto_ctrls, 2, true);
```
Comment (ngphibang) [inline drivers/video/ov5640.c:1186]: Sorry, could you clarify what is the issue on your side so that this fix is needed ?

Also, I can't see the differences between the code before and after the fix. They seems exactly the same except an extra step of using an intermediate pointer for `&ctrls->auto_gain`.

File: drivers/video/ov5640.c
Comment (ngphibang) [reply drivers/video/ov5640.c:159]: The anoymous struct is just to group the two ctrl struct together and has no other effect. It is equivalent to the array of two items. At line 1185, a pointer to `struct video_ctrl auto_gain` is passed into the function which is already a correct type (the address of the 1st element is equivalent to the address of the array). So, I don't understand what the issue is.

Comment (josuah) [reply drivers/video/ov5640.c:159]: I think it is a matter of getting the compiler/static analysis tools happy. https://github.com/zephyrproject-rtos/zephyr/issues/90508

```c
video_auto_cluster_ctrl(&ctrls->auto_gain, 2, true);
```

The pointer `&ctrls->auto_gain` is passed, but `video_auto_cluster_ctrl()` also accesses `&ctrls->gain` after it. Which is on purpose and how the API is designed, but Coverity complains.

At least that is how I understood it.

File: drivers/video/ov5640.c (hunk 1 above)
Comment (josuah) [reply drivers/video/ov5640.c:1186]: Probably just to fool Coverity.

Comment (ngphibang) [reply drivers/video/ov5640.c:1186]: If this really made Coverity silent so that's fine. But did you run Coverity or have some check to see if this actually fixes the Coverity issue ?

I think Coverity complains because it is afraid that we passed a single pointer but used it as an array in the function (but actually it's not a problem because we are sure that it's an array of two items). IMHO, we don't need to fix.

**Review by nashif — APPROVED** [review]
