### PR TITLE
arch: arm: cortex_m: fault: Improve handling of fault escalation on armv6-m

### LINKED ISSUE #57412: arch: arm: aarch32: cortex_m: fault: ARMv6-M illegal instruction fetch triggers lockup before any fault debug output
**Describe the bug**
When attempting to fetch an instruction from an address on an Cortex-M CPU in an MPU region with the XN attribute, a lockup is triggered before the HardFault handler can output any debug information.

As an example, running the MPU test in the samples directory outputs this when attempting an invalid read:

```
<err> os: ***** HARD FAULT *****
<err> os: r0/a1:  0x0800a54c  r1/a2:  0x00000008  r2/a3:  0x08003
<err> os: r3/a4:  0x24000000 r12/ip:  0x00000040 r14/lr:  0x0800d
<err> os:  xpsr:  0x01000000
<err> os: Faulting instruction address (r15/pc): 0x08000486
<err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
<err> os: Current thread: 0x200006a8 (shell_uart)
<err> os: Halting system
``` 

A similar output happens on an invalid write. When attempting an invalid instruction fetch however, the processor locks up before any output occurs.

This bug occurs as the hard fault handler `hard_fault` in `zephyr/arch/arm/core/aarch32/cortex_m/fault.c` employs a workaround implemented in `z_arm_is_synchronous_svc` to determine if the HardFault originated from a SVC instruction. To do so, `z_arm_is_synchronous_svc:710` (GitHub link to line [here](https://github.com/zephyrproject-rtos/zephyr/blob/12ed08a2fb02515b2469f3e7d0f91ae4b03ea83e/arch/arm/core/aarch32/cortex_m/fault.c#L710)) dereferences the ESF PC:

```c
...

#if defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE) && !defined(CONFIG_ARMV8_M_BASELINE)
	/* Note: ARMv6-M does not support CCR.BFHFNMIGN so this accesstriggered
	 * could generate a fault if the pc was invalid.
	 */
	uint16_t fault_insn = *(ret_addr - 1);
#else

...
```
The synchronous SVC detection change was introduced in #18712, and a fix to the bug described in this issue for Cortex-M CPUs that have distinct HardFaults and BusFaults (ARMv7-M and ARMv8-M) was introduced in #48487, along with the above comment indicating this same bug.

**To Reproduce**
To reproduce this behavior, follow the following steps (as outlined in the [MPU test documentation](https://docs.zephyrproject.org/latest/samples/arch/mpu/mpu_test/README.html) after #57104 was merged):

- Connect a ARMv6-M development board over USB (I used the Nucleo G071RB for my tests)
- Start the MPU test under gdb via `west debug`
- Execute `mpu run` over UART (i.e. via `minicom`)
- Interrupt gdb with Ctrl-C
- Display the program counter by using `l` in gdb

The program counter should be listed as `0xfffffffe`, indicating a lockup. Note in particular that there is no output over the console.

**Expected behavior**
The expected behavior, given that read/write MPU failures trigger HardFaults, is that an invalid instruction fetch should trigger a HardFault as well.

**Impact**
This bug could significantly confuse Zephyr users who aren't aware that MPU invalid instruction fetches trigger lockups, as there is no debug output to work from. Moreover, this behavior for ARMv6-M does not line up with that of any other Cortex-M architecture, potentially leading to additional confusion. I only discovered this after a few days and some lucky discoveries in the Zephyr source and the ARMv6-M Architecture Reference Manual, so this bug could cause timeline delays in applicatoins leveraging ARMv6-M MPU support in Zephyr.  

**Logs and console output**
The full outputs of the MPU test as run on my development laptop with a Nucleo G071RB are here:

```
uart:~$ mpu read
<err> os: ***** HARD FAULT *****
<err> os: r0/a1:  0x0800a54c  r1/a2:  0x00000008  r2/a3:  0x08003
<err> os: r3/a4:  0x24000000 r12/ip:  0x00000040 r14/lr:  0x0800d
<err> os:  xpsr:  0x01000000
<err> os: Faulting instruction address (r15/pc): 0x08000486
<err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
<err> os: Current thread: 0x200006a8 (shell_uart)
<err> os: Halting system
```

```
mpu write
<err> os: ***** HARD FAULT *****
<err> os: r0/a1:  0x00000000  r1/a2:  0x0000000e  r2/a3:  0x0000e
<err> os: r3/a4:  0x0badc0de r12/ip:  0x00000000 r14/lr:  0x08009
<err> os:  xpsr:  0x61000000
<err> os: Faulting instruction address (r15/pc): 0x0800046a
<err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
<err> os: Current thread: 0x200006a8 (shell_uart)
<err> os: Halting system
```

```
uart:~$ mpu run
<no output>
```

**Environment**
The following environment was used for the above tests:
 - OS: Ubuntu 22.04
 - Zephyr SDK
 - Zephyr commit `c2ec3d49cd2f952e0ead3dc7415d6cc9845a0db8`

**Proposed solution**
As supported in the above comment, there is no way I know of to temporarially disable HardFaults on ARMv6-M CPUs.

One method could be to have the HardFault handler, for ARMv6-M CPUs only, read out the current MPU regions to a priori determine if dereferencing the ESF PC would result in a fault. This would likely add significant delay to the handler, and is a touch hacky, but since HardFaults are treated as generally unrecoverable in ARMv6-M, it could be a slightly better option.

Given I'm relatively new to Zephyr though, I'd love to hear other developers' thoughts on what the best option could be.

(Thank you so much!)

### PR DESCRIPTION
**Pull request by ithinuel**
The current implementation causes a lockup of the core when the exception originates from an invalid/unreachable pc. This fix first verifies on armv6-m and armv8-m.base that pc was in an expected runnable region, namely:

- .text
- .ramfunc
- .itcm

Fixes: #57412

### CODE REVIEW

File: arch/arm/core/aarch32/cortex_m/fault.c [hunk 1]
```diff
@@ -729,6 +730,39 @@ static inline bool z_arm_is_synchronous_svc(z_arch_esf_t *esf)
 	return false;
 }
 
+#if defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE)
+static inline bool z_arm_is_pc_valid(uintptr_t pc)
+{
+	/* Is it in valid text region */
+	extern uint32_t __text_region_start;
+	extern uint32_t __text_region_end;
```
Comment (carlocaione) [inline arch/arm/core/aarch32/cortex_m/fault.c:738]: why not simply including `include/zephyr/linker/linker-defs.h`?

**Review by carlocaione — CHANGES_REQUESTED** [review]

File: arch/arm/core/aarch32/cortex_m/fault.c [hunk 2]
```diff
@@ -729,6 +730,39 @@ static inline bool z_arm_is_synchronous_svc(z_arch_esf_t *esf)
 	return false;
 }
 
+#if defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE)
+static inline bool z_arm_is_pc_valid(uintptr_t pc)
```
Comment (carlescufi) [inline arch/arm/core/aarch32/cortex_m/fault.c:734]: Don't we already have something like already @nordic-krch?

**Review by carlescufi — DISMISSED** [review]

File: arch/arm/core/aarch32/cortex_m/fault.c (hunk 1 above)
Comment (ithinuel) [reply arch/arm/core/aarch32/cortex_m/fault.c:738]: Oh I didn't know about it! Thank you!
I'm traveling this week so it may take a bit of time for the update to come but I'll do that asap!

File: arch/arm/core/aarch32/cortex_m/fault.c (hunk 2 above)
Comment (nordic-krch) [reply arch/arm/core/aarch32/cortex_m/fault.c:734]: No, there was similar function to determine if address is in .rodata (for detecting if string is read only).

Comment (carlescufi) [reply arch/arm/core/aarch32/cortex_m/fault.c:734]: I wonder if it would make sense to make this new `z_arm_is_pc_valid()` a generic one @andyross @dcpleung?

**Comment by microbuilder** [comment]
Looks good to me, other than the requested change from Carlo. Thanks for putting this together.

File: arch/arm/core/aarch32/cortex_m/fault.c (hunk 1 above)
Comment (ithinuel) [reply arch/arm/core/aarch32/cortex_m/fault.c]: The update should resolve this thread.

**Review by carlocaione — APPROVED** [review]
LGTM but we should verify whether we want to have this in a general helper or not.

**Comment by microbuilder** [comment]
> 

@carlocaione Are you OK with merging this one as a first step, and sorting out a multi-arch or at least generic Arm version separately?

@ithinuel Want to make a new PR with this as a generic helper, not just Cortex M?

**Review by microbuilder — APPROVED** [review]

**Comment by carlocaione** [comment]
> > 
> 
> @carlocaione Are you OK with merging this one as a first step, and sorting out a multi-arch or at least generic Arm version separately?
> 
> @ithinuel Want to make a new PR with this as a generic helper, not just Cortex M?

totally fine to me

**Review by carlescufi — APPROVED** [review]
