### PR TITLE
tests: benchmarks: use high-res counter for MEC1501 SoC

### LINKED ISSUE #23414: tests/benchmarks/timing_info  failed on mec15xxevb_assy6853 board.
**Describe the bug**
Running tests/benchmarks/timing_info on mec15xxevb_assy6853 board,  the test result is incorrect, for example, the "Clock Frequency is 0 MHz".

**To Reproduce**
1. sanitycheck --hardware-map ~/mec1.yml --device-testing -T  tests/benchmarks/timing_info
2. See error

**Screenshots or console output**
*** Booting Zephyr OS build zephyr-v2.2.0-219-g86bfc489f4a7  ***
starting test - Time Measurement

**Timing Results: Clock Frequency: 0 MHz**
**Context switch                               :   0 cycles ,     0 ns**
Interrupt latency                            :   0 cycles ,     0 ns
Tick overhead                                :   0 cycles ,     0 ns
Thread Creation                              :   1 cycles , 30517 ns
Thread cancel                                :   0 cycles ,     0 ns
Thread abort                                 :   0 cycles ,     0 ns
Thread Suspend                               :   1 cycles , 30517 ns
Thread Resume                                :   0 cycles ,     0 ns
Thread Yield                                 :   0 cycles ,     0 ns
Thread Sleep                                 :   1 cycles , 30517 ns
Heap Malloc                                  :   0 cycles ,     0 ns
Heap Free                                    :   0 cycles ,     0 ns
Semaphore Take with context switch           :   0 cycles ,     0 ns
Semaphore Give with context switch           :   1 cycles , 30517 ns
Semaphore Take without context switch        :   0 cycles ,     0 ns
Semaphore Give without context switch        :   1 cycles , 30517 ns
Mutex lock                                   :   0 cycles ,     0 ns
Mutex unlock                                 :   0 cycles ,     0 ns
Message Queue Put with context switch        :   1 cycles , 30517 ns
Message Queue Put without context switch     :   0 cycles ,     0 ns
Message Queue get with context switch        :   1 cycles , 30517 ns
Message Queue get without context switch     :   0 cycles ,     0 ns
MailBox synchronous put                      :   0 cycles ,     0 ns
MailBox synchronous get                      :   1 cycles , 30517 ns
MailBox asynchronous put                     :   0 cycles ,     0 ns

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.1
 - Commit ID: 86bfc489f

### PR DESCRIPTION
**Pull request by dcpleung**
The timer counter for ticks on MEC1501 SoC is based on the RTOS
timer which runs at 32kHz. This is too slow for timing benchmarks
as most cases can be finished within one or two ticks. Since
the SoC has higher frequency timers running at 48MHz, add
the necessary bits to use these for timing benchmarks.

Fix #23414

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

File: drivers/timer/mchp_xec_rtos_timer.c [hunk 1]
```diff
@@ -217,6 +217,11 @@ static void xec_rtos_timer_isr(void *arg)
 {
 	ARG_UNUSED(arg);
 
+#ifdef CONFIG_EXECUTION_BENCHMARKING
+	extern void read_timer_start_of_tick_handler(void);
```
Comment (andrewboie) [inline drivers/timer/mchp_xec_rtos_timer.c]: I think this ought to be exposed in a header, perhaps under include/debug/ and namespaced with z_. I guess this PR didn't introduce this though.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by scottwcpg — APPROVED** [review]

File: drivers/timer/mchp_xec_rtos_timer.c (hunk 1 above)
Comment (dcpleung) [reply drivers/timer/mchp_xec_rtos_timer.c]: All the  `read_timer_{start,end}_of_*` in `arch/common/timing_info_bench.c` are not exposed.

**Review by franciscomunoz — APPROVED** [review]

**Comment by LeiW000** [comment]
Thanks for fixing it.
