### PR TITLE
net: ipv6: Drop NS packet if LL address is too long

### LINKED ISSUE #6235: echo server crash from ICMPv6 NS source link layer address anomaly
Defensics test case 10912: 0000000025G ICMPv6.NDP.Neighbor-solicitation.Neighbor-Solicitation.IPv6-Packet.payload.protocol.icmpv6-message.ndp-neighbor-solicitation.options.ndp-options.RFC2461-source-link-layer-address.element   Repeat+of+128+octets%3A+type+length+data

This test case crashes echo server in QEMU.

[icmpv6-ns-10912.zip](https://github.com/zephyrproject-rtos/zephyr/files/1730825/icmpv6-ns-10912.zip)

[net/ipv6] [DBG] handle_ns_input: (0x004037c0): Received Neighbor Solicitation from fe80::8c0:deff:fefc:102f to ff02::1:ff00:1, target 2001:db8::1
[net/nbr] [DBG] net_nbr_ref_debug: (0x004037c0): nbr 0x0041f080 ref 1 (net_nbr_get():81)
[net/ipv6] [DBG] nbr_new: (0x004037c0): nbr 0x0041f080 iface 0x0041fb00 state 0 IPv6 fe80::8c0:deff:fefc:102f
[net/ipv6] [DBG] net_ipv6_send_ns: (0x004037c0): Sent Neighbor Solicitation from fe80::1200:ff:fe00:10 to ff02::1:fffc:102f, target fe80::8c0:deff:fefc:102f
[net/ipv6] [DBG] net_ipv6_nbr_add: (0x004037c0): [0] nbr 0x0041f080 state 0 router 0 IPv6 fe80::8c0:deff:fefc:102f ll 0A:C0:DE:FC:10:2F iface 0x0041fb00
[net/ipv6] [DBG] net_ipv6_send_na: (0x004037c0): Sent Neighbor Advertisement from 2001:db8::1 to fe80::8c0:deff:fefc:102f, target 2001:db8::1
[net/ipv6] [DBG] check_route: (0x004037c0): No default route to fe80::8c0:deff:fefc:102f
[net/ipv6] [DBG] net_ipv6_prepare_for_send: (0x004037c0): Neighbor lookup 0x0041f080 (0) iface 0x00000000 addr fe80::8c0:deff:fefc:102f state incomplete
[net/ipv6] [DBG] net_ipv6_prepare_for_send: (0x004037c0): Neighbor 0x0041f080 addr 0A:C0:DE:FC:10:2F
***** CPU Page Fault (error code 0x00000010)
Supervisor thread executed address 0xc00a1001
PDE: 0x00 Non-present, Read-only, Supervisor, Execute Enabled
PTE: 0x00 Non-present, Read-only, Supervisor, Execute Enabled
Current thread ID = 0x004037c0
Faulting segment:address = 0x0008:0xc00a1001
eax: 0x00000000, ebx: 0xc00a1001, ecx: 0x0040c450, edx: 0x00000000
esi: 0x2f10fcde, edi: 0xc00a1001, ebp: 0x2f10fcde, esp: 0x0040c51c
eflags: 0x246
Fatal fault in essential thread! Spinning...
Terminate emulator due to fatal kernel error

### PR DESCRIPTION
**Pull request by rmstoi**
This commit fixes the crash of echo_server from overflow in ICMPv6 NS
source link-layer address option.

Fixes #6235

Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>

### CODE REVIEW

File: subsys/net/ip/ipv6.c [hunk 1]
```diff
@@ -1432,6 +1432,12 @@ static enum net_verdict handle_ns_input(struct net_pkt *pkt)
 				goto drop;
 			}
 
+			if (nd_opt_hdr->len > 2) {
+				NET_ERR("Invalid source link-layer address "
```
Comment (jukkar) [inline subsys/net/ip/ipv6.c]: I would not call this "Invalid ... length", it is just that the we do not support such long link layer address in zephyr currently. So we could say here "Too long source link-layer address length ...."
Same thing for commit message, this issue is in ipv6 and not in icmpv6, so change it to "net: ipv6: Drop NS packet if LL address len is too long"

**Review by jukkar — CHANGES_REQUESTED** [review]

**Review by jukkar — APPROVED** [review]
