### PR TITLE
usb: uvc: use uvc_device_ in API and add _enable()/_shutdown()

### LINKED ISSUE #104855: USB Composite Device with UVC and CDC
### Describe the bug

Using both UVC and CDC doesn't currently seem to work.  You can test this by modifying the sample/uvc project.  

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Modify the samples/subsys/usb/uvc/app.overlay 
dts

```
/ {
	chosen {
		zephyr,console = &cdc_acm_uart;
		zephyr,shell-uart = &cdc_acm_uart;
	};
};

&zephyr_udc0 {
	uvc: uvc {
		compatible = "zephyr,uvc-device";
	};

	cdc_acm_uart: cdc_acm_uart0 {
		compatible = "zephyr,cdc-acm-uart";
		label = "Zephyr USB CDC-ACM";
	};
};
```

2. cd zephyr
3. west build -p -b stm32n6570_dk --sysbuild -S video-sw-generator samples/subsys/usb/uvc/
4. west flash

### Relevant log output

```shell
*** Booting MCUboot v2.2.0-278-gd9c2ba153128 ***
*** Using Zephyr OS build v4.3.0-4645-g1bc469bcb454 ***
I: Starting bootloader
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Primary image: magic=bad, swap_type=0x1, copy_done=0x2, image_ok=0x2
I: Secondary image: magic=bad, swap_type=0x1, copy_done=0x2, image_ok=0x2
I: Boot source: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Bootloader chainload address offset: 0x10000
I: Image version: v0.0.0
I: Jumping to the first image slot
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS = Linux
- zephyr version - v4.3.0-4645-g1bc469bcb454
- Git hash - 1bc469bcb454f307b2ef73e1059fa2e341bc00a1

## Board tested with
* stm32n6570_dk 
* nrf52840dk/nrf52840

#### Note
I wanted to rule out that this wasn't at ST driver problem

## Related bug
* [MIDI and CDC](https://github.com/zephyrproject-rtos/zephyr/discussions/70553)

####  Note
I can build this example and i can see that i can get a composite USB device.  So it must be the combination of both UVC and CDC

## Wireshark capture

So it's building the proper USB description table

Image

### PR DESCRIPTION
**Pull request by josuah**
Use a different API call to complete the function rather than relying on USB `.init()` to terminate the configuration.

This allows to setup the endpoint descriptors before `usbd_init()` is called.

Tested with `west build -b nrf52840dk/nrf52840 -S video-sw-generator samples/subsys/usb/uvc/`

Not yet tested with both CDC ACM and UVC.

Fixes: #104855 (UVC part)

### CODE REVIEW

File: include/zephyr/usb/class/usbd_uvc.h [hunk 1]
```diff
@@ -34,20 +34,20 @@
...
  * request to @p video_dev.
  *
- * @note This function must be called before @ref usbd_enable.
+ * @note This function must be called before @ref uvc_device_enable.
  *
  * @param uvc_dev Pointer to the UVC device to configure
  * @param video_dev Pointer to the video device to which controls requests are sent
  */
-void uvc_set_video_dev(const struct device *uvc_dev, const struct device *video_dev);
+void uvc_device_set_video_dev(const struct device *uvc_dev, const struct device *video_dev);
```
Comment (jfischer-no) [inline include/zephyr/usb/class/usbd_uvc.h]: IMO it sounds a bit weird. I suggest to call it uvc_device_init().
`uvc_device_init()`
`uvc_device_add_format()`
`uvc_device_enable()`
`uvc_device_shutdown()`
matches better with what we have in the USB.

Btw, are there any reason to call uvc_device_add_format() multiple times or could we merge uvc_device_init() and uvc_device_add_format()?
```c
uvc_device_set_video_dev(const struct device *uvc_dev,
			 const struct device *video_dev,
			 const struct video_format *const fmt);
```

Comment (josuah) [reply include/zephyr/usb/class/usbd_uvc.h]: Calling `uvc_device_add_format()` in a loop is used to progressively fill the list of descriptors. To merge it with `uvc_device_init()`, this would require an array of formats used only for this call. So in theory still possible.

Thank you once again, updated. Let me know if more modifications should be done.

File: subsys/usb/device_next/class/usbd_uvc.c [hunk 2]
```diff
@@ -1499,6 +1499,11 @@ int uvc_device_enable(const struct device *const dev)
 	const struct uvc_config *cfg = dev->config;
 	int ret;
 
+	if (atomic_test_bit(&data->state, UVC_STATE_INITIALIZED)) {
+		LOG_DBG("UVC instance '%s' is already initialized via usb_init()", dev->name);
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_uvc.c]: uvc_device_enable() should be called after it is initialized.

```c
	if (!atomic_test_bit(&data->state, UVC_STATE_INITIALIZED)) {
		LOG_ERR("UVC instance '%s' is not initialized", dev->name);
		return -EIO;
```

File: subsys/usb/device_next/class/usbd_uvc.c [hunk 3]
```diff
@@ -1596,6 +1606,11 @@ int uvc_device_add_format(const struct device *const dev, const struct video_for
...
+		return 0;
+	}
+
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_uvc.c]: uvc_device_add_format() should be called after it is initialized.

```c
	if (!atomic_test_bit(&data->state, UVC_STATE_INITIALIZED)) {
		LOG_ERR("UVC instance '%s' is not initialized", dev->name);
		return -EIO;
```

File: subsys/usb/device_next/class/usbd_uvc.c [hunk 4]
```diff
@@ -1564,6 +1569,11 @@ void uvc_device_init(const struct device *const dev, const struct device *const
 	uint32_t mask = 0;
 	size_t map_sz = 0;
 
+	if (atomic_test_bit(&data->state, UVC_STATE_INITIALIZED)) {
+		LOG_DBG("UVC instance '%s' is already initialized via usb_init()", dev->name);
+		return 0;
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_uvc.c]: `void uvc_device_init(`!, I will be surprised if it not fail in CI.
```c
	if (atomic_test_bit(&data->state, UVC_STATE_INITIALIZED)) {
		LOG_DBG("UVC instance '%s' is already initialized", dev->name);
		return;
```

File: subsys/usb/device_next/class/usbd_uvc.c (hunk 2 above)
Comment (josuah) [reply subsys/usb/device_next/class/usbd_uvc.c]: I think I got confused and this PR was incomplete: I was still setting `UVC_STATE_INITIALIZED` from `uvc_init()` while I should have set it in `uvc_device_init()`.

Now works while done in this order (if it is the correct one):

- `uvc_device_init()` (which sets `UVC_STATE_INITIALIZED`)
- `uvc_device_add_format()` (in loop)
- `uvc_device_enable()`
- `usbd_init()`
- `usbd_enable()`

File: subsys/usb/device_next/class/usbd_uvc.c (hunk 4 above)
Comment (josuah) [reply subsys/usb/device_next/class/usbd_uvc.c]: I changed at the last moment and did not update everywhere...
Also updated from `LOG_DBG()` to `LOG_ERR()`.

File: subsys/usb/device_next/class/usbd_uvc.c (hunk 3 above)
Comment (josuah) [reply subsys/usb/device_next/class/usbd_uvc.c]: Updated as seen above.

File: subsys/usb/device_next/class/usbd_uvc.c [hunk 5]
```diff
@@ -1503,28 +1525,46 @@ static int uvc_init(struct usbd_class_data *const c_data)
...
-void uvc_set_video_dev(const struct device *const dev, const struct device *const video_dev)
+void uvc_device_init(const struct device *const dev, const struct device *const video_dev)
 {
 	struct uvc_data *data = dev->data;
 	const struct uvc_config *cfg = dev->config;
 	const struct uvc_control_map *map = NULL;
 	uint32_t mask = 0;
 	size_t map_sz = 0;
 
+	if (atomic_test_bit(&data->state, UVC_STATE_INITIALIZED)) {
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_uvc.c]: Better to test and set atomically 
```c
	if (atomic_test_and_set_bit(&data->state, UVC_STATE_INITIALIZED)) {
```

File: include/zephyr/usb/class/usbd_uvc.h [hunk 6]
```diff
@@ -27,27 +26,29 @@
  */
 
 /**
- * @brief Set the video device that a UVC instance will use for control requests.
+ * @brief Initialize a video device class.
```
Comment (jfischer-no) [inline include/zephyr/usb/class/usbd_uvc.h:29]: Please update `* @version 0.1.0` to `* @version 0.1.1` in the L:22.

File: subsys/usb/device_next/class/usbd_uvc.c (hunk 5 above)
Comment (josuah) [reply subsys/usb/device_next/class/usbd_uvc.c]: done, also removing the `atomic_set_bit()`

File: include/zephyr/usb/class/usbd_uvc.h (hunk 6 above)
Comment (josuah) [reply include/zephyr/usb/class/usbd_uvc.h:29]: done, I forgot to do it

**Review by jfischer-no — DISMISSED** [review]

**Review by jfischer-no — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
