### PR TITLE
Fix shell fault when too many arguments in the command were provided

### LINKED ISSUE #28108: EEPROM shell MPU Fault when performing a write command with more than 9 bytes
**Describe the bug**
Using EEPROM console to write more than 9 bytes on an AT24 gives MPU fault. The read is performing up to 256 (max allowed). When create a mock for `.transfer` with a `return 0` was noted the same behavior. This indicate that problem can be outside drivers.

**To Reproduce**
1. build hello world app
2. make menuconfig and enable an I2C + EEPROM AT24 + Console with 256 bytes buffer + Log + UART backend
3. execute: eeprom write <device> 0 8 7 6 5 4 3 2 1 0 1 2 3

**Expected behavior**
EEPROM Shell working up to 256 bytes for read and write

**Impact**
EEPROM Shell doesn't execute a write command with more than 9 bytes.

**Logs and console output**

```
uart:~$ eeprom write EEPROM_CAPE 10 8 7 6 5 4 3 2 1 0 1 2 3
Writing 9 bytes to EEPROM...
Verif[00:00:09.516,000] <err> os: ***** MPU FAULT *****
[00:00:09.516,000] <err> os:   Data Access Violation
[00:00:09.516,000] <err> os:   MMFAR Address: 0xceab
[00:00:09.516,000] <err> os: r0/a1:  0x00000000  r1/a2:  0x20000370  r2/a3:  0x00000002
[00:00:09.516,000] <err> os: r3/a4:  0x0000cea7 r12/ip:  0x000016ee r14/lr:  0x00007f99
[00:00:09.516,000] <err> os:  xpsr:  0x21000000
[00:00:09.516,000] <err> os: r4/v1:  0x00000000  r5/v2:  0x0000cc05  r6/v3:  0x0000f49b
[00:00:09.516,000] <err> os: r7/v4:  0x0000f597  r8/v5:  0x0000e8ed  r9/v6:  0x00000000
[00:00:09.516,000] <err> os: r10/v7: 0x00000000  r11/v8: 0x00000000    psp:  0x20003970
[00:00:09.517,000] <err> os: Faulting instruction address (r15/pc): 0x00003480
[00:00:09.517,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:09.517,000] <err> os: Current thread: 0x20000370 (shell_uart)
[00:00:09.604,000] <err> os: Halting system
```

Looking at LST file the that fault happen at `shell->ctx->state = state;` command:
```
	if ((flag_last_nl_get(shell) == 0U) ||
    3440:	f412 4f7f 	tst.w	r2, #65280	; 0xff00
    3444:	d005      	beq.n	3452 <shell_process+0xf6>
	return shell->ctx->internal.flags.last_nl;
    3446:	f8d0 2638 	ldr.w	r2, [r0, #1592]	; 0x638
    344a:	f3c2 2207 	ubfx	r2, r2, #8, #8
    344e:	4293      	cmp	r3, r2
    3450:	d1e0      	bne.n	3414 <shell_process+0xb8>
	shell->ctx->internal.flags.last_nl = val;
    3452:	f8d0 2638 	ldr.w	r2, [r0, #1592]	; 0x638
    3456:	f363 220f 	bfi	r2, r3, #8, #8
    345a:	f8c0 2638 	str.w	r2, [r0, #1592]	; 0x638
				if (!shell->ctx->cmd_buff_len) {
    345e:	8e42      	ldrh	r2, [r0, #50]	; 0x32
    3460:	b99a      	cbnz	r2, 348a <shell_process+0x12e>
	shell->ctx->internal.flags.history_exit = val ? 1 : 0;
    3462:	f8d0 3638 	ldr.w	r3, [r0, #1592]	; 0x638
    3466:	f362 1386 	bfi	r3, r2, #6, #1
    346a:	f8c0 3638 	str.w	r3, [r0, #1592]	; 0x638
	shell_history_mode_exit(shell->history);
    346e:	68e0      	ldr	r0, [r4, #12]
    3470:	f009 fb9b 	bl	cbaa <shell_history_mode_exit>
	shell_raw_fprintf(shell->fprintf_ctx, "\n");
    3474:	497b      	ldr	r1, [pc, #492]	; (3664 <shell_process+0x308>)
    3476:	6960      	ldr	r0, [r4, #20]
    3478:	f009 f875 	bl	c566 <shell_raw_fprintf>
	shell->ctx->state = state;
    347c:	68a3      	ldr	r3, [r4, #8]
    347e:	2202      	movs	r2, #2
    3480:	711a      	strb	r2, [r3, #4]
```

**Environment (please complete the following information):**
 - OS: Linux
 - Zephyr SDK 0.11.3
 - 2.4.0-rc1

**Additional context**
List file for MPU Enabled: [zephyr.lst](https://github.com/zephyrproject-rtos/zephyr/files/5180615/zephyr.txt)

__

### PR DESCRIPTION
**Pull request by nordic-krch**
Added fix and test case.

Fixes #28108.

### CODE REVIEW

File: subsys/shell/shell.c [hunk 1]
```diff
@@ -704,6 +704,16 @@ static int execute(const struct shell *shell)
 
 	}
 
+	if ((cmd_lvl == CONFIG_SHELL_ARGC_MAX) && (argc == 2)) {
+		/* argc == 2 indicates that when command string was parsed
+		 * there was more characters remaining. It means that number of
+		 * arguments exceeds the limit.
+		 */
+		shell_internal_fprintf(shell, SHELL_ERROR,
```
Comment (jakub-uC) [inline subsys/shell/shell.c:712]: This is not an error but a shell feature described in the documentation. If there are more arguments than `CONFIG_SHELL_ARGC_MAX` remaining are treated as a 1 argument.

Comment (nordic-krch) [reply subsys/shell/shell.c:712]: discussed offline with @jakub-uC: it is a documented behavior of shell but it is probably not what user expects. Since if too many arguments is provided then it's better to get notified than pass unexpected arguments to the handler.

Comment (nordic-krch) [reply subsys/shell/shell.c:712]: removed information from kconfig.

**Review by jakub-uC — APPROVED** [review]

**Review by pabigot — APPROVED** [review]
As best I can tell, while the documented behavior was to support a var-args--like solution where unexpected arguments were packaged into a single one, in fact the implementation never did anything but write past the end of an array.

So it's fine.

Since this removes a documented feature that somebody may have coded support for in a command (but never tested) I think there should be a release note bullet about the removal (feature was never  implemented, use causes overruns memory).  That could be done in this commit, or, because multiple PRs are targeting the release notes, it could be in a separate PR to avoid conflicts that would block merging this.

(If I'm wrong and there is a situation where the documented behavior was provided without generating fault, things become more complicated.)

**Comment by jakub-uC** [comment]
@pabigot This feature use to work fine but apperantly it was broken by 512de5ecac62de202cf17676d57c7c9d466dc3e2 .
Current implementation is in fact not backward compatible but I think it is a better solution from user experience perspective.

We were also discussing with @nordic-krch  about removing the parameter `CONFIG_SHELL_ARGC_MAX` and implement a dynamic memory allocation for arguments. Nevertheless this solution will be also having a drawback. It can lead to stack overflow.

**Comment by pabigot** [comment]
OK, so it was broken in a previous release (2.3).  More evidence we need much better test coverage.

Then I think it definitely merits a release note that explains the feature was inadvertently broken in 2.3, and rather than fixing it it's been removed in 2.4.

**Comment by nandojve** [comment]
> OK, so it was broken in a previous release (2.3). More evidence we need much better test coverage.

Agreed! Zephyr is currently fail because with don't cover all (minimal) paths. CI don't run all configs, even for a release. Confirmed with #28341 and previous advertised with #27151.

**Comment by nordic-krch** [comment]
@nandojve 
> Agreed! Zephyr is currently fail because with don't cover all (minimal) paths. CI don't run all configs, even for a release. 

It was actually different case: missing test case. Added now.

@pabigot @jakub-uC 
> Then I think it definitely merits a release note

Added a note, can you take a look?

File: doc/releases/release-notes-2.4.rst [hunk 2]
```diff
@@ -508,6 +508,12 @@ Libraries / Subsystems
 * Tracing:
   * Tracing backed API now checks if init function exists prio to calling it.
 
+* Shell:
+  * Fix case when number of arguments exceeded ``CONFIG_SHELL_ARGC_MAX``. Prior
+    2.3 when more arguments were provided then last argument contained remaining
+    arguments as one string. In 2.4 it was broken and system was crashing in
+    that case. Now it will report that command cannot be processed.
```
Comment (pabigot) [inline doc/releases/release-notes-2.4.rst:515]: s/Prior 2.3/Prior to 2.3/
s/2.4/2.3/

If you'd take a complete rewording:

```
* Change behavior when more than ``CONFIG_SHELL_ARGC_MAX`` arguments
  are passed.  Before 2.3 extra arguments were joined to the last
  argument.  In 2.3 extra arguments caused a fault.  Now the shell
  will report that the command cannot be processed.
```

Comment (nordic-krch) [reply doc/releases/release-notes-2.4.rst]: done

**Comment by nandojve** [comment]
> @nandojve
> 
> > Agreed! Zephyr is currently fail because with don't cover all (minimal) paths. CI don't run all configs, even for a release.
> 
> It was actually different case: missing test case. Added now.

Yes, I have a better perspective now.
