### PR TITLE
API Change: Stream Flash: Deprecating stream_flash_erase_page

### LINKED ISSUE #67407: stream_flash:  stream_flash_erase_page allows to accidently erase stream
**Describe the bug**
According to `stream_flash_erase_page` description it is erasing page unless it has already been erased in given stream flash context.
The function takes context which holds information like current write pointer for stream flash or last erased page and offset of page to erase:
https://github.com/zephyrproject-rtos/zephyr/blob/8785438d313fd20310661cc82c8e2327d2891271/include/zephyr/storage/stream_flash.h#L118-L130
The fact that the function allows to select page offset to erase is a problem.

In the concept of stream flash it should be only allowed to append data to the stream, so obviously only the forward pages should erased. The logic withing `stream_flash_erase_page` only protects against erasing the previously erased page, by a call to `stream_flash_erase_page`; which means that the function can erase any other page within the stream with no problem, it is not even checked if the page contains any data or not.

Additional problem with the function is that it will refuse (it will do nothing, no error) to erase page that ctx points to be erased, but once you select other page for erase and repeat request to the previous one it will be erased with no problem.
For example lets assume sequence:
```
stream_flash_buffered_write(ctx, ...)
stream_flash_erase_page(ctx, 0)
```
where `stream_flash_buffered_write` started writing to stream, the page 0 will be erased prior to write, so call to `stream_flash_erase_page`, as the page is marked as erased in ctx, but sequence:
```
stream_flash_erase_page(ctx, offset_of_any_other_page);
stream_flash_erase_page(ctx, 0);
```
has just destroyed data written by the `stream_flash_buffered_write`, yet data pointer still points to where previous write ended.
This happens due to:
https://github.com/zephyrproject-rtos/zephyr/blob/8785438d313fd20310661cc82c8e2327d2891271/subsys/storage/stream/stream_flash.c#L88-L100
where it is enough for previously erased page offset to differ from current, for erase to be performed.

There is a case for using the `stream_flash_erase_page`, although not in current form: when avoiding lengthy erase on write.
It may happen that buffers need to be synced to device, in which case next page may be required to be erase, which takes time;
knowing that user may request erase of the next page in most convenient moment.
The function `stream_flash_erase_page` should be deprecated, and replaced, to serve above case, function that would take size of predicted write and would make sure that enough space is erased, by erasing if needed, for the next write of the predicted size.
**User should not be allowed to erase any arbitrary page within stream.**

**To Reproduce**
The problem with `stream_flash_erase_page` has been found by @katgiadla, while running stream flash tests and can be reproduced by invoking:
```
zephyr/scripts/twister -T zephyr/tests/subsys/storage/stream/stream_flash/ -p nrf52840dk_nrf52840 --device-testing --device-serial  /dev/ttyACM0 -v --inline-logs
```
The above tests requires `nrf52840dk_nrf52840` but the problem is universal.

The test will fail at the line:
https://github.com/zephyrproject-rtos/zephyr/blob/8785438d313fd20310661cc82c8e2327d2891271/tests/subsys/storage/stream/stream_flash/src/main.c#L429
with information that the page has not been erased as expected.

**Expected behavior**
I do not know what is intended behavior of the `stream_flash_erase_page`, as I have described above that the page may or may not be erased, depending on whether other page has been erased previously.

**Impact**
With limited use of the function outside of the stream flash API, the impact is not huge.
With the rather undefined behaviour of the function it is just asking for weird bugs to happen.

**Environment (please complete the following information):**
 - OS: Linux 
 - Toolchain 016.1(e.g Zephyr SDK, ...)
 - Commit SHA 240bd8e16ac1f714356843720925387225de8df0

### PR DESCRIPTION
**Pull request by de-nordic**
A few commits that
 - move stream flash logic to stop using stream_flash_erase_page
 - fixing tests
 - marking  the stream_flash_erase_page as deprecated

Fixes #67407

### CODE REVIEW

**Review by maass-hamburg — DISMISSED** [review]

File: subsys/storage/stream/Kconfig [hunk 1]
```diff
@@ -18,6 +18,22 @@ config STREAM_FLASH_ERASE
...
 	  to.
+	  Option available only if there is at least one device in, a configuration,
+	  that requires erase prior to write.
+
+config STREAM_FLASH_ERASE_ONLY_WHEN_SUPPORTED
+	bool "Check if device supports erase prior to attempting one"
+	depends on STREAM_FLASH_ERASE
+	depends on FLASH_HAS_NO_EXPLICIT_ERASE
+	help
+	  This is used in stream flash code to exclude invocation of erase
```
Comment (nordicjm) [inline subsys/storage/stream/Kconfig:29]: n.b. for future: column length is 100 characters not 80

File: subsys/storage/stream/stream_flash.c [hunk 2]
```diff
@@ -72,7 +72,65 @@ static int settings_direct_loader(const char *key, size_t len,
...
+	}
+
+	/* Trying to append beyond available range? */
+	if (ctx->bytes_written + size > ctx->available) {
+		return -ERANGE;
+	}
+
+#if defined(CONFIG_STREAM_FLASH_ERASE_ONLY_WHEN_SUPPORTED)
+	/* There are both types of devices */
+	const struct flash_parameters *fparams = flash_get_parameters(ctx->fdev);
```
Comment (nordicjm) [inline subsys/storage/stream/stream_flash.c:103]: should declare variables at top

File: subsys/storage/stream/stream_flash.c [hunk 3]
```diff
@@ -72,7 +72,65 @@ static int settings_direct_loader(const char *key, size_t len,
...
+	LOG_DBG("Erasing page at offset 0x%08lx", (long)page.start_offset);
+
+	rc = flash_erase(ctx->fdev, page.start_offset, page.size);
+
+	if (rc != 0) {
+		LOG_ERR("Error %d while erasing page", rc);
+	} else {
+		ctx->erased_up_to += page.size;
+	}
+
```
Comment (nordicjm) [inline subsys/storage/stream/stream_flash.c:128]:
```suggestion
```

File: subsys/storage/stream/stream_flash.c [hunk 4]
```diff
@@ -85,6 +143,11 @@ int stream_flash_erase_page(struct stream_flash_ctx *ctx, off_t off)
 		return -ERANGE;
 	}
 
+	/* Do not allow pages that has already been erased */
```
Comment (nordicjm) [inline subsys/storage/stream/stream_flash.c:146]: -has+have

**Review by nordicjm — DISMISSED** [review]
minor nit.

**Review by kartben — CHANGES_REQUESTED** [review]
- deprecated API should be mentioned in the release notes (with brief mention of what's the suggested replacement)
- doxygen comment of the deprecated API should indicate what's the suggested replacement so that people who will potentially start seeing warnings in their code know what to do
- https://github.com/zephyrproject-rtos/zephyr/issues/80539 to be updated with a bullet point referencing this PR so that future-you knows when it's time to actually drop the API.

thanks!

**Comment by de-nordic** [comment]
> * deprecated API should be mentioned in the release notes (with brief mention of what's the suggested replacement)

Migration guide separately or in the deprecation note?

> 
>     * doxygen comment of the deprecated API should indicate what's the suggested replacement so that people who will potentially start seeing warnings in their code know what to do
> 
>     * [Deprecated APIs/options to be removed by 4.3 #80539](https://github.com/zephyrproject-rtos/zephyr/issues/80539) to be updated with a bullet point referencing this PR so that future-you knows when it's time to actually drop the API.
> 
> 
> thanks!

Sure, will do that. Note though that Stream Flash API is not considered stable, that is why deprecation process was not followed in the first place.

**Comment by maass-hamburg** [comment]
> * deprecated API should be mentioned in the release notes (with brief mention of what's the suggested replacement)

@kartben maybe the [docs](https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html) should be changed, so that entries in migration changes are also needed for experiential and unstable api, to document the established practice here.

**Comment by de-nordic** [comment]
@kartben Can you help here? This
https://github.com/zephyrproject-rtos/zephyr/actions/runs/12930306331/job/36061561448?pr=82326
image
ain't caused by my lines? 
image

File: doc/releases/release-notes-4.1.rst [hunk 5]
```diff
@@ -43,6 +43,14 @@ Deprecated in this release
   the same functionality in their application code by reconnecting to the peer when the
   :c:member:`bt_conn_cb.disconnected` callback is invoked.
 
+* Deprecated the :c:func:`stream_flash_erase_page` from Stream Flash API. The same functionality
+  can be achieved using :c:func:`flash_area_erase` or :c:func:`flash_erase`. Nevertheless
+  erasing of a device, while stream flash is supposed to do so, as configured, will result in
+  data lost from stream flash. There are only two situations where device should be erased
+  directly:
+    1) when Stream Flash is not configured to do erase on its own
+    2) when erase is used for removal of a data prior or after Stream Flash uses the designated area.
```
Comment (kartben) [inline doc/releases/release-notes-4.1.rst:52]:
```suggestion
  directly:

  1. when Stream Flash is not configured to do erase on its own
  2. when erase is used for removal of a data prior or after Stream Flash uses the designated area.```

Comment (de-nordic) [reply doc/releases/release-notes-4.1.rst]: Thanks!

**Review by maass-hamburg — DISMISSED** [review]

File: doc/releases/release-notes-4.1.rst [hunk 6]
```diff
@@ -88,6 +88,17 @@ Deprecated APIs and options
...
+  can be achieved using :c:func:`flash_area_erase` or :c:func:`flash_erase`. Nevertheless
+  erasing of a device, while stream flash is supposed to do so, as configured, will result in
+  data lost from stream flash. There are only two situations where device should be erased
+  directly:
+
+  1. when Stream Flash is not configured to do erase on its own
+  2. when erase is used for removal of a data prior or after Stream Flash uses the designated area.
+
+* Deprecated TinyCrypt library. The reasons for this are (:github:`43712`):
+
```
Comment (kartben) [inline doc/releases/release-notes-4.1.rst:101]: rebase glitch

```suggestion
```

**Review by kartben — CHANGES_REQUESTED** [review]

**Review by kartben — APPROVED** [review]

**Review by maass-hamburg — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]
