### PR TITLE
mgmt: smp: Fix shell sending smp response to wrong UART

### LINKED ISSUE #26939: MCUMGR - smp shell server sends responses to wrong port
**Describe the bug**

smp_shell always outputs responses to the console instead of back to the device that the shell is running on.

The shell can be run on any port, not just the console, and we can add smp_shell to any shell. When the shell is running on a port which is not the console it is correctly passing the received data to smp_shell, its just that smp_shell sends the reply out to the console, and not to the port the shell is running on.

Every dts that uses mcumgr, also has the console on the same port as the shell, there is no existing board that routes the mcumgr to a different place than the console. Hence you would never have seen this issue.

What have you tried to diagnose or workaround this issue?

I followed the flow of the data from mcumgr on the host computer, into the USB serial port, into the shell, and into smp_shell. All is working as expected. smp_shell then formulates a response to the mcumgr request and gets it ready to send,  but at the very last step. The function smp_shell_tx_raw() in subsys/mgmt/smp_shell.c is hard coded to always send the response via k_str_out(). k_str_out() is part of  lib/os/printk and calls __char_out(). The function __char_out() is hooked into printk with the function __printk_hook_install() very early in the kernel boot phases and all the places that the hook is installed always installs it to the console.

as a workaround I changed: 
`k_str_out((void *)data, len);`
to
`shell_print_stream(shell_backend_uart_get_ptr(), data, len);`
in the function smp_shell_tx_raw().

**To Reproduce**

First build the application and load it onto a nrf52840_mdk board. This works for Zephyr v2.3.0
```
#!/bin/bash
#
# defaults if none specified on command line
set -e 
KEY=mykey-rsa-2048.pem
VERSION=1.0
#BOARD=irdeto_gen1
BOARD=nrf52840_mdk
#parse the options
while getopts v:k:b: option
do
case "${option}"
in
k) KEY=${OPTARG};;
v) VERSION=${OPTARG};;
b) BOARD=${OPTARG};;
*) options -v VERSION, -k KEY, -b BOARD
esac
done
echo rebuild the project, for $BOARD, sign the image and flash the image. 
echo - using signing key $KEY
echo - adding version number $VERSION
echo - the board is -D`echo $BOARD | tr [a-z] [A-Z]` 

rm -rf build
west build -b $BOARD -- -DDTC_OVERLAY_FILE=`pwd`/$BOARD.overlay -DSET_BOARD=`echo $BOARD | tr [a-z] [A-Z]`
west sign -t imgtool -- --key ../../$KEY --version $VERSION
west flash --hex-file build/zephyr/zephyr.signed.hex
```
At this point the console will be running on the MDK board serial port. The hardware USB2UART on the MDK board will present the console on the host as /dev/ttyACM0. The Shell will be running on the USB CDC_ACM serial port. This will be visible on the host as /dev/ttyACM1. shell commands sent to /dev/ttyACM1 using a program such as tio work as expected.

Monitor /dev/ttyACM0 with a program like tio. There should be no output.

Next try to load a file into the littlefs using mcumgr

```
#!/bin/bash
#
# defaults if none specified on command line
ASSET=../assets/82841136.bin
#parse the options
while getopts a: option
do
case "${option}"
in
a) ASSET=${OPTARG};;
*) options -a ASSET
esac
done
echo flash the asset info into the littlefs over USB
echo - programming asset $ASSET
sudo ~/.go/bin/mcumgr conn add zephyr type=serial connstring="dev=/dev/ttyACM1" #,baud=115200"
sudo ~/.go/bin/mcumgr -c zephyr fs upload $ASSET /settings/Blob
```

mcumgr will timeout waiting for a response, however the response will be visible on the tio that is monitoring /dev/ttyACM0. This is the incorrect behaviour.

**Expected behavior**

mcumgr should upload the file to the littlefs.

**Impact**
I am having to rework my system to put the console and the shell on the same port.

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Ubuntu Linux, running on virtualbox under Windows
 - Toolchain  - Zephyr SDK 0.11.4
 - Commit SHA or Version used - v2.3.0 release.

support files prj.config, .config, and an overlay

[files.gz](https://github.com/zephyrproject-rtos/zephyr/files/4939286/files.gz)

### PR DESCRIPTION
**Pull request by de-nordic**
The commit fixes problem where the SMP over shell response was sent
via UART attached to the console rather than the UART attached to
the shell.

Fixes #26939

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

File: subsys/mgmt/mcumgr/smp_shell.c [hunk 1]
```diff
@@ -136,10 +140,19 @@ static uint16_t smp_shell_get_mtu(const struct net_buf *nb)
 	return CONFIG_MCUMGR_SMP_SHELL_MTU;
 }
 
+extern struct shell_transport shell_transport_uart;
+
 static int smp_shell_tx_raw(const void *data, int len, void *arg)
 {
-	/* Cast away const. */
-	k_str_out((void *)data, len);
+	struct shell_uart *const su = shell_transport_uart.st->ctx;
```
Comment (jakub-uC) [inline subsys/mgmt/mcumgr/smp_shell.c:147]: This will not compile :)

File: subsys/mgmt/mcumgr/smp_shell.c [hunk 2]
```diff
@@ -136,10 +140,19 @@ static uint16_t smp_shell_get_mtu(const struct net_buf *nb)
 	return CONFIG_MCUMGR_SMP_SHELL_MTU;
 }
 
+extern struct shell_transport shell_transport_uart;
```
Comment (jakub-uC) [inline subsys/mgmt/mcumgr/smp_shell.c:143]: You can get rid of this extern to make code a bit cleaner. You are able to access this structure using API function:
`shell_backend_uart_get_ptr()`

File: subsys/mgmt/mcumgr/smp_shell.c [hunk 3]
```diff
@@ -136,10 +140,19 @@ static uint16_t smp_shell_get_mtu(const struct net_buf *nb)
...
+
 static int smp_shell_tx_raw(const void *data, int len, void *arg)
 {
-	/* Cast away const. */
-	k_str_out((void *)data, len);
+	struct shell_uart *const su = shell_transport_uart.ctx;
```
Comment (jakub-uC) [inline subsys/mgmt/mcumgr/smp_shell.c:147]: shouldn't it be:
`struct shell_uart const *const su`?

File: subsys/mgmt/mcumgr/smp_shell.c [hunk 4]
```diff
@@ -136,10 +140,19 @@ static uint16_t smp_shell_get_mtu(const struct net_buf *nb)
...
+	struct shell_uart_ctrl_blk *const scb = su->ctrl_blk;
```
Comment (jakub-uC) [inline subsys/mgmt/mcumgr/smp_shell.c:148]: I think we can also add `const` here as well

File: subsys/mgmt/mcumgr/smp_shell.c (hunk 1 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_shell.c]: Fixed.

File: subsys/mgmt/mcumgr/smp_shell.c (hunk 3 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_shell.c:147]: Yes, actually nothing here modifies these structure so they may be const.

File: subsys/mgmt/mcumgr/smp_shell.c (hunk 2 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_shell.c]: Done.

File: subsys/mgmt/mcumgr/smp_shell.c (hunk 4 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_shell.c]: Done

**Comment by carlescufi** [comment]
Can you please add more information in the commit message? Why did `k_str_out()` send the message to the wrong device?

**Review by carlescufi — APPROVED** [review]

File: subsys/mgmt/mcumgr/smp_shell.c [hunk 5]
```diff
@@ -138,8 +142,15 @@ static uint16_t smp_shell_get_mtu(const struct net_buf *nb)
 
 static int smp_shell_tx_raw(const void *data, int len, void *arg)
 {
-	/* Cast away const. */
-	k_str_out((void *)data, len);
+	const struct shell_uart *const su = shell_backend_uart_get_ptr();
```
Comment (pabigot) [inline subsys/mgmt/mcumgr/smp_shell.c:145]: I wish this idiom of adding const to local variables wasn't being used.  It's not common in Zephyr, and creates difficulties when using Coccinelle to do massive changes involving `const` like #24873 

However there's enough of this already in-tree it's not worth changing IMO.  We might have to deal with it globally some day.

File: subsys/mgmt/mcumgr/smp_shell.c [hunk 6]
```diff
@@ -138,8 +142,15 @@ static uint16_t smp_shell_get_mtu(const struct net_buf *nb)
...
+	const struct shell_uart_ctrl_blk *const scb = su->ctrl_blk;
+	const uint8_t *out = data;
+
+	while (out && len) {
```
Comment (pabigot) [inline subsys/mgmt/mcumgr/smp_shell.c:149]: Some day real soon this would have to become:

    while ((out != NULL) && (len > 0)) {

since implicit treatment of pointers and integers as booleans is a MISRA violation.

**Review by pabigot — APPROVED** [review]

File: subsys/mgmt/mcumgr/smp_shell.c (hunk 6 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_shell.c:149]: Will fix.

File: subsys/mgmt/mcumgr/smp_shell.c (hunk 5 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_shell.c:145]: I do not know, I kinda like it. It just tells me that I am just using this constant as an shortcut/alias only.
It helped me to find bug once when I have used `=` instead of `==`  in conditional expression, in the old times.
