### PR TITLE
sensors: Fix alignment issues

### LINKED ISSUE #62845: Hard fault when reading sensors using shell on MCUs without unaligned read/write support
**Describe the bug**
When reading sensors using the `sensor get` command on the Zephyr shell on a nRF51 device, a hard fault occurs.
Reading sensors in the application seems to work though (I tried the `samples/sensor/die_temp_polling` sample).
I observed this on `nrf51dk_nrf51422` and a nRF51822-based board. The type of sensor does not seem to make a difference (I first noticed this with an external SHT30 connected via I²C).
Other platforms don't seem to be affected (I tried nRF52840 and STM32WB55RG).

This is a regression; using `git bisect` I found that commit ca5bf10143 (by @yperess) is the first with this bug.

**To Reproduce**
1. Connect a `nrf51dk_nrf51422` board to your PC
2. `cd zephyr/samples/sensor/sensor_shell`
3. `west build -p -b nrf51dk_nrf51422`
4. `west flash`
5. connect to the nRF51DK serial using a serial monitor, e.g. `picocom /dev/ttyACM0 -b 115200`
6. `sensor info` (optional)
7. `sensor get temp@4000c000`

**Expected behavior**
I expect to get sensor value readings as follows:
```
uart:~$ sensor info
device name: temp@4000c000, vendor: Nordic Semiconductor, model: nrf-temp, friendly name: (null)
uart:~$ sensor get temp@4000c000
channel idx=12 die_temp =  23.500000
uart:~$
```

**Impact**
No relevant impact on me.

**Logs and console output**
The hard fault (on commit ed380de152):
```
uart:~$ sensor info
device name: temp@4000c000, vendor: Nordic Semiconductor, model: nrf-temp, friendly name: (null)
uart:~$ sensor get temp@4000c000
[00:00:15.710,723] <err> os: ***** HARD FAULT *****
[00:00:15.710,876] <err> os: r0/a1:  0x00000005  r1/a2:  0x00000005  r2/a3:  0x00000005
[00:00:15.710,968] <err> os: r3/a4:  0x20001331 r12/ip:  0x00000005 r14/lr:  0x00007a09
[00:00:15.711,029] <err> os:  xpsr:  0x21000000
[00:00:15.711,090] <err> os: Faulting instruction address (r15/pc): 0x00007ada
[00:00:15.711,273] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:15.711,456] <err> os: Current thread: 0x200008a0 (shell_uart)
[00:00:15.784,423] <err> os: Halting system
```

When attaching GDB, I can get the following backtrace (image and text are identical):
image
```
(gdb) bt
#0  arch_system_halt (reason=reason@entry=0) at /home/jo/zephyrproject/zephyr/kernel/fatal.c:32
#1  0x00008f8c in k_sys_fatal_error_handler (reason=reason@entry=0, esf=esf@entry=0x20003038 <z_interrupt_stacks+1984>) at /home/jo/zephyrproject/zephyr/kernel/fatal.c:46
#2  0x00009058 in z_fatal_error (reason=0, reason@entry=536883240, esf=esf@entry=0x20003038 <z_interrupt_stacks+1984>) at /home/jo/zephyrproject/zephyr/kernel/fatal.c:131
#3  0x00005d7c in z_arm_fatal_error (reason=536883240, reason@entry=0, esf=0x20003038 <z_interrupt_stacks+1984>, esf@entry=0x20003058 <z_interrupt_stacks+2016>) at /home/jo/zephyrproject/zephyr/arch/arm/core/aarch32/fatal.c:63
#4  0x00006078 in z_arm_fault (msp=<optimized out>, psp=<optimized out>, exc_return=<optimized out>, callee_regs=<optimized out>) at /home/jo/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:1132
#5  0x0000612c in z_arm_hard_fault () at /home/jo/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault_s.S:102
#6  <signal handler called>
#7  0x00007ada in sensor_submit_fallback (iodev_sqe=0x0 <_vector_table>, dev=0x20001b38 <_sqe_pool_sensor_read_rtio_sqe_pool>) at /home/jo/zephyrproject/zephyr/drivers/sensor/default_rtio_sensor.c:181
#8  sensor_iodev_submit (iodev_sqe=0x0 <_vector_table>) at /home/jo/zephyrproject/zephyr/drivers/sensor/default_rtio_sensor.c:26
#9  0x0000ccc4 in rtio_iodev_submit (iodev_sqe=<optimized out>) at /home/jo/zephyrproject/zephyr/subsys/rtio/rtio_executor.c:28
#10 0x0000cd08 in rtio_executor_submit (r=r@entry=0x20000340 <sensor_read_rtio>) at /home/jo/zephyrproject/zephyr/subsys/rtio/rtio_executor.c:94
#11 0x000074c2 in z_impl_rtio_submit (r=0x20000340 <sensor_read_rtio>, wait_count=0) at /home/jo/zephyrproject/zephyr/include/zephyr/rtio/rtio.h:1424
#12 rtio_submit (r=0x20000340 <sensor_read_rtio>, wait_count=0) at /home/jo/zephyrproject/zephyr/samples/sensor/sensor_shell/build/zephyr/include/generated/syscalls/rtio.h:161
#13 sensor_read (iodev=0x2000036c <iodev_sensor_shell_read>, ctx=0x20000340 <sensor_read_rtio>, userdata=0x20002668 <shell_uart_stack+1520>) at /home/jo/zephyrproject/zephyr/include/zephyr/drivers/sensor.h:893
#14 cmd_get_sensor (sh=<optimized out>, argc=2, argv=<optimized out>) at /home/jo/zephyrproject/zephyr/drivers/sensor/sensor_shell.c:309
#15 0x000047e4 in exec_cmd (help_entry=0x200026d0 <shell_uart_stack+1624>, argv=0x200026e8 <shell_uart_stack+1648>, argc=<optimized out>, sh=0xd980 <shell_uart>) at /home/jo/zephyrproject/zephyr/subsys/shell/shell.c:558
#16 execute (sh=sh@entry=0xd980 <shell_uart>) at /home/jo/zephyrproject/zephyr/subsys/shell/shell.c:800
#17 0x00004a32 in state_collect (sh=0xd980 <shell_uart>) at /home/jo/zephyrproject/zephyr/subsys/shell/shell.c:1004
#18 shell_process (sh=0xd980 <shell_uart>) at /home/jo/zephyrproject/zephyr/subsys/shell/shell.c:1475
#19 0x0000b692 in shell_signal_handle (sh=sh@entry=0xd980 <shell_uart>, sig_idx=sig_idx@entry=SHELL_SIGNAL_RXRDY, handler=handler@entry=0x4875 <shell_process>) at /home/jo/zephyrproject/zephyr/subsys/shell/shell.c:1292
#20 0x000050f4 in shell_thread (arg_log_backend=<optimized out>, arg_log_level=<optimized out>, shell_handle=0xd980 <shell_uart>) at /home/jo/zephyrproject/zephyr/subsys/shell/shell.c:1351
#21 shell_thread (shell_handle=0xd980 <shell_uart>, arg_log_backend=<optimized out>, arg_log_level=<optimized out>) at /home/jo/zephyrproject/zephyr/subsys/shell/shell.c:1308
#22 0x0000a840 in z_thread_entry (entry=0x5061 <shell_thread>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at /home/jo/zephyrproject/zephyr/lib/os/thread_entry.c:36
#23 0xaaaaaaaa in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.1

### PR DESCRIPTION
**Pull request by yperess**
Add padding to the header and remove unnecessary memset in order to fix alignment faults in cores such as M0 or ones that support CONFIG_TRAP_UNALIGNED_ACCESS

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/62845

### CODE REVIEW

File: include/zephyr/drivers/sensor.h [hunk 1]
```diff
@@ -806,10 +806,15 @@ struct __attribute__((__packed__)) sensor_data_generic_header {
...
 	int8_t shift;
 
+	int8_t _padding;
+
 	/* Channels present in the frame */
 	enum sensor_channel channels[0];
 };
 
+BUILD_ASSERT((sizeof(struct sensor_data_generic_header) & (sizeof(void *) - 1)) ==
+	     sizeof(enum sensor_channel));
```
Comment (fabiobaltieri) [inline include/zephyr/drivers/sensor.h:816]: this may be worth a line of comment

Comment (yperess) [reply include/zephyr/drivers/sensor.h:820]: Done

**Review by fabiobaltieri — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

File: include/zephyr/drivers/sensor.h [hunk 2]
```diff
@@ -806,10 +806,19 @@ struct __attribute__((__packed__)) sensor_data_generic_header {
 	/* Shift value for all samples in the frame */
 	int8_t shift;
 
+	int8_t _padding;
```
Comment (tristan-google) [inline include/zephyr/drivers/sensor.h:809]: Is there a simple way to turn this off to save memory on platforms that do support unaligned access?

**Review by tristan-google — DISMISSED** [review]

File: include/zephyr/drivers/sensor.h (hunk 2 above)
Comment (yperess) [reply include/zephyr/drivers/sensor.h:809]: I checked with Fabio and currently there's no Kconfig to tell us if we have support for unaligned access

Comment (fabiobaltieri) [reply include/zephyr/drivers/sensor.h:809]: yeah not that I'm aware of anyway, afaik normally the compiler decides on whether to generate unaligned code or not based on the target architecture and flags like `-mno-unaligned-access`, the Kconfig option is just to enable trapping of those for architecture that supports both. I don't think that the compiler has anything that you could use, at least not in the preprocessor, but I may be wrong here, or maybe you could use an align attribute in the field.

Comment (MaureenHelm) [reply include/zephyr/drivers/sensor.h:809]: If we're having alignment issues then we shouldn't be packing this struct.

Comment (yperess) [reply include/zephyr/drivers/sensor.h:809]: Discussed with Fabio offline, the packing doesn't actually change this, we need to have alignment on the end of the struct with the size of `enum sensor_channel`, packing (or not) won't affect this (I checked). If packing and the `_padding` are removed we still run into the issue.

Comment (yperess) [reply include/zephyr/drivers/sensor.h:809]: I've tweaked the assert to check for `% sizeof(enum sensor_channel) == 0`

Comment (yperess) [reply include/zephyr/drivers/sensor.h]: OK, 2 problems were making this more difficult than expected:
1. `size_t` isn't always the same, I replaced it with `uint32_t` for the `num_channels` field of the header.
2. `sizeof(enum sensor_channel)` isn't always the same (some platforms used 2 bytes others 4). So I made the `_padding` variable based on it.

Comment (fabiobaltieri) [reply include/zephyr/drivers/sensor.h]: ouch :-\ how bad would it be to memcpy the samples in local buffers instead?

Comment (teburd) [reply include/zephyr/drivers/sensor.h]: is it the samples or the channel array that's the issue? I'm gathering that it's the channel array is unaligned because of the int8_t and packed attribute?

Comment (yperess) [reply include/zephyr/drivers/sensor.h]: Both

**Review by fabiobaltieri — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
I'm not really a fan of adding padding to align members of a packed structure, but I don't think it's worth holding up the release as this is an experimental API. Please revisit after the release

**Comment by fabiobaltieri** [comment]
Thanks everyone
