### PR TITLE
kernel: mmu: fix compilation warnings when memory size is 0

### LINKED ISSUE #64633: kernel: mmu: compilation warnings when memory size is 0
**Describe the bug**

The following code might generate compilation warnings if:
- `CONFIG_SRAM_BASE_ADDRESS` is 0, or
- `CONFIG_SRAM_BASE_ADDRESS` is 0 and `CONFIG_SRAM_SIZE` is 0, or
- `CONFIG_KERNEL_VM_BASE` is 0, or
- `CONFIG_KERNEL_VM_BASE` is 0 and `CONFIG_KERNEL_VM_SIZE` is 0

as the assert test would be essentially comparing unsigned int against 0, which will be escalated into error in Twister, see [this CI run](https://github.com/zephyrproject-rtos/zephyr/actions/runs/6705912230/job/18221509407?pr=63172).

https://github.com/zephyrproject-rtos/zephyr/blob/67676d8fbcf5d742bdc6bbf0635d79499fa66062/include/zephyr/sys/mem_manage.h#L193-L199

https://github.com/zephyrproject-rtos/zephyr/blob/67676d8fbcf5d742bdc6bbf0635d79499fa66062/include/zephyr/sys/mem_manage.h#L202-L209

https://github.com/zephyrproject-rtos/zephyr/blob/67676d8fbcf5d742bdc6bbf0635d79499fa66062/include/zephyr/sys/mem_manage.h#L226-L232

**To Reproduce**
1. Checkout `main` branch
2. In `sw_isr_table.h`, include additional `zephyr/device.h`, see https://github.com/zephyrproject-rtos/zephyr/pull/64630/commits/39e73a7c6b9e98a4a728597ff095f6b6c3bd5581
3. `west build -b nrf5340bsim_nrf5340_cpuapp -p always -T samples/subsys/logging/multidomain/sample.logging.multidomain.ipc_static_vrings.simu`

**Expected behavior**
Should compile without error nor warnings regardless of the configuration & without header dependency.

**Impact**
Blocking #63172

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 639d1f803b

**Additional context**

While this issue doesn't appear directly in `main` for some reason, including an additional `zephyr/device.h` in the `sw_isr_table.h` seems to 'reveal' the underlying issue.

### PR DESCRIPTION
**Pull request by ycsin**
When these memory sizes are defined to be zero, the assertions test will be comparing an unsigned int against zero which result in compilation warning, and will be raised to error in Twister.

Fix them with more conditional compilations, see also #63080

fixes #64633

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
Putting #if's around single arguments in a macro is sort of messy, especially in code like this that's already heavily #if'd.  Can't we refactor this to be readable, somehow?  They're assertions, they're supposed to be a clear expression of some kind of truth, right?  So when they fail we know how to fix it?

**Comment by ycsin** [comment]
> Putting #if's around single arguments in a macro is sort of messy, especially in code like this that's already heavily #if'd. Can't we refactor this to be readable, somehow? They're assertions, they're supposed to be a clear expression of some kind of truth, right? So when they fail we know how to fix it?

True, in less than 10 minutes after creating this PR, I doubt if I have the full picture to produce a legit fix, therefore I pulled this back to draft

File: include/zephyr/sys/mem_manage.h [hunk 1]
```diff
@@ -194,17 +194,21 @@ static inline uintptr_t z_mem_phys_addr(void *virt)
 #if CONFIG_KERNEL_VM_BASE != 0
 		 (addr >= CONFIG_KERNEL_VM_BASE) &&
 #endif
-		 (addr < (CONFIG_KERNEL_VM_BASE +
-			  (CONFIG_KERNEL_VM_SIZE))),
```
Comment (ycsin) [inline include/zephyr/sys/mem_manage.h:198]: When both `CONFIG_KERNEL_VM_BASE` and `CONFIG_KERNEL_VM_SIZE` are 0, `addr` will never be lesser than 0 and therefore it would be essentially:

```c
__ASSERT(false, ...);

**Comment by nashif** [comment]
why is this a hotfix? Is the issue breaking CI somewhere?

**Comment by ycsin** [comment]
> why is this a hotfix? Is the issue breaking CI somewhere?

Yes - https://github.com/zephyrproject-rtos/zephyr/actions/runs/6705912230/job/18221509407?pr=63172

**Comment by aescolar** [comment]
> > why is this a hotfix? Is the issue breaking CI somewhere?
> 
> Yes - https://github.com/zephyrproject-rtos/zephyr/actions/runs/6705912230/job/18221509407?pr=63172

A hotfix implies there is an issue in the plain main branch itself blocking development. That is, that tests do not pass on main itself.
It seems that failure you are pointing at is in your branch due to your branch changes(?).

=> Removing the hotfix label.

**Comment by ycsin** [comment]
> It seems that failure you are pointing at is in your branch due to your branch changes(?).

I think you are right, the warning was due to the inclusion of an additional `#include <zephyr/device.h>` in `sw_isr_table.h`

**Review by dcpleung — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
