### PR TITLE
Bluetooth: host: Fix potential deadlocks with the TX thread and system workqueue

### LINKED ISSUE #20938: ATT/L2CAP "deadlock"
To reproduce:

Pull this branch: https://github.com/carlescufi/zephyr/tree/gh-20938
EDIT: https://github.com/carlescufi/zephyr/tree/gh-20938-rev2 contains the patches from #20951

Build `samples/bluetooth/peripheral` and flash to an nRF52840 DK
Build `samples/bluetooth/central_hr` and flash to an nRF52840 DK
Examine the console output in the peripheral

Context: Modified sample app that is sending Write Cmd non-stop at high throughput while doing discovery and multiple control procedures over HCI (PHY, DLE, etc).

We just hit the following "deadlock" where we are waiting 30 seconds to allocate an ATT PDU (ATT MTU response). Depending on the timing one of the following symptoms happens:

1. HCI command send timeout and assert

The `k_sem_take(&sync_sem, HCI_CMD_TIMEOUT)` in `bt_hci_cmd_send_sync()` times out since it has a 10 second timeout.
This is because the TX thread is blocked (see below) and hence the HCI command is not sent at all.

```
ASSERTION FAIL [err == 0] @ ZEPHYR_BASE/subsys/bluetooth/host/hci_core.c:340
        k_sem_take failed with err -11
```

2. ATT packet allocation timeout

Same problem, but in this case there is no HCI command pending to be transmitted so instead of hitting the hci_core assert we get this:
```
[00:00:30.511,016] <wrn> bt_conn: Unable to allocate buffer: timeout 30000
[00:00:30.511,047] <err> bt_att: Unable to allocate buffer for op 0x03
```
---------

The TX thread follows this sequence:
```
hci_core: process_events()
conn: bt_conn_process_tx()
conn: send_buf()
conn: send_frag()
conn: add_pending_txt()
stuck at add_pending_tx::k_fifo_get(&free_tx, K_FOREVER);
```

The system workqueue in parallel follows this sequence:
```
l2cap: l2cap_rx_process()
l2cap: l2cap_chan_recv()
att: bt_att_recv()
att: att_mtu_req()
att: bt_att_create_pdu()
l2cap: bt_l2cap_create_pdu_timeout()
conn: bt_conn_create_pdu_timeout()
stuck at bt_conn_create_pdu_timeout::net_buf_alloc(pool, timeout) // timeout = 30 seconds
```

Perhaps we should reconsider the conditional statement [here](https://github.com/zephyrproject-rtos/zephyr/blob/03ae58490c13c72fe8401b2bd70f888c784a804a/subsys/bluetooth/host/conn.c#L2301), since this "deadlock" completely breaks the application.

### PR DESCRIPTION
**Pull request by jhedberg**
Three related patches, the essence is in the second one and described fairly well in its commit message:

This is a moderate redesign of the pending TX packet handling that aims to eliminate potential deadlocks between the TX thread and the system workqueue thread. The main changes are:
    
 - TX context (`bt_conn_tx`) is allocated during buffer allocation, i.e. not in the TX thread.   
 - We don't allocate a TX context unless there's an associated callback. When there's no callback simple integer counters are used for tracking.
 - The TX thread is no longer responsible for TX callbacks or scheduling of TX callbacks. Instead, the callbacks get directly scheduled (`k_work_submit`) from the RX priority thread.
 - The `CONFIG_BT_CONN_TX_MAX` defaults to `CONFIG_BT_L2CAP_TX_BUF_COUNT` and in most cases won't need changing.

Fixes #20938

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]
Tested with ipsp ping and had the same result.

File: subsys/bluetooth/host/conn_internal.h [hunk 1]
```diff
@@ -115,10 +116,10 @@ struct bt_conn {
 	u16_t		        rx_len;
 	struct net_buf		*rx;
 
-	/* Sent but not acknowledged TX packets */
+	/* Sent but not acknowledged TX packets with a callback */
 	sys_slist_t		tx_pending;
-	/* Acknowledged but not yet notified TX packets */
-	struct k_fifo		tx_notify;
+	/* Sent but not acknowledged TX packets without a callback */
+	u32_t                   pending_no_cb;
```
Comment (joerchan) [inline subsys/bluetooth/host/conn_internal.h]: Could we extend this comment to say that this is before the tx_pending?

i.e /* Sent but not acknowledged TX packets without a callback before the first element  with a callback */ ?

File: subsys/bluetooth/host/l2cap.c [hunk 2]
```diff
@@ -1707,7 +1703,8 @@ void bt_l2cap_recv(struct bt_conn *conn, struct net_buf *buf)
 		return;
 	}
 
-	l2cap_chan_recv_queue(chan, buf);
+	l2cap_chan_recv(chan, buf);
+	net_buf_unref(buf);
```
Comment (joerchan) [inline subsys/bluetooth/host/l2cap.c]: This change confuses me somewhat. Where was this done previously for the static channels?

**Review by joerchan — APPROVED** [review]

File: include/bluetooth/l2cap.h [hunk 3]
```diff
@@ -132,6 +129,9 @@ struct bt_l2cap_le_chan {
 	/** Segment SDU packet from upper layer */
 	struct net_buf			*_sdu;
 	u16_t				_sdu_len;
+
+	struct k_work			rx_work;
```
[the remark this answers is not in the document]
Comment (jhedberg) [reply include/bluetooth/l2cap.h]: This is part of the cleanup that I filed an issue for. *Most* of this trust can/should be compiled out without DYNAMIC_CHANNEL, but since I wanted to keep this PR minimal (due to the upcoming release I decided to leave this detail alone for now.

File: subsys/bluetooth/host/conn_internal.h (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/conn_internal.h]: sure, that does indeed make it clearer

File: subsys/bluetooth/host/l2cap.c (hunk 2 above)
Comment (jhedberg) [reply subsys/bluetooth/host/l2cap.c]: In the k_work callback that `l2cap_chan_recv_queue` schedules, i.e. `l2cap_rx_process()`, which then eventually called `l2cap_chan_recv()`
