### PR TITLE
net: ptp: Fix undefined bitwise shift in port management

### LINKED ISSUE #109133: Undefined bitwise shift behavior in PTP port management interval handling
### Describe the bug

The PTP subsystem has undefined behavior in bitwise shift operations when processing management messages. The `port_timer_set_timeout()` and `port_timer_set_timeout_random()` functions perform left and right shift operations using log_announce_interval and log_sync_interval values as shift counts.

These int8_t parameters can be set to extreme values via PTP management messages (e.g., values outside [-63, 63] range) that exceed the valid shift range for 64-bit operations, causing undefined behavior per C11 6.5.7p3 and C++11 5.8p1.

This is a security vulnerability as malicious PTP management frames could trigger undefined behavior.

### Regression

- [ ] This is a regression.

### Steps to reproduce

  1. Configure a Zephyr device with PTP enabled
  2. Send a PTP management message setting LOG_ANNOUNCE_INTERVAL or LOG_SYNC_INTERVAL to an extreme value (e.g., 127 or -128)
  3. The shift operation in timeout calculation uses this value, exceeding the 64-bit width limit
  4. Undefined behavior occurs

### Relevant log output

```shell
N/A - Undefined behavior may manifest as silent corruption, crashes, or unexpected values depending on toolchain/platform.
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

 - OS: Any
 - Toolchain: Any (C/C++ language specification issue)
 - Affected file: subsys/net/lib/ptp/port.c

### Additional Context

The fix involves clamping log_announce_interval and log_sync_interval to [-63, 63] range using CLAMP() macro when accepting values from PTP management frames, preventing shift operations outside the 64-bit width. Backport requested for v3.7-branch and v4.3-branch.

### PR DESCRIPTION
**Pull request by awojasinski**
Add bounds checking to PTP management interval parameters to prevent undefined behavior from bitwise shift operations.

The port_timer_set_timeout() and port_timer_set_timeout_random() functions perform left and right shift operations using the log_announce_interval and log_sync_interval values as shift counts. Without bounds validation, these int8_t parameters could be set to extreme values (e.g., via PTP management messages) that exceed the valid shift range, causing undefined behavior.

(C11, 6.5.7p3)
> If the value of the right operand is negative or is greater than
or equal to the width of the promoted left operand, the behavior is undefined

(C++11, 5.8p1)
> The behavior is undefined if the right operand is negative,
or greater than or equal to the length in bits of the promoted left operand.

Limit both log_announce_interval and log_sync_interval to the range [-63, 63] using MIN/MAX macros when accepting values from PTP management frames. This range is preventing shift operations outside the 64-bit width used in the timeout calculations.

Fixes: #109133

### CODE REVIEW

File: subsys/net/lib/ptp/port.c [hunk 1]
```diff
@@ -851,15 +851,18 @@ static int port_management_set(struct ptp_port *port,
...
 			       struct ptp_tlv_mgmt *tlv)
 {
+	static const int8_t limit = sizeof(uint64_t) * CHAR_BIT - 1;
 	bool send_resp = false;
 
 	switch (tlv->id) {
 	case PTP_MGMT_LOG_ANNOUNCE_INTERVAL:
-		port->port_ds.log_announce_interval = *tlv->data;
+		/* Use limits to protect from undefined bitwise shift operations */
+		port->port_ds.log_announce_interval = MAX(MIN(*tlv->data, limit), -limit);
```
Comment (jonas-5ae29c) [inline subsys/net/lib/ptp/port.c]: Nit: `CLAMP` might be clearer here.

Comment (awojasinski) [reply subsys/net/lib/ptp/port.c]: totally forgot about this macro, thanks!

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
