### PR TITLE
arch: arm: cortex_m: Fix meta-IRQ unable to preempt from interrupt

### LINKED ISSUE #80574: Meta-IRQ does not preempt cooperative threads when woken from IRQ  (cortex_m)
**Describe the bug**
I believe commit [42036cd](https://github.com/zephyrproject-rtos/zephyr/commit/42036cdbcae270d00b5bd08e805e33bbd3b5787f) broke the ability of Meta-IRQs to preempt all other threads even if those are cooperative. This was working as expected in Zephyr 3.5.0

```
Z_GENERIC_SECTION(.text._HandlerModeExit) void z_arm_exc_exit(void)
{
#ifdef CONFIG_PREEMPT_ENABLED
	/* If thread is preemptible */
	if (_kernel.cpus->current->base.prio >= 0) {
		/* and cached thread is not current thread */
		if (_kernel.ready_q.cache != _kernel.cpus->current) {
			/* trigger a context switch */
			SCB->ICSR |= SCB_ICSR_PENDSVSET_Msk;
		}
	}
#endif /* CONFIG_PREEMPT_ENABLED */
```
`if (_kernel.cpus->current->base.prio >= 0)` prevents the meta-IRQ from being woken when returning from an interrupt unblocking it with e.g sem_give()

The "promise" as stated in the documentation is broken: 
_The thread, once woken, will be guaranteed to run before the current CPU returns into application code._

**To Reproduce**
Have a cooperative thread doing some processing and have a meta-IRQ thread waiting for a semaphore. Unblock the meta-IRQ by calling a sem_give() from IRQ context. The meta-irq will not be woken immediately but I believe at the first possible reschedule point. 

**Expected behavior**
The meta-IRQ should preempt the cooperative thread and after processing return to that cooperative thread.  

**Impact**
(Severe impact) In our case, we are collected data from a front-end in a time-critical manner  (10ms interval) while also running Bluetooth host. Since BT_RX_WQ is a  cooperative thread the meta-IRQ cannot be woken within the time frame especially when connection is being established. 

**Environment :**

 - Zephyr 3.7.0

### PR DESCRIPTION
**Pull request by kietavainen**
This reverts commit 42036cdbcae270d00b5bd08e805e33bbd3b5787f.

Architecture specific code should not do preemption checking before context switch. This is already handled by the scheduler, so duplicating it would be redundant and error prone. These checks used to be necessary, but the scheduler has been rewritten since then and the checks were removed in 3a0cb2d35d9 (kernel: Remove legacy preemption checking, 2018-05-23).

The added checks tried to address #61761, and were motivated by this in the Architecture Porting Guide:
https://github.com/zephyrproject-rtos/zephyr/blob/5bc6446dcc317d3f3cff49b703ad32e8ecb724cd/doc/hardware/porting/arch.rst?plain=1#L255-L257

However, that part of the guide predates 3a0cb2d35d9 and is outdated. The check was also incorrect, as it didn't take scheduler locking nor meta-IRQs into account, and it was never verified to fix the issue according to [this comment](https://github.com/zephyrproject-rtos/zephyr/issues/61761#issuecomment-1946262214).

This PR also updates the meta-IRQ test to verify that meta-IRQs can preempt cooperative threads.

Fixes #80574

### CODE REVIEW

**Review by andyross — DISMISSED** [review]
No complaints about the extra test assert, but tests/kernel/sched/preempt is supposed to be covering all these cases already.  Do we know why that is passing for the affected (cortex-m only, right?) platforms?

File: tests/kernel/sched/metairq/src/main.c [hunk 1]
```diff
@@ -113,6 +115,8 @@ void coop_thread1(void *p1, void *p2, void *p3)
 	cnt2 = coop_cnt2;
 	zassert_equal(cnt2, LOOP_CNT, "Unexpected cnt2 at end: %d", cnt2);
 
+	printk("thread1 end\n");
```
Comment (nashif) [inline tests/kernel/sched/metairq/src/main.c:118]: debug code? Do we need this in the test?

Comment (kietavainen) [reply tests/kernel/sched/metairq/src/main.c:118]: Not necessarily. As the cooperative thread already printed when it ended, I added these for the other two threads. It also makes the failure case more clear in the logs, I think:
```
Running TESTSUITE suite_preempt_metairq
===================================================================
START - test_preempt_metairq
thread1 take sem
thread2 take sem
metairq start
give sem2
thread2 got sem
thread2 loop iteration 0
thread2 loop iteration 1
thread2 loop iteration 2
thread2 loop iteration 3
thread2 end

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/metairq/src/main.c:80: metairq_thread: (coop_cnt2 equal to LOOP_CNT)
thread2 wasn't preempted
 FAIL - test_preempt_metairq in 0.065 seconds
```

**Review by peter-mitsis — DISMISSED** [review]

**Comment by kartben** [comment]
@kietavainen CI failures seem legit?

**Comment by kietavainen** [comment]
> @kietavainen CI failures seem legit?

@kartben, Yes, the meta-IRQ test is supposed to fail on Cortex-M until #80574 is fixed. This PR just updated an existing test to reveal the issue.

**Comment by kietavainen** [comment]
This failure is a regression caused by 42036cd. I'm trying to figure out [here](https://github.com/zephyrproject-rtos/zephyr/issues/61761#issuecomment-2621398898) if a revert would be the best way to solve this.

**Comment by kietavainen** [comment]
In addition to the test update, this PR is now amended with a fix for #80574.

**Review by jhedberg — APPROVED** [review]

**Review by ithinuel — CHANGES_REQUESTED** [review]
This is reverting a fix for another issue.

As discussed in https://discord.com/channels/720317445772017664/1334503801402687549

The documentation in should be updated to:

> Fetch the cached thread from the ready queue
If the ready thread is a metaIRQ or (the current is interruptible and it is different from the current thread), invoke the context switch.
Else, do not invoke it.

The code in this function should be amended as per the suggestion from https://github.com/zephyrproject-rtos/zephyr/issues/80574#issuecomment-2451800979

**Comment by kietavainen** [comment]
> This is reverting a fix for another issue.
> 
> As discussed in https://discord.com/channels/720317445772017664/1334503801402687549

The [PR description](https://github.com/zephyrproject-rtos/zephyr/pull/84509#issue-2809514584) explains why the commit needs to be reverted and that there is no evidence that the commit fixed anything. You also [acknowledged](https://discord.com/channels/720317445772017664/1334503801402687549/1334513930059649055) that the assumed fix was never tested or verified. So it's just an assumption that the commit contains a fix.

> The documentation in should be updated to:
> 
> > Fetch the cached thread from the ready queue
> > If the ready thread is a metaIRQ or (the current is interruptible and it is different from the current thread), invoke the context switch.
> > Else, do not invoke it.

It's true that the documentation should be updated, but not like that. Instead, it should reflect the current scheduler behavior as explained in 3a0cb2d. I created #84977 to address this.

> The code in this function should be amended as per the suggestion from [#80574 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/80574#issuecomment-2451800979)

That's not enough, as that suggestion is still incorrect for scheduler locking. A correct check (albeit redundant as discussed before) is in this [comment](https://github.com/zephyrproject-rtos/zephyr/issues/61761#issuecomment-2621398898). I would not like to apply that change as it's redundant and might cause failures in the future if the scheduler is updated. This already happened when meta-IRQs were introduced, and that's what prompted the change to remove these checks from architecture specific code in 3a0cb2d. Besides, it would be adding redundant code into every IRQ.

**Comment by ithinuel** [comment]
> You also [acknowledged](https://discord.com/channels/720317445772017664/1334503801402687549/1334513930059649055) that the assumed fix was never tested or verified. So it's just an assumption that the commit contains a fix.

I acknowledged that no tests had been added to zephyr’s suites, not that is hasn’t been tested at all. @csheaupdesigns were you able to effectively test this? Maybe could you help with adding a test case for your issue?

Considering https://github.com/zephyrproject-rtos/zephyr/commit/3a0cb2d35d9499e5f8757bf07260160c448be02e dates back from 2018 and sched.c has had numerous changes since, @andyross is that commit message still relevant? What do you recommend?

**Comment by kietavainen** [comment]
> > You also [acknowledged](https://discord.com/channels/720317445772017664/1334503801402687549/1334513930059649055) that the assumed fix was never tested or verified. So it's just an assumption that the commit contains a fix.
> 
> I acknowledged that no tests had been added to zephyr’s suites, not that is hasn’t been tested at all.

I was referring to this in our Discord conversation:
> > However, it was never verified if the change fixed the issue:
> > https://github.com/zephyrproject-rtos/zephyr/issues/61761#issuecomment-1946262214

> Indeed, that is unfortunate 😦

Sorry if I misunderstood it. It would indeed be nice to know how this was tested and verified back then.

**Review by andyross — APPROVED** [review]
I'll buy this.  Do note that @ithinuel has a PR in #85080 that implements arch_switch(), (and that I'm about to pull the trigger on a semi-competing-but-very-different one!), which would/should obviate this bug by relying on the standard logic in the core kernel instead.

But no reason not to merge this if for no other reason that test coverage over the regression.  Which BTW I'm still confused about.  Why isn't tests/kernel/sched/preempt catching this?  Has anyone looked?

**Comment by kietavainen** [comment]
> But no reason not to merge this if for no other reason that test coverage over the regression. Which BTW I'm still confused about. Why isn't tests/kernel/sched/preempt catching this? Has anyone looked?

The bug should be triggered if there is a cooperative thread in a busy loop, e.g. `k_busy_wait()`, and then a meta-IRQ thread becomes ready from an IRQ, e.g. correctly timed `k_msleep()`. This is exactly what the meta-IRQ test is doing. I tried to trigger this scenario in the explicit preemption test, but didn't find a clean way yet. There is also this:
https://github.com/zephyrproject-rtos/zephyr/blob/b5c5ba8c832b8ac01b03a8a26ba76a49438b6cc5/tests/kernel/sched/preempt/src/main.c#L90-L97

**Comment by jhedberg** [comment]
@ithinuel I take it your "thumbs up" on https://github.com/zephyrproject-rtos/zephyr/pull/84509#pullrequestreview-2591024822 implies that you're not opposed to this going in? Your "changes requested" review is still blocking the merge however - would you like to dismiss that or change it to "Approved"?

**Review by ithinuel — APPROVED** [review]

**Comment by kietavainen** [comment]
As this fixes a regression introduced in v3.7.0, I'll add the backport labels for v3.7 and v4.0.
