### PR TITLE
wifi: fix SAE password validation and add shell support for SAE passwords

### LINKED ISSUE #103126: wifi: Shell connect command does not support passwords longer than 64 bytes
### Describe the bug

While testing the NET Wi-Fi functionality, I found that the current **wifi shell** connection command fails to connect to access points whose passwords exceed **64 bytes**.

```bash
wifi connect -s AP031 -p 1234567812345678123456781234567812345678123456781234567812345678
```

The failure happens in `zephyr/subsys/net/l2/wifi/wifi_mgmt.c`:

```c
static int wifi_connect(uint64_t mgmt_request, struct net_if *iface,
			void *data, size_t len)
{
  ......
  if (params->psk_length && (params->psk_length < 8 || params->psk_length > 64)) {
  	return -EINVAL;
  }

  if (params->sae_password_length &&
      (params->sae_password_length < 8 || params->sae_password_length > 64)) {
      return -EINVAL;
  }
}
```
In zephyr/subsys/net/l2/wifi/wifi_shell.c, we can see that  wifi shell command uses a PSK to store passwords:
```c
static int __wifi_args_to_params(...)
{
    ......
		case 'p':
			params->psk = state->optarg;
			params->psk_length = strlen(params->psk);
			break;
}
```
Therefore, the wifi shell command only accepts passwords shorter than 64 characters, which is not suitable for all use cases.
Could we also enable `sae_password` in the wifi shell command, or limit the length of the PSK separately based on the security type?

Additionally, the part of wifi_connect that checks the length of sae_password_length is also restricted to being less than 64?
But according to its definition, it should has "No length restrictions" or MAX as 128.

```c
struct wifi_connect_req_params {
    const uint8_t *sae_password;
/** SAE password length */
    uint8_t sae_password_length; /* No length restrictions */
    ...
};

/** Max SAW password length */
#define WIFI_SAE_PSWD_MAX_LEN 128
```

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SomilGupta98**
Summary
Fix SAE password length validation and add support in the Wi-Fi shell command to pass SAE passwords separately, enabling proper WPA3 connection handling.

Details
wifi_connect(....) incorrectly limited SAE password length to 64 bytes despite WIFI_SAE_PSWD_MAX_LEN allowing up to 128 bytes, causing connection failures with valid SAE passwords. This change updates the validation logic to use the correct limit.

Additionally, the Wi-Fi shell command previously stored all passwords as PSK, preventing SAE authentication paths from being used. Shell support is added to allow setting SAE passwords separately so WPA3 connections can be exercised correctly.

Fixes : #103126

### CODE REVIEW

File: subsys/net/l2/wifi/wifi_mgmt.c [hunk 1]
```diff
@@ -412,7 +412,8 @@ static int wifi_connect(uint64_t mgmt_request, struct net_if *iface,
 	}
 
 	if (params->sae_password_length &&
-	    (params->sae_password_length < 8 || params->sae_password_length > WIFI_SAE_PSWD_MAX_LEN)) {
+	    (params->sae_password_length < 8 ||
+	     params->sae_password_length > WIFI_SAE_PSWD_MAX_LEN)) {
```
Comment (MaochenWang1) [inline subsys/net/l2/wifi/wifi_mgmt.c:416]: this format change should be put into the first commit [wifi: fix SAE password length validation](https://github.com/zephyrproject-rtos/zephyr/pull/103313/changes/acbf26d53613b480229c9ad0a51f62ebc368105e)

Comment (SomilGupta98) [reply subsys/net/l2/wifi/wifi_mgmt.c:416]: Updated , pl check

**Review by MaochenWang1 — DISMISSED** [review]

File: subsys/net/l2/wifi/wifi_shell.c [hunk 2]
```diff
@@ -933,6 +933,19 @@ static int __wifi_args_to_params(const struct shell *sh, size_t argc, char *argv
...
+			    params->security == WIFI_SECURITY_TYPE_SAE_AUTO ||
+			    params->security == WIFI_SECURITY_TYPE_FT_SAE  ||
+			    params->security == WIFI_SECURITY_TYPE_SAE_EXT_KEY)) {
+
+		params->sae_password = params->psk;
+		params->sae_password_length = params->psk_length;
+
+		params->psk = NULL;
+		params->psk_length = 0;
+	}
```
Comment (krish2718) [inline subsys/net/l2/wifi/wifi_shell.c]:
```suggestion
	/* For SAE types, use -p passphrase as SAE password and clear PSK. */
	if (params->psk &&
	    (params->security == WIFI_SECURITY_TYPE_SAE_HNP ||
	     params->security == WIFI_SECURITY_TYPE_SAE_H2E ||
	     params->security == WIFI_SECURITY_TYPE_SAE_AUTO ||
	     params->security == WIFI_SECURITY_TYPE_FT_SAE ||
	     params->security == WIFI_SECURITY_TYPE_SAE_EXT_KEY)) {
		params->sae_password = params->psk;
		params->sae_password_length = params->psk_length;
		params->psk = NULL;
		params->psk_length = 0;
	}
```

Comment (krish2718) [reply subsys/net/l2/wifi/wifi_shell.c]: the indent also need to be fixed (see my suggestion)

Comment (SomilGupta98) [reply subsys/net/l2/wifi/wifi_shell.c]: updated , pl check

File: subsys/net/l2/wifi/wifi_shell.c [hunk 3]
```diff
@@ -933,6 +933,19 @@ static int __wifi_args_to_params(const struct shell *sh, size_t argc, char *argv
 		}
 	}
 
+	/* For SAE types, use -p passphrase as SAE password and clear PSK. */
+	if (params->psk &&
+	   (params->security == WIFI_SECURITY_TYPE_SAE_HNP ||
```
Comment (krish2718) [inline subsys/net/l2/wifi/wifi_shell.c]: sorry for the nit.Line 938-946 should be indented by a space i.e., align to opening brace in 937.

Comment (krish2718) [reply subsys/net/l2/wifi/wifi_shell.c]: or better yet use `git clang-format HEAD~1` (you might have to install or add this command).

Comment (SomilGupta98) [reply subsys/net/l2/wifi/wifi_shell.c]: could you clarify once again , 938-946 or 938-942

Comment (krish2718) [reply subsys/net/l2/wifi/wifi_shell.c]: sorry, it's 938-942, the statements inside `if` are properly indented.

Comment (SomilGupta98) [reply subsys/net/l2/wifi/wifi_shell.c]: using git clang-format HEAD~1 command , thanks for the tip

Comment (SomilGupta98) [reply subsys/net/l2/wifi/wifi_shell.c]: pushed the code again using the git clang-format HEAD~1 command , hopefully no formatting issues now

File: subsys/net/l2/wifi/wifi_shell.c (hunk 2 above)
Comment (krish2718) [reply subsys/net/l2/wifi/wifi_shell.c]: I still see a tab, not space. I have restarted the compliance job that should catch this.

Comment (SomilGupta98) [reply subsys/net/l2/wifi/wifi_shell.c]: Actually I just ran the clang-format command on the commit

File: subsys/net/l2/wifi/wifi_shell.c [hunk 4]
```diff
@@ -933,6 +933,18 @@ static int __wifi_args_to_params(const struct shell *sh, size_t argc, char *argv
 		}
 	}
 
+	/* For SAE types, use -p passphrase as SAE password and clear PSK. */
+	if (params->psk && (params->security == WIFI_SECURITY_TYPE_SAE_HNP ||
```
Comment (jukkar) [inline subsys/net/l2/wifi/wifi_shell.c]: Please change psk check to explicit (because the psk is not a boolean),
so `if (params->psk != NULL && (....`

**Comment by jukkar** [comment]
Please also change the commit subjects to `net: wifi: ...`

**Review by krish2718 — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
