### PR TITLE
drivers: nrf: Fix UART and UARTE hanging on RX errors

### LINKED ISSUE #19700: nrfx_uart RX hang on errors
I haven't set up a clear way to reproduce this, but I've seen cases where my nrf52832-based board will stop responding to input on the UART.  I noticed it particularly often while switching between a seral terminal and mcumgr, especially with `mcumgr reset`.  In my past experience with Nordic parts, this happens when there are unacknowledged errors like buffer overruns, parity errors, or BREAKs.

If I open up GDB while it's not receiving characters, I can see that `uart0_addr->EVENT_ERROR` is 1, and clearing it with `p uart0_addr->EVENT_ERROR=0` makes things work again.

Looking at the code (v2.0.0), I don't see any handling of `EVENT_ERROR` in the case where `CONFIG_UART_0_INTERRUPT_DRIVEN` is set.  The serial interrupt handler `uart_nrfx_isr` directly invokes the shell's `uart_callback`, but the UART API provides no way for the shell to handle these errors.
https://github.com/zephyrproject-rtos/zephyr/blob/8f1780f6dee29dc2b2db01744e328a1a4a20d0b8/subsys/shell/shell_uart.c#L118-L143

On the other hand, the async API (`CONFIG_UART_0_ASYNC`) has lots of what appears to be correct error handling in `uart_nrfx_uart.c`, so it seems that this should be added to the non-async code as well?

I haven't been able to reliably trigger the problem but a dumb patch like this appears to make things work for me:
```c
diff --git a/drivers/serial/uart_nrfx_uart.c b/drivers/serial/uart_nrfx_uart.c
index ec1f7b1db730..bca2bee49658 100644
--- a/drivers/serial/uart_nrfx_uart.c
+++ b/drivers/serial/uart_nrfx_uart.c
@@ -822,6 +822,9 @@ static void uart_nrfx_isr(void *arg)
 {
        ARG_UNUSED(arg);
 
+       if (nrf_uart_event_check(uart0_addr, NRF_UART_EVENT_ERROR))
+               nrf_uart_event_clear(uart0_addr, NRF_UART_EVENT_ERROR);
+
        if (irq_callback) {
                irq_callback(irq_cb_data);
        }
```

### PR DESCRIPTION
**Pull request by Mierunski**
Add clearing error event to UART and UARTE drivers.
Without it driver goes into infinite interrupt loop.

Fixes #19700 

Signed-off-by: Mieszko Mierunski <mieszko.mierunski@nordicsemi.no>

Solution proposed by @jimparis

### CODE REVIEW

**Comment by nordic-krch** [comment]
Do I understand correctly that legacy interrupt driven mode (`CONFIG_UART_INTERRUPT_DRIVEN`) had function for enabling and disabling error interrupt but did not have any means to read it or clear it?

**Comment by Mierunski** [comment]
> Do I understand correctly that legacy interrupt driven mode (`CONFIG_UART_INTERRUPT_DRIVEN`) had function for enabling and disabling error interrupt but did not have any means to read it or clear it?

There is a way to read and clear event source, but no possibility of clearing error event

File: drivers/serial/uart_nrfx_uart.c [hunk 1]
```diff
@@ -843,6 +843,10 @@ static void uart_nrfx_isr(void *arg)
 {
 	ARG_UNUSED(arg);
 
+	if (nrf_uart_event_check(uart0_addr, NRF_UART_EVENT_ERROR)) {
+		nrf_uart_event_clear(uart0_addr, NRF_UART_EVENT_ERROR);
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: Since this is called before the callback function, it will effectively preclude reading of the error source when any interrupt is enabled. Either this should be moved after the call to `irq_callback` or the [check](https://github.com/zephyrproject-rtos/zephyr/blob/27f358de34d8db27766207cbc09a51d131344253/drivers/serial/uart_nrfx_uart.c#L256) of `ERROR` event should be removed from `uart_nrfx_err_check`. The latter option seems to be better.
Same goes for UARTE.

**Review by anangl — CHANGES_REQUESTED** [review]

**Review by anangl — APPROVED** [review]

**Comment by jimparis** [comment]
LGTM

**Review by nordic-krch — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
Need to backport to 1.14.2 @Mierunski ??

**Review by anangl — APPROVED** [review]

**Comment by anangl** [comment]
> Need to backport to 1.14.2 @Mierunski ??

I think this should be backported to 1.14.
