### PR TITLE
soc: nxp: mcxn: configure CPU1 TrustZone access level

### LINKED ISSUE #88965: regression: NXP: GPIO inaccessible on frdm_mcxn947//cpu0
I broke GPIO access for cpu0 in https://github.com/zephyrproject-rtos/zephyr/pull/88523.  These changes to enable cpu1 now make the GPIO registers inaccessible from cpu0.  The blinky sample builds and runs, but fails to toggle the LED.  The button sample builds and runs, but fails to detect a button press.

### PR DESCRIPTION
**Pull request by DerekSnell**
Configures AHBSC MASTER_SEC_LEVEL register for the cpu1 before cpu1 is enabled.  By default, this gives CPU1 secure and privileged access to the rest of the SOC, same as CPU0.

This also reverts feb966df36cbb8b6d847b9f0873bc79195e7fd22.  Configuring the GPIO access permissions is no longer required for CPU1 to access the GPIO.

Resolves #88965 .

Tested using the blinky sample running on CPU1 using the following commands:
```
west build -b frdm_mcxn947//cpu1 samples/basic/blinky -d blinky_cpu1 -p -- -DCONFIG_SECOND_CORE_MCUX=y
west flash -d blinky_cpu1
west build -b frdm_mcxn947//cpu0 samples/hello_world/  -d hello_cpu0_loader -p -- -DCONFIG_SECOND_CORE_MCUX=y
west flash -d hello_cpu0_loader
```
GPIO also accessible from CPU0, tested with sample blinky and button.

### CODE REVIEW

**Comment by DerekSnell** [comment]
@alxrey and @ubieda , FYI

**Review by butok — DISMISSED** [review]

**Review by EmilioCBen — DISMISSED** [review]

**Review by ubieda — DISMISSED** [review]
I just tested and confirmed it fixes the regression. Thanks!

File: soc/nxp/mcx/mcxn/soc.c [hunk 1]
```diff
@@ -44,6 +44,11 @@ DT_FOREACH_STATUS_OKAY(nxp_lpspi, FLEXCOMM_CHECK)
 /* This function is also called at deep sleep resume. */
 static int second_core_boot(void)
 {
+	/* Configure CPU1 TrustZone access level before CPU1 is enabled */
+	AHBSC->MASTER_SEC_LEVEL |=
+		AHBSC_MASTER_SEC_LEVEL_CPU1(CONFIG_SECOND_CORE_MCUX_ACCESS_LEVEL);
+	AHBSC->MASTER_SEC_ANTI_POL_REG = (~AHBSC->MASTER_SEC_LEVEL & 0x3FFFFFF3U) | 0x80000000U;
```
Comment (alxrey) [inline soc/nxp/mcx/mcxn/soc.c:50]: Bits 3-2 (CPU1 field) are cleared by the mask `& 0x3FFFFFF3U`, which doesn't seem to be the intended behavior.

If COP1 in `MASTER_SEC_LEVEL` is set to 1 or 2 (_Non-secure and privileged Master_, respectively _Secure and non-privileged Master_), `MASTER_SEC_ANTI_POL_REG` will not have the inverse polarity of `MASTER_SEC_LEVEL` as specified.

IMHO, the mask should be set to `0x3FFFFFFFU`.

Comment (alxrey) [reply soc/nxp/mcx/mcxn/soc.c:50]: Shouldn't macros be used instead of hard-coded values?

Concretely:
```C
AHBSC->MASTER_SEC_ANTI_POL_REG = (~AHBSC->MASTER_SEC_LEVEL & ~AHBSC_MASTER_SEC_ANTI_POL_REG_MASTER_SEC_LEVEL_ANTIPOL_LOCK_MASK) | AHBSC_MASTER_SEC_ANTI_POL_REG_MASTER_SEC_LEVEL_ANTIPOL_LOCK(2);
```

**Review by alxrey — CHANGES_REQUESTED** [review]

File: soc/nxp/mcx/mcxn/soc.c (hunk 1 above)
Comment (DerekSnell) [reply soc/nxp/mcx/mcxn/soc.c]: Great feedback, @alxrey .  Updated as you requested.  Thanks for reviewing

**Review by ubieda — APPROVED** [review]
Refreshing my +1

**Comment by dleach02** [comment]
@alxrey did your request get satisfied?

**Comment by alxrey** [comment]
@dleach02 Yes, it looks perfect now.

**Comment by DerekSnell** [comment]
> @dleach02 Yes, it looks perfect now.

Thanks @alxrey , you still have a block on this PR.  Can you approve to dismiss your block?  Thank you for reviewing and your feedback.

File: boards/nxp/frdm_mcxn947/board.c [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright 2024-2025 NXP
+ * Copyright 2024  NXP
```
[the remark this answers is not in the document]
Comment (DerekSnell) [reply boards/nxp/frdm_mcxn947/board.c:2]: Hi @dleach02 , good question
I reverted my previous commit that modified this file.  After this revert, this file was effectively not updated in 2025.  Do you think we should update the copyright year anyway?

**Review by alxrey — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
