### PR TITLE
Bluetooth: audio: has: Fix coverity issues

### LINKED ISSUE #65325: [Coverity CID: 330933] Unchecked return value in subsys/bluetooth/audio/has.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/bluetooth/audio/has.c

Category: Error handling issues
Function: `client_alloc`
Component: Bluetooth
CID: [330933](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=330933)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/audio/has.c#L286

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #65326: [Coverity CID: 330726] Explicit null dereferenced in subsys/bluetooth/audio/has.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/bluetooth/audio/has.c#L288

Category: Null pointer dereferences
Function: `client_alloc`
Component: Bluetooth
CID: [330726](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=330726)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/audio/has.c#L288

```
282     #if defined(CONFIG_BT_HAS_PRESET_SUPPORT) || defined(CONFIG_BT_HAS_FEATURES_NOTIFIABLE)
283      k_work_init_delayable(&client->notify_work, notify_work_handler);
284     #endif /* CONFIG_BT_HAS_PRESET_SUPPORT || CONFIG_BT_HAS_FEATURES_NOTIFIABLE */
285     
286      bt_conn_get_info(conn, &info);
287     
>>>     CID 330726:  Null pointer dereferences  (FORWARD_NULL)
>>>     Passing null pointer "info.le.dst" to "context_find", which dereferences it.
288      client->context = context_find(info.le.dst);
289      if (client->context == NULL) {
290              client->context = context_alloc(info.le.dst);
291              if (client->context == NULL) {
292                      LOG_ERR("Failed to allocate client_context for %s",
293                              bt_addr_le_str(info.le.dst));
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_FORWARD_NULL). ([CWE-476](http://cwe.mitre.org/data/definitions/476.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by MariuszSkamra**
This fixes issues discovered by coverity check.

Fixes: #65325
Fixes: #65326

### CODE REVIEW

File: subsys/bluetooth/audio/has.c [hunk 1]
```diff
@@ -205,6 +205,8 @@ static struct has_client {
 
 static struct client_context *context_find(const bt_addr_le_t *addr)
 {
+	__ASSERT_NO_MSG(addr != NULL);
+
```
Comment (Thalley) [inline subsys/bluetooth/audio/has.c:209]: I'm not 100% convinced that coverity considers asserts as proper checks (may be run with asserts disabled?), so not sure if this will fix the issue or not. 

The (simple) alternative is of course just to add a `if (addr == NULL ) return NULL`.

**Review by Thalley — APPROVED** [review]
The changes look fine, but unsure whether coverity will agree

**Review by kruithofa — APPROVED** [review]
