### PR TITLE
fs: Fix fs_open resource leak when invoked on fs_file_t object in use

### LINKED ISSUE #29478: fs: fs_open can corrupt fs_open_t object given via zfp parameter
**Describe the bug**
There is no check, within `fs_open`, whether the provided zfp already points to used object.
This means that when `fs_open` is used twice on the same object it will overwrite contents of
zfp before passing execution to file system driver.
This may lead to two possible outcomes, depending on whether zfp is used for opening (1) file with the same path or (2) file with different path.
According to fs_api tests (1) should end with an error, but this is actually left to file system driver and is not certain.
In both cases the file system driver will be called which may result in resource leak; e.g. LittleFS will allocate slab memory overwriting original pointer within provided `fs_file_t` object before further deciding if open is successful or not; this means that at this point, if there has been already memory allocated by previous `fs_open`, if such occurred.
Depending on whether error occurred or not, and on stage, the pointers may be pointing to new resources, that might have been already released and is invalid, or  NULL

**To Reproduce**
Using LittleFS mounted partition.
Call fs_open, on different or the same file, twice and observe `fs_file_t->filep`.

**Expected behavior**
Not breaking the original structure and returning with error instead.

**Impact**
Possible data corruption, resource leaks, double assignment of the same file system driver structures to different file streams.

**Workaround**
Always `fs_close` `fs_file_t` before reusing structure. Avoid double-open as even on error the original `fs_file_t` object will be damaged.

**Environment (please complete the following information):**
-- zephyrproject-rtos/zephyr: c13603ef874b8c145b6cd32a3833a5d0eeeda9b5

### PR DESCRIPTION
**Pull request by de-nordic**
fs: Fix fs_open resource leak when invoked on fs_file_t object in use

Fixes problem when fs_open invoked on fs_file_t object, which is already
holding information on opened file, overwrites references to other
memory objects within the fs_file_t object causing resource leak.
If fs_open is invoked on already used fs_file_t object, it will return
-EBUSY.

Note: The change requires that all fs_file_t objects should be
initialized to 0.

Fixes: #29478

### CODE REVIEW

**Comment by nvlsianpu** [comment]
Maybe instead of `struct fs_file_t file = { 0 }` I would intoruce define of empty the fs_file_t variable or even introduce a macro which declares empty variable of fs_file_t type an use it everywhere.

**Comment by de-nordic** [comment]
> 
> 
> Maybe instead of `struct fs_file_t file = { 0 }` I would introduce a define of the empty fs_file_t variable or even introduce a macro which declares empty variable of fs_file_t type and use it everywhere.

Something like:
```
FS_FILE_T_INIT(name) { name.mp = 0; }
// usage
fs_file_t some;
FS_FILE_T_INIT(some);
```
or
```
MK_FS_FILE_T(name) name = { 0 };
// usage
MK_FS_FILE_T(some);
```

**Review by pabigot — CHANGES_REQUESTED** [review]
I'd like to see the commits that initialize the `fs_file_t` instances moved before the commit that requires they be initialized, otherwise bisect on fs tests may break.  Change the commit text to "in preparation for code changes that will require this" or some similar text instead of referring to `fs_open()` changes that won't be present yet.

I don't have a problem with `= { 0 };` as the initializer idiom, but I'd be fine with `FS_FILE_T_INITIALIZER` defined to `(struct fs_file_t){ 0 }` to make it more clear.  Or an inline function `fs_file_t_init()` that can be called.  Or both, with the latter using the former.

I **really** don't like macro functions to define initialized instances (among other things, they trigger checkpatch errors because it looks like code after declarations without an empty line), but since others in the community do like them I wouldn't block on it.

In any case the fact that you now need to initialize instances of `struct fs_file_t` before their first use must be part of the documentation of `struct fs_file_t`.

**Comment by de-nordic** [comment]
>  an inline function `fs_file_t_init()` that can be called

I will create the function. Now, as I think about it, the `= { 0 };` may require new changes later, when the `fs_type_f` gets extended with fields that require non-0 initialization, if such thing would happen
Not that I am not willing to do the changes again later, just users may not be happy to go through their code again.

File: include/fs/fs.h [hunk 1]
```diff
@@ -220,6 +220,22 @@ struct fs_statvfs {
...
+ *
+ * Initialized the fs_file_t object; the function needs to be invoked
+ * on object before first use with fs_open.
+ *
+ * @param zfp Pointer to file object
+ *
+ */
+inline void fs_file_t_init(struct fs_file_t *zfp)
+{
+	zfp->mp = NULL;
```
Comment (pabigot) [inline include/fs/fs.h:234]: Would you consider:

    *fp = (struct fs_file_t){
      flags = 0,
    };

This will initialize all fields to zero.  The only reason you need to provide even one is just because it's required syntactically.

This is a bit more flexible in that if you add or rename fields that would be initialized to zero you don't need to touch this function: they'll automatically be zeroed, which wouldn't happen if they're all set individually.

File: subsys/fs/fuse_fs_access.c [hunk 2]
```diff
@@ -468,6 +469,12 @@ static void fuse_fs_access_init(void)
 {
 	int err;
 	struct stat st;
+	int i = 0;
```
Comment (pabigot) [inline subsys/fs/fuse_fs_access.c:472]: Better to have this be `size_t` since it can never be negative and it's being compared to a value of type `size_t`.

File: tests/subsys/fs/fs_api/src/main.c [hunk 3]
```diff
@@ -72,6 +72,7 @@ void test_main(void)
 			 ztest_unit_test_setup_teardown(test_mount,
 							fs_setup,
 							dummy_teardown),
+			 ztest_unit_test(test_fs_file_t_init),
```
Comment (pabigot) [inline tests/subsys/fs/fs_api/src/main.c:75]: Why isn't this in the commit that adds this test case?

File: tests/subsys/fs/fs_api/src/test_fs.h [hunk 4]
```diff
@@ -32,6 +32,7 @@ struct test_fs_data {
 	int reserve;
 };
 
+void test_fs_file_t_init(void);
```
Comment (pabigot) [inline tests/subsys/fs/fs_api/src/test_fs.h:35]: this too.

**Review by pabigot — DISMISSED** [review]
The addition of `test_fs_init_t` seems to be split across two commits; it should all be together in the commit that adds the test.  This is the blocking request.

The other comments aren't blockers, just suggestions.

File: include/fs/fs.h (hunk 1 above)
Comment (de-nordic) [reply include/fs/fs.h:234]: @pabigot I have done that before, but this will fail compilation wit
```
tests/subsys/fs/fat_fs_dual_drive/src/main.c:18: undefined reference to `fs_file_t_init
```
and many other places, unless I will define the function as `static inline`.

File: tests/subsys/fs/fs_api/src/main.c (hunk 3 above)
Comment (de-nordic) [reply tests/subsys/fs/fs_api/src/main.c:75]: Some accidental addition to commit amend.

File: include/fs/fs.h (hunk 1 above)
Comment (pabigot) [reply include/fs/fs.h:234]: I hadn't noticed: why is this *not* `static inline`?  A non-static inline will fail exactly in that way unless you add this to some implementation file:

```
extern void fs_file_t_init(struct fs_file_t *zfp);
```

This guarantees that there is an extern version available for modules where the inline did not occur.  It comes from [C99](https://en.cppreference.com/w/c/language/inline), and for whatever reason we don't generally use it in Zephyr, preferring to use the old GNU extension `static inline` idiom which forces the inline (or a local callable implementation.

So, you can make this `static inline` so it's like almost every existing header inline function in Zephyr, or add the `extern` declaration to an implementation file.

Comment (de-nordic) [reply include/fs/fs.h:234]: Still: why without static the code with separate assignments linked fine while the one with cast did not?
Doesn't that mean that the assignments were always inlined while the other code could not be inlined in some situations?

Comment (pabigot) [reply include/fs/fs.h:234]: No idea.  The compiler's free to inline or not based on whatever rules it's using.

**Review by nvlsianpu — COMMENTED** [review]
Looks good now, although need to introduce fs_file_t_init() usage in the same commit which introduce the fix (or before).

Also I would introduce a test which will check whether fs_open() asserts on uninitialized fs_file_t variable

**Review by pabigot — COMMENTED** [review]
Unless I've missed something I don't see any need to change the commit order; the following command shows all commits pass all tests in `tests/subsys/fs`.  

```
git rebase -x 'twister -p k64f -T tests/subsys/fs' aed1db5782
```

Otherwise this looks good to me, though I agree a test that `fs_open` does return `-EBUSY` if the file structure is in use would be appropriate.

**Review by pabigot — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]
