### PR TITLE
lib: os: mpsc_pbuf: Fix infinite loop during allocation

### LINKED ISSUE #84286: Deferred logging causes calling thread to hang when log buffer is full
When I use deferred logging on a STM32 Nucleo L452RE-P board and the log buffer fills up, the thread that calls the LOG_* function hangs.

I can reproduce the behaviour with the following simple program:

```
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/drivers/gpio.h>

LOG_MODULE_REGISTER(main, CONFIG_LOG_DEFAULT_LEVEL);

// use large message size to fill up the log buffer
#define MSG_SIZE (CONFIG_LOG_BUFFER_SIZE/2)
#define LED0_NODE DT_ALIAS(led0)

int main(void)
{
	static char msg[MSG_SIZE];   // static because large buffer might not fit on stack

	for (int i = 0; i < sizeof(msg); ++i) {
		msg[i] = '.';
	}
	msg[sizeof(msg)-1] = '\0';

	const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(LED0_NODE, gpios);

	if (!gpio_is_ready_dt(&led)) {
		return 0;
	}

	if (gpio_pin_configure_dt(&led, GPIO_OUTPUT_ACTIVE) < 0) {
		return 0;
	}

	while (1) {
		gpio_pin_set_dt(&led, 1);
		LOG_INF("%s", msg);
		k_msleep(500);
		gpio_pin_set_dt(&led, 0);
		k_msleep(500);
	}

	return 0;
}
```

The test program is supposed to continuously log a large message (half the log buffer size) in order to fill up the log buffer.  It sets and clears the LED to indicate that it is still alive.  However when I run the program on the board the LED stays lit on the third iteration, indicating that it is hanging inside `LOG_INF`.

project configuration:
```
CONFIG_GPIO=y

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=128

#CONFIG_LOG_PRINTK=n
```

(you can ignore the `CONFIG_LOG_PRINTK=n` line for now; I disable `CONFIG_LOG_PRINTK` further down to get additional log messages from the `mpsc` module).

Console output:
```
*** Booting Zephyr OS build v4.0.0-3700-g09991d526a58 ***
[00:00:00.000,000] <inf> main: ...............................................................
[00:
```

It happens on both the latest Zephyr revision  (`09991d526a58f8a51ed9c59480b98a4f30c2053d`)  and also on Zephyr 3.6.0.

The problem does not occur when building the same project for the native_sim target:
```
*** Booting Zephyr OS build v4.0.0-3700-g09991d526a58 ***
[00:00:00.000,000] <inf> main: ...............................................................
[00:00:01.020,000] <inf> main: ...............................................................
[00:00:02.040,000] <inf> main: ...............................................................
[00:00:03.060,000] <inf> main: ...............................................................
```

Digging further into the problem suggests that there might be a bug in `mpsc_pbuf.c`, specifically in `mpsc_pbuf_alloc()`.  After enabling `MPSC_PBUF_DEBUG` and setting `CONFIG_LOG_PRINTK=n` I get the following neverending console output for the Nucleo target:

```
*** Booting Zephyr OS build v4.0.0-3700-g09991d526a58 ***
alloc 24 words, wr:0/0, rd:0/0
allocated 0x20000130, wr:0/24, rd:0/0
committed 0x20000130, wr:24/24, rd:0/0
>>claimed 24: 0x20000130, wr:24/24, rd:0/24
[00:00:00.011,000] <inf> main: ...............................................................
<<freed: 0x20000130, wr:24/24, rd:24/24
invalid claim 0: 0x20000190, wr:24/24, rd:24/24
>>claimed 0: 0, wr:24/24, rd:24/24
alloc 24 words, wr:24/24, rd:24/24
allocated 0x20000130, wr:0/24, rd:24/24
committed 0x20000130, wr:24/24, rd:24/24
>>claimed 24: 0x20000130, wr:24/24, rd:0/24
alloc 24 words, wr:24/24, rd:0/24
no space: Found busy packet 0x20000130 (len:24), wr:0/0, rd:0/24
no space: Found skip packet 8 len, wr:24/24, rd:24/24
no space: Found busy packet 0x20000130 (len:24), wr:0/0, rd:0/0
no space: Found skip packet 8 len, wr:24/24, rd:24/24
no space: Found busy packet 0x20000130 (len:24), wr:0/0, rd:0/0
no space: Found skip packet 8 len, wr:24/24, rd:24/24
no space: Found busy packet 0x20000130 (len:24), wr:0/0, rd:0/0
no space: Found skip packet 8 len, wr:24/24, rd:24/24
no space: Found busy packet 0x20000130 (len:24), wr:0/0, rd:0/0
no space: Found skip packet 8 len, wr:24/24, rd:24/24
no space: Found busy packet 0x20000130 (len:24), wr:0/0, rd:0/0
no space: Found skip packet 8 len, wr:24/24, rd:24/24
no space: Found busy packet 0x20000130 (len:24), wr:0/0, rd:0/0
no space: Found skip packet 8 len, wr:24/24, rd:24/24
no space: Found busy packet 0x20000130 (len:24), wr:0/0, rd:0/0
no space: Found skip packet 8 len, wr:24/24, rd:24/24
```
... and so on

The native_sim build, on the other hand, shows the following nice output:

```
*** Booting Zephyr OS build v4.0.0-3700-g09991d526a58 ***
alloc 24 words, wr:0/0, rd:0/0
allocated 0x8057450, wr:0/24, rd:0/0
committed 0x8057450, wr:24/24, rd:0/0
>>claimed 24: 0x8057450, wr:24/24, rd:0/24
[00:00:00.000,000] <inf> main: ...............................................................
<<freed: 0x8057450, wr:24/24, rd:24/24
invalid claim 0: 0x80574b0, wr:24/24, rd:24/24
>>claimed 0: (nil), wr:24/24, rd:24/24
alloc 24 words, wr:24/24, rd:24/24
allocated 0x8057450, wr:0/24, rd:24/24
committed 0x8057450, wr:24/24, rd:24/24
>>claimed 24: 0x8057450, wr:24/24, rd:0/24
[00:00:01.020,000] <inf> main: ...............................................................
<<freed: 0x8057450, wr:24/24, rd:24/24
alloc 24 words, wr:24/24, rd:24/24
allocated 0x8057450, wr:0/24, rd:24/24
committed 0x8057450, wr:24/24, rd:24/24
>>claimed 24: 0x8057450, wr:24/24, rd:0/24
[00:00:02.040,000] <inf> main: ...............................................................
<<freed: 0x8057450, wr:24/24, rd:24/24
alloc 24 words, wr:24/24, rd:24/24
allocated 0x8057450, wr:0/24, rd:24/24
committed 0x8057450, wr:24/24, rd:24/24
```
... and so on

### PR DESCRIPTION
**Pull request by nordic-krch**
It was possible that allocation was continuously attempting to find space. It could happen if allocation interrupted consuming a packet (which is marked as busy) and there is not enough space to allocate requested packet but there would be if busy packet was freed. Algorithm in that case was continuously going through the buffer in search for packets that can be dropped to find space for the new packet.

Fixes #84286.

### CODE REVIEW

**Comment by pdgendt** [comment]
Backports needed?

**Review by cfriedt — DISMISSED** [review]

File: lib/os/mpsc_pbuf.c [hunk 1]
```diff
@@ -201,10 +201,12 @@ static bool drop_item_locked(struct mpsc_pbuf_buffer *buffer,
 
 	uint32_t rd_wlen = buffer->get_wlen(item);
 
-	/* If packet is busy need to be ommited. */
+	/* If packet is busy need to be omitted. */
 	if (!is_valid(item)) {
 		return false;
 	} else if (item->hdr.busy) {
```
Comment (pdgendt) [inline lib/os/mpsc_pbuf.c:207]: No need for `else if` as the block ends with a `return`.

```suggestion
	}
	if (item->hdr.busy) {
```

File: lib/os/mpsc_pbuf.c [hunk 2]
```diff
@@ -215,15 +217,18 @@ static bool drop_item_locked(struct mpsc_pbuf_buffer *buffer,
...
 		if (buffer->rd_idx == buffer->tmp_rd_idx) {
 			buffer->tmp_rd_idx = idx_inc(buffer, buffer->tmp_rd_idx, rd_wlen);
+			ret = false;
 		}
 
 		buffer->tmp_wr_idx = buffer->tmp_rd_idx;
 		buffer->rd_idx = buffer->tmp_rd_idx;
 		buffer->flags |= MPSC_PBUF_FULL;
+		return ret;
 	} else {
```
Comment (pdgendt) [inline lib/os/mpsc_pbuf.c:232]: No need for the `else` now that the previous block has a `return`.

**Review by pdgendt — DISMISSED** [review]
We could gain some indented space, but not sure if this would backport nicely?

File: lib/os/mpsc_pbuf.c (hunk 1 above)
Comment (cfriedt) [reply lib/os/mpsc_pbuf.c:207]: I thought about commenting there as well, but it's not saving a level of indentation, so maybe that drive-by isn't totally needed 🤷🏼‍♂️

**Comment by kartben** [comment]
@nordic-krch so much for fixing typos, you now have a conflict and this needs rebasing, boohooh.

**Comment by nordic-krch** [comment]
:) rebased. @pdgendt @cfriedt can you re-approve?

**Review by pdgendt — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
