### PR TITLE
drivers: can: fix CAN frame priority inversion

### LINKED ISSUE #26541: Priority inversion in CAN
The drivers in the CAN subsystem suffer from priority inversion. This causes urgent frames to be delayed arbitrarily, and in the case of the FlexCAN drivers, to cause the CPU to spin for an arbitrary time.

I explain CAN priority inversion in a blog post here:

https://kentindell.github.io/2020/06/29/can-priority-inversion/

The solution to this is to rewrite the CAN drivers. Some software may rely on FIFO processing (e.g. for segmented messages) and a separate API for sending frames according to FIFO will probably be necessary. The blog post discusses this in more detail.

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Fix the CAN drivers to not transmit frames in FIFO/chronological order but rather respect the priority specified by the CAN ID of the frame.

For now, this change has been verified for the following drivers:
- NXP FlexCAN (`twr_ke18f`, `mimxrt1024_evk`).
- Bosch M_CAN (`lpcxpresso55s16`).
- STM32 bxCAN (`stm32f3_disco`).
- Microchip MPC2515

Drivers yet to be fixed:
- Renesas R-Car CAN (I do not have access to the hardware for testing).

The driver changes require changes to some of the higher level in-tree CAN protocols with respect to segmented messages:
- ISO-TP (verified using `tests/subsys/canbus/isotp/implementation`, `tests/subsys/canbus/isotp/conformance`, and `samples/subsys/canbus/isotp` between two boards).
- 6LoCAN (will likely need something along the changes to ISO-TP, but I am unable to test it since #42559)

The following higher level CAN protocols already handle segmented messages correctly:
- CANopenNode (verified using `samples/modules/canopennode`).

Fixes: #26541

The next logical step is to add a CAN frame software priority queue for use in drivers with a limited amount of TX MBs (such as the MCP2515 after the changes in this PR). I am working on that.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
@kentindell FYI

File: subsys/canbus/isotp/isotp.c [hunk 1]
```diff
@@ -1068,6 +1070,9 @@ static void send_state_machine(struct isotp_send_ctx *ctx)
 				ctx->state = ISOTP_TX_WAIT_ST;
 				break;
 			}
+
+			/* Ensure FIFO style transmission of CF */
+			k_sem_take(&ctx->tx_sem, K_FOREVER);
```
Comment (martinjaeger) [inline subsys/canbus/isotp/isotp.c:1075]: I think this should go before the `send_cf` or into the `ISOTP_TX_SEND_FF` state as the first frame is considered the frame with sequence number 0. No CF should be sent before FF.

File: subsys/canbus/isotp/isotp.c [hunk 2]
```diff
@@ -784,6 +785,7 @@ static void send_process_fc(struct isotp_send_ctx *ctx,
 		ctx->state = ISOTP_TX_SEND_CF;
 		ctx->wft = 0;
 		ctx->tx_backlog = 0;
+		k_sem_reset(&ctx->tx_sem);
```
Comment (martinjaeger) [inline subsys/canbus/isotp/isotp.c:788]: Why is the semaphore reset here? I don't think it should be necessary.

**Review by martinjaeger — CHANGES_REQUESTED** [review]
Thanks for pushing forward this long-standing topic!

File: include/drivers/can.h [hunk 3]
```diff
@@ -597,10 +597,20 @@ static inline int can_set_bitrate(const struct device *dev,
...
- * Transmit a CAN frame on the CAN bus with optional timeout and completion
- * callback function.
+ * Queue a CAN frame for transmission on the CAN bus with optional timeout and
+ * completion callback function.
+ *
+ * Queued CAN frames are transmitted in order according to the their CAN-ID. The
+ * lower the CAN-ID, the higher the priority. Data frames have higher priority
+ * than Remote Transmission Request (RTR) frames with identical
+ * CAN-IDs. Transmission order for queued frames with the same priority is
+ * hardware dependent.
```
[the remark this answers is not in the document]
Comment (henrikbrixandersen) [reply include/drivers/can.h]: Good idea, added.

File: subsys/canbus/isotp/isotp.c (hunk 1 above)
Comment (henrikbrixandersen) [reply subsys/canbus/isotp/isotp.c:1075]: This is handled by the ISO-TP state machine. Once the first frame (FF) is queued, it will enter state `ISOTP_TX_WAIT_FC` and wait for the receiver to acknowledge (by sending a flow control frame (FC)) before sending the first continuation frame (CF).

Comment (martinjaeger) [reply subsys/canbus/isotp/isotp.c:1075]: Indeed, you are correct.

File: subsys/canbus/isotp/isotp.c (hunk 2 above)
Comment (martinjaeger) [reply subsys/canbus/isotp/isotp.c:788]: Ok, makes sense for aborted transfer, thanks for the explanation.

**Review by martinjaeger — APPROVED** [review]

**Review by karstenkoenig — APPROVED** [review]
Thanks for tackling this!

**Comment by karstenkoenig** [comment]
I appreciate that you want to add the software priority queue for mcp2515. Are you planning on aborting the frame sitting in the tx mailbox if a higher priority frame is getting added to the queue and wouldn't that risk double transmission if the abort is timed poorly?

**Comment by alexanderwachter** [comment]
Thanks a lot @henrikbrixandersen!
Still, the priority inversion is there (however, reduced risk).
Let's take the MCP2515 as an example: You send a low prior frame and hence occupy the mailbox.
The bus is busy and the frame does not go out.
You cannot send any other frame since abortion is not possible -> priority inversion.

If I find some time, I'll try to work on the tx context-based sending again.

**Review by alexanderwachter — APPROVED** [review]

File: include/drivers/can.h [hunk 4]
```diff
@@ -597,10 +597,24 @@ static inline int can_set_bitrate(const struct device *dev,
  */
 
 /**
- * @brief Transmit a CAN frame on the CAN bus
- *
- * Transmit a CAN frame on the CAN bus with optional timeout and completion
- * callback function.
+ * @brief Queue a CAN frame for transmission on the CAN bus
+ *
+ * Queue a CAN frame for transmission on the CAN bus with optional timeout and
```
[the remark this answers is not in the document]
Comment (henrikbrixandersen) [reply include/drivers/can.h:602]: I don't think it needs to mentioned explicitly, since it is already implicit in the timeout for waiting for a free TX MB.

**Comment by henrikbrixandersen** [comment]
> I appreciate that you want to add the software priority queue for mcp2515. Are you planning on aborting the frame sitting in the tx mailbox if a higher priority frame is getting added to the queue and wouldn't that risk double transmission if the abort is timed poorly?

@karstenkoenig Exactly. The SW priority queue will need to be able to abort the lowest priority frame in the TX MBs (or in case of the MCP2515, the only TX MB) in order to make room for a higher priority frame. The CAN controller normally disallows abortion of a TX MB which is in transmission - but will refrain from retransmitting it, should the transmission fail due to lost arbitration, missing ACK etc, so if carefully written, no race/double transmission should be possible.

**Comment by henrikbrixandersen** [comment]
> Thanks a lot @henrikbrixandersen! Still, the priority inversion is there (however, reduced risk). Let's take the MCP2515 as an example: You send a low prior frame and hence occupy the mailbox. The bus is busy and the frame does not go out. You cannot send any other frame since abortion is not possible -> priority inversion.

Which is why this PR also mentions the next needed step (also outlined by @kentindell): a software priority queue with the same priority arbitration as the CAN controller/bus itself.

**Comment by kentindell** [comment]
> > I appreciate that you want to add the software priority queue for mcp2515. Are you planning on aborting the frame sitting in the tx mailbox if a higher priority frame is getting added to the queue and wouldn't that risk double transmission if the abort is timed poorly?
> 
> @karstenkoenig Exactly. The SW priority queue will need to be able to abort the lowest priority frame in the TX MBs (or in case of the MCP2515, the only TX MB) in order to make room for a higher priority frame. The CAN controller normally disallows abortion of a TX MB which is in transmission - but will refrain from retransmitting it, should the transmission fail due to lost arbitration, missing ACK etc, so if carefully written, no race/double transmission should be possible.

Exactly. The abort request is resolved either to "frame sent" or "abort succeeded" so the driver knows what to do (in general the cleanest way to write the drivers is to use a "buffer empty" ISR where abort or success always results in an empty buffer).

The MCP2515 is an awkward device: I spoke to Microchip about this when it was being designed many years ago and emphasised the need for three transmit buffers. Unfortunately, some architectural design decisions were made that makes things awkward for performance. Because the transmit buffers are not arbitrated by priority (i.e. CAN ID) it means that in the time the drivers take to respond to a transmit or abort IRQ a lower priority frame from elsewhere can win arbitration, which means that on a busy bus a low priority frame can get in between every frame sent via the MCP2515, which ruins real-time performance. But this is the best that can be done with this architecture.
