### PR TITLE
samples: net: mdns_responder: fix coverity issues

### LINKED ISSUE #33093: [Coverity CID :215391] Unchecked return value from library in samples/net/mdns_responder/src/service.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/samples/net/mdns_responder/src/service.c

Category: Error handling issues
Function: `welcome`
Component: Samples
CID: [215391](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=215391)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/samples/net/mdns_responder/src/service.c#L26

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #33094: [Coverity CID :215381] Resource leak in samples/net/mdns_responder/src/service.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/samples/net/mdns_responder/src/service.c

Category: Resource leaks
Function: `service`
Component: Samples
CID: [215381](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=215381)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/samples/net/mdns_responder/src/service.c

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by gudnimg**
* Fix #33093 [Coverity CID :215391] Unchecked return value from library in `samples/net/mdns_responder/src/service.c`
* Fix #33094 [Coverity CID :215381] Resource leak in `samples/net/mdns_responder/src/service.c`

### CODE REVIEW

File: samples/net/mdns_responder/src/service.c [hunk 1]
```diff
@@ -19,11 +19,19 @@ LOG_MODULE_REGISTER(mdns_echo_service, LOG_LEVEL_DBG);
...
+static int welcome(int fd)
 {
 	static const char msg[] = "Bonjour, Zephyr world!\n";
 
-	send(fd, msg, sizeof(msg), 0);
+	int r = send(fd, msg, sizeof(msg), 0);
+
+	if (r == -1) {
+		NET_DBG("send() failed (%d)", errno);
+		close(fd);
```
Comment (jukkar) [inline samples/net/mdns_responder/src/service.c:30]: This certainly works, but it would look uniform if the `close()` is done in `service()` so same way as other functions return -1 and then we call close.

File: samples/net/mdns_responder/src/service.c [hunk 2]
```diff
@@ -19,11 +19,19 @@ LOG_MODULE_REGISTER(mdns_echo_service, LOG_LEVEL_DBG);
 /* A default port of 0 causes bind(2) to request an ephemeral port */
```
Comment (jukkar) [inline samples/net/mdns_responder/src/service.c:19]: Commit subject of `samples: net: mdns_responder: Fix coverity issue` is ok, but please change the commit message, so something like this:
```
Check return value if sendto() fails.

Coverity-CID: 215391
Fixes #33093

Signed-off-by: ....
```

File: samples/net/mdns_responder/src/service.c [hunk 3]
```diff
@@ -66,7 +66,7 @@ void service(void)
 #else
 	/* The simple use case: fixed port */
 	DNS_SD_REGISTER_TCP_SERVICE(zephyr, CONFIG_NET_HOSTNAME,
-				    "_zephyr", "local", DNS_SD_EMPTY_TXT, DEFAULT_PORT);
+					"_zephyr", "local", DNS_SD_EMPTY_TXT, DEFAULT_PORT);
```
Comment (jukkar) [inline samples/net/mdns_responder/src/service.c:69]: This looks like unrelated change and the line is properly indented already, please remove it.

File: samples/net/mdns_responder/src/service.c [hunk 4]
```diff
@@ -66,7 +66,7 @@ void service(void)
 #else
```
Comment (jukkar) [inline samples/net/mdns_responder/src/service.c:66]: In commit `samples: net: mdns_responder: Fix coverity resource leak issue`
Same comment about commit message, please change to
```
Avoid resource leak by closing socket when there is an error.

Coverity-CID: 215381
Fixes #33094 

Signed-of-by: ...
```

**Review by jukkar — CHANGES_REQUESTED** [review]

File: samples/net/mdns_responder/src/service.c (hunk 3 above)
Comment (GunZi200) [reply samples/net/mdns_responder/src/service.c:69]: I had to convert spaces to tabs to fix indentation issues from my changes, it affected the entire file. I will revert this change.

File: samples/net/mdns_responder/src/service.c (hunk 4 above)
Comment (GunZi200) [reply samples/net/mdns_responder/src/service.c:66]: Fixed

File: samples/net/mdns_responder/src/service.c (hunk 2 above)
Comment (GunZi200) [reply samples/net/mdns_responder/src/service.c:19]: Fixed

File: samples/net/mdns_responder/src/service.c (hunk 1 above)
Comment (GunZi200) [reply samples/net/mdns_responder/src/service.c:30]: I 100% agree with you. Good idea!

File: samples/net/mdns_responder/src/service.c (hunk 3 above)
Comment (GunZi200) [reply samples/net/mdns_responder/src/service.c]: Fixed

File: samples/net/mdns_responder/src/service.c [hunk 5]
```diff
@@ -121,7 +121,12 @@ void service(void)
 			log_strdup(addrstr), ntohs(*portp));
 
 		/* send a banner */
-		welcome(client_fd);
+		r = welcome(client_fd);
+		if (r == -1) {
+			NET_DBG("send() failed (%d)", errno);
```
Comment (pfalcon) [inline samples/net/mdns_responder/src/service.c:128]: I'd say this should be NET_ERR().

Comment (GunZi200) [reply samples/net/mdns_responder/src/service.c:128]: @pfalcon Should I also add `NET_ERR()` when `bind()`, `listen()` and `socket()` fail?

Comment (GunZi200) [reply samples/net/mdns_responder/src/service.c:128]: Yeah I used `NET_DBG()` since it's used everywhere else. The main focus is to fix the coverity issue where the return value was not checked. I could add a separate commit to change `NET_DBG()` to `NET_ERR()` on top of the current changes.

@jukkar @tbursztyka what are your thoughts on the matter?

Comment (pfalcon) [reply samples/net/mdns_responder/src/service.c:128]: > The main focus is to fix the coverity issue

Right, I remember that, and why I say I don't want to introduce more scope creep into that. LGTM.

**Review by pfalcon — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
Thanks for the fixes!
