### PR TITLE
Bluetooth: Controller: Fix addr type in PA sync established event

### LINKED ISSUE #53720: Bluetooth: Controller: Incorrect address type for PA sync established
**Describe the bug**
The address type of the `bt_hci_evt_le_per_adv_sync_established` is incorrect set to 0x01 (`BT_ADDR_LE_RANDOM`) when the address is a resolved one, where it should have been `BT_ADDR_LE_RANDOM_ID`. It's possible that the same issue exists for the public address. 

**To Reproduce**
1. Build and run the `per_adv_conn_privacy.sh` test implemented by https://github.com/zephyrproject-rtos/zephyr/pull/53717
2. See that the address type of the event in `bt_hci_le_per_adv_sync_established` is not `BT_ADDR_LE_RANDOM_ID` even though the address is the resolved on. 

**Expected behavior**
Expected the address type of `bt_hci_evt_le_per_adv_sync_established` to be `BT_ADDR_LE_RANDOM_ID`

**Impact**
Minor as we don't expose `BT_ADDR_LE_RANDOM_ID` to the application layer

**Logs and console output**
```
d_01: @00:00:00.008408  [00:00:00.008,392] <inf> bt_hci_core: bt_dev_show_info: Identity: C0:68:C6:62:A9:8E (random)
d_01: @00:00:00.008408  [00:00:00.008,392] <inf> bt_hci_core: bt_dev_show_info: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x05f1
d_01: @00:00:00.008408  [00:00:00.008,392] <inf> bt_hci_core: bt_dev_show_info: LMP: version 5.3 (0x0c) subver 0xffff
d_00: @00:00:00.008408  [00:00:00.008,392] <inf> bt_hci_core: bt_dev_show_info: Identity: F0:06:A0:D2:FD:B9 (random)
d_00: @00:00:00.008408  [00:00:00.008,392] <inf> bt_hci_core: bt_dev_show_info: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x05f1
d_00: @00:00:00.008408  [00:00:00.008,392] <inf> bt_hci_core: bt_dev_show_info: LMP: version 5.3 (0x0c) subver 0xffff
d_00: @00:00:00.008408  Bluetooth initialized
d_01: @00:00:00.008778  Start scanning...done.
d_00: @00:00:00.009248  Creating connectable extended advertising set...done.
d_00: @00:00:00.009248  Starting Extended Advertising...done.
d_01: @00:00:00.013064  Waiting for connection...
[00:00:00.013,061] <err> bt_scan: le_adv_recv: addr 7C:24:21:7C:24:21 (random)
d_01: @00:00:00.013064  Stopping scan
d_01: @00:00:00.123644  Connected to 7C:24:21:7C:24:21 (random)
d_00: @00:00:00.123645  Connected to 5A:7B:27:5A:7B:27 (random)
d_01: @00:00:00.139710  done.
d_01: @00:00:00.140918  Setting security...done.
d_01: @00:00:00.878174  Waiting for bonding...done.
d_01: @00:00:00.878194  Start scanning...done.
d_01: @00:00:00.878194  Waiting for periodic advertising...
d_00: @00:00:00.878184  Creating extended advertising set...done.
d_00: @00:00:00.878662  Setting periodic advertising parameters...done.
d_00: @00:00:00.878662  Starting periodic advertising...done.
d_00: @00:00:00.879142  Starting Extended Advertising...done.
d_01: @00:00:01.323017  [00:00:01.322,998] <err> bt_scan: le_adv_recv: addr F0:06:A0:D2:FD:B9 (random-id)
d_01: @00:00:01.337220  Found periodic advertising.
d_01: @00:00:01.337220  Creating periodic advertising sync...done.
d_01: @00:00:01.337220  Waiting for periodic sync...
d_01: @00:00:01.653016  [00:00:01.653,015] <err> bt_scan: le_adv_recv: addr F0:06:A0:D2:FD:B9 (random-id)
d_01: @00:00:02.083854  [00:00:02.083,831] <err> bt_scan: bt_hci_le_per_adv_sync_established: addr F0:06:A0:D2:FD:B9 (random)
d_01: @00:00:02.083854  PER_ADV_SYNC[0]: [DEVICE]: F0:06:A0:D2:FD:B9 (random) synced, Interval 0x03c0 (1200000 us)
d_01: @00:00:02.095643  Periodic sync established.
d_01: @00:00:02.095643  Waiting for periodic sync lost...
d_00: @00:00:10.867402  Stopping Periodic Advertising...done.
d_00: @00:00:10.867402  Stopping Extended Advertising...done.
d_00: @00:00:10.867402  Stopping Extended Advertising...done.
d_00: @00:00:10.867402  Delete extended advertising set...done.
d_00: @00:00:10.867402  Delete extended advertising set...done.
d_00: @00:00:10.867402 INFO: PASSED: Periodic advertiser passed
d_01: @00:00:11.684010  PER_ADV_SYNC[0]: [DEVICE]: F0:06:A0:D2:FD:B9 (random) sync terminated
d_01: @00:00:11.695679 INFO: PASSED: Periodic advertising syncer passed
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: 871d6d26eeb05f4cdbc1152f1c682968088e883e

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by cvinayak**
The address type in the periodic adveritising sync established event is incorrectly set to 0x01
(BT_ADDR_LE_RANDOM) when the address is a resolved one, where it should have been BT_ADDR_LE_RANDOM_ID.

The address type has been fixed by offsetting by 2 to get BT_ADDR_LE_PUBLIC_ID or BT_ADDR_LE_RANDOM_ID when the address has been resolved.

Fixes #53720.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by Thalley** [comment]
Confirmed to work

File: subsys/bluetooth/controller/ll_sw/ull_sync.c [hunk 1]
```diff
@@ -698,7 +704,7 @@ void ull_sync_setup(struct ll_scan_set *scan, struct ll_scan_aux_set *aux,
 	/* Remember the peer address.
 	 * NOTE: Peer identity address is copied here when privacy is enable.
 	 */
-	sync->peer_id_addr_type = scan->periodic.adv_addr_type;
+	sync->peer_id_addr_type = scan->periodic.adv_addr_type & 0x01;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_sync.c:707]: In the host we are doing this translation by
```c
dst->type &= ~ADDR_RESOLVED_BITMASK;
```

Perhaps at some point we should add and use a common macro/function to translate the type. 

Ditto for marking it as resolved

**Review by Thalley — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
