### PR TITLE
drivers: gpio: emul: replace mutex with spinlock

### LINKED ISSUE #53964: gpio_emul: gpio_* functions not callable within an ISR
**Describe the bug**
The gpio_emul driver uses a mutex to protect the internal data.
Locking on a mutex is not allowed within an ISR.
If a user wants to check for example a pin state within an ISR, which is a common use-case, the program halts on an assert.

**To Reproduce**
call any gpio function, where the gpio controller is an emul, from an ISR

**Expected behavior**
The gpio_emul should behave like the other GPIO drivers, which are callable from an ISR

**Impact**
Makes testing hard if you have the situation where you trigger on both edges of a pin and the state of the pin is or relevance.
In such a case, one might want to call gpio_pin_get within the isr_callback

Fixed by #53480

### PR DESCRIPTION
**Pull request by alexanderwachter**
Replace all mutex with spinlocks to make the driver usable from ISRs.

Fixes #53964

### CODE REVIEW

**Comment by alexanderwachter** [comment]
@cfriedt second try :-)

**Comment by henrikbrixandersen** [comment]
How will switching from a mutex to a spinlock "make the driver usable from ISRs"? If application level code holds the spinlock and an ISR attempts to acquire it, the ISR will spin forever?

**Comment by alexanderwachter** [comment]
> How will switching from a mutex to a spinlock "make the driver usable from ISRs"? If application level code holds the spinlock and an ISR attempts to acquire it, the ISR will spin forever?

How can an ISR execute if the spinlock is locked?
Do you think there is an issue with multicore?
I'm only using it in native posix, where the current solution is unusable, because our app reads the state of an input within the ISR.

File: drivers/gpio/gpio_emul.c [hunk 1]
```diff
@@ -406,41 +418,38 @@ static int gpio_emul_pin_configure(const struct device *port, gpio_pin_t pin,
 		return -EINVAL;
 	}
 
-	k_mutex_lock(&drv_data->mu, K_FOREVER);
+	key = k_spin_lock(&drv_data->lock);
```
Comment (cfriedt) [inline drivers/gpio/gpio_emul.c:421]: Can you do a second pass and adjust the API doc to use `lock` instead of `mu`?

File: drivers/gpio/gpio_emul.c [hunk 2]
```diff
@@ -617,11 +650,12 @@ static int gpio_emul_pin_interrupt_configure(const struct device *port, gpio_pin
 					    enum gpio_int_mode mode,
 					    enum gpio_int_trig trig)
 {
-	int ret;
 	struct gpio_emul_data *drv_data =
 		(struct gpio_emul_data *)port->data;
 	const struct gpio_emul_config *config =
 		(const struct gpio_emul_config *)port->config;
+	k_spinlock_key_t key;
+	int ret;
```
Comment (cfriedt) [inline drivers/gpio/gpio_emul.c:658]: I would suggest not moving this just to minimize changes.

**Review by cfriedt — CHANGES_REQUESTED** [review]
Looks OK to me. I was actually not really sure if this would be possible, but I'm impressed. Just some minor changes requested to remove unnecessary changes / update docs.

I would like to take another look at the second draft as well and see if I can break it.

File: drivers/gpio/gpio_emul.c (hunk 1 above)
Comment (alexanderwachter) [reply drivers/gpio/gpio_emul.c:422]: You men the internal documentation of the data struct?

Comment (cfriedt) [reply drivers/gpio/gpio_emul.c:422]: Yeah, just for consistence

**Review by cfriedt — DISMISSED** [review]

File: drivers/gpio/gpio_emul.c [hunk 3]
```diff
@@ -90,8 +90,8 @@ struct gpio_emul_data {
 	gpio_port_value_t output_vals;
 	/** Interrupt status for each pin */
 	gpio_port_pins_t interrupts;
-	/** Mutex to synchronize accesses to driver data and config */
-	struct k_mutex mu;
+	/** Spinlock to synchronize accesses to driver data and config */
```
Comment (cfriedt) [inline drivers/gpio/gpio_emul.c:93]: Just a couple of lines above here, can you change `@a mu` to `@a lock`?

Comment (cfriedt) [reply drivers/gpio/gpio_emul.c:93]: Sorry - missed that prior to my approval

Comment (alexanderwachter) [reply drivers/gpio/gpio_emul.c:93]: Found some more mu...
Sorry, I'm really bad when it comes to documentation.

**Comment by alexanderwachter** [comment]
> 

@cfriedt not that I'm aware of. At least not from me.
Agree, it is a bug. The API must return -EWOULDBLOCK.

**Comment by cfriedt** [comment]
> @cfriedt not that I'm aware of. At least not from me.

Oh, I meant not being able to use gpio_emul in IRQ contexts is a bug actually, so this PR is itself a Bugfix.

Can you also please create an issue and link it here?

> Agree, it is a bug. The API must return -EWOULDBLOCK.

Right, I think I see what you mean.

Actually, that is part of a larger issue that we have in Zephyr. Very few Zephyr system calls have an associated timeout (including GPIO).

So there is no clean way at the moment to fail with an error if a such an operation would block.

However, one could also argue, much like accessing any kind of data structure, synchronizing control of a GPIO is entirely application dependent and is not needed by the large majority of GPIO users. Forcing GPIO to also incur a mute  lock overhead would add an unnecessary overhead to the general use case.

What you've identified is out of the scope of this PR, so I wouldn't worry about it here.

For the time being, the implicit assumption is that GPIO operations are quick and they never fail.

**Review by cfriedt — APPROVED** [review]

**Comment by alexanderwachter** [comment]
@cfriedt ready for merging?
I think this should go in 3.3.0

**Comment by cfriedt** [comment]
@alexanderwachter - yes, but I'll let @stephanosio or @laurenmurphyx64 do it once there is another review

**Comment by alexanderwachter** [comment]
@mnkp any input?

**Comment by cfriedt** [comment]
@henrikbrixandersen - will you ack?

**Comment by teburd** [comment]
Is the GPIO interface labeled as ISR safe? This is kind of a confusing change to be honest.

**Review by andyross — APPROVED** [review]
All looks reasonable to me.  Note that the "release the lock around the callback" pattern opens races if other contexts want to modify the data used by the callback while it's running.  That's arguably user error, but might be worth documenting.

**Review by carlescufi — APPROVED** [review]
