### PR TITLE
Bluetooth: tester: Fix 3 GAP qualification tests

### LINKED ISSUE #22927: PTS: Test Framework: Bluetooth:  SM/MAS/SIP/BV-02-C-INCONCLUSIV
Describe the bug
Zephyr set IO capability to KeyboardOnly instead of KeyboardDisplay

To Reproduce
run auto-pts

Expected behavior    
IO capability needs to be set to KeyboardDisplay

[SM_MAS_SIP_BV-02-C-INCONCLUSIV.zip](https://github.com/zephyrproject-rtos/zephyr/files/4223855/SM_MAS_SIP_BV-02-C-INCONCLUSIV.zip)

### LINKED ISSUE #22929: PTS: Test Framework :Bluetooth: SM/SLA/SIP/BV-01-C Error
Describe the bug
MITM bit in Pairing Request cannot be set to cleared. Zephyr aplication doesn't support set BTP MITM off command.

To Reproduce
run auto-pts

[SM_SLA_SIP_BV-01-C-FAIL.zip](https://github.com/zephyrproject-rtos/zephyr/files/4223970/SM_SLA_SIP_BV-01-C-FAIL.zip)

### LINKED ISSUE #22930: PTS: Test Framework :Bluetooth: SM/MAS/PKE/BV-01-C INCONCLUSIV
Describe the bug

Bonding flag in Pairing Request cannot be set to cleared. Zephyr aplication doesn't support set BTP bondable off command.

To Reproduce
run auto-pts

[SM_MAS_PKE_BV-01-C-INCONC.zip](https://github.com/zephyrproject-rtos/zephyr/files/4224043/SM_MAS_PKE_BV-01-C-INCONC.zip)

### PR DESCRIPTION
**Pull request by carlescufi**
Fix the following 3 failing tests:

- SM/SLA/SIP/BV-01-C
- SM/MAS/SIP/BV-02-C
- SM/MAS/PKE/BV-01-C

Fixes #22929.
Fixes #22927.
Fixes #22930.

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]
Nice work!

File: tests/bluetooth/tester/src/gap.c [hunk 1]
```diff
@@ -720,9 +795,19 @@ static void conn_param_update(const u8_t *data, u16_t len)
 		   status);
 }
 
+static void set_mitm(const u8_t *data, u16_t len)
+{
+	LOG_WRN("Use CONFIG_BT_SMP_ENFORCE_MITM instead");
```
Comment (joerchan) [inline tests/bluetooth/tester/src/gap.c]: With this option we can set the MITM bit based on the security level, maybe we should switch the security level we call 'bt_conn_set_security' with based on this command?

At the moment we always call with `BT_SECURITY_L2`, we could switch to `BT_SECURITY_L3` when mitm is requisted by the test.

**Review by joerchan — CHANGES_REQUESTED** [review]
Great, 3 for 1 deal.

The SET_MITM command should control the security level in `pair` I think.

File: tests/bluetooth/tester/src/gap.c (hunk 1 above)
Comment (carlescufi) [reply tests/bluetooth/tester/src/gap.c]: That's a good idea,  but I wonder if this would have unexpected consequences elsewhere in other tests? not sure, just thinking out loud

Comment (joerchan) [reply tests/bluetooth/tester/src/gap.c]: This is a new command, so if the default is L2, and using this command would change it to L3 then there shouldn't be any issues with the tests. If anything then`CONFIG_BT_SMP_ENFORCE_MITM=n` is the change I would question if had unexpected consequences for the tests.

**Review by joerchan — APPROVED** [review]

**Comment by joerchan** [comment]
Downgraded my comment to a suggestion instead.
