### PR TITLE
shell: telnet: Fix CTRL-C handling

### LINKED ISSUE #39985: Telnet shell breaks upon sending Ctrl+C character
**Describe the bug**
The `shell_module` sample application is modified to host a telnet shell and loaded to a board with an ethernet connection, a linux machine connects to the board using the standard `telnet` command, at this point, basic shell usage works. Ctrl+C is used on the telnet session, at which point the telnet session is essentially dead and the remote device fails to continue working with the current telnet session, the telnet session must be closed and re-opened for it to resume working

**To Reproduce**
Shell application with telnet shell interface, connect, send Ctrl+C character, try to continue using shell

**Expected behavior**
The shell to continue working

**Impact**
Annoyance

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.13.1
 - Commit SHA or Version used: 351d065f63c04b3431b10a2485a122e2de713749

### PR DESCRIPTION
**Pull request by rlubos**
A few fixes for the issues spotted when investigating CTRL-C handling:
* Fix command processing, currently only the first command in the packet has been processed,
* Disable echo on shell - on ECHO command we reply that we won't echo characters, so the implementation should conform,
* Enable command handling in the sample by default - the client behaves considerably better when he receives responses for the commands it sends, i. e. it doesn't lock on the unresponded `DO TIMING MARK` command.

Fixes #39985

### CODE REVIEW

File: subsys/shell/backends/shell_telnet.c [hunk 1]
```diff
@@ -166,15 +166,25 @@ static inline bool telnet_handle_command(struct net_pkt *pkt)
...
 
-	return true;
+	if (cmd->op == NVT_CMD_SB) {
+		/* TODO Add subnegotiation support. */
+		return -EOPNOTSUPP;
+	}
+
+	if (cmd->op == NVT_CMD_WILL || cmd->op == NVT_CMD_WONT ||
+	    cmd->op == NVT_CMD_DO || cmd->op == NVT_CMD_DONT) {
+		return 3;
```
Comment (jakub-uC) [inline subsys/shell/backends/shell_telnet.c:184]: Is it possible to replace these magic numbers (for me) with some defined error codes?

Comment (rlubos) [reply subsys/shell/backends/shell_telnet.c]: I've replaced the numbers with appropriate symbols.

**Review by jakub-uC — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]
