### PR TITLE
usb: fix for parallel transfer deadlock with usb_transfer_sync() 

### LINKED ISSUE #30736: Deadlock with usb_transfer_sync()
Calling usb_transfer_sync() from multiple thread with same endpoint address can cause deadlock.

Example code to reproduce can found from wpanusb sample where same end point is used from tx and rx context. USB_MAX_NUMBER_TRANSFERS shall be greater than 1 (default 4). Race condition is hard to get in practice and I don't have test code to reproduce the issue.

Based on debugging and code review issue seems to be with usb_ep_get_transfer() function implementation when called from usb_transfer_ep_callback().

```c
static struct usb_transfer_data *usb_ep_get_transfer(uint8_t ep)
{
	for (int i = 0; i < ARRAY_SIZE(ut_data); i++) {
		if (ut_data[i].ep == ep) {
			return &ut_data[i];
		}
	}
	return NULL;
}
```

This function always returns first transfer with endpoint address and doesn't care the transfer status. When there is 2 or more transfers with same endpoint address, this might return completed transfer and the ongoing transfer is not handled. This will lead to situation when transfer completion callback is never called to release caller semaphore.

An easy fix is just to return first ongoing transfer for endpoint callback.
```c
static struct usb_transfer_data *usb_ep_get_transfer(uint8_t ep)
{
	for (int i = 0; i < ARRAY_SIZE(ut_data); i++) {
		if (ut_data[i].ep == ep && ut_data[i].status != 0) {
			return &ut_data[i];
		}
	}
	return NULL;
}
```
If this is a valid fix to above issue, I can make a pull request for the change.

### PR DESCRIPTION
**Pull request by ktolonen**
Transfer status was not checked when accessing to transfer from endpoint callback. Adding status check, to prevent double complete. Double complete will cause deadlock when ongoing transfer complete callback is not called.

Fixes #30736

### CODE REVIEW

File: subsys/usb/usb_transfer.c [hunk 1]
```diff
@@ -49,7 +49,7 @@ static struct usb_transfer_data ut_data[CONFIG_USB_MAX_NUM_TRANSFERS];
 static struct usb_transfer_data *usb_ep_get_transfer(uint8_t ep)
 {
 	for (int i = 0; i < ARRAY_SIZE(ut_data); i++) {
-		if (ut_data[i].ep == ep) {
+		if (ut_data[i].ep == ep && ut_data[i].status != 0) {
```
Comment (jfischer-no) [inline subsys/usb/usb_transfer.c:52]: The whole thing around the transfer system is not designed to handle more than one transfer for specific endpoint. If an endpoint is used by two different contexts, then it should be checked with `usb_transfer_is_busy()`  before. I see API docu does not describe it. IMO, your change does not fix that and helps only if the transfers are not larger than endpoint MPS. I do not see any disadvantages of the patch yet, but commit message should be changed. I will block it for now.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: subsys/usb/usb_transfer.c (hunk 1 above)
Comment (ktolonen) [reply subsys/usb/usb_transfer.c:52]: I see... maybe this check could be in `usb_transfer_sync()` to prevent starting of parallel transfers to the same endpoint. Caller can implement the waiting logic based on `usb_transfer_is_busy()`, but if is it not done, the deadlock is hard to find without explicit error message. If API is changed then `samples/net/wpanusb/src/wpanusb.c` shall be updated accordingly since it does parallel transfers to same endpoint.

Comment (ktolonen) [reply subsys/usb/usb_transfer.c:52]: Updated commit with a check to prevent starting of the parallel transfers on same endpoint.

**Review by jfischer-no — APPROVED** [review]

**Review by nashif — APPROVED** [review]
