### PR TITLE
tests: drivers: counter: fix skip test check

### LINKED ISSUE #74358: tests/drivers/counter/counter_basic_api skips instances that are able to run the tests
**Describe the bug**
When running `tests/drivers/counter/counter_basic_api` with multiple counter instances that support different capabilities, if one of the instances does not support the test required capabilities, the test will be immediately skipped not giving the chance to run to the subsequent instances.

E.g. `tests/drivers/counter/counter_basic_api/boards/s32z2xxdc2_s32z270_rtu0.overlay` tests with 4 STM instances (support alarm APIs only) and 1 PIT instance (support top callback API only). Since PIT instance runs first, the rest of the STM instances are not tested:
```
Running TESTSUITE counter_basic
===================================================================
START - test_all_channels
Skipped for pit0_channel@0
 SKIP - test_all_channels in 0.003 seconds
===================================================================
```

This bug was introduced by e2656a24a9f. By reverting it:
```
Running TESTSUITE counter_basic
===================================================================
START - test_all_channels
Skipped for pit0_channel@0
Testing stm@76200000
Testing stm@76210000
Testing stm@76020000
Testing stm@76030000
 PASS - test_all_channels in 0.636 seconds
===================================================================
```

**To Reproduce**
```
west build -b s32z2xxdc2@D/s32z270/rtu0 tests/drivers/counter/counter_basic_api/ -p -t flash
```

**Expected behavior**
The test is marked as SKIP only if it all counter instances under test were skipped.

**Impact**
Potentially not running counter tests in multiple platforms.

**Logs and console output**
See above

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used 66630961627f4d8625e2dbe1cb7afe4abd690b2e

**Additional context**
NA

### PR DESCRIPTION
**Pull request by manuargue**
When running this test with multiple counter instances that support different capabilities, if one of the instances does not support the test required capabilities, the test will be immediately skipped not giving the chance to run to the subsequent instances.
Fix this by marking the test as skipped, only of all counter instances under test were skipped.

Fixes #74358

All instances skipped:
```
Running TESTSUITE counter_basic
===================================================================
START - test_all_channels
Skipped for pit0_channel@0
Skipped for pit0_channel@1
 SKIP - test_all_channels in 0.207 seconds
===================================================================
```

Some instances skipped, others executed:
```
===================================================================
START - test_all_channels
Skipped for pit0_channel@0
Testing stm@76200000
Testing stm@76210000
Testing stm@76020000
Testing stm@76030000
 PASS - test_all_channels in 0.636 seconds
===================================================================
```

### CODE REVIEW

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 1]
```diff
@@ -190,12 +192,15 @@ static void test_all_instances(counter_test_func_t func,
 			func(devices[i]);
 		} else {
 			TC_PRINT("Skipped for %s\n", devices[i]->name);
-			ztest_test_skip();
+			devices_skipped++;
 		}
```
Comment (RichardSWheatley) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c:196]: Much better, thank you!

**Review by RichardSWheatley — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]
