### PR TITLE
sensor: vcnl36825t: fix: Address CID 347083

### LINKED ISSUE #69125: [Coverity CID: 347083] Extra high-order bits in drivers/sensor/vcnl36825t/vcnl36825t.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/adeaa63bb71aba5c1732816df21f40d654e26cd4/drivers/sensor/vcnl36825t/vcnl36825t.c

Category: Integer handling issues
Function: `vcnl36825t_init_registers`
Component: Drivers
CID: [347083](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=347083)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/adeaa63bb71aba5c1732816df21f40d654e26cd4/drivers/sensor/vcnl36825t/vcnl36825t.c

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=347083

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CONSTANT_EXPRESSION_RESULT). ([CWE-569](http://cwe.mitre.org/data/definitions/569.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by ubieda**
Coverity found this legitimate issue: the datasheet specifies PS_IT being 2-bits long (1, 2, 4, 8) and this driver assumes more steps are available. Remove extraneous fields so the Proximity integration setting fits in the expected 16-bit value.

Fixes #69125

### CODE REVIEW

**Comment by ubieda** [comment]
CC: @deveritec-rosc

**Comment by deveritec-rosc** [comment]
Thank you!

Haven't seen this, might be I was in a "wrong" sensor. Might be a good idea to switch to an integer-based enum, then.

File: drivers/sensor/vishay/vcnl36825t/vcnl36825t.c [hunk 1]
```diff
@@ -242,26 +242,10 @@ static int vcnl36825t_init_registers(const struct device *dev)
 		reg_value |= VCNL36825T_PS_IT_1T;
 		data->meas_timeout_us *= 1 * VCNL36825T_FORCED_FACTOR_SCALE;
```
Comment (deveritec-rosc) [inline drivers/sensor/vishay/vcnl36825t/vcnl36825t.c:243]: You may remove `VCNL36825T_FORCED_FACTOR_SCALE` since it was necessary to get the 0.5 values into the integer range. If you do so, you can also simplify `VCNL36825T_FORCED_FACTOR_SCALE * VCNL36825T_FORCED_FACTOR_SCALE` in line 380 to a simple `VCNL36825T_FORCED_FACTOR_SCALE`

Comment (ubieda) [reply drivers/sensor/vishay/vcnl36825t/vcnl36825t.c]: Thanks. Addressed.

**Review by deveritec-jusc — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by decsny — APPROVED** [review]
