### PR TITLE
Bluetooth: controller: nRF21540 FEM support for nRF52x and nRF53x Series

### LINKED ISSUE #24142: NRF5340 PA/LNA support
**Describe the bug**
When enabling PA/LNA pin control the build fails with what appears to be both GPIO and PPID related errors. It doesn't look like the NRF53 PA/LNA code is implemented yet.

**To Reproduce**
1) 
add following to hci_rpmsg sample prj.conf, using the 
CONFIG_BT_CTLR=y
CONFIG_BT_CTLR_GPIO_PA=y
CONFIG_BT_CTLR_GPIO_PA_PIN=29
CONFIG_BT_CTLR_GPIO_LNA=y
CONFIG_BT_CTLR_GPIO_LNA_PIN=24

2)
west build samples/bluetooth/hci_rpmsg -b nrf5340_dk_nrf5340_cpunet
3)
Fails with lots of error, but seems to be both GPIO and ppi related:
...error: 'NRF_GPIO' undeclared (first use in this function); did you mean 'NRF_GPIOTE'?
 #define NRF_GPIO_PA     NRF_GPIO

...warning: implicit declaration of function 'hal_enable_palna_ppi_config'; did you mean 'hal_trigger_aar_ppi_config'? [-Wimplicit-function-declaration]

...error: 'HAL_ENABLE_PALNA_PPI' undeclared 

**Expected behavior**
Expected the sample to build and PA/LNA control to work.

**Impact**
My board is not useable as I have an external amplifier which cannot be controlled by the NRF5340.

**Environment (please complete the following information):**
- Latest NCS, so not up to date zephyr - but the affected file (radio.c) is the same as in latest zephyr master (7ba5e012f7f2e380b360df84f3a345fdec9cc234)

### PR DESCRIPTION
**Pull request by cvinayak**
Added nRF21540 FEM support for nRF52x and nRF53x Series.

Thanks to @bjornspock for the FEM contributions and @auroraslb for the DPPI refactoring.

image

Fixes #24142.

~Contains cherry-picked commit from @auroraslb PR: #30732~

### CODE REVIEW

**Comment by carlescufi** [comment]
@cvinayak this FEM configuration needs to be in Devicetree, not in Kconfig. @KAGA164 might have some input here.

**Comment by KAGA164** [comment]
I agree with @carlescufi  the FEM hardware configuration like pins should be in the device tree. We already have bindings for the nRF21540 FEM in the Zephyr. Also the FEM configuration is added to the nrf21540dk_nrf52840 dts file https://github.com/zephyrproject-rtos/zephyr/blob/a4f0ca8649065101efc628dab8fd6fbe62954b94/boards/arm/nrf21540dk_nrf52840/nrf21540dk_nrf52840.dts#L113 and https://github.com/zephyrproject-rtos/zephyr/blob/a4f0ca8649065101efc628dab8fd6fbe62954b94/boards/arm/nrf21540dk_nrf52840/nrf21540dk_nrf52840.dts#L216. I would like to add also a support for nrf21540EK which is currently in the PR #31523 but it seems to be blocked because we have only use case for it in the NCS not in the Zephyr. The BLE Controller should automatically enable support for FEM if its configuration is in the devicetree then we could easy build samples for nrf21540dk and also when the EK shield is used we could enable it when `west build` is invoked

**Comment by cvinayak** [comment]
@carlescufi and @KAGA164 This PR is collection of other authors works. I do not have the knowledge or time in the near future to rework, there is already a related issue https://github.com/zephyrproject-rtos/zephyr/issues/30708, if someone wants to work on it, they can use this PR as base and add commits to port to DTS macros.

**Comment by carlescufi** [comment]
@auroraslb or @KAGA164 could you please pick this up and rework it accordingly?

**Comment by mbolivar-nordic** [comment]
> @auroraslb or @KAGA164 could you please pick this up and rework it accordingly?

@carlescufi does that mean I should not work on #30708? Just clarifying.

**Comment by cvinayak** [comment]
@carlescufi This PR is relatively big in terms of feature support, should be reviewed as-is and merged. The DT porting should be addressed in #30708, which can be done by @mbolivar and I can assist in its review and testing.

Hope the functional changes in this PR gets some reviews, else this is now entering the merge conflicts due to other PRs modifying the files common to this PR.

**Comment by carlescufi** [comment]
> > @auroraslb or @KAGA164 could you please pick this up and rework it accordingly?
> 
> @carlescufi does that mean I should not work on #30708? Just clarifying.

Sorry for the delay. No, apparently no one is working on that, so you can feel free to pick that up in fact.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h [hunk 1]
```diff
@@ -28,7 +28,7 @@ static inline void hal_radio_nrf_ppi_channels_disable(uint32_t mask)
  * Enable Radio on Event Timer tick:
  * wire the EVENT_TIMER EVENTS_COMPARE[0] event to RADIO TASKS_TXEN/RXEN task.
  */
-#define HAL_RADIO_ENABLE_ON_TICK_PPI 0
+#define HAL_RADIO_ENABLE_ON_TICK_PPI 6
```
Comment (mbolivar-nordic) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h:32]: The commit log says the motivation is "so that DPPI 0-4 available for application's use" -- where is that going to be documented?

More generally, PPI values seem like something that should be moved into DT, since they are boot time hardware configuration values. Another benefit would be that users could override this macro with an overlay as they desire.

Would you agree? If so, that also would solve the documentation problem if there is no existing doc, because the pages in the DT bindings index would be the docs.

File: subsys/bluetooth/controller/Kconfig.ll_sw_split [hunk 2]
```diff
@@ -657,12 +657,57 @@ config BT_CTLR_GPIO_LNA_POL_INV
...
+	select BT_CTLR_GPIO_PA
+	select BT_CTLR_GPIO_LNA
+	help
+	  Enable PDN and CSN GPIO interface for the nRF21540. This allows
+	  hardware designs using the nRF21540 to let the controller toggle
+	  their state based on radio activity.
+
+if BT_CTLR_FEM_NRF21540
+
+config BT_CTLR_GPIO_PDN_PIN
```
Comment (mbolivar-nordic) [inline subsys/bluetooth/controller/Kconfig.ll_sw_split:678]: Forgive my ignorance, but are these Kconfig options being copy/pasted from somewhere else for a different SoC?

If not, they should definitely be in DT instead, along with the polarity (since we have the GPIO_ACTIVE_LOW flag in DTS), CSN pin, etc.

File: subsys/bluetooth/controller/Kconfig.ll_sw_split [hunk 3]
```diff
@@ -672,6 +717,24 @@ config BT_CTLR_PA_LNA_GPIOTE_CHAN
...
 	  Select the nRF5 GPIOTE channel to use for PA/LNA GPIO feature.
 
+config BT_CTLR_PDN_GPIOTE_CHAN
+	# Hidden "nRF5 GPIO FEM PDN GPIOTE Channel"
+	int
+	depends on SOC_FAMILY_NRF && BT_CTLR_FEM_NRF21540
+	default 4 if PWM_NRF5_SW
+	default 1
+	help
+	  Select the nRF5 GPIOTE channel to use for PA/LNA GPIO feature.
```
Comment (mbolivar-nordic) [inline subsys/bluetooth/controller/Kconfig.ll_sw_split:727]: This looks like a copy/paste error.

File: subsys/bluetooth/controller/Kconfig.ll_sw_split [hunk 4]
```diff
@@ -672,6 +717,24 @@ config BT_CTLR_PA_LNA_GPIOTE_CHAN
...
+
+config BT_CTLR_CSN_GPIOTE_CHAN
+	# Hidden "nRF5 GPIO FEM CSN GPIOTE Channel"
+	int
+	depends on SOC_FAMILY_NRF && BT_CTLR_FEM_NRF21540
+	default 5 if PWM_NRF5_SW
+	default 2
+	help
+	  Select the nRF5 GPIOTE channel to use for PA/LNA GPIO feature.
```
Comment (mbolivar-nordic) [inline subsys/bluetooth/controller/Kconfig.ll_sw_split:736]: Here too?

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:678]: I am not against use of DT, it is just that original controller contribution was before use of DT, and not all of controller has been ported to DT use.

> they should definitely be in DT

Agree. As a subsequent PR, please do work on the port.

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:727]: yes. Will fix it.

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 4 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:736]: yes, will fix it.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h:32]: > The commit log says the motivation is "so that DPPI 0-4 available for application's use" -- where is that going to be documented?

I thought this would document it: https://github.com/zephyrproject-rtos/zephyr/blob/45cdc051ed9e25b7252706ac7a7caf2436084631/modules/hal_nordic/nrfx/nrfx_glue.h#L229

> PPI values seem like something that should be moved into DT

Agree.

(Just thinking aloud, PPI/DPPIs and other peripherals are used by controller at scheduled time periods, they can but are not currently been used outside the Zephyr controller. nRF Connect SD controller based application do use outside the controller's scheduled time periods).

**Comment by carlescufi** [comment]
@mbolivar-nordic @anangl @rugeGerritsen @KAGA164 could you please review?

**Review by mbolivar-nordic — APPROVED** [review]
Looks OK to the best of my limited ability to review. I'll take on conversion of pin Kconfigs to DT as follow up PRs.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h [hunk 5]
```diff
@@ -168,6 +169,50 @@ static inline void hal_trigger_rateoverride_ppi_config(void)
...
+	nrf_gpiote_subscribe_set(NRF_GPIOTE, task, HAL_DISABLE_PALNA_PPI);
+}
+
+#endif /* CONFIG_BT_CTLR_GPIO_PA_PIN || CONFIG_BT_CTLR_GPIO_LNA_PIN */
+
+/******************************************************************************/
+#if defined(CONFIG_BT_CTLR_FEM_NRF21540)
+
+#define HAL_ENABLE_FEM_PPI 4
+#define HAL_DISABLE_FEM_PPI HAL_ENABLE_PALNA_PPI
```
Comment (anangl) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h:197]: These channels should be added to `HAL_USED_PPI_CHANNELS`, similarly to how it is done for the PA/LNA ones: https://github.com/zephyrproject-rtos/zephyr/blob/82a55328ccc96abeff252dc63e73b3577973abf0/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h#L582-L588

Same applies to the corresponding change in `radio_nrf5_ppi.h`.

Comment (anangl) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h:197]: It looks like it should be:
```suggestion
#define HAL_ENABLE_FEM_PPI 4
#define HAL_DISABLE_FEM_PPI HAL_ENABLE_FEM_PPI
```
Otherwise, the PDN and CSN pins will be toggled on `NRF_TIMER_EVENT_COMPARE3` and `NRF_RADIO_EVENT_DISABLED` but also on `NRF_TIMER_EVENT_COMPARE2` (what would be different from the PPI version) as this event is published to the same channel.

**Review by anangl — CHANGES_REQUESTED** [review]

**Review by cvinayak — COMMENTED** [review]
@anangl please re-review.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h (hunk 5 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h]: done

**Review by anangl — APPROVED** [review]
LGTM now.
