### PR TITLE
drivers: serial: nrfx_uarte2: Fixes in the new nordic shim

### LINKED ISSUE #67890: drivers: uart: uart_async_api: drivers.uart.async_api.nrf_uarte_new fails
**Describe the bug**
The test `drivers.uart.async_api.nrf_uarte_new` fails.

Observed for `nrf52840dk_nrf52840`.

**To Reproduce**
1. have `nrf52840dk_nrf52840` connected
2. connect pins follow `tests/drivers/uart/uart_async_api/boards/nrf52840dk_nrf52840.overlay`
3. go to your zephyr dir
4. call `$ZEPHYR_BASE/scripts/twister -vv --inline-logs --fixture gpio_loopback -T ./tests/drivers/uart/uart_async_api/ --device-testing --hardware-map map.yml --platform nrf52840dk_nrf52840 -j 1`
5. See handler.log and console output

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.5.0-4510-g18c23dec5f60 ***
Running TESTSUITE uart_async_chain_read
===================================================================
START - test_chained_read
Assertion failed at ../../../../../../../zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:338: test_chained_read_callback: err not equal to 0
FAIL - test_chained_read in 0.015 seconds
===================================================================
TESTSUITE uart_async_chain_read failed.
Running TESTSUITE uart_async_chain_write
===================================================================
START - test_chained_write
PASS - test_chained_write in 0.003 seconds
===================================================================
TESTSUITE uart_async_chain_write succeeded
Running TESTSUITE uart_async_double_buf
===================================================================
START - test_double_buffer
Assertion failed at ../../../../../../../zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:448: uart_async_double_buf_test_double_buffer: (k_sem_take(&rx_rdy, K_MSEC(100)) not equal to 0)
RX_RDY timeout
FAIL - test_double_buffer in 0.177 seconds
===================================================================
TESTSUITE uart_async_double_buf failed.
Running TESTSUITE uart_async_long_buf
===================================================================
START - test_long_buffers
Assertion failed at ../../../../../../../zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:859: uart_async_long_buf_test_long_buffers: (k_sem_take(&rx_rdy, K_MSEC(200)) not equal to 0)
RX_RDY timeout
FAIL - test_long_buffers in 0.376 seconds
===================================================================
TESTSUITE uart_async_long_buf failed.
Running TESTSUITE uart_async_multi_rx
===================================================================
START - test_multiple_rx_enable
PASS - test_multiple_rx_enable in 0.703 seconds
===================================================================
TESTSUITE uart_async_multi_rx succeeded
Running TESTSUITE uart_async_read_abort
===================================================================
START - test_read_abort
Assertion failed at ../../../../../../../zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:514: read_abort_timeout: (err not equal to 0)
Unexpected err:-14
FAIL - test_read_abort in 0.068 seconds
===================================================================
TESTSUITE uart_async_read_abort failed.
Running TESTSUITE uart_async_single_read
===================================================================
START - test_single_read
Assertion failed at ../../../../../../../zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:198: uart_async_single_read_test_single_read: (k_sem_take(&rx_rdy, K_MSEC(100)) not equal to 0)
RX_RDY timeout
FAIL - test_single_read in 0.377 seconds
===================================================================
TESTSUITE uart_async_single_read failed.
Running TESTSUITE uart_async_timeout
===================================================================
START - test_forever_timeout
PASS - test_forever_timeout in 3.001 seconds
===================================================================
TESTSUITE uart_async_timeout succeeded
Running TESTSUITE uart_async_write_abort
===================================================================
START - test_write_abort
Assertion failed at ../../../../../../../zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:632: uart_async_write_abort_test_write_abort: (k_sem_take(&rx_rdy, K_MSEC(100)) not equal to 0)
RX_RDY timeout
FAIL - test_write_abort in 0.176 seconds
===================================================================
TESTSUITE uart_async_write_abort failed.
------ TESTSUITE SUMMARY START ------
SUITE FAIL -   0.00% [uart_async_chain_read]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.015 seconds
- FAIL - [uart_async_chain_read.test_chained_read] duration = 0.015 seconds
SUITE PASS - 100.00% [uart_async_chain_write]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.003 seconds
- PASS - [uart_async_chain_write.test_chained_write] duration = 0.003 seconds
SUITE FAIL -   0.00% [uart_async_double_buf]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.177 seconds
- FAIL - [uart_async_double_buf.test_double_buffer] duration = 0.177 seconds
SUITE FAIL -   0.00% [uart_async_long_buf]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.376 seconds
- FAIL - [uart_async_long_buf.test_long_buffers] duration = 0.376 seconds
SUITE PASS - 100.00% [uart_async_multi_rx]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.703 seconds
- PASS - [uart_async_multi_rx.test_multiple_rx_enable] duration = 0.703 seconds
SUITE FAIL -   0.00% [uart_async_read_abort]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.068 seconds
- FAIL - [uart_async_read_abort.test_read_abort] duration = 0.068 seconds
SUITE FAIL -   0.00% [uart_async_single_read]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.377 seconds
- FAIL - [uart_async_single_read.test_single_read] duration = 0.377 seconds
SUITE PASS - 100.00% [uart_async_timeout]: pass = 1, fail = 0, skip = 0, total = 1 duration = 3.001 seconds
- PASS - [uart_async_timeout.test_forever_timeout] duration = 3.001 seconds
SUITE FAIL -   0.00% [uart_async_write_abort]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.176 seconds
- FAIL - [uart_async_write_abort.test_write_abort] duration = 0.176 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: ba6c879283bee2986900ac515803a39e
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Toolchain Zephyr 0.16.1
 - Commit SHA or Version used: zephyr-v3.5.0-4510-g18c23dec5f60

**Additional context**
Used pin set:
```
psels = <NRF_PSEL(UART_TX, 1, 1)>,
				<NRF_PSEL(UART_RX, 1, 2)>,
				<NRF_PSEL(UART_RTS, 1, 3)>,
				<NRF_PSEL(UART_CTS, 1, 4)>;
```

### PR DESCRIPTION
**Pull request by nordic-krch**
Set of fixes for new UART shim. After those fixes tests with new shim can be re-enabled on CI for nordic bsim targets.

Fixes #67890.

### CODE REVIEW

**Comment by aescolar** [comment]
Thanks Krzysztof, it looks fine enough to me. Should we aim at 3.6? (I set the milestone assuming so, please change it if you diagree)

File: drivers/serial/uart_nrfx_uarte2.c [hunk 1]
```diff
@@ -297,7 +316,6 @@ static void on_rx_buf_req(const struct device *dev)
 	 */
 	if (!K_TIMEOUT_EQ(adata->rx_timeout, K_NO_WAIT)) {
 		/* Read and clear any pending new data information. */
-		nrfx_uarte_rx_new_data_check(nrfx_dev);
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uarte2.c:300]: The related comment should be removed together with this call.

Comment (nordic-krch) [reply drivers/serial/uart_nrfx_uarte2.c:300]: removed

**Review by dcpleung — DISMISSED** [review]

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
