### PR TITLE
drivers: virtio: fix cleanup upon failure during virtqueues initialization

### LINKED ISSUE #91242: [Coverity CID: 525181] Infinite loop in drivers/virtio/virtio_pci.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/fd6b05c81b86a1ffe465d56ded7b73a9fdb7f14b/drivers/virtio/virtio_pci.c

Category: Program hangs
Function: `virtio_pci_init_virtqueues`
Component: Drivers
CID: [525181](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=525181)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/fd6b05c81b86a1ffe465d56ded7b73a9fdb7f14b/drivers/virtio/virtio_pci.c

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=525181

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INFINITE_LOOP). ([CWE-835](http://cwe.mitre.org/data/definitions/835.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by fkokosinski**
This PR fixes infinite loop reported in https://github.com/zephyrproject-rtos/zephyr/issues/91242, not deallocating array with virtqueues and not deactivating the virtqueues in case of failure.

Fixes #91242.

### CODE REVIEW

File: drivers/virtio/virtio_pci.c [hunk 1]
```diff
@@ -271,30 +271,44 @@ static int virtio_pci_init_virtqueues(
...
-			return ret;
+			goto fail;
 		}
+		activated_queues++;
 	}
 
 	return 0;
+
+fail:
+	for (int j = 0; j < activated_queues; j++) {
```
Comment (soburi) [inline drivers/virtio/virtio_pci.c:300]: nitpick: Here is not inside the loop where `i` is the counter, so I think it would be better to use `i` rather than `j`.

**Review by soburi — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by tgorochowik — APPROVED** [review]

**Review by nashif — APPROVED** [review]
