### PR TITLE
run i2s_api tests in user mode

### LINKED ISSUE #11383: tests/drivers/i2s/i2s_api failing on sam_e70_xplained
**Describe the bug**
This test defines two suites, i2s_loopback_test and i2s_states_test. i2s_loopback_test passes, but i2s_states_test is failing:
```
Running test suite i2s_states_test
===================================================================
starting test - test_i2s_tx_transfer_configure_1
PASS - test_i2s_tx_transfer_configure_1
===================================================================
starting test - test_i2s_rx_transfer_configure_1
PASS - test_i2s_rx_transfer_configure_1
===================================================================
starting test - test_i2s_state_not_ready_neg
[00:00:04.250,057] <dbg> dev_i2s_sam_ssc.i2s_sam_write: invalid state
[00:00:04.491,271] <dbg> dev_i2s_sam_ssc.bit_clock_set: freq = 256000
[00:00:04.505,136] <dbg> dev_i2s_sam_ssc.bit_clock_set: freq = 256000
[00:00:04.518,656] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: START trigger: invalid state
[00:00:04.518,664] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: DRAIN trigger: invalid state
[00:00:04.518,671] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: STOP trigger: invalid state
[00:00:04.518,678] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: DROP trigger: invalid state
[00:00:04.518,685] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: PREPARE trigger: invalid state
[00:00:04.518,690] <dbg> dev_i2s_sam_ssc.i2s_sam_read: invalid state
[00:00:04.518,702] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: START trigger: invalid state
[00:00:04.518,716] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: DRAIN trigger: invalid state
[00:00:04.518,724] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: STOP trigger: invalid state
[00:00:04.518,731] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: DROP trigger: invalid state
[00:00:04.518,736] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: PREPARE trigger: invalid state
[00:00:04.518,752] <dbg> dev_i2s_sam_ssc.i2s_sam_write: invalid state
PASS - test_i2s_state_not_ready_neg
===================================================================
starting test - test_i2s_state_ready_neg
PASS - test_i2s_state_ready_neg
===================================================================
starting test - test_i2s_state_running_neg
[00:00:04.638,157] <dbg> dev_i2s_sam_ssc.bit_clock_set: freq = 256000
[00:00:04.638,165] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: DRAIN trigger: invalid state
[00:00:04.638,174] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: STOP trigger: invalid state
[00:00:04.638,181] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: PREPARE trigger: invalid state
[00:00:04.638,189] <dbg> dev_i2s_sam_ssc.bit_clock_set: freq = 256000
[00:00:04.638,200] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: DRAIN trigger: invalid state
[00:00:04.638,206] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: STOP trigger: invalid state
[00:00:04.638,213] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: PREPARE trigger: invalid state
[00:00:04.655,082] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: START trigger: invalid state
[00:00:04.655,090] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: PREPARE trigger: invalid state
[00:00:04.655,102] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: START trigger: invalid state
[00:00:04.655,111] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: PREPARE trigger: invalid state

    Assertion failed at /home/apboie/projects/zephyr2/tests/drivers/i2s/i2s_api/src/test_i2s_states.c:33O

FAIL - test_i2s_state_running_neg
===================================================================
starting test - test_i2s_state_stopping_neg

    Assertion failed at /home/apboie/projects/zephyr2/tests/drivers/i2s/i2s_api/src/test_i2s_states.c:37)
RX START trigger failed
FAIL - test_i2s_state_stopping_neg
===================================================================
starting test - test_i2s_state_error_neg

    Assertion failed at /home/apboie/projects/zephyr2/tests/drivers/i2s/i2s_api/src/test_i2s_states.c:43)
RX START trigger failed
FAIL - test_i2s_state_error_neg
===================================================================
===================================================================
PROJECT EXECUTION FAILED
[00:00:04.743,897] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: START trigger: invalid state
[00:00:04.770,784] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: START trigger: invalid state
[00:00:04.799,466] <dbg> dev_i2s_sam_ssc.i2s_sam_trigger: START trigger: invalid state
```
This was undetected by CI due to an issue where if a test defines multiple suites, and the first suite to run passes, CI ignores the result of any subsequent suites.

**To Reproduce**
Build/flash the test on sam_e70_xplained, run on a board and observe console output

**Expected behavior**
All tests pass.

**Impact**
It means the driver has bugs.

### LINKED ISSUE #11384: CI ignores result of multiple test suites in one test application
**Describe the bug**
See #11383 
This test defines two suites:

```
void test_main(void)
{
	ztest_test_suite(i2s_loopback_test,
			ztest_unit_test(test_i2s_tx_transfer_configure_0),
			ztest_unit_test(test_i2s_rx_transfer_configure_0),
			ztest_unit_test(test_i2s_transfer_short),
			ztest_unit_test(test_i2s_transfer_long),
			ztest_unit_test(test_i2s_rx_sync_start),
			ztest_unit_test(test_i2s_rx_empty_timeout),
			ztest_unit_test(test_i2s_transfer_restart),
			ztest_unit_test(test_i2s_transfer_rx_overrun),
			ztest_unit_test(test_i2s_transfer_tx_underrun));
	ztest_run_test_suite(i2s_loopback_test);

	ztest_test_suite(i2s_states_test,
			ztest_unit_test(test_i2s_tx_transfer_configure_1),
			ztest_unit_test(test_i2s_rx_transfer_configure_1),
			ztest_unit_test(test_i2s_state_not_ready_neg),
			ztest_unit_test(test_i2s_state_ready_neg),
			ztest_unit_test(test_i2s_state_running_neg),
			ztest_unit_test(test_i2s_state_stopping_neg),
			ztest_unit_test(test_i2s_state_error_neg));
	ztest_run_test_suite(i2s_states_test);
}
```

The second suite fails, but because the result of the first suite prints PROJECT_EXECUTION_SUCCESSFUL, CI stops looking at console output after that.

**To Reproduce**
See #11383 , this test is broken but our test reports are not capturing this test as failing on the board.

**Expected behavior**
ztest should only print success/fail messages after all suites have been run (test_main exits) and it should be a boolean AND of all the individual suite runs.

**Impact**
It's annoying as you can have at most one suite per test application.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Contains code from #11388, plus an amended i2s_api test case which runs all the tests in user mode.

Also fixes #11384 and fixes #11383

### CODE REVIEW

File: tests/drivers/i2s/i2s_api/src/test_i2s_loopback.c [hunk 1]
```diff
@@ -335,10 +218,20 @@ void test_i2s_rx_sync_start(void)
 
 	/* Prefill TX queue */
 	for (int n = 0; n < NUM_TX_BLOCKS; n++) {
-		ret = k_mem_slab_alloc(&tx_0_mem_slab, &tx_block, K_FOREVER);
-		zassert_equal(ret, TC_PASS, NULL);
-		fill_buf_const((u16_t *)tx_block, 1, 2);
-		ret = i2s_write(dev_i2s, tx_block, BLOCK_SIZE);
+		if (test_priv_mode == TEST_SUPERVISOR_MODE) {
```
Comment (aurel32) [inline tests/drivers/i2s/i2s_api/src/test_i2s_loopback.c]: I wonder if we should use the same code for supervisor and user mode, ie always calling `i2s_buf_write` instead of allocating a memory block with `k_mem_slab_alloc` followed by `i2s_write`.

**Review by aurel32 — COMMENTED** [review]
It looks all good overall and passes the test on a SAM E70 Xplained board. I only have a minor/comment remark.

**Comment by andrewboie** [comment]
recheck

**Review by aescolar — COMMENTED** [review]
Regarding the I2S changes it is not my area so I can't comment.

About the ztest changes, I have no complaints.
(as most of the PR is about I2S I prefer to not give a +1 to not mislead)

File: tests/drivers/i2s/i2s_api/src/test_i2s_loopback.c (hunk 1 above)
Comment (andrewboie) [reply tests/drivers/i2s/i2s_api/src/test_i2s_loopback.c]: ok, done

**Review by ceolin — APPROVED** [review]

**Review by nashif — APPROVED** [review]
