### PR TITLE
Bluetooth: Fix gatt db stored twice

### LINKED ISSUE #22730: CONFIG_BT_SETTINGS writes bt/hash to storage twice
**Describe the bug**
When `CONFIG_BT_SETTINGS` is enabled and the user calls `settings_load()`, initially `bt/hash` is stored as 0x0000. Later, the OS calles `bt_hash_gen()` and re-stores the hash (this time calculated). In combination with a flash back-end this causes excessive flash wear.

**To Reproduce**
1. enable `CONFIG_BT_SETTINGS` in project, call `settings_load` in `bt_ready` callback (from `bt_init)
2. west build -b nrf52_pca10040
3. west flash
4. Reset the device a couple of times and check the storage partition using `nrfjprog --memrd flash_partition_offset --n 512`

**Expected behavior**
`bt/hash` should not be stored immediately, but calculated once and stored once.

**Impact**
In combination with a flash backend causes excessive flash wear on every reboot of the device.

**Screenshots or console output**
memrd output:
```
0x0007B000: C0FFEEEE 0007FF01 2F746218 68736168   |.........bt/hash|
0x0007B010: 9243D53D 3B7FBAD2 2DD486F0 2AD9F5CC   |=.C....;...-...*|
0x0007B020: 6218905A 61682F74 003D6873 00000000   |Z..bt/hash=.....|
0x0007B030: 00000000 00000000 EF000000 2F746218   |.............bt/|
0x0007B040: 68736168 9243D53D 3B7FBAD2 2DD486F0   |hash=.C....;...-|
0x0007B050: 2AD9F5CC 6218905A 61682F74 003D6873   |...*Z..bt/hash=.|
0x0007B060: 00000000 00000000 00000000 EF000000   |................|
0x0007B070: 2F746218 68736168 9243D53D 3B7FBAD2   |.bt/hash=.C....;|
0x0007B080: 2DD486F0 2AD9F5CC 6218905A 61682F74   |...-...*Z..bt/ha|
0x0007B090: 003D6873 00000000 00000000 00000000   |sh=.............|
0x0007B0A0: EF000000 2F746218 68736168 9243D53D   |.....bt/hash=.C.|
0x0007B0B0: 3B7FBAD2 2DD486F0 2AD9F5CC 6218905A   |...;...-...*Z..b|
0x0007B0C0: 61682F74 003D6873 00000000 00000000   |t/hash=.........|
0x0007B0D0: 00000000 EF000000 2F746218 68736168   |.........bt/hash|
0x0007B0E0: 9243D53D 3B7FBAD2 2DD486F0 2AD9F5CC   |=.C....;...-...*|
0x0007B0F0: 6218905A 61682F74 003D6873 00000000   |Z..bt/hash=.....|
0x0007B100: 00000000 00000000 EF000000 2F746218   |.............bt/|
0x0007B110: 68736168 9243D53D 3B7FBAD2 2DD486F0   |hash=.C....;...-|
0x0007B120: 2AD9F5CC 6218905A 61682F74 003D6873   |...*Z..bt/hash=.|
0x0007B130: 00000000 00000000 00000000 EF000000   |................|
0x0007B140: 2F746218 68736168 9243D53D 3B7FBAD2   |.bt/hash=.C....;|
0x0007B150: 2DD486F0 2AD9F5CC 6218905A 61682F74   |...-...*Z..bt/ha|
0x0007B160: 003D6873 00000000 00000000 00000000   |sh=.............|
0x0007B170: EF000000 2F746218 68736168 9243D53D   |.....bt/hash=.C.|
0x0007B180: 3B7FBAD2 2DD486F0 2AD9F5CC 6218905A   |...;...-...*Z..b|
0x0007B190: 61682F74 003D6873 00000000 00000000   |t/hash=.........|
0x0007B1A0: 00000000 EF000000 2F746218 68736168   |.........bt/hash|
0x0007B1B0: 9243D53D 3B7FBAD2 2DD486F0 2AD9F5CC   |=.C....;...-...*|
0x0007B1C0: 6218905A 61682F74 003D6873 00000000   |Z..bt/hash=.....|
0x0007B1D0: 00000000 00000000 EF000000 2F746218   |.............bt/|
0x0007B1E0: 68736168 9243D53D 3B7FBAD2 2DD486F0   |hash=.C....;...-|
0x0007B1F0: 2AD9F5CC 6218905A 61682F74 003D6873   |...*Z..bt/hash=.|
0x0007B200: 00000000 00000000 00000000 EF000000   |................|
0x0007B210: 2F746218 68736168 9243D53D 3B7FBAD2   |.bt/hash=.C....;|
```

**Environment (please complete the following information):**
 - OS: Manjaro-Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: zephyr 2.1.99

**Additional context**
Created from issue #20629

### PR DESCRIPTION
**Pull request by joerchan**
Fix issue where an invalid (all zeroes) hash was written to settings
storage on reset. This caused the old value to written to zeroes, before
being written back to it's original value again immediately after.
This causes excessive flash wear.

This happens because the check if (k_delayed_work_remaining) returns the
amount of time until the work will execute. When that time has run out
the time is zero, but the work has not yet been executed.
We then write the invalid hash to flash, and then once the work-item
executes it will write the correct value.

@Vudentz @jhedberg
I have documented the behaviour with bt_gatt_service_register and settings_load.
At least that is how it works currently.
I'm not sure if this is the behaviour we wanted or not. @Vudentz Was this intentional or not? Is it documented somewhere else?

If it is not the behaviour we want then we should probably change, but maybe that change could wait until after the release?

Fixes: #22730

### CODE REVIEW

**Comment by joerchan** [comment]
CC: @pabigot I think because of the assumption that the database hash work cannot be preempted we don't have to solve the preemption problem. Is my assumption correct?

**Review by pabigot — APPROVED** [review]
I think this is right.   The reason it's right is a bit subtle; for other reviewers: the cancel operation will succeed (return zero) only if the work was either in progress or was still pending.  "in-progress" isn't possible as long as the work can't be preempted.  So a zero return means there was a hash calculation pending, so the read operation has to calculate it itself.

I haven't tested this myself, of course.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -640,11 +647,13 @@ static ssize_t db_hash_read(struct bt_conn *conn,
...
 {
+	int err;
+
 	/* Check if db_hash is already pending in which case it shall be
-	 * generated immediately instead of waiting the work to complete.
+	 * generated immediately instead of waiting for the work to complete.
 	 */
-	if (k_delayed_work_remaining_get(&db_hash_work)) {
-		k_delayed_work_cancel(&db_hash_work);
+	err = k_delayed_work_cancel(&db_hash_work);
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c]: Interesting, I recall k_delayed_work_cancel was not causing any errors if it was already completed but it looks like that has been changed since then.

**Review by pabigot — CHANGES_REQUESTED** [review]
> Interesting, I recall k_delayed_work_cancel was not causing any errors if it was already completed but it looks like that has been changed since then.

After going back to the code, rather than the API documentation, I agree.  In fact I can't see any way to robustly detect whether a submitted delayed work item has been completed.

Since the solution here was based on my advice I'm drafting an alternative, to be more sure I know what I'm talking about.  Please wait on that before merging.

**Comment by Vudentz** [comment]
@joerchan it looks like we will be merging the change to k_delayed_work_cancel so this means you can keep these changes are they are.

**Review by Vudentz — APPROVED** [review]

**Comment by joerchan** [comment]
@Vudentz Thanks. I'll leave this one as is for the time being then.

**Comment by joerchan** [comment]
@pabigot This one approach should now work since #22810 has been merged, do you agree?

**Review by pabigot — APPROVED** [review]

**Comment by pabigot** [comment]
> @pabigot This one approach should now work since #22810 has been merged, do you agree?

Well, "should".  Has it been tested?

**Comment by joerchan** [comment]
> > @pabigot This one approach should now work since #22810 has been merged, do you agree?
> 
> Well, "should". Has it been tested?

Yes, tested with both cancel while it is pending in the work queue, and after it has executed. I mentioned it here as well: https://github.com/zephyrproject-rtos/zephyr/pull/22810#pullrequestreview-359900053
