### PR TITLE
drivers: display: stm32_ltdc: fix for stm32f429i_disc1

### LINKED ISSUE #68103: Display: STM32: display in not working on stm32f429i_disc1
**Describe the bug**
The drivers/display sample gives random noise on the screen. LVGL samples, modules/lvgl/demos & subsys/display/lvgl, give distorted frames.

 - What target platform are you using? stm32f429i_disc1 board
 - What have you tried to diagnose or workaround this issue? Found a fix to ili9341 driver that must be applied on top of PR #66271.
   PR #66271 alone gives a white screen.
 - Is this a regression? No info

**To Reproduce**
1. cd ~/zephyrproject/zephyr
2. west build -p always -b stm32f429i_disc1 samples/drivers/display
3. west flash

**Expected behavior**
Correct display of frames.

**Impact**
showstopper

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.3
 - Commit SHA or Version used: main, 571b647825b0402b1b46b4347b1db508b14cdf88

**Additional context**
This issue needs to be solved to be able to test PR #64587 on stm32f429i_disc1.

### PR DESCRIPTION
**Pull request by ajarmouni-st**
Fixes issue #68103.

### CODE REVIEW

**Comment by erwango** [comment]
@danieldegrasse FYI

File: drivers/display/display_ili9341.c [hunk 1]
```diff
@@ -134,5 +135,10 @@ int ili9341_regs_init(const struct device *dev)
 		return r;
 	}
 
+	r = ili9xxx_transmit(dev, ILI9XXX_DISPON, NULL, 0U);
+	if (r < 0) {
+		return r;
+	}
```
Comment (fabiobaltieri) [inline drivers/display/display_ili9341.c:141]: I don't think this is the correct fix, `ILI9XXX_DISPON` is normally sent with `ili9xxx_display_blanking_off`. The problem with this specific board is that the display needs that command to be sent for both the LTDC AND the ILI9xxx driver.

Since this is a board specific quirk I think that the correct fix is to have a board specific file grabbing the `ili9341` display device (with a nodelabel or something) and calling the API unblank command at the right time.

**Review by fabiobaltieri — CHANGES_REQUESTED** [review]

File: drivers/display/display_ili9341.c (hunk 1 above)
Comment (ajarmouni-st) [reply drivers/display/display_ili9341.c:141]: Okey, thanks! Will make the necessary modifs.

**Comment by erwango** [comment]
> @danieldegrasse FYI

Wrong PR, I wanted to mention https://github.com/zephyrproject-rtos/zephyr/pull/66271

**Comment by danieldegrasse** [comment]
> Wrong PR, I wanted to mention https://github.com/zephyrproject-rtos/zephyr/pull/66271

@erwango thanks for pointing this out.

From my understanding, the board's default strap configuration for the IM[3:0] pins is 0110, which uses SPI/MIPI-DBI mode to send data: 
image
(This is from the STM32F429I-DISC1 board schematic here: https://www.st.com/resource/en/schematic_pack/mb1075-f429i-e01_schematic.pdf)

That being said, the ILI9341 does support an RGB interface, which it looks like is what this board intends to use. This is specific to the way the board has been set up, but a pretty reasonable use case for the ILI9341. This feels like a common issue we have with displays, where the configuration of the display uses a different interface than the video output.

The same sort of issue exists for displays like the RM68200, which uses MIPI DSI to setup the display, but has RGB data driven via the LCDIF (which is piped through a MIPI DSI converter internally). There, the display is simply enabled during boot- so there is no need to call `display_blanking_off`.

One solution we might consider here is adding an `rgb-mode` parameter to the ili9341 devicetree. This has the following advantages:
- the ILI9341 does have support for additional configuration when using RGB mode, which we may want to expose via devicetree in the future:
image
- this would keep the functionality pretty generic, IE "if RGB mode is in use, automatically unblank the display and setup RGB interface parameters based on devicetree", which would make supporting other LCD controllers with this driver easier

**Comment by ajarmouni-st** [comment]
Rebased to integrate commit 2545c747b8688aa7f6f1b653ebd1dfabbd2050dd, and moved the fix to drivers/display/display_stm32_ltdc.c

File: drivers/display/display_stm32_ltdc.c [hunk 2]
```diff
@@ -169,6 +170,15 @@ static void stm32_ltdc_get_capabilities(const struct device *dev,
...
 	capabilities->current_orientation = DISPLAY_ORIENTATION_NORMAL;
+
+#if CONFIG_ILI9341
+	const struct device *ili9341 = DEVICE_DT_GET(DT_INST(0, ilitek_ili9341));
+
+	/* Needed for display to function correctly on stm32f429i_disc1 */
+	if (device_is_ready(ili9341)) {
+		display_blanking_off(ili9341);
+	}
+#endif /* CONFIG_ILI9341 */
```
Comment (fabiobaltieri) [inline drivers/display/display_stm32_ltdc.c:181]: no need to hard code a specific device-to-device dependency, do this instead:

- add an optional `phandle` property for the secondary device in `st,stm32-ltdc.yaml`
- use that to point at `ili9341` from the `&ltdc` node
- in this file use the property to populate a `struct device` pointer (or NULL) in the `display_stm32_ltdc_config` structure
- in `stm32_ltdc_display_api` implement the `.blanking_on` and `.blanking_off` function, there you can check if you have a device in that pointer, and if you do call `display_blanking_on` and `display_blanking_off` in that device (which will result in calling the right function at the right time once the application tries to unblank the ltdc controller)

**Comment by danieldegrasse** [comment]
> Yes but the dts of the board configures the interface for RGB, https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/stm32f429i_disc1/stm32f429i_disc1.dts#L170 if I recall correctly. So in this setup the ilitek,ili9341 device has to be used for configuration, including unblanking, and ltdc for the data.

Maybe the ltdc device could take an optional phandle and forward some API to that device instead?

Sure, I think that approach makes sense- I didn't realize the ILI9341 driver already handled RGB configuration

**Comment by fabiobaltieri** [comment]
> Maybe the ltdc device could take an optional phandle and forward some API to that device instead?

Yeah I think that would be ideal.

File: dts/bindings/display/st,stm32-ltdc.yaml [hunk 3]
```diff
@@ -64,3 +65,9 @@ properties:
   window0-y1:
     type: int
     description: Last pixel in y direction on layer 0. Defaults to height.
+
+  display-controller:
+    type: phandle
+    description: |
```
Comment (danieldegrasse) [inline dts/bindings/display/st,stm32-ltdc.yaml:71]: Nit: language in descriptions are usually more passive, right? IE something like "phandle of display controller. When set, used by LTDC driver to manage display blanking configuration"

File: drivers/display/display_stm32_ltdc.c [hunk 4]
```diff
@@ -260,6 +262,38 @@ static int stm32_ltdc_read(const struct device *dev, const uint16_t x,
...
+
+	LOG_DBG("Turning display blanking on");
+	/* Needed for display to function correctly on boards that use the display's controller
+	 * for configuration and LTDC for data.
+	 */
+	if (device_is_ready(config->display_controller)) {
+		r = display_blanking_on(config->display_controller);
+	}
+
+	return r;
```
Comment (fabiobaltieri) [inline drivers/display/display_stm32_ltdc.c:294]: it's usually a good practice throughtout the code base to indent error handling and keep "normal" execution inline, plus you are not handling the null case, how about somthing like

```c
if (config->display_controller == NULL) {
        return 0;
}

if (!device_is_ready(config->display_controller)) {
        LOG_ERR("Display device %s not ready", config->display_controller->name);
        return -ENODEV;
}

return display_blanking_on(config->display_controller);
```

File: drivers/display/display_stm32_ltdc.c [hunk 5]
```diff
@@ -439,7 +473,9 @@ static const struct display_driver_api stm32_ltdc_display_api = {
 	.read = stm32_ltdc_read,
 	.get_capabilities = stm32_ltdc_get_capabilities,
 	.set_pixel_format = stm32_ltdc_set_pixel_format,
-	.set_orientation = stm32_ltdc_set_orientation
+	.set_orientation = stm32_ltdc_set_orientation,
+	.blanking_off = stm32_ltdc_display_blanking_off,
+	.blanking_on = stm32_ltdc_display_blanking_on
```
Comment (fabiobaltieri) [inline drivers/display/display_stm32_ltdc.c:478]: nit: keep the `,` on the last element, then the next change won't have the stray diff

File: drivers/display/display_stm32_ltdc.c (hunk 4 above)
Comment (ajarmouni-st) [reply drivers/display/display_stm32_ltdc.c:294]: I think device_is_ready() handles the NULL case but can add it if it makes the code clearer.

Comment (danieldegrasse) [reply drivers/display/display_stm32_ltdc.c:294]: `device_is_ready` should handle the NULL case, yeah- but I think the idea here is that a NULL device is a different issue from a device that failed to initialize and is not ready.

**Review by danieldegrasse — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
good stuff!

**Review by erwango — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@jfischer-no can you take a look?

File: drivers/display/display_stm32_ltdc.c [hunk 6]
```diff
@@ -260,6 +262,40 @@ static int stm32_ltdc_read(const struct device *dev, const uint16_t x,
 	return 0;
 }
 
+static int stm32_ltdc_display_blanking_off(const struct device *dev)
+{
+	const struct display_stm32_ltdc_config *config = dev->config;
+	const struct device *display_dev = config->display_controller;
```
Comment (jfischer-no) [inline drivers/display/display_stm32_ltdc.c:268]: `config->display_controller` is ambiguous in the context of the device controller driver, needs to be improved, maybe `ext_dc` or `panel_controller`.

**Review by jfischer-no — APPROVED** [review]
