### PR TITLE
drivers: timer: stm32 lptim fix Potentially overflow

### LINKED ISSUE #29697: [Coverity CID :215243] Unintentional integer overflow in drivers/timer/stm32_lptim_timer.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/c9a2a5e7fb0194bfb168f5aa1a0a83c73f62acb3/drivers/timer/stm32_lptim_timer.c#L313

Category: Integer handling issues
Function: `z_timer_cycle_get_32`
Component: Drivers
CID: [215243](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=215243)

Details:

```
307             lp_time += LL_LPTIM_GetAutoReload(LPTIM1) + 1;
308         }
309    
310         lp_time += accumulated_lptim_cnt;
311    
312         /* convert lptim count in a nb of hw cycles with precision */
>>>     CID 215243:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
>>>     Potentially overflowing expression "lp_time * (sys_clock_hw_cycles_per_sec() / 32768)" with type "unsigned int" (32 bits, unsigned) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type "uint64_t" (64 bits, unsigned).
313         uint64_t ret = lp_time * (sys_clock_hw_cycles_per_sec() / LPTIM_CLOCK);
314    
315         k_spin_unlock(&lock, key);
316    
317         /* convert in hw cycles (keeping 32bit value) */
318         return (uint32_t)(ret);
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #29700: [Coverity CID :215253] Unintentional integer overflow in drivers/timer/stm32_lptim_timer.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/c9a2a5e7fb0194bfb168f5aa1a0a83c73f62acb3/drivers/timer/stm32_lptim_timer.c#L289

Category: Integer handling issues
Function: `z_clock_elapsed`
Component: Drivers
CID: [215253](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=215253)

Details:

```
283    
284         k_spin_unlock(&lock, key);
285    
286         /* gives the value of LPTIM1 counter (ms)
287          * since the previous 'announce'
288          */
>>>     CID 215253:  Integer handling issues  (OVERFLOW_BEFORE_WIDEN)
>>>     Potentially overflowing expression "lp_time * 4096U" with type "unsigned int" (32 bits, unsigned) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type "uint64_t" (64 bits, unsigned).
289         uint64_t ret = (lp_time * CONFIG_SYS_CLOCK_TICKS_PER_SEC) / LPTIM_CLOCK;
290    
291         return (uint32_t)(ret);
292     }
293    
294     uint32_t z_timer_cycle_get_32(void)
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by FRASTM**
Fix Unintentional integer overflow in the calculation
Integer handling issues (OVERFLOW_BEFORE_WIDEN)
Potentially overflowing expression with a cast

Fixes #29700 
Fixes #29697

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by r2r0** [comment]
Is there a reason why these calculations are done in two different ways (multiplication then division and division then multiplication)?
If we want to have the same results with the same inputs (and do not loose precision) then multiplication should be performed first using 64 bits arithmetic (casting) and then there should be made a division.

File: drivers/timer/stm32_lptim_timer.c [hunk 1]
```diff
@@ -290,7 +290,7 @@ uint32_t z_clock_elapsed(void)
 	/* gives the value of LPTIM1 counter (ms)
 	 * since the previous 'announce'
 	 */
-	uint64_t ret = (lp_time * CONFIG_SYS_CLOCK_TICKS_PER_SEC) / LPTIM_CLOCK;
+	uint64_t ret = (uint64_t)((lp_time * CONFIG_SYS_CLOCK_TICKS_PER_SEC) / LPTIM_CLOCK);
```
Comment (aurel32) [inline drivers/timer/stm32_lptim_timer.c:294]: That doesn't look correct for me, the `lp_time * CONFIG_SYS_CLOCK_TICKS_PER_SEC` multiplication is still done as 32-bit. This should be written as:

`uint64_t ret = ((uint64_t)lp_time * CONFIG_SYS_CLOCK_TICKS_PER_SEC) / LPTIM_CLOCK;`

File: drivers/timer/stm32_lptim_timer.c [hunk 2]
```diff
@@ -314,7 +314,7 @@ uint32_t z_timer_cycle_get_32(void)
 	lp_time += accumulated_lptim_cnt;
 
 	/* convert lptim count in a nb of hw cycles with precision */
-	uint64_t ret = lp_time * (sys_clock_hw_cycles_per_sec() / LPTIM_CLOCK);
+	uint64_t ret = (uint64_t)(lp_time * (sys_clock_hw_cycles_per_sec() / LPTIM_CLOCK));
```
Comment (aurel32) [inline drivers/timer/stm32_lptim_timer.c:317]: Ditto

**Review by aurel32 — CHANGES_REQUESTED** [review]

File: drivers/timer/stm32_lptim_timer.c (hunk 1 above)
Comment (FRASTM) [reply drivers/timer/stm32_lptim_timer.c:294]: I agree

**Comment by FRASTM** [comment]
with this calculation on 64bit of returned time value, the timer tests can pass on nucleo_wb55rg
tests/kernel/timer/timer_monotonic/
tests/kernel/timer/timer_api

File: drivers/timer/stm32_lptim_timer.c (hunk 1 above)
Comment (aurel32) [reply drivers/timer/stm32_lptim_timer.c:294]: Thanks for the change, it looks correct now.

File: drivers/timer/stm32_lptim_timer.c [hunk 3]
```diff
@@ -314,7 +314,7 @@ uint32_t z_timer_cycle_get_32(void)
 	lp_time += accumulated_lptim_cnt;
 
 	/* convert lptim count in a nb of hw cycles with precision */
-	uint64_t ret = lp_time * (sys_clock_hw_cycles_per_sec() / LPTIM_CLOCK);
+	uint64_t ret = (uint64_t)lp_time * (sys_clock_hw_cycles_per_sec() / LPTIM_CLOCK);
```
Comment (aurel32) [inline drivers/timer/stm32_lptim_timer.c:317]: This doesn't look correct to me, but it was already the case before and not due to to you change. If the computation has to be done with precision as in the comment, it should be:
`uint64_t ret = ((uint64_t)lp_time * sys_clock_hw_cycles_per_sec()) / LPTIM_CLOCK;`

Basically just like the other change. Also note that `sys_clock_hw_cycles_per_sec` is equivalent to `CONFIG_SYS_CLOCK_TICKS_PER_SEC` when `CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME` is not defined, which is the case for this driver.

Comment (FRASTM) [reply drivers/timer/stm32_lptim_timer.c:317]: Ok,
I did not find any error when testing (10x) tests/kernel/timer/timer_api and tests/kernel/timer/timer_monotonic on nucleo stm32wb55 (when lptim enabled)

**Comment by r2r0** [comment]
As I already wrote, dividing before multiplying causes lost of precision.
I.e. consider: sys_clock_hw_cycles_per_sec() = 64000000, LPTIM_CLOCK=32768, lp_time=32768 - the correct result is 64000000, but actual code gives: 63995904
Consider using expression as below, please.
```C
uint64_t ret = ((uint64_t)lp_time * sys_clock_hw_cycles_per_sec()) / LPTIM_CLOCK;
```

**Comment by r2r0** [comment]
Thanks @FRASTM

**Review by aurel32 — APPROVED** [review]
Thanks for the fix, it looks good to me now.

**Review by erwango — APPROVED** [review]

**Review by galak — APPROVED** [review]
