### PR TITLE
arc: core: Fix possible overrun

### LINKED ISSUE #20487: [Coverity CID :205648]Memory - corruptions in /arch/arc/core/mpu/arc_mpu_v3_internal.h
Static code scan issues seen in File: /arch/arc/core/mpu/arc_mpu_v3_internal.h
 Category: Memory - corruptions
 Function: arc_mpu_init
 Component: Architectures
 CID: 205648
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by ceolin**
dyn_reg_info has MPU_DYNAMIC_REGION_AREAS_NUM elements, just changing
the if check to be greater equal to this number to avoid access
MPU_DYNAMIC_REGION_AREAS_NUM element causing an out-of-bounds write.

CID: 205648

Fixes #20487

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
> CID: 205648

You probably want to add 

Fixes #<bug number>

here.

**Comment by ceolin** [comment]
Didn

> > CID: 205648
> 
> You probably want to add
> 
> Fixes #
> 
> here.

I thought Fixes was being used to reference github issue. I wanted to to put the coverity id for reference. Should I just reference the github issue id ?

**Review by ruuddw — APPROVED** [review]
Coverity is right, thanks for the quick fix Flavio!

**Comment by ruuddw** [comment]
> I thought Fixes was being used to reference github issue. I wanted to to put the coverity id for reference. Should I just reference the github issue id ?

Yes, if you add the Github issue id, the issue gets automatically closed. Not sure btw if that is best in this case, as also the Coverity issue should be updated and that isn't done automatically (at least not until a next scan).

**Review by ioannisg — APPROVED** [review]

File: arch/arc/core/mpu/arc_mpu_v3_internal.h [hunk 1]
```diff
@@ -711,7 +711,7 @@ static int arc_mpu_init(struct device *arg)
 
 		/* record the static region which can be split */
 		if (mpu_config.mpu_regions[i].attr & REGION_DYNAMIC) {
-			if (dynamic_regions_num >
+			if (dynamic_regions_num >=
 			MPU_DYNAMIC_REGION_AREAS_NUM) {
 				LOG_ERR("no enough dynamic regions %d",
```
Comment (ioannisg) [inline arch/arc/core/mpu/arc_mpu_v3_internal.h]: now that you are here, you can change "no" to "not", as well.

**Comment by nashif** [comment]
> I thought Fixes was being used to reference github issue. I wanted to to put the coverity id for reference. Should I just reference the github issue id ?

we do have an issue here, so this PR should be marked as fixing the bug.
Fixed #20487

File: arch/arc/core/mpu/arc_mpu_v3_internal.h (hunk 1 above)
Comment (ceolin) [reply arch/arc/core/mpu/arc_mpu_v3_internal.h]: fair enough

**Review by tyrantlizard77 — APPROVED** [review]
