### PR TITLE
arch and dma thead and bflb bugfixes

### LINKED ISSUE #98723: arch: custom: xtheadcmo: Range calculation is wrong
### Describe the bug

The range cache functions use a length too short to clear the addr and size pair provided, resulting in partially flushed arrays that are then incompletely updated when grabbed by the non-cache-using hardware.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Try to flush array from cache, see only most of it is flushed.

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by VynDragon**
Fix DMA not flush and invalidating source, fix cache functions not doing the whole range.

Fixes #98722
Fixes #98723

### CODE REVIEW

File: drivers/dma/dma_bflb.c [hunk 1]
```diff
@@ -271,8 +271,13 @@ static int dma_bflb_start(const struct device *dev, uint32_t channel)
 	size_t pending_length = (control & DMA_TRANSFERSIZE_MASK) >> DMA_TRANSFERSIZE_SHIFT;
 	uintptr_t addr = sys_read32(
 		cfg->base_reg + DMA_CxDSTADDR_OFFSET + BFLB_DMA_CH_OFFSET(channel));
-
```
Comment (JarmouniA) [inline drivers/dma/dma_bflb.c:274]: unnecessary change

**Review by JarmouniA — COMMENTED** [review]
Needs an accompanying (detailed) bug report if you want it merged before the release.

File: drivers/dma/dma_bflb.c (hunk 1 above)
Comment (VynDragon) [reply drivers/dma/dma_bflb.c:274]: done.

File: arch/riscv/custom/thead/cache_xtheadcmo.c [hunk 2]
```diff
@@ -83,7 +84,8 @@ int arch_icache_invd_range(void *addr_in, size_t size)
 		"fence\n"
 		"fence.i\n"
 	);
-	for (uintptr_t i = addr; i < addr + size; i += CONFIG_ICACHE_LINE_SIZE) {
+	for (uintptr_t i = addr; i < ROUND_UP(addr + size, CONFIG_DCACHE_LINE_SIZE);
```
Comment (josuah) [inline arch/riscv/custom/thead/cache_xtheadcmo.c]:
```suggestion
	for (uintptr_t i = addr; i < ROUND_UP(addr + size, CONFIG_ICACHE_LINE_SIZE);
```

**Review by josuah — COMMENTED** [review]
Almost ready!

File: arch/riscv/custom/thead/cache_xtheadcmo.c (hunk 2 above)
Comment (VynDragon) [reply arch/riscv/custom/thead/cache_xtheadcmo.c]: Thanks for catching that one. Done.

**Review by josuah — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Comment by jhedberg** [comment]
Is this planned for 4.3? If so, please set the appropriate milestone and link to a matching bug report (create one if it doesn't exist yet). Any bug fix PRs intended for 4.3 which were opened after rc2 (like this one) need a bug report.

**Comment by VynDragon** [comment]
> a matching bug report (create one if it doesn't exist yet)

Please turn your attention to the right side of the PR screen.
image

> Is this planned for 4.3? 

Not necessarily, nothing uses this code atm.

There is a draft for where this is causing problems: https://github.com/zephyrproject-rtos/zephyr/pull/98752

**Comment by jhedberg** [comment]
> Please turn your attention to the right side of the PR screen.

Thanks. Most PRs simply have "Fixes ..." references in the PR description, which is what I've gotten used to looking for. I'll modify this practice to inlcude those references (which I think have been manually created rather than github automatically picking them up from the PR description?)

**Comment by VynDragon** [comment]
Yes it is manual
