### PR TITLE
net: lib: coap: Handle truncated messages in CoAP server

### LINKED ISSUE #83735: CoAP server should not silently truncate too long requests
**Describe the bug**

The CoAP server reads incoming packets from the UDP socket using `recvfrom`, which silently truncates messages if they don't fit into the buffer (see [Socket API docs here](https://pubs.opengroup.org/onlinepubs/9699919799/functions/recvfrom.html)).

There is an assertion which checks the returned length. However, this assertion will never fail as long as the Socket API is implemented correctly.

https://github.com/zephyrproject-rtos/zephyr/blob/d78952b7ba930e20910c2b6fdac49cc8dc4f709e/subsys/net/lib/coap/coap_server.c#L139-L141

**To Reproduce**

1. Build some code that uses the CoAP server, e.g. `samples/net/sockets/coap_server`
2. Send a CoAP request that is larger than `CONFIG_COAP_SERVER_MESSAGE_SIZE`.
3. Observe that the message is silently truncated.

**Expected behavior**

The CoAP server should not further process incomplete CoAP messages. It should ~~also not~~ respond to the client ~~with an ACK, but~~ with [4.13 Request Entity Too Large](https://www.rfc-editor.org/rfc/rfc7252.html#section-5.9.2.9) ~~instead~~.

**Impact**

Buffers must be oversized to avoid undefined behavior, as incoming request length is usually not fully predictable at compile-time.

**Environment (please complete the following information):**

 - Commit SHA: d78952b7ba930e20910c2b6fdac49cc8dc4f709e

### PR DESCRIPTION
**Pull request by pdgendt**
If the CoAP server receives a message that doesn't fit into the receive buffer, we should stop processing the message and respond to the client with 4.13 "Request Entity too large".

Fixes #83735

### CODE REVIEW

File: subsys/net/lib/coap/coap_server.c [hunk 1]
```diff
@@ -149,7 +148,7 @@ static int coap_server_process(int sock_fd)
 		return -errno;
 	}
 
-	ret = coap_packet_parse(&request, buf, received, options, opt_num);
+	ret = coap_packet_parse(&request, buf, MIN(received, sizeof(buf)), options, opt_num);
```
Comment (martinjaeger) [inline subsys/net/lib/coap/coap_server.c:151]: I'm wondering if we should really still attempt to parse the packet if we know that it's incomplete?

File: subsys/net/lib/coap/coap_server.c [hunk 2]
```diff
@@ -170,6 +169,43 @@ static int coap_server_process(int sock_fd)
 
 	type = coap_header_get_type(&request);
 
+	if (received > sizeof(buf)) {
+		/* The message was truncated and can't be processed further */
+		uint8_t resp_buf[CONFIG_COAP_SERVER_MESSAGE_SIZE];
```
Comment (martinjaeger) [inline subsys/net/lib/coap/coap_server.c:174]: Could we re-use the already allocated `buf`? We are using block transfer with payload size of 1024 bytes in our application, so this would allocate another 1100 bytes on the stack (message size includes the header and must be larger than the maximum expected payload size).

**Review by martinjaeger — COMMENTED** [review]
Thanks again for the fix.

I will test the code tomorrow. Some initial comments below.

File: subsys/net/lib/coap/coap_server.c (hunk 1 above)
Comment (pdgendt) [reply subsys/net/lib/coap/coap_server.c:151]: I think so, it parses the header (and options) only, which are needed to be able to respond.

File: subsys/net/lib/coap/coap_server.c (hunk 2 above)
Comment (pdgendt) [reply subsys/net/lib/coap/coap_server.c]: Updated to re-use the `buf` array.

File: subsys/net/lib/coap/coap_server.c (hunk 1 above)
Comment (martinjaeger) [reply subsys/net/lib/coap/coap_server.c:151]: True. We need at least the request type.

**Review by jukkar — DISMISSED** [review]

File: subsys/net/lib/coap/coap_server.c [hunk 3]
```diff
@@ -136,9 +136,8 @@ static int coap_server_process(int sock_fd)
 	ssize_t received;
 	int ret;
 
-	received = zsock_recvfrom(sock_fd, buf, sizeof(buf), ZSOCK_MSG_DONTWAIT, &client_addr,
-				  &client_addr_len);
-	__ASSERT_NO_MSG(received <= sizeof(buf));
+	received = zsock_recvfrom(sock_fd, buf, sizeof(buf), ZSOCK_MSG_DONTWAIT | ZSOCK_MSG_TRUNC,
```
Comment (rlubos) [inline subsys/net/lib/coap/coap_server.c:139]: Could be make the MSG_TRUNC usage optional (can be enabled by default) as in case of coap client (
https://github.com/zephyrproject-rtos/zephyr/commit/715b97397b797c7f105053dd41f2532006ae909d)? We had some issues with that flag in the offloaded case.

**Review by rlubos — COMMENTED** [review]
Generally looks good, one request though.

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
Thanks!

**Review by martinjaeger — APPROVED** [review]
Works great.
