### PR TITLE
Bluetooth: ISO: Add ISO tx callback struct array

### LINKED ISSUE #38563: ISO broadcast cannot send with callback if CONFIG_BT_CONN=n
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/pull/38194 introduced a bug for ISO broadcast if CONFIG_BT_CONN=n. 
If CONFIG_BT_CONN=n then the `free_tx` FIFO is never intiialized, causes the FIFO to be empty and thus no able to use the `bt_conn_send_cb` function that `bt_iso_chan_send` now relies on. 

Update: It seems that TX still works, but the callback is missing.

**To Reproduce**
Build and run `samples/bluetooth/iso_broadcast/` and see the `<err> bt_conn.bt_conn_send_cb: Unable to allocate TX context` error

**Expected behavior**
Expect broadcast ISO to be fully independent on CONFIG_BT_CONN. 

**Impact**
Showstopper for specific builds. Increased memory usage as a work around. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: cd5357ca56c2629b957a3a79a3dd71fe528e2626

**Additional context**

### PR DESCRIPTION
**Pull request by Thalley**
Add an array similar to the bt_conn (ACL/L2CAP)
tx sent callback, and initialize it.

This increases the number of bt_conn_tx available
such that ISO does not take any of "L2CAP's" buffers,
but also ensures that the sent callback is called
for a broadcast iso only build.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

fixes #38563

### CODE REVIEW

**Review by asbjornsabo — APPROVED** [review]
Seems to make sense

**Review by rick1082 — APPROVED** [review]

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -87,6 +87,20 @@ static struct bt_conn sco_conns[CONFIG_BT_MAX_SCO_CONN];
...
+/* Callback TX buffers for ISO */
+static struct bt_conn_tx iso_tx[CONFIG_BT_ISO_TX_BUF_COUNT];
+
+int bt_conn_iso_init(void)
+{
+	for (size_t i = 0; i < ARRAY_SIZE(iso_tx); i++) {
+		k_fifo_put(&free_tx, &iso_tx[i]);
+	}
+
+	return 0;
```
Comment (rick1082) [inline subsys/bluetooth/host/conn.c:100]: Seems ```bt_conn_iso_init()``` will only return ```0```, should we make it ```void```, or we add some checking mechanism?

Comment (Thalley) [reply subsys/bluetooth/host/conn.c:100]: That's a good question. Made it return `int` to follow the pattern of `bt_conn_init`, but maybe it should be `void`. @joerchan Any input?
