### PR TITLE
drivers: i2c: stm32: Fix STM32 I2C hang on read

### LINKED ISSUE #95762: STM32 I2C hang on read
### Describe the bug

In the latest version, when sending I2C read from the master side, the slave side has a bug, and because of it, the I2C bus hangs. In the Zephyr 3.7.1LTS version, the bug doesn't exist. 

# Bug reason

STM32-I2C v2 in target-transmit state, if you don’t write TXDR when TXIS fires, the peripheral clock-stretches (holds SCL low) until you do. There isn’t a magic “NACK-this-byte” bit you can set as a target while transmitting; the controller (master) owns the ACK/NACK after each data byte. So the only way to avoid the hang mid-transfer is to always write something to TXDR for every TXIS

# Bug source
The bug comes from `c7cbe9176074bdd967fb36953c6936817187ee7e` commit, which was done by @FRASTM in `drivers/i2c/i2c_ll_stm32_v2.c` file.

Image

# The code after the change is causing the hang issue
 ```
	if (LL_I2C_IsActiveFlag_TXIS(i2c)) {
		uint8_t val;

		if (slave_cb->read_processed(slave_cfg, &val) < 0) {
			LOG_ERR("Error continuing reading");
		} else {
			LL_I2C_TransmitData8(i2c, val);
		}
		return;
	}
```

# The correct code to resolve the issue

	if (LL_I2C_IsActiveFlag_TXIS(i2c)) {
		uint8_t val;

		if (slave_cb->read_processed(slave_cfg, &val) < 0) {
			LOG_ERR("Error continuing reading");
		} 
                LL_I2C_TransmitData8(i2c, val); // We must always TX data from Slave to Master
		return;
	}

Please create a fix for this. 

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kbidani**
ensure LL_I2C_TransmitData8() is always called when TXIS is set, even if read_processed() returns an error. This prevents the peripheral from clock-stretching indefinitely and blocking the I2C bus when the master reads from the slave.

fixes: #95762

### CODE REVIEW

**Review by FRASTM — DISMISSED** [review]

File: drivers/i2c/i2c_ll_stm32_v2.c [hunk 1]
```diff
@@ -347,9 +347,8 @@ static void i2c_stm32_slave_event(const struct device *dev)
 
 		if (slave_cb->read_processed(slave_cfg, &val) < 0) {
 			LOG_ERR("Error continuing reading");
-		} else {
-			LL_I2C_TransmitData8(i2c, val);
 		}
+		LL_I2C_TransmitData8(i2c, val);
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32_v2.c:352]: Please break a line before and after this.

**Review by erwango — CHANGES_REQUESTED** [review]

**Review by erwango — DISMISSED** [review]

File: drivers/i2c/i2c_ll_stm32_v2.c (hunk 1 above)
Comment (etienne-lms) [reply drivers/i2c/i2c_ll_stm32_v2.c:352]: If the function fails, `val` is likely not loaded. Would it be preferred it has at least a known value,
e.g. `uint8_t val = 0;` at line 346?

Comment (kbidani) [reply drivers/i2c/i2c_ll_stm32_v2.c:352]: Good point, thank you for the suggestion :)

**Review by erwango — APPROVED** [review]

**Review by etienne-lms — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
