### PR TITLE
Bluetooth: Fix bt_rand() infinite recursion

### LINKED ISSUE #22202: bt_rand() is called over HCI when BT_HOST_CRYPTO=y, even if BT_CTLR_LE_ENC=n
**Describe the bug**
If LE encryption is not supported (like the case for VEGA controllers), and host encryption is enabled, there will still be calls to the controller for obtaining the necessary 8 bytes of random data.
This is done in two places in subsys/bluetooth/host/crypto.c, in prng_reseed() and in prng_init().

The problem is that the  sequence of calls is actually a kind of infinite recursion, as per below

prng_reseed() -> BT_HCI_OP_LE_RAND -> le_rand() -> bt_rand() (host) -> prng_reseed()

The call to bt_rand() in host is done because only one implementation of the bt_rand() function (either from controller or from host) is being linked at a time.

Although I have not tested this, I suppose that this could be reproducible on Nordic as well, if setting BT_CTLR_LE_ENC_SUPPORT to n and enabling host crypto. Will test later on, when I can get access to a Nordic board.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=rv32m1_vega_ri5cy -DBT_HOST_CRYPTO=y
3. make
4. run on board and notice an error similar with the one below:
```
[00:00:00.120,000] <err> os: Exception cause Illegal instruction (2)
[00:00:00.120,000] <err> os: Faulting instruction address = 0x0d8fe860
[00:00:00.120,000] <err> os:   ra: 0x832f304a  gp: 0xec7e3d7e  tp: 0xe25f7e36  t0: 0x306eda80
[00:00:00.120,000] <err> os:   t1: 0x2c6fde6f  t2: 0x30a507e6  t3: 0x6a09e667  t4: 0xbb67ae85
[00:00:00.120,000] <err> os:   t5: 0x3c6ef372  t6: 0xa54ff53a  a0: 0x510e527f  a1: 0x9b05688c
[00:00:00.120,000] <err> os:   a2: 0xb78b2e79  a3: 0xb9a2e204  a4: 0x2fb44915  a5: 0xd90c5060
[00:00:00.120,000] <err> os:   a6: 0xd4839fe3  a7: 0x579a9afc
```
This is due to the fact that eventually the stack will run out.

**Expected behavior**
The controller random function should not be called when BT_CTLR_LE_ENC_SUPPORT is not enabled. This is according the the BLE spec, vol 2, part E, 3.1 LE Controller Requirements: where the HCI_LE_Rand command is noted as C4; per the note "C4: Mandatory if LE Feature (LE Encryption) is supported, otherwise excluded.".

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: VEGA Toolchain
 - Commit SHA or Version used: 7cb74655da83bf100eaacc3e00d96c94f1cfbcb3

**Additional context**
One quick-fix would be to re-implement prng_reseed() and prng_init() to call locally the entropy device. Another dirty fix would be to just use the kernel ticks (k_uptime_get) as the 8 bytes of 'entropy'.

### PR DESCRIPTION
**Pull request by joerchan**
Fix infinite recursion in host-based bt_rand function. This would call
HCI LE Random Number command, which would in turn call bt_rand, causing
an infinite recursion.

bt_rand -> prng_reseed -> BT_HCI_OP_LE_RAND -> le_rand -> bt_rand

To solve this issue the controller should avoid doing calls into the
host, so all calls to bt_rand in the controller should be replaced with
a call to a controller function.

Fixes #22202

In a combined build where bt_rand functions is implemented in the host
the RPA module should not use the bluetooth rand function since the RPA
module is common for host and controller.
Having the controller call the the host only to go through HCI back into
the controller would not be a good idea.

### CODE REVIEW

**Comment by joerchan** [comment]
@alexandru-porosanu-nxp @George-Stefan Please verify that this is working for you.
Please give BT_PRIVACY config option a try as well. Since the RPA changes should be tested as well.

@carlescufi  @jhedberg A bit unsure about the change I did to the RPA. But I think the alternative is to take it out of common. Having the controller call up to the host is not a good idea in my opinion.

**Review by alexandru-porosanu-nxp — APPROVED** [review]
LGTM. I've checked on VEGA in the same scenario that was failing and now all is fine.

**Comment by joerchan** [comment]
> LGTM. I've checked on VEGA in the same scenario that was failing and now all is fine.

Did you check with BT_PRIVACY=y as well? I want to make sure that RPAs work fine. Privacy should be possible as a host-only feature even if the controller don't support it, i.e CONFIG_BT_CTLR_PRIVACY=n

**Comment by alexandru-porosanu-nxp** [comment]
> > LGTM. I've checked on VEGA in the same scenario that was failing and now all is fine.
> 
> Did you check with BT_PRIVACY=y as well? I want to make sure that RPAs work fine. Privacy should be possible as a host-only feature even if the controller don't support it, i.e CONFIG_BT_CTLR_PRIVACY=n

Nope, not yet; I'll try it as well and report back.

**Comment by joerchan** [comment]
@alexandru-porosanu-nxp You can try `tests/bluetooth/shell` for this.

```
bt init
bt oob # should print a valid RPA address
bt advertise on # should be visible now with the RPA address
```

**Comment by alexandru-porosanu-nxp** [comment]
> @alexandru-porosanu-nxp You can try `tests/bluetooth/shell` for this.
> 
> ```
> bt init
> bt oob # should print a valid RPA address
> bt advertise on # should be visible now with the RPA address
> ```

Right, haven't thought of that. Here's the log:

```
*** Booting Zephyr OS build zephyr-v2.1.0-1527-g13fc774836a1  ***
Type "help" for supported commands.Before any Bluetooth commands you must `bt init` to initialize the stack.


uart:~$ bt init
Bluetooth initialized
[00:00:02.900,000] <inf> fs_nvs: 4 Sectors of 4096 bytes
[00:00:02.900,000] <inf> fs_nvs: alloc wra: 0, ff0
[00:00:02.900,000] <inf> fs_nvs: data wra: 0, 0
[00:00:02.910,000] <inf> bt_hci_core: HW Platform: reserved (0x0000)
[00:00:02.910,000] <inf> bt_hci_core: HW Variant: unknown (0x0000)
[00:00:02.910,000] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.1 Build 99
[00:00:02.910,000] <inf> bt_hci_core: No ID address. App must call settings_load()
[00:00:02.910,000] <wrn> bt_hci_core: No static addresses stored in controller
[00:00:03.240,000] <inf> bt_hci_core: Identity: e5:3f:3b:13:f4:07 (random)
[00:00:03.240,000] <inf> bt_hci_core: HCI: version 5.1 (0x0a) revision 0x0000, manufacturer 0x05f1
[00:00:03.240,000] <inf> bt_hci_core: LMP: version 5.1 (0x0a) subver 0xffff
[00:00:03.250,000] <inf> bt_settings: Saving ID
uart:~$ bt oob
OOB data:
addr                       random                           confirm                         
4b:33:b9:4b:33:b9 (random) 74580be004cb0d9cc25f0a4bc47cc85a 8f7599560e0aecaed77438a5f0198f19
uart:~$ bt advertise
advertise: wrong parameter count
advertise - <type: off, on, scan, nconn> [mode: discov, non_discov] [whitelist:
            wl, wl-scan, wl-conn] [identity]
uart:~$ bt advertise on
Advertising started
Connected: 40:6f:2a:fa:4b:9a (public)
Disconnected: 40:6f:2a:fa:4b:9a (public) (reason 0x13)
```
On the other device (phone), I see that the random address is actually used (4b:33:b9:4b:33:b9). (I guess that the connection failing is not really a problem).

**Comment by joerchan** [comment]
@alexandru-porosanu-nxp Thank you. Valid RPA, all good :)
The disconnect seems fine, initiated by remote.

File: subsys/bluetooth/common/rpa.c [hunk 1]
```diff
@@ -14,20 +14,41 @@
...
 #include "common/log.h"
 
+#include <bluetooth/crypto.h>
+
+#if defined(CONFIG_BT_CTLR) && defined(CONFIG_BT_HOST_CRYPTO)
+#include "../controller/util/util.h"
+#include "../controller/hal/ecb.h"
+#endif /* defined(CONFIG_BT_CTLR) && defined(CONFIG_BT_HOST_CRYPTO) */
+
+static inline int _rand(void *buf, size_t len)
```
Comment (jhedberg) [inline subsys/bluetooth/common/rpa.c]: You can probably drop the `inline` here. Unless you disable inlining with some explicit compiler option any functions that are this short and have a single caller will almost certainly get implicitly inlined. Also, I think there's a general avoidance of underscore-prefixed symbols in Zephyr, so I'd drop it. You could either just call this `rand`, or (perhaps better since it's a common name) put an _internal suffix on it.

File: subsys/bluetooth/common/rpa.c [hunk 2]
```diff
@@ -14,20 +14,41 @@
...
+/* Force using controller rand function. */
+#if defined(CONFIG_BT_CTLR) && defined(CONFIG_BT_HOST_CRYPTO)
+	return util_rand(buf, len);
+#else
+	return bt_rand(buf, len);
+#endif
+}
+
+static inline int _encrypt_le(const u8_t key[16], const u8_t plaintext[16],
+			      u8_t enc_data[16])
```
Comment (jhedberg) [inline subsys/bluetooth/common/rpa.c]: Same thing here with `inline` and the underscore prefix.

**Review by jhedberg — CHANGES_REQUESTED** [review]
A couple of small things, otherwise looks good

File: subsys/bluetooth/common/rpa.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: Ok. using internal_rand then. Since rand is defined by stdlib.h

File: subsys/bluetooth/common/rpa.c (hunk 2 above)
Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: fixed.

File: subsys/bluetooth/common/rpa.c [hunk 3]
```diff
@@ -14,20 +14,41 @@
...
+	return bt_rand(buf, len);
+#endif
+}
+
+static int internal_encrypt_le(const u8_t key[16], const u8_t plaintext[16],
+			       u8_t enc_data[16])
+{
+/* Force using controller encrypt function if supported. */
+#if defined(CONFIG_BT_CTLR) && defined(CONFIG_BT_HOST_CRYPTO) && \
+    defined(CONFIG_BT_CTLR_LE_ENC_SUPPORT)
```
Comment (George-Stefan) [inline subsys/bluetooth/common/rpa.c]: BT_CTLR_LE_ENC_SUPPORT is not documented at all (in fact none of the BT_CTLR_*_SUPPORT macros).
ecb.c is not conditionally compiled based on BT_CTLR_LE_ENC_SUPPORT.

I understand your intention, but we should clarify the purpose of BT_CTLR_*_SUPPORT macros

**Review by George-Stefan — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/common/rpa.c (hunk 3 above)
Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: @George-Stefan Yeah, I just took the first one I found :) Is using BT_CTLR_LE_ENC better?
The _SUPPORT ones are meant to be  internal ones to make Kconfig dependencies easier.

Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: The LE Encrypt command is not conditionally compiled out by anything in the controller. Should it perhaps? I see you added empty functions instead. I think all other calls to ecb_encrypt or ecb_encrypt_le are behind guards for BT_CTLR_LE_ENC .

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/common/rpa.c (hunk 3 above)
Comment (George-Stefan) [reply subsys/bluetooth/common/rpa.c]: There is a mix of implicit and explicit capabilities the relation of which I don't quite understand:
- functions from ecb.h
- BT_HOST_CRYPTO
- BT_CTLR_CRYPTO
- BT_CTLR_LE_ENC_SUPPORT
- BT_CTLR_PRIVACY_SUPPORT

Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: BT_HOST_CRYPTO -> compile in host/crypto.c for bt_rand/bt_encrypt_le/bt_encrypt_be
BT_CTLR_CRYPTO -> compile in controller/crypto.c for bt_rand/bt_encrypt_le/bt_encrypt_be
The first two should be mutually exlusive. Which is why HOST_CRYPTO is set automatically if not CTLR_CRYPTo

BT_CTLR_LE_ENC_SUPPORT -> The controller can support the LE Encryption command
BT_CTLR_PRIVACY_SUPPORT -> The controller can support all related LE controller-based privacy commands.

BT_CTLR_LE_ENC -> Enable support for LE encryption (depends on controller support).
BT_CTLR_PRIVACY -> Enable support for LE controller-based privacy (depends on controller support).

More generally BT_CTLR_<feature>_SUPPORT is set by the different controllers to indicate that this feature can be enabled.
BT_CTLR_<feature> is visible if the selected controller has _SUPPORT, and the user can enable or disable this feature.

Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: The host depends on the bt_rand/bt_encrypt_le/bt_encrypt_be functions.

File: subsys/bluetooth/common/rpa.c (hunk 2 above)
Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: @jhedberg Interesting observation: having inline avoids "warning: 'internal_rand' defined but not used"

File: subsys/bluetooth/common/rpa.c (hunk 3 above)
Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: Switched to BT_CTLR_LE_ENC.
@George-Stefan @cvinayak Please comment if this is wrong.

Comment (George-Stefan) [reply subsys/bluetooth/common/rpa.c]: I believe that BT_CTLR_CRYPTO should be conditioned by a BT_CTLR_CRYPTO_SUPPORT as well.
Now, there is the implicit assumption that the controller has crypto acceleration/support.

And because of this, there is this confusion where you disable BT_CTLR_LE_ENC_SUPPORT/BT_CTLR_PRIVACY_SUPPORT but BT_CTLR_CRYPTO is enabled by default.

I can see how you could have BT_CTLR_LE_ENC_SUPPORT/BT_CTLR_PRIVACY_SUPPORT without BT_CTLR_CRYPTO.
So, internal_encrypt_le() is not needed.
What do you think?

Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: @George-Stefan You mean introduce a new Kconfig support flag? I like that suggestion.

@cvinayak Agree to add BT_CTLR_CRYPTO_SUPPORT, and have BT_CTLR_CRYPTO depend on this flag?

Comment (George-Stefan) [reply subsys/bluetooth/common/rpa.c]: > @George-Stefan You mean introduce a new Kconfig support flag? I like that suggestion.

Yes

Comment (joerchan) [reply subsys/bluetooth/common/rpa.c]: @George-Stefan I agree that that could be done. But I'd like to do that separately. So merge this PR, and then clean up the CTLR_CRYPTO later.

Comment (carlescufi) [reply subsys/bluetooth/common/rpa.c]: @George-Stefan I agree with @joerchan. This PR fixes a real bug, and the shuffling of Kconfig options can be done as a separate Pull Request where we can all focus on the cleanup.

Comment (George-Stefan) [reply subsys/bluetooth/common/rpa.c]: ok

**Review by George-Stefan — APPROVED** [review]
