### PR TITLE
tests: cmsis_rtos_v2: Fix race condition

### LINKED ISSUE #25507: up_squared:tests/portability/cmsis_rtos_v2 failed.
**To Reproduce**
1. west build -b up_squared -p auto tests/portability/cmsis_rtos_v2
2. west flash ~/up_squared.sh
3. See error

**Screenshots or console output**

*** Booting Zephyr OS build v2.3.0-rc1-210-gac898bc49ea8  ***
Running test suite test_cmsis_v2_apis

starting test - test_kernel_apis
PASS - test_kernel_apis

starting test - test_delay
PASS - test_delay

starting test - test_thread_apis
PASS - test_thread_apis
...
starting test - test_mempool_dynamic
PASS - test_mempool_dynamic

**starting test - test_messageq
E: Page fault at address 0xd25ff8 (error code 0x3)
E: Access violation: supervisor thread not allowed to write**
E: PML4E: 0x0000000000d15827 Writable, User, Execute Enabled
E: PDPTE: 0x0000000000d14827 Writable, User, Execute Enabled
E:   PDE: 0x0000000000d0d023 Writable, Supervisor, Execute Enabled
E:   PTE: 0x8000000000d25001 Read-only, Supervisor, Execute Disable
E: RAX: 0x00000000001a4c04 RBX: 0x0000000000d1cd60 RCX: 0x000000000000000c RDX: 0x0000000000d26020
E: RSI: 0x0000000000d1cd60 RDI: 0x0000000000d1dbc8 RBP: 0x0000000000d26090 RSP: 0x0000000000d26000
E:  R8: 0x0000000000d26020  R9: 0x0000000000d4d280 R10: 0x0000000000000000 R11: 0x0000000000000000
E: R12: 0x0000000000d26020 R13: 0x0000000000d1dbc8 R14: 0x0000000000d1dbc8 R15: 0x0000000000000000
E: RSP: 0x0000000000d26000 RFLAGS: 0x0000000000010003 CS: 0x0018 CR3: 0x0000000000115000
E: RIP: 0x0000000000103f87
**E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x0000000000d18f90 (send_thread)**
E: Halting system

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.11.2
 - Commit ID: ac898bc49

### PR DESCRIPTION
**Pull request by ceolin**
Both threads, 4 and the main thread (test_thread_join) where
joining thread5. If thread 4 is scheduled before the
main thread it will be dead before the main thread
had chance to join it. Adding a delay (following the test
pattern) to avoid this problem.

Fixes #25507

### CODE REVIEW

**Review by nashif — APPROVED** [review]

File: tests/portability/cmsis_rtos_v2/src/thread_apis.c [hunk 1]
```diff
@@ -264,6 +264,15 @@ static void thread4(void *argument)
 	printk(" + Thread A started.\n");
 	status = osThreadJoin(tB);
 	zassert_equal(status, osOK, "osThreadJoin thread B failed!");
+
+	/*
+	 * Both this thread and the main thread (test_thread_join) are
```
Comment (andrewboie) [inline tests/portability/cmsis_rtos_v2/src/thread_apis.c:269]: nit: test_thread_join is not the main thread. it's ztest_thread.

File: tests/portability/cmsis_rtos_v2/src/thread_apis.c [hunk 2]
```diff
@@ -264,6 +264,15 @@ static void thread4(void *argument)
...
+	 * joining thread5. If this thread is scheduled before the
+	 * main thread this thread will be dead before the main thread
+	 * has chance to join it. Adding a delay (following the test
```
Comment (andrewboie) [inline tests/portability/cmsis_rtos_v2/src/thread_apis.c:272]: If I understand how this test is set up:
- ztest_thread creates Thread B
- ztest_thread creates Thread A
- ztest_thread joins on Thread B, and goes to sleep
- Thread B starts, but it enters an osDelay() of 1000 MS which is a very long time, and goes back to sleep
- Thread A starts, and also joins on Thread B, going to sleep
- Thread B wakes up from its osDelay() call and exits

So is the bug the following scenario:
- Thread A wakes up from its join call on thread B, and exits
- ztest_thread wakes up, tries to join on Thread A, but since it already exited we get an error?

And if ztest_thread wakes up before Thread A, everything works as expected?

In general I haaaaaate fixing issues with test thread scheduling with delays, it's far more robust to use different thread priorities instead. Can we set priorities for Thread A / Thread B so that the expected sequence is guaranteed?

Comment (ceolin) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c:272]: That is the scenario, the priorities should be set between thread A and ztest_thread. I agree with you btw, I was explaining it for Aastha, about how bad is syncing with delays, I just followed the way it was being done but let fixes it properly though.

Comment (ceolin) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c:272]: Just setting thread priority to the lowest worked, but it seems fragile as well since ztest_thread has some instructions before call thread_join to A and it can be scheduled out in one of those if I understood correctly. IMHO the whole test is confuse and it needs some love. Just sending a new version using priorities right now

Comment (andrewboie) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c:272]: > has some instructions before call thread_join to A and it can be scheduled out in one of those if I understood correctly

Not sure what you mean by this. What instructions are we talking about which would cause the thread to be scheduled out?

This shouldn't be fragile, the whole execution sequence should be predictable / deterministic

Comment (ceolin) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c:272]: ztest_thread calls k_uptime_delta that calls the syscall k_uptime_ticks

Comment (ceolin) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c:272]: nevermind, it is not even building with usermode

Comment (andrewboie) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c]: > ztest_thread calls k_uptime_delta that calls the syscall k_uptime_ticks

Unless I'm mistaken neither of those functions invokes the scheduler.

Comment (ceolin) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c]: does this patch looks right now ?

**Review by aasthagr — APPROVED** [review]

**Comment by carlescufi** [comment]
@andrewboie could you take another look please?

File: tests/portability/cmsis_rtos_v2/prj.conf [hunk 3]
```diff
@@ -14,3 +14,5 @@ CONFIG_CMSIS_V2_MEM_SLAB_MAX_DYNAMIC_SIZE=128
 CONFIG_CMSIS_V2_THREAD_MAX_COUNT=23
 CONFIG_CMSIS_V2_THREAD_DYNAMIC_MAX_COUNT=10
 CONFIG_TIMEOUT_64BIT=n
+CONFIG_CMSIS_V2_THREAD_MAX_STACK_SIZE=1024
```
Comment (andrewboie) [inline tests/portability/cmsis_rtos_v2/prj.conf:17]: what arches/boards were we overflowing the stack?

File: tests/portability/cmsis_rtos_v2/src/thread_apis.c [hunk 4]
```diff
@@ -284,6 +284,7 @@ void test_thread_join(void)
 	zassert_not_null(tB, "Failed to create thread B with osThreadNew!");
 
 	printk(" - Creating thread A...\n");
+	attr.priority = osPriorityLow;
```
Comment (andrewboie) [inline tests/portability/cmsis_rtos_v2/src/thread_apis.c:287]: +1

Comment (andrewboie) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c:287]: can you update the commit message? it still references a delay

**Comment by carlescufi** [comment]
@ceolin can you address the comments from Andrew?

File: tests/portability/cmsis_rtos_v2/prj.conf (hunk 3 above)
Comment (ceolin) [reply tests/portability/cmsis_rtos_v2/prj.conf:17]: up squared

File: tests/portability/cmsis_rtos_v2/src/thread_apis.c (hunk 4 above)
Comment (ceolin) [reply tests/portability/cmsis_rtos_v2/src/thread_apis.c:287]: Done, thanks for reviewing it
