### PR TITLE
drivers: serial: stm32: use PM constraints to prevent suspension

### LINKED ISSUE #38382: stm32 uart finishes Tx before going to PM
**Describe the bug**
On the stm32, when the PM is enabled, the testsuite **tests/kernel/tickless/tickless_concept** cannot ends properly when running with the twister script
Even if the test is running successfully,  the twister is not really ended, the  `PROJECT EXECUTION SUCCESSFUL` is missing.
The `end_report()` function of the subsys/testsuite/ztest/src/ztest.c cannot display the _result_ line.

When flashing the board and running the test direclty, the test is complete as expected : `PROJECT EXECUTION SUCCESSFUL`

**To Reproduce**
1.  _./scripts/twister --device-testing --device-serial /dev/ttyACM0 -p nucleo_wb55rg -T tests/kernel/tickless/tickless_concept/_
2. See error

**Expected behavior**
test PASSED until "PROJECT EXECUTION SUCCESSFUL" line

**Impact**
test declared  FAILED

**Logs and console output**
```
Running test suite tickless_concept
===================================================================
START - test_tickless_sysclock
time 20, 230
time 240, 440
PASS - test_tickless_sysclock in 0.465 seconds
===================================================================
START - test_tickless_slice
elapsed slice 110, expected: <100, 110>
elapsed slice 100, expected: <100, 110>
elapsed slice 100, expected: <100, 110>
elapsed slice 100, expected: <100, 110>
PASS - test_tickless_slice in 0.690 seconds
===================================================================
Test suite tickless_concept succeeded
===================================================================
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain : 0.13.0
 - Commit SHA b78d6740ec3510cc99b41c998544bcac747b4e40
- Zephyr version: v2.7.0-rc1-23-g89f4adf2ef77

**Additional context**

### LINKED ISSUE #38437: stm32: g0b1re: Serial UART timing issue after MCU entered deep sleep
**Describe the bug**
The log starts to print very slowly and wrong string after the MCU entered deep sleep, Im guessing that it is related to some uart timing issue.

**To Reproduce**
1. Build anything that logs something through serial UART, then enter LPM on Nucleo G0B1

**Expected behavior**
The serial print shouldn't be affected by LPM.

**Impact**
LOG isn't working correctly after LPM.

**Logs and console output**
```
[00:00:46.981,000] <inf> modem_gsm: RSSI: -63
[00:00:47.594,000] <inf> telemetry_mqtt: MQTT Keepalive
[00:00:50.095,000] <inf> telemetry_mqtt: MQTT Keepalive
[00:00:50.606,000] <inf> telemetry_mqtt: MQTT client disconnected 0
<-------- entered LPM here -------->
øJ[00:00:51.35,000] <wrn> hwmanger: Alloe to sleep[m
[1;2mgmoc:~ $ [mÄø[00:051.5,000] <b> hw_mana
```

**Environment (please complete the following information):**
 - Zephyr v2.7 RC1

**Additional context**
Tipped by @erwango that it could be related to this commit introduced from a4f6a3a85afa7eac45b339266ccd04ce49e7e9f4 this PR #36759, and is seems to be the case.

After I edited `uart_stm32.c` like so:
```c
#ifdef CONFIG_PM_DEVICE
static int uart_stm32_pm_control(const struct device *dev,
				 enum pm_device_action action)
{
	USART_TypeDef *UartInstance = UART_STRUCT(dev);

	/* setting a low power mode */
	switch (action) {
	case PM_DEVICE_ACTION_RESUME:
		break;
	case PM_DEVICE_ACTION_SUSPEND:
		__fallthrough;
	case PM_DEVICE_ACTION_FORCE_SUSPEND:
		__fallthrough;
	case PM_DEVICE_ACTION_LOW_POWER:
#ifdef USART_ISR_BUSY
		/* Make sure that no USART transfer is on-going */
		while (LL_USART_IsActiveFlag_BUSY(UartInstance) == 1) {
		}
#endif
		while (LL_USART_IsActiveFlag_TC(UartInstance) == 0) {
		}
#ifdef USART_ISR_REACK
		/* Make sure that USART is ready for reception */
		while (LL_USART_IsActiveFlag_REACK(UartInstance) == 0) {
		}
#endif
		/* Clear OVERRUN flag */
		LL_USART_ClearFlag_ORE(UartInstance);
		/* Leave UartInstance unchanged */
		break;
	default:
		return -ENOTSUP;
	}

	/* UartInstance returning to active mode has nothing special to do */
	return 0;
}
#endif /* CONFIG_PM_DEVICE */
```

It is working correctly again.

```
[00:00:46.975,000] <inf> modem_gsm: RSSI: -61
[00:00:47.578,000] <inf> telemetry_mqtt: MQTT Keepalive
[00:00:50.079,000] <inf> telemetry_mqtt: MQTT Keepalive
[00:00:50.590,000] <inf> telemetry_mqtt: MQTT client disconnected 0
[00:00:51.341,000] <wrn> hw_manager: Allowed to sleep
[00:00:51.341,000] <dbg> hw_manager.hw_man_release: Released HW_MAN_DEV_SOC
[00:00:51.341,000] <wrn> hw_manager: Stopped modem
[00:00:51.341,000] <dbg> hw_manager.hw_man_release: Released HW_MAN_DEV_MODEM
[00:00:51.341,000] <inf> telemetry_mqtt: Stop OK
gmoc:~ $
```

### PR DESCRIPTION
**Pull request by gmarull**
In the current implementation, the STM32 UART driver required to enable
`CONFIG_PM_DEVICE` when `CONFIG_PM=y` to function properly. The main
reason is that in some situations, like in polling mode, transmissions
are not fully synchronous. That is, a byte is pushed to the _queue_ if
it is empty, and then the function returns without waiting for it to be
transmitted to the wire. This makes sense to make things like per-byte
transmission efficient. However, this introduces a problem: the system
may reach idle state, and so enter low power modes before the UART has
actually finished processing the last data in the queue. If this happens,
communications can be interrupted, or garbage data may be put into the
UART line.

The proposed solution in this patch uses PM constraints to solve this
problem. For the IRQ/DMA case it is easy since we can set the constraint
before transmission start, and when the completion (TC) interrupt is
received we can clear it. However, the polling mode did not have the
capability to signal the completion. For this case, a simpler IRQ
routine is provided to just release the constraint. As a result, the PM
hooks are not required, and so the system can operate with just `CONFIG_PM`.

Fixes #38382 
Fixes #38437

@erwango @FRASTM seems to fix the issue on my side, but I may have missed things. `CONFIG_PM_DEVICE=y` default for STM32 should likely be reviewed.

### CODE REVIEW

**Comment by ceolin** [comment]
Looks good removing the pm control callback since it was not doing PM and move that logic to the places where they make sense. One question, isn't possible to use `pm_device_busy_set` ? This way the SoC will still go sleep but this device will remain active, if not using constraint is the right thing to do.

**Comment by gmarull** [comment]
> Looks good removing the pm control callback since it was not doing PM and move that logic to the places where they make sense. One question, isn't possible to use `pm_device_busy_set` ? This way the SoC will still go sleep but this device will remain active, if not using constraint is the right thing to do.

The problem is that in low power modes the UART is not operational as far as I understand:

image

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for that proposal, that's probably the best compromise given previous discussions.
I'm fine with the change if @dcpleung agrees as well (specially to have IRQ logic in poll_out case).
Only request would be to set the full logic under CONFIG_PM.

**Comment by FRASTM** [comment]
I can confirm, it Fixes the https://github.com/zephyrproject-rtos/zephyr/issues/38382

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -451,12 +452,13 @@ static void uart_stm32_poll_out(const struct device *dev,
 {
 	USART_TypeDef *UartInstance = UART_STRUCT(dev);
 
+	/* do not allow system to suspend until transmission has completed */
+	pm_constraint_set(PM_STATE_SUSPEND_TO_IDLE);
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:456]: @ceolin, isn't it possible to have empty `pm_constraint_` definitions when PM is not defined?
This would avoid cluttering the code for such cases

**Review by gmarull — COMMENTED** [review]
@erwango There's still one path that I think needs to be handled: If user disables TX irq (uart_stm32_irq_tx_disable), the constraint will never be released. Should that function just toggle a flag (to avoid callback being fired)?

**Comment by erwango** [comment]
> uart_stm32_irq_tx_disable

Good catch.  So, the use case would be that user would use both `fifo_fill` and `poll_out` on the same device and for some reason (concurrent threads for instance), uart_irq_tx_disable happens during `poll_out` transaction. Seems plausible indeed.

According to API, using a flag is not sufficient " * @brief Disable TX interrupt in IER.".
Though, my feeling is that API is going too much deep into driver implementation, so it should be fine.
I guess that last word on this would be to @dcpleung .

File: drivers/serial/uart_stm32.c [hunk 2]
```diff
@@ -455,7 +456,12 @@ static void uart_stm32_poll_out(const struct device *dev,
 	while (!LL_USART_IsActiveFlag_TXE(UartInstance)) {
 	}
 
+#ifdef CONFIG_PM
+	/* do not allow system to suspend until transmission has completed */
+	pm_constraint_set(PM_STATE_SUSPEND_TO_IDLE);
+#else
 	LL_USART_ClearFlag_TC(UartInstance);
+#endif /* CONFIG_PM */
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:464]: Minor enhancement proposal:
According to RM, use of TC is "to avoid corrupting the last transmission when the USART is
disabled or enters Halt mode.".
Since we're not checking it when PM=n, I think it should be safe removing it completely from here.

Comment (gmarull) [reply drivers/serial/uart_stm32.c]: done

File: drivers/serial/uart_stm32.c [hunk 3]
```diff
@@ -1499,10 +1514,15 @@ static void uart_stm32_irq_config_func_##index(const struct device *dev)	\
...
-#define STM32_UART_IRQ_HANDLER_DECL(index)
+
+#if defined(CONFIG_UART_INTERRUPT_DRIVEN) || defined(CONFIG_UART_ASYNC_API)
+#define STM32_UART_IRQ_HANDLER_FUNC(index)				\
+	.irq_config_func = uart_stm32_irq_config_func_##index,
+#define STM32_UART_POLL_IRQ_HANDLER_FUNC(index)
+#elif defined(CONFIG_PM)
 #define STM32_UART_IRQ_HANDLER_FUNC(index)
-#define STM32_UART_IRQ_HANDLER(index)
+#define STM32_UART_POLL_IRQ_HANDLER_FUNC(index)				\
```
Comment (FRASTM) [inline drivers/serial/uart_stm32.c:1522]: in case the soc (like stm32l476) has no CONFIG_UART_INTERRUPT_DRIVEN, no CONFIG_UART_ASYNC_API, no CONFIG_PM, then the build is raising an error:
`drivers/serial/uart_stm32.c:1547:3: error: implicit declaration of function 'STM32_UART_IRQ_HANDLER_FUNC'; did you mean 'STM32_UART_IRQ_HANDLER_DECL'? [-Werror=implicit-function-declaration]`
--> for example:  _west build -p auto -b nucleo_l476rg `tests/kernel/timer/timer_api/_

Comment (gmarull) [reply drivers/serial/uart_stm32.c:1522]: good catch, should be fixed

**Review by dcpleung — APPROVED** [review]
LGTM. Do you envision a use case where interrupt is totally disabled (e.g. interrupt controller not begin setup at all)? The closest I could think of is a bootloader, but PM is not needed for that.

**Comment by gmarull** [comment]
> LGTM. Do you envision a use case where interrupt is totally disabled (e.g. interrupt controller not begin setup at all)? The closest I could think of is a bootloader, but PM is not needed for that.

A user can call `uart_irq_tx_disable`, however, when PM is enabled we always need to handle TX complete interrupt (to release PM constraint). I assume that when users call `uart_irq_tx_disable` they just expect that the user callback is not fired, am I right?

**Comment by dcpleung** [comment]
> A user can call `uart_irq_tx_disable`, however, when PM is enabled we always need to handle TX complete interrupt (to release PM constraint). I assume that when users call `uart_irq_tx_disable` they just expect that the user callback is not fired, am I right?

Some might actually expects that interrupts to be totally disabled.

Though, what I was thinking was that whether there are any use cases where interrupts are not configured at all at build time. So at runtime, the interrupt controller is not being setup and interrupts not being routed correctly. In this case, you won't get any interrupts at all. However, this is a rather unique use case.

File: drivers/serial/uart_stm32.c (hunk 1 above)
Comment (ceolin) [reply drivers/serial/uart_stm32.c]: https://github.com/zephyrproject-rtos/zephyr/pull/38472

**Review by ceolin — APPROVED** [review]

**Comment by erwango** [comment]
> > A user can call `uart_irq_tx_disable`, however, when PM is enabled we always need to handle TX complete interrupt (to release PM constraint). I assume that when users call `uart_irq_tx_disable` they just expect that the user callback is not fired, am I right?
> 
> Some might actually expects that interrupts to be totally disabled.
> 
> Though, what I was thinking was that whether there are any use cases where interrupts are not configured at all at build time. So at runtime, the interrupt controller is not being setup and interrupts not being routed correctly. In this case, you won't get any interrupts at all. However, this is a rather unique use case.

In case PM is disabled, the poll operations will work w disabled IRQ. I guess this should be sufficient for these specifci cases, right?

File: drivers/serial/uart_stm32.c [hunk 4]
```diff
@@ -455,7 +456,10 @@ static void uart_stm32_poll_out(const struct device *dev,
 	while (!LL_USART_IsActiveFlag_TXE(UartInstance)) {
 	}
 
-	LL_USART_ClearFlag_TC(UartInstance);
+#ifdef CONFIG_PM
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:459]: We should be able to remove these, thanks to https://github.com/zephyrproject-rtos/zephyr/pull/38472

File: drivers/serial/uart_stm32.c [hunk 5]
```diff
@@ -792,16 +803,24 @@ static void uart_stm32_dma_rx_flush(const struct device *dev)
 static void uart_stm32_isr(const struct device *dev)
 {
 	struct uart_stm32_data *data = DEV_DATA(dev);
+	USART_TypeDef *UartInstance = UART_STRUCT(dev);
 
 #ifdef CONFIG_UART_INTERRUPT_DRIVEN
+	if (LL_USART_IsActiveFlag_TC(UartInstance)) {
+		LL_USART_ClearFlag_TC(UartInstance);
+
+#ifdef CONFIG_PM
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:812]: ditto

File: drivers/serial/uart_stm32.c [hunk 6]
```diff
@@ -823,13 +842,29 @@ static void uart_stm32_isr(const struct device *dev)
 		LL_USART_ClearFlag_TC(UartInstance);
 		/* Generate TX_DONE event when transmission is done */
 		async_evt_tx_done(data);
+
+#ifdef CONFIG_PM
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:846]: ditto

File: drivers/serial/uart_stm32.c [hunk 7]
```diff
@@ -1052,6 +1087,11 @@ static int uart_stm32_async_tx(const struct device *dev,
 	/* Start TX timer */
 	async_timer_start(&data->dma_tx.timeout_work, data->dma_tx.timeout);
 
+#ifdef CONFIG_PM
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:1090]: ditto

File: drivers/serial/uart_stm32.c [hunk 8]
```diff
@@ -1501,10 +1516,22 @@ static void uart_stm32_irq_config_func_##index(const struct device *dev)	\
...
+	.irq_config_func = uart_stm32_irq_config_func_##index,
+#define STM32_UART_POLL_IRQ_HANDLER_FUNC(index)
+#elif defined(CONFIG_PM)
+#define STM32_UART_IRQ_HANDLER_FUNC(index)
+#define STM32_UART_POLL_IRQ_HANDLER_FUNC(index)				\
+	.irq_config_func = uart_stm32_irq_config_func_##index,
+#else
+#define STM32_UART_IRQ_HANDLER_FUNC(index)
+#define STM32_UART_POLL_IRQ_HANDLER_FUNC(index)
+#endif
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:1533]: Nitpick (I'm thinking to the ones that will read these lines for the first time)

```suggestion
#if defined(CONFIG_UART_INTERRUPT_DRIVEN) || defined(CONFIG_UART_ASYNC_API)
#define STM32_UART_IRQ_HANDLER_FUNC(index)				\
	.irq_config_func = uart_stm32_irq_config_func_##index,
#define STM32_UART_POLL_IRQ_HANDLER_FUNC(index) /* Not used */
#elif defined(CONFIG_PM)
#define STM32_UART_IRQ_HANDLER_FUNC(index)     /* Not used */
#define STM32_UART_POLL_IRQ_HANDLER_FUNC(index)			\
	.irq_config_func = uart_stm32_irq_config_func_##index,
#else
#define STM32_UART_IRQ_HANDLER_FUNC(index)      /* Not used */
#define STM32_UART_POLL_IRQ_HANDLER_FUNC(index) /* Not used */
#endif
```

Comment (gmarull) [reply drivers/serial/uart_stm32.c]: done

**Comment by gmarull** [comment]
> > > A user can call `uart_irq_tx_disable`, however, when PM is enabled we always need to handle TX complete interrupt (to release PM constraint). I assume that when users call `uart_irq_tx_disable` they just expect that the user callback is not fired, am I right?
> > 
> > 
> > Some might actually expects that interrupts to be totally disabled.
> > Though, what I was thinking was that whether there are any use cases where interrupts are not configured at all at build time. So at runtime, the interrupt controller is not being setup and interrupts not being routed correctly. In this case, you won't get any interrupts at all. However, this is a rather unique use case.
> 
> In case PM is disabled, the poll operations will work w disabled IRQ. I guess this should be sufficient for these specifci cases, right?

The problem only happens if `uart_irq_tx_disable` is called. If `uart_stm32_fifo_fill` is called afterwards, or polling API is used, then PM constraint will not be released. I'm not sure if this path makes sense in practice, though.

**Review by erwango — APPROVED** [review]
LGTM on my side, thanks!
 I let you decide when ready to merge and remove the DNM flag.
