### PR TITLE
net: hostname: Add a function to set the hostname postfix as is

### LINKED ISSUE #72363: The postfix for the hostname is not configured to the desired value
**Describe the bug**
I have enabled hostname configurations and setting postfix, for example "abcd", but not getting this hostname appended, hex value of "abcd" i.e 61626364 is appended to the hostname. Hence the new hostname becomes "zephyr61626364" instead of "zephyrabcd". If I remove the logix of hex conversion then I get desired hostname i.e "zephyrabcd"

Target: STM32U575
Zephyr version: 3.2.0,  Latest version 3.6.0 is also having same code implementation for net_hostname_set_postfix(..)

**One query related to Hostname configuration**:
Can I keep hostname empty like CONFIG_NET_HOSTNAME ="", and set only postfix? What will be the impact?
I tried this and able to use postfix(only) as a hostname.

**To Reproduce**
Enable following configurations

CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME_UNIQUE=y
CONFIG_NET_HOSTNAME="zephyr"
CONFIG_MDNS_RESPONDER=y
CONFIG_MDNS_RESPONDER_LOG_LEVEL_DBG=y
CONFIG_NET_HOSTNAME_LOG_LEVEL_DBG=y

Set postfix in a code:
const uint8_t* postfix_str = (const uint8_t*)"abcd";
reth = net_hostname_set_postfix(postfix_str, strlen((const char*)postfix_str));

**Expected behavior**
Hostname should be "zephyrabcd"

**Impact**
Impact on the user experience who will be using our product, user won't be able to use the actual postfix set by him/her, so could not progress ahead with hex converted postfix.

**Environment:**
 - OS: Windows
 - Toolchain Zephyr SDK zephyr-sdk-0.15.2

### PR DESCRIPTION
**Pull request by VineetaNarkhede-eaton**
Fixes: #72363

The existing function to set the postfix is converting postfix string to hexadecimal. Adding a new function to handle a use case where the provided postfix should be used as is without any conversion.

### CODE REVIEW

File: subsys/net/hostname.c [hunk 1]
```diff
@@ -97,6 +97,39 @@ int net_hostname_set_postfix(const uint8_t *hostname_postfix,
...
+	}
+
+	snprintk(&hostname[net_hostname_len], hostname_len_remain, "%s", hostname_postfix);
+
+	NET_DBG("New Unique hostname: %s", hostname);
+
+#if !defined(CONFIG_NET_HOSTNAME_UNIQUE_UPDATE)
+	postfix_set = true;
+#endif
+
```
Comment (prayassamriya) [inline subsys/net/hostname.c:130]: Do we need to trigger net event like done in other function?
 what is its purpose?

File: subsys/net/hostname.c
Comment (MarkVerheyen-eaton) [inline subsys/net/hostname.c:1]: We need the associated documentation with this. What does it do, why does it do it, how do we use it?

File: subsys/net/hostname.c (hunk 1 above)
Comment (VineetaNarkhede-eaton) [reply subsys/net/hostname.c]: trigger_net_event() is to trigger the event upon hostname change. Added the same into new function.

File: subsys/net/hostname.c
Comment (VineetaNarkhede-eaton) [reply subsys/net/hostname.c:1]: Updated the readme file and header file.

File: include/zephyr/net/hostname.h [hunk 2]
```diff
@@ -108,8 +109,31 @@ int net_hostname_set_postfix(const uint8_t *hostname_postfix,
 static inline int net_hostname_set_postfix(const uint8_t *hostname_postfix,
 					   int postfix_len)
 {
-	ARG_UNUSED(hostname_postfix);
```
Comment (rlubos) [inline include/zephyr/net/hostname.h:111]: Please don't remove `ARG_UNUSED()` macros here. And add them to the new function too.

**Comment by rlubos** [comment]
Regarding the compliance report:
```
5b9cdbb0a5569f494a6256000a28755f31005bd6: author email (vineeta <vineetasnarkhede@eaton.com>) needs to match one of the signed-off-by entries.
5b9cdbb0a5569f494a6256000a28755f31005bd6: author email (vineeta <vineetasnarkhede@eaton.com>) does not follow the syntax: First Last <email>.
```
You likely need to update your user.name and user.email git configs, and update the commit (`git commit --amend --reset-author`). They need to match the ones in the signoff entry.

There are also some trailing spaces, see the report.

File: include/zephyr/net/hostname.h (hunk 2 above)
Comment (VineetaNarkhede-eaton) [reply include/zephyr/net/hostname.h]: Fixed.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by VineetaNarkhede-eaton** [comment]
@rlubos @jukkar Could you please help me to merge the PR.

**Comment by rlubos** [comment]
@VineetaNarkhede-eaton We're in a feature freeze, this will be merged after 3.7 release.
