### PR TITLE
drivers: wifi: eswifi: fix casts for 64 bit pointers

### LINKED ISSUE #80242: tests/drivers/build_all/wifi fails on `native_sim/native/64`
**Describe the bug**
The WiFi driver build all test added in #79145 is failing to build on `native_sim/native/64`, due to some issues regarding 64 bit versus 32 bit pointers in the `eswifi` driver.

**To Reproduce**
1. `west build -p -b native_sim/native/64 tests/drivers/build_all/wifi -T drivers.wifi.build.uart`
2. See build warning (upgraded to error in CI)

**Expected behavior**
The build should pass without warnings

**Impact**
Blocking CI on #72102

**Logs and console output**
```
[118/162] Building C object zephyr/drivers/wifi/CM...ivers__wifi.dir/eswifi/eswifi_socket_offload.c.obj
/home/danieldegrasse/zephyr/zephyrproject/zephyr/drivers/wifi/eswifi/eswifi_socket_offload.c: In function ‘eswifi_socket_connect’:
/home/danieldegrasse/zephyr/zephyrproject/zephyr/drivers/wifi/eswifi/eswifi_socket_offload.c:31:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   31 | #define OBJ_TO_SD(obj) (((int)obj) - 1)
      |                          ^
/home/danieldegrasse/zephyr/zephyrproject/zephyr/drivers/wifi/eswifi/eswifi_socket_offload.c:58:20: note: in expansion of macro ‘OBJ_TO_SD’
   58 |         int sock = OBJ_TO_SD(obj);
      |                    ^~~~~~~~~
/home/danieldegrasse/zephyr/zephyrproject/zephyr/drivers/wifi/eswifi/eswifi_socket_offload.c: In function ‘eswifi_socket_listen’:
/home/danieldegrasse/zephyr/zephyrproject/zephyr/drivers/wifi/eswifi/eswifi_socket_offload.c:31:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   31 | #define OBJ_TO_SD(obj) (((int)obj) - 1)
```
Several similar warnings are present in the file.

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04 LTS
 - Toolchain: `zephyr-sdk-0.17.0-rc1`
 - Commit SHA or Version used 6e653a96f7903f (main)

### PR DESCRIPTION
**Pull request by danieldegrasse**
The eswifi driver uses an integer to identify the socket used for each connection, which must be cast to and from a `void *`. This causes warnings on 64 bit platforms, as precision is lost when casting from a `void *` to `int`. Use a `uintptr_t` type to store the socket value to resolve this warning. Also, fix a function signature for the `accept_cb` to use `size_t` instead of `int` for the length

Fixes #80242

### CODE REVIEW

File: drivers/wifi/eswifi/eswifi_socket_offload.c [hunk 1]
```diff
@@ -582,7 +583,7 @@ static bool eswifi_socket_is_supported(int family, int type, int proto)
 int eswifi_socket_create(int family, int type, int proto)
 {
 	int fd = zvfs_reserve_fd();
-	int sock;
+	uintptr_t sock;
```
Comment (jukkar) [inline drivers/wifi/eswifi/eswifi_socket_offload.c:586]: Shouldn't this be `intptr_t` as the value can be negative?

Comment (danieldegrasse) [reply drivers/wifi/eswifi/eswifi_socket_offload.c:586]: Yes it should be- let me fix this

**Review by jukkar — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
