### PR TITLE
Bluetooth: Host: GATT Delayed Store Fix

### LINKED ISSUE #58272: Bluetooth: Host: GATT delayed store flush on disconnect is broken
**Describe the bug**

When `CONFIG_BT_SETTINGS_DELAYED_STORE` (default `=y`) is enabled, the local GATT server will delay the write to flash of CCC and CF values. Write will be done in a work queue. At disconnection, `bt_gatt_disconnected` will be called and will try to reschedule the delayed store of the CCC and the CF for right now. 
The problem is that the `bt_gatt_disconnected` function is already in a workqueue context. This mean that the delayed store will be executed when `bt_gatt_disconnected` complete. At this moment, the CCC and CF values will have been already cleared. When the delayed store will look for value to store, it will find nothing.

**To Reproduce**

Will update with a test to reproduce.

**Impact**

CCC and CF are not stored, and thus cannot be retrieve between connection/disconnection of bonded peers.

### PR DESCRIPTION
**Pull request by theob-pro**
See commits message.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/58272

### CODE REVIEW

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1438,6 +1438,27 @@ static void gatt_delayed_store_enqueue(uint8_t id, const bt_addr_le_t *peer_addr
 	}
 }
 
+static void do_delayed_store(uint8_t id, const bt_addr_le_t *peer_addr)
```
Comment (hermabe) [inline subsys/bluetooth/host/gatt.c:1441]: Could `do_delayed_store` take `struct ds_peer *el` directly instead of `id and `peer_addr`? It seems like some work is done twice here to find `el`.

Comment (theob-pro) [reply subsys/bluetooth/host/gatt.c:1441]: Yes, I have done that because I would like to remove the condition on `CONFIG_BT_SETTINGS_DELAYED_STORE` in `bt_gatt_disconnected` and only use `do_delayed_store`. It's for a future work, I can use a `struct ds_peer *el` for now if you want.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -1438,6 +1438,27 @@ static void gatt_delayed_store_enqueue(uint8_t id, const bt_addr_le_t *peer_addr
...
+{
+	struct ds_peer *el = gatt_delayed_store_find(id, peer_addr);
+
+	if (bt_addr_le_is_bonded(id, peer_addr)) {
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:1445]: Does it make sense to "just store what you promised to store"? I don't think checking if the peer is bonded serves any purpose here. If the peer has become un-bonded, the write-back cache "delayed store" should have been updated accordingly.

```suggestion
	if (el) {
```

Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:1445]: I would like a local test that `el` is not NULL.

```suggestion
	if (el && bt_addr_le_is_bonded(id, peer_addr)) {
```

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (hermabe) [reply subsys/bluetooth/host/gatt.c:1441]: If you are planning to change things here anyway you can keep it as is.

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]
