### PR TITLE
tests: canbus: isotp: conformance: skip stmin test on low tick Hz

### LINKED ISSUE #54254: tests: canbus: isotp: conformance: test fails with CONFIG_SYS_CLOCK_TICKS_PER_SEC=100
**Describe the bug**
The CAN ISO-TP conformance test expects to receive a frame within STmin (5 msec) + upper tolerance (5msec) = 10msec. The expectation fails when `CONFIG_SYS_CLOCK_TICKS_PER_SEC=100` or below. If the timeout is bumped to 11msec, the test passes even with `CONFIG_SYS_CLOCK_TICKS_PER_SEC=100`.

` CONFIG_SYS_CLOCK_TICKS_PER_SEC=100` is default for non-tickles capable system timers (e.g. the `LPTMR` used on the `twr_ke18f` board by default) and on emulation platforms (e.g. `native_posix` and `native_posix_64`).

**To Reproduce**
1. `west build -p -t run -b native_posix_64 tests/subsys/canbus/isotp/conformance/`
2. See error:
```

[00:00:00.000,000] <inf> can_loopback: Init of can_loopback0 done
*** Booting Zephyr OS build v3.3.0-rc1-30-gfb0802a5b667 ***
Running TESTSUITE isotp_conformance
===================================================================
START - test_receive_data
 PASS - test_receive_data in 0.270 seconds
===================================================================
START - test_receive_data_blocks
 PASS - test_receive_data_blocks in 1.170 seconds
===================================================================
START - test_receive_sf
 PASS - test_receive_sf in 0.000 seconds
===================================================================
START - test_receive_sf_ext
 PASS - test_receive_sf_ext in 0.000 seconds
===================================================================
START - test_receive_sf_fixed
 PASS - test_receive_sf_fixed in 0.210 seconds
===================================================================
START - test_receive_timeouts
[00:00:02.660,000] <err> isotp: Timeout while waiting for CF
 PASS - test_receive_timeouts in 1.010 seconds
===================================================================
START - test_receiver_fc_errors
[00:00:02.870,000] <err> isotp: Sequence number mismatch
[00:00:02.870,000] <inf> isotp: Got unexpected frame. Ignore
[00:00:02.870,000] <inf> isotp: Got unexpected frame. Ignore
[00:00:02.870,000] <inf> isotp: Got unexpected frame. Ignore
[00:00:02.870,000] <inf> isotp: Got unexpected frame. Ignore
[00:00:02.870,000] <inf> isotp: Got unexpected frame. Ignore
[00:00:02.870,000] <inf> isotp: Got unexpected frame. Ignore
 PASS - test_receiver_fc_errors in 0.420 seconds
===================================================================
START - test_send_data
 PASS - test_send_data in 0.420 seconds
===================================================================
START - test_send_data_blocks
 PASS - test_send_data_blocks in 1.020 seconds
===================================================================
START - test_send_sf
 PASS - test_send_sf in 0.210 seconds
===================================================================
START - test_send_sf_ext
 PASS - test_send_sf_ext in 0.210 seconds
===================================================================
START - test_send_sf_fixed
 PASS - test_send_sf_fixed in 0.210 seconds
===================================================================
START - test_send_timeouts
[00:00:06.160,000] <err> isotp: Reception of next FC has timed out
[00:00:07.170,000] <err> isotp: Reception of next FC has timed out
[00:00:08.990,000] <err> isotp: Reception of next FC has timed out
 PASS - test_send_timeouts in 3.840 seconds
===================================================================
START - test_sender_fc_errors
[00:00:09.200,000] <err> isotp: Pkt length is 5118 but buffer has only 768 bytes
[00:00:09.200,000] <err> isotp: Got overflow FC frame
[00:00:09.410,000] <err> isotp: Got overflow FC frame
[00:00:09.620,000] <inf> isotp: Got to many wait frames
 PASS - test_sender_fc_errors in 0.630 seconds
===================================================================
START - test_stmin

    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/canbus/isotp/conformance/src/main.c:818: isotp_conformance_test_stmin: (ret not equal to 0)
Expected to get a message within 10ms. [-11]
 FAIL - test_stmin in 0.230 seconds
===================================================================
TESTSUITE isotp_conformance failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  93.33% [isotp_conformance]: pass = 14, fail = 1, skip = 0, total = 15 duration = 9.850 seconds
 - PASS - [isotp_conformance.test_receive_data] duration = 0.270 seconds
 - PASS - [isotp_conformance.test_receive_data_blocks] duration = 1.170 seconds
 - PASS - [isotp_conformance.test_receive_sf] duration = 0.000 seconds
 - PASS - [isotp_conformance.test_receive_sf_ext] duration = 0.000 seconds
 - PASS - [isotp_conformance.test_receive_sf_fixed] duration = 0.210 seconds
 - PASS - [isotp_conformance.test_receive_timeouts] duration = 1.010 seconds
 - PASS - [isotp_conformance.test_receiver_fc_errors] duration = 0.420 seconds
 - PASS - [isotp_conformance.test_send_data] duration = 0.420 seconds
 - PASS - [isotp_conformance.test_send_data_blocks] duration = 1.020 seconds
 - PASS - [isotp_conformance.test_send_sf] duration = 0.210 seconds
 - PASS - [isotp_conformance.test_send_sf_ext] duration = 0.210 seconds
 - PASS - [isotp_conformance.test_send_sf_fixed] duration = 0.210 seconds
 - PASS - [isotp_conformance.test_send_timeouts] duration = 3.840 seconds
 - PASS - [isotp_conformance.test_sender_fc_errors] duration = 0.630 seconds
 - FAIL - [isotp_conformance.test_stmin] duration = 0.230 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED
```

**Expected behavior**
The test case works with `CONFIG_SYS_CLOCK_TICKS_PER_SEC=100`.

**Impact**
Failing tests.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.15.2
 - Commit SHA: fb0802a5b667035204159957f27d27c12f966e2a

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
The CAN ISO-TP conformance test expects to receive a frame within STmin (5 msec) + upper tolerance (5msec) = 10msec. The expectation fails when `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is too low.
    
Skip the STmin test case to allow the test suite to succeed on non-tickless and emulation platforms, where `CONFIG_SYS_CLOCK_TICKS_PER_SEC` defaults to `100`. Enable the tests for `native_posix` and `native_posix_64`.

Fixes: #54254

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Review by alexanderwachter — DISMISSED** [review]

File: tests/subsys/canbus/isotp/conformance/src/main.c [hunk 1]
```diff
@@ -813,7 +813,7 @@ ZTEST(isotp_conformance, test_stmin)
 
 	start_time = k_uptime_get_32();
 	ret = k_msgq_get(&frame_msgq, &raw_frame,
-			 K_MSEC(STMIN_VAL_1 + STMIN_UPPER_TOLERANCE));
+			 K_TICKS(k_ms_to_cyc_ceil32(STMIN_VAL_1 + STMIN_UPPER_TOLERANCE)));
```
Comment (martinjaeger) [inline tests/subsys/canbus/isotp/conformance/src/main.c:816]: Not entirely sure if I got this right, but it looks like `k_ms_to_cyc_ceil32` returns hardware cycles, which are configured as `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=1000000` for `native_posix`. However, `K_TICKS` expects system clock ticks, which are based on [`SYS_CLOCK_TICKS_PER_SEC`](https://github.com/zephyrproject-rtos/zephyr/blob/63850804f167353df27b6b33d05f8f3ab642aae4/kernel/Kconfig#L614) and default to `100` for `native_posix`. Thus, `K_TICKS` will get a comparably huge number and not time out anymore.

Using `k_ms_to_ticks_ceil32` should lead to the same result as `K_MSEC` as far as I can see, so it would not fix the problem.

Maybe increasing `CONFIG_SYS_CLOCK_TICKS_PER_SEC` as done in [samples/bluetooth/unicast_audio_client](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/unicast_audio_client/boards/native_posix.conf) would be more appropriate?

Comment (henrikbrixandersen) [reply tests/subsys/canbus/isotp/conformance/src/main.c]: Thanks. I have changed it to `CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000` as per our conversations in Discord. I have put this PR back in draft state until I have had a chance to run the branch on our CAN board test farm.

File: tests/subsys/canbus/isotp/conformance/prj.conf [hunk 2]
```diff
@@ -7,3 +7,5 @@ CONFIG_ISOTP_ENABLE_CONTEXT_BUFFERS=y
 CONFIG_ISOTP_RX_BUF_COUNT=6
 CONFIG_ISOTP_RX_BUF_SIZE=128
 CONFIG_ISOTP_RX_SF_FF_BUF_COUNT=2
+# These tests require millisecond tick resolution
+CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
```
Comment (martinjaeger) [inline tests/subsys/canbus/isotp/conformance/prj.conf:11]: This will lead to problems with nordic MCUs, which run their sys clock on the RTC crystal with `CONFIG_SYS_CLOCK_TICKS_PER_SEC=32768`. Probably this setting should be changed only for `native_posix[64]` boards.

Comment (henrikbrixandersen) [reply tests/subsys/canbus/isotp/conformance/prj.conf:11]: I agree. Having to set this for a test suite is not optimal. However, it needs to be set for not only `native_posix` and `native_posix_64`, but also all non-tickless system timers as they default to 100Hz tick as well.

Comment (henrikbrixandersen) [reply tests/subsys/canbus/isotp/conformance/prj.conf]: @martinjaeger Instead of changing the tick frequency for this test suite I have opted to just skip the STmin test if `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is too low. Please re-review.

**Review by martinjaeger — APPROVED** [review]

File: tests/subsys/canbus/isotp/conformance/prj.conf (hunk 2 above)
Comment (martinjaeger) [reply tests/subsys/canbus/isotp/conformance/prj.conf]: That's also a clean solution. Thanks.

**Review by fabiobaltieri — APPROVED** [review]
