### PR TITLE
Bluetooth: Host: Fix wrong ID being stored

### LINKED ISSUE #55723: Bluetooth: Host: ID: bt_id_create API fails to store the created identity in Settings under certain conditions
**Describe the bug**
The ```bt_id_create``` API fails to store the created identity in the Settings storage partitions under certain conditions.

The settings storage operation is scheduled within the ```bt_id_create``` API with the ```k_work_submit``` API, and then the Bluetooth identity counter (`bt_dev.id_count`) is incremented. The issue occurs when the ```bt_id_create``` API is called in the execution context, which has a lower priority than the work queue context. In this case, the scheduled storage operation interrupts the ```bt_id_create``` context and stores the Bluetooth identity item in Settings using the outdated value of the Bluetooth identity counter (`bt_dev.id_count`). As a result, the newly created Bluetooth identity is not stored by the Settings subsystem.

The regression was probably introduced in the following PR: https://github.com/zephyrproject-rtos/zephyr/pull/51329/commits/ff9168b8ea6b592a5e7b60a51214b218fb69eb11 (https://github.com/zephyrproject-rtos/zephyr/pull/51329/).
In the linked PR, incrementing order of the ```bt_dev.id_count``` variable was changed.

I think we should also consider simplifying the ```bt_id_create``` API and perform the Bluetooth Identity storage operation within the same context (without using the workqueue context). Other APIs, like ```bt_id_reset```, already perform the settings operation like bond removal (```bt_unpair```) without switching to the workqueue context.

**To Reproduce**
You can use the modified Zephyr Bluetooth Peripheral HR sample to reproduce this issue:

1. Extend the project configuration file `prj.conf` with the following entries:
```
CONFIG_BT_ID_MAX=2

CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y

# Increased stack due to settings API usage
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
```

2. Add additional code to the main.c to create a new Bluetooth identity:

```
static int app_bt_id_create(uint8_t id)
{
	int ret;
	bt_addr_le_t addrs[CONFIG_BT_ID_MAX];
	size_t count = ARRAY_SIZE(addrs);

	/* Check if the new app identity wasn't already created. */
	bt_id_get(addrs, &count);
	if (id < count) {
		return 0;
	}

	/* Create the new app identity. */
	do {
		ret = bt_id_create(NULL, NULL);
		if (ret < 0) {
			return ret;
		}
	} while (ret != id);

	return 0;
}

#include <zephyr/settings/settings.h>

static void bt_ready(void)
{
	int err;
	size_t bt_id_count;

	err = settings_load();
	if (err) {
		printk("Settings load failed (err: %d)\n", err);
		return;
	} else {
		printk("Settings loaded\n");
	}

	bt_id_get(NULL, &bt_id_count);
	printk("Number of BT identities after settings_load: %d\n", bt_id_count);

	err = app_bt_id_create(1);
	if (err) {
		printk("Advertising failed to start (err %d)\n", err);
		return;
	}

	bt_id_get(NULL, &bt_id_count);
	printk("Number of BT identities after ID creation: %d\n", bt_id_count);

       (...)
```
3. Build and flash the sample using the following commands (the nRF52840 target is used as an example):
```
west build -b nrf52840dk_nrf52840
nrfjprog -e
west flash
```
4. Observe the logs from the first sample run.
5. Reset the target and observe the logs from the subsequent sample runs.

You can use the following commit to setup the reproduction context: https://github.com/kapi-no/zephyr/commit/c0ee6e162f537fc4bb3f0fc89951e7c14ead7ff3

**Expected behavior**
The created Bluetooth identity should be correctly stored in the Settings regardless of the execution context in which the ```bt_id_create``` is called.

**Impact**
Configuration of the last Bluetooth identity is not preserved between system reboots.

**Logs and console output**

Log output from the first run of the Peripheral HR sample (with the  erased Settings portion):
```
*** Booting Zephyr OS build zephyr-v3.3.0-1046-gc0ee6e162f53 ***
[00:00:00.392,395] <inf> fs_nvs: nvs_mount: 8 Sectors of 4096 bytes
[00:00:00.392,395] <inf> fs_nvs: nvs_mount: alloc wra: 0, fe8
[00:00:00.392,425] <inf> fs_nvs: nvs_mount: data wra: 0, 0
[00:00:00.393,951] <inf> bt_hci_core: hci_vs_init: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.393,981] <inf> bt_hci_core: hci_vs_init: HW Variant: nRF52x (0x0002)
[00:00:00.394,012] <inf> bt_hci_core: hci_vs_init: Firmware: Standard Bluetooth controller (0x00) Version 3.3 Build 99
[00:00:00.394,378] <inf> bt_hci_core: bt_init: No ID address. App must call settings_load()
[00:00:00.394,744] <inf> bt_hci_core: bt_dev_show_info: Identity: F1:12:25:B3:B7:2E (random)
[00:00:00.394,775] <inf> bt_hci_core: bt_dev_show_info: HCI: version 5.4 (0x0d) revision 0x0000, manufacturer 0x05f1
[00:00:00.394,805] <inf> bt_hci_core: bt_dev_show_info: LMP: version 5.4 (0x0d) subver 0xffff
Settings loaded
Number of BT identities after settings_load: 1
[00:00:00.410,888] <inf> bt_settings: save_id: Saving ID
Number of BT identities after ID creation: 2
Bluetooth initialized
Advertising successfully started
```

Log output from the subsequent runs of the Peripheral HR sample:
```
*** Booting Zephyr OS build zephyr-v3.3.0-1046-gc0ee6e162f53 ***
[00:00:00.258,117] <inf> fs_nvs: nvs_mount: 8 Sectors of 4096 bytes
[00:00:00.258,148] <inf> fs_nvs: nvs_mount: alloc wra: 0, fb8
[00:00:00.258,148] <inf> fs_nvs: nvs_mount: data wra: 0, 30
[00:00:00.259,704] <inf> bt_hci_core: hci_vs_init: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.259,735] <inf> bt_hci_core: hci_vs_init: HW Variant: nRF52x (0x0002)
[00:00:00.259,765] <inf> bt_hci_core: hci_vs_init: Firmware: Standard Bluetooth controller (0x00) Version 3.3 Build 99
[00:00:00.260,101] <inf> bt_hci_core: bt_init: No ID address. App must call settings_load()
[00:00:00.260,498] <inf> bt_hci_core: bt_dev_show_info: Identity: F1:12:25:B3:B7:2E (random)
[00:00:00.260,528] <inf> bt_hci_core: bt_dev_show_info: HCI: version 5.4 (0x0d) revision 0x0000, manufacturer 0x05f1
[00:00:00.260,589] <inf> bt_hci_core: bt_dev_show_info: LMP: version 5.4 (0x0d) subver 0xffff
Settings loaded
Number of BT identities after settings_load: 1
[00:00:00.263,153] <inf> bt_settings: save_id: Saving ID
Number of BT identities after ID creation: 2
Bluetooth initialized
Advertising successfully started
```
(Number of BT identities should be 2 after ```settings_load``` API call.)

**Environment (please complete the following information):**
 - Commit SHA (the Zephyr main branch): https://github.com/zephyrproject-rtos/zephyr/commit/139fa8292a9cb91312cb4f9fc3d43d97683db3e6

### PR DESCRIPTION
**Pull request by theob-pro**
See commits message.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/55723

### CODE REVIEW

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/id.c [hunk 1]
```diff
@@ -1273,12 +1273,11 @@ int bt_id_create(bt_addr_le_t *addr, uint8_t *irk)
 		}
 	}
 
-	new_id = bt_dev.id_count;
+	new_id = bt_dev.id_count++;
 	err = id_create(new_id, addr, irk);
 	if (err) {
+		bt_dev.id_count--;
```
Comment (carlescufi) [inline subsys/bluetooth/host/id.c:1279]: So `id_create()` calls a function that uses `bt_dev.id_count` instead of `new_id` @theob-pro ?

Comment (theob-pro) [reply subsys/bluetooth/host/id.c:1279]: `id_create()` will call `bt_settings_save_id()`, which will use the number of identity (`bt_dev.id_count`) to store the settings. `new_id` is the value of the new ID we want to create, the value is `bt_dev.id_count` before the creation of this new ID.
So it's not an error that `bt_settings_save_id()` use `bt_dev.id_count` instead of `new_id`.

File: tests/bsim/bluetooth/host/id/settings/test_scripts/settings.sh [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+if [ "${1}" != 'debug2' ]; then
+  Execute "./${test_exe}" \
+    -v=${verbosity_level} -s=${simulation_id} -d=1 -testid=dut2 \
+    -flash="${simulation_id}.log.bin" -flash_rm
+fi
+
+Execute ./bs_2G4_phy_v1 -v=${verbosity_level} -s=${simulation_id} \
+  -D=2 -sim_length=60e6
+
+if [ "${1}" == 'debug1' ]; then
```
Comment (aescolar) [inline tests/bsim/bluetooth/host/id/settings/test_scripts/settings.sh:30]: I will not reject the PR based on this, this is just a comment:
It seems like if you are debugging, and you are ok with setting a parameter for the script, you would probably be ok with just modifying this line in the script anyhow.

You can expect others will run the debugger from the IDE directly or in other ways, and that they will not expect about this option so adding all this `if != / == debug` does not really seem to add value for others, as much as be left overs from development. => I would remove them.

File: tests/bsim/bluetooth/host/id/settings/test_scripts/settings.sh [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+simulation_id="id_${test_name}"
+verbosity_level=2
+EXECUTE_TIMEOUT=30
+
+cd ${BSIM_OUT_PATH}/bin
+
+if [ "${1}" != 'debug1' ]; then
+  Execute "./${test_exe}" \
+    -v=${verbosity_level} -s=${simulation_id} -d=0 -testid=dut1 \
+    -flash="${simulation_id}.log.bin"
```
Comment (aescolar) [inline tests/bsim/bluetooth/host/id/settings/test_scripts/settings.sh:18]: Both devices are using the same flash file. That sounds like trouble..
There is also no file to start with, so you may just want to keep the flash content in RAM?

**Review by aescolar — DISMISSED** [review]

**Comment by aescolar** [comment]
Another request: These commits first add the test and then the fix. It would be much nicer to do it in the opposite order so main is kept bisectable.

File: tests/bsim/bluetooth/host/id/settings/prj.conf [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+
+CONFIG_FLASH=y
+CONFIG_FLASH_PAGE_LAYOUT=y
+CONFIG_FLASH_MAP=y
+CONFIG_NVS=y
+CONFIG_SETTINGS=y
+CONFIG_BT_SETTINGS=y
+
+# Increased stack due to settings API usage
+CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
```
[the remark this answers is not in the document]
Comment (theob-pro) [reply tests/bsim/bluetooth/host/id/settings/prj.conf:17]: Tests may be use as example by users discovering the project, I think it's better to keep that option if it is needed on real hardware.

File: tests/bsim/bluetooth/host/id/settings/test_scripts/settings.sh (hunk 3 above)
Comment (theob-pro) [reply tests/bsim/bluetooth/host/id/settings/test_scripts/settings.sh]: That's on purpose, I am testing that the settings stored are correct. To do that I simulate a device restart with a second device starting when the first one completed its work.
Tell me if I am wrong, but if I use the settings in RAM, I can't share the settings between devices.

File: subsys/bluetooth/host/id.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/id.c:1279]: @carlescufi I explained it to myself like this: `id_create` takes a specific `new_id`. It is the responsibility of the caller to allocate an id number. `bt_dev.id_count++` is the allocation. `bt_dev.id_count--` is the corresponding de-allocation.

File: tests/bsim/bluetooth/host/id/settings/test_scripts/settings.sh (hunk 3 above)
Comment (aescolar) [reply tests/bsim/bluetooth/host/id/settings/test_scripts/settings.sh]: I see, the problem is that what you are doing it works when things align well enough. Meaning:
Both devices execute simultaneously, and both race to open the flash storage file.
During initialization, the NVMC model, if the file did not exist, or had zero size, will resize it to the correct size and clear it (to 0xFF).
In principle in between the opening of the file, and the check of its size, and the clearing of the content, the other device may have raced ahead of the other. Meaning, one device may open a file that is nonexistant / empty / right size but not cleared / partially cleared/ already contains settings. And the state is changing under its feet as things go. And one device may clear the content after the other one started writing settings to it.

If you know device 2 is the one reading the settings, and that device 1 will have written its settings in less than x ms, you can postpone the boot of device 2 by that amount to ensure the file is already created and its settings written.
But for that to work you would really need to hope that neither 1 or 2 modify the content anymore after.

**Comment by aescolar** [comment]
> Isn't it correct that bisecting will find a failure at the commit before the fix? After all, the bug did exist on master. I don't agree that this breaks bisecting.

When bisecting you are searching for the origin of a currently existing bug, and trying to find when it was introduced. You don't want to have spurious failures due to bugs which were fixed pop up in the middle of the bisect.

**Comment by alwa-nordic** [comment]
> > Isn't it correct that bisecting will find a failure at the commit before the fix? After all, the bug did exist on master. I don't agree that this breaks bisecting.
> 
> When bisecting you are searching for the origin of a currently existing bug, and trying to find when it was introduced. You don't want to have spurious failures due to bugs which were fixed pop up in the middle of the bisect.

This answer ignores most of my comment. I think there is a real convenience to be had for those who want to do TDD. And I can't think of a realistic scenario of bisect failing due if the test is added before the fix. It simply does not matter; Realistically, you don't bisect using the entire test suite (since that takes several hours to run). You bisect with some specific test that had a regression from passing to failing.

**Review by aescolar — DISMISSED** [review]
-1 due to https://github.com/zephyrproject-rtos/zephyr/pull/59260#discussion_r1231079435
Let's try to clarify that

**Review by aescolar — COMMENTED** [review]
+1 for the test

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
