### PR TITLE
ARC: boards: hsdk: fix cy8c95xx I2C GPIO port init

### LINKED ISSUE #54241: The cy8c95xx I2C GPIO expander support was broken in #47841
**Describe the bug**

The cy8c95xx I2C GPIO expander support was broken in commit https://github.com/zephyrproject-rtos/zephyr/commit/4b30008f5b72fdb292a065ea67ef91e11d23fefe in #47841 PR. I can observe this issue when this I2C GPIO expander is connected to DW I2C controller (I haven't tried it with other I2C controllers due to the lack of such HW).

Currently we can see error messages during boot time:

```
E: cy8c95xx_port@1 init failed: -5
E: cy8c95xx_port@0 init failed: -5
*** Booting Zephyr OS build v3.3.0-rc1-5-gef9d5bbddfa5 ***
```

If we try to use GPIO's from this expander we'll get error that they are not ready.

**To Reproduce**
Build Zephyr from current main ([ef9d5bb](https://github.com/zephyrproject-rtos/zephyr/commit/ef9d5bbddfa53ac5636437df8c4e720aaff974d5)) for the `hsdk`  board. It can be reproduced with both GNU toolchain (i.e: from Zephyr SDK 0.15.0) and MWDT (2022.09).

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.15.0
 - Commit SHA used for test: ef9d5bbddfa53ac5636437df8c4e720aaff974d5
 - Bisected commit: 4b30008f5b72fdb292a065ea67ef91e11d23fefe

### PR DESCRIPTION
**Pull request by SiyuanCheng-CN**
cy8c95xx I2C GPIO support was broken in commit 4b30008 due to wrong i2c bus and address were wrote during GPIO_PORT_INIT.

Fixes: #54241

### CODE REVIEW

**Review by abrodkin — DISMISSED** [review]

**Review by evgeniy-paltsev — DISMISSED** [review]

**Review by ruuddw — COMMENTED** [review]
Not sure if this is the way it is supposed to work with the hardcoded `cypress_cy8c95xx_gpio` instead of the `#define DT_DRV_COMPAT cypress_cy8c95xx_gpio_port` at the top, but if this works it is probably ok if there is no better way to retrieve the I2C bus parent of the port.

File: drivers/gpio/gpio_cy8c95xx.c [hunk 1]
```diff
@@ -287,7 +287,7 @@ static const struct cy8c95xx_config cy8c95xx_##idx##_cfg = { \
 	.common = { \
 		.port_pin_mask = 0xFF, \
 	}, \
-	.i2c = I2C_DT_SPEC_INST_GET(idx), \
+	.i2c = I2C_DT_SPEC_GET(DT_INST(0, cypress_cy8c95xx_gpio)), \
```
Comment (fabiobaltieri) [inline drivers/gpio/gpio_cy8c95xx.c:290]: Well but then you'd always get the device 0 address and can't support multiple devices with different addresses. How about `.i2c = I2C_DT_SPEC_GET(DT_PARENT(DT_INST(idx, DT_DRV_COMPAT))),`?

**Review by ruuddw — CHANGES_REQUESTED** [review]
See fabio's suggestion, thanks!

File: drivers/gpio/gpio_cy8c95xx.c (hunk 1 above)
Comment (SiyuanCheng-CN) [reply drivers/gpio/gpio_cy8c95xx.c]: Thanks for the review!

**Review by ruuddw — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by evgeniy-paltsev — APPROVED** [review]

**Review by abrodkin — APPROVED** [review]
