### PR TITLE
drivers: clock control: stm32U5 set regulator voltage before clocks

### LINKED ISSUE #48081: tests/drivers/clock_control/stm32_clock_configuration/stm32u5_core not working with msis 48
**Describe the bug**
Unit test "tests/drivers/clock_control/stm32_clock_configuration/stm32u5_core" not working with clock msis 48MHz
Not working means that core doesn't even start. No zephyr banner.
Info : Example with overlay pll are working.

**To Reproduce**
1. west build -b b_u585i_iot02a tests/drivers/clock_control/stm32_clock_configuration/stm32u5_core/ -DDTC_OVERLAY_FILE="boards/clear_clocks.overlay;boards/msis_48.overlay" -p
2. west flash
3. See MCU not starting

**Impact**
stm32u5 does not start if we choose to use msis as clock

**Environment**
 - OS: ubuntu 20.04 running on WSL2
 - Toolchain : Zephyr SDK 0.13.1
 - Commit SHA : b7f1e9872495ee29d223cd7b5c2f8fb5eceab2cd

### PR DESCRIPTION
**Pull request by FRASTM**
The regulator voltage should be set before the clocks are enabled
This is especially the case when the MSIS at 48MHz is selected as
SYSCLK.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/48081

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
testing  `tests/drivers/clock_control/stm32_clock_configuration/stm32u5_core` on b_u585i_IOT02a disco kit :
```
drivers.stm32_clock_configuration.u5.sysclksrc_pll_msis_160 : PASSED
drivers.stm32_clock_configuration.u5.pll_msis_ahb_2_40 : PASSED
drivers.stm32_clock_configuration.u5.sysclksrc_pll_hsi_160 : PASSED
drivers.stm32_clock_configuration.u5.sysclksrc_pll_hsi_40 : PASSED
drivers.stm32_clock_configuration.u5.sysclksrc_msis_48 : PASSED
drivers.stm32_clock_configuration.u5.sysclksrc_msis_24 : PASSED
```

**Review by erwango — DISMISSED** [review]

File: drivers/clock_control/clock_stm32_ll_u5.c [hunk 1]
```diff
@@ -561,9 +564,6 @@ int stm32_clock_control_init(const struct device *dev)
 		return r;
 	}
 
-	/* Set voltage regulator to comply with targeted system frequency */
-	set_regu_voltage(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC);
-
 	/* Set flash latency */
 	/* If freq increases, set flash latency before any clock setting */
```
Comment (str4t0m) [inline drivers/clock_control/clock_stm32_ll_u5.c:568]: I believe the configuration of the flash latency, in case old < new, should be moved up as well.

**Review by str4t0m — CHANGES_REQUESTED** [review]

File: drivers/clock_control/clock_stm32_ll_u5.c (hunk 1 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_u5.c:568]: OK, to set flash latentcy before _any_ clock setting
(the refMan says to "Adjust number of wait states according new frequency" before the PLL config.)

**Review by str4t0m — APPROVED** [review]
Thanks

**Review by erwango — APPROVED** [review]
