### PR TITLE
tests: smp: correct the inappropriate testcase

### LINKED ISSUE #35200: tests/kernel/smp failed on hsdk board
**Describe the bug**
tests/kernel/smp failed on hsdk board

**To Reproduce**
1. west build -b hsdk -d build -p auto tests/kernel/smp
2. west flash
3. See error

**Logs and console output**
```
*** Booting Zephyr OS build v2.6.0-rc1-59-g8e69dafccf25  ***
Running test suite smp
===================================================================
START - test_smp_coop_threads
 PASS - test_smp_coop_threads in 0.563 seconds
===================================================================
START - test_cpu_id_threads
 PASS - test_cpu_id_threads in 1.11 seconds
===================================================================
START - test_coop_resched_threads
 PASS - test_coop_resched_threads in 0.51 seconds
===================================================================
START - test_preempt_resched_threads
 PASS - test_preempt_resched_threads in 0.531 seconds
===================================================================
START - test_yield_threads
 PASS - test_yield_threads in 0.301 seconds
===================================================================
START - test_sleep_threads
 PASS - test_sleep_threads in 1.11 seconds
===================================================================
START - test_wakeup_threads
 PASS - test_wakeup_threads in 0.201 seconds
===================================================================
START - test_smp_ipi
cpu num=4 PASS - test_smp_ipi in 0.331 seconds
===================================================================
START - test_get_cpu
 PASS - test_get_cpu in 0.51 seconds
===================================================================
START - test_fatal_on_smp
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 1
E: Current thread: 0x9000be58 (ztest_thread)
Caught system error -- reason 3 1
Fatal error expected as part of test case.
 PASS - test_fatal_on_smp in 0.16 seconds
===================================================================
START - test_workq_on_smp
 PASS - test_workq_on_smp in 0.51 seconds
===================================================================
START - test_smp_release_global_lock
 PASS - test_smp_release_global_lock in 0.21 seconds
===================================================================
START - test_smp_release_global_lock_irq
```

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK)
 - Commit 8e69dafccf25bc5b4015a607cdba114216c4ea0e

### LINKED ISSUE #35202: smp atomic_t global_lock will never be cleared when a thread oops with global_lock is set
**Describe the bug**

When CONFIG_SMP is configed.

we call `irq_lock`, we will call `z_smp_global_lock` and set `global_lock`: https://github.com/zephyrproject-rtos/zephyr/blob/8e69dafccf25bc5b4015a607cdba114216c4ea0e/kernel/smp.c#L16-L28

we call `irq_unlock`, we will call `z_smp_global_unlock` and clear `global_lock`: https://github.com/zephyrproject-rtos/zephyr/blob/8e69dafccf25bc5b4015a607cdba114216c4ea0e/kernel/smp.c#L30-L41

When a thread called `irq_lock`, then oops, the `global_lock` will never be cleared.

I found this bug when I debug for this issue: #35200.

in test case `test_fatal_on_smp`, thread `entry_oops` will first call 'irq_lock`, then oops:

https://github.com/zephyrproject-rtos/zephyr/blob/8e69dafccf25bc5b4015a607cdba114216c4ea0e/tests/kernel/smp/src/main.c#L652-L662

then in test case `test_smp_release_global_lock_irq`, thread `t2_mutex_lock_with_irq`, it will call 'irq_lock` again: 

https://github.com/zephyrproject-rtos/zephyr/blob/8e69dafccf25bc5b4015a607cdba114216c4ea0e/tests/kernel/smp/src/main.c#L758-L788

because the `global_lock` has been set, so `irq_lock` forever.

**Impact**
#35200

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK)
 - Commit 8e69dafccf25bc5b4015a607cdba114216c4ea0e

### PR DESCRIPTION
**Pull request by enjiamai**
Update testcase test_fatal_on_smp(), and refine it and correct some
inappropriate usage such as unnecessary irq_lock(). This prevents
the error propagation to the later executing testcase.

Fixes #35200
Fixes #35202

Signed-off-by: Enjia Mai <enjiax.mai@intel.com>

### CODE REVIEW

**Comment by enjiamai** [comment]
@IRISZZW could you please help to verify that in your hsdk board, I did not have it. I think these two testcase-related issues can be solved by this PR, thank you!

File: tests/kernel/smp/src/main.c [hunk 1]
```diff
@@ -632,59 +630,57 @@ void test_smp_ipi(void)
...
 {
-	unsigned int key;
-
-	ztest_set_fault_valid(true);
-
-	key = irq_lock();
 	k_oops();
 	TC_ERROR("SHOULD NEVER SEE THIS\n");
-	rv = TC_FAIL;
-	irq_unlock(key);
```
Comment (andyross) [inline tests/kernel/smp/src/main.c:662]: Seems like this will also resolve #35202

Indeed, I don't understand why that was every trying to oops with a lock held.

**Review by andyross — APPROVED** [review]

File: tests/kernel/smp/src/main.c (hunk 1 above)
Comment (enjiamai) [reply tests/kernel/smp/src/main.c:662]: Yes, @andyross , I think so, too. And thanks so much for your clear descriptions in #35202 . :)

**Comment by enjiamai** [comment]
@yingmingx could you please help to review this, I made some changes to it. thanks!

**Review by nashif — APPROVED** [review]
