### PR TITLE
CIS Central Qualification Fixes

### LINKED ISSUE #57904: Bluetooth: Controller: Incorrect CIS ID transmitted to peripherals on reconnect
**Describe the bug**
If a central connects CIS to multiple peripherals, then the transmitted CIS ID seems to become incorrect when both CIS are disconnected and then reconnected. 

For example we are seeing
1) Central creates CIG with CIG_ID 0 with CIS_ID 0 and CIS_ID 1 (which gets handles 6 and 7 respectively)
2) Central connects CIS with handle 6 to Peripheral 1 and correctly sends `LE Connected Isochronous Stream Request` with CIG_ID = 0 and CIS_ID = 0. 
3) Central connects CIS with handle 7 to Peripheral 2 and correctly sends `LE Connected Isochronous Stream Request` with CIG_ID = 0 and CIS_ID = 1. 
4) Central Disconnects both CIS and deletes the CIG. 
5) Central creates the CIG with same parameters (i.e. CIG_ID 0 and CIS_ID 0 and CIS_1), and gets handles 6 and 7
6) Central connects CIS with 6 to Peripheral 1, but incorrectly sends `LE Connected Isochronous Stream Request` with CIG_ID = 0 and CIS_ID = 1. 

**To Reproduce**
See above

**Expected behavior**
After recreating the CIG and wanting to connect the CIS again, the `LE Connected Isochronous Stream Request` for handle should use CIS_ID 0. 

**Impact**
Breaking for TWS if attempting to reconnect the CIS

**Logs and console output**
See attached `btmon` files
[central.txt](https://github.com/zephyrproject-rtos/zephyr/files/11479676/central.txt)
[peripheral_1.txt](https://github.com/zephyrproject-rtos/zephyr/files/11479677/peripheral_1.txt)
[peripheral_2.txt](https://github.com/zephyrproject-rtos/zephyr/files/11479678/peripheral_2.txt)

**Environment (please complete the following information):**
 - Commit SHA or Version used: a13858e13278a82100541a98995caa8afe629808 but using a non-default Zephyr hex for the nRF5340 netcpu (
[hci_rpmsg_iso_zll_202305150947.hex.zip](https://github.com/zephyrproject-rtos/zephyr/files/11479700/hci_rpmsg_iso_zll_202305150947.hex.zip) ) 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mtpr-ot**
**Bluetooth: controller: Fix reconfiguring of CIG and CISes**
Up until now, it has not been possible to reconfigure a CIG and its
CISes after initial configuration, without first removing the CIG.

With this commit, le_set_cig_parameters allows the following
reconfiguration operations in configuration state:
- Set new CIG configuration parameters on existing CIG
- Iteratively configure single CIS (of more CISes)
- Increment number of CISes via multiple configuration calls
- Keep handle- and CIS_ID relation

Changes:
- Pass handles in le_set_cig_parameters from ll_cig_parameters_commit
  via output variable.
- Implement CIG state variable instead of 'started', with states
  IDLE/CONFIGURABLE, ACTIVE and INACTIVE.
- Implement ll_conn_iso_stream_get_by_id for easier access to specific
  CIS.

This fixes the following CIS Central EBQ tests:
- HCI/CIS/BI-10-C
- HCI/CIS/BI-11-C
- HCI/CIS/BI-13-C
- HCI/CIS/BV-05-C

**Bluetooth: controller: Validate parameters for CIG configuration**
Parameter checking updates for passing HCI/CIS/BI* EBQ tests.

**Bluetooth: host: Fix hci_le_remove_iso_data_path direction parameters**

The path_dir variable of BT_HCI_OP_LE_REMOVE_ISO_PATH must be bitflags,
with the following meaning:
- BIT(0) : DIR_HOST_TO_CTLR
- BIT(1) : DIR_CTLR_TO_HOST

**Bluetooth: controller: Fix ll_remove_iso_path direction parameter**
According to the Core spec, the direction parameter passed to this function
should be bitfields, i.e.:
- BIT(0) : DIR_HOST_TO_CTLR
- BIT(1) : DIR_CTLR_TO_HOST

Signed-off-by: Morten Priess <mtpr@oticon.com>

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/57904

### CODE REVIEW

**Comment by mtpr-ot** [comment]
I believe failing CI is not caused by my commits

**Comment by Thalley** [comment]
@mtpr-ot instead of trying to deduce this myself, perhaps you can answer easily: Does this change still conform to the fact that a CIG cannot be modified with "Set CIG parameters" after the first "LE Create CIS command" has completed, as per the state machine in the core spec: 

image

Given your implementation of the configurable state, I assume so, but just wanted to make sure :)

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h [hunk 1]
```diff
@@ -8,6 +8,10 @@ struct ll_conn;
 
 typedef void (*ll_iso_stream_released_cb_t)(struct ll_conn *conn);
 
+#define CIG_STATE_IDLE         0
+#define CIG_STATE_CONFIGURABLE CIG_STATE_IDLE /* Central only */
+#define CIG_STATE_ACTIVE       1
+#define CIG_STATE_INACTIVE     2
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h:14]: Have unique values

```suggestion
#define CIG_STATE_IDLE         0
#define CIG_STATE_CONFIGURABLE 1 /* Central only */
#define CIG_STATE_ACTIVE       2
#define CIG_STATE_INACTIVE     3
```

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 2]
```diff
@@ -137,36 +217,43 @@ uint8_t ll_cig_parameters_commit(uint8_t cig_id)
...
+		if (!cig) {
+			ll_iso_setup.cis_idx = 0U;
 
-		/* No space for new CIG */
-		return BT_HCI_ERR_INSUFFICIENT_RESOURCES;
+			/* No space for new CIG */
+			return BT_HCI_ERR_INSUFFICIENT_RESOURCES;
+		}
+		cig->lll.num_cis = 0;
+	} else if (cig->state != CIG_STATE_CONFIGURABLE) {
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:241]:
```suggestion
	} else if ((cig->state != CIG_STATE_IDLE) && (cig->state != CIG_STATE_CONFIGURABLE)) {
```

**Review by cvinayak — CHANGES_REQUESTED** [review]

**Comment by mtpr-ot** [comment]
> Given your implementation of the configurable state, I assume so, but just wanted to make sure :)

Yes, this was the need that triggered the change.

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h (hunk 1 above)
Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h:14]: `IDLE` is not a state per the spec, are you sure we want a separate `IDLE` state?

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 2 above)
Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:241]: With the introduction of a separate `IDLE` state, this is necessary. However, we need to transition from `IDLE` to `CONFIGURABLE`, and that has to be done very early, at init and again at CIG release. Not sure it's worth the trouble.

**Comment by mtpr-ot** [comment]
@cvinayak thanks for your quick review.

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 3]
```diff
@@ -296,21 +431,14 @@ uint8_t ll_cig_parameters_commit(uint8_t cig_id)
...
 			 * subinterval.
 			 */
 			total_time += se[i].total_count * se[i].length;
-		} else {
-			/* Interleaved CISes - find the largest total duration and
-			 * set all subintervals to the largest SE_Length of any CIS x
-			 * the number of interleaved CISes.
-			 */
-			total_time = MAX(total_time, se[i].total_count * cis->lll.sub_interval +
-					 (i * cis->lll.sub_interval / cis_count));
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:313]: ok. Could you invert the `if (cig->central.packing == BT_ISO_PACKING_SEQUENTIAL)` outside the `for (uint8_t i = 0; i < num_cis; i++) {`  as it is not necessary to check for each CIS (`cig->central.packing` is for the entire CIG).

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h:14]: Then how about one `CIG_STATE_NO_CIG_OR_CONFIGURABLE`; and have `CIG_STATE_ACTIVE` and `CIG_STATE_INACTIVE`

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h:14]: Better, but still, to me the initial state of a CIG which has been alloc'ed into existence, and gets the state 'CIG_STATE_NO_CIG_XXX' seems a bit odd ;-) How about  `CIG_STATE_IDLE_OR_CONFIGURABLE`?

**Comment by Thalley** [comment]
@mtpr-ot this PR seems to fix https://github.com/zephyrproject-rtos/zephyr/issues/57904

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso_types.h:14]: `NO CIG`  is the BT spec defined term in the state machine, hence I will stick with `CIG_STATE_NO_CIG_OR_CONFIGURABLE` or have separate `CIG_STATE_NO_CIG` and `CIG_STATE_CONFIGURABLE`. I vote for the latter, separate states (like the Spec uses in the fig 4.65).

**Comment by mtpr-ot** [comment]
> @mtpr-ot this PR seems to fix #57904

Thanks @Thalley!

File: subsys/bluetooth/controller/hci/hci.c [hunk 4]
```diff
@@ -2025,24 +2025,21 @@ static void le_set_cig_parameters(struct net_buf *buf, struct net_buf **evt)
...
-			handle = UINT16_MAX;
+		rp->num_handles = cis_count;
+		status = ll_cig_parameters_commit(cig_id, handles);
 
+		if (status == BT_HCI_ERR_SUCCESS) {
 			for (uint8_t i = 0; i < cis_count; i++) {
-				(void)ll_conn_iso_stream_get_by_group(cig, &handle);
-				rp->handle[i] = sys_cpu_to_le16(handle);
+				rp->handle[i] = sys_cpu_to_le16(handles[i]);
 			}
```
Comment (Thalley) [inline subsys/bluetooth/controller/hci/hci.c:2039]: In case that `status != BT_HCI_ERR_SUCCESS`, are the `rp->handle[i]` value uninitialized? Or are they set to 0?

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 5]
```diff
@@ -54,6 +54,24 @@
...
+#define WORST_CASE_SCA_VALID_MASK 0x07
+#define PACKING_VALID_MASK 0x01
+#define FRAMING_VALID_MASK 0x01
+#define MAX_TRANSPORT_LATENCY_MIN (0x0005 * 1000)
+#define MAX_TRANSPORT_LATENCY_MAX (0x0FA0 * 1000)
+#define CIS_ID_VALID_MAX 0xEF
+#define MAX_SDU_VALID_MASK 0x0FFF
+#define PHY_VALID_MASK 0x07
+#define ISO_INTERVAL_MIN 0x0004
+#define ISO_INTERVAL_MAX 0x0C80
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:72]: Several of these are also defined by `iso.h` if you want to use any of those

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 6]
```diff
@@ -137,36 +217,46 @@ uint8_t ll_cig_parameters_commit(uint8_t cig_id)
...
+		if (!cig) {
+			ll_iso_setup.cis_idx = 0U;
 
-		/* No space for new CIG */
-		return BT_HCI_ERR_INSUFFICIENT_RESOURCES;
+			/* No space for new CIG */
+			return BT_HCI_ERR_INSUFFICIENT_RESOURCES;
+		}
+		cig->state = CIG_STATE_CONFIGURABLE;
+		cig->lll.num_cis = 0;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:241]: There are several instances in this PR where `0` is assigned to a unsigned value instead of `0U`. It unlikely to matter, but just in case that you want to conform to most other zero-assignments

**Review by Thalley — COMMENTED** [review]
Generally looks good to me

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 5 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:72]: This be defined (moved) to `include/zephyr/bluetooth/hci.h`, and reused in host and controller makes sense.

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 6 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:241]: Agree

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 5 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:72]: They can, yes, but it isn't something we've done before. They are similar to the min/max values in `gap.h`, and can be useful for applications. We rarely expect applications to include `hci.h`.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:72]: > We rarely expect applications to include hci.h

This is not true; `l2cap.h`, `iso.h` and `audio.h` include `hci.h` 

`hci.h` includes `conn.h`  which is incorrectly added in 0f06c7d8, hence making the controller dependent on host data types. This needs correction.

> They are similar to the min/max values in gap.h

GAP is different as the Core Spec defines recommended values for parameters, hence these recommended min/max/defaults are defined as public interface parameter values (these are not HCI min/max values).

Here too an exception has been with the introduction of these lines in `gap.h` (that shall be moved/defined in `hci.h`):
https://github.com/zephyrproject-rtos/zephyr/blob/c638d6fd21fd972a98cf114b89477abe9e8ed55f/include/zephyr/bluetooth/gap.h#L475-L482

There may be other exception that need correction, to not define HCI min/max values in upper layers.

> Not sure - @cvinayak - what is the normal pattern in the controller? Do we prefer to pull in host defines?

@mtpr-ot no, we do not pull host defines inside the Controller implementation. HCI command and event parameters are be defined in `hci.h`, like below:

https://github.com/zephyrproject-rtos/zephyr/blob/c638d6fd21fd972a98cf114b89477abe9e8ed55f/include/zephyr/bluetooth/hci.h#L884-L886

In the scope of this PR, let us define/use values from `hci.h` in the Controller implementation.

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:72]: Fair points :) 

We should consider moving all the HCI defined min/max values to `hci.h`, and possibly either deprecate the duplicated ones in `gap.h` and `iso.h` or keep them but use the macros from `hci.h` as their values (e.g. `#define BT_GAP_PER_ADV_MIN_INTERVAL BT_HCI_LE_PER_ADV_INTERVAL_MIN`)

File: subsys/bluetooth/controller/hci/hci.c (hunk 4 above)
Comment (mtpr-ot) [reply subsys/bluetooth/controller/hci/hci.c:2039]: Right, it's only if parameter checking fails. I'll add it to the case where commit fails

File: include/zephyr/bluetooth/hci.h [hunk 7]
```diff
@@ -1899,6 +1899,21 @@ struct bt_hci_rp_le_read_iso_tx_sync {
...
+#define BT_HCI_SDU_INTERVAL_MIN                 0x0000FF
+#define BT_HCI_SDU_INTERVAL_MAX                 0x0FFFFF
+#define BT_HCI_WORST_CASE_SCA_VALID_MASK        0x07
+#define BT_HCI_PACKING_VALID_MASK               0x01
+#define BT_HCI_FRAMING_VALID_MASK               0x01
+#define BT_HCI_MAX_TRANSPORT_LATENCY_MIN        0x0005
+#define BT_HCI_MAX_TRANSPORT_LATENCY_MAX        0x0FA0
+#define BT_HCI_CIS_ID_VALID_MAX                 0xEF
+#define BT_HCI_MAX_SDU_VALID_MASK               0x0FFF
+#define BT_HCI_PHY_VALID_MASK                   0x07
```
Comment (Thalley) [inline include/zephyr/bluetooth/hci.h:1913]: Suggest to prefix all these with `BT_HCI_ISO` as something like `BT_HCI_SDU_INTERVAL_MIN` is too generic and could apply to non-ISO SDUs

Comment (Thalley) [reply include/zephyr/bluetooth/hci.h:1913]: Perhaps with the exceptions with values prefixed with CIS/CIG/BIS/BIG

Comment (Thalley) [reply include/zephyr/bluetooth/hci.h:1913]: I guess since these are defined by the HCI spec, we don't need to add documentation nor add a unit suffix?

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 8]
```diff
@@ -77,6 +80,59 @@ static struct {
...
+		if (!IN_RANGE(ll_iso_setup.group.iso_interval,
+			      BT_HCI_ISO_INTERVAL_MIN, BT_HCI_ISO_INTERVAL_MAX)) {
+			/* Parameter out of range */
+			return BT_HCI_ERR_INVALID_PARAM;
+		}
+	} else {
+		if (!IN_RANGE(ll_iso_setup.group.c_latency, BT_HCI_MAX_TRANSPORT_LATENCY_MIN * 1000,
+			      BT_HCI_MAX_TRANSPORT_LATENCY_MAX * 1000) ||
+		    !IN_RANGE(ll_iso_setup.group.p_latency, BT_HCI_MAX_TRANSPORT_LATENCY_MIN * 1000,
+			      BT_HCI_MAX_TRANSPORT_LATENCY_MAX * 1000)) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:113]: I see that we store the latency in microseconds with 
```c
ll_iso_setup.group.c_latency = c_latency * 1000;
ll_iso_setup.group.p_latency = p_latency * 1000;
```

What is the rationale behind using microseconds?

Also suggest to use `* USEC_PER_MSEC` instead of `* 1000`

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 9]
```diff
@@ -77,6 +80,59 @@ static struct {
...
+			/* Parameter out of range */
+			return BT_HCI_ERR_INVALID_PARAM;
+		}
+	}
+
+	if (((ll_iso_setup.group.central.sca & ~BT_HCI_WORST_CASE_SCA_VALID_MASK) != 0) ||
+	    ((ll_iso_setup.group.central.packing & ~BT_HCI_PACKING_VALID_MASK) != 0) ||
+	    ((ll_iso_setup.group.central.framing & ~BT_HCI_FRAMING_VALID_MASK) != 0)) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:121]:
```suggestion
	if (((ll_iso_setup.group.central.sca & ~BT_HCI_WORST_CASE_SCA_VALID_MASK) != 0U) ||
	    ((ll_iso_setup.group.central.packing & ~BT_HCI_PACKING_VALID_MASK) != 0U) ||
	    ((ll_iso_setup.group.central.framing & ~BT_HCI_FRAMING_VALID_MASK) != 0U)) {
```

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 10]
```diff
@@ -105,7 +161,18 @@ uint8_t ll_cis_parameters_set(uint8_t cis_id,
...
 
-	if (cis_idx >= CONFIG_BT_CTLR_CONN_ISO_STREAMS_PER_GROUP) {
+	if ((cis_id > BT_HCI_CIS_ID_VALID_MAX) ||
+	    ((c_sdu & ~BT_HCI_MAX_SDU_VALID_MASK) != 0) ||
+	    ((p_sdu & ~BT_HCI_MAX_SDU_VALID_MASK) != 0)) {
+		return BT_HCI_ERR_INVALID_PARAM;
+	}
+
+	if (!c_phy || ((c_phy & ~BT_HCI_PHY_VALID_MASK) != 0) ||
+	    !p_phy || ((p_phy & ~BT_HCI_PHY_VALID_MASK) != 0)) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:171]:
```suggestion
	    ((c_sdu & ~BT_HCI_MAX_SDU_VALID_MASK) != 0U) ||
	    ((p_sdu & ~BT_HCI_MAX_SDU_VALID_MASK) != 0U)) {
		return BT_HCI_ERR_INVALID_PARAM;
	}

	if (!c_phy || ((c_phy & ~BT_HCI_PHY_VALID_MASK) != 0U) ||
	    !p_phy || ((p_phy & ~BT_HCI_PHY_VALID_MASK) != 0U)) {
```

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 11]
```diff
@@ -501,7 +619,18 @@ uint8_t ll_cis_parameters_test_set(uint8_t cis_id, uint8_t nse,
...
 
-	if (cis_idx >= CONFIG_BT_CTLR_CONN_ISO_STREAMS_PER_GROUP) {
+	if ((cis_id > BT_HCI_CIS_ID_VALID_MAX) ||
+	    ((c_sdu & ~BT_HCI_MAX_SDU_VALID_MASK) != 0) ||
+	    ((p_sdu & ~BT_HCI_MAX_SDU_VALID_MASK) != 0)) {
+		return BT_HCI_ERR_INVALID_PARAM;
+	}
+
+	if ((!c_phy || (c_phy & ~BT_HCI_PHY_VALID_MASK) != 0) ||
+	    (!p_phy || (p_phy & ~BT_HCI_PHY_VALID_MASK) != 0)) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:629]:
```suggestion
	    ((c_sdu & ~BT_HCI_MAX_SDU_VALID_MASK) != 0U) ||
	    ((p_sdu & ~BT_HCI_MAX_SDU_VALID_MASK) != 0U)) {
		return BT_HCI_ERR_INVALID_PARAM;
	}

	if ((!c_phy || (c_phy & ~BT_HCI_PHY_VALID_MASK) != 0U) ||
	    (!p_phy || (p_phy & ~BT_HCI_PHY_VALID_MASK) != 0U)) {
```

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:629]: It seems that these checks are added multiple times; have you considered a common function?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 8 above)
Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:113]: The rationale was to avoid doing the calculation when using the parameter, as they are referenced multiple times. Not sure changing that is in scope for this PR, unless you insist?

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:113]: > Not sure changing that is in scope for this PR, unless you insist?

No, it's fine to keep as microseconds, but do please update to use `USEC_PER_MSEC` instead of `1000` :)

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 11 above)
Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:629]: A common masking-checker function? E.g. an `IS_VALID_MASK(c_phy, BT_HCI_PHY_VALID_MASK)` macro or even a function?

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:629]: Ex.: 
```
#define IS_VALID_MASK(value, valid_mask) \
	(((value) & ~(valid_mask)) != 0U)
```

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:629]: Reading this again I suspect you refer to the duplicate code between `ll_cis_parameters_set` and `ll_cis_parameters_test_set`. Will make a function for that

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 5 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c]: > keep them but use the macros from `hci.h` as their values (e.g. `#define BT_GAP_PER_ADV_MIN_INTERVAL BT_HCI_LE_PER_ADV_INTERVAL_MIN`)

This will help avoid stable API change request/deprecation.

Lets plan to do this outside this PR.

File: include/zephyr/bluetooth/hci.h [hunk 12]
```diff
@@ -1899,6 +1899,21 @@ struct bt_hci_rp_le_read_iso_tx_sync {
...
+#define BT_HCI_ISO_INTERVAL_MIN                 0x0004
+#define BT_HCI_ISO_INTERVAL_MAX                 0x0C80
+
```
Comment (cvinayak) [inline include/zephyr/bluetooth/hci.h:1916]: I think @Thalley wanted something like this (i added `_CIG_`  as these values are used in the context of HCI LE Set CIG Parameters):

```suggestion
#define BT_HCI_CIG_ID_MAX                           0xFE
#define BT_HCI_CIG_CIS_COUNT_MAX                    0x1F
#define BT_HCI_CIG_SDU_INTERVAL_MIN                 0x0000FF
#define BT_HCI_CIG_SDU_INTERVAL_MAX                 0x0FFFFF
#define BT_HCI_CIG_WORST_CASE_SCA_VALID_MASK        0x07
#define BT_HCI_CIG_PACKING_VALID_MASK               0x01
#define BT_HCI_CIG_FRAMING_VALID_MASK               0x01
#define BT_HCI_CIG_MAX_TRANSPORT_LATENCY_MIN        0x0005
#define BT_HCI_CIG_MAX_TRANSPORT_LATENCY_MAX        0x0FA0
#define BT_HCI_CIG_CIS_ID_VALID_MAX                 0xEF
#define BT_HCI_CIG_MAX_SDU_VALID_MASK               0x0FFF
#define BT_HCI_CIG_PHY_VALID_MASK                   0x07
#define BT_HCI_CIG_ISO_INTERVAL_MIN                 0x0004
#define BT_HCI_CIG_ISO_INTERVAL_MAX                 0x0C80

```

**Review by cvinayak — CHANGES_REQUESTED** [review]

**Review by cvinayak — DISMISSED** [review]

File: include/zephyr/bluetooth/hci.h [hunk 13]
```diff
@@ -1899,6 +1899,21 @@ struct bt_hci_rp_le_read_iso_tx_sync {
...
+#define BT_HCI_CIG_WORST_CASE_SCA_VALID_MASK    0x07
+#define BT_HCI_CIG_PACKING_VALID_MASK           0x01
+#define BT_HCI_CIG_FRAMING_VALID_MASK           0x01
+#define BT_HCI_CIG_MAX_TRANSPORT_LATENCY_MIN    0x0005
+#define BT_HCI_CIG_MAX_TRANSPORT_LATENCY_MAX    0x0FA0
+#define BT_HCI_CIG_CIS_ID_VALID_MAX             0xEF
+#define BT_HCI_CIG_MAX_SDU_VALID_MASK           0x0FFF
+#define BT_HCI_CIG_PHY_VALID_MASK               0x07
+#define BT_HCI_CIG_ISO_INTERVAL_MIN             0x0004
+#define BT_HCI_CIG_ISO_INTERVAL_MAX             0x0C80
```
Comment (Thalley) [inline include/zephyr/bluetooth/hci.h:1915]: Just a note: If we make all these CIG specific, then they will be of no use to the application as @cvinayak suggested, as the ISO API does not differ between CIS and BIS for the majority of these values. 

@cvinayak is that OK for you, or should we make the values that are common between unicast and broadcast use a common generic prefix like `BT_HCI_ISO` instead of `BT_HCI_CIG`?

Comment (mtpr-ot) [reply include/zephyr/bluetooth/hci.h:1915]: Perhaps we can change these to `_ISO_` when BIS needs them?

**Review by Thalley — APPROVED** [review]

**Comment by mtpr-ot** [comment]
@cvinayak, please renew your approval, thanks

**Review by cvinayak — APPROVED** [review]
