### PR TITLE
mgmt: mcumgr: grp: img_mgmt: Fix detecting where a slot resides

### LINKED ISSUE #99762: mcumgr: Image management incorrectly identifies active slot when slots are on different flash devices
### Describe the bug

When MCUboot is configured with `slot0_partition` and `slot1_partition` on different flash devices (e.g., slot 1 on external flash), mcumgr image management cannot correctly identify the active application partition. This results in uploading new firmware to the wrong slot, corrupting the currently running image and making the device unbootable.

### Regression

- [x] This is a regression.

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Additional Context

The `FIXED_PARTITION_IS_RUNNING_APP_PARTITION` macro used in `img_mgmt_active_slot()` only compares the partition offset against `CONFIG_FLASH_LOAD_OFFSET` without considering which flash device the partition resides on.

https://github.com/zephyrproject-rtos/zephyr/blob/32615695ad1b96670be8f2a38a8a9fd27e2d8ae5/subsys/dfu/img_util/flash_img.c#L26-L28

When two partitions on different flash devices have overlapping offset ranges that include `CONFIG_FLASH_LOAD_OFFSET`, the macro can incorrectly identify a partition on external flash as the running partition.

In Zephyr versions prior to v4.3.0, the implementation used exact equality, so this could accidentally work in multi-device configurations when the slot offsets differed between flash devices.

### PR DESCRIPTION
**Pull request by nordicjm**
Fixes an issue introduced in commit
32615695ad1b96670be8f2a38a8a9fd27e2d8ae5 which wrongly did not check what the residing device was on before determining if a slot was part of a partition area

Fixes #99762

### CODE REVIEW

**Review by pdgendt — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]

**Review by tomchy — CHANGES_REQUESTED** [review]
This change introduces a regression - it is no longer possible to use a different partition for the code than `slot0/1_partition`.
In our setup - we define subpartitions within the `slot0/1_partition` for the `zephyr,code-partition`.

File: subsys/dfu/img_util/flash_img.c [hunk 1]
```diff
@@ -23,11 +24,16 @@ LOG_MODULE_REGISTER(flash_img, CONFIG_IMG_MANAGER_LOG_LEVEL);
 #include <bootutil/bootutil_public.h>
 #endif
 
+#define FIXED_PARTITION_GET_FLASH_NODE(node_id)                                    \
```
Comment (JarmouniA) [inline subsys/dfu/img_util/flash_img.c:27]: This is basically a combination of https://github.com/zephyrproject-rtos/zephyr/blob/8a72d776c5af6522478155adc91a5f4edb2794e3/include/zephyr/devicetree/fixed-partitions.h#L151
and
https://github.com/zephyrproject-rtos/zephyr/blob/8a72d776c5af6522478155adc91a5f4edb2794e3/include/zephyr/devicetree/fixed-partitions.h#L86
but without checking if Flash node has `soc_nv_flash` compatible.

Comment (nordicjm) [reply subsys/dfu/img_util/flash_img.c:27]: it does not get the device either which is the important part so that it works in macros

**Review by de-nordic — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Review by tomchy — APPROVED** [review]

**Review by jakubtopic — APPROVED** [review]

File: subsys/dfu/img_util/flash_img.c [hunk 2]
```diff
@@ -11,6 +11,7 @@
 #include <stdio.h>
 #include <string.h>
 #include <zephyr/logging/log.h>
+#include <zephyr/devicetree.h>
 #include <zephyr/dfu/mcuboot.h>
```
Comment (kartben) [inline subsys/dfu/img_util/flash_img.c:15]: random (unrelated) nit: this header is included twice

File: subsys/dfu/img_util/flash_img.c [hunk 3]
```diff
@@ -23,11 +24,16 @@ LOG_MODULE_REGISTER(flash_img, CONFIG_IMG_MANAGER_LOG_LEVEL);
 #include <bootutil/bootutil_public.h>
 #endif
 
+#define FIXED_PARTITION_GET_FLASH_NODE(node_id)                                    \
+	COND_CODE_1(DT_NODE_HAS_COMPAT(DT_PARENT(node_id), fixed_subpartitions),   \
+		    (DT_PARENT(DT_GPARENT(node_id))), (DT_GPARENT(node_id)))
```
Comment (JarmouniA) [inline subsys/dfu/img_util/flash_img.c:29]: The 2nd part should not really be an unconditional else, should be checking for fixed_partitions compat.

The justification for the extra check would be that the description of the `zephyr,code-partition` chosen property does not say it only takes fixed-partitions or fixed-subpartitions compatible nodes.
https://docs.zephyrproject.org/latest/build/dts/api/api.html#zephyr-specific-chosen-nodes

File: subsys/dfu/img_util/flash_img.c (hunk 1 above)
Comment (JarmouniA) [reply subsys/dfu/img_util/flash_img.c:27]: > it does not get the device either

Not really sure what you mean.
