### PR TITLE
Bluetooth: Mesh: refactor mesh to use both tinycrypt and psa based crypto

### LINKED ISSUE #58883: RFC: API Change: BLE Mesh (cdb)
### Problem description

https://github.com/zephyrproject-rtos/zephyr/pull/57788

Tinycrypt is deprecated. BLE Mesh has strict architecture dependency on Tinycrypt. Additionally, strict dependency on Tinycrypt doesn't allow using ARM Trustzone feature that is represented on many modern chips as well as multicore chips where security is managed by a separate core.

### Proposed change

1. Make BLE Mesh architecture\implementation flexible and scalable in aspect of third party crypto libraries. 
2. Make API scalable to key representations.
3. Key representation within BLE Mesh within BLE Mesh depends on KConfig options (depends on chosen crypto library).
4. Support both Tinycrypt and PSA based crypto libraries. Tinycrypt is supported while it is alive, or PSA based crypto libraries reach comparable memory footprint.

## Detailed RFC

1. Key representation is hidden beyond abstract structure type. Real key representation depends on KConfig option (crypto library).
2. All functional collaboration within mesh is performed (if specification doesn't require pure key presence) using abstract type.
3. All public API operates only with abstract type. The PR changes only cdb structure.
4. Setting\getting keys in cdb is performed via new import\export API. Access to keys via pointer is not valid anymore.

### Dependencies

Access to keys those have been set via cdb via pointer is not valid anymore. This should be replaced by import\export functionality.
Sample:
old:
```
struct bt_mesh_cdb_app_key *key;

key = bt_mesh_cdb_app_key_alloc(net_idx, app_idx);
if (key == NULL) {
	printk("Failed to allocate app-key 0x%04x\n", app_idx);
	return;
}

bt_rand(key->keys[0].app_key, 16);
```
new:
```
struct bt_mesh_cdb_app_key *key;
uint8_t app_key[16];
int err;

key = bt_mesh_cdb_app_key_alloc(net_idx, app_idx);
if (key == NULL) {
	printk("Failed to allocate app-key 0x%04x\n", app_idx);
	return;
}

bt_rand(app_key, 16);

err = bt_mesh_cdb_app_key_import(key, 0, app_key);
if (err) {
	printk("Failed to import appkey into cdb. Err:%d\n", err);
	return;
}
```

### Concerns and Unresolved Questions

1. Bad integration mbedTLS PSA into Zephyr's build system. There is no any case CI that checks it. During refactoring, there were some regressions in this.
2. Enormously huge mbedTLS footprint.
3. mbedTLS PSA ITS doesn't support Zephyr's settings subsystem. It is possible to use only on POSIX platforms.
4. mbedTLS PSA ITS based on POSIX file access to that is not thread safe. Parallel bsim tests running is always failed.
5. TF-M doesn't work correctly with Zephyr's settings subsystem. 

## Alternatives

Tinycrypt is morally deprecated.
If Tinycrypt is not going to support ARM Trustzone and HW features related to Trustzone chip vendors features, then there are no alternatives.

### PR DESCRIPTION
**Pull request by alxelax**
A mesh key type has been added to be able to choose the different key representation for different security libraries. The type as well as some functionality related to Mesh key management has been added as a public API.
If tynicrypt is chosen, then keys have representation as 16 bytes arrays. If mbedTLS with PSA is used, then keys are the PSA key id. Raw value is not kept within BLE Mesh stack for mbedTLS. Keys are imported into the security library and key IDs are gotten back. This refactoring has been done for the network(including all derivated keys), application, device, and session keys.

### CODE REVIEW

**Review by Andrewpini — COMMENTED** [review]
In general this looks good to me. Got a comment regarding some of the docs.

File: modules/mbedtls/configs/config-tls-generic.h [hunk 1]
```diff
@@ -458,6 +458,14 @@
 #if defined(CONFIG_MBEDTLS_PSA_CRYPTO_C)
 #define MBEDTLS_PSA_CRYPTO_C
 #define MBEDTLS_USE_PSA_CRYPTO
+
+#if defined(CONFIG_BOARD_NRF52_BSIM) || defined(CONFIG_BOARD_NATIVE_POSIX)
```
Comment (alxelax) [inline modules/mbedtls/configs/config-tls-generic.h:462]: @joerchan ble mesh requires these options to be able to use keys with persistent lifetime `PSA_KEY_LIFETIME_PERSISTENT`.

File: tests/bsim/bluetooth/mesh/src/distribute_keyid.h [hunk 2]
```diff
@@ -0,0 +1,17 @@
+/*
+ * Copyright (c) 2023 Nordic Semiconductor
```
Comment (PavelVPV) [inline tests/bsim/bluetooth/mesh/src/distribute_keyid.h:2]:
```suggestion
 * Copyright (c) 2023 Nordic Semiconductor ASA
```

File: subsys/bluetooth/mesh/cdb.c [hunk 3]
```diff
@@ -315,8 +319,10 @@ static int cdb_subnet_set(const char *name, size_t len_rd,
 	}
 
 	sub->kr_phase = key.kr_phase;
-	memcpy(sub->keys[0].net_key, &key.val[0], 16);
-	memcpy(sub->keys[1].net_key, &key.val[1], 16);
+	memcpy(&sub->keys[0].net_key, &key.val[0], sizeof(struct bt_mesh_key));
+	memcpy(&sub->keys[1].net_key, &key.val[1], sizeof(struct bt_mesh_key));
+	bt_mesh_key_assign(&sub->keys[0].net_key);
```
[the remark this answers is not in the document]
Comment (alxelax) [reply subsys/bluetooth/mesh/cdb.c:324]: Sounds reasonable. I'll try to do it.

File: modules/mbedtls/configs/config-tls-generic.h (hunk 1 above)
Comment (joerchan) [reply modules/mbedtls/configs/config-tls-generic.h:462]: Selecting these options based on board seems very strange to me.
Can you explain why these boards need the configurations?

File: subsys/bluetooth/mesh/friend.c [hunk 4]
```diff
@@ -164,6 +164,11 @@ static void friend_clear(struct bt_mesh_friend *frnd)
 	/* If cancelling the timer fails, we'll exit early in the work handler. */
 	(void)k_work_cancel_delayable(&frnd->timer);
 
+	for (int i = 0; i < ARRAY_SIZE(frnd->cred); i++) {
+		if (frnd->subnet->keys[i].valid) {
+			bt_mesh_friend_cred_destroy(&frnd->cred[i]);
```
[the remark this answers is not in the document]
Comment (alxelax) [reply subsys/bluetooth/mesh/friend.c:169]: It isn't required. I didn't find any place where both credentials or keys were checked they have zeroes. There is `valid` flag that keeps information about the validity of credentials.  In case of the creation of the new credentials, the old key\key ID will be rewritten by the new one.
The same for LPN.

File: subsys/bluetooth/mesh/provisioner.c [hunk 5]
```diff
@@ -488,20 +488,19 @@ static void send_prov_data(void)
...
 	struct bt_mesh_cdb_subnet *sub;
-	uint8_t session_key[16];
+	uint8_t net_key[16];
+	struct bt_mesh_key session_key;
 	uint8_t nonce[13];
 	int err;
 
 	err = bt_mesh_session_key(bt_mesh_prov_link.dhkey,
-				  bt_mesh_prov_link.prov_salt, session_key);
+				  bt_mesh_prov_link.prov_salt, &session_key);
```
[the remark this answers is not in the document]
Comment (alxelax) [reply subsys/bluetooth/mesh/provisioner.c:497]: Obviously, we should. Good catch, thanks.

File: subsys/bluetooth/mesh/provisioner.c [hunk 6]
```diff
@@ -520,17 +519,22 @@ static void send_prov_data(void)
 		return;
```
[the remark this answers is not in the document]
Comment (alxelax) [reply subsys/bluetooth/mesh/provisioner.c:519]: I doubt it is possible. I tried to do it but faced some issues that I don't remember already. We can try it, of course. Probably I missed something. Please add it to backlog.

File: modules/mbedtls/configs/config-tls-generic.h (hunk 1 above)
Comment (joerchan) [reply modules/mbedtls/configs/config-tls-generic.h:462]: @alxelax Is there a kconfig for the ITS based on POSIX file API? It seems better to enable these options based on this feature instead of the boards.

Comment (alxelax) [reply modules/mbedtls/configs/config-tls-generic.h:462]: @joerchan, there are no configs for ITS. Right now whatever you build is not able to be built if you chose PSA and POSIX incompatible platforms. I doubt anything uses mbedTLS PSA that is run in Zephyr's CI. There are bugs that I fix in this PR that does not allow building mbedTLS PSA with Zephyr's configs at all. Probably only specific configurations.
I'm pretty sure we (as ble mesh maintainers) will have to create a specific mesh configuration file to configure mbedtTLS properly but for now default config is OK with this addition.
mbedTLS ITS doesn't depend on features. It lacks implementations for platforms. It is why I added dependency on platform.

File: modules/mbedtls/CMakeLists.txt [hunk 7]
```diff
@@ -107,7 +107,7 @@ zephyr_interface_library_named(mbedTLS)
 
     zephyr_library_named(mbedTLSCrypto)
 
-    if (MBEDTLS_USE_PSA_CRYPTO)
```
Comment (alxelax) [inline modules/mbedtls/CMakeLists.txt:110]: @joerchan FYI. cmake file depends on the definition that is declared in the header file. Obviously, the header file is not available for cmake to choose files. That means mbedTLS PSA isn't possible to build with config files that are in Zephyr repo.

File: tests/bsim/bluetooth/mesh/src/test_beacon.c [hunk 8]
```diff
@@ -1149,18 +1154,13 @@ static void private_beacon_create(struct net_buf_simple *buf, const uint8_t *net
 		FAIL("Unable to generate Net ID");
 	}
 
-	err = bt_mesh_private_beacon_key(net_key, priv_beacon_key);
+	err = bt_mesh_private_beacon_key(net_key, &priv_beacon_key);
```
Comment (PavelVPV) [inline tests/bsim/bluetooth/mesh/src/test_beacon.c:1157]: Should `bt_mesh_key_destroy` be called after encrypting the beacon?

**Review by PavelVPV — COMMENTED** [review]
Two minor questions.

File: tests/bsim/bluetooth/mesh/src/test_beacon.c (hunk 8 above)
Comment (alxelax) [reply tests/bsim/bluetooth/mesh/src/test_beacon.c:1157]: It is used for decryption of incoming beacons here: https://github.com/alxelax/zephyr/blob/refactor_key_usage_2/tests/bsim/bluetooth/mesh/src/test_beacon.c#L355-L356

**Review by PavelVPV — APPROVED** [review]
~Since CDB is still experimental and this is the only API change, we don't need to follow any API deprecation procedures.~

**Review by Andrewpini — APPROVED** [review]

**Comment by PavelVPV** [comment]
Ah, I forgot that we marked CDB as not experimental :/ Then I guess we need to create RFC to merge this PR: https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-incompatible-changes

**Review by PavelVPV — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by alxelax** [comment]
https://github.com/zephyrproject-rtos/zephyr/issues/58883#issuecomment-1589509686
