### PR TITLE
net: Drop incoming packet if there is no data in it

### LINKED ISSUE #28131: Crash while serving large files via HTTP with TCP2
**Describe the bug**
While testing TCP2 with the _dumb_http_server_ sample application on the MIMXRT1050_EVK board I experimented several crashes when increasing the size of the served file.

**To Reproduce**
1. Apply patch in [test-tcp2.zip](https://github.com/zephyrproject-rtos/zephyr/files/5182994/test-tcp2.zip)
2. west build -b mimxrt1050_evk zephyr/samples/net/sockets/dumb_http_server
3. west flash
4. ping the board on a terminal `ping -A 192.168.1.241`
5. load the page with curl on another terminal `while true; do time curl http://192.168.1.241:8080 --output test || break; done`

**Expected behavior**
No crash.

**Impact**
Since we need to serve "large" files via HTTP this problem prevents us to deliver stable firmware to our customers. So far we are using TCP1 but we have even more problems with it, therefore we are hoping to switch to TCP2 in order to solve them.

**Logs and console output**
Here are several examples of crash log.

```
Connection #150 from 192.168.1.146
Err[00:00:55.861,000] <err> net_pkt: Data buffer (1500) allocation failed.
[00:00:55.861,000] <err> net_tcp: conn: 0x80007888 packet allocation failed, len=1452
[00:01:34.637,000] <err> os: ***** USAGE FAULT *****
[00:01:34.637,000] <err> os:   Attempt to execute undefined instruction
[00:01:34.637,000] <err> os: r0/a1:  0x80005010  r1/a2:  0x0f0e070d  r2/a3:  0x0000000b
[00:01:34.637,000] <err> os: r3/a4:  0x80000000 r12/ip:  0x0f0e070c r14/lr:  0x6000c4dd
[00:01:34.637,000] <err> os:  xpsr:  0x01000000
[00:01:34.637,000] <err> os: Faulting instruction address (r15/pc): 0x20000004
[00:01:34.637,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:01:34.637,000] <err> os: Current thread: 0x80001810 (unknown)
[00:01:34.655,000] <err> os: Halting system
```

```
Connection #0 from 192.168.1.146
Err[00:00:07.607,000] <err> net_pkt: Data buffer (1500) allocation failed.
[00:00:07.607,000] <err> net_tcp: conn: 0x80007888 packet allocation failed, len=1452
[00:00:07.607,000] <err> os: ***** BUS FAULT *****
[00:00:07.607,000] <err> os:   Instruction bus error
[00:00:07.607,000] <err> os: r0/a1:  0x80005058  r1/a2:  0x0d0d0f0f  r2/a3:  0x071d0d0d
[00:00:07.607,000] <err> os: r3/a4:  0x80000000 r12/ip:  0x0d0d0f0e r14/lr:  0x6000c4dd
[00:00:07.607,000] <err> os:  xpsr:  0xa1000000
[00:00:07.607,000] <err> os: Faulting instruction address (r15/pc): 0x071d0d0c
[00:00:07.607,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:07.607,000] <err> os: Current thread: 0x80001810 (unknown)
[00:00:07.651,000] <err> os: Halting system
```

```
Connection #1 from 192.168.1.146
Err[00:00:08.420,000] <err> net_pkt: Data buffer (1500) allocation failed.
[00:00:08.420,000] <err> net_tcp: conn: 0x80007888 packet allocation failed, len=1452
[00:00:08.421,000] <err> os: ***** BUS FAULT *****
[00:00:08.421,000] <err> os:   Instruction bus error
[00:00:08.421,000] <err> os: r0/a1:  0x80004f80  r1/a2:  0x4f0f0d0d  r2/a3:  0x0f2f0b1f
[00:00:08.421,000] <err> os: r3/a4:  0x80000000 r12/ip:  0x4f0f0d0c r14/lr:  0x6000c4dd
[00:00:08.421,000] <err> os:  xpsr:  0x81000000
[00:00:08.421,000] <err> os: Faulting instruction address (r15/pc): 0x0f2f0b1e
[00:00:08.421,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:08.421,000] <err> os: Current thread: 0x80001810 (unknown)
[00:00:08.465,000] <err> os: Halting system
```

```
$ZEPHYR_SDK_INSTALL_DIR/arm-zephyr-eabi/bin/arm-zephyr-eabi-addr2line -e build/zephyr/zephyr.elf 0x6000c4dd 
build/zephyr/include/generated/syscalls/kernel.h:168
```

`kernel.h:168` is the location of the `k_yield` function.

**Environment (please complete the following information):**
 - OS: Kubuntu 20.04
 - Toolchain: Zephyr SDK 0.11.4, west 0.7.3
 - Zephyr: v2.4.0-rc1

### PR DESCRIPTION
**Pull request by jukkar**
If the network driver for some reason did not set the data in
the network packet properly, then just drop it as we cannot do
anything with just plain net_pkt.

Fixes #28131

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

File: subsys/net/ip/net_core.c [hunk 1]
```diff
@@ -382,7 +382,7 @@ int net_recv_data(struct net_if *iface, struct net_pkt *pkt)
 		return -EINVAL;
 	}
 
-	if (!pkt->frags) {
+	if (!pkt->frags || !pkt->frags->data) {
```
Comment (tbursztyka) [inline subsys/net/ip/net_core.c:385]: I think it's time to add a net_pkt_is_empty() function :)

Comment (jukkar) [reply subsys/net/ip/net_core.c:385]: That is a good idea, I will send a new version.

File: include/net/net_pkt.h [hunk 2]
```diff
@@ -900,6 +900,12 @@ static inline uint8_t *net_pkt_ip_data(struct net_pkt *pkt)
 	return pkt->frags->data;
 }
 
+static inline bool net_pkt_is_empty(struct net_pkt *pkt)
+{
+	return (!pkt->buffer || !net_pkt_data(pkt) ||
+		!pkt->buffer->len) ? true : false;
```
Comment (mniestroj) [inline include/net/net_pkt.h:906]: I don't think this `? true : false` is needed here.

Comment (jukkar) [reply include/net/net_pkt.h:906]: Indeed, good point.

**Review by tbursztyka — APPROVED** [review]

File: include/net/net_pkt.h (hunk 2 above)
Comment (pfalcon) [reply include/net/net_pkt.h]: Maybe use old good arithmetic comparison, `pkt->buffer->len == 0`? Friendly to humans, and even required by MISRA C.

Comment (jukkar) [reply include/net/net_pkt.h]: Well, sure, that can be done too.

**Review by mniestroj — APPROVED** [review]
