### PR TITLE
test: timer: behavior: Enhancement for running this test

### LINKED ISSUE #49576: tests: kernel: timer: timer_behavior: kernel.timer.timer fails
**Describe the bug**
The tests/kernel/timer/timer_behavior/kernel.timer.timer fails

Observed for
- nrf9160dk_nrf9160
- nrf9160dk_nrf9160_ns
- nrf52840dk_nrf52840
- nrf5340dk_nrf5340_cpuapp
- nrf5340dk_nrf5340_cpuapp_ns

**To Reproduce**
1. have nrf52840dk_nrf52840 connected
2. go to your zephyr dir
3. call ./scripts/twister -T tests/kernel/timer/timer_behavior -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
[2022-08-26T07:49:46.753Z] ERROR   - *** Booting Zephyr OS build zephyr-v3.1.0-4233-g8a5d568a7979  ***
[2022-08-26T07:49:46.753Z] Running TESTSUITE timer_behavior
[2022-08-26T07:49:46.753Z] ===================================================================
[2022-08-26T07:49:46.753Z] START - test_periodic_behavior
[2022-08-26T07:49:46.753Z] periodic timer behavior test
[2022-08-26T07:49:46.753Z] periodic timer samples gathered, calculating statistics
[2022-08-26T07:49:46.753Z] timer clock rate 32768, kernel tick rate 32768, expected period 1000 us, samples 10000, period 32.768000 cycles
[2022-08-26T07:49:46.753Z] statistics samples 10000, rollovers 0, mean 1007.083130 us, variance 0.093123 us, stddev 0.305161 us, min 1007.080078 us, max 1037.597656 us
[2022-08-26T07:49:46.753Z] statistics samples 10000, rollovers 0, mean 33.000100 cycles, variance 0.000100 cycles, stddev 0.010000 cycles, min 33 cycles, max 34 cycles
[2022-08-26T07:49:46.753Z] timer start cycle 15030, end cycle 345031, total time 10070831.298828, expected time 10000000.000000, difference 70831.298828
[2022-08-26T07:49:46.753Z] Assertion failed at ../../../../../../../../../zephyr/zephyr/tests/kernel/timer/timer_behavior/src/main.c:176: timer_behavior_test_periodic_behavior: (abs(time_diff_us) < CONFIG_TIMER_TEST_MAX_DRIFT is false)
[2022-08-26T07:49:46.753Z] Drift (in microseconds) outside expected bound
[2022-08-26T07:49:46.753Z] FAIL - test_periodic_behavior in 10.281 seconds
[2022-08-26T07:49:46.753Z] ===================================================================
[2022-08-26T07:49:46.753Z] TESTSUITE timer_behavior failed.
[2022-08-26T07:49:46.753Z] ------ TESTSUITE SUMMARY START ------
[2022-08-26T07:49:46.753Z] SUITE FAIL -   0.00% [timer_behavior]: pass = 0, fail = 1, skip = 0, total = 1 duration = 10.281 seconds
[2022-08-26T07:49:46.753Z] - FAIL - [timer_behavior.test_periodic_behavior] duration = 10.281 seconds
[2022-08-26T07:49:46.753Z] ------ TESTSUITE SUMMARY END ------
[2022-08-26T07:49:46.753Z] ===================================================================
[2022-08-26T07:49:46.753Z] RunID: 6823904787c6f417e7a78c889bbc8520
[2022-08-26T07:49:46.753Z] PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.14.1
 - Commit SHA or Version used: v3.1.0-4233-g8a5d568a7979

### PR DESCRIPTION
**Pull request by chen-png**
Zephyr timer is based on system ticks, there usually exists some time drift due to round up/down errors between cycles, ticks and time delay, we need to add those expected time drift into the bound calculation for running this test.

Signed-off-by: Chen Peng1 <peng1.chen@intel.com>

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/49576

### CODE REVIEW

**Comment by chen-png** [comment]
Fixes #49576
I tested this on the only two boards reel_board and mimxrt1050_evk on hand whose HW cycle rate is 32768, seems fine.
```
*** Booting Zephyr OS build v3.2.0-rc2-2-g7069a895df8d  ***
Running TESTSUITE timer_behavior
===================================================================
START - test_periodic_behavior
periodic timer behavior test
periodic timer samples gathered, calculating statistics
timer clock rate 32768, kernel tick rate 32768, expected period 1000 us, samples 10000, period 32.768000 cycles, expected_period_drift 7.080078 us
statistics samples 10000, rollovers 0, mean 1007.080078 us, variance 0.000000 us, stddev 0.000000 us, min 1007.080078 us, max 1007.080078 us
statistics samples 10000, rollovers 0, mean 33.000000 cycles, variance 0.000000 cycles, stddev 0.000000 cycles, min 33 cycles, max 33 cycles
timer start cycle 12662, end cycle 342662, total time 10070800.781250, expected time 10000000.000000, expected_time_drift 70800.781250, difference 0.000000
 PASS - test_periodic_behavior in 10.216 seconds
===================================================================
TESTSUITE timer_behavior succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [timer_behavior]: pass = 1, fail = 0, skip = 0, total = 1 duration = 10.216 seconds
 - PASS - [timer_behavior.test_periodic_behavior] duration = 10.216 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

File: tests/kernel/timer/timer_behavior/src/main.c [hunk 1]
```diff
@@ -64,13 +64,6 @@ ZTEST(timer_behavior, test_periodic_behavior)
 
 	k_timer_init(&periodic_timer, periodic_fn, NULL);
 
-#ifdef CONFIG_TIMER_HAS_64BIT_CYCLE_COUNTER
-	periodic_start = k_cycle_get_64();
-#else
-	periodic_start = k_cycle_get_32();
-#endif
-
-	periodic_data[0] = periodic_start;
```
Comment (teburd) [inline tests/kernel/timer/timer_behavior/src/main.c:73]: This is actually useful as it shows the initial timer offset as working. I'm not sure I agree that removing this makes sense

File: tests/kernel/timer/timer_behavior/prj.conf [hunk 2]
```diff
@@ -1,3 +1,4 @@
 CONFIG_ZTEST=y
 CONFIG_ZTEST_NEW_API=y
 CONFIG_CBPRINTF_FP_SUPPORT=y
+CONFIG_FPU=y
```
Comment (teburd) [inline tests/kernel/timer/timer_behavior/prj.conf:4]: This shouldn't be needed, without the FPU there should be software generated fallbacks for float math from the compiler.

**Review by teburd — CHANGES_REQUESTED** [review]
I really like that this continues to be a wall clock test while accounting for the tick rounding errors in a convenient way.

I'm not sure I entirely agree that the test should ignore the initial timer time or that it requires FPU support.

File: tests/kernel/timer/timer_behavior/src/main.c [hunk 3]
```diff
@@ -152,14 +159,15 @@ ZTEST(timer_behavior, test_periodic_behavior)
 		 "%f cycles, min %llu cycles, max %llu cycles\n",
 		 CONFIG_TIMER_TEST_SAMPLES - periodic_rollovers, periodic_rollovers, mean_cyc,
 		 variance_cyc, stddev_cyc, min_cyc, max_cyc);
-	TC_PRINT("timer start cycle %llu, end cycle %llu, total time %f, expected time %f, "
-		 "difference %f\n",
-		 periodic_start, periodic_end, actual_time_us, expected_time_us, time_diff_us);
+	TC_PRINT("timer start cycle %llu, end cycle %llu, total time %f, "
+		"expected time %f, expected_time_drift %f, difference %f\n",
```
Comment (teburd) [inline tests/kernel/timer/timer_behavior/src/main.c:163]: s/expected_time_drift/expected time drift

File: tests/kernel/timer/timer_behavior/src/main.c [hunk 4]
```diff
@@ -130,20 +123,34 @@ ZTEST(timer_behavior, test_periodic_behavior)
...
+	double expected_time_drift_us = expected_period_drift
+		* CONFIG_TIMER_TEST_SAMPLES;
+	double time_diff_us = actual_time_us - expected_time_us
+		- expected_time_drift_us;
 
 	TC_PRINT("timer clock rate %d, kernel tick rate %d, expected period %d us, samples %d, "
-		 "period %f cycles\n",
-		 CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC, CONFIG_SYS_CLOCK_TICKS_PER_SEC,
-		 CONFIG_TIMER_TEST_PERIOD, CONFIG_TIMER_TEST_SAMPLES, expected_period);
+		"period %f cycles, expected_period_drift %f us\n",
```
Comment (teburd) [inline tests/kernel/timer/timer_behavior/src/main.c:150]: s/expected_period_drift/expected period drift

File: tests/kernel/timer/timer_behavior/src/main.c (hunk 1 above)
Comment (chen-png) [reply tests/kernel/timer/timer_behavior/src/main.c:73]: I removed the first timer shot because it needs to spend some cycles between the timer interrupt isr got triggered and went into the timer handler, this spent cycles would be added into the first timer period, and we can not guarantee the first period won't beyond the bound requirement of this test after adding those cycles.

Comment (teburd) [reply tests/kernel/timer/timer_behavior/src/main.c:73]: I might need some better explanation of this behavior. If you are seeing a large time difference between the desired first timeout of the timer and the actual timeout of the timer, that seems like a bug.

k_timer_start(&timer, K_MSEC(1), K_MSEC(1)); should fire in 1msec or a hair over from the call time otherwise there's presumably a bug and the test *should* fail if its massively off.

File: tests/kernel/timer/timer_behavior/prj.conf (hunk 2 above)
Comment (teburd) [reply tests/kernel/timer/timer_behavior/prj.conf:4]: After discussing this with others this seems like a bug on a particular platform. CONFIG_FPU=y should be selected by the board/soc probably if CONFIG_HAS_FPU=y as a default *or* the build flags should be set to infer CONFIG_FPU=n to mean "-msoft-float".

This flag isn't required on arm for example where a FPU may/may not exist and doesn't seem to cause fault probably because the implication is soft-float usage.

Comment (chen-png) [reply tests/kernel/timer/timer_behavior/prj.conf]: thanks, there is indeed a soft float support for my x86 platform via config X86_FP_USE_SOFT_FLOAT, but I am not sure why this config relies on NEWLIB_LIBC, from the commit message in  ff720cd9b34, NEWLIB_LIBC should rely on X86_FP_USE_SOFT_FLOAT or FPU, so I updated the Kconfig dependency for them.

Then if without FPU, this soft float will be enabled in default for x86, we don't want to set FPU in default because this will incur performance penalty to save FPU registers for all threads during context switch.

File: tests/kernel/timer/timer_behavior/src/main.c (hunk 1 above)
Comment (chen-png) [reply tests/kernel/timer/timer_behavior/src/main.c:73]: when we set the next timeout, it is based on last cycles count in timer isr, but between timer isr and custom defined timer handler, there will exist a drift(need to spent some cycles),

so for the first timeout, actually it is (_expected_period + drift_), and this drift relies on hardware(ideally it's 0), we cannot make sure this drift won't beyond required bound on all platforms.
but for the later timeout, like 2nd, _periodic_data[2] - periodic_data[1] = (2nd timer isr) - (1st timer isr) = (expected period)_

image

File: arch/x86/core/Kconfig.ia32 [hunk 5]
```diff
@@ -137,8 +137,8 @@ endif # CPU_HAS_FPU
 
 config X86_FP_USE_SOFT_FLOAT
 	bool
-	prompt "Use Software Floating Point Operations" if !(NEWLIB_LIBC && !FPU)
-	default y if NEWLIB_LIBC && !FPU
+	prompt "Use Software Floating Point Operations" if !FPU
+	default y if !FPU
```
Comment (stephanosio) [inline arch/x86/core/Kconfig.ia32:141]: @dcpleung since you introduced this requirement initially, does this change sound reasonable?

FYI, all the other archs are using soft float when `CONFIG_FPU=n`.

File: tests/kernel/timer/timer_behavior/src/main.c (hunk 1 above)
Comment (teburd) [reply tests/kernel/timer/timer_behavior/src/main.c:73]: This is really confusing behavior. If the test is failing only on the first timeout where the timer fires over 100us later or earlier than expected including the tick rounding that seems like a bug in some way to me.

File: arch/x86/core/Kconfig.ia32 (hunk 5 above)
Comment (keith-packard) [reply arch/x86/core/Kconfig.ia32:141]: I don't understand why `CONFIG_X86_USE_SOFT_FLOAT` is even configurable by the user here; if you are using the FPU, Zephyr needs to know this, so `CONFIG_FPU` must be the inverse of `CONFIG_X86_USE_SOFT_FLOAT`.

Comment (dcpleung) [reply arch/x86/core/Kconfig.ia32:141]: This looks fine.

IIRC, there was some size differences if soft float is enabled even though floating point is never used. This is due to different GCC libraries being included. We might want to remove the prompt so that this behaves the same as other arch.

Comment (teburd) [reply arch/x86/core/Kconfig.ia32:141]: Or maybe this comes back having a Kconfig that does the right thing

e.g.

CONFIG_FLOAT with options

NO_FLOAT (no fpu usage, no soft float flags)
SOFT_FLOAT (no fpu usage, explicit soft float compiler flags)
HARD_FLOAT (fpu usage, error if HAS_FPU=n)
AUTO_FLOAT (use FPU if available, or soft float flags if not)

If the size output is actually different when not using floats and linking in soft float then that seems like we should have something like this potentially? Or if this isn't useful then we should do the above and note in the docs CONFIG_FPU=n implies soft float inclusion if the toolchain supports it (presumably does).

Comment (keith-packard) [reply arch/x86/core/Kconfig.ia32:141]: How would `NO_FLOAT` differ from `SOFT_FLOAT`? Do you expect the build system to generate errors if the application accidentally uses a bit of floating point math?

How would `HARD_FLOAT` differ from `AUTO_FLOAT`? Would you expect the system to fail to build if there wasn't an FPU?

I think the existing option to force soft float is exactly right; when set, you never use the FPU. When not set, you use any available FPU. Whether it's soft float by default is a separate question; I generally don't buy SoCs with an FPU if I'm not going to use it, but I don't know what other people do.

Comment (teburd) [reply arch/x86/core/Kconfig.ia32:141]: NO_FLOAT comes from my assumption the current x86 setup is there for a reason which is effectively the default today. The compiler will use the FPU instructions but result in an exception. The reasoning is code size being smaller from the explanation above by @dcpleung.

HARD_FLOAT would fail if CPU_HAS_FPU=n. 

AUTO_FLOAT should use the FPU if it exists, if not use software floating point from the toolchain with whatever flags that entails.

File: tests/kernel/timer/timer_behavior/src/main.c (hunk 1 above)
Comment (chen-png) [reply tests/kernel/timer/timer_behavior/src/main.c]: I kept the first timeout, because I found the drift won't beyond 100us on most platforms, but I added a new config TEST_TIMER_PERIOD_MAX_DRIFT_PERCENT for users to set expected percentage.

File: arch/x86/core/Kconfig.ia32 (hunk 5 above)
Comment (chen-png) [reply arch/x86/core/Kconfig.ia32]: I just removed the prompt of CONFIG_X86_USE_SOFT_FLOAT to make it non-configurable by user.

**Review by teburd — APPROVED** [review]

**Review by andyross — APPROVED** [review]
+1 for the timer math.  I'll leave the floating point toolchainery policy arguments to others.

**Review by stephanosio — APPROVED** [review]
`X86_FP_USE_SOFT_FLOAT` change looks ok to me.

It simply does not make sense to emit FPU instructions when FPU is not enabled (i.e. when `CONFIG_FPU=n`).

I would prefer to see `X86_FP_USE_SOFT_FLOAT` completely gone, but that is beyond the scope of this change.

**Review by jhedberg — APPROVED** [review]

**Review by enjiamai — APPROVED** [review]
Verified pass on nrf52840dk_nrf52840.

**Comment by keith-packard** [comment]
> I would prefer to see `X86_FP_USE_SOFT_FLOAT` completely gone, but that is beyond the scope of this change.

It seems similar to the ARM options where FPU drives an arm-specific option that then sets the compiler flags.

I think the only question I have is whether the x86 FPU changes should be broken out into a separate PR. Otherwise, the change seems good to me.
