### PR TITLE
Bluetooth: TBS: Fix NULL pointer issue in v3.7

### LINKED ISSUE #84148: 3.7: Bluetooth: TBS: TBS client may return NULL instead of the empty string in callbacks
**Describe the bug**
If the TBS client receives an empty value when reading a string, it treated that as NULL, but since empty strings are still strings, it should simply treat it as such, and provide `"\0"` instead. The callbacks are documented to return strings. 

**To Reproduce**
1. Build and flash the https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/tmap_peripheral from the 3.7 branch
2. Connect a Android 15 phone to the sample
3. See that URI list is empty when read but `NULL` provided to the callback

**Expected behavior**
Expect the TBS client to follow its documentation and always return a string when there's no read error. 

**Impact**
Confused developers. The TMAP sample would call `strlen` and `strncpy` on a NULL value. 

**Logs and console output**
```
CCP: Discovered GTBS
CCP: Discovered remote URI: �w
CCP initialized

```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: 1182a4ca73abf5c30be2f09261778700135ecd79 (v3.7-branch)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/84148

### CODE REVIEW

File: samples/bluetooth/tmap_peripheral/src/ccp_call_ctrl.c [hunk 1]
```diff
@@ -139,6 +140,11 @@ int ccp_originate_call(void)
 	int err;
 	char uri[CONFIG_BT_TBS_MAX_URI_LENGTH];
 
+	if (strlen(remote_uri) == 0U) {
+		printk("Remove does not support any URI schemes, cannot place call\n");
```
Comment (aescolar) [inline samples/bluetooth/tmap_peripheral/src/ccp_call_ctrl.c:144]:
```suggestion
		printk("Remote does not support any URI schemes, cannot place call\n");
```
?

File: samples/bluetooth/tmap_peripheral/src/ccp_call_ctrl.c [hunk 2]
```diff
@@ -139,6 +140,11 @@ int ccp_originate_call(void)
 	int err;
 	char uri[CONFIG_BT_TBS_MAX_URI_LENGTH];
 
+	if (strlen(remote_uri) == 0U) {
```
Comment (jhedberg) [inline samples/bluetooth/tmap_peripheral/src/ccp_call_ctrl.c:143]: Quite minor, but when you just want to know if the string is empty or not, `strlen()` is rather overkill since you end up iterating the entire string every time when you're actually only interested in the first byte. `if (str[0] == '\0')` is not the prettiest thing either, so it could be nice to have a helper for it.

**Review by jhedberg — APPROVED** [review]

**Review by nashif — APPROVED** [review]
