### PR TITLE
usb_c: Notify DPM of Unsupported message reception

### LINKED ISSUE #53939: USB C PD stack no callback for MSG_NOT_SUPPORTED_RECEIVED policy notify
**Describe the bug**
I am developing an application on a custom PCB having USB C PD capabilities with the STM32G473 MCU. I used the code provide in the sample.

I am testing the USB C PD application with a PD source which has 4 PDOs (5V/30A, 9V/3A, 15V/3A and 20V/3.25A)
At 15V and 20V the source send a `Vendor Defined Message PD_DATA_VENDOR_DEF` which I was able to debug and find out from the below code in `usbc_pe_snk_states.c, line 424`
```
...
		/* Extended Message Request */
		if (header.extended) {
			extended_message_not_supported(dev);
			return;
		} else if (header.number_of_data_objects > 0) {
			/* Data Messages */
			switch (header.message_type) {
			case PD_DATA_SOURCE_CAP:
				pe_set_state(dev, PE_SNK_EVALUATE_CAPABILITY);
				break;
			default:
				LOG_INF("MSG TYPE = %d", header.message_type);
				pe_set_state(dev, PE_SEND_NOT_SUPPORTED);
			}
			return;
...
```
The USB C stack throws log messages  like `<inf> usbc_stack: PE_Not_Supported` but the `Policy Notify callback` doesn't get called, so the application does not have a chance to handle the error.

**Impact**
The device's charger not functioning and the application cannot show an error, so has a high impact

**Logs and console output**
```
[00001779] <inf> usbc_stack: Unattached.SNK
[00001784] <inf> usbc_stack: AttachWait.SNK
[00001992] <inf> usbc_stack: Attached.SNK
[00001997] <inf> usbc_stack: PE_SNK_Startup
[00001997] <inf> app_ucpd: NOT_PD_CONNECTED
[00001997] <inf> usbc_stack: PRL_INIT
[00001997] <inf> usbc_stack: PRL_HR_Wait_for_Request
[00001997] <inf> usbc_stack: PRL_Tx_PHY_Layer_Reset
[00001997] <inf> usbc_stack: PRL_Tx_Wait_for_Message_Request
[00002002] <inf> usbc_stack: PE_SNK_Discovery
[00002007] <inf> usbc_stack: PE_SNK_Wait_For_Capabilities
[00002010] <inf> usbc_stack: RECV 41a1/4
[00002010] <inf> usbc_stack:    [0]0a11912c
[00002010] <inf> usbc_stack:    [1]0012d12c
[00002010] <inf> usbc_stack:    [2]0014b12c
[00002010] <inf> usbc_stack:    [3]00164145
[00002015] <inf> usbc_stack: PE_SNK_Evaluate_Capability
[00002015] <inf> app_ucpd: SOURCE_CAPABILITIES_RECEIVED
[00002015] <inf> usbc_stack: PE_SNK_Select_Capability
[00002015] <inf> app_ucpd: snk_mv = 20000, snk_ma = 3000, pos = 4
[00002017] <inf> usbc_stack: PRL_Tx_Wait_for_PHY_response
[00002021] <inf> usbc_stack: RECV 03a3/0
[00002021] <inf> usbc_stack: PRL_Tx_Wait_for_Message_Request
[00002021] <inf> app_ucpd: PWR 3A0
[00002026] <inf> usbc_stack: PE_SNK_Transition_Sink
[00002260] <inf> usbc_stack: RECV 05a6/0
[00002265] <inf> app_ucpd: TRANSITION_PS
[00002265] <inf> usbc_stack: PE_SNK_Ready
[00002322] <inf> usbc_stack: RECV 17af/1
[00002322] <inf> usbc_stack:    [0]ff00a002
[00002327] <inf> usbc_stack: MSG TYPE = 15
[00002327] <inf> usbc_stack: PE_Not_Supported
[00002328] <inf> usbc_stack: PRL_Tx_Wait_for_PHY_response
[00002333] <inf> usbc_stack: RECV 03a1/0
[00002333] <inf> usbc_stack: PRL_Tx_Wait_for_Message_Request
[00002339] <inf> usbc_stack: PE_SNK_Ready
[00003996] <inf> app_ucpd: Source Caps:
[00003996] <inf> app_ucpd: PDO 0:
[00003996] <inf> app_ucpd:      Type:              FIXED
[00003996] <inf> app_ucpd:      Current:           3000
[00003996] <inf> app_ucpd:      Voltage:           5000
[00003996] <inf> app_ucpd:      Peak Current:      1
[00003996] <inf> app_ucpd:      Uchunked Support:  0
[00003996] <inf> app_ucpd:      Dual Role Data:    1
[00003996] <inf> app_ucpd:      USB Comms:         0
[00003996] <inf> app_ucpd:      Unconstrained Pwr: 1
[00003996] <inf> app_ucpd:      USB Suspend:       0
[00003996] <inf> app_ucpd:      Dual Role Power:   0
[00003999] <inf> usb_cdc_acm: Device suspended
[00004046] <inf> app_ucpd: PDO 1:
[00004046] <inf> app_ucpd:      Type:              FIXED
[00004046] <inf> app_ucpd:      Current:           3000
[00004046] <inf> app_ucpd:      Voltage:           9000
[00004046] <inf> app_ucpd:      Peak Current:      1
[00004047] <inf> app_ucpd:      Uchunked Support:  0
[00004047] <inf> app_ucpd:      Dual Role Data:    0
[00004047] <inf> app_ucpd:      USB Comms:         0
[00004047] <inf> app_ucpd:      Unconstrained Pwr: 0
[00004047] <inf> app_ucpd:      USB Suspend:       0
[00004047] <inf> app_ucpd:      Dual Role Power:   0
[00004097] <inf> app_ucpd: PDO 2:
[00004097] <inf> app_ucpd:      Type:              FIXED
[00004097] <inf> app_ucpd:      Current:           3000
[00004097] <inf> app_ucpd:      Voltage:           15000
[00004097] <inf> app_ucpd:      Peak Current:      1
[00004097] <inf> app_ucpd:      Uchunked Support:  0
[00004097] <inf> app_ucpd:      Dual Role Data:    0
[00004097] <inf> app_ucpd:      USB Comms:         0
[00004097] <inf> app_ucpd:      Unconstrained Pwr: 0
[00004097] <inf> app_ucpd:      USB Suspend:       0
[00004097] <inf> app_ucpd:      Dual Role Power:   0
[00004147] <inf> app_ucpd: PDO 3:
[00004147] <inf> app_ucpd:      Type:              FIXED
[00004147] <inf> app_ucpd:      Current:           3250
[00004147] <inf> app_ucpd:      Voltage:           20000
[00004147] <inf> app_ucpd:      Peak Current:      1
[00004147] <inf> app_ucpd:      Uchunked Support:  0
[00004147] <inf> app_ucpd:      Dual Role Data:    0
[00004147] <inf> app_ucpd:      USB Comms:         0
[00004147] <inf> app_ucpd:      Unconstrained Pwr: 0
[00004147] <inf> app_ucpd:      USB Suspend:       0
[00004147] <inf> app_ucpd:      Dual Role Power:   0
```

**Environment:**
 - OS: Linux
 - Toolchain Zephyr SDK zephyr-v3.2.0-3518-g7b5780e007
 - Hardware: custom hardware using STM32G473

### PR DESCRIPTION
**Pull request by sambhurst**
Notify the Device Policy Manager when an unsupported message is received. Fixes issue raised in 
USB C PD stack no callback for MSG_NOT_SUPPORTED_RECEIVED policy notify #53939.

Fixes #53939.

Signed-off-by: Sam Hurst <sbh1187@gmail.com>

### CODE REVIEW

**Review by jfischer-no — APPROVED** [review]

File: subsys/usb/usb_c/usbc_pe_common.c [hunk 1]
```diff
@@ -898,6 +898,9 @@ static void pe_send_not_supported_entry(void *obj)
 
 	LOG_INF("PE_Not_Supported");
 
+	/* Notify the Device Policy Manager of unsupported message reception */
+	policy_notify(dev, MSG_NOT_SUPPORTED_RECEIVED);
```
Comment (DianaZig) [inline subsys/usb/usb_c/usbc_pe_common.c:902]: This is hard notification to name since we're sending a Not_supported message to say we received a not supported message.... how about UNSUPPORTED_MSG_RECEIVED?

**Review by carlescufi — APPROVED** [review]
