### PR TITLE
stm32: Fix adc implementation for G4  series

### LINKED ISSUE #43888: adc: stm32: compilation broken on G4 targets
**Describe the bug**
`twister -b -T tests/drivers/adc/adc_api/  -p nucleo_g474re`

```
/local/mcu/zephyrproject/zephyr/drivers/adc/adc_stm32.c: In function 'adc_stm32_setup_channels':
/local/mcu/zephyrproject/zephyr/drivers/adc/adc_stm32.c:806:34: error: 'ADC_CHANNEL_TEMPSENSOR' undeclared (first use in this function); did you mean 'ADC_CHANNEL_TEMPSENSOR_ADC5'?
  806 |   __LL_ADC_CHANNEL_TO_DECIMAL_NB(ADC_CHANNEL_TEMPSENSOR) == channel_id) {
```

**Expected behavior**
Should build

**Impact**
Blocks CI: https://github.com/zephyrproject-rtos/zephyr/pull/43384

### PR DESCRIPTION
**Pull request by erwango**
Following https://github.com/zephyrproject-rtos/zephyr/pull/42567, https://github.com/zephyrproject-rtos/zephyr/pull/43752 and https://github.com/zephyrproject-rtos/zephyr/pull/43805, fix G4 implementation in adc_stm32 driver.

Fixes #43888

~~Based on https://github.com/zephyrproject-rtos/zephyr/pull/43936 to avoid a checkpatch false positive.~~ Merged

### CODE REVIEW

**Comment by erwango** [comment]
^^@benediktibk

File: drivers/adc/adc_stm32.c [hunk 1]
```diff
@@ -802,13 +802,21 @@ static void adc_stm32_setup_channels(const struct device *dev, uint8_t channel_i
 {
 	const struct adc_stm32_cfg *config = dev->config;
 
+#ifdef CONFIG_SOC_SERIES_STM32G4X
 	if (config->has_temp_channel &&
-		__LL_ADC_CHANNEL_TO_DECIMAL_NB(ADC_CHANNEL_TEMPSENSOR) == channel_id) {
+	    ((__LL_ADC_CHANNEL_TO_DECIMAL_NB(LL_ADC_CHANNEL_TEMPSENSOR_ADC1) == channel_id) ||
```
Comment (benediktibk) [inline drivers/adc/adc_stm32.c:807]: Don't you also have to check the ADC index as well, when the defines are different depending on the ADC? Otherwise I suppose an issue could be somebody calling this function e.g. for ADC1 with LL_ADC_CHANNEL_TEMPSENSOR_ADC5?

Comment (erwango) [reply drivers/adc/adc_stm32.c:807]: Right, will fix it

**Comment by erwango** [comment]
Reported compliance issue is a false positive:
```
-:10: ERROR:SPACING: need consistent spacing around '*' (ctx:WxV)
#10: FILE: drivers/adc/adc_stm32.c:806:
+	ADC_TypeDef *adc = config->base;
```

**Comment by benediktibk** [comment]
LGTM

**Review by gmarull — DISMISSED** [review]

File: drivers/adc/adc_stm32.c [hunk 2]
```diff
@@ -802,13 +802,25 @@ static void adc_stm32_setup_channels(const struct device *dev, uint8_t channel_i
...
 
+#ifdef CONFIG_SOC_SERIES_STM32G4X
+	ADC_TypeDef *adc = config->base;
+
 	if (config->has_temp_channel &&
-		__LL_ADC_CHANNEL_TO_DECIMAL_NB(ADC_CHANNEL_TEMPSENSOR) == channel_id) {
+	    (((__LL_ADC_CHANNEL_TO_DECIMAL_NB(LL_ADC_CHANNEL_TEMPSENSOR_ADC1) == channel_id) &&
+	      (adc == ADC1)) ||
+	      (__LL_ADC_CHANNEL_TO_DECIMAL_NB(LL_ADC_CHANNEL_TEMPSENSOR_ADC5) == channel_id) &&
+	      (adc == ADC5))) {
```
Comment (ABOSTM) [inline drivers/adc/adc_stm32.c:812]: ADC5 not defined for all G4 MCU

**Review by ABOSTM — CHANGES_REQUESTED** [review]

**Review by FRASTM — DISMISSED** [review]

**Review by ABOSTM — DISMISSED** [review]

**Review by FRASTM — DISMISSED** [review]

**Comment by gmarull** [comment]
> Reported compliance issue is a checkpatch false positive:
> 
> ```
> -:10: ERROR:SPACING: need consistent spacing around '*' (ctx:WxV)
> #10: FILE: drivers/adc/adc_stm32.c:806:
> +	ADC_TypeDef *adc = config->base;
> ```

can likely be mitigated by adding `ADC_TypeDef` to `scripts/checkpatch/typedefsfile`

**Comment by erwango** [comment]
> can likely be mitigated by adding ADC_TypeDef to scripts/checkpatch/typedefsfile

Does it take wild cards? 
We get similar issue randomly on most `*_TypeDef`

**Review by ABOSTM — DISMISSED** [review]

**Review by FRASTM — DISMISSED** [review]

**Review by ABOSTM — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
