### PR TITLE
Bluetooth: controller: Prevent LLCP handling of must-expire events (BT_CTLR_CONN_META)

### LINKED ISSUE #23015: Ongoing LL control procedures fails with must-expire latency (BT_CTLR_CONN_META)
If an LL control procedure is active and slave (or master) collides with other event and loses, must-expire feature may cause wrong "lazy" information handed to LLCP, and make the state machine fail.
**Note:** Feature is under CONFIG_BT_CTLR_CONN_META, and not default enabled in Zephyr.

**Steps to reproduce the behavior**
The scenario is observed in simulation:
1. ADV scheduled
2. Slave event collides with ADV, and does not get air-time, but must-expire callback is issued
3. ull_slave hands over 0xFFFF as current latency to LLCP
4. LLCP misinterprets 0xFFFF, and calculates connection events incorrectly

**Expected behavior**
Must-expire events must be ignored in LLCP, as they basically "didn't happen", but LLL must still be called.

**Impact**
May cause assertions and malfunctions when using CONFIG_BT_CTLR_CONN_META.

### PR DESCRIPTION
**Pull request by mtpr-ot**
When a must-expire ticker callback is executed, it is important not to
call the LLCP state machine, as the lazy state is unavailable. The code
must rely on the next proper event to call ull_conn_llcp with an updated
non-zero lazy count.
**Note:** This is for BT_CTLR_CONN_META only, which is not default enabled.

Fixes: #23015

Signed-off-by: Morten Priess <mtpr@oticon.com>

### CODE REVIEW

**Review by thoh-ot — APPROVED** [review]

**Comment by mtpr-ot** [comment]
Closed/reopened to re-trigger CI

File: subsys/bluetooth/controller/ll_sw/ull_master.c [hunk 1]
```diff
@@ -621,14 +621,24 @@ void ull_master_ticker_cb(u32_t ticks_at_expire, u32_t remainder, u16_t lazy,
...
 
-	/* Handle any LL Control Procedures */
-	ret = ull_conn_llcp(conn, ticks_at_expire, lazy);
-	if (ret) {
-		return;
+#if defined(CONFIG_BT_CTLR_CONN_META)
+	/* If this is a must-expire callback, LLCP state machine does not need
+	 * to know. Will be called with lazy > 0 when scheduled in air.
+	 */
+	if (lazy != TICKER_LAZY_MUST_EXPIRE) {
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_master.c]:
```
if (!IS_ENABLED(CONFIG_BT_CTLR_CONN_META) || (lazy != TICKER_LAZY_MUST_EXPIRE)) {
...
}
```

**Review by cvinayak — CHANGES_REQUESTED** [review]

**Review by cvinayak — APPROVED** [review]
