### PR TITLE
usb: device_next: use slist to store completed transfer requests

### LINKED ISSUE #74058: UDC events silently dropped on queue full lead to USB stack issues
**Describe the bug**
`udc_submit_ep_event()` events are queued to `usbd_msgq` inside `usbd_event_carrier()`. The problem is that the function can silently fail to queue the event because `k_msgq_put()` is called with `K_NO_WAIT`:
https://github.com/zephyrproject-rtos/zephyr/blob/0781caf408459dfd6c91477cedb62a43912a8c51/subsys/usb/device_next/usbd_core.c#L34-L38

This can lead to all sort of issues, but two major issues have been notified so far:

- Endpoint events like `udc_submit_ep_event(dev, buf, -ECONNABORTED);` can be silently dropped, never making it to the class. Observed on MSC class that would not requeue the OUT transfer because it never received the `-ECONNABORTED` on the request it submitted. The only solution was to reset the CPU (bus reset was not enough).
- VBUS ready/removed sequence can fill the queue, leading to e.g. VBUS removed being processed last while the last attempted-to-submit-but-silently-dropped was VBUS ready (or vice versa).

**To Reproduce**

The following ways to fill the message queue were identified so far:
- A task prevents context switches for more than 1.25 ms while the device is connected to host at high-speed. The SOF events are submitted in interrupt handler routine, filling whole queue, leaving no room for other events. If `udc_submit_ep_event` is called before USB stack pops the SOFs from `usbd_msgq`, the events are silently dropped.
- Rapid VBUS ready/removed sequence.

**Expected behavior**
Queued endpoint events are never dropped, i.e. there is always a matching `struct usbd_class_api` `request` call for every successful `usbd_ep_enqueue()`.

**Impact**
If the issue trigger, the stack can cease to work until device reboot.

**Logs and console output**
Console output irrelevant, the underlying issue is that things that must never be silently dropped can be dropped.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.5
 - Commit SHA or Version used: 2efc447c1b41efd23447ea180731d673114f06d8

**Additional context**
"Catching up" with not handled SOFs do not make much sense and can lead to avalanche effects if too many SOFs are queued for handling.

### PR DESCRIPTION
**Pull request by jfischer-no**
USBD_MAX_UDC_MSG configures the number of events coming from the UDC driver that the stack can keep. This can be filled very quickly if there would be multiple bus events for some reason, or function handlers of those events are blocked for long time. As a consequence, subsequent events could be dropped, and completed transfers not handled. To avoid it, we can store completed transfer requests in a slist and check it on every event.

Resolves: #74058

### CODE REVIEW

File: include/zephyr/usb/usbd.h [hunk 1]
```diff
@@ -287,6 +287,10 @@ struct usbd_context {
 	const struct device *dev;
 	/** Notification message recipient callback */
 	usbd_msg_cb_t msg_cb;
+	/** slist to keep endpoint events */
+	sys_slist_t ep_events;
```
Comment (cfriedt) [inline include/zephyr/usb/usbd.h:291]: I'm sure it was probably considered, but if not, another option is to use `sys_dlist_t`. There is  no additional cost in storage, and list elements can be removed efficiently from any point.

**Review by cfriedt — APPROVED** [review]

File: include/zephyr/usb/usbd.h (hunk 1 above)
Comment (tmon-nordic) [reply include/zephyr/usb/usbd.h:291]: The events are processed in FIFO manner, so the advantage of "list elements can be removed efficiently from any point" doesn't seem necessary.

File: subsys/usb/device_next/usbd_core.c [hunk 2]
```diff
@@ -138,6 +162,13 @@ static ALWAYS_INLINE void usbd_event_handler(struct usbd_context *const uds_ctx,
 {
 	int err = 0;
 
+	/* Always check if there is a completed transfer request. */
+	event_handler_ep_request(uds_ctx);
+	if (event->type == UDC_EVT_EP_REQUEST) {
+		/* It has already been handled and cannot be another event type. */
+		return;
+	}
```
Comment (tmon-nordic) [inline subsys/usb/device_next/usbd_core.c:170]: I would prefer to keep the `case UDC_EVT_EP_REQUEST` under switch below, i.e.
```
case UDC_EVT_EP_REQUEST:
	/* It has already been handled */
	break;
```

Functionality wise this is equivalent to the `if` above, but it makes it clear that there is no omission in the switch.

File: subsys/usb/device_next/usbd_core.c [hunk 3]
```diff
@@ -138,6 +162,13 @@ static ALWAYS_INLINE void usbd_event_handler(struct usbd_context *const uds_ctx,
 {
 	int err = 0;
 
+	/* Always check if there is a completed transfer request. */
```
Comment (tmon-nordic) [inline subsys/usb/device_next/usbd_core.c:165]: Please add note that this check is really a workaround for `usbd_event_carrier()` dropping messages on full queue, because otherwise the reason for unconditionally calling `event_handler_ep_request()` is not really obvious.

**Review by tmon-nordic — APPROVED** [review]
