### PR TITLE
test: arch: arm: arm_interrupt: clear FPSCR register in ISR

### LINKED ISSUE #31982: tests: kernel: queue: regression introduced by FPU sharing PR #31772
**Describe the bug**
Following tests:
* tests/kernel/queue/kernel.queue
* tests/arch/arm/arm_interrupt/arch.interrupt.arm
* tests/arch/arm/arm_interrupt/arch.interrupt.extra_exception_info
* tests/arch/arm/arm_interrupt/arch.interrupt.no_optimizations

are now failed on stm32f3_disco.
This is a regression introduced by PR #31772, test is passed before this PR and failed after.
Error message is not the same depending on test,
but in one case I got stack overflow. So I tried to enlarge MAIN_STACK_SIZE to 2048. It doesn't help.
I also increase IDLE_STACK_SIZE, ISR_STACK_SIZE and SYSTEM_WORKQUEUE_STACK_SIZE
but test is still failed.
Note: I could not reproduce issue on windows, only reproduced on Linux (different toolchain)

**To Reproduce**
1. twister -N --device-testing --hardware-map ../map.yaml -c  -p stm32f3_disco -T tests/kernel/queue/
2. See error

**Expected behavior**
test passed

**Logs and console output**
```
*** Booting Zephyr OS build v2.5.0-rc1-261-gfb2b77c9952f  ***
Running test suite queue_api
===================================================================
START - test_queue_supv_to_user
PASS - test_queue_supv_to_user
===================================================================
START - test_queue_alloc_prepend_user
PASS - test_queue_alloc_prepend_user
===================================================================
START - test_queue_alloc_append_user
PASS - test_queue_alloc_append_user
===================================================================
START - test_auto_free
PASS - test_auto_free
===================================================================
START - test_queue_thread2thread
PASS - test_queue_thread2thread
===================================================================
START - test_queue_thread2isr
PASS - test_queue_thread2isr
===================================================================
START - test_queue_isr2thread
PASS - test_queue_isr2thread
===================================================================
START - test_queue_get_2threads
PASS - test_queue_get_2threads
===================================================================
START - test_queue_get_fail
PASS - test_queue_get_fail
===================================================================
START - test_queue_loop
* Pass data by queue in loop 0
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 1
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 2
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 3
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 4
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 5
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 6
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 7
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 8
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 9
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queue append ---> main queue find and remove
main queue get
* Pass data by queue in loop 10
main queue append ---> isr queue find and remove
isr queue get
isr queue append ---> thread queue find and remove
thread queue get
thread queueE: ***** MPU FAULT *****
E:   Stacking error (context area might be not valid)
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x01000000
E: s[ 0]:  0x00000000  s[ 1]:  0x00000000  s[ 2]:  0x00000000  s[ 3]:  0x00000000
E: s[ 4]:  0x00000000  s[ 5]:  0x00000000  s[ 6]:  0x00000000  s[ 7]:  0x00000000
E: s[ 8]:  0x00000000  s[ 9]:  0x00000000  s[10]:  0x00000000  s[11]:  0x00000000
E: s[12]:  0x00000000  s[13]:  0x00000000  s[14]:  0x00000000  s[15]:  0x00000000
E: fpscr:  0x00000000
E: Faulting instruction address (r15/pc): 0x0800d432
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x20000718 (unknown)
Caught system error -- reason 2 0
Fatal error was unexpected, aborting...
```

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain Zephyr SDK
 - Commit SHA fb2b77c9952f3435b1a264becb32a1043ac2e899

### PR DESCRIPTION
**Pull request by ABOSTM**
test: arch: arm: arm_interrupt: clear FPSCR register in ISR

Clear Floating Point Status and Control Register (FPSCR),
in case FPU IRQ is selected by the test as "Available IRQ line"

Fixes #31982

### CODE REVIEW

**Comment by ABOSTM** [comment]
Note: I am not sure about the switches used.
Other switches may be more appropriate.

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c [hunk 1]
```diff
@@ -191,6 +191,13 @@ void arm_isr_handler(const void *args)
 {
 	ARG_UNUSED(args);
 
+#if defined(CPU_HAS_FPU) && defined(ARM)
```
Comment (galak) [inline tests/arch/arm/arm_interrupt/src/arm_interrupt.c:194]: When wouldn't `ARM` be defined for this specific code/test?

Comment (ioannisg) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c:194]: Agreed, the directive here should be: 
`#if defined(CONFIG_CPU_CORTEX_M) && defined(CONFIG_FPU) && defined(CONFIG_FPU_SHARING)`

CPU_HAS_FPU is not good here, cause the SoC may support FPU, but if the build doesn't, there is no need to clear any FP system control registers, and in fact, it may lead to co-processor faults.

The test is currently available for Cortex-M, so the CONFIG_CPU_CORTEX_M is currently redundant, but eventually we may want to support Cortex-R and 32 bit Cortex-A, hence my suggestion to add it.

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c [hunk 2]
```diff
@@ -191,6 +191,13 @@ void arm_isr_handler(const void *args)
...
+	/* Clear Floating Point Status and Control Register (FPSCR),
```
Comment (ioannisg) [inline tests/arch/arm/arm_interrupt/src/arm_interrupt.c:195]: add a sentence "...to prevent from having the interrupt line set to pending again, in case FPU IRQ is...."

**Review by ioannisg — CHANGES_REQUESTED** [review]
Thanks for the PR @ABOSTM.
So, this workaround should work in the edge case where the selected IRQ line found and used in the test happens to be the FPU NVIC IRQ line. To the best of my knowledge only the STM32F3 has this peculiarity.

I left some comments inline, please attend.

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c (hunk 1 above)
Comment (ABOSTM) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c]: done

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c (hunk 2 above)
Comment (ABOSTM) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c:196]: Done

**Review by ioannisg — APPROVED** [review]

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c [hunk 3]
```diff
@@ -191,6 +191,15 @@ void arm_isr_handler(const void *args)
 {
 	ARG_UNUSED(args);
 
+#if defined(CONFIG_CPU_CORTEX_M) && defined(CONFIG_FPU) &&
```
Comment (ioannisg) [inline tests/arch/arm/arm_interrupt/src/arm_interrupt.c:194]: probably need an "\" here

Comment (ABOSTM) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c]: Yes sure. Sorry. Fixed.

**Comment by ioannisg** [comment]
Though this seems to fix your issue, @ABOSTM , for a proper fix for FPU_SHARING in this test, we also need to get #32041 in. We could do this post 2.5.0 release if @nashif does not want to merge that now. I've not noticed any failures of this test in cortex-m platforms so #32041 could wait, perhaps

**Review by erwango — APPROVED** [review]
