### PR TITLE
pm: device_runtime: allow calling pm_device_runtime_get from ISRs

### LINKED ISSUE #60784: Potential race condition in uart console when using pm_device_runtime_get
**Describe the bug**
`pm_device_runtime_get()` is expected to be used only from thread context as it is using semaphore to protect resources but when it is called from the interrupt context it will proceed without taking the semaphore because return value from `k_sem_take` is ignored. It is used by `console_out` function in `uart_console.c` which can be called from any context (e.g. printk used in the interrupt context) so potential race can occur.

There are two topics in that bug:
- clarification of `pm_device_runtime_get()` when called from an interrupt context. The easiest would be to just return error but in console case that would result in bytes being dropped whenever in the interrupt context,
- uart poll_out being called from multiple contexts that can preempt one another. This issue is quite old as I recall discussions like #10512. Using poll_out for printk is user friendly (immediate output during single stepping, no dependency to interrupts, threads) but has many drawbacks (one found here, complex driver implementation to allow multiple users of poll_out). So it might be worth to reconsider buffered console.

### PR DESCRIPTION
**Pull request by gmarull**
pm_device_runtime_get() uses a semaphore to protect resources.
pm_device_runtime_get() blocked forever until obtaining the lock, making
it unusable from contexts where blocking is not allowed, e.g. ISRs. With
this patch, we give the chance to use the function from an ISR by not
waiting on the lock and returning -EWOULDBLOCK instead. If device is
suspending (from a previous put_async() operation) the same value is
returned as we can't wait either.

Fixes #60784

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]
LGTM

**Review by carlocaione — DISMISSED** [review]

**Comment by nordic-krch** [comment]
As mentioned in the issue. From uart console perspective it's not good as we won't be able to send any bytes from interrupt context when runtime power management is enabled. `printk` states "output is send immediately without any  mutual exclusion of buffering" but now it will be dropped.

**Comment by gmarull** [comment]
> As mentioned in the issue. From uart console perspective it's not good as we won't be able to send any bytes from interrupt context when runtime power management is enabled. `printk` states "output is send immediately without any mutual exclusion of buffering" but now it will be dropped.

I know, this is probably a separate issue.

**Comment by JordanYates** [comment]
Given that `k_sem_take` tries to work in an interrupt when provided `K_NO_WAIT`, could this not be done by changing the timeout argument if we detect we are in an ISR? This would at least give the call a chance to succeed if the device is uncontested.

File: subsys/pm/device_runtime.c [hunk 1]
```diff
@@ -145,6 +145,10 @@ int pm_device_runtime_get(const struct device *dev)
 	}
 
 	if (!k_is_pre_kernel()) {
+		if (k_is_in_isr()) {
+			return -EWOULDBLOCK;
+		}
+
 		(void)k_sem_take(&pm->lock, K_FOREVER);
```
Comment (JordanYates) [inline subsys/pm/device_runtime.c:152]: Suggestion:
```
rc = k_sem_take(&pm->lock, k_is_in_isr() ? K_NO_WAIT : K_FOREVER);
if (rc == -EAGAIN) {
  return -EWOULDBLOCK;
}
```

**Review by JordanYates — CHANGES_REQUESTED** [review]

File: subsys/pm/device_runtime.c (hunk 1 above)
Comment (gmarull) [reply subsys/pm/device_runtime.c]: good point, I've updated the code and handled the suspending state as well.

**Review by JordanYates — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by tmleman — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
