### PR TITLE
tests: kernel: mbox: fix uninitialized scalar variable of coverity

### LINKED ISSUE #32934: [Coverity CID :219511] Uninitialized scalar variable in tests/kernel/mbox/mbox_api/src/test_mbox_api.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/tests/kernel/mbox/mbox_api/src/test_mbox_api.c

Category: Uninitialized variables
Function: `thread_mbox_put_block_data`
Component: Tests
CID: [219511](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=219511)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/tests/kernel/mbox/mbox_api/src/test_mbox_api.c#L509

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by enjiamai**
Given an zero initialized value before using struct k_mbox_msg, to fix
CID: 219511.
Fix #32934

Signed-off-by: Enjia Mai <enjiax.mai@intel.com>

### CODE REVIEW

**Review by pabigot — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

File: tests/kernel/mbox/mbox_api/src/test_mbox_api.c [hunk 1]
```diff
@@ -480,7 +480,7 @@ void test_mbox_data_get_null(void)
 static void thread_mbox_get_block_data(void *p1, void *p2, void *p3)
 {
 	k_sem_take(&sync_sema, K_FOREVER);
-	struct k_mbox_msg bdmsg;
+	struct k_mbox_msg bdmsg = {0};
```
Comment (andyross) [inline tests/kernel/mbox/mbox_api/src/test_mbox_api.c:483]: FWIW: I recognize these lines because I just made these elements static in the big xtensa series (they're shared between threads and can't live on the stack when KERNEL_COHERENCE=y).  Looks like I have a rebase collision in my future.

**Review by andyross — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

File: tests/kernel/mbox/mbox_api/src/test_mbox_api.c (hunk 1 above)
Comment (enjiamai) [reply tests/kernel/mbox/mbox_api/src/test_mbox_api.c:483]: Oh, hope this won't  bring you too much trouble. And thanks for let me understand this point, does that mean in the future this would be handled implicitly, or we just make it static for all this? or might be like that:  
```
#if CONFIG_KERNEL_COHERENCE=y
static struct k_mbox_msg bdmsg;
#else
struct k_mbox_msg bdmsg = {0};
#endif
```

Comment (andyross) [reply tests/kernel/mbox/mbox_api/src/test_mbox_api.c:483]: It was just a passing note.  But yes, if it were static it wouldn't need an initializer to fix this issue.

Comment (enjiamai) [reply tests/kernel/mbox/mbox_api/src/test_mbox_api.c:483]: Got it, thanks for notifying this~^^
