### PR TITLE
tests: Bluetooth: Tester: Fix GATT Notify Multiple BTP command

### LINKED ISSUE #98971: Bluetooth GATT/SR/GAN/BV-02-C qualification test is failing in automated setup
### Describe the bug

Test is failing in automated setup due to issues in tester application GATT Multiple Notification BTP command.  Since CONFIG_ASAN=y is now enabled for native build mentioned issues result in sanitizer error and termination of tester app during test execution.

Note that this is a regression since CONFIG_ASAN is enabled, yet previously this was working only by chance.

### Regression

- [x] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sjanc**
This fix multiple issues with command implementation:
 - lack of LE to host convertion
 - using strtoul() on non-string data
 - passing stack variable as attr data (which must be present until notification is sent)

This was affecting GATT/SR/GAN/BV-02-C qualification test case.

Fixes #98971

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]

File: tests/bluetooth/tester/src/btp_gatt.c [hunk 1]
```diff
@@ -2133,14 +2133,23 @@ static uint8_t notify_mult(const void *cmd, uint16_t cmd_len,
...
-			server_db[0].handle];
+		const struct bt_gatt_attr *attr;
+		const struct gatt_value *value;
+		uint16_t handle = sys_le16_to_cpu(cp->attr_id[i]);
+
+		if (!IN_RANGE(handle, server_db_start_handle,
+			      server_db_start_handle + SERVER_MAX_ATTRIBUTES)) {
+			LOG_ERR("ATT handle %u not in server DB range", handle);
+			return BTP_STATUS_FAILED;
+		}
```
Comment (Thalley) [inline tests/bluetooth/tester/src/btp_gatt.c:2144]: Is this a valid check? 

If `server_db` only has e.g. 10 attributes initialized, and handle is `20`, then this doesn't fail, but shouldn't it? 

Should `attr_count` be used instead of `SERVER_MAX_ATTRIBUTES`?

Comment (sjanc) [reply tests/bluetooth/tester/src/btp_gatt.c:2144]: it should!  good catch

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
