### PR TITLE
tests: smp: cancel CONFIG_MP_NUM_CPUS limit of some testcases

### LINKED ISSUE #33558: qemu_cortex_a53_smp and qemu_x86_64 failed in tests/kernel/condvar/condvar while enabling for SMP
**Describe the bug**
Our new added test case try to remove the limit of CONFIG_MP_NUM_CPUS=1 for tests/kernel/condvar/ testing. Please refer to PR #33547. 
There are two test case failed while removing the CONFIG_MP_NUM_CPUS=1 
(1) test_condvar_usecase_broadcast
(2) test_condvar_usecase_signal

**To Reproduce**
1.  Edit the "tests/kernel/condvar/condvar_api/prj.conf", then comment or remove the line CONFIG_MP_NUM_CPUS=1.

2. Run command:  west build tests/kernel/smp -p auto -b qemu_cortex_a53_smp(or qemu_x86_64) -t run
 or twister -T tests/kernel/smp  -p qemu_cortex_a53(or -p qemu_x86_64(or qemu_x86_64) 

Test cases failed on qemu_cortex_a53_smp and qemu_x86_64 

3. It will hang up the test case mentioned above. See the error log below, please:

**Expected behavior**
Test cases are pass as expected.
```
===================================================================
START - test_condvar_usecase_signal
Starting watch_count: thread 1
 PASS - test_condvar_usecase_signal in 2.102 seconds
===================================================================
START - test_condvar_usecase_broadcast
Starting watch_count: thread 1
 PASS - test_condvar_usecase_broadcast in 2.100 seconds
===================================================================
```

**Impact**
Not clear. 

**Logs and console output**
Error log looks like this:
```
===================================================================
START - test_condvar_usecase_signal
Starting watch_count: thread 1

```
or 
```
===================================================================
START - test_condvar_usecase_broadcast
Starting watch_count: thread 1

```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK-0.12.3
 - Commit SHA  911ba334a06ac55e28856e49a694083974196f8c

**Additional context**

### PR DESCRIPTION
**Pull request by enjiamai**
This PR includes 2 commits:
The first commit try to remove CONFIG_MP_NUM_CPUS=1 configuration for the test of condvar,
sysmutex and semaphore, in order to test SMP condition more.

The second commit makes some changes on codvar test cases to fit SMP.
1. Re-init the mutex to prevent affection from previous test cases.
2. Shorter the test case execution time.
Fixes #33558.

Signed-off-by: Enjia Mai <enjiax.mai@intel.com>

### CODE REVIEW

**Review by LeiW000 — APPROVED** [review]

File: tests/kernel/semaphore/semaphore/src/main.c [hunk 1]
```diff
@@ -1327,11 +1327,11 @@ void test_main(void)
 			 ztest_user_unit_test(test_sem_give_from_thread),
 			 ztest_user_unit_test(test_sem_take_no_wait),
 			 ztest_user_unit_test(test_sem_take_no_wait_fails),
-			 ztest_1cpu_user_unit_test(test_sem_take_timeout_fails),
-			 ztest_user_unit_test(test_sem_take_timeout),
-			 ztest_1cpu_user_unit_test(test_sem_take_timeout_forever),
+			 ztest_user_unit_test(test_sem_take_timeout_fails),
+			 ztest_1cpu_user_unit_test(test_sem_take_timeout),
```
Comment (dcpleung) [inline tests/kernel/semaphore/semaphore/src/main.c:1331]: Why are you changing the `test_sem_take_timeout` to 1cpu?

Comment (enjiamai) [reply tests/kernel/semaphore/semaphore/src/main.c:1331]: Hi, because based on the design of this test case "test_sem_take_timeout", 1cpu is necessary, I believe this not design for multi-core in the first place. It will fail in more than two core. The test logic here is to spawn a thread,  check its count,  then take a semaphore(the spawned thread is scheduled to run). But with multi-core, it would be scheduled right away before the check count, then the test case will fail.
So I make it 1cpu here. Of course, I can slightly change the test code to adapt to multi-core, but I suggest just keep it this way because the test goal is simple here. How do you think about it? Thanks for you review ^^

Comment (enjiamai) [reply tests/kernel/semaphore/semaphore/src/main.c:1331]: Hi @dcpleung, do you think should I not make it 1cpu here? thanks~

Comment (dcpleung) [reply tests/kernel/semaphore/semaphore/src/main.c:1331]: It has been working without 1cpu. So I think we should keep it that way, especially what you are trying to do in this PR is to enable testing on multiple CPUs.

Comment (enjiamai) [reply tests/kernel/semaphore/semaphore/src/main.c:1331]: OK, got it, I think you are right. This makes it more consistent with this PR. I will update this, thanks for your suggestion!

File: tests/kernel/condvar/condvar_api/src/main.c [hunk 2]
```diff
@@ -557,6 +557,10 @@ void _condvar_usecase(long multi)
 
 }
 
+/* Skip these two board when trying to use CONFIG_MP_NUM_CPUS > 1
+ * please see issue #33558
+ */
+#if !defined(CONFIG_BOARD_QEMU_CORTEX_A53) && !defined(CONFIG_X86_64)
```
Comment (andyross) [inline tests/kernel/condvar/condvar_api/src/main.c:563]: It's cleaner to write this inline instead of #if'ing the whole test function, e.g.:

```c
 void test_condvar_usecase_signal(void)
{
    if (IS_ENABLED(CONFIG_BOARD_QEMU_CORTEX_A53)
        || IS_ENABLED(CONFIG_X86_64)) {
        /* See #33558  */
        ztest_test_skip();
    }
    _condvar_usecase(0);
}
```

File: tests/kernel/semaphore/semaphore/src/main.c [hunk 3]
```diff
@@ -21,6 +21,7 @@
 #define TOTAL_THREADS_WAITING (5)
 
 #define SEC2MS(s) ((s) * 1000)
+#define QSEC2MS(s) ((s) * 250)
```
Comment (andyross) [inline tests/kernel/semaphore/semaphore/src/main.c:24]: Why is this changing units?  Seems like this needs an explanation.

Comment (enjiamai) [reply tests/kernel/semaphore/semaphore/src/main.c:24]: Hi, @andyross , I change this because I got the following message when I run this case.
```
===================================================================
START - test_sem_multiple_take_and_timeouts

    Assertion failed at WEST_TOPDIR/zephyr/subsys/testsuite/ztest/src/ztest.c:125: cpu_hold: (dt < 3000 is false)
1cpu test took too long (5010 ms)
 FAIL - test_sem_multiple_take_and_timeouts in 5.7 seconds
===================================================================
```
So I try to make the time unit smaller to avoid this and save some execution time (without affecting the test case result)

```
===================================================================
START - test_sem_multiple_take_and_timeouts
 PASS - test_sem_multiple_take_and_timeouts in 1.255 seconds
===================================================================

```
Thank you!

File: tests/kernel/condvar/condvar_api/src/main.c (hunk 2 above)
Comment (enjiamai) [reply tests/kernel/condvar/condvar_api/src/main.c:563]: Got it, I have refined it based on your suggestion, thanks for pointing out this!

Comment (enjiamai) [reply tests/kernel/condvar/condvar_api/src/main.c]: got learned again, thanks!

**Review by LeiW000 — APPROVED** [review]

**Review by andyross — APPROVED** [review]
