### PR TITLE
driver: i2c: i2c_ll_stm32: add error handling in i2c_stm32_error for I2C target mode

### LINKED ISSUE #92383: driver: i2c: i2c_ll_stm32: no error handling in i2c_stm32_error for i2c target
### Describe the bug

I wrote an i2c slave app just like 'samples/drivers/i2c/custom_target' using i2c callbacks to process data transfers between i2c master.

The problem is when data transfers in process and the master shutdown by itself, how to get noticed the i2c bus error irq occurs and handle it, because the function 'i2c_stm32_error' will do nothing if dev is slave.

https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/i2c/i2c_ll_stm32_v1.c#L595-L606

### PR DESCRIPTION
**Pull request by juickar**
Taking over #95984 as mentioned [here](https://github.com/zephyrproject-rtos/zephyr/pull/95984#issuecomment-3405289008)

Main differences with the first PR are:
- Branch is rebased.
- Removed the `i2c_stm32_master_mode_end` calls from `drivers/i2c/i2c_ll_stm32_v2.c` because it has been removed with this [commit](https://github.com/zephyrproject-rtos/zephyr/commit/c8b9697eb390ae88fe326aa68173741d2d479592).

Fixes #92383

### CODE REVIEW

File: drivers/i2c/i2c_ll_stm32_v2.c [hunk 1]
```diff
@@ -613,6 +620,12 @@ int i2c_stm32_error(const struct device *dev)
 	if (LL_I2C_IsActiveFlag_BERR(i2c)) {
 		LL_I2C_ClearFlag_BERR(i2c);
 		data->current.is_err = 1U;
+#if defined(CONFIG_I2C_TARGET)
+		if (error_cb != NULL) {
+			error_cb(data->slave_cfg, I2C_ERROR_GENERIC);
+		}
+#endif
+		goto end;
 	}
```
Comment (etienne-lms) [inline drivers/i2c/i2c_ll_stm32_v2.c:630]: `end` sequence must be updated:
```patch
 end:
+#if defined(CONFIG_I2C_TARGET)
+	if (data->slave_attached && !data->master_active) {
+		return -EIO;
+	}
+#endif
 	i2c_stm32_disable_transfer_interrupts(dev);
 	/* Wakeup thread */
 	k_sem_give(&data->device_sync_sem);
 	return -EIO;
}
```
(with indentation updates)

File: drivers/i2c/i2c_ll_stm32_v2.c [hunk 2]
```diff
@@ -593,15 +593,22 @@ int i2c_stm32_error(const struct device *dev)
...
+		error_cb = data->slave_cfg->callbacks->error;
 	}
 #endif
 
 	if (LL_I2C_IsActiveFlag_ARLO(i2c)) {
 		LL_I2C_ClearFlag_ARLO(i2c);
 		data->current.is_arlo = 1U;
+#if defined(CONFIG_I2C_TARGET)
+		if (error_cb != NULL) {
+			error_cb(data->slave_cfg, I2C_ERROR_GENERIC);
```
Comment (etienne-lms) [inline drivers/i2c/i2c_ll_stm32_v2.c]: `I2C_ERROR_ARBITRATION`

**Review by etienne-lms — CHANGES_REQUESTED** [review]
I think you should add you're S-o-b tag to the commits in additions to @kbidani's one.

File: drivers/i2c/i2c_ll_stm32_v2.c (hunk 1 above)
Comment (juickar) [reply drivers/i2c/i2c_ll_stm32_v2.c:630]: done

File: drivers/i2c/i2c_ll_stm32_v2.c (hunk 2 above)
Comment (juickar) [reply drivers/i2c/i2c_ll_stm32_v2.c]: done

**Comment by erwango** [comment]
@teburd PTAL and advise if ok for V4.3.0

**Review by etienne-lms — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by erwango — APPROVED** [review]
