### PR TITLE
lorawan: adding settings NVM for LoRaWAN

### LINKED ISSUE #41773: LoRaWAN: Unable to correctly join networks of any version on LTS
**Describe the bug**

The LoRaWAN subsystem is unable to correctly join networks of any LoRaWAN protocol version on the LTS branch.
LoRaWAN fork: https://github.com/zephyrproject-rtos/loramac-node

The relevant versions for this issue:
1. v1.0.3 (Previous version)
2. v1.0.4 (Current version targeted by the Zephyr fork)
3. v1.1.x (Not supported at all by the release that the Zephyr fork is based upon)

The PR https://github.com/zephyrproject-rtos/loramac-node/pull/9 updated the release the fork was based upon from some older version (v1.0.3?) to v1.0.4. Part of the specification changes from v1.0.3 to v1.0.4 was a change in requirements around the device nonce value, sent in the join request as a way of avoiding replay attacks.

*LoRaWAN v1.0.3 Specification (6.2.4)*
> DevNonce is a random value.1 For each end-device, the network server keeps track of a certain number of DevNonce values used by the end-device in the past, and ignores join requests with any of these DevNonce values from that end-device.

*LoRaWAN v1.0.4 Specification (6.2.5)*
> DevNonce is a counter starting at 0 when the end-device is initially powered up and incremented with every Join-Request. A DevNonce value SHALL never be reused for a given JoinEUI value. If the end-device can be power-cycled, then DevNonce SHALL be persistent (e.g., stored in a non-volatile memory). Resetting DevNonce without changing JoinEUI will cause the Join Server to discard the Join-Requests of the end-device. For each end-device, the Join Server keeps track of the last DevNonce value used by the end device and ignores Join-Requests if DevNonce is not incremented.

With the changes in https://github.com/zephyrproject-rtos/loramac-node/pull/9, the DevNonce is no longer a random value, but instead restarts from 0 on each reboot. This results in network servers expecting either v1.0.3 or v1.04 to reject join requests due to duplicate DevNonce values. For a v1.0.3 we need to wait for the network servers internal cache to be evicted. For v1.0.4 we need to send an additional join request each time the device reboots. The Nth reboot will require at least N join requests before a join has a chance of succeeding. In both cases, for a device compliant with the join request backoff recommendations, this can quickly take hours.

At the same time, the LoRaWAN subsystem does not expose a mechanism for storing and restoring the NVM context required for correct operation under v1.0.4. This is currently a work in progress in #40193

This issue was picked up on in #36571, but was not followed through to the logical conclusion that we are now unable to properly join any network server compliant with the spec.

**To Reproduce**
Build the `zephyr/samples/subsys/lorawan/class_a` sample, and attempt to join a LoRaWAN network multiple times without clearing anything on the network server.

**Expected behavior**
The LoRaWAN subsystem should be able to correctly join network servers, ideally either v1.0.3 or v1.0.4 versions.

**Impact**
LoRaWAN functionality is significantly degraded when devices reboot for any reason (Faults, OTA upgrades etc).
The degradation increases with each reboot.

**Proposed Solution**

Merging #40193 into the LTS branch is likely too large a change to be accepted. Providing a mechanism to query and restore the loramac-node crypto NVS state is sufficient to fix this issue for both network types. This can be done by hooking into the `NvmDataChange` callback without additional changes to loramac-node.

**Environment (please complete the following information):**
 - v2.7.1 LTS

### PR DESCRIPTION
**Pull request by GiulianoFranchetto**
Adding a reference implementation of the Non-Volatile Memory module
needed to join any LoRaWAN network.

This NVM is based on the SETTINGS subsys to store all the required
key to join and communicate on a LoRaWAN network.

Without proper NVM, one may experience errors when using OTAA
to join the network, as the device may violate anti-replay
protection (depending on the version of LoRaWAN).

Fixes: #41773

Signed-off-by: Giuliano Franchetto <giuliano.franchetto@intellinium.com>

### CODE REVIEW

File: subsys/lorawan/lorawan.c [hunk 1]
```diff
@@ -14,6 +15,10 @@
 #include <LoRaMac.h>
 #include <Region.h>
 
+#if !defined(CONFIG_LORAWAN_NVM_NONE)
+#include "nvm/lorawan_nvm.h"
```
Comment (JordanYates) [inline subsys/lorawan/lorawan.c:19]: There is no real need to wrap this include in an `#if` in my opinion.

File: subsys/lorawan/lorawan.c [hunk 2]
```diff
@@ -599,6 +610,10 @@ static int lorawan_init(const struct device *dev)
 		return -EINVAL;
 	}
 
+#if !defined(CONFIG_LORAWAN_NVM_NONE)
```
Comment (JordanYates) [inline subsys/lorawan/lorawan.c:613]: I  believe the preferred pattern (when possible) is:
```
if (!IS_ENABLED(CONFIG_LORAWAN_NVM_NONE)) {
    lorawan_nvm_data_restore();
}
```

File: subsys/lorawan/nvm/Kconfig [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+choice LORAWAN_NVM
+	bool "LoRaWAN NVM backend"
+	default LORAWAN_NVM_SETTINGS if SETTINGS
+	default LORAWAN_NVM_NONE
+
+config LORAWAN_NVM_NONE
+	bool "No NVM backend for LoRaWAN"
+	help
+	  This configuration should only be used during testing as all
+	  the join request using OTAA will fail because of anti-replay
```
Comment (JordanYates) [inline subsys/lorawan/nvm/Kconfig:15]: "all join requests after a reboot using OTAA"

File: subsys/lorawan/nvm/lorawan_nvm.h [hunk 4]
```diff
@@ -0,0 +1,16 @@
+/*
+ * Copyright (c) 2022 Intellinium <giuliano.franchetto@intellinium.com>
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#ifndef LORAWAN_NVM_H
```
Comment (JordanYates) [inline subsys/lorawan/nvm/lorawan_nvm.h:7]: Other include files use guards in this format
`#ifndef ZEPHYR_INCLUDE_RANDOM_RAND32_H_`
so probably change this to
`ZEPHYR_INCLUDE_LORAWAN_NVM_H_`

File: subsys/lorawan/lorawan.c [hunk 5]
```diff
@@ -588,7 +595,11 @@ static int lorawan_init(const struct device *dev)
 	macPrimitives.MacMlmeIndication = MlmeIndication;
 	macCallbacks.GetBatteryLevel = getBatteryLevelLocal;
 	macCallbacks.GetTemperatureLevel = NULL;
+#if !defined(CONFIG_LORAWAN_NVM_NONE)
```
Comment (JordanYates) [inline subsys/lorawan/lorawan.c:598]: Same thing here with `IS_ENABLED`

**Review by JordanYates — CHANGES_REQUESTED** [review]
A few minor formatting and style suggestions

File: subsys/lorawan/lorawan.c (hunk 1 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/lorawan.c:19]: The include is not needed if ```CONFIG_LORAWAN_NVM_NONE``` is selected.
I can remove the ```#if``` but that would add a useless ```#include``` directive

File: subsys/lorawan/lorawan.c (hunk 2 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/lorawan.c:613]: done

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 6]
```diff
@@ -0,0 +1,211 @@
...
+	if (read_cb(cb_arg, tgt, len) != len) {
+		LOG_ERR("Can't load '%s' state, short read.",
+			log_strdup(key));
+		return -EINVAL;
+	}
+
+	return 0;
+}
+
+/* @formatter:off */
```
[the remark this answers is not in the document]
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/lorawan_nvm_settings.c:111]: Yes, sorry. It's a Clion comment

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 7]
```diff
@@ -0,0 +1,211 @@
...
+#define LOAD_SETTINGS(nvm, name)					\
+({									\
+int $err = -EAGAIN;							\
+if (strcmp(#name, key) == 0) {					\
```
[the remark this answers is not in the document]
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/lorawan_nvm_settings.c:115]: I need to check why they are not, as they are aligned on my computer...

File: subsys/lorawan/nvm/lorawan_nvm.h (hunk 4 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/lorawan_nvm.h:7]: done

File: subsys/lorawan/lorawan.c (hunk 5 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/lorawan.c]: done

File: subsys/lorawan/nvm/lorawan_nvm_settings.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/lorawan_nvm_settings.c]: The backslashes are still not aligned. I've used tabs to align them. Should I use spaces?

File: subsys/lorawan/nvm/Kconfig (hunk 3 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/Kconfig]: done

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 8]
```diff
@@ -0,0 +1,209 @@
...
+
+	LoRaMacNvmData_t *nvm = mibReq.Param.Contexts;
+
+	LOG_DBG("Crypto version: %"PRIu32", DevNonce: %d, JoinNonce: %"PRIu32,
+		mibReq.Param.Contexts->Crypto.LrWanVersion.Value,
+		mibReq.Param.Contexts->Crypto.DevNonce,
+		mibReq.Param.Contexts->Crypto.JoinNonce);
+
+	/* Wait for LoRa to be idle */
+	while (LoRaMacStop() != LORAMAC_STATUS_OK) {
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/nvm/lorawan_nvm_settings.c:54]: As spotted by @JordanYates, we can safely avoid stopping and starting the LoRaWAN stack here.

**Review by Mani-Sadhasivam — CHANGES_REQUESTED** [review]

File: subsys/lorawan/nvm/lorawan_nvm.h [hunk 9]
```diff
@@ -0,0 +1,41 @@
+/*
+ * Copyright (c) 2022 Intellinium <giuliano.franchetto@intellinium.com>
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#ifndef ZEPHYR_INCLUDE_LORAWAN_NVM_H_
```
[the remark this answers is not in the document]
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/lorawan_nvm.h]: done

File: subsys/lorawan/nvm/lorawan_nvm_settings.c (hunk 8 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/lorawan_nvm_settings.c]: done

**Comment by plmwd** [comment]
Are these changes good enough to be used for a small (school) project? I seem to be hitting this issue.

**Comment by GiulianoFranchetto** [comment]
> Are these changes good enough to be used for a small (school) project? I seem to be hitting this issue.

I think they are, but I need confirmation from @Mani-Sadhasivam

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 10]
```diff
@@ -0,0 +1,204 @@
...
+	SAVE_SETTINGS(nvm, LORAMAC_NVM_NOTIFY_FLAG_REGION_GROUP1, RegionGroup1)
+	SAVE_SETTINGS(nvm, LORAMAC_NVM_NOTIFY_FLAG_REGION_GROUP2, RegionGroup2)
+	SAVE_SETTINGS(nvm, LORAMAC_NVM_NOTIFY_FLAG_CLASS_B, ClassB)
+
+	settings_save();
+	/* Clean notification flag */
+	nvm_notify_flag = LORAMAC_NVM_NOTIFY_FLAG_NONE;
+
+	/* Restart LoRaMAC */
+	LoRaMacStart();
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/nvm/lorawan_nvm_settings.c:67]: Is this still necessary?

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 11]
```diff
@@ -0,0 +1,204 @@
...
+
+	err = settings_load_subtree_direct(LORAWAN_SETTINGS_BASE,
+					   on_setting_loaded,
+					   mibReq.Param.Contexts);
+	if (err) {
+		LOG_ERR("Could not load LoRaWAN settings, error %d", err);
+		return err;
+	}
+
+	LOG_DBG("LoRaWAN context restored");
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/nvm/lorawan_nvm_settings.c:190]: nit: This should be moved to the end of the function (i.e after restoring the context in LoRaMAC)

**Review by Mani-Sadhasivam — CHANGES_REQUESTED** [review]

**Comment by Mani-Sadhasivam** [comment]
> Are these changes good enough to be used for a small (school) project? I seem to be hitting this issue.

Yes you can. We will merge this PR soon into `main` branch and also backport to stable.

File: subsys/lorawan/nvm/lorawan_nvm_settings.c (hunk 11 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/lorawan_nvm_settings.c]: done

**Comment by Mani-Sadhasivam** [comment]
@GiulianoFranchetto Please merge `70a4bd7` with the initial one. There is no need of a separate commit for it.

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 12]
```diff
@@ -0,0 +1,202 @@
...
+	MibRequestConfirm_t mibReq;
+
+	/* Retrieve the actual context */
+	mibReq.Type = MIB_NVM_CTXS;
+	if (LoRaMacMibGetRequestConfirm(&mibReq) != LORAMAC_STATUS_OK) {
+		LOG_ERR("Could not get NVM context");
+		return -EINVAL;
+	}
+
+	err = settings_load_subtree_direct(LORAWAN_SETTINGS_BASE,
```
Comment (abxy) [inline subsys/lorawan/nvm/lorawan_nvm_settings.c:179]: It's possible (likely even) that this runs before the settings subsystem has been initialized. Even if an application were to call `settings_subsys_init()` in `main()` it would be too late since this code runs during initialization.

**Review by abxy — CHANGES_REQUESTED** [review]
Thanks for this PR! I'm eager to see it merged.

File: subsys/lorawan/nvm/lorawan_nvm_settings.c (hunk 12 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/nvm/lorawan_nvm_settings.c:179]: Now, I remember why I removed lorawan_init() from SYS_INIT. That's the problem I've faced when testing the NVM implementation.
Should we change lorawan_init() visibility to public, and require to call it in the main, after settings_load() has been called?

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 13]
```diff
@@ -0,0 +1,202 @@
...
+	SAVE_SETTINGS(nvm, LORAMAC_NVM_NOTIFY_FLAG_REGION_GROUP1, RegionGroup1)
+	SAVE_SETTINGS(nvm, LORAMAC_NVM_NOTIFY_FLAG_REGION_GROUP2, RegionGroup2)
+	SAVE_SETTINGS(nvm, LORAMAC_NVM_NOTIFY_FLAG_CLASS_B, ClassB)
+
+	settings_save();
+	/* Clean notification flag */
+	nvm_notify_flag = LORAMAC_NVM_NOTIFY_FLAG_NONE;
+}
+
+void lorawan_nvm_data_mgmt_event(uint16_t notifyFlags)
```
Comment (martinjaeger) [inline subsys/lorawan/nvm/lorawan_nvm_settings.c:67]: Also here: Please use correct coding style.
```suggestion
void lorawan_nvm_data_mgmt_event(uint16_t notify_flags)
```

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 14]
```diff
@@ -0,0 +1,202 @@
...
+
+	LOG_WRN("Unknown LoRaWAN setting: %s", log_strdup(key));
+	return 0;
+}
+
+int lorawan_nvm_data_restore(void)
+{
+	int err;
+	LoRaMacStatus_t status;
+	MibRequestConfirm_t mibReq;
```
Comment (martinjaeger) [inline subsys/lorawan/nvm/lorawan_nvm_settings.c:170]:
```suggestion
	MibRequestConfirm_t mib_req;
```

**Review by martinjaeger — CHANGES_REQUESTED** [review]
Thanks for working on a fix for the DevNonce issue, which I just came across while updating my firmware to newer Zephyr version.

I'm wondering where the nonce counter is actually increased after a successful join request. Couldn't spot it anywhere in the external LoRaMac-node code. Should it be done somewhere in this code?

Mainly got some style comments so far. Will try out the PR in the next days and give some more feedback.

I agree with @abxy that the macros should be made more memory-efficient, as they allocate many strings. Maybe it's sufficient to have one single error message at the end if any of the settings could not be loaded.

File: subsys/lorawan/nvm/lorawan_nvm_settings.c (hunk 12 above)
Comment (brian-level) [reply subsys/lorawan/nvm/lorawan_nvm_settings.c:179]: settings_subsys_init() is safe to call multiple times, and can be called in lorawan_init() inside the conditional right before lorawan_nvm_data_restore() is called

**Comment by martinjaeger** [comment]
I needed a quick solution for this issue to go ahead with my firmware development, so I came up with a simplified approach, see PR #43244. Ideally we would combine both PRs and provide both options in the future.

File: subsys/lorawan/lorawan.c [hunk 15]
```diff
@@ -576,7 +578,7 @@ int lorawan_start(void)
 	return 0;
 }
 
-static int lorawan_init(const struct device *dev)
+int lorawan_init(void)
```
Comment (martinjaeger) [inline subsys/lorawan/lorawan.c:581]: As far as I can see, this function is not called anywhere. Did I missed something?

Comment (GiulianoFranchetto) [reply subsys/lorawan/lorawan.c]: No, it's my bad. LoRa is not my priority right now, and I've made the code changed without testing it.
If possible, test this PR as I really don't have the bandwidth right now to do it.

Comment (martinjaeger) [reply subsys/lorawan/lorawan.c]: Ok, no problem. Just wanted to know what the status is and how we can go ahead. I'll have a look at your PR next week and do more testing.

File: subsys/lorawan/nvm/Kconfig [hunk 16]
```diff
@@ -0,0 +1,22 @@
...
+
+# Copyright (c) 2022 Intellinium <giuliano.franchetto@intellinium.com>
+# SPDX-License-Identifier: Apache-2.0
+
+choice LORAWAN_NVM
+	bool "LoRaWAN NVM backend"
+	default LORAWAN_NVM_SETTINGS if SETTINGS
+	default LORAWAN_NVM_NONE
+
+config LORAWAN_NVM_NONE
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/nvm/Kconfig:11]: Once #43244 gets merged, this Kconfig option should be used to select between the two implementations. So please change the help text accordingly.

File: subsys/lorawan/nvm/lorawan_nvm_settings.c [hunk 17]
```diff
@@ -0,0 +1,179 @@
...
+	LOG_WRN("Unknown LoRaWAN setting: %s", log_strdup(key));
+	return 0;
+}
+
+int lorawan_nvm_data_restore(void)
+{
+	int err;
+	LoRaMacStatus_t status;
+	MibRequestConfirm_t mib_req;
+
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/nvm/lorawan_nvm_settings.c:148]: Not a big deal, but adding a print would help during debugging:

LOG_DBG("Restoring LoRaWAN settings");

**Review by Mani-Sadhasivam — CHANGES_REQUESTED** [review]
I think this PR is ready to be merged but let's first merge #43244.

**Review by martinjaeger — DISMISSED** [review]
LGTM.

Only got some minor suggestions which are not blocking.

File: subsys/lorawan/lorawan.c [hunk 18]
```diff
@@ -212,13 +214,15 @@ static LoRaMacStatus_t lorawan_join_otaa(
 	mlme_req.Req.Join.Datarate = default_datarate;
 	mlme_req.Req.Join.NetworkActivation = ACTIVATION_TYPE_OTAA;
 
+#if !defined(CONFIG_LORAWAN_NVM_SETTINGS)
```
[the remark this answers is not in the document]
Comment (Mani-Sadhasivam) [reply subsys/lorawan/lorawan.c:217]: Yes, `IS_ENABLED()` should be used here.

File: subsys/lorawan/lorawan.c [hunk 19]
```diff
@@ -1,18 +1,20 @@
 /*
  * Copyright (c) 2020 Manivannan Sadhasivam <mani@kernel.org>
+ * Copyright (c) 2022 Intellinium <giuliano.franchetto@intellinium.com>
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/lorawan.c:3]: IANAL but I tend to put copyright only if it is a new file or I've made some significant changes to the existing file, like heavy refactoring etc,..

**Review by Mani-Sadhasivam — CHANGES_REQUESTED** [review]

File: subsys/lorawan/lorawan.c (hunk 19 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/lorawan.c:3]: what is the rule to choose between ```#if defined()``` and ```IS_ENABLED``` ?

Comment (martinjaeger) [reply subsys/lorawan/lorawan.c]: Don't know if there is an explicit rule. But I would use `IS_ENABLED` for small sections within a function (as it makes reading the code more smooth) and `#if defined` for larger sections of code (e.g. entire functions) that need to be selected depending on the config.

**Review by martinjaeger — DISMISSED** [review]

File: subsys/lorawan/lorawan.c [hunk 20]
```diff
@@ -7,12 +7,13 @@
...
 #include <errno.h>
 #include <lorawan/lorawan.h>
-#include <zephyr.h>
 
 #include "lw_priv.h"
 
 #include <LoRaMac.h>
 #include <Region.h>
+#include "nvm/lorawan_nvm.h"
+#include <settings/settings.h>
```
Comment (JordanYates) [inline subsys/lorawan/lorawan.c:16]: That this include is needed signals to me that the nvm backend isn't completely split out.

File: subsys/lorawan/Kconfig [hunk 21]
```diff
@@ -1,6 +1,7 @@
 # LoRaWAN configuration options
 
 # Copyright (c) 2020 Manivannan Sadhasivam <mani@kernel.org>
+# Copyright (c) 2022 Intellinium <giuliano.franchetto@intellinium.com>
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/Kconfig:4]: nit: you might need to drop this too.

**Review by Mani-Sadhasivam — DISMISSED** [review]
LGTM! Thanks for your continuous work on this PR.

**Review by Mani-Sadhasivam — DISMISSED** [review]

**Comment by Mani-Sadhasivam** [comment]
@carlescufi This PR is ready to merge now!

File: subsys/lorawan/lorawan.c [hunk 22]
```diff
@@ -605,9 +616,13 @@ static int lorawan_init(const struct device *dev)
 		return -EINVAL;
 	}
 
+	if (IS_ENABLED(CONFIG_LORAWAN_NVM_SETTINGS)) {
+		settings_subsys_init();
```
Comment (JordanYates) [inline subsys/lorawan/lorawan.c:620]: Can this be abstracted out to a `lorawan_nvm_init()` call.
That would let us remove all references to a particular NVM backend from the main lorawan files.
The `IS_ENABLED` would change to `if(!IS_ENABLED(CONFIG_LORAWAN_NVM_NONE))`

**Review by JordanYates — CHANGES_REQUESTED** [review]
I have some suggestions regarding making sure the NVM backends are properly split from the core files.

**Review by JordanYates — DISMISSED** [review]

**Review by martinjaeger — DISMISSED** [review]

File: subsys/lorawan/lorawan.c [hunk 23]
```diff
@@ -102,7 +102,7 @@ static void datarate_observe(bool force_notification)
 	LoRaMacMibGetRequestConfirm(&mibGet);
 
 	if ((mibGet.Param.ChannelsDatarate != current_datarate) ||
-	    (force_notification)) {
+		(force_notification)) {
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/lorawan.c:105]: May I know why you've changed this? The wrapped line was intentionally aligned with the opening bracket `(`

File: subsys/lorawan/lorawan.c [hunk 24]
```diff
@@ -152,7 +152,7 @@ static void McpsIndication(McpsIndication_t *mcpsIndication)
 	/* Iterate over all registered downlink callbacks */
 	SYS_SLIST_FOR_EACH_CONTAINER(&dl_callbacks, cb, node) {
 		if ((cb->port == LW_RECV_PORT_ANY) ||
-		    (cb->port == mcpsIndication->Port)) {
+			(cb->port == mcpsIndication->Port)) {
```
Comment (Mani-Sadhasivam) [inline subsys/lorawan/lorawan.c:155]: Here also.

**Review by Mani-Sadhasivam — CHANGES_REQUESTED** [review]

File: subsys/lorawan/lorawan.c (hunk 23 above)
Comment (GiulianoFranchetto) [reply subsys/lorawan/lorawan.c]: I think my IDE wanted to make it more fancy. I'll revert it

**Review by JordanYates — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Review by Mani-Sadhasivam — APPROVED** [review]

**Comment by Mani-Sadhasivam** [comment]
@carlescufi Please merge!
