### PR TITLE
drivers: timer: lptim timer clock on stm32u5 has a prescaler

### LINKED ISSUE #53012: stm32u5: timer api: lptim: k_msleep is twice long as expected
**Describe the bug**

Some timer_api tests are failed on b_u585i_iot02a
```
   zephyr/tests/kernel/tickless/tickless_concept/kernel.tickless.concept, b_u585i_iot02a
   zephyr/tests/kernel/timer/timer_api/kernel.timer.tickless, b_u585i_iot02a
```
Using `samples/boards/stm32/power_mgmt/blinky/src/main.c`, it can also be seen that `k_msleep(2000)` generates 4s sleep.
Though, `k_busy_wait` provides correct duration, so driver configuration and  `sys_clock_cycle_get_32()` implementation seem to be correct.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**
Using LPTIM as kernel ticker should provide correct sleep timeouts

**Environment (please complete the following information):**
zephyr-v3.2.0-2520-g33900ab99e

### PR DESCRIPTION
**Pull request by FRASTM**
The stm32U5 devices shows a x2 factor on the LPTIM1,3,4 clock source but it acts as a prescaler.
The max lptim counter (timebase) is counting 4 sec The LPTIM count unit is double.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/53012

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/timer/stm32_lptim_timer.c [hunk 1]
```diff
@@ -343,6 +343,22 @@ static int sys_clock_driver_init(const struct device *dev)
...
+	 * A full 16bit LPTIM counter is counting 4s at 2 * 1/32768 (with LSE)
+	 * Time base = (4s * freq) - 1
+	 */
+	if (lptim_clock_freq == KHZ(32)) {
+		lptim_time_base = 0xF9FF;
+	} else if (lptim_clock_freq == 32768) {
+		lptim_time_base = 0xFFFF;
+	} else {
+		return -EIO;
+	}
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/timer/stm32_lptim_timer.c]: That was also to change the comment above, but changing the order is also possible to avoid reading the same lines inside each section

**Comment by FRASTM** [comment]
Introducing a ` st,static-prescaler;`  optional property to adjust the lptim time base when a x2 factor is present at the LPTIM clock input, like on LPTIM1,3,4 of the stm32U5 devices

File: drivers/timer/stm32_lptim_timer.c [hunk 2]
```diff
@@ -348,16 +348,27 @@ static int sys_clock_driver_init(const struct device *dev)
...
 		return -EIO;
 	}
+#if DT_PROP(DT_DRV_INST(0), st_static_prescaler)
+	 /*
+	  * LPTIM of the stm32, like stm32U5, which has a clock source x2.
+	  * A full 16bit LPTIM counter is counting 4s at 2 * 1/32768 (with LSE)
+	  * Time base = (4s * freq) - 1
+	  */
+	lptim_clock_freq = lptim_clock_freq / 2;
+#else
```
Comment (erwango) [inline drivers/timer/stm32_lptim_timer.c:366]: let's take benefit of `IS_ENABLED` magic for readability:
    if (IS_ENEBLED(DT_PROP(DT_DRV_INST(0), st_static_prescaler))) {
           /*  bla */
           lptim_clock_freq = lptim_clock_freq / 2;
    }

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: drivers/timer/stm32_lptim_timer.c (hunk 2 above)
Comment (erwango) [reply drivers/timer/stm32_lptim_timer.c:366]: I'm sure comment could be reviewed to fit a good old if() implementation

**Comment by FRASTM** [comment]
version of the stm32_lptim_timer.c using `if (IS_ENABLED(DT_PROP(DT_DRV_INST(0), st_static_prescaler))) {`
instead of `#if DT_PROP(DT_DRV_INST(0), st_static_prescaler)`

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]
