### PR TITLE
ztress: Coherence fix for tests/lib/spsc_pbuf

### LINKED ISSUE #47300: Intel CAVS: Failure in tests/lib/spsc_pbuf
**Describe the bug**
On intel_adsp_cavs25 platform, tests/lib/spsc_pbuf/ failed. 

Please also mention any information which could help others to understand
the problem you're facing:
 - intel_adsp_cavs25
 - tests/lib/spsc_pbuf  No Console Output(Timeout)

**To Reproduce**

1. twister -W --hardware-map /home/ztest/cavs/cavs.map --device-testing -x=CONFIG_BOOT_DELAY=500 -T tests/lib/spsc_pbuf/ --no-skipped-report -vv
2. See error

**Logs and console output**
```
START - test_stress
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/kernel/sched.c:1764
aborted _current back from dead
E:  ** FATAL EXCEPTION
E:  ** CPU 0 EXCCAUSE 63 (zephyr exception)
E:  **  PC 0xbe0124ee VADDR (nil)
E:  **  PS 0x60b20
E:  **    (INTLEVEL:0 EXCM: 0 UM:1 RING:0 WOE:1 OWB:11 CALLINC:2)
E:  **  A0 0xbe0120b8  SP 0xbe01cf00  A2 0x4  A3 0x9e022b5c
E:  **  A4 0x1  A5 0x60b20  A6 0x1f  A7 0x1
E:  **  A8 0x1  A9 (nil) A10 0x1 A11 0x9e022a58
E:  ** A12 0x9e0224c8 A13 0x21 A14 0xbe01cef0 A15 0x4
E:  ** LBEG 0xbe013071 LEND 0xbe013087 LCOUNT (nil)
E:  ** SAR 0x4
Backtrace:0xBE0124EB:0xBE01CF00 0xBE0120B5:0xBE01CF10 0xBE016FF8:0xBE01CF30 0xBE011773:0xBE01CF70 
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x9e0224c8 (ztress_0)
E: Halting system
0% remaining:4000 ms
0% remaining:2999 ms
0% remaining:1999 ms
0% remaining:999 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
0% remaining:0 ms
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain - SDK 14.1
 - Commit SHA: fa055f743fd870809ed2a22dc41f6fb34a6eea46

### PR DESCRIPTION
**Pull request by smrtos**
When CONFIG_KERNEL_COHERENCE=y, it's illegal to place shared
data(like ztress_context_data in this test case) on the stack,
because that memory is incoherent with respect to other CPUs
in the system.

In this specific case, it will cause PC register to load invalid
handler function pointer and crash the Xtensa processor.

Make it static.

Signed-off-by: Ming Shao <ming.shao@intel.com>

Fix: https://github.com/zephyrproject-rtos/zephyr/issues/47300

### CODE REVIEW

File: subsys/testsuite/ztest/include/zephyr/ztress.h [hunk 1]
```diff
@@ -159,10 +159,14 @@ struct ztress_context_data {
 #define ZTRESS_EXECUTE(...) do {							\
 	Z_ZTRESS_TIMER_CONTEXT_VALIDATE(__VA_ARGS__);					\
 	int has_timer = Z_ZTRESS_HAS_TIMER(__VA_ARGS__);				\
-	struct ztress_context_data data[] = {						\
+	struct ztress_context_data data1[] = {						\
```
Comment (edersondisouza) [inline subsys/testsuite/ztest/include/zephyr/ztress.h:162]: I'm not sure I get why this indirection - why not make `data` static directly?

Comment (smrtos) [reply subsys/testsuite/ztest/include/zephyr/ztress.h]: Uh... it's indeed too ugly. I will just add the `static`. Please see my latest push.

**Review by nordic-krch — DISMISSED** [review]

**Review by teburd — APPROVED** [review]
Makes sense, good find

**Review by nordic-krch — APPROVED** [review]
