### PR TITLE
tests/kernel/context: Improve to resist parallel threads interrupting

### LINKED ISSUE #67477: tests/kernel/context fails in master for the nrf5340bsim_nrf5340_cpunet
**Describe the bug**

This test assumes that nothing will wake the CPU apart from the timer set by the test (https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/kernel/context/src/main.c#L239),
but the NRF sync RTC mechanism is doing its thing in the background, causing the CPU to awake which causes that test condition to be checked too soon and the test to fail

**To Reproduce**
1. twister -p nrf5340bsim_nrf5340_cpuapp -s tests/kernel/context/kernel.context.minimallibc
2. See error

**Expected behavior**
No error

**Impact**
Blocked PRs which trigger this test

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/7474773275/job/20378030950?pr=67432#step:13:977

**Environment (please complete the following information):**
 - OS: Linux CI (Ubuntu 20.04)
 - Toolchain (e.g Zephyr SDK, ...): Host gcc 11
 - Commit SHA or Version used: main as of now : 8356ec21e5c98ddf9b9e91203ff3962e992e73e6

**Additional context**
The test fails in this board since the sync rtc mechanism support was enabled in this board in
9dabc55c3e332b28ad01c7f7cf73782a95777621

### PR DESCRIPTION
**Pull request by aescolar**
This test assumes that nothing will wake the CPU apart from the timer set by the test.
But that is not necessarily the case.
Some other platform thread started at boot
may be waking the CPU every now and then.

Let's allow for some spurious wakes while we are testing k_cpu_idle, while at the same time ensuring we are not just busy waiting all the way.

Fixes #67477

### CODE REVIEW

File: tests/kernel/context/src/main.c [hunk 1]
```diff
@@ -224,20 +227,30 @@ static void _test_kernel_cpu_idle(int atomic)
 	unsigned int i, key;
 	uint32_t dur = k_ms_to_ticks_ceil32(10);
 	uint32_t slop = 1 + k_ms_to_ticks_ceil32(1);
+	int idle_loops;
+/* Something else may be running in the background waking the CPU, but we still want to
+ * check that k_cpu_idle() idles the CPU and we are not just busy waiting. We allow the loop
+ * to run up to 128 times in 10ms, which allows for plenty of other systems' interrupts
+ */
+#define MAX_IDLE_WAKES 128
```
Comment (andyross) [inline tests/kernel/context/src/main.c:235]: This threshold seems too high to me. If you handed me a device that was waking up spuriously every 40ms (5s/128) and asked me if its CPU idle implementation was working, I'd probably say "hell no". :)

Maybe limit this (i.e. set the max to zero by default) to specific platforms/configurations (just nRF with SYNC_RTC, right?) that are known to have internal idle wakeups, and tune the number as tight as we can?

Comment (aescolar) [reply tests/kernel/context/src/main.c:235]: Well.. it could be anything that happens to run at the same time as the test. And as the test runs very soon after boot, there may be quite a few platform components doing something.
128 just felt like safe enough to avoid false negatives (unless the platform is, say, printing thru the UART and interrupt per byte or something like that) while at the same time, still checking that we are not just busy waiting.
I can certainly lower it to, say, 16 or so, which should cover most platforms.
Does that sound good to you?

Comment (andyross) [reply tests/kernel/context/src/main.c]: Right, but that's a software robustness argument.  This is a test, and the assumption in the test is clearly that "nothing should wake us up".  It turns out there's an edge case where something might, so (if we don't want to fix the edge case) let's tune the detection to just that edge case.

Again, if this test is waking up on any platform except nRF+SYNC_RTC, that's a failure we want to know about.  "Too much fiddling" is a very minor sin when compared to "we lost test coverage". :)

**Review by andyross — DISMISSED** [review]
Looks great.  I would have personally done this with plain preprocessor code instead of the kconfig for simplicity reasons, but no reason to nitpick about totally reasonable design choices.

**Comment by aescolar** [comment]
@andyross the default was in the wrong order, so it was default to 0 always. Now it works as it should :)

**Review by andyross — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
