### PR TITLE
net: mqtt: websocket: Only accept data packets in RX

### LINKED ISSUE #24156: MQTT Websocket transport interprets all received data as MQTT messages
`mqtt_client_websocket_read()` does not filter the received websocket messages on their `message_type`. However, apart from text and binary frames, `websocket_recv_msg()` may also return control frames (Websocket messages with close and ping opcodes), which should not be passed to the MQTT client.

https://github.com/zephyrproject-rtos/zephyr/blob/7ede50b8e531dc79a353f48fd2c6240150f4a810/subsys/net/lib/mqtt/mqtt_transport_websocket.c#L140-L151

Below is a log showing a MQTT broker performing a client take-over by closing the Websocket (cleanly) right after successful connection setup because another client with the same client ID connected a few seconds afterwards. It shows how the Websocket control frame `0x88 0x02 0x03 0xE8` (i.e. close connection w/ close code 1000 (normal closure)) is passed to `mqtt_read_message_chunk()` resulting in a "Transport read error" message.

```
...                ...
[00:00:27.859,000] <dbg> net_mqtt.client_connect: (0x200002e8): Connect completed
[00:00:27.954,000] <dbg> net_sock.zsock_received_cb: (0x20008cf4): ctx=0x20008a00, pkt=0x200232d4, st=0, user_data=0x00000000
[00:00:28.000,000] <dbg> net_mqtt.mqtt_input: (0x200002e8): state:0x00000002
[00:00:28.030,000] <dbg> net_websocket.Header
82 04                   |..      
[00:00:28.061,000] <dbg> net_websocket.websocket_recv_msg: (0x200002e8): [0x20000000] masked 0 mask 0xa3db7e93 hdr 2 msg 4
[00:00:28.106,000] <dbg> net_websocket.Payload
20 02 00 00             | ...    
[00:00:28.136,000] <dbg> net_websocket.websocket_recv_msg: (0x200002e8): [0x20000000] Received total 4 bytes
[00:00:28.176,000] <dbg> net_mqtt_dec.unpack_uint8: (0x200002e8): >> cur:0x200046c8, end:0x200046cc
[00:00:28.211,000] <dbg> net_mqtt_dec.unpack_uint8: (0x200002e8): << val:20
[00:00:28.241,000] <dbg> net_mqtt_dec.packet_length_decode: (0x200002e8): length:0x00000002
[00:00:28.277,000] <dbg> net_mqtt_rx.mqtt_handle_packet: (0x200002e8): [CID 0x20004038]: Received MQTT_PKT_TYPE_CONNACK!
[00:00:28.322,000] <dbg> net_mqtt_dec.unpack_uint8: (0x200002e8): >> cur:0x200046ca, end:0x200046cc
[00:00:28.357,000] <dbg> net_mqtt_dec.unpack_uint8: (0x200002e8): << val:00
[00:00:28.387,000] <dbg> net_mqtt_dec.unpack_uint8: (0x200002e8): >> cur:0x200046cb, end:0x200046cc
[00:00:28.422,000] <dbg> net_mqtt_dec.unpack_uint8: (0x200002e8): << val:00
[00:00:28.452,000] <dbg> net_mqtt_dec.connect_ack_decode: (0x200002e8): [CID 0x20004038]: session_present_flag: 0
[00:00:28.493,000] <dbg> net_mqtt_rx.mqtt_handle_packet: (0x200002e8): [CID 0x20004038]: return_code: 0
[00:00:33.083,000] <dbg> net_sock.zsock_received_cb: (0x20008cf4): ctx=0x20008a00, pkt=0x200232d4, st=0, user_data=0x00000000
[00:00:33.129,000] <dbg> net_mqtt.mqtt_input: (0x200002e8): state:0x00000006
[00:00:33.159,000] <dbg> net_websocket.Header
88 02                   |..      
[00:00:33.190,000] <dbg> net_websocket.websocket_recv_msg: (0x200002e8): [0x20000000] masked 0 mask 0xa3db7e93 hdr 2 msg 2
[00:00:33.235,000] <dbg> net_websocket.Payload
03 e8                   |..      
[00:00:33.265,000] <dbg> net_websocket.websocket_recv_msg: (0x200002e8): [0x20000000] Received total 2 bytes
[00:00:33.305,000] <dbg> net_mqtt_dec.unpack_uint8: (0x200002e8): >> cur:0x200046c8, end:0x200046ca
[00:00:33.340,000] <dbg> net_mqtt_dec.unpack_uint8: (0x200002e8): << val:03
[00:00:33.370,000] <dbg> net_sock.zsock_recv_stream: (0x200002e8): NULL return from fifo
[00:00:33.406,000] <dbg> net_mqtt_rx.mqtt_read_message_chunk: (0x200002e8): [CID 0x20004038]: Transport read error: -11
```

In the end the client will disconnect due to this transport error (what happens to be correct for the Websocket close control frame, but not for Websocket ping/pong control frames) here:

https://github.com/zephyrproject-rtos/zephyr/blob/0c8d81c46f5bf06a407fc17e7cc12e74b32eafe1/subsys/net/lib/mqtt/mqtt.c#L125-L139

### PR DESCRIPTION
**Pull request by jukkar**
Check the message type and only accept MQTT binary data.

Fixes #24156

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

File: subsys/net/lib/mqtt/mqtt_transport_websocket.c [hunk 1]
```diff
@@ -141,13 +141,22 @@ int mqtt_client_websocket_read(struct mqtt_client *client, u8_t *data,
...
 	if (!shall_block) {
 		timeout = K_NO_WAIT;
 	}
 
-	return websocket_recv_msg(client->transport.websocket.sock,
-				  data, buflen, NULL, NULL, timeout);
+	ret = websocket_recv_msg(client->transport.websocket.sock,
+				 data, buflen, &message_type, NULL, timeout);
+	if (ret > 0) {
+		if (!(message_type & WEBSOCKET_FLAG_BINARY)) {
```
Comment (rlubos) [inline subsys/net/lib/mqtt/mqtt_transport_websocket.c:154]: Shouldn't `WEBSOCKET_FLAG_CLOSE` be handled separately? Otherwise, MQTT engine will not be aware that peer closed the connection. Socket based transport implementations simply return `0` in that case.

Comment (jukkar) [reply subsys/net/lib/mqtt/mqtt_transport_websocket.c:154]: Sure, that can be added here. I just wonder that if we receive CLOSE, then the underlying socket is probably closed anyway by the peer so the end result is probably the same. Anyway, I will send new version.

Comment (mrfuchs) [reply subsys/net/lib/mqtt/mqtt_transport_websocket.c:158]: [RFC 6455, chapter 7.1.2](https://tools.ietf.org/html/rfc6455#section-7.1.2):

> Once an endpoint has both sent and received a Close control frame, that endpoint SHOULD _Close the WebSocket Connection_ as defined in Section 7.1.1.

**Comment by mrfuchs** [comment]
@jukkar, I think the `message_type` variable should be initialized to 0 and checked for non-zero after calling `websocket_recv_msg()` since `message_type` may be untouched, see:

https://github.com/zephyrproject-rtos/zephyr/blob/748eb996465acdb00e65e068d26eb78444201140/subsys/net/lib/websocket/websocket.c#L687-L688

**Comment by jukkar** [comment]
> I think the `message_type` variable should be initialized to 0 and checked for non-zero after calling `websocket_recv_msg()` since `message_type` may be untouched, see:

Indeed, that is correct, will fix.

**Review by rlubos — APPROVED** [review]
LGTM
