### PR TITLE
drivers: watchdog: Add enableWait setting for wdt_mcux_imx_wdog

### LINKED ISSUE #86437: Unexpected Watchdog Reset on NXP RT1060-EVKB with Sleep Mode Enabled
**Describe the bug**

Hey, I tested the watchdog on the RT1060-EVKB with a timeout of 1000ms and enabled both flags: `WDT_OPT_PAUSE_HALTED_BY_DBG` and `WDT_OPT_PAUSE_IN_SLEEP`.

As shown in the code, immediately after calling `wdt_setup`, the CPU enters sleep mode for 2000ms. However, I noticed that the SoC unexpectedly resets, even though it shouldn't.

code snippet:
```
void main(void) {
    int err;
    int wdt_channel_id;
    const struct device *const wdt = DEVICE_DT_GET(DT_ALIAS(watchdog0));

    printk("Watchdog sample application\n");

    if (!device_is_ready(wdt)) {
        printk("%s: device not ready.\n", wdt->name);
        return;
    }

    struct wdt_timeout_cfg wdt_config = {
        /* Reset SoC when watchdog timer expires. */
        .flags = WDT_FLAG_RESET_SOC,

        /* Expire watchdog after max window */
        .window.min = 0U,
        .window.max = 1000U,
    };

    wdt_channel_id = wdt_install_timeout(wdt, &wdt_config);
    if (wdt_channel_id < 0) {
        printk("Watchdog install error\n");
        return;
    }

    err = wdt_setup(wdt, (WDT_OPT_PAUSE_HALTED_BY_DBG | WDT_OPT_PAUSE_IN_SLEEP));
    if (err < 0) {
        printk("Watchdog setup error\n");
        return;
    }

    for (int i = 0; i < 100; ++i) {
        printk("Feeding watchdog... %d \n", i);
        wdt_feed(wdt, 0);
        k_sleep(K_MSEC(2000));
    }

    return 0;
}
```

**To Reproduce**
Simply build and run the code for `mimxrt1060_evkb`.

**Expected behavior**
SoC shouldn't reset.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: Zephyr SDK
 - SHA: 30b94635397a241e08d423640ac0a682656f74c9

### PR DESCRIPTION
**Pull request by dleach02**
When WDT_OPT_PAUSE_IN_SLEEP option is passed in set enableWait flag in addition to the enableStop .

Fixes #86437

### CODE REVIEW

**Comment by dleach02** [comment]
@ofirshe can you confirm with your platform

**Comment by ofirshe** [comment]
Hi @dleach02, thank you for that fix.
Unfortunately, I don’t have access to either the RT1060EVK or EVKB boards in the lab to verify this, as we've moved to a custom board. Currently, the external supply that drives the POR when the watchdog is asserted is not yet set up.

If you or someone else at NXP has an available platform, you can reproduce the issue by copying the code snippet from the original [report](https://github.com/zephyrproject-rtos/zephyr/issues/86437) and verifying that the device does not reset when executing `k_sleep(K_MSEC(2000));`. I observed the problem on an RT1060 EVKB.

Thanks again!

**Comment by dleach02** [comment]
Yes, I was able to reproduce the issue based on your test code. I'll probably follow-up the PR with an extension to the test cases for watchdog to include this particular use case

**Comment by dleach02** [comment]
@hakehuang our platforms are not covered by the wdog tests. I created a test case based on the original submitter's details and reproduced his reported failure and was able to verify that the RT1060 now passes this.

**Comment by hakehuang** [comment]
> @hakehuang our platforms are not covered by the wdog tests. I created a test case based on the original submitter's details and reproduced his reported failure and was able to verify that the RT1060 now passes this.

@dleach02 Thanks for the notice, I enhance the watchdog test with this feature https://github.com/zephyrproject-rtos/zephyr/pull/91557

File: drivers/watchdog/wdt_mcux_imx_wdog.c [hunk 1]
```diff
@@ -41,14 +41,27 @@ static int mcux_wdog_setup(const struct device *dev, uint8_t options)
...
+	 * to keep system time accurate enough on timer rollovers. During
+	 * this time, the wdog will start ticking again so you can
+	 * possibly still have the wdog expire.
+	 *
+	 */
+	data->wdog_config.workMode.enableWait =
+		(options & WDT_OPT_PAUSE_IN_SLEEP) == 0U;
+
 	data->wdog_config.workMode.enableStop =
 		(options & WDT_OPT_PAUSE_IN_SLEEP) == 0U;
```
Comment (decsny) [inline drivers/watchdog/wdt_mcux_imx_wdog.c:57]: duplicate expression `(options & WDT_OPT_PAUSE_IN_SLEEP) == 0U` could be made a boolean variable

Comment (dleach02) [reply drivers/watchdog/wdt_mcux_imx_wdog.c:57]: It could but I find this construct clearer and direct

**Review by hakehuang — APPROVED** [review]
board regression test pass, and testcase enhanced in another pr

File: drivers/watchdog/wdt_mcux_imx_wdog.c (hunk 1 above)
Comment (ofirshe) [reply drivers/watchdog/wdt_mcux_imx_wdog.c:57]: Maybe this may satisfy you both :)
```
data->wdog_config.workMode.enableWait =
data->wdog_config.workMode.enableStop =
        (options & WDT_OPT_PAUSE_IN_SLEEP) == 0U;
```

Comment (decsny) [reply drivers/watchdog/wdt_mcux_imx_wdog.c:57]: The way he has it is fine

**Review by decsny — APPROVED** [review]

**Comment by ofirshe** [comment]
@dleach02 Maybe add the bug tag to indicate this is a fix rather than a feature, so that mergers are aware.

**Review by mmahadevan108 — APPROVED** [review]
