### PR TITLE
Bluetooth: Controller: Fix Extended Scanning and Periodic Synchronization assertions

### LINKED ISSUE #39438: Scanning for devices sending periodic advertisements stops working after a while, but keeps reporting none periodic.
**Describe the bug**
From what I can read it's ok to keep scanning enabled while using `bt_le_per_adv_sync_create` etc. By removing the `scan_disable()` in direction_finding_connectionless_rx sample scanning stops working after a while. The standard scan callback keeps reporting standard advertisements, but stops reporting devices sending periodic advertisments. I guess the extended scanning stops working, but normal continues. (never getting in [here ](https://github.com/zephyrproject-rtos/zephyr/blob/82d7d3c5c98296fde51f157e54583f535e4dee12/samples/bluetooth/direction_finding_connectionless_rx/src/main.c#L198) as `info->interval `is always 0.

**To Reproduce**
1. Use latest Zephyr direction_finding_connectionless_tx on one device
2. Use latest Zephyr direction_finding_connectionless_rx on another device and commit out call to `scan_disable()` in `main`. Also comment out the large print in `scan_recv` to avoid to much spam in the logs.
3. Power on the tag, wait for sync and IQ data, then reset the device.
4. Re-do step 3. a few times until the sending device will not be found anymore.

**Expected behavior**
Continuous scanning still reporting devices sending periodic advertisements until scan is stopped. Or that application get notfied somehow that scanning stopped.

**Impact**
Application ends up in an unknown state and quirky workarounds are necessary (I assume restarting scanning will work, but have not tried it. If that does not work then impact is larger.

**Logs and console output**
In the log I added a print in `scan_recv` to show that scanning is still running, but no device advertising periodic are found.
[log.txt](https://github.com/zephyrproject-rtos/zephyr/files/7345929/log.txt)

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK
 - Commit SHA or Version used: 429d6cf055766d63add2a000ba81c522d2e24f77

### LINKED ISSUE #40317: Crash in ull.c when stressing periodic advertising sync (scanner side)
**Describe the bug**
Having 10 periodic advertisers sending periodic advertisements at a "faster" rate triggers various asserts often:

```
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull.c:1195
```

**Edit:** I saw another crash using this app:
`ASSERTION FAIL [e] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:892
`

**To Reproduce**
1. Make sure to cherry-pick this commit (unless it's been merged) 06d7e47e58580b17e1d04ed94f0525209752cae8 ([pull](https://github.com/zephyrproject-rtos/zephyr/pull/40227)) otherwise the application will hang every now and then (you can still get the crash both with and without that, just easier with as it won't hang the test app)
2. Build the attached code (pretty much samples/bluetooth/direction_finding_connectionless_tx) and samples/bluetooth/direction_finding_connectionless_rx.
_Note that for some reason `CONFIG_BT_CTLR_DF_PER_SCAN_CTE_NUM_MAX=1` in prj.conf does not stick, so when you compile you will get bss overflow. You need to manually go in and change to =1 in the generated .config in the build folder and build again. Not sure if it's a bug or something weird in the prj.conf, maybe you can check if that's a bug._
3. Flash one device with rx code and 10+ with tx code (less may work, but will take longer).
4. Wait for the receiver code to crash.

**Expected behavior**
No crashes

**Impact**
Moderate, it is related with periodic advertising only.

**Logs and console output**
-

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Windows
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK
 - Commit SHA or Version used: a08e6e1d9ad22920b7a08a366b3d66eaef7440f1 (with [this pull](https://github.com/zephyrproject-rtos/zephyr/pull/40227) cherry-picked)

**Additional context**
Code to reproduce: 
[reproduce.zip](https://github.com/zephyrproject-rtos/zephyr/files/7529182/reproduce.zip)

### PR DESCRIPTION
**Pull request by cvinayak**
Fix reset of is_aux_sched flag when closing the primary and
auxiliary PDU reception. Without this fix when scan window
is closed there would be duplicate auxiliary release message
generated causing memory corruption.

Fix auxiliary context release on scan done, do not wait for
reference count to reduce when Periodic Sync events overlap.

Fix missing use of auxiliary context to generate done event
which caused leak in release of auxiliary context being not
release when reference count that should decrease to zero.

Fix missing auxiliary context release message on abort of
LLL scheduling scheduling used by scan context.

Fix race condition in setting up ISR callback and parameter
caused between ULL_HIGH and LLL context. As LLL IRQ is not
disabled the parameter and ISR callback would get out of
sync causing incorrect parameter supplied to callback and
hence leading to development assert in ull_scan_done().

Fixes #39438.
Fixes #40317.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/lll_scan.h [hunk 1]
```diff
@@ -86,3 +86,4 @@ int lll_scan_reset(void);
 void lll_scan_prepare(void *param);
 
 extern uint8_t ull_scan_lll_handle_get(struct lll_scan *lll);
+extern struct lll_scan *ull_scan_lll_is_valid_get(struct lll_scan *lll);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/lll_scan.h:89]:
```suggestion
extern struct lll_scan *ull_scan_lll_get_valid(struct lll_scan *lll);
```

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan.c [hunk 2]
```diff
@@ -1009,91 +1013,63 @@ static void isr_done_cleanup(void *param)
...
-#if defined(CONFIG_BT_CTLR_ADV_EXT)
-	struct event_done_extra *extra;
-
-	if (lll->is_aux_sched) {
-		struct node_rx_pdu *node_rx;
-
-		node_rx = ull_pdu_rx_alloc();
-		LL_ASSERT(node_rx);
+#if defined(CONFIG_BT_CTLR_SCAN_INDICATION)
+	struct node_rx_hdr *node_rx = ull_pdu_rx_alloc_peek(3);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan.c:1017]: Can you please add a comment on why we need 3 nodes here? That has been very useful the other times where you've commented on that :)

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c [hunk 3]
```diff
@@ -596,6 +597,27 @@ static int prepare_cb(struct lll_prepare_param *p)
 	return 0;
 }
 
+static int is_abort_cb(void *next, void *curr, lll_prepare_cb_t *resume_cb)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c:600]: `resume_cb` seems unused. Is that intentional?

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c [hunk 4]
```diff
@@ -455,6 +456,27 @@ static int prepare_cb_common(struct lll_prepare_param *p, uint8_t chan_idx)
 	return 0;
 }
 
+static int is_abort_cb(void *next, void *curr, lll_prepare_cb_t *resume_cb)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:459]: Ditto with unused `resume_cb`

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan.c]: Added comment.

File: subsys/bluetooth/controller/ll_sw/lll_scan.h (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/lll_scan.h:89]: It is common signature in zephyr atleast when returning boolean to use `something_is_valid()`, hence Controller uses `something_is_valid_get()` to return a context if valid within its memory pool.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c:600]: Added `ARG_UNUSED`

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c (hunk 4 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:459]: Added `ARG_UNUSED`

File: subsys/bluetooth/controller/ll_sw/lll_scan.h (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/lll_scan.h:89]: > It is common signature in zephyr atleast when returning boolean to use something_is_valid()

Indeed it is, but this is also one my main peeves with this name: using `is_valid` in a function that does not return a boolean. 

I'd like a 3rd input on this as well (ping @ppryga @kruithofa ), although I will not block this PR due to this :)

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c:600]: `resume_cb` is a return parameter, and an `ASSERT` or any assignment is unnecessary when `-EAGAIN` is not the return value.

File: subsys/bluetooth/controller/ll_sw/lll_scan.h (hunk 1 above)
Comment (ppryga) [reply subsys/bluetooth/controller/ll_sw/lll_scan.h:89]: I got used to the `is_valid_get` but I agree with @Thalley. If one reads the name first time, she may be confused: is this a bool value that is returned or if `is valid` then `get` reference.

Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/lll_scan.h:89]: IMO 'ull_scan_lll_get_valid' is a better name, since this function is not returning a boolean.
However that will break consistency with already existing functions that follow the scheme 'something_is_valid', in particulare we already have an 'ull_scan_is_valid_get'.

It is probably best to create an issue/enhancement proposing the name change, and then do the change for all functions in one go, so that we remain consistent.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/lll_scan.h:89]: Zephyr is a mix of `something_get()` and `get_something()`, hence will be a API breaker enhancement needing some real work to get consistency, else the naming preference will always come up again in reviews.

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/lll_scan.h:89]: > Zephyr is a mix of `something_get()` and `get_something()`, hence will be a API breaker enhancement needing some real work to get consistency, else the naming preference will always come up again in reviews.

From https://github.com/zephyrproject-rtos/zephyr/pull/30892 it seems that the majority points towards `get_something()` for `get`ters. 

I agree with @kruithofa that it's probably better to do the consisting naming refactor in another PR.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan_aux.c:600]: > `resume_cb` is a return parameter, 

Ah, I had misunderstood the argument then. OK to leave as is :)

**Review by Thalley — APPROVED** [review]
LGTM, but will request that we create an issue or PR to change the naming from `is_valid_get()` to `get_valid()`, but across the controller subsystem for consistency.

File: subsys/bluetooth/controller/ll_sw/lll_scan.h (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/lll_scan.h:89]: #30892 has not concluded. The last agreement being from @nashif  “noun-verb” word ordering is recommended, example `k_work_delayable_remaining_get()` given here: https://github.com/zephyrproject-rtos/zephyr/pull/30892/files#r556478744

And the approved API is upstream: https://github.com/zephyrproject-rtos/zephyr/blob/2f5976d674fff5dd437074a2a92ae890c674e594/include/kernel.h#L3318

`ull_scan_lll_is_valid_get`  is descriptive of the purpose, is to check for valid context and then return the context, not a boolean.
`ull_scan_lll_valid_get` or `ull_scan_lll_get_valid` could mean `valid` being the noun/subject.

**Comment by cvinayak** [comment]
> LGTM, but will request that we create an issue or PR to change the naming from `is_valid_get()` to `get_valid()`, but across the controller subsystem for consistency.

#30892 is sufficient, which is inspired by https://barrgroup.com/embedded-systems/books/embedded-c-coding-standard/procedure-rules/naming-conventions, upstreamed outcoming being the use of “noun-verb” word ordering in the PR: https://github.com/zephyrproject-rtos/zephyr/pull/29618/files#diff-d425c69d5282cb213b62e545f89a0aa44326d0187725db1d83c8209a9bb1585fR3182-R3183

**Review by carlescufi — APPROVED** [review]
