### PR TITLE
net: packet: Do not drop net_pkt immediately

### LINKED ISSUE #34865: CONFIG_NET_SOCKETS_PACKET interferes with other network traffic (gptp, IP)
**Describe the bug**
I want to send Ethernet packets (AF_PACKET, SOCK_DGRAM) from a BSD socket while also running gPTP on my system, but this has proven problematic.
In trying to debug this, I have simplified my code into an empty main file where only changing one line in prj.conf is enough to trigger the issue.
Here is the content of my prj.conf file (it is very similar to the prj.conf of the gptp sample):
```
CONFIG_NETWORKING=y
CONFIG_NET_LOG=y
CONFIG_LOG=y
CONFIG_NET_IPV6=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=n
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_STATISTICS=y
CONFIG_NET_STATISTICS_USER_API=y

CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_NET_PKT_RX_COUNT=32
CONFIG_NET_PKT_TX_COUNT=32
CONFIG_NET_BUF_RX_COUNT=32
CONFIG_NET_BUF_TX_COUNT=32
CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT=5
CONFIG_NET_IF_MCAST_IPV6_ADDR_COUNT=5
CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=1
CONFIG_NET_MAX_CONTEXTS=10

CONFIG_INIT_STACKS=y
CONFIG_PRINTK=y
CONFIG_NET_SHELL=y

# Ethernet is needed for gPTP
CONFIG_NET_L2_ETHERNET=y

CONFIG_NET_CONFIG_NEED_IPV6=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_SETTINGS=y

CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::1"
CONFIG_NET_CONFIG_PEER_IPV6_ADDR="2001:db8::2"
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"
CONFIG_NET_CONFIG_MY_IPV4_GW="169.254.202.192"

# gPTP settings
CONFIG_NET_GPTP=y
CONFIG_NET_GPTP_STATISTICS=y
CONFIG_NET_GPTP_GM_CAPABLE=y

#CONFIG_NET_GPTP_LOG_LEVEL_DBG=y
#CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
#CONFIG_NET_CONTEXT_LOG_LEVEL_DBG=y
#CONFIG_NET_CONN_LOG_LEVEL_DBG=y
#CONFIG_NET_IF_LOG_LEVEL_DBG=y
#CONFIG_NET_L2_ETHERNET_LOG_LEVEL_DBG=y

# How many traffic classes to enable
CONFIG_NET_TC_TX_COUNT=6
CONFIG_NET_TC_RX_COUNT=6

# Enable priority support in net_context
CONFIG_NET_CONTEXT_PRIORITY=y
```

With this setup, gPTP works as expected, and my system replies to pings.
Now if _both_ of these lines are included:
```
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_PACKET=y
```
then my system answers neither gPTP requests or pings.
This is problematic because these contain the functionality I need to set up a BSD socket in my code.
It seems like a callback in the sockets code receives all the ingoing packets, instead of the modules that need them, from what I have observed so far.

**To Reproduce**
I am using a FRDM K64F connected directly to my computer with an ethernet cable
The code was compiled and flashed to the board using West.
The network traffic between the board and my computer was then observed in Wireshark.
I am running the gptp host on my computer as described here:
https://docs.zephyrproject.org/2.5.0/samples/net/gptp/README.html#setting-up-linux-host

**Expected behavior**
I expect gptp traffic and ping requests to still be handled normally after I've set my necessary socket options.

**Impact**
Setting the necessary options to set up an ethernet packet socket diverts other incoming network traffic.
This makes me unable to set up a socket like this while also running gPTP on my system.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Toolchain Zephyr v. 2.5.99
 - Platform: NXP FRDM K64F

### PR DESCRIPTION
**Pull request by jukkar**
If there are no sockets in the system, then do not drop the
packet immediately as there can be other L2 network handlers
like gPTP in the system. This will also allow ICMP messages
to pass to local handler.

Fixes #34865

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

File: subsys/net/ip/packet_socket.c [hunk 1]
```diff
@@ -46,7 +48,13 @@ enum net_verdict net_packet_socket_input(struct net_pkt *pkt, uint8_t proto)
...
+	orig_family = net_pkt_family(pkt);
+
 	net_pkt_set_family(pkt, AF_PACKET);
 
-	return net_conn_input(pkt, NULL, proto, NULL);
+	(void)net_conn_input(pkt, NULL, proto, NULL);
+
+	net_pkt_set_family(pkt, orig_family);
+
+	return NET_CONTINUE;
```
Comment (mniestroj) [inline subsys/net/ip/packet_socket.c:59]: What if `net_conn_input()` returns `NET_OK`? Isn't `pkt` already "consumed" and dereferenced inside `net_conn_input()`?

Comment (jukkar) [reply subsys/net/ip/packet_socket.c:59]: Could be, I will investigate this. The packet socket is quite complex and convoluted, this needs to be re-written at some point. It is difficult to see how the system will behave just by looking the code, basically one needs to run a test to verify that it is working ok. I did some tests with echo-server and did not see immediate issues with this proposal, but can try again with more complex setup.

Comment (mniestroj) [reply subsys/net/ip/packet_socket.c:59]: In all other network stack places function returning NET_OK does consume the packet. So this place looks suspicious, as it doesn't respect that. At least we should make some assumption what **should** happen, so that if we run into another issue related to it, then at least we will know which part is misbehaving.

While testing is important, I don't think we should rely on that. We might solve one issue and introduce another one here. Also, it would be nice to cover the case that we are fixing now with tests, so that we don't reintroduce it when fixing something different.

Comment (jukkar) [reply subsys/net/ip/packet_socket.c:59]: I found one corner case when testing with echo-server/client and when packet sockets were enabled.

I did not change the code to check NET_OK as it does not seem to ever happen for packet socket.

**Comment by jukkar** [comment]
Did some testing and did not see any buffer leaks.

**Comment by galak** [comment]
@mniestroj can you take another look

**Review by mniestroj — APPROVED** [review]
As @jukkar said, it is hard to tell whether we will run into some corner cases looking at the code alone, so we will need an overhaul at some point. For now I am okay with that.
