### PR TITLE
Bluetooth: Controller: Fix missing ISO Receiver address capture

### LINKED ISSUE #90097: Bluetooth: iso_receive: asserts when iso_broadcast terminates BIG in /nordic/lll/lll_sync_iso.c
**Describe the bug**
This is related to the pair of sample apps bluetooth/iso_broadcast and bluetooth/iso_receive and an assert that now happens in the iso_receive app in the latest main (as of Sunday 18 May25). This was not the case around mid-March25.

I am using the nordic nrf52840 devkits (pca10056) for both sample apps.

The assert is logged as:
```
ASSERTION FAIL [hcto == (start_us + 1U)] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1393
```
The iso_broadcast sample app is designed so that every 60 seconds it terminates the BIG and recreates it.  
The iso_receive sample app is designed to cope with the BIG disappearing and resync so that the pair of apps can be used to test creation and termination.  

Either wait until 60s elapses or reset the board running iso_broadcast.
The fact that resetting (or power cycling) the iso_broadcast devkit results in the assert means that this is an issue related to broadcast reception.

**To Reproduce**
After loading the apps in the nrf52840 devkits and confirming normal operation from the serial output log, reset the board that is running iso_broadcast.

**Expected behavior**
When receiving a broadcast, iso_receive should gracefully terminate and then enter a state to re-sync with the same broadcast.

**Impact**
As my work is for a demo of a le broadcast proprietary enhancement, my workaround is to restart the devkit running the sink end and also to configure iso_broadcast to never terminate the BIG.

**Logs and console output**
```
Incoming data channel 0x20000158 flags 0xa seq_num 351 ts 4007677 len 0:  (counter value 0)
Incoming data channel 0x20000144 flags 0xa seq_num 352 ts 4017687 len 0:  (counter value 0)
Incoming data channel 0x20000158 flags 0xa seq_num 352 ts 4017687 len 0:  (counter value 0)
Incoming data channel 0x20000144 flags 0xa seq_num 353 ts 4027697 len 0:  (counter value 0)
Incoming data channel 0x20000158 flags 0xa seq_num 353 ts 4027697 len 0:  (counter value 0)
Incoming data channel 0x20000144 flags 0xa seq_num 354 ts 4037676 len 0:  (counter value 0)
Incoming data channel 0x20000158 flags 0xa seq_num 354 ts 4037676 len 0:  (counter value 0)
Incoming data channel 0x20000158 flags 0xa seq_num 348 ts 3977679 len 0:  (counter value 0)
ASSERTION FAIL [hcto == (start_us + 1U)] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1393
[00:00:04.301,300] <err> os: r0/a1:  0x00000003  r1/a2:  0x00000000  r2/a3:  0x0000000d
[00:00:04.301,300] <err> os: r3/a4:  0x00000003 r12/ip:  0x00000014 r14/lr:  0x000031f3
[00:00:04.301,330] <err> os:  xpsr:  0x21000011
[00:00:04.301,361] <err> os: Faulting instruction address (r15/pc): 0x00003200
[00:00:04.301,391] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
[00:00:04.301,391] <err> os: Fault during interrupt handling

[00:00:04.301,422] <err> os: Current thread: 0x200006b8 (unknown)
[00:00:04.440,002] <err> os: Halting system

```

**Environment (please complete the following information):**

 - Commit SHA or Version used   [https://github.com/zephyrproject-rtos/zephyr/commit/b5934e8dfe5c8dd4c1a9f2221341aa46e3dce72a](url)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by cvinayak**
Fix missing ISO Receiver access address capture that caused ISO PDU reception error. Missing access address capture for subsequent subevent when prior subevent did not have an anchor point sync prevent proper drift compensation hence causing ISO PDU reception error for the entire BIG event.

Fix the jitter considered in the PDU reception in the subevents of ISO Sync Receiver to not exceed such that the reception is scheduled late (causing assertion).

Fixes #90097.

Overnight testing between `bap_broadcast_source` on nrf52833dk and `bap_broadcast_sink` on nrf54l15dk:
```
[2025-09-03 06:09:34.562] [00:02:52.835,401] <inf> stream_rx: [2593000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 37095 and ts 172835214: Valid 2593000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:09:34.579] [00:02:52.835,459] <inf> stream_rx: [2593000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 37095 and ts 172835214: Valid 2593000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:09:44.562] [00:03:02.835,921] <inf> stream_rx: [2594000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 38095 and ts 182835728: Valid 2594000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:09:44.579] [00:03:02.835,981] <inf> stream_rx: [2594000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 38095 and ts 182835728: Valid 2594000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:09:54.562] [00:03:12.836,436] <inf> stream_rx: [2595000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 39095 and ts 192836243: Valid 2595000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:09:54.579] [00:03:12.836,494] <inf> stream_rx: [2595000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 39095 and ts 192836243: Valid 2595000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:04.562] [00:03:22.836,945] <inf> stream_rx: [2596000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 40095 and ts 202836757: Valid 2596000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:04.579] [00:03:22.837,003] <inf> stream_rx: [2596000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 40095 and ts 202836757: Valid 2596000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:14.562] [00:03:32.837,465] <inf> stream_rx: [2597000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 41095 and ts 212837272: Valid 2597000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:14.579] [00:03:32.837,524] <inf> stream_rx: [2597000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 41095 and ts 212837272: Valid 2597000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:24.562] [00:03:42.837,979] <inf> stream_rx: [2598000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 42095 and ts 222837786: Valid 2598000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:24.580] [00:03:42.838,037] <inf> stream_rx: [2598000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 42095 and ts 222837786: Valid 2598000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:34.562] [00:03:52.838,488] <inf> stream_rx: [2599000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 43095 and ts 232838301: Valid 2599000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:34.579] [00:03:52.838,546] <inf> stream_rx: [2599000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 43095 and ts 232838301: Valid 2599000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:44.562] [00:04:02.839,008] <inf> stream_rx: [2600000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 44095 and ts 242838816: Valid 2600000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:44.580] [00:04:02.839,067] <inf> stream_rx: [2600000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 44095 and ts 242838816: Valid 2600000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:54.562] [00:04:12.839,523] <inf> stream_rx: [2601000]: Incoming audio on stream 0x2000246c len 40, flags 0x09, seq_num 45095 and ts 252839329: Valid 2601000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
[2025-09-03 06:10:54.580] [00:04:12.839,583] <inf> stream_rx: [2601000]: Incoming audio on stream 0x200024b8 len 40, flags 0x09, seq_num 45095 and ts 252839329: Valid 2601000 | Error 0 | Loss 0 | Dup TS 0 | Dup PSN 0
```

### CODE REVIEW

**Review by Thalley — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c [hunk 1]
```diff
@@ -1344,16 +1351,30 @@ static void isr_rx(void *param)
...
+			jitter_max_us = 0U;
+		}
+
 		jitter_us = (EVENT_CLOCK_JITTER_US << 1) * nse;
 		if (jitter_us > jitter_max_us) {
 			jitter_us = jitter_max_us;
 		}
+
+		LL_ASSERT(hcto > jitter_us);
+
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1377]: Funny; was about to suggest this in my last review, but noticed that it wasn't there before either, so I didn't :) Glad to see it added

**Review by Thalley — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1377]: Well, I noticed that a newly added assert was caught in CI for high number of subevents which I had to convert to if-then-else; hence, decided to add a assert here as well.

Do not hesitate to leave a comment, your reviews help think differently, and hence better solutions.

That said, I do not like the calculations here for the jitter, it is always calculating for `nse` i.e. from the first subevent; ideally, current jitter should be from the last sync-ed subevent.

The problem to solve, active clock is permitted a +/-2 us jitter which means over the duration of the subevents, a subevent can jitter by +/- 2 us multiplied by current subevent count `nse` when none of the previous subevent where received (anchor point sync).

I will comeback and solve it some other day, for now, bsim is happy; my other changes does expose too little jitter or drift causing assertion... fix for that another day.

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1377]: Consider creating a GH issue for the above so you don't forget it ;)

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1377]: Not going to forget it, listed (updated with the above problem statement now) in https://github.com/zephyrproject-rtos/zephyr/issues/82399

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c [hunk 2]
```diff
@@ -1344,16 +1351,30 @@ static void isr_rx(void *param)
 		hcto -= radio_rx_chain_delay_get(lll->phy, PHY_FLAGS_S8);
 		hcto -= addr_us_get(lll->phy);
 		hcto -= radio_rx_ready_delay_get(lll->phy, PHY_FLAGS_S8);
+
 		overhead_us = radio_rx_chain_delay_get(lll->phy, PHY_FLAGS_S8);
 		overhead_us += addr_us_get(lll->phy);
 		overhead_us += radio_rx_ready_delay_get(lll->phy, PHY_FLAGS_S8);
 		overhead_us += (EVENT_CLOCK_JITTER_US << 1);
+
+		LL_ASSERT(EVENT_IFS_US > overhead_us);
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1360]: Do not want a message.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c [hunk 3]
```diff
@@ -1344,16 +1351,30 @@ static void isr_rx(void *param)
...
+
 		jitter_max_us = (EVENT_IFS_US - overhead_us) >> 1;
-		jitter_max_us -= RANGE_DELAY_US + HAL_RADIO_TMR_START_DELAY_US;
+		jitter_max_us = (jitter_max_us * nse) / (lll->num_bis * lll->nse);
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1363]: No, nse and lll->nse are different values.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c [hunk 4]
```diff
@@ -1344,16 +1351,30 @@ static void isr_rx(void *param)
...
+		} else {
+			jitter_max_us = 0U;
+		}
+
 		jitter_us = (EVENT_CLOCK_JITTER_US << 1) * nse;
 		if (jitter_us > jitter_max_us) {
 			jitter_us = jitter_max_us;
 		}
+
+		LL_ASSERT(hcto > jitter_us);
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:1376]: Do not want a message.

**Review by carlescufi — APPROVED** [review]
