### PR TITLE
drivers: clock_control: stm32h7: do not enable systick in clock control initialization

### LINKED ISSUE #41691: Tickless Kernel on STM32H7 fails with Exception
**Describe the bug**
Running a tickless kernel on a STM32H7 produces the following error:

    *** BootingE: ***** Reserved Exception ( -1) *****
    E: r0/a1:  0x0800e9c8  r1/a2:  0x10000000  r2/a3:  0x00600010
    E: r3/a4:  0x240031ac r12/ip:  0x00000000 r14/lr:  0x08004e83
    E:  xpsr:  0x01000000
    E: Faulting instruction address (r15/pc): 0x0800deb6
    E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
    E: Current thread: 0x24000568 (main)
    E: Halting system

**To Reproduce**
1. mkdir -p build
2. CONF_FILE=prj_tickless.conf west build -b stm32h735g_disco -s zephyr/tests/kernel/timer/timer_api -d build/timer_api
3. west flash -d build/timer_api
4. Enjoy the error!

**Expected behavior**
This output should be produced:

    Running test suite timer_api
    ===================================================================
    START - test_time_conversions
     PASS - test_time_conversions in 0.5 seconds
    ===================================================================
    START - test_timer_duration_period
     PASS - test_timer_duration_period in 0.326 seconds
    ===================================================================
    START - test_timer_restart
     PASS - test_timer_restart in 0.276 seconds
    ===================================================================
    START - test_timer_period_0
     PASS - test_timer_period_0 in 0.202 seconds
    ===================================================================
    START - test_timer_period_k_forever
     PASS - test_timer_period_k_forever in 0.202 seconds
    ===================================================================
    START - test_timer_expirefn_null
     PASS - test_timer_expirefn_null in 0.326 seconds
    ===================================================================
    START - test_timer_periodicity
     PASS - test_timer_periodicity in 0.251 seconds
    ===================================================================
    START - test_timer_status_get
     PASS - test_timer_status_get in 0.1 seconds
    ===================================================================
    START - test_timer_status_get_anytime
     PASS - test_timer_status_get_anytime in 0.326 seconds
    ===================================================================
    START - test_timer_status_sync
     PASS - test_timer_status_sync in 0.351 seconds
    ===================================================================
    START - test_timer_k_define
     PASS - test_timer_k_define in 0.701 seconds
    ===================================================================
    START - test_timer_user_data
     PASS - test_timer_user_data in 0.301 seconds
    ===================================================================
    START - test_timer_remaining
     PASS - test_timer_remaining in 0.51 seconds
    ===================================================================
    START - test_timeout_abs
     PASS - test_timeout_abs in 0.1 seconds
    ===================================================================
    START - test_sleep_abs
     PASS - test_sleep_abs in 0.6 seconds
    ===================================================================
    Test suite timer_api succeeded
    ===================================================================
    PROJECT EXECUTION SUCCESSFUL

**Impact**
It is not possible to use a tickless kernel, e.g. for power management, on a STM32H7.

**Environment (please complete the following information):**
 - Board: STM32H735G Discovery Kit
 - Zephyr Version e4481f82cb02afced321adc845f771e82a541e6e

**Additional context**
I stumbled upon this while investigating #41408. The error is actually not a real exception, there is just no interrupt handler for Systick installed in a tickless kernel, but the clock control still enables Systick.

### PR DESCRIPTION
**Pull request by benediktibk**
Do not enable systick in the clock control initialization.

Fixes #41691

### CODE REVIEW

**Comment by benediktibk** [comment]
Fixes #41691

File: drivers/clock_control/clock_stm32_ll_h7.c [hunk 1]
```diff
@@ -755,8 +755,11 @@ static int stm32_clock_control_init(const struct device *dev)
 	}
 #endif /* STM32_PLL3_ENABLE */
 
-	/* Set systick to 1ms */
-	SysTick_Config(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC / 1000);
+	if (!IS_ENABLED(TICKLESS_KERNEL)) {
```
Comment (benediktibk) [inline drivers/clock_control/clock_stm32_ll_h7.c:758]: I am actually uncertain which config parameter I should check here best. Maybe CORTEX_M_SYSTICK?

Comment (erwango) [reply drivers/clock_control/clock_stm32_ll_h7.c:758]: I'm a bit puzzled here. Not sure why this problem is H7 only.
I need first to understand why this code is H7 only...

Comment (erwango) [reply drivers/clock_control/clock_stm32_ll_h7.c:758]: Likely this should be completely removed. This is already done by `sys_clock_driver_init` in cortex_m_systick driver.
This would require some tests to confirm it though.

Comment (erwango) [reply drivers/clock_control/clock_stm32_ll_h7.c:758]: @benediktibk I had some tests, and I think you can safely, fully, remove this line.

Comment (benediktibk) [reply drivers/clock_control/clock_stm32_ll_h7.c]: I already played around a bit without this line on a H7, and also had no problems. It is removed.

**Comment by erwango** [comment]
Please rebase to fix CI issue (fixed by https://github.com/zephyrproject-rtos/zephyr/pull/41725)

**Review by erwango — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
@benediktibk I'm fine with the change, but you need to update commit title and message (+ PR title and description)

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
