### PR TITLE
kernel/queue: fix queue append/get race

### LINKED ISSUE #29257: Race condition in k_queue_append and k_queue_alloc_append
**Describe the bug**
Using either of the above mentioned functions from a preemptive context, can lead to the element being appended to the queue to be lost.
The element loss happens when the `k_queue_append` is interrupted at a critical point, when the list only contains one element and `k_queue_get` is called, before the `k_queue_append` is allowed to complete. See below for a more detailed description.

**To Reproduce**
The loss of the element being placed on the queue happens in the following case:
- Three or more threads, Two or more producers which calls `k_queue_append` and of which at least one is preemptive, one consumer which waits on `k_queue_get`.
1. A producer thread calls `k_queue_append`. The queue now holds one element.
2. Another producer calls `k_queue_append`, but given the following `k_queue_append` implementation
`void k_queue_append(struct k_queue *queue, void *data)`
`{`
`	(void)queue_insert(queue, sys_sflist_peek_tail(&queue->data_q),`
`			   data, false);`
`}`
This thread is now interrupted right after `sys_sflist_peek_tail(&queue->data_q)` and thus before `queue_insert` which is also before the spin lock.
3. The consumer thread is now scheduled in, and it grabs the only element from the queue, does whatever it needs to do and possible places the element on a free list.
4. The producer from 2. is now scheduled back in and it now calls `queue_insert`, but as it peeked the tail before the consumer thread ran, it will now append the element to the tail element which is no longer on the queue but is actually on a free list, and as such the element is essentially lost.

The above scenario has been observed through `k_fifo_put` used from `bt_att_send`.

- The `k_spin_lock` in `queue_insert`, must be taken before calling `sys_sflist_peek_tail` in both `k_queue_append` and `k_queue_alloc_append`.

**Expected behavior**
The element should be placed on the list and be available on a call to k_queue_get.

**Impact**
The potential loss of a queue element is severe.

### PR DESCRIPTION
**Pull request by megatherium-95**
k_queue_append and k_queue_alloc_append are in a race
    condition.

    Scenario:
    Using either of the above mentioned functions from a
    preemptive context, can lead to the element being
    appended to the queue to be lost. The element loss happens
    when the k_queue_append is interrupted at a critical point,
    when the list only contains one element and k_queue_get is
    called, before the k_queue_append is allowed to complete.

    Fix:
    move locking out of the queue_insert API. Every function
    calling queue_insert has to lock and unlock the queue before
    making the call.

Fixes #29257

Signed-off-by: iva kik <megatheriumiva@gmail.com>

### CODE REVIEW

File: kernel/queue.c [hunk 1]
```diff
@@ -135,17 +135,22 @@ static inline void z_vrfy_k_queue_cancel_wait(struct k_queue *queue)
 #include <syscalls/k_queue_cancel_wait_mrsh.c>
 #endif
 
+/* Insert data into queue.
+ * API is not thread safe, lock the queue before using this API
```
Comment (andrewboie) [inline kernel/queue.c:139]: too much verbiage here. just say that `queue->lock` should be held by callers.

**Review by tyrantlizard77 — COMMENTED** [review]
If I understand this race condition properly, the real issue is that `k_queue_append` and `k_queue_alloc_append` are examining the queue outside of the lock with their calls to `sys_sflist_peek_tail(&queue->data_q)`. Could we adjust `queue_insert()` such that the peek_tail operation is done inside of it? Instead of moving all the locking outside and unconditionally rescheduling. Would make this change a bit simpler.

**Review by daor-oti — CHANGES_REQUESTED** [review]
@megatherium-95 Thank you for fixing this, I was just about to start fixing it and creating a PR...

Please update the commit message Fix section, with the spin lock remaining within queue_insert and the added parameter for queue tail peek.

**Review by daor-oti — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Review by daor-oti — COMMENTED** [review]
@andrewboie Can this be merged?

**Review by nashif — APPROVED** [review]

File: kernel/queue.c [hunk 2]
```diff
@@ -136,11 +136,14 @@ static inline void z_vrfy_k_queue_cancel_wait(struct k_queue *queue)
...
 
 static int32_t queue_insert(struct k_queue *queue, void *prev, void *data,
-			  bool alloc)
+			    bool alloc, bool is_append)
 {
-	k_spinlock_key_t key = k_spin_lock(&queue->lock);
 	struct k_thread *first_pending_thread;
+	k_spinlock_key_t key = k_spin_lock(&queue->lock);
 
+	if (is_append) {
```
Comment (andyross) [inline kernel/queue.c:144]: Might be simpler to use a NULL prev to signal this condition instead?  Not a big deal, but there are a lot of boilerplate changes here to add the extra argument, and the function already had five arguments.

Alternatively: split the function up into a must-be-locked core and a wrapper to manage the locking, then add a new "queue_append()" wrapper that selects an appropriate prev?

**Review by andyross — APPROVED** [review]
Some style whining, but looks good to me.

File: kernel/queue.c (hunk 2 above)
Comment (daor-oti) [reply kernel/queue.c:144]: I had the same thought, about using NULL prev to signal the append condition, but that will not work as the k_queue_prepend also sets prev to NULL thus the prepend would become append.

I do not really see the benefit of splitting the function, since the tail peek together with the is_append flag makes it simple, easy to understand and maintain, and also efficient as there is no need for extra function calls... But that is just my opinion.
