### PR TITLE
security: stack protection: Add more granularity for stack protection

### LINKED ISSUE #80559: Add Support for different stack protector options
Currently, the Zephyr project only supports the `-fstack-protector-all` option for stack protection. To better tune memory footprint and security requirements, it is necessary to add support for other stack protector options such as,
- `-fstack-protector, `
- `-fstack-protector-strong`, and 
- `-fstack-protector-explicit`.

**Rationale:**

- **Memory Footprint:** Different stack protector options provide varying levels of protection, which can help optimize the memory usage for different applications. For instance, `-fstack-protector-all` adds stack protection to all functions regardless of their vulnerability, that increases memory footprint significantly, while `-fstack-protector`/ `-fstack-protector-strong` provides a more balanced approach by protecting functions with certain characteristics.
- **Security Requirements:** Allowing more granular control over stack protection can help meet diverse security needs. For example, `-fstack-protector-explicit` allows developers to manually specify which functions should be protected, offering a tailored security approach.

**Proposed Changes:**

- **Build System Modifications:**
  - Update the CMake build scripts to accept new stack protector options.
  - Introduce configuration options in Kconfig to select the desired stack protector level.
  - Ensure compatibility with different compiler versions and platforms supported by Zephyr.
- **Codebase Adjustments:**
   - Modify the compiler flags in the build system to include the selected stack protector option.
   - Implement conditional compilation to apply the appropriate stack protector based on the configuration.
- **Documentation Updates:**
   - Update the Zephyr documentation to include detailed descriptions of each stack protector option.
   - Provide guidelines on how to select the appropriate stack protector based on application requirements.
   - Include examples demonstrating the impact of different stack protector options on memory usage and security.
- **Testing and Validation:**
   - Develop unit tests to verify the correct application of each stack protector option.
   - Perform regression testing to ensure that the new options do not introduce any issues.
   - Conduct performance benchmarking to evaluate the impact of different stack protector options on memory footprint and execution time.

### PR DESCRIPTION
**Pull request by ceolin**
Add more options for stack canaries.

Fixes: #80559

### CODE REVIEW

File: tests/kernel/mem_protect/stackprot/src/main.c [hunk 1]
```diff
@@ -70,6 +70,22 @@ void __attribute__((noinline)) check_input(const char *name, const char *input)
...
 
+/**
+ *
+ * check_input_fail
+ *
+ * This function is similar to check_input() but does not use an array
+ * so, unless it is built with stack protection for all functions it should fail
+ * with an error different from K_ERR_STACK_CHK_FAIL.
+ */
+void __attribute__((noinline)) check_input_fail(const char *name, const char *input)
```
Comment (rruuaanng) [inline tests/kernel/mem_protect/stackprot/src/main.c:81]: If I remember correctly, there seems to be an `__noinline`.

File: tests/kernel/mem_protect/stackprot/src/main.c [hunk 2]
```diff
@@ -85,15 +101,23 @@ void alternate_thread(void *p1, void *p2, void *p3)
...
+				"Input string is too long and stack overflowed!\n");
+	}
 	/*
 	 * Expect this thread to terminate due to stack check fail and will not
 	 * execute pass here.
 	 */
 	print_loop(__func__);
 
-	ret = TC_FAIL;
+	if (!should_fail) {
```
Comment (rruuaanng) [inline tests/kernel/mem_protect/stackprot/src/main.c:118]:
```suggestion
	if (should_fail == 0) {
```
(Forgive me for being mobile and can't see more context.)

Comment (ceolin) [reply tests/kernel/mem_protect/stackprot/src/main.c:118]: I am curious about this suggestion. `should_fail` is a boolean type, so AFAIK `!should_fail` is a valid construction according with our and MISRA-C code guidelines. In other hand, comparing boolean with integer is probably violating MISRA-C.

File: tests/kernel/mem_protect/stackprot/src/main.c (hunk 1 above)
Comment (ceolin) [reply tests/kernel/mem_protect/stackprot/src/main.c:81]: Just followed what was already done in this test. I can add a commit changing the other function too.

File: tests/kernel/mem_protect/stackprot/src/main.c (hunk 2 above)
Comment (rruuaanng) [reply tests/kernel/mem_protect/stackprot/src/main.c:116]: Oh, you can ignore my suggestion. I mistakenly thought it was int :)

File: tests/kernel/mem_protect/stackprot/src/main.c (hunk 1 above)
Comment (ceolin) [reply tests/kernel/mem_protect/stackprot/src/main.c:81]: We don't have it well defined. Just added here https://github.com/zephyrproject-rtos/zephyr/pull/82184

**Review by nordicjm — DISMISSED** [review]

**Comment by ruuddw** [comment]
As described in the issue, there may be 4 levels of protection (```
-fstack-protector, -fstack-protector-strong, -fstack-protector-all and
-fstack-protector-explicit
```). The PR excludes the lowest level (`-fstack-protector`), any reason? Isn't it confusing to take over the post-fix names but change the no-postfix version to '-all'?

**Comment by ruuddw** [comment]
Thanks for including the ARC Metaware compiler flags. FYI, that follows the LLVM/Clang approach - no `-explicit`. Note that the reverse `(__attribute__((no_stack_protector))` is supported, which ensures no canary is inserted even if the heuristics would have decided to add one.

**Review by cfriedt — COMMENTED** [review]
Looks good to me - I think I just spotted a small typo

File: kernel/Kconfig [hunk 3]
```diff
@@ -862,25 +862,47 @@ config XIP
 
 menu "Security Options"
 
-config STACK_CANARIES
-	bool "Compiler stack canaries"
-	depends on ENTROPY_GENERATOR || TEST_RANDOM_GENERATOR
-	select NEED_LIBC_MEM_PARTITION if !STACK_CANARIES_TLS
+config NEED_STACK_CANARIES
```
Comment (tejlmand) [inline kernel/Kconfig:865]: can we use `REQUIRES_STACK_CANARIES` to stay aligned with other Zephyr toolchain / build system settings, like
`REQUIRES_STD_C99`, `REQUIRES_FULL_LIBC`, etc.

File: kernel/Kconfig [hunk 4]
```diff
@@ -862,25 +862,47 @@ config XIP
...
+	bool
 	help
-	  This option enables compiler stack canaries.
+	  Hidden option to signal that software stack protection is enabled.
```
Comment (tejlmand) [inline kernel/Kconfig:868]:
```suggestion
	  Hidden option to signal that software stack protection is required.
```

File: kernel/Kconfig [hunk 5]
```diff
@@ -862,25 +862,47 @@ config XIP
...
-	  in footprint and an associated decrease in performance.
+	  Enabling this option, depending on the level chosen, can result in a
+	  significant increase in footprint and a corresponding decrease in performance.
 
 	  If stack canaries are not supported by the compiler an error
 	  will occur at build time.
 
-if STACK_CANARIES
+config STACK_CANARIES
+	bool "Compiler stack canaries for all functions"
```
Comment (tejlmand) [inline kernel/Kconfig:886]: perhaps shorten the names as those are choice entries:
Current:
image

Proposal:
image

```suggestion
	bool "All functions"
```
Only a proposal, thus non-blocking .

File: kernel/Kconfig [hunk 6]
```diff
@@ -862,25 +862,47 @@ config XIP
...
+	depends on ENTROPY_GENERATOR || TEST_RANDOM_GENERATOR
+	select NEED_LIBC_MEM_PARTITION if !STACK_CANARIES_TLS
+	select NEED_STACK_CANARIES
+	help
+	  This option enables compiler stack canaries for all functions.
+
+config STACK_CANARIES_STRONG
+	bool "Compiler stack canaries in most functions"
```
Comment (tejlmand) [inline kernel/Kconfig:894]: related to other Kconfig choice entry prompt proposal:

```suggestion
	bool "Most functions"
```
Only a proposal, thus non-blocking .

File: kernel/Kconfig [hunk 7]
```diff
@@ -900,6 +900,15 @@ config STACK_CANARIES_STRONG
 	  functions that have local array definitiion or have references to local
 	  frame addresses.
 
+config STACK_CANARIES_EXPLICIT
+	bool "Compiler stack canaries in explicit functions"
```
Comment (tejlmand) [inline kernel/Kconfig:904]: related to other Kconfig choice entry prompt proposal:

```suggestion
	bool "Explicit functions"
```
Only a proposal, thus non-blocking .

**Review by tejlmand — CHANGES_REQUESTED** [review]
Looks good.

Some minor suggestions, the main one being the proposal to use `REQUIRES` instead of `NEED`.

File: kernel/Kconfig (hunk 5 above)
Comment (ceolin) [reply kernel/Kconfig]: Applied suggestions, much better indeed.

File: kernel/Kconfig (hunk 3 above)
Comment (ceolin) [reply kernel/Kconfig]: Done :)

File: kernel/Kconfig (hunk 4 above)
Comment (ceolin) [reply kernel/Kconfig]: done

File: tests/kernel/mem_protect/stackprot/src/main.c [hunk 8]
```diff
@@ -86,15 +102,21 @@ void alternate_thread(void *p1, void *p2, void *p3)
 	ARG_UNUSED(p3);
 
 	TC_PRINT("Starts %s\n", __func__);
-	check_input(__func__,
-		    "Input string is too long and stack overflowed!\n");
+
+	if (should_fail) {
+		check_input_fail(__func__, "Input string is too long 2222 and stack overflowed!\n");
```
[the remark this answers is not in the document]
Comment (ceolin) [reply tests/kernel/mem_protect/stackprot/src/main.c]: fixed, thanks for spotting it.

**Review by tejlmand — DISMISSED** [review]

**Review by peter-mitsis — DISMISSED** [review]

**Review by cfriedt — DISMISSED** [review]

**Comment by vujjuri** [comment]
> As described in the issue, there may be 4 levels of protection (`-fstack-protector, -fstack-protector-strong, -fstack-protector-all and -fstack-protector-explicit`). The PR excludes the lowest level (`-fstack-protector`), any reason? Isn't it confusing to take over the post-fix names but change the no-postfix version to '-all'?

I agree here. All the 4 levels are different. User should have provision to choose among 4 options

File: cmake/compiler/arcmwdt/compiler_flags.cmake [hunk 9]
```diff
@@ -168,6 +168,8 @@ set_compiler_property(PROPERTY imacros -imacros)
 # Security canaries.
 #no support of -mstack-protector-guard=global"
 set_compiler_property(PROPERTY security_canaries -fstack-protector-all)
+set_compiler_property(PROPERTY security_canaries_strong -fstack-protector-strong)
+set_compiler_property(PROPERTY security_canaries_explicit -fstack-protector-explicit)
```
Comment (vujjuri) [inline cmake/compiler/arcmwdt/compiler_flags.cmake:173]: `-fstack-protector-all` and `-fstack-protector` are different options. User should be able to select them different. If no explicit choice is specified by user, `-fstack-protector-all` can be taken to make it compatibility with previous versions

**Comment by vujjuri** [comment]
> As described in the issue, there may be 4 levels of protection (`-fstack-protector, -fstack-protector-strong, -fstack-protector-all and -fstack-protector-explicit`). The PR excludes the lowest level (`-fstack-protector`), any reason? Isn't it confusing to take over the post-fix names but change the no-postfix version to '-all'?

I agree. `-fstack-protector-all` and `-fstack-protector` are different options. User should be able to select among those. If no explicit choice is specified by user, `-fstack-protector-all` can be taken to make it compatibility with previous versions

**Comment by ceolin** [comment]
> > As described in the issue, there may be 4 levels of protection (`-fstack-protector, -fstack-protector-strong, -fstack-protector-all and -fstack-protector-explicit`). The PR excludes the lowest level (`-fstack-protector`), any reason? Isn't it confusing to take over the post-fix names but change the no-postfix version to '-all'?
> 
> I agree. `-fstack-protector-all` and `-fstack-protector` are different options. User should be able to select among those. If no explicit choice is specified by user, `-fstack-protector-all` can be taken to make it compatibility with previous versions


Yep, they are not the same, I kept it to keep the same the symbol name and behavior, otherwise I would need to change the current symbol to `-fstack-protector` to add `STACK_CANARIES_ALL` for he current option.

That's said I have no hard feeling about adding it, I just don't know how much we gain adding it.

**Comment by ruuddw** [comment]
> That's said I have no hard feeling about adding it, I just don't know how much we gain doing it.

My preference would be to align the Zephyr names with the compiler names. I find it confusing to map the less intrusive "STACK_CANARIES" to the strongest option "stack-protector-all". And to have "STACK_CANARIES_STRONG" to be weaker than "STACK_CANARIES".

For the explicit option, unfortunately there is a mismatch between gcc and llvm. From what I understand gcc uses pragma's to explicitly enable canaries for a function, and llvm/clang has pragma's to explicitly disable canaries. I don't see an easy way to abstract from this and have a unified approach.

File: cmake/compiler/arcmwdt/compiler_flags.cmake [hunk 10]
```diff
@@ -168,6 +168,8 @@ set_compiler_property(PROPERTY imacros -imacros)
...
```
Comment (ruuddw) [inline cmake/compiler/arcmwdt/compiler_flags.cmake:172]: MetaWare is like llvm/clang, there is no "-fstack-protector-explicit" option, and instead of `__attribute__((stack_protector))`  the ` __attribute__((no_stack_protector))` is used for explicit control.

File: include/zephyr/toolchain/llvm.h [hunk 11]
```diff
@@ -28,6 +28,13 @@
 #define TOOLCHAIN_HAS_C_AUTO_TYPE 1
 #endif
 
+/*
+ * -fstack-protector-explicit is not available in clang.
+ * Define the macro before including gcc.h to avoid
+ * problems with non existent attribute.
+ */
+#define __stack_protect
```
Comment (ruuddw) [inline include/zephyr/toolchain/llvm.h:36]: Something similar will be needed for MetaWare as well.

**Review by ruuddw — CHANGES_REQUESTED** [review]

File: cmake/compiler/arcmwdt/compiler_flags.cmake (hunk 10 above)
Comment (ceolin) [reply cmake/compiler/arcmwdt/compiler_flags.cmake:172]: So it is the other way around, instead of tells which functions the compiler should instrument you tells which ones shouldn't ?

**Comment by ceolin** [comment]
> > That's said I have no hard feeling about adding it, I just don't know how much we gain doing it.
> 
> My preference would be to align the Zephyr names with the compiler names. I find it confusing to map the less intrusive "STACK_CANARIES" to the strongest option "stack-protector-all". And to have "STACK_CANARIES_STRONG" to be weaker than "STACK_CANARIES".
> 
> For the explicit option, unfortunately there is a mismatch between gcc and llvm. From what I understand gcc uses pragma's to explicitly enable canaries for a function, and llvm/clang has pragma's to explicitly disable canaries. I don't see an easy way to abstract from this and have a unified approach.

I can add macros for both, disable / enable. There is no internal usage of these macros and we can enforce that only application uses it. The application will need to know which toolchain is been used but there is not much else we can do. These compilers have different approach for this.

**Comment by ceolin** [comment]
> `I can add macros for both, disable / enable. There is no internal usage of these macros and we can enforce that only application uses it. The application will need to know which toolchain is been used but there is not much else we can do. These compilers have different approach for this.`
> 
> That could work, but it doesn't really abstract to a unified solution. Maybe just using the attributes instead of a macro is good enough. Risk of macros that get compiled away is that people may assume a canary is inserted or prevented while it isn't.

That is a good point indeed. I will remove it.

**Comment by ruuddw** [comment]
Thanks, just a final question to check if it was a design choice or mistake. MetaWare doesn't support `-fstack-protector-explicit`, selecting it will result in compiler warnings. An alternative to the compiler warning could be a configuration time solution blocking the choice, or a pre-processor #error instead of compiler warning. In any case the user will notice, so I don't have a strong preference. Only concern now is that the user doesn't know if this is a bug or a feature. So I suggest to at least add a remark in the description of `config STACK_CANARIES_EXPLICIT` that it is not supported for all toolchains.

**Comment by ceolin** [comment]
> Thanks, just a final question to check if it was a design choice or mistake. MetaWare doesn't support `-fstack-protector-explicit`, selecting it will result in compiler warnings. An alternative to the compiler warning could be a configuration time solution blocking the choice, or a pre-processor #error instead of compiler warning. In any case the user will notice, so I don't have a strong preference. Only concern now is that the user doesn't know if this is a bug or a feature. So I suggest to at least add a remark in the description of `config STACK_CANARIES_EXPLICIT` that it is not supported for all toolchains.

I will fix it, @ruuddw where can I find the MetaWare compiler documentation ? I briefly tried to find this yesterday but failed.

Thanks for checking it closely !

**Comment by ruuddw** [comment]
There's no online documentation for MetaWare, as far as I know. There is a free version, called [MetaWare Lite](https://www.synopsys.com/cgi-bin/arcmwtk_lite/reg1.cgi). Windows only, and image size restricted to 32 kB (good to ensure people care about codesize...). That includes documentation. Appreciate your efforts - it is also fine to rely on the ARC team and me to provide the inputs and testing. We have internal CI running with MetaWare as well to catch problems.

**Review by ruuddw — APPROVED** [review]
All good now!

**Review by tejlmand — APPROVED** [review]
