### PR TITLE
Bluetooth fixes for build failures

### LINKED ISSUE #18298: Unable to build mesh-demo for BBC micro:bit
---
name: Unable to build mesh-demo for BBC micro:bit
about: SRAM exceeded by 64 bytes
labels: bug
---
**Bug**
Using both the GNU gcc toolchain, and the Zephyr 0.10.2 SDK, attempting to build this firmware fails with the following:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:       83866 B       256 KB     31.99%
            SRAM:       16448 B        16 KB    100.39%
        IDT_LIST:         136 B         2 KB      6.64%
/home/david/zephyr-sdk-0.10.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: zephyr_prebuilt.elf section `_net_buf_pool_area' will not fit in region `SRAM'
/home/david/zephyr-sdk-0.10.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: section .intList VMA [0000000020004000,0000000020004087] overlaps section _net_buf_pool_area VMA [0000000020003fc0,000000002000403f]
/home/david/zephyr-sdk-0.10.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.3.0/../../../../arm-zephyr-eabi/bin/ld: region `SRAM' overflowed by 64 bytes
collect2: error: ld returned 1 exit status
```

Tested using both Ninja and make.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=bbc_microbit ..
3. make

**Impact**
showstopper

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu
 - Toolchain Zephyr SDK / GNU make
 - Commit 5d30d49

### PR DESCRIPTION
**Pull request by carlescufi**
Fix the Bluetooth samples in #18246

Fixes #18298

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by joerchan — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 1]
```diff
@@ -781,6 +781,11 @@ void ll_rx_mem_release(void **node_rx)
 		case NODE_RX_TYPE_USER_START ... NODE_RX_TYPE_USER_END:
 #endif /* CONFIG_BT_CTLR_USER_EXT */
 
+		/* Ensure that at least one 'case' statement is present for this
+		 * code block.
+		 */
+		case NODE_RX_TYPE_NONE:
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull.c]: Approved.

**Review by cvinayak — APPROVED** [review]

**Review by galak — APPROVED** [review]
