### PR TITLE
mcuboot: enable use on RISC-V with ram load mode 

### LINKED ISSUE #83941: mcuboot: Don't select CONFIG_USE_DT_CODE_PARTITION, when CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD
**Describe the bug**
When ``CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD`` is activated, ``CONFIG_USE_DT_CODE_PARTITION`` should not be selected by ``CONFIG_BOOTLOADER_MCUBOOT``, as we don't know on build time on which partition our current image is.

**To Reproduce**
NA

**Expected behavior**
NA

**Impact**
RAM load mode does not work right. 

**Logs and console output**
NA

**Environment (please complete the following information):**
NA

**Additional context**

### PR DESCRIPTION
**Pull request by maass-hamburg**
this enables the use of mcuboot on riscv with ram load mode.

for that a function to get the flash_img_get_upload_slot() is needed.

Fixes: #83941

### CODE REVIEW

File: subsys/dfu/boot/mcuboot.c [hunk 1]
```diff
@@ -75,8 +74,8 @@ struct mcuboot_v1_raw_header {
  * End of strict defines
  */
 
-#if defined(CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD)
-static uint8_t boot_fetch_active_slot(void)
+#ifdef CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD
```
Comment (nordicjm) [inline subsys/dfu/boot/mcuboot.c:77]:
```suggestion
#if defined(CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD)
```

**Review by nordicjm — COMMENTED** [review]
Changes look OK, one nit.

**Review by nordicjm — DISMISSED** [review]

**Comment by maass-hamburg** [comment]
We have some problems in ci, now that `CONFIG_ROM_START_OFFSET` isn't ignored anymore on RISCV platforms and actually used.

**Comment by d3zd3z** [comment]
The CI issues will have to be addressed.

File: arch/common/CMakeLists.txt [hunk 2]
```diff
@@ -76,9 +76,9 @@ zephyr_linker_sources_ifdef(CONFIG_NOCACHE_MEMORY
   nocache.ld
 )
 
-# Only ARM, X86 and OPENISA_RV32M1_RISCV32 use ROM_START_OFFSET.
+# Only ARM, X86 and RISCV use ROM_START_OFFSET.
 if (DEFINED CONFIG_ARM OR DEFINED CONFIG_X86 OR DEFINED CONFIG_ARM64
-    OR DEFINED CONFIG_SOC_OPENISA_RV32M1)
+    OR (DEFINED CONFIG_RISCV AND CONFIG_ROM_START_OFFSET GREATER 0))
```
Comment (nordicjm) [inline arch/common/CMakeLists.txt:81]: why is `CONFIG_ROM_START_OFFSET > 0` needed here but only for risc?

Comment (maass-hamburg) [reply arch/common/CMakeLists.txt:81]: - I don't wanted to change it for the other archs
- there are some riscv soc, that don't work, so the part to add a offset is only used, if that offset is needed

Comment (nordicjm) [reply arch/common/CMakeLists.txt:81]: If the others are failing, they should be fixed, this is adding a hack

Comment (maass-hamburg) [reply arch/common/CMakeLists.txt:81]: the problem was mainly opentitan, which needs to put a other rom header in front. maybe @snematbakhsh can help

Comment (maass-hamburg) [reply arch/common/CMakeLists.txt:81]: @nordicjm the opentitan one is not compatible with having a CONFIG_ROM_START_OFFSET, because it has to put something soc specific in front in the linker.

Comment (maass-hamburg) [reply arch/common/CMakeLists.txt:81]: for the opentitan soc the offset is now forced to be `0x0`.

Comment (tejlmand) [reply arch/common/CMakeLists.txt:81]: > for the opentitan soc the offset is now forced to be 0x0.

so can the `CONFIG_ROM_START_OFFSET GREATER 0` be removed then ?
I agree with @nordicjm that this is not a nice adjustment.

Or can you elaborate so much on the issue that we might find another way to handle this ?

Comment (maass-hamburg) [reply arch/common/CMakeLists.txt:81]: no `CONFIG_ROM_START_OFFSET GREATER 0` is necessary , so that
```
  zephyr_linker_sources(ROM_START SORT_KEY ! rom_start_address.ld)
  # Some linkers fill unspecified region with pattern other than 0x00. Include
  # fill_with_zeros.ld file which forces the linker to use 0x00 pattern. Please
  # note that the pattern will affect empty spaces created after FILL(0x00).
  zephyr_linker_sources(ROM_START SORT_KEY $ fill_with_zeros.ld)
 zephyr_linker_sources(ROM_START SORT_KEY 0x0 rom_start_offset.ld)
```
is not used on the opentitan soc

**Comment by maass-hamburg** [comment]
@tkng-rivos @snematbakhsh ping ??

File: arch/common/CMakeLists.txt (hunk 2 above)
Comment (snematbakhsh) [reply arch/common/CMakeLists.txt:81]: @maass-hamburg  Once we turn on CONFIG_ROM_START_OFFSET for risc-v, I think we need to account for the manifest (similar to [what is done here for another SOC](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/nxp/rw/Kconfig.defconfig#L8)). So I think we want to change [soc/lowrisc/opentitan/Kconfig.defconfig](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/lowrisc/opentitan/Kconfig.defconfig) as follows:

```
# The OpenTitan SoC requires a manifest in front of the
# application binary.
config ROM_START_OFFSET
	default 0x404
```
.. and subsequently we no longer need the "GREATER 0" special case.

Why 0x404 and not 0x400 for 1024 byte manifest, you ask? [It's this bug](https://github.com/zephyrproject-rtos/zephyr/issues/82822), I will take care of it once you land your PR (so just use 0x404).

Comment (maass-hamburg) [reply arch/common/CMakeLists.txt:81]: @snematbakhsh the `CONFIG_ROM_START_OFFSET` will result in everything before the offset being filled with zeros. But you need to write the start address in the manifest  see here: https://github.com/zephyrproject-rtos/zephyr/blob/90ff9c0883b29dc0c59e3dd063114e30a4b27456/soc/lowrisc/opentitan/rom_header.S#L25

We would also have to remove the part for creating the manifest, because it would conflict with the  `CONFIG_ROM_START_OFFSET` code.

Comment (snematbakhsh) [reply arch/common/CMakeLists.txt:81]: @maass-hamburg 

> the CONFIG_ROM_START_OFFSET will result in everything before the offset being filled with zeros.

It seems to work fine on my side, did I miss something?
Applying patches 1d65a59355fb53a606db1b8ffa54c73dc2800095 (to generate .bin) and 387478cdbdedb1de8aba526bb23298c5f7139156 (my proposed change as previously discussed). 

```
$ west build -b opentitan_earlgrey samples/hello_world/
$ hexdump build/zephyr/zephyr.bin | more
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
0000380 0000 0000 0404 0000 0000 0000 0000 0000
0000390 0000 0000 0000 0000 0000 0000 0000 0000
*
0000400 0000 0000 1197 f000 8193 4541 0297 0000
```

I think this works because [the SORT_KEY for the OpenTitan manifest](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/lowrisc/opentitan/CMakeLists.txt#L5) ("000") precedes [the SORT_KEY for rom_start_offset.ld](https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/common/CMakeLists.txt#L89) ("0x0").

Comment (maass-hamburg) [reply arch/common/CMakeLists.txt]: seems like its working

**Review by snematbakhsh — DISMISSED** [review]

**Review by nordicjm — COMMENTED** [review]
minor nit.

**Comment by maass-hamburg** [comment]
fixed nit.

File: tests/kernel/smp/testcase.yaml [hunk 3]
```diff
@@ -31,6 +31,9 @@ tests:
       - smp
     ignore_faults: true
     filter: (CONFIG_MP_MAX_NUM_CPUS > 1)
+    platform_exclude:
+      - qemu_riscv64/qemu_virt_riscv64/smp
+      - qemu_riscv32/qemu_virt_riscv32/smp
```
Comment (cfriedt) [inline tests/kernel/smp/testcase.yaml:36]: This seems completely unrelated to the PR. Please revert.

**Review by cfriedt — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

File: tests/kernel/smp/testcase.yaml (hunk 3 above)
Comment (maass-hamburg) [reply tests/kernel/smp/testcase.yaml]: @cfriedt these tests are now failing, and I don't know why. You may want to take a look.

**Review by cfriedt — DISMISSED** [review]

**Comment by maass-hamburg** [comment]
qemu_riscv64 and qemu_riscv32 do not support a different a ROM offset. The start has to be at `0x80000000`. It is not using the Entry point address from the elf file.

**Review by cfriedt — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
