### PR TITLE
nxp-fix-lpuart-dma-race-condition-issue

### LINKED ISSUE #102001: uart_mcux_lpuart: DMA race condition with sysworkq and isr
### Describe the bug

Race condition in uart_mcux_lpuart between ISR and Work Queue causes RX length underflow

I have identified a concurrency issue in the uart_mcux_lpuart driver that leads to a system crash due to an integer underflow.

Symptoms: The system crashes after proccossing the underflowed len value (which yield to FFFF FFBC size len is size_t which is unsigned)
```
[00:12:11.098,000] <dbg> uart_mcux_lpuart: RX Ready: (len: -68 off: 68 buf: 20200140)
```
Root Cause Analysis: The issue stems from a race condition between the System Work Queue (sysworkq) and the DMA Interrupt Service Routine (ISR).
- Context A: sysworkq executes mcux_lpuart_async_rx_timeout.
- Context B: The ISR preempts the work queue to execute dma_callback.

Both contexts access and modify data->async.rx_dma_params without any synchronization or locking mechanism. Specifically, the ISR modifies the DMA parameters while the timeout function is in the middle of calculating the RX length:
```c
.data.rx.len = dma_params->counter - dma_params->offset
```

If the ISR updates counter or offset mid-calculation, this subtraction results in an underflow. Access to rx_dma_params should be protected by a critical section or lock.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Take an UART async application that utilizing DMA, let it run for 10-60 minutes eventually len would underflow which could escalate to to a busfault.

### Relevant log output

```shell

```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Holt-Sun**
This resolve https://github.com/zephyrproject-rtos/zephyr/issues/102001

## Overview

This PR fixes a critical race condition in the LPUART async driver that causes system crashes due to RX buffer length underflow, and improves error diagnostics in the RX enable path.

### Race Condition (Patch 2/2)
A race condition exists between the system work queue executing `mcux_lpuart_async_rx_timeout()` and the DMA ISR executing `dma_callback()`. Both contexts access and modify `data->async.rx_dma_params` without synchronization.

**Crash symptom:**
```
[00:12:11.098,000] <dbg> uart_mcux_lpuart: RX Ready: (len: -68 off: 68 buf: 20200140)
```

When the ISR preempts during the length calculation `len = counter - offset`, it can update these values mid-calculation, resulting in integer underflow (0xFFFFFFBC for size_t), leading to system crash.

### Error Handling (Patch 1/2)
The original error handling in `mcux_lpuart_rx_enable()` combined two different error conditions with unclear messaging, making debugging difficult.

### Patch 1: Improve rx_enable error reporting
- Split DMA status query failures from busy status checks
- Use appropriate log levels (LOG_ERR for failures, LOG_DBG for busy)
- Provide specific error messages for better diagnostics

### Patch 2: Fix race condition
- Add `irq_lock()`/`irq_unlock()` protection around all `rx_dma_params` accesses in:
  - `async_evt_rx_rdy()` - protect counter/offset calculation
  - `mcux_lpuart_async_rx_flush()` - protect counter updates
  - `async_evt_rx_buf_release()` - atomic buffer pointer snapshot
- Initialize `offset`/`counter` to 0 in `mcux_lpuart_rx_enable()` for clean state
- Add overflow check in `mcux_lpuart_async_rx_flush()`
- Fix log format specifiers (%d → %zu for size_t, %x → %p for pointers)

Here is the test uart_async_rx run result:
```
[17:07:00.384]*** Booting Zephyr OS build v4.3.0-3941-g2ac20b86f1cf ***
Running TESTSUITE uart_async_rx
===================================================================
START - test_rx
 PASS - test_rx in 0.001 seconds
===================================================================
START - test_rx_late_consume
 PASS - test_rx_late_consume in 0.001 seconds
===================================================================
START - test_rx_ztress_no_chunks

[17:07:01.432]0% remaining:4000 ms
[17:07:02.429]0% remaining:3000 ms
[17:07:03.428]0% remaining:2000 ms
[17:07:04.428]0% remaining:1000 ms
[17:07:05.428]0% remaining:0 ms
Ztress execution report:
	 context 0:
		 - executed:8042, preempted:0
		 - ticks initial:20, optimized:4
	 context 1:
		 - executed:8036, preempted:0
		 - ticks initial:20, optimized:4
	Average CPU load:12%, measurements:50
total bytes: 29055
 PASS - test_rx_ztress_no_chunks in 5.067 seconds
===================================================================
START - test_rx_ztress_with_chunks

[17:07:06.467]0% remaining:4000 ms
[17:07:07.462]0% remaining:3000 ms
[17:07:08.461]0% remaining:2000 ms
[17:07:09.457]0% remaining:1000 ms
[17:07:10.452]0% remaining:0 ms
Ztress execution report:
	 context 0:
		 - executed:8031, preempted:0
		 - ticks initial:20, optimized:4
	 context 1:
		 - executed:8031, preempted:0
		 - ticks initial:20, optimized:4
	Average CPU load:14%, measurements:50
total bytes: 26372
 PASS - test_rx_ztress_with_chunks in 5.052 seconds
===================================================================
TESTSUITE uart_async_rx succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [uart_async_rx]: pass = 4, fail = 0, skip = 0, total = 4 duration = 10.121 seconds
 - PASS - [uart_async_rx.test_rx] duration = 0.001 seconds
 - PASS - [uart_async_rx.test_rx_late_consume] duration = 0.001 seconds
 - PASS - [uart_async_rx.test_rx_ztress_no_chunks] duration = 5.067 seconds
 - PASS - [uart_async_rx.test_rx_ztress_with_chunks] duration = 5.052 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

### CODE REVIEW

**Comment by Holt-Sun** [comment]
> I do have suggestion though for patch 2, wouldn't it be better to only disable the specific LPUART DMA interrupt in the `mcux_lpuart_async_rx_timeout` function and then after returning from `mcux_lpuart_async_rx_flush` re-enable the interrupt? Now we disable al interrupts, but we know that only the DMA interrupt could cause this.

Hi @PetervdPerk-NXP , thanks for the suggestion. The racing context here is the DMA controller ISR (dma_callback()), not an LPUART peripheral interrupt. Disabling “LPUART DMA interrupts” around mcux_lpuart_async_rx_timeout() wouldn’t prevent the DMA driver from invoking the RX DMA callback and updating rx_dma_params concurrently.

To mask only the specific source, we’d need to disable the DMA channel IRQ (or otherwise stop the DMA engine/callback) during the critical section. Zephyr’s generic DMA API doesn’t provide a portable “disable just this DMA channel interrupt” primitive, and adding DMA-driver-specific masking would be more invasive and risk missing completion notifications / ordering issues.

The current fix keeps the irq_lock() scope very small (just snapshot/update of rx_dma_params; callbacks/logging happen after unlock), and it protects all shared access points (async_evt_rx_rdy(), mcux_lpuart_async_rx_flush(), async_evt_rx_buf_release()), which is necessary because those helpers are reached from both thread/workqueue and ISR paths

**Review by PetervdPerk-NXP — DISMISSED** [review]
I ran a duration test and couldn't reproduce the crash anymore.
LGTM

File: drivers/serial/uart_mcux_lpuart.c [hunk 1]
```diff
@@ -468,19 +468,32 @@ static void async_evt_rx_rdy(const struct device *dev)
...
+	size_t offset;
+	size_t len;
+
+	key = irq_lock();
+	buf = dma_params->buf;
+	counter = dma_params->counter;
+	offset = dma_params->offset;
+
+	len = counter - offset;
+
```
Comment (mmahadevan108) [inline drivers/serial/uart_mcux_lpuart.c:488]: Can you help me understand why we need to store these in local variables. Maybe a comment here would also be helpful

Comment (Holt-Sun) [reply drivers/serial/uart_mcux_lpuart.c:488]: I store buf, counter, and offset in local variables to take a consistent snapshot of rx_dma_params while interrupts are locked. These fields can be updated by the DMA ISR concurrently, so reading them directly multiple times risks mixing values from different points in time (e.g., new counter with old offset), which can lead to incorrect length computation (including underflow) and inconsistent event/log payloads. Using locals lets us keep the irq_lock() window short (snapshot + offset update only), while building the uart_event, logging, and calling the user callback outside the critical section.

Comment (Holt-Sun) [reply drivers/serial/uart_mcux_lpuart.c:488]: Comment has been added: https://github.com/zephyrproject-rtos/zephyr/pull/102559/changes#diff-b52eb85e1cdf037f16de983f18bf4cfb8079bc5e657706e94a36de8cf842167aR476-R479

Comment (mmahadevan108) [reply drivers/serial/uart_mcux_lpuart.c:488]: If we are locking out the interrupts using `irq_lock` then it should avoid the scenario you mention. Is it sufficient to lock out irqs without making a local copy, please look into this.

Comment (Holt-Sun) [reply drivers/serial/uart_mcux_lpuart.c:488]: It’s sufficient only if you keep irq_lock() held for the entire time you use those values, but we explicitly don’t want that (callback/logging). Therefore, you still need a snapshot. Locals are just the simplest snapshot mechanism; populating the event struct under the lock would be an equivalent alternative.

**Review by mmahadevan108 — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]
