### PR TITLE
Bluetooth: Controller: Fix ISO Tx PDU memory pool corruption

### LINKED ISSUE #45666: Building samples about BLE audio with nrf5340dk does not work
**Describe the bug**
I built zephyr/samples/broadcast_audio_source and zephyr/samples/unicast_audio_server for nrf5340dk_nrf5340_cpuapp, but the demo prompts an error when running, I think it has something to do with the configuration of zephyr/samples/hci_rpmsg built for nrf5340dk_nrf5340_cpunet.I see in zephyr/samples/hci_rpmsg that in addition to prj.conf there is also nrf5340_cpunet_iso_broadcast.conf and nrf5340_cpunet_iso_receive.conf, but I can't get the sample to work no matter which file I use.

**To Reproduce**
1. west build -b nrf5340dk_nrf5340_cpuapp -d 5340_cpuapp -p auto .\samples\bluetooth\broadcast_audio_source\
2. west flash -d 5340_cpuapp
3. west build -p auto -b nrf5340dk_nrf5340_cpunet -d 5340_cpunet -- -DCONF_FILE="E:/zephyr/zephyrproject/zephyr/samples/bluetooth/hci_rpmsg/nrf5340_cpunet_iso_broadcast.conf" .\samples\bluetooth\hci_rpmsg\
4. west flash -d 5340_cpunet
or use default configuration for hci_rpmsg 
3. west build -p auto -b nrf5340dk_nrf5340_cpunet -d 5340_cpunet .\samples\bluetooth\hci_rpmsg\
4. west flash -d 5340_cpunet

And:
1. west build -b nrf5340dk_nrf5340_cpuapp -d 5340_cpuapp -p auto .\samples\bluetooth\unicast_audio_server\
2. west flash -d 5340_cpuapp
3. west build -p auto -b nrf5340dk_nrf5340_cpunet -d 5340_cpunet -- -DCONF_FILE="E:/zephyr/zephyrproject/zephyr/samples/bluetooth/hci_rpmsg/nrf5340_cpunet_iso_broadcast.conf" .\samples\bluetooth\hci_rpmsg\
4. west flash -d 5340_cpunet
or same as above

**Expected behavior**
Samples running successfully

**Logs and console output**
broadcast_audio_source:(use nrf5340_cpunet_iso_broadcast.conf)
*** Booting Zephyr OS build zephyr-v3.0.0-3960-g782480313edc  ***
Bluetooth initialized
Creating broadcast source
Unable to create broadcast source: -5
[00:00:00.282,165] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.282,196] <inf> bt_hci_core: HW Variant: nRF53x (0x0003)
[00:00:00.282,226] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 3.0 Build 99
[00:00:00.283,874] <inf> bt_hci_core: Identity: FD:57:DF:FB:69:05 (random)
[00:00:00.283,905] <inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x05f1
[00:00:00.283,935] <inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffff
[00:00:00.292,724] <wrn> bt_hci_core: opcode 0x2037 status 0x07

unicast_audio_server:(use nrf5340_cpunet_iso_broadcast.conf)
*** Booting Zephyr OS build zephyr-v3.0.0-3960-g782480313edc  ***
Bluetooth initialized
Failed to set advertising data (err -5)
[00:00:00.279,632] <wrn> bt_hci_core: Controller to host flow control not supported
[00:00:00.282,012] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.282,043] <inf> bt_hci_core: HW Variant: nRF53x (0x0003)
[00:00:00.282,043] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 3.0 Build 99
[00:00:00.284,057] <inf> bt_hci_core: Identity: FD:57:DF:FB:69:05 (random)
[00:00:00.284,088] <inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x05f1
[00:00:00.284,088] <inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffff
[00:00:00.287,811] <wrn> bt_hci_core: opcode 0x2037 status 0x07
[00:00:00.296,783] <wrn> bt_pacs: PACS notify failed: -2

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: arm-none-eabi
 - Commit: 3.0.99

**Additional context**
I want to know the configuration of the nrf5340dk_nrf5340_cpunet for each BLE audio sample,I can't find any relevant descriptions

### PR DESCRIPTION
**Pull request by cvinayak**
Increase the Controller supported Advertising Data Length
Maximum so that Advertising Data set by Broadcast Audio
Source sample is accepted by the controller.

Also, tune down the supported ISO Tx PDU size to suffice the
Broadcast Audio Source usecase.

Move the removal of BIG context association with the
Periodic Advertising context to when the BIG streams are
release and BIG terminate message is generated.

Add implementation to flush pending ISO Tx PDUs when BIG
events are terminated.

Fix ISO Tx PDU memory pool corruption due to duplicate ISO
Tx PDU buffers repeatedly released into the memory pool.

Fixes #45666.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 1]
```diff
@@ -2414,26 +2414,58 @@ static uint8_t tx_cmplt_get(uint16_t *handle, uint8_t *first, uint8_t last)
...
+			 *
+			 *       Tx node is released early without waiting for
+			 *       any dependency on Rx queue. Released Tx node
+			 *       reference is overloaded to store the Tx
+			 *       fragment count.
+			 *
+			 *       A hack is used here that depends on the fact
+			 *       that memory addresses have a value greater than
+			 *       0xFF, to determined if a node Tx has been
+			 *       released in a prior iteration of this function.
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull.c:2430]: So is this a temporary solution? If so, I suggest to create a GH issue to track this and to implement a proper solution.

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull.c:2430]: Is implementing this without a "hack" a large task, or what is the reasoning to use a "hack"?

**Comment by Thalley** [comment]
Running the `broadcast_audio_source` on the 52840DK with this PR:
```
*** Booting Zephyr OS build v3.1.0-rc2-62-g7c895b3d7fd9  ***
Bluetooth initialized
Creating broadcast source
Starting broadcast source
[00:00:00.365,142] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.365,173] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
[00:00:00.365,203] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 3.1 Build 0
[00:00:00.365,814] <inf> bt_hci_core: Identity: C4:E7:C8:4B:98:F5 (random)                 
[00:00:00.365,844] <inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x05f1
[00:00:00.365,844] <inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffff                
Broadcast source started
Waiting 30 seconds before stopped
Sent 1000 total ISO packets
Sent 2000 total ISO packets
Sent 3000 total ISO packets
Stopping broadcast source
Broadcast source stopped
Deleting broadcast source
Broadcast source deleted
Creating broadcast source
Starting broadcast source
[00:00:31.677,581] <err> bt_hci_core: packets count mismatch
[00:00:31.677,642] <err> bt_hci_core: packets count mismatch
Broadcast source started
Waiting 30 seconds before stopped
[00:00:32.914,215] <err> bt_hci_core: No connection for handle 0
[00:00:32.914,306] <err> bt_hci_core: No connection for handle 0
Sent 4000 total ISO packets
Sent 5000 total ISO packets
Sent 6000 total ISO packets
Stopping broadcast source
Broadcast source stopped
Deleting broadcast source
Broadcast source deleted
Creating broadcast source
Starting broadcast source
[00:01:03.005,096] <err> bt_hci_core: packets count mismatch
[00:01:03.005,187] <err> bt_hci_core: packets count mismatch
Broadcast source started
Waiting 30 seconds before stopped
[00:01:04.241,485] <err> bt_hci_core: No connection for handle 0
[00:01:04.241,577] <err> bt_hci_core: No connection for handle 0
```

The same sample running on main (SHA: c534ae294724f3463369363da9818a7a3cf81f95)
```
*** Booting Zephyr OS build v3.1.0-rc2-58-gc534ae294724  ***
Bluetooth initialized
Creating broadcast source
Starting broadcast source
[00:00:00.363,983] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.364,013] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
[00:00:00.364,044] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 3.1 Build 0
[00:00:00.364,654] <inf> bt_hci_core: Identity: C4:E7:C8:4B:98:F5 (random)
[00:00:00.364,654] <inf> bt_hci_core: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x05f1
[00:00:00.364,685] <inf> bt_hci_core: LMP: version 5.3 (0x0c) subver 0xffff
Broadcast source started
Waiting 30 seconds before stopped
Sent 1000 total ISO packets
Sent 2000 total ISO packets
Sent 3000 total ISO packets
Stopping broadcast source
Broadcast source stopped
Deleting broadcast source
Broadcast source deleted
Creating broadcast source
Starting broadcast source
[00:00:31.675,903] <err> bt_hci_core: packets count mismatch
[00:00:31.675,994] <err> bt_hci_core: packets count mismatch
Broadcast source started
Waiting 30 seconds before stopped
[00:00:32.901,458] <err> bt_hci_core: No connection for handle 0
[00:00:32.901,550] <err> bt_hci_core: No connection for handle 0
Stopping broadcast source
Broadcast source stopped
Deleting broadcast source
Broadcast source deleted
Creating broadcast source
Starting broadcast source
[00:01:02.992,828] <err> bt_hci_core: packets count mismatch
Broadcast source started
Waiting 30 seconds before stopped
[00:01:04.218,170] <err> bt_hci_core: No connection for handle 0
[00:01:04.218,261] <err> bt_hci_core: No connection for handle 0
```

The BUS FAULT mentioned in https://github.com/zephyrproject-rtos/zephyr/issues/45666#issuecomment-1131539301 is no longer present on main (fixed by something else?), and this PR does improve the recreation of the BIG, but the issues with "packets count mismatch" and "No connection for handle 0" are still present.

**Comment by cvinayak** [comment]
> The BUS FAULT mentioned in https://github.com/zephyrproject-rtos/zephyr/issues/45666#issuecomment-1131539301 is no longer present on main (fixed by something else?), and this PR does improve the recreation of the BIG, but the issues with "packets count mismatch" and "No connection for handle 0" are still present.

I was able to reproduce the BUS FAULT on upstream/main yesterday. And without this PR, but with #45069 included their will be assertion in `ull_adv_iso.c`. The fault depends on memory layout due to invalid memory released into controller's ISO Tx PDU pool.

**Comment by Thalley** [comment]
> > The BUS FAULT mentioned in [#45666 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/45666#issuecomment-1131539301) is no longer present on main (fixed by something else?), and this PR does improve the recreation of the BIG, but the issues with "packets count mismatch" and "No connection for handle 0" are still present.
> 
> I was able to reproduce the BUS FAULT on upstream/main yesterday. And without this PR, but with #45069 included their will be assertion in `ull_adv_iso.c`. The fault depends on memory layout due to invalid memory released into controller's ISO Tx PDU pool.

Can you also reproduce it on `main` today? Is it related to timing, or did something change since yesterday?

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull.c:2430]: The implementation comes from the original controller contribution, and has not been changed since then.

**Comment by cvinayak** [comment]
image

I am able to reproduce it on the tag: v3.1.0-rc2, with one BT_DBG changed to printk.
And with the commits in this PR cherry-picked the fault is not reproducible.

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull.c:2430]: I will give a thought, this has to done for the ACL Tx ack too where there is difference between ack that is generating a num complete only for data PDU and not for control PDU (inline ENC_REQ PDU) that was transmitted.

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 1 above)
Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull.c:2480]: I have an alternative solution for which I will make a PR today

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull.c:2480]: @mtpr-ot should we merge this PR and thereafter yours? (#49855 LGTM, though you apply the same changes to ACL too).

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull.c:2480]: @cvinayak ACL, what do you mean?

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull.c:2480]: I think my solution is more intuitive, and if possible, should go in first. You need to re-implement this for current state of main anyway.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull.c:2480]: > ACL, what do you mean? 

Check this PR changes, ACL connections too use similar bitmask for num complete counting, it will be best if both are fixed.

> I agree, this is very difficult to understand and maintain, so instead of repeating the pattern from node_tx for node_tx_iso, could we perhaps use the available unused bits in node_tx_iso for a state, which can maintain the information instead of overloading the pointer meaning?

#49855 is still the same hack but hiding the code with macros, compared to your original request in this PR was for a redesign.

There seems to be no merge conflicts reported in this PR. As #49855 is just a refactor of the existing hack, it should go after this PR which is a fix for a github issue.

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull.c:2480]: @cvinayak Please rebase

**Review by mtpr-ot — CHANGES_REQUESTED** [review]
It looks like the changes in this PR reverts previous commits in ull.c. Please fix.

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 2]
```diff
@@ -2464,21 +2464,56 @@ static uint8_t tx_cmplt_get(uint16_t *handle, uint8_t *first, uint8_t last)
...
+				}
 
-			if (IS_ADV_ISO_HANDLE(tx->handle)) {
-				/* FIXME: ADV_ISO shall be updated to use ISOAL for
-				 * TX. Until then, assume 1 node equals 1 fragment.
-				 */
-				cmplt += 1;
-			} else {
-				/* We count each SDU fragment completed by this PDU */
-				cmplt += tx_node_iso->sdu_fragments;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull.c:2477]: @mtpr-ot This is not a revert of previous changes in ull.c. Do you mean the comments missing?

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 3]
```diff
@@ -2464,21 +2464,56 @@ static uint8_t tx_cmplt_get(uint16_t *handle, uint8_t *first, uint8_t last)
...
+			 *       0xFF, to determined if a node Tx has been
+			 *       released in a prior iteration of this function.
+			 */
 			tx_node_iso = tx->node;
 			p = (void *)tx_node_iso->pdu;
+			/* TODO: We may need something more advanced for framed */
+			if ((((uint32_t)tx_node_iso & ~0xFF) &&
+			     ((p->ll_id == PDU_CIS_LLID_COMPLETE_END) ||
+			      (p->ll_id == PDU_BIS_LLID_COMPLETE_END))) ||
+			    ((uint32_t)tx_node_iso & 0xFF)) {
```
Comment (mtpr-ot) [inline subsys/bluetooth/controller/ll_sw/ull.c]: Sorry for not being more precise. You are re-introducing code that was refactored away in a previous commit. This will not work, and will fail our qualification tests. There should be no LLID checks.

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Review by Thalley — APPROVED** [review]
