### PR TITLE
drivers: ieee802154: rf2xx: Add missing handle_ack call

### LINKED ISSUE #21763: at86rf2xx radio driver does not report whether a TX was ACKed
**Describe the bug**
The newly introduced at86rf2xx driver is doing automatic retransmissions in hardware based on whether ACKs are received or not. Currently the driver is not invoking `ieee802154_radio_handle_ack()` as other drivers are doing and required by OpenThread since https://github.com/zephyrproject-rtos/zephyr/commit/4fe1da9f588230d690d3df4232d066243bbe7b19.

**Impact**
OpenThread does not work on this radio.

**Environment (please complete the following information):**
 - Zephyr SHA 0b6c18bd64cc601d65f8f85def64618d376d16d2

**Additional context**
@nandojve, I am in the process of mimic'ing the behaviour of drivers/ieee802154/ieee802154_kw41z.c handle_ack().

### PR DESCRIPTION
**Pull request by nandojve**
The rf2xx driver is doing automatic retransmissions in hardware based
on whether ACKs are received or not. Currently the driver is not
invoking ieee802154_radio_handle_ack() as other drivers are doing and
required by OpenThread since 4fe1da9. This add rf2xx_handle_ack method
to ensures required ACK processing when driver performs TX.

Fixes: #21763

Signed-off-by: Gerson Fernando Budke <nandojve@gmail.com>

### CODE REVIEW

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 1]
```diff
@@ -378,6 +382,45 @@ static int rf2xx_filter(struct device *dev,
...
+	defined(CONFIG_NET_L2_OPENTHREAD)
+
+#define ACK_FRAME_LEN 3
+#define ACK_FRAME_TYPE (2 << 0)
+#define ACK_FRAME_PENDING_BIT (1 << 4)
+
+static void rf2xx_handle_ack(struct rf2xx_context *ctx, u8_t seq_number)
+{
+	struct net_pkt *pkt;
+	u8_t ack_psdu[ACK_FRAME_LEN] = {ACK_FRAME_TYPE, 0, seq_number};
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: reverse the order of these 2 lines, we usually follow "pre-assigned variables first, then the rest" in net stack. (I don't think it's documented anywhere though)

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 2]
```diff
@@ -378,6 +382,45 @@ static int rf2xx_filter(struct device *dev,
...
+
+	pkt = net_pkt_alloc_with_buffer(ctx->iface, ACK_FRAME_LEN,
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: What about allocating pkt on stack? it's a bit heavy yes, but at least you won't have to call the allocator, and thus no allocation error to handle (note that ieee802154_radio_handle_ack() do not mangle with pkt ref so it will be fine here)

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 3]
```diff
@@ -378,6 +382,45 @@ static int rf2xx_filter(struct device *dev,
...
+		LOG_ERR("No free packet available.");
+		return;
+	}
+
+	/* Re-create ACK frame. */
+	if (ctx->trx_trac == RF2XX_TRX_PHY_STATE_TRAC_SUCCESS_DATA_PENDING) {
+		ack_psdu[0] |=  ACK_FRAME_PENDING_BIT;
+	}
+
+	memcpy(pkt->buffer->data, ack_psdu, ACK_FRAME_LEN);
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: same as for pkt, allocate the buffer on stack and pre-fill it, no need to memcpy then.

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 4]
```diff
@@ -378,6 +382,45 @@ static int rf2xx_filter(struct device *dev,
...
+
+	/* Use some fake values for LQI and RSSI. */
+	net_pkt_set_ieee802154_lqi(pkt, 80);
+	net_pkt_set_ieee802154_rssi(pkt, -40);
+
+	if (ieee802154_radio_handle_ack(ctx->iface, pkt) != NET_OK) {
+		LOG_INF("ACK packet not handled - releasing.");
+	}
+
+	net_pkt_unref(pkt);
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: and then no need of this

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 5]
```diff
@@ -378,6 +382,45 @@ static int rf2xx_filter(struct device *dev,
...
+}
+#endif
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: you could have a: 
#else 
define rf2xx_handle_ack(...)

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 6]
```diff
@@ -444,6 +487,10 @@ static int rf2xx_tx(struct device *dev,
 	 */
 	default:
 		response = 0;
+#if !defined(CONFIG_IEEE802154_RAW_MODE) && \
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: so you could get rid of this #if ... #endif

**Review by tbursztyka — CHANGES_REQUESTED** [review]

File: drivers/ieee802154/ieee802154_rf2xx.c (hunk 2 above)
Comment (tbursztyka) [reply drivers/ieee802154/ieee802154_rf2xx.c]: Just something like:
struct net_buf buf = {
    .data = ack_psdu,
    .len = ACK_FRAME_LEN,
    .size = ACK_FRAME_LEN
};
struct net_pkt pkt = { .buffer = &buf };

and there you go.

**Review by tbursztyka — APPROVED** [review]
try to rebase against master to get CI pass (the error does not seem to be related to your patch)

**Comment by jukkar** [comment]
> try to rebase against master to get CI pass (the error does not seem to be related to your patch)

Easiest is just to re-trigger CI tests so closing and then re-opening the PR is enough.

**Comment by nandojve** [comment]
Hi Folks, I added DNM because I don't have a full setup to test OT yet, sorry about not comment about it. I'll start to create setup this weeek I hope test this ASAP.  After applying @tbursztyka tips I believe solution is ready, but need test first. @markus-becker-tridonic-com could you describe your setup so I can reproduce my own to test OT? Any tip how to create one and configure is welcome. You can find me at zephyrproject.slack.com too.

PS.: I have 2 - PCA10056 that may help and one Wireshark Sniffer.

**Comment by jukkar** [comment]
Adding also DNM label. Remember to remove the label after the PR is ready to be merged.

**Comment by markus-becker-tridonic-com** [comment]
@nandojve my test set-up is the Tridonic Thread BR based on mbed, but it should also work with a Nordic dev board BR based on OT: https://openthread.io/guides/border-router .

**Comment by jukkar** [comment]
ping @nandojve / @markus-becker-tridonic-com Is this PR ready for merge?

**Comment by nandojve** [comment]
> ping @nandojve / @markus-becker-tridonic-com Is this PR ready for merge?

Hello @jukkar, sorry for my delay. @markus-becker-tridonic-com did tests and report success at #21763. With this we fixed the issue and I'm removing DNM from PR Label. It's ready to be merged!

Thank you everyone for helping with this!

**Review by jukkar — APPROVED** [review]
