### PR TITLE
kernel: smp: remove unused internal API z_smp_reacquire_global_lock()

### LINKED ISSUE #33273: The z_smp_reacquire_global_lock() internal API is not used any where inside zephyr code base
**Describe the bug**
The z_prefix internal API, z_smp_reacquire_global_lock() in kernel/smp.c, which is not used by any code in zephyr project.

**To Reproduce**
1. By shell command **grep z_smp_reacquire_global_lock -rn --exclude-dir={doc, twister-out, build}** , you can only find it is declared and defined, but found nowhere it was called.  
2. Run "**twister -T tests/kernel/ -p qemu_x86 --coverage**" to generate the coverage report, and look at the kernel/smp.c line 44~52 were not be executed.

**Expected behavior**
This internal function shall be used by zephyr code base.

**Impact**
The impact is low. But there is no way to be covered by testing unless we call this internal API directly.

**Logs and console output**
Gcov coverage report:
```
44                 :          0 : void z_smp_reacquire_global_lock(struct k_thread *thread)
45                 :            : {
46         [ #  # ]:          0 :         if (thread->base.global_lock_count) {
47                 :          0 :                 arch_irq_lock();
48                 :            : 
49         [ #  # ]:          0 :                 while (!atomic_cas(&global_lock, 0, 1)) {
50                 :            :                 }
51                 :            :         }
52                 :          0 : }
```
**Additional context**
We want to confirm which solution can be applied for this issue:
1. Remove this API (Is it belongs to a dead code?)
2. Design a test case that will call internal API z_smp_reacquire_global_lock(). 
3. Leave it there and use /* LCOV_EXCL_START */   /* LCOV_EXCL_STOP */ to skip it in code coverage report.  

or another better solution for it, thanks!

### PR DESCRIPTION
**Pull request by enjiamai**
The internal function z_smp_reacquire_global_lock() has not used by
anywhere inside zephyr code, the context switch code logic did use it anymore also,  so remove it.

Fixes #33273.

Signed-off-by: Enjia Mai <enjiax.mai@intel.com>

### CODE REVIEW

File: kernel/include/kswap.h [hunk 1]
```diff
@@ -24,8 +24,11 @@ extern struct k_spinlock sched_spinlock;
  * thread (via either z_swap() or interrupt/exception return!) we need
  * to restore the lock state to whatever the thread's counter
  * expects.
+ *
+ * Note: The paired function z_smp_reacquire_global_lock() has been
+ * removed due to no longer being used during context switch.
+ * See issue #33273.
```
Comment (andyross) [inline kernel/include/kswap.h:30]: Take this comment out.   There's no need to document functions that don't exist.

**Review by andyross — APPROVED** [review]
Indeed, the need to restore the nested irq_lock() state went away with the scheduler rework of 2018 (because we now only sleep based on spinlocked state, and spinlocks aren't recursive).

In fact the fact that the kernel used to allow sleeping with a lock held was a bug in the earlier scheduler.

Good catch.

File: kernel/include/kswap.h (hunk 1 above)
Comment (enjiamai) [reply kernel/include/kswap.h]: Thank you for correcting this,  @andyross, got it fix~ ^^

**Review by nashif — APPROVED** [review]
