### PR TITLE
Test arch arm thread swap minor fix

### LINKED ISSUE #18999: assignment in assert in test of arm_thread_arch causes build failures
https://github.com/zephyrproject-rtos/zephyr/blob/6e46a64a489d5cce2b7621c5e5852fc3e1235a38/tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c#L468

is producing [build failures](https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/49969/summary/console) on two of five platforms in #18991:

```
rtos/zephyr/tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c: In function 'test_arm_thread_swap':
/home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c:468:2: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
  zassert_true(_current->arch.swap_return_value = SWAP_RETVAL,
  ^~~~~~~~~~~~
```

As far as I can tell the diagnostic is correct.

Am I wrong?  If not, how did this get past release testing?

### PR DESCRIPTION
**Pull request by ioannisg**
Fixes a bug in erroneous zassert expression in arm thread swap test suite

Fixes #18999

### CODE REVIEW

File: tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c [hunk 1]
```diff
@@ -431,6 +432,18 @@ void test_arm_thread_swap(void)
 		: "memory"
 	);
 
+	#if !defined(CONFIG_NO_OPTIMIZATIONS)
```
Comment (pabigot) [inline tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c]: Remove tabs before `#if`/`#endif`.

File: tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c [hunk 2]
```diff
@@ -431,6 +432,18 @@ void test_arm_thread_swap(void)
...
+	__asm__ volatile (
+		"mov r0, %1;\n\t"
+		"stm %0, {r0};\n\t"
+		:
+		: "r" (&ztest_swap_return_val), "r" (swap_return_val)
+		: "memory"
```
Comment (pabigot) [inline tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c]: I believe (verified assembly, tested sanitycheck and nucleo_l476rg`) that this can be reduced to:
```
	__asm__ volatile (
		"stm %0, {%1};\n\t"
		:
		: "r" (&ztest_swap_return_val), "r" (swap_return_val)
		: "memory"
	);
```
which avoids an unnecessary `mov r0, r0`.

**Review by pabigot — CHANGES_REQUESTED** [review]
Thanks for doing this.  Please fix the preprocessor whitespace issue.  I would go with the code change, but there may be subtleties I'm not seeing so that's just a suggestion.

File: tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c (hunk 1 above)
Comment (ioannisg) [reply tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c]: Sure. Fixed

File: tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c (hunk 2 above)
Comment (ioannisg) [reply tests/arch/arm/arm_thread_swap/src/arm_thread_arch.c]: Yeap, I agree with simplification. Fixed

**Review by ioannisg — COMMENTED** [review]
@pabigot thanks for your comments, I applied your feedback.
Let me know if this plays OK over #18991

**Review by pabigot — APPROVED** [review]

**Comment by pabigot** [comment]
The original version passed under #18991 so this should be good.  Thanks.
