### PR TITLE
net: lib: ptp: Fix `PTP_UDP_IPv6_PROTOCOL` compilation error

### LINKED ISSUE #92975: PTP does not compile with CONFIG_PTP_UDP_IPv6_PROTOCOL=y
### Describe the bug

When using UDPv6 for PTP, (setting CONFIG_PTP_UDP_IPv6_PROTOCOL=y) the mcast address of PTP is `s6_addr`.
However in [transport.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/ptp/transport.c#L198), the mcast address is still handled as ipv4 (`s_addr`). 

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. set  CONFIG_PTP_UDP_IPv6_PROTOCOL=y 
2. west build samples/net/ptp

### Relevant log output

```shell
zephyr/subsys/net/lib/ptp/transport.c:201:72: error: 'struct in6_addr' has no member named 's_addr'; did you mean 's6_addr'?
  201 |                         net_sin(&m_addr)->sin_addr.s_addr = mcast_addr.s_addr;
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Arch Linux
- Toolchain: Zephyr SDK + openocd

### Additional Context

Addtionally, when compiling a hotfixed version, my STM32F767ZI will hang during boot.
No shell or other output provided.

Am I missing a device tree entry/overlay for the example or something else? The [sample ptp entry](https://docs.zephyrproject.org/latest/samples/net/ptp/README.html#ptp) says it is supported board. 
However, I can not find any ptp_clock entry in the dtsi in comparison to other hardware like the nxp frdm_k64f.

I am still debugging the issue and can try to provide more debug output soon, but I thought maybe someone else has a solution for that already.

### PR DESCRIPTION
**Pull request by awojasinski**
When the `PTP_UDP_IPv6_PROTOCOL` configuration is enabled the `mcast_addr` variable is defined as an IPv6 structure, which doesn't have `s_addr` member.

To not introduce preprocessor guarded code blocks in functions added union to represent both configurations: IPv4 and IPv6.

Fixes: #92975

### CODE REVIEW

File: subsys/net/lib/ptp/transport.c [hunk 1]
```diff
@@ -15,11 +15,20 @@ LOG_MODULE_REGISTER(ptp_transport, CONFIG_PTP_LOG_LEVEL);
 
 #define INTERFACE_NAME_LEN (32)
 
+typedef union {
```
Comment (jukkar) [inline subsys/net/lib/ptp/transport.c]: We have been trying hard (at least in networking side) to use typedef only for function pointers. With this in mind, we could just say here `union mcast_addr { ... };` like what we do for structs.

File: subsys/net/lib/ptp/transport.c [hunk 2]
```diff
@@ -15,11 +15,20 @@ LOG_MODULE_REGISTER(ptp_transport, CONFIG_PTP_LOG_LEVEL);
...
+	struct in_addr ipv4;
+	struct in6_addr ipv6;
+} mcast_addr_t;
+
 #if CONFIG_PTP_UDP_IPv4_PROTOCOL
-static struct in_addr mcast_addr = {{{224, 0, 1, 129}}};
+static mcast_addr_t mcast_addr = {
+	.ipv4 = {{{224, 0, 1, 129}}}
```
Comment (jukkar) [inline subsys/net/lib/ptp/transport.c]: We are wasting memory if IPv6 is not enabled. You could use `COND_CODE_1()` in the union to only enable `ipv6` field if IPv6 is enabled, and then have `depends on NET_IPV6` for `CONFIG_PTP_UDP_IPv6_PROTOCOL`

File: subsys/net/lib/ptp/transport.c (hunk 1 above)
Comment (awojasinski) [reply subsys/net/lib/ptp/transport.c]: thanks for advice! I'll push the change

File: subsys/net/lib/ptp/transport.c (hunk 2 above)
Comment (awojasinski) [reply subsys/net/lib/ptp/transport.c]: done

**Review by jukkar — COMMENTED** [review]
Did you run the latest version through clang-format or similar as the code just looks much worse now?

**Comment by awojasinski** [comment]
@jukkar Yes I run it through clang-format. Do you think it's better to stay with the previous code format?

**Comment by jukkar** [comment]
> Do you think it's better to stay with the previous code format?

Yes, I would recommend not to use clang-format in patches. It just introduces bad looking changes without much benefit.

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
