### PR TITLE
Bluetooth: Host: Settings: Handle extra settings_load before bt_enable

### LINKED ISSUE #39317: `BT_SETTINGS=y` without `bt_enable()` causes MPU fault
**Describe the bug**

Enabling the Settings subsystem  for use with a project using a SD card mounted with a FAT file system works as intended. However, when the Bluetooth subsystem is also enabled, then a MPU Fault is caused in most cases the as `settings_load()` is called. Or some other failure. related to the file system.

**To Reproduce**

I've modified the [samples/syubsys/settings](https://github.com/NZSmartie/zephyr/tree/samples/settings-fs-backed) sample to include support for SD card backed settings to make it easier to reproduce this problem.

1. `git clone https://github.com/NZSmartie/zephyr -b samples/settings-fs-backed`
2. Modify `samples/subsys/settings/boards/nrf52840_blip.conf` and add:

   ```property
   # Enable Bluetooth subsys
   CONFIG_BT=y
   CONFIG_BT_SETTINGS=y
   ```

3. `west build -b nrf52840_blip`
4. `west flash`
5. See error

**Expected behavior**
The settings sample project using the FAT FS backend and with the Bluetooth subsys enabled (`CONFIG_BT=y`) to run to completion.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
*** Booting Zephyr OS build v2.7.99-420-g9c4366f1ae33  ***

*** Settings usage example ***

disk mount: OK.
settings subsys initialization: OK.
subtree <alpha> handler registered: OK
subtree <alpha/beta> has static handler

##############
# iteration 0
##############

=================================================
basic load and save using registered handlers

load all key-value pairs using registered handlers
<alpha/beta/voltage> = -3450
<alpha/beta/source> =
<alpha/angle/1> = 18
<alpha/length/1> = 58
<alpha/length/2> = 42
loading all settings under <beta> handler is done
ASSERTION FAIL [err == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:306
        k_sem_take failed with err -11
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 x64
 - Toolchain: zephyr SDK 0.13.1
 - g9c4366f1ae

**Additional context**

### PR DESCRIPTION
**Pull request by alwa-nordic**
Before this change, enabling CONFIG_BT_SETTINGS and calling
settings_load(), but delaying / not calling bt_enable would trigger an
assertion error due to a timeout. The fault is that the settings load
handler for the Bluetooth host assumes bt_enable has already been called
and sends HCI commands to the controller. This times out if HCI is not
running.

The fix is to skip loading Bluetooth settings before bt_enable. The doc
is updated to guide the user on how to enable Bluetooth after settings
have been loaded before.

Fixes #39317.

Signed-off-by: Aleksander Wasaznik <aleksander.wasaznik@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/settings.c [hunk 1]
```diff
@@ -119,6 +119,14 @@ static int set(const char *name, size_t len_rd, settings_read_cb read_cb,
 	ssize_t len;
 	const char *next;
 
+	if (!atomic_test_and_set_bit(bt_dev.flags, BT_DEV_ENABLE)) {
```
Comment (jhedberg) [inline subsys/bluetooth/host/settings.c:122]: Should be `atomic_test_bit()` not `test_and_set()`

File: subsys/bluetooth/host/settings.c [hunk 2]
```diff
@@ -233,7 +241,13 @@ static int commit(void)
 {
 	int err;
 
-	BT_DBG("");
+	if (!atomic_test_and_set_bit(bt_dev.flags, BT_DEV_ENABLE)) {
```
Comment (jhedberg) [inline subsys/bluetooth/host/settings.c:244]: Same here. Or is there something I'm missing, why you want to set the ENABLE bit here?

**Review by jhedberg — CHANGES_REQUESTED** [review]

**Comment by jhedberg** [comment]
Btw, an alternative solution would be to use `settings_register()` instead of `SETTINGS_STATIC_HANDLER_DEFINE()`. That way these callbacks would only get registered when `bt_enable()` is called.

File: subsys/bluetooth/host/settings.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/settings.c:122]: Of course! Thank you.

**Comment by jhedberg** [comment]
@alwa-nordic any comment regarding my idea regarding runtime registration of the handlers? There might be some minor RAM penalty, but otherwise it sounds like the cleaner approach. We should also check if it's really necessary to initialize the settings subsystem like we do - I have a feeling it was a mistake to leave that in, but it might be too late now since it would break applications which don't do it themselves.

**Comment by alwa-nordic** [comment]
> Any comment regarding my idea regarding runtime registration of the handlers? There might be some minor RAM penalty, but otherwise it sounds like the cleaner approach.

I don't have a preference here. The solution is a bit more explicit like it is now. It's clear to readers of the code. I like that. A runtime registration may look a bit more like an arbitrary decision. Not sure, though.

> We should also check if it's really necessary to initialize the settings subsystem like we do - I have a feeling it was a mistake to leave that in, but it might be too late now since it would break applications which don't do it themselves.

You mean that `settings_subsys_init` is called as part of `bt_enable`? I agree. It feels like it should not be the responsibility of the Bluetooth subsystem. I think it's reasonable to transition if we start with a deprecation warning for a while if we decide to go for it.

**Comment by Laczen** [comment]
@jhedberg, @alwa-nordic finally the `settings_subsys_init()` will be removed from bt, it should never have been there. The placement inside bt instead of inside the application has made the more advance usage of settings impossible for years.

File: subsys/bluetooth/host/settings.c [hunk 3]
```diff
@@ -119,6 +119,14 @@ static int set(const char *name, size_t len_rd, settings_read_cb read_cb,
 	ssize_t len;
 	const char *next;
 
+	if (!atomic_test_bit(bt_dev.flags, BT_DEV_ENABLE)) {
```
Comment (MarekPieta) [inline subsys/bluetooth/host/settings.c:122]: Does the Bluetooth's settings `set` handler actually require that Bluetooth is enabled before? I think not, but maybe I missed something here (please correct me if I am wrong).
If it's not required then we may handle settings set and then just delay calling commit to ensure that it's called after bt_enable. That approach would be simpler - no matter when user calls settings_load, the Bluetooth settings will eventually be handled properly.

Comment (alwa-nordic) [reply subsys/bluetooth/host/settings.c:122]: > Does the Bluetooth's settings set handler actually require that Bluetooth is enabled before? I think not, but maybe I missed something here (please correct me if I am wrong).

Not currently. But I was worried a future change may assume that `bt_enable` has been called. And we may as well skip handling the `set` events if we are not going to handle the `commit`.

> If it's not required then we may handle settings set and then just delay calling commit to ensure that it's called after bt_enable. That approach would be simpler - no matter when user calls settings_load, the Bluetooth settings will eventually be handled properly.

Do you mean that `commit` should set a flag for `bt_enable` to continue the "commit"? Sounds reasonable.

Comment (Laczen) [reply subsys/bluetooth/host/settings.c:122]: > > Does the Bluetooth's settings set handler actually require that Bluetooth is enabled before? I think not, but maybe I missed something here (please correct me if I am wrong).
> 
> Not currently. But I was worried a future change may assume that `bt_enable` has been called. And we may as well skip handling the `set` events if we are not going to handle the `commit`.

IMO it is a good idea to check for the `bt_enable` flag, some things might not be set-up to process the settings entries that are stored. If anything calls the `set` method when `bt` is not enabled it should return without causing problems.

The same holds for the commit.

**Comment by jhedberg** [comment]
> I don't have a preference here. The solution is a bit more explicit like it is now. It's clear to readers of the code. I like that. A runtime registration may look a bit more like an arbitrary decision. Not sure, though.

@alwa-nordic at least to me having to check for the flag feels like a hack/workaround for the Bluetooth subsystem going and registering settings callbacks before it's ready to do anything with them. So in that sense registering the callbacks only when we are ready to use them feels cleaner. That said, if we ever introduce a `bt_disable()` API which undoes some of the settings-critical stuff that `bt_enable()` does, then the callbacks would need the checks (assuming the settings subsystem doesn't itself introduce an `unregister()` API for handlers).

File: include/bluetooth/bluetooth.h [hunk 4]
```diff
@@ -130,10 +130,12 @@ typedef void (*bt_ready_cb_t)(int err);
  * Enable Bluetooth. Must be the called before any calls that
  * require communication with the local Bluetooth hardware.
  *
- * When @kconfig{CONFIG_BT_SETTINGS} has been enabled and the application is not
- * managing identities of the stack itself then the application must call
- * @ref settings_load() before the stack is fully enabled.
- * See @ref bt_id_create() for more information.
+ * When @kconfig{CONFIG_BT_SETTINGS} is enabled, the application must load the
+ * bluetooth settings at some point after bluetooth is enabled, before using
```
Comment (Thalley) [inline include/bluetooth/bluetooth.h:134]:
```suggestion
 * bluetooth settings at some point after bluetooth is enabled by calling bt_enable(), before using
```

File: subsys/bluetooth/host/settings.c [hunk 5]
```diff
@@ -119,6 +119,14 @@ static int set(const char *name, size_t len_rd, settings_read_cb read_cb,
...
+		/* Cannot load settings before bt_enable() because this handler uses bt
+		 * functions. The application shall call settings_load_subtree("bt")
+		 * after bt_enable().
+		 */
+		return 0;
```
Comment (Thalley) [inline subsys/bluetooth/host/settings.c:127]: I don't think returning 0 in case that setting were not loaded is very good. Perhaps `-ECANCELED`?

File: subsys/bluetooth/host/settings.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/host/settings.c:122]: @MarekPieta 

@alwa-nordic writes in his commit message that loading settings send HCI commands to the controller. When calling `bt_enable()` we send the `HCI Reset` opcode to controller, so even if it didn't crash, `bt_enable` would erase any data previously sent to the controller.

File: subsys/bluetooth/host/settings.c [hunk 6]
```diff
@@ -233,7 +241,13 @@ static int commit(void)
 {
 	int err;
 
-	BT_DBG("");
+	if (!atomic_test_bit(bt_dev.flags, BT_DEV_ENABLE)) {
+		/* Cannot load settings before bt_enable() because this handler uses bt
+		 * functions. The application shall call settings_load_subtree("bt")
+		 * after bt_enable().
+		 */
+		return 0;
```
Comment (Thalley) [inline subsys/bluetooth/host/settings.c:249]: Ditto regarding the return code

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/settings.c (hunk 3 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/settings.c:122]: > > Does the Bluetooth's settings set handler actually require that Bluetooth is enabled before? I think not, but maybe I missed something here (please correct me if I am wrong).
> 
> Not currently. But I was worried a future change may assume that `bt_enable` has been called. And we may as well skip handling the `set` events if we are not going to handle the `commit`.
> 
> > If it's not required then we may handle settings set and then just delay calling commit to ensure that it's called after bt_enable. That approach would be simpler - no matter when user calls settings_load, the Bluetooth settings will eventually be handled properly.
> 
> Do you mean that `commit` should set a flag for `bt_enable` to continue the "commit"? Sounds reasonable.

I think it may be a good approach (it may be simpler from user's perspective and less error prone if user does not need to explicitly handle the special case where settings are loaded before Bluetooth is enabled).

Comment (MarekPieta) [reply subsys/bluetooth/host/settings.c:122]: > @MarekPieta
> 
> @alwa-nordic writes in his commit message that loading settings send HCI commands to the controller. When calling `bt_enable()` we send the `HCI Reset` opcode to controller, so even if it didn't crash, `bt_enable` would erase any data previously sent to the controller.

Settings commit callbacks sends the HCI commands. Settings set callback does not do it currently, but as mentioned by @alwa-nordic it could do it at some point in the future.

Comment (Thalley) [reply subsys/bluetooth/host/settings.c:122]: > Settings commit callback sends the HCI commands. Settings set callback does not do it currently, but as mentioned by @alwa-nordic it could do it at some point in the future. If it's the case then I understand that solution proposed by me may be rejected. Still I think that, if it's possible, we should ensure that Bluetooth settings would be automatically loaded at some point after settings_load is called globally to make solution less error prone.

Would it make sense to conditionally automatically load settings in `bt_enable`? Either via a Kconfig option, or a new argument to the function?

File: subsys/bluetooth/host/settings.c (hunk 5 above)
Comment (Laczen) [reply subsys/bluetooth/host/settings.c:127]: As this is no error situation but intended behavior it should not return an error.

File: subsys/bluetooth/host/settings.c (hunk 6 above)
Comment (Laczen) [reply subsys/bluetooth/host/settings.c:249]: As this is no error situation but intended behavior the return code should be 0.

File: subsys/bluetooth/host/settings.c (hunk 3 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/settings.c:122]: @Thalley, from CONFIG_BT_SETTINGS ducumentation:
```
When this option has been enabled, it's important that the
application makes a call to settings_load() after having done
all necessary initialization (e.g. calling bt_enable). The
reason settings_load() is handled externally to the stack, is
that there may be other subsystems using the settings API, in
which case it's more efficient to load all settings in one go,
instead of each subsystem doing it independently.
```
In general, Zephyr used to assume that we load all of the settings globally, assuming that modules are prepared for this (this was done for efficiency). Automatically loading settings in bt_enable would contradict a bit with this assumption (it would be a "special case"). That's why I was thinking about remembering values during set callback and then only ensuring that commit is called after the bt_enable to prevent errors.

File: subsys/bluetooth/host/settings.c (hunk 5 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/settings.c:127]: If we want to stick with the current approach I would at least add an warning log to ensure that user is actually aware that his Bluetooth settings were not loaded even though he called globally settings_load.

Comment (Laczen) [reply subsys/bluetooth/host/settings.c:127]: Adding a warning or debug message inside the `bt` settingshandler routines is fine.

Delegating this to the `settings` system is bad: log messages wil only be seen if the logsystem is enabled for `settings` (and not `bt`), the `settings` system cannot return this to the user because it might have received different error messages from different subsystems.

**Comment by jhedberg** [comment]
Turns out the dynamic settings handler registration is disabled by default in Kconfig. Due to this, and the fact that we're introducing a `bt_disable()` I think having the flag check in the handlers is the best solution.

**Comment by Laczen** [comment]
> Turns out the dynamic settings handler registration is disabled by default in Kconfig. Due to this, and the fact that we're introducing a `bt_disable()` I think having the flag check in the handlers is the best solution.

It is also possible to create a local `bt_settings_handler` structure that would map the settings routines to either NULL or the present routines. `bt_enable()` could then update this structure with the present routines, `bt_disable()` would reset them to NULL. Thas way you wouldn't need to check for the flag.

**Comment by Laczen** [comment]
@alwa-nordic, inside the bluetooth subsystem there seem to be a lot of `SETTINGS_STATIC_HANDLER()` definitions, each of them might also require the `bt` subsystem to be enabled.

File: subsys/bluetooth/host/settings.c (hunk 3 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/settings.c:122]: I would like to keep the current approach in this PR as the bug fix. It is compatible with the API doc. We can open an enhancement discussion on improving the API.

File: include/bluetooth/bluetooth.h [hunk 7]
```diff
@@ -130,10 +130,13 @@ typedef void (*bt_ready_cb_t)(int err);
...
- * When @kconfig{CONFIG_BT_SETTINGS} has been enabled and the application is not
- * managing identities of the stack itself then the application must call
- * @ref settings_load() before the stack is fully enabled.
- * See @ref bt_id_create() for more information.
+ * When @kconfig{CONFIG_BT_SETTINGS} is enabled, the application must load the
+ * Bluetooth settings after this API call successfully completes before
+ * Bluetooth APIs can be used. Loading the settings before calling this function
+ * is insufficient. Bluetooth settings can be loaded with @ref settings_load()
+ * or @ref settings_load_subtree("bt"). The latter selectivy loads only
+ * Bluetooth settings and is reccomended if @ref settings_load() has been called
```
Comment (Thalley) [inline include/bluetooth/bluetooth.h:138]: IIRC, doxygen will autmatically create ref`s when you add parenthesis, and thus this could be
```suggestion
 * is insufficient. Bluetooth settings can be loaded with settings_load()
 * or settings_load_subtree("bt"). The latter selectively loads only
 * Bluetooth settings and is recommended if settings_load() has been called
```

**Review by Thalley — CHANGES_REQUESTED** [review]
A few typos. 

Not sure how I feel about the multiple identical (fairly long) comments. Gives a feeling that something is distributed when perhaps it should have been central in some way.

**Review by Thalley — DISMISSED** [review]

**Comment by alwa-nordic** [comment]
> Not sure how I feel about the multiple identical (fairly long) comments. Gives a feeling that something is distributed when perhaps it should have been central in some way.

@carlescufi, @cvinayak, and I discussed whether to consolidate all loading of Bluetooth settings into one place yesterday. We concluded that we wanted to just quick-fix this for now.

Anyway, I'm not too bothered by the duplication. It's not intrinsically bad to have the same code in several places. In principle, these handlers have the Bluetooth-enabled-condition independently from each other. I can imagine that we may want to remove this condition from some of the handlers but not all. (Each set and commit are tied, though. It would be nice to somehow put their checks in one place.)

**Comment by carlescufi** [comment]
@wopu-ot a review would be appreciated

**Comment by Laczen** [comment]
@alwa-nordic, I can't comment if it is appropiate to duplicate the check in so many places. I will remove my request for review (this doesn't mean that the fix is bad).

IMO we should show the users how to use the settings system:
a. The application initialises the backend,
b. Each subsystem can call `settings_load_subtree()` for its own settings after initialisation (if it is required for a subsequent subsystem to have some settings loaded already),
c. After all subsystems have been initialized, the application calls `settings_load()`.

To avoid the present problem with other subsystem in future we could deprecate `settings_load()` and replace it with `settings_load_all()` to make it clearer. At the same time we could also rename `settings_load_subtree()` with `settings_load_sub()`.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
BTW, ^^ good point on missing in settings guide.

**Comment by jhedberg** [comment]
@alwa-nordic please fix the build failure
```
zephyr/subsys/bluetooth/mesh/CMakeFiles/subsys__bluetooth__mesh.dir/settings.c.obj.d -o zephyr/subsys/bluetooth/mesh/CMakeFiles/subsys__bluetooth__mesh.dir/settings.c.obj -c /__w/zephyr/zephyr/subsys/bluetooth/mesh/settings.c
[154](https://github.com/zephyrproject-rtos/zephyr/runs/5217093609?check_suite_focus=true#step:6:154)
/__w/zephyr/zephyr/subsys/bluetooth/mesh/settings.c:18:10: fatal error: hci_core.h: No such file or directory
[155](https://github.com/zephyrproject-rtos/zephyr/runs/5217093609?check_suite_focus=true#step:6:155)
   18 | #include "hci_core.h"
[156](https://github.com/zephyrproject-rtos/zephyr/runs/5217093609?check_suite_focus=true#step:6:156)
      |          ^~~~~~~~~~~~
```

**Review by jhedberg — APPROVED** [review]

File: include/bluetooth/bluetooth.h [hunk 8]
```diff
@@ -130,10 +130,13 @@ typedef void (*bt_ready_cb_t)(int err);
...
  * require communication with the local Bluetooth hardware.
  *
- * When @kconfig{CONFIG_BT_SETTINGS} has been enabled and the application is not
- * managing identities of the stack itself then the application must call
- * @ref settings_load() before the stack is fully enabled.
- * See @ref bt_id_create() for more information.
+ * When @kconfig{CONFIG_BT_SETTINGS} is enabled, the application must load the
+ * Bluetooth settings after this API call successfully completes before
+ * Bluetooth APIs can be used. Loading the settings before calling this function
+ * is insufficient. Bluetooth settings can be loaded with settings_load() or
```
Comment (MarekPieta) [inline include/bluetooth/bluetooth.h:136]: Maybe we could even explicitly state that Bluetooth settings will be skipped if settings_load() is called before Bluetooth is enabled.

**Review by MarekPieta — APPROVED** [review]
