### PR TITLE
Bluetooth: controller: LLCP: Add separate pool for remote procedure contexts

### LINKED ISSUE #41823: Bluetooth: Controller: llcp: Remote request are dropped due to lack of free proc_ctx
**Describe the bug**
The issues is related with refactored LLCPs implementation.

Two devices are in a connected state and start to exchange messages.
First device host starts `CONFIG_BT_CTLR_LLCP_PROC_CTX_BUF_NUM` number of control procedures by HCI commands.
Second device starts at leas one remote control procedure.

First device receives remote request and acknowledges it (default behavior of Controller).
New procedure is handled by upper link layer but due to lack of free `proc_ctx` the command is dropped without and error or notification.

**To Reproduce**
Use peripheral and central samples. Modify them to run multiple LLCPs on one end and at leas one LLCP on other end just after connection is established.

**Expected behavior**
Remote control procedure should be handled accordingly or not acknowledged.

**Impact**
Easy to reproduce with `CONFIG_BT_CTLR_LLCP_PROC_CTX_BUF_NUM` to default value.
Can cause strange and not expected behavior due to lack of notification about procedure drop.

### PR DESCRIPTION
**Pull request by thoh-ot**
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/41823

### CODE REVIEW

File: subsys/bluetooth/controller/Kconfig.ll_sw_split [hunk 1]
```diff
@@ -532,16 +532,26 @@ config BT_CTLR_LLCP_COMMON_TX_CTRL_BUF_NUM
 	  procedures/connections with allocation through a fifo queue.
 	  Configure between 0 and (4 - BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM) * BT_CTLR_LLCP_CONN
 
-config BT_CTLR_LLCP_PROC_CTX_BUF_NUM
-	int "Number of control procedure contexts to be available across all connections"
+config BT_CTLR_LLCP_LOCAL_PROC_CTX_BUF_NUM
```
Comment (kruithofa) [inline subsys/bluetooth/controller/Kconfig.ll_sw_split:535]: IIRC the reason for having the minimum number of contexts 2 so that we have at least 1 for local and 1 for remote procedures. Since we now have a separate pool for remote procedures the minimum can be set to 1 I think.
Sidenote: the way the unittests are written today they require a minimum of 4 local contexts available

File: subsys/bluetooth/controller/ll_sw/ull_llcp_internal.h [hunk 2]
```diff
@@ -4,6 +4,12 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
+/* LLCP Memory Pool Descriptor */
+struct mem_pool {
```
Comment (kruithofa) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_internal.h:8]:
```suggestion
struct llcp_mem_pool {
```

**Review by kruithofa — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 3]
```diff
@@ -59,8 +59,13 @@ static uint8_t buffer_mem_tx[TX_CTRL_BUF_SIZE * LLCP_TX_CTRL_BUF_COUNT];
 static struct mem_pool mem_tx = { .pool = buffer_mem_tx };
 
 /* TODO: Determine 'correct' number of ctx */
-static uint8_t buffer_mem_ctx[PROC_CTX_BUF_SIZE * CONFIG_BT_CTLR_LLCP_PROC_CTX_BUF_NUM];
-static struct mem_pool mem_ctx = { .pool = buffer_mem_ctx };
+static uint8_t buffer_mem_local_ctx[PROC_CTX_BUF_SIZE * CONFIG_BT_CTLR_LLCP_PROC_CTX_BUF_NUM];
+static struct mem_pool mem_local_ctx = { .pool = buffer_mem_local_ctx };
+
+/* TODO(thoh-ot): Determine 'correct' number of ctx */
```
Comment (erbr-ot) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c:65]: TODO is not needed?

**Review by erbr-ot — COMMENTED** [review]
Looks good to me. 
One additional comment - re number of local CTXs - don't we actually need 2 per conn, to ensure termination is available? Until we have static alloc of termination proc?

**Comment by thoh-ot** [comment]
> Looks good to me. One additional comment - re number of local CTXs - don't we actually need 2 per conn, to ensure termination is available? Until we have static alloc of termination proc?

Local termination calls `llcp_lr_abort` which should flush all the pending local ctx thereby freeing one for termination.

**Comment by sjanc** [comment]
> > Looks good to me. One additional comment - re number of local CTXs - don't we actually need 2 per conn, to ensure termination is available? Until we have static alloc of termination proc?
> 
> Local termination calls `llcp_lr_abort` which should flush all the pending local ctx thereby freeing one for termination.

does this mean this will never happen for ull_cp_terminate() ?
        ctx = llcp_create_local_procedure(PROC_TERMINATE);
        if (!ctx) {
                return BT_HCI_ERR_CMD_DISALLOWED;
        }

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 4]
```diff
@@ -71,17 +65,26 @@ static struct mem_pool mem_ctx = { .pool = buffer_mem_ctx };
 /*
  * LLCP Resource Management
  */
-static struct proc_ctx *proc_ctx_acquire(void)
+static struct proc_ctx *proc_ctx_acquire(struct mem_pool *owner)
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c:73]: Nit-pick: In my humble opinion `owner` could be more general eg `ctx_pool`. That makes the function meaning to be more general. `ctx->owner` points to a source `mem_pool` where the acquired `ctx` should be released.

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 5]
```diff
@@ -71,17 +65,26 @@ static struct mem_pool mem_ctx = { .pool = buffer_mem_ctx };
...
+		ctx->owner = owner;
+	}
+
 	return ctx;
 }
 
 void llcp_proc_ctx_release(struct proc_ctx *ctx)
 {
-	mem_release(ctx, &mem_ctx.free);
+	if (ctx->owner) {
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c:89]: What if there is no owner? That should not happen but if it happens then released context is lost.

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 6]
```diff
@@ -249,11 +252,11 @@ void llcp_tx_flush(struct ll_conn *conn)
  * LLCP Procedure Creation
  */
 
-static struct proc_ctx *create_procedure(enum llcp_proc proc)
+static struct proc_ctx *create_procedure(enum llcp_proc proc, struct mem_pool *owner)
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c:260]: Referring to my comment from above, I would not name the `mem_pool` as `owner`. In this context it is a memory pool. 
Look at line below `ctx = proc_ctx_acquire(owner);`. Would it be easier to understand if that is `ctx = proc_ctx_acquire(ctx_pool)`?

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 7]
```diff
@@ -278,7 +281,7 @@ struct proc_ctx *llcp_create_local_procedure(enum llcp_proc proc)
 {
 	struct proc_ctx *ctx;
 
-	ctx = create_procedure(proc);
+	ctx = create_procedure(proc, &mem_ctx);
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]: General question, not related with this PR itself.
I think that there should be some naming convention for globals to make them easier to distinguish from local variables and function arguments. What do you think?

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 8]
```diff
@@ -1021,11 +1029,21 @@ void ull_cp_rx(struct ll_conn *conn, struct node_rx_pdu *rx)
...
+{
+	return mem_free_count_get(mem_remote_ctx.free);
+}
+
+uint16_t ctx_buffers_free(void)
+{
+	uint16_t nr_of_free_ctx;
 
-	nr_of_free_ctx = mem_free_count_get(mem_ctx.free);
+	nr_of_free_ctx = local_ctx_buffers_free() + remote_ctx_buffers_free();
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c:1047]: Can't the sum be returned directly?

**Review by ppryga-nordic — CHANGES_REQUESTED** [review]
In general the functionality is ok. 
I've added some minor comments related with naming.

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 1 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:535]: As discussed in meeting we keep the default value as was

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 8 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c:1047]: As in
```suggestion
             return local_ctx_buffers_free() + remote_ctx_buffers_free();
```

**Comment by thoh-ot** [comment]
> > > Looks good to me. One additional comment - re number of local CTXs - don't we actually need 2 per conn, to ensure termination is available? Until we have static alloc of termination proc?
> > 
> > 
> > Local termination calls `llcp_lr_abort` which should flush all the pending local ctx thereby freeing one for termination.
> 
> does this mean this will never happen for ull_cp_terminate() ? ctx = llcp_create_local_procedure(PROC_TERMINATE); if (!ctx) { return BT_HCI_ERR_CMD_DISALLOWED; }

As discussed on the last meeting, I will change this into an assert. But i have decided to so in a separate PR.

**Review by kruithofa — DISMISSED** [review]

**Comment by kruithofa** [comment]
Fixes #41823

**Comment by thoh-ot** [comment]
Need to rebase and fix issues

**Review by kruithofa — APPROVED** [review]

**Comment by thoh-ot** [comment]
@ppryga is you'r change request still valid?

**Review by ppryga-nordic — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
quick ack.
