### PR TITLE
drivers/spi: stm32: Fix use of single dma channel

### LINKED ISSUE #25284: spi: stm32: dma_client: Cannot use RX only configuration
**Describe the bug**
STM32 SPI DMA client can work with TX and RX, or TX/RX only configuration.
Configuration should be done using device tree:
```
&spi1 {
	dmas = <&dmamux1 11 7 0x20440 0
		&dmamux1 1 6 0x20480 0>;
	dma-names = "tx", "rx";
};
```
Tx only configuration
```
&spi1 {
	dmas = <&dmamux1 11 7 0x20440 0>;
	dma-names = "tx";
};
```
Both configs above work fine, but SPI driver does not compile in RX only configuration.

**To Reproduce**
Build `tests/drivers/spi/spi_loopback/` and tweak `boards/nucleo_wb55rg.overlay`

**Expected behavior**
SPI DMA client can build in all single channel config

### PR DESCRIPTION
**Pull request by erwango**
Current dma struture code didn't allowed only rx channel removal,
disabling tx channel (in spi client node) was leading compilation
issue.
Fix this by moving conditional code inside SPI_DMA_CHANNEL macro and
get the part of code which is present or removed (SPI_DMA_CHANNEL_INIT)
outside of {}.

Fixes #25284

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -861,19 +860,26 @@ static void spi_stm32_irq_config_func_##id(struct device *dev)		\
...
+				DMA_CHANNEL_CONFIG(index, dir)),	\
 	.dst_addr_increment = STM32_DMA_CONFIG_##dest_dev##_ADDR_INC(	\
-				DMA_CHANNEL_CONFIG(index, dir)),\
+				DMA_CHANNEL_CONFIG(index, dir)),	\
 	.transfer_complete = false,					\
 	.fifo_threshold = STM32_DMA_FEATURES_FIFO_THRESHOLD(		\
-					DMA_FEATURES(index, dir))	\
-}
+					DMA_FEATURES(index, dir)),	\
+
```
Comment (FRASTM) [inline drivers/spi/spi_ll_stm32.c:869]: missing '}' ?

Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:869]: The brackets are now in `SPI_DMA_CHANNEL` macro.
I haven't found other way to achieve what I wanted to do.

**Review by FRASTM — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
