### PR TITLE
Bluetooth: HCI: Add option CONFIG_BUF_ACL_DATA_LEN

### LINKED ISSUE #30441: hci_uart uses wrong BT_BUF_ACL_SIZE on dual chip solutions + multicore
**Describe the bug**
hci_raw.h has a dependency on CONFIG_BT_CTLR_TX_BUFFER_SIZE

This option can not be set for dual chip solutions for multicores platorms like nrf5340pdk_nrf5340_cpuapp, leading to a max hci data payload of 69 bytes.

**To Reproduce**
west build -p auto -b nrf5340pdk_nrf5340_cpuapp -dapp samples/bluetooth/hci_uart
west build -p auto -b nrf5340pdk_nrf5340_cpunet -dnet samples/bluetooth/hci_rpmsg

Use HCI_LE_Set_Data_Length to establish a connection and update the data length (251 octets, 2120us)
HCI data packets with data length > 69 bytes are now dropped because they do not fit in the buffer between the application core and the network core. 

**Expected behavior**
It should be possible to send the maximum LL payload between the cores (251 bytes)

**Impact**
Many bluetooth conformance tests are failing due to this.

**Environment (please complete the following information):**
 - Linux
 - Zephyr SDK

### PR DESCRIPTION
**Pull request by jostn**
Add the option CONFIG_BT_BUF_ACL_DATA_LEN which allows the user
to configure the max HCI ACL payload. This is needed for platorms
where the BLE LL, HCI uart and host run on three different cores.

Fixes: #30441

Signed-off-by: Johan Stridkvist <johan.stridkvist@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/Kconfig [hunk 1]
```diff
@@ -47,6 +47,13 @@ config BT_RX_BUF_LEN
 	  an L2CAP MTU of 65 bytes. On top of this there's the L2CAP header
 	  (4 bytes) and the ACL header (also 4 bytes) which yields 73 bytes.
 
+config BT_BUF_ACL_DATA_LEN
+    int
+	range 27 251
+	default 65
+	depends on BT_HCI_RAW
+	prompt "Override the maximum ACL data payload." if BT_HCI_RAW
```
Comment (jhedberg) [inline subsys/bluetooth/host/Kconfig:55]: Please use the same consistent indentation style as the other option use. Here you have everything after `int` using a different indentation.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Looks generally fine. One inline comment and then you also have a typo in the commit summary (`_BT` is missing)

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/Kconfig [hunk 2]
```diff
@@ -47,6 +47,13 @@ config BT_RX_BUF_LEN
 	  an L2CAP MTU of 65 bytes. On top of this there's the L2CAP header
 	  (4 bytes) and the ACL header (also 4 bytes) which yields 73 bytes.
 
+config BT_BUF_ACL_DATA_LEN
+	int
+	range 27 251
+	default 65
+	depends on BT_HCI_RAW
+	prompt "Override the maximum ACL data payload." if BT_HCI_RAW
```
Comment (joerchan) [inline subsys/bluetooth/host/Kconfig:55]: I don't think the if BT_HCI_RAW is needed here when you have depends on BT_HCI_RAW.

File: include/bluetooth/hci_raw.h [hunk 3]
```diff
@@ -28,7 +28,12 @@ extern "C" {
 #endif /* CONFIG_BT_CTLR */
 
 /** Data size needed for ACL buffers */
+#if defined(CONFIG_BT_BUF_ACL_DATA_LEN)
+#define BT_BUF_ACL_SIZE MAX(BT_L2CAP_BUF_SIZE(BT_L2CAP_MTU), \
+	(CONFIG_BT_BUF_ACL_DATA_LEN + BT_HCI_ACL_HDR_SIZE + BT_BUF_RESERVE))
+#else
 #define BT_BUF_ACL_SIZE BT_L2CAP_BUF_SIZE(BT_L2CAP_MTU)
```
Comment (joerchan) [inline include/bluetooth/hci_raw.h:35]: Just curious, when would this apply? You include hci_raw.h but don't enable BT_HCI_RAW. Could we reduce the amount of possibilities for the BT_BUF_ACL_SIZE and end up with less surprises?

Comment (joerchan) [reply include/bluetooth/hci_raw.h:35]: Maybe we could eliminate the define above? The ACL shouldn't have to depend on the L2CAP MTU, because that should be fragmented across the LL PDUs. The ACL should be aligned with the LL PDU size like it is when CONFIG_BT_CTLR_TX_BUFFER_SIZE is defined.

It would be good if we could make the buffer size configurations simpler because we end up with many of these situations where depending on the board selected we get different buffer sizes.

**Comment by joerchan** [comment]
@jostn Could you have a look at my questions, so that we can proceed?

File: include/bluetooth/hci_raw.h (hunk 3 above)
Comment (jostn) [reply include/bluetooth/hci_raw.h]: > @jostn Could you have a look at my questions, so that we can proceed?



> @jostn Could you have a look at my questions, so that we can proceed?

I've reworked the PR so that we do not depend on l2cap any longer.

**Review by jhedberg — APPROVED** [review]

File: include/bluetooth/hci_raw.h [hunk 4]
```diff
@@ -21,23 +21,23 @@
...
+#define _BT_ACL_BUF_SIZE(len) (BT_BUF_RESERVE + \
+				BT_HCI_ACL_HDR_SIZE + \
+				(len))
 
 /** Data size needed for ACL buffers */
-#define BT_BUF_ACL_SIZE BT_L2CAP_BUF_SIZE(BT_L2CAP_MTU)
+#ifdef CONFIG_BT_HCI_ACL_DATA_SIZE
+#define BT_BUF_ACL_SIZE _BT_ACL_BUF_SIZE(CONFIG_BT_HCI_ACL_DATA_SIZE)
+#else
+#define BT_BUF_ACL_SIZE _BT_ACL_BUF_SIZE(27)
```
Comment (joerchan) [inline include/bluetooth/hci_raw.h:32]: CONFIG_BT_HCI_ACL_DATA_SIZE should always be defined, since it only depends on CONFIG_BT_HCI_RAW, and it has the same default value of 27.
Removing this else would mean that the value always comes from Kconfig, which would be cleaner.

**Review by joerchan — APPROVED** [review]
