### PR TITLE
Bluetooth: BAP: Update encrypt_state when BIG synced after bad code

### LINKED ISSUE #88461: Scan delegator keeps reporting bad code to broadcast assistant after BIG is synchronized
**Describe the bug**
When using a co-located broadcast scan delegator and broadcast sink
and the receive state encrypt state is BT_BAP_BIG_ENC_STATE_BAD_CODE,
even after bt_bap_broacast_sink_sync is called again with a correct broadcast_code,
the encrypt state stays in BT_BAP_BIG_ENC_STATE_BAD_CODE,
causing the assistant to show a broadcast prompt to the user.

**To Reproduce**

1. Add source and set bis sync request bits
2. when receive state encrypt state goes to BT_BAP_BIG_ENC_STATE_BCODE_REQ, set a wrong broadcast_code
3. call bt_bap_broacast_sink_sync with wrong code
4. when receive state encrypt state goes to BT_BAP_BIG_ENC_STATE_BAD_CODE, set the correct broadcast_code
3. call bt_bap_broacast_sink_sync with correct code

**Expected behavior**
encrypt state goes to BT_BAP_BIG_ENC_STATE_DEC;

**Impact**
Bad user experience as for example a phone with auracast will keep showing me a broadcast code prompt after I use a wrong code once

**Logs and console output**

**Environment (please complete the following information):**

 - Can be reproduced in BabbleSim simulation

**Additional context**
Can be fixed with this change:
```
--- a/subsys/bluetooth/audio/bap_broadcast_sink.c
+++ b/subsys/bluetooth/audio/bap_broadcast_sink.c
@@ -122,7 +122,8 @@ static void update_recv_state_big_synced(const struct bt_bap_broadcast_sink *sin
                subgroup_param->bis_sync = sink_subgroup->bis_indexes & sink->indexes_bitfield;
        }
 
-       if (recv_state->encrypt_state == BT_BAP_BIG_ENC_STATE_BCODE_REQ) {
+       if (recv_state->encrypt_state == BT_BAP_BIG_ENC_STATE_BCODE_REQ ||
+        recv_state->encrypt_state == BT_BAP_BIG_ENC_STATE_BAD_CODE) {
                mod_src_param.encrypt_state = BT_BAP_BIG_ENC_STATE_DEC;
        } else {
                mod_src_param.encrypt_state = recv_state->encrypt_state;
```

### PR DESCRIPTION
**Pull request by mefromac**
Fixes #88461

### CODE REVIEW

File: subsys/bluetooth/audio/bap_broadcast_sink.c [hunk 1]
```diff
@@ -122,7 +122,8 @@ static void update_recv_state_big_synced(const struct bt_bap_broadcast_sink *sin
 		subgroup_param->bis_sync = sink_subgroup->bis_indexes & sink->indexes_bitfield;
 	}
 
-	if (recv_state->encrypt_state == BT_BAP_BIG_ENC_STATE_BCODE_REQ) {
+	if (recv_state->encrypt_state == BT_BAP_BIG_ENC_STATE_BCODE_REQ ||
+        recv_state->encrypt_state == BT_BAP_BIG_ENC_STATE_BAD_CODE) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_sink.c:126]:
```suggestion
	if (recv_state->encrypt_state == BT_BAP_BIG_ENC_STATE_BCODE_REQ ||
            recv_state->encrypt_state == BT_BAP_BIG_ENC_STATE_BAD_CODE) {
```

**Review by Thalley — CHANGES_REQUESTED** [review]
The change looks OK (needs a small formatting fix), but the commit message needs to be more descriptive and not refer to a Github issue. 

See https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

File: subsys/bluetooth/audio/bap_broadcast_sink.c (hunk 1 above)
Comment (mefromac) [reply subsys/bluetooth/audio/bap_broadcast_sink.c]: Thanks for your comments, I hope I have updated the commit accordingly.

**Review by Thalley — APPROVED** [review]

**Review by pin-zephyr — APPROVED** [review]
LGTM

**Review by larsgk — APPROVED** [review]
