### PR TITLE
posix: pthread: implement pthread_sigmask()

### LINKED ISSUE #59944: posix: implement `pthread_sigmask()`
There are currently 20 missing POSIX functions with trivial implementations, `pthread_sigmask()` is one of them.

> pthread_sigmask, sigprocmask - examine and change blocked signals
> 
> The pthread_sigmask() function shall examine or change (or both) the calling thread's signal mask, regardless of the number of threads in the process. The function shall be equivalent to sigprocmask(), without the restriction that the call be made in a single-threaded process.
> 
> In a single-threaded process, the sigprocmask() function shall examine or change (or both) the signal mask of the calling thread.
> 
> If the argument set is not a null pointer, it points to a set of signals to be used to change the currently blocked set.
> 
> The argument how indicates the way in which the set is changed, and the application shall ensure it consists of one of the following values:
> 
> SIG_BLOCK
> The resulting set shall be the union of the current set and the signal set pointed to by set.
> SIG_SETMASK
> The resulting set shall be the signal set pointed to by set.
> SIG_UNBLOCK
> The resulting set shall be the intersection of the current set and the complement of the signal set pointed to by set.
> If the argument oset is not a null pointer, the previous mask shall be stored in the location pointed to by oset. If set is a null pointer, the value of the argument how is not significant and the thread's signal mask shall be unchanged; thus the call can be used to enquire about currently blocked signals.
> 
> If there are any pending unblocked signals after the call to sigprocmask(), at least one of those signals shall be delivered before the call to sigprocmask() returns.
> 
> It is not possible to block those signals which cannot be ignored. This shall be enforced by the system without causing an error to be indicated.
> 
> If any of the SIGFPE, SIGILL, SIGSEGV, or SIGBUS signals are generated while they are blocked, the result is undefined, unless the signal was generated by the action of another process, or by one of the functions [kill()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/kill.html), [pthread_kill()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_kill.html), [raise()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/raise.html), or [sigqueue()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigqueue.html).
> 
> If sigprocmask() fails, the thread's signal mask shall not be changed.
> 
> The use of the sigprocmask() function is unspecified in a multi-threaded process.

See https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_sigmask.html

See RFC #51211 for more info.

### PR DESCRIPTION
**Pull request by cfriedt**
`pthread_sigmask()` is required by the POSIX_THREADS_BASE Option Group as detailed in Section E.1 of IEEE-1003.1-2017.

The POSIX_THREADS_BASE Option Group is required for PSE51, PSE52, PSE53, and PSE54 conformance, and is otherwise mandatory for any POSIX conforming system as per Section A.2.1.3 of IEEE-1003-1.2017.

Currently, setting a pthread signal mask has no effect.

Fixes #59944

### CODE REVIEW

**Comment by cfriedt** [comment]
* made `signal.h` constants and types not dependent on `CONFIG_POSIX_SIGNAL`

File: include/zephyr/posix/signal.h [hunk 1]
```diff
@@ -45,24 +44,17 @@ extern "C" {
 /* 30 not used */
 #define SIGSYS    31 /**< Bad system call */
 
+#define RTSIG_MAX CONFIG_POSIX_RTSIG_MAX
```
[the remark this answers is not in the document]
Comment (keith-packard) [reply include/zephyr/posix/signal.h:47]: never mind, you've moved this outside the CONFIG_SIGNAL block.

File: lib/posix/Kconfig.signal [hunk 2]
```diff
@@ -24,3 +18,12 @@ config POSIX_SIGNAL_STRING_DESC
 	  Will use 256 bytes of ROM.
 
 endif
+
+# needed outside of if clause above to define constants & types in signal.h
+config POSIX_RTSIG_MAX
+	int "Maximum number of realtime signals"
+	default 31 if POSIX_SIGNAL
+	default 0 if !POSIX_SIGNAL
```
Comment (keith-packard) [inline lib/posix/Kconfig.signal:26]: probably don't need the if !POSIX_SIGNAL here?

File: tests/posix/common/src/signal.c [hunk 3]
```diff
@@ -5,12 +5,16 @@
...
+#include <pthread.h>
 #include <signal.h>
 #include <stdio.h>
 
-#include <zephyr/kernel.h>
+#include <zephyr/sys/util.h>
 #include <zephyr/ztest.h>
 
+/* A 32-bit value to use between threads for validation */
+#define BIOS_FOOD 0xB105F00D
```
Comment (keith-packard) [inline tests/posix/common/src/signal.c:16]: A more descriptive name might be good here? What is this value used for?

File: tests/posix/headers/src/signal_h.c [hunk 4]
```diff
@@ -40,12 +40,12 @@ ZTEST(posix_headers, test_signal_h)
 	zassert_not_equal(-1, offsetof(union sigval, sival_int));
 	zassert_not_equal(-1, offsetof(union sigval, sival_ptr));
 
-	/* zassert_not_equal(-1, RTSIG_MAX); */ /* not implemented */
-	/* zassert_true(SIGRTMAX - SIGRTMIN >= RTSIG_MAX); */ /* not implemented */
+	zassert_not_equal(-1, RTSIG_MAX);
+	zassert_true(SIGRTMAX - SIGRTMIN >= RTSIG_MAX);
```
Comment (keith-packard) [inline tests/posix/headers/src/signal_h.c:44]: should this be strictly equal?

Comment (cfriedt) [reply tests/posix/headers/src/signal_h.c:44]: > The range SIGRTMIN through SIGRTMAX inclusive shall include at least {RTSIG_MAX} signal numbers.

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html

File: tests/posix/common/src/signal.c (hunk 3 above)
Comment (cfriedt) [reply tests/posix/common/src/signal.c:16]: fixed!

File: lib/posix/Kconfig.signal (hunk 2 above)
Comment (cfriedt) [reply lib/posix/Kconfig.signal:26]: fixed!

**Review by keith-packard — DISMISSED** [review]

File: include/zephyr/posix/signal.h [hunk 5]
```diff
@@ -67,6 +67,16 @@ typedef struct {
 #define SIGEV_THREAD 3
```
Comment (jukkar) [inline include/zephyr/posix/signal.h:67]: Typo in commit message of `posix: pthread: implement pthread_sigmask()`
s/sitting/setting/

File: lib/posix/pthread.c [hunk 6]
```diff
@@ -1073,6 +1073,49 @@ int pthread_atfork(void (*prepare)(void), void (*parent)(void), void (*child)(vo
...
+			*oset = t->sigset;
+		}
+
+		if (set == NULL) {
+			K_SPINLOCK_BREAK;
+		}
+
+		switch (how) {
+		case SIG_BLOCK:
+			for (size_t i = 0, N = ARRAY_SIZE(set->sig); i < N; ++i) {
```
Comment (jukkar) [inline lib/posix/pthread.c:1101]: Wouldn't this be enough here i.e., why do we need `N` variable
```
for (size_t i = 0; i < ARRAY_SIZE(set->sig); ++i) {
```

File: lib/posix/pthread.c [hunk 7]
```diff
@@ -1073,6 +1073,49 @@ int pthread_atfork(void (*prepare)(void), void (*parent)(void), void (*child)(vo
...
+				t->sigset.sig[i] |= set->sig[i];
+			}
+			break;
+		case SIG_SETMASK:
+			t->sigset = *set;
+			break;
+		case SIG_UNBLOCK:
+			for (size_t i = 0, N = ARRAY_SIZE(set->sig); i < N; ++i) {
```
Comment (jukkar) [inline lib/posix/pthread.c:1109]: same here

File: lib/posix/pthread.c (hunk 6 above)
Comment (cfriedt) [reply lib/posix/pthread.c:1101]: Yes, good catch

**Review by keith-packard — APPROVED** [review]

**Comment by cfriedt** [comment]
@ycsin - can you have a look?

**Review by ycsin — APPROVED** [review]
