### PR TITLE
Bluetooth: Controller: Fix multiple advertiser assertion

### LINKED ISSUE #71608: Bluetooth: Controller: Multiple Broadcaster asserts when each of them overlap over time
**Describe the bug**
Multiple Broadcaster asserts when each of then overlap over time

```
ASSERTION FAIL [(ret == 0) || (ret == 2) || (fp_op_func == ((void *)0))] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_adv.c:1964
```

**To Reproduce**
1. mkdir -p build/broadcaster_multiple; cd build/broadcaster_multiple
2. cmake -GNinja -DBOARD=nrf52840dk_nrf52840 ../../samples/bluetooth/broadcaster_multiple
3. ninja
4. ninja flash
5. See error after a random amount of time, the implementation has to be changed as below

```
diff --git a/samples/bluetooth/broadcaster_multiple/prj.conf b/samples/bluetooth/broadcaster_multiple/prj.conf
index 1a401ed6c77..04248f7a2be 100644
--- a/samples/bluetooth/broadcaster_multiple/prj.conf
+++ b/samples/bluetooth/broadcaster_multiple/prj.conf
@@ -1,7 +1,7 @@
 CONFIG_BT=y
 CONFIG_BT_BROADCASTER=y
 CONFIG_BT_EXT_ADV=y
-CONFIG_BT_EXT_ADV_MAX_ADV_SET=1
+CONFIG_BT_EXT_ADV_MAX_ADV_SET=64
 CONFIG_BT_DEVICE_NAME="Broadcaster Multiple"
 
 CONFIG_LOG=y
diff --git a/samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c b/samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c
index d4ce51c4f25..fba839aee0c 100644
--- a/samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c
+++ b/samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c
@@ -69,9 +69,10 @@ int broadcaster_multiple(void)
                .id = BT_ID_DEFAULT,
                .sid = 0U, /* Supply unique SID when creating advertising set */
                .secondary_max_skip = 0U,
-               .options = (BT_LE_ADV_OPT_EXT_ADV | BT_LE_ADV_OPT_USE_NAME),
-               .interval_min = BT_GAP_ADV_FAST_INT_MIN_2,
-               .interval_max = BT_GAP_ADV_FAST_INT_MAX_2,
+               // .options = (BT_LE_ADV_OPT_EXT_ADV | BT_LE_ADV_OPT_USE_NAME),
+               .options = BT_LE_ADV_OPT_USE_NAME,
+               .interval_min = 0x00a0,
+               .interval_max = 0x00a0,
                .peer = NULL,
        };
        int err;
diff --git a/subsys/bluetooth/controller/ll_sw/ull_adv.c b/subsys/bluetooth/controller/ll_sw/ull_adv.c
index ee070d14857..a99cebca3bf 100644
--- a/subsys/bluetooth/controller/ll_sw/ull_adv.c
+++ b/subsys/bluetooth/controller/ll_sw/ull_adv.c
@@ -1952,6 +1952,7 @@ static uint32_t ticker_update_rand(struct ll_adv_set *adv, uint32_t ticks_delay_
        lll_rand_isr_get(&random_delay, sizeof(random_delay));
        random_delay %= ticks_delay_window;
        random_delay += (ticks_delay_window_offset + 1);
+       random_delay = ull_adv_handle_get(adv) + 1U;
 
        ret = ticker_update(TICKER_INSTANCE_ID_CTLR,
                            TICKER_USER_ID_ULL_HIGH,

```

**Expected behavior**

**Impact**
showstopper

**Logs and console output**
See description

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 2b7f5dce258

**Additional context**
NA

### PR DESCRIPTION
**Pull request by cvinayak**
When multiple advertisers overlap over time, the random delay being applied need many ticker operation context. This causes the ticker_update interface to return error causing assertion in the Controller.

This is fixed by not applying random_delay value to the overlapping advertiser that does not get to use the radio.

Fixes #71608.

### CODE REVIEW

**Review by mtpr-ot — DISMISSED** [review]
LGTM

File: subsys/bluetooth/controller/ll_sw/ull_adv.c [hunk 1]
```diff
@@ -2391,9 +2394,24 @@ static void ticker_cb(uint32_t ticks_at_expire, uint32_t ticks_drift,
...
+#if defined(CONFIG_BT_CTLR_JIT_SCHEDULING)
+			adv->delay = random_delay;
+#endif /* CONFIG_BT_CTLR_JIT_SCHEDULING */
+		} else {
+			random_delay = 0U;
+		}
+
+		if (lazy == TICKER_LAZY_MUST_EXPIRE) {
+			lazy = 0U;
+		}
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_adv.c:2414]: @mtpr-ot and @Tronil This is needed right? and was a bug upstream that `lazy` value of `TICKER_LAZY_MUST_EXPIRE`  0xFFFF was added to `adv->event_counter`, right?

Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c]: Yes it looks like there was a bug there

File: subsys/bluetooth/controller/ll_sw/ull_adv.c [hunk 2]
```diff
@@ -2391,11 +2394,31 @@ static void ticker_cb(uint32_t ticks_at_expire, uint32_t ticks_drift,
...
 
 #if defined(CONFIG_BT_CTLR_ADV_EXT)
+		uint16_t event_counter_inc;
+
+		if (lazy == TICKER_LAZY_MUST_EXPIRE) {
+			lazy = 0U;
+			event_counter_inc = 0U;
+		} else {
+			event_counter_inc = (lazy + 1U);
+		}
```
Comment (Tronil) [inline subsys/bluetooth/controller/ll_sw/ull_adv.c:2420]: Isn't it enough to set lazy = 0 for lazy == TICKER_LAZY_MUST_EXPIRE? I would expect the event counter to need to be incremented by 1 in that case also

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:2420]: i agree... i am discussing with the mesh team, as the fix in this PR seems to break some mesh tests in bsim CI.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:2420]: @Tronil, the skipped event is not counted so that the events returned to Host when the adv set terminates reflects correctly the number of event transmitted on air. With this conclusion, the behavior in this PR remains as it is currently upstream.

Please review and provide your approval.

Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:2420]: Ah - yeah carefully reading the spec we should actually keep track of the value of *completed* *transmitted* extended advertising events. So I guess we are actually not being entirely correct:
1. adv->event_counter should be increment once the adv_aux event is done, not in this ticker_cb
2. adv->event_counter should always be incremented by 1, lazy should not be used

It doesn't really have anything to do with this change though, so we should probably address that separately.

**Review by Tronil — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_adv.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:2420]: Agreed... would you be able to create github issue referencing the spec text?

**Review by kruithofa — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
