### PR TITLE
Bluetooth: add callbacks to indicate if pairing was complete or failed

### LINKED ISSUE #8390: bluetooth: request APIs to notify application that pairing is complete or not
Bluetooth pairing provides the way for authentication and security practice, thus the application should be notified if the pairing with a specific device was successful or not. The current zephyr Bluetooth stack doesn't have one which can meet this requirement. So, it is better to add a new API to cover this requirement.  Thank you!

More discussions about this request can be referred here: https://lists.zephyrproject.org/g/devel/topic/22117716#4763

### PR DESCRIPTION
**Pull request by jli157**
Added callback functions for Bluetooth stack to notify its client that pairing has been completed or failed.

fixes: #8390

### CODE REVIEW

File: include/bluetooth/conn.h [hunk 1]
```diff
@@ -392,6 +392,8 @@ struct bt_conn_auth_cb {
 #if defined(CONFIG_BT_BREDR)
 	void (*pincode_entry)(struct bt_conn *conn, bool highsec);
 #endif
+	/* @brief indicate the authentication process is complete */
+	void (*pairing_complete)(struct bt_conn *conn, unsigned int status);
```
Comment (jhedberg) [inline include/bluetooth/conn.h]: Some issues I see with this:

 - The meaning and possible values for status will need to be documented. 

 - Are there defines/enum available for the possible values in some public header file? It seems this maps to the SMP status which is only available in the private `subsys/bluetooth/host/smp.h` header file currently.

 - Why `unsigned int` instead of `u8_t` as smp.c uses internally?

 - Since this maps to SMP errors it seems you don't plan to have this used for BR/EDR? Is it not useful there? Either way it needs to be documented that the application should not expect this callback for BR/EDR.

File: subsys/bluetooth/host/smp.c [hunk 2]
```diff
@@ -1472,6 +1472,10 @@ static void smp_pairing_complete(struct bt_smp *smp, u8_t status)
 {
 	BT_DBG("status 0x%x", status);
 
+	if(bt_auth->pairing_complete) {
+		bt_auth->pairing_complete(smp->chan.chan.conn, status);
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c]: I think I suggested passing the no-bonding/bonding information to the callback, so the app has some idea whether the pairing will be discarded after the connection goes away, or if the keys will be stored persistently. Wouldn't this be useful to have?

**Review by jhedberg — CHANGES_REQUESTED** [review]
Thanks a lot for taking the initiative and implementing a solution for this open issue! There are however some things to sort out before we can merge (see my inline comments).

Also, could you please make the commit message prefix consistent with the existing commit history. As you'll see we use "Bluetooth: ..." for all Bluetooth commits.

File: include/bluetooth/conn.h (hunk 1 above)
Comment (jli157) [reply include/bluetooth/conn.h]: Hi Johan, I added a enumeration to address your concern. But maybe we need to make the naming better. Any suggestions?  

As for BR/EDR, do you mean the suggestion you made last time about moving the callback to "struct bt_conn_cb"? I'm not familiar with BR/EDR part, can you confirm and advise further on this?

File: subsys/bluetooth/host/smp.c (hunk 2 above)
Comment (jli157) [reply subsys/bluetooth/host/smp.c]: Can you check the callback definition again? Also, for your convenience, the suggestions you made last time can be referred here: https://lists.zephyrproject.org/g/devel/topic/22117716#4763

**Comment by jli157** [comment]
Hi @jhedberg , thanks for the comments! I just want to make this work to roll so that we can get the feature done as soon as possible. ( I need it. :) ). Please feel free to make more comments and directly modify it if necessary.

File: subsys/bluetooth/host/smp.c [hunk 3]
```diff
@@ -1472,6 +1472,14 @@ static void smp_pairing_complete(struct bt_smp *smp, u8_t status)
 {
 	BT_DBG("status 0x%x", status);
 
+	if (bt_auth->pairing_completed) {
+		bt_pairing_result_t pairing_ret = status == 0 ?
+			BT_PAIRING_STATUS_BONDED :
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c]: I'm not sure you understand what bonded means. There's a flag in the smp struct for that. "bonded" means you're paired and intend to store the keys persistently. "paired" is a superset of "bonded" which doesn't guarantee that the keys will be stored persistently. In the Zephyr case when pairing, but not bonding, the keys are not stored beyond the connection that creates them, i.e. they're lost once you disconnect. So mapping "status == 0" to "bonded" is not right.

Comment (jli157) [reply subsys/bluetooth/host/smp.c]: Thanks for clarifying! Where can the function "amp_pairing_complete" know that the pairing is "bonded" from its argument? The "bonded" status has been stored somewhere?

**Comment by jli157** [comment]
Reworked the patch by following your suggestions, and added two callbacks for notifying success and failure cases. 

However, for the failure reason, I need more advice about what kind of reasons should be used for the failure case.

File: include/bluetooth/conn.h [hunk 4]
```diff
@@ -392,6 +392,23 @@ struct bt_conn_auth_cb {
...
+	 * @param bonded pairing is bonded or not.
+	 */
+	void (*pairing_complete)(struct bt_conn *conn, bool bonded);
+
+	/** @brief notify that pairing process has failed.
+	 *
+	 * @param conn Connection object.
+	 * @param err_code error code of failure.
+	 */
+	void (*pairing_failed)(struct bt_conn *conn, int err_code);
```
Comment (jhedberg) [inline include/bluetooth/conn.h]: As long as we're not exposing the possible values in a public header, I'd question whether we should have an error parameter at all. Are there any good use cases where the app might want to do different things depending on the error?

**Review by jhedberg — DISMISSED** [review]
This is starting to look much better, thanks. I'm still a bit concerned with the error code parameter (see my separate comment)

File: include/bluetooth/conn.h (hunk 4 above)
Comment (jli157) [reply include/bluetooth/conn.h]: Okay, maybe it is enough to keep just one callback like before, with a `ret_code` argument which is defined to serval values including:
```
BT_PAIRING_FAILED,
BT_PAIRING_NOT_BONDED,
BT_PAIRING_BONDED
```

**Comment by jhedberg** [comment]
This looks pretty good to me now. It'd be nice to hear some opinion from other maintainers though. @Vudentz @sjanc does this look reasonable, or do you see something obvious missing or something?

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
> @Vudentz @sjanc does this look reasonable, or do you see something obvious missing or something?

I'll take the lack of comments from @sjanc and @Vudentz to mean that they're fine with this ;)
