### PR TITLE
Bluetooth: Host: Fix incorrect ACL buffer count

### LINKED ISSUE #46241: Bluetooth: Controller: ISO: Setting CONFIG_BT_CTLR_ISO_TX_BUFFERS=4 breaks non-ISO data
**Describe the bug**
If `CONFIG_BT_CTLR_ISO_TX_BUFFERS=4` and CONFIG_BT_CTLR_ADV_ISO=y then non-ISO TX buffer overflow occurs (e.g. when doing GATT operations). It also fails for larger values than 4. 

**To Reproduce**
Run e.g. `tests/bluetooth/bsim_bt/bsim_test_audio/test_scripts/vcs.sh` with `CONFIG_BT_CTLR_ISO_TX_BUFFERS=4` (instead of the CONFIG_BT_CTLR_ISO_TX_BUFFERS=3 which is the default/current at the time of this issue) with https://github.com/zephyrproject-rtos/zephyr/pull/46204.

**Expected behavior**
That the test passes with `CONFIG_BT_CTLR_ISO_TX_BUFFERS=4` as it does with `CONFIG_BT_CTLR_ISO_TX_BUFFERS=3`.

**Impact**
Minor

**Logs and console output**
Running the test will result in the following:
```
d_01: @00:00:00.835740  [00:00:00.835,723] <dbg> bt_vcs_client: vcs_discover_func: Setup complete for VCS
d_00: @00:00:01.086560  [00:00:01.086,547] <err> bt_ctlr_hci: Tx Buffer Overflow
d_00: @00:00:01.086560  [00:00:01.086,547] <wrn> bt_hci_core: Data buffer overflow (link type 0x01)
d_00: @00:00:01.086560  [00:00:01.086,547] <err> bt_conn: Unable to send to driver (err -105)
d_01: @00:00:30.000000 ERROR: (WEST_TOPDIR/zephyr/tests/bluetooth/bsim_bt/bsim_test_audio/src/common.c:73): test failed (not passed after 30 seconds)
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/46204

**Additional context**N/A

### PR DESCRIPTION
**Pull request by cvinayak**
Fix incorrect ACL buffer count use when Controller used
supports separate ISO buffers.

Fixes #46241.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -115,10 +115,12 @@ struct k_sem *bt_conn_get_pkts(struct bt_conn *conn)
...
-	if (conn->type == BT_CONN_TYPE_ISO || bt_dev.le.iso_mtu) {
-		if (bt_dev.le.iso_pkts.limit) {
-			return &bt_dev.le.iso_pkts;
-		}
+	/* Use ISO pkts semaphore if LE Read Buffer Size command returned
+	 * dedicated ISO buffers.
+	 */
+	if (conn->type == BT_CONN_TYPE_ISO &&
+	    bt_dev.le.iso_mtu && bt_dev.le.iso_pkts.limit) {
+		return &bt_dev.le.iso_pkts;
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:123]: This seems more correct, and more similar to the check we have in `conn_mtu`:
```c
static inline uint16_t conn_mtu(struct bt_conn *conn)
{
#if defined(CONFIG_BT_BREDR)
	if (conn->type == BT_CONN_TYPE_BR || !bt_dev.le.acl_mtu) {
		return bt_dev.br.mtu;
	}
#endif /* CONFIG_BT_BREDR */
#if defined(CONFIG_BT_ISO)
	if (conn->type == BT_CONN_TYPE_ISO && bt_dev.le.iso_mtu) {
		return bt_dev.le.iso_mtu;
	}
#endif /* CONFIG_BT_ISO */
#if defined(CONFIG_BT_CONN)
	return bt_dev.le.acl_mtu;
#else
	return 0;
#endif /* CONFIG_BT_CONN */
}
```

where it is an `&&` instead of an `||`. 

I do wonder if it should be something like
```c
	if (conn->type == BT_CONN_TYPE_ISO) {
		if (bt_dev.le.iso_mtu && bt_dev.le.iso_pkts.limit) {
			return &bt_dev.le.iso_pkts;
		}

		return NULL;
	}
```

So that we return `0` for ISO connections if we haven't read the buffer count yet, or if the buffer count is 0? 

Maybe it could even be as simple as 
```c
	if (conn->type == BT_CONN_TYPE_ISO) {
		return &bt_dev.le.iso_pkts;
	}
```

The point is that we probably don't want to return `&bt_dev.le.acl_pkts;` for ISO channels at all, right? 

Should `conn_mtu` be updated too?

Comment (cvinayak) [reply subsys/bluetooth/host/conn.c:123]: `If the Controller supports HCI ISO
Data packets, it shall return non-zero values for the ISO_Data_Packet_Length
and Total_Num_ISO_Data_Packets parameters.`

By this statement, we should use your proposal, right?:
```c
	if (conn->type == BT_CONN_TYPE_ISO) {
		if (bt_dev.le.iso_mtu && bt_dev.le.iso_pkts.limit) {
			return &bt_dev.le.iso_pkts;
		}

		return NULL;
	}
```

Comment (Thalley) [reply subsys/bluetooth/host/conn.c]: > `If the Controller supports HCI ISO Data packets, it shall return non-zero values for the ISO_Data_Packet_Length and Total_Num_ISO_Data_Packets parameters.`
> 
> By this statement, we should use your proposal, right?:
> 
> ```c
> 	if (conn->type == BT_CONN_TYPE_ISO) {
> 		if (bt_dev.le.iso_mtu && bt_dev.le.iso_pkts.limit) {
> 			return &bt_dev.le.iso_pkts;
> 		}
> 
> 		return NULL;
> 	}
> ```

Yes, I think this would be the best way of handling it, otherwise we risk returning a non-NULL value for ISO packets (which would for connected ISO default to the ACL buffers).

**Review by Thalley — APPROVED** [review]
We should still consider whether we want to change `conn_mtu` to use the same check too

**Review by carlescufi — APPROVED** [review]

**Comment by cvinayak** [comment]
> We should still consider whether we want to change `conn_mtu` to use the same check too

Do not want to change more than what is need to fix the reported issue of mismatched ACL buffer count. `conn_mtu` be handled in separate PR after v3.1 release.
