### PR TITLE
tests: threads: fix uninitialized scalar variable

### LINKED ISSUE #37916: [Coverity CID :219656] Uninitialized scalar variable in file /tests/kernel/threads/thread_stack/src/main.c
**Describe the bug**
Category: Uninitialized scalar variable
Function: stack_buffer_scenarios
Component: Tests
CID: 219656

Static code scan issues found in file:
https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/kernel/threads/thread_stack/src/main.c

1. In function `void stack_buffer_scenarios(void)` declaring variable `val` without initializer in L95.
2. Then in L164 assigning `stack_ptr = &val`, which points to uninitialized data.
3. In for loop in L165 assigning `pos = stack_ptr`, which points to uninitialized data.
4. Then in L167 `val = *pos;` Coverity raised next violation that uninitialized scalar variable (UNINIT), using uninitialized value `*pos`.

Please fix or provide comments in coverity using the link:
[scan9.coverity.com/reports.htm#v32951/p12996](https://scan9.coverity.com/reports.htm#v32951/p12996)

Note: This issue was created manually.

### PR DESCRIPTION
**Pull request by naiyuantian**
In the file variable val is not initialized,
causing the variable stack_ptr, pos, points to uninitialized data.
Initialize the variable val according to the code and commits.

Fixes #37916

Signed-off-by: Naiyuan Tian <naiyuan.tian@intel.com>

### CODE REVIEW

**Comment by maksimmasalski** [comment]
@naiyuantian You need to add into message body, not into title "Fixes #Github_Issue_Number". Use a Github issue number, not a Coverity issue number.

**Comment by maksimmasalski** [comment]
@naiyuantian I think Coverity wants you to initialize `val` in its declaration like `uint8_t val=0;`

File: tests/kernel/threads/thread_stack/src/main.c [hunk 1]
```diff
@@ -161,6 +161,7 @@ void stack_buffer_scenarios(void)
 	 * First test does direct read & write starting at the estimated
 	 * stack pointer up to the highest addresses in the buffer
 	 */
+	val = *stack_start;
```
Comment (maksimmasalski) [inline tests/kernel/threads/thread_stack/src/main.c:164]: As I said in the comment, Coverity wants you to initialize `val` in its declaration like `uint8_t val=0;`

Comment (maksimmasalski) [inline tests/kernel/threads/thread_stack/src/main.c:164]: As I said in the comment, Coverity wants you to initialize val in its declaration like uint8_t val=0;

**Review by maksimmasalski — CHANGES_REQUESTED** [review]

**Review by maksimmasalski — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
