### PR TITLE
Fix race and deadlock in SMP context switch paths

### LINKED ISSUE #28105: sporadic "Attempt to resume un-suspended thread object" faults on x86-64
**Describe the bug**
For some time now we have seen weird behavior on x86_64 where a thread object that was not suspended was being resumed, or the same thread was being scheduled on two CPUs at the same time. A typical backtrace:

```
START - test_fs_read
E: Page fault at address 0xb9 (error code 0x10)
E: Linear address not present in page tables
E: Access violation: supervisor thread not allowed to execute
E: PTE: not present
E: RAX: 0x0000000000104522 RBX: 0x0000000000125780 RCX: 0x000000000000000c RDX: 0x0000000000000138
E: RSI: 0x000000000014e000 RDI: 0x0000000000138000 RBP: 0x000000000013a3f8 RSP: 0x0000000000140e80
E:  R8: 0x000000000014b578  R9: 0x0000000000000000 R10: 0x0000000000000000 R11: 0x0000000000000000
E: R12: 0x0000000000000000 R13: 0x000000000014b578 R14: 0x0000000000104522 R15: 0x0000000000000000
E: RSP: 0x0000000000140e80 RFLAGS: 0x0000000000000246 CS: 0x0018 CR3: 0x0000000000150000
E: RIP: 0x00000000000000b9
E: Attempt to resume un-suspended thread object
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 1
E: Current thread: 0x0000000000126220 (main)
E: Halting system
```

I have a hypothesis that this is at least in part a race condition between the determination of the next thread to run in `next_up()` and performing the actual context switch. I suspect this has to be atomic with respect to the `sched_spinlock`, as this lock's scope includes any changes in thread state.

Currently, in both x86_64's interrupt exit handling path, and the core kernel implementation of `do_swap()`, some API (either `z_get_next_switch_handle()` or `z_get_next_ready_thread()`) is called to determine the next thread to schedule, both end up invoking `next_up()`. This is then used to perform the context switch in `arch_switch()`. The `sched_spinlock` is not held in between these two events, only local CPU interrupts are disabled. The thread state could change in the meantime due to activity on some other CPU.

If this holds, I am not yet completely sure the best way to adjust the interrupt exit path on x86_64. But for the C code in `do_swap()` I had an idea we could replace this bit:

```
	if (is_spinlock) {
		k_spin_release(lock);
	}
```

with an operation to atomically re-queue whatever lock was provided, to the sched_spinlock. If the sched_spinlock was already provided, do nothing and keep it locked. If local interrupts were just locked (z_swap_irqlock() for example), just grab the sched_spinlock. Whatever the case, hold sched_spinlock through the determination of the next ready thread and the subsequent context switch call to the end of do_swap().

I expect this is also an issue on ARC HS, our other platform which supports SMP.

### PR DESCRIPTION
**Pull request by andyross**
Two bugs found by one exerciser in #28105 that repeatedly hammered the thread preemption paths.

The first was simple enough, some needless defensive coding (not wanting to change a preexisting switch handle) could be seen by code spinning in wait_for_switch() as a completed context switch and cause the other to start running the current thread before it had spilled its context.

The second was an even rarer (and more interesting) deadlock exposed when that was fixed, in a similar area of code.  Crazy timing (possible seemingly only under qemu) could lead to two CPUs trying to run **each other's** active threads, and spinning forever waiting for the other CPU to context switch.

Fixes #28105

### CODE REVIEW

**Comment by andyross** [comment]
Pushing this before I have a working twister locally.  I'm seeing some weird failures on qemu_leon3 and qemu_cortex_a53 and need to see what's actually happening in CI.

**Review by dcpleung — APPROVED** [review]

**Comment by andyross** [comment]
Yeah, the leon3 and a53 failures seem to be phantom and local to my installation (I ran west update, I swear!)

But the handful of remaining failures are legitimate.  The last patch in this PR breaks k_yield().  Oops.  Fix incoming.

**Review by pabigot — COMMENTED** [review]
Nice work.  The first two commits look fine, but I was still trying to convince myself the third was correct before it was identified as having a problem.  Will update tomorrow after the planned fix gets pushed.

**Comment by andyross** [comment]
Add the needed logic to handle yielded current when it no longer gets added to the runqueue at the yield.

**Comment by andyross** [comment]
For those reviewing: it's admittedly true that the final patch in this series is a little subtle.  We for sure want the bug fix in the tree, but as it's just one medium bug (that doesn't actually affect real hardware due to timing constraints with IPIs) it might be worth considering pushing this until after the release and then doing a backport.

**Comment by pabigot** [comment]
My concern with the third commit is it has this:

    if (z_is_thread_queued(old_thread)) {
             _priq_run_add(&_kernel.ready_q.runq,
                           old_thread);
    }

which is odd because if the thread's queued like it says, why do we need to queue it again?

What I see is that `queue_thread()` will flag the thread as queued without actually queuing if SMP and thread is not the current thread. Presumably this is the situation that needs to be mitigated by the conditional `_priq_run_add()` call above.

Assessing whether each call site might flag a thread without queuing it:
* Line 318 in `next_up()` won't because it passes `_current`
* 336 `move_thread_to_end_of_prio_q()` might
* 476 in `ready_thread()` might
* 868 in `z_set_prio()` would if it isn't passed `_current`
* 1291 in `z_impl_k_thread_deadline_set()` would if it isn't passed `_current`
* 1323 in `z_impl_k_yield()` won't because it passes `_current`

At least 336 and 1291 leave me worried that a thread might be marked as queued, but never actually be queued, as I dont see a path from them to `z_requeue_current()` which is the only other place flagged-without-being-queued might be fixed.  I didn't look closely at the other potential call sites.

What prevents this from leaving a thread flagged as queued but not in a queue?

**Comment by andyross** [comment]
I swear I convinced myself the leon3 failures had disappeared, but they hadn't and the root cause was a broken arch_switch() on sparc.  Worked around here (it's simple), root cause bug linked.

@pabigot The point to the refactor in the second patch is to clarify that the run queue (_priq_run_add/remove()) and QUEUED flags get managed through the same API, and that they are identical exactly **except** for the case of _current, which remains outside the global run queue until the point of a context switch.  That happens in two spots: synchronously in kswap.h:do_swap() and via interrupt return where z_get_next_switch_handle() is called to fetch the next thread.

**Comment by andyross** [comment]
Pfft.  ARM64 had a different bug with arch_switch().  NOW it should work, heh.

File: kernel/sched.c [hunk 1]
```diff
@@ -181,6 +181,55 @@ static ALWAYS_INLINE struct k_thread *_priq_dumb_mask_best(sys_dlist_t *pq)
 }
 #endif
 
+/* _current is never in the run queue until context switch on
+ * SMP configurations, see z_requeue_current()
+ */
+static inline bool should_queue_thread(struct k_thread *th)
+{
+	return !IS_ENABLED(CONFIG_SMP) || th != _current;
```
Comment (pabigot) [inline kernel/sched.c:189]: >  **except** for the case of _current, which remains outside the global run queue until the point of a context switch.

A-hah.  I misread the condition.

    !IS_ENABLED(CONFIG_SMP) || th != _current;

does not mean "don't queue if SMP and *not* current thread.  It's equivalent to the **much** clearer expression:

    !(IS_ENABLED(CONFIG_SMP) && (th == _current));

which means "don't queue if SMP and *is* current thread".

Then it makes sense.

I wouldn't object to using the alternative expression here.

**Review by pabigot — APPROVED** [review]

**Comment by andyross** [comment]
Squash the bug workaround patch into the main change, as I realized (1) that this can be implemented by just disabling that write on !SMP (thus making it a performance win and not a workaround) and (2) it broke bisectability anyway.  Also rewrite the docs on arch_switch(), as they weren't great and probably part of the problem at the arch layer.

File: kernel/include/kernel_arch_interface.h [hunk 2]
```diff
@@ -78,50 +78,54 @@ void arch_new_thread(struct k_thread *thread, k_thread_stack_t *stack,
...
+ *
+ * The actual type and interpretation of the switch handle is specified
+ * by the architecture.  It is the same data structure stored in the
+ * "switch_handle" field of a newly-created thread in arch_new_thread(),
+ * and passed to the kernel as the "interrupted" argument to
+ * z_get_next_switch_handle().
+ *
+ * Note that on SMP systems, the kernel uses the store through the second
+ * pointer as a synchronization point to detect when a thread context is
+ * completely saved (so another CPU can no when it is safe to switch).
```
Comment (dcpleung) [inline kernel/include/kernel_arch_interface.h:95]: s/no/know/?

Comment (andyross) [reply kernel/include/kernel_arch_interface.h]: Oops.  Fixed.
