### PR TITLE
tests: mec15xxevb_assy6853: Enlarge the IDLE_STACK_SIZE from 256 to 512

### LINKED ISSUE #47987: test: samples/boards/mec15xxevb_assy6853/power_management failed after commit 5f60164a0fc
**Describe the bug**
test case samples/boards/mec15xxevb_assy6853/power_management failed after commit 5f60164a0fc

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? mec15xxevb_assy6853
 - What have you tried to diagnose or workaround this issue? git bisect and found first bad commit is 5f60164a0fc

**To Reproduce**
1. west build -p always -b mec15xxevb_assy6853  samples/boards/mec15xxevb_assy6853/power_management/
2. west flash

**Expected behavior**
The test should pass

**Impact**
1 test case fail in daily test

**Logs and console output**
```
[00:00:00.006,927] <wrn> pwrmgmt_test: PM single-thread test started for cycles: 5, logging: 0
[00:00:00.006,958] <inf> pwrmgmt_test: About to enter light sleep
[00:00:01.508,941] <inf> pwrmgmt_test: About to enter deep Sleep
[00:00:02.129,028] <inf> pwrmgmt_test: PM sleep entry latency 0.621 seconds
[00:00:02.129,058] <wrn> pwrmgmt_test: Sleep entry latency is higher than expected
[00:00:04.609,527] <err> os: ***** USAGE FAULT *****
[00:00:04.609,527] <err> os:   Illegal use of the EPSR
[00:00:04.609,558] <err> os: r0/a1:  0x000e9119  r1/a2:  0x00000000  r2/a3:  0x00118e20
[00:00:04.609,588] <err> os: r3/a4:  0xffffffff r12/ip:  0x001186a0 r14/lr:  0x000e5d83
[00:00:04.609,588] <err> os:  xpsr:  0x60000000
[00:00:04.609,619] <err> os: Faulting instruction address (r15/pc): 0x00001080
[00:00:04.609,619] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:04.609,649] <err> os: Current thread: 0x118d90 (main)
[00:00:04.665,527] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Ubuntu 20.04
 - Toolchain (e.g Zephyr SDK, ...)  0.14.1
 - Commit SHA or Version used 5f60164a0fc

### PR DESCRIPTION
**Pull request by hunterhu3000**
The test case "samples/boards/mec15xxevb_assy6853/power_management" could
always pass until commit 5f60164 was merged in. This patch changes the sem
take timeout value from 50ms to forever of the log thread, it will make the
idle thread run longer and takes more stack memory. Analyzed the coredump
of the failed test case, it can be found that the test case stucks at
z_idle_stacks. The test case used default CONFIG_IDLE_STACK_SIZE = 256 in
kernel/Kconfig, now we increase the value to 512 in prj.conf for this test
only. With this change, the test case can pass with the commit of 5f60164.
Fixes #47987

Signed-off-by: Hu Zhenyu <zhenyu.hu@intel.com>

### CODE REVIEW

File: subsys/logging/log_backend_uart.c [hunk 1]
```diff
@@ -136,6 +136,13 @@ static void log_backend_uart_init(struct log_backend const *const backend)
 	}
 }
 
+static int is_ready(struct log_backend const *const backend)
+{
+	if (backend->cb)
```
Comment (nashif) [inline subsys/logging/log_backend_uart.c:141]: curly braces here

**Review by nashif — DISMISSED** [review]

File: subsys/logging/log_backend_uart.c (hunk 1 above)
Comment (hunterhu3000) [reply subsys/logging/log_backend_uart.c]: Updated. But it seems there is another CI fail

File: subsys/logging/log_core.c [hunk 2]
```diff
@@ -282,7 +282,11 @@ static uint32_t z_log_init(bool blocking, bool can_sleep)
 				log_backend_enable(backend,
 						   backend->cb->ctx,
 						   CONFIG_LOG_MAX_LEVEL);
-			} else {
+			}
+			/* if the backend is activated by the if code above,
+			 * set the mask
+			 */
+			if (log_backend_is_ready(backend)) {
```
Comment (nordic-krch) [inline subsys/logging/log_core.c:289]: why this change is needed?

**Comment by nordic-krch** [comment]
See my comment https://github.com/zephyrproject-rtos/zephyr/issues/47987#issuecomment-1210191227
Imo this change is not needed and i'm not sure why it fixes #47987.

File: subsys/logging/log_core.c (hunk 2 above)
Comment (hunterhu3000) [reply subsys/logging/log_core.c:289]: Previously, log_backend_is_ready is checked only once, if the backend is not ready, it will try enable it. If it is ready, it will set the mask. When the backend is enabled, it will miss the setting of the mask, so I redo the check after that. 
If you think the below code looks better, I can replace with it 
···
                        if (log_backend_is_ready(backend) == 0) {
                                log_backend_enable(backend,
                                                   backend->cb->ctx,
                                                   CONFIG_LOG_MAX_LEVEL);
                                if (log_backend_is_ready(backend)) {
                                        mask |= BIT(i);
                                }
                        }
                        else {
                                         mask |= BIT(i);
                        }
···

**Review by chen-png — DISMISSED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Please explain the motivation for the change in the commit message

**Comment by hunterhu3000** [comment]
> Please explain the motivation for the change in the commit message
samples/boards/mec15xxevb_assy6853/power_management can pass until commit https://github.com/zephyrproject-rtos/zephyr/commit/5f60164a0fc36484b60004310320dfd6f3ef0525 merged in. This patch changes the sem take timeout of the log thread, and affect the run time of idle thread. Analyzed the coredump of the failed test case, it can be found that the program stucks at z_idle_stacks 
```
Remote debugging using 127.0.0.1:1234
0x0011ed78 in z_idle_stacks ()
(gdb) bt
#0  0x0011ed78 in z_idle_stacks ()
#1  0x000e2ab8 in arch_swap (key=<optimized out>) at /home/ztest/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:58
#2  0x0011ec40 in z_main_stack ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info thread
  Id   Target Id         Frame
* 1    Thread <main>     0x0011ed78 in z_idle_stacks ()
``` 
The CONFIG_IDLE_STACK_SIZE is set to 256 by default in the kernel/Kconfig. Change it to 512, and then the test case can pass.
The history can be seen in https://github.com/zephyrproject-rtos/zephyr/issues/47987

**Comment by hunterhu3000** [comment]
@MaureenHelm, the git commit message is updated as well. Thanks to review.

**Review by MaureenHelm — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
