### PR TITLE
Bluetooth: Fix store `disconnected_handles` reason

### LINKED ISSUE #70497: Bluetooth: hci_core: disconnect reason lost on event reorder
https://github.com/zephyrproject-rtos/zephyr/commit/dd7caf667c8edd08e841bfb14f65ff96275d232c introduces a regression; it will lose the disconnect reason if connection complete and disconnect complete events are reordered.

### PR DESCRIPTION
**Pull request by alwa-nordic**
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/70497

### CODE REVIEW

**Review by Thalley — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -807,35 +807,38 @@ int bt_hci_disconnect(uint16_t handle, uint8_t reason)
 }
 
 static uint16_t disconnected_handles[CONFIG_BT_MAX_CONN];
+static uint8_t disconnected_handles_reason[CONFIG_BT_MAX_CONN];
 static void disconnected_handles_reset(void)
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:811]: Keep the empty line after the variables definitions, please
