### PR TITLE
Bluetooth spi hci: BlueNRG-MS: Chip Select  management reworked with full DT support

### LINKED ISSUE #43310: disco_l475_iot1: BLE not working
**Describe the bug**
`samples/bluetooth/peripheral` is not working anymore on `zephyr-v3.0.0-483-g145bcd7ab9`.
It was working fine on v3.0.0

**To Reproduce**
1. west -p -b disco_l475_iot1 samples/bluetooth/peripheral
2. west flash

**Expected behavior**
BLE should be functional on this board

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-483-g145bcd7ab96e  ***                
[00:00:00.000,000] <inf> flash_stm32_qspi: M
```
Stack remains stuck in SPI transfer:
```
spi_stm32_complete (dev=<optimized out>, status=0)
    at /local/mcu/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:417
417		ll_func_disable_spi(spi);
(gdb) bt
#0  spi_stm32_complete (dev=<optimized out>, status=0)
    at /local/mcu/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:417
#1  0x0800349a in _isr_wrapper ()
    at /local/mcu/zephyrproject/zephyr/arch/arm/core/aarch32/isr_wrapper.S:233
#2  <signal handler called>
#3  0x00004000 in ?? ()
#4  0x000f8000 in ?? ()

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Ubuntu 20.04
 - Toolchain (e.g Zephyr SDK, ...)*: SDK 0.13.2
 - Commit SHA or Version used: zephyr-v3.0.0-483-g145bcd7ab9

### PR DESCRIPTION
**Pull request by ABOSTM**
Bluetooth spi hci: BlueNRG-MS Chip Select  management reworked with full DT support
See detailed analysis in #43310

* disco_l475_iot1 DT should define CS as `GPIO_ACTIVE_LOW`
* `kick_cs()` and `release_cs()` should use logic instead of pin value as active low inversion is managed underneath in `gpio_pin_set_dt()`
* for BlueNRG-MS module, we should prevent SPI driver to release CS, and let bluetooth driver do the job, otherwise, for example, CS is released between sending Read command and effective read transaction, and this cause read failure.
This could be achieved by setting operation flag `SPI_HOLD_ON_CS`

Fixes #43310

### CODE REVIEW

File: drivers/bluetooth/hci/spi.c [hunk 1]
```diff
@@ -190,13 +190,13 @@ static int configure_cs(void)
 
 static void kick_cs(void)
 {
-	gpio_pin_set_dt(&bus.config.cs->gpio, 1);
-	gpio_pin_set_dt(&bus.config.cs->gpio, 0);
+	gpio_pin_set_dt(&bus.config.cs->gpio, false);
+	gpio_pin_set_dt(&bus.config.cs->gpio, true);
```
Comment (erwango) [inline drivers/bluetooth/hci/spi.c:203]: gpio api defines 2nd argument as 'int', so 0/1 is fine as per API. If there's an actual issue, it should also be fixed at api level (and extended to users). I'd suggest to raise a dedicated issue for this point.

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/spi.c (hunk 1 above)
Comment (ABOSTM) [reply drivers/bluetooth/hci/spi.c]: Ok, right, but I don't want to change API, so let's keep integer 0/1, and change values to have logical value instead of pin value.

File: drivers/bluetooth/hci/spi.c [hunk 2]
```diff
@@ -190,13 +190,13 @@ static int configure_cs(void)
 
 static void kick_cs(void)
 {
-	gpio_pin_set_dt(&bus.config.cs->gpio, 1);
 	gpio_pin_set_dt(&bus.config.cs->gpio, 0);
+	gpio_pin_set_dt(&bus.config.cs->gpio, 1);
```
Comment (erwango) [inline drivers/bluetooth/hci/spi.c:203]: Please update commit message to fit the new behavior.

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

**Comment by ABOSTM** [comment]
Commit message is still valid. values 0/1 are now logical level and not pin values.

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Comment by carlescufi** [comment]
@jhedberg could you please take a look?

**Review by jhedberg — APPROVED** [review]
