### PR TITLE
shell: backend: telnet: No Error ENETDOWN

### LINKED ISSUE #99795: Telnet Shell Server Shows Error Log Message when iface goes down
### Describe the bug

After https://github.com/zephyrproject-rtos/zephyr/issues/99245 the Telnet Shell Server shows a Error Log Message Every time the iface goes down.

### Regression

- [ ] This is a regression.

### Steps to reproduce

west build --board=stm32h573i_dk/stm32h573xx samples/net/telnet -- -DCONFIG_LOG=y

Take the iface down, using the net shell command or plugging out the ethernet cable.

### Relevant log output

```shell
[2025-11-13 08:27:05.671] <err> shell_telnet: Telnet socket 6 error (115)
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

OS: Windows
Toolchain: Zephyr SDK 0.17.4
Zephyr: v4.3.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Jowllel**
Set Log Level to Info when the Telnet socket reports ENETDOWN, instead of logging an error each time the network is down.

Fixes #99795

### CODE REVIEW

File: subsys/shell/backends/shell_telnet.c [hunk 1]
```diff
@@ -475,7 +475,12 @@ static void telnet_server_cb(struct net_socket_service_event *evt)
 	    (evt->event.revents & ZSOCK_POLLNVAL)) {
 		(void)zsock_getsockopt(evt->event.fd, SOL_SOCKET,
 				       SO_ERROR, &sock_error, &optlen);
-		NET_ERR("Telnet socket %d error (%d)", evt->event.fd, sock_error);
+
+		if (sock_error == ENETDOWN) {
+			LOG_INF("Telnet socket %d ENETDOWN", evt->event.fd);
+		} else {
+			NET_ERR("Telnet socket %d error (%d)", evt->event.fd, sock_error);
+		}
```
Comment (jukkar) [inline subsys/shell/backends/shell_telnet.c]: Similar suggestions here as in http server pr.
```
		if (sock_error == ENETDOWN) {
			LOG_INF("Network is down");
		} else {
			LOG_ERR("Telnet socket %d error (%d)", evt->event.fd, -sock_error);
		}
```

File: subsys/shell/backends/shell_telnet.c [hunk 2]
```diff
@@ -475,7 +476,14 @@ static void telnet_server_cb(struct net_socket_service_event *evt)
...
 		(void)zsock_getsockopt(evt->event.fd, SOL_SOCKET,
 				       SO_ERROR, &sock_error, &optlen);
-		NET_ERR("Telnet socket %d error (%d)", evt->event.fd, sock_error);
+
+		ret = -sock_error;
+
+		if (ret == -ENETDOWN) {
+			LOG_INF("Network is down");
+		} else {
+			NET_ERR("Telnet socket %d error (%d)", evt->event.fd, ret);
```
Comment (rlubos) [inline subsys/shell/backends/shell_telnet.c]: Since you're already changing this, please use `LOG_ERR()` macro here, not sure why was the NET_* wrapper used given it's shell subsys.

Comment (jukkar) [reply subsys/shell/backends/shell_telnet.c]: That was what I was also suggesting my comment, although it was only in my code example

Comment (Jowllel) [reply subsys/shell/backends/shell_telnet.c]: Ah yeah sorry
I missed that in your Code Example

**Review by rlubos — DISMISSED** [review]

**Comment by rlubos** [comment]
> Could someone please add this PR to the V4.3.0 Milestone?

Up to release managers @cfriedt @jhedberg to decide if it qualifies.

**Comment by jhedberg** [comment]
> @Jowllel there's a merge conflict, so you need to rebase

Seems like you didn't do this, rather there's now a merge commit which is not allowed by Zephyr. By "rebase" I really meant `git rebase`, after which you will need to use `--force` when pushing to the PR branch.

**Review by rlubos — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
