### PR TITLE
Fix integer handling coverity issue in PPP module

### LINKED ISSUE #22912: [Coverity CID :208406] Macro compares unsigned to 0 in subsys/net/l2/ppp/ppp_l2.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/93b78b7bf8bfad75196de969a7487f95f235aad3/subsys/net/l2/ppp/ppp_l2.c#L346

Category: Integer handling issues
Function: `echo_reply_handler`
Component: Networking
CID: [208406](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=208406)

Details:

```
340     static void echo_reply_handler(void *user_data, size_t user_data_len)
341     {
342         struct ppp_context *ctx = user_data;
343         u32_t end_time = k_cycle_get_32();
344         int time_diff;
345    
>>>     CID 208406:  Integer handling issues  (NO_EFFECT)
>>>     This less-than-zero comparison of an unsigned value is never true. "end_time - ctx->shell.echo_req_data < 0U".
346         time_diff = abs(end_time - ctx->shell.echo_req_data);
347         ctx->shell.echo_req_data =
348             k_cyc_to_ns_floor64(time_diff) / 1000;
349    
350         k_sem_give(&ctx->shell.wait_echo_reply);
351     }
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by rveerama1**
Store the time difference value in u32_t variable than abs() value in signed variable.

Fixes #22912
Coverity CID: 208406

### CODE REVIEW

**Review by jukkar — APPROVED** [review]

File: subsys/net/l2/ppp/ppp_l2.c [hunk 1]
```diff
@@ -341,9 +341,9 @@ static void echo_reply_handler(void *user_data, size_t user_data_len)
 {
 	struct ppp_context *ctx = user_data;
 	u32_t end_time = k_cycle_get_32();
```
Comment (chrta) [inline subsys/net/l2/ppp/ppp_l2.c]: Can't k_cycle_get_32() wrap-around (e.g. on an ARM Cortex M), so ctx->shell.echo_req_data could actually be larger than end_time?

Comment (jukkar) [reply subsys/net/l2/ppp/ppp_l2.c]: Sure, but we are actually interested in the diff which will be correctly set even if the time has wrapped.

Comment (chrta) [reply subsys/net/l2/ppp/ppp_l2.c]: ok, thx for the explanation

**Review by chrta — APPROVED** [review]
