### PR TITLE
drivers: gpio: nrf5: Fix GPIOTE channel use overlap

### LINKED ISSUE #8815: Nordic: Directly accessing GPIOTE might create unstable firmware (GPIO, PWM, BLE)
I found the issue causing https://github.com/zephyrproject-rtos/zephyr/issues/8252 (GPIO interrupt only called once on nRF52832).

The issue is accessing GPIOTE registers responsible for GPIO pin configuration (ie: `gpiote->CONFIG[]`) from multiple Zephyr drivers.

Nordic Zephyr drivers directly access these registers without checking if other drivers also access it. So they overwrite each other GPIO configurations.
In the case of  https://github.com/zephyrproject-rtos/zephyr/issues/8252, it was the PWM driver that was overwriting the GPIO driver configurations. As @JoeHut mentioned, there are two other drivers that uses GPIO interrupts. And following which one was started first, the other one was not working (as soon as the PWM driver was doing stuff with `gpiote->CONFIG[]`).

At the moment, there are 3 drivers directly accessing `gpiote->CONFIG[]`:
- **Nordic GPIO driver:** https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/gpio/gpio_nrf5.c
- **Nordic PWM drivers:** https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/pwm/pwm_nrf5_sw.c
- **Nordic Radio drivers (BLE)**: https://github.com/zephyrproject-rtos/zephyr/blob/354c8222f1ba70d8f209fe4239c34dbb438d8660/subsys/bluetooth/controller/hal/nrf5/radio/radio.c#L995

Not sure if the new Nordic PWN driver https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/pwm/pwm_nrfx.c accesses `GPIOTE` through NRFX SDK.

**I see two possibles fixes for this issue:**
- either we introduce a Zephyr Nordic GPIOTE driver (that could live in `arch/arm/soc/nordic_nrf/`) that manages all GPIOTE accesses (mainly GPIO pin configuration allocations).
- or we only use NRFX SDK to access GPIOTE registers (I guess that will be the preferred solution as some Zephyr drivers are migrating to this API).

Note: This issue is already raised in GPIO driver: https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/gpio/gpio_nrf5.c#L68

@henrikbrixandersen Your pull-request https://github.com/zephyrproject-rtos/zephyr/pull/8628 would be affected

### PR DESCRIPTION
**Pull request by cvinayak**
Fixes issues caused in GPIO driver due to overlapping GPIOTE
channel use in nRF5 software PWM driver and in Bluetooth
controller for implementing PA/LNA feature.

The issue is solved by assigning the base and available
channel count for GPIOTE considering whether PWM and/or
PA/LNA feature is selected in the Kconfig.

Fixes #8815.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@Olivier-ProGlove FYI

File: drivers/gpio/gpio_nrf5.c [hunk 1]
```diff
@@ -66,7 +59,9 @@ struct _gpiote {
 };
 
 /*@todo: move GPIOTE channel management to a separate module */
-static u32_t gpiote_chan_mask;
+/* Reserve channels below the base index */
+#define GPIOTE_CH_BASE CONFIG_GPIO_NRF5_GPIOTE_CHAN_BASE
+static u32_t gpiote_chan_mask = BIT(GPIOTE_CH_BASE) - 1;
```
Comment (anangl) [inline drivers/gpio/gpio_nrf5.c]: You can use the `BIT_MASK` macro for this.

File: drivers/gpio/gpio_nrf5.c [hunk 2]
```diff
@@ -233,6 +228,21 @@ static int gpio_nrf5_config(struct device *dev,
...
+		if (i < 0) {
+			if (popcount(gpiote_chan_mask) == GPIOTE_CH_NUM) {
+				return -EIO;
+			}
+
+			/* allocate a GPIOTE channel */
+			i = find_lsb_set(~gpiote_chan_mask) - 1;
+		}
+
+		gpiote_chan_mask |= BIT(i);
```
Comment (anangl) [inline drivers/gpio/gpio_nrf5.c]: This should be inside the `if` above, since it is only needed for newly allocated channels.

File: drivers/gpio/gpio_nrf5.c (hunk 1 above)
Comment (cvinayak) [reply drivers/gpio/gpio_nrf5.c]: will do

File: drivers/gpio/gpio_nrf5.c (hunk 2 above)
Comment (cvinayak) [reply drivers/gpio/gpio_nrf5.c]: agreed

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
