### PR TITLE
bluetooth: host: Bug fix in bt_uuid_create

### LINKED ISSUE #18799: bt_uuid_create_le() and bt_uuid_create() have endianness issues, and only one of them is needed
The `bt_uuid_create()` API is missing byte order conversions required for big-endian architectures.  Fixing it will make `bt_uuid_create_le()` unnecessary, so that can be removed.

### PR DESCRIPTION
**Pull request by akshhr**
Endianness bug fix in bt_uuid_create function.
Replaced bt_uuid_create_le with bt_uuid_create which
handles both UUID from air and internal varaiable.
Fixed bug with endianess in case of big endian targets.

Fixes #18799

Signed-off-by: Akshatha.H <akhr@oticon.com>

### CODE REVIEW

**Review by Vudentz — DISMISSED** [review]
bt_uuid_create may not be only used with data coming over the air so conversion should be done before the call, we could perhaps have a _le alternative that can be used directly when parsing data received over the air.

**Comment by akshhr** [comment]
> bt_uuid_create may not be only used with data coming over the air so conversion should be done before the call, we could perhaps have a _le alternative that can be used directly when parsing data received over the air.

@Vudentz There is already a function bt_uuid_create_le just before this function call to handle the above mentioned scenario

**Review by jhedberg — CHANGES_REQUESTED** [review]
The fix doesn't look right to me (considering the existence of `bt_uuid_create_le()`), but at the same time the current implementation of `bt_uuid_create()` looks buggy in that it seems to have unaligned access issues if given unaligned data. @kimsekkelund any comments? It looks like you're behind this code?

**Review by joerchan — CHANGES_REQUESTED** [review]
`bt_uuid_create_le` is meant to handle packets on air.
`bt_uuid_create` was meant to create a bt_uuid type from internal represententation (like from the read callback). Since it is from internal representation i don't think it needs to handle unaligned access.

**Comment by akshhr** [comment]
> `bt_uuid_create_le` is meant to handle packets on air.
> `bt_uuid_create` was meant to create a bt_uuid type from internal represententation (like from the read callback). Since it is from internal representation i don't think it needs to handle unaligned access.

Yes, that is my understanding also.

**Comment by akshhr** [comment]
> The fix doesn't look right to me (considering the existence of `bt_uuid_create_le()`), but at the same time the current implementation of `bt_uuid_create()` looks buggy in that it seems to have unaligned access issues if given unaligned data. @kimsekkelund any comments? It looks like you're behind this code?

I assume sys_get_le16() and sys_get_le32() functions assures aligned memory even though the input data is unaligned.

**Comment by jhedberg** [comment]
> I assume sys_get_le16() and sys_get_le32() functions assures aligned memory even though the input data is unaligned.

Yes, they are safe to use, however considering that that `bt_uuid_create()` takes the "internal representation" doesn't that imply native byte order, meaning no conversion should be needed? If  alignment is not guaranteed then `UNALIGNED_GET()` is what should be used when no byte order conversion is needed.

**Comment by akshhr** [comment]
> > I assume sys_get_le16() and sys_get_le32() functions assures aligned memory even though the input data is unaligned.
> 
> Yes, they are safe to use, however considering that that `bt_uuid_create()` takes the "internal representation" doesn't that imply native byte order, meaning no conversion should be needed? If alignment is not guaranteed then `UNALIGNED_GET()` is what should be used when no byte order conversion is needed.

In function find_type_cb, attr->read (line 603) always returns uuid in **little endian** , so we need to do this conversion for big endian targets

**Comment by jhedberg** [comment]
> In function find_type_cb, attr->read (line 603) always returns uuid in little endian , so we need to do this conversion for big endian targets

There's something wrong with the naming of these APIs then. If both take little-endian data it's confusing that only one has an _le suffix. Can we come up with better names for them?

**Comment by wdhpawa** [comment]
> > In function find_type_cb, attr->read (line 603) always returns uuid in little endian , so we need to do this conversion for big endian targets
> 
> There's something wrong with the naming of these APIs then. If both take little-endian data it's confusing that only one has an _le suffix. Can we come up with better names for them?

I think the problem is that someone expected local database reads to return native endian UUIDs, and client related reads to return little endian UUIDs (in this case 2 different create functions are needed), whereas someone else expected both types of reads to be handled by the same function (in this case only one create function is needed). So now we have a mix: both types of read are handled by the same function which returns little-endian UUIDs, and we have two create functions which both process little-endian UUIDs.

At this point it is probably easier to merge the 2 create functions into one.

By the way, the database read function currently lacks support for 32-bit UUIDs, so we should add that.

**Comment by joerchan** [comment]
> > > In function find_type_cb, attr->read (line 603) always returns uuid in little endian , so we need to do this conversion for big endian targets
> > 
> > 
> > There's something wrong with the naming of these APIs then. If both take little-endian data it's confusing that only one has an _le suffix. Can we come up with better names for them?
> 
> I think the problem is that someone expected local database reads to return native endian UUIDs, and client related reads to return little endian UUIDs (in this case 2 different create functions are needed), whereas someone else expected both types of reads to be handled by the same function (in this case only one create function is needed). So now we have a mix: both types of read are handled by the same function which returns little-endian UUIDs, and we have two create functions which both process little-endian UUIDs.
> 
> At this point it is probably easier to merge the 2 create functions into one.
> 
> By the way, the database read function currently lacks support for 32-bit UUIDs, so we should add that.

It looks like you are correct, if the `attr->read` function in `find_type_cb` in att.c is `bt_gatt_attr_read_service` in `gatt.c` then it seems that data is not in native CPU endianness, but always little endian, so then `bt_uuid_create` in `find_type_cb` should actually be `bt_uuid_create_le`.

It seems that we should get rid of one of the functions then. It would seems this PRs version of `bt_uuid_create` is the correct one.  I suggest we use this one, and get rid of `bt_uuid_create_le`.

The changes to these uuid create functions was here: https://github.com/zephyrproject-rtos/zephyr/pull/17765

**Comment by akshhr** [comment]
> > > > In function find_type_cb, attr->read (line 603) always returns uuid in little endian , so we need to do this conversion for big endian targets
> > > 
> > > 
> > > There's something wrong with the naming of these APIs then. If both take little-endian data it's confusing that only one has an _le suffix. Can we come up with better names for them?
> > 
> > 
> > I think the problem is that someone expected local database reads to return native endian UUIDs, and client related reads to return little endian UUIDs (in this case 2 different create functions are needed), whereas someone else expected both types of reads to be handled by the same function (in this case only one create function is needed). So now we have a mix: both types of read are handled by the same function which returns little-endian UUIDs, and we have two create functions which both process little-endian UUIDs.
> > At this point it is probably easier to merge the 2 create functions into one.
> > By the way, the database read function currently lacks support for 32-bit UUIDs, so we should add that.
> 
> It looks like you are correct, if the `attr->read` function in `find_type_cb` in att.c is `bt_gatt_attr_read_service` in `gatt.c` then it seems that data is not in native CPU endianness, but always little endian, so then `bt_uuid_create` in `find_type_cb` should actually be `bt_uuid_create_le`.
> 
> It seems that we should get rid of one of the functions then. It would seems this PRs version of `bt_uuid_create` is the correct one. I suggest we use this one, and get rid of `bt_uuid_create_le`.
> 
> The changes to these uuid create functions was here: #17765

@joerchan I have modified the code accordingly, hope this should be fine.

**Comment by joerchan** [comment]
@akshhr Thank you. Did you run the files through an automated style tool?
There are some `#endif /*CONFIG_NAME */` That are weirdly aligned with the code line above them. Can you fix them?

**Comment by akshhr** [comment]
> @akshhr Thank you. Did you run the files through an automated style tool?
> There are some `#endif /*CONFIG_NAME */` That are weirdly aligned with the code line above them. Can you fix them?
I ran the uncrustify tool as specified in contribution guidelines. I will check once again and confirm. Thank you

File: include/bluetooth/uuid.h [hunk 1]
```diff
@@ -50,29 +50,29 @@ struct bt_uuid_128 {
...
-#define BT_UUID_INIT_128(value...)	\
-{					\
-	.uuid.type = BT_UUID_TYPE_128,	\
-	.val = { value },		\
-}
+#define BT_UUID_INIT_128(value ...)	       \
+	{				       \
+		.uuid.type = BT_UUID_TYPE_128, \
+		.val = { value },	       \
+	}
```
Comment (jhedberg) [inline include/bluetooth/uuid.h]: These white-space changes don't seem to be related to the fix? Please put them in a separate patch. We'd probably want to merge this for 2.0, and the less changes there are the better.

File: include/bluetooth/uuid.h [hunk 2]
```diff
@@ -50,29 +50,29 @@ struct bt_uuid_128 {
...
 
 #define BT_UUID_DECLARE_16(value) \
 	((struct bt_uuid *) (&(struct bt_uuid_16) BT_UUID_INIT_16(value)))
 #define BT_UUID_DECLARE_32(value) \
 	((struct bt_uuid *) (&(struct bt_uuid_32) BT_UUID_INIT_32(value)))
-#define BT_UUID_DECLARE_128(value...) \
+#define BT_UUID_DECLARE_128(value ...) \
```
Comment (jhedberg) [inline include/bluetooth/uuid.h]: Same here.

File: subsys/bluetooth/host/att.c [hunk 3]
```diff
@@ -34,28 +34,28 @@
...
+#define BT_GATT_PERM_WRITE_MASK                 (BT_GATT_PERM_WRITE |	      \
+						 BT_GATT_PERM_WRITE_ENCRYPT | \
+						 BT_GATT_PERM_WRITE_AUTHEN)
+#define BT_GATT_PERM_ENCRYPT_MASK               (BT_GATT_PERM_READ_ENCRYPT | \
+						 BT_GATT_PERM_WRITE_ENCRYPT)
+#define BT_GATT_PERM_AUTHEN_MASK                (BT_GATT_PERM_READ_AUTHEN | \
+						 BT_GATT_PERM_WRITE_AUTHEN)
+#define ATT_CMD_MASK                            0x40
+
+#define ATT_TIMEOUT                             K_SECONDS(30)
```
Comment (jhedberg) [inline subsys/bluetooth/host/att.c]: And here.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Please remove the white-space changes from this PR. The rest of the fix looks good to me. Since we haven't had any release with the now removed `bt_uuid_create_le()` it'd be important to get this PR for 2.0. @ioannisg FYI.

**Review by jhedberg — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by Vudentz — APPROVED** [review]
LGTM, I will send a PR adding the test case for it.
