### PR TITLE
drivers: Fix ESP32 I2C unwilled stop and repeated start

### LINKED ISSUE #40483: ESP32: display sample over i2c not working
**Describe the bug**
I wanted to run "subsys/display/lvgl" sample with SSD1306 display connected over i2c.

Using nrf52840dk the display works as expected. Sniffed init transmission looks like following:
```
Restart, 78 [ 3C | WR ], 00, AE, Stop
Start, 78 [ 3C | WR ], 00, D5, 80, D9, 22, DB, 20, Stop
Start, 78 [ 3C | WR ], 00, 40, D3, 00, DA, 12, A8, 3F, Stop
Start, 78 [ 3C | WR ], 00, A1, C8, Stop
Start, 78 [ 3C | WR ], 00, 8D, 14, 33, Stop
Start, 78 [ 3C | WR ], 00, A4, A6, Stop
Start, 78 [ 3C | WR ], 00, 81, 80, Stop
Start, 78 [ 3C | WR ], 00, AF, Stop
Start, 78 [ 3C | WR ], 00, 20, 00, 21, 00, 7F, 22, 00, 04, Stop
```
Once I switched to esp32 the display stopped working. Sniffed init sequence:
```
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], AE, Stop
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], D5, 80, D9, 22, DB, 20, Stop
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], 40, D3, 00, DA, 12, A8, 3F, Stop
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], A1, C8, Stop
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], 8D, 14, 33, Stop
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], A4, A6, Stop
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], 81, 80, Stop
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], AF, Stop
Start, 78 [ 3C | WR ], 00, Stop
Start, 78 [ 3C | WR ], 20, 00, 21, 00, 7F, 22, 00, 04, Stop
```
 
**To Reproduce**
1.  Add `arduino_i2c: &i2c0 {};` to `boards/xtensa/esp32/esp32.dts`
1. `west build samples/subsys/display/lvgl -b esp32 -- -DSHIELD=ssd1306_128x64`
2. `west flash`
3. Sniff transmission with some external hardware
4. Notice not working display.

**Expected behavior**
Working display, i2c sequence as nrf52's one.

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 21.04 64-bit x86_64
 - Toolchain: esp-2020r3-8.4.0 (espressif), zephyr-sdk-0.13.1
 - Commit SHA or Version used: 7b7e175f8ce2b9e32abbf3ba1edc88d06c933d46

### PR DESCRIPTION
**Pull request by znfgnu**
Fixes zephyrproject-rtos/zephyr#40483

- Fixes STOP signal generation condition:
  - at the end of i2c_msg transmission **only** if `I2C_MSG_STOP` flag is set
- Adds new field to driver's data that indicates if STOP condition was generated at the end of the previous transmission.
- Start condition is generated if `I2C_MSG_RESTART` flag is set of if STOP was generated previously.

### CODE REVIEW

File: drivers/i2c/i2c_esp32.c [hunk 1]
```diff
@@ -471,13 +475,13 @@ static int IRAM_ATTR i2c_esp32_write_msg(const struct device *dev,
 			i2c_hal_write_cmd_reg(&data->hal, cmd, data->cmd_idx++);
 		}
 
-		if (msg->len == 0 || (msg->flags & I2C_MSG_STOP)) {
+		if (msg->len == 0 && (msg->flags & I2C_MSG_STOP)) {
```
Comment (sylvioalves) [inline drivers/i2c/i2c_esp32.c:478]: Hi @znfgnu. When I refactored this, I think I missed removing this check: `msg->len == 0`.  
So this line would be:  
 `if ((msg->flags & I2C_MSG_STOP)) {`  

Would yo be able to re-test only with this change?

Comment (znfgnu) [reply drivers/i2c/i2c_esp32.c:478]: Hi @sylvioalves ! I will check this on Monday or Tuesday and let you know.

I think that the change you proposed would work for i2c msgs shorter than `SOC_I2C_FIFO_LEN` bytes.
I don't think it would be correct for i2c messages longer than `SOC_I2C_FIFO_LEN`.
Without checking `msgs->len == 0` STOP would be generated after each `SOC_I2C_FIFO_LEN` bytes.
Please, correct me if I'm wrong.

IMO condition `msg->len == 0 && (msg->flags & I2C_MSG_STOP)` will let STOP to be generated after last transmission (when `msg->len == 0`) for given i2c_msg only when `I2C_MSG_STOP` flag is set, which is expected behavior.

Comment (sylvioalves) [reply drivers/i2c/i2c_esp32.c:478]: You are correct. `msg->len` needs to be checked with AND in there. I didn't quite get the reason for having the `data->stop_generated`. What's the scenario for that?

Comment (znfgnu) [reply drivers/i2c/i2c_esp32.c:478]: SSD1306 driver (which I used to have problem with) uses `i2c_burst_write` (`drivers/i2c.h`) function to send data to the display. This routine writes `num_bytes` bytes from buffer `*buf` to register `start_addr` of  device with address `dev_addr`. The function implements data transfer by sending two `i2c_msg`s:
```
	msg[0].buf = &start_addr;
	msg[0].len = 1U;
	msg[0].flags = I2C_MSG_WRITE;

	msg[1].buf = (uint8_t *)buf;
	msg[1].len = num_bytes;
	msg[1].flags = I2C_MSG_WRITE | I2C_MSG_STOP;

	return i2c_transfer(dev, msg, 2, dev_addr);
```
Before introducing this flag, esp32 i2c driver used to send repeated start and device address after the first message, which was unintended - `I2C_MSG_RESTART` flag for the second message was not set. In line 461 in my commit I added condition that allows start condition as well as device address to be sent - if `I2C_MSG_RESTART` is set or right after STOP condition was generated.

Comment (sylvioalves) [reply drivers/i2c/i2c_esp32.c:478]: I retest the same sample and only changed the `msg->len` check  from OR to AND. It seems it is enough to fix the issue, isn't it? Can you paste the buffer that requires `data->stop_generated` to be added?

Only changing the `msg->len` to AND got this output from I2C: 

```c
I2C data received: 00 AE
I2C data received: 00 D5 80 D9 22 DB 20
I2C data received: 00 40 D3 00 DA 12 A8 3F
I2C data received: 00 A1 C8
I2C data received: 00 8D 14 33
I2C data received: 00 A4 A6
I2C data received: 00 81 80
I2C data received: 00 AF
I2C data received: 00 20 00 21 00 7F 22 00 04
```

Comment (znfgnu) [reply drivers/i2c/i2c_esp32.c:478]: It isn't - without check from line 461 the driver sends repeated START with address before sending `msg[1]`'s payload. I'll send you recorded transmission later today (once I go back home).

I suspect that your logging device ignores repeated START and treats two consecutive `i2c_msg`s as one transmission despite the presence of repeated START - maybe because of lack of STOP condition. The display didn't worked in this case.

Comment (sylvioalves) [reply drivers/i2c/i2c_esp32.c:478]: @znfgnu thanks, no need to record I transmission.

Comment (znfgnu) [reply drivers/i2c/i2c_esp32.c:478]: Despite no need for recording I'll leave it here for other people involved in this MR - it should make my changes more clear.

I checked the driver using `nrf52840dk_nrf52840` and `nucleo_h743zi` boards and transmission looked like the following (display working):
```
Start, 78 [ 3C | WR ], 00, AE, Stop
Start, 78 [ 3C | WR ], 00, D5, 80, D9, 22, DB, 20, Stop
Start, 78 [ 3C | WR ], 00, 40, D3, 00, DA, 12, A8, 3F, Stop
Start, 78 [ 3C | WR ], 00, A1, C8, Stop
Start, 78 [ 3C | WR ], 00, 8D, 14, 33, Stop
Start, 78 [ 3C | WR ], 00, A4, A6, Stop
Start, 78 [ 3C | WR ], 00, 81, 80, Stop
Start, 78 [ 3C | WR ], 00, AF, Stop
Start, 78 [ 3C | WR ], 00, 20, 00, 21, 00, 7F, 22, 00, 04, Stop
```

esp32 without `stop_generated` flag (display not working):
```
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], AE, Stop
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], D5, 80, D9, 22, DB, 20, Stop
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], 40, D3, 00, DA, 12, A8, 3F, Stop
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], A1, C8, Stop
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], 8D, 14, 33, Stop
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], A4, A6, Stop
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], 81, FF, Stop
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], AF, Stop
Start, 78 [ 3C | WR ], 00, 
Restart, 78 [ 3C | WR ], 20, 00, 21, 00, 7F, 22, 00, 04, Stop
```

esp32 with `stop_generated` flag (display working):
```
Start, 78 [ 3C | WR ], 00, AE, Stop
Start, 78 [ 3C | WR ], 00, D5, 80, D9, 22, DB, 20, Stop
Start, 78 [ 3C | WR ], 00, 40, D3, 00, DA, 12, A8, 3F, Stop
Start, 78 [ 3C | WR ], 00, A1, C8, Stop
Start, 78 [ 3C | WR ], 00, 8D, 14, 33, Stop
Start, 78 [ 3C | WR ], 00, A4, A6, Stop
Start, 78 [ 3C | WR ], 00, 81, 80, Stop
Start, 78 [ 3C | WR ], 00, AF, Stop
Start, 78 [ 3C | WR ], 00, 20, 00, 21, 00, 7F, 22, 00, 04, Stop
```

**Comment by sylvioalves** [comment]
@znfgnu Although the proposed PR works, I think we could have this fix by handling it in its messages flags instead of creating a new variable (very similar to other I2C drivers). Could you PTAL in #40651? I would copy the diff in here but it it will mess up). If you approve, feel free to change in here.

**Comment by znfgnu** [comment]
@sylvioalves I fixed the driver according to changes you proposed. The difference is that messages validation is done before the transfer. By the way, I moved `k_sem_take` after emptiness check - for empty transmissions the semaphore used to be taken but not released.

**Review by sylvioalves — APPROVED** [review]

**Comment by sylvioalves** [comment]
@ulipe @glaubermaroto PTAL

**Comment by sylvioalves** [comment]
@znfgnu Please, add the commit signature.

**Review by uLipe — APPROVED** [review]

**Comment by znfgnu** [comment]
> @znfgnu Please, add the commit signature.

Done by force-pushing amended commit. Let me know if there is any other, more human way to do it.

**Review by glaubermaroto — APPROVED** [review]
