### PR TITLE
Bluetooth: gatt settings (NVS) fixes

### LINKED ISSUE #54172: Bluetooth: GATT: Written value of gatt_cf_cfg data may be dropped on power down
**Describe the bug**
The `gatt_cf_cfg` data is stored in the non-volatile memory only on `bt_gatt_identity_resolved` and `bt_gatt_disconnected`.
It is possible that device running Zephyr would drop the written value if an unexpected power down happens while connection is still maintained.
I think that, by default, the CF configuration should be stored in non-volatile memory when GATT write is handled to make sure that the default configuration is safe.

**To Reproduce**
Used nRF Desktop application (`applications/nrf_desktop`) from nRF Connect SDK (https://github.com/nrfconnect/sdk-nrf).

1. Flash the nRF52840 DK with configuration that works as HID keyboard
   `west build -b nrf52840dk_nrf52840 --pristine -- -DCONF_FILE=prj_keyboard.conf`
   `west flash --erase`
2. Add logs to indicate when the following functions are called in `bluetooth/host/gatt.c`: `cf_write` (CF value GATT write), `cf_set` (CF value loaded from non-volatile memory - settings).
3. Connect and bond with a Bluetooth Central.
    Make sure that the connected Central uses GATT Caching and triggered the CF GATT write.
4. Reboot the device running Zephyr while Bluetooth connection is still maintained (before disconnection).
5. See that `cf_set` is not called after reboot, because the CF data was not stored in non-volatile memory.

Note: You can also verify that if the Bluetooth connection is disconnected before the reboot, the CF value is properly stored in the non-volatile memory for the bonded peer (and then it's restored after reboot).

**Expected behavior**
The `gatt_cf_cfg` data for a bonded peer should be stored in the non-volatile memory and restored after reboot.

**Impact**
GATT caching feature may not  work correctly - GATT Client would not be properly marked as change unaware.

**Environment (please complete the following information):**
Replicated on nRF Connnect SDK (https://github.com/nrfconnect/sdk-nrf; commit hash: `54125e4ae7b670b8c8331055d8be06f8b416f5ea`).

### LINKED ISSUE #54173: Bluetooth: GATT: Change awareness of bonded GATT Client is not maintained on reconnection after reboot
**Describe the bug**
According to Bluetooth core specification v5.2 (Vol 3, Part G, 2.5.2.1 Robust Caching):

> From the perspective of a server, each connected client is either "change-aware" or "change-unaware" regarding changes in the database definitions. After connecting to a server, the initial state of a client without a trusted relationship is change-aware. The initial state of a client with a trusted relationship is unchanged from the previous connection unless the database has been updated since the last connection, in which case the initial state is change-unaware.

Zephyr's Bluetooth host does not store the the `CF_CHANGE_AWARE` flag for GATT Client in non-volatile memory, so that after reboot bonded GATT Client is marked as change unaware even if nothing has changed in GATT Server's database (the initial state of the GATT Client is not unchanged from the previous connection).

**To Reproduce**
Used nRF Desktop application (applications/nrf_desktop) from nRF Connect SDK (https://github.com/nrfconnect/sdk-nrf).

1. Flash the nRF52840 DK with configuration that works as HID keyboard
  `west build -b nrf52840dk_nrf52840 --pristine -- -DCONF_FILE=prj_keyboard.conf`
  `west flash --erase`
2. Add logs to indicate value returned by the `bt_gatt_change_aware` (in `bluetooth/host/gatt.c`) for the connected peer.
3. Add logs  when the following functions are called in `bluetooth/host/gatt.c`: `cf_write` (CF value GATT write), `cf_set` (CF value loaded from non-volatile memory - settings).
4. Connect and bond with a Bluetooth Central.
    Make sure that the connected Central uses GATT Caching and triggered the CF GATT write.
5. Disconnect the Bluetooth connection (to workaround: https://github.com/zephyrproject-rtos/zephyr/issues/54172).
6. Reboot Zephyr device.
7. Notice that even though the GATT database was unchanged, the peer is initially marked as "change-unaware").

The error replicates after each reboot.

**Expected behavior**
The initial state of a client with a trusted relationship should be unchanged from the previous connection unless the database
has been updated since the last connection.

**Impact**
GATT caching feature may not work correctly after reboot. GATT Server forces GATT Client to perform rediscovery even if it's not needed.

Environment (please complete the following information):
Replicated on nRF Connnect SDK (https://github.com/nrfconnect/sdk-nrf; commit hash: 54125e4ae7b670b8c8331055d8be06f8b416f5ea).

### PR DESCRIPTION
**Pull request by jori-nordic**
See commit messages.

I will also write a bsim test for this, hence why the PR is in draft.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54172.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54173.

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1211,73 +1256,115 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
+		}
 	}
 }
 
-static void gatt_ccc_conn_enqueue(struct bt_conn *conn)
+static void gatt_delayed_store_enqueue(struct bt_conn *conn, enum delayed_store_flags flag)
 {
-	if ((!gatt_ccc_conn_is_queued(conn)) &&
-	    bt_addr_le_is_bonded(conn->id, &conn->le.dst)) {
+	if (!conn) {
```
Comment (jori-nordic) [inline subsys/bluetooth/host/gatt.c:1295]: there might be a bug here:
- if the device is disconnected, and we (de)register a gatt service afterwards, we won't store the change-aware status
- also need to double-check there is no way `_dequeue` will get called with `conn == NULL`.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -1211,73 +1256,115 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
+		LOG_WRN("Not connected: cannot store client features to NVS");
+		return;
+	}
+
+	bool queued = gatt_delayed_store_is_queued(conn, flag);
+	bool bonded = bt_addr_le_is_bonded(conn->id, &conn->le.dst);
+
+	if (!queued && bonded) {
 		/* Store the connection with the same index it has in
```
Comment (jori-nordic) [inline subsys/bluetooth/host/gatt.c:1304]: I don't really like this, leads to problems when doing stuff to the gatt db when the connection is not active.

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:1295]: it looks like the first point isn't really an issue: if we don't get powered down, then the change-aware status will be correct (it's just not stored to NVS).
If we power-down, then the gatt db will be reset to its initial state, and if we decide to alter the db, the peer will be marked correctly as change-unaware when the connection is established (and will refuse ATT operations)

File: subsys/bluetooth/host/gatt.c [hunk 3]
```diff
@@ -1211,73 +1225,109 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
 		 * the conns array
 		 */
-		gatt_ccc_store.conn_list[bt_conn_index(conn)] =
-			bt_conn_ref(conn);
+		uint8_t index = bt_conn_index(conn);
+		struct conn_list *el = &gatt_delayed_store.conn_list[index];
 
-		k_work_reschedule(&gatt_ccc_store.work, CCC_STORE_DELAY);
+		if (el->conn == NULL) {
+			el->conn = bt_conn_ref(conn);
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:1315]: Btw. should we somehow ensure that all flags are cleared just after we allocated the new connection? Otherwise there could be a risk that new conn inherits flags from previous one.

**Review by MarekPieta — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 4]
```diff
@@ -5896,13 +5926,30 @@ static int cf_set(const char *name, size_t len_rd, settings_read_cb read_cb,
...
 			return len;
 		}
 
+		memcpy(cfg->data, dst, sizeof(cfg->data));
 		LOG_DBG("Read CF: len %zd", len);
+
+		if (len != sizeof(dst)) {
+			LOG_DBG("Change-aware status not stored, "
+				"defaulting peer status to change-aware");
+			set_change_aware(NULL, cfg, true);
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:5941]: Good point, I reverted it to change-unaware.

For the bit, I prefer if that bit is set from only one place. 
I removed the manual setting below, since in that case (when running `settings_load`) we will not be connected, and `set_change_aware` will only set the bit and not try to write it back to NVS.

`set_change_aware` needs to be able to have `conn == NULL` because it can get called from other places where the connection is not valid anymore.

**Comment by jori-nordic** [comment]
Moving out of draft. The stack changes / test can be reviewed, I'll fix the CI errors on the next push.

File: subsys/bluetooth/host/gatt.c [hunk 5]
```diff
@@ -1211,73 +1225,110 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
 		 */
-		gatt_ccc_store.conn_list[bt_conn_index(conn)] =
-			bt_conn_ref(conn);
+		uint8_t index = bt_conn_index(conn);
+		struct conn_list *el = &gatt_delayed_store.conn_list[index];
 
-		k_work_reschedule(&gatt_ccc_store.work, CCC_STORE_DELAY);
+		if (el->conn == NULL) {
+			el->conn = bt_conn_ref(conn);
+			atomic_set(el->flags, 0);
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:1340]: There is hidden a type error here. `atomic_set` takes a pointer to a single `atomic_t`. `el->flags` is an array of `atomic_t`. This happens to work fine so long as `enum delayed_store_flags` has fewer than `ATOMIC_BITS` members, which admittedly is quite large; so maybe this case is fine by our code standard since we don't anticipate the flag count to grow that much?

Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:1340]: yeah I don't think we're gonna cross `ATOMIC_BITS`, is that 32 or something?

File: subsys/bluetooth/host/gatt.c [hunk 6]
```diff
@@ -1211,73 +1225,110 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
 		}
 
 		if (bt_addr_le_is_bonded(conn->id, &conn->le.dst)) {
-			ccc_store->conn_list[i] = NULL;
-			bt_gatt_store_ccc(conn->id, &conn->le.dst);
-			bt_conn_unref(conn);
+			if (IS_ENABLED(CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE) &&
+			    gatt_delayed_store_is_queued(conn, DELAYED_STORE_CCC)) {
+				bt_gatt_store_ccc(conn->id, &conn->le.dst);
+				gatt_delayed_store_dequeue(conn, DELAYED_STORE_CCC);
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:1379]: I think these effects must be done in reverse order. The flag must be cleared first. When the flag is set again while the store-procedure is in progress (possibly almost finished), it is necessary to run the procedure again.

File: subsys/bluetooth/host/Kconfig [hunk 7]
```diff
@@ -208,15 +208,40 @@ config BT_SETTINGS_CCC_LAZY_LOADING
 	  Disabling this option will increase memory usage as CCC values for all
 	  bonded devices will be loaded when calling settings_load.
 
+config BT_SETTINGS_DELAYED_STORE
+	# Enables delayed non-volatile storage mechanism
+	bool
+	help
+	  Triggers the storage of the CF and CCC right after a write.
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/Kconfig:215]: What happens when you set this config to false?

Comment (alwa-nordic) [inline subsys/bluetooth/host/Kconfig:215]: What happens when you set this config to false?

Comment (alwa-nordic) [inline subsys/bluetooth/host/Kconfig:215]: What happens when you set this config to false?

File: tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/server.c [hunk 8]
```diff
@@ -0,0 +1,77 @@
...
+
+	if (get_test_round() == 0) {
+		printk("bonding\n");
+		bond(conn);
+	} else {
+		printk("encrypting\n");
+		set_security(conn, BT_SECURITY_L2);
+	}
+
+	wait_disconnected();
```
Comment (alwa-nordic) [inline tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/server.c:74]: This doesn't test that the write happens before the disconnection.

Comment (alwa-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/server.c:74]: But also: Does anything bad happen if we power-off in the on-disconnected callback? (I suspect some work items will not run.)

File: subsys/bluetooth/host/Kconfig (hunk 7 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/Kconfig:215]: this is a convenience option, not user-selectable. Check out the `CCC_STORE_ON_WRITE` and `CF_STORE_ON_WRITE` help strings for what happens in that case.

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:1323]: alright, on second thought, this is a bad design. I wil instead try to rework `bt_gatt_store_cf` to not need `conn` (seems easy) so we always store to NVS regardless of connection status.

File: tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/server.c (hunk 8 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/server.c:74]: I will change that so the server dies before the connection is ended.
For the second point, I think that should rather be in a separate bsim robustness-type test, since I suppose other stuff than GATT might break.

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c]: @MarekPieta you can take another look now

Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c]: Yes, I just started rereview

File: subsys/bluetooth/host/gatt.c [hunk 9]
```diff
@@ -549,10 +553,58 @@ enum delayed_store_flags {
...
+	return changed;
+}
+
+void set_change_aware(struct gatt_cf_cfg *cfg, bool aware)
+{
+	bool changed = set_change_aware_no_store(cfg, aware);
+
+#if defined(CONFIG_BT_SETTINGS_DELAYED_STORE)
+	if (changed) {
+		gatt_delayed_store_enqueue(cfg->id, &cfg->peer, DELAYED_STORE_CF);
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:582]: With the current approach we may need to increase number of delayed CF writes that can be queued (to `(CONFIG_BT_MAX_PAIRED + CONFIG_BT_MAX_CONN)`). Keep in mind that we may call `set_change_aware` also for bonded peers that are not connected. Alternatively maybe we could simply store the value instantly if peer is not connected?

File: subsys/bluetooth/host/gatt.c [hunk 10]
```diff
@@ -1211,73 +1228,135 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
-			bt_conn_unref(conn);
+			if (IS_ENABLED(CONFIG_BT_SETTINGS_CF_STORE_ON_WRITE) &&
+			    atomic_test_bit(el->flags, DELAYED_STORE_CF)) {
+				atomic_clear_bit(el->flags, DELAYED_STORE_CF);
+				bt_gatt_store_cf(el->id, &el->peer);
+			}
+
+			if (atomic_get(el->flags) == 0) {
+				gatt_delayed_store_free(el);
+			}
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:1427]: Not sure if we need to do it with current implementation. During allocation we can override the `gatt_delayed_store` object if flags are set to zeros anyway

**Review by MarekPieta — CHANGES_REQUESTED** [review]

**Comment by MarekPieta** [comment]
During the review I focused on implementation in `gatt.c` file. I am not too familiar with `bsim`.

File: subsys/bluetooth/host/gatt.c (hunk 9 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:582]: I'd prefer the second solution, but it seems like an optimization. I'd rather do it after getting the bug fix in.

File: subsys/bluetooth/host/gatt.c [hunk 11]
```diff
@@ -878,8 +878,11 @@ static void sc_indicate(uint16_t start, uint16_t end);
 
 static void db_hash_process(struct k_work *work)
 {
+	bool store;
+
 #if defined(CONFIG_BT_SETTINGS)
-	if (atomic_test_and_clear_bit(gatt_sc.flags, DB_HASH_LOAD)) {
+	store = atomic_test_and_clear_bit(gatt_sc.flags, DB_HASH_LOAD);
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:884]: yes, in the case `store` = false. The prev. behavior was to always store, even if we hadn't actually loaded the hash from the NVS.

File: subsys/bluetooth/host/gatt.c [hunk 12]
```diff
@@ -1211,73 +1228,137 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
-	if ((!gatt_ccc_conn_is_queued(conn)) &&
-	    bt_addr_le_is_bonded(conn->id, &conn->le.dst)) {
-		/* Store the connection with the same index it has in
-		 * the conns array
-		 */
-		gatt_ccc_store.conn_list[bt_conn_index(conn)] =
-			bt_conn_ref(conn);
+	if (el) {
+		memset(&el->peer, 0, sizeof(el->peer));
+		atomic_set(el->flags, 0);
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:1359]: since 0 is a valid `id`, I didn't bother. But yeah I can do that.

File: subsys/bluetooth/host/gatt.c [hunk 13]
```diff
@@ -1211,73 +1228,137 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
+static void gatt_delayed_store_enqueue(uint8_t id, const bt_addr_le_t *peer_addr,
+				       enum delayed_store_flags flag)
+{
+	bool bonded = bt_addr_le_is_bonded(id, peer_addr);
+	struct ds_peer *el = gatt_delayed_store_find(id, peer_addr);
+
+	if (bonded) {
+		if (el == NULL) {
+			el = gatt_delayed_store_alloc(id, peer_addr);
+			if (el == NULL) {
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:1373]: Yeah I also think it shouldn't happen.

File: subsys/bluetooth/host/gatt.c (hunk 10 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:1427]: let's do it just for correctness.

File: tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/client.c [hunk 14]
```diff
@@ -0,0 +1,105 @@
...
+#include <string.h>
+
+void client_round_0(void)
+{
+	struct bt_conn *conn;
+
+	printk("start round 0...........\n");
+
+	conn = connect_as_peripheral();
+	printk("connected: conn %p\n", conn);
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/client.c:26]: this is a common idiom in zephyr (that we don't explicitly cast to void), take a look at e.g. `gatt.c`

File: subsys/bluetooth/host/gatt.c [hunk 15]
```diff
@@ -5927,13 +5984,34 @@ static int cf_set(const char *name, size_t len_rd, settings_read_cb read_cb,
...
 			return len;
 		}
 
+		memcpy(cfg->data, dst, sizeof(cfg->data));
 		LOG_DBG("Read CF: len %zd", len);
+
+		if (len != sizeof(dst)) {
+			LOG_WRN("Change-aware status not found in settings, "
+				"defaulting peer status to change-unaware");
+			set_change_aware(cfg, false);
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:6011]: I added a check for change-awareness once the gatt bearer has been encrypted (`bt_gatt_encrypt_change`), seems to fit the bill. I added a test round to double-check that we do receive the SC indication when the change-unaware status is loaded from the settings.

File: subsys/bluetooth/host/gatt.c [hunk 16]
```diff
@@ -5927,13 +5984,34 @@ static int cf_set(const char *name, size_t len_rd, settings_read_cb read_cb,
...
+		} else {
+			/* change-aware byte is present in NVS */
+			uint8_t change_aware = dst[sizeof(cfg->data)];
+
+			if (change_aware & ~BIT(CF_CHANGE_AWARE)) {
+				LOG_WRN("Read back bad change-aware value: 0x%x, "
+					"defaulting peer status to change-unaware",
+					change_aware);
+				set_change_aware(cfg, false);
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:6020]: should be handled by this https://github.com/zephyrproject-rtos/zephyr/pull/54349/files#r1101366188

File: subsys/bluetooth/host/gatt.c [hunk 17]
```diff
@@ -1211,73 +1300,129 @@ static void clear_ccc_cfg(struct bt_gatt_ccc_cfg *cfg)
...
+	if (bonded) {
+		if (el == NULL) {
+			el = gatt_delayed_store_alloc(id, peer_addr);
+			__ASSERT(el != NULL, "Can't save CF / CCC to flash");
+		}
+
+		atomic_set_bit(el->flags, flag);
+
+		k_work_reschedule(&gatt_delayed_store.work,
+				  K_MSEC(CONFIG_BT_SETTINGS_DELAYED_STORE_MS));
```
Comment (hermabe) [inline subsys/bluetooth/host/gatt.c:1377]: Nothing will be stored to flash if the device reboots/loses power before `CONFIG_BT_SETTINGS_DELAYED_STORE_MS`?

File: tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/gatt_utils.c [hunk 18]
```diff
@@ -0,0 +1,368 @@
...
+	 */
+	int err = bt_gatt_service_register(&test_svc_2);
+
+	__ASSERT(!err, "Failed to register GATT service (err %d)\n", err);
+}
+
+/* We need to discover:
+ * - Dynamic service
+ * - Client Features (to set robust caching)
+ * - DB hash handle (to get out of the change-unaware state)
```
Comment (hermabe) [inline tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/gatt_utils.c:112]: I dont see the DB hash is read anywhere? Also a thing to note, the DB hash shall use read by uuid:
> In order to read the value of this characteristic the client shall always use the
GATT Read Using Characteristic UUID sub-procedure. The Starting Handle
should be set to 0x0001 and the Ending Handle should be set to 0xFFFF.

Not sure it is worth caring about in a test.

File: tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/client.c (hunk 14 above)
[the remark this answers is not in the document]
Comment (MarekPieta) [reply tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/client.c:26]: C standard states that `for %p the argument shall be a pointer to void.`
Anyway let's leave it if it's acceptable here.

File: subsys/bluetooth/host/gatt.c [hunk 19]
```diff
@@ -852,6 +904,8 @@ static void db_hash_process(struct k_work *work)
 		 */
 		sc_indicate(0x0001, 0xffff);
 
+		set_all_change_unaware();
```
[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:910]: There is an edge case I think. It could appear right after the DFU.

We see that database hash does not match, so we store new hash and set change awareness to false (keep in mind the change awareness store operation is delayed). At this point we may be rebooted and after the reboot we no longer see that the database hash was modified (so we forgotten that peers should have been marked as change unaware).

Should not have high impact anyway since we would most probably send SC indications.

[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:910]: There is an edge case I think. It could appear right after the DFU.

We see that database hash does not match, so we store new hash and set change awareness to false (keep in mind the change awareness store operation is delayed). At this point we may be rebooted and after the reboot we no longer see that the database hash was modified (so we forgotten that peers should have been marked as change unaware).

Should not have high impact anyway since we would most probably send SC indications.

File: subsys/bluetooth/host/gatt.c (hunk 17 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:1377]: That's true. Proper fix would require to write from RX thread in some places I think (otherwise we never know if the value would actually be stored before response is sent). I noticed that implementation tries to avoid it.

File: subsys/bluetooth/host/gatt.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:884]: Are you sure? It seems that the value of `store` is not used anywhere undef if and code under if ends with return. If BT_SETTINGS are disabled, the value of store is set to `true` anyway so behavior seems not changed.

[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:884]: There is an additional `db_hash_store` under the `if` statement too

File: subsys/bluetooth/host/gatt.c (hunk 9 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:582]: The count seems updated, so it should work fine :)

File: subsys/bluetooth/host/gatt.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:884]: this is inside the ifdef: 
image

[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:884]: if the settings haven't yet been loaded, `store` will be false. previously we would then call `db_hash_gen` (at the end of this fn) with store=true, overwriting the value in the settings. 
Then when settings are loaded, the hash is recalculated, but it will match with the one in NVS (since it has just been overwritten).

File: subsys/bluetooth/host/gatt.c (hunk 17 above)
Comment (hermabe) [reply subsys/bluetooth/host/gatt.c:1377]: Yeah, not sure if there is a better way to solve it. It can anyway wait until laters as it was not introduced here as you say.

File: subsys/bluetooth/host/gatt.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:884]: Ahh, you are right. There is a case where we do not enter `if` and it makes the difference. I initially overlooked it - sorry.

[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:884]: so there was actually a bug here, I reworked it.

File: subsys/bluetooth/host/gatt.c (hunk 19 above)
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:910]: hm that is true, I did misunderstand you. 
The best way would be to store a "last seen hash" for each peer. I would do that if storage was free. 
I've changed it now to store to settings in `set_all_change_unaware`.

File: subsys/bluetooth/host/gatt.c [hunk 20]
```diff
@@ -502,6 +500,9 @@ static struct _bt_gatt_ccc sc_ccc = BT_GATT_CCC_INITIALIZER(NULL,
 							    sc_ccc_cfg_write,
 							    NULL);
 
+/* Do not shuffle the values in this enum, they are used as bit offsets when
+ * saving the CF flags to NVS (i.e. NVS persists between FW upgrades).
+ */
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:505]: I don't think there is. I'm kinda already doing this when reading it (e.g. if the bit is not present or a bad value).

File: tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/gatt_utils.c (hunk 18 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_gatt_settings/src/gatt_utils.c:112]: I was reading it in a previous version. I'll remove it.

File: subsys/bluetooth/host/gatt.c (hunk 19 above)
[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:938]: Should be good enough.
I think it's better to force a few unnecessary discoveries than to miss a necessary discovery.

File: subsys/bluetooth/host/gatt.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c]: Yes, thanks :)

**Review by MarekPieta — CHANGES_REQUESTED** [review]

**Review by alwa-nordic — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 21]
```diff
@@ -5547,6 +5717,15 @@ void bt_gatt_encrypt_change(struct bt_conn *conn)
 #endif	/* CONFIG_BT_GATT_AUTO_RESUBSCRIBE */
 
 	bt_gatt_foreach_attr(0x0001, 0xffff, update_ccc, &data);
+
+#if defined(CONFIG_BT_SETTINGS)
+	if (!bt_gatt_change_aware(conn, false)) {
+		/* Send a Service Changed indication if the current peer is
+		 * marked as change-unaware.
+		 */
+		sc_indicate(0x0001, 0xffff);
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:5726]: We could consider optimizing it and indicating only to this particular peer (may be done in the future since it should not lead to bugs - it's just an optimization)

File: subsys/bluetooth/host/gatt.c [hunk 22]
```diff
@@ -638,7 +704,13 @@ static ssize_t cf_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
 
 	bt_addr_le_copy(&cfg->peer, &conn->le.dst);
 	cfg->id = conn->id;
-	atomic_set_bit(cfg->flags, CF_CHANGE_AWARE);
+	set_change_aware(cfg, true);
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:707]: If a connected peer writes CF value before bonded and then reboots without disconnection, the written CF value is lost. On the other hand if the same peer disconnects before the reboot, the CF value is written to settings. Seems like bug.
Replicated this one with a Windows 10 used as Bluetooth Central.

File: subsys/bluetooth/host/gatt.c [hunk 23]
```diff
@@ -885,7 +886,28 @@ static void sc_indicate(uint16_t start, uint16_t end);
...
+	bool hash_loaded_from_settings =
+		atomic_test_bit(gatt_sc.flags, DB_HASH_LOAD);
+	bool already_processed =
+		atomic_test_bit(gatt_sc.flags, DB_HASH_LOAD_PROC);
+
+	if (!hash_loaded_from_settings) {
+		/* we want to generate the hash, but not overwrite the hash
+		 * stored in settings, that we haven't yet loaded.
+		 */
+		db_hash_gen(false);
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:898]: can we get `db_hash_store` out of `db_hash_gen()`?

**Review by alwa-nordic — CHANGES_REQUESTED** [review]
&ZeroWidthSpace;

File: subsys/bluetooth/host/gatt.c (hunk 22 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:707]: btw. Similar issue could affect CCC values if they are written before bonded.
Maybe we should store CCC and CF also on `pairing_complete` from `bt_conn_auth_info_cb `  to prevent the issue (I think that could be done in a separate PR)?

File: subsys/bluetooth/host/gatt.c [hunk 24]
```diff
@@ -638,7 +704,13 @@ static ssize_t cf_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
...
 	bt_addr_le_copy(&cfg->peer, &conn->le.dst);
 	cfg->id = conn->id;
-	atomic_set_bit(cfg->flags, CF_CHANGE_AWARE);
+	set_change_aware(cfg, true);
+
+#if defined(CONFIG_BT_SETTINGS_DELAYED_STORE)
+	/* Save the new configuration to NVM (in another thread) */
+	LOG_DBG("trigger CF write");
+	gatt_delayed_store_enqueue(conn->id, &conn->le.dst, DELAYED_STORE_CF);
+#endif
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:713]: Isn't it already done by `set_change_aware` now?

File: subsys/bluetooth/host/gatt.c (hunk 21 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:5726]: yeah I wanted to do that originally, but its trickier than it seems because we use global flags, not per-peer for book-keeping. Maybe will do the optimization later.

File: subsys/bluetooth/host/gatt.c [hunk 25]
```diff
@@ -813,7 +886,28 @@ static void sc_indicate(uint16_t start, uint16_t end);
 static void db_hash_process(struct k_work *work)
 {
 #if defined(CONFIG_BT_SETTINGS)
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:888]: Maybe we could perform `db_hash_process` in `db_hash_commit` callback context (instead of moving it to Bluetooth long workqueue context that has low priority)?
That could allow us to avoid synchronization issues related to processing the db_hash and marking peers as change unaware when GATT database changes after a DFU operation. I think current implementation introduces possibility of accessing GATT by previously bonded peer before DB hash is processed and before the peer is properly marked as change unaware.
The issue also seem not directly related to the PR so may be addressed separately I think.

**Review by MarekPieta — DISMISSED** [review]
One small improvement: https://github.com/zephyrproject-rtos/zephyr/pull/54349#discussion_r1102865765

Also added 2 comments related to other possible issues found during the review. Maybe we could address these issues in separate PRs to limit scope of this one?

File: subsys/bluetooth/host/gatt.c (hunk 21 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:5726]: yep, will do that in the future. Please open an Enhancement issue linking this comment, you can assign it to me :+1:

File: subsys/bluetooth/host/gatt.c (hunk 22 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:707]: Yeah I think we should only ever store to NVS when we are sure that we are bonded. I will double-check the spec to be sure.

File: subsys/bluetooth/host/gatt.c (hunk 25 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:888]: Yeah, please open another low-prio bug for that. you can assign me for now as well.
I think it should be okay to NAK all GATT access until the hash has been calculated.

File: subsys/bluetooth/host/gatt.c (hunk 23 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c]: done

**Review by alwa-nordic — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 21 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:5720]: https://github.com/zephyrproject-rtos/zephyr/issues/54766

File: subsys/bluetooth/host/gatt.c (hunk 22 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:707]: Discussed offline. We do not store to NVS when we are not bonded (we already have proper checks in code to ensure this).

The main problem is that we may not store the CCC and CF values if peer writes it and then bonds. We need to trigger write when bonding is complete (the `identity_resolved` callback would not be called if the connected peer does not use privacy).

**Review by hermabe — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 22 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:707]: can you please open another bug and assign me?

File: subsys/bluetooth/host/gatt.c (hunk 25 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:883]: Alternatively, maybe we could delay sending GATT response and force the database hash calculation in the current context (I am not sure which solution would provide better interoperability with devices available on the market)

Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:883]: that may be a valid idea, but this is kinda why we added this long-wq in the first place: bt runs as a coop prio, and the hash can be quite long, and will pre-empt other threads from running (even if cooperative).

Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:883]: Follow-up issue: https://github.com/zephyrproject-rtos/zephyr/issues/54773

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
Seems like this might be good to get included in the 3.3 release.

**Review by stephanosio — COMMENTED** [review]
The changes in this PR are confined to the Bluetooth subsystem and, given that there is a dedicated team vigorously testing and fixing any Bluetooth-related bugs, I am ok with including this in the 3.3 release.
