### PR TITLE
kernel: avoid recursive scheduler lock in k_heap_free path

### LINKED ISSUE #106659: kernel: Recursive locking of _sched_spinlock in k_thread_abort() with user-space
### Describe the bug

I have found a path where we attempt to recursively lock __sched_spinlock_ (something that is not allowed in Zephyr).

It occurs under very specific circumstances--aborting a user thread that has dynamic objects but there are threads waiting for the memory that aborting it would be free.

I stumbled across this when I tried refactoring _z_unpend_all()_ so that it had __sched_spinlock_ locked for its whole loop.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Inspection.

1. k_thread_abort() calls z_thread_abort().
2. z_thread_abort() locks _sched_spinlock  <<<< Important
3. z_thread_abort() calls z_thread_halt()
4. z_thread_halt() calls halt_thread()  
5. halt_thread() calls k_thread_perms_all_clear() when CONFIG_USERSPACE=y
6. k_thread_perms_all_clear() calls clear_perms_cb() foreach object wordlist.
7. clear_perms_cb() calls unref_check()
8. unref_check() calls k_free() when CONFIG_DYNAMIC_OBJECTS=y
9. k_free() calls k_heap_free()
10. k_heap_free() calls z_unpend_all()
11. z_unpend_all() wakes any threads blocked waiting for memory from the heap
12. z_unpend_all() calls z_unpend_thread()
13. z_unpend_thread() calls z_unpend_thread_no_timeout()
14. z_unpend_thread_no_timeout() locks _sched_spinlock      <<<< Recursive attempt.

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

Current SHA: 77eb31e8604216cad176b11d34f2a2643b23dcfa

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by npitre**
Alternative to #106732.

When `halt_thread()` calls `k_thread_perms_all_clear()` under `_sched_spinlock`,
the permission cleanup can trigger `k_free()` on dynamic objects. `k_heap_free()`
then calls `z_unpend_all()` which attempts to take `_sched_spinlock` again,
causing a recursive lock.

Rather than adding a per-CPU flag and conditional locking in `z_unpend_all()`,
this introduces `_sched_locked` variants of the free functions that use internal
scheduler helpers to operate on wait queues without re-acquiring the lock:

- `z_unpend_all_locked()` — lock-free core of `z_unpend_all()`, assumes
  `_sched_spinlock` is held. `z_unpend_all()` becomes a thin wrapper.
- `k_heap_free_sched_locked()` — frees heap memory and wakes waiters via
  `z_unpend_all_locked()`. Drops the heap lock before unpending since the
  wait queue is protected by the scheduler lock, not the heap lock.
- `k_free_sched_locked()` — `k_free()` counterpart using the above.
- `unref_check()` gains a `sched_locked` parameter: `true` from the abort
  path (`clear_perms_cb`), `false` from `k_thread_perms_clear()`.

Fixes #106659

### CODE REVIEW

File: kernel/userspace.c [hunk 1]
```diff
@@ -681,15 +686,15 @@ void k_thread_perms_clear(struct k_object *ko, struct k_thread *thread)
...
+		unref_check(ko, index, false);
 	}
 }
 
 static void clear_perms_cb(struct k_object *ko, void *ctx_ptr)
 {
 	uintptr_t id = (uintptr_t)ctx_ptr;
 
-	unref_check(ko, id);
+	unref_check(ko, id, true);
```
Comment (peter-mitsis) [inline kernel/userspace.c:716]: This is close. Of the three (3) cases where `clear_perms_cb()` is used, only one of them has the scheduler locked.

Scenario 1. Scheduler not locked.
   1. k_object_alloc() / k_object_alloc_size()
   2. z_object_alloc()
  3. thread_idx_alloc()

Scenario 2.  Scheduler not locked
   1. k_object_alloc() / k_object_alloc_size()
   2. z_object_alloc()  : dynamic_objece_create() failed for K_OBJ_THREAD
   3. thread_idx_free()

Scenario 3. Scheduler locked
   1. k_thread_perms_all_clear()

Continuing with this approach, we could modify the internal API `k_object_wordlist_foreach()` to accept a sched_locked paramter and propagate this to the callback routines `clear_perms_cb()` and `wordlist_cb()`.

**Comment by peter-mitsis** [comment]
I think this looks good. I'll check back in a bit to verify that CI passed. Meanwhile, I'll close my ugly solution.

**Comment by npitre** [comment]
Interesting finding during CI: the new `z_unpend_all()` now takes `_sched_spinlock` once around the whole loop (via `z_unpend_all_locked()`), instead of the original per-thread lock/unlock cycles through `z_unpend_thread()`/`z_ready_thread()`. This means `CONFIG_SPIN_VALIDATE` now catches any caller of `k_heap_free()` that already holds the sched lock — even when the wait queue is empty and no actual deadlock would occur.

This exposed a real bug beyond the `unref_check` → `k_free(dyn)` path: `unref_check()` also calls `k_msgq_cleanup()` and `k_stack_cleanup()` which internally call `k_free()` on dynamically allocated buffers. Those were going through the regular `k_free()` path while `_sched_spinlock` was held.

The fix now also introduces `z_msgq_cleanup_sched_locked()` and `z_stack_cleanup_sched_locked()` variants, factored from the original cleanup functions with a common static helper that returns the memory to free, letting each wrapper use the appropriate free call.

We got away with this before only because the system heap never had waiters — `z_unpend_all()` looped zero times, so the recursive lock was never attempted. The tighter locking in the new `z_unpend_all()` made the validation trip even on empty queues, surfacing these hidden issues.

**Review by peter-mitsis — DISMISSED** [review]

File: kernel/kheap.c [hunk 2]
```diff
@@ -216,3 +216,22 @@ void k_heap_free(struct k_heap *heap, void *mem)
...
+ * Uses z_unpend_all_locked() to avoid recursive locking.
+ * Any woken threads are readied but not rescheduled. The caller is
+ * responsible for ensuring a reschedule happens after releasing the
+ * scheduler lock.
+ */
+void k_heap_free_sched_locked(struct k_heap *heap, void *mem)
+{
+	k_spinlock_key_t key = k_spin_lock(&heap->lock);
+
+	sys_heap_free(&heap->heap, mem);
```
Comment (sylvioalves) [inline kernel/kheap.c:231]: Evaluate if tracing is missing in here:

`SYS_PORT_TRACING_OBJ_FUNC(k_heap, free, heap);`

**Review by sylvioalves — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]
