### PR TITLE
drivers/sensor: lsm6ds0: Fix SENSOR_DEG2RAD_DOUBLE macro

### LINKED ISSUE #39483: LSM6DS0 Gyroscope rad/s Calculation Error
**Describe the bug**
It appears the LSM6DS0 driver uses an incorrect constant when calculating the rad/s angular velocity for its gyroscope.

The following calculation is used:
```c
// drivers/sensor/lsm6ds0/lsm6ds0.c
static inline void lsm6ds0_gyro_convert(struct sensor_value *val, int raw_val,
          float numerator)
{
  double dval;

  dval = (double)(raw_val) * numerator / 1000.0 * SENSOR_DEG2RAD_DOUBLE;
  val->val1 = (int32_t)dval;
  val->val2 = ((int32_t)(dval * 1000000)) % 1000000;
}
``` 

With the `SENSOR_DEG2RAD_DOUBLE` constant defined as:
```c
// drivers/sensor/lsm6ds0/lsm6ds0.h
#define SENSOR_DEG2RAD_DOUBLE (180.0 / SENSOR_PI_DOUBLE)
```
Resulting in an incorrect value (in deg^2 / rad).

The correct value can be obtained by modifying the macro definition to:
```c
// drivers/sensor/lsm6ds0/lsm6ds0.h
#define SENSOR_DEG2RAD_DOUBLE (SENSOR_PI_DOUBLE / 180.0 )
```

**To Reproduce**
The `samples/shields/x_nucleo_iks01a1` project can be used. However an additional `sensor_sample_fetch` needs to be added for the lsm6ds0 gyroscope, as it is currently not included in the example.

**Expected behavior**
When the lsm6ds0 is near stationary, the measured angular velocity should be close to 0. Currently the readings for each axis are floating up to +- 100 rad/s.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain :  gcc-arm-none-eabi 1.80201.181220 (8.2.1).
 - Commit SHA or Version used: Zephyr 2.20600.210721 (2.6.0) ,

### PR DESCRIPTION
**Pull request by avisconti**
In order to convert from degrees to radiants the SENSOR_DEG2RAD_DOUBLE
macro must divide the argument by 180 degrees and multiply by PI
radiants, and not the other way around. Please note that same macro
is already defined in the correct way in other sensor drivers as well.
(Fix #39483)

### CODE REVIEW

**Review by gmarull — APPROVED** [review]

File: drivers/sensor/lsm6ds0/lsm6ds0.h [hunk 1]
```diff
@@ -314,7 +314,7 @@
 
 #define SENSOR_G_DOUBLE		(SENSOR_G / 1000000.0)
 #define SENSOR_PI_DOUBLE	(SENSOR_PI / 1000000.0)
-#define SENSOR_DEG2RAD_DOUBLE	(180.0 / SENSOR_PI_DOUBLE)
+#define SENSOR_DEG2RAD_DOUBLE	(SENSOR_PI_DOUBLE / 180)
```
Comment (MaureenHelm) [inline drivers/sensor/lsm6ds0/lsm6ds0.h:317]: Is there a reason you're not using `sensor_degrees_to_rad` defined in `include/drivers/sensor.h`?

Comment (MaureenHelm) [inline drivers/sensor/lsm6ds0/lsm6ds0.h:317]: Is there a reason you're not using `sensor_degrees_to_rad` defined in `include/drivers/sensor.h`?

Comment (avisconti) [reply drivers/sensor/lsm6ds0/lsm6ds0.h:317]: > sensor_degrees_to_rad
This driver is very old (2016). I'm not sure but maybe the sensor_degrees_to_rad() was not available at that time. Since the LSM6DS0 component is old and now obsolete, can we keep it as it is? For the new components (either the ones that are currently using SENSOR_DEG2RAD_DOUBLE) I may do a separate commit.

Currently I see the following:

```iis2iclx/iis2iclx.h:#define SENSOR_DEG2RAD_DOUBLE			(SENSOR_PI_DOUBLE / 180)
ism330dhcx/ism330dhcx.h:#define SENSOR_DEG2RAD_DOUBLE			(SENSOR_PI_DOUBLE / 180)
lsm6ds0/lsm6ds0.h:#define SENSOR_DEG2RAD_DOUBLE	(SENSOR_PI_DOUBLE / 180)
lsm6dsl/lsm6dsl.h:#define SENSOR_DEG2RAD_DOUBLE			(SENSOR_PI_DOUBLE / 180)
lsm6dso/lsm6dso.h:#define SENSOR_DEG2RAD_DOUBLE			(SENSOR_PI_DOUBLE / 180)
```
Only lsm6ds0 is obsolete. I can do a separate PR for all of them (even lsm6ds0)

Comment (MaureenHelm) [reply drivers/sensor/lsm6ds0/lsm6ds0.h:317]: Sounds good, thanks.

**Review by MaureenHelm — APPROVED** [review]
