### PR TITLE
nvs: fix possibility of losing data

### LINKED ISSUE #34722: nvs: possibility of losing data
**Describe the bug**
When nvs does a garbage collection to free up space for new writes it ends by doing a flash erase of a sector. When the erase is interrupted due to a power fail the subsequent startup of nvs will detect data in the sector that was being erased and restart a gc operation (erasing the already copied data). As the erase was ongoing the data that is found in the sector might no longer contain valid data.

The result is losing data that was valid before the interrupted erase.
 
**Expected behavior**
No data should be lost even if a sector erase is interrupted.

**Impact**
This could result in a variety of malfunctions depending on the use of the nvs file system.

### PR DESCRIPTION
**Pull request by Laczen**
Fix the possibility of losing data after startup as a result of a badly
erased sector.

Fixes #34722.

Signed-off-by: Laczen JMS <laczenjms@gmail.com>

### CODE REVIEW

**Comment by Laczen** [comment]
@nvlsianpu, fyi

File: subsys/fs/nvs/nvs.c [hunk 1]
```diff
@@ -586,6 +594,22 @@ static int nvs_gc(struct nvs_fs *fs)
 		}
 	} while (gc_prev_addr != stop_addr);
 
+gc_done:
+
+	/* Make it possible to detect that gc has finished by writing a
```
Comment (nvlsianpu) [inline subsys/fs/nvs/nvs.c:599]: cool comment!

File: subsys/fs/nvs/nvs.c [hunk 2]
```diff
@@ -485,7 +486,18 @@ static int nvs_sector_close(struct nvs_fs *fs)
...
 }
 
+static int nvs_add_gc_done_ate(struct nvs_fs *fs)
+{
+	struct nvs_ate gc_done_ate;
+
+	LOG_DBG("Adding gc done ate at %x", fs->ate_wra & ADDR_OFFS_MASK);
+	gc_done_ate.id = 0xffff;
+	gc_done_ate.len = 0U;
+	gc_done_ate.offset = (uint16_t)(fs->data_wra & ADDR_OFFS_MASK);
```
Comment (nvlsianpu) [inline subsys/fs/nvs/nvs.c:496]: gc_done_ate.offset: doses it have any future sense to set this value to data_wra?
Not a problem, I'm just curious.

File: subsys/fs/nvs/nvs.c [hunk 3]
```diff
@@ -715,6 +741,34 @@ static int nvs_startup(struct nvs_fs *fs)
 	}
 	if (rc) {
 		/* the sector after fs->ate_wrt is not empty */
+		bool gc_done_marker = false;
+		struct nvs_ate gc_done_ate;
+
+		addr = fs->ate_wra + ate_size;
```
Comment (nvlsianpu) [inline subsys/fs/nvs/nvs.c:747]: maybe a comment for emphasizing that following loop will scan the ATE area of the open sector (selected before) for GC DONE ATE

**Review by nvlsianpu — APPROVED** [review]
Thanks!
Patch is fine and logical.
Put just a few comment - answers are not needed for merge that.

File: subsys/fs/nvs/nvs.c [hunk 4]
```diff
@@ -715,6 +741,34 @@ static int nvs_startup(struct nvs_fs *fs)
...
+		while ((addr & ADDR_OFFS_MASK) < (fs->sector_size - ate_size)) {
+			rc = nvs_flash_ate_rd(fs, addr, &gc_done_ate);
+			if (rc) {
+				goto end;
+			}
+			if (nvs_ate_valid(fs, &gc_done_ate)) {
+				if ((gc_done_ate.id == 0xffff) &&
```
Comment (de-nordic) [inline subsys/fs/nvs/nvs.c:754]: That could be one if

File: subsys/fs/nvs/nvs.c (hunk 1 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c:599]: Thanks

File: subsys/fs/nvs/nvs.c (hunk 2 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c:496]: No real reason, if it would ever be needed to evaluate where the data stopped after gc it is stored.

File: subsys/fs/nvs/nvs.c (hunk 3 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c:749]: done

File: subsys/fs/nvs/nvs.c (hunk 4 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c]: done

**Review by de-nordic — APPROVED** [review]
Looks OK. Thanks!
