### PR TITLE
Bluetooth: Gatt settings fixes 2 electric boogaloo

### LINKED ISSUE #54770: Bluetooth: GATT: CCC and CF values written by privacy-disabled peer before bonding may be lost
**Describe the bug**
Values of CCC and CF may not be stored in non-volatile memory if a connected peer writes the values before it's bonded. If the peer then bonds and reboots without disconnection, the values written over GATT will be lost (they would not be stored in non-volatile memory). On the other hand if the same peer disconnects after bonding an before the reboot, these values are written to non-volatile memory.

**To Reproduce**

Used nRF Desktop application (applications/nrf_desktop) from nRF Connect SDK (https://github.com/nrfconnect/sdk-nrf).

1. Flash the nRF52840 DK with configuration that works as HID keyboard
  `west build -b nrf52840dk_nrf52840 --pristine -- -DCONF_FILE=prj_keyboard.conf`
  `west flash --erase`
2. Add logs when the following functions are called in `bluetooth/host/gatt.c`: `cf_write` (CF value GATT write), `cf_set` (CF value loaded from non-volatile memory).
3. Connect and bond with a Bluetooth Central.
   Make sure that the connected Central uses GATT Caching and triggers the CF GATT write **only before bonding** (otherwise the issue would not replicate; I replicated the problem with a Windows 10 Bluetooth host).
4. Reboot Zephyr device while the Bluetooth connection is still maintained.
5. Notice that CF value written for the bonded peer is lost (it's not loaded from settings).

If the peer is disconnected before the reboot, the value is stored during the disconnection (that works around the issue).

**Expected behavior**
CF and CCC values should be stored between connections for bonded peers.

**Impact**
Implementation of Zephyr's Bluetooth host is not consistent with the Bluetooth Core specification.

The Bluetooth Core specification  (v. 5.2, vol. 3, part G, section 3.3.3.3):
`The Client Characteristic Configuration descriptor value shall be persistent across connections for bonded devices.`

The Bluetooth Core specification  (v. 5.2, vol. 3, part G, section 7.2):
```
A Client Supported Features characteristic value shall exist for each connected client. For clients with a trusted relationship, the characteristic value shall be persistent across connections. For clients without a trusted relationship the characteristic value shall be set to the default value at each connection.
```

**Environment:**
Replicated on nRF Connnect SDK (https://github.com/nrfconnect/sdk-nrf; commit hash: `5be84b48937b0c42fb2b8d643ef452a25a693f17`).

**Additional context**
Similar issue was already spotted some time ago:
https://github.com/zephyrproject-rtos/zephyr/issues/39989

Seems that the introduced fix does not cover all of the edge cases:
https://github.com/zephyrproject-rtos/zephyr/pull/40006
The fix relied on storing the CF and CCC on `identity_resolved` callback which may actually not be triggered e.g. if the connected peer does not support privacy.

I would suggest to trigger an additional write to storage of the mentioned values also on `pairing_complete` from `bt_conn_auth_info_cb`  to prevent the issue.

### LINKED ISSUE #54813: Bluetooth: host: Implicit sc_indicate declaration when Service Changed is disabled
**Describe the bug**
Calling `sc_indicate` in `bt_gatt_encrypt_change` (`subsys/bluetooth/host/gatt.c`) may result in an implicit `sc_indicate` declaration build issue when Service Changed is disabled. We could ensure that the function would not be called if feature is not supported in the configuration.

**Environment (please complete the following information):**
Current main branch: `839050b9947a125af17ce454ece1891555cc3121`

### PR DESCRIPTION
**Pull request by jori-nordic**
See the commit messages. Mostly addresses #54770

Fixes #54770
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54813

### CODE REVIEW

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -878,6 +878,8 @@ static void db_hash_process(struct k_work *work)
 {
 	if (!atomic_test_bit(gatt_sc.flags, DB_HASH_VALID)) {
 		db_hash_gen();
+	} else {
+		return;
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:882]: If we generate the hash before settings are loaded (e.g. if a GATT service is registered before settings are loaded), we could accidentally skip setting `DB_HASH_LOAD_PROC` and performing the related operations needed after db_hash load from settings is completed.

Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:882]: btw. Shouldn't the condition below be `if (already_processed)` (without the negation) ?

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -1496,14 +1510,24 @@ void bt_gatt_init(void)
 #endif
 
 #if defined(CONFIG_BT_GATT_CLIENT) && defined(CONFIG_BT_SETTINGS) && defined(CONFIG_BT_SMP)
-	static struct bt_conn_cb gatt_conn_cb = {
-		.identity_resolved = bt_gatt_identity_resolved,
+	static struct bt_conn_auth_info_cb gatt_conn_auth_info_cb = {
+		.pairing_complete = bt_gatt_pairing_complete,
 	};
 
 	/* Register the gatt module for connection callbacks so it can be
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:1517]: `... for authentication info callbacks ...` ?

File: subsys/bluetooth/host/gatt.c [hunk 3]
```diff
@@ -1119,6 +1119,20 @@ static void bt_gatt_identity_resolved(struct bt_conn *conn, const bt_addr_le_t *
...
+	struct gatt_cf_cfg *cfg = find_cf_cfg_by_addr(conn->id, private_addr);
+
+	if (cfg) {
+		bt_addr_le_copy(&cfg->peer, id_addr);
+		bt_gatt_store_cf(conn->id, &conn->le.dst);
+	}
+}
+
+static void bt_gatt_pairing_complete(struct bt_conn *conn, bool bonded)
+{
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:1135]: Shouldn't we skip storing the values if not bonded?

File: subsys/bluetooth/host/gatt.c [hunk 4]
```diff
@@ -1119,6 +1119,20 @@ static void bt_gatt_identity_resolved(struct bt_conn *conn, const bt_addr_le_t *
 
 	bt_gatt_foreach_attr(0x0001, 0xffff, convert_to_id_on_match, &user_data);
 
+	/* Store the ccc */
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:1122]: We should make sure if the peer is bonded before storing data I think.

**Review by alwa-nordic — DISMISSED** [review]

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 4 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:1122]: The cf_cfg in RAM should be updated anyway

File: subsys/bluetooth/host/gatt.c [hunk 5]
```diff
@@ -1496,14 +1510,24 @@ void bt_gatt_init(void)
...
 	 * CF storage on pairing complete.
 	 */
+	bt_conn_auth_info_cb_register(&gatt_conn_auth_info_cb);
+
+	static struct bt_conn_cb gatt_conn_cb = {
+		.identity_resolved = bt_gatt_identity_resolved,
+	};
+
+	/* Also update the address of CCC or CF writes that happened before the
+	 * bond. Note that to increase security in the future, we might want to
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:1528]: `before the identity resolution`?

**Review by MarekPieta — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:882]: ugh yeah. shouldn't have refactored this I guess

**Review by jhedberg — DISMISSED** [review]

**Review by MarekPieta — APPROVED** [review]
One minor comment. Since it should not break anything, approved.

File: subsys/bluetooth/host/gatt.c [hunk 6]
```diff
@@ -1498,13 +1519,24 @@ void bt_gatt_init(void)
...
-	/* Register the gatt module for connection callbacks so it can be
-	 * notified when pairing has completed. This is used to enable CCC and
-	 * CF storage on pairing complete.
+	/* Also update the address of CCC or CF writes that happened before the
+	 * identity resolution. Note that to increase security in the future, we
+	 * might want to explicitly not do this and treat a bonded device as a
+	 * brand-new peer.
 	 */
 	bt_conn_cb_register(&gatt_conn_cb);
 #endif /* CONFIG_BT_GATT_CLIENT && CONFIG_BT_SETTINGS && CONFIG_BT_SMP */
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:1542]: We need to move the newly added functionality to use it also for cases when BT_GATT_CLIENT role is disabled. Otherwise it would have no effect at all for devices that do not support GATT Client role.

**Review by MarekPieta — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 6 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:1542]: I missed this one initially, I noticed it making an additional test other Bluetooth Central.

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 6 above)
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:1542]: Fixed here: https://github.com/jori-nordic/zephyr/pull/1

File: subsys/bluetooth/host/gatt.c [hunk 7]
```diff
@@ -876,7 +876,9 @@ static void sc_indicate(uint16_t start, uint16_t end);
 
 static void db_hash_process(struct k_work *work)
 {
-	if (!atomic_test_bit(gatt_sc.flags, DB_HASH_VALID)) {
+	bool new_hash = !atomic_test_bit(gatt_sc.flags, DB_HASH_VALID);
```
[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:879]: @jori-nordic, could you take a look at this one?

[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:879]: I think I've seen in my test that the run can be scheduled even if `DB_HASH_VALID` is set.

[the remark this answers is not in the document]
Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:879]: Discussed offline.
I think it was before hash was initially calculated after finished settings load. Still we can leave it as it is for now, because it should not break anything.

**Review by jhedberg — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 8]
```diff
@@ -5748,7 +5748,7 @@ void bt_gatt_encrypt_change(struct bt_conn *conn)
 
 	bt_gatt_foreach_attr(0x0001, 0xffff, update_ccc, &data);
 
-#if defined(CONFIG_BT_SETTINGS)
+#if defined(CONFIG_BT_SETTINGS) && defined(CONFIG_BT_GATT_SERVICE_CHANGED)
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c:5751]: Hi @jori-nordic
Seems that you (probably accidentally) cherry-picked the fix without comment alignment.

Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c:5751]: Discussed offline. Will be fixed separately

Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:5751]: will do that in a subsequent PR to not block the releases.

**Review by MarekPieta — APPROVED** [review]

**Comment by jori-nordic** [comment]
@stephanosio can this be merged?

**Comment by stephanosio** [comment]
@jori-nordic Is that last commit ("Bluetooth: host: Fix SC indication on encrypt change") necessary to fix #54770? If not, it should not be part of this series.

**Comment by jori-nordic** [comment]
> @jori-nordic Is that last commit ("Bluetooth: host: Fix SC indication on encrypt change") necessary to fix #54770? If not, it should not be part of this series.

It can be, yes, because the whole series is useless if we don't select a kconfig (`BT_GATT_CLIENT`) that is not selected for most applications.

**Review by stephanosio — APPROVED** [review]
Merging since this series is fixing a release blocker issue.
