### PR TITLE
lora: power consumption fixes

### LINKED ISSUE #31569: lora: sx126x: interrupt pin permanently enabled
**Describe the bug**
The sx126x driver leaves the `DIO1` interrupt permanently enabled, resulting in excess power consumption.
For nRF SoC's, this means the `GPIOTE` peripheral is permanently enabled, increasing current draw by ~15uA.
Per the datasheet (Table 8-3), DIO1 is not driven as an output in `Reset`, `Startup`, or `Sleep` modes.
We can therefore safely turn off the interrupt in sleep mode.

**Expected behavior**
`DIO1` pin should only have the interrupt enabled when it is actually needed (Not in sleep mode).

**Impact**
Minor, permanent +15uA to the current consumption of any application.

**Environment (please complete the following information):**
 - Zephyr v2.4

### PR DESCRIPTION
**Pull request by JordanYates**
Fixes two causes of excess power consumption.

The initial commit keeps the drivers power state variable in sync with the actual state, to ensure the wakeup function is only called once per exit from sleep.

The second commit disables the DIO1 interrupt when the modem is in sleep mode, fixes #31569

The third commit moves when the LoRaWAN MAC layer is notified of the public network state.
The new location in `lorawan_join` is the more correct location for the command, and reduces power consumption when `lorawan_start` and `lorawan_join` are separated in time.

### CODE REVIEW

**Review by Mani-Sadhasivam — CHANGES_REQUESTED** [review]

File: drivers/lora/sx126x.c [hunk 1]
```diff
@@ -336,6 +336,12 @@ void SX126xSetOperatingMode(RadioOperatingModes_t mode)
 		sx126x_set_tx_enable(0);
 		break;
 	}
+
+	/* Disable the DIO1 interrupt in sleep mode to save power */
+	if (mode == MODE_SLEEP) {
```
[the remark this answers is not in the document]
Comment (JordanYates) [reply drivers/lora/sx126x.c:341]: The default case is also catching `MODE_STDBY_RC` and `MODE_STDBY_XOSC`, which shouldn't disable DIO1.
I can do the following if it is preferable:
```
case MODE_SLEEP:
    gpio_pin_interrupt_configure(...);
    __fallthrough:
default:
    sx126x_set_rx_enable(0);
    sx126x_set_tx_enable(0);
```

File: drivers/lora/sx126x.c [hunk 2]
```diff
@@ -385,6 +385,8 @@ void SX126xReset(void)
 	k_sleep(K_MSEC(20));
 	gpio_pin_set(dev_data.reset, GPIO_RESET_PIN, 0);
 	k_sleep(K_MSEC(10));
+	/* Device transitions to standby on reset */
+	dev_data.mode = MODE_STDBY_RC;
```
[the remark this answers is not in the document]
Comment (JordanYates) [reply drivers/lora/sx126x.c:395]: In the future other places may call the reset function. Why shouldn't we update the state at the location that the state is being changed?

File: drivers/lora/sx126x.c [hunk 3]
```diff
@@ -500,7 +507,6 @@ static int sx126x_lora_init(const struct device *dev)
 	dev_data.spi_cfg.frequency = DT_INST_PROP(0, spi_max_frequency);
 	dev_data.spi_cfg.slave = DT_INST_REG_ADDR(0);
 
-	dev_data.mode = MODE_SLEEP;
```
[the remark this answers is not in the document]
Comment (JordanYates) [reply drivers/lora/sx126x.c:503]: `sx12xx_init` calls `Radio.Init` which results in `dev_data.mode` being setup correctly via `SX126xInit`.
While we could manually set `dev_data.mode` after the init call, there is no guarantee that we are actually setting the value to the correct mode given the calls `Radio.Init` makes.

Unfortunately it isn't obvious that this is the case because of the call structure, or even that it is initialized at all.
Perhaps we just need a comment above `sx12xx_init` stating that it correctly sets up the variable?

[the remark this answers is not in the document]
Comment (JordanYates) [reply drivers/lora/sx126x.c:503]: As justification for why this shouldn't be manually set, the current value is actually incorrect for this modem until #31568 is merged.

File: drivers/lora/sx126x.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (Mani-Sadhasivam) [reply drivers/lora/sx126x.c:341]: > The default case is also catching `MODE_STDBY_RC` and `MODE_STDBY_XOSC`, which shouldn't disable DIO1.

I suggested moving `if (mode == MODE_SLEEP)` under `default` case but what you've proposed above also looks sane.

File: drivers/lora/sx126x.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (Mani-Sadhasivam) [reply drivers/lora/sx126x.c:395]: After reading your below explanation, I think it makes sense to keep it here.

File: drivers/lora/sx126x.c [hunk 4]
```diff
@@ -331,6 +331,11 @@ void SX126xSetOperatingMode(RadioOperatingModes_t mode)
 		sx126x_set_rx_enable(1);
 		break;
 
+	case MODE_SLEEP:
+		/* Additionally disable the DIO1 interrupt to save power */
```
Comment (mniestroj) [inline drivers/lora/sx126x.c:335]: Is it common to other platforms (other than Nordic) that gpio interrupt consumes constant power?

Comment (JordanYates) [reply drivers/lora/sx126x.c:335]: I can't speak for all platforms, but it wasn't something that needed to be managed on TI or Silicon Labs microcontrollers.
Are there platforms where the enabling/disabling of the interrupt is a problem?

Comment (mniestroj) [reply drivers/lora/sx126x.c:335]: > Are there platforms where the enabling/disabling of the interrupt is a problem?

No, I am not aware of any. It just adds a bit overhead when entering/exiting sleep mode. I just haven't seen other drivers doing similar stuff, so I was wondering whether this enable/disable interrupts is just a workaround for single platform.

On the other hand the LoRa radio will rarely (no more than once a second) switch between modes, so the "overhead" isn't significant.

Comment (JordanYates) [reply drivers/lora/sx126x.c:335]: > I just haven't seen other drivers doing similar stuff, so I was wondering whether this enable/disable interrupts is just a workaround for single platform.

Because my hardware designs are Nordic based, all of my out-of-tree drivers with interrupts do this in some form or another. If we're stretching, this also helps in the case where you have N available interrupt lines, N+1 GPIO's that want to be interrupts at some point, and only some subset of drivers enabled at once.

The statement regarding low overhead applies to all the other drivers as well, you generally only care about the idle case. Saving 15uA when your base consumption is 5uA is huge. Saving 15uA when the sensor is using 2mA is irrelevant.

Comment (mniestroj) [reply drivers/lora/sx126x.c:335]: >Because my hardware designs are Nordic based, all of my out-of-tree drivers with interrupts do this in some form or another.

AFAIK, not all Nordic MCUs have this issue. For example nRF52832 is affected and nRF52840 is not. My only concern here is that enabling/disabling interrupts in runtime is needed for small part of MCUs. My approach with reducing power was to use gpio level interrupts, so that the "faulty" (according to errata) GPIOTE mechanism is not used. Last week I've developed #31823, so you can take a look there.

>If we're stretching, this also helps in the case where you have N available interrupt lines, N+1 GPIO's that want to be interrupts at some point, and only some subset of drivers enabled at once.

Makes sense.

>The statement regarding low overhead applies to all the other drivers as well, you generally only care about the idle case. Saving 15uA when your base consumption is 5uA is huge. Saving 15uA when the sensor is using 2mA is irrelevant.

I was referring to "time/processing overhead" when basically before/after each communication over LoRa you need to setup and cleanup GPIO interrupts. The "power overhead" that you describe is huge, I agree.

Comment (JordanYates) [reply drivers/lora/sx126x.c:335]: > nRF52840 is not

It definitely is, you can see this in section 5.2.1.1 of the datasheet.
```
System ON, full 256 kB RAM retention, wake on any event: 2.35uA
System ON, full 256 kB RAM retention, wake on GPIOTE input: 17.37uA
```

>I was referring to "time/processing overhead"

So was I, just from the opposite angle. My point was that you are only transitioning between these modes rarely, so spending a few clock cycles to save significant power is worth it.

Comment (JordanYates) [reply drivers/lora/sx126x.c:335]: Re #31823, I can see that being an alternative. You are trading cycles at setup/teardown for cycles during every interrupt however, which is not always a good tradeoff.
The question IMO is whether drivers should be cleaning up resources that they are not currently using.

Comment (mniestroj) [reply drivers/lora/sx126x.c:335]: Thanks for pointing out that nrf52840 is affected as well. Seems like this issue got upgraded from bug to a feature. Quite confusing, because I was only looking at errata and didn't find it there.

>Re #31823, I can see that being an alternative. You are trading cycles at setup/teardown for cycles during every interrupt however, which is not always a good tradeoff.

If that would work (not sure yet, still under review), then the major advantage would be one place where that would be handled, instead of modifying many drivers that depend on the edge interrupt feature.

Thanks for all explanation in this thread and also for patches!

**Review by mniestroj — APPROVED** [review]

File: drivers/lora/sx126x.c (hunk 4 above)
Comment (JordanYates) [reply drivers/lora/sx126x.c:335]: > Seems like this issue got upgraded from bug to a feature

It feels like the GPIOTE using power when enabled is part of the hardware design (otherwise why would you have the PORT events). If its part of the design, then it's not an errata.

> Thanks for all explanation in this thread and also for patches!

No problem, the fewer commits I have to keep reapplying on my fork each release the better!

**Comment by nashif** [comment]
@Mani-Sadhasivam  can you please re-review?

**Review by Mani-Sadhasivam — APPROVED** [review]
