### PR TITLE
drivers: spi: Use timeout for transfer completion

### LINKED ISSUE #33192: LoRaWAN - Application fails to start if module is not powered
LoRaWAN - Application fails to start if module is not powered
------

**Describe the bug**
When a LoRa module is attached, LoRaWAN (and other associated switches in proj.conf) are enabled, but power is not enabled to the LoRa module, the main thread fails to run the user code (that inside main() ). It also does not print the banner (*** Booting Zephyr OS build zephyr-v2.4.0-3155-gc19c6fb438b9  ***). Note, if the module is not attached, the system will start normally (even with proj.conf switches saying LoRaWAN is enabled). 

**To Reproduce**
Connect LoRa module to MCU but don't power on boot of MCU.

**Expected behavior**
It should error, not catastrophoic fail. The initilisation should really be done in application code, not via SYS_INIT() as this scenario of power switching external devices (LoRa module in this case) would be very common, especially for devices where very low power draw in standby is desired.

**Impact**
Catastrophoic in terms of a data logger which could have a failed transciever but can still log to memory. Wasted power usage on very low power systems if required to leave module always powered.

**Logs and console output**
No Console output. I enabled:
CONFIG_LOG=y
CONFIG_LOG_MAX_LEVEL=4
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_LOG_PRINTK=y
CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=0
CONFIG_COVERAGE=n

yet got no logging on the serial interface (I presume there is something I missed).

**Environment (please complete the following information):**
 - Windows 10
 - Zephyr with gnu-arm-embedded
 - zephyr-v2.4.0-3155-gc19c6fb438b9

**Additional context**
In my application, I'm using LoRa on a battery system which we're hoping to last 5-10 years on battery (with battery charging to extend battery life). As such we need to minimise battery usage as much as possible. I'm using an nrf52840dk with a SX1276MB1LAS shield and another board between them. This extra board, one of it's functions is to switch power rails. These rails default to being off, so when the MCU is in deep sleep (system off), the rails are disabled and thus don't waste power. The system is woken up from an external RTC alarm interrupt.

I've tested the behaviour of the bug over multiple reboots changing the power status with a switch. The switch allows 3v3 on boot to the SX1276 module or has the power controlled by the application code (which is the desired behaviour now, and requried for the final design).

Other notes:
The shell boots fine, and I can see the "main" thread is running:

Scheduler: 4450839 since last call
Threads:
 0x20000e10 sysworkq
        options: 0x0, priority: -1 timeout: 536874636
        state: pending
        stack size 1024, unused 904, usage 120 / 1024 (11 %)

*0x20000bd0 shell_uart
        options: 0x0, priority: 14 timeout: 536874060
        state: queued
        stack size 2048, unused 1168, usage 880 / 2048 (42 %)

 0x20000b18 logging
        options: 0x0, priority: 14 timeout: 536873876
        state: pending
        stack size 768, unused 656, usage 112 / 768 (14 %)

 0x20000c88 idle 00
        options: 0x1, priority: 15 timeout: 536874244
        state:
        stack size 320, unused 248, usage 72 / 320 (22 %)

 0x20000d40 main
        options: 0x1, priority: 0 timeout: 536874428
        state: pending
        stack size 1024, unused 760, usage 264 / 1024 (25 %)

LoRa kconfigs enabled are:
CONFIG_SPI=y
CONFIG_SPI_1=y
CONFIG_LORA=y
CONFIG_LORA_SX12XX=y
CONFIG_LORAWAN=y
CONFIG_LORAMAC_REGION_AS923=y

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
Instead of waiting forever for the SPI transfer to complete, let's use
a timeout value and bail out if elapsed. The timeout value logic is,

xfer_len/frequency + 200 ms (tolerance)

Fixes: #33192

Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by Mani-Sadhasivam** [comment]
The timeout value logic is taken from Linux kernel: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/spi/spi.c#n1125

File: drivers/spi/spi_context.h [hunk 1]
```diff
@@ -112,13 +112,29 @@ static inline void spi_context_release(struct spi_context *ctx, int status)
 static inline int spi_context_wait_for_completion(struct spi_context *ctx)
 {
 	int status = 0;
+	uint64_t ms;
+
+	ms = MAX(ctx->tx_len, ctx->rx_len) * 8 * 1000 / ctx->config->frequency;
+	ms += 200; /* tolerance */
```
Comment (jfischer-no) [inline drivers/spi/spi_context.h:118]: Why 200ms, why hard-coded and why is it not optional that this change does not break anything?

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_context.h (hunk 1 above)
Comment (Mani-Sadhasivam) [reply drivers/spi/spi_context.h:118]: 200ms is somewhat the high tolerance level which could be sufficient for most of the SPI controllers available in market. This is what the Linux kernel is using today and I took inspiration from it:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/spi/spi.c?id=833bfade96561216aa2129516a5926a0326860a2

For sure this change won't break anything. If it does then most likely we need to increase the tolerance level.

Comment (jfischer-no) [reply drivers/spi/spi_context.h:118]: > For sure this change won't break anything.

really?, you change behavior of each SPI driver,  and use hard-coded 200ms value.

Comment (Mani-Sadhasivam) [reply drivers/spi/spi_context.h:118]: Yes, this impacts every SPI driver but it won't cause any issue IMO as we have this same logic working in Linux kernel for years.

Comment (Mani-Sadhasivam) [reply drivers/spi/spi_context.h:118]: @jfischer-no Moreover the current implementation of waiting forever won't work in all cases where the slave is powered down (see linked issue). So the timeout logic makes use of the transfer speed plus 200ms tolerance value.

File: drivers/spi/spi_context.h [hunk 2]
```diff
@@ -112,13 +112,29 @@ static inline void spi_context_release(struct spi_context *ctx, int status)
...
+	if (ms > UINT_MAX)
+		ms = UINT_MAX;
+
 #ifdef CONFIG_SPI_ASYNC
 	if (!ctx->asynchronous) {
-		k_sem_take(&ctx->sync, K_FOREVER);
+		if (k_sem_take(&ctx->sync, K_MSEC(ms))) {
+			LOG_ERR("Timeout waiting for transfer complete");
+			status = -ETIMEDOUT;
+			goto out;
```
Comment (gmarull) [inline drivers/spi/spi_context.h:128]: there is no need for a `goto` unless you need to perform some sort of cleanup.

File: drivers/spi/spi_context.h [hunk 3]
```diff
@@ -112,13 +112,29 @@ static inline void spi_context_release(struct spi_context *ctx, int status)
...
+		}
 		status = ctx->sync_status;
 	}
 #else
-	k_sem_take(&ctx->sync, K_FOREVER);
+	if (k_sem_take(&ctx->sync, K_MSEC(ms))) {
+		LOG_ERR("Timeout waiting for transfer complete");
+		status = -ETIMEDOUT;
+		goto out;
```
Comment (gmarull) [inline drivers/spi/spi_context.h:136]: same here

File: drivers/spi/spi_context.h (hunk 1 above)
Comment (gmarull) [inline drivers/spi/spi_context.h:118]: A few comments:

- I think this change should be justified better. For example, a case where it solves a problem
- Tolerance should not be hardcoded, probably a Kconfig value at least.
- `ms` variable name does not help understanding its purpose.
- `config->frequency` may not necessarily contain the actual SPI frequency (more reason to make tolerance not hardcoded)

**Review by gmarull — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_context.h (hunk 1 above)
Comment (henrikbrixandersen) [reply drivers/spi/spi_context.h:118]: > * I think this change should be justified better. For example, a case where it solves a problem

You do not think #33192 is justification enough?

> * Tolerance should not be hardcoded, probably a Kconfig value at least.

I agree. Either Kconfig or spi-controller.yaml binding, so the driver can fill it out in `struct spi_context`.

> * `ms` variable name does not help understanding its purpose.
> * `config->frequency` may not necessarily contain the actual SPI frequency (more reason to make tolerance not hardcoded)

When would `config->frequency` not contain the actual SPI frequency?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Please avoid hardcoding the tolerance (I know it works for the Linux kernel, but generally we should let the user be in control, at least when such a timeout is not mandated by the specification/standard).

**Comment by Mani-Sadhasivam** [comment]
@MaureenHelm Sorry for not being active here... Bit occupied with official work. Will get to this PR on the weekend.

**Comment by Mani-Sadhasivam** [comment]
@MaureenHelm @henrikbrixandersen Updated the PR to use Kconfig symbol for tolerance.

**Review by jfischer-no — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

File: drivers/spi/spi_context.h [hunk 4]
```diff
@@ -112,13 +112,27 @@ static inline void spi_context_release(struct spi_context *ctx, int status)
 static inline int spi_context_wait_for_completion(struct spi_context *ctx)
 {
 	int status = 0;
+	uint64_t ms;
```
Comment (gmarull) [inline drivers/spi/spi_context.h:115]: do we really need to store the result in `uint64_t`? Sounds like the results should fit in `uint32_t`, meaning clamping to `UINT_MAX` could even be avoided.

File: drivers/spi/spi_context.h [hunk 5]
```diff
@@ -112,13 +112,27 @@ static inline void spi_context_release(struct spi_context *ctx, int status)
...
+	if (ms > UINT_MAX)
+		ms = UINT_MAX;
+
 #ifdef CONFIG_SPI_ASYNC
 	if (!ctx->asynchronous) {
-		k_sem_take(&ctx->sync, K_FOREVER);
+		if (k_sem_take(&ctx->sync, K_MSEC(ms))) {
+			LOG_ERR("Timeout waiting for transfer complete");
+			return -ETIMEDOUT;
+		}
```
Comment (mnkp) [inline drivers/spi/spi_context.h:128]: It would be cleaner if we passed on the value returned by `k_sem_take` and not fixed `-ETIMEDOUT`.

File: drivers/spi/spi_context.h (hunk 4 above)
Comment (mnkp) [inline drivers/spi/spi_context.h:115]: As @gmarull has mentioned `ms` is not a very good name. What about `timeout_ms`?

File: drivers/spi/spi_context.h (hunk 5 above)
Comment (mnkp) [reply drivers/spi/spi_context.h:128]: Actually, I'm not sure about this anymore. Maybe `-ETIMEDOUT` is a better choice.

**Review by gmarull — APPROVED** [review]

**Review by tbursztyka — DISMISSED** [review]
Though I agree that this feature is missing on SPI, it's in fact missing almost everywhere.

See #22941

I am not willing to add it only for SPI atm.

**Comment by henrikbrixandersen** [comment]
> Though I agree that this feature is missing on SPI, it's in fact missing almost everywhere.
> 
> See #22941
> 
> I am not willing to add it only for SPI atm.

I think there is a huge difference between a generic way of timing out on a syscall and a bus timeout where we already have all the information in the syscall to do a proper timeout. I don't think you not "being will to to add it only for SPI" is a valid reason for blocking this feature.

@carlescufi I think we should discuss this at the first API meeting after the summer holidays.

**Comment by carlescufi** [comment]
API meeting

- The reference to [#22941](https://github.com/zephyrproject-rtos/zephyr/issues/22941) implies that there will be work done on it in the near future, which is unlikely, and in the meantime we need to have a solution for this problem
- The Kconfig timeout should probably be configurable to disable it entirely (K_FOREVER)

**Comment by tbursztyka** [comment]
@carlescufi unblocked the PR.
