### PR TITLE
nRF: Add system clock stability policy

### LINKED ISSUE #22758: RFC: Require system clock stability on startup
Currently, at least on Nordic, the system timer startup starts an underlying clock, but then starts the timer and continues with system startup without waiting for that clock to stabilize.  In some cases this may take several hundred milliseconds, with no guarantee on how the clock will behave during stabilization.

It's unclear whether this is a bug, or is allowed as an option for under-defined behavior.

I propose that z_clock_driver_init() be expected to wait internally until the clock has stabilized.  This may require support from the clock control API to signal that stability has been reached.

### LINKED ISSUE #26280: test_kernel_systicks from tests/portability/cmsis_rtos_v1 fails on nrf platforms
**Describe the bug**
The test case _test_kernel_systicks_ from tests/portability/cmsis_rtos_v1 test suite fails consistently at nrf platforms: (nrf52dk_nrf52832, nrf52840dk_nrf52840 and nrf9160dk_nrf9160)

**To Reproduce**
1. run in zephyr dir ./scripts/sanitycheck --testcase-root ./tests/portability/cmsis_rtos_v1 --device-testing -p nrf52dk_nrf52832 -v -v --device-serial /dev/ttyACM0
2. See error

**Expected behavior**
The test case test_kernel_systicks passes on nrf platforms

**Impact**
not clear

**Screenshots or console output**
```
DEBUG   - DEVICE: Assertion failed at CMAKE_SOURCE_DIR/src/kernel_apis.c:58: test_kernel_systick: (diff <= max && diff >= min is false)
DEBUG   - DEVICE: start 991 stop 34848 (diff 1033233) wait 1000000
DEBUG   - DEVICE: 
DEBUG   - DEVICE: FAIL - test_kernel_systick
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: starting test - test_thread_apis
DEBUG   - DEVICE: PASS - test_thread_apis
DEBUG   - DEVICE: ===================================================================
[...]
DEBUG   - DEVICE: Test suite test_cmsis_apis failed.
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
INFO    - 1/1 nrf52dk_nrf52832          tests/portability/cmsis_rtos_v1/portability.cmsis_rtos_v1 FAILED Failed (device 15.061s)
ERROR   - see: /home/maciej/zephyrproject2/zephyr/sanity-out/nrf52dk_nrf52832/tests/portability/cmsis_rtos_v1/portability.cmsis_rtos_v1/handler.log

INFO    - 0 of 1 tests passed (0.00%), 1 failed, 0 skipped with 0 warnings in 20.19 seconds
INFO    - In total 1 test cases were executed on 1 out of total 255 platforms (0.39%)
INFO    - 1 tests executed on platforms, 0 tests were only built.

Hardware distribution summary:

| Board            | ID   |   Counter |
|------------------|------|-----------|
| nrf52dk_nrf52832 |      |         1 |
```

**Environment:**
 - OS:  Linux, 
 - Toolchain Zephyr SDK
 - Commit SHA b5764f9902

**Additional context**
The test seems to pass on other platforms (https://testing.zephyrproject.org/daily_tests/v2.3.0-rc2/report/index.html). The value for `diff` supposed to be between `min 990000` and `max 1010000`
 From running it 3 times per platform I've got diff eq. to:
nrf52dk_nrf52832: 1032470, 1033355 and 1033843
nrf52840dk_nrf52840: 981140, 980743 and 981384 
nrf9160dk_nrf9160: 1127929, 1121948 and 1121459

### PR DESCRIPTION
**Pull request by nordic-krch**
Pull request adds clock stability policy configuration to the system clock (see #22758) and adds support to Nordic platform. Additionally, spin waiting for stable or available clock has been reworked for Nordic to allow going to idle while waiting for clock readiness (it can take up to 250 ms). Added test dedicated for Nordic platforms which validates correctness of behavior for each configuration against various clock sources.

Fixes #22758.
Fixes #26280.

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
No complaints about the code.  But is this really a good candidate for a global API?  Right now it's just the one platform that needs to care about this.  Maybe we should start this out as an internal thing with the nRF timer driver and promote the kconfig API to a global one only later?

I guess my criteria for this is: if we add a kconfig value to the core kernel, and it's never inspected by or modified by any of the code or tests dealing with the core kernel, it shouldn't be a core kernel feature. ... ?

**Comment by nordic-krch** [comment]
Seems to me that there is also sam0_rtc driver which seems to currently wait for the clock:

https://github.com/zephyrproject-rtos/zephyr/blob/e227f5ba13c00ff5269c09dd3a3af791d984ed86/drivers/timer/sam0_rtc_timer.c#L191

Not sure who is maintaining it.

File: drivers/clock_control/nrf_power_clock.c [hunk 1]
```diff
@@ -459,18 +471,53 @@ static void lfclk_spinwait(nrf_clock_lfclk_t t)
...
+	int key = irq_lock();
 
 	while (!(nrf_clock_is_running(NRF_CLOCK, d, (void *)&type)
 		 && (type == t))) {
-		/* empty */
-		/* k_cpu_idle(); */
+		/* Synth source start is almost instant and LFCLKSTARTED may
+		 * happen before calling idle. That would lead to deadlock.
+		 */
+		if (!IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_SYNTH)) {
```
Comment (pabigot) [inline drivers/clock_control/nrf_power_clock.c:485]: I see the goal here, but `z_clock_driver_init()` will invoke `z_nrf_clock_control_lf_on()` which on its first entry will use the onoff manager to trigger `TASK_LFCLKSTART`.  All that is before interrupts are locked on entry to this function.

There is a typical 1 ms startup time for this on nRF52840, but it does seem like the ISR may have already processed LFCLKSTARTED before the lock is taken, so deadlock is still possible.

**Review by pabigot — COMMENTED** [review]
One question about whether `EVENT_LFCLKSTART` could be handled by the ISR and cleared before the spinwait that's looking for it.  E.g. if something else like a bootloader had done some clock configuration so it could be triggered faster than normal.

I like the two-phase startup for LFXO to catch the distinct stages.

File: drivers/clock_control/nrf_power_clock.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c:485]: > There is a typical 1 ms startup time for this on nRF52840, but it does seem like the ISR may have already processed LFCLKSTARTED before the lock is taken, so deadlock is still possible.

Interrupts are locked at this point or startup. I call `irq_lock` just to get `key` which is required by `k_cpu_atomic_idle` and `irq_unlock` for consistency.

Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c:485]: i will see if i can do something to support call of `z_nrf_clock_control_lf_on` without that assumption.

Comment (pabigot) [reply drivers/clock_control/nrf_power_clock.c:486]: > Interrupts are locked at this point of startup.

Could you expand on this?

`z_clock_driver_init()` at PRE_KERNEL_2/CONFIG_SYSTEM_CLOCK_INIT_PRIORITY invokes
`z_nrf_clock_control_lf_on()` invokes
`onoff_request()` invokes
`lfclk_start()` triggers NRF_CLOCK_TASK_LFCLKSTART then
`z_nrf_clock_control_lf_on()` invokes `lfclk_spinwait()`

Nothing on that path appears to disables interrupts, so theoretically the `EVENT_LFCLKSTARTED` could have been cleared by `clock_event_check_and_clean()` in `nrf_power_clock_isr()` before the subsequent `lfclk_spinwait()` gets control and does disable interrupt, expecting to be able to see that event itself.

What am I missing?

**Comment by carlescufi** [comment]
DNM until #27422 is merged

**Review by pabigot — DISMISSED** [review]
Switching from comment to block because we've lost momentum and I don't want this concern to be missed.

https://github.com/zephyrproject-rtos/zephyr/pull/27398#discussion_r468035499

File: drivers/clock_control/nrf_power_clock.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: > Nothing on that path appears to disables interrupts

driver initialization is called from `z_cstart` which has interrupts disabled.

I have added support to spinwaiting from thread context and added test for that.

**Comment by nordic-krch** [comment]
Upmerged since #27422 got merged. Removed DNM.

**Comment by pabigot** [comment]
Should this be tagged for 2.4.0?  @carlescufi

File: drivers/clock_control/clock_control_nrf.c [hunk 2]
```diff
@@ -427,17 +426,64 @@ static void lfclk_spinwait(nrf_clock_lfclk_t t)
 {
 	nrf_clock_domain_t d = NRF_CLOCK_DOMAIN_LFCLK;
 	nrf_clock_lfclk_t type;
+	static const bool lfxo_target =
+		    IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL) |
```
Comment (pabigot) [inline drivers/clock_control/clock_control_nrf.c:430]: These should be `||` since the operands and result are essentially boolean.

Same in other locations (`isr_mode` next definition)

File: tests/drivers/clock_control/nrf_lf_clock_start/src/main.c [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+static bool on;
+static uint32_t rtc_cnt;
+
+static void xtal_check(bool on, nrf_clock_lfclk_t type)
+{
+	if (IS_ENABLED(CONFIG_SYSTEM_CLOCK_NO_WAIT)) {
+		zassert_false(on, "Clock should be off");
+	} else if (IS_ENABLED(CONFIG_SYSTEM_CLOCK_WAIT_FOR_AVAILABILITY)) {
+		bool is_running =
+			rtc_cnt | (on && (type == NRF_CLOCK_LFCLK_RC));
```
Comment (pabigot) [inline tests/drivers/clock_control/nrf_lf_clock_start/src/main.c:20]: so for essential type this should be `(rtc_cnt != 0) || (on ...`

File: tests/drivers/clock_control/nrf_lf_clock_start/src/main.c [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+{
+	/* Do clock state read as early as possible. When RC is already running
+	 * and XTAL has been started then LFSRCSTAT register content might be
+	 * not valid, in that case read system clock to check if it has
+	 * progressed.
+	 */
+	on = nrf_clock_is_running(NRF_CLOCK, NRF_CLOCK_DOMAIN_LFCLK, &type);
+	k_busy_wait(100);
+	rtc_cnt = k_cycle_get_32();
+
```
Comment (pabigot) [inline tests/drivers/clock_control/nrf_lf_clock_start/src/main.c:100]: Would you be open to this patch at this point in the code:

```
--- a/tests/drivers/clock_control/nrf_lf_clock_start/src/main.c
+++ b/tests/drivers/clock_control/nrf_lf_clock_start/src/main.c
@@ -98,6 +98,18 @@ void test_main(void)
        k_busy_wait(100);
        rtc_cnt = k_cycle_get_32();
 
+       TC_PRINT("CLOCK_CONTROL_NRF_K32SRC=%s\n",
+                IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC) ? "RC"
+                : IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_SYNTH) ? "SYNTH"
+                : IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL) ? "XTAL"
+                : "???");
+       TC_PRINT("SYSTEM_CLOCK_NO_WAIT=%c\n",
+                IS_ENABLED(CONFIG_SYSTEM_CLOCK_NO_WAIT) ? 'y' : 'n');
+       TC_PRINT("SYSTEM_CLOCK_WAIT_FOR_AVAILABILITY=%c\n",
+                IS_ENABLED(CONFIG_SYSTEM_CLOCK_WAIT_FOR_AVAILABILITY) ? 'y' : 'n');
+       TC_PRINT("SYSTEM_CLOCK_WAIT_FOR_STABILITY=%c\n",
+                IS_ENABLED(CONFIG_SYSTEM_CLOCK_WAIT_FOR_STABILITY) ? 'y' : 'n');
+
        ztest_test_suite(test_nrf_lf_clock_start,
                ztest_unit_test(test_clock_check),
                ztest_unit_test(test_wait_in_thread)
```
This produces the following in the `handler.log` which is helpful when trying to correlate the build tags with the configuration:
```
CLOCK_CONTROL_NRF_K32SRC=SYNTH
SYSTEM_CLOCK_NO_WAIT=n
SYSTEM_CLOCK_WAIT_FOR_AVAILABILITY=n
SYSTEM_CLOCK_WAIT_FOR_STABILITY=y
Running test suite test_nrf_lf_clock_start
```

**Review by pabigot — CHANGES_REQUESTED** [review]
I'd like to see the logical operators used for boolean expressions, since we're going that way for MISRA.  That's the only request changes.  Otherwise this looks fine by inspection.

I get failures on `drivers.clock.nrf_lf_clock_start_xtal_*` variants on `nrf52840dk_nrf52840` running sanitycheck with `--device-testing`.  For `*=available` the failure mode is that it appears that configuration doesn't output anything so the test times out, and it always fails under sanity check but passes manually.  This may be a race condition specific to the test infrastructure.

I got one failure with `*=no_wait`:
```
tirzah[765]$ cat sanity-out/nrf52840dk_nrf52840/tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_xtal_no_wait/handler.log
CLOCK_CONTROL_NRF_K32SRC=XTAL
SYSTEM_CLOCK_NO_WAIT=y
SYSTEM_CLOCK_WAIT_FOR_AVAILABILITY=n
SYSTEM_CLOCK_WAIT_FOR_STABILITY=n
Running test suite test_nrf_lf_clock_start
===================================================================
START - test_clock_check
PASS - test_clock_check
===================================================================
O	MhFE: SPSEL in thread mode does not indicate PSP
ASSERTION FAIL [esf != ((void *)0)] @ WEST_TOPDIR/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:955
ESF could not be retrieved successfully. Shall never occur.
E: ***** HARD FAULT *****
E:   Fault escalation (see below)
E: ***** BUS FAULT *****
E:   Imprecise data bus error
E: r0/a1:  0x00000004  r1/a2:  0x000003bb  r2/a3:  0x00000001
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00001d71
E:  xpsr:  0x61000005
E: Faulting instruction address (r15/pc): 0x00005880
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Fault during interrupt handling
E: Current thread: 0x20000240 (main)
E: Halting system
```

File: tests/drivers/clock_control/nrf_lf_clock_start/src/main.c (hunk 4 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/nrf_lf_clock_start/src/main.c:100]: sure, added.

File: tests/drivers/clock_control/nrf_lf_clock_start/src/main.c (hunk 3 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/nrf_lf_clock_start/src/main.c]: done

File: drivers/clock_control/clock_control_nrf.c (hunk 2 above)
Comment (nordic-krch) [reply drivers/clock_control/clock_control_nrf.c]: done

**Comment by nordic-krch** [comment]
> I get failures

@pabigot i see no such failures. Is it always? I tried multiple times on 2 nrf52840dk boards and see no failure.

**Comment by pabigot** [comment]
Pretty consistent, yes:
```
tirzah[973]$ sanitycheck --device-testing --hardware-map test.yml -T tests/drivers/clock_control/nrf_lf_clock_start/
Renaming output directory to /mnt/nordic/zp/zephyr/sanity-out.1
INFO    - JOBS: 32
INFO    - Building initial testcase list...
INFO    - 18 test configurations selected, 0 configurations discarded due to filters.

Device testing on:

| Platform            |           ID | Serial device   |
|---------------------|--------------|-----------------|
| nrf52840dk_nrf52840 | 000683290670 | /dev/ttyACM0    |
| nrf52dk_nrf52832    | 000682687522 | /dev/ttyACM1    |

INFO    - Adding tasks to the queue...
INFO    - Total complete:    2/  18  11%  skipped:    0, failed:    0
ERROR   - nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_xtal_stable FAILED: Timeout
ERROR   - see: /mnt/nordic/zp/zephyr/sanity-out/nrf52dk_nrf52832/tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_xtal_stable/build.log
INFO    - Total complete:   18/  18  100%  skipped:    0, failed:    1
INFO    - 17 of 18 tests passed (94.44%), 1 failed, 0 skipped with 0 warnings in 95.98 seconds
INFO    - In total 72 test cases were executed on 2 out of total 283 platforms (0.71%)
INFO    - 18 tests executed on platforms, 0 tests were only built.

Hardware distribution summary:

| Board               |           ID |   Counter |
|---------------------|--------------|-----------|
| nrf52dk_nrf52832    | 000682687522 |         9 |
| nrf52840dk_nrf52840 | 000683290670 |         9 |
```

`drivers.clock.nrf_lf_clock_start_xtal_stable` and  `drivers.clock.nrf_lf_clock_start_xtal_available` both observed to fail.  When both are run in the same test it appears that only one fails.  The failure mode is that the `handler.log` contains no data.

So there's a reasonable chance it's a failure in the test infrastructure.

File: drivers/clock_control/clock_control_nrf.c [hunk 5]
```diff
@@ -429,16 +428,64 @@ static void lfclk_spinwait(nrf_clock_lfclk_t t)
 {
 	nrf_clock_domain_t d = NRF_CLOCK_DOMAIN_LFCLK;
 	nrf_clock_lfclk_t type;
+	static const bool lfxo_target =
+		    IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL) ||
+		    IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_EXT_LOW_SWING) ||
+		    IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING);
+	bool isr_mode = k_is_in_isr() | k_is_pre_kernel();
```
Comment (pabigot) [inline drivers/clock_control/clock_control_nrf.c:435]: `||`

**Review by pabigot — CHANGES_REQUESTED** [review]
One missed case, otherwise looks good.

File: drivers/clock_control/clock_control_nrf.c (hunk 5 above)
Comment (nordic-krch) [reply drivers/clock_control/clock_control_nrf.c]: done

**Comment by nordic-krch** [comment]
@pabigot i run it with following command
```
sanitycheck --device-testing --device-serial /dev/ttyACM0 -p nrf52840dk_nrf52840 -T tests/drivers/clock_control/nrf_lf_clock_start/
```

**Review by pabigot — APPROVED** [review]

**Comment by pabigot** [comment]
Interesting.  My hardware YAML files used `jlink` as the runner.  Switching to `nrfjprog` it passes, as it does with the command you provided.

File: tests/drivers/clock_control/nrf_lf_clock_start/testcase.yaml [hunk 6]
```diff
@@ -0,0 +1,75 @@
+tests:
+  drivers.clock.nrf_lf_clock_start_xtal_stable:
+    tags: drivers
+    platform_allow: nrf51dk_nrf51422 nrf52dk_nrf52832 nrf52840dk_nrf52840
```
Comment (nashif) [inline tests/drivers/clock_control/nrf_lf_clock_start/testcase.yaml:4]: maybe put this in a common section on top.

Comment (nashif) [reply tests/drivers/clock_control/nrf_lf_clock_start/testcase.yaml:4]: but the real question, can we use some filter instead of listing platforms individually?

**Comment by carlescufi** [comment]
@andyross could you please take a look so we can merge this in time for 2.4.0?

**Comment by PerMac** [comment]
Running on this PR solves the problem with `test_kernel_systicks` on nrf9160dk_nrf9160.  However, it introduces an error for nrf5340dk_nrf5340_cpuapp: after flashing the board hangs, and the test from `tests/portability/cmsis_rtos_v1` ends with a timeout.

**Comment by nordic-krch** [comment]
@PerMac thanks for running it on that PR, i will look into nrf53 issue then.

**Comment by nordic-krch** [comment]
nrf53 is fixed by https://github.com/zephyrproject-rtos/zephyr/pull/28121

**Comment by carlescufi** [comment]
> No complaints about the code. But is this really a good candidate for a global API? Right now it's just the one platform that needs to care about this. Maybe we should start this out as an internal thing with the nRF timer driver and promote the kconfig API to a global one only later?

We have restricted it to the scope of the nRF timer for now, and after the 2.4 release we will consider expanding this to the rest of platforms.

**Comment by carlescufi** [comment]
@anangl please take a look

File: drivers/clock_control/clock_control_nrf.c [hunk 7]
```diff
@@ -441,16 +440,64 @@ static void lfclk_spinwait(nrf_clock_lfclk_t t)
...
+	int key = isr_mode ? irq_lock() : 0;
+
+	if (!isr_mode) {
+		nrf_clock_int_disable(NRF_CLOCK, NRF_CLOCK_INT_LF_STARTED_MASK);
+	}
 
-	while (!(nrfx_clock_is_running(d, (void *)&type) && (type == t))) {
-		/* empty */
+	while (!(nrfx_clock_is_running(d, (void *)&type)
+		 && ((type == t) || (type == CLOCK_CONTROL_NRF_K32SRC)))) {
```
Comment (anangl) [inline drivers/clock_control/clock_control_nrf.c:455]: This won't work for `CONFIG_CLOCK_CONTROL_NRF_K32SRC_EXT_LOW_SWING` and `CONFIG_CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING`, as `type` will be `NRF_CLOCK_LFCLK_Xtal` then.

I'd propose to correct it and simplify a bit the logic used here as follows.
First, to change the function signature to:
```
static void lfclk_spinwait(enum nrf_lfclk_start_mode start_mode)
```
then instead of `lfxo_target` use something like:
```
	nrf_clock_lfclk_t target_type =
		/* For sources XTAL, EXT_LOW_SWING, and EXT_FULL_SWING,
		 * NRF_CLOCK_LFCLK_Xtal is returned as the type of running clock.
		 */
		(IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL) ||
		 IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_EXT_LOW_SWING) ||
		 IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING))
		? NRF_CLOCK_LFCLK_Xtal
		: CLOCK_CONTROL_NRF_K32SRC;
 ```
and then use here:
```
	while (!(nrfx_clock_is_running(d, (void *)&type)
		 && ((type == target_type)
		     || (mode == NRF_LFCLK_START_MODE_SPINWAIT_AVAILABLE))) {
```
and below:
```
		if (target_type == NRF_CLOCK_LFCLK_Xtal
		    && (nrf_clock_lf_src_get(NRF_CLOCK) == NRF_CLOCK_LFCLK_RC)
		    && nrf_clock_event_check(NRF_CLOCK,
		    ...
```
In the `switch` in `z_nrf_clock_control_lf_on()` we'll have then:
```
	case NRF_LFCLK_START_MODE_SPINWAIT_STABLE:
	case NRF_LFCLK_START_MODE_SPINWAIT_AVAILABLE:
		lfclk_spinwait(mode);
```

**Review by anangl — CHANGES_REQUESTED** [review]

File: include/drivers/clock_control/nrf_clock_control.h [hunk 8]
```diff
@@ -38,7 +38,7 @@ enum clock_control_nrf_type {
 /** @brief LF clock start modes. */
 enum nrf_lfclk_start_mode {
 	NRF_LFCLK_START_MODE_NOWAIT,
-	NRF_LFCLK_START_MODE_SPINWAIT_RUNNING,
+	NRF_LFCLK_START_MODE_SPINWAIT_AVAILABLE,
 	NRF_LFCLK_START_MODE_SPINWAIT_STABLE,
 };
```
Comment (anangl) [inline include/drivers/clock_control/nrf_clock_control.h:43]: Shouldn't we use other prefixes here? I know, `CLOCK_CONTROL_NRF_` is lengthy, but the current one is not consistent with the other stuff defined in this file.

Comment (nordic-krch) [reply include/drivers/clock_control/nrf_clock_control.h]: renamed to `CLOCK_CONTROL_NRF_LF_START_[STABLE, AVAILABLE,NOWAIT]`

File: drivers/clock_control/clock_control_nrf.c (hunk 7 above)
Comment (nordic-krch) [reply drivers/clock_control/clock_control_nrf.c]: Nice suggestion. Done.

File: drivers/clock_control/clock_control_nrf.c [hunk 9]
```diff
@@ -463,13 +510,20 @@ void z_nrf_clock_control_lf_on(enum nrf_lfclk_start_mode start_mode)
 		__ASSERT_NO_MSG(err >= 0);
 	}
 
+	/* In case of simulated board leave immediately. */
+	if (IS_ENABLED(CONFIG_BOARD_NRF52_BSIM)) {
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/clock_control_nrf.c]: done

File: drivers/clock_control/clock_control_nrf.c [hunk 10]
```diff
@@ -463,16 +512,19 @@ void z_nrf_clock_control_lf_on(enum nrf_lfclk_start_mode start_mode)
...
+	if (IS_ENABLED(CONFIG_SOC_SERIES_BSIM_NRFXX)) {
+		return;
+	}
 
-	case NRF_LFCLK_START_MODE_SPINWAIT_RUNNING:
-		lfclk_spinwait(NRF_CLOCK_LFCLK_RC);
+	switch (start_mode) {
+	case CLOCK_CONTROL_NRF_LF_START_AVAILABLE:
+		/* fall through. */
+	case CLOCK_CONTROL_NRF_LF_START_STABLE:
```
Comment (anangl) [inline drivers/clock_control/clock_control_nrf.c:523]: The comment here is not needed. There is no code between those two cases, so there will be no warning here. It's not a not a "true fall through". ;-)

**Review by anangl — APPROVED** [review]
LGTM. One unnecessary comment could be removed.

**Comment by nordic-krch** [comment]
@carlescufi since this is now nordic only maybe i could be merged.
