### PR TITLE
test:loop_transfer avoid useing flash as dma source address

### LINKED ISSUE #26812: NXP: tests/drivers/dma/loop_transfer fails on FRDM-K64F
**Describe the bug**

The `tests/drivers/dma/loop_transfer` test case fails on the NXP FRDM-K64F. Not all DMA RX buffers contain the DMA TX buffer string.

**To Reproduce**
1. cd tests/drivers/dma/loop_transfer; mkdir build; cd build
2. cmake -DBOARD=frdm_k64f
3. make flash
4. See the following output on the board console:

```
*** Booting Zephyr OS build zephyr-v2.3.0-898-g668e359d8558  ***
DMA memory to memory transfer started on DMA_0
Preparing DMA Controller
Starting the transfer and waiting for 1 second
TX data: The quick brown fox jumps over the lazy dog ....
block_size 48
I: channel 0 error status is 0x2
ERROR: unfinished transfer
Each RX buffer should contain the full TX buffer string.
TX data: The quick brown fox jumps over the lazy dog ....
RX data Loop 0: The quick brown fox jumps over the lazy dog ....
RX data Loop 1: The quick brown fox jups
RX data Loop 2: 
RX data Loop 3: 
RX data Loop 4: 
Finished: DMA
```
**Expected behavior**
All RX buffers contain the TX buffer content.

**Impact**
Not sure if the EDMA driver works correctly. The `tests/drivers/dma/chan_blen_transfer` test case passes, so something is working...

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA: 668e359d85585e18df5678199cae8f5be25a8b9a

**Additional context**
I found the issue while enabling the eDMA driver on the NXP KE1xF SoC (see #26813).

### PR DESCRIPTION
**Pull request by hakehuang**
avoid to use the flash address as dma source,
to avoid flash cache issue
this is fix to issue #26812

Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>

### CODE REVIEW

**Review by pabigot — CHANGES_REQUESTED** [review]
Please add to the comment that this has to be in RAM to support use as a DMA source pointer.  Otherwise somebody will come along later, notice it's never modified, and make it `const` again.

**Comment by hakehuang** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/26964#pullrequestreview-451676191

ok

File: tests/drivers/dma/loop_transfer/src/dma.c [hunk 1]
```diff
@@ -26,8 +26,8 @@ static __aligned(16) char tx_data[64] __used
 static __aligned(16) char rx_data[TRANSFER_LOOPS][RX_BUFF_SIZE] __used
 	__attribute__((__section__(".nocache.dma")));
 #else
-/* pad to times of 8*/
-static const char tx_data[] =
+/* this src memory shall be in RAM to support usingas a DMA source pointer.*/
+static char tx_data[] =
```
Comment (pabigot) [inline tests/drivers/dma/loop_transfer/src/dma.c:30]: Does this need to be aligned the way `rx_data` is?

**Review by pabigot — APPROVED** [review]
I'm OK with this as-is because I don't know better, but if the source buffer requires alignment to match the receive buffer that should be fixed.

**Review by MaureenHelm — APPROVED** [review]

File: tests/drivers/dma/loop_transfer/src/dma.c (hunk 1 above)
Comment (hakehuang) [reply tests/drivers/dma/loop_transfer/src/dma.c:30]: I did not see any restiction on src address alignment for kinetis, so I did not add it. maybe it is better t add, I will track it. Thanks
