### PR TITLE
Bluetooth: GATT: Fix bug in bt_gatt_attr_next unable for static handles

### LINKED ISSUE #19795: bt_gatt_attr_next returns first attribute in table for attributes with static storage.
**Describe the bug**
The public API function `bt_gatt_attr_next` does not work when given an attribute that has static
allocation. Since statically added attributes have handle 0 the function will then always return the attribute with handle 1.

**Expected behavior**
The function should return the next attribute in the table.

**Impact**
Minor, this is a helper function. Users can make workaround.

**Environment (please complete the following information):**
 - Commit SHA: 3b67130334033662e3a667c9ac166b0e166000fe

### PR DESCRIPTION
**Pull request by joerchan**
Fix bug in bt_gatt_attr_next when given an attribute that has static
allocation. The handle is then 0 and the function would always return
the attribute with handle 1.

Fixes: #19795
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@Vudentz I think this one needs backporting to 2.0.0, right? But not 1.14 AFAIK.

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1164,8 +1164,9 @@ static u8_t find_next(const struct bt_gatt_attr *attr, void *user_data)
 struct bt_gatt_attr *bt_gatt_attr_next(const struct bt_gatt_attr *attr)
 {
 	struct bt_gatt_attr *next = NULL;
+	u16_t handle = handle = attr->handle ? : find_static_attr(attr);
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: One too many `handle =` there? :)

**Comment by Vudentz** [comment]
We should also add a test for it since apparently there is no users currently, also there are 2 very similar function with bt_gatt_attr_value_handle which is kind bad imo, Im not sure we need the later actually since we can garantee the value_handle is always +1 in zephyr.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -1164,8 +1164,9 @@ static u8_t find_next(const struct bt_gatt_attr *attr, void *user_data)
...
 
-	bt_gatt_foreach_attr(attr->handle + 1, attr->handle + 1, find_next,
+	bt_gatt_foreach_attr(handle + 1, handle + 1, find_next,
```
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c]: Fixed.

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c]: Fixed.

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
For a backport there needs to be a matching issue as well

**Comment by joerchan** [comment]
> We should also add a test for it since apparently there is no users currently, also there are 2 very similar function with bt_gatt_attr_value_handle which is kind bad imo, Im not sure we need the later actually since we can garantee the value_handle is always +1 in zephyr.

@Vudentz I have a different PR that will use this function. `bt_gatt_attr_value_handle` does more checking though, it will check that it is actually a characteristic, and check for NULL. So I would just leave it as is.

@jhedberg Yes, will create an issue.

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]
