### PR TITLE
driver: refactor the arcv2 timer0 driver

### LINKED ISSUE #10747: tests/kernel/tickless/tickless_concept fails on ARC boards
Execution log on emsk:

```
***** Booting Zephyr OS zephyr-v1.13.0-1232-g556dc7f (delayed boot 1000ms) *****
Running test suite tickless_concept
===================================================================
starting test - test_tickless_sysclock
ASSERTION FAIL [timer_count <= programmed_limit] @ /home/kspoorth/work/latest_zephyr/drivers/timer/arcv2_timer0.c:444:
        timer_count: 279, limit 0
```

Execution log on quark_se_c1000_ss_devboard:

```
***** Booting Zephyr OS zephyr-v1.13.0-1232-g556dc7f (delayed boot 1000ms) *****
Running test suite tickless_concept
===================================================================
starting test - test_tickless_sysclock
time 1030, -422565944
time -422565934, -845132908
PASS - test_tickless_sysclock
===================================================================
starting test - test_tickless_slice
elapsed slice -422566974, expected: <100, 110>

    Assertion failed at /home/kspoorth/work/latest_zephyr/tests/kernel/tickless/tickless_concept/src/main.c:57: thread_tslice: t >= SLICE_SIZE is false

elapsed slice 20, expected: <100, 110>

    Assertion failed at /home/kspoorth/work/latest_zephyr/tests/kernel/tickless/tickless_concept/src/main.c:57: thread_tslice: t >= SLICE_SIZE is false

elapsed slice 10, expected: <100, 110>

    Assertion failed at /home/kspoorth/work/latest_zephyr/tests/kernel/tickless/tickless_concept/src/main.c:57: thread_tslice: t >= SLICE_SIZE is false

elapsed slice 20, expected: <100, 110>

    Assertion failed at /home/kspoorth/work/latest_zephyr/tests/kernel/tickless/tickless_concept/src/main.c:57: thread_tslice: t >= SLICE_SIZE is false

FAIL - test_tickless_slice
===================================================================
===================================================================
PROJECT EXECUTION FAILED
```

### LINKED ISSUE #11129: CONFIG_TICKLESS_KERNEL makes z_clock_set_timeout doesn't work
@andyross @nashif  @ruuddw 

in timeout.c, the function will call  the clock driver wrapper z_clock_set_timerout in legacy_api.h.

```
void z_clock_set_timeout(s32_t ticks, bool idle)
{
#ifdef CONFIG_TICKLESS_KERNEL
	if (idle) {
		_timer_idle_enter(ticks);
	} else {
		_set_time(ticks == K_FOREVER ? 0 : ticks);
	}
#endif
}
```

According to the code, if TICKLESS_KERNEL is not configured,  z_clock_set_timeout will do nothing, which means  the timeout mechnism will fail.

I already observed the failure in tests/kernel/profiling/profiling_api caused by the changes in clock driver (legacy_api.h)

BTW in line 46 of legacy_api.h 

`#ifdef TICKLESS_KERNEL` shoud be `#ifdef CONFIG_TICKLESS_KERNEL` ?

### PR DESCRIPTION
**Pull request by vonhust**
refactor the arcv2 timer0 driver according to
the latest changes in sys clock dirver

The new dirver refers the implementation of cortex-m sys tick driver

Verified by the test/kernel on nsim_sem

Fixes #10747
Fixes #11129

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

### CODE REVIEW

File: drivers/timer/arcv2_timer0.c [hunk 1]
```diff
@@ -156,323 +108,44 @@ static ALWAYS_INLINE void timer0_limit_register_set(u32_t count)
...
  *
- * This routine handles the system clock periodic tick interrupt. It always
- * announces one tick.
+ * This routine handles the system clock tick interrupt. It always
+ * announces one tick when TICKLESS is not enabled, or multiple ticks
+ * when TICKLESS is enabled.
  *
  * @return N/A
  */
 void _timer_int_handler(void *unused)
```
Comment (andyross) [inline drivers/timer/arcv2_timer0.c]: Unless this is required for external linkage, make this a static function.  A few architectures are still weird, but it would be good to get away from "the timer ISR always has a particular name".

File: drivers/timer/arcv2_timer0.c [hunk 2]
```diff
@@ -512,76 +178,69 @@ int z_clock_driver_init(struct device *device)
...
-#ifdef CONFIG_DEVICE_POWER_MANAGEMENT
-static int sys_clock_suspend(struct device *dev)
+void z_clock_set_timeout(s32_t ticks, bool idle)
 {
-	ARG_UNUSED(dev);
+	/* If the kernel allows us to miss tick announcements in idle,
+	 * then shut off
+	 * the counter. (Note: we can assume if idle==true that
+	 * interrupts are already disabled)
+	 */
```
Comment (andyross) [inline drivers/timer/arcv2_timer0.c]: FWIW: I'm about to remove the idle parameter here in a separate patch series.  This logic is going into the kernel and will be replaced with a simpler "shut off the counter" API.  Not a problem here, just be aware you might need to rebase this depending on which lands first.

File: drivers/timer/arcv2_timer0.c [hunk 3]
```diff
@@ -512,76 +178,69 @@ int z_clock_driver_init(struct device *device)
...
+		timer0_control_register_set(0);
+		timer0_count_register_set(0);
+		timer0_limit_register_set(0);
+		last_load = TIMER_STOPPED;
+		return;
+	}
 
-	saved_limit = timer0_limit_register_get();
-	saved_control = timer0_control_register_get();
+#if defined(CONFIG_TICKLESS_KERNEL) && !defined(CONFIG_QEMU_TICKLESS_WORKAROUND)
```
Comment (andyross) [inline drivers/timer/arcv2_timer0.c]: You only need the QEMU_TICKLESS_WORKAROUND logic if you have to run in qemu without icount enabled (which tries to return host time from the cycle counter).  ARC doesn't have a qemu target and IIRC nsim is cycle-exact.  You just want to test for TICKLESS_KERNEL here.

File: drivers/timer/arcv2_timer0.c [hunk 4]
```diff
@@ -512,76 +178,69 @@ int z_clock_driver_init(struct device *device)
...
 {
-	if (ctrl_command == DEVICE_PM_SET_POWER_STATE) {
-		if (*((u32_t *)context) == DEVICE_PM_SUSPEND_STATE) {
-			return sys_clock_suspend(port);
-		} else if (*((u32_t *)context) == DEVICE_PM_ACTIVE_STATE) {
-			return sys_clock_resume(port);
-		}
-	} else if (ctrl_command == DEVICE_PM_GET_POWER_STATE) {
-		*((u32_t *)context) = arcv2_timer0_device_power_state;
+	if (!TICKLESS) {
```
Comment (andyross) [inline drivers/timer/arcv2_timer0.c]: As above.  Can be IS_ENABLED(CONFIG_TICKLESS_KERNEL) here, no need for QEMU silliness.

**Review by andyross — CHANGES_REQUESTED** [review]
Fantastic, thanks!  A few nitpicks, but I can't see anything particularly wrong.

FWIW: I thought I remember reading somewhere that the ARC timer has a free-running "comparator" mode (i.e. one where you don't need to change the cycle counter and can set a value that will cause an interrupt when the cycle count is equal)?  If it does, you should consider doing that instead of the "limit" register here, which is more fragile (it must always lose a few cycles, and can't recover from delayed timer interrupts easily) and error prone (I had a LOT more trouble getting SysTick working than the other drivers, which are simpler and mostly just clones of each other).

I had a LOT more trouble getting SysTick working than the others.

**Review by andyross — DISMISSED** [review]
OK, I went back and checked the docs.  Indeed, the "LIMIT0" register is exactly the kind of comparator we want.

You want this driver to look like the one for Xtensa (or hpet or risc-v, but those have more architectural complexity -- Xtensa looks the closest to how I think ARCv2 works) and not SysTick.

In particular that allows you to remove the loop around the counter read in elapsed() (because the free-running counter never stops or requires synchronized state) and allows you to cleanly handle lost interrupts because you can compute elapsed ticks from the cycle counter and the time of the last announcement regardless of when the interrupt actually arrives.

**Comment by vonhust** [comment]
@andyross , according to ARCv2 ISA and my experience on arc processors, the count will starts from 0 when it reaches the limit regs. so the logic in elasped (refer your code in cortex-m sys tick driver) is required to handle the case that timer couter re-starts from  0, for arc it will loop at most once.

File: drivers/timer/arcv2_timer0.c (hunk 4 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c]: We are woring on adding arc support in QMEU,  so it may be needed in the future.

File: drivers/timer/arcv2_timer0.c (hunk 1 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c]: agreed, it should be static, i will change it.

**Comment by ruuddw** [comment]
Wayne, I think Andy tries to explain that ARM Systick handles 'overflow' differently. When the counter keeps counting after generating an interrupt, the value is always accurate - no need to have the 'complex' elapsed() function that checks for overflow, just read the counter value.

File: drivers/timer/arcv2_timer0.c (hunk 4 above)
Comment (andyross) [reply drivers/timer/arcv2_timer0.c]: It's a monstrostrous hack, needed by only a few tests right now.  Let's not propagate it if we aren't sure we need it.  By the time arc support lands in our SDK qemu we will hopefully have icount working.

**Comment by andyross** [comment]
OK, if the counter restarts on reaching limit, then that's not the behavior I understood and is like SysTick.  I'm obviously not the expert.

File: drivers/timer/arcv2_timer0.c (hunk 4 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c]: ok, i will remove it

**Review by ruuddw — COMMENTED** [review]
Looks ok, except for the comments on 'ctrl_cache'. The overflow handling in 'elapsed' looks robust (not sure it's the fastest way to do this on ARC, though).

**Review by ruuddw — APPROVED** [review]

**Comment by nashif** [comment]
@andyross please re-review

**Review by andyross — APPROVED** [review]
Looks great, thanks!
