### PR TITLE
kernel: timer: Eliminate a race condition in expiration handling

### LINKED ISSUE #54567: Assertion in z_add_timeout() fails in drivers.uart.uart_mix_poll_async_api test
**Describe the bug**
Execution of the `tests/drivers/uart/uart_mix_fifo_poll/drivers.uart.uart_mix_poll_async_api` test on the `nrf52840dk_nrf52840` board usually ends up with an assertion failure reported for the `z_add_timeout` function (`kernel/timeout.c:99`).

While debugging, I figured out that this is caused by a race condition in the execution of the timer expiration handler. When a timer is restarted from a high priority interrupt, it may happen that the timer is re-added to the timeout list right after it is removed from that list prior to execution of its expiration handler but before that execution actually occurs. `z_add_timeout()`, called from `z_timer_expiration_handler()` for periodic timers, turns out then to be adding a timeout that is already added to the timeout list and the assertion fails.

This problem is also reported in #53613 but since it is not the only one there, I decided to create a separate issue for it.

**To Reproduce**
1. Execute `west twister -p nrf52840dk_nrf52840 -s tests/drivers/uart/uart_mix_fifo_poll/drivers.uart.uart_mix_poll_async_api --device-testing --device-serial /dev/ttyACM0 --fixture gpio_loopback`
2. See `twister-out/nrf52840dk_nrf52840/tests/drivers/uart/uart_mix_fifo_poll/drivers.uart.uart_mix_poll_async_api/handler.log`

**Logs and console output**
```
*** Booting Zephyr OS build v3.3.0-rc2-59-g36421f2efc8d ***
Running TESTSUITE uart_mix_fifo_poll
===================================================================
START - test_mixed_uart_access
ASSERTION FAIL [!sys_dnode_is_linked(&to->node)] @ WEST_TOPDIR/zephyr/kernel/timeout.c:99
E: r0/a1:  0x00000004  r1/a2:  0x00000063  r2/a3:  0x00000000
E: r3/a4:  0x00000021 r12/ip:  0x00000000 r14/lr:  0x0000aed3
E:  xpsr:  0x41000021
E: Faulting instruction address (r15/pc): 0x0000e22a
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Fault during interrupt handling
E: Current thread: 0x200000d8 (unknown)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.15.1
 - Commit 36421f2efc8d18ba520287804f0cc9df5cf570d8

### PR DESCRIPTION
**Pull request by anangl**
When a timer is restarted from a high priority interrupt, it may happen that the timer is re-added to the timeout list right after it is removed from that list prior to execution of its expiration handler but before that execution actually occurs. This leads to an assertion failure reported for `z_add_timeout()` because then that function, called from `z_timer_expiration_handler()` for periodic timers, turns out to be adding a timeout that is already added to the timeout list.
This commit detects such situation in `z_timer_expiration_handler()` and makes that function exit immediately when that occurs (as the timer was restared, its expiration handler should not be executed).

Fixes #54567.

### CODE REVIEW

File: kernel/timer.c [hunk 1]
```diff
@@ -26,6 +26,24 @@ void z_timer_expiration_handler(struct _timeout *t)
...
+	 * unlocked interrupts). For kernel timers, the expiration handler is
+	 * this function. Usually, the timeout structure related to the timer
+	 * that is handled here will not be linked to the timeout list at this
+	 * point. But it may happen that before this function is executed and
+	 * interrupts are locked again, a given timer gets restarted from an
+	 * interrupt context that has a priority higher than the system timer
+	 * interrupt. Then, the timeout structure for this timer will turn out
+	 * to be linked to the timeout list. And in such case, since the timer
+	 * was restarted, its expiration handler should not be executed then,
+	 * so the function exits immediately.
```
Comment (andyross) [inline kernel/timer.c:40]: Explaining race conditions is never clear enough. :)  But maybe make this shorter?  As I see it the relevant details are (1) this callback runs unsynchronized and (2) another context may have already run and cancelled/rescheduled us before we took our own lock, in which case the handler must noop.

**Review by andyross — APPROVED** [review]
Looks correct to me.  Nitpickery on the explanation.

**Review by dcpleung — APPROVED** [review]
