### PR TITLE
drivers: video: dcmi: fix DMA channel configuration

### LINKED ISSUE #92015: drivers: video: dcmi: DMA error message on capture sample
### Describe the bug

Trying the [capture](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/drivers/video/capture/) again on `main`, an error message appears.

This was working earlier so will be possible to walk up the history tree.

### Regression

- [x] This is a regression.

### Steps to reproduce

1. `west build -b arduino_nicla_vision/stm32h747xx/m7`
2. `west flash`
3. Connect to the console over USB where the logs are printed (i.e. /dev/ttyACM0, any baudrate)

### Relevant log output

```shell
[00:00:00.000,000] <inf> camera_ext_clock: Camera external clock rate: (10000000) Hz
[00:00:00.000,000] <err> video_stm32_dcmi: DCMI DMA Init failed
[00:00:00.000,000] <err> video_stm32_dcmi: DMA initialization failed.
*** Booting Zephyr OS build v4.1.0-6399-g1931a35c74fa ***
[00:00:00.413,000] <err> main: dcmi@48020000: video device is not ready
uart:~$ device list
...
- dma@40020000 (READY)
  DT node labels: dma1
...
- gc2145@3c (READY)
  DT node labels: gc2145
- dcmi@48020000 (DISABLED)
  DT node labels: dcmi
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

- OS: `Debian 13.0`
- Toolchain: `zephyr-sdk-0.17.0`
- Commit: 92d4669752b

### PR DESCRIPTION
**Pull request by josuah**
Commit 64149e4df6d4c2873e222f6bf118a9ee6cb2bdb1 added an `#if defined()` for configuring DMA channels differently depending on SOC family of the STM32 HAL, but did not include the STM32H7 family in the same group as STM32F7. Fix it by adding the STM32H7 in the same `#ifdef` filter.

Fixes #92015

### CODE REVIEW

**Comment by josuah** [comment]
I do not know the internals of the STM32 HAL enough to tell if this is the right approach.

File: drivers/video/video_stm32_dcmi.c [hunk 1]
```diff
@@ -155,11 +155,11 @@ static int stm32_dma_init(const struct device *dev)
 	hdma.Init.MemDataAlignment	= DMA_MDATAALIGN_WORD;
 	hdma.Init.Mode			= DMA_CIRCULAR;
 	hdma.Init.Priority		= DMA_PRIORITY_HIGH;
-#if defined(CONFIG_SOC_SERIES_STM32F7X)
+#if defined(CONFIG_SOC_SERIES_STM32F7X) || defined(CONFIG_SOC_SERIES_STM32H7X)
```
Comment (JarmouniA) [inline drivers/video/video_stm32_dcmi.c:158]: I think the filtering should be done by DMA compatible instead of series.

Comment (josuah) [reply drivers/video/video_stm32_dcmi.c:158]: Yes, it sounds like this would avoid forgetting platforms accidentally.

**Comment by josuah** [comment]
Force-push:
- Rebased on `main` for easier UVC testing.

**Review by kartben — APPROVED** [review]

File: drivers/video/video_stm32_dcmi.c (hunk 1 above)
Comment (josuah) [reply drivers/video/video_stm32_dcmi.c:158]: Is it suitable to keep the current bugfix and follow-up with this issue to avoid a change just before the release?
- https://github.com/zephyrproject-rtos/zephyr/issues/92308

**Review by JarmouniA — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by avolmat-st — APPROVED** [review]
