### PR TITLE
Bluetooth: Fix GATT CCC issue with multiple local identities

### LINKED ISSUE #23023: Bluetooth: GATT CCC problem (GATT Server)
**Describe the bug**
The GATT CCCs are not properly connected with Bluetooth local identities on GATT Server. This may cause problems when using multiple Bluetooth local identities.

**To Reproduce**
Reproduced with `nrf_desktop` application (from NordicPlayground/fw-nrfconnect-nrf):

1. Use Bluetooth Peripheral device with GATT Server, supporting multiple Bluetooth local identities.
2. Bond the device twice with the same host using various Bluetooth local identities.
3. Reboot the device.
4. Observe problems sending GATT notifications after reconnection.

**Impact**
GATT notifications may not be properly sent when using Bluetooth local identities.

**Screenshots or console output**
Peripheral device being unable to send BAS notification, every notification try fails (Peripheral assumes that notifications are not enabled).
```
[59624386] <inf> battery_meas: Battery level: 89% (4068 mV)
[59624388] <inf> event_manager: e: battery_level_event level=89
[59624389] <err> bas: GATT notify failed (err=-57)
```

### PR DESCRIPTION
**Pull request by joerchan**
Fix issue where a new connection with the same peer would use the CCC
from from first connection, despite different local identity.
Since there is no CCC for the new connection yet this caused the
application to think that CCC was enabled but the remote device had not
yet subscribed.
    
Fix this issue by making the id as an input to the peer address check
function. This will force us to make the check every time. This
might also fix similar issues not yes discovered as the ID check was
missing in a few other places as well.

Fixes: #23023

### CODE REVIEW

**Comment by joerchan** [comment]
@MarekPieta Can you please check for me?

**Comment by Vudentz** [comment]
This sure looks like the first step to have multiple adapter support in Zephyr since it appears this wants to have all states per identity. Btw, I don't think the spec describe this scenario so this might be confusing if we don't have a clear way to describe what is it that we are trying to accomplished, IMO bonding and CCC state shall go along, so we can do CCC state per identity if bonding is per identity, that would bloat the code for single identity though, besides let say someone decides to really do have 2 different controllers so we will have to deal with 2 layer of complexity one stack over another.

**Comment by joerchan** [comment]
@Vudentz The state change is mostly due to this:
https://github.com/zephyrproject-rtos/zephyr/pull/22949/files#diff-18e9bede72d2870a34b188f8dda195c6R1737 
Which could potentially save the sc_data for the bond with a different identity.

For the rest the state change would not change anything. For the time being most of the places where we use the state lookup it is to find the pending connections. And then there can be only one connection in that specific state. For advertising extension with multiple advertising set that might change. But then there could still be two advertiser using the same identity. So still unsure how that will look.

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -430,12 +431,14 @@ static struct gatt_cf_cfg *find_cf_cfg(struct bt_conn *conn)
 	int i;
 
 	for (i = 0; i < ARRAY_SIZE(cf_cfg); i++) {
+		struct gatt_cf_cfg *cfg = &cf_cfg[i];
+
 		if (!conn) {
-			if (!bt_addr_le_cmp(&cf_cfg[i].peer, BT_ADDR_LE_ANY)) {
-				return &cf_cfg[i];
+			if (!bt_addr_le_cmp(&cf_cfg->peer, BT_ADDR_LE_ANY)) {
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c]: `cfg->peer` ?

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -1406,13 +1409,15 @@ static struct bt_gatt_ccc_cfg *find_ccc_cfg(const struct bt_conn *conn,
...
+
 		if (conn) {
-			if (conn->id == ccc->cfg[i].id &&
-			    !bt_conn_addr_le_cmp(conn, &ccc->cfg[i].peer)) {
-				return &ccc->cfg[i];
+			if (bt_conn_is_peer_addr_le(conn, cfg->id,
+						    &cfg->peer)) {
+				return cfg;
 			}
 		} else if (!bt_addr_le_cmp(&ccc->cfg[i].peer, BT_ADDR_LE_ANY)) {
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c]: Here we could use cfg pointer aswell.

File: subsys/bluetooth/host/gatt.c [hunk 3]
```diff
@@ -59,6 +59,7 @@ struct ccc_store {
 };
 
 struct gatt_sub {
+	u8_t id;
```
Comment (MarekPieta) [inline subsys/bluetooth/host/gatt.c]: I guess we should initialize it on `gatt_sub_add`

**Review by MarekPieta — APPROVED** [review]
The reported issue is fixed. Thank you.

**Comment by carlescufi** [comment]
> This sure looks like the first step to have multiple adapter support in Zephyr since it appears this wants to have all states per identity. Btw, I don't think the spec describe this scenario so this might be confusing if we don't have a clear way to describe what is it that we are trying to accomplished, IMO bonding and CCC state shall go along, so we can do CCC state per identity if bonding is per identity, that would bloat the code for single identity though, besides let say someone decides to really do have 2 different controllers so we will have to deal with 2 layer of complexity one stack over another.

@Vudentz Just to clarify, this is not really trying to start the path towards multiple adapter support in Zephyr. It is instead fixing issues with a feature that has been in Zephyr for a while (multiple identity support), introduced by @jhedberg at the request of Nordic engineers that maintain a Zephyr-based keyboard+mouse application reference design.

**Review by jhedberg — DISMISSED** [review]

File: subsys/bluetooth/host/conn.c [hunk 4]
```diff
@@ -1803,19 +1803,24 @@ struct bt_conn *bt_conn_lookup_handle(u16_t handle)
 	return NULL;
 }
 
-int bt_conn_addr_le_cmp(const struct bt_conn *conn, const bt_addr_le_t *peer)
+int bt_conn_is_peer_addr_le(const struct bt_conn *conn, u8_t id,
```
Comment (Vudentz) [inline subsys/bluetooth/host/conn.c]: Looks like this is expecting a int as return but instead it return true/false.

Comment (Vudentz) [reply subsys/bluetooth/host/conn.c]: It might be cleaner if we have something like:

struct bt_le_peer {
  u8_t id;
  bt_addr_le_t *addr;
}

And then replace where we might need to store them both and we can call it bt_conn_is_le_peer and keep bt_conn_addr_le_cmp for just comparing the address.

Comment (jhedberg) [reply subsys/bluetooth/host/conn.c]: You could also consider adding a `u8_t id` parameter to `bt_conn_addr_le_cmp`, since I can't think of any use case where you would want to compare the address and ignore the identity.

Comment (joerchan) [reply subsys/bluetooth/host/conn.c]: Fixed the return value.

The other change I'm not so sure about. Mostly because it seems like it would cause ripple effect to the functions. Most of the functions accept an ID and and address, and some of these functions are public API functions. In that case we would have to construct this object.

I added `u8_t` parameter to `bt_conn_addr_le_cmp` but since it does not strictly only return values from addr_cmp I changed it to return true/false and renamed it. So the old function is in use anymore. And I don't see the need to have it either.

File: subsys/bluetooth/host/conn.c [hunk 5]
```diff
@@ -1803,19 +1803,24 @@ struct bt_conn *bt_conn_lookup_handle(u16_t handle)
...
+
 	/* Check against conn dst address as it may be the identity address */
 	if (!bt_addr_le_cmp(peer, &conn->le.dst)) {
-		return 0;
+		return true;
 	}
 
 	/* Check against initial connection address */
 	if (conn->role == BT_HCI_ROLE_MASTER) {
 		return bt_addr_le_cmp(peer, &conn->le.resp_addr);
```
Comment (jhedberg) [inline subsys/bluetooth/host/conn.c]: Don't you need to change this line as well? I'd prefer if you do explicit comparisons with the return value as well, so `return (bt_addr_le_cmp(...) == 0);` here as well as a few lines below

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/conn.c (hunk 5 above)
Comment (joerchan) [reply subsys/bluetooth/host/conn.c]: Yes missed that, thank you.

Comment (jhedberg) [reply subsys/bluetooth/host/conn.c]: And just to clarify why I prefer the explicit comparisons: normally what you'd apply the `!` operator to is a boolean expression, however in this case you're applying it to a comparison function that can return negative, 0, or positive, so it makes the intent of the code harder to follow.

**Comment by joerchan** [comment]
> It might be cleaner if we have something like:
> 
> struct bt_le_peer {
u8_t id;
bt_addr_le_t *addr;
}

There are further issues with `bt_gatt_clear` only `bt_gatt_clear_ccc` checked the `id`. So I find myself reconsidering this suggestion. There is already a struct similar to what you suggest, name `struct addr_with_id`. However `struct bt_gatt_ccc_cfg` is declared in public `gatt.h` header file.  
Is it acceptable to change this definition?
It's only use is by `struct _bt_gatt_ccc`, which is marked as internal representation of CCC value.

File: subsys/bluetooth/host/conn.c (hunk 5 above)
Comment (joerchan) [reply subsys/bluetooth/host/conn.c]: Just to clarify, do mean the return statements, or the if statement as well, because the if's all use `if (!memcmp())` and is fairly consistent.

Comment (jhedberg) [reply subsys/bluetooth/host/conn.c]: Yeah, I know. If I were to write everything from scratch I might prefer to have the `== 0` everywhere. At leasts for if-statments its immediately clear what's expected (it's always a boolean expression) and I'm also quite used to seeing the `if (!memcmp())` style stuff there so that it's immediately clear. In the case of the return statement you'd have to jump up to the beginning of the function to realise that it returns a boolean type, so being more explicit is more justified there, IMO. Feel free to disagree 😉

**Review by jhedberg — APPROVED** [review]
