### PR TITLE
Bluetooth: Controller: Fix incorrect event_count when CIG overlaps

### LINKED ISSUE #83584: Bluetooth: Controller: ISO: CIS MIC errors commonly occur
**Describe the bug**
It has become a common occurrence to see MIC errors causing CIS disconnects (reason 0x3d (`BT_HCI_ERR_TERM_DUE_TO_MIC_FAIL`)) in various configurations. These are often found in the LE Audio tests. They occur with both unidirectional and bidirectional configurations and with both a single peripheral and multiple peripherals. 

**To Reproduce**
1. Apply https://github.com/zephyrproject-rtos/zephyr/pull/83539
2. Run https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bsim/bluetooth/audio/compile.sh
3. Run any of the tests that disabled in that PR marked with "reason 0x3d"

**Expected behavior**
Expect to see no MIC errors when sending audio on a CIS on an encrypted ACL. 

**Impact**
Significant as it occurs often and seemingly not something that is fixable by the application. Causes CI issues. 

**Logs and console output**
Common log for these tests (look for `bt_iso_chan_disconnected: 0xXXXXXXXX, reason 0x3d`):
```
 d_00: @00:00:12.995916  Started stream 0x84ce7c0
d_00: @00:00:12.995916  [00:00:12.995,910] <inf> bap_stream_tx: Registered 0x84ce7c0 for TX
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_cap_initiator: bt_cap_initiator_started: cap_stream 0x84ce7c0
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_cap_initiator: update_proc_done_cnt: proc 1 subproc 5: 2/4
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_cap_initiator: bt_cap_initiator_started: Stream 0x84ce7c0 started (2/4 streams done)
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_stream: bt_bap_stream_start: stream 0x84ce920 ep 0x8537724
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_unicast_client: bt_bap_unicast_client_start: stream 0x84ce920
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_unicast_client: unicast_client_ep_start: ep 0x8537724 buf 0x8537d5c
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_unicast_client: unicast_client_ep_start: id 0x03
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_unicast_client: bt_bap_unicast_client_ep_send: conn 0x84fd340 ep 0x8537724 buf 0x8537d5c len 3
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_disconnected: 0x850dee0
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_chan_disconnected: 0x8535e60, reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x8535e60 iso 0x850dee0 connected -> disconnected
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_cleanup_acl: 0x850dee0
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_iso_disconnected: stream 0x84cf160 ep 0x852e448 state streaming reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_iso_disconnected: stream 0x84cf1b8 ep 0x852e7d8 state enabling reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_get_status: ep 0x852e448 id 0x01 state qos-configured
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_get_status_qos: dir sink codec id 0x06 interval 7500 framing 0x00 phy 0x02 rtn 1 latency 15 pd 10000
d_01: @00:00:13.006947  [00:00:13.006,927] <wrn> bt_conn: bt_conn_create_pdu_timeout: Timeout discarded. No blocking in syswq.
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: state_transition_work_handler: ase 0x852e444 ep 0x852e448 id 0x01 streaming -> qos-configured
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_disconnected: 0x850dfd0
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_chan_disconnected: 0x8535ef0, reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x8535ef0 iso 0x850dfd0 connected -> disconnected
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_cleanup_acl: 0x850dfd0
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_iso_disconnected: stream 0x84cf18c ep 0x852e610 state streaming reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_iso_disconnected: stream 0x84cf1e4 ep 0x852e9a0 state enabling reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_get_status: ep 0x852e610 id 0x02 state qos-configured
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_get_status_qos: dir sink codec id 0x06 interval 7500 framing 0x00 phy 0x02 rtn 1 latency 15 pd 10000
d_01: @00:00:13.006947  [00:00:13.006,927] <wrn> bt_conn: bt_conn_create_pdu_timeout: Timeout discarded. No blocking in syswq.
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: state_transition_work_handler: ase 0x852e60c ep 0x852e610 id 0x02 streaming -> qos-configured
d_00: @00:00:13.013547  [00:00:13.013,519] <inf> bap_stream_tx: Stream 0x84ce7c0 sent 0 SDUs
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ascs_cp_write: conn 0x84fd340 attr 0x8490c28 buf 0x85acf0f len 3 op Receiver Start Ready (0x04)
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ascs_start: num_ases 1
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ascs_start: ase 0x03
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ase_start: ase 0x852e7d4
d_01: @00:00:13.065698  [00:00:13.065,673] <wrn> bt_ascs: ase_start: Start failed: CIS not connected: 0
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x03 code Invalid ASE State (0x04) reason None (0x00)
d_00: @00:00:13.066004  [00:00:13.065,979] <dbg> bt_bap_unicast_client: unicast_client_ep_notify: conn 0x84fd340 ep 0x853737c len 17
d_00: @00:00:13.066004  [00:00:13.065,979] <dbg> bt_cap_common: bt_cap_common_abort_proc: Aborting proc 1 with subproc 5 for 0x84fd340: -74
d_00: @00:00:13.066004  Stream 0x84ce660 stopped with reason 0x13
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/83539 (but also occurs for https://github.com/zephyrproject-rtos/zephyr/pull/81093). Both running on `b7b3449f482cd9fb736e3a79363d390fd648051d`

**Additional context**
See also https://github.com/zephyrproject-rtos/zephyr/actions/runs/12581046107/job/35064082709?pr=81093

### PR DESCRIPTION
**Pull request by cvinayak**
Fix incorrect event_count use in CIG events when the next
CIG interval's prepare overlaps with the current CIG event.
Use separate event_count_prepare variable in ULL and copy
the value in LLL event.

Fixes #83584.

Other miscellaneous improvements:
- Fix Connected ISO to use accumulated latency to update the
payload count.
- Fix incorrect elapsed events value when event prepare are
aborted in the pipeline. This can caused premature
supervision timeouts.
Relates to commit https://github.com/zephyrproject-rtos/zephyr/commit/247037bd3e2ab6f137bcc02d6e0f10f4dcfa9c99 ("Bluetooth: Controller: Fix
incorrect elapsed events value").

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c [hunk 1]
```diff
@@ -711,17 +711,17 @@ void ull_conn_iso_ticker_cb(uint32_t ticks_at_expire, uint32_t ticks_drift,
 		 * has been reached, and offset calculated.
 		 */
 		if (cis->lll.handle != 0xFFFF && cis->lll.active) {
-			cis->lll.event_count += (lazy + 1U);
+			cis->lll.event_count_prepare += (lazy + 1U);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c:714]: `event_count_prepare` is initialized to `LLL_CONN_ISO_EVENT_COUNT_MAX` but unconditionally incremented here. 

Does this not risk overflowing the counter? Is that intentional?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso.c:714]: yes, intentional to rollover and take the value `0` on the very first (and corresponding in case of skipped) ISO interval event.

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso.c:714]: Can I bother you to add a comment stating that? 

Generally, unless completely obvious, I do prefer when overflows are intentional that they are documented as well, so this won't be considered a bug by someone else :)

**Review by Thalley — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
