### PR TITLE
usb: Do not allow to clear STALL or dtoggle for ISO ep.

### LINKED ISSUE #28361: USB audio samples fails if ASSERT=y
**Describe the bug**
Running the USB audio samples for nrf5340dk_nrf5340_cpuapp fails on ASSERT in nrf_usbd.h:1273 if asserts are turned on

**To Reproduce**
1. cd samples\subsys\usb\audio\headphones_microphone
2. west build -b nrf5340dk_nrf5340_cpuapp
3. west flash
4. See error on UART

### PR DESCRIPTION
**Pull request by eobalski**
ISO endpoints do not support dtoggle for synchronization
purposes so omit calling dtoggle clear for them.
ISO endpoints cannot be STLLed as well omit clearing STALL
for ISO endpoints.

Signed-off-by: Emil Obalski <emil.obalski@nordicsemi.no>

Closes: #28361

### CODE REVIEW

File: drivers/usb/device/usb_dc_nrfx.c [hunk 1]
```diff
@@ -1612,7 +1619,10 @@ int usb_dc_ep_enable(const uint8_t ep)
 		return -EINVAL;
 	}
 
-	nrfx_usbd_ep_dtoggle_clear(ep_addr_to_nrfx(ep));
+	if (!NRF_USBD_EPISO_CHECK(ep)) {
+		/* ISO endpoints do not support dtoggle */
```
Comment (jfischer-phytec-iot) [inline drivers/usb/device/usb_dc_nrfx.c:1623]: The comment does not explain it correct, see "8.5.5 Isochronous Transactions". Probably: "A full-speed device do not support toggle sequencing and should only send DATA0 PID.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/device/usb_dc_nrfx.c (hunk 1 above)
Comment (emob-nordic) [reply drivers/usb/device/usb_dc_nrfx.c:1623]: That's right for both comments. Will update it, thanks!

File: drivers/usb/device/usb_dc_nrfx.c [hunk 2]
```diff
@@ -1565,6 +1565,13 @@ int usb_dc_ep_clear_stall(const uint8_t ep)
 		return -EINVAL;
 	}
 
+	if (NRF_USBD_EPISO_CHECK(ep)) {
+		/* ISO Endpoints do not support dtoggle
```
[the remark this answers is not in the document]
Comment (emob-nordic) [reply drivers/usb/device/usb_dc_nrfx.c:1569]: What do You think about:
```
/* ISO transactions do not support a handshake phase so there
 * is no point to clear STALL handshake on ISO Endpoints
 */
```

File: drivers/usb/device/usb_dc_nrfx.c (hunk 1 above)
Comment (emob-nordic) [reply drivers/usb/device/usb_dc_nrfx.c:1623]: What about?
```
/* ISO transactions for full-speed device do not support
 * toggle sequencing and should only send DATA0 PID.
 * There is no point to clear it.
 */
```

File: drivers/usb/device/usb_dc_nrfx.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (jfischer-phytec-iot) [reply drivers/usb/device/usb_dc_nrfx.c:1569]: Just "/* ISO transactions do not support a handshake phase. */

File: drivers/usb/device/usb_dc_nrfx.c (hunk 1 above)
Comment (jfischer-phytec-iot) [reply drivers/usb/device/usb_dc_nrfx.c:1623]: /* ISO transactions for full-speed device do not support
 * toggle sequencing and should only send DATA0 PID.
 */

**Review by jfischer-no — APPROVED** [review]

File: drivers/usb/device/usb_dc_nrfx.c [hunk 3]
```diff
@@ -1565,6 +1565,11 @@ int usb_dc_ep_clear_stall(const uint8_t ep)
 		return -EINVAL;
 	}
 
+	if (NRF_USBD_EPISO_CHECK(ep)) {
+		/* ISO transactions do not support a handshake phase. */
+		return -EIO;
```
Comment (anangl) [inline drivers/usb/device/usb_dc_nrfx.c:1570]: I think that `-EINVAL` would be a more appropriate error code for this case. `-EIO` suggests that some operation involving hardware failed, and here the request is simply wrong.

**Review by anangl — APPROVED** [review]
