### PR TITLE
kernel: device: invert sense of ready bit

### LINKED ISSUE #27985: change in device initialization behavior
There appears to be an unintended behavioral difference resulting from merging #24873: in the past some attempts to retrieve the device pointer for a device that had not yet been initialized succeeded, while they now fail.

The case is demonstrated for `tests/drivers/eeprom` on `native_posix`.  The I2C device initializes at `POST_KERNEL` with priority `CONFIG_I2C_INIT_PRIORITY=60`, while the EEPROM initializes at `POST_KERNEL` with priority `CONFIG_KERNEL_INIT_PRIORITY_DEVICE=50`.  After the merge the attempt by the EEPROM init function to retrieve its parent bus fails because the returned pointer is null as the I2C controller has not yet been initialized.  (The EEPROM driver does not use the I2C bus during initialization.)

I don't think this ever should have worked, and a fix will be to correct the init priorities in this specific case, but it suggests that this will occur in other cases and may be difficult to detect.

### PR DESCRIPTION
**Pull request by pabigot**
The device status ready bit replaced the previous hack of clearing the device API pointer when initialization of the device failed.  It inadvertently changed the behavior of device_get_binding() when invoked before the device was initialized: previously that succeeded for uninitialized devices, after the change it failed.

Multiple driver initializations rely on being able to get a device pointer for something they're going to depend on in their init function, even if that device has not yet been initialized.  Although this is wrong, and would cause faults if the device failed to initialize before use, in practice it has been working.

It's not feasible to identify all the situations where this has occurred, nor to add code to diagnose such cases without changing the state associated with a device to distinguish initialized from initialization success/failure.  Restore the previous behavior until a more holistic solution is developed.

Closes #27985

### CODE REVIEW

**Review by eugmes — COMMENTED** [review]
This fixes #28331 for me.

File: kernel/device.c [hunk 1]
```diff
@@ -64,9 +64,9 @@ void z_sys_init_run_level(int32_t level)
 			z_object_init(dev);
 		}
 
-		if ((entry->init(dev) == 0) && (dev != NULL)) {
-			/* Initialization was successful.
-			 * Set the init status bit so device is declared ready.
+		if ((entry->init(dev) != 0) && (dev != NULL)) {
```
Comment (henrikbrixandersen) [inline kernel/device.c:67]: Shouldn't the NULL check for the dev pointer be negated as well?

Comment (eugmes) [reply kernel/device.c:67]: @henrikbrixandersen: I think that is fine as is, the check is there because `dev` is used to calculate offset in `__device_init_status_start`.

**Review by tbursztyka — APPROVED** [review]
let's keep the old behavior in 2.4, and revert for 2.5 to fix priority issues

**Review by henrikbrixandersen — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
