### PR TITLE
drivers: spi_context: Fix timeout in slave mode and handling of zero-length buffers

### LINKED ISSUE #39594: Possible bug or undocumented behaviour of spi_write
When using spi_buf_set's it will stop processing spi_buf's at the first occurrence of a buf with length 0 even if there are remanining spi_buf's listed after.

**To Reproduce**

```
      struct spi_buf tx_buf_data[] = {{
                                        .buf = bufA,
                                        .len = 10,
                                      },
                                      {
                                        .buf = bufB,
                                        .len = 0,
                                      },
                                      {
                                        .buf = bufC,
                                        .len = 1,
                                      }};
      struct spi_buf_set tx_bufs = {
        .buffers = tx_buf_data,
        .count = ARRAY_SIZE(tx_buf_data),
      };
      spi_write(spi_dev, spi_cfg, &tx_bufs);
```
results in only bufA being sent.
```
      struct spi_buf tx_buf_data[] = {{
                                        .buf = bufA,
                                        .len = 10,
                                      },
                                      {
                                        .buf = bufB,
                                        .len = 1,
                                      },
                                      {
                                        .buf = bufC,
                                        .len = 1,
                                      }};
      struct spi_buf_set tx_bufs = {
        .buffers = tx_buf_data,
        .count = ARRAY_SIZE(tx_buf_data),
      };
      spi_write(spi_dev, spi_cfg, &tx_bufs);
```
results in all 3 buffers being sent.

**Expected behavior**
That all buffers listed in the array will be processed or that the documentation be updated to indicate that a 0 length buffer will stop transmitting any following buffers.

**Impact**
Spent quite a few hours figuring out what was happening.

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.1.31
 - Zephyr v2.6.0 (79a6c07536)
 - Target is a nrf52832

**Additional context**
Having the possibility to have 0 byte buffers listed in a spi_buf is quite useful when crafting dynamic messages without having to manually concat the different buffers.

### LINKED ISSUE #39609: spi: slave: division by zero in timeout calculation
Zephyr 2.6.99 changed <xxx>\zephyr\drivers\spi\spi_context.h\ static inline int spi_context_wait_for_completion(struct spi_context *ctx) by adding a timeout that is dependent on ctx->config->frequency.

`timeout_ms = MAX(ctx->tx_len, ctx->rx_len) * 8 * 1000 / ctx->config->frequency;`

 ctx->config->frequency is not set when nrf52840dk_nrf52840.overlay includes a clock-frequency assignment as shown in the attached.

As a result, ctx->config->frequency is always 0 and a divide by zero error occurs.

The nRFX SPI context structure does not appear to be compatible with Zephyr's. I tried using dev_data->ctx.config->frequency = spi_cfg->frequency; in transceiver function. However, dev_data…frequency is a read-only value.

**To Reproduce**
Replace main.c and proj.conf, and add nrf5240dk_nrf52840 to zephyr\samples\bluetooth\hci_spi sample. When the sample is and programmed onto an nrf52840dk and monitor the comm port. The output should resemble, 

```
*** Booting Zephyr OS build v2.6.99-ncs1  ***
[00:00:00.004,180] <inf> sdc_hci_driver: SoftDevice Controller build revision:
                                         3f 47 70 8e 81 95 4e 86  9d d3 a2 95 8         f6 30 0a |?Gp...N. ......0.
                                         7f 53 49 fd                                             |.SI.
[00:00:00.004,516] <inf> bt_hci_raw: Bluetooth enabled in RAW mode
[00:00:00.004,547] <err> os: ***** USAGE FAULT *****
[00:00:00.004,577] <err> os:   Division by zero
[00:00:00.004,577] <err> os: r0/a1:  0x00008000  r1/a2:  0x00009c40  r2/a3:  0x        0000001
[00:00:00.004,577] <err> os: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x        001f573
[00:00:00.004,577] <err> os:  xpsr:  0x21000000
[00:00:00.004,577] <err> os: Faulting instruction address (r15/pc): 0x0001d822
[00:00:00.004,608] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.004,608] <err> os: Current thread: 0x20001ab8 (unknown)
[00:00:01.459,564] <err> fatal_error: Resetting system
```

**Expected behavior**
The SoftSevice Controller build revision will print and but no error will follow.

**Impact**
Because the only changes <xxx>\zephyr\drivers\spi\spi_context.h is the inline functions spi_context_wait_for_completion, a temporary solution could be to replace spi_contect.h with an earlier release. However, this does not resolve the root cause that frequency is not being set for the struct pointer being passed to spi_context_wait_for_completion().

Because of this, the full impact of this bug is unknown, and the nature of this project, I consider this a crtical bug that needs to be fixed prior to the end of Q4.

**Logs and console output**
Console output included above.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: nRF Connect SDK v1.7.0, Zephyr Project 2.6.9

**Additional context**
Tools install using nRF Connect for Desktop v3.7.1, Toolchain Manager, original sample project zephyr\samples\bluetooth\hci_spi

### PR DESCRIPTION
**Pull request by anangl**
_drivers: spi_context: Do not use transfer timeout in slave mode_

Do not use any timeout in the slave mode, as in this case it is not
known when the transfer will actually start and what the frequency
will be.

Fixes #39609.

_drivers: spi_context: Fix handling of zero-length buffers_

In some cases, it is quite useful to have the possibility to also
include zero-length buffers in a buffer set used in transfers
(for example, when frames in a protocol consist of several parts,
of which some are optional). So far, the behavior of spi_context
update functions was that the transfer in a given direction was
finished when a zero-length buffer was encountered in the buffer
set. Change those functions to simply skip such buffers. Correct
in the same way also the spi_context_buffers_setup() function.

Fixes #39594.

### CODE REVIEW

**Review by Mani-Sadhasivam — APPROVED** [review]
Timeout part LGTM!

File: drivers/spi/spi_context.h [hunk 1]
```diff
@@ -291,10 +301,10 @@ void spi_context_buffers_setup(struct spi_context *ctx,
...
 
 	LOG_DBG("current_tx %p (%zu), current_rx %p (%zu),"
-		    " tx buf/len %p/%zu, rx buf/len %p/%zu",
-		    ctx->current_tx, ctx->tx_count,
-		    ctx->current_rx, ctx->rx_count,
-		    ctx->tx_buf, ctx->tx_len, ctx->rx_buf, ctx->rx_len);
+		" tx buf/len %p/%zu, rx buf/len %p/%zu",
+		ctx->current_tx, ctx->tx_count,
+		ctx->current_rx, ctx->rx_count,
+		ctx->tx_buf, ctx->tx_len, ctx->rx_buf, ctx->rx_len);
```
Comment (mniestroj) [inline drivers/spi/spi_context.h:307]: Not a big deal, but those whitespace-only changes could be part of separate commit.

File: drivers/spi/spi_context.h [hunk 2]
```diff
@@ -311,13 +321,21 @@ void spi_context_update_tx(struct spi_context *ctx, uint8_t dfs, uint32_t len)
...
-			ctx->tx_buf = (const uint8_t *)ctx->current_tx->buf;
-			ctx->tx_len = ctx->current_tx->len / dfs;
-		} else {
-			ctx->tx_buf = NULL;
+			if ((ctx->current_tx->len / dfs) != 0) {
+				ctx->tx_len = ctx->current_tx->len / dfs;
+				ctx->tx_buf =
+					(const uint8_t *)ctx->current_tx->buf;
+				break;
+			}
```
Comment (mniestroj) [inline drivers/spi/spi_context.h:338]: This while-loop here implements the same thing as the white loop in `spi_context_buffers_setup()`, but in a slightly different way. Could create a helper function to skip zero-length buffers, that would be used from `spi_context_update_tx()` and `spi_context_buffers_setup()`?

Another thing that I noticed is that RX and TX handling look very similar. Ideally those would also be deduplicated, as there is a big chance of introducing copy-paste bug when handling rx and tx. Maybe this is not a thing for this PR specifically (though it would be really nice to have), but what about a follow-up PR?

Overall this looks fine to me, the only thing that bugs me is that there are 4 places of really similar code, which takes 4x times longer to read, review and debug.

**Review by mniestroj — COMMENTED** [review]
+1 for timeout changes, some comments for zero-length buffers.

**Comment by anangl** [comment]
Rebased.

File: drivers/spi/spi_context.h (hunk 1 above)
Comment (anangl) [reply drivers/spi/spi_context.h:305]: It's a really straightforward change, made just on the occasion of editing this function. I don't think it deserves a separate commit.

File: drivers/spi/spi_context.h (hunk 2 above)
Comment (anangl) [reply drivers/spi/spi_context.h]: I refactored the implementation so that the common part of those 4 pieces of code is extracted into a helper function. Could you take one more look?

**Review by carlescufi — APPROVED** [review]
This LGTM now

**Comment by anangl** [comment]
Rebased.

File: drivers/spi/spi_context.h (hunk 2 above)
Comment (mniestroj) [reply drivers/spi/spi_context.h]: Much better now, thanks!

File: drivers/spi/spi_context.h (hunk 1 above)
Comment (mniestroj) [reply drivers/spi/spi_context.h:324]: It is straightforward, but I find it easier to navigate `git blame`, `git log` and (if necessary) use `git revert` / `git cherry-pick` if functional changes are separated from whitespace changes.

**Review by mniestroj — APPROVED** [review]
LGTM

File: drivers/spi/spi_context.h (hunk 1 above)
Comment (tbursztyka) [reply drivers/spi/spi_context.h:324]: yep, same here, please separate into its own commit

File: drivers/spi/spi_context.h [hunk 3]
```diff
@@ -331,14 +338,12 @@ void spi_context_update_tx(struct spi_context *ctx, uint8_t dfs, uint32_t len)
...
 	if (!ctx->tx_len) {
-		ctx->tx_count--;
-		if (ctx->tx_count) {
-			ctx->current_tx++;
-			ctx->tx_buf = (const uint8_t *)ctx->current_tx->buf;
-			ctx->tx_len = ctx->current_tx->len / dfs;
-		} else {
-			ctx->tx_buf = NULL;
-		}
+		++ctx->current_tx;
```
Comment (tbursztyka) [inline drivers/spi/spi_context.h:341]: Put a comment here explaining the jump (to differentiate from the spi_context_get_next_buf() call made in spi_context_buffers_setup()). Also I don't see why you change the de/in-crement syntax here (and the order of them as well)

File: drivers/spi/spi_context.h [hunk 4]
```diff
@@ -379,14 +384,12 @@ void spi_context_update_rx(struct spi_context *ctx, uint8_t dfs, uint32_t len)
...
-		ctx->rx_count--;
-		if (ctx->rx_count) {
-			ctx->current_rx++;
-			ctx->rx_buf = (uint8_t *)ctx->current_rx->buf;
-			ctx->rx_len = ctx->current_rx->len / dfs;
-		} else {
-			ctx->rx_buf = NULL;
-		}
+		++ctx->current_rx;
+		--ctx->rx_count;
```
Comment (tbursztyka) [inline drivers/spi/spi_context.h:388]: same here

**Review by tbursztyka — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_context.h (hunk 3 above)
Comment (anangl) [reply drivers/spi/spi_context.h:342]: > Put a comment here explaining the jump (to differentiate from the spi_context_get_next_buf() call made in spi_context_buffers_setup()).

Done.

> Also I don't see why you change the de/in-crement syntax here (and the order of them as well)

I just thought it would make this more readable if both those operators were aligned on the left and these fields were updated in the same order they are passed as parameters in function calls. But it's not in any way important to me and I can reverse the order and move the operators to the right if that's preferred.

File: drivers/spi/spi_context.h (hunk 1 above)
Comment (anangl) [reply drivers/spi/spi_context.h:324]: Done.

**Review by tbursztyka — APPROVED** [review]
