### PR TITLE
logging: Do not set CYCCNTENA to zero in swo backend

### LINKED ISSUE #34341: SWO logging and DWT timing collision
**Describe the bug**
The `log_backend_swo_init` function sets the `CYCCNTENA` bit of the `DWT` register to `0`, disabling the counter (which is necessary for the timing functions.

As a workaroud/fix I added this patch:

```diff
diff --git a/subsys/logging/log_backend_swo.c b/subsys/logging/log_backend_swo.c
index 203896ccd0..21773f3bf9 100644
--- a/subsys/logging/log_backend_swo.c
+++ b/subsys/logging/log_backend_swo.c
@@ -91,7 +91,8 @@ static void log_backend_swo_init(void)
         /* Enable unprivileged access to ITM stimulus ports */
         ITM->TPR  = 0x0;
         /* Configure Debug Watchpoint and Trace */
-        DWT->CTRL = 0x400003FE;
+        DWT->CTRL &= 0x000003FF;
+        DWT->CTRL |= 0x000003FE;
         /* Configure Formatter and Flush Control Register */
         TPI->FFCR = 0x00000100;
         /* Enable ITM, set TraceBusID=1, no local timestamp generation */
```

I'm not sure why the value used before is 0x4... (those bits are supposed to be read only). Maybe I'm missing something.

**To Reproduce**
I executed a simple loop and read the register, and saw it was not updating.

**Expected behavior**
The timing functions work properly with SWO logging enabled

**Impact**
It prevents the timing API to work

**Environment (please complete the following information):**
 - OS: ArchLinux
 - Toolchain Zephyr SDK
 - Version 9f858ac1b6bcf7f9262906f6719d51d5be4404ac

**Additional context**
 - Testing SWO in STM32L4

### PR DESCRIPTION
**Pull request by andresmanelli**
The log_backend_swo_init function sets the CYCCNTENA bit of the DWT
register to 0, disabling the counter (which is necessary for the timing
functions.
Avoid overwriting the CYCCNTENA bit.
Do not try to set read-only bits.

Fixes #34341

Signed-off-by: Andrés Manelli <am@toroid.io>

### CODE REVIEW

File: subsys/logging/log_backend_swo.c [hunk 1]
```diff
@@ -91,7 +91,8 @@ static void log_backend_swo_init(void)
 	/* Enable unprivileged access to ITM stimulus ports */
 	ITM->TPR  = 0x0;
 	/* Configure Debug Watchpoint and Trace */
-	DWT->CTRL = 0x400003FE;
+	DWT->CTRL &= 0x000003FF;
```
Comment (nordic-krch) [inline subsys/logging/log_backend_swo.c:94]: Could you make further improvement and use CMSIS mask and bit fieds here?

Comment (andresmanelli) [reply subsys/logging/log_backend_swo.c]: Yes, i just pushed the changes.

**Review by ioannisg — APPROVED** [review]
Thanks!

**Review by nordic-krch — APPROVED** [review]

**Review by chen-png — APPROVED** [review]
