### PR TITLE
tests.drivers.spi_loopback stm32wb55x transfer multiple buffers with dma

### LINKED ISSUE #25241: tests.drivers.spi_loopback stm32wb55x fails transfering multiple buffers with dma
**Describe the bug**
A deadlock occurs with the fast SPI config, in the multiple buffer testcase of the tests/drivers/spi/spi_loopback application, when enabling the dma and mux transfer on the stm32wb55 soc.

The DMA Tx channel is looping on the DMA Rx channels. The spi client application is changing Tx buffer once the dma Tx irq occurs, but at this time (with SPI FAST config)  the DMA Rx channels has not received the data it expects, so Rx never ends.

**To Reproduce**
- defined the CONFIG_DMA=y and CONFIG_SPI_STM32_DMA=y in the tests/drivers/spi/spi_loopback/boards/nucleo_wb55rg.conf 
- activated peripherals by DT in the tests/drivers/spi/spi_loopback/boards/nucleo_wb55rg.overlay
+CONFIG_SPI_STM32_DMA=y

1. mkdir build; cd build
2. cmake -DBOARD=nucleo_wb55rg
3. make

**Expected behavior**
I: SPI test fast config
I: Start complete multiple
I: CS control inhibited (no GPIO device)
I: Passed

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Screenshots or console output**
I: SPI test fast config
I: Start complete multiple
I: CS control inhibited (no GPIO device)
--> deadlock

**Additional context**

### PR DESCRIPTION
**Pull request by FRASTM**
The spi test application is transferring several buffers and check that Rx one equals Tx one.

In this configuration of the stm32wb It is using the dma communication capability of the SPI feature.
In transmission mode, when the DMA has written all the data to be transmitted (the TCIF
flag is set in the DMA_ISR register), the BSY flag can be monitored to ensure that the SPI
communication is complete.
This is done waiting for the SPI BUSY flag _before_ considering the DMA Tx and Rx completion flags. The DMA callback function, based on the DMA channel irq, will set "a end of transfer" flag.
The main SPI client transfer loop will  then switch the Tx/Rx buffers when both Rx and Tx are completed.

Refer to the Data transmission and reception procedures of the SPI feature in the Ref Manual.

Fix https://github.com/zephyrproject-rtos/zephyr/issues/25241

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
I'm fine with the change, but please rebase first as the 3 first commits are already in tree

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -686,8 +686,62 @@ static int transceive_dma(struct device *dev,
...
+				data->dma_rx.channel,
+				periph_addr,
+				(u32_t)data->ctx.rx_buf,
+				data->ctx.rx_len);
+		}
+		LL_SPI_EnableDMAReq_RX(spi);
+		LL_SPI_EnableDMAReq_TX(spi);
+	}
+
+	/* end of the transfer : all buffers sent/receceived */
```
Comment (FRASTM) [inline drivers/spi/spi_ll_stm32.c:743]: received

**Comment by FRASTM** [comment]
rebased

**Review by erwango — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
