### PR TITLE
tests: pwm_loopback: Capture disable omission issue

### LINKED ISSUE #81199: PWM Loopback Test Misses Disabling Capture
In an effort to add support for PWM functionality with `PWM_CAPTURE`, I observed that omitting to disable capturing between successive tests can trigger either abortion with error or even can raise system fault exceptions. #81198 is the PR that addresses that issue which is thoroughly described in PR's description section.

### PR DESCRIPTION
**Pull request by ioannis-karachalios**
1. As per the PWM API definition, `-EBUSY` should be returned when `pwm_enable_capture` is called while capturing
is already enabled. This commit should deal with adding a `ztest_suite_before_t` function that should disable capturing.
Some tests, though, such as `test_pulse_capture`, execute two sub-tests and so, capturing is disabled in between.
In fact, the omission of `pwm_disable_capture` should not only result in aborting a single test, but it can also raise system exception due to invalid context. This is the case for `z_impl_pwm_capture_cycles` where `z_pwm_capture_cycles_callback` can be fired whilst the routine has already aborted (without disabling capturing) and so `struct z_pwm_capture_cb_data data`, defined within function declaration, should not longer be valid.
2. For the inverted pulse measurements, that should reflect the duty-cycle off interval, the 1% deviation in `test_capture` should be adjusted so it reflects duty-cycle off.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/81199

### CODE REVIEW

**Review by henrikbrixandersen — DISMISSED** [review]

File: tests/drivers/pwm/pwm_loopback/src/test_pwm_loopback.c [hunk 1]
```diff
@@ -98,9 +100,15 @@ static void test_capture(uint32_t period, uint32_t pulse, enum test_pwm_unit uni
...
 	if (flags & PWM_CAPTURE_TYPE_PULSE) {
-		zassert_within(pulse_capture, pulse, pulse / 100,
-			       "pulse capture off by more than 1%");
+		if (flags & PWM_POLARITY_INVERTED) {
+			zassert_within(pulse_capture, period - pulse, (period - pulse) / 100,
+					"pulse capture off by more than 1%");
+		} else {
+			zassert_within(pulse_capture, pulse, pulse / 100,
+					"pulse capture off by more than 1%");
+		}
```
Comment (anangl) [inline tests/drivers/pwm/pwm_loopback/src/test_pwm_loopback.c:109]: This change is not really related to missing `pwm_disable_capture()` calls. It should be done in a separate commit.

File: tests/drivers/pwm/pwm_loopback/src/test_pwm_loopback.c [hunk 2]
```diff
@@ -98,9 +100,15 @@ static void test_capture(uint32_t period, uint32_t pulse, enum test_pwm_unit uni
...
 	}
+
```
Comment (anangl) [inline tests/drivers/pwm/pwm_loopback/src/test_pwm_loopback.c:111]: And this seems to be unneeded.

File: tests/drivers/pwm/pwm_loopback/src/test_pwm_loopback.c (hunk 1 above)
Comment (ioannis-karachalios) [reply tests/drivers/pwm/pwm_loopback/src/test_pwm_loopback.c]: Moved to a separate commit.

File: tests/drivers/pwm/pwm_loopback/src/test_pwm_loopback.c (hunk 2 above)
Comment (ioannis-karachalios) [reply tests/drivers/pwm/pwm_loopback/src/test_pwm_loopback.c]: Removed

**Review by anangl — APPROVED** [review]

**Comment by kartben** [comment]
ping @henrikbrixandersen, if you could please re-approve

**Review by henrikbrixandersen — APPROVED** [review]
