### PR TITLE
Fix all instances of -Waddress-of-packed-member

### LINKED ISSUE #16587: build failures with gcc 9.x
**Describe the bug**
warnings with new compilers that turn into errors when building using sanitycheck

```
In file included from /home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:16:
/home/nashif/Work/zephyrproject/zephyr/include/net/net_pkt.h: In function ‘net_pkt_set_src_ipv6_addr’:
/home/nashif/Work/zephyrproject/zephyr/include/net/net_pkt.h:824:9: error: taking address of packed member of ‘struct net_ipv6_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  824 |         &NET_IPV6_HDR(pkt)->src);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c: In function ‘arp_hdr_check’:
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:537:32: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  537 |      net_ipv4_is_addr_loopback(&arp_hdr->src_ipaddr)) {
      |                                ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c: In function ‘net_arp_input’:
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:590:9: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  590 |         &arp_hdr->src_ipaddr,
      |         ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:602:30: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  602 |       net_ipv4_is_addr_mcast(&arp_hdr->src_ipaddr)) {
      |                              ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:608:42: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  608 |   addr = if_get_addr(net_pkt_iface(pkt), &arp_hdr->dst_ipaddr);
      |                                          ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:635:8: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  635 |        &arp_hdr->src_ipaddr,
      |        ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:655:27: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  655 |   if (net_ipv4_is_my_addr(&arp_hdr->dst_ipaddr)) {
      |                           ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:657:8: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  657 |        &arp_hdr->src_ipaddr,
      |        ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [zephyr/subsys/net/l2/ethernet/CMakeFiles/subsys__net__l2__ethernet.dir/build.make:63: zephyr/subsys/net/l2/ethernet/CMakeFiles/subsys__net__l2__ethernet.dir/arp.c.obj] Error 1
```
**To Reproduce**

Build for native_posix on Fedora 30 with new compiler

### PR DESCRIPTION
**Pull request by carlescufi**
This finally closes #16587 by removing all remaining pieces of code that can trigger the compiler warning after #39192 resolved all the ones in the networking code.

Additional analysis of the problem can be found [here](https://github.com/zephyrproject-rtos/zephyr/issues/16587#issuecomment-930116330).

### CODE REVIEW

File: include/toolchain/common.h [hunk 1]
```diff
@@ -187,6 +187,9 @@
  */
 #define Z_DECL_ALIGN(type) __aligned(__alignof(type)) type
 
+/* Check if a pointer is aligned enough for a particular data type. */
+#define IS_PTR_ALIGNED(ptr, type) ((((uintptr_t)ptr) % __alignof(type)) == 0)
```
Comment (carlescufi) [inline include/toolchain/common.h:191]: @rlubos it would be possible to replace some of the `UNALIGNED_GET()` code in networking with usage of this macro inside an assert statement.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 2]
```diff
@@ -2868,8 +2869,11 @@ static inline void event_conn_upd_init(struct ll_conn *conn,
 		}
 #endif /* CONFIG_BT_CTLR_XTAL_ADVANCED */
 
-		conn->llcp.conn_upd.pdu_win_offset = (uint16_t *)
-			&pdu_ctrl_tx->llctrl.conn_update_ind.win_offset;
+		win_offs = (void *)
+				&pdu_ctrl_tx->llctrl.conn_update_ind.win_offset;
+
+		LL_ASSERT(IS_PTR_ALIGNED(win_offs, uint16_t));
+		conn->llcp.conn_upd.pdu_win_offset = (void *)win_offs;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c:2876]: This is intentionally misaligned as the field is inside a packed PDU struct. memcpy is used to fill this address ensuring there is no memfault.

File: subsys/bluetooth/controller/hci/hci.c [hunk 3]
```diff
@@ -6628,7 +6628,11 @@ static void le_scan_req_received(struct pdu_data *pdu_data,
 static void le_conn_complete(struct pdu_data *pdu_data, uint16_t handle,
 			     struct net_buf *buf)
 {
-	struct node_rx_cc *cc = (void *)pdu_data;
+	void *node = (void *)pdu_data;
+
+	LL_ASSERT(IS_PTR_ALIGNED(node, struct node_rx_cc));
+
+	struct node_rx_cc *cc = node;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/hci/hci.c:6635]: This: https://github.com/zephyrproject-rtos/zephyr/blob/aa83b8d6e3bb5e9fbe35912350e9faa6c6e9c5b2/subsys/bluetooth/controller/ll_sw/lll.h#L391-L401

should have avoided misaligned access?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 2 above)
Comment (carlescufi) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c:2876]: I assume this is true for line 3759, which is currently asserting?

File: subsys/bluetooth/controller/hci/hci.c (hunk 3 above)
Comment (carlescufi) [reply subsys/bluetooth/controller/hci/hci.c:6635]: No, because `node_rx_cc` and `node_rx_pdu` are not packed and have alignment requirements, whereas `struct pdu_data` is packed and thus has zero alignment requirements. Hence, the compiler complains.

**Comment by cvinayak** [comment]
@carlescufi added commits to address required changes related to Broadcast ISO and Connected ISO implementations.

File: subsys/bluetooth/controller/hci/hci.c (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/hci/hci.c]: `__aligned(4)` ensures that inside `strict node_rx_pdu` the field `pdu` is  not unaligned. The allocation by `mem_acquire` ensures runtime aligned memory for each node.

>  because node_rx_cc and node_rx_pdu are not packed and have alignment requirements, whereas struct pdu_data is packed and thus has zero alignment requirements. Hence, the compiler complains.

Agree; on the compile time complain.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: 3759 in this PR?  None of the struct typecast use should assert, if they do, then its genuine misalignment/bug.

File: include/toolchain/common.h (hunk 1 above)
Comment (rlubos) [reply include/toolchain/common.h:191]: Do you have any examples where could this be applied? I had an impression, that with data inside a packet (which the packed struct is casted on) we should not make any assumptions regarding alignment?

File: kernel/mmu.c [hunk 4]
```diff
@@ -380,7 +380,12 @@ static void free_page_frame_list_put(struct z_page_frame *pf)
 {
 	PF_ASSERT(pf, z_page_frame_is_available(pf),
 		 "unavailable page put on free list");
-	sys_slist_append(&free_page_frame_list, &pf->node);
+	/* TODO: Check why this assertion hits */
+	/*PF_ASSERT(pf, IS_PTR_ALIGNED(pf, void*), "unaligned pf pointer");*/
```
Comment (carlescufi) [inline kernel/mmu.c:384]: @dcpleung @andyross any idea why we are hitting this assert if I uncomment it?

File: kernel/userspace.c [hunk 5]
```diff
@@ -466,8 +466,12 @@ static void unref_check(struct z_object *ko, uintptr_t index)
 	sys_bitfield_clear_bit((mem_addr_t)&ko->perms, index);
 
 #ifdef CONFIG_DYNAMIC_OBJECTS
+	/* TODO: check why this assert hits */
+	/*__ASSERT(IS_PTR_ALIGNED(ko, struct dyn_obj), "unaligned z_object");*/
```
Comment (carlescufi) [inline kernel/userspace.c:470]: @dcpleung @andyross any idea why we are hitting this assert if I uncomment it?

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 2 above)
Comment (carlescufi) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: The assert in line 3759 in ull_conn.c hits, but it's not a struct, it's an int16_t @cvinayak \

**Comment by carlescufi** [comment]
> @carlescufi added commits to address required changes related to Broadcast ISO and Connected ISO implementations.

Thank you @cvinayak, added that in the Bluetooth commit.

File: include/toolchain/common.h (hunk 1 above)
Comment (carlescufi) [reply include/toolchain/common.h:191]: No, only in places where you know or suspect that the alignment has been ensured by the allocation itself. If you do not know where the allocation was performed then it wouldn't be useful. But I thought we had some of those in networking, maybe I was wrong.

**Review by cvinayak — APPROVED** [review]
Controller changes look good.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: > I assume this is true too for line 3759, which is currently asserting?

Yes.

File: kernel/mmu.c [hunk 6]
```diff
@@ -380,7 +380,12 @@ static void free_page_frame_list_put(struct z_page_frame *pf)
...
+	/* The structure is packed, which ensures that this is true */
+	void *node = (void *)pf;
```
Comment (jhedberg) [inline kernel/mmu.c:386]: I don't think the explicit typecast is needed. Isn't one of the main feature of void pointers that you don't need to do explicit casts to/from them.

File: subsys/bluetooth/controller/hci/hci.c [hunk 7]
```diff
@@ -3728,16 +3728,23 @@ static void le_cis_request(struct pdu_data *pdu_data,
...
 
-	req = (void *)pdu_data;
-
 	sep = meta_evt(buf, BT_HCI_EVT_LE_CIS_REQ, sizeof(*sep));
 	sep->acl_handle = sys_cpu_to_le16(node_rx->hdr.handle);
+
+	/* Check for pdu field being aligned before accessing CIS established
+	 * event.
+	 */
+	node = (void *)pdu_data;
```
Comment (jhedberg) [inline subsys/bluetooth/controller/hci/hci.c:3744]: Same here regarding unnecessary explicit typecast

File: subsys/bluetooth/controller/hci/hci.c [hunk 8]
```diff
@@ -3769,10 +3777,16 @@ static void le_cis_established(struct pdu_data *pdu_data,
...
 	lll_cis_c = is_central ? &lll_cis->tx : &lll_cis->rx;
 	lll_cis_p = is_central ? &lll_cis->rx : &lll_cis->tx;
-	est = (void *)pdu_data;
 
 	sep = meta_evt(buf, BT_HCI_EVT_LE_CIS_ESTABLISHED, sizeof(*sep));
 
+	/* Check for pdu field being aligned before accessing CIS established
+	 * event.
+	 */
+	node = (void *)pdu_data;
```
Comment (jhedberg) [inline subsys/bluetooth/controller/hci/hci.c:3786]: And here. I guess it doesn't make sense to to go pointing out every single place in this PR, but if you agree it be good to remove these explicit casts.

File: kernel/mmu.c (hunk 6 above)
Comment (carlescufi) [reply kernel/mmu.c:386]: Absolutely, will check and remove. Thanks!

Comment (carlescufi) [reply kernel/mmu.c]: Should be done now @jhedberg, thanks for catching this.

Comment (carlescufi) [reply kernel/mmu.c]: I've also removed them from the inverse assignment (void to a data type) since those are not necessary either.

**Review by jhedberg — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

File: drivers/sensor/bmi160/bmi160.c [hunk 9]
```diff
@@ -790,9 +790,11 @@ static inline void bmi160_gyr_channel_get(const struct device *dev,
 					  struct sensor_value *val)
 {
 	struct bmi160_data *data = to_data(dev);
+	void *gyr = data->sample.gyr;
 
-	bmi160_channel_convert(chan, data->scale.gyr,
-			       data->sample.gyr, val);
+	/* Assert below triggers with native_posix. */
+	/*__ASSERT_NO_MSG(IS_PTR_ALIGNED(gyr, uint16_t));*/
```
Comment (carlescufi) [inline drivers/sensor/bmi160/bmi160.c:796]: @andyross @dcpleung @peter-mitsis  Again, I am hitting this on native_posix which is x86-32.

File: kernel/mmu.c (hunk 4 above)
Comment (andyross) [reply kernel/mmu.c:384]: I'm not the expert on paging, but per the comment at the top of the struct in kernel/include/mmu.h it's intentionally misaligned for size optimization.  z_page_frame is a 5- or 9-byte struct (one pointer and a flags byte) and the intent seems to be to pack them all together, alignment be damned.

File: kernel/userspace.c (hunk 5 above)
Comment (andyross) [reply kernel/userspace.c:470]: You want to be checking IS_PTR_ALIGNED(dyn, struct dyn_obj), no?  It would be pathological, but you could imagine a kernel object aligned on N*8 + 4, with a (8-byte-aligned) dyn_obj field offset 4 or 12 bytes in, and that would be legal.

Beyond that possibility, the question is why this particular kernel object got misaligned.  And as this is a dynamic object, that points to a glitch in the allocator?  Someone should definitely look at this.

Comment (dcpleung) [reply kernel/userspace.c:470]: could be that the object is not allocated using the aligned alloc function?

**Review by rlubos — APPROVED** [review]
LGTM

File: kernel/mmu.c (hunk 4 above)
Comment (carlescufi) [reply kernel/mmu.c:384]: OK, I will leave out the assertion then. Thanks!

File: kernel/userspace.c (hunk 5 above)
Comment (carlescufi) [reply kernel/userspace.c:470]: >You want to be checking IS_PTR_ALIGNED(dyn, struct dyn_obj),

It really is the same, because the `struct z_object` is the first member of `struct dyn_obj`. But sure, let me fix that.

Comment (carlescufi) [reply kernel/userspace.c:470]: >could be that the object is not allocated using the aligned alloc function?

@dcpleung I have no idea, could you check?

File: kernel/userspace.c [hunk 10]
```diff
@@ -466,8 +466,11 @@ static void unref_check(struct z_object *ko, uintptr_t index)
 	sys_bitfield_clear_bit((mem_addr_t)&ko->perms, index);
 
 #ifdef CONFIG_DYNAMIC_OBJECTS
-	struct dyn_obj *dyn =
-			CONTAINER_OF(ko, struct dyn_obj, kobj);
+	void *vko = ko;
+
+	struct dyn_obj *dyn = CONTAINER_OF(vko, struct dyn_obj, kobj);
+	/* TODO: check why this assert hits */
+	/*__ASSERT(IS_PTR_ALIGNED(dyn, struct dyn_obj), "unaligned z_object");*/
```
Comment (andyross) [inline kernel/userspace.c:473]: Just to repeat my comment from elsewhere: this points to some suspicious behavior in the kernel dynamic object allocator.  We should probably open a bug to make sure it gets looked at.  Given the architecture, it's not illegal to misalign structs, but we shouldn't be doing it without a good reason.

(If I had to make a wild guess, it was written for i386 and 4-byte-aligns everything, so misses half the time for structs with 64 bit pointers.)

**Review by andyross — APPROVED** [review]

File: kernel/userspace.c (hunk 5 above)
Comment (dcpleung) [reply kernel/userspace.c]: `z_impl_k_object_alloc()` is using `obj_align_get()` to feed alignment to memory allocation, where it should align to `sizeof(void *)`.

Does `IS_PTR_ALIGNED(dyn, struct dyn_obj)` work?

File: kernel/userspace.c (hunk 10 above)
Comment (carlescufi) [reply kernel/userspace.c:473]: Indeed, see here: https://github.com/zephyrproject-rtos/zephyr/issues/41062
