### PR TITLE
shell: handle reprint correctly when output crosses line boundary

### LINKED ISSUE #82155: shell prompt does not properly handle editing multiline commands
**Describe the bug**
When inputting long commands that wrap across multiple lines in the terminal, editing input on the previous line does not function correctly. When pressing backspace, the cursor will jump to the previous line, and any attempt to insert characters into the terminal will result in the current command being edited being reprinted at the wrong location.

This has been reproduced within the UART shell backend.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
   `mimxrt1060_evk`
 - What have you tried to diagnose or workaround this issue?
   Running `resize` to expand the terminal width works around the issue, but a sufficiently long command will still expose this problem.
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
   I don't believe so, it seems like the logic for reprinting shell commands just doesn't handle multiline editing.

**To Reproduce**
1. `west build -p always -b mimxrt1060_evk samples/hello_world/ -DCONFIG_SHELL=y -DCONFIG_SHELL_DEFAULT_TERMINAL_WIDTH=20` (should reproduce on other platforms as well)
2. `west flash`
3. Enter the text "the quick brown fox jumps over the lazy dog" into the terminal
4. Use the arrow keys, and attempt to replace the word "quick" with "slow"
5. See terminal print in incorrect location

Example:

Screen Recording 2024-11-27 at 11 19 22

**Expected behavior**
It should be possible to edit multiline commands within the shell

**Impact**
Mildly annoying for long command inputs

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04 LTS
 - Toolchain Zephyr SDK 16.5-1
 - Commit SHA or Version used 318492b5bf2c34

### PR DESCRIPTION
**Pull request by danieldegrasse**
When reprinting the shell command buffer with long user inputs, the reprinted buffer may cross a line boundary, and require a newline to be printed. For these cases, print the command buffer character by character, inserting newlines as appropriate.

Fixes #82155

### CODE REVIEW

File: subsys/shell/shell_ops.c [hunk 1]
```diff
@@ -250,8 +250,29 @@ static void reprint_from_cursor(const struct shell *sh, uint16_t diff,
 			z_shell_raw_fprintf(sh->fprintf_ctx, "*");
 		}
 	} else {
-		z_shell_fprintf(sh, SHELL_NORMAL, "%s",
-			      &sh->ctx->cmd_buff[sh->ctx->cmd_buff_pos]);
+		/* Check if the reprint will cross a line boundary */
+		int line_len = sh->ctx->cmd_buff_len + z_shell_strlen(sh->ctx->prompt);
+		int buff_pos = sh->ctx->cmd_buff_pos + z_shell_strlen(sh->ctx->prompt);
+
+		if ((buff_pos / sh->ctx->vt100_ctx.cons.terminal_wid) !=
```
Comment (danieldegrasse) [inline subsys/shell/shell_ops.c:257]: I don't really like the requirement to perform division here to check if the reprint will cross a terminal width boundary, but I'm not sure how else to check this effectively- the condition we need to detect is one where the command buffer position is on a different line than the end of the command buffer

**Comment by danieldegrasse** [comment]
> The only related issue I'm aware of, which I decided not to address due to its low priority, is handling wrapping when a command is longer than the entire terminal window—specifically, when it spans more lines than the terminal can display.

This is the issue this change addresses- the linked issue in this PR should provide steps to reproduce it. Do you think the issue is not worth addressing? I'm aware that running `resize` will work around this, but it seems like we should support multiline command editing for longer commands

**Review by EmilioCBen — APPROVED** [review]

**Comment by jakub-uC** [comment]
@danieldegrasse
The `resize` command is useful when changing the default terminal width. Other than that, everything should work as expected. The `resize` command must be executed when you change the terminal width, for example, from 80x10 to 70x10. The shell must be aware of how text is being displayed in the terminal to allow proper navigation through the command using the arrow keys, backspace, or delete.

The issue I am referring to occurs when the terminal is, let's say, 80 characters wide and 10 lines high. If your command doesn't fit within that 80x10 area — meaning the command exceeds ~800 characters — the shell will not handle cursor movement correctly between line 1 and line 10+. **Please confirm you are fixing this.**

If the terminal is 80x10 and your long command takes up to 6 lines (over ~500 characters), everything should still work correctly, even though the command is a multiline command.

File: subsys/shell/shell_ops.c (hunk 1 above)
Comment (jakub-uC) [reply subsys/shell/shell_ops.c:257]: I understand that you're wrapping each line manually. From my experience, most terminals automatically handle line wrapping when printing long commands. Could you share more details about the issue you're facing? What terminal and settings are you using?

**Comment by danieldegrasse** [comment]
> If the terminal is 80x10 and your long command takes up to 6 lines (over ~500 characters), everything should still work correctly, even though the command is a multiline command.

At least for me in a UART terminal (with minicom) this is not the case. Here is what I see when editing a multiline command:

https://github.com/user-attachments/assets/60608178-b6fe-4bae-9475-a13b312dd867

**Comment by jakub-uC** [comment]
@danieldegrasse

Indeed, there are issues when running the example for `qemu_x86` using the `west build -t run` command. Similarly, I encountered the same problem when using the `minicom` terminal with its default settings (which I had never tested before) on the nRF52840 DK.

Interestingly, the modification you showed in the video works perfectly fine in the `picocom` and `Putty` terminals, which I used during development to test this feature.

Please allow me until tomorrow to investigate this further. If I can’t come up with a reasonable solution, we can proceed with merging your changes. I sincerely apologize for the inconvenience; I didn’t anticipate such behavior.

**Comment by danieldegrasse** [comment]
> @danieldegrasse
> 
> Indeed, there are issues when running the example for `qemu_x86` using the `west build -t run` command. Similarly, I encountered the same problem when using the `minicom` terminal with its default settings (which I had never tested before) on the nRF52840 DK.
> 
> Interestingly, the modification you showed in the video works perfectly fine in the `picocom` and `Putty` terminals, which I used during development to test this feature.
> 
> Please allow me until tomorrow to investigate this further. If I can’t come up with a reasonable solution, we can proceed with merging your changes. I sincerely apologize for the inconvenience; I didn’t anticipate such behavior.

No worries, and no rush- sounds like I need to switch to picocom 😄

**Comment by dleach02** [comment]
@jakub-uC and update on your investigation?

**Comment by jakub-uC** [comment]
Sorry for the delay—I was busy with some other tasks. Let's go ahead and merge it. If I find a better way to handle this, I'll open a PR

**Review by jakub-uC — APPROVED** [review]
