### PR TITLE
Fix net_if_send_data for non-l2 iface 

### LINKED ISSUE #24382: disco_l475_iot1 not working with samples/net/wifi
**Describe the bug**
The ST disco_l475_iot1 is not working with samples/net/wifi when enable DHCPv4

**To Reproduce**
Add below config at prj.conf
_CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_DHCPV4=y_

_west build -b disco_l475_iot1 samples/net/wifi
west flash_

**Expected behavior**
board be capable to have console, connect to wifi network and send a ping.

**Screenshots or console output**
```
[uart:~$ *** Booting Zephyr OS build zephyr-v2.2.0-1408-gacc0e9025d5e  ***
[00:00:00.539,000] <inf> net_config: Initializing network
[00:00:00.539,000] <inf> net_config: Running dhcpv4 client...
uart:~$ \���񆿆�ο��YjلO}R��B���᭟�o�1߻��ﻏ_y������׾����ϝo��q]��5�N�O������������������O�
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.11.2
 - Commit SHA or Version used: mainline

### PR DESCRIPTION
**Pull request by loicpoulain**
Some services like DHCHPv4 directly send raw packets to the iface.
This causes issue when the iface does not implement l2, e.g.
because it is a socket offload interface. fix that.

Fixes: #24382
Signed-off-by: Loic Poulain <loic.poulain@linaro.org>

### CODE REVIEW

File: subsys/net/ip/net_if.c [hunk 1]
```diff
@@ -356,6 +356,12 @@ enum net_verdict net_if_send_data(struct net_if *iface, struct net_pkt *pkt)
 		goto done;
 	}
 
+	if (unlikely(!net_if_l2(iface))) {
```
Comment (tbursztyka) [inline subsys/net/ip/net_if.c:359]: if (IS_ENABLED(CONFIG_NET_OFFLOAD) && unliely()...

Comment (loicpoulain) [reply subsys/net/ip/net_if.c:359]: @tbursztyka ok, assuming CONFIG_NET_OFFLOAD would be the only reason l2 is NULL

Comment (tbursztyka) [reply subsys/net/ip/net_if.c:359]: Yes, that's the only case so far

File: subsys/net/ip/net_if.c [hunk 2]
```diff
@@ -356,6 +356,12 @@ enum net_verdict net_if_send_data(struct net_if *iface, struct net_pkt *pkt)
 		goto done;
```
Comment (jukkar) [inline subsys/net/ip/net_if.c:356]: The change is ok. Just minor nit for the commit message, there is now double `net: net_...` there which is quite pointless, could you change that to `net: if: ...`

Comment (loicpoulain) [reply subsys/net/ip/net_if.c:356]: fixed

**Review by jukkar — APPROVED** [review]
