### PR TITLE
Fixes mimxrt10xx: Wrong I2C transfer status #13819

### LINKED ISSUE #13819: mimxrt10xx: Wrong I2C transfer status
**Describe the bug**
When running samples/drivers/i2c_scanner, application wrongly reports slaves found on multiple addresses. It is actually due to transfer success instead of failure. Interesting to note that only odd addresses are reported. Logic analyzer screenshot below. 

**To Reproduce**
1. cd samples/drivers/i2c_scanner
2. west build -b mimxrt1064_evk

**Expected behavior**
Only connected slave reported
I2C transfer failure on NAK

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Screenshots or console output**
***** Booting Zephyr OS v1.14.0-rc1-458-g41dad49 *****
Starting i2c scanner...
0x 5 FOUND
0x 7 FOUND
0x 9 FOUND
0x b FOUND
0x d FOUND
0x f FOUND
0x11 FOUND
0x13 FOUND
0x15 FOUND
0x17 FOUND
0x19 FOUND
0x1a FOUND
0x1c FOUND
0x1e FOUND
0x20 FOUND
0x22 FOUND
0x24 FOUND
0x26 FOUND
0x28 FOUND
0x2a FOUND
0x2c FOUND
0x2e FOUND
0x30 FOUND
0x32 FOUND
0x34 FOUND
0x36 FOUND
0x38 FOUND
0x3a FOUND
0x3c FOUND
0x3e FOUND
0x40 FOUND
0x42 FOUND
0x44 FOUND
0x46 FOUND
0x48 FOUND
0x4a FOUND
0x4c FOUND
0x4e FOUND
0x50 FOUND
0x52 FOUND
0x54 FOUND
0x56 FOUND
0x58 FOUND
0x5a FOUND
0x5c FOUND
0x5e FOUND
0x60 FOUND
0x62 FOUND
0x64 FOUND
0x66 FOUND
0x68 FOUND
0x6a FOUND
0x6c FOUND
0x6e FOUND
0x70 FOUND
0x72 FOUND
0x74 FOUND
0x76 FOUND

0x05_transfer_wrongly_reported

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK

### PR DESCRIPTION
**Pull request by CristXu**
Fixes : mimxrt10xx: Wrong I2C transfer status zephyrproject-rtos#13819 

Adding a delay between a transfer, then detect the NACK flag

Signed-off-by: crist.xu@nxp.com <crist.xu@nxp.com>

### CODE REVIEW

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 1]
```diff
@@ -105,6 +105,22 @@ static uint32_t mcux_lpi2c_convert_flags(int msg_flags)
...
 
+volatile int s_i;
+bool HAL_I2C_IsDeviceReady(LPI2C_Type *pI2C, uint16_t DevAddress,
+		uint32_t baudrate)
+{
+	bool isRdy = 0;
+	uint32_t safeDelay = 10000 * 150 / (baudrate / 1000);
+
+	LPI2C_MasterStart(pI2C, DevAddress, kLPI2C_Write);
+	for (s_i = 0; s_i < safeDelay; s_i++) {
```
Comment (pabigot) [inline drivers/i2c/i2c_mcux_lpi2c.c:116]: Can you replace this with `k_busy_wait()`?   It's gotta be a time-based delay, and an empty loop isn't the right way to do that.

**Review by pabigot — CHANGES_REQUESTED** [review]
I can confirm this fixes scanning, but I'm not convinced it's a good idea to have a delay of unclear duration before every transfer.

File: drivers/i2c/i2c_mcux_lpi2c.c (hunk 1 above)
Comment (CristXu) [reply drivers/i2c/i2c_mcux_lpi2c.c]: ok, Has updated

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 2]
```diff
@@ -16,6 +16,8 @@
 LOG_MODULE_REGISTER(mcux_lpi2c);
 
 #include "i2c-priv.h"
+#define DELAY_TIME(baudrate) \
+	(1e6 * 10 * 10000 * 150 / (baudrate / 1000) / 600000000)
```
Comment (MaureenHelm) [inline drivers/i2c/i2c_mcux_lpi2c.c:20]: This looks like it uses the system clock frequency (600 MHz), will it work with other clock frequencies? You probably need to use `clock_control_get_rate` similar to `mcux_lpi2c_configure`.

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

**Comment by MaureenHelm** [comment]
Please also update the PR summary to say `Fixes #xxxxx`
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

File: drivers/i2c/i2c_mcux_lpi2c.c (hunk 2 above)
Comment (pabigot) [reply drivers/i2c/i2c_mcux_lpi2c.c:20]: Yes; and the logic behind this calculation needs some explanation. Why is the numerator 1.5E12?

Comment (CristXu) [reply drivers/i2c/i2c_mcux_lpi2c.c:20]: Hi，Be honest,  i test many values, the 10000 * 150 / (baudrate / 1000) is an experience one. I do not know why too.  But it works. bigger is maybe ok, but lower, not.
The values: the 1e6 means -> us, 10 is a simmliar ticks with (for (i=0;i<xx;i++), this will expand to 10 instructs costs about 
10 ticks), the 600000000 is sure, the cpu frequency.

Comment (CristXu) [reply drivers/i2c/i2c_mcux_lpi2c.c:20]: > This looks like it uses the system clock frequency (600 MHz), will it work with other clock frequencies? You probably need to use `clock_control_get_rate` similar to `mcux_lpi2c_configure`.

Ok， I will update the code soon.

**Review by pabigot — CHANGES_REQUESTED** [review]
Looking more closely: this approach will not work.

The solution involves generating a start condition followed by a stop condition before every call to the I2C transfer function.  This will break transactions that span multiple calls, i.e. starting in one then finishing in another.

(That the cost of doing the check affects every transaction, and that the duration of the delay is not based on analysis, is also a concern: but the fact this will break I2C is what rules it out.)

**Comment by CristXu** [comment]
> Looking more closely: this approach will not work.
> 
> The solution involves generating a start condition followed by a stop condition before every call to the I2C transfer function. This will break transactions that span multiple calls, i.e. starting in one then finishing in another.
> 
> (That the cost of doing the check affects every transaction, and that the duration of the delay is not based on analysis, is also a concern: but the fact this will break I2C is what rules it out.)

Hi, I do some changes, move the delay inside the transfer body, remove the start + stop, but the delay time is neccessary still. Or Adding a judge, so we can add this delay only when run the i2c scan command?

File: drivers/i2c/i2c_mcux_lpi2c.c [hunk 3]
```diff
@@ -161,6 +163,12 @@ static int mcux_lpi2c_transfer(struct device *dev, struct i2c_msg *msgs,
 			return -EIO;
 		}
 
+		k_busy_wait(DELAY_TIME(config->bitrate));
```
Comment (pabigot) [inline drivers/i2c/i2c_mcux_lpi2c.c:166]: If you do this wait only when `msgs->len == 0` does that fix the problem?  Because that's the case that isn't being handled correctly by the HAL.

I'd still like to see the delay duration based on something that makes sense, say a specific number of cycles of the I2C clock.

Comment (CristXu) [reply drivers/i2c/i2c_mcux_lpi2c.c]: Hi， Yes ， I add one if(msgs->len == 0), it works. Now the delay time is beyond CPU_FREQ & i2c's baudrate.

File: drivers/i2c/i2c_mcux_lpi2c.c (hunk 2 above)
Comment (CristXu) [reply drivers/i2c/i2c_mcux_lpi2c.c]: > This looks like it uses the system clock frequency (600 MHz), will it work with other clock frequencies? You probably need to use `clock_control_get_rate` similar to `mcux_lpi2c_configure`.

Hi, I have updated the macro with a function to get the CPU_FREQ, But I use CLOCK_GetCoreSysClkFreq instead, because the clock_control_get_rate can not return the core_freq, or do we need to add this into the mcux_ccm_get_subsys_rate()?

**Review by pabigot — CHANGES_REQUESTED** [review]
Please change this to:

```
/* Wait for the duration of 12 bits to detect a NAK after a bus
 * address scan.  (10 appears sufficient, 20% safety factor.)
 */
#define SCAN_DELAY_US(baudrate) (12 * USEC_PER_SEC / baudrate)
```

and update the name of the macro below.  This decouples from the clock rate (which is irrelevant once we wait for microseconds) and makes the purpose of the delay more clear.

**Comment by CristXu** [comment]
> Please change this to:
> 
> ```
> /* Wait for the duration of 12 bits to detect a NAK after a bus
>  * address scan.  (10 appears sufficient, 20% safety factor.)
>  */
> #define SCAN_DELAY_US(baudrate) (12 * USEC_PER_SEC / baudrate)
> ```
> 
> and update the name of the macro below. This decouples from the clock rate (which is irrelevant once we wait for microseconds) and makes the purpose of the delay more clear.

Hi， Yes， it works, I have updated.

**Review by pabigot — APPROVED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Thanks @pabigot for your help. This change looks much better now.

@CristXu please amend the commit message to indicate this change is for the mcux i2c driver, something like this:
```
drivers: i2c: Fix mcux driver transfer status after NACK

Adds a delay after transferring zero-length messages to correctly detect a NACK.
```

**Comment by CristXu** [comment]
> Thanks @pabigot for your help. This change looks much better now.
> 
> @CristXu please amend the commit message to indicate this change is for the mcux i2c driver, something like this:
> 
> ```
> drivers: i2c: Fix mcux driver transfer status after NACK
> 
> Adds a delay after transferring zero-length messages to correctly detect a NACK.
> ```

Updated

**Review by MaureenHelm — APPROVED** [review]
