### PR TITLE
drivers: spi_mcux_flexcomm: Fix spi slave count check

### LINKED ISSUE #92542: NXP: RW61x: Flexcomm SPI CS
### Describe the bug

Configuring software (gpio) chip selects appears to not work, the HW CS0 is stuck enabled and activates with transactions to other devices on the bus.

If you attempt to configure the original CS0 as a gpio based CS, the entire spi pin muxing breaks and clock, miso and mosi stop functioning.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Define a board or overlay which uses a flexcomm spi with multiple slaves (`cs-gpio` not overlapping CS0)
2. capture CS0 pin state with a logic analyser, you will see it goes low with every transaction to any slave

Test 2

1. Define a board or overlay which uses a flexcomm spi with one or more slaves, overlap the CS0 with its associated CS
2. Capture sck with a logic analyser, you will see no activity.

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- Ubuntu 24.04 LTS
- SHA: 4bd1d39c67df
- Board: custom RW610 based.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by decsny**
The current implementation checking for the validity of the spi slave number is wrong. First of all, there is an off by one error where it allows SPI_CHIP_SELECT_COUNT value as a valid slave, when really it should be that value minus one. Secondly, it doesn't take into account the fact that having software controlled GPIO CS can technically have any number of slaves on the bus. So fix by finding the max of these two values and fixing the off by one mistake. Also, for RW612, only one HW native CS is available due to SOC pinmux limitations.

Fixes #92542

### CODE REVIEW

**Review by tbursztyka — DISMISSED** [review]

File: drivers/spi/spi_mcux_flexcomm.c [hunk 1]
```diff
@@ -29,7 +29,12 @@ LOG_MODULE_REGISTER(spi_mcux_flexcomm, CONFIG_SPI_LOG_LEVEL);
 
 #include "spi_context.h"
 
+#ifdef CONFIG_SOC_SERIES_RW6XX
+#define SPI_CHIP_SELECT_COUNT	1
+#else
 #define SPI_CHIP_SELECT_COUNT	4
+#endif
```
Comment (mmahadevan108) [inline drivers/spi/spi_mcux_flexcomm.c:37]: Can you use this available in the SDK chip features file `FSL_FEATURE_SPI_SSEL_COUNT` instead of fixing the value to 4

File: drivers/spi/spi_mcux_flexcomm.c [hunk 2]
```diff
@@ -29,7 +29,12 @@ LOG_MODULE_REGISTER(spi_mcux_flexcomm, CONFIG_SPI_LOG_LEVEL);
 
 #include "spi_context.h"
 
+#ifdef CONFIG_SOC_SERIES_RW6XX
+#define SPI_CHIP_SELECT_COUNT	1
```
Comment (mmahadevan108) [inline drivers/spi/spi_mcux_flexcomm.c:34]: Please add a comment as to why this was fixed to 1. This there in the commit message, but also helps to have in the code.

**Comment by mmahadevan108** [comment]
@decsny for "Also, for RW612, only one HW native CS is available due to SOC pinmux limitations."

Should this be a change to the RW612 features file to make `FSL_FEATURE_SPI_SSEL_COUNT` 1 instead of its current value of 4

File: drivers/spi/spi_mcux_flexcomm.c (hunk 2 above)
Comment (decsny) [reply drivers/spi/spi_mcux_flexcomm.c:34]: I think it is self explanatory that it's because that SOC series only has one chip select available, but I can put a comment.

**Comment by decsny** [comment]
> @decsny for "Also, for RW612, only one HW native CS is available due to SOC pinmux limitations."
> 
> Should this be a change to the RW612 features file to make `FSL_FEATURE_SPI_SSEL_COUNT` 1 instead of its current value of 4

I don't know , because that file AFAIK is auto generated based on the IP, and the IP does have 4 CS, but the SOC pinmux limits it. You will have to find out from NPI team how that affects the process. For now, I don't want to maintain an extra patch in the zephyr HAL module for this, especially considering, we don't even use that macro in zephyr.

> Can you use this available in the SDK chip features file FSL_FEATURE_SPI_SSEL_COUNT instead of fixing the value to 4

No, I don't think we should use these SDK macros at all in Zephyr, not just this one specifically. All the hardware features should be described by DT, not random macros in external modules. But I do not want to expand the scope of this PR to add the feature of new DT properties right now, nor do I want to add a technical debt by coupling the zephyr code further to an external module. So I will leave as is for now.

**Review by tbursztyka — DISMISSED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
