### PR TITLE
bluetooth: controller: Fixing race re. adv disable in HDC

### LINKED ISSUE #18584: BT LL assert on LL/CON/ADV/BV-04-C
**Describe the bug**
The BLE LL crashes during conformance testing, in LL/CON/ADV/BV-04-C
With a controller only build, split LL.

**Expected behavior**
No crash

**Screenshots or console output**
```
LL/CON/ADV/BV-04-C [Accepting Connection Request after Directed Advertising] test started...
d_01: @00:21:46.802490  [00:21:46.802,490] <dbg> bt_ctlr_llsw_nordic_lll_filter.rpa_refresh_start: 
d_02: @00:21:46.843135  [00:21:46.843,109] <dbg> bt_ctlr_llsw_nordic_lll_filter.rpa_refresh_start: 
d_02: @00:21:47.820373  [00:21:47.820,373] <dbg> bt_ctlr_llsw_nordic_lll_filter.rpa_refresh_start: 
d_01: @00:21:48.082489  [00:21:48.082,489] <err> bt_ctlr_llsw_ull_adv: assert: 'adv->link_cc_free' failed
d_01: @00:21:48.082489  @ subsys/bluetooth/controller/ll_sw/ull_adv.c:1134:
d_01: @00:21:48.082489  FATAL: >>> ZEPHYR FATAL ERROR 3: Kernel oops
d_01: @00:21:48.082489  FATAL: Current thread: 0x565df840 (unknown)
d_01: @00:21:48.082489  FATAL: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
 - Commit SHA: aed767a98c00bc11b5455fb60c3a3d8f0bda37c0 (but has been happening for at least 2 weeks)
 - nrf52_bsim with EDTT tests

**Additional context:**
Adding a delay in the middle of the test code avoids the issue (just before re-enabling the scanner)

Labeling as low until it is understood better

### PR DESCRIPTION
**Pull request by erbr-ot**
Re. issue "BT LL assert on LL/CON/ADV/BV-04-C #18584"

Fixes #18584

Signed-off-by: Erik Brockhoff <erbr@oticon.com>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_adv.c [hunk 1]
```diff
@@ -1200,6 +1200,22 @@ static inline u8_t disable(u16_t handle)
 		return BT_HCI_ERR_CMD_DISALLOWED;
 	}
 
+#if defined(CONFIG_BT_PERIPHERAL)
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_adv.c]: Move this before the primary ticker is stopped. and re-init ret_cb thereafter for stopping the primary.

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_adv.c (hunk 1 above)
Comment (erbr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c]: Is this what you mean?
```
static inline u8_t disable(u16_t handle)
{
	volatile u32_t ret_cb = TICKER_STATUS_BUSY;
	struct ll_adv_set *adv;
	void *mark;
	u32_t ret;

	adv = ull_adv_is_enabled_get(handle);
	if (!adv) {
		return BT_HCI_ERR_CMD_DISALLOWED;
	}

	mark = ull_disable_mark(adv);
	LL_ASSERT(mark == adv);

#if defined(CONFIG_BT_PERIPHERAL)
	if (adv->lll.is_hdcd) {
		ret = ticker_stop(TICKER_INSTANCE_ID_CTLR,
				  TICKER_USER_ID_THREAD, TICKER_ID_ADV_STOP,
				  ull_ticker_status_give, (void *)&ret_cb);
		ret = ull_ticker_status_take(ret, &ret_cb);
		if (ret) {
			mark = ull_disable_mark(adv);
			LL_ASSERT(mark == adv);

			return BT_HCI_ERR_CMD_DISALLOWED;
		}
	}
	ret_cb = TICKER_STATUS_BUSY;
#endif

	ret = ticker_stop(TICKER_INSTANCE_ID_CTLR, TICKER_USER_ID_THREAD,
			  TICKER_ID_ADV_BASE + handle,
			  ull_ticker_status_give, (void *)&ret_cb);

	ret = ull_ticker_status_take(ret, &ret_cb);
	if (ret) {
		mark = ull_disable_mark(adv);
		LL_ASSERT(mark == adv);

		return BT_HCI_ERR_CMD_DISALLOWED;
	}

	ret = ull_disable(&adv->lll);
	LL_ASSERT(!ret);

	mark = ull_disable_unmark(adv);
	LL_ASSERT(mark == adv);

#if defined(CONFIG_BT_PERIPHERAL)
	if (adv->lll.conn) {
		conn_release(adv);
	}
#endif /* CONFIG_BT_PERIPHERAL */

	adv->is_enabled = 0U;

#if defined(CONFIG_BT_CTLR_PRIVACY)
	if (IS_ENABLED(CONFIG_BT_OBSERVER) && !ull_scan_is_enabled_get(0)) {
		ull_filter_adv_scan_state_cb(0);
	}
#endif /* CONFIG_BT_CTLR_PRIVACY */

	return 0;
}
```

**Review by cvinayak — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
