### PR TITLE
serial: uart_nrfx_uarte: graceful async power down

### LINKED ISSUE #31930: uart_nrfx_uarte: `CONFIG_UART_ASYNC_API` with `CONFIG_PM_DEVICE` breaks
**Describe the bug**

There are two breaking problems with the `uart_nrfx_uarte.c` driver.

Firstly, commit 751bdf483b0345eb4de3f424587fd5ce75ec5b25 makes `uarte_nrfx_poll_out` early exit if the device is not in the active state. This has exposed the issue that `data->pm_state` is never updated in `uarte_nrfx_set_power_state` if the async API is enabled on that instance. This issue only appears after disabling the driver for the first time, as `data->pm_state` is initialised to `DEVICE_PM_ACTIVE_STATE`. Therefore after disabling the driver once, all further calls to `uarte_nrfx_poll_out` will do nothing.

After fixing the above issue by appropriately updating `data->pm_state`, the second issue appears.

When the async API is enabled on an instance, and the driver transitions to the off mode, the UART peripheral is immediately disabled: https://github.com/zephyrproject-rtos/zephyr/blob/67f43119be9485844219bb38025f9e49d37da0bf/drivers/serial/uart_nrfx_uarte.c#L1577

This cancels any ongoing transmissions, but more importantly the `ENDTX` and `TXSTOPPED` events are never generated. This means that when the peripheral is next enabled, `is_tx_ready` will always return false, locking up whichever thread is trying to send data (the logging thread in my case). I cannot easily test whether this same error appears when the async API is not enabled. Without bisecting, this appears to be a regression introduced in db6bfde8b36ec4e164eed11715acb29996172459.

The second issue can be resolved (poorly) by waiting for the transmission to complete before disabling the peripheral:
```
		if (get_dev_data(dev)->async) {
			while(!is_tx_ready(dev)) {
				k_sleep(K_MSEC(1));
			}
			nrf_uarte_disable(uarte);
			uarte_nrfx_pins_enable(dev, false);
			return;
		}
```

**Expected behavior**

The UARTE peripheral should be able to be powered up and down when the async API is enabled.
`uarte_nrfx_poll_out` should not block forever / the power down sequence should properly cleanup the peripheral

**Impact**
This breaks logging/printk in my applications which use the async API together with power management.

**Environment (please complete the following information):**
 - Zephyr v2.5rc2

### PR DESCRIPTION
**Pull request by JordanYates**
Gracefully shutdown the UARTE peripheral when the async API is used.
Failure to do so results in the driver being unusable when powered back
up as the required events (ENDTX & TXSTOPPED) are not set. This also
ensures that the last byte sent out via `poll_out` is properly output
on the serial line before powering down.

Fixes #31930.

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

### CODE REVIEW

File: drivers/serial/uart_nrfx_uarte.c [hunk 1]
```diff
@@ -1540,6 +1540,7 @@ static void uarte_nrfx_set_power_state(const struct device *dev,
 			nrfx_timer_enable(&get_dev_config(dev)->timer);
 		}
 		if (get_dev_data(dev)->async) {
+			data->pm_state = new_state;
```
Comment (pabigot) [inline drivers/serial/uart_nrfx_uarte.c:1555]: Why not just move `data->pm_state = new_state;` up to the top of this block, rather than having it here as well asthe bottom?  There's no control path that depends on the original value, nor that should be inspecting `pm_state`.

**Review by pabigot — CHANGES_REQUESTED** [review]
Thanks; I'd looked at the issue but wasn't clear on exactly what needed to be done.

I think the logic of `pm_state` maintenance can be more clean, but otherwise this looks reasonable if it fixes the problem.

**Comment by JordanYates** [comment]
> Thanks; I'd looked at the issue but wasn't clear on exactly what needed to be done.

AFAICT the behavior of the UARTE peripheral is not documented when you just hard disable it (The events are only documented in terms of their START and STOP tasks). So I don't think it's clear to anyone except the Nordic hardware devs. This of course makes validating code rather annoying.

File: drivers/serial/uart_nrfx_uarte.c (hunk 1 above)
Comment (JordanYates) [reply drivers/serial/uart_nrfx_uarte.c]: done

**Review by pabigot — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
