### PR TITLE
modem: hl7800: fix IPv6 operation

### LINKED ISSUE #38716: modem: HL7800: does not work with IPv6
**Describe the bug**
If `CONFIG_NET_IPV6=y` and `CONFIG_NET_IPV4=n` the HL7800 driver will not work with IPv6 addresses.

**To Reproduce**
Modify `proj.conf` in this sample to test:
https://github.com/LairdCP/Pinnacle_100_Sample_Applications/tree/master/apps/low_power

**Expected behavior**
HL7800 driver should work with IPv4 only, IPv6 only, or both enabled.

**Impact**
Showstopper for those wanting to use IPv6 with the HL7800

### PR DESCRIPTION
**Pull request by rerickson1**
Assign the IPv6 address from the LTE network to the
network iface.
Configure DNS resolver with IPv6 DNS address from the
LTE network.
Fix socket AT commands to account for IPv6 addresses.

fixes #38716

### CODE REVIEW

File: drivers/modem/hl7800.c [hunk 1]
```diff
@@ -1707,16 +1726,22 @@ static void dns_work_cb(struct k_work *work)
 #if defined(CONFIG_DNS_RESOLVER) && !defined(CONFIG_DNS_SERVER_IP_ADDRESSES)
 	int ret;
 	struct dns_resolve_context *dnsCtx;
-	static const char * const dns_servers_str[] = { ictx.dns_string, NULL };
+	static const char *const dns_servers_str[] = { ictx.dns_v4_string,
```
Comment (ycsin) [inline drivers/modem/hl7800.c:1729]: I remembered that open braces should be the last char in a line?
```c
static const char *const dns_servers_str[] = {
        ictx.dns_v4_string,
        ...
```

File: drivers/modem/hl7800.c [hunk 2]
```diff
@@ -311,7 +311,15 @@ static const struct mdm_control_pinconfig pinconfig[] = {
 #define PROFILE_LINE_2                                                         \
 	"S00:255 S01:255 S03:255 S04:255 S05:255 S07:255 S08:255 S10:255\r\n"
 
-#define SETUP_GPRS_CONNECTION_CMD "AT+KCNXCFG=1,\"GPRS\",\"\",,,\"IPV4V6\""
+#define ADDRESS_FAMILY_IPV4 "IPV4"
+#if defined(CONFIG_MODEM_HL7800_ADDRESS_FAMILY_IPV4V6)
```
Comment (ycsin) [inline drivers/modem/hl7800.c:315]: Personally from my limited experience I'd prefer
```c
#if IS_ENABLED(CONFIG_*)
```

rather than `#ifdef *` or `#if defined(*)` because `IS_ENABLED` is only true when the CONFIG_* is defined to 1, and the code will compile as intended if the user unintentionally or unknowingly defined `CONFIG_*` = false somewhere and expect the features to be disabled.

Please correct me if I'm wrong

Comment (jukkar) [reply drivers/modem/hl7800.c:315]: Using `IS_ENABLED` is a good habit, but in practice there should be no big difference if one uses `defined`. I recall that there is a check that makes sure user is not able to define `CONFIG_` options in source files. Also one cannot define `CONFIG_*=false` in prj.conf file because Kconfig will make sure that the boolean value needs to be integer.

Comment (ycsin) [reply drivers/modem/hl7800.c:315]: @jukkar Wouldn't `CONFIG_SOMETHING=n` in `prj.conf` or `someboard_defconfig` get compiled into `autoconf.h` as
```c
#define CONFIG_SOMETHING 0
```
, and `#ifdef CONFIG_SOMETHING` will then becomes true?

Comment (jukkar) [reply drivers/modem/hl7800.c:315]: Dunno, but you can certainly try and see what happens. We do not have many invocations of `#if IS_ENABLED()` in the header files atm, so it does not seem be a big concern right now.
`find . -name '*.h' | xargs grep '#if IS_ENABLED'`

Comment (ycsin) [reply drivers/modem/hl7800.c:315]: I checked my app's `autoconf.h` things that are specifically "n" defined in my `prj.conf` aren't being compiled, which is great. I guess I'm just too paranoid.

**Review by rlubos — COMMENTED** [review]
Just some nits.

File: drivers/modem/hl7800.c (hunk 1 above)
Comment (rerickson1) [reply drivers/modem/hl7800.c:1729]: This file was auto-formatted with the .clang-format file using VSCode. So I am going to leave this as is.

File: drivers/modem/hl7800.c (hunk 2 above)
Comment (rerickson1) [reply drivers/modem/hl7800.c:315]: Thanks for the discussion. Going to leave this as is.

File: drivers/modem/hl7800.c [hunk 3]
```diff
@@ -1748,6 +1760,107 @@ char *mdm_hl7800_get_imsi(void)
...
+}
+
+#ifdef CONFIG_NET_IPV6
+/* Convert HL7800 IPv6 address string in format
+ * a01.a02.a03.a04.a05.a06.a07.a08.a09.a10.a11.a12.a13.a14.a15.a16 to
+ * standard IPv6 string xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
+ */
+static int hl7800_v6_addr_to_std_v6_addr(const char *src, int src_len, char *dst, int dst_len)
+{
+	int num_sections = 8;
```
[the remark this answers is not in the document]
Comment (rerickson1) [reply drivers/modem/hl7800.c]: agree, this saves some code.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
LGTM
