### PR TITLE
modem: cmux: Don't set flow-control too easily

### LINKED ISSUE #98644: modem: cmux: extremely premature RX buffer full notification
### Describe the bug

Modem Status Commands (MSC) notifying the modem that the RX buffer is full are sent extremely prematurely.

The MSC is sent if the receive buffer has fewer than `MODEM_CMUX_DATA_FRAME_SIZE_MAX` (`MODEM_CMUX_HEADER_SIZE + CONFIG_MODEM_CMUX_MTU`) bytes remaining.
https://github.com/zephyrproject-rtos/zephyr/blob/0f5e03f1fcba4326baf4507c343f3609bf32c524/subsys/modem/modem_cmux.c#L906-L911
However, these buffers are only created with `MODEM_CMUX_WORK_BUFFER_SIZE` (`CONFIG_MODEM_CMUX_MTU + MODEM_CMUX_HEADER_SIZE`) bytes.
https://github.com/zephyrproject-rtos/zephyr/blob/0f5e03f1fcba4326baf4507c343f3609bf32c524/drivers/modem/modem_cellular.c#L125-L127

In practice, since the buffer size and the threshold are identical, every single packet received by the application results in a MSC event being sent to the modem, which is then acknowledged by the modem. Immediately following this, the receive buffer is processed, and yet another MSC command is sent, followed by another ACK from the modem.
https://github.com/zephyrproject-rtos/zephyr/blob/0f5e03f1fcba4326baf4507c343f3609bf32c524/subsys/modem/modem_cmux.c#L1453-L1459

From the specification:
> Bit 2.Flow Control (FC). The bit is set to 1(one) when the device is unable to accept frames.

I don't believe the current location for setting and clearing the FC bit makes sense. The application is still able to receive data (through the buffering in UART drivers), and still has a place to push the data to (the caller of `pipe_receive`).

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- Zephyr v4.3.0-rc1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SeppoTakalo**
Only track the available buffer space, if
CONFIG_MODEM_CMUX_MSC_FC_THRESHOLD is configured.
When less than required amount fit into the ringbuffer,
indicate the RX buffer is full.

Otherwise, only mark RX buffer full when incoming data is being
dropped.

When RX buffer is detected to be full, send Modem Status Command
with flow-controll bit set.

Flow control is released once the incoming buffer has at least
MODEM_CMUX_MTU bytes free again.

Fixes #98644

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
Verified with BG96 without specifying any extra buffer space
```
&uart30 {
	current-speed = <115200>;
	hw-flow-control;
        zephyr,pm-device-runtime-auto;

	/* Quectel BG96 modem configuration */
	modem: modem {
		status = "okay";
		compatible = "quectel,bg96";
                zephyr,pm-device-runtime-auto;

		mdm-power-gpios = <&gpio1 11 GPIO_ACTIVE_HIGH>;
	};
};
```
```
# Modem driver
CONFIG_MODEM=y
CONFIG_MODEM_CELLULAR=y
CONFIG_MODEM_MODULES_LOG_LEVEL_DBG=y
#CONFIG_MODEM_CMUX_WORK_BUFFER_SIZE_EXTRA=399
```

**Comment by JordanYates** [comment]
Thanks for the quick fix. My plan before seeing this PR was to add a new Kconfig option specifying a threshold at which to send the FC MSC message, probably defaulting to 0.
So by default it would only message when bytes were being dropped, but the user could tune the threshold arbitrarily.
IMO its a bit more flexible that this PR, which only allows a non-zero value if the extra size is set.
Something like this
```
config MODEM_CMUX_MSC_FLOW_CONTROL_THRESHOLD
    int "Enable flow control when the DLCI ring buffer has <= this many bytes space
    range 0 MODEM_CMUX_MTU
    default MODEM_CMUX_MTU if MODEM_CMUX_WORK_BUFFER_SIZE_EXTRA
    default 0
```

edit: regardless of what the defaults end up being, I do think a dedicated symbol makes sense, instead of retconning `MODEM_CMUX_WORK_BUFFER_SIZE_EXTRA`. I could see people setting a threshold of 100 bytes or something with a CMUX_MTU of 1500, even without the extra work buffer size.

**Review by bjarki-andreasen — DISMISSED** [review]

**Comment by bjarki-andreasen** [comment]
`MODEM_CMUX_MSC_FLOW_CONTROL_THRESHOLD` would also be a nice addition

File: subsys/modem/modem_cmux.c [hunk 1]
```diff
@@ -899,14 +900,17 @@ static void modem_cmux_on_dlci_frame_uih(struct modem_cmux_dlci *dlci)
...
-		LOG_WRN("DLCI %u receive buffer overrun (dropped %u out of %u bytes)",
+	if (written < cmux->frame.data_len) {
+		LOG_ERR("DLCI %u receive buffer overrun (dropped %u out of %u bytes)",
 			dlci->dlci_address, cmux->frame.data_len - written, cmux->frame.data_len);
+		dlci->rx_full = true;
 	}
-	if (written < cmux->frame.data_len ||
-	    ring_buf_space_get(&dlci->receive_rb) < MODEM_CMUX_DATA_FRAME_SIZE_MAX) {
-		LOG_WRN("DLCI %u receive buffer is full", dlci->dlci_address);
+	if (CONFIG_MODEM_CMUX_WORK_BUFFER_SIZE_EXTRA > 0 &&
```
Comment (JordanYates) [inline subsys/modem/modem_cmux.c]:
```suggestion
	if (ring_buf_space_get(&dlci->receive_rb) < CONFIG_MODEM_CMUX_FC_THRESHOLD)
```

**Review by JordanYates — CHANGES_REQUESTED** [review]
The defaults can be setup to replicate what you did, but a dedicated symbol just makes the whole thing more flexible.

**Comment by SeppoTakalo** [comment]
@JordanYates Added the Kconfig as you suggested.

File: subsys/modem/modem_cmux.c [hunk 2]
```diff
@@ -1449,10 +1454,9 @@ static int modem_cmux_dlci_pipe_api_receive(void *data, uint8_t *buf, size_t siz
 
 	ret = ring_buf_get(&dlci->receive_rb, buf, size);
 	k_mutex_unlock(&dlci->receive_rb_lock);
-
 	/* Release FC if set */
 	if (dlci->rx_full &&
-	    ring_buf_space_get(&dlci->receive_rb) >= MODEM_CMUX_DATA_FRAME_SIZE_MAX) {
+	    ring_buf_space_get(&dlci->receive_rb) >= CONFIG_MODEM_CMUX_MTU) {
```
Comment (JordanYates) [inline subsys/modem/modem_cmux.c:1459]: Shouldn't this also be the `CONFIG_MODEM_CMUX_MSC_FC_THRESHOLD`?

File: subsys/modem/Kconfig [hunk 3]
```diff
@@ -64,6 +64,19 @@ config MODEM_CMUX_WORK_BUFFER_SIZE_EXTRA
 	  Extra bytes to add to the work buffers used by the CMUX module.
 	  The default size of these buffers is MODEM_CMUX_MTU + 7 (CMUX header size).
 
+config MODEM_CMUX_MSC_FC_THRESHOLD
+	int "Enable flow control when the DLCI ring buffer has less than this many bytes free"
+	range 0 MODEM_CMUX_MTU
+	default MODEM_CMUX_MTU if MODEM_CMUX_WORK_BUFFER_SIZE_EXTRA > 0
+	default 0
+	help
+	  When the available space in a DLCI receive ring buffer is less than this
```
Comment (JordanYates) [inline subsys/modem/Kconfig:73]: If 0 disables this feature it should be mentioned somewhere

Comment (SeppoTakalo) [reply subsys/modem/Kconfig:73]: Thanks.
Added a note.

File: subsys/modem/modem_cmux.c (hunk 2 above)
Comment (SeppoTakalo) [reply subsys/modem/modem_cmux.c:1459]: No, there is intentional treshold there.

Once the flow-control is set, it will wait until the full frame can fit.

I indicated this on the commit message:
```
When RX buffer is detected to be full, send Modem Status Command
with flow-controll bit set.

Flow control is released once the incoming buffer has at least
MODEM_CMUX_MTU bytes free again.
```

**Review by JordanYates — APPROVED** [review]

**Review by rerickson1 — APPROVED** [review]
