### PR TITLE
samples: bluetooth: hci_spi: Fix cmd_hdr and acl_hdr usage

### LINKED ISSUE #27266: samples: bluetooth: hci_spi: Invalid cmd_hdr and acl_hdr usage
**Describe the bug**
cmd_hdr and acl_hdr local structs were read but never written.
Causing unpredictable errors in bt_tx_thread such as :
"Invalid HCI CMD packet length" in hci.c:2280
or Imprecise data bus errors on nrf52810.

I have pinpointed the issue to samples/bluetooth/hci_spi/src/main.c using SEGGER J-Link probe

**To Reproduce**
1. have an hci_spi hardware setup
2. Add these Kconfig option to hci_spi sample:
    CONFIG_BT_LOG_LEVEL_DBG=y
    CONFIG_BT_DEBUG_LOG=y
    CONFIG_BT_DEBUG_HCI_DRIVER=y
3. build and flash hci_spi for the controller
4. build and flash peripheral_hr for the host
5. See error on controller serial console

**Expected behavior**
cmd_hdr and acl_hdr local structs should be filled with the SPI data received from the host cpu

**Impact**
hci_spi is unusable and crash at random spots depending on the host application:
- Advertiser might not start
- Discovering bluetooth services won't work

**Environment (please complete the following information):**
 - OS: Linux x86_64 Kernel : 5.7.6-arch1-1
 - Toolchain : Zephyr SDK (0.11.3)
 - Commit : Tag v2.3.0

### PR DESCRIPTION
**Pull request by CorentinDOROTHEE**
Fixes #27266.
cmd_hdr and acl_hdr local structs were read but never written.
Causing unpredictable errors in bt_tx_thread such as :
"Invalid HCI CMD packet length" in hci.c:2280
or Imprecise data bus errors on nrf52810.

cmd_hdr and acl_hdr are now filled with the received data
from SPI Master.

Signed-off-by: Corentin Dorothée <corentin.dorothee@gmail.com>

### CODE REVIEW

**Review by lochej — APPROVED** [review]
LGTM

Finally a fix for HCI SPI sample which was broken even in v2.3.0.
Tested in conjonction with #27281 which fixes the CS pin driving for bluetooth hci_spi driver on the host board.
Host board: STM nucleo_l4r5zi
HCI SPI controller: Laird Connectivity bl651

Experienced reviewers/members should help to integrate this fix in zephyr v2.3.0

File: samples/bluetooth/hci_spi/src/main.c [hunk 1]
```diff
@@ -195,6 +195,7 @@ static void bt_tx_thread(void *p1, void *p2, void *p3)
 
 		switch (rxmsg[PACKET_TYPE]) {
 		case HCI_CMD:
+			memcpy(&cmd_hdr, &rxmsg[1], sizeof(cmd_hdr));
```
Comment (joerchan) [inline samples/bluetooth/hci_spi/src/main.c:198]: Coping seems uneccesary, I think changing cmd_hdr and acl_hdr to pointers into rxmsg would be better.

```
		case HCI_CMD:
		{
			struct bt_hci_cmd_hdr *cmd_hdr;

			buf = bt_buf_get_tx(BT_BUF_CMD, K_NO_WAIT, &rxmsg[1],
					    sizeof(*cmd_hdr));
			if (buf) {
				net_buf_add_mem(buf, &rxmsg[4],
						cmd_hdr->param_len);
...
```

Comment (CorentinDOROTHEE) [reply samples/bluetooth/hci_spi/src/main.c:198]: I agree I'll change that !
I initially put the original implementation.

Comment (lochej) [reply samples/bluetooth/hci_spi/src/main.c]: That's a clever way of avoiding copies. Else we could have just get rid of the header structs and reference the buffer directly and use the header size defines instead of the sizeof(cmd_hdr).

But I like this approach more as it is straight forward compatible with v2.3.0.

**Comment by lochej** [comment]
The new implementation avoiding copies looks good to me.
Needs testing though but code wise, this should be no issues.
If that's the implementation you want to provide. Please squash your two commits to only keep the latest implementation. Avoid adding code and removing it in the next commit.

Thanks for this fix :-)

**Review by joerchan — APPROVED** [review]

**Review by lochej — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

File: samples/bluetooth/hci_spi/src/main.c [hunk 2]
```diff
@@ -148,8 +148,8 @@ static void bt_tx_thread(void *p1, void *p2, void *p3)
 	uint8_t header_slave[5] = { READY_NOW, SANITY_CHECK,
 				 0x00, 0x00, 0x00 };
 	struct net_buf *buf = NULL;
-	struct bt_hci_cmd_hdr cmd_hdr;
-	struct bt_hci_acl_hdr acl_hdr;
+	struct bt_hci_cmd_hdr *cmd_hdr = (struct bt_hci_cmd_hdr *) &rxmsg[1];
+	struct bt_hci_acl_hdr *acl_hdr = (struct bt_hci_acl_hdr *) &rxmsg[1];
```
Comment (jhedberg) [inline samples/bluetooth/hci_spi/src/main.c:152]: Minor optimisation, but wouldn't a union make sense here? Also, remove the space between the typecast and variable name - I think that's more consistent with the rest of the Bluetooth code (even though there might not be a documented coding style rule that requires is)

Comment (lochej) [reply samples/bluetooth/hci_spi/src/main.c:152]: ```checkpatch``` should be able to tell for this rule.

I personnally like the struct pointer approach more than the original memcpy approach as it is faster and sill makes clear sense of how the rxmsg buffer is interpreted. 

Could you be more clear about how the union change would improve this already optimized version ?

Comment (lochej) [reply samples/bluetooth/hci_spi/src/main.c:152]: I think I understand where you're getting at:
```c
union hdr_ptr {
   struct bt_hci_cmd_hdr *cmd_hdr;
   struct bt_hci_acl_hdr *acl_hdr;
};
```
(Syntax may be wrong)
And only instanciate one ```union hdr_ptr``` and pick either cmd_hdr or acl_hdr based on the context. 

We only save 1 pointer right ?

Comment (jhedberg) [reply samples/bluetooth/hci_spi/src/main.c:152]: Correct. Regarding global coding style and checkpatch, that can be discussed separately, but having a consistent style across a subsystem (whatever it might be) is something I hope is not controversial to anyone.

File: samples/bluetooth/hci_spi/src/main.c [hunk 3]
```diff
@@ -195,22 +199,24 @@ static void bt_tx_thread(void *p1, void *p2, void *p3)
...
 			} else {
 				LOG_ERR("No available command buffers!");
 				continue;
 			}
 			break;
 		case HCI_ACL:
 			buf = bt_buf_get_tx(BT_BUF_ACL_OUT, K_NO_WAIT,
-					    &rxmsg[1], sizeof(acl_hdr));
+					    hci_hdr.acl_hdr,
+					    sizeof(*hci_hdr.acl_hdr));
```
Comment (CorentinDOROTHEE) [inline samples/bluetooth/hci_spi/src/main.c:216]: I further reduced the number of reference to &rxmsg[1] by using the union pointer.

**Review by lochej — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
