### PR TITLE
drivers/sensor/lsm6dsl: Fix read/write bus API in shub code

### LINKED ISSUE #28565: sensor: lsm6dsl: incompatible pointer type (warning)
**Describe the bug**
Warnings generated when building sensor lsm6dsl.
```
lsm6dsl_shub.c: In function 'lsm6dsl_shub_embedded_en':
lsm6dsl_shub.c:160:26: error: passing argument 1 of 'data->hw_tf->update_reg' from incompatible pointer type [-Werror=incompatible-pointer-types]
  160 |  data->hw_tf->update_reg(data, LSM6DSL_REG_FUNC_CFG_ACCESS,
      |                          ^~~~
      |                          |
      |                          struct lsm6dsl_data *
lsm6dsl_shub.c:160:26: note: expected 'const struct device *' but argument is of type 'struct lsm6dsl_data *'

```

**To Reproduce**
1. sanitycheck -b 96b_argonkey -T samples/sensor/lsm6dsl (or -T samples/boards/96b_argonkey/sensors)
2. See error

**Expected behavior**
Should build w/o warning

### PR DESCRIPTION
**Pull request by avisconti**
The ce0cc3a7 commit (lsm6dsl: make the driver multi-instance) changes
all bus API signature, which now requires a "const struct device *dev"
and not a "struct lsm6dsl_data *data". By mistake the shub part was
left unchanged. Fix: #28565

Not tested yet!
I just built it and verified it is compiling properly.
I would like to test it on x_nucleo_iks01a2 shield, but I require to extend the current available
sample. For the moment just take a look at it and see if I have done any mistake.

For the moment it is a DNM. I do not think the shub will have any problem. So, we may want to
skip the test if v2.4.0 has to be released soon.

EDIT:
Removed the DNM!
Tested on x_nucleo_iks01a2 shield in shub mode. Tested both LIS2MDL and LPS22HB sensors connected in shub mode.
The shield and sample changes will be provided in a separated commit as some documentation change is required.

### CODE REVIEW

File: drivers/sensor/lsm6dsl/lsm6dsl_shub.c [hunk 1]
```diff
@@ -153,155 +153,165 @@ static inline void lsm6dsl_shub_wait_completed(struct lsm6dsl_data *data)
...
 /*
  * use SLV0 for generic read to slave device
  */
-static int lsm6dsl_shub_read_slave_reg(struct lsm6dsl_data *data,
+static int lsm6dsl_shub_read_slave_reg(const struct device *dev,
 				       uint8_t slv_addr, uint8_t slv_reg,
 				       uint8_t *value, uint16_t len)
 {
+	struct lsm6dsl_data *data = dev->data;
+
```
Comment (pabigot) [inline drivers/sensor/lsm6dsl/lsm6dsl_shub.c:259]: remove extra blank line

File: drivers/sensor/lsm6dsl/lsm6dsl_shub.c [hunk 2]
```diff
@@ -366,14 +377,13 @@ int lsm6dsl_shub_read_external_chip(const struct device *dev, uint8_t *buf,
 {
 	struct lsm6dsl_data *data = dev->data;
```
Comment (pabigot) [inline drivers/sensor/lsm6dsl/lsm6dsl_shub.c:378]: Remove this unused definition.

**Review by pabigot — CHANGES_REQUESTED** [review]
Minor cleanups, otherwise looks reasonable.

File: drivers/sensor/lsm6dsl/lsm6dsl_shub.c [hunk 3]
```diff
@@ -53,23 +53,23 @@ static int lsm6dsl_shub_write_slave_reg(struct lsm6dsl_data *data,
 #define LIS2MDL_OFF_CANC          0x02
 #define LIS2MDL_SENSITIVITY       1500
 
-static int lsm6dsl_lis2mdl_init(struct lsm6dsl_data *data, uint8_t i2c_addr)
+static int lsm6dsl_lis2mdl_init(const struct device *dev, uint8_t i2c_addr)
 {
 	uint8_t mag_cfg[2];
 
 	data->magn_sensitivity = LIS2MDL_SENSITIVITY;
```
Comment (erwango) [inline drivers/sensor/lsm6dsl/lsm6dsl_shub.c:60]: Leftover ?

**Review by erwango — CHANGES_REQUESTED** [review]
One leftover.
Otherwise one suggestion:
`lsm6dsl_shub_wait_completed` is now the only function to take a `struct lsm6dsl_data *data` arg.
This is kind of error prone (at least for the review). Moving it to take `const struct device *dev` woul make code more uniform and would allow to get rid of few (2 or 3) `struct lsm6dsl_data *data = dev->data;` lines. Doesn't bring any improvement but slight gain in readability.
This is just a suggestion.

File: drivers/sensor/lsm6dsl/lsm6dsl_shub.c (hunk 3 above)
Comment (avisconti) [reply drivers/sensor/lsm6dsl/lsm6dsl_shub.c:60]: @erwango 
I just wanted to minimize the changes. But your suggestion looks reasonable.
I'll do the change today

File: drivers/sensor/lsm6dsl/lsm6dsl_shub.c (hunk 1 above)
Comment (avisconti) [reply drivers/sensor/lsm6dsl/lsm6dsl_shub.c:259]: ack

File: drivers/sensor/lsm6dsl/lsm6dsl_shub.c (hunk 2 above)
Comment (avisconti) [reply drivers/sensor/lsm6dsl/lsm6dsl_shub.c:378]: ack

Comment (avisconti) [reply drivers/sensor/lsm6dsl/lsm6dsl_shub.c:378]: No, sorry! Actually it is required.

Comment (pabigot) [reply drivers/sensor/lsm6dsl/lsm6dsl_shub.c:378]: Ah, yes, I see its use now.

**Comment by avisconti** [comment]
@erwango @pabigot 
I addessed your requests. And I finally tested it on shield, so I removed now the DNM.
Board and sample changes for shub mode will be provided in a separate commit later on (to be planned).

**Review by pabigot — APPROVED** [review]

**Review by erwango — APPROVED** [review]
Tested ok on disco_l475_iot1

**Review by MaureenHelm — APPROVED** [review]
