### PR TITLE
Bluetooth: ATT: Multiple fixes

### LINKED ISSUE #25964: Bluetooth: <err> bt_att: ATT Timeout
**Describe the bug**
Local device performing ATT write cmds, generates `<wrn> bt_att: Ignoring unexpected request` when peer device send an ATT request. The peer then gets `<err> bt_att: ATT timeout`

**To Reproduce**
Use the branch: https://github.com/cvinayak/zephyr/commit/b4939f526a9c1c86a88fd55810ed85e1ecaaf46d

Build and flash peripheral:
  1. mkdir -p build/peripheral; cd build/peripheral
  2. cmake -GNinja -DBOARD=nrf52dk_nrf52832 ../../samples/bluetooth/peripheral
  3. ninja
  4. ninja flash

Build and flash central_hr:
  5. mkdir -p build/central_hr; cd build/central_hr
  6. cmake -GNinja -DBOARD=nrf52dk_nrf52832 ../../samples/bluetooth/central_hr
  7. ninja
  8. ninja flash

  9. Open two terminals, `minicom -D /dev/ttyACMx`
  10. Observe both peripheral and central_hr fail with respective warning and error messages in the console.

**Expected behavior**
ATT request from peer device shall not be dropped. ATT bearer shall not timeout.

**Impact**
showstopper

**Screenshots or console output**
image

**Environment (please complete the following information):**
- OS: Linux
 - Toolchain: Zephyr SDK 0.11.2
 - Commit SHA or Version used: https://github.com/cvinayak/zephyr/commit/b4939f526a9c1c86a88fd55810ed85e1ecaaf46d

**Additional context**

### LINKED ISSUE #26070: Bluetooth: ATT request not processed
**Describe the bug**
`bt_gatt_read` after several `bt_gatt_write_without_response` call, exit without error but the BLE packet is not sent over the air. After `bt_gatt_read` sample works but characteristic is never read and sniffer does not detect any GATT Read packet. I did some dubbuging and I found that if L2CAP channel is bussy by previous write operation the Read ATT request is queued:
```
	/* Queue the request to be send later */
	sys_slist_append(&att->reqs, &req->node);
```

But after Write operation is finished this list is never proccessed.

When write operation is outgoing the `tx_sem` is taken and Read request return on ` k_sem_take` with error here:
```
static int bt_att_chan_req_send(struct bt_att_chan *chan,
				struct bt_att_req *req)
{
	int err;

	__ASSERT_NO_MSG(chan);
	__ASSERT_NO_MSG(req);
	__ASSERT_NO_MSG(req->func);
	__ASSERT_NO_MSG(!chan->req);

	BT_DBG("req %p", req);

	if (chan->chan.tx.mtu < net_buf_frags_len(req->buf)) {
		return -EMSGSIZE;
	}

	if (k_sem_take(&chan->tx_sem, K_NO_WAIT) < 0) {
		return -EAGAIN;
	}

	BT_DBG("chan %p req %p len %zu", chan, req,
	       net_buf_frags_len(req->buf));

	chan->req = req;

	/* Save request state so it can be resent */
	net_buf_simple_save(&req->buf->b, &req->state);

	/* Keep a reference for resending in case of an error */
	err = chan_send(chan, net_buf_ref(req->buf), NULL);
	if (err < 0) {
		net_buf_unref(req->buf);
		req->buf = NULL;
		k_sem_give(&chan->tx_sem);
		chan->req = NULL;
	}

	return err;
}
```
In this case after `k_sem_take` returned with error. Request are queued here:

```
	/* Queue the request to be send later */
	sys_slist_append(&att->reqs, &req->node);
```
As I said earlier this is never processed.
In previous revision of the `att.c` this mechanism looks a little different. When tx_sem was taken then
the att_requests are also added to `tx_queue` like other att data, now they are not there and they are never processed.

Previous behaviour:
```
	if (k_sem_take(&att->tx_sem, K_NO_WAIT) < 0) {
		k_fifo_put(&att->tx_queue, req->buf);
		return 0;
	}
```

Conclusions.
If the BLE Host is bussy by sending the ATT data, sending ATT Request is queued but after the HOST finish processing previous ATT send the queued ATT request are never send.

**To Reproduce**
Sample code to reproduce
```
	while (prog < IMG_SIZE) {
		bt_gatt_write_without_response(throughput->conn,
					      throughput->char_handle,
					      data, len, false)
		if (err) {
			printk("GATT write failed (err %d)\n", err);
			break;
		}

		/* print graphics */
		printk("%c", img[prog / IMG_X][prog % IMG_X]);
		data += 244;
		prog++;
	}

	delta = k_uptime_delta_32(&stamp);

	printk("\nDone\n");
	printk("[local] sent %u bytes (%u KB) in %u ms at %llu kbps\n",
	       data, data / 1024, delta, ((u64_t)data * 8 / delta));

	/* read back char from peer */
	throughput->read_params.single.handle = throughput->char_handle;
	throughput->read_params.single.offset = 0;
	throughput->read_params.handle_count = 1;
	throughput->read_params.func = read_fn;

	err = bt_gatt_read(throughput->conn, &throughput->read_params);
	if (err) {
		LOG_ERR("Characteristic read failed.");
	}
	if (err) {
		printk("GATT read failed (err %d)\n", err);
	}
```

**Expected behavior**
GATT Read Request should be sent over air or `bt_gatt_read` should return an error code.

### LINKED ISSUE #26071: Bluetooth: host: ATT sent callback lost
**Describe the bug**
The problem occurs when two transmissions of different types (REQUEST, CONFIRMATION, etc) on the same ATT channel occur within a very short window.
In Jordan Yates' case at least, this occurs when the GATT server publishes an Indication, which the host schedules an acknowledgement for. If the GATT client is also performing writes to the server, two writes can go through the host in a very short window.

https://github.com/zephyrproject-rtos/zephyr/blob/e77985a2f0531a8fbefdb9ae2e5ea7c5e3dbd70f/subsys/bluetooth/host/att.c#L152
This line sets the ATT callback, `chan_cfm_sent`, `chan_rsp_sent`, etc.
However there is no protection around this setting. If `chan_send` is called again before `bt_att_sent` runs, the original callback is lost, and the callback associated with the second transmission is instead run twice.

In my situation, because the callback is lost, `chan_cfm_sent` is never called and thus the `ATT_PENDING_CFM` bit is never cleared on the flags. The next indication from the server is therefore ignored at https://github.com/zephyrproject-rtos/zephyr/blob/e77985a2f0531a8fbefdb9ae2e5ea7c5e3dbd70f/subsys/bluetooth/host/att.c#L2309

This issue occurs also in https://github.com/zephyrproject-rtos/zephyr/issues/25964 as the  `<wrn> bt_att: Ignoring unexpected request` warning. This issue is unrelated to the ATT timeout.

Build and flash peripheral:
  1. mkdir -p build/peripheral; cd build/peripheral
  2. cmake -GNinja -DBOARD=nrf52dk_nrf52832 ../../samples/bluetooth/peripheral
  3. ninja
  4. ninja flash

Build and flash central_hr:
  5. mkdir -p build/central_hr; cd build/central_hr
  6. cmake -GNinja -DBOARD=nrf52dk_nrf52832 ../../samples/bluetooth/central_hr
  7. ninja
  8. ninja flash

  9. Open two terminals, `minicom -D /dev/ttyACMx`
  10. Observe both peripheral and central_hr fail with respective warning and error messages in the console.

### PR DESCRIPTION
**Pull request by Vudentz**
ATT channel sent callback shall not be overwritting until the
operation completes as it can result in breaking flow control when
CONFIG_BT_ATT_ENFORCE_FLOW is enabled.

Fixes #25964
Fixes #26070
Fixes #26071

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

**Comment by cvinayak** [comment]
@alexsven could you check if your unsubscribe scenario under ATT traffic works now with this PR?

**Review by joerchan — DISMISSED** [review]
This appears to fix a problem reported by some, but not the ATT timeout that was reported by @cvinayak 

I have created a new bug-report for this issue and updated the fixes line.

**Review by carlescufi — CHANGES_REQUESTED** [review]
@Vudentz this PR fixes #26071 according to @joerchan, but it doesn't fix #25964. Can you update the commit to reflect this or add an additional commit to fix #25964 please?

**Review by carlescufi — DISMISSED** [review]
@Vudentz thanks!

>Fixes #25964 #26071

You will need 2 separate `Fixes` lines for GitHub to pick up both issues

File: subsys/bluetooth/host/att.c [hunk 1]
```diff
@@ -194,6 +202,8 @@ static void bt_att_sent(struct bt_l2cap_chan *ch)
 		chan->sent(chan);
 	}
```
[the remark this answers is not in the document]
Comment (carlescufi) [reply subsys/bluetooth/host/att.c:258]: Agreed, this looks suspicious, is `chan->sent` being set to NULL elsewhere?

[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/att.c:258]: That is just there because chan_cb can return NULL, reseting to NULL doesn't make any difference here since chan_send will always attempt to set the callback when called.

**Comment by Vudentz** [comment]
> @Vudentz thanks!
> 
> > Fixes #25964 #26071
> 
> You will need 2 separate `Fixes` lines for GitHub to pick up both issues

Done.

**Comment by joerchan** [comment]
@Vudentz There should be 3 issues fixed now, right? Missing 26063

**Comment by joerchan** [comment]
@Vudentz I also ran into an issue where the error code was not forwarded to the user because of this:
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/att.c#L2833
I'm not sure why the error code was ignored in this case, are there some other parts relying on the fact that it returns 0 here?

**Comment by joerchan** [comment]
```
D: bt_att_recv():Received ATT chan 0x20007e28 code 0x07 len 4
D: att_handle_find_type_rsp():
D: att_handle_rsp():chan 0x20007e28 err 0x00 len 4: 0e001000
D: att_req_destroy():req 0x20007cb8
D: bt_att_req_free():req 0x20007cb8
D: gatt_find_type_rsp():err 0x00
D: gatt_find_type_rsp():start_handle 0x000e end_handle 0x0010
D: gatt_find_info():start_handle 0x000f end_handle 0x0010
D: bt_att_req_alloc():req 0x20007cb8
D: bt_att_req_send():conn 0x20002e08 req 0x20007cb8
D: bt_att_chan_req_send():req 0x20007cb8
W: chan_req_send():chan 0x20007e28 req 0x20007cb8 len 5
W: chan_req_send():231: buf 0x200080a0 ref
D: chan_send():code 0x04
W: chan_req_send():req->buf = NULL
D: bt_att_req_send():req 0x20007cb8 queued
D: att_sent():conn 0x20002e08 chan 0x20007e2c
D: bt_att_sent():chan 0x20007e28
D: chan_rsp_sent():chan 0x20007e28
W: chan_req_send():chan 0x20007e28 req 0x20007cb8 len 0
W: chan_req_send():231: buf 0x00000000 ref
ASSERTION FAIL [buf] @ WEST_TOPDIR/zephyr/subsys/net/buf.c:574

```
We end up with request in the queue that has set req->buf = NULL;
Compare the two functions below and their handling of the returned err value.
```
static int chan_req_send(struct bt_att_chan *chan, struct bt_att_req *req)
{
        /* ... */
	err = chan_send(chan, net_buf_ref(req->buf), NULL);
	if (err < 0) {
		net_buf_unref(req->buf);
		BT_WARN("req->buf = NULL");
		req->buf = NULL;
		chan->req = NULL;
	}

	return err;
}

```

```
int bt_att_req_send(struct bt_conn *conn, struct bt_att_req *req)
{
	/* ... */
	SYS_SLIST_FOR_EACH_CONTAINER_SAFE(&att->chans, chan, tmp, node) {
			/* ... */
			ret = bt_att_chan_req_send(chan, req);
			if (ret >= 0) {
				return ret;
			}
		}
	}

	/* Queue the request to be send later */
	sys_slist_append(&att->reqs, &req->node);

	BT_DBG("req %p queued", req);

	return 0;
}
```

**Comment by Vudentz** [comment]
> We end up with request in the queue that has set req->buf = NULL;
> Compare the two functions below and their handling of the returned err value.
> 
> ```
> static int chan_req_send(struct bt_att_chan *chan, struct bt_att_req *req)
> {
>         /* ... */
> 	err = chan_send(chan, net_buf_ref(req->buf), NULL);
> 	if (err < 0) {
> 		net_buf_unref(req->buf);
> 		BT_WARN("req->buf = NULL");
> 		req->buf = NULL;

Ive remove the above statement, it shouldn't be reseting the buffer to NULL.

File: subsys/bluetooth/host/att.c [hunk 2]
```diff
@@ -316,6 +384,18 @@ static int bt_att_chan_send(struct bt_att_chan *chan, struct net_buf *buf,
...
 
+static void bt_att_chan_send_rsp(struct bt_att_chan *chan, struct net_buf *buf,
+				 bt_att_chan_sent_t cb)
+{
+	int err;
+
+	err = bt_att_chan_send(chan, buf, cb);
+	if (err) {
+		/* Responses need to be sent back using the same channel */
+		k_fifo_put(&chan->tx_queue, buf);
```
Comment (jhedberg) [inline subsys/bluetooth/host/att.c:395]: This needs to be `net_buf_puf()`, so that fragment handling is correct. Even if you don't have fragments it ensures that buf->flags, etc is correct.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/att.c [hunk 3]
```diff
@@ -2420,6 +2485,11 @@ static void att_chan_detach(struct bt_att_chan *chan)
 		k_sem_give(&chan->tx_sem);
 	}
 
+	/* Release pending buffers */
+	while ((buf = k_fifo_get(&chan->tx_queue, K_NO_WAIT))) {
```
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/att.c]: Done.

File: subsys/bluetooth/host/att.c (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/att.c]: Done.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/att.c [hunk 4]
```diff
@@ -178,36 +188,97 @@ static int chan_send(struct bt_att_chan *chan, struct net_buf *buf,
...
-				att_sent, &chan->chan.chan);
+				att_cb(chan->sent), &chan->chan.chan);
+}
+
+static int process_queue(struct bt_att_chan *chan, struct k_fifo *queue)
+{
+	struct net_buf *buf;
+	int err;
+
+	while ((buf = net_buf_get(queue, K_NO_WAIT))) {
```
Comment (joerchan) [inline subsys/bluetooth/host/att.c:202]: `while` with always one iteration? change to `if`?

File: subsys/bluetooth/host/att.c [hunk 5]
```diff
@@ -2420,6 +2537,11 @@ static void att_chan_detach(struct bt_att_chan *chan)
 		k_sem_give(&chan->tx_sem);
 	}
 
+	/* Release pending buffers */
```
Comment (joerchan) [inline subsys/bluetooth/host/att.c:2540]: In the ATT timeout handler the channel that the ATT timeout happened for will be detached, what about if you had other  ATT channels active at the same time? How would they be released?

File: subsys/bluetooth/host/att.c (hunk 4 above)
Comment (carlescufi) [reply subsys/bluetooth/host/att.c:202]: Why only one iteration? This will loop until `buf != NULL`? which btw, why `K_NO_WAIT` in this case and busy-loop like that?

File: subsys/bluetooth/host/att.c (hunk 5 above)
Comment (Vudentz) [reply subsys/bluetooth/host/att.c:2540]: Timeout is per bearer, other channels will not be affected, provided they don't timeout as well.

File: subsys/bluetooth/host/att.c (hunk 4 above)
Comment (Vudentz) [reply subsys/bluetooth/host/att.c:202]: That indeed can be converted to if statement, I will change that.

Comment (Vudentz) [reply subsys/bluetooth/host/att.c]: Done.

**Comment by Vudentz** [comment]
@carlescufi process_queue will not attempt to take tx_sem like bt_att_chan_send would, so it is essencially just taking ownership of the slot used by the previous request, iirc this was made like that to reduce the time we spend on the sent callback.

**Review by carlescufi — APPROVED** [review]
Tested and verified to solve the issues linked.

File: subsys/bluetooth/host/att.c (hunk 5 above)
Comment (joerchan) [reply subsys/bluetooth/host/att.c:2541]: But you would call att_reset and notify gatt that the connection is disconnect, not the channel. Since att_reset is called the att->conn is set to NULL and bt_att_send will now return ENOTCONN for everything as far as I can tell.

Comment (Vudentz) [reply subsys/bluetooth/host/att.c:2541]: Well read it again:

```
	/* Don't notify if there are still channels to be used */
	if (!sys_slist_is_empty(&att->chans)) {
		return;
	}
```

Comment (joerchan) [reply subsys/bluetooth/host/att.c:2541]: Right. missed that.

**Review by joerchan — APPROVED** [review]

**Comment by carlescufi** [comment]
@Vudentz would you mind sending this PR against the `v2.3-branch` so we backport it in time for v2.3.1? Thanks!
