### PR TITLE
tests: mutex: fixed a testcase assert failure

### LINKED ISSUE #34116: mec15xxevb_assy6853: tests/kernel/mutex/sys_mutex/
**Describe the bug**
test_mutex_multithread_competition in tests/kernel/mutex/sys_mutex/ failed

This test is also failing on Up squared x86 and Nordic Reel board

**To Reproduce**
1.  twister --hardware-map ~/mec1.file --device-testing -s tests/kernel/mutex/sys_mutex/test_mutex_multithread_competition/
2. See error

**Expected behavior**
Test should pass

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.5.0-2011-gecac194448da  ***
Running test suite mutex_complex
===================================================================
START - test_mutex
START - Test kernel Mutex API
===================================================================
Done LOCKING!  Current priority = 5
*** Booting Zephyr OS build zephyr-v2.5.0-2011-gecac194448da  ***
Running test suite mutex_complex
===================================================================
START - test_mutex
START - Test kernel Mutex API
===================================================================
Done LOCKING!  Current priority = 5
Testing recursive locking
Recursive locking tests successful
PASS - test_mutex in 7.519 seconds
===================================================================
START - test_user_access
SKIP - test_user_access in 0.1 seconds
===================================================================
START - test_supervisor_access
PASS - test_supervisor_access in 0.1 seconds
===================================================================
START - test_mutex_multithread_competition
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mutex/sys_mutex/src/thread_competition.c:119: test_mutex_multithread_competition: (flag == LOW_PRO is false)
The low priority thread failed to take the mutex.
FAIL - test_mutex_multithread_competition in 0.75 seconds
===================================================================
Test suite mutex_complex failed.
===================================================================
PROJECT EXECUTION FAILED 
```

**Environment (please complete the following information):**
 - OS: Fedora 
 - Toolchain: zephyr-sdk-0.12.3
 - Commit ID: ecac194448da

### PR DESCRIPTION
**Pull request by Zhaoningx**
Modify the testcase design to solve some threads
can't lock mutex. Using array index to detect the order
of threads getting mutex instead of delaying.

Fixed #34116

Signed-off-by: Ningx Zhao <ningx.zhao@intel.com>

### CODE REVIEW

File: tests/kernel/mutex/sys_mutex/src/thread_competition.c [hunk 1]
```diff
@@ -7,10 +7,6 @@
 #include <ztest.h>
 #include <sys/mutex.h>
 
-#define HIGH_T1	 0xaaa
-#define HIGH_T2	 0xbbb
-#define LOW_PRO	 0xccc
```
Comment (andyross) [inline tests/kernel/mutex/sys_mutex/src/thread_competition.c:12]: I don't understand.  The old version had named constants for your flag cookies, but the new one is hard-coding the values?  That seems to be going backwards.

**Review by andyross — APPROVED** [review]
Patch makes sense as an optimization, though I don't understand the loss of the named constants.

I do worry this isn't SMP-safe though.  Thread execution order isn't always guaranteed to be highest-priority-first when you can have two+ threads running at the same time.  You'd need to control that with careful synchronization at thread creation time to make sure there's never a situation where the low priority thread gets started first on a different CPU.

**Review by dcpleung — APPROVED** [review]

File: tests/kernel/mutex/sys_mutex/src/thread_competition.c (hunk 1 above)
Comment (Zhaoningx) [reply tests/kernel/mutex/sys_mutex/src/thread_competition.c]: Hi @andyross , I totally agree with you, and I have update this.

**Review by LeiW000 — APPROVED** [review]

**Review by LeiW000 — APPROVED** [review]
