### PR TITLE
driver: usb_dc_sam_usbhs: Restore EP0 after detach

### LINKED ISSUE #50549: USB: samhs: Device does not work after detach-attach sequence
**Describe the bug**

`sam_v71b_xult` fails to re-enumerate on the bus after detach (see #50268).

With OpenVizsla, I was able to observe that `sam_v71b_xult` does reattach to the bus but does not reply to GET DEVICE DESCRIPTOR and SET ADDRESS control transfers. Device is recognizing bus resets.

`usb_dc_disable()` does not set `USBHS_DEVCTRL_DETACH` bit, i.e. the code currently clears the bit instead of setting it. https://github.com/zephyrproject-rtos/zephyr/blob/7e6e4579c29f269626d52bb70d5eed30113d90ee/drivers/usb/device/usb_dc_sam_usbhs.c#L351

Just fixing the `USBHS_DEVCTRL_DETACH` bit is not enough. The EP0 does not seem to be configured anymore after the detach, i.e. `usb_dc_ep_is_configured(0);` returns 0 (I have manually added the extra `usb_dc_ep_is_configured(0);` call in `usb_dc_isr()`).

**To Reproduce**
1. Checkout PR #50268
2. Build and flash MCUboot
3. `west build -b sam_v71b_xult zephyr/samples/subsys/usb/dfu -d build-dfu-sam -- -DCONFIG_MCUBOOT_SIGNATURE_KEY_FILE=\"bootloader/mcuboot/root-rsa-2048.pem\"`
4. `west flash -d build-dfu-sam`
5. `west build -b sam_v71b_xult zephyr/samples/hello_world -d build-hello_world-sam --    -DCONFIG_BOOTLOADER_MCUBOOT=y '-DCONFIG_MCUBOOT_SIGNATURE_KEY_FILE="bootloader/mcuboot/root-rsa-2048.pem"'`
6. `dfu-util --alt 1 --download build-hello_world-sam/zephyr/zephyr.signed.bin`

**Expected behavior**
Hello world example successfully downloads to the target.

**Impact**
USB DFU does not work when `CONFIG_DFU_WILL_DETACH` is enabled.

**Logs and console output**

```
Opening DFU capable USB device...
Device ID 2fe3:0005
Device DFU version 0110
Claiming USB DFU (Run-Time) Interface...
Setting Alternate Interface zero...
Determining device status...
DFU state(0) = appIDLE, status(0) = No error condition is present
Device really in Run-Time Mode, send DFU detach request...
Device will detach and reattach...
dfu-util: Lost device after RESET?
```

**Environment:**
 - OS: Linux
 - Zephyr SDK 0.15.0
 - PR #50268

### PR DESCRIPTION
**Pull request by desowin**
SAM V71 Xplained Ultra failed to re-enumerate on the bus after device detach-attach sequence. The device was recognized by the host, but it was not responding to control transfers, i.e. it was not acknowledging SETUP data. Make device acknowledge SETUP data by reconfiguring EP0 when necessary and actually set DETACH bit during detach instead of clearing it.

Fixes  #50549

### CODE REVIEW

**Review by jfischer-no — DISMISSED** [review]

File: drivers/usb/device/usb_dc_sam_usbhs.c [hunk 1]
```diff
@@ -348,7 +358,7 @@ int usb_dc_attach(void)
 int usb_dc_detach(void)
 {
 	/* Detach the device */
-	USBHS->USBHS_DEVCTRL &= ~USBHS_DEVCTRL_DETACH;
+	USBHS->USBHS_DEVCTRL |= USBHS_DEVCTRL_DETACH;
```
Comment (anangl) [inline drivers/usb/device/usb_dc_sam_usbhs.c:361]: This change seems to deserve a separate commit.

Comment (desowin) [reply drivers/usb/device/usb_dc_sam_usbhs.c:361]: Done.

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
