### PR TITLE
Bluetooth: controller: split: Fix assert on DLE procedure stall

### LINKED ISSUE #23069: Bluetooth: controller: Assert in data length update procedure
**Describe the bug**
Seen (both on real phone and in simulation) that the LLCP system can crash if a connection event was lost due to scheduling conflicts.

A slave device that both advertises and has a connection with a master phone.  On the connection the master makes a PHY update followed by the save doing a length update. After the PHY update instant the master does a new length update. Unfortunately the master length update is placed at the connection event right after the PHY update, but the connection event that the PHY update is to take place is lost on the slave due to scheduling conflict with the advertiser role. Due to the lost event the LLCP machine has not been run prior to handling the length update on the slave and the LLCP machine is now in the wrong state.

```
ull_conn.c:4635 ull_conn_rx ASSERT(pdu_rx -->llctrl.opcode == PDU_DATA_LLCTRL_TYPE_LENGTH_RSP)
```

**To Reproduce**
(assuming the below build process, as the issue is reported by someone else)
1. mkdir build; cd build
2. cmake -DBOARD=board\nrf52_pca10040 ../samples/bluetooth/peripheral
3. make

**Expected behavior**
No assertion

**Impact**
showstopper

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.
image

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 58908aa5d0

**Additional context**
Add any other context about the problem here. None

### PR DESCRIPTION
**Pull request by cvinayak**
Fix local initiated Data Length Update procedure from being
stalled when a remote initiates a procedure with instant.

Fixes #23069.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by thoh-ot — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 1]
```diff
@@ -830,8 +830,27 @@ int ull_conn_llcp(struct ll_conn *conn, u32_t ticks_at_expire, u16_t lazy)
 		}
 	}
 
-	/* check if procedure is requested */
+	/* Check if procedures with instant or encryption setup is requested or
+	 * active.
+	 */
 	if (((conn->llcp_req - conn->llcp_ack) & 0x03) == 0x02) {
+		/* Process parallel procedures that are active */
+		if (0) {
```
Comment (kruithofa) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: why the 'if (0)'?

**Review by mtpr-ot — APPROVED** [review]
LGTM

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Ah! A style I follow when having many conditionally compiled if-then block. But, here I should not be using it. If you have a strong feeling I should change it, please request change.

Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: No strong feeling, let's get this in so we can proceed

**Review by kruithofa — APPROVED** [review]
