### PR TITLE
Bluetooth: Host: Remove blocking behaviour from `gatt_req_alloc`

### LINKED ISSUE #39624: Bluetooth: Submitting more GATT writes than available buffers blocks for 30s and then errors out
**Describe the bug**
If I after subscribing to a characteristic fire away too many `bt_gatt_write`'s, the thread will block for 30 seconds.

I have:
```
CONFIG_BT_CONN_TX_MAX=10
CONFIG_BT_L2CAP_TX_BUF_COUNT=10
CONFIG_BT_BUF_ACL_TX_COUNT=10
```

If I after subscribing do:
```
    LOG_INF("subscribed");
    for (int i = 0; i < (CONFIG_BT_CONN_TX_MAX - 1); ++i) {
        if (bt_gatt_write(ble_api_conn->conn, &wr_params) != 0)
            LOG_ERR("write failed");
    }
    LOG_INF("wrote");
```
Everything works as expected:
```
[00:00:06.715,942] <inf> main: subscribed
[00:00:06.716,094] <inf> main: wrote
```
But if I iterate 10 (or more) times, this happens:
```
[00:00:12.633,605] <inf> main: subscribed
[00:00:42.633,911] <err> main: write failed
[00:00:42.633,941] <inf> main: wrote
```

**To Reproduce**
1. Connect and subscribe to a GATT characteristic
2. Write at least `CONFIG_BT_CONN_TX_MAX` times

**Expected behavior**
Either having `bt_gatt_write` return an error, or get an error in the registered callback.

**Impact**
Annoyance - I keep track of the number of outstanding writes to avoid this.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain gcc-arm-none-eabi-10.3-2021.07
 - v2.7.0 (but i'm pretty sure this has been an issue for a long time)

### PR DESCRIPTION
**Pull request by alwa-nordic**
bt_gatt_write would block in call to gatt_req_alloc if there were no
free req objects. `bt_gatt_write` is documented as async, so it should
not block.  This also affects all other `bt_gatt_*` functions that
allocate a req object.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/39624 where
if `bt_gatt_write` is called from BT RX thread (as can happen if it is
called from a bluetooth callback), the BT RX thread can be blocked and
prevented from processing the request responses and unblocking itself.
This was the cause of a soft 30s deadlock until gatt_req_alloc timeouts.

Signed-off-by: Aleksander Wasaznik <aleksander.wasaznik@nordicsemi.no>

### CODE REVIEW

File: include/bluetooth/gatt.h [hunk 1]
```diff
@@ -1465,6 +1465,15 @@ struct bt_gatt_write_params {
...
  *  @return 0 in case of success or negative value in case of error.
+ *
+ *  @retval 0
+ *      Successfully queued request.
+ *      Will call @p params->func on resolution.
+ *
+ *  @retval -ENOMEM
+ *      Too many pending ATT requests.
+ *      Allow a pending request to resolve before retrying.
+ *      Relevant limit is @kconfig{CONFIG_BT_L2CAP_TX_BUF_COUNT}.
```
Comment (jhedberg) [inline include/bluetooth/gatt.h:1476]: This constitutes in some ways API breakage (in the sense that some application might have depended on the blocking behaviour for correct functionality). Would it make more sense to introduce a `bt_gett_write_async()` along side of the old API? If we don't do that we should follow the API change process and clearly document this in the release notes for Zephyr 3.0.

Comment (alwa-nordic) [reply include/bluetooth/gatt.h:1476]: I see your point. But just above in the function doc we have:

>  This procedure is asynchronous therefore the parameters need to remains valid while it is active.

So there was a mismatch between the documented API and behavior. This change makes the function adhere to its API. Given the function doc above, `bt_gatt_write_async` would be confusing.

Does this change your mind on this, @jhedberg?

Of course we should consider if we are breaking someones code. The blocking behavior could easily be relied on as flow control.

We could instead ratify the blocking behavior in the API. It may be possible to give a more informative LOG_ERR about the timeout. We could detect that we are on BT RX thread and report it as a deadlock. But what if we are in a more complex situation involving a transitive blocking where BT RX thread waits on different thread that is stuck in `bt_gatt_write`. Maybe we could detect a blocked BT RX thread on timeout and log it as the probable reason for the timeout. But it gets needlessly complex.

I prefer removing the blocking to remove any concerns of a deadlock. But I know how unpopular breaking other peoples code for the sake of correctness is. I would not be against scheduling this change for a major release.

Comment (jhedberg) [reply include/bluetooth/gatt.h:1476]: > Does this change your mind on this, @jhedberg?

Yes, that's a pretty good point. However, I still think it would be good to get maximal visibility on this change by having an entry in the release notes for it.

Comment (joerchan) [reply include/bluetooth/gatt.h:1476]: This seems to be the same issue that we had with conn_tx_alloc.
Which we solved like this:
```
static struct bt_conn_tx *conn_tx_alloc(void)
{
	/* The TX context always get freed in the system workqueue,
	 * so if we're in the same workqueue but there are no immediate
	 * contexts available, there's no chance we'll get one by waiting.
	 */
	if (k_current_get() == &k_sys_work_q.thread) {
		return k_fifo_get(&free_tx, K_NO_WAIT);
	}
```
This is also documented in the API headers.

Not saying any solution is better than the other, but it gets confusing when it it is handled in multiple different ways.

Comment (alwa-nordic) [reply include/bluetooth/gatt.h:1476]: Good idea. `bt_gatt_write` is not the only public function that has changed. I think we should mention them all in the release notes. I'll have a look and find them. Should it go into doc/releases/release-notes-3.0.rst?

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -2018,8 +2018,8 @@ static struct bt_att_req *gatt_req_alloc(bt_att_func_t func, void *params,
 {
 	struct bt_att_req *req;
 
-	/* Allocate new request */
-	req = bt_att_req_alloc(BT_ATT_TIMEOUT);
+	/* This function is called from asynchronous bt_gatt functions and shall not block/wait. */
+	req = bt_att_req_alloc(K_NO_WAIT);
```
Comment (carlescufi) [inline subsys/bluetooth/host/gatt.c:2022]:
```
	if (k_current_get() == &bt_rx_thread) {
		return bt_att_req_alloc(K_NO_WAIT);
	}
```

Comment (carlescufi) [reply subsys/bluetooth/host/gatt.c:2022]: And then add a comment similar to https://github.com/zephyrproject-rtos/zephyr/blob/main/include/bluetooth/gatt.h#L985

File: include/bluetooth/gatt.h (hunk 1 above)
Comment (Thalley) [reply include/bluetooth/gatt.h]: > This procedure is asynchronous therefore the parameters need to remains valid while it is active.

@alwa-nordic This line got me thinking: When you read this, it sounds like procedure == function to you, but I am not sure I agree with that. The function may still be blocking, even if it an asynchronous procedure, so I don't agree that there is a mismatch between the documented API and the behavior. 

In any case, the blocking behavior of the function have caused significant amounts of issues when the receiver of callbacks in the RX thread attempts to send additional requests, so I am not against this change at all.

It will be different behavior from the POSIX `send()` function though. Not sure how badly Zephyr tries to be similar to POSIX.

File: include/bluetooth/gatt.h [hunk 3]
```diff
@@ -1208,10 +1208,30 @@ struct bt_gatt_exchange_params {
  *
  *  @note Shall only be used once per connection.
  *
+ *  The Response comes in callback @p params->func. The callback is run from
+ *  the Bluetooth event context. @p *params must remain valid until start of
```
Comment (Thalley) [inline include/bluetooth/gatt.h:1212]: "Bluetooth event context" is not described or mentioned anywhere else. I suppose you mean the RX thread?

Comment (Thalley) [reply include/bluetooth/gatt.h:1212]:
```suggestion
 *  the Bluetooth event context. @p params must remain valid until start of
```

File: include/bluetooth/gatt.h [hunk 4]
```diff
@@ -1208,10 +1208,30 @@ struct bt_gatt_exchange_params {
...
+ *  @retval 0
+ *      Successfully queued request.
+ *      Will call @p params->func on resolution.
+ *
+ *  @retval -ENOMEM
+ *      ATT request queue is full and blocking would cause deadlock.
+ *      Allow a pending request to resolve before retrying, or call
+ *      this function outside Bluetooth event context to get blocking
+ *      behavior.
+ *      Queue size is controlled by @kconfig{CONFIG_BT_L2CAP_TX_BUF_COUNT}.
```
Comment (Thalley) [inline include/bluetooth/gatt.h:1234]: Uh, I like the use of `@retval`. That's something I'd like to see more of in the Bluetooth headers

File: include/bluetooth/gatt.h [hunk 5]
```diff
@@ -1340,13 +1360,31 @@ struct bt_gatt_discover_params {
  *  For each attribute found the callback is called which can then decide
  *  whether to continue discovering or stop.
  *
- *  @note This procedure is asynchronous therefore the parameters need to
- *        remains valid while it is active.
+ *  The Response comes in callback @p params->func. The callback is run from
+ *  the Bluetooth event context. @p *params must remain valid until start of
```
Comment (Thalley) [inline include/bluetooth/gatt.h:1364]:
```suggestion
 *  the Bluetooth event context. @p params must remain valid until start of
```

File: include/bluetooth/gatt.h [hunk 6]
```diff
@@ -1208,10 +1208,30 @@ struct bt_gatt_exchange_params {
...
  *  @note Shall only be used once per connection.
  *
+ *  The Response comes in callback @p params->func. The callback is run from
+ *  the Bluetooth event context. @p *params must remain valid until start of
+ *  callback.
+ *
+ *  This function will block while the ATT request queue is full, except when
+ *  called from Bluetooth event context. When called from Bluetooth context,
+ *  this function will instead instead return `-ENOMEM` if it would block to
+ *  avoid a deadlock.
```
Comment (Thalley) [inline include/bluetooth/gatt.h:1218]: It's not bad to have, but it does seem a bit superfluous to describe the return value both here and in the `@retval`

File: include/bluetooth/gatt.h [hunk 7]
```diff
@@ -1425,13 +1463,31 @@ struct bt_gatt_read_params {
  *  caller will need to read the remaining data separately using the handle and
  *  offset.
  *
- *  @note This procedure is asynchronous therefore the parameters need to
- *        remains valid while it is active.
+ *  The Response comes in callback @p params->func. The callback is run from
+ *  the Bluetooth event context. @p *params must remain valid until start of
```
Comment (Thalley) [inline include/bluetooth/gatt.h:1467]:
```suggestion
 *  the Bluetooth event context. @p params must remain valid until start of
```

File: subsys/bluetooth/host/gatt.c [hunk 8]
```diff
@@ -4607,45 +4640,49 @@ int bt_gatt_unsubscribe(struct bt_conn *conn,
...
 	}
 
+	if (!sub_has_subscription(sub, params)) {
+		return -EINVAL;
+	}
+
+	if (!sub_has_other_subscriptions_to_same_attribute(sub, params)) {
+		int gatt_write_err;
+
+		params->value = 0x0000;
```
Comment (Thalley) [inline subsys/bluetooth/host/gatt.c:4650]: Suggest to create a 
```
#define BT_GATT_CCC_UNSUB			0x0000
```
and use that here

File: subsys/bluetooth/host/gatt.c [hunk 9]
```diff
@@ -4587,13 +4592,41 @@ int bt_gatt_resubscribe(uint8_t id, const bt_addr_le_t *peer,
...
+}
+
 int bt_gatt_unsubscribe(struct bt_conn *conn,
 			struct bt_gatt_subscribe_params *params)
 {
 	struct gatt_sub *sub;
 	struct bt_gatt_subscribe_params *tmp, *next;
-	bool has_subscription = false, found = false;
 	sys_snode_t *prev = NULL;
+	bool wait_for_ccc_write_response = false;
```
Comment (Thalley) [inline subsys/bluetooth/host/gatt.c:4629]: Not crazy about this name, as we are actually not really waiting for anything.

File: subsys/bluetooth/host/hci_core.c [hunk 10]
```diff
@@ -3363,8 +3363,29 @@ void hci_event_prio(struct net_buf *buf)
 	}
 }
 
+static k_tid_t bt_recv_thread_id;
+bool bt_recv_is_blocked_by_current_thread(void)
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:3367]: Just call this `bt_is_recv_thread()'

**Review by Thalley — CHANGES_REQUESTED** [review]
Minor comments, otherwise the change looks good

File: subsys/bluetooth/host/gatt.c [hunk 11]
```diff
@@ -4587,13 +4592,41 @@ int bt_gatt_resubscribe(uint8_t id, const bt_addr_le_t *peer,
...
+	SYS_SLIST_FOR_EACH_CONTAINER(&sub->list, other_params, node) {
+		if (params == other_params) {
+			return true;
+		}
+	}
+
+	return false;
+}
+
+static bool sub_has_other_subscriptions_to_same_attribute(struct gatt_sub *sub,
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:4609]: You really seem to like long symbol names 😉 

How about just `has_other_sub()`?

File: subsys/bluetooth/host/gatt.c (hunk 9 above)
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:4629]: How about calling this `other_sub' and not pre-initializing it, rather pass the return value from `has_other_sub()` to it?

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/hci_core.c [hunk 12]
```diff
@@ -3363,8 +3363,29 @@ void hci_event_prio(struct net_buf *buf)
...
+		bt_recv_thread_id = k_current_get();
+	}
+
+	__ASSERT(bt_recv_thread == k_current_get(),
+		"Assumed bt_recv is always called by the same thread.");
+}
+
 int bt_recv(struct net_buf *buf)
 {
+	save_bt_recv_thread_id();
```
Comment (carlescufi) [inline subsys/bluetooth/host/hci_core.c:3387]: inline the function contents directly in `bt_recv`

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 8 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:4629]: I chose not to do this because it seems to me that `BT_GATT_CCC_*` is intended for `bt_gatt_subscribe_params.value`. And it makes little sense to allow BT_GATT_CCC_UNSUB there.

**Comment by alwa-nordic** [comment]
I had a bug in my previous change set. I forgot to wrap the ccc write with `if (!has_subscription)`. Fixed now.

**Comment by alwa-nordic** [comment]
I tried to de-duplicate the documentation using `@snippet{doc} this my_snippet`. But it did not work well. The delimited snippet (surrounded by `[my_snippet]`) has to be in a Doxygen block since it's not C code. But we have a rule that comments must start with a `*`. But the snippet is captured verbatim and `*` is not stripped even if the snippet is inside a Doxygen block. The `*` parsed as markdown and ends up producing a bullet list.

File: subsys/bluetooth/host/gatt.c [hunk 13]
```diff
@@ -4608,19 +4607,10 @@ int bt_gatt_unsubscribe(struct bt_conn *conn,
 	}
 
 	/* Lookup existing subscriptions */
-	SYS_SLIST_FOR_EACH_CONTAINER_SAFE(&sub->list, tmp, next, node) {
-		/* Remove subscription */
+	SYS_SLIST_FOR_EACH_CONTAINER(&sub->list, tmp, node) {
```
Comment (carlescufi) [inline subsys/bluetooth/host/gatt.c:4610]: instead of `continue` you could have `else if()`

**Review by carlescufi — CHANGES_REQUESTED** [review]
Need to check with @gmarull whether there is a better alternative to the duplication in doxygen.

File: include/bluetooth/gatt.h [hunk 14]
```diff
@@ -1340,13 +1356,27 @@ struct bt_gatt_discover_params {
...
+ *
+ *  @retval 0
+ *      Successfully queued request.
+ *      Will call @p params->func on resolution.
+ *
+ *  @retval -ENOMEM
+ *      ATT request queue is full and blocking would cause deadlock.
+ *      Allow a pending request to resolve before retrying, or call this
+ *      function outside the BT RX thread to get blocking behavior.
+ *      Queue size is controlled by @kconfig{CONFIG_BT_L2CAP_TX_BUF_COUNT}.
```
Comment (gmarull) [inline include/bluetooth/gatt.h:1379]: this documentation is now inconsistent, looks like first `@return` is now redundant?

better use this format, for consistency:
```c
 *  @retval -ENOMEM ATT request queue is full and blocking would cause deadlock.
 *  Allow a pending request to resolve before retrying, or call this function outside the
 *  BT RX thread to get blocking behavior. Queue size is controlled by 
 *  @kconfig{CONFIG_BT_L2CAP_TX_BUF_COUNT}.
```

File: include/bluetooth/gatt.h [hunk 15]
```diff
@@ -1340,13 +1356,27 @@ struct bt_gatt_discover_params {
  *  For each attribute found the callback is called which can then decide
  *  whether to continue discovering or stop.
  *
- *  @note This procedure is asynchronous therefore the parameters need to
- *        remains valid while it is active.
+ *  The Response comes in callback @p params->func. The callback is run from
```
Comment (carlescufi) [inline include/bluetooth/gatt.h:1359]: We could potentially use something like pinctrl here, its own "named" section: https://docs.zephyrproject.org/latest/doxygen/html/group__pinctrl__interface.html#ga46d7997af7e9231b431c79af34288d50

**Review by carlescufi — CHANGES_REQUESTED** [review]
Doxygen needs rework

**Comment by jsiverskog** [comment]
@alwa-nordic : what's the plan for this mr?

File: include/bluetooth/gatt.h [hunk 16]
```diff
@@ -1216,10 +1216,24 @@ struct bt_gatt_exchange_params {
...
+ *  the BT RX thread. @p params must remain valid until start of callback.
+ *
+ *  This function will block while the ATT request queue is full, except when
+ *  called from the BT RX thread, as this would cause a deadlock.
+ *
  *  @param conn Connection object.
  *  @param params Exchange MTU parameters.
  *
  *  @return 0 in case of success or negative value in case of error.
```
Comment (carlescufi) [inline include/bluetooth/gatt.h:1228]: remove this line

**Review by carlescufi — CHANGES_REQUESTED** [review]

**Review by carlescufi — APPROVED** [review]
