### PR TITLE
I2S_MCUX: Fixup I2S MCUX Audio PLL Rate Calculation and Reg Writes

### LINKED ISSUE #45800: Clock control settings for MCUX Audio Clock are Incorrect
**Describe the bug**
The Audio PLL Clock Rate calculation for the I2S Clock is incorrect, resulting in incorrect downstream clocks (for example I2S MCLK). Additionally, the PLL configuration for NXP RT parts configures the PLL settings outside of their allowable ranges according to the datasheet.

This affects:
- MCUX Clock Control Driver when using the Audio PLL
- IMX RT Parts configuring the SAI module in DTS

**To Reproduce**
Run the sample I2S test code on a compatible NXP RT part:
https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/i2s/i2s_api

1. west build -p auto -b mimxrt1060_evk tests/drivers/i2s/i2s_api
2. Probe the MCLK output line with a scope or logic analyzer and measure the MClk frequency
3. Compare it to the calculated MCLK rate (from the driver: [here](https://github.com/zephyrproject-rtos/zephyr/blob/2dc866fa487ba524b426adc453d028bdd7aaa4e2/drivers/i2s/i2s_mcux_sai.c#L448))
4. Notice the measured value and the calculated value do not agree.

**Expected behavior**
The calculated mclk rate should match the actual produced rate and the driver should set up the PLL according to datasheet specifications.

**Impact**
I2S cannot be correctly configured on RT parts.

### PR DESCRIPTION
**Pull request by NickolasLapp**
This PR Fixes the Audio PLL Rate Calculation (there was an additional
divide / 8 which is not necessary and does not appear in similar
calculations in example code from the SDK).

Additionally, it adjusts the SAI .dtsi to more correctly configure the
mclk rate, and adds comments specifying what the regististers mean.

Signed-off-by: Nickolas Lapp <nickolaslapp@gmail.com>

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/45800

### CODE REVIEW

File: drivers/clock_control/clock_control_mcux_ccm.c [hunk 1]
```diff
@@ -170,17 +170,17 @@ static int mcux_ccm_get_subsys_rate(const struct device *dev,
 
 #ifdef CONFIG_I2S_MCUX_SAI
 	case IMX_CCM_SAI1_CLK:
-		*rate = CLOCK_GetFreq(kCLOCK_AudioPllClk) / 8
+		*rate = CLOCK_GetFreq(kCLOCK_AudioPllClk)
```
Comment (NickolasLapp) [inline drivers/clock_control/clock_control_mcux_ccm.c:173]: From the RM: 
image

The Audio PLL goes directly through 2 dividers, but no automatic DIV/8 is needed. This is also backed up by example driver code from the MCU Expresso SDK Builder.

File: dts/arm/nxp/nxp_rt.dtsi [hunk 2]
```diff
@@ -800,19 +799,27 @@
...
-					<&anatop 0x70 0x7F 32>,
-					<&anatop 0x70 0x18 1>,
-					<&anatop 0x80 0x3FFFFFFF 77>,
-					<&anatop 0x90 0x3FFFFFFF 100>;
+			// Audio PLL Output Frequency is determined by:
+			// (Fref * (DIV_SELECT + NUM/DENOM)) / POST_DIV
+			// = (24MHz * (32 + 77 / 100)) / 1 = 786.48 MHz
+		       pll-clocks = <&anatop 0x70 0xC000 0>,
+				      <&anatop 0x70 0x7F 32>,
+				      <&anatop 0x70 0x18 1>,
```
Comment (NickolasLapp) [inline dts/arm/nxp/nxp_rt.dtsi:807]: image
Bits 20,19 `(0x3<<19 == 0x180000)` are the post divider

File: dts/arm/nxp/nxp_rt.dtsi [hunk 3]
```diff
@@ -800,19 +799,27 @@
...
+				      <&anatop 0x80 0x3FFFFFFF 77>,
+				      <&anatop 0x90 0x3FFFFFFF 100>;
 			pll-clock-names = "src", "lp", "pd", "num", "den";
+			// The maximum input frequency into the SAI mclk input is 300MHz
```
Comment (NickolasLapp) [inline dts/arm/nxp/nxp_rt.dtsi:811]: image

**Comment by mmahadevan108** [comment]
@hakehuang could you please review these changes.

File: dts/arm/nxp/nxp_rt.dtsi [hunk 4]
```diff
@@ -22,7 +22,6 @@
 		cpu0: cpu@0 {
 			device_type = "cpu";
 			compatible = "arm,cortex-m7";
-			d-cache-line-size = <32>;
```
Comment (mmahadevan108) [inline dts/arm/nxp/nxp_rt.dtsi:25]: Could you please clarify why this was removed

File: dts/arm/nxp/nxp_rt.dtsi [hunk 5]
```diff
@@ -800,19 +799,27 @@
...
-			podf = <63>;
-			pll-clocks = <&anatop 0x70 0xC000 0>,
-					<&anatop 0x70 0x7F 32>,
-					<&anatop 0x70 0x18 1>,
-					<&anatop 0x80 0x3FFFFFFF 77>,
-					<&anatop 0x90 0x3FFFFFFF 100>;
+			// Audio PLL Output Frequency is determined by:
+			// (Fref * (DIV_SELECT + NUM/DENOM)) / POST_DIV
+			// = (24MHz * (32 + 77 / 100)) / 1 = 786.48 MHz
+		       pll-clocks = <&anatop 0x70 0xC000 0>,
```
Comment (hakehuang) [inline dts/arm/nxp/nxp_rt.dtsi:805]: although defined in device tree, but driver code does not use it, still default value

File: drivers/clock_control/clock_control_mcux_ccm.c (hunk 1 above)
Comment (hakehuang) [reply drivers/clock_control/clock_control_mcux_ccm.c:173]: the default value is /4 and /2 which is /8, and currently there is no where that we change this vaule

File: dts/arm/nxp/nxp_rt.dtsi (hunk 3 above)
Comment (hakehuang) [reply dts/arm/nxp/nxp_rt.dtsi:811]: thanks for the bits setting correction.

File: dts/arm/nxp/nxp_rt.dtsi [hunk 6]
```diff
@@ -800,19 +799,27 @@
...
+				      <&anatop 0x70 0x7F 32>,
+				      <&anatop 0x70 0x180000 1>,
```
Comment (hakehuang) [inline dts/arm/nxp/nxp_rt.dtsi:807]: Thanks for the correction

File: dts/arm/nxp/nxp_rt.dtsi [hunk 7]
```diff
@@ -800,19 +799,27 @@
...
+				      <&anatop 0x80 0x3FFFFFFF 77>,
+				      <&anatop 0x90 0x3FFFFFFF 100>;
 			pll-clock-names = "src", "lp", "pd", "num", "den";
+			// The maximum input frequency into the SAI mclk input is 300MHz
+			// Based on this requirement, pre-div must be at least 3
+			// The pre-div and post-div are one less than the actual divide-by amount.
+			// A pre-div value of 0x1 results in a pre-divider of (1+1) = 2
+			pre-div = <0x3>;
+			podf = <0x3F>;
```
Comment (hakehuang) [inline dts/arm/nxp/nxp_rt.dtsi:816]: the podf shall not be 63 if you change the pre-div to 3, it shall be 15

**Comment by hakehuang** [comment]
> @hakehuang could you please review these changes.

@DerekSnell do you know why we overclock the podf(> 300M), I copy  the defult value 0 from sdk samples.

File: dts/arm/nxp/nxp_rt.dtsi (hunk 7 above)
Comment (NickolasLapp) [reply dts/arm/nxp/nxp_rt.dtsi]: Done

**Comment by DerekSnell** [comment]
> @DerekSnell do you know why we overclock the podf(> 300M), I copy the defult value 0 from sdk samples.

Hi @hakehuang ,
Thanks for pointing out the issue with the SDK example.  This looks like the PODF maximum limitation was missed by the SDK team.  I have reported this to them internally with ticket MCUX-50011.  Thank you to @NickolasLapp for making us aware.

File: dts/arm/nxp/nxp_rt.dtsi [hunk 8]
```diff
@@ -800,19 +800,27 @@
...
 			reg = <0x40384000 0x4000>;
 			clocks = <&ccm IMX_CCM_SAI1_CLK 0x7C 2>;
-			pre-div = <0>;
-			podf = <63>;
-			pll-clocks = <&anatop 0x70 0xC000 0>,
-					<&anatop 0x70 0x7F 32>,
-					<&anatop 0x70 0x18 1>,
-					<&anatop 0x80 0x3FFFFFFF 77>,
-					<&anatop 0x90 0x3FFFFFFF 100>;
+			// Audio PLL Output Frequency is determined by:
```
Comment (danieldegrasse) [inline dts/arm/nxp/nxp_rt.dtsi:803]: @ioannisg Should `checkpatch` be catching these comments? [Zephyr coding guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#coding-style) suggest these should be C89 comments:
> Use C89-style single line comments, /*  */. The C99-style single line comment, //, is not allowed.

**Review by hakehuang — DISMISSED** [review]

File: dts/arm/nxp/nxp_rt.dtsi [hunk 9]
```diff
@@ -800,19 +800,27 @@
...
+			// A pre-div value of 0x1 results in a pre-divider of (1+1) = 2
+			pre-div = <0x3>;
+			podf = <0x0F>;
 			pinmuxes = <&iomuxcgpr 0x4 0x80000>;
 			interrupts = <56 0>;
 			dmas = <&edma0 0 19>, <&edma0 0 20>;
 			dma-names = "rx", "tx";
-			nxp,tx-channel = <0>;
+			// This translates to SAIChannelMask (fsl_sai.c) and cannot be 0
+			nxp,tx-channel = <1>;
```
Comment (DerekSnell) [inline dts/arm/nxp/nxp_rt.dtsi:823]: good point

**Review by DerekSnell — DISMISSED** [review]
@NickolasLapp , thank you for fixing these issues.  These changes look good to me

File: dts/arm/nxp/nxp_rt.dtsi [hunk 10]
```diff
@@ -800,19 +800,27 @@
...
+			// (Fref * (DIV_SELECT + NUM/DENOM)) / POST_DIV
+			// = (24MHz * (32 + 77 / 100)) / 1 = 786.48 MHz
+		       pll-clocks = <&anatop 0x70 0xC000 0>,
+				      <&anatop 0x70 0x7F 32>,
+				      <&anatop 0x70 0x180000 1>,
+				      <&anatop 0x80 0x3FFFFFFF 77>,
+				      <&anatop 0x90 0x3FFFFFFF 100>;
 			pll-clock-names = "src", "lp", "pd", "num", "den";
+			// The maximum input frequency into the SAI mclk input is 300MHz
+			// Based on this requirement, pre-div must be at least 3
```
Comment (danieldegrasse) [inline dts/arm/nxp/nxp_rt.dtsi:813]: @NickolasLapp can you replace all C99 style `// ` comments in this PR with `/* */` C89 style comments? CI isn't catching it but generally only C89 style comments are allowed upstream

File: dts/arm/nxp/nxp_rt.dtsi [hunk 11]
```diff
@@ -828,11 +836,11 @@
...
 			podf = <63>;
-			pll-clocks = <&anatop 0x70 0xC000 0>,
-				   <&anatop 0x70 0x7F 32>,
-				   <&anatop 0x70 0x18 1>,
-				   <&anatop 0x80 0x3FFFFFFF 77>,
-				   <&anatop 0x90 0x3FFFFFFF 100>;
+			pll-clocks = <&anatop 0x70 0xC000 0x0>,
+					<&anatop 0x70 0x7F 32>,
+					<&anatop 0x70 0x180000 1>,
+					<&anatop 0x80 0x3FFFFFFF 0>,
```
Comment (danieldegrasse) [inline dts/arm/nxp/nxp_rt.dtsi:842]: Any reason the numerator for this PLL is 0 and not 77?

File: dts/arm/nxp/nxp_rt.dtsi (hunk 8 above)
Comment (dleach02) [inline dts/arm/nxp/nxp_rt.dtsi:803]: @NickolasLapp, please replace the // with /* */

**Review by dleach02 — CHANGES_REQUESTED** [review]
Please make a pass to change the comments to /* */. The CI is missing this but will likely change in the future to address this oversite.

File: dts/arm/nxp/nxp_rt.dtsi (hunk 11 above)
Comment (NickolasLapp) [reply dts/arm/nxp/nxp_rt.dtsi]: Reverted--this was for some internal testing with a different MCLK value.

File: dts/arm/nxp/nxp_rt.dtsi (hunk 10 above)
Comment (NickolasLapp) [reply dts/arm/nxp/nxp_rt.dtsi]: Comments are replaced! Thanks for catching

File: dts/arm/nxp/nxp_rt.dtsi (hunk 8 above)
Comment (NickolasLapp) [reply dts/arm/nxp/nxp_rt.dtsi]: Done, thanks!

**Review by hakehuang — APPROVED** [review]

**Comment by dleach02** [comment]
@NickolasLapp can you add a GitHub issue and then add a "Fixes #<issue>" for traceability?

**Comment by NickolasLapp** [comment]
Fixes: #45800
CC: @dleach02

**Review by dleach02 — APPROVED** [review]
