### PR TITLE
NXP LPSPI: Fix native CS on non-DMA driver

### LINKED ISSUE #16544: drivers: spi: spi_mcux_lpspi: inconsistent chip select behaviour
**Describe the bug**
The MCUX LPSPI SPI driver handles SPI chip selects inconsistently when comparing GPIO CS and "native" controller CS handling over multipart transfers.

With GPIO CS enabled (where the LPSPI controller does not control the CS line), the CS line is kept asserted through the entire transfer. This is opposed to what happens when the CS line is controlled by the LPSPI controller itself; then the CS line is deasserted between the different parts of the transfer.

**To Reproduce**
```
#include <zephyr.h>
#include <misc/printk.h>
#include <spi.h>

#define SPI_LABEL     "SPI_1"
#define GPIO_CS_LABEL "GPIO_0"
#define GPIO_CS_PIN   16

void main(void)
{
	struct spi_config spi_cfg;
	struct device *spi_dev;
	struct spi_cs_control spi_cs;
	u8_t cmd[2] = { 0xaa, 0x55 }; /* 2 bytes command */
	u8_t response[2];             /* 2 bytes response */

	const struct spi_buf tx_bufs[] = {
		{
			.buf = cmd,
			.len = sizeof(cmd),
		},
	};
	const struct spi_buf_set tx = {
		.buffers = tx_bufs,
		.count = ARRAY_SIZE(tx_bufs),
	};
	const struct spi_buf rx_bufs[] = {
		{
			.buf = NULL,
			.len = sizeof(cmd), /* 2 dummy bytes */
		},
		{
			.buf = response,
			.len = sizeof(response),
		},
	};
	const struct spi_buf_set rx = {
		.buffers = rx_bufs,
		.count = ARRAY_SIZE(rx_bufs),
	};

	spi_dev = device_get_binding(SPI_LABEL);
	if (!spi_dev) {
		printk("SPI device not found\n");
		return;
	}

	spi_cfg.operation = SPI_OP_MODE_MASTER | SPI_TRANSFER_MSB |
		SPI_WORD_SET(8);
	spi_cfg.frequency = 1000000;
	spi_cfg.slave = 2;

#if 0
	spi_cs.gpio_dev = device_get_binding(GPIO_CS_LABEL);
	if (!spi_cs.gpio_dev) {
		printk("SPI GPIO CS device not found\n");
		return;
	}
	spi_cs.gpio_pin = GPIO_CS_PIN;
	spi_cs.delay = 1; /* us */
	spi_cfg.cs = &spi_cs;
#else
	spi_cfg.cs = NULL;
#endif

	spi_transceive(spi_dev, &spi_cfg, &tx, &rx);
}

```

**Expected behavior**
The CS line remains asserted through all the parts of the multipart transfer.

**Impact**
Deasserting the CS line in the middle of a transfer causes problem e.g. when communicating with SPI EEPROMs.

**Screenshots or console output**
When using GPIO CS:
GPIO CS

When using LPSPI CS:
SPI CS

**Environment (please complete the following information):**
 - OS: GNU/Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: c88c91942d984e4c2ad2b3484576d39c2538858d

**Additional context**
This was spotted when trying to use a SPI EEPROM with the TWR-KE18F board, but it is not limited to that board nor to the KE1xF SoC series, as far as I can tell.

### LINKED ISSUE #63280: drivers: spi_mcux_lpspi: spurious irq interrupt
**Describe the bug**
The `spi_mcux_lpspi.c` `spi_transceive` implementation sometimes fails.

This is due to a spurious interrupt in [LPSPI_MasterTransferHandleIRQ](https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/mcux-sdk/drivers/lpspi/fsl_lpspi.c#L1643C15-L1643C15).

The issue arises if the SPI clock speed is high and there are other interrupts occurring.

I have found a work around but not a solution:
```c
static void spi_mcux_isr(const struct device *dev)
...
	if (data->handle.state == (uint8_t)kLPSPI_Idle) {
		return;
	}

	LPSPI_MasterTransferHandleIRQ(base, &data->handle);
}
```

**To Reproduce**
1. Increase SPI clock frequency: `sed -i 's|6400000>|30000000>|g' zephyr/samples/drivers/led_ws2812/boards/mimxrt1050_evk.overlay`
2. Add `assert(handle->state != (uint8_t)kLPSPI_Idle);` in the top of `modules/hal/nxp/mcux/mcux-sdk/drivers/lpspi/fsl_lpspi.c:LPSPI_MasterTransferHandleIRQ`
3. Build sample: `west build -p always -b mimxrt1050_evk zephyr/samples/drivers/led_ws2812/ -- -DCONFIG_SAMPLE_LED_UPDATE_DELAY=0 -DCONFIG_SHELL=y -DCONFIG_ASSERT=y`
4. Since the issue is not consistent the error might occur by itself during boot. If not press and hold \<ENTER\> to stress the system.

```
*** Booting Zephyr OS build zephyr-v3.4.0-4642-g1084c8b083f0 ***
[00:00:00.000,000] <inf> main: Found LED strip device ws2812@0
[00:00:00.000,000] <inf> main: Displaying pattern on strip
uart:~$
uart:~$
uart:~$
uart:~$
uart:~$
uart:~$
uart:~$
uart:~$
uart:~$ assertion "handle->state != (uint8_t)kLPSPI_Idle" failed: file "WEST_TOPDIR/modules/hal/nxp/mcux/mcux-sdk/drivers/lpspi/fsl_lpspi.c", line 1566, function: LPSPI_MasterTransferHandleIRQ
abort()
[00:00:02.323,000] <err> os: r0/a1:  0x00000004  r1/a2:  0x80000ab0  r2/a3:  0x80000ab0
[00:00:02.323,000] <err> os: r3/a4:  0x800011b4 r12/ip:  0x0000ea60 r14/lr:  0x60008d31
[00:00:02.323,000] <err> os:  xpsr:  0x61000032
[00:00:02.323,000] <err> os: Faulting instruction address (r15/pc): 0x60008d3c
[00:00:02.323,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:02.323,000] <err> os: Fault during interrupt handling

[00:00:02.323,000] <err> os: Current thread: 0x80000ab0 (idle)
[00:00:02.370,000] <err> os: Halting system
```

**Expected behavior**
No spurious interrupt.

**Impact**
If thousands of `spi_transceive`s occurs every second at some point the spurious interrupt will run while a thread is in the middle of `spi_transceive` resulting in e.g. an absurdly high length which will result in the accessing an invalid address at some point:
```
[00:04:16.814,000] <err> spi_mcux_lpspi: Transfer could not start
[00:06:26.320,000] <err> spi_mcux_lpspi: Transfer could not start
[00:06:29.384,000] <err> spi_mcux_lpspi: Transfer could not start
[00:06:29.584,000] <err> spi_mcux_lpspi: Transfer could not start
[00:06:29.784,000] <err> spi_mcux_lpspi: Transfer could not start
[00:06:29.984,000] <err> spi_mcux_lpspi: Transfer could not start
[00:06:29.995,000] <err> os: ***** BUS FAULT *****
[00:06:29.995,000] <err> os:   Precise data bus error
[00:06:29.995,000] <err> os:   BFAR Address: 0x20280000
[00:06:29.995,000] <err> os: r0/a1:  0x20280000  r1/a2:  0x00000000  r2/a3:  0x00000000
[00:06:29.995,000] <err> os: r3/a4:  0x20280000 r12/ip:  0xaaaaaaaa r14/lr:  0x6005b76f
[00:06:29.995,000] <err> os:  xpsr:  0x81000032
[00:06:29.995,000] <err> os: Faulting instruction address (r15/pc): 0x6005b6ec
[00:06:29.995,000] <err> os: >>> ZEPHYR FATAL ERROR 25: Unknown error on CPU 0
[00:06:29.995,000] <err> os: Fault during interrupt handling
```

### PR DESCRIPTION
**Pull request by decsny**
Have to rework this driver completely to fix the CS because the SDK handle is based on the idea of a transfer being a single buffer, so we can't use the SDK transfer function

depends on:

- https://github.com/zephyrproject-rtos/zephyr/pull/82650
- https://github.com/zephyrproject-rtos/zephyr/pull/82806
- https://github.com/zephyrproject-rtos/zephyr/pull/82750
- https://github.com/zephyrproject-rtos/zephyr/pull/84406

Fixes #16544
Fixes #63280

### CODE REVIEW

**Comment by ofirshe** [comment]
Hi @decsny,

Thank you very much for your contribution on this front! I hope this issue will be resolved soon. I wanted to kindly ask if you’ve tested transferring and receiving with all possible combinations:
- When tx_len == rx_len
- When tx_len != rx_len
- When either tx_len or rx_len is zero.
As observed [here](https://github.com/zephyrproject-rtos/zephyr/discussions/81264#discussioncomment-11310063), the problem seems to occur when the sizes are equal in native GPIO CS mode, but it is expressed differently when the sizes are not equal.

Thanks again!

**Comment by decsny** [comment]
> Hi @decsny,
> 
> Thank you very much for your contribution on this front! I hope this issue will be resolved soon. I wanted to kindly ask if you’ve tested transferring and receiving with all possible combinations:
> 
>     * When tx_len == rx_len
> 
>     * When tx_len != rx_len
> 
>     * When either tx_len or rx_len is zero.
>       As observed [here](https://github.com/zephyrproject-rtos/zephyr/discussions/81264#discussioncomment-11310063), the problem seems to occur when the sizes are equal in native GPIO CS mode, but it is expressed differently when the sizes are not equal.
> 
> 
> Thanks again!

Those cases are covered by the zephyr test suite. If you have more cases you want tested then please add them to the zephyr tests, would be useful

**Comment by decsny** [comment]
The thing not covered by the zephyr test suite is the monitoring the chip select behavior, we might want to think about how to approach that

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c [hunk 1]
```diff
@@ -0,0 +1,378 @@
...
+	while (spi_context_rx_buf_on(ctx)) {
+		words_read = lpspi_rx_buf_write_words(dev, ctx->rx_len);
+		spi_context_update_rx(ctx, lpspi_data->word_size_bytes, words_read);
+	}
+
+	LOG_DBG("LPSPI transfer over");
+	spi_context_complete(ctx, dev, 0);
+}
+
+static inline uint8_t rx_fifo_cur_len(LPSPI_Type *base) {
```
Comment (bperseghetti) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:92]:
```suggestion
static inline uint8_t rx_fifo_cur_len(LPSPI_Type *base)
{
```

**Review by bperseghetti — COMMENTED** [review]
I think this is the only thing keeping it from passing the CI.

**Review by tbursztyka — DISMISSED** [review]

**Review by bperseghetti — DISMISSED** [review]

**Comment by decsny** [comment]
rebased to fix conflicts

**Review by bperseghetti — DISMISSED** [review]

**Comment by mmahadevan108** [comment]
@wearyzen, can you help look at the IRQ additions.

**Comment by mmahadevan108** [comment]
@tbursztyka @teburd , can you help look at the changes to the SPI code.

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c [hunk 2]
```diff
@@ -0,0 +1,362 @@
...
+		lpspi_handle_rx_irq(dev);
+	}
+
+	if (status_flags & kLPSPI_TxDataRequestFlag) {
+		lpspi_handle_tx_irq(dev);
+	}
+
+	if (!spi_context_tx_on(ctx) && lpspi_is_rx_done(dev)) {
+		spi_context_complete(ctx, dev, 0);
+		arch_irq_clear_pending(config->irqn);
```
Comment (wearyzen) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:240]: For consistency I think you should use irq_* macros as we have [here](https://github.com/zephyrproject-rtos/zephyr/blob/b80a058e9043087f2a114310df48eab4638598b6/include/zephyr/irq.h#L290) and use that here instead of calling arch_irq_*

Comment (wearyzen) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:240]: Sorry for not making that clear, what I meant if we are adding an arch_irq_* () apis then we should also add a new irq_clear_pending() macro in generic layer to be consistent with how arch_* apis are used.
Also, I see some other code in drivers using [NVIC_ClearPendingIRQ ](https://github.com/search?q=repo%3Azephyrproject-rtos%2Fzephyr%20NVIC_ClearPendingIRQ&type=code) and [NVIC_SetPendingIRQ ](https://github.com/search?q=repo%3Azephyrproject-rtos%2Fzephyr%20NVIC_SetPendingIRQ&type=code) so this is not the only use case.
You can chose to use the NVIC apis directly as others have used but if we add arch_irq_* apis then just defining these 3  seems incomplete. Ideally you would also need to define the arch_irq_* () to z_soc_irq_* () [here](https://github.com/zephyrproject-rtos/zephyr/pull/82877/files#diff-43e44cef4ccc0de92602731134c3013993fdae45d64a367dd80891185479f585R68) so things don't break when there is a custom interrupt controller defined with CONFIG_ARM_CUSTOM_INTERRUPT_CONTROLLER.

Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:240]: okay, in this case, I will just directly use those CMSIS functions without any zephyr wrapper, because I don't want to address the arch irq code really in this PR, thanks

**Comment by decsny** [comment]
updated to remove the commit touching the cortex m irq file, and use cmsis function directly instead, and rebased

**Review by bperseghetti — DISMISSED** [review]

**Comment by jeppenodgaard** [comment]
Looks like this PR also fixes https://github.com/zephyrproject-rtos/zephyr/issues/63280.

**Review by EmilioCBen — APPROVED** [review]

**Review by teburd — APPROVED** [review]
Looks fine to me. I wouldn't bother implementing the transcieve_async API though as its not actually async (can block at any time, not usable from any context). To support rtio natively with this driver doesn't seem that far off, it requires using a different context with different functions to get the next read/write/transcieve and inform when the task is complete slightly different.

**Review by mmahadevan108 — APPROVED** [review]
