### PR TITLE
Bluetooth: Audio: Fix and move assigned numbers

### LINKED ISSUE #43098: Move the capabilities and configuration defines out of lc3.h
**Describe the bug**
The Codec Capabilities and Configuration types defined in the Generic Audio assigned numbers are not LC3 codec specific. Move the common codec definitions out of lc3.h

### PR DESCRIPTION
**Pull request by Thalley**
Fix the definitions of the audio-related assigned numbers and remove them from lc3.h

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/43098

### CODE REVIEW

File: samples/bluetooth/broadcast_audio_sink/src/main.c [hunk 1]
```diff
@@ -108,8 +108,8 @@ static struct bt_conn *broadcast_assistant_conn;
 static struct bt_le_ext_adv *ext_adv;
 
 static const struct bt_audio_codec_cap codec_cap = BT_AUDIO_CODEC_CAP_LC3(
-	BT_AUDIO_CODEC_LC3_FREQ_16KHZ | BT_AUDIO_CODEC_LC3_FREQ_24KHZ,
-	BT_AUDIO_CODEC_LC3_DURATION_10, BT_AUDIO_CODEC_LC3_CHAN_COUNT_SUPPORT(1), 40u, 60u, 1u,
+	BT_AUDIO_CODEC_CAP_FREQ_16KHZ | BT_AUDIO_CODEC_CAP_FREQ_24KHZ,
```
Comment (kartben) [inline samples/bluetooth/broadcast_audio_sink/src/main.c:111]: looks like a breaking change or am I missing something? shouldn't the `...LC3...` option only be deprecated for now?
and would need entires in release notes / migration guide too

Comment (Thalley) [reply samples/bluetooth/broadcast_audio_sink/src/main.c:111]: @kartben My understanding is that for experimental APIs (like LE Audio), this is not necessary. 

Given how long time these macros have existed, it may make sense to put something in the migration guide, but AFAIK that's not something we've done before for experimental APIs. 

What do you think?

Comment (kartben) [reply samples/bluetooth/broadcast_audio_sink/src/main.c:111]: Ah, forgot that LE Audio was experimental, sorry. So yes, you're right, it's not strictly necessary. If you don't mind, and based on your comment re: how long they've been around, a short note in the migration guide would be welcome indeed. Thanks!

**Review by fredrikdanebjer — DISMISSED** [review]
Aside from the comment from kartben above, lgtm

File: doc/releases/migration-guide-3.6.rst [hunk 2]
```diff
@@ -450,6 +450,14 @@ Bluetooth
...
     :kconfig:option:`CONFIG_BT_MESH_SAR_RX_ACK_RETRANS_COUNT` Kconfig options.
 
+* Audio
+
+  * The BT_AUDIO_CODEC_LC3_* values from ``<zephyr/bluetooth/audio/lc3.h>`` have moved to
+    ``<zephyr/bluetooth/audio/audio.h>`` and have the ``LC3`` part of their names replaced by a
+    more semantically correct name: e.g.
+    ``BT_AUDIO_CODEC_LC3_CHAN_COUNT`` is now ``BT_AUDIO_CODEC_CAP_TYPE_CHAN_COUNT``,
+    ``BT_AUDIO_CODEC_LC3_FREQ`` is now ``BT_AUDIO_CODEC_CAP_TYPE_FREQ``, and
+    ``BT_AUDIO_CODEC_CONFIG_LC3_FREQ`` is now ``BT_AUDIO_CODEC_CFG_FREQ``, etc. (:github:`67024`)
```
Comment (fredrikdanebjer) [inline doc/releases/migration-guide-3.6.rst:460]: Some function and enum type names has also changed to used the more commonly used abbreviation of cfg and cap, e.g.:
bt_audio_codec_config_freq -> bt_audio_codec_cfg_freq
bt_audio_codec_capability_type -> bt_audio_codec_cap_type

Should you perhaps also mention this, as they also are part of public api?

Comment (Thalley) [reply doc/releases/migration-guide-3.6.rst]: Sure, I added some of the enums here as well (but far from all of them).

File: doc/releases/migration-guide-3.6.rst [hunk 3]
```diff
@@ -450,6 +450,18 @@ Bluetooth
     :kconfig:option:`CONFIG_BT_MESH_SAR_RX_DISCARD_TIMEOUT`,
     :kconfig:option:`CONFIG_BT_MESH_SAR_RX_ACK_RETRANS_COUNT` Kconfig options.
 
+* Audio
+
+  * The BT_AUDIO_CODEC_LC3_* values from ``<zephyr/bluetooth/audio/lc3.h>`` have moved to
```
Comment (kartben) [inline doc/releases/migration-guide-3.6.rst:455]: nit

```suggestion
  * The ``BT_AUDIO_CODEC_LC3_*`` values from ``<zephyr/bluetooth/audio/lc3.h>`` have moved to
```

**Review by kartben — COMMENTED** [review]
migration guide lgtm, thanks! don't know enough about the topic to give an actual +1 though :)

File: doc/releases/migration-guide-3.6.rst (hunk 3 above)
Comment (Thalley) [reply doc/releases/migration-guide-3.6.rst]: Wasn't sure about that one, since it's not an actual value, but I added your suggestion anyways :)

**Review by kruithofa — APPROVED** [review]

**Review by fredrikdanebjer — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
