### PR TITLE
tests pipe_api: Fix unitialized variable warning

### LINKED ISSUE #84250: Uninitialized variable build warning on tests/kernel/pipe/pipe_api
**Describe the bug**
gcc throws an unitialiazed variable build warning in tests/kernel/pipe/pipe_api (see long below)
when build with no optimizations

**To Reproduce**
1. twister -p nrf52_bsim -T tests/kernel/pipe/pipe_api

OR
1. cmake -GNinja -DBOARD=native_sim ../tests/kernel/pipe/pipe_api/ -DCONFIG_NO_OPTIMIZATIONS=y
2. ninja
3. See error

**Expected behavior**
No build warnings

**Impact**
Twister failures

**Logs and console output**
```
tests/kernel/pipe/pipe_api/src/concurrency.c:34:22: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
   34 |         zassert_true(k_pipe_write((struct k_pipe *)arg1, garbage, sizeof(garbage),
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   35 |                 K_MSEC(partial_wait_time)) == sizeof(garbage), "Failed to write to pipe");
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
subsys/testsuite/ztest/include/zephyr/ztest_assert.h:180:35: note: in definition of macro ‘_zassert_base’
  180 |                         z_zassert(cond, _msg ? ("(" default_msg ")") : (default_msg), __FILE__,    \
      |                                   ^~~~
subsys/testsuite/ztest/include/zephyr/ztest_assert.h:194:9: note: in expansion of macro ‘_zassert_va’
  194 |         _zassert_va(cond, default_msg, COND_CODE_1(__VA_OPT__(1), (__VA_ARGS__), (NULL)))
      |         ^~~~~~~~~~~
subsys/testsuite/ztest/include/zephyr/ztest_assert.h:275:33: note: in expansion of macro ‘zassert’
  275 | #define zassert_true(cond, ...) zassert(cond, #cond " is false", ##__VA_ARGS__)
      |                                 ^~~~~~~
tests/kernel/pipe/pipe_api/src/concurrency.c:34:9: note: in expansion of macro ‘zassert_true’
   34 |         zassert_true(k_pipe_write((struct k_pipe *)arg1, garbage, sizeof(garbage),
      |         ^~~~~~~~~~~~
In file included from include/zephyr/kernel.h:6443,
                 from tests/kernel/pipe/pipe_api/src/concurrency.c:7:
zephyr/include/generated/zephyr/syscalls/kernel.h:1467:19: note: by argument 2 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} to ‘k_pipe_write’ declared here
 1467 | static inline int k_pipe_write(struct k_pipe * pipe, const uint8_t * data, size_t len, k_timeout_t timeout)
      |                   ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Environment (please complete the following information):**

 - OS: Ubuntu Linux 24.04
 - Toolchain (e.g Zephyr SDK, ...): Host gcc 14.02
 - Commit SHA or Version used: Main as of now a238e5c29d7fcef8a4ea8b4a230dd1976096c3da

**Additional context**

### PR DESCRIPTION
**Pull request by aescolar**
Fix so the compiler does not throw a warning thinking that those buffers may be used unitialized inside k_pipe_write/read().

The issue was discovered with with gcc 14.2

Fixes #84250

### CODE REVIEW

**Comment by npitre** [comment]
I understand why the compiler may warn in the write case. But why the need
to pre-initialize the buffer in the read case?

**Review by henrikbrixandersen — APPROVED** [review]

**Review by npitre — APPROVED** [review]

File: tests/kernel/pipe/pipe_api/src/concurrency.c [hunk 1]
```diff
@@ -29,15 +29,15 @@ static void thread_reset(void *arg1, void *arg2, void *arg3)
 
 static void thread_write(void *arg1, void *arg2, void *arg3)
 {
-	uint8_t garbage[dummy_data_size];
+	uint8_t garbage[DUMMY_DATA_SIZE] = {};
```
Comment (andyross) [inline tests/kernel/pipe/pipe_api/src/concurrency.c:32]: FWIW this line changes semantics: it used to be garbage, now it's zero-filled.

Comment (aescolar) [reply tests/kernel/pipe/pipe_api/src/concurrency.c:32]: ok, but does that matter in this case?

Comment (andyross) [reply tests/kernel/pipe/pipe_api/src/concurrency.c:32]: Probably not?  But in a patch to fix a warning it's generally best practice to change nothing else.
