### PR TITLE
kernel: Fix pipe ISR instability issues (#52812)

### LINKED ISSUE #52812: Various problems with pipes (Not unblocking, Data Access Violation, unblocking wrong thread...)
**Describe the bug**
I'm trying to use a pipe object to send data from a UART IRQ (async) to a thread. Since f86027f this should be possible, but there is some weird behaviour. It could be multiple bugs, but I suspect that these are related, so I'm combining them here. Here is a short description of the bugs (details below):
1. `k_pipe_get(..., K_FOREVER)` does not unlock if data is written after the read call is blocking. I worked around this issue by polling `k_pipe_get` with a small timeout. Code to reproduce this error is added below.
2. Sporadic Data Access Violation because of NULL-Pointer in `dest_list` in `z_impl_k_pipe_put()`, if `k_pipe_put()` is called from IRQ. It seems that the list is ok after being filled in `pipe_waiter_list_populate()`, but by the time `pipe_write()` is called the list isn't valid anymore. This can be caught by checking `prev` and `next` in `sys_dlist_remove()`. Code to reproduce this error is added below.
3. Unused pipes that wait for data sometimes unlock with "return value==0" and "bytes_read==buffer_size" although no data was received. I was not able to produce a minimal working example for this error or narrow this down. But this happens with completly unrelated pipes, so I suspect, that the `waiter_list` from the previous point leads to this problem and unblocks a wrong thread.

The code to reproduce these issues can be seen below. I could only really narrow down the second error. Here the stack trace and log output for the second error.

```
k_sys_fatal_error_handler(unsigned int reason, const z_arch_esf_t * esf) (c:\ncs\v2.2.0-rc1\zephyr\kernel\fatal.c:41)
z_fatal_error(unsigned int reason, const z_arch_esf_t * esf) (c:\ncs\v2.2.0-rc1\zephyr\kernel\fatal.c:131)
z_arm_fatal_error(unsigned int reason, const z_arch_esf_t * esf) (c:\ncs\v2.2.0-rc1\zephyr\arch\arm\core\aarch32\fatal.c:63)
z_arm_fault(uint32_t msp, uint32_t psp, uint32_t exc_return, _callee_saved_t * callee_regs) (c:\ncs\v2.2.0-rc1\zephyr\arch\arm\core\aarch32\cortex_m\fault.c:1097)
z_arm_usage_fault() (c:\ncs\v2.2.0-rc1\zephyr\arch\arm\core\aarch32\cortex_m\fault_s.S:102)
<signal handler called> (Unbekannte Quelle:0)
sys_dlist_remove(sys_dnode_t * node) (c:\ncs\v2.2.0-rc1\zephyr\include\zephyr\sys\dlist.h:501)
sys_dlist_get(sys_dlist_t * list) (c:\ncs\v2.2.0-rc1\zephyr\include\zephyr\sys\dlist.h:522)
pipe_write(struct k_pipe * pipe, sys_dlist_t * src_list, sys_dlist_t * dest_list, _Bool * reschedule) (c:\ncs\v2.2.0-rc1\zephyr\kernel\pipes.c:307)
z_impl_k_pipe_put(struct k_pipe * pipe, void * data, size_t bytes_to_write, size_t * bytes_written, size_t min_xfer, k_timeout_t timeout) (c:\ncs\v2.2.0-rc1\zephyr\kernel\pipes.c:420)
k_pipe_put(size_t min_xfer, size_t * bytes_written, size_t bytes_to_write, void * data, struct k_pipe * pipe) (c:\ncs\projects\eblem\build_eblem\zephyr\include\generated\syscalls\kernel.h:1284)
test_write(const char * str) (c:\ncs\projects\eblem\src\main.c:213)
test_write_irq() (c:\ncs\projects\eblem\src\main.c:237)
uart_cb(const struct device * dev, struct uart_event * evt, void * user_data) (c:\ncs\projects\eblem\src\uart\ngp_uart.c:27)
user_callback(const struct device * dev, struct uart_event * evt) (c:\ncs\v2.2.0-rc1\zephyr\drivers\serial\uart_nrfx_uarte.c:849)
notify_uart_rx_rdy(const struct device * dev, size_t len) (c:\ncs\v2.2.0-rc1\zephyr\drivers\serial\uart_nrfx_uarte.c:863)
rx_timeout(struct k_timer * timer) (c:\ncs\v2.2.0-rc1\zephyr\drivers\serial\uart_nrfx_uarte.c:1102)
z_timer_expiration_handler(struct _timeout * t) (c:\ncs\v2.2.0-rc1\zephyr\kernel\timer.c:63)
sys_clock_announce(int32_t ticks) (c:\ncs\v2.2.0-rc1\zephyr\kernel\timeout.c:270)
sys_clock_timeout_handler(int32_t chan, uint64_t expire_time, void * user_data) (c:\ncs\v2.2.0-rc1\zephyr\drivers\timer\nrf_rtc_timer.c:422)
process_channel(int32_t chan) (c:\ncs\v2.2.0-rc1\zephyr\drivers\timer\nrf_rtc_timer.c:494)
rtc_nrf_isr(const void * arg) (c:\ncs\v2.2.0-rc1\zephyr\drivers\timer\nrf_rtc_timer.c:518)
_isr_wrapper() (c:\ncs\v2.2.0-rc1\zephyr\arch\arm\core\aarch32\isr_wrapper.S:259)
<signal handler called> (Unbekannte Quelle:0)
arch_swap(unsigned int key) (c:\ncs\v2.2.0-rc1\zephyr\arch\arm\core\aarch32\swap.c:53)
z_swap_irqlock(unsigned int key) (c:\ncs\v2.2.0-rc1\zephyr\kernel\include\kswap.h:185)
z_swap(struct k_spinlock * lock) (c:\ncs\v2.2.0-rc1\zephyr\kernel\include\kswap.h:196)
z_pend_curr(struct k_spinlock * lock, k_spinlock_key_t key, _wait_q_t * wait_q, k_timeout_t timeout) (c:\ncs\v2.2.0-rc1\zephyr\kernel\sched.c:859)
z_sched_wait(struct k_spinlock * lock, k_spinlock_key_t key, _wait_q_t * wait_q, k_timeout_t timeout, void ** data) (c:\ncs\v2.2.0-rc1\zephyr\kernel\sched.c:1912)
pipe_get_internal(k_spinlock_key_t key, struct k_pipe * pipe, void * data, size_t bytes_to_read, size_t * bytes_read, size_t min_xfer, k_timeout_t timeout) (c:\ncs\v2.2.0-rc1\zephyr\kernel\pipes.c:635)
z_impl_k_pipe_get(struct k_pipe * pipe, void * data, size_t bytes_to_read, size_t * bytes_read, size_t min_xfer, k_timeout_t timeout) (c:\ncs\v2.2.0-rc1\zephyr\kernel\pipes.c:668)
k_pipe_get(size_t min_xfer, size_t * bytes_read, size_t bytes_to_read, void * data, struct k_pipe * pipe) (c:\ncs\projects\eblem\build_eblem\zephyr\include\generated\syscalls\kernel.h:1309)
test_read(char * data, size_t len) (c:\ncs\projects\eblem\src\main.c:226)
test_thread_entry(void * x, void * y, void * z) (c:\ncs\projects\eblem\src\main.c:245)
z_thread_entry(k_thread_entry_t entry, void * p1, void * p2, void * p3) (c:\ncs\v2.2.0-rc1\zephyr\lib\os\thread_entry.c:36)
z_thread_entry(k_thread_entry_t entry, void * p1, void * p2, void * p3) (c:\ncs\v2.2.0-rc1\zephyr\lib\os\thread_entry.c:36)
[Unknown code] (Unbekannte Quelle:0)
```

```
*** Booting Zephyr OS build v3.2.99-ncs1-rc1 ***
[00:00:05.693,939] <inf> main: test_write: test_write("Hello World")
[00:00:05.694,305] <inf> main: test_read:   Read OK (11 bytes, "Hello World")
[00:00:11.715,454] <inf> main: test_write: test_write("Hello World")
[00:00:11.715,606] <inf> main: test_read:   Read OK (11 bytes, "Hello World")
[00:00:11.715,667] <inf> main: test_write: test_write("Hello World")
[00:00:11.715,850] <inf> main: test_write: test_write("Hello World")
[00:00:11.715,911] <inf> main: test_read:   Read OK (11 bytes, "Hello World")
[00:00:11.716,094] <inf> main: test_read:   Read OK (11 bytes, "Hello World")
....
[00:00:56.939,178] <err> os: mem_manage_fault: ***** MPU FAULT *****
[00:00:56.939,208] <err> os: mem_manage_fault:   Data Access Violation
[00:00:56.939,208] <err> os: mem_manage_fault:   MMFAR Address: 0x0
[00:00:56.939,239] <err> os: esf_dump: r0/a1:  0x20000bf8  r1/a2:  0x20010208  r2/a3:  0x00000000
[00:00:56.939,239] <err> os: esf_dump: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x0003be4f
[00:00:56.939,270] <err> os: esf_dump:  xpsr:  0x21000021
[00:00:56.939,300] <err> os: esf_dump: Faulting instruction address (r15/pc): 0x0004673a
[00:00:56.939,331] <err> os: z_fatal_error: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:56.939,331] <err> os: z_fatal_error: Fault during interrupt handling
[00:00:56.939,392] <err> os: z_fatal_error: Current thread: 0x20001f98 (test_thread_tid)
[00:01:01.753,631] <err> os: k_sys_fatal_error_handler: Halting system
```

The second error can be caught early if following code is added to `sys_dlist_remove`:

```C
__ASSERT(prev, "prev is null");
__ASSERT(next, "next is null");
```

The second error can also be worked around if I remove the call to `pipe_waiter_list_populate()` in `z_impl_k_pipe_put()`. But I'm pretty sure that this messes with the wakeup of other threads. But it shows, that there is some problem with the waiter_list.

**To Reproduce**
Following code reproduces error 1 (k_pipe_get does not unblock). It's just one write thread and one read thread, while the order of read/write is mixed. There are two variants in `test_read()`. The first is the expected solution that does not work (read does not unblock and thread 2 never ends) and the second variant is my workaround that works but is definitely not great. The log output of both variants is included as a comment.

```C
static void test_thread1_entry(void * x, void * y, void * z);
static void test_thread2_entry(void * x, void * y, void * z);
K_THREAD_DEFINE(test_thread1_tid, 512, test_thread1_entry, NULL, NULL, NULL, 5, 0, 0);
K_THREAD_DEFINE(test_thread2_tid, 512, test_thread2_entry, NULL, NULL, NULL, 5, 0, 0);
K_PIPE_DEFINE(test_pipe, 256, 4);

static void test_write(const char * str) {
   LOG_INF("test_write(\"%s\")", str);

   size_t bytes_written;
   int err = k_pipe_put(&test_pipe, (void *) str, strlen(str), &bytes_written, 1, K_NO_WAIT);
   if (err || (strlen(str) != bytes_written)){
      LOG_WRN("  test_write failed (%d, %d)", err, (int) bytes_written);
   } else {
      LOG_INF("  Write OK");
   }
}

static void test_read(char * data, size_t len) {
   LOG_INF("test_read()");

   size_t bytes_read;
   int err;

   /* Variant 1: Expected behaviour (does not unlock) */
   // [00:00:04.264,099] <inf> main: test_write: test_write("Hello World")
   // [00:00:04.264,129] <inf> main: test_write:   Write OK
   // [00:00:05.264,373] <inf> main: test_read: test_read()
   // [00:00:05.264,434] <inf> main: test_read:   Read OK (11 bytes, "Hello World")
   // [00:00:06.264,617] <inf> main: test_read: test_read()
   // [00:00:07.264,831] <inf> main: test_write: test_write("asdasdf")
   // [00:00:07.264,862] <inf> main: test_write:   Write OK
   // [00:00:08.264,984] <inf> main: test_thread1_entry: Thread 1 done...
   err = k_pipe_get(&test_pipe, data, len, &bytes_read, 1, K_FOREVER);
   if (err) {
      LOG_WRN("  test_read failed (%d, %d)", err, (int) bytes_read);
   } else {
      LOG_INF("  Read OK (%d bytes, \"%s\")", (int) bytes_read, data);
   }

   /* Variant 2: Workaround using polling */
   // [00:00:02.977,935] <inf> main: test_write: test_write("Hello World")
   // [00:00:02.977,966] <inf> main: test_write:   Write OK
   // [00:00:03.978,179] <inf> main: test_read: test_read()
   // [00:00:03.978,240] <inf> main: test_read:   Read OK (11 bytes, "Hello World")
   // [00:00:04.978,393] <inf> main: test_read: test_read()
   // [00:00:05.178,527] <wrn> main: test_read:   test_read failed (-11)
   // [00:00:05.378,692] <wrn> main: test_read:   test_read failed (-11)
   // [00:00:05.578,796] <wrn> main: test_read:   test_read failed (-11)
   // [00:00:05.778,900] <wrn> main: test_read:   test_read failed (-11)
   // [00:00:05.978,576] <inf> main: test_write: test_write("asdasdf")
   // [00:00:05.978,607] <inf> main: test_write:   Write OK
   // [00:00:05.979,003] <inf> main: test_read:   Read OK (7 bytes, "asdasdf")
   // [00:00:06.978,759] <inf> main: test_thread1_entry: Thread 1 done...
   // [00:00:07.979,278] <inf> main: test_thread2_entry: Thread 2 done...
   // do {
   //    bytes_read = 0;
   //    err = k_pipe_get(&test_pipe, data, len, &bytes_read, 1, K_MSEC(200));
   //    if (err != 0) {
   //       LOG_WRN("  test_read failed (%d)", (int) err);
   //    }
   // } while (err != 0);
   // LOG_INF("  Read OK (%d bytes, \"%s\")", (int) bytes_read, data);
}

static void test_thread1_entry(void * x, void * y, void * z) {
   /* First Write, then read -> OK */
   test_write("Hello World");
   k_sleep(K_MSEC(1000));
   k_sleep(K_MSEC(1000));

   /* First Read, then write -> Fail */
   k_sleep(K_MSEC(1000));
   test_write("asdasdf");
   k_sleep(K_MSEC(1000));

   LOG_INF("Thread 1 done...");
   while (1) {k_sleep(K_MSEC(1000));}
}

static void test_thread2_entry(void * x, void * y, void * z) {
   char data[100];

   /* First Write, then read -> OK */
   memset(data, 0, sizeof(data));
   k_sleep(K_MSEC(1000));
   test_read(data, sizeof(data));
   k_sleep(K_MSEC(1000));

   /* First Read, then write -> Fail */
   memset(data, 0, sizeof(data));
   test_read(data, sizeof(data));
   k_sleep(K_MSEC(1000));
   k_sleep(K_MSEC(1000));

   LOG_INF("Thread 2 done...");
   while (1) {k_sleep(K_MSEC(1000));}
}
```

The second bug can be reproduced with following code. The function `test_write_irq()` has to be called periodically from an IRQ. In my case I use an UART IRQ that calls this function on incoming data. But I guess that this should also fail when using another IRQ.

```C
static void test_thread_entry(void * x, void * y, void * z);
K_THREAD_DEFINE(test_thread_tid, 1024, test_thread_entry, NULL, NULL, NULL, 5, 0, 0);
K_PIPE_DEFINE(test_pipe, 256, 4);

static void test_write(const char * str) {
   LOG_INF("test_write(\"%s\")", str);

   size_t bytes_written;
   int err = k_pipe_put(&test_pipe, (void *) str, strlen(str), &bytes_written, 1, K_NO_WAIT);
   if (err || (strlen(str) != bytes_written)) {
      LOG_WRN("  test_write failed (%d, %d)", err, (int) bytes_written);
   }
}

static void test_read(char * data, size_t len) {
   int err;
   size_t bytes_read;

   do {
      bytes_read = 0;
      err = k_pipe_get(&test_pipe, data, len, &bytes_read, 1, K_MSEC(1));
      if ((err != 0) && (err != -EAGAIN)) {
         LOG_WRN("  test_read failed (%d)", (int) err);
      }
   } while (err != 0);
   LOG_INF("  Read OK (%d bytes, \"%s\")", (int) bytes_read, data);
}

/* Function has to be called periodically from IRQ */
void test_write_irq(void) {
   test_write("Hello World");
}

static void test_thread_entry(void * x, void * y, void * z) {
   char data[100];
   while (1) {
      memset(data, 0, sizeof(data));
      test_read(data, sizeof(data));
   }
}
```

**Expected behavior**
I expect the pipe objects to work according to the documentation and not affect unrelated kernel objects.

**Impact**
With these bugs there is basically no way to use pipes to asynchronously wait for data or use them from IRQs. I could use other kernel objects (e.g. FIFO), but I like the copying of the pipe, to make memory management easier.

**Logs and console output**
Logs are included in the top sections.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: Nordic nRF Connect SDK v2.2.0-rc1 (Based on Zephyr cd16a83; Release candidate used because it includes f86027f)
 - MCU: nRF52840

**Additional context**
None

### PR DESCRIPTION
**Pull request by peter-mitsis**
Fixes #52812 (well, most of it)

This series of commits is an attempt to fix the pipe instability issues raised in issue #52812 (the second and third issues). The issues that I have been able identify related to those boil down to improperly protecting the wait queue from within the pipe routines.

When the working list of pended threads (to read from or write to) is generated, sched_spinlock must be taken to protect the wait queue. Otherwise, an in-opportune timeout can lead to problems.

As there is a gap in time between when that list is generated and when data is copied to/from the previously identified waiting thread, that thread can time out. There are two things that need to be done to avoid problems stemming from this.
    1. Waking the thread must be done safely. That is, it must be explicitly specified and a run-time check to determine if it is still pended must be done before unpending it.
    2. A barrier must be inserted after the thread has been safely unpended so that it spins waiting for the pipe lock, which it can get after the put/get operation that was supposed to wake it finishes. I specify "supposed to" because it could have technically timed out while data was being copied, but since it made it to the "working list" before timing out, I am arguing that it is not really a timeout, but a special processing case.

This set of commits does not address the first of the three issues identified in #52812.

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Comment by stephanosio** [comment]
@andyross Could you take a quick look?

**Review by nashif — DISMISSED** [review]

File: kernel/pipes.c [hunk 1]
```diff
@@ -457,6 +484,16 @@ int z_impl_k_pipe_put(struct k_pipe *pipe, void *data, size_t bytes_to_write,
...
 	z_sched_wait(&pipe->lock, key, &pipe->wait_q.writers, timeout, NULL);
 
+	/*
+	 * On SMP systems, threads in the processing list may timeout before
+	 * the data has finished copying. The following spin lock/unlock pair
+	 * prevents those threads from executing further until the data copying
+	 * is complete.
+	 */
+
+	key = k_spin_lock(&pipe->lock);
```
Comment (teburd) [inline kernel/pipes.c:494]: Seems like this is being used to spin and wait for a completion flag effectively, spin locks have some implied irq mask/unmask operations tied to them, do you need that behavior as well or only an atomic cas loop? The comment above doesn't help in terms of the arch irq locking behavior being desired/undesired.

Comment (peter-mitsis) [reply kernel/pipes.c:494]: I'm not the happiest with using the spin lock here, but it seemed to be the simplest mechanism to accomplish the following two goals.

 1.  Serve as an indicator that it is safe to continue execution.
 2. Prevent the thread from executing while another core was still in the process of copying the data that the thread had requested.

The biggest downside to this approach that I can see is (and admittedly you may see something more) that the one core is essentially stalled while the other core finishes copying data. However, as an attempt to put this into perspective, I pose the following question ... "Is blocking on the spin lock on the 'tail end' of the pipe operation fundamentally any worse than blocking on a spin lock at the 'front end' of the pipe operation?"

**Comment by fabiobaltieri** [comment]
@andyross any chance you could review this one?

**Review by dcpleung — DISMISSED** [review]

File: kernel/sched.c [hunk 2]
```diff
@@ -788,7 +788,9 @@ static inline void unpend_thread_no_timeout(struct k_thread *thread)
 ALWAYS_INLINE void z_unpend_thread_no_timeout(struct k_thread *thread)
 {
 	LOCKED(&sched_spinlock) {
-		unpend_thread_no_timeout(thread);
+		if (thread->base.pended_on != NULL) {
```
Comment (andyross) [inline kernel/sched.c:791]: Not understanding the logic change here.  The current (not terribly informative) naming scheme is that z_xxxx() scheduler APIs are (or at least tend to be) synchronized calls and the internal static functions have no prefix and (usually) are expected to be externally synchronized.

And that's true here, where this used to be just a wrapper around the internal function.  But now it's got different behavior, which seems likely to be confusing.

What's the circumstances where you are now able to land here to unpend a thread that isn't actually pended?  That seems like a state management problem somewhere else?

File: kernel/pipes.c [hunk 3]
```diff
@@ -478,6 +478,16 @@ int z_impl_k_pipe_put(struct k_pipe *pipe, void *data, size_t bytes_to_write,
 
 	z_sched_wait(&pipe->lock, key, &pipe->wait_q.writers, timeout, NULL);
 
+	/*
+	 * On SMP systems, threads in the processing list may timeout before
+	 * the data has finished copying. The following spin lock/unlock pair
+	 * prevents those threads from executing further until the data copying
+	 * is complete.
```
Comment (andyross) [inline kernel/pipes.c:491]: I'm not quite understanding how this acts as a barrier?  I'm guessing the thinking is something like "if another CPU already holds the lock, this forces us to wait until it releases it".  But that doesn't protect against the case where it gets the lock immediately after.

Basically this doesn't feel like a fix to me.  What's the exact sequencing we're trying to protect?  My guess is something needs to be inside a lock that isn't.

**Review by andyross — COMMENTED** [review]
Most of the comments are nitpicks (though I will say that barrier change seems unlikely to fix anything except statistically), but I'm having a hard time with the use of the scheduler lock for that iterator callback.  On a single CPU, it's just a big spinlock and sort of unavoidable I guess. 
 But on SMP, the sched lock will block every other CPU in the system out of hte scheduler, so e.g. interrupt returns won't happen until it's released, context switches won't progress, no one will be able to exit a k_sleep() call, etc...  That's a **lot** of downstream latency.

That just seems like we're going to have to fix it later.  We'll end up with a bug along the lines of "using pipes causes interrupt latency to skyrocket".

There's already a per-pipe spinlock, right?  Can't you just hold that as an outer lock (maybe a mutex, if possible -- not sure if you need to lock against ISRs or not) around the iteration instead, such that any operation that tries to pend/unpend a thread on that pipe has to hold the pipe's lock first?  Then you can limit the latency effects to just the local pipe object (and the local CPU if it's a spinlock).

File: kernel/sched.c [hunk 4]
```diff
@@ -1913,3 +1913,28 @@ int z_sched_wait(struct k_spinlock *lock, k_spinlock_key_t key,
...
 	return ret;
 }
+
+int z_sched_waitq_walk(_wait_q_t  *wait_q,
+		       int (*func)(struct k_thread *, void *), void *data)
+{
+	struct k_thread *thread;
+	int  status = 0;
+
+	LOCKED(&sched_spinlock) {
```
[the remark this answers is not in the document]
Comment (peter-mitsis) [reply kernel/sched.c:1925]: I see where your concerns are coming from. Walking the wait queue is a functionality to which we do not want to provide too much exposure as it has the potential to be misused. That's one of the reasons why I stuck the prototype in kerenl/include/sched.h--it should imply that it is a restricted operation, and should be used with care. If you like, I can add warnings to the description to make the risks more clear to potential callers (of whom there should be few).

File: kernel/sched.c (hunk 2 above)
Comment (peter-mitsis) [reply kernel/sched.c:791]: Excellent question--and it is for an SMP case that I did not originally spot when I first re-did the pipes implementation.

Pipe operations essentially act in two stages. In stage one, we create a list of the copying work that needs to be done. In stage two, we perform the copy and unpend an item if necessary once the copying is complete. However, unless I am misunderstanding something, there exists a window of opportunity where a timeout can be processed on another core after the work list has been generated that can cause it to be removed from the wait/pend queue. The pipe's spin-lock does not protect against this.

File: kernel/pipes.c (hunk 3 above)
Comment (peter-mitsis) [reply kernel/pipes.c:491]: Below is the sequence of events.

1. Thread A is in the process of copying a bunch of data for pipe P on core 1.
2. Meanwhile core 2 unpends thread B that was previously waiting on pipe P.
3. Core 2 schedules thread B to run, while thread A is still copying data on core 1.

Both threads A and B then want to simultaneously access thread B's pipe descriptor--A to update it, B to read it. Worse, thread B might execute, block on pipe Q and then thread A starts updating B's pipe descriptor mistakenly thinking that it is safe to do so, when in fact it is now being used by a different pipe altogether.

What we need to do is stop thread B from executing further until the thread A has finished the pipe operation, and the spin lock is the simplest and most effective method I can think of to do it.

**Review by andyross — APPROVED** [review]
I guess there's no reason to hold this up, as it's fixing real bugs and the concerns are mostly with performance in a somewhat-seldom-used IPC mechanism.  I do worry that latency-sensitive apps are going to end up bitten by this though, and suspect there are probably better ways to do this that don't involve synchronized wait queue enumerations.

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by nashif** [comment]
@laurenmurphyx64  @stephanosio  please merge before next RC

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
> tests/kernel/mem_protect/syscalls/kernel.memory_protection.syscalls (qemu_arc_em:tests/kernel/mem_protect/syscalls/kernel.memory_protection.syscalls) failed

The above failure is a known issue and has been addressed in https://github.com/zephyrproject-rtos/zephyr/pull/54721.

Merging with a failure.
