### PR TITLE
userspace: address some memory domain issues

### LINKED ISSUE #21991: memory domain locking may not be entirely correct
**Describe the bug**
The memory domain APIs have a global spinlock in kernel/mem_domain.c to serialize access to memory domain data structures. However, the memory domain structures may also be accessed from within the arch code, without holding these locks.

For example, on x86, arch_user_mode_enter() examines the thread's current memory domain object and updates page tables based on its contents, without any lock held. It's possible that the thread's memory domain may be simultaneously manipulated by another thread.

On ARM, which is uniprocessor-only, the memory domain is accessed in the context switch code to reprogram the MPU. This happens with IRQs locked, so I think we are safe for now (at least until we have some sort of ARM SMP support).

We need the locking to protect:
1. The struct k_mem_domain itself
2. For any thread that is a member of the memory domain, its assignment and membership dlist.

A semaphore may suffice, a spinlock may not be required. I don't think we have use-cases for memory domain APIs being called from ISRs. I think it would be good to have the locking be on a per-domain basis instead of global.

**To Reproduce**
Found via code inspection.

**Impact**
It's possible that the thread could obtain an undefined memory domain configuration. Depending on what the arch code does with the data structures, this might also crash.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
The PR fixes some issues:

- When threads exit, they were not being removed from the list of threads in the memory domain they belonged to. This wasn't causing major issues yet, but will when we need to adjust shared page tables on thread exit.
- The spinlock for memory domains is no longer static and the x86 code was adjusted to hold it when a thread drops to user mode and needs to update its page tables
- `k_mem_domain_destroy()` no longer leaves threads without a memory domain assignment

Also:
- Remove an unnecessary NULL check in the x86 code
- Add a test to ensure the main and static threads properly get assigned to the default memory domain at boot

Fixes: #21991

### CODE REVIEW

**Review by ceolin — APPROVED** [review]

File: kernel/mem_domain.c [hunk 1]
```diff
@@ -259,7 +248,45 @@ void k_mem_domain_add_thread(struct k_mem_domain *domain, k_tid_t thread)
...
+void z_mem_domain_exit_thread(struct k_thread *thread)
+{
+	k_spinlock_key_t key = k_spin_lock(&lock);
+	remove_thread_locked(thread);
+	k_spin_unlock(&lock, key);
+}
+
+void k_mem_domain_add_thread(struct k_mem_domain *domain, k_tid_t thread)
+{
+	k_spinlock_key_t key;
```
Comment (jenmwms) [inline kernel/mem_domain.c:261]: nit: the preceding key initializations were combined into a single line statement

**Review by dcpleung — APPROVED** [review]

File: include/app_memory/mem_domain.h [hunk 2]
```diff
@@ -127,7 +127,12 @@ extern void k_mem_domain_init(struct k_mem_domain *domain, uint8_t num_parts,
 /**
  * @brief Destroy a memory domain.
  *
- * Destroy a memory domain.
+ * Destroy a memory domain. All member threads will be re-assigned to the
+ * default memory domain.
+ *
+ * The default memory domain may not be destroyed.
```
Comment (jenmwms) [inline include/app_memory/mem_domain.h:133]: Is this saying that the default memory domain cannot be destroyed (with this function), like it is not permissible? Since the members are re-assigned to the default, it would not make sense to destroy itself. sorry, my brain tried to also read it as a potential to not be destroyed

File: include/app_memory/mem_domain.h [hunk 3]
```diff
@@ -127,7 +127,12 @@ extern void k_mem_domain_init(struct k_mem_domain *domain, uint8_t num_parts,
...
+ *
+ * This API is deprecated and will be removed in Zephyr 2.5.
  *
```
Comment (jenmwms) [inline include/app_memory/mem_domain.h:136]: Do we wait until then to add the @deprecate tag? I found it helpful.

File: include/app_memory/mem_domain.h (hunk 2 above)
Comment (jenmwms) [reply include/app_memory/mem_domain.h:133]: ah there it is! "cannot destroy default domain" (line 281)

**Review by jenmwms — APPROVED** [review]

**Review by ruuddw — APPROVED** [review]
