### PR TITLE
i2c: stm32: add missing DMA configuration fields

### LINKED ISSUE #87516: STM32 I2C DMA Incorrect DMA config
**Describe the bug**

Testing communication on I2C4 on a STM32H747i-Discovery board with DMA turned on
results in an error message:
```
[00:00:43.223,000] <err> dma_stm32_bdma: source and dest unit size error, 0  
[00:00:43.223,000] <err> dmamux_stm32: cannot configure the dmamux.  
[00:00:43.223,000] <err> i2c_ll_stm32_v2: Problem setting up DMA: -22  
[00:00:43.223,000] <err> i2c_ll_stm32_v2: Problem setting up TX DMA   
```
Seems like the 'source_data_size' is not setup in configure_dma() in  I2C driver
introduced in https://github.com/zephyrproject-rtos/zephyr/pull/81814

**To Reproduce**

Use configuration:
```
CONFIG_I2C_STM32_V2_DMA=y
CONFIG_DMA_STM32_BDMA=y
```
And device tree overlay
```
&i2c4 {
	dmas = <&dmamux2 0 14 (STM32_DMA_PERIPH_TX | STM32_DMA_PRIORITY_HIGH)
		&dmamux2 1 13 (STM32_DMA_PERIPH_RX | STM32_DMA_PRIORITY_HIGH)>;
		dma-names = "tx", "rx";
};
&bdma1 {
	status = "okay";
};
&dma2 {
	status = "okay";
};
&dmamux2 {
	status = "okay";
};
```
Test communication on I2C4 (Touch controller on STM32H747i-Discovery)
**Expected behavior**

No error message and communication working
**Impact**

None
**Logs and console output**

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) Ubuntu 22
 - Toolchain (e.g Zephyr SDK, ...) NA
 - Commit SHA or Version used 56f7dc4c2ea3390ef8efeed295334afc62ebbea9
**Additional context**

### PR DESCRIPTION
**Pull request by sgilbert182**
Add missing fields for DMA tx and rx configuration macros

fix #87516

Tested on stm32h735-Discovery and STM32H747i-Discovery board

### CODE REVIEW

**Review by jonas-5ae29c — CHANGES_REQUESTED** [review]

File: drivers/i2c/i2c_ll_stm32.c [hunk 1]
```diff
@@ -587,15 +587,56 @@ static void i2c_stm32_irq_config_func_##index(const struct device *dev)	\
...
+
+	if (status != 0) {
+		LOG_ERR("DMA error %d", status);
+	}
+}
+
+void i2c_stm32_dma_rx_cb(const struct device *dma_dev, void *user_data,
+	uint32_t channel, int status)
+{
+	struct i2c_stm32_data *data = user_data;
```
Comment (erian747) [inline drivers/i2c/i2c_ll_stm32.c:611]: Compiler warning about unused variable

File: drivers/i2c/i2c_ll_stm32.c [hunk 2]
```diff
@@ -587,15 +587,56 @@ static void i2c_stm32_irq_config_func_##index(const struct device *dev)	\
...
+		.dev_dma = COND_CODE_1(DT_INST_DMAS_HAS_NAME(index, dir),\
+				(DEVICE_DT_GET(STM32_DMA_CTLR(index, dir))), (NULL)),\
+		.dma_channel = COND_CODE_1(DT_INST_DMAS_HAS_NAME(index, dir),\
+				(DT_INST_DMAS_CELL_BY_NAME(index, dir, channel)), (-1)),\
+		},
+
+void i2c_stm32_dma_tx_cb(const struct device *dma_dev, void *user_data,
+	uint32_t channel, int status)
+{
+	struct i2c_stm32_data *data = user_data;
```
Comment (erian747) [inline drivers/i2c/i2c_ll_stm32.c:601]: Compiler warning about unused variable

File: drivers/i2c/i2c_ll_stm32.c (hunk 1 above)
Comment (sgilbert182) [reply drivers/i2c/i2c_ll_stm32.c]: Removed variable

**Review by jonas-5ae29c — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/i2c/i2c_ll_stm32_v2.c [hunk 3]
```diff
@@ -195,10 +195,13 @@ static inline void msg_init(const struct device *dev, struct i2c_msg *msg,
 				/* Configure RX DMA */
 				data->dma_blk_cfg.source_address = LL_I2C_DMA_GetRegAddr(
 					cfg->i2c, LL_I2C_DMA_REG_DATA_RECEIVE);
+				data->dma_blk_cfg.source_addr_adj = DMA_ADDR_ADJ_NO_CHANGE;
+
```
[the remark this answers is not in the document]
Comment (sgilbert182) [reply drivers/i2c/i2c_ll_stm32_v2.c]: Done

File: drivers/i2c/i2c_ll_stm32.c [hunk 4]
```diff
@@ -587,15 +587,52 @@ static void i2c_stm32_irq_config_func_##index(const struct device *dev)	\
...
+#define I2C_DMA_INIT(index, dir)					\
+	.dir##_dma = {							\
+		.dev_dma = COND_CODE_1(DT_INST_DMAS_HAS_NAME(index, dir),\
+				(DEVICE_DT_GET(STM32_DMA_CTLR(index, dir))), (NULL)),\
+		.dma_channel = COND_CODE_1(DT_INST_DMAS_HAS_NAME(index, dir),\
+				(DT_INST_DMAS_CELL_BY_NAME(index, dir, channel)), (-1)),\
+		},
+
+void i2c_stm32_dma_tx_cb(const struct device *dma_dev, void *user_data,
+	uint32_t channel, int status)
```
[the remark this answers is not in the document]
Comment (sgilbert182) [reply drivers/i2c/i2c_ll_stm32.c]: Done

File: drivers/i2c/i2c_ll_stm32.c [hunk 5]
```diff
@@ -587,15 +587,52 @@ static void i2c_stm32_irq_config_func_##index(const struct device *dev)	\
...
+	}
+}
+
+void i2c_stm32_dma_rx_cb(const struct device *dma_dev, void *user_data,
+	uint32_t channel, int status)
+{
+	if (status != 0) {
+		LOG_ERR("DMA error %d", status);
+	}
+}
```
[the remark this answers is not in the document]
Comment (sgilbert182) [reply drivers/i2c/i2c_ll_stm32.c]: Tidied up the functions and broken out into it's own commit with an explanation for their use

File: drivers/i2c/i2c_ll_stm32.c [hunk 6]
```diff
@@ -595,6 +595,32 @@ static void i2c_stm32_irq_config_func_##index(const struct device *dev)	\
 				(DT_INST_DMAS_CELL_BY_NAME(index, dir, channel)), (-1)),\
 		},
 
+void i2c_stm32_dma_tx_cb(const struct device *dma_dev, void *user_data,
+			uint32_t channel, int status)
+{
+	(void)dma_dev;
+	(void)user_data;
+	(void)channel;
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32.c:603]:
```suggestion
	ARG_UNUSED(dma_dev);
	ARG_UNUSED(user_data);
	ARG_UNUSED(channel);
```

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/i2c/i2c_ll_stm32.c (hunk 6 above)
Comment (sgilbert182) [reply drivers/i2c/i2c_ll_stm32.c]: Done

**Review by erian747 — APPROVED** [review]

**Comment by sgilbert182** [comment]
Hi @erwango, this seems to have sat stale for a while but is tested working and is good to go. Are there any more changes you need?

**Review by erwango — APPROVED** [review]

File: drivers/i2c/i2c_ll_stm32.h [hunk 7]
```diff
@@ -105,7 +105,8 @@ struct i2c_stm32_data {
 	const struct device *smbalert_cb_dev;
 #endif
 #ifdef CONFIG_I2C_STM32_V2_DMA
-	struct dma_config dma_cfg;
+	struct dma_config dma_tx_cfg;
+	struct dma_config dma_rx_cfg;
```
Comment (gautierg-st) [inline drivers/i2c/i2c_ll_stm32.h:109]: Nit (non-blocking): since struct `i2c_stm32_config` has `tx_dma` and `rx_dma`, it would be more logical to name these `tx_dma_cfg` and `rx_dma_cfg` (or the other way around by renaming the first two as `dma_tx` and `dma_rx`)

**Review by gautierg-st — APPROVED** [review]
