### PR TITLE
drivers: clock control: stm32h7 set the voltage scale0 correctly

### LINKED ISSUE #104536: clock_stm32_ll_h7.c: VOS0 mode improperly set
### Describe the bug

The stm32 clock driver does not set the VOS0 mode as it claims to do.
In the function `prepare_regulator_voltage_scale(void)` there is the following code:
```
/* Make sure to put the CPU in highest Voltage scale during clock configuration */
/* Highest voltage is SCALE0 */
LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0);
```
The comments clearly say the purpose of the function to set VOS0 and also the value used LL_PWR_REGU_VOLTAGE_SCALE0 means VOS0, however the LL_PWR_SetRegulVoltageScaling function is unable to do so:
```
/**
  * @brief  Set the main internal Regulator output voltage
  * @rmtoll D3CR    VOS       LL_PWR_SetRegulVoltageScaling
  * @param  VoltageScaling This parameter can be one of the following values:
  *         @arg @ref LL_PWR_REGU_VOLTAGE_SCALE0
  *         @arg @ref LL_PWR_REGU_VOLTAGE_SCALE1
  *         @arg @ref LL_PWR_REGU_VOLTAGE_SCALE2
  *         @arg @ref LL_PWR_REGU_VOLTAGE_SCALE3
  * @note   For all H7 lines except STM32H7Axxx and STM32H7Bxxx lines, VOS0
  *         is applied when PWR_D3CR_VOS[1:0] = 0b11 and  SYSCFG_PWRCR_ODEN = 0b1.
  * @retval None
  */
__STATIC_INLINE void LL_PWR_SetRegulVoltageScaling(uint32_t VoltageScaling)
{
#if defined (PWR_CPUCR_PDDS_D2)
  MODIFY_REG(PWR->D3CR, PWR_D3CR_VOS, VoltageScaling);
#else
  MODIFY_REG(PWR->SRDCR, PWR_SRDCR_VOS, VoltageScaling);
#endif /* PWR_CPUCR_PDDS_D2 */
}
```
The note correctly states that to use VOS0 is necessary also to set the ODEN bit, but this function does not modify it.
To actually activate the VOS0 is necessary to use something like:
```
__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);
```
This macro correctly sets VOS1 and then sets the ODEN bit which eventually set VOS0 correctly.

The effect of this bug is that in case of highly demanding fw (many peripherals used at the same time), the fw could crash because it fails to correctly read from ram (especially during initialization phase). It is a subtle bug because in many cases the VOS1 setting is enough to keep things working also in case high AXI Interface clock frequency (225MHz,240MHz) is used. (See table 16 of STM32H747 Reference manual, RM0399, pag. 166).

Below I classified the bug as "major" because it could be very problematic to detect and lead to unusable boards: perfectly fine application crashes only when many peripheral are use together. Nevertheless it is very easy to reproduce and systematic.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Use the following function to print the vos status:
```
#include <soc.h>

/**
 * @brief Prints the current STM32H7 Voltage Scaling (VOS) state.
 * This reads the raw hardware registers from the PWR and SYSCFG
 * peripherals to determine the exact voltage being supplied to the core.
 */
void print_vos_setting(void)
{
   /* Ensure the SYSCFG clock is enabled so we can read its registers */
   __HAL_RCC_SYSCFG_CLK_ENABLE();

   /* Read the hardware registers */
   uint32_t pwr_d3cr = PWR->D3CR;
   uint32_t syscfg_pwrcr = SYSCFG->PWRCR;

   /* Extract the specific bits */
   /* VOS is located at bits 14 and 15 of PWR->D3CR */
   uint32_t vos_bits = (pwr_d3cr & PWR_D3CR_VOS) >> PWR_D3CR_VOS_Pos;
   /* ODEN is bit 0 of SYSCFG->PWRCR */
   uint32_t oden_bit = (syscfg_pwrcr & SYSCFG_PWRCR_ODEN) ? 1 : 0;

   printk("\n========================================\n");
   printk("       DIAGNOSTIC: VOLTAGE SCALE        \n");
   printk("========================================\n");
   printk("PWR_D3CR (VOS bits) : %u\n", vos_bits);
   printk("SYSCFG_PWRCR (ODEN) : %u\n", oden_bit);

   /* 4. Interpret the results based on the STM32H7 datasheet */
   if (vos_bits == 3) {
      if (oden_bit == 1) {
         printk("Current State       : VOS0 (Overdrive / 1.35V)\n");
      } else {
         printk("Current State       : VOS1 (1.25V)\n");
      }
   } else if (vos_bits == 2) {
      printk("Current State       : VOS2 (1.15V)\n");
   } else if (vos_bits == 1) {
      printk("Current State       : VOS3 (1.05V)\n");
   } else {
      printk("Current State       : Unknown\n");
   }
   printk("========================================\n\n");
}
```
The function will print:
```
=======================================
       DIAGNOSTIC: VOLTAGE SCALE
========================================
PWR_D3CR (VOS bits) : 3
SYSCFG_PWRCR (ODEN) : 0
Current State       : VOS1 (1.25V)
========================================
```
This means that the current code calling LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0); does not work properly.

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

OS: Linux (Ubuntu 22.04)
Zephyr SDK version: 0.17.4
Zephyr version: tag v4.3.0 (SHA: 3568e1b6d5cdd51a6b964a2a1d6d29200fea2056)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by FRASTM**
This PR uses the correct macro that actually set VOS0
 (thanks to @pillo79 that got the bottom of the problem discovering
 that this is a bug in the STM zephyr driver).
A bug report that explains the problem can be found here:
 zephyrproject-rtos#104536 and the fix for the arduino-zephyr  https://github.com/arduino/zephyr/pull/12/changes Arduino 

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/104536

### CODE REVIEW

File: drivers/clock_control/clock_stm32_ll_h7.c [hunk 1]
```diff
@@ -256,10 +268,11 @@ static int32_t prepare_regulator_voltage_scale(void)
 {
 	/* Make sure to put the CPU in highest Voltage scale during clock configuration */
 	/* Highest voltage is SCALE0 */
-	LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0);
 #if defined(CONFIG_SOC_SERIES_STM32H7RSX)
+	HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE0);
 	while (LL_PWR_IsActiveFlag_VOSRDY() == 0) {
 #else
+	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);
```
Comment (mathieuchopstm) [inline drivers/clock_control/clock_stm32_ll_h7.c]: H7R/S doesn't seem to have `ODEN` - how about:
```suggestion
	LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0);
	while (LL_PWR_IsActiveFlag_VOSRDY() == 0) {
#else
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);
```

File: drivers/clock_control/Kconfig.stm32 [hunk 2]
```diff
@@ -14,6 +14,8 @@ menuconfig CLOCK_CONTROL_STM32_CUBE
 		SOC_SERIES_STM32MP2X || SOC_SERIES_STM32H7X || SOC_SERIES_STM32H7RSX || \
 		SOC_SERIES_STM32F4X || SOC_SERIES_STM32F7X || \
 		SOC_SERIES_STM32N6X)
+	select USE_STM32_HAL_PWR if SOC_SERIES_STM32H7X
+	select USE_STM32_HAL_PWR_EX if SOC_SERIES_STM32H7RSX
```
Comment (mathieuchopstm) [inline drivers/clock_control/Kconfig.stm32]: `__HAL_PWR_VOLTAGESCALING_CONFIG` is in the HAL header - the driver should not be needed for H7

If you accept proposal above, the HAL PWR EX driver is also not needed on H7R/S

Comment (FRASTM) [reply drivers/clock_control/Kconfig.stm32]: changed

File: drivers/clock_control/Kconfig.stm32 [hunk 3]
```diff
@@ -14,6 +14,7 @@ menuconfig CLOCK_CONTROL_STM32_CUBE
 		SOC_SERIES_STM32MP2X || SOC_SERIES_STM32H7X || SOC_SERIES_STM32H7RSX || \
 		SOC_SERIES_STM32F4X || SOC_SERIES_STM32F7X || \
 		SOC_SERIES_STM32N6X)
+	select USE_STM32_HAL_PWR if SOC_SERIES_STM32H7X
```
Comment (mathieuchopstm) [inline drivers/clock_control/Kconfig.stm32]: Have you tried to build without it? I *think* it should not be needed.

But non-blocker, linker should just discard the file if not actually used.

**Review by mathieuchopstm — DISMISSED** [review]

File: drivers/clock_control/Kconfig.stm32 (hunk 3 above)
Comment (etienne-lms) [reply drivers/clock_control/Kconfig.stm32]: Indeed. Macro `__HAL_PWR_VOLTAGESCALING_CONFIG()` only requires the  HAL header file, not the C source implementation.

File: drivers/clock_control/clock_stm32_ll_h7.c [hunk 4]
```diff
@@ -256,10 +268,11 @@ static int32_t prepare_regulator_voltage_scale(void)
 {
 	/* Make sure to put the CPU in highest Voltage scale during clock configuration */
 	/* Highest voltage is SCALE0 */
-	LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0);
 #if defined(CONFIG_SOC_SERIES_STM32H7RSX)
+	LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0);
 	while (LL_PWR_IsActiveFlag_VOSRDY() == 0) {
 #else
+	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h7.c:275]: `__HAL_PWR_VOLTAGESCALING_CONFIG()` confiures PWR_CR1[VOS] which seems used on Stop mode exit. Shouldn't `LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0)` also be called here?

**Review by etienne-lms — COMMENTED** [review]
Maybe revword the commit message:
```patch
drivers: clock control: stm32h7: set the voltage scale0 correctly

Correct the macro used to set VOS0 on H7xx targets.

Fixes: #104579 
Signed-off-by: ...

File: drivers/clock_control/Kconfig.stm32 (hunk 3 above)
Comment (FRASTM) [reply drivers/clock_control/Kconfig.stm32]: ok

File: drivers/clock_control/clock_stm32_ll_h7.c (hunk 4 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_h7.c:275]: no, this is what we do not want anymore : see https://github.com/arduino/zephyr/pull/12/changes

File: drivers/clock_control/Kconfig.stm32 (hunk 2 above)
Comment (FRASTM) [reply drivers/clock_control/Kconfig.stm32]: done

File: drivers/clock_control/clock_stm32_ll_h7.c (hunk 4 above)
Comment (etienne-lms) [reply drivers/clock_control/clock_stm32_ll_h7.c:275]: Right. I see I was looking at another SoC `__HAL_PWR_VOLTAGESCALING_CONFIG()` implementation. Discard my comment.

While at it, I think It would be worth cleaning the `while()` loop end brace:
```patch
#if defined(CONFIG_SOC_SERIES_STM32H7RSX)
	LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE0);
	while (LL_PWR_IsActiveFlag_VOSRDY() == 0) {
+	}
#else
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);
	while (LL_PWR_IsActiveFlag_VOS() == 0) {
+	}
#endif
-	}

(not a blocking comment)

**Review by erwango — APPROVED** [review]

File: drivers/clock_control/clock_stm32_ll_h7.c
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h7.c:293]: A first look, it seems the regulator voltage scale seem not modified between the call to `prepare_regulator_voltage_scale()` and the call to this function. That said, for consistency, should this function be changed also to use `__HAL_PWR_VOLTAGESCALING_CONFIG()` on H7xx targets?

By the way, what is the difference between `prepare_regulator_voltage_scale()` and `optimize_regulator_voltage_scale()`. It seems the 2 implementation have always been the same across this source file changes and `sysclk_freq()` never been used here.

Comment (etienne-lms) [reply drivers/clock_control/clock_stm32_ll_h7.c:293]: Not a blocking comment. Could be looked at later.

**Review by etienne-lms — APPROVED** [review]
