### PR TITLE
drivers: usb_dc_mcux_ehci: fix endpoints index assignment

### LINKED ISSUE #27569: mimxrt1050_evk:samples.usb.cdc-acm-composite failed
Describe the bug
building samples/subsys/usb/cdc_acm_composite/ board, it would report a wrong.

To Reproduce

    west build -b mimxrt1050_evk samples/subsys/usb/cdc_acm_composite/
    west flash
    see error

Logs and console output
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v2.3.0-1774-g34859d0d3e40  ***
DEBUG   - DEVICE: [00:00:00.005,000] <err> usb_dc_mcux_ehci: Wrong endpoint index/address
DEBUG   - DEVICE: [00:00:00.005,000] <err> cdc_acm_composite: Failed to enable USB

Environment (please complete the following information):

    OS: Fedora28
    Toolchain: Zephyr-sdk-0.11.3
    Commit ID: 34859d0d3e

### PR DESCRIPTION
**Pull request by jfischer-no**
MCUX EHCI USB device controller supports a specific
number of bidirectional endpoints. Bidirectional means
that an endpoint object is represented to the outside
as an OUT and an IN Eindpoint with its own buffers
and control structures.

ep_abs_idx index refers to the corresponding control
structure, for example:

```
 EP addr | ep_idx | ep_abs_idx
-------------------------------
 0x00    | 0x00   | 0x00
 0x80    | 0x00   | 0x01
 0x01    | 0x01   | 0x02
 0x81    | 0x01   | 0x03
 ....    | ....   | ....
```

The NUM_OF_EP_MAX (and number of s_ep_ctrl) should be double
of num_bidir_endpoints. There is also no need to reserve
endpoint addresses for this controller type.

Fixes: #27569
Depends/associated with https://github.com/zephyrproject-rtos/hal_nxp/pull/54

### CODE REVIEW

File: drivers/usb/device/usb_dc_mcux_ehci.c [hunk 1]
```diff
@@ -37,7 +37,7 @@ extern void USB_DeviceEhciIsrFunction(void *deviceHandle);
 /* Then endpoint number/index calculation */
 #define EP_ABS_IDX(ep)		(USB_EP_GET_IDX(ep) * 2 + \
 					(USB_EP_GET_DIR(ep) >> 7))
-#define NUM_OF_EP_MAX		DT_INST_PROP(0, num_bidir_endpoints)
+#define NUM_OF_EP_MAX		(DT_INST_PROP(0, num_bidir_endpoints) * 2)
```
Comment (dleach02) [inline drivers/usb/device/usb_dc_mcux_ehci.c:40]: I understand what you are doing here. One observation is that this NUM_OF_EP_MAX is the total number of endpoints but each endpoint is not equal. As long as the reader of the code understands that, at least in this case, this is the total count with an equal split between IN and OUT endpoints.

I also think that your comments in the commit should be pulled into the source code somewhere for the viewer to see and understand.

**Review by dleach02 — CHANGES_REQUESTED** [review]
Tested and works on my platform. 

I have one request though to copy the comments in the commit into the source code someplace to capture the underlying design intent for future readers of the code.

**Review by dleach02 — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
