### PR TITLE
Bluetooth: host: add dedicated WQ for long-running tasks

### LINKED ISSUE #43811: ble: gatt: db_hash_work runs for too long and makes serial communication fail
**Environment**
Zephyr version: 2.5
Target: NRF52840

**Bug description**
Just after registering a service, UART communication is blocked for more than 10ms, causing a communication failure. In the following image, the moment when the bus is interrupted is circled in red. As a result, the chip answers before the tx communication finishes.
image

Some investigation showed that the `db_hash_work` (`gatt.c`) execution is taking several ms, and blocks all serial communications during this time as sysworkq is very high priority: 

- On the SystemView capture below, we see that the sysworkq is interrupting our LPWAN thread (which is making UART communications) for 10ms.
- By printing the work pointers, I saw that `db_hash_work` was executed just at the time of the bug. Setting a k_busy_wait(5000) in `db_hash_process` confirmed this, as the interruption time was now 15ms.

image

The execution time of this work depends of the number of services (in this case 13 services).

The only simple temporary workaround we found (which is not thread safe) is to add a k_sleep of several ms after each call to bt_gatt_service_register.

**To Reproduce**
1. Register a lot of services with `bt_gatt_service_register`
2. A bit less than 10ms after registering the last service, make a long UART communication

This communication failure is not easy to reproduce as it requires a particular timing. But even without reproducing the communication failure, the fact that db_hash_work lasts a long time can be easily seen with Segger SystemView (or even with timestamped logs placed at the beginning and at the end of `db_hash_process` function). For this, it is enough to register a lot of services (for example 15 with each 5 characteristics) with `bt_gatt_service_register` and capture the right moment, 10ms after the last service register.
Maybe the execution time is completely different on another target than the NRF52840.

**Expected behavior**
If this `db_hash_process` can be interrupted, it should maybe be executed in a low priority thread. If it cannot be interrupted, I think there should be at least a callback indicating the caller of `bt_gatt_service_register` that `db_hash_process` has finished and serial communications are safe.
There are certainly better solutions that I didn't think of.

### PR DESCRIPTION
**Pull request by jori-nordic**
Send long-running tasks to a dedicated low-priority workqueue.

This shouldn't increase memory usage since by doing this, we get rid of the
ECC processing thread.

This should fix issues like #43811, since the system workqueue runs at a
cooperative priority, and the new dedicated one runs at a pre-emptible
priority.

Open to any comments or other solutions. I'll change the PR title when we settled on something.

Fixes #43811

Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>

### CODE REVIEW

**Review by Thalley — COMMENTED** [review]
What is the advantage of using this WQ instead of e.g. the system workqueue? Is it used for computationally heavy operations that may be blocking the other workqueue? 

Is this useful for non-BT work? I.e. should we have a generic low-priority, heavy-workload workqueue instead?

**Comment by jori-nordic** [comment]
> What is the advantage of using this WQ instead of e.g. the system workqueue? Is it used for computationally heavy operations that may be blocking the other workqueue?
> 
> Is this useful for non-BT work? I.e. should we have a generic low-priority, heavy-workload workqueue instead?

I'll try to answer everything:

1. The 'only' advantage is that it's a pre-emptible priority, so can be pre-empted by any other coop thread (or sys wq). The linked issue shows a possible failure mode of using a coop wq.
2. Yes and yes. @alwa-nordic suggested exactly this this afternoon, but @carlescufi and I thought it's be good to have it first in use in bluetooth, and then we can argue to have it system-wide in a later PR.

Another point that was raised in the discussion was that @LingaoM added a way to use a 'bluetooth-dedicated' wq in a space-saving PR a while ago, and I could arrange to re-use that one (or use the syswq) for applications where space is a premium and where waiting 10ms-ish isn't that big a deal.

**Comment by jori-nordic** [comment]
> I understand that db hash does not occupy a separate task in the past implementation, but now it shares a task with ecc, is there an additional resource burden? After all, in the past mechanism, after ecc is closed, it will not there are other ecc tasks exist.

What do you mean by `ecc is closed` ? The previous implementation had a low-priority thread that ran the ecc tasks, blocking until ECC tasks are submitted, but isn't stopped, so the RAM used for its stack can't be reclaimed anyways. The new implementation has a low-priority workqueue, also staying idle if no more tasks are submitted.
 
The only difference (with the current patch) is that there will be an additional thread if you enable GATT caching but not ECC_TINYCRYPT. I will change that so a memory-conscious user can disable this new wq by setting `CONFIG_BT_LONG_WQ=n`, and then the gatt hashing will be sent to the system wq as was done before.

**Review by alwa-nordic — DISMISSED** [review]

**Review by LingaoM — DISMISSED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1307,7 +1308,11 @@ void bt_gatt_init(void)
 	/* Submit work to Generate initial hash as there could be static
 	 * services already in the database.
 	 */
+#if defined(CONFIG_BT_LONG_WQ)
+	k_work_schedule_for_queue(bt_long_wq_get(), &db_hash.work, DB_HASH_TIMEOUT);
+#else
 	k_work_schedule(&db_hash.work, DB_HASH_TIMEOUT);
+#endif /* CONFIG_BT_LONG_WQ */
```
Comment (Thalley) [inline subsys/bluetooth/host/gatt.c]: Can't we use `IS_ENABLED` now that we use `bt_long_wq_get()`?

File: subsys/bluetooth/host/hci_ecc.c [hunk 2]
```diff
@@ -261,7 +256,7 @@ static uint8_t le_gen_dhkey(uint8_t *key, uint8_t key_type)
 	atomic_set_bit_to(flags, USE_DEBUG_KEY,
 			  key_type == BT_HCI_LE_KEY_TYPE_DEBUG);
 
-	k_sem_give(&cmd_sem);
+	k_work_submit_to_queue(bt_long_wq_get(), &ecc_work);
```
Comment (Thalley) [inline subsys/bluetooth/host/hci_ecc.c:259]: GATT caching is conditionally using the long WQ, but here we are unconditionally using it. Is that intentional?

File: subsys/bluetooth/host/long_work.c [hunk 3]
```diff
@@ -0,0 +1,27 @@
+#include <zephyr/kernel.h>
+#include <zephyr/init.h>
+
+K_THREAD_STACK_DEFINE(bt_lw_stack_area, CONFIG_BT_LONG_WQ_STACK_SIZE);
+static struct k_work_q bt_long_wq;
+
+struct k_work_q * bt_long_wq_get(void)
```
Comment (Thalley) [inline subsys/bluetooth/host/long_work.c:12]:
```suggestion
struct k_work_q *bt_long_wq_get(void)
```

File: subsys/bluetooth/host/long_work.h [hunk 4]
```diff
@@ -0,0 +1,20 @@
+/* long_work.h - Workqueue intended for long-running operations. */
+
+/*
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#ifndef __LONG_WORK_H_
+#define __LONG_WORK_H_
```
Comment (Thalley) [inline subsys/bluetooth/host/long_work.h:7]: We generally don't use include guards for internal header files

File: subsys/bluetooth/host/long_work.h [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+
+#if defined(CONFIG_BT_LONG_WQ)
+struct k_work_q * bt_long_wq_get(void);
+#else
+#include <zephyr/kernel.h>
+
+inline struct k_work_q * bt_long_wq_get(void)
+{
+	return &k_sys_work_q;
+}
```
Comment (Thalley) [inline subsys/bluetooth/host/long_work.h:17]: Hmm, not sure how I feel about this, as `bt_long_wq_get` might suggest that it is a specific WQ. 

Could there not be a case where you'd want to either use the long_wq (if enabled), or a workqueue different from the system workqueue in case that the long_wq isn't available?

File: subsys/bluetooth/host/hci_ecc.c (hunk 2 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/hci_ecc.c:259]: yes, since it's replacing the hci_ecc thread, we still need it if this file is compiled in.

File: subsys/bluetooth/host/long_work.h (hunk 5 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/long_work.h:17]: what parameter type would you propose ? I thought of `prio` but am not sure.

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c]: yeah, sorry I updated the PR a few minutes after with the selection done in `long_work.h`. I'll update it again when we decide on https://github.com/zephyrproject-rtos/zephyr/pull/46131#discussion_r887797468

File: subsys/bluetooth/host/hci_ecc.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/host/hci_ecc.c:259]: But will the ECC still work without the long workqueue?

File: subsys/bluetooth/host/long_work.h (hunk 5 above)
Comment (Thalley) [reply subsys/bluetooth/host/long_work.h:17]: I am not sure `bt_long_wq_get` should return `&k_sys_work_q` at all. IMO, since we added a Kconfig for it, `bt_long_wq_get` should be callable if, and only if, the long workqueue Kconfig is enabled.

File: subsys/bluetooth/host/hci_ecc.c (hunk 2 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/hci_ecc.c:259]: you're right that if a user puts `CONFIG_BT_LONG_WQ=n` then ECC won't work. I will add a `select` statement to `BT_TINYCRYPT_ECC` to prevent that.

Comment (Thalley) [reply subsys/bluetooth/host/hci_ecc.c:259]: Any reason why we don't want to treat ECC and GATT caching the same? i.e. if GATT caching can be done in the system workqueue, can't ECC be that too?

Comment (jori-nordic) [reply subsys/bluetooth/host/hci_ecc.c:259]: It's a good point, maybe @cvinayak could comment on that ?
I guess it could open the door to more bugs like the one this PR is trying to fix. Maybe even deadlocks ? not sure.

File: subsys/bluetooth/host/Kconfig [hunk 6]
```diff
@@ -4,14 +4,29 @@
 # Copyright (c) 2015-2016 Intel Corporation
 # SPDX-License-Identifier: Apache-2.0
 
+config BT_LONG_WQ
+	# Enable dedicated wq for long-running tasks
+	bool "Enable dedicated workqueue for long-running tasks."
+	default y if BT_GATT_CACHING || BT_TINYCRYPT_ECC
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/Kconfig:11]: You need to add a proper help text here, explaining what happens if this gets disabled, i.e. that the operations will run in system work queue context then and have some potentially unexpected (bad) behaviour.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Generally looks like this is going in the right direction, however please take a look at my inline comments.

File: subsys/bluetooth/host/Kconfig [hunk 7]
```diff
@@ -4,14 +4,29 @@
...
+if BT_LONG_WQ
+config BT_LONG_WQ_STACK_SIZE
+	int "Long workqueue stack size."
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/Kconfig:14]: I get what you mean, but the same can be argued for `BT_HCI_ECC_STACK_SIZE` which is public.

I made it settable so quick fixes would be possible without source changes. I don't have a strong opinion though, I can make it private if you want.

File: subsys/bluetooth/host/gatt.c [hunk 8]
```diff
@@ -1307,7 +1308,7 @@ void bt_gatt_init(void)
 	/* Submit work to Generate initial hash as there could be static
 	 * services already in the database.
 	 */
-	k_work_schedule(&db_hash.work, DB_HASH_TIMEOUT);
+	k_work_schedule_for_queue(bt_long_wq_get(), &db_hash.work, DB_HASH_TIMEOUT);
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:1311]: huh I originally had it that way but decided to go without. I'll add them.

File: subsys/bluetooth/host/Kconfig (hunk 7 above)
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/Kconfig:14]: We could have the `BT_HCI_ECC_STACK_SIZE` `default` on some decent values depending on whether ECC/GATT caching is enabled. I assume that if we have GATT caching without ECC it can be smaller?

[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/Kconfig:21]: @Thalley that's what I was going for/expecting. Or maybe I misunderstand your comment ?

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/Kconfig:21]: No, I think we are aligned: Make this private and have the stack size depend on what internal requirements we have (as the long_wq isn't available to the application).

File: subsys/bluetooth/host/long_work.h [hunk 9]
```diff
@@ -0,0 +1,20 @@
...
+void bt_long_work_reschedule(struct k_work_delayable *dwork, k_timeout_t timeout);
+void bt_long_work_submit(struct k_work *dwork);
+
+#else
+
+#define bt_long_work_schedule k_work_schedule
+#define bt_long_work_reschedule k_work_reschedule
+#define bt_long_work_submit k_work_submit
+
+#endif /* CONFIG_BT_LONG_WQ */
```
Comment (Thalley) [inline subsys/bluetooth/host/long_work.h:20]: I am still on the fence on this: 

To me it is odd to be able to call `bt_long_work_schedule` and then _not_ having it being schedule on the long workqueue, but rather the system workqueue.

File: subsys/bluetooth/host/Kconfig [hunk 10]
```diff
@@ -4,14 +4,37 @@
 # Copyright (c) 2015-2016 Intel Corporation
 # SPDX-License-Identifier: Apache-2.0
 
+config BT_LONG_WQ
+	bool "Dedicated workqueue for long-running tasks."
+	default y if BT_GATT_CACHING || BT_TINYCRYPT_ECC
```
Comment (Thalley) [inline subsys/bluetooth/host/Kconfig:9]: Does `BT_TINYCRYPT_ECC` work without this? 

i.e. should we have a `select` or `depends on` for `BT_TINYCRYPT_ECC`?

File: subsys/bluetooth/host/Kconfig (hunk 7 above)
[the remark this answers is not in the document]
Comment (jhedberg) [reply subsys/bluetooth/host/Kconfig:21]: The one argument I can think of is if the stack size may vary depending on the architecture and compilation options (e.g. if optimization is enabled), however I think there might be some system-wide option affect all thread stacks for such cases?

File: subsys/bluetooth/host/long_work.h (hunk 9 above)
Comment (jhedberg) [reply subsys/bluetooth/host/long_work.h:20]: Well, at least the API doesn't explicitly spell out that it promises to schedule the work through a dedicated work queue. It just says that it's for scheduling work of a long duration. How that's implemented is a configurable detail. Btw, I think static inline functions are cleaner whenever possible (e.g. for type checking), so I'd prefer to see that instead of defines for the else-branch.

File: subsys/bluetooth/host/long_work.h [hunk 11]
```diff
@@ -0,0 +1,20 @@
...
+/*
+ * Copyright (c) 2022 Nordic Semiconductor ASA
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#if defined(CONFIG_BT_LONG_WQ)
+
+void bt_long_work_schedule(struct k_work_delayable *dwork, k_timeout_t timeout);
+void bt_long_work_reschedule(struct k_work_delayable *dwork, k_timeout_t timeout);
+void bt_long_work_submit(struct k_work *dwork);
```
Comment (jhedberg) [inline subsys/bluetooth/host/long_work.h:12]: The parameter name should probably be just `work` since it's not delayed work in this case.

File: subsys/bluetooth/host/long_work.h (hunk 9 above)
Comment (jhedberg) [reply subsys/bluetooth/host/long_work.h:20]: It'd be nice to see some test results of the system work queue option on some low performance platforms (e.g. nRF51) - I have a feeling you'll instantly see bad behaviour on those.

Comment (jori-nordic) [reply subsys/bluetooth/host/long_work.h:20]: yep, I'll try to get my hands on one and do that next week.

File: subsys/bluetooth/host/Kconfig (hunk 10 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/Kconfig:9]: I'll test that next week yeah. In theory it should work, since it'll just get submitted to the sys wq, but the stack size is not propagated there, and I just suspect bad behavior all around like johan said in another comment. If it doesn't work, I'll add a `select` or `depends on`, I always forget which one's the strongest.

Comment (Thalley) [reply subsys/bluetooth/host/Kconfig:9]: `select` and `depends on` are equally strong :) You may be thinking of `default` or `imply` which can be overridden.

File: subsys/bluetooth/host/long_work.h (hunk 9 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/long_work.h]: So I spent half the day trying to make security L2 work on a 51422, but it hung in the middle of the procedure. That was with the long workqueue enabled, I didn't dare to try with the syswq.

It didn't even work on (today's) main, got an assert in the ull
```
uart:~$ ASSERTION FAIL [!radio_is_ready()] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:384
```

So I added a `depends on` in the ECC Kconfig, so the functionality/footprint stays the same (ECC runs in a low-prio thread).
Of course I'm not opposed to someone making it possible to run in the syswq, but I'd like that to be part of another PR.

I also addressed the other comments.

File: subsys/bluetooth/host/long_work.h [hunk 12]
```diff
@@ -0,0 +1,31 @@
+/* long_work.h - Workqueue intended for long-running operations. */
+
+/*
+ * Copyright (c) 2022 Nordic Semiconductor ASA
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#if defined(CONFIG_BT_LONG_WQ)
+
+void bt_long_work_schedule(struct k_work_delayable *dwork, k_timeout_t timeout);
```
Comment (jhedberg) [inline subsys/bluetooth/host/long_work.h:10]: Seems like you forgot to update the return types here?

Comment (jori-nordic) [reply subsys/bluetooth/host/long_work.h]: yep good catch. fixed

**Review by jhedberg — DISMISSED** [review]

File: subsys/bluetooth/host/long_work.h [hunk 13]
```diff
@@ -0,0 +1,31 @@
...
+{
+	return k_work_reschedule(dwork, timeout);
+}
+
+static inline int bt_long_work_submit(struct k_work *work)
+{
+	return k_work_submit(work);
+}
+
+#endif /* CONFIG_BT_LONG_WQ */
```
Comment (Thalley) [inline subsys/bluetooth/host/long_work.h:31]: I don't recall if we ever discussed this, but I am not a huge fan of silently using the system workqueue when calling `bt_long_work_reschedule`, as the name implies a specific workqueue. 

If everyone else is OK with this approach, I guess it's fine

File: subsys/bluetooth/host/CMakeLists.txt [hunk 14]
```diff
@@ -12,6 +12,7 @@ zephyr_library_sources_ifdef(CONFIG_BT_RFCOMM           rfcomm.c)
 zephyr_library_sources_ifdef(CONFIG_BT_TESTING          testing.c)
 zephyr_library_sources_ifdef(CONFIG_BT_SETTINGS         settings.c)
 zephyr_library_sources_ifdef(CONFIG_BT_HOST_CCM         aes_ccm.c)
+zephyr_library_sources_ifdef(CONFIG_BT_LONG_WQ          long_work.c)
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/CMakeLists.txt:15]: yeah that's a good observation, I was on the fence of if I should keep it that way or align with the kconf. I'll change the api to `long_wq`.

File: subsys/bluetooth/host/gatt.c [hunk 15]
```diff
@@ -5586,7 +5588,7 @@ static int db_hash_commit(void)
 	/* Reschedule work to calculate and compare against the Hash value
 	 * loaded from flash.
 	 */
-	k_work_reschedule(&db_hash.work, K_NO_WAIT);
+	bt_long_work_reschedule(&db_hash.work, K_NO_WAIT);
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:5591]: I added a check for that one, yes (it should never fail methinks). But the other two call sites are void functions.

File: subsys/bluetooth/host/long_work.h (hunk 13 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/long_work.h]: I think @jhedberg had an ok argument there https://github.com/zephyrproject-rtos/zephyr/pull/46131#discussion_r889127801 (also my arg pretty much).

File: subsys/bluetooth/host/long_work.h (hunk 9 above)
Comment (Thalley) [reply subsys/bluetooth/host/long_work.h]: > Btw, I think static inline functions are cleaner whenever possible (e.g. for type checking), so I'd prefer to see that instead of defines for the else-branch.

I don't disagree with that, but my suggestion is to remove the `#else` part all together. 

It's not a public API, so I guess it's fine as is, but I would prefer to return linker errors if `CONFIG_BT_LONG_WQ=n` and someone attempted to call `bt_long_work_submit`

Comment (jori-nordic) [reply subsys/bluetooth/host/long_work.h]: It's just that if we don't do this, then we have to litter the code with yet other ifdefs. 
I don't know if it's just me, but ifdefs add a cognitive load when trying to read code, as they break the code indentation. 
So I prefer that they are used only for big code blocks and not around individual function calls if possible.

If I use `IS_ENABLED` in an if-else, would the compiler optimize that like and #if-else block ?

Comment (Thalley) [reply subsys/bluetooth/host/long_work.h]: > If I use IS_ENABLED in an if-else, would the compiler optimize that like an #if-else block ?

Yes - IS_ENABLED will still compile it, but won't link it (and thus the final result is the same as if it wasn't compiled), which is why it is also the preferred method. 

It isn't a huge issue to keep as is, but I think it'll be more explicit what is going on if we don't silent forward the work item to the system workqueue instead if `CONFIG_BT_LONG_WQ=n`.

File: subsys/bluetooth/host/long_wq.c [hunk 16]
```diff
@@ -0,0 +1,44 @@
...
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#include <zephyr/kernel.h>
+#include <zephyr/init.h>
+
+K_THREAD_STACK_DEFINE(bt_lw_stack_area, CONFIG_BT_LONG_WQ_STACK_SIZE);
+static struct k_work_q bt_long_wq;
+
+int bt_long_work_schedule(struct k_work_delayable *dwork, k_timeout_t timeout)
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/long_wq.c:14]: I wasn't comfortable changing the api to long_wq since it implied some specific workqueue. `work` was more like "I have some long-running work I want to schedule, please deal with it".
But since I've since changed it to not 'degrade' to the syswq, then I've renamed it as you suggested

**Review by jhedberg — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]

**Comment by carlescufi** [comment]
DNM until a potential regression is investigated.

**Review by alwa-nordic — DISMISSED** [review]

**Review by Thalley — APPROVED** [review]

**Comment by carlescufi** [comment]
@jhedberg @alwa-nordic can you please take another look?

**Review by jhedberg — APPROVED** [review]

**Comment by galak** [comment]
> rebased on today's main.
> Changes add 56 bytes of ROM, 64 bytes of RAM, measured by compiling bt_shell on main vs on this rebased commit.

This blows up RAM usage for `samples/boards/bbc_microbit/pong`:

` region `SRAM' overflowed by 1079 bytes`
