### PR TITLE
drivers: fuel_gauge: max17048: Fix overflow when calculating voltage

### LINKED ISSUE #63659: uint16_t Arithmetic overflow in MAX17048 driver
**Describe the bug**
The MAX17048 Fuel Gauge driver (drivers/fuel_gauge/max17048/max17048.c) function max17048_voltage() is returning erroneous values due to arithmetic overflow in the conversion from ADC register values to millivolts.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
   STM32 and likely all others, though may be compiler-dependent. I repro the problem with gcc.
 - What have you tried to diagnose or workaround this issue?
   Debugger, calculator, and using a cast to force type-promotion to uint32_t.
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
   No. This appears to have been in the code since its original contribution.

**To Reproduce**
1.  Create any project with a MAX17048 or with the emul_max17048 returning ADC register values close to 4V 
2.  Call max17048_voltage()
3.  Note that the return value is out-of-range for the battery attached or for the value provided in the emulator code and is inconsistent with manual calculations, though consistent with 16-bit overflow. You can also manually repeat the calculation of X * 78125 / 1,000,000 (where X is the ADC register value) on a calculator and note that the value differs from what the code returns.
4.  I can provide a sample project, though it's pretty easy to noodle out through code inspection at line 93 in max17048.c. Perhaps the compiler should have type-promoted to uint32, but the gcc compiler is not doing so.  Forcing that promotion via a cast remedies the problem.  Changing that line from:
    ```*response = *response * 78125 / 1000000;```
    to
    ```*response = (uint16_t)((uint32_t)*response * 78125L / 1000000L);```
    remedies the problem. Happy to submit a pull request to that effect.
 
**Expected behavior**
for max17048_voltage() to return a voltage value in millivolts that accurately represents the value encoded in the max17048 ADC register.

**Impact**
Renders the data returned by the driver invalid and unusable.

**Environment (please complete the following information):**
 - OS: Linux, MacOS, and Windows
 - Toolchain (e.g Zephyr SDK, ...) : Zephyr SDK 0.16.3
 - Commit SHA or Version used : Version 3.4.0

### PR DESCRIPTION
**Pull request by martincalsyn**
Annotate the calculation with type casts to force
promotion to uint32_t and then cast back down
to uint16_t for the return. This solves the issue
with invalid voltage (mV) values being returned
due to overflow during the conversion from the
register value on the max17048 chip.

fixes #63659 

Signed-off-by: Martin Calsyn <martin.calsyn@outcomex.com.au>

### CODE REVIEW

**Review by aaronemassey — DISMISSED** [review]
LGTM.

I plan on adding some extra generic emulated testing to all the implementations of the fuel gauge API.

I definitely think this could've been caught with the existing tests with a different stub emulator value. 

I plan on implementing the [set_battery_charging()](https://github.com/zephyrproject-rtos/zephyr/blob/ee588bae7a6106721328bd7a3d3cd7c856e2c7ec/include/zephyr/drivers/emul_fuel_gauge.h#L58) emulator API for the emul_max17048 to catch things like this.

You're than welcome to add that yourself to make a regression test for this, but I'll try to get to it in the coming weeks. But I'd rather get this fix in before the next release.

**Comment by martincalsyn** [comment]
I'm a Zephyr-PR-first-timer. Bear with me please as I work through the submission process.

File: drivers/fuel_gauge/max17048/max17048.c [hunk 1]
```diff
@@ -90,7 +90,7 @@ int max17048_voltage(const struct device *i2c_dev, uint16_t *response)
 	 * milli volts instead of volts.
 	 */
 
-    *response = (uint16_t)((uint32_t)*response * 78125L / 1000000L);
+	*response = (uint16_t)((uint32_t)*response * 78125L / 1000000L);
```
Comment (aaronemassey) [inline drivers/fuel_gauge/max17048/max17048.c:93]: By the way. We also make use of `clang-format` I highly recommend using that for formatting your code.

Also in general `ClangD` is great :)

**Comment by aaronemassey** [comment]
> I'm a Zephyr-PR-first-timer. Bear with me please as I work through the submission process.

No worries and thank you for contributing!

By the way, you can check the compliance locally by running `./scripts/ci/check_compliance.py` from the root of your Zephyr project.

File: drivers/fuel_gauge/max17048/max17048.c (hunk 1 above)
Comment (martincalsyn) [reply drivers/fuel_gauge/max17048/max17048.c:93]: Good call. Will do for future work as we are making a substantial bet on Zephyr am I look forward to more contributions. Thanks for your time and guidance.

**Comment by martincalsyn** [comment]
Good to know as this first go was a bit too trial-and-error (which is on me). Thanks.

File: drivers/fuel_gauge/max17048/max17048.c (hunk 1 above)
Comment (aaronemassey) [reply drivers/fuel_gauge/max17048/max17048.c:93]: That's great!

If you're interested, you should check out the wiki https://github.com/zephyrproject-rtos/zephyr/wiki. It has links to the working groups as well as a link to the Discord which is really active.

**Review by aaronemassey — APPROVED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

File: drivers/fuel_gauge/max17048/max17048.c [hunk 2]
```diff
@@ -90,7 +90,7 @@ int max17048_voltage(const struct device *i2c_dev, uint16_t *response)
 	 * milli volts instead of volts.
 	 */
 
-	*response = *response * 78125 / 1000000;
+    *response = (uint16_t)((uint32_t)*response * 78125L / 1000000L);
```
[the remark this answers is not in the document]
Comment (MaureenHelm) [reply drivers/fuel_gauge/max17048/max17048.c]: Right, I didn't see the second commit. It needs to be squashed into the first commit

**Comment by martincalsyn** [comment]
@MaureenHelm - fixed as requested with squashed commits. Thanks for bearing with me here.

**Review by MaureenHelm — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
