### PR TITLE
Bluetooth: Controller: Fix some compiler instruction re-ordering

### LINKED ISSUE #62661: [v3.3, v3.4] Bluetooth: Controller: Assertion in lll.c [evdone] running observer role
**Describe the bug**
Assertion observed in lll.c allocating `evdone`.
https://github.com/zephyrproject-rtos/zephyr/blob/577fd949c2a05781bef61bae1f28b9a3f05a52e5/subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c#L388

**To Reproduce**
1. mkdir -p build; cd build/hci_uart
2. cmake -GNinja -DBOARD=nrf52833dk_nrf52833 -DOVERLAY_CONFIG=overlay-all-bt_ll_sw_split.conf -DDTS_OVERLAY_FILE=boards/nrf52833dk_nrf52833_df.overlay ../../samples/bluetooth/hci_uart
3. ninja
4. ninja flash
5. On a linux distribution,
6. on one terminal, run `btmon`
7. on second terminal, run `btattach -B /dev/ttyACMx -S 1000000`
8. on third terminal, run `bluetoothctl`, and issue `scan le`
9. Observe that LE Extended Advertising Reports are generated in the btmon terminal output
10. Let the discovery run for minutes to hours
11. The said assertion is observed over time

**Expected behavior**
Device discovery in BlueZ on a linux distribution should be abe to run for ever without assertions

**Impact**
Showstopper

**Logs and console output**
TBD

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.15.1-rc1
 - Commit SHA or Version: 8350fc2c

**Additional context**
NA

### PR DESCRIPTION
**Pull request by cvinayak**
Fix some compiler instruction re-ordering. Mayfly code with cpu_dmb() help avoid stalled memq_ull_rx processing when rx_demux is to be executed using mayfly.

image

Fixes #62661

### CODE REVIEW

**Comment by cvinayak** [comment]
@wopu-ot and @mtpr-ot need your review.

**Review by kruithofa — APPROVED** [review]
LGTM

File: subsys/bluetooth/controller/util/mayfly.c [hunk 1]
```diff
@@ -154,10 +159,12 @@ static void dequeue(uint8_t callee_id, uint8_t caller_id, memq_link_t *link,
 		m->_link = link;
 
 		/* reset mayfly state to idle */
+		cpu_dmb();
```
Comment (Thalley) [inline subsys/bluetooth/controller/util/mayfly.c:162]: I'm not familiar with the `cpu_dmb()`, and it doesn't have any (generic) documentation on what it does or how it works. 

I can see that it marks something as `volatile`, but is that only the next operation, or all operations after `cpu_dmb()` has been present?

Comment (cvinayak) [reply subsys/bluetooth/controller/util/mayfly.c:162]: This is inserting a compiler stronger Data Memory Barrier:
`asm volatile ("" : : : "memory")`

Refer: https://gcc.gnu.org/onlinedocs/gcc/Volatiles.html

FYI, `cpu_dmb()` is Zephyr Controller specific HAL implementation, I see that recently (May'23) Zephyr is providing now a interface `barrier_dsync_fence_full()`  replacing __DSB() instruction which is more a CPU memory barrier instruction in combination with compiler memory barrier but focusing on multi-cpu senarios (SMP). On single core, ___DSB() is not implemented.

**Review by Thalley — APPROVED** [review]

**Review by mtpr-ot — APPROVED** [review]
LGTM
