### PR TITLE
drivers: uart_imx: Fix the poll_in function

### LINKED ISSUE #45533: uart_imx_poll_in() seems to be a blocking function
**Describe the bug**

As per #45468, I'm filling a bug report against the UART driver for NXP i.MX7.  The function `uart_imx_poll_in()` seems to be a blocking call, as [wrongly documented in our doc](https://docs.zephyrproject.org/latest/hardware/peripherals/uart.html).  The function, instead, should be non-blocking and must return `-1` when there is no valid data.

**Expected behavior**
Non blocking and return `-1` when no valid data is available.

**Impact**
Different behavior compare to other UART drivers.

**Additional context**
https://github.com/zephyrproject-rtos/zephyr/issues/45468#issuecomment-1122620593

### PR DESCRIPTION
**Pull request by mmahadevan108**
Current poll_in function implementation blocks when there is no data available. The Zephyr documentation for poll_in expects the function to return -1 when no data is available.

Fixes #45533

### CODE REVIEW

**Review by yashi — APPROVED** [review]
LGTM

**Review by dleach02 — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

File: drivers/serial/uart_imx.c [hunk 1]
```diff
@@ -113,16 +113,18 @@ static void uart_imx_poll_out(const struct device *dev, unsigned char c)
 static int uart_imx_poll_in(const struct device *dev, unsigned char *c)
 {
 	UART_Type *uart = UART_STRUCT(dev);
+	int ret = -1;
```
Comment (GeorgeCGV) [inline drivers/serial/uart_imx.c:116]: Could we use the `-EIO` (`-5`) instead of `-EPERM` (`-1`)?

Comment (GeorgeCGV) [reply drivers/serial/uart_imx.c:116]: Sorry, I didn't look into the UART header. Not sure how `-1` got in there, normally `-<ERRNO>` is used from `errno.h`.

Comment (mmahadevan108) [reply drivers/serial/uart_imx.c:116]: Please do add an issue and if possible a PR if this is something that needs to be addressed.
