### PR TITLE
kernel: work_q: fix return value in non-error case

### LINKED ISSUE #22933: k_delayed_work_submit_to_queue returns error code when resubmitting previously completed work.
**Describe the bug**
k_delayed_work_submit_to_queue returns error code -EALREADY when submitting previously completed task. Tak is submitted successfully. This response is not covered in doc. This should probably be changed to 0 since error code is propagated from k_delayed_work_cancel. 

**Expected behavior**
0 result - work was submitted to queue. 
OR
response described in doc

### PR DESCRIPTION
**Pull request by pabigot**
A recent patch allowed an error code to be returned even though the
execution path treated it as a non-error condition.  Clear the code
before returning.

Fixes #22933

### CODE REVIEW

File: kernel/work_q.c [hunk 1]
```diff
@@ -99,7 +99,9 @@ int k_delayed_work_submit_to_queue(struct k_work_q *work_q,
 		/* -EALREADY indicates the work has already completed so this
 		 * is likely a recurring work.
 		 */
```
Comment (joerchan) [inline kernel/work_q.c]: This seems like further circumvention of the problem to me.
It would be better to have a better check for if the work should be canceled or not. because in this case it doesn't need to be canceled, which is why it returns EALREADY.
The work->work_q is not reset to NULL once finished, so it should be used in all this error handling.

The check above for example:
```
	if (work->work_q != NULL && work->work_q != work_q) {
		err = -EADDRINUSE;
		goto done;
	}
```
Is this one the correct behavior?

Comment (joerchan) [reply kernel/work_q.c]: I would pick https://github.com/zephyrproject-rtos/zephyr/issues/22933#issuecomment-588287754 as the solution.

**Review by andyross — APPROVED** [review]
I think this looks fine as written.  The code is trying to ensure that the existing work item isn't already submitted, so it calls work_cancel() to do that.  The -EALREADY result is, for that requirement, equivalent to zero.  So this patch treats it that way.  It seems straightforward.

(Note that becuase this is an internal context, we're already synchronized so not subject to the fundamental raciness of this "is it done yet?" API that I've complained about before.)

File: kernel/work_q.c (hunk 1 above)
Comment (andyross) [reply kernel/work_q.c]: That seems like something that should go into work_cancel(), not here, though, right?

**Review by jhedberg — APPROVED** [review]

**Review by Vudentz — APPROVED** [review]
LGTM, while at it please add a check for the return of submit on tests since it appear I forgot to do that which is why the tests passes even with this regression.

File: kernel/work_q.c (hunk 1 above)
Comment (Vudentz) [reply kernel/work_q.c]: Yep, I though about moving that check ou of work_cancel now that you mentioned it might be the right thing to do as a separate patch.
