### PR TITLE
kernel: thread: fix comparison of unsigned expression is always false

### LINKED ISSUE #81049: kernel: thread: warning generated if comparison of unsigned expression is always false
K_KERNEL_STACK_RESERVED can be 0 which can give a warning with -Wtype-limits. 

```
zephyr/kernel/thread.c: In function 'setup_thread_stack':
zephyr/kernel/thread.c:416:45: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
  416 |                 if (K_KERNEL_STACK_RESERVED > stack_obj_size) {
      |                          
```

### PR DESCRIPTION
**Pull request by XenuIsWatching**
K_KERNEL_STACK_RESERVED can be 0 which can give a warning with -Wtype-limits. Only perform the check if K_KERNEL_STACK_RESERVED is not 0.

```
zephyr/kernel/thread.c: In function 'setup_thread_stack':
zephyr/kernel/thread.c:416:45: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
  416 |                 if (K_KERNEL_STACK_RESERVED > stack_obj_size) {
      |                                             ^
```

### CODE REVIEW

File: kernel/thread.c [hunk 1]
```diff
@@ -413,14 +413,15 @@ static char *setup_thread_stack(struct k_thread *new_thread,
 		stack_buf_start = K_KERNEL_STACK_BUFFER(stack);
 		stack_buf_size = stack_obj_size - K_KERNEL_STACK_RESERVED;
 
+#ifdef ARCH_KERNEL_STACK_RESERVED
```
Comment (peter-mitsis) [inline kernel/thread.c:416]: I don't think that `#ifdef ARCH_KERNEL_STACK_RESERVED` is the right approach. Some architectures appear to define  ARCH_KERNEL_STACK_RESERVED to 0, which in turn can lead to K_KERNEL_STACK_RESERVED being defined to 0.

Is there any reason why we the following could not be done to prevent that warning?

```
#if (K_KERNEL_STACK_RESERVED > 0)
...
#endif
```

Comment (XenuIsWatching) [reply kernel/thread.c]: that works as well

**Review by cfriedt — DISMISSED** [review]

**Comment by XenuIsWatching** [comment]
> @XenuIsWatching will you be coming back to this PR? (also note the trivial compliance error)

if I ever can find a way to fix the compliance error as well as fix the real issue... right now it seems to be one or the other, I just having figured out a way to solve both

**Review by cfriedt — APPROVED** [review]
@peter-mitsis - PTAL

**Review by peter-mitsis — APPROVED** [review]
