### PR TITLE
tests: drivers: counter: Fix test for nrf52 platform

### LINKED ISSUE #13254: tests/drivers/counter/counter_basic_api: counter failed to raise alarm after ticks limit reached
**Describe the bug**
test_single_shot_alarm_top() reports that there was no alarm  despite ticks exceeded limits

**To Reproduce**
1. Modify src/test_counter.c to disable all tests except test_single_shot_alarm_top() in test_main(). This modification is to avoid you being distracted by an assertion error in test_multiple_alarms() and  "kernel panic" message.
2. mkdir build; cd build
3. cmake -GNinja  -DBOARD=nrf52_pca10040 -DARCH=arm #nrf52_pca10040
4. ninja
5. ninja run

Replace (3) with
cmake -GNinja -DBOARD=nrf51_pca10028 -DARCH=arm for nrf51_pca10028
cmake -GNinja -DBOARD=nrf52840_pca10056 -DARCH=arm for nrf52840_pca10056

**Screenshots or console output**
For nrf52_pca10040:
```
===================================================================
starting test - test_single_shot_alarm_top
    Assertion failed at /path/to/zephyr.git/tests/drivers/counter/counter_basic_api/src/test_counter.c:196: test_single_shot_alarm_instance: (-E
INVAL not equal to err)
Counter should return error because ticks exceeded the limit set alarm
FAIL - test_single_shot_alarm_top
===================================================================
```

For nrf51_pca10028:
```
Running test suite test_counter
===================================================================
starting test - test_single_shot_alarm_top
    Assertion failed at /path/to/tests/zephyr.git/tests/drivers/counter/counter_basic_api/src/test_counter.c:196: test_single_shot_alarm_instance: (-EINVAL not equal to err)
Counter should return error because ticks exceeded the limit set alarm
FAIL - test_single_shot_alarm_top
===================================================================
```

For nrf52840_pca10056:
```
starting test - test_single_shot_alarm_top
    Assertion failed at /path/to/tests/zephyr.git/tests/drivers/counter/counter_basic_api/src/test_counter.c:196: test_single_shot_alarm_instance: (-E
INVAL not equal to err)
Counter should return error because ticks exceeded the limit set alarm
FAIL - test_single_shot_alarm_top
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain : Zephyr
 - Commit SHA or Version used: 012d40412568201f975dd0356e1e3fbf9e8aad73

**Additional context**

### PR DESCRIPTION
**Pull request by nordic-krch**
Fix failing tests.

Tests were failing because:
1. `alarm_cnt` was not reset before the test.
2. one test was failing because it was expecting that setting `top_value` for channel_alarm is too much but in fact `top_value+1` is too much.

Fixes #13254.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by nordic-krch** [comment]
fyi @cinlyooi-intel

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 1]
```diff
@@ -92,6 +92,8 @@ static void counter_tear_down_instance(const char *dev_name)
 
 	err = counter_stop(dev);
 	zassert_equal(0, err, "Counter failed to stop\n");
+
+	alarm_cnt = 0;
```
Comment (anangl) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: This should be done in `test_all_channels_instance` where it is actually needed. Doing it here is obscure.

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 2]
```diff
@@ -190,6 +192,7 @@ void test_single_shot_alarm_instance(const char *dev_name, bool set_top)
 
 		zassert_equal(0, err, "Counter failed to set top value\n");
 
+		alarm_cfg.ticks = ticks + 1;
```
Comment (anangl) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: This is not directly related but why is the number of ticks decreased by 100 in line [200](https://github.com/zephyrproject-rtos/zephyr/pull/13305/files#diff-cbfda9aaae5d9069931b177bfff91d59R200)? This happens only when the top value is modified. Is this intentional? Maybe a word of comment could help there?

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 3]
```diff
@@ -323,23 +326,22 @@ void test_all_channels_instance(const char *str)
 	const int n = 10;
 	int nchan = 0;
 	bool limit_reached = false;
-	struct counter_alarm_cfg alarm_cfgs[n];
+	struct counter_alarm_cfg alarm_cfgs;
```
Comment (anangl) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: The changes in this function do not seem to be related to a failing test. This is more refactoring, so I think it should be done in a separate commit (lines [209-210](https://github.com/zephyrproject-rtos/zephyr/pull/13305/files#diff-cbfda9aaae5d9069931b177bfff91d59R209) could be also removed in it, since they are a duplicate that probably popped up during some merging).

**Review by anangl — CHANGES_REQUESTED** [review]
The commit description needs to be improved. Currently it is not clear what was failing (it is mentioned only in the PR description). And the fix affects all platforms (the test case is common), not only the nrf52 one, so I think the commit title may be a bit misleading.

**Comment by nordic-krch** [comment]
@anangl splitted work into 2 commits, reworked commit message and applied your suggestions.

**Review by anangl — APPROVED** [review]
Since you decided to use `counter_setup_instance` for clearing the count of alarms, it would be good to remove redundant now clearings of this count in lines [183](https://github.com/zephyrproject-rtos/zephyr/blob/20a379448908655f698bb97c5f74d13f3d2674e2/tests/drivers/counter/counter_basic_api/src/test_counter.c#L183) and [285](https://github.com/zephyrproject-rtos/zephyr/blob/20a379448908655f698bb97c5f74d13f3d2674e2/tests/drivers/counter/counter_basic_api/src/test_counter.c#L285). It's not a blocker though.

**Review by nashif — APPROVED** [review]
