### PR TITLE
drivers: sensor: bmp180 fix unintentional integer overflow issue

### LINKED ISSUE #81988: [Coverity CID: 434515] Unintentional integer overflow in drivers/sensor/bosch/bmp180/bmp180.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/drivers/sensor/bosch/bmp180/bmp180.c

Category: Integer handling issues
Function: `bmp180_compensate_press`
Component: Drivers
CID: [434515](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434515)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/drivers/sensor/bosch/bmp180/bmp180.c#L330

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434515

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_OVERFLOW_BEFORE_WIDEN). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by jilaypandya**
cast partial_x3 explicitly to uint64_t to circumvent unintentioanl integer overflow coverity issue

### CODE REVIEW

File: drivers/sensor/bosch/bmp180/bmp180.c [hunk 1]
```diff
@@ -327,7 +327,7 @@ static uint32_t bmp180_compensate_press(struct bmp180_data *data)
 	partial_X1 = (cal->ac3 * partial_B6) / 0x2000;
 	partial_X2 = cal->b1 * partial_B6 * (float)(1.0f * partial_B6 / 0x8000000);
 	partial_X3 = (partial_X1 + partial_X2 + 2) / 4;
-	partial_B4 = (uint64_t)(cal->ac4 * (partial_X3 + 32768)) / 0x8000;
+	partial_B4 = (uint64_t)(cal->ac4 * ((int64_t)(partial_X3) + 32768)) >> 15;
```
Comment (faxe1008) [inline drivers/sensor/bosch/bmp180/bmp180.c:330]: Kinda odd to have the shifting but everywhere else to still perform division. Just a thought :^)

**Review by faxe1008 — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
