### PR TITLE
openamp: resource table: fixes resource table to work with ram_console section

### LINKED ISSUE #75656: ram_console buffer pointer is incompatible with openamp trace log
The ram_console buffer used to be a global variable (array), now it's a pointer to an array. The problem with this is, that the lib/open-amp/resource_table.c directly uses this pointer for its resource table and the openamp host can't handle it.

My suggestion would be that, instead of using the global variable `ram_console`, implement a `ram_console_get_buffer` function and use that in rsc_table_get to complete the resource table.

### PR DESCRIPTION
**Pull request by mausys**
in commit 1cd37f21f3a the global ram console buffer was replaced with a pointer. This didn't work with the OpenAMP resource table anymore (#75656). This commit removes also the unnecessary console buffer, if a ram console device tree node is configured.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/75656

### CODE REVIEW

**Comment by carlocaione** [comment]
Hi @mausys can you make sure that the CI is all green?

**Comment by mausys** [comment]
This change is also included in #79605

**Comment by mmahadevan108** [comment]
cc @alxlastur @Zhiqiang-Hou
Can you also please help review this PR

File: lib/open-amp/resource_table.c [hunk 1]
```diff
@@ -29,7 +29,18 @@
...
-extern char ram_console[];
+#ifdef CONFIG_RAM_CONSOLE_BUFFER_SECTION
+#if DT_HAS_CHOSEN(zephyr_ram_console)
+
+static const uint32_t ram_console_buf = DT_REG_ADDR(DT_CHOSEN(zephyr_ram_console));
+
+#else
+#error "Lack of chosen property zephyr,ram_console!"
+#endif
+
```
Comment (mmahadevan108) [inline lib/open-amp/resource_table.c:40]: Is'nt it sufficient to just use the extern to get the already defined `ram_console_buf`. This has the `RAM_CONOLE_BUF_ATTR` defined for it which should place it in the appropriate RAM section.

Comment (mausys) [reply lib/open-amp/resource_table.c:40]: The ram_console_buf in ram_console.c is only used when CONFIG_RAM_CONSOLE_BUFFER_SECTION is disabled. That's why I changed it in ram_console.c to not wasting memory.

File: drivers/console/ram_console.c [hunk 2]
```diff
@@ -29,7 +29,10 @@
 #define RAM_CONSOLE_BUF_ATTR
 #endif
 
+#ifndef CONFIG_RAM_CONSOLE_BUFFER_SECTION
 char ram_console_buf[CONFIG_RAM_CONSOLE_BUFFER_SIZE] RAM_CONSOLE_BUF_ATTR;
+#endif
+
```
Comment (Zhiqiang-Hou) [inline drivers/console/ram_console.c:35]: revert this and directly use `extern char ram_console_buf[];` in lib/open-amp/resource_table.c.

**Comment by mmahadevan108** [comment]
@carlocaione, can you help review this again.

**Review by Zhiqiang-Hou — APPROVED** [review]

**Review by alxlastur — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@carlocaione , can you help take a look. This bug fix can be included in 4.0 release

**Review by nashif — APPROVED** [review]
