### PR TITLE
DT: missing phandle-array entries fix

### LINKED ISSUE #30846: devicetree: unspecified phandle-array elements cause errors
**Describe the bug**
As shown in https://github.com/torvalds/linux/blob/master/include/linux/of_gpio.h#L82, a `0` cell in a phandle array should be treated as an unspecified element.

In zephyr, edtlib chokes on this with the following error:

```
devicetree error: bad phandle in <Property ...>
```

**To Reproduce**
1. Add a 0 cell in a phandle-array to the devicetree
2. `west build --cmake-only` any application of your choice with that devicetree
3. see above error

**Expected behavior**
This should work. The macros generated for that index should clearly show there's nothing there. The length of the array should reflect the unspecified element.

**Impact**
Blocks an option for converting to phandle-array in https://github.com/zephyrproject-rtos/zephyr/pull/30262.

**Environment (please complete the following information):**
 - OS: all
 - Toolchain: all
 - Commit: ae35d3000f

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
Fixes: #30846 

The DTS language permits zeroing out phandles in a phandle array to say "there's nothing at this index", and dtlib manages that correctly, but edtlib and gen_defines.py aren't equipped to do so.

Fix this by allowing None elements in the lists of `ControllerAndData` values returned by edtlib for such properties.

Handle that in gen_defines.py by setting the generated `DT_N_<node>_P_<prop>_IDX_<i>_EXISTS` macro to 0 in such cases.

The `DT_N_<node>_P_<prop>_LEN` macro still accounts for the entire length of the phandle-array; it's just that some indexes may be missing data.

This series starts with a couple of cleanup commits.

### CODE REVIEW

**Review by pabigot — APPROVED** [review]
Thanks, I think this will be very useful.

File: tests/lib/devicetree/api/src/main.c [hunk 1]
```diff
@@ -702,15 +702,25 @@ static void test_phandles(void)
...
+	zassert_false(DT_PHA_HAS_CELL_AT_IDX(TEST_PH, pha_gpios, 1, pin),
+		      "has pha-gpio 0 pin");
 	zassert_false(DT_PHA_HAS_CELL_AT_IDX(TEST_PH, pha_gpios, 1, flags),
-		      "no pha-gpio 1 flags");
+		      "has pha-gpio 0 flags");
+	/* index 2 only has pin, no flags */
 	zassert_true(DT_PHA_HAS_CELL_AT_IDX(TEST_PH, pha_gpios, 2, pin),
+		      "no pha-gpio 1 pin");
+	zassert_false(DT_PHA_HAS_CELL_AT_IDX(TEST_PH, pha_gpios, 2, flags),
+		      "no pha-gpio 1 flags");
```
Comment (anangl) [inline tests/lib/devicetree/api/src/main.c:716]: Several messages in the assertions here are quite confusing and misleading. For example, the above two should refer to index 2 and one of them should say "has" instead of "no", but actually I'm not sure which one, as I'm not sure if those messages are intended to say what was expected or what turned out to be incorrect.

File: scripts/dts/edtlib.py [hunk 2]
```diff
@@ -2129,11 +2138,15 @@ def _add_names(node, names_ident, objs):
                  .format(full_names_ident, node.path, node.dt.filename,
                          len(names), len(objs)))
 
-        for obj, name in zip(objs, names):
+        for item in zip(objs, names):
+            if item is None:
```
Comment (mbolivar-nordic) [inline scripts/dts/edtlib.py:2142]: Hm, I think this change is wrong, actually. I will add a test case covering this.

Comment (mbolivar-nordic) [reply scripts/dts/edtlib.py]: >  I think this change is wrong, actually. I will add a test case covering this.

fixed

File: tests/lib/devicetree/api/src/main.c (hunk 1 above)
Comment (mbolivar-nordic) [reply tests/lib/devicetree/api/src/main.c]: > Several messages in the assertions here are quite confusing and misleading.

You know, you're totally right. I think most of the assertions in this file are easy enough to read on their own, so I've added a cleanup commit at the beginning of the series that removes the ones that add nothing, or worse are actively confusing.

Thanks.

**Review by anangl — APPROVED** [review]

**Review by galak — APPROVED** [review]
