### PR TITLE
drivers: nxp_s32_canxl: add CANXL MRU handler

### LINKED ISSUE #75022: NXP S32 CANXL driver is missing CANXL MRU handler, CANXL errors is not reported
NXP S32 CANXL driver is missing CANXL MRU handler, CANXL error is not reported

**Describe the bug**
In HAL driver NXP S32 RTD, it supplies APIs and error handler that statistic CAN errors and count CAN TX and RX errors via BCANXL, uses CANXL MRU to exchange information with CAN host to get errors report.

But current implementation handler of NXP S32 CANXL driver is missing CANXL MRU handler.

**To Reproduce**
Run [samples/net/socket/can](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/net/sockets/can) in normal mode and CAN bus is disconnected. The log error is expected to see. 

Result: just see CAN sending frames but not see any errors print in console
image

The flow error handling when error interrupts happen: error handler is called -> execute Canexcel_GetControllerMRU() and verify status -> If status OK, errors is reported, error callbacks is call else no error reported.

See function Canexcel_GetControllerMRU() will enable CANXL MRU and send a msg MRU to get error report then expect a CANXL MRU interrupt trigger, call MRU handler to return status OK for get error report sucessfully.
Because of missing CANXL MRU handler, Canexcel_GetControllerMRU() return TIMEOUT, so error callbacks are not called.

Canexcel_GetControllerMRU() return TIMEOUT
image
image

**Expected behavior**
CANXL Errors is reported and printed in console.
image

**Impact**
CANXL errors is not reported. No console error is printed.

**Logs and console output**
See above captures

**Environment (please complete the following information):**
OS: Linux
Toolchain Zephyr SDK
Commit SHA or Version used 7f8cc43

**Additional context**
NA

### PR DESCRIPTION
**Pull request by congnguyenhuu**
Add CANXL MRU handler, use the same IRQ number as RX, TX interrupt. Update the error priority that is lower priority than the the tx_rx_mru priority incase the error interrupt happens continuously, mru interrupt priority must be higher to get report error counter. Otherwise the mru interrupt can be delayed by error interrupt and never call to MRU handler. This fixes #75022.

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
> Add CANXL MRU handler, use the same RX, TX IRQ number. Update the error priority that is lower priority than the the tx_rx_mru priority incase the error interrupt happens continuously, mru interrupt priority must be higher to get report error counter. Otherwise the mru interrupt can be delayed by error interrupt and never call to MRU handler. This fixes #75022.

This is a bug fix. 

> Additionally, enable CANXL_INT_RXSMB_OVER and CAN_INT_ERR_FAST(ERR for CAN-FD). Statistic CAN errors and count CAN TX and RX errors via BCANXL that uses CANXL MRU to exchange informations with CAN host.

This is a feature addition. 

Please split this in at least two commits, preferably two PRs. We only accept bug fixes for v3.7.0 currently, so a PR combining a bug fix with a feature addition cannot go in.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Please split this as described above.

**Comment by congnguyenhuu** [comment]
> Please split this as described above.

I separated this to 2 PRs. this PR only includes change for bug fix now

File: drivers/can/can_nxp_s32_canxl.c [hunk 1]
```diff
@@ -1003,11 +1004,16 @@ static int can_nxp_s32_init(const struct device *dev)
...
 }
 
-static void can_nxp_s32_isr_rx_tx(const struct device *dev)
+static void can_nxp_s32_isr_rx_tx_mru(const struct device *dev)
 {
 	const struct can_nxp_s32_config *config = dev->config;
 
 	Canexcel_Ip_RxTxIRQHandler(config->instance);
+
+	if ((config->base_mru->CHXCONFIG[0u].CH_CFG0 & CANXL_MRU_CH_CFG0_CHE_MASK)
```
Comment (manuargue) [inline drivers/can/can_nxp_s32_canxl.c:1013]: Where is this MRU channel enabled?

Comment (manuargue) [reply drivers/can/can_nxp_s32_canxl.c:1013]: Nevermind, I see you already detailed this in the issue description.

**Review by manuargue — APPROVED** [review]
No objections from my side

**Review by henrikbrixandersen — APPROVED** [review]

**Review by Dat-NguyenDuy — APPROVED** [review]

**Review by str4t0m — APPROVED** [review]

**Review by bperseghetti — APPROVED** [review]
