### PR TITLE
tests: stackprot: add guard area to ensure portable overflow behavior

### LINKED ISSUE #95060: tests/kernel/mem_protect/stackprot: test_create_alt_thread fails on ARC nsim_em due to MPU exception at thread stack boundary
### Describe the bug

On ARC `nsim_em` with MetaWare toolchain, the test `kernel.memory_protection.stackprot` fails in the second case (`test_create_alt_thread`). Instead of raising the expected stack overflow (`K_ERR_STACK_CHK_FAIL`), it triggers an MPU protection exception.

**Observed behavior:**

* `check_input()` copies a long string into `buf[16]` to force overflow.
* The test assumes the overflow will stay inside the thread stack and trip stack protection.
* On ARC `nsim_em`, the combined stack usage (`alternate_thread` frame + `check_input` frame + `buf[16]`) is slightly smaller than the string length (string\_size – 4) https://github.com/zephyrproject-rtos/zephyr/blob/e0fcfa1be9e0806635826af4ca79da416cb474a1/tests/kernel/mem_protect/stackprot/src/main.c#L89-L90.
* This causes the last 4 bytes to spill past the end of the thread stack at `0x80003800` into the next MPU-protected region.
* The MPU then raises `EV_ProtV` (“Memory write protection violation”) instead of the expected stack overflow trap.

**Evidence:**

* `buf` starts at `0x800037d4`, thread stack ends at `0x80003800`.
* Map file confirms `alt_thread_stack_area` ends at the faulting address.
* Removing 4 characters from the string or enlarging `buf` to 20 bytes keeps the overflow within the thread stack, and the test passes.

**Root cause:**
The test depends on **compiler stack frame layout**.
If `(caller frame + callee frame + buf)` < string length, the overflow escapes the thread stack; if it’s larger, the overflow stays contained. 
**This makes the test non-portable across toolchains and architectures.**

### Regression

- [ ] This is a regression.

### Steps to reproduce

Use ARCMWDT toolchain
`west build -b nsim/nsim_em tests/kernel/mem_protect/stackprot -T kernel.memory_protection.stackprot`

### Relevant log output

```shell
Running TESTSUITE stackprot 
=================================================================== 
START - test_canary_value 
Starts alternate_thread_canary 
PASS - test_canary_value in 0.107 seconds 
=================================================================== 
START - test_create_alt_thread 
Starts alternate_thread 
E: ***** Exception vector: 0x6, cause code: 0x2, parameter 0x4 
E: Address 0x80003800 
E: EV_ProtV 
E: Memory write protection violation (MPU) 
E: r0: 0x800037d4 r1: 0xd076 r2: 0x80003800 r3: 0x64 
E: r4: 0x0 r5: 0x0 r6: 0x56 r7: 0x0 
E: r8: 0x0 r9: 0x0 r10: 0x0 r11: 0x0 
E: r12: 0x4 r13: 0xd19f pc: 0x39ec 
E: blink: 0x72c status32: 0x80186886 
E: lp_end: 0x3970 lp_start: 0x396c lp_count: 0x0 
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0 
E: Current thread: 0x80001850 (unknown) wrong error type
 =================================================================== 
PROJECT EXECUTION FAILED
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

OS: Linux
Toolchain (e.g Zephyr SDK, ...): arcmwdt
Commit SHA or Version used: Main e0fcfa1be9e0806635826af4ca79da416cb474a1

### Additional Context

**Proposed fix:**
Make the test independent of frame layout by ensuring overflows always hit memory within the thread stack:
Add a padding array in the caller (**alternate_thread**) so the intentional overflow first clobbers this controlled region before reaching the MPU boundary.

### PR DESCRIPTION
**Pull request by M-Moawad**
The stackprot test currently depends on compiler-generated stack frame layouts, which can vary between toolchains and optimization levels. This makes the overflow check fragile and may cause unintended faults.

Add a small guard buffer in alternate_thread so the intentional overflow is always contained within the thread stack. This ensures the test behaves consistently across toolchains, architectures, and optimization settings.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/95060

### CODE REVIEW

**Comment by M-Moawad** [comment]
@ceolin @dcpleung Could you take a look at the issue https://github.com/zephyrproject-rtos/zephyr/issues/95060 and this PR?

File: tests/kernel/mem_protect/stackprot/src/main.c [hunk 1]
```diff
@@ -84,6 +84,13 @@ void alternate_thread(void *p1, void *p2, void *p3)
 	ARG_UNUSED(p1);
 	ARG_UNUSED(p2);
 	ARG_UNUSED(p3);
+	/*
+	 * Padding buffer to absorb the intentional overflow inside the thread stack.
+	 * This prevents writes from crossing the thread stack boundary into the next
+	 * MPU-protected region. Required to make the test independent of compiler-
+	 * specific stack frame layouts.
+	 */
+	volatile char overflow_guard_area[32] = "Forcing Initialization!";
```
Comment (dcpleung) [inline tests/kernel/mem_protect/stackprot/src/main.c]: Might need to make this `__used` so compiler won't complain about this not being used.

Comment (M-Moawad) [reply tests/kernel/mem_protect/stackprot/src/main.c]: Using `__used` gives the following warning:

```bash
zephyr/tests/kernel/mem_protect/stackprot/src/main.c:87:11: warning: '__used__' attribute only applies to variables with non-local storage, functions, and Objective-C methods [-Wignored-attributes]
   87 |         volatile __used char overflow_guard_area[32] = "Forcing Initialization!";
      |                  ^
zephyr/include/zephyr/toolchain/gcc.h:278:32: note: expanded from macro '__used'
  278 | #define __used          __attribute__((__used__))
      |                                        ^
1 warning generated.

```

Comment (dcpleung) [reply tests/kernel/mem_protect/stackprot/src/main.c]: Hm... let's hope that compilers (other than those in Zephyr SDK) are not going to complain about it not being used.

**Review by dcpleung — DISMISSED** [review]

**Comment by M-Moawad** [comment]
@cfriedt Could you review this fix and the related issue?

**Review by cfriedt — DISMISSED** [review]

File: tests/kernel/mem_protect/stackprot/src/main.c (hunk 1 above)
Comment (M-Moawad) [reply tests/kernel/mem_protect/stackprot/src/main.c]: Using `__unused` makes both Zephyr SDK and ARCMWDT happy!

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]
