### PR TITLE
logging: Refactor RTT backend to handle host absence

### LINKED ISSUE #12051: LOG_PANIC never returns if RTT is disconnected
**Describe the bug**
When RTT is connected LOG_PANIC ends at some point. When RTT is disconnected it does not.

**To Reproduce**
Use LOG_PANIC with JLink disconnected.

**Expected behavior**
LOG_PANIC should never lock.

**Impact**
LOG_PANIC deadlocks so application cannot finish its activities.

**Environment (please complete the following information):**
- rev `5ea8454e46208ab3fd7006e98b47ca15d5c7a450`

### PR DESCRIPTION
**Pull request by nordic-krch**
Refactored blocking operation of RTT backend. Log_output buffer
is used directly in case of blocking operation. Detection of
host presence added. Prevent use of RTT lock when in panic mode.
Removed pending on data being read by the host on every message.

Refactor gives savings of 300 bytes in ROM and 120 bytes in RAM.

Fixes #12051.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by nordic-krch** [comment]
fyi @pkral78

**Review by pdunaj — APPROVED** [review]
It looks ok. Small style issues.

File: subsys/logging/Kconfig [hunk 1]
```diff
@@ -330,18 +330,45 @@ config LOG_BACKEND_RTT_MODE_DROP
...
+config LOG_BACKEND_RTT_RETRY_CNT
+	int "Number of retries"
+	default 2
+	help
+	  Number of TX retries before dropping the data and assuming that
+	  RTT session is inactive.
+
+config LOG_BACKEND_RTT_RETRY_DELAY_MS
+	int "Delay between TX retries in milliseconds"
+	default 2
```
Comment (pizi-nordic) [inline subsys/logging/Kconfig]: I suggest increasing this value. Sometimes the RTT could be polled only teen times per second.

File: subsys/logging/Kconfig [hunk 2]
```diff
@@ -330,18 +330,45 @@ config LOG_BACKEND_RTT_MODE_DROP
...
+	help
+	  Sleep period between TX retry attempts. During RTT session, host pulls
+	  data periodically. Period starts from 1-2 milliseconds and can be
+	  increased if traffic on RTT increases (also from host to device). In
+	  case of heavy traffic data can be lost and it may be necessary to
```
Comment (pizi-nordic) [inline subsys/logging/Kconfig]: to do what?

File: subsys/logging/Kconfig [hunk 3]
```diff
@@ -330,18 +330,45 @@ config LOG_BACKEND_RTT_MODE_DROP
...
 	default 128
 	help
 	  This option defines maximum message size transferable to up-buffer.
 
+endif #LOG_BACKEND_RTT_MODE_DROP
+
+if LOG_BACKEND_RTT_MODE_BLOCK
+
+config LOG_BACKEND_RTT_BUFFER_SIZE
+	int "Size of the output buffer"
```
Comment (pizi-nordic) [inline subsys/logging/Kconfig]: This is not the RTT buffer? Please clarify.

File: subsys/logging/log_backend_rtt.c [hunk 4]
```diff
@@ -16,12 +16,18 @@
 
 #define DROP_MSG "\nmessages dropped:    \r"
 #define DROP_MSG_LEN (sizeof(DROP_MSG) - 1)
-
+#define MESSAGE_SIZE CONFIG_LOG_BACKEND_RTT_MESSAGE_SIZE
+#define CHAR_BUF_SIZE 1
+#define RETRY_DELAY_MS 10 /* Long enough to detect host presence */
```
Comment (pizi-nordic) [inline subsys/logging/log_backend_rtt.c]: Doesn't we have Kconfig options for that?
(`LOG_BACKEND_RTT_RETRY_CNT` and `LOG_BACKEND_RTT_RETRY_DELAY_MS`)

File: subsys/logging/log_backend_rtt.c [hunk 5]
```diff
@@ -139,45 +138,59 @@ static int log_backend_rtt_write_drop(void)
...
-					 length);
-	log_backend_rtt_flush();
-	return written;
-}
+	do {
+		if (!panic_mode) {
+			RTT_LOCK();
+		}
+
+		ret = SEGGER_RTT_WriteSkipNoLock(CONFIG_LOG_BACKEND_RTT_BUFFER,
```
Comment (pizi-nordic) [inline subsys/logging/log_backend_rtt.c]: What if `panic_mode` changes during call to SEEGER?

File: subsys/logging/log_backend_rtt.c [hunk 6]
```diff
@@ -139,45 +138,59 @@ static int log_backend_rtt_write_drop(void)
...
+static void on_failed_write(int retry_cnt)
 {
-	if (IS_ENABLED(CONFIG_LOG_BACKEND_RTT_MODE_BLOCK)) {
-		return log_backend_rtt_write_block();
-	} else if (IS_ENABLED(CONFIG_LOG_BACKEND_RTT_MODE_DROP)) {
-		return log_backend_rtt_write_drop();
+	if (retry_cnt == 0) {
+		host_present = false;
+	} else if (panic_mode) {
+		k_busy_wait(1000*RETRY_DELAY_MS);
```
Comment (pizi-nordic) [inline subsys/logging/log_backend_rtt.c]: USEC_PER_MSEC * ...

**Review by pizi-nordic — CHANGES_REQUESTED** [review]

File: subsys/logging/log_backend_rtt.c (hunk 5 above)
Comment (nordic-krch) [reply subsys/logging/log_backend_rtt.c]: if call is interrupted by panic it will not return here.

File: subsys/logging/log_backend_rtt.c (hunk 4 above)
Comment (nordic-krch) [reply subsys/logging/log_backend_rtt.c]: those options are present only in blocking mode. In drop mode, in normal operation they are not used because data is dropped when no room (that covers disconnected host case). In drop mode, it will only do blocking write in panic and those settings are for this case. I didn't want to spoil kconfig. If user picks drop mode then it's confusing to set also retry timeout.

File: subsys/logging/Kconfig (hunk 1 above)
Comment (nordic-krch) [reply subsys/logging/Kconfig]: increased to 4(retry) and 5(delay)

File: subsys/logging/Kconfig (hunk 2 above)
Comment (nordic-krch) [reply subsys/logging/Kconfig]: returned what was swallowed

File: subsys/logging/Kconfig (hunk 3 above)
Comment (nordic-krch) [reply subsys/logging/Kconfig]: added help, renamed to `LOG_BACKEND_RTT_OUTPUT_BUFFER_SIZE`

File: subsys/logging/log_backend_rtt.c (hunk 6 above)
Comment (nordic-krch) [reply subsys/logging/log_backend_rtt.c]: done

File: subsys/logging/log_backend_rtt.c [hunk 7]
```diff
@@ -40,49 +46,43 @@
...
 
-static int msg_out(u8_t *data, size_t length, void *ctx);
-
-static int line_out(u8_t data);
-
-static void log_backend_rtt_flush(void);
+static bool host_present;
 
-static int log_backend_rtt_write(void);
+static int data_out_block_mode(u8_t *data, size_t length, void *ctx);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply subsys/logging/log_backend_rtt.c]: cannot do it right now as functions must comply with `log_output_func_t` prototype. Prototype should be fixed (different PR).

**Comment by pkral78** [comment]
> fyi @pkral78

LGTM

File: subsys/logging/log_backend_rtt.c (hunk 5 above)
Comment (pizi-nordic) [reply subsys/logging/log_backend_rtt.c]: As far as I remember, @andrewboie suggested, that we should disabled panic if we entered recoverable fault (thread is terminated, but system is operational). Shouldn't we take under consideration such mode of operation?

Comment (nordic-krch) [reply subsys/logging/log_backend_rtt.c]: if we are entering recoverable fault we shouldn't enter panic. If we enter today then it's a bug. Panic should be used only for nonrecoverable situations.

Comment (pizi-nordic) [reply subsys/logging/log_backend_rtt.c]: OK

**Review by pizi-nordic — APPROVED** [review]

File: subsys/logging/Kconfig [hunk 8]
```diff
@@ -330,18 +330,49 @@ config LOG_BACKEND_RTT_MODE_DROP
...
-	  and until the message is completely transferred to the host.
+	  Waits until there is enough space in the up-buffer for a message.
 
 endchoice
 
+if LOG_BACKEND_RTT_MODE_DROP
+
 config LOG_BACKEND_RTT_MESSAGE_SIZE
 	int "Size of internal buffer for storing messages."
 	range 32 256
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply subsys/logging/Kconfig]: i wanted to keep it consistent with LOG_BACKEND_RTT_MODE_BLOCK which has more options.

**Review by jakub-uC — APPROVED** [review]
