### PR TITLE
samples: canbus: isotp: add missing call to can_start()

### LINKED ISSUE #54078: No activity on can_tx when running the ISO-TP sample
**Describe the bug**
No activity on can_tx when running the isotp sample.

**To Reproduce**
1. mkdir /tmp/isotp-bug &&  cd /tmp/isotp-bug
3. west init .
4. west update
5. cd zephyr
6. west build --pristine -b nucleo_f303re samples/subsys/canbus/isotp
7. sudo west flash
8. observe can_tx with oscilloscope

**Expected behavior**
Sample should function as described, and activity should be observable on the can_tx pin.

**Impact**
Sample intended to demonstrate setup and use of ISO-TP on the CAN bus does not correctly do so, making it difficult to determine how to use it in a real project.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Docker Image zephyrprojectrtos/zephyr-build
 - Version: v0.24.9-amd64

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add missing call to can_start().

Fixes: #54078

Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>

### CODE REVIEW

**Review by martinjaeger — DISMISSED** [review]
Thanks!

**Review by str4t0m — DISMISSED** [review]

File: samples/subsys/canbus/isotp/src/main.c [hunk 1]
```diff
@@ -154,6 +154,11 @@ void main(void)
 		return;
 	}
 
+	ret = can_start(can_dev);
+	if (ret != 0) {
+		printk("CAN: Failed to start device [%d]\n", ret);
```
Comment (gmarull) [inline samples/subsys/canbus/isotp/src/main.c:159]:
```suggestion
		printk("CAN: Failed to start device [%d]\n", ret);
		return;
```
?

Comment (henrikbrixandersen) [reply samples/subsys/canbus/isotp/src/main.c:159]: Gah, thanks.

**Review by gmarull — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Review by str4t0m — APPROVED** [review]
