### PR TITLE
net: lwm2m: Fix Invalid ACK when server is using message ID 0 

### LINKED ISSUE #28283: LWM2M: Invalid ACK when server is using message ID 0
When a LWM2M server is sending a confirmable CoAP packet with message ID 0, the ACK packet from the zephyr is using another message id (due to special semantics of 0 in the client to request generation of a new id, see #28281).
As a result, the ACK is ignored by the LWM2M server and the confirmable CoAP packet is retransmitted.

**To Reproduce**
1. Start LWM2M bootstrap server that start with message id 0 for each client
2. Start zephyr bootstrap client
3. Zephyr send initial bootstrap request with mid=X
4. LWM2M send bootstrap ACK with mid=X
5. LWM2M sends DELETE / request to zephyr with mid=0
6. zephyr sends ACK with mid=X+1

**Expected behavior**
Step 6: zephyr sends ACK with mid=0

**Impact**
Could lead to various unexpected behavior every time the server uses message id 0 due to multipel retransmission by the server. A similar issue is present if a CoAP token is 0 or 0xFF.

### PR DESCRIPTION
**Pull request by broglep-work**
Fixes #28283 based on #28281

### CODE REVIEW

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 1]
```diff
@@ -939,7 +939,7 @@ int lwm2m_init_message(struct lwm2m_message *msg)
 	 * msg->tkl == 0 is for a new TOKEN
 	 * msg->tkl == LWM2M_MSG_TOKEN_LEN_SKIP means dont set
 	 */
-	if (msg->tkl == 0U) {
+	if (msg->tkl == LWM2M_MSG_TOKEN_GENERATE_NEW) {
 		tokenlen = 0U;
```
Comment (rlubos) [inline subsys/net/lib/lwm2m/lwm2m_engine.c:943]: Looking at this line, I already see that token handling in the lwm2m library also needs an inspection. On one hand, we generate a token, on the other `tokenlen` is set to 0. As a result, we don't send a token anyway... (just confirmed in wireshark)

Comment (rlubos) [reply subsys/net/lib/lwm2m/lwm2m_engine.c:943]: Yes, I didn't mean to have this fixed in this PR. I'll create a separate issue for token handling improvement.

**Review by rlubos — COMMENTED** [review]
Looks good, but please squash the commits into one or possibly two (one with token length change, other with message id fix).

**Review by rlubos — APPROVED** [review]

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 2]
```diff
@@ -948,8 +948,7 @@ int lwm2m_init_message(struct lwm2m_message *msg)
 	}
```
Comment (jukkar) [inline subsys/net/lib/lwm2m/lwm2m_engine.c:948]: Please change the commit message so that the "fixes" line is not part of the description. Usually we have first commit description, followed an empty line, then the "Fixes #xxxxx" line, followed an empty line and then the signed-off.

Do we really need first to introduce some change, and then removing that change in the next commit. Looks like we could just squash these changes together.

Comment (broglep-work) [reply subsys/net/lib/lwm2m/lwm2m_engine.c:948]: @jukkar the first commit's scope is bigger. It introduces an improvement to both message id as well as token generation. The second commit is the actual fix for the message id generation only. Thus squashing them together does not make sense. 

The first commit is also available as its separate pull request #28281. if you prefer to separate the concerns, I'm open to rebase this pull request should you decide to merge the other first.

Comment (jukkar) [reply subsys/net/lib/lwm2m/lwm2m_engine.c:948]: No need to separate the commits, it was just looking a bit unnecessary to first introduce a change, and then next commit would change the previous commit again.

**Review by jukkar — APPROVED** [review]

**Comment by MaureenHelm** [comment]
Please rebase to pick up a fix for the failed check
