### PR TITLE
net: lwm2m: dont use system workqueue for services

### LINKED ISSUE #15204: lwm2m engine hangs on native_posix
**Describe the bug**
When running the LwM2M engine, the application gets into an infinite loop and does not respond anymore on native_posix. This happens on my machine after 188 seconds.
When setting CONFIG_NATIVE_POSIX_SLOWDOWN_TO_REAL_TIME=n, the hang also occurs after 188 seconds simulated time.

**To Reproduce**
1. cd samples/net/lwm2m_client
2. mkdir build; cd build
3. cmake -GNinja -DBOARD=native_posix ..
4. ninja run
5. after 3 min the application does not respond anymore and consumes 100% cpu

**Expected behavior**
The application should continue to run normally.

**Impact**
LwM2M cannot be used on native_posix.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK
 - Version: v1.14.0-rc3

**Possible fix**
```
diff --git a/subsys/net/lib/lwm2m/lwm2m_engine.c b/subsys/net/lib/lwm2m/lwm2m_engine.c
index c38fd787ee..28397e732b 100644
--- a/subsys/net/lib/lwm2m/lwm2m_engine.c
+++ b/subsys/net/lib/lwm2m/lwm2m_engine.c
@@ -3808,7 +3808,7 @@ static void lwm2m_engine_service(struct k_work *work)
                service_due_timestamp = srv->last_timestamp +
                                        K_MSEC(srv->min_call_period);
                /* service is due */
-               if (timestamp > service_due_timestamp) {
+               if (timestamp >= service_due_timestamp) {
                        srv->last_timestamp = k_uptime_get();
                        k_work_submit(&srv->service_work);
                }
```

### PR DESCRIPTION
**Pull request by mike-scott**
"It's a Trap!" -- Admiral Ackbar

When moving to the BSD-socket APIs, the original thread running LwM2M
periodic services such as observes and lifetime updates, was replaced
with a re-occuring workqueue job.  To save the overhead of creating a
new thread, I used the system workqueue for these jobs.

This was a mistake.  If these jobs hit a semaphore or wait for some
reason, it cannot be prempted due to the priority of the system work
queue.

Let's instead add this service handling to the thread that we already
use for polling sockets.  This also removes a configuration issue where
the system workqueue stack size needed to be increased.  This can now
be adjusted via the LWM2M_ENGINE_STACK_SIZE knob.

Directly fixes semaphore usage in the socket-based DNS code.
This was introduced as a bugfix for non-responsive DNS server hanging
the Zephyr device forever.  However, this probably fixes randomly
seeming hangs on the device.

Fixes  #15204 

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by andyross** [comment]
Work queue jobs really should never be blocking for any reason, that's an abuse of the API, the whole point of which is to isolate units of actual **work** so they can be scheduled asynchronously.   Even if you don't run into priority problems doing this, you are starving the other users of the queue.

Seems like an OK workaround, but this isn't a root cause fix.  Maybe we should have some kind of assertion layer to catch behavior like this, maybe flag a thread as  "must stay schedulable" while the work_q callback is in progresss...

**Review by jukkar — APPROVED** [review]
LGTM.

Do we actually need to have the #15210 as the DNS resolver already has timeout mechanism which should work just fine. So the fix in #15210 is something that we should not normally need in the socket layer.

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 1]
```diff
@@ -3810,16 +3806,12 @@ static void lwm2m_engine_service(struct k_work *work)
 		/* service is due */
 		if (timestamp > service_due_timestamp) {
```
Comment (pieterjanc) [inline subsys/net/lib/lwm2m/lwm2m_engine.c]: If timestamp == service_due_timestamp, the work will not be handled. engine_next_service_timeout_ms will return 0 and lwm2m_engine_service will be called repeatedly without the work being handled.
```suggestion
		if (timestamp >= service_due_timestamp) {
```

**Comment by mike-scott** [comment]
@jukka This is a companion PR to the Socket-based DNS fix.  Both are needed.

File: subsys/net/lib/lwm2m/lwm2m_engine.c (hunk 1 above)
Comment (mike-scott) [reply subsys/net/lib/lwm2m/lwm2m_engine.c]: @pieterjanc I will add this as a second patch.  Thank you for pointing out the zero case.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by mike-scott** [comment]
@jukkar Should I add the fix for @pieterjanc issue here or do it as a separate PR?

**Comment by jukkar** [comment]
> Should I add the fix for @pieterjanc issue here or do it as a separate PR?

Just add it to this PR.

**Comment by mike-scott** [comment]
@pieterjanc I've added a new patch to this PR to address the issue you brought up.  I explain the issue in detail in the commit description.   Please make sure my understanding of this issue is correct.

**Comment by pieterjanc** [comment]
Perfect! This will also fix #15204 which I opened just before this pull request.
Thanks!
