### PR TITLE
drivers: i2c: stm32_v2: abort pending controller START on ADDR

### LINKED ISSUE #99074: [i2c][stm32-v2] Multi-master deadlock: master_active set before START blocks target IRQs during BUSY wait, causing bus hang
### Bug description

On STM32 I²C v2 in multi-master setups (device configured for both master + target), the Zephyr driver sets `data->master_active = true` in `msg_init()` before issuing a START and before the bus is confirmed idle. If the bus is still BUSY (e.g., peer master performs immediate repeated-STARTs), target IRQ handling is suppressed by the `slave_attached && !master_active check;` the local device fails to ACK as a target, the peer stalls with BUSY held, and our master side spins waiting for idle → deadlock / bus hang.

File: drivers/i2c/i2c_ll_stm32_v2.c 
Function: msg_init()

### Bug Fix:
```
#define STM32_I2C_ARLO_TIMEOUT_USEC  	 2000

static inline int wait_bus_idle(const struct device *dev, uint32_t timeout_us)
{
    const struct i2c_stm32_config *cfg = dev->config;
    I2C_TypeDef *i2c = cfg->i2c;
    uint32_t start = k_cycle_get_32();

    /* Wait for BUSY=0 (bus idle) */
    while (LL_I2C_IsActiveFlag_BUSY(i2c)) {
        if (k_cyc_to_us_near32(k_cycle_get_32() - start) > timeout_us) {
            return -EBUSY;
        }
    }
    return 0;
}

static inline void msg_init(const struct device *dev, struct i2c_msg *msg,
			    uint8_t *next_msg_flags, uint16_t slave,
			    uint32_t transfer)
{
	const struct i2c_stm32_config *cfg = dev->config;
	struct i2c_stm32_data *data = dev->data;
	I2C_TypeDef *i2c = cfg->i2c;

	if (LL_I2C_IsEnabledReloadMode(i2c)) {
		LL_I2C_SetTransferSize(i2c, msg->len);
	} else {
		if (I2C_ADDR_10_BITS & data->dev_config) {
			LL_I2C_SetMasterAddressingMode(i2c,
					LL_I2C_ADDRESSING_MODE_10BIT);
			LL_I2C_SetSlaveAddr(i2c, (uint32_t) slave);
		} else {
			LL_I2C_SetMasterAddressingMode(i2c,
				LL_I2C_ADDRESSING_MODE_7BIT);
			LL_I2C_SetSlaveAddr(i2c, (uint32_t) slave << 1);
		}

		if (!(msg->flags & I2C_MSG_STOP) && next_msg_flags &&
		    !(*next_msg_flags & I2C_MSG_RESTART)) {
			LL_I2C_EnableReloadMode(i2c);
		} else {
			LL_I2C_DisableReloadMode(i2c);
		}
		LL_I2C_DisableAutoEndMode(i2c);
		LL_I2C_SetTransferRequest(i2c, transfer);
		LL_I2C_SetTransferSize(i2c, msg->len);

		LL_I2C_Enable(i2c);

        /*wait for real bus idle BEFORE declaring master_active */
        if (wait_bus_idle(dev, STM32_I2C_ARLO_TIMEOUT_USEC) != 0) {
            /* Make sure we do NOT look like a master while we back out */
#if defined(CONFIG_I2C_TARGET)
            data->master_active = false;
#endif
            return;
        }

#if defined(CONFIG_I2C_TARGET)
        data->master_active = true;   /* <<< set only now */
#endif

		LL_I2C_GenerateStartCondition(i2c);
	}
}
```

Image
Image
Image

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

Zephyr SDK, STM32

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AydinyanNarek**
- Adds a short `BUSY` wait before starting a new controller session when target mode is attached. This handles the common case where another controller already owns the bus and avoids needlessly arming controller mode while the bus is still busy.
- Adds helper paths to resolve the matched target configuration and to centralize target address setup after `ADDR` handling.
- Detects own-address `ADDR` while `controller_active` is set and aborts the pending controller request instead of blocking target IRQ handling.
- Clears the pending controller request under interrupt lock by dropping `CR2.START` and `CR2.STOP`, marks the transfer as arbitration lost, wakes the waiting thread, and immediately continues with target-side address handling.
- Extends the same controller-to-target handoff to the error path so `ARLO` or `BERR` combined with own-address recognition recover cleanly instead of leaving the bus stuck.
- Prevents duplicate completion signaling by funneling controller-transfer wakeup through a single helper and resetting the sync semaphore before each IRQ transfer.
- Keeps the peripheral enabled when target mode remains attached or SMBus Alert is active, including the DMA startup failure path, so an aborted controller transfer does not tear down target support.
- Simplifies the IRQ finish disable decision by computing `disable_i2c` once from transfer state and explicit keep-alive conditions.
- Resets `current.is_arlo` before a new message so stale arbitration-loss state is not carried into the next transfer.

This is intended to fix the STM32 I2C v2 multi-controller/target race where own-address recognition can arrive while a controller START is still pending, causing target IRQ handling to be blocked and the bus to hang.

### CODE REVIEW

File: drivers/i2c/i2c_stm32_v2.c [hunk 1]
```diff
@@ -275,6 +274,80 @@ static void i2c_stm32_target_event(const struct device *dev)
...
+	 */
+	key = irq_lock();
+	LL_I2C_ClearFlag_ADDR(i2c);
+	stm32_reg_clear_bits(&i2c->CR2, I2C_CR2_START);
+	irq_unlock(key);
+
+	data->current.is_arlo = 1U;
+	data->controller_active = false;
+
+#ifdef CONFIG_I2C_STM32_INTERRUPT
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: I guess this whole function is only used when interrupts are configured, so no need for #ifdef here

File: drivers/i2c/i2c_stm32_v2.c [hunk 2]
```diff
@@ -275,6 +274,80 @@ static void i2c_stm32_target_event(const struct device *dev)
...
+	i2c_stm32_disable_transfer_interrupts(dev);
+	k_sem_give(&data->device_sync_sem);
+#endif
+
+	i2c_stm32_target_addr_setup(dev, target_cfg);
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: Is it possible to continue as a target in this case ,immediately after the aborted controller transaction?
The errata sheet doesn't say anything about that
Maybe there are ST folks here than can clarify?

Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: I checked the STM32 errata. For the affected I2C v2 parts, the workaround is applied after ADDR is set and must complete before STOP, which implies the matched target transaction is still ongoing while the pending controller START is being aborted. Since this driver does not enable SBC, we are in the normal-mode (SBC=0) case, so continuing directly into target setup here is the intended interpretation. If we skip target setup at this point, the ADDR event has already been cleared and the target transaction would be lost.

`STM32H745/H747/H755/H757 errata, ES0445 Rev 6, section 2.19.3: `
https://www.st.com/resource/en/errata_sheet/dm00530531-stm32h745-747xi-g-and-stm32h755-757xi-
device-limitations-stmicroelectronics.pdf

`STM32U575/U585 errata, ES0499 Rev 11:`
https://www.st.com/resource/en/errata_sheet/es0499-stm32u575xx-and-stm32u585xx-device-errata-stmicroelectronics.pdf

File: drivers/i2c/i2c_stm32_v2.c [hunk 3]
```diff
@@ -726,8 +781,15 @@ static int stm32_i2c_irq_msg_finish(const struct device *dev, struct i2c_msg *ms
 		keep_enabled = true;
 	}
 
-	/* If I2C no longer need to be enabled or on error */
-	if (!keep_enabled || (ret != 0)) {
+	disable_i2c = !keep_enabled || (ret != 0);
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c:837]: I think it would be possible to simplify the I2C disable logic in this function

Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c:837]: Good point. I simplified the disable path so the function now computes
disable_i2c once from the transfer completion/error state, then keeps
the peripheral enabled only when target mode is still attached or
SMBus Alert is active.

File: drivers/i2c/i2c_stm32_v2.c [hunk 4]
```diff
@@ -4,8 +4,8 @@
  *
  * SPDX-License-Identifier: Apache-2.0
  *
- * I2C Driver for: STM32F0, STM32F3, STM32F7, STM32L0, STM32L4, STM32WB and
- * STM32WL
+ * I2C Driver for: STM32F0, STM32F3, STM32F7, STM32L0, STM32L4, STM32WB,
+ * STM32WL and STM32U5 series
```
Comment (erwango) [inline drivers/i2c/i2c_stm32_v2.c]: I'd prefer your remove these lines fully. This is obsolete information

File: drivers/i2c/i2c_stm32_v2.c [hunk 5]
```diff
@@ -129,6 +129,37 @@ static struct i2c_stm32_timings_t i2c_valid_timing[I2C_STM32_VALID_TIMING_NBR];
 static uint32_t i2c_valid_timing_nbr;
 #endif /* CONFIG_I2C_STM32_V2_TIMING */
 
+#define STM32_I2C_ARLO_TIMEOUT_USEC 2000U
```
Comment (erwango) [inline drivers/i2c/i2c_stm32_v2.c]: Please make it a Kconfig symbol as `I2C_STM32_TRANSFER_TIMEOUT_MSEC`

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/i2c/i2c_stm32_v2.c (hunk 5 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: Done

File: drivers/i2c/i2c_stm32_v2.c (hunk 4 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: Done

File: drivers/i2c/i2c_stm32_v2.c [hunk 6]
```diff
@@ -715,31 +868,124 @@ static int stm32_i2c_irq_msg_finish(const struct device *dev, struct i2c_msg *ms
...
+{
+	struct i2c_stm32_data *data = dev->data;
+
+	if ((isr & I2C_ISR_TCR) != 0U) {
+		return 0;
+	}
+
+#if defined(CONFIG_I2C_TARGET)
+	if (starting_controller_session && data->target_attached &&
+	    (wait_bus_idle(dev, CONFIG_I2C_STM32_BUSY_WAIT_TIMEOUT_USEC) != 0)) {
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: Do wee need to poll here with wait_bus_idle?
According to reference manual it should be possible to set START even if BUSY is set, i suppose then the I2C controller waits until bus becomes ready and then begins transaction
(Except when ourself are the one being addressed as a target on the bus, but in that case we don't need to poll, a STOP event for target could set a semaphore for example, giving access to controller)
Image

Comment (erian747) [reply drivers/i2c/i2c_stm32_v2.c]: I think the 'controller_active' flag is a bit flawed from the beginning
for example i2c_stm32_target_unregister will fail if a transaction is ongoing
we have data->bus_mutex in i2c_stm32.c that protects against mutual accesses to i2c-hw
but that mutex isn't used at all when we are adressed in target mode, i guess it should be to block starting controller transactions
Note: Im not saying you should fix this, just want to point out that target implementation are a bit flaky from the beginning IMO

Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: You’re right that wait_bus_idle() is not the core correctness fix by itself, and the hang is really addressed by the own-address / controller-abort handling.

I kept wait_bus_idle() as a best-effort optimization for multi-master + target use cases. In stress testing, it made a noticeable performance difference: it avoids starting a controller transaction when the bus is already clearly busy, which reduces unnecessary ARLO/recovery cycles, retry churn, and controller state resets.

So, from my testing, the benefit is not “fixes the deadlock” only, but also “avoids expensive failed attempts and improves throughput/latency under contention”. The errata-style overlap handling is still needed for the race window between the BUSY check and START, which was already added here.


I agree. The mutex only serializes local software access to the controller path; it does not protect against asynchronous target-address matches coming from the bus. That is why this fix handles the overlap in the ISR/error path instead of relying on controller_active alone.

I think the broader controller/target arbitration model could be improved separately, but for this PR I’m keeping scope focused on the concrete deadlock/hang caused by own-address overlap during controller start.

Comment (erian747) [reply drivers/i2c/i2c_stm32_v2.c]: Yes i fully understand, best to limit the scope or a PR can be hanging forever without beeing merged

**Comment by erwango** [comment]
@AydinyanNarek Please squash commits when it makes sense and don't fix comments in later commits, but in initial, "faulty", commit.

File: drivers/i2c/i2c_stm32_v2.c [hunk 7]
```diff
@@ -129,6 +125,41 @@ static struct i2c_stm32_timings_t i2c_valid_timing[I2C_STM32_VALID_TIMING_NBR];
...
 #endif /* CONFIG_I2C_STM32_V2_TIMING */
 
+static inline int wait_bus_idle(const struct device *dev, uint32_t timeout_us)
+{
+	const struct i2c_stm32_config *cfg = dev->config;
+	I2C_TypeDef *i2c = cfg->i2c;
+	uint32_t start = k_cycle_get_32();
+
+	while (LL_I2C_IsActiveFlag_BUSY(i2c)) {
+		if (k_cyc_to_us_near32(k_cycle_get_32() - start) > timeout_us) {
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: I guess the amount of time spent waiting here depends on how many bytes remains to be transferred by other controller
If its a big message CPU would spend many waste cycles here
Maybe add short sleep, like 10 microseconds between each busy poll retry so cpu can context switch and work with other things in the meantime

Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: Thanks, good point. I updated the BUSY polling loop to add a 10us delay between retries.

To keep ISR-safe behavior, the loop now uses:
- k_usleep(10) in thread context (allows scheduling),
- k_busy_wait(10) in ISR context (sleep is not allowed there).

This should reduce wasted CPU cycles during BUSY wait while preserving behavior on IRQ paths.

File: drivers/i2c/i2c_stm32_v2.c [hunk 8]
```diff
@@ -715,31 +879,122 @@ static int stm32_i2c_irq_msg_finish(const struct device *dev, struct i2c_msg *ms
...
 {
 	const struct i2c_stm32_config *cfg = dev->config;
 	struct i2c_stm32_data *data = dev->data;
 	I2C_TypeDef *regs = cfg->i2c;
+	int ret;
+#if defined(CONFIG_I2C_TARGET)
+	bool starting_controller_session = !data->controller_active;
+	bool arm_controller_active = false;
+#endif
+
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c:941]: Why is semaphore reset here?

File: drivers/i2c/i2c_stm32_v2.c [hunk 9]
```diff
@@ -806,53 +1057,35 @@ static int stm32_i2c_irq_xfer(const struct device *dev, struct i2c_msg *msg,
...
-			 */
-			if (data->current.len > 0U) {
-				LL_I2C_TransmitData8(regs, *data->current.buf);
-				data->current.len--;
-				data->current.buf++;
-			}
+	ret = i2c_stm32_irq_prepare_start(dev, msg, isr, regs, &cr2
+#if defined(CONFIG_I2C_TARGET)
+					  ,
+					  starting_controller_session, &arm_controller_active
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: Maybe you can use the return code combined with starting_controller_session to set arm_controller_active instead of having pointer to it supplied to the function

File: drivers/i2c/i2c_stm32_v2.c (hunk 7 above)
Comment (erian747) [reply drivers/i2c/i2c_stm32_v2.c]: No need to support ISR context here i would say as this function must not be called from ISR (blocking inside ISRs shall be strictly avoided)

File: drivers/i2c/i2c_stm32_v2.c (hunk 8 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c:941]: `device_sync_sem` is a per-transfer completion event.  
I reset it before arming a new transfer to clear any stale token from a previous one (for example, if a previous transfer timed out/aborted in thread context but its IRQ completion `k_sem_give()` arrives later).

Without `k_sem_reset()`, the next `k_sem_take()` may return immediately on that old token, and we could treat the new transfer as completed too early.

File: drivers/i2c/i2c_stm32_v2.c (hunk 6 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: I added the ISR/non-ISR branch defensively at first, to avoid sleeping if this helper ever got called from interrupt context.

After review, that was unnecessary here: this BUSY wait helper is only valid in thread context. Supporting ISR there could hide misuse, so I removed that path and made it explicit with `__ASSERT_NO_MSG(!k_is_in_isr())` + `k_usleep()`.

File: drivers/i2c/i2c_stm32_v2.c (hunk 9 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: Good suggestion, I refactored this.

I removed the `arm_controller_active` out-pointer from
`i2c_stm32_irq_prepare_start()`.
Now the caller derives `controller_active` from the existing state:
`starting_controller_session` plus `isr` (`TCR` not set), after a successful
prepare-start return.

So the behavior is unchanged, but the interface is simpler and avoids the
extra output parameter.

File: drivers/i2c/i2c_stm32_v2.c (hunk 7 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: I added the ISR/non-ISR branch defensively at first, to avoid sleeping if this helper ever got called from interrupt context.

After review, that was unnecessary here: this BUSY wait helper is only valid in thread context. Supporting ISR there could hide misuse, so I removed that path and made it explicit with __ASSERT_NO_MSG(!k_is_in_isr()) + k_usleep().

File: drivers/i2c/i2c_stm32_v2.c [hunk 10]
```diff
@@ -900,13 +899,13 @@ static int stm32_i2c_irq_msg_finish(const struct device *dev, struct i2c_msg *ms
...
+static int i2c_stm32_irq_prepare_start(const struct device *dev, struct i2c_msg *msg, uint32_t isr,
+				       I2C_TypeDef *regs, uint32_t *cr2
 #if defined(CONFIG_I2C_TARGET)
-				       , bool starting_controller_session,
-				       bool *arm_controller_active
+				       ,
+				       bool starting_controller_session, bool *arm_controller_active
 #endif
-				       )
+)
```
Comment (erwango) [inline drivers/i2c/i2c_stm32_v2.c]: Don't fix formatting in a later commit, but make it right in first commit that introduced the change.
(Also, the `)` move is wrong).

File: drivers/i2c/i2c_stm32_v2.c [hunk 11]
```diff
@@ -1062,9 +1059,10 @@ static int stm32_i2c_irq_xfer(const struct device *dev, struct i2c_msg *msg,
 	 */
 	ret = i2c_stm32_irq_prepare_start(dev, msg, isr, regs, &cr2
 #if defined(CONFIG_I2C_TARGET)
-					  , starting_controller_session, &arm_controller_active
+					  ,
+					  starting_controller_session, &arm_controller_active
 #endif
-					  );
+	);
```
Comment (erwango) [inline drivers/i2c/i2c_stm32_v2.c]: Ditto on formatting changes.
(and on `)` move)

File: drivers/i2c/i2c_stm32_v2.c [hunk 12]
```diff
@@ -141,6 +137,12 @@ static inline int wait_bus_idle(const struct device *dev, uint32_t timeout_us)
 		if (k_cyc_to_us_near32(k_cycle_get_32() - start) > timeout_us) {
 			return -EBUSY;
 		}
+
+		if (k_is_in_isr()) {
+			k_busy_wait(I2C_STM32_BUSY_POLL_DELAY_USEC);
+		} else {
+			(void)k_usleep(I2C_STM32_BUSY_POLL_DELAY_USEC);
+		}
```
Comment (erwango) [inline drivers/i2c/i2c_stm32_v2.c]: This change is undocumented in commit message.
(Put in wrong commit ?)

File: drivers/i2c/i2c_stm32_v2.c [hunk 13]
```diff
@@ -133,16 +133,15 @@ static inline int wait_bus_idle(const struct device *dev, uint32_t timeout_us)
...
 	while (LL_I2C_IsActiveFlag_BUSY(i2c)) {
 		if (k_cyc_to_us_near32(k_cycle_get_32() - start) > timeout_us) {
 			return -EBUSY;
 		}
 
-		if (k_is_in_isr()) {
-			k_busy_wait(I2C_STM32_BUSY_POLL_DELAY_USEC);
-		} else {
-			(void)k_usleep(I2C_STM32_BUSY_POLL_DELAY_USEC);
-		}
```
Comment (erwango) [inline drivers/i2c/i2c_stm32_v2.c]: Remove this from previous commit and directly provide a commit that does the right thing.

File: drivers/i2c/i2c_stm32_v2.c [hunk 14]
```diff
@@ -715,31 +878,116 @@ static int stm32_i2c_irq_msg_finish(const struct device *dev, struct i2c_msg *ms
...
 
 	return ret;
 }
 
+static int i2c_stm32_irq_prepare_start(const struct device *dev, struct i2c_msg *msg, uint32_t isr,
+				       I2C_TypeDef *regs, uint32_t *cr2
+#if defined(CONFIG_I2C_TARGET)
+				       ,
+				       bool starting_controller_session
+#endif
```
Comment (erwango) [inline drivers/i2c/i2c_stm32_v2.c]: Rather than having this conditional in the header of the function, make `starting_controller_session` an unused arg if !defined(CONFIG_I2C_TARGET) in the function. This will increase readability

File: drivers/i2c/i2c_stm32_v2.c [hunk 15]
```diff
@@ -1060,7 +1053,7 @@ static int stm32_i2c_irq_xfer(const struct device *dev, struct i2c_msg *msg,
 	ret = i2c_stm32_irq_prepare_start(dev, msg, isr, regs, &cr2
 #if defined(CONFIG_I2C_TARGET)
 					  ,
-					  starting_controller_session, &arm_controller_active
```
Comment (erwango) [inline drivers/i2c/i2c_stm32_v2.c]: Fix this directly in commit that introduce the function

**Review by erwango — CHANGES_REQUESTED** [review]
Some rework still required in commits structure.
Thanks for your patience !

**Comment by erwango** [comment]
Side note: you're not supposed to resolve conversations by yourself.

File: drivers/i2c/i2c_stm32_v2.c [hunk 16]
```diff
@@ -129,6 +125,48 @@ static struct i2c_stm32_timings_t i2c_valid_timing[I2C_STM32_VALID_TIMING_NBR];
...
+
+		(void)k_usleep(I2C_STM32_BUSY_POLL_DELAY_USEC);
+	}
+
+	return 0;
+}
+
+static inline bool i2c_stm32_signal_xfer_done(const struct device *dev)
+{
+#ifdef CONFIG_I2C_STM32_INTERRUPT
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: The whole i2c_stm32_signal_xfer_done function are only used when CONFIG_I2C_STM32_INTERRUPT is defined
so no need to use #ifdef CONFIG_I2C_STM32_INTERRUPT inside function
better to place the function itselfs inside the file scope #ifdef CONFIG_I2C_STM32_INTERRUPT

File: drivers/i2c/i2c_stm32_v2.c [hunk 17]
```diff
@@ -129,6 +125,48 @@ static struct i2c_stm32_timings_t i2c_valid_timing[I2C_STM32_VALID_TIMING_NBR];
...
+			return -EBUSY;
+		}
+
+		(void)k_usleep(I2C_STM32_BUSY_POLL_DELAY_USEC);
+	}
+
+	return 0;
+}
+
+static inline bool i2c_stm32_signal_xfer_done(const struct device *dev)
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: Return value is not used anywhere so this function could be declared with void return value

File: drivers/i2c/i2c_stm32_v2.c [hunk 18]
```diff
@@ -715,31 +878,118 @@ static int stm32_i2c_irq_msg_finish(const struct device *dev, struct i2c_msg *ms
...
+
+	if ((isr & I2C_ISR_TCR) != 0U) {
+		return 0;
+	}
+
+#if defined(CONFIG_I2C_TARGET)
+	if (starting_controller_session && data->target_attached &&
+	    (wait_bus_idle(dev, CONFIG_I2C_STM32_BUSY_WAIT_TIMEOUT_USEC) != 0)) {
+		data->current.msg = NULL;
+		return -EBUSY;
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c:870]: Don't we need to do the same I2C_Disable logic here in same way as in i2c_stm32_irq_start_dma if timeout?

Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c:870]: Good point. I checked this path and updated it.

In i2c_stm32_irq_prepare_start(), this timeout happens while waiting for BUSY to clear, before issuing START and before arming IRQ/DMA transfer. So there is no active controller transfer to unwind, unlike the DMA-start failure path.

Also, this branch is entered only when the target is attached, so disabling the peripheral here would be incorrect (it should remain available for target mode). I removed the disable logic and kept only the cleanup of the current.msg + return -EBUSY.

File: drivers/i2c/i2c_stm32_v2.c (hunk 17 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: Fixed

File: drivers/i2c/i2c_stm32_v2.c (hunk 16 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: Fixed

Comment (erian747) [reply drivers/i2c/i2c_stm32_v2.c]: If this function is only used for irq mode, the ifdef don't need to be inside function

Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: It is not inside the function. I think you haven't seen the updated diff, or you are looking at an old commit

Comment (erian747) [reply drivers/i2c/i2c_stm32_v2.c]: Ah, probably was a glitch when page was loaded

File: drivers/i2c/i2c_stm32_v2.c [hunk 19]
```diff
@@ -931,11 +1147,16 @@ static inline void msg_init(const struct device *dev, struct i2c_msg *msg,
...
 		LL_I2C_SetTransferSize(i2c, msg->len);
-
+		LL_I2C_Enable(i2c);
 #if defined(CONFIG_I2C_TARGET)
+		if (data->target_attached) {
+			if (wait_bus_idle(dev, CONFIG_I2C_STM32_BUSY_WAIT_TIMEOUT_USEC) != 0) {
+				data->controller_active = false;
+				return;
+			}
+		}
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: msg_init() init is only used when CONFIG_I2C_STM32_INTERRUPT is not enabled
and i suppose target mode is only available with CONFIG_I2C_STM32_INTERRUPT enabled
so target_attached will never be set here

File: drivers/i2c/i2c_stm32_v2.c [hunk 20]
```diff
@@ -806,53 +1043,30 @@ static int stm32_i2c_irq_xfer(const struct device *dev, struct i2c_msg *msg,
...
+	if (ret != 0) {
+		return ret;
 	}
 #else
 	/* If not using DMA, also enable RX and TX empty interrupts */
 	cr1 |= I2C_CR1_TXIE | I2C_CR1_RXIE;
 #endif /* CONFIG_I2C_STM32_V2_DMA */
 
+#if defined(CONFIG_I2C_TARGET)
+	if (starting_controller_session && ((isr & I2C_ISR_TCR) == 0U)) {
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: Not really following what the purpose is of checking TCR here
If we have successfully passed i2c_stm32_irq_prepare_start(() i suppose data->controller_active always shall be set to true
Maybe add a code comment to explain reason behind it if its needed

File: drivers/i2c/i2c_stm32_v2.c [hunk 21]
```diff
@@ -277,6 +316,72 @@ static void i2c_stm32_target_event(const struct device *dev)
...
+	struct i2c_stm32_data *data = dev->data;
+
+	if (own_addr_match) {
+		LL_I2C_ClearFlag_ADDR(cfg->i2c);
+		i2c_stm32_clear_controller_request(cfg->i2c);
+	}
+
+	i2c_stm32_disable_transfer_interrupts(dev);
+	LL_I2C_ClearFlag_TXE(cfg->i2c);
+	data->controller_active = false;
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c:377]: If DMA is used for controller, it should be disabled here when switching from controller mode to target
with LL_I2C_DisableDMAReq_RX and LL_I2C_DisableDMAReq_TX otherwise it will interfere with target data transfer
(i know the thread will call dma_finish but that can be to late, target data transfer might already have started before thread is woken)

File: drivers/i2c/i2c_stm32_v2.c [hunk 22]
```diff
@@ -617,18 +754,28 @@ int i2c_stm32_error(const struct device *dev)
...
 	i2c_target_error_cb_t error_cb = NULL;
+	bool own_addr_while_controller;
 
 	if (data->target_attached && !data->controller_active &&
 	    data->target_cfg != NULL && data->target_cfg->callbacks != NULL) {
 		error_cb = data->target_cfg->callbacks->error;
 	}
+
+	own_addr_while_controller =
+		data->target_attached && data->controller_active && LL_I2C_IsActiveFlag_ADDR(i2c);
```
Comment (erian747) [inline drivers/i2c/i2c_stm32_v2.c]: I don't think you can get an arbitration loss in controller mode and at the same moment having the ADDR flag set
From datasheet:
"In master mode, arbitration loss is detected during the address phase, data phase and
data acknowledge phase. In this case, the SDA and SCL lines are released, the
START control bit is cleared by hardware and the master switches automatically to
slave mode. "

I interpret it as if a remote controller send our address while we are a controller, we would not detect the address, just an arbitration loss

To keep things simple, i suggest you remove the call to i2c_stm32_target_handle_controller_error for both ARLO and BERR

File: drivers/i2c/i2c_stm32_v2.c (hunk 21 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c:377]: Good catch, agreed. I updated the controller -> target abort path to explicitly disable both DMA requests immediately (LL_I2C_DisableDMAReq_RX/TX) before clearing TXE and signaling completion, so target traffic cannot be affected by stale controller DMA state.

File: drivers/i2c/i2c_stm32_v2.c (hunk 22 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: I simplified this as suggested and removed the i2c_stm32_target_handle_controller_error() path from ARLO/BERR handling.

ADDR preemption is now handled only in the dedicated target-preempt event path, while ARLO/BERR no longer tries to infer own-address overlap in that error handler.

File: drivers/i2c/i2c_stm32_v2.c (hunk 20 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: I removed the extra TCR condition and now set controller_active directly when starting_controller_session is true after successful prepare/start flow. This makes the intent clearer.

File: drivers/i2c/i2c_stm32_v2.c (hunk 19 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: Removed the target-specific logic from the non-interrupt msg_init path (and related timeout cleanup path there), since target mode is interrupt-driven and that branch was not meaningful in the polling path.

**Review by erian747 — APPROVED** [review]

**Comment by erian747** [comment]
For some reason i can't set my comments as resolved, but as far as im concerned they are resolved
I approved the PR (only been looking into the technical details, not formatting etc)

**Comment by AydinyanNarek** [comment]
Hello maintainers,

My PR #106434 appears to be waiting on workflow approval, so the full CI suite has not continued to run yet.

This change is intended to fix an issue in the STM32 I2C driver, and I would appreciate it if someone could review the PR and approve the workflows so the remaining tests can proceed.

I understand everyone is busy, but I wanted to follow up because the PR has been waiting for some time, and I would like to keep it moving.

Thank you for your time and for maintaining Zephyr.

File: drivers/i2c/i2c_stm32_v2.c [hunk 23]
```diff
@@ -592,25 +651,8 @@ void i2c_stm32_event(const struct device *dev)
...
-			i2c_stm32_controller_abort_to_target(dev, true);
-			i2c_stm32_target_addr_setup(dev, target_cfg, false);
-			return;
-		}
-
-		if (!data->controller_active) {
-			i2c_stm32_target_event(dev);
-			return;
-		}
+	if (i2c_stm32_target_preempt_controller_event(dev, isr)) {
```
Comment (etienne-lms) [inline drivers/i2c/i2c_stm32_v2.c:654]: Prefer explicit `!= 0` or `< 0`.

File: drivers/i2c/i2c_stm32_v2.c [hunk 24]
```diff
@@ -445,6 +445,65 @@ static void i2c_stm32_target_event(const struct device *dev)
...
+		i2c_stm32_target_addr_setup(dev, target_cfg, false);
+		return 0;
+	}
+
+	if (data->controller_active) {
+		i2c_stm32_controller_abort_to_target(dev, false);
+		return -EIO;
+	}
+
+	return 1;
```
Comment (etienne-lms) [inline drivers/i2c/i2c_stm32_v2.c:504]: `return 0`? What does `1` means here?

**Review by etienne-lms — COMMENTED** [review]
Commit *"drivers: i2c: stm32_v2: make bus wait timeout configurable"* conaints coding style related changes and instruction changes. Could you move the coding style related changes into a dedicated commit (or maybe discard them if not really needed).

The logic of the commits is a bit hard to follow. It seems each commit does several things. It would be easier to have 1 commit per functional changes, if possible. Maybe I've misunderstand the dependencies of the changes.

File: drivers/i2c/i2c_stm32_v2.c (hunk 24 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: This is in an outdated commit. It is returning true.

File: drivers/i2c/i2c_stm32_v2.c (hunk 23 above)
Comment (AydinyanNarek) [reply drivers/i2c/i2c_stm32_v2.c]: Done

**Comment by AydinyanNarek** [comment]
@etienne-lms 

Thanks, you were right. I reworked the branch and force-pushed a cleaner stack so each commit is narrower and easier to follow.

The functional changes are now split into:

drivers: i2c: stm32_v2: abort pending controller START on ADDR
drivers: i2c: stm32_v2: handle controller/target own-address races
drivers: i2c: stm32_v2: make bus wait timeout configurable
I also removed the unrelated style/comment churn from the timeout commit. The explicit == true review nit is now in a separate tiny follow-up commit:

drivers: i2c: stm32_v2: make target preempt check explicit
Please take another look when you have a chance.

**Comment by AydinyanNarek** [comment]
@All,

Are there any problems with delaying this PR from being merged?

**Review by gautierg-st — APPROVED** [review]

**Comment by AydinyanNarek** [comment]
@erwango can you please take a look at this PR?

**Review by erwango — APPROVED** [review]
