### PR TITLE
posix: move limit definitions to posix_limits.h

### LINKED ISSUE #80409: Zephyr defines POSIX values which already appear in limits.h
**Describe the bug**
Upstream picolibc includes definitions for various minimum values in limits.h that are required by POSIX including `_POSIX_NAME_MAX` and `_POSIX_PATH_MAX`. Zephyr is redefining these in include/zephyr/posix/posix_features.h.

**To Reproduce**
1. Download toolchain built against current picolibc development branch: https://github.com/zephyrproject-rtos/sdk-ng/actions/runs/11503233418/artifacts/2100796287
2.  west twister -p qemu_malta -s tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc
3. See error

**Expected behavior**
Successful test run

**Impact**
Cannot migrate picolibc to upstream development version

**Logs and console output**
```
[81/147] Building C object zephyr/lib/posix/options/CMakeFiles/lib__posix__options.dir/sysconf.c.obj
FAILED: zephyr/lib/posix/options/CMakeFiles/lib__posix__options.dir/sysconf.c.obj 
ccache /__w/sdk-ng/sdk-ng/tools/zephyr-sdk-0.17.0-8-g6fd2e1d/mips-zephyr-elf/bin/mips-zephyr-elf-gcc -DKERNEL -DK_HEAP_MEM_POOL_SIZE=1024 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -DTC_RUNID=020f12a965888084e31d7f59ce1d46d3 -D__LINUX_ERRNO_EXTENSIONS__ -D__ZEPHYR__=1 -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/kernel/include -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/arch/mips/include -I/__w/sdk-ng/sdk-ng/test/twister-out/qemu_malta/tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc/zephyr/include/generated/zephyr -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include -I/__w/sdk-ng/sdk-ng/test/twister-out/qemu_malta/tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc/zephyr/include/generated -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/soc/qemu/malta -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/posix -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/soc/qemu/malta/. -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/subsys/testsuite/include -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/subsys/testsuite/coverage -I/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/subsys/testsuite/ztest/include -isystem /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/lib/libc/common/include -Os -DNDEBUG -Wshadow -fno-strict-aliasing -Werror -Os -imacros /__w/sdk-ng/sdk-ng/test/twister-out/qemu_malta/tests/lib/c_lib/thrd/libraries.libc.c11_threads.picolibc/zephyr/include/generated/zephyr/autoconf.h -fno-printf-return-value -fno-common -g -gdwarf-4 -fdiagnostics-color=always -EL -msoft-float -G0 -mno-gpopt -fno-pic -pipe --sysroot=/__w/sdk-ng/sdk-ng/tools/zephyr-sdk-0.17.0-8-g6fd2e1d/mips-zephyr-elf/mips-zephyr-elf -imacros /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/tests/lib/c_lib/thrd=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/sdk-ng/sdk-ng/zephyrproject/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/sdk-ng/sdk-ng/zephyrproject=WEST_TOPDIR -ffunction-sections -fdata-sections --specs=picolibc.specs -D_POSIX_THREADS -mips32 -std=c99 -MD -MT zephyr/lib/posix/options/CMakeFiles/lib__posix__options.dir/sysconf.c.obj -MF zephyr/lib/posix/options/CMakeFiles/lib__posix__options.dir/sysconf.c.obj.d -o zephyr/lib/posix/options/CMakeFiles/lib__posix__options.dir/sysconf.c.obj -c /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/lib/posix/options/sysconf.c
In file included from /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/posix/signal.h:10,
                 from /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/posix/time.h:62,
                 from /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/posix/pthread.h:14,
                 from /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/lib/posix/options/sysconf.c:9:
/__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/posix/posix_features.h:241: error: "_POSIX_AIO_LISTIO_MAX" redefined [-Werror]
  241 | #define _POSIX_AIO_LISTIO_MAX               (2)
      | 
In file included from /__w/sdk-ng/sdk-ng/tools/zephyr-sdk-0.17.0-8-g6fd2e1d/mips-zephyr-elf/picolibc/include/limits.h:6,
                 from /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/kernel_includes.h:22,
                 from /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/kernel.h:17,
                 from /__w/sdk-ng/sdk-ng/zephyrproject/zephyr/include/zephyr/posix/pthread.h:13:
/__w/sdk-ng/sdk-ng/tools/zephyr-sdk-0.17.0-8-g6fd2e1d/mips-zephyr-elf/picolibc/include/sys/syslimits.h:63: note: this is the location of the previous definition
   63 | #define _POSIX_AIO_LISTIO_MAX   2
```
**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK development version

### PR DESCRIPTION
**Pull request by cfriedt**
* posix: move limit definitions to common libc limits.h
* posix: move posix limit definitions to posix_limits.h

This is an alternative PR to #93387 which includes changes related to comments made by @stephanosio 

Fixes #80409

### CODE REVIEW

**Comment by cfriedt** [comment]
@stephanosio - please let me know if this is what you had in mind or suggest changes that you would like to see.

File: include/zephyr/posix/posix_limits.h [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+ * Copyright The Zephyr Project Contributors
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#ifndef ZEPHYR_INCLUDE_ZEPHYR_POSIX_POSIX_LIMITS_H_
+#define ZEPHYR_INCLUDE_ZEPHYR_POSIX_POSIX_LIMITS_H_
+
+/*
+ * clang-format and checkpatch disagree on formatting here, so use rely and checkpatch and disable
```
Comment (tomi-font) [inline include/zephyr/posix/posix_limits.h]: Use or rely on?

File: include/zephyr/posix/posix_limits.h [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+ * clang-format since the checkpatch cannot be selectively disabled.
```
Comment (tomi-font) [inline include/zephyr/posix/posix_limits.h]:
```suggestion
 * clang-format since checkpatch cannot be selectively disabled.
```

File: lib/libc/minimal/include/limits.h [hunk 3]
```diff
@@ -80,8 +80,16 @@ extern "C" {
 #error "unexpected __SIZEOF_LONG_LONG__ value"
 #endif
 
+#if defined(_POSIX_C_SOURCE) || defined(__DOXYGEN__)
```
Comment (tomi-font) [inline lib/libc/minimal/include/limits.h:83]: No more need for the Picolibc `limits.h` inclusion?

File: include/zephyr/posix/posix_limits.h [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+#define HOST_NAME_MAX \
+	COND_CODE_1(CONFIG_POSIX_NETWORKING, (CONFIG_POSIX_HOST_NAME_MAX), (0))
+#define LOGIN_NAME_MAX                _POSIX_LOGIN_NAME_MAX
+#define MQ_OPEN_MAX \
+	COND_CODE_1(CONFIG_POSIX_MESSAGE_PASSING, (CONFIG_POSIX_MQ_OPEN_MAX), (0))
+#define MQ_PRIO_MAX                   _POSIX_MQ_PRIO_MAX
+#define OPEN_MAX                      CONFIG_POSIX_OPEN_MAX
+#define PAGE_SIZE                     CONFIG_POSIX_PAGE_SIZE
+#define PAGESIZE                      CONFIG_POSIX_PAGE_SIZE
+#undef PATH_MAX
```
Comment (tomi-font) [inline include/zephyr/posix/posix_limits.h]: Is this undef really needed?

File: include/zephyr/posix/posix_limits.h (hunk 1 above)
Comment (cfriedt) [reply include/zephyr/posix/posix_limits.h]: Thanks - this is fixed in the other PR, but not here.

File: include/zephyr/posix/posix_limits.h (hunk 2 above)
Comment (cfriedt) [reply include/zephyr/posix/posix_limits.h]: Same - thanks for finding that.

File: lib/libc/minimal/include/limits.h (hunk 3 above)
Comment (cfriedt) [reply lib/libc/minimal/include/limits.h:83]: Picolibc headers are not used when the minimal libc is selected.

File: include/zephyr/posix/posix_limits.h (hunk 4 above)
Comment (cfriedt) [reply include/zephyr/posix/posix_limits.h]: Probably not.

File: include/zephyr/posix/posix_limits.h (hunk 1 above)
Comment (cfriedt) [reply include/zephyr/posix/posix_limits.h]: Fixed!

File: include/zephyr/posix/posix_limits.h (hunk 4 above)
Comment (cfriedt) [reply include/zephyr/posix/posix_limits.h]: Fixed!

File: lib/libc/minimal/include/limits.h (hunk 3 above)
Comment (cfriedt) [reply lib/libc/minimal/include/limits.h:83]: Fixed!

File: include/zephyr/posix/posix_limits.h (hunk 2 above)
Comment (cfriedt) [reply include/zephyr/posix/posix_limits.h]: Fixed!

File: lib/libc/minimal/include/limits.h (hunk 3 above)
Comment (tomi-font) [reply lib/libc/minimal/include/limits.h:83]: I didn't mean to comment for this particular header, rather just wanted to point out that `posix_features.h` used to include picolibc's `limits.h` and to check whether we still need this condition (that would be in `posix_limits.h`).

**Review by dkalowsk — APPROVED** [review]

File: lib/libc/minimal/include/limits.h (hunk 3 above)
Comment (cfriedt) [reply lib/libc/minimal/include/limits.h:83]: No, it's not necessary.

**Review by ldomaigne — APPROVED** [review]
LGTM

**Review by stephanosio — APPROVED** [review]

**Comment by cfriedt** [comment]
I should also mention that this is still a problem with newlib that will need to be addressed, but in a separate PR.

https://github.com/zephyrproject-rtos/zephyr/pull/93387#issuecomment-3233242584
