### PR TITLE
drivers: memc: Fix various APS6404 device driver issues

### LINKED ISSUE #81151: Multiple APS6404 MSPI Device Issues
In an effort to port our MSPI controller, I came across couple of issues in the APS6404 MSPI device driver implementation that should result in throwing few build errors when employed by an MSPI controller other than AMBIQ. #79513 is the PR that addresses these issues and are thoroughly described in the PR's description section.

### PR DESCRIPTION
**Pull request by ioannis-karachalios**
This commit deals with fixing various issues that prevents the APS6404 MSPI device from being built. In specific:

1. Fix default timing macro definitions to build with an MSPI controller, other than AMBIG. Add macro definition for MSPI_PORT.
2. Timing settings should be applied only when MSPI_TIMING is defined. Otherwise, the APS6404 initialization routine should fail with -EIO.
3. Similarly, use MSPI_XIP and MSPI_SCRAMBLE to apply XIP and SCRAMBLE device settings, respectively (optimization).
4. Based on current MEMC_INIT_PRIORITY (0), APS6404 device should be initialized before the underlying MSPI bus is enabled, and so the APS6404 initialization routine should fail during controller's bus check. Change init. priority to a value higher than MSPI_INIT_PRIORITY (70).

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/81151

### CODE REVIEW

File: drivers/memc/Kconfig [hunk 1]
```diff
@@ -13,7 +13,7 @@ if MEMC
 
 config MEMC_INIT_PRIORITY
 	int "Initialization priority"
-	default 0
+	default 80
```
Comment (swift-tk) [inline drivers/memc/Kconfig:16]: This may not be a good idea as it changed priorities for all the memc drivers and other people may still want to early init. 
default 80 if MSPI may be better.

**Review by swift-tk — CHANGES_REQUESTED** [review]

**Comment by swift-tk** [comment]
@ioannis-karachalios Thanks for filing the PR, I was going to fix those things but apparently you’ve beat me to it😄.

File: drivers/memc/Kconfig (hunk 1 above)
Comment (ioannis-karachalios) [reply drivers/memc/Kconfig]: You are right.

**Comment by ioannis-karachalios** [comment]
> @ioannis-karachalios Thanks for filing the PR, I was going to fix those things but apparently you’ve beat me to it😄.

@swift-tk, you're welcome. I am working on a new family of device that is going to support the MSPI driver and I came across these errors.

**Review by ydamigos — DISMISSED** [review]

**Review by swift-tk — APPROVED** [review]

**Comment by swift-tk** [comment]
@ioannis-karachalios Please note that you also have to fix the CI checks before a merge.

**Comment by RichardSWheatley** [comment]
> > @ioannis-karachalios Thanks for filing the PR, I was going to fix those things but apparently you’ve beat me to it😄.
> 
> 
> 
> @swift-tk, you're welcome. I am working on a new family of device that is going to support the MSPI driver and I came across these errors. 

I am following as we are creating another device driver for memc. Same family, higher density.

**Comment by ioannis-karachalios** [comment]
"Please note that you also have to fix the CI checks before a merge."
@swift-tk, to my understanding, the CI errors should be irrelevant to the underlying changes. Should these errors be addressed here?

File: drivers/memc/memc_mspi_aps6404l.c [hunk 2]
```diff
@@ -341,28 +343,34 @@ static int memc_mspi_aps6404l_init(const struct device *psram)
...
+#if CONFIG_MSPI_TIMING
 	if (mspi_timing_config(cfg->bus, &cfg->dev_id, cfg->timing_cfg_mask,
 			       (void *)&cfg->tar_timing_cfg)) {
 		LOG_ERR("Failed to config mspi timing/%u", __LINE__);
 		return -EIO;
 	}
 	data->timing_cfg = cfg->tar_timing_cfg;
+#endif /* CONFIG_MSPI_TIMING */
 
+#if CONFIG_MSPI_XIP
```
Comment (RichardSWheatley) [inline drivers/memc/memc_mspi_aps6404l.c:355]: Why are these ifdef's included of the enable is already there?

To save code space?

**Review by RichardSWheatley — DISMISSED** [review]

File: drivers/memc/memc_mspi_aps6404l.c (hunk 2 above)
Comment (swift-tk) [reply drivers/memc/memc_mspi_aps6404l.c:355]: When XIP is not supported by a specific hardware, CONFIG_MSPI_XIP=n is used to indicate that. This also means that xip_config may not be implemented, so calling it in device driver will result in error. Leaving it out of compile will not only save code space but also ensure the device driver is still functional without optional features.

**Comment by swift-tk** [comment]
> "Please note that you also have to fix the CI checks before a merge." @swift-tk, to my understanding, the CI errors should be irrelevant to the underlying changes.

Could you try rebase to latest main and try again with the CI. If that don't work, I will ask help in discord.

**Comment by ioannis-karachalios** [comment]
> Could you try rebase to latest main and try again with the CI. If that don't work, I will ask help in discord.
I re-based to the latest main, but CI reports the same twister errors, again. I'd appreciate if we seek for assistance in discord as my schedule is tight at the moment to further investigate it.

File: drivers/memc/Kconfig [hunk 3]
```diff
@@ -13,7 +13,7 @@ if MEMC
 
 config MEMC_INIT_PRIORITY
 	int "Initialization priority"
-	default 0
+	default 80 if MSPI
```
Comment (swift-tk) [inline drivers/memc/Kconfig:16]: This is the reason why CI failed. LOL
```suggestion
	default 80 if MSPI
	default 0
```

**Review by swift-tk — CHANGES_REQUESTED** [review]
I did not notice the default 0 was gone.

**Review by swift-tk — APPROVED** [review]

**Comment by ioannis-karachalios** [comment]
> I did not notice the default 0 was gone.

@swift-tk, I was under the impression that a zero value should be given if not defined, explicitly. Thanks for your support.

**Review by ydamigos — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@ioannis-karachalios , we are only merging PR that have a Zephyr Issue linked to it. If this is needed for the 4.0 release, then please add a Zephyr issue with details about the problem seen and link it to this PR.

**Comment by ioannis-karachalios** [comment]
@mmahadevan108, I opened #81151 bug report incident that links this PR.
