### PR TITLE
arm_arch_timer: Fix ticks count on !CONFIG_TICKLESS_KERNEL

### LINKED ISSUE #33873: arm_arch_timer: Too many clock announcements with CONFIG_TICKLESS_KERNEL=n on SMP
https://github.com/zephyrproject-rtos/zephyr/blob/95cddd4df7e63375f27d6308dd9b31ffd4d8ab97/drivers/timer/arm_arch_timer.c#L46

If `CONFIG_TICKLESS_KERNEL` is not set this always announces a tick. With SMP only one core is expected to announce a tick even if all cores receive the IRQ, therefore this announces too many ticks. For example, this causes applications which use `k_msleep` to be woken up too early.

The code works correctly in a tickless kernel because `last_cycle` is shared and the cores that execute the critical section subsequently calculate `delta_tick=0`.

Unrelated: I believe `last_cycle` does not need to be `volatile` because it is protected by the lock.

### PR DESCRIPTION
**Pull request by carlocaione**
When SMP is enabled all the cores are announcing a tick and this is
causing too many ticks to be announced. Only the primary core is
expected to announce a tick. Introduce a check and fix the issue.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

Reported by @luisgerhorst

### CODE REVIEW

**Comment by carlocaione** [comment]
@luisgerhorst can you check with this patch?

**Comment by npitre** [comment]
Can't you use `IS_ENABLED(CONFIG_SMP)` with the first `if ()` instead of the #ifdef here?
Also you could have a single `if ()` with all 3 conditions.

**Comment by carlocaione** [comment]
> Can't you use `IS_ENABLED(CONFIG_SMP)` with the first `if ()` instead of the #ifdef here?
> Also you could have a single `if ()` with all 3 conditions.

Done.

**Review by npitre — APPROVED** [review]

File: drivers/timer/arm_arch_timer.c [hunk 1]
```diff
@@ -16,14 +16,21 @@
...
-static volatile uint64_t last_cycle;
+static uint64_t last_cycle;
 
 static void arm_arch_timer_compare_isr(const void *arg)
 {
 	ARG_UNUSED(arg);
 
 	k_spinlock_key_t key = k_spin_lock(&lock);
 
+	/* Only the primary core is supposed to announce a tick */
```
Comment (andyross) [inline drivers/timer/arm_arch_timer.c:27]: This will work, but is a little fragile in the face of unexpected latency on core 0.  The way this works on other SMP platforms is that all the interrupted CPUs independently compute (atomically!) the elapsed time from the last announced interrupt and announce it.  This will be zero on the second of two simultaneously-interrupted CPUs, and everything will work correctly.  And there will be less code, one fewer test on a hot path, and everything will be symmetric.

Comment (andyross) [reply drivers/timer/arm_arch_timer.c:27]: Oh, actually belay that.  This won't work.  Timeslicing works by multiplexing the timer announce stream, which means that suppressing timer interrupts on the other cores means that timesliced threads on other CPUs won't be preempted as expected.

This is sort of a design wart.  At some point it would be better to rework timeslice expirations as a per-CPU timeout object and have the handler deliver the actual preemption via the scheduler IPI (or a more flexible derivative).

But at least for now it's required that every timeout be delivered to every CPU, even if the announce ticks parameter is zero.

**Review by andyross — DISMISSED** [review]

File: drivers/timer/arm_arch_timer.c (hunk 1 above)
Comment (carlocaione) [reply drivers/timer/arm_arch_timer.c]: I pushed a new version that it works on tests but again not sure if it's the correct way to implement this because I'm not really familiar with the details of the kernel time keeping. Anyway, v2 just pushed.

**Review by npitre — APPROVED** [review]

**Review by luisgerhorst — APPROVED** [review]
Looks good to me!

**Comment by carlocaione** [comment]
@andyross ping

**Review by povergoing — APPROVED** [review]
Agree with andyross, better to handle the actual preemption via the scheduler IPI.

But for this change, LGTM

**Comment by cfriedt** [comment]
@carlocaione - looks as though this has all of the approvals and only needs a couple of fixups. Do you have an ETA?

**Review by stephanosio — APPROVED** [review]
LGTM as far as this change is concerned.

As @andyross noted, we should rework the Zephyr kernel to keep track of the timeouts per CPU.

**Comment by stephanosio** [comment]
p.s. it looks like Xtensa has the same problem, cc @dcpleung @andyross 
https://github.com/zephyrproject-rtos/zephyr/blob/2b91ebe16e25e5ce17270ea36b88fbb34f5f28ed/drivers/timer/xtensa_sys_timer.c#L56
