### PR TITLE
mgmt: mcumgr: Fix non-start outgoing packets sent with start headers

### LINKED ISSUE #49444: mcumgr: Outgoing packets that are larger than the transport MTU are wrongly split into different individual messages
**Describe the bug**
A pending outgoing mcumgr message is checked against the transport MTU size, if the outgoing message is larger than the MTU, it is wrongly split into multiple start packets. This can be easily observed with an echo message, if an echo message of 280 bytes is sent to the mcu, the response seems to start OK with a first packet and then continuation packets, but then the final packet is wrongly given a first packet header, and the data contained is (from the point of view of a first package) garbage, it is actually continuation data from the previous packets. This leads to wild data being decoded:
```
Op:  111
Flags:  109
Length:  25
Group:  26725
Sequence:  114
ID:  101
0 true
Text:  "f"
Clearing garbage data
```
And the previous packets end abruptly with corrupt data that cannot be used.

**To Reproduce**
Build smp_svr with shell and shell-mgmt overlays, send an echo command which is longer than the shell MTU to the target device, watch the response

**Expected behavior**
For the output data to be split up accordingly, not wrongly

**Impact**
Annoyance/showstopper, for the use case of echo, it isn't very important, however the echo command can be abused to send a specially crafted packet which would then be interpreted as a valid mcumgr frame to a client, this can have undefined operation depending upon how the client works, e.g. a security-related frame could be crafted to change access, or a packet with a length of 65535 byte length field could be made which might block the client from processing packets until 65KB of data has been received, causing a denial of service

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.14.2
 - Commit SHA or Version used: 80f848e4a4fea98fcc587990cd73696ec43563bd

### PR DESCRIPTION
**Pull request by nordicjm**
Fixes an issue with outgoing mcumgr frames that are larger than the
transport MTU size whereby they would wrongly be split up into multiple
frames with multiple start frame headers, which affected SMP over
console transports. Now, the whole mcumgr packet is chunked into frames
after calculating the full length and checksum.

Fixes #49444

Also happens to reduce smp_svr build size by 144 bytes with the overlay-bt.conf, which is a nice added benefit

Tested backends:
- [X] Shell
- [X] UART
- [X] Bluetooth
- [X] UDP

### CODE REVIEW

File: drivers/console/uart_mcumgr.c [hunk 1]
```diff
@@ -211,9 +211,10 @@ static int uart_mcumgr_send_raw(const void *data, int len, void *arg)
 	return 0;
 }
 
-int uart_mcumgr_send(const uint8_t *data, int len)
+int uart_mcumgr_send(const uint8_t *data, int len, enum smp_transport_out_flags flags,
```
Comment (de-nordic) [inline drivers/console/uart_mcumgr.c:214]: We need to change the function set here. Of  all the parameters only `data` and `len` should be left and the others should be passed as parameters of some context object.
Additional initialization function should be added for initializing of the context.
There is also advantage of using context object: we may calculate frame boundaries in advance and figure out whether we will be able to fit CRC in the last frame or move it, with one byte, to another.
This should allow us to simplify logic in  `mcumgr_serial_tx_frame`.

**Review by de-nordic — CHANGES_REQUESTED** [review]

File: drivers/console/uart_mcumgr.c (hunk 1 above)
Comment (nordicjm) [reply drivers/console/uart_mcumgr.c:214]: Can use a struct to pass the information through and then access it but I don't follow the rest, the MTU is already known and accessed in the `.zst_get_mtu` function pointer, the serial processing output functions can be vastly optimised but that is separate from this bug

Comment (nordicjm) [reply drivers/console/uart_mcumgr.c]: Reworked to use a struct variable

File: subsys/mgmt/mcumgr/serial_util.c [hunk 2]
```diff
@@ -241,8 +239,14 @@ int mcumgr_serial_tx_frame(const uint8_t *data, bool first, int len,
...
-	} else if (reminder >= 2) {
-		last = true;
+
+		if (tx_data->flags & SMP_TRANSPORT_OUT_LAST_PACKET) {
+			/* This is the last frame but the checksum cannot be added, remove the
+			 * last packet flag until the function runs again with the final piece
+			 * of data and place the checksum there
+			 */
+			tx_data->flags ^= SMP_TRANSPORT_OUT_LAST_PACKET;
+		}
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/serial_util.c:249]: No need for branches here, just do the `tx-data->flags &= ~SMP_TRANSPORT_OUT_LAST_PACKET`.

Comment (nordicjm) [reply subsys/mgmt/mcumgr/serial_util.c]: Fixed

File: include/zephyr/mgmt/mcumgr/smp.h [hunk 3]
```diff
@@ -13,21 +13,46 @@
...
+ * @brief SMP transport out function flags
+ *
+ * @details Flags passed to the transport out function
+ */
+enum smp_transport_out_flags {
+	SMP_TRANSPORT_OUT_NONE = 0,
+	SMP_TRANSPORT_OUT_FIRST_PACKET = BIT(0),
+	SMP_TRANSPORT_OUT_LAST_PACKET = BIT(1),
+};
+
```
Comment (de-nordic) [inline include/zephyr/mgmt/mcumgr/smp.h:26]: I do not think this is needed: when you store `total_len` and `sent_bytes` in your "fragmentation state/context" `zephyr_tx_information`, you have all the info needed to figure where you are at a transfer.

**Review by de-nordic — DISMISSED** [review]

File: include/zephyr/mgmt/mcumgr/serial.h [hunk 4]
```diff
@@ -129,11 +130,12 @@ struct net_buf *mcumgr_serial_process_frag(
...
  * @param cb                    A callback used to transmit raw bytes.
  * @param arg                   An optional argument to pass to the callback.
+ * @param tx_data               Overall packet context
  *
  * @return                      0 on success; negative error code on failure.
  */
-int mcumgr_serial_tx_pkt(const uint8_t *data, int len, mcumgr_serial_tx_cb cb,
-			 void *arg);
+int mcumgr_serial_tx_pkt(const uint8_t *data, int len, mcumgr_serial_tx_cb cb, void *arg,
+			 struct zephyr_tx_information *tx_data);
```
[the remark this answers is not in the document]
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/serial.h:138]: The length and crc are appended at the bottom level, at mcumgr_serial_tx_frame in serial_util.c, that means it has to transverse all of these layers:
```
#0  mcumgr_serial_tx_frame (data=data@entry=0x200064c0 <net_buf_data_pkt_pool+768> "\003", len=len@entry=256, 
    cb=cb@entry=0x1aca5 <smp_shell_tx_raw>, arg=arg@entry=0x0, tx_data=tx_data@entry=0x20005ad0 <sys_work_q_stack+1944>, 
    out_data_bytes_txed=out_data_bytes_txed@entry=0x20005a94 <sys_work_q_stack+1884>)
    at zephyr/subsys/mgmt/mcumgr/serial_util.c:198
#1  0x0001b1fc in mcumgr_serial_tx_pkt (data=0x200064c0 <net_buf_data_pkt_pool+768> "\003", len=256, 
    cb=cb@entry=0x1aca5 <smp_shell_tx_raw>, arg=arg@entry=0x0, tx_data=0x20005ad0 <sys_work_q_stack+1944>)
    at zephyr/subsys/mgmt/mcumgr/serial_util.c:323
#2  0x000126ea in smp_shell_tx_pkt (zst=<optimized out>, nb=0x20006190 <_net_buf_pkt_pool+48>, tx_data=<optimized out>)
    at zephyr/subsys/mgmt/mcumgr/smp_shell.c:183
#3  0x0001ac68 in zephyr_smp_tx_rsp (ns=<optimized out>, rsp=<optimized out>, arg=0x200015f0 <smp_shell_transport>)
    at zephyr/subsys/mgmt/mcumgr/smp.c:185
#4  0x000137f6 in smp_process_request_packet (streamer=streamer@entry=0x20005b34 <sys_work_q_stack+2044>, 
    vreq=0x20006160 <_net_buf_pkt_pool>) at zephyr/subsys/mgmt/mcumgr/lib/smp/src/smp.c:297
#5  0x00012694 in zephyr_smp_process_packet (nb=<optimized out>, zst=0x200015f0 <smp_shell_transport>)
    at zephyr/subsys/mgmt/mcumgr/smp.c:218
```
zephyr_smp_tx_rsp is the function where the packet starts getting chopped up, at the start of the function, all the data is available for knowing the full length and checksum of the packet, after 1 iteration the buffer is missing the complete set of data

File: include/zephyr/mgmt/mcumgr/smp.h [hunk 5]
```diff
@@ -13,21 +13,46 @@
...
  *
  * @param zst                   The transport to send via.
  * @param nb                    The net_buf to transmit.
+ * @param tx_data               Overall packet context
  *
  * @return                      0 on success, MGMT_ERR_[...] code on failure.
  */
 typedef int zephyr_smp_transport_out_fn(struct zephyr_smp_transport *zst,
-					struct net_buf *nb);
+					struct net_buf *nb, struct zephyr_tx_information *tx_data);
```
[the remark this answers is not in the document]
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/smp.h:55]: zst_output is not called with the complete packet, zst_output is called with the data for sets of frames, the bug that this code fixes is that zst_output is called twice for a single (long) output, and in the second instance it wrongly puts a start of packet header on the packet, which is invalid

File: include/zephyr/mgmt/mcumgr/serial.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (de-nordic) [reply include/zephyr/mgmt/mcumgr/serial.h:138]: My bad. Anyway: dump the `zephyr_smp_tx_rsp` and move fragmentation directly to transports.
Why? Because all transports directly access `net_buf->data` so they can loop themselves over the data with the mtu they have.
This helps us with a few problems:
 1) exhausting mcumgr `net_buf` pool for fragmenting packets for transports with mtu smaller than packet, as currently buffers for "fragments" are taken from the mcumgr pool;
 2) having two levels of fragmentation, for example when uart mtu does not fit into uart encoding buffer you will have to fragment the output twice; this can be done once directly in uart where you select smaller of the values (mtu, buffer size) and fragment buffer once.
 3) we do not have to pass mtu to upper levels - one callback less.

[the remark this answers is not in the document]
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/serial.h:138]: Will have to redo this review but will need the code in this version of the review to be updated on zephyr 2.7 since this bug is present there

[the remark this answers is not in the document]
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/serial.h:138]: ...Should probably have tested with 2.7 sooner, turns out 2.7 doesn't have this issue, will rework this review.

File: include/zephyr/mgmt/mcumgr/serial.h [hunk 6]
```diff
@@ -129,11 +130,12 @@ struct net_buf *mcumgr_serial_process_frag(
  * @param len                   The length of the unencoded mcumgr packet.
  * @param cb                    A callback used to transmit raw bytes.
  * @param arg                   An optional argument to pass to the callback.
+ * @param tx_data               Overall packet context
  *
  * @return                      0 on success; negative error code on failure.
  */
-int mcumgr_serial_tx_pkt(const uint8_t *data, int len, mcumgr_serial_tx_cb cb,
-			 void *arg);
+int mcumgr_serial_tx_pkt(const uint8_t *data, int len, mcumgr_serial_tx_cb cb, void *arg,
```
[the remark this answers is not in the document]
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/serial.h]: Dropped

File: include/zephyr/mgmt/mcumgr/smp.h [hunk 7]
```diff
@@ -13,21 +13,46 @@
...
 struct net_buf;
 
+/**
+ * @brief Holds contexts for mcumgr packet being transmitted
+ *
+ * @param crc                   Checksum of the whole mcumgr packet.
+ * @param total_len             Total length of the whole mcumgr packet, in bytes.
+ * @param flags                 Flags for the current mcumgr frame.
+ */
+struct zephyr_tx_information {
```
[the remark this answers is not in the document]
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/smp.h]: Removed

File: include/zephyr/mgmt/mcumgr/smp.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/smp.h]: Fixed

File: include/zephyr/mgmt/mcumgr/serial.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/serial.h]: Fixed

File: include/zephyr/mgmt/mcumgr/smp.h (hunk 3 above)
Comment (nordicjm) [reply include/zephyr/mgmt/mcumgr/smp.h]: Removed

File: subsys/mgmt/mcumgr/smp.c [hunk 8]
```diff
@@ -143,36 +82,23 @@ static int
...
-	uint16_t mtu;
 	int rc;
-	int i;
 
 	zst = arg;
 	nb = rsp;
 
-	mtu = zst->zst_get_mtu(rsp);
-	if (mtu == 0U) {
+	if (zst->zst_get_mtu(rsp) == 0U) {
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/smp.c:91]: This can be done by `zst_output` callback.

File: subsys/mgmt/mcumgr/serial_util.c [hunk 9]
```diff
@@ -157,179 +156,158 @@ static int mcumgr_serial_tx_small(const void *data, int len,
...
 
-	if (reminder == 0 || reminder == 1) {
-		to_process -= 1;
-	} else if (reminder >= 2) {
-		last = true;
-	}
+			++src_off;
+			/* One triple of allowed input already used */
+			max_input -= 3;
+		}
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/serial_util.c:224]: Unwind the loop a little bit and take the "first" case out of it. Save us some conditional checking within loop.

**Review by de-nordic — COMMENTED** [review]
Nome nitpicks, but this is generally looking good.

File: subsys/mgmt/mcumgr/serial_util.c (hunk 9 above)
Comment (nordicjm) [reply subsys/mgmt/mcumgr/serial_util.c:224]: This would still need a check if it was removed as taking it out would need the start or continuation frame marking sending, and then an if would need to be added to the loop to see if it was sent (first packet) or not

File: subsys/mgmt/mcumgr/smp.c (hunk 8 above)
Comment (nordicjm) [reply subsys/mgmt/mcumgr/smp.c]: Fixed

**Comment by nordicjm** [comment]
@de-nordic @nvlsianpu @carlescufi This has been ready to review for some time now, can you please review?

File: subsys/mgmt/mcumgr/smp_shell.c [hunk 10]
```diff
@@ -176,13 +176,17 @@ static int smp_shell_tx_raw(const void *data, int len, void *arg)
...
 
-static int smp_shell_tx_pkt(struct zephyr_smp_transport *zst,
-			    struct net_buf *nb)
+static int smp_shell_tx_pkt(struct zephyr_smp_transport *zst, struct net_buf *nb)
 {
 	int rc;
 
-	rc = mcumgr_serial_tx_pkt(nb->data, nb->len, smp_shell_tx_raw, NULL);
-	mcumgr_buf_free(nb);
+	if (CONFIG_MCUMGR_SMP_SHELL_MTU == 0U) {
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/smp_shell.c:183]: A value of the `CONFIG_MCUMGR_SMP_SHELL_MTU` is known at compile time, why not just fail the compilation here?
Also, is the `MTU == 0` only MTU that is bad, because I am quite convinced that it is any MTU that can not handle minimal frame.

Comment (nordicjm) [reply subsys/mgmt/mcumgr/smp_shell.c:183]: This is outside the scope of this review and will need to be addressed later, the change above is the same behavior that mcumgr currently has but was moved out into the transport as per the request:
```
[de-nordic](https://github.com/de-nordic) [14 days ago](https://github.com/zephyrproject-rtos/zephyr/pull/49455#discussion_r955887120)

This can be done by zst_output callback.
```

File: subsys/mgmt/mcumgr/smp.c [hunk 11]
```diff
@@ -157,36 +90,18 @@ static int
...
-
-		rc = zst->zst_output(zst, frag);
-		if (rc != 0) {
-			return MGMT_ERR_EUNKNOWN;
-		}
-	}
+	/* Pass full packet to output function so it can be transmitted or split into frames as
+	 * needed by the transport
+	 */
+	rc = zst->zst_output(zst, nb);
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/smp.c:102]: No point to have `rc` here anymore.

File: subsys/mgmt/mcumgr/smp_shell.c (hunk 10 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_shell.c:183]: Yeah, what I meant was calling the mtu callback to modify how data is processed.
The check here is compile time check of 0 vs literal. This should just fail compilation.

Comment (nordicjm) [reply subsys/mgmt/mcumgr/smp_shell.c]: Fixed

File: subsys/mgmt/mcumgr/smp.c (hunk 11 above)
Comment (nordicjm) [reply subsys/mgmt/mcumgr/smp.c]: Fixed

File: subsys/mgmt/mcumgr/smp_udp.c [hunk 12]
```diff
@@ -65,27 +65,52 @@ static struct configs configs = {
 static int smp_udp4_tx(struct zephyr_smp_transport *zst, struct net_buf *nb)
 {
 	ARG_UNUSED(zst);
+	int ret;
+
+	if (CONFIG_MCUMGR_SMP_UDP_MTU == 0U) {
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/smp_udp.c:70]: Here in `udp6` version, same as in uart.

Comment (nordicjm) [reply subsys/mgmt/mcumgr/smp_udp.c]: Fixed

**Review by de-nordic — DISMISSED** [review]
Tested on nrf52840dk_nrf52840 (BT and UART). Works OK.

Looks OK.

**Comment by fabiobaltieri** [comment]
@nvlsianpu @carlescufi can you review this? It's blocking a high priority issue, would love to merge it before cutting RC1.

**Comment by fabiobaltieri** [comment]
@nordicjm sorry, just merged https://github.com/zephyrproject-rtos/zephyr/pull/49835, this needs a rebase now.

**Comment by nordicjm** [comment]
@fabiobaltieri rebased

**Review by de-nordic — DISMISSED** [review]

**Comment by nordicjm** [comment]
@fabiobaltieri I think everyone EU-side is done for the week, any way to get this merged before the release?

**Review by de-nordic — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri I think everyone EU-side is done for the week, any way to get this merged before the release?

It fixes a bug so it would be no problem merging after it, but it sounds like there's quite high confidence on this, let's merge it now.

**Review by fabiobaltieri — APPROVED** [review]
