### PR TITLE
Bluetooth: Controller: nRF54Lx: Fix DTM when using GRTC

### LINKED ISSUE #100754: bt test commands not working/crashing for nRF54LM20A DK board
### Describe the bug

I am trying to use the DTM HCI commands on nRF54LM20A DK board and zephyr BT controller. 

I am using this sample: 
`tests/bluetooth/shell`

and i build the sample like:
`west build -b nrf54lm20dk/nrf54lm20a/cpuapp tests/bluetooth/shell -p -- -DCONFIG_BT_CTLR_DTM_HCI=y -DCONFIG_CLOCK_CONTROL_NRF_HFINT_CALIBRATION=y`

For some reason, if i don't enable the `CONFIG_CLOCK_CONTROL_NRF_HFINT_CALIBRATION` 
then the application crashes like this: 

Image

Once i enabled that then i am able to issue commands without crashing.

Image

But unfortunately, i dont see any radio packets in spectrum analyzer (in channels i am trying), when i issue tx command. 
And when i issue `bt test_end` device hangs and i had reboot it to try. 

May be i am missing a crucial config relevant for this sample or may be there is bug to enable zephyr BT controller for this board. 

### Regression

- [x] This is a regression.

### Steps to reproduce

`west build -b nrf54lm20dk/nrf54lm20a/cpuapp tests/bluetooth/shell -p -- -DCONFIG_BT_CTLR_DTM_HCI=y -DCONFIG_CLOCK_CONTROL_NRF_HFINT_CALIBRATION=y`

in the shell issue
`bt init`
`bt test_tx 1 10 0 1`
`bt test_end`

### Relevant log output
pictures attached above

### Impact

blocks using nRF54LM20A for certification and production usecases with zephyr BT controller

### Environment

Ubuntu 22.04.5 LTS
My zephyr branch points to: `7c39469e1757bde345e20124f33fca6600f49dd5`

Image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by cvinayak**
Fix nRF54Lx DTM implementation when using GRTC. The Radio start needs to be offset by a maximum ISR latency value that is less than inter-frame switching, plus minimum counter compare offset that can be set, plus minimum CPU latency to set the counter compare register.

```
[2025-12-10 16:34:55.039] *** Booting Zephyr OS build v4.3.0-2132-geefa7f50055c ***
[2025-12-10 16:34:55.046] Type "help" for supported commands.Before any Bluetooth commands you must `bt init` to initialize the stack.
[2025-12-10 16:34:55.060] uart:~$ bt init
[2025-12-10 16:34:58.722] Bluetooth initialized
[2025-12-10 16:34:58.724] Settings Loaded
[2025-12-10 16:34:58.914] [00:00:03.687,403] <inf> fs_nvs: 8 Sectors of 4096 bytes
[2025-12-10 16:34:58.922] [00:00:03.687,417] <inf> fs_nvs: alloc wra: 0, ac0
[2025-12-10 16:34:58.929] [00:00:03.687,422] <inf> fs_nvs: data wra: 0, 600
[2025-12-10 16:34:58.937] [00:00:03.689,445] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[2025-12-10 16:34:58.947] [00:00:03.689,460] <inf> bt_hci_core: HW Variant: nRF54Lx (0x0005)
[2025-12-10 16:34:58.956] [00:00:03.689,474] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 4.3 Build 99
[2025-12-10 16:34:58.968] [00:00:03.689,710] <inf> bt_hci_core: No ID address. App must call settings_load()
[2025-12-10 16:34:58.978] [00:00:03.690,833] <err> settings: set-value failure. key: bt/mesh/AppKey/0 error(-2)
[2025-12-10 16:34:58.989] [00:00:03.690,921] <err> settings: set-value failure. key: bt/mesh/Seq error(-2)
[2025-12-10 16:34:58.999] [00:00:03.690,993] <err> settings: set-value failure. key: bt/mesh/IV error(-2)
[2025-12-10 16:34:59.010] [00:00:03.691,109] <err> settings: set-value failure. key: bt/mesh/Net error(-2)
[2025-12-10 16:34:59.020] [00:00:03.691,225] <err> settings: set-value failure. key: bt/mesh/NetKey/0 error(-2)
[2025-12-10 16:34:59.031] [00:00:03.691,938] <inf> bt_hci_core: HCI transport: Controller
[2025-12-10 16:34:59.039] [00:00:03.691,989] <inf> bt_hci_core: Identity: F4:BE:7F:30:2B:AC (random)
[2025-12-10 16:34:59.049] [00:00:03.692,007] <inf> bt_hci_core: HCI: version 5.4 (0x0d) revision 0x0000, manufacturer 0x05f1
[2025-12-10 16:34:59.061] [00:00:03.692,025] <inf> bt_hci_core: LMP: version 5.4 (0x0d) subver 0xffff
[2025-12-10 16:34:59.070] uart:~$ bt test_tx 0 10 0 1
[2025-12-10 16:35:05.787] test_tx...
[2025-12-10 16:35:05.787] uart:~$ bt test_end
[2025-12-10 16:35:09.462] num_rx= 0.
[2025-12-10 16:35:09.463] uart:~$ 
```

Fixes #100754.

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:649]: @dhananjaygj Please help check the below suggestion (I suspect UART or h/w interrupt may be causing additional latency setting up counter compare).

```suggestion
	int key = irq_lock();
	
	start_us = radio_tmr_start(1, cntr_cnt_get() + CNTR_MIN_DELTA, 0);
	
	irq_unlock(key);
```

Comment (dhananjaygj) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:649]: @cvinayak  I checked this suggestion but app still hangs when i dont see any radio packets.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:649]: ok... I think, `HAL_TICKER_CNTR_CMP_OFFSET_MIN` and/or `HAL_TICKER_CNTR_SET_LATENCY` values need to be tweaked then... unfortunately, I will not be able work on this any soon... will update here next week.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:649]: I have increase the CPU latency value and similarly tested as you have. Please check and revert back.

Comment (dhananjaygj) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_test.c:649]: i tested the change and now it works fine. no hangs seen in my setup

**Review by dhananjaygj — APPROVED** [review]
I tested the changes with HAL_TICKER_CNTR_SET_LATENCY 30 and tests are working fine without hanging in my setup.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_clock.c [hunk 1]
```diff
@@ -12,9 +12,19 @@
...
+ */
+#define LFCLOCK_TIMEOUT_MS 1000U
+
+/* HFXO clock setup timeout */
+#if DT_NODE_HAS_PROP(DT_NODELABEL(hfxo), startup_time_us)
+/* Use value from devicetree plus an additional margin */
+#define HFCLOCK_TIMEOUT_MS (DIV_ROUND_UP(DT_PROP(DT_NODELABEL(hfxo), startup_time_us), 1000U) + 3U)
+#else
+/* Use manually tested (peripheral role) value, includes added additional margin */
+#define HFCLOCK_TIMEOUT_MS 5U
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_clock.c:26]: Did you measure this, or did you decrease/increase until it worked?

**Review by Thalley — APPROVED** [review]
Changes looks OK to me, but I'm not familiar with the values at all

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_clock.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_clock.c:26]: Historically, what I remember, 16 or 32 MHz crystal would settle in 800 to 1500 us. Hence, the earlier 2 ms timeout. But lately nRF54L15 DKs show over 1500 us and the device tree now has ~ 1600 us as the settling time. I have added ~ 200 % additional margin for the timeout and tested manually that it is sufficient at desk.

**Review by carlescufi — APPROVED** [review]
