### PR TITLE
drivers: adc: stm32: only set CR2/DMA bit once on STM32F1

### LINKED ISSUE #101190: adc sequence sample mixes up channels on stm32f103
### Describe the bug

I'm using the `adc_sequence` sample from zephyr 4.3.0 on a custom stm32f103c8 based board. This is the relevant part of the DTS:
```

&adc1 {
    pinctrl-0 = <
        &adc1_in1_pa1
        &adc1_in2_pa2
        &adc1_in3_pa3
        &adc1_in4_pa4
        &adc1_in5_pa5
        &adc1_in6_pa6
        &adc1_in7_pa7
        &adc1_in8_pb0
    >;
    pinctrl-names = "default";
    status = "okay";

    dmas = <&dma1 1 (STM32_DMA_PERIPH_TO_MEMORY
        | STM32_DMA_MEM_INC
        | STM32_DMA_16BITS
        | STM32_DMA_PRIORITY_HIGH
    )>;
    dma-names = "adc1";

	#address-cells = <1>;
	#size-cells = <0>;
	channel@1 {
		reg = <1>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
	};
	channel@2 {
		reg = <2>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
	};
	channel@3 {
		reg = <3>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
	};
	channel@4 {
		reg = <4>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
	};
	channel@5 {
		reg = <5>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
	};
	channel@6 {
		reg = <6>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
	};
	channel@7 {
		reg = <7>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
	};
	channel@8 {
		reg = <8>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
	};
};
```
For simplicity I configured `CONFIG_SEQUENCE_SAMPLES=1`.

The first reading is showing correct values on all channels, however from the second sequence onwards, the channels are shifted, the value of channel 1 gets moved to channel 2, all the way to channel 8 moving to channel 1. I tested the `adc_dt` sample as well, this behavior wasn't observed there.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Add an overlay to an stm32f103 board DTS with 8 ADC channels and DMA assignment as above.
2. Build `adc_sequence` sample for this board.
3. Test it with logs enabled.

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by benedekkupper**
As reported in #101190, running adc_sequence sample on stm32f103c8 with 8 ADC channels causes all subsequent conversions after the first to be one channel shifted. When only disabling the DMA without checking its setting first, the mysterious conversion is triggered only on the first sequence after boot. With this change, CR2 register writes without modification are eliminated, fixing the mysterious conversion trigger that caused the channel shift.

Closes #101190

### CODE REVIEW

File: drivers/adc/adc_stm32.c [hunk 1]
```diff
@@ -1107,9 +1107,13 @@ static void adc_context_start_sampling(struct adc_context *ctx)
...
 
 #ifdef CONFIG_ADC_STM32_DMA
-#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32f4_adc)
-	/* Make sure DMA bit of ADC register CR2 is set to 0 before starting a DMA transfer */
-	LL_ADC_REG_SetDMATransfer(adc, LL_ADC_REG_DMA_TRANSFER_NONE);
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32f4_adc) || DT_HAS_COMPAT_STATUS_OKAY(st_stm32f1_adc)
+	/* Make sure DMA bit of ADC register CR2 is set to 0 before starting a DMA transfer,
+	 * without an unnecessary write
+	 */
+	if (LL_ADC_REG_GetDMATransfer(adc) != LL_ADC_REG_DMA_TRANSFER_NONE) {
```
Comment (etienne-lms) [inline drivers/adc/adc_stm32.c]: I am surprised this test is needed. Is it to prevent a write access (adding a read access) or do you confirm it fixes the "mysterious conversion trigger"?

Comment (benedekkupper) [reply drivers/adc/adc_stm32.c]: The full picture is that on my branch I do the `dma_config()` in the adc driver's init, and I only do `dma_reload()` in the sequence start to save on execution time. When this check isn't present (so what's done in #101550), then ADC CR2 register is written back with its identical value as it was read, with DMA bit at 0, that also causes a mysterious conversion trigger, in this case causing a channel shift only at the first sequence after boot. Perhaps a cleaner change would be to perform this check in `adc_stm32_enable_dma_support()`, to avoid writing the DMA bit to 1, when it's already set.

Comment (BhuvanB404) [reply drivers/adc/adc_stm32.c]: wow, I never encountereed the channel shift bug at boot, thats fascinating. 
I  tried a couple of things but found just using the implementation for stm32f4 the most stable and non-breaking method. Resetting it again seemed redundant to me because stm32f1 only has unlimited or none transfer mode as i hadn't encountered the after-boot shift in channels

**Comment by BhuvanB404** [comment]
@erwango @benedekkupper  I am curious, since we have two prs, on the same issue, what will be maintainers verdit?

File: drivers/adc/adc_stm32.c (hunk 1 above)
Comment (benedekkupper) [reply drivers/adc/adc_stm32.c]: > wow, I never encountereed the channel shift bug at boot, thats fascinating.

Indeed, using the `adc_sequence` sample doesn't produce this bug on `main`, like I said, this manifested with my changes:

> The full picture is that on my branch I do the dma_config() in the adc driver's init, and I only do dma_reload() in the sequence start to save on execution time.

I'm planning to submit this change as a PR in the future, it is currently blocked by another DMA bug (`dma_stop` disables interrupts that `dma_start` doesn't enable), which I will also need to submit another PR for. If either the current PR or #101550 is merged, the #101190 bug is solved. But if #101550 is merged, I might have to revisit this PR after those changes are merged. I made a branch for you to test: https://github.com/benedekkupper/zephyr/tree/stm32-adc-dma-test this is working with `adc_sequence`, but when the #101550 change is used instead, the first sample after boot will be offset.

Comment (etienne-lms) [reply drivers/adc/adc_stm32.c]: I wonder if this issue you see can be explained by an information in STM32F1xx reference manuals: on these SoCs, writing 1 to ADC_CR2[ADON] always starts a conversion unless *"any other bit in this register apart from ADON is changed at the same time"*. E.g. in RM0008 Rev 21, page 243:
> Bit 0 **ADON**: A/D converter ON / OFF
  This bit is set and cleared by software. If this bit holds a value of zero and a 1 is written to it
  then it wakes up the ADC from Power Down state.
  Conversion starts when this bit holds a value of 1 and a 1 is written to it. The application
  should allow a delay of tSTAB between power up and start of conversion. Refer to Figure 23.
  0: Disable ADC conversion/calibration and go to power down mode.
  1: Enable ADC and to start conversion
>
> Note: If any other bit in this register apart from ADON is changed at the same time, then
  conversion is not triggered. This is to prevent triggering an erroneous conversion.

While on STM32F4, writing 1 to ADC_CR2[ADON] only enables the ADC, it does not trigger a conversion.

Hence in your case, on F1, if ADC was already enabled, writing 0 in ADC_CR2[DMA] that was already 0 would trigger the ghost conversion you mention.

If confirmed, I would suggest a F1 dedicated implementation with an explicit inline comment, something like:
```patch
 #ifdef CONFIG_ADC_STM32_DMA
 #if DT_HAS_COMPAT_STATUS_OKAY(st_stm32f4_adc)
 	/* Make sure DMA bit of ADC register CR2 is set to 0 before starting a DMA transfer */
 	LL_ADC_REG_SetDMATransfer(adc, LL_ADC_REG_DMA_TRANSFER_NONE);
+#elseif DT_HAS_COMPAT_STATUS_OKAY(st_stm32f1_adc)
+	/* Make sure DMA bit of ADC register CR2 is set to 0 before starting a DMA transfer
+	 * without an unnecessary write to prevent triggering a conversion in case CR2[ADON]
+	 * is already set and other bits in CR2 are not modified.
+	 */
+	if (LL_ADC_REG_GetDMATransfer(adc) != LL_ADC_REG_DMA_TRANSFER_NONE) {
+		LL_ADC_REG_SetDMATransfer(adc, LL_ADC_REG_DMA_TRANSFER_NONE);
+	}
#endif
	adc_stm32_dma_start(dev, data->buffer, data->channel_count);
#endif
```

**(edited)** Looking at other STM32, only stm32f37xx ADC has the same behavior and is driven from the same DT node compat ID `"st-stm32f1-adc"` hence would also be addressed here.

Comment (benedekkupper) [reply drivers/adc/adc_stm32.c]: That is indeed matching my experience, I will go ahead with a separate fix.

**Review by etienne-lms — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Review by erwango — APPROVED** [review]
