### PR TITLE
net: refactor tftp library

### LINKED ISSUE #34131: TFTP client ignores incoming data packets
TFTP client implementation (/subsus/net/lib/tftp/tftp_client.c) doesn't work with tftpd ver.0.17-22
After creating socket (line 235) it sends request to server port 69 (line 196). Server responds with data packet, but the data transfer ports are chosen independently by the sender and receiver during the transfer initialization.
As a result, /subsus/net/ip/connection.c drops incoming data packet from server as it has source port differ than expected port 69 (checking at line 695):
```
[00:01:23.478,000] <dbg> net_conn.conn_register_debug: (sysworkq): [0x20004fcc/17/2/0x3f] remote fe80::5c00:82ff:fe96:9800/69
[00:01:23.485,000] <dbg> net_conn.conn_register_debug: (sysworkq):   local ::/38166 cb 0x803cd91 ud (nil)
[00:01:23.599,000] <dbg> net_conn.net_conn_input: (rx_q[0]): Check UDP listener for pkt 0x2001497c src port 36610 dst port 38166 family 2
[00:01:23.607,000] <dbg> net_conn.net_conn_input: (rx_q[0]): No match found.
[00:01:25.995,000] <dbg> net_conn.net_conn_unregister: (sysworkq): Connection handler 0x20004fcc removed
[00:01:26.001,000] <dbg> net_conn.conn_register_debug: (sysworkq): [0x20004fcc/17/2/0x3f] remote fe80::5c00:82ff:fe96:9800/69
[00:01:26.008,000] <dbg> net_conn.conn_register_debug: (sysworkq):   local ::/38166 cb 0x803cd91 ud (nil)
[00:01:26.110,000] <dbg> net_conn.net_conn_input: (rx_q[0]): Check UDP listener for pkt 0x2001497c src port 45641 dst port 38166 family 2
[00:01:26.118,000] <dbg> net_conn.net_conn_input: (rx_q[0]): No match found.
[00:01:28.518,000] <dbg> net_conn.net_conn_unregister: (sysworkq): Connection handler 0x20004fcc removed
[00:01:28.524,000] <dbg> net_conn.conn_register_debug: (sysworkq): [0x20004fcc/17/2/0x3f] remote fe80::5c00:82ff:fe96:9800/69
[00:01:28.531,000] <dbg> net_conn.conn_register_debug: (sysworkq):   local ::/38166 cb 0x803cd91 ud (nil)
[00:01:28.599,000] <dbg> net_conn.net_conn_input: (rx_q[0]): Check UDP listener for pkt 0x2001497c src port 36610 dst port 38166 family 2
[00:01:28.606,000] <dbg> net_conn.net_conn_input: (rx_q[0]): No match found.
```

https://snipboard.io/GhUDEF.jpg

**Temporary workaround:**

Comment out 'continue' on line 698 file connection.c, it disables source port checking; use recvfrom() and sendto() to keep server's port.

### PR DESCRIPTION
**Pull request by mnkp**
- bugfix: Accept initial TFTP server reply from a port different than
  the one used to establish the connection (typically 69) as mandated
  by RFC 1350. Previous implementation was not standard compliant.
- bugfix: close socket in case of error or timeout.
- bugfix: Reset retransmit counter after receipt of a good packet.
- bugfix: Use CONFIG_TFTP_LOG_LEVEL to set log level.
- api: upon successful receipt of the file set `client.user_buf_size`
  to the size of the file received.
- Restructure the code, comments.
- Limit usage of global variables.
- Limit usage of `goto`.

This PR, apart from one necessary exception, does not attempt to modify TFTP API. Consequently not all issues are fixed:
- usage of a large, private static buffer was not removed
- buffer passed as a parameter to `tftp_get` function call has to be large enough to fit the full file, i.e. to receive a file of size up to 64 kB user is forced to reserve 64 kB of RAM.

Fixes #34131

### CODE REVIEW

**Comment by mnkp** [comment]
@olsky, @bwasim

File: subsys/net/lib/tftp/tftp_client.c [hunk 1]
```diff
@@ -5,292 +5,247 @@
...
+LOG_MODULE_REGISTER(tftp_client, CONFIG_TFTP_LOG_LEVEL);
 
-/* Public / Internal TFTP header file. */
+#include <stddef.h>
 #include <net/tftp.h>
 #include "tftp_client.h"
 
+#define ADDRLEN(sock) \
+	(((struct sockaddr *)sock)->sa_family == AF_INET ? \
+		(sizeof(struct sockaddr_in)) : \
```
Comment (jukkar) [inline subsys/net/lib/tftp/tftp_client.c:16]: Extra `()` around `sizeof` are not needed.

File: subsys/net/lib/tftp/tftp_client.c [hunk 2]
```diff
@@ -5,292 +5,247 @@
...
-	tftpc_block_no = 1;
-	tftpc_index    = 0;
-
-	/* Create Socket for TFTP (IPv4 / UDP) */
-	sock = socket(server->sa_family, SOCK_DGRAM, IPPROTO_UDP);
+	int sock;
+	uint32_t tftpc_block_no = 1;
+	uint32_t tftpc_index = 0;
+	int tx_count = 0;
+	struct tftphdr_ack ackhdr = {htons(ACK_OPCODE), htons(1)};
```
Comment (jukkar) [inline subsys/net/lib/tftp/tftp_client.c:158]: better would be set the values using the `.field = value,` notation, then there are no errors if the fields are reorganized in the struct

**Review by jukkar — COMMENTED** [review]
Is this fixing any issues mentioned in #34131?

**Comment by mnkp** [comment]
> Is this fixing any issues mentioned in #34131?

Sorry, I missed the issue. Yes, this PR is fixing the problem described in #34131 including

> Noticed resource leak in tftp_get(), the sock is not closed in the case of error or timeout. Also tftp_lock is not relased in the case of error. We should goto to req_done: label in the case of errors (except the socket() failing)

I will wait a bit for additional reviews before cleaning up this PR.

File: subsys/net/lib/tftp/tftp_client.c [hunk 3]
```diff
@@ -5,292 +5,247 @@
...
+		if (block_no == tftpc_block_no) {
+			uint32_t data_size = rcv_size - TFTP_HEADER_SIZE;
+
+			tftpc_block_no++;
+			ackhdr.block = htons(block_no);
+			tx_count = 0;
+
+			/* Only copy block if user buffer has enough space */
+			if (data_size > (client->user_buf_size - tftpc_index)) {
+				send_err(sock, 0x3, NULL);
```
Comment (rlubos) [inline subsys/net/lib/tftp/tftp_client.c:199]: Could you add a symbol for this magic number?

**Review by rlubos — COMMENTED** [review]
Looks pretty good, not much to comment.

File: subsys/net/lib/tftp/tftp_client.c [hunk 4]
```diff
@@ -5,292 +5,247 @@
...
+
+			/* Perform the actual copy and update the index. */
+			memcpy(client->user_buf + tftpc_index,
+				tftpc_buffer + TFTP_HEADER_SIZE, data_size);
+			tftpc_index += data_size;
+
+			/* Per RFC1350, the end of a transfer is marked
+			 * by datagram size < TFTP_BLOCK_SIZE.
+			 */
+			if (rcv_size < TFTP_BLOCK_SIZE) {
```
Comment (mnkp) [inline subsys/net/lib/tftp/tftp_client.c:212]: Should be `rcv_size < TFTPC_MAX_BUF_SIZE`

**Review by mnkp — COMMENTED** [review]
All pending issues were fixed. I've updated `include/net/tftp.h` to mention that upon successful transfer `client->user_buf_size` will contain received file size.

File: subsys/net/lib/tftp/tftp_client.c (hunk 3 above)
Comment (mnkp) [reply subsys/net/lib/tftp/tftp_client.c]: I've added respective defines to `subsys/net/lib/tftp/tftp_client.h`. The comments describing errors are copied verbatim from [RFC 1350](https://datatracker.ietf.org/doc/html/rfc1350). I expect that falls under fair use. To be on the safe side I can remove them or try to rephrase.

**Review by rlubos — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]
