### PR TITLE
regulator-fixed, regulator-gpio: remove gpio_pin_get_dt calls

### LINKED ISSUE #93012: regulator-gpio: new voltage does not get applied when reading current GPIO state is not possible
### Describe the bug

The current implementation of the `regulator-fixed` read the current state of the GPIO before writing and only changes the state of that GPIO, when it is different from the expected state. This leads to the problem, that a requested new state is not applied when a wrong value is being returned by `gpio_pin_get_dt()` and the voltage change is not effective.

<https://github.com/zephyrproject-rtos/zephyr/blob/e22ca6b132840efb23b4a00ff7718225a0dd9f29/drivers/regulator/regulator_gpio.c#L41-L48>

I tried to use this driver with a nRF9151 and noticed, that it somehow did lock up in one specific state. The nRF9151 does actually disconnect the input buffer when configured as output. This can also be seen on the diagram of how the pins on a nRF9151 work.

Image

The nRF9151 allows to enable the input driver while being configured as output. The driver expects in this case that `gpio_pin_configure()` the `GPIO_OUTPUT` and `GPIO_INPUT` flags are being set.

<https://github.com/zephyrproject-rtos/zephyr/blob/e22ca6b132840efb23b4a00ff7718225a0dd9f29/drivers/gpio/gpio_nrfx.c#L187-L192>

To allow the `regulator-gpio` driver to work with nordic micro controllers, i see two possible improvements, which would solve this:
- Don't check the current state of the GPIO before setting it, or allow to disable this behavior
- Set `GPIO_OUTPUT` and `GPIO_INPUT` flags when configuring the control GPIOs

### Regression

- [ ] This is a regression.

### Steps to reproduce

- Connect a GPIO controlled voltage regulator to a nordic micro controller(or any micro controller not allowing read back from outputs by default)
- Configure the voltage regulator as `regulator-gpio` in the device tree
- Change the requested voltage e.g. via the regulator-shell and observe, that certain voltages won't change even when requested

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- MCU: nRF9151
- SDK: nRF Connect SDK 3.0.1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by seov-nordic**
On some platforms configuring a GPIO pin as OUTPUT disconnects the input buffer. In this case we cannot rely on reading the current pin state with a `gpio_pin_get_dt` call. This removes these calls as well as modifies the initialization procedure for `regulator-fixed` and `regulator-gpio` to configure the `enable` pin to a known state ~~(INACTIVE) without the need to read it before calling `regulator_common_init` (with `is_enabled=false`).~~ based on the `REGULATOR_INIT_ENABLED` flag before calling `regulator_common_init` with `is_enabled` reflecting the actual state

Fixes #93012

### CODE REVIEW

**Comment by rvoell-7lab** [comment]
I would love to see this being merged. Its only a small fix, but would make the `regulator-fixed` and `regulator-gpio` actually useful.

File: drivers/regulator/regulator_fixed.c [hunk 1]
```diff
@@ -94,22 +93,14 @@ static int regulator_fixed_init(const struct device *dev)
 			return -ENODEV;
 		}
 
-		int ret = gpio_pin_configure_dt(&cfg->enable, GPIO_OUTPUT);
+		int ret = gpio_pin_configure_dt(&cfg->enable, GPIO_OUTPUT_INACTIVE);
```
Comment (seov-nordic) [inline drivers/regulator/regulator_fixed.c]: There is one caveat here that a colleague of mine pointed out - the regulator might already be enabled before this is called (e.g. by a bootloader or similar)... so it isn't great to always initialise this to the inactive state. The previous solution at least tried to get the current state, but, as seen in the issue this addresses, it doesn't always work.

I am actually a bit lost here and not sure if this can be solved properly with current GPIO API...

**Comment by seov-nordic** [comment]
> I would love to see this being merged. Its only a small fix, but would make the `regulator-fixed` and `regulator-gpio` actually useful.

I will try to get more reviewers

File: drivers/regulator/regulator_fixed.c (hunk 1 above)
Comment (rvoell-7lab) [reply drivers/regulator/regulator_fixed.c]: Hmm, I see.

My understanding is, that this is what the [regulator-boot-on and regulator-boot-of](https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/regulator/regulator.yaml#L54-L67) devicetree properties are for. Maybe this property needs to be evaluated during initialization of the GPIO pin here and not only in `regulator_common_init()`.

Yes, these properties don't resolve this autonomously. I think that without actually transferring the information from the bootloader to the firmware, this can not be solved in a portable way.

**Review by bjarki-andreasen — DISMISSED** [review]

**Review by rvoell-7lab — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

File: drivers/regulator/regulator_fixed.c [hunk 2]
```diff
@@ -90,7 +90,8 @@ static DEVICE_API(regulator, regulator_fixed_api) = {
 static int regulator_fixed_init(const struct device *dev)
 {
 	const struct regulator_fixed_config *cfg = dev->config;
-	bool is_enabled = false;
+	const bool should_enable = cfg->common.flags & REGULATOR_INIT_ENABLED;
```
Comment (nordic-auko) [inline drivers/regulator/regulator_fixed.c:93]: If I understand correctly, this means that the regulator is actively disabled if neither `regulator-boot-on` or `regulator-always-on` dts properties are set. The API seems a bit ambiguous if `regulator-boot-off` isn't set either. I don't have an issue with this behavior, I just wanted to clarify that this is the intention.

**Review by nordic-auko — APPROVED** [review]

File: drivers/regulator/regulator_fixed.c (hunk 2 above)
Comment (seov-nordic) [reply drivers/regulator/regulator_fixed.c:93]: yeah, I recognise this, it's just that if we say that if neither of the aforementioned properties is set we keep the given regulator as it is, we again run into the original problem of not knowing the pin state and hence the value of `is_enabled` to pass to the common init function :(
