### PR TITLE
subsys: power: decouple device power management and specific board

### LINKED ISSUE #28099: subsys: power: device implicit depends on CONFIG_SYS_POWER_MANAGEMENT
**Describe the bug**
When try using subsys:shell on a device that have Power Management capabilities **device_pm_state_str** doesn't compile. Some investigation shows that subsys/power/device.c compile only when CONFIG_SYS_POWER_MANAGEMENT is enabled.
However, SYS_POWER_MANAGEMENT and DEVICE_POWER_MANAGEMENT are independent on the subsys/power/Kconfig.

https://github.com/zephyrproject-rtos/zephyr/blob/016b5422d90e9d3405eda22da4fda23d6a13a415/subsys/shell/modules/device_service.c#L101-L110

https://github.com/zephyrproject-rtos/zephyr/blob/016b5422d90e9d3405eda22da4fda23d6a13a415/subsys/power/device.c#L13

**To Reproduce**
See #28094

**Expected behavior**
If sys PM and dev PM are independent things, the subsys/power/device.c should be adjusted. Otherwise, when users select DEVICE_POWER_MANAGEMENT, the SYS_POWER_MANAGEMENT should be selected to avoid problems. However, it is expected that some SoC does't have proper clocks and PM implemented on Zephyr and this should be treat accordly.

The path to add a new SoC in general is a long journey and maybe flag like SOC_SERIES_HAS_PM could help to avoid problems. A gracious build error message with some information that device driver PM could not be enabled because SoC doesn't have PM implemented will be enough to uses understand the situation.

**Impact**
Device Power Management is not independent right now on Zephy. Any Power Management feature will only work for those devices that define **core_devices** hard coded at `device.c` and there is no possible to use device PM on boards that don't implement sys PM.

https://github.com/zephyrproject-rtos/zephyr/blob/016b5422d90e9d3405eda22da4fda23d6a13a415/subsys/power/device.c#L18-L54

This could bring a lot of unnecessary issues after release 2.40.

Ex.: Try use a SPI_FLASH_AT45 NOR with PM activated on a SoC that doesn't have sys PM implemented.

**Logs and console output**
```
home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c
/home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c:53:2: error: #error "Add SoC's core devices list for PM"
   53 | #error "Add SoC's core devices list for PM"
      |  ^~~~~
/home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c:68:32: error: 'MAX_PM_DEVICES' undeclared here (not in a function)
   68 | static device_idx_t pm_devices[MAX_PM_DEVICES];
      |                                ^~~~~~~~~~~~~~
In file included from ../include/sched_priq.h:9,
                 from ../include/kernel_includes.h:23,
                 from ../include/kernel.h:17,
                 from ../include/zephyr.h:18,
                 from /home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c:7:
/home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c: In function 'sys_pm_create_device_list':
/home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c:163:22: error: 'core_devices' undeclared (first use in this function); did you mean 'pm_devices'?
  163 |  num_pm = ARRAY_SIZE(core_devices);
      |                      ^~~~~~~~~~~~
../include/sys/util.h:67:66: note: in definition of macro 'ZERO_OR_COMPILE_ERROR'
   67 | #define ZERO_OR_COMPILE_ERROR(cond) ((int) sizeof(char[1 - 2 * !(cond)]) - 1)
      |                                                                  ^~~~
../include/sys/util.h:98:11: note: in expansion of macro 'IS_ARRAY'
   98 |  ((long) (IS_ARRAY(array) + (sizeof(array) / sizeof((array)[0]))))
      |           ^~~~~~~~
/home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c:163:11: note: in expansion of macro 'ARRAY_SIZE'
  163 |  num_pm = ARRAY_SIZE(core_devices);
      |           ^~~~~~~~~~
/home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c:163:22: note: each undeclared identifier is reported only once for each function it appears in
  163 |  num_pm = ARRAY_SIZE(core_devices);
      |                      ^~~~~~~~~~~~
../include/sys/util.h:67:66: note: in definition of macro 'ZERO_OR_COMPILE_ERROR'
   67 | #define ZERO_OR_COMPILE_ERROR(cond) ((int) sizeof(char[1 - 2 * !(cond)]) - 1)
      |                                                                  ^~~~
../include/sys/util.h:98:11: note: in expansion of macro 'IS_ARRAY'
   98 |  ((long) (IS_ARRAY(array) + (sizeof(array) / sizeof((array)[0]))))
      |           ^~~~~~~~
/home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c:163:11: note: in expansion of macro 'ARRAY_SIZE'
  163 |  num_pm = ARRAY_SIZE(core_devices);
      |           ^~~~~~~~~~
At top level:
/home/gfbudke/zephyros/mainline/zephyr/subsys/power/device.c:68:21: warning: 'pm_devices' defined but not used [-Wunused-variable]
   68 | static device_idx_t pm_devices[MAX_PM_DEVICES];
      |                     ^~~~~~~~~~
[58/148] Building C object zephyr/arch/common/CMakeFiles/isr_tables.dir/isr_tables.c.obj
```
**Environment (please complete the following information):**
 - OS: Linux
 - Zephyr SDK 0.11.3
 - 2.4.0-rc1

### PR DESCRIPTION
**Pull request by mengxianglinx**
When try to enable CONFIG_DEVICE_POWER_MANAGEMENT for a board,
the #error directive in subsys/power/device.c requires that
"MAX_PM_DEVICE" and "core_devices[]" must be defined exactly in that
file, or a compile error will come up.
For flexibility, this patch move "MAX_PM_DEVICE" to Kconfig and define
a weak version of "core_devices[]", so any board or SOC can define
these varibles in their own module.

Signed-off-by: Meng xianglin <xianglinx.meng@intel.com>

Fixes #28099

### CODE REVIEW

File: subsys/power/device.c [hunk 1]
```diff
@@ -50,7 +50,8 @@ static const char *const core_devices[] = {
 	"sys_clock",
 };
 #else
-#error "Add SoC's core devices list for PM"
+#define MAX_PM_DEVICES CONFIG_MAX_PM_DEVICES
+__weak const char *const core_devices[] = {"",};
```
Comment (pabigot) [inline subsys/power/device.c:54]: I don't think this is a good API.  `core_devices` should not be a global symbol.  It could be changed to `z_core_devices` or something that's namespaced.

Also the relation between the array and its size is too fragile.  I think a case can be made to allow an external override via a weak symbol, but the number of devices should be detected by a terminal null pointer rather than a configuration-time constant.

**Review by pabigot — CHANGES_REQUESTED** [review]

File: subsys/power/device.c (hunk 1 above)
Comment (mengxianglinx) [reply subsys/power/device.c:54]: Thank you @pabigot , I once considered to do it like this:

extern const char *const *z_core_devices; (a null terminated array )
static const char* const *core_devices = z_core_devices;

then change all core_devices[] in this file to a null terminated array
in sys_pm_create_device_list() enumerate core_devices by "if(core_devices[i])"
ensure size of core_devices less than MAX_PM_DEVICES by assert.

what do you think about that?

Comment (pabigot) [reply subsys/power/device.c:54]: For the list of core devices specifically I think it can be slightly simpler and more flexible if you do something like the top commit of https://github.com/pabigot/zephyr/commits/proposed/28106.  That depends on a Kconfig `PM_MAX_DEVICES` similar to the one you have here (the name should start with a subsystem, could be `POWER_MAX_DEVICES`), and uses the `z_pm_core_devices` directly.  And simplifies how the defaults are set.

Something like that, at any rate.  You can incorporate that patch into your PR if you wish (it hasn't been tested at all).  The other ideas are fine.

This whole thing should go away soon so it's not too critical to get it perfect.

Comment (mengxianglinx) [reply subsys/power/device.c]: Good idea @pabigot . I try to base my patch on your https://github.com/pabigot/zephyr/commits/proposed/28106 but failed, so I include your modifications in that patch into my patch, do you mind that?

Comment (pabigot) [reply subsys/power/device.c]: I don't mind, this looks much better.  Thanks.

**Review by pabigot — APPROVED** [review]

**Review by wentongwu — APPROVED** [review]
