### PR TITLE
Bluetooth: ATT: Fix not restoring buffer state when send fails

### LINKED ISSUE #27434: Bluetooth: L2CAP: buffer use after free
**Describe the bug**
Commit f4192bda26a1c7770e3d4c50235a6760f0506a0d ("Bluetooth: ATT: Add support EATT bearer") changed bt_att_sent() implementation, so packets that were not successfully sent are pushed back to queue:
```
		if (chan_send(chan, buf, NULL) < 0) {
			/* Push it back if it could not be send */
			k_queue_prepend(&att->tx_queue._queue, buf);
			break;
		}
```
There is however a problem in `chan_send` -> `bt_l2cap_send_cb` path, because buffer is being modified there (prepended with 4 header bytes in `bt_l2cap_send_cb()`) and freed (in `bt_conn_send_cb()`) when buffer is not sent successfully (e.g. no connection).

**To Reproduce**
Used `mcumgr` with `image list` command and a custom application + custom board. Target crashes when `mcumgr` disconnects because of timeout. Can provide more info if needed, but I think that bug is clear enough to notice looking at the code only.

**Expected behavior**
Getting rid of "use after free".

**Impact**
Undefined behavior (e.g. MPU FAULT crashes).

**Logs and console output**
With some additional logs enabled:
```
[00:00:23.386,566] <inf> bt_l2cap: conn 0x200044d0 cid 4 buf 0x2001c838 len 23                                                       
[00:00:23.386,566] <inf> bt_l2cap: hdr 0x2001ebfc                                                                                    
[00:00:23.386,596] <inf> bt_l2cap: enter send_cb                                                                                     
[00:00:23.386,596] <err> bt_conn: not connected!
[00:00:23.386,596] <inf> bt_l2cap: exit send_cb -128                                                                                 
[00:00:23.386,596] <inf> bt_att: push back 0x2001c838 ref 0                                                                          
[00:00:23.386,627] <inf> bt_l2cap: conn 0x200044d0 cid 4 buf 0x2001c838 len 27                                                       
[00:00:23.386,657] <inf> bt_l2cap: buf                                                                                               
00 8e 01 20 e1 d5 00 00  4f bc 03 00 1d d6 00 00 |... .... O.......                                                                  
1d d6 00 00 1d d6 00 00  1d d6 00                |........ ...                                                                       
[00:00:23.386,657] <inf> bt_att: push back 0x2001c838 ref 0                                                                          
[00:00:23.386,688] <inf> bt_l2cap: conn 0x200044d0 cid 4 buf 0x2001c838 len 27                                                       
[00:00:23.386,718] <inf> bt_l2cap: buf                                                                                               
00 8e 01 20 e1 d5 00 00  4f bc 03 00 1d d6 00 00 |... .... O.......                                                                  
1d d6 00 00 1d d6 00 00  1d d6 00                |........ ...                                                                       
[00:00:23.386,718] <inf> bt_att: push back 0x2001c838 ref 0                                                                          
[00:00:23.386,779] <wrn> bt_att: Not connected
[00:00:23.386,871] <err> os: ***** MPU FAULT *****
[00:00:23.386,871] <err> os:   Instruction Access Violation
[00:00:23.386,871] <err> os: r0/a1:  0x200132fc  r1/a2:  0x00000002  r2/a3:  0x000022b3
[00:00:23.386,901] <err> os: r3/a4:  0xd4bd0881 r12/ip:  0x00000000 r14/lr:  0x00047be3
[00:00:23.386,901] <err> os:  xpsr:  0x41000000
[00:00:23.386,901] <err> os: Faulting instruction address (r15/pc): 0xd4bd0880
[00:00:23.386,901] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:23.386,932] <err> os: Current thread: 0x20005548 (sysworkq)
[00:00:23.584,106] <err> os: Halting system
```
Notice increased length and 0 reference count of net_buf being pushed back to queue.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA (current tip of master): 2505daf28f378aa968cd4e4a7fbdeaaf3eeeeaa8

**Additional context**

### PR DESCRIPTION
**Pull request by Vudentz**
Since bt_l2cap_send_cb can fail returning its error is not enough as
the buffer has been modified to add the headers, so this save the state
before calling bt_conn_send_cb and takes a reference so it can be
restored its original state in case of error.

Fixes #27434

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

File: subsys/bluetooth/host/l2cap.c [hunk 1]
```diff
@@ -582,14 +582,25 @@ int bt_l2cap_send_cb(struct bt_conn *conn, uint16_t cid, struct net_buf *buf,
...
 	hdr->len = sys_cpu_to_le16(buf->len - sizeof(*hdr));
 	hdr->cid = sys_cpu_to_le16(cid);
 
-	return bt_conn_send_cb(conn, buf, cb, user_data);
+	err = bt_conn_send_cb(conn, buf, cb, user_data);
+	if (!err) {
+		return 0;
+	}
+
+	net_buf_simple_restore(&buf->b, &state);
```
Comment (mniestroj) [inline subsys/bluetooth/host/l2cap.c:601]: Buffer is most probably freed at this point with `net_buf_unref(buf);` inside `bt_conn_send_cb()`. So any operation at buffer is undefined in results.

**Review by mniestroj — COMMENTED** [review]
This doesn't fix #27434 yet, but it might be one step closer to doing so.

File: subsys/bluetooth/host/l2cap.c (hunk 1 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c:603]: Just fixed that.

File: subsys/bluetooth/host/l2cap.c [hunk 2]
```diff
@@ -582,14 +582,27 @@ int bt_l2cap_send_cb(struct bt_conn *conn, uint16_t cid, struct net_buf *buf,
...
 
+	net_buf_simple_save(&buf->b, &state);
+
 	hdr = net_buf_push(buf, sizeof(*hdr));
 	hdr->len = sys_cpu_to_le16(buf->len - sizeof(*hdr));
 	hdr->cid = sys_cpu_to_le16(cid);
 
-	return bt_conn_send_cb(conn, buf, cb, user_data);
+	/* Take a ref since bt_conn_send_cb takes ownership of the buffer */
+	err = bt_conn_send_cb(conn, net_buf_ref(buf), cb, user_data);
```
Comment (mniestroj) [inline subsys/bluetooth/host/l2cap.c:597]: Right now `buf` will not be freed in case of error. This solves one case when user expects such behavior. But there are other places where `bt_l2cap_send_cb` is called and in those places expect unrefed buffer.

Function documentation also say about unrefing:
```
/* Send L2CAP PDU over a connection
 *
 * Buffer ownership is transferred to stack so either in case of success
 * or error the buffer will be unref internally.
 *
 * Calling this from RX thread is assumed to never fail so the return can be
 * ignored.
 */
int bt_l2cap_send_cb(struct bt_conn *conn, uint16_t cid, struct net_buf *buf,
		     bt_conn_tx_cb_t cb, void *user_data);
```

**Review by mniestroj — DISMISSED** [review]
So far changes fix one single problem, but cause more harm in other cases. See my comments.

File: subsys/bluetooth/host/l2cap.c (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c:597]: This is no longer the case, it can fail as you are experiencing, I can update the documentation if that is your problem with it.

Comment (mniestroj) [reply subsys/bluetooth/host/l2cap.c:597]: Documentation would be wrong, so yes, it needs update. Another thing is that other places such as `smp_br_send()` and `smp_send()` in `subsys/bluetooth/host/smp.c` expect buffer to be unreferenced.

Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c:597]: Yep, I guess we would need to ref it from ATT then but then the whole logic of save/restore would need to be done by in att.c.

Comment (mniestroj) [reply subsys/bluetooth/host/l2cap.c:597]: So in general I don't think `Bluetooth: L2CAP: Fix not restoring buffer state when send fails` commit title is valid. Documentation says about taking ownership and unreferencing buffer, so state of unrefed buffer is invalid anyway. So it is more like user of `bt_l2cap_send_cb()` is not doing the right thing, by trying to reuse the buffer. If that needs to be changed, than we need to look at whole codebase.

Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Ive updated it to be just affect ATT code.

File: subsys/bluetooth/host/att.c [hunk 3]
```diff
@@ -198,10 +198,23 @@ static int chan_send(struct bt_att_chan *chan, struct net_buf *buf,
...
+	/* Take a ref since bt_l2cap_send_cb takes ownership of the buffer */
+	err = bt_l2cap_send_cb(chan->att->conn, BT_L2CAP_CID_ATT,
+				net_buf_ref(buf), att_cb(chan->sent),
+				&chan->chan.chan);
+	if (!err) {
+		net_buf_unref(buf);
+		return 0;
+	}
+
+	net_buf_simple_restore(&buf->b, &state);
```
Comment (mniestroj) [inline subsys/bluetooth/host/att.c:214]: Seems fine now, with one exception. I am looking at `chan_req_send()` and this fragment:
```
	/* Keep a reference for resending in case of an error */
	err = chan_send(chan, net_buf_ref(req->buf), NULL);
	if (err) {
		net_buf_unref(req->buf);
		chan->req = NULL;
	}
```
seems suspicious to me. First of all "keep reference for resending in case of error" does not match what the code does: buffer will be referenced first, then unreferenced when error occurs - as a result buffer will be freed. Additionally properly sent buffer will be leaked, as all `chan_req_send` callers expect buffer to be freed/consumed.

Comment (Vudentz) [reply subsys/bluetooth/host/att.c:214]: The resending logic it mentions is for the request itself, in case it is not for chan_send, the buffer is release at att_handle_rsp, we wouldn't keep a reference in bt_att_req if we expected it to be consumed. That said the error path seems wrong now, it would not free the buffer just the extra reference, what we should do is only take a reference if chan_send succeeds.

Comment (Vudentz) [reply subsys/bluetooth/host/att.c:214]: Actually we always do prepend it back to att->reqs in case of an error, so it looks like it was broken already as release the reference and reset the req->buf to NULL, weird that we didn't hit this before though.

Comment (Vudentz) [reply subsys/bluetooth/host/att.c:214]: Ive end up fixing the behavior of chan_req_send so it doesn't reset the req->buf to NULL.

**Comment by Vudentz** [comment]
@joerchan @jhedberg any comments? I guess we want to process this one quickly given it fixes a high priority bug.

**Comment by joerchan** [comment]
@mniestroj Can you please confirm that the updated PR fixes the reported issue?

**Review by joerchan — APPROVED** [review]

**Review by mniestroj — COMMENTED** [review]
I can confirm that this PR fixes linked issue.

**Comment by Vudentz** [comment]
@jhedberg any comments on this one?

**Review by jhedberg — APPROVED** [review]
This seems like an appropriate thing to do to me (i.e. there shouldn't be side-effects to the buffer in the case of an error)
