### PR TITLE
Shell fix crashing tab button

### LINKED ISSUE #28434: Shell Tab Completion Candidates results in segmentation fault
**Describe the bug**
This was found using the Bluetooth Shell (`/tests/bluetooth/shell/`). Attempting to tab to find completion candidates, i.e. tab after a space, results in a segmentation fault. 

**To Reproduce**
1. build the `/tests/bluetooth/shell/` project (e.g. `west build -b native_posix /tests/bluetooth/shell/`) 
2. Run the shell .exe (e.g. with Valgrind to get the logs below)
3. enter `bt ` and press tab

**Expected behavior**
Expected to see the possible `bt` subcommands. 

**Impact**
Major annoyance when using the shell, as the shell will exit sometimes if pressing tab at the wrong times. 

**Logs and console output**
```
UART_0 connected to pseudotty: /dev/pts/9
Warning: locale not supported by Xlib, locale set to C
*** Booting Zephyr OS build v2.4.0-rc1-135-g1a7cd6ddbdcc  ***
Type "help" for supported commands.Before any Bluetooth commands you must `bt init` to initialize the stack.
==39871== Thread 2:
==39871== Conditional jump or move depends on uninitialised value(s)
==39871==    at 0x11D73F: shell_strlen (shell_utils.h:31)
==39871==    by 0x11E2EA: find_completion_candidates (shell.c:298)
==39871==    by 0x11E2EA: tab_handle (shell.c:763)
==39871==    by 0x11E2EA: state_collect (shell.c:941)
==39871==    by 0x11E2EA: shell_process (shell.c:1355)
==39871==    by 0x11D94F: shell_signal_handle (shell.c:1190)
==39871==    by 0x11EDE4: shell_thread (shell.c:1244)
==39871==    by 0x11EDE4: shell_thread (shell.c:1200)
==39871==    by 0x11A695: z_thread_entry (thread_entry.c:29)
==39871==    by 0x1264CB: posix_thread_starter (posix_core.c:305)
==39871==    by 0x494C627: start_thread (in /usr/lib32/libpthread-2.32.so)
==39871==    by 0x4A6EC89: clone (in /usr/lib32/libc-2.32.so)
==39871==  Uninitialised value was created by a stack allocation
==39871==    at 0x11E070: shell_process (shell.c:1336)
==39871== 
==39871== Use of uninitialised value of size 4
==39871==    at 0x483CB48: strlen (vg_replace_strmem.c:459)
==39871==    by 0x11D74C: shell_strlen (shell_utils.h:31)
==39871==    by 0x11E2EA: find_completion_candidates (shell.c:298)
==39871==    by 0x11E2EA: tab_handle (shell.c:763)
==39871==    by 0x11E2EA: state_collect (shell.c:941)
==39871==    by 0x11E2EA: shell_process (shell.c:1355)
==39871==    by 0x11D94F: shell_signal_handle (shell.c:1190)
==39871==    by 0x11EDE4: shell_thread (shell.c:1244)
==39871==    by 0x11EDE4: shell_thread (shell.c:1200)
==39871==    by 0x11A695: z_thread_entry (thread_entry.c:29)
==39871==    by 0x1264CB: posix_thread_starter (posix_core.c:305)
==39871==    by 0x494C627: start_thread (in /usr/lib32/libpthread-2.32.so)
==39871==    by 0x4A6EC89: clone (in /usr/lib32/libc-2.32.so)
==39871==  Uninitialised value was created by a stack allocation
==39871==    at 0x11E070: shell_process (shell.c:1336)
==39871== 
==39871== Use of uninitialised value of size 4
==39871==    at 0x483CB53: strlen (vg_replace_strmem.c:459)
==39871==    by 0x11D74C: shell_strlen (shell_utils.h:31)
==39871==    by 0x11E2EA: find_completion_candidates (shell.c:298)
==39871==    by 0x11E2EA: tab_handle (shell.c:763)
==39871==    by 0x11E2EA: state_collect (shell.c:941)
==39871==    by 0x11E2EA: shell_process (shell.c:1355)
==39871==    by 0x11D94F: shell_signal_handle (shell.c:1190)
==39871==    by 0x11EDE4: shell_thread (shell.c:1244)
==39871==    by 0x11EDE4: shell_thread (shell.c:1200)
==39871==    by 0x11A695: z_thread_entry (thread_entry.c:29)
==39871==    by 0x1264CB: posix_thread_starter (posix_core.c:305)
==39871==    by 0x494C627: start_thread (in /usr/lib32/libpthread-2.32.so)
==39871==    by 0x4A6EC89: clone (in /usr/lib32/libc-2.32.so)
==39871==  Uninitialised value was created by a stack allocation
==39871==    at 0x11E070: shell_process (shell.c:1336)
==39871== 
==39871== Use of uninitialised value of size 4
==39871==    at 0x483D1BB: strncmp (vg_replace_strmem.c:647)
==39871==    by 0x11E343: is_completion_candidate (shell.c:289)
==39871==    by 0x11E343: find_completion_candidates (shell.c:308)
==39871==    by 0x11E343: tab_handle (shell.c:763)
==39871==    by 0x11E343: state_collect (shell.c:941)
==39871==    by 0x11E343: shell_process (shell.c:1355)
==39871==    by 0x11D94F: shell_signal_handle (shell.c:1190)
==39871==    by 0x11EDE4: shell_thread (shell.c:1244)
==39871==    by 0x11EDE4: shell_thread (shell.c:1200)
==39871==    by 0x11A695: z_thread_entry (thread_entry.c:29)
==39871==    by 0x1264CB: posix_thread_starter (posix_core.c:305)
==39871==    by 0x494C627: start_thread (in /usr/lib32/libpthread-2.32.so)
==39871==    by 0x4A6EC89: clone (in /usr/lib32/libc-2.32.so)
==39871==  Uninitialised value was created by a stack allocation
==39871==    at 0x11E070: shell_process (shell.c:1336)
==39871== ==39871== Invalid read of size 1
==39871==    at 0x483CB48: strlen (vg_replace_strmem.c:459)
==39871==    by 0x11D74C: shell_strlen (shell_utils.h:31)
==39871==    by 0x11E2EA: find_completion_candidates (shell.c:298)
==39871==    by 0x11E2EA: tab_handle (shell.c:763)
==39871==    by 0x11E2EA: state_collect (shell.c:941)
==39871==    by 0x11E2EA: shell_process (shell.c:1355)
==39871==    by 0x11D94F: shell_signal_handle (shell.c:1190)
==39871==    by 0x11EDE4: shell_thread (shell.c:1244)
==39871==    by 0x11EDE4: shell_thread (shell.c:1200)
==39871==    by 0x11A695: z_thread_entry (thread_entry.c:29)
==39871==    by 0x1264CB: posix_thread_starter (posix_core.c:305)
==39871==    by 0x494C627: start_thread (in /usr/lib32/libpthread-2.32.so)
==39871==    by 0x4A6EC89: clone (in /usr/lib32/libc-2.32.so)
==39871==  Address 0x1 is not stack'd, malloc'd or (recently) free'd
==39871== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==39871==  Access not within mapped region at address 0x1
==39871==    at 0x483CB48: strlen (vg_replace_strmem.c:459)
==39871==    by 0x11D74C: shell_strlen (shell_utils.h:31)
==39871==    by 0x11E2EA: find_completion_candidates (shell.c:298)
==39871==    by 0x11E2EA: tab_handle (shell.c:763)
==39871==    by 0x11E2EA: state_collect (shell.c:941)
==39871==    by 0x11E2EA: shell_process (shell.c:1355)
==39871==    by 0x11D94F: shell_signal_handle (shell.c:1190)
==39871==    by 0x11EDE4: shell_thread (shell.c:1244)
==39871==    by 0x11EDE4: shell_thread (shell.c:1200)
==39871==    by 0x11A695: z_thread_entry (thread_entry.c:29)
==39871==    by 0x1264CB: posix_thread_starter (posix_core.c:305)
==39871==    by 0x494C627: start_thread (in /usr/lib32/libpthread-2.32.so)
==39871==    by 0x4A6EC89: clone (in /usr/lib32/libc-2.32.so)
==39871==  If you believe this happened as a result of a stack
==39871==  overflow in your program's main thread (unlikely but
==39871==  possible), you can try to increase the size of the
==39871==  main thread stack using the --main-stacksize= flag.
==39871==  The main thread stack size used in this run was 8388608.
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.11.3
 - Commit SHA: `1a7cd6ddbdcce8a099f0bcbb8179e47aa185216d`

**Additional context**
I I don't which commit(s) causes this, but the issue is non-existing on commit `d6fa062a7d3fe322dd50d4e4371f49b6283a0185`

### PR DESCRIPTION
**Pull request by jakub-uC**
Commit 770f232a670b2f4bc359886dc3dc03f53ca2bd62 removes an array termination from the shell_make_argv function. This function was called from two functions: `execute` and `tab_handle`. In the mentioned commit termination was added only in the `execute` function.  As a result calling `tab_handle` function was causing a segmentation fault. This fix adds array termination to the`tab_handle` function.

Fixes #28434

### CODE REVIEW

File: subsys/shell/shell.c [hunk 1]
```diff
@@ -248,6 +248,13 @@ static bool tab_prepare(const struct shell *shell,
 	(void)shell_make_argv(argc, *argv, shell->ctx->temp_buff,
 			      CONFIG_SHELL_ARGC_MAX);
 
+	if (*argc > CONFIG_SHELL_ARGC_MAX) {
+		return false;
+	}
+
+	/* terminate arguments with NULL */
+	(*argv)[*argc] = NULL;
```
Comment (nordic-krch) [inline subsys/shell/shell.c:256]: do we need this? maybe early leave when argc exceeds is enough?

**Review by nordic-krch — APPROVED** [review]

File: subsys/shell/shell.c (hunk 1 above)
Comment (jakub-uC) [reply subsys/shell/shell.c:256]: Yes, this change is needed to avoid calling `strcmp` with `argv[argc]` as an argument when it has random data.

**Review by de-nordic — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
Tested to work. LGTM.

**Review by erwango — APPROVED** [review]
Tested OK
