### PR TITLE
Bluetooth: ascs: Fix ASE invalid state transition

### LINKED ISSUE #44004: Bluetooth: ascs: Invalid ASE state transition: Releasing -> QoS Configured
**Describe the bug**
The ASE state transition: Releasing -> QoS Configured is invalid and not allowed by the ASCS specification. 

**To Reproduce**
1. Enter Streaming state
2. Receive Release
3. See the IUT goes to Releasing state
4. Once ISO is disconnected, the ASE state is changed to QoS Configured state (invalid behavior)

**Expected behavior**
ASE should go to Codec Configured state

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
< ACL Data TX: Handle 0 flags 0x00 dlen 14                                                                                                                                                                                           #2853 [hci1] 1175.114040
      Channel: 85 len 10 sdu 8 [PSM 39 mode Enhanced Credit (0x81)] {chan 11}
      ATT: Handle Value Notification (0x1b) len 7
        Handle: 0x001c
          Data: 0801010000
        ASCS: Audio Stream Endpoint Control Point (Handle: 0x001c)
        Operation response: Release
        Number of ASEs: 1
         ASE ID: 1
          Response code: Success
< ACL Data TX: Handle 0 flags 0x00 dlen 12                                                                                                                                                                                           #2854 [hci1] 1175.114151
      LE L2CAP: LE Flow Control Credit (0x16) ident 27 len 4
        Source CID: 64
        Credits: 1
< ACL Data TX: Handle 0 flags 0x00 dlen 11                                                                                                                                                                                           #2855 [hci1] 1175.115254
      Channel: 84 len 7 sdu 5 [PSM 39 mode Enhanced Credit (0x81)] {chan 10}
      ATT: Handle Value Notification (0x1b) len 4
        Handle: 0x0016
          Data: 0106
        ASCS: Audio Stream Sink Endpoint (Handle: 0x0016)
        ASE ID: 1
        Releasing
> HCI Event: Disconnect Complete (0x05) plen 4                                                                                                                                                                                       #2859 [hci1] 1175.197932
        Status: Success (0x00)
        Handle: 2
        Reason: Remote User Terminated Connection (0x13)
< ACL Data TX: Handle 0 flags 0x00 dlen 26                                                                                                                                                                                           #2860 [hci1] 1175.201373
      Channel: 85 len 22 sdu 20 [PSM 39 mode Enhanced Credit (0x81)] {chan 11}
      ATT: Handle Value Notification (0x1b) len 19
        Handle: 0x0016
          Data: 0102010010270000022800020a00204e00
        ASCS: Audio Stream Sink Endpoint (Handle: 0x0016)
        ASE ID: 1
        QoS configured
          CIG ID: 1
          CIS ID: 0
          SDU interval: 10000
          Framing: Unframed
          LE PHY (0x02)
            LE 2M PHY
          Maximum SDU size: 40
          Retransmission number: 2
          Transport latency: 10 ms
          Presentation delay: 20000

```

[state_transition.zip](https://github.com/zephyrproject-rtos/zephyr/files/8314031/state_transition.zip)

### PR DESCRIPTION
**Pull request by MariuszSkamra**
This fixes issue where, the ASE went directly to QoS Configured state
when in Releasing state and the ISO link has been disconnected.

To not change the current behavior, the transition from Streaming state
has been unchanged, but rather fixed depending on the ASE direction.

Fixes: #44004
Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>

### CODE REVIEW

File: subsys/bluetooth/audio/ascs.c [hunk 1]
```diff
@@ -338,11 +337,24 @@ static void ascs_iso_disconnected(struct bt_iso_chan *chan, uint8_t reason)
 		BT_WARN("No callback for stopped set");
 	}
 
-	ascs_ep_set_state(ep, BT_AUDIO_EP_STATE_QOS_CONFIGURED);
+	if (ep->status.state == BT_AUDIO_EP_STATE_RELEASING) {
+		ascs_ep_set_state(ep, BT_AUDIO_EP_STATE_CODEC_CONFIGURED);
+	} else { /* Streaming or Enabling */
```
Comment (Thalley) [inline subsys/bluetooth/audio/ascs.c:342]: Should we have proper state checks, instead of a comment (`/* Streaming or Enabling */`)?

Comment (MariuszSkamra) [reply subsys/bluetooth/audio/ascs.c:342]: > Should we have proper state checks, instead of a comment (`/* Streaming or Enabling */`)?

I will remove the comment as the CIS can exist in disabling and qos configured state as well

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
