### PR TITLE
sensor: lis2dh: cache CTRL1 on PM_DEVICE_ACTION_TURN_ON

### LINKED ISSUE #92196: LIS2DH initialization enables and then immediately disables accelerometer.
### Describe the bug

On June 16th 2025, a commit for the LIS2DH was merged in that changed the initialization sequence for the accelerometer. For some reason, it's not letting me reference the commit or PR directly in this bug report, but the author was @petrosyan-van 

As part of the new initialization sequence, the accelerometer is "turned on" (PM_DEVICE_ACTION_TURN_ON), and the accelerometer is enabled and a value is written to the CTRL1 register.

The snippet for PM_DEVICE_ACTION_TURN_ON:
``` C	
case PM_DEVICE_ACTION_TURN_ON:
		status = lis2dh_init_chip(dev);
		break;
````

The snippet where CTRL1 is set, using bits that were derived from the project config:
``` C
	/* Initialize control register ctrl1 to ctrl 6 to default boot values
	 * to avoid warm start/reset issues as the accelerometer has no reset
	 * pin. Register values are retained if power is not removed.
	 * Default values see LIS2DH documentation page 30, chapter 6.
	 */
	(void)memset(raw, 0, sizeof(raw));
	raw[0] = LIS2DH_ACCEL_EN_BITS;

	status = lis2dh->hw_tf->write_data(dev, LIS2DH_REG_CTRL1, raw,
					   sizeof(raw));
```

After the accelerometer is turned on, it is then "resumed" (PM_DEVICE_ACTION_RESUME), which immediately overwrites the contents of CTRL1 with the value of "reg_ctrl1_active_val".

``` C	
case PM_DEVICE_ACTION_RESUME:
		/* read REFERENCE register (see datasheet rev 6 section 8.9 footnote 1) */
		status = lis2dh->hw_tf->read_reg(dev, LIS2DH_REG_REFERENCE, &regdata);
		if (status < 0) {
			LOG_ERR("failed to read reg_reference");
			return status;
		}

		/* Resume previous mode. */
		status = lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_CTRL1,
						  lis2dh->reg_ctrl1_active_val);
		if (status < 0) {
			LOG_ERR("failed to write reg_crtl1");
			return status;
		}
		break;  
```

The problem here, for our application, is that we've never been made aware of the existence of the "reg_ctrl1_active_val" member. If we don't configure it, the PM_DEVICE_ACTION_RESUME routine will write 0x00 to the CTRL1 register and disable the device.

It seems as though a valid workaround would be to assign "reg_ctrl1_active_val" with the current value from CTRL1 after PM_DEVICE_ACTION_TURN_ON, as below.
``` C	
case PM_DEVICE_ACTION_TURN_ON:
		status = lis2dh_init_chip(dev);

                /* After init, store the current active mode. */
		status = lis2dh->hw_tf->read_reg(dev, LIS2DH_REG_CTRL1,
						 &lis2dh->reg_ctrl1_active_val);
                                                 
		if (status < 0) {
			LOG_ERR("failed to read reg_crtl1");
			return status;
		}
		break;
```

But I'm confused how this change worked for @petrosyan-van in the first place.

### Regression

- [x] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Windows 10
- Toolchain: Zephyr SDK 0.17.0
- Commit : 3b035954

### Additional Context

The commit that caused the regression has a SHA: 442b6c15280a1e6ab840977c63544cea626c1592

### PR DESCRIPTION
**Pull request by petrosyan-van**
Cache CTRL1 into reg_ctrl1_active_val right after lis2dh_init_chip() in the PM_DEVICE_ACTION_TURN_ON path.  This prevents the first runtime-PM RESUME from writing 0x00 to CTRL1 and disabling the sensor when runtime-PM is enabled.

This PR is fixing the regression introduced by my PR
https://github.com/zephyrproject-rtos/zephyr/pull/91139 

Fixes: #92196

### CODE REVIEW

File: drivers/sensor/st/lis2dh/lis2dh.c [hunk 1]
```diff
@@ -454,6 +454,16 @@ static int lis2dh_pm_action(const struct device *dev,
 	switch (action) {
 	case PM_DEVICE_ACTION_TURN_ON:
 		status = lis2dh_init_chip(dev);
+		if (status == 0) {
+			/* Cache CTRL1 so the RESUME that follows has a valid value */
+			status = lis2dh->hw_tf->read_reg(dev,
+							 LIS2DH_REG_CTRL1,
+							 &lis2dh->reg_ctrl1_active_val);
```
Comment (bjarki-andreasen) [inline drivers/sensor/st/lis2dh/lis2dh.c]: The value in CTRL1 is initialized to a static value by the preceeding call to `lis2dh_init_chip()`, see line 395 and 442, it is last set to
```
LIS2DH_ACCEL_EN_BITS | LIS2DH_LP_EN_BIT | LIS2DH_ODR_BITS
```
so simply setting `lis2dh->reg_ctrl1_active_val = LIS2DH_ACCEL_EN_BITS | LIS2DH_LP_EN_BIT | LIS2DH_ODR_BITS` would save a reg read.

Even better, just replace the call on line 442 with
```
lis2dh->reg_ctrl1_active_val = LIS2DH_ACCEL_EN_BITS | LIS2DH_LP_EN_BIT | LIS2DH_ODR_BITS;
return lis2dh->hw_tf->read_reg(dev,
		               LIS2DH_REG_CTRL1,
	                       &lis2dh->reg_ctrl1_active_val);
```
and everything is nicely initialized in the init function :)

Comment (petrosyan-van) [reply drivers/sensor/st/lis2dh/lis2dh.c]: Done

**Review by MaureenHelm — COMMENTED** [review]
@avisconti please take a look

File: drivers/sensor/st/lis2dh/lis2dh.c [hunk 2]
```diff
@@ -439,6 +439,7 @@ int lis2dh_init_chip(const struct device *dev)
 		(uint8_t)LIS2DH_LP_EN_BIT, lis2dh->scale);
 
 	/* enable accel measurements and set power mode and data rate */
+	lis2dh->reg_ctrl1_active_val = LIS2DH_ACCEL_EN_BITS | LIS2DH_LP_EN_BIT | LIS2DH_ODR_BITS;
 	return lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_CTRL1,
 					LIS2DH_ACCEL_EN_BITS | LIS2DH_LP_EN_BIT |
 					LIS2DH_ODR_BITS);
```
Comment (bjarki-andreasen) [inline drivers/sensor/st/lis2dh/lis2dh.c]: This could be replaced with
```
return lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_CTRL1, lis2dh->reg_ctrl1_active_val);
```
that way the value is only set once, and its not possible for the values set on lines 442 and 443 to get out of sync :)

Comment (petrosyan-van) [reply drivers/sensor/st/lis2dh/lis2dh.c]: Fixed

**Review by avisconti — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]
Cool :)

**Review by MaureenHelm — APPROVED** [review]
