### PR TITLE
net: tcp: Prevent Silly Window Syndrome

### LINKED ISSUE #45844: Not all bytes are downloaded with HTTP request
**Describe the bug**
Downloading considerable amount of data fails.
Getting fewer bytes than expected, without any error indication from networking stack.

Using http_client, socket_tls and default TCP stack (no socket offloading).

Download amount ca. 1 MB. Chunks are 1 KB.

In general, use case is very close to `big_http_download` sample, but:
- in the setup where resends are needed (medium-quality Wi-Fi and slow target).
- without explicitly setting any networking sizes -` CONFIG_NET_TCP_MAX_RECV_WINDOW_SIZE, CONFIG_NET_TCP_MAX_SEND_WINDOW_SIZE, CONFIG_NET_PKT_TX_COUNT, CONFIG_NET_PKT_RX_COUNT, CONFIG_NET_BUF_TX_COUNT or CONFIG_NET_BUF_RX_COUNT`

**Expected behavior**
All bytes are downloaded

**Environment (please complete the following information):**
 - OS: Any
 - Toolchain NRF with SDK 1.9.99 (based on Zephyr 3.0) or Zephyr main. With Zephyr 2.7 all works as expected.

### PR DESCRIPTION
**Pull request by rlubos**
Implement a mechanism, according to RFC 813, which allows to prevent so
called "Silly Window Syndrome" - a scenario where the TCP receiver keeps
reporting small window sizes in the acknowledgments, effectively
limiting the connection throughput. This allows to improve performance
in low-buffer configurations, where the maximum window size is small,
and the issue was hitting quite often.

~~Additionally, the aforementioned RFC suggests to delay the
acknowledgment in a case, where PSH flag is missing in the packet -
which indicates that peer intends to send more data. Implementing this
case as well, allows to limit the overall acknowledgment count sent by
the receiver (as the stack no longer acknowledges every single packet)
and achieve even better throughputs in performance tests.~~

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

File: subsys/net/ip/tcp.c [hunk 1]
```diff
@@ -2312,12 +2364,21 @@ int net_tcp_listen(struct net_context *context)
...
+	int ret;
+
+	if (!conn) {
 		NET_ERR("context->tcp == NULL");
 		return -EPROTOTYPE;
 	}
 
-	return tcp_update_recv_wnd((struct tcp *)context->tcp, delta);
+	k_mutex_lock(&conn->lock, K_FOREVER);
+
```
Comment (carlescufi) [inline subsys/net/ip/tcp.c:2376]: why those empty lines around the `tcp_update_recv_wnd()`?

Comment (rlubos) [reply subsys/net/ip/tcp.c:2376]: Personally, I think it's easier to analyze then, when you separate the actual logic from thread-safety protection. But it also follows the general convention used in this file: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp.c#L530.
Not sure thou if it's against the general coding guidelines (at least compliance doesn't complain).

File: subsys/net/ip/tcp.c [hunk 2]
```diff
@@ -1795,7 +1836,17 @@ static bool tcp_data_received(struct tcp *conn, struct net_pkt *pkt,
 
 	net_stats_update_tcp_seg_recv(conn->iface);
 	conn_ack(conn, *len);
-	tcp_out(conn, ACK);
+
+	/* Delay ACK response in case of small window or missing PSH,
+	 * as described in RFC 813.
+	 */
+	if (tcp_short_window(conn) || !psh) {
```
Comment (ssharks) [inline subsys/net/ip/tcp.c:1843]: By using the PSH symbol, you start implementing delayed ACKS see: https://en.wikipedia.org/wiki/TCP_delayed_acknowledgment. This is not without its drawbacks. It can negatively affect the functioning of the Nagle algorithm. Secondly it increases the reaction time of the 3 duplicate acks fast retransmit. Since the stack does not impact SACK, and usually is quite memory constraint, I would recommend staying away from these trouble and usually just alsways send and ack

File: subsys/net/ip/tcp.c [hunk 3]
```diff
@@ -2119,7 +2170,8 @@ static void tcp_in(struct tcp *conn, struct net_pkt *pkt)
 
 		if (th) {
 			if (th_seq(th) == conn->ack) {
-				if (!tcp_data_received(conn, pkt, &len)) {
+				if (!tcp_data_received(conn, pkt, &len,
```
Comment (ssharks) [inline subsys/net/ip/tcp.c:2173]: See previous comment on delayed ACKS

File: subsys/net/ip/tcp_private.h [hunk 4]
```diff
@@ -263,6 +264,7 @@ struct tcp { /* TCP connection */
 	enum tcp_data_mode data_mode;
 	uint32_t seq;
 	uint32_t ack;
+	uint16_t recv_win_max;
```
Comment (ssharks) [inline subsys/net/ip/tcp_private.h:267]: Since you added the recv_win_max, is it possible to restructure the code so that the recv_win is not required any more and based on the ack value and buffer filling? This removes another state variable with the potential of going out of sync.

**Review by ssharks — COMMENTED** [review]
Nice work, this is a big improvement to the TCP stack

File: subsys/net/ip/tcp.c (hunk 2 above)
Comment (rlubos) [reply subsys/net/ip/tcp.c:1843]: Ok, thanks for pointing out potential issues with delayed ACKs. I think I'll drop that part from the PR and maybe implement in separately, as a configurable option as you suggest.

File: subsys/net/ip/tcp_private.h (hunk 4 above)
Comment (rlubos) [reply subsys/net/ip/tcp_private.h:267]: Could you elaborate what do you mean by "buffer filling"? I don't really see what you suggest.

**Comment by rlubos** [comment]
Dropped the delayed ACK on missing PSH for now.

File: subsys/net/ip/tcp_private.h (hunk 4 above)
Comment (rlubos) [reply subsys/net/ip/tcp_private.h:267]: We can't use `queue_recv_data` as it's used for a different purpose - the TCP stack queues out-of-order-packets in this queue, it has nothing to do with the window size.

There's a separate fifo where packets are queued before being passed to the application (`recv_data`), but I don't really see how could it be used to track the current window size. Once the packet is passed to the application, it's lost from the TCP stack radar, however the window shouldn't be updated until the packet is consumed by the application (i. e. at the socket/net_context layer). So I'm afraid we still need a variable to track the current window size.

**Review by ssharks — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
