### PR TITLE
fix two ARC issues and improve stack object checking

### LINKED ISSUE #15130: ARC: Z_ARCH_THREAD_STACK_MEMBER defined incorrectly
The definition isn't taking into account minimum MPU region sizes and is creating arrays that are too small for stacks < 2K

### LINKED ISSUE #15131: ARC: off-by-one in MPU V2 _is_in_region()
There's an off-by-one in arc_mpu_v2_internal.h where the last byte of a region is incorrectly reported as being out-of-bounds. This bug was found by calling arc_core_mpu_buffer_validate() on every byte individually in the region, the last one reports failure.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
- Address an off-by-one in ARC MPU v2 driver when testing whether a thread has access to a particular memory range at the end of the MPU region (similar to a bug I recently fixed in the MPU v3 implementation)
- Fix a definition problem with K_THREAD_STACK_MEMBER() on ARC
- Drastically improve testing of stack objects to reduce future bit-rot

Fixes: #15130 
Fixes: #15131

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by vonhust — APPROVED** [review]

File: arch/arc/core/mpu/arc_mpu_v2_internal.h [hunk 1]
```diff
@@ -118,7 +118,7 @@ static inline bool _is_in_region(u32_t r_index, u32_t start, u32_t size)
 	r_size_lshift = (r_size_lshift & 0x3) | ((r_size_lshift >> 7) & 0x1C);
 	r_addr_end = r_addr_start  + (1 << (r_size_lshift + 1));
 
-	if (start >= r_addr_start && (start + size) < r_addr_end) {
+	if (start >= r_addr_start && (start + size) <= r_addr_end) {
```
Comment (ioannisg) [inline arch/arc/core/mpu/arc_mpu_v2_internal.h]: Don't know what the best is, here. I would prefer : `(start + size - 1) < r_addr_end`
It's a style thing.

**Review by ioannisg — CHANGES_REQUESTED** [review]
Looks ok
NACK - just until I test it in ARMv8-M

File: tests/kernel/mem_protect/userspace/prj.conf [hunk 2]
```diff
@@ -1 +1,4 @@
 CONFIG_ZTEST=y
+CONFIG_INIT_STACKS=y
+CONFIG_APPLICATION_DEFINED_SYSCALL=y
+CONFIG_THREAD_USERSPACE_LOCAL_DATA=y
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/prj.conf]: @andrewboie correct me if I am wrong:

```
config ERRNO
	bool "Enable errno support"
	default y
	select THREAD_USERSPACE_LOCAL_DATA if USERSPACE
```

So THREAD_USERSPACE_LOCAL_DATA is selected by default if ERRNO is selected, right? And that one is default=y

File: include/arch/arc/arch.h [hunk 3]
```diff
@@ -105,7 +105,7 @@ extern "C" {
 #define Z_ARCH_THREAD_STACK_MEMBER(sym, size) \
 	struct _k_thread_stack_element \
 		__aligned(POW2_CEIL(STACK_SIZE_ALIGN(size))) \
-		sym[POW2_CEIL(size) + \
+		sym[POW2_CEIL(STACK_SIZE_ALIGN(size)) + \
```
Comment (ioannisg) [inline include/arch/arc/arch.h]: We do not do the same for ARM, as far as I can see.

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 4]
```diff
@@ -895,6 +898,203 @@ static void domain_remove_part_context_switch(void)
...
+	Z_OOPS(Z_SYSCALL_MEMORY_WRITE(size, sizeof(u32_t)));
+
+	z_impl_stack_info_get((u32_t *)start_addr, (u32_t *)size);
+
+	return 0;
+}
+
+int z_impl_check_perms(void *addr, size_t size, int write)
+{
+	return z_arch_buffer_validate(addr, size, write);
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/src/main.c]: Could we simply use the Z_SYSCALL_MEMORY_WRITE macros here, too? Isn't it effectively the same?

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 5]
```diff
@@ -895,6 +898,203 @@ static void domain_remove_part_context_switch(void)
...
+}
+
+Z_SYSCALL_HANDLER(check_perms, addr, size, write)
+{
+	return z_impl_check_perms((void *)addr, size, write);
+}
+
+void *z_impl_get_tls_pointer(void)
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/src/main.c]: Where does the name tls come from?

Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: Isn't this a more generic thing, i.e. getting the pointer to the userspace local data?

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 6]
```diff
@@ -895,6 +898,203 @@ static void domain_remove_part_context_switch(void)
...
+{
+	size_t stack_size;
+	u8_t val;
+	char *stack_start, *stack_ptr, *stack_end, *obj_start, *obj_end;
+	volatile char *pos;
+
+	expect_fault = false;
+
+
+	/* Dump interesting information */
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/src/main.c]: Report interesting information ) :)

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 7]
```diff
@@ -895,6 +898,203 @@ static void domain_remove_part_context_switch(void)
...
+	       stack_size);
+
+	stack_end = stack_start + stack_size;
+	obj_end = (char *)stack_obj + obj_size;
+	obj_start = (char *)stack_obj;
+
+	/* Assert that the created stack object, with the reserved data
+	 * removed, can hold a thread buffer of STEST_STACKSIZE
+	 */
+	zassert_true(STEST_STACKSIZE <= (obj_size - K_THREAD_STACK_RESERVED),
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/src/main.c]: Correct me if I am wrong, but I think this could be strickt equality, except for the case of ARMv7-M MPU. Right @andrewboie ?

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 8]
```diff
@@ -895,6 +898,203 @@ static void domain_remove_part_context_switch(void)
...
+{
+	return (u32_t)z_impl_get_tls_pointer();
+}
+
+void stack_buffer_scenarios(k_thread_stack_t *stack_obj, size_t obj_size)
+{
+	size_t stack_size;
+	u8_t val;
+	char *stack_start, *stack_ptr, *stack_end, *obj_start, *obj_end;
+	volatile char *pos;
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/src/main.c]: Should we be more consistent on types for pos and val? E.g. char val and char *pos, or using u8_t...

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 9]
```diff
@@ -895,6 +898,203 @@ static void domain_remove_part_context_switch(void)
...
+		val = *pos;
+		*pos = val;
+	}
+
+	if (z_arch_is_user_context()) {
+		/* If we're in user mode, check every byte in the stack buffer
+		 * to ensure that the thread has permissions on it.
+		 */
+		for (pos = stack_start; pos < stack_end; pos++) {
+			zassert_false(check_perms((void *)pos, 1, 0),
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/src/main.c]: It seems to me you are only checking read permissions here. EIther we need write permissions' checking too, or we should update the comment before, the the assert text....

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 10]
```diff
@@ -895,6 +898,203 @@ static void domain_remove_part_context_switch(void)
...
+
+
+	/* This API is being removed just whine about it for now */
+	if (K_THREAD_STACK_BUFFER(stack_obj) != stack_start) {
+		printk("WARNING: K_THREAD_STACK_BUFFER() reports %p\n",
+		       K_THREAD_STACK_BUFFER(stack_obj));
+	}
+
+	if (z_arch_is_user_context()) {
+		zassert_true(stack_size <= obj_size - K_THREAD_STACK_RESERVED,
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/src/main.c]: Again, I suppose, we can't use a strict equality due to ARMv7-MPU, right?

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 11]
```diff
@@ -895,6 +898,203 @@ static void domain_remove_part_context_switch(void)
...
+					 (void *)false);
+	} else {
+		stack_buffer_scenarios((k_thread_stack_t *)p1, (size_t)p2);
+	}
+}
+
+void stest_thread_launch(void *stack_obj, size_t obj_size, u32_t flags,
+			 bool drop)
+{
+	k_thread_create(&uthread_thread, stack_obj, STEST_STACKSIZE,
```
Comment (ioannisg) [inline tests/kernel/mem_protect/userspace/src/main.c]: Can we repeat the test using k_thread_create with THREAD_STACK_SIZEOF, to confirm that _that_ is also working?

**Review by ioannisg — CHANGES_REQUESTED** [review]
The test as-is is passing on all ARM-based MPU architectures.
Left some feedback to be addressed.

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 10 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: I know, it might not be of great value, and would make the test case not so easy to read, but would it make sense to transform some of the inequalities to strict equality (whenever possible), in order to get higher coverage level?

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 4 above)
Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/src/main.c]: what is the advantage of doing that

File: arch/arc/core/mpu/arc_mpu_v2_internal.h (hunk 1 above)
Comment (andrewboie) [reply arch/arc/core/mpu/arc_mpu_v2_internal.h]: you've lost me.
they are the same.

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 10 above)
Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/src/main.c]: can we do this some other time?
I have very little bandwidth to further enhance this test until after 1.14 is out

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 11 above)
Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/src/main.c]: can we do this some other time?
I have very little bandwidth to further enhance this test until after 1.14 is out

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 8 above)
Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/src/main.c]: why is this change needed?

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 7 above)
Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/src/main.c]: I need to work with the objects as they are currently defined.
I don't want to further iterate on this until after 1.14 is out.

File: tests/kernel/mem_protect/userspace/prj.conf (hunk 2 above)
Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/prj.conf]: what are you trying to say here? that I should not explicitly put dependencies in prj.conf and rely on defaults elsewhere that might change?

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 5 above)
Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/src/main.c]: it's not.
userspace local data is a poorly named implementation of thread-local storage.

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 9 above)
Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/src/main.c]: fixed

**Comment by andrewboie** [comment]
@ioannisg it's not clear to me what items in your feedback are gating acceptance. I fixed the call to check both read and write permissions, and removed the TLS pointer syscall as I haven't written a test yet to use it. The other feedback seems to be either further enhancements you desire, or fall under the category of "six of one, half dozen of the other"

File: include/arch/arc/arch.h (hunk 3 above)
Comment (andrewboie) [reply include/arch/arc/arch.h]: the min MPU region size on ARM is 32 bytes. on ARC it's 2K.

File: tests/kernel/mem_protect/userspace/prj.conf (hunk 2 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/prj.conf]: Yeap, that's what I am trying to say. Obviously, I am wrong :)

File: arch/arc/core/mpu/arc_mpu_v2_internal.h (hunk 1 above)
Comment (ioannisg) [reply arch/arc/core/mpu/arc_mpu_v2_internal.h]: I know, I said it is a style thing :) We usually have "something" -1 < "sthg else", not <=.
Just style, ignore at will.

File: include/arch/arc/arch.h (hunk 3 above)
Comment (ioannisg) [reply include/arch/arc/arch.h]: Alright. I leave this to ARC-guys, anyways..

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 5 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: Right! So tls is thread-local storage? I confused it to TLS, actually, remembering you did some mbedTLS stuff few days ago. 

Yes, I have a task for 1.15 to rename that, actually.

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 8 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: Just a style thing

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 10 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: Yeap, let's do this in 1.15

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 7 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: Let's improve this in 1.15

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 11 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: Let's improve this in 1.15

**Review by ioannisg — APPROVED** [review]
Good to go for ARM, thanks for the test - really helpful.

File: arch/arc/core/mpu/arc_mpu_v2_internal.h (hunk 1 above)
Comment (ruuddw) [reply arch/arc/core/mpu/arc_mpu_v2_internal.h]: my suggestion would be to directly compare sizes and not calculate end addresses: no need to add the start addresses, less risk for 1-off mistakes.
