### PR TITLE
net: socket: Add locking to prevent concurrent access

### LINKED ISSUE #27032: zephyr network stack socket APIs are not thread safe
**Describe the bug**
The current Zephyr implementation of the BSD Socket APIs is not thread safe. Concurrent use of networking APIs by multiple threads may lead to kernel crashes and/or data corruption.

**To Reproduce**
Found by code inspection and also this comment from the author:

>  You're absolutely right that it's not thread-safe, that's why I don't seriously suggest to revert that commit. On the other hand, I don't remember seeing a bug report of users hitting that issue. So, your heroic effort of fixing it is somewhat misplaced, because the whole socket subsystem is not thread safe. That's because its initial goal was simplicity and small resource usage, it was literally a proof of concept that we can use standards-based API on top of existing adhoc Zephyr API without significant overhead imposed on applications. That worked, and Sockets API was even made the only Zephyr's networking API. Its suggested mode of operation is that a single thread performs all networking activity, while other threads handle sensors, actuators, etc.

**Expected behavior**
The socket implementation for this operating system uses the necessary locking (spinlocks, semaphores) to be safe to use by multiple threads without crashes or data corruption.

The Open Group specifications for the socket APIs specifically cite threat safety as a requirement. For example https://pubs.opengroup.org/onlinepubs/009695399/functions/freeaddrinfo.html

The "significant overhead" used as a justification for lack of thread safety doesn't really exist. spinlocks are very fast, especially on uniprocessor (they just map to irq lock/unlock calls which are a couple CPU instructions). Operating System features must be thread safe, this ticket is a bug and not an enhancement.

**Impact**
Showstopper for users who use the network stack by more than one thread.

### PR DESCRIPTION
**Pull request by jukkar**
The BSD API calls were not thread safe. Add locking to fix this.

Fixes #27032

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — COMMENTED** [review]
Still looking this over, but a few comments:

Would it be possible to move the locking up a layer of abstraction, so that by the time we get to the specific socket type implementations, the lock is already held? This seems preferable to me (if feasible) as its less code duplication.

One thing that worries me is problems introduced by `close()` on net_contexts. Let's say several threads are working with sockets and another thread calls `close()` on the socket descriptor. Are there any windows where this can cause corruption? I'm specifically thinking about the scenario where Thread A is deep within a socket call using the net_context object, and in the middle of that Thread B calls close on it(). On close the net_context would be returned to the pool, and possibly immediately be re-used. Could this cause data corruption?

**Comment by jukkar** [comment]
> Would it be possible to move the locking up a layer of abstraction, so that by the time we get to the specific socket type implementations, the lock is already held? This seems preferable to me (if feasible) as its less code duplication.

Indeed, that is actually much better solution. I moved the mutex to fdtable and then whoever calls `z_get_fd_obj_and_vtable()` (like socket call) can use that for locking purposes.


> I'm specifically thinking about the scenario where Thread A is deep within a socket call using the net_context object, and in the middle of that Thread B calls close on it(). On close the net_context would be returned to the pool, and possibly immediately be re-used. Could this cause data corruption?

There is also locking in net_context, and I am hoping it will catch this case.

File: subsys/net/lib/sockets/sockets.c [hunk 1]
```diff
@@ -1236,13 +1271,21 @@ int z_impl_zsock_poll(struct zsock_pollfd *fds, int nfds, int poll_timeout)
 			 * and non-offloaded sockets, the offloaded poll handler
 			 * shall return an error.
 			 */
-			return z_fdtable_call_ioctl(vtable, ctx,
-						    ZFD_IOCTL_POLL_OFFLOAD,
-						    fds, nfds, poll_timeout);
+			result = z_fdtable_call_ioctl(vtable, ctx,
+						      ZFD_IOCTL_POLL_OFFLOAD,
+						      fds, nfds, poll_timeout);
+			sys_mutex_unlock(lock);
```
Comment (rlubos) [inline subsys/net/lib/sockets/sockets.c:1277]: I think that mutex should be unlocked before the actual call to the offloaded `poll`. Otherwise, the socket would be locked throughout the `poll` call (and it would only be the first socket on the `fds` list locked which makes little sense).

The offloaded `poll` will still have access to the mutexes, it can handle the synchronization if needed.

**Review by rlubos — COMMENTED** [review]
Technically seems fine, but with these changes we render TX/RX operations exclusive on a socket which concerns me a bit. A scenario where one thread reads data from a socket with blocking `recv` and another periodically sends some data will not be possible in this case.

**Comment by jukkar** [comment]
> A scenario where one thread reads data from a socket with blocking `recv` and another periodically sends some data will not be possible in this case.

There are problems if the reading socket blocks waiting data which never comes. If data is received or socket does not block, there should be no issues. We probably should unlock the mutex when reading data to solve that. Passing the mutex to reading function requires some tricks. Not sure if we should try to tackle this obstacle in this PR.

**Comment by rlubos** [comment]
> We probably should unlock the mutex when reading data to solve that. Passing the mutex to reading function requires some tricks. Not sure if we should try to tackle this obstacle in this PR.

I'm wondering, maybe separate mutexes for TX/RX path could help to solve this? Other operations on a socket could lock both.

**Comment by jukkar** [comment]
> I'm wondering, maybe separate mutexes for TX/RX path could help to solve this? Other operations on a socket could lock both.

This looks a bit problematic as we have multiple locking operations involved, sounds like a recipe for deadlock.

I did some experimentation and added a new commit `net: socket: Do not lock long lasting RX or TX` that tries to unlock the locking mutex before long lasting RX or TX operation. Usage is a bit cumbersome at places, especially for read() or write() functions. What do you think?

File: subsys/net/lib/sockets/sockets.c [hunk 2]
```diff
@@ -257,8 +276,14 @@ int z_impl_zsock_close(int sock)
 
 	NET_DBG("close: ctx=%p, fd=%d", ctx, sock);
 
-	return z_fdtable_call_ioctl((const struct fd_op_vtable *)vtable,
-				    ctx, ZFD_IOCTL_CLOSE);
+	(void)sys_mutex_lock(lock, K_FOREVER);
```
Comment (rlubos) [inline subsys/net/lib/sockets/sockets.c:279]: The mutex is a part of `struct fd_entry`, which got released just before. I think we should move `z_free_fd(sock);` after the mutex operation.

File: subsys/net/lib/sockets/sockets.c [hunk 3]
```diff
@@ -870,7 +917,16 @@ static inline ssize_t zsock_recv_dgram(struct net_context *ctx,
...
 		int res;
 
+		if (K_TIMEOUT_EQ(timeout, K_FOREVER)) {
+			sys_mutex_unlock(lock);
+		}
+
 		res = k_fifo_wait_non_empty(&ctx->recv_q, timeout);
+
+		if (K_TIMEOUT_EQ(timeout, K_FOREVER)) {
+			(void)sys_mutex_lock(lock, K_FOREVER);
```
Comment (rlubos) [inline subsys/net/lib/sockets/sockets.c:927]: I think there might be a problem here... The socket might've gotten closed when `recv` was waiting on a FIFO, so technically we'll use a mutex of an unassigned FD object here. Or even worse, if the FD was reassigned, we'll use someone else mutex.

I'm not really sure how to solve that. Theoretically, we should re-verify that we still own the FD, but this might be tricky given we have no knowledge of the FD we use at this point.

File: subsys/net/lib/sockets/sockets.c [hunk 4]
```diff
@@ -30,26 +30,43 @@ LOG_MODULE_REGISTER(net_sock, CONFIG_NET_SOCKETS_LOG_LEVEL);
...
+		void *obj;				     \
+		int ret;				     \
+							     \
+		obj = get_sock_vtable(sock, &vtable, &lock); \
+		if (obj == NULL || vtable->fn == NULL) {     \
+			errno = EBADF;			     \
+			return -1;			     \
+		}					     \
+							     \
+		obj_locking.obj = obj;			     \
```
Comment (rlubos) [inline subsys/net/lib/sockets/sockets.c:47]: Again, a very unlikely scenario, but if we get preempted after `get_sock_vtable` and before `sys_mutex_lock` and the socket gets closed, we again might use the mutex we no longer own. Perhaps the scheduler shall be locked before `get_sock_vtable` call to prevent that?

**Review by rlubos — COMMENTED** [review]
Given the complexity and potential problems that unlocking the mutex in the middle of the operation brings, I'm wondering if it's worth it... Perhaps we should just document that concurrent `send`/`recv` on blocking sockets is not possible and recommend to use `poll` instead.

File: subsys/net/lib/sockets/sockets.c (hunk 2 above)
Comment (jukkar) [reply subsys/net/lib/sockets/sockets.c:279]: Good point, fixed.

File: subsys/net/lib/sockets/sockets.c (hunk 3 above)
Comment (jukkar) [reply subsys/net/lib/sockets/sockets.c:927]: The refcounting PR at #25902 might help here.

File: subsys/net/lib/sockets/sockets.c (hunk 4 above)
Comment (jukkar) [reply subsys/net/lib/sockets/sockets.c:47]: I removed the commit that introduced this.

**Comment by jukkar** [comment]
> Perhaps we should just document that concurrent `send`/`recv` on blocking sockets is not possible and recommend to use `poll` instead.

Yes, I agree. Lets keep this simple for time being.

**Comment by andrewboie** [comment]
was on vacation but I'm back and merged the refcount PR, please rebase.

**Comment by jukkar** [comment]
Fixed merge conflicts.

**Comment by lowlander** [comment]
@jukkar this doesn't apply to master anymore, I would like to try this out to see if some strange random crashes i am having go away.

**Comment by jukkar** [comment]
Fixed merge conflicts.

File: include/sys/fdtable.h [hunk 5]
```diff
@@ -96,10 +97,13 @@ void *z_get_fd_obj(int fd, const struct fd_op_vtable *vtable, int err);
  *
  * @param fd File descriptor previously returned by z_reserve_fd()
  * @param vtable A pointer to a pointer variable to store the vtable
+ * @param lock A pointer to a pointer variable to store a mutex preventing
+ *        concurrent descriptor access.
```
Comment (pabigot) [inline include/sys/fdtable.h:101]: I think it would be helpful to make explicit: 

> (The lock is not taken, it is just returned for the caller to use if necessary).

**Comment by jukkar** [comment]
Updated according to comments, also fixed merge conflicts.

**Comment by jukkar** [comment]
@rlubos can you check that I did not make a mistake while adding locking support to TLS sockets.

File: subsys/net/lib/sockets/sockets_tls.c [hunk 6]
```diff
@@ -1842,8 +1846,12 @@ static inline int ztls_poll_offload(struct pollfd *fds, int nfds, int timeout)
 			fds[i].revents = 0;
 		}
 
+		(void)sys_mutex_lock(lock, K_FOREVER);
```
Comment (rlubos) [inline subsys/net/lib/sockets/sockets_tls.c:1849]: We should not lock the mutex for the offloaded `poll()` call, just as in the native socket implementation.

**Review by rlubos — COMMENTED** [review]
One comment, looks good otherwise.

**Comment by carlescufi** [comment]
> > A scenario where one thread reads data from a socket with blocking `recv` and another periodically sends some data will not be possible in this case.
> 
> There are problems if the reading socket blocks waiting data which never comes. If data is received or socket does not block, there should be no issues. We probably should unlock the mutex when reading data to solve that. Passing the mutex to reading function requires some tricks. Not sure if we should try to tackle this obstacle in this PR.

I do believe that we should address this personally. Having a thread calling `recv()` in a loop and another thread/context calling `send()` asynchronously is one of the most common usecases I can think of.

**Comment by pfalcon** [comment]
> Having a thread calling recv() in a loop and another thread/context calling send() asynchronously is one of the most common usecases I can think of.

A socket (or any other I/O resource) should never be shared between 2 threads. So, that's not "one of the most common usecases", that's "impossible usecase". An app which does that is broken by design. I personally never seen such (sockets I mean, sharing other I/O resources is a known source of bugs indeed). And a moderately broken app which still wants to share I/O resources among threads, would do explicit locking among threads while access the I/O resource (or it would be totally broken app).

**Comment by carlescufi** [comment]
> > Having a thread calling recv() in a loop and another thread/context calling send() asynchronously is one of the most common usecases I can think of.
> 
> A socket (or any other I/O resource) should never be shared between 2 threads. So, that's not "one of the most common usecases", that's "impossible usecase". An app which does that is broken by design. I personally never seen such (sockets I mean, sharing other I/O resources is a known source of bugs indeed). And a moderately broken app which still wants to share I/O resources among threads, would do explicit locking among threads while access the I/O resource (or it would be totally broken app).

I see, I stand corrected. I came to this based on my Python programming experience with serial ports and sockets, where I do use an rx thread (before I switched to asyncio), and I incorrectly assumed that the C APIs are used similarly.

**Comment by pfalcon** [comment]
> I came to this based on my Python programming experience with serial ports and sockets, where I do use an rx thread (before I switched to asyncio), and I incorrectly assumed that the C APIs are used similarly.

I don't think it depends on Python/C API. It based on the idea that most protocols are bidirectional - if you send something, you usually expect something in return (at least an ack). If TX and RX are handled by different threads, then they need to spend extra effort to synchronize between themselves. Why, if a single thread can handle it easier?

The only scenario where 2-thread scenario would make sense is a completely "dumb proxy" design, e.g. read something from a UART, forward (send) to socket, and vice-versa, read from socket, send to UART, not caring what data flows around. I have to admit that I heard discussions of a design where this is handled by 2 separate threads, but I never saw argumentation why to do that instead of the standard select/poll/epoll way, which is exactly the async way. If anything, async way would be still more efficient here, simply because threads are themselves pretty heavy-weight objects (all the register saving and restoring, etc.). Situation would be different if we talk about multicore system, but using 2 cores to handle 1 UART ... still sounds strange, internal bus arbiter would probably add more overhead than doing everything on single core.

Again, I heard, but never saw such designs. Not that I saw all the source code in the world, so if such an implementation is used in a more or less popular project, I'd love learn about it, for educational purposes.

**Comment by carlescufi** [comment]
> I don't think it depends on Python/C API. It based on the idea that most protocols are bidirectional - if you send something, you usually expect something in return (at least an ack). If TX and RX are handled by different threads, then they need to spend extra effort to synchronize between themselves. Why, if a single thread can handle it easier?

Well, I am not sure about how one typically programs this in C, but at least in Python I process whatever comes from `recv()` on a TCP socket until I have a full frame of the higher-level protocol (typically comes with a header) and then queue it for consumption. In parallel this protocol allows sending unsolicited "commands" with `send()` regardless of what one has received. I know of at least a couple of protocols that work this way and use TCP as a transport, without mentioning tons of custom ones.

**Comment by carlescufi** [comment]
> Why, if a single thread can handle it easier?

Because you are going to have multiple threads no matter what if your module exposes an API that calls you back whenever data or a packet has been received, and at the same time allows you to send packets at any time. Remember I am talking about implementing a protocol that is exposed via an API and that runs on top of TCP (or UDP, or serial).

Here's an example from pyserial: https://github.com/pyserial/pyserial/blob/master/serial/threaded/__init__.py#L149

**Comment by carlescufi** [comment]
> > Having a thread calling recv() in a loop and another thread/context calling send() asynchronously is one of the most common usecases I can think of.
> 
> A socket (or any other I/O resource) should never be shared between 2 threads.

You piqued my interest. I searched a bit and found several conversations about this that seem to contradict your statement., Here's a  random thread mentioning the use case:

https://groups.google.com/g/comp.os.linux.networking/c/cLbMGRNw8EA/m/ngeL2KgWAKgJ

>However, as has already been explained, it is possible, and actually common to
have one thread reading from a socket and another writing to the same socket
with no problems.

Do you have a source for your statement about never reading and writing from 2 different threads? It seems it's more common that you might have initially assumed.

**Comment by pfalcon** [comment]
@carlescufi:

> Well, I am not sure about how one typically programs this in C, but at least in Python I process whatever comes from recv() on a TCP socket until I have a full frame of the higher-level protocol (typically comes with a header) and then queue it for consumption. In parallel this protocol allows sending unsolicited "commands" with send() regardless of what one has received. I know of at least a couple of protocols that work this way

Yeah, I'm not surprised that you give that example as that's how BT protocols work. But from my PoV, such protocols in minority. But still, there's no guarantee that send() succeeds. So, for a reasonable implementation, outgoing data would need to be queued that as incoming, and that's only natural to do in single thread.

> Because you are going to have multiple threads no matter what

This logic doesn't scale, that's why it's abandoned (at least at the part of the world outside my window). E.g., even IPv6 allows to have merely 64K simultaneous connections, but even that with a typical stack size of 1MB of big systems would take 64GB (perhaps not fully mapped, and 64-bit systems helped with address space exhaustion, but hopefully "doesn't scale" part is visible). It similar with smaller systems, suppose you have an app with 8 threads, each with modest stack of 1K, and 8K of working memory. If 16K RAM is all you have, logic "we already have 8 threads, let's throw in 9th" doesn't work.

> Here's an example from pyserial: https://github.com/pyserial/pyserial/blob/master/serial/threaded/__init__.py#L149

Thanks, so the code is in the wild. I was looking into pyserial docs for when it recommends to use this threading implementation, and found this: https://pyserial.readthedocs.io/en/latest/pyserial_api.html?highlight=threaded#module-serial.threaded

> This implementation is currently in an experimental state. Use at your own risk.

I guess it summarizes it well, and proves my point: it's *always* possible to use threads where they normally wouldn't be, it's just all the pieces are up to you to hold.

**Comment by pfalcon** [comment]
@carlescufi 

> You piqued my interest. I searched a bit and found several conversations about this that seem to contradict your statement., Here's a random thread mentioning the use case:
https://groups.google.com/g/comp.os.linux.networking/c/cLbMGRNw8EA/m/ngeL2KgWAKgJ

I don't know what you found in that message, I found this:

> In most cases it makes no sense to have multiple threads read or writing to a
socket, unless the socket is UDP and you are processing separate messages.

Which is just the same as I'm saying (without exceptions to IP protocol types).

The guys continues:

> However, as has already been explained, it is possible, and actually common

So, the guy says it's common, and I say it's uncommon and bad practice. Opinions, opinions.

> Do you have a source for your statement about never reading and writing from 2 different threads? It seems it's more common that you might have initially assumed.

"Never" I hopefully didn't say, "makes no sense and bad practice" I stick to. As for how common, I judge by the fact that we never did that in Zephyr so far, and I never saw that in the code I ported to Zephyr or considered as making sense to port. As for "more common", everything is possible. I may imagine that relatively a lot of people talk to sockets in their GUI update threads, and that's why interwebs are full of hits regarding that. But nope, that doesn't make it a good thing or worth being supported in Zephyr.

Now about references. Let start from the opposite side from what we had so far (codes with "use at your own risk" comments). Let's first get terminology straight. A socket is a stateful object (has internal state), and that state is mutable, i.e. changeable. This is commonly known as "mutable state". Then, references:

1. https://en.wikipedia.org/wiki/Actor_model "Actors may modify their own private state, but can only affect each other indirectly through messaging (removing the need for lock-based synchronization)." I.e. Actor Model prohibits and shared state at all, even shared memory. It's a model of Erlang and many other systems nowadays. You compare how modest and conservative I am, advocating that only I/O objects shouldn't be shared.
2. http://henrikeichenhardt.blogspot.com/2013/06/why-shared-mutable-state-is-root-of-all.html "Why shared mutable state is the root of all evil."
3. https://exploringjs.com/deep-js/ch_shared-mutable-state.html "The problems of shared mutable state and how to avoid them"

To get closer to our target domain, let's look at Rust. It's interesting because it brings in a (patched) concept of Linear Types. Roughly, by default, a value can be used only by one routine (not a process, not a thread, but *routine*). If you passed an object to another function, you lose access to it (because who knows what that function did to it). You can get around that by explicitly annotating operations the function and caller do, and compiler will check that it's not modified in more than one place concurrently.

So, I'm sorry that I can't provide searches for query "sharing socket between threads" which say "don't do that, it's bad", because the search results are swamped by questions of people who actually trying to do that, and that's how software is written in C, etc. Limiting to e.g. Rust, it's much easier: https://stackoverflow.com/questions/28300742/how-do-i-share-a-socket-between-a-thread-and-a-function .

First comment is: "Why do you need to share the socket between the threads?" And the answer is "The cleanest way is to use channels to pass the data between threads".

**Comment by pfalcon** [comment]
> EDIT: Seems that POSIX declares send() and recv() as thread safe: https://pubs.opengroup.org/onlinepubs/009695399/functions/xsh_chap02_09.html#tag_02_09_01

Yeah, but POSIX declares another thousand of functions which should be there, and things like POSIX shell, etc., which we'll never have.


This thread is again about why locking was not implemented in the original socket shim. It was conscious, explicit, and communicated, if not discussed decision, based on the fact that normally sharing shouldn't happen, and when it does, there would be explicit locking on application's side. And against catastrophically incorrect behavior, there should have been locking on the level of native Zephyr objects (net_context, net_if, etc.).

Since then, nothing has changed from my PoV. In particular, I never saw a case presented that current behavior gives a vulnerability and thus needs to be fixed. And this change is kinda advertised as security-related, but look e.g. at the limitations of Zephyr memory protection: at https://docs.zephyrproject.org/latest/reference/usermode/overview.html#design-goals , there's

> We are specifically not protecting against the following attacks:
> * The kernel itself, and any threads that are executing in supervisor mode, are assumed to be trusted.
> * The toolchain and any supplemental programs used by the build system are assumed to be trusted.
> (long list continues)

So, just as Zephyr memory protection doesn't protect against cosmic rays or compiler bugs, similarly socket subsystem doesn't support implicit sharing of sockets between threads. If they are shared, there must be explicit synchronization implemented on the application (library) side. Perhaps that fact is not documented well enough (at all?), but that's different matter.

**Comment by andrewboie** [comment]
> So, just as Zephyr memory protection doesn't protect against cosmic rays or compiler bugs, similarly socket subsystem doesn't support implicit sharing of sockets between threads. If they are shared, there must be explicit synchronization implemented on the application (library) side. Perhaps that fact is not documented well enough (at all?), but that's different matter.

You're not correctly interpreting the threat model.

We provide these socket APIs to user mode as system calls. We can't have concurrent user mode threads potentially cause data corruption in the kernel (or exploits derived from such corruption) by omitting locking. Activity done by user threads, or in syscall implementations on behalf of user threads, is in scope of the threat model.

Arguments on whether sharing sockets is bad programming practice are totally irrelevant to the question "is it a requirement that system calls be thread safe?" It is. They must be thread safe. Full stop.

What form and granularity that locking takes is not defined by the threat model. From that perspective I don't care if you serialize the whole damn network stack on a single global mutex, although that certainly wouldn't be a great way to do it. But the idea that thread safety is somehow optional for system calls is absurd.

**Comment by pfalcon** [comment]
> But the idea that thread safety is somehow optional for system calls is absurd.

Perhaps. But "system calls" is the keyword here. The original code was written without syscalls in mind, and they likely were added later at all. It was written for "RTOS which can run in 8K", which Zephyr was advertized as at that time. And the concern expressed is that this syscalls business adds growing overhead which isn't needed in 80-90% of cases (opinion). Which would call to make those overheads optional, but they aren't.

Maybe it should be called "natural evolution", and maybe Zephyr is destined to be used in 80-90% cases with syscalls and all their overheads, and "RTOS in 8K" picture should be faded and forgotten. All in all, this is a "feedback and discussion" on the changes, especially given concerns that the original implenentation may have been "underdiscussed" (but it was discussed pretty much, and the biggest concern at that time was whether Socket API should be used wide enough comparing to "native API" (callbacks and stuff), and how to address concerns that sockets just add overhead comparing to it).

**Comment by cfriedt** [comment]
Is it possible to create a test case that reproduces a couple of different manifestations of the bug so that we can provide evidence that something was first broken and then fixed after the change?

I'm not trying to imply at all that the bug doesn't exist, but I think that this is tremendously important issue and it should have some regularly reproduced test coverage.

In particular, I feel like concurrent blocking I/O on sockets is something that *iwouldtotallydo* and therefore I might inadvertently write broken code :-)

Would be happy to inspect the code live once there is a test case.

**Comment by andrewboie** [comment]
> Perhaps. But "system calls" is the keyword here

No it's not. The spec for these socket APIs also says they are thread safe and this issue is of interest to anyone who uses this network stack, regardless of whether they have memory protection turned on or opinions on programming practices.

**Comment by andrewboie** [comment]
> Zephyr is destined to be used in 80-90% cases with syscalls and all their overheads, and "RTOS in 8K" picture should be faded and forgotten

Please provide evidence for this claim that the minimum footprint has blown up when CONFIG_USERSPACE=n. This is bug if that's the case. All the system call verification functions, infrastructure, and hooks compile to nothing if CONFIG_USERSPACE=n; this entire subsystem was specifically designed not to affect the footprint of devices that don't use it. Be very specific.

Basic thread safety for APIs that are documented as being such is NOT part of userspace before you cite that.

**Comment by jukkar** [comment]
The discussion is interesting but we are side tracking here. I agree with @andrewboie that we cannot dictate how the applications will use the socket API. It could be that application developer does stupid things but we (as network stack & kernel) must handle all this stuff.
So all this in mind, please review this PR so that we can get it in sooner than later. The nearer we get to the 2.4 release, the less time we have to try and test this.

**Comment by carlescufi** [comment]
> Zephyr is destined to be used in 80-90% cases with syscalls and all their overheads, and "RTOS in 8K" picture should be faded and forgotten

If that were true then our Zephyr-based SDK would be nearly useless to many of our customers, and I like to think it's not. I would love to have statistics about builds with and without userspace of Zephyr products in the wild, but I am willing to bet that most of them do not use userspace.

**Comment by jukkar** [comment]
As agreed on API meeting:

* postponing this to 2.5 at which point we should have condition variables support which would help to implement the locking properly
* create a new PR which documents the socket api thread unsafeness for the 2.4 release

**Comment by pfalcon** [comment]
@jukkar: What's the status of this? As you can see, it was even bot-marked as stale. It's otherwise hard to argue with the message of "what needs to be done, needs to be done". In that regard, it would be good idea to not wait for the next release rush, but merge this ~ now, to let people test thru it well.

**Comment by jukkar** [comment]
This is waiting  #27732

**Comment by pfalcon** [comment]
@jukkar :

> This is waiting #27732

Ok, that now was merged, so need to make a decision whether to try to merge this (still not formally approved) change in the last day of the pre-freeze window.

(Oh, and if it waited to be refactored with facilitiesm fro #27732, then apparently not.)

**Comment by jukkar** [comment]
Updated to use condition variables so that blocking socket read releases the lock and avoids blocking the write calls.

**Review by pabigot — CHANGES_REQUESTED** [review]
This looks good, but I'd like to see the one-lock/multi-release code refactored if possible.  And another documentation clarification.

**Comment by jukkar** [comment]
Updated according to comments.

**Review by pabigot — APPROVED** [review]

**Comment by jukkar** [comment]
Fixes to get the sanity check to pass.

**Review by rlubos — APPROVED** [review]
Thanks, looks good. Tested with several samples, no issues spotted.

File: include/net/net_context.h [hunk 7]
```diff
@@ -276,6 +276,13 @@ __net_socket struct net_context {
 		struct k_fifo accept_q;
 	};
 
+	struct {
+		/** Condition variable for used when receiving data */
```
[the remark this answers is not in the document]
Comment (jukkar) [reply include/net/net_context.h:280]: Typo, I will fix.

**Comment by jukkar** [comment]
I am seeing some weird sanity failures with four qemu based platforms: **mps2_an385**, **qemu_leon3**, **qemu_riscv32** and **qemu_riscv64**. The backtraces do not make much sense, they indicate some invalid memory access error in kernel scheduler. That is hard to believe so I am suspecting some stack issue as that might cause weird crashes, but increasing the stack sizes did not help.

**Comment by jukkar** [comment]
I investigated the crash issues seen in the unit test and there is a crash when `k_condvar_wait()` is called in `subsys/net/lib/sockets/sockets.c:wait_data()` when running the `tests/net/socket/tcp` tests.

I increased the size of various stacks like this (placed these settings to `overlay-stacks.conf` file)
```
CONFIG_INIT_STACKS=y
CONFIG_STACK_USAGE=y
CONFIG_NET_TX_STACK_SIZE=8192
CONFIG_NET_RX_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
CONFIG_NET_MGMT_EVENT_STACK_SIZE=8192
CONFIG_ZTEST_STACKSIZE=8192
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_ISR_STACK_SIZE=8192
CONFIG_PRIVILEGED_STACK_SIZE=8192
CONFIG_CMSIS_THREAD_MAX_STACK_SIZE=8192
CONFIG_CMSIS_V2_THREAD_MAX_STACK_SIZE=8192
CONFIG_CMSIS_V2_THREAD_DYNAMIC_STACK_SIZE=8192
CONFIG_IDLE_STACK_SIZE=8192
CONFIG_TEST_EXTRA_STACKSIZE=2048
```
but that did not help.

I compiled the test app like this:
```
# cd tests/net/socket/tcp
# cmake -B build -DBOARD=<qemu_riscv32|qemu_riscv64|mps2_an385> -DOVERLAY_CONFIG=overlay-stacks.conf .
# make -C build -j 9 run
```
For each failed arch **qemu_riscv32**, **qemu_riscv64** and **mps2_an385** (I did not try **qemu_leon3** at this point), the crash happens at the same place
```
kernel/sched.c:

add_to_waitq_locked() -> z_priq_dumb_add() -> sys_dlist_append()

static inline void sys_dlist_append(sys_dlist_t *list, sys_dnode_t *node)
{
	node->next = list;
	node->prev = list->tail;

	list->tail->next = node;             <--- crashing here
	list->tail = node;
}
```

Exact crashes:

**mps2_an385**
----------
Here the userspace was set in the test so `CONFIG_USERSPACE=y`
```
[QEMU] CPU: cortex-m3
qemu-system-arm: warning: nic lan9118.0 has no peer
*** Booting Zephyr OS build v2.5.0-rc1-20-ga85a4918f2a8  ***
Running test suite socket_tcp
===================================================================
START - test_v4_send_recv
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x0
E: r0/a1:  0x00000000  r1/a2:  0x20000b30  r2/a3:  0x00000001
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x0000ef9f
E:  xpsr:  0x61000200
E: Faulting instruction address (r15/pc): 0x0000fa6a
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20000b30 (ztest_thread)
E: Halting system

Disassembly:

	node->prev = list->tail;
    fa66:	6063      	str	r3, [r4, #4]
	list->tail->next = node;
    fa68:	686b      	ldr	r3, [r5, #4]
    fa6a:	601c      	str	r4, [r3, #0]
	list->tail = node;
    fa6c:	606c      	str	r4, [r5, #4]
    fa6e:	e7f7      	b.n	fa60 <add_to_waitq_locked+0x64>
```

**qemu_riscv32**
------------
Here userspace was not enabled, `CONFIG_USERSPACE=n`
```
[QEMU] CPU: riscv32
*** Booting Zephyr OS build v2.5.0-rc1-20-ga85a4918f2a8  ***
Running test suite socket_tcp
===================================================================
START - test_v4_send_recv
E: 
E:  mcause: 7, unknown
E:      a0: 8001a290    t0: 00000000
E:      a1: 8001a490    t1: 800047be
E:      a2: ffffffff    t2: fffffff5
E:      a3: ffffffff    t3: 00000000
E:      a4: 00000000    t4: 010200c0
E:      a5: 00000000    t5: 010200c0
E:      a6: 40000000    t6: cdf60640
E:      a7: 80000000
E:                      tp: aaaaaaaa
E:      ra: 800140dc    gp: aaaaaaaa
E:    mepc: 80014160
E: mstatus: 00001800
E: 
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x8001a490 (ztest_thread)
E: Halting system

Disassembly:

	node->prev = list->tail;
8001415c:	c05c                	sw	a5,4(s0)
	list->tail->next = node;
8001415e:	40dc                	lw	a5,4(s1)
80014160:	c380                	sw	s0,0(a5)
	list->tail = node;
80014162:	c0c0                	sw	s0,4(s1)
80014164:	b7e5                	j	8001414c <add_to_waitq_locked+0x82>
```

**qemu_riscv64**
------------
Here userspace was not enabled, `CONFIG_USERSPACE=n`
```
[QEMU] CPU: riscv64
*** Booting Zephyr OS build v2.5.0-rc1-20-ga85a4918f2a8  ***
Running test suite socket_tcp
===================================================================
START - test_v4_send_recv
E: 
E:  mcause: 7, unknown
E:      a0: 000000008001aee8    t0: 0000000000000000
E:      a1: 000000008001b5d0    t1: 0000000080003f82
E:      a2: ffffffffffffffff    t2: fffffffffffffff5
E:      a3: 0000000000000000    t3: 0000000000000001
E:      a4: 0000000000000000    t4: 000000008002ff48
E:      a5: 0000000000000000    t5: 0000000000000007
E:      a6: ffffffffffffffff    t6: 0ccccccccccccccc
E:      a7: 0000000000000008
E:                              tp: aaaaaaaaaaaaaaaa
E:      ra: 0000000080013bc8    gp: aaaaaaaaaaaaaaaa
E:    mepc: 0000000080013c4e
E: mstatus: 0000000000001800
E: 
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x8001b5d0 (ztest_thread)
E: Halting system

Disassembly:

	node->prev = list->tail;
    80013c4a:	e41c                	sd	a5,8(s0)
	list->tail->next = node;
    80013c4c:	649c                	ld	a5,8(s1)
    80013c4e:	e380                	sd	s0,0(a5)
	list->tail = node;
    80013c50:	e480                	sd	s0,8(s1)
    80013c52:	b7ed                	j	80013c3c <add_to_waitq_locked+0x84>
```

@andyross any idea what might be wrong here?

**Comment by pabigot** [comment]
@jukkar Could you push this up for another test?  I'm a bit concerned about the implication that `k_condvar` doesn't work, and would like to see test results on the current RC.

**Comment by jukkar** [comment]
Rebased to latest master.

**Comment by jukkar** [comment]
Rebased to latest master.

**Comment by jukkar** [comment]
Rebased to latest master.

**Comment by jukkar** [comment]
Investigated why two tests fail still for  mps2_an385 and the MPU fault happens when
`z_impl_k_condvar_wait()` calls `z_pend_curr(&lock, key, &condvar->wait_q, timeout);`
```
*** Booting Zephyr OS build zephyr-v2.5.0-1142-g9f051c4bd4f7  ***
Running test suite socket_tcp
===================================================================
START - test_v4_send_recv
E: ***** MPU FAULT *****
E:   Data Access Violation
E:   MMFAR Address: 0x0
E: r0/a1:  0x200008e0  r1/a2:  0x20000bf0  r2/a3:  0x00000001
E: r3/a4:  0x00000000 r12/ip:  0x000042ed r14/lr:  0x0000fc1d
E:  xpsr:  0x21000200
E: Faulting instruction address (r15/pc): 0x0000fcd8
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20000bf0 (ztest_thread)
E: Halting system
```
The call flow looks like this (done manually as I was not able to get gdb to co-operate with me):
```
tests/net/socket/tcp/src/main.c:
-> test_v4_send_recv()
-> test_recv()
-> recv()
subsys/net/lib/sockets/sockets.c:
-> zsock_recv_stream()
-> wait_data()
kernel/condvar.c:
-> k_condvar_wait()
-> z_impl_k_condvar_wait()
-> z_pend_curr()
-> pend()      <- crashing here
```

There was similar crashes for RISC-V qemu targets but those have disappeared in latest twister run. @andyross / @nashif any idea how to solve this issue?

**Comment by jukkar** [comment]
Fixing merge conflict

**Comment by galak** [comment]
@jukkar I debugged this and it looks like the cond var isn't getting initialized in all cases.  The accept socket net_context doesn't appear to have `ctx->cond.recv` initialized and thus the failure.

I'm not familiar with the net code but I added this:

```
diff --git a/subsys/net/lib/sockets/sockets.c b/subsys/net/lib/sockets/sockets.c
index ffc9d1c31b..114f804437 100644
--- a/subsys/net/lib/sockets/sockets.c
+++ b/subsys/net/lib/sockets/sockets.c
@@ -332,6 +332,8 @@ static void zsock_accepted_cb(struct net_context *new_ctx,
                                       NULL);
                k_fifo_init(&new_ctx->recv_q);
 
+               k_condvar_init(&new_ctx->cond.recv);
+
                k_fifo_put(&parent->accept_q, new_ctx);
        }
 }
```

**Comment by jukkar** [comment]
> I debugged this and it looks like the cond var isn't getting initialized in all cases

:facepalm: indeed, that is the case. It was just too close to me to see, thanks for the help :+1:

**Comment by jukkar** [comment]
@galak / @nashif could you force merge this, there is false positive check in checkpatch that is failing
