### PR TITLE
drivers: dai: sai: don't crash on underrun/overrun

### LINKED ISSUE #77633: drivers: dai: nxp: sai: RTOS crashes on TX/RX underrun/overrun
**Describe the bug**

RTOS will crash if there's a FIFO underrun/overrun because of a `z_irq_spurious()` call in the error ISR. Issue was observed while adding support for a new platform in SOF.

**Expected behavior**

RTOS shouldn't crash. Instead, the error flag should be cleared and the transmit/receive operations should continue.

Fixed by: https://github.com/zephyrproject-rtos/zephyr/pull/77236

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
TX/RX FIFO underrun shouldn't crash the RTOS when it occurs. Also, since this can also happen under "normal" conditions (i.e: DMA doesn't copy data fast enough from/to SAI's FIFOs) the software should be able to recover from it.

As such:
	1) Remove `z_irq_spurious()` call.
	2) Clear error flag
	3) De-escalate error message to warning message

Fixes #77633

### CODE REVIEW

File: drivers/dai/nxp/sai/sai.h [hunk 1]
```diff
@@ -210,6 +210,12 @@ LOG_MODULE_REGISTER(nxp_dai_sai);
 	((dir) == DAI_DIR_RX ? ((UINT_TO_I2S(regmap))->RCSR & (which)) : \
 	 ((UINT_TO_I2S(regmap))->TCSR & (which)))
 
+/* used to clear status flags */
+#define SAI_TX_RX_STATUS_CLEAR(dir, regmap, which)\
+	((dir) == DAI_DIR_RX ?\
+	 SAI_RxClearStatusFlags(UINT_TO_I2S(regmap), which) :\
+	 SAI_TxClearStatusFlags(UINT_TO_I2S(regmap), which))
+
 /* used to retrieve the SYNC direction. Use this macro when you know for sure
```
Comment (dbaluta) [inline drivers/dai/nxp/sai/sai.h:219]: @LaurentiuM1234  change looks good to me. Will approve once this warning is fixed.

**Review by dbaluta — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by LaurentiuM1234** [comment]
created bug report (https://github.com/zephyrproject-rtos/zephyr/issues/77633) for backporting

**Review by iuliana-prodan — APPROVED** [review]
