### PR TITLE
Bluetooth: Shell: Fix bt adv-data command

### LINKED ISSUE #62235: Bluetooth: Shell : bt adv_data crash issue
**Describe the bug**

bt adv_data crash issue

**To Reproduce**
1. build
```
west build -b native_posix ~/zephyrproject/zephyr/tests/bluetooth/shell/ --pristine -- -DOVERLAY_CONFIG=audio.conf
``` 
2. run
```
./build/zephyr/zephyr.exe -bt-dev=hci0
```
3. set adv data
```
bt init
bt adv-create conn-nscan ext-adv name
bt adv-data discov
```
4. Crash
```
#0  0xf7ded3d3 in ?? () from /lib32/libc.so.6
#1  0x565ef8eb in ad_stream_read (stream=0xf62fce64, buf=0x56755ce8 <net_buf_data_hci_cmd_pool+8> "", buf_len=64 '@')
    at /home/fanhang/zephyrproject/zephyr/subsys/bluetooth/host/adv.c:160
#2  0x565f05dd in hci_set_adv_ext_fragmented (adv=0x56762020 <adv_pool>, hci_op=8247, ad=0xf62fcf3c, ad_len=2) at /home/fanhang/zephyrproject/zephyr/subsys/bluetooth/host/adv.c:622
#3  0x565f076e in hci_set_ad_ext (adv=0x56762020 <adv_pool>, hci_op=8247, ad=0xf62fcf3c, ad_len=2) at /home/fanhang/zephyrproject/zephyr/subsys/bluetooth/host/adv.c:670
#4  0x565f07a1 in set_ad (adv=0x56762020 <adv_pool>, ad=0xf62fcf3c, ad_len=2) at /home/fanhang/zephyrproject/zephyr/subsys/bluetooth/host/adv.c:681
#5  0x565f0ba3 in le_adv_update (adv=0x56762020 <adv_pool>, ad=0xf62fcffc, ad_len=6, sd=0x0, sd_len=0, ext_adv=true, scannable=false, name_type=ADV_NAME_TYPE_AD)
    at /home/fanhang/zephyrproject/zephyr/subsys/bluetooth/host/adv.c:820
#6  0x565f25ec in bt_le_ext_adv_set_data (adv=0x56762020 <adv_pool>, ad=0xf62fcffc, ad_len=6, sd=0x0, sd_len=0)
    at /home/fanhang/zephyrproject/zephyr/subsys/bluetooth/host/adv.c:1712
#7  0x5663816a in cmd_adv_data (sh=0x5675e12c <shell_uart>, argc=2, argv=0xf62fd14c) at /home/fanhang/zephyrproject/zephyr/subsys/bluetooth/shell/bt.c:1983
#8  0x565d0b9e in exec_cmd (sh=0x5675e12c <shell_uart>, argc=2, argv=0xf62fd14c, help_entry=0xf62fd134) at /home/fanhang/zephyrproject/zephyr/subsys/shell/shell.c:558
#9  0x565d1299 in execute (sh=0x5675e12c <shell_uart>) at /home/fanhang/zephyrproject/zephyr/subsys/shell/shell.c:800
#10 0x565d1884 in state_collect (sh=0x5675e12c <shell_uart>) at /home/fanhang/zephyrproject/zephyr/subsys/shell/shell.c:1008
#11 0x565d2754 in shell_process (sh=0x5675e12c <shell_uart>) at /home/fanhang/zephyrproject/zephyr/subsys/shell/shell.c:1479
#12 0x565d2159 in shell_signal_handle (sh=0x5675e12c <shell_uart>, sig_idx=SHELL_SIGNAL_RXRDY, handler=0x565d2674 <shell_process>)
    at /home/fanhang/zephyrproject/zephyr/subsys/shell/shell.c:1296
#13 0x565d2321 in shell_thread (shell_handle=0x5675e12c <shell_uart>, arg_log_backend=0x1, arg_log_level=0x4) at /home/fanhang/zephyrproject/zephyr/subsys/shell/shell.c:1355
#14 0x565b6320 in z_thread_entry (entry=0x565d21d3 <shell_thread>, p1=0x5675e12c <shell_uart>, p2=0x1, p3=0x4) at /home/fanhang/zephyrproject/zephyr/lib/os/thread_entry.c:48
#15 0x565dc20c in posix_arch_thread_entry (pa_thread_status=0x56752608 <shell_uart_stack+2024>) at /home/fanhang/zephyrproject/zephyr/arch/posix/core/thread.c:57
#16 0x565dc5de in posix_thread_starter (arg=0x2) at /home/fanhang/zephyrproject/zephyr/arch/posix/core/posix_core.c:293
#17 0xf7e9460a in start_thread (arg=<optimized out>) at pthread_create.c:477
#18 0xf7da3d2a in clone () from /lib32/libc.so.6
```

```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by Fanhang32**
Fix wrong adv elements length for bt adv-data command

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/62235

### CODE REVIEW

**Comment by Fanhang32** [comment]
side effect of https://github.com/zephyrproject-rtos/zephyr/pull/61418#discussion_r1294333908

**Review by theob-pro — DISMISSED** [review]

**Review by rugeGerritsen — APPROVED** [review]

File: subsys/bluetooth/shell/bt.c [hunk 1]
```diff
@@ -1945,7 +1944,7 @@ static int cmd_adv_data(const struct shell *sh, size_t argc, char *argv[])
 			}
 
 			data = sd;
-			data_len = &sd_len;
+			data_len = sd_len;
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/shell/bt.c:1947]: Hmm, looking over the code again, it looks like `data` and `data_len` is intended to let the user control if the data set is set for the scan response or advertising data. 

Line 1972 assumes that `data_len` is for `ad` only. 

So while this PR (so far) fixes an issue with `data` being uninitialized, it modifies the behavior of the command, so that it is actually impossible to set scan response data, as `sd_len` will always be `0` after this change. 

I suggest to initialize `data` to NULL instead (with checks before it is being dereferenced), and modify line 1972 to use `data` instead of `ad`, or something other to ensure that `data_len` isn't assumed to be the length of just the `ad`

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/shell/bt.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (Fanhang32) [reply subsys/bluetooth/shell/bt.c]: This is indeed a problem of scan response.
I‘ve fixed it to use`data` instead of `ad` in `ad_int`  and assigne the correct value of 'sd_len' .

File: subsys/bluetooth/shell/bt.c [hunk 2]
```diff
@@ -1970,15 +1969,18 @@ static int cmd_adv_data(const struct shell *sh, size_t argc, char *argv[])
 	atomic_set_bit_to(adv_set_opt[selected_adv], SHELL_ADV_OPT_APPEARANCE,
 			  appearance);
 
-	ad_len = ad_init(&ad[*data_len], ARRAY_SIZE(ad) - *data_len,
-			 adv_set_opt[selected_adv]);
-	if (ad_len < 0) {
+	len = ad_init(&data[*data_len], ARRAY_SIZE(ad) - *data_len, adv_set_opt[selected_adv]);
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:1972]: If we allow this to be called with either `ad` or `sd`, then we cannot use `ARRAY_SIZE(ad)`.

File: subsys/bluetooth/shell/bt.c [hunk 3]
```diff
@@ -1970,15 +1969,18 @@ static int cmd_adv_data(const struct shell *sh, size_t argc, char *argv[])
...
 
 		return -ENOEXEC;
 	}
 
-	ad_len += *data_len;
+	if (data == ad) {
+		ad_len += len;
+	} else {
+		sd_len += len;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:1983]: How does this work in practice actually? 

Can we set `ad` and `sd` in a single command? And if so, then I guess it's the latter that will have the data from `ad_init`?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/shell/bt.c (hunk 2 above)
Comment (Fanhang32) [reply subsys/bluetooth/shell/bt.c:1972]: > If we allow this to be called with either `ad` or `sd`, then we cannot use `ARRAY_SIZE(ad)`.

Both `ARRAY_SIZE(ad)` or `ARRAY_SIZE(sd) ` are all same fixed value during initialization in `bt_data ad[9]` and `bt_data sd[9]`. They are just used to limit the maximum of adv elements.  

So i think it’s fun to use `ARRAY_SIZE(ad)` . Or do you think we need another parameter to replace it?

File: subsys/bluetooth/shell/bt.c (hunk 3 above)
Comment (Fanhang32) [reply subsys/bluetooth/shell/bt.c:1983]: > How does this work in practice actually?
> 
> Can we set `ad` and `sd` in a single command? And if so, then I guess it's the latter that will have the data from `ad_init`?

We can only set `ad` and `sd` separately .  `sd` can get data from `ad_init`.

Comment (Thalley) [reply subsys/bluetooth/shell/bt.c:1983]: > We can only set ad and sd separately . sd can get data from ad_init.

Okay, so when `bt_le_ext_adv_set_data` is called, we either set `sd` or `ad`, but never both? So the user cannot do a mix of `ad` and `sd`?

File: subsys/bluetooth/shell/bt.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/shell/bt.c:1972]: > Both ARRAY_SIZE(ad) or ARRAY_SIZE(sd) are all same fixed value during initialization in bt_data ad[9]

Isn't that more of a coincidence than a rule? 

We could add a `#define` to set the size, and use that to initalize `ad` and `sd` and use that here as well, to ensure that they are always the same size.

File: subsys/bluetooth/shell/bt.c (hunk 3 above)
Comment (Fanhang32) [reply subsys/bluetooth/shell/bt.c:1985]: Seems only legecy and scannable and adv can set both `sd` and `ad` when `bt_le_ext_adv_set_data` called.
But we couldn't do that in `cmd_adv_data`.   It‘s not introduced by this PR.

This PR mainly want to fix https://github.com/zephyrproject-rtos/zephyr/issues/62235

File: subsys/bluetooth/shell/bt.c (hunk 2 above)
Comment (Fanhang32) [reply subsys/bluetooth/shell/bt.c]: done

**Review by Thalley — APPROVED** [review]

**Review by theob-pro — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
