### PR TITLE
drivers: adc_shell: rework commands

### LINKED ISSUE #27350: ADC: adc shell failure when mismatch with dts device label
**Describe the bug**
using `adc` command forces `adc ADC_0` when ADC_1 is the first enabled ADC, causing any command to fail with `device is not in device list` error

**To Reproduce**
Try on any STM32 EVB

**Expected behavior**
The root cause for this bug is the ambiguous use of the sub command name, here "ADC_0", and the device label configured in the dts.
if "ADC_0" means "the first enabled ADC instance" in line 45: .device_name = DT_INST_LABEL(inst), sets the device_name field in the hdl struct as "ADC_1", the device label string defined in the dts.
But, in line 111 in function get_adc_from_list(char *name): if (!strcmp(name, adc_list[adc_idx].device_name)) { it is compared to the argv parameter given, which is "ADC_0". thus always failing the search.

Note: using "ADC_1" as shell parameter fails the shell core as this is not a valid subcommand.

This can happen in the following cases, which causes the enabled device under instance index x to no be labelled "ADC_x":
1. The arch dts device label defines are not 0-based (like in STM32 which start at ADC_1)
2. The first enabled device is not ADC_0, but ADC_1, or 2
3. The arch dts doesn't even use the ADC_x naming for its labels. it can be "A2D_0" (for digital-to-analog) or something like that.

Solution:
I suggest avoiding the double use of ADC_x for both the subcommand syntax and the device label. using index only for the subcommand. using adc 0 read 15 for example.

If this "ADC_x" naming convention is necessary, using "ADC_0" for "first enabled instance" is wrong, and it should be "ADC_1" for the device label as defined in the dts. can be achieved by dynamically creating the subcommand syntax.

For now, this code is malfunctioning in every ST core we used.

### PR DESCRIPTION
**Pull request by jakub-uC**
ADC shell commands can be only executed on the property label exiting in the device tree. It is realized by the dynamic subcommand returning the existing ADC Label.

Fixes #27350

Signed-off-by: Jakub Rzeszutko <jakub.rzeszutko@nordisemi.no>

### CODE REVIEW

**Comment by jakub-uC** [comment]
@avigreen1978 may you please test it?

**Comment by erwango** [comment]
^^ @avigreen1978

File: drivers/adc/adc_shell.c [hunk 1]
```diff
@@ -32,17 +32,41 @@
...
+	"Configure resolution\n"
+
+#define CMD_HELP_GAIN				\
+	"Configure gain."
+
+#define NODE_LABELS(n) DT_INST_LABEL(n),
 #define ADC_HDL_LIST_ENTRY(inst)					\
 	{								\
-		.device_name = DT_INST_LABEL(inst),			\
+		.device_name = inst,					\
```
Comment (erwango) [inline drivers/adc/adc_shell.c:69]: If I reading it right (otherwise, please discard this comment):
While this is working and doing the expected thing, the use of `inst` is misleading here.
In DT macros, we're usually calling INST the ordinal number of the node (2nd, 3rd, ..).
In `ADC_HDL_LIST_ENTRY`, the argument is actually the label property value ("ADC_X" string).

So, to clarify this piece of code, I'd witch argument to something less misleading: `node_label` or similar.

**Comment by erwango** [comment]
@jakub-uC basic test ok

File: drivers/adc/adc_shell.c (hunk 1 above)
Comment (jakub-uC) [reply drivers/adc/adc_shell.c:69]: Sure, I will update the naming. It is a property label like `ADC_0` or `ADC_1`.

**Review by erwango — APPROVED** [review]
Approved from my side, but need ADC friends reviews.

File: drivers/adc/adc_shell.c [hunk 2]
```diff
@@ -233,256 +214,198 @@ static int cmd_adc_acq(const struct shell *shell, size_t argc, char **argv)
...
-	/* Alphabetically sorted. */
-	SHELL_CMD(VDD_1, NULL, "VDD", cmd_adc_ref),
-	SHELL_CMD(VDD_1_2, NULL, "VDD/2", cmd_adc_ref),
-	SHELL_CMD(VDD_1_3, NULL, "VDD/3", cmd_adc_ref),
-	SHELL_CMD(VDD_1_4, NULL, "VDD/4", cmd_adc_ref),
-	SHELL_CMD(INT, NULL, "Internal", cmd_adc_ref),
-	SHELL_CMD(EXT0, NULL, "EXT0", cmd_adc_ref),
-	SHELL_CMD(EXT1, NULL, "EXT1", cmd_adc_ref),
-	SHELL_SUBCMD_SET_END /* Array terminated. */
+	SHELL_CMD_ARG(VDD_1, NULL, "VDD", cmd_adc_ref, 1, 0),
```
Comment (nordic-krch) [inline drivers/adc/adc_shell.c:358]: we could think at some point about shell extension which would allow creating subcommand with a dictionary. In that case argv would contain direct value. Something like
```
SHELL_STATIC_SUBCMD_DICT_CREATE(sub, dictionary_array)
```
where array contains string + value. String for tab handle, value passed to command handler. That would make code much compact in cases like this and there are many cases like this one.

Comment (jakub-uC) [reply drivers/adc/adc_shell.c:358]: May you please create an issue for that?

**Review by nordic-krch — APPROVED** [review]

File: drivers/adc/adc_shell.c [hunk 3]
```diff
@@ -52,178 +72,139 @@ struct adc_hdl {
...
 	}
-	adc_list[chosen_adc].channel_config.channel_id =
+
+	adc->channel_config.channel_id =
 		(uint8_t)strtol(argv[args_indx.conf], NULL, 10);
-	retval = adc_channel_setup(adc_dev,
-			&adc_list[chosen_adc].channel_config);
+
+	if (IS_ENABLED(CONFIG_ADC_CONFIGURABLE_INPUTS)) {
+		adc->channel_config.input_positive = 1;
```
Comment (anangl) [inline drivers/adc/adc_shell.c:164]: This should not be hard-coded. Users should be able to select the input to use. And this value may be even invalid for some drivers.

Comment (jakub-uC) [reply drivers/adc/adc_shell.c:164]: @anangl Do you think it is a good idea to add one more command for setting this value?

File: drivers/adc/adc_shell.c [hunk 4]
```diff
@@ -32,17 +34,35 @@
...
-#define ADC_HDL_LIST_ENTRY(inst)					\
+#define CMD_HELP_READ				\
+	"Read adc value\n"			\
+	"Usage: read <channel>\n"
+
+#define CMD_HELP_RES				\
+	"Configure resolution\n"		\
+	"Usage: resolution <resolution>\n"
+
+#define CMD_HELP_REF	"Configure resolution\n"
```
[the remark this answers is not in the document]
Comment (jakub-uC) [reply drivers/adc/adc_shell.c]: fixed

**Comment by carlescufi** [comment]
@anangl please take another look

File: drivers/adc/adc_shell.c [hunk 5]
```diff
@@ -32,17 +34,45 @@
...
+	"Configure acquisition time."		\
+	"\nUsage: acq_time <time> <unit>"	\
+	"\nunits: us, ns, ticks\n"
+
+#define CMD_HELP_CHANNEL			\
+	"Configure ADC channel\n"
+
+#define CMD_HELP_CH_ID				\
+	"Configure channel id\n"		\
+	"Usage: channel <channel_id>\n"
```
Comment (anangl) [inline drivers/adc/adc_shell.c:50]: I guess this should be
```suggestion
	"Usage: id <channel_id>\n"
```

File: drivers/adc/adc_shell.c [hunk 6]
```diff
@@ -52,178 +82,201 @@ struct adc_hdl {
...
+	{ .string = "ADC_GAIN_1_2", .gain = ADC_GAIN_1_2 },
+	{ .string = "ADC_GAIN_2_3", .gain = ADC_GAIN_2_3 },
+	{ .string = "ADC_GAIN_1", .gain = ADC_GAIN_1 },
+	{ .string = "ADC_GAIN_2", .gain = ADC_GAIN_2 },
+	{ .string = "ADC_GAIN_3", .gain = ADC_GAIN_3 },
+	{ .string = "ADC_GAIN_4", .gain = ADC_GAIN_4 },
+	{ .string = "ADC_GAIN_8", .gain = ADC_GAIN_8 },
+	{ .string = "ADC_GAIN_16", .gain = ADC_GAIN_16 },
+	{ .string = "ADC_GAIN_32", .gain = ADC_GAIN_32 },
+	{ .string = "ADC_GAIN_64", .gain = ADC_GAIN_64 }
```
Comment (anangl) [inline drivers/adc/adc_shell.c:123]: Could you add `ADC_GAIN_128` as well (here and in `sub_gain_cmds`), as it was added in `adc.h`?

Comment (jakub-uC) [reply drivers/adc/adc_shell.c]: done

File: drivers/adc/adc_shell.c (hunk 5 above)
Comment (jakub-uC) [reply drivers/adc/adc_shell.c]: fixed

**Review by anangl — APPROVED** [review]

**Comment by pabigot** [comment]
Last dev review we'd discussed #28566 and identified a generic way to associate devices with specific APIs.  @jakub-uC are you pursuing that approach?  Would doing that supersede this proposal?

It's a little hard to understand what this is doing since it packs a bunch of refactoring/reformatting along with the described device access change into a single commit.  I think there's a device access change in there somewhere.

**Comment by jakub-uC** [comment]
@pabigot : I think we can merge this PR and next it could be updated according to your proposal.

The most important parts of the code of this change are here:

```
static void cmd_adc_dev_get(size_t idx, struct shell_static_entry *entry)
{
	/* -1 because the last element in the list is a "list terminator" */
	if (idx < ARRAY_SIZE(adc_list) - 1) {
		entry->syntax  = adc_list[idx].device_label;  // <=== HERE
		entry->handler = NULL;
		entry->subcmd  = &sub_adc_cmds;
		entry->help    = "Select subcommand for ADC property label.\n";
	} else {
		entry->syntax  = NULL;
	}
}
```

Here: `entry->syntax  = adc_list[idx].device_label;` I need an array of strings with active ADCs. This string is used to: prompt a device name in the shell and bind an ADC device in the command handler.

A list of strings is created here:

```
#define INIT_MACRO() DT_INST_FOREACH_STATUS_OKAY(NODE_LABELS) "NA"

/* This table size is = ADC devices count + 1 (NA). */
static struct adc_hdl {
	char *device_label;
	struct adc_channel_cfg channel_config;
	uint8_t resolution;
} adc_list[] = {
	FOR_EACH(ADC_HDL_LIST_ENTRY, (,), INIT_MACRO())
};
```
I believe it is also part of the code that you would need to change according to your proposal.

**Review by pabigot — COMMENTED** [review]
From https://github.com/zephyrproject-rtos/zephyr/pull/28599#issuecomment-706090444

> @pabigot : I think we can merge this PR and next it could be updated according to your proposal.
> 
> The most important parts of the code of this change are here:

This ideally would have been done in multiple, focused commits. Among all the re-ordering of help and structure definitions, conversion from array index to pointer, etc it's not at all clear what was done and why.  Since this already has three approvals I'm not going to block this, but I'm not going to approve it because it's not worth the time to try to figure it all out.

**Comment by nordic-krch** [comment]
@jakub-uC what about using dictionary commands? Are you plan it in this PR?

**Comment by jakub-uC** [comment]
@nordic-krch : Yes I am reworking that and splitting to different commits. 
When this PR was submitted there were no dictionary commands on the master branch.

**Comment by jakub-uC** [comment]
@pabigot I've tried to make reasonable commits. The most important is the last commit: `adc_shell: rework commands`

In order to prompt valid ADC labels I've implemented dynamic command that is realized by the function `static void cmd_adc_dev_get(size_t idx, struct shell_static_entry *entry)`. What this function needs for proper work is an array of valid ADC labels that can be used to bind the ADC device.

If we know that the ADC label, for example, `ADC_0`, is prompted by the shell as a subcommand it is not needed in the commands handler to check if the device is on the list. This is why commands were simplified.
