### PR TITLE
net: l2: ethernet: arp: Fix ARP probe target HW address matching

### LINKED ISSUE #73038: IOT Devices disconnects if the Gateway is replaced with new gateway
**Describe the bug**
We have multiple IOT devices connected in lab network. The Gateway is helping route the IOT communication to external hub.
But if the Lab team replaces the Gateway all the device are disconnected and we need to to do manual reset of the devices.
With the change of the Gateway the ip address is kept same but the mac address gets changed so I think the device are not able to communicate through new Gateway device.

We are using NucleoH743 devices as IOT nodes connecting to Azure IOT hub.

**To Reproduce**
1. Establish IOT agent and IOT hub communication.
2. Change the Lab Gateway with same Gateway address. ( mac will be obviously different for different unit)
3. The IOT agent and Hub communication stops.
4. Restart the device the communication establishes.

**Expected behavior**
The reset of the device should not be required when gateway changes.
We have hundreds of devices connected in lab network where manual reset is not possible.

**Impact**
showstopper

**Environment (please complete the following information):**
 - OS: - NA
 - Toolchain - zephyr-sdk-0.15.2 
 - Zephyr RTOS version - v3.2.0

**Additional context**
target configuration - STM32H743

### PR DESCRIPTION
**Pull request by rlubos**
According to RFC3927 and RFC5227, an ARP probe target HW address should be set to all-zeroes:

"The 'target hardware address' field is ignored and SHOULD be set to all zeroes."

Hence, we should allow the ARP probes to have all-zeroes target HW address as well.

Fixes #73038

### CODE REVIEW

File: include/zephyr/net/ethernet.h [hunk 1]
```diff
@@ -725,6 +725,27 @@ static inline bool net_eth_is_addr_broadcast(struct net_eth_addr *addr)
 	return false;
 }
 
+/**
+ * @brief Check if the Ethernet MAC address is a all zeroes address.
+ *
+ * @param addr A valid pointer to a Ethernet MAC address.
+ *
+ * @return true if address is a all zeroes address, false if not
```
Comment (pdgendt) [inline include/zephyr/net/ethernet.h:733]:
```suggestion
 * @brief Check if the Ethernet MAC address is a all zeroes address.
 *
 * @param addr A valid pointer to an Ethernet MAC address.
 *
 * @return true if address is an all zeroes address, false if not
```

**Review by pdgendt — DISMISSED** [review]
Nit

File: include/zephyr/net/ethernet.h (hunk 1 above)
Comment (rlubos) [reply include/zephyr/net/ethernet.h]: Thanks, fixed

**Review by jukkar — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
