### PR TITLE
Bluetooth: host: Add check for already enabled in advertising set start

### LINKED ISSUE #33897: Bluetooth: extended advertising can't restart after connection
**Describe the bug**
A peripheral using an extended advertising set is unable to restart that advertising set to allow a second connection to a central while remaining connected to the first.

The error first occurs in `ull_adv.c` at line 994 when `node_rx_adv_term = ll_rx_alloc()` returns null.

**To Reproduce**
1. Create a Zephyr application using the provided `main.c` and `prj.conf` [prj.zip](https://github.com/zephyrproject-rtos/zephyr/files/6232986/prj.zip)
2. mkdir build; cd build
3. cmake -DBOARD=board\nrf52840dk_nrf52840
4. make
5. See error

**Expected behavior**
An extended advertising set should be able to be restarted after obtaining a connection to allow a second connection.

**Impact**
We cannot ship product unless we can obtain multiple connections to central devices, and we must use extended advertising sets to do so as we have a secondary, non-connectable advertisement that is broadcast simultaneously with the connectable advertising.

**Logs and console output**
```
00> [00:00:12.129,608] <dbg> bt_ctlr_hci_driver.prio_recv_thread: sem taken
00> 
00> [00:00:12.129,638] <dbg> bt_ctlr_hci_driver.prio_recv_thread: RX node enqueue
00> [00:00:12.129,638] <dbg> bt_ctlr_hci_driver.prio_recv_thread: RX node enqueue
00> [00:00:12.129,669] <dbg> bt_ctlr_hci_driver.prio_recv_thread: RX node enqueue
00> [00:00:12.129,669] <dbg> bt_ctlr_hci_driver.prio_recv_thread: sem take...
00> [00:00:12.129,699] <dbg> bt_ctlr_hci_driver.recv_thread: unblocked
00> [00:00:12.129,730] <dbg> bt_ctlr_hci_driver.recv_thread: Packet in: type:1 len:33
00> [00:00:12.129,730] <dbg> bt_hci_core.bt_recv: buf 0x2000d6a0 len 33
00> [00:00:12.129,730] <dbg> bt_hci_core.hci_event: event 0x3e
00> [00:00:12.129,730] <dbg> bt_hci_core.hci_le_meta_event: subevent 0x0a
00> [00:00:12.129,974] <dbg> bt_hci_core.enh_conn_complete: status 0x00 handle 0 role 1 peer 4F:53:10:9A:48:41 (random) peer RPA 00:00:00:00:00:00
00> [00:00:12.130,096] <dbg> bt_hci_core.enh_conn_complete: local RPA 00:00:00:00:00:00
00> [00:00:12.130,096] <dbg> bt_conn.bt_conn_ref: handle 0 ref 1 -> 2
00> [00:00:12.130,096] <dbg> bt_conn.bt_conn_unref: handle 0 ref 2 -> 1
00> [00:00:12.130,126] <dbg> bt_conn.bt_conn_ref: handle 0 ref 1 -> 2
00> [00:00:12.130,126] <dbg> bt_adv.bt_le_adv_resume: No valid legacy adv
00> [00:00:12.130,126] <dbg> bt_conn.bt_conn_set_state: connect-adv -> connected
00> [00:00:12.130,157] <dbg> bt_att.bt_att_accept: conn 0x20000980 handle 0
00> [00:00:12.130,187] <dbg> bt_l2cap.bt_l2cap_chan_add: conn 0x20000980 chan 0x20005348
00> [00:00:12.130,187] <dbg> bt_att.bt_att_connected: chan 0x20005348 cid 0x0004
00> [00:00:12.130,187] <dbg> bt_att.att_chan_attach: att 0x2000d84c chan 0x20005340 flags 0
00> [00:00:12.130,218] <dbg> bt_att.bt_att_status: chan 0x20005348 status 0x20005388
00> [00:00:12.130,218] <dbg> bt_l2cap.l2cap_accept: conn 0x20000980 handle 0
00> [00:00:12.130,218] <dbg> bt_l2cap.bt_l2cap_chan_add: conn 0x20000980 chan 0x20000b00
00> [00:00:12.130,218] <dbg> bt_l2cap.l2cap_connected: ch 0x20000b00 cid 0x0005
00> [00:00:12.130,218] <dbg> bt_smp.bt_smp_accept: conn 0x20000980 handle 0
00> [00:00:12.130,249] <dbg> bt_l2cap.bt_l2cap_chan_add: conn 0x20000980 chan 0x20000d08
00> [00:00:12.130,279] <dbg> bt_conn.bt_conn_set_state: disconnected -> connect-adv
00> [00:00:12.130,279] <dbg> bt_conn.bt_conn_ref: handle 0 ref 1 -> 2
00> [00:00:12.130,279] <dbg> bt_hci_core.bt_hci_cmd_create: opcode 0x2039 param_len 6
00> [00:00:12.130,310] <dbg> bt_hci_core.bt_hci_cmd_create: buf 0x2000d748
00> [00:00:12.130,310] <dbg> bt_hci_core.bt_hci_cmd_send_sync: buf 0x2000d748 opcode 0x2039 len 9
00> [00:00:12.130,340] <dbg> bt_hci_core.process_events: count 2
00> [00:00:12.130,340] <dbg> bt_hci_core.process_events: ev->state 4
00> [00:00:12.130,340] <dbg> bt_hci_core.send_cmd: calling net_buf_get
00> [00:00:12.130,371] <dbg> bt_hci_core.send_cmd: calling sem_take_wait
00> [00:00:12.130,371] <dbg> bt_hci_core.send_cmd: Sending command 0x2039 (buf 0x2000d748) to driver
00> [00:00:12.130,371] <dbg> bt_hci_core.bt_send: buf 0x2000d748 len 9 type 0
00> [00:00:12.130,371] <dbg> bt_ctlr_hci_driver.hci_driver_send: enter
00> [00:00:12.130,432] <dbg> bt_buf.bt_buf_get_cmd_complete: sent_cmd 0x2000d748
00> [00:00:12.130,432] <dbg> bt_ctlr_hci_driver.cmd_handle: Replying with event of 6 bytes
00> [00:00:12.130,432] <dbg> bt_hci_core.hci_cmd_complete: opcode 0x2039
00> [00:00:12.130,462] <dbg> bt_hci_core.hci_cmd_done: opcode 0x2039 status 0x07 buf 0x2000d748[0m
00> [00:00:12.130,462] <dbg> bt_ctlr_hci_driver.hci_driver_send: exit: 0
00> [00:00:12.130,462] <dbg> bt_hci_core.process_events: ev->state 1
00> [00:00:12.130,493] <dbg> bt_conn.bt_conn_prepare_events: 
00> [00:00:12.130,493] <dbg> bt_conn.conn_prepare_events: Adding conn 0x20000980 to poll list
00> [00:00:12.130,493] <dbg> bt_hci_core.hci_tx_thread: Calling k_poll with 3 events
00> [00:00:12.130,523] <wrn> bt_hci_core: opcode 0x2039 status 0x07
00> [00:00:12.130,523] <err> bt_adv: Failed to start advertiser
00> [00:00:12.130,523] <dbg> bt_conn.bt_conn_set_state: connect-adv -> disconnected
00> [00:00:12.130,554] <dbg> bt_conn.bt_conn_unref: handle 0 ref 2 -> 1
00> [00:00:12.130,554] <dbg> bt_conn.bt_conn_unref: handle 0 ref 1 -> 0
00> [00:00:12.130,554] <dbg> bt_adv.bt_le_adv_resume: No valid legacy adv
00> [00:00:12.130,554] <err> os: r0/a1:  0x00000003  r1/a2:  0x00000000  r2/a3:  0x20000880
00> [00:00:12.130,584] <err> os: r3/a4:  0x00000036 r12/ip:  0x00000000 r14/lr:  0x000029b3
00> [00:00:12.130,584] <err> os:  xpsr:  0x61000000
00> [00:00:12.130,584] <err> os: Faulting instruction address (r15/pc): 0x00001c4e
00> [00:00:12.130,584] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
00> [00:00:12.130,584] <err> os: Current thread: 0x20000f08 (unknown)
00> [00:00:13.856,811] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: GNU Arm Embedded 10 2020-q4-major
 - Commit SHA or Version used: f282c93b9a71baf411b20c33cb8e4f4de2570156

### PR DESCRIPTION
**Pull request by joerchan**
Add check for the advertising already being enabled when attempting to
start the advertising set.
Document that the advertising set cannot be started from the connection
connected callback, and instead has to be started from the advertising
set connected callback.

Fixes: #33897

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

File: include/bluetooth/conn.h [hunk 1]
```diff
@@ -769,6 +769,11 @@ struct bt_conn_cb {
 	 *  In case the err parameter is non-zero it means that the
 	 *  connection establishment failed.
 	 *
+	 *  @note If the connection was estableshed from an advertising set then
```
Comment (cvinayak) [inline include/bluetooth/conn.h:772]:
```suggestion
	 *  @note If the connection was established from an advertising set then
```

**Review by cvinayak — DISMISSED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
