### PR TITLE
usb: Add macro for user defined string descriptors

### LINKED ISSUE #41017: USB string descriptors can be re-ordered causing corruption and out-of-bounds-write
**Describe the bug**
While trying to implement a USB video device I encountered
unexpected errors in `dmesg` when plugging in the device.

I managed to to track the problem to the single string descriptor I had
defined. I believe my string descriptor was placed before the other string descriptors
(`string_descr` in `usb_descriptor.c`) by the linker, causing the `usb_fix_descriptor`
routine to break in ways I don't yet understand.
I have created a PR https://github.com/zephyrproject-rtos/zephyr/pull/41014  that fixes my issue by disambiguating the order
between string descriptor zero and other string descriptors.

**To Reproduce**
Since the issue is with under specified section ordering I have not
been able to find a way to reproduce this with any in-tree boards or samples.

I'm working on my USB video class driver out-of-tree application,
that might affect the link order.

The following config options were helpful in discovering the cause:
```
CONFIG_USB_DEVICE_LOG_LEVEL_DBG=y
CONFIG_LOG_BUFFER_SIZE=4096
```

**Logs and console output**
Log output during descriptor fixup:
```
[00:00:00.000,000] <dbg> usb_descriptor.usb_get_device_descriptor: __usb_descriptor_start 0x20000190
[00:00:00.000,000] <dbg> usb_descriptor.usb_get_device_descriptor: __usb_descriptor_end 0x20000298
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Configuration descriptor 0x200001a2
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Association descriptor 0x200001ab
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Interface descriptor 0x200001b3
[00:00:00.000,000] <dbg> usb_video.video_interface_config: function_string_desc: 0x2000024a
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Interface descriptor 0x200001e4
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Interface descriptor 0x20000234
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Skip alternate interface
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Interface descriptor 0x2000023a
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Skip alternate interface
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Endpoint descriptor 0x20000243
[00:00:00.000,000] <dbg> usb_descriptor.usb_validate_ep_cfg_data: Fixing EP address 80 -> 81
[00:00:00.000,000] <dbg> usb_descriptor.usb_validate_ep_cfg_data: endpoint 0x81
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: Now the wTotalLength is 168
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: idx_max 1, ascii_idx_max 0, buf 0x20000254
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char 	: 9, idx 0 -> 1
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: idx_max 11, ascii_idx_max 5, buf 0x20000258
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char R : 52, idx 5 -> 11
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char Y : 59, idx 4 -> 9
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char H : 48, idx 3 -> 7
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char P : 50, idx 2 -> 5
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char E : 45, idx 1 -> 3
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char Z : 5a, idx 0 -> 1
[00:00:00.000,000] <dbg> usb_descriptor: Serial Number
                                         30 39 51 12 00 31 80 0e                          |09Q..1..         
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: idx_max 13, ascii_idx_max 6, buf 0x20000266
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char 1 : 31, idx 6 -> 13
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char 1 : 31, idx 5 -> 11
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char 5 : 35, idx 4 -> 9
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char 9 : 39, idx 3 -> 7
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char 3 : 33, idx 2 -> 5
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char 0 : 30, idx 1 -> 3
[00:00:00.000,000] <dbg> usb_descriptor.ascii7_to_utf16le: char 3 : 33, idx 0 -> 1
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x2000032d
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x2000032f
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000331
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000333
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000335
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000337
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000339
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x2000033b
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x2000033d
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x2000033f
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000341
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000343
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000345
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000347
[00:00:00.000,000] <dbg> usb_descriptor.usb_fix_descriptor: try to fix next descriptor at 0x20000349
[00:00:00.000,000] <err> usb_descriptor: Incomplete device descriptor
[00:00:00.000,000] <err> usb_descriptor: Failed to fixup USB descriptor
[00:00:00.000,000] <err> usb_device: Failed to configure USB device stack
```

Output from dmesg when plugging in device with broken descriptor.
```
[36837.798905] usb 1-9.3: new full-speed USB device number 60 using xhci_hcd
[36837.799222] usb 1-9.3: Device not responding to setup address.
[36838.007260] usb 1-9.3: Device not responding to setup address.
[36838.214879] usb 1-9.3: device not accepting address 60, error -71
[36838.398888] usb 1-9.3: new full-speed USB device number 61 using xhci_hcd
[36838.399201] usb 1-9.3: Device not responding to setup address.
[36838.607032] usb 1-9.3: Device not responding to setup address.
[36838.818905] usb 1-9.3: device not accepting address 61, error -71
[36838.819032] usb 1-9-port3: unable to enumerate USB device
```

**Environment:**
 - OS: Debian 11 (5.10.0-9-amd64)
 - Toolchain: Zephyr SDK 0.13.1
 - Zephyr tag v2.7.0

### PR DESCRIPTION
**Pull request by abxy**
The new macro USBD_STRING_DESCR_USER_DEFINE works like
USBD_STRING_DESCR_DEFINE with the exception of being
ordered strictly after it. The new macro is needed to
ensures that user defined string descriptors can be added
without disturbing the order of string descriptors
defined by the usb subsystem.

Fixes  #41017

### CODE REVIEW

File: subsys/usb/usb_descriptor.c [hunk 1]
```diff
@@ -126,7 +126,7 @@ struct usb_string_desription {
  * placed in the string section.
  * FIXME: These should be sorted additionally.
```
Comment (abxy) [inline subsys/usb/usb_descriptor.c:127]: Maybe this commit warrants the removal of this FIXME.

File: include/usb/usb_device.h [hunk 2]
```diff
@@ -58,10 +58,12 @@ extern "C" {
...
 #define USBD_USER_DESCR_DEFINE(p) \
 	static __in_section(usb, descriptor_##p, 3) __used __aligned(1)
-#define USBD_STRING_DESCR_DEFINE(p) \
+#define USBD_INITIAL_STRING_DESCR_DEFINE(p) \
 	static __in_section(usb, descriptor_##p, 4) __used __aligned(1)
-#define USBD_TERM_DESCR_DEFINE(p) \
+#define USBD_STRING_DESCR_DEFINE(p) \
 	static __in_section(usb, descriptor_##p, 5) __used __aligned(1)
+#define USBD_TERM_DESCR_DEFINE(p) \
+	static __in_section(usb, descriptor_##p, 6) __used __aligned(1)
```
Comment (jfischer-no) [inline include/usb/usb_device.h:66]: Better the other way around with minimal changes, just:
```diff
diff --git a/include/usb/usb_device.h b/include/usb/usb_device.h
index 8884c8afbbe..83abab6755f 100644
--- a/include/usb/usb_device.h
+++ b/include/usb/usb_device.h
@@ -60,8 +60,10 @@ extern "C" {
        static __in_section(usb, descriptor_##p, 3) __used __aligned(1)
 #define USBD_STRING_DESCR_DEFINE(p) \
        static __in_section(usb, descriptor_##p, 4) __used __aligned(1)
-#define USBD_TERM_DESCR_DEFINE(p) \
+#define USBD_STRING_DESCR_USER_DEFINE(p) \
        static __in_section(usb, descriptor_##p, 5) __used __aligned(1)
+#define USBD_TERM_DESCR_DEFINE(p) \
+       static __in_section(usb, descriptor_##p, 6) __used __aligned(1)
 
 /*
  * This macro should be used to place the struct usb_cfg_data
```

Please revise you commit message, among others: "Without this fix, the order between individual string descriptors is undefined." is not correct. The order is well defined, you just need to understand how it works.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: include/usb/usb_device.h (hunk 2 above)
Comment (abxy) [reply include/usb/usb_device.h:66]: What would be a better wording? The order might not be "undefined" per se, but from what I can tell there is currently no explicit constraint to ensure that the "initial" string descriptors are really placed first.

Comment (jfischer-no) [reply include/usb/usb_device.h:66]: Something like: "Add a new macro to define string descriptors in the user code more easily with the respect for the correct order."

Comment (carlescufi) [reply include/usb/usb_device.h:66]: @abxy could you please follow-up to @jfischer-no's comment above?

Comment (abxy) [reply include/usb/usb_device.h:66]: Sorry. The project where I needed this fix kind of fell to the wayside. I have changed the implementation like @jfischer-no suggested, and updated the commit message & PR description.

Comment (jfischer-no) [reply include/usb/usb_device.h:66]: Thank you @abxy

**Review by jfischer-no — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
