### PR TITLE
posix: multi process: add support for times()

### LINKED ISSUE #51978: newlib integration: _times isn't mapped to _times_r
**Describe the bug**

Using the newlib libc in Zephyr, the clock() and/or time() functions call the _times_r function which requires the _times function to be supplied, but this function is missing and the compilation fails at link time.

I have tested this while trying to create a lua module for Zephyr. Lua uses both the clock() and the time() function and the compilation fails with the following error:

... zephyr-sdk-0.15.0/arm-zephyr-eabi/arm-zephyr-eabi/lib/thumb/v7e-m/nofp/libc.a(lib_a-timesr.o): in function `_times_r':
timesr.c:(.text._times_r+0x2): undefined reference to `_times'
collect2: error: ld returned 1 exit status

**To Reproduce**

I prepared a hello_world example available at: https://github.com/tenllado/zephyr_hello_world_lua

The README.md file contains instructions to compile it as a west workspace. The project includes a file src/missing_stubs.c a definition of _times (and also _unlink, which is also missing in Zephyr). If you comment the _times definition you will obtain the error mentioned above.

**Expected behavior**
Zephyr should be including a definition of the _times function for the newlib libc library.

**Impact**
The absence of this function prevents the full support of the lua library for the zephyr project.

**Environment (please complete the following information):**
- OS: Linux
 - Toolchain: zephyr-sdk-0.15.0
 - Commit SHA: sha for the zephyr project is 8db84cfa6a954e466d3c7d416afeb1d638df6c69

### PR DESCRIPTION
**Pull request by cfriedt**
Add support for the `times()` function, which can be used to get the number of ticks spent in "system" and "user" mode, and which returns the "real time" that has expired, since an arbitrary point in the past.

The following invariant should always hold:

```
rtime <= stime + utime
```

The `times()` function measures time for the calling process and all of it's child processes. In Zephyr, we don't support separate processes (yet), so the time spent in child processes is zero.

Additionally, in Zephyr we do not differentiate between "system" time (i.e. time spent executing kernel code) and "user" time (time spent executing application code). We only have information on "total time" (time spent executing code) and "execution time" (time spent executing code plus idle time).

For now, only report utime, since it is not clear how to obtain other values.

The `times()` function is part of the `POSIX_MULTI_PROCESS` Option Group. For more information, please see
https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_subprofiles.html

Closes #51978

> [!NOTE]
> This was added in order to facilitate lua as a Zephyr module

cc @tenllado @oscarbaselga @alexayl @agguo @danjshaw

### CODE REVIEW

**Comment by cfriedt** [comment]
Code Sonar warning is a false positive

File: tests/posix/timers/src/sleep.c [hunk 1]
```diff
@@ -24,37 +24,6 @@ static void waker_func(struct k_work *work)
 }
 K_WORK_DELAYABLE_DEFINE(waker, waker_func);
 
-ZTEST(posix_timers, test_sleep)
```
Comment (sylvioalves) [inline tests/posix/timers/src/sleep.c:27]: With this change it will miss testing `test_sleep`  when the below is not met, right?
`CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=8192`

I am not sure if it is an issue though. Overall LGTM.
```c
  portability.posix.muti_process.newlib:
    filter: TOOLCHAIN_HAS_NEWLIB == 1
    extra_configs:
      - CONFIG_NEWLIB_LIBC=y
      - CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=8192
```

Comment (cfriedt) [reply tests/posix/timers/src/sleep.c:27]: Hmm... Yeah, that requirement seems a tad unnecessary. I can fix it.

Comment (cfriedt) [reply tests/posix/timers/src/sleep.c:27]: Fixed!

**Review by sylvioalves — APPROVED** [review]

**Review by ycsin — APPROVED** [review]
