### PR TITLE
Fix version string formatting

### LINKED ISSUE #45261: mcumgr: conversion of version to string fails (snprintf format issue)
**Describe the bug**
The version information is not correctly converted to a string when querying image slots.

**To Reproduce**
run `mcumgr image list` command with suitable firmware.

The version string received is: `hu.hu.`

**Expected behavior**
Version should be converted correctly

**Impact**
showstopper

**Logs and console output**

hexdump of response:
<pre>
    0000  01 00 00 87 00 01 00 00  bf 66 69 6d 61 67 65 73  |.........fimages|
    0016  9f bf 64 73 6c 6f 74 00  67 76 65 72 73 69 6f 6e  |..dslot.gversion|
    0032  66 68 75 2e 68 75 2e 64  68 61 73 68 58 20 c5 ef  |f<b>hu.hu.</b>dhashX ..|
    0048  01 3a 69 e8 2e f7 f8 24  e9 83 86 46 a0 58 48 3b  |.:i....$...F.XH;|
    0064  49 27 a3 64 0d f0 37 0d  01 56 e2 a8 e9 16 68 62  |I'.d..7..V....hb|
    0080  6f 6f 74 61 62 6c 65 f5  67 70 65 6e 64 69 6e 67  |ootable.gpending|
    0096  f4 69 63 6f 6e 66 69 72  6d 65 64 f5 66 61 63 74  |.iconfirmed.fact|
    0112  69 76 65 f5 69 70 65 72  6d 61 6e 65 6e 74 f4 ff  |ive.ipermanent..|
    0128  ff 6b 73 70 6c 69 74 53  74 61 74 75 73 00 ff     |.ksplitStatus.. |
</pre>

gdb log

<pre>
Breakpoint 2, img_mgmt_ver_str (ver=ver@entry=0x2000272c <sys_work_q_stack+1492>, dst=dst@entry=0x20002754 <sys_work_q_stack+1532> "hu.hu.")
    at $ZEPHYR_BASE/subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:15
15	{
(gdb) p ver
$11 = (const struct image_version *) 0x2000272c <sys_work_q_stack+1492>
(gdb) p *ver
$12 = <b>{iv_major = 0 '\000', iv_minor = 0 '\000', iv_revision = 1, iv_build_num = 0}</b>
(gdb) l
10	#include "img_mgmt/image.h"
11	#include "img_mgmt/img_mgmt.h"
12	
13	int
14	img_mgmt_ver_str(const struct image_version *ver, char *dst)
15	{
16		int rc = 0;
17		int rc1 = 0;
18	
19		rc = snprintf(dst, IMG_MGMT_VER_MAX_STR_LEN, <b>"%hhu.%hhu.%.hu"</b>,
(gdb) n
19		rc = snprintf(dst, IMG_MGMT_VER_MAX_STR_LEN, "%hhu.%hhu.%.hu",
(gdb) p rc
$14 = 6
(gdb) p dst
$15 = 0x20002754 <sys_work_q_stack+1532> <b>"hu.hu."</b>
...
img_mgmt_state_read (ctxt=<optimized out>) at $ZEPHYR_BASE/subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_state.c:235
235					vers_str[sizeof(vers_str) - 1] = '\0';
(gdb) p vers_str 
$17 = "hu.hu.\000\252\315\025\001\020\000\000\000\000\223+\000 \247'\000", <incomplete sequence \315>
</pre>

**Environment (please complete the following information):**
 - Commit SHA 3.0.99: main@83c79d10510e28e8706581168d257c1b556732d2
 
**Additional context**
Probably relevant config of libc

```
Config lib c

#
# C Library
#
CONFIG_SUPPORT_MINIMAL_LIBC=y
# CONFIG_MINIMAL_LIBC is not set
CONFIG_NEWLIB_LIBC=y
# CONFIG_EXTERNAL_LIBC is not set
CONFIG_HAS_NEWLIB_LIBC_NANO=y
CONFIG_NEWLIB_LIBC_NANO=y
CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=2048
# CONFIG_NEWLIB_LIBC_FLOAT_PRINTF is not set
# CONFIG_NEWLIB_LIBC_FLOAT_SCANF is not set
# CONFIG_NEWLIB_LIBC_HEAP_LISTENER is not set
```

**Tests/Fixes**
Problem was found with a LPC55S28 SoC.

There are two problems here
1. `%hhu` format is not recognized with this libc configuration. Might also be an integer width problem?
2. The version number is not correctly formated, if build_num != 0 and patch == 0: `255.255..4294967295`

Note: the following format string works for this configuration: `"%hu.%hu.%hu"`, also for the maximum possible version+build number and also problem 2.

### PR DESCRIPTION
**Pull request by de-nordic**
Fixes astray dot (my bad) and a problem with newlib not recognizing %hhu formatting ~~(their bad)~~ when `CONFIG_NEWLIB_LIBC_NANO=y`

Fixes #45261

### CODE REVIEW

File: subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c [hunk 1]
```diff
@@ -16,8 +16,9 @@ img_mgmt_ver_str(const struct image_version *ver, char *dst)
 	int rc = 0;
 	int rc1 = 0;
 
-	rc = snprintf(dst, IMG_MGMT_VER_MAX_STR_LEN, "%hhu.%hhu.%hu",
-		ver->iv_major, ver->iv_minor, ver->iv_revision);
+	rc = snprintf(dst, IMG_MGMT_VER_MAX_STR_LEN, "%hu.%hu.%hu",
+		(uint16_t)ver->iv_major, (uint16_t)ver->iv_minor,
+		ver->iv_revision);
```
Comment (stephanosio) [inline subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: > The "New C Library" (CONFIG_NEWLIB_LIBC=y) does not correctly
process %hhu formatting, causing a version string to be returned
malformed

Could you elaborate? How does it get malformed? Also what toolchain/version did you use?

p.s. "New C Lib" is an interesting way to refer to the "newlib;" it should be just called "newlib" like a proper noun.

Comment (de-nordic) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: > 
> Could you elaborate? How does it get malformed? Also what toolchain/version did you use?

Here is bug that describes the issue: https://github.com/zephyrproject-rtos/zephyr/issues/45261, in short:
when you do the "%hhu", to format char or uint8_t,  it will print "hu", for example:
```
$$ sudo ~/go/bin/mcumgr -t 1200 --conntype ble --connstring ctlr_name=hci0,peer_name='Zephyr' image list
Images:
 image=0 slot=0
    version: 0.0.0
    bootable: true
    flags: active confirmed
    hash: 8fc300ef78d8471420c9f46e7ff311707c48807c253df48b54a847c8e5db7fd7
 image=0 slot=1
    version: 0.0.0
    bootable: true
    flags:
    hash: e3364341a7fc9ecaada6709b757ba72e90389012eaea7528999c9d39afd01ee1
Split status: N/A (0)
```
The SDK is zephyr-sdk-0.14.1, the SHA of Zephyr is d5e7732e0d0f66bc9a3684f9597d9fd6a2d351b2
> 
> p.s. "New C Lib" is an interesting way to refer to the "newlib;" it should be just called "newlib" like a proper noun.

Yeah, that was me being dumb and typing the "Kconfig" option prompt for memory, which obviously should be "Newlib C library"

I usually build and test the mcumgr,  by the smp_svr sample, on newlib and the minimal one, but somehow failed to do this this time and have failed to notice the problem.

Comment (stephanosio) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: Ok, I just tested this and `%hhu` and its friends are indeed broken (not enabled) -- moreover, `PRIu8` resolves to `%hhu` even for the newlib, so this is indeed very broken.

A brief investigation suggests that our newlib is being built without `_WANT_IO_C99_FORMATS`, so the `hh` modifier support is not enabled:
https://github.com/zephyrproject-rtos/newlib-cygwin/blob/2893dbb10f1fe3bf431a26f89a22e12a5020dc02/newlib/libc/stdio/vfprintf.c#L1105-L1110

I will file a separate bug for this and eventually get this fixed in the Zephyr SDK.

Comment (stephanosio) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: UPDATE: `_WANT_IO_C99_FORMATS` is enabled for the full newlib build, so it should work if you build with `CONFIG_NEWLIB_LIBC_NANO=n` (nano variant is used by default on ARM).

Nevertheless, the fact that `PRIu8` is `%hhu` for the newlib nano in spite of it not supporting the `hh` modifiers is wrong and needs to be fixed.

Comment (de-nordic) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: > 
> A brief investigation suggests that our newlib is being built without `_WANT_IO_C99_FORMATS`, so the `hh` modifier support is not enabled: https://github.com/zephyrproject-rtos/newlib-cygwin/blob/2893dbb10f1fe3bf431a26f89a22e12a5020dc02/newlib/libc/stdio/vfprintf.c#L1105-L1110

Quick find  👍 

> 
> I will file a separate bug for this and eventually get this fixed in the Zephyr SDK.

Thanks.

Comment (de-nordic) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: > UPDATE: `_WANT_IO_C99_FORMATS` is enabled for the full newlib build, so it should work if you build with `CONFIG_NEWLIB_LIBC_NANO=n` (nano variant is used by default on ARM).
> 

@stephanosio  Maybe it is not worth enabling another part of newlib  for this. I will just change commit message to not blame newlib on that and leave the fix.

Comment (stephanosio) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: > @stephanosio Maybe it is not worth enabling another part of newlib for this. I will just change commit message to not blame newlib on that and leave the fix.

The fundamental issue is that `inttypes.h` is not correctly resolving (I think it is a header inclusion issue, that the newlib-nano `newlib.h` is not included, and instead the full newlib `newlib.h` is included by `inttypes.h`) the `PRIu8` inttype.

In case of the newlib-nano, `PRIu8` should be `%hu` (the closest type to `%hhu`), in which case you should be able to generalise the patch as `PRIu8 "." PRIu8 "." PRIu16`.

**Review by stephanosio — DISMISSED** [review]

File: subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c (hunk 1 above)
Comment (stephanosio) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: Filed #45336

Comment (de-nordic) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt_util.c:21]: > Filed #45336

Thank you!

**Comment by LeBlue** [comment]
@de-nordic Fix is working correctly, for both issues (`hu` in the version string and the stripped `ver_patch` number).

**Comment by de-nordic** [comment]
> @de-nordic Fix is working correctly, for both issues (`hu` in the version string and the stripped `ver_patch` number).

Thanks for testing!

**Comment by de-nordic** [comment]
@mbolivar-nordic  Can you take a look?

**Comment by de-nordic** [comment]
**Force push due to rebase with main**

**Review by mbolivar-nordic — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
