### PR TITLE
Bluetooth: GATT: Fix assuming CCC position

### LINKED ISSUE #28324: GATT notifications aren't working for CUD characteristics
**Describe the bug**
GATT notifications are not working with custom "Characteristic User Format Descriptors" (CUD) defined with BT_GATT_CUD. It is possible to read the values, but notifications are not working.

**To Reproduce**
1. ```west build -p auto -b nrf52840_pca10056 samples/bluetooth/peripheral_esp```
2. ```west flash```
3. Using a mobile phone or tablet, pair with "ESP peripheral" device
4. Open "nRF Connect" app and connect to the "ESP peripheral" device
5. Select "Environmental Sensing" service
6. Click the "Read" button to the right of "Temperature" (see attached picture) and notice a valid temperature reading (i.e. Value: 12.00°C)
7. Enabled notifications by clicking the "Notify" button to the right of "Temperature" (see attached picture) and notice that the temperature value never changes

Screenshot_20200911-113138

**Expected behavior**
The simulated temperature value should increment every second.

**Impact**
Due to this bug, I am unable to use newer versions of Zephyr, so for me, this is a showstopper for my project.

**Logs and console output**
Logs don't show anything different when it's working versus not working.

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: GNU Arm Embedded Toolchain 9-2020-q2-update
 - Commit SHA: e0f3ab6bf20e804fc6ac64fbb6f8397ddbd36a60

**Additional context**
Custom characteristic GATT notifications were working for me on version ```1.14.1``` of Zephyr. I noticed this problem when I tried to update to version ```2.3.0```. I ran ```git bisect``` to find the commit that caused the regression and was able to narrow the problem down to this commit: e0f3ab6bf20e804fc6ac64fbb6f8397ddbd36a60. The commit directly before that one works fine. When I compile and flashed the peripheral_hr sample on the offending commit, notifications work fine for the heart rate service measurement characteristic, for example, so I think this has something to do with custom characteristics.

### PR DESCRIPTION
**Pull request by Vudentz**
Accourding to the spec the CCC descriptor may occur in any position
 within the characteristic definition after the Characteristic Value.

Fixes #28324

### CODE REVIEW

**Comment by doceme** [comment]
@Vudentz, thanks for jumping on this so quickly! Very much appreciated.

**Comment by doceme** [comment]
I can confirm that this PR fixes the GATT notify issue with the ```peripheral_esp``` bluetooth sample as well as my project that uses a custom characteristic.

**Comment by carlescufi** [comment]
@joerchan could you please review?

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -2030,23 +2038,18 @@ static uint8_t notify_cb(const struct bt_gatt_attr *attr, uint16_t handle,
...
-struct find_data {
-	const struct bt_gatt_attr *attr;
-	uint16_t handle;
-};
-
 static uint8_t match_uuid(const struct bt_gatt_attr *attr, uint16_t handle,
 			  void *user_data)
 {
-	struct find_data *found = user_data;
+	struct notify_data *data = user_data;
```
Comment (joerchan) [inline subsys/bluetooth/host/gatt.c:2044]: Not sure I understand the reason for changing this here.

I think I would have preferred to use find data inside notify_data, don't need rest of the notify_data in this one.

```
struct notify_data {
    struct find_data found_chrc;
    /* ... */
};
```

**Review by joerchan — APPROVED** [review]
Looks correct. Added a suggestion though, the diff could have been smaller.
Mostly I think stack-size should be considered for my suggestion.

**Comment by joerchan** [comment]
@carlescufi @jhedberg Need another approval for this fix.

**Review by jhedberg — APPROVED** [review]
