### PR TITLE
log: net: Fix the immediate logging mode in network backend

### LINKED ISSUE #14661: samples/net/syslog_net fails for native_posix
**Describe the bug**
In native_posix configuration, syslog_net sample is not working

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=native_posix 
3. make run
4. Ensure syslogd is listening to the UDP port 514.
For example, in xubuntu, ensure that following is uncommented in /etc/rsyslogd.conf
``module(load="imudp")``
``input(type="imudp" port="514")``
5. Run
6. Observe syslog updates (e.g tail -f /var/log/syslog)

**Expected behavior**
Log items generated by Zephyr running in native_posix shoud be visible in syslog

**Impact**
While the sample works for qemu_x86 it does not generate any log entries for native_posix
Checking in Wireshark, reveals that no packets is sent over the net
 
**Environment (please complete the following information):**
Linux
SDK 0.10.0

### PR DESCRIPTION
**Pull request by jukkar**
If CONFIG_LOG_IMMEDIATE is enabled, then we need to handle
the output strings using a different output function.
The issue was noticed with native_posix board where no syslog
output strings were sent to network.

Fixes #14661

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

File: subsys/logging/log_backend_net.c [hunk 1]
```diff
@@ -216,10 +216,32 @@ static void panic(struct log_backend const *const backend)
...
+static void sync_string(const struct log_backend *const backend,
+		     struct log_msg_ids src_level, u32_t timestamp,
+		     const char *fmt, va_list ap)
+{
+	u32_t flags = LOG_OUTPUT_FLAG_LEVEL | LOG_OUTPUT_FLAG_FORMAT_SYSLOG |
+		LOG_OUTPUT_FLAG_TIMESTAMP;
+	u32_t key;
+
+	if (!net_init_done) {
+		net_init_done = true;
```
Comment (tbursztyka) [inline subsys/logging/log_backend_net.c]: Why setting it to true first? 

I don't see do_net_init() doing anything with net_init_done

So instead it could be:
`if (!net_init_done && do_net_init() == 0) {
    net_initi_done = true;
}`

Comment (jukkar) [reply subsys/logging/log_backend_net.c]: Could be done like that too, just copied the same check from `send_output()`. Beside if the `do_net_init()` fails, then it is probably not worth re-trying, so I made it to do the init only once.

Comment (tbursztyka) [reply subsys/logging/log_backend_net.c]: if net_init_done is reset to false, do_net_init() is going to be retried on another call.

Comment (jukkar) [reply subsys/logging/log_backend_net.c]: Yep, I was wrong. It tries indeed to re-init after all :)

Comment (jukkar) [reply subsys/logging/log_backend_net.c]: Ah, now I remember the logic here. We need to retry the net setup as it might be that the network is not yet ready when the logging is called, and so the setup might fail.

Comment (tbursztyka) [reply subsys/logging/log_backend_net.c]: yep makes sense. though the net_init_done check, set, unset could be revised.

File: subsys/logging/log_backend_net.c [hunk 2]
```diff
@@ -216,10 +216,32 @@ static void panic(struct log_backend const *const backend)
...
+	log_output_string(&log_output, src_level, timestamp, fmt, ap, flags);
+	irq_unlock(key);
+}
+
 const struct log_backend_api log_backend_net_api = {
-	.put = send_output,
 	.panic = panic,
 	.init = init_net,
+	.put = IS_ENABLED(CONFIG_LOG_IMMEDIATE) ? NULL : send_output,
+	.put_sync_string = IS_ENABLED(CONFIG_LOG_IMMEDIATE) ?
```
Comment (nordic-krch) [inline subsys/logging/log_backend_net.c]: you haven't add support for synchronous hexdump printing.

**Review by nordic-krch — CHANGES_REQUESTED** [review]

File: subsys/logging/log_backend_net.c (hunk 2 above)
Comment (jukkar) [reply subsys/logging/log_backend_net.c]: Yes, probably does not make sense to send hexdumps to remote syslog servers so I left it out.

Comment (nordic-krch) [reply subsys/logging/log_backend_net.c]: i see. Maybe it's work putting comment here about this decision. In future some may wonder.

**Review by nordic-krch — APPROVED** [review]

File: subsys/logging/log_backend_net.c (hunk 2 above)
Comment (jukkar) [reply subsys/logging/log_backend_net.c]: Sure, I will add comment about that.

File: subsys/logging/log_backend_net.c (hunk 1 above)
Comment (jukkar) [reply subsys/logging/log_backend_net.c]: I updated the net_init_done check.

**Review by tbursztyka — APPROVED** [review]
