### PR TITLE
kernel: mutex: delay setting lock_count = 0.

### LINKED ISSUE #11798: A thread may lock a mutex before it is fully unlocked.
**Describe the bug**
My team was trying to get Zephyr 1.13 to run on a RISC-V soft core we designed and implemented for the RISC-V Contest https://riscv.org/2018contest/ when we hit a bug in Zephyr.
After running the philosophers sample for some time the kernel fails like this:

`ASSERTION FAIL [mutex->owner == _kernel.current] @ /usr/local/share/zephyr/kernel/mutex.c:215:`

The issue is in this part of _impl_k_mutex_unlock:
```
	mutex->lock_count--;

	K_DEBUG("mutex %p lock_count: %d\n", mutex, mutex->lock_count);

	if (mutex->lock_count != 0) {
		k_sched_unlock();
		return;
	}

	key = irq_lock();

	adjust_owner_prio(mutex, mutex->owner_orig_prio);

	struct k_thread *new_owner = _unpend_first_thread(&mutex->wait_q);

	mutex->owner = new_owner;
```
What happens is:
Thread A:
1) It tries to unlock a mutex it is holding. 
2) `mutex->lock_count` is set to 0.
3) The thread recalculates its own priority.
4) At sometime thread B, which has a higher priority than A, becomes eligible to run
4) It calls `_thread_priority_set()` to reorder the run queue setting thread B first.
5) It calls `_reschedule()` and `_Swap()`s to B.
Thread B:
6) B calls `_impl_k_mutex_lock()` on the mutex A was holding.
7) B sees `mutex->lock_count == 0` and sets itself as its owner.
8) For some reason B is swapped and A starts running.
Thread A:
9) It is still in the `` function. It calls `_unpend_first_thread()` and gets thread C that was in the queue to lock the mutex.
10) A sets C as the owner of the mutex.

From this point on both B and C think they own the mutex. 
The assert is triggered when C tries to unlock the mutex after B unlocked it (it sets owner to NULL), or viceversa.

**To Reproduce**
1) Change the philosophers example.

```diff
@@ -183,7 +183,7 @@ void philosopher(void *id, void *unused1, void *unused2)
 		print_phil_state(my_id, "   HOLDING ONE FORK   ", 0);
 		take(fork2);

-		delay = get_random_delay(my_id, 25);
+		delay = get_random_delay(my_id, 2);
 		print_phil_state(my_id, "  EATING  [ %s%d ms ] ", delay);
 		k_sleep(delay);

@@ -191,7 +191,7 @@ void philosopher(void *id, void *unused1, void *unused2)
 		print_phil_state(my_id, "   DROPPED ONE FORK   ", 0);
 		drop(fork1);

-		delay = get_random_delay(my_id, 25);
+		delay = get_random_delay(my_id, 1);
 		print_phil_state(my_id, " THINKING [ %s%d ms ] ", delay);
 		k_sleep(delay);
 	}
```

2) Compile it with `cmake -GNinja -DBOARD=qemu_riscv32 ..` and run it with `ninja run`.
After a few seconds you should see the assert fail.

**Environment (please complete the following information):**
 - Zephyr 1.13 compiled for RV32I.

### PR DESCRIPTION
**Pull request by nicber**
Fixes #11798.

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Checkpatch is going to freak because the whitespace is wonky here and it's missing a proper body for that  the commit message (please add that -- the description in the bug is fine, but this is subtle and the reader looking at the commit in isolation isn't going to understand it).

But per the explanation in the bug, I think the logic is correct.  I'm sold anyway.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
Code looks good, but please fix your commit message to have a body and proper signed-off-by

File: kernel/mutex.c [hunk 1]
```diff
@@ -219,11 +219,11 @@ void _impl_k_mutex_unlock(struct k_mutex *mutex)
 
 	RECORD_STATE_CHANGE();
 
-	mutex->lock_count--;
 
 	K_DEBUG("mutex %p lock_count: %d\n", mutex, mutex->lock_count);
```
Comment (walter-xie) [inline kernel/mutex.c]: It will be better that move "K_DEBUG" after "k_mutex_unlock_return"
