### PR TITLE
arc: arm: fix support for MPUs on non-XIP systems

### LINKED ISSUE #15558: support for power-of-two MPUs on non-XIP systems
On a XIP system, text/rodata are on flash and all read-write memory are on SRAM. It's trivial to define MPU regions for each with appropriate permissions.

On a non-XIP system, text, rodata, and data are all in SRAM. We need the capability to configure a power-of-two sized subsection, starting at the lowest SRAM addresses, for text/rodata, and then pad this out so that data starts at the end of this region.

The size of memory reserved for text/rodata should be a configuration option (OK but not great solution), or somehow automatically derived (much better solution).

Since all power-of-two MPUs we have encountered to date support prioritized overlapping regions, we would have region definitions:

1. A lowest priority static region covering all of SRAM with supervisor read-write, no execute permissions
2. A higher-priority static region covering the first X bytes of memory with read-only, execute permissions, where X is some power of two which can fit all the text/rodata within it.

```
|------------------------SRAM REGION (rw) -------------------------|
|--------ROM REGION (rx)--------|

Then in the linker, pad out the beginning of the data section:

|--text--|--rodata--|--padding--|--data sections----|--unused RAM--|
```

Affected platforms are devices with the ARMv7 Cortex-M MPU (not NXP) and ARC devices with MPU version 2.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
We now use MPU_ALIGN() to set the location counter after the ROM region.
On non-power of two systems, this just rounds the location up to the MPU granularity, the parameter value is ignored.
On power of two systems, this rounds up appropriately based on the size of ROM.

Fixes: #15558

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

File: include/toolchain/gcc.h [hunk 1]
```diff
@@ -59,6 +59,16 @@
...
 
+/**
+ * Round the provided value up to the nearest power of two
+ *
+ * @param x Value to round up
+ * @return Provided value rounded up to next power of two
+ */
+#define POW2_CEIL(x) ((1 << (31 - __builtin_clz(x))) < x ?  \
+		1 << (31 - __builtin_clz(x) + 1) : \
+		1 << (31 - __builtin_clz(x)))
```
Comment (ulfalizer) [inline include/toolchain/gcc.h]: (http://locklessinc.com/articles/next_pow2/ might be interesting too. :)

File: arch/Kconfig [hunk 2]
```diff
@@ -462,6 +462,18 @@ config FP_SHARING
 
 endif # FLOAT
 
+config MPU_ROM_REGION_SIZE
+	int "Size of read-only/executable region in memory"
+	depends on !XIP
+	depends on MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT
+	depends on MEMORY_PROTECTION
```
Comment (ulfalizer) [inline arch/Kconfig]: Is there a sensible default that could be used here? `int` symbols default to an empty value instead of 0, which causes warnings when the `.config` is read back in.

File: include/toolchain/gcc.h (hunk 1 above)
Comment (andrewboie) [reply include/toolchain/gcc.h]: I would rather leave this exactly as-is, I just moved the definition.
Currently, if X is a constant, then this resolves to a constant at build time.

File: arch/Kconfig (hunk 2 above)
Comment (andrewboie) [reply arch/Kconfig]: Is there a way to make this a required configuration value?
In other words, if the depends criteria are met, and no value supplied, throw an error, rather than fill in 0 and generate a warning?

Comment (ulfalizer) [reply arch/Kconfig]: No way to have required values like that. Would get tricky to define. There's a bunch of utilities like `allyesconfig`, and it'd have to make sense for those too.

It's kinda-sorta required now though, in that you get a warning-turned-error if you load a configuration file that was saved without specifying it. Might not be the nicest kind of required though, since it also prevents the `menuconfig` from being run (see https://github.com/zephyrproject-rtos/zephyr/issues/9573, IMO that one's mostly a CMake issue).

Comment (ruuddw) [reply arch/Kconfig]: Why only having the option for a MPU_ROM_REGION for power of two MPU?
If the issue is to solve alignment of the 'rom region' in case of power-of-two, isn't there another way or a more clear name instead of MPU_ROM_REGION_SIZE?

File: include/arch/arc/arch.h [hunk 3]
```diff
@@ -34,51 +34,43 @@
 extern "C" {
 #endif
 
-#if defined(CONFIG_MPU_STACK_GUARD) || defined(CONFIG_USERSPACE)
```
Comment (ruuddw) [inline include/arch/arc/arch.h]: Thanks, this restructuring simplifies and avoids some duplications.

File: arch/Kconfig (hunk 2 above)
Comment (andrewboie) [reply arch/Kconfig]: > Why only having the option for a MPU_ROM_REGION for power of two MPU?

@ruuddw because if the MPU does not require power of two region alignment, there is no problem and none of this is necessary.
It's not clear to me what your objections are.

**Comment by andrewboie** [comment]
I found a much simpler way to do this entirely in the linker script.

I'll take off 'draft' status once I've done some more testing.

**Review by dcpleung — APPROVED** [review]

**Comment by andrewboie** [comment]
recheck

**Review by nashif — APPROVED** [review]
