### PR TITLE
mcumgr: BT SMP transport config for authenticated requirement

### LINKED ISSUE #16482: mcumgr seems to compromise BT security
## Introduction

I'm using a nrf52840 based custom peripheral in my project where I can upload FOTAs via mcumgr under Linux. My peripheral requests security (Mode 1, Level 4 with fixed passkey) after a connection request. All my peripheral's Characteristic and Descriptors are authenticated read/write only, except the mcumgr SMP BT service.

If I want to connect to the peripheral I get asked for the passkey as expected. There are three possibilities here:

- Entering the correct passkey -> peers will bond, connection fully established.
- Entering wrong passkey -> disconnect with authentication error.
- Entering nothing -> disconnect with authentication error after some amount of time.

Here are my security and pairing/bondig related configurations:

BT_SMP=y
BT_SMP_SC_ONLY=y
BT_SMP_SC_PAIR_ONLY=y
BT_FIXED_PASSKEY=y
BT_BONDABLE=y
BT_SETTINGS=y

### Problem description

When uploading images (or performing any other mcumgr operation on the peripheral) I won't get asked to enter a passkey, but I don't get a disconnect with an authentication error either. It seems that mcumgr is somehow able to break my security feature. I also tried this with peers that were unbonded (no previous pairing keys available) before.

This is a serious issue, because this compromises my security concept. How is this possible and how I can prevent this?

### PR DESCRIPTION
**Pull request by nixward**
This PR introduces a new Kconfig symbol MCUMGR_SMP_BT_AUTHEN.
When selected it configures the Bluetooth mcumgr transport to require
an authenticated connection.

If the Bluetooth mcumgr transport is selected then this new symbol is
selected by default.  Bluetooth SMP is also selected to ensure Zephyr
is configured with Bluetooth security features enabled to provide
Bluetooth authentication APIs to the user's app.  Users can choose to
disable this level of security for the Bluetooth mcumgr transport if
they do not require it.

This PR takes the approach of security by default so Zephyr samples that
selected MCUMGR_SMP_BT (and previously were not using authentication)
required this new symbol to be unselected.

Fixes #16482

Signed-off-by: Nick Ward <nix.ward@gmail.com>

### CODE REVIEW

**Comment by joerchan** [comment]
@carlescufi Why the bug-label? The issue is marked as enhancement.

**Comment by carlescufi** [comment]
> @carlescufi Why the bug-label? The issue is marked as enhancement.

True, thank you. I saw the `Fixes: ` in the description and wrongly assumed that this was fixing a bug.

File: subsys/mgmt/Kconfig [hunk 1]
```diff
@@ -14,6 +14,14 @@ config MCUMGR_SMP_BT
 	help
 	  Enables handling of SMP commands received over Bluetooth.
 
+config MCUMGR_SMP_BT_AUTHEN
+	bool "Authenticated requirement for Bluetooth mcumgr SMP transport"
+	depends on MCUMGR_SMP_BT
+	select BT_SMP
+	default y
+	help
+	  Enables authenticated connection requirement to Bluetooth SMP transport.
```
Comment (joerchan) [inline subsys/mgmt/Kconfig]: "Enables encrypted and authenticated ..."

**Review by joerchan — COMMENTED** [review]
Should we add the option for requiring encryption (but not authentication) as well?

File: subsys/mgmt/smp_bt.c [hunk 2]
```diff
@@ -76,9 +76,19 @@ static struct bt_gatt_attr smp_bt_attrs[] = {
 	BT_GATT_CHARACTERISTIC(&smp_bt_chr_uuid.uuid,
 			       BT_GATT_CHRC_WRITE_WITHOUT_RESP |
 			       BT_GATT_CHRC_NOTIFY,
+#ifdef CONFIG_MCUMGR_SMP_BT_AUTHEN
```
Comment (Vudentz) [inline subsys/mgmt/smp_bt.c]: Would that make sense to have an option to just encrypt or perhaps have a int option where the user can enter the level like we have done with CONFIG_NET_L2_BT_SEC_LEVEL.

**Comment by nixward** [comment]
I added the security label as depending on which components of mcumgr is enabled the mcumgr simple management protocol can reset a Zephyr device (this command is normally run at the end of the DFU process), modify files (possibly settings subsystem files), read system statistics, crash the system or manage logs.

**Comment by nixward** [comment]
> Should we add the option for requiring encryption (but not authentication) as well?

I don't think so as most of the commands involve managing/controlling the device or reading device statistics in which I don't think (only) secrecy helps.  Without authentication an attacker/snooper can just connect to and control or connect to and read the same data.

File: subsys/mgmt/Kconfig (hunk 1 above)
Comment (nixward) [reply subsys/mgmt/Kconfig]: Done

**Comment by joerchan** [comment]
> ~~Fixes~~ Implements enhancement for #16482

@nixward If you write "Fixes: # 123" it will auto-close the issue. So you should put it back, even though it is an enhancement and not a bug-fix :)

**Review by joerchan — APPROVED** [review]

File: subsys/mgmt/smp_bt.c (hunk 2 above)
Comment (nixward) [reply subsys/mgmt/smp_bt.c]: See my comment here: https://github.com/zephyrproject-rtos/zephyr/pull/20557#issuecomment-552405402

**Review by jhedberg — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by mrgsts** [comment]
I have hit the same problem, seems that mcumgr reset the connection and all of the pairing information is lost

Peek 25-10-2020 15-07
