### PR TITLE
shell: fix assert in panic mode

### LINKED ISSUE #38612: Fault with assertions enabled prevents detailed output because of ISR() assertion check in shell function
**Describe the bug**
If we have a firmware configured with a shell, a log and assertions enabled, when a fault happens the details should get printed to the screen, but this does not happen due to https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/shell/shell_ops.c#L481 in which cause we see the following output:
```
ASSERTION FAIL [!k_is_in_isr()] @ WEST_TOPDIR/zephyr/subsys/shell/shell_ops.c:481
Thread context required.
[01:39:59.425,964] <err> os: ***** MPU FAULT *****
```

Because the fault prompted an ISR to handle the fault, this means we lose all debug information because of this check which then reboots the module. I'm sure in a normal firmware you would want to check this, but this check is really not helpful for firmware development.

**Expected behavior**
If there is a fault, to not have the debug log reduced to a single line which makes it worthless because of this assertion check and for the full log to be printed

**Impact**
Major annoyance, I'm just removing the assertion check on this line in my local build because it's so annoying

### PR DESCRIPTION
**Pull request by jakub-uC**
In panic mode, the function: z_shell_fprintf is expected to be called from an interrupt context. Therefore, the dedicated assert
cannot be checked in this case.

Fixes #38612

### CODE REVIEW

**Comment by nordic-krch** [comment]
CI failures fixed by #38965

**Review by nordicjm — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

File: subsys/shell/shell_ops.c [hunk 1]
```diff
@@ -502,19 +502,22 @@ void z_shell_vfprintf(const struct shell *shell, enum shell_vt100_color color,
...
+	__ASSERT_NO_MSG(sh);
+	__ASSERT_NO_MSG(sh->ctx);
+	__ASSERT_NO_MSG(sh->fprintf_ctx);
 	__ASSERT_NO_MSG(fmt);
 
 	va_list args;
 
+	if (!z_flag_panic_mode_get(sh)) {
+		__ASSERT(!k_is_in_isr(), "Thread context required.");
+	}
```
Comment (pdgendt) [inline subsys/shell/shell_ops.c:518]: Why not
```suggestion
	__ASSERT(z_flag_panic_mode_get(sh) || !k_is_in_isr(), "Thread context required.");
```

Comment (jakub-uC) [reply subsys/shell/shell_ops.c:518]: good point
