### PR TITLE
bluetooth: gatt: Fix ATT Read By Type by DB change unaware client

### LINKED ISSUE #77088: net: buf: Pre-initialize `user_data` on `net_buf_alloc()`
## Introduction

We can initialize a net_buf's `user_data` member with a known pattern.
Just like the `CONFIG_INIT_STACKS` option.
 
### Problem description

It is not clear who owns `user_data`.
Is it the module that allocates it, the API that consumes it, something else?

With a known (non-null) initialized value, it will be possible to perform some checks and avoid head-scratching debug sessions. We've had some of those sessions in Bluetooth/L2CAP.

### Proposed change 

Call `memset(buf->user_data, 0xAA, buf->user_data_size)` in `net_buf_alloc()` right before returning `buf`.
Can be locked behind a kconfig, just like the stacks option.

### Concerns and Unresolved Questions

Other users (maybe out of tree too) could break due to `NULL` checks on user_data not working anymore.
E.g. the pattern of casting `cb` from `user_data` and having a block like this one:
```c
if (cb) {
  cb(some_param);
}
```

## Alternatives

- APIs that consume `net_buf`s enforce clearing by the application

### PR DESCRIPTION
**Pull request by sjanc**
When change unaware client send ATT request it shall get Database Out of Sync error. Reading GATT database hash is an exception here.

This was affecting GATT/SR/GAS/BV-05-C qualification test case.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/77088

### CODE REVIEW

File: subsys/bluetooth/host/att.c [hunk 1]
```diff
@@ -1548,6 +1548,19 @@ static uint8_t att_read_type_req(struct bt_att_chan *chan, struct net_buf *buf)
 		return 0;
 	}
 
+	/* Reading Database Hash is special as it is required to make client
```
Comment (Thalley) [inline subsys/bluetooth/host/att.c:1551]: In all the other cases we have this part

```c
	if (!bt_gatt_change_aware(chan->att->conn, true)) {
		if (!atomic_test_and_set_bit(chan->flags, ATT_OUT_OF_SYNC_SENT)) {
			return BT_ATT_ERR_DB_OUT_OF_SYNC;
		} else {
			return 0;
		}
	}
```

in the `rsp` functions. 

To be consistent, shouldn't we simply add the above to `att_read_type_rsp`?

Comment (Thalley) [reply subsys/bluetooth/host/att.c:1551]: If the point of this PR is adding the additional check `if (bt_uuid_cmp(&u.uuid, BT_UUID_GATT_DB_HASH) != 0) {`, then shouldn't that check be added to all read handlers? What if the client reads the database with `BT_ATT_OP_READ_REQ` instead of `BT_ATT_OP_READ_TYPE_REQ`?

Comment (sjanc) [reply subsys/bluetooth/host/att.c:1551]: This is not very consistent as some (att_read_mult_req, att_read_mult_vl_req) are handled in req handlers,  but I can do this in rsp too

**Comment by jhedberg** [comment]
@sjanc should this go into 3.7? If so, it likely requires a matching bug report (as well as the respective milestone set).

**Comment by MaureenHelm** [comment]
@sjanc @jhedberg ping

**Comment by jhedberg** [comment]
> @sjanc should this go into 3.7? If so, it likely requires a matching bug report (as well as the respective milestone set).

@sjanc I'm still waiting for a reply to this.

**Comment by sjanc** [comment]
If qualification fixes are to be backported to 3.7 than yes.

Note that this is stil pending review, preferably from someone familiar with robust GATT caching

**Comment by jhedberg** [comment]
> If qualification fixes are to be backported to 3.7 than yes.

They are. I added the necessary label now.

> Note that this is stil pending review, preferably from someone familiar with robust GATT caching

Ok. I'll wait with my approval until then.

**Comment by sjanc** [comment]
#AutoPTS run zephyr GATT/SR

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/75720#issuecomment-2306698978, board: nrf52, estimated start time: 11:37:46, test case count: 89, estimated duration: 0:41:51<details><summary>Test cases to be run</summary>GATT/SR/GAC/BV-01-C<br>GATT/SR/GAC/BI-01-C<br>GATT/SR/GAD/BV-01-C<br>GATT/SR/GAD/BV-02-C<br>GATT/SR/GAD/BV-03-C<br>GATT/SR/GAD/BV-04-C<br>GATT/SR/GAD/BV-05-C<br>GATT/SR/GAD/BV-06-C<br>GATT/SR/GAR/BV-01-C<br>GATT/SR/GAR/BI-01-C<br>GATT/SR/GAR/BI-02-C<br>GATT/SR/GAR/BI-03-C<br>GATT/SR/GAR/BI-04-C<br>GATT/SR/GAR/BI-05-C<br>GATT/SR/GAR/BV-03-C<br>GATT/SR/GAR/BI-06-C<br>GATT/SR/GAR/BI-07-C<br>GATT/SR/GAR/BI-08-C<br>GATT/SR/GAR/BI-09-C<br>GATT/SR/GAR/BI-10-C<br>GATT/SR/GAR/BI-11-C<br>GATT/SR/GAR/BV-04-C<br>GATT/SR/GAR/BI-12-C<br>GATT/SR/GAR/BI-13-C<br>GATT/SR/GAR/BI-14-C<br>GATT/SR/GAR/BI-15-C<br>GATT/SR/GAR/BI-16-C<br>GATT/SR/GAR/BI-17-C<br>GATT/SR/GAR/BV-05-C<br>GATT/SR/GAR/BI-18-C<br>GATT/SR/GAR/BI-19-C<br>GATT/SR/GAR/BI-20-C<br>GATT/SR/GAR/BI-21-C<br>GATT/SR/GAR/BI-22-C<br>GATT/SR/GAR/BV-06-C<br>GATT/SR/GAR/BV-07-C<br>GATT/SR/GAR/BV-08-C<br>GATT/SR/GAR/BV-09-C<br>GATT/SR/GAR/BV-11-C<br>GATT/SR/GAR/BV-12-C<br>GATT/SR/GAR/BI-36-C<br>GATT/SR/GAR/BI-38-C<br>GATT/SR/GAR/BI-40-C<br>GATT/SR/GAR/BI-42-C<br>GATT/SR/GAR/BI-44-C<br>GATT/SR/GAR/BI-45-C<br>GATT/SR/GAW/BV-01-C<br>GATT/SR/GAW/BV-02-C<br>GATT/SR/GAW/BI-01-C<br>GATT/SR/GAW/BV-03-C<br>GATT/SR/GAW/BI-02-C<br>GATT/SR/GAW/BI-03-C<br>GATT/SR/GAW/BI-04-C<br>GATT/SR/GAW/BI-05-C<br>GATT/SR/GAW/BI-06-C<br>GATT/SR/GAW/BV-05-C<br>GATT/SR/GAW/BI-07-C<br>GATT/SR/GAW/BI-08-C<br>GATT/SR/GAW/BI-09-C<br>GATT/SR/GAW/BI-11-C<br>GATT/SR/GAW/BI-12-C<br>GATT/SR/GAW/BI-13-C<br>GATT/SR/GAW/BV-06-C<br>GATT/SR/GAW/BV-10-C<br>GATT/SR/GAW/BV-11-C<br>GATT/SR/GAW/BV-07-C<br>GATT/SR/GAW/BV-08-C<br>GATT/SR/GAW/BV-09-C<br>GATT/SR/GAW/BI-32-C<br>GATT/SR/GAW/BI-33-C<br>GATT/SR/GAW/BV-12-C<br>GATT/SR/GAW/BV-13-C<br>GATT/SR/GAW/BV-14-C<br>GATT/SR/GAW/BI-38-C<br>GATT/SR/GAN/BV-01-C<br>GATT/SR/GAN/BV-02-C<br>GATT/SR/GAI/BV-01-C<br>GATT/SR/GAS/BV-01-C<br>GATT/SR/GAS/BV-02-C<br>GATT/SR/GAS/BV-03-C<br>GATT/SR/GAS/BV-04-C<br>GATT/SR/GAS/BV-05-C<br>GATT/SR/GAS/BV-06-C<br>GATT/SR/GAS/BV-07-C<br>GATT/SR/GAS/BV-08-C<br>GATT/SR/GAT/BV-01-C<br>GATT/SR/UNS/BI-01-C<br>GATT/SR/UNS/BI-02-C<br>GATT/SR/GPM/BV-05-C</details>

File: subsys/bluetooth/host/att.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/host/att.c:1551]: > This is not very consistent as some (att_read_mult_req, att_read_mult_vl_req) are handled in req handlers, but I can do this in rsp too

Planning any updates on this? 
It's unclear to me whether this PR needs a change or not

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GATT    GATT/SR/GAC/BI-01-C             PASS<br>GATT    GATT/SR/GAC/BV-01-C             PASS<br>GATT    GATT/SR/GAD/BV-01-C             PASS<br>GATT    GATT/SR/GAD/BV-02-C             PASS<br>GATT    GATT/SR/GAD/BV-03-C             PASS<br>GATT    GATT/SR/GAD/BV-04-C             PASS<br>GATT    GATT/SR/GAD/BV-05-C             PASS<br>GATT    GATT/SR/GAD/BV-06-C             PASS<br>GATT    GATT/SR/GAI/BV-01-C             PASS<br>GATT    GATT/SR/GAN/BV-01-C             PASS<br>GATT    GATT/SR/GAN/BV-02-C             PASS<br>GATT    GATT/SR/GAR/BI-01-C             PASS<br>GATT    GATT/SR/GAR/BI-02-C             PASS<br>GATT    GATT/SR/GAR/BI-03-C             PASS<br>GATT    GATT/SR/GAR/BI-04-C             PASS<br>GATT    GATT/SR/GAR/BI-05-C             PASS<br>GATT    GATT/SR/GAR/BI-06-C             PASS<br>GATT    GATT/SR/GAR/BI-07-C             PASS<br>GATT    GATT/SR/GAR/BI-08-C             PASS<br>GATT    GATT/SR/GAR/BI-09-C             PASS<br>GATT    GATT/SR/GAR/BI-10-C             PASS<br>GATT    GATT/SR/GAR/BI-11-C             PASS<br>GATT    GATT/SR/GAR/BI-12-C             PASS<br>GATT    GATT/SR/GAR/BI-13-C             PASS<br>GATT    GATT/SR/GAR/BI-14-C             PASS<br>GATT    GATT/SR/GAR/BI-15-C             PASS<br>GATT    GATT/SR/GAR/BI-16-C             PASS<br>GATT    GATT/SR/GAR/BI-17-C             PASS<br>GATT    GATT/SR/GAR/BI-18-C             PASS<br>GATT    GATT/SR/GAR/BI-19-C             PASS<br>GATT    GATT/SR/GAR/BI-20-C             PASS<br>GATT    GATT/SR/GAR/BI-21-C             PASS<br>GATT    GATT/SR/GAR/BI-22-C             PASS<br>GATT    GATT/SR/GAR/BI-36-C             PASS<br>GATT    GATT/SR/GAR/BI-38-C             PASS<br>GATT    GATT/SR/GAR/BI-40-C             PASS<br>GATT    GATT/SR/GAR/BI-42-C             PASS<br>GATT    GATT/SR/GAR/BI-44-C             PASS<br>GATT    GATT/SR/GAR/BI-45-C             PASS<br>GATT    GATT/SR/GAR/BV-01-C             PASS<br>GATT    GATT/SR/GAR/BV-03-C             PASS<br>GATT    GATT/SR/GAR/BV-04-C             PASS<br>GATT    GATT/SR/GAR/BV-05-C             PASS<br>GATT    GATT/SR/GAR/BV-06-C             PASS<br>GATT    GATT/SR/GAR/BV-07-C             PASS<br>GATT    GATT/SR/GAR/BV-08-C             PASS<br>GATT    GATT/SR/GAR/BV-09-C             PASS<br>GATT    GATT/SR/GAR/BV-11-C             PASS<br>GATT    GATT/SR/GAR/BV-12-C             PASS<br>GATT    GATT/SR/GAS/BV-01-C             PASS<br>GATT    GATT/SR/GAS/BV-02-C             PASS<br>GATT    GATT/SR/GAS/BV-03-C             PASS<br>GATT    GATT/SR/GAS/BV-04-C             PASS<br>GATT    GATT/SR/GAS/BV-05-C             PASS<br>GATT    GATT/SR/GAS/BV-06-C             PASS<br>GATT    GATT/SR/GAS/BV-07-C             PASS<br>GATT    GATT/SR/GAS/BV-08-C             PASS (2)<br>GATT    GATT/SR/GAT/BV-01-C             PASS<br>GATT    GATT/SR/GAW/BI-01-C             PASS<br>GATT    GATT/SR/GAW/BI-02-C             PASS<br>GATT    GATT/SR/GAW/BI-03-C             PASS<br>GATT    GATT/SR/GAW/BI-04-C             PASS<br>GATT    GATT/SR/GAW/BI-05-C             PASS<br>GATT    GATT/SR/GAW/BI-06-C             PASS<br>GATT    GATT/SR/GAW/BI-07-C             PASS<br>GATT    GATT/SR/GAW/BI-08-C             PASS<br>GATT    GATT/SR/GAW/BI-09-C             PASS<br>GATT    GATT/SR/GAW/BI-11-C             PASS<br>GATT    GATT/SR/GAW/BI-12-C             PASS<br>GATT    GATT/SR/GAW/BI-13-C             PASS<br>GATT    GATT/SR/GAW/BI-32-C             PASS<br>GATT    GATT/SR/GAW/BI-33-C             PASS<br>GATT    GATT/SR/GAW/BI-38-C             PASS<br>GATT    GATT/SR/GAW/BV-01-C             PASS<br>GATT    GATT/SR/GAW/BV-02-C             PASS<br>GATT    GATT/SR/GAW/BV-03-C             PASS<br>GATT    GATT/SR/GAW/BV-05-C             PASS<br>GATT    GATT/SR/GAW/BV-06-C             PASS<br>GATT    GATT/SR/GAW/BV-07-C             PASS<br>GATT    GATT/SR/GAW/BV-08-C             PASS<br>GATT    GATT/SR/GAW/BV-09-C             PASS<br>GATT    GATT/SR/GAW/BV-10-C             PASS<br>GATT    GATT/SR/GAW/BV-11-C             PASS<br>GATT    GATT/SR/GAW/BV-12-C             PASS<br>GATT    GATT/SR/GAW/BV-13-C             PASS<br>GATT    GATT/SR/GAW/BV-14-C             PASS<br>GATT    GATT/SR/GPM/BV-05-C             PASS<br>GATT    GATT/SR/UNS/BI-01-C             PASS<br>GATT    GATT/SR/UNS/BI-02-C             PASS</details>

File: subsys/bluetooth/host/att.c [hunk 2]
```diff
@@ -1549,6 +1549,23 @@ static uint8_t att_read_type_req(struct bt_att_chan *chan, struct net_buf *buf)
...
 	}
 
+	/* Reading Database Hash is special as it may be used to make client change aware
+	 * (Core Specification 5.4 Vol 3. Part G. 2.5.2.1 Robust Caching).
+	 *
+	 * GATT client shall always use GATT Read Using Characteristic UUID sub-procedure for
+	 * reading Database Hash
+	 * (Core Specification 5.4 Vol 3. Part G. 7.3 Databse Hash)
+	 */
+	if (bt_uuid_cmp(&u.uuid, BT_UUID_GATT_DB_HASH) != 0) {
```
Comment (Thalley) [inline subsys/bluetooth/host/att.c:1559]: Hmm, this made me think of whether we can/should reject reads to `BT_UUID_GATT_DB_HASH` from the other read requests?

**Review by Thalley — APPROVED** [review]
The changes look good. Possible extension to reject invalid read requests from other types may be needed

File: subsys/bluetooth/host/att.c (hunk 2 above)
Comment (sjanc) [reply subsys/bluetooth/host/att.c:1559]: other reads (and also wrtite reqs) are already handling it (that if bt_gatt_change_aware() blocks are doing that)

Comment (Thalley) [reply subsys/bluetooth/host/att.c:1559]: They are just blocking reading when the database is out of sync though, right? 

The core spec states that the client shall read the database sync with the read by type request (read by UUID). That means that even if the client is not out of sync, it shall not read the characteristic with e.g. a regular read request. Arguably that is a requirement on the client side, but we could (not sure if we should) block reads of that characteristic if not with read by type

**Review by jhedberg — APPROVED** [review]
