### PR TITLE
arch/x86: drivers/x86/apic_timer: new local APIC timer driver for x86

### LINKED ISSUE #16720: drivers/loapic_timer.c is buggy, needs cleanup
**Describe the bug**

The local APIC timer code is suffering from bitrot.  It will not build properly with `CONFIG_DEVICE_POWER_MANAGEMENT`, or `CONFIG_TICKLESS_KERNEL`, and even when it does, the timer ticks seem off by orders of magnitude (`k_sleep(1)` will sleep for nearly a second instead of a ms).  It needs an overhaul.

**To Reproduce**

For example, try to build with `CONFIG_DEVICE_POWER_MANAGEMENT` with the local APIC timer.  Add `CONFIG_DEVICE_POWER_MANAGEMENT=y CONFIG_LOAPIC_TIMER=y CONFIG_HPET_TIMER=n` options to `prj.conf` and try to build for an x86 target (`up_squared`).

`drivers/timer/loapic_timer.c:711:6: error: 'dev' undeclared (first use in this function)
   cb(dev, ret, context, arg);`

Attempting to build with `CONFIG_TICKLESS_KERNEL` gives a different build failure, but the point is that it fails to build.

**Impact**

Running on hypervisors (like `ACRN`) require the use of the local APIC timer as they don't virtualize the HPET, or virtualize it poorly, so the driver needs to be updated.  Doesn't affect any production systems now.

### PR DESCRIPTION
**Pull request by ghost**
The existing local APIC timer driver ~had~ has fallen into disuse in favor of the HPET timer by @andyross. As a result it's not been maintained through the last few timer API changes, especially tickless operation. For better or worse, the local APIC timer is making a raging comeback and is required for real-time operation with some hypervisors like ACRN.

Fixes: #16720

### CODE REVIEW

File: drivers/timer/apic_timer.c [hunk 1]
```diff
@@ -0,0 +1,378 @@
...
+
+u32_t z_timer_cycle_get_32(void)
+{
+	u32_t ret;
+	u32_t ccr;
+	u32_t icr;
+
+	k_spinlock_key_t key = k_spin_lock(&lock);
+	ccr = x86_read_loapic(LOAPIC_TIMER_CCR);
+	icr = x86_read_loapic(LOAPIC_TIMER_ICR);
```
Comment (andyross) [inline drivers/timer/apic_timer.c]: Sort of unfortunate naming.  The "ICR" register you'll find in the SDM is the "Interrupt Control Register".  This thing is the LVT Timer Initial Count, which doesn't seem to have a standard acronym.

On the subject of naming, and unrelated to this patch: we need to kill "loapic" dead.  That's a Zephyrism that no one else  understands.  The Intel term is just "APIC", or "Local APIC" if you absolutely have to disambiguate (but you never do, becuase the IO-APIC does a totally different job).  Linux uses "lapic", so I could see that.  But this name is weird.

Comment (andyross) [reply drivers/timer/apic_timer.c]: More meaty criticism: would be better to cache ICR rather than read it back from the hardware every time.   You're locked anyway, so it can only be a win.  That's what other drivers do with e.g. "last_load".

File: drivers/timer/apic_timer.c [hunk 2]
```diff
@@ -0,0 +1,378 @@
...
+	val &= ~LVT_MODE_MASK;
+	val |= LVT_MODE;
+	x86_write_loapic(LOAPIC_TIMER, val);
+
+	/* 3. wire up interrupt (this will configure remaining LVT bits) */
+
+	IRQ_CONNECT(CONFIG_APIC_TIMER_IRQ,
+		CONFIG_APIC_TIMER_IRQ_PRIORITY,
+		isr, 0, 0);
+	irq_enable(CONFIG_APIC_TIMER_IRQ);
```
Comment (andyross) [inline drivers/timer/apic_timer.c]: Put the enable at the end.  You don't know what's in the ICR yet so can't predict when the next interrupt will arrive.

File: drivers/timer/apic_timer.c [hunk 3]
```diff
@@ -0,0 +1,378 @@
...
+
+	return 0;
+}
+
+#ifdef CONFIG_TICKLESS_KERNEL
+
+/*
+ * Based on my understanding of the contract described in
+ * include/drivers/system_timer.h, this function acts as follows:
+ *
```
Comment (andyross) [inline drivers/timer/apic_timer.c]: Better to update the contract in include/drivers/system_timer.h then than repeat it here, no? :)

File: drivers/timer/apic_timer.c [hunk 4]
```diff
@@ -0,0 +1,378 @@
...
+ * 1. n <= 0
+ *
+ *     These are treated the same as a call to n == 1, that
+ *     is, announce at the next tick boundary (see 3).
+ *
+ * 2. (a) n == K_FOREVER or
+ *    (b) n > MAX_TICKS (which includes n == INT_MAX)
+ *
```
Comment (andyross) [inline drivers/timer/apic_timer.c]: MAX_TICKS in the other drivers is a precision issue.  If the hardware can't handle the requested timeout it waits for as long as it can.  It's not part of the API per se.  The kernel is prepared to take an announce call at any time (as long as it doesn't lie, of course).

File: drivers/timer/apic_timer.c [hunk 5]
```diff
@@ -0,0 +1,378 @@
...
+	u32_t icr;
+	u32_t ticks;
+
+	k_spinlock_key_t key = k_spin_lock(&lock);
+	ccr = x86_read_loapic(LOAPIC_TIMER_CCR);
+	icr = x86_read_loapic(LOAPIC_TIMER_ICR);
+	ticks = total_cycles - last_announcement;
+	ticks += icr - ccr;
+	ticks /= CYCLES_PER_TICK;
+	k_spin_unlock(&lock, key);
```
Comment (andyross) [inline drivers/timer/apic_timer.c]: Move the last two lines out of the lock, they depend only on local state.

File: drivers/timer/apic_timer.c [hunk 6]
```diff
@@ -0,0 +1,378 @@
...
+
+u32_t z_clock_elapsed(void)
+{
+	u32_t ccr;
+	u32_t icr;
+	u32_t ticks;
+
+	k_spinlock_key_t key = k_spin_lock(&lock);
+	ccr = x86_read_loapic(LOAPIC_TIMER_CCR);
+	icr = x86_read_loapic(LOAPIC_TIMER_ICR);
```
Comment (andyross) [inline drivers/timer/apic_timer.c]: This pattern appears a lot.  Probably worth defining something like:

```c
u32_t apic_cyc_elapsed()
{
    return x86_read_loapic(LOAPIC_TIMER_CCR) - x86_read_loapic(LOAPIC_TIMER_ICR);
}
```

File: drivers/timer/apic_timer.c [hunk 7]
```diff
@@ -0,0 +1,378 @@
...
+	u32_t cycles;
+	s32_t ticks;
+
+	k_spinlock_key_t key = k_spin_lock(&lock);
+
+	/*
+	 * If we get here and the CCR isn't zero, then this interrupt is
+	 * stale: it was queued while z_clock_set_timeout() was setting
+	 * a new counter. Just ignore it. See above for more info.
+	 */
```
Comment (andyross) [inline drivers/timer/apic_timer.c]: Trying to think of a way this could mess you up... can't, but still sounds scary.

File: drivers/timer/apic_timer.c [hunk 8]
```diff
@@ -0,0 +1,378 @@
...
+	 * counted down. Luckily this situation is easy to detect, which is
+	 * why the ISR actually checks to be sure the CCR is 0 before acting.
+	 */
+
+	k_spinlock_key_t key = k_spin_lock(&lock);
+
+	icr = x86_read_loapic(LOAPIC_TIMER_ICR);
+	ccr = x86_read_loapic(LOAPIC_TIMER_CCR);
+	total_cycles += (icr - ccr);
+	partial_cycles = CYCLES_PER_TICK - (total_cycles % CYCLES_PER_TICK);
```
Comment (andyross) [inline drivers/timer/apic_timer.c]: FWIW: the complexity involved in calculating "partial cycles" goes away entirely if you use an Invariant TSC as your time base (along the potential loss of precision when interrupts are late).  Just calculate your "desired TSC expiration" based on the last announcement time, subtract from the current value, and that's your new ICR.

**Review by andyross — APPROVED** [review]
Some notes.  Can't see anything wrong.  I will say this is awfully comment-heavy for such a short file. :)

File: drivers/timer/apic_timer.c [hunk 9]
```diff
@@ -0,0 +1,378 @@
...
+ * timer restart (ICR - CCR) yields the total number of cycles since power-on.
+ *
+ * While 'total_cycles' is not, in general, bound to have a value that is
+ * an integral multiple of CYCLES_PER_TICK, it is a matter of design that the
+ * timer will always be programmed such that 'total_cycles' plus the timer
+ * count will result in an interrupt at a tick boundary. That is, (ICR +
+ * 'total_cycles') is always an integral multiple of CYCLES_PER_TICK.
+ */
+
+static void isr(void *arg); /* I love forward declarations in the morning */
```
[the remark this answers is not in the document]
Comment (gnuless) [reply drivers/timer/apic_timer.c]: Since it bothers you so, I will re-order the file so this is unnecessary. :)

File: drivers/timer/apic_timer.c (hunk 1 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: That's an excellent point.  I will do that.

File: drivers/timer/apic_timer.c (hunk 2 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: _Ackshually_.... the ordering here was deliberate.  I seem to recall that writing the initial count before enabling the interrupt in the LVT would result in some buggy APICs never starting the countdown... but I can't find the reference.

I initially thought an early interrupt wouldn't be a problem, but it would be (for starters, the `total_cycles` + ICR invariant is broken, and that's just the beginning).  I'll make the change, since my memory of buggy APICs might just be wildly out-of-date or my brain malfunctioning due to age..

File: drivers/timer/apic_timer.c (hunk 1 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: And for the record, I didn't make any of `LOAPIC` or `ICR` here, these were pre-existing.  I agree that they're not the best choices.  I'll make a mental note to fix them after we retire the legacy local APIC timer driver.

File: drivers/timer/apic_timer.c (hunk 4 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: Right, right. `MAX_TICKS` is my own maximum, so I suppose it's confusing that I am documenting here as part of the API...

File: drivers/timer/apic_timer.c (hunk 3 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: But that's _your_ documentation. :)

File: drivers/timer/apic_timer.c (hunk 5 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: Will do.

File: drivers/timer/apic_timer.c (hunk 7 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: It's bullet-proof :)

File: drivers/timer/apic_timer.c (hunk 8 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: The driver is written to be useful on systems without a suitable TSC... I don't know if it's worth starting the special-case spaghetti here, but point taken.  If a usable TSC is assumed, the driver could certainly look a lot different.

**Comment by gnuless** [comment]
> Some notes. Can't see anything wrong. I will say this is awfully comment-heavy for such a short file. :)

Well, hopefully they were  _helpful_ comments (if not, I'll remove them). Until recently the existing local APIC driver had comments that were practically copy-and-paste from the data sheets.

File: drivers/timer/apic_timer.c (hunk 7 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: Also, one word: PendSV

File: drivers/timer/apic_timer.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (nashif) [reply drivers/timer/apic_timer.c]: and please avoid such unrelated comments :)

[the remark this answers is not in the document]
Comment (gnuless) [reply drivers/timer/apic_timer.c]: The forward declaration will go away when I re-order, and the hat-tip to Robert Duvall's iconic movie line will go with it.

File: drivers/timer/apic_timer.c (hunk 8 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: In fact, on that note, I'll assign myself a github to-do to write a TSC-only driver, then the TSC stuff can come out of here entirely. The idea in this driver is to assume the least common denominator, with a tiny concession to the existence of TSCs where the cost/benefit was high.

File: drivers/timer/apic_timer.c (hunk 2 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: On second thought, I'll just stop the timer before initializing it and the leave the ordering as-is. This way both problems (the early interrupt and the possible buggy APICs) are addressed.

**Comment by gnuless** [comment]
Force push, took most of the advice from @andyross, fixed issues with warnings due to unused variables when not running tickless.

File: drivers/timer/apic_timer.c (hunk 2 above)
Comment (gnuless) [reply drivers/timer/apic_timer.c]: On third thought, you're right. I'll just move the enable. In the case of sloppy firmware/bootware that interrupt could be queued on the local APIC when we enable it, and that need not have anything at all to do with the timer...

**Comment by gnuless** [comment]
Force push: change ordering of irq_enable() as previously suggested by @andyross and add fix to test to account for new timer type (CONFIG_APIC_TIMER).

**Comment by pfalcon** [comment]
This driver is broken in the current master, see https://github.com/zephyrproject-rtos/zephyr/pull/17054#issuecomment-506425340
