### PR TITLE
net: http: service: check for uncompressed file correctly

### LINKED ISSUE #92917: Webserver does not find uncompressed files when compression is enabled
### Describe the bug

if we have `CONFIG_HTTP_SERVER_COMPRESSION=y`,
but for a specific file no compressed version is found in the filesystem,
instead for checking for e.g. `index.html`, we will be checking for the last checked compressed version, `index.html.zz`

### Suggested fix:
https://github.com/zephyrproject-rtos/zephyr/pull/92918/

### Steps to reproduce

1. Take any Zephyr device with filesystem and webserver. 
2. Make sure compression is enabled (`CONFIG_HTTP_SERVER_COMPRESSION=y`)
3. Place `index.html` in the filesystem
4. Read it out with the client supporting extensions, e.g. with any browser.
5. Observe File Not Found

### PR DESCRIPTION
**Pull request by AndreyDodonov-EH**
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/92917

Correct not resetting compression extension,
when checking for an uncompressed file,
in case if compression is enabled, but no compressed file found.

So  if we have `CONFIG_HTTP_SERVER_COMPRESSION=y`, but for a specific file no compressed version is found in the filesystem, instead for checking for e.g. `index.html`, we will be checking for the last checked compressed version, `index.html.zz`

This happens because extension is not cleared.
Correct that.

### CODE REVIEW

**Review by rlubos — DISMISSED** [review]

**Review by mrodgers-witekio — DISMISSED** [review]

File: subsys/net/lib/http/http_server_core.c [hunk 1]
```diff
@@ -847,6 +847,8 @@ int http_server_find_file(char *fname, size_t fname_size, size_t *file_size,
 			}
 		}
 	}
+	/* No compressed file found, try the original filename */
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_core.c]: Shouldn't this be placed inside previous block? No need to do this if compression is not enabled.

Comment (mrodgers-witekio) [reply subsys/net/lib/http/http_server_core.c]: Now that you mention it, the `len = strlen(fname)` above the block could also be skipped if compression is not enabled...

Comment (AndreyDodonov-EH) [reply subsys/net/lib/http/http_server_core.c]: Good point, I have shifted it one line above.

**Review by rlubos — DISMISSED** [review]

**Review by mrodgers-witekio — DISMISSED** [review]

File: subsys/net/lib/http/http_server_core.c (hunk 1 above)
Comment (AndreyDodonov-EH) [reply subsys/net/lib/http/http_server_core.c]: @mrodgers-witekio  should I also move `size_t len;` inside?
I personally prefer to keep things scoped, but I think Zephyr's convention is to declare local variables at the beginning of the function

Comment (mrodgers-witekio) [reply subsys/net/lib/http/http_server_core.c]: I think the PR is fine as it is - the `strlen` outside the block was there already, and is optimised out by the compiler anyway (I just built the sample app without compression enabled and took a quick look at the disassembly)

But if you want to clean this up, I would probably lean towards declaring `len` inside the block too unless Robert/Jukka disagree - there are already other instances in the same file where it's done this way, e.g. see line 170

**Review by mrodgers-witekio — DISMISSED** [review]

File: subsys/net/lib/http/http_server_core.c (hunk 1 above)
Comment (AndreyDodonov-EH) [reply subsys/net/lib/http/http_server_core.c]: @mrodgers-witekio 
I agree, it's not that important anyway, because of compiler optimizations. 
It's just that people will receive warning of unused variable with linters (and some compilers) in case `CONFIG_HTTP_SERVER_COMPRESSION=n`, that was my reasoning

**Review by rlubos — DISMISSED** [review]

**Review by jukkar — APPROVED** [review]

**Review by mrodgers-witekio — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by tpambor — APPROVED** [review]

**Comment by tpambor** [comment]
Could we assign this bugfix to the 4.2.0 release? @rlubos @jukkar
