### PR TITLE
drivers: display: mcux_elcdif: Optional start on init

### LINKED ISSUE #94509: MIMXRT1170_EVKB screen rk055hdmipi4ma0 stopped working
### Describe the bug

The screen RK055HDMIPI4MA0 stopped working on the RT1170 when running the latest main branch. The display is completely dark with no signs of activity.

### Regression

- [x] This is a regression.

### Steps to reproduce

west build -p -b mimxrt1170_evk@B/mimxrt1176/cm7 samples/drivers/display -DSHIELD='rk055hdmipi4ma0'

### Relevant log output

```shell
There is nothing on the output.
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pdgendt**
After 8495e307266f87132a123535fea9b21e37d18bc4 some display controller drivers failed to start. Make the start optional and enabled by default if there are frame buffers allocated by the driver.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/94509

### CODE REVIEW

File: drivers/display/Kconfig.mcux_elcdif [hunk 1]
```diff
@@ -36,6 +36,13 @@ config MCUX_ELCDIF_FB_SIZE
 	  4-bytes pixel format, e.g. ARGB8888. Applications should change this value
 	  according to the actual used resolution and format to optimize the heap size.
 
+config MCUX_ELCDIF_START_ON_INIT
+	bool "Start the ELCDIF display driver during initialization"
+	default y if MCUX_ELCDIF_FB_NUM != 0
```
Comment (trunghieulenxp) [inline drivers/display/Kconfig.mcux_elcdif:41]: Why is the default Y setting needed when MCU_ELCDIF_FB_NUM is not equal to 0? I think this option should be enabled by default, regardless of the frame buffer number.

File: drivers/display/display_mcux_elcdif.c [hunk 2]
```diff
@@ -373,6 +377,9 @@ static int mcux_elcdif_init(const struct device *dev)
 #endif
 
 	ELCDIF_RgbModeInit(config->base, &dev_data->rgb_mode);
+#ifdef CONFIG_MCUX_ELCDIF_START_ON_INIT
```
Comment (trunghieulenxp) [inline drivers/display/display_mcux_elcdif.c:381]: AFAIK, there's no other start mode besides the start on init. Do you know of any other usecases for this ?

**Review by trunghieulenxp — CHANGES_REQUESTED** [review]

File: drivers/display/display_mcux_elcdif.c (hunk 2 above)
Comment (pdgendt) [reply drivers/display/display_mcux_elcdif.c:381]: That was the exact problem I tried to solve, if there are no framebuffers allocated in the driver, starting the ELCDIF interface would output rubbish data until the first `display_write` call.

Comment (trunghieulenxp) [reply drivers/display/display_mcux_elcdif.c:381]: I don't think start on init or start in write will resolve the issue of displaying garbage data. The garbage appears when the ELCDIF hardware pointer is not yet pointing to a valid address. So, in the case CONFIG_MCUX_ELCDIF_START_ON_INIT=y, I think you should set the hardware address before starting:
`
**ELCDIF_SetNextBufferAddr(config->base, dev_data->active_fb);**

ELCDIF_RgbModeStart(config->base);
`
Otherwise, I don't find any other solution for the case when CONFIG_MCUX_ELCDIF_FB_NUM == 0 for now.

Comment (pdgendt) [reply drivers/display/display_mcux_elcdif.c:381]: I've set the `bufferAddr` to the first frame buffer (if available) which will now be correctly set in `ELCDIF_RgbModeInit`.

**Review by JarmouniA — APPROVED** [review]

File: drivers/display/display_mcux_elcdif.c (hunk 2 above)
Comment (trunghieulenxp) [reply drivers/display/display_mcux_elcdif.c:381]: Thanks, this works well for cases where at least one frame buffer is available. However, the scenario where MCUX_ELCDIF_START_ON_INIT=n and MCUX_ELCDIF_FB_NUM=0 remains unresolved. This configuration can break the entire Zephyr driver initialization if someone manually sets these options.

I suggest we avoid exposing the configuration MCUX_ELCDIF_START_ON_INIT to users for now. We can accept that the ELCDIF may display garbage data when no framebuffer is present, as a temporary compromise.

Comment (pdgendt) [reply drivers/display/display_mcux_elcdif.c:381]: Can you clarify how this breaks the entire Zephyr driver initialization? This is the scenario I'm trying to use, starting to run the ELCDIF driver on the first `display_write` where the buffers are provided by LVGL.

Comment (trunghieulenxp) [reply drivers/display/display_mcux_elcdif.c:381]: As I mentioned in issue [#94509](https://github.com/zephyrproject-rtos/zephyr/issues/94509), on RT1170 platform, mcux_elcdif_init is called first, followed by the hx8394_init driver initialization.

I have test your patch, if the function
` ELCDIF_RgbModeStart(config->base);`
is not called within
`static int mcux_elcdif_init(const struct device *dev)`,
then the function
`static int hx8394_init(const struct device *dev)`
will be blocked. As a result, the entire driver initialization process in Zephyr will be halted.

This is the reason why, the function 
` ELCDIF_RgbModeStart(config->base);`
must be called in
`static int mcux_elcdif_init(const struct device *dev)`
unconditionally.

Thanks.

Comment (JarmouniA) [reply drivers/display/display_mcux_elcdif.c:381]: > the function `hx8394_init()` will be blocked

Why is that? What does `ELCDIF_RgbModeStart` do under the hood?

Comment (pdgendt) [reply drivers/display/display_mcux_elcdif.c:381]: > This is the reason why, the function ` ELCDIF_RgbModeStart(config->base);` must be called in `static int mcux_elcdif_init(const struct device *dev)` unconditionally.

I get that this is a limitation when a board has both the drivers you specify, though this is not the default configuration for the i.MX RT1170 EVK board.

It is, however, an improvement for other boards or combination of drivers, so I would argue that we **can** make it conditional.

Comment (trunghieulenxp) [reply drivers/display/display_mcux_elcdif.c:381]: Thanks for your argument. I’ve checked and confirmed that the hardware topology can vary between boards, so this patch looks good to me now.

**Review by trunghieulenxp — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
