### PR TITLE
drivers: flash: simulator: fix address resolution

### LINKED ISSUE #79082: drivers: flash: simulator: fix address resolution
**Describe the bug**

The flash simulator currently treats relative flash offsets as if they were absolute addresses. This didn't have an impact so far, because the base address is always zero when the flash simulator is used in practice.

Experimenting with non-zero offsets for the memory region revealed the error.

As I'm intending to support non-zero offsets for the flash simulator in a future PR, this bug should be fixed first.

PR with a fix follows.

**To Reproduce**

According to https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/dts/bindings/mtd/fixed-partitions.yaml#L93

A fixed flash partition's `reg` address'...

> [...] is the offset of the flash partition **relative to the base address** of the parent memory.

In https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/subsys/storage/flash_map/flash_map_default.c#L25

This _relative_ address of the partition is assigned to the `fa_off` member of `struct flash_area`.

The relative address is then propagated to the file system. In the case of the NVS settings backend and NVS, this is for example being done here:

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/subsys/settings/src/settings_nvs.c#L424

This offset is the base address for writes to the flash drivers, see e.g.

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/subsys/fs/nvs/nvs.c#L116

Which again is propagated verbatim to the flash driver:

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/include/zephyr/drivers/flash.h#L274

In the case of the flash simulator, however, the base address of the flash memory region is being **deduced** from the offset as if the offset was an **absolute** address, see for example here

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/drivers/flash/flash_simulator.c#L241

and here

https://github.com/zephyrproject-rtos/zephyr/blob/24851026064d7912a9f91031e95ed71445842fd9/drivers/flash/flash_simulator.c#L51

**Expected behavior**

The flash simulator should treat relative addresses as relative to the base address rather than as absolute addresses.

**Impact**

Illegal addresses are being accessed (page fault, mem fault) with a non-zero flash memory-region base address.

**Logs and console output**

n/a (processor halts)

**Environment (please complete the following information):**

all

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by ghost**
The flash simulator assumes that flash is being addressed with absolute addresses by clients. But this is not the case. Given addresses are relative to the flash base address.

The existing code only worked because the base address was always zero. Testing with non-zero base addresses caused a mem fault/page fault.

(Reproducible e.g. when using the NVS settings subsystem on QEMU x86 with a non-zero base address in the soc-nv-flash node.)

Fixes #79082

### CODE REVIEW

File: drivers/flash/flash_simulator.c [hunk 1]
```diff
@@ -48,7 +48,7 @@
 #error "Erase unit must be a multiple of program unit"
 #endif
 
-#define MOCK_FLASH(addr) (mock_flash + (addr) - FLASH_SIMULATOR_BASE_OFFSET)
+#define MOCK_FLASH(rel_addr) (mock_flash + (rel_addr))
```
Comment (jeppenodgaard) [inline drivers/flash/flash_simulator.c:51]: I am not sure `rel` means. It should probably be a full word.

Comment (fgrandel) [reply drivers/flash/flash_simulator.c:51]: @jeppenodgaard 

You're right. This is not a good name.

Is it ok, if I just name this to `offset` which is the same name that is used elswhere in the file for the same thing?

File: drivers/flash/flash_simulator.c [hunk 2]
```diff
@@ -174,9 +174,8 @@ static int flash_range_is_valid(const struct device *dev, off_t offset,
 				size_t len)
 {
 	ARG_UNUSED(dev);
-	if ((offset + len > FLASH_SIMULATOR_FLASH_SIZE +
-			    FLASH_SIMULATOR_BASE_OFFSET) ||
-	    (offset < FLASH_SIMULATOR_BASE_OFFSET)) {
+
+	if ((offset + len > FLASH_SIMULATOR_FLASH_SIZE) || (offset < 0)) {
```
Comment (de-nordic) [inline drivers/flash/flash_simulator.c:178]: Since you are fixing this, can we fix the somehow absurd check for correctness of `offset` _after_ doing calculations with it? I know that it was here before...
Also the more correct approach would be to do:
```
(offset < 0 || offset >= FLASH_SIMULATOR_FLASH_SIZE || (FLASH_SIMULATOR_FLASH_SIZE - offset) < size)
```
this should let us avoid all overflows the addition could cause.

Comment (fgrandel) [reply drivers/flash/flash_simulator.c]: Good catch! Fixed. BTW: The reason, why I'm fixing this is #79130.

**Review by cfriedt — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
Thanks for fixing.
