### PR TITLE
drivers: flash: stm32_qspi: Fix configuration & erase in dual-flash mode

### LINKED ISSUE #93153: stm32h747 dual quad-flash reading failure
### Describe the bug

stm32h747i_disco // m7 reading the dual quad flash is not correct
west build p -b stm32h747i_disco//m7 samples/drivers/spi_flash

### Regression

- [x] This is a regression.

### Steps to reproduce
release: Zephyr 4.2.0-rc3

### Relevant log output

```shell
spi-nor-flash-1@0 SPI flash testing
==========================

Perform test on single sector
Test 1: Flash erase
Flash erase failed at offset 0xff000 got 0x88888888

Perform test on multiple consecutive sectors
Test 1: Flash erase
Flash erase failed at offset 0xff000 got 0x88888888
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

Expected output (whater the CONFIG_STM32_MEMMAP is)
```

qspi-nor-flash-1@0 SPI flash testing
==========================

Perform test on single sector
Test 1: Flash erase
Flash erase succeeded!

Test 2: Flash write
Attempting to write 4 bytes
Data read matches data written. Good!!

Perform test on multiple consecutive sectors
Test 1: Flash erase
Flash erase succeeded!

Test 2: Flash write
Attempting to write 4 bytes at offset 0xff000
Data read matches data written. Good!!
Attempting to write 4 bytes at offset 0x100000
Data read matches data written. Good!!
```

### PR DESCRIPTION
**Pull request by taltenbach**
When dual-flash mode is enabled, two identical flash memories are connected to the QUADSPI peripheral and are accessed in parallel. This means in particular that:
* Both flash memories must be configured the same way, so any write performed to the status register of a given flash memory must also be performed for the other flash memory.
* When performing a program or erase operation, the flash driver must wait for the operation to complete on both flash memories by polling both status registers.
* Page and erase size are doubled.

That was not properly handled by the QSPI flash driver, which might lead to errors when reading, erasing or programming data. In particular, this fixes #93153.

The changes were tested on a STM32H747I-DISCO board, in both single- and dual-flash configuration. It was ensured that the `drivers/spi_flash` sample runs without errors and that the status register can be properly read/written.

### CODE REVIEW

**Comment by taltenbach** [comment]
cc @erwango @FRASTM

File: drivers/flash/flash_stm32_qspi.c [hunk 1]
```diff
@@ -580,20 +660,96 @@ static int flash_stm32_qspi_read(const struct device *dev, off_t addr,
...
 	int ret;
 
 	QSPI_CommandTypeDef cmd = {
-		.Instruction = SPI_NOR_CMD_RDSR,
+		.Instruction = SPI_NOR_CMD_WRSR,
 		.InstructionMode = QSPI_INSTRUCTION_1_LINE,
 		.DataMode = QSPI_DATA_1_LINE,
 	};
 
+	if (reg_num == 1) {
```
Comment (FRASTM) [inline drivers/flash/flash_stm32_qspi.c]: if (reg_num == 1) {
and next `if ...`

```suggestion
	if (reg_num == 1U) {
```

**Review by FRASTM — COMMENTED** [review]
LGTM. Thanks for fixing
The samples/drivers/spi_flash passed in indirect or memory Mapped mode on a dual quad-SPI flash stm32 target

**Comment by taltenbach** [comment]
@FRASTM Thanks for reviewing and testing! I applied your suggestion :)

File: drivers/flash/flash_stm32_qspi.c [hunk 2]
```diff
@@ -65,6 +65,86 @@ LOG_MODULE_REGISTER(flash_stm32_qspi, CONFIG_FLASH_LOG_LEVEL);
...
+ *
+ * In dual-flash mode, this routine returns true if and only if the bit is set for both flash
+ * memories.
+ */
+static inline bool flash_reg_is_set_for_all(struct flash_reg *reg, uint8_t bit)
+{
+	bool is_set = reg->flash0_val & bit;
+
+#if STM32_QSPI_DOUBLE_FLASH
+	is_set = is_set && (reg->flash1_val & bit);
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_qspi.c]: For coding style, would prefer:
```suggestion
	bool is_set = (reg->flash0_val & bit) != 0U;

#if STM32_QSPI_DOUBLE_FLASH
	is_set = is_set && ((reg->flash1_val & bit) != 0U);

File: drivers/flash/flash_stm32_qspi.c [hunk 3]
```diff
@@ -65,6 +65,86 @@ LOG_MODULE_REGISTER(flash_stm32_qspi, CONFIG_FLASH_LOG_LEVEL);
...
+ * Gets the raw representation of a flash register, as a uint16_t value where the lower byte is the
+ * value for the first flash memory and the upper byte is the value of the second flash memory, if
+ * any.
+ */
+static inline uint16_t flash_reg_to_raw(const struct flash_reg *reg)
+{
+	uint16_t raw = reg->flash0_val;
+
+#if STM32_QSPI_DOUBLE_FLASH
+	raw |= (reg->flash1_val << 8);
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_qspi.c]: Could remove parentheses.

File: drivers/flash/flash_stm32_qspi.c [hunk 4]
```diff
@@ -65,6 +65,86 @@ LOG_MODULE_REGISTER(flash_stm32_qspi, CONFIG_FLASH_LOG_LEVEL);
...
+ *
+ * In dual-flash mode, this routine returns true if and only if the bit is clear for both flash
+ * memories.
+ */
+static inline bool flash_reg_is_clear_for_all(struct flash_reg *reg, uint8_t bit)
+{
+	bool is_clear = !(reg->flash0_val & bit);
+
+#if STM32_QSPI_DOUBLE_FLASH
+	is_clear = is_clear && !(reg->flash1_val & bit);
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_qspi.c]: Ditto on coding style:
```suggestion
	bool is_clear = (reg->flash0_val & bit) == 0U;

#if STM32_QSPI_DOUBLE_FLASH
	is_clear = is_clear && ((reg->flash1_val & bit) == 0U);

**Review by etienne-lms — COMMENTED** [review]
LGTM with a few coding style comments.

File: drivers/flash/flash_stm32_qspi.c [hunk 5]
```diff
@@ -65,6 +65,86 @@ LOG_MODULE_REGISTER(flash_stm32_qspi, CONFIG_FLASH_LOG_LEVEL);
...
+	return is_set;
+}
+
+/*
+ * Checks if a bit is clear in a flash register.
+ *
+ * In dual-flash mode, this routine returns true if and only if the bit is clear for both flash
+ * memories.
+ */
+static inline bool flash_reg_is_clear_for_all(struct flash_reg *reg, uint8_t bit)
```
Comment (GeorgeCGV) [inline drivers/flash/flash_stm32_qspi.c]: Nitpick: would suggest renaming `bit` to `bitmask`  for better accuracy. 
In `spi_nor.h`, the status register "bits" are defined as bitmasks, not as individual bit positions.

For bit checks, there is `IS_BIT_SET` in `util_macro.h`.

Comment (taltenbach) [reply drivers/flash/flash_stm32_qspi.c]: Indeed, `bitmask` makes more sense

**Comment by taltenbach** [comment]
@etienne-lms @GeorgeCGV Suggested changes applied

File: drivers/flash/flash_stm32_qspi.c [hunk 6]
```diff
@@ -1251,8 +1327,8 @@ static int qspi_program_quad_io(const struct device *dev)
 		return ret;
 	}
 
-	if ((reg & qe_bit) == 0U) {
-		LOG_ERR("Status Register %u [0x%02x] not set", qe_reg_num, reg);
+	if (!flash_reg_is_set_for_all(&reg, qe_bit)) {
+		LOG_ERR("Status Register %u [0x%02x] not set", qe_reg_num, flash_reg_to_raw(&reg));
```
Comment (GeorgeCGV) [inline drivers/flash/flash_stm32_qspi.c]: The status register log output with format `%02x` will crop `uint16_t` to `uint8_t` (_for `STM32_QSPI_DOUBLE_FLASH`_); is that desired?

Comment (taltenbach) [reply drivers/flash/flash_stm32_qspi.c]: Indeed, fixed!

**Review by etienne-lms — DISMISSED** [review]

**Review by GeorgeCGV — DISMISSED** [review]

File: drivers/flash/flash_stm32_qspi.c [hunk 7]
```diff
@@ -1251,8 +1327,8 @@ static int qspi_program_quad_io(const struct device *dev)
 		return ret;
 	}
 
-	if ((reg & qe_bit) == 0U) {
-		LOG_ERR("Status Register %u [0x%02x] not set", qe_reg_num, reg);
+	if (!flash_reg_is_set_for_all(&reg, qe_bit)) {
+		LOG_ERR("Status Register %u [0x%04x] not set", qe_reg_num, flash_reg_to_raw(&reg));
```
Comment (GeorgeCGV) [inline drivers/flash/flash_stm32_qspi.c]: Nit: might confuse people without dual flash. Maybe worth having different formats for single and dual, something like:
```c
	LOG_ERR("Status Register %u "
#if STM32_QSPI_DOUBLE_FLASH
		"[0x%04x]"
#else
		"[0x%02x]"
#endif
		" not set", qe_reg_num, flash_reg_to_raw(&reg));
```

Comment (taltenbach) [reply drivers/flash/flash_stm32_qspi.c]: Makes sense! I created a macro for the format

**Review by JarmouniA — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Review by GeorgeCGV — APPROVED** [review]

**Comment by erwango** [comment]
Removing the backport tag. Eventhough it has been carefully and reviewed, I prefer to remain on the safe side and avoid disturbing v4.2.0 with this for now.
I'd be open to backport after a while, once we'll have evidence it has been used widely w/o trouble.

**Review by erwango — APPROVED** [review]
