### PR TITLE
boards: nxp: frdm_mcxn947: enable GPIO in all modes

### LINKED ISSUE #88521: NXP MCXN947 CPU1 cannot control GPIO
Apps executing on CPU1 cannot write to the GPIO registers.  The issue is seen on the FRDM-MCXN947 board.  When building the blinky sample for the CPU1 target, the app executes and prints messages about toggling the LED, but the LED does not toggle.  And the GPIO registers do not update.

The problem is the security settings of this GPIO peripheral.  By default, TrustZone non-secure access of the GPIO registers is prevented.  The registers PCNS, PCNP, ICNS, and PCNS control these accesses, and should be enabled by CPU0 in secure mode.

This does not appear to be a regression issue.  https://github.com/zephyrproject-rtos/zephyr/pull/81882 added CPU1 support on this platform.  But reverting to 64585b74445b9e10352dc3fa368105ba75a451bd has the same issue.

### PR DESCRIPTION
**Pull request by DerekSnell**
For CPU1 access, enable GPIO access in non-secure and non-privilege modes.

Resolves #88521.

This update enables the blinky sample to run on CPU1 using the following commands:
```
west build -b frdm_mcxn947//cpu1 samples/basic/blinky -d blinky_cpu1 -p -- -DCONFIG_SECOND_CORE_MCUX=y
west flash -d blinky_cpu1
west build -b frdm_mcxn947//cpu0 samples/hello_world/  -d hello_cpu0_loader -p -- -DCONFIG_SECOND_CORE_MCUX=y
west flash -d hello_cpu0_loader
```

### CODE REVIEW

**Review by alxrey — APPROVED** [review]

**Review by butok — DISMISSED** [review]

File: boards/nxp/frdm_mcxn947/board.c [hunk 1]
```diff
@@ -84,6 +84,15 @@ __ramfunc static void enable_cache64(void)
 }
 #endif
 
+static void unsecure_gpio(GPIO_Type * base)
+{
+	/* Enables CPU1 to access GPIO registers */
+	base->PCNS = 0xFFFFFFFFU; /* Pins can be configured in non-secure access */
+	base->PCNP = 0xFFFFFFFFU; /* Pins can be configured in non-privilege access */
+	base->ICNS = 0xFFFFFFFFU; /* Interrupts can be configured in non-secure access */
+	base->PCNS = 0xFFFFFFFFU; /* Interrupts can be configured in non-privilege access */
```
Comment (decsny) [inline boards/nxp/frdm_mcxn947/board.c:93]: this is the same register as the first line, is it intentional?

Comment (DerekSnell) [reply boards/nxp/frdm_mcxn947/board.c]: Good catch @decsny .  No that was my error, not intentional.  And while confirming the proper register name, I realized I was setting many reserved bits.  Now updated to fix this.  Thank you

File: boards/nxp/frdm_mcxn947/board.c [hunk 2]
```diff
@@ -84,6 +84,19 @@ __ramfunc static void enable_cache64(void)
...
+	 * Pins and interrupts can be configured in non-secure access
+	 */
+	base->PCNS = 0xFFFFFFFFU;
+	base->ICNS = GPIO_ICNS_NSE1_MASK | GPIO_ICNS_NSE0_MASK;
+
+	/* Pins and interrupts can be configured in non-privilege access */
+	base->PCNP = 0xFFFFFFFFU;
+	base->ICNP = GPIO_ICNP_NPE1_MASK | GPIO_ICNP_NPE0_MASK;
+}
+
```
Comment (decsny) [inline boards/nxp/frdm_mcxn947/board.c:99]: is there a reason this code shouldn't go in the driver?

File: boards/nxp/frdm_mcxn947/board.c [hunk 3]
```diff
@@ -177,22 +190,27 @@ void board_early_init_hook(void)
...
 #endif
 
 #if DT_NODE_HAS_STATUS_OKAY(DT_NODELABEL(gpio3))
 	CLOCK_EnableClock(kCLOCK_Gpio3);
+	unsecure_gpio(GPIO3);
 #endif
 
 #if DT_NODE_HAS_STATUS_OKAY(DT_NODELABEL(gpio4))
 	CLOCK_EnableClock(kCLOCK_Gpio4);
+	unsecure_gpio(GPIO4);
```
Comment (decsny) [inline boards/nxp/frdm_mcxn947/board.c:213]: calling this routine for every instance makes me think it should go in a driver init routine

File: boards/nxp/frdm_mcxn947/board.c [hunk 4]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright 2024  NXP
+ * Copyright 2025 NXP
```
Comment (decsny) [inline boards/nxp/frdm_mcxn947/board.c:2]: should not remove 2024, ie 2024-2025

**Review by decsny — CHANGES_REQUESTED** [review]

File: boards/nxp/frdm_mcxn947/board.c (hunk 4 above)
Comment (DerekSnell) [reply boards/nxp/frdm_mcxn947/board.c]: oops, dumb mistake.  Updated now, thanks for catching it @decsny

File: boards/nxp/frdm_mcxn947/board.c (hunk 3 above)
Comment (DerekSnell) [reply boards/nxp/frdm_mcxn947/board.c:213]: that is another option, but not one I plan to spend time on right now.

**Review by decsny — APPROVED** [review]

File: boards/nxp/frdm_mcxn947/board.c (hunk 3 above)
Comment (alxrey) [reply boards/nxp/frdm_mcxn947/board.c:213]: I'm the one who originally reported this issue (on Discord).
If you would like, I can help implement the change into the driver. What would be the best way to do it? Two functions with a `mask` parameter for pin control and two for interrupt control, and adapt the API accordingly?

Comment (decsny) [reply boards/nxp/frdm_mcxn947/board.c:213]: it seems like the code in the function being added here can just be added to the driver init routine

Comment (alxrey) [reply boards/nxp/frdm_mcxn947/board.c:213]: Oh yes if we want the pins to be configurable for non-secure/non-privilege access all the time.
But the best would be to make it dynamically customizable, I guess.

**Review by dleach02 — APPROVED** [review]

**Comment by ubieda** [comment]
Seems like with this patch now GPIOs are not accessible from cpu0? I bisected the GPIO input functionality with:
``` console
west build -b frdm_mcxn947/mcxn947/cpu0 samples/basic/button/
```
@DerekSnell my question is: How can we configure the build so that by default we keep the old behavior GPIOs are routed through cpu0 (keep the old behavior for users not using cpu1)?
