### PR TITLE
drivers: timer: nrf_rtc_timer: Implement stop function

### LINKED ISSUE #52667: nrf_rtc_timer: Booting application with zephyr < 3.0.0 from mcuboot with zephyr >= 3.0.0
**Describe the bug**
Due to change of the NRF RTC timer in zephyr v3.0.0 which enable the overflow interrupt, MCUBoot will leave this interrupt enabled which is not handled by the driver for earlier version. In practice that mean that in such use case, after ~8.5 minutes of running the interrupt will be triggered indefinitely leading to starvation of all threads.

**To Reproduce**
On NRF an platform:
1. Build and program MCUBoot with zephyr >= v3.0.0
2. Build and program an application with zephyr < v3.0.0
3. Wait 8 minutes and 30s

**Impact**
The impact of that issue is not that big since this configuration ("new" bootloader with "old" application) is probably not very common

### PR DESCRIPTION
**Pull request by nordicjm**
drivers: timer: nrf_rtc_timer: Implement stop function
    
    Implements functionality to stop the nRF RTC timer clock source.

Fixes #52667

### CODE REVIEW

**Comment by nordicjm** [comment]
CC @kurddt @rene-becker-setec

**Comment by kurddt** [comment]
I was wondering why this would solve the issue, so other might as well: The new implementation of `sys_clock_disable`  wil be called here: https://github.com/zephyrproject-rtos/mcuboot/blob/143485e35b8da7d234677d8920a28f5ea03f6d09/boot/zephyr/main.c#L194

File: drivers/timer/nrf_rtc_timer.c [hunk 1]
```diff
@@ -660,6 +660,23 @@ uint32_t sys_clock_cycle_get_32(void)
...
+{
+	uint32_t mask = NRF_RTC_INT_TICK_MASK     |
+			NRF_RTC_INT_OVERFLOW_MASK |
+			NRF_RTC_INT_COMPARE0_MASK |
+			NRF_RTC_INT_COMPARE1_MASK |
+			NRF_RTC_INT_COMPARE2_MASK |
+			NRF_RTC_INT_COMPARE3_MASK;
+
+	nrf_rtc_task_trigger(RTC, NRF_RTC_TASK_STOP);
+	nrf_rtc_task_trigger(RTC, NRF_RTC_TASK_CLEAR);
```
Comment (anangl) [inline drivers/timer/nrf_rtc_timer.c:673]: Is it actually needed to clear the counter?

File: drivers/timer/nrf_rtc_timer.c [hunk 2]
```diff
@@ -660,6 +660,23 @@ uint32_t sys_clock_cycle_get_32(void)
...
+	irq_disable(RTC_IRQn);
+	nrf_rtc_int_disable(RTC, mask);
+	nrf_rtc_event_disable(RTC, mask);
```
Comment (anangl) [inline drivers/timer/nrf_rtc_timer.c:676]: This could be extracted to a helper function called by both `sys_clock_disable()` and `sys_clock_driver_init()`.

File: doc/releases/release-notes-3.4.rst [hunk 3]
```diff
@@ -355,6 +355,9 @@ Trusted Firmware-M
 
 * Timer
 
+  * Support added for stopping Nordic nRF RTC timer clock source, which fixes
```
Comment (anangl) [inline doc/releases/release-notes-3.4.rst:358]: This "clock source" mentioned here and in the commit message might be a bit confusing as the LFCLK that drives the RTC is actually not stopped. Perhaps "system timer" would be more suitable.

File: drivers/timer/nrf_rtc_timer.c (hunk 1 above)
Comment (nordicjm) [reply drivers/timer/nrf_rtc_timer.c]: It is not, removed.

File: drivers/timer/nrf_rtc_timer.c (hunk 2 above)
Comment (nordicjm) [reply drivers/timer/nrf_rtc_timer.c]: Moved to separate function

File: doc/releases/release-notes-3.4.rst (hunk 3 above)
Comment (nordicjm) [reply doc/releases/release-notes-3.4.rst]: Changed text

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
