### PR TITLE
soc: nordic: dmm: Fix DMM_REG_ALIGN_SIZE macro when CONFIG_DCACHE=n

### LINKED ISSUE #80873: Compilation failure on nRF54H20 VPR with UART memory region
**Describe the bug**
Recently, the `uart_nrfx_uarte` driver adopted DMM and exposed a bug with one of the DMM macros. It may cause compilation to fail when building for a target with no data cache, such as the nRF54H20 PPR core.

**To Reproduce**
1. Create `samples/hello_world/app.overlay`:
```
&uart135 {
    memory-regions = <&cpuapp_dma_region>;
};
```
2. Run `west build -p samples/hello_world -b nrf54h20dk//cpuppr`

**Expected behavior**
Build success

**Impact**
Showstopper

**Logs and console output**
```
FAILED: zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_nrfx_uarte.c.obj
/home/gms/ncs/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-gcc -DKERNEL -DK_HEAP_MEM_POOL_SIZE=0 -DNRF54H20_XXAA -DNRF_PPR -DPICOLIBC_LONG_LONG_PRINTF_SCANF -D__LINUX_ERRNO_EXTENSIONS__ -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I/home/gms/ncs/zephyr/samples/hello_world/build/zephyr/include/generated/zephyr -I/home/gms/ncs/zephyr/include -I/home/gms/ncs/zephyr/samples/hello_world/build/zephyr/include/generated -I/home/gms/ncs/zephyr/soc/nordic -I/home/gms/ncs/zephyr/soc/common/riscv-privileged/. -I/home/gms/ncs/zephyr/soc/nordic/nrf54h/. -I/home/gms/ncs/zephyr/soc/nordic/nrf54h/gpd/include -I/home/gms/ncs/zephyr/soc/nordic/common/vpr/. -I/home/gms/ncs/zephyr/soc/nordic/common/. -I/home/gms/ncs/modules/hal/nordic/nrfx -I/home/gms/ncs/modules/hal/nordic/nrfx/drivers/include -I/home/gms/ncs/modules/hal/nordic/nrfx/mdk -I/home/gms/ncs/zephyr/modules/hal_nordic/nrfx/. -isystem /home/gms/ncs/zephyr/lib/libc/common/include -Wshadow -fno-strict-aliasing -Os -imacros /home/gms/ncs/zephyr/samples/hello_world/build/zephyr/include/generated/zephyr/autoconf.h -fno-printf-return-value -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mabi=ilp32e -march=rv32emc_zicsr --sysroot=/home/gms/ncs/zephyr-sdk-0.16.8/riscv64-zephyr-elf/riscv64-zephyr-elf -imacros /home/gms/ncs/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/home/gms/ncs/zephyr/samples/hello_world=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/gms/ncs/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/gms/ncs=WEST_TOPDIR -ffunction-sections -fdata-sections -specs=picolibc.specs -std=c99 -MD -MT zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_nrfx_uarte.c.obj -MF zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_nrfx_uarte.c.obj.d -o zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_nrfx_uarte.c.obj -c /home/gms/ncs/zephyr/drivers/serial/uart_nrfx_uarte.c
In file included from /home/gms/ncs/modules/hal/nordic/nrfx/drivers/nrfx_utils.h:37,
                 from /home/gms/ncs/modules/hal/nordic/nrfx/drivers/nrfx_common.h:44,
                 from /home/gms/ncs/modules/hal/nordic/nrfx/nrfx.h:38,
                 from /home/gms/ncs/modules/hal/nordic/nrfx/hal/nrf_uarte.h:37,
                 from /home/gms/ncs/zephyr/drivers/serial/uart_nrfx_uarte.c:15:
/home/gms/ncs/zephyr/soc/nordic/common/./dmm.h:37:42: error: 'CONFIG_DCACHE_LINE_SIZE' undeclared here (not in a function); did you mean 'CONFIG_TIMESLICE_SIZE'?
   37 |         (DMM_IS_REG_CACHEABLE(node_id) ? CONFIG_DCACHE_LINE_SIZE : sizeof(uint8_t))
```

**Environment:**

 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.8
 - Commit SHA or Version used: v4.0.0-rc2

### PR DESCRIPTION
**Pull request by 57300**
Make sure this expansion doesn't include `CONFIG_DCACHE_LINE_SIZE`, which would be undefined and produce a build error.

Fixes #80873

### CODE REVIEW

File: soc/nordic/common/dmm.h [hunk 1]
```diff
@@ -34,7 +34,9 @@ extern "C" {
  * Cache line alignment is required if region is cacheable and data cache is enabled.
  */
 #define DMM_REG_ALIGN_SIZE(node_id) \
-	(DMM_IS_REG_CACHEABLE(node_id) ? CONFIG_DCACHE_LINE_SIZE : sizeof(uint8_t))
+	COND_CODE_0(CONFIG_DCACHE,  \
```
Comment (nordic-krch) [inline soc/nordic/common/dmm.h:37]: i don't think that this will work. `CONFIG_DCACHE` or exists and is set to 1 or is not defined. `COND_CODE_0` will evaluate to first option only if `CONFIG_DCACHE` is defined as 0. Use `COND_CODE_1` and swap options.

Comment (57300) [reply soc/nordic/common/dmm.h]: Thanks, I keep forgetting this. Updated.

File: soc/nordic/common/dmm.h [hunk 2]
```diff
@@ -33,8 +33,10 @@ extern "C" {
 /* Determine required alignment of the data buffers in specified memory region.
  * Cache line alignment is required if region is cacheable and data cache is enabled.
  */
-#define DMM_REG_ALIGN_SIZE(node_id) \
-	(DMM_IS_REG_CACHEABLE(node_id) ? CONFIG_DCACHE_LINE_SIZE : sizeof(uint8_t))
+#define DMM_REG_ALIGN_SIZE(node_id)							\
+	COND_CODE_1(CONFIG_DCACHE,							\
+	   (DMM_IS_REG_CACHEABLE(node_id) ? CONFIG_DCACHE_LINE_SIZE : sizeof(uint8_t)),	\
```
Comment (anangl) [inline soc/nordic/common/dmm.h:38]: Missing one pair of parentheses. The outermost ones will be taken out by the `COND_CODE_1()` macro, so the result will be different than before and may potentially break some code.
```suggestion
	   ((DMM_IS_REG_CACHEABLE(node_id) ? CONFIG_DCACHE_LINE_SIZE : sizeof(uint8_t))),	\
```
But perhaps it will be cleaner and easier to handle `CONFIG_DCACHE` outside of the macro definition. Especially that `DMM_IS_REG_CACHEABLE()` needs to check for it as well. How about:
```
#ifdef CONFIG_DCACHE

/* Determine if memory region is cacheable. */
#define DMM_IS_REG_CACHEABLE(node_id)					     \
	COND_CODE_1(DT_NODE_HAS_PROP(node_id, zephyr_memory_attr),	     \
		((DT_PROP(node_id, zephyr_memory_attr) & DT_MEM_CACHEABLE)), \
		(0))

/* Determine required alignment of the data buffers in specified memory region.
 * Cache line alignment is required if region is cacheable and data cache is enabled.
 */
#define DMM_REG_ALIGN_SIZE(node_id) \
	(DMM_IS_REG_CACHEABLE(node_id) ? CONFIG_DCACHE_LINE_SIZE : sizeof(uint8_t))

#else
#define DMM_IS_REG_CACHEABLE(node_id) 0
#define DMM_REG_ALIGN_SIZE(node_id) sizeof(uint8_t)
#endif /* CONFIG_DCACHE */
```

Comment (57300) [reply soc/nordic/common/dmm.h]: Fair enough. Applied the long version.

**Review by anangl — APPROVED** [review]

File: soc/nordic/common/dmm.h [hunk 3]
```diff
@@ -23,19 +23,27 @@ extern "C" {
 
 /** @cond INTERNAL_HIDDEN */
 
+#ifdef CONFIG_DCACHE
+
 /* Determine if memory region is cacheable. */
-#define DMM_IS_REG_CACHEABLE(node_id)					 \
```
Comment (nordic-krch) [inline soc/nordic/common/dmm.h:27]: Was there any issues with that macro?

Comment (57300) [reply soc/nordic/common/dmm.h:27]: It was suggested by @anangl. Not interested in going back and forth on this, it's an urgent fix.

**Review by nordic-krch — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@57300 Can you please add an issue with details and link that issue to this PR. After RC2 only bug fixes with Github issue will be merged into the upcoming 4.0 release.

**Comment by 57300** [comment]
> @57300 Can you please add an issue with details and link that issue to this PR. After RC2 only bug fixes with Github issue will be merged into the upcoming 4.0 release.

@mmahadevan108 Yes, I added an issue link.
