### PR TITLE
Bluetooth: host: Save CCC data on pairing complete

### LINKED ISSUE #39989: Zephyr does not persist CCC data written before bonding when bonding has completed which leads to loss of subscriptions on device reset
**Describe the bug**

Zephyr is currently only persisting CCC data on a disconnect event.

Zephyr does not persist CCC data written before bonding when bonding has completed which leads to loss of subscriptions on device reset before a disconnect.

**To Reproduce**

1. BLE connect to a Zephyr device.
2. Subscribe to a characteristic.
3. Bond with the Zephyr device.
4. Reboot device without any disconnect event before the reboot.
5. See that the subscription to the characteristic is lost when booting has completed.

**Expected behavior**

The bluetooth spec version 5.2 section 3.3.3.3 says that:

The Client Characteristic Configuration descriptor value shall be persistent across connections for bonded devices.

So it is expected that the CCC data is persisted on bonding complete to ensure subscriptions are not lost.

**Impact**

This has the unfortunate effect that users who enable a new feature in their Zephyr device which results in an update of the GATT database, could have connected and bonded devices that are not given a service changed indication, to let them know that they need a new service discovery process, if the Zephyr device is rebooted without being disconnected first.

A more concrete example:

1. A cell phone is connecting and discovers services on a Zephyr device.
2. The cell phone subscribes immediately to the service changed characteristic.
3. The cell phone bonds with the Zephyr device.
4. The cell phone enables a new feature in the Zephyr device that results in an additional characteristic appearing in the GATT database.
5. The user reboots the zephyr device (so no BLE disconnect event).
6. The cell phone reconnects to the Zephyr device after the reboot
7. The cell phone does not get a service changed indication since the subscription was not persisted due to the reboot and no disconnect event.
8. The cell phone is unaware of the new characteristic.

iPhone 12 is known to subscribe before bonding is therefore among the devices that cause this problematic behavior in upgrade scenarios.

**Logs and console output**

None

**Environment (please complete the following information):**

 - OS: Zephyr version 2.7.0
 - Zephyr SDK 0.13.1

**Additional context**

No additional context.

### PR DESCRIPTION
**Pull request by jilu-ot**
Fixes #39989.

Save CCC data on pairing complete by replacing private addresses
for the just bonded device with its public address in CCC attributes'
CFG arrays. This is then followed by calls to bt_gatt_store_ccc
and bt_gatt_store_cf for the just bonded device.

Signed-off-by: Jim Benjamin Luther <jilu@oticon.com>

### CODE REVIEW

File: include/bluetooth/gatt.h [hunk 1]
```diff
@@ -725,6 +725,29 @@ struct _bt_gatt_ccc {
 			  const struct bt_gatt_attr *attr);
 };
 
+#if defined(CONFIG_BT_SETTINGS)
```
Comment (jhedberg) [inline include/bluetooth/gatt.h:728]: Please avoid #ifdefs in header files, since a) it hides the doxygen documentation unless you add exceptions to documentation generation and b) it prevents usage of `IS_ENABLED()` in calling code.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -1656,6 +1667,8 @@ static struct bt_gatt_ccc_cfg *find_ccc_cfg(const struct bt_conn *conn,
 	return NULL;
 }
 
+
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:1671]: What's this addition for?

File: subsys/bluetooth/host/gatt.c [hunk 3]
```diff
@@ -5140,6 +5153,57 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+{
+	struct device_addresses user_data = {.private_addr = private_addr,
+		.public_addr = public_addr};
+
+	bt_gatt_foreach_attr(0x0001, 0xffff, convert_to_public_on_match, &user_data);
+}
+
+int bt_gatt_store_ccc_and_cf(struct bt_conn *conn)
+{
+	int return_code = 0;
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5194]: Just call this variable `err` to be consistent with the rest of the code base

File: subsys/bluetooth/host/gatt.c [hunk 4]
```diff
@@ -5140,6 +5153,57 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+
+	return_code     = bt_gatt_store_ccc(conn->id, &(conn->le.dst));
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5196]: Some whitespace issue here - there should only be one space between the variable name and `=`

File: subsys/bluetooth/host/gatt.c [hunk 5]
```diff
@@ -5140,6 +5153,57 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5197]: You can remove this line (no empty line between variable assignment and testing for its value

File: subsys/bluetooth/host/gatt.c [hunk 6]
```diff
@@ -5140,6 +5153,57 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
 	return 0;
 }
 
+uint8_t convert_to_public_on_match(const struct bt_gatt_attr *attr, uint16_t handle,
+			void *user_data)
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5157]: This doesn't seem to be aligned with the `(` of the first line

File: subsys/bluetooth/host/gatt.c [hunk 7]
```diff
@@ -5140,6 +5153,57 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+{
+	struct _bt_gatt_ccc     *ccc;
+	struct device_addresses *device_addresses   = user_data;
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5160]: There seems to be some white space issues here: remove the multiple consecutive space characters

File: subsys/bluetooth/host/gatt.c [hunk 8]
```diff
@@ -5140,6 +5153,57 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+#endif /* CONFIG_BT_CTLR_ALLOW_SAME_PEER_CONN */
+		}
+	}
+	return BT_GATT_ITER_STOP;
+}
+
+void bt_gatt_update_ccc_cfg_addr(const bt_addr_le_t *private_addr, const bt_addr_le_t *public_addr)
+{
+	struct device_addresses user_data = {.private_addr = private_addr,
+		.public_addr = public_addr};
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5187]: There should be a space before `}` and after `{`. You might in general make this more readable with something like:
```
struct device addresses addr = {
        .private_addr = private_addr,
        .public_addr = public_addr,
};
```

File: subsys/bluetooth/host/gatt.c [hunk 9]
```diff
@@ -52,6 +52,17 @@
 
 static uint16_t last_static_handle;
 
+#if defined(CONFIG_BT_SETTINGS)
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:55]: Either remove the #ifdef, or (perhaps better) move this definition down to where it's actually used (and probably already behind the same CONFIG_BT_SETTINGS #ifdef.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Some coding-style related comments

**Comment by joerchan** [comment]
This looks like it could either be solved by `CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE`, or create issues when it is enabled.
I suggest to re-use (or use) this feature or the functions it uses. I think you could end up trying to write CCCs from different contexts now.

**Comment by jilu-ot** [comment]
> This looks like it could either be solved by `CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE`, or create issues when it is enabled. I suggest to re-use (or use) this feature or the functions it uses. I think you could end up trying to write CCCs from different contexts now.

Would CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE store CCC data if the device is not bonded?

The issue here is that some ble masters, like the iPhone 12, will subscribe to characteristics before bonding, and this creates problems if the slave device is rebooted and not disconnected.

Does CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE not only write CCC data on CCC write if the device has already been bonded?

**Comment by joerchan** [comment]
@jilu-ot I think you should use the STORE_ON_WRITE feature, and add an enqueue of ccc data in the connected. Instead of adding a different way to store the CCC data. Now you are possibly scheduling storing of CCC from 2 different contexts.

Also if you have to add updating of the device address before storing then the STORE_ON_WRITE feature is broken for privacy enabled devices as well then. Currently this is only updated in the `disconnected_cb` AFAICT.

A better place to call `bt_gatt_update_ccc_cfg_addr` would be from `bt_conn_identity_resolved` in that case. Would be more in line with how bt_gatt_disconnected is called for example.

Since STORE_ON_WRITE feature was added to solve the problem where the device is rebooted while connected it would make sense to expand on this feature instead of adding another.

**Comment by jilu-ot** [comment]
> @jilu-ot I think you should use the STORE_ON_WRITE feature, and add an enqueue of ccc data in the connected. Instead of adding a different way to store the CCC data. Now you are possibly scheduling storing of CCC from 2 different contexts.
> 
> Also if you have to add updating of the device address before storing then the STORE_ON_WRITE feature is broken for privacy enabled devices as well then. Currently this is only updated in the `disconnected_cb` AFAICT.
> 
> A better place to call `bt_gatt_update_ccc_cfg_addr` would be from `bt_conn_identity_resolved` in that case. Would be more in line with how bt_gatt_disconnected is called for example.
> 
> Since STORE_ON_WRITE feature was added to solve the problem where the device is rebooted while connected it would make sense to expand on this feature instead of adding another.

Ok. I will look into this.

**Comment by jilu-ot** [comment]
@joerchan I have implemented the changes we discussed.

**Comment by carlescufi** [comment]
@joerchan and @jhedberg could you please take another look?

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 10]
```diff
@@ -5158,6 +5158,67 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+	ccc = attr->user_data;
+
+	/* Copy the device's public address to the config's address if the config's address is the
+	 * same as the device's private address
+	 */
+	for (size_t i = 0; i < ARRAY_SIZE(ccc->cfg); i++) {
+		if (bt_addr_le_cmp((const bt_addr_le_t *)&ccc->cfg[i].peer,
+		    device_addresses->private_addr) == 0) {
+			bt_addr_le_copy(&ccc->cfg[i].peer, device_addresses->public_addr);
+#ifndef CONFIG_BT_CTLR_ALLOW_SAME_PEER_CONN
```
Comment (carlescufi) [inline subsys/bluetooth/host/gatt.c:5190]: Host code cannot use controller kconfig options. On top of that, this is a hidden Kconfig option. Please remove the conditional compilation even though it will result in code a bit less optimized.

**Comment by jilu-ot** [comment]
All the issues addressed should have been resolved now, and the tests are passing.

File: subsys/bluetooth/host/smp.c [hunk 11]
```diff
@@ -1876,6 +1880,10 @@ static void smp_pairing_complete(struct bt_smp *smp, uint8_t status)
 
 		if (bt_auth && bt_auth->pairing_complete) {
 			bt_auth->pairing_complete(conn, bond_flag);
+#if defined(CONFIG_BT_SETTINGS) && defined(CONFIG_BT_GATT_CLIENT)
+			/* Pairing has completed, so persist the CCC and CF data. */
+			k_work_submit(&(smp->work_settings_ccc_and_cf_save));
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:1885]: minor, but to keep consistency throughout the style used within the subsystem: the () is unnecessary around `smp->work_settings_ccc_and_cf_save`, i.e. the `&` operator will do the right thing also without it

File: subsys/bluetooth/host/smp.c [hunk 12]
```diff
@@ -4569,6 +4588,11 @@ static void bt_smp_connected(struct bt_l2cap_chan *chan)
 	       CONTAINER_OF(chan, struct bt_l2cap_le_chan, chan)->tx.cid);
 
 	k_work_init_delayable(&smp->work, smp_timeout);
+#if defined(CONFIG_BT_SETTINGS) && defined(CONFIG_BT_GATT_CLIENT)
+	k_work_init(&smp->work_settings_ccc_and_cf_save,
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:4592]: Here you're not using the parenthesis, so you're also being inconsistent with yourself :)

File: subsys/bluetooth/host/smp.c [hunk 13]
```diff
@@ -204,6 +205,9 @@ struct bt_smp {
 
 	/* Delayed work for timeout handling */
 	struct k_work_delayable		work;
+
+	/* A work item for persisting ccc and cf data in the system workqueue */
+	struct k_work			work_settings_ccc_and_cf_save;
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:210]: Let's come up with a shorter name for this. Any suggestions? It might also make sense to rename the existing `work` member to avoid confusion.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/smp.c (hunk 13 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:210]: How about: work_save_ccc_cf and work_timeout?

**Comment by carlescufi** [comment]
> Since STORE_ON_WRITE feature was added to solve the problem where the device is rebooted while connected it would make sense to expand on this feature instead of adding another.

@joerchan @MarekPieta 
After #40766, #40767 and #40769 being merged, do we really need the current PR anymore?

**Comment by joerchan** [comment]
@carlescufi As far as I understand what this PR addresses was a peer that first subscribes, then encrypts.
Since the CCC store is submitted only when bonded peer writes to the CCC this would not be stored before disconnection.
Hence the addition to submit the CCC store when pairing is complete.
The second thing was to add storing of CF in the same way as CCC.

From what I can see these two points are still valid.

**Comment by carlescufi** [comment]
@jilu-ot please follow-up as soon as you are able to.

File: subsys/bluetooth/host/gatt.c [hunk 14]
```diff
@@ -5158,6 +5158,64 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+	 * same as the device's private address
+	 */
+	for (size_t i = 0; i < ARRAY_SIZE(ccc->cfg); i++) {
+		if (bt_addr_le_cmp((const bt_addr_le_t *)&ccc->cfg[i].peer,
+		    device_addresses->private_addr) == 0) {
+			bt_addr_le_copy(&ccc->cfg[i].peer, device_addresses->public_addr);
+		}
+	}
+
+	return BT_GATT_ITER_STOP;
```
[the remark this answers is not in the document]
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5193]: Yes. I believe that's right. Will do.

[the remark this answers is not in the document]
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5193]: I will change it to BT_GATT_ITER_CONTINUE. Testing. I think I will drop the name changes this time around. But I am moving the gatt calls to gatt.c.

File: subsys/bluetooth/host/smp.c [hunk 15]
```diff
@@ -4569,6 +4588,11 @@ static void bt_smp_connected(struct bt_l2cap_chan *chan)
 	       CONTAINER_OF(chan, struct bt_l2cap_le_chan, chan)->tx.cid);
 
 	k_work_init_delayable(&smp->work, smp_timeout);
+#if defined(CONFIG_BT_SETTINGS) && defined(CONFIG_BT_GATT_CLIENT)
```
[the remark this answers is not in the document]
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:4591]: It seems to not work when I use CONFIG_BT_GATT_SERVER. Don't know why yet. But perhaps CONFIG_BT_SETTINGS is enough?

File: subsys/bluetooth/host/smp.c (hunk 13 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:210]: See comments below.

**Review by alwa-nordic — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 16]
```diff
@@ -5140,6 +5140,67 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
 	return 0;
 }
 
+/* Struct used to store both the public and the random address of a device when replacing
+ * random addresses in the ccc attribute's cfg array with the device's public address after
+ * pairing complete.
+ */
+struct device_addresses {
```
[the remark this answers is not in the document]
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5165]: Ok. I agree that name is not very informative. We can go with your suggestion.

File: subsys/bluetooth/host/gatt.c [hunk 17]
```diff
@@ -5140,6 +5140,67 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+
+uint8_t convert_to_public_on_match(const struct bt_gatt_attr *attr,
+									uint16_t handle,
+									void *user_data)
+{
+	struct _bt_gatt_ccc *ccc;
+	struct device_addresses *device_addresses = user_data;
+
+	/* Check if attribute is a CCC */
+	if (attr->write != bt_gatt_attr_write_ccc) {
```
[the remark this answers is not in the document]
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5177]: Sounds good, but not sure how many other places that use a similar approach. Could we perhaps do this in another PR?

File: subsys/bluetooth/host/gatt.c [hunk 18]
```diff
@@ -5140,6 +5140,67 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
 	return 0;
 }
 
+/* Struct used to store both the public and the random address of a device when replacing
```
[the remark this answers is not in the document]
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5161]: Ok.

File: subsys/bluetooth/host/smp.c (hunk 15 above)
[the remark this answers is not in the document]
Comment (alwa-nordic) [reply subsys/bluetooth/host/smp.c:4591]: I think CONFIG_BT_SETTINGS is enough. Both server and client must save the CCC configs to persistent storage at the same time to be in sync, so this PR has good reason to affect the client as well as the server. I assume this function is called after a bonding event, correct? At that point both the server and client should persist the CCCs.

File: subsys/bluetooth/host/gatt.c (hunk 17 above)
[the remark this answers is not in the document]
Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:5177]: I see that this is comparison is done in a lot of places. Best to do it in a separate PR then. I'll create a new issue for this.

**Comment by carlescufi** [comment]
@MarekPieta @jilu-ot Given that we merged #40766 and #40767, is this PR still needed and why?

**Comment by jilu-ot** [comment]
> @MarekPieta @jilu-ot Given that we merged #40766 and #40767, is this PR still needed and why?

#40766 will only store CCC data on a write and this does not prevent the loss of CCC data if a device is rebooted before a disconnect when the CCC data is normally stored.
#40767 removes updating the CCC data as I could see in the code change, so the missing CCC store on bonding complete would still be a problem as I understand it.

So I believe this PR is still needed.

**Comment by jilu-ot** [comment]
I hope to follow up with a code update that resolves some of the new review comments, sometime next week. I am currently quite busy, but hope to have more time next week.

File: subsys/bluetooth/host/smp.c (hunk 13 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:210]: Would it be alright to place name changes in a different PR? And also the reuse of a work item, since that might cause other problems?

Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:210]: So we can perhaps close this item for now?

File: subsys/bluetooth/host/gatt.c [hunk 19]
```diff
@@ -5171,6 +5171,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
 	return 0;
 }
 
+/** Struct used to store both the public and the random address of a device when replacing
+ * random addresses in the ccc attribute's cfg array with the device's public address after
+ * pairing complete.
+ */
+struct convert_to_public_on_match_params {
+	const bt_addr_le_t *private_addr;
+	const bt_addr_le_t *public_addr;
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5180]: id_addr

File: subsys/bluetooth/host/gatt.c [hunk 20]
```diff
@@ -5171,6 +5171,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+		if (bt_addr_le_cmp((const bt_addr_le_t *)&ccc->cfg[i].peer,
+		    device_addresses->private_addr) == 0) {
+			bt_addr_le_copy(&ccc->cfg[i].peer, device_addresses->public_addr);
+		}
+	}
+
+	return BT_GATT_ITER_CONTINUE;
+}
+
+void bt_gatt_update_ccc_cfg_addr(const bt_addr_le_t *private_addr, const bt_addr_le_t *public_addr)
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5209]: second parameter should be `id_addr`

File: subsys/bluetooth/host/gatt.c [hunk 21]
```diff
@@ -5171,6 +5171,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+{
+	struct convert_to_public_on_match_params user_data = {
+		.private_addr = private_addr,
+		.public_addr = public_addr
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5213]: `id_addr`

**Review by jhedberg — CHANGES_REQUESTED** [review]
What you get after pairing is actually called the identity address. It might be a public addresss, but that's not always the case. E.g. many single mode devices use a static random address as their identity address.

The other thing I'd comment on, but which doesn't necessarily have to be done in this PR, is that it's not very clean to have SMP depending on GATT (including `gatt_internal.h`). What we might instead want to have is a way for protocols like GATT to register a callback to be called when SMP is complete (i.e. `smp.c` would maintain a callback list)

File: subsys/bluetooth/host/smp.c [hunk 22]
```diff
@@ -1927,6 +1935,17 @@ static void smp_timeout(struct k_work *work)
...
+#if defined(CONFIG_BT_SETTINGS)
+static void bt_smp_save_ccc_and_cf_on_pairing_complete(struct k_work *work)
+{
+	struct bt_smp *smp = CONTAINER_OF(work, struct bt_smp, work_settings_ccc_and_cf_save);
+
+	bt_gatt_identity_resolved(smp->chan.chan.conn, &(smp->chan.chan.conn->le.init_addr),
+				  &smp->chan.chan.conn->le.dst);
+}
+
+#endif /* CONFIG_BT_SETTINGS */
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:1947]: Let's not do this. There is an `identity_resolved` callback that's part of the `bt_conn_cb` struct. I think GATT should register one of these structs and use that mechanism to get notified of identity resolving.

File: subsys/bluetooth/host/gatt.c (hunk 19 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Done.

File: subsys/bluetooth/host/gatt.c (hunk 20 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Done.

File: subsys/bluetooth/host/gatt.c (hunk 21 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Done.

File: subsys/bluetooth/host/smp.c (hunk 22 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:1947]: Yes. That sounds better to me too, but I would prefer if this could be done in another PR.

File: subsys/bluetooth/host/gatt.c [hunk 23]
```diff
@@ -5171,6 +5171,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+		return err;
+	}
+
+	err = bt_gatt_store_cf(conn);
+
+	return err;
+}
+
+void bt_gatt_identity_resolved(struct bt_conn *conn, const bt_addr_le_t *private_addr,
+			       const bt_addr_le_t *public_addr)
```
[the remark this answers is not in the document]
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Done.

**Comment by runegrunnet** [comment]
> What you get after pairing is actually called the identity address. It might be a public addresss, but that's not always the case. E.g. many single mode devices use a static random address as their identity address.
> 
> The other thing I'd comment on, but which doesn't necessarily have to be done in this PR, is that it's not very clean to have SMP depending on GATT (including `gatt_internal.h`). What we might instead want to have is a way for protocols like GATT to register a callback to be called when SMP is complete (i.e. `smp.c` would maintain a callback list)

**Comment by runegrunnet** [comment]
Closed by mistake

File: subsys/bluetooth/host/gatt.c [hunk 24]
```diff
@@ -5210,6 +5210,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
 	return 0;
 }
 
+/** Struct used to store both the id and the random address of a device when replacing
+ * random addresses in the ccc attribute's cfg array with the device's id address after
+ * pairing complete.
+ */
+struct convert_to_id_on_match_params {
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5217]: Please come up with some shorter name for this

File: subsys/bluetooth/host/gatt.c [hunk 25]
```diff
@@ -5210,6 +5210,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+	const bt_addr_le_t *private_addr;
+	const bt_addr_le_t *id_addr;
+};
+
+uint8_t convert_to_id_on_match(const struct bt_gatt_attr *attr,
+				   uint16_t handle, void *user_data)
+{
+	struct _bt_gatt_ccc *ccc;
+	struct convert_to_id_on_match_params *device_addresses = user_data;
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5226]: Same here for the variable name, e.g. just `match`

File: subsys/bluetooth/host/gatt.c [hunk 26]
```diff
@@ -5210,6 +5210,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+ * random addresses in the ccc attribute's cfg array with the device's id address after
+ * pairing complete.
+ */
+struct convert_to_id_on_match_params {
+	const bt_addr_le_t *private_addr;
+	const bt_addr_le_t *id_addr;
+};
+
+uint8_t convert_to_id_on_match(const struct bt_gatt_attr *attr,
+				   uint16_t handle, void *user_data)
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5223]: This line doesn't seem to be properly aligned

File: subsys/bluetooth/host/smp.c (hunk 13 above)
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:210]: If you're really not going to use the existing `identity_resolved` callback (which I still hope you'd reconsider for this PR), then at least please keep the changes to `smp.c` as minimal as possible. That means putting any additional work structs into `gatt.c` and not `smp.c`.

The name of the variable is also unnecessarily long (you really seem to be a fan of long symbol names 😉 ).

File: subsys/bluetooth/host/smp.c [hunk 27]
```diff
@@ -1876,6 +1880,10 @@ static void smp_pairing_complete(struct bt_smp *smp, uint8_t status)
 
 		if (bt_auth && bt_auth->pairing_complete) {
 			bt_auth->pairing_complete(conn, bond_flag);
+#if defined(CONFIG_BT_SETTINGS)
+			/* Pairing has completed, so persist the CCC and CF data. */
+			k_work_submit(&smp->work_settings_ccc_and_cf_save);
+#endif /* CONFIG_BT_SETTINGS */
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:1886]: Why is this done here, and not the same place where the `identity_resolved` callback is called?

File: subsys/bluetooth/host/smp.c [hunk 28]
```diff
@@ -1927,6 +1935,17 @@ static void smp_timeout(struct k_work *work)
 	atomic_set_bit(smp->flags, SMP_FLAG_TIMEOUT);
 }
 
+#if defined(CONFIG_BT_SETTINGS)
+static void bt_smp_save_ccc_and_cf_on_pairing_complete(struct k_work *work)
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:1939]: Please use some shorter function name

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 24 above)
Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c:5217]: E.g. simply `struct addr_match` would have been fine (feel free to suggest something else if you don't like it - as long as it's short, yet understandable)

File: subsys/bluetooth/host/smp.c (hunk 13 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:210]: Okidoki :-) Yes I am ;-) But I will find something shorter.

File: subsys/bluetooth/host/gatt.c (hunk 24 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5217]: Okidoki.

Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5217]: Changing it to addr_match.

File: subsys/bluetooth/host/gatt.c (hunk 25 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5226]: Using the addr_match name.

File: subsys/bluetooth/host/gatt.c (hunk 26 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c:5223]: Done.

File: subsys/bluetooth/host/smp.c (hunk 13 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:210]: I am now using the identity_resolved callback. I agree this is nicer.

File: subsys/bluetooth/host/smp.c (hunk 28 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c:1939]: There are no changes to smp.c

File: subsys/bluetooth/host/gatt.c [hunk 29]
```diff
@@ -4989,6 +4998,14 @@ void bt_gatt_connected(struct bt_conn *conn)
...
 #if defined(CONFIG_BT_GATT_CLIENT)
 	add_subscriptions(conn);
+
+#if defined(CONFIG_BT_SETTINGS)
+	/* Register the gatt module for connection callbacks so it can be
+	 * notified when pairing has completed. This is used to enable CCC and
+	 * CF storage on pairing complete.
+	 */
+	bt_conn_cb_register(&gatt_conn_cb);
+#endif
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5008]: This is really the only #ifdef block that you should need for the callback struct:
```
#if defined(CONFIG_BT_SETTINGS)
        static struct bt_conn_cb gatt_conn_cb = {
                .identity_resolved = bt_gatt_identity_resolved;
        };

        bt_conn_cb_register(&gatt_conn_cb);
#endif

File: subsys/bluetooth/host/gatt.c [hunk 30]
```diff
@@ -5210,6 +5227,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+ * random addresses in the ccc attribute's cfg array with the device's id address after
+ * pairing complete.
+ */
+struct addr_match {
+	const bt_addr_le_t *private_addr;
+	const bt_addr_le_t *id_addr;
+};
+
+uint8_t convert_to_id_on_match(const struct bt_gatt_attr *attr,
+							   uint16_t handle, void *user_data)
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5240]: The alignment of the split line is not correct

File: subsys/bluetooth/host/gatt.c [hunk 31]
```diff
@@ -5210,6 +5227,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+{
+	struct _bt_gatt_ccc *ccc;
+	struct addr_match *device_addresses = user_data;
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5243]: As I earlier suggested, the variable name can probably be shortened (I'm in particular bringing this up since it will allow you to merge some split lines later in the code). E.g. simply `match` would be perfectly readable to me at least.

File: subsys/bluetooth/host/gatt.c [hunk 32]
```diff
@@ -5210,6 +5227,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+		return BT_GATT_ITER_CONTINUE;
+	}
+
+	ccc = attr->user_data;
+
+	/* Copy the device's id address to the config's address if the config's address is the
+	 * same as the device's private address
+	 */
+	for (size_t i = 0; i < ARRAY_SIZE(ccc->cfg); i++) {
+		if (bt_addr_le_cmp((const bt_addr_le_t *)&ccc->cfg[i].peer,
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5256]: The `(const bt_addr_le_t *)` typecast seems unnecessary.

File: subsys/bluetooth/host/gatt.c [hunk 33]
```diff
@@ -5210,6 +5227,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+	}
+
+	return BT_GATT_ITER_CONTINUE;
+}
+
+void bt_gatt_update_ccc_cfg_addr(const bt_addr_le_t *private_addr, const bt_addr_le_t *id_addr)
+{
+	struct addr_match user_data = {
+		.private_addr = private_addr,
+		.id_addr	  = id_addr
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5269]: These two are differently aligned (I'd just forget about the alignment attempts here and just have a single space before and after `=`)

File: subsys/bluetooth/host/gatt.c [hunk 34]
```diff
@@ -5210,6 +5227,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+{
+	int err = bt_gatt_store_ccc(conn->id, &(conn->le.dst));
+
+	if (err != 0) {
+		return err;
+	}
+
+	err = bt_gatt_store_cf(conn);
+
+	return err;
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5285]: Just do `return bt_gatt_store_cv(conn);`

File: subsys/bluetooth/host/gatt.c [hunk 35]
```diff
@@ -5210,6 +5227,71 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr)
...
+}
+
+void bt_gatt_identity_resolved(struct bt_conn *conn, const bt_addr_le_t *private_addr,
+			       const bt_addr_le_t *id_addr)
+{
+	bt_gatt_update_ccc_cfg_addr(private_addr, id_addr);
+	bt_gatt_store_ccc_and_cf(conn);
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5292]: Since these are both single-purpose functions called from a single place and both are fairly short, I'd just code them inline directly into this function. Btw, remember to declare functions as `static` if they're only used within a single c-file. Also place new static functions as high up in the c-file as possible in order to avoid the need for forward-declarations (i.e. if possible, place this before the point where you register the callbacks).

File: subsys/bluetooth/host/gatt_internal.h [hunk 36]
```diff
@@ -34,6 +34,11 @@ int bt_gatt_store_ccc(uint8_t id, const bt_addr_le_t *addr);
 
 int bt_gatt_clear(uint8_t id, const bt_addr_le_t *addr);
 
+void bt_gatt_update_ccc_cfg_addr(const bt_addr_le_t *private_addr, const bt_addr_le_t *id_addr);
+int bt_gatt_store_ccc_and_cf(struct bt_conn *conn);
+void bt_gatt_identity_resolved(struct bt_conn *conn, const bt_addr_le_t *private_addr,
+							   const bt_addr_le_t *id_addr);
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt_internal.h:41]: All of this should be removed, now that nothing is getting called from outside of `gatt.c`.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Thanks a lot for converting to use `bt_conn_cb`! It looks indeed cleaner 😄 

There are still some minor things to fix, which I've pointed out in the more detailed inline comments.

File: subsys/bluetooth/host/gatt.c (hunk 29 above)
Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c:5008]: Actually, you might even be able to use:
```c
if (IS_ENABLED(CONFIG_BT_SETTINGS) {
        static struct bt_conn_cb gatt_conn_cb = {
                .identity_resolved = bt_gatt_identity_resolved,
        };

        bt_conn_cb_register(&gatt_conn_cb);
}
```

That might let you skip the #ifdef block also for `bt_gatt_identity_resolved()` and any other static functions that it may call.

**Comment by carlescufi** [comment]
> > @MarekPieta @jilu-ot Given that we merged #40766 and #40767, is this PR still needed and why?
> 
> #40766 will only store CCC data on a write and this does not prevent the loss of CCC data if a device is rebooted before a disconnect when the CCC data is normally stored. #40767 removes updating the CCC data as I could see in the code change, so the missing CCC store on bonding complete would still be a problem as I understand it.
> 
> So I believe this PR is still needed.

@jilu-ot so the scenario that you are covering here is:
a) Client connects and writes to CCC, with no encryption or bonding available
b) Client or server initiates bonding
c) Bonding completes, CCC must now be stored

is that correct?

File: subsys/bluetooth/host/gatt.c (hunk 29 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Done.

File: subsys/bluetooth/host/gatt.c (hunk 30 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Fixed I hope.

File: subsys/bluetooth/host/gatt.c (hunk 31 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Used match.

File: subsys/bluetooth/host/gatt.c (hunk 32 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Removed the typecast.

File: subsys/bluetooth/host/gatt.c (hunk 33 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Fixed alignment.

File: subsys/bluetooth/host/gatt.c (hunk 34 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Ok.

Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Can't return here now actually since it the void callback handler for identity_resolved. Ok?

File: subsys/bluetooth/host/gatt_internal.h (hunk 36 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt_internal.h]: Done.

File: subsys/bluetooth/host/smp.c (hunk 13 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c]: This one no longer used.

File: subsys/bluetooth/host/smp.c (hunk 27 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c]: Not used anymore.

File: subsys/bluetooth/host/smp.c (hunk 28 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/smp.c]: Not used anymore.

File: subsys/bluetooth/host/gatt.c (hunk 25 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Used match.

File: subsys/bluetooth/host/gatt.c (hunk 24 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Used addr_match.

**Comment by jilu-ot** [comment]
> > > @MarekPieta @jilu-ot Given that we merged #40766 and #40767, is this PR still needed and why?
> > 
> > 
> > #40766 will only store CCC data on a write and this does not prevent the loss of CCC data if a device is rebooted before a disconnect when the CCC data is normally stored. #40767 removes updating the CCC data as I could see in the code change, so the missing CCC store on bonding complete would still be a problem as I understand it.
> > So I believe this PR is still needed.
> 
> @jilu-ot so the scenario that you are covering here is: a) Client connects and writes to CCC, with no encryption or bonding available b) Client or server initiates bonding c) Bonding completes, CCC must now be stored
> 
> is that correct?

Yes. This is to make sure that CCC data is stored if the device reboots before a disconnect. This will ensure that for instance a service changed subscription is remembered and a service changed indication is sent after the reboot if the gatt database has changed.

File: subsys/bluetooth/host/gatt.c [hunk 37]
```diff
@@ -455,6 +455,60 @@ static ssize_t sc_ccc_cfg_write(struct bt_conn *conn,
...
+/** Struct used to store both the id and the random address of a device when replacing
+ * random addresses in the ccc attribute's cfg array with the device's id address after
+ * pairing complete.
+ */
+struct addr_match {
+	const bt_addr_le_t *private_addr;
+	const bt_addr_le_t *id_addr;
+};
+
+uint8_t convert_to_id_on_match(const struct bt_gatt_attr *attr,
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:470]: missing `static` here

File: subsys/bluetooth/host/gatt.c [hunk 38]
```diff
@@ -455,6 +455,60 @@ static ssize_t sc_ccc_cfg_write(struct bt_conn *conn,
 	return sizeof(value);
 }
 
+#if defined(CONFIG_BT_SETTINGS) && defined(CONFIG_BT_SMP)
+static int bt_gatt_store_cf(struct bt_conn *conn);
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:459]: Is there really no way to avoid this, e.g. by moving stuff up or down in the c-file? Note: I'm not asking you to necessarily do something, if it's too invasive, just that you checked what it would mean if one would try to avoid it.

File: subsys/bluetooth/host/gatt.c [hunk 39]
```diff
@@ -4989,6 +5043,18 @@ void bt_gatt_connected(struct bt_conn *conn)
 
 #if defined(CONFIG_BT_GATT_CLIENT)
 	add_subscriptions(conn);
+
+#if defined(CONFIG_BT_SETTINGS) && defined(CONFIG_BT_SMP)
+	static struct bt_conn_cb gatt_conn_cb = {
+		.identity_resolved	= bt_gatt_identity_resolved
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:5049]: minor: just use a space before `=` (now you have a tab, and tabs should only ever exist at the very beginning of a line)

Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c:5049]: Also, add a comma at the end (I know, not necessary, but it makes diffs easier to read if/when new callbacks get added here)

File: subsys/bluetooth/host/gatt.c (hunk 37 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Done.

File: subsys/bluetooth/host/gatt.c (hunk 38 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Found a way.

File: subsys/bluetooth/host/gatt.c (hunk 39 above)
Comment (jilu-ot) [reply subsys/bluetooth/host/gatt.c]: Done.

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
@alwa-nordic can you take another look?

**Review by alwa-nordic — APPROVED** [review]
