### PR TITLE
soc: st: stm32u5 set backup sram retention if regulator is LDO

### LINKED ISSUE #99056: stm32: driver: stm32_backup_sram: Backup regulator is never powered on for stm32u5(q) with smps regulator
### Describe the bug

According to the documentation, the backup regulator can be enabled only when the regulator is LDO, but at the time the driver is called, the regulator is smps and the code processing is stuck in
 `while (!LL_PWR_IsEnabledBkUpRegulator())`
Tested on stm32u575zi-q

### Regression

- [ ] This is a regression.

### Steps to reproduce

```
# Enable the internal SMPS regulator
CONFIG_POWER_SUPPLY_DIRECT_SMPS=y
CONFIG_STM32_BACKUP_SRAM=y
```

```
&backup_sram {
	status = "okay";
};
```

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

Linux Ubuntu
SDK 0.17.0
Zephyr version 4.2.99

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by FRASTM**
On the stm32u5 series, this commit will enable backup sram regulator when the regulator is LDO, during SOC init.
Then stm32_backup_sram_init()  will not change the backup SRAM retention anymore.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/99056

### CODE REVIEW

File: soc/st/stm32/common/stm32_backup_sram.c [hunk 1]
```diff
@@ -51,6 +60,8 @@ static int stm32_backup_sram_init(const struct device *dev)
 	}
 
 	return 0;
+#endif /* CONFIG_SOC_SERIES_STM32U5X */
+
```
Comment (mathieuchopstm) [inline soc/st/stm32/common/stm32_backup_sram.c]: The `return 0` can be shared by both blocks, i.e.:
```c
#if defined(CONFIG_SOC_SERIES_STM32U5X)
	/*
	 * For series like stm32u5 which have LDO/SMPS internal regulator, enabling
	 * the Backup RAM retention is possible only when the regulator is LDO.
	 * The backup regulator position has been set at soc init ;
	 * exit now to avoid writing the BREN bit of the PWR_BDCR1 register.
	 */
#else /* CONFIG_SOC_SERIES_STM32U5X */
	/* enable backup sram regulator (required to retain backup SRAM content
	 * while in standby or VBAT modes).
	 */
	LL_PWR_EnableBkUpRegulator();
	while (!LL_PWR_IsEnabledBkUpRegulator()) {
	}
#endif /* CONFIG_SOC_SERIES_STM32U5X */
	return 0;
```

But instead I would suggest:
```c
	if (IS_ENABLED(CONFIG_SOC_SERIES_STM32U5X)) {
		/*
		 * On STM32U5 series, backup RAM retention can only be enabled
		 * when the LDO is selected as voltage regulator. However, the
		 * SMPS regulator may have been selected by the time this code
		 * executes, which results in a deadlock. To avoid this, the
		 * SoC initialization code is modified to enable the regulator
		 * on our behalf, before switching regulators - don't try to
		 * enable the regulator again.
		 */
	} else {
		/* enable backup sram regulator (required to retain backup SRAM content
		 * while in standby or VBAT modes).
		 */
		LL_PWR_EnableBkUpRegulator();
		while (!LL_PWR_IsEnabledBkUpRegulator()) {
		}
	}
```

File: soc/st/stm32/stm32u5x/soc.c [hunk 2]
```diff
@@ -60,6 +60,16 @@ void soc_early_init_hook(void)
...
 #endif
 
+#ifdef CONFIG_STM32_BACKUP_SRAM
+	/*
+	 * Enabling the Backup RAM retention is possible only when the regulator is LDO.
+	 * Force the backup sram regulator ON, before the SELECTED_POWER_SUPPLY.
+	 */
+	LL_PWR_EnableBkUpRegulator();
+	while (!LL_PWR_IsEnabledBkUpRegulator()) {
+	}
```
Comment (mathieuchopstm) [inline soc/st/stm32/stm32u5x/soc.c:71]: Proposal:
```suggestion
	/*
	 * Enabling the Backup SRAM regulator is possible only when the LDO
	 * voltage regulator is selected, as is the case after reset). If the
	 * backup SRAM driver is enabled, make sure to enable the Backup SRAM
	 * regulator on its behalf before (potentially) switching to SMPS.
	 */
	LL_PWR_EnableBkUpRegulator();
	while (!LL_PWR_IsEnabledBkUpRegulator()) {
	}
```

**Review by mathieuchopstm — COMMENTED** [review]
LGTM functionally

File: soc/st/stm32/common/stm32_backup_sram.c (hunk 1 above)
Comment (FRASTM) [reply soc/st/stm32/common/stm32_backup_sram.c]: I see that, but I just want to avoid a section #if defined(CONFIG_SOC_SERIES_STM32U5X) with just a comment line, no code.
So suggestion is fine even if consuming more rom.

**Comment by FRASTM** [comment]
with @mathieuchopstm 's  suggestion

**Review by mathieuchopstm — APPROVED** [review]

File: soc/st/stm32/stm32u5x/soc.c [hunk 3]
```diff
@@ -59,6 +59,16 @@ void soc_early_init_hook(void)
 		LL_PWR_DisableUCPDDeadBattery();
 	}
 #endif
+	/*
```
Comment (mathieuchopstm) [inline soc/st/stm32/stm32u5x/soc.c:63]: Missing `#ifdef CONFIG_STM32_BACKUP_SRAM` here

**Review by mathieuchopstm — CHANGES_REQUESTED** [review]

File: soc/st/stm32/stm32u5x/soc.c [hunk 4]
```diff
@@ -59,6 +59,17 @@ void soc_early_init_hook(void)
 		LL_PWR_DisableUCPDDeadBattery();
 	}
 #endif
+#ifdef CONFIG_STM32_BACKUP_SRAM
+	/*
+	 * Enabling the Backup SRAM regulator is possible only when the LDO
+	 * voltage regulator is selected, as is the case after reset). If the
```
Comment (etienne-lms) [inline soc/st/stm32/stm32u5x/soc.c]: Typo
```suggestion
	 * voltage regulator is selected, as is the case after reset. If the

File: soc/st/stm32/stm32u5x/soc.c [hunk 5]
```diff
@@ -59,6 +59,17 @@ void soc_early_init_hook(void)
...
+	 * backup SRAM driver is enabled, make sure to enable the Backup SRAM
+	 * regulator on its behalf before (potentially) switching to SMPS.
+	 */
+	LL_PWR_EnableBkUpRegulator();
```
Comment (etienne-lms) [inline soc/st/stm32/stm32u5x/soc.c:69]: `__ASSERT(LL_PWR_GetRegulatorSupply() == LL_PWR_LDO_SUPPLY)`?

Comment (mathieuchopstm) [reply soc/st/stm32/stm32u5x/soc.c:69]: No need to check, this is guaranteed in hardware (this code runs right after reset).

**Review by mathieuchopstm — DISMISSED** [review]

File: soc/st/stm32/stm32u5x/soc.c (hunk 5 above)
Comment (etienne-lms) [reply soc/st/stm32/stm32u5x/soc.c:69]: This code may run after MCUboot, TF-M or something else.
If there's a potential deadlock, I think an assertion would help one to locate the issue.

**Review by erwango — APPROVED** [review]

File: soc/st/stm32/stm32u5x/soc.c (hunk 5 above)
Comment (mathieuchopstm) [reply soc/st/stm32/stm32u5x/soc.c:69]: If this is executed by a second-stage binary then the first stage should have executed and already enabled the generator: the `while (!LL_PWR_IsEnabledBkUpRegulator()) {}` will exit immediately.

**Review by mathieuchopstm — APPROVED** [review]
