### PR TITLE
drivers: ethernet: dsa_nxp_imx_netc: fix zephyr random mac

### LINKED ISSUE #101236: NXP: Failed to disable random-mac-address in ethernet driver.
### Describe the bug

Conventionally, if we want to disable a boolean property, we will use `/delete-property/` as tag before that certain field inside the overlay dts file. Inside mimxrt1180_evk.dtsi, `zephyr,random-mac-address` is set for each switch port:
```
// mimxrt1180_evk.dtsi, line 97
&switch_port0 {
	zephyr,random-mac-address;
	pinctrl-0 = <&eth0_default>;
	pinctrl-names = "default";
	phy-handle = <&phy0>;
	phy-connection-type = "rmii";
	status = "okay";
};
```
After adding `/delete-property/` before `zephyr,random-mac-address` and adding `local-mac-address` field inside the overlay dts, 
```
// mimxrt1180_evk_mimxrt1189_cm33.overlay
&switch_port0 {
    /delete-property/ zephyr,random-mac-address;
    local-mac-address = [00 00 00 01 04 00];
};

&switch_port1 {
    /delete-property/ zephyr,random-mac-address;
    local-mac-address = [00 00 00 01 05 00];
};

&switch_port2 {
    /delete-property/ zephyr,random-mac-address;
    local-mac-address = [00 00 00 01 06 00];
};

&switch_port3 {
	/delete-property/ zephyr,random-mac-address;
    local-mac-address = [00 00 00 01 07 00];
};

/* Internal port */
&switch_port4 {
    /delete-property/ zephyr,random-mac-address;
};
```
the MAC address for the switch port is still random instead of the specific value assigned by `local-mac-address`.

Image

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Call `net_if_foreach` with a printing method to print each ethernet device's information at the beginning of the app.
2. west build -p -b mimxrt1180_evk/mimxrt1189/cm33 {your_app} && west flash -r jlink
3. Reset your MIMXRT1180EVK board and look at the output.

### Relevant log output

```shell
[00:00:00.052,000] <inf> phy_mii: PHY (3) ID 1CC816
[00:00:00.103,000] <inf> phy_mii: PHY (2) ID 1CC816
[00:00:00.143,000] <inf> dsa_netc: DSA user port 0 Link down
[00:00:00.143,000] <inf> dsa_netc: DSA user port 1 Link down
[00:00:00.143,000] <inf> dsa_netc: DSA user port 2 Link down
[00:00:00.144,000] <inf> dsa_netc: DSA user port 3 Link down
[00:00:00.144,000] <inf> nxp_imx_eth_psi: ENETC0 MAC: 00:00:00:01:02:00
[00:00:00.144,000] <inf> nxp_imx_eth_psi: ENETC0 Link down
[00:00:00.144,000] <inf> nxp_imx_eth_psi: ENETC1 MAC: 00:00:00:01:03:00
*** Booting Zephyr OS build v4.2.0 ***
[00:00:00.145,000] <inf> main: Initalizing modules
[00:00:00.145,000] <inf> ethernet: Available Interfaces:
[00:00:00.145,000] <inf> ethernet: Interface  Device               MAC Address          IPv4 Address         Netmask              Gateway              Up
[00:00:00.145,000] <inf> ethernet: swp0       switch_port@0        02-04-9f-83-be-05    0.0.0.0              0.0.0.0              0.0.0.0              0

[00:00:00.145,000] <inf> ethernet: swp1       switch_port@1        02-04-9f-e4-7b-6f    0.0.0.0              0.0.0.0              0.0.0.0              0

[00:00:00.145,000] <inf> ethernet: swp2       switch_port@2        02-04-9f-e3-0c-ba    0.0.0.0              0.0.0.0              0.0.0.0              0

[00:00:00.145,000] <inf> ethernet: swp3       switch_port@3        02-04-9f-60-a2-be    0.0.0.0              0.0.0.0              0.0.0.0              0

[00:00:00.145,000] <inf> ethernet: swp4       switch_port@4        02-04-9f-7b-d5-de    0.0.0.0              0.0.0.0              0.0.0.0              0

[00:00:00.145,000] <inf> ethernet: eth0       ethernet@60b00000    00-00-00-01-02-00    0.0.0.0              0.0.0.0              0.0.0.0              0

[00:00:00.146,000] <inf> ethernet: eth1       ethernet@60b40000    00-00-00-01-03-00    109.103.1.16         172.27.0.16          181.106.1.16         1
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Ubuntu 24.04
- Toolchain: west
- 413b789deb391d3a37d06b463288a5fe765ee57e

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by tswaehn**
`zephyr,random-mac-address` defaults to 0 or 1, which is always available in generated code. so we can use the value itself.

actually just replaced 

`DT_NODE_HAS_PROP`

by

`DT_PROP`

Fixes: #101236

### CODE REVIEW

File: drivers/ethernet/dsa/dsa_nxp_imx_netc.c [hunk 1]
```diff
@@ -115,32 +115,33 @@ static struct dsa_api dsa_netc_api = {
...
+	COND_CODE_1(DT_NUM_PINCTRL_STATES(port), (PINCTRL_DT_DEFINE(port);), (EMPTY))              \
+                                                                                                   \
+	struct dsa_netc_port_config dsa_netc_##n##_##port##_config = {                             \
+		.pincfg = COND_CODE_1(DT_NUM_PINCTRL_STATES(port),				   \
+			(PINCTRL_DT_DEV_CONFIG_GET(port)), NULL),                             \
+			.phy_mode = NETC_PHY_MODE(port),                                           \
+	};                                                                                         \
+                                                                                                   \
+	struct dsa_port_config dsa_##n##_##port##_config = {                                       \
+		.use_random_mac_addr = DT_INST_PROP(port, zephyr_random_mac_address),              \
```
Comment (pdgendt) [inline drivers/ethernet/dsa/dsa_nxp_imx_netc.c]: I'd recommend only modifying this line, and not re-format as this loses crucial change information.

Comment (tswaehn) [reply drivers/ethernet/dsa/dsa_nxp_imx_netc.c]: understand. however ci-compliance tests doesnt like the format of the rest.

Comment (pdgendt) [reply drivers/ethernet/dsa/dsa_nxp_imx_netc.c]: The format compliance test is ~optional~ excluded in CI

Comment (tswaehn) [reply drivers/ethernet/dsa/dsa_nxp_imx_netc.c]: done

**Review by pdgendt — DISMISSED** [review]

**Review by maass-hamburg — APPROVED** [review]

File: doc/connectivity/networking/dsa.rst [hunk 2]
```diff
@@ -83,7 +83,7 @@ of i.MX NETC.
                    .phy_mode = NETC_PHY_MODE(port),                                            \
            };                                                                                  \
            struct dsa_port_config dsa_##n##_##port##_config = {                                \
-                   .use_random_mac_addr = DT_NODE_HAS_PROP(port, zephyr_random_mac_address),   \
+                   .use_random_mac_addr = DT_INST_PROP(port, zephyr_random_mac_address),       \
```
Comment (maass-hamburg) [inline doc/connectivity/networking/dsa.rst]: use the non inst variant on both ones

**Review by maass-hamburg — CHANGES_REQUESTED** [review]

**Comment by decsny** [comment]
this is actually a bug technically, boolean prop should not be read with _HAS_PROP macro, @tswaehn can you please fix PR to use the right macro like @maass-hamburg said

File: doc/connectivity/networking/dsa.rst (hunk 2 above)
Comment (tswaehn) [reply doc/connectivity/networking/dsa.rst]: I actually used `DT_INST_PROP(...) `- so that is not correct to use it?

Comment (maass-hamburg) [reply doc/connectivity/networking/dsa.rst]: It is wrong, `port` is not a instance number here, it is already a node identifier. 
instance number -> `DT_INST_PROP`
node identifier -> `DT_PROP`
thats why for most devicetree macros there are 2 variants.

see https://docs.zephyrproject.org/latest/build/dts/api/api.html#instance-based-apis

Comment (tswaehn) [reply doc/connectivity/networking/dsa.rst]: ok. that explains ... thanks

File: doc/connectivity/networking/dsa.rst [hunk 3]
```diff
@@ -83,7 +83,7 @@ of i.MX NETC.
                    .phy_mode = NETC_PHY_MODE(port),                                            \
            };                                                                                  \
            struct dsa_port_config dsa_##n##_##port##_config = {                                \
-                   .use_random_mac_addr = DT_NODE_HAS_PROP(port, zephyr_random_mac_address),   \
+                   .use_random_mac_addr = DT_PROP(port, zephyr_random_mac_address),       \
```
Comment (pdgendt) [inline doc/connectivity/networking/dsa.rst]: Fix `\` alignment

Comment (pdgendt) [reply doc/connectivity/networking/dsa.rst]: Should only add spaces here.

File: drivers/ethernet/dsa/dsa_nxp_imx_netc.c [hunk 4]
```diff
@@ -552,7 +552,7 @@ static struct dsa_api dsa_netc_api = {
 		.phy_mode = NETC_PHY_MODE(port),                                            \
 	};                                                                                  \
 	struct dsa_port_config dsa_##n##_##port##_config = {                                \
-		.use_random_mac_addr = DT_NODE_HAS_PROP(port, zephyr_random_mac_address),   \
+		.use_random_mac_addr = DT_PROP(port, zephyr_random_mac_address),	    \
```
Comment (pdgendt) [inline drivers/ethernet/dsa/dsa_nxp_imx_netc.c]: Replace the `<tab>` with spaces to be consistent with the surrounding code, please.

File: doc/connectivity/networking/dsa.rst (hunk 3 above)
Comment (tswaehn) [reply doc/connectivity/networking/dsa.rst]: I am checking with `./scripts/ci/check_compliance.py` it feels like the whole format seems to be strange.

File: drivers/ethernet/dsa/dsa_nxp_imx_netc.c (hunk 4 above)
Comment (tswaehn) [reply drivers/ethernet/dsa/dsa_nxp_imx_netc.c]: btw. after closing this, we should probably follow the scheme from PR https://github.com/zephyrproject-rtos/zephyr/pull/100619

**Review by maass-hamburg — APPROVED** [review]

**Review by yangbolu1991 — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
