### PR TITLE
tests: posix: fix nanosleep tests for clock slew

### LINKED ISSUE #26263: reel_board:tests/posix/common failed.
**To Reproduce**
1. west build -b reel_board -p auto tests/posix/common
2. west flash
3. See error

**Screenshots or console output**
*** Booting Zephyr OS build zephyr-v2.3.0-397-g540ed9578613  ***
Running test suite posix_apis

starting test - test_posix_pthread_execution
Thread 0 starting with scheduling policy 0 & priority 15
Thread 1 starting with scheduling policy 0 & priority 15
Thread 2 starting with scheduling policy 0 & priority 15
Bounce test OK
Barrier test OK
PASS - test_posix_pthread_execution

starting test - test_posix_pthread_termination
Thread 0 starting with a priority of 4
Cancelling thread 0
Thread 1 starting with a priority of 3
Cancelling thread 1
Thread 1 could not be cancelled
Thread 2 starting with a priority of 2
Cancelling thread 2
Thread 3 starting with a priority of 1
Cancelling thread 3
Thread 3 could not be cancelled
PASS - test_posix_pthread_termination

starting test - test_posix_multiple_threads_single_key
Different threads set different values to same key:
thread 0: set value = 536877516 and retrieved value = 536877516
thread 1: set value = 536877756 and retrieved value = 536877756
PASS - test_posix_multiple_threads_single_key
....
starting test - test_nanosleep_0_1000000000
PASS - test_nanosleep_0_1000000000

starting test - test_nanosleep_0_1
dt_ns: 30518
PASS - test_nanosleep_0_1

**starting test - test_nanosleep_0_500000000
dt_ns: 499847413
Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/nanosleep.c:203: common: (dt_ns >= ns is false)
expected dt_ns >= 500000000: actual: 499847413**
FAIL - test_nanosleep_0_500000000

starting test - test_nanosleep_1_0
dt_ns: 999908448
Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/nanosleep.c:203: common: (dt_ns >= ns is false)
expected dt_ns >= 1000000000: actual: 999908448
FAIL - test_nanosleep_1_0

Test suite posix_apis failed.

PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.11.3
 - Commit ID: 540ed95786

### PR DESCRIPTION
**Pull request by pabigot**
Use the technique from portability/cmsis_rtos_v1 to compensate for
systems where times are being measured with different clocks.

Fixes #26263.

### CODE REVIEW

**Comment by cfriedt** [comment]
Hmm... interesting. I have an NRF board that I could test this on. The big issue I had with testing for any kind of tolerance, was that it's actually really difficult to do in CI either using qemu or software.

I also think that there needs to be some work in Zephyr to organize a number of clock sources with various tolerances, but I haven't done my homework on that yet, so it's just speculation. My preference would be to do things in a POSIX-y way as well, which may or may not be what the community would like.

**Comment by pabigot** [comment]
The test fails on mostly oddball platforms like qemu_cortex_r5, qemu_xtensa, qemu_arc_em, qemu_arc_hs, and mps2_an385.

The failure mode is that for a 1 ns sleep the tick counter advances by a large number (124 for qemu_cortex_r5, 166 for qemu_xtensa) which of course converts to an unacceptably large nanosecond measured duration.

This seems to be specific to the test environment and/or processor.  I don't know how to fix that.

@nashif @andyross any ideas?

**Comment by cfriedt** [comment]
@pabigot - it's possible that this is an artifact of the instruction-accurate vs clock-cycle accurate dichotomy in qemu. The issues is really speed vs accuracy - it's impossible to make qemu run fast (instruction accurate) while making any kind of attempt to say that it is clock-cycle accurate to a specific architecture.

I would say, if the test passes on hardware, then enable it only for certain hardware, and add high-precision tests to an "ignore list" for if running in qemu.

File: tests/posix/common/src/nanosleep.c [hunk 1]
```diff
@@ -186,22 +199,19 @@ static void common(const uint32_t s, uint32_t ns)
...
-		 */
-		dt_ns = 1;
-	}
-
-	printk("dt_ns: %llu\n", dt_ns);
-
-	zassert_true(dt_ns >= ns, "expected dt_ns >= %d: actual: %d", (int)ns,
-		(int)dt_ns);
+	uint64_t exp_ns = s * NSEC_PER_SEC + ns;
+	uint64_t tolerance_ns = MAX(NSEC_PER_CYCLE,
```
Comment (nordic-krch) [inline tests/posix/common/src/nanosleep.c:203]: what is the reason for capping it with NSEC_PER_CYCLE?

Comment (pabigot) [reply tests/posix/common/src/nanosleep.c:203]: It's not being capped: it's being cupped (? whatever the opposite is).  I.e. the minimum value is NSEC_PER_CYCLE, necessary to handle the cases where `exp_ns` is so small that even with tolerance it's a sub-cycle amount.  A one-cycle minimum is necessary because the ceiling is used when converting cycles to ns.

This test is supposed to work on 1ns delays, which should round up to a one cycle delay due to timer resolution.

**Review by nordic-krch — APPROVED** [review]

**Review by pfalcon — DISMISSED** [review]

**Comment by pfalcon** [comment]
@pabigot I hope you saw:

~~~
INFO    -  4/20 qemu_arc_hs               tests/posix/common/portability.posix.common        FAILED Failed (qemu 17.511s)
INFO    - 16/20 mps2_an521                tests/posix/common/portability.posix.common        FAILED Failed (qemu 8.669s)
~~~
etc.

These things never have been easy. Withdrawing my approval for now.

**Comment by pabigot** [comment]
> @pabigot I hope you saw:

I certainly did.  https://github.com/zephyrproject-rtos/zephyr/pull/27065#issuecomment-664372003

**Comment by carlescufi** [comment]
#ifdef out the test cases that require high fidelity using `CONFIG_QEMU_TARGET` and report it as skipped.

**Review by carlescufi — APPROVED** [review]
Fixed as agreed
