### PR TITLE
Bluetooth: shell: Add examples for the Bluetooth Shell

### LINKED ISSUE #54529: Bluetooth: shell: Missing help messages and parameters
**Describe the bug**

Some commands of the Bluetooth Shell have incomplete/missing help message:
- `adv-create` and `adv-param` does not print mention the `anon` and `tx-power` parameters in their help message;
- `id-create`, `id-reset` and `scan-filter-set` use `addr` as help message when in the other commands that need an address, the help message is printing a nicely formatted address;
- `appearance`, `adv-stop`, `adv-delete` is using an empty string as help message instead of the `HELP_NONE` macro;
-   `oob` is using `NULL` as help message instead of `HELP_NONE` macro;
- `disconnect` print no help but can actually take a parameter (an address);
- `clear` help message is not clear, `all` is a parameter but `addr` is not;
- `scan-filter-set` is defined as a sub command but is not defined properly, thus the help message is confusing.

The `adv-create` and `adv-param` allow the creation of a directed advertiser but does not have a parameter to use RPA for directed advertiser. The `directed-adv` command have a parameter for it `dir-rpa`. The same parameter should be used by `adv-create` and `adv-param`.

**To Reproduce**

Run the Bluetooth Shell in `tests/bluetooth/shell`.

**Expected behavior**

The command should correctly describe their parameters and the help message should be consistent.

**Impact**

The Bluetooth Shell may be hard to use.

### PR DESCRIPTION
**Pull request by theob-pro**
Add examples for the Bluetooth Shell on common use cases.

Also, update the help of some Bluetooth Shell commands to be more consistent.

Link to the compiled documentation: https://builds.zephyrproject.io/zephyr/pr/54124/docs/connectivity/bluetooth/bluetooth-shell.html

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54529

### CODE REVIEW

File: subsys/bluetooth/shell/bt.c [hunk 1]
```diff
@@ -1542,6 +1542,8 @@ static bool adv_param_parse(size_t argc, char *argv[],
 			param->options |= BT_LE_ADV_OPT_FORCE_NAME_IN_AD;
 		} else if (!strcmp(arg, "low")) {
 			param->options |= BT_LE_ADV_OPT_DIR_MODE_LOW_DUTY;
+		} else if (!strcmp(arg, "dir-rpa")) {
+			param->options |= BT_LE_ADV_OPT_DIR_ADDR_RPA;
```
Comment (jori-nordic) [inline subsys/bluetooth/shell/bt.c:1546]: seems this should be in a different commit. or just update the commit message, but it's a functional change not just help text.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 2]
```diff
@@ -0,0 +1,357 @@
+.. _bluetooth_shell:
+
+Bluetooth Shell
+###############
+
+Bluetooth Shell Setup and Usage
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:6]: A small sentence explaining what "Bluetooth Shell" is and what it can be used for.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 3]
```diff
@@ -0,0 +1,357 @@
...
+*******************************
+
+First you need to build and flash your board with the Bluetooth shell. For more details on that,
+look at the :ref:`getting_started`. The Bluetooth shell itself is located in
+:zephyr_file:`tests/bluetooth/shell/`.
+
+When it's done, connect to the CLI using your favorite application. You should be welcomed by the
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:13]: using your favorite serial terminal application

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 4]
```diff
@@ -0,0 +1,357 @@
...
+following prompt:
+
+.. code-block:: console
+
+        uart:~$
+
+For more details on the common usage of the shell, see :ref:`shell_api`.
+
+The first thing you need to do is enable Bluetooth. To do, use :code:`bt init`. Messages should
+confirm you the initialization with a bunch of logging message, if enabled.
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:23]: `Messages should be printed confirming Bluetooth has been initialized.`

Could you also add a small snippet of what a `bt init` call ouptuts?

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 5]
```diff
@@ -0,0 +1,357 @@
...
+
+Identities
+**********
+
+The shell allows the creation of multiple identities, the maximum being set by the Kconfig symbol
+:kconfig:option:`CONFIG_BT_ID_MAX`. To create a new identity, use :code:`bt id-create`. You can then
+use it by selecting it with its ID :code:`bt id-select <id>`. Finally, you can list all the
+identities available with :code:`id-show`.
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:31]: `available identities.`

Could you add another sentence briefly describing the concept of identity? Since we don't really have it anywhere; we will move it when we add stack documentation for it.

Something like:
`Identities are a Zephyr host concept, allowing a single physical device to behave like multiple logical Bluetooth devices.`

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 6]
```diff
@@ -0,0 +1,357 @@
...
+
+Scan for devices
+****************
+
+Start scanning by using :code:`bt scan on`. Depending on the environment you're in, you may see a
+lot of new line on the shell. To stop the scan, run :code:`bt scan off`, the scrolling should stop.
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:37]: you may see a lot of lines printed on the shell.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 7]
```diff
@@ -0,0 +1,357 @@
...
+
+Here is an example of what you could expect:
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:39]: can

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 8]
```diff
@@ -0,0 +1,357 @@
...
+        LE Features: 0x000000000001412f
+        LE PHY updated: TX PHY LE 2M, RX PHY LE 2M
+        LE conn  param req: int (0x0018, 0x0028) lat 0 to 42
+        LE conn param updated: int 0x0028 lat 0 to 42
+
+You can list the active connections of the shell using :code:`bt connections`. The shell maximum
+number of connections is defined by :kconfig:option:`CONFIG_BT_MAX_CONN`. You can disconnect from a
+connection with :code:`bt disconnect <address: XX:XX:XX:XX:XX:XX> <type: (public|random)>`.
+
+On a side note, if you were scanning just before, you can connect to the last scanned device by
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:103]: There is a sphinx tag for notes (`.. note::`), see the getting started .rst for usage.
Suggest removing `on a side note,` and using that tag instead.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 9]
```diff
@@ -0,0 +1,357 @@
...
+.. code-block:: console
+
+        uart:~$ bt adv-stop
+        Advertiser set stopped
+        uart:~$ bt adv-param conn-scan name
+        uart:~$ bt adv-start
+        Advertiser[0] 0x200022f0 set started
+
+You should now see the name of the device in the advertising data. You can also set the advertising
+data manually by using :code:`bt adv-data`. The following example show how to set the advertiser
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:146]: shows

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 10]
```diff
@@ -0,0 +1,357 @@
...
+The data must be formatted according to the Bluetooth Core Specification (see version 5.3, vol. 3,
+part C, 11). In this example, the first octet is the size of the data, the second one is type of
+data, 0x09 being the Complete Local Name and the remaining data are the name in ASCII. So, on the
+other device you should see the name *Bluetooth-Shell*.
+
+Directed Advertising
+====================
+
+It is possible to use directed advertising on the shell if you want to reconnect to a device. The
+following example, demonstrate how to create a directed advertiser. The address is specified right
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:166]: demonstrates

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 11]
```diff
@@ -0,0 +1,357 @@
...
+after the parameter :code:`directed`. The :code:`low` parameter indicates that we want to use the
+low duty cycle mode. :code:`dir-rpa` is required if the remote device has a security level enabling
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:168]: I'm not sure about that, isn't it just if the other device uses privacy?

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 12]
```diff
@@ -0,0 +1,357 @@
...
+        uart:~$ bt fal-add 73:72:82:B4:8F:B9 random
+        uart:~$ bt fal-add 5D:85:50:1C:72:64 random
+        uart:~$ bt scan on fal
+
+You should see only those three addresses reported by the scanner.
+
+Enabling security
+*****************
+
+When connected to a device, you can enable multiple level of security, here is the list for
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:224]: levels

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 13]
```diff
@@ -0,0 +1,357 @@
...
+To enable security, do :code:`bt security <level>`. For levels requiring authentication (level 3 and
+above), you must first set the authentication method, to do it, you can use :code:`bt auth all`.
+After that, when you will set the security level, you will be asked to confirm the passkey on both
+devices. On the shell side, do it with the command :code:`bt auth-passkey-confirm`.
+
+Pairing
+=======
+
+Enabling authentication requires the devices to be bondable. By default the shell is bondable. You
+can make the shell not bondable using :code:`bt bondable off`. You can list all the device you are
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:241]: devices

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 14]
```diff
@@ -0,0 +1,357 @@
...
+paired with :code:`bt bonds`.
+
+The shell has a maximum of paired devices defined by :kconfig:option:`CONFIG_BT_MAX_PAIRED`. You can
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:244]: The maximum number of paired devices is set using ...

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 15]
```diff
@@ -0,0 +1,357 @@
...
+remove a paired device using :code:`bt clear <address: XX:XX:XX:XX:XX:XX> <type: (public|random)>`
+or simply remove all paired device with :code:`bt clear all`.
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:246]: devices

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 16]
```diff
@@ -0,0 +1,357 @@
...
+
+GATT
+****
+
+On the following examples we will assume that you have two devices already connected.
+
+To perform services discovery on the client side, use :code:`gatt discover`. This should show you
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:253]: service discovery
This should print all the services that are available on the GATT server.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 17]
```diff
@@ -0,0 +1,357 @@
...
+
+        uart:~$ log status
+
+* Disabling logging for *bt_hci_core*
+
+.. code-block:: console
+
+        uart:~$ log disable bt_hci_core
+
+* Enable errors logging messages for *bt_att* and *bt_smp*
```
Comment (jori-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:341]: Enable error logs for *bt_att* ..

**Review by jori-nordic — CHANGES_REQUESTED** [review]

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 18]
```diff
@@ -0,0 +1,357 @@
...
+For example, if you want to create a connectable and scannable advertiser and start it:
+
+.. code-block:: console
+
+        uart:~$ bt adv-create conn-scan
+        Created adv id: 0, adv: 0x200022f0
+        uart:~$ bt adv-start
+        Advertiser[0] 0x200022f0 set started
+
+You may notice that with this custom advertiser do not advertise the device name, you need to enable
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:134]:
```suggestion
You may notice that this custom advertiser does not advertise the device name; you need to enable
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 19]
```diff
@@ -0,0 +1,357 @@
...
+it. If we take back from the previous example:
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:135]:
```suggestion
it. Continuing from the previous example:
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst (hunk 9 above)
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:146]:
```suggestion
data manually by using the :code:`bt adv-data` command. The following example shows how to set the advertiser
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 20]
```diff
@@ -0,0 +1,357 @@
...
+.. code-block:: console
+
+        uart:~$ bt adv-create conn-scan
+        Created adv id: 0, adv: 0x20002348
+        uart:~$ bt adv-data 1009426C7565746F6F74682D5368656C6C
+        uart:~$ bt adv-start
+        Advertiser[0] 0x20002348 set started
+
+The data must be formatted according to the Bluetooth Core Specification (see version 5.3, vol. 3,
+part C, 11). In this example, the first octet is the size of the data, the second one is type of
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:158]:
```suggestion
part C, 11). In this example, the first octet is the size of the data, the second one is the type of
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 21]
```diff
@@ -0,0 +1,357 @@
...
+data, 0x09 being the Complete Local Name and the remaining data are the name in ASCII. So, on the
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:159]:
```suggestion
data, ``0x09`` is the Complete Local Name and the remaining data are the name in ASCII. So, on the
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst (hunk 10 above)
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:166]:
```suggestion
following example demonstrates how to create a directed advertiser. The address is specified right
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst (hunk 11 above)
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:168]:
```suggestion
low duty cycle mode. :code:`dir-rpa` is required if the remote device has a security level that enables
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 22]
```diff
@@ -0,0 +1,357 @@
...
+
+        uart:~$ bt adv-create conn-scan directed D7:54:03:CE:F3:B4 random low dir-rpa
+        Created adv id: 0, adv: 0x20002348
+
+After that, you can start the advertiser and then the target device will be able to reconnect.
+
+Extended Advertising
+====================
+
+Let's now have a look at some extended advertising features, to enable extended advertising, use the
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:181]:
```suggestion
Let's now have a look at some extended advertising features. To enable extended advertising, use the
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 23]
```diff
@@ -0,0 +1,357 @@
...
+        uart:~$ bt adv-start
+        Advertiser[0] 0x200022f0 set started
+
+This will create an advertiser, connectable and non scannable.
+
+Filter Accept List
+******************
+
+It's possible to create a list of allowed addresses. That list can be used to
+connect to those addresses automatically, here is how to do it:
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:197]:
```suggestion
It's possible to create a list of allowed addresses that can be used to
connect to those addresses automatically. Here is how to do it:
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 24]
```diff
@@ -0,0 +1,357 @@
...
+
+.. code-block:: console
+
+        uart:~$ bt fal-add 47:38:76:EA:29:36 random
+        uart:~$ bt fal-add 66:C8:80:2A:05:73 random
+        uart:~$ bt fal-connect on
+
+It will then connect to the first available device. In the example, if both devices are advertising
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:205]: Is "It" here "device" or "the shell"? Or something else entirely.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 25]
```diff
@@ -0,0 +1,357 @@
...
+at the same time, we will connect to the first address added to the list.
+
+The Filter Accept List can also be used for scanning or advertising by using the option :code:`fal`.
+For example, if we want to scan for a bunch of selected addresses, we can set up a Filter Accept
+List, like that:
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:210]:
```suggestion
List:
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 26]
```diff
@@ -0,0 +1,357 @@
...
+
+When connected to a device, you can enable multiple level of security, here is the list for
+Bluetooth LE:
+
+* **1** No encryption and no authentication;
+* **2** Encryption and no authentication;
+* **3** Encryption and authentication;
+* **4** Bluetooth LE Secure Connection.
+
+To enable security, do :code:`bt security <level>`. For levels requiring authentication (level 3 and
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:232]:
```suggestion
To enable security, use the :code:`bt security <level>` command. For levels requiring authentication (level 3 and
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 27]
```diff
@@ -0,0 +1,357 @@
...
+above), you must first set the authentication method, to do it, you can use :code:`bt auth all`.
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:233]:
```suggestion
above), you must first set the authentication method. Tto do it, you can use :code:`bt auth all`.
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 28]
```diff
@@ -0,0 +1,357 @@
...
+After that, when you will set the security level, you will be asked to confirm the passkey on both
+devices. On the shell side, do it with the command :code:`bt auth-passkey-confirm`.
+
+Pairing
+=======
+
+Enabling authentication requires the devices to be bondable. By default the shell is bondable. You
+can make the shell not bondable using :code:`bt bondable off`. You can list all the device you are
+paired with :code:`bt bonds`.
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:242]:
```suggestion
paired with the command :code:`bt bonds`.
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst (hunk 15 above)
Comment (wiba-nordic) [reply doc/connectivity/bluetooth/bluetooth-shell.rst:246]:
```suggestion
or remove all paired device with the command :code:`bt clear all`.
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 29]
```diff
@@ -0,0 +1,357 @@
...
+
+The shell has a maximum of paired devices defined by :kconfig:option:`CONFIG_BT_MAX_PAIRED`. You can
+remove a paired device using :code:`bt clear <address: XX:XX:XX:XX:XX:XX> <type: (public|random)>`
+or simply remove all paired device with :code:`bt clear all`.
+
+GATT
+****
+
+On the following examples we will assume that you have two devices already connected.
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:251]:
```suggestion
The following examples assume that you have two devices already connected.
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst (hunk 16 above)
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:253]:
```suggestion
To perform service discovery on the client side, use the :code:`gatt discover` command. This should show you
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 30]
```diff
@@ -0,0 +1,357 @@
...
+
+To perform services discovery on the client side, use :code:`gatt discover`. This should show you
+the all the services on the server.
+
+On the server side, you can register pre-defined test service using :code:`gatt register`. When
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:256]:
```suggestion
On the server side, you can register a pre-defined test service using the :code:`gatt register` command. When
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 31]
```diff
@@ -0,0 +1,357 @@
...
+done, you should see the newly added services on the client side when running the discovery command.
+
+You can now subscribe to those new services on the client side, here is an example on how to
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:259]:
```suggestion
You can now subscribe to those new services on the client side. Here is an example on how to
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 32]
```diff
@@ -0,0 +1,357 @@
...
+subscribe to the test service:
+
+.. code-block:: console
+
+        uart:~$ gatt subscribe 26 25
+        Subscribed
+
+The server can now notify the client with :code:`gatt notify`.
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:267]:
```suggestion
The server can now notify the client with the command :code:`gatt notify`.
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 33]
```diff
@@ -0,0 +1,357 @@
...
+
+Another option available though the GATT command is initiating the MTU exchange, to do it, use
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:269]:
```suggestion
Another option available though the GATT command is initiating the MTU exchange. To do it, use
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 34]
```diff
@@ -0,0 +1,357 @@
...
+:code:`gatt exchange-mtu`. To update the shell maximum MTU you need to update Kconfig symbols in the
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:270]:
```suggestion
the :code:`gatt exchange-mtu` command. To update the shell maximum MTU, you need to update Kconfig symbols in the
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 35]
```diff
@@ -0,0 +1,357 @@
...
+configuration file of the shell. For more details on how to do it, look at the sample
+:ref:`bluetooth_mtu_update_sample`.
+
+L2CAP
+*****
+
+It is possible to use L2CAP commands into the shell. The following example will show you how to
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:277]:
```suggestion
It is possible to use L2CAP commands in the shell. The following example shows you how to
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 36]
```diff
@@ -0,0 +1,357 @@
...
+        Incoming data channel 0x20000210 len 14
+        00000000: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff       |........ ......  |
+        Channel 0x20000210 requires buffer
+        Incoming data channel 0x20000210 len 14
+        00000000: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff       |........ ......  |
+
+Logging
+*******
+
+You can configure the level of logging of each module directly in the shell. To do that use the
```
[the remark this answers is not in the document]
Comment (wiba-nordic) [reply doc/connectivity/bluetooth/bluetooth-shell.rst:326]:
```suggestion
You can configure the logging level per module at runtime. This depends on the maximum logging level that is compiled in. To configure, use the
```

**Review by wiba-nordic — CHANGES_REQUESTED** [review]
There's quite a few requests, but most of them are pretty small or relate to adding "the command" for all commands.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 37]
```diff
@@ -0,0 +1,357 @@
...
+When it's done, connect to the CLI using your favorite application. You should be welcomed by the
+following prompt:
+
+.. code-block:: console
+
+        uart:~$
+
+For more details on the common usage of the shell, see :ref:`shell_api`.
+
+The first thing you need to do is enable Bluetooth. To do, use :code:`bt init`. Messages should
```
[the remark this answers is not in the document]
Comment (theob-pro) [reply doc/connectivity/bluetooth/bluetooth-shell.rst:22]: I am not sure, usually "call" is for functions.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 38]
```diff
@@ -0,0 +1,357 @@
...
+        uart:~$ bt scan-filter-set name "test shell"
+
+Or if you want to look for devices on really close range:
+
+.. code-block:: console
+
+        uart:~$ bt scan-filter-set rssi -40
+        RSSI cutoff set at -40 dB
+
+Finally, if you want to remove all filters:
```
[the remark this answers is not in the document]
Comment (theob-pro) [reply doc/connectivity/bluetooth/bluetooth-shell.rst:74]: You're right, I should add something like that just before the first filter example: "You can add multiple filters by using the commands again."

File: doc/connectivity/bluetooth/bluetooth-shell.rst (hunk 37 above)
[the remark this answers is not in the document]
Comment (wiba-nordic) [reply doc/connectivity/bluetooth/bluetooth-shell.rst:22]: The "command is good for all the uses where I suggested it.

File: doc/connectivity/bluetooth/bluetooth-shell.rst (hunk 24 above)
Comment (theob-pro) [reply doc/connectivity/bluetooth/bluetooth-shell.rst:205]: The device, I will update that.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 39]
```diff
@@ -0,0 +1,389 @@
...
+
+.. code-block:: console
+
+        uart:~$
+
+For more details on general usage of the shell, see :ref:`shell_api`.
+
+The first step is enabling Bluetooth. To do so, use the :code:`bt init` command. Messages should be
+printed confirming Bluetooth has been initialized. The following message is printed to confirm
+Bluetooth has been initialized.
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:27]: There's now two sentences saying the same thing.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 40]
```diff
@@ -0,0 +1,389 @@
...
+remove a paired device using :code:`bt clear <address: XX:XX:XX:XX:XX:XX> <type: (public|random)>`
+or remove all paired devices with the command :code:`bt clear all`.
+
+GATT
+****
+
+The following examples assume that you have two devices already connected.
+
+To perform service discovery on the client side, use the :code:`gatt discover` command. This should
+print all the the services that are available on the GATT server.
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:285]:
```suggestion
print all the services that are available on the GATT server.
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 41]
```diff
@@ -0,0 +1,389 @@
...
+
+On the server side, you can register a pre-defined test services using the :code:`gatt register`
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:287]:
```suggestion
On the server side, you can register pre-defined test services using the :code:`gatt register`
```

**Review by wiba-nordic — CHANGES_REQUESTED** [review]
A couple of typos slipped past.

File: doc/connectivity/bluetooth/bluetooth-shell.rst (hunk 39 above)
Comment (theob-pro) [reply doc/connectivity/bluetooth/bluetooth-shell.rst:27]: Oh yeah oops, sorry 😅

**Review by wiba-nordic — DISMISSED** [review]
Docs are good.

**Review by jori-nordic — DISMISSED** [review]

**Review by alwa-nordic — DISMISSED** [review]
Looks great! Love it!

**Review by carlescufi — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

**Comment by stephanosio** [comment]
@theob-pro Could you open a bug issue briefly describing the problem that the commit "Bluetooth: Small fixes for some Bluetooth Shell commands" is fixing and link to this PR since we have been requiring bug issue for other bug-fix PRs?

**Comment by theob-pro** [comment]
Rebased to:

- Update help message of `adv-create` and `adv-param` commands to add the `anon`, `tx-power` and `scan-report` parameters;
- Update documentation to add a paragraph about active/passive scanning;
- Update documentation to add a paragraph about `scan-reports` in advertiser;
- Update documentation for custom data in advertiser to remove possible misunderstanding on the data size.

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 42]
```diff
@@ -0,0 +1,397 @@
...
+Finally, if you want to remove all filters:
+
+.. code-block:: console
+
+        uart:~$ bt scan-filter-clear all
+
+The command :code:`bt scan on` create an *active* scanner, meaning that the scanner will ask the
+advertisers for more information by sending a *scan request* packet. It is possible to use a
+*passive scanner* by using the :code:`bt scan passive` command, the scanner will so not ask the
+advertiser for more information.
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:107]:
```suggestion
You can use the command :code:`bt scan on` to create an *active* scanner, meaning that the scanner will ask the
advertisers for more information by sending a *scan request* packet. Alternatively, you can create a
*passive scanner* by using the :code:`bt scan passive` command, so the scanner will not ask the
advertiser for more information.
```

**Review by carlescufi — DISMISSED** [review]

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 43]
```diff
@@ -0,0 +1,397 @@
...
+For example, if you want to create a connectable and scannable advertiser and start it:
+
+.. code-block:: console
+
+        uart:~$ bt adv-create conn-scan
+        Created adv id: 0, adv: 0x200022f0
+        uart:~$ bt adv-start
+        Advertiser[0] 0x200022f0 set started
+
+You may notice that with this custom advertiser does not advertise the device name; you need to
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:168]:
```suggestion
You may notice that with this, the custom advertiser does not advertise the device name; you need to
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 44]
```diff
@@ -0,0 +1,397 @@
...
+*Bluetooth-Shell*.
+
+When advertising, if others devices use an *active* scanner, you may receive *scan request* packets.
+To visualize those packets, you can add :code:`scan-reports` to the parameters of your advertiser.
+
+Directed Advertising
+====================
+
+It is possible to use directed advertising on the shell if you want to reconnect to a device. The
+following example, demonstrates how to create a directed advertiser. The address is specified right
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:204]:
```suggestion
following example demonstrates how to create a directed advertiser with the address specified right
```

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 45]
```diff
@@ -0,0 +1,397 @@
...
+after the parameter :code:`directed`. The :code:`low` parameter indicates that we want to use the
+low duty cycle mode. :code:`dir-rpa` is required if the remote device is privacy-enabled and
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:206]:
```suggestion
low duty cycle mode, and the :code:`dir-rpa` parameter is required if the remote device is privacy-enabled and
```

**Review by wiba-nordic — CHANGES_REQUESTED** [review]

**Review by carlescufi — DISMISSED** [review]

File: doc/connectivity/bluetooth/bluetooth-shell.rst [hunk 46]
```diff
@@ -0,0 +1,397 @@
...
+:code:`bt auth all` command. After that, when you will set the security level, you will be asked to
+confirm the passkey on both devices. On the shell side, do it with the command
+:code:`bt auth-passkey-confirm`.
+
+Pairing
+=======
+
+Enabling authentication requires the devices to be bondable. By default the shell is bondable. You
+can make the shell not bondable using :code:`bt bondable off`. You can list all the devices you are
+paired with the command :code:`bt bonds`.
```
Comment (wiba-nordic) [inline doc/connectivity/bluetooth/bluetooth-shell.rst:281]:
```suggestion
paired with using the command :code:`bt bonds`.
```

**Review by wiba-nordic — CHANGES_REQUESTED** [review]
An extra word left over, and noticed two more little improvements.

**Review by carlescufi — APPROVED** [review]

**Review by wiba-nordic — APPROVED** [review]
Looks good.

**Review by jhedberg — APPROVED** [review]
