### PR TITLE
Bluetooth: Host: Fix Periodic Advertising Sync using Advertiser Lists

### LINKED ISSUE #38520: Bluetooth:Host:Scan: "bt_le_per_adv_list_add" function doesn't work
**Describe the bug**
I am trying to develop an application that supports multiple "periodic extended advertisement" based on this sample:
https://docs.zephyrproject.org/latest/samples/bluetooth/direction_finding_connectionless_rx/README.html

By default it only supports one synchronized device at a time, to support multiple device, I tried to use "bt_le_per_adv_list_add" function to add peer device LE address to the periodic advertising list. Also "BT_LE_PER_ADV_SYNC_OPT_USE_PER_ADV_LIST" is added to the options. the final source code of "create_sync" function is:
```
static void create_sync(void)
{
	int err;

	printk("Creating Periodic Advertising Sync...");
	bt_addr_le_copy(&sync_create_param.addr, &per_addr);
	sync_create_param.options = BT_LE_PER_ADV_SYNC_OPT_USE_PER_ADV_LIST;
	sync_create_param.sid = per_sid;
	sync_create_param.skip = 0;
	sync_create_param.timeout = 0xa;
	err = bt_le_per_adv_sync_create(&sync_create_param, &sync);

	err = bt_le_per_adv_list_add(&per_addr, per_sid);
	if (err != 0) {
		printk("add failed (err %d)\n", err);
		return;
	}
	printk("success.\n");
}
```

In the above code, `failed (err -5)` is printed. `bt_le_per_adv_list_add` calls `bt_hci_cmd_send_sync` function which fails by `opcode 0x2047 status 0x01`, where status 0x01 means `BT_HCI_ERR_UNKNOWN_CMD` as defined at [hci_err.h](https://docs.zephyrproject.org/apidoc/latest/hci__err_8h.html)

Indeed, executing the above code, calls `cmd_handle` from [hci_driver.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/controller/hci/hci_driver.c#L542) which consequently calls `hci_cmd_handle` function. The corresponding opcode is "0x2047", so it calls `controller_cmd_handle` from [hci.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/controller/hci/hci.c#L4411) which returns `-EINVAL` because this opcode is not implemented.

**To Reproduce**
1. modify "[Bluetooth: Direction Finding Periodic Advertising Locator](https://docs.zephyrproject.org/latest/samples/bluetooth/direction_finding_connectionless_rx/README.html)" sample as described above.
2. west build -b nrf52833dk_nrf52833
3. west flash

**Expected behavior**
`bt_le_per_adv_list_add` function adds devices to the periodic advertising list as it is described in the [bluetooth.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/bluetooth/bluetooth.h#L1575) header file.

**Impact**
It is not possible to receive advertisement information from more than one AoA tag at the same time.

**Logs and console output**
I have added printk function to some of the above methods to see the errors, result is:
```
*** Booting Zephyr OS build v2.7.0-rc1-100-g50ff77fa910d  ***                                                            
opcode 0x0c03, err:0                                                                                                     
opcode 0x1003, err:0                                                                                                     
opcode 0x1001, err:0                                                                                                     
opcode 0x1002, err:0                                                                                                     
opcode 0x2003, err:0                                                                                                     
opcode 0x201c, err:0                                                                                                     
opcode 0x2058, err:0                                                                                                     
opcode 0x2001, err:0                                                                                                     
opcode 0x0c01, err:0                                                                                                     
opcode 0x2044, err:0                                                                                   
opcode 0x2047, err:-22                                                                                                   
opcode 0x2047 status 0x01                                                                                                
add failed (err -5) 
```

modified files:
hci.c:
```
struct net_buf *hci_cmd_handle(struct net_buf *cmd, void **node_rx)
{
        ...
        if (err == -EINVAL) {
		evt = cmd_status(BT_HCI_ERR_UNKNOWN_CMD);
	}

	printk("opcode 0x%04x, err:%i\n", _opcode, err);

	return evt;
}
```
hci_core.c
```
int bt_hci_cmd_send_sync(uint16_t opcode, struct net_buf *buf,
			 struct net_buf **rsp)
{
    ...
	if (status) {
               ...
		printk("opcode 0x%04x status 0x%02x\n", opcode, status);
               ...
        }
    ...
}
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: 50ff77fa91

**Additional context**
By searching `BT_HCI_OP_LE_ADD_DEV_TO_PER_ADV_LIST` in the project files, you can see it is defined at `hci.h` and only is used by `scan.c` but is not implemented ate any other source file.

### PR DESCRIPTION
**Pull request by cvinayak**
Fix Periodic Advertising Sync Establishment to accept
synchronization establishment to device listed in the
Periodic Advertisers List when filter policy was used.

Fixes #38520.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@saleh-unikie please check if this PR in combination with #38338 fixes #38520

**Comment by saleh-unikie** [comment]
> 
> 
> @saleh-unikie please check if this PR in combination with #38338 fixes #38520

Yes, Thank you!

File: subsys/bluetooth/host/scan.c [hunk 1]
```diff
@@ -694,8 +694,10 @@ void bt_hci_le_per_adv_sync_established(struct net_buf *buf)
 	}
 
 	if (!pending_per_adv_sync ||
-	    pending_per_adv_sync->sid != evt->sid ||
-	    bt_addr_le_cmp(&pending_per_adv_sync->addr, &evt->adv_addr)) {
+	    (!atomic_test_bit(pending_per_adv_sync->flags,
+			     BT_PER_ADV_SYNC_USE_LIST) &&
+	     ((pending_per_adv_sync->sid != evt->sid) ||
+	      bt_addr_le_cmp(&pending_per_adv_sync->addr, &evt->adv_addr)))) {
```
Comment (Thalley) [inline subsys/bluetooth/host/scan.c:700]: The check here is correct, although I wish we could make it a bit more readable, but I don't have any suggestions. 

There's a little bit of indentation that should be fixed 
```suggestion
	    (!atomic_test_bit(pending_per_adv_sync->flags,
			      BT_PER_ADV_SYNC_USE_LIST) &&
	     ((pending_per_adv_sync->sid != evt->sid) ||
	       bt_addr_le_cmp(&pending_per_adv_sync->addr, &evt->adv_addr)))) {
```

File: subsys/bluetooth/host/hci_core.h [hunk 2]
```diff
@@ -156,6 +156,9 @@ enum {
 	/** Periodic Advertising Sync has been created in the host. */
 	BT_PER_ADV_SYNC_CREATED,
 
+	/** Periodic Advertising Sync Create using Advertiser List */
+	BT_PER_ADV_SYNC_USE_LIST,
+
```
Comment (Thalley) [inline subsys/bluetooth/host/hci_core.h:161]:
```suggestion
	/** Periodic advertising is attempting sync sync */ using Advertiser List */
	BT_PER_ADV_SYNC_SYNCING_USE_LIST,
```

And move next to the `BT_PER_ADV_SYNC_SYNCING` flag as those are the most related flags.

**Review by Thalley — CHANGES_REQUESTED** [review]
Looks correct, but a few minor requests

File: subsys/bluetooth/host/scan.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/host/scan.c]: Only line 698 was missing a whitespace, fixed.

File: subsys/bluetooth/host/hci_core.h (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/host/hci_core.h]: Update this and other comments.

**Review by Thalley — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
