### PR TITLE
samples: blinky_pwm: decreased min PWM period for blinky sample

### LINKED ISSUE #38954: Can't get FlexPWM working for imxrt1060
I'm trying the blinky_pwm sample for the teensy4 using the onboard LED. I've added an dt overlay to add the pwm bits which look like:
```
/ {
	pwmleds {
		compatible = "pwm-leds";
		external_pwm_led: external_pwm_led {
			pwms = <&flexpwm1_pwm1 0>;
		};
	};

	aliases {
		pwm-led0 = &external_pwm_led;
	};
};

&flexpwm1_pwm1 {
	status = "okay";
};
```

But i'm getting the following error on the console:

```
*** Booting Zephyr OS build v2.7.0-rc2-54-g2160e0fc364d  ***
PWM-based blinky
Calibrating for channel 0...
[00:00:00.009,000] <err> pwm_mcux: Too long period (1171875), adjust pwm prescaler!
[00:00:00.017,000] <err> pwm_mcux: Too long period (585937), adjust pwm prescaler!
[00:00:00.026,000] <err> pwm_mcux: Too long period (292968), adjust pwm prescaler!
[00:00:00.034,000] <err> pwm_mcux: Too long period (146484), adjust pwm prescaler!
[00:00:00.042,000] <err> pwm_mcux: Too long period (73242), adjust pwm prescaler!
Error: PWM device does not support a period at least 62500
```

### PR DESCRIPTION
**Pull request by danieldegrasse**
Blinky PWM sample minimum pwm period was too high for iMX.RT PWM module.
decrease the minimum pwm period so sample will pass pwm calibration
phase, and successfully run

Fixes #38954

Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>

### CODE REVIEW

**Review by dleach02 — APPROVED** [review]

File: samples/basic/blinky_pwm/src/main.c [hunk 1]
```diff
@@ -27,7 +27,7 @@
 #define PWM_FLAGS	0
 #endif
 
-#define MIN_PERIOD_USEC	(USEC_PER_SEC / 64U)
+#define MIN_PERIOD_USEC	(USEC_PER_SEC / 128U)
```
Comment (MaureenHelm) [inline samples/basic/blinky_pwm/src/main.c:30]: Need to update the README accordingly

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

File: samples/basic/blinky_pwm/src/main.c (hunk 1 above)
Comment (danieldegrasse) [reply samples/basic/blinky_pwm/src/main.c:30]: Thanks for the heads up, just did

**Review by MaureenHelm — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]
