### PR TITLE
drivers: flash controller for the stm32u5 soc serie

### LINKED ISSUE #42478: Unable to build mcuboot for b_u585i_iot02a
**Describe the bug**
Building mcuboot for ST's B-U585I-IOT02A fails.

**To Reproduce**
1.add to \bootloader\mcuboot\boot\zephyr\dts.overlay

&flash0 {
        /*
         * For more information, see:
         * http://docs.zephyrproject.org/latest/guides/dts/index.html#flash-partitions
         */
        partitions {
                compatible = "fixed-partitions";
                #address-cells = <1>;
                #size-cells = <1>;

                boot_partition: partition@0 {
                        label = "mcuboot";
                        reg = <0x00000000 0x10000>;
                };
                slot0_partition: partition@10000 {
                        label = "image-0";
                        reg = <0x00010000 0x20000>;
                };
                slot1_partition: partition@30000 {
                        label = "image-1";
                        reg = <0x00030000 0x50000>;
                };
                scratch_partition: partition@70000 {
                        label = "image-scratch";
                        reg = <0x00070000 0x10000>;
                };
        };
};

2. \zephyrproject\bootloader\mcuboot>west build -p auto -b b_u585i_iot02a boot\zephyr

**Expected behavior**
Build should be OK.

**Impact**
Not able to proceed

**Logs and console output**

-- west build: generating a build system
Including boilerplate (Zephyr base (cached)): C:/OWN/Work/ZEP/zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/boot/zephyr
-- Zephyr version: 3.0.0-rc1 (C:/OWN/Work/ZEP/zephyrproject/zephyr), build: v3.0.0-rc1-247-gf86f6e002510
-- Found west (found suitable version "0.12.0", minimum required is "0.7.1")
-- Board: b_u585i_iot02a
-- Cache files will be written to: C:/OWN/Work/ZEP/zephyrproject/zephyr/.cache
-- Found toolchain: gnuarmemb (C:/gnu_arm_embedded)
-- Found BOARD.dts: C:/OWN/Work/ZEP/zephyrproject/zephyr/boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts
-- Found devicetree overlay: C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/boot/zephyr/dts.overlay
-- Found devicetree overlay: C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/boot/zephyr/dts.overlay
-- Generated zephyr.dts: C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/build/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/build/zephyr/include/generated/device_extern.h
-- Including generated dts.cmake file: C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/build/zephyr/dts.cmake

warning: FLASH_MAP (defined at subsys/storage/flash_map/Kconfig:10) has direct dependencies FLASH_HAS_DRIVER_ENABLED with value n, but is currently being y-selected by the following symbols:
 - MCUBOOT_DEVICE_SETTINGS (defined at C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/boot/zephyr/Kconfig:656), with value y, direct dependencies y (value: y)Parsing C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/boot/zephyr/Kconfig
Loaded configuration 'C:/OWN/Work/ZEP/zephyrproject/zephyr/boards/arm/b_u585i_iot02a/b_u585i_iot02a_defconfig'
Merged configuration 'C:/OWN/Work/ZEP/zephyrproject/bootloader/mcuboot/boot/zephyr/prj.conf'

error: Aborting due to Kconfig warnings

CMake Error at C:/OWN/Work/ZEP/zephyrproject/zephyr/cmake/kconfig.cmake:272 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  C:/OWN/Work/ZEP/zephyrproject/zephyr/cmake/app/boilerplate.cmake:544 (include)
  C:/OWN/Work/ZEP/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  C:/OWN/Work/ZEP/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:40 (include_boilerplate)
  CMakeLists.txt:44 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: 'C:\Program Files\CMake\bin\cmake.EXE' '-DWEST_PYTHON=C:\Python310\python.exe' '-BC:\OWN\Work\ZEP\zephyrproject\bootloader\mcuboot\build' '-SC:\OWN\Work\ZEP\zephyrproject\bootloader\mcuboot\boot\zephyr' -GNinja

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: GNU Arm Embedded Toolchain Version 10.3-2021.10
 -  commit f86f6e00251066815b0a7a7ad45047b525b3fab9 (HEAD -> main, origin/main, origin/HEAD)

### PR DESCRIPTION
**Pull request by FRASTM**
This PR adds the flash controller driver for the stm32U5xx soc
It defines the flash controller node in the DTS
It defines a partition for the flash memory. 
The drivers/flash/flash_stm32u5x.c  is adapted from the drivers/flash/flash_stm32l5x.c
Applicable on the stm32U575/585 devices where the Flash memory is organized as two banks of 1 Mbyte each containing 128 pages of 8 Kbytes ( 137 bits wide data read and write = 128 effective bits plus 9 ECC bits)

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/42478

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
$ west build -p auto -b b_u585i_iot02a tests/drivers/flash
```
*** Booting Zephyr OS build v3.0.0-rc1-252-g7de53a4c47a2  ***                   
Running test suite flash_driver_test                                            
===================================================================             
START - test_setup                                                              
 PASS - test_setup in 0.1 seconds                                               
===================================================================             
START - test_read_unaligned_address                                             
 PASS - test_read_unaligned_address in 0.4 seconds                              
===================================================================             
Test suite flash_driver_test succeeded                                          
===================================================================             
PROJECT EXECUTION SUCCESSFUL 
```

**Comment by FRASTM** [comment]
adding the DTS for the **b_u585i_iot02a_ns** target  with a `image-1-nonsecure` partition

**Comment by FRASTM** [comment]
rebase

File: drivers/flash/flash_stm32u5x.c [hunk 1]
```diff
@@ -0,0 +1,380 @@
...
+	}
+
+	/* Check that no Flash main memory operation is ongoing */
+	rc = flash_stm32_wait_flash_idle(dev);
+	if (rc < 0) {
+		return rc;
+	}
+
+	/* Check if this double word is erased */
+	if ((flash[0] != 0xFFFFFFFFUL) || (flash[1] != 0xFFFFFFFFUL)) {
```
Comment (wcappelle) [inline drivers/flash/flash_stm32u5x.c:159]: just a note: a write will still fail if the ECC is already written.
ECC can be set if a programmer/ previous write was done with 0xFF...FF as data.
Maybe good to add this in the check?

File: drivers/flash/flash_stm32u5x.c [hunk 2]
```diff
@@ -0,0 +1,380 @@
...
+#include "flash_stm32.h"
+
+/* at this time stm32u5 mcus have 1MB (stm32u575) or 2MB (stm32u585) */
+#define STM32U5_SERIES_MAX_FLASH	2048
+#define BANK2_OFFSET	(KB(STM32U5_SERIES_MAX_FLASH) / 2)
+
+#define ICACHE_DISABLE_TIMEOUT_VALUE           1U   /* 1ms */
+#define ICACHE_INVALIDATE_TIMEOUT_VALUE        1U   /* 1ms */
+
+static int stm32u5x_icache_disable(void)
```
Comment (erwango) [inline drivers/flash/flash_stm32u5x.c:30]: I wonder what is the diff vs L5 driver.
If close enough, it would be good to use a single file to ease maintainance.
For instance https://github.com/zephyrproject-rtos/zephyr/pull/42099 may need to be backported on this file also is duplicated

File: drivers/flash/flash_stm32l5_u5.c [hunk 3]
```diff
@@ -0,0 +1,396 @@
...
+			stm32_flash_layout[2].pages_count = PAGES_PER_BANK;
+			stm32_flash_layout[2].pages_size = FLASH_PAGE_SIZE;
+		}
+	} else {
+		/*
+		 * For stm32l562xx & stm32l552xx with 512 KB flash
+		 * or For stm32u58x with 2MB flash
+		 */
+
+		if (stm32_flash_layout[0].pages_count == 0) {
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/flash/flash_stm32l5_u5.c:387]: @wcappelle could you please detail what you mean, I do not catch your comment

File: drivers/flash/flash_stm32.h [hunk 4]
```diff
@@ -53,6 +53,19 @@ struct flash_stm32_priv {
...
+#define FLASH_NSCR_NSPG FLASH_NSCR_PG
+#define FLASH_NSCR_NSBKER_Msk FLASH_NSCR_BKER_Msk
+#define FLASH_NSCR_NSBKER FLASH_NSCR_BKER
+#define FLASH_NSCR_NSPER FLASH_NSCR_PER
+#define FLASH_NSCR_NSPNB_Msk FLASH_NSCR_PNB_Msk
+#define FLASH_NSCR_NSPNB_Pos FLASH_NSCR_PNB_Pos
+#define FLASH_NSCR_NSPNB FLASH_NSCR_PNB
+#define FLASH_NSCR_NSSTRT FLASH_NSCR_STRT
+#endif /* CONFIG_SOC_SERIES_STM32U5X */
+
```
Comment (erwango) [inline drivers/flash/flash_stm32.h:68]: For clarity, if we need to provide zephyr specific abstraction on top of Cube apis, avoid re-using Cube definition and create zephyr specific ones.

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/flash/flash_stm32.h (hunk 4 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32.h]: the fact is that FLASH_NSCR_NSLOCK is in the flash_stm32.c or FLASH_NSCR_NSPNB_Msk in the flash_stm32l5x.c etc

File: dts/arm/st/u5/stm32u5.dtsi [hunk 5]
```diff
@@ -83,8 +84,8 @@
 	};
 
 	soc {
-		flash-controller@40022000 {
-			compatible = "st,stm32u5-flash-controller";
+		flash: flash-controller@40022000 {
+			compatible = "st,stm32-flash-controller", "st,stm32wb-flash-controller";
```
Comment (erwango) [inline dts/arm/st/u5/stm32u5.dtsi:88]: stm32wb ?

File: drivers/flash/flash_stm32l5_u5.c [hunk 6]
```diff
@@ -0,0 +1,405 @@
+/*
```
Comment (erwango) [inline drivers/flash/flash_stm32l5_u5.c:1]: I wonder why this is appearing as a new file introduction.
Maybe you need to remove the L5 one ?

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
rebase on ae71444426a07a918ff82132e046e90d05093725
deleting flash_stm32l5.c

File: boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts [hunk 7]
```diff
@@ -24,3 +24,38 @@
 		sw0 = &user_button;
 	};
 };
+
+&flash0 {
+	/*
+	 * For more information, see:
+	 * https://docs.zephyrproject.org/latest/reference/devicetree/index.html#fixed-flash-partitions
+	 */
```
Comment (erwango) [inline boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts:32]: Please remove this

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/flash/flash_stm32.h (hunk 4 above)
Comment (erwango) [reply drivers/flash/flash_stm32.h]: Yes

File: boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts (hunk 7 above)
Comment (erwango) [reply boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts:32]: cf https://github.com/zephyrproject-rtos/zephyr/pull/43882

File: drivers/flash/flash_stm32.h (hunk 4 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32.h]: The FLASH_NSCR_LOCK is the name of the bit registered in the stm32CUbe/stm32l5x HAL
Changing FLASH_NSCR_LOCK to FLASH_STM32_NSCR_LOCK in the zephyr driver means 
  a change in the drivers/flash/stm32_flash.h and also updating drivers/flash/flash_stm32l5x.c, drivers/flash/flash_stm32g4x.c and drivers/flash/flash_stm32l4x

Comment (FRASTM) [reply drivers/flash/flash_stm32.h]: cf commit 4a94eedbc1a428f1013a662a318022a6d5499eb9

File: boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts (hunk 7 above)
Comment (FRASTM) [reply boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts:32]: removed

**Comment by FRASTM** [comment]
add a commit 4a94eedbc1a428f1013a662a318022a6d5499eb9 to change FLASH_STM32_xx bitfield

File: drivers/flash/flash_stm32.h (hunk 4 above)
Comment (erwango) [reply drivers/flash/flash_stm32.h]: I agree this is not straightforward but we should keep each level of abstraction clear. Otherwise this will lead to confusion in the end (if this is spreading in other drivers)
Alternatives are:
- get CMSIS definitions fixed (but LL is here to provide CMSIS abstraction)
- convert whole driver to use of LL

**Comment by FRASTM** [comment]
rebase on 574e166e1357641cb80dda00ff0a01096b6695a0
reorder commits
fix compilation error on some l4 boards

File: drivers/flash/Kconfig.stm32 [hunk 8]
```diff
@@ -7,7 +7,7 @@
 config SOC_FLASH_STM32
 	bool "STM32 flash driver"
 	depends on SOC_FAMILY_STM32
-	depends on (SOC_SERIES_STM32F0X || SOC_SERIES_STM32F1X || SOC_SERIES_STM32F2X || SOC_SERIES_STM32F3X || SOC_SERIES_STM32F4X || SOC_SERIES_STM32F7X || SOC_SERIES_STM32L0X  || SOC_SERIES_STM32L1X || SOC_SERIES_STM32L4X || SOC_SERIES_STM32L5X || SOC_SERIES_STM32WBX || SOC_SERIES_STM32WLX || SOC_SERIES_STM32G0X || SOC_SERIES_STM32G4X || SOC_SERIES_STM32H7X)
+	depends on (SOC_SERIES_STM32F0X || SOC_SERIES_STM32F1X || SOC_SERIES_STM32F2X || SOC_SERIES_STM32F3X || SOC_SERIES_STM32F4X || SOC_SERIES_STM32F7X || SOC_SERIES_STM32L0X  || SOC_SERIES_STM32L1X || SOC_SERIES_STM32L4X || SOC_SERIES_STM32L5X || SOC_SERIES_STM32U5X || SOC_SERIES_STM32WBX || SOC_SERIES_STM32WLX || SOC_SERIES_STM32G0X || SOC_SERIES_STM32G4X || SOC_SERIES_STM32H7X)
```
Comment (erwango) [inline drivers/flash/Kconfig.stm32:10]: Not blocking: would be nice to replace this line by a :
```
DT_COMPAT_ST_STM32_FLASH_CONTROLLER := st,stm32-flash-controller
[...]
	depends on $(dt_compat_enabled,$(DT_COMPAT_ST_STM32_FLASH_CONTROLLER))
```

File: drivers/flash/flash_stm32l5_u5.c [hunk 9]
```diff
@@ -15,18 +15,30 @@ LOG_MODULE_REGISTER(LOG_DOMAIN);
 #include <drivers/flash.h>
 #include <init.h>
 #include <soc.h>
+#if defined(CONFIG_SOC_SERIES_STM32L5X)
 #include <stm32l5xx_ll_icache.h>
+#endif
+#if defined(CONFIG_SOC_SERIES_STM32U5X)
+#include <stm32u5xx_ll_icache.h>
+#endif
+
```
Comment (erwango) [inline drivers/flash/flash_stm32l5_u5.c:24]: Could be replaced by #include <stm32_ll_icache.h>

File: boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts [hunk 10]
```diff
@@ -24,3 +24,34 @@
 		sw0 = &user_button;
 	};
 };
+
+&flash0 {
+	partitions {
+		compatible = "fixed-partitions";
```
Comment (erwango) [inline boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts:30]: Let's add a comment specifying that this partition is dedicated to the use of b_u585i_iot02a target with TZEN=0 (so w/o TFM)

File: tests/drivers/flash/boards/b_u585i_iot02a.overlay [hunk 11]
```diff
@@ -0,0 +1,11 @@
+/*
+ * Copyright (c) 2022 STMicroelectronics
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/ {
+	chosen {
+		zephyr,code-partition = &slot0_partition;
+	};
```
Comment (erwango) [inline tests/drivers/flash/boards/b_u585i_iot02a.overlay:10]: Why not putting this directly in board.dts ?

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/flash/Kconfig.stm32 (hunk 8 above)
Comment (erwango) [reply drivers/flash/Kconfig.stm32:10]: Note: This might need some tests. I'm not sure how this will behave when there is no flash controller available for the target.

Comment (FRASTM) [reply drivers/flash/Kconfig.stm32:10]: ok

File: boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts (hunk 10 above)
Comment (FRASTM) [reply boards/arm/b_u585i_iot02a/b_u585i_iot02a.dts:31]: ok

**Comment by FRASTM** [comment]
with optimized Kconfig writing and dts

File: drivers/flash/Kconfig.stm32 (hunk 8 above)
Comment (FRASTM) [reply drivers/flash/Kconfig.stm32]: with a special case for H7 : `DT_COMPAT_ST_STM32H7_FLASH_CONTROLLER := st,stm32h7-flash-controller`

File: drivers/flash/flash_stm32.h [hunk 12]
```diff
@@ -54,18 +54,31 @@ struct flash_stm32_priv {
 
 /* Redefinitions of flags and masks to harmonize stm32 series: */
 #if defined(CONFIG_SOC_SERIES_STM32U5X)
-#define FLASH_NSCR_NSLOCK FLASH_NSCR_LOCK
-#define FLASH_OPTR_DBANK FLASH_OPTR_DUALBANK
-#define FLASH_NSCR_NSPG FLASH_NSCR_PG
-#define FLASH_NSCR_NSBKER_Msk FLASH_NSCR_BKER_Msk
```
Comment (erwango) [inline drivers/flash/flash_stm32.h]: This whole part should ideally be moved into initial commit "drivers: flash stm32 flash driver includes stm32u5 serie".
But I agree this require a full rework of the PR, so ok to keep it that way.

**Review by erwango — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
Merging since @nvlsianpu is on leave
