### PR TITLE
bluetooth: Add bt_disable(), hci.close() and its implementation on stm32wb

### LINKED ISSUE #41944: Assertion triggered when system is going to PM_STATE_SOFT_OFF
**Describe the bug**
When I try to switch to SHUTDOWN mode using applicatiom PM policy then there is triggered system assertion from `sched.c`.
The call stack reveals that there is scheduled semaphore waiting from the idle thread and it is not allowed.
Platform: STM32WB55
 
Call stack:
z_priq_rb_add -> __ASSERT_NO_MSG(!z_is_idle_thread_object(thread))
add_to_waitq_locked
pend
z_pend_curr
z_impl_k_sem_take
k_sem_take
bt_hci_cmd_send_sync
send_stack_reset
shutdown_ble_stack
pm_power_state_set
pm_state_set
pm_system_suspend
idle

**To Reproduce**
1. Request system to switch to PM_STATE_SOFT_OFF on STM32WB55

**Expected behavior**
No assertion should be triggered when system try to switch to PM_STATE_SOFT_OFF.

**Impact**
showstopper

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA e8df8a579033be238beb774e4909d637da649f3a

**Additional context**

### PR DESCRIPTION
**Pull request by erwango**
In order to allow shuting down C2 core on stm32wb SoCs, an application callable function is required to properly executing the required procedure from HCI IPM driver (see #41944).

Propose a `bt_disable()` function, together with a hci `close()` implementation to achieve this.

STM32 dedicated sample has been updated to demonstrate:
- bt_disable() successful behavior
- bt_enable() could be successfully applied after bt_disable() was performed

Likely deserves some polishing:
- bt dedicated tests update
- API documentation clarification
- Check on the correctness of changes applied to BT_DEV_ENABLE/BT_DEV_DISABLE flags

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/41944 (Instead of https://github.com/zephyrproject-rtos/zephyr/pull/42309)

Based on:
- ~~#42274~~ (merged)
- ~~#42368~~ (merged)

### CODE REVIEW

**Comment by erwango** [comment]
^^ @r2r0 in place of https://github.com/zephyrproject-rtos/zephyr/pull/42309

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -3641,6 +3641,46 @@ int bt_enable(bt_ready_cb_t cb)
...
+		return -ENODEV;
+	}
+
+	atomic_clear_bit(bt_dev.flags, BT_DEV_ENABLE);
+
+	if (atomic_test_and_set_bit(bt_dev.flags, BT_DEV_DISABLE)) {
+		return -EALREADY;
+	}
+
+	err = bt_dev.drv->close();
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:3659]: You can't assume that drivers implement a `close()` callback. This is important for backwards compatibility, and also if a `close()` callback doesn't make sense for some drivers (possibly most of them). So you should probably have a check right after the `if (!bt_dev.drv)` check:
```c
if (!bt_dev.drv->close) {
	return -ENOTSUP;
}
```

Comment (erwango) [reply subsys/bluetooth/host/hci_core.c:3663]: Nice, sure. Added.

File: subsys/bluetooth/host/hci_core.c [hunk 2]
```diff
@@ -3641,6 +3641,50 @@ int bt_enable(bt_ready_cb_t cb)
...
+
+	atomic_clear_bit(bt_dev.flags, BT_DEV_ENABLE);
+
+	if (atomic_test_and_set_bit(bt_dev.flags, BT_DEV_DISABLE)) {
+		return -EALREADY;
+	}
+
+	if (!bt_dev.drv->close) {
+		return -ENOTSUP;
+	}
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:3661]: You need to have this check before making any state modifications, i.e. you need to move it before clearing `BT_DEV_ENABLE`.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/hci_core.c (hunk 2 above)
Comment (erwango) [reply subsys/bluetooth/host/hci_core.c]: Right, fixed.

**Comment by r2r0** [comment]
I see "Bluetooth disable failed (err -120)" message as the result of the latest `bt_disable` call.
After adding `atomic_clear_bit(bt_dev.flags, BT_DEV_DISABLE);` at the begining of `bt_init` everything looks Ok.

**Comment by erwango** [comment]
> I see "Bluetooth disable failed (err -120)" message as the result of the last `bt_disable` call. After adding `atomic_clear_bit(bt_dev.flags, BT_DEV_DISABLE);` at the begining of `bt_init` everything looks Ok.

Thanks @r2r0. I had it fixed originally, but apparently I somehow lost it during a rebase. Setting it back (in `bt_enable` to keep symetry with mnagement of `BT_DEV_ENABLE` flag).

**Comment by erwango** [comment]
Rebased after https://github.com/zephyrproject-rtos/zephyr/pull/42274 was merged.

**Comment by erwango** [comment]
Rebased, following merge of https://github.com/zephyrproject-rtos/zephyr/pull/42368

File: subsys/bluetooth/host/hci_core.c [hunk 3]
```diff
@@ -3641,6 +3643,50 @@ int bt_enable(bt_ready_cb_t cb)
...
+	k_thread_abort(&rx_thread_data);
+#endif
+
+	if (IS_ENABLED(CONFIG_BT_TINYCRYPT_ECC)) {
+		bt_hci_ecc_deinit();
+	}
+
+	bt_monitor_send(BT_MONITOR_CLOSE_INDEX, NULL, 0);
+
+	atomic_set_bit(bt_dev.flags, BT_DEV_DISABLE);
```
Comment (ceolin) [inline subsys/bluetooth/host/hci_core.c:3685]: wasn't is already set in line 3661 ? Probably you should just check there and set the bit here ...

File: subsys/bluetooth/host/hci_core.c [hunk 4]
```diff
@@ -3641,6 +3643,50 @@ int bt_enable(bt_ready_cb_t cb)
...
+	if (!bt_dev.drv) {
+		BT_ERR("No HCI driver registered");
+		return -ENODEV;
+	}
+
+	if (!bt_dev.drv->close) {
+		return -ENOTSUP;
+	}
+
+	atomic_clear_bit(bt_dev.flags, BT_DEV_ENABLE);
```
Comment (ceolin) [inline subsys/bluetooth/host/hci_core.c:3659]: shouldn't it be done in the end of this function ? Otherwise another thread can call `bt_enable()` while this one is still disabling it ...

File: subsys/bluetooth/host/hci_core.h [hunk 5]
```diff
@@ -29,6 +29,7 @@ enum {
 /* bt_dev flags: the flags defined here represent BT controller state */
 enum {
 	BT_DEV_ENABLE,
+	BT_DEV_DISABLE,
```
Comment (ceolin) [inline subsys/bluetooth/host/hci_core.h:32]: Is this  necessary ? Couldn't enable / disable be controlled by one single bit ?

Comment (erwango) [reply subsys/bluetooth/host/hci_core.h:32]: Having a DISABLE bit prevents hci.close() reentry which is something required as this can involve complex procedure like communication with another core.

File: subsys/bluetooth/host/hci_core.c (hunk 3 above)
Comment (erwango) [reply subsys/bluetooth/host/hci_core.c:3685]: Thanks, fixed

File: subsys/bluetooth/host/hci_core.c (hunk 4 above)
Comment (erwango) [reply subsys/bluetooth/host/hci_core.c:3659]: Makes sense, moved.

**Comment by erwango** [comment]
@jhedberg, @ceolin  Thanks for the review, I hope I addressed all the comments.

Btw, I'm getting an error in Bluetooth tests, it doesn't seems linked and I'm not sure what to do about it
`tests/bluetooth/bsim_bt/bsim_test_mesh/tests_scripts/provision/pb_adv_reprovision.sh FAILED`

File: samples/boards/stm32/power_mgmt/stm32wb_ble/src/main.c [hunk 6]
```diff
@@ -116,7 +124,27 @@ void main(void)
...
+	printk("BLE disable\n");
+
+	err = bt_disable();
+	if (err) {
+		printk("Bluetooth disable failed (err %d)\n", err);
+	}
+
+	printk("BLE restart\n");
+	/* Initialize the Bluetooth Subsystem */
+	err = bt_enable(bt_ready);
```
Comment (ceolin) [inline samples/boards/stm32/power_mgmt/stm32wb_ble/src/main.c:136]: nitpick. It should check `err` value.

File: subsys/bluetooth/host/hci_core.h (hunk 5 above)
Comment (ceolin) [reply subsys/bluetooth/host/hci_core.h:32]: :+1:

**Review by ceolin — DISMISSED** [review]

**Comment by erwango** [comment]
@ceolin Your review were dismissed when fixing the remark. Would you mind approving again ?

**Review by ceolin — DISMISSED** [review]

File: subsys/bluetooth/host/hci_core.c [hunk 7]
```diff
@@ -3627,6 +3629,49 @@ int bt_enable(bt_ready_cb_t cb)
...
+	k_thread_abort(&rx_thread_data);
+#endif
+
+	if (IS_ENABLED(CONFIG_BT_TINYCRYPT_ECC)) {
+		bt_hci_ecc_deinit();
+	}
+
+	bt_monitor_send(BT_MONITOR_CLOSE_INDEX, NULL, 0);
+
+	atomic_clear_bit(bt_dev.flags, BT_DEV_ENABLE);
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:3669]: I just took a look at #41424 and it's adding an API For checking BT_DEV_READY instead of BT_DEV_ENABLE. How do these relate? It seems that either this or that PR should be changed (ping @JordanYates), since if we don't clear BT_DEV_READY then the new `bool bt_dev_ready(void);` API that @JordanYates adds wouldn't work with `bt_disable()` as added here.

Comment (JordanYates) [reply subsys/bluetooth/host/hci_core.c:3669]: Clearing `BT_DEV_READY` should definitely be done. Most Bluetooth API's are checking whether `BT_DEV_READY` is set, not `BT_DEV_ENABLE`.

Comment (erwango) [reply subsys/bluetooth/host/hci_core.c:3673]: @jhedberg I've added BT_DEV_READY clearing.

Comment (erwango) [reply subsys/bluetooth/host/hci_core.c:3673]: @jhedberg I've fixed the point.

File: subsys/bluetooth/host/hci_core.c [hunk 8]
```diff
@@ -3627,6 +3629,53 @@ int bt_enable(bt_ready_cb_t cb)
...
+	}
+
+	/* Clear BT_DEV_READY before disabling HCI link */
+	atomic_clear_bit(bt_dev.flags, BT_DEV_READY);
+
+	err = bt_dev.drv->close();
+	if (err) {
+		BT_ERR("HCI driver close failed (%d)", err);
+		return err;
+	}
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:3656]: Won't this leave the stack in an inconsistent and unrecoverable state? You've cleared the `BT_DEV_READY` flag, but not the `BT_DEV_ENABLE` flag. Should the `BT_DEV_READY` be re-enabled in this error branch?

Comment (erwango) [reply subsys/bluetooth/host/hci_core.c:3656]: Indeed, this is probably safer to set it back. Done

**Comment by erwango** [comment]
> @erwango which parts do you still consider of "RFC" quality? I'll do one final review when you think "RFC" can be removed (I don't have anything to object to at this point)

@jhedberg RFC removed. I've also fixed the last BT_DEV_READY comment. Thanks for the review.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 9]
```diff
@@ -540,41 +584,54 @@ static int bt_ipm_open(void)
...
+	struct net_buf *rsp;
+
+	err = bt_hci_cmd_send_sync(ACI_HAL_STACK_RESET, NULL, &rsp);
+
+	net_buf_unref(rsp);
+
+	if (err) {
+		BT_ERR("IPM Channel Close Issue");
+		return err;
+	}
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c:599]: If `bt_hci_cmd_send_sync()` returns an error, the `rsp` buffer will be undefined (not set), so the unconditional `net_buf_unref(rsp)` is wrong. You might want to check if you have similar faulty patterns elsewhere in the driver.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 9 above)
Comment (erwango) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Fixed, thanks. Other usages of `bt_hci_cmd_send_sync()` were actually correct.

**Review by jhedberg — APPROVED** [review]

**Comment by erwango** [comment]
@ceolin Would you mind re-re-approving ?

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 10]
```diff
@@ -65,6 +65,7 @@ struct aci_set_ble_addr {
 
 #define ACI_WRITE_SET_TX_POWER_LEVEL       BT_OP(BT_OGF_VS, 0xFC0F)
 #define ACI_HAL_WRITE_CONFIG_DATA	   BT_OP(BT_OGF_VS, 0xFC0C)
+#define ACI_HAL_STACK_RESET		   BT_OP(BT_OGF_VS, 0xFC3B)
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c:68]: @erwango btw, I noticed that `drivers/bluetooth/hci/spi.c` also has these defines:https://github.com/zephyrproject-rtos/zephyr/blob/3cbfc505b357f80b6aca4cd2dc39c0f60a24c1b1/drivers/bluetooth/hci/spi.c#L106-L109

Perhaps they should be moved into a common header file?

It also seems like the defines here in `ipm_stm32wb.c` have slightly different values - I think the `0xFC..` part of the OCF is redundant, since that'll come from the OGF value when combined with it.

**Review by ceolin — APPROVED** [review]
