### PR TITLE
fs: Fix null pointer exception caused by async fs_unmount

### LINKED ISSUE #73501: fs.c null pointer exception when doing file i/o in a thread, and fs_unmount in another thread.
fs.c is not thread safe, it has a mutex around the mount list to give the illusion that it is thread safe, but it is not sufficient.

**Describe the bug**
I have an stm32h7 target running zephyr with a usb host stack that supports mass storage devices with fatfs. I have a thread that wakes up when the mass storage is removed from the system and invokes fs_unmount() when the device is removed. Other threads do file io with fs_open(), fs_write(), fs_close() as follows:

```
void write_data()
{
	static uint32_t buf[256] __nocache;
	fs_file_t file;
	fs_file_t_init(&file);
	if(fs_open(&file, "/USB:/output.bin", FS_O_CREATE | FS_O_WRITE) == 0)
	{
		printk("file open\n\r");
		for(int i = 0; i < (((1024 * 1024) * 1024) / sizeof(buf)); i++)
		{
			for(int x = 0; x < ARRAY_SIZE(buf); x++)
			{
				buf[x] = i;
			}
			if(fs_write(&file, buf, sizeof(buf)) != sizeof(buf))
			{
				printk("Write failed %i\n\r", i);
				break;
			}
		}
		fs_close(&file);
		printk("done\n\r");
	}
	else
	{
		printk("open failed\n\r");
	}
}

```
If this function is running in thread X and I remove the usb stick, and fs_unmount is invoked from another thread, then most frequently what happens is the fs_write fails and returns an error as expected, the loop breaks, fs_close is invoked and a null pointer is dereferenced. zfp->mp->fs = NULL. because fs_unmount sets mp->fs = NULL. It is my opinion that the fs API needs to be fully mutex protected, and the fs pointers must be NULL checked before dereference to protect in this case. This should be done in all functions that invoke fs specific calls.

### PR DESCRIPTION
**Pull request by cdesjardins**
If fs_unmount is invoked while fs i/o is ongoing then it will cause a NULL pointer exception due to the unchecked and unprotected dereference of the fs pointer.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/73501

### CODE REVIEW

File: subsys/fs/fs.c [hunk 1]
```diff
@@ -130,7 +130,7 @@ static int fs_get_mnt_point(struct fs_mount_t **mnt_pntp,
 }
 
 /* File operations */
-int fs_open(struct fs_file_t *zfp, const char *file_name, fs_mode_t flags)
+static int _fs_open(struct fs_file_t *zfp, const char *file_name, fs_mode_t flags)
```
Comment (pdgendt) [inline subsys/fs/fs.c:133]: Function names should avoid starting with underscores IMO. Maybe `fs_open_locked` shows the intent.

Also maybe add `ALWAYS_INLINE` to avoid the additional stack frame.

**Comment by de-nordic** [comment]
This should be configurable by user as it is up to user setup, mostly, where mounted fs is used by more than one thread.
Users that do not have the issue should be able to turn off the feature as it adds code and impacts execution paths.

File: subsys/fs/fs.c [hunk 2]
```diff
@@ -336,13 +407,8 @@ int fs_opendir(struct fs_dir_t *zdp, const char *abs_path)
 
 	if (strcmp(abs_path, "/") == 0) {
 		/* Open VFS root dir, marked by zdp->mp == NULL */
-		k_mutex_lock(&mutex, K_FOREVER);
```
Comment (de-nordic) [inline subsys/fs/fs.c:339]: This is not correct mutext to use. This one is used for protecting mount points so that when path to FS is figured out the mount list do not get removed/added.
Using this mutex for ops like fs_open means that you are globally locking VFS to perform operation of some mount point, so if you take a lot of time to write to one mount point the other thread has to wait on own fs_ op, even if that is applied to different mount point.

**Comment by cdesjardins** [comment]
Thanks for your comments, and indeed I believe there is a much simpler solution which I have tested on my platform and pushed.

**Comment by de-nordic** [comment]
> Thanks for your comments, and indeed I believe there is a much simpler solution which I have tested on my platform and pushed.

The issue you have logged is still correc.

File: subsys/fs/fs.c [hunk 3]
```diff
@@ -791,9 +791,6 @@ int fs_unmount(struct fs_mount_t *mp)
 		goto unmount_err;
 	}
 
-	/* clear file system interface */
```
Comment (de-nordic) [inline subsys/fs/fs.c:794]: I understand that this fixes problem with NULL pointer exception but unfortunately now systems continue write to system that is no longer valid.

Comment (cdesjardins) [reply subsys/fs/fs.c:794]: In my testing the i/o errors out and returns an error code, which is a huge improvement over the NULL pointer exception.

**Comment by MaureenHelm** [comment]
@de-nordic please revisit

File: subsys/fs/fs.c (hunk 3 above)
Comment (de-nordic) [reply subsys/fs/fs.c:794]: Remove the "Fixes https://github.com/zephyrproject-rtos/zephyr/issues/73501" from commit and description as this does not fix the problem, it only makes it manifest in a less violent way.

Comment (cdesjardins) [reply subsys/fs/fs.c:794]: But it does fix "the problem", which is NULL pointer dereference caused by a user removing a usb drive during file i/o.

Comment (bas-archembedded) [reply subsys/fs/fs.c:794]: @de-nordic  Please check https://github.com/zephyrproject-rtos/zephyr/pull/78018 as an alternative.

**Review by de-nordic — APPROVED** [review]
OK, let it be.
It still does not make the FS thread safe, but reduces fallout from unmounting system somebody else is using.

A proper way would be to not allow unmounting system being used by somebody else
I think that https://github.com/zephyrproject-rtos/zephyr/pull/78018 may deliver that, once completed.

**Review by pdgendt — APPROVED** [review]
