### PR TITLE
logging: Prevent multiple arguments evaluation (take 2)

### LINKED ISSUE #42050: printk bug: A function called from printk is invoked three times given certain configuration variables
**Describe the bug**
Calling a function from a printk statement invokes the function three times.

This depends on having both of these two configuration variables set true: 
```
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
```

**To Reproduce**
prj.conf:
```
CONFIG_NEWLIB_LIBC=y
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
```
main.c:
```#include <zephyr.h>
#include <stdio.h>
#include <stdlib.h>

static int my_int = 0;
int my_func(void){
	my_int++;
	printf("\t\t in my_func; my_int=%d\n",my_int);
	return my_int;
}

void main(void)
{
	printf("\n testing printf\n");
	printf("\t printf: value returned by my_func: %d\n", my_func());
	printf("\n testing printk\n");
	printk("\t printk: value returned by my_func: %d\n", my_func());
}
```
build:
```
source ~/zephyr/zephyr/zephyr-env.sh
west build -b native_posix
west build -t run
```
output:
```
*** Booting Zephyr OS build v2.7.99-3561-g25e6803705b2  ***

 testing printf
		 in my_func; my_int=1
	 printf: value returned by my_func: 1

 testing printk
		 in my_func; my_int=2
		 in my_func; my_int=3
		 in my_func; my_int=4
	 printk: value returned by my_func: 4

```
**Expected behavior**
I expect the function to be invoked only once. This is the case with either CONFIG_LOG=n or CONFIG_LOG_PRINTK=n:

prj.conf:
```
CONFIG_NEWLIB_LIBC=y
CONFIG_LOG=n
CONFIG_LOG_PRINTK=y
```
output:
```
*** Booting Zephyr OS build v2.7.99-3561-g25e6803705b2  ***

 testing printf
		 in my_func; my_int=1
	 printf: value returned by my_func: 1

 testing printk
		 in my_func; my_int=2
	 printk: value returned by my_func: 2
```

**Impact**
It confused the hell out of me. I only discovered it because I had a left-over print statement in a function being called from LOG_INF. 

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: ~/gnuarmemb/gcc-arm-none-eabi-9-2019-q4-major
 - Version: Zephyr OS build v2.7.99-3561-g25e6803705b2

**Additional context**
My target microcontroller is the nrf52840. I get the same unexpected behavior when building and running on nrf52840dk.

This unexpected behavior also occurs with the LOGGING module, which I'm guessing uses printk.

**The test program**
[test_printk.zip](https://github.com/zephyrproject-rtos/zephyr/files/7915256/test_printk.zip)

### LINKED ISSUE #43016: Self inc/dec works incorrectly with logging API.
**Describe the bug**
When using logging API with self inc/dec operation, the increased/decreased value is incorrect.

**To Reproduce**
1. Download the code from here: https://github.com/smrtos/zephyr_rtos_bug_repro/tree/main/SelfIncInLoggingApi

```
void main(void)
{
    LOG_INF("hello, main()\n");
    volatile int32_t ii = 0;


    while (ii < 100)
    {
        // bad one
        LOG_INF("hello, logger %d\n", ii++);

        // good one
        //LOG_INF("hello, logger %d\n", ii);
        //ii++;
    }

}
```

2. Build it for qemu_x86_64.
3. Run the app in qemu.

**Expected behavior**
100 logs should be printed. Like this:

```
[00:00:00.049,635] <inf> main: hello, main()

[00:00:00.052,334] <inf> main: hello, logger 0

[00:00:00.053,610] <inf> main: hello, logger 1

[00:00:00.054,293] <inf> main: hello, logger 2

....

```

**Actual behavior**

```
[00:00:00.049,154] <inf> main: hello, main()

[00:00:00.051,420] <inf> main: hello, logger 2 // <============= the value is increased too much

[00:00:00.052,509] <inf> main: hello, logger 5

[00:00:00.053,200] <inf> main: hello, logger 8

[00:00:00.053,872] <inf> main: hello, logger 11

...
```

**Impact**
Customer cannot use self inc/dec in logging API.

**Investigation**
I checked the preprocessed file and debugged through it. It  showed that the macro expansion in logging infrastructure introduced some extra/unwanted execution of the self inc/dec statement.

### PR DESCRIPTION
**Pull request by nordic-krch**
This is another attempt to fix #42050. First attempt (#42165) was reverted (#42609) due to #42608. Test was failing because of increased stack usage after changes in logging. Increased stack usage has been seen in `CONFIG_NO_OPTIMIZATIONS=y` case.

In this take, logging macro path has been changed so that runtime packaging (the one without preprocessor magic and multiple arguments evaluation) is used always when `CONFIG_NO_OPTIMIZATIONS=y` or `CONFIG_LOG_MODE_IMMEDIATE=y`. In both cases static packaging is not needed since static packaging is used to get best performance and with those two options enabled it is not a case. Since preprocessor magic is used only when optimization is enabled, compiler handles it correctly, resolving all static values without bloating stack usage.

Additionally, added a test (`tests/subsys/logging/log_stack`) for checking stack usage when logging is used. Test has been used to characterize stack usage for various architectures (it varies a lot) in 4 configurations:
- deferred mode
- deferred mode (no optimization)
- immediate mode
- immediate mode (no optimization)

Test should detect any unexpected stack usage increases in logging area.

Fixes #42050.
Fixed #43016.

### CODE REVIEW

**Comment by nashif** [comment]
@nordic-krch  we also had issues with the previous attempt on XCC, @dcpleung  can provide the details.

**Comment by dcpleung** [comment]
Actually, @MaureenHelm found the issue first.

The issue is that XCC complains: `#pragma GCC diagnostic not allowed inside functions`. If you `#ifdef` them, XCC complains about `_auto_type` being unknown since this was introduced in GCC 4.9, but XCC is based on GCC 4.2.

**Comment by nordic-krch** [comment]
> The issue is that XCC complains: #pragma GCC diagnostic not allowed inside functions. If you #ifdef them, XCC complains about _auto_type being unknown since this was introduced in GCC 4.9, but XCC is based on GCC 4.2.

Added guard similar to one in cbprintf. For GCC < 4.9 and clang < 3.8 runtime packaging is used always and preprocessor cuts path with __auto_type and _Generic.

**Review by dcpleung — APPROVED** [review]

File: include/logging/log_msg2.h [hunk 1]
```diff
@@ -34,6 +34,22 @@ typedef uint64_t log_timestamp_t;
...
+ * Supported by:
+ * - GCC 4.9.0 https://gcc.gnu.org/gcc-4.9/changes.html
+ * - Clang 3.8
+ */
+#ifndef CONFIG_LOG2_ALWAYS_RUNTIME
+#if !defined(__cplusplus) && \
+	!(((__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) >= 40900) || \
+	((__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__) >= 30800))
+#define CONFIG_LOG2_ALWAYS_RUNTIME 1
+#error
```
Comment (SebastianBoe) [inline include/logging/log_msg2.h:49]: ? What is the point of defining something if we immediately #error anyway ?

File: include/logging/log_msg2.h [hunk 2]
```diff
@@ -34,6 +34,22 @@ typedef uint64_t log_timestamp_t;
...
+ * be used.
+ *
+ * Supported by:
+ * - GCC 4.9.0 https://gcc.gnu.org/gcc-4.9/changes.html
+ * - Clang 3.8
+ */
+#ifndef CONFIG_LOG2_ALWAYS_RUNTIME
+#if !defined(__cplusplus) && \
+	!(((__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) >= 40900) || \
+	((__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__) >= 30800))
```
Comment (SebastianBoe) [inline include/logging/log_msg2.h:47]: Maybe put this in a #define ?

#define AUTO_TYPE_IS_SUPPORTED

File: include/logging/log_msg2.h [hunk 3]
```diff
@@ -394,6 +373,36 @@ do { \
 	} \
 	(void)_mode; \
 } while (0)
+
+/* Macro for getting name of a local variable with the exception of the first argument
+ * which is a formatted string in log message.
+ */
+#define Z_LOG_LOCAL_ARG_NAME(idx, arg) COND_CODE_0(idx, (arg), (_v##idx))
+
+/* Create local variable from input variable (expect first (fmt) argument). */
```
Comment (SebastianBoe) [inline include/logging/log_msg2.h:382]:
```suggestion
/* Create local variable from input variable (except for the first (fmt) argument). */
```

File: include/logging/log_msg2.h [hunk 4]
```diff
@@ -394,6 +373,36 @@ do { \
...
+#ifdef __cplusplus
+#define Z_LOG_LOCAL_ARG_CREATE(idx, arg) \
+	COND_CODE_0(idx, (), (auto Z_LOG_LOCAL_ARG_NAME(idx, arg) = (arg) + 0))
+#else
+#define Z_LOG_LOCAL_ARG_CREATE(idx, arg) \
+	COND_CODE_0(idx, (), (__auto_type Z_LOG_LOCAL_ARG_NAME(idx, arg) = (arg) + 0))
```
Comment (SebastianBoe) [inline include/logging/log_msg2.h:388]: Can we have a define that evaluates to either auto or __auto_type so this is simplified ?

File: tests/subsys/logging/log_stack/src/test.inc [hunk 5]
```diff
@@ -0,0 +1,288 @@
+/*
```
Comment (SebastianBoe) [inline tests/subsys/logging/log_stack/src/test.inc:1]: Suffix should be .h, not .inc.

This makes it easier for tools and humans to understand what kind of file it is.

File: tests/subsys/logging/log_stack/src/maincxx.cxx [hunk 6]
```diff
@@ -0,0 +1,11 @@
+/*
+ * Copyright (c) 2019 Oticon A/S
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <ztest.h>
+#include <sys/util.h>
+#include <string.h>
```
Comment (SebastianBoe) [inline tests/subsys/logging/log_stack/src/maincxx.cxx:9]: AFAICT these #includes should be removed or moved into test.inc. And the same for main.c.

File: tests/subsys/logging/log_stack/src/maincxx.cxx [hunk 7]
```diff
@@ -0,0 +1,11 @@
+/*
+ * Copyright (c) 2019 Oticon A/S
```
Comment (SebastianBoe) [inline tests/subsys/logging/log_stack/src/maincxx.cxx:2]: Is this copyright intentional?

File: tests/subsys/logging/log_stack/src/test.inc [hunk 8]
```diff
@@ -0,0 +1,288 @@
...
+#include <ztest.h>
+#include <logging/log.h>
+
+#define MODULE_NAME test
+#define CXX_MODULE_NAME test_cxx
+
+/* The idea of this test is to estimate stack usage of logging messages. Each
+ * test checks stack usage before and after logging a message. Increase of stack
+ * usage is interpreted as stack used by the logging. Test has been used to
+ * characterize some common architectures and it will fail if more stack is
```
Comment (SebastianBoe) [inline tests/subsys/logging/log_stack/src/test.inc:16]:
```suggestion
 * characterize some common architectures and it will fail if significantly more stack is
```

I assume we don't want to maintain this limit for every byte that is incremented?

File: tests/subsys/logging/log_stack/src/test.inc [hunk 9]
```diff
@@ -0,0 +1,288 @@
...
+#define TEST_SUFFIX cc
+#endif
+
+#define SUFFIXED_NAME(_name) UTIL_CAT(_name, UTIL_CAT(_, TEST_SUFFIX))
+
+#define WRAP_TEST(suite_name, test_name)                   \
+	ZTEST(SUFFIXED_NAME(suite_name), SUFFIXED_NAME(test_name)) \
+	{                                                  \
+		test_name();                               \
+	}
```
Comment (SebastianBoe) [inline tests/subsys/logging/log_stack/src/test.inc:43]: If we didn't have main.c and main.cxx in the same executable we wouldn't have to generate the symbol names like this would we?

I propose we use testcase.yaml to determine whether either main.c or maincxx.cxx is used so we don't have to deal with this problem.

**Review by SebastianBoe — CHANGES_REQUESTED** [review]
Changes requested

File: include/logging/log_msg2.h (hunk 2 above)
Comment (tejlmand) [reply include/logging/log_msg2.h:47]: are there any way we could detect if this is supported before build time ?

For example checking compiler version in CMake or testing the compiler (I'm not aware of any compiler flags related to this feature, so this will most likely not be possible).

File: tests/subsys/logging/log_stack/CMakeLists.txt [hunk 10]
```diff
@@ -0,0 +1,7 @@
+# SPDX-License-Identifier: Apache-2.0
+
+cmake_minimum_required(VERSION 3.20.0)
+find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
+project(log_stack)
+
+target_sources(app PRIVATE src/main.c src/maincxx.cxx)
```
Comment (tejlmand) [inline tests/subsys/logging/log_stack/CMakeLists.txt:7]: I believe if you update `test.yaml` to have tests where `CONFIG_CPLUSPLUS=y` then you can use this knowledge here, like:
```suggestion
target_sources_ifdef(CONFIG_CPLUSPLUS app PRIVATE src/maincxx.cxx)
target_sources_ifndef(CONFIG_CPLUSPLUS app PRIVATE src/main.c)
```

and is more aligned with how users should enable C++ support, [CONFIG_CPLUSPLUS](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_CPLUSPLUS.html)

and then you may cleanup as proposed here: https://github.com/zephyrproject-rtos/zephyr/pull/42686/commits/f9ac5ea65d8c9dccca4a775f49acf544f0bc21b3#r806674828

**Review by tejlmand — CHANGES_REQUESTED** [review]
Agreeing with @SebastianBoe comments.

Please cleanup how compilation of main.c and maincxx.cxx is done.

File: tests/subsys/logging/log_stack/src/test.inc (hunk 5 above)
Comment (nordic-krch) [reply tests/subsys/logging/log_stack/src/test.inc:1]: there is a pattern, first started in `tests/unit/util` to name if `test.inc` and this is forth test that do that. I would keep it as is for consistency.

Comment (SebastianBoe) [reply tests/subsys/logging/log_stack/src/test.inc:1]: fair enough

File: include/logging/log_msg2.h (hunk 1 above)
Comment (nordic-krch) [reply include/logging/log_msg2.h]: that was left unintentionally, fixed.

File: include/logging/log_msg2.h (hunk 2 above)
Comment (nordic-krch) [reply include/logging/log_msg2.h]: not sure about compile time, but i rephrased this define to fixed https://github.com/zephyrproject-rtos/zephyr/pull/42686#discussion_r806654572 same time.

File: include/logging/log_msg2.h (hunk 4 above)
Comment (nordic-krch) [reply include/logging/log_msg2.h]: Done, Setting `Z_AUTO_TYPE` define to `auto` in cpp and `__auto_type` if c (and supported).

File: tests/subsys/logging/log_stack/src/test.inc (hunk 9 above)
Comment (nordic-krch) [reply tests/subsys/logging/log_stack/src/test.inc]: Done

File: tests/subsys/logging/log_stack/src/test.inc [hunk 11]
```diff
@@ -0,0 +1,288 @@
...
+
+static size_t simple_usage;
+static size_t hexdump_usage;
+static size_t more_args_usage;
+
+#define STACK_USAGE_MARGIN 8
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply tests/subsys/logging/log_stack/src/test.inc]: Increased to 16. Will see how often we get caught by that.

File: tests/subsys/logging/log_stack/CMakeLists.txt (hunk 10 above)
Comment (nordic-krch) [reply tests/subsys/logging/log_stack/CMakeLists.txt]: Done.

**Comment by nordic-krch** [comment]
@tejlmand @SebastianBoe thanks for review. Comments applied.

File: include/logging/log_msg2.h [hunk 12]
```diff
@@ -34,6 +34,25 @@ typedef uint64_t log_timestamp_t;
...
+ */
+#if defined(__cplusplus)
+#define Z_AUTO_TYPE auto
+#elif ((__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) >= 40900) || \
+	((__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__) >= 30800)
+#define Z_AUTO_TYPE __auto_type
+#else
+/* If compiler does not support auto/__auto_type keywork runtime packaging must be used. */
+#undef CONFIG_LOG2_ALWAYS_RUNTIME
+#define CONFIG_LOG2_ALWAYS_RUNTIME 1
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply include/logging/log_msg2.h]: agree. Added error there with note that runtime packaging must be enabled.

File: include/logging/log_msg2.h [hunk 13]
```diff
@@ -34,6 +34,23 @@ typedef uint64_t log_timestamp_t;
...
+ * - GCC 4.9.0 https://gcc.gnu.org/gcc-4.9/changes.html
+ * - Clang 3.8
+ */
+#if defined(__cplusplus)
+#define Z_AUTO_TYPE auto
+#elif ((__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) >= 40900) || \
+	((__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__) >= 30800)
+#define Z_AUTO_TYPE __auto_type
+#else
+#error "Compiler lacks support for __auto_type. Enable CONFIG_LOG2_ALWAYS_RUNTIME."
```
Comment (SebastianBoe) [inline include/logging/log_msg2.h:51]: should be

#ifndef CONFIG_LOG2_ALWAYS_RUNTIME
#error
#endif

right?

I see that below in this file we are checking if this define is set, so I assume it is not always unset.

Comment (SebastianBoe) [reply include/logging/log_msg2.h:52]: "move fast and break things" ;)

looks like a good job overall, at least the parts I was able
to understand.

**Review by SebastianBoe — DISMISSED** [review]

**Review by dcpleung — DISMISSED** [review]

File: tests/subsys/logging/log_stack/CMakeLists.txt [hunk 14]
```diff
@@ -0,0 +1,9 @@
+# SPDX-License-Identifier: Apache-2.0
+
+cmake_minimum_required(VERSION 3.20.0)
+find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
+project(log_stack)
+
+target_sources_ifdef(CONFIG_CPLUSPLUS app PRIVATE src/maincxx.cxx)
+
+target_sources_ifndef(CONFIG_CPLUSPLUS app PRIVATE src/main.c)
```
Comment (tejlmand) [inline tests/subsys/logging/log_stack/CMakeLists.txt:9]: actually, because `maincxx.cxx` and `main.c` are identical and including the same file, so a much better approach is to request CMake to compile `main.c` using the C++ compiler, like this:
```suggestion
target_sources(app PRIVATE src/main.c)
if(CONFIG_CPLUSPLUS)
  # Feel free to add a good comment here.
  set_source_files_properties(src/main.c PROPERTIES LANGUAGE CXX)
endif()
```

and then remove `maincxx.cxx` as well as `test.inc`.
Have just a single `main.c` file.

Cleaning of other places using `test.inc` can be done in seperate PR.

**Review by tejlmand — CHANGES_REQUESTED** [review]
Please use the features of CMake instead of hacks like including `test.inc` in to main files that are named just for the sole purposes of having them compiled with different compilers.

File: include/logging/log_msg2.h [hunk 15]
```diff
@@ -34,6 +34,25 @@ typedef uint64_t log_timestamp_t;
...
+ * - Clang 3.8
+ */
+#if defined(__cplusplus)
+#define Z_AUTO_TYPE auto
+#elif ((__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) >= 40900) || \
+	((__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__) >= 30800)
+#define Z_AUTO_TYPE __auto_type
+#else
+#ifndef CONFIG_LOG2_ALWAYS_RUNTIME
+#error "Compiler lacks support for __auto_type. Enable CONFIG_LOG2_ALWAYS_RUNTIME."
```
Comment (tejlmand) [inline include/logging/log_msg2.h:52]: Never got a reply on this part:
https://github.com/zephyrproject-rtos/zephyr/pull/42686#discussion_r808932898
> For example checking compiler version in CMake

This can be done with: https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_VERSION.html which is supported for gcc and llvm.
That way we may detect this BEFORE compilation.

File: include/logging/log_msg2.h (hunk 2 above)
Comment (tejlmand) [reply include/logging/log_msg2.h]: placed comment here: https://github.com/zephyrproject-rtos/zephyr/pull/42686#discussion_r811090728

comments to comments easily gets lost in history threads.

File: include/logging/log_msg2.h (hunk 15 above)
Comment (tejlmand) [reply include/logging/log_msg2.h:52]: that way we can inform user earlier that there is a configuration issue that must be fixed.

**Comment by nordic-krch** [comment]
@SebastianBoe @dcpleung approvals have been withdrawn, rebased and applied @tejlmand comments. Please take another look.

**Review by SebastianBoe — DISMISSED** [review]

File: subsys/logging/CMakeLists.txt [hunk 16]
```diff
@@ -15,6 +15,24 @@ if(NOT CONFIG_LOG_MODE_MINIMAL)
...
+  # Determine if __auto_type is supported. If not then runtime approach must always
+  # be used.
+  # Supported by:
+  # - C++ (auto)
+  # - GCC 4.9.0 https://gcc.gnu.org/gcc-4.9/changes.html
+  # - Clang 3.8
+  if (NOT CONFIG_LOG2_ALWAYS_RUNTIME)
+    if(CMAKE_C_COMPILER_ID STREQUAL "Clang")
+      if(CMAKE_C_COMPILER_VERSION VERSION_LESS "3.8.0")
+        message(FATAL_ERROR "Compiler version requires CONFIG_LOG2_ALWAYS_RUNTIME to be set")
```
Comment (tejlmand) [inline subsys/logging/CMakeLists.txt:27]: I think we should downgrade this to `WARNING`.

```suggestion
        message(WARNING "Compiler version requires CONFIG_LOG2_ALWAYS_RUNTIME to be set")
```

Reason, a fatal error will prevent users from running menuconfig and fix the problem, ref https://github.com/zephyrproject-rtos/zephyr/issues/9573

In principle FATAL_ERROR would be optimal here, but as users should be able to fix this using menuconfig, we have to go for less optimal solution.

File: subsys/logging/CMakeLists.txt [hunk 17]
```diff
@@ -15,6 +15,24 @@ if(NOT CONFIG_LOG_MODE_MINIMAL)
...
+      endif()
+    endif()
+    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
+      if(CMAKE_C_COMPILER_VERSION VERSION_LESS "4.9.0")
+        message(FATAL_ERROR "Compiler version requires CONFIG_LOG2_ALWAYS_RUNTIME to be set")
```
Comment (tejlmand) [inline subsys/logging/CMakeLists.txt:32]: I think we should downgrade this to `WARNING`.

```suggestion
        message(WARNING "Compiler version requires CONFIG_LOG2_ALWAYS_RUNTIME to be set")
```

Reason, a fatal error will prevent users from running menuconfig and fix the problem, ref https://github.com/zephyrproject-rtos/zephyr/issues/9573

**Review by tejlmand — CHANGES_REQUESTED** [review]
Looks good, only comment left is we should reduce the fatal error to a warning.

File: subsys/logging/CMakeLists.txt (hunk 17 above)
Comment (nordic-krch) [reply subsys/logging/CMakeLists.txt]: done

**Review by tejlmand — APPROVED** [review]
lgtm

**Review by carlescufi — APPROVED** [review]
