### PR TITLE
drivers: flash: flexspi_nor: Update page program LUT for 4-byte addressing

### LINKED ISSUE #102155: flash: mcux-flexspi-nor: Regression with ISSI `is25wx01g` flash device
### Describe the bug

Commit 7b561f760577b12fea06e22c53556bd3e226bfe6 introduces a regression where the NOR flash driver for MCUX flexspi no longer checks for vendor instruction sets.
This result in faulty reads.

### Regression

- [x] This is a regression.

### Steps to reproduce

1. Build the flash shell sample for a board with the specified flash device
2. Try writing data

```shell
$ west build -p -b cusom_board samples/drivers/flash_shell
```

Current behavior:
```
uart:~$ flash write is25wx01g@0 0 0 1 2 3 4 5
Write OK.
Verification ERROR!
uart:~$ flash read is25wx01g@0 0 32
00000000: 00 00 00 01 00 00 00 02  00 00 00 03 00 00 00 04 |........ ........|
00000010: 00 00 00 05 00 00 00 ff  ff ff ff ff ff ff ff ff |........ ........|
00000020: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000030: ff ff
```

Before the regression:
```
uart:~$ flash write is25wx01g@0 0 0 1 2 3 4 5
Write OK.
Verified.
uart:~$ flash read is25wx01g@0  0 32
00000000: 00 00 00 00 01 00 00 00  02 00 00 00 03 00 00 00 |........ ........|
00000010: 04 00 00 00 05 00 00 00  ff ff ff ff ff ff ff ff |........ ........|
00000020: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000030: ff ff                                            |..               |
```

Notice the off-by-one data difference.

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: Ubuntu 24.04
- Toolchain: Zephyr SDK 0.17.4
- Commit d6f9a4808f2ea86ab786a681b85166628f7ffba8

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Albort12138**
Fixes: #102155

# Root Cause
When 4-byte addressing mode is enabled on the flash device, there is an inconsistency in how address widths are handled between read and write operations:

Current behavior:

The read command correctly updates its addr_width to 32 bits when 4-byte mode is enabled
The program (write) command does NOT update its addr_width and remains at the default width
Impact: This mismatch causes the program command to send addresses with incorrect width (likely 24 bits instead of 32 bits) when the device is in 4-byte addressing mode. As a result:

Writes may target incorrect memory addresses
Data corruption or write failures can occur
The device behavior becomes unpredictable when accessing addresses beyond the 24-bit range (>16MB)

# Resulution
When 4-byte addressing is enabled, update the page program LUT entry to use the appropriate 4-byte page program command (SPI_NOR_CMD_PP_4B).

For octal mode (1S-8S-8S), select the correct page program command based on address width:
- Use SPI_NOR_CMD_PP_1_8_8_4B for 32-bit addressing
- Use SPI_NOR_CMD_PP_1_8_8 for 24-bit addressing

This ensures the flash controller uses the correct command sequence for page programming operations in both standard and octal modes with extended addressing.

Signed-off-by: Albort Xue <yao.xue@nxp.com>

### CODE REVIEW

**Review by pdgendt — DISMISSED** [review]
Needs a rebase to get fix from main, and one compliance issue.

This seems to fix my issue! 👍 One side-note, can you explain why I saw an issue with writing address `0x0` specifically?

File: drivers/flash/spi_nor.h [hunk 1]
```diff
@@ -70,6 +72,8 @@
 #define SPI_NOR_CMD_PP_4B        0x12  /* Page Program 4 Byte Address */
 #define SPI_NOR_CMD_PP_1_1_4_4B  0x34  /* Quad Page program (1-1-4) 4 Byte Address */
 #define SPI_NOR_CMD_PP_1_4_4_4B  0x3e  /* Quad Page program (1-4-4) 4 Byte Address */
+#define SPI_NOR_CMD_PP_1_1_8_4B  0x84  /* Octal Page program (1-1-8) 4 Byte Address */
+#define SPI_NOR_CMD_PP_1_8_8_4B  0x8E   /* Extended Octal Page program (1-8-8) 4 Byte Address */
```
Comment (pdgendt) [inline drivers/flash/spi_nor.h]: Nit

```suggestion
#define SPI_NOR_CMD_PP_1_8_8_4B  0x8E  /* Extended Octal Page program (1-8-8) 4 Byte Address */
```

**Review by pdgendt — DISMISSED** [review]

**Review by mmahadevan108 — DISMISSED** [review]

File: drivers/flash/spi_nor.h (hunk 1 above)
Comment (Albort12138) [reply drivers/flash/spi_nor.h]: Fixed

**Review by pdgendt — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]
