### PR TITLE
drivers: i2c: stm32: support more than 256 bytes transfer for RTIO

### LINKED ISSUE #90675: I2C RTIO stream issue/limitation with STM32
**Describe the bug**

I noticed that e8bd35e305 commit is breaking RTIO streaming capability on my STM32 board (i.e. nucleo_h503rb + x_nucleo_iks4a1 shield)

**To Reproduce**

1. west build -b nucleo_h503rb samples/sensor/stream_fifo/
2. west flash

**Expected behavior**

You should observe sensor data streamed from lsm6dsv16x sensor on terminal emulator

**Impact**

I had to revert e8bd35e305 in order to proceed with my development and debugging, as I need my h/w setup to be functional.

**Logs and console output**
```
FIFO count - 64
XL data for lsm6dsv16x@6b 3703702965ns (0.114839, -0.559844, 9.986294)
XL data for lsm6dsv16x@6b 3770369631ns (0.354089, 0.143549, 10.000649)
XL data for lsm6dsv16x@6b 3837036297ns (0.148334, 0.856514, 9.952799)
XL data for lsm6dsv16x@6b 3903702963ns (-0.229679, 0.392369, 10.000649)
XL data for lsm6dsv16x@6b 3970369629ns (0.583769, 0.148334, 9.962369)
XL data for lsm6dsv16x@6b 4037036295ns (0.267959, 0.224894, 9.971939)
XL data for lsm6dsv16x@6b 4103702961ns (0.033494, 0.272744, 9.967154)
XL data for lsm6dsv16x@6b 4170369627ns (0.172259, 0.071774, 9.971939)
GY data for lsm6dsv16x@6b 3703702965ns (0.000609, 0.001524, 0.174154)
GY data for lsm6dsv16x@6b 3770369631ns (0.011894, -0.014029, 0.757924)
GY data for lsm6dsv16x@6b 3837036297ns (0.002134, 0.007014, 0.508434)
GY data for lsm6dsv16x@6b 3903702963ns (0.009149, -0.009454, 0.487389)
GY data for lsm6dsv16x@6b 3970369629ns (0.002744, 0.014639, 0.451704)
GY data for lsm6dsv16x@6b 4037036295ns (0.003354, -0.010979, 0.156159)
GY data for lsm6dsv16x@6b 4103702961ns (0.002134, 0.000609, 0.096074)
GY data for lsm6dsv16x@6b 4170369627ns (0.002134, -0.001524, 0.051849)
TP data for lsm6dsv16x@6b 3703702965ns 25.890625 ??°?C
TP data for lsm6dsv16x@6b 3770369631ns 25.917967 ??°?C
TP data for lsm6dsv16x@6b 3837036297ns 25.890625 ??°?C
TP data for lsm6dsv16x@6b 3903702963ns 25.890625 ??°?C
ROT data for lsm6dsv16x@6b 3770369631ns (-0.031204, 0.095825, -0.226318, 0.968825)
ROT data for lsm6dsv16x@6b 3837036297ns (-0.027267, 0.093017, -0.203613, 0.974241)
ROT data for lsm6dsv16x@6b 3903702963ns (-0.021209, 0.091186, -0.188476, 0.977605)
ROT data for lsm6dsv16x@6b 3970369629ns (-0.017715, 0.091125, -0.173950, 0.980369)
ROT data for lsm6dsv16x@6b 4037036295ns (-0.016799, 0.088012, -0.160888, 0.982896)
ROT data for lsm6dsv16x@6b 4103702961ns (-0.016448, 0.085693, -0.157226, 0.983700)
ROT data for lsm6dsv16x@6b 4170369627ns (-0.015869, 0.085083, -0.155639, 0.984014)
ROT data for lsm6dsv16x@6b 4237036293ns (-0.016601, 0.083801, -0.155395, 0.984151)
GV data for lsm6dsv16x@6b 3770369631ns (-171.287994, -103.761001, 977.952026)
GV data for lsm6dsv16x@6b 3837036297ns (-170.068008, -90.951004, 980.392028)
GV data for lsm6dsv16x@6b 3903702963ns (-170.190002, -75.822998, 981.856018)
GV data for lsm6dsv16x@6b 3970369629ns (-172.507995, -66.429000, 982.343994)
GV data for lsm6dsv16x@6b 4037036295ns (-167.505996, -61.305000, 983.807983)
GV data for lsm6dsv16x@6b 4103702961ns (-163.358001, -59.291999, 984.783996)
GV data for lsm6dsv16x@6b 4170369627ns (-162.503997, -57.706001, 985.272033)
GV data for lsm6dsv16x@6b 4237036293ns (-159.820007, -58.681999, 985.760009)
GY GBIAS data for lsm6dsv16x@6b 3703702965ns (0.115291, -0.229975, 0.049703)
GY GBIAS data for lsm6dsv16x@6b 3770369631ns (0.115291, -0.229975, 0.049703)
GY GBIAS data for lsm6dsv16x@6b 3837036297ns (0.115291, -0.229975, 0.049703)
GY GBIAS data for lsm6dsv16x@6b 3903702963ns (0.115291, -0.229975, 0.049703)
GY GBIAS data for lsm6dsv16x@6b 3970369629ns (0.115291, -0.229975, 0.049703)
GY GBIAS data for lsm6dsv16x@6b 4037036295ns (0.115291, -0.229975, 0.049703)
GY GBIAS data for lsm6dsv16x@6b 4103702961ns (0.115291, -0.229975, 0.049703)
GY GBIAS data for lsm6dsv16x@6b 4170369627ns (0.115291, -0.229975, 0.049703)
XL data for lsm6dsv16x@6b 4237036293ns (0.244034, 0.148334, 9.971939)
XL data for lsm6dsv16x@6b 4303702959ns (0.325379, 0.095699, 9.967154)
XL data for lsm6dsv16x@6b 4370369625ns (0.430649, 0.105269, 9.991079)
GY data for lsm6dsv16x@6b 4237036293ns (0.003354, -0.004269, 0.081739)
GY data for lsm6dsv16x@6b 4303702959ns (0.005489, -0.007624, 0.165309)
GY data for lsm6dsv16x@6b 4370369625ns (0.002134, -0.007014, 0.290054)
TP data for lsm6dsv16x@6b 3970369629ns 25.886717 ??°?C
```

### PR DESCRIPTION
**Pull request by etienne-lms**
Add support for transfer of more than 256 byte in STM32 v1 and v2 RTIO drivers.

Add missing disable of I2C error interrupt when disabling I2C interrupts
in STM32 RTIO drivers.

### CODE REVIEW

File: drivers/i2c/i2c_ll_stm32.h [hunk 1]
```diff
@@ -73,7 +73,7 @@ struct i2c_stm32_data {
 	struct i2c_rtio *ctx;
 	uint32_t dev_config;
 	uint8_t *xfer_buf;
-	uint8_t xfer_len;
+	unsigned int xfer_len;
```
Comment (mathieuchopstm) [inline drivers/i2c/i2c_ll_stm32.h]: Nit:
```suggestion
	uint32_t xfer_len;
```
(not strictly equivalent as `uint32_t` is `unsigned long` in Zephyr, but `sizeof(int) == sizeof(long)`...)

**Review by mathieuchopstm — COMMENTED** [review]
Not familiar with RTIO API so can't comment on that area; rest LGTM.

Nit: is non-RTIO driver also affected by this limitation? If so, we should try to fix it there too (but in another PR :slightly_smiling_face:)

File: drivers/i2c/i2c_ll_stm32.h (hunk 1 above)
Comment (etienne-lms) [reply drivers/i2c/i2c_ll_stm32.h]: Actually I think `size_t` would even be better since it relates to a buffer. Would it be ok for you?

**Review by teburd — DISMISSED** [review]
Were you able to test this, when I tried it with a modified i2c_ram test I ran into issues, which is in part why this was a todo.

**Comment by etienne-lms** [comment]
> Were you able to test this, when I tried it with a modified i2c_ram test I ran into issues, which is in part why this was a todo.

I've tested with the sensor/stream_fifo sample.
I am working on the i2c target mode for these RTIO drivers, to extend my tests using I2C loopback test samples.

I'll see if I can get a shield with an I2C accessed memory, to replicate your tests setup.
Do you mean some of your tests that were passing before this P-R now fail?

File: drivers/i2c/i2c_ll_stm32.h (hunk 1 above)
Comment (mathieuchopstm) [reply drivers/i2c/i2c_ll_stm32.h]: Indeed this is filled from a `size_t`, so OK for me.

File: drivers/i2c/i2c_ll_stm32.h [hunk 2]
```diff
@@ -73,7 +73,7 @@ struct i2c_stm32_data {
...
 	uint8_t xfer_flags;
 #ifdef CONFIG_I2C_STM32_V1
 	uint8_t msg_len;
```
Comment (etienne-lms) [inline drivers/i2c/i2c_ll_stm32.h]: I missed this one:
```patch
-	uint8_t msg_len;
+	size_t_t msg_len;
```

**Comment by avisconti** [comment]
@etienne-lms The PR seems good to me, but I'm not able to test it right now. How did you test it? (board, shield, sensor, ...)
Can you add it on the PR main message? Thanks

EDIT:
OK, I see it from comments above. Tomorrow I will test it on a real board/shiled

**Comment by etienne-lms** [comment]
Updated from review comments feedback.

**Comment by avisconti** [comment]
OK, I just re-fetched your latest work (i.e. aligned to 5aed1b6).
It is working on my side. I tested it on a nucleo_h503rb board plus a x_nucleo_iks4a1 shield. On this shield there is a lsm6dsv16x sensor connected to I2C bus. And your branch IT IS solving the issue.

Now, I'll take a better look to your code, just to potentially give you other feedback. But yesterday it seemed good also from code style point of view.

File: drivers/i2c/i2c_ll_stm32_v1_rtio.c [hunk 3]
```diff
@@ -38,6 +38,7 @@ static void i2c_stm32_disable_transfer_interrupts(const struct device *dev)
 	LL_I2C_DisableIT_RX(i2c);
 	LL_I2C_DisableIT_EVT(i2c);
 	LL_I2C_DisableIT_BUF(i2c);
+	LL_I2C_DisableIT_ERR(i2c);
```
Comment (avisconti) [inline drivers/i2c/i2c_ll_stm32_v1_rtio.c:41]: Is this an issue only for RTIO?

File: drivers/i2c/i2c_ll_stm32_v2_rtio.c [hunk 4]
```diff
@@ -37,6 +37,7 @@ static void i2c_stm32_disable_transfer_interrupts(const struct device *dev)
 	LL_I2C_DisableIT_STOP(i2c);
 	LL_I2C_DisableIT_NACK(i2c);
 	LL_I2C_DisableIT_TC(i2c);
+	LL_I2C_DisableIT_ERR(i2c);
```
Comment (avisconti) [inline drivers/i2c/i2c_ll_stm32_v2_rtio.c:40]: Same doubt here. Was it missing also before?

**Review by avisconti — APPROVED** [review]
LGTM.
Just few doubts whether these fixes only apply to RTIO case or it is more general. But works fine on my RTIO tests.

**Review by gautierg-st — APPROVED** [review]

File: drivers/i2c/i2c_ll_stm32_v1_rtio.c (hunk 3 above)
Comment (etienne-lms) [reply drivers/i2c/i2c_ll_stm32_v1_rtio.c:41]: Only for RTIO. The non-RTIO already handles that.

**Comment by etienne-lms** [comment]
For info, I've successfully tested samples/drivers/i2c/rtio_loopback on nucleo_f401re (stm32 i2c v1 driver) (with few changes only related to I2C target mode) and burst of more than 256 bytes are properly exchanged.

I need to do the same for i2c stm32 v2 driver (applies to nucleo_h503rb). I'll create a dedicated P-R for adding this I2C target mode support in the stm32 I2C/RTIO drivers.

**Review by teburd — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Comment by avisconti** [comment]
> For info, I've successfully tested samples/drivers/i2c/rtio_loopback on nucleo_f401re (stm32 i2c v1 driver) (with few changes only related to I2C target mode) and burst of more than 256 bytes are properly exchanged.
> 
> I need to do the same for i2c stm32 v2 driver (applies to nucleo_h503rb). I'll create a dedicated P-R for adding this I2C target mode support in the stm32 I2C/RTIO drivers.

I did it on nucleo_h503rb [here](https://github.com/zephyrproject-rtos/zephyr/pull/91664#issuecomment-2979322747)
