### PR TITLE
Bluetooth: Controller: Fix privacy advertiser connect peer address type

### LINKED ISSUE #17944: [zephyr 1.14]  LE Enhanced Connection Complete indicates Resolved Public once connected to Public peer address
-
**Describe the bug**
PTS test case GATT/SR/GAS/BV-04-C, GATT/SR/GAS/BV-07-C require pairing. PTS connects with Public address type, but distributes IRK during pairing. 
```
> HCI Event: LE Meta Event (0x3e) plen 31                                                                                                                                                                                                                            #50 [hci0] 22.423416
      LE Enhanced Connection Complete (0x0a)
        Status: Success (0x00)
        Handle: 0
        Role: Slave (0x01)
        Peer address type: Public (0x00)
        Peer address: 00:1B:DC:08:E6:76 (Vencer Co., Ltd.)
        Local resolvable private address: 58:D4:77:1E:98:EF (Resolvable)
        Peer resolvable private address: 00:00:00:00:00:00 (Non-Resolvable)
        Connection interval: 75.00 msec (0x003c)
        Connection latency: 0.00 msec (0x0000)
        Supervision timeout: 20000 msec (0x07d0)
        Master clock accuracy: 0x01
...
> ACL Data RX: Handle 0 flags 0x02 dlen 11                                                                                                                                                                                                                           #55 [hci0] 22.477316
      SMP: Pairing Request (0x01) len 6
        IO capability: KeyboardDisplay (0x04)
        OOB data: Authentication data not present (0x00)
        Authentication requirement: Bonding, No MITM, Legacy, No Keypresses (0x01)
        Max encryption key size: 7
        Initiator key distribution: EncKey IdKey Sign (0x07)
        Responder key distribution: EncKey IdKey Sign (0x07)
< ACL Data TX: Handle 0 flags 0x00 dlen 11                                                                                                                                                                                                                           #56 [hci0] 22.479016
      SMP: Pairing Response (0x02) len 6
        IO capability: NoInputNoOutput (0x03)
        OOB data: Authentication data not present (0x00)
        Authentication requirement: Bonding, No MITM, Legacy, No Keypresses (0x01)
        Max encryption key size: 16
        Initiator key distribution: EncKey IdKey Sign (0x07)
        Responder key distribution: EncKey IdKey Sign (0x07)
```
Host adds PTS to Resolving list with IRK distributed.
```
< HCI Command: LE Add Device To Resolving List (0x08|0x0027) plen 39                                                                                                                                                                                                 #83 [hci0] 23.298916
        Address type: Public (0x00)
        Address: 00:1B:DC:08:E6:76 (Vencer Co., Ltd.)
        Peer identity resolving key: aa3341ca020d4835838b0d6c8f93aaae
        Local identity resolving key: 7fc6689ad83cc3ba07fcb63d65ddc27c
```
PTS reconnects and initiates pairing again using Public address type
```
> HCI Event: LE Meta Event (0x3e) plen 31                                                                                                                                                                                                                           #126 [hci0] 28.442216
      LE Enhanced Connection Complete (0x0a)
        Status: Success (0x00)
        Handle: 0
        Role: Slave (0x01)
        Peer address type: Resolved Public (0x02)
        Peer address: 00:1B:DC:08:E6:76 (Vencer Co., Ltd.)
        Local resolvable private address: 58:D4:77:1E:98:EF (Resolvable)
          Identity type: Random (0x01)
          Identity: DD:AD:FB:8F:B7:AE (Static)
        Peer resolvable private address: 00:1B:DC:08:E6:76 (Non-Resolvable)
        Connection interval: 75.00 msec (0x003c)
        Connection latency: 0.00 msec (0x0000)
        Supervision timeout: 20000 msec (0x07d0)
        Master clock accuracy: 0x01
...
> ACL Data RX: Handle 0 flags 0x02 dlen 11                                                                                                                                                                                                                          #132 [hci0] 28.539816
      SMP: Pairing Request (0x01) len 6
        IO capability: KeyboardDisplay (0x04)
        OOB data: Authentication data not present (0x00)
        Authentication requirement: Bonding, No MITM, Legacy, No Keypresses (0x01)
        Max encryption key size: 7
        Initiator key distribution: EncKey IdKey Sign (0x07)
        Responder key distribution: EncKey IdKey Sign (0x07)
< ACL Data TX: Handle 0 flags 0x00 dlen 11                                                                                                                                                                                                                          #133 [hci0] 28.541516
      SMP: Pairing Response (0x02) len 6
        IO capability: NoInputNoOutput (0x03)
        OOB data: Authentication data not present (0x00)
        Authentication requirement: Bonding, No MITM, Legacy, No Keypresses (0x01)
        Max encryption key size: 16
        Initiator key distribution: EncKey IdKey Sign (0x07)
        Responder key distribution: EncKey IdKey Sign (0x07)
```
The controller indicates the Peer address type: Resolved Public (0x02). This should be Public (0x00).

As the result, pairing fails
```
      SMP: Pairing Failed (0x05) len 1
        Reason: Confirm value failed (0x04)
```

**To Reproduce**
1. Set TSPX_iut_device_name_in_adv_packet_for_random_address tester
2. Execute GATT/SR/GAS/BV-04-C
3. bt init
4. bt clear all
5. gatt register
6. bt name tester
7. bt advertise on

**Expected behavior**
Pairing succeeds

**Impact**
Qualification test cases GATT/SR/GAS/BV-04-C, GATT/SR/GAS/BV-07-C

**Environment (please complete the following information):**
 - nrf52840pdk

[btmon.zip](https://github.com/zephyrproject-rtos/zephyr/files/3456864/gatt_cach.zip)
[sniffer_traces.zip](https://github.com/zephyrproject-rtos/zephyr/files/3456943/sniffer_traces.zip)

### PR DESCRIPTION
**Pull request by joerchan**
Fix an issue with enhanced connection complete event raised by the
advertiser role. The advertiser reported that it has resolved the
the identity address of the peer, even when the peer is connecting
using it's identity address.
The host will not have the correct on-air address type i.e public.

Fixes: #17944

### CODE REVIEW

**Comment by joerchan** [comment]
FYI: @MariuszSkamra

**Review by carlescufi — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ctrl.c [hunk 1]
```diff
@@ -1090,7 +1090,7 @@ static inline u32_t isr_rx_adv(u8_t devmatch_ok, u8_t devmatch_id,
 		radio_le_conn_cmplt->own_addr_type = pdu_adv->rx_addr;
 		memcpy(&radio_le_conn_cmplt->own_addr[0],
 		       &pdu_adv->connect_ind.adv_addr[0], BDADDR_SIZE);
-		if (rl_idx != FILTER_IDX_NONE) {
+		if (irkmatch_ok && rl_idx != FILTER_IDX_NONE) {
```
Comment (carlescufi) [inline subsys/bluetooth/controller/ll_sw/ctrl.c]: A couple of questions though:

1. Maybe better to fix this higher up, when we set `rl_idx` and set it to `NONE` if `irkmatch_ok == FALSE`?
2. Does this need to be fixed in the split LL?

Comment (joerchan) [reply subsys/bluetooth/controller/ll_sw/ctrl.c]: 1. I'm not 100% sure that would be without side effects. This way matches the inititiaor side of it

2. As far as I could tell the split one handled this, so no

**Review by cvinayak — CHANGES_REQUESTED** [review]
What about the other NODE_RX_TYPE_CONNECTION in initiator?

**Review by cvinayak — APPROVED** [review]
