### PR TITLE
sys/time_units.h: Work around clang div-by-zero warning

### LINKED ISSUE #63564: Spurious `warning: division by zero is undefined` on `K_THREAD_DEFINE` when building with clang
**Describe the bug**
Hi, bumped into this compiler warning on `K_THREAD_DEFINE` since https://github.com/zephyrproject-rtos/zephyr/pull/62900 got merged. One of our project that is building for an stm32 with LLVM started failing with a compiler warning:

```
/mnt/host/source/src/platform/ec/zephyr/shim/src/tasks.c:51:1251: error: division by zero is undefined [-Werror,-Wdivision-by-zero]
 struct z_thread_stack_element __attribute__((section("." "noinit" "." "\"EC_BASE/ec/zephyr/shim/src/tasks.c\"" "." "21"))) __attribute__((__aligned__(((((0x40) > (0)) ? (0x40) : (0)))))) _k_thread_stack_RWSIG[(((((unsigned long)(1536) + ((unsigned long)(8) - 1)) / (unsigned long)(8)) * (unsigned long)(8)) + ((size_t)0x40))]; struct k_thread _k_thread_obj_RWSIG; __attribute__((__aligned__(__alignof(struct _static_thread_data)))) struct _static_thread_data _k_thread_data_RWSIG __attribute__((section("." "__static_thread_data" "." "static" "." "_k_thread_data_RWSIG_"))) __attribute__((__used__)) = { .init_thread = (&_k_thread_obj_RWSIG), .init_stack = (_k_thread_stack_RWSIG), .init_stack_size = (1536), .init_entry = (k_thread_entry_t)rwsig_task, .init_p1 = (void *)0, .init_p2 = (void *)((void*)0), .init_p3 = (void *)((void*)0), .init_prio = ((EC_TASK_PRIO_COUNT - EC_TASK_RWSIG_PRIO - 1)), .init_options = (0), .init_delay = ((k_timeout_t) { .ticks = (((-1)) == (-1) ? ((k_ticks_t) -1) : ((k_ticks_t)((1) ? ( ((10000) == (1000)) ? (uint64_t) (((((-1)) > (0)) ? ((-1)) : (0))) : ((1000) > (10000) && (1000) % (10000) == 0U) ? ((uint64_t) (((((-1)) > (0)) ? ((-1)) : (0))) + ((0) ? ((1000) / (10000)) / 2 : (1) ? ((1000) / (10000)) - 1 : 0)) / ((1000) / (10000)) : ((10000) > (1000) && (10000) % (1000) == 0U) ? (uint64_t) (((((-1)) > (0)) ? ((-1)) : (0)))*((10000) / (1000)) : ((((((365 * 24ULL * 3600ULL * 1000) + (4294967295U) - 1) / (4294967295U)) * 10000) <= 4294967295U) ? (((uint64_t) (((((-1)) > (0)) ? ((-1)) : (0)))*(10000) + ((0) ? (1000) / 2 : (1) ? (1000) - 1 : 0)) / (1000)) : (((uint64_t) (((((-1)) > (0)) ? ((-1)) : (0))) / (1000))*(10000) + (((uint64_t) (((((-1)) > (0)) ? ((-1)) : (0))) % (1000))*(10000) + ((0) ? (1000) / 2 : (1) ? (1000) - 1 : 0)) / (1000))) ) : (((uint64_t) (((((-1)) > (0)) ? ((-1)) : (0))) / (1000))*(10000) + (((uint64_t) (((((-1)) > (0)) ? ((-1)) : (0))) % (1000))*(10000) + ((0) ? (1000) / 2 : (1) ? (1000) - 1 : 0)) / (1000)) ))) }), .init_name = "RWSIG", }; const k_tid_t RWSIG = (k_tid_t)&_k_thread_obj_RWSIG;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ^ ~~~~~~~~~~~~~~~~~~
```

The cause seems to be the introduction of `SYS_TIMEOUT_MS` in `Z_THREAD_INITIALIZER`, the macro eventually expands into some call of `z_tmcvt_64` which includes a `/ (Z_HZ_ms / Z_HZ_cyc)`, that becomes a `/ 0` in most tickless setups since `Z_HZ_ms = 1000` and `Z_HZ_cyc = CONFIG_SYS_CLOCK_TICKS_PER_SEC = 10000`. The ternary picks the valid value and GCC is happy with that, but clang seems to be firing a warning.

I managed to reproduce this with this example:

```c
#include <stdio.h>

int ticks = 0 ? 1 / 0 : 0 ;

int main(int argc, char **argv)
{
        printf("%d\n", ticks);
}
```

```
$ gcc -Wall -o test test.c
$ clang -Wall -o test test.c
test.c:3:19: warning: division by zero is undefined [-Wdivision-by-zero]
int ticks = 0 ? 1 / 0 : 0 ;
                  ^ ~
1 warning generated.
```

Note that for some reason the warning does not fire if the condition is moved inside the function.

The CI did not catch it because the clang build that we run is all for `native_posix` and runs with `SYS_CLOCK_TICKS_PER_SEC = 100`, but this can be reproduced upstream fairly easily with:

```
$ export ZEPHYR_TOOLCHAIN_VARIANT=llvm
$ west build -p -b native_posix_64 samples/basic/threads -DCONFIG_SYS_CLOCK_TICKS_PER_SEC=10000
...
/usr/local/google/home/fabiobaltieri/zephyrproject/zephyr/samples/basic/threads/src/main.c:111:1: warning: division by zero is undefined [-Wdivision-by-zero]
K_THREAD_DEFINE(blink0_id, STACKSIZE, blink0, NULL, NULL, NULL,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```

To get around this in our application we ended up selectively disabling the warning (https://chromium-review.googlesource.com/4907933), but that's obviously not a scalable workaround. Unfortunately the way our CI is setup does not give us much visibility into it, but there's probably many users compling with clang for tickless systems and I think this should be looked into before the release.

I tried to look into the https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/sys/time_units.h definitions but can't quite see a decent workaround, looking for more ideas around this.

**To Reproduce**
```
$ export ZEPHYR_TOOLCHAIN_VARIANT=llvm
$ west build -p -b native_posix_64 samples/basic/threads -DCONFIG_SYS_CLOCK_TICKS_PER_SEC=10000
```

**Expected behavior**
No warning

**Impact**
Build fail if warning as treated as errors.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: clang 14.0.6 and 17.0.0

### PR DESCRIPTION
**Pull request by keith-packard**
clang emits a warning for this code:

  foo.c:1:25: warning: division by zero is undefined [-Wdivision-by-zero]
  int i = (10 > 100 ? (20 / (10 / 100)) : (20 * (100 / 10)));
	                        ^ ~~~~~~~~~~

The warning is generated for code whose value does not affect the expression result, but technically it is still 'undefined behavior'.

Work around this warning by checking for a zero divisor and substituting one to make the compiler happy.

Closes: #63564

### CODE REVIEW

**Review by fabiobaltieri — DISMISSED** [review]
Thanks!

Just a few compliance warnings:

```
 SPACING: space required after that ',' (ctx:VxV)
File:include/zephyr/sys/time_units.h
Line:146
 SPACING: spaces required around that '?:' (ctx:WxV)
File:include/zephyr/sys/time_units.h
Line:146
 SPACING: space required after that ',' (ctx:VxV)
File:include/zephyr/sys/time_units.h
Line:148
```

**Review by fabiobaltieri — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

**Review by ghost — DISMISSED** [review]

**Review by evgeniy-paltsev — CHANGES_REQUESTED** [review]
Can we add a test-case which triggers this issue to `tests/kernel/timer/timer_api/src/timer_convert.c`?

**Comment by keith-packard** [comment]
> Can we add a test-case which triggers this issue to `tests/kernel/timer/timer_api/src/timer_convert.c`?

good idea. That also caught a problem with the definition of Z_HZ_cyc, which used sys_clock_hw_cycles_per_sec. That was never a constant expression because it was a static inline instead of being a macro.

**Comment by evgeniy-paltsev** [comment]
> That also caught a problem with the definition of Z_HZ_cyc, which used sys_clock_hw_cycles_per_sec. That was never a constant expression because it was a static inline instead of being a macro.

Hmm, do we require that sys_clock_hw_cycles_per_sec must be compile-time constant?

Cause it naturally can't be compile-time constant if `CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME` is enabled - so we use `sys_clock_hw_cycles_per_sec_runtime_get()`

**Comment by keith-packard** [comment]
> > That also caught a problem with the definition of Z_HZ_cyc, which used sys_clock_hw_cycles_per_sec. That was never a constant expression because it was a static inline instead of being a macro.
> 
> Hmm, do we require that sys_clock_hw_cycles_per_sec must be compile-time constant?

No, it's only constant when it isn't read at runtime. The issue was that `sys_clock_hw_cycles_per_sec()` wasn't a "constant" even when the timer frequency was specified at compile time.

> Cause it naturally can't be compile-time constant if `CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME` is enabled - so we use `sys_clock_hw_cycles_per_sec_runtime_get()`

Yup. In that case, we aren't testing to make sure the timer macros are valid C constant expressions.

**Review by ghost — DISMISSED** [review]
Nitpick: I personally try to avoid `#ifndef ... #else ...` as the negation is easy to overlook and requires extra cognitive load.

Why not `#ifdef ... #else ...` instead?

**Comment by keith-packard** [comment]
> > That also caught a problem with the definition of Z_HZ_cyc, which used sys_clock_hw_cycles_per_sec. That was never a constant expression because it was a static inline instead of being a macro.
> 
> Hmm, do we require that sys_clock_hw_cycles_per_sec must be compile-time constant?
> 
> Cause it naturally can't be compile-time constant if `CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME` is enabled - so we use `sys_clock_hw_cycles_per_sec_runtime_get()`

I'm wondering if this means we need something like #63594 ?

**Review by fabiobaltieri — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@evgeniy-paltsev can you revisit this once you have a chance? Would be nice to merge it before RC2.

**Comment by jhedberg** [comment]
> @evgeniy-paltsev can you revisit this once you have a chance? Would be nice to merge it before RC2.

@andyross (as the assignee) would also need to approve first

File: include/zephyr/sys/time_units.h [hunk 1]
```diff
@@ -138,6 +135,16 @@ static TIME_CONSTEXPR inline int sys_clock_hw_cycles_per_sec(void)
 	 (__round_up) ? ((__from_hz) / (__to_hz)) - 1 :			\
 	 0)
 
+/* Clang emits a divide-by-zero warning even though the int_div macro
+ * results are only used when the divisor will not be zero. Work
+ * around this by substituting 1 to make the compiler happy.
+ */
+#ifdef __clang__
+#define z_tmcvt_divisor(a, b) ((a) / (b) ?: 1)
```
Comment (andyross) [inline include/zephyr/sys/time_units.h:143]: At what level of the language standard did that ternary syntax appear?  I worry because we have `__clang__` compilers in the stable (c.f. Cadence's xt-clang) which are comparatively old.  Might be safer to write that out long hand?  Or not, if we're sure this is supported.

Comment (andyross) [reply include/zephyr/sys/time_units.h:143]: Also grade school math pedantry: the operation of this macro should probably be named "quotient", or just "divide", the "divisor" is the `a` argument.

**Review by andyross — APPROVED** [review]
Some nitpicks, but not worth a -1, looks fine on the whole.

**Comment by andyross** [comment]
> As far as I can tell, this only impacts qemu_x86 platforms (as those appear to use HPET which implies run-time timer freq).

FWIW: I wouldn't cry if someone went in there with a hatchet and just removed the runtime frequency query from the HPET driver.  Literally everything else in Zephyr is based on compile-time hardware configuration, and in point of fact all of our HPET x86 devices have hard frequency settings anyway, IIRC.

CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME is a historical wart, and it doesn't even do the thing we actually know we need, which is dynamic runtime frequency selection (right now there are a handful of devices that do that, but by translation inside the timer driver).

**Review by evgeniy-paltsev — APPROVED** [review]

File: include/zephyr/sys/time_units.h (hunk 1 above)
Comment (keith-packard) [reply include/zephyr/sys/time_units.h:143]: Yeah, the name actually refers to the division that this value is used as a part of -- which is in the `z_tmcvt_int_div_*` macros. In that context, it looks like I guessed right in using 'divisor' (I admit that I just checked :-)

**Comment by keith-packard** [comment]
> CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME is a historical wart, and it doesn't even do the thing we actually know we need, which is dynamic runtime frequency selection (right now there are a handful of devices that do that, but by translation inside the timer driver).

I'd suspect to make this work reliably you'd need to annotate every timeout value with some kind of 'required precision' value so that the dynamic frequency stuff didn't introduce so much slop that things started breaking when the core timer frequency got set too low...

In any case, it looks like HPET doesn't require runtime timer values, it just allows them, so turning all of that off could be done by simply removing the 'imply y' value from the relevant Kconfig file.
