### PR TITLE
Bluetooth: shell: VCS: Use BT_VOCS_MIN_OFFSET/BT_VOCS_MAX_OFFSET

### LINKED ISSUE #40236: Unsigned int can't be used in condition compare with int
**Describe the bug**
some of zephyr code has below pattern
```
static int cmd_vcs_vocs_offset_set(const struct shell *sh, size_t argc,
				   char **argv)
{
	int result;
	int index = strtol(argv[1], NULL, 0);
	int offset = strtol(argv[2], NULL, 0);

	if (index > CONFIG_BT_VCS_VOCS_INSTANCE_COUNT) {
		shell_error(sh, "Index out of range; 0-%u, was %u",
			    CONFIG_BT_VCS_VOCS_INSTANCE_COUNT, index);
		return -ENOEXEC;
	}

	if (offset > UINT8_MAX || offset < -UINT8_MAX) {
		shell_error(sh, "Offset shall be %d-%d, was %d",
			    -UINT8_MAX, UINT8_MAX, offset);
		return -ENOEXEC;
	}
```

and the offset < -UINT8_MAX is always true, as -UINT8_MAX will give you a big unsigned number

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\_xyz
3. make

**Expected behavior**

**Impact**
code logic

**Logs and console output**
If applicable, add console logs or other types of debug information
e.g Wireshark capture or Logic analyzer capture (upload in zip archive).
copy-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue. (if unable to obtain text log, add a screenshot)

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

### PR DESCRIPTION
**Pull request by Thalley**
Use the defined min and max values for offset instead
of UINT8_MAX.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

fixes https://github.com/zephyrproject-rtos/zephyr/issues/40236

### CODE REVIEW

**Review by hakehuang — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/shell/vcs_client.c [hunk 1]
```diff
@@ -622,9 +622,9 @@ static int cmd_vcs_client_vocs_offset_set(const struct shell *sh,
 		return -ENOEXEC;
 	}
 
-	if (offset > UINT8_MAX || offset < -UINT8_MAX) {
+	if (offset > BT_VOCS_MAX_OFFSET || offset < -UINT8_MAX) {
```
Comment (asbjornsabo) [inline subsys/bluetooth/shell/vcs_client.c:625]: Why is only one of the limits replaced here?
Without looking at the code in detail, this case seems very analogous to the one in the other file, where both limits have been replaced.

**Review by asbjornsabo — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/shell/vcs_client.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/shell/vcs_client.c]: Good question; not sure how that happened. Must've forgot to save the file. Thanks!

**Review by asbjornsabo — APPROVED** [review]
