### PR TITLE
Bluetooth: Mesh: Fixes Relay to frnd_cred message

### LINKED ISSUE #29544: Bluetooth: Mesh: Friend node unable relay message for lpn
As defined by Mesh Specification 1.0.1 Section  3.6.6.2 Friendship security.

`The Low Power node then decides to send two messages: OutMsg1 and OutMsg2. OutMsg1 is sentsecured using the friend security credentials and therefore only the Friend node will receive and relay thismessage. When the Friend node relays OutMsg1, the message will be retransmitted using the mastersecurity credentials. OutMsg2 is sent secured using the master security credentials and therefore theFriend node and any other Relay node within range of the Low Power node can relay the message.OutMsg2, when it is relayed, will be retransmitted using the master security credentials. `

If low power node publish with unicast address other than friend address, the friend node not relayed this message, no matter friend cred used.

https://github.com/zephyrproject-rtos/zephyr/blob/ba9fd65a4bfaeb193f84b52f3e0bf09e1ac2adfc/subsys/bluetooth/mesh/net.c#L797-L805

Another problem in `bt_mesh_net_relay`
https://github.com/zephyrproject-rtos/zephyr/blob/ba9fd65a4bfaeb193f84b52f3e0bf09e1ac2adfc/subsys/bluetooth/mesh/net.c#L614-L618

This implementation obviously prohibit relay message for low power node, even local is friend node.

### PR DESCRIPTION
**Pull request by LingaoM**
If low power node publish with unicast address other
than friend address, the friend node should relayed
this message to all network interface.

Fixes: #29544

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

### CODE REVIEW

File: subsys/bluetooth/mesh/net.c [hunk 1]
```diff
@@ -661,18 +662,17 @@ static void bt_mesh_net_relay(struct net_buf_simple *sbuf,
...
 	 */
 	if (IS_ENABLED(CONFIG_BT_MESH_GATT_PROXY) &&
-	    bt_mesh_gatt_proxy_get() == BT_MESH_GATT_PROXY_ENABLED) {
-		if (bt_mesh_proxy_relay(&buf->b, rx->ctx.recv_dst) &&
-		    BT_MESH_ADDR_IS_UNICAST(rx->ctx.recv_dst)) {
-			goto done;
-		}
+	    (rx->friend_match ||
+	     bt_mesh_gatt_proxy_get() == BT_MESH_GATT_PROXY_ENABLED)) {
+		bt_mesh_proxy_relay(&buf->b, rx->ctx.recv_dst);
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/net.c:672]: I don't think the destination can be both an LPN and a proxy client at the same time, can it? I.e. this looks like an unnecessary check here.

File: subsys/bluetooth/mesh/net.c [hunk 2]
```diff
@@ -63,7 +63,7 @@
 
 static struct {
 	uint32_t src : 15, /* MSb of source is always 0 */
-	      seq : 17;
+			 seq : 17;
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/net.c:66]: Please don't mix coding style cleanups into a patch with functional changes (you can still have them in the same PR but in separate commits)

File: subsys/bluetooth/mesh/net.c [hunk 3]
```diff
@@ -76,7 +76,7 @@ NET_BUF_POOL_DEFINE(loopback_buf_pool, CONFIG_BT_MESH_LOOPBACK_BUFS,
 		    LOOPBACK_MAX_PDU_LEN, LOOPBACK_USER_DATA_SIZE, NULL);
 
 static uint32_t dup_cache[CONFIG_BT_MESH_MSG_CACHE_SIZE];
-static int   dup_cache_next;
+static int dup_cache_next;
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/net.c:79]: Same here regarding coding style and functional changes

File: subsys/bluetooth/mesh/net.c [hunk 4]
```diff
@@ -624,7 +625,7 @@ static void bt_mesh_net_relay(struct net_buf_simple *sbuf,
 	 * Anything else (like GATT to adv, or locally originated packets)
 	 * use the Network Transmit state.
 	 */
-	if (rx->net_if == BT_MESH_NET_IF_ADV) {
+	if (rx->net_if == BT_MESH_NET_IF_ADV && !rx->friend_match) {
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/net.c:628]: Could you explain this change a bit more? The protocol between LPN and Friend is timing and request-response based. Is there somewhere in the spec that says that it should use the RelayRetransmit state rather than the NetworkTransmit state?

**Review by jhedberg — CHANGES_REQUESTED** [review]
See my inline comments

File: subsys/bluetooth/mesh/net.c (hunk 1 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/net.c]: Sorry, obviously it should be friend_cred.

File: subsys/bluetooth/mesh/net.c (hunk 4 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/net.c]: Please see Mesh Specification 1.0.1 Section 3.6.6.2 Friendship security for more information.
`The Low Power node then decides to send two messages: OutMsg1 and OutMsg2. OutMsg1 is sentsecured using the friend security credentials and therefore only the Friend node will receive and relay thismessage. When the Friend node relays OutMsg1, the message will be retransmitted using the mastersecurity credentials.`

File: subsys/bluetooth/mesh/net.c [hunk 5]
```diff
@@ -661,18 +662,17 @@ static void bt_mesh_net_relay(struct net_buf_simple *sbuf,
...
 	 */
 	if (IS_ENABLED(CONFIG_BT_MESH_GATT_PROXY) &&
-	    bt_mesh_gatt_proxy_get() == BT_MESH_GATT_PROXY_ENABLED) {
-		if (bt_mesh_proxy_relay(&buf->b, rx->ctx.recv_dst) &&
-		    BT_MESH_ADDR_IS_UNICAST(rx->ctx.recv_dst)) {
-			goto done;
-		}
+	    (rx->friend_cred ||
+	     bt_mesh_gatt_proxy_get() == BT_MESH_GATT_PROXY_ENABLED)) {
+		bt_mesh_proxy_relay(&buf->b, rx->ctx.recv_dst);
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/net.c:672]: Unless it breaks qualification, I think the old unicast address check should still be here. If a unicast message is going to a proxy node, there's no reason to relay it to the advertising bearer.

Comment (LingaoM) [reply subsys/bluetooth/mesh/net.c:672]: Yes, it is suitable for white list, but if it is for black list, even unicast address does not mean it is required by proxy client.

Comment (LingaoM) [reply subsys/bluetooth/mesh/net.c:672]: I am thinking, if blacklist filtering is enabled, if the unicast address is not in the blacklist, does it mean that the proxy client needs this unicast address? In this case, it does not need to be relayed through ADV bearer.

Comment (trond-snekvik) [reply subsys/bluetooth/mesh/net.c]: Good point, I forgot the proxy puts the unicast addresses in the filters. I suppose we can only be sure of this check if the proxy is using a whitelist. Your original version was better, I didn't consider the blacklist.

**Review by trond-snekvik — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
