### PR TITLE
Stm32 external dcache support for drivers

### LINKED ISSUE #89218: CONFIG_DCACHE=y causing issues in UART driver on STM32U5 devices
**Describe the bug**

`CONFIG_DCACHE` is now enabled for STM32U5 and other devices, which have ST proprietary DCache.
This is related to PR #88585.
The DCache on these devices affects only external memories (internal SRAM is not cached). This can cause issues in some scenarios.

**To Reproduce**

Example `samples\boards\st\uart\circular_dma` on `nucleo_u575zi_q` doesn't work properly. The driver refuses the async API, since it checks the DMA buffer in `buf_in_nocache` function in `drivers\serial\uart_stm32.c` file.
To compile the example, I'm using:
`west build -p -b nucleo_u575zi_q samples\boards\st\uart\circular_dma`

**Expected behavior**

There are few ways how to handle this:
1. Don't enable `CONFIG_DCACHE` by default or give user the option to disable it. But I'm not sure what is feasible in current system.
2. Modify the `buf_in_nocache` to allow internal SRAM as non-cacheable.
  a. This function should be probably moved outside UART driver
  b. We need to check if there are STM32 devices that have ST DCache affecting internal memories as well

**Impact**

This issue is concerning UART driver and STM32U5, but it might affect all drivers where DMA is involved.
Additional devices that might be affected: STM32L5, STM32H5, STM32WBA.
Related issue #89098 

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Windows 11
 - Toolchain Zephyr SDK
 - Commit SHA: 9de3d6bf643455493dad32eda0c496cb97ee221a

**Additional context**

### PR DESCRIPTION
**Pull request by lindblandro**
For drivers that check for `CONFIG_DCACHE` the recent changes from #88585 enable the DCACHE peripheral for a bunch of STM32 Cortex-M33 chips. Some drivers, when configured to use DMA check if DCACHE option is enabled and proceed to check whether the buffer resides in cached memory. The STM32 DCACHE peripheral only supports external memories so the buffer validation lacks a simple check for external cache controllers. Also, the same buffer validation function has essentially been copy pasted in many drivers so this PR moves that to a shared location under soc/.

Fixes #89218

### CODE REVIEW

**Comment by lindblandro** [comment]
This is related but already aproved so didn't add a fix in this PR https://github.com/zephyrproject-rtos/zephyr/pull/89103

**Comment by erwango** [comment]
^^@ABESTM

**Review by JarmouniA — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -1830,12 +1799,10 @@ static int uart_stm32_async_rx_buf_rsp(const struct device *dev, uint8_t *buf,
 	} else if (!data->dma_rx.enabled) {
 		err = -EACCES;
 	} else {
-#ifdef CONFIG_DCACHE
 		if (!buf_in_nocache((uintptr_t)buf, len)) {
```
[the remark this answers is not in the document]
Comment (lindblandro) [reply drivers/serial/uart_stm32.c:1802]: My purpose was to increase readability by shifting the work to the compiler as @erwango noted. However, I think it might require `CONFIG_LTO` (and `CONFIG_ISR_TABLES_LOCAL_DECLARATION` as a requisite) to get the unnecessary functions fully. Enabling LTO is not supported on all platforms, but for Arm it is.

I did a quick test by enabling LTO for the circular dma sample mentioned in the linked issue. In the first build I just converted `buf_in_nocache()` to return a constant value and it was unconditionally called. In the second build I used the same version of `buf_in_nocache()` as in this PR and it was gated behind a preprocessor macro.

```
# with LTO & constant function unconditionally called
Memory region         Used Size  Region Size  %age Used
           FLASH:       23576 B         2 MB      1.12%
             RAM:        9304 B       768 KB      1.18%
        IDT_LIST:          0 GB        32 KB      0.00%

# with LTO & standard function behind ifdefs
Memory region         Used Size  Region Size  %age Used
           FLASH:       23576 B         2 MB      1.12%
             RAM:        9304 B       768 KB      1.18%
        IDT_LIST:          0 GB        32 KB      0.00%
```
So identical binary sizes (unsurprisingly). Without LTO the gated version has slightly smaller binary size

```
Constant function
Memory region         Used Size  Region Size  %age Used
           FLASH:       26224 B         2 MB      1.25%
             RAM:        9312 B       768 KB      1.18%
        IDT_LIST:          0 GB        32 KB      0.00%

ifdefs
Memory region         Used Size  Region Size  %age Used
           FLASH:       26140 B         2 MB      1.25%
             RAM:        9312 B       768 KB      1.18%
        IDT_LIST:          0 GB        32 KB      0.00%
```

I didn't check if the function was called or not in this case, but I couldn't coax godbolt to give me an example that _wouldn't_ bypass a function call when it evaluated to a constant if optimizations were enabled, even without LTO.

File: soc/st/stm32/common/stm32_cache.c [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#include "stm32_cache.h"
+#include <zephyr/linker/linker-defs.h>
+#include <zephyr/mem_mgmt/mem_attr.h>
+#include <zephyr/dt-bindings/memory-attr/memory-attr-arm.h>
+
+/* Returns true if given buffer is in a non-cacheable SRAM region.
+ * This is determined using the device tree, meaning the .nocache region won't work.
```
[the remark this answers is not in the document]
Comment (lindblandro) [reply soc/st/stm32/common/stm32_cache.c:12]: I'll just remove the comment as it should be clear from the code what it does.

File: drivers/serial/uart_stm32.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (ABESTM) [reply drivers/serial/uart_stm32.c:1802]: The solution could be to define `buf_in_nocache` as `static ALWAYS_INLINE` when `CONFIG_DCACHE=n` and otherwise keep it. However, I'm not sure if this is in line with the coding standards.
This should then optimize out the `buf_in_nocache` even without LTO. I would also rename it to clarify it is STM32 specific, so something like `stm32_buf_in_no_cache`.

File: soc/st/stm32/common/stm32_cache.c [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+		return true;
+	}
+#endif /* CONFIG_EXTERNAL_CACHE */
+
+#ifdef CONFIG_NOCACHE_MEMORY
+	buf_within_nocache = (buf >= ((uintptr_t)_nocache_ram_start)) &&
+			     ((buf + len_bytes - 1) <= ((uintptr_t)_nocache_ram_end));
+	if (buf_within_nocache) {
+		return true;
+	}
```
Comment (mathieuchopstm) [inline soc/st/stm32/common/stm32_cache.c:41]: Thanks to above pre-computation (+ fix upper boundary check, style and bring back comment):
```suggestion
	/* Check if buffer is in NOCACHE region defined by the linker */
	if (((uintptr_t)_nocache_ram_start) <= buf && buf_end < ((uintptr_t)_nocache_ram_end)) {
		return true;
	}
```

File: soc/st/stm32/common/stm32_cache.c [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+#endif /* CONFIG_NOCACHE_MEMORY */
+
+#ifdef CONFIG_MEM_ATTR
+	buf_within_nocache =
+		mem_attr_check_buf((void *)buf, len_bytes, DT_MEM_ARM_MPU_RAM_NOCACHE) == 0;
+	if (buf_within_nocache) {
+		return true;
+	}
```
Comment (mathieuchopstm) [inline soc/st/stm32/common/stm32_cache.c:49]: Ditto (+ bring back comment)
```suggestion
	/* Check if buffer is in a region marked NOCACHE in DT */
	if (mem_attr_check_buf((void *)buf, len_bytes, DT_MEM_ARM_MPU_RAM_NOCACHE) == 0) {
		return true;
	}
```

File: soc/st/stm32/common/stm32_cache.c [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+#endif /* CONFIG_MEM_ATTR */
+
+	buf_within_nocache = (buf >= ((uintptr_t)__rodata_region_start)) &&
+			     ((buf + len_bytes - 1) <= ((uintptr_t)__rodata_region_end));
+
+	return buf_within_nocache;
```
Comment (mathieuchopstm) [inline soc/st/stm32/common/stm32_cache.c:55]: Ditto (+ bring back comment)
```suggestion
	/* Check if buffer is in read-only region, which cannot
	 * be stale due to DCACHE because it is not writeable.
	 */
	if (((uintptr_t)__rodata_region_start) <= buf && buf_end < ((uintptr_t)__rodata_region_end)) {
		return true;
	}

	/* Not in any region known to be NOCACHE */
	return false;
```
(which means the `buf_within_nocache` variable can be removed entirely)

**Review by mathieuchopstm — COMMENTED** [review]
\+ general remarks about the file's layout

**Review by JarmouniA — APPROVED** [review]

**Comment by lindblandro** [comment]
Are some of the CI jobs in a limbo as it says "waiting for status to be reported"?

**Comment by erwango** [comment]
> Are some of the CI jobs in a limbo as it says "waiting for status to be reported"?

I'm seeing this also frequently lately. Have a try to rebase on recent main.
@nashif is that a known issue ?

**Comment by erwango** [comment]
@lindblandro We need to test these changes more widely

**Comment by lindblandro** [comment]
> @lindblandro We need to test these changes more widely

Ack :+1:

File: drivers/adc/adc_stm32.c [hunk 6]
```diff
@@ -315,13 +286,13 @@ static int check_buffer(const struct adc_sequence *sequence,
 		return -ENOMEM;
 	}
 
-#if defined(CONFIG_ADC_STM32_DMA) && defined(CONFIG_SOC_SERIES_STM32H7X)
+#if defined(CONFIG_ADC_STM32_DMA)
```
Comment (djiatsaf-st) [inline drivers/adc/adc_stm32.c:289]:
```suggestion
#if defined(CONFIG_ADC_STM32_DMA) && defined(CONFIG_SOC_SERIES_STM32H7X)
```

After running tests on this PR in CI for multiple series, there is a regression in the `adc_api` driver test for the `Nucleo_F746ZG` with the following log:
```
Running TESTSUITE adc_basic
===================================================================
START - test_adc_asynchronous_call
E: Supplied buffer is not in a non-cacheable region according to DTS.

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/adc/adc_api/src/test_adc.c:223: test_task_asynchronous_call: (ret not equal to 0)
adc_read_async() failed with code -22
 FAIL - test_adc_asynchronous_call in 0.022 seconds
===================================================================
[...]
```

After reintroducing the condition `&& defined(CONFIG_SOC_SERIES_STM32H7X)`, all tests passed for all series. There may be another way to solve the issue, but adding this condition makes everything work well.

**Review by djiatsaf-st — CHANGES_REQUESTED** [review]

**Review by JarmouniA — CHANGES_REQUESTED** [review]

**Review by JarmouniA — DISMISSED** [review]

File: drivers/adc/adc_stm32.c (hunk 6 above)
Comment (lindblandro) [reply drivers/adc/adc_stm32.c:289]: Any consensus on this? It's a trivial addition and a similar fix seems to be in place for `nucleo_h743zi`.

**Review by djiatsaf-st — DISMISSED** [review]

**Comment by lindblandro** [comment]
Rebased to fix merge conflicts.

**Review by JarmouniA — DISMISSED** [review]

**Comment by lindblandro** [comment]
Anybody still reviewing this? :)

**Review by djiatsaf-st — DISMISSED** [review]
I'm already fine with this PR; just waiting for @erwango 's approval

File: soc/st/stm32/common/stm32_cache.c [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+#else
+	bool buf_within_nocache = false;
+
+#ifdef CONFIG_EXTERNAL_CACHE
+	buf_within_nocache = (buf >= ((uintptr_t)_image_ram_start) &&
+			      (buf + len_bytes - 1) <= ((uintptr_t)_image_ram_end));
+	if (buf_within_nocache) {
+		return true;
+	}
+#endif /* CONFIG_EXTERNAL_CACHE */
```
[the remark this answers is not in the document]
Comment (mathieuchopstm) [reply soc/st/stm32/common/stm32_cache.c]: After checking, it seems I was mistaken w.r.t. (1) - at least, I wasn't able to find code that appeared to do what I described. Heaps seem to be mere buffers in `noinit` section, so they *should* be covered in `_image_ram_{start/end}` range.
I agree with the point about external memories being untrustable, but it still seems like a valid use case to me, so I'm not keen on dismissing it as "will never happen".

Heaps are created as a plain `char[...]` so I don't think they have any special linker symbols associated to them. But c.f. above, it seems I was wrong and we can ignore this.

To close/TL;DR: I'm fine in current state *with a small request to add a note in the comment indicating that the check spuriously return `true` if Zephyr image RAM is in external memory*. This ensures the limitation is documented.

File: soc/st/stm32/common/stm32_cache.c [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+#include <zephyr/dt-bindings/memory-attr/memory-attr-arm.h>
+#include <zephyr/sys/math_extras.h>
+
+bool stm32_buf_in_nocache(uintptr_t buf, size_t len_bytes)
+{
+#ifndef CONFIG_DCACHE
+	ARG_UNUSED(buf);
+	ARG_UNUSED(len_bytes);
+	return true;
+#else
```
Comment (mathieuchopstm) [inline soc/st/stm32/common/stm32_cache.c]: This entire file is `zephyr_sources_ifdef(CONFIG_DCACHE stm32_cache.c)`, so this cannot happen?

**Review by mathieuchopstm — COMMENTED** [review]
One remark, otherwise LGTM.

File: soc/st/stm32/common/stm32_cache.c (hunk 8 above)
Comment (JarmouniA) [reply soc/st/stm32/common/stm32_cache.c]: Good catch

**Review by ABESTM — APPROVED** [review]
LGTM

File: soc/st/stm32/common/stm32_cache.c (hunk 8 above)
Comment (lindblandro) [reply soc/st/stm32/common/stm32_cache.c]: Probably forgot to remove. The default implementation was moved to the header, making this unnecessary. Do you wish me to remove it now?

Comment (mathieuchopstm) [reply soc/st/stm32/common/stm32_cache.c]: Yes please.

File: soc/st/stm32/common/stm32_cache.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (lindblandro) [reply soc/st/stm32/common/stm32_cache.c]: Added a note about this.

File: soc/st/stm32/common/stm32_cache.c (hunk 8 above)
Comment (lindblandro) [reply soc/st/stm32/common/stm32_cache.c]: Done :)

**Comment by lindblandro** [comment]
Included a couple of minor changes requested by @mathieuchopstm

**Review by JarmouniA — APPROVED** [review]

**Review by mathieuchopstm — APPROVED** [review]

**Review by erwango — APPROVED** [review]
