### PR TITLE
net: http_client: Fix payload issue on HTTP upload

### LINKED ISSUE #24431: http_client assumes request payload is non-binary
`http_client.c` uses `strlen` (in `http_send_data`) to calculate request `payload` size, instead of using `payload_len` that is provided by the user. This is incorrect and results in writing fewer bytes than is expected by the server when `payload` is binary. 

An additional issue is that when `payload_cb` is used by the user to provide data via callback, no `Content-Length` is sent by `http_client` event if `payload_len` is provided. By the time `payload_cb` is invoked to provide the data the request headers have already been sent.

### PR DESCRIPTION
**Pull request by arvinf**
Bug fix and improved `payload` handling in `http_client_req`.

Changes to `http_client_req` behaviour:

If the user provides `payload_len` it is used to generate the `Content-Length`
header. This is done even if `payload_cb` is used to provide the actual data.
If no `payload_len` is specified then no `Content-Length` is generated.

If `payload_cb` is provided it is called to send the payload data.
Otherwise `payload` is used as the payload buffer and sent. If
`payload_len` is not zero, it is used as the size of `payload`. Otherwise
`payload` is assumed to be a string and `strlen` is used to determine its size.
This is to maintain current behaviour and not break existing samples.

Fixes #24431

### CODE REVIEW

File: subsys/net/lib/http/http_client.c [hunk 1]
```diff
@@ -568,9 +568,27 @@ int http_client_req(int sock, struct http_request *req,
 		total_sent += ret;
 	}
 
-	if (req->payload_cb) {
-		ret = http_send_data(sock, send_buf, send_buf_max_len,
+	if ((req->payload) || (req->payload_cb)) {
```
Comment (jukkar) [inline subsys/net/lib/http/http_client.c:571]: Unnecessary () here, just do
```
if (req->payload || req->payload_cb) {
```

File: subsys/net/lib/http/http_client.c [hunk 2]
```diff
@@ -568,9 +568,27 @@ int http_client_req(int sock, struct http_request *req,
...
+			}
+
+			ret = http_send_data(sock, send_buf, send_buf_max_len,
+					     &send_buf_pos, "Content-Length", ": ",
+					     content_len_str, HTTP_CRLF,
+					     HTTP_CRLF, NULL);
+		}else {
+			ret = http_send_data(sock, send_buf, send_buf_max_len,
 				     &send_buf_pos, HTTP_CRLF, NULL);
+
```
Comment (jukkar) [inline subsys/net/lib/http/http_client.c:589]: Remove extra empty line

File: subsys/net/lib/http/http_client.c [hunk 3]
```diff
@@ -568,9 +568,27 @@ int http_client_req(int sock, struct http_request *req,
...
+			if (ret <= 0 || ret >= HTTP_CONTENT_LEN_SIZE) {
+				ret = -ENOMEM;
+				goto out;
+			}
+
+			ret = http_send_data(sock, send_buf, send_buf_max_len,
+					     &send_buf_pos, "Content-Length", ": ",
+					     content_len_str, HTTP_CRLF,
+					     HTTP_CRLF, NULL);
+		}else {
```
Comment (jukkar) [inline subsys/net/lib/http/http_client.c:586]: space between `}else`

**Review by jukkar — CHANGES_REQUESTED** [review]
> If the user provides `payload_len` it is used to generate the `Content-Length`
> header. This is done even if `payload_cb` is used to provide the actual data.
> If no `payload_len` is specified then no `Content-Length` is generated.

This changes the API as the client documentation says
```
	/** Payload length, may be 0. Only used if payload field is not NULL */
	size_t payload_len;
```
Could you change the comment to something like
```
Payload length, may be 0. Should not be set if sending chunked data.
```
Fix also the checkpatch warnings.

**Review by jukkar — APPROVED** [review]
LGTM
