### PR TITLE
drivers: pwm: Fix build error and capture support bug

### LINKED ISSUE #104435: Build failure on NXP RT1176 with CONFIG_PWM_CAPTURE enabled
### Describe the bug

When building PWM applications with `CONFIG_PWM_CAPTURE` enabled, the build fails with undefined definitions for `PWM_SetFilterSampleCount` and `PWM_SetFilterSamplePeriod`. These function definitions are guarded by `FSL_FEATURE_PWM_HAS_INPUT_FILTER_CAPTURE` flag which is not defined for RT11XX family. The following change fixes the build:
```
--- a/drivers/pwm/pwm_mcux.c
+++ b/drivers/pwm/pwm_mcux.c
@@ -464,11 +464,14 @@ static int mcux_pwm_configure_capture(const struct device *dev,
        /* Setup input capture on channel */
        PWM_SetupInputCapture(config->base, config->index, pwm_channel, &capture_config);
 
+#if defined(FSL_FEATURE_PWM_HAS_INPUT_FILTER_CAPTURE) && \
+       (FSL_FEATURE_PWM_HAS_INPUT_FILTER_CAPTURE == 1U)
        /* Set capture filter */
        PWM_SetFilterSampleCount(config->base, pwm_channel, config->index,
                config->input_filter_count);
        PWM_SetFilterSamplePeriod(config->base, pwm_channel, config->index,
                config->input_filter_period);
+#endif
 
        return 0;
 }

```
but the PWM capture doesn't seem to work for simple loopback test from channel A to B of PWM submodule 0:
```
 <wrn> pwm_capture: pwm capture timed out
```

Have anyone tested FlexPWM driver for input capture (with/without input filter) on RT11XX series?
Is this a known issue?

### Regression

- [ ] This is a regression.

### Steps to reproduce

Build applications for NXP RT11XX family with `CONFIG_PWM_CAPTURE=y` and `pwm_capture_cycles` API used in code.

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by FelixWang47831**
1. Guard input filter functions with feature check
2. Refactor the PWM capture interrupt handler to properly support all three capture channels (A, B, and X).
3. Enable test for mimxrt1170_evk_mimxrt1176_cm4

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/104435

### CODE REVIEW

File: drivers/pwm/pwm_mcux.c [hunk 1]
```diff
@@ -304,6 +304,36 @@ static int mcux_pwm_calc_ticks(uint16_t first_capture, uint16_t second_capture,
...
+	struct pwm_mcux_capture_data *capture = &data->capture;
+	uint32_t ticks = 0;
+	int err = overflow_err;
+
+	if (err != 0) {
+		LOG_ERR("overflow_count overflows.");
+	} else {
+		err = mcux_pwm_calc_ticks(first_edge_value, second_edge_value, modValue,
+				capture->overflow_count, &ticks);
+		LOG_DBG("First edge capture: %d, second edge capture: %d,"
```
Comment (Holt-Sun) [inline drivers/pwm/pwm_mcux.c]: Should use `%u` for unsigned.

Comment (FelixWang47831) [reply drivers/pwm/pwm_mcux.c]: Fixed.

**Review by Holt-Sun — APPROVED** [review]

**Review by jsbatch — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]
