### PR TITLE
Fix json object array alignment

### LINKED ISSUE #73899: json: Bug in decoding arrays of structures
**Describe the bug**
In some cases when decoding substructures in an array the JSON parses skips fields in a result structure.

Noticed this while running tests on native_posix_64. After some digging, I guess that the json parser incorrectly computes the sizes of the array elements. In the example I provided the size of the inner structure is 12, but the parses thinks it's 16 and skips fields in the next array element. My guess is that this happens due to `JSON_OBJ_DESCR_OBJ_ARRAY` assigning incorrect align_shift to the array's element descriptor causing the size to round up more than it needs to. I don't see a straightforward way to fix this, so opening an issue.

Tested on the latest commit from main fd236ee991e704d4bb560a8d691b2f8b4da07ba6

**To Reproduce**
1. Insert code into the hello world sample:
```/*
 * Copyright (c) 2012-2014 Wind River Systems, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stdio.h>
#include <zephyr/data/json.h>

#define INNERS_MAX 10
struct inner {
	const int32_t A;
	const int32_t B;
	const int32_t C;
};

struct outer {
	const char* something;
	const struct inner inners[INNERS_MAX];
	size_t inners_len;
};

char json[] = "{"
	"\"something\" : \"Hello World!\", "
	"\"inners\": [ "
	"{ \"A\": 1, "
	"\"B\": 2, "
	"\"C\":  3 }, "
	"{ \"A\": 4, "
	"\"B\": 5, "
	"\"C\": 6 } "
	"] "
	"}";

static const struct json_obj_descr inner_spec_descr[] = {
	JSON_OBJ_DESCR_PRIM(struct inner, A, JSON_TOK_NUMBER),
	JSON_OBJ_DESCR_PRIM(struct inner, B, JSON_TOK_NUMBER),
	JSON_OBJ_DESCR_PRIM(struct inner, C, JSON_TOK_NUMBER),
};

static const struct json_obj_descr outer_spec_descr[] = {
	JSON_OBJ_DESCR_PRIM(struct outer, something, JSON_TOK_STRING),
	JSON_OBJ_DESCR_OBJ_ARRAY(struct outer, inners,
				 INNERS_MAX, inners_len,
				 inner_spec_descr,
				 ARRAY_SIZE(inner_spec_descr)),
};

int main(void)
{
	struct outer data;
	size_t json_size = sizeof(json) - 1;
	int ret;

	ret = json_obj_parse(json,
				 json_size, outer_spec_descr,
				 ARRAY_SIZE(outer_spec_descr), &data);

	printf("ret = %d\n", ret);
	printf("data.something = %s\n", data.something);
	printf("data.inners_len = %ld\n", data.inners_len);
	for (int i = 0; i < data.inners_len; i++) {
		printf("data.inners[%d].A = %d\n", i, data.inners[i].A);
		printf("data.inners[%d].B = %d\n", i, data.inners[i].B);
		printf("data.inners[%d].C = %d\n", i, data.inners[i].C);
	}
	return 0;
}
```
2. Add config `CONFIG_JSON_LIBRARY=y`
3.  `cd samples/hello_world`
4.  `west build -b native_posix_64 -p always -t run`

**Expected behavior**
```
*** Booting Zephyr OS build v3.6.0-5577-gfd236ee991e7 ***
ret = 3
data.something = Hello World!
data.inners_len = 2
data.inners[0].A = 1
data.inners[0].B = 2
data.inners[0].C = 3
data.inners[1].A = 4
data.inners[1].B = 5
data.inners[1].C = 6
```

**Actual behavior**
```
*** Booting Zephyr OS build v3.6.0-5577-gfd236ee991e7 ***
ret = 3
data.something = Hello World!
data.inners_len = 2
data.inners[0].A = 1
data.inners[0].B = 2
data.inners[0].C = 3
data.inners[1].A = 0
data.inners[1].B = 4
data.inners[1].C = 5
```

**Impact**
Annoyance

**Environment:**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.1
 - Commit SHA: fd236ee991e704d4bb560a8d691b2f8b4da07ba6

### PR DESCRIPTION
**Pull request by Deedone**
Currently, json array macros are passing the outer "container" struct
to the Z_JSON_ELEMENT_DESCR macro, causing the alignment to be calculated
from the outer struct which may be incorrect. Fix this by using the
biggest shift from the nested objects to calculate the alignment as the
struct size is calculated based on the biggest alignment of it's members.

Also add a test for such case.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/73899

### CODE REVIEW

File: lib/utils/json.c [hunk 1]
```diff
@@ -559,13 +559,18 @@ static ptrdiff_t get_elem_size(const struct json_obj_descr *descr)
...
 		ptrdiff_t total = 0;
+		uint32_t align_shift = 0;
 		size_t i;
 
 		for (i = 0; i < descr->object.sub_descr_len; i++) {
 			total += get_elem_size(&descr->object.sub_descr[i]);
+
+			if (descr->object.sub_descr[i].align_shift > align_shift) {
+				align_shift = descr->object.sub_descr[i].align_shift;
+			}
```
Comment (d3zd3z) [inline lib/utils/json.c:570]: Is it sufficient to just walk through this object, or do nested objects need to be traversed as well?

Comment (Deedone) [reply lib/utils/json.c:570]: Should be sufficient, AFAIK the shifts for structs and whole arrays are calculated correctly and we can't have Z_JSON_ELEMENT_DESCR nested directly. I also did some more testing with nested arrays and structs and everything seems to work fine.

**Review by d3zd3z — APPROVED** [review]

**Comment by aescolar** [comment]
@mrfuchs @sir-branch please review

**Review by ubieda — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]
