### PR TITLE
driver: hwinfo: nxp_rcm correct implementation of get_supported_reset…

### LINKED ISSUE #89163: drivers: hwinfo: hwinfo_mcux_rcm.c should report hwinfo_get_supported_reset_cause() correctly
**Describe the bug**
the function hwinfo_get_supported_reset_cause() reports  the causes for the current pending reset reasons.
But must list all possible values of reset_reason that can be detected by the driver.

seen in Zephyr 4.1, the implementation is used in NXP modules only.

this actual implementation returns the same values as for hwinfo_get_reset_cause()
`
int z_impl_hwinfo_get_supported_reset_cause(uint32_t *supported)
{
	uint32_t sources;

	sources = RCM_GetResetSourceImplementedStatus(RCM);
	*supported = hwinfo_mcux_rcm_xlate_reset_sources(sources);

	LOG_DBG("sources = 0x%08x, supported = 0x%08x", sources, *supported);

	return 0;
}
`

**To Reproduce**
check implementation code for hwinfo_get_supported_reset_cause()
in case of wrong implementation the sequence:
`
uint32_t value=0;
hwinfo_clear_reset_cause();
hwinfo_get_supported_reset_cause(&value);
`
value remains 0(zero)

**Expected behavior**
hwinfo_get_supported_reset_cause() must always return a consntat value matching all combinations of
hwinfo_get_reset_cause()

**Impact**

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Linux Ubuntu
 - Toolchain Zephyr SDK 0.17
 - Zephyr 4.1

**Additional context**

### PR DESCRIPTION
**Pull request by theadib**
…_cause()

The function should return all possible combinations for reset cause. Removed the surrounding #ifdef as the _xlate_() function is platform specific to handle all cases for the dedicated platform.

This PR should fix #89163
Somehow related to PR #89161 as the code and idea was taken from this driver.

Regards, Adib

### CODE REVIEW

File: drivers/hwinfo/hwinfo_mcux_rcm.c [hunk 1]
```diff
@@ -117,16 +117,11 @@ int z_impl_hwinfo_clear_reset_cause(void)
 }
 #endif /* (defined(FSL_FEATURE_RCM_HAS_SSRS) && FSL_FEATURE_RCM_HAS_SSRS) */
 
-#if (defined(FSL_FEATURE_RCM_HAS_PARAM) && FSL_FEATURE_RCM_HAS_PARAM)
```
Comment (alexanderwachter) [inline drivers/hwinfo/hwinfo_mcux_rcm.c:120]: Can you keep the ifdef please.
The reason is that supported function should return the same as the cause function in case the driver is not available.

**Review by alexanderwachter — CHANGES_REQUESTED** [review]
Thanks for this fix!

**Comment by alexanderwachter** [comment]
Fixes #89163

File: drivers/hwinfo/hwinfo_mcux_rcm.c (hunk 1 above)
Comment (theadib) [reply drivers/hwinfo/hwinfo_mcux_rcm.c:120]: Changed. 
But not sure if I understand correctly. In the case the driver is not available the whole module is not compiled.
There are also not #ifdefs around the cause function ...

**Review by alexanderwachter — APPROVED** [review]

File: drivers/hwinfo/hwinfo_mcux_rcm.c (hunk 1 above)
Comment (alexanderwachter) [reply drivers/hwinfo/hwinfo_mcux_rcm.c:120]: There is a default implementation that is weak. So calling it will give -ENOSYS

drivers/hwinfo/hwinfo_weak_impl.c

**Review by kartben — APPROVED** [review]
