### PR TITLE
netapp / LwM2M: local port support and LwM2M registration client changes

### LINKED ISSUE #7475: LwM2M: UDP local port setting not obeyed, random port doesn't work
I'm running into a number of fancy issues with LwM2M on a Nucleo-F429ZI board connected via Ethernet.

_If_ the app is actually capable of sending out packets over the network I'm getting the following output:
```
[lib/lwm2m_rd_client] [INF] sm_do_init: RD Client started with endpoint 'nucleo_f429zi' and client lifetime 30
[lib/lwm2m_rd_client] [DBG] sm_send_registration: registration sent [212.18.24.70]
[lib/lwm2m_engine] [DBG] retransmit_request: Resending message: 0x20004024
[lib/lwm2m_engine] [DBG] retransmit_request: Resending message: 0x20004024
[lib/lwm2m_engine] [DBG] retransmit_request: Resending message: 0x20004024
[lib/lwm2m_engine] [DBG] retransmit_request: Resending message: 0x20004024
[lib/lwm2m_rd_client] [WRN] do_registration_timeout_cb: Registration Timeout
```

Further investigation with a mirrored port and wireshark shows that the packet is actually sent out, and ACKed by the server but the source IP chosen by zephyr is actually random instead of the configured port via `CONFIG_LWM2M_LOCAL_PORT=5683` and for some reason Zephyr doesn't route the reply sent to the chosen source port back to the receive function to the app but generates a ICMP message "Destination unreachable".

### PR DESCRIPTION
**Pull request by mike-scott**
The netapp layer didn't support setting the local_port of a new client.  This was required to fix https://github.com/zephyrproject-rtos/zephyr/issues/7475.

This patchset does the following:
- Fix a byte-order bug in the netapp layer
- Add local port handling to the netapp layer based on the client_addr parameter pass into the init function
- Set the local port for the LwM2M client based on CONFIG_LWM2M_LOCAL_PORT setting.
- Set the local port for the LwM2M client firmware update connection based on a new config: CONFIG_LWM2M_FIRMWARE_UPDATE_PULL_LOCAL_PORT.
- Use random ports as default instead of the previous setting so we don't change functionality for current users due to the bugfix
- Remove the multi-server logic of the LwM2M registration client as it doesn't work if the local port of the client is customized, and it's kind of a hot mess at the moment and needs to be re-thought out.  This cleanup makes implementing bootstrap support much easier.

This fixes: https://github.com/zephyrproject-rtos/zephyr/issues/7475

### CODE REVIEW

**Comment by mike-scott** [comment]
@therealprof feel free to review and comment

**Comment by mike-scott** [comment]
@rbtchc if you have time, please take a look

**Review by rbtchc — CHANGES_REQUESTED** [review]
Tested w/ Qemu_x86 and Wakaama server. 
Can assign local port as patch described.

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 1]
```diff
@@ -3851,11 +3851,23 @@ static int setup_cert(struct net_app_ctx *app_ctx, void *cert)
...
 		       char *peer_str, u16_t peer_port)
 {
+	struct sockaddr client_addr;
 	int ret = 0;
 
 	/* TODO: use security object for initial setup */
+
+	/* setup the local client port */
+	memset(&client_addr, 0, sizeof(client_addr));
+#if defined(CONFIG_NET_IPV6)
```
Comment (jukkar) [inline subsys/net/lib/lwm2m/lwm2m_engine.c]: This probably does not work as planned if both IPv6 and IPv4 are enabled. If peer address in peer_str is IPv4 one, then we would set the family to IPv6 here (if both IPv6 and v4 are enabled) instead of IPv4. IMHO we need to check this at runtime. Note that there is net_ipaddr_parse() function that can be used to parse IP address string and get the family.

File: subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c [hunk 2]
```diff
@@ -478,7 +479,20 @@ static void firmware_transfer(struct k_work *work)
 	tmp = server_addr[off + len];
 	server_addr[off + len] = '\0';
 
-	ret = net_app_init_udp_client(&firmware_ctx.net_app_ctx, NULL, NULL,
+	/* setup the local firmware download client port */
+	memset(&client_addr, 0, sizeof(client_addr));
+#if defined(CONFIG_NET_IPV6)
```
Comment (jukkar) [inline subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c]: Shouldn't we set the local family depending on what is the IP address type of the server?

**Review by jukkar — CHANGES_REQUESTED** [review]
Looks good, some comments about setting IP address family.

**Comment by therealprof** [comment]
@jukkar The whole network and source selection stuff is still in early infancy. At the moment addresses are kept separately for IPv4 and IPv6 and it is not quite clear to me which one is used when. I can't really use IPv6 due to #6307 but when I work around the issues and end up with booting device it still doesn't work due to some other issue and there's no fall back to IPv4.

In an ideal world I would indeed except that there's one (or two for the BS server) endpoint specified and the system would figure out how to reach that by itself.

**Review by therealprof — COMMENTED** [review]
I find the network byte order swapping a bit confusing and can't vouch for correctness. I can confirm that communication still works after the change with and without random port however I can't verify at the moemnt that the packets really leave the device as claimed by Zephyr.

**Comment by jukkar** [comment]
> In an ideal world I would indeed except that there's one (or two for the BS server) endpoint specified and the system would figure out how to reach that by itself.

I was actually not talking about two network endpoints and their selection.

In the lwm2m_engine_start() function, the peer_str string contains probably the IP address of the peer. We can deduct from that what is the source IP address family that we should use. With the proposed code that selection will fail IPv6 and IPv4 are enabled but the peer address is IPv4. Similar runtime selection of IP address family is done in other parts of the system so I think we should handle this properly here too.

**Comment by jukkar** [comment]
> I find the network byte order swapping a bit confusing and can't vouch for correctness

Looks ok to me, the addresses/ports in sockaddr struct should always be in network byte order (because of consistency), thus we need to do the conversion here.

File: subsys/net/lib/app/client.c [hunk 3]
```diff
@@ -379,12 +379,43 @@ int net_app_init_client(struct net_app_ctx *ctx,
...
+#if defined(CONFIG_NET_IPV6)
+		if (client_addr->sa_family == AF_INET6) {
+			empty_addr = net_is_ipv6_addr_unspecified(
+					&net_sin6(client_addr)->sin6_addr);
+			local_port = net_sin6(client_addr)->sin6_port;
+		}
+#endif
+
+		if (empty_addr) {
+			addr.sa_family = remote_addr.sa_family;
```
[the remark this answers is not in the document]
Comment (mike-scott) [reply subsys/net/lib/app/client.c]: Nice catch!  Removing.

File: subsys/net/lib/lwm2m/lwm2m_engine.c (hunk 1 above)
Comment (mike-scott) [reply subsys/net/lib/lwm2m/lwm2m_engine.c]: Yeah this part is confusing for sure.  The netapp layer doesn't use the client_addr IP type for anything other than deciding what function to call for pulling the port data (net_sin vs. net_sin6)
 in client.c line 385.   The local addr sa_family is assigned based on the remote_addr if the IP addr is unassigned (0).

File: subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c (hunk 2 above)
Comment (mike-scott) [reply subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c]: Same as above.  The netapp layer doesn't actually use the IP type if the IP address is unassigned.

**Comment by mike-scott** [comment]
> In an ideal world I would indeed except that there's one (or two for the BS server) endpoint specified and the system would figure out how to reach that by itself.

The eventual goal is to add DNS support when Bootstrap support is added.  During the name resolution stage, the system determines if there is an AAAA record for IPv6 or an A record for IPv4, so network selection becomes a function of what's available rather than hard-coded.

File: subsys/net/lib/app/client.c [hunk 4]
```diff
@@ -379,12 +379,43 @@ int net_app_init_client(struct net_app_ctx *ctx,
...
+		bool empty_addr = false;
 
-		if (addr.sa_family != remote_addr.sa_family) {
-			NET_DBG("Address family mismatch %d vs %d",
-				addr.sa_family, remote_addr.sa_family);
-			return -EINVAL;
+		addr.sa_family = remote_addr.sa_family;
+
+		/* local_port is used if the IP address isn't specified */
+#if defined(CONFIG_NET_IPV4)
```
Comment (mike-scott) [inline subsys/net/lib/app/client.c]: @jukkar This is the code I was referring to where the remote_addr family doesn't matter.  It's a bit sloppy for sure, but without changing the API from a sockaddr (client_addr) to a u16_t port, this is the best I could come up with.

**Comment by mike-scott** [comment]
Addressed @rbtchc comment: https://hastebin.com/avefewimes.hs

**Review by jukkar — APPROVED** [review]
LGTM
