### PR TITLE
kernel: sched: Disable FPU context when thread ends

### LINKED ISSUE #60678: `portability.posix.eventfd` is failing on `qemu_cortex_a53_smp`
On these PRs:

https://github.com/zephyrproject-rtos/zephyr/pull/60626/checks?check_run_id=15229833588
https://github.com/zephyrproject-rtos/zephyr/actions/runs/5620196109/job/15228779043

the test is failing with:

```
START - test_stress
BOARD: qemu_cortex_a53
TEST_DURATION_S: 5
UPDATE_INTERVAL_S: 1
223209 writes
223209 reads
451461 writes
451461 reads
682912 reads
682940 writes
914342 writes
914308 reads
avg: 228872 writes/s
avg: 228865 reads/s
E: ELR_ELn: 0x0000000000000000
E: ESR_ELn: 0x0000000086000006
E:   EC:  0x21 (Instruction Abort taken without a change in Exception level.)
E:   IL:  0x1
E:   ISS: 0x6
E: FAR_ELn: 0x0000000000000000
E: TPIDRRO: 0x0100000040034ca8
E: x0:  0x0000000000000000  x1:  0x0000000040031000
E: x2:  0x0000000000000000  x3:  0x0000000000000001
E: x4:  0x000000004007f3f0  x5:  0x000000000000000a
E: x6:  0x00000000ffffffd8  x7:  0x0000000000000073
E: x8:  0x000000000000000a  x9:  0x00000000ffffffff
E: x10: 0x0000000000000000  x11: 0x0000000000000000
E: x12: 0x0000000000000000  x13: 0x0000000000000000
E: x14: 0x0000000000000000  x15: 0x0000000000000000
E: x16: 0x0000000000000000  x17: 0x0000000000000000
E: x18: 0x0000000000000000  lr:  0x0000000000000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 1
E: Current thread: 0x400327b0 (test_stress)
E: Halting system
```

The problem was bisected down to https://github.com/zephyrproject-rtos/zephyr/commit/2bc980f83190b22f4aa3f6b1560b40ece649ed95 but the root cause must be still found.

### LINKED ISSUE #61454: ARM64: Saved FPU context accessed after thread ends
The following is with respect to ARM64, although this issue likely exists on other architectures too.

When `CONFIG_FPU_SHARING` is enabled each `k_thread` struct has a saved floating point context (`saved_fp_context`).
During a context switch, the current FPU owner's (`_current_cpu->arch.fpu_owner`) registers are saved to its `saved_fp_context`, and the destination threads FPU registers are loaded from its `saved_fp_context`.

When a thread ends, it does not release ownership of the FPU (`_current_cpu->arch.fpu_owner`).
This is problematic if the `k_thread` struct was allocated on the stack.
The next context switch will save the FPU registers into `k_thread -> saved_fp_context` which may now be out of scope.
This will likely (but not always) result in a crash.

**To Reproduce**

Source:

	#include <zephyr/kernel.h>
	
	static K_THREAD_STACK_DEFINE(thread_stack, 4096);
	
	static void thread_func(void *arg1, void *arg2, void *arg3)
	{
		printk("");
	}
	
	static void run_thread(void)
	{
		struct k_thread thread; // <-- make static to prevent crash
		k_thread_create(&thread, thread_stack, K_THREAD_STACK_SIZEOF(thread_stack),
				thread_func, NULL, NULL, NULL, 0, 0, K_NO_WAIT);
		k_thread_join(&thread, K_FOREVER);
	}
	
	int main(void)
	{
		printk("Start\n");
		run_thread();
		printk("done\n"); // <-- crash
		k_sleep(K_FOREVER);
		return 0;
	}

kconfig:

	CONFIG_LOG=y

Build and run:

	west build -b qemu_cortex_a53 path/to/test -t run

Output:

	*** Booting Zephyr OS build zephyr-v3.4.0-2252-gd11c0a1664f6 ***
	Start
	[00:00:00.050,000] <err> os: ELR_ELn: 0xffffff80ffffffc8
	[00:00:00.050,000] <err> os: ESR_ELn: 0x0000000086000004
	[00:00:00.050,000] <err> os:   EC:  0x21 (Instruction Abort taken without a change in Exception level.)
	[00:00:00.050,000] <err> os:   IL:  0x1
	[00:00:00.050,000] <err> os:   ISS: 0x4
	[00:00:00.050,000] <err> os: FAR_ELn: 0xffffff80ffffffc8
	[00:00:00.050,000] <err> os: TPIDRRO: 0x020000004001f6d8
	[00:00:00.050,000] <err> os: x0:  0x00000000400149d8  x1:  0x000000004001f000
	[00:00:00.050,000] <err> os: x2:  0x0000000000000000  x3:  0x00000000400086a4
	[00:00:00.050,000] <err> os: x4:  0x0000000040069380  x5:  0x0000000040068540
	[00:00:00.050,000] <err> os: x6:  0x0000000040068550  x7:  0x0000000000000000
	[00:00:00.050,000] <err> os: x8:  0x0000000000000000  x9:  0x0000000000000000
	[00:00:00.050,000] <err> os: x10: 0x0000000000000000  x11: 0x0000000000000000
	[00:00:00.060,000] <err> os: x12: 0x0000000000000000  x13: 0x0000000000000000
	[00:00:00.060,000] <err> os: x14: 0x0000000000000000  x15: 0x0000000000000000
	[00:00:00.060,000] <err> os: x16: 0x000000004001f000  x17: 0x0000000000000000
	[00:00:00.060,000] <err> os: x18: 0x0000000000000000  lr:  0xffffff80ffffffc8
	[00:00:00.060,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
	[00:00:00.060,000] <err> os: Current thread: 0x4001f000 (unknown)
	[00:00:00.060,000] <err> os: Halting system
	
This is also the root cause of https://github.com/zephyrproject-rtos/zephyr/issues/60678

### PR DESCRIPTION
**Pull request by gramsay0**
The following is with respect to ARM64, although this issue likely exists on other architectures too.

When `CONFIG_FPU_SHARING` is enabled each `k_thread` struct has a saved floating point context (`saved_fp_context`).
During a context switch, the current FPU owner's (`_current_cpu->arch.fpu_owner`) registers are saved to its `saved_fp_context`, and the destination threads FPU registers are loaded from its `saved_fp_context`.

When a thread ends, it does not release ownership of the FPU (`_current_cpu->arch.fpu_owner`).
This is problematic if the `k_thread` struct was allocated on the stack.
The next context switch will save the FPU registers into `k_thread -> saved_fp_context` which may now be out of scope.
This will likely (but not always) result in a crash.

Adding `arch_float_disable(thread);` when a thread ends disables preservation of floating point context information, fixing this issue

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/61454
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/60678

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]

**Review by npitre — APPROVED** [review]

**Comment by gramsay0** [comment]
Something was bugging me with this fix: shouldn't the "main" thread be the new FPU owner after the "test" thread ends?

I added some extra debug, printing out the FPU owner at different points (`CONFIG_THREAD_NAME=y`):

	#include <zephyr/kernel.h>
	
	static K_THREAD_STACK_DEFINE(thread_stack, 4096);
	
	static void print_fpu_owner(const char *str)
	{
		struct k_thread *fpu_owner = atomic_ptr_get(&_current_cpu->arch.fpu_owner);
		printk("%s: %s\n", str, fpu_owner != NULL ? fpu_owner->name : "NULL");
	}
	
	static void thread_func(void *arg1, void *arg2, void *arg3)
	{
		print_fpu_owner("thread_func 1");
		k_sleep(K_MSEC(1));
		print_fpu_owner("thread_func 2");
	}
	
	static void run_thread(void)
	{
		print_fpu_owner("run_thread 1");
		struct k_thread thread;
		k_thread_create(&thread, thread_stack, K_THREAD_STACK_SIZEOF(thread_stack),
				thread_func, NULL, NULL, NULL, 0, 0, K_FOREVER);
		k_thread_name_set(&thread, "test");
		k_thread_start(&thread);
		print_fpu_owner("run_thread 2");
		k_thread_join(&thread, K_FOREVER);
		print_fpu_owner("run_thread 3");
		k_sleep(K_MSEC(1));
		print_fpu_owner("run_thread 4");
	}
	
	int main(void)
	{
		printk("Start\n");
		run_thread();
		printk("done\n");
		k_sleep(K_FOREVER);
		return 0;
	}

Without fix from this PR:

	Start
	run_thread 1: main
	run_thread 2: main
	thread_func 1: main
	thread_func 2: test
	run_thread 3: test
	run_thread 4: main
	done

With fix:

	Start
	run_thread 1: main
	run_thread 2: main
	thread_func 1: main
	thread_func 2: test
	run_thread 3: NULL
	run_thread 4: main
	done

I think this should actually be:

	Start
	run_thread 1: main
	run_thread 2: main
	thread_func 1: test
	thread_func 2: test
	run_thread 3: main
	run_thread 4: main
	done

There are two issues:

1. when the test thread starts, it does not become the FPU owner until after switching contexts and then resuming
2. when the test thread ends,  the "main" thread does not become the FPU owner until after switching contexts and then resuming

I don't think my proposed change is the correct fix for the underlying issue

**Review by nashif — DISMISSED** [review]

**Comment by gramsay0** [comment]
Never mind my other (since deleted) comment, the FPU registers are saved/restored lazily by trapping FPU access exceptions. After adding some actual floating point operations I could see the FPU owner getting updated correctly

File: kernel/sched.c [hunk 1]
```diff
@@ -1714,6 +1714,10 @@ static void end_thread(struct k_thread *thread)
 		unpend_all(&thread->join_queue);
 		update_cache(1);
 
+#if defined(CONFIG_FPU) && defined(CONFIG_FPU_SHARING)
```
Comment (andyross) [inline kernel/sched.c:1717]: Why test both?  Surely the latter is the only one you need.

**Review by andyross — APPROVED** [review]
FWIW, longer term it might be better to have an arch_thread_end() hook or whatever.  There are other tricks that might want to be played, and we could stub the function out more appropriately to avoid the #if'ery.

File: kernel/sched.c (hunk 1 above)
Comment (gramsay0) [reply kernel/sched.c:1717]: I agree, only the latter check is needed, and also that `arch_thread_end` is a better place for this eventually
