### PR TITLE
drivers: video: common: fix video_closest_frmival() fie.index

### LINKED ISSUE #89663: drivers: video: common: API misuse in video_closest_frmival()
**Describe the bug**

`video_closest_frmival()` is expecting the driver to increment `fie.index`. This is not the correct API and having this in `video_common.c` and `video_emul_imager.c` is misleading. The tests is also wrong.

**To Reproduce**

The CI passes while it should fail as the test is testing the wrong thing:

https://github.com/zephyrproject-rtos/zephyr/blob/493be790ac6ea85f99ffcfc10c55602e32eedb32/tests/drivers/video/api/src/video_emul.c#L84-L86

**Expected behavior**

The driver does not increment `fie.index`, the caller does.

**Impact**

No public code currently uses it, but developers building new code will be confused. 

**Logs and console output**

**Environment (please complete the following information):**

CI

**Additional context**

A PR to fix it is already proposed here:

- https://github.com/zephyrproject-rtos/zephyr/pull/88003

But only one commit out of it is for the actual fix and can be split:

- https://github.com/zephyrproject-rtos/zephyr/pull/88003/commits/fd3677d26f4dae15c66a80b4ef14de617ac4471f

### PR DESCRIPTION
**Pull request by josuah**
Downstream:
- #88003

Fix bug introduced in 46a262ffe62d5e29bf54453de34104779d3e7385 where the fie.index field was expected to be incremented by the driver, while it is the responsibility of the caller to increment it.

Fixes #89663 
Split out of #88003

### CODE REVIEW

**Comment by josuah** [comment]
Example of implementation that correctly keep `fie.index` unchanged:

https://github.com/zephyrproject-rtos/zephyr/blob/af77efb77e912e109e8a9326c0b522c5058d9218/drivers/video/ov5640.c#L1195-L1221

**Review by avolmat-st — APPROVED** [review]

File: drivers/video/video_common.c [hunk 1]
```diff
@@ -153,10 +153,16 @@ void video_closest_frmival(const struct device *dev, enum video_endpoint_id ep,
 		a = video_frmival_nsec(&desired);
```
Comment (avolmat-st) [inline drivers/video/video_common.c:153]: One more small optimization if I get it right. This first calculation of the desired frmival (a) only has to be done once, so should be done before entering the while loop.

**Review by avolmat-st — CHANGES_REQUESTED** [review]

File: drivers/video/video_common.c [hunk 2]
```diff
@@ -153,10 +153,16 @@ void video_closest_frmival(const struct device *dev, enum video_endpoint_id ep,
...
 		b = video_frmival_nsec(&tmp);
 		diff_nsec = a > b ? a - b : b - a;
+
 		if (diff_nsec < best_diff_nsec) {
 			best_diff_nsec = diff_nsec;
 			match->index = fie.index;
 			memcpy(&match->discrete, &tmp, sizeof(tmp));
```
Comment (avolmat-st) [inline drivers/video/video_common.c:160]: what about simply doing match->discrete = tmp here ? Meaning, simply letting the compiler decide what is the best way to do that, and figure out optimization, depending on alignments etc. There is good chances that it would end up to be same as memcpy in this case but this is also I think more easy to read.

**Comment by josuah** [comment]
force-push:
- Apply extra improvement suggested

File: drivers/video/video_common.c (hunk 2 above)
Comment (josuah) [reply drivers/video/video_common.c]: Much better I agree!

File: drivers/video/video_common.c (hunk 1 above)
Comment (josuah) [reply drivers/video/video_common.c]: Applied thank you!

**Review by avolmat-st — APPROVED** [review]

**Review by ngphibang — APPROVED** [review]
