### PR TITLE
Bluetooth: Controller: Handle overlapping CIG and ACL

### LINKED ISSUE #98072: Bluetooth: Controller: Assert in ull_conn_iso.c due to negative cig_offset_us
### Describe the bug

This bug has always been in the ull since the first commit, if an ACL and a CIG/CIS overlaps when it tries to start a cis stream the code calculates negative time and asserts on that.
Overlapping ACL/CIS'es are allowed by the standard, possibly greater care should be taken to avoid them.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Switch streams a lot of times .. it seems that automatically restarting a stream is especially affected.
I have not been able to make a unittest to reproduce.

### Relevant log output

```shell
ull_conn_iso.c:1057 ull_conn_iso_start [assert]
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by segerlund**
If the cig and ACL overlap each other when the cis is starting zephyr will assert on negative time, so fit this special case.

Fixes #98072

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c [hunk 1]
```diff
@@ -979,6 +979,11 @@ void ull_conn_iso_start(struct ll_conn *conn, uint16_t cis_handle,
 				lost_cig_events = 1U;
 				cis_offset = cis->offset + iso_interval_us - acl_latency_us;
 			}
+			/* Correct if the ACL and cig overlaps. */
+			if (cis_offset < (cig->sync_delay-cis->sync_delay)) {
+				cis_offset += iso_interval_us;
+				lost_cig_events++;
+			}
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]: Is this correct for dissimilar CIG and ACL intervals?

How do you reproduce the issue being addressed in this PR? Please create a GH Issue with details.

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c (hunk 1 above)
Comment (segerlund) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]: Hi, IMHO in case the CIG collides with the acl intervall it will assert on negative time since the end of the offset is the offset for the cis_offset ... so calculating cig_offset ends up negative, so it should be good for dissimilar ACL and CIG intervalls ( they usually are are they not ? You tend to have multiple cig's in an acl intervall  ?
As for reproducability, and internal innivation project managed to end up with 100% reproducability :-D ... which is what I used, but the but shows up in 'real' usecases and in CI testing on real devices from time to time .. ( it's getting more frequent ). But I have tried to reproduce it in a unittest to no avail. So it's not reproducable on main, but it occurs in real devices and testing.

Comment (segerlund) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]: https://github.com/zephyrproject-rtos/zephyr/issues/98072

Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]:
```suggestion

			/* Correct the cis_offset to next CIG event, if the ACL and CIG overlaps.
			 * ACL radio event at the instant was skipped and a relative CIS offset at
			 * the current ACL event has been calculated. But the current ACL event
			 * is partially overlapping with the other of CISes (not yet established) in
			 * the CIG event. Hence, lets establish the CIS at the next ISO interval so
			 * as to have a positive CIG event offset.
			 */
			if (cis_offset < (cig->sync_delay - cis->sync_delay)) {
				cis_offset += iso_interval_us;
				lost_cig_events++;
			}
```

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c [hunk 2]
```diff
@@ -979,6 +979,17 @@ void ull_conn_iso_start(struct ll_conn *conn, uint16_t cis_handle,
 				lost_cig_events = 1U;
 				cis_offset = cis->offset + iso_interval_us - acl_latency_us;
 			}
+			/* Correct the cis_offset to next CIG event, if the ACL and CIG overlaps.
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c:982]:
```suggestion

			/* Correct the cis_offset to next CIG event, if the ACL and CIG overlaps.
```

Have a blank line.

**Review by cvinayak — COMMENTED** [review]
LGTM. nitpick... a blank line and of use 'B', 'C' and `CIG` as used in BT Spec in commit title "Bluetooth: Controller: Handle overlapping CIG and ACL.

**Review by cvinayak — APPROVED** [review]

**Review by cvinayak — CHANGES_REQUESTED** [review]
hmm.... please squash commits and fix commit title.

**Comment by cvinayak** [comment]
hmmm.... `Bluetooth: Controller: Handle overlapping CIG and ACL`

**Review by aescolar — DISMISSED** [review]

**Comment by aescolar** [comment]
Approving assuming the commit title will be updated as requested. (note a commit msg update does not void reviews)

**Comment by segerlund** [comment]
IMHO is all good now ? I am going for vacation in an hour or so, but afaik all should be fixed ...
If it's good, feel free to merge.

**Comment by aescolar** [comment]
@segerlund I think @cvinayak wants you to change the commit title to
`Bluetooth: Controller: Handle overlapping CIG and ACL`

**Comment by aescolar** [comment]
@segerlund please drop the merge commit

**Review by aescolar — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
