### PR TITLE
Bluetooth: Controller: Fix slot_plus_us by converting max CTE len to us

### LINKED ISSUE #53786: BLE:DF: slot_plus_us is not set properly
**Describe the bug**
I was reviewing the source code and I noticed to update the sync slot, an improper number is used.
As you can find here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/controller/ll_sw/ull_df.c#L494
```
...
slot_plus_us = BT_HCI_LE_CTE_LEN_MAX;
...
err = ull_sync_slot_update(sync, slot_plus_us, slot_minus_us);
...
```
And it's expected that ``slot_plus_us``be in microseconds unit, according to this line which converts us to ticks:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/controller/ll_sw/ull_sync.c#L1212
```
int ull_sync_slot_update(...)
{
	...
	ret = ticker_update(...,
			    HAL_TICKER_US_TO_TICKS(slot_plus_us),
			    HAL_TICKER_US_TO_TICKS(slot_minus_us),
			    ...);
```

while the variable is not in microseconds:
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/bluetooth/hci.h#L1602
```
/* Min and max Constant Tone Extension length in 8us units */
#define BT_HCI_LE_CTE_LEN_MIN                  0x2
#define BT_HCI_LE_CTE_LEN_MAX                  0x14
```

It should be multiplied to 8 to be converted to the microseconds unit.

**To Reproduce**
Check the source code

**Expected behavior**
N/A

**Impact**
Unknown

**Logs and console output**
N/A

**Environment (please complete the following information):**
N/A

### PR DESCRIPTION
**Pull request by saleh-unikie**
Fixes #53786

Signed-off-by: Saleh Mehdikhani <saleh.mehdikhani@unikie.com>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_df.c [hunk 1]
```diff
@@ -490,8 +490,9 @@ uint8_t ll_df_set_cl_iq_sampling_enable(uint16_t handle,
 			/* Extend sync event by maximum CTE duration.
 			 * CTE duration depends on transmitter configuration
 			 * so it is unknown for receiver upfront.
+			 * BT_HCI_LE_CTE_LEN_MAX is in 8us units.
 			 */
-			slot_plus_us = BT_HCI_LE_CTE_LEN_MAX;
+			slot_plus_us = BT_HCI_LE_CTE_LEN_MAX * 8;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_df.c:495]:
```suggestion
			slot_plus_us = BT_HCI_LE_CTE_LEN_MAX * 8U;
```

**Review by cvinayak — CHANGES_REQUESTED** [review]
Minor nitpick and please fix the commit title:

>  1: UC3 Commit title does not follow [subsystem]: [subject] (and should not start with literal subsys:): "BLE:DF: Fix slot_plus_us by converting max CTE len to us"

Use "Bluetooth: Controller: Fix slot_plus_us by converting max CTE len to us" 

Keep the length of the title upto 72 chars

**Review by cvinayak — CHANGES_REQUESTED** [review]
Code LGTM. But forgot to tell that please include a commit message stating the text you reference in the github issue. i.e. why this change and how the implementation was changed.

The "Fixes ..." is only needed in the github description, for github.

@ppryga-nordic Minor review for you.

**Review by cvinayak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
