### PR TITLE
lib: posix: clock: Use k_uptime_get() to compute tv_nsec

### LINKED ISSUE #8009: POSIX `clock_gettime()` is discontinuous
The implementation of `clock_gettime()` when called with `CLOCK_MONOTONIC` is non-monotonic (it jumps backward) about once a second after the first time that the k_cycle_get_32() counter wraps. On the FRDM-K64F, this means the result is incorrect after about 35 seconds, and is never correct from then on.

The problem is that the `k_cycle_get_32()` is used mod `sys_clock_hw_cycles_per_sec`. Unless the hw cycles per sec is a power of two, the overflow will not occur on a second boundary. This effectively means that this sub-second value is completely meaningless after the counter wraps the first time.

I can suggest two solutions, a short-term and a better fix:

1. Use the lower precision 'ms' value from `k_uptime_get() to set the nanosecond field. The value will be less "accurate", but a less accurate number is still more useful than a completely meaningless value that is currently used.
2. Longer term, keep a proper 64-bit counter by watching the k_cycle_get_32 counter, noticing overflows, and using them to increment an upper-32-bit counter. It might be best to just have a `k_cycle_get_64()` counter, and use that for the monotonic time.

### PR DESCRIPTION
**Pull request by ramakrishnapallala**
Use k_uptime_get() to compute both tv_sec and tv_nsec members
of timespec structure.

Fixes #8009

Signed-off-by: Ramakrishna Pallala <ramakrishna.pallala@intel.com>

### CODE REVIEW

File: lib/posix/clock.c [hunk 1]
```diff
@@ -15,21 +15,18 @@
...
 	elapsed_msecs = k_uptime_get();
-	elapsed_secs = elapsed_msecs / MSEC_PER_SEC;
-
-	elapsed_cycles = (s64_t) (k_cycle_get_32() %
-				  sys_clock_hw_cycles_per_sec);
-	elapsed_nsec = (s64_t) ((elapsed_cycles * NSEC_PER_SEC) /
-				sys_clock_hw_cycles_per_sec);
+	elapsed_secs = (s64_t) (elapsed_msecs / MSEC_PER_SEC);
+	elapsed_nsec = (s64_t) ((elapsed_msecs % MSEC_PER_SEC) *
+					USEC_PER_MSEC * NSEC_PER_USEC);
```
Comment (andyross) [inline lib/posix/clock.c]: Seems like it's still to complicated.  If you're going to do this in 64 bit math, don't bother finessing the components, you don't need to:

    u64_t ms = k_uptime_get();
    ts->tv_sec = (s32_t)(ms / 1000);
    ts->tv_nsec = (s32_t)((ms % 1000)*1000);

Also, IMHO it's perfectly fine to assume that the SI standard for unit naming is going to adhere in perpetuity and that humanity will never change the meaning of "micro" or "nano" such that the code needs to adapts.  Those x_PER_y constants seem sorta silly to me.

**Review by andyross — APPROVED** [review]
Style nitpickery

File: lib/posix/clock.c (hunk 1 above)
Comment (ramakrishnapallala) [reply lib/posix/clock.c]: will get rid of the local variables and those constants are from Zephyr include headers so will stick with them.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by nashif — APPROVED** [review]
