### PR TITLE
drivers: serial: cdns: fix interrupt driven uart

### LINKED ISSUE #81048: driver: serial: cdns: race condition with interrupt driver uart
The interrupt driven uart relies on a timeout condition for when to trigger the interrupt. This can causes issues for when the interrupt is disabled by `uart_cdns_disable_tx_irq` before it gets a chance to be kicked off by `uart_cdns_enable_tx_irq` Where  a full message may not come out.

### PR DESCRIPTION
**Pull request by XenuIsWatching**
The tx fifo empty interrupt is a edge driven interrupt, so if it is already empty then and the interrupt is enabled, it will not fire so the isr needs to be triggered manually for the callback.

This also removes the unnecessary interrupt locking in the isr and removes the receiver timeout interrupt which lead to a lot of race conditions.

### CODE REVIEW

File: drivers/serial/uart_cdns.c [hunk 1]
```diff
@@ -105,21 +105,24 @@ static int uart_cdns_read_fifo(const struct device *dev, uint8_t *rx_data, const
...
-	 * we have the timer involved here
+	 * TX FIFO. We need another way generate the first interrupt. If the TX FIFO
+	 * is already empty, we need to trigger the callback manually.
 	 */
-	uart_regs->rx_timeout = DEFAULT_RTO_PERIODS_FACTOR;
-	uart_regs->intr_enable = CSR_TEMPTY_MASK | CSR_TOUT_MASK;
+	uart_regs->intr_enable = CSR_TEMPTY_MASK;
+	key = irq_lock();
+	uart_cdns_irq_handler(dev);
+	irq_unlock(key);
```
Comment (dcpleung) [inline drivers/serial/uart_cdns.c:117]: Don't you need to check if the FIFO is empty before doing callback? Because the IRQ handler does not check for whether there are any pending interrupts, and simply do the callback.

**Review by dcpleung — COMMENTED** [review]
If it is setup to do level triggering, the interrupt line should be raised until it is handled or interrupt disabled. That's why TX needs to be disabled when nothing more needs to be sent.

File: drivers/serial/uart_cdns.c (hunk 1 above)
Comment (XenuIsWatching) [reply drivers/serial/uart_cdns.c:117]: I wasn't sure if that was necessary because for something like the `shell_uart.c`, it should be assumed that it put data in to the ring buffer calling the `uart_irq_tx_enable` and the callback should put more data in to the FIFO of the uart reading out of the ring buffer. If the FIFO wasn't full, when it called the `tx_enable`, then the same thing would happen anyway when it eventually gets empty.

I do see other Uarts have similar approaches...
https://github.com/zephyrproject-rtos/zephyr/blob/193eeaef0c04570b80a954b58ccd98075150fb11/drivers/serial/uart_apbuart.c#L378

**Review by dcpleung — DISMISSED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@XenuIsWatching , moving this to 4.1 release. If this is critical for 4.0, then please add a` backport-v4.0` label
