### PR TITLE
cmsis_rots_v1: fix for clearing signal flags in osSignalWait.

### LINKED ISSUE #37182: cmsis_v1 osSignalWait doesn't clear the signals properly when any signal mask is set
**Describe the bug**
cmsis_v1 osSignalWait doesn't clear the signals properly when any signal mask is set; so at the next call, the previous bits are still set even if not raised again.

**To Reproduce**
call osSignalSet(thread, 0x1)
call osSignalWait(thread, 0x0) -- special 0x0 flag to wait for any signal
check that evt.value.signals is really 0x1
call osSignalWait(thread, 0x0)
evt.value.signals is still 0x1 !

**Expected behavior**
call osSignalSet(thread, 0x1)
call osSignalWait(thread, 0x0) -- special 0x0 flag to wait for any signal
check that evt.value.signals is really 0x1
call osSignalWait(thread, 0x0)
check that evt.value.signals is really 0x0

**Impact**
Bug making the signaling of any not usable.

**Logs and console output**
NA

**Environment (please complete the following information):**
Any

**Additional context**
My patch here 
[0001-Fix-an-y-signal-mask-bug.patch.gz](https://github.com/zephyrproject-rtos/zephyr/files/6872080/0001-Fix-an-y-signal-mask-bug.patch.gz)

### PR DESCRIPTION
**Pull request by chen-png**
we use flag 0 in osSignalWait function to wait for
any single signal flag, but with this 0 flag,
it won't clear thread signal results as expected in "thread_def->signal_results &= signals".
we need to check whether signal flag is 0 firstly.

fix: #37182 

Signed-off-by: Chen Peng1 <peng1.chen@intel.com>

### CODE REVIEW

File: subsys/portability/cmsis_rtos_v1/cmsis_signal.c [hunk 1]
```diff
@@ -157,7 +157,7 @@ osEvent osSignalWait(int32_t signals, uint32_t millisec)
 
 	/* Clear signal flags as the thread is ready now */
 	key = irq_lock();
-	thread_def->signal_results &= ~(signals);
+	thread_def->signal_results &= signals ? ~(signals) : 0;
```
Comment (LeiW000) [inline subsys/portability/cmsis_rtos_v1/cmsis_signal.c:160]: Is it better to define a macro for "0"?

**Review by LeiW000 — CHANGES_REQUESTED** [review]

**Comment by chen-png** [comment]
hi @dcpleung, could you help review this? thanks.

**Review by LeiW000 — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
