### PR TITLE
libc: minimal: qsort remove callback cast in call of qsort_r

### LINKED ISSUE #42870: Build error due to minimal libc qsort callback cast
**Describe the bug**
Some toolchains experience problems when casting a function pointer to another function pointer with different number of parameters. This is especially a problem when the cast is from a function pointer with fewer parameters than the function pointer being cast to. As is the case in the minimal libc stdlib.h function qsort.

Following error comes from arm-none-eabi-gcc version 10.3.1 20210824
> stdlib.h:71:29: error: cast between incompatible function types from 'int (*)(const void *, const void )' to 'int ()(const void *, const void *, void *)'

The error above will probably be very similar to what a proprietary toolchain could output.

A fix is proposed in [PR42384](https://github.com/zephyrproject-rtos/zephyr/pull/42384)

**To Reproduce**
The above error was from a zephyr decoupled build of the minimal libc, with the gnu arm compiler. This is only to show that gcc also does not like the cast.

**Expected behavior**
No error during build, even with proprietary toolchains, and thus no casts of this type should be present in the minimal libc.

**Impact**
This could potentially be a showstopper for those not using the zephyr sdk, and thus probably proprietary toolchains.

**Logs and console output**
None

**Environment (please complete the following information):**
 - Linux
 - Toolchain proprietary, but shown with gnu arm gcc version 10.3.1 20210824

**Additional context**
None

### PR DESCRIPTION
**Pull request by daor-oti**
This removes the cast of the two parameter compare function used by qsort, to
the three parameter callback function used by qsort_r, in order to
ensure compatibility with other toolchains, even those off-tree.

Fixes #42870

### CODE REVIEW

**Comment by daor-oti** [comment]
I believe that the failure in the check of the coding guide lines are a false positive. This is a c library, and as such it should be allowed to use reserved names, otherwise it will have a hard time fulfilling its purpose. Or am I wrong?

File: lib/libc/minimal/source/stdlib/qsort.c [hunk 1]
```diff
@@ -80,7 +80,28 @@ static void heap_sort(void *base, int nmemb, size_t size, comp3_t comp, void *co
 	}
 }
 
-void qsort_r(void *base, size_t nmemb, size_t size, comp3_t comp, void *arg)
+static compar_fn_t qsort_compar_fn;
```
Comment (cfriedt) [inline lib/libc/minimal/source/stdlib/qsort.c:83]: nak. this is dangerous.

File: lib/libc/minimal/include/stdlib.h [hunk 2]
```diff
@@ -30,8 +30,12 @@ void *bsearch(const void *key, const void *array,
 	      size_t count, size_t size,
 	      int (*cmp)(const void *key, const void *element));
 
-void qsort_r(void *base, size_t nmemb, size_t size,
-	     int (*compar)(const void *, const void *, void *), void *arg);
+typedef int (*compar_fn_t)(const void *, const void *);
```
Comment (cfriedt) [inline lib/libc/minimal/include/stdlib.h:33]: Generally, we do not want to add new typedefs into headers.

**Comment by cfriedt** [comment]
>  This removes the cast of the two parameter compare function used by qsort, to the three parameter callback function used by qsort_r, in order to ensure compatibility with other toolchains, even those off-tree.

@daor-oti - can you be specific about which toolchain has an incompatible comparison function?

File: lib/libc/minimal/source/stdlib/qsort.c (hunk 1 above)
Comment (daor-oti) [reply lib/libc/minimal/source/stdlib/qsort.c:83]: How so, please explain.

File: lib/libc/minimal/include/stdlib.h (hunk 2 above)
Comment (daor-oti) [reply lib/libc/minimal/include/stdlib.h:33]: And why is that? It makes type checking easy, and the match between prototypes and usages can be checked at compile time.

**Comment by daor-oti** [comment]
@cfriedt It is a proprietary toolchain, but why would a cast from a two parameter function pointer to a three parameter function pointer ever be acceptable, as it is not portable and should result in a compilation error?

File: lib/libc/minimal/include/stdlib.h (hunk 2 above)
Comment (cfriedt) [reply lib/libc/minimal/include/stdlib.h:33]: To avoid collisions in the global namespace especially in the case of standard library headers

File: lib/libc/minimal/source/stdlib/qsort.c (hunk 1 above)
Comment (cfriedt) [reply lib/libc/minimal/source/stdlib/qsort.c:83]: Saving the function pointer is not state that needs to be persisted. I suggest not saving a pointer to the comparison function

**Comment by cfriedt** [comment]
> @cfriedt It is a proprietary toolchain, but why would a cast from a two parameter function pointer to a three parameter function pointer ever be acceptable, as it is not portable and should result in a compilation error?

@daor-oti - the reason that it was acceptable in this case was because it is the same strategy used for every platform that is supported by glibc, so it's portable enough.

As it stands none of the supported compilers are generating errors.

File: lib/libc/minimal/source/stdlib/qsort.c (hunk 1 above)
Comment (daor-oti) [reply lib/libc/minimal/source/stdlib/qsort.c:83]: In that case, I see no other way than to add an extra parameter to heap_sort, heapify and shift_down. The shift_down function can the check that parameter, and thereby determine which type of callback to call, with the correct number of parameters. How does that sound?

shift_down could then call, instead directly calling the compare function callback, a function similar to this:
> static int compare_cb(void *cmp_fn, bool cmp_fn_has_3, void *a, void *b, void *arg)
> {
>         int cmp;
>         if (cmp_fn_has_3) {
>                 cmp = ((compar_d_fn_t) cmp_fn)(a, b, arg);
>         } else {
>                 cmp = ((compar_fn_t) cmp_fn)(a, b);
>         }
>         return cmp;
> }
> 
Sorry for the poor formatting, I cannot get GitHub to format as multiline code, hope it is readable. 
Would that be a better option?

File: lib/libc/minimal/include/stdlib.h (hunk 2 above)
Comment (daor-oti) [reply lib/libc/minimal/include/stdlib.h:33]: I see that, but as you state, this is a standard library, and standard libraries do provide typedefs in their header files. Those two typedefs are actually the same as from glibc stdlib.h, except for removal of __.
What is needed in order to keep these typedefs? Will that be adding the _'s?
Or shall the typedefs be removed completely?

**Comment by daor-oti** [comment]
@cfriedt Thank you for your review and comments. I can see that none of the Zephyr SDK provided compilers complain, but we do allow for off-tree and non Zephyr SDK compilers and toolchains to be used, and in order to ensure as broad a compatibility as possible, this would have to be resolved. Also, of cause, we have a need for this to be resolved.

**Comment by cfriedt** [comment]
@daor-oti - are you able to copy & paste the error message you're receiving? Maybe in a new issue? Ideally it would include the compiler you are using, etc.

https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

This change is non-trivial and it would be good to capture the actual problem in a GitHub issue.  I guess you could maybe file it as a bug.

**Comment by daor-oti** [comment]
@cfriedt Thanks for the code formatting guide. 
As it is a proprietary compiler and toolchain, I am unable to provide any useful information from that. The error it spits out is though, something along the lines of, unable to cast from two parameter function pointer to three parameter function pointer.
I can actually get a similar error from arm-none-eabi-gcc version 10.3.1 20210824, which reads 
> stdlib.h:71:29: error: cast between incompatible function types from 'int (*)(const void *, const void *)' to 'int (*)(const void *, const void *, void *)'
I will create a GitHub issue for this. I will also update this PR with the changes I suggested above, perhaps that will be acceptable, if it passes the build checks, that is.

**Comment by cfriedt** [comment]
> I will create a GitHub issue for this. I will also update this PR with the changes I suggested above, perhaps that will be acceptable, if it passes the build checks, that is.

@daor-oti - please do. Once that is done, please also do a `git commit --amend` and adjust your commit message to include the line `Fixes #<Issue Number>` so that this PR is automatically linked to the issue.

**Comment by daor-oti** [comment]
@cfriedt What can we do to move this forward? What do you think of the current suggestion?

File: lib/libc/minimal/include/stdlib.h (hunk 2 above)
Comment (cfriedt) [reply lib/libc/minimal/include/stdlib.h:33]: I'm ok with this changes to stdlib.h as long as the typedefs can be removed.

File: lib/libc/minimal/source/stdlib/qsort.c [hunk 3]
```diff
@@ -59,28 +73,34 @@ static void sift_down(void *base, int start, int end, size_t size, comp3_t comp,
...
-	heapify(base, nmemb, size, comp, comp_arg);
+	heapify(base, nmemb, size, comp, comp_arg, comp_fn_has_3);
 
 	for (end = nmemb - 1; end > 0; --end) {
 		byteswp(A(end), A(0), size);
-		sift_down(base, 0, end, size, comp, comp_arg);
+		sift_down(base, 0, end, size, comp, comp_arg, comp_fn_has_3);
 	}
 }
+void qsort_r(void *base, size_t nmemb, size_t size, compar_d_fn_t compar, void *arg)
```
Comment (cfriedt) [inline lib/libc/minimal/source/stdlib/qsort.c:98]: I'm ok with removing the static inline version of qsort from the minimal libc `stdlib.h`. No need to add any typedefs anywhere really, even in `qsort.c`.

The qsort implementation can be simplified by instantiating a `struct qsort_comp` in the bodies of `qsort()` and `qsort_r()`. With this, the `comp_arg` parameter can be removed from `heap_sort()` and `sift_down()`.

```
struct qsort_comp {
	bool has3;
	void *arg;
	union {
		int (*comp2)(const void *, const void *);
		int (*comp3)(const void *, const void *, void *);
	};
};

static inline int comp(struct qsort_comp *cmp, const void *a, const void *b)
{
	if (cmp->has3) {
		return cmp->comp3(a, b, cmp->arg);
	}

	return cmp->comp2(a, b);
}
```

File: lib/libc/minimal/include/stdlib.h (hunk 2 above)
Comment (daor-oti) [reply lib/libc/minimal/include/stdlib.h]: I have removed the typedefs.

File: lib/libc/minimal/source/stdlib/qsort.c (hunk 3 above)
Comment (daor-oti) [reply lib/libc/minimal/source/stdlib/qsort.c]: @cfriedt Thanks for the suggestion, and I have now reworked the PR as per your suggestion. I hope it is acceptable now, but let me know what you think.

**Comment by daor-oti** [comment]
@cfriedt I beleive that I have updated this PR as per your requests, any chance that you could find the time to look at, and let me know what you think?

**Review by cfriedt — DISMISSED** [review]
LGTM. Thanks for your work. I'll bring up the false positive in the release meeting today.

File: lib/libc/minimal/source/stdlib/qsort.c [hunk 4]
```diff
@@ -59,28 +76,47 @@ static void sift_down(void *base, int start, int end, size_t size, comp3_t comp,
...
 }
 
-void qsort_r(void *base, size_t nmemb, size_t size, comp3_t comp, void *arg)
+void qsort_r(void *base, size_t nmemb, size_t size,
+	     int (*comp3)(const void *a, const void *b, void *arg), void *arg)
+{
+	struct qsort_comp cmp = {
+		.has3 = true,
+		.arg = arg,
+		.comp3 = comp3
```
Comment (stephanosio) [inline lib/libc/minimal/source/stdlib/qsort.c:106]: Older versions of GCC (<= 4.5), even when compiling with -std=gnu99,
do not allow specifying members of an anonymous union without braces
in an initialiser.

```suggestion
		{
			.comp3 = comp3
		}
```

File: lib/libc/minimal/source/stdlib/qsort.c [hunk 5]
```diff
@@ -59,28 +76,47 @@ static void sift_down(void *base, int start, int end, size_t size, comp3_t comp,
...
+}
+
+void qsort(void *base, size_t nmemb, size_t size,
+	   int (*comp2)(const void *a, const void *b))
 {
-	heap_sort(base, nmemb, size, comp, arg);
+	struct qsort_comp cmp = {
+		.has3 = false,
+		.arg = NULL,
+		.comp2 = comp2
```
Comment (stephanosio) [inline lib/libc/minimal/source/stdlib/qsort.c:118]: ditto

```suggestion
		{
			.comp2 = comp2
		}
```

**Review by stephanosio — CHANGES_REQUESTED** [review]
Looks ok overall.

Just need to fix the anonymous union initialisation for portability.

**Comment by cfriedt** [comment]
Although I wouldn't necessarily consider it a bug, per-se, it might be good to backport the change for stability.

File: lib/libc/minimal/source/stdlib/qsort.c (hunk 4 above)
Comment (daor-oti) [reply lib/libc/minimal/source/stdlib/qsort.c:106]: Yes of cause, good point, will fix that.

File: lib/libc/minimal/source/stdlib/qsort.c (hunk 5 above)
Comment (daor-oti) [reply lib/libc/minimal/source/stdlib/qsort.c:118]: Will fix.

**Comment by daor-oti** [comment]
@cfriedt and @stephanosio PR updated, let me know what you think and thank you for your reviews.

**Review by stephanosio — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
