### PR TITLE
drivers:spi_nand: ignore ECC errors on the parameter page

### LINKED ISSUE #104760: drivers: spi_nand: reading ONFI table may fail due to ECC
### Describe the bug

Initialization of the drive may fail due to reading ONFI table resulting uncorrectable ECC error condition. This must never happen as parameter table is not ECC protected.

Tagging @kartben as the original driver contributor.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Using spi_nand with the following DT node

```
	spi_nand: mt29f8g01adbfd@0 {
		compatible = "jedec,spi-nand";
		zephyr,deferred-init;
		status = "okay";
		reg = <0>;
		spi-max-frequency = <8000000>;
		/* 35=4Gb 47=8Gb */
		jedec-id = [ 2c 47 ];
		write-block-size = <4096>;
		erase-block-size = <262144>;
		/* ecc-bits = <8>; */
		size-bytes = <1073741824>;
		block-erase-duration-max = <10000>;
		page-program-duration-max = <600>;
		page-read-duration-max = <200>;
		reset-duration-max = <500>;
	};
```

### Relevant log output

```shell
[00:00:00.056,083] <dbg> spi_nand: spi_nand_wait_until_ready: Ready after 128 us (Op reset, Status 20)
[00:00:00.056,905] <dbg> spi_nand: spi_nand_wait_until_ready: Ready after 128 us (Op read, Status 20)
[00:00:00.056,911] <wrn> spi_nand: ECC uncorrectable error on page 000001
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

Driver ported from Zephyr-main into sdk-nrf from Nordic.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by embed**
The parameter page is not ECC protected, but can return ECC errors under some rare conditions. These errors should be ignored so drivers can initialize.

### CODE REVIEW

File: drivers/flash/spi_nand.c [hunk 1]
```diff
@@ -621,7 +621,7 @@ static int onfi_parameters_load(const struct device *dev)
 
 	/* Load parameter info into cache */
```
Comment (tpambor) [inline drivers/flash/spi_nand.c]:
```suggestion
	/* Load parameter info into cache (ignoring ECC errors) */
```

**Review by tpambor — COMMENTED** [review]
Please use `flash: spi_nand: ...` in the title and also add a sign-off line to the commit message. https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines

**Review by tpambor — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
