### PR TITLE
drivers: adc: lmp90xxx: fix coverity issues

### LINKED ISSUE #35603: [Coverity CID: 236130] Wrong sizeof argument in drivers/adc/adc_lmp90xxx.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/374629af906a24add294b1c3b945128cb6a486e8/drivers/adc/adc_lmp90xxx.c#L250

Category: Incorrect expression
Function: `lmp90xxx_read_reg8`
Component: Drivers
CID: [236130](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=236130)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/374629af906a24add294b1c3b945128cb6a486e8/drivers/adc/adc_lmp90xxx.c#L250

```
244         return err;
245     }
246    
247     static int lmp90xxx_read_reg8(const struct device *dev, uint8_t addr,
248                       uint8_t *val)
249     {
>>>     CID 236130:  Incorrect expression  (SIZEOF_MISMATCH)
>>>     Passing argument "val" of type "uint8_t *" and argument "4U /* sizeof (val) */" to function "lmp90xxx_read_reg" is suspicious.
250         return lmp90xxx_read_reg(dev, addr, val, sizeof(val));
251     }
252    
253     static int lmp90xxx_write_reg(const struct device *dev, uint8_t addr,
254                       uint8_t *dptr,
255                       size_t len)
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #35604: [Coverity CID: 236129] Unused value in drivers/adc/adc_lmp90xxx.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/374629af906a24add294b1c3b945128cb6a486e8/drivers/adc/adc_lmp90xxx.c#L616

Category: Code maintainability issues
Function: `lmp90xxx_adc_read_channel`
Component: Drivers
CID: [236129](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=236129)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/374629af906a24add294b1c3b945128cb6a486e8/drivers/adc/adc_lmp90xxx.c#L616

```
610             delay = lmp90xxx_odr_delay_tbl[odr];
611             LOG_DBG("sleeping for %d ms", delay);
612             k_msleep(delay);
613    
614             /* Poll for data ready */
615             do {
>>>     CID 236129:  Code maintainability issues  (UNUSED_VALUE)
>>>     Assigning value from "lmp90xxx_read_reg8(dev, 24, &adc_done)" to "err" here, but that stored value is overwritten before it can be used.
616                 err = lmp90xxx_read_reg8(dev, LMP90XXX_REG_ADC_DONE,
617                             &adc_done);
618                 if (adc_done == 0xFFU) {
619                     LOG_DBG("sleeping for 1 ms");
620                     k_msleep(1);
621                 } else {
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by gmarull**
Fixes #35603
Fixes #35604

### CODE REVIEW

File: drivers/adc/adc_lmp90xxx.c [hunk 1]
```diff
@@ -247,7 +247,7 @@ static int lmp90xxx_read_reg(const struct device *dev, uint8_t addr,
 static int lmp90xxx_read_reg8(const struct device *dev, uint8_t addr,
 			      uint8_t *val)
 {
-	return lmp90xxx_read_reg(dev, addr, val, sizeof(val));
```
Comment (nashif) [inline drivers/adc/adc_lmp90xxx.c:250]: in commit msg you have buzzer?

Comment (gmarull) [reply drivers/adc/adc_lmp90xxx.c:250]: oops, fixed

**Review by nashif — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
Thanks.

**Review by anangl — APPROVED** [review]
