### PR TITLE
pinctrl: esp32/s2/c3: initial support

### LINKED ISSUE #43715: ESP32 UART devicetree binding design issue
**Describe the bug**

Creating a bug from the discussion here:

https://github.com/zephyrproject-rtos/zephyr/pull/41941#discussion_r789262385

The espresssif,esp32-uart devicetree binding has a required `peripheral` property which specifies an index into the available UARTs.

This is a binding design problem because the index number is not hardware description: according to @sylvioalves , the value is not used to describe or configure hardware, and is present in the binding as a work-around for interfacing with the HAL-based zephyr UART shim driver for this peripheral. Such properties go against devicetree design principles.

**Expected behavior**

- The property should be removed from the binding
- Another hardware-appropriate workaround should be implemented in the shim driver

**Impact**

Annoyance

### PR DESCRIPTION
**Pull request by glaubermaroto**
This PR brings `pinctrl` support to Espressif SoCs and their related boards.

It also removes `pinmux` support off Espressif SoCs.

This work links to #39740.

Closes #43715

### CODE REVIEW

File: drivers/pinctrl/pinctrl_esp32.c [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+
+	if (ESP32_PORT_IDX(pin_num) >= gpio_ports_cnt) {
+		return -EINVAL;
+	}
+
+	port_device = gpio_ports[ESP32_PORT_IDX(pin_num)];
+
+	if ((port_device == NULL) || (!device_is_ready(port_device))) {
+		return -ENODEV;
+	}
```
Comment (gmarull) [inline drivers/pinctrl/pinctrl_esp32.c:41]: please don't mix GPIO/pinctrl. pinctrl drivers need to be independent, and, if there's ever a relation it'll likely be GPIO depending on pinctrl (since in most cases it's a subset). Same discussion happened for the Microchip case, see https://github.com/zephyrproject-rtos/zephyr/pull/43282

File: boards/xtensa/esp32/esp32_defconfig [hunk 2]
```diff
@@ -18,6 +18,8 @@ CONFIG_XTENSA_USE_CORE_CRT1=n
 CONFIG_PINMUX=y
 CONFIG_PINMUX_ESP32=y
 
+CONFIG_PINCTRL=y
```
Comment (gmarull) [inline boards/xtensa/esp32/esp32_defconfig:18]: suggestion: default PINCTRL to y at SoC level if it's always required.

File: drivers/pinctrl/Kconfig.esp32 [hunk 3]
```diff
@@ -0,0 +1,9 @@
+# Copyright (c) 2022 Espressif Systems (Shanghai) Co., Ltd.
+# SPDX-License-Identifier: Apache-2.0
+
+config PINCTRL_ESP32
+	bool "Pin controller driver for ESP32 SoC"
+	depends on SOC_ESP32
+	default y
```
Comment (gmarull) [inline drivers/pinctrl/Kconfig.esp32:7]: please default based on `dt_compat_status`

File: dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml [hunk 4]
```diff
@@ -0,0 +1,56 @@
+# Copyright (c) 2022 Espressif Systems (Shanghai) Co., Ltd.
+# SPDX-License-Identifier: Apache-2.0
+
+description: |
+    ESP32 Pin controller Node
+    Based on pincfg-node.yaml binding.
+
+    Note: `bias-disable` and `drive-push-pull` are default pin configurations.
+           They will be applied in case no `bias-foo` or `driver-bar` properties
+           are set.
```
Comment (gmarull) [inline dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml:10]: please extend description on usage (see other vendors as a reference, e.g. GD32, nRF, Microchip, etc.)

File: drivers/i2c/i2c_esp32.c [hunk 5]
```diff
@@ -676,6 +678,9 @@ static int IRAM_ATTR i2c_esp32_init(const struct device *dev)
 	I2C_ESP32_FREQUENCY(DT_INST_PROP(idx, clock_frequency))
 
 #define ESP32_I2C_INIT(idx)		\
+					\
+PINCTRL_DT_INST_DEFINE(idx);		\
```
Comment (gmarull) [inline drivers/i2c/i2c_esp32.c:711]: nit: please align with other macro content

File: drivers/i2c/i2c_esp32.c [hunk 6]
```diff
@@ -41,6 +43,14 @@ LOG_MODULE_REGISTER(i2c_esp32, CONFIG_I2C_LOG_LEVEL);
 #define I2C_CLK_LIMIT_RTC (20 * 1000 * 1000 / 20)	/* Limited by RTC, no more than RTC/20 */
 #define I2C_CLK_LIMIT_XTAL (40 * 1000 * 1000 / 20)	/* Limited by RTC, no more than XTAL/20 */
 
+#define I2C_GET_PIN_INFO(state, idx)								\
+{												\
+	.gpio_name = gpio_esp32_get_gpio_for_pin(ESP32_PIN_NUM(state->pins[idx].pinmux)),	\
+	.sig_out = ESP32_PIN_SIGO(state->pins[idx].pinmux),					\
+	.sig_in = ESP32_PIN_SIGI(state->pins[idx].pinmux),					\
+	.pin = ESP32_PIN_NUM(state->pins[idx].pinmux)						\
+}
```
Comment (gmarull) [inline drivers/i2c/i2c_esp32.c:52]: it is not allowed to query pin information, API operates on states. all pinctrl structs should be considered private.

**Review by gmarull — CHANGES_REQUESTED** [review]
I've done a quick initial review. Please check my comments.

**Comment by glaubermaroto** [comment]
@carlescufi Would you please add me as one of the assignees at #39740?

Could you also help me with this [failing compliance check](https://github.com/zephyrproject-rtos/zephyr/runs/5479786024?check_suite_focus=true)? My understanding is that using `typedef` to define `pinctrl_soc_pin_t` should be an exception to that rule, right?

**Comment by glaubermaroto** [comment]
@adalava Could you gently check/report any misbehavior when testing this PR on Heltec's LoRa board? Feel free to get in touch.

**Comment by gmarull** [comment]
> Could you also help me with this [failing compliance check](https://github.com/zephyrproject-rtos/zephyr/runs/5479786024?check_suite_focus=true)? My understanding is that using `typedef` to define `pinctrl_soc_pin_t` should be an exception to that rule, right?

This failure is expected, you can ignore it.

File: boards/xtensa/esp32/esp32_defconfig (hunk 2 above)
Comment (glaubermaroto) [reply boards/xtensa/esp32/esp32_defconfig]: Moved to SoC level. Thanks for the suggestion.

File: drivers/pinctrl/Kconfig.esp32 (hunk 3 above)
Comment (glaubermaroto) [reply drivers/pinctrl/Kconfig.esp32]: Done.

File: drivers/i2c/i2c_esp32.c (hunk 6 above)
Comment (glaubermaroto) [reply drivers/i2c/i2c_esp32.c:52]: This query is not part of the regular flow of the pinctrl API. It is included here to overcome an I2C driver constraint:

Most Espressif SoCs are provisioned with HAL mechanisms to overcome an eventual I2C FSM failure, while others need to keep pin numbering info to achieve the same.

File: drivers/pinctrl/pinctrl_esp32.c (hunk 1 above)
Comment (glaubermaroto) [reply drivers/pinctrl/pinctrl_esp32.c:168]: @gmarull thanks for pointing that out. I have decoupled the pinctrl driver from the GPIO driver, removing dependency between them.

Though you will see some gpio-prefixed naming are kept here and there, it is due to hal_espressif's own conventions.

**Comment by adalava** [comment]
> @adalava Could you gently check/report any misbehavior when testing this PR on Heltec's LoRa board? Feel free to get in touch.

@glaubermaroto , I tested basic/button and subsys/display/lvgl samples with your branch, they exercise a lot of pin stuff. It looks good to me!

File: drivers/i2c/i2c_esp32.c (hunk 5 above)
Comment (glaubermaroto) [reply drivers/i2c/i2c_esp32.c:711]: This driver will be addressed again in another PR, the scope of that PR also includes some code refactoring.

If you don't mind, I'd rather address this alignment suggestion in that PR to not cloud pinctrl-related modifications in here, ok?

File: drivers/serial/uart_esp32.c [hunk 7]
```diff
@@ -530,35 +466,14 @@ static const DRAM_ATTR struct uart_driver_api uart_esp32_api = {
...
-
-#define DT_UART_ESP32_GPIO_NAME(idx, pin) ( \
-	DT_INST_PROP(idx, pin) < 32 ? GPIO0_NAME : GPIO1_NAME)
-
 #define ESP32_UART_INIT(idx)						       \
+										\
+PINCTRL_DT_INST_DEFINE(idx);							\
+										\
 static const DRAM_ATTR struct uart_esp32_config uart_esp32_cfg_port_##idx = {	       \
 	.uart_num = DT_INST_PROP(idx, peripheral),	\
```
Comment (sylvioalves) [inline drivers/serial/uart_esp32.c:474]: Remove `uart_num`, it is not necessary anymore.
Also, remove `peripheral` from devicetree binding so #43715 can be closed.

Comment (glaubermaroto) [reply drivers/serial/uart_esp32.c]: @sylvioalves Removal was done here, I'll open another PR to address `hal_espressif`'s side.

**Comment by glaubermaroto** [comment]
Twister is [raising an error](https://github.com/zephyrproject-rtos/zephyr/runs/5527942652?check_suite_focus=true) when running on the odroig_go board, however, this board is not being maintained by Espressif.

I'm not sure how should be the approach to this. Not including the odroid_go board on this PR, in turn, will lead to compilation errors.

@nashif @sylvioalves Could you help me with this one?

File: drivers/pinctrl/Kconfig.esp32 (hunk 3 above)
Comment (gmarull) [reply drivers/pinctrl/Kconfig.esp32]: can't see this fixed in the first commit, can you fixup this one?

File: drivers/pinctrl/pinctrl_esp32.c (hunk 1 above)
Comment (gmarull) [reply drivers/pinctrl/pinctrl_esp32.c:168]: I still see the gpio based implementation on the first commit, can you please squash//fixup?

File: drivers/pinctrl/Kconfig.esp32 (hunk 3 above)
Comment (glaubermaroto) [reply drivers/pinctrl/Kconfig.esp32]: Fixed.

File: drivers/pinctrl/pinctrl_esp32.c (hunk 1 above)
Comment (glaubermaroto) [reply drivers/pinctrl/pinctrl_esp32.c:168]: Squashed/Fixed.

**Comment by glaubermaroto** [comment]
The last push was to solve file conflicts.

**Review by uLipe — DISMISSED** [review]

**Review by sylvioalves — DISMISSED** [review]

File: drivers/pinctrl/pinctrl_esp32.c [hunk 8]
```diff
@@ -0,0 +1,270 @@
...
```
Comment (gmarull) [inline drivers/pinctrl/pinctrl_esp32.c:168]: this driver continues depending on GPIO, please make driver independent of GPIO. See e.g. GD32 driver where GPIO information is used from DT, but no GPIO device is used internally.

**Review by gmarull — CHANGES_REQUESTED** [review]

File: drivers/pinctrl/pinctrl_esp32.c (hunk 8 above)
Comment (glaubermaroto) [reply drivers/pinctrl/pinctrl_esp32.c]: Fixed.

**Review by uLipe — DISMISSED** [review]

**Comment by glaubermaroto** [comment]
> Twister is [raising an error](https://github.com/zephyrproject-rtos/zephyr/runs/5527942652?check_suite_focus=true) when running on the odroid_go board, however, this board is not being maintained by Espressif.
> 
> I'm not sure how should be the approach to this. Not including the odroid_go board on this PR, in turn, will lead to compilation errors.
> 
> @nashif @sylvioalves Could you help me with this one?

File: drivers/i2c/i2c_esp32.c (hunk 6 above)
Comment (gmarull) [reply drivers/i2c/i2c_esp32.c:52]: The problem here is that driver's can't make use of any pinctrl state information since it is opaque. You can't rely on the data structure behind pinctrl_dev_config. If you need GPIO access to i2c pins, you'll need something like:

1. Create a new custom state "gpio" (or whatever name) that configures pins as GPIO instead of muxed to the I2C peripheral
2. Store GPIO phandles in DT, e.g. `i2c-gpios = <&gpiox 0 1>, <&gpioy 2 3>;`. It's true that this duplicates some information also stored by pinctrl, but right now, the pinctrl API doesn't expose any specified pin as a GPIO device. We may explore this in the future based on the initial round of pinctrl ports.
3. When in need for gpio access, just do `pinctrl_apply_state(..., PINCTRL_GPIO_STATE);`. Use GPIO API. When done, apply `PINCTRL_DEFAULT_STATE` back.

File: boards/xtensa/heltec_wifi_lora32_v2/CMakeLists.txt [hunk 9]
```diff
@@ -1,6 +1,6 @@
 # SPDX-License-Identifier: Apache-2.0
 
-if(CONFIG_PINMUX_ESP32)
+if(CONFIG_PINCTRL_ESP32)
```
Comment (gmarull) [inline boards/xtensa/heltec_wifi_lora32_v2/CMakeLists.txt:3]: seems like board is using just GPIO API to configure some pins, how is that related to pinctrl?

File: boards/xtensa/esp_wrover_kit/CMakeLists.txt [hunk 10]
```diff
@@ -1,6 +1,6 @@
 # SPDX-License-Identifier: Apache-2.0
 
-if(CONFIG_PINMUX_ESP32)
+if(CONFIG_PINCTRL_ESP32)
```
Comment (gmarull) [inline boards/xtensa/esp_wrover_kit/CMakeLists.txt:3]: ditto

**Review by gmarull — CHANGES_REQUESTED** [review]
Thanks for the continued work, I have some questions please check.

**Comment by sylvioalves** [comment]
rebased to check odroid_go twister issue.

File: drivers/i2c/i2c_esp32.c (hunk 6 above)
Comment (glaubermaroto) [reply drivers/i2c/i2c_esp32.c]: I have gone through a different approach but got rid of the pin state query.

File: boards/xtensa/heltec_wifi_lora32_v2/CMakeLists.txt (hunk 9 above)
Comment (glaubermaroto) [reply boards/xtensa/heltec_wifi_lora32_v2/CMakeLists.txt]: Good point. I have changed it to evaluate `CONFIG_GPIO_ESP32` instead.

File: boards/xtensa/esp_wrover_kit/CMakeLists.txt (hunk 10 above)
Comment (glaubermaroto) [reply boards/xtensa/esp_wrover_kit/CMakeLists.txt]: Good point. I have changed it to evaluate `CONFIG_GPIO_ESP32` instead.

**Comment by glaubermaroto** [comment]
> > @adalava Could you gently check/report any misbehavior when testing this PR on Heltec's LoRa board? Feel free to get in touch.
> 
> @glaubermaroto , I tested basic/button and subsys/display/lvgl samples with your branch, they exercise a lot of pin stuff. It looks good to me!

@adalava It might be worth re-testing on Heltec's board again, I have made a couple of changes here and there.

**Comment by glaubermaroto** [comment]
@ydamigos Could you try this PR on the `odroid_go` board? Please, let me know how it goes on that board.

**Comment by ydamigos** [comment]
@glaubermaroto I did a quick check and got compilation error about missing "espressif/32/esp32-pinctrl.dtsi" file. I' ll have a better look.

**Comment by glaubermaroto** [comment]
> @glaubermaroto I did a quick check and got compilation error about missing "espressif/32/esp32-pinctrl.dtsi" file. I' ll have a better look.

That's on `hal_espressif`'s side. Before building, you probably need to run these two:

```sh
west update
west espressif update
```

**Comment by ydamigos** [comment]
> That file is on `hal_espressif`'s side. Before building, you probably need to run these two commands:
> 
> ```shell
> west update
> west espressif update
> ```

That did the trick. UART and GPIO output work fine. Tested with hello_world sample and blinky.
GPIO input didn't work using button sample. I will check if this issue is related to this PR or not.

**Comment by adalava** [comment]
> > @adalava It might be worth re-testing on Heltec's board again, I have made a couple of changes here and there.
> 
> @glaubermaroto, the button sample is fine but the display sample is not working anymore after latest changes, the display doesn't turn on. I can make it work manually by simply wiring pin16 (OLED RESET) to 3V3 directly.
> 
> To help you reproduce it, here's where I've set the pin16 to HIGH during board initialization: https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/xtensa/heltec_wifi_lora32_v2/board_init.c#L28. I think you can do something similar on your board and check voltage.
> 
> Build command: `west build -p auto -b heltec_wifi_lora32_v2 samples/subsys/display/lvgl -- -DSHIELD=ssd1306_128x64`

Hi @glaubermaroto, looks like it's just the order of the things. In boards/xtensa/heltec_wifi_lora32_v2/board_init.c  I switched SYS_INIT back to PRE_KERNEL_2 and display sample is back working fine to me :)

**Comment by glaubermaroto** [comment]
> > @glaubermaroto, the button sample is fine but the display sample is not working anymore after latest changes, the display doesn't turn on. I can make it work manually by simply wiring pin16 (OLED RESET) to 3V3 directly.
> 
> Hi @glaubermaroto, looks like it's just the order of the things. In boards/xtensa/heltec_wifi_lora32_v2/board_init.c I switched SYS_INIT back to PRE_KERNEL_2 and display sample is back working fine to me :)

Right, thanks for pointing this out. I'll revert the board's initialization priority before moving on.

**Comment by glaubermaroto** [comment]
For now, I have changed this PR to Draft/DNM in order to address some review points.

**Comment by ydamigos** [comment]
> @ydamigos Something similar might be happening to the odroid_go board. Could you confirm?

@glaubermaroto The issue was related to missing pull up. I thought all the buttons had external pull up but that's not the case. I' ll open a PR to address it.

File: dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml [hunk 11]
```diff
@@ -0,0 +1,116 @@
...
+    Searching through the .dtsi file the following pin state matches
+
+
+      i2c0_sda_gpio33: i2c0_sda_gpio33 {
+          pinmux = <ESP32_PINMUX(33, ESP_I2CEXT0_SDA_IN, ESP_I2CEXT0_SDA_OUT)>;
+          bias-pull-up;
+          drive-open-drain;
+          input-enable;
+          output-high;
+      };
```
[the remark this answers is not in the document]
Comment (glaubermaroto) [reply dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml]: I have changed the approach here, only pin muxing information is pre-defined now. Pin properties are selected on-demand.

File: dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml [hunk 12]
```diff
@@ -0,0 +1,161 @@
...
+    states are defined on another file (i.e, 'esp_wrover_kit-pinctrl.dtsi') on
+    the same folder of the DTS file. Check below the excerpt describing SDA's
+    pin state
+
+
+        i2c0_sda_gpio21: i2c0_sda_gpio21 {
+                pinmux = <I2C0_SDA_GPIO21>;
+                bias-pull-up;
+                drive-open-drain;
+                output-high;
```
Comment (gmarull) [inline dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml:45]: nit: is this still correct (ie i2c pull-up)?

File: include/dt-bindings/pinctrl/esp-pinctrl-common.h [hunk 13]
```diff
@@ -0,0 +1,72 @@
+/*
+ * Copyright (c) 2022 Espressif Systems (Shanghai) Co., Ltd.
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_ESP_PINCTRL_COMMON_H_
+#define ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_ESP_PINCTRL_COMMON_H_
+
+#define ESP32_PIN_NUM_SHIFT      0U
```
Comment (gmarull) [inline include/dt-bindings/pinctrl/esp-pinctrl-common.h:10]: nit: this header makes use of `BIT()`, so it should include `<sys/util_macro.h>`

**Review by gmarull — APPROVED** [review]
LGTM, just have a couple of minor comments

**Comment by gmarull** [comment]
@glaubermaroto not sure if it's the case, but please also check in samples/tests if there's any overlay changing pins for ESP32 boards.

File: dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml (hunk 12 above)
Comment (glaubermaroto) [reply dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml:45]: The difference now is that - differently from the previous version of this PR - using this and other properties is no longer mandatory, but the option was kept in case one's wants to use SoC's internal pull-up at its own discretion.

File: include/dt-bindings/pinctrl/esp-pinctrl-common.h (hunk 13 above)
Comment (glaubermaroto) [reply include/dt-bindings/pinctrl/esp-pinctrl-common.h:10]: In this case, "BIT()" is one of those macros that is also defined on Espressif's HAL.

**Comment by glaubermaroto** [comment]
> @glaubermaroto not sure if it's the case, but please also check in samples/tests if there's any overlay changing pins for ESP32 boards.

I've checked it previously. Anyway, thanks for drawing attention to this.

File: dts/xtensa/espressif/esp32.dtsi [hunk 14]
```diff
@@ -9,6 +9,7 @@
 #include <dt-bindings/i2c/i2c.h>
 #include <dt-bindings/clock/esp32_clock.h>
 #include <dt-bindings/interrupt-controller/esp-xtensa-intmux.h>
+#include <dt-bindings/pinctrl/esp32-pinctrl.h>
```
Comment (ydamigos) [inline dts/xtensa/espressif/esp32.dtsi:12]: I tried to build lvgl sample for odroid_go but this file is missing.

Comment (glaubermaroto) [reply dts/xtensa/espressif/esp32.dtsi:12]: @ydamigos I am facing no issues when building this sample for the odroid_go board. Did you try the following commands before?

```
west update
west espressif update
```

Comment (ydamigos) [reply dts/xtensa/espressif/esp32.dtsi:12]: False alarm. I always forget to run these commands first.

File: include/dt-bindings/pinctrl/esp-pinctrl-common.h (hunk 13 above)
Comment (gmarull) [reply include/dt-bindings/pinctrl/esp-pinctrl-common.h:10]: I mean, header is not self-contained, this is a bad practice.

File: dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml (hunk 12 above)
Comment (gmarull) [reply dts/bindings/pinctrl/espressif,esp32-pinctrl.yaml:45]: in general internall pull-ups are not suitable for I2C (even though in many cases "it just works" for certain configurations).

**Review by gmarull — CHANGES_REQUESTED** [review]
These overlays need to be updated:

samples/bluetooth/hci_uart/boards/esp32.overlay
samples/subsys/fs/fat_fs/boards/esp_wrover_kit.overlay

**Comment by glaubermaroto** [comment]
> These overlays need to be updated:
> 
> samples/bluetooth/hci_uart/boards/esp32.overlay samples/subsys/fs/fat_fs/boards/esp_wrover_kit.overlay

That's true. I have grepped only inside `samples/drivers`

File: dts/xtensa/espressif/esp32.dtsi (hunk 14 above)
Comment (glaubermaroto) [reply dts/xtensa/espressif/esp32.dtsi:12]: Something similar was reported on Heltec's board a while ago. Could you try editing `boards/xtensa/odroid_go/board_init.c` and replace `SYS_INIT`'s second argument by `PRE_KERNEL_2` instead of `APPLICATION`?

Comment (ydamigos) [reply dts/xtensa/espressif/esp32.dtsi:12]: I did the change but it didn't work. I tried also `samples/drivers/display` with the same result.

**Comment by adalava** [comment]
@glaubermaroto I verified samples/subsys/display/lvgl and samples/basic/button/ at 75f568a452f6b3ed91f8fb39fcccb1e3d0371fd4 on board heltec_wifi_lora32_v2, it's everything working as expected!

File: boards/xtensa/odroid_go/odroid_go-pinctrl.dtsi [hunk 15]
```diff
@@ -0,0 +1,53 @@
...
+
+	i2c0_sda_gpio4: i2c0_sda_gpio4 {
+		pinmux = <I2C0_SDA_GPIO4>;
+		bias-pull-up;
+		drive-open-drain;
+		output-high;
+	};
+
+	i2c0_scl_gpio15: i2c0_scl_gpio15 {
+		pinmux = <I2C0_SCL_GPIO22>;
```
Comment (ydamigos) [inline boards/xtensa/odroid_go/odroid_go-pinctrl.dtsi:47]: I2C0_SCL_GPIO15

Comment (glaubermaroto) [reply boards/xtensa/odroid_go/odroid_go-pinctrl.dtsi]: Fixed, thanks.

File: dts/xtensa/espressif/esp32.dtsi (hunk 14 above)
Comment (ydamigos) [reply dts/xtensa/espressif/esp32.dtsi:12]: I agree., it's really strange. I checked odroid_go device tree files several times to find out what is wrong without success. I will try to create a Discord account the following days and ping you there.

File: drivers/spi/spi_esp32_spim.c [hunk 16]
```diff
@@ -419,7 +332,12 @@ static const struct spi_driver_api spi_api = {
 #define GET_AS_CS(idx)
 #endif
 
+#define SPI2_PINSTATE_IDX	0
+#define SPI3_PINSTATE_IDX	1
```
Comment (ydamigos) [inline drivers/spi/spi_esp32_spim.c:336]: these defines doesn't work properly when board has one SPI instance (like odroid_go only has SPI3).

**Review by gmarull — DISMISSED** [review]

**Comment by gmarull** [comment]
compliance failure can be ignored, it's for the `pinctrl_soc_pin_t` typedef.

File: drivers/spi/spi_esp32_spim.c (hunk 16 above)
Comment (mbolivar-nordic) [reply drivers/spi/spi_esp32_spim.c:336]: Perhaps related to what @ydamigos is saying here, this does appear to be using instance numbers incorrectly.

Please read https://docs.zephyrproject.org/latest/reference/devicetree/api.html#c.DT_INST carefully, especially these parts:

```
Instance numbers have the following properties:

- for each compatible, instance numbers start at 0 and are contiguous
- exactly one instance number is assigned for each node with a compatible,
  **including disabled nodes**
- enabled nodes (status property is "okay" or missing) are assigned the
  instance numbers starting from 0, and disabled nodes have instance
  numbers which are greater than those of any enabled node

No other guarantees are made. In particular:

- instance numbers **in no way reflect** any numbering scheme that
  might exist in SoC documentation, node labels or unit addresses,
  or properties of the /aliases node (use DT_NODELABEL() or DT_ALIAS()
  for those)
- there **is no general guarantee** that the same node will have
  the same instance number between builds, even if you are building
  the same application again in the same build directory
```

You seem to be making some assumptions here contrary to what the API guarantees. Please adjust the PR accordingly.

**Review by mbolivar-nordic — DISMISSED** [review]
Please revisit the use of devicetree instance numbers; this does not seem correct to me.

I am leaving a comment on one patch, but the same check should be performed on all the driver changes in this PR.

File: drivers/spi/spi_esp32_spim.c (hunk 16 above)
Comment (ydamigos) [reply drivers/spi/spi_esp32_spim.c:336]: @mbolivar-nordic yes, the issue I am referring to is related with the wrong SPI instance numbers.   
I tried the following changes based on other SPI driver implementations and it works fine:

```
diff --git a/drivers/spi/spi_esp32_spim.c b/drivers/spi/spi_esp32_spim.c
index ae6d249b27..f018c2331f 100644
--- a/drivers/spi/spi_esp32_spim.c
+++ b/drivers/spi/spi_esp32_spim.c
@@ -327,57 +327,48 @@ static const struct spi_driver_api spi_api = {
 };
 
 #ifdef CONFIG_SOC_ESP32
-#define GET_AS_CS(idx) .as_cs = DT_PROP(DT_NODELABEL(spi##idx), clk_as_cs),
+#define GET_AS_CS(idx) .as_cs = DT_INST_PROP(idx, clk_as_cs),
 #else
 #define GET_AS_CS(idx)
 #endif
 
-#define SPI2_PINSTATE_IDX	0
-#define SPI3_PINSTATE_IDX	1
-
 #define ESP32_SPI_INIT(idx)	\
 				\
-PINCTRL_DT_INST_DEFINE(SPI##idx##_PINSTATE_IDX);	\
+PINCTRL_DT_INST_DEFINE(idx);	\
 										\
 	static struct spi_esp32_data spi_data_##idx = {	\
 		SPI_CONTEXT_INIT_LOCK(spi_data_##idx, ctx),	\
 		SPI_CONTEXT_INIT_SYNC(spi_data_##idx, ctx),	\
-		SPI_CONTEXT_CS_GPIOS_INITIALIZE(DT_NODELABEL(spi##idx), ctx)	\
+		SPI_CONTEXT_CS_GPIOS_INITIALIZE(DT_DRV_INST(idx), ctx)	\
 		.hal = {	\
-			.hw = (spi_dev_t *)DT_REG_ADDR(DT_NODELABEL(spi##idx)),	\
+			.hw = (spi_dev_t *)DT_INST_REG_ADDR(idx),	\
 		},	\
 		.dev_config = {	\
-			.half_duplex = DT_PROP(DT_NODELABEL(spi##idx), half_duplex),	\
+			.half_duplex = DT_INST_PROP(idx, half_duplex),	\
 			GET_AS_CS(idx)							\
-			.positive_cs = DT_PROP(DT_NODELABEL(spi##idx), positive_cs),	\
-			.no_compensate = DT_PROP(DT_NODELABEL(spi##idx), dummy_comp),	\
-			.sio = DT_PROP(DT_NODELABEL(spi##idx), sio)	\
+			.positive_cs = DT_INST_PROP(idx, positive_cs),	\
+			.no_compensate = DT_INST_PROP(idx, dummy_comp),	\
+			.sio = DT_INST_PROP(idx, sio)	\
 		}	\
 	};	\
 		\
 	static const struct spi_esp32_config spi_config_##idx = {	\
-		.spi = (spi_dev_t *)DT_REG_ADDR(DT_NODELABEL(spi##idx)),	\
+		.spi = (spi_dev_t *)DT_INST_REG_ADDR(idx),	\
 			\
-		.clock_dev = DEVICE_DT_GET(DT_CLOCKS_CTLR(DT_NODELABEL(spi##idx))),	\
+		.clock_dev = DEVICE_DT_GET(DT_INST_CLOCKS_CTLR(idx)),	\
 		.duty_cycle = 0, \
 		.input_delay_ns = 0, \
-		.irq_source = DT_IRQN(DT_NODELABEL(spi##idx)), \
-		.pcfg = PINCTRL_DT_INST_DEV_CONFIG_GET(SPI##idx##_PINSTATE_IDX),	\
+		.irq_source = DT_INST_IRQN(idx), \
+		.pcfg = PINCTRL_DT_INST_DEV_CONFIG_GET(idx),	\
 		.clock_subsys =	\
-			(clock_control_subsys_t)DT_CLOCKS_CELL(	\
-				DT_NODELABEL(spi##idx), offset),	\
+			(clock_control_subsys_t)DT_INST_CLOCKS_CELL(	\
+				idx, offset),	\
 					\
 	};	\
 		\
-	DEVICE_DT_DEFINE(DT_NODELABEL(spi##idx), &spi_esp32_init,	\
+	DEVICE_DT_INST_DEFINE(idx, &spi_esp32_init,	\
 			      NULL, &spi_data_##idx,	\
 			      &spi_config_##idx, POST_KERNEL,	\
 			      CONFIG_SPI_INIT_PRIORITY, &spi_api);
 
-#if DT_NODE_HAS_STATUS(DT_NODELABEL(spi2), okay)
-ESP32_SPI_INIT(2);
-#endif
-
-#if DT_NODE_HAS_STATUS(DT_NODELABEL(spi3), okay)
-ESP32_SPI_INIT(3);
-#endif
+DT_INST_FOREACH_STATUS_OKAY(ESP32_SPI_INIT)
```

**Comment by glaubermaroto** [comment]
Rebased to solve conflicts.

**Review by sylvioalves — DISMISSED** [review]

**Review by ydamigos — DISMISSED** [review]

**Comment by glaubermaroto** [comment]
> Please revisit the use of devicetree instance numbers; this does not seem correct to me.
> 
> I am leaving a comment on one patch, but the same check should be performed on all the driver changes in this PR.

@mbolivar-nordic I have updated the usage of DT instance numbers on the SPI driver, please, take another look.

**Comment by glaubermaroto** [comment]
I am not sure why but one of the approvals on this PR is not being validated.

**Review by uLipe — DISMISSED** [review]

**Comment by glaubermaroto** [comment]
It was mentioned before by @gmarull on this PR but just as a refresher for whoever is able to merge it:

The compliance failure can be ignored, it's for the `pinctrl_soc_pin_t` typedef.

**Comment by glaubermaroto** [comment]
@carlescufi This PR is ready. How should we proceed? Can we move forward with it?

**Comment by mbolivar-nordic** [comment]
> > I am leaving a comment on one patch, but the same check should be performed on all the driver changes in this PR.
> 
> @mbolivar-nordic I have updated the usage of DT instance numbers on the SPI driver, please, take another look.

@glaubermaroto you seem to have missed the comment that "the same check should be performed on all the driver changes in this PR"

File: drivers/pinctrl/pinctrl_esp32.c [hunk 17]
```diff
@@ -0,0 +1,286 @@
...
+int pinctrl_configure_pins(const pinctrl_soc_pin_t *pins, uint8_t pin_cnt,
+			   uintptr_t reg)
+{
+	uint32_t pin_mux, pin_cfg;
+	int ret = 0;
+
+	ARG_UNUSED(reg);
+
+	for (uint8_t i = 0U; i < pin_cnt; i++) {
+		pin_mux = pins[i].pinmux;
```
Comment (gmarull) [inline drivers/pinctrl/pinctrl_esp32.c:276]:
```suggestion
	ARG_UNUSED(reg);

	for (uint8_t i = 0U; i < pin_cnt; i++) {
		int ret;

		pin_mux = pins[i].pinmux;
```

**Review by gmarull — DISMISSED** [review]
lgtm, compliance check can be ignored (typedef)

**Comment by glaubermaroto** [comment]
> @glaubermaroto you seem to have missed the comment that "the same check should be performed on all the driver changes in this PR"

@mbolivar-nordic It didn't go unnoticed, I did review the other drivers as well. Please, check my dismiss review message above.

File: drivers/pinctrl/pinctrl_esp32.c (hunk 17 above)
Comment (glaubermaroto) [reply drivers/pinctrl/pinctrl_esp32.c:276]: Though, in general, it is good practice to keep variables restricted to the scope they are being used. Here, I'd rather keep it out to avoid variable redefinitions or stack unwinding in different compiling optimization scenarios (including, eventually, debugging).

**Comment by glaubermaroto** [comment]
As stated before, the compliance check can be ignored.

@cfriedt Can you merge this one?

**Comment by cfriedt** [comment]
> As stated before, the compliance check can be ignored.
> 
> @cfriedt Can you merge this one?

@glaubermaroto - I cannot. I only have merge privileges when all checks are passing. @nashif ? @carlescufi ? @stephanosio ?

**Comment by glaubermaroto** [comment]
The last push was a rebase to solve conflicts.

**Review by sylvioalves — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Comment by glaubermaroto** [comment]
> > As stated before, the compliance check can be ignored.
> > @cfriedt Can you merge this one?
> 
> @glaubermaroto - I cannot. I only have merge privileges when all checks are passing. @nashif ? @carlescufi ? @stephanosio ?

@nashif ? @carlescufi ? @stephanosio ?

**Review by ydamigos — APPROVED** [review]
