### PR TITLE
drivers: rtc: stm32: Fixes RTC issues related to device runtime pm (previous pr #62910)

### LINKED ISSUE #62843: drivers: rtc: stm32: It's not possible to set the time when device runtime pm is enabled and LSE is enabled.
**Describe the bug**
In order to set the time or any other RTC register, the backup domain protection has to be disabled by `LL_PWR_EnableBkUpAccess`. 
Normally, this is called once during RTC initialization and everything works fine. After enabling device runtime PM and LSE, the `set_up_fixed_clock_sources` function is called every time after waking up by PM, and part of this function is enabling backup domain protection when LSE is active. This leads to the situation when backup domain protection is enabled all the time and setting the RTC time doesn't work.

Relevant code from function `set_up_fixed_clock_sources` in file `clock_stm32_ll_common.c` :

```
	if (IS_ENABLED(STM32_LSE_ENABLED)) {
		/* LSE belongs to the back-up domain, enable access.*/

		z_stm32_hsem_lock(CFG_HW_RCC_SEMID, HSEM_LOCK_DEFAULT_RETRY);

#if defined(PWR_CR_DBP) || defined(PWR_CR1_DBP) || defined(PWR_DBPR_DBP)
		/* Set the DBP bit in the Power control register 1 (PWR_CR1) */
		LL_PWR_EnableBkUpAccess();
		while (!LL_PWR_IsEnabledBkUpAccess()) {
			/* Wait for Backup domain access */
		}
#endif /* PWR_CR_DBP || PWR_CR1_DBP || PWR_DBPR_DBP */

#if STM32_LSE_DRIVING
		/* Configure driving capability */
		LL_RCC_LSE_SetDriveCapability(STM32_LSE_DRIVING << RCC_BDCR_LSEDRV_Pos);
#endif

		if (IS_ENABLED(STM32_LSE_BYPASS)) {
			/* Configure LSE bypass */
			LL_RCC_LSE_EnableBypass();
		}

		/* Enable LSE Oscillator (32.768 kHz) */
		LL_RCC_LSE_Enable();
		while (!LL_RCC_LSE_IsReady()) {
			/* Wait for LSE ready */
		}

#ifdef RCC_BDCR_LSESYSEN
		LL_RCC_LSE_EnablePropagation();
		/* Wait till LSESYS is ready */
		while (!LL_RCC_LSE_IsPropagationReady()) {
		}
#endif /* RCC_BDCR_LSESYSEN */

#if defined(PWR_CR_DBP) || defined(PWR_CR1_DBP) || defined(PWR_DBPR_DBP)
		LL_PWR_DisableBkUpAccess();
#endif /* PWR_CR_DBP || PWR_CR1_DBP || PWR_DBPR_DBP */

```

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
      STM32L4R5
 - What have you tried to diagnose or workaround this issue?
     Disabling backup domain protection before setting RTC time fixes the problem

**To Reproduce**
1. enable RTC, device runtime PM, and LSE
2. set RTC time 

**Expected behavior**
Time is set correctly

**Impact**
The code execution is halted due to a never-ending while loop in the RTC driver.

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain:  Zephyr SDK

My suggested fix is to disable backup domain protection in `rtc_stm32_set_time`, I can prepare a PR.

### PR DESCRIPTION
**Pull request by coran21**
@erwango @FRASTM 
(I made some mistakes when I was updating the old PR and created this new one)

When device runtime pm is enabled, Backup Domain protection is active most of the time. RTC driver need this protection to be disabled in order to set the time or calibration. Commit in this PR disables the protection in set time and set calibration functions.
In addition, another commit fixes the recently added WAIT macro which makes the set time and set calibration functions nonworking when device runtime is enabled.

I divided the original commit into 3 commits as @faloj suggested.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/62843

### CODE REVIEW

File: drivers/rtc/rtc_ll_stm32.c [hunk 1]
```diff
@@ -79,22 +79,10 @@ struct rtc_stm32_data {
 
 static int rtc_stm32_enter_initialization_mode(bool kernel_available)
```
Comment (faloj) [inline drivers/rtc/rtc_ll_stm32.c:80]: You can remove the kernel_available argument wich is now useless.

Comment (erwango) [reply drivers/rtc/rtc_ll_stm32.c:80]: I guess the whole function is useless.

File: drivers/rtc/rtc_ll_stm32.c [hunk 2]
```diff
@@ -361,7 +349,7 @@ static int rtc_stm32_set_calibration(const struct device *dev, int32_t calibrati
 	}
 
 	/* wait for recalibration to be ok if a previous recalibration occurred */
-	if (!WAIT_FOR(LL_RTC_IsActiveFlag_RECALP(RTC) == 0, 100000, k_msleep(1))) {
+	if (!WAIT_FOR(LL_RTC_IsActiveFlag_RECALP(RTC) == 0, 10000, k_busy_wait(1000))) {
```
Comment (erwango) [inline drivers/rtc/rtc_ll_stm32.c:353]: Is that still required after the previous commit ?

You mention "k_msleep cause disabling backup domain access by pm", but in previous commit, you add systematic handling of back up domain access. Does the problem remain ?

Note: I've seen this problem as well in other cases and I think we need a back up domain access framework, which would be able to handle such conflicts between devices (not requesting it in this PR, but FYI this is in my TODO list).

File: drivers/rtc/rtc_ll_stm32.c (hunk 1 above)
Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c]: I removed that function and replaced with LL function.

File: drivers/rtc/rtc_ll_stm32.c (hunk 2 above)
Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c]: No, it's not needed with fixed backup access, I removed that change from the commit.

File: drivers/rtc/rtc_ll_stm32.c (hunk 1 above)
Comment (faloj) [reply drivers/rtc/rtc_ll_stm32.c]: Well then if you removed it you can also remove the rtc_stm32_leave_initialization_mode function.

Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c]: Yes, that makes sense.

**Review by FRASTM — DISMISSED** [review]

File: drivers/rtc/rtc_ll_stm32.c [hunk 3]
```diff
@@ -346,16 +334,24 @@ static int rtc_stm32_set_calibration(const struct device *dev, int32_t calibrati
 	}
 
 	/* wait for recalibration to be ok if a previous recalibration occurred */
-	if (!WAIT_FOR(LL_RTC_IsActiveFlag_RECALP(RTC) == 0, 100000, k_msleep(1))) {
+	if (!WAIT_FOR(LL_RTC_IsActiveFlag_RECALP(RTC) == 0, 100000, 100000, k_msleep(1))) {
```
Comment (erwango) [inline drivers/rtc/rtc_ll_stm32.c:337]: Will this build ?

Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c]: I didn't have CONFIG_RTC_CALIBRATION active, so it was built for me, but it's a mistake; thanks for letting me know. I fixed that.

File: drivers/rtc/rtc_ll_stm32.c [hunk 4]
```diff
@@ -123,14 +95,14 @@ static int rtc_stm32_configure(const struct device *dev)
 	if ((hour_format != LL_RTC_HOURFORMAT_24HOUR) ||
 	    (sync_prescaler != cfg->sync_prescaler) ||
 	    (async_prescaler != cfg->async_prescaler)) {
-		err = rtc_stm32_enter_initialization_mode(false);
```
Comment (faloj) [inline drivers/rtc/rtc_ll_stm32.c:126]: The error return type is not the same as for rtc_stm32_enter_initialization_mode. You should use an ErrorStatus and check if it's different from SUCCESS and set err accordingly. (same for the other call at line 194).

Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c:126]: I fixed this issue. Does it look correct now?

File: drivers/rtc/rtc_ll_stm32.c [hunk 5]
```diff
@@ -123,14 +95,18 @@ static int rtc_stm32_configure(const struct device *dev)
...
+		ErrorStatus status = LL_RTC_EnterInitMode(RTC);
+
+		if (status != SUCCESS) {
+			err = -EIO;
+		}
 		if (err == 0) {
```
Comment (faloj) [inline drivers/rtc/rtc_ll_stm32.c:103]: This check is probably useless now

Comment (faloj) [inline drivers/rtc/rtc_ll_stm32.c:103]: It may be more explicit to replace it by an else no ?

File: drivers/rtc/rtc_ll_stm32.c [hunk 6]
```diff
@@ -208,10 +188,22 @@ static int rtc_stm32_set_time(const struct device *dev, const struct rtc_time *t
...
+
 	LL_RTC_DisableWriteProtection(RTC);
 
-	err = rtc_stm32_enter_initialization_mode(true);
+	ErrorStatus status = LL_RTC_EnterInitMode(RTC);
+
+	if (status != SUCCESS) {
+		err = -EIO;
+	}
 	if (err) {
```
Comment (faloj) [inline drivers/rtc/rtc_ll_stm32.c:203]: It may be better to merge the two "if" ?

**Comment by erwango** [comment]
@coran21 Can you address @faloj comments ?

File: drivers/rtc/rtc_ll_stm32.c (hunk 5 above)
Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c]: I agree, updated.

File: drivers/rtc/rtc_ll_stm32.c (hunk 6 above)
Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c]: I agree, updated.

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

**Comment by faloj** [comment]
> Otherwise LGTM

Same for me

**Review by faloj — APPROVED** [review]

File: drivers/rtc/rtc_ll_stm32.c [hunk 7]
```diff
@@ -177,10 +177,13 @@ static int rtc_stm32_init(const struct device *dev)
...
 	LL_RCC_EnableRTC();
 
-	z_stm32_hsem_unlock(CFG_HW_RCC_SEMID);
-
 	err = rtc_stm32_configure(dev);
 
+#if defined(PWR_CR_DBP) || defined(PWR_CR1_DBP) || defined(PWR_DBPCR_DBP) || defined(PWR_DBPR_DBP)
+	LL_PWR_DisableBkUpAccess();
+#endif /* PWR_CR_DBP || PWR_CR1_DBP || PWR_DBPR_DBP */
+	z_stm32_hsem_unlock(CFG_HW_RCC_SEMID);
```
[the remark this answers is not in the document]
Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c]: I'm not sure if I understood your proposal correctly. Could you check the new changes? I just put the semaphore where it was originally.

File: drivers/rtc/rtc_ll_stm32.c [hunk 8]
```diff
@@ -146,6 +146,7 @@ static int rtc_stm32_init(const struct device *dev)
 
 	/* Enable RTC clock source */
 	if (clock_control_configure(clk, (clock_control_subsys_t)&cfg->pclken[1], NULL) != 0) {
+		z_stm32_hsem_unlock(CFG_HW_RCC_SEMID);
```
[the remark this answers is not in the document]
Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c:149]: Are you proposing to remove the `hsem` completely? Otherwise, I would keep the missing unlock in the code. As I wrote above I'm not sure if I understand your proposal correctly.

[the remark this answers is not in the document]
Comment (erwango) [reply drivers/rtc/rtc_ll_stm32.c:149]: The lock/unlock around `LL_PWR_EnableBkUpAccess` isn't required

[the remark this answers is not in the document]
Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c]: Ok, I removed them, sorry for that misunderstanding.

File: drivers/rtc/rtc_ll_stm32.c [hunk 9]
```diff
@@ -152,8 +150,6 @@ static int rtc_stm32_init(const struct device *dev)
 
 	LL_RCC_EnableRTC();
```
Comment (erwango) [inline drivers/rtc/rtc_ll_stm32.c:151]: HSEM lock is required but only around `LL_RCC_EnableRTC()`.

So it should be: 
```
z_stm32_hsem_lock(CFG_HW_RCC_SEMID, HSEM_LOCK_DEFAULT_RETRY);

LL_RCC_EnableRTC();

z_stm32_hsem_unlock(CFG_HW_RCC_SEMID);
```

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: drivers/rtc/rtc_ll_stm32.c (hunk 9 above)
Comment (coran21) [reply drivers/rtc/rtc_ll_stm32.c:154]: Got it. I'm still learning, sorry.

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
