### PR TITLE
drivers: flash: flash_rpi_pico: Added buffered flash write for addresses in flash

### LINKED ISSUE #68728: rp2040 flash driver hangs infinitely when used with settings nvs backend
**Describe the bug**
When using the settings api with NVS backend a call to `settings_save_one()` will often hang up and never recover.
The cause seems to be the rp2040 flash driver. It is waiting to receive bytes from the flash but they never arrive so
`flash_put_get()` will run in a while loop. This will never recover. The `tx_count` and `rx_skip` are both 0 but
the while loop is still running because `rx_count` remains non 0 and will never decrease.

I am using a custom board with the rp2040 and a W25Q16JV flash attached to the pico.
Unfortunately i did find no workaround for this.

**To Reproduce**
This can be reproduced with the settings sample `samples/subsys/settings`.
I extended the proj.conf:

```
CONFIG_STDOUT_CONSOLE=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y

CONFIG_SETTINGS=y
CONFIG_SETTINGS_RUNTIME=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
```

And using this device tree

```
/ {
	chosen {
		zephyr,sram = &sram0;
		zephyr,flash = &flash0;
		zephyr,flash-controller = &ssi;
		zephyr,console = &cdc_acm_uart0 ;
		zephyr,shell-uart = &cdc_acm_uart0 ;
		zephyr,code-partition = &slot0_partition;
	};
};

zephyr_udc0: &usbd {
	status = "okay";
	cdc_acm_uart0: cdc_acm_uart0 {
		compatible = "zephyr,cdc-acm-uart";
	};
};

&flash0 {
	reg = <0x10000000 DT_SIZE_M(2)>;

	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;

		/* Reserved memory for the second stage bootloader */
		second_stage_bootloader: partition@0 {
			label = "second_stage_bootloader";
			reg = <0x00000000 0x100>;
			read-only;
		};

		slot0_partition: partition@100 {
			label = "image-0";
			reg = <0x100 (DT_SIZE_M(1) - 0xF000)>;
		};

		storage_partition: partition@1f9000 {
			label = "storage";
			reg = <0x1F9000 0x00007000>;
		};
	};
};
```

To reproduce build this sample with the extended proj.conf and device tree for a rp2040 based board and flash it.
This will consistently hang up in `flash_put_get()` .

**Expected behavior**
Not hanging up during flash write.

**Impact**
This is a showstopper since the settings nvs may hang up the whole system.

**Logs and console output**
Here is a gdb stack trace of the hangup

```
#0  flash_put_get (tx=0x10008de9 "", tx@entry=0x10008de2 "", rx=0x0, count=count@entry=7, rx_skip=0, rx_skip@entry=4) at /data/projects/nfc/zephyr/drivers/flash/flash_rpi_pico.c:105
#1  0x20000548 in flash_write_partial_internal (addr=addr@entry=2072832, data=data@entry=0x10008de2 "", size=size@entry=7) at /data/projects/nfc/zephyr/drivers/flash/flash_rpi_pico.c:157
#2  0x20000226 in flash_write_partial (flash_offs=flash_offs@entry=2072832, data=data@entry=0x10008de2 "", count=count@entry=7) at /data/projects/nfc/zephyr/drivers/flash/flash_rpi_pico.c:180
#3  0x10007ef4 in flash_rpi_write (dev=<optimized out>, offset=<optimized out>, data=<optimized out>, size=<optimized out>) at /data/projects/nfc/zephyr/drivers/flash/flash_rpi_pico.c:241
#4  0x1000730a in z_impl_flash_write (len=12, data=0x10008ddd, offset=2072827, dev=<optimized out>) at /data/projects/nfc/zephyr/include/zephyr/drivers/flash.h:212
#5  flash_write (len=12, data=0x10008ddd, offset=2072827, dev=<optimized out>) at /data/projects/nfc/zephyr/samples/subsys/settings/build/zephyr/include/generated/syscalls/flash.h:64
#6  nvs_flash_al_wrt (fs=fs@entry=0x20000b48 <default_settings_nvs+8>, addr=<optimized out>, data=data@entry=0x10008ddd, len=len@entry=12) at /data/projects/nfc/zephyr/subsys/fs/nvs/nvs.c:122
#7  0x10007620 in nvs_flash_data_wrt (len=12, data=0x10008ddd, fs=0x20000b48 <default_settings_nvs+8>) at /data/projects/nfc/zephyr/subsys/fs/nvs/nvs.c:182
#8  nvs_flash_wrt_entry (len=12, data=0x10008ddd, id=32776, fs=0x20000b48 <default_settings_nvs+8>) at /data/projects/nfc/zephyr/subsys/fs/nvs/nvs.c:415
#9  nvs_write (fs=fs@entry=0x20000b48 <default_settings_nvs+8>, id=id@entry=32776, data=data@entry=0x10008ddd, len=12) at /data/projects/nfc/zephyr/subsys/fs/nvs/nvs.c:1112
#10 0x10003f38 in settings_nvs_save (cs=0x20000b40 <default_settings_nvs>, name=0x10008ddd "", value=0x20000000 <length_val> "d", val_len=8) at /data/projects/nfc/zephyr/subsys/settings/src/settings_nvs.c:297
#11 0x10003aa0 in settings_save_one (name=0x10008ddd "", value=0x20000000 <length_val>, val_len=8) at /data/projects/nfc/zephyr/subsys/settings/src/settings_store.c:106
#12 0x10001d1e in alpha_handle_export (cb=0x10003a75 <settings_save_one>) at /data/projects/nfc/zephyr/samples/subsys/settings/src/main.c:163
#13 0x10003bac in settings_save () at /data/projects/nfc/zephyr/subsys/settings/src/settings_store.c:147
#14 0x10002204 in example_save_and_load_basic () at /data/projects/nfc/zephyr/samples/subsys/settings/src/main.c:245
#15 main () at /data/projects/nfc/zephyr/samples/subsys/settings/src/main.c:555
(gdb) p tx_count
$1 = 0
(gdb) p rx_count
$2 = 1
(gdb) p rx_skip
$3 = 0
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr sdk 0.16.3
 - Commit: zephyr-v3.5.0

### PR DESCRIPTION
**Pull request by lgehreke**
It is impossible to perform flash reads during a flash write. When the data to write to flash lies in the flash itself, for example when using names in the settings api, it is buffered in ram before writing.

This fixes #68728

### CODE REVIEW

**Comment by Laczen** [comment]
@lgehreke thanks for this PR. The same approach seems to be used in `mcux_flexspi_hyperflash`.

The code would simplify when it would always copy to the ram buffer.

Limit the line length to 100 chars.

**Comment by lgehreke** [comment]
The code would be simpler when everything is copied to the ram buffer, but this would introduce unnecessary memcpy operations when the data is already located in ram. Also big writes with sizes of multiple pages can be performed with one call to `flash_range_program()` if the data already lies in ram. If we would perform a ram copy we would introduce a memcpy and a call to `flash_range_program()` for every 256 bytes.

**Comment by Laczen** [comment]
> The code would be simpler when everything is copied to the ram buffer, but this would introduce unnecessary memcpy operations when the data is already located in ram. Also big writes with sizes of multiple pages can be performed with one call to `flash_range_program()` if the data already lies in ram. If we would perform a ram copy we would introduce a memcpy and a call to `flash_range_program()` for every 256 bytes.

Next to simplicity it would also avoid the checking if an address is in ram or not. This check is fragile and might result in problems when other memory mapped devices are used. The disadvantage of not being able to optimize long writes from ram is true, but how frequent would this appear and how big is this disadvantage ?

**Comment by lgehreke** [comment]
> > The code would be simpler when everything is copied to the ram buffer, but this would introduce unnecessary memcpy operations when the data is already located in ram. Also big writes with sizes of multiple pages can be performed with one call to `flash_range_program()` if the data already lies in ram. If we would perform a ram copy we would introduce a memcpy and a call to `flash_range_program()` for every 256 bytes.
> 
> Next to simplicity it would also avoid the checking if an address is in ram or not. This check is fragile and might result in problems when other memory mapped devices are used. The disadvantage of not being able to optimize long writes from ram is true, but how frequent would this appear and how big is this disadvantage ?

Is it possible that other memory mapped devices map in the address space of the chip itself?

**Comment by Laczen** [comment]
> > > The code would be simpler when everything is copied to the ram buffer, but this would introduce unnecessary memcpy operations when the data is already located in ram. Also big writes with sizes of multiple pages can be performed with one call to `flash_range_program()` if the data already lies in ram. If we would perform a ram copy we would introduce a memcpy and a call to `flash_range_program()` for every 256 bytes.
> > 
> > 
> > Next to simplicity it would also avoid the checking if an address is in ram or not. This check is fragile and might result in problems when other memory mapped devices are used. The disadvantage of not being able to optimize long writes from ram is true, but how frequent would this appear and how big is this disadvantage ?
> 
> Is it possible that other memory mapped devices map in the address space of the chip itself?

Yes, and as far as I know the rpi2040 is also doing this by mapping an external spi flash chip to an address space of the chip itself.

There are other devices that are using a similar setup: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/Kconfig.mcux#L86 (and L95) shows that a write buffer is default enabled to avoid the same error you are experiencing.

**Comment by lgehreke** [comment]
> > > > The code would be simpler when everything is copied to the ram buffer, but this would introduce unnecessary memcpy operations when the data is already located in ram. Also big writes with sizes of multiple pages can be performed with one call to `flash_range_program()` if the data already lies in ram. If we would perform a ram copy we would introduce a memcpy and a call to `flash_range_program()` for every 256 bytes.
> > > 
> > > 
> > > Next to simplicity it would also avoid the checking if an address is in ram or not. This check is fragile and might result in problems when other memory mapped devices are used. The disadvantage of not being able to optimize long writes from ram is true, but how frequent would this appear and how big is this disadvantage ?
> > 
> > 
> > Is it possible that other memory mapped devices map in the address space of the chip itself?
> 
> Yes, and as far as I know the rpi2040 is also doing this by mapping an external spi flash chip to an address space of the chip itself.
> 
> There are other devices that are using a similar setup: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/flash/Kconfig.mcux#L86 (and L95) shows that a write buffer is default enabled to avoid the same error you are experiencing.

Yes, that is the same problem. According to rp2040 datasheet section 2.2.2, 2.6.2 and 2.6.3 the qspi flash is always mapped to  0x10000000 and the ram is mapped to 0x20000000 so why should the check if the data is located in flash fragile?

**Comment by Laczen** [comment]
@lgehreke, in most cases (don't know about the rp2040) it would be possible to setup an alternative external QSPI device that could also be memory mapped to a different address. In that case it would cause problems.

I prefer the solution used for the mcux: a always working solution is enabled by default, a possibility is created to avoid doing a copy when wanted/possible. This creates smaller binaries for both solutions.

File: drivers/flash/flash_rpi_pico.c [hunk 1]
```diff
@@ -246,6 +275,29 @@ static int flash_rpi_write(const struct device *dev, off_t offset, const void *d
 	return 0;
 }
 
+static bool data_in_flash(const void *data)
```
Comment (de-nordic) [inline drivers/flash/flash_rpi_pico.c:278]: I am not sure this check is correct. SRAM is based at 0x20000000 and the XIP/SSI mapped region starts at 0x10000000, but it consists on many sub-regions that have different meanings.
Regions between 0x14000000-0x20000000 do not map to flash, and the 0x18000000-0x20000000 is actually range of SSI control registers.
The 0x20000000-0x13ffffff is actually 0x10000000 remapped with different attributes.
Btw. shouldn't this be rather named `data_in_xip_region`, it is not exactly in flash as the region contains possible cache check first.

Comment (lgehreke) [reply drivers/flash/flash_rpi_pico.c:278]: Should this check be used or is the always copy to ram solution by @Laczen preferred?

Comment (de-nordic) [reply drivers/flash/flash_rpi_pico.c:278]: The preference is on @yonsch , as far as I remember he is the platform maintainer.

I do not think that code size is an issue here, as the rpi uses external device for code, so having both functions is fine.
I guess that most of code would make ram-to-flash copy rather than flash-to-flash, which means that memcpy is just taking clocks; with a delay that the SPI processing would take it probably isn't that much on CPU. On the other side we do irq_lock here which means that we keep the irq_lock longer than probably needed in most cases.

I would stick with buffered/unbuffered separation.

I also wonder whether there should be added irq_unlock/lock within loop to allow irq processing between calls to write (@yonsch ?)

Comment (de-nordic) [reply drivers/flash/flash_rpi_pico.c:278]: I have missed the BSS usage by the flash_ram_buffer, which is PAGE_SIZE, it may be issue for some.
Anyway, in case of Nordic QSPI driver we have something like this:
https://github.com/zephyrproject-rtos/zephyr/blob/c33743ef955b066a5711097a6b0e184de1519b7f/drivers/flash/Kconfig.nordic_qspi_nor#L31-L41
where we also use intermediate buffer to copy data through and it is mostly enabled.

**Comment by yonsch** [comment]
A few general comments -
1. irq lock/unlock - IIRC it's only used to protect against context switches happening while the flash is out of XIP mode. It might be possible to move the locking and unlocking into `flash_write_partial` to allow other services to run in the background. However, it makes me think how thread safe this driver is now that it uses a global buffer for writing. Is it possible that two threads would try writing to flash simultaneously?
2. valid range - I can't say for sure if more areas other than the flash would cause problems as the datasheet is not too verbose in that area. We can either go the safe way and buffer everything from `XIP_BASE` to `XIP_SRAM_END` (worst that could happen is we get some memory copies in those areas, though I find it hard to believe any user would accidentally try to copy something from those addresses), or we can buffer only addresses that are inside the flash defined by devicetree, and if there's a problem someone will report it at some point :).
3. always buffer - I'm not too concerned about it as memcpy is not too much of an overhead compared to the actual write. Maybe we can make this configurable in three modes - always buffer, never buffer (to save RAM/cycles on tight projects not using NVS) and conditional buffer, although this is probably an overkill.

**Comment by lgehreke** [comment]
So the preference is on you @yonsch. Should we always buffer since the check may be faulty or should i implement the configurable modes?

**Comment by yonsch** [comment]
> So the preference is on you @yonsch. Should we always buffer since the check may be faulty or should i implement the configurable modes?

@lgehreke Let's do the always buffer approach and if anyone ever complains we'll add the other options as well :)

**Review by Laczen — APPROVED** [review]
LGTM

**Review by de-nordic — APPROVED** [review]

**Review by yonsch — APPROVED** [review]

**Comment by zhang-wenchao** [comment]
I've encountered a new problem: nvs_write sucesssful, Using nvs_read results in a -2 error, [No such file or directory.](https://docs.zephyrproject.org/latest/doxygen/html/errno_8h.html)

```
[00:00:01.004,000] <dbg> fs_nvs: nvs_recover_last_ate: Recovering last ate from sector 0
[00:00:01.015,000] <dbg> fs_nvs: nvs_add_gc_done_ate: Adding gc done ate at ff0
[00:00:01.026,000] <inf> fs_nvs: 768 Sectors of 4096 bytes
[00:00:01.030,000] <inf> fs_nvs: alloc wra: 0, fe8
[00:00:01.035,000] <inf> fs_nvs: data wra: 0, 0
NVS Configuration:
  Flash device: 0x10018190 (flash-controller@18000000)
  Offset: 0x100000 (1048576)
  Sector size: 4096 bytes
  Sector count: 768
  Total size: 3145728 bytes
check id 5 res -2 00 00
storage check 0
write id 5 res 6
storage write 1
check id 5 res -2 00 00
storage check 0
```
