### PR TITLE
Bluetooth: LE: HCI: Added bt_le_set_default_phy command

### LINKED ISSUE #89889: Not able to keep PHY at 1M when connecting with iPhone
**Describe the bug**

I (Peripheral) wants to connect with iPhone(Central) and make sure connection PHY is 1M.
Please note that my device (peripheral) supports 2M, i just want to use 1M.
I tried the recommended settings (gathered by reading zephyr doc + google search), but the iPhone moves the PHY to 2M after connection.

**To Reproduce**
To make this happen i set following config params

CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_PHY_CODED=n
# Tell user about phy update
CONFIG_BT_USER_PHY_UPDATE=y
# Udpate PHY
CONFIG_BT_PHY_UPDATE=n
#https://devzone.nordicsemi.com/f/nordic-q-a/119628/how-to-set-cis-phy-to-1m-in-le-audio
CONFIG_BT_AUTO_PHY_UPDATE=n

The expectation was that connection will happen at 1M.

The initial connection happens at 1M. After that iPhone sends a phy request (preferring 2M), my device (peripheral) responds with PHY response (preferring 2M). This leads to PHY moving to 2M.

See below screen grab of OTA.

Image

**Expected behavior**
iPhone ends phy request (preferring 2M) and my device (peripheral) responds with PHY response (preferring 1M).

Please note: as a work around i created a fork of zephyr (https://github.com/zephyrproject-rtos/zephyr/pull/87810) . This makes use of LE_SET_DEFAULT_PHY HCI commands. This enables me to achieve right behaviour (See OTA below)

Image

**Environment (please complete the following information):**
Zephyr OS build ba3251d14138
 

**What configuration i need to do to achieve the desired behaviour?**

### PR DESCRIPTION
**Pull request by mahori-ravinder**
Added bt_le_set_default_phy in hci. This handles the HCI_LE_Set_Default_PHY HCI command.

BLUETOOTH CORE SPECIFICATION Version 6.0 | Vol 4, Part E
7.8.48 LE Set Default PHY command

Signed-off-by: Ravinder Singh <ravinder.singh2@infineon.com>

Fixes #89889

### CODE REVIEW

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -1132,6 +1132,27 @@ static int hci_le_read_phy(struct bt_conn *conn)
 }
 #endif /* defined(CONFIG_BT_USER_PHY_UPDATE) */
 
+
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:1136]: Three empty lines?

File: subsys/bluetooth/host/hci_core.c [hunk 2]
```diff
@@ -1132,6 +1132,27 @@ static int hci_le_read_phy(struct bt_conn *conn)
...
+	cp = net_buf_add(buf, sizeof(*cp));
+	cp->all_phys = all_phys;
+	cp->tx_phys = pref_tx_phy;
+	cp->rx_phys = pref_rx_phy;
+
+	return bt_hci_cmd_send_sync(BT_HCI_OP_LE_SET_DEFAULT_PHY, buf, NULL);
+}
+
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:1155]: Two empty lines? You should ever only need one in C code.

**Review by jhedberg — CHANGES_REQUESTED** [review]
A couple of style comments. Please also pay attention to the Compliance check failure.

However, a more serious concern: here you're adding a new internal API, but no callers for it, i.e. it's effectively dead code. We don't generally allow dead code in Zephyr.

**Comment by mahori-ravinder** [comment]
> A couple of style comments. Please also pay attention to the Compliance check failure.
> 
> However, a more serious concern: here you're adding a new internal API, but no callers for it, i.e. it's effectively dead code. We don't generally allow dead code in Zephyr.

@jhedberg  Thanks for your comment. I expect the application to directly call this API (bt_le_set_default_phy). The header file (hci_core.h) doesn't say anything about users not using this directly.

- is this wrong expectation?
- Shall i wrap this in some upper layer and make available to user?

Thanks for your time!

File: subsys/bluetooth/host/hci_core.c (hunk 1 above)
Comment (mahori-ravinder) [reply subsys/bluetooth/host/hci_core.c:1136]: Thanks. will run the compliance check locally before pushing update.

**Comment by jhedberg** [comment]
@mahori-ravinder all Zephyr public APIs are found under `include/zephyr` (`include/zephyr/bluetooth` for Bluetooth). That's also what apps get by default in their include lookup path, i.e. you have to play extra tricks to get something like `subsys/bluetooth/host/` included. If you want to propose this as a public API it needs to go under `include/zephyr/bluetooth`, and you should also introduce at least one sample or test app that uses the API, so that we get CI coverage for it.

**Comment by mahori-ravinder** [comment]
Updated the code to expose the API to application through conn.h
Please note that this API doesn't require connection to exist to call, but there is no need for anyone to call this if they don't want to connect ever, hence exposed via conn.h

Working on adding/updating example that uses this.

File: include/zephyr/bluetooth/conn.h [hunk 3]
```diff
@@ -1222,6 +1222,19 @@ int bt_conn_le_data_len_update(struct bt_conn *conn,
...
+ *  Update the preferred transmit and receive PHYs of LE transport.
+ *  Use @ref BT_GAP_LE_PHY_NONE to indicate no preference.
+ *
+ *  @param pref_tx_phy  Preferred transmitter phy prarameters.
+ *  @param pref_rx_phy  Preferred receiver phy prameters.
+ *
+ *  @return Zero on success or (negative) error code on failure.
+ */
+int bt_conn_le_set_default_phy(uint8_t pref_tx_phy, uint8_t pref_rx_phy);
+
```
Comment (cvinayak) [inline include/zephyr/bluetooth/conn.h:1237]: Add a call to this new function here: 
https://github.com/zephyrproject-rtos/zephyr/blob/3c7e43f4e2ba87c2427bb74d6fa5fa6b3311891d/samples/bluetooth/central_gatt_write/src/central_gatt_write.c#L97
before starting scan and here
https://github.com/zephyrproject-rtos/zephyr/blob/3c7e43f4e2ba87c2427bb74d6fa5fa6b3311891d/samples/bluetooth/peripheral_gatt_write/src/peripheral_gatt_write.c#L69
before starting advertising, for coverage in samples and be run in BabbleSIM PR CI.

**Review by cvinayak — DISMISSED** [review]

File: include/zephyr/bluetooth/conn.h (hunk 3 above)
Comment (mahori-ravinder) [reply include/zephyr/bluetooth/conn.h:1237]: Will do. Thanks.

Comment (mahori-ravinder) [reply include/zephyr/bluetooth/conn.h]: @cvinayak  Updated the samples  (peripheral_gatt_write and central_gatt_write) to call the newly added function.

**Comment by mahori-ravinder** [comment]
> @mahori-ravinder all Zephyr public APIs are found under `include/zephyr` (`include/zephyr/bluetooth` for Bluetooth). That's also what apps get by default in their include lookup path, i.e. you have to play extra tricks to get something like `subsys/bluetooth/host/` included. If you want to propose this as a public API it needs to go under `include/zephyr/bluetooth`, and you should also introduce at least one sample or test app that uses the API, so that we get CI coverage for it.

@jhedberg 
The newly added function is exposed via conn.h
For coverage, added call to this function in 2 samples as suggested by @cvinayak

File: subsys/bluetooth/host/hci_core.c [hunk 4]
```diff
@@ -1194,8 +1194,6 @@ static int hci_le_read_phy(struct bt_conn *conn)
 }
 #endif /* defined(CONFIG_BT_USER_PHY_UPDATE) */
 
-
-
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: Please squash this into the commit that originally introduced the empty lines

File: subsys/bluetooth/host/hci_core.c [hunk 5]
```diff
@@ -1214,7 +1212,6 @@ int bt_le_set_default_phy(uint8_t all_phys, uint8_t pref_tx_phy, uint8_t pref_rx
 	return bt_hci_cmd_send_sync(BT_HCI_OP_LE_SET_DEFAULT_PHY, buf, NULL);
 }
 
-
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: Same here.

File: subsys/bluetooth/host/conn.c [hunk 6]
```diff
@@ -3535,17 +3535,17 @@ int bt_conn_le_phy_update(struct bt_conn *conn,
...
 
-    if (pref_rx_phy == BT_GAP_LE_PHY_NONE) {
-        all_phys |= BT_HCI_LE_PHY_RX_ANY;
-    }
+	if (pref_rx_phy == BT_GAP_LE_PHY_NONE) {
+		all_phys |= BT_HCI_LE_PHY_RX_ANY;
+	}
 
-    return bt_le_set_default_phy(all_phys, pref_tx_phy, pref_rx_phy);
+	return bt_le_set_default_phy(all_phys, pref_tx_phy, pref_rx_phy);
```
Comment (jhedberg) [inline subsys/bluetooth/host/conn.c]: What's going on here? Please fix this in the commit that introduced it.

File: subsys/bluetooth/host/hci_core.c [hunk 7]
```diff
@@ -1199,9 +1199,9 @@ int bt_le_set_default_phy(uint8_t all_phys, uint8_t pref_tx_phy, uint8_t pref_rx
 	struct bt_hci_cp_le_set_default_phy *cp;
 	struct net_buf *buf;
 
-	buf = bt_hci_cmd_create(BT_HCI_OP_LE_SET_DEFAULT_PHY, sizeof(*cp));
+	buf = bt_hci_cmd_alloc(K_FOREVER);
 	if (!buf) {
-	return -ENOBUFS;
+		return -ENOBUFS;
 	}
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: Same here.

**Review by jhedberg — CHANGES_REQUESTED** [review]
You need to squash the fixes you made to the first commit into that commit, rather than doing them in later commits. `git rebase -i` is quite useful here.

File: subsys/bluetooth/host/hci_core.c (hunk 7 above)
Comment (mahori-ravinder) [reply subsys/bluetooth/host/hci_core.c]: Squashed all commits into 1. Thanks.

File: subsys/bluetooth/host/conn.c (hunk 6 above)
Comment (mahori-ravinder) [reply subsys/bluetooth/host/conn.c]: Squashed all commits into 1. Thanks.

File: subsys/bluetooth/host/hci_core.c (hunk 4 above)
Comment (mahori-ravinder) [reply subsys/bluetooth/host/hci_core.c]: Squashed all commits into 1. Thanks.

File: include/zephyr/bluetooth/conn.h [hunk 8]
```diff
@@ -1226,6 +1226,19 @@ int bt_conn_le_data_len_update(struct bt_conn *conn,
...
 			  const struct bt_conn_le_phy_param *param);
 
+/** @brief Update the default PHY parameters to be used for all subsequent
+ * connections over the LE transport.
+ *
+ *  Update the preferred transmit and receive PHYs of LE transport.
+ *  Use @ref BT_GAP_LE_PHY_NONE to indicate no preference.
+ *
+ *  @param pref_tx_phy  Preferred transmitter phy prarameters.
+ *  @param pref_rx_phy  Preferred receiver phy prameters.
```
Comment (jhedberg) [inline include/zephyr/bluetooth/conn.h]: I think this should be clearer on what the allowed values are and where they're defined. You mention one of them (`BT_GAP_LE_PHY_NONE`), but where would a developer find the other valid values?

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: include/zephyr/bluetooth/conn.h (hunk 8 above)
Comment (mahori-ravinder) [reply include/zephyr/bluetooth/conn.h]: @jhedberg  Updated documentation with a ref to bt_gap_le_phy

**Comment by mahori-ravinder** [comment]
@jhedberg  Acted on your comment.
+ there were formatting issues with commit message itself. Ran the compliance check script locally to verify that those are resolved. 
Thanks.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/hci_core.c [hunk 9]
```diff
@@ -1194,6 +1194,24 @@ static int hci_le_read_phy(struct bt_conn *conn)
 }
 #endif /* defined(CONFIG_BT_USER_PHY_UPDATE) */
 
+int bt_le_set_default_phy(uint8_t all_phys, uint8_t pref_tx_phy, uint8_t pref_rx_phy)
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/hci_core.c:1197]: I think it would be better YAGNI to just inline this `bt_le_set_default_phy` into `bt_conn_le_set_default_phy` and I would prefer that.

I understand this is the boilerplate for sending the specific command, and it even includes the not-yet-used argument `all_phys` (whatever that is), but I argue that this boilerplate is not completely general may not be always appropriate since it chooses `K_FOREVER`.

@jhedberg, do you agree with me?

Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c:1197]: I'm not opposed to inlining, but it's not completely clear what exactly the benefit of that is, since `bt_le_set_default_phy()` is an internal API way.

**Review by alwa-nordic — APPROVED** [review]

File: subsys/bluetooth/host/hci_core.c (hunk 9 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/hci_core.c:1197]: I approved now to not keep this PR over this. The benefit I see is just better readability.

**Comment by mahori-ravinder** [comment]
@cvinayak  This PR merge is pending your approval. Do have a look when you get chance.
