### PR TITLE
Fix posix stat

### LINKED ISSUE #58911: POSIX stat function returns filesystem statistics, not file statistics
Please see Discord discussion https://discord.com/channels/720317445772017664/883450954878439445/1115355325055381625 .

**Describe the bug**
When using the POSIX function stat the returned statistics are not those of the file passed as an argument, but that from the filesystem the file is located on.

The bug present in the current master, and appears in the POSIX filesystem layer of Zephyr.

**To Reproduce**
Write application which uses stat function with CONFIG_POSIX_FS=y  . 

**Expected behavior**
To get actual information of the file.

**Impact**
File size and attribute retrieval will not return the expected result. For example our application using mongoose did not function properly, as mongoose uses the stat function to determine the file size when using the default filesystem API.

**Environment (please complete the following information):**
 - Linux (Ubuntu 20.04)
 - Zephyr SDK 0.15.2
 - Zephyr 3.3.0

**Additional context**
CONFIG_POSIX_FS=y
See:
https://github.com/zephyrproject-rtos/zephyr/blob/be1e7e8c37a6ebedd830a0cc73d33c3407b04029/lib/posix/fs.c#L359
I would expect it to call fs_stat and not fs_statvfs  as it does now.

### PR DESCRIPTION
**Pull request by plinnie**
This commit fixes [#58911](https://github.com/zephyrproject-rtos/zephyr/issues/58911) where the stat command only returned information on the filesystem, and not the actual file itself. It also adds some tests for the POSIX stat command.

### CODE REVIEW

File: tests/posix/fs/src/test_fs_stat.c [hunk 1]
```diff
@@ -0,0 +1,140 @@
+/*
+ * Copyright (c) 2023 Nikhef
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <string.h>
+#include <fcntl.h>
```
Comment (cfriedt) [inline tests/posix/fs/src/test_fs_stat.c:8]: Please also add the `<zephyr/posix/..>` prefix here

File: lib/posix/fs.c [hunk 2]
```diff
@@ -349,22 +349,45 @@ int unlink(const char *path)
...
+
+	switch (stat_file.type) {
+	case FS_DIR_ENTRY_FILE:
+		buf->st_mode = S_IFREG;
+		break;
+	case FS_DIR_ENTRY_DIR:
+		buf->st_mode = S_IFDIR;
+		break;
+	default:
+		/* what about this? */
```
Comment (cfriedt) [inline lib/posix/fs.c:382]: `EIO` maybe?
https://pubs.opengroup.org/onlinepubs/9699919799/functions/stat.html

File: tests/posix/fs/src/test_fs_stat.c [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+	res = unlink(TEST_DIR);
+	if (res < 0) {
+		TC_PRINT("Failed to unlink file " TEST_DIR " [%d]\n", res);
+		__ASSERT_NO_MSG(res == 0);
+	}
+
+	test_unmount(NULL);
+}
+
+ZTEST_SUITE(posix_fs_stat_test, NULL, setup_fn, NULL, NULL, teardown_fn);
```
Comment (cfriedt) [inline tests/posix/fs/src/test_fs_stat.c:95]: it might be better to convert these to before and after

Comment (plinnie) [reply tests/posix/fs/src/test_fs_stat.c:95]: Afaik these functions which are called at the setup and teardown of the test-suite should be called accordingly. Though a quick search through the Zephyr code-base seems to indicate that nobody is really consistent with this. However, as you can see here: https://github.com/zephyrproject-rtos/zephyr/blob/68dc53b0779a37342f86a29362c8efdafdcea005/tests/bluetooth/audio/ascs/src/test_ase_state_transition_invalid.c#L67 they also use setup and teardown naming

File: tests/posix/fs/src/test_fs_stat.c (hunk 1 above)
Comment (plinnie) [reply tests/posix/fs/src/test_fs_stat.c:8]: Fixed

File: tests/posix/fs/src/test_fs_stat.c [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+
+	uint8_t filling[FILL_SIZE];
+
+	while (size > FILL_SIZE) {
+		res = write(fh, filling, FILL_SIZE);
+		size -= FILL_SIZE;
+	}
+
+	res = write(fh, filling, size);
+	if (res < 0) {
```
Comment (cfriedt) [inline tests/posix/fs/src/test_fs_stat.c:38]: I would just zassert here as well

File: tests/posix/fs/src/test_fs_stat.c [hunk 5]
```diff
@@ -0,0 +1,140 @@
...
+		TC_PRINT("Failed writing to file [%d]\n", res);
+		close(fh);
+		__ASSERT_NO_MSG(res == 0);
+	}
+
+	res = close(fh);
```
Comment (cfriedt) [inline tests/posix/fs/src/test_fs_stat.c:44]: This could also just be zassert

File: tests/posix/fs/src/test_fs_stat.c [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+	}
+}
+
+static void *setup_fn(void)
+{
+	int res;
+
+	test_mount();
+
+	res = mkdir(TEST_DIR, 0070);
```
Comment (cfriedt) [inline tests/posix/fs/src/test_fs_stat.c:57]: Could also be zassert

File: tests/posix/fs/src/test_fs_stat.c [hunk 7]
```diff
@@ -0,0 +1,140 @@
...
+	return NULL;
+}
+
+static void teardown_fn(void *unused)
+{
+	ARG_UNUSED(unused);
+
+	int res;
+
+	res = unlink(TEST_FILE);
```
Comment (cfriedt) [inline tests/posix/fs/src/test_fs_stat.c:76]: Could also be zassert

File: tests/posix/fs/src/test_fs_stat.c [hunk 8]
```diff
@@ -0,0 +1,140 @@
...
+	if (res < 0) {
+		TC_PRINT("Failed to unlink file " TEST_FILE " [%d]\n", res);
+		__ASSERT_NO_MSG(res == 0);
+	}
+	res = unlink(TEST_DIR_FILE);
```
Comment (cfriedt) [inline tests/posix/fs/src/test_fs_stat.c:81]: Same - zassert

File: tests/posix/fs/src/test_fs_stat.c [hunk 9]
```diff
@@ -0,0 +1,140 @@
...
+	if (res < 0) {
+		TC_PRINT("Failed to unlink file " TEST_DIR_FILE " [%d]\n", res);
+		__ASSERT_NO_MSG(res == 0);
+	}
+	res = unlink(TEST_DIR);
```
Comment (cfriedt) [inline tests/posix/fs/src/test_fs_stat.c:86]: Ah yes - so this you can also zassert on even in setup / teardown.

The only reason I suggest doing it in before / after is that it would ensure there is no shared state between tests.

The setup / teardown functions are mostly used for allocation or deallocation of a test fixture (see `TEST_F`). Even if it simply returns a pointer to a struct that has one static declaration.

File: tests/posix/fs/src/test_fs_stat.c (hunk 3 above)
Comment (cfriedt) [reply tests/posix/fs/src/test_fs_stat.c:95]: setup / teardown are only called once per suite and not once per test, so naming might be a bit confusing.

So the only reason I suggest before & after is so that there is no shared state between tests

Comment (plinnie) [reply tests/posix/fs/src/test_fs_stat.c:95]: I can do it, but in principle (I know this is an assumption) there should only be read actions to the storage using the stat function. If the stat function does happen write to the storage it may also corrupt the underlying filesystem which is not reset between tests, as far as I can tell. I think we should also then clear the RAM before each mount operation, such that each tests indeed has a completely clean slate.

File: tests/posix/fs/src/test_fs_stat.c (hunk 9 above)
Comment (plinnie) [reply tests/posix/fs/src/test_fs_stat.c]: So, I have converted the setup / teardown to before and after, but kept the mounting and unmounting in the setup and teardown as is done with other test suits.

File: tests/posix/fs/src/test_fs_stat.c (hunk 3 above)
Comment (plinnie) [reply tests/posix/fs/src/test_fs_stat.c]: Please see comments below.

**Review by cfriedt — APPROVED** [review]

File: tests/posix/fs/src/test_fs_stat.c (hunk 3 above)
Comment (cfriedt) [reply tests/posix/fs/src/test_fs_stat.c]: thanks!

**Review by nashif — APPROVED** [review]
