### PR TITLE
Fix unstable tests involving nRF system timer

### LINKED ISSUE #35509: tests: timer: Unstable tests using timer at nrf platforms
**Describe the bug**
Once in a few runs tests 
tests/kernel/timer/timer_api/: test_timeout_abs (sometimes fails on nrf9160dk_nrf9160, often on nrf5340dk_nrf5340_cpuappns )
tests/posix/common/ : test_posix_realtime (sometimes at nrf9160, often on nrf5340dk_nrf5340_cpuappns)
are failing, respectively:
```
START - test_timeout_abs
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:777: test_timeout_abs: (t0 + rem_ticks == exp_ticks is false)
Wrong remaining: now 135407 rem 327544594 expires 327680000 (1)
FAIL - test_timeout_abs in 0.20 seconds
```
```
START - test_posix_realtime
POSIX clock set APIs
Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/clock.c:75: test_posix_realtime: (rts.tv_nsec not equal to mts.tv_nsec)
Nanoseconds not equal
FAIL - test_posix_realtime
```

I created a combined issue as there might be the same root cause for these. Sorry for such imprecise language (often, sometimes). I haven't counted the success/fail rate, just run it several times in a row, also saw these test sometimes failing in our on-target CI. It is possible that the tests are also unstable on other (not mentioned here) nrf platforms, but I haven't caught it. 

**Environment:**
 - OS: Ubuntu 18.04
 - Toolchain zephyr-sdk 0.12.2
 - Commit SHA or Version used v2.6.0-rc1-244-gaa78a6473b16

**Additional context**

### PR DESCRIPTION
**Pull request by anangl**
Fixes #35509.

*kernel: timeout: Fix adding of an absolute timeout*

Correct the way the relative ticks value is calculated for an absolute
timeout. Previously, elapsed() was called twice and the returned value
was first subtracted from and then added to the ticks value. It could
happen that the HW counter value read by elapsed() changed between the
two calls to this function. This caused the test_timeout_abs test case
from the timer_api test suite to occasionally fail, e.g. on certain nRF
platforms.

*drivers: nrf_rtc_timer: Remove unnecessary locking*

As per description of the sys_clock_elapsed() function, "the kernel
will call this with appropriate locking, the driver needs only provide
an instantaneous answer". Remove then the unnecessary locking from the
function, as it only adds an undesirable delay.

The above delay combined with the disabled instruction cache (the issue
fixed initially by #35455, then by #35510) caused the test_posix_realtime
test case from the posix_apis test suite to fail on some nRF platforms
(see #35509).

### CODE REVIEW

File: kernel/timeout.c [hunk 1]
```diff
@@ -90,20 +90,21 @@ void z_add_timeout(struct _timeout *to, _timeout_func_t fn,
 	__ASSERT_NO_MSG(arch_mem_coherent(to));
 #endif
 
-	k_ticks_t ticks = timeout.ticks + 1;
-
-	if (IS_ENABLED(CONFIG_TIMEOUT_64BIT) && Z_TICK_ABS(ticks) >= 0) {
-		ticks = Z_TICK_ABS(timeout.ticks) - (curr_tick + elapsed());
-	}
```
Comment (andyross) [inline kernel/timeout.c:97]: Good catch.  Indeed, this computation should always have happened inside the lock, anyway.

File: drivers/timer/nrf_rtc_timer.c [hunk 2]
```diff
@@ -386,11 +386,7 @@ uint32_t sys_clock_elapsed(void)
 		return 0;
 	}
 
-	k_spinlock_key_t key = k_spin_lock(&lock);
-	uint32_t ret = counter_sub(counter(), last_count) / CYC_PER_TICK;
-
-	k_spin_unlock(&lock, key);
```
Comment (andyross) [inline drivers/timer/nrf_rtc_timer.c:392]: This looks wrong.  That comment isn't saying you don't need synchronization, it's saying that this function isn't reentrant: you don't need to worry about other users of the timeout system asking for the current time simultaneously.

In fact that last_count variable is mutated from an ISR, so if you aren't locking interrupts this can race, e.g.:

* Call `counter()`, which returns a time 1 cycle before the expiration value "`T`"
* The counter advances and the interrupt preempts, then advances last_count to be equal to `T`
* The ISR returns and this subtracts last_count (now "`T`") from counter()'s result from earlier ("`T - 1`"), giving `0xffffff`
* The world blows up due to the overflowed value

Maybe I should remove that sentence in the docs.

**Review by andyross — CHANGES_REQUESTED** [review]
Bug fix looks great.  Optimization seems wrong, unless I missed something.

**Comment by andyross** [comment]
Ah, but this is a single-CPU system and in fact all existing usage (after the fix in the first patch here) is done with a spinlock held and interrupts masked.  I'm not completely sure that's safe to document, but this isn't actually a bug as it stands.  Might be worth a comment explaining, and maybe an assertion to check that interrupts are masked, but I don't see why this can't go in.  I'll remove my -1.

**Review by andyross — APPROVED** [review]

**Review by nashif — APPROVED** [review]
