### PR TITLE
kernel: Reset the switch_handler only in the arch code

### LINKED ISSUE #40795: Timer signal thread execution loop break SMP on ARM64
See code at ([https://github.com/fkan-ec/zephyr.git](https://github.com/fkan-ec/zephyr.git)) pulled from Zephyr latest main, the problem was replicated at multiple release points including v2.7.

The samples/old directory contains main function which spins up multiple threads that takes signals from multiple timer routines. The timer routine regularly signal the threads to  run a simple multiplication routine. The program would run a bit and one of the thread would crash from stack overflow. Adjusting stack size does not seem to remedy the problem. Enable CONFIG_THREAD_ANALYZER seems to deter the problem from happening.

Primarily uses the qemu_cortex_a53_smp platform to test this code, but also tried this on actual ARMv8 hardware.

Steps to reproduce the behavior: (0.13.2 SDK)
1. west build -p -b qemu_cortex_a53_smp samples/old
2. west -b build -t run

**Expected behavior**
One of the thread would stack overflow
uart:~$ E: ELR_ELn: 0x0000000040016670
E: ESR_ELn: 0x0000000056000002
E:   EC:  0x15 (Unknown)
E:   IL:  0x1
E:   ISS: 0x2
E: TPIDRRO: 0x020000004002b030
E: x0:  0x0000000040083d78  x1:  0x0000000000000000
E: x2:  0x0000000000000000  x3:  0x0000000000000000
E: x4:  0x00000000400284f0  x5:  0x0000000000000001
E: x6:  0x0000000000000000  x7:  0x0000000000000001
E: x8:  0x0000000000000002  x9:  0x00000000400284f0
E: x10: 0x0000000000000000  x11: 0x0000000040075a50
E: x12: 0x000000004001a2c8  x13: 0xaaaaaaaaaaaaaaaa
E: x14: 0xaaaaaaaaaaaaaaaa  x15: 0x0000000000000000
E: x16: 0x0000000000000000  x17: 0x0000000000000000
E: x18: 0xaaaaaaaaaaaaaaaa  x30: 0x0000000040014b64
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 3
E: Current thread: 0x40027040 (THREAD_A)
E: Halting system

**Environment (please complete the following information):**
 - Ubuntu 20.04 x86 server 
 - Centos 8 armv8 server

### PR DESCRIPTION
**Pull request by carlocaione**
This PR follows the discussion at #40795 and is an ARM64-specific alternative to #41840

For details refer to that ticket and issue, but bottom line is that for ARM64 we do not set the `switch_handler` when exiting from `z_get_next_switch_handle()` but only in the context switching code when the context has been already fully saved to avoid races on multiple cores.

Fixes: #40795

### CODE REVIEW

**Comment by andyross** [comment]
This likely works fine, but as mentioned I'd still prefer that the real fix to be refactor the context switch code a bit so that you aren't trying to use what amounts to  arch_switch() at interrupt exit and can call z_get_next_switch_handle() at the correct time.  That wart is likely to cause other problems as the kernel evolves, the design intent is that that function is the kernel's "end of interrupt" hook.

File: arch/arm64/core/thread.c [hunk 1]
```diff
@@ -124,9 +124,25 @@ void arch_new_thread(struct k_thread *thread, k_thread_stack_t *stack,
...
+	/*
+	 * XXX: see thread in #41840 and #40795
+	 *
+	 * We pass NULL here to _not_ set the switch_handle for the old thread
+	 * at the end of the z_get_next_switch_handle() to avoid a race
+	 * condition with other cores waiting for that on wait_for_switch().
+	 * Instead we set the switch_handle _only_ in the
+	 * z_arm64_context_switch() code when we are 100% sure that the context
+	 * has been swapped out and the thread can be safely picked up by a
+	 * different core.
```
Comment (andyross) [inline arch/arm64/core/thread.c:143]: I think this would be more understandable if you explain this as an optimization on top of the expectations of the original API, something like:


```c
/* The scheduler API requires a complete switch handle here, but arm64
 * optimizes things such that the callee-save registers are still
 * unsaved here (they get written out in z_arm64_context_switch()
 * below).  So pass a NULL instead, which the scheduler will store
 * into the thread switch_handle field.  The resulting thread won't be
 * switched into until we write that ourselves.
 */
```

**Review by andyross — APPROVED** [review]

**Comment by npitre** [comment]
Might be a good idea to create a test with the reproducer.

Also you could consider this on top:

```
diff --git a/arch/arm64/core/isr_wrapper.S b/arch/arm64/core/isr_wrapper.S
index 3d4ee5c125..927cc87bd4 100644
--- a/arch/arm64/core/isr_wrapper.S
+++ b/arch/arm64/core/isr_wrapper.S
@@ -128,9 +128,6 @@ spurious_continue:
 #ifdef CONFIG_SMP
 	cmp	x0, #0x0
 	beq	restore
-#else
-	b	exit
-#endif
 
 	/* Switch thread */
 	bl	z_arm64_context_switch
@@ -142,6 +139,7 @@ restore:
 	 * z_arch_get_next_switch_handle()
 	 */
 	mov	x0, x1
+#endif
 
 exit:
 #ifdef CONFIG_STACK_SENTINEL
```

**Comment by carlocaione** [comment]
> Might be a good idea to create a test with the reproducer.

I'll open a different PR for that because this PR is already ACK-ed.

> Also you could consider this on top:

I had to slightly change the code to fix the `!SMP` case, so your suggestion is not applicable anymore.

**Comment by npitre** [comment]
> I had to slightly change the code to fix the `!SMP` case, so your
> suggestion is not applicable anymore.

The principle still is:

```
diff --git a/arch/arm64/core/isr_wrapper.S b/arch/arm64/core/isr_wrapper.S
index d92e9b85d8..63a1645db7 100644
--- a/arch/arm64/core/isr_wrapper.S
+++ b/arch/arm64/core/isr_wrapper.S
@@ -128,7 +128,15 @@ spurious_continue:
 	 *  - x0 == NULL: no context switch
 	 */
 	cmp	x0, #0x0
-	beq	restore
+	bne	skip
+
+	/*
+	 * Restore x0 from x1 (they are the same thread). See also comments to
+	 * z_arch_get_next_switch_handle()
+	 */
+	mov	x0, x1
+	b	exit
+skip:
 #else
 	cmp	x0, x1
 	beq	exit
@@ -136,14 +144,6 @@ spurious_continue:
 
 	/* Switch thread */
 	bl	z_arm64_context_switch
-	b	exit
-
-restore:
-	/*
-	 * Restore x0 from x1 (they are the same thread). See also comments to
-	 * z_arch_get_next_switch_handle()
-	 */
-	mov	x0, x1
 
 exit:
 #ifdef CONFIG_STACK_SENTINEL
```

**Comment by carlocaione** [comment]
> The principle still is:

alright. Changed that.

**Review by povergoing — APPROVED** [review]
I spend some time understanding the issue. So it is because the regs saving splits into 2 stages and the  `z_get_next_switch_handle ` is called in the middle and results in other CPU seeing and picking the current unfinished task(whose switch_handle is not NULL), right?

**Comment by carlocaione** [comment]
> I spend some time understanding the issue. So it is because the regs saving splits into 2 stages and the `z_get_next_switch_handle ` is called in the middle and results in other CPU seeing and picking the current unfinished task(whose switch_handle is not NULL), right?

Yes, correct.
