### PR TITLE
net: ip: Introduce mesh_local flag

### LINKED ISSUE #12203: openthread: bind IP is randomly selected causing off-mesh communication problems
**Describe the bug**
OpenThread generates quite a lot of unicast and multicast IP addresses for MeshLocal, default route, and other routable prefixes.  When it comes time for Zephyr to bind to a local IP for creating a connection to an external service, there just isn't enough logic to select the correct IP.
This results in communication problems when dealing with off-mesh services.

I can place a weight on local IPs that hacks Zephyr into picking the right bind IP.

**To Reproduce**
1. Need to build LwM2M client with an overlay which enables OpenThread (will upstream)
2. Configure OpenThread BorderRouter
3. Watch local IP bindings and communication issues

**Expected behavior**
Local OpenThread nodes should be able to select the correct local IP address to use for connections

**Impact**
Essentially OpenThread is unusable for practical communications until this issues is solved.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Zephyr SHA: 6410a16adbe84f89f78b8cb817c6d80819908b93

### PR DESCRIPTION
**Pull request by rlubos**
This PR introduces a concept of mesh-local address. Such addresses (used for instance by Thread) are fine to use for on-mesh communication, but should not be used when sending packets off-mesh.

Source address selection algorithm needs to distinguish between addresses that have mesh-local (or Realm-local in IPv6 nomenclature) scope and other addresses. As they all have form of ULA, it cannot be distinguished on the address format itself, which lead to erroneous source address assignment. Therfore, an additional flag was added to the `net_if_addr ` structure that can store this information.

Mesh-local addresses will only be used as a source address for destinations placed within the same subnet (mesh).

A sample interface configuration is shown below. Starred addresses were marked as `meshlocal`, therefore they'll only be selected for on-mesh communication.
```
Interface 0x200149a0 (<unknown type>) [0]
=========================================
Link addr : 16:0F:22:72:A6:90:22:3D
MTU       : 1280
IPv6 unicast addresses (max 8):
        *fdde:ad00:beef:0:1bc2:6311:f1e7:31a4 autoconf preferred infinite meshlocal
        fe80::28a6:a531:967d:9660 autoconf preferred infinite
        *fdde:ad00:beef::2 manual preferred infinite meshlocal
        fd5f:a074:3e6e:5:1aec:4f9f:9138:4d39 autoconf preferred infinite
        fdbe:387:ce8d:15:1797:25ec:a7e5:92a3 autoconf preferred infinite
        2a02:f78:1:315:1696:202:12d0:762c autoconf preferred infinite
        fd11:22::2554:c337:1897:ab6f autoconf preferred infinite
IPv6 multicast addresses (max 8):
        ff33:40:fdde:ad00:beef::1
        ff32:40:fdde:ad00:beef::1
        ff02::1
        ff03::1
        ff03::fc
        ff02::2
        ff03::2
IPv6 prefixes (max 2):
        <none>
IPv6 hop limit           : 64
IPv6 base reachable time : 30000
IPv6 reachable time      : 38475
IPv6 retransmit timer    : 0
```

Resolves #12203

### CODE REVIEW

**Comment by rlubos** [comment]
@mike-scott @aurel32 Note that though the concept remained similar in this solution, the implementation is slightly different to what you've tested yesterday. It'd be good if you could give it a try with your use-cases.

**Comment by tbursztyka** [comment]
@rlubos Do you have a reference in an RFC? Could be nice to add it in the commit message then.

**Comment by rlubos** [comment]
@tbursztyka Not exactly a RFC, the concept was more or less introduced by Thread, which differentiates between mesh-local addresses and global addresses (I'm not aware of RFC covering that). And the former ones should only be used within a mesh.

In Thread specification. ch. 5.2.2.5, we have:
```
Thread uses mesh-local addresses to reach Thread interfaces within the same Thread
Network Partition.
```
And later in ch. 9.2.4:
```
Communication using MLAs [Mesh Local Address] is not routable to the exterior of a Thread 
Network via a Border Router.
```

**Review by jukkar — COMMENTED** [review]
Overall looks good. Any idea why there is `*` char in front of the address as the shell is not printing those, or did you add them manually in this example?

```
 *fdde:ad00:beef:0:1bc2:6311:f1e7:31a4 autoconf preferred infinite meshlocal
 fe80::28a6:a531:967d:9660 autoconf preferred infinite
 *fdde:ad00:beef::2 manual preferred infinite meshlocal
```

**Comment by aurel32** [comment]
It seems the mesh-local addresses concept from Thread is a bit similar to the site-local addresses that was deprecated by RFC3879.

**Review by aurel32 — APPROVED** [review]
It looks good to me. I have tested it here on a OT network where I haven't attributed GUA addresses, and it works fine. I am able to use COAP with the nodes using the ML-EID addresses.

**Comment by rlubos** [comment]
@jukkar It was manual addition, sorry for confusion.

**Comment by aurel32** [comment]
@rlubos The IP range used for mesh-local addresses by Thread corresponds to the unique local address (ULA) range, as defined by RFC4193.

**Comment by rlubos** [comment]
@aurel32 Yes, you are right. The point is, the same IP range (ULA) is used in prefixes distributed by Border Routers (see unstarred unicast addresses in my example), and these prefixes (and therefore addresses created with them) are allowed to be used outside of the mesh (and to be honest that's why they are assigned). Hence we need more information to differentiate these.

**Review by jukkar — APPROVED** [review]

File: subsys/net/l2/openthread/openthread_utils.c [hunk 1]
```diff
@@ -94,9 +105,20 @@ void add_ipv6_addr_to_zephyr(struct openthread_context *context)
...
-		net_if_ipv6_addr_add(context->iface,
-				     (struct in6_addr *)(&address->mAddress),
-				     NET_ADDR_ANY, 0);
+		if_addr = net_if_ipv6_addr_add(
+					context->iface,
+					(struct in6_addr *)(&address->mAddress),
+					NET_ADDR_AUTOCONF, 0);
+
+		if (if_addr == NULL) {
+			NET_WARN("Not enough buffers to register OpenThread's"
```
Comment (pfalcon) [inline subsys/net/l2/openthread/openthread_utils.c]: Why "buffers"?

**Review by pfalcon — CHANGES_REQUESTED** [review]
First commit message has "addresss" (3 "s").

But most importantly, let's say again (in commit message I guess), what happens if we add NET_ADDR_MESH_LOCAL instead?

File: subsys/net/l2/openthread/openthread_utils.c (hunk 1 above)
Comment (pfalcon) [reply subsys/net/l2/openthread/openthread_utils.c]: And this is not NET_WARN I guess.

File: subsys/net/l2/openthread/openthread_utils.c [hunk 2]
```diff
@@ -94,9 +105,20 @@ void add_ipv6_addr_to_zephyr(struct openthread_context *context)
...
+				 " IP address. Increase "
+				 "CONFIG_NET_IF_UNICAST_IPV6_ADDR_COUNT");
```
Comment (pfalcon) [inline subsys/net/l2/openthread/openthread_utils.c]: And I absolutely love self-diagnosing software. But as other things I love, I also like to know limits on them. For example, I do it like this (explicitly hint user that by enabling some config var they can get more info) in the shell. But that's because shell is a debugging feature. Speaking of *error messages*, this one would be first of such nature. (So, do we need such a long error message?)

File: subsys/net/l2/openthread/openthread_utils.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/l2/openthread/openthread_utils.c]: > Why "buffers"?

Because of lack of better word for "IP address placeholder"

> And this is not NET_WARN I guess.

And what exactly is wrong with NET_WARN?

File: subsys/net/l2/openthread/openthread_utils.c (hunk 2 above)
Comment (rlubos) [reply subsys/net/l2/openthread/openthread_utils.c]: Sorry I don't follow this comment (beside of the last sentence).

File: subsys/net/l2/openthread/openthread_utils.c (hunk 1 above)
Comment (pfalcon) [reply subsys/net/l2/openthread/openthread_utils.c]: > Because of lack of better word for "IP address placeholder"

The right word would be "entry", but the whole message is problematic. That message is printed when net_if_ipv6_addr_add() returns NULL. Are you sure that the only condition when it does that is when there're no free addres entries? Are you sure it'll stay like that in the future? "Cannot add OpenThread <if possible, type> address" is the message which will never lie. (I'm all for more detailed error messages, as I said, but there're limits to it all.)

> And what exactly is wrong with NET_WARN?

Because it's *error*. Unless that address is not used for anything useful, and we add it just for fun ;-).

**Comment by rlubos** [comment]
> But most importantly, let's say again (in commit message I guess), what happens if we add NET_ADDR_MESH_LOCAL instead?

I'm not convinced about writing "what if" statements in commit message.

But to answer you question, I did not reuse `enum net_addr_type addr_type` field because it already stores different information (see starred addresses in the sample I posted, one is `autoconf` another one is `manual`). If we overwrite this field, we lose this info.

File: subsys/net/l2/openthread/openthread_utils.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/l2/openthread/openthread_utils.c]: Ok, I'll update this piece

**Comment by pfalcon** [comment]
> If we overwrite this field, we lose this info.

Ok, please add a short paragraph describing this situation to the commit message, so it can be found by someone who'll investigate it in the future.

**Comment by rlubos** [comment]
Updated the commit message and error message.

**Comment by mike-scott** [comment]
Sorry for the delay, the depreciation changes are making it semi- difficult to swap back and forth between dev trees and master at the moment.

I tested this today using https://github.com/zephyrproject-rtos/zephyr/pull/12781 
And found the fix to be quite nice:
```
IPv6 unicast addresses (max 6):
        fdde:ad00:beef:0:531:74ba:b057:ef7d autoconf preferred infinite meshlocal
        fe80::e7:f30e:3f3e:901e autoconf preferred infinite
        fd11:22::262:b438:3091:e604 autoconf preferred infinite
```

Works great, thanks @rlubos

**Review by mike-scott — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]
Thanks!

**Comment by mike-scott** [comment]
I'm not sure if the test_select sanity failure is due to this commit.  Might want to re-run.
