### PR TITLE
Bluetooth: GATT: Fix discover callback invalid pointer

### LINKED ISSUE #21186: Gatt discover callback gives invalid pointer to primary and secondary service UUID.
**Describe the bug**
Two issues related to using the UUID_DECLARE and then assigning a pointer that has a different scope that the declared variable.

1. The discovery callback giving a pointer to a variable that has been
declared in a scope that is no longer valid. This causes undefined
behavior as the memory pointed to can get corrupt at any time.

2. Giving an invalid pointer during gatt_find_type sending which
will lead to sending invalid data during discovery procedure.

These issues seems to have been hidden until trying out
gcc-arm-none-eabi-9-2019-q4-major

**To Reproduce**
1. Install GCC 9 2019-q4-major
2. Connect central_hr sample together with peripheral sample.

**Impact**
Undefined behaviour during GATT Discovery procedure.

**Screenshots or console output**
```
[00:00:00.010,162] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.010,162] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
[00:00:00.010,162] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.1 Build 0
[00:00:00.010,742] <inf> bt_hci_core: Identity: cd:48:4a:4c:78:af (random)
[00:00:00.010,772] <inf> bt_hci_core: HCI: version 5.1 (0x0a) revision 0x0000, manufacturer 0x05f1
[00:00:00.010,772] <inf> bt_hci_core: LMP: version 5.1 (0x0a) subver 0xffff
Connected 5f:ea:c6:56:60:2c (random)
The discovery procedure failed, err -12
[00:00:02.762,725] <err> bt_gatt_dm: Unsupported UUID type.
[00:00:02.762,756] <err> bt_gatt_dm: Not enough memory for service attribute data.
```

With provided fix:
```
[00:00:00.010,101] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.010,101] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
[00:00:00.010,131] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.1 Build 0
[00:00:00.010,711] <inf> bt_hci_core: Identity: cd:48:4a:4c:78:af (random)
[00:00:00.010,711] <inf> bt_hci_core: HCI: version 5.1 (0x0a) revision 0x0000, manufacturer 0x05f1
[00:00:00.010,711] <inf> bt_hci_core: LMP: version 5.1 (0x0a) subver 0xffff
Connected 5f:ea:c6:56:60:2c (random)
Found service 1801
Attribute count: 3
ATT[1]:         UUID: 0x2803    Handle: 0x0002  Value:
        Characteristic: 0x2a05  Properties: 0x0020
ATT[2]:         UUID: 0x2a05    Handle: 0x0003  Value:
```

Commit: 240d519de369f83529fcadc21f07af69e9f703fd

### PR DESCRIPTION
**Pull request by joerchan**
Fix the discovery callback giving a pointer to a variable that has been
declared in a scope that is no longer valid. This causes undefined
behavior as the memory pointed to can get corrupt at any time.
This issue seems to have been hidden until trying out
gcc-arm-none-eabi-9-2019-q4-major.

Fixes: #21186

### CODE REVIEW

**Comment by joerchan** [comment]
@cvinayak Please check if the issue you saw with GCC9 is the same as this one. This is a different report but both of the issues are provoked by switching compiler version.

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -2744,14 +2745,17 @@ static u16_t parse_service(struct bt_conn *conn, const void *pdu,
...
 		} else {
-			attr.uuid = BT_UUID_GATT_SECONDARY;
+			memcpy(&uuid_svc, BT_UUID_GATT_SECONDARY,
+			       sizeof(uuid_svc));
 		}
 
 		value.end_handle = end_handle;
 		value.uuid = &u.uuid;
 
+		attr.uuid = (struct bt_uuid *)&uuid_svc;
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: `attr.uuid = &uuid_srv.uuid;` might be a bit cleaner since it avoids the typecast

**Review by jhedberg — APPROVED** [review]
Looks fine to me, except for the minor style thing I pointed out

**Comment by rakons** [comment]
Please note that there may be general problem with BT_UUID_DECLARE_16 (_32 and _128) that would make this macros unusable in GCC 9.

**Comment by cvinayak** [comment]
There are other such changes required, example, in gatt_find_type, as my original issue was with central_hr sending garbage UUID during discover that failed. Hope this PR scans for all such use in host and fixes them together.

**Comment by joerchan** [comment]
> Please note that there may be general problem with BT_UUID_DECLARE_16 (_32 and _128) that would make this macros unusable in GCC 9.

Can you explain? I don't think they are unusable, but they need to be used correctly.

**Comment by joerchan** [comment]
@jhedberg Could you give it another look. Since I included the other issue that vinayak reported. Which is the same issue in a different place.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -2314,6 +2314,7 @@ static void gatt_find_type_rsp(struct bt_conn *conn, u8_t err,
 	     i++, length -=  sizeof(rsp->list[i])) {
 		struct bt_gatt_attr attr = {};
 		struct bt_gatt_service_val value;
+		struct bt_uuid_16 uuid_svc;
```
Comment (cvinayak) [inline subsys/bluetooth/host/gatt.c]: nitpick, do we still follow reverse Christmas tree declaration coding style?

**Comment by rakons** [comment]
> 
> 
> > Please note that there may be general problem with BT_UUID_DECLARE_16 (_32 and _128) that would make this macros unusable in GCC 9.
> 
> Can you explain? I don't think they are unusable, but they need to be used correctly.

What is the correct use of this macro? Here we was trying to set a structure member using the value returned by the macro and call a function with it - it failed. Where you can use it if GCC 9 optimises a structure created in such a way?

**Comment by joerchan** [comment]
> > > Please note that there may be general problem with BT_UUID_DECLARE_16 (_32 and _128) that would make this macros unusable in GCC 9.
> > 
> > 
> > Can you explain? I don't think they are unusable, but they need to be used correctly.
> 
> What is the correct use of this macro? Here we was trying to set a structure member using the value returned by the macro and call a function with it - it failed. Where you can use it if GCC 9 optimises a structure created in such a way?

It's not what happened. Basically we had code that looked like this:
```

struct bt_uuid *uuid;

if (params->type == BT_GATT_DISCOVER_PRIMARY) {
	struct bt_uuid_16 uuid_svc;

	uuid_svc.val = 0x1234;
	uuid = &uuid_svc;
} else {
	struct bt_uuid_16 uuid_svc;

	uuid_svc.val = 0x4321;
	uuid = &uuid_svc;
}

callback(uuid);
```
This is invalid code, and what the compiler does with this undefined. In this case I guess the compiler thought it didn't need to have this code, because it makes no sense.

**Review by cvinayak — CHANGES_REQUESTED** [review]

**Comment by joerchan** [comment]
@cvinayak I did a check, and found 3 more.

File: subsys/bluetooth/host/gatt.c [hunk 3]
```diff
@@ -2322,14 +2323,17 @@ static void gatt_find_type_rsp(struct bt_conn *conn, u8_t err,
 		       end_handle);
 
 		if (params->type == BT_GATT_DISCOVER_PRIMARY) {
-			attr.uuid = BT_UUID_GATT_PRIMARY;
+			memcpy(&uuid_svc, BT_UUID_GATT_PRIMARY,
```
Comment (rakons) [inline subsys/bluetooth/host/gatt.c]: I am just not sure if this is optimal way to do it - we are creating object in RAM, initializing it, and after that copying data using memcpy... and then the object is not valid any more. Technically it is correct, but we can optimise it:
```
uuid_svc.uuid.type = BT_UUID_TYPE_16;
if (params->type == BT_GATT_DISCOVER_PRIMARY) {
    uuid_svc.val = BT_UUID_16(BT_UUID_GATT_PRIMARY)->val;
} else {
    uuid_svc.val = BT_UUID_16(BT_UUID_GATT_SECONDARY)->val
}
```

With a hope that compiler would optimise ```BT_UUID_16(BT_UUID_GATT_PRIMARY)->val``` to one constant.

**Review by rakons — APPROVED** [review]
Generally ok. But I would rather prefer to optimise out the ```memcpy``` functions like described in the comments.

**Comment by rakons** [comment]
@joerchan - Exactly like you say. Thanks for the detailed description - I just got it a moment after I have written the previous comment :)

File: subsys/bluetooth/host/gatt.c (hunk 3 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c]: Thanks. Update to this. I agree a memcpy on 2 bytes is a bit much

**Review by cvinayak — APPROVED** [review]
aside the nitpick, functionally solves the issue when compiling using gcc9

File: subsys/bluetooth/host/gatt.c (hunk 2 above)
Comment (carlescufi) [reply subsys/bluetooth/host/gatt.c]: We do, would be good if @joerchan placed this at the top.

File: subsys/bluetooth/host/gatt.c (hunk 3 above)
Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: > With a hope that compiler would optimise BT_UUID_16(BT_UUID_GATT_PRIMARY)->val to one constant.

I realise we can't do it for the release, but the need for this kind of indirection is indicative of a suboptimal or incomplete API definition. We should probably have defines for the literal integers values so we can use them directly. Any chance someone could check that the compiler really does optimize the short-term solution and that we're not left with an extra 3-byte struct and a pointer to that struct, just to get the value stored in 2 bytes of the struct?

Comment (rakons) [reply subsys/bluetooth/host/gatt.c]: It looks good (with size optimisation):
```
		if (params->type == BT_GATT_DISCOVER_PRIMARY) {
   19bd0:	f896 3028 	ldrb.w	r3, [r6, #40]	; 0x28
		end_handle = sys_le16_to_cpu(rsp->list[i].end_handle);
   19bd4:	f8b1 9002 	ldrh.w	r9, [r1, #2]
		attr.handle = start_handle;
   19bd8:	f8ad 201c 	strh.w	r2, [sp, #28]
			uuid_svc.val = BT_UUID_16(BT_UUID_GATT_SECONDARY)->val;
   19bdc:	2b00      	cmp	r3, #0
   19bde:	f642 0301 	movw	r3, #10241	; 0x2801
   19be2:	bf08      	it	eq
   19be4:	f44f 5320 	moveq.w	r3, #10240	; 0x2800
   19be8:	f8ad 3002 	strh.w	r3, [sp, #2]
```

You can see at 19bde and 19be4 that simple constant values are used.

Comment (joerchan) [reply subsys/bluetooth/host/gatt.c]: @rakons Thank you for that analysis.

@jhedberg I thought about adding defines for the UUID values. There is a lot of them though.
But with those values I could have used `BT_UUID_INIT_16` instead. I think we could atleast have for the most standard ones, like characterstic and service. But didn't want to do it for this fix.

File: subsys/bluetooth/host/gatt.c (hunk 2 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c]: Done.

**Review by carlescufi — APPROVED** [review]

**Comment by ioannisg** [comment]
Changing milestone to 2.2.
Note: we might need to merge it to 2.1 if we need Medium priority bugs to drop below 20
