### PR TITLE
LE Audio: Receiver start fix

### LINKED ISSUE #50777: LE Audio: Receiver start ready command shall only be sent by the receiver
**Describe the bug**
The ASCS Receiver start ready opcode, trigger by `bt_audio_stream_start`, shall only be sent by the receiver, i.e. the client for source endpoints, and the server for sink endpoints. Furthermore, this should not sent automatically by the ASCS implementation as it is currently, but should be done by the upper layers when they are in fact, ready. 

**To Reproduce**
N/A

**Expected behavior**
The the API will reject requests to start an endpoint that is not sending to the device sending the opcode. 

**Impact**
Minor spec violation possible

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: a5ce3da6ab425d104d73d34f47352ae721c5d216

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Modifies how and when the ASE on the unicast server side transitions to the streaming state. 

Depends on https://github.com/zephyrproject-rtos/zephyr/pull/50822
fixes https://github.com/zephyrproject-rtos/zephyr/issues/50777

Reverts some changes done by https://github.com/zephyrproject-rtos/zephyr/pull/51027

### CODE REVIEW

**Comment by Thalley** [comment]
Ping @szymon-czapracki

**Comment by MariuszSkamra** [comment]
@szymon-czapracki could you please take a look at this one as it seems to be related to the issue you've discovered

**Comment by Thalley** [comment]
Rebased on https://github.com/zephyrproject-rtos/zephyr/pull/51897

File: include/zephyr/bluetooth/audio/audio.h [hunk 1]
```diff
@@ -1872,6 +1872,14 @@ int bt_audio_stream_disable(struct bt_audio_stream *stream);
...
  *  stream start streaming.
  *
+ *  For the unicast client, this will connect the CIS for the stream before
+ *  sending the start command.
+ *
+ *  For the unicast server, this will put the stream into the streaming state if
+ *  the CIS is connected (initialized by the unicast client). If the CIS is not
+ *  connected yet, the stream will go into the streaming state as soon as the
+ *  CIS is connected.
+ *
```
Comment (MariuszSkamra) [inline include/zephyr/bluetooth/audio/audio.h:1882]: I'm not sure we need go into implementation details here. What do you think?

Comment (Thalley) [reply include/zephyr/bluetooth/audio/audio.h:1882]: Hmm, maybe not, since the ISO state is not known to the caller anyhow. 

What I wanted to capture here is that for the unicast client, you can assume that the stream will go into streaming state shortly after (as we are initiating the CIS connection), but for the unicast server, the state change to streaming will depend on when the remote side connects the CIS. 

Since the caller does not know the CIS state, it cannot possible know if this will put the stream into the streaming state immediately (if CIS is connected), or later (if CIS is not connected).

File: samples/bluetooth/unicast_audio_server/src/main.c [hunk 2]
```diff
@@ -514,13 +543,29 @@ static void stream_stopped(struct bt_audio_stream *stream)
...
+	 * client has enabled them.
+	 */
+	if (stream_dir(stream) == BT_AUDIO_DIR_SINK) {
+		const int err = bt_audio_stream_start(stream);
+
+		if (err != 0) {
+			printk("Failed to start stream %p: %d", stream, err);
+		}
+	}
+}
```
Comment (MariuszSkamra) [inline samples/bluetooth/unicast_audio_server/src/main.c:559]: Why `bt_audio_stream_start` is called for SINK only? The API says:

```
 *  For the unicast server, this will put the stream into the streaming state if
 *  the CIS is connected (initialized by the unicast client). If the CIS is not
 *  connected yet, the stream will go into the streaming state as soon as the
 *  CIS is connected.
```

In other words I would expect `bt_audio_stream_start` will put the stream in streaming state, where both streams SINK and SOURCE need to be handled the same way from API point of view.

It's a detail that in case of SINK and SOURCE this method will be handled differently internally:
SINK:
* Wait for CIS to be connected if not yet
* Notify ASE state: Streaming
* Call stream->started()

SOURCE:
* Wait for CIS to be connected if not yet
* Wait for ASE control operation: Receiver Start Ready
* Notify ASE state: Streaming
* Call stream->started()

Comment (Thalley) [reply samples/bluetooth/unicast_audio_server/src/main.c:559]: We could have similar behavior for sink and source ASEs for `bt_audio_stream_start`, but my thought here would be that `bt_audio_stream_start` is a wrapper for the receiver start ready operation, which can only be done on sink ASEs on the server, and similarly only for source ASEs on the client (as per the ASCS spec). 

I agree that the documentation of the function is incorrect in this regard, and should be updated.

Comment (Thalley) [reply samples/bluetooth/unicast_audio_server/src/main.c:559]: Updated the documentation a bit :)

**Review by kruithofa — APPROVED** [review]

File: subsys/bluetooth/audio/ascs.c [hunk 3]
```diff
@@ -567,50 +567,28 @@ static void ascs_iso_sent(struct bt_iso_chan *chan)
...
 
-	err = ase_stream_start(stream);
-	if (err) {
-		LOG_ERR("Could not start stream %d", err);
+	if (ep->dir == BT_AUDIO_DIR_SINK && ep->receiver_ready) {
+		/* Source ASEs shall be ISO connected first, and then receive
+		 * the receiver start ready command to enter the streaming
+		 * state
+		 */
+		ascs_ep_set_state(ep, BT_AUDIO_EP_STATE_STREAMING);
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/audio/ascs.c:591]: We are not removing them, it has just been moved to `ase_start`.

**Review by fredrikdanebjer — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]
