### PR TITLE
drivers/counter nrfx: Fix with DT instance not matching device instance

### LINKED ISSUE #69216: driver: Timer / Counter initialization incorrect for timer2 with BLE on nRF52840
**Describe the bug**
An initialization value is incorrect if timer2 is enabled (and used in counter mode) with BLE (where timer0 and timer1 are disabled) on nRF52840.

Please also mention any information which could help others to understand
the problem you're facing:
 - `drivers/counter/counter_nrfx_timer.c` uses a Nordic HAL value to initialize `.timer`.
This is out-of-sync with devicetree information as timer0 and timer1 are disabled but
timer2 is enabled because:
[devicetree](https://docs.zephyrproject.org/latest/build/dts/api/api.html#c.DT_INST)
implies that devicetree starts indexing instances from 0 based on enabled devices, and then indexes disabled devices. So, devicetree index for timer2 (0) and HAL index for timer2 (2) differ.

 - see: commit 9a27906e38343b07cbdf1b4aca5451c5886dbd41

**To Reproduce**
1. Use `samples/bluetooth/broadcaster`
2. Add following to `prj.conf `
```
CONFIG_COUNTER=y
CONFIG_NRFX_TIMER2=y
```
3. Create `boards/nrf52840dk_nrf52840.overlay` with:
```
&timer2 {
  status = "okay";
};
```
4. Build and run on nRF52840DK
5. Check value of `reg` in `init_timer`. It is 0x40008000 and should be 0x4000a000

**Expected behavior**
timer2 should operate correctly as a counter.

**Impact**
Very low priority (workaround is to revert commit above).

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: zephyr-sdk-0.16.5
 - Commit SHA or Version used: 5c455aae88d14a527bdd438adf9da4958d52c17b

### PR DESCRIPTION
**Pull request by aescolar**
478530ec0aa1fe5f481786c25d50f7a081b22208 introduced a bug where if the DT index while iterating its DT structure initialization does not match the actual peripheral instance, or if the device instance string is not just a simple integer, but a more complex string like "00", or "02", either the wrong peripheral address would be used, or the file would failt to compile.

Let's fix this by reverting that change, and instead, for simulation converting the hardcoded DT/real HW address to the valid addr for simulation on the fly.

Fixes #69216

### CODE REVIEW

File: drivers/counter/counter_nrfx_timer.c [hunk 1]
```diff
@@ -283,7 +283,14 @@ static uint32_t get_pending_int(const struct device *dev)
 static int init_timer(const struct device *dev,
 		      const struct counter_timer_config *config)
 {
-	const struct counter_nrfx_config *nrfx_config = dev->config;
+	struct counter_nrfx_config *nrfx_config = (struct counter_nrfx_config *) dev->config;
+
+#if defined(CONFIG_SOC_SERIES_BSIM_NRFXX)
+	/* For simulated devices we need to convert the hardcoded DT address from the real
+	 * peripheral into the correct one for simulation */
+	nrfx_config->timer = nhw_get_periph_base_addr(nrfx_config->timer);
```
Comment (gmarull) [inline drivers/counter/counter_nrfx_timer.c:291]: since timer can be now mutated, shouldn't it be placed in data?

File: drivers/counter/counter_nrfx_timer.c [hunk 2]
```diff
@@ -283,7 +283,14 @@ static uint32_t get_pending_int(const struct device *dev)
 static int init_timer(const struct device *dev,
 		      const struct counter_timer_config *config)
 {
-	const struct counter_nrfx_config *nrfx_config = dev->config;
+	struct counter_nrfx_config *nrfx_config = (struct counter_nrfx_config *) dev->config;
```
Comment (gmarull) [inline drivers/counter/counter_nrfx_timer.c:286]: cast should be conditioned to simulation, otherwise config is not mutable.

Overall I do not see any problems with these changes, but abusing config for potentially mutable data doesn't feel right, so I'd discuss this in the near future before it propagates to other drivers.

File: drivers/counter/counter_nrfx_timer.c (hunk 1 above)
Comment (aescolar) [reply drivers/counter/counter_nrfx_timer.c]: Updated as agreed on offline discussion

**Review by gmarull — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

**Review by nordic-krch — DISMISSED** [review]

**Review by nordic-krch — APPROVED** [review]

**Review by anangl — APPROVED** [review]
