### PR TITLE
Bluetooth: Audio: CSIP set member register fix

### LINKED ISSUE #55457: LE Audio: CSIP not disabling option characteristics for size and rank
**Describe the bug**
The documentation for `struct bt_csip_set_member_register_param` states that if `rank` or `set_size` is 0, then the (optional) characteristics are not initialized. However, the implementation of `bt_csip_set_member_register` ensures not such thing. 

**To Reproduce**
N/A

**Expected behavior**
That the implementation of `bt_csip_set_member_register` ensures that the set size and rank characteristics are not registered for the instances where rank and size parameters are `0`. 

**Impact**
Annoyance

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 29cc07efbd71b779d584a30fb495b4a3de6e0e91

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Fixes a bug with the CSIP set member register. Fixing this issue and adding tests for it, also found a few other issues that were found and fixed in order to get the tests parsing. 

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/55457

### CODE REVIEW

File: subsys/bluetooth/audio/csip_set_coordinator.c [hunk 1]
```diff
@@ -842,12 +847,15 @@ static uint8_t csip_set_coordinator_discover_insts_read_rank_cb(struct bt_conn *
...
+
 		LOG_HEXDUMP_DBG(data, length, "Data read");
 
-		if (length == 1) {
-			(void)memcpy(&client->svc_insts[cur_inst->idx].rank,
-				     data, length);
-			LOG_DBG("%u", client->svc_insts[cur_inst->idx].rank);
+		set_info = &client->set_member.insts[cur_inst->idx].info;
+
+		if (length == sizeof(set_info->set_size)) {
```
Comment (fredrikdanebjer) [inline subsys/bluetooth/audio/csip_set_coordinator.c:856]: sizeof(set_info->rank)) ?

File: subsys/bluetooth/audio/csip_set_member.c [hunk 2]
```diff
@@ -697,6 +700,50 @@ static bool valid_register_param(const struct bt_csip_set_member_register_param
...
+			 * characteristic or not
+			 */
+			if (i == (svc->attr_count - (attrs_to_rem - 1))) {
+				/* This is the last characteristic in the service: just decrement
+				 * the attr_count by number of attributes to remove
+				 * (CSIS_CHAR_ATTR_COUNT)
+				 */
+			} else {
+				/* Move all following attributes 3 locations "up" */
+				for (size_t j = i - 1U; j < svc->attr_count - attrs_to_rem; j++) {
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/audio/csip_set_member.c:733]: My comment may be unclear :D 

For the sake of the argument, let's assume that we just have an array of services and characteristics like
```
[0] = Primary service
[1] = Characteristic A
[2] = Characteristic B
[3] = Characteristic C
[4] = Characteristic D
```

And we want to remove `Characteristic B`. 
What this does, is to move everything from (and including) `Characteristic C` up, so this becomes

```
[0] = Primary service
[1] = Characteristic A
[2] = Characteristic C
[3] = Characteristic D
```

Technically `[4]` is also `Characteristic D`, but since we decrement the `attr_count`, it can ignored. 

The term "up" may be confusing, and perhaps we should say something like "reduce the index of" or similar. 

The changes done here would also have been much simpler if the GATT API used a a linked list for the attributes :D

[the remark this answers is not in the document]
Comment (fredrikdanebjer) [reply subsys/bluetooth/audio/csip_set_member.c:733]: It's my bad, I see how I read it wrong now, lgtm

File: subsys/bluetooth/audio/csip_set_member.c [hunk 3]
```diff
@@ -722,8 +771,28 @@ int bt_csip_set_member_register(const struct bt_csip_set_member_register_param *
...
+		remove_csis_char(BT_UUID_CSIS_RANK, inst->service_p);
+	}
+
+	if (param->set_size == 0U) {
+		remove_csis_char(BT_UUID_CSIS_SET_SIZE, inst->service_p);
+	}
+
+	if (!param->lockable) {
+		remove_csis_char(BT_UUID_CSIS_SET_LOCK, inst->service_p);
+	}
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/csip_set_member.c:795]: Wouldn't it be easier and cleaner to do the opposite? I mean to compose the service attributes based on parameters given?
Luckily, there is no `bt_csip_set_member_unregister` method, because, currently, this does not restore the `csip_set_member_service_list` initial state.

**Review by MariuszSkamra — COMMENTED** [review]
One minor comment, otherwise looks good to me

File: subsys/bluetooth/audio/csip_set_member.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/audio/csip_set_member.c:795]: That's a good point, but the reason why it is done this way, is that the list of CSIS instances are declared using `BT_GATT_SERVICE_INSTANCE_DEFINE`. 

We could modify `BT_CSIP_SERVICE_DEFINITION` to have these 3 characteristics as empty by default and then populate them when requested. That might indeed by the cleaner solution, even if takes a bit more effort :) 

Let me know if that makes sense to you

**Review by szymon-czapracki — DISMISSED** [review]

File: subsys/bluetooth/audio/csip_set_coordinator.c [hunk 4]
```diff
@@ -1527,19 +1527,34 @@ static int bt_csip_set_coordinator_get_lock_state(
...
+		active.members_handled++;
 	}
 
-	err = csip_set_coordinator_read_set_lock(cur_inst);
-	if (err == 0) {
-		busy = true;
-	} else {
-		cur_inst = NULL;
+	if (!busy && err == 0) {
+		/* Not lock states are being read, can just call the ordered access callback
```
Comment (fredrikdanebjer) [inline subsys/bluetooth/audio/csip_set_coordinator.c:1554]: This comment is not clear to me, possibly there is a typo in it?

File: subsys/bluetooth/audio/csip_set_member.c [hunk 5]
```diff
@@ -681,7 +684,7 @@ static bool valid_register_param(const struct bt_csip_set_member_register_param
 		return false;
 	}
 
-	if (param->rank > 0 && param->rank > param->set_size) {
+	if (param->rank > 0 && param->set_size > 0 && param->rank > param->set_size) {
 		LOG_DBG("Invalid rank: %u (shall be less than set_size: %u)", param->set_size,
```
Comment (larsgk) [inline subsys/bluetooth/audio/csip_set_member.c:688]: first arg should be param->rank and should it be 'less than' or 'less than or equal', which seems to be what the test checks for

**Review by fredrikdanebjer — APPROVED** [review]

**Review by szymon-czapracki — APPROVED** [review]
