### PR TITLE
soc: stm32: Fix DBGMCU register write for SWO configuration

### LINKED ISSUE #44584: SWO log output does not compile for STM32WB55
Building Zephyr with SWO log output for STM32WB55 target enabled fails due to the missing definition.

For example, hello_world sample fails with:
`west build -b nucleo_wb55rg samples/hello_world -DCONFIG_LOG=y -DCONFIG_LOG_PRINTK=y -DCONFIG_LOG_BACKEND_SWO=y`

```
/home/alex/zephyr-upstream/zephyr/soc/arm/st_stm32/common/soc_config.c: In function 'st_stm32_common_config':
/home/alex/zephyr-upstream/zephyr/soc/arm/st_stm32/common/soc_config.c:30:17: error: 'DBGMCU_CR_TRACE_MODE_Msk' undeclared (first use in this function); did you mean 'DBGMCU_CR_TRACE_IOEN_Msk'?
   30 |  DBGMCU->CR &= ~DBGMCU_CR_TRACE_MODE_Msk;
```

This happens because for some STM32 MCUs DBGMCU register does not have TRACE_MODE bits, which are responsible for Asynchronous/Synchronous trace mode selection.  For them it is enough to only set DBGMCU_CR_TRACE_IOEN bit.

The issue can be fixed with the following amendment to `soc/arm/st_stm32/common/soc_config.c`:
```
#ifdef CONFIG_LOG_BACKEND_SWO
#if defined(DBGMCU_CR_TRACE_MODE)
	/* TRACE pin assignment for asynchronous mode */
	DBGMCU->CR &= ~DBGMCU_CR_TRACE_MODE_Msk;
#endif
	/* Enable the SWO pin */
	DBGMCU->CR |= DBGMCU_CR_TRACE_IOEN;
#endif
```
Tested on nucleo_wb55rg board.

### PR DESCRIPTION
**Pull request by amvasil-v**
DBGMCU register, which is used for SWO pin configuration,
may not have TRACE_MODE bits in some STM32 MCUs.
Remove unnecessary clear for these MCUs.

Fixes #44584

Signed-off-by: Alexander Vasiliev <alex.m.vasil@gmail.com>

### CODE REVIEW

**Review by erwango — DISMISSED** [review]
Thanks for this fix!

File: soc/arm/st_stm32/common/soc_config.c [hunk 1]
```diff
@@ -26,8 +26,10 @@
 static int st_stm32_common_config(const struct device *dev)
 {
 #ifdef CONFIG_LOG_BACKEND_SWO
+#if defined(DBGMCU_CR_TRACE_MODE)
 	/* TRACE pin assignment for asynchronous mode */
 	DBGMCU->CR &= ~DBGMCU_CR_TRACE_MODE_Msk;
+#endif
 	/* Enable the SWO pin */
 	DBGMCU->CR |= DBGMCU_CR_TRACE_IOEN;
```
Comment (FRASTM) [inline soc/arm/st_stm32/common/soc_config.c:34]: should TRACE_IOEN be set first or at the same time than TRACE_MODE=00
liek the `LL_DBGMCU_SetTracePinAssignment` function does
if TRACE_IOEN=0 when writing DBGMCU->CR &= ~DBGMCU_CR_TRACE_MODE_Msk; then TRACE_MODE=xx: TRACE pins not assigned --> useless
Only With TRACE_IOEN=1 is the TRACE_MODE written

Comment (amvasil-v) [reply soc/arm/st_stm32/common/soc_config.c:34]: Maybe better to rewrite it using LL and explicitly mention SoC family:
```
#ifdef CONFIG_LOG_BACKEND_SWO
	/* Enable SWO trace asynchronous mode */
#if defined(CONFIG_SOC_SERIES_STM32WBX)
	LL_DBGMCU_EnableTraceClock();
#else
	LL_DBGMCU_SetTracePinAssignment(LL_DBGMCU_TRACE_ASYNCH);
#endif
#endif /* CONFIG_LOG_BACKEND_SWO */
```

Other series like H7 and L5 may have different enable procedure, but it looks like SWO is not supported for them by Zephyr by now.

**Review by FRASTM — APPROVED** [review]

**Review by erwango — APPROVED** [review]

File: soc/arm/st_stm32/common/soc_config.c [hunk 2]
```diff
@@ -26,11 +26,13 @@
 static int st_stm32_common_config(const struct device *dev)
 {
 #ifdef CONFIG_LOG_BACKEND_SWO
-	/* TRACE pin assignment for asynchronous mode */
-	DBGMCU->CR &= ~DBGMCU_CR_TRACE_MODE_Msk;
-	/* Enable the SWO pin */
-	DBGMCU->CR |= DBGMCU_CR_TRACE_IOEN;
+	/* Enable SWO trace asynchronous mode */
+#if defined(CONFIG_SOC_SERIES_STM32WBX)
+	LL_DBGMCU_EnableTraceClock();
```
Comment (erwango) [inline soc/arm/st_stm32/common/soc_config.c:31]: Open question:
I don't know much on this part, but this functions is also defined on U5 and L5, as well as `LL_DBGMCU_SetTracePinAssignment`.
So for these 2 series, is `LL_DBGMCU_SetTracePinAssignment()` a better choice than `LL_DBGMCU_EnableTraceClock(LL_DBGMCU_TRACE_ASYNCH)`?
