### PR TITLE
Bluetooth: Fix deadlock issues when running low on buffers

### LINKED ISSUE #16864: Bluetooth: Mesh: Rx buffer exhaustion causes deadlock
In the Bluetooth Mesh environment, the following conditions caused a deadlock:
1. Advertising data reporting causes the Rx buffer to be exhausted
2. The Mesh protocol stack invoke the ACL to send data. It blocks the RX thread because it waits for the ACL numCompleted event.
3. The HCI driver cannot report the numCompleted event because the Rx buffer is exhausted, and the Rx thread cannot release the Rx buffer because it is blocked.

rx_thread call stack:
#0  __swap (key=0, key@entry=16965509) at /home/ubuntu/zephyr/arch/arm/core/swap.c:68
#1  z_swap_irqlock (key=16965509) at /home/ubuntu/zephyr/kernel/include/kswap.h:128
#2  z_swap (key=..., lock=0x2000346c <k_sys_work_q>) at /home/ubuntu/zephyr/kernel/include/kswap.h:145
#3  z_pend_curr (lock=lock@entry=0x2000346c <k_sys_work_q>, key=..., key@entry=..., wait_q=wait_q@entry=0x0, timeout=timeout@entry=-1) at /home/ubuntu/zephyr/kernel/sched.c:448
#4  z_impl_k_sem_take (sem=sem@entry=0x0, timeout=timeout@entry=-1) at /home/ubuntu/zephyr/kernel/sem.c:160
#5  k_sem_take (timeout=-1, sem=0x0) at /home/ubuntu/zephyr/samples/bluetooth/mesh_test_platform/build/xxxx/zephyr/include/generated/syscalls/kernel.h:103
#6  bt_att_send (conn=0x0, conn@entry=0x20000ae4 <conns>, buf=buf@entry=0x200083a8 <net_buf_acl_tx_pool+48>,  cb=cb@entry=0x0) at /home/ubuntu/zephyr/subsys/bluetooth/host/att.c:2222
#7  gatt_notify (conn=conn@entry=0x20000ae4 <conns>, handle=<optimized out>, data=0x0, data@entry=0x20004980 <rx_thread_stack+3120>, len=len@entry=28, cb=cb@entry=0x0) at /home/ubuntu/zephyr/subsys/bluetooth/host/gatt.c:1167
#8  bt_gatt_notify_cb (conn=conn@entry=0x20000ae4 <conns>, attr=0x20009320 <proxy_attrs+80>,  attr@entry=0x2000930c <proxy_attrs+60>, data=0x20004980 <rx_thread_stack+3120>, len=<optimized out>, func=func@entry=0x0) at /home/ubuntu/zephyr/subsys/bluetooth/host/gatt.c:1379
#9  bt_gatt_notify (len=<optimized out>, data=<optimized out>, attr=0x2000930c <proxy_attrs+60>, conn=0x20000ae4 <conns>) at /home/ubuntu/zephyr/include/bluetooth/gatt.h:759
#10 proxy_send (conn=conn@entry=0x20000ae4 <conns>, data=<optimized out>, len=<optimized out>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/proxy.c:893
#11 proxy_segment_and_send (conn=conn@entry=0x20000ae4 <conns>, type=type@entry=0 '\000', msg=msg@entry=0x20004974 <rx_thread_stack+3108>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/proxy.c:918
#12 bt_mesh_proxy_send (conn=0x20000ae4 <conns>, type=type@entry=0 '\000', msg=msg@entry=0x20004974 <rx_thread_stack+3108>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/proxy.c:955
#13 bt_mesh_proxy_relay (buf=buf@entry=0x200086b4 <net_buf_adv_buf_pool+56>, dst=<optimized out>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/proxy.c:878
#14 bt_mesh_net_send (tx=tx@entry=0x20004a64 <rx_thread_stack+3348>, buf=buf@entry=0x200086ac <net_buf_adv_buf_pool+48>, cb=0x1030210 <seg_sent_cb>, cb_data=cb_data@entry=0x200001d8 <seg_tx>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/net.c:885
#15 send_seg (net_tx=net_tx@entry=0x20004a64 <rx_thread_stack+3348>, sdu=sdu@entry=0x20004a90 <rx_thread_stack+3392>, cb=cb@entry=0x0, cb_data=cb_data@entry=0x0) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/transport.c:411
#16 bt_mesh_trans_send (tx=tx@entry=0x20004a64 <rx_thread_stack+3348>, msg=msg@entry=0x20004a90 <rx_thread_stack+3392>, cb=cb@entry=0x0, cb_data=cb_data@entry=0x0) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/transport.c:507
#17 model_send (model=model@entry=0x20008a6c <root_models>, tx=tx@entry=0x20004a64 <rx_thread_stack+3348>, implicit_bind=implicit_bind@entry=false, msg=msg@entry=0x20004a90 <rx_thread_stack+3392>, cb=cb@entry=0x0, cb_data=cb_data@entry=0x0) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/access.c:638
#18 bt_mesh_model_send (model=model@entry=0x20008a6c <root_models>, ctx=ctx@entry=0x20004be8 <rx_thread_stack+3736>, msg=msg@entry=0x20004a90 <rx_thread_stack+3392>, cb=cb@entry=0x0, cb_data=cb_data@entry=0x0) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/access.c:654
#19 dev_comp_data_get (model=0x20008a6c <root_models>, ctx=0x20004be8 <rx_thread_stack+3736>, buf=<optimized out>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/cfg_srv.c:198
#20 bt_mesh_model_recv (rx=rx@entry=0x20004be4 <rx_thread_stack+3732>, buf=buf@entry=0x20004b28 <rx_thread_stack+3544>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/access.c:579
#21 sdu_recv (rx=rx@entry=0x20004be4 <rx_thread_stack+3732>, seq=1, hdr=<optimized out>, aszmic=aszmic@entry=0 '\000', buf=buf@entry=0x20004bfc <rx_thread_stack+3756>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/transport.c:627
#22 trans_unseg (buf=buf@entry=0x20004bfc <rx_thread_stack+3756>, rx=rx@entry=0x20004be4 <rx_thread_stack+3732>, seq_auth=seq_auth@entry=0x20004bc0 <rx_thread_stack+3696>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/transport.c:898
#23 bt_mesh_trans_recv (buf=buf@entry=0x20004bfc <rx_thread_stack+3756>, rx=rx@entry=0x20004be4 <rx_thread_stack+3732>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/transport.c:1400
#24 bt_mesh_net_recv (data=data@entry=0x20009218 <clients+24>, rssi=rssi@entry=0 '\000', net_if=net_if@entry=BT_MESH_NET_IF_PROXY) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/net.c:1324
#25 proxy_complete_pdu (client=client@entry=0x20009200 <clients>) at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/proxy.c:405
#26 proxy_recv (conn=<optimized out>, attr=<optimized out>, buf=0x20008261 <net_buf_data_hci_rx_pool+109>, len=<optimized out>, offset=0, flags=2 '\002') at /home/ubuntu/zephyr/subsys/bluetooth/host/mesh/proxy.c:467
#27 write_cb (attr=0x200092f8 <proxy_attrs+40>, user_data=0x20004c98 <rx_thread_stack+3912>) at /home/ubuntu/zephyr/subsys/bluetooth/host/att.c:1225
#28 bt_gatt_foreach_attr (start_handle=start_handle@entry=25, end_handle=end_handle@entry=25, func=func@entry=0x10287f5 <write_cb>, user_data=user_data@entry=0x20004c98 <rx_thread_stack+3912>) at /home/ubuntu/zephyr/subsys/bluetooth/host/gatt.c:935
#29 att_write_rsp (conn=conn@entry=0x20000ae4 <conns>, req=req@entry=0 '\000', rsp=rsp@entry=0 '\000', handle=<optimized out>, offset=offset@entry=0, value=0x20008261 <net_buf_data_hci_rx_pool+109>, len=22 '\026') at /home/ubuntu/zephyr/subsys/bluetooth/host/att.c:1268
#30 att_write_cmd (att=<optimized out>, buf=0x200081ac <net_buf_hci_rx_pool+24>) at /home/ubuntu/zephyr/subsys/bluetooth/host/att.c:1500
#31 bt_att_recv (chan=0x20000c18 <bt_req_pool>, buf=0x200081ac <net_buf_hci_rx_pool+24>) at /home/ubuntu/zephyr/subsys/bluetooth/host/att.c:1947
#32 l2cap_chan_recv (chan=<optimized out>, buf=buf@entry=0x200081ac <net_buf_hci_rx_pool+24>) at /home/ubuntu/zephyr/subsys/bluetooth/host/l2cap.c:1573
#33 bt_l2cap_recv (conn=conn@entry=0x20000ae4 <conns>, buf=buf@entry=0x200081ac <net_buf_hci_rx_pool+24>) at /home/ubuntu/zephyr/subsys/bluetooth/host/l2cap.c:1606
#34 bt_conn_recv (conn=conn@entry=0x20000ae4 <conns>, buf=buf@entry=0x200081ac <net_buf_hci_rx_pool+24>, flags=flags@entry=2 '\002') at /home/ubuntu/zephyr/subsys/bluetooth/host/conn.c:1149
#35 hci_acl (buf=buf@entry=0x200081ac <net_buf_hci_rx_pool+24>) at /home/ubuntu/zephyr/subsys/bluetooth/host/hci_core.c:551
#36 hci_rx_thread () at /home/ubuntu/zephyr/subsys/bluetooth/host/hci_core.c:4683
#37 z_thread_entry (entry=0x1005b11 <hci_rx_thread>, p1=<optimized out>, p2=<optimized out>, p3=<optimized out>) at /home/ubuntu/zephyr/lib/os/thread_entry.c:29
#38 0xaaaaaaaa in ?? ())

### PR DESCRIPTION
**Pull request by jhedberg**
The first patch is from #16870. The second patch is what I think is a better approach to handling lots of discardable events hogging up buffers that may be needed for other more important events. By allocating these from a separate pool we make sure not to starve the more important buffer pools.

```
Johan Hedberg (2):
      Bluetooth: Add dedicated pool for HCI_Num_Completed_Packets HCI event
      Bluetooth: Introduce separate pool for discardable events

 drivers/bluetooth/hci/h4.c                         | 11 ++---
 drivers/bluetooth/hci/h5.c                         | 11 +----
 drivers/bluetooth/hci/ipm_stm32wb.c                |  6 +--
 drivers/bluetooth/hci/spi.c                        |  7 +--
 drivers/bluetooth/hci/userchan.c                   | 11 ++---
 include/bluetooth/buf.h                            | 13 ++++++
 include/bluetooth/hci.h                            |  1 +
 samples/bluetooth/mesh/prj.conf                    |  1 -
 samples/bluetooth/mesh/prj_bbc_microbit.conf       |  2 +
 samples/bluetooth/mesh_demo/prj.conf               |  1 -
 samples/boards/nrf52/mesh/onoff-app/prj.conf       |  1 -
 .../mesh/onoff_level_lighting_vnd_app/prj.conf     |  1 -
 samples/boards/reel_board/mesh_badge/prj.conf      |  1 -
 subsys/bluetooth/controller/hci/hci.c              |  4 +-
 subsys/bluetooth/controller/hci/hci_driver.c       |  6 ++-
 subsys/bluetooth/host/Kconfig                      | 21 +++++++++
 subsys/bluetooth/host/hci_core.c                   | 54 ++++++++++++++++++++++
 subsys/bluetooth/host/hci_ecc.c                    |  2 +-
 subsys/bluetooth/host/hci_raw.c                    | 12 +++++
 tests/bluetooth/hci_prop_evt/src/main.c            |  2 +-
 tests/bluetooth/mesh/dbg.conf                      |  1 -
 tests/bluetooth/mesh/friend.conf                   |  1 -
 tests/bluetooth/mesh/gatt.conf                     |  1 -
 tests/bluetooth/mesh/lpn.conf                      |  1 -
 tests/bluetooth/mesh/pb_gatt.conf                  |  1 -
 tests/bluetooth/mesh/prj.conf                      |  1 -
 tests/bluetooth/mesh/proxy.conf                    |  1 -
 tests/bluetooth/mesh_shell/prj.conf                |  1 -
 tests/bluetooth/shell/mesh.conf                    |  1 -
 29 files changed, 121 insertions(+), 56 deletions(-)
```

Fixes #16864

### CODE REVIEW

File: include/bluetooth/buf.h [hunk 1]
```diff
@@ -69,12 +69,13 @@ struct net_buf *bt_buf_get_cmd_complete(s32_t timeout);
...
- *  @param timeout Timeout in milliseconds, or one of the special values
- *                 K_NO_WAIT and K_FOREVER.
+ *  @param evt          HCI event code
+ *  @param discardable  Whether the driver considers the event discardable.
+ *  @param timeout      Timeout in milliseconds, or one of the special values
+ *                      K_NO_WAIT and K_FOREVER.
  *  @return A new buffer.
  */
-struct net_buf *bt_buf_get_evt(u8_t evt, s32_t timeout);
+struct net_buf *bt_buf_get_evt(u8_t evt, bool discardable, s32_t timeout);
```
Comment (Vudentz) [inline include/bluetooth/buf.h]: I assume the K_NO_WAIT would discard anyway so I not sure why we need another variable besides that is completely ignore when CONFIG_BT_DISCARDABLE_POOL is not set.

File: subsys/bluetooth/host/hci_core.c [hunk 2]
```diff
@@ -5672,8 +5677,22 @@ struct net_buf *bt_buf_get_cmd_complete(s32_t timeout)
...
+#if defined(CONFIG_BT_DISCARDABLE_POOL)
+	if (discardable) {
+		struct net_buf *buf;
+
+		buf = net_buf_alloc(&discardable_pool, timeout);
+		if (buf) {
+			net_buf_reserve(buf, CONFIG_BT_HCI_RESERVE);
+			bt_buf_set_type(buf, BT_BUF_EVT);
+		}
+
```
Comment (Vudentz) [inline subsys/bluetooth/host/hci_core.c]: I guess we should log something if we cannot allocate a buffer and thus would discard the event.

**Review by Vudentz — CHANGES_REQUESTED** [review]

File: include/bluetooth/buf.h (hunk 1 above)
Comment (jhedberg) [reply include/bluetooth/buf.h]: @Vudentz those are not quite the same. A HCI driver might be calling this from an ISR for a non-discardable event, in which case K_NO_WAIT is the right timeout to pass. E.g. the h4.c driver does this, and then if that fails it defers the further allocation attempts to the RX thread.

File: subsys/bluetooth/host/hci_core.c (hunk 2 above)
Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c]: The HCI drivers (at least the H4 one) have the logs for when they discard events.

Comment (Vudentz) [reply subsys/bluetooth/host/hci_core.c]: Depending on the LOG domain that may not be printed though and since this is behind a config option it may be difficult to analize traces so I don't think it would hurt to say we are dropping here, it doesn't need to be an error/warning though since since it been flagged as discardable.

File: include/bluetooth/buf.h (hunk 1 above)
Comment (Vudentz) [reply include/bluetooth/buf.h]: Fair enough, I though would use the new pool as well but it seems they are exclusive to each type.

File: subsys/bluetooth/host/hci_core.c (hunk 2 above)
Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c]: Sure, I'll add a log, it's not quite dropping that's happening here, rather just a failed allocation. It's then up to the driver to deal with this failure, either by dropping the incoming packet or by deferring to wait in a thread.

Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c]: Actually, can we forget about this for now. I'm trying to keep the changes minimal since this is to be backported, and adding such a log would mean that we should add it to `bt_buf_get_cmd_complete()` and `bt_buf_get_rx()` as well for consistency. In fact, the place you're asking to add it is the least important since discardable buffers are designed to be able to get allocation failures where as for the other pools it's a more severe thing.

File: include/bluetooth/buf.h (hunk 1 above)
Comment (jhedberg) [reply include/bluetooth/buf.h]: Yeah, I'm all for eliminating redundancy in parameters, but in this case they're a bit orthogonal and we can't make too many assumptions about getting a K_NO_WAIT.

File: subsys/bluetooth/host/hci_core.c (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/hci_core.c]: Sure, np.

Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c]: > Sure, np.

@Vudentz any chance you could withdraw your "changes requested' then? :)

**Review by Vudentz — APPROVED** [review]

File: subsys/bluetooth/host/Kconfig [hunk 3]
```diff
@@ -47,6 +48,26 @@ config BT_RX_BUF_LEN
 	  an L2CAP MTU of 65 bytes. On top of this there's the L2CAP header
 	  (4 bytes) and the ACL header (also 4 bytes) which yields 73 bytes.
 
+config BT_DISCARDABLE_POOL
```
Comment (carlescufi) [inline subsys/bluetooth/host/Kconfig]: Why not use `BT_DISCARDABLE_BUF_COUNT != 0` instead of adding this Kconfig option?

File: subsys/bluetooth/host/Kconfig [hunk 4]
```diff
@@ -47,6 +48,26 @@ config BT_RX_BUF_LEN
...
+	  Use a separate buffer pool for events which the HCI driver
+	  considers discardable. Examples of such events could be e.g.
+	  Advertising Reports. The benefit of having such a pool means that
+	  the if there is a heavy inflow of such events it will not cause
+	  the allocation for other critical events to block and may even
+	  eliminate deadlocks in some cases.
+
+config BT_DISCARDABLE_BUF_COUNT
+	int "Number of discardable event buffers"
+	range 1 255
```
Comment (carlescufi) [inline subsys/bluetooth/host/Kconfig]: Change the range here to `0 255`

File: subsys/bluetooth/host/Kconfig (hunk 3 above)
Comment (carlescufi) [reply subsys/bluetooth/host/Kconfig]: Or at the very least make this hidden and set it based on that

Comment (jhedberg) [reply subsys/bluetooth/host/Kconfig]: > Why not use BT_DISCARDABLE_BUF_COUNT != 0 instead of adding this Kconfig option?

Mainly because it's more natural to have a boolean instead of indirect `> 0` in some places, but also because there are two levels of dependencies and it's (IMO) more natural to reference them with two options: first you have the drivers which are able to support the discardable pool (with this PR it's the native controller and H:4), so these are used to enable the pool in general. Next you have the second level, i.e. *if* the pool has been enabled what the default should be (e.g. a higher value if BT_MESH is enable). I find it easier to understand the dependencies with the split.

That said, if we forget about the slightly better readability of having a boolean the way to represent this with a single DISCARDABLE_BUF_COUNT option is to transform the DISCARDAB_POOL `default y` conditions into the DISCARDABLE_BUF_COUNT dependencies. That way it's not `!= 0` we'll use, rather `#if defined(CONFIG_BT_DISCARDABLE_BUF_COUNT)` which gets us back to a boolean again. Makes sense? It's *slightly* worse since we're then using an `int` type both as an int and as a general boolean (i.e. does the option exist at all or not).

Comment (jhedberg) [reply subsys/bluetooth/host/Kconfig]: @carlescufi so if based on my explanation you're still in favour of a single option I'd do what I described above. One concrete difference is that you'll no-longer be able to force the option on unless the dependencies are fulfilled, but I guess that's desirable anyway, since it makes no sense to enable this unless we have a driver that can provide sufficiently nuanced information to the buffer allocators to take advantage of this feature.

Comment (jhedberg) [reply subsys/bluetooth/host/Kconfig]: @carlescufi so the option definition would end up looking like this:
```
config BT_DISCARDABLE_BUF_COUNT
        int "Number of discardable event buffers"
        range 1 255
        default 20 if BT_MESH
        default 3
        depends on BT_H4 || BT_CTLR
        help
          Number of buffers in a separate buffer pool for events which
          the HCI driver considers discardable. Examples of such events
          could be e.g. Advertising Reports. The benefit of having such
          a pool means that the if there is a heavy inflow of such events
          it will not cause the allocation for other critical events to
          block and may even eliminate deadlocks in some cases.
```

I've not stretched the minimum to 0 since that makes no sense if we can simply either have this defined to something meaningful or not defined at all.

Comment (jhedberg) [reply subsys/bluetooth/host/Kconfig]: @carlescufi I kind of like this single-option approach now that I tested implementing it - I've updated the PR accordingly.

**Comment by jhedberg** [comment]
@xiaoliang314  would you be able to run some tests on this PR? It's a second attempt at solving the deadlocks. The first patch is the same from the original PR for the num_completed_pkts pool, but the second patch is new.

**Comment by xiaoliang314** [comment]
@jhedberg Of course, I will test it next Monday.

**Review by carlescufi — APPROVED** [review]
Looks good thanks! Much cleaner than the previous approach

**Comment by jhedberg** [comment]
> https://github.com/zephyrproject-rtos/zephyr/blob/4cd675c59ce75372d258c07a73b3c103407ffd6b/subsys/bluetooth/host/hci_core.c#L3126-L3132
> @jhedberg My advertising can't be used. It reports a warning message here. Is this a miss?

@xiaoliang314 that warning comes when the HCI driver does not use `bt_buf_get_cmd_complete()` to allocated a buffer for a command complete/status event, or if `bt_buf_get_cmd_complete()` is used but the host doesn't have any pending command to match it with.

**Comment by jhedberg** [comment]
@xiaoliang314 since you're not using any upstream HCI driver, rather some modified h4.c (if I understood right), have you looked the changes I've done to the upstream h4.c in this PR?

**Comment by jhedberg** [comment]
> @xiaoliang314 that warning comes when the HCI driver does not use bt_buf_get_cmd_complete() to allocated a buffer for a command complete/status event, or if bt_buf_get_cmd_complete() is used but the host doesn't have any pending command to match it with.

Sorry, correction: `bt_buf_get_cmd_complete()` is (after this PR) effectively internal to the host stack. You should just be using `bt_buf_get_evt()` and it should take care of the rest. What your description sounds like is that you're passing `true` as the value for the `discardable` parameter of `bt_buf_get_evt()` even in the case of a command complete/status event, which is wrong - you should only pass `true` for advertising reports, and anything else should be `false`.

**Comment by xiaoliang314** [comment]
@jhedberg Yes, only adversting is marked as true, I have referenced the changes in your PR h4.c

**Comment by xiaoliang314** [comment]
I will revisit your changes to make sure I have not missed

**Comment by xiaoliang314** [comment]
@jhedberg I still can't find the reason, this is my log, for your reference.

```
bt_hci_core: opcode 0x0c03 pool id 0 pool 0x20009904 != &hci_cmd_pool 0x200099a4
bt_hci_core: opcode 0x1003 pool id 0 pool 0x20009904 != &hci_cmd_pool 0x200099a4
```

**Comment by xiaoliang314** [comment]
@jhedberg I am very sorry, I am writing wrong. Because my work network is isolated and cannot be copied directly.

**Comment by jhedberg** [comment]
@xiaoliang314 any further update? I haven't found anything wrong myself when re-reviewing the PR, however I did make one change to `bt_buf_get_evt()` it now only allocates from the discardable pool when the event code has first been checked and it isn't one of the critical ones the host stack cares about (num complete, cmd status, cmd complete). This shouldn't make much difference though if the driver is correctly implemented. So if you're still investigating, please try also with the latest version of this PR.

**Comment by xiaoliang314** [comment]
@jhedberg Thank you, it has been resolved. Your PR is working properly
