### PR TITLE
LE Audio: Fixes issues and race conditions when disconnecting CIS

### LINKED ISSUE #54538: LE Audio: BAP Unicast Client Idle/CIS disconnect race condition
**Describe the bug**
When the unicast client receives a notification that the ASE is in the idle state, we call the `released` callback. It should be assumed that if all the streams in a unicast group are released, the group can be deleted. However, the idle state notification can arrive at the unicast client before the CIS disconnect event, causing it to be impossible to delete the group. 

**To Reproduce**
1. Apply https://github.com/zephyrproject-rtos/zephyr/pull/54441
2. Build and run the `unicast_audio.sh` BSIM test
3. See error with deleting group on the 3rd iteration

**Expected behavior**
The stream should not be "released" until all resources are free'd (i.e. wait for the CIS disconnect event). 

**Impact**
Minor as it is a timing issue, and only applies if one attempts to delete the group immediately after the `released` callback. 

**Logs and console output**
```
d_00: @00:00:06.673157  Released stream 0x81cd148
d_00: @00:00:06.673157  [00:00:06.673,156] <dbg> bt_audio_stream: bt_audio_stream_reset: stream 0x81cd148
d_00: @00:00:06.673157  [00:00:06.673,156] <dbg> bt_audio_iso: bt_audio_iso_unbind_ep: iso 0x81d9c30 ep 0x81da20c dir sink
d_00: @00:00:06.673157  [00:00:06.673,156] <dbg> bt_audio_stream: bt_audio_stream_detach: stream 0x81cd148
d_00: @00:00:06.673157  [00:00:06.673,156] <dbg> bt_audio_stream: bt_audio_stream_disconnect: stream 0x81cd148 iso (nil)
d_00: @00:00:06.676117  Deleting unicast group
d_00: @00:00:06.676117  [00:00:06.676,116] <dbg> bt_audio_stream: bt_audio_cig_terminate: group 0x81e75e0
d_00: @00:00:06.676117  [00:00:06.676,116] <dbg> bt_iso: bt_iso_cig_terminate: Invalid CIG state: 2
d_00: @00:00:06.676117  [00:00:06.676,116] <dbg> bt_audio_stream: bt_audio_unicast_group_delete: bt_audio_cig_terminate failed with err -22
d_00: @00:00:06.676117  main: The TESTCASE FAILED with return code 2
d_00: @00:00:06.676117 ERROR: (WEST_TOPDIR/zephyr/tests/bluetooth/bsim_bt/bsim_test_audio/src/unicast_client_test.c:473): Unable to delete unicast group: -22
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: 2ab11953e3ba8842a6947836dbc18ca5b8a2fbd6

**Additional context**
N/A

### LINKED ISSUE #54539: LE Audio: Unicast client should only disconnect CIS if both ASEs are not in streaming state
**Describe the bug**
The calls to `bt_audio_stream_disconnect` does not take into account that a CIS may be bound to 2 ASEs, and should not be attempted to be disconnected if just one of the ASEs goes out of the streaming state. 

**To Reproduce**
N/A

**Expected behavior**
The call to `bt_audio_stream_disconnect` should only be done if none of the ASEs need the CIS. 

**Impact**
Can cause invalid and confusing behavior. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 9e77dae6d99a880d1f5dc5b952c38a8ce2379acc

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Fixes multiple issues with disconnecting the CIS in the unicast client. 

This PR adds additional state checks and proper handling of disconnection of CIS when two endpoints are involved. 

Tested with https://github.com/zephyrproject-rtos/zephyr/pull/54441 which discovered the issue

fixes https://github.com/zephyrproject-rtos/zephyr/issues/54538
fixes https://github.com/zephyrproject-rtos/zephyr/issues/54539

### CODE REVIEW

File: subsys/bluetooth/audio/unicast_client.c [hunk 1]
```diff
@@ -730,12 +730,15 @@ static void unicast_client_ep_releasing_state(struct bt_audio_ep *ep,
 
 	LOG_DBG("dir %s", bt_audio_dir_str(ep->dir));
 
-	/* The Unicast Client shall terminate any CIS established for that ASE
-	 * by following the Connected Isochronous Stream Terminate procedure
-	 * defined in Volume 3, Part C, Section 9.3.15 in when the Unicast
-	 * Client has determined that the ASE is in the Releasing state.
-	 */
-	bt_audio_stream_disconnect(stream);
+	if (ep->iso != NULL && ep->iso->chan.state == BT_ISO_STATE_CONNECTED) {
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/unicast_client.c]: Shouldn't disconnect be called as well if `BT_ISO_STATE_CONNECTING` like you did in other places? Going from Enabling to Releasing I guess there might be no CIS Connected yet (looking at Figure 3.2 in ASCS)

Comment (Thalley) [reply subsys/bluetooth/audio/unicast_client.c]: The addition check for `BT_ISO_STATE_CONNECTING` is added an a later commit in this PR :) At the time of this commit, no other places checks it.

**Comment by laurenmurphyx64** [comment]
Hi @Thalley, link a bug report for this to be merged for 3.3

**Review by kruithofa — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
