### PR TITLE
Bluetooth: Mesh: Decouple blob_io_flash from flash

### LINKED ISSUE #71055: bl_mesh_blob_io_flash: Probable issue with block_start logic and dependency on CONFIG_FLASH_PAGE_LAYOUT
**Describe the bug**
In code here:

https://github.com/zephyrproject-rtos/zephyr/blob/3c42daee9c1b1898bbbdbaab1f32087339f5fd8c/subsys/bluetooth/mesh/blob_io_flash.c#L59-L93

We can see two issues:
 1) Setting of other subsystem, CONFIG_FLASH_PAGE_LAYOUT, indirectly controls the code here
 2) Something that seems to be verification, and alignment, of parameters passed to flash_area_erase may be completely turned off by the Kconfig in other subsystem.

The 1) should probably be resolved by some `CONFIG_BT_MESH_BLOB_` that would default to Y,  when `CONFIG_FLASH_PAGE_LAYOUT=y`, or by enforcing the dependency, on the unit that `CONFIG_FLASH_PAGE_LAYOUT=y`, always.
The existence of local `CONFIG_BT_MESH_BLOB_`  to control the behaviour should describe that now blocks passed to `block_start` should be aligned to erase block of a device the `block_start` operates on (*).

Note that when `CONFIG_FLASH_PAGE_LAYOUT=y` then the code will correct erase size to align it with device requirements, and this reduces chances of `flash_area_erase` to fail, but also means that when passing `block->size` unaligned, to erase block of a device,  will work with  `CONFIG_FLASH_PAGE_LAYOUT=y` and fail when `CONFIG_FLASH_PAGE_LAYOUT=n`: it seems that `CONFIG_FLASH_PAGE_LAYOUT=n`, from other subsystem, controls correction of a parameter that is passed to other subsystem (seemingly unrelated).

Assuming that the said block->size is passed, when `CONFIG_FLASH_PAGE_LAYOUT=n` top to bottom correct with the device layout, this means that the parameter has been checked somewhere before the call to `block_start` has been invoked. This means that the size alignment done at line 86, and entire 70-87 block, may not be needed at all.
If that is not the case, this probably means that unverified parameter has probably reached too low into a call path.

I do not think it should be allowed for the `flash_area_erase` to fail here due to incorrect `block->size` so the `CONFIG_FLASH_PAGE_LAYOUT=y` is mandatory, which means that there is only one path in code and the #else could be removed.

### PR DESCRIPTION
**Pull request by ludvigsj**
This fully decouples blob_io_flash from flash configuration details, by removing remaining direct references to CONFIG_FLASH_* options and hard-coded write block size, instead pulling this from the actual flash device used.

It also requires the use of FLASH_PAGE_LAYOUT APIs when enabling the module for use with flash with explicit erase. This was already a silent requirement, since the existing code does not work for such use cases except for the case when a BLOB has a size which is a multiple of the page size (since, without it, trying to erase flash space for the final block, which is of variable size, will fail).

Additionally, the erasure logic has been changed slightly to only erase a page when starting the first block on that page. This fixes a bug where, if the block size is smaller than the page size, the entire page would be erased upon start of each block when writing, meaning only the final block on each page would be retained. This works because blocks are always received in order.

(Note: we might need to add some code to ensure that the area and offset passed to the init function lies on a page boundary. I suggest to defer that to a separate PR, as it is an existing problem already and not introduced by my changes)

The block write routine has been updated to be more generic and fix a few bugs:

  * The write buffer is now sized based on a KConfig option instead of basing it off the device tree - this makes the module usable with any flash device, not just the internal memory. The configured value is checked during initialization, to ensure that the configured size will fit the write block size required by the device passed to the init function.
  * The erase value used to fill the buffer when using a device with explicit erase is now pulled from the flash parameters instead of being hard-coded to `0xff`.
  * An additional write block sized piece of buffer is allocated - the previous buffer sizing with rounding up only worked if `BLOB_RX_CHUNK_SIZE % WRITE_BLOCK_SIZE` was 0 or 1 (which coincidentally worked in all testing because the chunk size defaults to 161, and for internal flash w/write block size of 4, `161 % 4 == 1`).
  * The choice of whether to just write the chunk as-is or to write-block align it is now based on the erase cap pulled from the flash parameters, instead of checking the type of memory in the SOC. This means the module dos _not_ currently support the case where memory has to be written write-block aligned, but the memory does _not_ use explicit erase. It uses a trick of filling the write buffer with the erase value to avoid overwriting existing chunks, which will not work in this case. This trick is required to support random ordered chunks while still writing write-block aligned.
  * The code has been cleaned up a bit in general.

### CODE REVIEW

File: subsys/bluetooth/mesh/blob_io_flash.c [hunk 1]
```diff
@@ -28,9 +28,17 @@ static int test_flash_area(uint8_t area_id)
...
+
 	flash_area_close(area);
 
-	if (align > WRITE_BLOCK_SIZE) {
+	if (!fdev) {
+		return -ENODEV;
+	}
+
+	if ((flash_params_get_erase_cap(fparam) & FLASH_ERASE_C_EXPLICIT) &&
+	    align > CONFIG_BT_MESH_BLOB_IO_FLASH_WRITE_BLOCK_SIZE_MAX) {
```
Comment (alxelax) [inline subsys/bluetooth/mesh/blob_io_flash.c]:
```suggestion
	    CONFIG_BT_MESH_BLOB_IO_FLASH_WRITE_BLOCK_SIZE_MAX % align) {
```
I guess this should be better

File: subsys/bluetooth/mesh/blob_io_flash.c [hunk 2]
```diff
@@ -56,42 +64,42 @@ static void io_close(const struct bt_mesh_blob_io *io,
 	flash_area_close(flash->area);
 }
 
+/* Erasure code not needed if no flash in the system requires explicit erase */
+#ifdef CONFIG_BT_MESH_BLOB_IO_FLASH_WITH_ERASE
```
Comment (alxelax) [inline subsys/bluetooth/mesh/blob_io_flash.c]: Hm... I'm not sure if this is correct. Please take a look at the initial intention of this:
https://github.com/zephyrproject-rtos/zephyr/pull/82386#discussion_r1900714580

I guess even if device does not have explicit erase, it might use external memory with explicit erase.

File: subsys/bluetooth/mesh/blob_io_flash.c [hunk 3]
```diff
@@ -56,42 +64,42 @@ static void io_close(const struct bt_mesh_blob_io *io,
...
+	const struct device *fdev = flash_area_get_device(fa);
+	struct flash_pages_info page;
+	int err;
+
+	if (!fdev) {
+		return -ENODEV;
 	}
 
-	return 0;
+#ifdef CONFIG_BT_MESH_BLOB_IO_FLASH_WITHOUT_ERASE
```
Comment (alxelax) [inline subsys/bluetooth/mesh/blob_io_flash.c]: Probably we do not need this for the same reason as above (soc has memory with explicit erase and external RRAM not)

File: subsys/bluetooth/mesh/Kconfig [hunk 4]
```diff
@@ -1058,12 +1058,24 @@ config BT_MESH_BLOB_IO_FLASH_WITH_ERASE
 	bool "BLOB flash support for devices with erase"
```
Comment (alxelax) [inline subsys/bluetooth/mesh/Kconfig]: Do we need these options(BT_MESH_BLOB_IO_FLASH_WITHOUT_ERASE and BT_MESH_BLOB_IO_FLASH_WITH_ERASE) at all after your refactoring?
I guess this information can be extracted from flash parameters.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 2 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c]: This option means "There is at least one device (meaning: flash, external, internal, whatever) in my system which uses explicit erase, that I'd like to use with the BLOB IO". If it is disabled, then either no such device exists in the configuration, or the user has manually disabled it, meaning they agree to not use this module with such a device. ("Device" here meaning specific flash device, not the entire system). Or have I misunderstood?

File: subsys/bluetooth/mesh/Kconfig (hunk 4 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/Kconfig]: The reason for these are twofold:
  * `select FLASH_PAGE_LAYOUT` only if the application actually plans to/is able to use this with an explicit erase flash device
  * Selectively compile things like erasure code only if they are needed.

We can remove flexibility and remove these options, this will cause a) all users to be forced to compile in erasure code even if they will never run it and b) force all users to enable FLASH_PAGE_LAYOUT even if they don't need it. (This is a bit of a moot point, since most use cases require this anyways for settings or mcuboot)

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 1 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c]: I don't think so? Having a MAX value of 5 when using write block size == 4 is fine, it just causes some unused bytes on the stack that will never be passed to the flash API. Your suggestion would also incorrectly return success if the configured max size is 0.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 2 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c]: If an external flash device using explicit erase is enabled, this option will default to 1 even if internal flash doesn't use erase

File: subsys/bluetooth/mesh/Kconfig (hunk 4 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/Kconfig]: (Looking at this again, `BT_MESH_BLOB_IO_FLASH_WITHOUT_ERASE` is actually quite useless and can probably be removed)

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 1 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c]: Oh, no you are actually correct here because of the `ROUND_UP`. I'm sorry, I'll look into this.

File: subsys/bluetooth/mesh/blob_io_flash.c [hunk 5]
```diff
@@ -125,30 +134,49 @@ static int wr_chunk(const struct bt_mesh_blob_io *io,
...
 
-	uint8_t buf[ROUND_UP(BLOB_RX_CHUNK_SIZE, WRITE_BLOCK_SIZE)];
+	/*
+	 * Allocate one additional write block for the case where a chunk will need
+	 * an extra write block on both sides to fit.
+	 */
+	uint8_t buf[ROUND_UP(BLOB_RX_CHUNK_SIZE, CONFIG_BT_MESH_BLOB_IO_FLASH_WRITE_BLOCK_SIZE_MAX)
+		    + CONFIG_BT_MESH_BLOB_IO_FLASH_WRITE_BLOCK_SIZE_MAX];
+	uint32_t write_block_size = flash_area_align(flash->area);
 	off_t area_offset = flash->offset + block->offset + chunk->offset;
```
Comment (alxelax) [inline subsys/bluetooth/mesh/blob_io_flash.c:163]: I do not understand how this will work if chunk->size is not equal to 1 or multiple write block sizes. Let say 7.
It will store incoming data with wholes due to padding.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 2 above)
Comment (alxelax) [reply subsys/bluetooth/mesh/blob_io_flash.c]: I see flash driver has already had this logic:
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/drivers/flash.h#L112-L124
```
static inline
int flash_params_get_erase_cap(const struct flash_parameters *p)
{
#if defined(CONFIG_FLASH_HAS_EXPLICIT_ERASE)
#if defined(CONFIG_FLASH_HAS_NO_EXPLICIT_ERASE)
	return (p->caps.no_explicit_erase) ? 0 : FLASH_ERASE_C_EXPLICIT;
#else
	ARG_UNUSED(p);
	return FLASH_ERASE_C_EXPLICIT;
#endif
#endif
	return 0;
}
```
if there are no devices with explicit erase, the inline function will be reduced till `return 0` and I'm pretty sure the further code should be cut out by compiler.

I do not think we need to bring this mess from driver level to some functionality that is built above driver.

I would suggest leaving it to the driver developers.
My main idea was blob flash io gets all necessary information from driver and does not need any configuration from Mesh KConfig.
That means it is possible to use any memory that has Zephyr's flash driver.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 5 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c:163]: No, it will write the same write block twice (one time per chunk overlapping that write block), with either the first or last part set to the erase value, causing no holes. I have tested this with chunk size of 159, which is == 3 mod 4. The logic is for all purposes the same that was there before this PR.

File: subsys/bluetooth/mesh/Kconfig (hunk 4 above)
Comment (alxelax) [reply subsys/bluetooth/mesh/Kconfig]: To me, it seems redundant. However, I do not want to insist of removing it since it has been already existed.
If code owner agrees with it, then leave it.
@PavelVPV, do we need such flexibility? (please read this first: https://github.com/zephyrproject-rtos/zephyr/pull/95836/files#r2341155292)

Comment (PavelVPV) [reply subsys/bluetooth/mesh/Kconfig]: @de-nordic , since you introduced these Kconfigs, can you comment on this?

I see flash driver had this capability that [Alex refers to](https://github.com/zephyrproject-rtos/zephyr/pull/95836/files#r2341155292) already when these options [were introduced](https://github.com/zephyrproject-rtos/zephyr/pull/82386).

In either case, I would consider their removal (if we decide to do so) as a separate PR.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 2 above)
Comment (PavelVPV) [inline subsys/bluetooth/mesh/blob_io_flash.c]: Separate discussion:
what was the need in getting rid of `IS_ENABLED` pattern and using `ifdef..endif` explicitly? Did you check what is left in the binary in the original variant and did you compare it with this variant? What if LTO is enabled?

The reason I ask is that most likely after LTO we will get the same binary code here with the original variant as with the new code from this PR. `IS_ENABLED` could be used when `block_start` is assigned. Then we compile all branches in a single variant. Of course unless I missed something.

File: subsys/bluetooth/mesh/Kconfig [hunk 6]
```diff
@@ -1058,12 +1058,24 @@ config BT_MESH_BLOB_IO_FLASH_WITH_ERASE
...
 	default y if FLASH_HAS_EXPLICIT_ERASE
 	depends on FLASH_HAS_EXPLICIT_ERASE
+	select FLASH_PAGE_LAYOUT
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/Kconfig]: > It also requires the use of FLASH_PAGE_LAYOUT APIs when enabling the module for use with flash with explicit erase. This was already a silent requirement, since the existing code does not work for such use cases except for the case when a BLOB has a size which is a multiple of the page size (since, without it, trying to erase flash space for the final block, which is of variable size, will fail).

This should be in a separate commit.

File: subsys/bluetooth/mesh/blob_io_flash.c [hunk 7]
```diff
@@ -56,42 +64,42 @@ static void io_close(const struct bt_mesh_blob_io *io,
...
+
+	err = flash_get_page_info_by_offs(fdev, start, &page);
+	if (err) {
+		return err;
+	}
+
+	if (start != page.start_offset) {
+		/* Only need to erase when starting the first block on the page. */
+		return 0;
+	}
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/blob_io_flash.c:98]: I guess this change belongs to the comment:
> Additionally, the erasure logic has been changed slightly to only erase a page when starting the first block on that page. This fixes a bug where, if the block size is smaller than the page size, the entire page would be erased upon start of each block when writing, meaning only the final block on each page would be retained. This works because blocks are always received in order.

Then this should be done in a separate commit.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 1 above)
Comment (PavelVPV) [inline subsys/bluetooth/mesh/blob_io_flash.c]: It would be good to print error and explain what user can do to fix it.

File: subsys/bluetooth/mesh/Kconfig [hunk 8]
```diff
@@ -1058,12 +1058,24 @@ config BT_MESH_BLOB_IO_FLASH_WITH_ERASE
...
 	  Enable path supporting devices with erase. This option appears only
 	  if there are devices requiring erase,  before write, in the system
 	  and may be disabled to reduce code size in case when no operations
 	  are intended on such type of devices.
 
+if BT_MESH_BLOB_IO_FLASH_WITH_ERASE
+
+config BT_MESH_BLOB_IO_FLASH_WRITE_BLOCK_SIZE_MAX
+	int "Maximum supported write block size"
+	default 16
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/Kconfig]: Maybe shorten this to 4? 16 is not that much but we can reduce stack usage a bit if we use 4. 4 is also default write block size for external and local flash on nRF DKs.

**Review by PavelVPV — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 2 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c]: If you want this for testing purposes, there is nothing stopping you from enabling both `_WITH_ERASE` and `_WITHOUT_ERASE` for testing, compiling everything at once. I have not checked LTO, we might not even need LTO though for this, since the handler is static, it should be able to be optimized out at the compile stage? I'll check and remove the `#ifdef`s if they are not needed, to simplify.

File: subsys/bluetooth/mesh/Kconfig (hunk 8 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/Kconfig]: Right, I see. I set it to 16 because RRAM on nRF54L uses 16, but that of course doesn't need a buffer at all since it is written directly, my mistake.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 2 above)
Comment (PavelVPV) [reply subsys/bluetooth/mesh/blob_io_flash.c]: I am mostly concerned about changing from `IS_ENABLED` to `ifdef` here. I don't see what is the need for this. And if there is no need, prefer to not change code. My guess was that you were trying to optimize the code even more by using `ifdef`s, that is why I brought up LTO as argument here because maybe this change isn't needed if with LTO the result is the same.

If you want to keep your change, please move to a separate commit.

Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c]: There is no point in using `IS_ENABLED`, checking of the flash params from the driver is enough in that case, so the only reason to keep using these KConfigs would be conditional compilation. If we don't want to do that, they can be completely removed to simplify, optionally only used when assigning the handler.

Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c]: > prefer to not change code

I don't see why these options were introduced in the first place if not to save code size when erasure is not needed.

File: subsys/bluetooth/mesh/blob_io_flash.c [hunk 9]
```diff
@@ -125,30 +134,49 @@ static int wr_chunk(const struct bt_mesh_blob_io *io,
...
 
-	if (IS_ENABLED(CONFIG_SOC_FLASH_NRF_RRAM)) {
+	const struct flash_parameters *fparam = flash_get_parameters(fdev);
+
+	/*
+	 * If device has no erase requirement then write directly.
+	 * This is required since trick with padding using the erase value will
+	 * not work in this case.
+	 */
+	if (!(flash_params_get_erase_cap(fparam) & FLASH_ERASE_C_EXPLICIT)) {
```
Comment (omkar3141) [inline subsys/bluetooth/mesh/blob_io_flash.c:150]: This condition is checked several times in this module. Also, wr_chunk() will execute thousands of times during DFU. Though this is not time-critical, we could save few bytes of code, if condition `(flash_params_get_erase_cap(fparam) & FLASH_ERASE_C_EXPLICIT` is extracted as a boolean value during init and saved into `bt_mesh_blob_io_flash` context, and then use that value where needed. That way, it will be bit faster and reduce footprint a bit.

File: subsys/bluetooth/mesh/blob_io_flash.c [hunk 10]
```diff
@@ -125,30 +134,49 @@ static int wr_chunk(const struct bt_mesh_blob_io *io,
...
 					flash->offset + block->offset + chunk->offset,
 					chunk->data, chunk->size);
 	}
 
-	uint8_t buf[ROUND_UP(BLOB_RX_CHUNK_SIZE, WRITE_BLOCK_SIZE)];
+	/*
+	 * Allocate one additional write block for the case where a chunk will need
+	 * an extra write block on both sides to fit.
+	 */
+	uint8_t buf[ROUND_UP(BLOB_RX_CHUNK_SIZE, CONFIG_BT_MESH_BLOB_IO_FLASH_WRITE_BLOCK_SIZE_MAX)
```
Comment (omkar3141) [inline subsys/bluetooth/mesh/blob_io_flash.c:160]: Maybe it is better to allocate this buffer inside the `bt_mesh_blob_io_flash`, since this can be quite a large buffer, it will have implications on stack size needed for RX thread. Playing with stack value of the thread becomes more annoying (due to such large buffers) and this creates yet another mechanism where it can break in the field (or someone has to allocate large stack just to be sure it does not fail, wasting the memory). Since this buffer will be needed anyway during lifetime of the device, it is better to move to common context and let it get allocated in the global memeory.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 9 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c:150]: I thought about this, but there is not much point: the actual call to `flash_area_write` takes up orders of magnitude more time than this code which evaluates to ~either a constant or~ something like a simple memory read of a single byte, depending on what the compiler does here (I haven't checked the assembly, but I _have_ checked the timings for this)

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 10 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c:160]: I decided to work with the principle of as few changes as possible here. If we want this as an optimization, I think it should be a separate task. The buffer is currently on the stack on _main_.

(Also, using the stack means you can save quite a bit of memory if you have an application with multiple BLOB IO contexts initialized at the same time (to different flash areas) but only use one of them in any given transfer)

File: subsys/bluetooth/mesh/Kconfig (hunk 8 above)
Comment (omkar3141) [reply subsys/bluetooth/mesh/Kconfig]: I would suggest it to keep to 16 or make it select different values based on underlaying platform. Reason being, not using 16 for nRF54L (and if writes are not aligned to 16 byte boundary) it will cause double (or multiple wries) due to how RRAM driver is written. On RRAM, each write will consume one endurance of 16 byte word line due to necessary ECC bits updates to commit the writes to actual NVM. We analyzed this throughly for EMDS and concluded that the best usage of RRAM is aligning all writes to 16 byte boundary and writing 16 bytes at a time except for the last part of the data. 

This means, allowed chunk sizes could be constrained to multiples of 16 (this is okay and not a big issue IMO), or BLOB IO logic could collect 16 bytes across chunk boundaries before triggering actual writes (this can be a bit complicated due to reporting of received chunks). 

As I write this, I realize that it may cause some extra work, and I'm okay to do this as next step in seperate PR (optimizing writes to RRAM usecase).

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 10 above)
Comment (omkar3141) [reply subsys/bluetooth/mesh/blob_io_flash.c:160]: It is okay to create seperate task for this, but I see this as a considerable issue in our architecture choices. Specially, insufficient stack related quereis (crashes and doubts) from devzone, and specially our exercises to tune stack sizes for threads across samples every few months (I think twice in recent past). Of course we can't avoid changing required max stack sizes by some amounts as code depth grows or gets refactored but keeping it to minimum and reducing the gap between min to max is good ... I think.

Utilizing multiple BLOB IO context does not seem immediate application need based on my experience. For majority of the cases single BLOB IO context will be used. For those cases, stack size setting gymnastic (or wasted stack size because one cannot predict how large stack could grow) could be annoying.

Also, why do you say this buffer is on the stack on main?

File: subsys/bluetooth/mesh/Kconfig (hunk 4 above)
Comment (omkar3141) [reply subsys/bluetooth/mesh/Kconfig]: > In either case, I would consider their removal (if we decide to do so) as a separate PR.

Why not in this one, since it is relavant for the title of the PR?

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 2 above)
Comment (omkar3141) [reply subsys/bluetooth/mesh/blob_io_flash.c]: I don't think LTO is a mainstream option yet. It is not enabled by default nor we recommend it anywhere.

File: subsys/bluetooth/mesh/Kconfig (hunk 8 above)
Comment (PavelVPV) [reply subsys/bluetooth/mesh/Kconfig]: Then default value could be based on platform, but either way fine by my to keep as is considering the reply above.

File: subsys/bluetooth/mesh/Kconfig (hunk 4 above)
Comment (PavelVPV) [reply subsys/bluetooth/mesh/Kconfig]: > > In either case, I would consider their removal (if we decide to do so) as a separate PR.
> 
> Why not in this one, since it is relavant for the title of the PR?

Yeah, up to the author. I'm fine with deprecating these options.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 10 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/blob_io_flash.c:160]: https://github.com/zephyrproject-rtos/zephyr/blob/0748b4e47d1f2888708b65d0a7ed5a2d10851b62/subsys/bluetooth/mesh/blob_io_flash.c#L135 Stack allocated buffer, current main. I did not introduce this.

File: subsys/bluetooth/mesh/Kconfig (hunk 8 above)
Comment (ludvigsj) [reply subsys/bluetooth/mesh/Kconfig]: This option does not affect the RRAM case at all, because that does not use a buffer. The only thing this option does is control the buffer size. It does not control the writing, it does not control alignment.

Comment (ludvigsj) [reply subsys/bluetooth/mesh/Kconfig]: > BLOB IO logic could collect 16 bytes across chunk boundaries before triggering actual writes

This will in the worst theoretical case require us to collect 32 bytes (16 on each end) for each chunk, if we receive chunks 0, 2, 4 etc. before the chunks in between, and will introduce a lot of complexity. Aligning the chunk size to write block size seems a much better solution (in fact, since the max chunk size that can fit in a message is 161 bytes, we can default this to 160 bytes for all BLOB IO flash users, only lose 1 byte per message, and then actually get rid of the buffer for flash with explicit erase as well. Idea for improvement and new task.)

Comment (PavelVPV) [reply subsys/bluetooth/mesh/Kconfig]: > This option does not affect the RRAM case at all, because that does not use a buffer. The only thing this option does is control the buffer size. It does not control the writing, it does not control alignment.

Oh, yes, you are right. In case of RRAM this will be executed:https://github.com/zephyrproject-rtos/zephyr/blob/b77724229f8de62db5ac454c6822289b22312150/subsys/bluetooth/mesh/blob_io_flash.c#L150-L154

Comment (PavelVPV) [reply subsys/bluetooth/mesh/Kconfig]: >  Aligning the chunk size to write block size seems a much better solution (in fact, since the max chunk size that can fit in a message is 161 bytes, we can default this to 160 bytes for all BLOB IO flash users, only lose 1 byte per message, and then actually get rid of the buffer for flash with explicit erase as well. Idea for improvement and new task.)

But chunk size is dictated by BLOB client and that is not necessarily our stack.

Comment (ludvigsj) [reply subsys/bluetooth/mesh/Kconfig]: Oh, you are right. Then I still think the current behavior (which, bear in mind, is unchanged compared to the behavior on the current main branch) is the best we can do without a larger rethink/rewrite. As I mentioned, just writing everything unbuffered to RRAM will (assuming the chunk size is always much larger than the write block size) cause it to wear out twice as fast in the worst case (the write blocks on chunk boundaries will be written twice). Since BLOB reception is typically not happening with a very high frequency, I think this should be fine for now.

File: subsys/bluetooth/mesh/blob_io_flash.c (hunk 10 above)
Comment (omkar3141) [reply subsys/bluetooth/mesh/blob_io_flash.c:160]: ahh ... you mean the "main" branch. Not the main thread :D.  Well yes, that was my point, since this is stack allocated it pushes up the stack requirement for RX thread, which is how it is today, but can be updated to reduce stack usage for RX thread.

**Review by omkar3141 — COMMENTED** [review]
PR looks fine to me. Are we going to remove the KConfig options then?

**Comment by ludvigsj** [comment]
I have split this into separate commits now. Please take another look. (I'm currently checking that DFU works on the last commit, if someone wants me to run DFU using each of the commits, please tell me. All of the separate commits pass twister on my desk.)

**Review by PavelVPV — APPROVED** [review]

**Review by omkar3141 — APPROVED** [review]
