### PR TITLE
drivers: clock_control: mspm0: Conditionally set syspllclk0 as the source of MCLK

### LINKED ISSUE #100734: Ti LP-MSPM0G3507 is bricked after flashing blinky sample
### Describe the bug

Zephyr commit: 4758cfadf5aa8664bfe61316aa2311fb2deaad0f
Openocd commit: 3e7a7092d47ceca874166839d6e88439c911f452
SDK: zephyr-sdk-0.17.4

I built the sample: `west build -b lp_mspm0g3507 samples/basic/blinky/`
Since the SDK's openocd doesn't have support for the on-board programmer (XDS110), I had to compile the openocd by myself.
I tried flashing the firmware with command: `west flash --openocd /usr/local/bin/openocd`

Something happened, some errors appeared and the MCU is bricked since then. The programmer is correctly detected by the PC, but it is unable to detect the MCU. It returns error that "core not detected". I tried using external Ti's programmer, I tried using BSL, I tried using multiple external SWD programmers and nothing helped. I bricked two boards.

As additional test, I tried using pyocd after bricking and got this message:
```
~/Workspace/zephyr/zephyr$ pyocd reset
0000306 W Generic 'cortex_m' target type is selected by default; is this intentional? You will be able to debug most devices, but not program flash. To set the target type use the '--target' argument or 'target_override' option. Use 'pyocd list --targets' to see available targets types. [board]
0005359 C No cores were discovered! [__main__]
```

I'm not sure if this is a bug in Zephyr or Openocd, but since the Zephyr is executing the openocd flasher, I'm reporting it here.

In the MSPM0 documentation I've found a note that may be a reason of the brick:
```
Extreme care must be taken when erasing and programming NONMAIN. If done incorrectly, like losing
connection in NONMAIN programming, the device is locked in a permanently unrecoverable state.
```

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. west build -b lp_mspm0g3507 samples/basic/blinky/
2. west flash --openocd /usr/local/bin/openocd 

### Relevant log output

```shell

```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

OS: Linux Debian Trixie
Zephyr commit: 4758cfadf5aa8664bfe61316aa2311fb2deaad0f
Openocd commit: 3e7a7092d47ceca874166839d6e88439c911f452
SDK: zephyr-sdk-0.17.4

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lsd-he360**
The mspm0g.dtsi DT sets the clk2x-div property for the syspll node in the DT to enable syspllclk2x. The MSPM0 clock control code has a compile-time check to ensure either syspllclk2x or syspllclk0 is enabled at a time. The clock control code; however, sets clk0 as the MCLK source even when syspllck2x is enabled (and syspllclk0 disabled). The changes in this commit would ensure syspllclk0 is only set as the source for MCLK if syspllclk0 is enabled. The syspllclk0 is considered enabled if clk0-div property is defined for the syspll node.

Fixes #100734.

### CODE REVIEW

File: drivers/clock_control/clock_control_mspm0.c [hunk 1]
```diff
@@ -167,7 +167,8 @@ static int clock_mspm0_init(const struct device *dev)
 #endif
 
 #if MSPM0_SYSPLL_ENABLED
-#if DT_SAME_NODE(DT_MCLK_CLOCKS_CTRL, DT_NODELABEL(syspll))
+#if (DT_SAME_NODE(DT_MCLK_CLOCKS_CTRL, DT_NODELABEL(syspll)) && \
+		DT_NODE_HAS_PROP(DT_NODELABEL(syspll), clk0_div))
```
Comment (ssekar15) [inline drivers/clock_control/clock_control_mspm0.c]: use 

if(clock_mspm0_cfg_syspll.enableCLK0 == true)

**Review by ssekar15 — CHANGES_REQUESTED** [review]
@lsd-he360 I understand that SYSPLL.CLK0 is selected as MCLK/CPUCLK without enabled halts the cpu, but how does it related to issue which bricks the SoC permanently?

Could you improve the commit message with above information and fix tag of issue `Fix #100734`.  'why' changes is more important that 'what'.

File: drivers/clock_control/clock_control_mspm0.c (hunk 1 above)
Comment (lsd-he360) [reply drivers/clock_control/clock_control_mspm0.c]: Fixed.

**Review by ssekar15 — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]
