### PR TITLE
Bluetooth: L2CAP: Fix missing buffer length check for sdu_len

### LINKED ISSUE #32497: No checks of buffer size in l2cap_chan_le_recv
**Describe the bug**

https://github.com/zephyrproject-rtos/zephyr/blob/80ec93860ba5aee4e730dc46569060a8eb7bd16e/subsys/bluetooth/host/l2cap.c#L2192

```c
static void l2cap_chan_le_recv(struct bt_l2cap_le_chan *chan,
			       struct net_buf *buf)
{
	uint16_t sdu_len;
	int err;

	if (!test_and_dec(&chan->rx.credits)) {
		BT_ERR("No credits to receive packet");
		bt_l2cap_chan_disconnect(&chan->chan);
		return;
	}

	/* Check if segments already exist */
	if (chan->_sdu) {
		l2cap_chan_le_recv_seg(chan, buf);
		return;
	}

	sdu_len = net_buf_pull_le16(buf);
```

May be I'm missing something. But it looks like net_buf_pull_le16 can read outside of the buffer if a frame has the length fewer than 2. I couldn't find any checks in the callers as well.

### PR DESCRIPTION
**Pull request by jhedberg**
We should verify that the buffer has sufficient data before attempting
to parse the SDU length field.

Fixes #32497

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
Only compile tested, but seemed trivial enough..

File: subsys/bluetooth/host/l2cap.c [hunk 1]
```diff
@@ -2189,6 +2189,11 @@ static void l2cap_chan_le_recv(struct bt_l2cap_le_chan *chan,
 		return;
 	}
 
+	if (buf->len < 2) {
+		BT_WARN("Too short data packet");
+		return;
```
Comment (joerchan) [inline subsys/bluetooth/host/l2cap.c:2194]: Should the channel be disconnected, like it is for other error cases? sdu_len exceeds chan RX mtu for example?

Comment (jhedberg) [reply subsys/bluetooth/host/l2cap.c:2195]: @joerchan agreed, updated now

**Review by joerchan — APPROVED** [review]

**Review by Vudentz — APPROVED** [review]
LGTM
