### PR TITLE
drivers: flash: mcux: clear caches after erase and write on Kinetis

### LINKED ISSUE #98487: tests: tests/drivers/flash/common: kinetis with nxp mpu : failed: Testsuite failed
**Describe the bug**
below case are failed
drivers.flash.common.test_storage_partition.flash_driver.flash_fill
drivers.flash.common.test_storage_partition.flash_driver.read_unaligned_address
drivers.flash.common.test_storage_partition.flash_driver.flash_flatten
drivers.flash.common.test_storage_partition.flash_driver.flash_erase

test is failed on v4.3.0-rc1
- twr_ke18f/mke18f16
- frdm_k82f

this cases are not pass, and remind by #98281, maybe cache issue.

testcase path is tests/drivers/flash/common

see logs for details

**To Reproduce**
1. 
```
scripts/twister -p twr_ke18f/mke18f16  -T tests/drivers/flash/common --sub-test tests/drivers/flash/common
```
or
```
# west twister -p twr_ke18f/mke18f16 -T tests/drivers/flash/common --sub-test tests/drivers/flash/common
```
2. See error

```
Testsuite failed
```

**Expected behavior**
test pass

**Impact**

**Logs and console output**

```  
START - test_flash_erase
Test will run on device flash-controller@40020000
i=0:	read_buf[i]=170	expected[i]=0
i=1:	read_buf[i]=170	expected[i]=1
i=2:	read_buf[i]=170	expected[i]=2
i=3:	read_buf[i]=170	expected[i]=3
i=4:	read_buf[i]=170	expected[i]=4
i=5:	read_buf[i]=170	expected[i]=5
i=6:	read_buf[i]=170	expected[i]=6
i=7:	read_buf[i]=170	expected[i]=7
i=8:	read_buf[i]=170	expected[i]=8
i=9:	read_buf[i]=170	expected[i]=9
i=10:	read_buf[i]=170	expected[i]=10
i=11:	read_buf[i]=170	expected[i]=11
i=12:	read_buf[i]=170	expected[i]=12
i=13:	read_buf[i]=170	expected[i]=13
i=14:	read_buf[i]=170	expected[i]=14
i=15:	read_buf[i]=170	expected[i]=15
i=16:	read_buf[i]=170	expected[i]=16
i=17:	read_buf[i]=170	expected[i]=17
i=18:	read_buf[i]=170	expected[i]=18
i=19:	read_buf[i]=170	expected[i]=19
i=20:	read_buf[i]=170	expected[i]=20
i=21:	read_buf[i]=170	expected[i]=21
i=22:	read_buf[i]=170	expected[i]=22
i=23:	read_buf[i]=170	expected[i]=23
i=24:	read_buf[i]=170	expected[i]=24
i=25:	read_buf[i]=170	expected[i]=25
i=26:	read_buf[i]=170	expected[i]=26
i=27:	read_buf[i]=170	expected[i]=27
i=28:	read_buf[i]=170	expected[i]=28
i=29:	read_buf[i]=170	expected[i]=29
i=30:	read_buf[i]=170	expected[i]=30
i=31:	read_buf[i]=170	expected[i]=31
i=32:	read_buf[i]=170	expected[i]=32
i=33:	read_buf[i]=170	expected[i]=33
i=34:	read_buf[i]=170	expected[i]=34
i=35:	read_buf[i]=170	expected[i]=35
i=36:	read_buf[i]=170	expected[i]=36
i=37:	read_buf[i]=170	expected[i]=37
i=38:	read_buf[i]=170	expected[i]=38
i=39:	read_buf[i]=170	expected[i]=39
i=40:	read_buf[i]=170	expected[i]=40
i=41:	read_buf[i]=170	expected[i]=41
i=42:	read_buf[i]=170	expected[i]=42
i=43:	read_buf[i]=170	expected[i]=43
i=44:	read_buf[i]=170	expected[i]=44
i=45:	read_buf[i]=170	expected[i]=45
i=46:	read_buf[i]=170	expected[i]=46
i=47:	read_buf[i]=170	expected[i]=47
i=48:	read_buf[i]=255	expected[i]=48
i=49:	read_buf[i]=255	expected[i]=49
i=50:	read_buf[i]=255	expected[i]=50
i=51:	read_buf[i]=255	expected[i]=51
i=52:	read_buf[i]=255	expected[i]=52
i=53:	read_buf[i]=255	expected[i]=53
i=54:	read_buf[i]=255	expected[i]=54
i=55:	read_buf[i]=255	expected[i]=55
i=56:	read_buf[i]=255	expected[i]=56
i=57:	read_buf[i]=255	expected[i]=57
i=58:	read_buf[i]=255	expected[i]=58
i=59:	read_buf[i]=255	expected[i]=59
i=60:	read_buf[i]=255	expected[i]=60
i=61:	read_buf[i]=255	expected[i]=61
i=62:	read_buf[i]=255	expected[i]=62
i=63:	read_buf[i]=255	expected[i]=63
i=64:	read_buf[i]=170	expected[i]=64
i=65:	read_buf[i]=170	expected[i]=65
i=66:	read_buf[i]=170	expected[i]=66
i=67:	read_buf[i]=170	expected[i]=67
i=68:	read_buf[i]=170	expected[i]=68
i=69:	read_buf[i]=170	expected[i]=69
i=70:	read_buf[i]=170	expected[i]=70
i=71:	read_buf[i]=170	expected[i]=71
i=72:	read_buf[i]=170	expected[i]=72
i=73:	read_buf[i]=170	expected[i]=73
i=74:	read_buf[i]=170	expected[i]=74
i=75:	read_buf[i]=170	expected[i]=75
i=76:	read_buf[i]=170	expected[i]=76
i=77:	read_buf[i]=170	expected[i]=77
i=78:	read_buf[i]=170	expected[i]=78
i=79:	read_buf[i]=170	expected[i]=79
i=80:	read_buf[i]=170	expected[i]=80
i=81:	read_buf[i]=170	expected[i]=81
i=82:	read_buf[i]=170	expected[i]=82
i=83:	read_buf[i]=170	expected[i]=83
i=84:	read_buf[i]=170	expected[i]=84
i=85:	read_buf[i]=170	expected[i]=85
i=86:	read_buf[i]=170	expected[i]=86
i=87:	read_buf[i]=170	expected[i]=87
i=88:	read_buf[i]=170	expected[i]=88
i=89:	read_buf[i]=170	expected[i]=89
i=90:	read_buf[i]=170	expected[i]=90
i=91:	read_buf[i]=170	expected[i]=91
i=92:	read_buf[i]=170	expected[i]=92
i=93:	read_buf[i]=170	expected[i]=93
i=94:	read_buf[i]=170	expected[i]=94
i=95:	read_buf[i]=170	expected[i]=95
i=96:	read_buf[i]=170	expected[i]=96
i=97:	read_buf[i]=170	expected[i]=97
i=98:	read_buf[i]=170	expected[i]=98
i=99:	read_buf[i]=170	expected[i]=99
i=100:	read_buf[i]=170	expected[i]=100
i=101:	read_buf[i]=170	expected[i]=101
i=102:	read_buf[i]=170	expected[i]=102
i=103:	read_buf[i]=170	expected[i]=103
i=104:	read_buf[i]=170	expected[i]=104
i=105:	read_buf[i]=170	expected[i]=105
i=106:	read_buf[i]=170	expected[i]=106
i=107:	read_buf[i]=170	expected[i]=107
i=108:	read_buf[i]=170	expected[i]=108
i=109:	read_buf[i]=170	expected[i]=109
i=110:	read_buf[i]=170	expected[i]=110
i=111:	read_buf[i]=170	expected[i]=111
i=112:	read_buf[i]=170	expected[i]=112
i=113:	read_buf[i]=170	expected[i]=113
i=114:	read_buf[i]=170	expected[i]=114
i=115:	read_buf[i]=170	expected[i]=115
i=116:	read_buf[i]=170	expected[i]=116
i=117:	read_buf[i]=170	expected[i]=117
i=118:	read_buf[i]=170	expected[i]=118
i=119:	read_buf[i]=170	expected[i]=119
i=120:	read_buf[i]=170	expected[i]=120
i=121:	read_buf[i]=170	expected[i]=121
i=122:	read_buf[i]=170	expected[i]=122
i=123:	read_buf[i]=170	expected[i]=123
i=124:	read_buf[i]=170	expected[i]=124
i=125:	read_buf[i]=170	expected[i]=125
i=126:	read_buf[i]=170	expected[i]=126
i=127:	read_buf[i]=170	expected[i]=127
i=128:	read_buf[i]=170	expected[i]=128
i=129:	read_buf[i]=170	expected[i]=129
i=130:	read_buf[i]=170	expected[i]=130
i=131:	read_buf[i]=170	expected[i]=131
i=132:	read_buf[i]=170	expected[i]=132
i=133:	read_buf[i]=170	expected[i]=133
i=134:	read_buf[i]=170	expected[i]=134
i=135:	read_buf[i]=170	expected[i]=135
i=136:	read_buf[i]=170	expected[i]=136
i=137:	read_buf[i]=170	expected[i]=137
i=138:	read_buf[i]=170	expected[i]=138
i=139:	read_buf[i]=170	expected[i]=139
i=140:	read_buf[i]=170	expected[i]=140
i=141:	read_buf[i]=170	expected[i]=141
i=142:	read_buf[i]=170	expected[i]=142
i=143:	read_buf[i]=170	expected[i]=143
i=144:	read_buf[i]=170	expected[i]=144
i=145:	read_buf[i]=170	expected[i]=145
i=146:	read_buf[i]=170	expected[i]=146
i=147:	read_buf[i]=170	expected[i]=147
i=148:	read_buf[i]=170	expected[i]=148
i=149:	read_buf[i]=170	expected[i]=149
i=150:	read_buf[i]=170	expected[i]=150
i=151:	read_buf[i]=170	expected[i]=151
i=152:	read_buf[i]=170	expected[i]=152
i=153:	read_buf[i]=170	expected[i]=153
i=154:	read_buf[i]=170	expected[i]=154
i=155:	read_buf[i]=170	expected[i]=155
i=156:	read_buf[i]=170	expected[i]=156
i=157:	read_buf[i]=170	expected[i]=157
i=158:	read_buf[i]=170	expected[i]=158
i=159:	read_buf[i]=170	expected[i]=159
i=160:	read_buf[i]=170	expected[i]=160
i=161:	read_buf[i]=170	expected[i]=161
i=162:	read_buf[i]=170	expected[i]=162
i=163:	read_buf[i]=170	expected[i]=163
i=164:	read_buf[i]=170	expected[i]=164
i=165:	read_buf[i]=170	expected[i]=165
i=166:	read_buf[i]=170	expected[i]=166
i=167:	read_buf[i]=170	expected[i]=167
i=168:	read_buf[i]=170	expected[i]=168
i=169:	read_buf[i]=170	expected[i]=169
i=171:	read_buf[i]=170	expected[i]=171
i=172:	read_buf[i]=170	expected[i]=172
i=173:	read_buf[i]=170	expected[i]=173
i=174:	read_buf[i]=170	expected[i]=174
i=175:	read_buf[i]=170	expected[i]=175
i=176:	read_buf[i]=170	expected[i]=176
i=177:	read_buf[i]=170	expected[i]=177
i=178:	read_buf[i]=170	expected[i]=178
i=179:	read_buf[i]=170	expected[i]=179
i=180:	read_buf[i]=170	expected[i]=180
i=181:	read_buf[i]=170	expected[i]=181
i=182:	read_buf[i]=170	expected[i]=182
i=183:	read_buf[i]=170	expected[i]=183
i=184:	read_buf[i]=170	expected[i]=184
i=185:	read_buf[i]=170	expected[i]=185
i=186:	read_buf[i]=170	expected[i]=186
i=187:	read_buf[i]=170	expected[i]=187
i=188:	read_buf[i]=170	expected[i]=188
i=189:	read_buf[i]=170	expected[i]=189
i=190:	read_buf[i]=170	expected[i]=190
i=191:	read_buf[i]=170	expected[i]=191
i=192:	read_buf[i]=170	expected[i]=192
i=193:	read_buf[i]=170	expected[i]=193
i=194:	read_buf[i]=170	expected[i]=194
i=195:	read_buf[i]=170	expected[i]=195
i=196:	read_buf[i]=170	expected[i]=196
i=197:	read_buf[i]=170	expected[i]=197
i=198:	read_buf[i]=170	expected[i]=198
i=199:	read_buf[i]=170	expected[i]=199
i=200:	read_buf[i]=170	expected[i]=200
i=201:	read_buf[i]=170	expected[i]=201
i=202:	read_buf[i]=170	expected[i]=202
i=203:	read_buf[i]=170	expected[i]=203
i=204:	read_buf[i]=170	expected[i]=204
i=205:	read_buf[i]=170	expected[i]=205
i=206:	read_buf[i]=170	expected[i]=206
i=207:	read_buf[i]=170	expected[i]=207
i=208:	read_buf[i]=170	expected[i]=208
i=209:	read_buf[i]=170	expected[i]=209
i=210:	read_buf[i]=170	expected[i]=210
i=211:	read_buf[i]=170	expected[i]=211
i=212:	read_buf[i]=170	expected[i]=212
i=213:	read_buf[i]=170	expected[i]=213
i=214:	read_buf[i]=170	expected[i]=214
i=215:	read_buf[i]=170	expected[i]=215
i=216:	read_buf[i]=170	expected[i]=216
i=217:	read_buf[i]=170	expected[i]=217
i=218:	read_buf[i]=170	expected[i]=218
i=219:	read_buf[i]=170	expected[i]=219
i=220:	read_buf[i]=170	expected[i]=220
i=221:	read_buf[i]=170	expected[i]=221
i=222:	read_buf[i]=170	expected[i]=222
i=223:	read_buf[i]=170	expected[i]=223
i=224:	read_buf[i]=170	expected[i]=224
i=225:	read_buf[i]=170	expected[i]=225
i=226:	read_buf[i]=170	expected[i]=226
i=227:	read_buf[i]=170	expected[i]=227
i=228:	read_buf[i]=170	expected[i]=228
i=229:	read_buf[i]=170	expected[i]=229
i=230:	read_buf[i]=170	expected[i]=230
i=231:	read_buf[i]=170	expected[i]=231
i=232:	read_buf[i]=170	expected[i]=232
i=233:	read_buf[i]=170	expected[i]=233
i=234:	read_buf[i]=170	expected[i]=234
i=235:	read_buf[i]=170	expected[i]=235
i=236:	read_buf[i]=170	expected[i]=236
i=237:	read_buf[i]=170	expected[i]=237
i=238:	read_buf[i]=170	expected[i]=238
i=239:	read_buf[i]=170	expected[i]=239
i=240:	read_buf[i]=170	expected[i]=240
i=241:	read_buf[i]=170	expected[i]=241
i=242:	read_buf[i]=170	expected[i]=242
i=243:	read_buf[i]=170	expected[i]=243
i=244:	read_buf[i]=170	expected[i]=244
i=245:	read_buf[i]=170	expected[i]=245
i=246:	read_buf[i]=170	expected[i]=246
i=247:	read_buf[i]=170	expected[i]=247
i=248:	read_buf[i]=170	expected[i]=248
i=249:	read_buf[i]=170	expected[i]=249
i=250:	read_buf[i]=170	expected[i]=250
i=251:	read_buf[i]=170	expected[i]=251
i=252:	read_buf[i]=170	expected[i]=252
i=253:	read_buf[i]=170	expected[i]=253
i=254:	read_buf[i]=170	expected[i]=254
i=255:	read_buf[i]=170	expected[i]=0
i=256:	read_buf[i]=170	expected[i]=1
i=257:	read_buf[i]=170	expected[i]=2
i=258:	read_buf[i]=170	expected[i]=3
i=259:	read_buf[i]=170	expected[i]=4
i=260:	read_buf[i]=170	expected[i]=5
i=261:	read_buf[i]=170	expected[i]=6
i=262:	read_buf[i]=170	expected[i]=7
i=263:	read_buf[i]=170	expected[i]=8
i=264:	read_buf[i]=170	expected[i]=9
i=265:	read_buf[i]=170	expected[i]=10
i=266:	read_buf[i]=170	expected[i]=11
i=267:	read_buf[i]=170	expected[i]=12
i=268:	read_buf[i]=170	expected[i]=13
i=269:	read_buf[i]=170	expected[i]=14
i=270:	read_buf[i]=170	expected[i]=15
i=271:	read_buf[i]=170	expected[i]=16
i=272:	read_buf[i]=170	expected[i]=17
i=273:	read_buf[i]=170	expected[i]=18
i=274:	read_buf[i]=170	expected[i]=19
i=275:	read_buf[i]=170	expected[i]=20
i=276:	read_buf[i]=170	expected[i]=21
i=277:	read_buf[i]=170	expected[i]=22
i=278:	read_buf[i]=170	expected[i]=23
i=279:	read_buf[i]=170	expected[i]=24
i=280:	read_buf[i]=170	expected[i]=25
i=281:	read_buf[i]=170	expected[i]=26
i=282:	read_buf[i]=170	expected[i]=27
i=283:	read_buf[i]=170	expected[i]=28
i=284:	read_buf[i]=170	expected[i]=29
i=285:	read_buf[i]=170	expected[i]=30
i=286:	read_buf[i]=170	expected[i]=31
i=287:	read_buf[i]=170	expected[i]=32
i=288:	read_buf[i]=170	expected[i]=33
i=289:	read_buf[i]=170	expected[i]=34
i=290:	read_buf[i]=170	expected[i]=35
i=291:	read_buf[i]=170	expected[i]=36
i=292:	read_buf[i]=170	expected[i]=37
i=293:	read_buf[i]=170	expected[i]=38
i=294:	read_buf[i]=170	expected[i]=39
i=295:	read_buf[i]=170	expected[i]=40
i=296:	read_buf[i]=170	expected[i]=41
i=297:	read_buf[i]=170	expected[i]=42
i=298:	read_buf[i]=170	expected[i]=43
i=299:	read_buf[i]=170	expected[i]=44
i=300:	read_buf[i]=170	expected[i]=45
i=301:	read_buf[i]=170	expected[i]=46
i=302:	read_buf[i]=170	expected[i]=47
i=303:	read_buf[i]=170	expected[i]=48
i=304:	read_buf[i]=170	expected[i]=49
i=305:	read_buf[i]=170	expected[i]=50
i=306:	read_buf[i]=170	expected[i]=51
i=307:	read_buf[i]=170	expected[i]=52
i=308:	read_buf[i]=170	expected[i]=53
i=309:	read_buf[i]=170	expected[i]=54
i=310:	read_buf[i]=170	expected[i]=55
i=311:	read_buf[i]=170	expected[i]=56
i=312:	read_buf[i]=170	expected[i]=57
i=313:	read_buf[i]=170	expected[i]=58
i=314:	read_buf[i]=170	expected[i]=59
i=315:	read_buf[i]=170	expected[i]=60
i=316:	read_buf[i]=170	expected[i]=61
i=317:	read_buf[i]=170	expected[i]=62
i=318:	read_buf[i]=170	expected[i]=63
i=319:	read_buf[i]=170	expected[i]=64
i=320:	read_buf[i]=170	expected[i]=65
i=321:	read_buf[i]=170	expected[i]=66
i=322:	read_buf[i]=170	expected[i]=67
i=323:	read_buf[i]=170	expected[i]=68
i=324:	read_buf[i]=170	expected[i]=69
i=325:	read_buf[i]=170	expected[i]=70
i=326:	read_buf[i]=170	expected[i]=71
i=327:	read_buf[i]=170	expected[i]=72
i=328:	read_buf[i]=170	expected[i]=73
i=329:	read_buf[i]=170	expected[i]=74
i=330:	read_buf[i]=170	expected[i]=75
i=331:	read_buf[i]=170	expected[i]=76
i=332:	read_buf[i]=170	expected[i]=77
i=333:	read_buf[i]=170	expected[i]=78
i=334:	read_buf[i]=170	expected[i]=79
i=335:	read_buf[i]=170	expected[i]=80
i=432:	read_buf[i]=170	expected[i]=177
i=433:	read_buf[i]=170	expected[i]=178
i=434:	read_buf[i]=170	expected[i]=179
i=435:	read_buf[i]=170	expected[i]=180
i=436:	read_buf[i]=170	expected[i]=181
i=437:	read_buf[i]=170	expected[i]=182
i=438:	read_buf[i]=170	expected[i]=183
i=439:	read_buf[i]=170	expected[i]=184
i=440:	read_buf[i]=170	expected[i]=185
i=441:	read_buf[i]=170	expected[i]=186
i=442:	read_buf[i]=170	expected[i]=187
i=443:	read_buf[i]=170	expected[i]=188
i=444:	read_buf[i]=170	expected[i]=189
i=445:	read_buf[i]=170	expected[i]=190
i=446:	read_buf[i]=170	expected[i]=191
i=447:	read_buf[i]=170	expected[i]=192
i=448:	read_buf[i]=170	expected[i]=193
i=449:	read_buf[i]=170	expected[i]=194
i=450:	read_buf[i]=170	expected[i]=195
i=451:	read_buf[i]=170	expected[i]=196
i=452:	read_buf[i]=170	expected[i]=197
i=453:	read_buf[i]=170	expected[i]=198
i=454:	read_buf[i]=170	expected[i]=199
i=455:	read_buf[i]=170	expected[i]=200
i=456:	read_buf[i]=170	expected[i]=201
i=457:	read_buf[i]=170	expected[i]=202
i=458:	read_buf[i]=170	expected[i]=203
i=459:	read_buf[i]=170	expected[i]=204
i=460:	read_buf[i]=170	expected[i]=205
i=461:	read_buf[i]=170	expected[i]=206
i=462:	read_buf[i]=170	expected[i]=207
i=463:	read_buf[i]=170	expected[i]=208
i=464:	read_buf[i]=170	expected[i]=209
i=465:	read_buf[i]=170	expected[i]=210
i=466:	read_buf[i]=170	expected[i]=211
i=467:	read_buf[i]=170	expected[i]=212
i=468:	read_buf[i]=170	expected[i]=213
i=469:	read_buf[i]=170	expected[i]=214
i=470:	read_buf[i]=170	expected[i]=215
i=471:	read_buf[i]=170	expected[i]=216
i=472:	read_buf[i]=170	expected[i]=217
i=473:	read_buf[i]=170	expected[i]=218
i=474:	read_buf[i]=170	expected[i]=219
i=475:	read_buf[i]=170	expected[i]=220
i=476:	read_buf[i]=170	expected[i]=221
i=477:	read_buf[i]=170	expected[i]=222
i=478:	read_buf[i]=170	expected[i]=223
i=479:	read_buf[i]=170	expected[i]=224
i=480:	read_buf[i]=170	expected[i]=225
i=481:	read_buf[i]=170	expected[i]=226
i=482:	read_buf[i]=170	expected[i]=227
i=483:	read_buf[i]=170	expected[i]=228
i=484:	read_buf[i]=170	expected[i]=229
i=485:	read_buf[i]=170	expected[i]=230
i=486:	read_buf[i]=170	expected[i]=231
i=487:	read_buf[i]=170	expected[i]=232
i=488:	read_buf[i]=170	expected[i]=233
i=489:	read_buf[i]=170	expected[i]=234
i=490:	read_buf[i]=170	expected[i]=235
i=491:	read_buf[i]=170	expected[i]=236
i=492:	read_buf[i]=170	expected[i]=237
i=493:	read_buf[i]=170	expected[i]=238
i=494:	read_buf[i]=170	expected[i]=239
i=495:	read_buf[i]=170	expected[i]=240
i=496:	read_buf[i]=170	expected[i]=241
i=497:	read_buf[i]=170	expected[i]=242
i=498:	read_buf[i]=170	expected[i]=243
i=499:	read_buf[i]=170	expected[i]=244
i=500:	read_buf[i]=170	expected[i]=245
i=501:	read_buf[i]=170	expected[i]=246
i=502:	read_buf[i]=170	expected[i]=247
i=503:	read_buf[i]=170	expected[i]=248
i=504:	read_buf[i]=170	expected[i]=249
i=505:	read_buf[i]=170	expected[i]=250
i=506:	read_buf[i]=170	expected[i]=251
i=507:	read_buf[i]=170	expected[i]=252
i=508:	read_buf[i]=170	expected[i]=253
i=509:	read_buf[i]=170	expected[i]=254
i=510:	read_buf[i]=170	expected[i]=255
i=511:	read_buf[i]=170	expected[i]=0

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/flash/common/src/main.c:308: flash_driver_test_flash_erase: (comparison_result is false)
Write operation failed
 FAIL - test_flash_erase in 1.441 seconds
===================================================================
START - test_flash_fill
Test will run on device flash-controller@40020000

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/flash/common/src/main.c:248: flash_driver_test_flash_fill: (i not equal to EXPECTED_SIZE)
Expected device to be filled wth 0xaa
 FAIL - test_flash_fill in 0.070 seconds
===================================================================
START - test_flash_flatten
Test will run on device flash-controller@40020000

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/flash/common/src/main.c:280: flash_driver_test_flash_flatten: (i not equal to EXPECTED_SIZE)
Expected device to be filled wth 0xaa
 FAIL - test_flash_flatten in 0.070 seconds
===================================================================
START - test_flash_page_layout
Test will run on device flash-controller@40020000
start_offset=0x76000	size=4096	index=118
page_count=128
 PASS - test_flash_page_layout in 0.016 seconds
===================================================================
START - test_get_size
Test will run on device flash-controller@40020000
 SKIP - test_get_size in 0.009 seconds
===================================================================
START - test_read_unaligned_address
Test will run on device flash-controller@40020000
 PASS - test_read_unaligned_address in 0.020 seconds
===================================================================
START - test_supply_gpios_control
Test will run on device flash-controller@40020000
 SKIP - test_supply_gpios_control in 0.011 seconds
===================================================================
TESTSUITE flash_driver failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  50.00% [flash_driver]: pass = 3, fail = 3, skip = 2, total = 8 duration = 1.728 seconds
 - PASS - [flash_driver.test_flash_copy] duration = 0.091 seconds
 - FAIL - [flash_driver.test_flash_erase] duration = 1.441 seconds
 - FAIL - [flash_driver.test_flash_fill] duration = 0.070 seconds
 - FAIL - [flash_driver.test_flash_flatten] duration = 0.070 seconds
 - PASS - [flash_driver.test_flash_page_layout] duration = 0.016 seconds
 - SKIP - [flash_driver.test_get_size] duration = 0.009 seconds
 - PASS - [flash_driver.test_read_unaligned_address] duration = 0.020 seconds
 - SKIP - [flash_driver.test_supply_gpios_control] duration = 0.011 seconds



```

**Environment (please complete the following information):**
 - OS: (e.g. Linux ): Linux
 - Toolchain (e.g Zephyr SDK): zephyr
 - Commit SHA or Version used: v4.3.0-rc1

some more findings

```
Previous Test Contamination: The 0xAA pattern comes from test_flash_fill() which runs before this test
Insufficient Erase: Flash wasn't properly erased before writing
Write Alignment: Kinetis flash requires 8-byte aligned writes
Flash Controller State: FTFE controller might be in wrong state
```

### PR DESCRIPTION
**Pull request by mohittalwar23**
drivers: flash: mcux: clear caches after erase and write on Kinetis

Kinetis ke1xf (twr_ke18f/mke18f16) and k8x (frdm_k82f) select
CONFIG_HAS_MCUX_CACHE but previously fell through to the no-op
clear_flash_caches() path, meaning caches were not invalidated
after flash erase or write operations.

After the FTFE controller completes an erase or write, stale data
may remain in the instruction cache and (on some parts) the system
bus cache. Subsequent reads can return outdated values instead of
updated flash contents. This causes test_flash_erase,
test_flash_fill, and test_flash_flatten in
tests/drivers/flash/common to fail, with data read back as stale
values (e.g. 0xAA from a prior fill).

Rebased on top of #105918 and updated to use Zephyr's generic cache
API (sys_cache_instr_invd_all() / sys_cache_data_invd_all()) for
cache invalidation. This keeps the flash driver SoC-agnostic and
relies on the cache driver (e.g. LMEM) for hardware-specific
handling.

Fixes #98487

### CODE REVIEW

File: drivers/flash/soc_flash_mcux.c [hunk 1]
```diff
@@ -160,6 +160,16 @@ static void clear_flash_caches(void)
 {
 	SYSCON->LPCAC_CTRL |= SYSCON_LPCAC_CTRL_DIS_LPCAC(1U);
 }
+#elif defined(CONFIG_HAS_MCUX_CACHE)
+static void clear_flash_caches(void)
+{
+	/* Invalidate code cache (LMEM PCCCR) */
```
Comment (hakehuang) [inline drivers/flash/soc_flash_mcux.c]: This new `CONFIG_HAS_MCUX_CACHE` path only invalidates `LMEM->PCCCR` (instruction/code cache). It does **not** invalidate the LMEM system-bus cache (`PSCCR`), so it doesn't fully match the PR description and may still leave stale flash data on parts that actually cache flash reads through the system side (for example K82-class devices).

If we want to keep the flash driver at the generic level, I think the better direction is the one discussed in-thread: use `sys_cache_instr_invd_all()` / `sys_cache_data_invd_all()` here and add the LMEM-specific `PSCCR` handling in `drivers/cache/cache_nxp_lmem_cache.c`.

One more thing to check if you go that route: these failing Kinetis SoCs currently select `HAS_MCUX_CACHE`, but I don't see them selecting `HAS_MCUX_LMEM_CACHE`, and `CONFIG_CACHE_NXP_LMEM_CACHE` depends on the latter. So the SoC/Kconfig wiring may also need updating, otherwise the generic cache-driver path won't become active on the affected boards.

**Review by hakehuang — COMMENTED** [review]
Thanks for working on this. I think the current version is heading in the right direction in terms of diagnosing the stale-cache behavior, but I don't think the implementation is complete enough to merge yet.

Main concern:
- the new `CONFIG_HAS_MCUX_CACHE` branch in `soc_flash_mcux.c` only invalidates LMEM `PCCCR` (instruction/code cache)
- it does not invalidate LMEM `PSCCR` / system-bus cache, so it may still leave stale flash contents visible on affected parts
- that also means it doesn't fully match the PR description, which says both code and system caches should be invalidated

I agree with the direction suggested in the thread: keep `soc_flash_mcux.c` at the generic cache-API level and move LMEM register details into `drivers/cache/cache_nxp_lmem_cache.c` (using `sys_cache_instr_invd_all()` / `sys_cache_data_invd_all()` from the flash driver).

Also worth checking as part of that follow-up: the affected Kinetis SoCs seem to select `HAS_MCUX_CACHE`, but not obviously `HAS_MCUX_LMEM_CACHE`, while `CONFIG_CACHE_NXP_LMEM_CACHE` depends on the latter. So some Kconfig/SoC wiring may be needed before the generic LMEM cache driver can actually cover these boards.

Because of that, I'm leaving this as comment-only for now rather than approving.

**Comment by Holt-Sun** [comment]
> What we tried and why it failed:
> 
> L1CACHE_InvalidateCodeCache() + L1CACHE_InvalidateSystemCache() — failed because fsl_cache.h isn't in the include path for these boards via the old mcux-sdk
> 
> Inline LMEM register writes worked to compile but register-level cache handling belongs in the cache driver, not the flash driver
> 
> Feedback:
> 
> Use Zephyr's generic cache API (sys_cache_instr_invd_all() / sys_cache_data_invd_all()) in the flash driver, and implement those in the LMEM cache driver
> 
> Where we are now:
> 
> drivers/cache/cache_nxp_lmem_cache.c already exists and implements cache_instr_invd_all() but is missing all data cache functions frdm_k82f has a system bus cache (FSL_FEATURE_LMEM_HAS_SYSTEMBUS_CACHE=1) that needs data cache functions added twr_ke18f has no system bus cache (FSL_FEATURE_LMEM_HAS_SYSTEMBUS_CACHE=0) so only instruction cache invalidation is needed
> 
> The fix:
> 
> drivers/cache/cache_nxp_lmem_cache.c : add data cache functions guarded by FSL_FEATURE_LMEM_HAS_SYSTEMBUS_CACHE
> 
> drivers/flash/soc_flash_mcux.c : replace our block with: #elif defined(CONFIG_CACHE_NXP_LMEM_CACHE) sys_cache_instr_invd_all(); sys_cache_data_invd_all();
> 
> Am I right ?

Broadly yes, that is the right direction, but I would keep soc_flash_mcux.c fully at the generic cache-API level rather than adding another LMEM-specific #elif defined(CONFIG_CACHE_NXP_LMEM_CACHE) branch there.

The prerequisite pieces are:
1. extend drivers/cache/cache_nxp_lmem_cache.c with LMEM data-cache ops, guarded by FSL_FEATURE_LMEM_HAS_SYSTEMBUS_CACHE, so K82-class parts cover both PCCCR and PSCCR while KE1x stays instruction-cache-only
2. update the affected SoC/Kconfig wiring so the generic LMEM cache-driver path is actually enabled on those boards
I split that prerequisite work into a separate PR here: https://github.com/zephyrproject-rtos/zephyr/pull/105918

Once that merged, this flash PR can switch to sys_cache_instr_invd_all() / sys_cache_data_invd_all() and leave the LMEM-specific register handling inside the cache driver, which is the part I think the review is asking for.

**Review by Holt-Sun — APPROVED** [review]

**Review by hakehuang — APPROVED** [review]

**Review by zejiang0jason — APPROVED** [review]
