### PR TITLE
bluetooth: OTS: Delay indications to system workqueue

### LINKED ISSUE #66023: OTS - OACP Indications sent before write rsp
**Describe the bug**
OTS test cases require that at least one object stored on the IUT is initialized as Current Object. This is achieved by Lower Tester performing procedure as desrcibed in section 4.2.4. of [OTS TS](https://www.bluetooth.org/docman/handlers/DownloadDoc.ashx?doc_id=309983). According to subsection 6. of this preamble procedure, "The IUT, after sending a Write Response to acknowledge the write to the Object List Control Point, sends an indication of the Object List Control Point characteristic.". Unfortunately, zephyr in a first place is sending indication of the OLCP characteristic followed by write response.

**To Reproduce**
Can be reproduced with AutoPTS

**Expected behavior**
According to [OTP spec](https://www.bluetooth.org/docman/handlers/DownloadDoc.ashx?doc_id=309936) section 4.4.4.: "An OLCP or OACP operation is started when the ATT Write Response is received from the Object Server as a result of the Object Client writing an Op Code to a control point to perform some desired action. The control point operation ends when the Object Server sends an indication to the Object Client with the Op Code set to Response Code.". This suggests that correct order while performing OLCP or OACP operations should be Write Response First, Indication second.

**Impact**
Unable to pass any OTS test case that require operations on objects. 

**Logs and console output**
[OTS_SR_CR_BV_02_C_2023_12_01_10_52_20.zip](https://github.com/zephyrproject-rtos/zephyr/files/13524934/OTS_SR_CR_BV_02_C_2023_12_01_10_52_20.zip)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Toolchain: Zephyr SDK 0.16.4
 - [PR#66022](https://github.com/zephyrproject-rtos/zephyr/pull/66022)

### PR DESCRIPTION
**Pull request by sjanc**
OTS requires that indications about state change are sent after response to ATT Write.

OTS Specification p.4.4.4.: "An OLCP or OACP operation is started when the ATT Write Response is received from the Object Server as a result of the Object Client writing an Op Code to a control point to perform some desired action. The control point operation ends when the Object Server sends an indication to the Object Client
 with the Op Code set to Response Code."

fixes https://github.com/zephyrproject-rtos/zephyr/issues/66023

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr OTS

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/71679#issuecomment-2065934502 after 09:28:40.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>OTS     OTS/SR/CON/BV-03-C              INCONC<br>OTS     OTS/SR/CR/BV-01-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/CR/BV-02-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/CR/BV-03-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/CR/BV-04-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/CR/BV-07-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/CR/BV-08-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/CW/BV-01-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/DLO/BV-01-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-03-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-04-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-05-C              FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-06-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-07-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-08-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-09-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-13-C              INCONC<br>OTS     OTS/SR/OASP/BV-01-C             FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OASP/BV-02-C             FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OASP/BV-03-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OASP/BV-04-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OASP/BV-05-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OASP/BV-06-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OC/BV-01-C               INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OLE/BI-01-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OLE/BI-03-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OLE/BI-04-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OLSP/BV-01-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OLSP/BV-02-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OME/BI-01-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OTD/BI-01-C              FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OTD/BI-04-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OTD/BI-05-C              INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/SGGIT/CHA/BV-03-C        FAIL<br>OTS     OTS/SR/SGGIT/CHA/BV-15-C        FAIL</details>
<details><summary>Successful tests</summary>OTS     OTS/SR/CON/BV-01-C              PASS<br>OTS     OTS/SR/CON/BV-02-C              PASS<br>OTS     OTS/SR/OAE/BI-01-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OAE/BI-12-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/OLE/BI-05-C              PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023<br>OTS     OTS/SR/SGGIT/CHA/BV-01-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-04-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-05-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-10-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-11-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-13-C        PASS<br>OTS     OTS/SR/SGGIT/CHA/BV-14-C        PASS<br>OTS     OTS/SR/SGGIT/SER/BV-01-C        PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run zephyr OTS OTS/SR/CR/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/71679#issuecomment-2066180266 after 11:24:56.

**Comment by sjanc** [comment]
#AutoPTS run zephyr OTS/SR/CR/BV-01-C

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>OTS     OTS/SR/CR/BV-01-C               FAIL - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023</details>

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/71679#issuecomment-2066286796 after 12:29:49.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>OTS     OTS/SR/CR/BV-01-C               PASS - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/66023</details>

**Comment by sjanc** [comment]
#AutoPTS run zephyr OTS

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/71679#issuecomment-2066340686 after 13:05:08.

**Comment by sjanc** [comment]
Remaining failing tests with are not related to interleaving write response and indications, and fails on subsequent steps of tests. Those will be handled separartely.

File: subsys/bluetooth/services/ots/ots.c [hunk 1]
```diff
@@ -442,6 +442,22 @@ void *bt_ots_svc_decl_get(struct bt_ots *ots)
...
+	bt_gatt_indicate(NULL, &ots->oacp_ind.params);
+}
+
+static void olcp_indicate_work_handler(struct k_work *work)
+{
+	struct bt_gatt_ots_indicate *ind = CONTAINER_OF(work, struct bt_gatt_ots_indicate, work);
+	struct bt_ots *ots = CONTAINER_OF(ind, struct bt_ots, olcp_ind);
+
+	bt_gatt_indicate(NULL, &ots->olcp_ind.params);
+}
```
Comment (Thalley) [inline subsys/bluetooth/services/ots/ots.c:459]: Since delaying indications does guard us from new request, we might need to prevent any OACP or OLCP requests while these are pending. 

If we get a new request in before these are handled (not unlikely if EATT is enabled), then we will overwrite these, and not send the previous ones, right?

**Review by Thalley — COMMENTED** [review]
Change looks good, but I think we need to ensure that we don't allow new requests before these indications are sent to the GATT/ATT layer.

File: subsys/bluetooth/services/ots/ots.c (hunk 1 above)
Comment (sjanc) [reply subsys/bluetooth/services/ots/ots.c:459]: OK, I've added check and since spec doesn't mention on how this should be handled I used BT_ATT_ERR_PROCEDURE_IN_PROGRESS (0xFE) error code.

**Review by Thalley — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/services/ots/ots_oacp.c [hunk 2]
```diff
@@ -699,6 +690,11 @@ ssize_t bt_gatt_ots_oacp_write(struct bt_conn *conn,
 		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
 	}
 
+	if (k_work_is_pending(&ots->oacp_ind.work)) {
+		LOG_ERR("OACP Write received before indication sent");
+		return BT_GATT_ERR(BT_ATT_ERR_PROCEDURE_IN_PROGRESS);
+	}
+
```
Comment (alwa-nordic) [inline subsys/bluetooth/services/ots/ots_oacp.c:697]: I recommend removing this check. It is not our job to police the remote. (That's the job of Bluetooth qualification.) And this if-statement can dangerously be mistaken to be a guarantee the notification has been sent.

**Review by alwa-nordic — APPROVED** [review]
The recommendation I give is optional and can be a follow-up PR.

File: subsys/bluetooth/services/ots/ots_oacp.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/services/ots/ots_oacp.c:697]: > I recommend removing this check. It is not our job to police the remote. (That's the job of Bluetooth qualification.) And this if-statement can dangerously be mistaken to be a guarantee the notification has been sent.

The spec does not say anything about this though. Write requests and indications are not related. The point of this check is that we only ever have 1 pending indication on our side, so we avoid implementing a queue
