### PR TITLE
net: tcp: Fix SYN handling after connection is established

### LINKED ISSUE #48465: net: tcp: SYN flag received after connection is established should result in connection reset
**Describe the bug**
According to [RFC 793](https://www.rfc-editor.org/rfc/rfc793.txt), receiving a SYN flag after connection has been established is an error and should results in RST response and connection being closed:
```
      SYN-RECEIVED
      ESTABLISHED STATE
      FIN-WAIT STATE-1
      FIN-WAIT STATE-2
      CLOSE-WAIT STATE
      CLOSING STATE
      LAST-ACK STATE
      TIME-WAIT STATE

        If the SYN is in the window it is an error, send a reset, any
        outstanding RECEIVEs and SEND should receive "reset" responses,
        all segment queues should be flushed, the user should also
        receive an unsolicited general "connection reset" signal, enter
        the CLOSED state, delete the TCB, and return.
```

Currently it's not the case, and the SYN flag is ignored by the TCP stack in such case.

**To Reproduce**
No easy way to reproduce, as it requires to inject a malformed packet into the connection. The issue was reported by one of the Maxwell Pro tests.

**Expected behavior**
RFC compliance.

**Impact**
Could be a problem for example if peer goes down, and after reset tries to establish a new connection from the same port.

### PR DESCRIPTION
**Pull request by rlubos**
According to RFC 793, ch 3.9 Event Processing, receving SYN flag after
the connection has been established is an error codition:

    If the SYN is in the window it is an error, send a reset, any
    outstanding RECEIVEs and SEND should receive "reset" responses,
    all segment queues should be flushed, the user should also
    receive an unsolicited general "connection reset" signal, enter
    the CLOSED state, delete the TCB, and return."

Currently TCP stack ignored such event, causing interoperability test
failures. Fix this, by verifying if the SYN flag is set in a packet in
any state other than TCP_LISTEN and TCP_SYN_SENT.

Fixes #48465

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

File: subsys/net/ip/tcp.c [hunk 1]
```diff
@@ -1962,6 +1962,21 @@ static enum net_verdict tcp_in(struct tcp *conn, struct net_pkt *pkt)
 		goto next_state;
 	}
 
+	if (th && (conn->state != TCP_LISTEN) && (conn->state != TCP_SYN_SENT) &&
+	    tcp_validate_seq(conn, th) && FL(&fl, &, SYN)) {
+		/* According to RFC 793, ch 3.9 Event Processing, receiving SYN
+		 * once the connection has been established is an error
+		 * condition, reset should be sent and connection closed.
+		 */
+		NET_ERR("conn: %p, SYN received in %s state, dropping connection",
```
Comment (jukkar) [inline subsys/net/ip/tcp.c:1971]: Are you sure we want to flag this as an error, after all it is not an error in our code but an error in a packet we receive. This could cause huge load in our system if we receive big number of these (denial of service). I would suggest a normal debug message here.

Comment (rlubos) [reply subsys/net/ip/tcp.c]: Good point, I've lowered the log level to debug.

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by ssharks** [comment]
Hmmm... I think a SYN should be allowed in SYN-ACK state as well, in case the reply is lost in transmission.

**Comment by rlubos** [comment]
> Hmmm... I think a SYN should be allowed in TCP_SYN_RECEIVED state as well, in case the reply is lost in transmission.

Duplicated SYN, in this case, should be covered by the `tcp_validate_seq(conn, th)` check - such a duplicate would have SEQ field outside of the current window, so the RST won't be sent in this case. RFC 793 marks `SYN-RECEIVED` state explicitly as incorrect in case SEQ is within the current window.

**Comment by ssharks** [comment]
Ok, thanks for the explanation
