### PR TITLE
Fix k_sleep() timeouts in net

### LINKED ISSUE #7657: Invalid argument passed to k_sleep
https://github.com/zephyrproject-rtos/zephyr/blob/0b76b12837deb995077bf026de01a6e9a9e50dfe/tests/kernel/semaphore/semaphore/src/main.c#L202

Probably confised with K_MSEC.

Present in multiple places.
Check also:
https://github.com/zephyrproject-rtos/zephyr/blob/0b76b12837deb995077bf026de01a6e9a9e50dfe/tests/net/traffic_class/src/main.c#L516

https://github.com/zephyrproject-rtos/zephyr/blob/0b76b12837deb995077bf026de01a6e9a9e50dfe/subsys/net/lib/app/net_app.c#L1300

### PR DESCRIPTION
**Pull request by jukkar**
This converts remaining MSEC() calls to K_MSEC() in networking code.
Also convert MSEC_PER_SEC to K_SECONDS() as that is more intuitive.

Fixes #7657

### CODE REVIEW

File: subsys/net/ip/ipv6.c [hunk 1]
```diff
@@ -65,7 +65,7 @@ static void nd_reachable_timeout(struct k_work *work);
 
 #define MAX_MULTICAST_SOLICIT 3
 #define MAX_UNICAST_SOLICIT   3
-#define DELAY_FIRST_PROBE_TIME (5 * MSEC_PER_SEC) /* RFC 4861 ch 10 */
+#define DELAY_FIRST_PROBE_TIME K_SECONDS(5) /* RFC 4861 ch 10 */
 #define RETRANS_TIMER 1000 /* in ms, RFC 4861 ch 10 */
```
Comment (pfalcon) [inline subsys/net/ip/ipv6.c]: We have more "raw" values like this, IMHO makes sense to convert them within the scope of this PR too.

File: subsys/net/ip/l2/ieee802154/ieee802154_fragment.c [hunk 2]
```diff
@@ -26,8 +26,8 @@
 #include "6lo.h"
 #include "6lo_private.h"
 
-#define FRAG_REASSEMBLY_TIMEOUT (MSEC_PER_SEC * \
-				 CONFIG_NET_L2_IEEE802154_REASSEMBLY_TIMEOUT)
+#define FRAG_REASSEMBLY_TIMEOUT \
+	K_SECONDS(CONFIG_NET_L2_IEEE802154_REASSEMBLY_TIMEOUT)
```
Comment (pfalcon) [inline subsys/net/ip/l2/ieee802154/ieee802154_fragment.c]: Should convert this to msecs for better granularity. In a separate PR apparently.

File: subsys/net/ip/rpl.c [hunk 3]
```diff
@@ -1642,8 +1642,7 @@ static void set_dao_lifetime_timer(struct net_rpl_instance *instance)
 		u32_t expiration_time;
 
 		expiration_time = (u32_t)instance->default_lifetime *
-			(u32_t)instance->lifetime_unit *
-			MSEC_PER_SEC / 2;
+			(u32_t)instance->lifetime_unit * K_SECONDS(1) / 2;
```
Comment (pfalcon) [inline subsys/net/ip/rpl.c]: Maybe K_MSEC(500) after all?

**Review by pfalcon — COMMENTED** [review]
Good! (Was in my queue too ;-) )

Suggested to over "raw" time-related values in net/ip/ and convert them too.

File: subsys/net/buf.c [hunk 4]
```diff
@@ -289,11 +289,11 @@ struct net_buf *net_buf_alloc_len(struct net_buf_pool *pool, size_t size,
 #if defined(CONFIG_NET_BUF_POOL_USAGE)
 			NET_BUF_WARN("%s():%d: Pool %s blocked for %u secs",
 				     func, line, pool->name,
-				     (k_uptime_get_32() - ref) / MSEC_PER_SEC);
+				     (k_uptime_get_32() - ref) / K_SECONDS(1));
 #else
```
Comment (jhedberg) [inline subsys/net/buf.c]: The rest of the fixes in this PR seem good, but I'm not sure I agree with this. The way the K_SECONDS, K_MSEC, K_MINUTES, K_HOURS macros work, is that you don't need to know what the "native" representation of time is that's passed to the kernel APIs. It might be milliseconds, but it could be something else that the macros convert the input to. The above change assumes that the macro converts to milliseconds, whereas with MSEC_PER_SEC it's at least explicit.

File: subsys/net/buf.c [hunk 5]
```diff
@@ -289,11 +289,11 @@ struct net_buf *net_buf_alloc_len(struct net_buf_pool *pool, size_t size,
...
 			NET_BUF_WARN("%s():%d: Pool %p blocked for %u secs",
 				     func, line, pool,
-				     (k_uptime_get_32() - ref) / MSEC_PER_SEC);
+				     (k_uptime_get_32() - ref) / K_SECONDS(1));
 #endif
```
Comment (jhedberg) [inline subsys/net/buf.c]: Same here.

File: subsys/net/buf.c (hunk 4 above)
Comment (pfalcon) [reply subsys/net/buf.c]: +1 to @jhedberg's comment, I'd also say that division by MSEC_PER_SEC is easier to understand than division by K_SECONDS(1).

File: subsys/net/ip/rpl.c (hunk 3 above)
Comment (jukkar) [reply subsys/net/ip/rpl.c]: The comment few lines above says "Set up another DAO within half the expiration time" so in this respect it makes sense to leave the division in place.

File: subsys/net/buf.c (hunk 4 above)
Comment (jukkar) [reply subsys/net/buf.c]: Ok, lets leave MSEC_PER_SEC there then.

**Comment by jukkar** [comment]
Updated according to comments.

**Review by nashif — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]
