### PR TITLE
Bluetooth: host: Fix RPA timeout expiration 

### LINKED ISSUE #51208: Bluetooth: Host: `bt_le_oob_get_local` gives incorrect address
`bt_le_oob_get_local` gives incorrect address when using the extended advertisement code paths. (i.e. `(IS_ENABLED(CONFIG_BT_EXT_ADV) && BT_DEV_FEAT_LE_EXT_ADV(bt_dev.le.features))` is true.)

_Originally posted by @joerchan in https://github.com/zephyrproject-rtos/zephyr/discussions/50967#discussioncomment-3850650_

When you start an advertiser using the legacy API (`bt_le_adv_*`) then the OOB information is provided by `bt_le_oob_get_local`. When you start an advertiseng using the extended API then the OOB informartion is provided by `bt_le_ext_adv_oob_get_local`.

The new bug now is that `bt_le_oob_get_local` does not return the RPA address of the advertiser.

You can verify this bug like this:
```bash
west build -b nrf52840dk_nrf52840 tests/bluetooth/shell  -- -DCONFIG_BT_PRIVACY=y -DCONFIG_BT_LOG_SNIFFER_INFO=y -DCONFIG_BT_RPA_TIMEOUT=30
```

Using the nRF Sniffer for Bluetooth LE.
Add the printed IRK to the sniffer, and select follow IRK.

```
uart:~$ bt advertise on
Advertising started
[00:00:10.378,570] <inf> bt_id: bt_id_set_adv_private_addr: RPA: 5E:0B:7D:F9:9A:D1
uart:~$ bt oob
OOB data:
addr                          random                           confirm                         
   4E:44:19:A9:44:12 (random) 015ce2d5e52416dfc3f54a562822b10d c47cb850fd05737e21eb502cd65c8003
[00:00:23.610,137] <inf> bt_id: bt_id_set_adv_private_addr: RPA: 6D:28:FE:FE:A3:61
[00:00:23.610,717] <inf> bt_id: bt_id_set_private_addr: RPA: 4E:44:19:A9:44:12
```

The advertiser starts using `5E:0B:7D:F9:9A:D1`. When calling `bt_le_oob_get_local` it returns `4E:44:19:A9:44:12 (random)`, but is advertising using `6D:28:FE:FE:A3:61`.

On zephyr 3.0.0 release this works as expected.

Reverting the fix https://github.com/zephyrproject-rtos/zephyr/commit/6c40427931dba65092d0eb050a2ed7e9e8069845 shows that the RPA is not updated, neither on calling bt_le_oob_get_local, or on an RPA timeout.

https://github.com/zephyrproject-rtos/zephyr/issues/51208#tasklist-block-11cca9a8-bf0c-4ea2-b69b-3116fb495c40

### LINKED ISSUE #51228: Bluetooth: Privacy in scan roles not updating RPA on timeout
**Describe the bug**
The scan roles scanner and initiator do not update their RPA on RPA timeout in the host when BT_EXT_ADV is enabled.

Reproduce:
```
west build -b nrf52833dk_nrf52833 tests/bluetooth/shell  -- \
-DCONFIG_BT_PRIVACY=y \
-DCONFIG_BT_LOG_SNIFFER_INFO=y \
-DCONFIG_BT_RPA_TIMEOUT=10

west flash --erase
```
Shell:
```
uart:~$ bt init
...
uart:~$ bt fal-add C9:B7:8A:A5:E8:2C (random) # scanners own identity address, to stop advertise reports 
uart:~$ bt scan on fal  # enable fal to receive no advertise reports
Bluetooth active scan enabled
[00:00:17.164,001] <inf> bt_id: bt_id_set_private_addr: RPA: 58:B5:62:46:FC:B9
```
RPA is only set when scan role is started.

Regression since: 4e924b6b1f4d8c9acd3fe2501b06572ddf4d4ed3

Behavior before (expected behavior)
```
uart:~$ bt fal-add C9:B7:8A:A5:E8:2C (random)
uart:~$ bt scan on fal
Bluetooth active scan enabled
[00:00:11.469,848] <inf> bt_id: RPA: 4D:1B:1C:52:19:E2
[00:00:21.470,367] <inf> bt_id: RPA: 62:BD:8E:06:02:F0
[00:00:31.470,855] <inf> bt_id: RPA: 42:32:D2:75:51:43
[00:00:41.471,343] <inf> bt_id: RPA: 62:34:B5:01:7D:C2
[00:00:51.471,801] <inf> bt_id: RPA: 69:E5:5B:98:8A:06
[00:01:01.472,290] <inf> bt_id: RPA: 44:50:AD:E9:E4:34
[00:01:11.472,808] <inf> bt_id: RPA: 45:93:70:66:DB:58
```

**Impact**
Privacy feature is broken for the scan roles i.e scanner, and creating connections.

**Workaround**
Disable extended advertising API (CONFIG_BT_EXT_ADV=n) when using scan roles with privacy enabled (CONFIG_BT_PRIVACY=y).

**Environment (please complete the following information):**
 - Commit SHA or Version used: Zephyr 3.2.0

**Additional context**
Working as expected in Zephyr 3.1.0 and earlier versions.

### LINKED ISSUE #51247: Bluetooth: RPA expired callback inconsistently called
**Describe the bug**
The RPA expired callback is inconsistently called for advertising sets.
1. RPA expired callback called on advertising set using its identity address if there is another user of RPA timer
2. RPA expired callback called on disabled advertising set if there is another user of the RPA timer.

Added the RPA expiration callback to the shell in order to demonstrate the issues.
```
diff --git a/subsys/bluetooth/shell/bt.c b/subsys/bluetooth/shell/bt.c
index 7c4a630d58..7ecd803eb1 100644
--- a/subsys/bluetooth/shell/bt.c
+++ b/subsys/bluetooth/shell/bt.c
@@ -274,6 +274,24 @@ static void adv_connected(struct bt_le_ext_adv *adv,
                    bt_le_ext_adv_get_index(adv), adv, str);
 }
 #endif /* CONFIG_BT_PERIPHERAL */
+#if defined(CONFIG_BT_PRIVACY)
+static int rpa_expire_count = 3;
+static bool adv_rpa_expired(struct bt_le_ext_adv *adv)
+{
+               shell_print(ctx_shell, "Advertiser[%d] %p RPA expired",
+                   bt_le_ext_adv_get_index(adv), adv);
+
+               return true;
+}
+#endif /* defined(CONFIG_BT_PRIVACY) */
+
 #endif /* CONFIG_BT_EXT_ADV */
 
 #if !defined(CONFIG_BT_CONN)
@@ -563,6 +581,10 @@ static struct bt_le_ext_adv_cb adv_callbacks = {
 #if defined(CONFIG_BT_PERIPHERAL)
        .connected = adv_connected,
 #endif /* CONFIG_BT_PERIPHERAL */
+#if defined(CONFIG_BT_PRIVACY)
+       .rpa_expired = adv_rpa_expired,
+#endif /* defined(CONFIG_BT_PRIVACY) */
```

Reproduce:
```
west build -b nrf52840dk_nrf52840 ../zephyr/tests/bluetooth/shell  -- \
-DCONFIG_BT_PRIVACY=y \
-DCONFIG_BT_LOG_SNIFFER_INFO=y \
-DCONFIG_BT_RPA_TIMEOUT=10
```

1. RPA expired callback called on advertising set using its identity address if there is another user of RPA timer
```
uart:~$ bt fal-add F4:3C:20:48:15:CA (random)
uart:~$ bt scan on fal
Bluetooth active scan enabled
uart:~$ bt adv-create conn-scan identity
Created adv id: 0, adv: 0x20002348
uart:~$ bt adv-start
Advertiser[0] 0x20002348 set started
Advertiser[0] 0x20002348 RPA expired
Advertiser[0] 0x20002348 RPA expired
uart:~$ bt scan off
Scan successfully stopped
# No more RPA expirations
```

2. RPA expired callback called on disabled advertising set if there is another user of the RPA timer.
```
uart:~$ bt fal-add F4:3C:20:48:15:CA (random)
uart:~$ bt scan on fal
Bluetooth active scan enabled
[00:00:46.310,302] <inf> bt_id: bt_id_set_private_addr: RPA: 53:CD:C2:A9:A3:2F
uart:~$ bt adv-create conn-scan
Created adv id: 0, adv: 0x20002348
[00:00:52.830,261] <inf> bt_id: bt_id_set_adv_private_addr: RPA: 47:58:00:75:D4:7B
uart:~$ bt adv-start
Advertiser[0] 0x20002348 set started
Advertiser[0] 0x20002348 RPA expired
[00:01:46.321,044] <inf> bt_id: bt_id_set_adv_private_addr: RPA: 5E:4C:64:18:35:F2
uart:~$ bt adv-stop
Advertiser set stopped
Advertiser[0] 0x20002348 RPA expired
Advertiser[0] 0x20002348 RPA expired
uart:~$ bt scan off 
Scan successfully stopped
# No more RPA expirations
```

**Expected behavior**
The rule for when an RPA expiration callback should be called should not be dependent on other roles running.

**Impact**
Applications must track their own state of the advertiser enabled, or if using identity address.

**Environment (please complete the following information):**
 - Commit SHA or Version used: zephyr 3.2.0 release + shell modification.

### PR DESCRIPTION
**Pull request by joerchan**
Fix RPA timeout expiration when BT_EXT_ADV has been enabled.

Always invalidate the device RPA on RPA timeout.
This RPA is used by the scan roles, and the advertiser that was started
using the bt_le_adv_start API.

Call the RPA expire callback only on advertising sets that are enabled
and not being limited by a timeout and not using the identity address.
On RPA timeout always invalidate the RPA of advertising sets that are
disabled.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51208
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51228
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51247

Add shell support for RPA expire callback.
This prints a message when the callback is called on the specific
advertising set.
Add a command to control the return value of this callback for a
specific advertising set.

### CODE REVIEW

File: subsys/bluetooth/host/id.c [hunk 1]
```diff
@@ -184,9 +184,10 @@ int bt_id_set_adv_random_addr(struct bt_le_ext_adv *adv,
 	return 0;
 }
 
-static void adv_rpa_invalidate(struct bt_le_ext_adv *adv, void *data)
+static void adv_disabled_rpa_invalidate(struct bt_le_ext_adv *adv, void *data)
 {
-	if (!atomic_test_bit(adv->flags, BT_ADV_LIMITED)) {
+	/* Don't invalide RPA of enabled advertising set. */
```
Comment (cvinayak) [inline subsys/bluetooth/host/id.c:189]:
```suggestion
	/* Don't invalidate RPA of enabled advertising set. */
```

File: subsys/bluetooth/host/id.c [hunk 2]
```diff
@@ -410,25 +406,27 @@ static void adv_disable_rpa(struct bt_le_ext_adv *adv, void *data)
...
+		}
 
-	if (rpa_invalid) {
-		atomic_clear_bit(adv->flags, BT_ADV_RPA_VALID);
+		if (rpa_invalid) {
+			atomic_clear_bit(adv->flags, BT_ADV_RPA_VALID);
+		} else {
+			/* Submit the timeout in case no advertising set updates the their RPA
+			 * in the current period. This makes sure that the RPA timer is running.
+			 */
```
Comment (cvinayak) [inline subsys/bluetooth/host/id.c:421]:
```suggestion
			/* Submit the timeout in case no advertising set updates their RPA
			 * in the current period. This makes sure that the RPA timer is running.
			 */
```

**Review by cvinayak — CHANGES_REQUESTED** [review]
Minor typos.

**Review by Thalley — DISMISSED** [review]

**Review by cvinayak — DISMISSED** [review]

File: subsys/bluetooth/host/id.c [hunk 3]
```diff
@@ -199,8 +200,13 @@ static void le_rpa_invalidate(void)
 		atomic_clear_bit(bt_dev.flags, BT_DEV_RPA_VALID);
 	}
 
+	/* Invalidate RPA of advertising sets that are disabled.
+	 *
+	 * Enabled advertising set have to call rpa_expired callback first to
+	 * determine if the RPA of the advertising set should be rotated.
+	 */
```
Comment (kapi-no) [inline subsys/bluetooth/host/id.c:207]: Please consider my comment:

https://github.com/zephyrproject-rtos/zephyr/issues/51247#issuecomment-1283705406

Comment (kapi-no) [reply subsys/bluetooth/host/id.c:207]: @Thalley, @cvinayak and other stakeholders/reviewers of the ```rpa_expired``` callback feature. I suggested the potential modification in the linked comment above. We discussed it briefly with @joerchan. Please speak up if you have any counter-arguments/feedback regarding the conditions in which this callback is called.

Comment (Thalley) [reply subsys/bluetooth/host/id.c:207]: I am not sure I follow the issue mentioned in that comment well enough to provide any additional comments at this point

Comment (carlescufi) [reply subsys/bluetooth/host/id.c:207]: @jhedberg @jori-nordic @alwa-nordic @cvinayak we need input to resolve this.

Comment (kapi-no) [reply subsys/bluetooth/host/id.c:207]: > Would it be useful for the application to get a new_rpa event? Right now rpa_expired is suggested as the event the application should use to synchronize with RPA changes. But that does not quite fit with the stopped-advertising-set case (unless we do assign new RPAs to stopped advertising sets), since a rotation would also happen on adv-start. Hopefully most applications are fine with just the 'expired' event.

I think the new_rpa event is unnecessary if the API user is familiar with Zephyr Bluetooth stack mechanics (we might improve the documentation for this reason). If the advertising is ongoing, the ```rpa_expired``` is also a signal that the new RPA will be used after the callback execution. If the advertising is stopped and the advertising set is not deleted, the ```rpa_expired``` callback should also notify the user about the RPA expiry. The API user should be aware at this point that the Bluetooth stack uses the new RPA upon the advertising restart.

Furthermore, the API user has full control over the RPA for its advertising set regardless of the advertising state (running / disabled). They can suspend the RPA rotation with the ```rpa_expired``` callback for an indefinite time while switching between advertising states. They can also enforce the rotation asynchronously with the ```bt_le_ext_adv_oob_get_local``` API. They have also the possibility to reject the RPA rotation in case of the asynchronous ```bt_le_ext_adv_oob_get_local``` API call, triggered by the user of some other advertising set (mitigates dependency on other advertising sets).

Comment (carlescufi) [reply subsys/bluetooth/host/id.c:207]: Summary from @kapi-no:
The `rpa_expired` callback should be called every time when the `BT_ADV_RPA_VALID` flag is cleared for consistency (clearing causes RPA regeneration).

**Comment by carlescufi** [comment]
@joerchan please update this PR with the [conclusion](https://github.com/zephyrproject-rtos/zephyr/pull/51258#discussion_r1005556543) in the comments.

**Comment by joerchan** [comment]
I've updated the PR with the RPA expired callback now always being called when the RPA of the advertising set is no longer valid.
The application can choose to not invalide RPA on inactive advertising sets.

I've included this as a separate commit. I can squash this with the fix commit if that is preferred.

**Review by kapi-no — APPROVED** [review]

**Comment by kapi-no** [comment]
@joerchan, now it seems that the ```rpa_expired``` callback works reliably. The ```BT_ADV_RPA_VALID``` flag clearing operation seems always to be preceded by execution of the ```rpa_expired``` callback (when the BT_EXT_ADV and BT_PRIVACY are enabled). Thanks for improving callback behaviour!

And once again sorry for introducing unwanted side effects for the Bluetooth Central privacy feature with my initial ```rpa_expired``` PR

**Comment by kruithofa** [comment]
@jhedberg @alwa-nordic please re-review

**Review by cvinayak — APPROVED** [review]
quick pass.

**Review by jori-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
