### PR TITLE
tests: kernel: mutex: add timeout null ptr deref test

### LINKED ISSUE #48056: Possible null pointer dereference after k_mutex_lock times out
**Describe the bug**

Assume thread A holds a mutex and thread B tries to lock it with a timeout, when that time comes up B gets unpended by z_thread_timeout and thus removed from the mutex's wait queue.

If however A unlocks this mutex before B being rescheduled again, the mutex->owner field will be set to null because B is not on the wait queue anymore. And when B finally gets resheduled again it will dereference the null pointer (mutex-owner) here

```
static bool adjust_owner_prio(struct k_mutex *mutex, int32_t new_prio)
{
	if (mutex->owner->base.prio != new_prio) {
```

as @peter-mitsis pointed out in #47906 , complete steps of one possible scenario are:

1. A low priority thread (Tlow) locks mutex A.
2. A high priority thread (Thigh) blocks on mutex A, boosting the priority of Tlow.
3. Thigh times out waiting for mutex A.
4. Before Thigh has a chance to execute, Tlow unlocks mutex A (which now has no owner) and drops its own priority.
5. Thigh now gets a chance to execute and finds that it timed out, and then enters the block of code to lower the priority of the thread that owns mutex A (now nobody).
6. Thigh tries to the dereference the owner of mutex A (which is nobody, and thus it is NULL). This leads to an exception.

**To Reproduce**

Use this test code as an app

```c
#include <kernel.h>
#include <sys/printk.h>

#define TIMEOUT_MS   	100
#define STACKSZ         8192

static struct k_mutex mutex;
static struct k_thread thread;

K_THREAD_STACK_DEFINE(stack, STACKSZ);

void test_thread(void *p1, void *p2, void *p3)
{
    ARG_UNUSED(p1);
    ARG_UNUSED(p2);
    ARG_UNUSED(p3);

    k_mutex_lock(&mutex, K_MSEC(TIMEOUT_MS));

    k_mutex_unlock(&mutex);
}

void main(void)
{
    k_mutex_init(&mutex);

    k_thread_create(&thread, stack, K_THREAD_STACK_SIZEOF(stack),
                    test_thread, NULL, NULL, NULL, 8, 0, K_NO_WAIT);

    k_mutex_lock(&mutex, K_FOREVER);

    k_sleep(K_MSEC(TIMEOUT_MS));

    k_mutex_unlock(&mutex);
}
```

`west build -b qemu_cortex_a53 path_to_the_above_app -t run # will data abort`

**Expected behavior**

Should not dereference a null pointer.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**

*** Booting Zephyr OS build 38de9b0156a8  ***
[00:00:00.000,000] <dbg> os: k_sched_unlock: scheduler unlocked (0x40017600:0)
[00:00:00.010,000] <dbg> os: setup_thread_stack: stack 0x4005fa40 for thread 0x40017000: obj_size=8192 buf_start=0x4005fa40  buf_size 8192 stack_ptr=0x40061a40
[00:00:00.010,000] <dbg> os: z_impl_k_mutex_lock: 0x40017600 took mutex 0x40017900, count: 1, orig prio: 0
[00:00:00.010,000] <dbg> os: z_impl_k_mutex_lock: adjusting prio up on mutex 0x40017900
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_unlock: mutex 0x40017900 lock_count: 1
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_unlock: new owner of mutex 0x40017900: (nil) (prio: -1000)
[00:00:00.120,000] <dbg> os: k_sched_unlock: scheduler unlocked (0x40017600:0)
main 40
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: on mutex 0x40017900 got_mutex value: -11
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: 0x40017000 got mutex 0x40017900 (y/n): y
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: 0x40017000 timeout on mutex 0x40017900
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: adjusting prio down on mutex 0x40017900
[00:00:00.120,000] <err> os: ELR_ELn: 0x0000000040006c30
[00:00:00.120,000] <err> os: ESR_ELn: 0x0000000096000006
[00:00:00.120,000] <err> os:   EC:  0x25 (Data Abort taken without a change in Exception level)
[00:00:00.120,000] <err> os:   IL:  0x1
[00:00:00.120,000] <err> os:   ISS: 0x6
[00:00:00.120,000] <err> os: FAR_ELn: 0x000000000000001a
[00:00:00.120,000] <err> os: TPIDRRO: 0x0100000040017978
[00:00:00.120,000] <err> os: x0:  0x0000000040017900  x1:  0x0000000000000000
[00:00:00.120,000] <err> os: x2:  0x0000000000000000  x3:  0x0000000000000000
[00:00:00.120,000] <err> os: x4:  0x0000000000000000  x5:  0x0000000000000003
[00:00:00.120,000] <err> os: x6:  0x000000000000000a  x7:  0x0000000000000000
[00:00:00.120,000] <err> os: x8:  0x000000000000002f  x9:  0x00000000ffffffff
[00:00:00.120,000] <err> os: x10: 0x0000000000000000  x11: 0x0000000000000000
[00:00:00.120,000] <err> os: x12: 0x0000000000000000  x13: 0x0000000000000000
[00:00:00.130,000] <err> os: x14: 0x0000000000000000  x15: 0x0000000000000000
[00:00:00.130,000] <err> os: x16: 0x0000000000000000  x17: 0x0000000000000000
[00:00:00.130,000] <err> os: x18: 0x0000000000000000  x30: 0x0000000040007204
[00:00:00.130,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.130,000] <err> os: Current thread: 0x40017000 (unknown)
[00:00:00.130,000] <err> os: Halting system

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: v2.7.2

### PR DESCRIPTION
**Pull request by cfriedt**
This test was included in #48056 and should have accompanied #47906 (89c4a07) as well as the backport of that commit (https://github.com/zephyrproject-rtos/zephyr/pull/49031).

### CODE REVIEW

**Comment by cfriedt** [comment]
The backport for this PR is likely to fail because it will need adjustment for 1) removing the `zephyr/`> include prefix, and 2) adjusting to use the old ztest API

File: tests/kernel/mutex/mutex_null_ptr_deref/src/main.c [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+	k_mutex_unlock(&mutex);
+}
+
+ZTEST(mutex_timeout_null_ptr_deref, test_mutex_timeout_error)
+{
+	k_mutex_init(&mutex);
+
+	k_thread_create(&thread, stack, K_THREAD_STACK_SIZEOF(stack), test_thread, NULL, NULL, NULL,
+			8, 0, K_NO_WAIT);
```
Comment (peter-mitsis) [inline tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:33]: I recommend trying to align to a tick boundary prior to calling k_thread_create(). As both test_thread() and test_mutex_timeout_error() delay for TIMEOUT_MS, this should help ensure that they both expire on the same tick.

File: tests/kernel/mutex/mutex_null_ptr_deref/src/main.c [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+	ARG_UNUSED(p2);
+	ARG_UNUSED(p3);
+
+	k_mutex_lock(&mutex, K_MSEC(TIMEOUT_MS));
+
+	k_mutex_unlock(&mutex);
+}
+
+ZTEST(mutex_timeout_null_ptr_deref, test_mutex_timeout_error)
+{
```
Comment (peter-mitsis) [inline tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:29]: There should be a restriction that this test only be executed on a uniprocessor system. Otherwise on an MP system, we may be not even validating PR #47906 as both threads could be executing simultaneously on different cores.

File: tests/kernel/mutex/mutex_null_ptr_deref/src/main.c [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+
+static void test_thread(void *p1, void *p2, void *p3)
+{
+	ARG_UNUSED(p1);
+	ARG_UNUSED(p2);
+	ARG_UNUSED(p3);
+
+	k_mutex_lock(&mutex, K_MSEC(TIMEOUT_MS));
+
+	k_mutex_unlock(&mutex);
```
Comment (peter-mitsis) [inline tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:25]: I think that we should be verifying that k_mutex_lock() fails as it is expected to timeout (which means that k_mutex_unlock is unnecessary).

**Review by peter-mitsis — DISMISSED** [review]
A couple minor things to clean up to make this test a little more robust.

File: tests/kernel/mutex/mutex_null_ptr_deref/src/main.c (hunk 1 above)
Comment (peter-mitsis) [reply tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:33]: The simplest way is sleep for a tick.

Comment (andyross) [reply tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:33]: Yeah, k_usleep(1) and k_sleep(K_TICKS(1)) are patterns that appear again and again in timer-related tests.

Comment (andyross) [reply tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:33]: Oh, but this is a backport, so the ship already sailed :)  No reason not to fix, but would have to be done in main.

Comment (andyross) [reply tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:33]: Or no, it's not, just can't read my labels today :)

File: tests/kernel/mutex/mutex_null_ptr_deref/src/main.c (hunk 2 above)
Comment (cfriedt) [reply tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:29]: what is the best way to achieve that today? I recall ztest 1cpu existed with the old framework.

**Comment by cfriedt** [comment]
@peter-mitsis , @andyross - Updated. PTAL. Not sure if just adding `CONFIG_MP_NUM_CPUS=1` is the best way to ensure that we're  testing on a uniprocessor system.

**Comment by cfriedt** [comment]
> The automatic backport for this PR is likely to fail because it will need adjustment for 1) removing the `zephyr/`> include prefix, and 2) adjusting to use the old ztest API

Previously, we used to use `ztest_1cpu_unit_test()`, to ensure we run on a single CPU, but it looks like `CONFIG_MP_NUM_CPUS=1` should work.

File: tests/kernel/mutex/mutex_null_ptr_deref/src/main.c (hunk 2 above)
Comment (cfriedt) [reply tests/kernel/mutex/mutex_null_ptr_deref/src/main.c:29]: `CONFIG_NUM_CPUS=1`

**Comment by cfriedt** [comment]
@peter-mitsis - I think I've addressed all of your concerns. How does it look now?

**Review by dcpleung — DISMISSED** [review]

**Review by stephanosio — COMMENTED** [review]
Is there any reason this needs to be a separate test on its own? (i.e. why is it not part of `mutex_api` or `mutex_error_case`)

In general, we want to avoid small tests like this because they incur a lot of overhead.

**Comment by stephanosio** [comment]
> Not sure if just adding `CONFIG_MP_NUM_CPUS=1` is the best way to ensure that we're testing on a uniprocessor system.

ztest_1cpu_unit_test

**Review by andyross — DISMISSED** [review]
Test case seems fine to me.  A few nitpicks if you want to respin:

* I agree that this should probably be an extra case added to an existing test.  New test binaries are **MUCH** more expensive in CI than new test cases.
* Naming this "null_ptr_deref" makes me think it's a test of fault handling or something.  Instead it's exercising a particular race/ordering bug in k_mutex (that I'm too lazy to look up to understand).  If it's a regression test we should be clear about that.
* Likewise the commit message's explanation is limited to a links to Github issues, so they don't help with understanding (and won't survive our eventual move to another hosting provider).

**Comment by cfriedt** [comment]
> > Not sure if just adding `CONFIG_MP_NUM_CPUS=1` is the best way to ensure that we're testing on a uniprocessor system.
> 
> ztest_1cpu_unit_test

Only works for the old ztest API, no?

**Comment by cfriedt** [comment]
> Test case seems fine to me. A few nitpicks if you want to respin:
> 
> * I agree that this should probably be an extra case added to an existing test.  New test binaries are **MUCH** more expensive in CI than new test cases.

It looks like any of the mutex suites could work because they all set `CONFIG_MP_NUM_CPUS=1`, but maybe `mutex_error_case` would be the best choice.

> * Naming this "null_ptr_deref" makes me think it's a test of fault handling or something.  Instead it's exercising a particular race/ordering bug in k_mutex (that I'm too lazy to look up to understand).  If it's a regression test we should be clear about that.

Agree. The two hardest problems in computer science
1. cache invalidation
2. naming things
3. off-by-one errors

I could call it `mutex_timeout_race`, but I'm really bad at naming things. Feel free to suggest an alternative.

As far as whether it's a regression, I have not yet traced it back, but according to the original poster, it was a problem in v2.7 - there is a backport for that change, but both fixes (`main` and `v2.7-branch`) did not have an accompanying test even though it was right there in the bug report.

> * Likewise the commit message's explanation is limited to a links to Github issues, so they don't help with understanding (and won't survive our eventual move to another hosting provider).

I can clean that up. Will likely copy from the original commit message though, because @peter-mitsis has described it clearly, and I would really just be paraphrasing.

**Review by andyross — APPROVED** [review]
refresh +1

**Comment by stephanosio** [comment]
> Only works for the old ztest API, no?

right, you need to use `ztest_simple_1cpu_before` and `ztest_simple_1cpu_after` now.

**Review by stephanosio — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
