### PR TITLE
drivers: spi: stm32h7: Use FIFO, transferSize and EOT

### LINKED ISSUE #66326: SPI devices fail after H7 SPI FIFO introduction
The SPI devices started to fail (_periodically_) on STM32H730 after the merge of #63173 where the issue discussion has started. 

The SPI driver gets stuck in `spi_stm32_complete` after data reception due to `ll_func_spi_is_busy` being `true` all the time.

Different SPI peripherals fail at different times. To trigger the issue the board has to be restarted multiple times. When it gets stuck it is always within `spi_stm32_complete`. Sometimes it works, but then devices fail due to corruption of transmitted and/or received data.

The `CR2` is `0`, obviously the `SPI_CR2_TSIZE` is `0` as well. The `SR` (_checked in `LL_SPI_IsActiveFlag_TXC`_) is usually `0`, but there were cases of it being `2`. The `TXC` bit is `0`. Because `TXC` is `0`, the `ll_func_spi_is_busy` returns `true` and it loops forever. At that stage nothing happens on the SPI lines. The context rx/tx count, len are 0 as well as rx/tx buffers are set to 0x0. 

After reducing the clock the issue started to appear every time. With higher clock the issue required board restart to trigger it. Sized down connected zoo to one device per SPI (_to eliminate possible issue(s) from having multiple devices_).

SPI without FIFO, the **device works**:

fifo_off_works

SPI with FIFO, the **device doesn't work** and it is stuck as described:

fifo_on_fail

It is clearly visible that the CS (_chip select_) is dramatically off. It is software controlled by the driver. Most probably that is where the problems are coming from.
 
**Impact**
The #63173 breaks previously working SPI. At least on H730.

**Environment:**
- Toolchain: arm gnu toolchain 12.3 REL1
- Zephyr version is pretty much up to date: [f69641f7d204864aa26f8bdd9fecab259e535da2](https://github.com/zephyrproject-rtos/zephyr/commit/f69641f7d204864aa26f8bdd9fecab259e535da2).

**Additional context**
It is a custom device based on H730. Multiple SPIs are used where each has multiple targets (_slaves_).
I still have to check if existing loopback test would detect the problem.

### PR DESCRIPTION
**Pull request by dgastonochoa**
Use the SPI FIFO for better performance (see #63173 and #66595)

Set the transfer size in SPI H7 and check EOT instead of TXC to be sure the transaction has finished. This requires to enable/disable extra interrupts.

This is very important as otherwise SPI seems to operate in "continuous mode", which produces several SCK cycles after the last frame has been sent/received. However, with TSIZE != 0, the transaction size is known before starting to send anything, which makes the SPI peripheral to stop producing the above mentioned spurious clock cycles.

**The spurious SCK cycles problem is not detected by the spi_loopback tests**; a logic analyzer is required to see the signals and verify the extra SCK cycles are there.

At the time this PR is opened, it's unclear why this clock cycles are generated if TSIZE is not set, or why they are generated only if the FIFO capabilities are used (if the non-fifo shift functions are used, this problem doesn't arise).

Fixes #66326

Related to #65802

Test plan
=========
Run all the spi_loppback tests, with and without DMA/IRQs enabled, and with and without enabling the FIFO usage. That is:

Connect an STM32H7 board to the PC with pins D11 and D12 connected.

Open a minicom or equivalent terminal to read the test report.

Execute the following commands both with and without `fifo-enabled;` in the `spi1` node in the `nucleo-h743/53` dts files and the `stm32-16bits.overlay` one:

```
rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h753zi tests/drivers/spi/spi_loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h753zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_16bits_frames.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h753zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_dma.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h753zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_16bits_frames_dma.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h753zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_dma_no_nocache.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h753zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_16bits_frames_dma_no_nocache.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h753zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_interrupt.loopback
west flash




rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h743zi tests/drivers/spi/spi_loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h743zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_16bits_frames.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h743zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_dma.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h743zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_16bits_frames_dma.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h743zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_dma_no_nocache.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h743zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_16bits_frames_dma_no_nocache.loopback
west flash

rm -rf ~/zephyrproject/zephyr/build
west build -p auto -b nucleo_h753zi -T tests/drivers/spi/spi_loopback/drivers.spi.stm32_spi_interrupt.loopback
west flash
```
Also, as the error mentioned above is not detected by the spi_loopback tests, inspect the signals (with and without irqs enabled) with a logic analyzer, and verify the extra clock cycles are not generated.

Below you can find the captures obtained, with an extra test suggested by @GeorgeCGV that is not part of the current spi_loopback tests, but it's worth to consider to add it as it helps to detect this problem.

The test, adapted to the spi_loopback tests setup, is: 

```
static __aligned(32) uint8_t tx_data2[36] __NOCACHE;
static __aligned(32) uint8_t rx_data2[36] __NOCACHE;

static int spi_complete_multiple2(struct spi_dt_spec *spec)
{
	int ret;

	for (unsigned i = 0; i < sizeof(tx_data2); ++i) {
		tx_data2[i] = i;
	}

	for(unsigned len = 2; len <= sizeof(tx_data2); len += 2) {
		(void)memset(rx_data2, 0, sizeof(rx_data2));

		struct spi_buf tx_buf = { .buf = tx_data2, .len = len };
		struct spi_buf rx_buf = { .buf = rx_data2, .len = len };
		const struct spi_buf_set tx = { .buffers = &tx_buf, .count = 1U };
		const struct spi_buf_set rx = { .buffers = &rx_buf, .count = 1U };

		ret = spi_transceive_dt(spec, &tx, &rx);
		if (ret) {
			LOG_ERR("Code %d, len %u", ret, len);
			continue;
		}

		if (memcmp(tx_data2, rx_data2, len)) {
			LOG_ERR("Buffer contents are different, rx&tx len %u", len);
		}

		memset(rx_data2, 0, 36);
	}

	return 0;
}
```
Notice that the lengths sent need to be a multiple of 2, or the 16 bits frame tests will fail.

This test, called _spi_complete_multiple2_, is executed in second place. Below there is a code snippet that shows it:

```
[...]
if (spi_complete_multiple(&spi_fast) || spi_complete_multiple2(&spi_fast) ||
	    spi_complete_loop(&spi_fast) ||
[...]
```

And the obtained captures, which can be opened with Logic II, are below:

[new_captures.zip](https://github.com/zephyrproject-rtos/zephyr/files/13663861/new_captures.zip)

### CODE REVIEW

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -678,6 +709,52 @@ static int spi_stm32_release(const struct device *dev,
...
+
+	if (rx_frames < 0) {
+		return rx_frames;
+	}
+
+	if (tx_frames > UINT16_MAX || rx_frames > UINT16_MAX) {
+		return -EMSGSIZE;
+	}
+
+	return (rx_frames > tx_frames) ? rx_frames : tx_frames;
```
Comment (GeorgeCGV) [inline drivers/spi/spi_ll_stm32.c:754]:
```suggestion
	return MAX(rx_frames, tx_frames);
```

**Comment by GeorgeCGV** [comment]
Looks great 🎉
Will test the changes tomorrow.

File: drivers/spi/spi_ll_stm32.c [hunk 2]
```diff
@@ -678,6 +709,52 @@ static int spi_stm32_release(const struct device *dev,
 	return 0;
 }
 
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+static int32_t spi_stm32_count_bufset_frames(const struct spi_config *config,
+			const struct spi_buf_set *bufs)
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:714]: Nitpick: indentation

File: drivers/spi/spi_ll_stm32.c [hunk 3]
```diff
@@ -678,6 +709,52 @@ static int spi_stm32_release(const struct device *dev,
...
+
+	if ((num_bytes % bytes_per_frame) != 0) {
+		return -EINVAL;
+	}
+	return num_bytes / bytes_per_frame;
+}
+
+static int32_t spi_stm32_count_total_frames(const struct spi_config *config,
+			const struct spi_buf_set *tx_bufs,
+			const struct spi_buf_set *rx_bufs)
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:736]: Nitpick: indentation

File: drivers/spi/spi_ll_stm32.c [hunk 4]
```diff
@@ -678,6 +709,52 @@ static int spi_stm32_release(const struct device *dev,
...
 
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+static int32_t spi_stm32_count_bufset_frames(const struct spi_config *config,
+			const struct spi_buf_set *bufs)
+{
+	if (bufs == NULL) {
+		return 0;
+	}
+
+	uint32_t num_bytes = 0;
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:720]: Variables should be declared at the beginning of the block (see coding guidelines).

File: drivers/spi/spi_ll_stm32.c [hunk 5]
```diff
@@ -678,6 +709,52 @@ static int spi_stm32_release(const struct device *dev,
...
+
+	for (size_t i = 0; i < bufs->count; i++) {
+		num_bytes += bufs->buffers[i].len;
+	}
+
+	uint8_t bytes_per_frame = SPI_WORD_SIZE_GET(config->operation) / 8;
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:726]: Ditto

File: drivers/spi/spi_ll_stm32.c [hunk 6]
```diff
@@ -678,6 +709,52 @@ static int spi_stm32_release(const struct device *dev,
...
+			const struct spi_buf_set *tx_bufs,
+			const struct spi_buf_set *rx_bufs)
+{
+	int tx_frames = spi_stm32_count_bufset_frames(config, tx_bufs);
+
+	if (tx_frames < 0) {
+		return tx_frames;
+	}
+
+	int rx_frames = spi_stm32_count_bufset_frames(config, rx_bufs);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:744]: Ditto on variable declaration

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for the engagement on fixing this issue.

Some changes requested on the variables declaration.

Then, a general comment (not blocking)
It would be welcomed to split the change in 2 commits:
- one part that refactor the code, with no additional code
- second part which introduces the new code (the actual, expected, fix)

Reason why I'm asking this is because this change is impacting parts of code non related to H7 (even if this is simple refactoring), which is once again a risk to introduce regressions. So I'd like a closer control, and splitting changes is a way to make impacts clearer.

Side note: Are you still planning to introduce dts property to allow users control on the fifo activation ? (totally fine with me if this is done in a second PR)

**Comment by GeorgeCGV** [comment]
Tested with the application that has multiple SPIs with multiple slaves.
Stalling/freezing is no longer observed. The application continues to run. 
However, started to get SPI overruns (_wasn't the case before_).

**Comment by avisconti** [comment]
I tested it with sensortile_box_pro board and I DO NOT observe #66486 issue anymore.

**Comment by GeorgeCGV** [comment]
The CS seem to stay on longer sometimes.

##### stays on longer at the end
cs_stays_on_longer

##### stays on longer at the start
cs_stays_on_longer_before2

But probably it is related to other parts in the system that interrupt the thread that is performing spi transaction.

File: drivers/spi/spi_ll_stm32.c (hunk 4 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:720]: Sorry, could you point me to the exact rule? I'm inspecting this coding guidelines document: https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html and I can't find the related rule.

**Comment by dgastonochoa** [comment]
> Are you still planning to introduce dts property to allow users control on the fifo activation ? (totally fine with me if this is done in a second PR)

@erwango Yes, but in a separated PR. I prefer to isolate this problem solution as much as possible, as it was rather complex for me.

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c]: Done

File: drivers/spi/spi_ll_stm32.c (hunk 2 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:714]: Done (I hope)

File: drivers/spi/spi_ll_stm32.c [hunk 7]
```diff
@@ -899,6 +994,9 @@ static int transceive_dma(const struct device *dev,
 	}
 
 #if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	/* Endless transaction */
```
[the remark this answers is not in the document]
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c]: Done

File: drivers/spi/spi_ll_stm32.c [hunk 8]
```diff
@@ -459,42 +459,73 @@ static void spi_stm32_cs_control(const struct device *dev, bool on)
...
-	if (LL_SPI_GetMode(spi) == LL_SPI_MODE_MASTER) {
+	/* BSY flag is cleared when MODF flag is raised */
+	if (LL_SPI_IsActiveFlag_MODF(spi)) {
+		LL_SPI_ClearFlag_MODF(spi);
+	}
+
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	LL_SPI_ClearFlag_TXTF(spi);
+	LL_SPI_ClearFlag_OVR(spi);
+	LL_SPI_ClearFlag_SUSP(spi);
```
Comment (GeorgeCGV) [inline drivers/spi/spi_ll_stm32.c:494]: The `LL_SPI_ClearFlag_SUSP` is cleared in `ll_func_disable_spi`.

**Comment by dgastonochoa** [comment]
>  by the way, without holding the irq with while loops during shifting it works without overruns.

@GeorgeCGV Could you clarify this please? What IRQ are you referring to? This PR doesn't hold the IRQ handler in a while loop.

File: drivers/spi/spi_ll_stm32.c [hunk 9]
```diff
@@ -459,42 +459,73 @@ static void spi_stm32_cs_control(const struct device *dev, bool on)
...
+static void spi_stm32_disable_irqs(SPI_TypeDef *spi)
+{
 	ll_func_disable_int_tx_empty(spi);
 	ll_func_disable_int_rx_not_empty(spi);
 	ll_func_disable_int_errors(spi);
-#endif
 
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	LL_SPI_DisableIT_DXP(spi);
+	LL_SPI_DisableIT_TXTF(spi);
```
[the remark this answers is not in the document]
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:471]: I don't remember exactly why I disabled them. Maybe I did it as a "just in case" they get enabled in the future. I could change it, but I would rather avoid modify the logic at this point to avoid going through the tests I have and making everyone else to re-test.

File: drivers/spi/spi_ll_stm32.c (hunk 8 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:494]: I wouldn't pay much attention to the `disable_spi` function as I believe is incorrect. It clears the `SUSP` flag because it suspends the transaction, which shouldn't be done unless there is a reason for it (and there isn't). So it shouldn't do either of the above, but that's out of this PR's scope.

File: drivers/spi/spi_ll_stm32.c (hunk 4 above)
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:720]: Ha, it seems this page has evolved since the last time I've checked. Only close reference (which would answer your exact question) I've found is https://wiki.sei.cmu.edu/confluence/display/c/DCL19-C.+Minimize+the+scope+of+variables+and+functions, but it does not specify the rule I mention.
I'll make more research

Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:720]: Doesn't see to be explicitly stated anywhere, but it is a general C coding best practice, recommended by K & R: `In Chapter 1.2 of K&R is written: In C, all variables must be declared before they are used, usually at the beginning of a function, before any executable statements.`
Take this comment as non blocking.

File: drivers/spi/spi_ll_stm32.c [hunk 10]
```diff
@@ -479,22 +499,23 @@ static void spi_stm32_complete(const struct device *dev, int status)
 	}
 #endif
 
-	if (LL_SPI_GetMode(spi) == LL_SPI_MODE_MASTER) {
-		while (ll_func_spi_is_busy(spi)) {
-			/* NOP */
-		}
-
-		spi_stm32_cs_control(dev, false);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:487]: Are you reverting https://github.com/zephyrproject-rtos/zephyr/pull/66381?
If, yes, please do it in a dedicated commit with a proper justification

Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:487]: It's not a reversion: I have moved it from where it was to below because now the "way of waiting for the SPI to finish" has 2 forms: one with a while loop for when interrupts are not enabled, and another one with an `if` for when interrupts are enabled. In any case, CS needs to be de-asserted after the driver has waited enough, so (to avoid replicating code) this statement needs to be moved to after the wait operation. But it's equivalent in terms of functionality.

File: drivers/spi/spi_ll_stm32.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:471]: > I don't remember exactly why I disabled them. Maybe I did it as a "just in case" they get enabled in the future. I could change it, but I would rather avoid modify the logic at this point to avoid going through the tests I have and making everyone else to re-test.

That's not exactly a good answer. 
Despite all your efforts (which I think every one can appreciate), I don't want to rush into merging a follow up fix that could introduce other regressions (as we can see it is not easy to anticipate or prevent the regressions).

Here is my proposal:
- Revert https://github.com/zephyrproject-rtos/zephyr/pull/63173/commits/bffa0c6bddbc91d39f4b01baa34e3d0595760d50
- Push a new version of the FIFO patch together with a dts property that allows users to enable the feature.

This would be the safest way to bring this new feature (which I think is valuable to the driver) and avoid to disturb users and impact driver maturity.

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by dgastonochoa** [comment]
> part from #63173

@GeorgeCGV if I understood you correctly, you are suggesting to replace the while loops by just `if`s, so that the IRQ handler finishes almost immediately, so the reaction to incoming RX frames is faster, am I right? If so, I agree. This way, non-IRQ SPI still sends frames in a loop while IRQs are reaction if better. It could happen that the SPI performance decreases if many IRQs from other devices need to be attended, but this is a much better scenario than having overruns. I believe overruns can no longer happen as the RxFIFO is always checked before the Tx one.

I have added a 3rd commit with what I think you mean (it works for the loopback tests and logic analyzer captures). Would it be possible to test it in the scenario you mentioned? Thanks.

**Comment by dgastonochoa** [comment]
> That's not exactly a good answer.

@erwango I think you misinterpreted me. I'm not trying to give a quick justification to get the PR forward. What I mean is that this change (transferSize + EOT) is something I did some time ago and I don't fully remember every single bit of it. For this case in particular, I think I cleared/disabled some flags that are not enabled before in case the driver is modified in the future and they are enabled. Whether or not this is correct is a matter of discussion.

With regards to adding the FIFO-enable feature, I'm happy to add it to this PR.

About reverting the previous one, I don't see the need for it but I can do it anyway if you, the reviewer, thinks it's better.

In summary, I can add the reversion commit as the first commit of this PR and the device-tree enable/disable as the last one; and change the title to something more generic as "Fix-FIFO". I will also remove the mentioned irqs/flags clear/disable. Could you confirm you are happy with this? Thanks.

**Comment by erwango** [comment]
> In summary, I can add the reversion commit as the first commit of this PR and the device-tree enable/disable as the last one; and change the title to something more generic as "Fix-FIFO". I will also remove the mentioned irqs/flags clear/disable. Could you confirm you are happy with this? Thanks.

My main target it to preserve driver maturity status. Hence, I'd like to ensure the change is structurally set in order to achieve this goal. So one additional request is to ensure that no functional change is applied on the non-fifo code.
Otherwise, I'm fine with this proposal. Thanks.

**Comment by GeorgeCGV** [comment]
> > part from #63173
> 
> @GeorgeCGV if I understood you correctly, you are suggesting to replace the while loops by just `if`s, so that the IRQ handler finishes almost immediately, so the reaction to incoming RX frames is faster, am I right? If so, I agree. This way, non-IRQ SPI still sends frames in a loop while IRQs reaction is faster. It could happen that the SPI performance decreases if many IRQs from other devices need to be attended, but this is a much better scenario than having overruns.
> 
> I have added a 3rd commit with what I think you mean (it works for the loopback tests and logic analyzer captures). Would it be possible to test it in the scenario you mentioned? Thanks.

I tried such approach and it does work, also fixes overruns. However, I am not sure if fifo is really utilized when doing it that way.
Do we really reduce the amount of interrupts compared to the non h7/fifo approach?

We can look into [linux H7 SPI driver](https://github.com/torvalds/linux/blob/5bd7ef53ffe5ca580e93e74eb8c81ed191ddc4bd/drivers/spi/spi-stm32.c#L1189-L1193C7) to see how they handled that.

They fill the TX-FIFO before CSTART.

In the IRQ offload they (_non dma_):
1. Check errors
2. Check EOT. When set, read out RX-FIFO (_pre-filled TX-FIFO could have ended the transfer_), finish.
3. Fill TX-FIFO for as long as there is space in TX-FIFO and something to send (_spi->tx_len > 0_)
4. Read RX-FIFO for as long as there is something in RX-FIFO and to receive (_spi->rx_len > 0_) **OR** `EOT and (RXWNE or RXPLVL > 0)`

That seems logical, and that is close to the way in the #63173. But it causes overruns (_not observed with disabled #63173_). 

Sure, in our case the IRQ handling is not offloaded as in linux. And it is questionable if doing that is beneficial for most users and applications.

I agree with @erwango, you did a great job and responded in a timely manner to assist with the regression. Thank you very much.

Overall, I think that the idea to:

1. Revert #63173
2. Combine changes of #63173 with #66503 (_this PR_)
3. Added ability to enable new SPI handling for h7/fifo via DT that is off by default
4. Maybe some clean-up is required (_i.e. not suspending the spi if it is already done, not disabling not enabled IRQs_)

is not bad. That makes history cleaner, compacts the feature in a single PR with sequential commits. With added ability to turn on/off the feature could allow future modifications of the feature without affecting other parts.

There are some open aspects:
1. How to test the SPI to reduce similar regressions? If at all possible. As the initial issues related to the signals. 
2. Is there a benchmark to test that new feature/modification performs better than existing one?

**Comment by dgastonochoa** [comment]
@GeorgeCGV:

> I am not sure if fifo is really utilized when doing it that way. 

Could you explain why? I have inspected the waveforms with a logic analyzer and they are identical to the ones in the test plan, that is, the time gaps between bytes disappear.

As long as the TxFIFO is not full, TXP fires endlessly, so the new version should be equivalent to the `while` loop one, but with many more, much shorter, interrupt handlers, which leads to more stability against overruns and more room for other ISR to execute. Don't you agree with this?

> Do we really reduce the amount of interrupts compared to the non h7/fifo approach?

As explained above, no, the number of interrupts is not reduced, but that's not the goal either. What this change achieves is that the IRQ handler doesn't wait for tx to not be full, then write a frame to the TxFIFO, then wait for it to be transmitted, and then read from RxFIFO (al within the same ISR, blocking others)

> How to test the SPI to reduce similar regressions? If at all possible. As the initial issues related to the signals.

Maybe with a specialized test case for this, with a GPIO that counts SCK cycles.


@erwango 

> My main target it to preserve driver maturity status. Hence, I'd like to ensure the change is structurally set in order to achieve this goal. 

I couldn't agree more.

**Comment by reatreada** [comment]
> Could you explain why?

We don't fill the tx fifo with more than 1 byte and don't read more than 1 byte from rx fifo (_case of 8 bit frame_).

**Comment by GeorgeCGV** [comment]
> Could you explain why? ... As long as the TxFIFO is not full, TXP fires endlessly...

It fires, goes to IRQ handler, then we feed 1 frame and read another (_if we use `if` statements_). Then cycle repeats.

Therefore, we don't fill the tx-fifo with more than 1 byte and don't read more than 1-byte from rx fifo (_case of 8 bit frame_).

By the way, with `if` statements there is no need in `spi_stm32_transfer_ongoing` within `spi_stm32_shift_fifo`, as it is checked before in `spi_stm32_shift_frames`.

**Comment by dgastonochoa** [comment]
> It fires, goes to IRQ handler, then we feed 1 frame and read another (if we use if statements). Then the interrupt repeats. 
Therefore, we don't fill the tx-fifo with more than 1 byte and don't read more than 1-byte from rx fifo (case of 8 bit frame).

That's not the case. It fires, the IRQ handler writes to Tx and then it checks the Rx FIFO. The frame in Tx has not yet been sent, since it first needs to be shifted by the SPI device (which doesn't happen instantaneously after the TxFIFO is populated, otherwise FIFOs wouldn't be necessary) and the byte needs to be fully shifted (8 CLK cycles in this case). Then it keeps firing either because there is room again in TxFIFO or because (at least) one frame is available in RxFIFO. 

Unless a very strange (almost certain impossible or unusable) configuration is placed, so that the SPI peripheral and the SCK clock signals are both faster than the CPU clock, the TxFIFO will be fully populated before the first frame arrives to Rx. 

I insist, look at the waveforms with a logic analyzer, or place a log trace in the ISR and verify how the TXP IRQ triggers 10s of times before the first frame arrives to Rx (assuming asynchronous logging, of course).

**Comment by GeorgeCGV** [comment]
@dgastonochoa I see..., then it is good. However, probably we should pre-fill the tx-fifo before starting the SPI. That could reduce the amount of interrupts for short transmissions.

File: drivers/spi/spi_ll_stm32.c (hunk 2 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c]: > A very commonly used style is to align descendants to a function open parenthesis.

I have tried this and the compliance check fails. 

Compliance checks pass now, so marking as resolved.

**Comment by dgastonochoa** [comment]
The build fails because the workaround in https://github.com/zephyrproject-rtos/zephyr/pull/66503/commits/c7c7e5fad1d570a0480d8c4bb9e0aaa6150d48b7 would need to be applied in many places.

File: drivers/spi/spi_ll_stm32.c [hunk 11]
```diff
@@ -338,20 +338,36 @@ static int spi_stm32_get_err(SPI_TypeDef *spi)
...
-		/* NOP */
+	if (ll_func_rx_is_not_empty(spi)) {
+		spi_stm32_read_next_frame(spi, data);
 	}
 
-	spi_stm32_send_next_frame(spi, data);
-
-	while (!ll_func_rx_is_not_empty(spi)) {
-		/* NOP */
+	if (ll_func_tx_is_not_full(spi) && spi_stm32_transfer_ongoing(data)) {
```
Comment (GeorgeCGV) [inline drivers/spi/spi_ll_stm32.c:347]: Is `spi_stm32_transfer_ongoing(data)` necessary here? As the check is done before in 
https://github.com/zephyrproject-rtos/zephyr/blob/1d61642388097d4afcd567c3043a5829e27a2f14/drivers/spi/spi_ll_stm32.c#L530

**Comment by GeorgeCGV** [comment]
> The build fails because the workaround in [c7c7e5f](https://github.com/zephyrproject-rtos/zephyr/commit/c7c7e5fad1d570a0480d8c4bb9e0aaa6150d48b7) would need to be applied in many places.

Maybe `#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_spi_fifo)` could be changed to `DT_NODE_HAS_COMPAT(DT_DRV_INST(id), st_stm32_spi_fifo)`? That should help to avoid `compat` order dependency.

**Comment by avisconti** [comment]
I tried to build sensortile_box_pro but it failed. It seems it reports same build error as the CI does:

```
west build -b sensortile_box_pro samples/boards/sensortile_box_pro/sensors-on-board

[0/1] Re-running CMake...
Loading Zephyr default modules (Zephyr base (cached)).
-- Application: /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/samples/boards/sensortile_box_pro/sensors-on-board
-- CMake version: 3.20.2
-- Cache files will be written to: /local/home/visconti/.cache/zephyr
-- Zephyr version: 3.5.99 (/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr)
-- Found west (found suitable version "1.1.0", minimum required is "0.14.0")
-- Board: sensortile_box_pro
-- Found host-tools: zephyr 0.16.1 (/local/home/visconti/bin/zephyr-sdk-0.16.1)
-- Found toolchain: zephyr 0.16.1 (/local/home/visconti/bin/zephyr-sdk-0.16.1)
-- Found BOARD.dts: /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/boards/arm/sensortile_box_pro/sensortile_box_pro.dts
-- Generated zephyr.dts: /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build/zephyr/dts.cmake
Parsing /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/Kconfig
Loaded configuration '/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build/zephyr/.config'
No change to configuration in '/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build/zephyr/.config'
No change to Kconfig header in '/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h'
-- Configuring done
-- Generating done
-- Build files have been written to: /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build
[1/23] Generating include/generated/version.h
-- Zephyr version: 3.5.99 (/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr), build: zephyr-v3.5.0-3315-g1d6164238809
[15/23] Building C object zephyr/drivers/spi/CMakeFiles/drivers__spi.dir/spi_ll_stm32.c.obj
FAILED: zephyr/drivers/spi/CMakeFiles/drivers__spi.dir/spi_ll_stm32.c.obj 
ccache /local/home/visconti/bin/zephyr-sdk-0.16.1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DHSE_VALUE=8000000 -DKERNEL -DPICOLIBC_DOUBLE_PRINTF_SCANF -DSTM32U585xx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D_FORTIFY_SOURCE=1 -D_POSIX_C_SOURCE=200809 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I../include -Izephyr/include/generated -I../soc/arm/st_stm32/stm32u5 -I../drivers -I../soc/arm/st_stm32/common -I../subsys/usb/device -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/cmsis/CMSIS/Core/Include -I../modules/cmsis/. -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/st/sensor/stmemsc/hts221_STdC/driver -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/st/sensor/stmemsc/lis2du12_STdC/driver -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/st/sensor/stmemsc/lis2mdl_STdC/driver -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/st/sensor/stmemsc/lps22df_STdC/driver -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/st/sensor/stmemsc/lsm6dsv16x_STdC/driver -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/stm32/stm32cube/stm32u5xx/soc -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/stm32/stm32cube/stm32u5xx/drivers/include -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/stm32/stm32cube/stm32u5xx/drivers/include/Legacy -I/local/home/visconti/Projects/GIT/FW/zephyrproject/modules/hal/stm32/stm32cube/common_ll/include -isystem ../lib/libc/common/include -Wshadow -fno-strict-aliasing -Os -imacros /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m33 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft --sysroot=/local/home/visconti/bin/zephyr-sdk-0.16.1/arm-zephyr-eabi/arm-zephyr-eabi -imacros /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/samples/boards/sensortile_box_pro/sensors-on-board=CMAKE_SOURCE_DIR -fmacro-prefix-map=/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/local/home/visconti/Projects/GIT/FW/zephyrproject=WEST_TOPDIR -ffunction-sections -fdata-sections --specs=picolibc.specs -std=c99 -MD -MT zephyr/drivers/spi/CMakeFiles/drivers__spi.dir/spi_ll_stm32.c.obj -MF zephyr/drivers/spi/CMakeFiles/drivers__spi.dir/spi_ll_stm32.c.obj.d -o zephyr/drivers/spi/CMakeFiles/drivers__spi.dir/spi_ll_stm32.c.obj -c /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c
In file included from ../include/zephyr/sys/util_macro.h:34,
                 from ../include/zephyr/sys/util.h:17,
                 from ../include/zephyr/sys/cbprintf_internal.h:15,
                 from ../include/zephyr/sys/cbprintf.h:124,
                 from ../include/zephyr/logging/log_msg.h:11,
                 from ../include/zephyr/logging/log_core.h:9,
                 from ../include/zephyr/logging/log.h:11,
                 from /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:10:
zephyr/include/generated/devicetree_generated.h:12710:39: error: 'DT_N_S_soc_S_spi_40013000_P_fifo_enabled' undeclared here (not in a function); did you mean 'DT_N_S_soc_S_serial_40013800_P_fifo_enable'?
12710 | #define DT_N_INST_0_st_stm32_spi      DT_N_S_soc_S_spi_40013000
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
../include/zephyr/sys/util_internal.h:72:26: note: in definition of macro '__DEBRACKET'
   72 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
../include/zephyr/sys/util_internal.h:64:9: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   64 |         __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |         ^~~~~~~~~~~~~~~~~~~~
../include/zephyr/sys/util_internal.h:59:9: note: in expansion of macro '__COND_CODE'
   59 |         __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~
../include/zephyr/sys/util_macro.h:180:9: note: in expansion of macro 'Z_COND_CODE_1'
  180 |         Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~~~
../include/zephyr/devicetree.h:4112:9: note: in expansion of macro 'COND_CODE_1'
 4112 |         COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT),   \
      |         ^~~~~~~~~~~
../include/zephyr/devicetree.h:615:32: note: in expansion of macro 'DT_CAT3'
  615 | #define DT_PROP(node_id, prop) DT_CAT3(node_id, _P_, prop)
      |                                ^~~~~~~
../include/zephyr/devicetree.h:3500:34: note: in expansion of macro 'DT_PROP'
 3500 | #define DT_INST_PROP(inst, prop) DT_PROP(DT_DRV_INST(inst), prop)
      |                                  ^~~~~~~
../include/zephyr/sys/util_internal.h:105:36: note: in expansion of macro 'DT_N_INST_0_st_stm32_spi'
  105 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
../include/zephyr/sys/util_internal.h:104:26: note: in expansion of macro 'UTIL_PRIMITIVE_CAT'
  104 | #define UTIL_CAT(a, ...) UTIL_PRIMITIVE_CAT(a, __VA_ARGS__)
      |                          ^~~~~~~~~~~~~~~~~~
../include/zephyr/devicetree.h:334:31: note: in expansion of macro 'UTIL_CAT'
  334 | #define DT_INST(inst, compat) UTIL_CAT(DT_N_INST, DT_DASH(inst, compat))
      |                               ^~~~~~~~
../include/zephyr/devicetree.h:3298:27: note: in expansion of macro 'DT_INST'
 3298 | #define DT_DRV_INST(inst) DT_INST(inst, DT_DRV_COMPAT)
      |                           ^~~~~~~
../include/zephyr/devicetree.h:3500:42: note: in expansion of macro 'DT_DRV_INST'
 3500 | #define DT_INST_PROP(inst, prop) DT_PROP(DT_DRV_INST(inst), prop)
      |                                          ^~~~~~~~~~~
/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:1262:33: note: in expansion of macro 'DT_INST_PROP'
 1262 | #define SPI_FIFO_ENABLED(id)    DT_INST_PROP(id, fifo_enabled)
      |                                 ^~~~~~~~~~~~
/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:1280:25: note: in expansion of macro 'SPI_FIFO_ENABLED'
 1280 |         .fifo_enabled = SPI_FIFO_ENABLED(id),                           \
      |                         ^~~~~~~~~~~~~~~~
zephyr/include/generated/devicetree_generated.h:21545:47: note: in expansion of macro 'STM32_SPI_INIT'
21545 | #define DT_FOREACH_OKAY_INST_st_stm32_spi(fn) fn(0) fn(1)
      |                                               ^~
../include/zephyr/sys/util_internal.h:105:36: note: in expansion of macro 'DT_FOREACH_OKAY_INST_st_stm32_spi'
  105 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:1303:1: note: in expansion of macro 'DT_INST_FOREACH_STATUS_OKAY'
 1303 | DT_INST_FOREACH_STATUS_OKAY(STM32_SPI_INIT)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
zephyr/include/generated/devicetree_generated.h:16820:39: error: 'DT_N_S_soc_S_spi_40003800_P_fifo_enabled' undeclared here (not in a function); did you mean 'DT_N_S_soc_S_serial_40004800_P_fifo_enable'?
16820 | #define DT_N_INST_1_st_stm32_spi      DT_N_S_soc_S_spi_40003800
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
../include/zephyr/sys/util_internal.h:72:26: note: in definition of macro '__DEBRACKET'
   72 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
../include/zephyr/sys/util_internal.h:64:9: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   64 |         __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |         ^~~~~~~~~~~~~~~~~~~~
../include/zephyr/sys/util_internal.h:59:9: note: in expansion of macro '__COND_CODE'
   59 |         __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~
../include/zephyr/sys/util_macro.h:180:9: note: in expansion of macro 'Z_COND_CODE_1'
  180 |         Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~~~
../include/zephyr/devicetree.h:4112:9: note: in expansion of macro 'COND_CODE_1'
 4112 |         COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT),   \
      |         ^~~~~~~~~~~
../include/zephyr/devicetree.h:615:32: note: in expansion of macro 'DT_CAT3'
  615 | #define DT_PROP(node_id, prop) DT_CAT3(node_id, _P_, prop)
      |                                ^~~~~~~
../include/zephyr/devicetree.h:3500:34: note: in expansion of macro 'DT_PROP'
 3500 | #define DT_INST_PROP(inst, prop) DT_PROP(DT_DRV_INST(inst), prop)
      |                                  ^~~~~~~
../include/zephyr/sys/util_internal.h:105:36: note: in expansion of macro 'DT_N_INST_1_st_stm32_spi'
  105 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
../include/zephyr/sys/util_internal.h:104:26: note: in expansion of macro 'UTIL_PRIMITIVE_CAT'
  104 | #define UTIL_CAT(a, ...) UTIL_PRIMITIVE_CAT(a, __VA_ARGS__)
      |                          ^~~~~~~~~~~~~~~~~~
../include/zephyr/devicetree.h:334:31: note: in expansion of macro 'UTIL_CAT'
  334 | #define DT_INST(inst, compat) UTIL_CAT(DT_N_INST, DT_DASH(inst, compat))
      |                               ^~~~~~~~
../include/zephyr/devicetree.h:3298:27: note: in expansion of macro 'DT_INST'
 3298 | #define DT_DRV_INST(inst) DT_INST(inst, DT_DRV_COMPAT)
      |                           ^~~~~~~
../include/zephyr/devicetree.h:3500:42: note: in expansion of macro 'DT_DRV_INST'
 3500 | #define DT_INST_PROP(inst, prop) DT_PROP(DT_DRV_INST(inst), prop)
      |                                          ^~~~~~~~~~~
/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:1262:33: note: in expansion of macro 'DT_INST_PROP'
 1262 | #define SPI_FIFO_ENABLED(id)    DT_INST_PROP(id, fifo_enabled)
      |                                 ^~~~~~~~~~~~
/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:1280:25: note: in expansion of macro 'SPI_FIFO_ENABLED'
 1280 |         .fifo_enabled = SPI_FIFO_ENABLED(id),                           \
      |                         ^~~~~~~~~~~~~~~~
zephyr/include/generated/devicetree_generated.h:21545:53: note: in expansion of macro 'STM32_SPI_INIT'
21545 | #define DT_FOREACH_OKAY_INST_st_stm32_spi(fn) fn(0) fn(1)
      |                                                     ^~
../include/zephyr/sys/util_internal.h:105:36: note: in expansion of macro 'DT_FOREACH_OKAY_INST_st_stm32_spi'
  105 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
/local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/drivers/spi/spi_ll_stm32.c:1303:1: note: in expansion of macro 'DT_INST_FOREACH_STATUS_OKAY'
 1303 | DT_INST_FOREACH_STATUS_OKAY(STM32_SPI_INIT)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /local/home/visconti/Projects/GIT/FW/zephyrproject/zephyr/build
```

**Comment by dgastonochoa** [comment]
> I tried to build sensortile_box_pro but it failed. It seems it reports same build error as the CI does:

Yes, that error is the same one shown in the build checks in the PR and I explained it in comments above.

**Comment by dgastonochoa** [comment]
> Maybe `#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_spi_fifo)` could be changed to `#if DT_NODE_HAS_COMPAT(DT_DRV_INST(id), st_stm32_spi_fifo)`? That should help to avoid `compat` order dependency.

I think the compatible order dependency is expected as explainer here: #66694. I have moved the new property to the proper yaml file according to the explanation above, and remove the work around commit. 

In any case, about your suggestion, I can't use `#if` with it because in that context the instance ID is not known unless I'm missing something. Maybe it could be used with `COND_CODE_1`.

**Comment by erwango** [comment]
> I have moved the new property to the proper yaml file according to the explanation above, and remove the work around commit.

Well actually the compatible order is defined in [Device tree specification](https://github.com/devicetree-org/devicetree-specification/releases/tag/v0.4):
```
The compatible property value consists of one or more strings that define the specific programming model for
the device. This list of strings should be used by a client program for device driver selection. The property
value consists of a concatenated list of null terminated strings, **from most specific to most general**. They allow
a device to express its compatibility with a family of similar devices, potentially allowing a single device driver
to match against several devices.
```
From this perspective, following order should be used:
"st,stm32h7-spi", "st,stm32-spi-fifo", "st,stm32-spi"

**Comment by GeorgeCGV** [comment]
> In any case, about your suggestion, I can't use #if with it because in that context the instance ID is not known unless I'm missing something. Maybe it could be used with COND_CODE_1.

Id is provided in the spi enable macro via init macro.

File: drivers/spi/spi_ll_stm32.c [hunk 12]
```diff
@@ -867,6 +984,11 @@ static int transceive_dma(const struct device *dev,
 	}
 
 #if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	/* Set TSIZE = 0 just in case, somehow, it has a value != 0 from the previous transaction
+	 * (which is a non-tested scenarion for DMA).
+	 */
+	LL_SPI_SetTransferSize(spi, 0);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:983]: Is it safe operation to perform when fifo is not used ?
Why not doing it under fifo-enabled condition ?

File: drivers/spi/spi_ll_stm32.c [hunk 13]
```diff
@@ -718,6 +830,11 @@ static int transceive(const struct device *dev,
 	spi_stm32_cs_control(dev, true);
 
 #ifdef CONFIG_SPI_STM32_INTERRUPT
+
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	LL_SPI_EnableIT_EOT(spi);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:828]: Is it safe operation to perform when fifo is not used ?
Why not doing it under fifo-enabled condition ?

File: drivers/spi/spi_ll_stm32.c [hunk 14]
```diff
@@ -683,6 +782,19 @@ static int transceive(const struct device *dev,
 		spi_context_buffers_setup(&data->ctx, tx_bufs, rx_bufs, 2);
 	}
 
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	if (SPI_OP_MODE_GET(config->operation) == SPI_OP_MODE_MASTER) {
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:779]: I guess this only relates to fifo-enabled operation.
Why not doing it under fifo-enabled condition ?

File: drivers/spi/spi_ll_stm32.c (hunk 8 above)
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:477]: The less changes you do, the more this change is safe. Otrherwise make sure changes are done in dedicated commit with proper justification

File: drivers/spi/spi_ll_stm32.c (hunk 10 above)
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:455]: To avoid confusion a dedicated commit would be welcome

File: drivers/spi/spi_ll_stm32.c [hunk 15]
```diff
@@ -431,14 +463,34 @@ static void spi_stm32_complete(const struct device *dev, int status)
...
+	if (status == 0 && (LL_SPI_GetMode(spi) == LL_SPI_MODE_MASTER)) {
+#ifdef CONFIG_SPI_STM32_INTERRUPT
+		if (ll_func_spi_is_busy(spi)) {
+			return;
+		}
+#else /* CONFIG_SPI_STM32_INTERRUPT */
+		while (ll_func_spi_is_busy(spi)) {
+			/* NOP */
+		}
+#endif
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c]: You're changing function behavior when fifo is not enabled.
It would deserve a proper justification and a dedicated commit if this is justified

File: drivers/spi/spi_ll_stm32.c [hunk 16]
```diff
@@ -454,6 +454,19 @@ static void spi_stm32_cs_control(const struct device *dev, bool on)
...
 
+#ifdef CONFIG_SPI_STM32_INTERRUPT
+static void spi_stm32_disable_irqs(SPI_TypeDef *spi)
+{
+	ll_func_disable_int_tx_empty(spi);
+	ll_func_disable_int_rx_not_empty(spi);
+	ll_func_disable_int_errors(spi);
+
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	LL_SPI_DisableIT_EOT(spi);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:455]: Following functions are now missing. This is not justified in the commit message.
	LL_SPI_DisableIT_DXP(spi);	
	LL_SPI_DisableIT_TXTF(spi);

File: drivers/spi/spi_ll_stm32.c [hunk 17]
```diff
@@ -704,7 +694,7 @@ static int spi_stm32_release(const struct device *dev,
 
 #if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
 static int32_t spi_stm32_count_bufset_frames(const struct spi_config *config,
-	                                     const struct spi_buf_set *bufs)
+	const struct spi_buf_set *bufs)
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:697]: Identation was fine before

File: drivers/spi/spi_ll_stm32.c [hunk 18]
```diff
@@ -725,8 +715,8 @@ static int32_t spi_stm32_count_bufset_frames(const struct spi_config *config,
 }
 
 static int32_t spi_stm32_count_total_frames(const struct spi_config *config,
-	                                    const struct spi_buf_set *tx_bufs,
-	                                    const struct spi_buf_set *rx_bufs)
+	const struct spi_buf_set *tx_bufs,
+	const struct spi_buf_set *rx_bufs)
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:719]: Identation was fine before

**Review by erwango — CHANGES_REQUESTED** [review]
This review has been done in order to provide some guidelines to make this PR structurally safe to merge.
Note that mainly the first commit would need to be reviewed/split in order to minimize potentially harmful changes. The following commits are fine from this point of view.

Also I'd suggest to review the PR organisation in order to first introduce the dt configuration, then add fifo related changes under fifo-enabled condition. The perform useful and harmless cleanups.
Note that, if required, some clean ups can be delayed to a later PR once the initial changes have been sufficiently tested and estimated mature.

Thanks again for your perseverance and dedication

File: drivers/spi/spi_ll_stm32.c (hunk 12 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:983]: The purpose of this was to make the SPI use safer, let me explain. DMA, as it stands now, has only been used in 'endless' mode, that is, with TSIZE = 0. If a 'normal' SPI operation occurs, and after a DMA one is performed, maybe due to some error or malfunction TSIZE could end up with a value different than 0 at the beginning of the DMA transaction. In that case, it would be safer to set TSIZE to 0, as that's the only scenario in which DMA has been tested.

It also adds the semantics to the code of that DMA operations have only been tested under this particular scenario.

As it stands now, it's not possible to perform a non-DMA SPI op. and then a DMA one, because DMA is enabled in Kconfig and then all SPI transactions are necessarily DMA. In that sense, the function call above is unnecessary, yet I added it in case this changes in the future and to add semantics to the code as explained before.

File: drivers/spi/spi_ll_stm32.c (hunk 13 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:828]: My bad, that should happen only if FIFO is enabled.

File: drivers/spi/spi_ll_stm32.c (hunk 14 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:779]: Absolutely, this should happen only if FIFO is enabled.

Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:779]: Yes, it should be under FIFO-enabled operation.

File: drivers/spi/spi_ll_stm32.c (hunk 16 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:455]: @GeorgeCGV requested to remove them because they are not enabled before. You commented as well that you agreed in that. 

In https://github.com/zephyrproject-rtos/zephyr/pull/66503#discussion_r1426617281:

> DXP and TXTF interrupts are never enabled. [...]

**Comment by dgastonochoa** [comment]
> Note that mainly the first commit would need to be reviewed/split in order to minimize potentially harmful changes. 

The first commit functionality is very coupled. TransferSize and EOT must be together in the same commit, as using one without the other would make SPI to stop working. The FIFO usage can be split.

> Note that, if required, some clean ups can be delayed to a later PR once the initial changes have been sufficiently tested and estimated mature.

Given the time this feature is taking, I will leave the non-functional changes (that is, pure source code improvements in terms of splitting in smaller functions etc.) out of this PR.

On another front, is the `fifo-enabled` parameter in the proper `yaml` file?

File: drivers/spi/spi_ll_stm32.c (hunk 17 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:697]: As explained in https://github.com/zephyrproject-rtos/zephyr/pull/66503#discussion_r1426785103, that makes the compliance check to fail.

File: drivers/spi/spi_ll_stm32.c (hunk 18 above)
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:719]: Same as above, indentation check fails as explained in https://github.com/zephyrproject-rtos/zephyr/pull/66503#discussion_r1426785103

File: drivers/spi/spi_ll_stm32.c (hunk 17 above)
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:680]: You can observe yourself that the indentation you propose is not in line with indentation that can be seen otherwise in this file and most of other zephyr c files.
Whatever issue you faced previously, I think the error was elsewhere.
Also, note that if you don't change a line, it won't be inspected by scripts and should not trigger any error.

Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c]: I think the problem was that I had tab size of 4 characters before, which led me to add too many tabs and cause an error. As a consequence, I only wanted to add one tab and then all spaces, which causes another error. The test passes now.

**Comment by avisconti** [comment]
> @GeorgeCGV, @avisconti Would you mind having a try on this proposal ? At least I'd like to be sure that this doesn't break anything when fifo is not enabled (default config)

Just tested the d585d61ee5 set of commits on my sensortile_box_pro board and it works fine as expected. Nevertheless, if I enable spi fifo in device tree (fifo-enabled) it stuck:

``` 
  &spi2 {
         pinctrl-0 = <&spi2_sck_pi1 &spi2_miso_pi2 &spi2_mosi_pi3>;
         pinctrl-names = "default";
         status = "okay";
         fifo-enabled;                                                                                                                              
  
         cs-gpios = <&gpioi 5 GPIO_ACTIVE_LOW>, <&gpioi 7 GPIO_ACTIVE_LOW>;```

**Comment by dgastonochoa** [comment]
@avisconti are you using 8 or 16 bits frames? Could you provide more details about your setup? 

@erwango is it intended to merge this PR after the message from @avisconti?

**Comment by avisconti** [comment]
> @avisconti are you using 8 or 16 bits frames? Could you provide more details about your setup?
> 

I'm not sure about the frame size. The DT setting is as follows, don't know if it is enough:

```
&spi2 {
	pinctrl-0 = <&spi2_sck_pi1 &spi2_miso_pi2 &spi2_mosi_pi3>;
	pinctrl-names = "default";
	status = "okay";

	cs-gpios = <&gpioi 5 GPIO_ACTIVE_LOW>, <&gpioi 7 GPIO_ACTIVE_LOW>;

	lsm6dsv16x: lsm6dsv16x@0 {
		compatible = "st,lsm6dsv16x";
		spi-max-frequency = <DT_FREQ_M(10)>;
		reg = <0>;
		int1-gpios = <&gpioa 4 GPIO_ACTIVE_HIGH>;
		int2-gpios = <&gpiod 11 GPIO_ACTIVE_HIGH>;

		drdy-pin = <2>;
	};

	lis2du12: lis2du12@1 {
		compatible = "st,lis2du12";
		spi-max-frequency = <DT_FREQ_M(10)>;
		reg = <1>;
		int1-gpios = <&gpiof 2 GPIO_ACTIVE_HIGH>;
		int2-gpios = <&gpiof 15 GPIO_ACTIVE_HIGH>;

		drdy-pin = <2>;
	};
};                                                                                
```

**Comment by dgastonochoa** [comment]
@avisconti the frame size won't be visible in devicetree, but in the code itself. It is specified in the SPI config. that is provided as a parameter to the `transceive` function (or `write` or `read`). It is important to know, because 16 bits frames along with the transfer size could explain why it is getting locked.

**Comment by dgastonochoa** [comment]
Kind reminder to @erwango to review this

**Comment by avisconti** [comment]
> @avisconti the frame size won't be visible in devicetree, but in the code itself. It is specified in the SPI config. that is provided as a parameter to the `transceive` function (or `write` or `read`). It is important to know, because 16 bits frames along with the transfer size could explain why it is getting locked.

```
#define LSM6DSV16X_SPI_OP  (SPI_WORD_SET(8) |				\
			 SPI_OP_MODE_MASTER |				\
			 SPI_MODE_CPOL |				\
			 SPI_MODE_CPHA)					\

#define LIS2DU12_SPI_OP  (SPI_WORD_SET(8) |				\
			 SPI_OP_MODE_MASTER |				\
			 SPI_MODE_CPOL |				\
			 SPI_MODE_CPHA)					\

```

It seems to me 8-bit frames.

**Comment by GeorgeCGV** [comment]
Tested, observing the same behavior as @avisconti. The driver is stuck when `fifo-enabled` is set. Therefore, something is off.
@dgastonochoa, 8-bit frames are used in my case.

**Comment by dgastonochoa** [comment]
@avisconti , @GeorgeCGV could you clarify if you have interrupts enabled or not?

**Comment by GeorgeCGV** [comment]
@dgastonochoa interrupts are enabled.

Interestingly, when `LL_SPI_ClearFlag_SUSP(spi);` is added to `spi_stm32_complete` (_where other flags are cleared_), then it works.

**Comment by GeorgeCGV** [comment]
@dgastonochoa no, maybe timing. Tested a bit more. The signal seems ok. When transactions are made with some delays everything seems to work. But performing transactions without any delays leads to the stuck condition within `while (ll_func_spi_is_busy(spi))` in `spi_stm32_complete` where `TSIZE` and `TXC` are `0`.

**Comment by erwango** [comment]
@dgastonochoa, @GeorgeCGV, @avisconti Since we've now validated that change doesn't introduce regression by default and use of fifo is kept a user choice, I think it would be fair to get it merged for v3.6.0 release (code freeze on 02/02).
This being said, it would be  better to have it fully functional, even if we're not there yet.
So I propose to give some time till next week to seek for progress. Then next week, we merge the PR and depending on the status we add a word in the dts binding to mention that this feature is functional under XYZ condition and welcome contributions otherwise. Then I trust @dgastonochoa to provide support to users which would be interested in getting it fully functional.

**Comment by GeorgeCGV** [comment]
@dgastonochoa after some debugging it appears that SPI interrupt is raised after transaction is complete and it gets stuck within "is busy". 

The state of SPI peripheral in that case as follows: `IER` register is `0` (_SPI interrupts are off_), `TSIZE`, `TXC` and `EOT` are `0` while `CTSIZE` is `> 0`. I don't know what triggers the interrupt as `IER` appears to be `0`.

Do you remember what was the `status` within `spi_stm32_complete` in https://github.com/zephyrproject-rtos/zephyr/pull/66503#discussion_r1434097022?

**Comment by dgastonochoa** [comment]
> @dgastonochoa after some debugging it appears that SPI interrupt is raised after transaction is complete and it gets stuck within "is busy".

Thank you very much for this, I will take a look as soon as I can.

> Do you remember what was the status within spi_stm32_complete in https://github.com/zephyrproject-rtos/zephyr/pull/66503#discussion_r1434097022?

Not sure if I understand the question. `status` should be 0, otherwise an error occured.

**Comment by GeorgeCGV** [comment]
@dgastonochoa the issue is gone if we ignore the interrupt that is triggered when SPE is disabled.

Adding

```
	if (!LL_SPI_IsEnabled(spi)) {
		return;
	}
```

to `spi_stm32_complete` after line `452` solves the issue.

What might cause the interrupt?

**Comment by GeorgeCGV** [comment]
@dgastonochoa after removal of `LL_SPI_SetTransferSize(spi, 0);` the interrupt is no longer triggered when SPE is disabled.

File: drivers/spi/spi_ll_stm32.c [hunk 19]
```diff
@@ -683,6 +758,19 @@ static int transceive(const struct device *dev,
 		spi_context_buffers_setup(&data->ctx, tx_bufs, rx_bufs, 2);
 	}
 
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	if (cfg->fifo_enabled && SPI_OP_MODE_GET(config->operation) == SPI_OP_MODE_MASTER) {
```
Comment (GeorgeCGV) [inline drivers/spi/spi_ll_stm32.c:762]:
```suggestion
	if (SPI_OP_MODE_GET(config->operation) == SPI_OP_MODE_MASTER) {
```

to fix hardware CS (_#65802_) when fifo is not used.

File: drivers/spi/spi_ll_stm32.c [hunk 20]
```diff
@@ -460,6 +482,13 @@ static void spi_stm32_complete(const struct device *dev, int status)
 		LL_SPI_ClearFlag_MODF(spi);
 	}
 
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)
+	LL_SPI_ClearFlag_TXTF(spi);
+	LL_SPI_ClearFlag_OVR(spi);
+	LL_SPI_ClearFlag_EOT(spi);
+	LL_SPI_SetTransferSize(spi, 0);
```
Comment (GeorgeCGV) [inline drivers/spi/spi_ll_stm32.c:489]:
```suggestion	
```

Seems to cause extra interrupt when SPE is disabled that leads to SPE stalling when `fifo-enabled` is set. Moreover, the size is going to be set in `transceive` anyway. However, the `transceive` sets it only when `fifo-enabled` is set, that condition should be removed.

File: drivers/spi/spi_ll_stm32.c (hunk 4 above)
Comment (GeorgeCGV) [reply drivers/spi/spi_ll_stm32.c:686]: IMHO
Most drivers in Zephyr are written that way - "_Variables should be declared at the beginning of the block_".
It would be preferable to write new code in a similar way to existing one.

**Comment by dgastonochoa** [comment]
> @dgastonochoa the issue is gone if we ignore the interrupt that is triggered when SPI is disabled.
> 
> Adding
> 
> ```
> 	if (!LL_SPI_IsEnabled(spi)) {
> 		return;
> 	}
> ```
> 
> to `spi_stm32_complete` (_after line `452`_) or `spi_stm32_isr` (_after line `505`_) solves the issue.
> 
> At that point the `IER`, `CR2` registers are `0`. The `SR` register has everything to `0` except `CTSIZE`.
> 
> What might cause the interrupt?

I have been able to reproduce this error by adding another test case to the loopback tests which runs `spi_complete_multiple` 100 times with interrupts enabled. Effectively, the fix you propose works. Thanks for it. 

I'm happy to add you as co-author to the PR or commits if you wish (and if you tell me how to do it)

> [...] Seems to cause extra interrupt when SPI is disabled that leads to SPI stalling when fifo-enabled is set. [...]

With regards to this, I have tried the fix above with and without this change and I saw no changes. Have you seen this affecting the driver when FIFO is enabled? If not, If the interrupt is triggered as you mention, that is a problem and needs to be fixed. However, I would rather do so in a different PR to keep this one's scope as narrow as possible, as we agreed in previous comments. 

Also, as far as I can see, the driver enables interrupts only after the SPI periph. has been enabled, right? I don't see how the errata in _2.18.3 TXP interrupt occurring while SPI disabled_ applies.

> [...] to fix hardware CS (https://github.com/zephyrproject-rtos/zephyr/pull/65802) when fifo is not used. That fixes H7's "2.18.3 TXP interrupt occurring while SPI disabled" errata as well. [...]

About this, doing the change you propose would make the driver to use EOT and TransferSize even when FIFO is not enabled, which is the problem we wanted to avoid by allowing to enable FIFO from devicetree, but leaving it disabled by default. I would rather treat the problem described in #65802 in a different PR (that PR).

**Comment by GeorgeCGV** [comment]
@dgastonochoa it is enough to set the transfer size once to avoid extra spurious interrupt (_before the transaction starts, there is no need to set it to 0 at the end_). IMHO, that should be better for performance as well.

Note: if `EOT` and `TransferSize` are not used for non `fifo-enabled` SPI on H7, then spurious interrupt will happen for such SPI instances. However, that fixes it for `fifo-enabled` SPI instances on H7 (_as long as `TransferSize` is not set to `0` at the end_).

> I'm happy to add you as co-author to the PR or commits if you wish (and if you tell me how to do it)

I am not against.

To add a co-author the commit message has to contain the same information as `Signed-off-by:`, like `Co-authored-by: Georgij Cernysiov <geo.cgv@gmail.com>`.

File: dts/bindings/spi/st,stm32h7-spi.yaml [hunk 21]
```diff
@@ -27,3 +27,7 @@ properties:
     description: |
       (Master SS Idleness) minimum clock inserted between
       start and first data transaction.
+
+  fifo-enabled:
```
Comment (GeorgeCGV) [inline dts/bindings/spi/st,stm32h7-spi.yaml:31]: Maybe it is better to rename it to `fifo-enable` to stay consistent with STM32 serial driver: https://github.com/zephyrproject-rtos/zephyr/blob/346997f8be66565ed8d5fe5d4ff1f8078ff8dec1/dts/bindings/serial/st%2Cstm32-uart-base.yaml#L90

Comment (dgastonochoa) [reply dts/bindings/spi/st,stm32h7-spi.yaml:31]: I would rather suggest to modify `fifo-enable` to `fifo-enabled`, which is semantically correct in my opinion. I have inspected it and there aren't many occurrences of the "current" `fifo_enable`, so it would be simple to modify. I would understand modifying this PR if `fifo-enable` was used in many places, but it's not the case.

Comment (erwango) [reply dts/bindings/spi/st,stm32h7-spi.yaml:31]: `fifo-enable` is actually already used out of tree and in other bindings. I don't think the arguable semantic difference is worth the trouble.

**Comment by GeorgeCGV** [comment]
Overall LGTM, but extra interrupt is bothering.

@avisconti could you please test if on your target it works as expected when the following is removed:

`LL_SPI_SetTransferSize(spi, 0);`

and 

```
if (!LL_SPI_IsEnabled(spi)) {
	return;
}
``` 
for fifo enabled SPI? It can fail for other **non** fifo enabled SPIs.

**Comment by erwango** [comment]
Thanks @dgastonochoa @GeorgeCGV for your work so far.
Question on the current state of things today:
- Can we consider the change is safe with fifo disabled ? (I expect a yes, but a confirmation would be nice)
- Is it functional with fifo-enabled (and if not fully, to which extent ?)  => Would not be a blocker in any case,as already mentioned

**Comment by GeorgeCGV** [comment]
> Can we consider the change is safe with fifo disabled ? (I expect a yes, but a confirmation would be nice)

It works when fifo is disabled, but adds extra operations that are not required.

For example: we don't enable `EOT` and `TransferSize` for non fifo enabled devices, but `LL_SPI_SetTransferSize(spi, 0);` is invoked as well as related flags clearing and IRQ disable on transfer completion. Probably, all fifo related code should be within `if (cfg->fifo_enabled)` condition. 

> Is it functional with fifo-enabled (and if not fully, to which extent ?) => Would not be a blocker in any case as already mentioned

It works. However, for me a spurious interrupt is raised when `LL_SPI_SetTransferSize(spi, 0);` is present. Added condition `if (!LL_SPI_IsEnabled(spi))` within IRQ handler solves the "stuck" condition.

When I remove the transfer size reset to 0, it works as expected (doesn't raise the spurious interrupt). It would be great to check that on other targets.

**Comment by erwango** [comment]
> Probably, all fifo related code should be within `if (cfg->fifo_enabled)` condition.

@dgastonochoa Can you take care of that ?

**Comment by dgastonochoa** [comment]
> > Probably, all fifo related code should be within `if (cfg->fifo_enabled)` condition.
> 
> @dgastonochoa Can you take care of that ?



> > Probably, all fifo related code should be within `if (cfg->fifo_enabled)` condition.
> 
> @dgastonochoa Can you take care of that ?

Yes.

The last commit ignores the spurious interrupt; I'm hesitant about doing that only if the fifo is enabled as well. @GeorgeCGV ?

**Comment by GeorgeCGV** [comment]
> > > Probably, all fifo related code should be within `if (cfg->fifo_enabled)` condition.
> > 
> > 
> > @dgastonochoa Can you take care of that ?
> 
> Yes.
> 
> The last commit ignores the spurious interrupt; I'm hesitant about doing that only if the fifo is enabled as well. @erwango, @GeorgeCGV ?

It worked before, so it is up to you. I guess erratas can be dealt with when they happen.

**Comment by erwango** [comment]
> I'm hesitant about doing that only if the fifo is enabled as well.

I'm a bit blur about the exact context, but my recommendation, is to keep previous fifo disabled behavior untouched. As mention by @GeorgeCGV, if this is linked to already present real issues, they are already there and we can deal with them later on if problem arise.

**Review by GeorgeCGV — APPROVED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: drivers/spi/spi_ll_stm32.c [hunk 22]
```diff
@@ -1161,6 +1163,7 @@ static const struct spi_stm32_config spi_stm32_cfg_##id = {		\
 	.pclken = pclken_##id,						\
 	.pclk_len = DT_INST_NUM_CLOCKS(id),				\
 	.pcfg = PINCTRL_DT_INST_DEV_CONFIG_GET(id),			\
+	.fifo_enabled = SPI_FIFO_ENABLED(id),				\
```
[the remark this answers is not in the document]
Comment (dgastonochoa) [reply drivers/spi/spi_ll_stm32.c:1274]: I tried this some time ago, but it made some devices to fail. If a DT node has a `st.stm32..spi` compatible but not the one whose `yaml` file declares `fifo-enable`, the build fails.

[the remark this answers is not in the document]
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:1274]: I see, property is only visible within stm32h7 binding. Let's go with this proposal. We'll try to find a better looking solution afterwards.

**Review by erwango — APPROVED** [review]

**Comment by GeorgeCGV** [comment]
@dgastonochoa unfortunate news. Tested on real scenarios and observing spi with enabled fifo to still getting in a stuck condition awaiting looping within EOT checks. I can't dive deeper at the moment, time...

**Comment by dgastonochoa** [comment]
@GeorgeCGV unfortunate news indeed. Could you provide a few more details about the error? I imagine it happens with 8 bits frames and when rebooting many times, right?

**Comment by GeorgeCGV** [comment]
> @GeorgeCGV unfortunate news indeed. Could you provide a few more details about the error? I imagine it happens with 8 bits frames and when rebooting many times, right?

The same configuration as before (yes. 8 bit frames). No, this time it was happening at runtime with the system "under load" (many SPI exchanges).

**Comment by dgastonochoa** [comment]
> The same configuration as before (yes. 8 bit frames). No, this time it was happening at runtime with the system "under load" (many SPI exchanges).

@GeorgeCGV I have tried running the `spi_complete_multiple` test (in the loopback tests) 1000 times in a row and it works with both fast and slow configurations. Please, could you provide more details about the scenario under which you see it failing? In particular, how many buffers are being sent (in `spi_buf_set`) and how long they are. Also, what speed is SPI configured to. Maybe it's simpler to copy the code snippet that sets the transaction, along with the `devicetree` details. 

Thanks

**Comment by dgastonochoa** [comment]
@GeorgeCGV I have also tried running 1000 2-byte SPI read operation against a sensor with an SPI interface and I haven't found any problem.

Unless there is more info., I won't do anything else about this.

Thanks

**Comment by GeorgeCGV** [comment]
@dgastonochoa sorry for the delay. We tested it on the recent main once more. The problem exists on SPI with several devices. It looks like it works fine on the bus with one device. I hope to get back to the topic one day to provide more information.
