### PR TITLE
lib: posix: fix a wrong type in mqueue.c

### LINKED ISSUE #11133: lib/posix/mqueue.c: WARNING: Unsigned expression compared with zero
Found using Coccinelle.
https://github.com/zephyrproject-rtos/zephyr/pull/11132
```
himanshu@himanshu-Vostro-3559:~/zephyr$ ./scripts/coccicheck --mode=report --cocci=scripts/coccinelle/unsigned_lesser_than_zero.cocci --verbose=1 lib/

Please check for false positives in the output before submitting a patch.
When using "patch" mode, carefully review the patch before submitting it.

Processing unsigned_lesser_than_zero.cocci
with option(s) ""

Message example to submit a patch:
 Unsigned expressions cannot be lesser than zero. Presence of
 comparisons 'unsigned (<|<=) 0' often indicates a bug,
 usually wrong type of variable.

 The semantic patch that makes this report is available
 in scripts/coccinelle/unsigned_lesser_than_zero.cocci.

 More information about semantic patching is available at
 http://coccinelle.lip6.fr/

Running (4 in parallel): /usr/local/bin/spatch -D report --no-show-diff --very-quiet --cocci-file scripts/coccinelle/unsigned_lesser_than_zero.cocci --patch /home/himanshu/zephyr --dir lib/ --jobs 4 --chunksize 1
lib/posix/mqueue.c:71:45-53: WARNING: Unsigned expression compared with zero.
lib/posix/mqueue.c:72:10-18: WARNING: Unsigned expression compared with zero.
```

### PR DESCRIPTION
**Pull request by nniranjhana**
`mq_maxmsg` and `mq_msgsize` are defined to be of type `long` in [POSIX standard](http://man7.org/linux/man-pages/man3/mq_getattr.3.html#DESCRIPTION). So use `long` for variables that hold its value in `mq_open()`.

Fixes #11133 

Signed-off-by: Niranjhana N <niranjhana.n@intel.com>

### CODE REVIEW

**Review by pfalcon — APPROVED** [review]
Looks good as a patch in "Trivial" category.

File: lib/posix/mqueue.c [hunk 1]
```diff
@@ -51,7 +51,7 @@ mqd_t mq_open(const char *name, int oflags, ...)
 	va_list va;
 	mode_t mode;
 	mq_attr *attrs = NULL;
-	u32_t msg_size = 0, max_msgs = 0;
+	s32_t msg_size = 0, max_msgs = 0;
```
Comment (ceolin) [inline lib/posix/mqueue.c]: why don't you use long here ? You are casting long to s32_t that still not right.

**Review by ceolin — CHANGES_REQUESTED** [review]

**Comment by andrewboie** [comment]
I concur with flavio; if the API uses a long, why are we using fixed-sized types? Is this some misguided MISRA fix? We are just going to trip over this if we ever support a 64-bit arch.

**Comment by pfalcon** [comment]
People just don't want to embrace concept of a "Trivial" fix from PR processing RFC, https://docs.google.com/document/d/1dSLSTckOgCeBh8MrU4AgpjkR6hQ0IikPnreAOO_wWGY/edit . Half (or so) of "POSIX subsystem" needs fixing otherwise, oftentimes in "pulled as a string fashion". Last time I touched it, I was swamped by it for 2 weeks.

So, we really need to learn to appreciate simple fixes: if it's not incorrect, i.e. moves in the right direct, let it be. Otherwise, we'll just scare away people from submitting fixes. I for one already scared away - after https://github.com/zephyrproject-rtos/zephyr/pull/10429, I wanted to apply to be a CODEOWNER for POSIX, but after I was made to go thru "why don't we go and have per-thread file descriptors?" kind of review, I decided that I have enough stuff to care about already ;-).

**Review by tyrantlizard77 — DISMISSED** [review]
>  i.e. moves in the right direct, let it be.

This doesn't move in the right direction, so NACK
We have someone working on an x86_64 port right now, it currently runs in X32 mode but won't always and this will just have to get fixed.
Are you going to whine forever about the file descriptors thing? Let it go.

**Comment by pfalcon** [comment]
> This doesn't move in the right direction

It's good if you're sure about it, just wanted to remind about the other side in the process. The truth is somewhere in the middle of course.

> Let it go.

I will, but what about all other contributors which may get into similar situations? (It's not me who mass-closed a bunch of PRs in frustration for example.) TSC seems to be concerned how to improve the PR process, and I'm trying to help as I can (which includes raising awareness of hardnesses of contribution by those who don't have "commit access").

**Comment by nniranjhana** [comment]
@pfalcon @ceolin @andrewboie Sorry guys, I have modified it to use `long` now. Is this fix okay now?

I did think of it at first, but saw that in a lot of places (for example, in `mq_timedsend`) the function argument passed an int type (pointer to `abstime`), but the local variable to handle it was defined as `s32_t` or `u32_t`.. I checked the range for both `s32_t` and `long`, and seeing it was the same, used it to keep with the convention I thought we were using.

**Review by ceolin — APPROVED** [review]

**Review by spoorthik — APPROVED** [review]
