### PR TITLE
stm32 DMA driver bindings new packaging

### LINKED ISSUE #34543: STM32F1 failed to compile with CONFIG_UART_ASYNC_API
**Describe the bug**
Testing nucleo_f103rb board, with my own code or the tests/drivers/uart/uart_async_api code, the compile fails.

**To Reproduce**
1. Configure a board with STM32F1 SoC, e.g, nucleo_f103rb
2. $ west build -p auto -b nucleo_f103rb --cmake ./zephyr/tests/drivers/uart/uart_async_api/
3. See error
```
/zephyr/drivers/dma/dma_stm32.c: In function 'dma_stm32_configure':
/zephyr/drivers/dma/dma_stm32.c:464:16: error: 'LL_DMA_InitTypeDef' has no member named 'PeriphRequest'
  464 |  DMA_InitStruct.PeriphRequest = config->dma_slot;
      |                ^
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: 
```

**Expected behavior**
Compile should pass.

**Impact**
annoyance

**Logs and console output**
as above

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.12.3
 - Zephyr version: 2.5.99

**Additional context**
I believe DMA_InitStruct.PeriphRequest  is only used by SoCs that support dmamux. STM32F1 does not.
Adding the following seems to fix the problem.
```
	#if defined(DMAMUX1)
	DMA_InitStruct.PeriphRequest = config->dma_slot;
	#endif
```

### PR DESCRIPTION
**Pull request by FRASTM**
With this definition of the dma bindings, a new type of stm32 DMA version is supported.
For stm32F1 and stm32L1 soc, the DMA is of type V2 without dma request : named _V2bis_
A generic stm32-dma is introduced as a basis for all the stm32 dma types. The the `#dma-cells` is specified in the .yaml for each stm32 dma version, with a specific nb of elements.
- For the V1: stm32 F2, F4, F7, H7 : the dma instance has a Fifo the dma-cells has 4 (all) elements
- For the V2: stm32 F0, F3, G0,G4,WB, L0, L4,L5  : the dma instance has no Fifo, the dma-cells has 3 elements (no 'feature')
- For the V2bis: stm32 F1, L1 : the dma instance has only one possible request and no fifo ; the dma-cells has 2 elements (no 'slot', no 'feature')
- For the dmamux, the 'feature' element is not used --> removed from #dma-cells (3 elements)

Fixes #34543

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
tests/drivers/spi/spi_loopback  successfully  tested with nucleo_l152re, nucleo_g071rb, nucleo_l476, nucleo_f767.
(Note that stm32f767 should require a cache disable)

**Review by erwango — CHANGES_REQUESTED** [review]
Looks good in general.

Though, I wonder if this should be considered as an API change as it will have impact on out of tree users.

File: drivers/dma/dma_stm32.h [hunk 1]
```diff
@@ -75,7 +75,7 @@ bool dma_stm32_is_fe_active(DMA_TypeDef *DMAx, uint32_t id);
 void dma_stm32_clear_fe(DMA_TypeDef *DMAx, uint32_t id);
 #endif
 
-#ifdef CONFIG_DMA_STM32_V2
+#if defined(CONFIG_DMA_STM32_V2) || defined(CONFIG_DMA_STM32_V2BIS)
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/dma/dma_stm32.h]: yes

File: dts/bindings/dma/st,stm32-dma-v1.yaml [hunk 2]
```diff
@@ -71,32 +70,11 @@ description: |
...
-      description: >
-        offset in the table of channels when mapping to a DMAMUX
-        for 1st dma instance, offset is 0,
-        for 2nd dma instance, offset is the nb of dma channels of the 1st dma,
-        for 3rd dma instance, offset is the nb of dma channels of the 2nd dma
-        plus the nb of dma channels of the 1st dma instance, etc.
-
     "#dma-cells":
-      const: 4
+        const: 4
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply dts/bindings/dma/st,stm32-dma-v1.yaml]: Because the #dma-cells  does not appear in the (common) dts/bindings/dma/st,st32-dma.yaml
it has not to be in a 'property-blocklist'.

File: drivers/serial/uart_stm32.c [hunk 3]
```diff
@@ -1493,12 +1493,18 @@ static int uart_stm32_pm_control(const struct device *dev,
 #define DMA_CTLR(id, dir)						\
 	DT_INST_DMAS_CTLR_BY_NAME(id, dir)
 
+#if !DT_HAS_COMPAT_STATUS_OKAY(st_stm32_dma_v2bis)
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/serial/uart_stm32.c:1496]: I think that talking about `st_stm32_dma_v2bis` here gives more contextual information than 
`#if DT_INST_PHA_HAS_CELL(id, dma-cells , slot)`

File: drivers/dma/Kconfig.stm32 [hunk 4]
```diff
@@ -25,7 +26,8 @@ config DMA_STM32_V1
 
 config DMA_STM32_V2
 	bool
-	default y if $(dt_compat_enabled,$(DT_COMPAT_ST_STM32_DMA_V2))
+	default y if $(dt_compat_enabled,$(DT_COMPAT_ST_STM32_DMA_V2)) \
+			|| $(dt_compat_enabled,$(DT_COMPAT_ST_STM32_DMA_V2BIS))
 	help
 	  Enable DMA V2 support.
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/dma/Kconfig.stm32:32]: done

**Comment by FRASTM** [comment]
Rebase, 
Add comment in the drivers/dma/Kconfig.stm32
Change the definition of the dma-cells for the qspi instance of the disco-l475-iot1
and add one comment to the st,stm32-qspi.yaml

**Comment by FRASTM** [comment]
rebase after merge of the #34826

File: drivers/serial/uart_stm32.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/serial/uart_stm32.c:1496]: Ok. Though, instead of adding this in each driver supporting DMA, please move this to dma_stm32.h.

File: tests/drivers/spi/spi_loopback/boards/nucleo_f411re.conf [hunk 5]
```diff
@@ -1,8 +0,0 @@
-CONFIG_SPI_LOOPBACK_DRV_NAME="SPI_1"
```
Comment (erwango) [inline tests/drivers/spi/spi_loopback/boards/nucleo_f411re.conf:1]: Why is this one removed ?

**Review by erwango — CHANGES_REQUESTED** [review]
Few comments, but this clean up really adds value.

File: drivers/dma/Kconfig.stm32 [hunk 6]
```diff
@@ -25,9 +26,14 @@ config DMA_STM32_V1
...
+	  Set DT_COMPAT_ST_STM32_DMA_V2BIS when the DMA V2 instance has all
+	  the requests from the peripherals simply logically ORed to one
+	  input request, like in the stm32F1 or stm32L1 soc families.
+	  Note that a DMA of type V2bis has a same driver code as V2.
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/dma/Kconfig.stm32:36]: ok, modified

File: include/dt-bindings/dma/stm32_dma.h [hunk 7]
```diff
@@ -28,7 +28,11 @@
...
 #define STM32_DMA_CONFIG_PRIORITY(config)		((config >> 16) & 0x3)
 
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_dma_v1)
 /* macros for features */
 #define STM32_DMA_FEATURES_FIFO_THRESHOLD(features)	(features & 0x3)
+#else
+#define STM32_DMA_FEATURES_FIFO_THRESHOLD(features)	0
+#endif
 
 #endif /* ZEPHYR_INCLUDE_DT_BINDINGS_DMA_STM32_DMA_H_ */
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply include/dt-bindings/dma/stm32_dma.h:38]: yes, transfer of macro is possible.

File: drivers/dma/Kconfig.stm32 [hunk 8]
```diff
@@ -25,9 +26,16 @@ config DMA_STM32_V1
...
+	default y if $(dt_compat_enabled,$(DT_COMPAT_ST_STM32_DMA_V2)) \
+			|| $(dt_compat_enabled,$(DT_COMPAT_ST_STM32_DMA_V2BIS))
 	help
 	  Enable DMA V2 support.
+	  "DMA_STM32_V2 symbol controls code that is common to both st,stm32-dma
+	  and st,stm32-dma-v2bis compatible. Behavior difference between these bindings
+	  is that the st,stm32-dma-v2bis has all the requests from the peripherals
+	  logically ORed to one input request, like in the stm32F1 or stm32L1.
+	  DMA_STM32_V2BIS is enabled using compatible specific macros.
+	  Note that a DMA of type V2bis has a same driver code as V2.
```
Comment (erwango) [inline drivers/dma/Kconfig.stm32:38]:
```suggestion
	  DMA_STM32_V2 symbol controls code that is common to both "st,stm32-dma"
	  and "st,stm32-dma-v2bis" compatibles. Behavior difference between these bindings
	  is that the "st,stm32-dma-v2bis" has all the requests from the peripherals
	  logically ORed to one input request, like in the STM32F1 or STM32L1.
	  Note that a DMA of type V2bis has a same driver code as V2, and
	  V2bis specific code is controller using compatible specific macros.
```

Refering to DMA_STM32_V2BIS is misleading as this Kconfig symbol does not exist

File: CODEOWNERS [hunk 9]
```diff
@@ -457,7 +457,6 @@
 /include/display/                         @vanwinkeljan
 /include/dt-bindings/clock/kinetis_mcg.h  @henrikbrixandersen
 /include/dt-bindings/clock/kinetis_scg.h  @henrikbrixandersen
-/include/dt-bindings/dma/stm32_dma.h      @cybertale
```
Comment (erwango) [inline CODEOWNERS:460]: Please also remove references to #include <dt-bindings/dma/stm32_dma.h> in various drivers

**Review by erwango — CHANGES_REQUESTED** [review]

File: CODEOWNERS (hunk 9 above)
Comment (FRASTM) [reply CODEOWNERS:460]: --> drivers/spi/spi_ll_stm32.c
--> drivers/i2s/i2s_ll_stm32.c
--> drivers/sperialuart_stm32.c
--> drivers/flash/flash_stm32_qspi.c

File: drivers/dma/Kconfig.stm32 (hunk 8 above)
Comment (FRASTM) [reply drivers/dma/Kconfig.stm32]: ok

**Comment by FRASTM** [comment]
replace #include <dt-bindings/dma/stm32_dma.h> with #include <drivers/dma/stm32_dma.h> when needed

**Comment by FRASTM** [comment]
rebase
add the stm32f3 disco board for the tests/drivers/spi/spi_loopback 
add the nucleo_l152re board for the tests/drivers/spi/spi_loopback

File: drivers/serial/uart_stm32.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/serial/uart_stm32.c:1496]: Deifning a `STM32_DMA_SLOT` would be required so we don't have to repeat this in each driver

**Review by erwango — CHANGES_REQUESTED** [review]
One comment.

Also, we need to add a specific code for existing users to detect newly wrong configuration (4 cells with compat dma-v2) and either trig an error (if there's no way to overcome the error) or generate a warning and continue if we can still compile.

**Comment by FRASTM** [comment]
rebase
defining the DMA_SLOT for any dma type in the include/dt-bindings/dma/stm32_dma.h like the macro for the features does.

**Comment by FRASTM** [comment]
add ./tests/drivers/spi/spi_loopback/boards for nucleo_g431rb
add ./tests/drivers/uart/uart_async_api/boards for nucleo_g474re

**Comment by FRASTM** [comment]
add one commit to move the definition of the macro (proefixed with STM32_) to the include/drivers/dma/dma_stm32.h header file (instead of include/dt-bindings/dma/stm32_dma.h, suppressed)

File: dts/bindings/dma/st,stm32-dma-v2bis.yaml [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+    "#dma-cells":
+      const: 2
+
+# Parameter syntax of stm32 follows the dma client dts syntax
+# in the Linux kernel declared in
+# https://git.kernel.org/pub/scm/linux/kernel/git/devicetree/devicetree-rebasing.git/plain/Bindings/dma/st,stm32-dma.yaml
+
+# Parameter syntax of stm32 follows the dma client dts syntax
+# in the Linux kernel declared in
+# https://git.kernel.org/pub/scm/linux/kernel/git/devicetree/devicetree-rebasing.git/plain/Bindings/dma/st,stm32-dma.yaml
```
Comment (erwango) [inline dts/bindings/dma/st,stm32-dma-v2bis.yaml:77]: Duplicate

File: dts/bindings/dma/st,stm32-dma.yaml [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+
+    st,mem2mem:
+      type: boolean
+      required: false
+      description: If the DMA controller V1 supports memory to memory transfer
+
+    dma-offset:
+      type: int
+      required: false
+      description: >
```
Comment (erwango) [inline dts/bindings/dma/st,stm32-dma.yaml:33]: New recommendation is to use:
```suggestion
      description: |
```

File: dts/bindings/dma/st,stm32-dmamux.yaml [hunk 12]
```diff
@@ -55,10 +54,11 @@ description: |
     for client SPI of stm32wb55x
      spi1: spi@40013000 {
          compatible = "st,stm32-spi";
-         dmas = <&dmamux1 11 7 0x20440 0
-         &dmamux1 1 6 0x20480 0>;
+         dmas = <&dmamux1 11 7 0x20440
+         &dmamux1 1 6 0x20480>;
```
Comment (erwango) [inline dts/bindings/dma/st,stm32-dmamux.yaml:58]: Xould be nice to fix indentation, while we're at it

File: drivers/spi/spi_ll_stm32.c [hunk 13]
```diff
@@ -858,37 +858,30 @@ static void spi_stm32_irq_config_func_##id(const struct device *dev)		\
...
 
-#define DMA_CHANNEL_CONFIG(id, dir)					\
-		DT_INST_DMAS_CELL_BY_NAME(id, dir, channel_config)
-#define DMA_FEATURES(id, dir)						\
-		DT_INST_DMAS_CELL_BY_NAME(id, dir, features)
-#define DMA_CTLR(id, dir)						\
-		DT_INST_DMAS_CTLR_BY_NAME(id, dir)
-
 #define SPI_DMA_CHANNEL_INIT(index, dir, dir_cap, src_dev, dest_dev)	\
-	.dma_dev = DEVICE_DT_GET(DMA_CTLR(index, dir)),			\
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:869]: For consistency, either do the same change in uart driver in this commit as well.
Either move this to another commit

File: soc/arm/st_stm32/stm32f7/soc.c [hunk 14]
```diff
@@ -32,11 +32,13 @@ static int st_stm32f7_init(const struct device *arg)
 
 	key = irq_lock();
 
+#ifndef CONFIG_NOCACHE_MEMORY
```
Comment (erwango) [inline soc/arm/st_stm32/stm32f7/soc.c:35]: This can't be done in current PR

File: dts/arm/st/l1/stm32l1.dtsi [hunk 15]
```diff
@@ -419,6 +419,16 @@
 			status = "disabled";
 			label = "EEPROM_0";
 		};
+
+		dma1: dma@40026000 {
```
Comment (erwango) [inline dts/arm/st/l1/stm32l1.dtsi:423]: Please do this in a dedicated commit/PR

File: drivers/serial/uart_stm32.c [hunk 16]
```diff
@@ -1502,7 +1502,7 @@ static int uart_stm32_pm_control(const struct device *dev,
 	.dma_dev = DEVICE_DT_GET(DMA_CTLR(index, dir)),			\
 	.dma_channel = DT_INST_DMAS_CELL_BY_NAME(index, dir, channel),	\
 	.dma_cfg = {							\
-		.dma_slot = DT_INST_DMAS_CELL_BY_NAME(index, dir, slot),\
+		.dma_slot = DMA_SLOT(index, dir, slot),\
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:1505]: DMA_SLOT is not defined

**Review by erwango — CHANGES_REQUESTED** [review]

File: dts/bindings/dma/st,stm32-dma-v2bis.yaml (hunk 10 above)
Comment (FRASTM) [reply dts/bindings/dma/st,stm32-dma-v2bis.yaml:77]: removing duplicates

File: dts/bindings/dma/st,stm32-dma.yaml (hunk 11 above)
Comment (FRASTM) [reply dts/bindings/dma/st,stm32-dma.yaml:33]: changed

File: soc/arm/st_stm32/stm32f7/soc.c (hunk 14 above)
Comment (FRASTM) [reply soc/arm/st_stm32/stm32f7/soc.c:35]: ok

File: dts/arm/st/l1/stm32l1.dtsi (hunk 15 above)
Comment (FRASTM) [reply dts/arm/st/l1/stm32l1.dtsi:423]: is it correct if `dma1: dma@40026000 `  is set in the overlay of the **nucleo_152re** for the _test/drivers/spi/spi_loopback_ ?

File: dts/bindings/dma/st,stm32-dmamux.yaml (hunk 12 above)
Comment (FRASTM) [reply dts/bindings/dma/st,stm32-dmamux.yaml:58]: done

**Comment by FRASTM** [comment]
including changes from comments
spi tests for nucleo_l15re is in a separated PR

File: drivers/serial/uart_stm32.c (hunk 16 above)
Comment (FRASTM) [reply drivers/serial/uart_stm32.c]: changed

File: drivers/spi/spi_ll_stm32.c (hunk 13 above)
Comment (FRASTM) [reply drivers/spi/spi_ll_stm32.c:869]: in this commit ab764e3335214bfc8ef4a036b851d7f03e96521f
```
-	.dma_dev = DEVICE_DT_GET(DMA_CTLR(index, dir)),			\
+	.dma_dev = DEVICE_DT_GET(STM32_DMA_CTLR(index, dir)),			\
```
 for _both_ drivers drivers/spi/for spi_ll_stm32.c  and drivers/serial/uart_stm32.c

File: drivers/serial/Kconfig.stm32 [hunk 17]
```diff
@@ -5,6 +5,7 @@
 
 DT_COMPAT_ST_STM32_DMA_V1 := st,stm32-dma-v1
 DT_COMPAT_ST_STM32_DMA_V2 := st,stm32-dma-v2
+DT_COMPAT_ST_STM32_DMA_V2BIS := st,stm32-dma-v2bis
```
Comment (erwango) [inline drivers/serial/Kconfig.stm32:8]: Please move this in a dedicated commit

File: drivers/serial/uart_stm32.c [hunk 18]
```diff
@@ -1490,38 +1490,32 @@ static int uart_stm32_pm_control(const struct device *dev,
...
-#define DMA_CTLR(id, dir)						\
-	DT_INST_DMAS_CTLR_BY_NAME(id, dir)
 
 /* src_dev and dest_dev should be 'MEMORY' or 'PERIPHERAL'. */
 #define UART_DMA_CHANNEL_INIT(index, dir, dir_cap, src_dev, dest_dev)	\
-	.dma_dev = DEVICE_DT_GET(DMA_CTLR(index, dir)),			\
+	.dma_dev = DEVICE_DT_GET(STM32_DMA_CTLR(index, dir)),			\
 	.dma_channel = DT_INST_DMAS_CELL_BY_NAME(index, dir, channel),	\
 	.dma_cfg = {							\
 		.dma_slot = DT_INST_DMAS_CELL_BY_NAME(index, dir, slot),\
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:1499]: `STM32_DMA_SLOT`

File: CODEOWNERS [hunk 19]
```diff
@@ -461,7 +461,6 @@
...
```
Comment (erwango) [inline CODEOWNERS:464]: This change should be moved to another appropriate commit

File: dts/bindings/dma/st,stm32-dma.yaml (hunk 11 above)
Comment (erwango) [reply dts/bindings/dma/st,stm32-dma.yaml:33]: Not resolved

File: include/dt-bindings/dma/stm32_dma.h [hunk 20]
```diff
@@ -1,34 +0,0 @@
-/*
```
Comment (erwango) [inline include/dt-bindings/dma/stm32_dma.h:1]: This change should be moved to another commit

File: tests/drivers/spi/spi_loopback/boards/nucleo_f411re.conf (hunk 5 above)
Comment (erwango) [inline tests/drivers/spi/spi_loopback/boards/nucleo_f411re.conf:1]: Why is that removed ?

File: tests/drivers/spi/spi_loopback/boards/nucleo_f746zg.conf [hunk 21]
```diff
@@ -1,2 +1,10 @@
 CONFIG_SPI_LOOPBACK_DRV_NAME="SPI_1"
-CONFIG_SPI_STM32_INTERRUPT=y
```
Comment (erwango) [inline tests/drivers/spi/spi_loopback/boards/nucleo_f746zg.conf:2]: I'm not sure we need to convert all tests to use DMA, as we won't test IRQ mode anymore in the end

**Review by erwango — CHANGES_REQUESTED** [review]
Some clean up required.
Also we miss a test to generate a warning that would detect wrong configurations (excessive number of cells), to help current users identifying the change and updating their out of tree configurations.

File: drivers/serial/Kconfig.stm32 (hunk 17 above)
Comment (FRASTM) [reply drivers/serial/Kconfig.stm32:8]: removing all the _tests_ stuff

Comment (FRASTM) [reply drivers/serial/Kconfig.stm32:8]: In case there is a element missing in the dma-cells, the building will fail with something like:
```
nucleo_f746zg.dts.pre.tmp:2550.2-2551.22: Warning (dmas_property): /soc/spi@40013000:dmas: cell 5 is not a phandle reference
nucleo_f746zg.dts.pre.tmp:295.22-304.5: Warning (dmas_property): /soc/spi@40013000: Missing property '#dma-cells' in node /clocks/pll or bad phandle (referred from dmas[5])
  also defined at nucleo_f746zg.dts.pre.tmp:2411.20-23
  also defined at nucleo_f746zg.dts.pre.tmp:2504.7-2508.3
  also defined at nucleo_f746zg.dts.pre.tmp:2549.7-2553.3
devicetree error: <Node /clocks/pll in 'nucleo_f746zg.dts.pre.tmp'> lacks #dma-cells

```

File: CODEOWNERS (hunk 19 above)
Comment (FRASTM) [reply CODEOWNERS:464]: moved to commit a6a6897b79e1640192697e45197a834be64d99ff

File: drivers/serial/uart_stm32.c (hunk 18 above)
Comment (FRASTM) [reply drivers/serial/uart_stm32.c:1499]: shouldn't the .dma_dev be made by the STM32_DMA_CTLR ?

File: include/dt-bindings/dma/stm32_dma.h (hunk 20 above)
Comment (FRASTM) [reply include/dt-bindings/dma/stm32_dma.h:1]: moved to commit a6a6897

File: tests/drivers/spi/spi_loopback/boards/nucleo_f746zg.conf (hunk 21 above)
Comment (FRASTM) [reply tests/drivers/spi/spi_loopback/boards/nucleo_f746zg.conf]: Ok to  modify only the existing test cases

File: drivers/serial/Kconfig.stm32 (hunk 17 above)
Comment (erwango) [reply drivers/serial/Kconfig.stm32:8]: ok, then we'll need to send a mail to users & dev list to inform of this change.

Comment (erwango) [reply drivers/serial/Kconfig.stm32:8]: What about the case when there is one too much ?

File: drivers/serial/uart_stm32.c (hunk 18 above)
Comment (erwango) [reply drivers/serial/uart_stm32.c:1499]: Sure

File: drivers/serial/Kconfig.stm32 (hunk 17 above)
Comment (FRASTM) [reply drivers/serial/Kconfig.stm32:8]: in case there is an extra parameter, the error comes in the building as well:
```
stm32f3_disco.dts.pre.tmp:1515.2-1516.22: Warning (dmas_property): /soc/spi@40013000:dmas: cell 3 is not a phandle reference
stm32f3_disco.dts.pre.tmp:1515.2-1516.22: Warning (dmas_property): /soc/spi@40013000:dmas: Could not get phandle node for (cell 3)
devicetree error: dma-names property in /soc/spi@40013000 in stm32f3_disco.dts.pre.tmp has 2 strings, expected 4 strings
```

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/flash/flash_stm32_qspi.c [hunk 22]
```diff
@@ -17,7 +17,6 @@
 #include <drivers/clock_control/stm32_clock_control.h>
 #include <drivers/clock_control.h>
 #include <drivers/flash.h>
-#include <dt-bindings/dma/stm32_dma.h>
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/flash/flash_stm32_qspi.c:20]: now in the commit 611b8aa1f9e127ef6a2544555ce4fa2487a62211

File: drivers/i2s/i2s_ll_stm32.c [hunk 23]
```diff
@@ -9,7 +9,7 @@
 #include <string.h>
 #include <drivers/dma.h>
 #include <drivers/i2s.h>
-#include <dt-bindings/dma/stm32_dma.h>
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/i2s/i2s_ll_stm32.c:12]: now in the commit 696124e008b64766dc272cbb9faffc710296aa39

File: drivers/dma/Kconfig.stm32 (hunk 4 above)
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/dma/Kconfig.stm32:32]: do you mean commenting the commit message or the "help" of the drivers/dma/Kconfig.stm32 ?

[the remark this answers is not in the document]
Comment (erwango) [reply drivers/dma/Kconfig.stm32:32]: I mean adding comment in help section to help understanding the use of DMA_STM32_V2 that match both compatibles, and use of compatibles based macros for differences between V2 and V2BIS

**Comment by FRASTM** [comment]
one more commit for drivers/flash/flash_stm32_qspi.c 
one more commit for drivers/i2s/i2s_ll_stm32.c

File: drivers/flash/flash_stm32_qspi.c (hunk 22 above)
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/flash/flash_stm32_qspi.c:20]: now in the commit ce0731509db4f7aef958ea27e416ae822d5e0dda

File: drivers/dma/Kconfig.stm32 (hunk 4 above)
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/dma/Kconfig.stm32]: this is now in the commit 78bca5627ad0943969768648e1c01dbc1e745642

**Comment by FRASTM** [comment]
rebase (fix conflict with CODEOWNERS)

**Review by mbolivar-nordic — APPROVED** [review]
Nice work on the bindings documentation

**Comment by FRASTM** [comment]
rebased on cc0abee3db739413f2498d465386ab5a8bf7c1eb

**Review by erwango — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by erwango — CHANGES_REQUESTED** [review]
Nack'ed as we wait for the CI fix

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
> Nack'ed as we wait for the CI fix

EDIT: Set as DNM, waiting for the CI fix

**Comment by FRASTM** [comment]
rebase and fix CI for nucleo_l476rg ( dma is of type V2)
