### PR TITLE
logging: Use k_uptime_get_32 for high frequency system clock

### LINKED ISSUE #9043: New logging subsystem's timestamps wrap a little before the 3-minute mark
The log format implies that it can show up many hours, however it seems to be wrapping back to zero a little bit before the three minute mark.

### LINKED ISSUE #14010: logger: timestamp resets after 35.7 seconds on K64F
**Describe the bug**
Timestamps will wrap from 35.7 seconds to 0 on the FRDM K64F board.

I haven't bisected the issue yet, but it seems to have been around for more than a week.

**To Reproduce**
1. cd samples/subsys/shell/shell_module/
2. mkdir build && cd build
3. cmake -DBOARD=frdm_k64f ..
4. make
5. make flash
6. [connect to the console on K64F and enter] log_test start demo

**Expected behavior**
Expect the timestamps not to reset to 0 after 35.7 seconds.

**Impact**
Not sure what actual impact this has or where the bug lies.

**Screenshots or console output**
```
[00:00:35.616,064] <inf> app: Timer expired.
[00:00:35.616,067] <inf> app_test: info message
[00:00:35.616,069] <wrn> app_test: warning message
[00:00:35.616,072] <err> app_test: err message
[00:00:00.024,673] <inf> app: Timer expired.
[00:00:00.024,676] <inf> app_test: info message
[00:00:00.024,685] <wrn> app_test: warning message
[00:00:00.024,688] <err> app_test: err message
```

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: Current master as of 3/2/2019 (630af8a65f114b6b247dd26fbf47e9ebeb4672d1)

### PR DESCRIPTION
**Pull request by nordic-krch**
If system clock runs fast k_cycle_get_32(), which is the timestamp
source, wraps often (few minutes). This patch changes default
timestamp function to use k_uptime_get_32() if system clock
frequency is higher than 1 MHz and k_cycle_get_32() otherwise.

If system clock runs at 1 MHz, counter will wrap every 71.5 minutes.

Fixes #9043.
Fixes #14010.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by jhedberg** [comment]
Don't you also need to pass a different value to `log_output_timestamp_freq_set()` so the new value gets interpreted correctly?

**Comment by nordic-krch** [comment]
@jhedberg 
> Don't you also need to pass a different value to log_output_timestamp_freq_set() so the new value gets interpreted correctly?

Good point. Fixed.

**Review by jhedberg — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

File: subsys/logging/log_core.c [hunk 1]
```diff
@@ -298,7 +305,7 @@ void log_core_init(void)
 
 	/* Set default timestamp. */
 	timestamp_func = timestamp_get;
-	log_output_timestamp_freq_set(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC);
+	log_output_timestamp_freq_set(freq);
```
Comment (jhedberg) [inline subsys/logging/log_core.c]: Couldn't we actually make this a lot simpler by not requiring a separate static function at all:

```
if (CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC > 1000000)
        timestamp_func = k_uptime_get_32;
        log_output_timestamp_freq_set(MSEC_PER_SEC);
} else {
        timestamp_func = k_cycle_get_32;
        log_output_timestamp_freq_set(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC);
}
```

I'll leave it up to you to decide if it makes sense/is worth it.

**Review by carlescufi — APPROVED** [review]
