### PR TITLE
net: sockets: add support for SO_REUSEADDR and SO_REUSEPORT

### LINKED ISSUE #61884: net: upd sockets: incorrect behavior for multiple clients on a single server
**Describe the bug**

In an application, where we have a single UPD socket waiting for incoming data from multiple clients (e.g., a DTLS server with multiple DTLS clients), we ideally want a file descriptor for each “connected” client for easier handling of the connections. This is especially important for DTLS server implementations. For this to work, we create a new socket UDP socket, bind it to the same local IP:Port as the existing listening one, and finally call connect with the IP:Port of the new remote peer. This new additional socket is now more specific than the existing listening socket, resulting in incoming UDP messages from this remote peer forwarded to the new socket, not the general one. 
This is the desired behavior, correctly implemented within Linux and used by many DTLS server libraries. See, for example, here: [https://tlsalmin.github.io/2018/12/06/DTLS-server.html](https://tlsalmin.github.io/2018/12/06/DTLS-server.html)

In Zephyr, this behavior currently doesn't work correctly. On the one hand, support for SO_REUSEADDR is missing to be able to bind the new socket to the same IP:Port as the existing one. On the other hand, there is a bug in the connect() path for UDP connections, resulting in the remote peer IP address and port not correctly set to be parsed for incoming messages. 

**To Reproduce**

The following code works as intended on Linux, not on Zephyr:

```
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <errno.h>

#ifdef __ZEPHYR__

#include <zephyr/posix/fcntl.h>
#include <zephyr/net/net_ip.h>
#include <zephyr/net/socket.h>

#else

#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <poll.h>

#define net_addr_ntop inet_ntop
#define net_addr_pton inet_pton

#endif


#ifdef CONFIG_NET_CONFIG_MY_IPV4_ADDR
#define LOCAL_IP CONFIG_NET_CONFIG_MY_IPV4_ADDR
#else
#define LOCAL_IP "192.168.0.10"
#endif

#define LOCAL_PORT 4242


void setblocking(int fd, bool val)
{
	int fl;

	fl = fcntl(fd, F_GETFL, 0);

	if (val) {
		fl &= ~O_NONBLOCK;
	} else 	{
		fl |= O_NONBLOCK;
	}

	fcntl(fd, F_SETFL, fl);
}


int main(void)
{	
	/* Poll variables */
	struct pollfd pollfds[5];
	int num_fds = 0;
	for (int i = 0; i < sizeof(pollfds)/sizeof(pollfds[0]); i++) 
	{
		pollfds[i].fd = -1;
		pollfds[i].events = 0;
		pollfds[i].revents = 0;
	}

	/* UDP server */
	int server_fd = -1;

	/* Clients */
	int client_1_fd = -1;
	int client_2_fd = -1;


	struct sockaddr_in local_addr = {
			.sin_family = AF_INET,
			.sin_port = htons(LOCAL_PORT),
			.sin_addr.s_addr = 0
	};

	net_addr_pton(local_addr.sin_family, LOCAL_IP, &local_addr.sin_addr);
	
	/* Create the UDP server socket */
	server_fd = socket(local_addr.sin_family, SOCK_DGRAM, IPPROTO_UDP);

	/* Make sure we can bind to the address:port */
	int yes = 1;
	setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, (void*)&yes, sizeof(yes));

	/* Bind server socket to its destined IPv4 address */
	bind(server_fd, (struct sockaddr*) &local_addr, sizeof(local_addr)); 

	/* We want non-blocking sockets */
	setblocking(server_fd, false);

	/* Prepare server_fd for poll() */
	pollfds[num_fds].fd = server_fd;
	pollfds[num_fds].events = POLLIN;
	num_fds++;


	while (1) 
	{
		char buf[1500];
		
		struct sockaddr client_addr;
		socklen_t client_addr_len = sizeof(client_addr);

		/* Block and wait for incoming events */
		int ret = poll(pollfds, num_fds, -1);

		if (ret == -1) {
			continue;
		}

		/* Check which fds created an event */
		for (int i = 0; i < num_fds; i++) 
		{
			int fd = pollfds[i].fd;
			short revents = pollfds[i].revents;


			if ((fd == server_fd) && (revents & POLLIN))
			{
				int received = recvfrom(fd, buf, sizeof(buf), 0, &client_addr, &client_addr_len);

				if (received < 0) 
				{
					printf("recvfrom: error %d on fd %d", errno, server_fd);
				} 
				else 
				{
					char client_ip_string[20];
					net_addr_ntop(AF_INET, 
						      &((struct sockaddr_in*) &client_addr)->sin_addr, 
						      client_ip_string, 
						      sizeof(client_ip_string));
					uint16_t client_port = htons(((struct sockaddr_in*) &client_addr)->sin_port);
					buf[received] = '\0';

					if (client_1_fd == -1)
					{
						/* Create a more specific socket to have a direct connection to the new client */
						client_1_fd = socket(client_addr.sa_family, SOCK_DGRAM, IPPROTO_UDP);
						setsockopt(client_1_fd, SOL_SOCKET, SO_REUSEADDR, (void*)&yes, sizeof(yes)); 
						bind(client_1_fd, (struct sockaddr*) &local_addr, sizeof(local_addr));
						setblocking(client_1_fd, false);
						connect(client_1_fd, &client_addr, sizeof(client_addr));

						pollfds[num_fds].fd = client_1_fd;
						pollfds[num_fds].events = POLLIN;
						num_fds++;

						printf("New Connection (fd %d) from %s:%d: %s", 
						       client_1_fd, 
						       client_ip_string, 
						       client_port, 
						       buf);
					}
					else if (client_2_fd == -1) 
					{
						/* Create a more specific socket to have a direct connection to the new client */
						client_2_fd = socket(client_addr.sa_family, SOCK_DGRAM, IPPROTO_UDP);
						setsockopt(client_2_fd, SOL_SOCKET, SO_REUSEADDR, (void*)&yes, sizeof(yes)); 
						bind(client_2_fd, (struct sockaddr*) &local_addr, sizeof(local_addr));
						setblocking(client_2_fd, false);
						connect(client_2_fd, &client_addr, sizeof(client_addr));

						pollfds[num_fds].fd = client_2_fd;
						pollfds[num_fds].events = POLLIN;
						num_fds++;

						printf("New Connection (fd %d) from %s:%d: %s", 
						       client_2_fd, 
						       client_ip_string, 
						       client_port, 
						       buf);
					}
					else
					{
						printf("Data from %s:%d on fd %d: %s", 
						       client_ip_string, 
						       client_port, 
						       fd, 
						       buf);
					}
				}
			}
			else if ((fd == client_1_fd) && (revents & POLLIN))
			{
				int received = recv(fd, buf, sizeof(buf), 0);

				if (received < 0) 
				{
					printf("recv client_1: error %d", errno);
				} 
				else 
				{						
					buf[received] = '\0';
					printf("Data from client_1 (fd %d): %s", client_1_fd, buf);
				}
			}
			else if ((fd == client_2_fd) && (revents & POLLIN))
			{
				int received = recv(fd, buf, sizeof(buf), 0);

				if (received < 0) 
				{
					printf("recv client_2: error %d", errno);
				} 
				else 
				{						
					buf[received] = '\0';
					printf("Data from client_2 (fd %d): %s", client_2_fd, buf);
				}
			}
		}
	}

	return 0;
}
```

Used with this proj.conf for the Zephyr build:
```
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=y
CONFIG_NET_LOG=y
CONFIG_NET_IPV6=n
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=n
CONFIG_NET_SOCKETS=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_SOCKETS_POLL_MAX=5

CONFIG_NET_BUF_DATA_SIZE=1500

CONFIG_INIT_STACKS=y
CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_MAX_CONN=5
CONFIG_NET_MAX_CONTEXTS=8
CONFIG_POSIX_MAX_FDS=5

CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.0.10" 
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255" 
CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.0.1" 

CONFIG_NET_SHELL=y

CONFIG_MAIN_STACK_SIZE=4096

CONFIG_DEBUG_OPTIMIZATIONS=y
```

**Expected behavior**

The first two UDP clients sending data to the server receive their own socket. When messages are then received from one of these two peers, the specific socket for this peer receives the data and triggers the poll() event. All other peers still trigger the first general socket of the UDP server.

### PR DESCRIPTION
**Pull request by Frauschi**
The first commit adds support for the SO_REUSEADDR option in order to allow multiple sockets to be bound to the same local IP:Port combination.
The second commit then fixes a bug in the connect() calls for UDP sockets. With that, remote peer IP address and port are correctly set and can be properly parsed for incoming messages to find the correct socket for the incoming message.

I'm pretty sure that the proposed fixes are not perfectly fitting and are rather intended for a discussion on how to implement the fix in the correct way. The implementation of the SO_REUSEADDR option certainly misses some places where the option needs to be taken care off. I'm also pretty sure, that there is a better fix for the UDP connect() issue of the second commit, but I'm not familiar enough with the code base to come up with a better solution at the moment.

However, I'm looking forward to your feedback on the proposed changes and fixes. I'm of course willing to update the PR based on your feedback. 

Fixes #61884

### CODE REVIEW

**Comment by rlubos** [comment]
@Frauschi The `connect()` for UDP sockets was just fixed in a slightly different way in https://github.com/zephyrproject-rtos/zephyr/pull/61843 (with tests added to cover this case).

**Comment by jukkar** [comment]
I think we need to add some changes to the `net_context_bind()` too so that we check the address/ports before allowing bind to succeed.

There is actually quite nice summary how `SO_REUSEADDR` should work in StackOverflow so adding a link here just in case
https://stackoverflow.com/questions/14388706/how-do-so-reuseaddr-and-so-reuseport-differ

**Comment by Frauschi** [comment]
> @Frauschi The `connect()` for UDP sockets was just fixed in a slightly different way in #61843 (with tests added to cover this case).

This indeed fixes the bug, thank you. I reverted the commit with my proposed (less elegant) fix and rebased to the current main branch. Therefore, we are only talking about the SO_REUSEADDR topic going further.

File: subsys/net/ip/connection.c [hunk 1]
```diff
@@ -211,6 +211,12 @@ static struct net_conn *conn_find_handler(uint16_t proto, uint8_t family,
 				continue;
 			}
 
+#if defined(CONFIG_NET_CONTEXT_REUSEADDR)
+			if (conn->context->options.reuseaddr != 0) {
+				continue;
+			}
+#endif
```
Comment (jukkar) [inline subsys/net/ip/connection.c:218]: To me this looks like we are doing this too early. We are now ignoring all the checks done below. Better would be to check the reuseaddr if we have found a duplicate entry.

Comment (Frauschi) [reply subsys/net/ip/connection.c]: You are definitely right. I moved to the end after all other checks in my last commit

**Comment by Frauschi** [comment]
> I think we need to add some changes to the `net_context_bind()` too so that we check the address/ports before allowing bind to succeed.

Integrated in the last commit. While checking net_context_bind(), I also found another minor bug: the wrong protocol (AF_INET) is passed to check_used_port() instead of the actual protocol from the context. I fixed this right away, as this bug caused all checks of check_used_port anyway.

**Comment by Frauschi** [comment]
> There is actually quite nice summary how `SO_REUSEADDR` should work in StackOverflow so adding a link here just in case
> https://stackoverflow.com/questions/14388706/how-do-so-reuseaddr-and-so-reuseport-differ

If I understand the article correctly, we have now (if I haven't missed another place to check the option) implemented the desired SO_REUSEADDR behavior. For SO_REUSEPORT, we would have to add further checks, that all other contexts also have the option set in order to have a successful bind() call. Should we implement that, too, or is SO_REUSEADDR enough atm? (for my use case it is actually).

File: subsys/net/ip/connection.c [hunk 2]
```diff
@@ -248,6 +248,12 @@ static struct net_conn *conn_find_handler(uint16_t proto, uint8_t family,
 			continue;
 		}
 
+#if defined(CONFIG_NET_CONTEXT_REUSEADDR)
+		if (conn->context->options.reuseaddr != 0) {
```
Comment (rlubos) [inline subsys/net/ip/connection.c:252]: Is this actually correct? We're checking the option on a socket (net_context) that has already registered a connection, and not the one that that tries to register a new connection (and should have SO_REUSEADDR set)?

And to me, it'd make a bit more sense to let the `conn_find_handler()` function work as it is, and leave the decistion on what to do with an already existing connection to `net_conn_register()` (i. e. check whether the flag is set).

File: subsys/net/ip/net_context.c [hunk 3]
```diff
@@ -591,15 +591,20 @@ int net_context_bind(struct net_context *context, const struct sockaddr *addr,
...
 					      addr);
-			if (!ret) {
-				net_sin6_ptr(&context->local)->sin6_port =
-					addr6->sin6_port;
-			} else {
+			if (ret != 0
+#if defined(CONFIG_NET_CONTEXT_REUSEADDR)
+			    && context->options.reuseaddr == 0
+#endif
+			    ) {
```
Comment (rlubos) [inline subsys/net/ip/net_context.c:600]: This is quite hard to read with the ifdef inside if condition - IMO it'd make sense to introduce a helper function which provides the option value (`bool is_reuseaddr_set(struct net_context *context)` or so), that would simply return false if the option was disabled in KConfig.

**Comment by jukkar** [comment]
> For SO_REUSEPORT, we would have to add further checks, that all other contexts also have the option set in order to have a successful bind() call. Should we implement that, too, or is SO_REUSEADDR enough atm? (for my use case it is actually).

It makes actually sense to implement SO_REUSEPORT too, this could be a separate PR or this one. It would be great if you could add support for it.

BTW, please implement also unit tests that will make sure the option works as expected. You could place the tests to `tests/net/socket/misc` for example.

**Comment by Frauschi** [comment]
The new commit now also adds support for SO_REUSEPORT and improves the SO_REUSEADDR implementation. A lot more changes were necessary to properly implement both options and all possibilities. I followed the explanation from the StackOverflow article and added unit tests for all identified situations. 
The implementation now completely (hopefully) follows the BSD implementation and tries to follow the additional Linux options as much as possible. However, there are currently three limitions and therefore differences to the way Linux handles these options:
-  SO_REUSEADDR and SO_REUSEPORT are not "the same" for client sockets, as we do not have a trivial way so identify a socket as "client" during binding.
- No prevention of "port hijacking"
- No support for the load balancing stuff for incoming packets/connections

I think these limitations are ok, as an implementation would drastically increase the complexity for these two options and would change many more places in the code. The first one also can easily be worked around (just properly use SO_REUSEPORT instead of SO_REUSEADDR). For the other two, I am not sure if Zephyr even needs these features anyway.

On my way through the code I also fixed some bugs I found. Feel free to ask questions if some of the changes are unclear or seem useless / unrelated at first.

File: include/zephyr/net/net_context.h [hunk 4]
```diff
@@ -322,6 +322,9 @@ __net_socket struct net_context {
 #endif
 #if defined(CONFIG_NET_CONTEXT_DSCP_ECN)
 		uint8_t dscp_ecn;
+#endif
+#if defined(CONFIG_NET_CONTEXT_REUSEADDR)
+		uint8_t reuseaddr;
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply include/zephyr/net/net_context.h]: Done in the new commit

File: subsys/net/ip/connection.c (hunk 2 above)
Comment (Frauschi) [reply subsys/net/ip/connection.c]: You are right. This is fixed (and further improved) in the new commit

File: subsys/net/ip/net_context.c (hunk 3 above)
Comment (Frauschi) [reply subsys/net/ip/net_context.c]: Done in the new commit

**Comment by jukkar** [comment]
Please check the compliance issue(s).

Also the commits look weird, there are multiple commits with same text. I suggest you create four commits in this PR,
1. one that introduce SO_REUSEADDR
2. tests for SO_REUSEADDR
3. then one that introduces SO_REUSEPORT
4. and tests for SO_REUSEPORT

**Comment by Frauschi** [comment]
> Please check the compliance issue(s).
> 
> Also the commits look weird, there are multiple commits with same text. I suggest you create four commits in this PR,
> 
> 1. one that introduce SO_REUSEADDR
> 2. tests for SO_REUSEADDR
> 3. then one that introduces SO_REUSEPORT
> 4. and tests for SO_REUSEPORT

I changed the commits and hopefully fixed the missing compliance issues. I'm looking forward to your feedback of the changes.

**Comment by Frauschi** [comment]
I think the failing tests are not related to this PR

**Comment by rlubos** [comment]
It seems that all failures are related to Thrift - @cfriedt any ideas?

**Comment by cfriedt** [comment]
> It seems that all failures are related to Thrift - @cfriedt any ideas?

I believe these are TLS issues. I think there is a bit of an ongoing effort here, but I've been out of the loop for a couple of weeks. Cc @d3zd3z

**Comment by cfriedt** [comment]
> > It seems that all failures are related to Thrift - @cfriedt any ideas?
> 
> I believe these are TLS issues. I think there is a bit of an ongoing effort here, but I've been out of the loop for a couple of weeks. Cc @d3zd3z 

I can make a PR this morning to disable TLS Transport tests until the issue is resolved. @d3zd3z - do you have an issue open already?

**Comment by rlubos** [comment]
Actually, in case of this PR, it seems that the root cause may be different. Thrift seems to be `SO_REUSEADDR`  user, so it now needs to enable `NET_CONTEXT_REUSEADDR`, the following made the test pass for me locally:
```patch
diff --git a/tests/lib/thrift/ThriftTest/prj.conf b/tests/lib/thrift/ThriftTest/prj.conf
index 4d2b145b13..7625b849d0 100755
--- a/tests/lib/thrift/ThriftTest/prj.conf
+++ b/tests/lib/thrift/ThriftTest/prj.conf
@@ -13,6 +13,7 @@ CONFIG_NET_SOCKETS=y
 CONFIG_NET_SOCKETPAIR=y
 CONFIG_HEAP_MEM_POOL_SIZE=16384
 CONFIG_EVENTFD=y
+CONFIG_NET_CONTEXT_REUSEADDR=y
 
 CONFIG_THRIFT=y
```

File: subsys/net/ip/Kconfig [hunk 5]
```diff
@@ -683,6 +683,18 @@ config NET_CONTEXT_DSCP_ECN
 	  Notification values on net_context. Those values are then used in
 	  IPv4/IPv6 header when sending packets over net_context.
 
+config NET_CONTEXT_REUSEADDR
```
Comment (cfriedt) [inline subsys/net/ip/Kconfig:686]: Why are these even optional? Shouldn't it just always be supported in order to support this aspect of the BSD Socket API?

No Kconfig required, IMHO.

**Comment by jukkar** [comment]
> Seems unnecessary. I think we should just always support it reuseaddr / reuseport.

Atm we have almost all socket options behind a Kconfig option, so we could do the same here. We could mark reuseadd/reuseport as y by default. Anyone wanting to squeeze extra bytes out from memory could turn the options off if the options are not needed.

**Comment by Frauschi** [comment]
> > Seems unnecessary. I think we should just always support it reuseaddr / reuseport.
> 
> Atm we have almost all socket options behind a Kconfig option, so we could do the same here. We could mark reuseadd/reuseport as y by default. Anyone wanting to squeeze extra bytes out from memory could turn the options off if the options are not needed.

I did exactly that in my last commit. Enabling both by default if TCP or UDP are enabled. But the user can still disable them explicitly. I think this is a reasonable way to go.

File: subsys/net/ip/net_context.c [hunk 6]
```diff
@@ -2363,6 +2492,28 @@ static int set_context_dscp_ecn(struct net_context *context,
...
+				 const void *value, size_t len)
+{
+#if defined(CONFIG_NET_CONTEXT_REUSEADDR)
+	bool reuseaddr = false;
+
+	if (*((int *) value) != 0) {
+		reuseaddr = true;
+	}
+
+	if (len > sizeof(int)) {
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply subsys/net/ip/net_context.c]: Done in the last commit

File: subsys/net/ip/net_context.c [hunk 7]
```diff
@@ -1309,6 +1418,26 @@ static int get_context_dscp_ecn(struct net_context *context,
 #endif
 }
 
+static int get_context_reuseaddr(struct net_context *context,
+				 void *value, size_t *len)
+{
+#if defined(CONFIG_NET_CONTEXT_REUSEADDR)
+	if (context->options.reuseaddr == true) {
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply subsys/net/ip/net_context.c:1467]: Done

File: subsys/net/ip/net_context.c [hunk 8]
```diff
@@ -119,20 +218,24 @@ static uint16_t find_available_port(struct net_context *context,
...
 	} while (check_used_port(net_context_get_proto(context),
-				 htons(local_port), addr) == -EEXIST);
+				 htons(local_port), addr, false) == -EEXIST);
 
 	return htons(local_port);
 }
 #else
 #define check_used_port(...) 0
 #define find_available_port(...) 0
+bool net_context_is_reuseaddr_set(struct net_context *context)
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply subsys/net/ip/net_context.c]: I removed the dummy implementation from `net_context.c` and moved the actual implementation outside of the `defined(CONFIG_NET_UDP) || defined(CONFIG_NET_TCP)` block to catch all compile options.

File: subsys/net/ip/net_context.c [hunk 9]
```diff
@@ -2514,6 +2576,28 @@ static int set_context_reuseaddr(struct net_context *context,
...
+				 const void *value, size_t len)
+{
+#if defined(CONFIG_NET_CONTEXT_REUSEPORT)
+	bool reuseport = false;
+
+	if (*((int *) value) != 0) {
+		reuseport = true;
+	}
+
+	if (len > sizeof(int)) {
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply subsys/net/ip/net_context.c]: done

File: subsys/net/ip/net_context.c [hunk 10]
```diff
@@ -1438,6 +1480,26 @@ static int get_context_reuseaddr(struct net_context *context,
 #endif
 }
 
+static int get_context_reuseport(struct net_context *context,
+				void *value, size_t *len)
+{
+#if defined(CONFIG_NET_CONTEXT_REUSEPORT)
+	if (context->options.reuseport == true) {
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply subsys/net/ip/net_context.c:1495]: done

File: subsys/net/ip/net_context.c [hunk 11]
```diff
@@ -229,13 +265,17 @@ bool net_context_is_reuseaddr_set(struct net_context *context)
 {
 	return false;
 }
+bool net_context_is_reuseport_set(struct net_context *context)
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply subsys/net/ip/net_context.c]: done

File: tests/net/socket/misc/src/main.c [hunk 12]
```diff
@@ -286,6 +286,8 @@ void test_so_bindtodevice(int sock_c, int sock_s, struct sockaddr *peer_addr,
 	zassert_equal(ret, 0, "close failed, %d", errno);
 	ret = close(sock_s);
 	zassert_equal(ret, 0, "close failed, %d", errno);
+
+	k_sleep(K_MSEC(CONFIG_NET_TCP_TIME_WAIT_DELAY));
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply tests/net/socket/misc/src/main.c:290]: The changes in the unrelated tests are necessary, as otherwise these tests now fail without the REUSEADDR/REUSEPORT option. Most of the tests create sockets in the `TIME_WAIT` state, resulting in the next test failing on a call to `bind()` to the same IP address / port combination.

File: subsys/net/ip/tcp.c [hunk 13]
```diff
@@ -1923,6 +1923,19 @@ static struct tcp *tcp_conn_new(struct net_pkt *pkt)
 		goto err;
 	}
 
+	/* Set the local port in the context object after the net_context_bind()
+	 * call in order to avoid port reuse problems (as REUSEADDR / REUSEPORT
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply subsys/net/ip/tcp.c:1927]: `tcp_conn_new()` is used to create a new TCP client connection during `accept()`. During debugging the `TIME_WAIT` stuff, I encountered that the remote address and port, as well as the local address, are properly written to the related `net_context` object (remote address and port in line 1901, local address within the call to`net_context_bind`). However, the local port is missing. 

In case this connection is closed and entered the `TIME_WAIT` state, the missing local port in the net_context object resulted in this object not properly being found during a `bind()` call to the same local address / port combination.

However, we cannot add the local port to the `local_addr' variable prior to the call to `net_context_bind`, as this call will then fail because the SO_REUSEPORT option is not enabled on both net_context options. Therefore, we just add the port afterward to make sure the net_context objects holds the information.

[the remark this answers is not in the document]
Comment (jukkar) [reply subsys/net/ip/tcp.c:1927]: You explanation is good, could you add most of it to the comment in the code. The existing comment is a bit too vague.

File: tests/net/socket/tcp/src/main.c [hunk 14]
```diff
@@ -31,21 +31,21 @@ static void test_bind(int sock, struct sockaddr *addr, socklen_t addrlen)
 {
```
Comment (jukkar) [inline tests/net/socket/tcp/src/main.c:31]: Please place all the test related code to commit that creates the tests, now there is test changes in the 1st commit for example.

File: tests/net/socket/reuseaddr/CMakeLists.txt [hunk 15]
```diff
@@ -0,0 +1,8 @@
+# SPDX-License-Identifier: Apache-2.0
```
Comment (jukkar) [inline tests/net/socket/reuseaddr/CMakeLists.txt]: Please change the commit subject of "net: tests: add tests for SO_REUSEADDR" to
`tests: net: sockets: add tests for SO_REUSEADDR`

File: tests/net/socket/reuseaddr_reuseport/src/main.c [hunk 16]
```diff
@@ -0,0 +1,2468 @@
+/*
+ * Copyright (c) 2019 Linaro Limited
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <zephyr/logging/log.h>
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply tests/net/socket/reuseaddr_reuseport/src/main.c:7]: Unfortunately, I can't find the testsuite app `net/socket/ip`. Can you please specifiy where to put the tests?

File: subsys/net/ip/connection.c [hunk 17]
```diff
@@ -174,67 +175,75 @@ static struct net_conn *conn_find_handler(uint16_t proto, uint8_t family,
 			continue;
 		}
 
-		if (remote_addr) {
```
Comment (jukkar) [inline subsys/net/ip/connection.c:177]: The changes here were a bit difficult to read. Are we just swapping the remote/local address check branches here, if true, why do we need to do it.

File: tests/net/socket/misc/src/main.c [hunk 18]
```diff
@@ -286,6 +286,8 @@ void test_so_bindtodevice(int sock_c, int sock_s, struct sockaddr *peer_addr,
 	zassert_equal(ret, 0, "close failed, %d", errno);
```
Comment (jukkar) [inline tests/net/socket/misc/src/main.c:286]: Please change the commit subject of "net: sockets: add tests for SO_REUSEPORT" to
`tests: net: sockets: add tests for SO_REUSEPORT`

File: subsys/net/ip/Kconfig [hunk 19]
```diff
@@ -685,12 +685,14 @@ config NET_CONTEXT_DSCP_ECN
```
Comment (jukkar) [inline subsys/net/ip/Kconfig:685]: Please do not add commit that "fixes" the earlier commits in this PR. So place the review changes to corresponding earlier commits. Having a separate commit for fixes/changes is nice for the reviewer but it hurts bisectability so we avoid doing it.

**Comment by Frauschi** [comment]
As both Kconfig options are now enabled by default, I think the failing tests are not related. I also cannot reproduce the failing tests on my side.

File: tests/net/socket/reuseaddr_reuseport/src/main.c [hunk 20]
```diff
@@ -0,0 +1,1011 @@
...
+	accept_sock = test_accept(server_sock, &accept_addr, &accept_addrlen);
+
+	/* Close the server socket */
+	close(server_sock);
+
+	/* Close the accepted socket */
+	close(accept_sock);
+
+	/* Wait a short time for the accept socket to enter TIME_WAIT state*/
+	k_msleep(50);
```
Comment (jukkar) [inline tests/net/socket/reuseaddr_reuseport/src/main.c:512]: This might cause some issues in the future if some timing changes etc. Anyway, we can cross that bridge when we get there.

**Review by jukkar — APPROVED** [review]
LGTM. Thanks for putting effort to the tests, they are very easy to read and understand.

**Comment by jukkar** [comment]
The twister error is this one
```
INFO    - --/__w/zephyr/zephyr/twister-out/qemu_x86/tests/net/conn_mgr_monitor/net.conn_mgr_dad/handler.log---
ERROR   - SeaBIOS (version zephyr-v1.0.0-0-g31d4e0e-dirty-20200714_234759-fv-az50-zephyr)
Booting from ROM..
*** Booting Zephyr OS build zephyr-v3.4.0-3292-g6304095e9c0d ***
Running TESTSUITE conn_mgr_monitor
===================================================================
START - test_DAD
 PASS - test_DAD in 0.154 seconds
===================================================================
START - test_cycle_ready_CC
E: Double Fault
E: EAX: 0x00010af5, EBX: 0x00000000, ECX: 0x000f4240, EDX: 0x00000000
E: ESI: 0x00000046, EDI: 0x00000000, EBP: 0x0013e014, ESP: 0x0013dfec
E: EFLAGS: 0x00000012 CS: 0x0008 CR3: 0x0015b000
E: call trace:
E: EIP: 0x001001b7
E:      0x001124e8 (0x10af5)
E:      0x00118ec4 (0xa)
E:      0x00118ff9 (0x0)
E:      0x0010659e (0x13e088)
E:      0x00106830 (0x106830)
E:      0x0010c51d (0x1551f8)
E:      0x0010c630 (0x10c630)
E:      0x0010f5cb (0x0)
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x12b120 (net_mgmt)
E: Halting system
```
which indicates stack overflow in net_mgmt thread and which indeed does not look related to these changes. But we have modified common code paths in this PR so that unrelated functionality might be affected. I try to replicate the issue.

**Comment by jukkar** [comment]
I could replicate this by `west build -b qemu_x86 -d build/conn_mgr_monitor -t run zephyr/tests/net/conn_mgr_monitor`

This fixed the conn_mgr_monitor stack overflow issue
```
diff --git a/tests/net/conn_mgr_monitor/prj.conf b/tests/net/conn_mgr_monitor/prj.conf
index 1e60d8327e..f68f3f09fd 100644
--- a/tests/net/conn_mgr_monitor/prj.conf
+++ b/tests/net/conn_mgr_monitor/prj.conf
@@ -23,6 +23,7 @@ CONFIG_ZTEST_NEW_API=y
 CONFIG_NET_IF_MAX_IPV4_COUNT=6
 CONFIG_NET_IF_MAX_IPV6_COUNT=6
 CONFIG_TEST_USERSPACE=y
+CONFIG_NET_MGMT_EVENT_STACK_SIZE=1024
 
 # Enable for help debugging this test suite:
 # CONFIG_NET_LOG=y
```
Could you add a commit to this PR that increases the net_mgmt stack size?

**Comment by jukkar** [comment]
There is actually already a PR that fixes the conn_mgr_monitor at #62317 so never mind fixing it here. Lets merge that one first and this PR should work too.

**Comment by jukkar** [comment]
@Frauschi the stack size is now fixed in mainline, could you rebase against latest main and re-submit

File: tests/net/socket/reuseaddr_reuseport/src/main.c (hunk 16 above)
[the remark this answers is not in the document]
Comment (cfriedt) [reply tests/net/socket/reuseaddr_reuseport/src/main.c:7]: Sorry - on mobile - `tests/net/tcp` / `tests/net/udp/`

**Comment by jukkar** [comment]
@cfriedt @ssharks if you have time, please take a look.

**Review by cfriedt — APPROVED** [review]
LGTM for now - It might be better to eventually use these for NET_TCP and NET_UDP as an alternative to he `default y if ...`

```
select NET_CONTECT_REUSEADDR
select NET_CONTECT_REUSEPORT
```

**Review by rlubos — APPROVED** [review]
Looks good, thanks for the nice test rework.
