### PR TITLE
LPSPI optimizations 5/19/25

### LINKED ISSUE #89583: tests: spi: mimxrt1180_evk_cm33: test fail with spi_async case
**Describe the bug**

spi async test fails when enabled on rt1180 platform

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - mimxrt1180_evk_cm33
 - What have you tried to diagnose or workaround this issue?
 - git bisect
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 
```
08351250db03b0e7ca4d745ef66598c10f054ff4 is the first bad commit
commit 08351250db03b0e7ca4d745ef66598c10f054ff4
Author: Declan Snyder <declan.snyder@nxp.com>
Date:   Thu Mar 13 14:25:58 2025 -0500

    tests: spi_loopback: nxp: remove lpspi async=n cfg

    Remove the overlay files for many of the NXP platforms, because they
    were doing two things that are no longer relevant:

    1) CONFIG_SPI_ASYNC=n -> LPSPI driver used to not work with
       CONFIG_SPI_ASYNC, now it does, so we should test it.
    2) CONFIG_SPI_MCUX_LPSPI_DMA=y -> This is redundant with the
       testcase.yaml

    Signed-off-by: Declan Snyder <declan.snyder@nxp.com>

```

**To Reproduce**

```
west update
scripts/twister --device-testing --hardware-map ${HOME}/nxp/mimxrt1180_evk_cm33/map.yaml -T tests/drivers/spi/spi_loopback --west-flash
```

**Expected behavior**

Test pass

**Impact**

spi async functions

**Logs and console output**

```
2025-05-07 10:41:01,249 - twister - DEBUG - DEVICE: �*** Booting Zephyr OS build v4.1.0-3452-g021d90b641bb ***
2025-05-07 10:41:01,252 - twister - DEBUG - DEVICE: Running TESTSUITE log_link_order
2025-05-07 10:41:02,939 - twister - DEBUG - DEVICE: =============================================�*** Booting Zephyr OS build v4.1.0-3509-g91fe6c13e52f ***
2025-05-07 10:41:02,948 - twister - DEBUG - DEVICE: SPI test on buffers TX/RX 0x30004320/0x30004300, frame size = 8, DMA enabled (without CONFIG_NOCACHE_MEMORY)
2025-05-07 10:41:02,953 - twister - DEBUG - DEVICE: Polling...Running TESTSUITE spi_extra_api_features
2025-05-07 10:41:02,959 - twister - DEBUG - DEVICE: ===================================================================
2025-05-07 10:41:02,961 - twister - DEBUG - DEVICE: START - test_spi_lock_release
2025-05-07 10:41:03,167 - twister - DEBUG - DEVICE: E: Timeout waiting for transfer complete
2025-05-07 10:41:03,179 - twister - DEBUG - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:109: spi_loopback_transceive: (ret is true)
2025-05-07 10:41:03,182 - twister - DEBUG - DEVICE: SPI transceive failed, code -116
2025-05-07 10:41:03,186 - twister - DEBUG - DEVICE: FAIL - test_spi_lock_release in 0.221 seconds
2025-05-07 10:41:03,192 - twister - DEBUG - DEVICE: ===================================================================
2025-05-07 10:41:03,195 - twister - DEBUG - DEVICE: TESTSUITE spi_extra_api_features failed.
2025-05-07 10:41:03,199 - twister - DEBUG - DEVICE: Running TESTSUITE spi_extra_api_features
2025-05-07 10:41:03,205 - twister - DEBUG - DEVICE: ===================================================================
2025-05-07 10:41:03,208 - twister - DEBUG - DEVICE: START - test_spi_lock_release
2025-05-07 10:41:03,413 - twister - DEBUG - DEVICE: E: Timeout waiting for transfer complete
2025-05-07 10:41:03,424 - twister - DEBUG - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:109: spi_loopback_transceive: (ret is true)
2025-05-07 10:41:03,427 - twister - DEBUG - DEVICE: SPI transceive failed, code -116
2025-05-07 10:41:03,431 - twister - DEBUG - DEVICE: FAIL - test_spi_lock_release in 0.220 seconds
2025-05-07 10:41:03,437 - twister - DEBUG - DEVICE: ===================================================================
2025-05-07 10:41:03,441 - twister - DEBUG - DEVICE: TESTSUITE spi_extra_api_features failed.
2025-05-07 10:41:03,443 - twister - DEBUG - DEVICE: Running TESTSUITE spi_loopback
2025-05-07 10:41:03,449 - twister - DEBUG - DEVICE: ===================================================================
2025-05-07 10:41:03,452 - twister - DEBUG - DEVICE: Testing loopback spec: SLOW
2025-05-07 10:41:03,454 - twister - DEBUG - DEVICE: START - test_nop_nil_bufs
2025-05-07 10:41:03,458 - twister - DEBUG - DEVICE: PASS - test_nop_nil_bufs in 0.001 seconds
2025-05-07 10:41:03,464 - twister - DEBUG - DEVICE: ===================================================================
2025-05-07 10:41:03,467 - twister - DEBUG - DEVICE: START - test_spi_async_call
```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v4.1.0-3452-g021d90b641bb

### PR DESCRIPTION
**Pull request by decsny**
Update to optimize the LPSPI configuration latency and code size, as well as fix a few bugs. This is the revival of #85010 plus a few other things.

Changelist:
* Removes call to SDK functions. More info on that below
* Add a wait time limit for the wait_tx_fifo_empty to avoid infinite loop in ISR
* Add major version ID to driver data
* Remove the check for already configured that was preventing register write due to clocking being done in SDK call, now we clocked the LPSPI in the zephyr driver init already, so this was no longer necessary. Also remove a redundant CR write.
* Add clarifying comments to common file for future developers.
* Removes a useless pointer from the driver data to save 4 bytes of RAM per instance.

Removing SDK calls in common file results:
The measurement of 3.7 in #85010 is obviously still valid, but most of the other stuff from that PR already merged, and the comparison from the theoretical 4.1 to this PR is very close, maybe only 1 or 2 hundred bytes more now due to many of the other PRs that have merged over the last few months. The only thing left was removing this LPSPI_MasterInit call in the configure function, so I will hone in on that, which is also very important to the latency of transfers as well. 

All measurements taken on same platform (MCXN947) with same configuration (the one in the spi loopback test). The exact numbers will vary slightly based on platform and configuration (just as before, but should be better in all cases now)
```
Before this PR:
spi_mcux_configure: 900 bytes
fsl_lpspi.c: 1020 bytes
Total: **1920 bytes**
Configuration took 4942 clock cycles

After this PR:
lpspi_configure: 604 bytes
fsl_lpspi: 0 bytes (removed from build)
Total: **604 bytes**
Configuration took 2070 clock cycles
```

Code size improved overall by almost 2x for configure code from around 2000 to 1300 bytes. Or you could consider it to be almost 3x since the new code added is about 400 bytes in the zephyr driver while we remove the 1KB of the SDK doing the same. This is mostly due to SDK having generic code for taking parameters to configure LPSPI in many ways, and having shim code needed to call on this API. With native zephyr driver, we know already for the most part which configuration we need, so we can hardcode it. And the parts we don't know either come from DT (close to hardcoded, just need to read a struct member), or from the spi_config in the API (just needing to decode a bitmask from a struct member). So there removes a lot of the overhead to use a two layer driver. 

Latency improved for configure (and the configure step is the biggest part of software to hardware transfer start latency in the driver) by also about 2x, from almost 5000 to close to 2500 clock cycles. This is mostly due to switching to use a binary search algorithm for the clock divs instead of a linear search. So this improvement is actually algorithmic going from (O(n)) to O(log(n)) depending on which div is optimal. I have suggested to the MCUX SDK team to also make a similar change on that codebase. But I will admit that this is the type of function which would benefit from a direct unit test, which I do not know if that is possible with zephyr. The algorithm is more complex.

Fixes #91015

### CODE REVIEW

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 1]
```diff
@@ -116,6 +118,156 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+	uint8_t best_prescaler = 0, best_div = 0;
+	uint32_t best_freq = 0;
+
+	for (uint8_t prescaler = 0U; prescaler < 8U; prescaler++) {
+		uint8_t high = 255, low = 0, test_div = 255;
+		uint32_t real_freq = 0;
+
+		/* maximum freq won't get better than what we got with previous prescaler */
+		if (clock_freq / (TWO_EXP(prescaler) * 2) < best_freq) {
+			goto done;
```
Comment (tbursztyka) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:195]: break?

**Review by tbursztyka — DISMISSED** [review]
lgtm

**Comment by decsny** [comment]
@hakehuang can you help test this one

**Comment by hakehuang** [comment]
> @hakehuang can you help test this one

sure, let me kick a test and feedback

File: doc/releases/migration-guide-4.2.rst [hunk 2]
```diff
@@ -500,6 +500,9 @@ OpenThread
 SPI
 ===
 
+* Renamed Renamed :kconfig:option:`CONFIG_SPI_MCUX_LPSPI` to :kconfig:option:`CONFIG_SPI_NXP_LPSPI`,
+  and similar for any child configs for that driver, including
+  :kconfig:option:`CONFIG_SPI_NXP_LPSPI_DMA` and :kconfig:option:`CONFIG_SPI_NXP_LPSPI_CPU`.
```
Comment (pdgendt) [inline doc/releases/migration-guide-4.2.rst:505]: Symbols that no longer exist can't use the `:kconfig:option:` directive.

```suggestion
* Renamed ``CONFIG_SPI_MCUX_LPSPI`` to :kconfig:option:`CONFIG_SPI_NXP_LPSPI`,
  and similar for any child configs for that driver, including
  :kconfig:option:`CONFIG_SPI_NXP_LPSPI_DMA` and :kconfig:option:`CONFIG_SPI_NXP_LPSPI_CPU`.
```

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 3]
```diff
@@ -101,16 +118,166 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
 
-int spi_mcux_configure(const struct device *dev, const struct spi_config *spi_cfg)
+static uint8_t lpspi_calc_delay(uint32_t desired_delay_ns, uint32_t best_delay_ns,
+				uint32_t prescaled_clock, uint32_t additional_scaler)
+{
+	uint64_t real_delay = NSEC_PER_SEC / prescaled_clock;
+	uint8_t best_scaler = 0, scaler = 0;
+	uint32_t diff, min_diff = 0xFFFFFFFF;
+
+	while (scaler < 256 && min_diff != 0) {
```
Comment (pdgendt) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:128]: `scaler` is a `uint8_t`, this condition does not make sense.

Comment (dleach02) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:128]: I'm surprised our new sonar static analysis didn't catch this

Comment (pdgendt) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:128]: Should we check if Copilot would? 👀

Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:128]: woops

File: doc/releases/migration-guide-4.2.rst (hunk 2 above)
Comment (decsny) [reply doc/releases/migration-guide-4.2.rst:505]: I was wondering if it would show up like a red link or something and if that was desired

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 3 above)
Comment (teburd) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:128]: > Should we check if Copilot would? 👀

Coverity would absolutely see this.

Copilot would helplessly suggest a typo fix while burning a small forest to do so.

Comment (teburd) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:128]: It turns out even clang would see this which should be entirely expected?

https://clang-tidy.godbolt.org/z/MWPx148xK

Comment (pdgendt) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:128]: Clang-tidy requires an actual build AFAIK, so not "free"

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 4]
```diff
@@ -101,16 +118,166 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+		real_delay *= ((uint64_t)scaler + 1 + (uint64_t)additional_scaler);
+
+		/* Delay must not be less than desired */
+		if (real_delay >= desired_delay_ns) {
+			diff = (uint32_t)(real_delay - (uint64_t)desired_delay_ns);
```
[the remark this answers is not in the document]
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:133]: I'll have to look into this more closely, I don't understand this suggestion immediately

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 5]
```diff
@@ -101,16 +118,166 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+	for (uint8_t prescaler = 0U; prescaler < 8U; prescaler++) {
+		uint8_t high = 255, low = 0, test_div = 255;
+		uint32_t real_freq = 0;
+
+		/* maximum freq won't get better than what we got with previous prescaler */
+		if (clock_freq / (TWO_EXP(prescaler) * 2) < best_freq) {
+			goto done;
+		}
+
+		while (test_div > 0) {
```
[the remark this answers is not in the document]
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:198]: um, I already did, so I don't know what it wants here

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 3 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:128]: I ran the AI below because I was curious what feedback it would give on my PR generally, and it didn't find this. So at least this copilot seems not reliable for rigorous static analysis right now.

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 6]
```diff
@@ -126,61 +293,47 @@ int spi_mcux_configure(const struct device *dev, const struct spi_config *spi_cf
...
 
+	lpspi_set_sckdiv(base, spi_cfg->frequency, clock_freq, &prescaler);
+	lpspi_set_delays(dev, clock_freq / TWO_EXP(prescaler));
+
+	base->CR |= LPSPI_CR_MEN_MASK;
+
+	base->TCR = LPSPI_TCR_CPOL(!!(spi_cfg->operation & SPI_MODE_CPOL)) |
+		    LPSPI_TCR_CPHA(!!(spi_cfg->operation & SPI_MODE_CPHA)) |
+		    LPSPI_TCR_LSBF(!!(spi_cfg->operation & SPI_TRANSFER_LSB)) |
+		    LPSPI_TCR_FRAMESZ(SPI_WORD_SIZE_GET(spi_cfg->operation)) |
```
Comment (kartben) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:332]: The FRAMESZ register field requires "number_of_bits - 1", plus, you probably want to use the clamped `word_size` from line 297 (which you probably wanted to as it's actually unused right now?)

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 7]
```diff
@@ -126,61 +293,47 @@ int spi_mcux_configure(const struct device *dev, const struct spi_config *spi_cf
...
+		    LPSPI_TCR_PRESCALE(prescaler) | LPSPI_TCR_PCS(spi_cfg->slave);
+
+	lpspi_wait_tx_fifo_empty(dev);
```
Comment (kartben) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:335]: check error code?

File: doc/releases/migration-guide-4.2.rst [hunk 8]
```diff
@@ -500,6 +500,9 @@ OpenThread
 SPI
 ===
 
+* Renamed Renamed :kconfig:option:`CONFIG_SPI_MCUX_LPSPI` to :kconfig:option:`CONFIG_SPI_NXP_LPSPI`,
```
Comment (kartben) [inline doc/releases/migration-guide-4.2.rst:503]:
```suggestion
* Renamed :kconfig:option:`CONFIG_SPI_MCUX_LPSPI` to :kconfig:option:`CONFIG_SPI_NXP_LPSPI`,
```

**Review by kartben — COMMENTED** [review]
so here's for my 100% AI-assisted code review (Gemini 2.5, in this case). I would be really curious to know if the comments related to LPSPI_TCR_FRAMESZ are actually correct (but I think they are) since obviously I have am pretty much clueless when it comes to LPSPI :) And also curious about what @decsny  and @teburd think, of course.

One more comment which I also don't know enough about the code to qualify as being legit or not

> `spi_nxp_lpspi_common.c` - Flawed logic in `lpspi_set_delays`:
> 
> * The conditions if (config->pcs_sck_delay <= minimum_delay_ns) (and similar for SCK-PCS and transfer delays) are counter-intuitive. They cause delay scalers to be configured only if the requested delay is extremely short (e.g., less than or equal to one tick of the prescaled clock). If a longer delay is requested, the if condition is false, and no scaler is set (defaulting to scaler 0, the shortest delay).
> * This is likely the opposite of the intended behavior. The delay scalers are meant to achieve specific, often longer, delays. These if conditions should probably be removed, allowing lpspi_calc_delay to always determine the best scaler (0-255) based on the config->*_delay_ns values. If a delay value in config is 0, lpspi_calc_delay will correctly return scaler = 0.
>

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 6 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:332]: man I hate that I messed that up lol

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 7 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:335]: true

File: doc/releases/migration-guide-4.2.rst (hunk 8 above)
Comment (decsny) [reply doc/releases/migration-guide-4.2.rst:503]: no, this is valid grammar, it's saying it's renaming the previously renamed config to another name. (just kidding, its a typo)

Comment (kartben) [reply doc/releases/migration-guide-4.2.rst:503]: > no, this is valid grammar, it's saying it's renaming the previously renamed config to another name. (just kidding, its a typo)

ROFL - you actually got me there :)

**Comment by decsny** [comment]
> One more comment which I also don't know enough about the code to qualify as being legit or not
> 
> > `spi_nxp_lpspi_common.c` - Flawed logic in `lpspi_set_delays`:
> > 
> > * The conditions if (config->pcs_sck_delay <= minimum_delay_ns) (and similar for SCK-PCS and transfer delays) are counter-intuitive. They cause delay scalers to be configured only if the requested delay is extremely short (e.g., less than or equal to one tick of the prescaled clock). If a longer delay is requested, the if condition is false, and no scaler is set (defaulting to scaler 0, the shortest delay).
> > * This is likely the opposite of the intended behavior. The delay scalers are meant to achieve specific, often longer, delays. These if conditions should probably be removed, allowing lpspi_calc_delay to always determine the best scaler (0-255) based on the config->*_delay_ns values. If a delay value in config is 0, lpspi_calc_delay will correctly return scaler = 0.

I had to go back and see how the hardware works and what this code meant since I wrote it months ago now, but, the AI is wrong here. The dividers were already calculated at this point, and what these functions do is actually directly calculate the delay cycles, which will then be divided. So actually the code is doing the correct thing by skipping the calculation if we already know the best minimum is 1 cycle (hardware default, value 0, which will be written at the end of the routine).

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 9]
```diff
@@ -101,16 +118,166 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+
+			/* check if we are closer to the desired */
+			if (real_freq >= best_freq) {
+				best_prescaler = prescaler;
+				best_div = test_div;
+				best_freq = real_freq;
+			}
+
+			/* if our best found is a match, we're done */
+			if (best_freq == desired_freq) {
```
Comment (MikhailSiomin) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: If the `clock frequency` is 254117647 and the `desired frequency` is 4100000, then the `desired frequency` will never be reached and the `loop` will continue `indefinitely`.

**Comment by decsny** [comment]
update: fixed the sonarqubecloud complaint and fixed the twister failure

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 10]
```diff
@@ -53,12 +62,22 @@ static inline clock_ip_name_t lpspi_get_clock(LPSPI_Type *const base)
...
 	LPSPI_Type *base = (LPSPI_Type *)DEVICE_MMIO_NAMED_GET(dev, reg_base);
-
-	while (LPSPI_GetTxFifoCount(base) != 0) {
+	int arbitrary_cycle_limit = CONFIG_SPI_NXP_LPSPI_TXFIFO_WAIT_CYCLES;
+	bool limit_wait = arbitrary_cycle_limit > 0;
+
+	while (FIELD_GET(LPSPI_FSR_TXCOUNT_MASK, base->FSR) != 0) {
+		if (!limit_wait) {
+			continue;
+		} else if (arbitrary_cycle_limit-- < 0) {
```
[the remark this answers is not in the document]
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: it really doesn't matter

[the remark this answers is not in the document]
Comment (kartben) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: right but it is, however, a coding guideline violation ([rule 78](https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#:~:text=A%20full%20expression%20containing%20an%20increment%20(%2B%2B)%20or%20decrement%20(%E2%80%93)%20operator%20should%20have%20no%20other%20potential%20side%20effects%20other%20than%20that%20caused%20by%20the%20increment%20or%20decrement%20operator))

[the remark this answers is not in the document]
Comment (kartben) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: unresolving the comment so that it shows up and gets a chance to be addressed, even if the fix that's needed is different from what copilot initially pointed out :)

[the remark this answers is not in the document]
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: How is it noncompliant? The expression doesn't have any other side effects, just like the rule says

[the remark this answers is not in the document]
Comment (kartben) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: I might have misinterpreted the rule - I thought it was meant to discourage this kind of construct but looking at all the examples I could find I am probably wrong :) Sorry for the noise.

[the remark this answers is not in the document]
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: @kartben To be clear, a side effect is just anything that is an observable change in the program state besides the evaluation (return value, if you will) of an expression. In this case the expression is "returning" (evaluating) to true or false, and there is one side effect (the decrement of the variable). 

Interestingly, an expression like `x = 10` is also an expression with 1 side effect. The overall expression evaluates to 10, but it also has a "side effect" of changing the value of `x` to 10.

**Comment by sgfeniex** [comment]
This resolves a LPSPI regression from earlier this year on our custom board accessing a ISSI flash device.

Looking forward to seeing this merged.

**Comment by decsny** [comment]
Fixes #91015

File: drivers/spi/spi_nxp_lpspi/Kconfig [hunk 11]
```diff
@@ -27,13 +27,29 @@ config SPI_MCUX_LPSPI_DMA
...
+config SPI_NXP_LPSPI_TXFIFO_WAIT_CYCLES
+	int "Number of CPU cycles to wait on TX fifo empty"
+	default 0 if DEBUG
+	default 10000
+	help
+	  This option most likely does not need changed.
+	  The drivers tend to need to wait on confirming the transmit command
+	  is consumed by the hardware by checking of the TX fifo is emptied.
+	  Usually this should not be a problem and should happen immediately,
+	  but in the rare case of some bug, this option is available to avoid
```
Comment (dleach02) [inline drivers/spi/spi_nxp_lpspi/Kconfig]: "rare case of some bug". Where would the bug be?

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (dleach02) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: it seems to be worried about doing the repeated "real_delay *= ..." and how that would exponentially grow the value in real_delay. But the suggestion seems to fundamentally change the algorithm you have because now your steps would be smaller and I guess less steps.

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 12]
```diff
@@ -101,17 +120,204 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
 	return 0;
 }
 
-int spi_mcux_configure(const struct device *dev, const struct spi_config *spi_cfg)
+static uint8_t lpspi_calc_delay(uint32_t desired_delay_ns, uint32_t best_delay_ns,
+				uint32_t prescaled_clock, uint32_t additional_scaler)
```
Comment (dleach02) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: best_delay_ns isn't used in this function. Does the build give you any warnings on this?

just a bit of a nit but wouldn't this function be more appropriately named lpspi_calc_delay_scaler?

When is additional_scaler needed?

File: drivers/spi/spi_nxp_lpspi/Kconfig (hunk 11 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/Kconfig]: Basically, if for some reason the TX FIFO is not emptying then the command will not be consumed because the SPI hardware configuration commands go in the same FIFO as the TX data. That's one of the things that makes this LPSPI somewhat odd to deal with. Obviously this is not the intended situation and the TX fifo is supposed to be emptied automatically by the hardware for as long as the transfer is going on. But the possibility of an infinite loop in ISR because of some unforeseen programming error which ends the transfer too early or something might scare some people, which is why I am adding this default timeout. There's no bug like that which I know of now, but can't be too confident, especially since software is always changing. Are you saying the help string should be reworded to not mention "bugs"

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 13]
```diff
@@ -101,17 +120,204 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+		ccr |= LPSPI_CCR_SCKPCS(lpspi_calc_delay(config->sck_pcs_delay,
+							 minimum_delay_ns * 256,
+							 prescaled_clock, 0));
+	}
+
+	if (config->transfer_delay <= (2 * minimum_delay_ns)) {
+		ccr |= LPSPI_CCR_DBT(lpspi_calc_delay(config->transfer_delay,
+						      minimum_delay_ns * 257,
+						      prescaled_clock, 1));
+	}
```
Comment (dleach02) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: while the second parameter is not used, it does make me wonder why the first two multiply by 256 and the last one by 257?

Why does the last one need additional_scaler of 1?

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 14]
```diff
@@ -101,17 +120,204 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+static uint32_t lpspi_calc_sck_freq(uint32_t src_clk_hz, uint16_t sckdiv, uint8_t prescaler)
+{
+	return (uint32_t)(src_clk_hz / (TWO_EXP(prescaler) * (sckdiv + 2)));
+}
+
+/* This function returns the best div for a prescaler, within the frequency bound
+ * of the min and max params, given a src clk freq. It tries to get as close to
+ * the max freq as possible without going over, with min freq as the value to beat.
+ */
+static inline uint8_t lpspi_find_best_div_for_prescale(uint32_t src_clk_hz,
```
Comment (dleach02) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: nit: probably should name the function ...prescaler()

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 12 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: additional_scaler is just a parameter to be able to abstract all the code instead of having a separate one for DBT. Since the calculation is +1 for DBT because the other two already have +1 in the hardware

and no , there's no build warning about that unused parameter. I don't remember what it was for originally but you're right that it's clearly not used anymore.

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 13 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: That's just the formula for the last one (DBT), I don't know why

**Comment by decsny** [comment]
rebased, took suggestions of sonarqubecloud and @dleach02

**Comment by decsny** [comment]
rebased onto https://github.com/zephyrproject-rtos/zephyr/pull/91079 and also added two commits fixing some things related to TX fifo fill

**Comment by decsny** [comment]
updates: 

- fixed an issue reported to me by @hakehuang  about the timing test failing on the MCX series, turns out one of the registers which is readable on other platforms is write-only on this MCX 🙄 
- I found and fixed a potential issue which could cause extra bytes to be sent at the end of the transfer for the interrupt-based driver. Not sure if it is the same issue that is causing #90614 ?

**Comment by pdgendt** [comment]
Running this on MIMXRT1170-EVKB:

```
------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [spi_extra_api_features]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.003 seconds
 - PASS - [spi_extra_api_features.test_spi_hold_on_cs] duration = 0.002 seconds
 - PASS - [spi_extra_api_features.test_spi_lock_release] duration = 0.001 seconds

SUITE FAIL -  84.00% [spi_loopback]: pass = 21, fail = 4, skip = 0, total = 25 duration = 0.408 seconds
 - PASS - [spi_loopback.test_nop_nil_bufs] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_async_call] duration = 0.137 seconds
 - PASS - [spi_loopback.test_spi_complete_large_transfers] duration = 0.136 seconds
 - PASS - [spi_loopback.test_spi_complete_loop_mode_0] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_loop_mode_1] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_loop_mode_2] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_loop_mode_3] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_multiple] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_multiple_timed] duration = 0.008 seconds
 - FAIL - [spi_loopback.test_spi_concurrent_transfer_different_spec] duration = 0.032 seconds
 - FAIL - [spi_loopback.test_spi_concurrent_transfer_same_spec] duration = 0.032 seconds
 - PASS - [spi_loopback.test_spi_null_rx_buf_set] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_null_tx_buf] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_null_tx_buf_set] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_rx_bigger_than_tx] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_rx_every_4] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_rx_half_end] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_rx_half_start] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_same_buf_cmd] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_word_size_16] duration = 0.001 seconds
 - FAIL - [spi_loopback.test_spi_word_size_24] duration = 0.022 seconds
 - PASS - [spi_loopback.test_spi_word_size_32] duration = 0.004 seconds
 - PASS - [spi_loopback.test_spi_word_size_7] duration = 0.001 seconds
 - FAIL - [spi_loopback.test_spi_word_size_9] duration = 0.020 seconds
 - PASS - [spi_loopback.test_spi_write_back] duration = 0.001 seconds

------ TESTSUITE SUMMARY END ------
```

**Comment by decsny** [comment]
> Running this on MIMXRT1170-EVKB:
> 
> ```
> ------ TESTSUITE SUMMARY START ------
> 
> SUITE PASS - 100.00% [spi_extra_api_features]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.003 seconds
>  - PASS - [spi_extra_api_features.test_spi_hold_on_cs] duration = 0.002 seconds
>  - PASS - [spi_extra_api_features.test_spi_lock_release] duration = 0.001 seconds
> 
> SUITE FAIL -  84.00% [spi_loopback]: pass = 21, fail = 4, skip = 0, total = 25 duration = 0.408 seconds
>  - PASS - [spi_loopback.test_nop_nil_bufs] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_async_call] duration = 0.137 seconds
>  - PASS - [spi_loopback.test_spi_complete_large_transfers] duration = 0.136 seconds
>  - PASS - [spi_loopback.test_spi_complete_loop_mode_0] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_complete_loop_mode_1] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_complete_loop_mode_2] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_complete_loop_mode_3] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_complete_multiple] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_complete_multiple_timed] duration = 0.008 seconds
>  - FAIL - [spi_loopback.test_spi_concurrent_transfer_different_spec] duration = 0.032 seconds
>  - FAIL - [spi_loopback.test_spi_concurrent_transfer_same_spec] duration = 0.032 seconds
>  - PASS - [spi_loopback.test_spi_null_rx_buf_set] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_null_tx_buf] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_null_tx_buf_set] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_rx_bigger_than_tx] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_rx_every_4] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_rx_half_end] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_rx_half_start] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_same_buf_cmd] duration = 0.001 seconds
>  - PASS - [spi_loopback.test_spi_word_size_16] duration = 0.001 seconds
>  - FAIL - [spi_loopback.test_spi_word_size_24] duration = 0.022 seconds
>  - PASS - [spi_loopback.test_spi_word_size_32] duration = 0.004 seconds
>  - PASS - [spi_loopback.test_spi_word_size_7] duration = 0.001 seconds
>  - FAIL - [spi_loopback.test_spi_word_size_9] duration = 0.020 seconds
>  - PASS - [spi_loopback.test_spi_write_back] duration = 0.001 seconds
> 
> ------ TESTSUITE SUMMARY END ------
> ```

to be clear, those fails are already on main, and not supposed to be fixed on this PR

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 15]
```diff
@@ -126,62 +326,55 @@ int spi_mcux_configure(const struct device *dev, const struct spi_config *spi_cf
 		return ret;
 	}
 
+	/* For the purpose of configuring the LPSPI, 8 is the minimum frame size for the hardware */
+	word_size = word_size < 8 ? 8 : word_size;
```
Comment (pdgendt) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]:
```suggestion
	word_size = MAX(8, word_size);
```

**Review by MikhailSiomin — COMMENTED** [review]
https://github.com/zephyrproject-rtos/zephyr/blob/58c0fea675c003da7ec96568246d308564bf47fa/drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c#L167-L168
`current_buf->len` stores the number of bytes, but `buf_len` argumet of `lpspi_fill_tx_fifo` function multiply by the number of bytes in the word.

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 9 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: I think you are reviewing an old revision from when this PR was in draft state, I fixed this algorithm a lot and tested millions of combinations, and had no problems, I can try that one to confirm though

edit: confirmed that the algorithm got `4098671` as the best frequency for the parameters you described and had no problem

Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: to be clear, not every frequency is exactly possible, its not supposed to reach exactly `4100000`, because that's not possible, the code you commented on (well for one, no longer exists) is a *fast path*, not the main/expected way for the loop to stop

Comment (MikhailSiomin) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: @decnsy, sorry, I created a comment incorrectly, which pulled up an old comment. I wanted to report about the `lpspi_fill_tx_fifo` function

**Comment by decsny** [comment]
> https://github.com/zephyrproject-rtos/zephyr/blob/58c0fea675c003da7ec96568246d308564bf47fa/drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c#L167-L168
> 
> `current_buf->len` stores the number of bytes, but `buf_len` argumet of `lpspi_fill_tx_fifo` function multiply by the number of bytes in the word.

Okay... I think you might be right about this but that code is not being touched by this PR at all, and it would be an issue on main... I guess since this PR is becoming a bit of a kitchen sink unfortunately anyways, I suppose can add a commit to fix issue that as well, if it's truly wrong. I'll have to check though because right now that driver (the interrupt-based one) is passing all the different word size test cases both on main and this PR, so not sure what's going on there

**Comment by MikhailSiomin** [comment]
@decsny, unfortunately, now I can't get it to work with nand-flash memory and some sensors, unlike the driver of zephyr-4.0.0.

**Comment by decsny** [comment]
> @decsny, unfortunately, now I can't get it to work with nand-flash memory and some sensors, unlike the driver of zephyr-4.0.0.

Are you saying this PR is breaking it for you? Or are you saying it's an issue on main? If it's an issue on main then please submit a bug report about it with more details

**Comment by MikhailSiomin** [comment]
> > @decsny, unfortunately, now I can't get it to work with nand-flash memory and some sensors, unlike the driver of zephyr-4.0.0.
> 
> Are you saying this PR is breaking it for you? Or are you saying it's an issue on main? If it's an issue on main then please submit a bug report about it with more details

main and this PR do not work for me. I will try to figure out this problem and give feedback in the issue if the problem is on the driver side. Thanks

**Comment by igalloway** [comment]
Thanks for the great effort so far. 
We need this PR to be finished to a reasonable level so it can be pushed - so we can then continue to iterate on the remaining associated issues.
Could you please allocate some time to work on it to get it in decent shape?
Currently it is blocking proper SPI performance needed for high data rate sensors with low latency.
We would very much appreciate increasing the priority somehow.

**Comment by decsny** [comment]
> Could you please allocate some time to work on it to get it in decent shape?

What part of it is not decent? Can you clarify what you are asking for? 

> We would very much appreciate increasing the priority somehow.

I am already working on this as highest priority as I have been for the last 6 months, if you want it to go faster you are more than welcome to help by submitting contributions.

**Comment by igalloway** [comment]
> > Could you please allocate some time to work on it to get it in decent shape?
> 
> What part of it is not decent? Can you clarify what you are asking for?
> 
> > We would very much appreciate increasing the priority somehow.
> 
> I am already working on this as highest priority as I have been for the last 6 months, if you want it to go faster you are more than welcome to help by submitting contributions.

Decent was a poor choice of wording.
I did not mean for this to be directed at you, but towards getting it reviewed by colleagues and getting it into a "final mergeable" state. Including the required approvals.

**Comment by decsny** [comment]
update:

- rebase
- added fix suggested by @MikhailSiomin regarding filling tx fifo.  There could have been an issue if the very end of a buffer was smaller than the size of a word, in other words, buf_size % word_size != 0
- confirmed I made a mistake on the last push by calculating the prescaler after the delay scalars (the prescaler must be known for the delay calculations), thanks @smaherdev for reporting an issue with the delays on this PR so I realized this. I had the DNM because of this issue, so now that I think I fixed it, I removed the DNM.

So now AFAIK the PR is ready

**Comment by hakehuang** [comment]
with my mimxrt1170_evk@B board
```
*** Booting Zephyr OS build v4.1.0-5591-g28f940aa4d4c ***
SPI test on buffers TX/RX 0x80004160/0x80004140, frame size = 8, DMA enabled
Polling...Running TESTSUITE spi_extra_api_features
===================================================================
START - test_spi_hold_on_cs
 PASS - test_spi_hold_on_cs in 0.002 seconds
===================================================================
START - test_spi_lock_release
 PASS - test_spi_lock_release in 0.001 seconds
===================================================================
TESTSUITE spi_extra_api_features succeeded
Running TESTSUITE spi_extra_api_features
===================================================================
START - test_spi_hold_on_cs
 PASS - test_spi_hold_on_cs in 0.002 seconds
===================================================================
START - test_spi_lock_release
 PASS - test_spi_lock_release in 0.001 seconds
===================================================================
TESTSUITE spi_extra_api_features succeeded
Running TESTSUITE spi_loopback
===================================================================
Testing loopback spec: SLOW
START - test_nop_nil_bufs
 PASS - test_nop_nil_bufs in 0.001 seconds
===================================================================
START - test_spi_async_call
 PASS - test_spi_async_call in 0.138 seconds
===================================================================
START - test_spi_complete_large_transfers
 PASS - test_spi_complete_large_transfers in 0.136 seconds
===================================================================
START - test_spi_complete_loop_mode_0
 PASS - test_spi_complete_loop_mode_0 in 0.001 seconds
===================================================================
START - test_spi_complete_loop_mode_1
 PASS - test_spi_complete_loop_mode_1 in 0.001 seconds
===================================================================
START - test_spi_complete_loop_mode_2
 PASS - test_spi_complete_loop_mode_2 in 0.001 seconds
===================================================================
START - test_spi_complete_loop_mode_3
 PASS - test_spi_complete_loop_mode_3 in 0.001 seconds
===================================================================
START - test_spi_complete_multiple
 PASS - test_spi_complete_multiple in 0.002 seconds
===================================================================
START - test_spi_complete_multiple_timed
Transfer took 959 us vs theoretical minimum 864 us
Latency measurement: 95 us
 PASS - test_spi_complete_multiple_timed in 0.008 seconds
===================================================================
START - test_spi_concurrent_transfer_different_spec
SPI concurrent transfer data mismatch, spec 0x80008bfc
SPI concurrent transfer data mismatch, spec 0x80008bcc
SPI concurrent transfer data mismatch, spec 0x80008be4

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:787: test_spi_concurrent_transfer_helper: atomic_get(&thread_test_fails) not equal to 0

 FAIL - test_spi_concurrent_transfer_different_spec in 0.032 seconds
===================================================================
START - test_spi_concurrent_transfer_same_spec
SPI concurrent transfer data mismatch, spec 0x80008028
SPI concurrent transfer data mismatch, spec 0x80008028
SPI concurrent transfer data mismatch, spec 0x80008028

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:787: test_spi_concurrent_transfer_helper: atomic_get(&thread_test_fails) not equal to 0

 FAIL - test_spi_concurrent_transfer_same_spec in 0.032 seconds
===================================================================
START - test_spi_null_rx_buf_set
 PASS - test_spi_null_rx_buf_set in 0.001 seconds
===================================================================
START - test_spi_null_tx_buf
 PASS - test_spi_null_tx_buf in 0.001 seconds
===================================================================
START - test_spi_null_tx_buf_set
 PASS - test_spi_null_tx_buf_set in 0.001 seconds
===================================================================
START - test_spi_rx_bigger_than_tx
 PASS - test_spi_rx_bigger_than_tx in 0.001 seconds
===================================================================
START - test_spi_rx_every_4
 PASS - test_spi_rx_every_4 in 0.001 seconds
===================================================================
START - test_spi_rx_half_end
 PASS - test_spi_rx_half_end in 0.001 seconds
===================================================================
START - test_spi_rx_half_start
 PASS - test_spi_rx_half_start in 0.001 seconds
===================================================================
START - test_spi_same_buf_cmd
 PASS - test_spi_same_buf_cmd in 0.001 seconds
===================================================================
START - test_spi_word_size_16
 PASS - test_spi_word_size_16 in 0.001 seconds
===================================================================
START - test_spi_word_size_24

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:643: spi_loopback_test_word_size: (memcmp(compare_data, rx_buffer, buffer_size) is true)
24-bit word buffer contents are different
 FAIL - test_spi_word_size_24 in 0.022 seconds
===================================================================
START - test_spi_word_size_32
 PASS - test_spi_word_size_32 in 0.004 seconds
===================================================================
START - test_spi_word_size_7
 PASS - test_spi_word_size_7 in 0.001 seconds
===================================================================
START - test_spi_word_size_9

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:643: spi_loopback_test_word_size: (memcmp(compare_data, rx_buffer, buffer_size) is true)
9-bit word buffer contents are different
 FAIL - test_spi_word_size_9 in 0.020 seconds
===================================================================
START - test_spi_write_back
 PASS - test_spi_write_back in 0.001 seconds
===================================================================
TESTSUITE spi_loopback failed.
Running TESTSUITE spi_loopback
===================================================================
Testing loopback spec: FAST
START - test_nop_nil_bufs
 PASS - test_nop_nil_bufs in 0.001 seconds
===================================================================
START - test_spi_async_call
 PASS - test_spi_async_call in 0.010 seconds
===================================================================
START - test_spi_complete_large_transfers
 PASS - test_spi_complete_large_transfers in 0.009 seconds
===================================================================
START - test_spi_complete_loop_mode_0
 PASS - test_spi_complete_loop_mode_0 in 0.001 seconds
===================================================================
START - test_spi_complete_loop_mode_1
 PASS - test_spi_complete_loop_mode_1 in 0.001 seconds
===================================================================
START - test_spi_complete_loop_mode_2
 PASS - test_spi_complete_loop_mode_2 in 0.001 seconds
===================================================================
START - test_spi_complete_loop_mode_3
 PASS - test_spi_complete_loop_mode_3 in 0.001 seconds
===================================================================
START - test_spi_complete_multiple
 PASS - test_spi_complete_multiple in 0.001 seconds
===================================================================
START - test_spi_complete_multiple_timed
Transfer took 106 us vs theoretical minimum 27 us
Latency measurement: 79 us
 PASS - test_spi_complete_multiple_timed in 0.007 seconds
===================================================================
START - test_spi_concurrent_transfer_different_spec
SPI concurrent transfer data mismatch, spec 0x80008bfc
SPI concurrent transfer data mismatch, spec 0x80008bcc
SPI concurrent transfer data mismatch, spec 0x80008be4

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:787: test_spi_concurrent_transfer_helper: atomic_get(&thread_test_fails) not equal to 0

 FAIL - test_spi_concurrent_transfer_different_spec in 0.031 seconds
===================================================================
START - test_spi_concurrent_transfer_same_spec
SPI concurrent transfer data mismatch, spec 0x80008040
SPI concurrent transfer data mismatch, spec 0x80008040
SPI concurrent transfer data mismatch, spec 0x80008040

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:787: test_spi_concurrent_transfer_helper: atomic_get(&thread_test_fails) not equal to 0

 FAIL - test_spi_concurrent_transfer_same_spec in 0.031 seconds
===================================================================
START - test_spi_null_rx_buf_set
 PASS - test_spi_null_rx_buf_set in 0.001 seconds
===================================================================
START - test_spi_null_tx_buf
 PASS - test_spi_null_tx_buf in 0.001 seconds
===================================================================
START - test_spi_null_tx_buf_set
 PASS - test_spi_null_tx_buf_set in 0.001 seconds
===================================================================
START - test_spi_rx_bigger_than_tx
 PASS - test_spi_rx_bigger_than_tx in 0.001 seconds
===================================================================
START - test_spi_rx_every_4
 PASS - test_spi_rx_every_4 in 0.001 seconds
===================================================================
START - test_spi_rx_half_end
 PASS - test_spi_rx_half_end in 0.001 seconds
===================================================================
START - test_spi_rx_half_start
 PASS - test_spi_rx_half_start in 0.001 seconds
===================================================================
START - test_spi_same_buf_cmd
 PASS - test_spi_same_buf_cmd in 0.001 seconds
===================================================================
START - test_spi_word_size_16
 PASS - test_spi_word_size_16 in 0.001 seconds
===================================================================
START - test_spi_word_size_24

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:643: spi_loopback_test_word_size: (memcmp(compare_data, rx_buffer, buffer_size) is true)
24-bit word buffer contents are different
 FAIL - test_spi_word_size_24 in 0.020 seconds
===================================================================
START - test_spi_word_size_32
 PASS - test_spi_word_size_32 in 0.001 seconds
===================================================================
START - test_spi_word_size_7
 PASS - test_spi_word_size_7 in 0.001 seconds
===================================================================
START - test_spi_word_size_9

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:643: spi_loopback_test_word_size: (memcmp(compare_data, rx_buffer, buffer_size) is true)
9-bit word buffer contents are different
 FAIL - test_spi_word_size_9 in 0.019 seconds
===================================================================
START - test_spi_write_back
 PASS - test_spi_write_back in 0.001 seconds
===================================================================
TESTSUITE spi_loopback failed.

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [spi_extra_api_features]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.003 seconds
 - PASS - [spi_extra_api_features.test_spi_hold_on_cs] duration = 0.002 seconds
 - PASS - [spi_extra_api_features.test_spi_lock_release] duration = 0.001 seconds

SUITE FAIL -  84.00% [spi_loopback]: pass = 21, fail = 4, skip = 0, total = 25 duration = 0.410 seconds
 - PASS - [spi_loopback.test_nop_nil_bufs] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_async_call] duration = 0.138 seconds
 - PASS - [spi_loopback.test_spi_complete_large_transfers] duration = 0.136 seconds
 - PASS - [spi_loopback.test_spi_complete_loop_mode_0] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_loop_mode_1] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_loop_mode_2] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_loop_mode_3] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_complete_multiple] duration = 0.002 seconds
 - PASS - [spi_loopback.test_spi_complete_multiple_timed] duration = 0.008 seconds
 - FAIL - [spi_loopback.test_spi_concurrent_transfer_different_spec] duration = 0.032 seconds
 - FAIL - [spi_loopback.test_spi_concurrent_transfer_same_spec] duration = 0.032 seconds
 - PASS - [spi_loopback.test_spi_null_rx_buf_set] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_null_tx_buf] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_null_tx_buf_set] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_rx_bigger_than_tx] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_rx_every_4] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_rx_half_end] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_rx_half_start] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_same_buf_cmd] duration = 0.001 seconds
 - PASS - [spi_loopback.test_spi_word_size_16] duration = 0.001 seconds
 - FAIL - [spi_loopback.test_spi_word_size_24] duration = 0.022 seconds
 - PASS - [spi_loopback.test_spi_word_size_32] duration = 0.004 seconds
 - PASS - [spi_loopback.test_spi_word_size_7] duration = 0.001 seconds
 - FAIL - [spi_loopback.test_spi_word_size_9] duration = 0.020 seconds
 - PASS - [spi_loopback.test_spi_write_back] duration = 0.001 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: 6a393893f19313cd73eab94086cba3a8
PROJECT EXECUTION FAILED

```

**Comment by decsny** [comment]
Again, like I told the other person, those failures are all existing on main, they have to do only with the DMA-based driver, I made bug reports for them last week, they are not regressions, and I am not messing with trying to fix the DMA-based transfer driver on this PR, it's out of scope

**Comment by decsny** [comment]
At this point I am not accepting any more comments for scope expansions on this PR, there's been enough, this PR is becoming a kitchen sink.

Reviewers just tell me if this PR is specifically regressing something, or review _only the code being changed on this PR_ for if you don't like some part of it.

If anyone wants to have some other feature or optimization or bug fix added to the driver, please make a separate github issue (minding the ones that already exist) or submit your own PR, otherwise this one is never going to merge.

The only thing I'm left to do right now is apparently the delay scalars are still being regressed on this PR according to @smaherdev so I am going to try to figure that out, so the DNM is back for now

**Comment by pdgendt** [comment]
> If anyone wants to have some other feature or optimization or bug fix added to the driver, please make a separate github issue (minding the ones that already exist) or submit your own PR, otherwise this one is never going to merge.
> 
> The only thing I'm left to do right now is apparently the delay scalars are still being regressed on this PR according to @smaherdev so I am going to try to figure that out, so the DNM is back for now

_Just some feedback regarding this, ignore if it isn't relevant_

Trying to get an nRF7002EK shield working with the LPSPI driver (tested both mimxrt1050_evk and mimxrt1170_evk), I do think the `pcs-sck-delay` and `sck-pcs-delay` values aren't applied properly. Setting these to `5000` (5 µs) still results in:

image

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 16]
```diff
@@ -101,17 +122,196 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+}
+
+/* returns CCR mask of the bits 8-31 */
+static inline uint32_t lpspi_set_delays(const struct device *dev, uint32_t prescaled_clock)
+{
+	uint64_t minimum_delay_ns = NSEC_PER_SEC / prescaled_clock;
+	const struct lpspi_config *config = dev->config;
+	uint32_t ccr = 0;
+
+	ccr &= ~(LPSPI_CCR_PCSSCK_MASK | LPSPI_CCR_SCKPCS_MASK | LPSPI_CCR_DBT_MASK);
```
Comment (pdgendt) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: This line does nothing as the value is set to `0` two lines above.

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 17]
```diff
@@ -101,17 +122,196 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+
+	if (config->pcs_sck_delay <= minimum_delay_ns) {
```
Comment (pdgendt) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: Shouldn't this be `>=`?

```suggestion
	if (config->pcs_sck_delay >= minimum_delay_ns) {
```

**Comment by decsny** [comment]
> > If anyone wants to have some other feature or optimization or bug fix added to the driver, please make a separate github issue (minding the ones that already exist) or submit your own PR, otherwise this one is never going to merge.
> > The only thing I'm left to do right now is apparently the delay scalars are still being regressed on this PR according to @smaherdev so I am going to try to figure that out, so the DNM is back for now
> 
> _Just some feedback regarding this, ignore if it isn't relevant_
> 
> Trying to get an nRF7002EK shield working with the LPSPI driver (tested both mimxrt1050_evk and mimxrt1170_evk), I do think the `pcs-sck-delay` and `sck-pcs-delay` values aren't applied properly. Setting these to `5000` (5 µs) still results in:

Yeah I reproduced it and am fixing it, I'm doing more rigorous regression testing for it now similar to how I did for the sckdiv

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 15 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: Thanks

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 16 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: True

**Comment by decsny** [comment]
I found that issue with the delay scalers was because I somewhat mindlessly copied the algorithm from the SDK without thinking too much about it, assuming it would be the same, but I made some mistakes which led to most cases being "edge" cases. 

The code that was there for those scalers on this PR before latest push was atrociously bad due to my mistakes, so I apologize to anyone who tested this PR for wasting their time.

The good news is that now I've fixed it and done a lot of regression testing with many different scaler and clock frequency combinations, and I'm pretty confident about it now. And on top of that, when I was looking into this, I realized that the algorithm used by the SDK was ridiculously overcomplicated, amazingly so. I've done a new algorithm which has the same behavior as the old one but is way simpler and therefore should be much faster. Even though it is still a basic naive linear search, nevertheless, what I measure for the new code size of the configure functions are hundreds of bytes less than what is reported in the original PR message, and the configure latency is hundreds of cycles less as well.

**Comment by decsny** [comment]
update:
- rebase
- fixed delay scalers
- removed fill_len from driver data because it is no longer used (forgot to do this before)
- fixed extra byte issue from #90614 (I think)

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 18]
```diff
@@ -101,17 +122,193 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+
+		/* if our best found is an exact match, we're done early */
+		if (min_freq == max_freq) {
+			break;
+		}
+	} while (low < high);
+
+	if (low == high) {
+		new_freq = lpspi_calc_sck_freq(src_clk_hz, high, prescaler);
+		if (new_freq > min_freq && new_freq <= max_freq) {
```
[the remark this answers is not in the document]
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:219]: wrong

File: drivers/spi/spi_nxp_lpspi/Kconfig [hunk 19]
```diff
@@ -27,13 +27,26 @@ config SPI_MCUX_LPSPI_DMA
...
 	help
 	  Enable "normal" CPU based SPI driver for LPSPI.
 	  This has lower latency than DMA-based driver but over the
 	  longer transfers will likely have less bandwidth and use more CPU time.
 
-endif # SPI_MCUX_LPSPI
+config SPI_NXP_LPSPI_TXFIFO_WAIT_CYCLES
+	int "Number of CPU cycles to wait on TX fifo empty"
+	default 0 if DEBUG
+	default 10000
```
[the remark this answers is not in the document]
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/Kconfig:42]: ?

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 18 above)
[the remark this answers is not in the document]
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: I think this is redundant and will never happen, because, 1) the logic in the loop already checks for the case of the exact match, and 2) the purpose of this code is for a situation where we exhausted all the possibilities in the search, so there wouldn't have been an exact match. But, it doesn't hurt to have a bit of built in redundancy, so I'll change the sign if I have to push again

File: drivers/spi/spi_nxp_lpspi/Kconfig (hunk 19 above)
[the remark this answers is not in the document]
Comment (hakehuang) [reply drivers/spi/spi_nxp_lpspi/Kconfig:42]: @decsny now zephyr project enables copilot review, but copilot is not good at Kconfig staff.

**Comment by pdgendt** [comment]
_Thanks for the continued effort, I'm just going to post my first naive approach to test the updated version here. Will take a look at the calculated values too._

So I patch the following minimal change:

```diff
diff --git a/boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm7.dts b/boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm7.dts
index 0da2e365a25..8b8a2cde645 100644
--- a/boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm7.dts
+++ b/boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm7.dts
@@ -106,8 +106,10 @@ zephyr_mipi_dsi: &mipi_dsi {
 };

 &lpspi1 {
-       dmas = <&edma0 0 36>, <&edma0 1 37>;
-       dma-names = "rx", "tx";
+       pcs-sck-delay = <5000>;
+       sck-pcs-delay = <5000>;
        status = "okay";
 };
```

The full resulting `lpspi1` node after
``` shell
$ west build -p -b mimxrt1170_evk/mimxrt1176/cm7 samples/net/wifi/shell --shield nrf7002ek
```

```dts
		/* node '/soc/spi@40114000' defined in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:422 */
		lpspi1: arduino_spi: spi@40114000 {
			compatible = "nxp,lpspi";         /* in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:423 */
			reg = < 0x40114000 0x4000 >;      /* in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:424 */
			interrupts = < 0x26 0x3 >;        /* in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:425 */
			clocks = < &ccm 0x500 0x6c 0x0 >; /* in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:427 */
			rx-fifo-size = < 0x10 >;          /* in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:428 */
			tx-fifo-size = < 0x10 >;          /* in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:429 */
			#address-cells = < 0x1 >;         /* in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:430 */
			#size-cells = < 0x0 >;            /* in zephyr/dts/arm/nxp/nxp_rt11xx.dtsi:431 */
			pinctrl-0 = < &pinmux_lpspi1 >;   /* in zephyr/boards/nxp/mimxrt1170_evk/mimxrt1170_evk.dtsi:214 */
			pinctrl-names = "default";        /* in zephyr/boards/nxp/mimxrt1170_evk/mimxrt1170_evk.dtsi:215 */
			pcs-sck-delay = < 0x1388 >;       /* in zephyr/boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm7.dts:111 */
			sck-pcs-delay = < 0x1388 >;       /* in zephyr/boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm7.dts:112 */
			status = "okay";                  /* in zephyr/boards/shields/nrf7002ek/nrf7002ek.overlay:15 */

			/* node '/soc/spi@40114000/nrf7002-spi@0' defined in zephyr/boards/shields/nrf7002ek/nrf7002ek.overlay:17 */
			nrf70: nrf7002-spi@0 {
				compatible = "nordic,nrf7002-spi";               /* in zephyr/boards/shields/nrf7002ek/nrf7002ek.overlay:18 */
				status = "okay";                                 /* in zephyr/boards/shields/nrf7002ek/nrf7002ek.overlay:19 */
				reg = < 0x0 >;                                   /* in zephyr/boards/shields/nrf7002ek/nrf7002ek.overlay:20 */
				spi-max-frequency = < 0x7a1200 >;                /* in zephyr/boards/shields/nrf7002ek/nrf7002ek.overlay:21 */
				iovdd-ctrl-gpios = < &arduino_header 0x6 0x20 >; /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:10 */
				bucken-gpios = < &arduino_header 0x7 0x20 >;     /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:12 */
				host-irq-gpios = < &arduino_header 0xd 0x0 >;    /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:14 */
				srrf-switch-gpios = < &arduino_header 0xe 0x0 >; /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:18 */
				wifi-max-tx-pwr-2g-dsss = < 0x15 >;              /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:21 */
				wifi-max-tx-pwr-2g-mcs0 = < 0x10 >;              /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:22 */
				wifi-max-tx-pwr-2g-mcs7 = < 0x10 >;              /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:23 */
				wifi-max-tx-pwr-5g-low-mcs0 = < 0xd >;           /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common_5g.dtsi:7 */
				wifi-max-tx-pwr-5g-low-mcs7 = < 0xd >;           /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common_5g.dtsi:8 */
				wifi-max-tx-pwr-5g-mid-mcs0 = < 0xd >;           /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common_5g.dtsi:9 */
				wifi-max-tx-pwr-5g-mid-mcs7 = < 0xd >;           /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common_5g.dtsi:10 */
				wifi-max-tx-pwr-5g-high-mcs0 = < 0xc >;          /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common_5g.dtsi:11 */
				wifi-max-tx-pwr-5g-high-mcs7 = < 0xc >;          /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common_5g.dtsi:12 */

				/* node '/soc/spi@40114000/nrf7002-spi@0/wlan0' defined in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:26 */
				wlan0: wlan0 {
					compatible = "nordic,wlan"; /* in zephyr/boards/shields/nrf7002ek/nrf7002ek_common.dtsi:27 */
				};
			};
		};
```

Delays do not appear correct:
image

Value written in the `configure` function:
```
CCR 00000030
TCR 00000007
```

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 20]
```diff
@@ -101,17 +122,193 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+	 * We most likely want to treat the requested delay as a minimum, since it
+	 * probably has to do with setup and hold times of some spi device.
+	 * So this algorithm is simple linear time algorithm that approaches the
+	 * desired value from above.
+	 */
+	do {
+		if (lpspi_calc_delay(prescaled_clock, delay_cycles) < desired_delay_ns) {
+			break;
+		}
+	} while (--delay_cycles >= 0);
```
Comment (pdgendt) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: There's an issue here if the `break` is done on the first iteration, where `+1` is done on top of `255U` resulting in a `uint8_t` overflow.

**Comment by pdgendt** [comment]
Another oddity is that some bytes appear to be missing a final clock pulse?

Sending `3f 01` & receiving 0 bytes:
image

Logs:
```
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_buffers_setup: tx_bufs 0x80053630 - rx_bufs 0 - 1
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_buffers_setup: current_tx 0x80053628 (1), current_rx 0 (0), tx buf/len 0x80053624/2, rx buf/len 0/0
[00:00:00.058,000] <wrn> spi_lpspi: CCR ffff00c6
[00:00:00.058,000] <wrn> spi_lpspi: TCR 08000007
[00:00:00.058,000] <dbg> spi_lpspi: transceive: Starting LPSPI transfer
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_fill_tx_fifo: Filled TX FIFO to 2 words (2 bytes)
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_update_tx: tx buf/len 0/0
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_handle_rx_irq: RX FIFO: 1, RX BUF: 0
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_handle_rx_irq: RX done 0 words to spi buf
```

Sending `2f 00 00 00 00 00` & receiving 6 bytes:
image

Logs:
```
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_buffers_setup: tx_bufs 0x80053610 - rx_bufs 0x80053620 - 1
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_buffers_setup: current_tx 0x80053608 (1), current_rx 0x80053618 (1), tx buf/len 0x800535f8/6, rx buf/len 0x80053600/6
[00:00:00.058,000] <dbg> spi_lpspi: transceive: Starting LPSPI transfer
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_fill_tx_fifo: Filled TX FIFO to 6 words (6 bytes)
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_update_tx: tx buf/len 0/0
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_handle_rx_irq: RX FIFO: 1, RX BUF: 0x80053600
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_update_rx: rx buf/len 0x80053601/5
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_update_rx: rx buf/len 0x80053603/3
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_update_rx: rx buf/len 0x80053604/2
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_handle_rx_irq: RX done 4 words to spi buf
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_fill_tx_fifo_nop: Filled TX fifo with 1 NOPs
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_handle_rx_irq: RX FIFO: 2, RX BUF: 0x80053604
[00:00:00.058,000] <dbg> spi_lpspi: spi_context_update_rx: rx buf/len 0/0
[00:00:00.058,000] <dbg> spi_lpspi: lpspi_handle_rx_irq: RX done 2 words to spi buf
```

Tested both on 8MHz and 1MHz

**Comment by pdgendt** [comment]
> Another oddity is that some bytes appear to be missing a final clock pulse?

This issue is "fixed" if `transfer-delay` is added to a sufficient high value (currently testing with 125).

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 20 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: there's no `uint8_t` in the function as far as I can see, what do you mean?

Comment (pdgendt) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: The return type? If you have a very large `desired_delay_ns`, the decrement is never done, and you do `return 256U;`.

**Comment by decsny** [comment]
@pdgendt the issue of the "missing clock pulse" is most likely I think a signal analyzer sampling rate issue, or maybe even a pinctrl issue, or both combined. I'm assuming that since you're using the RT1170 that the function clock frequency of the lpspi is actually extremely fast (probably something like 48 MHz i'm guessing is how you have it configured?) and the default transfer delay is 2 cycles of that, so you would need a sampling rate of probably a few hundred MHz to see it cleanly assuming the pad can even reach the low threshold in that time. And to be clear, the function clock which is used for the delays, is the one that is the source to the lpspi, not the SCK

**Comment by pdgendt** [comment]
> @pdgendt the issue of the "missing clock pulse" is most likely I think a signal analyzer sampling rate issue, or maybe even a pinctrl issue, or both combined. I'm assuming that since you're using the RT1170 that the function clock frequency of the lpspi is actually extremely fast (probably something like 48 MHz i'm guessing is how you have it configured?) and the default delay is 2 cycles of that, so you would need a sampling rate of probably a few hundred MHz to see it cleanly assuming the pad can even reach the low threshold in that time

The target device is an nRF7002, which has a max clock frequency of 8 MHz, but with the logic analyzer I set it to 1 MHz and sample at 40MS/s, so I don't think the analyzer is the issue.

Also note my previous comment that it works if I use a high enough `transfer-delay`, see (8 MHz):
image

**Comment by decsny** [comment]
As for your screenshot of the SCKPCS and PCSSCK, I'll see if I can find an RT1170 board and reproduce, that delay of 5 us should have been possible I would think. It looks like the algorithm should get a scaler of 239, so I'll see if it actually gets that or not on hardware.

**Comment by decsny** [comment]
> > @pdgendt the issue of the "missing clock pulse" is most likely I think a signal analyzer sampling rate issue, or maybe even a pinctrl issue, or both combined. I'm assuming that since you're using the RT1170 that the function clock frequency of the lpspi is actually extremely fast (probably something like 48 MHz i'm guessing is how you have it configured?) and the default delay is 2 cycles of that, so you would need a sampling rate of probably a few hundred MHz to see it cleanly assuming the pad can even reach the low threshold in that time
> 
> The target device is an nRF7002, which has a max clock frequency of 8 MHz, but with the logic analyzer I set it to 1 MHz and sample at 40MS/s, so I don't think the analyzer is the issue.
> 
> Also note my previous comment that it works if I use a high enough `transfer-delay`, see (8 MHz)

I'm not sure you're clear on what I'm saying. I did note that you found it "works" if you use a higher `transfer-delay`, which is the main reason that led me to say what I said. I'm saying the fact that the transfer delay is so short is making it look like it didn't happen due to the sampling resolution or could be not reaching low threshold due to pinctrl capability. 

The fact that you configured the max frequency of the spi device to be 1 MHz is irrelevant to what I'm saying. But, I saw from your screenshot that the frequency of your SCK was 1 MHz and you said CCR was written as 0x30, so that's how I calculated that your source clock frequency to LPSPI is probably around 48 MHz. Like I said, it's this source clock frequency, not the SCK frequency, that determines how the delays are calculated. So if transfer-delay is set to the default of 0, the driver will configure the absolute minimum delay, which is 2 cycles of the source clock, i.e. 41 ns, so you need triple digits of MS/s to see that pulse, probably at least 100 MS/s according to nyquist theorem.

**Comment by decsny** [comment]
@pdgendt thanks for your suggestion, [here is the diff](https://github.com/zephyrproject-rtos/zephyr/compare/f24b628169d20d813acad48c02dd60e5f2292738..528458d4c21765a32278d4416899411ff7013d92), please try when you get the chance.

**Comment by decsny** [comment]
What I just realized is that I have no idea why even do a looping algorithm at all, it's literally just a single unknown algebra equation, we can figure out the delays in O(1) time ??? updated PR

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 21]
```diff
@@ -101,17 +122,180 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+	 * probably has to do with setup and hold times of some spi device.
+	 */
+	uint16_t max_cycles = 255 + min_cycles;
+	uint64_t delay_cycles;
+
+	delay_cycles = (uint64_t)prescaled_clock * desired_delay_ns;
+	delay_cycles = DIV_ROUND_UP(delay_cycles, NSEC_PER_SEC);
+	delay_cycles = CLAMP(delay_cycles, min_cycles, max_cycles);
+
+	return delay_cycles - min_cycles;
```
Comment (pdgendt) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: Better safe than sorry?

```suggestion
	delay_cycles = CLAMP(delay_cycles, min_cycles, max_cycles);
	delay_cycles -= min_cycles;

	return MIN(delay_cycles, UINT8_MAX);
```

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 15 above)
Comment (pdgendt) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: Not changed yet?

**Review by pdgendt — COMMENTED** [review]
Thanks @decsny! The changes do make a lot of sense!

Will test them soon and report the results.

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 21 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: `max_cycles` = 255 + `min_cycles`

delay_cycles gets clamped already to high of `max_cycles`, so assuming that is the maximum then just reorder one term of the equation:

`max_cycles` - `min_cycles` = 255

so maximum value returned then would be 255

I won't fight too hard against making the change if you still think it's worthwhile but I think it's pretty obviously mathematically proveable that it won't be needed...

However, an argument could be made though that it could make the code above that more robust against someone changing it later erroneously. And it's negligible overhead to add that macro. What do you think

Comment (pdgendt) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: Yeah, it is somewhat straightforward, we can keep this version, maybe a comment for future readers?

Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: I have an idea actually to satisfy your concern without adding extra code, and maybe even remove some. I'll push it in a minute

**Comment by decsny** [comment]
@pdgendt I pushed a minor change for you to review based on the comments above, but at this time of the day in the week, I didn't test on hardware yet, I'll do it on monday

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 22]
```diff
@@ -101,17 +122,179 @@ static inline int lpspi_validate_xfer_args(const struct spi_config *spi_cfg)
...
+		 */
+		if (lpspi_calc_sck_freq(clock_freq, 0, prescaler) < best_freq) {
+			break;
+		}
+
+		/* the algorithm approaches the desired freq from below intentionally,
+		 * therefore the min is our previous best and the max is the desired.
+		 */
+		uint8_t new_div = lpspi_find_best_div_for_prescaler(clock_freq, prescaler,
+								   best_freq, desired_freq);
```
Comment (pdgendt) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c]: Nit
```suggestion
		uint8_t new_div = lpspi_find_best_div_for_prescaler(clock_freq, prescaler,
								    best_freq, desired_freq);
```

**Review by pdgendt — DISMISSED** [review]

**Comment by decsny** [comment]
just realized the sckdiv algorithm was completely unnecessary as well...

**Comment by pdgendt** [comment]
> just realized the sckdiv algorithm was completely unnecessary as well...

Great, will try it out tomorrow

**Review by pdgendt — APPROVED** [review]

**Review by EmilioCBen — APPROVED** [review]
LGTM! Great work!

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c [hunk 23]
```diff
@@ -60,12 +60,24 @@ static inline clock_ip_name_t lpspi_get_clock(LPSPI_Type *const base)
...
-	while (LPSPI_GetTxFifoCount(base) != 0) {
+	while (FIELD_GET(LPSPI_FSR_TXCOUNT_MASK, base->FSR) != 0) {
+		if (!limit_wait) {
+			continue;
+		}
+
+		if (arbitrary_cycle_limit-- < 0) {
+			LOG_WRN("Failed waiting for TX fifo empty");
+			return -EIO;
+		}
```
Comment (mmahadevan108) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:79]: Why not use `k_busy_wait()` here for maybe 1usec per iteration and use the Kconfig  to determine total the wait time in usec. This way the behavior will not vary by the processor speed.

Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:79]: It's supposed to vary by processor speed. It's just a number of attempts to try before quitting. It's simply a basic safety mechanism, which is just about being more safe than sorry, not a unique feature. It shouldn't even be needed. Most likely this consumption by the fifo happens immediately, and this loop isn't necessary. But people wanted to expand the scope of this PR, so here it is.  I'm not overcomplicating it any more by making it time -based based on CPU frequency calculations.

Also the specific suggestion to use k_busy_wait is not a good idea. That function is not isr safe. This function is called in isr context. k_busy_wait is implemented by polling kernel time, which can't increment due to this function would be blocking in isr context, causing a likely infinite loop in the kernel.

**Review by mmahadevan108 — APPROVED** [review]

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c (hunk 23 above)
Comment (teburd) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi_common.c:79]: If this is polling a register waiting for some truth expression with a timeout, WAIT_FOR is the appropriate tool. It uses cycles not ticks while accepting us timeouts. If you see any bugs in this do send fixes.

https://docs.zephyrproject.org/apidoc/latest/group__sys-util.html#ga68eb35df6b4715714312df90209accee
