### PR TITLE
drivers: usb: dc: stm32: don't invoke callbacks from ISR context

### LINKED ISSUE #61464: USB device stack (new and old) assertion on STM32
**Describe the bug**
When using the new and old USB device stack ECM class on STM32H7 the assertion is raised due to mutex usage within ISR.

**To Reproduce**
1. build USB device with ECM class for STM32 MCU with enabled asserts (_`CONFIG_ASSERT=y`_)
3. run against linux

**Expected behavior**
~The existing stack doesn't have this issue. Assuming the new stack shall not fail as well.~
It should work fine with `CONFIG_ASSERT=y`.

**Impact**
The new stack stops working.

**Logs and console output**
The "mutexes cannot be used inside ISRs" assertion happens within `udc_stm32_lock` that is called from `HAL_PCD_SetupStageCallback`.

```
#0  arch_system_halt (reason=4) at <workspace>/zephyr/kernel/fatal.c:32
#1  0x90077762 in k_sys_fatal_error_handler (reason=4, esf=0x240203a8 <z_interrupt_stacks+3496>) at <workspace>/zephyr/kernel/fatal.c:46
#2  0x90077988 in z_fatal_error (reason=4, esf=0x240203a8 <z_interrupt_stacks+3496>) at <workspace>/zephyr/kernel/fatal.c:131
#3  0x9008c3cc in z_arm_fatal_error (reason=4, esf=0x240203a8 <z_interrupt_stacks+3496>) at <workspace>/zephyr/arch/arm/core/aarch32/fatal.c:73
#4  0x9008c3ec in z_do_kernel_oops (esf=0x240203a8 <z_interrupt_stacks+3496>, callee_regs=0x2) at <workspace>/zephyr/arch/arm/core/aarch32/fatal.c:118
#5  0x90013e76 in _oops () at <workspace>/zephyr/arch/arm/core/aarch32\swap_helper.S:573
#6  <signal handler called>
#7  assert_post_action (file=0x900e0aa0 "WEST_TOPDIR/zephyr/kernel/mutex.c", line=101) at <workspace>/zephyr/lib/os/assert.c:44
#8  0x9007988a in z_impl_k_mutex_lock (mutex=0x240009ec <udc0_data+132>, timeout=...) at <workspace>/zephyr/kernel/mutex.c:101
#9  0x90098624 in k_mutex_lock (mutex=0x240009ec <udc0_data+132>, timeout=...) at <workspace>/<app>/zephyr/include/generated/syscalls/kernel.h:984
#10 0x900986a6 in udc_lock_internal (dev=0x900cb0d8 <__device_dts_ord_88>, timeout=...) at <workspace>/zephyr/drivers/usb/udc/udc_common.h:257
#11 0x90098704 in udc_stm32_lock (dev=0x900cb0d8 <__device_dts_ord_88>) at <workspace>/zephyr/drivers/usb/udc/udc_stm32.c:60
#12 0x90031564 in udc_ep_buf_alloc (dev=0x900cb0d8 <__device_dts_ord_88>, ep=0 '\000', size=8) at <workspace>/zephyr/drivers/usb/udc/udc_common.c:622
#13 0x90097ed8 in udc_ctrl_alloc (dev=0x900cb0d8 <__device_dts_ord_88>, ep=0 '\000', size=8) at <workspace>/zephyr/drivers/usb/udc/udc_common.c:646
#14 0x900322da in HAL_PCD_SetupStageCallback (hpcd=0x24003fa4 <udc0_priv>) at <workspace>/zephyr/drivers/usb/udc/udc_stm32.c:149
#15 0x900719f6 in PCD_EP_OutSetupPacket_int (hpcd=0x24003fa4 <udc0_priv>, epnum=0) at <workspace>/modules/hal/stm32/stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_pcd.c:2327
#16 0x900c3076 in HAL_PCD_IRQHandler (hpcd=0x24003fa4 <udc0_priv>) at <workspace>/modules/hal/stm32/stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_pcd.c:1140
#17 0x900988fa in udc_stm32_irq (dev=0x900cb0d8 <__device_dts_ord_88>) at <workspace>/zephyr/drivers/usb/udc/udc_stm32.c:361
#18 0x90013fc6 in _isr_wrapper () at <workspace>/zephyr/arch/arm/core/aarch32\isr_wrapper.S:264
```

**Environment:**
 - OS: irrelevant
 - Toolchain: gcc-arm-none-eabi-10.3-2021.07
 - Zephyr : [d9fe26](https://github.com/zephyrproject-rtos/zephyr/commit/d9fe261f8eae2ca8b999a35852024ecf2ec3dc2a)

Ping @loicpoulain

### PR DESCRIPTION
**Pull request by mathieuchopstm**
Modify driver to process interrupts from upper half ISR then signal a bottom half ISR thread which performs callback invokation. This ensures callbacks run in thread context which is necessary for proper operation of various classes.

Fixes #61464

### CODE REVIEW

File: drivers/usb/device/usb_dc_stm32.c [hunk 1]
```diff
@@ -184,23 +196,117 @@ struct usb_dc_stm32_ep_state {
...
+			. _status_field = _status,				\
+			.target = _target,					\
+		};								\
+										\
+		int _errcode = k_msgq_put(					\
+			&usb_dc_stm32_state.isr_msgq, &_msg, K_NO_WAIT);	\
+		if (_errcode != 0) {						\
+			LOG_ERR("k_msgq_put() failed: %d", _errcode);		\
+			__ASSERT_NO_MSG(0);					\
+		}								\
```
Comment (tmon-nordic) [inline drivers/usb/device/usb_dc_stm32.c:246]: While putting messages to message queue from ISR context, the code should be prepared to lose the message. I generally prefer different synchronization primitives, i.e. ones that do not depend on `K_NO_WAIT` call succeeding.

There is LOG_ERR(), so at least there will be some inidication for the user when things go south.

Considering this change is for the old stack, maybe it is not worth bullet-proofing this.

**Review by tmon-nordic — APPROVED** [review]

File: drivers/usb/device/usb_dc_stm32.c (hunk 1 above)
Comment (mathieuchopstm) [reply drivers/usb/device/usb_dc_stm32.c:246]: We have the same code in the UDC driver (except no `__ASSERT(0)`) and I've never seen messages being dropped... so unless I didn't have logs on and it did happen (? :sweat:), I think it should be *relatively* safe (especially as I doubled the default msgq size vs UDC).

**Review by erwango — APPROVED** [review]
