### PR TITLE
mgmt/mcumgr: Drop zephyr_ prefix from functions

### LINKED ISSUE #49962: RFC: Stable API Change:  SMP (Simple Management Protocol) transport API within MCUMgr drops zephyr_ prefix in functions and type definitions and drop zst parameter from zephyr_smp_transport_out_fn
## Introduction

The MCUMgr, which used to be external library, used to support multiple operating systems and required implementations of some functions to be provided by operating system it was linked to.
In case of Zephyr port of mcumgr, such functions, and type definitions, would have `zephyr_` prefix.
Since MCUMgr is now Zephyr subsystem, it seems redundant to have `zephyr_` prefix added, for example to SMP Transport API identifiers.
The proposal is to drop the `zephyr_` prefix.

The second part of proposal is to drop `zst ` parameter from `zephyr_smp_transport_out_fn` type, which is type for callback function which is called from inside of MCUMgr to pass `net_buf` type of buffer to a transport providing the callback.
This parameter is no longer needed as  it has never been used wit Zephyr, since we are able to carry transport information within `net_buf` itself.

### Problem description

Redundant prefix and a little bit confusing naming which may suggest that transport service for MCUMgr is provided by Zephyr, which is not true: a transport is registered directly to MCUMgr and transport is a client for Zephyr provided services (like drivers and other APIs).

### Proposed change

Remove the `zephyr_` prefix for transport. The `smp_transport` is enough to distinguish the API, `zephyr_` addition is redundant.
There is exception to naming which is `smp_reassembly`, but this is MCUMgr internal API and its usage out of MCUMgr makes no sense.

### Concerns and Unresolved Questions

User provided transport may require changes, the `zephyr_` prefixed functions have been deprecated but are left there to allow more fluent transition.
Removal of `zst` parameter from `zephyr_smp_transport_out_fn` function is less friendly and will just break user code, until removed.

### PR DESCRIPTION
**Pull request by de-nordic**
The MCUMgr library is now part of Zephyr, so there is no point
to prefix SMP functions with Zephyr.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

Closes: https://github.com/zephyrproject-rtos/zephyr/issues/49962

~~DNM until dependency https://github.com/zephyrproject-rtos/zephyr/pull/50904 is merged.~~

### CODE REVIEW

**Review by galak — DISMISSED** [review]
This is technically a breaking API change, so should go through the API change process: https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html

**Comment by de-nordic** [comment]
> This is technically a breaking API change, so should go through the API change process: https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html

OK, can follow that path, although nothing I have changed is available in public documentation, nor here https://docs.zephyrproject.org/latest/develop/api/overview.html.

**Comment by galak** [comment]
Please update release notes for deprecation.

**Comment by stephanosio** [comment]
Please rebase to fix CI failure

File: subsys/mgmt/mcumgr/smp.c [hunk 1]
```diff
@@ -116,57 +116,57 @@ zephyr_smp_split_frag(struct net_buf **nb, void *arg, uint16_t mtu)
...
-	zst = arg;
+	smpt = arg;
 	nb = rsp;
 
-	mtu = zst->zst_get_mtu(rsp);
+	mtu = smpt->get_mtu(rsp);
 	if (mtu == 0U) {
 		/* The transport cannot support a transmission right now. */
 		return MGMT_ERR_EUNKNOWN;
 	}
```
Comment (nordicjm) [inline subsys/mgmt/mcumgr/smp.c:160]: This code can go once the other PRs are merged

**Review by nordicjm — DISMISSED** [review]

File: include/zephyr/mgmt/mcumgr/smp.h [hunk 2]
```diff
@@ -13,23 +13,29 @@
...
  *
- * @param zst                   The transport to send via.
+ * @param smpt                  The transport to send via.
  * @param nb                    The net_buf to transmit.
  *
  * @return                      0 on success, MGMT_ERR_[...] code on failure.
  */
-typedef int zephyr_smp_transport_out_fn(struct zephyr_smp_transport *zst,
+typedef int smp_transport_out_fn(struct smp_transport *smpt,
 					struct net_buf *nb);
```
Comment (nordicjm) [inline include/zephyr/mgmt/mcumgr/smp.h:31]: nit. alignment

File: subsys/mgmt/mcumgr/smp_uart.c [hunk 3]
```diff
@@ -91,7 +91,7 @@ static int smp_uart_init(const struct device *dev)
 {
 	ARG_UNUSED(dev);
 
-	zephyr_smp_transport_init(&smp_uart_transport, smp_uart_tx_pkt,
+	smp_transport_init(&smp_uart_transport, smp_uart_tx_pkt,
 				  smp_uart_get_mtu, NULL, NULL);
```
Comment (nordicjm) [inline subsys/mgmt/mcumgr/smp_uart.c:95]: nit. alignment

**Comment by carlescufi** [comment]
We agreed with @de-nordic to follow the [stable API change procedure](https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-incompatible-changes)

**Comment by nordicjm** [comment]
Needs rebase

File: doc/releases/release-notes-3.2.rst [hunk 4]
```diff
@@ -98,6 +98,49 @@ Deprecated in this release
 * Bluetooth mesh Configuration Client API prefixed with ``bt_mesh_cfg_``
   is deprecated in favor of a new API with prefix ``bt_mesh_cfg_cli_``.
 
+* MCUmgr subsystem, specifically the SMP transport API, is dropping `zephyr_`
+  prefix, deprecating prefixed functions and callback type definitions with the
+  prefix and replacing them with with prefix-less variants.
+  The :c:struct:`zephyr_smp_transport` type, representing transport object,
+  is now replaced with c:struct:`smp_transport`, and the later one is used,
```
Comment (nordicjm) [inline doc/releases/release-notes-3.2.rst:105]:
```suggestion
  is now replaced with :c:struct:`smp_transport`, and the later one is used,
```

File: doc/releases/release-notes-3.2.rst [hunk 5]
```diff
@@ -98,6 +98,49 @@ Deprecated in this release
...
+
+  Deprecated functions and their replacements:
+
+  .. table::
+     :align: center
+
+     +-------------------------------------+---------------------------------------+
+     | Deprecated                          | Drop in replacement                   |
+     +=====================================+=======================================+
+     | :C:func:`zephyr_smp_transport_init` | :c:func:`smp_transport_init`          |
```
Comment (nordicjm) [inline doc/releases/release-notes-3.2.rst:116]: Not sure if C vs c makes a difference here but rest are lowercase

File: doc/releases/release-notes-3.2.rst [hunk 6]
```diff
@@ -98,6 +98,49 @@ Deprecated in this release
...
+
+  Deprecated callback types and their replacements:
+
+  .. table::
+     :align: center
+
+     +---------------------------------------------+---------------------------------------+
+     | Deprecated                                  | Drop in replacement                   |
+     +=============================================+=======================================+
+     | :C:func:`zephyr_smp_transport_out_fn`       | :c:func:`smp_transport_out_fn`        |
```
Comment (nordicjm) [inline doc/releases/release-notes-3.2.rst:133]: As above

File: doc/releases/release-notes-3.2.rst [hunk 7]
```diff
@@ -98,6 +98,49 @@ Deprecated in this release
...
+     +---------------------------------------------+---------------------------------------+
+     | :c:func:`zephyr_smp_transport_get_mtu_fn`   | :C:func:`smp_transport_get_mtu_fn`    |
+     +---------------------------------------------+---------------------------------------+
+     | :C:func:`zephyr_smp_transport_ud_copy_fn`   | :c:func:`smp_transport_ud_copy_fn`    |
```
Comment (nordicjm) [inline doc/releases/release-notes-3.2.rst:137]: As above

**Comment by nordicjm** [comment]
@de-nordic needs rebase

File: subsys/mgmt/mcumgr/smp.c [hunk 8]
```diff
@@ -193,7 +187,7 @@ zephyr_smp_tx_rsp(struct smp_streamer *ns, void *rsp, void *arg)
  * Processes a single SMP packet and sends the corresponding response(s).
  */
 static int
-zephyr_smp_process_packet(struct zephyr_smp_transport *zst,
+smp_process_packet(struct smp_transport *smpt,
 			  struct net_buf *nb)
```
Comment (nordicjm) [inline subsys/mgmt/mcumgr/smp.c:191]: nit. alignment, can all go on one line

**Review by nordicjm — DISMISSED** [review]

**Comment by de-nordic** [comment]
> @de-nordic please fix the compliance issue

@carlescufi checkpatch wants me to do this
```
-                              zephyr_smp_transport_ud_free_fn *ud_free_func);
+                              zephyr_smp_transport_ud_free_fn * ud_free_func)
```
to correct "problem". Seems weird.

**Comment by gmarull** [comment]
> > @de-nordic please fix the compliance issue
> 
> @carlescufi checkpatch wants me to do this
> 
> ```
> -                              zephyr_smp_transport_ud_free_fn *ud_free_func);
> +                              zephyr_smp_transport_ud_free_fn * ud_free_func)
> ```
> 
> to correct "problem". Seems weird.

check `scripts/checkpatch/typedefsfile`, btw why isn't that typedef already a pointer?

File: include/zephyr/mgmt/mcumgr/smp.h [hunk 9]
```diff
@@ -98,17 +131,31 @@ struct zephyr_smp_transport {
...
  * @param get_mtu_func          The transport's get-MTU function.
  * @param ud_copy_func          The transport buffer user_data copy function.
  * @param ud_free_func          The transport buffer user_data free function.
  */
-void zephyr_smp_transport_init(struct zephyr_smp_transport *zst,
+void smp_transport_init(struct smp_transport *smpt,
+			       smp_transport_out_fn *output_func,
+			       smp_transport_get_mtu_fn *get_mtu_func,
+			       smp_transport_ud_copy_fn *ud_copy_func,
+			       smp_transport_ud_free_fn *ud_free_func);
```
Comment (nordicjm) [inline include/zephyr/mgmt/mcumgr/smp.h:144]: nit. alignment

File: subsys/mgmt/mcumgr/smp.c [hunk 10]
```diff
@@ -218,54 +211,54 @@ zephyr_smp_process_packet(struct zephyr_smp_transport *zst,
...
-zephyr_smp_transport_init(struct zephyr_smp_transport *zst,
-			  zephyr_smp_transport_out_fn *output_func,
-			  zephyr_smp_transport_get_mtu_fn *get_mtu_func,
-			  zephyr_smp_transport_ud_copy_fn *ud_copy_func,
-			  zephyr_smp_transport_ud_free_fn *ud_free_func)
+smp_transport_init(struct smp_transport *smpt,
+			  smp_transport_out_fn *output_func,
+			  smp_transport_get_mtu_fn *get_mtu_func,
+			  smp_transport_ud_copy_fn *ud_copy_func,
+			  smp_transport_ud_free_fn *ud_free_func)
```
Comment (nordicjm) [inline subsys/mgmt/mcumgr/smp.c:231]: nit. alignment

**Review by nordicjm — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Comment by de-nordic** [comment]
> check `scripts/checkpatch/typedefsfile`, btw why isn't that typedef already a pointer?

OK so I have no good reason not to fix the new definitions (the `smp_transport_`), but I do not want to touch the old `zephyr_smp_transport_` definitions which I am deprecating anyway.
@gmarull  Can the compliance issue be waved in this instance, as this has been triggered only because I have extended original declaration of `zephyr_smp_transport_init` to inline it, and actually just call `smp_transport_init`, and have it deprecated.

**Review by nordicjm — DISMISSED** [review]

**Comment by nordicjm** [comment]
@de-nordic needs rebase

**Review by nordicjm — CHANGES_REQUESTED** [review]
smp_dummy.c needs updates too

**Review by nordicjm — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Review by nvlsianpu — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@de-nordic we are in stabilization phase, should this be considered a bugfix or part of some deprecation we need to do for v3.2? Otherwise, can we wait for v3.3 or you want this to be discussed with the TSC for merging during stabilization?

**Comment by de-nordic** [comment]
> @de-nordic we are in stabilization phase, should this be considered a bugfix or part of some deprecation we need to do for v3.2? Otherwise, can we wait for v3.3 or you want this to be discussed with the TSC for merging during stabilization?

@fabiobaltieri  Lets postpone it and have it merged just after the 3.2 gets released; I think it will be more wise to introduce API change at the beginning of development cycle rather than just prior to release.

**Review by nvlsianpu — DISMISSED** [review]

**Review by nordicjm — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Comment by nordicjm** [comment]
@de-nordic please rebase

**Review by nvlsianpu — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]
