### PR TITLE
spi: stm32: initialise according to `zephyr,pm-device-runtime-auto`

### LINKED ISSUE #77196: drivers: spi: stm32: Broken device power management on SPI bus
With PR #72991, the SPI driver does not work with PM device + runtime features enabled.

The bug was reproduced on the STM32WL device.

Steps to reproduce:

1. In `samples/subsys/lorawan/class_a` add  `CONFIG_PM_DEVICE=y` and `CONFIG_PM_DEVICE_RUNTIME=y` to `prj.conf`.

2. Build the sample: `west build -b lora_e5_mini`

3. Debug the sample (`west debug`), set the breakpoint to the `main` function `b main`, and run the code.

4. The `main` function is never hit as it is stuck in the SPI driver (`spi_ll_stm32.c:878` - in `transceive` function).

When I reverted the commit `858e8c51f1f42abb0afe62a4d701e69b7a6bd2b1` from PR #72991, the sample works as expected even with the above PM device options enabled.

### PR DESCRIPTION
**Pull request by JordanYates**
Don't automatically enable device runtime PM on the SPI port just
because `PM_DEVICE_RUNTIME` is enabled. Require the user to explicitly
call `pm_device_runtime_enable` on the port, or add
`zephyr,pm-device-runtime-auto` to the devicetree node.

Through the usage of `pm_device_driver_init`, the default clock control
and pinctrl handling can all be contained in `spi_stm32_pm_action`.

### CODE REVIEW

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -1380,6 +1380,64 @@ static inline bool spi_stm32_is_subghzspi(const struct device *dev)
...
 }
 
+#ifdef CONFIG_PM_DEVICE
+static int spi_stm32_pm_action(const struct device *dev,
+			       enum pm_device_action action)
+{
+	const struct spi_stm32_config *config = dev->config;
+	const struct device *const clk = DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE);
+	int err;
+
```
Comment (etienne-lms) [inline drivers/spi/spi_ll_stm32.c:1407]: By the way, could you remove the extra empty line?

File: drivers/spi/spi_ll_stm32.c [hunk 2]
```diff
@@ -1380,6 +1380,64 @@ static inline bool spi_stm32_is_subghzspi(const struct device *dev)
...
+			err = pinctrl_apply_state(config->pcfg, PINCTRL_STATE_SLEEP);
+			if ((err < 0) && (err != -ENOENT)) {
+				/*
+				 * If returning -ENOENT, no pins where defined for sleep mode :
+				 * Do not output on console (might sleep already) when going to
+				 * sleep,
+				 * "SPI pinctrl sleep state not available"
+				 * and don't block PM suspend.
+				 * Else return the error.
+				 */
```
Comment (etienne-lms) [inline drivers/spi/spi_ll_stm32.c]: Also by the way, maybe simplify to:
 ```c
		if (!spi_stm32_is_subghzspi(dev)) {
			/* Move pins to optional sleep state if any */
			err = pinctrl_apply_state(config->pcfg, PINCTRL_STATE_SLEEP);
			if ((err < 0) && (err != -ENOENT)) {
				return err;
			}
		}

File: drivers/spi/spi_ll_stm32.c [hunk 3]
```diff
@@ -1380,25 +1380,44 @@ static inline bool spi_stm32_is_subghzspi(const struct device *dev)
...
+	const struct spi_stm32_config *config = dev->config;
+	int err;
+
+	if (spi_stm32_is_subghzspi(dev)) {
+		return 0;
+	}
+
+	/* Move pins to requested state */
+	err = pinctrl_apply_state(config->pcfg, id);
+	if ((err < 0) && (err != -ENOENT)) {
```
Comment (etienne-lms) [inline drivers/spi/spi_ll_stm32.c]: Support for the default (active) pinctrl is required, so `-ENOENT` is an error case when `id == PINCTRL_STATE_DEFAULT`. Suggestion:
```patch
 	err = pinctrl_apply_state(config->pcfg, id);
-	if ((err < 0) && (err != -ENOENT)) {
-		/* If returning -ENOENT, no pins where defined for sleep mode :
-		 * Do not output on console (might sleep already) when going to
-		 * sleep,
-		 * "SPI pinctrl sleep state not available"
-		 * and don't block PM suspend.
-		 * Else return the error.
-		 */
-		return err;
-	}
-	return 0;
+	/* Only default (active) pinctrl is required, others are optional*/
+	if (id != PINCTRL_STATE_DEFAULT && err != -ENOENT) {
+		err = 0;
+	}
+	return err;

File: drivers/spi/spi_ll_stm32.c [hunk 4]
```diff
@@ -1437,7 +1436,8 @@ static int spi_stm32_pm_action(const struct device *dev,
 			LOG_ERR("Could not disable SPI clock");
 			return err;
 		}
-
+		__fallthrough;
+	case PM_DEVICE_ACTION_TURN_ON:
```
[the remark this answers is not in the document]
Comment (etienne-lms) [reply drivers/spi/spi_ll_stm32.c:1431]: > (Another solution would be to factor out the pinctrl_apply_state to dedicated functions, and call them from both SUSPEND and TURN_ON, without falling through. This would also "hide" the !is_subghz and -ENOENT stuff... maybe cleaner)

In case clock driver supports PM, it will likely suspend/resume rather than switch on/off. In that scope, it would be better the SPI switches clocks off/on from its suspend/resume actions, rather than its off/on actions.


> Could use a comment, because seeing SUSPEND fall through into TURN_ON is unexpected.

I would be more in favor of this suggestion, known that `PM_DEVICE_ACTION_TURN_ON` is used to place the device in suspended state (implicitly from its off state) according to PM device documentation.

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (etienne-lms) [reply drivers/spi/spi_ll_stm32.c:1407]: My bad, addressed in to next commit.

File: drivers/spi/spi_ll_stm32.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (JordanYates) [reply drivers/spi/spi_ll_stm32.c:1431]: The code the comment originally referred to was updated.
There is no longer any fallthrough.

**Comment by JordanYates** [comment]
For review purposes, please ignore the first commit which only moves the PM function.
Comments should address the second commit.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
Fixes #77196. Thanks @JordanYates

**Review by mathieuchopstm — APPROVED** [review]
