### PR TITLE
Bug: drivers/clock_control: SAM PMC missing soc.h

### LINKED ISSUE #59136: clock_control_sam_pmc.c missing <soc.h>
**Describe the bug**
The source at `zephyr/drivers/clock_control/clock_control_sam_pmc.c` is not buildable if `CONFIG_ARM_MPU` is not enabled. This is because it requires the `<soc.h>` header, which is included indirectly somewhere in in the header `<zephyr/arch/cpu.h>`, only when `CONFIG_ARM_MPU` which is not the desired behavior.

**To Reproduce**
Build the hello_world sample for the target board `sam4e_xpro`,
`west build -p -b sam4e_xpro zephyr/samples/hello_world`
disabling the config `CONFIG_ARM_MPU=n` in `zephyr/boards/arm/sam4e_xpro/sam4e_xpro_defconfig`

**Expected behavior**
The clock_control driver should build regardless of the ARM_MPU features inclusion.

**Impact**
The driver does not build unless ARM_MPU is enabled, which is unexpected since there is no direct link between the two components, which results in a very cryptic build error when building for the sam family of chips.

**Logs and console output**
```
/home/private/Documents/trackunit/zephyr_rtc/zephyr/drivers/clock_control/clock_control_sam_pmc.c: In function 'atmel_sam_clock_control_get_rate':
/home/private/Documents/trackunit/zephyr_rtc/zephyr/drivers/clock_control/clock_control_sam_pmc.c:89:25: error: 'SOC_ATMEL_SAM_MCK_FREQ_HZ' undeclared (first use in this function)
   89 |                 *rate = SOC_ATMEL_SAM_MCK_FREQ_HZ;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Environment (please complete the following information):**
 - OS: Linux Debian
 - Toolchain Zephyr SDK
 - Commit SHA efe9111b215f81ee3dbb48b3825a0b0f91cb6083

**Cross reference**
A fix for this bug is found in this PR: #59135

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
The source clock_control_sam_pmc.c can not build without the symbol SOC_ATMEL_SAM_MCK_FREQ_HZ which is contained in soc.h

This bug only shows itself if CONFIG_ARM_MPU is not enabled, which probably includes soc.h through the <zephyr/arch/cpu.h> which is not desired behavior.

This commit adds the missing header, making the source build regardless of CONFIG_ARM_MPU.

Fixes #59136

### CODE REVIEW

**Review by henrikbrixandersen — DISMISSED** [review]

File: drivers/clock_control/clock_control_sam_pmc.c [hunk 1]
```diff
@@ -7,6 +7,7 @@
 #define DT_DRV_COMPAT atmel_sam_pmc
 
 #include <stdint.h>
+#include <soc.h>
```
Comment (gmarull) [inline drivers/clock_control/clock_control_sam_pmc.c:10]: nit: move it below zephyr includes

**Review by henrikbrixandersen — APPROVED** [review]

**Review by nandojve — APPROVED** [review]

**Review by attie-argentum — COMMENTED** [review]
LGTM

**Review by attie-argentum — APPROVED** [review]
