### PR TITLE
net: lib: sockets: tls: Improve socket address storage

### LINKED ISSUE #104948: net: lib: socket: tls: Potential out-of-bounds write in socket_op_vtable::connect
### Describe the bug

Creating a TLS socket with a `net_socklen_t addrlen` value larger than `sizeof(struct net_sockaddr)` (an opaque type), when the TLS session cache is enabled, results in a `memcpy` that reads and writes past an address memory stored in the TLS session cache.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pdgendt**
- Validate the socket address length before storing it in the TLS session cache
- Use `struct net_sockaddr_storage` for stack variables to store socket addresses

Related to https://github.com/zephyrproject-rtos/zephyr/issues/104845
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/104948

### CODE REVIEW

**Review by rlubos — APPROVED** [review]

File: subsys/net/lib/sockets/sockets_tls.c [hunk 1]
```diff
@@ -121,7 +121,7 @@ struct tls_session_cache {
 	int64_t timestamp;
 
 	/** Peer address. */
-	struct net_sockaddr peer_addr;
+	struct net_sockaddr_storage peer_addr;
```
Comment (pdgendt) [inline subsys/net/lib/sockets/sockets_tls.c:124]: This does maybe need an accompanied `net_socklen_t peer_addrlen`?

Comment (rlubos) [reply subsys/net/lib/sockets/sockets_tls.c:124]: Not necessarily needed as address comparison in `peer_addr_cmp()` is based on the address family anyway. Copying is not a problem here as we only copy from `struct net_sockaddr_storage` to `struct net_sockaddr_storage`.

**Review by jukkar — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
