### PR TITLE
drivers: can: mcan: fix handling of bus-off status events

### LINKED ISSUE #68953: drivers: can: mcan: wrong behavior on entering bus-off
**Describe the bug**
The Zephyr CAN controller API states that `can_tx_callback_t` TX callback functions should behave identically to `can_send()` when it comes to error handling. This includes being called with `-ENETUNREACH` if the CAN controller enters bus-off while the transmission is pending. The Bosch M_CAN does not behave this way. 

Furthermore, pending transmissions are not cancelled when entering bus-off, nor does the driver implement automatic bus-off recovery when `CONFIG_CAN_AUTO_BUS_OFF_RECOVERY` is enabled.

**To Reproduce**
1. Build and flash an application with the CAN shell enabled and `CONFIG_CAN_AUTO_BUS_OFF_RECOVERY=n`
2. Connect the CAN controller to another CAN node, but short CAN_H and CAN_L on the CAN transceiver to trigger a bus-off event.
3. Start the CAN controller using the CAN shell and queue a frame for transmission.
4. Show the current status of the CAN controller using the CAN shell and see that it entered bus-off but the frame transmission did not fail (still queued).
5. Remove the short between CAN_H and CAN_L
6. Manually recover the CAN controller from bus-off using the shell.
7. Notice that the pending frame, which should have been cancelled, is now transmitted

The above steps 1 to 5 can be repeated with `CONFIG_CAN_AUTO_BUS_OFF_RECOVERY=y` only to find out that the CAN controller does not automatically attempt to recover from the bus-off condition.

**Expected behavior**
The Bosch M_CAN should honor the CAN controller API contract.

**Impact**
No way of recovering from bus-off except for stopping and re-starting the CAN controller.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: f0fe6b8833c101d071a6d95b8a98cb0b0e6dd4e3

**Additional context**
Found while testing v3.6.0-rc2.

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Fix handling bus-off events in the Bosch M_CAN driver backend:
- Cancel all pending TX buffers when entering bus-off state
- Call all pending TX buffer callbacks with -ENETUNREACH when entering bus-off
- Automatically initiate bus-off recovery if CONFIG_CAN_AUTO_BUS_OFF_RECOVERY=y

Fixes: #68953

### CODE REVIEW

File: drivers/can/can_mcan.c [hunk 1]
```diff
@@ -426,16 +426,59 @@ int can_mcan_set_mode(const struct device *dev, can_mode_t mode)
...
+	}
+
+	if (state == CAN_STATE_BUS_OFF) {
+		/* Request all TX buffers to be cancelled */
+		err = can_mcan_write_reg(dev, CAN_MCAN_TXBCR, CAN_MCAN_TXBCR_CR);
+		if (err != 0) {
+			return;
+		}
+
+		/* Call all TX queue callbacks with -ENETUNCREACH */
```
Comment (martinjaeger) [inline drivers/can/can_mcan.c:454]:
```suggestion
		/* Call all TX queue callbacks with -ENETUNREACH */
```

Comment (henrikbrixandersen) [reply drivers/can/can_mcan.c]: Thank you. Fixed.

File: drivers/can/can_mcan.c [hunk 2]
```diff
@@ -426,16 +426,59 @@ int can_mcan_set_mode(const struct device *dev, can_mode_t mode)
...
+		/* Call all TX queue callbacks with -ENETUNREACH */
+		for (tx_idx = 0U; tx_idx < cbs->num_tx; tx_idx++) {
+			tx_cb = cbs->tx[tx_idx].function;
+
+			if (tx_cb != NULL) {
+				cbs->tx[tx_idx].function = NULL;
+				tx_cb(dev, -ENETUNREACH, cbs->tx[tx_idx].user_data);
+				k_sem_give(&data->tx_sem);
+			}
+		}
```
Comment (alexanderwachter) [inline drivers/can/can_mcan.c:463]: Can you put this in a separate function?

Comment (henrikbrixandersen) [reply drivers/can/can_mcan.c:463]: I could, but I'd rather avoid the overhead of calling yet another function.

**Review by martinjaeger — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by str4t0m — APPROVED** [review]
