### PR TITLE
usb: cdc_acm: re-trigger transfer for OUT endpoint on resume 

### LINKED ISSUE #26725: USB suspend-resume process is not properly handled
**Describe the bug**
The USB subsystem does not properly handle the suspend-resume process.

When a USB device is suspended, all on-going transfers are cancelled:

https://github.com/zephyrproject-rtos/zephyr/blob/0651688dd350851ab5e00265d1170f3f015e77c0/subsys/usb/usb_device.c#L1017-L1025

The CDC ACM device class implementation, for instance, does not restore the cancelled USB transfer upon the resume event and this results in the USB transfer remaining in cancelled state:

https://github.com/zephyrproject-rtos/zephyr/blob/0651688dd350851ab5e00265d1170f3f015e77c0/subsys/usb/class/cdc_acm.c#L437-L440

This causes the USB device to become unresponsive.

**To Reproduce**
1. Build and flash `samples/subsys/usb/cdc_acm`
2. Open the board USB device serial port and see that everything is echoed.
3. Close the board USB device serial port
3. Suspend the board USB device.
4. Resume the board USB device.
5. Open the board USB device serial port and see that the device does not echo anything back.

**Expected behavior**
USB endpoint transfers are in working state after device is resumed.

**Impact**
USB suspend-resume process does not work, and any attempt by the host to suspend the device will result in the device being unusable until the device is re-enumerated (and configured).

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.11.3
 - Commit SHA: cbb252adef08ba482b14ef2ab562baf879956c93

**Additional context**
Note that this issue is not specific to the CDC ACM device class; a quick glance over other device class implementations suggest that they will be affected by this issue as long as the USB transfers are cancelled when a suspend event is received.

Also note that the `USB_DC_DISCONNECTED` event is not implemented or, as far as I can tell, does not work on any platforms.

### PR DESCRIPTION
**Pull request by jfischer-no**
usb: cdc_acm: re-trigger transfer for OUT endpoint on resume

Transfers are cancelled on suspend event, OUT transfers
needs to be re-trigger on resume.
Rework event handling to filter out spurious resume
events and re-trigger transfer if previous event was
a suspend event.

_Fixes #26725 for CDC ACM class, other classes/functions have to be reviewed and fixed (if necessary) in subsequent PRs._

### CODE REVIEW

File: subsys/usb/class/cdc_acm.c [hunk 1]
```diff
@@ -425,18 +421,27 @@ static void cdc_acm_do_cb(struct cdc_acm_dev_data_t *dev_data,
...
 		LOG_INF("USB device configured");
 		break;
 	case USB_DC_DISCONNECTED:
 		LOG_INF("USB device disconnected");
 		cdc_acm_reset_port(dev_data);
+		dev_data->usb_status = status;
 		break;
 	case USB_DC_SUSPEND:
-		LOG_INF("USB device suspended");
+		LOG_INF("CDC ACM suspended");
```
Comment (emob-nordic) [inline subsys/usb/class/cdc_acm.c:433]: Just a minor note. Let's keep `USB device` or change to `CDC ACM` everywhere in `cdc_acm_do_cb`.

**Review by eobalski — APPROVED** [review]

File: subsys/usb/class/cdc_acm.c (hunk 1 above)
Comment (jfischer-phytec-iot) [reply subsys/usb/class/cdc_acm.c:433]: I would like to remove both USB device and CDC ACM because every log line is prefixed with `usb_cdc_acm: .... `

Comment (jfischer-phytec-iot) [reply subsys/usb/class/cdc_acm.c]: done

**Review by carlescufi — APPROVED** [review]
