### PR TITLE
tests: timer_api: Use busy slew threshold when checking remaining ticks 

### LINKED ISSUE #66075: kernel: timer: timer_api: kernel.timer fails
**Describe the bug**
The test `kernel.timer` fails.

Observed for `nrf52840dk_nrf52840`.

**To Reproduce**
1. have `nrf52840dk_nrf52840` connected
2. go to your zephyr dir
3. call `./scripts/twister -T tests/kernel/timer/timer_api -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.5.0-2427-g742de21eef24 ***
Running TESTSUITE timer_api
===================================================================
START - test_sleep_abs
PASS - test_sleep_abs in 0.004 seconds
===================================================================
START - test_time_conversions
PASS - test_time_conversions in 0.072 seconds
===================================================================
START - test_timeout_abs
PASS - test_timeout_abs in 0.001 seconds
===================================================================
START - test_timer_duration_period
PASS - test_timer_duration_period in 0.323 seconds
===================================================================
START - test_timer_expirefn_null
PASS - test_timer_expirefn_null in 0.323 seconds
===================================================================
START - test_timer_k_define
PASS - test_timer_k_define in 0.695 seconds
===================================================================
START - test_timer_period_0
PASS - test_timer_period_0 in 0.200 seconds
===================================================================
START - test_timer_period_k_forever
PASS - test_timer_period_k_forever in 0.200 seconds
===================================================================
START - test_timer_periodicity
PASS - test_timer_periodicity in 0.252 seconds
===================================================================
START - test_timer_remaining
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:727: timer_api_test_timer_remaining: ((int64_t)exp_ticks - (int64_t)now) <= (dur_ticks / 2) + 1 is false
FAIL - test_timer_remaining in 0.067 seconds
===================================================================
START - test_timer_restart
PASS - test_timer_restart in 0.274 seconds
===================================================================
START - test_timer_status_get
PASS - test_timer_status_get in 0.001 seconds
===================================================================
START - test_timer_status_get_anytime
PASS - test_timer_status_get_anytime in 0.323 seconds
===================================================================
START - test_timer_status_sync
PASS - test_timer_status_sync in 0.352 seconds
===================================================================
START - test_timer_user_data
PASS - test_timer_user_data in 0.301 seconds
===================================================================
TESTSUITE timer_api failed.
------ TESTSUITE SUMMARY START ------
SUITE FAIL -  93.33% [timer_api]: pass = 14, fail = 1, skip = 0, total = 15 duration = 3.388 seconds
- PASS - [timer_api.test_sleep_abs] duration = 0.004 seconds
- PASS - [timer_api.test_time_conversions] duration = 0.072 seconds
- PASS - [timer_api.test_timeout_abs] duration = 0.001 seconds
- PASS - [timer_api.test_timer_duration_period] duration = 0.323 seconds
- PASS - [timer_api.test_timer_expirefn_null] duration = 0.323 seconds
- PASS - [timer_api.test_timer_k_define] duration = 0.695 seconds
- PASS - [timer_api.test_timer_period_0] duration = 0.200 seconds
- PASS - [timer_api.test_timer_period_k_forever] duration = 0.200 seconds
- PASS - [timer_api.test_timer_periodicity] duration = 0.252 seconds
- FAIL - [timer_api.test_timer_remaining] duration = 0.067 seconds
- PASS - [timer_api.test_timer_restart] duration = 0.274 seconds
- PASS - [timer_api.test_timer_status_get] duration = 0.001 seconds
- PASS - [timer_api.test_timer_status_get_anytime] duration = 0.323 seconds
- PASS - [timer_api.test_timer_status_sync] duration = 0.352 seconds
- PASS - [timer_api.test_timer_user_data] duration = 0.301 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: 02dfea9105d81be9c49bdb753298d946
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.1
 - Commit SHA or Version used: zephyr-v3.5.0-2427-g742de21eef24

### PR DESCRIPTION
**Pull request by anangl**
On Nordic SoCs, the clock that drives the system timer and the one that is used in busy-waiting may be significantly skewed, so the test cases that compare durations derived from those two clocks need to take into
 account a proper threshold. After the `z_timeout_expires` function was
 corrected in 3d29c9fe546cd42554becee9dddcbe2e9e73d5cc, it turned out that the threshold was missing in one check and the related test case
 started to fail on nRF platforms. This patch adds that threshold there.

Fixes #66075.

On the occasion, the threshold calculation is corrected to prevent 32-bit integer overflows.

### CODE REVIEW

**Review by katgiadla — APPROVED** [review]
LGTM

**Review by npitre — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]

File: tests/kernel/timer/timer_api/src/main.c [hunk 1]
```diff
@@ -45,8 +45,8 @@ struct timer_data {
  * between the two clocks.  Produce a maximum error for a given
  * duration in microseconds.
  */
-#define BUSY_SLEW_THRESHOLD_TICKS(_us)				\
-	k_us_to_ticks_ceil32((_us) * BUSY_TICK_SLEW_PPM		\
+#define BUSY_SLEW_THRESHOLD_TICKS(_us)					\
+	k_us_to_ticks_ceil32((_us) * (uint64_t)BUSY_TICK_SLEW_PPM	\
```
Comment (andyross) [inline tests/kernel/timer/timer_api/src/main.c:49]: ... but clearly the overflow fix here is obviously correct.  No objections to this patch.

**Review by andyross — COMMENTED** [review]
So, I've been in this space and do know what's happening here: the device
has a instruction-counted busy wait implementation that is ultimately based on the CPU clock, which is an internal oscillator.  The tick timekeeping is provided by a counter running on a crystal.  And the former is less stable and will skew vs. the "real" timer by a bit.

But... that's still sort of a hardware bug.  Maybe it's one we decide is tolerable with reasonable workarounds.  But it's still the hardware not providing the right behavior for a standard Zephyr API.

I'm not a fan of relaxing test requirements for everyone just for the benefit of one platform.  Odds are that failures here in other platforms probably represent something that can be fixed, and we'd want them to fix it, which they won't if they don't notice it because the test was relaxed.

Can we rework this so that (1) the precision issues are expressed more rigorously (i.e. MAX_BUSY_VS_TIMER_SKEW_PPM or something like that, maybe even make it a kconfig), and (2) we set that specifically for nRF and not for everyone?

**Comment by nashif** [comment]
@anangl  can you rebase please?

**Comment by anangl** [comment]
> @anangl can you rebase please?

done
