### PR TITLE
drivers: spi: spi_ll_stm32: Fix uncleared MODF flag

### LINKED ISSUE #17363: SPI driver does not reset master mode fault on STM32
**Describe the bug**

The current implementation of the STM32 SPI driver does not reset MODF (master mode fault). This leads to the situation where, after starting a new transmission, the SPI chip select signal is active but the function never returns because the interrupts is never triggered.

https://github.com/zephyrproject-rtos/zephyr/blob/eb57607c7d761f076d9f4abd03b22e933a2898b2/drivers/spi/spi_ll_stm32.c#L52-L69

**To Reproduce**

Set up an SPI master with CS control. Build for an STM32 board/target.

```
static const spi_cs_control cs_ctrl = {
  .gpio_dev = device_get_binding(DT_ST_STM32_SPI_1_CS_GPIOS_CONTROLLER),
  .gpio_pin = DT_ST_STM32_SPI_1_CS_GPIOS_PIN,
  .delay = 0
};

static const spi_config spi_cfg = {
  .frequency = spi_clock_freq,
  .operation = SPI_OP_MODE_MASTER | SPI_TRANSFER_MSB | SPI_WORD_SET(8) | SPI_LINES_SINGLE,
  .cs        = &cs_ctrl
};
```

Continuously send data over SPI (in a thread/loop). Externally pull low and release the CS signal on your board. The SPI communication stops working.

**Expected behavior**

MODF does not lock up SPI communication. MODF, if being set by the controller, is reset by the driver.

**Additional context**

Fix:

```diff
diff --git a/drivers/spi/spi_ll_stm32.c b/drivers/spi/spi_ll_stm32.c
index 67ecb32336..ec8ec80c40 100644
--- a/drivers/spi/spi_ll_stm32.c
+++ b/drivers/spi/spi_ll_stm32.c
@@ -62,6 +62,11 @@ static int spi_stm32_get_err(SPI_TypeDef *spi)
 			LL_SPI_ClearFlag_OVR(spi);
 		}
 
+		/* MODF error must be explicitly cleared */
+		if (LL_SPI_IsActiveFlag_MODF(spi)) {
+			LL_SPI_ClearFlag_MODF(spi);
+		}
+
 		return -EIO;
 	}
```

### PR DESCRIPTION
**Pull request by yboutreux**
Clear raised MODF flag, if not done the flag stay set forever.
    
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/17363

### CODE REVIEW

**Comment by yboutreux** [comment]
@mrfuchs since the `BSY` flag is raised when `MODF` is raised, I placed the reset of the `MODF` flag when `LL_SPI_IsActiveFlag_BSY` is checked later in the program, instead of inside `spi_stm32_get_err`. This will ensure that the program don't get stuck in the 
`while (LL_SPI_IsActiveFlag_BSY(spi)) {}` loop.

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -193,7 +193,9 @@ static void spi_stm32_complete(struct spi_stm32_data *data, SPI_TypeDef *spi,
 
 	if (LL_SPI_GetMode(spi) == LL_SPI_MODE_MASTER) {
 		while (LL_SPI_IsActiveFlag_BSY(spi)) {
-			/* NOP */
+			if (LL_SPI_IsActiveFlag_MODF(spi)) {
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c]: Please add a comment directly in the code

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (yboutreux) [reply drivers/spi/spi_ll_stm32.c]: Done, thank you !

**Review by erwango — APPROVED** [review]

File: drivers/spi/spi_ll_stm32.c [hunk 2]
```diff
@@ -193,7 +193,12 @@ static void spi_stm32_complete(struct spi_stm32_data *data, SPI_TypeDef *spi,
 
 	if (LL_SPI_GetMode(spi) == LL_SPI_MODE_MASTER) {
 		while (LL_SPI_IsActiveFlag_BSY(spi)) {
-			/* NOP */
+			/* BSY flag is set when MODF is raised (but not only).
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c]: BSY but is cleared when MODF is raised.
So MODF clearing should be done out of while loop

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_ll_stm32.c (hunk 2 above)
Comment (yboutreux) [reply drivers/spi/spi_ll_stm32.c]: MODF clearance has been placed out of the loop, thank you !

File: drivers/spi/spi_ll_stm32.c [hunk 3]
```diff
@@ -196,6 +196,11 @@ static void spi_stm32_complete(struct spi_stm32_data *data, SPI_TypeDef *spi,
 			/* NOP */
 		}
 	}
+	/* BSY flag is set when MODF is raised (but not only).
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c]: "BSY flag is **cleared** when MODF is raised"
Also, put the comment end tag on the same line

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_ll_stm32.c (hunk 3 above)
Comment (yboutreux) [reply drivers/spi/spi_ll_stm32.c]: Done, thank you :)

**Review by erwango — APPROVED** [review]
