### PR TITLE
tests: skip arch_nop test for ARM platforms

### LINKED ISSUE #42666: test: kernel.common.misra: test failure on mimxrt595_evk_cm33 with test_nop
**Describe the bug**
kernel.common.misra test failure on mimxrt595_cm33_evk
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/common/src/irq_offload.c:199: test_nop: (diff > 0 is false)

**To Reproduce**
cd tests/kernel/common
1. mkdir build; cd build
2. cmake -DBOARD=mimxrt595_cm33_evk -- -DCONFIG_MISRA_SANE=y
3. make flash

**Expected behavior**
test PASS

**Impact**
arch_nop seems wrong

**Logs and console output**

```
*** Booting Zephyr OS build v3.0.0-rc2  (delayed boot 500ms) ***

    Running test suite common

    ===================================================================

    START - test_bootdelay

     PASS - test_bootdelay in 0.1 seconds

    ===================================================================

    START - test_irq_offload

     PASS - test_irq_offload in 0.1 seconds

    ===================================================================

    [******** Truncated '86' Lines Log ********]

    Testing bit array alloc and free with divisor 8

    Testing bit array alloc and free with divisor 16

    Testing bit array alloc and free with divisor 32

    Testing bit array alloc and free with divisor 64

    Testing bit array interval alloc and free

     PASS - test_bitarray_alloc_free in 0.146 seconds

    ===================================================================

    START - test_bitarray_region_set_clear

    Testing bit array region bit tests

    Testing bit array region bit manipulations

     PASS - test_bitarray_region_set_clear in 0.8 seconds

    ===================================================================

    START - test_printk

    22 113 10000 32768 40000 22

    p 112 -10000 -32768 -40000 -22

    0x1 0x01 0x0001 0x00000001 0x0000000000000001

    0x1 0x 1 0x   1 0x       1

    42 42 0042 00000042

    -42 -42 -042 -0000042

    42 42   42       42

    42 42 0042 00000042

    255     42    abcdef        42

    68719476735 -1 18446744073709551615 ffffffffffffffff

    0xcafebabe 0xbeef 0x2a

     PASS - test_printk in 0.32 seconds

    ===================================================================

    START - test_timeout_order

     PASS - test_timeout_order in 0.127 seconds

    ===================================================================

    START - test_clock_uptime

     PASS - test_clock_uptime in 0.13 seconds

    ===================================================================

    START - test_clock_cycle_32

     PASS - test_clock_cycle_32 in 0.3 seconds

    ===================================================================

    START - test_clock_cycle_64

     SKIP - test_clock_cycle_64 in 0.1 seconds

    ===================================================================

    START - test_version

     PASS - test_version in 0.1 seconds

    ===================================================================

    START - test_multilib

     PASS - test_multilib in 0.1 seconds

    ===================================================================

    START - test_thread_context

     PASS - test_thread_context in 0.31 seconds

    ===================================================================

    START - test_errno

     PASS - test_errno in 0.1 seconds

    ===================================================================

    START - test_ms_time_duration

     PASS - test_ms_time_duration in 0.182 seconds

    ===================================================================

    START - test_bounds_check_mitigation

     PASS - test_bounds_check_mitigation in 0.1 seconds

    ===================================================================

    START - test_nop

    time k_cycle_get_32() takes 13 cycles

    arch_nop() takes 0 cycles

    

        Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/common/src/irq_offload.c:199: test_nop: (diff > 0 is false)

    arch_nop() takes 0 cpu cycles

     FAIL - test_nop in 0.20 seconds

    ===================================================================

    START - test_ffs

     PASS - test_ffs in 0.1 seconds

    ===================================================================

    Test suite common failed.

    ===================================================================

    PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.0.0-rc2

### PR DESCRIPTION
**Pull request by mmahadevan108**
ARM does not the guarantee the timing effects of NOP Instruction on Cortex-M platforms. The ARMv6-M Architecture manual states the following:
No Operation does nothing. This instruction can be used for code alignment purposes.

NOTE: The timing effects of including a NOP instruction in code are not guaranteed. It can increase execution time, leave it unchanged, or even reduce it. NOP instructions are therefore not suitable for timing loops.

 A Similar statement can be found in the ARMv8-M Architecture Manual. Hence we skip this test.

Fixes #42666

Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

File: tests/kernel/common/src/irq_offload.c [hunk 1]
```diff
@@ -142,13 +142,20 @@ __no_optimization void test_nop(void)
...
+	 *
+	 * NOTE: The timing effects of including a NOP instruction
+	 * in code are not guaranteed. It can increase execution time,
+	 * leave it unchanged, or even reduce it. NOP instructions are
+	 * therefore not suitable for timing loops.
+	 *
+	 * A Similar statement can be found in the ARMv8-M Architecture Manual.
+	 * So we skip this test.
+	 */
+	ztest_test_skip();
```
Comment (stephanosio) [inline tests/kernel/common/src/irq_offload.c:158]: Since this is applicable to all ARM architecture variants (i.e. ARMv6/ARMv7/ARMv8, -A/-R/-M), we might as well just check for `defined(CONFIG_ARM) || defined(CONFIG_ARM64)`.

Also note that we already handle this for ARMv8-A below, so it would be good to expand on that.
https://github.com/zephyrproject-rtos/zephyr/blob/502ce2870fca78aa8da17d2cabf120230000ea4d/tests/kernel/common/src/irq_offload.c#L180-L181

**Review by stephanosio — CHANGES_REQUESTED** [review]

**Review by hakehuang — APPROVED** [review]

File: tests/kernel/common/src/irq_offload.c (hunk 1 above)
Comment (mmahadevan108) [reply tests/kernel/common/src/irq_offload.c]: @stephanosio I have updated the implementation. I have reused earlier macros `CONFIG_ARMV6_M_ARMV8_M_BASELINE` and `CONFIG_ARMV7_M_ARMV8_M_MAINLINE` and avoided increasing the scope of the platforms covered as I have not investigated all.

Comment (stephanosio) [reply tests/kernel/common/src/irq_offload.c]: This is universal to all ARM architecture variants.

Looking at the ["ARM Architecture Reference Manual ARMv7-A and ARMv7-R edition"](https://developer.arm.com/documentation/ddi0406/cb/Application-Level-Architecture/Instruction-Details/Alphabetical-list-of-instructions/NOP):

> The timing effects of including a NOP instruction in a program are not guaranteed. It can increase execution time, leave it unchanged, or even reduce it. Therefore, NOP instructions are not suitable for timing loops.

For ARMv8-R, "ARM Architecture Reference Manual Supplement for the ARMv8-R AArch32 architecture profile" states the behaviour of `NOP` instruction is unchanged from that of the ARMv8-A, and the ARMv8-A ISA manual states the same thing as the above.

We can safely say that it is incorrect for this test to rely on the NOP timing delay effect on any ARM family architecture variants, so please update it as suggested earlier; otherwise, this test will still be technically broken for the currently supported ARMv7-A, ARMv7-R and ARMv8-R variants.

Comment (povergoing) [reply tests/kernel/common/src/irq_offload.c]: I agreed with stephanosio that it is universal to all ARM archs. we can use `defined(CONFIG_ARM) || defined(CONFIG_ARM64)` for all ARM profiles. Or at least, `CONFIG_ARMV8_A ` can be replaced with `CONFIG_ARM64`

**Review by stephanosio — APPROVED** [review]

**Comment by nashif** [comment]
this test probably needs to be removed completely, not sure what is the value and what we are testing here. When we start ifdeffing for specific platforms and architectures with the goal of just achieving coverage, it becomes more of an overhead. The coverage can also be dealt with using tool specific exclusion comments.

**Review by povergoing — APPROVED** [review]
