### PR TITLE
sensors: Fix shell missing channel types

### LINKED ISSUE #73296: ICM42688 is not configurable from DTS and gyro does not work with sensor shell
**Describe the bug**

Please also mention any information which could help others to understand
the problem you're facing:
 - Using platform VMU_RT1170
 - Unable to set params for ICM42688 from dts (just overrides with fixed values at lowest settings that clip in most use cases): https://github.com/zephyrproject-rtos/zephyr/blob/68bd4da4c64ca0c19cee0334bee6496ec8cde2b9/drivers/sensor/tdk/icm42688/icm42688.c#L274-L286

Also sensor shell does not work properly for gyro:
Screenshot_from_2024-05-25_11-50-17

**To Reproduce**
1. Attempt to set sensor attributes with DTS for ICM42688
2. Test shaking and see it locks to 125 deg/sec (hard coded gyro FS)
3. Run sensor shell and see it does not output gyro 

**Expected behavior**
Sensor should be configurable and sensor shell should work for the gyro.

**Impact**
Makes sensor not work as expected.

### PR DESCRIPTION
**Pull request by teburd**
The shell tries to decode all channel types and sequential channel indexes. Unfortunately when swapping to channel specs we forgot to reset the channel index for the next channel type to look at.

Fixes #73296

### CODE REVIEW

**Comment by ycsin** [comment]
Does it work on https://github.com/zephyrproject-rtos/zephyr/pull/72972/commits/862833b38f1a6718e8dbb0d0f68ab50364b859d1 ?

Specifically, update the pytest to check if every channel has an output:

```python
def assert_lines_has(lines, expected):
    assert any([expected in line for line in lines]), 'expected response not found'

for channel in range(59):
    logger.info(f'channel {channel}')
    lines = shell.exec_command(f'sensor get sensor@0 {channel}')
    assert_lines_has(lines, f'channel type={channel}')
```

**Review by yperess — APPROVED** [review]

**Comment by teburd** [comment]
And right, shouldn’t have this issue with metadata about what channels a sensor has available (we don’t have this today)

File: drivers/sensor/sensor_shell.c [hunk 1]
```diff
@@ -518,10 +522,11 @@ void sensor_shell_processing_callback(int result, uint8_t *buf, uint32_t buf_len
 					   ch.chan_idx,
 					   data->shift, accumulator_buffer.count,
 					   PRIsensor_q31_data_arg(*data, 0));
-			}
+				}
```
Comment (ubieda) [inline drivers/sensor/sensor_shell.c:525]: Not sure about this indentation change. It makes sense to me the way it was before.

**Review by ubieda — APPROVED** [review]
It may not address all the issues, nevertheless, this is a legit fix. +1

**Review by bperseghetti — APPROVED** [review]

File: drivers/sensor/sensor_shell.c (hunk 1 above)
Comment (ycsin) [inline drivers/sensor/sensor_shell.c:525]: The previous indentation is weird but correct according to our clang-format

**Review by ycsin — DISMISSED** [review]
Tested on the `sensor_shell` sample:

```
uart:~$ sensor get sensor@0 0
channel type=3(accel_xyz) index=0 shift=0 num_samples=0 value=4294967295ns, (-0.000000, -0.000000, -0.000000)
uart:~$ sensor get sensor@0 1
uart:~$ sensor get sensor@0 2
uart:~$ sensor get sensor@0 3
channel type=3(accel_xyz) index=0 shift=2 num_samples=1 value=9220133425350000000ns, (3.000000, 3.000000, 3.000000)
uart:~$ sensor get sensor@0 4
channel type=7(gyro_xyz) index=0 shift=0 num_samples=0 value=4294967295ns, (-0.000000, -0.000000, -0.000000)
uart:~$ sensor get sensor@0 5
uart:~$ sensor get sensor@0 6
uart:~$ sensor get sensor@0 7
channel type=7(gyro_xyz) index=0 shift=3 num_samples=1 value=9220133425350000000ns, (7.000000, 7.000000, 7.000000)
uart:~$ sensor get sensor@0 8
channel type=11(magn_xyz) index=0 shift=0 num_samples=0 value=4294967295ns, (-0.000000, -0.000000, -0.000000)
uart:~$ sensor get sensor@0 9
uart:~$ sensor get sensor@0 10
uart:~$ sensor get sensor@0 11
channel type=11(magn_xyz) index=0 shift=4 num_samples=1 value=9220133425350000000ns, (11.000000, 11.000000, 11.000000)
```

removed #72840 from the link

**Review by MaureenHelm — APPROVED** [review]
