### PR TITLE
tests: portability: cmsis_rtos_v1: Fix systick test

### LINKED ISSUE #26626: tests/portability/cmsis_rtos_v1 failed on reel_board.
**To Reproduce**
1. west build -b reel_board -p auto  tests/portability/cmsis_rtos_v1
2. west flash
3. see error

**Logs and console output**
*** Booting Zephyr OS build zephyr-v2.3.0-720-gab3e778f47d8  ***
Running test suite test_cmsis_apis

START - test_kernel_start
PASS - test_kernel_start

**START - test_kernel_systick
Assertion failed at WEST_TOPDIR/zephyr/tests/portability/cmsis_rtos_v1/src/kernel_apis.c:68: test_kernel_systick: (diff <= max && diff >= min is false)
start 879 stop 33626 (diff 999359) wait 1000000
FAIL - test_kernel_systick**

START - test_thread_apis
PASS - test_thread_apis

START - test_thread_prio
PASS - test_thread_prio
...
START - test_signal_events_no_wait
PASS - test_signal_events_no_wait

START - test_signal_events_timeout
PASS - test_signal_events_timeout

START - test_signal_events_signalled
PASS - test_signal_events_signalled

START - test_signal_events_isr
PASS - test_signal_events_isr

Test suite test_cmsis_apis failed.

PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.4
 - Commit ID: ab3e778f4

### PR DESCRIPTION
**Pull request by nordic-krch**
Added missing perenthesis to TOLERANCE_PPC macro.

Fixes #26626 
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

File: tests/portability/cmsis_rtos_v1/src/kernel_apis.c [hunk 1]
```diff
@@ -19,7 +19,7 @@
  * Additionally, if RC is used for low frequency clock then it has 5% tolerance.
  */
 #define TOLERANCE_PPC \
-	1 + 8 + (IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC) ? 5 : 0)
+	(1 + 8 + (IS_ENABLED(CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC) ? 5 : 0))
```
Comment (anangl) [inline tests/portability/cmsis_rtos_v1/src/kernel_apis.c:22]: As a side note, the comment describing this macro does not explain this leading 1 which actually seems to be not needed (currently the used tolerance is 9 or 14%, from the comment I'd assume it would be 8 or 13%). Maybe this could be corrected on the occasion?

**Review by anangl — APPROVED** [review]

File: tests/portability/cmsis_rtos_v1/src/kernel_apis.c (hunk 1 above)
Comment (nordic-krch) [reply tests/portability/cmsis_rtos_v1/src/kernel_apis.c:23]: this 1 is a "base" to cover cpu processing in the test.
```
start_time = osKernelSysTick();
k_busy_wait(WAIT_TIME_US);
stop_time = osKernelSysTick();
```
I've added comment in the common section.

**Review by carlescufi — APPROVED** [review]
