### PR TITLE
drivers: serial: uart_ns16550: add missing isr locking

### LINKED ISSUE #23026: missing ISR locking in UART driver?
**Describe the bug**

When IO APIC working in fixed delivery mode to broadcast interrupts to all CPUs in SMP system, seems the UART may not work properly.

Running this app and will see that the console is not able to echo keyboard input.
$ west build -b qemu_x86_64 samples/subsys/console/echo/ && west build -t run

**To Reproduce**
1. Apply these commits:.
https://github.com/zephyrproject-rtos/zephyr/pull/22848/commits/3a447e65a68d59581dede00d402b2e534aac417f
https://github.com/zephyrproject-rtos/zephyr/pull/22848/commits/3ee41f80b55ebe766e2627286f270efc50ea878c

2. replace IOAPIC_LOWEST with IOAPIC_FIXED in drivers/interrupt_controller/intc_ioapic.c to make sure IO APIC is working in logical + fixed mode.

3. Run the test and it won't work.
$ west build -b qemu_x86_64 samples/subsys/console/echo/ && west build -t run

**Expected behavior**

Skip (2) and use IOAPIC_LOWEST to deliver IO APIC to one CPU only, and run the same test, the console will print whatever characters you input from keyboard.

This problem could be caused by UART driver doesn't have ISR locking, so that it will have problems if same interrupt is delivered to all CPUs.

### PR DESCRIPTION
**Pull request by jenmwms**
ISR locking was missing in the UART driver for x86_64. This PR adds a spinlock mechanism to interrupt related services in the driver.

Fixes #23026

### CODE REVIEW

File: drivers/serial/uart_ns16550.c [hunk 1]
```diff
@@ -251,6 +252,10 @@ BUILD_ASSERT_MSG(IS_ENABLED(CONFIG_PCIE), "NS16550(s) in DT need CONFIG_PCIE");
 #define OUTBYTE(x, d) OUTWORD(x, d)
 #endif
 
+#ifdef CONFIG_UART_INTERRUPT_DRIVEN
+	static struct k_spinlock lock;
```
Comment (andrewboie) [inline drivers/serial/uart_ns16550.c]: shouldn't this spinlock be per-device instead of global? I would really expect the lock to be a member of uart_ns16550_dev_data_t

Comment (jenmwms) [reply drivers/serial/uart_ns16550.c]: Yes, thank you! I'll update that.

**Comment by jenmwms** [comment]
The automated tests are passing, however the issue/bug #23026 is still observed with: 
`west build -b qemu_x86_64 samples/subsys/console/echo/ && west build -t run`

I'll keep it as WIP until it fixes the issue.

**Comment by jenmwms** [comment]
To reproduce the failed Shippable test - 
./scripts/sanitycheck --platform=qemu_x86_64 -T tests/drivers/ipm/

The test is successful before this patch, but fails with it. Trying to figure out why then I'll submit an update.

**Comment by jenmwms** [comment]
> To reproduce the failed Shippable test -
> ./scripts/sanitycheck --platform=qemu_x86_64 -T tests/drivers/ipm/
> 
> The test is successful before this patch, but fails with it. Trying to figure out why then I'll submit an update.

This 1 test is still failing, but moving out of Draft will get more eyes on it as a PR so we can get code review.

**Comment by nashif** [comment]
please do not put bug numbers in commit titles:

```
drivers: serial: uart: ns16550 add missing isr locking #23026
```

**Comment by galak** [comment]
hmm, something seems off about the baseline of this PR.

**Comment by jenmwms** [comment]
> hmm, something seems off about the baseline of this PR.

Oh wow, thanks. I'll look into this. Hmmm. 
I did a 'git commit --amend' to edit the title of my commit message and saved that. Then I fetched from upstream/master and rebased based on upstream master so my commit sat on top. Then I checked with sanitcycheck, it passed so I force pushed to my branch to update this.

**Comment by jenmwms** [comment]
@galak Ok, can you please take another look? I think I fixed it.

File: drivers/serial/uart_ns16550.c [hunk 2]
```diff
@@ -355,8 +362,12 @@ static int uart_ns16550_configure(struct device *dev,
 	}
 #endif
 
+	k_spin_unlock(&dev_data->lock, key);
```
Comment (dcpleung) [inline drivers/serial/uart_ns16550.c:365]: Instead of unlock->call->lock, you can rename `set_baud_rate()` to something like `set_baud_rate_unlocked()` which contains code without locking. Then add a "new" `set_baud_rate()` function which does locking, then call `set_baud_rate_unlocked()`, then unlock. So in here, `set_baud_rate_unlocked()` can be used, so there is no need to do unlock->call->lock.

**Review by dcpleung — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_ns16550.c [hunk 3]
```diff
@@ -309,6 +313,8 @@ static void set_baud_rate(struct device *dev, u32_t baud_rate)
 		OUTBYTE(LCR(dev), lcr_cache);
 
 		dev_data->uart_config.baudrate = baud_rate;
+
+		k_spin_unlock(&dev_data->lock, key);
```
[the remark this answers is not in the document]
Comment (pabigot) [reply drivers/serial/uart_ns16550.c:317]: I'd move it inside the block; it has no role outside.

File: drivers/serial/uart_ns16550.c [hunk 4]
```diff
@@ -320,6 +326,7 @@ static int uart_ns16550_configure(struct device *dev,
 
 	unsigned int old_level;     /* old interrupt lock level */
 	u8_t mdc = 0U;
+	k_spinlock_key_t key = k_spin_lock(&dev_data->lock);
```
[the remark this answers is not in the document]
Comment (pabigot) [reply drivers/serial/uart_ns16550.c:329]: Since there are multiple error return locations and all are within a locked region a cleaner (IMO) idiom would be something like:
```
int rv = 0;
// stuff here
key = k_spin_lock(&dev_data->lock);
// more stuff here
if (some_error_detected) {
  rv = -ENOTSUP;
  goto out;
}
// ....
out:
   k_spin_unlock(&dev_data->lock, key);

   return rv;
```

**Review by pabigot — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_ns16550.c (hunk 2 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:365]: That makes sense. I'll work that into the update soon. Thanks!

Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:365]: Can you please help me resolve this build error that I get with the above implementation? Since we would call `set_baud_rate_unlocked( )` here in `configure`, then the `set_baud_rate( )` would need to be called from an application to be considered used in code coverage. Please correct me if I'm wrong.
             warning: 'set_baud_rate' defined but not used [-Wunused-function]
      291 | static void set_baud_rate(struct device *dev, u32_t baud_rate)
FUNC_UNUSED was not recognized....

Comment (dcpleung) [reply drivers/serial/uart_ns16550.c:365]: I thought `set_baud_rate()` was a API function. However, since `set_baud_rate()` is only called with this file, there is no need to do spinlock within this function. Locking can be done in the caller, as it looks like those functions need to lock anyway.

Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:365]: Thanks, @dcpleung! You're right, `set_baud_rate()` is an API function, so it should be spinlocked, yeah? The only place it was being called in this file was in `configure`, but this convo considers replacing that call with the `set_baud_rate_unlocked()`.

Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:365]: also, sorry it's a build *warning* not error

Comment (dcpleung) [reply drivers/serial/uart_ns16550.c:365]: `set_baud_rate()` is only being called by `uart_ns16550_configure()` and `uart_ns16550_line_ctrl_set()`. It is not directly callable by app. So there is no need to lock inside `set_baud_rate()` as the other two callers need to lock anyway.

File: drivers/serial/uart_ns16550.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:329]: Thanks for catching that unlock, and I'm all for cleaner code. I'll update it.

[the remark this answers is not in the document]
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:329]: fwiw At first I was a little unsure if we should use goto due to secure coding practice guidelines, but in this context looks like we are ok. At least according to MISRA-C which advises against the use of goto (Rule 15.1) but sets requirements if goto is put into use: 
Rule 15.2 (Required): The goto statement shall jump to a label declared later in the same function
Rule 15.3 (Required): Any label referenced by a goto statement shall be declared in the same block, or in any block enclosing the goto statement

File: drivers/serial/uart_ns16550.c (hunk 2 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:365]: Ok update here, I was mistaken about `set_baud_rate` is not an API function. It is not in uart.h, and it is also not assigned in the api structure in this driver `static const struct uart_driver_api uart_ns16550_driver_api`.
So, no need to spinlock within this function (as mentioned above) -- that means we do not need to  use `set_baud_rate_unlocked()`? Thanks for the help to figure this out!

**Comment by jenmwms** [comment]
Thanks for the help @dcpleung and @pabigot!

File: drivers/serial/uart_ns16550.c [hunk 5]
```diff
@@ -321,13 +323,19 @@ static int uart_ns16550_configure(struct device *dev,
 	unsigned int old_level;     /* old interrupt lock level */
```
Comment (pabigot) [inline drivers/serial/uart_ns16550.c:323]: This should be removed, along with the calls to `irq_lock()` and `irq_unlock()` which have been superseded by use of ths spin lock.

File: drivers/serial/uart_ns16550.c [hunk 6]
```diff
@@ -480,13 +497,18 @@ static int uart_ns16550_init(struct device *dev)
  */
 static int uart_ns16550_poll_in(struct device *dev, unsigned char *c)
 {
+	k_spinlock_key_t key = k_spin_lock(&DEV_DATA(dev)->lock);
+
```
Comment (pabigot) [inline drivers/serial/uart_ns16550.c:501]: This could be refactored to:
```
int rv = -1;
k_spinlock_key_t key = k_spin_lock(&DEV_DATA(dev)->lock);

if ((INBYTE(LSR(dev)) & LSR_RXRDY) != 0) {
    /* got a character */
￼   *c = INBYTE(RDR(dev)); 
    rv = 0;
}

k_spin_unlock(&DEV_DATA(dev)->lock, key);

return rv;
````

It's generally easier to pair up lock/unlock operations when they occur in pairs at the same depth.

Not a required change.

File: drivers/serial/uart_ns16550.c [hunk 7]
```diff
@@ -613,7 +668,18 @@ static int uart_ns16550_irq_tx_ready(struct device *dev)
  */
 static int uart_ns16550_irq_tx_complete(struct device *dev)
 {
-	return (INBYTE(LSR(dev)) & (LSR_TEMT | LSR_THRE)) == (LSR_TEMT | LSR_THRE);
+	k_spinlock_key_t key = k_spin_lock(&DEV_DATA(dev)->lock);
+	int check = 0;
+
+	if (
```
Comment (pabigot) [inline drivers/serial/uart_ns16550.c:674]: Personal opinion: this way of breaking up lines looks horrible, particularly the way the closing paren before the equality check is on a separate line from the opening paren, but also the bare opening paren following `if`.

Maybe this could be done instead, satisfying both the line length limit and MISRA's "ints aren't bools" rule.

```
int rv = ((INBYTE(LSR(dev)) & (LSR_TEMT | LSR_THRE))
          == (LSR_TEMT | LSR_THRE)) ? 1 : 0;
```

Several other functions below also could use a trinary expression to avoid using an `if` to override an initialized variable.

Not a required change.

**Review by pabigot — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_ns16550.c (hunk 5 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:323]: Thanks, I'll update this!

File: drivers/serial/uart_ns16550.c (hunk 6 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:501]: Awesome, thanks for the code suggestion and dev tips for spinlocks!

File: drivers/serial/uart_ns16550.c (hunk 7 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:674]: Wow, that helps clean it up a lot. Thanks!

**Review by dcpleung — APPROVED** [review]

**Review by pabigot — APPROVED** [review]
Untested, but looks good.  Shippable failure should not be related to this PR.

**Comment by pfalcon** [comment]
@jenmwms, thanks for investigation and this patch.

Earlier comment:

> the issue/bug #23026 is still observed with:
west build -b qemu_x86_64 samples/subsys/console/echo/ && west build -t run

Thanks for that earlier comment. Could you also provide a final summary of how you tested this patch. (For reference, ideal testing would include a real hardware system, then both `qemu_x86` and `qemu_x86_64`. I for one don't think I have access to real hw with 16550 now.)

**Comment by jenmwms** [comment]
> Could you also provide a final summary of how you tested this patch. (For reference, ideal testing would include a real hardware system, then both `qemu_x86` and `qemu_x86_64`

@pfalcon Thank you! I tested with the following:
1. samples/hello_world
2. tests/drivers/uart/uart_basic_api

for both `qemu_x86` and `qemu_x86`
using both `west` and `sanitycheck` as follows:
`west build -p -b qemu_x86 tests/drivers/uart/uart_basic_api`
`./scripts/sanitycheck -T tests/drivers/uart/uart_basic_api`

However, the `frdm_k64f` platform passes (1-hello_world) but *fails* (2-uart_basic_api) the .configure and .config_get tests in the uart_basic_api test suite. I'm looking into this. I have a FRDM-K64F for this.

**Comment by pfalcon** [comment]
> I tested with the following:
    samples/hello_world
    tests/drivers/uart/uart_basic_api

Nice, thanks. But #23026, which this PR fixes, talks about samples/subsys/console/echo/, was that re-tested too?

> for both qemu_x86 and qemu_x86

I assume "both qemu_x86 and qemu_x86_64".

> However, the frdm_k64f platform ...

Well, frdm_k64f doesn't use 16550 chip or driver, so it wouldn't be affected by this PR. I would say feel free to skip testing frdm_k64f. Or put better, if you have time to help investigate issues with frdm_k64f, that would be appreciated, but it would be a unrelated issue, and should be treated as such (a separate ticket, etc. If you'd file one, please @-mention me, as I have frdm_k64f and would be happy to help with review/testing.)

Also, to elaborate, why I'm asking - UART drivers appear to be worked on by different developers (including myself) intermittently (i.e. with big time gaps), and sadly, bugs may still be lurking. So, I think it's a nice idea to provide summary (like how exactly a final change as tested) to our future colleagues who may investigate further issues. Thanks again.

**Comment by pfalcon** [comment]
Ok, testing myself:

1. Zephyr master 6540f81f7ca2859d50a9c7d9b216ee5da04bd291 (today's)
a)
~~~
$ samples/subsys/console/echo
$ west build -b qemu_x86_64 -t run --pristine
...
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
*** Booting Zephyr OS build zephyr-v2.2.0-1276-g6540f81f7ca2  ***
You should see another line with instructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
~~~

As can be seen, expected (another) line is not printed, the sample doesn't react to keyboard input.

b)
~~~
$ west build -b qemu_x86 -t run --pristine
...
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
*** Booting Zephyr OS build zephyr-v2.2.0-1276-g6540f81f7ca2  ***
You should see another line with instructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
Start typing characters to see them echoed back
fmdlkasjf;wke
~~~

As can be seen, qemu_x86 behaves as expected, interrupt-driven output and input work.

2. Zephyr master 6540f81f7ca2859d50a9c7d9b216ee5da04bd291 + this PR (#23693):
a)
~~~
$ samples/subsys/console/echo
$ west build -b qemu_x86_64 -t run --pristine
...
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
*** Booting Zephyr OS build zephyr-v2.2.0-1277-g099719ebdfc4  ***
You should see another line with instructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
~~~

In other words, with this patch, qemu_x86_64 works the same as without it, which is "not working".

b)
~~~
$ west build -b qemu_x86 -t run --pristine
...
*** Booting Zephyr OS build zephyr-v2.2.0-1277-g099719ebdfc4  ***
You should see another line with instructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
Start typing characters to see them echoed back
dartgbsdgd
~~~

In other words, with this patch, qemu_x86 works the same as without it, which is "working as expected".



Now commentary: 16550 emulation in QEMU is known to have artifact, or better say, defects. Given that qemu_x86 is everyone's default testing target, I'm always on alert that some change may break interrupt-driven uart support in qemu_x86.

In this case, I don't see any improvements, but neither I see any regressions from my black-box testing. As I didn't review the patch in detail (I don't have resource for that now), I'd prefer to not give any vote, but existing approvals should be enough.

**Comment by pfalcon** [comment]
@jenmwms, So, the remaining issue here is broken build. If you click thru Shippable reports, you'll see that failure happened in `tests/drivers/ipm/drivers.ipc.mailbox`, which immediately can't be linked to changes in this PR, let's guess it was a random failure. So, need to restart the build, and current pattern for that is to close/reopen the PR, what I'm doing now.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
> In other words, with this patch, qemu_x86_64 works the same as without it, which is "not working".

There's a bug open on this, https://github.com/zephyrproject-rtos/zephyr/issues/23507

I did find that this seemed related to SMP, as setting the number of CPUs to 1 made the problem go away. But I don't know whether the concurrency issue is related to the driver. Since this patch doesn't fix it, possibly not.

**Comment by andrewboie** [comment]
In the latest CI run a test failed on x86_64 due to a stack overflow:

```
[0mSeaBIOS (version rel-1.12.1-0-ga5cab58-dirty-20200214_052440-f7294c49af13-zephyr
)
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
*** Booting Zephyr OS build zephyr-v2.2.0-1347-gca63d76446cb  ***
starting test - Test IPM
E: Page fault at address 0x11dff8 (error code 0x3)
E: Access violation: supervisor thread not allowed to write
E: PML4E: 0x000000000011a827 Writable, User, Execute Enabled
E: PDPTE: 0x0000000000119827 Writable, User, Execute Enabled
E:   PDE: 0x0000000000118827 Writable, User, Execute Enabled
E:   PTE: 0x800000000011d001 Read-only, Supervisor, Execute Disable
E: RAX: 0x0000000000108160 RBX: 0x000000000010023e RCX: 0x0000000000108771 RDX: 0x0000000000000010
E: RSI: 0x0000000000000069 RDI: 0x0000000000129190 RBP: 0x000000000011e09c RSP: 0x000000000011e000
E:  R8: 0x0000000000108770  R9: 0x0000000000000015 R10: 0x0000000000000000 R11: 0x0000000000000000
E: R12: 0x0000000000000069 R13: 0x000000000011e0b8 R14: 0x0000000000000000 R15: 0x0000000000000001
E: RSP: 0x000000000011e000 RFLAGS: 0x0000000000000216 CS: 0x0018 CR3: 0x000000000010a000
E: RIP: 0x00000000001034c7
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x000000000011b050 (unknown)
E: Halting system
```

**Comment by pfalcon** [comment]
> There's a bug open on this, #23507

Thanks.


> I did find that this seemed related to SMP, as setting the number of CPUs to 1 made the problem go away.

Per my previous comments, I wouldn't be totally surprised if it turned out to be QEMU emulation artifact (popping up in case of SMP). All in all, only running on the real hardware could tell. Which makes me wonder - even if 16550 are still embedded in south bridges or something of modern motherboards, in most PCs they're not broken out, so idea "just boot a suitable built zephyr.bin via GRUB" probably won't work...

**Comment by pfalcon** [comment]
> E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0

It's actually 2nd time in row, on the same test. @jenmwms, please rebase on the latest master, in case it might have been fixed in the meantime. But just in case, be prepared to bump stack size for that sample (and then extra points for actually trying to consider whether this patch could increase stack size requirements for interrupts or something).

**Comment by jenmwms** [comment]
> It's actually 2nd time in row, on the same test. @jenmwms, please rebase on the latest master, in case it might have been fixed in the meantime.

Indeed, that's the same 1 test that has been failing consistently for a couple weeks since I posted the draft and has remained through updates to the patch. I will rebase again and see if it has been resolved since my last update.

Also, please note  #23325 and mine are taking different approaches to address this issue. That patch configures UART interrupts as lowest priority delivery mode. In this one here we are adding spinlock mechanism to the UART driver. Using that patch yields successful samples/subsys/console/echo (test UART driver) on qemu_x86_64 (xapic, SP and SMP)

Perhaps it would be more accurate to say in this commit/PR that it partially fixes the issue - which really describes 2 problems: 1 is the missing locking mechanism; and 2 is the failing sample(s).

**Comment by jenmwms** [comment]
> Well, frdm_k64f doesn't use 16550 chip or driver,

My mistake, thank you. I now have an up2 board to test, I'll post results soon.

**Comment by jenmwms** [comment]
> Nice, thanks. But #23026, which this PR fixes, talks about samples/subsys/console/echo/, was that re-tested too?

That is an interesting one.  Alone, this PR will not resolve the failing sample. It does add locking mechanism. Please see my previous note to see #23325. We can use that PR with this one for testing, yes?

**Comment by jenmwms** [comment]
> but neither I see any regressions from my black-box testing.

@pfalcon Thanks so much for the help me improve testing this. 

Please see summary below at this time:

Test  (master)  (master + PR) : | Qemu_x86 | Qemu_x86_64 | Up_squared
-- | -- | -- | --
samples/hello_world | PASS     PASS | PASS     PASS | PASS     PASS
tests/drivers/uart/uart_basic_api  | PASS     FAIL* | FAIL     FAIL | FAIL     FAIL
samples/subsys/console/echo  | PASS   PASS | FAIL   FAIL | FAIL     FAIL

_samples/hello_world_

1. Zephyr master `ab15602`
    a. Qemu_x86
	```
        $ samples/hello_world
        $  west build -p -b qemu_x86 -t run
        …
        Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
        *** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
        Hello World! qemu_x86
	```
	As can be seen, qemu_x86 behaves as expected.

    b. Qemu_x86_64
	```
        $  west build -p -b qemu_x86_64 -t run
        …
        Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
        *** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
        Hello World! qemu_x86_64
	```
	As can be seen, qemu_x86_64 behaves as expected.
		
    c. Up_squared
	```
        $ west build -p -b up_squared
        …
        *** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
        Hello World! up_squared
	```
	As can be seen, up_squared behaves as expected.
		
2. Zephyr master `ab15602` + this PR (#23693)
    a. Qemu_x86
	```
        $ samples/hello_world
        $  west build -p -b qemu_x86 -t run
        …
        Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
        *** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
        Hello World! qemu_x86
	```
	As can be seen, qemu_x86 behaves as expected.
		
    b. Qemu_x86_64
	```
	$  west build -p -b qemu_x86_86 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
	*** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
	Hello World! qemu_x86_64
	```
	As can be seen, qemu_x86_64 behaves as expected.
		
    c. Up_squared
	```
	$ west build -p -b up_squared
	…
	*** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
	Hello World! up_squared
	```
	As can be seen, up_squared behaves as expected.

_tests/drivers/uart/uart_basic_api_
1. Zephyr master `ab15602`
    a. Qemu_x86
	```
	$ tests/drivers/uart/uart_basic_api
	$  west build -p -b qemu_x86 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
	*** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
	Running test suite uart_basic_test
	===================================================================
	starting test - test_uart_configure
	PASS - test_uart_configure
	===================================================================
	starting test - test_uart_config_get
	This is a configure_get test.
	PASS - test_uart_config_get
	===================================================================
	starting test - test_uart_fifo_fill
	This is a FIFO test.
	PASS - test_uart_fifo_fill
	===================================================================
	starting test - test_uart_fifo_read
	Please send characters to serial console
	PASS - test_uart_fifo_read
	===================================================================
	starting test - test_uart_poll_in
	Please send characters to serial console
	PASS - test_uart_poll_in
	===================================================================
	starting test - test_uart_poll_out
	This is a POLL test.
	PASS - test_uart_poll_out
	===================================================================
	Test suite uart_basic_test succeeded
	===================================================================
	PROJECT EXECUTION SUCCESSFUL
	```
	As can be seen, qemu_x86 behaves as expected and all test cases pass.

    b. Qemu_x86_64
	```	
	$  west build -p -b qemu_x86_64 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
	*** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
	Running test suite uart_basic_test
	===================================================================
	starting test - test_uart_configure
	PASS - test_uart_configure
	===================================================================
	starting test - test_uart_config_get
	This is a configure_get test.
	PASS - test_uart_config_get
	===================================================================
	starting test - test_uart_fifo_fill
	
	Assertion failed at ../src/test_uart_fifo.c:146: test_uart_fifo_fill: test_fifo_fill() == TC_PASS is false
		
	FAIL - test_uart_fifo_fill
	===================================================================
	starting test - test_uart_fifo_read
	Please send characters to serial console
	PASS - test_uart_fifo_read
	===================================================================
	starting test - test_uart_poll_in
	Please send characters to serial console
	PASS - test_uart_poll_in
	===================================================================
	starting test - test_uart_poll_out
	This is a POLL test.
	PASS - test_uart_poll_out
	===================================================================
	Test suite uart_basic_test failed.
	===================================================================
	PROJECT EXECUTION FAILED
	```
	As can be seen, qemu_x86_64 does *not* behave as expected. Assertion failed for FIFO fill test but subsequent test cases respond to keyboard and pass.

    c. Up_squared
	```
	$ west build -p -b up_squared
	…
	*** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
	Running test suite uart_basic_test
	===================================================================
	PASS - test_uart_configureconfigure
	===================================================================
	starting test - test_uart_config_get
	PASS - test_uart_config_gett.
	===================================================================
	starting test - test_uart_fifo_fill
		
	Assertion failed at ../src/test_uart_fifo.c:146: test_uart_fifo_fill: test_fifo_fill() == TC_PASS is false
		
	FAIL - test_uart_fifo_fill
	===================================================================
	starting test - test_uart_fifo_read
	Please send characters to serial console
	```	
	As can be seen, up_squared does *not* behave as expected. Assertion failed and the test does not react to keyboard input.

2. Zephyr master `ab15602` + this PR (#23693)
    a. Qemu_x86
	```
	$ tests/drivers/uart/uart_basic_api
	$  west build -p -b qemu_x86 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
	*** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
	Running test suite uart_basic_test
	===================================================================
	starting test - test_uart_configure
	PASS - test_uart_configure
	===================================================================
	starting test - test_uart_config_get
	This is a configure_get test.
	PASS - test_uart_config_get
	===================================================================
	starting test - test_uart_fifo_fill
	```	
	As can be seen, qemu_x86 does *not* behave as expected. The test does not react to keyboard input.

    b. Qemu_x86_64
	```
	$  west build -p -b qemu_x86_64 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
	*** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
	Running test suite uart_basic_test
	===================================================================
	starting test - test_uart_configure
	PASS - test_uart_configure
	===================================================================
	starting test - test_uart_config_get
	This is a configure_get test.
	PASS - test_uart_config_get
	===================================================================
	starting test - test_uart_fifo_fill
	```
	As can be seen, qemu_x86_64 does *not* behave as expected. The test does not react to keyboard input.

    c. Up_squared
	```
	$  west build -p -b up_squared
	…
	*** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
	Running test suite uart_basic_test
	===================================================================
	PASS - test_uart_configureconfigure
	===================================================================
	starting test - test_uart_config_get
	PASS - test_uart_config_gett.
	===================================================================
	starting test - test_uart_fifo_fill
	
	Assertion failed at ../src/test_uart_fifo.c:146: test_uart_fifo_fill: test_fifo_fill() == TC_PASS is false
	
	FAIL - test_uart_fifo_fill
	===================================================================
	starting test - test_uart_fifo_read
	Please send characters to serial console

	```	
	As can be seen, up_squared does *not* behave as expected. Assertion failed and the test does not react to keyboard input.

_samples/subsys/console/echo_
1. Zephyr master `ab15602`
    a. Qemu_x86
	```
	$ samples/subsys/console/echo
	$  west build -p -b qemu_x86 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
	*** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
	You should see another line with instructions below. If not,
	the (interrupt-driven) console device doesn't work as expected:
	Start typing characters to see them echoed back
	fdarfda
	```
	As can be seen, qemu_x86 behaves as expected.

    b. Qemu_x86_64
	```
	$  west build -p -b qemu_x86_64 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
	*** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
	You should see another line with instructions below. If not,
	the (interrupt-driven) console device doesn't work as expected:
	```
	Same as @pfalcon reported - As can be seen, qemu_x86_64 does *not* behave as expected - (another) line is not printed, the sample doesn't react to keyboard input.

    c. Up_squared
	```
	$  west build -p -b up_squared
	…
	*** Booting Zephyr OS build zephyr-v2.2.0-1364-gab15602b7964  ***
	You should see another line with instructions below. If not,
	the (interrupt-driven) console device doesn't work as expected:
	
	```
	As can be seen, up_squared does *not* behave as expected - (another) line is not printed, the sample doesn't react to keyboard input.

2. Zephyr master `ab15602` + this PR (#23693)
    a. Qemu_x86
	```
	$ samples/subsys/console/echo
	$  west build -p -b qemu_x86 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
	*** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
	You should see another line with instructions below. If not,
	the (interrupt-driven) console device doesn't work as expected:
	Start typing characters to see them echoed back
	fdafda
	
	```
	As can be seen, qemu_x86 behaves as expected.
		
    b. Qemu_x86_64
	```
	$  west build -p -b qemu_x86_64 -t run
	…
	Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
	*** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
	You should see another line with instructions below. If not,
	the (interrupt-driven) console device doesn't work as expected:
	
	```
	Same as @pfalcon reported - As can be seen, qemu_x86_64 does *not* behave as expected - (another) line is not printed, the sample doesn't react to keyboard input.

    c. Up_squared
	```
	$  west build -p -b up_squared
	…
	*** Booting Zephyr OS build zephyr-v2.2.0-1365-g3e55462d17c8  ***
	You should see another line with instructions below. If not,
	the (interrupt-driven) console device doesn't work as expected:
	
	```
	As can be seen, up_squared does *not* behave as expected - (another) line is not printed, the sample does not react to keyboard input.

The commentary: There is one scenario (`qemu_x86` `tests/drivers/uart/uart_basic_api`) which the test results are different from master to master + PR.  I'm not sure why yet. I'm also curious to try this with master + this PR + #23325 next...

**Comment by jenmwms** [comment]
Ah, this issue is still being resolved - #21156 "Interrupts do not work on UP Squared board". That could be impacting `tests/drivers/uart/uart_basic_api` and `samples/subsys/console/echo`...

**Review by andyross — APPROVED** [review]
Just realized I never gave this a +1, sorry

**Comment by jenmwms** [comment]
> Just realized I never gave this a +1, sorry

@andyross np thanks!

**Comment by pfalcon** [comment]
@jenmwms 

Re: https://github.com/zephyrproject-rtos/zephyr/pull/23693#issuecomment-611874206

Thanks for the detailed testing matrix!

> There is one scenario (qemu_x86 tests/drivers/uart/uart_basic_api) which the test results are different from master to master + PR. I'm not sure why yet.

Yes, I would find that worrying, would be nice to understand what's getting wrong.

**Comment by pfalcon** [comment]
On the separate matter, I tried to look into seemingly stable stack overflow in tests/drivers/ipm which happens with this PR in Shippable. So, I'm being hit by non-deterministic https://github.com/zephyrproject-rtos/zephyr/issues/12478, but in the end, with this PR, I can't reproduce stack overflow locally.

I still may suggest to adding a separate commit with:

~~~
--- a/tests/drivers/ipm/prj.conf
+++ b/tests/drivers/ipm/prj.conf
@@ -6,3 +6,4 @@ CONFIG_IPM_CONSOLE_RECEIVER=y
 CONFIG_IPM_CONSOLE_SENDER=y
 CONFIG_IRQ_OFFLOAD=y
 CONFIG_MP_NUM_CPUS=1
+CONFIG_MAIN_STACK_SIZE=2048
~~~

(If such a test commit helps, I'd suggest to use more modest stack size increase for the final version, e.g. 1088 (up 64 bytes from default 1K)).

**Comment by jenmwms** [comment]
> adding a separate commit with

@pfalcon That makes sense, thanks! Do you suggest I have a separate PR with that stack size commit? Then once it is merged, this PR should not experience the ipm test issue like before.

**Comment by pfalcon** [comment]
> Do you suggest I have a separate PR with that stack size commit? Then once it is merged, this PR should not experience the ipm test issue like before.

No, I suggest to just add that commit to this PR, and see if CI will pass. If so, play with the stack size increase (I'd suggest to limit it to +64 bytes, if that works), and call it done (i.e. have this PR merged).

If increasing stack size doesn't help, remove that commit, and continue investigation.

**Comment by jenmwms** [comment]
> if increasing stack size doesn't help, remove that commit, and continue investigation.

Increasing the stack size did not help. I was able to test locally before/after, with no apparent effect. I'll continue investigation

**Comment by jenmwms** [comment]
I tested today on master 7201c1d - No modification or cherry-pick.
Omitting hello_world tests this time:

Test (master) (master + PR) : | Qemu_x86 | Qemu_x86_64 | Up_squared
-- | -- | -- | --
tests/drivers/uart/uart_basic_api | PASS FAIL | PASS FAIL | PASS FAIL
samples/subsys/console/echo | PASS PASS | PASS FAIL | PASS PASS
tests/drivers/ipm | tbd  PASS | tbd FAIL | tbd PASS

1. tests/drivers/uart/uart_basic_api
Qemu_x86
Master + PR
```
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
*** Booting Zephyr OS build zephyr-v2.2.0-2727-g7b3bf498010d  ***
Running test suite uart_basic_test
===================================================================
starting test - test_uart_configure
PASS - test_uart_configure
===================================================================
starting test - test_uart_config_get
This is a configure_get test.
PASS - test_uart_config_get
===================================================================
starting test - test_uart_fifo_fill

```

Qemu_x86_64
Master + PR
```
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
*** Booting Zephyr OS build zephyr-v2.2.0-2727-g7b3bf498010d  ***
Running test suite uart_basic_test
===================================================================
starting test - test_uart_configure
PASS - test_uart_configure
===================================================================
starting test - test_uart_config_get
This is a configure_get test.
PASS - test_uart_config_get
===================================================================
starting test - test_uart_fifo_fill

```

Up_squared
Master + PR
```
*** Booting Zephyr OS build zephyr-v2.2.0-2727-g7b3bf498010d  ***
Running test suite uart_basic_test
===================================================================
PASS - test_uart_configureconfigure
===================================================================
starting test - test_uart_config_get
PASS - ▒est_uart_config_gett.
===================================================================
starting test - test_uart_fifo_fill
ASSERTION FAIL [z_spin_lock_valid(l)] @ ../include/spinlock.h:92

```
2. samples/subsys/console/echo 
Qemu_x86
Master + PR

```
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
*** Booting Zephyr OS build zephyr-v2.2.0-2727-g7b3bf498010d  ***
You should see another line with instructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
Start typing characters to see them echoed back
fdafda
```
Qemu_x86_64
Master + PR

```
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
*** Booting Zephyr OS build zephyr-v2.2.0-2727-g7b3bf498010d  ***
You should see another line with instructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
```

Up_squared
Master +  PR

```
*** Booting Zephyr OS build zephyr-v2.2.0-2726-g7201c1d6e983  ***
You should see another line with in{tructions below. If not,
the (interrupt-driven) console device doesn't work as expected:
Start typing characters to see them echoed back
Fdafda

```
3. tests/drivers/ipm/
Qemu_x86
Master + PR

```
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 7
*** Booting Zephyr OS build zephyr-v2.2.0-2727-g7b3bf498010d  ***
starting test - Test IPM
ipm_recv0: 'everything is awesome'
ipm_recv0: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor '
ipm_recv0: 'incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost'
ipm_recv0: 'rud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis '
ipm_recv0: 'aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugi'
ipm_recv0: 'at nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culp'
ipm_recv0: 'a qui officia deserunt mollit anim id est laborum.'
PASS - main
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

Qemu_x86_64
Master + PR

```
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
*** Booting Zephyr OS build zephyr-v2.2.0-2727-g7b3bf498010d  ***
starting test - Test IPM
E: Page fault at address 0x11dff8 (error code 0x3)
E: Access violation: supervisor thread not allowed to write
E: PML4E: 0x000000000011a827 Writable, User, Execute Enabled
E: PDPTE: 0x0000000000119827 Writable, User, Execute Enabled
E:   PDE: 0x0000000000118827 Writable, User, Execute Enabled
E:   PTE: 0x800000000011d001 Read-only, Supervisor, Execute Disable
E: RAX: 0x00000000001080c0 RBX: 0x000000000010019a RCX: 0x00000000001086d1 RDX: 0x0000000000000010
E: RSI: 0x0000000000000069 RDI: 0x0000000000129150 RBP: 0x000000000011e09c RSP: 0x000000000011e000
E:  R8: 0x00000000001086d0  R9: 0x0000000000000015 R10: 0x0000000000000000 R11: 0x0000000000000000
E: R12: 0x0000000000000069 R13: 0x000000000011e0b8 R14: 0x0000000000000000 R15: 0x0000000000000001
E: RSP: 0x000000000011e000 RFLAGS: 0x0000000000000216 CS: 0x0018 CR3: 0x000000000010a000
E: RIP: 0x00000000001035b7
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x000000000011b050 (unknown)
E: Halting system
FAILED: zephyr/CMakeFiles/run
cd /home/jennife2/zephyrproject/zephyr/build && /home/jennife2/zephyr-sdk-0.11.2/sysroots/x86_64-pokysdk-linux/usr/bin/qemu-system-x86_64 -m 9 -cpu qemu64,+x2apic -device isa-debug-exit,iobase=0xf4,iosize=0x04 -no-reboot -nographic -net none -pidfile qemu.pid -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -device loader,file=/home/jennife2/zephyrproject/zephyr/build/zephyr-qemu-main.elf -kernel /home/jennife2/zephyrproject/zephyr/build/zephyr-qemu-locore.elf
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /home/jennife2/bin/cmake/cmake-3.13.1-Linux-x86_64/bin/cmake --build /home/jennife2/zephyrproject/zephyr/build --target run
```
Up_squared
Master + PR

```
*** Booting Zephyr OS build zephyr-v2.2.0-2727-g7b3bf498010d  ***
starting test - Test IPM
ipm_recv0: 'everything is awesome'
ipm_recv0: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor '
ipm_recv0: 'incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost'
ipm_recv0: 'rud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis '
ipm_recv0: 'aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugi'
ipm_recv0: 'at nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culp'
ipm_recv0: 'a qui officia deserunt mollit anim id est laborum.'
PASS - main
===================================================================
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
Looks like shippable is still getting a stack overflow failure in the mailbox test:

```
[0mSeaBIOS (version rel-1.12.1-0-ga5cab58-dirty-20200214_052440-f7294c49af13-zephyr
)
Booting from ROM..Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 8
*** Booting Zephyr OS build v2.3.0-rc1-17-gac7fec1a8218  ***
starting test - Test IPM
E: Page fault at address 0x11dff8 (error code 0x3)
E: Access violation: supervisor thread not allowed to write
E: PML4E: 0x000000000011a827 Writable, User, Execute Enabled
E: PDPTE: 0x0000000000119827 Writable, User, Execute Enabled
E:   PDE: 0x0000000000118827 Writable, User, Execute Enabled
E:   PTE: 0x800000000011d001 Read-only, Supervisor, Execute Disable
E: RAX: 0x00000000001080c0 RBX: 0x000000000010019a RCX: 0x00000000001086d1 RDX: 0x0000000000000010
E: RSI: 0x0000000000000069 RDI: 0x0000000000129150 RBP: 0x000000000011e09c RSP: 0x000000000011e000
E:  R8: 0x00000000001086d0  R9: 0x0000000000000015 R10: 0x0000000000000000 R11: 0x0000000000000000
E: R12: 0x0000000000000069 R13: 0x000000000011e0b8 R14: 0x0000000000000000 R15: 0x0000000000000001
E: RSP: 0x000000000011e000 RFLAGS: 0x0000000000000216 CS: 0x0018 CR3: 0x000000000010a000
E: RIP: 0x00000000001035b7
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x000000000011b050 (unknown)
E: Halting system
```

This looks like a stack overflow, it's trying to write to a guard page at 0x11dff8 , notice the RSP is 0x000000000011e000 

It's probably one of the test threads, can you find out which thread is 0x000000000011b050 and kick up its stack space a bit? Are the stack sizes in the test adding CONFIG_TEST_EXTRA_STACKSIZE (or whatever it's called) to their stack sizes?

**Comment by jenmwms** [comment]
> can you find out which thread is 0x000000000011b050 and kick up its stack space a bit? Are the stack sizes in the test adding CONFIG_TEST_EXTRA_STACKSIZE (or whatever it's called) to their stack sizes?

Thanks for looking into it! I tried this in the past,
```
--- a/tests/drivers/ipm/prj.conf
+++ b/tests/drivers/ipm/prj.conf
@@ -6,3 +6,4 @@ CONFIG_IPM_CONSOLE_RECEIVER=y
 CONFIG_IPM_CONSOLE_SENDER=y
 CONFIG_IRQ_OFFLOAD=y
 CONFIG_MP_NUM_CPUS=1
+CONFIG_MAIN_STACK_SIZE=2048
```
but no effect. I'm not sure if it uses CONFIG_TEST_EXTRA_STACKSIZE, I'll take a look. Thanks for pointing that out.

**Comment by jenmwms** [comment]
I added CONFIG_IPM_CONSOLE_STACK_SIZE=2048 in `tests/drivers/ipm/prj.conf` and it passes now.

**Comment by jenmwms** [comment]
Still investigating why test_uart_fifo_fill is getting stuck on qemu_x86 , qemu_x86_64, and up_squared with this PR. Also, samples/subsys/console/echo for qemu_x86_64.

**Comment by carlescufi** [comment]
@jenmwms please let me know when this is ready to merge

File: drivers/serial/uart_ns16550.c [hunk 8]
```diff
@@ -733,10 +821,13 @@ static void uart_ns16550_isr(void *arg)
 {
 	struct device *dev = arg;
 	struct uart_ns16550_dev_data_t * const dev_data = DEV_DATA(dev);
+	k_spinlock_key_t key = k_spin_lock(&dev_data->lock);
```
Comment (nashif) [inline drivers/serial/uart_ns16550.c:824]: This one is causing `test_uart_fifo_fill` to fail

Comment (andyross) [reply drivers/serial/uart_ns16550.c:824]: Is it spinning with the lock held waiting on a full fifo to drain?  I bet it's spinning with the lock held waiting on a full fifo to drain.

Comment (andyross) [reply drivers/serial/uart_ns16550.c:824]: For clarity, because my joke wasn't as obvious (or funny) as it seemed when I wrote it: that would deadlock the ISR, which would be needed to wake up a reader to drain the fifo.

Comment (pfalcon) [reply drivers/serial/uart_ns16550.c:824]: > For clarity, because my joke wasn't as obvious (or funny) as it seemed ...

Fairly speaking, concerns like this were the reason why I popped up in this (and/or related) ticket. To be more precise, my concern that even seemingly working changes (e.g. tested on real hw) may still adversely affect qemu, which doesn't have too faithful 16550 emulation.

File: drivers/serial/uart_ns16550.c [hunk 9]
```diff
@@ -505,11 +521,15 @@ static int uart_ns16550_poll_in(struct device *dev, unsigned char *c)
 static void uart_ns16550_poll_out(struct device *dev,
 					   unsigned char c)
 {
+	k_spinlock_key_t key = k_spin_lock(&DEV_DATA(dev)->lock);
+
 	/* wait for transmitter to ready to accept a character */
 	while ((INBYTE(LSR(dev)) & LSR_THRE) == 0) {
```
Comment (andyross) [inline drivers/serial/uart_ns16550.c:527]: Relevant to the discussion earlier: this is a potential deadlock right here, though unlikely to be the source of the hang mentioned above.  This is going to spin with the lock held waiting for the hardware FIFO to drain.  But some uarts (at least in theory) have hardware implementations of flow control, which means that the device on the other side is capable of stalling the FIFO at will and causing a hang locally.

This while need to go outside a single block that does (atomically) "can I send a byte?  if so, send it and break out of the loop".   And it's probably good practice to put a busy wait of ~1 byte transfer time (87us at 115200bps) to avoid spamming the lock and/or banging the hardware too fast.

File: drivers/serial/uart_ns16550.c (hunk 8 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:824]: @nashif  Thanks for helping narrow this down! How did you figure it out? 
@andyross lol thanks. the `test_uart_fifo_fill` passes if I remove the locking here, cool. So now I need to figure out how to add it back without breaking things...

File: drivers/serial/uart_ns16550.c (hunk 9 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:527]: ah, wonderful. makes sense

Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:527]: That sounds similar to what's going on in https://github.com/zephyrproject-rtos/zephyr/pull/25064/files?  I tried that approach but did not resolve the hang. Still investigating

Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:527]: @andyross Interesting. There are a few functions that seem to fit this scenario...perhaps I need to make the same adjustment with a while loop outside a single block that does the checking/doing, yeah?  `uart_ns16550_poll_out`, `uart_ns16550_poll_in`, `uart_ns16550_fifo_fill`, and `uart_ns16550_fifo_read`

Comment (pfalcon) [reply drivers/serial/uart_ns16550.c:527]: @jenmwms: Mind that there's a huge difference between poll_out/poll_in vs fifo_fill/fifo_read. Please refer to the docstrings: https://github.com/zephyrproject-rtos/zephyr/blob/master/include/drivers/uart.h#L703 . To quote import points:

> This function is expected to be called from UART
> interrupt handler (ISR)

> Result of calling this function not from an ISR is undefined

> Likewise, *not* calling this function
> from an ISR if uart_irq_tx_ready() returns true may lead to
> undefined behavior

As pointed by @andyross, normally, one doesn't use locking in ISRs. Thus, a solution suitable for poll_out/poll_in, wouldn't be suitable for fifo_fill/fifo_read, and vice versa, solution for fifo_fill/fifo_read might be not the best for poll_out/poll_in.

Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:527]: @pfalcon Thanks for the info and link, it is helpful. I'll keep that in mind as I keep working on this.

Comment (andyross) [reply drivers/serial/uart_ns16550.c:527]: @jenmwms Almost always yes.  The point to a spinlock[1] is that it needs to enclose a critical section with firmly bounded runtime.  It's not like you can never use a "while" in there syntactically, but never in a circumstance where you aren't 100% sure exactly how long it will be until you unlock.

[1] In production code.  In the test suite we do all kinds of abusive things to locking paradigms to isolate stuff we want to test.

@pfalcon: You still need locking in ISRs, though the rules get more complicated.   Almost all Zephyr platforms support nested interrupts, so it's rarely actually true that you know you won't be interrupted.  And the driver in question is used on SMP systems, where you can have an interrupt racing against code on another CPU.

Comment (pfalcon) [reply drivers/serial/uart_ns16550.c:527]: @andyross, Right, someone *may* need locking in ISRs, and the rules for deal with those cases are complicated, so I didn't try to mention them in my comment.

**Comment by andyross** [comment]
Sorry, forgot this was in two places.  See comment at https://github.com/zephyrproject-rtos/zephyr/pull/25306#discussion_r426188664 

That's almost certainly where the deadlock is.

**Comment by carlescufi** [comment]
Tagged as DNM until you've had a chance to fix any unresolved issues.

**Review by nashif — CHANGES_REQUESTED** [review]
deadlocks on a few tests

File: drivers/serial/uart_ns16550.c [hunk 10]
```diff
@@ -463,10 +471,14 @@ static int uart_ns16550_init(struct device *dev)
 {
 	uart_ns16550_configure(dev, &DEV_DATA(dev)->uart_config);
 
+	k_spinlock_key_t key = k_spin_lock(&DEV_DATA(dev)->lock);
```
Comment (dcpleung) [inline drivers/serial/uart_ns16550.c:474]: That's no need to lock here. As `_init()` is called at boot before scheduler runs.

File: drivers/serial/uart_ns16550.c (hunk 8 above)
Comment (dcpleung) [reply drivers/serial/uart_ns16550.c:824]: As @andyross said, this lock can be removed. The callback are (supposedly) using the `poll_in()`, `poll_out()`, `fifo_read()` (etc., etc.) to read or write data. If a lock is held in `_isr()`, the read/write functions are waiting for lock to be released (and can't since they are called inside callback), resulting in deadlock.

**Review by dcpleung — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_ns16550.c (hunk 10 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:474]: great, thanks

**Comment by jenmwms** [comment]
> As @andyross said, this lock can be removed.
Thanks for your help! I thought that might be the case, but wasn't sure. I'll update it.

**Comment by jenmwms** [comment]
I incorporated the suggested changes, namely I removed the locking on the _isr() and _init(). I rebased to have the latest from master. And I tested with qemu_x86, qemu_x86_64, and up_squared using tests/drivers/uart/uart_basic_api.

Here is the result for up_squared:
image

**Comment by jenmwms** [comment]
This suggested edit still remains (but could be an enhancement in the interest of time?) from @andyross to implement:
>And it's probably good practice to put a busy wait of ~1 byte transfer time (87us at 115200bps) to avoid spamming the lock and/or banging the hardware too fast.

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by schouleu** [comment]
Hi,

Sorry to revive this discussion.

As explained by @andyross blocking all interrupts while waiting for the UART fifo to be empty is a very bad idea:

- Flow controlled UART can be waiting forever if the remote isn't ready
- UART is usually slow, waiting for 1 character to be flushed will spend 87us with interrupts masked, this is not acceptable in a RTOS.

I don't understand how this patch could be merged as-is. Plus I don't see the need to lock interrupts while waiting for the UART fifo to be empty.

```
        k_spinlock_key_t key = k_spin_lock(&DEV_DATA(dev)->lock);
	while (1) {
		/* wait for transmitter to ready to accept a character */
		if ((INBYTE(LSR(dev)) & LSR_THRE) == 0) {
			continue;
		}
		OUTBYTE(THR(dev), c);
		break;
	}
	k_spin_unlock(&DEV_DATA(dev)->lock, key);
```
