### PR TITLE
bluetooth: host: Use correct identity when direct advertising

### LINKED ISSUE #15526: Unhandled identity in bt_conn_create_slave_le
**Describe the bug**
See the following line in `bt_conn_create_slave_le`:
`conn = bt_conn_lookup_addr_le(BT_ID_DEFAULT, peer);`

Lookup is done on the default identity whereas connection can be done on some other identity.

**To Reproduce**
1. Create 2 identities. 
2. Advertise (directly) on second identity.
3. Connect to peer.
4. Advertise (directly) again on the same identity.
5. See that pending connection is ignored.

**Expected behavior**
Lookup should do check on the identity passed via parameters to the function.

**Impact**
Depending on the project. Can be a showstopper.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
ncs zephyr: `a288e8b8ab54c667c6ed9776042200411710a9cf` (from `06ab394` upstream)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pdunaj**
When starting direct advertising use correct identity during
connection lookup. Also unref connection when exiting with error.

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

Fixed: #15526

### CODE REVIEW

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -2043,6 +2043,7 @@ struct bt_conn *bt_conn_create_slave_le(const bt_addr_le_t *peer,
 			if (err && (err != -EALREADY)) {
 				BT_WARN("Directed advertising could not be"
 					" started: %d", err);
+				bt_conn_unref(conn);
```
Comment (jhedberg) [inline subsys/bluetooth/host/conn.c]: Even though these are small, one-line fixes, they're really independent issues and should therefore be in independent commits (can still be the same PR though), so please split these up. Note that I've added the 1.14 backport tag since I think these fixes are important enough to go to the LTS branch as well.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/conn.c (hunk 1 above)
Comment (pdunaj) [reply subsys/bluetooth/host/conn.c]: Commit split

**Review by jhedberg — APPROVED** [review]

**Comment by pdunaj** [comment]
Hi @Vudentz , @carlescufi , could we merge this and do the upmerge to ncs?

**Review by carlescufi — APPROVED** [review]
