### PR TITLE
Bluetooth: CSIP: Handle disconnects while in procedure

### LINKED ISSUE #80747: Bluetooth: CSIP: Assert when disconnecting during locking or releasing set
**Describe the bug**
The `bt_csip_set_coordinator_lock` and `bt_csip_set_coordinator_release` function performs a GATT write on one or more device. The state of the remote devices are checked at the beginning, but if one of the devices disconnect while the procedure is performed then `get_next_active_instance` in `csip_set_coordinator_write_lock_cb` or `csip_set_coordinator_write_release_cb` may give a service instance with a `NULL` `conn` pointer. The NULL pointer may then be provided to `bt_conn_index` causing an assert since `NULL` is not a valid pointer for that function. 

**To Reproduce**
N/A

**Expected behavior**
Expect the procedure to fail, but by calling `lock_set_complete` or `release_set_complete` with an error. 

**Impact**
Fatal error when asserts are enabled. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 193eeaef0c04570b80a954b58ccd98075150fb11

**Additional context**
Found during PTS testing

### PR DESCRIPTION
**Pull request by Thalley**
If a device disconnects while we are in a procedure then get_next_active_instance would return a service instance pointer with the `conn` set to NULL.

The issue was caused by the set_info being potentially memset
when the device that disconnected was the one that held the
set_info pointer.
The solution is to not use a pointer, but rather a copy of the
set_info, so that the active.set_info value is still valid
after a disconnect.
    
Since the set_info is not longer a pointer to a specific
set_info from one of the members, the logs have been updated
as well, as the pointer of the active.set_info is useless
for debugging.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/80747

### CODE REVIEW

**Review by asbjornsabo — DISMISSED** [review]
LGTM

**Review by kruithofa — DISMISSED** [review]

File: subsys/bluetooth/audio/csip_set_coordinator.c [hunk 1]
```diff
@@ -187,6 +187,9 @@ static struct bt_csip_set_coordinator_svc_inst *get_next_active_instance(void)
 	svc_inst =  lookup_instance_by_set_info(member, active.info);
 	if (svc_inst == NULL) {
 		LOG_DBG("Failed to lookup instance by set_info %p", active.info);
+	} else if (svc_inst->conn == NULL) {
+		LOG_DBG("Next service instance %p disconnected", svc_inst);
```
Comment (pin-zephyr) [inline subsys/bluetooth/audio/csip_set_coordinator.c:191]: in terms of commit message, it seems to happen when a device disconnects.

disconnected()  will reset the whole svc instance including set_info, I did not understand why svc_inst in line 187 is not NULL when device disconnects

Comment (Thalley) [reply subsys/bluetooth/audio/csip_set_coordinator.c:191]: That is a very good point. Will mark this as DNM until I've investigated. Thanks

**Comment by Thalley** [comment]
Refactored the solution. Found the root cause thanks to @pin-zephyr pointing out that this quick fix didn't solve it properly. 

Please re-review :)

**Review by pin-zephyr — APPROVED** [review]
LGTM

**Review by kruithofa — APPROVED** [review]
