### PR TITLE
Bluetooth: Audio: redone the base subgroup struct.

### LINKED ISSUE #68338: LE Audio: Broadcast Assistant API should not use `struct bt_bap_scan_delegator_subgroup`
**Describe the bug**
The `struct bt_bap_broadcast_assistant_add_src_param` and `struct bt_bap_broadcast_assistant_mod_src_param` use the `struct bt_bap_scan_delegator_subgroup` to provide subgroup information to the scan delegator. 

The issue is that the `struct bt_bap_scan_delegator_subgroup` depend on a Kconfig value that only exists for the Scan Delegator (guarded by `CONFIG_BT_BAP_SCAN_DELEGATOR`). 

**To Reproduce**
Build the sample from https://github.com/zephyrproject-rtos/zephyr/pull/68228 with `CONFIG_BT_BAP_SCAN_DELEGATOR=n`.

**Expected behavior**
The Broadcast Assistant API should be fully independent of the scan delegator. 
Either the struct needs to be redone to avoid a dependency on `CONFIG_BT_BAP_SCAN_DELEGATOR`, or the add/mod source parameters need their own way to describing subgroups. 

**Impact**
Annoyance as it requires enabling more features that should be necessary. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 19700040afb78e165eb0b988c55472b5e1c0b717

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pin-zephyr**
The struct bt_bap_broadcast_assistant_add_src_param and struct bt_bap_broadcast_assistant_mod_src_param use the struct bt_bap_scan_delegator_subgroup to provide subgroup information to the scan delegator. 

The issue is that the struct bt_bap_scan_delegator_subgroup depend on a Kconfig value that only exists for the Scan Delegator (guarded by CONFIG_BT_BAP_SCAN_DELEGATOR).

Therefore, make a general struct bt_bap_base_subgroup which can be used by scan delegator and broadcast assistant. 

Fixes #68338

### CODE REVIEW

File: include/zephyr/bluetooth/audio/bap.h [hunk 1]
```diff
@@ -296,7 +287,7 @@ struct bt_bap_scan_delegator_recv_state {
 	uint8_t num_subgroups;
 
 	/** Subgroup specific information */
-	struct bt_bap_scan_delegator_subgroup subgroups[BT_BAP_SCAN_DELEGATOR_MAX_SUBGROUPS];
+	struct bt_bap_base_subgroup subgroups[CONFIG_BT_BAP_BASE_MAX_SUBGROUPS];
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:290]: Ditto: `CONFIG_BT_BAP_BASE_MAX_SUBGROUPS` is too generic (and we have in fact just removed a similar Kconfig).

**Review by Thalley — CHANGES_REQUESTED** [review]

File: include/zephyr/bluetooth/audio/bap.h [hunk 2]
```diff
@@ -255,15 +246,15 @@ struct bt_bap_unicast_group;
...
+struct bt_bap_bass_subgroup {
 	/** BIS synced bitfield */
 	uint32_t bis_sync;
 
 	/** Length of the metadata */
 	uint8_t metadata_len;
 
 	/** The metadata */
-	uint8_t metadata[BT_BAP_SCAN_DELEGATOR_MAX_METADATA_LEN];
+	uint8_t metadata[CONFIG_BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE];
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:257]: Hmm, this file may actually be included when `CONFIG_BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE` is undefined. 

We may need to guard the `metadata` field with the Kconfig live we've done other places:
```c
struct bt_audio_codec_cap {
	/** Data path ID
	 *
	 * @ref BT_ISO_DATA_PATH_HCI for HCI path, or any other value for
	 * vendor specific ID.
	 */
	uint8_t path_id;
	/** Whether or not the local controller should transcode
	 *
	 * This effectively sets the coding format for the ISO data path to @ref
	 * BT_HCI_CODING_FORMAT_TRANSPARENT if false, else uses the @ref bt_audio_codec_cfg.id.
	 */
	bool ctlr_transcode;
	/** Codec ID */
	uint8_t id;
	/** Codec Company ID */
	uint16_t cid;
	/** Codec Company Vendor ID */
	uint16_t vid;
#if CONFIG_BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE > 0
	/** Codec Specific Capabilities Data count */
	size_t data_len;
	/** Codec Specific Capabilities Data */
	uint8_t data[CONFIG_BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE];
#endif /* CONFIG_BT_AUDIO_CODEC_CAP_MAX_DATA_SIZE > 0 */
#if defined(CONFIG_BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE)
	/** Codec Specific Capabilities Metadata count */
	size_t meta_len;
	/** Codec Specific Capabilities Metadata */
	uint8_t meta[CONFIG_BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE];
#endif /* CONFIG_BT_AUDIO_CODEC_CAP_MAX_METADATA_SIZE */
};
```

File: include/zephyr/bluetooth/audio/bap.h [hunk 3]
```diff
@@ -296,7 +287,7 @@ struct bt_bap_scan_delegator_recv_state {
 	uint8_t num_subgroups;
 
 	/** Subgroup specific information */
-	struct bt_bap_scan_delegator_subgroup subgroups[BT_BAP_SCAN_DELEGATOR_MAX_SUBGROUPS];
+	struct bt_bap_bass_subgroup subgroups[CONFIG_BT_BAP_BASS_MAX_SUBGROUPS];
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:290]: Ditto

File: include/zephyr/bluetooth/audio/bap.h [hunk 4]
```diff
@@ -391,7 +382,7 @@ struct bt_bap_scan_delegator_cb {
 	 */
 	int (*bis_sync_req)(struct bt_conn *conn,
 			    const struct bt_bap_scan_delegator_recv_state *recv_state,
-			    const uint32_t bis_sync_req[BT_BAP_SCAN_DELEGATOR_MAX_SUBGROUPS]);
+			    const uint32_t bis_sync_req[CONFIG_BT_BAP_BASS_MAX_SUBGROUPS]);
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:385]: What happens here if `CONFIG_BT_BAP_BASS_MAX_SUBGROUPS` is undefined?

File: include/zephyr/bluetooth/audio/bap.h [hunk 5]
```diff
@@ -1359,7 +1350,7 @@ int bt_bap_unicast_client_discover(struct bt_conn *conn, enum bt_audio_dir dir);
  */
 
 /** @brief Abstract Broadcast Audio Source Endpoint (BASE) subgroup structure. */
-struct bt_bap_base_subgroup;
+struct bt_bap_bass_subgroup;
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:1353]:
```suggestion
struct bt_bap_base_subgroup;
```

File: include/zephyr/bluetooth/audio/bap.h [hunk 6]
```diff
@@ -1436,7 +1427,7 @@ int bt_bap_base_get_bis_indexes(const struct bt_bap_base *base, uint32_t *bis_in
  * @retval 0 if all subgroups were iterated
  */
 int bt_bap_base_foreach_subgroup(const struct bt_bap_base *base,
-				 bool (*func)(const struct bt_bap_base_subgroup *subgroup,
+				 bool (*func)(const struct bt_bap_bass_subgroup *subgroup,
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:1430]: All the `bt_bap_base` parts need to be reverted to `bt_bap_base_subgroup`

File: samples/bluetooth/broadcast_audio_sink/Kconfig [hunk 7]
```diff
@@ -64,4 +64,18 @@ config TARGET_BROADCAST_CHANNEL
 	  Channel Audio Location to sync to. These corresponds to the bt_audio_location,
 	  supporting mono, left and right channels
 
+config BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE
+	int "BASE Subgroup Maximum Metadata Length"
+	default 32
+	range 0 255
+	help
+	  The maximum metadata length support by the BASS server.
```
Comment (Thalley) [inline samples/bluetooth/broadcast_audio_sink/Kconfig:72]: This already exists in `kconfig.bap`

File: samples/bluetooth/broadcast_audio_sink/Kconfig [hunk 8]
```diff
@@ -64,4 +64,18 @@ config TARGET_BROADCAST_CHANNEL
...
+
+config BT_BAP_BASS_MAX_SUBGROUPS
+	int "BASE Subgroup Maximum Number of Subgroups support"
+	default 1
+	range 0 31
+	help
+	  The maximum number of BIS subgroups supported.
```
Comment (Thalley) [inline samples/bluetooth/broadcast_audio_sink/Kconfig:79]: This should be defined in `kconfig.bap` instead of in this sample

File: samples/bluetooth/broadcast_audio_source/Kconfig [hunk 9]
```diff
@@ -38,4 +38,18 @@ config USE_USB_AUDIO_INPUT
...
+	range 0 255
+	help
+	  The maximum metadata length support by the BASS server.
+
+config BT_BAP_BASS_MAX_SUBGROUPS
+	int "BASE Subgroup Maximum Number of Subgroups support"
+	default 1
+	range 0 31
+	help
+	  The maximum number of BIS subgroups supported.
```
Comment (Thalley) [inline samples/bluetooth/broadcast_audio_source/Kconfig:53]: Ditto: These should be defined in `kconfig.bap` instead

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/Kconfig.bap [hunk 10]
```diff
@@ -53,6 +53,13 @@ config BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE
 	help
 	  Number of octets to support for Codec Specific Configuration metadata.
 
+config BT_BAP_BASS_MAX_SUBGROUPS
+	int "BASE Subgroup Maximum Number of Subgroups support"
+	default 1
+	range 0 31
```
Comment (Thalley) [inline subsys/bluetooth/audio/Kconfig.bap:59]:
```suggestion
	range 0 25
```

Due limitations in advertising data, the maximum size of a BASE is 253, the maximum size of all subgroups are 249 and the minimum size of a subgroup is 10 octets, so effectively there can be a maximum of 24 subgroups in a BASE
```suggestion
	range 0 24
```

File: subsys/bluetooth/audio/Kconfig.bap [hunk 11]
```diff
@@ -53,6 +53,13 @@ config BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE
...
+	help
+	  The maximum number of BIS subgroups supported.
```
Comment (Thalley) [inline subsys/bluetooth/audio/Kconfig.bap:61]:
```suggestion
	  The maximum number of subgroups supported.
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: include/zephyr/bluetooth/audio/bap.h [hunk 12]
```diff
@@ -255,15 +246,17 @@ struct bt_bap_unicast_group;
 struct bt_bap_ep;
 
 /** Struct to hold subgroup specific information for the receive state */
-struct bt_bap_scan_delegator_subgroup {
+struct bt_bap_base_subgroup {
```
[the remark this answers is not in the document]
Comment (pin-zephyr) [reply include/zephyr/bluetooth/audio/bap.h:249]: could you elabrate bit more?   are we gonna make 2 structures: struct bass and struct base to be the exactly same ?

[the remark this answers is not in the document]
Comment (Thalley) [reply include/zephyr/bluetooth/audio/bap.h:249]: They won't be the same :) 

The BASE in the advertising data has a structure like this:
image


i.e. a structure where there are 1 or more subgroups, with codec id, config data, meta data, and an array of BIS, each with BIS specific config data as well. 

For BASS the structure is much simpler:
image

Here we have an array of 1 or more subgroups, but without codec ID, config data, and the list of BIS indexes have been converted to a bitfield. 

`bt_bap_base_subgroup` represents the former, more complex version, and the `bt_bap_bass_subgroup` should represent the latter, simpler version.

File: include/zephyr/bluetooth/audio/bap.h [hunk 13]
```diff
@@ -367,7 +362,7 @@ struct bt_bap_scan_delegator_cb {
 	void (*broadcast_code)(struct bt_conn *conn,
 			       const struct bt_bap_scan_delegator_recv_state *recv_state,
 			       const uint8_t broadcast_code[BT_AUDIO_BROADCAST_CODE_SIZE]);
-
+#if defined(CONFIG_BT_BAP_BASS_MAX_SUBGROUPS)
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:365]: Since `CONFIG_BT_BAP_BASS_MAX_SUBGROUPS` cannot be `0`, do we need the guards? 

We have many other Kconfig options that are guarded by `CONFIG_BT_AUDIO` in this file, so I think it's OK to assume that `CONFIG_BT_BAP_BASS_MAX_SUBGROUPS` is always non-0, and we can remove all the guards for this value

**Review by Thalley — CHANGES_REQUESTED** [review]
LGTM, but I think we can remove some unnecessary guards

**Review by Thalley — APPROVED** [review]

**Review by fredrikdanebjer — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@Thalley Is this bug fix targeting v3.6.0? If so, please add it to the milestone.
