### PR TITLE
drivers: counter: Fix handling of relative alarms on nrf platform

### LINKED ISSUE #13255: tests/drivers/counter/counter_basic_api: Kernel panic and an assertion error when you run  test_multiple_alarms() after test_single_shot_alarm_top() failed
**Describe the bug**
If you run test_multiple_alarms() after test_single_shot_alarm_top() failed, test_multiple_alarms() will generate a assertion error and there will be a Kernel Panic.

Please take note that 
a. Running test_single_shot_alarm_top() by itself will fail with the same message you see in the console log section below. This is being filed as a separate bug https://github.com/zephyrproject-rtos/zephyr/issues/13254
b. Running test_multiple_alarms() alone by itself will result in a successful test, i.e. no failure recorded.
c. This bug is about what will happen if you run test_single_shot_alarm_top() followed by test_multiple_alarms()

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja  -DBOARD=nrf52_pca10040 -DARCH=arm #nrf52_pca10040
3. ninja
4. ninja run

Replace (2) with
cmake -GNinja -DBOARD=nrf51_pca10028 -DARCH=arm for nrf51_pca10028
cmake -GNinja -DBOARD=nrf52840_pca10056 -DARCH=arm for nrf52840_pca10056

**Screenshots or console output**
For nrf52_pca10040:
```
starting test - test_single_shot_alarm_top
    Assertion failed at /path/to/tests/zephyr.git/tests/drivers/counter/counter_basic_api/src/test_counter.c:196: test_single_shot_alarm_instance: (-EINVAL not equal to err)
Counter should return error because ticks exceeded the limit set alarm
FAIL - test_single_shot_alarm_top
===================================================================
starting test - test_multiple_alarms
ASSERTION FAIL [m_cb[p_instance->instance_id].state == NRFX_DRV_STATE_INITIALIZED] @ /path/to/tests/zephyr.git/ext/hal/nordic/nrfx/drivers/src/nrfx_ti
mer.c:134
[00:00:00.000,000] <dbg> counter_timer.4.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.3.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.2.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.1.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.0.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_rtc.0.init_rtc: Initialized
[00:00:00.000,000] <dbg> counter_rtc.2.init_rtc: Initialized
***** Kernel Panic! *****
Current thread ID = 0x200008c0
Faulting instruction address = 0x228a
```

For nrf51_pca10028:
```
===================================================================
starting test - test_single_shot_alarm_top
    Assertion failed at /path/to/tests/zephyr.git/tests/drivers/counter/counter_basic_api/src/test_counter.c:196: test_single_shot_alarm_instance: (-EINVAL not equal to err)
Counter should return error because ticks exceeded the limit set alarm
FAIL - test_single_shot_alarm_top
===================================================================
starting test - test_multiple_alarms
ASSERTION FAIL [m_cb[p_instance->instance_id].state == NRFX_DRV_STATE_INITIALIZED] @ /path/to/tests/zephyr.git/ext/hal/nordic/nrfx/drivers/src/nrfx_ti
mer.c:134
[00:00:00.000,000] <dbg> counter_timer.2.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.1.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.0.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_rtc.0.init_rtc: Initialized
***** Kernel Panic! *****
Current thread ID = 0x200001c0
Faulting instruction address = 0x2744
```

For nrf52840_pca10056:
```
starting test - test_single_shot_alarm_top
    Assertion failed at /path/to/tests/zephyr.git/tests/drivers/counter/counter_basic_api/src/test_counter.c:196: test_single_shot_alarm_instance: (-EINVAL not equal to err)
Counter should return error because ticks exceeded the limit set alarm
FAIL - test_single_shot_alarm_top
===================================================================
starting test - test_multiple_alarms
ASSERTION FAIL [m_cb[p_instance->instance_id].state == NRFX_DRV_STATE_INITIALIZED] @ /path/to/tests/zephyr.git/ext/hal/nordic/nrfx/drivers/src/nrfx_t
imer.c:134
[00:00:00.000,000] <dbg> counter_timer.4.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.3.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.2.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.1.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_timer.0.init_timer: Initialized
[00:00:00.000,000] <dbg> counter_rtc.0.init_rtc: Initialized
[00:00:00.000,000] <dbg> counter_rtc.2.init_rtc: Initialized
***** Kernel Panic! *****
Current thread ID = 0x200008c0
Faulting instruction address = 0x22aa
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain : zephyr 
 - Commit SHA or Version used: 012d40412568201f975dd0356e1e3fbf9e8aad73

**Additional context**

### PR DESCRIPTION
**Pull request by nordic-krch**
In case of relative alarm, nrf counter driver for TIMER peripheral
was not handling correctly case when new value exceeded top value.
Additionally, RTC implementation has been refactored to use similar
code for calculating alarm ticks.

Fixes #13255.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
LGTM, thanks

File: drivers/counter/counter_nrfx_timer.c [hunk 1]
```diff
@@ -90,8 +90,15 @@ static int counter_nrfx_set_alarm(struct device *dev, u8_t chan_id,
...
 
-	cc_val = alarm_cfg->ticks + (alarm_cfg->absolute ?
-				0 : nrfx_timer_capture(timer, COUNTER_READ_CC));
+	if (alarm_cfg->absolute) {
+		cc_val = alarm_cfg->ticks;
+	} else {
+		cc_val = alarm_cfg->ticks +
+				nrfx_timer_capture(timer, COUNTER_READ_CC);
+		cc_val -= (cc_val > counter_get_top_value(dev)) ?
+				counter_get_top_value(dev) : 0;
```
Comment (anangl) [inline drivers/counter/counter_nrfx_timer.c]: I am afraid it still may fail to set the proper compare value. Consider the following (contrived but still) scenario:
- top value is `0xFFFFFF00`
- `nrfx_timer_capture(timer, COUNTER_READ_CC)` returns `0xFFFFF100`
- an alarm with relative ticks of `0x1000` is requested

`cc_val` will be set to `0x100` then, while it should be `0x200`.

Maybe something like the code below could work?
```
u32_t remainder;
...
cc_val = nrfx_timer_capture(timer, COUNTER_READ_CC);
remainder = (counter_get_top_value(dev) - cc_val);
if (remainder > alarm_cfg->ticks) {
    cc_val += alarm_cfg->ticks;
} else {
    cc_val = alarm_cfg->ticks - remainder;
}
```

**Review by anangl — CHANGES_REQUESTED** [review]

File: drivers/counter/counter_nrfx_timer.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/counter/counter_nrfx_timer.c]: good catch. I've refactored the algorithm in `counter_nrfx_timer.c` to separate function.

Comment (anangl) [reply drivers/counter/counter_nrfx_timer.c]: > I've refactored the algorithm in `counter_nrfx_timer.c` to separate function.

Good. Shouldn't the RTC based implementation use a similar solution?

Comment (nordic-krch) [reply drivers/counter/counter_nrfx_timer.c]: it's 24bit so there is no risk so i left it but if you insist. I felt that first argument is more straight forward (but was failing due to 32 bit overflow).

Comment (anangl) [reply drivers/counter/counter_nrfx_timer.c]: Oh, right, the top value is 24-bit and the relative ticks value cannot be bigger than it. So there won't be a 32-bit overflow when these two are added. Maybe a short comment just stating that there is no risk of the overflow would be a good thing then?

**Review by anangl — APPROVED** [review]

File: drivers/counter/counter_nrfx_timer.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/counter/counter_nrfx_timer.c]: done
