### PR TITLE
Fix eatt mtu

### LINKED ISSUE #53475: The ATT_MTU value for EATT should be set as the minimum MTU of ATT Client and ATT Server
**Describe the bug**
BLUETOOTH CORE SPECIFICATION Version 5.3 | Vol 3, Part G page 1528
[GATT] 5.3 ENHANCED ATT BEARER L2CAP INTEROPERABILITY REQUIREMENTS
5.3.1 ATT_MTU
**The ATT_MTU for the Enhanced ATT bearer shall be set to the minimum of the
MTU field values of the two devices**; these values come from the L2CAP_CREDIT_BASED_CONNECTION_REQ and L2CAP_CREDIT_BASED_CONNECTION_RSP signaling packets or the latest L2CAP_CREDIT_BASED_RECONFIGURE_REQ packets.
Note: The minimum ATT_MTU for an Enhanced ATT bearer is 64 octets.

From the specification, we can see that ATT_MTU for EATT should be chosen as the  the minimum of the MTU of ATT client and ATT server. This has the same behavior as ATT.

**To Reproduce**
The current implementation in zephyr does not follow the "ENHANCED ATT BEARER L2CAP INTEROPERABILITY REQUIREMENTS". When EATT is connected, TX MTU and RX MTU can be different. GATT send ATT PDU size as TX MTU (bt_att_get_mtu) without considering RX MTU. In other words, maximum ATT PDU size can be different for different direction.

**Expected behavior**
Follow the "ENHANCED ATT BEARER L2CAP INTEROPERABILITY REQUIREMENTS", set ATT_MTU for EATT as the  the minimum of the MTU of ATT client and ATT server, so that maximum ATT PDU size is the same for different direction.

**Impact**
Different maximum ATT PDU size for sending and receiving will cause a lot of issues.
Issue 1:
When handling GATT read response, TX MTU is used to check whether it is a long characteristic, but real received payload size is decided by RX MTU.
Issue 2:
When sending "Prepare Write", TX MTU is used to set payload size, the same payload shall be returned by ATT server with the same EATT bearer, but RX MTU might be smaller than TX MTU, ATT client has no way to check the response successfully.

Hope that I didn't miss something in the specification.
Please help to check.

### PR DESCRIPTION
**Pull request by alwa-nordic**
See commit log for a "story". The gist of it is that storing the current ATT MTU in `chan->chan.rx.mtu` was incompatible with L2CAP ECRED MTU updates. The fix is to not overwrite `chan->chan.rx.mtu`.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/53475

### CODE REVIEW

File: subsys/bluetooth/host/att.c [hunk 1]
```diff
@@ -3035,11 +3045,8 @@ static void bt_att_connected(struct bt_l2cap_chan *chan)
 
 	atomic_set_bit(att_chan->flags, ATT_CONNECTED);
 
-	if (0) {
-#if defined(CONFIG_BT_EATT)
-	} else if (atomic_test_bit(att_chan->flags, ATT_ENHANCED)) {
+	if (bt_att_is_enhanced(att_chan)) {
```
Comment (jori-nordic) [inline subsys/bluetooth/host/att.c]: I think there's quite a bit more of those checks

**Review by theob-pro — DISMISSED** [review]

**Review by theob-pro — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

**Review by jori-nordic — APPROVED** [review]

**Review by theob-pro — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
