### PR TITLE
USB Device next cdc acm can get in a deadlock when the host doesn't pull the endpoint data

### LINKED ISSUE #78104: USB CDC_ACM locks system or at least slows it down heavily when no terminal is connected (USB DEVICE-NEXT)
**Describe the bug**
When running a device (using the device-next drivers / subsystem) using the cdc-acm class, the complete system can be slowed down or even locked. 
In this case, we have used a self-powered device using a nRF52833, but is looks to apply for any chipset. 

When there's data transfer sent to the cdc_acm and there's no terminal conntected, the tx_fifo worker keeps running in circles. 

at zephyr/subsys/usb/device_next/class/usbd_cdc_acm.c:545 the worker task (static void cdc_acm_tx_fifo_handler(struct k_work *work)), schedules submits it's own work task when there is no buffer. This would give an infinite loop. 
As the USB stack is running at prio -2. nothing else can be executed anymore. 

I notice this with a linux PC, but I can imagine the same will happen when there's no PC connected at all. 

**To Reproduce**
Build the passthrough example (zephyr/samples/drivers/uart/passthrough) with an actual uart on one end and the cdc-acm on the second. Send a lot of data over the physical uart which will start filling the the ringbuffers and fifo of the USB side. 
Connect the board to a (linux) pc and connect a terminal app. you would receive data and as soon as you close the terminal, the application will get stuck in the USB driver layer. (E.g. add printk("+") and printk("-") in the callback functions. 
Two ringbuffer blocks will be forwarded and then everything stops. 

**Expected behavior**
If the host doesn't consume the data in the endpoint / cdc-acm part is not satisfied and you run out of net buffers for this endpoint, do not constantly retry, but but let the other part of the usb device driver check if there is something in the tx_fifo as soon as the net buf is freed.

**Impact**
This is currently a showstopper for several USB based applications as the performance is killed / unexpected when using CDC-ACM

**Environment (please complete the following information):**

 - OS: Linux Mint 21 / Ubuntu 22.04
 - Toolchain Zephyr SDK
 - Version Zephyr 3.7

### PR DESCRIPTION
**Pull request by SynchronicIT**
Fixes #78104 

Current situation before the fix:
- The cdc_acm code starts claiming buffers to hand over to the lower layer driver for TX. 
- The lower layer drivers puts the data into the endpoint for the application / host
- lower layer gives a request callback when the endpoint is read
- cdc_acm layer frees the buffer. 

When the endpoint is not read, due to no terminal application running, the last two steps doesn't occur and the cdc_acm simply occupies all available buffers, followed by rescheduling the same work task for tx_fifo directly, creating an endless loop. 

By checking if a TX task is ongoing, the new work task scheduled as soon as the callback is given. 

There is no timeout used in this case, as I couldn't find an interface to configure a timeout.

### CODE REVIEW

File: subsys/usb/device_next/class/usbd_cdc_acm.c [hunk 1]
```diff
@@ -535,14 +551,20 @@ static void cdc_acm_tx_fifo_handler(struct k_work *work)
...
 	if (atomic_test_and_set_bit(&data->state, CDC_ACM_LOCK)) {
+		atomic_clear_bit(&data->state, CDC_ACM_RX_FIFO_BUSY);
 		cdc_acm_work_submit(&data->tx_fifo_work);
 		return;
 	}
 
 	buf = cdc_acm_buf_alloc(cdc_acm_get_bulk_in(c_data));
 	if (buf == NULL) {
-		cdc_acm_work_submit(&data->tx_fifo_work);
+		// cdc_acm_work_submit(&data->tx_fifo_work);
```
[the remark this answers is not in the document]
Comment (SynchronicIT) [reply subsys/usb/device_next/class/usbd_cdc_acm.c]: resolved in updated pull-request

**Comment by tmon-nordic** [comment]
Is this essentially https://github.com/zephyrproject-rtos/zephyr/issues/76642 that is fixed by https://github.com/zephyrproject-rtos/zephyr/pull/75439 or some other issue?

**Comment by SynchronicIT** [comment]
@tmon-nordic : The fix does take in account that poll could also be used, but I haven't validated that this would fix this mixed usage.

File: subsys/usb/device_next/class/usbd_cdc_acm.c [hunk 2]
```diff
@@ -48,6 +48,7 @@ UDC_BUF_POOL_DEFINE(cdc_acm_ep_pool,
 #define CDC_ACM_IRQ_TX_ENABLED		3
 #define CDC_ACM_RX_FIFO_BUSY		4
 #define CDC_ACM_LOCK			5
+#define CDC_ACM_TX_FIFO_BUSY		6
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_cdc_acm.c:51]: I do not want to introduce TX_FIFO_BUSY, we can handle it by using delayed work, which is needed anyway, see https://github.com/zephyrproject-rtos/zephyr/pull/75439/commits/741d8a7803c9417f755bbfa98b1f4f6fdf98d668.

File: subsys/usb/device_next/class/usbd_cdc_acm.c [hunk 3]
```diff
@@ -217,6 +218,11 @@ static int usbd_cdc_acm_request(struct usbd_class_data *const c_data,
 			atomic_clear_bit(&data->state, CDC_ACM_RX_FIFO_BUSY);
 		}
 
+		if (bi->ep == cdc_acm_get_bulk_in(c_data)) {
+			atomic_clear_bit(&data->state, CDC_ACM_TX_FIFO_BUSY);
+			LOG_ERR("TX ERROR !!");
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_cdc_acm.c:223]: There is no need to log an error here.

File: subsys/usb/device_next/class/usbd_cdc_acm.c [hunk 4]
```diff
@@ -236,9 +242,19 @@ static int usbd_cdc_acm_request(struct usbd_class_data *const c_data,
...
+		
+
+		if (ring_buf_is_empty(data->tx_fifo.rb)) {
+			/* Raise TX ready interrupt */
+			if (data->cb) {
+				cdc_acm_work_submit(&data->irq_cb_work);
+			}
+		} else {
+			/* Queue pending TX data on IN endpoint */
+			cdc_acm_work_submit(&data->tx_fifo_work);
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_cdc_acm.c:255]: No need to do anything other than trigger irq_cb_work.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

**Review by jfischer-no — COMMENTED** [review]
@SynchronicIT Can you please check commit message? Otherwise LGTM.

>In case the host doesn't pull the new data from the endpoint, the work task
would schedule itself again delayed (at the max. priority). When there is
no terminal program or active application. This commit changes this from
a polling behavior to

^

>By using a atomic flag for tx busy, the polling is solved and changed into
a postponed  execution of the next work taks which saves up to 5% of
CPU cycles.

File: subsys/usb/device_next/class/usbd_cdc_acm.c [hunk 5]
```diff
@@ -1,5 +1,6 @@
 /*
  * Copyright (c) 2022 Nordic Semiconductor ASA
+ * Copyright (c) 2024 SynchronicIT BV
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_cdc_acm.c:3]: I do not think that this commit is worthy of a claim here.

File: subsys/usb/device_next/class/usbd_cdc_acm.c [hunk 6]
```diff
@@ -548,6 +561,11 @@ static void cdc_acm_tx_fifo_handler(struct k_work *work)
...
 	}
 
+	if (atomic_test_and_set_bit(&data->state, CDC_ACM_TX_FIFO_BUSY)) {
+		LOG_DBG("TX transfer already in progress");
+		return;
+	}
+
 	buf = cdc_acm_buf_alloc(cdc_acm_get_bulk_in(c_data));
 	if (buf == NULL) {
 		cdc_acm_work_schedule(&data->tx_fifo_work, K_MSEC(1));
```
[the remark this answers is not in the document]
Comment (SynchronicIT) [reply subsys/usb/device_next/class/usbd_cdc_acm.c:572]: with the current implementation, having dedicated buffers for tx and rx, the buf == NULL case should never occur using the TX_BUSY flags. (both buffers are protected by a flag). 
For future changes (more buffers allocated) to go completely wrong, I added the extra clear statement. 

I also swapped the buffer free and flag free, so the flag is cleared after the buffer is cleared (and thus not busy anymore)

**Review by tmon-nordic — APPROVED** [review]

**Comment by SynchronicIT** [comment]
@tmon-nordic Do you want me to add this to the commit comment? or leave it as it is. For me no problem, but it triggers potentially the review and commit checks again.

**Comment by tmon-nordic** [comment]
> @tmon-nordic Do you want me to add this to the commit comment? or leave it as it is. For me no problem, but it triggers potentially the review and commit checks again.

I'd appreciate it if you do change the commit message. The commit message will stay there and it will be the first thing people looking through the CDC ACM class implementation history will notice. I am not sure if my review will disappear after merely commit message change, but I will re-approve as soon as I see the notification.

**Comment by jfischer-no** [comment]
From the commit message:

>Secondly, under the current structure of usbd_cdc_acm, there is a
possibility that TX data is enqueued to UDC driver before the previous
transaction is completed, hence causing dropped data. By using a
atomic flag for tx busy, no data is dropped and will only be enqueued
when there is room to forward the data.

I am still confused by this statement, where is the data dropped, can you point me to the line. It is fine to enqueue multiple transfers!

**Comment by SynchronicIT** [comment]
Hi @jfischer-no

I added the additional comments to the commit message on request of @tmon-nordic so that both mentioned issues are referred to. The initial goal of the commit was first of all solve the original deadlock and with the other patches, improve the performance. 
I'm hoping that we can get this merged into the main branch as soon as possible. And whatever non-technical part needs to be done, just agree together and tell me, so we can get it done. (and sorry for my direct Dutch approach...)

**Comment by jfischer-no** [comment]
> I added the additional comments to the commit message on request of @tmon-nordic so that both mentioned issues are referred to. The initial goal of the commit was first of all solve the original deadlock and with the other patches, improve the performance. I'm hoping that we can get this merged into the main branch as soon as possible. And whatever non-technical part needs to be done, just agree together and tell me, so we can get it done. (and sorry for my direct Dutch approach...)

I have seen this [request](https://github.com/zephyrproject-rtos/zephyr/pull/78160#issuecomment-2405004382). That is addressed in https://github.com/zephyrproject-rtos/zephyr/pull/78160/commits/adfb154b253f0c4a7ff6d5698a8ee3ddeda73ab1#diff-55bd613139b01a65e6f92a663ef66b84b0041b280ad89aa53a0afd517c86b059R261-R263. I think the commit message could be:


"In case the host doesn't pull the new data from the endpoint, the work task
would schedule itself again delayed (at the max. priority). When there is
no terminal program or active application reading the endpoint this
results in a constant polling of the endpoint burning up to 5% of the
CPU cycles.

By using a atomic flag for tx busy, the polling is solved and changed into
a postponed execution of the next work task which saves up to 5% of
CPU cycles and allows a better real-time behavior for other tasks.

_Secondly, if the TX interrupt is disabled but there is still data in the TX
FIFO (ring buffer), the implementation will continue to trigger subsequent
TX work and attempt to flush the data to the host._"

**Review by jfischer-no — APPROVED** [review]
