### PR TITLE
net: tcp: Send RST reply for unexpected TCP packets 

### LINKED ISSUE #63966: net: ip: Does not reset expired TCP session
**Describe the bug**
A TCP client can be programmed to use a fixed TCP source port. When we perform a power cycle to a target running the fixed-source-port TCP client that has already connected to the TCP server, the target will make a new TCP session with the same TCP source port, but the old TCP session is still kept by the TCP server which replies with the old ACK number.

<B>For Linux TCP client</B>, RST is issued if the TCP server ACKed unseen segment, and then the TCP server can accept new SYN with the same TCP source port.
(At packet No. 93, the TCP client restarts and sends a new SYN.)
image

If the Linux TCP client issues random-source-port SYN after a power cycle and hence the new connection is established immediately, the TCP server still issues TCP Keep-Alive for the old session, and the Linux TCP client will reset the old connection when it receives  TCP Keep-Alive.
(At packet No. 107, the TCP client restarts and sends a new SYN.)
image

<B>For Zephyr TCP client</B>, ACK is ignored if the TCP server ACKed unseen segment, and the Zephyr TCP client keeps retransmitting SYN, the connection cannot be established until the old TCP session kept by the TCP server reaches TCP-Keep-Alive timeout.
(At packet No. 49, the TCP client restarts and sends a new SYN.)
image

**To Reproduce**
1. Power the Zephyr TCP client up to make a TCP connection to the TCP server.
2. Power the Zephyr TCP client down, and then power the Zephyr TCP client up again.
```
#include <zephyr/net/socket.h>

int main(void)
{
    int fd, ret;
    struct sockaddr_in sin, servaddr;
    struct in_addr inaddr;

    fd = zsock_socket(AF_INET, SOCK_STREAM, 0);

    sin.sin_family = AF_INET;
    sin.sin_addr.s_addr = INADDR_ANY;
    sin.sin_port = htons(4044);
    zsock_bind(fd, (const struct sockaddr *)&sin, sizeof(sin));

    inet_pton(AF_INET, "10.123.4.223", (void *)&inaddr);

    servaddr.sin_family = AF_INET;
    servaddr.sin_addr = inaddr;
    servaddr.sin_port = htons(502);

    ret = zsock_connect(fd, (const struct sockaddr *)&servaddr, sizeof(servaddr));
    printk("zsock_connect()=%d\n", ret);

    return 0;
}
```

**Expected behavior**
Zephyr will reset the expired TCP session kept by the peer when the peer replies with an unexpected ACK number.

**Environment**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit: https://github.com/zephyrproject-rtos/zephyr/commit/433a85e7bf32ffc77ba194bb903bcca84c44c047

### PR DESCRIPTION
**Pull request by rlubos**
This PR improves the handling of unexpected packets within Zephyr's TCP stack. The TCP stack will now send RST packet in a response to unexpected TCP packets, to address issues mostly related to ungraceful TCP connection shutdown (for example due to reboot):
1) Invalid ACK value received during handshake (connection still open
   on the peer side),
2) Unexpected data packet on a listening port (accepted connection
   closed),
3) SYN received on a closed port.

For this, a new helper function was introduced which allows to send an RST packet to **any** destination (current functions allow only to send TCP packets to destinations associated with a TCP connection context, which is not always the case in this scenario).

Finally, add a few new tests to cover this functionality.

Fixes #63966

### CODE REVIEW

File: subsys/net/ip/connection.c [hunk 1]
```diff
@@ -828,11 +828,12 @@ enum net_verdict net_conn_input(struct net_pkt *pkt,
 
 	if (IS_ENABLED(CONFIG_NET_IP) && (pkt_family == AF_INET || pkt_family == AF_INET6) &&
 	    !(is_mcast_pkt || is_bcast_pkt)) {
-		conn_send_icmp_error(pkt);
-
 		if (IS_ENABLED(CONFIG_NET_TCP) && proto == IPPROTO_TCP) {
+			net_tcp_reply_rst(pkt);
```
Comment (jukkar) [inline subsys/net/ip/connection.c:832]: In Linux one can use netfilter to prevent RST to be sent out, and in Zephyr that might be possible at some point (currently not possible). So I was thinking that should we have a Kconfig option to allow earlier behavior, so that RST would not be sent if option is set, by default the option could be off so RST would be sent out. WDYT?

Comment (rlubos) [reply subsys/net/ip/connection.c:833]: @jukkar I've added a Kconfig option to configure whether to send RST packet on closed port. If disabled, ICMP is sent instead as it used to.

**Comment by rlubos** [comment]
@cfriedt Thrift tests needed small adjustments due to timing issues, please check the commit message for details.

**Review by jukkar — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
