### PR TITLE
Bluetooth: Add BT_SMP_ENFORCE_MITM option

### LINKED ISSUE #17463: Bluetooth: API limits usage of MITM flags in Pairing Request
**Describe the bug**
The problem was seen while testing Zephyr against qualification tests.
SM/MAS/SCPK/BV-01-C requires to initiate pairing with IO capability set to “DisplayOnly” or “KeyboardOnly” and MITM flag not set. The problem is that if local IO capabilities allow to create authenticated link, the Zephyr sets MITM flag automatically.

**Expected behavior**
The user should decide whether to pair with MITM or not, regardless of IO Capabilities used.

**Impact**
Cannot meet SM/MAS/SCPK/BV-01-C requirements

### PR DESCRIPTION
**Pull request by MariuszSkamra**
Having this option disabled, MITM flag state can be controlled by
bt_conn_security state. This option is enabled by default to not
change the current implementation behavior.
Related to SM/MAS/SCPK/BV-01-C.

Fixes #17463

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]
Will you also  have a patch to update the tester app? If that's needed it might be easier (for the subsequent backport) to include them both in the same PR.

**Comment by MariuszSkamra** [comment]
> Will you also have a patch to update the tester app? If that's needed it might be easier (for the subsequent backport) to include them both in the same PR.

I would wait with tester app PR for now. I think it will be necessary to modify btp documentation as well to add security level parameter to Opcode 0x11 - Pair command/response (or separate command). It's fixed now, set to BT_SECURITY_MEDIUM.

**Review by sjanc — APPROVED** [review]
yeap,  this is needed for manual testing only
we can think on how to extend btp when more tests will be added for autopts

File: subsys/bluetooth/host/smp.c [hunk 1]
```diff
@@ -2440,7 +2442,8 @@ static u8_t smp_pairing_req(struct bt_smp *smp, struct net_buf *buf)
 	smp->prsp[0] = BT_SMP_CMD_PAIRING_RSP;
 	rsp = (struct bt_smp_pairing *)&smp->prsp[1];
 
-	rsp->auth_req = get_auth(req->auth_req);
+	rsp->auth_req = get_auth(req->auth_req,
+				 req->auth_req & BT_SMP_AUTH_MITM);
```
Comment (joerchan) [inline subsys/bluetooth/host/smp.c]: Should we just give false here? It seems strange to me to let the request MITM flag control our response MITM flag. Unless we have the IO capabilities we cannot achieve MITM anyway. And the option to force MITM flag on should be enough to solve the problem.

**Review by joerchan — CHANGES_REQUESTED** [review]
I don't think the addition of the mitm flag is required. When we receive a request we shouldn't let the peer's MITM flag say that we can we want MITM protection unless we can actually acheive it.
And when sending requests, we already check that the required sec_level can be acheived by checking the IO capabilites.
I think the BT_SMP_ENFORCE_MITM option should be the only change.

File: subsys/bluetooth/host/smp.c (hunk 1 above)
Comment (MariuszSkamra) [reply subsys/bluetooth/host/smp.c]: You have right regarding mitm flag. But apart from BT_SMP_ENFORCE_MITM, conn->required_sec_level has to be checked when BT_SMP_ENFORCE_MITM is disabled.

Comment (joerchan) [reply subsys/bluetooth/host/smp.c]: Yes, we do that in `sec_level_reachable`, which is done before. So it will always be true, otherwise -EINVAL is returned.

Comment (MariuszSkamra) [reply subsys/bluetooth/host/smp.c]: But the aim of this PR is to have a possibility to set the MITM flag based security level provided by user. Looking into API:

/** Security level. */
typedef enum __packed {
	/** Only for BR/EDR special cases, like SDP */
	BT_SECURITY_NONE,
	/** No encryption and no authentication. */
	BT_SECURITY_LOW,
	/** Encryption and no authentication (no MITM). */
	BT_SECURITY_MEDIUM,
	/** Encryption and authentication (MITM). */
	BT_SECURITY_HIGH,
	/** Authenticated Secure Connections */
	BT_SECURITY_FIPS,
} bt_security_t;

Passing BT_SECURITY_MEDIUM to bt_conn_security will set the MITM flag based on local IO Capabilities even if user requested encryption without authentication.

Comment (joerchan) [reply subsys/bluetooth/host/smp.c]: Thank you for explaining, that makes sense.

**Review by joerchan — APPROVED** [review]
