### PR TITLE
Fix init hang issue

### LINKED ISSUE #74980: mbedtls and libc initialization priority problem leads to device hanging
In device init phase, it will call _mbedtls_init before malloc_prepare as mbedtls has higher priority defined in SYS_INIT..
_mbedtls_init() will call psa_crypto_init() and malloc buffer, but z_malloc_heap is not initialized, which will cause device hang.
Should call malloc_prepare() before _mbedtls_init to fix this issue, so exchange their priority to init in SYS_INIT.

### PR DESCRIPTION
**Pull request by MaochenWang1**
modules: mbedtls: Fix init hang issue
libc: common: Fix init hang issue

In device init phase, it will call _mbedtls_init before malloc_prepare
as mbedtls has higher priority defined in SYS_INIT..
_mbedtls_init() will call psa_crypto_init() and malloc buffer,
but z_malloc_heap is not initialized, which will cause device hang.
Should call malloc_prepare() before _mbedtls_init to fix this issue,
so exchange their priority to init in SYS_INIT.

Fixes #74980

### CODE REVIEW

File: lib/libc/common/source/stdlib/malloc.c [hunk 1]
```diff
@@ -260,7 +260,7 @@ void free(void *ptr)
 	malloc_unlock();
 }
 
-SYS_INIT(malloc_prepare, POST_KERNEL, CONFIG_KERNEL_INIT_PRIORITY_DEFAULT);
+SYS_INIT(malloc_prepare, POST_KERNEL, 0);
```
Comment (ceolin) [inline lib/libc/common/source/stdlib/malloc.c:263]: Not blocking but wouldn't be better having a specific symbol for the C library ?
```
config KERNEL_INIT_PRIORITY_LIBC
	int "LIBC initialization priority"
	default 30
	help
	  LIBC uses this priority for initialization. This
	  priority needs to be higher than minimal default initialization
	  priority.
```

**Comment by ithinuel** [comment]
I had issues because of this with the ethos-u drivers that’s currently requiring a malloc call during device driver initialization, which happens before malloc_prepare is called.

What would be the reason for not doing this ASAP during boot? Or is it a matter where drivers relying on this should be given a lower priority and done at a later stage?

**Comment by ceolin** [comment]
> I had issues because of this with the ethos-u drivers that’s currently requiring a malloc call during device driver initialization, which happens before malloc_prepare is called.
> 
> What would be the reason for not doing this ASAP during boot? Or is it a matter where drivers relying on this should be given a lower priority and done at a later stage (if possible, I’m not familiar with this)?

Services initialization is "complicated" now. The priority I suggest is just an example, it can be `0` as in this PR. I would just make it through a symbol in case a target needs a different priority. Since we are talking about the C library I don't see a problem having a specific symbol for that.

**Review by keith-packard — DISMISSED** [review]
This seems like a fine hack to resolve this specific issue. A perfect solution would compute the correct priorities based on a dependency graph, but generating dependency information would take a lot of analysis. At the least, it would be good to provide some documentation about the priorities somewhere so that developers can configure them in a less ad-hoc fashion.

**Comment by cfriedt** [comment]
Malloc is kind of horrible in drivers and critical subsystems. It would be great if it could be avoided entirely.

File: lib/libc/common/source/stdlib/malloc.c (hunk 1 above)
Comment (MaochenWang1) [reply lib/libc/common/source/stdlib/malloc.c]: Hi @ceolin , changed as your comment, pls review again

**Comment by MaochenWang1** [comment]
Hi @keith-packard ,pls review again

**Review by ceolin — DISMISSED** [review]

**Comment by MaochenWang1** [comment]
Hi @keith-packard , can you please review again?

File: kernel/Kconfig.device [hunk 2]
```diff
@@ -45,6 +45,14 @@ config KERNEL_INIT_PRIORITY_OBJECTS
 	  priority needs to be higher than minimal default initialization
 	  priority.
 
+config KERNEL_INIT_PRIORITY_LIBC
+	int "LIBC initialization priority"
+	default 30
```
Comment (keith-packard) [inline kernel/Kconfig.device:50]: I think malloc should initialize after kernel objects as malloc initialization *could* involve initializing various kernel objects like mutexes. Therefore, I think this value should be between KERNEL_INIT_PRIORITY_OBJECTS and KERNEL_INIT_PRIORITY_DEFAULT.

File: modules/mbedtls/zephyr_init.c [hunk 3]
```diff
@@ -104,7 +104,7 @@ static int _mbedtls_init(void)
 }
 
 #if defined(CONFIG_MBEDTLS_INIT)
-SYS_INIT(_mbedtls_init, POST_KERNEL, 0);
```
Comment (keith-packard) [inline modules/mbedtls/zephyr_init.c:107]: There are dozens of other SYS_INIT call sites using priority level 0. Do you want to fix them all? Should we make this an error so that we can catch it in the future?

**Review by keith-packard — CHANGES_REQUESTED** [review]
I think the LIBC priority needs to be set so that it is initialized after kernel objects in case it needs to perform a runtime mutex initialization.

File: modules/mbedtls/zephyr_init.c (hunk 3 above)
Comment (MaochenWang1) [reply modules/mbedtls/zephyr_init.c:107]: Fixing them all needs fully test, but now I only can find the issue between mbedtls and malloc on our device, so for the safety consideration, I will only change this one.

File: kernel/Kconfig.device (hunk 2 above)
Comment (MaochenWang1) [reply kernel/Kconfig.device]: have updated as your comment, pls review again

**Comment by MaochenWang1** [comment]
Hi @keith-packard @ceolin 
pls review again, thanks

**Comment by andyross** [comment]
>  Malloc is kind of horrible in drivers and critical subsystems. It would be great if it could be avoided entirely.

An alternative here would be to enforce that: assert or panic if you get a malloc call before libc initialization and force subsystems that want to do clumsy things to finesse things themselves...

**Comment by dleach02** [comment]
> Malloc is kind of horrible in drivers and critical subsystems. It would be great if it could be avoided entirely.

While I tend to agree, this problem is really between mbedtls and libc initialization order. Not sure I characterize mbedtls as a driver. 

But @andyross suggestion is a good one to generally consider to see if we can find other entities that are probably failing this priority inversion. Adding the following in the various alloc routines (malloc, aligned_alloc, realloc?, free?) should capture this problem. The z_malloc_heap is defined as a static but should be in the bss section but if we want to ensure that we could define it with an assignments to set to NULL:

`
	__ASSERT(z_malloc_heap.heap != NULL, "Priority inversion, malloc_prepare() has not been called");
`

**Review by keith-packard — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by dleach02** [comment]
@stephanosio need your attention

**Review by npitre — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
