### PR TITLE
subsys/mgmt/hawkbit: Bug fixes and improvements

### LINKED ISSUE #37272: subsys/mgmt/hawkbit: Falsely determine that an update is installed successfully
**Describe the bug**
`hawkbit` determines that an update is installed and ready for reboot even though it only downloaded and written 5.75% of the image into the flash.

**To Reproduce**
I testing the `hawkbit` sample with a STM32G0B1RE custom board with a GSM (LTE) modem (Quectel EC21). `image-1` slot is in an external `spi-nor` flash.

**Expected behavior**
Downloads the OTA target firmware successfully, and can be applied to primary slot after `kernel reboot cold`

**Impact**
Unable to use `hawkbit`

**Logs and console output**
[hawkbit_log.txt](https://github.com/zephyrproject-rtos/zephyr/files/6891871/hawkbit_log.txt)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: gnuarmemb
 - v2.6.0-rc2-107-gebe282b02d9f

**Additional context**
Ubuntu 20.04, running `hawkbit` in a docker following the `hawkbit`'s sample `README`
`hawkbit` external port is changed to `9010` instead of the default `8080`, sitting behind nginx reverse proxy such that it can be access from hawkbit.mydomain.com with SSL. (shouldn't matter since the device access `hawkbit` using raw IP)

### LINKED ISSUE #37327: subsys/mgmt/hawkbit: hawkbit run can interrupt a running instance
**Describe the bug**
`hawkbit`'s shell cmd: [`hawkbit run` ](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/hawkbit/shell.c#L22) calls the [`hawkbit_probe()`](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/hawkbit/hawkbit.c#L1010) which clears the `hawkbit` context variable [on entry](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/hawkbit/hawkbit.c#L1021). The same function is called by the [`autohandler()`](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/hawkbit/hawkbit.c#L1228), which is scheduled to run in the background as work. So if the shell cmd is used while the work is running, or the other way around, something will be wrong.

**To Reproduce**
1. Run the `hawkbit` sample
2. Type `hawkbit run` in the console while the `hawkbit_probe()` is running
3. IIRC, the whole thing will hang

**Expected behavior**
The shell command should just return, telling the user that a `hawkbit` process is already running, without interrupting the running process.

## Suggested fix
Initialize a semaphore with an initial count of one and limit to one in the `hawkbit_init`, in the `hawkbit_probe()`, take the sem with `K_NO_WAIT`, continue only if it got the sem or return otherwise. Before the `hawkbit_probe()` returns, signal the semaphore so that the `hawkbit_probe` can be called again.

Since `hawkbit_probe()` is of `enum hawkbit_response` type, it is necessary to create another entry `HAWKBIT_ALREADY_RUNNING` and handle that in the `cmd_run()` & `autohandler()`

### PR DESCRIPTION
**Pull request by ycsin**
Bug fixes and improvements for the hawkbit subsys.

Fixes:

- #37327
- #37272
- #37225
   - 1 - The hawkbit_init function is assuming the "storage" label to be with DT_CHOSEN_ZEPHYR_FLASH_CONTROLLER_LABEL (usually flash0?) whereas it can can be with the external serial flash so this should follows where the "storage" is defined instead of a constant.
   - 2 - Similar to 1
   - 3 - Removes a typo (extra space)
   - 7 - LOG_MODULE_REGISTER(hawkbit); is wrong, its verbosity can't be configured
 - (sample) Add missing header
 - (sample) Remove unused variable

Improvements
- Verify SHA256 hash of the downloaded image to determine if the download is successful before asking the bootloader to perform an upgrade.

Closes #37272
Closes #37327

### CODE REVIEW

**Comment by ycsin** [comment]
@cfriedt

**Comment by ycsin** [comment]
This seems to be not used as well:
```c
#define NETWORK_TIMEOUT (2 * MSEC_PER_SEC)
```

**Comment by ycsin** [comment]
@Navin-Sankar Is there a possibility where the firmware written into the flash can be corrupted? To eliminate such possibility I guess maybe we can read back the written firmware and calculate its SHA256 again?

File: subsys/mgmt/hawkbit/hawkbit.c [hunk 1]
```diff
@@ -298,6 +307,29 @@ static void cleanup_connection(void)
 	}
 }
 
+static int string2hex(const char *string, const size_t len, char *hex)
```
Comment (sylvioalves) [inline subsys/mgmt/hawkbit/hawkbit.c:310]: Zephyr already contains some of these functions as in `sys/util.h`. For this one, I think `hex2bin` does the job. Can you check?

File: subsys/mgmt/hawkbit/hawkbit.c [hunk 2]
```diff
@@ -1195,20 +1245,53 @@ enum hawkbit_response hawkbit_probe(void)
...
-		goto cleanup;
+		goto free_md;
 	}
 
-	if (boot_request_upgrade(BOOT_UPGRADE_TEST)) {
-		LOG_ERR("Download failed");
+	if (!hb_context.final_data_received) {
+		LOG_ERR("Download is not complete");
+		hb_context.code_status = HAWKBIT_DOWNLOAD_ERROR;
+	} else if (memcmp(response_hash, hb_context.dl.file_hash,
```
Comment (sylvioalves) [inline subsys/mgmt/hawkbit/hawkbit.c:1285]: Does hawkbit server supply file hash info on its json response with available docker image?

File: subsys/mgmt/hawkbit/hawkbit.c [hunk 3]
```diff
@@ -621,7 +661,7 @@ int hawkbit_init(void)
 	LOG_DBG("Action id: current %d", action_id);
 
 	image_ok = boot_is_img_confirmed();
-	LOG_INF("Image is %s confirmed OK", image_ok ? "" : " not");
+	LOG_INF("Image is %s confirmed OK", image_ok ? "" : "not");
```
Comment (sylvioalves) [inline subsys/mgmt/hawkbit/hawkbit.c:664]: `LOG_INF("Image is %s confirmed OK", image_ok ? "" : "not");`
In case of success, message will contain 2 spaces as in: `Image is**confirmed OK`  
Solution would be:
``LOG_INF("Image is%s confirmed OK", image_ok ? "" : " not");``
Make sense?

File: subsys/mgmt/hawkbit/hawkbit.c (hunk 2 above)
Comment (Navin-Sankar) [reply subsys/mgmt/hawkbit/hawkbit.c:1285]: yes the available docker image provides file hash info in three format's `sha1`, `md5` and `sha256`.

**Review by Navin-Sankar — DISMISSED** [review]

File: subsys/mgmt/hawkbit/hawkbit.c (hunk 3 above)
Comment (ycsin) [reply subsys/mgmt/hawkbit/hawkbit.c:664]: @sylvioalves You are right, thanks for pointing that out

File: subsys/mgmt/hawkbit/hawkbit.c [hunk 4]
```diff
@@ -92,6 +99,8 @@ static union {
 
 static struct k_work_delayable hawkbit_work_handle;
 
+static struct k_sem probe_sem;
```
[the remark this answers is not in the document]
Comment (ycsin) [reply subsys/mgmt/hawkbit/hawkbit.c:102]: @Navin-Sankar I don't think I can, the `hawkbit_probe` will reset the whole hawkbit_context.

File: subsys/mgmt/hawkbit/hawkbit.c (hunk 2 above)
Comment (ycsin) [reply subsys/mgmt/hawkbit/hawkbit.c:1261]: @sylvioalves It [should](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/hawkbit/hawkbit.c#L588). You can verify if you [fixed and enabled the log](https://github.com/zephyrproject-rtos/zephyr/pull/37351/commits/d761a3a74816cf543fb16c671d9f8c532e69139a).

File: subsys/mgmt/hawkbit/hawkbit.c (hunk 1 above)
Comment (ycsin) [reply subsys/mgmt/hawkbit/hawkbit.c]: @sylvioalves I think you are right, didn't notice that `hex2bin` actually outputs `uint8_t` instead of binary as I previously thought, thanks for pointing that out.

File: subsys/mgmt/hawkbit/hawkbit.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (Navin-Sankar) [reply subsys/mgmt/hawkbit/hawkbit.c:102]: Ok. then it's not required.

File: subsys/mgmt/hawkbit/hawkbit.c (hunk 1 above)
Comment (ycsin) [reply subsys/mgmt/hawkbit/hawkbit.c]: I modified it to use the `hex2bin` now, but I'm not sure if it works (unsure about the `strlen()` part), have to test it when I'm back to work

File: subsys/mgmt/hawkbit/hawkbit.c (hunk 2 above)
Comment (Navin-Sankar) [reply subsys/mgmt/hawkbit/hawkbit.c:1261]: Available docker image provides file hash info in three format's `sha1`, `md5` and `sha256`

File: subsys/mgmt/hawkbit/hawkbit.c [hunk 5]
```diff
@@ -517,6 +526,13 @@ static int hawkbit_parse_deployment(struct hawkbit_dep_res *res,
 	}
 
 	artifact = &chunk->artifacts[0];
+
+	if (hex2bin(artifact->hashes.sha256, strlen(artifact->hashes.sha256),
```
Comment (sylvioalves) [inline subsys/mgmt/hawkbit/hawkbit.c:530]: For safety reasons, I would consider using `strnlen` or eventually `mbedtls_md_get_size(hash_info)` as size reference:
```c
size_t hash_size = mbedtls_md_get_size(hash_info);
```

Comment (ycsin) [reply subsys/mgmt/hawkbit/hawkbit.c]: Make sense, edited

**Review by sylvioalves — APPROVED** [review]
@ycsin Looks good to me. 
@Navin-Sankar Can you review again?

File: subsys/mgmt/hawkbit/hawkbit.c [hunk 6]
```diff
@@ -517,6 +527,13 @@ static int hawkbit_parse_deployment(struct hawkbit_dep_res *res,
 	}
 
 	artifact = &chunk->artifacts[0];
+	hash_info = mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);
+	if (hex2bin(artifact->hashes.sha256, mbedtls_md_get_size(hash_info),
```
Comment (ycsin) [inline subsys/mgmt/hawkbit/hawkbit.c:531]: This is wrong, second arg of `hex2bin` is the length of the hex string provided, so it should be 64 here instead of 32.
The `mbedtls_md_get_size(hash_info)` has to be replaced by either `strlen(artifact->hashes.sha256)` or a hardcoded `#define` macro.

@sylvioalves What do you think?

Comment (sylvioalves) [reply subsys/mgmt/hawkbit/hawkbit.c:531]: I am not exactly aware of what is provided by the hawkbit server. However, I agree it won't work as the hex-string would be then 64 bytes instead of 32 as from the byte-array hash.  I am ok then using previous modification.

Comment (ycsin) [reply subsys/mgmt/hawkbit/hawkbit.c:531]: @sylvioalves I will use the `hex2bin` instead of the previously custom conversion function, just that I'd have to use `strlen` instead of `strnlen` because `strnlen` requires a max length arg and if I use `strnlen`, I might as well just use a defined macro. And you raised some security concert with `strlen` last time, that's why I'd like to have your comments.

FYI it will receive this:

```json
{
    "id": "2",
    "deployment": {
        "download": "forced",
        "update": "forced",
        "chunks": [
            {
                "part": "bApp",
                "version": "0.0.1",
                "name": "hawkbit",
                "artifacts": [
                    {
                        "filename": "zephyr.signed.bin",
                        "hashes": {
                            "sha1": "ffe8f293999df74153b53ac53618d65b1e3f6764",
                            "md5": "23d17ad9288c229941d0806e4d78af03",
                            "sha256": "95141b6b8a70676d204bbc4587666a691f8cc651e43596824a2d05e360d3da41"
                        },
                        "size": 205765,
                        "_links": {
                            "download-http": {
                                "href": "http://123.123.12:9010/DEFAULT/controller/v1/ivm22_g0b1re-2037334b3436500b004d003f/softwaremodules/1/artifacts/zephyr.signed.bin"
                            },
                            "md5sum-http": {
                                "href": "http://123.123.12:9010/DEFAULT/controller/v1/ivm22_g0b1re-2037334b3436500b004d003f/softwaremodules/1/artifacts/zephyr.signed.bin.MD5SUM"
                            }
                        }
                    }
                ]
            }
        ]
    }
}
```

Comment (sylvioalves) [reply subsys/mgmt/hawkbit/hawkbit.c:531]: I don't see a problem having the some  `#define HAWKBIT_HASH_STR_SIZE 64` for this. Any other sugestion?

**Comment by carlescufi** [comment]
@Navin-Sankar could you please approve this if happy?

**Comment by ycsin** [comment]
I've force pushed to fix a few more typo and make the log outputs of the sample and the subsys itself more consistent in this [commit](https://github.com/zephyrproject-rtos/zephyr/pull/37351/commits/0697d1b65f548bd9f528df415f3666479f8f6054). The functionalities should remain the same.

**Review by Navin-Sankar — APPROVED** [review]
