### PR TITLE
stm32: mco: Remove deprecated Kconfig configuration

### LINKED ISSUE #80885: PLL-I2S clock misconfiguration on STM32F446
**Describe the bug**

I'm using a custom board with an STM32F446 inside and a 24MHz crystal oscillator for HSE. I want to generate a 25MHz via MCO2 output. To do so, i want to use pll-i2s clock with this configuration:
- DIV_M = 12
- MULT_N = 100
- DIV_R = 2
This creates a 100MHz output. With MCO's clock divider = 4 it must generate a 25MHz clock.
Instead i have a 36Mhz output. I've took a look on RCC config register and values are not consistent with dts configuration file. Register values are:
- DIV_M = 16
- MULT_N = 192
- DIV_R = 2
Those values are consistent with experimental 36MHz clock. Furthermore, MCO_2 pin slew_rate is not set to very_high.

**To Reproduce**

DTS file:

```dts
 /dts-v1/;
 #include <st/f4/stm32f446Xe.dtsi>
 #include <st/f4/stm32f446r(c-e)tx-pinctrl.dtsi>
 #include <zephyr/dt-bindings/input/input-event-codes.h>
 
 / {
	 model = "Custom board test";
	 compatible = "st,stm32f446re-nucleo";
 
	 chosen {
		 zephyr,console = &uart4;
		 zephyr,shell-uart = &uart4;
		 zephyr,sram = &sram0;
		 zephyr,flash = &flash0;
	 };
 
	 leds: leds {
		compatible = "gpio-leds";
		green_led: led_0 {
			gpios = <&gpioa 9 GPIO_ACTIVE_HIGH>;
			label = "User LD1";
		};
		en_vusb: led_1 {
			gpios = <&gpioc 3 GPIO_ACTIVE_HIGH>;
			label = "Enable USB alim";
		};
		en_vana: led_2 {
			gpios = <&gpioc 13 GPIO_ACTIVE_HIGH>;
			label = "Enable Analog alim";
		};
	};



	aliases {
		led0 = &green_led;
		led1 = &en_vusb;
		led2 = &en_vana;
	};
 };
 
 &clk_lsi {
	 status = "okay";
 };
 
 &clk_hse {
	clock-frequency = <DT_FREQ_M(24)>; /* 24MHz clock */
	status = "okay";
 };
 
 &pll {
	 div-m = <12>;
	 mul-n = <96>;
	 div-p = <2>;
	 div-q = <4>;
	 clocks = <&clk_hse>;
	 status = "okay";
 };

 &plli2s {
	mul-n = <100>;
	div-r = <2>;
	clocks = <&clk_hse>;
	status = "okay";
};
 
 &rcc {
	 clocks = <&pll>;
	 clock-frequency = <DT_FREQ_M(96)>;
	 ahb-prescaler = <1>;
	 apb1-prescaler = <2>;
	 apb2-prescaler = <1>;
 };
 
 &usart2 {
	 pinctrl-0 = <&usart2_tx_pa2 &usart2_rx_pa3>;
	 pinctrl-names = "default";
	 current-speed = <460800>;
	 status = "okay";
 };

 &uart4 {
	pinctrl-0 = <&uart4_tx_pa0 &uart4_rx_pa1>;
	pinctrl-names = "default";
	current-speed = <460800>;
	status = "okay";
};

&i2s1 {
	pinctrl-0 = <&i2s1_ck_pa5 &i2s1_sd_pa7 &i2s1_ws_pa4>;
	// clocks = <&rcc STM32_SRC_PLL2_R I2S_SEL(0)>;
	pinctrl-names = "default";
	status = "okay";
};

&i2s2 {
	pinctrl-0 = <&i2s2_ck_pb13 &i2s2_sd_pb15 &i2s2_ws_pb12>;
	// clocks = <&rcc STM32_SRC_PLL2_R I2S_SEL(0)>;
	pinctrl-names = "default";
	status = "okay";
};

&mco2 {
	clocks = <&rcc STM32_SRC_PLLI2S_R MCO2_SEL(1)>;
	prescaler = <MCO2_PRE(6)>;
	pinctrl-0 = <&rcc_mco_2_pc9>;
	pinctrl-names = "default";
	status = "okay";
};

 zephyr_udc0: &usbotg_fs {
	pinctrl-0 = <&usb_otg_fs_dm_pa11 &usb_otg_fs_dp_pa12>;
	pinctrl-names = "default";
	maximum-speed = "full-speed";
	phys = <&otgfs_phy>;
	status = "okay";
};

&sdmmc1 {
	compatible = "st,stm32-sdmmc";
	pinctrl-0 = <&sdio_d0_pc8 &sdio_d1_pb0
				&sdio_d2_pb1 &sdio_d3_pc11
				&sdio_d4_pb8 &sdio_d5_pb9
				&sdio_d6_pc6 &sdio_d7_pc7
				&sdio_ck_pb2 &sdio_cmd_pd2>;
	// resets = <&gpiog 6 GPIO_ACTIVE_LOW>;
	// reset-names = "default";
	clk-div = <16>;
	pinctrl-names = "default";
	bus-width = <8>;
	status = "okay";
};
 
 &backup_sram {
	 status = "okay";
 };
 
 &flash0 {
 
	 partitions {
		 compatible = "fixed-partitions";
		 #address-cells = <1>;
		 #size-cells = <1>;
 
		 boot_partition: partition@0 {
			 label = "mcuboot";
			 reg = <0x00000000 DT_SIZE_K(64)>;
			 read-only;
		 };
 
		 /*
		  * The flash starting at 0x00010000 and ending at
		  * 0x0001ffff (sectors 16-31) is reserved for use
		  * by the application.
		  */
		 storage_partition: partition@10000 {
			 label = "storage";
			 reg = <0x00010000 DT_SIZE_K(64)>;
		 };
 
		 slot0_partition: partition@20000 {
			 label = "image-0";
			 reg = <0x00020000 DT_SIZE_K(128)>;
		 };
		 slot1_partition: partition@40000 {
			 label = "image-1";
			 reg = <0x00040000 DT_SIZE_K(128)>;
		 };
		 scratch_partition: partition@60000 {
			 label = "image-scratch";
			 reg = <0x00060000 DT_SIZE_K(128)>;
		 };
	 };
 };
```

**Expected behavior**

Expected behavior is a 25MHz clock on MCO2 pin.

**Impact**

**Logs and console output**

**Environment (please complete the following information):**

 - OS:  Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: Zephyr OS build v3.7.0-4773-g2f23313e37e4

**Additional context**

### PR DESCRIPTION
**Pull request by FRASTM**
change the configuration of the MCO 1 or 2 output for the stm32 series
Kconfig is no more used, set the configuration by the DTS  as speciied by the  dts/bindings/clock/st,stm32-clock-mco.yaml

See the refman of the stm32 to put the correct clock source and the prescaler value

```
&mco2 {
	clocks = <&rcc STM32_SRC_PLLI2S_R MCO2_SEL(1)>;
	prescaler = <MCO2_PRE(5)>; /* div by 5 --> set 0b111 in the MCO2PRE of the RCC CFGR */
	pinctrl-0 = <&rcc_mco_2_pc9>;
	pinctrl-names = "default";
	status = "okay";
};

```
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/80885

### CODE REVIEW

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 1]
```diff
@@ -110,7 +110,11 @@ void config_plli2s(void)
 				       STM32_PLLI2S_N_MULTIPLIER,
 				       plli2sr(STM32_PLLI2S_R_DIVISOR));
 #elif DT_HAS_COMPAT_STATUS_OKAY(st_stm32f412_plli2s_clock)
+#ifdef RCC_PLLR_I2S_CLKSOURCE_SUPPORT
 	LL_RCC_PLL_ConfigDomain_I2S(get_pll_source(),
+#else
+	LL_RCC_PLLI2S_ConfigDomain_I2S(get_pll_source(),
+#endif
```
Comment (erwango) [inline drivers/clock_control/clock_stm32f2_f4_f7.c:117]: STM2F411 should define its own compatible then.

File: dts/arm/st/f4/stm32f411.dtsi [hunk 2]
```diff
@@ -6,7 +6,17 @@
 
 #include <st/f4/stm32f401.dtsi>
 
+/delete-node/ &plli2s;
```
Comment (erwango) [inline dts/arm/st/f4/stm32f411.dtsi:9]: Not required

File: dts/arm/st/f4/stm32f446.dtsi [hunk 3]
```diff
@@ -8,6 +8,8 @@
 #include <zephyr/dt-bindings/clock/stm32f410_clock.h>
 #include <zephyr/dt-bindings/memory-controller/stm32-fmc-sdram.h>
 
+/delete-node/ &plli2s;
+
```
Comment (erwango) [inline dts/arm/st/f4/stm32f446.dtsi:12]: Not required

**Review by erwango — CHANGES_REQUESTED** [review]
In commit message of "drivers: clock_control: stm32 mco driver get define from DTS", please mention that DTS configuration has been introduced and Kconfig method deprecated two releases before and can be then safely removed.
Please also update migration guide on this.

File: dts/arm/st/f4/stm32f411.dtsi (hunk 2 above)
Comment (FRASTM) [reply dts/arm/st/f4/stm32f411.dtsi]: removed

File: dts/arm/st/f4/stm32f446.dtsi (hunk 3 above)
Comment (FRASTM) [reply dts/arm/st/f4/stm32f446.dtsi]: removed

File: drivers/clock_control/clock_stm32f2_f4_f7.c (hunk 1 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32f2_f4_f7.c]: new st,stm32f411-plli2s-clock  added,

File: drivers/clock_control/clock_stm32_ll_u5.c [hunk 4]
```diff
@@ -117,16 +111,13 @@ static uint32_t get_sysclk_frequency(void)
...
 {
-	if ((src_clk == STM32_SRC_SYSCLK) ||
-	    (src_clk == STM32_SRC_HCLK) ||
-	    (src_clk == STM32_SRC_PCLK1) ||
-	    (src_clk == STM32_SRC_PCLK2) ||
+	if ((src_clk == STM32_SRC_SYSCLK) || (src_clk == STM32_SRC_HCLK) ||
+	    (src_clk == STM32_SRC_PCLK1) || (src_clk == STM32_SRC_PCLK2) ||
 	    (src_clk == STM32_SRC_PCLK3) ||
 	    ((src_clk == STM32_SRC_HSE) && IS_ENABLED(STM32_HSE_ENABLED)) ||
 	    ((src_clk == STM32_SRC_HSI16) && IS_ENABLED(STM32_HSI_ENABLED)) ||
```
Comment (erwango) [inline drivers/clock_control/clock_stm32_ll_u5.c:123]: This change makes code harder to read and maintain.

File: drivers/clock_control/clock_stm32_ll_u5.c [hunk 5]
```diff
@@ -103,10 +99,8 @@ static uint32_t get_pllout_frequency(uint32_t pllsrc_freq,
 static uint32_t get_sysclk_frequency(void)
 {
 #if defined(STM32_SYSCLK_SRC_PLL)
-	return get_pllout_frequency(get_pllsrc_frequency(PLL1_ID),
-					STM32_PLL_M_DIVISOR,
-					STM32_PLL_N_MULTIPLIER,
-					STM32_PLL_R_DIVISOR);
+	return get_pllout_frequency(get_pllsrc_frequency(PLL1_ID), STM32_PLL_M_DIVISOR,
+				    STM32_PLL_N_MULTIPLIER, STM32_PLL_R_DIVISOR);
```
Comment (erwango) [inline drivers/clock_control/clock_stm32_ll_u5.c:103]: This change makes code harder to read and maintain.

File: drivers/clock_control/clock_stm32_ll_u5.c [hunk 6]
```diff
@@ -18,23 +17,22 @@
 #include <zephyr/sys/util.h>
 #include <zephyr/drivers/clock_control/stm32_clock_control.h>
 
-
 /* Macros to fill up prescaler values */
-#define z_ahb_prescaler(v) LL_RCC_SYSCLK_DIV_ ## v
-#define ahb_prescaler(v) z_ahb_prescaler(v)
+#define z_ahb_prescaler(v) LL_RCC_SYSCLK_DIV_##v
```
Comment (erwango) [inline drivers/clock_control/clock_stm32_ll_u5.c:21]: Are we sure this change is safe ?

File: samples/boards/st/mco/sample.yaml [hunk 7]
```diff
@@ -2,5 +2,6 @@ sample:
   name: STM32 microcontroller clock output (MCO) example
 tests:
   sample.board.stm32.mco:
-    platform_allow: nucleo_u5a5zj_q stm32f746g_disco
+    platform_allow: nucleo_u5a5zj_q stm32f746g_disco nucleo_f411re
+    filter: not CONFIG_SOC_SERIES_STM32WB0X
```
Comment (erwango) [inline samples/boards/st/mco/sample.yaml:6]: Why specifically WB0 ? There are other series not enabling MCO.
Also, filter should not be required if `platform_allow` is used

File: samples/boards/st/mco/README.rst [hunk 8]
```diff
@@ -16,6 +16,12 @@ Requirements
 The SoC should support MCO functionality and use a pin that has the MCO alternate function.
 To support another board, add a dts overlay file in boards folder.
 Make sure that the output clock is enabled in dts overlay file.
+Depending on the stm32 serie, several clock source and prescaler are possible for each MCOx.
+The clock source is set by the DTS among the possible values for each stm32 serie.
+The prescaler is set by the DTS, through the property ``prescaler = <MCOx_PRE(n)>;``
+where ``n`` depends on the stm32 serie.
+
+It is required to check the Reference Manual to  configure the DTS correctly.
```
Comment (erwango) [inline samples/boards/st/mco/README.rst:24]: We should rather enhance binding documentation and redirect to it.

File: samples/boards/st/mco/boards/nucleo_f411re.overlay [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+	pinctrl-0 = <&rcc_mco_1_pa8>;
+	pinctrl-names = "default";
+	status = "okay";
+};
+
+#define MCO2_PRE_DIV_5 7
+
+&mco2 {
+	clocks = <&rcc STM32_SRC_PLLI2S_R MCO2_SEL(1)>;
+	prescaler = <MCO2_PRE(MCO2_PRE_DIV_5)>; /* set 0b111 in the MCO2PRE of the RCC CFGR */
```
Comment (erwango) [inline samples/boards/st/mco/boards/nucleo_f411re.overlay:28]: Usage of `MCO2_PRE_DIV_5` greatly increase usability of the property.
I think we should add as part of `include/zephyr/dt-bindings/clock/stm32yy_clock.h` files directly so that all users could benefit.

File: samples/boards/st/mco/src/main.c [hunk 10]
```diff
@@ -7,23 +7,29 @@
 #include <zephyr/kernel.h>
 #include <zephyr/drivers/pinctrl.h>
 
+#if DT_NODE_HAS_STATUS_OKAY(DT_NODELABEL(mco1)) || DT_NODE_HAS_STATUS_OKAY(DT_NODELABEL(mco2))
+const struct device *dev;
```
Comment (erwango) [inline samples/boards/st/mco/src/main.c:11]: Use of a single const dev won't work if both MCO are enabled

**Review by erwango — CHANGES_REQUESTED** [review]
I'd drop the clang commit entirely as most of the changes are bad from readbility/maintainability point of view.

**Review by gautierg-st — CHANGES_REQUESTED** [review]

File: include/zephyr/dt-bindings/clock/stm32c0_clock.h [hunk 11]
```diff
@@ -81,4 +81,23 @@
 #define MCO2_SEL(val)           STM32_MCO_CFGR(val, 0x7, 16, CFGR1_REG)
 #define MCO2_PRE(val)           STM32_MCO_CFGR(val, 0x7, 20, CFGR1_REG)
 
+/* MCO prescaler : division factor */
+#define MCO1_PRE_DIV_1   0
```
Comment (erwango) [inline include/zephyr/dt-bindings/clock/stm32c0_clock.h:85]: Nice. Please also update https://github.com/zephyrproject-rtos/zephyr/blame/main/dts/bindings/clock/st%2Cstm32-clock-mco.yaml

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 12]
```diff
@@ -109,6 +109,11 @@ void config_plli2s(void)
 				       pllm(STM32_PLLI2S_M_DIVISOR),
 				       STM32_PLLI2S_N_MULTIPLIER,
 				       plli2sr(STM32_PLLI2S_R_DIVISOR));
+#elif DT_HAS_COMPAT_STATUS_OKAY(st_stm32f411_plli2s_clock)
+	LL_RCC_PLLI2S_ConfigDomain_I2S(get_pll_source(),
+				       plli2sm(STM32_PLLI2S_M_DIVISOR),
+				       STM32_PLLI2S_N_MULTIPLIER,
+				       plli2sr(STM32_PLLI2S_R_DIVISOR));
 #elif DT_HAS_COMPAT_STATUS_OKAY(st_stm32f412_plli2s_clock)
 	LL_RCC_PLL_ConfigDomain_I2S(get_pll_source(),
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:118]: right, Calling the LL_RCC_PLL_ConfigDomain_I2S(get_pll_source(),  for the stm32f412 compatible was wrong, the PLLI2S configuration is expected here. the  LL_RCC_PLLI2S_ConfigDomain_I2S is needed, with parameter divM, mul N, div R. 
Note that div M is either dedicated PLL I2S M divider for some stm32 devices (ex on stm32f41x)  or the PLL M divider  (ex on stm32f74x)

**Comment by FRASTM** [comment]
add the MCO prescaler : division factor  as common to stm32 series, not defined yet all the stm32 series
Use the same LL_RCC_PLLI2S_ConfigDomain_I2S to configure the PLL I2S, only the div M factor changes depending on the stm32 serie

File: include/zephyr/dt-bindings/clock/stm32c0_clock.h (hunk 11 above)
Comment (FRASTM) [reply include/zephyr/dt-bindings/clock/stm32c0_clock.h:85]: done

File: include/zephyr/dt-bindings/clock/stm32f7_clock.h [hunk 13]
```diff
@@ -82,6 +82,20 @@
...
+#define MCO1_PRE_DIV_2 4
+#define MCO1_PRE_DIV_3 5
+#define MCO1_PRE_DIV_4 6
+#define MCO1_PRE_DIV_5 7
+
+#define MCO2_PRE_DIV_1 0
+#define MCO2_PRE_DIV_2 4
+#define MCO2_PRE_DIV_3 5
+#define MCO2_PRE_DIV_4 6
+#define MCO2_PRE_DIV_5 7
```
Comment (erwango) [inline include/zephyr/dt-bindings/clock/stm32f7_clock.h:97]: Since value is always the same between MCO 1 and MCO 2, lets provide only one set of definitions for each series.
```
#define MCO_PRE_DIV_1 0
#define MCO_PRE_DIV_2 4
#define MCO_PRE_DIV_3 5
#define MCO_PRE_DIV_4 6
#define MCO_PRE_DIV_5 7
```

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/clock_control/clock_stm32_ll_u5.c (hunk 4 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_u5.c]: abandoned

File: drivers/clock_control/clock_stm32_ll_u5.c (hunk 5 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_u5.c]: abandoned

File: drivers/clock_control/clock_stm32_ll_u5.c (hunk 6 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_u5.c]: abandoned

File: samples/boards/st/mco/boards/nucleo_f411re.overlay (hunk 9 above)
Comment (FRASTM) [reply samples/boards/st/mco/boards/nucleo_f411re.overlay]: adding MCO2_PRE_DIV_n for stm32XX_clock.h bindings files

File: samples/boards/st/mco/boards/nucleo_f411re.overlay [hunk 14]
```diff
@@ -0,0 +1,30 @@
...
+/*	clocks = <&rcc STM32_SRC_PLL_P MCO1_SEL(3)>; */
+	prescaler = <MCO1_PRE(4)>; /* set 0b100 in the MCO1PRE of the RCC CFGR */
+	pinctrl-0 = <&rcc_mco_1_pa8>;
+	pinctrl-names = "default";
+	status = "okay";
+};
+
+&mco2 {
+	clocks = <&rcc STM32_SRC_PLLI2S_R MCO2_SEL(1)>;
+	prescaler = <MCO2_PRE(MCO2_PRE_DIV_5)>; /* set 0b111 in the MCO2PRE of the RCC CFGR */
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply samples/boards/st/mco/boards/nucleo_f411re.overlay:26]: comment removed

File: samples/boards/st/mco/boards/nucleo_f411re.overlay [hunk 15]
```diff
@@ -0,0 +1,30 @@
...
+};
+
+/* see RefMan RM0383 */
+&mco1 {
+	/* Select One of the line below for clock source */
+	clocks = <&rcc STM32_SRC_HSI MCO1_SEL(0)>;
+/*	clocks = <&rcc STM32_SRC_LSE MCO1_SEL(1)>; */
+/*	clocks = <&rcc STM32_SRC_HSE MCO1_SEL(2)>; */
+/*	clocks = <&rcc STM32_SRC_PLL_P MCO1_SEL(3)>; */
+	prescaler = <MCO1_PRE(4)>; /* set 0b100 in the MCO1PRE of the RCC CFGR */
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply samples/boards/st/mco/boards/nucleo_f411re.overlay:18]: with <MCO1_PRE(MCO_PRE_DIV_2)>;

File: drivers/clock_control/Kconfig.stm32 [hunk 16]
```diff
@@ -97,310 +97,6 @@ config CLOCK_STM32_MCO
...
-	             SOC_SERIES_STM32H5X || \
-	             SOC_SERIES_STM32H7X || \
-	             SOC_SERIES_STM32H7RSX \
-	           )
-	default 1
-	range 1 5 if SOC_SERIES_STM32F4X || SOC_SERIES_STM32F7X
-	range 1 15 if SOC_SERIES_STM32H7X || SOC_SERIES_STM32H7RSX || SOC_SERIES_STM32H5X
-	help
-	  Prescaler for MCO2 output clock
+	# MCO configuration from DT-based for compiling the MCO driver.
```
Comment (erwango) [inline drivers/clock_control/Kconfig.stm32:100]:
```
	help
	  Allows to output various different clock sources onto the MCO pin using a configurable prescaler.
```

File: samples/boards/st/mco/README.rst [hunk 17]
```diff
@@ -16,6 +16,13 @@ Requirements
 The SoC should support MCO functionality and use a pin that has the MCO alternate function.
 To support another board, add a dts overlay file in boards folder.
 Make sure that the output clock is enabled in dts overlay file.
+Depending on the stm32 serie, several clock source and prescaler are possible for each MCOx.
+The clock source is set by the DTS among the possible values for each stm32 serie.
+The prescaler is set by the DTS, through the property ``prescaler = <MCOx_PRE(MCO_PRE_DIV_n)>;``
+
+See the ``dts/bindings/clock/st,stm32-clock-mco.yaml``.
```
Comment (erwango) [inline samples/boards/st/mco/README.rst:23]:
```suggestion
See :zephyr_file:`dts/bindings/clock/st,stm32-clock-mco.yaml`
```

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: samples/boards/st/mco/README.rst (hunk 17 above)
Comment (FRASTM) [reply samples/boards/st/mco/README.rst:23]: changed

File: drivers/clock_control/Kconfig.stm32 (hunk 16 above)
Comment (FRASTM) [reply drivers/clock_control/Kconfig.stm32]: changed

**Review by erwango — DISMISSED** [review]

**Review by gautierg-st — DISMISSED** [review]

**Comment by erwango** [comment]
@FRASTM Please rebase to fix CI issue

**Comment by FRASTM** [comment]
rebased on 065bd322200ccf2f9d717fd258ec966a522ce733

**Comment by FRASTM** [comment]
rebase on  af68d97507188249e2f9677119fc716a4d04989e

**Review by gautierg-st — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@nordic-krch PTAL

**Comment by fabiobaltieri** [comment]
All changes are in ST specific file, reassigning.

**Comment by fabiobaltieri** [comment]
```
Area matches: {<Area STM32 Platforms>: 20, <Area Drivers: Clock control>: 8, <Area Release Notes>: 1, <Area Samples>: 0}
labels: {'area: Clock control', 'platform: STM32', 'area: Samples', 'Release Notes'}
collab: ['erwango', 'FRASTM', 'gautierg-st', 'GeorgeCGV', 'marwaiehm-st', 'mathieuchopstm', 'nordic-krch', 'fabiobaltieri', 'kartben', 'nashif']
Submitted by: FRASTM
candidate maintainers: {'erwango': 20, 'nordic-krch': 8, 'fabiobaltieri': 1, 'kartben': 1}
Picked assignees: ['nordic-krch'] (27.59% ownership)
```

shrugs
