### PR TITLE
drivers: usb_dc_nrfx: Do not uninit on detach

### LINKED ISSUE #52703: tests: subsys: usb: device: usb.device USAGE FAULT exception
**Describe the bug**
The zephyr/tests/subsys/usb/device/usb.device fails

Observed for
- nrf5340dk_nrf5340_cpuapp
- nrf52840dk_nrf52840

**To Reproduce**
1. have nrf52840dk_nrf52840 J-Link connected and **DO NOT** connect nRF USB
2. go to your zephyr dir
3. call ./scripts/twister -T tests/subsys/usb/device  -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
[2022-11-30T23:52:29.023Z] [0mERROR   - *** Booting Zephyr OS build zephyr-v3.2.0-2123-g14358aee1cda ***[0m
[2022-11-30T23:52:29.023Z] [0mWatchdog sample application[0m
[2022-11-30T23:52:29.023Z] [0mCallback in RESET_SOC disabled for this platform[0m
[2022-11-30T23:52:29.023Z] [0mFeeding watchdog 5 times[0m
[2022-11-30T23:52:29.023Z] [0mFeeding watchdog...[0m
[2022-11-30T23:52:29.023Z] [0mD: __usb_descriptor_start 0x2000012c[0m
[2022-11-30T23:52:29.023Z] [0mD: __usb_descriptor_end 0x2000019d[0m
[2022-11-30T23:52:29.023Z] [0mD: Configuration descriptor 0x2000013e[0m
[2022-11-30T23:52:29.023Z] [0mD: Interface descriptor 0x20000147[0m
[2022-11-30T23:52:29.024Z] [0mD: Endpoint descriptor 0x20000150[0m
[2022-11-30T23:52:29.024Z] [0mD: ep 0x81, mps 64, type 2[0m
[2022-11-30T23:52:29.024Z] [0mD: Fixing EP address 81 -> 81[0m
[2022-11-30T23:52:29.024Z] [0mD: endpoint 0x81[0m
[2022-11-30T23:52:29.024Z] [0mD: Now the wTotalLength is 25[0m
[2022-11-30T23:52:29.024Z] [0mD: idx_max 11, ascii_idx_max 5, buf 0x2000015d[0m
[2022-11-30T23:52:29.024Z] [0mD: char R : 52, idx 5 -> 11[0m
[2022-11-30T23:52:29.024Z] [0mD: char Y : 59, idx 4 -> 9[0m
[2022-11-30T23:52:29.024Z] [0mD: char H : 48, idx 3 -> 7[0m
[2022-11-30T23:52:29.024Z] [0mD: char P : 50, idx 2 -> 5[0m
[2022-11-30T23:52:29.024Z] [0mD: char E : 45, idx 1 -> 3[0m
[2022-11-30T23:52:29.024Z] [0mD: char Z : 5a, idx 0 -> 1[0m
[2022-11-30T23:52:29.024Z] [0mD: idx_max 13, ascii_idx_max 6, buf 0x2000016b[0m
[2022-11-30T23:52:29.024Z] [0mD: char V : 56, idx 6 -> 13[0m
[2022-11-30T23:52:29.024Z] [0mD: char E : 45, idx 5 -> 11[0m
[2022-11-30T23:52:29.024Z] [0mD: char D : 44, idx 4 -> 9[0m
[2022-11-30T23:52:29.024Z] [0mD: char - : 2d, idx 3 -> 7[0m
[2022-11-30T23:52:29.024Z] [0mD: char B : 42, idx 2 -> 5[0m
[2022-11-30T23:52:29.024Z] [0mD: char S : 53, idx 1 -> 3[0m
[2022-11-30T23:52:29.024Z] [0mD: char U : 55, idx 0 -> 1[0m
[2022-11-30T23:52:29.024Z] [0mD: Serial Number[0m
[2022-11-30T23:52:29.024Z] [0mD: 47 5a c4 c0 1d 7e a0 57 |GZ...~.W[0m
[2022-11-30T23:52:29.024Z] [0mD: idx_max 31, ascii_idx_max 15, buf 0x2000017b[0m
[2022-11-30T23:52:29.024Z] [0mD: char 7 : 37, idx 15 -> 31[0m
[2022-11-30T23:52:29.024Z] [0mD: char 5 : 35, idx 14 -> 29[0m
[2022-11-30T23:52:29.024Z] [0mD: char 0 : 30, idx 13 -> 27[0m
[2022-11-30T23:52:29.024Z] [0mD: char A : 41, idx 12 -> 25[0m
[2022-11-30T23:52:29.024Z] [0mD: char E : 45, idx 11 -> 23[0m
[2022-11-30T23:52:29.024Z] [0mD: char 7 : 37, idx 10 -> 21[0m
[2022-11-30T23:52:29.024Z] [0mD: char D : 44, idx 9 -> 19[0m
[2022-11-30T23:52:29.024Z] [0mD: char 1 : 31, idx 8 -> 17[0m
[2022-11-30T23:52:29.024Z] [0mD: char 0 : 30, idx 7 -> 15[0m
[2022-11-30T23:52:29.024Z] [0mD: char C : 43, idx 6 -> 13[0m
[2022-11-30T23:52:29.024Z] [0mD: char 4 : 34, idx 5 -> 11[0m
[2022-11-30T23:52:29.024Z] [0mD: char C : 43, idx 4 -> 9[0m
[2022-11-30T23:52:29.024Z] [0mD: char A : 41, idx 3 -> 7[0m
[2022-11-30T23:52:29.024Z] [0mD: char 5 : 35, idx 2 -> 5[0m
[2022-11-30T23:52:29.024Z] [0mD: char 7 : 37, idx 1 -> 3[0m
[2022-11-30T23:52:29.024Z] [0mD: char 4 : 34, idx 0 -> 1[0m
[2022-11-30T23:52:29.024Z] [0m*** Booting Zephyr OS build zephyr-v3.2.0-2123-g14358aee1cda ***[0m
[2022-11-30T23:52:29.024Z] [0mRunning TESTSUITE device_usb[0m
[2022-11-30T23:52:29.024Z] [0m===================================================================[0m
[2022-11-30T23:52:29.024Z] [0mD: lock usb_enable_lock mutex[0m
[2022-11-30T23:52:29.024Z] [0mD: set cb, ep: 0x81[0m
[2022-11-30T23:52:29.024Z] [0mD: EP enable: 0x00[0m
[2022-11-30T23:52:29.024Z] [0mD: EP enable: 0x80[0m
[2022-11-30T23:52:29.024Z] [0mD: unlock usb_enable_lock mutex[0m
[2022-11-30T23:52:29.024Z] [0mSTART - test_usb_dc_api[0m
[2022-11-30T23:52:29.024Z] [0mPASS - test_usb_dc_api in 0.001 seconds[0m
[2022-11-30T23:52:29.024Z] [0m===================================================================[0m
[2022-11-30T23:52:29.024Z] [0mSTART - test_usb_dc_api_invalid[0m
[2022-11-30T23:52:29.024Z] [0mD: ep_write: ep 0x20, len 1[0m
[2022-11-30T23:52:29.024Z] [0mD: ep_read: ep 0x20, maxlen 1[0m
[2022-11-30T23:52:29.024Z] [0mPASS - test_usb_dc_api_invalid in 0.006 seconds[0m
[2022-11-30T23:52:29.024Z] [0m===================================================================[0m
[2022-11-30T23:52:29.024Z] [0mSTART - test_usb_dc_api_read_write[0m
[2022-11-30T23:52:29.024Z] [0mD: ep_read: ep 0x20, maxlen 1[0m
[2022-11-30T23:52:29.024Z] [0mD: ep_write: ep 0x20, len 1[0m
[2022-11-30T23:52:29.024Z] [0mPASS - test_usb_dc_api_read_write in 0.006 seconds[0m
[2022-11-30T23:52:29.024Z] [0m===================================================================[0m
[2022-11-30T23:52:29.024Z] [0mSTART - test_usb_deconfig[0m
[2022-11-30T23:52:29.024Z] [0mPASS - test_usb_deconfig in 0.001 seconds[0m
[2022-11-30T23:52:29.024Z] [0m===================================================================[0m
[2022-11-30T23:52:29.024Z] [0mSTART - test_usb_disable[0m
[2022-11-30T23:52:29.024Z] [0mD: EP disable: 0x00[0m
[2022-11-30T23:52:29.024Z] [0mD: EP disable: 0x80[0m
[2022-11-30T23:52:29.024Z] [0mE: ***** USAGE FAULT *****[0m
[2022-11-30T23:52:29.024Z] [0mE:   Illegal use of the EPSR[0m
[2022-11-30T23:52:29.024Z] [0mE: r0/a1:  0x20001c1c  r1/a2:  0x00000000  r2/a3:  0x00000006[0m
[2022-11-30T23:52:29.024Z] [0mE: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00008629[0m
[2022-11-30T23:52:29.024Z] [0mE:  xpsr:  0x00000000[0m
[2022-11-30T23:52:29.024Z] [0mE: Faulting instruction address (r15/pc): 0x00000000[0m
[2022-11-30T23:52:29.024Z] [0mE: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0[0m
[2022-11-30T23:52:29.024Z] [0mE: Current thread: 0x200001c8 (test_usb_disable)[0m
[2022-11-30T23:52:29.024Z] [0mE: Halting system[0m
[2022-11-30T23:52:29.024Z] [0m[0m
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.15.1
 - Commit SHA or Version used: zephyr-v3.2.0-2123-g14358aee1cda

### PR DESCRIPTION
**Pull request by desowin**
It is possible for nrfx usbd driver to send NRFX_USBBD_EP_ABORTED during endpoint disable. The event is passed to event handler registered with nrfx_usbd_init(). The nrfx_usbd_uninit() removes the registered event handler, replacing it with NULL. If any event is sent after uninit, the NULL pointer is executed and device crashes.

Do not uninit nrfx usbd driver on detach so it is possible for the usb_disable() to disable all the endpoints.

Fixes: 460ca86527dd ("drivers: usb_dc_nrfx: Always allow endpoint disable")

Fixes: #52703

### CODE REVIEW

File: drivers/usb/device/usb_dc_nrfx.c [hunk 1]
```diff
@@ -1281,11 +1281,14 @@ int usb_dc_attach(void)
 	IRQ_CONNECT(DT_INST_IRQN(0), DT_INST_IRQ(0, priority),
 		    nrfx_isr, nrfx_usbd_irq_handler, 0);
 
-	err = nrfx_usbd_init(usbd_event_handler);
+	if (!nrfx_usbd_is_initialized()) {
+		err = nrfx_usbd_init(usbd_event_handler);
```
Comment (jfischer-no) [inline drivers/usb/device/usb_dc_nrfx.c:1285]: Can it be move to driver's initialization usb_init()?

**Review by jfischer-no — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
