### PR TITLE
Fix MCUboot failed to build on ESP32 platforms

### LINKED ISSUE #74695: MCUboot Zephyr port (--sysbuild) has insufficient .dram0 memory
**Describe the bug**
After recent changes in the Xtensa arch, the MCUboot build fails due to insufficient dram memory.

**To Reproduce**
Build the hello_world sample using any ESP32/ESP32S3 board with the `--sysbuild` flag, to see build process to fail.

**Expected behavior**
The MCUboot should build and load the slot0 application.

**Impact**
Show stopper.

**Additional context**
The CI tests are not catching the build issues.

### PR DESCRIPTION
**Pull request by marekmatej**
The MCUboot is failing during the build on ESP32 and ESP32S3 boards. The reason is the recent changes in Xtensa architecture and the fact that CI didn't catch those changes. That's why we adding the ESP32 platforms to the MCUboot/--sysbuild samples.

Fixes #74695

### CODE REVIEW

**Comment by marekmatej** [comment]
fixing https://github.com/zephyrproject-rtos/zephyr/issues/74695

**Review by LucasTambor — DISMISSED** [review]

**Review by sylvioalves — DISMISSED** [review]

File: soc/espressif/esp32/memory.h [hunk 1]
```diff
@@ -48,7 +48,7 @@
 	(SRAM1_SIZE - ((addr_dram) - SRAM1_DRAM_START) + SRAM1_IRAM_START)
 
 /* For safety margin between bootloader data section and startup stacks */
-#define BOOTLOADER_DRAM_SEG_LEN        0x6400
+#define BOOTLOADER_DRAM_SEG_LEN        0x7000
```
Comment (nordicjm) [inline soc/espressif/esp32/memory.h:51]: Based on https://github.com/zephyrproject-rtos/zephyr/pull/73975#issuecomment-2183348010 having changed something and this only changing to give:
```
        iram_seg:       38960 B        40 KB     95.12%
        dram_seg:       26984 B      27392 B     98.51%
```
This does not enthrill confidence in my to allow this running in CI with such a tiny overhead for the build, any random change could happen with something in the zephyr kernel or anywhere for 408 bytes changing so would prefer these sizes be set larger to prevent this from silently breaking

Comment (marekmatej) [reply soc/espressif/esp32/memory.h]: you are right, I missed that

**Review by nordicjm — DISMISSED** [review]

**Review by sylvioalves — DISMISSED** [review]

**Review by sylvioalves — DISMISSED** [review]

**Review by LucasTambor — DISMISSED** [review]

File: soc/espressif/esp32/default.ld [hunk 2]
```diff
@@ -759,6 +759,7 @@ SECTIONS
   {
     _rodata_start = ABSOLUTE(.);
     _rodata_reserved_start = ABSOLUTE(.);
+    __rom_region_start = ABSOLUTE(.);
```
Comment (tejlmand) [inline soc/espressif/esp32/default.ld:762]: shouldn't there be a `__rom_region_end` somewhere ?
Comment applies to other ld files as well.

**Review by tejlmand — CHANGES_REQUESTED** [review]

File: soc/espressif/esp32/default.ld (hunk 2 above)
Comment (marekmatej) [reply soc/espressif/esp32/default.ld]: Thanks for pointing this out. TBH, those symbols are not used in the ESP32 port. I see them used on other Xtensa platforms, but it states that `__rom_region_start` and `__rom_region_end` delimit text AND data - note, that this is not possible to do in the case of Espressif Xtensa SoCs, because of those addresses are on separate address spaces therefor subtracting them doesn't give you an `__rom_region_size` as one would expect. I set it to delimit the `.flash.text` region in all SoCs.

**Review by sylvioalves — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@tejlmand Please revisit.

**Review by tejlmand — APPROVED** [review]

**Review by LucasTambor — APPROVED** [review]
