### PR TITLE
lib: smf: Fix handled bug causing events to not propagate.

### LINKED ISSUE #81300: SMF smf_set_handled() bug preventing event propagation to parent states.
I think there might be a bug in the Zephyr state machine framework (SMF) that causes `smf_set_handled()` to cause future calls to `smf_run_state()` to not propagate events up the state hierarchy in HSMs in certain situations.

I am using a state hierarchy in where there is a state `S1` which has multiple child states `S1A`, `S1B`, e.t.c. `S1A` calls `smf_set_handled()` on one event, and then a second event comes it to cause the state machine to transition to other child states like `S1B`. At some point the state machine transitions back to `S1A`.

It is here that I've noticed that an event can come in to `S1A`, and the parent state `run()` functions are not called. I am definitely not calling `smf_set_handled()` or `smf_set_state()` in the `s1a_run()` function, thus I'm not handling the event and would expect the parent `run()` functions to be called in backwards order.

Unfortunately the code that causes bug is private and I cannot share it. I tried to recreate a minimal working example but haven't yet been able to trigger the bug (my attempt is here: https://github.com/gbmhunter/zephyr-examples/tree/main/apps/state-machine-framework).

Further evidence that has me thinking this is a bug with the SMF library is that if I modify `zephyr/lib/smf/smf.c` so that `handled` is set to `false` everytime `smf_run_state()` is called, the bug goes away. To me, this seems like a reasonable thing to do, you would expect the `handled` state to be refreshed to `false` on every invocation of `smf_run_state()`.

```c
int32_t smf_run_state(struct smf_ctx *const ctx)
{
	struct internal_ctx *const internal = (void *)&ctx->internal;
	internal->handled = false; // Added this line!!!!!!!!!!!!

	/* No need to continue if terminate was set */
	if (internal->terminate) {
		return ctx->terminate_val;
	}
```

I am running Zephyr `v3.7.0`, the Zephyr SDK `v0.17.0` and building for `native_sim`. Running this on WSL (Ubuntu).

### PR DESCRIPTION
**Pull request by gbmhunter**
When using the SMF for a project discovered that events would sometimes not propagate to parent states correctly. Could not create a minimum reproducable test case for this, but it was found that these changes fixed the bug. This resets the handled and new_state variables on entry to smf_run_state().

Closes #81300.

### CODE REVIEW

**Comment by glenn-andrews** [comment]
Looks like it should work, but I'd prefer to find the root cause of the path where `internal->handled` is not being cleared.

That said, you should be able to remove all the `internal->handled = false;` lines except for the ones that initialize the internal context since this does it in one place.

**Comment by gbmhunter** [comment]
@glenn-andrews agreed, I'll see if I have some time in the next week or two to dig into this further and find the root cause.

**Comment by gbmhunter** [comment]
@glenn-andrews yes that is clean in the sense you only need to do it once and it's guaranteed to be in the correct state when starting. I should have time in the next few days to make those changes.

One other thing that crossed my mind is that I don't think this framework supports transitions in entry/exit functions (i.e. calling `smf_set_state()` from these functions). As such, it might be worth adding some internal state called "set_state_call_count", which if goes above 1 returns an error or asserts (i.e. makes sure smf_set_state() is never called recursively). This should not be part of this MR, but just food for thought.

**Comment by glenn-andrews** [comment]
> As such, it might be worth adding some internal state called "set_state_call_count", which if goes above 1 returns an error or asserts (i.e. makes sure smf_set_state() is never called recursively). This should not be part of this MR, but just food for thought.

This sounds interesting, and yes, transitions on an exit or entry action are not allowed.

The other thing I want to do is replace `smf_set_handled()` with a return code from the run functions, since it is easy to forget to call it and then unintentionally propagate up through the states. I'm working on a diff for that now, but will probably get push-back from everyone whose app falls over.

**Comment by glenn-andrews** [comment]
> As such, it might be worth adding some internal state called "set_state_call_count", which if goes above 1 returns an error or asserts (i.e. makes sure smf_set_state() is never called recursively). This should not be part of this MR, but just food for thought.

One minor problem is internal context needs to be as small as possible for ram-constrained devices, but we could add another flag to the bitfield without changing its length. If you call `smf_set_state()` and the flag is set, then assert.

**Comment by gbmhunter** [comment]
> > As such, it might be worth adding some internal state called "set_state_call_count", which if goes above 1 returns an error or asserts (i.e. makes sure smf_set_state() is never called recursively). This should not be part of this MR, but just food for thought.
> 
> This sounds interesting, and yes, transitions on an exit or entry action are not allowed.
> 
> The other thing I want to do is replace `smf_set_handled()` with a return code from the run functions, since it is easy to forget to call it and then unintentionally propagate up through the states. I'm working on a diff for that now, but will probably get push-back from everyone whose app falls over.

@glenn-andrews that's a good idea. Given how new the SMF is (relatively speaking), even though you would break some stuff I would argue it's worth it for long term benefits. I myself have forgotten about `smf_set_handled()` myself a few times. Return codes are harder to ignore. Presumably, if you called `smf_set_state()` in the event handler it would ignore the return value, even if `NOT_HANDLED` was returned?

I have my own HSM framework in which I am experimenting with the idea of allowing `set_state()` to be called in entry and exit functions. The specific use case I want is to be able to implement entry guards, and rather than add the same guard logic to all possible source states that could initiate the transition, just add the entry guard to the entry function of the destination state. When allowing this though, you have design `set_state()` to work recursively, and also explicitly define whether a state's entry/exit functions will be called when a `set_state()` is called in a transition guard. I hopefully choose some intuitive defaults for these cases, which are explained at https://github.com/gbmhunter/NinjaHSM if you are interested. I'm interested if you think this would be worth implementing for this library, or it doesn't add enough value (or departs too far away from what is considered best practice!).

**Comment by glenn-andrews** [comment]
> Presumably, if you called `smf_set_state()` in the event handler it would ignore the return value, even if `NOT_HANDLED` was returned?

Correct. `smf_execute_ancestor_run_actions()` returns early if `internal->new_state` or `internal->handled` is set.

> The specific use case I want is to be able to implement entry guards, and rather than add the same guard logic to all possible source states that could initiate the transition, just add the entry guard to the entry function of the destination state. 

I think if you need entry guards like that, you probably have a malformed state machine. Given your `LAUNCH` example, it should only be accessible from a `READY_TO_LAUNCH` state, and any event that makes the system unready should take you back into an `ABORT` state or other appropriate handler (e.g. `SCE_TO_AUX`). I do get that was a trivial example, though.

UML does allow transitions in exit actions, which SMF doesn't handle and probably could be made to do. I don't know how important it is, though to do so.

**Comment by gbmhunter** [comment]
> I think if you need entry guards like that, you probably have a malformed state machine. Given your `LAUNCH` example, it should only be accessible from a `READY_TO_LAUNCH` state, and any event that makes the system unready should take you back into an `ABORT` state or other appropriate handler (e.g. `SCE_TO_AUX`). I do get that was a trivial example, though.
> 
> UML does allow transitions in exit actions, which SMF doesn't handle and probably could be made to do. I don't know how important it is, though to do so.

The problem I have found with things like a  `READY_TO_LAUNCH` state is that you may only need to check some things in a synchronous manner and not wait for any event. In that case, how do you perform the checks? You cannot check things and transition in the entry to READY_TO_LAUNCH, so you end up having to create a "dummy" event which fires immediately after entry and runs the states event handler function. This doesn't feel like a tidy solution. A general rule I have is to only make states for things which the state machine can reside in for a non-zero amount of time (ignoring processing time of course...i.e. things that need a external event to continue). I'm not sure it makes sense to have states for things which enter and immediately transition somewhere else without the need for any external event.

**Comment by glenn-andrews** [comment]
> The problem I have found with things like a `READY_TO_LAUNCH` state is that you may only need to check some things in a synchronous manner and not wait for any event. In that case, how do you perform the checks? 

Can the synchronous checks be replaced by events when the items being checked change?

Lots of state variables and guard conditions is an HSM 'code smell'.

**Comment by glenn-andrews** [comment]
Either way, I agree with resetting all the state variables in at the beginning of `smf_run_state()`

**Comment by gbmhunter** [comment]
> Can the synchronous checks be replaced by events when the items being checked change?
> 
> Lots of state variables and guard conditions is an HSM 'code smell'.

Sometimes it doesn't make sense to have an event on change, but just a check when entering a specific state. But regardless, you've provided some got ideas I'll muse over. Regarding the changes relevant to this MR, I'm still hoping to do them soon.

**Comment by glenn-andrews** [comment]
> Regarding the changes relevant to this MR, I'm still hoping to do them soon.

Agreed. Will you have time to update the MR with the suggestions soon? I think I'm good with the plan.

File: lib/smf/smf.c [hunk 1]
```diff
@@ -384,6 +394,11 @@ int32_t smf_run_state(struct smf_ctx *const ctx)
 {
 	struct internal_ctx *const internal = (void *)&ctx->internal;
 
+	/* Executing a states run function could cause a transition, so clear the
+	 * internal state to ensure that the transition is handled correctly.
+	 */
+	smf_clear_internal_state(ctx);
```
Comment (glenn-andrews) [inline lib/smf/smf.c:400]: This has to happen after lines 403-405 since you're nuking the `internal->terminate` field used in the test.

**Review by glenn-andrews — CHANGES_REQUESTED** [review]

File: lib/smf/smf.c [hunk 2]
```diff
@@ -277,6 +285,8 @@ void smf_set_state(struct smf_ctx *const ctx, const struct smf_state *new_state)
 		return;
 	}
 
+	smf_clear_internal_state(ctx);
```
Comment (glenn-andrews) [inline lib/smf/smf.c:288]: I don't think this belongs in `smf_set_state()`.

Were you experiencing issues if you leave it out?

Comment (gbmhunter) [reply lib/smf/smf.c:288]: Woops, no sorry I added it in there thinking it would be a good idea, but I only need it in `smf_run_state()` to fix the bug. I'll remove this.

File: lib/smf/smf.c (hunk 1 above)
Comment (gbmhunter) [reply lib/smf/smf.c:400]: Good catch!

**Review by glenn-andrews — APPROVED** [review]
LGTM

**Review by sambhurst — DISMISSED** [review]

File: lib/smf/smf.c [hunk 3]
```diff
@@ -209,6 +204,22 @@ static bool smf_execute_all_exit_actions(struct smf_ctx *const ctx, const struct
...
+
+	internal->is_exit = false;
+	internal->terminate = false;
+	internal->handled = false;
+	internal->new_state = false;
+}
+
 void smf_set_initial(struct smf_ctx *ctx, const struct smf_state *init_state)
 {
 	struct internal_ctx *const internal = (void *)&ctx->internal;
```
Comment (glenn-andrews) [inline lib/smf/smf.c:225]: This is causing an unused variable error.

**Review by glenn-andrews — CHANGES_REQUESTED** [review]

**Review by glenn-andrews — DISMISSED** [review]

**Review by glenn-andrews — APPROVED** [review]

**Comment by glenn-andrews** [comment]
Ping @sambhurst

**Review by keith-zephyr — APPROVED** [review]

**Comment by glenn-andrews** [comment]
Can we get this merged before https://github.com/zephyrproject-rtos/zephyr/pull/83854 ?

**Comment by gbmhunter** [comment]
@glenn-andrews yes this MR has been hanging around for a while. What needs to happen next?

**Comment by glenn-andrews** [comment]
I'm not authorized to merge it. I assume that's the responsibility of @sambhurst

**Comment by keith-zephyr** [comment]
> I'm not authorized to merge it. I assume that's the responsibility of @sambhurst

@sambhurst is the assignee and needs to approve the PR.  Then someone from the release team will merge it.

**Review by sambhurst — APPROVED** [review]
