### PR TITLE
drivers: ethernet: eth_mcux: fix phy_event state diagram sequence

### LINKED ISSUE #56654: eth_mcux: phy event state diagram starts eth_mcux_phy_state_read_duplex without iface
When initalizing the eth_mcux driver, it does not switch correctly between the different states of the eth_mcux_phy_event state diagram. This will cause the Ethernet functionality to not work correctly.

When the state diagram ends up in the eth_mcux_phy_state_read_status case, the eth carrier is enabled. However, this step only happens when an interface is available in the context. This can be seen in the code snippet below:
```
context->link_up = link_up;
context->phy_state = eth_mcux_phy_state_read_duplex;

/* Network interface might be NULL at this point */
if (context->iface) {
    net_eth_carrier_on(context->iface);
    k_msleep(USEC_PER_MSEC);
}
```

Regardless of the state of the iface, the state machine will switch to eth_mcux_phy_state_read_duplex in the next iteration. Thus, the states diagram never returns to the previous state. As a result, the eth carrier will never be enabled in the future.

To reproduce the problem I used a custom mimxrt1064 board. Note that the lan8720a eth phy is used as opposed to the evk where a ksz8081 is used. I could not reproduce the problem on the evk. I used the dhcpv4_client sample.

The issue occurs for example when certain configurations are enabled. In my case, I enabled the following configurations to reproduce the problem:

```
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME_UNIQUE=y
CONFIG_NET_HOSTNAME="hostname"

CONFIG_MDNS_RESPONDER=y
CONFIG_MDNS_RESPONDER_DNS_SD=y
CONFIG_DNS_SD=y
```

Note that enabling certain drivers could also cause the problem. By enabling debug logging, I obtained the results below. I added additional logging when the iface is assigned to the context ("eth_iface_init") in the eth_iface_init function.

```
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_start: ETH_0 phy_state=initial
[00:00:00.500,000] <dbg> eth_mcux: eth_init: ethernet@402d8000 MAC 02:04:9f:09:1e:6f
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=initial
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=reset
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=autoneg
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=restart
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=read-status
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=read-duplex
[00:00:00.500,000] <inf> eth_mcux: ETH_0 enabled 100M full-duplex mode.
[00:00:00.501,000] <err> eth_mcux: eth_iface_init
*** Booting Zephyr OS build zephyr-v3.3.0 ***
[00:00:00.501,000] <wrn> net_if: iface 0x20200bf0 is down
[00:00:00.501,000] <inf> net_dhcpv4_client_sample: Run dhcpv4 client
```

The logging shows that the read-duplex step is already executed before eth_iface_init. Since no interface is available at the time of read status, as already mentioned above, no eth carrier will be enabled.

The desired behavior occurs when the above configurations are not enabled. Here one can see that the order is correct:

```
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_start: ETH_0 phy_state=initial
[00:00:00.500,000] <dbg> eth_mcux: eth_init: ethernet@402d8000 MAC 02:04:9f:09:1e:6f
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=initial
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=reset
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=autoneg
[00:00:00.500,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=restart
[00:00:00.500,000] <err> eth_mcux: eth_iface_init
[00:00:00.501,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=read-status
*** Booting Zephyr OS build zephyr-v3.3.0 ***
[00:00:00.501,000] <inf> net_dhcpv4_client_sample: Run dhcpv4 client
[00:00:01.501,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=read-duplex
[00:00:01.501,000] <inf> eth_mcux: ETH_0 enabled 100M full-duplex mode.
[00:00:02.501,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=wait
[00:00:02.501,000] <dbg> eth_mcux: eth_mcux_phy_event: ETH_0 phy_state=read-status
```

Presumably the problem occurs because the additional (mdns) functionality slows down the init function slightly and thus results in the timing problem. I think the fact that this is not reproducible on the evk is explained by the different eth phy model. This one is possibly slightly slower so the read state will be executed later and thus no timing problems occur.

**Environment**
 - OS: Linux
 - Toolchain: Zephyr SDK

### PR DESCRIPTION
**Pull request by IVandeVeire**
When the phy_event state diagram ends up in the eth_mcux_phy_state_read_status case, the eth carrier is enabled. However, this step only happens when an interface is available in the context. 

Regardless of the state of the iface, the state machine will switch to eth_mcux_phy_state_read_duplex in the next iteration. Thus, the states diagram never returns to the previous state. As a result, the eth carrier will never be enabled in the future.

This problem is fixed by only changing to the next state if the interface is available.

Fixes: #56654

### CODE REVIEW

File: drivers/ethernet/eth_mcux.c [hunk 1]
```diff
@@ -555,16 +555,12 @@ static void eth_mcux_phy_event(struct eth_context *context)
...
 			context->link_up = link_up;
 			context->phy_state = eth_mcux_phy_state_read_duplex;
-
-			/* Network interface might be NULL at this point */
-			if (context->iface) {
-				net_eth_carrier_on(context->iface);
-				k_msleep(USEC_PER_MSEC);
-			}
+			net_eth_carrier_on(context->iface);
+			k_msleep(1);
```
Comment (danieldegrasse) [inline drivers/ethernet/eth_mcux.c:559]: I'm not sure the entire delay of 1 second is needed here, but I have some reservations about changing this delay from
1 second to 1 ms. The original introduction of this delay was in #12465, so it does seem it solved an issue at the time. Is there a reason you reduced this delay value?

Comment (pdgendt) [reply drivers/ethernet/eth_mcux.c:559]: Hey @danieldegrasse, the delay you are referring to was already 1 ms. It was in (wrongly) set to 1 second in #24864.

Comment (danieldegrasse) [reply drivers/ethernet/eth_mcux.c:559]: Ah ok, I didn't realize `k_sleep` could a timeout in microseconds (maybe it could at that point in Zephyr's history). In that case, glad we fixed this up.

**Review by danieldegrasse — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
@IVandeVeire thank you for the contribution
