### PR TITLE
Bluetooth: L2CAP: Queue packets when a segment could not be allocated

### LINKED ISSUE #20640: Bluetooth: l2cap do not recover when faced with long packets and run out of buffers
**Describe the bug**
l2cap do not recover when faced with long packets and runs out of buffers. Discovered while testing hci_usb with IPSP sample. After ping with long payload or short intervals the IPSP device remains unresponsive (does not recover / not respond anymore).

If the [l2cap_chan_le_send_sdu](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/l2cap.c#L1891) returns EAGAIN and the buffer is queued and then in [l2cap_chan_le_send_resume](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/l2cap.c#L1304) the same situation happens again because the l2cap_chan_le_send_sdu() and subsequent calls of
l2cap_chan_le_send()->
l2cap_chan_create_seg()->
l2cap_alloc_seg()->
bt_l2cap_create_pdu() **fail** (with _bt_conn: Unable to allocate buffer_), the device remains unresponsive or not recover even if the host stops sending data. l2cap also do not try l2cap_chan_le_send_resume() again.

**To Reproduce**
Build, flash, connect to IPSP sample, try `ping -i 0,3 -s 512 2001:db8::1` or `ping -i 1 -s 1024 2001:db8::1`

**Expected behavior**
The device should recover after ping flood, even if it does not have enough buffer for the data.

**console output**
```
[00:01:26.327,941] <dbg> bt_l2cap.l2cap_chan_le_send_resume: buf 0x20009f90 sent 113                     
[00:01:26.327,972] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x20009f58 len 10             
[00:01:26.328,002] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 10 credits 50         
[00:01:26.328,033] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 10                        
[00:01:26.328,063] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x20009f90 len 23             
[00:01:26.328,094] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 49         
[00:01:26.328,125] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23                        
[00:01:26.328,155] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x20009fe4 len 23     
[00:01:26.328,186] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 48         
[00:01:26.328,216] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23                        
[00:01:26.328,247] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x2000a070 len 23           
[00:01:26.328,277] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 47         
[00:01:26.328,308] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23                        
[00:01:26.328,338] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x2000a08c len 23
[00:01:26.328,369] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 46
[00:01:26.328,369] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23
[00:01:26.328,430] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x2000a0a8 len 23
[00:01:26.328,460] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 45
[00:01:26.328,460] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23
[00:01:26.328,521] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x2000a0c4 len 13
[00:01:26.328,521] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 13 credits 44
[00:01:26.328,552] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 13
[00:01:26.328,613] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x2000a054 len 23
[00:01:26.328,643] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 43
[00:01:26.328,643] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23
[00:01:26.328,704] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x20009f20 len 23
[00:01:26.328,704] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 42
[00:01:26.328,735] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23
[00:01:26.328,796] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x20009ecc len 23
[00:01:26.328,796] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 41
[00:01:26.328,826] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23
[00:01:26.328,857] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x20009654 len 23
[00:01:26.328,887] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 40
[00:01:26.328,918] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23
[00:01:26.328,948] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x2000961c len 23
[00:01:26.328,979] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 39
[00:01:26.328,979] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23
[00:01:26.329,040] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x20009638 len 13
[00:01:26.329,071] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 13 credits 38
[00:01:26.329,071] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 13
[00:01:26.329,132] <dbg> bt_l2cap.l2cap_chan_create_seg: ch 0x2000d18c seg 0x20009f74 len 23
[00:01:26.329,132] <dbg> bt_l2cap.l2cap_chan_le_send: ch 0x2000d18c cid 0x0040 len 23 credits 37
[00:01:26.329,162] <dbg> bt_l2cap.bt_l2cap_send_cb: conn 0x20000698 cid 64 len 23
[00:01:26.329,193] <wrn> bt_conn: Unable to allocate buffer with K_NO_WAIT
[00:01:26.329,193] <wrn> bt_conn: Unable to allocate buffer: timeout -1
[00:01:27.971,221] <dbg> bt_l2cap.bt_l2cap_recv: Packet for CID 64 len 22
[00:01:27.971,282] <dbg> bt_l2cap.l2cap_rx_process: chan 0x2000d18c buf 0x20009590
[00:01:27.971,313] <dbg> bt_l2cap.l2cap_chan_le_recv: chan 0x2000d18c len 20 sdu_len 20
[00:01:27.971,313] <dbg> net_bt.ipsp_alloc_buf: (0x20002de0): Channel 0x2000d18c requires buffer
[00:01:27.971,343] <dbg> bt_l2cap.l2cap_chan_le_recv_seg: chan 0x2000d18c seg 1 len 20
[00:01:27.971,374] <dbg> bt_l2cap.l2cap_chan_le_recv_sdu: chan 0x2000d18c len 20
```

### PR DESCRIPTION
**Pull request by Vudentz**
When a segment could not be allocated it should be possible to resume
sending it later once previous segments complete, the only exception is
when there is no previous activity and we are unable to alocate even the
very first segment which should indicate to the caller that it would
block since that only happens on syswq the caller might need to defer to
another thread or resubmit the work.

Fixes #20640

Patch grow a little bit big but the overall impact in memory is quite small:

IPSP sample board=qemu_x86

Before:

make ram_report

    l2                                                                                   392     0.35%
      bluetooth                                                                          392     0.35%
        bluetooth.c                                                                      392     0.35%
          __config_net_bt                                                                 12     0.01%
          __device_net_bt                                                                 12     0.01%
          __net_if_dev_net_bt_0                                                           28     0.02%
          __net_if_net_bt_0                                                               32     0.03%
          __net_l2_data_net_bt0                                                            4     0.00%
          bt_context_data                                                                228     0.20%
          bt_if_api                                                                        4     0.00%
          conn_callbacks                                                                  28     0.02%
          default_conn                                                                     4     0.00%
          ipsp_ops                                                                        28     0.02%
          server                                                                          12     0.01%

make rom_report

    l2                                                                                  1419     0.47%
      bluetooth                                                                         1419     0.47%
        bluetooth.c                                                                     1419     0.47%
          __config_net_bt                                                                 12     0.00%
          __device_net_bt                                                                 12     0.00%
          __net_if_dev_net_bt_0                                                           28     0.01%
          __net_if_net_bt_0                                                               32     0.01%
          __net_l2_data_net_bt0                                                            4     0.00%
          ad                                                                              16     0.01%
          bt_advertise                                                                   106     0.04%
          bt_context_data                                                                228     0.08%
          bt_if_api                                                                        4     0.00%
          bt_iface_init                                                                   27     0.01%
          conn_callbacks                                                                  28     0.01%
          connected                                                                       46     0.02%
          disconnected                                                                    32     0.01%
          ipsp_accept                                                                     40     0.01%
          ipsp_alloc_buf                                                                  16     0.01%
          ipsp_connected                                                                 247     0.08%
          ipsp_disconnected                                                               47     0.02%
          ipsp_ops                                                                        28     0.01%
          ipsp_recv                                                                      115     0.04%
          net_bt_enable                                                                   35     0.01%
          net_bt_flags                                                                     3     0.00%
          net_bt_get_conn                                                                 17     0.01%
          net_bt_init                                                                     30     0.01%
          net_bt_recv                                                                     23     0.01%
          net_bt_send                                                                    117     0.04%
          net_mgmt_NET_REQUEST_BT_ADVERTISE                                              106     0.04%
          sd                                                                               8     0.00%
          server                                                                          12     0.00%
          
After:

make ram_report

    l2                                                                                   404     0.36%
      bluetooth                                                                          404     0.36%
        bluetooth.c                                                                      404     0.36%
          __config_net_bt                                                                 12     0.01%
          __device_net_bt                                                                 12     0.01%
          __net_if_dev_net_bt_0                                                           28     0.02%
          __net_if_net_bt_0                                                               32     0.03%
          __net_l2_data_net_bt0                                                            4     0.00%
          bt_context_data                                                                240     0.21%
          bt_if_api                                                                        4     0.00%
          conn_callbacks                                                                  28     0.02%
          default_conn                                                                     4     0.00%
          ipsp_ops                                                                        28     0.02%
          server                                                                          12     0.01%

make rom_report

    l2                                                                                  1446     0.48%
      bluetooth                                                                         1446     0.48%
        bluetooth.c                                                                     1446     0.48%
          __config_net_bt                                                                 12     0.00%
          __device_net_bt                                                                 12     0.00%
          __net_if_dev_net_bt_0                                                           28     0.01%
          __net_if_net_bt_0                                                               32     0.01%
          __net_l2_data_net_bt0                                                            4     0.00%
          ad                                                                              16     0.01%
          bt_advertise                                                                   106     0.04%
          bt_context_data                                                                240     0.08%
          bt_if_api                                                                        4     0.00%
          bt_iface_init                                                                   27     0.01%
          conn_callbacks                                                                  28     0.01%
          connected                                                                       46     0.02%
          disconnected                                                                    32     0.01%
          ipsp_accept                                                                     40     0.01%
          ipsp_alloc_buf                                                                  16     0.01%
          ipsp_connected                                                                 247     0.08%
          ipsp_disconnected                                                               47     0.02%
          ipsp_ops                                                                        28     0.01%
          ipsp_recv                                                                      115     0.04%
          net_bt_enable                                                                   35     0.01%
          net_bt_flags                                                                     3     0.00%
          net_bt_get_conn                                                                 17     0.01%
          net_bt_init                                                                     30     0.01%
          net_bt_recv                                                                     23     0.01%
          net_bt_send                                                                    132     0.04%
          net_mgmt_NET_REQUEST_BT_ADVERTISE                                              106     0.04%
          sd                                                                               8     0.00%
          server                                                                          12     0.00%

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

**Comment by Vudentz** [comment]
This is still crashing so more work is needed.

**Comment by joerchan** [comment]
@Vudentz Is this a continuation #20544 ?

**Comment by Vudentz** [comment]
@jfischer-phytec-iot With this set I was able to ping -s 1024, Ive also added some tunning so it doesn't take forever to reply at the cost of increasing our frag_pool when NET_L2_BT is set.

**Comment by jfischer-phytec-iot** [comment]
@Vudentz thanks, looks better. It does not lock anymore. I will test it for a while.

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -53,8 +53,13 @@ NET_BUF_POOL_DEFINE(acl_tx_pool, CONFIG_BT_L2CAP_TX_BUF_COUNT,
  * are queued up in the TX queue. In such a situation, trying to allocate
  * another buffer from the acl_tx_pool would result in a deadlock.
  */
+#if defined(CONFIG_BT_L2CAP_DYNAMIC_CHANNEL)
+NET_BUF_POOL_DEFINE(frag_pool, CONFIG_BT_L2CAP_TX_FRAG_COUNT, FRAG_SIZE,
+		    BT_BUF_USER_DATA_MIN, NULL);
+#else
 NET_BUF_POOL_FIXED_DEFINE(frag_pool, CONFIG_BT_L2CAP_TX_FRAG_COUNT, FRAG_SIZE,
 			  NULL);
+#endif /* CONFIG_BT_L2CAP_DYNAMIC_CHANNEL */
```
Comment (jhedberg) [inline subsys/bluetooth/host/conn.c]: What's the difference here? `NET_BUF_POOL_DEFINE()` is the same as `NET_BUF_POOL_FIXED_DEFINE()` in fact, you shouldn't use `NET_BUF_POOL_DEFINE()` anymore as it's essentially deprecated (even though it might not be formally marked so).

**Review by jhedberg — DISMISSED** [review]

File: subsys/bluetooth/host/conn.c (hunk 1 above)
Comment (Vudentz) [reply subsys/bluetooth/host/conn.c]: It was just for setting user_data size, the fixed does seem to take the user_data size.

Comment (jhedberg) [reply subsys/bluetooth/host/conn.c]: Take a look at the actual definition. All it does with it is a build assert. Ensuring the BT_BUF_USER_DATA_MIN is already covered by `range 8 65535 if BT` in `subsys/net/Kconfig`

Comment (jhedberg) [reply subsys/bluetooth/host/conn.c]: If that still wasn't clear: since quite a while ago all net_buf objects share the same user data size that gets set using `CONFIG_NET_BUF_USER_DATA_SIZE`. I.e. you can't set it per-pool

Comment (Vudentz) [reply subsys/bluetooth/host/conn.c]: Ok now I realize that it doesn't actually assume a 0 size with fixed version, will fix that.

Comment (Vudentz) [reply subsys/bluetooth/host/conn.c]: Fixed.

**Comment by jfischer-phytec-iot** [comment]
@Vudentz 7ce7658c936e688f9fac3dd05de94d43c017940e does not survive flood like `ping -i 0.02 -s 82 2001:db8::1`, looks like deadlock.  (Previous version 21746b4c8a0e66b3ea96d391576058d2c17e3e71 disconnected during flood after `bt_l2cap_chan_disconnect(&chan->chan) `)

The test which must be passed:
```bash
#!/bin/bash

IP=$1

for (( n=0; n<1; n++ ))
do
        for (( packetsize=0; packetsize<1500; packetsize=$packetsize+1 ))
        do
                echo "payload $packetsize"
                ping6 -w 1 -i 0.002 -c 100 -s $packetsize -q $IP
        done
done

```

**Comment by Vudentz** [comment]
> @Vudentz [7ce7658](https://github.com/zephyrproject-rtos/zephyr/commit/7ce7658c936e688f9fac3dd05de94d43c017940e) does not survive flood like `ping -i 0.02 -s 82 2001:db8::1`, looks like deadlock. (Previous version [21746b4](https://github.com/zephyrproject-rtos/zephyr/commit/21746b4c8a0e66b3ea96d391576058d2c17e3e71) disconnected during flood after `bt_l2cap_chan_disconnect(&chan->chan) `)
> 
> The test which must be passed:
> 
> ```shell
> #!/bin/bash
> 
> IP=$1
> 
> for (( n=0; n<1; n++ ))
> do
>         for (( packetsize=0; packetsize<1500; packetsize=$packetsize+1 ))
>         do
>                 echo "payload $packetsize"
>                 ping6 -w 1 -i 0.002 -c 100 -s $packetsize -q $IP
>         done
> done
> ```

So I managed to fix the lockup, though sometimes I experience crashes with qemu which I don't experience with native_posix, the backtrace points to buf.c:207 so I guess it is some sort of corruption.

**Comment by Vudentz** [comment]
> So I managed to fix the lockup, though sometimes I experience crashes with qemu which I don't experience with native_posix, the backtrace points to buf.c:207 so I guess it is some sort of corruption.

Fixes these issues, the channel will now shutdown and eventually be disconnected if credits cannot be sent due to congestion caused by flooding.

**Comment by Vudentz** [comment]
Depends on https://github.com/zephyrproject-rtos/zephyr/pull/20951

**Comment by jhedberg** [comment]
@Vudentz could you please rebase this?

File: subsys/bluetooth/host/l2cap.c [hunk 2]
```diff
@@ -376,6 +382,10 @@ static struct net_buf *l2cap_create_le_sig_pdu(struct net_buf *buf,
 					       u16_t len)
 {
 	struct bt_l2cap_sig_hdr *hdr;
+	struct net_buf_pool *pool = NULL;
+
+	if (code == BT_L2CAP_DISCONN_REQ)
+		pool = &disc_pool;
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: missing {}

File: subsys/bluetooth/host/l2cap.c [hunk 3]
```diff
@@ -376,6 +382,10 @@ static struct net_buf *l2cap_create_le_sig_pdu(struct net_buf *buf,
...
 
 	/* Don't wait more than the minimum RTX timeout of 2 seconds */
 	buf = bt_l2cap_create_pdu_timeout(NULL, 0, K_SECONDS(2));
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: Did you intend to pass `pool` here? The variable seems unused otherwise.

File: subsys/bluetooth/host/l2cap.c [hunk 4]
```diff
@@ -1692,6 +1692,19 @@ static void l2cap_chan_le_recv(struct bt_l2cap_le_chan *chan,
...
 }
+
+static void l2cap_chan_recv_queue(struct bt_l2cap_le_chan *chan,
+				  struct net_buf *buf)
+{
+	if (chan->chan.state == BT_L2CAP_DISCONNECT) {
+		BT_WARN("Ignoring data received while disconnecting");
+		net_buf_unref(buf);
+		return;
+	}
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: Don't we want this check somewhere earlier and applied also the fixed channels?

File: subsys/bluetooth/host/l2cap.c [hunk 5]
```diff
@@ -50,6 +50,12 @@
 #define L2CAP_CONN_TIMEOUT	K_SECONDS(40)
 #define L2CAP_DISC_TIMEOUT	K_SECONDS(2)
 
+/* Dedicated pool for disconnect buffers so they are guaranteed to be send
+ * even in case of data congestion due to flooding.
+ */
+NET_BUF_POOL_FIXED_DEFINE(disc_pool, 1,
+			  BT_L2CAP_BUF_SIZE(CONFIG_BT_L2CAP_TX_MTU), NULL);
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: Does this really guarantee allocation success? Remember that the bt_conn_tx allocation is something that can also fail if any sending is done from the sys wq.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/l2cap.c (hunk 3 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Will fix it.

File: subsys/bluetooth/host/l2cap.c (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Will fix.

File: subsys/bluetooth/host/l2cap.c (hunk 5 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Now that we are using RX thread for fixed channels this might not be necessary since we block with K_FOREVER.

Comment (jhedberg) [reply subsys/bluetooth/host/l2cap.c]: I guess it depends where the disconnect request is sent from. What context is that, and are there multiple possibilities? Only the server-side is run through the RX thread. Is that what you were trying to fix? I suppose the client side is completely application-dependent, i.e. what context a disconnection is requested from.

Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Right, I was thinking just about the signalling but you are right the application can call it in any context, including on syswq.

File: subsys/bluetooth/host/l2cap.c (hunk 4 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Fixed channels are never in disconnect, they are either connected or disconnected.

File: subsys/bluetooth/host/l2cap.c [hunk 6]
```diff
@@ -1295,15 +1293,20 @@ static int l2cap_chan_le_send(struct bt_l2cap_le_chan *ch, struct net_buf *buf,
...
 	}
 
-	if (ret) {
-		BT_WARN("Unable to send seg: %d",  ret);
-		k_sem_give(&ch->tx.credits);
+	/* Channel may have been disconnected while sending */
+	if (!ch->chan.conn) {
+		net_buf_unref(seg);
+		return -ECONNRESET;
+	}
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: This looks weird. At this point you haven't checked the return value of `bt_l2cap_send_cb()` yet you assume this code still owns the reference?

Btw, this logic seems to go against what we discussed on slack (to be fair though I didn't see you comment on the issue there): we need to establish a consistent behaviour across all APIs when it comes to buffer ownership and errors. My proposal was that APIs taking buffers would always assume ownership of them, so if the calling code doesn't care about errors (e.g. can't do anything useful with them) it doesn't have to check them. This would mean that if the calling code wants to retain a reference (e.g. for retransmission attempts) it needs to do net_buf_ref first.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/l2cap.c [hunk 7]
```diff
@@ -724,13 +724,54 @@ static void l2cap_chan_rx_init(struct bt_l2cap_le_chan *chan)
...
+		int sent = data_sent(buf)->len;
+
+		BT_DBG("buf %p sent %u", buf, sent);
+
+		sent = l2cap_chan_le_send_sdu(ch, &buf, sent);
+		if (sent < 0) {
+			if (sent == -EAGAIN) {
+				ch->tx_buf = buf;
+			}
+			break;
```
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: bt_conn_send_cb would unref it if it fails to send.

File: subsys/bluetooth/host/l2cap.c [hunk 8]
```diff
@@ -61,6 +61,12 @@
 #define l2cap_lookup_ident(conn, ident) __l2cap_lookup_ident(conn, ident, false)
 #define l2cap_remove_ident(conn, ident) __l2cap_lookup_ident(conn, ident, true)
 
+struct data_sent {
+	int len;
```
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: I thought I did change it to u16_t, maybe I did not rebase it.

File: subsys/bluetooth/host/l2cap.c (hunk 6 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Right it should have unref it on bt_conn_send_cb since that is checking the state of the connection, though when sending the original buffer an extra reference is done by create_seg, I can fix that so that we always make a reference to the original buffer before creating a segment.

File: subsys/bluetooth/host/l2cap.c (hunk 5 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Yes, it does because the flooding still causes the credits to fail so we have to shutdown and disconnect.

File: subsys/bluetooth/host/l2cap.c [hunk 9]
```diff
@@ -376,9 +382,14 @@ static struct net_buf *l2cap_create_le_sig_pdu(struct net_buf *buf,
...
 	struct bt_l2cap_sig_hdr *hdr;
+	struct net_buf_pool *pool = NULL;
+
+	if (code == BT_L2CAP_DISCONN_REQ) {
+		pool = &disc_pool;
+	}
 
 	/* Don't wait more than the minimum RTX timeout of 2 seconds */
-	buf = bt_l2cap_create_pdu_timeout(NULL, 0, K_SECONDS(2));
+	buf = bt_l2cap_create_pdu_timeout(pool, 0, K_SECONDS(2));
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: Unrelated to this patch since it doesn't change it, but there's `#define L2CAP_DISC_TIMEOUT	K_SECONDS(2)` higher up in this file which should probably be used? Or is that for something else?

File: subsys/bluetooth/host/l2cap.c [hunk 10]
```diff
@@ -1201,14 +1250,14 @@ void l2cap_chan_seg_sent(struct bt_conn *conn, void *user_data)
...
-	l2cap_chan_le_send_resume(BT_L2CAP_LE_CHAN(chan));
+	l2cap_chan_tx_resume(BT_L2CAP_LE_CHAN(chan));
 }
 
 static int l2cap_chan_le_send(struct bt_l2cap_le_chan *ch, struct net_buf *buf,
 			      u16_t sdu_hdr_len)
 {
 	struct net_buf *seg;
-	int len;
+	int len, ret;
```
Comment (jhedberg) [inline subsys/bluetooth/host/l2cap.c]: Why `ret` instead of `err`? Don't we use `err` everywhere else?

Comment (jhedberg) [reply subsys/bluetooth/host/l2cap.c]: .. I can see some other use of `ret` in other "send" functions though

File: subsys/bluetooth/host/l2cap.c (hunk 9 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: That is something else, this applies to all the L2CAP signalling not a specific PDU.

File: subsys/bluetooth/host/l2cap.c (hunk 10 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: No specific reason, I could rename it if that matters to you.

**Comment by jhedberg** [comment]
@jfischer-phytec-iot it be good if you could test the latest version of this PR, especially since we're still considering it for inclusion to the 2.1 release.

File: subsys/bluetooth/host/l2cap.c [hunk 11]
```diff
@@ -494,7 +513,7 @@ void bt_l2cap_send_cb(struct bt_conn *conn, u16_t cid, struct net_buf *buf,
 	hdr->len = sys_cpu_to_le16(buf->len - sizeof(*hdr));
 	hdr->cid = sys_cpu_to_le16(cid);
 
-	bt_conn_send_cb(conn, buf, cb, user_data);
+	return bt_conn_send_cb(conn, buf, cb, user_data);
```
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: We can't ignore this since it does return errors in case syswq is used.

[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/l2cap.c]: I mean wherever this function is used (`bt_l2cap_send_cb`). The return value is currently being ignored 15 places in att.c for example.

File: subsys/bluetooth/host/l2cap.c [hunk 12]
```diff
@@ -483,8 +502,8 @@ struct net_buf *bt_l2cap_create_pdu_timeout(struct net_buf_pool *pool,
 					  timeout);
 }
 
-void bt_l2cap_send_cb(struct bt_conn *conn, u16_t cid, struct net_buf *buf,
-		      bt_conn_tx_cb_t cb, void *user_data)
+int bt_l2cap_send_cb(struct bt_conn *conn, u16_t cid, struct net_buf *buf,
```
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: bt_l2cap_send is just a macro os it is already updated by this patch. Regarding the ownership nothing has changed, the buffer passed on this are owned by the stack, so it works exactly like bt_conn_send_cb, so if bt_conn_send_cb fails it unref the buffer, that is it. The same rule also applies to bt_l2cap_chan_send, but since it actually queues packets failing to sending a segment won't drop the packets, they are just processed later.

File: subsys/bluetooth/host/l2cap_internal.h [hunk 13]
```diff
@@ -224,6 +224,8 @@ struct bt_l2cap_br_fixed_chan {
 
 void l2cap_chan_sdu_sent(struct bt_conn *conn, void *user_data);
 
+void l2cap_chan_seg_sent(struct bt_conn *conn, void *user_data);
```
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap_internal.h]: Sure, will remove them.

File: include/bluetooth/l2cap.h [hunk 14]
```diff
@@ -74,6 +74,9 @@ typedef enum bt_l2cap_chan_status {
 	/** Channel output status */
 	BT_L2CAP_STATUS_OUT,
 
+	/** Channel shutdown status */
```
[the remark this answers is not in the document]
Comment (jhedberg) [reply include/bluetooth/l2cap.h]: @joerchan I was equally confused and had an offline chat with @Vudentz to clear this up. He's taken the terms from the poll() API an what kind of events it returns. There's e.g. POLLHUP and POLLOUT there which have the same meaning. This association however isn't at all clear from the context here, and I don't think this should be trying to mirror poll nomenclature. We'll be cleaning this up for 2.2. E.g. `status` will probably be renamed to `flags`. Also, for this PR I think @Vudentz already updated HUP to SHUTDOWN.

File: subsys/bluetooth/host/l2cap.c (hunk 12 above)
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/l2cap.c]: No, bt_l2cap_send is not a macro, it is an inline function, which ignores the return value of bt_l2cap_send_cb.

Yes, the ownership is still the same, but I think it would be beneficial to document this anyway. Especially now that we are ignoring the return value in multiple places. The `net_buf_unref` handling is a bit all over the place, so it would be nice with some comments stating the current behavior.

[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: Ive fixed that now, it should have a return now.

File: subsys/bluetooth/host/l2cap.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: att.c uses a fixed channel though, so it can be ignored due to the fact we just block when using an RX thread or you are suggesting to start changing all of that now?

**Review by joerchan — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/l2cap.c (hunk 12 above)
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: I mean bt_l2cap_send does never fail, there are comments regarding this behavior on the ATT PR.

File: subsys/bluetooth/host/l2cap.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: -EAGAIN is return whenever a segment cannot be send immediately which can happen under the following circuntances:

1. There are no credits
2. There are no buffers
3. There are no TX contexts

In all these case we just push the buffer back to the tx_queue to be send later. Note that what is dropped on number 3 is the segment buffer, the original buffer is unfacted since we restore the data if that cannot be sent.

File: subsys/bluetooth/host/l2cap.c (hunk 12 above)
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/l2cap.c]: Yeah, I just meant that even without a callback `bt_conn_send_cb` could still fail here:
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/conn.c#L1254

I think a comment with the assumptions about why it is safe to ignore the return value would be beneficial.

File: subsys/bluetooth/host/l2cap.c [hunk 15]
```diff
@@ -1447,6 +1505,44 @@ static int l2cap_recv(struct bt_l2cap_chan *chan, struct net_buf *buf)
...
+	atomic_set_bit(chan->status, BT_L2CAP_STATUS_SHUTDOWN);
+
+	/* Destroy segmented SDU if it exists */
+	if (ch->_sdu) {
+		net_buf_unref(ch->_sdu);
+		ch->_sdu = NULL;
+		ch->_sdu_len = 0U;
+	}
+
+	/* Cleanup queues */
```
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: The following code will clean up the TX/RX queues as well as the current outstanding tx_buf, so I don't see anything wrong with it.

File: subsys/bluetooth/host/l2cap.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/l2cap.c]: Thank you.
Me question about EMSGSIZE still remains then. I think in the case where `bt_l2cap_chan_send` submits the work, and  `l2cap_chan_tx_process` calls `l2cap_chan_le_send_sdu` and returns -EMSGSIZE the buffer seems to be not released, because the application would not receive this error code. It appears to me that the application has acquired the first ref but it is unclear who has the responsebility to release it.
This check here:
```
 	if (total_len > ch->tx.mtu) {
		return -EMSGSIZE;
	}
```
Maybe this check could be moved out of `l2cap_chan_le_send_sdu` in that case?

I'm looking at avdtp BTW, and it appears to not release the buf in case of errors returned. I think we need to document in the API of `bt_l2cap_chan_send` how error handling and buffer releasing should be handled.

File: subsys/bluetooth/host/l2cap.c (hunk 10 above)
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: You know, this sort of comment comes out like a patronizing thing, there is obviously no logical difference between using an err or ret.

File: include/bluetooth/l2cap.h (hunk 14 above)
[the remark this answers is not in the document]
Comment (joerchan) [reply include/bluetooth/l2cap.h]: Yeah, I saw. I think that is a good change. Thank you for the clarification.

File: subsys/bluetooth/host/l2cap.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: -EMSGSIZE will be generated only in the context of l2cap_chan_le_send_sdu since after that the buffer is no longer under the control of caller. I haven't changed the semantics of bt_l2cap_chan_send so Id leave any changes such as unrefing the buffer on error for later, and then yes we can update the documentation and do some of the necessary clean ups.

**Comment by Vudentz** [comment]
@dleach02 Im not very sure this was pushed back to 2.2 but there is a high chance that this will need to backported to 2.1 because this also fixes the regression where TX error are not dealt with so IPSP will not work the as as before.

File: subsys/bluetooth/host/l2cap.c (hunk 10 above)
Comment (joerchan) [reply subsys/bluetooth/host/l2cap.c]: It wasn't meant like that. I'm just in a fan of consistency. err is the usual name for returned errno defines. makes it easier to read IMO.

File: subsys/bluetooth/host/l2cap.c (hunk 15 above)
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/l2cap.c]: Ok. I thought it only addressed the following if which is why I found it confusing. maybe include the "current outstanding" in the comment?

**Comment by Vudentz** [comment]
@jhedberg Is there anything blocking us to merge this now that 2.1 has been release?

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
@Vudentz there still seems to be some outstanding stuff from @joerchan (at least GitHub is saying "Merging is blocked" because of that)

**Review by joerchan — APPROVED** [review]

**Comment by Vudentz** [comment]
@joerchan Ive updated the comment regarding cleaning the outstanding tx_buf and a define for the RTX timeout.

**Comment by joerchan** [comment]
```
	if (IS_ENABLED(CONFIG_BT_DEBUG_CONN)) {
		struct bt_conn_tx *tx = k_fifo_get(&free_tx, K_NO_WAIT);

		if (tx) {
			return tx;
		}
	}

	return k_fifo_get(&free_tx, K_FOREVER);
```
I think this one could be a changed to just the last returned now that BT_WARN is gone.

**Comment by Vudentz** [comment]
> ```
> 	if (IS_ENABLED(CONFIG_BT_DEBUG_CONN)) {
> 		struct bt_conn_tx *tx = k_fifo_get(&free_tx, K_NO_WAIT);
> 
> 		if (tx) {
> 			return tx;
> 		}
> 	}
> 
> 	return k_fifo_get(&free_tx, K_FOREVER);
> ```
> 
> I think this one could be a changed to just the last returned now that BT_WARN is gone.

Will fix that.

**Comment by joerchan** [comment]
@Vudentz Great. Sorry for the questions. I'm not that familiar with this part of the code :)
