### PR TITLE
net: sockets: Add locking to receive callback

### LINKED ISSUE #34964: net regression: Connection to Zephyr server non-deterministically leads to client timeout, ENOTCONN on server side
**Describe the bug**

When running dumb_http_server sample for qemu_x86, and connecting to it with `ab -n1000 http://192.0.2.1:8080/`, the `ab` tool aborts due to timeout during handling of one of these 1000 requests. Previously (v2.5.0), 100K requests were served without any problem.

**To Reproduce**
1. cd samples/net/sockets/dumb_http_server
2. west build -b qemu_x86 -t run
3. In another window, `ab -n1000 http://192.0.2.1:8080/`
4. Example output:
```
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 192.0.2.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 542 requests completed
```

The exact request number at which `ab` fails, but over 10 tries, none of 1000-request runs completed successfully.

**Expected behavior**
Both `ab -n1000 http://192.0.2.1:8080/` and `ab -n100000 http://192.0.2.1:8080/` should complete successfully. v2.5.0 worked like that, and I verified that checking out that tag still works like that for me.

**Impact**
We used to have issue(s) like that previously (early 2.x releases). 2.4 and 2.5 passed this test. We're back to network stack instability with this issue.

**Logs and console output**

In addition to the `ab` output shown above, on the dumb_http_server sample side, the output is:
```
Connection #538 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #539 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #540 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #541 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #542 from 192.0.2.2
Error sending data to peer, errno: 128
Connection from 192.0.2.2 closed
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.12.4
 - Commit: git master f05ea6711a730c12dde2c6f8284c50438e992d66

### PR DESCRIPTION
**Pull request by jukkar**
Fix a regression when application is waiting data but does
not notice that because socket layer is not woken up.

This could happen because application was waiting condition
variable but the signal to wake the condvar came before the
wait started. Normally if there is constant flow of incoming
data to the socket, the signal would be given later. But if
the peer is waiting that Zephyr replies, there might be a
timeout at peer.

The solution is to add locking in socket receive callback so
that we only signal the condition variable after we have made
sure that the condition variable is actually waiting the data.

Fixes #34964

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by jukkar** [comment]
@pfalcon I did testing with `dumb_http_server` and ab and did not see the error any more. Can you give it a run too as you seemed to have a good test setup for this.

File: subsys/net/lib/sockets/sockets.c [hunk 1]
```diff
@@ -1221,6 +1221,16 @@ static inline ssize_t zsock_recv_stream(struct net_context *ctx,
 				timeout = Z_TIMEOUT_TICKS(remaining);
 			}
 		}
+
+		if (!K_TIMEOUT_EQ(timeout, K_NO_WAIT) && waitall &&
```
Comment (rlubos) [inline subsys/net/lib/sockets/sockets.c:1225]: The idea seems fine, but I wonder if the logic could be refined a bit to make it less complex. Currently we call `wait_data()` before entering the loop and at the end of the loop. I think it'd be more reasonable to call the `wait_data()` at the beginning of the loop instead, i. e.  add
```
if (!K_TIMEOUT_EQ(timeout, K_NO_WAIT) {
	res = wait_data(ctx, &timeout);
	if (res < 0) { 
		errno = -res; 
		return -1; 
	}
}
```
after `if (sock_is_eof(ctx))` check at line 1147.

Comment (jukkar) [reply subsys/net/lib/sockets/sockets.c:1225]: I tried that, but it did not work (unit tests started to fail). I can investigate more what was the reason.

Comment (jukkar) [reply subsys/net/lib/sockets/sockets.c:1225]: > I tried that, but it did not work (unit tests started to fail). I can investigate more what was the reason.

My earlier experiment with this was clearly wrong as now, when trying it again, it works just fine. Will send a new version shortly.

**Review by mniestroj — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by pfalcon** [comment]
@jukkar 

> I did testing with dumb_http_server and ab and did not see the error any more. Can you give it a run too as you seemed to have a good test setup for this.

Sorry for the delay with response, I was on vacation. Confirming that that this patch resolved issue with dumb_http_server/qemu_x86 + ab for me. Also retested with big_http_download (as the test for "opposite" transfer direction), and it works as expected.

Thanks for investigating this!
