### PR TITLE
nvs: hardening against bad sector close

### LINKED ISSUE #34382: fs/nvs: if closing ATE has to high offset NVS iterates up to the end of flash.
**Describe the bug**
If closing ate is valid (crc is ok) and close_ate.offset
has not allowed value GC will performed flash read above
NVS partition.

**Environment (please complete the following information):**
 - https://github.com/zephyrproject-rtos/zephyr/commit/e3a25b3b3a141560d9d6c41121ab598e07a431c4

### PR DESCRIPTION
**Pull request by Laczen**
A badly written sector close ate that has correct crc8 could allow
jumps outside the assigned flash area. This behavior is fixed.

Fixes #34382

Signed-off-by: Laczen JMS <laczenjms@gmail.com>

### CODE REVIEW

**Review by de-nordic — COMMENTED** [review]
There is present PR that has been created to fix that (https://github.com/zephyrproject-rtos/zephyr/pull/34381), that comes from investigation of the issue.
You are aware of that, because  you have attempted the review.
If you did not like the solution you should have state that in comments and work  out the solution with the author.
Providing contemporary solution, being aware of ongoing work and being active at review process of that solution, is strictly rude and in-cooperative move.

**Comment by Laczen** [comment]
> There is present PR that has been created to fix that (#34381), that comes from investigation of the issue.
> You are aware of that, because you have attempted the review.
> If you did not like the solution you should have state that in comments and work out the solution with the author.
> Providing contemporary solution, being aware of ongoing work and being active at review process of that solution, is strictly rude and in-cooperative move.

@nvlsianpu, I'm sorry if you perceived this PR as strictly rude, this was not my intention.

@de-nordic, the changes I'm proposing here I have mentioned in the review. These changes are no part of the other PR, which is why I have proposed them.

**Comment by nvlsianpu** [comment]
> @nvlsianpu, I'm sorry if you perceived this PR as strictly rude, this was not my intention.

I felt confused. I spent lot of time debugging user issue - a patch is just a tip of the iceberg.
But OK, we all want to have the patch.

Will review that. (I was going to re-implement something similar in my patch, as was suggested in the review).
Due my multitasking role this would takes extended amount of time).

File: subsys/fs/nvs/nvs.c [hunk 1]
```diff
@@ -386,20 +423,14 @@ static int nvs_prev_ate(struct nvs_fs *fs, uint32_t *addr, struct nvs_ate *ate)
...
-		 */
-		if (close_ate.offset < (fs->sector_size - ate_size) &&
-		    !(close_ate.offset % ate_size)) {
-			(*addr) &= ADDR_SECT_MASK;
-			(*addr) += close_ate.offset;
-			return 0;
-		}
+	/* Update the address if the close ate is valid.
+	 */
+	if (nvs_close_ate_valid(fs, &close_ate)) {
```
Comment (nvlsianpu) [inline subsys/fs/nvs/nvs.c:428]: lack of check of case `close_ate.offset > (fs->sector_size - ate_size)`
need add service of `close_ate.offset == (fs->sector_size - ate_size)`

File: subsys/fs/nvs/nvs.c [hunk 2]
```diff
@@ -425,12 +456,14 @@ static int nvs_sector_close(struct nvs_fs *fs)
...
 	size_t ate_size;
+	uint16_t sector_offset;
 
 	ate_size = nvs_al_size(fs, sizeof(struct nvs_ate));
+	sector_offset = (uint16_t)((fs->ate_wra	+ ate_size) & ADDR_OFFS_MASK);
 
 	close_ate.id = 0xFFFF;
 	close_ate.len = 0U;
-	close_ate.offset = (uint16_t)((fs->ate_wra + ate_size) & ADDR_OFFS_MASK);
+	close_ate.offset = sector_offset;
```
Comment (nvlsianpu) [inline subsys/fs/nvs/nvs.c:466]: why this `sector_offset` assignment mediation was introduced?

File: subsys/fs/nvs/nvs.c [hunk 3]
```diff
@@ -483,7 +516,7 @@ static int nvs_gc(struct nvs_fs *fs)
 
 	stop_addr = gc_addr - ate_size;
 
-	if (!nvs_ate_crc8_check(&close_ate)) {
+	if (nvs_close_ate_valid(fs, &close_ate)) {
```
Comment (nvlsianpu) [inline subsys/fs/nvs/nvs.c:519]: lack of check of case close_ate.offset > (fs->sector_size - ate_size)
need add service of close_ate.offset == (fs->sector_size - ate_size)

**Review by nvlsianpu — CHANGES_REQUESTED** [review]

File: subsys/fs/nvs/nvs.c (hunk 1 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c:428]: I don't think we need to service this, IMO the simplest idea is to consider any ate as valid if `.offset< fs->sector_size - ate_size` . In that case the service of the special case is automatically done.

File: subsys/fs/nvs/nvs.c (hunk 2 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c:466]: Because it was over the 80 char limit.

File: subsys/fs/nvs/nvs.c (hunk 3 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c:519]: IMO not needed, see comment above.

File: subsys/fs/nvs/nvs.c (hunk 1 above)
Comment (nvlsianpu) [reply subsys/fs/nvs/nvs.c:433]: Almost, yes `.offset == (fs->sector_size - ate_size)` need special treatment

File: subsys/fs/nvs/nvs.c (hunk 2 above)
Comment (nvlsianpu) [reply subsys/fs/nvs/nvs.c:471]: line should be break instead (I think).

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
I need, spend some more time reviewing that
at last putted some comments right now

**Comment by nvlsianpu** [comment]
@Laczen Will you continue this patch? If no I can take your commit to my PR.

**Comment by Laczen** [comment]
> @Laczen Will you continue this patch? If no I can take your commit to my PR.

This PR is complete

The special treatment is not needed, recover_last_ate sets gc_addr to stop_addr.

The line break is a correction, doing a line break makes it ugly.

You can take this commit to your PR, if you would like this better.

File: subsys/fs/nvs/nvs.c [hunk 4]
```diff
@@ -277,6 +277,48 @@ static int nvs_ate_cmp_const(const struct nvs_ate *entry, uint8_t value)
...
+ *     return 1 if crc8 and offset valid,
+ *            0 otherwise
+ */
+static int nvs_ate_valid(struct nvs_fs *fs, const struct nvs_ate *entry)
+{
+	size_t ate_size;
+
+	ate_size = nvs_al_size(fs, sizeof(struct nvs_ate));
+
+	if ((nvs_ate_crc8_check(entry)) ||
```
Comment (de-nordic) [inline subsys/fs/nvs/nvs.c:290]: According to `.checkpatch.conf` you can have now 100 chars per line so ou do not have to break these `if`s

File: subsys/fs/nvs/nvs.c [hunk 5]
```diff
@@ -277,6 +277,48 @@ static int nvs_ate_cmp_const(const struct nvs_ate *entry, uint8_t value)
...
+ * - len = 0 and id = 0xFFFF
+ * - offset points to location at ate multiple from sector size
+ * return 1 if valid, 0 otherwise
+ */
+static int nvs_close_ate_valid(struct nvs_fs *fs, const struct nvs_ate *entry)
+{
+	size_t ate_size;
+
+	if ((!nvs_ate_valid(fs, entry)) || (entry->len != 0U) ||
+	    (entry->id != 0xFFFF)) {
```
Comment (de-nordic) [inline subsys/fs/nvs/nvs.c:310]: This probably will fit in one 100 character line.

**Comment by de-nordic** [comment]
@Laczen @nvlsianpu Would it be possible to provide the test case that covers the changes? The problem originally did not trigger any of tests.

File: subsys/fs/nvs/nvs.c (hunk 4 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c:290]: restored the original line.

File: subsys/fs/nvs/nvs.c (hunk 5 above)
Comment (Laczen) [reply subsys/fs/nvs/nvs.c:310]: Yes, but don't turn the rule around because then I would have to do lot's of changes :-) :-). I will leave this one as is and still try to keep the 80 char rule.

BTW, I think there is a 78 char rule on the PR description in github which already makes it very difficult to copy part of your code into the PR (e.g. as source for discussion).

**Comment by Laczen** [comment]
> @Laczen @nvlsianpu Would it be possible to provide the test case that covers the changes? The problem originally did not trigger any of tests to fail.

@de-nordic, there does not have to be a test case for every improvement that is provided. The result would be bloated tests that just take a very long time to verify. If tests are required to show how "good" the proposed solution is, they should not be part of the present test directory. Instead these tests should be part of a set of "development_tests".

**Comment by de-nordic** [comment]
> 
> @de-nordic, there does not have to be a test case for every improvement that is provided. The result would be bloated tests that just take a very long time to verify. If tests are required to show how "good" the proposed solution is, they should not be part of the present test directory. Instead these tests should be part of a set of "development_tests".

The tests are provided to avoid regression and in future changes to the code make sure that applied changes still cover such cases like this one, which required engagement of several developers to investigate the problem and come out with a solution.

In simple words: the tests are here for the future development to prove that further  changes are  not breaking anything and that they maintain already agreed behavior of the black-box, and are not bringing back something that has already been fixed in the past.

**Comment by Laczen** [comment]
> The tests are provided to avoid regression and in future changes to the code make sure that applied changes still cover such cases like this one, which required engagement of several developers to investigate the problem and come out with a solution.
> 
> In simple words: the tests are here for the future development to prove that further changes are not breaking anything and that they maintain already agreed behavior of the black-box, and are not bringing back something that has already been fixed in the past.

Where did you find this ? I agree that testing is needed. Applying the methodology above is just a bridge too far (and will stop people proposing improvements).

**Comment by de-nordic** [comment]
>
> Applying the methodology above is just a bridge too far (and will stop people proposing improvements).

No it will not. If you want to improve something and agree it will change certain behavior, you would need to reflect that in tests; this way next person to fix things will not break your improvements.
On the other side the developers will be less reluctant to provide changes because they can make sure that they have not broken some other stuff or brought regression.

You need to agree that the the problem, the fix you have delivered for, has not been easy to spot and prove (discussion:  https://github.com/zephyrproject-rtos/zephyr/pull/34381) and may be as easy to be missed next time, when some changes are applied.

**Comment by Laczen** [comment]
I'm not going in that direction, For me testing is mainly to make sure that the system isn't broken by changes outside the subsystem.

**Comment by nvlsianpu** [comment]
>> @Laczen Will you continue this patch? If no I can take your commit to my PR.

> This PR is complete

> The special treatment is not needed, recover_last_ate sets gc_addr to stop_addr.

As I tested Patch works in a way that GC recoveries data from sectors which was closing as empty (case of valid closing ate with `close_ate.offset == (fs->sector_size - ate_size)`).
This mean that sector which have been recognized as containing no valid data at moment when It have been closed became effective source of data for new sector later during GC. This sector have been treated different when it was read using nvs_read() than when it was read during GC. This is incoherent behavior.

**Comment by Laczen** [comment]
> > > @Laczen Will you continue this patch? If no I can take your commit to my PR.
> 
> > This PR is complete
> 
> > The special treatment is not needed, recover_last_ate sets gc_addr to stop_addr.
> 
> As I tested Patch works in a way that GC recoveries data from sectors which was closing as empty (case of valid closing ate with `close_ate.offset == (fs->sector_size - ate_size)`).
> This mean that sector which have been recognized as containing no valid data at moment when It have been closed became effective source of data for new sector later during GC. This sector have been treated different when it was read using nvs_read() than when it was read during GC. This is incoherent behavior.

I don't understand what you are saying. What is the incoherent behavior ?

**Comment by nvlsianpu** [comment]
If sector is closed with this offset in closing ate, it mean that was treated as containing no valid data.
And after that GC operation shouldn't extract any data from that sector. And with this path GC does extract these data.

This would be OK (consistent) if gaps in ATE area were allowed.

**Comment by Laczen** [comment]
> If sector is closed with this offset in closing ate, it mean that was treated as containing no valid data.
> And after that GC operation shouldn't extract any data from that sector. And with this path GC does extract these data.
> 
> This would be OK (consistent) if gaps in ATE area were allowed.

You are right, recover_close_ate() does not mind any ATE being empty. Now would it not be better to handle this at startup (by erasing the sector) ?

**Comment by nvlsianpu** [comment]
> Now would it not be better to handle this at startup (by erasing the sector) ?

This might disturb recognition of open/current sector on startup(I'm no 100% sure). 

Serving this in GC will not damage anything else, I would go this way then.

**Comment by Laczen** [comment]
> > Now would it not be better to handle this at startup (by erasing the sector) ?
> 
> This might disturb recognition of open/current sector on startup(I'm no 100% sure).
> 
> Serving this in GC will not damage anything else, I would go this way then.

This problem will only appear if the sector is detected as the current sector (an other sector will not be closed), so doing it at startup would create a empty sector.

**Comment by nvlsianpu** [comment]
@Laczen If so, I have no objection.

@de-nordic I will provide testcase later.

**Comment by de-nordic** [comment]
@Laczen since the PR is result of work and investigation (and lengthy discussion) that has been done by both you and @nvlsianpu , consider adding him as a co-author.

**Comment by Laczen** [comment]
> @Laczen since the PR is result of work and investigation (and lengthy discussion) that has been done by both you and @nvlsianpu , consider adding him as a co-author.

I don't mind this at all, @nvlsianpu can take or claim ownership. I don't know how to add a co-author or to transfer ownership. All I want is a good nvs system.

**Comment by de-nordic** [comment]
> 
> I don't mind this at all, @nvlsianpu can take or claim ownership. I don't know how to add a co-author or to transfer ownership. All I want is a good nvs system.

You both did the work and my proposal was not intended to strip you from your important commitment into the NVS improvements.

**Comment by Laczen** [comment]
@nvlsianpu, I added the erase of the sector during startup. However this fix is probably not handling the root cause of the problem. The root cause might be:
a. A bad/incomplete erase -> needs a different fix
b. External writing to the sector (strange that it would create valid entries) -> needs to fix (unsupported)
c. Switching alignment from 16 to 8 bytes -> needs a different fix
d. End of life -> needs a different fix
e. ...

**Comment by nvlsianpu** [comment]
@Laczen Thanks for update.

I tested it and it works so the patch prevents closing empty an sector. So the patch is good.

I guess I hurried up a bit with the comment. Forgot that people might have devices in the field with this problem and its result (a sector already closed as empty). Actually that was exactly root of the issue reported to me. I think need to add fix for that as well (maybe as I did in GC code or in nvs_startup).

**Comment by Laczen** [comment]
> @Laczen Thanks for update.
> 
> I tested it and it works so the patch prevents closing an empty sector. So the patch is good.
> 
> I guess I hurried up a bit with the comment. Forgot that people might have devices in the field with this problem and its result (a sector already closed as empty). Actually that was exactly root of the issue reported to me. I think need to add fix for that as well (maybe as I did in GC code or in nvs_startup).

The sector closed as empty is not the root cause, it is the result of some other error.

A start of nvs with data already in the first sector could cause it. A incomplete erase (due to power failure) would be detected at startup and (wrongly) retrigger a gc operation, but it would not cause closing an empty sector. What puzzles me most it that it seems there are some valid ate's inside the sector, this indicates that it is due to a bad erase.

**Comment by Laczen** [comment]
@nvlsianpu, can you confirm that the non FFFFFFFF value that is written at F6FD8 is a valid ATE. From the data that is inside it seems that this is not an ate, but I'm doubting on byte order.

**Comment by nvlsianpu** [comment]
>@nvlsianpu, can you confirm that the non FFFFFFFF value that is written at F6FD8 is a valid ATE. From the data that is inside it seems that this is not an ate, but I'm doubting on byte order.

Yes that's valid ATE.

> A incomplete erase (due to power failure) would be detected at startup and (wrongly) retrigger a gc operation, but it would not cause closing an empty sector. What puzzles me most it that it seems there are some valid ate's inside the sector, this indicates that it is due to a bad erase

Additional patch will allow to use an affected NVS's in-flash image (Assumed that what cause a bad erase will be fixed).

**Comment by Laczen** [comment]
For my understanding can you distill the id, len and offset from this ate ?

The solution might be completely different depending on the origin of this. A (un)lucky shot that created a valid crc8 (can be fixed at startup) or a real bad erase (will require checking the result of the erase).

**Comment by Laczen** [comment]
Added erase verification.

**Comment by nvlsianpu** [comment]
ATE was : 51 c7 60 00 30 00 FF F6
id: 0xc751
offset: 0x0060
len: 0x0030
crc8: F6 (match)

And there is expected data block at this offset, and of this size. There is only erased memory before and after this data block which suggest rather problem with flash write than erase.

This looks like NVS had been writing its data and metadata without any reflection in flash - and after that NVS have write another data and metadata successfully, all in the same run.

**Comment by Laczen** [comment]
> ATE was : 51 c7 60 00 30 00 FF F6
> id: 0xc751
> offset: 0x0060
> len: 0x0030
> crc8: F6 (match)
> 
> And there is expected data block at this offset, and of this size. There is only erased memory before and after this data block which suggest rather problem with flash write than erase.
> 
> This looks like NVS had been writing its data and metadata without any reflection in flash - and after that NVS have write another data and metadata successfully, all in the same run.

Thanks, if this is the case the fix not solve the issue. The above is possible, even if the flash_write returns an error the ate is updated !!!!!!

**Comment by nvlsianpu** [comment]
> Added erase verification.

Where? Is this done by moving code block from line 651?

This PR fix the issue by prevents its occurrence (issue is close_ate.offset == addr of close_ate). Looks fine I will accept it.

Problem I want have to solve as well is a patch which will works for NVS images which already have sector closed with this bug result. It is what I did here https://github.com/zephyrproject-rtos/zephyr/pull/33947/commits/f5fa36158d3244a6280671583c488215601b8a73
Should I open another patch, or you will do something like this here. Or you think  something else.

**Comment by Laczen** [comment]
> > Added erase verification.
> 
> Where? Is this done by moving code block from line 651?
> 
Yes

> This PR fix the issue by prevents its occurrence (issue is close_ate.offset == addr of close_ate). Looks fine I will accept it.
> 
> Problem I want have to solve as well is a patch which will works for NVS images which already have sector closed with this bug result. It is what I did here [f5fa361](https://github.com/zephyrproject-rtos/zephyr/commit/f5fa36158d3244a6280671583c488215601b8a73)
> Should I open another patch, or you will do something like this here. Or you think something else.

I think something else, the patch is wrong. I think we should treat these sectors as carrying valid data. The startup procedure needs to be modified (using recover_last_ate to find the write location). In that case empty ate's are ignored and there is no need to fix something to the write failure (although we could also fix that).

**Comment by nvlsianpu** [comment]
>I think something else, the patch is wrong. I think we should treat these sectors as carrying valid data. The startup procedure needs to be modified (using recover_last_ate to find the write location). In that case empty ate's are ignored and there is no need to fix something to the write failure (although we could also fix that).

That affected sector was recognized as empty during it was active one. Did I understand correctly: such sector will be might assumed active? - this will be bad as without that another sector might buy recognized as active.
GC from affected sector causes dead data resurrections.
======================

Can you explain what code block move does?

**Comment by Laczen** [comment]
> > I think something else, the patch is wrong. I think we should treat these sectors as carrying valid data. The startup procedure needs to be modified (using recover_last_ate to find the write location). In that case empty ate's are ignored and there is no need to fix something to the write failure (although we could also fix that).
> 
> That affected sector was recognized as empty during it was active one. Did I understand correctly: such sector will be might assumed active? - this will be bad as without that another sector might buy recognized as active.

A sector is considered active or erased based on the data in last ate in a sector (the close ate). So the sector you have (which is not yet closed) would be considered as active. A restart would identify this sector as the active sector and when there is insufficient space close the sector -> empty closed sector. This would then no longer be considered a active sector. 

> GC from affected sector causes dead data resurrections.

Is this true ? If there is valid data it can be explainen by a write failure, if there only is dead data the only explanation I can see is a bad erase.

> 
> Can you explain what code block move does?

Before the flash sector was checked to avoid doing an erase of an already empty sector. This was useless as a already erased flash will not have a reduced life expectancy from an erase. So I just moved the compare after the erase to make sure that the erase has been succesfull.

**Review by nvlsianpu — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@de-nordic @carlescufi This should go now.

**Comment by Laczen** [comment]
@nvlsianpu, is the data that is found in the sector dead data, or is it valid data ?

**Comment by nvlsianpu** [comment]
^^ they are dead, they were not possible to be read using nvs_read() when sector was either active or closed.

**Comment by Laczen** [comment]
> ^^ they are dead, they were not possible to be read using nvs_read() when sector was either active or closed.

Thanks for the reply. What you are saying now is that they were buried :-), it's OK to say: I don't know if the data was still needed or not. We can then decide what is the most probable, an erase failure or a unwritten ate, and react based on that decision.

**Comment by Laczen** [comment]
Updated searching the last ate during startup. Empty ate's are now allowed and recognized during startup.

**Comment by nvlsianpu** [comment]
> Thanks for the reply. What you are saying now is that they were buried :-), it's OK to say: I don't know if the data was still needed or not. We can then decide what is the most probable, an erase failure or a unwritten ate, and react based on that decision.

These buried data were not available using nvs_read() anytime. They should flushed away.

> Updated searching the last ate during startup. Empty ate's are now allowed and recognized during startup.
Is result similar to what I did here? https://github.com/zephyrproject-rtos/zephyr/pull/33947/commits/409c145191726fbb0f474a7d8ec98d37de968567
Do I understood correctly that this makes behavior coherent so data will be no buried anymore (while sector is active, closed or is the GC source )?

**Comment by Laczen** [comment]
> > Updated searching the last ate during startup. Empty ate's are now allowed and recognized during startup.
> Is result similar to what I did here? [409c145](https://github.com/zephyrproject-rtos/zephyr/commit/409c145191726fbb0f474a7d8ec98d37de968567)
> Do I understood correctly that this makes behavior coherent so data will be no buried anymore (while sector is active, closed or is the GC source )?

Yes, it is coherent and data is no longer burried: by making the empty sector close ate invalid (a valid ate should have a offset < sector_size - ate_size) the gc or read routine will recover the last ate. At startup (active) the same is done.

**Comment by nvlsianpu** [comment]
OK, I will test on my desk.

**Comment by nvlsianpu** [comment]
@Laczen Verified on my desk - works fine.
@de-nordic can you review?

**Review by de-nordic — APPROVED** [review]
Looks OK.

**Comment by nvlsianpu** [comment]
@Laczen Can you update commit message?
Look like buildkite failed du the bug inherited from the master. Maybe it is fixed already on master.

**Comment by nvlsianpu** [comment]
@carlescufi This PR can be merged. buildkite failed due this:
``` console
/workdir/zephyr/drivers/sensor/max17262/max17262.c:343:13: error: Macro is deprecated [-Werror]
  343 | DT_INST_FOREACH_STATUS_OKAY(MAX17262_INIT)
```
which is not related to this patch content.
