### PR TITLE
xtensa: check for valid stack pointers before dumping stack and printing backtraces

### LINKED ISSUE #74433: xtensa: unwinding stack during exception can access invalid memory
**Describe the bug**
Sometimes when unwinding stack on Xtensa during exception, especially with a corrupted stack, it can access invalid memory.

**Expected behavior**
Do not access invalid memory.

**Impact**
Annoyance for now as it is currently a rare occurrence.

### PR DESCRIPTION
**Pull request by dcpleung**
During exception, to get information on the interrupted context (PC, PS, EXCCAUSE, etc.) requires de-referencing pointers (e.g. `frame->ptr_to_bsa` then `bsa->pc`). If the stack is corrupted, it could lead to infinite exceptions. So better check them.

(See individual commits for more details.)

Fixes #74433

### CODE REVIEW

File: arch/xtensa/core/vector_handlers.c [hunk 1]
```diff
@@ -116,7 +116,12 @@ static void print_fatal_exception(void *print_stack, int cause,
 
 	__asm__ volatile("rsr.excvaddr %0" : "=r"(vaddr));
 
-	LOG_ERR(" ** FATAL EXCEPTION%s", (is_dblexc ? " (DOUBLE)" : ""));
+	if (is_dblexc) {
+		LOG_ERR(" ** FATAL EXCEPTION (DOUBLE)");
+	} else {
+		LOG_ERR(" ** FATAL EXCEPTION");
```
Comment (andyross) [inline arch/xtensa/core/vector_handlers.c:235]: Can we please root cause this instead of merging the workaround?  That sounds like stack overflow of the interrupt frame or something equally terrifying.  Does it happen in emulation anywhere?

**Review by andyross — COMMENTED** [review]
The first patch creeps me out a bit, can we at least file a bug on that?  Almost certainly that's a symptom of something bad.   Regarding the bigger change: is this really that useful?  Exception entry isn't safe on xtensa right now and can't easily be made so (yes, still need to get call0 in).  Stack corruption is just as likely to lead to an explosion on interrupt entry that this can't fix, no?  Why spend code bytes to handle this particular subset of failures?

**Comment by dcpleung** [comment]
> The first patch creeps me out a bit, can we at least file a bug on that? Almost certainly that's a symptom of something bad. Regarding the bigger change: is this really that useful? Exception entry isn't safe on xtensa right now and can't easily be made so (yes, still need to get call0 in). Stack corruption is just as likely to lead to an explosion on interrupt entry that this can't fix, no? Why spend code bytes to handle this particular subset of failures?

This, to certain extent, prevents infinite faulting due to stack corruption of the frame pointer, especially `frame->ptr_to_bsa` being bad. Another big part is to prevent backtrace from going through bad pointers. The sure way to trigger this is via `tests/kernel/mem_protect/stackprot` with `qemu_xtensa/dc233c/mmu`. The `alt_thread` is definitely corrupting the stack frame and the BSA pointer.

File: arch/xtensa/core/vector_handlers.c (hunk 1 above)
Comment (dcpleung) [reply arch/xtensa/core/vector_handlers.c:235]: Stack frame was definitely corrupted when this happened, and the corruption was deliberate. Though I have no idea why it would print `(null)` instead of nothing (via `%s`). Debugging via GDB always makes it work again.

**Review by andyross — DISMISSED** [review]
Still don't love all the code being added as a purely defensive workaround for a poorly-understood[1] condition that shouldn't happen, but not a reason to refuse I guess.  Can always look at refactoring later.

[1] FWIW, one possibility is that you're seeing exactly the vulnerability I mentioned, where a userspace process has found a path to stuff "weird things" into its rotated registers in a context where interrupts are enabled, and the kernel is blowing up on the resulting confusion.  Then we end up here trying to "handle" the context dump when the root cause is elsewhere.

**Comment by nashif** [comment]
@dcpleung  rebase please

**Comment by dcpleung** [comment]
Rebased.

**Comment by aescolar** [comment]
@dcpleung If this is a bug, would you be so kind as to label it so and create a linked bug report.
Otherwise the milestone should be changed to 4.0.
(A rebase is needed in any case)

**Review by nashif — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
