### PR TITLE
pm: device_runtime: return -ENOTSUP if PM not supported

### LINKED ISSUE #45648: pm: device_runtime: API functions fault when PM not supported
**Describe the bug**

Attempting to run `pm_device_runtime` functions on drivers that don't support PM result in hard faults instead of error codes.
This is true even for functions which could conceivably be used to determine if PM is supported (`pm_device_runtime_is_enabled`).

Documented API return codes no longer occur either, for example:
https://github.com/zephyrproject-rtos/zephyr/blob/bfe16bdc1713f8eed507375f2f3643659b5bbb55/include/zephyr/pm/device_runtime.h#L37

All PM functions dereference the PM pointer as one of the first actions without checking if the pointer is valid, as done here:
https://github.com/zephyrproject-rtos/zephyr/blob/bfe16bdc1713f8eed507375f2f3643659b5bbb55/subsys/pm/device_runtime.c#L219-L221

**Expected behavior**

Calling any of the functions from `device_runtime.h` on devices that don't support PM should return `-ENOSYS`.

**Impact**

Hard-faults at runtime unless you know the implementation details of devices beforehand.

### PR DESCRIPTION
**Pull request by JordanYates**
Return `-ENOTSUP` on calls to device_runtime functions if the underlying
device does not support power management, instead of hard-faulting.

Fixes #45648.

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

### CODE REVIEW

File: subsys/pm/device_runtime.c [hunk 1]
```diff
@@ -119,6 +119,10 @@ int pm_device_runtime_get(const struct device *dev)
 	int ret = 0;
 	struct pm_device *pm = dev->pm;
 
+	if (pm == NULL) {
+		return -ENOSYS;
+	}
+
```
Comment (ceolin) [inline subsys/pm/device_runtime.c:125]: Checking for this is something good imho. Just a few points with the implementation:

1) It seems to me that it should return `-ENOTSUP` since runtime API was enabled and is a specific device that does not support PM.
2) Why don't we use `CHECKIF` here and make this check optional.

Other than these points I think the commit is nice.

Comment (gmarull) [reply subsys/pm/device_runtime.c:125]: agreed, should be `-ENOTSUP`.

**Comment by JordanYates** [comment]
Return value has been changed to `-ENOTSUP`.
Return options have been documented in the header
A Test for the new return values has been added.

File: subsys/pm/device_runtime.c (hunk 1 above)
Comment (JordanYates) [reply subsys/pm/device_runtime.c:125]: Done. Not using `CHECKIF` because it should never be promoted to an assertion.
Some device drivers just don't need to support PM because they are always in their lowest power state when not running.

An example use case is a common thread that can be given any temperature sensor to run. Giving it a sensor that doesn't have PM is not an error condition, but it still needs to run `pm_device_runtime` functions for sensors that do.

Comment (ceolin) [reply subsys/pm/device_runtime.c:125]: That is ok, I still think `CHECKIF` is better. The default behavior is the branch, it is really expected that if someone promotes it to an assert or to a NOP they know what they are doing. But that is minor.

**Review by ceolin — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

File: subsys/pm/device_runtime.c (hunk 1 above)
Comment (JordanYates) [reply subsys/pm/device_runtime.c:125]: I disagree, doing a spot check of other uses in-tree, they are all for conditions which either should not occur at runtime (e.g. passing a NULL device as an argument) or are the result of an invalid configuration (e.g. some name is too long).

These are the results of bugs or misconfigurations, and you could reasonably select `CONFIG_ASSERT_ON_ERRORS` after initial testing and expect nothing to go wrong. A device not supporting PM is not a bug or a misconfiguration, and in the case of upstream drivers can't be fixed without copying the driver.

You would be unable to use `CONFIG_ASSERT_ON_ERRORS` or `CONFIG_NO_RUNTIME_CHECKS` if any particular device did not support PM.
