### PR TITLE
 drivers: ipm_stm32wb: add workaround for conn_complete

### LINKED ISSUE #19509: Bluetooth: stm32wb55: Unable to pair with privacy-enabled peer
Secure connection could not be established. Fails with code 1 (BT_SECURITY_ERR_AUTH_FAIL).

The first suspicious thing to look on: if BT_SMP=y then HCI will send the peer address as ff:ff:ff:ff:ff:ff (random). For the nrf52 we'll see here some valid address.
Dumped hci packet in stm32 hold the ff ff ff .. address. 

**To Reproduce**
1. build the peripheral_hids sample
2. cmake -GNinja -DBOARD=nucleo_wb55rg && ninja flash
3. Open serial console 
4. Try connect.
5. Enter passkey.
6. Observe authentication failure.

**Expected behavior**
Pairing successful. 

**Impact**
No secure connection pairing with privacy enabled peer could be established.
No legacy pairing using passkey with privacy enabled peer could be established.

**Screenshots or console output**
Connected ff:ff:ff:ff:ff:ff (random)
Security failed: ff:ff:ff:ff:ff:ff (random) level 1 err 1
Disconnected from ff:ff:ff:ff:ff:ff (random) (reason 0x13)

**Environment (please complete the following information):**
 - Linux (Ubuntu 18.04 x64)
 - Zephyr SDK
 - 89d4c6928e (latest master)

**Additional context**
1) The M0 firmware is updated to latest  BLE: v1.2.0 FUS: v1.0.2
2) tried to take HAL from latest CUBE. - the same result https://github.com/zephyrproject-rtos/hal_stm32/pull/21
3) if BT_SMP is disabled. then the proper peer addresses are seen. https://github.com/zephyrproject-rtos/zephyr/pull/19508 could be used to simply enable/disable SMP

### PR DESCRIPTION
**Pull request by pavlohamov**
Enhanced connection complete message lacks of
the peer address (FF::FF), which leads to pairing/bonding failure.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/19509

### CODE REVIEW

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -1032,10 +1032,20 @@ static void enh_conn_complete(struct bt_hci_evt_le_enh_conn_complete *evt)
...
 	int err;
 
-	BT_DBG("status 0x%02x handle %u role %u %s", evt->status, handle,
-	       evt->role, bt_addr_le_str(&evt->peer_addr));
+	BT_DBG("status 0x%02x handle %u role %u adr:%s rpa:%s local_rpa:%s",
+			evt->status, handle, evt->role, bt_addr_le_str(&evt->peer_addr),
+			bt_addr_str(&evt->peer_rpa), bt_addr_str(&evt->local_rpa));
 
 #if defined(CONFIG_BT_SMP)
+	if (!bt_addr_cmp(&evt->peer_addr.a, BT_ADDR_NONE)) {
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: This extra code should be build-time conditional to the HCI driver that exhibits this issue. You should also add a code comment here explaining it (basically the same as you have in the commit message). We could also entertain the thought of introducing driver quirks (same as Linux HCI drivers have), but I think a Kconfig dependency is enough for now.

Alternatively, could you do the fixup directly inside the HCI driver, to avoid polluting the HW-agnostic host-side code with this kind of workarounds?

File: subsys/bluetooth/host/hci_core.c [hunk 2]
```diff
@@ -1032,10 +1032,20 @@ static void enh_conn_complete(struct bt_hci_evt_le_enh_conn_complete *evt)
...
+		if (bt_addr_cmp(&evt->peer_rpa, BT_ADDR_NONE)) {
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: Is the ST firmware actually sometimes giving your BT_ADDR_NONE as RPA? If not, I'd just leave out this secondary check.

File: subsys/bluetooth/host/hci_core.c [hunk 3]
```diff
@@ -1032,10 +1032,20 @@ static void enh_conn_complete(struct bt_hci_evt_le_enh_conn_complete *evt)
...
+			BT_DBG("RPA is ok. Copy to peer address");
+			bt_addr_copy(&evt->peer_addr.a, &evt->peer_rpa);
+			evt->peer_addr.type = BT_ADDR_LE_RANDOM;
+		} else {
+			BT_WARN("Invalid peer address %s", bt_addr_le_str(&evt->peer_addr));
+		}
+	}
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: minor coding style: empty line after this (whenever the next line is not also a `}`)

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/hci_core.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c]: I think that putting the code in ipm_stm32wb.c might be the best option. That would leave the least amount of clutter I think. Especially in case somebody wants to use the BT_ADDR_NONE address with an IRK.

File: subsys/bluetooth/host/hci_core.c (hunk 2 above)
Comment (pavlohamov) [reply subsys/bluetooth/host/hci_core.c]: Totally agree with your point. I'm not familiar with the raw HCI packet format, thus it was easier for me to write code for the "parsed" HCI packet. Now I'm investigating which bytes to copy in the driver

Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c]: @pavlohamov Yeah, it is a bit more tricky to add it there.

Your buffer will consist of these:
struct bt_hci_evt_hdr
check if evt == BT_HCI_EVT_LE_META_EVENT
struct bt_hci_evt_le_meta_event
check if subevent == BT_HCI_EVT_LE_ENH_CONN_COMPLETE
struct bt_hci_evt_le_enh_conn_complete

Comment (pavlohamov) [reply subsys/bluetooth/host/hci_core.c]: @joerchan Thank you for your directions. I've dumped the message content and understand that it could be simply cast'ed to bt_hci_evt_le_enh_conn_complete. Please take a look

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 4]
```diff
@@ -119,8 +119,31 @@ void TM_EvtReceivedCb(TL_EvtPacket_t *hcievt)
...
+/*
+ * https://github.com/zephyrproject-rtos/zephyr/issues/19509
+ * For some reason BLE stack (v 1.2.0) is not reporting the peer address
+ * 0A 00 01 08 01 01 FF FF FF FF FF FF 00 00 00 00 00 00 0C AA C5 B3 3D 6B ...
+ * If such message is passed to HCI core than no Secure connection could be
+ * established. Temporary copy RPA to PEER address
+ */
+		struct bt_hci_evt_le_meta_event *mev;
+		mev = (struct bt_hci_evt_le_meta_event *)hcievt->evtserial.evt.payload;
+		if (mev->subevent == BT_HCI_EVT_LE_ENH_CONN_COMPLETE) {
```
Comment (joerchan) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: Check that it is in fact an LE_Meta_Event.
```suggestion
		if (hcievt->evtserial.evt.evtcode == BT_HCI_EVT_LE_META_EVENT &&
		    mev->subevent == BT_HCI_EVT_LE_ENH_CONN_COMPLETE) {
```

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 5]
```diff
@@ -119,8 +119,31 @@ void TM_EvtReceivedCb(TL_EvtPacket_t *hcievt)
...
+			struct bt_hci_evt_le_enh_conn_complete *evt =
+					(struct bt_hci_evt_le_enh_conn_complete*)(mev + 1);
+			BT_WARN("Invalid peer addr %s", bt_addr_le_str(&evt->peer_addr));
```
Comment (joerchan) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: Move warning into the if-statement?

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 4 above)
Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Make sense. Thanks, Done

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 5 above)
Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Oups, my bad. Was fixing the 80 characters issue and moved to improper place. Thanks, done

**Review by joerchan — APPROVED** [review]
Looks OK.
You have a few lines that are too long, and there is a requirement to have blank line after variable declarations.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 6]
```diff
@@ -119,8 +119,33 @@ void TM_EvtReceivedCb(TL_EvtPacket_t *hcievt)
 					     K_FOREVER);
 			break;
 		}
+/*
+ * https://github.com/zephyrproject-rtos/zephyr/issues/19509
+ * For some reason BLE stack (v 1.2.0) is not reporting the peer address
```
Comment (joerchan) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: The bug as it appears to me is that: "Unresolved Resolvable Private Addresses (RPA) is reported in the peer_rpa field, and not in the peer address, as it should, when this happens the peer address is set to all FFs"
Might be a better explanation for what you are doing here.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 7]
```diff
@@ -119,8 +119,33 @@ void TM_EvtReceivedCb(TL_EvtPacket_t *hcievt)
...
+ * 0A 00 01 08 01 01 FF FF FF FF FF FF 00 00 00 00 00 00 0C AA C5 B3 3D 6B ...
+ * If such message is passed to HCI core than no Secure connection could be
+ * established. Temporary copy RPA to PEER address
```
Comment (joerchan) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: It's not temporary.  Should update to "Rewrite the event with the RPA in the PEER address field"

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 8]
```diff
@@ -119,8 +119,33 @@ void TM_EvtReceivedCb(TL_EvtPacket_t *hcievt)
 					     K_FOREVER);
 			break;
 		}
+/*
+ * https://github.com/zephyrproject-rtos/zephyr/issues/19509
+ * For some reason BLE stack (v 1.2.0) is not reporting the peer address
+ * 0A 00 01 08 01 01 FF FF FF FF FF FF 00 00 00 00 00 00 0C AA C5 B3 3D 6B ...
+ * If such message is passed to HCI core than no Secure connection could be
```
Comment (joerchan) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: Legacy pairing is also affected. Essentially the Pairing procedure will fail.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 9]
```diff
@@ -119,8 +119,33 @@ void TM_EvtReceivedCb(TL_EvtPacket_t *hcievt)
...
+ * established. Temporary copy RPA to PEER address
+ */
+		struct bt_hci_evt_le_meta_event *mev;
```
Comment (joerchan) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: With all the 80 character limit violations you might consider just moving this into a function.

**Comment by pavlohamov** [comment]
@joerchan Thank you for your review. I've updated the description and moved solution to separate function. Added new lines after the variable declaration

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 10]
```diff
@@ -96,6 +96,37 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
...
+ * If such message is passed to HCI core than pairing will essentially fail.
+ * Solution: Rewrite the event with the RPA in the PEER address field
+ */
+	struct bt_hci_evt_le_meta_event *mev =
+			(struct bt_hci_evt_le_meta_event *)&tev->payload;
+
+	if (tev->evtcode == BT_HCI_EVT_LE_META_EVENT &&
+			mev->subevent == BT_HCI_EVT_LE_ENH_CONN_COMPLETE) {
+		struct bt_hci_evt_le_enh_conn_complete *evt =
+				(struct bt_hci_evt_le_enh_conn_complete *)(mev + 1);
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: Are you sure this does the right thing? Doesn't the `(mev + 1)` in translate to `mev + 1 * sizeof(*mev)`? I.e. you need a `u8_t *` typecast somewhere there, I think, e.g. :  `(struct bt_hci_evt_le_enh_conn_complete *)((u8_t *)mev + 1)`

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 10 above)
Comment (jhedberg) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Which actually begs the question, did you test this? 😃

Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Yeap, i've tested it. And i was expecting here see the same: pointer incrimination by size of the struct, not simply as the integer. Without any modification to pointer calculation
`BT_WARN("%p %p", mev, evt);`
```
[00:00:09.560,900] <dbg> hci_ipm.TM_EvtReceivedCb: EVT: hcievt->evtserial.evt.evtcode: 0x3e
[00:00:09.560,900] <wrn> hci_ipm: 0x20038437 0x20038438
[00:00:09.561,100] <wrn> hci_ipm: Invalid peer addr ff:ff:ff:ff:ff:ff (random)
```
Seems like GCC is too smart.
But you right that it's making sense to cast pointer to u8_t* before addition.
Updated.

Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: > 
> 
> Which actually begs the question, did you test this? 😃

:) Yep, I've tested it. And there is some "pointer magic"

Comment (joerchan) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: sizeof(struct bt_hci_evt_le_meta_event) is 1 i think. But isn't that correct, you want to move past the struct and get the bytes after that?

Comment (jhedberg) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: > sizeof(struct bt_hci_evt_le_meta_event) is 1 i think. 

Indeed it is, and that explains why the pointer arithmetic gave the right result.

> But isn't that correct, you want to move past the struct and get the bytes after that?

Yes, you're right, I misunderstood the intent of the code since this kind of pointer arithmetic bugs happen quite easily with the special rules C has.

Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Got your point. Moving by hard-coded 1 byte offset is bad idea. Updated and added sizeof instead of hard code.

**Review by erwango — DISMISSED** [review]

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 11]
```diff
@@ -96,6 +96,37 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
 	BT_DBG("status:%d", status);
 }
 
+static void tryfix_event(TL_Evt_t *tev)
+{
+/*
+ * https://github.com/zephyrproject-rtos/zephyr/issues/19509
+ * Tested on BLE stack (v1.2.0)
```
[the remark this answers is not in the document]
Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Sure. Thank you for noticing. My comment is a bit confusing. Done

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 12]
```diff
@@ -96,6 +96,37 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
...
+			(struct bt_hci_evt_le_meta_event *)&tev->payload;
+	u8_t *ptr = ((u8_t *)mev + (sizeof(*mev)));
+
+	if (tev->evtcode == BT_HCI_EVT_LE_META_EVENT &&
+			mev->subevent == BT_HCI_EVT_LE_ENH_CONN_COMPLETE) {
+		struct bt_hci_evt_le_enh_conn_complete *evt =
+				(struct bt_hci_evt_le_enh_conn_complete *)ptr;
+		if (!bt_addr_cmp(&evt->peer_addr.a, BT_ADDR_NONE)) {
+			BT_WARN("Invalid peer addr %s", bt_addr_le_str(&evt->peer_addr));
+			if (bt_addr_cmp(&evt->peer_rpa, BT_ADDR_NONE)) {
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: This seems like an unnecessary branch if you haven't actually seen the controller report an invalid peer_rpa.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 13]
```diff
@@ -96,6 +96,37 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
...
+ */
+	struct bt_hci_evt_le_meta_event *mev =
+			(struct bt_hci_evt_le_meta_event *)&tev->payload;
+	u8_t *ptr = ((u8_t *)mev + (sizeof(*mev)));
+
+	if (tev->evtcode == BT_HCI_EVT_LE_META_EVENT &&
+			mev->subevent == BT_HCI_EVT_LE_ENH_CONN_COMPLETE) {
+		struct bt_hci_evt_le_enh_conn_complete *evt =
+				(struct bt_hci_evt_le_enh_conn_complete *)ptr;
+		if (!bt_addr_cmp(&evt->peer_addr.a, BT_ADDR_NONE)) {
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: Wouldn't `bt_addr_le_cmp(&evt->peer_addr, BT_ADDR_LE_NONE)` work?

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 14]
```diff
@@ -96,6 +96,37 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
 	BT_DBG("status:%d", status);
 }
 
+static void tryfix_event(TL_Evt_t *tev)
+{
+/*
+ * https://github.com/zephyrproject-rtos/zephyr/issues/19509
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: Normally code comments use the same indentation level as the code itself, meaning this comment block should be indented by one extra tab.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 15]
```diff
@@ -96,6 +96,37 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
...
+ * 0A 00 01 08 01 01 FF FF FF FF FF FF 00 00 00 00 00 00 0C AA C5 B3 3D 6B ...
+ * If such message is passed to HCI core than pairing will essentially fail.
+ * Solution: Rewrite the event with the RPA in the PEER address field
+ */
+	struct bt_hci_evt_le_meta_event *mev =
+			(struct bt_hci_evt_le_meta_event *)&tev->payload;
+	u8_t *ptr = ((u8_t *)mev + (sizeof(*mev)));
+
+	if (tev->evtcode == BT_HCI_EVT_LE_META_EVENT &&
+			mev->subevent == BT_HCI_EVT_LE_ENH_CONN_COMPLETE) {
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: This should be aligned with the opening ( on the first line

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 13 above)
Comment (joerchan) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: LE_NONE doesn't work because of the address type is public, but this one is random.

Comment (jhedberg) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Ok, fair point - just ignore this comment then

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 14 above)
Comment (jhedberg) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Alternatively, move the block right above the function (probably simpler since you've already got the text pre-formatted for the the full width)

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 12 above)
Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Have never seen station like that. Idea was just to be sure that we do not copy some new garbage. You right - keep i simple. Done

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 14 above)
Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Moved right above the function. Thanks.

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 15 above)
Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Oh, it even looks better. Thanks. Done.

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 16]
```diff
@@ -96,6 +96,37 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
...
+ * Solution: Rewrite the event with the RPA in the PEER address field
+ */
+static void tryfix_event(TL_Evt_t *tev)
+{
+	struct bt_hci_evt_le_meta_event *mev =
+			(struct bt_hci_evt_le_meta_event *)&tev->payload;
+	u8_t *ptr = ((u8_t *)mev + (sizeof(*mev)));
+
+	if (tev->evtcode != BT_HCI_EVT_LE_META_EVENT ||
+		mev->subevent != BT_HCI_EVT_LE_ENH_CONN_COMPLETE) {
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: Still not quite right :) It should be one tab and then 4 spaces to align with the same position as `tevt->evtcode` on the first line.

Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Ah, you are faster than I'm! just was seeking for example in the code. Done

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 17]
```diff
@@ -96,6 +96,37 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
...
+ * as it should, when this happens the peer address is set to all FFs
+ * 0A 00 01 08 01 01 FF FF FF FF FF FF 00 00 00 00 00 00 0C AA C5 B3 3D 6B ...
+ * If such message is passed to HCI core than pairing will essentially fail.
+ * Solution: Rewrite the event with the RPA in the PEER address field
+ */
+static void tryfix_event(TL_Evt_t *tev)
+{
+	struct bt_hci_evt_le_meta_event *mev =
+			(struct bt_hci_evt_le_meta_event *)&tev->payload;
+	u8_t *ptr = ((u8_t *)mev + (sizeof(*mev)));
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: This `ptr` variable seems a bit unnecessary - how come you don't just assign directly to `evt`? Even if you did have an intermediate variable wouldn't `void *` be better since it doesn't require explicit typecasting? (I'd still go for just dropping this variable however)

Comment (jhedberg) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: @pavlohamov btw, thanks for your patience with the reviews. Once this last small thing is sorted I think we can go and merge this.

Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: It's just a matter of fitting in one line. for one cast from ptr is much more clear than 
```
struct bt_hci_evt_le_enh_conn_complete *evt =
		(struct bt_hci_evt_le_enh_conn_complete *)((u8_t *)mev +
		(sizeof(*mev)));
```
No problem. Thank you for the pedantic review. During review I've learned couple of thing about zephyr HCI core. Now I understand the internals of HCI packet. at least one =)

Comment (jhedberg) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: You could do a `(void *)` cast to make the line shorter. It's equally valid (as in, the compiler won't complain) as the exact type on the left side of `=`

Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Make sense. Now two extra lines are saved. Thanks,

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 18]
```diff
@@ -96,6 +96,35 @@ static void syscmd_status_not(SHCI_TL_CmdStatus_t status)
...
+{
+	struct bt_hci_evt_le_meta_event *mev = (void *)&tev->payload;
+
+	if (tev->evtcode != BT_HCI_EVT_LE_META_EVENT ||
+	    mev->subevent != BT_HCI_EVT_LE_ENH_CONN_COMPLETE) {
+		return;
+	}
+
+	struct bt_hci_evt_le_enh_conn_complete *evt = (void *)((u8_t *)mev +
+			(sizeof(*mev)));
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c]: I'm going to approve now, since I feel like I've exceeded my "being pedantic" quota 😄 , but if you split it like this then you need to align it again with the right ( on the previous line since the second line continues something inside (). Alternatively, and what might be more readable, is to just split after the `=` so you have the full pointer manipulation on a single line.

**Review by jhedberg — APPROVED** [review]

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 18 above)
Comment (pavlohamov) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Got it. Done. On the one line ok

**Comment by joerchan** [comment]
@erwango Your comments have been addressed. Does it look ok?

**Review by carlescufi — APPROVED** [review]
