### PR TITLE
tests: drivers: can: timing: test that calculated timings can be set

### LINKED ISSUE #44482: drivers: can: mcan: CAN_SJW_NO_CHANGE not accepted with CONFIG_ASSERT=y
**Describe the bug**
The `__ASSERT_NO_MSG()` calls in `can_mcan_configure_timing()` does not allow for passing in `CAN_SJW_NO_CHANGE` causing calls to fail.

**Expected behavior**
`can_mcan_configure_timing()` should allow for passing in `CAN_SJW_NO_CHANGE`.

**Impact**
Prevents users (and test cases) to set timing without changing SJW in debug builds.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux v20.04 LTS
 - Toolchain: Zephyr SDK v0.14.0
 - Commit SHA: e04172fcef2c69992884246dcad3aa3727d56cd6

### LINKED ISSUE #44483: drivers: can: mcan: data phase prescaler bounds checking uses wrong value
**Describe the bug**
The `__ASSERT_NO_MSG()` call in `can_mcan_configure_timing()` uses 20 decimal instead of 0x20 to validate the upper limit for the data phase prescaler.

**Expected behavior**
`can_mcan_configure_timing()` should use the correct value for the upper limit of the data phase prescaler.

**Impact**
Prevents users (and test cases) to set certain timing in debug builds.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux v20.04 LTS
 - Toolchain: Zephyr SDK v0.14.0
 - Commit SHA: e04172fcef2c69992884246dcad3aa3727d56cd6

### LINKED ISSUE #44484: drivers: can: mcp2515: The MCP2515 driver uses wrong timing limits
**Describe the bug**
- The MCP2515 requires phase segment 2 to be at least 2 time quanta, but the driver allows `phase_seg2` to be 0x01.
- The MCP2515 prescaler has a 6 bit register, allowing for real-world prescaler values between 1 and 64, but the driver limits this to 0x20.

**Expected behavior**
Minimal `phase_seg2` should be 0x02 and maximum `prescaler` should be 0x40.

**Impact**
Prevents users (and test cases) to set certain timing. Allows for calculating timing values not valid for the device.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux v20.04 LTS
 - Toolchain: Zephyr SDK v0.14.0
 - Commit SHA: e04172fcef2c69992884246dcad3aa3727d56cd6

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
This patch set adds the following CAN timing test cases:
- tests: drivers: can: timing: test that calculated timings can be set
- tests: drivers: can: timing: test min/max timing can be set

The addition of these test cases revealed a few bugs, for which fixes are included:
- drivers: can: mcan: allow sjw == CAN_SJW_NO_CHANGE (Fixes: #44482)
- drivers: can: mcan: fix bounds check for data phase prescaler (Fixes: #44483)
- drivers: can: mcp2515: correct min/max timing values (Fixes: #44484)

Furthermore, the handler for `can_set_timing()` is changes to validate all parameters and copy them before calling the implementation.

The tested sample point locations for bitrates >= 800kbit/s have been modified to match those uses in the Linux kernel CAN layer as these seem to be much more likely to be met with 100% accuracy by a wide range of CAN controllers. I will follow up with a PR for changing the default sample point locations used by `can_set_bitrate()`.

### CODE REVIEW

File: tests/drivers/can/timing/src/main.c [hunk 1]
```diff
@@ -40,18 +40,18 @@ static const struct can_timing_test can_timing_tests[] = {
 	/** Standard bitrates. */
 	{  125000, 875, false },
 	{  500000, 875, false },
-	{ 1000000, 875, false },
+	{ 1000000, 750, false },
```
Comment (alexanderwachter) [inline tests/drivers/can/timing/src/main.c:43]: For diversification?

File: tests/drivers/can/timing/src/main.c [hunk 2]
```diff
@@ -193,6 +193,17 @@ static void test_timing_values(const struct device *dev, const struct can_timing
...
 		assert_sp_within_margin(&timing, test->sp, SAMPLE_POINT_MARGIN);
 
+		if (IS_ENABLED(CONFIG_CAN_FD_MODE)) {
+			if (data_phase) {
+				err = can_set_timing(dev, can_get_timing_min(dev), &timing);
+			} else {
+				err = can_set_timing(dev, &timing, can_get_timing_min_data(dev));
+			}
+		} else {
+			err = can_set_timing(dev, &timing, NULL);
```
Comment (alexanderwachter) [inline tests/drivers/can/timing/src/main.c:203]: Do you want to set the min timing here too?

Comment (karstenkoenig) [reply tests/drivers/can/timing/src/main.c:203]: the test case is supposed to try to set `timing`, not `min_timing`. 
I guess `min_timing` is used in the can-fd case to avoid setting the same timing configuration for both data and regular timings.

**Review by karstenkoenig — DISMISSED** [review]
Thanks for catching those mcp2515 off by one (bit) errors.... 
Was this marked draft by purpose? Looks small and self contained enough to be good enough as is?

File: tests/drivers/can/timing/src/main.c (hunk 1 above)
Comment (henrikbrixandersen) [reply tests/drivers/can/timing/src/main.c:43]: No. As described in the commit log, these sample point locations match those used by the Linux kernel and seem to be much more likely to be met with 100% accuracy by a wide range of CAN controllers.

File: tests/drivers/can/timing/src/main.c (hunk 2 above)
Comment (henrikbrixandersen) [reply tests/drivers/can/timing/src/main.c:203]: @karstenkoenig Exactly. We cannot set the same timing for both the arbitration and data phase as they may have different limits. Therefore, the data phase timing test simply uses the minimum timing allowed by the driver for the arbitration phase (at this point, that was already validated by another test case).

**Comment by henrikbrixandersen** [comment]
> Thanks for catching those mcp2515 off by one (bit) errors....

Welcome.

> Was this marked draft by purpose? Looks small and self contained enough to be good enough as is?

Yes, it was converted to draft on purpose. I needed to get a minor change in. It is ready for review now.

**Review by karstenkoenig — DISMISSED** [review]

**Comment by henrikbrixandersen** [comment]
Rebased to fix an issue with passing non-NULL `timing_data_copy` even if user passed NULL `timing_data`.

**Review by alexanderwachter — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@karstenkoenig Please re-review.

**Review by martinjaeger — APPROVED** [review]
