### PR TITLE
Fix implicit function declaration warning for subsys/net/lib/http/http_server_http1.c

### LINKED ISSUE #74843: Posix API `strnlen` declaration not found in native_posix/native_sim
https://github.com/zephyrproject-rtos/zephyr/actions/runs/9638989345/job/26580638001?pr=74706

``` C
/__w/zephyr/zephyr/subsys/net/lib/http/http_server_http1.c
/__w/zephyr/zephyr/subsys/net/lib/http/http_server_http1.c: In function ‘dynamic_get_req’:
/__w/zephyr/zephyr/subsys/net/lib/http/http_server_http1.c:104:35: error: implicit declaration of function ‘strnlen’; did you mean ‘strlen’? [-Werror=implicit-function-declaration]
  104 |                                   strnlen(http_response,                \
      |                                   ^~~~~~~
/__w/zephyr/zephyr/subsys/net/lib/http/http_server_http1.c:116:15: note: in expansion of macro ‘SEND_RESPONSE’
  116 |         ret = SEND_RESPONSE(RESPONSE_TEMPLATE_CHUNKED,
      |               ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

I'm also checkout zephyr-3.5.0, this branch build passed, and also compare build command:

**zephyr-3.5.0**
```C
"command": "/usr/bin/gcc -DKERNEL -D_POSIX_C_SOURCE=200809 -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -DK_HEAP_MEM_POOL_SIZE=0 -D__ZEPHYR__=1 -I/home/mi/works/github/zephyrproject/zephyr/kernel/include
```
**main:**
```C
"command": "/usr/bin/gcc -DKERNEL -DK_HEAP_MEM_POOL_SIZE=0 -D__ZEPHYR__=1 -I/home/mi/works/github/zephyrproject/zephyr/kernel/include
```

### PR DESCRIPTION
**Pull request by aescolar**
subsys/net/lib/http: Set feature macro as required
    
    This file uses strnlen() but the C library is not require to expose its prototype unless
    _POSIX_C_SOURCE is defined.
    So let's define it to avoid an implicit function declaration warning.

-------

    tests/net/lib/http_server/hpack: Exclude native_posix
    
    This test explicitly enables the POSIX_API which is not compatible with native_posix.
    Let's exclude this target.
    
Fixes #74843

### CODE REVIEW

**Review by kartben — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
I guess this is fine now, but (and I don't want to rattle any cages) this does depend on the used `libc`, right?

**Review by rlubos — APPROVED** [review]

**Review by LingaoM — APPROVED** [review]

File: subsys/net/lib/http/http_server_http1.c [hunk 1]
```diff
@@ -5,6 +5,9 @@
  * SPDX-License-Identifier: Apache-2.0
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_http1.c:5]: Usually there is no need to mention the path in the commit subject i.e., the `subsys` is kind of redundant information.

Comment (aescolar) [reply subsys/net/lib/http/http_server_http1.c:5]: You are right :)
