### PR TITLE
net: ip: Fix checksum calculation/validation for fragmented packets

### LINKED ISSUE #60822: net: Checksum offload breaks IP fragmentation
**Describe the bug**
When IP fragmentation is enabled and if a driver support TCP/IP checksum offload then all packets will be dropped by the driver (or device) as checksum should be calculated before fragmentation and verified after re-assembly. This only works when fragmentation/re-assembly is also offloaded to driver.

**To Reproduce**
1. Enable either `NET_IPV4_FRAGMENT` or `NET_IPV6_FRAGMENT`
2. Choose a networking device with checksum offload support (I have used a downstream device)
3. `net ping <IP> -s 1473` to trigger IP fragmentation

**Expected behavior**
Offloaded ping should work. (Applicable for UDP/TCP as well)

**Impact**
Its a showstopper.

**Logs and console output**
NA

**Environment (please complete the following information):**
 - OS: Zephyr
 - Toolchain: Zephyr SDK
 - Downstream fork

**Additional context**
Linux has couple of solutions for this problem: See https://elixir.bootlin.com/linux/latest/source/include/linux/skbuff.h#L97

1. Per-packet checksum decision
    - Each packet has a field to indicate whether driver/HW has calculated the checksum or not, so, for this case Driver can mark as `CHECKSUM_NONE` to fallback to SW checksum
2. Leverage HW for payload
    - RX case: `CHECKSUM_COMPLETE` HW does a 1's complement checksum for the payload (as submitted to networking stack) and stack can use that to derive other checksums by basic arithmetic like deleting sub-checksums from the final one and finally fold it and verify
    - TX case: AFAIK, this is still a problem in Linux, as device would need to loop through all frags and update checksum in packet.

For now checksum offload is disabled when IP fragmentation is enabled, but we need to extend existing checksum capabilities in Zephyr to cope with such cases.

### PR DESCRIPTION
**Pull request by rlubos**
In case HW checksum offloading was enabled on an interface, the checksum calculation/verification was broken for IP fragmented packets. This PR fixes this:
  * Always calculate/verify checksum for IP fragmented packets, regardless of the HW offloading capability
  * `chksum_done` flag is introduced, to indicate checksum status on the net_pkt, which can be used by drivers to determine whether checksum calculation is needed (unless they detect IP fragments automatically, like `eth_stm32_hal.c`, which has been used to verify the functionality on HW),
  * A set of new test cases was introduced, to verify checksums are calculated properly on for fragmented packets
  * Further cleanup in existing checksum offloading tests cases, to reduce code duplication.

Fixes #60822

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]
Not an expert on this, subsystem changes seem logical, but testing part I haven't reviewed thoroughly.

**Comment by pdgendt** [comment]
Would be nice to get feedback from the issue author @krish2718 if this PR fixes it.

File: include/zephyr/net/net_pkt.h [hunk 1]
```diff
@@ -194,6 +194,9 @@ struct net_pkt {
 	uint8_t l2_processed : 1; /* Set to 1 if this packet has already been
 				   * processed by the L2
 				   */
+	uint8_t chksum_done : 1; /* L4 Checksum has already been computed for
```
Comment (krish2718) [inline include/zephyr/net/net_pkt.h:197]: This is used by L3 (IP) as well, no? also if you want abbreviate `csum` might be better?

File: include/zephyr/net/net_pkt.h [hunk 2]
```diff
@@ -836,6 +836,20 @@ static inline void net_pkt_set_ipv6_fragment_id(struct net_pkt *pkt,
 }
 #endif /* CONFIG_NET_IPV6_FRAGMENT */
 
+static inline bool net_pkt_is_ip_reassembled(struct net_pkt *pkt)
+{
+	if ((IS_ENABLED(CONFIG_NET_IPV4_FRAGMENT) &&
+	     net_pkt_family(pkt) == AF_INET &&
+	     net_pkt_ipv4_fragment_more(pkt)) ||
```
Comment (krish2718) [inline include/zephyr/net/net_pkt.h:843]: If its re-assembled won't the more_frags be 0?

File: tests/net/checksum_offload/src/main.c [hunk 3]
```diff
@@ -204,6 +271,61 @@ static void test_receiving(struct net_pkt *pkt)
...
+			hdr_offset += sizeof(struct net_udp_hdr);
+		} else if (test_proto == IPPROTO_ICMP ||
+			   test_proto == IPPROTO_ICMPV6) {
+			chksum = get_icmp_chksum(pkt);
+			hdr_offset += sizeof(struct net_icmp_hdr) +
+				      sizeof(struct net_icmpv6_echo_req);
+		}
+
+		/* Fragmented packet should have checksum set regardless of
+		 * chksum offloading
```
Comment (krish2718) [inline tests/net/checksum_offload/src/main.c:304]: checksum

File: include/zephyr/net/net_pkt.h (hunk 1 above)
Comment (rlubos) [reply include/zephyr/net/net_pkt.h]: I think we can drop L4 here, we either calculate either both (L3/L4) checksums or none anyway.
As for the abbreviation, I'd prefer to stick to `chksum`, as it's already widely used in Zephyr, in checksum related routines.

File: include/zephyr/net/net_pkt.h (hunk 2 above)
Comment (rlubos) [reply include/zephyr/net/net_pkt.h:843]: I was puzzled about this part of code (note, that I've just moved it from other place) as well, but it turned out, that the fragmentation code re-uses the first fragment packet as a base for the reassembled one, so the more flag (for Ipv6) or frag offset (for IPv6) would be only on those reassembled packets (and only on them).

**Comment by rlubos** [comment]
@krish2718 I've pushed an updated version.

**Review by jukkar — DISMISSED** [review]

File: include/zephyr/net/net_pkt.h (hunk 2 above)
Comment (krish2718) [reply include/zephyr/net/net_pkt.h:843]: Ah, I thought those flags would be reset as once re-assembled they are of no use, but https://datatracker.ietf.org/doc/html/rfc791 doesn't say so, so, I guess it should work.

But this also means if someone uses that helper on each-fragment then it would falsely returns true, encording `fragment_offset == 0 && more_frags == 1` might mitigate this, then its a question of first fragment or reassembled packet.

Comment (rlubos) [reply include/zephyr/net/net_pkt.h:843]: I can add an explicit flag to `net_pkt` structure to indicate that packet is IP reassembled. There should be no ambiguity then.

Comment (krish2718) [reply include/zephyr/net/net_pkt.h:843]: Ah, so, the L2 driver should set this flag? If yes, that should work, as the stack has no way of knowing its 1st fragment or re-assembled frame.

Comment (rlubos) [reply include/zephyr/net/net_pkt.h:843]: No, L2 has nothing to do with fragmentation. The flag would be off by default, and only set if the IP layer reassembled the packet.

Comment (krish2718) [reply include/zephyr/net/net_pkt.h:843]: Ok, I guess we needn't worry about frag-reassembly offload.

**Comment by rlubos** [comment]
@jukkar @krish2718 Added one extra commit on top, adding an explicit flag to indicate that the packet has been IP reassembled (instead of using some ambiguous logic).

File: include/zephyr/net/net_pkt.h [hunk 4]
```diff
@@ -194,7 +194,12 @@ struct net_pkt {
 	uint8_t l2_processed : 1; /* Set to 1 if this packet has already been
 				   * processed by the L2
 				   */
-
+	uint8_t chksum_done : 1; /* Checksum has already been computed for
+				  * the packet.
+				  */
+#if defined(CONFIG_NET_IPV4_FRAGMENT) || defined(CONFIG_NET_IPV6_FRAGMENT)
+	uint8_t ip_reassembled : 1; /* Packet is an reassembled IP packet. */
```
Comment (pdgendt) [inline include/zephyr/net/net_pkt.h:201]: Nit
```suggestion
	uint8_t ip_reassembled : 1; /* Packet is a reassembled IP packet. */
```

File: include/zephyr/net/net_pkt.h [hunk 5]
```diff
@@ -822,6 +838,35 @@ static inline void net_pkt_set_ipv6_fragment_id(struct net_pkt *pkt,
 }
 #endif /* CONFIG_NET_IPV6_FRAGMENT */
 
+#if defined(CONFIG_NET_IPV4_FRAGMENT) || defined(CONFIG_NET_IPV6_FRAGMENT)
```
Comment (pdgendt) [inline include/zephyr/net/net_pkt.h:841]: **A more general remark, definitely not something this PR should do;**

The code base has a lot of `#if defined(CONFIG_NET_IPV4_<feature>) || defined(CONFIG_NET_IPV6_<feature>)`,
I think we could use a hidden Kconfig to our advantage here:

```cfg
config NET_IP_FRAGMENT
	bool
	default y
	depends on NET_IPV4_FRAGMENT || NET_IPV6_FRAGMENT
```

And use this option in code:

```c
#ifdef CONFIG_NET_IP_FRAGMENT
/* Insert code */
#endif
```

Disclaimer: This is the lazy me, who wants to type/copy less, talking.

Comment (rlubos) [reply include/zephyr/net/net_pkt.h]: Good point actualy, I've added one more commit introducing the hidden symbol for IP fragmentation.

**Review by pdgendt — DISMISSED** [review]

**Review by jukkar — APPROVED** [review]

**Review by krish2718 — APPROVED** [review]
