### PR TITLE
drivers/clock_control: stm32 L0,L1 fix STM32_SRC_PLLCLK calculation

### LINKED ISSUE #47105: drivers: clock_control: stm32 common: wrong PLLCLK rate returned
**Describe the bug**
The clock_control_get_subsys_rate() calls returns the wrong frequency value for the PLLCLK clock source on the affected STM32 targets. This is a result of using the wrong PLL source frequency in the calculation.

**Expected behavior**
As long as the PLLCLK is enabled, the correct frequency value should be returned otherwise 0.

**Impact**
The PLLCLK frequency can't be queried on most SOCs of the stm32_ll_common driver.
Affected: STM32G0, STM32G4, STM32L0, STM32L1, STM32L4, STM32L5, STM32WB, STM32WL.

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Zephyr main (a1ef368094)

### PR DESCRIPTION
**Pull request by str4t0m**
Some Series were calculating the pll output frequency from an
clock source index instead of the clock source frequency.

This commit resolves this issue for l0, l1 and removes an unused function for f2, f4, f7.

fixes #47105

### CODE REVIEW

File: drivers/clock_control/clock_stm32l0_l1.c [hunk 1]
```diff
@@ -41,6 +41,22 @@ static uint32_t get_pll_source(void)
 	return 0;
 }
 
+/**
+ * @brief get the pll source frequency
+ */
+__unused
+uint32_t get_pllsrc_frequency(void)
```
Comment (stephanosio) [inline drivers/clock_control/clock_stm32l0_l1.c:48]:
```suggestion
static uint32_t get_pllsrc_frequency(void)
```

**Review by erwango — DISMISSED** [review]
Approved, but please fix comment from @stephanosio

**Review by erwango — DISMISSED** [review]

File: drivers/clock_control/clock_stm32l0_l1.c (hunk 1 above)
Comment (str4t0m) [reply drivers/clock_control/clock_stm32l0_l1.c:48]: This function is declared in clock_stm32_ll_common.h:51such that that the variant specific implementations can be used in clock_stm32_ll_common.c. While clock_stm32_ll_common doesn't use it in the case of stm32l0 and stm32l1 I couldn't mark it static just like that.

**Comment by str4t0m** [comment]
Test failure is unrelated, caused by unknown dt vendor prefix "ultrachip"

File: drivers/clock_control/clock_stm32l0_l1.c (hunk 1 above)
Comment (stephanosio) [reply drivers/clock_control/clock_stm32l0_l1.c:48]: Fair enough.

**Comment by erwango** [comment]
> Test failure is unrelated, caused by unknown dt vendor prefix "ultrachip"

@str4t0m Can  you rebase, now that a fix was merged for this ?

**Review by erwango — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM
