### PR TITLE
modules: lvgl: fix initialization order

### LINKED ISSUE #62753: lvgl: hello world sample crashes
**Describe the bug**
Running the zephyr lvgl sample on any commit after `c7292efbda9902579966657ae5bc514bcda7033b` (target: native_posix) leads to a  segfault.

Please also mention any information which could help others to understand
the problem you're facing:
- The issue is that the drivers are now initialized before the default display [lvgl.c#L252](https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/lvgl/lvgl.c#L252). LVGL requires the presence of the display before any drivers, which are group and therefore display related, are instantiated.

**To Reproduce**
1. west build -b native_posix -d build vendor/zephyr/samples/subsys/display/lvgl
2. west build -t run -d build 

**Expected behavior**
The sample should not crash.

**Impact**
Encoder devices are not usable anymore.

### PR DESCRIPTION
**Pull request by faxe1008**
Adds init priority to ensure the following initialization order:
1. Hardware devices (screens, buttons)
2. LVGL prerequisits (heap, rendering setup)
3. Input subsystem
4. LVGL pseudo devices

This resolves #62753.

### CODE REVIEW

File: modules/lvgl/Kconfig [hunk 1]
```diff
@@ -12,6 +12,10 @@ config LVGL
 
 if LVGL
 
+config LV_Z_SYS_INIT_PRIORITY
+	int
+	default 90
```
Comment (pdgendt) [inline modules/lvgl/Kconfig:17]: Add a prompt to allow for the user to modify the value?

Comment (faxe1008) [reply modules/lvgl/Kconfig]: True, added this. Also for the other priority defined by the module.

**Review by pdgendt — DISMISSED** [review]

File: modules/lvgl/lvgl.c [hunk 2]
```diff
@@ -244,9 +244,12 @@ static int lvgl_init(void)
 	return 0;
 }
 
-BUILD_ASSERT(CONFIG_APPLICATION_INIT_PRIORITY < CONFIG_LV_Z_INPUT_INIT_PRIORITY);
+/* Display device needs to be ready */
+BUILD_ASSERT(CONFIG_KERNEL_INIT_PRIORITY_DEVICE < CONFIG_LV_Z_SYS_INIT_PRIORITY);
```
Comment (gmarull) [inline modules/lvgl/lvgl.c:248]: `CONFIG_DISPLAY_INIT_PRIORITY`. Note that (hopefully) device init priorities will disappear soon.

File: modules/lvgl/lvgl.c [hunk 3]
```diff
@@ -244,9 +244,12 @@ static int lvgl_init(void)
...
+/* Heap needs to be initialized first */
+BUILD_ASSERT(CONFIG_LV_Z_SYS_INIT_PRIORITY < CONFIG_LV_Z_INPUT_INIT_PRIORITY);
 #ifdef CONFIG_INPUT
 BUILD_ASSERT(CONFIG_INPUT_INIT_PRIORITY < CONFIG_LV_Z_INPUT_INIT_PRIORITY);
 #endif /* CONFIG_INPUT */
 
-SYS_INIT(lvgl_init, APPLICATION, CONFIG_APPLICATION_INIT_PRIORITY);
+SYS_INIT(lvgl_init, POST_KERNEL, CONFIG_LV_Z_SYS_INIT_PRIORITY);
```
Comment (gmarull) [inline modules/lvgl/lvgl.c:255]: if this is needed by "pseudo-drivers", then we have a problem with this design. Driver's dependencies on SYS_INIT should be avoided, and this is why I've always been very skeptical about using device-tree for non-hardware related stuff.

**Review by gmarull — CHANGES_REQUESTED** [review]

**Comment by gmarull** [comment]
> Adds init priority to ensure the following initialization order:
> 
> 1. Hardware devices (screens, buttons)
> 2. LVGL prerequisits (heap, rendering setup)
> 3. Input subsystem
> 4. LVGL pseudo devices
> 
> This resolves issue #62753.

The init sequence described here means that pseudo-devices are a problem, and we should be careful about allowing them in the future. The main problem here is that devicetree has been abused for something that it's not real hardware, and as it can be seen here, it actually has software dependencies that, of course, devicetree can't capture. This was being solved by hiding the problem behind init levels. I already expressed my concerns when this was being reviewed, and now we see this firing back.

I think software devices should stay away from devicetree, even likely from device model. I'll think about this.

File: modules/lvgl/lvgl.c (hunk 3 above)
Comment (faxe1008) [reply modules/lvgl/lvgl.c:255]: Hmm I get your concern regarding this, putting pseudo devices into the device tree is unusual. 
The main benefits that imo it brings to the table are:
- it reduces boilerplate
- it allows for easy per instance configuration
- properties can be expressed in yaml files

A solution I could imagine is still using the yaml files for configuring them but move the instantiation to the source using macrobatics:
```
PSEUDO_DEVICE_DEFINE(compat, <per device specific config struct>);
```
The initialization would happen with a `SYS_INIT`. This would be my rough idea, needs to be validated ofc. What do you think?

Comment (gmarull) [reply modules/lvgl/lvgl.c:255]: So the main problem I see in the current design is that LVGL init code (subsystem/module code) needs to be run before LVGL pseudo-devices, but after Kernel display devices. I'd consider a more reasonable design:

1. Kernel devices are initialized (no dependencies on 3rd party stuff)
2. LVGL is initialized, together with all its pseudo-devices.

This means we can leave Kernel alone and break its interdependency on a 3rd party module. I see a couple of solutions to this problem:

1. Keep using devicetree, but avoid using device model infrastructure. Overall, it looks like LVGL pseudo-devices can be freely initialized after all Kernel devices. So having an array of pseudo-device init calls run at lvgl_init would be enough (again, not using device model).
2. Avoid usage of devicetree and device model altogether. Simply provide a set of macros to statically define N pseudo-devices in C code. By using stuff like iterable sections, you can put all of them together and initialize them in lvgl_init.

(1) is a kind of "easy fix", (2) is more a change of paradigm, even though is what one usually sees in many other projects.

Comment (fabiobaltieri) [reply modules/lvgl/lvgl.c:255]: How about: let the input device initialize but don't register them (i.e. drop `lv_indev_drv_register` from the individual drivers). Then in `lvgl_init`, after lvgl is initialized, cycle through all the various `zephyr,lvgl...input` devices and register them all.

You keep the tree, you can init all the input devices at `INPUT_INIT_PRIORITY` and drop a custom priority symbol, LVGL can initialze whenever after the devices.

**Comment by fabiobaltieri** [comment]
> I think software devices should stay away from devicetree, even likely from device model. I'll think about this.

I think it's fine, we just need to be careful with what to do in their init functions and keep calls that belong to higher level services off them.

**Comment by gmarull** [comment]
> > I think software devices should stay away from devicetree, even likely from device model. I'll think about this.
> 
> I think it's fine, we just need to be careful with what to do in their init functions and keep calls that belong to higher level services off them.

I'm fine with this if they do not implicitly insert other software dependencies in the Kernel devices (which can't be tracked and end up affecting the whole init sequence).

**Comment by fabiobaltieri** [comment]
> I'm fine with this if they do not implicitly insert other software dependencies in the Kernel devices (which can't be tracked and end up affecting the whole init sequence).

Yeah I think that would play pretty well with the model we are going to where services are always initialized after devices.

File: modules/lvgl/lvgl.c (hunk 3 above)
Comment (faxe1008) [reply modules/lvgl/lvgl.c:255]: @fabiobaltieri I really like your solution, solves the problem at hand and actually simplifies priority handling. @gmarull would this be also a reasonable approach for you?

Comment (gmarull) [reply modules/lvgl/lvgl.c:255]: makes sense

**Comment by faxe1008** [comment]
Implemented  your suggestion @fabiobaltieri, unsure about the error propagation since macros with flowcontrol are not ideal.

File: modules/lvgl/input/lvgl_encoder_input.c [hunk 4]
```diff
@@ -64,7 +59,7 @@ static int lvgl_encoder_input_init(const struct device *dev)
 		.button_input_code = BUTTON_CODE(inst),                                            \
 	};                                                                                         \
 	static struct lvgl_common_input_data lvgl_common_input_data_##inst;                        \
-	DEVICE_DT_INST_DEFINE(inst, lvgl_encoder_input_init, NULL, &lvgl_common_input_data_##inst, \
+	DEVICE_DT_INST_DEFINE(inst, NULL, NULL, &lvgl_common_input_data_##inst,                    \
```
Comment (fabiobaltieri) [inline modules/lvgl/input/lvgl_encoder_input.c:62]: how about leaving the input function there (it has the device type and may need to do something else as well in the future) and instead you only defer `lv_indev_drv_register` to `lvgl_init_input_devices`? I'm thinking that that would allow you to group all type together in an array of 'struct device' and make that code a bit less quirky.

Comment (faxe1008) [reply modules/lvgl/input/lvgl_encoder_input.c:62]: Unsure if I understood correctly, but e.g. `lv_indev_set_button_points(data->indev ...` depends on `data->indev` which is the result of `lv_indev_drv_register`. So I guess at least for the button this is not possible.

Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_encoder_input.c:62]: Oh I see, that's unfortunate. Then I would say leave the spcific initializers in their own files, just drop the static and call them from `lvgl_init_input_devices`, basically the pattern you did here already for `lvgl_init_button_device` but for encoder and pointer as well. Just looking into leaking as few device type details out of their individual files as possible.

File: modules/lvgl/input/lvgl_common_input.c [hunk 5]
```diff
@@ -52,3 +55,21 @@ int lvgl_input_register_driver(lv_indev_type_t indev_type, const struct device *
 
 	return 0;
 }
+
+#define LV_DEV_INIT(node_id, init_fn, ret) ret |= init_fn(DEVICE_DT_GET(node_id));
```
Comment (fabiobaltieri) [inline modules/lvgl/input/lvgl_common_input.c:59]: not a big fan of trying to go forward with initialization with partial failures, if this errors out there's probably something real bad going on.

I would do this as
```c
#define LV_DEV_INIT(node_id, init_fn) do { \
        int ret = init_fn(DEVICE_DT_GET(node_id)); \
        if (ret) { \
                return ret; \
        } while (0)
```

(like https://github.com/zephyrproject-rtos/zephyr/blob/f007f21b3ce2b85f941e8b5d1fc6386ee7fc45d3/lib/os/cbprintf_complete.c#L1366C24-L1373, I think that the do loop is not strictly necessary with GCC but I'm not quite lucky with compiler quirks these days...)

Then `lvgl_init_input_devices` would just call the foreach, use the non VARGS version and `return 0` at the end.

Note that with @gmarull https://github.com/zephyrproject-rtos/zephyr/pull/61986 this would become super simple since it moves the callback in the struct device, but for now I think this is good, we can revisit later.

File: modules/lvgl/input/lvgl_common_input.c [hunk 6]
```diff
@@ -52,3 +55,21 @@ int lvgl_input_register_driver(lv_indev_type_t indev_type, const struct device *
...
+				     lvgl_pointer_input_init, ret)
+
+	DT_FOREACH_STATUS_OKAY_VARGS(zephyr_lvgl_button_input, LV_DEV_INIT, lvgl_button_input_init,
+				     ret)
+
+	DT_FOREACH_STATUS_OKAY_VARGS(zephyr_lvgl_encoder_input, LV_DEV_INIT,
+				     lvgl_encoder_input_init, ret)
+
+	return ret;
+}
```
Comment (gmarull) [inline modules/lvgl/input/lvgl_common_input.c:75]: note that with iterable sections you can gather all init calls in a single array and call them in a loop. wouldn't it be a better option?

Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_common_input.c:75]: https://github.com/zephyrproject-rtos/zephyr/pull/61986 would be best, you just find all the struct devices and call `dev->init()` on them.

Iterable section would be cool but I'm wondering if it's worth setting that up considering that it'll be torn down once the one above gets IMO. What do you think?

Comment (gmarull) [reply modules/lvgl/input/lvgl_common_input.c:75]: even if we have dev->init, I'd like to implement deferred init first (it likely will imply managing dependencies properly, even if in this case it does not apply)

Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_common_input.c:75]: ok so you think iterable section for this in the meantime? I'm happy with either, bit of a hassle to set up the section but then it's nice that the init functions could stay static. @faxe1008 what do you think?

Comment (faxe1008) [reply modules/lvgl/input/lvgl_common_input.c:75]: @gmarull I'd love that but how do I associate the devices init function in a way so that they are not called during `POST_KERNEL`  "automatically"?

File: modules/lvgl/input/lvgl_common_input.c (hunk 5 above)
Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_common_input.c:59]: yikes... yeah maybe let's go with iterable sections as Gerard is suggesting on the other comment, may be the cleanest solution.

Sorry for kicking this around so much.

File: modules/lvgl/input/lvgl_common_input.c (hunk 6 above)
Comment (gmarull) [reply modules/lvgl/input/lvgl_common_input.c:75]: btw, we should think of these devices as input devices that have a custom API call to perform LVGL gluing. Could that call be common (ie single API call that `return lvgl_input_register_driver(x, dev);` where `x` is, e.g. `LV_INDEV_TYPE_POINTER` (stored in dev->config)?

File: modules/lvgl/input/lvgl_common_input.c (hunk 5 above)
Comment (gmarull) [reply modules/lvgl/input/lvgl_common_input.c:59]: well guys, let's not overengineer this, just throwing some ideas :-) I'm fine with any reasonable solution, as soon as it does not insert soft dependencies in the init chain.

File: modules/lvgl/input/lvgl_common_input.c (hunk 6 above)
Comment (gmarull) [reply modules/lvgl/input/lvgl_common_input.c:75]: I realize this will insert 3rd party module glue code in include/zephyr/linker/common-rom/common-rom-misc.ld, which is not ideal (IIRC this is due to a bug in xtensa on iterable sections, because they could be defined in an ld file placed wherever you want).

Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_common_input.c:75]: Is it a problem? Would go behind a #if guard I imagine

Comment (gmarull) [reply modules/lvgl/input/lvgl_common_input.c:75]: yeah, just that glue code is usually restricted to `modules/`

Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_common_input.c:75]: Ok, I'll press the green button and say this is fine as is. :-)

**Review by fabiobaltieri — DISMISSED** [review]

File: modules/lvgl/input/lvgl_common_input.c (hunk 6 above)
Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_common_input.c:75]: ...apart from the undefined reference in CI...

File: modules/lvgl/input/lvgl_common_input.c (hunk 5 above)
Comment (gmarull) [inline modules/lvgl/input/lvgl_common_input.c:59]: `|` should be avoided for signed integers, so Fabio's early return versions seems more appropriate

File: modules/lvgl/input/lvgl_common_input.c (hunk 6 above)
Comment (faxe1008) [reply modules/lvgl/input/lvgl_common_input.c:75]: Sure would be possible but I'd rather pick the actual init methods, since it also cares about setting up device specific configs.  Do I understand correctly that you suggest declaring a structure like:
```
struct lvgl_pseudo_device {
       const struct device* dev;
       init_fn fn;
};
```
And store those in a new iterable section?

**Review by gmarull — COMMENTED** [review]
fine as is, would probably suggest looking if a single init function prototype is possible, otherwise lgtm

File: modules/lvgl/input/lvgl_common_input.c (hunk 5 above)
Comment (faxe1008) [reply modules/lvgl/input/lvgl_common_input.c:59]: Yup, but is the checkpatch issue accetable then? `ARNING:MACRO_WITH_FLOW_CONTROL: Macros with flow control statements should be avoided`

Comment (gmarull) [reply modules/lvgl/input/lvgl_common_input.c:59]: I think so, it's an internal macro after all...

Comment (faxe1008) [reply modules/lvgl/input/lvgl_common_input.c]: Grateful for your help in hashing this one out :^)

File: modules/lvgl/input/lvgl_common_input.c [hunk 7]
```diff
@@ -52,3 +55,26 @@ int lvgl_input_register_driver(lv_indev_type_t indev_type, const struct device *
...
+{
+	int ret = 0;
+
+	DT_FOREACH_STATUS_OKAY_VARGS(zephyr_lvgl_pointer_input, LV_DEV_INIT,
+				     lvgl_pointer_input_init)
+
+	DT_FOREACH_STATUS_OKAY_VARGS(zephyr_lvgl_button_input, LV_DEV_INIT, lvgl_button_input_init)
+
+	DT_FOREACH_STATUS_OKAY_VARGS(zephyr_lvgl_encoder_input, LV_DEV_INIT,
+				     lvgl_encoder_input_init)
```
Comment (fabiobaltieri) [inline modules/lvgl/input/lvgl_common_input.c:77]: two things:
1. these needs some `;` at the end of the line
2. unfortunately it's possible for these device to be "okay" and the driver not being build, then this would build fail, so I'm afraid these will have to be enclosed in some `#if LV_Z_POINTER_INPUT` etc...

Comment (faxe1008) [reply modules/lvgl/input/lvgl_common_input.c:77]: Sure will add that.

> unfortunately it's possible for these device to be "okay" and the driver not being build,

Is that because any of the other prerequisites (e.g. CONFIG_LVGL) not being fulfilled?

**Review by gmarull — APPROVED** [review]

File: modules/lvgl/input/lvgl_common_input.c (hunk 7 above)
Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_common_input.c]: yeah, CONFIG_INPUT I think, regardless, that's the condition that enable the file that defines the function so all good

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@carlescufi could you merge this? checkpatch complains for `Macros with flow control statements should be avoided` but we think it's fine in this case.
