### PR TITLE
drivers: i2c_gecko: Fix mutation of config_info content

### LINKED ISSUE #25255: drivers: i2c: gecko: device config_info content mutated
The device config_info structure is intended to be read-only, and so the generic pointer stored in struct device is a pointer-to-const. The gecko driver removes this qualifier when casting the pointer to the device-specific type.  This removal is a violation of MISRA 11.8 as it evokes undefined behavior.

When the qualifier is preserved the driver does not build, because it modifies the object content at runtime.  Consequently the fix for this driver has been removed from #25248.

https://github.com/pabigot/zephyr/commits/nordic/issue/24745a provides the changes necessary to preserve const correctness.  When applied it produces the following diagnostic:

```
drivers/i2c/i2c_gecko.c:95:23: error: assignment of member 'freq' in read-only object
   95 |  config->i2cInit.freq = baudrate;
```

The driver must be updated to resolve this.

### PR DESCRIPTION
**Pull request by chrta**
Since the i2c init structure is moved from config_info to the stack,
this change requires 12 bytes more stack during driver initialization.

This fixes #25255

Signed-off-by: Christian Taedcke <christian.taedcke@lemonbeat.com>

### CODE REVIEW

File: drivers/i2c/i2c_gecko.c [hunk 1]
```diff
@@ -198,7 +197,6 @@ static const struct i2c_driver_api i2c_gecko_driver_api = {
 static struct i2c_gecko_config i2c_gecko_config_0 = {
```
Comment (pabigot) [inline drivers/i2c/i2c_gecko.c:197]: This could be made `const` and so put into flash, since `struct device` assumes it'll be in flash.  Same for the other instances.

**Review by pabigot — APPROVED** [review]
Looks like this should do it.  Recommend making the config structure const, but not required.

File: drivers/i2c/i2c_gecko.c (hunk 1 above)
Comment (chrta) [reply drivers/i2c/i2c_gecko.c]: done

**Review by sjg20 — APPROVED** [review]
