### PR TITLE
net: sockets: tls: Fix poll() handling during the handshake

### LINKED ISSUE #33330: Poll on DTLS socket returns -EAGAIN if bind & receive any data.
**Describe the bug**
I am running into a problem where poll() is called with timeout but returning 0 without waiting. This causes a busy-wait loop which is blocking lower-priority tasks (and essentially all tasks if time-slicing is not enabled). I am doing the following:

1. A DTLS socket is created
2. A call to bind() is done to open up a port.
3. It then loops poll() with a timeout to see if any data has been received on the socket.
4. If data is received, it will call recvfrom and handle the data.

The application is a CoAP server/client where a client call `sendto` starts the DTLS handshake. In other words, my end is a DTLS *client*.

It seems the problem is that bind() call will open up incoming data to be given to the socket FIFO without being given to mbedTLS.

https://github.com/zephyrproject-rtos/zephyr/blob/4626a577c48e566b82c51ccd23bd2fc885d8d765/subsys/net/lib/sockets/sockets.c#L364-L367

It seems like data is only given to mbedTLS when recv(from) or send(to) is called. So if any data comes in after bind() then this causes data to exist in the FIFO but it hasn't reached mbedTLS. Then from what I can see sockets_tls returns -EAGAIN in the `update_pollin` function because
1. Data is available to read
2. Handshake not completed
..but due to mentioned reasons, handshake hasn't even been started yet.

https://github.com/zephyrproject-rtos/zephyr/blob/4626a577c48e566b82c51ccd23bd2fc885d8d765/subsys/net/lib/sockets/sockets_tls.c#L1875-L1877

It will stay this way until the end of time since no handshake is started and will neither timeout nor ever finish.

I don't know if this is usage fault from my side, probably, but from what I can see even if my DTLS socket were to have the server role then if bind() is called and data is received then handshake would not be started and poll would still act this way because it seems like it's firstly when recvfrom is called that mbedTLS is fed the data and any data that comes in after bind() is called will just be put in the queue and not be given to mbedTLS. Please correct me if I'm wrong. Anyways in *my opinion* this kind of behavior is wrong and the case should  be handled. Please comment and advice, and I can implement a fix if it's deemed necessary.

**To Reproduce**
1. Create DTLS socket
2. bind() to some port
3. From extern send any data UDP data to said port
4. --> Poll will return 0 without waiting even if timeout is given.

**Expected behavior**
* If bind() is called and DTLS is set to be client, then if data is received and DTLS session is not established then the data should be discarded
* If bind() is called and DTLS is set to be server, then if data is received then poll() should say data is available and recvfrom start DTLS handshaking.

**Impact**
Showstopper, kinda, since the external library is using bind()/poll() combination. I could change it to recvfrom with some non-blocking flag and then check if data was received and then `k_msleep(1)` but it seems like a better solution to fix the root problem.

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Zephyr SDK
 - 89a90963343437378a462aa64431b2283b7c397a

**Additional context**

### PR DESCRIPTION
**Pull request by rlubos**
Current implementation of poll prepare/update could end up busy looping
if `poll()` function was called before/during DTLS client handshake
(i. e. `poll()` called before an initial `send()`).

Fix this, by monitoring the handshake semaphore, already available in
the tls_context structure for DTLS client instead of underlying socket.
After the handshake is complete, switch to monitoring the underlying
socket instead.

For DTLS server this is not needed, since the handshake is initiated in
the `recv()` function, therefore any incoming data should trigger the
handshake.

Fixes #33330

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
CC @emillindq Please have a look. Would be good if you could provie some feedback if it fixes the issue for you (I've tested it on my side and it worked fine with the scenario you've posted, but anyway).

**Review by jukkar — APPROVED** [review]

**Comment by emillindq** [comment]
@rlubos 
My test setup:
1. loop calling `poll()` with timeout 100ms (prio 2) and every time it returns it increases a counter.
2. A task running with prio 5 which is waiting 10ms, increases a number and printing "Run %d".
3. A loop in main (prio 0) printing the number which is increased by the first point (like "has called %d") every 1s.
4. Logging task prio set to 1.

This is the debug output without your fix.
```
[00:00:26.679,000] <inf> main: Run 2492
[00:00:26.689,000] <inf> main: Run 2493
[00:00:26.699,000] <inf> main: Run 2494
[00:00:26.709,000] <inf> main: Run 2495
[00:00:26.720,000] <inf> main: Run 2496
[00:00:26.730,000] <inf> main: Run 2497
[00:00:26.740,000] <inf> main: Run 2498
[00:00:26.750,000] <inf> main: Run 2499
[00:00:26.760,000] <inf> main: Run 2500
[00:00:26.770,000] <inf> main: Run 2501
[00:00:26.780,000] <inf> main: Run 2502
[00:00:26.790,000] <inf> main: Run 2503
[00:00:26.800,000] <inf> main: Run 2504
[00:00:26.811,000] <inf> main: Run 2505
####My note: sent UDP packet to port bound by bind()###
[00:00:27.401,000] <inf> main: has called 217
[00:00:28.401,000] <inf> main: has called 227
[00:00:29.401,000] <inf> main: has called 237
[00:00:30.401,000] <inf> main: has called 247
[00:00:31.402,000] <inf> main: has called 257
[00:00:32.402,000] <inf> main: has called 267
[00:00:33.402,000] <inf> main: has called 277
[00:00:34.402,000] <inf> main: has called 287
[00:00:35.402,000] <inf> main: has called 297
[00:00:36.402,000] <inf> main: has called 307
[00:00:37.402,000] <inf> main: has called 317
[00:00:38.402,000] <inf> main: has called 327
[00:00:39.402,000] <inf> main: has called 337
[00:00:40.402,000] <inf> main: has called 347
```
We can see that the lowest priority task is being blocked by both point 1 and 3 task, but that point 1 task is allowed to run every 100ms. Indicating a busy wait in poll(), which returns after timeout as expected.

With your fix:
```
[00:01:02.460,000] <inf> main: Run 6035
[00:01:02.471,000] <inf> main: Run 6036
[00:01:02.481,000] <inf> main: Run 6037
[00:01:02.491,000] <inf> main: Run 6038
[00:01:02.501,000] <inf> main: Run 6039
[00:01:02.508,000] <inf> main: has called 569
[00:01:02.511,000] <inf> main: Run 6040
[00:01:02.521,000] <inf> main: Run 6041
[00:01:02.531,000] <inf> main: Run 6042
[00:01:02.541,000] <inf> main: Run 6043
[00:01:02.551,000] <inf> main: Run 6044
[00:01:02.561,000] <inf> main: Run 6045
[00:01:02.572,000] <inf> main: Run 6046
[00:01:02.582,000] <inf> main: Run 6047
[00:01:02.592,000] <inf> main: Run 6048
[00:01:02.602,000] <inf> main: Run 6049
[00:01:02.612,000] <inf> main: Run 6050
[00:01:02.622,000] <inf> main: Run 6051
####Truncated by me####
[00:01:03.430,000] <inf> main: Run 6131
[00:01:03.440,000] <inf> main: Run 6132
[00:01:03.450,000] <inf> main: Run 6133
[00:01:03.460,000] <inf> main: Run 6134
[00:01:03.471,000] <inf> main: Run 6135
[00:01:03.481,000] <inf> main: Run 6136
[00:01:03.491,000] <inf> main: Run 6137
[00:01:03.501,000] <inf> main: Run 6138
[00:01:03.508,000] <inf> main: has called 579
[00:01:03.511,000] <inf> main: Run 6139
[00:01:03.521,000] <inf> main: Run 6140
[00:01:03.531,000] <inf> main: Run 6141
[00:01:03.541,000] <inf> main: Run 6142
[00:01:03.551,000] <inf> main: Run 6143

```
I confirmed it is fixed. Thank you!

**Comment by jukkar** [comment]
@rlubos any suggestion who could review and +1 to this one?

File: subsys/net/lib/sockets/sockets_tls.c [hunk 1]
```diff
@@ -1930,27 +1949,54 @@ static int ztls_poll_update_ctx(struct tls_context *ctx,
...
 	}
 
+	/* Check if the socket was waiting for the handshake to complete. */
+	if ((pfd->events & ZSOCK_POLLIN) &&
+	    ((*pev)->obj == &ctx->tls_established)) {
+		/* In case handshake is complete, reconfigure the k_poll_event
+		 * to monitor the underlying socket now.
+		 */
+		if ((*pev)->state != K_POLL_STATE_NOT_READY) {
+			ret = z_fdtable_call_ioctl(vtable, obj,
```
[the remark this answers is not in the document]
Comment (rlubos) [reply subsys/net/lib/sockets/sockets_tls.c:1967]: Initially (before the handshake is complete) the k_poll_event is configured to monitor `ctx->tls_established` semaphore, which indicates whether the handshake is complete or not (so that the poll() won't busy loop if some data is received before the handshake is initiated or is being handled in some other thread). After the semaphore indicates that the handshake is complete, we can monitor the underlying socket for data (as they will get processed by mbedTLS to indicate whether there's application data available or not), so the event is reconfigured.

File: subsys/net/lib/sockets/sockets_tls.c [hunk 2]
```diff
@@ -1930,27 +1949,54 @@ static int ztls_poll_update_ctx(struct tls_context *ctx,
...
+						   ZFD_IOCTL_POLL_PREPARE,
+						   pfd, pev, *pev + 1);
+			if (ret != 0 && ret != -EALREADY) {
+				return ret;
+			}
+
+			return -EAGAIN;
```
Comment (pfalcon) [inline subsys/net/lib/sockets/sockets_tls.c:1974]: Re: discussion above: I see, but please add comment here along the lines of: "signal to poll() that it should make (if needed) another iteration with the event reconfigured above".

Comment (rlubos) [reply subsys/net/lib/sockets/sockets_tls.c:1978]: Sure, I've added the comment.

**Comment by pfalcon** [comment]
Another question is about normal (STREAM) TLS sockets - is that condition already handled properly for them?

**Review by pfalcon — APPROVED** [review]
Thanks for the replies and updates. The patch looks reasonable, approving.
