### PR TITLE
drivers: nrf_clock_calibration: wait for sensor initialization

### LINKED ISSUE #20416: sample: sensor: fxos8700 issues
**Describe the bug**
After compiling the fxos8700 sample for the BBC Micro:bit  fails to boot with a fatal error.

The issue appears to be connected to an update to the nRF series die temperature sensing. (drivers: sensor: temp_nrf5: Code cleanup #17249). The 'blocking' aspects seem to create a interrupt deadlock.

I have not reaised a PR with changes as this has links to the nRF Clock Control Calibration;
```
config CLOCK_CONTROL_NRF_CALIBRATION_TEMP_DIFF
    int "Temperature change triggering calibration (in 0.25 degree units)"
    default 2
    depends on CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION && CLOCK_CONTROL_NRF && !CLOCK_CONTROL_NRF_FORCE_ALT && CLOCK_CONTROL
    help
      Calibration is triggered if the temperature has changed by at least
      this amount since the last calibration.
```

The issue may only exist on the nrf51 series as am unable to test on other devices.

**To Reproduce**
Follow steps indicated described sample, which need to be updated to use the WEST tool.

**Expected behavior**
Works as expected as in v1.14

**Impact**
Showstopper as appears to effect multiple sensors

**Screenshots or console output**

> [00:00:00.000,976] [1B][1;31m<err> os:  xpsr:  0x61000000[1B][0m
> [1B][1;31m--- 3 messages dropped ---
> [1B][0m[00:00:00.001,037] [1B][1;31m<err> os: Faulting instruction address (r15/pc): 0x0000449a[1B][0m
> [00:00:00.001,098] [1B][1;31m<err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0[1B][0m
> [00:00:00.001,159] [1B][1;31m<err> os: Current thread: 0x20000774 (unknown)[1B][0m
> [00:00:00.040,344] [1B][1;31m<err> os: Halting system[1B][0m

**Additional context**
If i amend the temp_nrf.c code to remove the block, the application works (well it boots and allows the accelerometer to be read).

**\drivers\sensor\nrf5\temp_nrf5.c**

Original Code:
```
	r = clock_control_async_on(data->hfclk_dev, NULL, &clk_data);
	__ASSERT_NO_MSG(!r);

	k_sem_take(&data->device_sync_sem, K_FOREVER);

	r = clock_control_off(data->hfclk_dev, 0);
	__ASSERT_NO_MSG(!r);
```

Amended Code:
```
	nrf_temp_task_trigger(NRF_TEMP, NRF_TEMP_TASK_START);

	k_sem_take(&data->device_sync_sem, K_MSEC(10));
```
Output post changes:

> ***** Booting Zephyr OS build zephyr-v2.0.0-1806-geaa6058ebdcf *****
> Setting sampling frequency
> [00:00:00.014,221] [1B][0m<dbg> FXOS8700.fxos8700_set_odr: Set ODR to 0x30[1B][0m
> [1B][1;31m--- 3 messages dropped ---
> [1B][0m[00:00:00.014,617] [1B][0m<dbg> FXOS8700.fxos8700_set_mt_ths: Set FF_MT_THS to 17[1B][0m
> [00:00:00.016,082] [1B][0m<dbg> temp_nrf5.temp_nrf5_sample_fetch: sample: 104[1B][0m
> [00:00:00.016,174] [1B][0m<dbg> temp_nrf5.temp_nrf5_channel_get: Temperature:26,0[1B][0m
> trigger_handler: sensor_sample_fetch 
> AX=  3.677493 AY= -2.911350 AZ= 12.411541 
> trigger_handler: sensor_sample_fetch 
> AX= 14.097059 AY=  0.612915 AZ=  0.153228 
> trigger_handler: sensor_sample_fetch 
> AX= 16.395492 AY=-14.250289 AZ= -1.072603 
> [00:00:12.276,245] [1B][0m<dbg> FXOS8700.fxos8700_handle_motion_int: FF_MT_SRC 0xa4[1B][0m
> [00:00:12.748,474] [1B][0m<dbg> FXOS8700.fxos8700_handle_motion_int: FF_MT_SRC 0x82[1B][0m
> [00:00:13.063,293] [1B][0m<dbg> FXOS8700.fxos8700_handle_motion_int: FF_MT_SRC 0x9e[1B][0m

### PR DESCRIPTION
**Pull request by pabigot**
When using the RC clock source a periodic calibration is invoked that
involves reading from the die temperature sensor.  The code did not
protect against execution order that caused the periodic calibration
to be invoked before the temperature sensor was initialized.

Update the temperature sensor to detect that it has not been
initialized and so should reject attempts to fetch a reading.

Update the calibration code to do nothing when temperature reading
fails.

Fixes #20416

### CODE REVIEW

**Comment by pabigot** [comment]
The failure on `bbc_microbit` can be replicated on `nrf51_pca10028` with the patch below.

```
diff --git a/boards/arm/nrf51_pca10028/nrf51_pca10028.dts b/boards/arm/nrf51_pca10028/nrf51_pca10028.dts
index aed232099f..8a8def2cbb 100644
--- a/boards/arm/nrf51_pca10028/nrf51_pca10028.dts
+++ b/boards/arm/nrf51_pca10028/nrf51_pca10028.dts
@@ -109,6 +109,14 @@
 	status = "okay";
 	sda-pin = <30>;
 	scl-pin = <7>;
+
+	mma8653fc@1d {
+		compatible = "nxp,fxos8700","nxp,mma8653fc";
+		reg = <0x1d>;
+		label = "MMA8653FC";
+		int1-gpios = <&gpio0 28 0>;
+		int2-gpios = <&gpio0 27 0>;
+	};
 };
 
 &i2c1 {
diff --git a/boards/arm/nrf51_pca10028/nrf51_pca10028_defconfig b/boards/arm/nrf51_pca10028/nrf51_pca10028_defconfig
index 94177e85d0..a4c5f8f413 100644
--- a/boards/arm/nrf51_pca10028/nrf51_pca10028_defconfig
+++ b/boards/arm/nrf51_pca10028/nrf51_pca10028_defconfig
@@ -16,3 +16,6 @@ CONFIG_UART_0_NRF_UART=y
 # enable console
 CONFIG_CONSOLE=y
 CONFIG_UART_CONSOLE=y
+
+CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
+CONFIG_CLOCK_CONTROL_NRF_K32SRC_250PPM=y
```

File: drivers/clock_control/nrf_clock_calibration.c [hunk 1]
```diff
@@ -194,8 +198,14 @@ static void measure_temperature(struct k_work *work)
 	s16_t diff;
 	bool started = false;
 	int key;
+	int rc;
+
+	rc = get_temperature(&temperature);
+	if (rc != 0) {
```
Comment (nordic-krch) [inline drivers/clock_control/nrf_clock_calibration.c]: It seems to be that leaving here will break calibration algorithm as state machine will stay with HF clock turned on and nothing started to change the state (no calibration or calibration timer active). When calibration initially starts then `calib_skip_cnt` is set to 0 to ensure that calibration will be performed in first attempt disregarding temperature measurement. Initial temperature measurement is used only to have value for next iteration to calculate diff. If temperature sensor does not return value, then it would be better to set temperature to some arbitrary value (something unrealistic like 150'C). That will result in additional calibration during next timeout due to temperature change.

Comment (pabigot) [reply drivers/clock_control/nrf_clock_calibration.c]: I'm not going to try tricks with temperatures; instead I've updated it to reset `cal_state` to the state that it was in when the callback determined it was necessary to invoke `measure_temperature()`.  Does that work?  If not I'd rather reassign this to you so you get a solution you're willing to maintain.

Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: Sorry for the delay. I've reproduced the problem. The proposed solution stops calibration because state machine stuck in that state as there is no asynchronous event to push it forward. I still think that simplest and most reasonable is to set unrealistic temperature. That will force calibration.

Something like:
```
if (rc != 0) {
  temperature = INT16_MAX;
  LOG_WRN("Temperature sensor not ready. Setting max temperature to enforce calibration.");
}
```

Initially, i thought about requesting temperature measurement again (`k_work_submit(&temp_measure_work)`) but that won't work as this work submit has higher priority so calling it recursively leads to deadlock.

**Comment by nordic-krch** [comment]
It would be good to extract `temp_nrf5.c` changes into independent commit.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 2]
```diff
@@ -190,16 +194,24 @@ static s16_t get_temperature(void)
...
 
-	temperature = get_temperature();
-	diff = abs(temperature - prev_temperature);
+	rc = get_temperature(&temperature);
 
 	key = irq_lock();
 
+	if (rc != 0) {
+		/* Temperature read failed: update state to try again */
+		cal_state = CAL_HFCLK_REQ;
```
Comment (nordic-krch) [inline drivers/clock_control/nrf_clock_calibration.c]: ok, i've tried it. What you can do here is to instead of setting `CAL_HFCLK_REQ` call `to_idle()`. That will restart calibration timer and make another attempt.

Comment (pabigot) [reply drivers/clock_control/nrf_clock_calibration.c]: Thanks; commit updated.

**Review by nordic-krch — APPROVED** [review]

**Comment by ioannisg** [comment]
@WilliamGFish could you test this bug-fix for #20416 ??

**Comment by nashif** [comment]
sample works for me with this fix...
```
[00:01:52.291,503] <dbg> temp_nrf5.temp_nrf5_sample_fetch: sample: 96
[00:01:52.291,625] <dbg> temp_nrf5.temp_nrf5_channel_get: Temperature:24,0
[00:01:56.292,755] <dbg> temp_nrf5.temp_nrf5_sample_fetch: sample: 96
[00:01:56.292,877] <dbg> temp_nrf5.temp_nrf5_channel_get: Temperature:24,0
[00:02:00.310,058] <dbg> temp_nrf5.temp_nrf5_sample_fetch: sample: 96
[00:02:00.310,180] <dbg> temp_nrf5.temp_nrf5_channel_get: Temperature:24,0
[00:02:04.311,309] <dbg> temp_nrf5.temp_nrf5_sample_fetch: sample: 96
[00:02:04.311,431] <dbg> temp_nrf5.temp_nrf5_channel_get: Temperature:24,0
```

**Comment by WilliamGFish** [comment]
> @WilliamGFish could you test this bug-fix for #20416 ??

Sorry not quick enough off the mark, but works great. Thanks all.

Billy..
