### PR TITLE
Bluetooth: ATT: Fix conn parameter to req cb in att_reset

### LINKED ISSUE #41794: Bluetooth: ATT calls GATT callbacks with NULL conn pointer during disconnect
**Describe the bug**
When disconnected `att_reset` will be called, which will run through all outstanding requests and will call their respective callbacks. The issue is that the callback functions are called with `conn == NULL`: 

```
		if (req->func) {
			req->func(NULL, BT_ATT_ERR_UNLIKELY, NULL, 0,
				  req->user_data);
		}
```

This `NULL` reference is then propagated up to the application-defined callbacks. 

The GATT API does not state that the `conn` pointer in the callbacks can ever be NULL, and in almost all (if not all) cases the `conn` pointer is never NULL checked in callbacks for this reason. 

**To Reproduce**
It is timing related, as a disconnect need to happen after sending an ATT request, but before getting a response. Can be trigger by continuously sending any ATT/GATT request. 

**Expected behavior**
The callback should be called with the correct `conn` pointer, in order for the application to properly handle it. 

**Impact**
It is a fatal error in some cases (e.g. in VCS (`vcs.c`) where we need to the connection pointer to get the specific VCS instance), but otherwise will be application specific how bit an issue this is. 

**Logs and console output**
MicrosoftTeams-image

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): N/A
 - Toolchain (e.g Zephyr SDK, ...): N/A
 - Commit SHA or Version used: 727ea490292255e3d0462f583fbc490a5c4936e4

**Additional context**
An alternative to fixing the pointer would be to document that the `conn` pointer can in fact be NULL in the `gatt.h` API.

### PR DESCRIPTION
**Pull request by alwa-nordic**
The conn pointer is still valid / not reused at this time and can be
used further up the stack as an identifer. This simplifies the API of
ATT, and fixes callbacks in GATT that pass on this value directly since
their API does not allow conn to be NULL.

Fixes #41794

Signed-off-by: Aleksander Wasaznik <aleksander.wasaznik@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/att.c [hunk 1]
```diff
@@ -2622,6 +2623,7 @@ static void att_reset(struct bt_att *att)
 		net_buf_unref(buf);
 	}
 
+	conn = att->conn;
 	att->conn = NULL;
```
Comment (jhedberg) [inline subsys/bluetooth/host/att.c:2627]: How is `att->conn` reference counted? It looks like there's a missing `bt_conn_unref()` before the original `att->conn = NULL`. If `att->conn` wasn't ref-counted (created with `att->conn = bt_conn_ref(conn);` somewhere) that should probably be fixed.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/att.c [hunk 2]
```diff
@@ -2632,7 +2634,7 @@ static void att_reset(struct bt_att *att)
 		node = sys_slist_get_not_empty(&att->reqs);
 		req = CONTAINER_OF(node, struct bt_att_req, node);
 		if (req->func) {
-			req->func(NULL, BT_ATT_ERR_UNLIKELY, NULL, 0,
+			req->func(conn, BT_ATT_ERR_UNLIKELY, NULL, 0,
```
Comment (Thalley) [inline subsys/bluetooth/host/att.c:2637]: Alternative solution:

Move the `att->conn = NULL` to after this loop, and use `att->conn` here instead. 

That seems simpler to me, and should provide the same result. 

Of course, there's not really any way for the application to know that this "error" is occurred due to a disconnect. I wonder if there's anything we can do there.

Comment (alwa-nordic) [reply subsys/bluetooth/host/att.c:2637]: I assumed there was a reason for why `att->conn = NULL` is above the callback invocation. Is it really the same?

Comment (Thalley) [reply subsys/bluetooth/host/att.c:2637]: Hmm, it's a good question. I would expect that any connection related checks would check for the `conn->state` and not if `att->conn == NULL`, but it's hard to tell, and would require some additional time to check. 

There's no comment for this assignement, and @jhedberg can't remember (it is old code after all) the reasoning either :)

Comment (alwa-nordic) [reply subsys/bluetooth/host/att.c:2637]: > I would expect that any connection related checks would check for the `conn->state` and not if `att->conn == NULL`

If that's the case, `att->conn = NULL` is not needed at all, right? `att` is freed at the end of this function.

Comment (Thalley) [reply subsys/bluetooth/host/att.c:2637]: Does `k_mem_slab_free(&att_slab, (void **)&att);` memset `att` to `0`? Not familiar with that function.

Comment (alwa-nordic) [reply subsys/bluetooth/host/att.c:2637]: I don't think it does. But `bt_att_accept`, memsets it on allocation.

Comment (Thalley) [reply subsys/bluetooth/host/att.c:2637]: OK, then the question is if we ever check `att->conn`, and if it needs to be set to NULL here :)

File: subsys/bluetooth/host/att.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/att.c]: @jhedberg I think this issue should not block this PR in any case.

File: subsys/bluetooth/host/att.c [hunk 3]
```diff
@@ -2622,8 +2622,6 @@ static void att_reset(struct bt_att *att)
 		net_buf_unref(buf);
 	}
 
-	att->conn = NULL;
```
Comment (Thalley) [inline subsys/bluetooth/host/att.c:2625]: The removal of `att->conn = NULL;` from this function needs the approval of @jhedberg or @Vudentz. I simply do not know if it is needed at all, or what consequences it may have.

**Comment by carlescufi** [comment]
Please add a note to the release notes since this affects the values received in public callbacks.

File: subsys/bluetooth/host/att.c (hunk 3 above)
Comment (carlescufi) [reply subsys/bluetooth/host/att.c:2625]: Do not set this to NULL

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
Given that providing NULL was not documented, this does not need to be considered a stable API change.
