### PR TITLE
random: rand32_ctr_drbg: Fix missed device constify change

### LINKED ISSUE #28033: rand32_ctr_drbg.c fails to build
When I try:

`./scripts/sanitycheck -p frdm_kw41z -s samples/net/sockets/websocket_client/sample.net.sockets.websocket_client`

I get:

```
/home/galak/git/zephyr/subsys/random/rand32_ctr_drbg.c: In function 'ctr_drbg_initialize':
/home/galak/git/zephyr/subsys/random/rand32_ctr_drbg.c:72:9: error: passing argument 3 of 'mbedtls_ctr_drbg_seed' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
   72 |         entropy_driver,
      |         ^~~~~~~~~~~~~~
In file included from /home/galak/git/zephyr/subsys/random/rand32_ctr_drbg.c:19:
/home/galak/git/modules/crypto/mbedtls/include/mbedtls/ctr_drbg.h:278:26: note: expected 'void *' but argument is of type 'const struct device *'
  278 |                    void *p_entropy,
      |                    ~~~~~~^~~~~~~~~

```

### PR DESCRIPTION
**Pull request by dleach02**
Device constify PR missed changes needed within the mbedtls conditional code.

Fixes #28033

Signed-off-by: David Leach <david.leach@nxp.com>

### CODE REVIEW

File: subsys/random/rand32_ctr_drbg.c [hunk 1]
```diff
@@ -69,7 +69,7 @@ static int ctr_drbg_initialize(void)
 
 	ret = mbedtls_ctr_drbg_seed(&ctr_ctx,
 				    ctr_drbg_entropy_func,
-				    entropy_driver,
+				    (void *)entropy_driver,
```
Comment (tbursztyka) [inline subsys/random/rand32_ctr_drbg.c:72]: We loose the const qualifier then. Since entropy_driver is static to the whole file, just pass NULL here, and use entropry_driver instead of ctx in ctr_drbg_entropy_func

Comment (dleach02) [reply subsys/random/rand32_ctr_drbg.c:72]: okay

**Review by MaureenHelm — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

**Comment by ioannisg** [comment]
@tbursztyka pls take a look once more

**Review by tbursztyka — APPROVED** [review]
