### PR TITLE
drivers: can: stm32: rework filter handling

### LINKED ISSUE #44725: drivers: can: stm32: can_add_rx_filter() does not respect CONFIG_CAN_MAX_FILTER
**Describe the bug**
Calling `can_add_rx_filter()` on an STM32 bxCAN driver instance does not respect `CONFIG_CAN_MAX_FILTER` setting.

When setting `CONFIG_CAN_MAX_FILTER=5` the driver returns `-ENOSPC` when attempting to add standard, unmasked CAN-ID filter number 5. On the other hand, it seems to allow for infinite number of extended, unmasked CAN-ID filters (which clearly overflows the internal arrays of the driver).

**Expected behavior**
The driver should accept up to the number of configured filters and should not overflow internal arrays. 

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04 LTS
 - Toolchain Zephyr SDK v0.14.0
 - Commit SHA: 70c48417c7a0d7db139accc2368bec7f4aa9c762

**Additional context**
This was found during implementation of #44687.

### LINKED ISSUE #47986: Rework of STM32 bxCAN driver filter handling required
## Background

The STM32 bxCAN assigns a number to the filters in the order they appear in the filter banks. This number is used in the RX FIFOs to associate a stored message to the used filter (the filter number is called filter match index in this context).

One filter bank can store 1 (extended ID + mask) to 4 (std ID, non-masked) filters depending on their mode and scale. If a bank configuration is changed e.g. from extended ID filter with a mask to std ID with mask, all filter numbers in the following banks get an offset by 2 as the same bank has 2 more filters.

Each of the two FIFOs has its own numbering scheme. However, the Zephyr driver currently only uses FIFO 0.

See below figure from RM0390 for an example for filter numbering for different FIFOs (assigned per bank).
image

This behaviour makes the filter assignment in the driver very complicated, especially with respect to the maximum number of filters required by the application, configured using `CONFIG_CAN_MAX_FILTER`.

### Direct mapping between filter number and callback

The driver uses the filter number as the index in the callback array, which allows to deliver an incoming message to the application very fast without searching for the right callback depending on the CAN ID.

If there is an unused part of a filter bank, also the callback array at that position must be left empty.

Example:
1. Add std ID filter without mask (list mode). This filter will get filter number 0 and the remaining 3 slots in this bank are unused.
2. Add extended ID filter with mask: This filter will get number 4 and occupy one entire bank.

If `CONFIG_CAN_MAX_FILTER` was set to 5, no further extended ID filter can be added even though only 2 filters are actually configured.

This leads to unpredictable behavior, as a user would expect to be able to add up to `CONFIG_CAN_MAX_FILTER` filters.

Adding `can_get_max_filters` API call to the driver also makes the `tests/drivers/can/api` test fail for `CONFIG_CAN_MAX_FILTER=5` because the `can_stm32_shift_arr` function requires some more empty elements at the end to work correctly.

As stated in #44725, the driver may even overflow the callback arrays under some circumstances.

### 1. Configure std and ext filters individually and always use mask

The STM32 CAN-FD driver has individual settings for CONFIG_CAN_MAX_STD_ID_FILTER and CONFIG_CAN_MAX_EXT_ID_FILTER. This could also be used for the bxCAN driver.

In order to make the number of filters predictable, filters would always be stored with a mask and the two FIFOs can be used to differentiate between std and ext filters because they have their individual numbering scheme (FIFO 1 is currently not used).

The lower numbers of `filter_id` returned by `can_add_rx_filter` (less than `CONFIG_CAN_MAX_STD_ID_FILTER`) would be used for std ID, the higher numbers for ext ID (same as in the CAN-FD driver).

**Pro**
- Simplified driver implementation: no shifting shifting operations required

**Contra**
- Filter bank usage not fully optimized, maximum 28 std ID filters or 14 ext ID filters possible.

### 2. Change CAN API `can_get_max_filters`

This function only works if the available number of filters is constant, independent of the order or type of filters already present in the banks.

The function could be replaced by a more dynamic function `can_get_free_filters` which returns the number of filters still available for the given type (std or ext). This would also be more useful for an application, as there is currently no way to determine if there are free filters left except for trying to add one and checking if it fails.

**Pro**
- Amount of useable filters is maximized for bxCAN

**Contra**
- API change for all CAN drivers

CC @alexanderwachter @henrikbrixandersen @FRASTM @erwango

### PR DESCRIPTION
**Pull request by martinjaeger**
The previous driver implementation aimed to maximize the amount of filters, which resulted in a fairly complex implementation.

Background: The bxCAN assigns a number to the filters in the order they appear in the filter banks. This number is used to match messages in the FIFO with their filter. If the scale or mode of a filter bank is changed, all following filter numbers get an offset and the assigned callbacks have to be shifted accordingly.

The required additional space for the shifting operations resulted in non-deterministic behaviour and the maximum number of filters could not be determined at compile-time, which made several tests like `tests/drivers/can/api` fail.

This implementation uses a more simple but reliable approach for filtering and and reserves fixed space for extended and standard ID filters in the available banks (configurable via Kconfig).
The list mode is not used, which may reduce the total number of usable filters depending on the application.

The maximum amount of filters is 14 if all filters use ext. IDs, 28 if all use std IDs and something in between if mixed IDs are used.

Also see issue #47986 for more detailed background information.

Passes the following tests:
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p nucleo_f446re -T tests/drivers/can
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p nucleo_f446re -T samples/drivers/can
```

The first commit does not contain any functional changes, but helped me to better understand the driver code before fixing it. I suggest to review the two commits separately.

Fixes #44725.

### CODE REVIEW

**Comment by martinjaeger** [comment]
FYI: For the same amount of filters (21) the new (more simple) implementation reduces the flash footprint by 672 bytes for `samples/drivers/can`. RAM stays exactly the same.

Before:
```
$ west build -b nucleo_f446re samples/drivers/can -p
[...]
Memory region         Used Size  Region Size  %age Used
           FLASH:       47756 B       512 KB      9.11%
            SRAM:       12424 B       128 KB      9.48%
     BACKUP_SRAM:          0 GB         4 KB      0.00%
        IDT_LIST:          0 GB         2 KB      0.00%
```

After:
```
$ west build -b nucleo_f446re samples/drivers/can -p
[...]
Memory region         Used Size  Region Size  %age Used
           FLASH:       47084 B       512 KB      8.98%
            SRAM:       12424 B       128 KB      9.48%
     BACKUP_SRAM:          0 GB         4 KB      0.00%
        IDT_LIST:          0 GB         2 KB      0.00%
```

File: drivers/can/can_stm32.c [hunk 1]
```diff
@@ -503,9 +517,10 @@ static int can_stm32_init(const struct device *dev)
 	data->state_change_cb = NULL;
 	data->state_change_cb_data = NULL;
 
-	data->filter_usage = (1ULL << CAN_STM32_MAX_NUM_FILTERS) - 1ULL;
-	(void)memset(data->rx_cb, 0, sizeof(data->rx_cb));
-	(void)memset(data->cb_arg, 0, sizeof(data->cb_arg));
+	(void)memset(data->rx_cb_std, 0, sizeof(data->rx_cb_std));
+	(void)memset(data->cb_arg_std, 0, sizeof(data->cb_arg_std));
+	(void)memset(data->rx_cb_ext, 0, sizeof(data->rx_cb_ext));
+	(void)memset(data->cb_arg_ext, 0, sizeof(data->cb_arg_ext));
```
Comment (henrikbrixandersen) [inline drivers/can/can_stm32.c:524]: We can get rid of all these `memset()` and `NULL` initializers since `data` is `static` and therefore zeroed.

File: drivers/can/can_stm32.c [hunk 2]
```diff
@@ -913,157 +810,94 @@ static inline uint32_t can_stm32_filter_to_ext_id(const struct zcan_filter *filt
...
-	int filter_id = 0;
-	int filter_index_new = -ENOSPC;
-	int bank_nr;
+	int filter_id = -ENOSPC;
 	int bank_offset = 0;
-	uint32_t bank_bit;
-	int register_demand;
-	enum can_stm32_filter_type filter_type;
-	enum can_stm32_filter_type bank_type;
+	int bank_nr;
```
Comment (henrikbrixandersen) [inline drivers/can/can_stm32.c:822]: Perhaps use `bank_num`?

File: drivers/can/can_stm32.c [hunk 3]
```diff
@@ -913,157 +810,94 @@ static inline uint32_t can_stm32_filter_to_ext_id(const struct zcan_filter *filt
...
 
 	if (filter->id_type == CAN_STANDARD_IDENTIFIER) {
-		id = can_stm32_filter_to_std_id(filter);
-		filter_type = CAN_STM32_FILTER_STANDARD;
-
-		if (filter->id_mask != CAN_STD_ID_MASK) {
-			mask = can_stm32_filter_to_std_mask(filter);
-			filter_type = CAN_STM32_FILTER_STANDARD_MASKED;
+		for (int i = 0; i < CONFIG_CAN_MAX_STD_ID_FILTER; i++) {
+			if (data->rx_cb_std[i] == NULL) {
```
Comment (henrikbrixandersen) [inline drivers/can/can_stm32.c:831]: This is fine, but could perhaps be optimised slightly by using an atomic. Just an observation, not blocking at all.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Thank you for addressing this @martinjaeger. Overall it looks great, just a few minor observations.

File: drivers/can/can_stm32.c (hunk 3 above)
Comment (martinjaeger) [reply drivers/can/can_stm32.c:831]: Do you think we could avoid the mutex-guarded section from which this function is called by using an atomic? I don't think so, as we also change the filter bank registers, which should not be accessed from two threads in parallel.

And if this section is already protected by a mutex, an additional atomic would only be unnecessary additional overhead, as far as I understand.

File: drivers/can/can_stm32.c (hunk 1 above)
Comment (martinjaeger) [reply drivers/can/can_stm32.c:514]: Good point. Done.

File: drivers/can/can_stm32.c (hunk 2 above)
Comment (martinjaeger) [reply drivers/can/can_stm32.c]: Makes sense. Renamed it.

File: drivers/can/can_stm32.c (hunk 3 above)
Comment (henrikbrixandersen) [reply drivers/can/can_stm32.c:821]: No, the mutex would still be needed.

**Review by henrikbrixandersen — COMMENTED** [review]
Looks good! From what I can tell, this change renders the `tests/drivers/can/stm32` test suite unnecessary?

File: drivers/can/can_stm32.c (hunk 3 above)
Comment (martinjaeger) [reply drivers/can/can_stm32.c:821]: Ok, so if the mutex is still needed, what would be the "optimization" by using an atomic?

**Comment by martinjaeger** [comment]
> Looks good! From what I can tell, this change renders the `tests/drivers/can/stm32` test suite unnecessary?

Yes, probably correct. I'll double-check and add another commit to remove the test if it makes sense.

File: drivers/can/can_stm32.c (hunk 3 above)
Comment (henrikbrixandersen) [reply drivers/can/can_stm32.c:821]: Likely none, depending on the instructions generated by the compiler. I had not noticed the existing mutex.

**Comment by str4t0m** [comment]
> Looks good! From what I can tell, this change renders the `tests/drivers/can/stm32` test suite unnecessary?

Yes, this test checks tests edge cases of the old filter implementation.
I briefly thought about generalizing it to test edge cases of in-tree driver's filter handling.
But as all drivers do a simple array or bitfield traversal, there is not much to test really.
So I do agree that we could remove it afterwards.

**Review by str4t0m — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by henrikbrixandersen** [comment]
@martinjaeger I take it all the `twister -t can ...` test pass?

**Comment by martinjaeger** [comment]
> @martinjaeger I take it all the `twister -t can ...` test pass?

Yes, they do. My full test command was:
```
scripts/twister -t can --device-testing --device-serial /dev/ttyACM0 -p nucleo_l452re --west-flash="--reset-after-load" --west-runner=jlink
```

**Review by str4t0m — DISMISSED** [review]

**Comment by martinjaeger** [comment]
Had to rebase again because https://github.com/zephyrproject-rtos/zephyr/commit/def230187bf94afc5f99e29cc3a9be8500ffcb06 was merged in the meantime and resulted in a merge conflict. Sorry to ask you for a re-approval again.

**Review by str4t0m — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
