### PR TITLE
drivers: timer: nrf_rtc_timer: Add clearing of previous CC event

### LINKED ISSUE #30526: tests: drivers: timer: Tests from drivers.timer.nrf_rtc_timer.basic fail on all nrf platforms
**Describe the bug**
Tests from drivers.timer.nrf_rtc_timer.basic (zephyr/tests/drivers/timer/nrf_rtc_timer) fail on all platforms. 

**To Reproduce**
1. go to zephyr dir
2. have nrf52 platform connected (e.g. nrf52dk_nrf52832)
3. run `./scripts/sanitycheck --device-testing -T tests/drivers/timer/nrf_rtc_timer/ -p nrf52dk_nrf52832 --device-serial /dev/ttyACM0 -v -v`

**Expected behavior**
The tests pass.

**Impact**
Not clear

**Logs and console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v2.4.0-2107-gd1c2a5261781  ***
DEBUG   - DEVICE: Running test suite test_nrf_rtc_timer
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_basic
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Assertion failed at CMAKE_SOURCE_DIR/src/main.c:84: test_timeout: (test_data.err not equal to 0)
DEBUG   - DEVICE: Unexpected err: -22
DEBUG   - DEVICE: FAIL - test_basic
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_z_nrf_rtc_timer_compare_evt_address_get
DEBUG   - DEVICE: PASS - test_z_nrf_rtc_timer_compare_evt_address_get
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_int_disable_enabled
DEBUG   - DEVICE: PASS - test_int_disable_enabled
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_get_ticks
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Assertion failed at CMAKE_SOURCE_DIR/src/main.c:172: test_get_ticks: ((ticks >= exp_ticks - 1) && (ticks <= exp_ticks) is false)
DEBUG   - DEVICE: Unexpected result -22 (expected: 18260)
DEBUG   - DEVICE: FAIL - test_get_ticks
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_absolute_scheduling
DEBUG   - DEVICE: RTC event scheduled at 585083us for 590761us,event occured at 2073157196us (uptime)
DEBUG   - DEVICE: RTC event scheduled now, at 598297us,event occured at 2073183624us (uptime)
DEBUG   - DEVICE: PASS - test_absolute_scheduling
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_alloc_free
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Assertion failed at CMAKE_SOURCE_DIR/src/main.c:248: test_alloc_free: (chan[i] >= 0 is false)
DEBUG   - DEVICE: Failed to allocate RTC channel.
DEBUG   - DEVICE: FAIL - test_alloc_free
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_stress
DEBUG   - DEVICE: 
DEBUG   - DEVICE: Assertion failed at CMAKE_SOURCE_DIR/src/main.c:266: test_stress: (chan >= 0 is false)
DEBUG   - DEVICE: Failed to allocate RTC channel.
DEBUG   - DEVICE: FAIL - test_stress
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: Test suite test_nrf_rtc_timer failed.
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
DEBUG   - run status: nrf52dk_nrf52832/tests/drivers/timer/nrf_rtc_timer/drivers.timer.nrf_rtc_timer failed
INFO    - 1/1 nrf52dk_nrf52832          tests/drivers/timer/nrf_rtc_timer/drivers.timer.nrf_rtc_timer FAILED Failed (device 3.997s)
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: zephyr-v2.4.0-2107-gd1c2a5261781

### PR DESCRIPTION
**Pull request by nordic-krch**
Added clearing of CC event which may occure due to previous
CC value which was closed to current counter value.

Fixes #30526.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by nordic-krch** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/29810#discussion_r532412748

Apparently, event though event is disabled it can still be generated (for previous CC value) and needs to be cleared.
I've moved event enabling before even though it seems to not be needed but according to RTC spec event generation depends on event being enabled. Spec: https://infocenter.nordicsemi.com/topic/ps_nrf52840/rtc.html?cp=4_0_0_5_21_5#concept_eml_dkj_sr

File: drivers/timer/nrf_rtc_timer.c [hunk 1]
```diff
@@ -160,10 +160,10 @@ static void set_absolute_alarm(uint32_t chan, uint32_t abs_val)
 	uint32_t cc_val = abs_val & COUNTER_MAX;
 	uint32_t prev_cc = get_comparator(chan);
 
-
 	do {
 		now = counter();
 
+		event_enable(chan);
```
Comment (pabigot) [inline drivers/timer/nrf_rtc_timer.c:166]: This seems OK.  My concern was that this could be executed with interrupts enabled.  It can't from `z_clock_set_timeout()` because that holds a lock.  It can't for other channels because `z_nrf_rtc_timer_compare_set()` also holds a lock.  

However, while this will be fine, it seems that anybody who uses `z_nrf_rtc_timer_compare_int_lock()` then invokes `z_nrf_rtc_timer_compare_set()` will have their lock cleared prematurely when the set completes.  That seems like a bug which I'll raise elsewhere.

**Review by pabigot — APPROVED** [review]

File: drivers/timer/nrf_rtc_timer.c (hunk 1 above)
Comment (pabigot) [reply drivers/timer/nrf_rtc_timer.c:166]: No, I see the `key` parameter should avoid that.

**Comment by nordic-krch** [comment]
I've added additional test for resetting CC which happens just before earlier setting. It has shown that if event occurred when event was disabled in `EVTEN` it will expire immediately after enabling this event because of that first event is enabled then cleared (if previous event occurred).
Moreover, I've noticed that bsim behaves differently and busy wait in case of close event must be longer: full tick instead of half tick.

File: drivers/timer/nrf_rtc_timer.c [hunk 2]
```diff
@@ -160,20 +161,21 @@ static void set_absolute_alarm(uint32_t chan, uint32_t abs_val)
...
 
-
 	do {
 		now = counter();
 
 		/* Handle case when previous event may generate an event.
-		 * It is handled by setting CC to now (that's furtherst future),
+		 * It is handled by setting CC to now (far in the future),
 		 * in case previous event was set for next tick wait for half
 		 * LF tick and clear event that may have been generated.
```
Comment (anangl) [inline drivers/timer/nrf_rtc_timer.c:170]: > Moreover, I've noticed that bsim behaves differently and busy wait in case of close event must be longer: full tick instead of half tick.

Perhaps it would be good to include this information in the above comment. Right now someone might get confused why for BSim half LF tick is 31 microseconds.

**Review by anangl — APPROVED** [review]

**Comment by nordic-krch** [comment]
It seems that bsim is still not working #30507 on master and after this fix, too.

**Comment by nordic-krch** [comment]
I've found an issue in nrf52_bsim model. Compare interrupts in RTC were lost if they occurred while interrupt was disabled. I've added PR (https://github.com/BabbleSim/ext_NRF52_hw_models/pull/17) that checks on INTENSET if there are pending interrupt and triggers it.

**Comment by nordic-krch** [comment]
> Apparently, event though event is disabled it can still be generated (for previous CC value) and needs to be cleared.
I've moved event enabling before even though it seems to not be needed but according to RTC spec event generation depends on event being enabled.

Further testing shown that RTC behaves as in spec. If event is enabled but interrupt is disabled then event will set EVENTS_COMPARE[n]=1 and when interrupt is enabled that will generate nvic interrupt.
It also means that if event and interrupt is disabled then when compare event occurs it is not recorded at all.

File: west.yml [hunk 3]
```diff
@@ -128,9 +130,10 @@ manifest:
     - name: mipi-sys-t
       path: modules/debug/mipi-sys-t
       revision: 75e671550ac1acb502f315fe4952514dc73f7bfb
-    - name: nrf_hw_models
+    - name: ext_NRF52_hw_models
```
Comment (carlescufi) [inline west.yml:133]: next time use `repo-path` so that you don't change the name and hence the bot can work

Comment (nordic-krch) [reply west.yml]: changed to: https://github.com/zephyrproject-rtos/zephyr/blob/be2a233296f4496a2baf3b2bed2d48a0a840fc4a/west.yml
but now CI is broken, works locally.

**Comment by nordic-krch** [comment]
Removing `DNM` as `nrf_hw_models` fix is in master. Updated revision in west.yml.

File: drivers/timer/nrf_rtc_timer.c [hunk 4]
```diff
@@ -160,20 +161,23 @@ static void set_absolute_alarm(uint32_t chan, uint32_t abs_val)
...
 		 */
 		set_comparator(chan, now);
 		if (counter_sub(prev_cc, now) == 1) {
+			/* Apparently BSIM is not syncing on half tick thus
+			 * added full tick waiting.
+			 */
```
Comment (anangl) [inline drivers/timer/nrf_rtc_timer.c:176]: This comment is no longer valid.

Comment (nordic-krch) [reply drivers/timer/nrf_rtc_timer.c]: removed.

**Comment by aescolar** [comment]
@nordic-krch , when I merge this PR with #30601, I seem to see the same failure that this PR is trying to fix in the new testcase that PR is adding:
```
d_00: @00:00:00.000000  *** Booting Zephyr OS build zephyr-v2.4.0-2276-gfc42e67439a6  ***
d_00: @00:00:00.000000  Running test suite native_cpu_hold
d_00: @00:00:00.000000  ===================================================================
d_00: @00:00:00.000000  START - test_cpu_hold_basic
d_00: @00:00:00.009979  ASSERTION FAIL [chan && chan < (0 + 1)] @ /persistant/scratch/alpi/Zephyr/west_zephyr/zephyr/drivers/timer/nrf_rtc_timer.c:216
d_00: @00:00:00.009979  @ /persistant/scratch/alpi/Zephyr/west_zephyr/zephyr/lib/os/assert.c:45
d_00: @00:00:00.009979  E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
d_00: @00:00:00.009979  E: Current thread: 0x56629c60 (ztest_thread)
d_00: @00:00:00.009979  E: Halting system
```

**Comment by nordic-krch** [comment]
@aescolar confirmed same on my side. Investingating...

**Comment by aescolar** [comment]
@nordic-krch seems that the cause of the assert is CONFIG_TICKLESS_KERNEL by the test

**Comment by nordic-krch** [comment]
@aescolar that was false alarm. Forgot that `nrf52_bsim` required `CONFIG_SYS_CLOCK_TICKS_PER_SEC=32768` option to match timings in the test. That was added in `testcase.yaml` and not in `prj.conf`. I've added it to `prj.conf` now since that makes no harm for hw platforms and makes test work for bsim out of the box.

**Comment by nordic-krch** [comment]
@carlescufi can we merge this?

**Comment by aescolar** [comment]
> @nordic-krch , when I merge this PR with #30601, I seem to see the same failure in nrf52_bsim that this PR is trying to fix in the new testcase that PR is adding:

Just for the record, this issue is fixed with the latest commit form @nordic-krch
