### PR TITLE
pthread: cond: fix pthread_cond_wait always returning ETIMEDOUT

### LINKED ISSUE #41284: pthread_cond_wait return value incorrect
**Describe the bug**
The `pthread_cond_wait` always returns `ETIMEDOUT`

I try to use `pthread_cond_wait` and find that its return value is always `ETIMEDOUT`, even the thread is wakened normally.

**To Reproduce**
https://github.com/zephyrproject-rtos/zephyr/blob/c3715da5d95c10527e65624d47954987037f50c5/tests/posix/common/src/pthread.c#L100

we can easily check the return value here.
And I think this test case also needs to check the return value.

I guess we should reset the thread's ret_val in `pthread_cond_signal `and `pthread_cond_broadcast`, just like the `pthread_mutex` doing. 
https://github.com/zephyrproject-rtos/zephyr/blob/c3715da5d95c10527e65624d47954987037f50c5/lib/posix/pthread_mutex.c#L148

**Expected behavior**
The thread calling `pthread_cond_wait` should return 0 (its wait time is K_FOREVER, so it should not return `ETIMEDOUT`.

**Impact**
We will fail to port some code because of the incorrect return value.

### PR DESCRIPTION
**Pull request by cfriedt**
It was noted that `pthread_cond_wait()` would always return `ETIMEDOUT`, even when successful (and no timeout should ever occur with `K_FOREVER`).

The `z_sched_wake()` / `z_sched_wake_all()` / `z_sched_wait()` API are used here with a swap return value of 0 to indicate success.
        
Fixes #41284

### CODE REVIEW

File: kernel/include/ksched.h [hunk 1]
```diff
@@ -239,13 +239,15 @@ static inline bool _is_valid_prio(int prio, void *entry_point)
 	return true;
 }
 
-static inline void _ready_one_thread(_wait_q_t *wq)
+static inline struct k_thread *_ready_one_thread(_wait_q_t *wq)
```
Comment (andyross) [inline kernel/include/ksched.h:242]: No objections to this API change, especially for an inline function where it incurs no overhead.

But I'm a little worried about the use/abuse of the swap return value in the pthread code here.  That's a voodoo-scale interface that I'd like to get rid of, precisely because it engenders bugs like this.  Zero isn't "success", it's just whatever the subsystem wants it to mean.  The default is indeed -EAGAIN (to indicate that something "unexpected" rescheduled the thread, like a timeout).  If pthread_cond_wait() was surprised here, it's probably going to be surprised elsewhere too.

File: lib/posix/pthread_cond.c [hunk 2]
```diff
@@ -52,20 +52,30 @@ static int cond_wait(pthread_cond_t *cv, pthread_mutex_t *mut,
 
 int pthread_cond_signal(pthread_cond_t *cv)
 {
+	struct k_thread *thread;
 	k_spinlock_key_t key = k_spin_lock(&z_pthread_spinlock);
 
-	_ready_one_thread(&cv->wait_q);
+	thread = _ready_one_thread(&cv->wait_q);
+	if (thread != NULL) {
+		arch_thread_return_value_set(thread, 0);
```
Comment (andyross) [inline lib/posix/pthread_cond.c:60]: Actually on further thought: I withdraw my lack of objections.  This actually won't work. :)

At the point where _ready_one_thread() has returned, the thread has already been readied and **may already have run** (on an SMP system with an idle core, it's basically guaranteed to be running already).  It's too late to set the return value here.  My guess is that this resolves the error seen simply because the thread running this code is higher priority.

**Review by andyross — DISMISSED** [review]

File: lib/posix/pthread_cond.c (hunk 2 above)
Comment (cfriedt) [reply lib/posix/pthread_cond.c:60]: I assumed that because the POSIX lick was held it was safe

Comment (andyross) [reply lib/posix/pthread_cond.c:60]: If you're in a nested spinlock, then yes: you're protected from preemption on uniprocessor systems.  But on SMP, ready means ready and the scheduler is free to run that on any core available.

**Comment by andyross** [comment]
So... this does look correct, at the cost of a new internal API that is sort of a kludge. :)

This is **exactly** why I hate this API.  In the scheduler, it's generally not possible to know which thread you're going to wake up until after you've woken it up (by design: you're racing against other contexts pending and unpending threads).  So pushing the responsibility for the "swap return value" into the subsystem code means that the subsystem needs to be part of the synchronized critical section along with the rest of the scheduler.

It sort of made sense in uniprocessor situations (and in particular on uniprocessor x86, where it happened to be implemented at zero cost by writing the EAX register into the thread's register block).  On SMP it's a huge, huge race factory.

Really the right solution here is for pthread_cond to stop using this, and detect timeouts on its own.

But... absent that I'll note (I knew but had sort of forgotten) that @pabigot  had hit exactly this issue about a year ago and added a z_sched_wait()/z_sched_wake() API which does (I think) almost exactly what you want here.  If you absolutely must use thread return values, please investigate that API.

**Comment by cfriedt** [comment]
> Really the right solution here is for pthread_cond to stop using this, and detect timeouts on its own.
> 
> But... absent that I'll note (I knew but had sort of forgotten) that @pabigot had hit exactly this issue about a year ago and added a z_sched_wait()/z_sched_wake() API which does (I think) almost exactly what you want here. If you absolutely must use thread return values, please investigate that API.

Shouldn't it, kind of by definition, be possible to use Zephyr's `k_condvar` here? 🤔 

https://docs.zephyrproject.org/latest/reference/kernel/synchronization/condvar.html

**Comment by cfriedt** [comment]
> But... absent that I'll note (I knew but had sort of forgotten) that @pabigot had hit exactly this issue about a year ago and added a z_sched_wait()/z_sched_wake() API which does (I think) almost exactly what you want here. If you absolutely must use thread return values, please investigate that API.

@andyross  - done!

**Comment by cfriedt** [comment]
> @andyross - Shouldn't it, kind of by definition, be possible to use Zephyr's `k_condvar` here? 🤔
> 
> https://docs.zephyrproject.org/latest/reference/kernel/synchronization/condvar.html

Experiment was largely successful to make pthread_mutex and pthread_cond simple wrappers around k_mutex and k_condvar structures / APIs. I might put a bit more effort into that at a later date. The pthread flavours more or less duplicate the native flavours, so it could save a small bit of code space. However, I think that more valuable aspect of that would be to reduce "concept clutter" - it is a bit helpful to simply have one threading implementation that others can just wrap.

**Review by andyross — APPROVED** [review]
This looks great, thanks.

And yes, absolutely we want this to be a wrapper.  The reason it's not is just timing.  The POSIX API appeared first.

(Actually I think the condition variable specifically, and thus this race, might have been my work originally, but I honestly can't remember -- or alternatively it might have been introduced in one of the waves of scheduler API reorganization, also my doing, so... sorry, if true)

**Review by dcpleung — APPROVED** [review]

**Review by povergoing — APPROVED** [review]
I tested on arm64 board fvp_baser_aemv8r. there are no issues. :)

**Comment by ycsin** [comment]
@cfriedt should this be backported?
