### PR TITLE
stm32: ethernet: mac address: Deprecate Kconfig symbols and generate iud based address by default

### LINKED ISSUE #50947: stm32 static IPv4 networking in smp_svr sample application does not seem to work until a ping is received
**Describe the bug**
Testing `samples/subsys/mgmt/mcumgr/smp_svr` for the `nucleo_f746zg` board with the `overlay-udp.conf` overlay enabled (note: there is no partition map for this board, which needs to be setup) results in an image that, once flashed, does work, but does not accept UDP connections until the device is pinged.
Output on board after boot and sending a command via mcumgr (using `mcumgr --conntype udp --connstring=[192.168.1.220]:1337 fs upload /tmp/file /lfs1/testfile`):
```
uart:~$ *** Booting Zephyr OS build zephyr-v3.2.0-115-gee5a56aad1ab  ***
[00:00:01.533,000] <dbg> net_ethernet: ethernet_init: (main): Initializing Ethernet L2 0x20016c9c for iface 0x20012714
[00:00:01.539,000] <inf> net_config: Initializing network
[00:00:01.539,000] <inf> net_config: Waiting interface 1 (0x20012714) to be up...
[00:00:02.029,000] <dbg> net_ethernet: carrier_on_off: (sysworkq): Carrier ON for interface 0x20012714
[00:00:02.029,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:14[00:00:02.029,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:14[00:00:02.030,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:FF:B6:33:E4[00:00:02.030,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:04[00:00:01.533,000] <dbg> net_ethernet: ethernet_init: (main): Initializing Ethernet L2 0x20016c9c for iface 0x20012714
[00:00:01.539,000] <inf> net_config: Initializing network
[00:00:01.539,000] <inf> net_config: Waiting interface 1 (0x20012714) to be up..[00:00:02.030,000] <inf> net_config: Interface 1 (0xp.
[00:00:02.029,000] <dbg> net_ethernet: carrier_on_off: (sysworkq): Carrier ON for interface 0x2001271[00:00:02.030,000] <inf> net_co04
[00:00:02.029,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:144
[00:00:02.029,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:144
[00:00:02.030,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:FF:B6:33:E0[00:00:02.031,000] <inf> littlefs: FS at flash-controller@40023c00:0x10000 is 2 0x8000-byte blocks with 512 cycle
[00:00:02.031,000] <inf> littlefs: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
4
[00:00:02.030,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:0}[00:00:02.031,000] <wrn> littlefs: can't mount (LFS -84); formatting
[00:00:02.226,000] <inf> net_config: IPv6 address: 2001:db8::1
4
[00:00:02.030,000] <inf> net_config: Interface 1 (0x20012714) coming u[00:00:02.226,000] <inf> net_config: IPv6 address: 2001:db8::1
p
[00:00:02.030,000] <inf> net_config: IPv4 address: 192.168.1.22[00:00:02.429,000] <inf> littlefs: /lfs1 mounted
0
[00:00:02.030,000] <dbg> net_ethernet: ethernet_fill_header: (main): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:16 tyd[00:00:02.429,000] <inf> smp_sample: build time: Oct  4 2022 12:58:36
[00:00:02.430,000] <inf> smp_udp: Started (IPv4)
4
[00:00:02.031,000] <dbg> net_ethernet: ethernet_fill_header: (main): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:FF:00:00:01 ty)4
[00:00:02.031,000] <inf> littlefs: LittleFS version 2.5, disk version 2.0
[00:00:02.031,000] <inf> littlefs: FS at flash-controller@40023c00:0x10000 is 2 0x8000-byte blocks with 512 cycle
[00:00:02.031,000] <inf> littlefs: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
[00:00:02.031,000] <err> littlefs: WEST_TOPDIR/modules/fs/littlefs/lfs.c:1234: Corrupted dir pair at {0x0, 0x1}
[00:00:02.031,000] <wrn> littlefs: can't mount (LFS -84); formatting
[00:00:02.226,000] <inf> net_config: IPv6 address: 2001:db8::1
[00:00:02.226,000] <inf> net_config: IPv6 address: 2001:db8::1
[00:00:02.429,000] <inf> littlefs: /lfs1 mounted
[00:00:02.429,000] <inf> smp_udp_sample: Network connected
[00:00:02.429,000] <inf> smp_sample: build time: Oct  4 2022 12:58:36
[00:00:02.430,000] <inf> smp_udp: Started (IPv4)
[00:00:02.430,000] <inf> smp_udp: Started (IPv6)
uart:~$ [00:00:03.030,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:004[00:00:04.031,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:04[00:00:03.030,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:04[00:00:04.031,000] <dbg> net_ethernet: ethernet_fill_header: (sysworkq): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 33:33:00:00:00:04uart:~$ [00:00:21.026,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src CC:96:A0:4B:AB:D5 dst FF:FF:FF:FF:FF:F0[00:00:21.026,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): ARP packet from CC:96:A0:4B:AB:D5 received
[00:00:21.026,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src CC:96:A0:4B:AB:D5 dst FF:FF:FF:FF:FF:FF type 00[00:00:21.026,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): ARP packet from CC:96:A0:4B:AB:D5 received
uart:~$ [00:00:27.276,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src CC:96:A0:4B:AB:D5 dst FF:FF:FF:FF:FF:F0[00:00:27.276,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): ARP packet from CC:96:A0:4B:AB:D5 received
[00:00:27.276,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src CC:96:A0:4B:AB:D5 dst FF:FF:FF:FF:FF:FF type 00[00:00:27.276,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): ARP packet from CC:96:A0:4B:AB:D5 received
```
(Nothing from the mcumgr client ever appears) Output when I then ping the device (First 3 pings from host time out):
```
uart:~$ [00:01:19.861,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src 0C:37:96:21:F9:5D dst FF:FF:FF:FF:FF:F0[00:01:19.861,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): ARP packet from 0C:37:96:21:F9:5D received
[00:01:19.861,000] <dbg> net_ethernet: ethernet_fill_header: (rx_q[0]): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 0C:37:96:21:F9:5D4[00:01:19.863,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src 0C:37:96:21:F9:5D dst 02:80:E1:B6:33:E0 type 08[00:01:19.863,000] <dbg> net_ethernet: ethernet_ll_prepare_on_ipv4: (rx_q[0]): Found ARP entry, sending pkt 0x20020614 to iface 0x204[00:01:19.863,000] <dbg> net_ethernet: ethernet_fill_header: (rx_q[0]): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 0C:37:96:21:F9:5D4[00:01:19.861,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src 0C:37:96:21:F9:5D dst FF:FF:FF:FF:FF:FF type 00[00:01:19.861,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): ARP packet from 0C:37:96:21:F9:5D received
[00:01:19.861,000] <dbg> net_ethernet: ethernet_fill_header: (rx_q[0]): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 0C:37:96:21:F9:5D4[00:01:19.863,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src 0C:37:96:21:F9:5D dst 02:80:E1:B6:33:E0 type 08[00:01:19.863,000] <dbg> net_ethernet: ethernet_ll_prepare_on_ipv4: (rx_q[0]): Found ARP entry, sending pkt 0x20020614 to iface 0x204[00:01:19.863,000] <dbg> net_ethernet: ethernet_fill_header: (rx_q[0]): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 0C:37:96:21:F9:5D4uart:~$ 
```
Output when I then send the same mcumgr command after the ping:
```
uart:~$ [00:02:12.034,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src 0C:37:96:21:F9:5D dst 02:80:E1:B6:33:E0[00:02:12.037,000] <dbg> net_ethernet: ethernet_ll_prepare_on_ipv4: (mcumgr smp): Found ARP entry, sending pkt 0x20020614 to iface 04[00:02:12.037,000] <dbg> net_ethernet: ethernet_fill_header: (mcumgr smp): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 0C:37:96:21:F94[00:02:12.034,000] <dbg> net_ethernet: ethernet_recv: (rx_q[0]): iface 0x20012714 src 0C:37:96:21:F9:5D dst 02:80:E1:B6:33:E0 type 00[00:02:12.037,000] <dbg> net_ethernet: ethernet_ll_prepare_on_ipv4: (mcumgr smp): Found ARP entry, sending pkt 0x20020614 to iface 04[00:02:12.037,000] <dbg> net_ethernet: ethernet_fill_header: (mcumgr smp): iface 0x20012714 src 02:80:E1:B6:33:E0 dst 0C:37:96:21:F94uart:~$ 
```

**Expected behavior**
For static IPv4 networking to work out of the box.

**Impact**
Annoying to me, I imagine this would be a showstopper for anyone wanting to use this board however.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.15.0
 - Commit SHA or Version used: 0ec243b65ee0ae07cf8f4bec897be0d7955fde25

### PR DESCRIPTION
**Pull request by erwango**
First, deprecate Kconfig based mac address configuration in profit of existing available device tree properties:
- local-mac-address
- zephyr,random-mac-address

Then, in case user doesn't select any of above options, generate a mac address using device's unique id.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/50947

### CODE REVIEW

**Review by gautierg-st — CHANGES_REQUESTED** [review]
Except typos, LGTM

File: drivers/ethernet/eth_stm32_hal.c [hunk 1]
```diff
@@ -38,6 +38,21 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME);
...
 
+#if CONFIG_ETH_STM32_HAL_MAC3 || \
+	CONFIG_ETH_STM32_HAL_MAC4 || \
+	CONFIG_ETH_STM32_HAL_MAC5
+#warning CONFIG_ETH_STM32_HAL_MAC* is deprecated, use device tree "local-mac-address"
+#define ETH_STM32_KCONFIG_MAC
+#endif
+
+#if defined(CONFIG_ETH_STM32_HAL_RANDOM_MAC)
+#warning CONFIG_ETH_STM32_HAL_RANDOM_MAC is deprecated, use device tree "zephyr,random-mac-aadress"
```
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/ethernet/eth_stm32_hal.c]: Fixed, txs

File: drivers/ethernet/eth_stm32_hal.c [hunk 2]
```diff
@@ -1012,15 +1027,23 @@ void HAL_ETH_RxCpltCallback(ETH_HandleTypeDef *heth_handle)
 
 static void generate_mac(uint8_t *mac_addr)
 {
-#if defined(CONFIG_ETH_STM32_HAL_RANDOM_MAC)
+#if defined(ETH_STM32_RANDOM_MAC)
+	/* Either CONFIG_ETH_STM32_HAL_RANDOM_MAC or devie tree property */
```
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/ethernet/eth_stm32_hal.c]: Fixed, txs

**Review by gautierg-st — DISMISSED** [review]

File: drivers/ethernet/Kconfig.stm32_hal [hunk 3]
```diff
@@ -54,6 +55,7 @@ config ETH_STM32_HAL_RANDOM_MAC
 	default y
```
Comment (nordicjm) [inline drivers/ethernet/Kconfig.stm32_hal:55]: If this is deprecated, should select DEPRECATED and also not be default y

File: drivers/ethernet/eth_stm32_hal.c [hunk 4]
```diff
@@ -38,6 +39,21 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME);
 #include "eth.h"
 #include "eth_stm32_hal_priv.h"
 
+#if CONFIG_ETH_STM32_HAL_MAC3 || \
+	CONFIG_ETH_STM32_HAL_MAC4 || \
+	CONFIG_ETH_STM32_HAL_MAC5
+#warning CONFIG_ETH_STM32_HAL_MAC* is deprecated, use device tree "local-mac-address"
```
Comment (nordicjm) [inline drivers/ethernet/eth_stm32_hal.c:45]: This is not how deprecation is done - see https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#deprecated

**Review by nordicjm — CHANGES_REQUESTED** [review]
Also release note changes needed for deprecation

File: drivers/ethernet/Kconfig.stm32_hal (hunk 3 above)
Comment (nordicjm) [reply drivers/ethernet/Kconfig.stm32_hal:55]: And add ` (DEPRECATED)` or similar to end of the text too e.g. `bool "Random MAC address (DEPRECATED)"`

Comment (erwango) [reply drivers/ethernet/Kconfig.stm32_hal]: Ok will update

File: doc/releases/release-notes-3.3.rst [hunk 5]
```diff
@@ -111,6 +111,11 @@ Deprecated in this release
 
   NOTE: Only functions are marked as ``__deprecated``, type definitions are not.
 
+* STM32 Ethernet Mac address Kconfig related symbols (kconfig:option:`CONFIG_ETH_STM32_HAL_RANDOM_MAC`),
+  kconfig:option:CONFIG_ETH_STM32_HAL_MAC4, ...) have been deprecated in favor
```
Comment (nordicjm) [inline doc/releases/release-notes-3.3.rst:115]:
```suggestion
  kconfig:option:`CONFIG_ETH_STM32_HAL_MAC4`, ...) have been deprecated in favor
```

**Review by nordicjm — CHANGES_REQUESTED** [review]

File: drivers/ethernet/Kconfig.stm32_hal [hunk 6]
```diff
@@ -48,35 +49,42 @@ config ETH_STM32_HAL_PHY_ADDRESS
 	help
 	  The phy address to use.
 
-config ETH_STM32_HAL_RANDOM_MAC
+config ETH_STM32_HAL_RANDOM_MAC (DEPRECATED)
 	bool "Random MAC address"
```
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/ethernet/Kconfig.stm32_hal:53]: :-), txs

File: doc/releases/release-notes-3.3.rst [hunk 7]
```diff
@@ -350,6 +358,8 @@ Devicetree
     * STM32 SoCs:
 
       * :dtcompatible: `st,stm32-lse-clock`: new ``lse-bypass`` property
+      * :dtcompatible: `st,stm32-ethernet`: now allows ``local-mac-address`` and
+        `zephyr,random-mac-address`` properties.
```
Comment (nordicjm) [inline doc/releases/release-notes-3.3.rst:362]: missing 2x quote

File: doc/releases/release-notes-3.3.rst [hunk 8]
```diff
@@ -111,6 +111,11 @@ Deprecated in this release
 
   NOTE: Only functions are marked as ``__deprecated``, type definitions are not.
 
+* STM32 Ethernet Mac address Kconfig related symbols (kconfig:option:`CONFIG_ETH_STM32_HAL_RANDOM_MAC`,
+  kconfig:option:`CONFIG_ETH_STM32_HAL_MAC4`, ...) have been deprecated in favor
+  of the use of zephyr generic device tree `local-mac-address`` and `zephyr,random-mac-address``
```
Comment (nordicjm) [inline doc/releases/release-notes-3.3.rst:116]: missing 2x quote on both

**Review by nordicjm — CHANGES_REQUESTED** [review]
final change!

File: drivers/ethernet/Kconfig.stm32_hal [hunk 9]
```diff
@@ -49,34 +50,41 @@ config ETH_STM32_HAL_PHY_ADDRESS
...
 
 config ETH_STM32_HAL_MAC3
-	hex "MAC Address Byte 3"
+	hex "MAC Address Byte 3 (DEPRECATED)"
 	default 0
 	range 0 0xff
+	select DEPRECATED
 	help
 	  This is the byte 3 of the MAC address.
+	  Deprecated in favor of device tree property "local-mac-address"
```
Comment (nordicjm) [inline drivers/ethernet/Kconfig.stm32_hal:69]: Actually yes, this would always generate a deprecated warning, something doesn't seem right here, maybe use a choice

File: doc/releases/release-notes-3.3.rst (hunk 8 above)
Comment (erwango) [reply doc/releases/release-notes-3.3.rst:116]: I'm not seeing double quotes on other Kconfig symbols in this file, but I agree there should be a discrepancy somewhere. Anyway: fixed.

File: drivers/ethernet/Kconfig.stm32_hal (hunk 9 above)
Comment (erwango) [reply drivers/ethernet/Kconfig.stm32_hal:69]: @nordicjm 
Also note that `select DEPRECATED` can't be used with these hex symbols:
```
warning: the hex symbol ETH_STM32_HAL_MAC3 (defined at drivers/ethernet/Kconfig.stm32_hal:62) has selects or implies
```
In the end, I don't see a simple change that would not add a new symbol, nor break user configuration.

What about the initial, efficient and simple:
```
#if CONFIG_ETH_STM32_HAL_MAC3 || \
	CONFIG_ETH_STM32_HAL_MAC4 || \
	CONFIG_ETH_STM32_HAL_MAC5
#warning CONFIG_ETH_STM32_HAL_MAC* is deprecated, use device tree "local-mac-address"
```
?

Comment (erwango) [reply drivers/ethernet/Kconfig.stm32_hal]: @nordicjm I reverted to the warning solution. Please tell me if you have better idea.

File: drivers/ethernet/Kconfig.stm32_hal [hunk 10]
```diff
@@ -49,34 +50,38 @@ config ETH_STM32_HAL_PHY_ADDRESS
...
 if !ETH_STM32_HAL_RANDOM_MAC
 
 config ETH_STM32_HAL_MAC3
-	hex "MAC Address Byte 3"
+	hex "MAC Address Byte 3 (DEPRECATED)"
 	default 0
 	range 0 0xff
 	help
 	  This is the byte 3 of the MAC address.
+	  Deprecated in favor of device tree property "local-mac-address"
```
Comment (nordicjm) [inline drivers/ethernet/Kconfig.stm32_hal:69]: The problem with this is there this file shows 2 possible options, the deprecated random mac, or the 3 byte mac address, it does not allow for a third option. The 3 bytes should be in an if() that only shows if that mode is selected, the 3 modes are random (deprecated), static (deprecated) and dts - so the first option here can be made a choice with those 3 options where dts is the default

File: drivers/ethernet/eth_stm32_hal.c [hunk 11]
```diff
@@ -38,6 +39,15 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME);
 #include "eth.h"
 #include "eth_stm32_hal_priv.h"
 
+#if CONFIG_ETH_STM32_HAL_MAC3 || CONFIG_ETH_STM32_HAL_MAC4 || CONFIG_ETH_STM32_HAL_MAC5
+#define ETH_STM32_KCONFIG_MAC
+#warning CONFIG_ETH_STM32_HAL_MAC* is deprecated, use device tree "local-mac-address"
```
Comment (nordicjm) [inline drivers/ethernet/eth_stm32_hal.c:44]: This line is not needed with the choice, cmake will emit a warning if either of the 2 deprecated choices are selected

File: drivers/ethernet/Kconfig.stm32_hal (hunk 10 above)
Comment (erwango) [reply drivers/ethernet/Kconfig.stm32_hal:69]: Problem is that current status (before changes) is:
- Default config: Static address used (using default 0)
- If selected: random defined

Adding a choice, user would have to select the new symbol 'static kconfig' to be able to use the deprecated `ETH_STM32_HAL_MACX` symbols. So modify his configuration to be able use a deprecated configuration....
To me the point of deprecation, is to let user keeping his configuration w/o doing nothing, but be informed this wll have to be changed.
If he's forced to change his configuration anyway, no point of using the deprecated symbols..

File: doc/releases/release-notes-3.3.rst [hunk 12]
```diff
@@ -129,6 +129,11 @@ Deprecated in this release
 
   NOTE: Only functions are marked as ``__deprecated``, type definitions are not.
 
+* STM32 Ethernet Mac address Kconfig related symbols (kconfig:option:``CONFIG_ETH_STM32_HAL_RANDOM_MAC``,
+  kconfig:option:``CONFIG_ETH_STM32_HAL_MAC4``, ...) have been deprecated in favor
```
[the remark this answers is not in the document]
Comment (erwango) [reply doc/releases/release-notes-3.3.rst:133]: got it. fixed

File: doc/releases/release-notes-3.3.rst [hunk 13]
```diff
@@ -129,6 +129,11 @@ Deprecated in this release
...
+  of the use of zephyr generic device tree `local-mac-address`` and `zephyr,random-mac-address``
```
[the remark this answers is not in the document]
Comment (erwango) [reply doc/releases/release-notes-3.3.rst:134]: got it. fixed

File: drivers/ethernet/Kconfig.stm32_hal (hunk 10 above)
Comment (erwango) [reply drivers/ethernet/Kconfig.stm32_hal]: @nordicjm Ok, I tried to follow your advise. Please have a new look.

**Review by nordicjm — DISMISSED** [review]
Not tested it but looks good! Thanks

**Comment by erwango** [comment]
@nordicjm Can you have a new look?
I revisited the choice definition to make it optional, which prevents the need to add dummy choices. This is cleaner.

**Review by FRASTM — APPROVED** [review]

**Comment by erwango** [comment]
@ABOSTM FYI

**Review by nordicjm — APPROVED** [review]

**Review by nordicjm — COMMENTED** [review]
Would combine these 2 commits:

- drivers: ethernet: stm32_hal: Move mac address configuration to dt 
- drivers: stm32: stm32_hal: Generate device id based mac address

Reason is to prevent breakage if someone does a bisect, if they end up on the top commit there, networking will not fail to build but will fail to work.

**Comment by carlescufi** [comment]
> Would combine these 2 commits:
> 
> * drivers: ethernet: stm32_hal: Move mac address configuration to dt
> * drivers: stm32: stm32_hal: Generate device id based mac address
> 
> Reason is to prevent breakage if someone does a bisect, if they end up on the top commit there, networking will not fail to build but will fail to work.

Given that we do not ensure breakage when bisecting in general, although you are right I will merge this to expedite the process.
