### PR TITLE
device: add API to iterate over devices and check their validity

### LINKED ISSUE #24750: need API to get list of succeed initialization device or add initialization status flag in struct device
**Describe the bug**
device_list_get located in device sub system is the API exposed to other modules, and the returned list shouldn't include the initialization failed devices, or at least we should have that kind of API to get all the devices whose initialization is well, though it's not common case that device fail it's initialization.

### PR DESCRIPTION
**Pull request by pabigot**
The power management infrastructure added a generic API to access the static device list, but it is not generally available.  Provide an internal standard API for this.

Replace all the shell infrastructure that iterated over devices with a helper that implements it once.  This incidently fixes bugs related to using a pointer before checking it for null, and matching a prefix wherever it occurred in the device name.

Finally add standard API to determine whether a device is OK to use, so we can replace the nulling of the API pointer with something else.

Fixes #24750

### CODE REVIEW

File: include/device.h [hunk 1]
```diff
@@ -240,6 +240,17 @@ __syscall struct device *device_get_binding(const char *name);
  */
 size_t z_device_get_all_static(struct device **devices);
 
+/** @brief Determine whether a device has been successfully initialized.
+ *
+ * @param dev pointer to the device in question.
+ *
+ * @return true if and only if the device is available for use.
+ */
+static inline bool z_device_ok(const struct device *dev)
```
Comment (tbursztyka) [inline include/device.h:249]: I have a similar patch for device const-ify stuff (name is different and obviously it does not check on driver_api attribute, plus other details). Since that one is not very relevant for that PR, could your remove that commit?

Comment (pabigot) [reply include/device.h]: I wondered if that might conflict, but figured that outside the potential name difference it should be easy to adapt to either.  Removed anyway.

I do think we should be consistent in naming, i.e. agree whether the check for validity  and fetch of static device pointers should be `device_*` or `z_device_*` functions.

Comment (pabigot) [reply include/device.h]: Can't close #24750 without that patch, though.

Comment (tbursztyka) [reply include/device.h]: indeed, I can pull my patch out for it then

Comment (tbursztyka) [reply include/device.h]: Hum it's inside a patch that revise the initialization status part. 

Well, let's cut the pear in half: call it device_ready() and that will be fine for me then

Comment (pabigot) [reply include/device.h]: I'll do that.

But if this is `device_ready` then perhaps `z_device_get_all_static()` should be `device_get_all_static()`.  I don't see applications having a use for `device_ready()`, as they can't get a device pointer unless it's ready.  (In a future Zephyr when they can, e.g. when devices can be made unready, we might have to add more API.)

Comment (pabigot) [reply include/device.h]: It's back, but I kept the internal-use prefix (which I may be mis-using, not sure).  This path allows `device_ready()` to remain available for future situations where somebody might get a device pointer without going through a validating API like `device_get_binding()`, or where a device may be made unready through power management.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]
