### PR TITLE
drivers: ethernet: phy: microchip_t1s: fix link state and callback handling

### LINKED ISSUE #103826: Potential redundant callback trigger in microchip_t1s PHY driver causing log spam
### Describe the bug

I'm working with a 10Base-T1S setup using the microchip,t1s-phy driver under Zephyr (main). I've noticed that my console is getting spammed every 500ms with: `<inf> eth_nxp_enet_mac: Link is up`.

After digging into `phy_microchip_t1s.c` (in the `phy_monitor_work_handler`), it seems the driver triggers the callback inconditionnally at every poll interval, regardless of whether the link state has actually changed.

This causes the MAC driver to re-log the "Link is up" status even when the state is stable.
Even if the NXP driver could be more quiet, it feels like the PHY driver shouldn't trigger a "state change" event when the state is strictly identical.

Questions:

- Is this intentional for T1S/PLCA (e.g., to keep the MAC updated)?
- Should we implement a check to only trigger data->cb when data->state differs from the previous iteration?

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell
[00:00:14.510,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:15.010,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:15.510,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:16.011,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:16.511,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:17.011,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:17.511,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:18.011,000] <inf> eth_nxp_enet_mac: Link is up
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ParthibanI17164**
### Summary

This PR fixes issues in the Microchip T1S PHY driver related to
link state handling and callback invocation (issue #103826).

Previously, the PHY driver:
- Always invoked the link state callback on every check, even when
  the link state had not changed.
- Did not properly synchronize access to the link state.

This caused unnecessary notifications, spurious logging, and potential
race conditions when multiple contexts accessed the PHY state.

### Changes

- Introduces a semaphore to protect the PHY link state.
- Updates link state in `phy_mc_t1s_update_link_state()` with proper synchronization.
- Calls the registered callback only when the link state actually changes.
- Logs link-up and link-down events correctly.

### Impact

- Callback is now invoked only on actual link state changes.
- Link state updates are properly synchronized, preventing race conditions.
- Improves correctness and reduces unnecessary notifications.

Fixes: #103826

### CODE REVIEW

**Comment by pdgendt** [comment]
Please rebase onto `main` instead of merging. Merge commits are not accepted.

**Comment by ParthibanI17164** [comment]
> Please rebase onto `main` instead of merging. Merge commits are not accepted.

Sorry, somehow I messed up. I couldn't rebase. I will try again.

File: drivers/ethernet/phy/phy_microchip_t1s.c [hunk 1]
```diff
@@ -562,6 +579,9 @@ static int phy_mc_t1s_init(const struct device *dev)
 	int ret;
 
 	data->dev = dev;
+	data->state.is_up = false;
+	/* Microchip’s 10BASE-T1S half-duplex PHYs are only supported here */
+	data->state.speed = LINK_HALF_10BASE;
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_t1s.c]: why not just save `is up` in the data struct?

File: drivers/ethernet/phy/phy_microchip_t1s.c
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_t1s.c]: use `phy_mc_t1s_get_link` to get the state, we don't want the state change in the middle of the callback.

might want to have something like
```
static void invoke_link_cb(const struct device *dev)
{
	struct phy_mii_dev_data *const data = dev->data;
	struct phy_link_state state;

	if (data->cb == NULL) {
		return;
	}

	phy_mii_get_link_state(dev, &state);

	data->cb(dev, &state, data->cb_data);
}
```
for invoking the link cb, this is from the phy_mii.c.

in `phy_mc_t1s_link_cb_set` and `phy_mc_t1s_update_link_state`

**Review by maass-hamburg — CHANGES_REQUESTED** [review]

File: drivers/ethernet/phy/phy_microchip_t1s.c (hunk 1 above)
Comment (ParthibanI17164) [reply drivers/ethernet/phy/phy_microchip_t1s.c]: Ah, do you mean that instead of having `struct phy_link_state state;` inside the `data struct`, we should declare `bool is_up` directly in the `data struct`?

Comment (maass-hamburg) [reply drivers/ethernet/phy/phy_microchip_t1s.c]: yes

File: drivers/ethernet/phy/phy_microchip_t1s.c
Comment (ParthibanI17164) [reply drivers/ethernet/phy/phy_microchip_t1s.c]: Ok will do.

File: drivers/ethernet/phy/phy_microchip_t1s.c [hunk 2]
```diff
@@ -562,6 +591,7 @@ static int phy_mc_t1s_init(const struct device *dev)
 	int ret;
 
 	data->dev = dev;
+	data->link_is_up = false;
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_t1s.c]: not needed, is already 0/false

Comment (ParthibanI17164) [reply drivers/ethernet/phy/phy_microchip_t1s.c]: Ah yes, will remove it. Thank you.

**Review by maass-hamburg — DISMISSED** [review]

File: drivers/ethernet/phy/phy_microchip_t1s.c [hunk 3]
```diff
@@ -628,7 +657,9 @@ static DEVICE_API(ethphy, mc_t1s_phy_api) = {
 		.plca = &mc_t1s_plca_##n##_config,                                                 \
 	};                                                                                         \
                                                                                                    \
-	static struct mc_t1s_data mc_t1s_##n##_data;                                               \
+	static struct mc_t1s_data mc_t1s_##n##_data = {                                            \
+		.sem = Z_SEM_INITIALIZER(mc_t1s_##n##_data.sem, 1, 1),                             \
```
Comment (pdgendt) [inline drivers/ethernet/phy/phy_microchip_t1s.c]: This usually is done in the `_init` function of driver with

```c
k_sem_init(&data->sem, 1, 1);
```

**Review by pdgendt — DISMISSED** [review]

File: drivers/ethernet/phy/phy_microchip_t1s.c (hunk 3 above)
Comment (ParthibanI17164) [reply drivers/ethernet/phy/phy_microchip_t1s.c]: Thank you for the feedback.
Would you prefer that I update this by moving it to the `_init` function of the driver, or should I leave the current implementation as is?

Comment (pdgendt) [reply drivers/ethernet/phy/phy_microchip_t1s.c]: My recommendation would be to move it to the init function. The `Z_SEM_INITIALIZER` is not part of the public API, and should be used with care.

Comment (ParthibanI17164) [reply drivers/ethernet/phy/phy_microchip_t1s.c]: Ok thank you for the comment. I will do it now.

**Review by maass-hamburg — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
