### PR TITLE
arch: arm64: coredump: add FP and SP registers for correct GDB backtr…

### LINKED ISSUE #99054: ARM64: Wrong register is being saved in coredump, causing corrupted backtrace show in gdb
### Describe the bug

Following the guide at [link](https://docs.zephyrproject.org/latest/services/debugging/coredump.html), I tried to generate and analyze the coredump of a sample program. When trying out the `bt` command, the stack seems corrupted.

```
(gdb) target remote localhost:1234
Remote debugging using localhost:1234
sys_read32 (addr=19393077248) at /home/bachnguyen/zephyr_porting/ca53_core_zephyr_3.7/include/zephyr/arch/arm64/sys_io.h:73
73              __asm__ volatile("ldr %w0, [%1]" : "=r" (val) : "r" (addr));
(gdb) bt
#0  sys_read32 (addr=19393077248)
    at /home/bachnguyen/zephyr_porting/ca53_core_zephyr_3.7/include/zephyr/arch/arm64/sys_io.h:73
#1  memory_read (sh=0x830211d0 <shell_uart>, addr=19393077248, width=<optimized out>)
    at /home/bachnguyen/zephyr_porting/ca53_core_zephyr_3.7/subsys/shell/modules/devmem_service.c:273
Backtrace stopped: Cannot access memory at address 0x6000004d
```

Next, I ran `info reg` command to check the register values. The value of `sp` was incorrect, as it's not in the SRAM address range.

```
(gdb) info reg
x0             0x830211d0          2197950928
x1             0x483eae000         19393077248
x2             0x20                32
x3             0x8300a724          2197858084
x4             0xa                 10
x5             0x8                 8
x6             0x0                 0
x7             0x6a0               1696
x8             0xaaaaaaaaaaaaaaaa  -6148914691236517206
x9             0xaaaaaaaaaaaaaaaa  -6148914691236517206
x10            0xaaaaaaaaaaaaaaaa  -6148914691236517206
x11            0xaaaaaaaaaaaaaaaa  -6148914691236517206
x12            0xaaaaaaaaaaaaaaaa  -6148914691236517206
x13            0xaaaaaaaaaaaaaaaa  -6148914691236517206
x14            0xaaaaaaaaaaaaaaaa  -6148914691236517206
x15            0x0                 0
x16            0x0                 0
x17            0x0                 0
x18            0xaaaaaaaaaaaaaaaa  -6148914691236517206
x19            <unavailable>
x20            <unavailable>
x21            <unavailable>
x22            <unavailable>
x23            <unavailable>
x24            <unavailable>
x25            <unavailable>
x26            <unavailable>
x27            <unavailable>
x28            <unavailable>
x29            <unavailable>
x30            0x8300619c          2197840284
sp             0x60000045          0x60000045
pc             0x83006008          0x83006008 <memory_read+124>
cpsr           <unavailable>
fpsr           <unavailable>
fpcr           <unavailable>
```

Following the code, here's the structure of ARM64 registers stored inside coredump binary
https://github.com/zephyrproject-rtos/zephyr/blob/b38054bbaea768dda46b67cac042f49480ae4421/arch/arm64/core/coredump.c#L19-L44

And here's the value parsed by the coredump gdb server scripts. Apparently, the value stored was SPSR (Saved Program Status Register), but in the script it is interpreted incorrectly as stack pointer.

https://github.com/zephyrproject-rtos/zephyr/blob/b38054bbaea768dda46b67cac042f49480ae4421/scripts/coredump/gdbstubs/arch/arm64.py#L78-L104

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Build Zephyr for any ARM64 board with `CONFIG_DEBUG_COREDUMP=y`
2. Collect and analyze the coredump following [link](https://docs.zephyrproject.org/latest/services/debugging/coredump.html)

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

Commit b38054bbaea768dda46b67cac042f49480ae4421 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kedareswararao**
…aces

The ARM64 coredump arch block did not include FP (x29) and SP, aking GDB unable to unwind the stack. The GDB stub also misinterpreted SPSR as SP (tu[20] mapped to SP_EL0), producing corrupted stack pointer values and broken backtraces. Bump the arch block version to v2 (24 registers, 192 bytes) adding FP and SP after the existing 22 registers. Update the GDB stub to auto-detect v1 vs v2 blocks by payload size and correctly map SPSR (skip), ELR (PC), FP (x29), and SP.

Fixes #99054

### CODE REVIEW

**Review by mrkhldn — DISMISSED** [review]

File: arch/arm64/core/coredump.c [hunk 1]
```diff
@@ -94,6 +93,17 @@ void arch_coredump_info_dump(const struct arch_esf *esf)
...
+#ifdef CONFIG_FRAME_POINTER
+	arch_blk.r.fp = esf->fp;
+#else
+	arch_blk.r.fp = 0;
+#endif
+	/*
+	 * The exception entry macro does: sub sp, sp, ___esf_t_SIZEOF
+	 * So the pre-fault SP is right above the saved ESF.
+	 */
+	arch_blk.r.sp = (uintptr_t)esf + sizeof(struct arch_esf);
```
Comment (JiafeiPan) [inline arch/arm64/core/coredump.c:106]: This matches “pre-fault SP = SP_after_alloc + frame_size” only for the stack pointer used to build the ESF.

But when CONFIG_ARM64_SAFE_EXCEPTION_STACK is enabled, the exception entry code already saves the original sp_el0 into the ESF (struct arch_esf has a sp field under CONFIG_ARM64_SAFE_EXCEPTION_STACK, and vector_table.S stores sp_el0 there for EL0 exceptions), refer to [this code
](https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/arm64/core/vector_table.S#L90)

So for EL0 exceptions with safe exception stack enabled, the best “fault SP” is esf->sp, but not (esf + sizeof)

Comment (kedareswararao) [reply arch/arm64/core/coredump.c:106]: Thanks for the review updated the code to handle this use case well please review when you have sometime.

**Review by mrkhldn — DISMISSED** [review]

**Review by npitre — DISMISSED** [review]
Looks good overall.

One minor suggestion: in the `#else` path for SP reconstruction (`coredump.c` line 108), it might be worth noting that for EL0 exceptions this gives SP_EL1 (kernel stack), not the user SP_EL0:

```c
/*
 * The exception entry does: sub sp, sp, ___esf_t_SIZEOF
 * So the pre-fault SP is right above the saved ESF.
 * Note: for EL0 exceptions this is SP_EL1, not the user SP_EL0.
 */
```

Not blocking — the safe-exception-stack path correctly uses the saved `sp_el0`, and most coredump scenarios are EL1 faults anyway.

File: arch/arm64/core/coredump.c (hunk 1 above)
Comment (JiafeiPan) [reply arch/arm64/core/coredump.c:106]: Also need to check whether the exception is from EL0 when use esf->sp, suggest the following code:

```suggestion
    arch_blk.r.sp = (uintptr_t)esf + sizeof(struct arch_esf);
#ifdef CONFIG_ARM64_SAFE_EXCEPTION_STACK
	/*
	 * When SAFE_EXCEPTION_STACK is enabled, for EL0 exceptions the vector
	 * entry saves the original sp_el0 into esf->sp.
	 */
	if (esf->spsr & SPSR_MODE_MASK) == SPSR_MODE_EL0T) {
		arch_blk.r.sp = esf->sp;
	}
#endif

```

**Review by JiafeiPan — CHANGES_REQUESTED** [review]

**Review by JiafeiPan — APPROVED** [review]

**Comment by kedareswararao** [comment]
@npitre Please re-approve updated comments as suggested
@mrkhldn: Please re-approve addressed updated review comments

**Review by wearyzen — APPROVED** [review]

**Review by npitre — APPROVED** [review]

**Review by mrkhldn — APPROVED** [review]
