### PR TITLE
ws2812_gpio: Fix prematurely overwrite of pixel input

### LINKED ISSUE #96099: drivers: ws2812_gpio: driver overwrites still used values in loop
### Describe the bug

During debugging, I noticed that the WS2812 GPIO driver overwrites values that are still about to read in future loops. E.g., by having a color-mapping of <BGR> and wanting to to write a red color value, it overwrites by reading blue into the same buffer where the red value is stored.

I work with a self-designed board based on the nordic nrf52 series, and I reproduced the image with modification of the led_strip example.

I fixed this issue, together with another 'error case' that may be a problem, at https://github.com/zephyrproject-rtos/zephyr/pull/95815

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

OS: Linux
Zephyr toolchain 0.17.4
Zephyr main

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Alicipy**
This PR fixes too early overwriting of the input led buffer during iteration, and statically assures that no overflow happens.

While the API allows modification of the led input, the ws2812_gpio driver modified the input already due to the ptr alias, while it still reads in the next inner loop. This leads to reading already modified values, making the LED strip showing other colors than expected.

I also noticed that the code could technically overflow when there are more color mappings than the struct led. But as I am unsure if this is a realistic problem, I went for a BUILD_ASSERT so in case one has an LED strip, it does not break during runtime but earlier to fix if necessary, as a new buffer would need additional memory. 

Fixes #96099

### CODE REVIEW

**Comment by ljd42** [comment]
Fixes: #96099

File: drivers/led_strip/ws2812_gpio.c [hunk 1]
```diff
@@ -225,6 +225,10 @@ static const uint8_t ws2812_gpio_##idx##_color_mapping[] =		\
 		return gpio_pin_configure_dt(&cfg->gpio, GPIO_OUTPUT);	\
 	}								\
 									\
+	BUILD_ASSERT(WS2812_NUM_COLORS(idx) <= sizeof(struct led_rgb),  \
+		"Due to implementation details, the number of channels" \
+		" in color-mapping is restricted");			\
+									\
```
Comment (ljd42) [inline drivers/led_strip/ws2812_gpio.c:231]: Nit-picking here.
Suggest to improve user's driver experience by twisting slightly your build assert error. Something along the line:

> too many channels in color-mapping; currently not supported by the ws2812_gpio driver

**Review by ljd42 — COMMENTED** [review]
Good Catch :+1:

I had some difficulty to understand the change for the 2nd commit 'prevent overflow'. I got confused by the first part in the commit message:
> In case one defines an RGB led that is bigger than the led_rgb struct,

This could be perhaps reworded. 
Also, the build assert error message could be more explicit. 

Apart this nit-picking comments, PR looks good!

File: drivers/led_strip/ws2812_gpio.c [hunk 2]
```diff
@@ -140,6 +140,7 @@ static int ws2812_gpio_update_rgb(const struct device *dev,
 	/* Convert from RGB to on-wire format (e.g. GRB, GRBW, RGB, etc) */
 	for (i = 0; i < num_pixels; i++) {
 		uint8_t j;
+		const struct led_rgb current_pixel = pixels[i];
```
Comment (simonguinot) [inline drivers/led_strip/ws2812_gpio.c:143]: I don't think that pixels are overwritten here because the `LED_STRIP_RGB_SCRATCH` option is selected for this driver. This provides the pad space needed to reorder the pixels safely.

**Review by simonguinot — CHANGES_REQUESTED** [review]

File: drivers/led_strip/ws2812_gpio.c (hunk 2 above)
Comment (simonguinot) [reply drivers/led_strip/ws2812_gpio.c:143]: Well, actually they are :) Please, can you remove the `LED_STRIP_RGB_SCRATCH` dependency ?

File: drivers/led_strip/ws2812_gpio.c (hunk 1 above)
Comment (Alicipy) [reply drivers/led_strip/ws2812_gpio.c:231]: Thanks for the idea, I took this 'as is', I was also unsure how to write it in a clear way.

File: drivers/led_strip/ws2812_gpio.c (hunk 2 above)
Comment (Alicipy) [reply drivers/led_strip/ws2812_gpio.c:143]: Thanks for the response, and sorry for taking so long to fix.

When one only use GRB, the scratch indeed helped previously, but with more complex addressing, it removed information.

I removed the dependency as it is not necessary anymore.

**Review by ljd42 — APPROVED** [review]
LGTM. Thanks for your PR!

**Review by simonguinot — APPROVED** [review]
Thanks for the bug fix !
