### PR TITLE
driver: flash: esp32: fix unaligned read

### LINKED ISSUE #86241: espressif: Flash driver not accouting for all unaligned reading scenarios
**Describe the bug**
ESP32 flash driver do not perform full unaligned scenarios check, failing during MCUBoot read operations.

**Impact**
It can lead to failing OTA operation. 

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK 0.17.0
 - v4.1-rc2

### PR DESCRIPTION
**Pull request by sylvioalves**
Fix flash read operation to account for all unaligned
scenarios, i.e, address, buffer and length. This is needed
when using flash APIs provided in ROM.

This also removes the unaligned flash write call as it
expects aligned values only.

ROM flash code calls are only used in MCUBoot environment as it saves aroung 16kb RAM when
compare to default spi_flash calls.

Fixes #86241

### CODE REVIEW

**Comment by sylvioalves** [comment]
PR is ready.

File: drivers/flash/flash_esp32.c [hunk 1]
```diff
@@ -76,26 +76,67 @@ static inline void flash_esp32_sem_give(const struct device *dev)
...
-		ret = esp_rom_flash_read(aligned_address, temp_buf, aligned_length, true);
+	uint8_t *dest_ptr = (uint8_t *)buffer;
+	size_t remaining = length;
+	size_t copy_size = 0;
+	size_t aligned_size = 0;
+	bool allow_decrypt = esp_flash_encryption_enabled();
+
+	if (flash_esp32_is_aligned(address, buffer, length)) {
+		ret = esp_rom_flash_read(address, buffer, length, allow_decrypt);
+		return -EIO;
```
Comment (marekmatej) [inline drivers/flash/flash_esp32.c:101]: shouldnt it return `ret` instead of `-EIO`  ?

Comment (sylvioalves) [reply drivers/flash/flash_esp32.c]: Please, check again.

**Review by wmrsouza — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]
