### PR TITLE
Bluetooth: controller: fix failing EBQ scanner tests

### LINKED ISSUE #59580: Bluetooth: Controller: EBQ: failing LL/DDI/ADV/BV-??-C tests
Describe the bug
EBQ: failing LL/DDI/ADV/BV-??-C tests on zephyr main branch, a regression from the previous EBQ testing autumn 2022
tests fail with an assert in nordic/lll/lll_adv.c, line 442

To Reproduce
perform an EBQ run

Expected behavior
test should pass

Impact
What impact does this issue have on your progress (e.g., annoyance, showstopper)

Logs and console output
N/A

Environment (please complete the following information):

OS: (e.g. Linux, MacOS, Windows)
Toolchain (e.g Zephyr SDK, ...)
Commit SHA or Version used
Additional context
N/A

### PR DESCRIPTION
**Pull request by kruithofa**
In the case that chaining is enabled when adding new data to an advertising chain a new PDU is created for this data. This limits how often data can be added to the number of available PDUs.

The changes in this PR add the data to the last PDU in the chain, and only if there is not enough room a new PDU is created

A test was added to CI where the name is set to an extra long length to force an overflow of data to occur so that this new functionality is tested

See issues #63288 and #63290 for further improvements

fixes #59580

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 1]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			/*
+			 * in the next PDU we still need to add ad_len_chain bytes of data
+			 * but we do not have overflow, since we already added
+			 * the exact amount that would fit
+			 */
+			ad_len_chain = len-ad_len;
+			ad_len_overflow = 0;
+
+		} else {
+			ad_len_overflow = 0;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:466]:
```suggestion
			ad_len_overflow = 0U;

		} else {
			ad_len_overflow = 0U;
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 2]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			(void)memcpy(val_ptr, &data, sizeof(data));
+
+			/* we now know how much data we can add to the
+			 * last PDU without getting an overflow
+			 */
+			chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+							   (ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND |
+							    ULL_ADV_PDU_HDR_FIELD_AUX_PTR),
+							   0, hdr_data);
+			LL_ASSERT(chain_err == 0);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:456]:
```suggestion
			LL_ASSERT(chain_err == 0U);
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 3]
```diff
@@ -555,8 +612,12 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
 		pdu_chain->len = sec_len + ad_len_overflow + len;
 
 		/* Fill AD Data in chain PDU */
-		(void)memcpy(dptr_chain, data, len);
-
+		if (ad_len_overflow != 0) {
+			(void)memcpy(dptr_chain, data, ad_len_overflow);
+		}
+		if (ad_len_chain != 0) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:618]:
```suggestion
		if (ad_len_overflow != 0U) {
			(void)memcpy(dptr_chain, data, ad_len_overflow);
		}
		if (ad_len_chain != 0U) {
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 4]
```diff
@@ -555,8 +612,12 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			(void)memcpy(dptr_chain, &data[ad_len + ad_len_overflow], len);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:619]: Should this have been
```suggestion
			(void)memcpy(dptr_chain, &data[ad_len + ad_len_overflow], ad_len_chain);
```

File: tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf [hunk 5]
```diff
@@ -0,0 +1,41 @@
+CONFIG_BT=y
+CONFIG_BT_BROADCASTER=y
+CONFIG_BT_OBSERVER=y
+CONFIG_BT_EXT_ADV=y
+CONFIG_BT_EXT_ADV_MAX_ADV_SET=2
+#
+# The extra long device name requires chaining an additional PDU in this test-case
+CONFIG_BT_DEVICE_NAME="Broadcaster Multiple with an extra long name 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf:8]: Wouldn't it have been "easier" to define some long advertising data in the test instead? The host may truncate this

File: tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+
+# Maximum Extended Scanning buffer size
+CONFIG_BT_EXT_SCAN_BUF_SIZE=1650
+
+# Set maximum scan data length for Extended Scanning in Bluetooth LE Controller
+CONFIG_BT_CTLR_SCAN_DATA_LEN_MAX=1650
+
+# Zephyr Bluetooth LE Controller needs 16 event buffers to generate Extended
+# Advertising Report for receiving the complete 1650 bytes of data
+CONFIG_BT_BUF_EVT_RX_COUNT=16
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf:37]: Why 16? Each report can hold up to 229 octets, so for 1650 octets at most 8 events are required

File: tests/bsim/bluetooth/host/adv/chain/src/main.c [hunk 7]
```diff
@@ -31,7 +31,11 @@
 		bs_trace_info_time(1, __VA_ARGS__);	\
 	} while (0)
 
+#if defined(CONFIG_BT_DEVICE_NAME)
+#define NAME_LEN (strlen(CONFIG_BT_DEVICE_NAME) + 1U)
+#else
 #define NAME_LEN 30
+#endif
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/adv/chain/src/main.c:38]: Ditto

File: tests/bsim/bluetooth/host/adv/chain/src/main.c [hunk 8]
```diff
@@ -94,25 +98,29 @@ static void scan_recv(const struct bt_le_scan_recv_info *info,
 
 	data_len = buf->len;
 	if (data_len != DATA_LEN) {
+		printk("Unexpected length\n");
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/adv/chain/src/main.c:101]: Shouldn't this fail? Please also print the `data_len` here for debugging purposes

File: tests/bsim/bluetooth/host/adv/chain/src/main.c [hunk 9]
```diff
@@ -94,25 +98,29 @@ static void scan_recv(const struct bt_le_scan_recv_info *info,
...
 		if (sid[i] == info->sid) {
+			printk("Wrong SID\n");
 			return;
 		}
 	}
 
 	sid[sid_count++] = info->sid;
 
 	if (sid_count < CONFIG_BT_EXT_ADV_MAX_ADV_SET) {
+		printk("Wrong number of advertising sets\n");
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/adv/chain/src/main.c:123]: Ditto

**Review by Thalley — DISMISSED** [review]

File: samples/bluetooth/observer/src/observer.c [hunk 10]
```diff
@@ -9,7 +9,11 @@
 #include <zephyr/bluetooth/bluetooth.h>
 #include <zephyr/bluetooth/hci.h>
 
+#if defined(CONFIG_BT_DEVICE_NAME)
+#define NAME_LEN (strlen(CONFIG_BT_DEVICE_NAME) + 1U)
+#else
 #define NAME_LEN 30
+#endif
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply samples/bluetooth/observer/src/observer.c:16]: You are right, we need instead to check whether the device name is configurable during runtime. Updated this piece of code accordingly

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 11]
```diff
@@ -116,7 +116,9 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
 	struct pdu_adv *pdu_prev;
 	uint8_t ad_len_overflow;
 	uint8_t ad_len_chain;
+	uint8_t chain_err = 0;
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:119]: done

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 12]
```diff
@@ -317,28 +318,22 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
-			/* Prepare for aux ptr field reference to be returned, hence
-			 * second parameter will be for AD data field.
-			 */
-			*val_ptr = 0U;
-			(void)memset((void *)&val_ptr[ULL_ADV_HDR_DATA_DATA_PTR_OFFSET],
-				     0U, ULL_ADV_HDR_DATA_DATA_PTR_SIZE);
+			val_ptr = hdr_data;
+			*val_ptr++ = 0U;
+			(void)memset((void *)val_ptr, 0U,
+			     ULL_ADV_HDR_DATA_DATA_PTR_SIZE);
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:326]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 13]
```diff
@@ -317,28 +318,22 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
 		do {
-			/* Prepare for aux ptr field reference to be returned, hence
-			 * second parameter will be for AD data field.
-			 */
-			*val_ptr = 0U;
-			(void)memset((void *)&val_ptr[ULL_ADV_HDR_DATA_DATA_PTR_OFFSET],
-				     0U, ULL_ADV_HDR_DATA_DATA_PTR_SIZE);
+			val_ptr = hdr_data;
+			*val_ptr++ = 0U;
+			(void)memset((void *)val_ptr, 0U,
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:325]: OTOH val_ptr points to unsigned int. There are several other places in the code where 0U is used in memset. Let us discuss outside of this PR, and create another PR to fix all locations if that is what we agree on.

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 14]
```diff
@@ -317,28 +318,22 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
 			pdu = pdu_chain;
 
-			/* Add Aux Ptr field if not already present */
 			err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
-						(ULL_ADV_PDU_HDR_FIELD_AD_DATA |
-						 ULL_ADV_PDU_HDR_FIELD_AUX_PTR),
-						0, hdr_data);
-			LL_ASSERT(!err || (err == BT_HCI_ERR_PACKET_TOO_LONG));
+							ULL_ADV_PDU_HDR_FIELD_AD_DATA,
+							0, hdr_data);
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:333]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 15]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
 	if ((op == BT_HCI_LE_EXT_ADV_OP_INTERM_FRAG) ||
-	    (op == BT_HCI_LE_EXT_ADV_OP_LAST_FRAG) ||
-	    ad_len_overflow) {
+	    (op == BT_HCI_LE_EXT_ADV_OP_LAST_FRAG)) {
+		/* in the previous step we duplicated the chain
+		 * the next step is to append new data in the last existing pdu in the chain,
+		 */
+
+		val_ptr = hdr_data;
+		*val_ptr++ =  len;
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:394]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 16]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+		(void)memcpy(val_ptr, &data, sizeof(data));
+
+		/* Append data to the last PDU */
+		chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+						      (ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND),
+						      0, hdr_data);
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:400]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 17]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+		 * the next step is to append new data in the last existing pdu in the chain,
+		 */
+
+		val_ptr = hdr_data;
+		*val_ptr++ =  len;
+		(void)memcpy(val_ptr, &data, sizeof(data));
+
+		/* Append data to the last PDU */
+		chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+						      (ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND),
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:399]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 18]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			val_ptr = hdr_data;
+			*val_ptr++ =  len;
+			(void)memcpy(val_ptr, &data, sizeof(data));
+			val_ptr += sizeof(data);
+			*val_ptr++ =  len;
+			(void)memcpy(val_ptr, &data, sizeof(data));
+			chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+							   (ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND |
+							    ULL_ADV_PDU_HDR_FIELD_AUX_PTR),
+							    0, hdr_data);
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:424]: fixed

[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:424]: but proper indentation pushes us over the 100 character line limit...

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 19]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			 * ad_len_overflow_first_try is how much overflows without the AUX ptr
+			 * ad_len_overflow is how much overflows with the AUX ptr
+			 */
+			uint8_t ad_len_overflow_first_try;
+
+			ad_len_overflow_first_try = hdr_data[ULL_ADV_HDR_DATA_DATA_PTR_OFFSET +
+							     ULL_ADV_HDR_DATA_DATA_PTR_SIZE];
+
+			val_ptr = hdr_data;
+			*val_ptr++ =  len;
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:416]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 20]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			(void)memcpy(val_ptr, &data, sizeof(data));
+			val_ptr += sizeof(data);
+			*val_ptr++ =  len;
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:419]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 21]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			(void)memcpy(val_ptr, &data, sizeof(data));
+			chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+							   (ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND |
+							    ULL_ADV_PDU_HDR_FIELD_AUX_PTR),
+							    0, hdr_data);
+			ad_len_overflow =
+				hdr_data[ULL_ADV_HDR_DATA_AUX_PTR_PTR_OFFSET +
+					 ULL_ADV_HDR_DATA_AUX_PTR_PTR_SIZE +
+					 ULL_ADV_HDR_DATA_DATA_PTR_OFFSET +
+					 ULL_ADV_HDR_DATA_DATA_PTR_SIZE];
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:429]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 22]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			/* ad_len_overflow - ad_len_overflow_first_try is the size of
+			 * the AUX_PTR and optional header
+			 * ad_len_prev is how much data is already present, ad_len is how
+			 * much data we can add to this PDU
+			 */
+			/* FIXME: why do we need to subtract the extra bytes,
+			 * is PDU_AC_PAYLOAD_SIZE_MAX wrong?
+			 */
+			ad_len =  PDU_AC_PAYLOAD_SIZE_MAX - ad_len_prev -
+				(ad_len_overflow - ad_len_overflow_first_try) - 4;
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:440]: yes, this needs an explanation @cvinayak

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 23]
```diff
@@ -411,8 +385,89 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			*val_ptr++ =  ad_len;
+			(void)memcpy(val_ptr, &data, sizeof(data));
+
+			/* we now know how much data we can add to the
+			 * last PDU without getting an overflow
+			 */
+			chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+							   (ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND |
+							    ULL_ADV_PDU_HDR_FIELD_AUX_PTR),
+							   0, hdr_data);
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:455]: either that or over the 100 character limit

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 1 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:466]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 2 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:456]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 3 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:618]: fixed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 4 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:619]: fixed

File: tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf (hunk 6 above)
Comment (kruithofa) [reply tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf:37]: Hm, this was copied from prj.conf

File: tests/bsim/bluetooth/host/adv/chain/src/main.c (hunk 8 above)
Comment (kruithofa) [reply tests/bsim/bluetooth/host/adv/chain/src/main.c:101]: Didn't cause fail in the original test. Text updated to better reflect this, and print more debugging info

File: tests/bsim/bluetooth/host/adv/chain/src/main.c (hunk 9 above)
Comment (kruithofa) [reply tests/bsim/bluetooth/host/adv/chain/src/main.c:123]: Did not fail in the original test. Updated text to reflect this better

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 13 above)
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:325]: Doesn't really matter that much :) But it's just common to use `U` when doing unsigned, and omit it for signed values (like for `memset`).

File: tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf (hunk 5 above)
Comment (Thalley) [reply tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf:8]: My point is that the name has specific handling in the host: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/adv.c#L511-L518

Where it may be truncated, so using the name to set large advertising data may not work as intended. 

Any other advertising type would work ;)

File: samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c [hunk 24]
```diff
@@ -75,7 +79,7 @@ int broadcaster_multiple(void)
 		printk("Bluetooth init failed (err %d)\n", err);
 		return err;
 	}
-
+printk("Length: %d\n", BT_DEVICE_NAME_LEN);
```
Comment (Thalley) [inline samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c:82]: Leftover debug?

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 25]
```diff
@@ -411,8 +385,88 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			val_ptr = hdr_data;
+			*val_ptr++ = len;
+			(void)memcpy(val_ptr, &data, sizeof(data));
+			val_ptr += sizeof(data);
+			*val_ptr++ = len;
+			(void)memcpy(val_ptr, &data, sizeof(data));
+			chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+							   (ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND |
+							    ULL_ADV_PDU_HDR_FIELD_AUX_PTR),
+							    0U, hdr_data);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:424]: One alternative to make this fit in 100 line length is to do
```suggestion
			chain_err = ull_adv_aux_pdu_set_clear(
				adv, pdu_prev, pdu, 
				(ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND | 
				 ULL_ADV_PDU_HDR_FIELD_AUX_PTR), 
				0U, hdr_data);1
```

Alternatively move `(ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND | ULL_ADV_PDU_HDR_FIELD_AUX_PTR)` to a local `const `variable

Another alternative is to move this into a new function (`ll_adv_aux_ad_data_set` is 500 lines long with this change, so arguably that should be split into multiple functions anyhow).

File: samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c (hunk 24 above)
Comment (kruithofa) [reply samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c]: removed

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 26]
```diff
@@ -411,8 +385,88 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+		(void)memcpy(val_ptr, &data, sizeof(data));
+
+		/* Append data to the last PDU */
+		chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+						      ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND,
+						      0U, hdr_data);
+
+		LL_ASSERT((!chain_err)  || (chain_err == BT_HCI_ERR_PACKET_TOO_LONG));
+
+		/* FIXME: this probably needs a for loop  */
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c]: updated the comment, the handling has become quite complex and we should probably rewrite this whole procedure to simplify.

**Comment by kruithofa** [comment]
@Tronil for some reason I can not reply to your comment regarding the calculation. Actually it is the right calculation, we substract ad_len_overflow_first_try from ad_len_overflow_first to find how much extra data is needed in the variable sized header.
But the code has become quite complicated and @cvinayak and I agree that this code needs a rewrite

**Comment by Thalley** [comment]
@kruithofa Please also update the commit message for the first commit (and the PR title too) as "Bluetooth: controller: fix regression" is extremely generic :D

**Review by cvinayak — CHANGES_REQUESTED** [review]
review rework in ull_adv_aux.c file may have been commited to the test file commits, please move the changes to the other commit.

**Comment by cvinayak** [comment]
@aescolar new bsim test, you may be interested to test/review.

**Comment by aescolar** [comment]
> @aescolar new bsim test, you may be interested to test/review.

No evident issues to my eyes, and the test works fine on a simulated nrf53

File: tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf (hunk 6 above)
Comment (cvinayak) [reply tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf:37]: 8 + 8, is used as Zephyr Controller does not combine all the 1650 bytes before fragmenting them into 8 HCI reports, if a PDU has 255 bytes, it will generate 2 HCI reports.

**Review by cvinayak — DISMISSED** [review]

File: tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf (hunk 6 above)
Comment (Thalley) [reply tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf:37]: I see. Can we update the comment to state this? It just says that it needs 16, but not _why_

**Comment by carlescufi** [comment]
@Thalley PTAL

**Comment by Thalley** [comment]
> @Thalley PTAL

@kruithofa There are still a few unresolved comments from previous reviews. Will re-review once they have been resolved

File: tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf (hunk 6 above)
Comment (kruithofa) [reply tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf:37]: Updated the comment to explain why

File: tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf (hunk 5 above)
Comment (kruithofa) [reply tests/bsim/bluetooth/host/adv/chain/prj_extra_chain.conf:8]: Removed the long name, and duplicated the manufacturer data field

File: tests/bsim/bluetooth/host/adv/chain/src/main.c (hunk 7 above)
Comment (Thalley) [reply tests/bsim/bluetooth/host/adv/chain/src/main.c:38]: @kruithofa Will you update this as well?

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 22 above)
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:440]: @kruithofa If this is correct, please update the comment. 

Regardless if this is correct or not, it probably shouldn't use magic numbers like `4` :)

[the remark this answers is not in the document]
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:440]: @cvinayak can we discuss this?

File: samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c [hunk 27]
```diff
@@ -75,7 +75,6 @@ int broadcaster_multiple(void)
 		printk("Bluetooth init failed (err %d)\n", err);
 		return err;
 	}
-
```
Comment (Thalley) [inline samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c:78]: You can remove this change

File: samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c [hunk 28]
```diff
@@ -27,7 +27,11 @@
 #define BT_AD_DATA_FORMAT_LEN_MAX 255U
 
 /* Device name length, size minus one null character */
-#define BT_DEVICE_NAME_LEN (sizeof(CONFIG_BT_DEVICE_NAME) - 1U)
+#if defined(CONFIG_BT_DEVICE_NAME_DYNAMIC)
+#define BT_DEVICE_NAME_LEN (CONFIG_BT_DEVICE_NAME_MAX + 1U)
+#else
+#define BT_DEVICE_NAME_LEN sizeof(CONFIG_BT_DEVICE_NAME)
+#endif
```
Comment (Thalley) [inline samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c:34]: This change now seems unnecessary

File: samples/bluetooth/observer/src/observer.c [hunk 29]
```diff
@@ -9,7 +9,11 @@
 #include <zephyr/bluetooth/bluetooth.h>
 #include <zephyr/bluetooth/hci.h>
 
-#define NAME_LEN 30
+#if defined(CONFIG_BT_DEVICE_NAME_DYNAMIC)
+#define NAME_LEN (CONFIG_BT_DEVICE_NAME_MAX + 1U)
+#else
+#define NAME_LEN sizeof(CONFIG_BT_DEVICE_NAME)
+#endif
```
Comment (Thalley) [inline samples/bluetooth/observer/src/observer.c:16]: Ditto; this change can be reverted

File: tests/bsim/bluetooth/host/adv/chain/src/main.c [hunk 30]
```diff
@@ -31,11 +31,19 @@
 		bs_trace_info_time(1, __VA_ARGS__);	\
 	} while (0)
 
-#define NAME_LEN 30
+#if defined(CONFIG_BT_DEVICE_NAME_DYNAMIC)
+#define NAME_LEN (CONFIG_BT_DEVICE_NAME_MAX + 1U)
+#else
+#define NAME_LEN sizeof(CONFIG_BT_DEVICE_NAME)
+#endif
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/adv/chain/src/main.c:38]: Ditto; this change can be reverted

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 31]
```diff
@@ -411,8 +385,88 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+		 * must be send, and create the chained PDUs from this array
+		 */
+		if (chain_err == BT_HCI_ERR_PACKET_TOO_LONG) {
+			/* We could not fit all the data, append as much as possible
+			 * ad_len_overflow_first_try is how much overflows without the AUX ptr
+			 * ad_len_overflow is how much overflows with the AUX ptr
+			 */
+			uint8_t ad_len_overflow_first_try;
+			const uint16_t chain_add_fields = ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND |
+				ULL_ADV_PDU_HDR_FIELD_AUX_PTR;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:415]:
```suggestion
			const uint16_t chain_add_fields = ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND |
							  ULL_ADV_PDU_HDR_FIELD_AUX_PTR;
```

**Review by Thalley — CHANGES_REQUESTED** [review]

**Comment by kruithofa** [comment]
we want to consider issue #63290 and #63288 before merging this (or replacing with another PR)

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 22 above)
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:440]: @Tronil and @Emil-Gydesen-Bose  Myself and @kruithofa has a code walk through today and found a bug in the `ull_adv_aux_pdu_set_clear()` function wherein it did not correctly return the overflow length. We now are able to fill the Adv chain PDUs to its max 255 bytes PDU length with @Tronil  suggested `len - ad_len_overflow` as the last PDU's AD length before adding a following new chain PDU to contain the remainder bytes.

Please review #63298, and then this PR will be updated to remove the unnecessary `ad_len_overflow_first_try` value that was used to do the complex calculations.

@kruithofa will update this PR once #63298 is merged.

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c (hunk 28 above)
Comment (kruithofa) [reply samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c:34]: It is not really necessary, but is a more generic way of setting the device name. I prefer leaving it this way.

File: samples/bluetooth/observer/src/observer.c (hunk 29 above)
Comment (kruithofa) [reply samples/bluetooth/observer/src/observer.c:16]: The original set the NAME_LEN to a fixed nr. I prefer this way

File: tests/bsim/bluetooth/host/adv/chain/src/main.c (hunk 30 above)
Comment (kruithofa) [reply tests/bsim/bluetooth/host/adv/chain/src/main.c:38]: Ditto I will remove the conditional compile

File: samples/bluetooth/observer/src/observer.c [hunk 32]
```diff
@@ -9,7 +9,7 @@
 #include <zephyr/bluetooth/bluetooth.h>
 #include <zephyr/bluetooth/hci.h>
 
-#define NAME_LEN 30
+#define NAME_LEN sizeof(CONFIG_BT_DEVICE_NAME)
```
Comment (Thalley) [inline samples/bluetooth/observer/src/observer.c:12]: Can't this be reverted back to how it was? Or is this change necessary?

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 33]
```diff
@@ -411,8 +385,85 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+		val_ptr = hdr_data;
+		*val_ptr++ = len;
+		(void)memcpy(val_ptr, &data, sizeof(data));
+
+		/* Append data to the last PDU */
+		chain_err = ull_adv_aux_pdu_set_clear(adv, pdu_prev, pdu,
+						      ULL_ADV_PDU_HDR_FIELD_AD_DATA_APPEND,
+						      0U, hdr_data);
+
+		LL_ASSERT((!chain_err)  || (chain_err == BT_HCI_ERR_PACKET_TOO_LONG));
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:402]:
```suggestion
		LL_ASSERT((!chain_err) || (chain_err == BT_HCI_ERR_PACKET_TOO_LONG));
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 34]
```diff
@@ -411,8 +385,85 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+			LL_ASSERT(chain_err == 0U);
+			/*
+			 * in the next PDU we still need to add ad_len_chain bytes of data
+			 * but we do not have overflow, since we already added
+			 * the exact amount that would fit. We explicitly set overflow to 0.
+			 * FIXME: ad_len_overflow already should be 0, to be verified. We wait
+			 * fixing this until rewriting this whole function
+			 */
+			ad_len_overflow = 0U;
+
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:460]:
```suggestion
			ad_len_overflow = 0U;
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 35]
```diff
@@ -555,8 +608,12 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
 		pdu_chain->len = sec_len + ad_len_overflow + len;
 
 		/* Fill AD Data in chain PDU */
-		(void)memcpy(dptr_chain, data, len);
-
+		if (ad_len_overflow != 0U) {
+			(void)memcpy(dptr_chain, data, ad_len_overflow);
+		}
+		if (ad_len_chain != 0U) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:614]:
```suggestion
		}
		
		if (ad_len_chain != 0U) {
```

File: tests/bsim/bluetooth/host/adv/chain/src/main.c [hunk 36]
```diff
@@ -31,11 +31,15 @@
 		bs_trace_info_time(1, __VA_ARGS__);	\
 	} while (0)
 
-#define NAME_LEN 30
+#define NAME_LEN sizeof(CONFIG_BT_DEVICE_NAME)
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/adv/chain/src/main.c:34]: Can't this be reverted back to how it was? Or is this change necessary?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c [hunk 37]
```diff
@@ -26,8 +26,8 @@
 /* Maximum value of AD data format length field (8-bit) */
 #define BT_AD_DATA_FORMAT_LEN_MAX 255U
 
-/* Device name length, size minus one null character */
-#define BT_DEVICE_NAME_LEN (sizeof(CONFIG_BT_DEVICE_NAME) - 1U)
+/* Device name length, size */
+#define BT_DEVICE_NAME_LEN sizeof(CONFIG_BT_DEVICE_NAME)
```
[the remark this answers is not in the document]
Comment (kruithofa) [reply samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c:30]: it is not related to what we are fixing here, but is more correct. I'll put it in a separate PR

File: samples/bluetooth/observer/src/observer.c (hunk 32 above)
Comment (kruithofa) [reply samples/bluetooth/observer/src/observer.c:12]: Ditto, separate PR

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 33 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:402]: done

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 34 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:460]: done

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 35 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:614]: done

File: tests/bsim/bluetooth/host/adv/chain/src/main.c (hunk 36 above)
Comment (kruithofa) [reply tests/bsim/bluetooth/host/adv/chain/src/main.c:34]: Ditto, separate PR

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 38]
```diff
@@ -411,8 +385,84 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+		LL_ASSERT((!chain_err) || (chain_err == BT_HCI_ERR_PACKET_TOO_LONG));
+
+		/* FIXME: the code has become quite complex, an alternative and simpler
+		 * implementation would be to first fill an array with all data that
+		 * must be send, and create the chained PDUs from this array
+		 */
+		if (chain_err == BT_HCI_ERR_PACKET_TOO_LONG) {
+			/* We could not fit all the data, append as much as possible
+			 * ad_len_overflow_first_try is how much overflows without the AUX ptr
+			 * ad_len_overflow is how much overflows with the AUX ptr
```
Comment (Tronil) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:411]: Unless I am missing something, `ad_len_overflow_first_try` was removed, so this comment is no longer correct

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 39]
```diff
@@ -411,8 +385,84 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
+						ULL_ADV_HDR_DATA_DATA_PTR_OFFSET +
+						ULL_ADV_HDR_DATA_DATA_PTR_SIZE];
+
+			/* len is the total amount of datawe want to add
+			 * ad_len_chain is the amount of data that does
+			 * not fit in the current PDU
+			 * the difference of the two is the amount that
+			 * we can fit in the current PDU
+			 */
+			ad_len = len - ad_len_chain;
```
Comment (Tronil) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:436]: What happens if we have a completely full PDU that we want to add an aux ptr to (ie. we now have to move some existing advertising data to the next PDU)? This code doesn't seem to handle that case.

Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:436]: That is handled by the ull_adv_aux_clear_set function. However this code is hard to follow, so we want to do a rewrite. See issue #63288 and #63290

**Review by Tronil — APPROVED** [review]

**Review by Thalley — DISMISSED** [review]

**Review by Tronil — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 38 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:410]: fixed

File: samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c [hunk 40]
```diff
@@ -47,11 +47,18 @@
 					BT_AD_DATA_FORMAT_LEN_SIZE - \
 					BT_AD_DATA_FORMAT_TYPE_SIZE - \
 					BT_DEVICE_NAME_AD_DATA_LEN)))
-
+/*
+ * Datalength is an integer, so BT_MFG_DATA_LEN can not be larger than 255.
+ * To ensure that we need to chain PDUs we therefor add manufacturer data
```
Comment (cvinayak) [inline samples/bluetooth/broadcaster_multiple/src/broadcaster_multiple.c:52]:
```suggestion
 * To ensure that we need to chain PDUs we therefore add manufacturer data
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 41]
```diff
@@ -116,7 +116,9 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
 	struct pdu_adv *pdu_prev;
 	uint8_t ad_len_overflow;
 	uint8_t ad_len_chain;
+	uint8_t chain_err = 0U;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:119]: Move this declaration as close to its locality of reference.

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 42]
```diff
@@ -116,7 +116,9 @@ uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref,
...
 	struct pdu_adv *pdu;
+	uint8_t ad_len = 0U, ad_len_prev = 0U;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:121]: May be these too can move closer to locality of reference? (to reduce program stack depth)

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 42 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:121]: only ad_len_prev can be moved

**Review by Thalley — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
