### PR TITLE
drivers: timer: nrf_grtc_timer: add last_count initialization

### LINKED ISSUE #89147: nRF54L: uptime does not reset across reboots
**Describe the bug**

On the nRF54L, resetting the application without removing power does not result in the internal counters starting again from 0.

**To Reproduce**

1. Update `zephyr/samples/hello_world` to:
```
#include <stdio.h>
#include <zephyr/kernel.h>

int main(void)
{
	while(1) {
		printf("Hello World! %s %6d\n", CONFIG_BOARD_TARGET, k_uptime_seconds());
		k_sleep(K_SECONDS(1));
	}
	return 0;
}
```
2. `west build -b nrf54l15dk/nrf54l15/cpuapp zephyr/samples/hello_world/`
3. `west flash`
4. Wait several seconds
5. `nrfutil device reset`
6. Observe the serial output

**Expected behavior**

Application should start counting from 0 on each reset.

**Impact**

Application thinks it's been running for much longer than it has been.
Absolute timestamps not constructed without reference to the current uptime will be broken.
i.e. `K_TIMEOUT_ABS_MS(5000)` will expire immediately upon reboot.

**Logs and console output**

Image

**Environment (please complete the following information):**

 - Zephyr v4.1 and main

**Additional context**

`k_uptime_seconds()` is not special in any way, it simply retrieves the system tick counter and does a division.
This implies that the system tick counter is not being reset across reboots.

The nRF54L series does not use the same system tick source as previous nRF SoCs, it uses the GRTC (`nrf_grtc_timer`).

### PR DESCRIPTION
**Pull request by adamkondraciuk**
The GRTC counter is not cleared at startup, therefore the `last_count` variable needs to be initialized accordingly. This change:
- Prevents overflow of the `sys_clock_announce()` int32_t parameter
- Ensures the correct uptime value, which should be reset during initialization
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/89147

### CODE REVIEW

**Review by nordic-krch — DISMISSED** [review]

File: drivers/timer/nrf_grtc_timer.c [hunk 1]
```diff
@@ -485,6 +485,7 @@ static int sys_clock_driver_init(void)
 	}
 #endif /* CONFIG_NRF_GRTC_START_SYSCOUNTER */
 
+	last_count = counter();
```
Comment (nika-nordic) [inline drivers/timer/nrf_grtc_timer.c]: shouldn't be wrapped in Kconfig-equivalent of `NRFX_GRTC_CLEAR_AT_INIT` ? or this feature is not configurable via Kconfig ?

**Review by nika-nordic — DISMISSED** [review]

File: drivers/timer/nrf_grtc_timer.c (hunk 1 above)
Comment (adamkondraciuk) [reply drivers/timer/nrf_grtc_timer.c]: There is another PR for that: https://github.com/zephyrproject-rtos/zephyr/pull/89664

**Review by kl-cruz — DISMISSED** [review]

**Review by nordic-krch — DISMISSED** [review]

File: drivers/timer/nrf_grtc_timer.c [hunk 2]
```diff
@@ -485,6 +491,8 @@ static int sys_clock_driver_init(void)
 	}
 #endif /* CONFIG_NRF_GRTC_START_SYSCOUNTER */
 
+	last_count = sys_clock_tick_get() * CYC_PER_TICK;
+	grtc_start_value = last_count;
```
Comment (masz-nordic) [inline drivers/timer/nrf_grtc_timer.c]: Is there a potential race between here and `sys_clock_timeout_handler` for `last_count`?
If that is not the case and `sys_clock_announce` is not expected to be called at this point, could this code be simplified and skip `sys_clock_tick_get` logic to just call `counter()`?

Comment (anangl) [reply drivers/timer/nrf_grtc_timer.c]: It's definitely better to use `counter()` here to initialize both these variables than to involve `sys_clock_tick_get()` (calling this function from the system timer driver doesn't actually seem to be appropriate).

**Review by nordic-krch — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by nika-nordic — APPROVED** [review]

**Review by kl-cruz — APPROVED** [review]
