### PR TITLE
Test: dac : fixing ci failure for rd_rw612_bga and frdm_mcx947

### LINKED ISSUE #70814: tests: frdm_mcxn947/mcxn947/cpu0: some applications build failure
**Describe the bug**

below application build failure

<html>
<body>

|CASE_NAME | ZEPHYR_VERSION | RESULT | PLATFORM | TEST_PATH
-- | -- | -- | -- | --
input.api.thread | v3.6.0-3120-g0291c551a201 | Build failure | frdm_mcxn947/mcxn947/cpu0 | tests/subsys/input/api
input.api.synchronous | v3.6.0-3120-g0291c551a201 | Build failure | frdm_mcxn947/mcxn947/cpu0 | tests/subsys/input/api
drivers.dac.api | v3.6.0-3120-g0291c551a201 | Build failure | frdm_mcxn947/mcxn947/cpu0 | tests/drivers/dac/dac_api

</body>
</html>

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 frdm_mcxn947/mcxn947/cpu0
 - What have you tried to diagnose or workaround this issue?

 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 this build failure is there since this board check-in

**To Reproduce**

west build -b frdm_mcxn947/mcxn947/cpu0 samples/subsys/input/input_dump

**Expected behavior**
Build Pass

**Impact**
input fucntion

**Logs and console output**

```
zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_mcux_lpuart.c.obj.d -o zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_mcux_lpuart.c.obj -c /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/serial/uart_mcux_lpuart.c
In file included from /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_macro.h:34,
                 from /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/irq_multilevel.h:15,
                 from /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/devicetree.h:20,
                 from /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/device.h:12,
                 from /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/serial/uart_mcux_lpuart.c:11:
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/device.h:91:41: error: '__device_dts_ord_DT_N_S_soc_S_peripheral_50000000_S_flexcomm_b4000_S_lpuart_b4000_P_dmas_NAME_rx_PH_ORD' undeclared here (not in a function); did you mean 'DT_N_S_soc_S_peripheral_50000000_S_flexcomm_93000_S_lpspi_93000_P_dmas_NAME_rx_PH'?
   91 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id)
      |                                         ^~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_internal.h:72:26: note: in definition of macro '__DEBRACKET'
   72 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_internal.h:64:9: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   64 |         __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |         ^~~~~~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_internal.h:59:9: note: in expansion of macro '__COND_CODE'
   59 |         __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_macro.h:180:9: note: in expansion of macro 'Z_COND_CODE_1'
  180 |         Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/devicetree.h:4263:9: note: in expansion of macro 'COND_CODE_1'
 4263 |         COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT),   \
      |         ^~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/toolchain/common.h:138:23: note: in expansion of macro '_DO_CONCAT'
  138 | #define _CONCAT(x, y) _DO_CONCAT(x, y)
      |                       ^~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/device.h:91:33: note: in expansion of macro '_CONCAT'
   91 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id)
      |                                 ^~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/device.h:218:37: note: in expansion of macro 'DEVICE_NAME_GET'
  218 | #define DEVICE_DT_NAME_GET(node_id) DEVICE_NAME_GET(Z_DEVICE_DT_DEV_ID(node_id))
      |                                     ^~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/device.h:235:34: note: in expansion of macro 'DEVICE_DT_NAME_GET'
  235 | #define DEVICE_DT_GET(node_id) (&DEVICE_DT_NAME_GET(node_id))
      |                                  ^~~~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/serial/uart_mcux_lpuart.c:1193:25: note: in expansion of macro 'DEVICE_DT_GET'
 1193 |                         DEVICE_DT_GET(DT_INST_DMAS_CTLR_BY_NAME(id, rx)),                      \
      |                         ^~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/serial/uart_mcux_lpuart.c:1244:9: note: in expansion of macro 'RX_DMA_CONFIG'
 1244 |         RX_DMA_CONFIG(n)        \
      |         ^~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/serial/uart_mcux_lpuart.c:1255:9: note: in expansion of macro 'LPUART_MCUX_DECLARE_CFG'
 1255 |         LPUART_MCUX_DECLARE_CFG(n)                                      \
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/frdm_mcxn947_mcxn947_cpu0/tests/drivers/uart/uart_async_api/drivers.uart.async_api.lpuart/zephyr/include/generated/devicetree_generated.h:11512:53: note: in expansion of macro 'LPUART_MCUX_INIT'
11512 | #define DT_FOREACH_OKAY_INST_nxp_kinetis_lpuart(fn) fn(0)
      |                                                     ^~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_internal.h:105:36: note: in expansion of macro 'DT_FOREACH_OKAY_INST_nxp_kinetis_lpuart'
  105 | #define UTIL_PRIMITIVE_CAT(a, ...) a##__VA_ARGS__
      |                                    ^
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/serial/uart_mcux_lpuart.c:1266:1: note: in expansion of macro 'DT_INST_FOREACH_STATUS_OKAY'
 1266 | DT_INST_FOREACH_STATUS_OKAY(LPUART_MCUX_INIT)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/frdm_mcxn947_mcxn947_cpu0/tests/drivers/uart/uart_async_api/drivers.uart.async_api.lpuart/zephyr/include/generated/devicetree_generated.h:7907:42: error: 'DT_N_S_soc_S_peripheral_50000000_S_flexcomm_b4000_S_lpuart_b4000_P_dmas_NAME_rx_VAL_mux' undeclared here (not in a function); did you mean 'DT_N_S_soc_S_peripheral_50000000_S_flexcomm_93000_S_lpspi_93000_P_dmas_NAME_rx_VAL_mux'?
 7907 | #define DT_N_INST_0_nxp_kinetis_lpuart   DT_N_S_soc_S_peripheral_50000000_S_flexcomm_b4000_S_lpuart_b4000
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_internal.h:72:26: note: in definition of macro '__DEBRACKET'
   72 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_internal.h:64:9: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   64 |         __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |         ^~~~~~~~~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_internal.h:59:9: note: in expansion of macro '__COND_CODE'
   59 |         __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/sys/util_macro.h:180:9: note: in expansion of macro 'Z_COND_CODE_1'
  180 |         Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/devicetree.h:4263:9: note: in expansion of macro 'COND_CODE_1'
 4263 |         COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(DT_DRV_COMPAT),   \
      |         ^~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/devicetree.h:1457:9: note: in expansion of macro 'DT_CAT7'
 1457 |         DT_CAT7(node_id, _P_, pha, _NAME_, name, _VAL_, cell)
      |         ^~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/devicetree/dma.h:221:9: note
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.6.0-1834-gbec115fbcfe7

### PR DESCRIPTION
**Pull request by hakehuang**
add dts and dac setting for tests/driver/dac/dac_api, tested on both platform

Fixes #70814

### CODE REVIEW

**Comment by hakehuang** [comment]
@wmrsouza  ESP32S2_DEVKITC  has the same issue

**Comment by hakehuang** [comment]
the build failure is due to BOARD_ESP32S2_DEVKITC has the same issue ping the owner already.

**Comment by wmrsouza** [comment]
> add dts and dac setting for tests/driver/dac/dac_api

PR #73015 submitted

**Review by decsny — DISMISSED** [review]

File: tests/drivers/dac/dac_api/src/test_dac.c [hunk 1]
```diff
@@ -87,6 +87,18 @@
 #define DAC_RESOLUTION		12
 #define DAC_CHANNEL_ID		0
 
+#elif defined(CONFIG_BOARD_RD_RW612_BGA)
+
+#define DAC_DEVICE_NODE		DT_NODELABEL(dac0)
+#define DAC_RESOLUTION		10
+#define DAC_CHANNEL_ID		0
+
+#elif defined(CONFIG_BOARD_FRDM_MCXN947)
```
Comment (martinjaeger) [inline tests/drivers/dac/dac_api/src/test_dac.c:96]: Please add this to the already existing group with same configuration above.

File: tests/drivers/dac/dac_api/boards/frdm_mcxn947_mcxn947_cpu0.overlay
Comment (martinjaeger) [inline tests/drivers/dac/dac_api/boards/frdm_mcxn947_mcxn947_cpu0.overlay:1]: As far as I can see, the `dac0` is already enabled in the [board `.dts` file](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/nxp/frdm_mcxn947/frdm_mcxn947_mcxn947_cpu0.dts), so this file should not be required:

File: tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay
Comment (martinjaeger) [inline tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay:1]: Why is this particular configuration needed? If we can use the default configuration, this file is not necessary.

File: tests/drivers/dac/dac_api/src/test_dac.c [hunk 2]
```diff
@@ -87,6 +87,18 @@
 #define DAC_RESOLUTION		12
 #define DAC_CHANNEL_ID		0
 
+#elif defined(CONFIG_BOARD_RD_RW612_BGA)
+
+#define DAC_DEVICE_NODE		DT_NODELABEL(dac0)
+#define DAC_RESOLUTION		10
```
Comment (martinjaeger) [inline tests/drivers/dac/dac_api/src/test_dac.c:93]: Can you please point me to the datasheet of this SOC? I couldn't find it.

Does its DAC really only have 10 bits? If it has 12 bits as well, we could move it to the existing group above as well.

**Review by martinjaeger — CHANGES_REQUESTED** [review]

File: tests/drivers/dac/dac_api/src/test_dac.c (hunk 2 above)
Comment (decsny) [reply tests/drivers/dac/dac_api/src/test_dac.c:93]: The data from this DAC is indeed a 10 bit resolution.

This SOC does not have a reference manual or datasheet.

File: tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay
Comment (hakehuang) [reply tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay:1]: > Why is this particular configuration needed? If we can use the default configuration, this file is not necessary.

it does not hurt either, as the dac is not a must for every application. IMHO, keep the dependency explicitely would be easy for user to know this.

File: tests/drivers/dac/dac_api/boards/frdm_mcxn947_mcxn947_cpu0.overlay
Comment (hakehuang) [reply tests/drivers/dac/dac_api/boards/frdm_mcxn947_mcxn947_cpu0.overlay:1]: it does not hurt either, as the dac is not a must for every application. IMHO, keep the dependency explicitely would be easy for user to know this.

File: tests/drivers/dac/dac_api/src/test_dac.c (hunk 1 above)
Comment (hakehuang) [reply tests/drivers/dac/dac_api/src/test_dac.c]: updated.

File: tests/drivers/dac/dac_api/src/test_dac.c [hunk 3]
```diff
@@ -48,7 +48,8 @@
 	defined(CONFIG_BOARD_SEEEDUINO_XIAO) || \
 	defined(CONFIG_BOARD_ARDUINO_MKRZERO) || \
 	defined(CONFIG_BOARD_ARDUINO_ZERO) || \
-	defined(CONFIG_BOARD_LPCXPRESSO55S36)
+	defined(CONFIG_BOARD_LPCXPRESSO55S36) || \
+	defined(CONFIG_BOARD_FRDM_MCXN947)
```
Comment (martinjaeger) [inline tests/drivers/dac/dac_api/src/test_dac.c:52]: Nits: Can you please add this define next to the other `FRDM` boards so that it's easier to spot?

File: tests/drivers/dac/dac_api/boards/frdm_mcxn947_mcxn947_cpu0.overlay
Comment (martinjaeger) [reply tests/drivers/dac/dac_api/boards/frdm_mcxn947_mcxn947_cpu0.overlay:1]: Having the same thing defined in multiple places always increases maintenance burden.

This test is only run for a board when `dac` is listed as supported in the board `.yaml` file, so it can be expected that the DAC node is enabled in Devicetree. An application would enable the DAC via Kconfig, not Devicetree.

File: tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay
Comment (martinjaeger) [reply tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay:1]: See above.

**Review by martinjaeger — CHANGES_REQUESTED** [review]

File: tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay [hunk 4]
```diff
@@ -0,0 +1,9 @@
+/*
+ * Copyright 2022 Espressif (Shanghai)
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+&dac {
+	status = "okay";
```
Comment (martinjaeger) [inline tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay:8]: As mentioned in the other PR, I prefer enabling the DAC in the board `.dts` file.

**Review by martinjaeger — CHANGES_REQUESTED** [review]

File: tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay (hunk 4 above)
Comment (sylvioalves) [reply tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay:8]: Then code size would increase when dac isn't enabled in .dts:  

```c
config ADC_ESP32
	bool "ESP32 ADC driver"
	default y
	depends on DT_HAS_ESPRESSIF_ESP32_ADC_ENABLED
	help
	  Enable the driver implementation for the ESP32 ADC
```

Comment (martinjaeger) [reply tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay:8]: I guess you meant the DAC and not the ADC, but it's the same for both: The above snippet enables the specific DAC driver of that chip **only if** the DAC in general is enabled as well (by setting `CONFIG_DAC=y`). And in that case you do want to use the DAC and it's fine that the code size increases.

See here:

https://github.com/zephyrproject-rtos/zephyr/blob/de526632ae7a58eb323e68b7f44c76bd6a79c627/drivers/CMakeLists.txt#L30

https://github.com/zephyrproject-rtos/zephyr/blob/de526632ae7a58eb323e68b7f44c76bd6a79c627/drivers/dac/Kconfig#L14

https://github.com/zephyrproject-rtos/zephyr/blob/de526632ae7a58eb323e68b7f44c76bd6a79c627/drivers/dac/Kconfig#L54

Comment (sylvioalves) [reply tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay:8]: Sorry, DAC. Indeed, you are correct. Well, lots of overlay files could be removed after all, not only in this particular sample code.

Comment (martinjaeger) [reply tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay:8]: Possibly yes. But let's at least make sure that no further redundant ones are added :)

File: tests/drivers/dac/dac_api/boards/frdm_mcxn947_mcxn947_cpu0.overlay
Comment (hakehuang) [reply tests/drivers/dac/dac_api/boards/frdm_mcxn947_mcxn947_cpu0.overlay:1]: ok.

File: tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay
Comment (hakehuang) [reply tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay:1]: ok

File: tests/drivers/dac/dac_api/src/test_dac.c (hunk 3 above)
Comment (hakehuang) [reply tests/drivers/dac/dac_api/src/test_dac.c:52]: ok

File: tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay (hunk 4 above)
Comment (sylvioalves) [reply tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay:8]: I agree.

File: tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay
Comment (martinjaeger) [reply tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay:1]: Why do we need these setting and cannot use the defaults?

Comment (hakehuang) [reply tests/drivers/dac/dac_api/boards/rd_rw612_bga.overlay:1]: good question, I find it is ok with default, let me update

File: tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay (hunk 4 above)
Comment (sylvioalves) [reply tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay:8]: @hakehuang Would you remove this esp32s2_devkitc overlay file and enable the dac into `esp32s2_devkitc.dts` instead?

Comment (hakehuang) [reply tests/drivers/dac/dac_api/boards/esp32s2_devkitc.overlay:8]: ok

**Comment by marekmatej** [comment]
I think we don't need another `ESP32-S2` board under tests. The `saola` and `devkitc` boards are identical from the DAC standpoint.

**Comment by hakehuang** [comment]
> I think we don't need another `ESP32-S2` board under tests. The `saola` and `devkitc` boards are identical from the DAC standpoint.

the CI will triggerred by board.yaml settings. which is good to autmaticaly extend test coverage

**Review by martinjaeger — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by sylvioalves — APPROVED** [review]
@hakehuang, thanks!

**Review by dleach02 — APPROVED** [review]
