### PR TITLE
task_wdt: Fix the way the kernel timer is used

### LINKED ISSUE #36357: tests: samples: watchdog: sample.subsys.task_wdt fails on nrf platforms
**Describe the bug**
The sample from `zephyr/samples/subsys/task_wdt` fails on nrf9160 and nrf52840 (passes on nrf5340)

**To Reproduce**
1. have nrf52840 connected
2. run `./scripts/twister -T samples/subsys/task_wdt/ -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0 -v -v`
3. See error

**Expected behavior**
The test passes

**Impact**
Not clear

**Logs and console output**
The device is printing the below msg in a loop and terminates with a timeout
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v2.6.0-368-g3e492665c012  ***
DEBUG   - DEVICE: Task watchdog sample application.
DEBUG   - DEVICE: Main thread still alive...
DEBUG   - DEVICE: Control thread started.
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain zephyr-sdk 0.12.2
 - Commit SHA or Version used: zephyr-v2.6.0-368-g3e492665c012

### PR DESCRIPTION
**Pull request by anangl**
Do not use periodic executions of the timer handler, as in certain
circumstances (the fallback hardware watchdog used, one or more
task_wdt channel activated but none of them being ever fed) this
would lead to no callback/reset being executed for any channel.
Instead, schedule the next timeout from the timer handler function
when the function is executed for the dummy background channel or
for a channel that was deleted.

This fixes #36357.

Use the actual minimum timeout used by the sample for task watchdog
channels (100 ms) as the configuration value for the fallback hardware
watchdog, to avoid unnecessary executions of the timer handler.

Add missing indentation in the documentation of the sample so that
the console output is rendered correctly.

### CODE REVIEW

File: subsys/task_wdt/task_wdt.c [hunk 1]
```diff
@@ -199,7 +199,14 @@ int task_wdt_feed(int channel_id)
...
 	k_timer_start(&timer, K_TIMEOUT_ABS_TICKS(next_timeout),
-		K_TIMEOUT_ABS_TICKS(next_timeout));
+		/* If the fallback hardware watchdog is used, also periodic
+		 * executions of the timer handler need to be scheduled
+		 * so that the hardware watchdog gets a chance to be fed
+		 * when its timeout turns out to be shorter than any active
+		 * channel timeout.
+		 */
+		IS_ENABLED(CONFIG_TASK_WDT_HW_FALLBACK) ?
+			K_MSEC(CONFIG_TASK_WDT_MIN_TIMEOUT) : K_NO_WAIT);
```
Comment (pdgendt) [inline subsys/task_wdt/task_wdt.c:209]: Isn't it an issue that `next_channel_id` differs from `TASK_WDT_BACKGROUND_CHANNEL` in the repeated calls to the timer's expiry function?

Comment (martinjaeger) [reply subsys/task_wdt/task_wdt.c:209]: I think I agree with @pdgendt, it's probably not good to have a miss-match between channel ID and timeout. If `CONFIG_TASK_WDT_MIN_TIMEOUT` was configured bad (as it actually was in the sample) the `TASK_WDT_BACKGROUND_CHANNEL` should automatically become the `next_channel_id`.

Thinking twice, we should not need any periodic execution of the timer at all, so we could just always set the `period` to `K_NO_WAIT` or to `K_FOREVER` (which leads to the same result, but is more intuitive, in my opinion).

**Review by martinjaeger — COMMENTED** [review]
IIRC I set the `CONFIG_TASK_WDT_MIN_TIMEOUT` to a "bad" value on purpose so that this feature is tested via the sample. But I should have left a comment to explain it.

File: subsys/task_wdt/task_wdt.c (hunk 1 above)
Comment (anangl) [reply subsys/task_wdt/task_wdt.c]: > Thinking twice, we should not need any periodic execution of the timer at all, so we could just always set the `period` to `K_NO_WAIT` or to `K_FOREVER` (which leads to the same result, but is more intuitive, in my opinion).

This was also my first thought that periodic executions should not be used at all. But I saw that the hardware watchdog handling needed those, so I tried to align to the existing implementation. After looking at this again, I found that such approach is problematic - if you just comment out both calls to `task_wdt_feed()` in the sample, there will be no reset at all. Therefore, I decided to rework this a bit deeper.

I agree that `K_FOREVER` instead of  `K_NO_WAIT` is more intuitive when supplied as the 'period' parameter. I just saw that `K_NO_WAIT` was mainly used for that purpose in Zephyr. But I guess that's just because it simple replaced the value of 0 that had to be used earlier in such calls.

**Comment by anangl** [comment]
> IIRC I set the `CONFIG_TASK_WDT_MIN_TIMEOUT` to a "bad" value on purpose so that this feature is tested via the sample. But I should have left a comment to explain it.

This feature is anyway tested in this sample, as the control thread is started after one second. Before that time, there is only one channel enabled with timeout set to 1100 ms and the background channel timeout is 100 ms.
I think it is better to not provide such "bad" value in the sample. Users might just copy such configuration into their own applications without being aware that it is suboptimal.

**Review by martinjaeger — APPROVED** [review]
Thanks for the update. Makes sense and I also agree regarding the fix of the bad value in the sample.

**Review by pdgendt — APPROVED** [review]
LGTM
