### PR TITLE
fix the bug of mpu stack guard in kconfig

### LINKED ISSUE #14693: ARC: need test coverage for MPU stack guards
On nsim_em and nsim_sem we have configured CONFIG_ARC_STACK_CHECKING, with no MPU guards. A sanitycheck run will not reveal issues with MPU guards on ARC, such as #14692

At minimum, we need a variant build target for nsim_em which enabled MPU guards and disables ARC stack checking.

### PR DESCRIPTION
**Pull request by vonhust**
* HW_STACK_PROTECTION can be done by STACK_
  CHECKING or MPU stack guard. ARC STACK_CHECKING is prioritized
  over MPU-based stack guard
* fix compile error in mpu drivers
* add new configurations in nsim_em to cover mpu stack guard
   * the original configurations are configured with stack checking
   * the new configurations are configured with mpu stack guard

Fixes #14693

### CODE REVIEW

File: arch/arc/Kconfig [hunk 1]
```diff
@@ -85,13 +85,35 @@ config ARC_FIRQ
 	  If FIRQ is disabled, the handle of interrupts with highest priority
 	  will be same with other interrupts.
 
-config	ARC_STACK_CHECKING
+config 	ARC_HAS_STACK_CHECKING
+	bool "ARC has STACK_CHECKING"
```
Comment (ulfalizer) [inline arch/arc/Kconfig]: Is this a fixed feature of the hardware, or something that it makes sense to enable/disable in the `menuconfig` interface?

If it's a fixed hardware feature, then the symbol should not have a prompt, because then you'll be able to change its value in `menuconfig`. If it's a feature that it makes sense to enable/disable, then the name probably shouldn't have "HAS" in it, because that makes it look like a hardware feature flag.

See [this section](https://docs.zephyrproject.org/latest/guides/kconfig/index.html#what-to-turn-into-kconfig-options) on the Kconfig best practices page.

File: arch/arc/Kconfig [hunk 2]
```diff
@@ -85,13 +85,35 @@ config ARC_FIRQ
...
+	default y
+	help
+	  ARC is configured with STACK_CHECKING which is a mechanism for
+	  checking stack accesses and raising an exception when a stack
+	  overflow or underflow is detected.
+
+config  ARC_STACK_CHECKING
+	bool
+	# Omit prompt to signify "hidden" option
```
Comment (ulfalizer) [inline arch/arc/Kconfig]: Maybe these comments could be skipped. They get copied around everywhere. :)

Comment (vonhust) [reply arch/arc/Kconfig]: already fixed

File: arch/arc/Kconfig (hunk 1 above)
Comment (vonhust) [reply arch/arc/Kconfig]: In fact, it's a fixed feature of the hardware.   But because arc is highly configurable,   to avoid creating many different soc in nsim (most options are the same),  it's better to make it configurable from def_config, so we can use different def_config to simulate different soc with one nsim soc configuration. 

What's more, although it's a fixed feature, user can choose whether to use it or not.

File: arch/arc/core/fault.c [hunk 3]
```diff
@@ -29,6 +31,99 @@ static const struct z_exc_handle exceptions[] = {
...
+ *   and only if a Stacking error has been reported.
+ *
+ * If stack corruption is detected, the function returns the lowest
+ * allowed address where the Stack Pointer can safely point to, to
+ * prevent from errors when un-stacking the corrupted stack frame
+ * upon exception return.
+ *
+ * @param fault_addr memory address on which memory access violation
+ *                   has been reported.
+ * @param psp        current address the PSP points to
```
Comment (ruuddw) [inline arch/arc/core/fault.c]: psp -> sp

File: arch/arc/Kconfig [hunk 4]
```diff
@@ -85,13 +85,34 @@ config ARC_FIRQ
...
+	  ARC is configured with STACK_CHECKING which is a mechanism for
+	  checking stack accesses and raising an exception when a stack
+	  overflow or underflow is detected.
+
+config  ARC_STACK_CHECKING
+	bool
+	help
+	  Use ARC STACK_CHECKING to do stack protection
+
+config	ARC_STACK_PROTECTION
```
Comment (ruuddw) [inline arch/arc/Kconfig]: Is this additional ARC_STACK_PROTECTION option required? Can't the common HW_STACK_PROTECTION be used to enable either the ARC_STACK_CHECKING or MPU_STACK_GUARD?

File: arch/arc/core/fault.c [hunk 5]
```diff
@@ -29,6 +31,99 @@ static const struct z_exc_handle exceptions[] = {
...
+ * is supported). Additionally the current thread stack pointer
+ * must be pointing inside or below the guard area.
+ *
+ * Thread stack corruption for user threads in user mode is reported,
+ * if the current stack pointer is pointing below the start of the current
+ * thread's stack.
+ *
+ * Notes:
+ * - we assume a fully descending stack,
+ * - we assume a stacking error has occurred,
```
Comment (ruuddw) [inline arch/arc/core/fault.c]: why assume a stack error occurred? isn't this function testing that, instead of assuming?

File: arch/arc/core/fault.c [hunk 6]
```diff
@@ -29,6 +31,99 @@ static const struct z_exc_handle exceptions[] = {
...
+ * - the function shall be called when handling MemManage and Bus fault,
```
Comment (ruuddw) [inline arch/arc/core/fault.c]: these are called differently on ARC...

File: arch/arc/core/fault.c [hunk 7]
```diff
@@ -29,6 +31,99 @@ static const struct z_exc_handle exceptions[] = {
...
+ *   and only if a Stacking error has been reported.
+ *
+ * If stack corruption is detected, the function returns the lowest
+ * allowed address where the Stack Pointer can safely point to, to
```
Comment (ruuddw) [inline arch/arc/core/fault.c]: This return value doesn't seem to be used on ARC, is the corrupt stack pointer 'repaired' elsewhere? (or simply not used after the stack exception, since exception handling uses a different stack).

File: arch/arc/Kconfig (hunk 1 above)
Comment (ulfalizer) [reply arch/arc/Kconfig]: `Kconfig.defconfig` files might be another option. Might be able to have "true" `_HAS_` symbols that way too, that hide e.g. `ARC_STACK_CHECKING` in the menuconfig when the feature isn't available.

Maybe the help text could mention that the hw needs to have the feature available otherwise.

Anyway, won't block over it. Don't know much about ARC (except it has ties to Starfox on SNES, which is cool :).

Comment (ulfalizer) [reply arch/arc/Kconfig]: If the symbol enables use of the HW feature in the code (and assumes it's there), I'd drop the `_HAS_` from the name though.

File: arch/arc/Kconfig (hunk 4 above)
Comment (vonhust) [reply arch/arc/Kconfig]: It's a temp value,  and provides some kind of abstraction.  If directly use HW_STACK_PROTECTION, it means when HW_STACK_PROTECTION is selected, it's needed to select ARC_STACK_CHECKING or MPU_STACK_GUARD in the entry of HW_STACK_PROTECTION, and the coressponing logic may be a little complex.

File: arch/arc/core/fault.c (hunk 5 above)
Comment (vonhust) [reply arch/arc/core/fault.c]: Because non-sp based memory access to stack are may also rasie mpu privilege violation, this is not a stack error, but may be caused by some codes on purpose or malicious code.

File: arch/arc/core/fault.c (hunk 3 above)
Comment (vonhust) [reply arch/arc/core/fault.c]: fixed

File: arch/arc/core/fault.c (hunk 6 above)
Comment (vonhust) [reply arch/arc/core/fault.c]: fixed

File: arch/arc/core/fault.c (hunk 7 above)
Comment (vonhust) [reply arch/arc/core/fault.c]: returning the lowest allowed stack frame pointer sometimes is useful when it's required to do some stack frame analysis,

File: arch/arc/Kconfig (hunk 4 above)
Comment (ruuddw) [reply arch/arc/Kconfig]: If it is temp, it could be an internal, hidden config?

**Review by ruuddw — APPROVED** [review]
ok for me. Note some overlap/conflict with #14823 (saved_value -> arc_exc_saved_sp). I believe with this PR, #14823 isn't required.

**Comment by vonhust** [comment]
ping....

File: arch/arc/core/fatal.c [hunk 8]
```diff
@@ -43,7 +43,7 @@ void z_NanoFatalErrorHandler(unsigned int reason, const NANO_ESF *pEsf)
 		break;
 
 #if defined(CONFIG_STACK_CANARIES) || defined(CONFIG_ARC_STACK_CHECKING) \
-	|| defined(CONFIG_STACK_SENTINEL)
+	|| defined(CONFIG_STACK_SENTINEL) || defined(CONFIG_MPU_STACK_GUARD)
```
Comment (ioannisg) [inline arch/arc/core/fatal.c]: In ARM we have, here, the top-level Kconfig symbol: CONFIG_HW_STACK_PROTECTION.

File: arch/arc/core/fault.c (hunk 5 above)
Comment (ioannisg) [reply arch/arc/core/fault.c]: Yeah, we seem to have the same issue in ARM :)

**Review by ioannisg — APPROVED** [review]
Looks OK to me - I left a comment about an #ifdef sentence

File: arch/arc/Kconfig (hunk 4 above)
Comment (andrewboie) [reply arch/arc/Kconfig]: It is hidden, there is no prompt

**Review by tyrantlizard77 — APPROVED** [review]
