### PR TITLE
stm32wb has no PWR clock to enable

### LINKED ISSUE #26766: Build failure on nucleo_wb55rg for tests/kernel/profiling/profiling_api/kernel.common.profiling
The following fails (shown in the daily overall build):

```./scripts/sanitycheck -p nucleo_wb55rg -s tests/kernel/profiling/profiling_api/kernel.common.profiling```

### PR DESCRIPTION
**Pull request by FRASTM**
The stm32wb soc does not have any PWR clock for its power IP block when initializing the module.

This fixes a compilation error when CONFIG_SYS_POWER_MANAGEMENT=y
because stm332wb  has no LL_APB1_GRP1_PERIPH_PWR.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/26766

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Review by erwango — APPROVED** [review]

File: soc/arm/st_stm32/stm32wb/power.c [hunk 1]
```diff
@@ -117,8 +117,7 @@ static int stm32_power_init(struct device *dev)
 
 	ret = irq_lock();
 
-	/* enable Power clock */
-	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);
+	/* no specific Power clock to enable */
```
Comment (pabigot) [inline soc/arm/st_stm32/stm32wb/power.c:120]: Remove the unnecessary IRQ lock:
```
static int stm32_power_init(struct device *dev)
{
        ARG_UNUSED(dev);

        /* no specific Power clock to enable */
        return 0;
}

**Review by pabigot — CHANGES_REQUESTED** [review]

File: soc/arm/st_stm32/stm32wb/power.c (hunk 1 above)
Comment (pabigot) [reply soc/arm/st_stm32/stm32wb/power.c:120]: Actually, remove the whole `SYS_INIT`.

Comment (FRASTM) [reply soc/arm/st_stm32/stm32wb/power.c]: yes in the end, Removing the stm32_power_init and SYS_INIT

**Review by pabigot — APPROVED** [review]
