### PR TITLE
Bluetooth: Tests: Fix uninitialized value in eatt_notif test

### LINKED ISSUE #50520: Bluetooth: bsim eatt_notif test fails with assertion in some environments
The tests/bluetooth/bsim_bt/bsim_test_eatt_notif/test_scripts/eatt_notif.sh test is failing when run in both CentOS 7.5 and Debian 11 (note that it passes in the Ubuntu 20.04 based docker image used in Github actions). This is with the latest main branch (currently commit 55c4e06b35639d525d214cb3432740a489b7147f).

From running it under valgrind, it looks like the root cause is use of some uninitialized memory:
```
==4120961== Memcheck, a memory error detector
==4120961== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4120961== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==4120961== Command: ./bs_nrf52_bsim_tests_bluetooth_bsim_bt_bsim_test_eatt_notif_prj_conf -v=2 -s=eatt_notif -d=1 -testid=server
==4120961== 
d_00: @00:00:00.000000  *** Booting Zephyr OS build v3.2.0-rc2-178-g55c4e06b3563  ***
d_01: @00:00:00.000000  *** Booting Zephyr OS build v3.2.0-rc2-178-g55c4e06b3563  ***
d_00: @00:00:00.003368  Scanning successfully started
d_01: @00:00:00.002648  Bluetooth initialized
d_01: @00:00:00.002648  Advertising successfully started
d_00: @00:00:00.318530  Device found: ED:71:8F:C2:E4:6E (random) (RSSI -35)
d_00: @00:00:00.318530  Stopping scan
d_01: @00:00:00.426609  Connected to ED:3B:20:15:18:12 (random)
d_01: @00:00:00.426609  Connected to ED:3B:20:15:18:12 (random)
d_00: @00:00:00.426606  Connected to ED:71:8F:C2:E4:6E (random)
d_00: @00:00:00.426606  Connected to ED:71:8F:C2:E4:6E (random)
d_00: @00:00:01.337220  Waiting for sync
d_01: @00:00:01.397095  Discovering services and characteristics
==4120961== Thread 3:
==4120961== Conditional jump or move depends on uninitialised value(s)
==4120961==    at 0x80DE451: bt_att_chan_opt_valid (att.c:3895)
==4120961==    by 0x80E3410: gatt_req_send (gatt.c:2341)
==4120961==    by 0x80E7B08: gatt_find_type (gatt.c:3615)
==4120961==    by 0x80E9F0F: bt_gatt_discover (gatt.c:4307)
==4120961==    by 0x8088582: gatt_discover (server_test.c:119)
==4120961==    by 0x8088CA7: test_main (server_test.c:207)
==4120961==    by 0x809D821: bst_main (bstests_entry.c:218)
==4120961==    by 0x80874C5: _posix_zephyr_main (main.c:20)
==4120961==    by 0x81175B1: bg_thread_main (init.c:254)
==4120961==    by 0x808C918: z_thread_entry (thread_entry.c:36)
==4120961==    by 0x809AF19: posix_thread_starter (posix_core.c:305)
==4120961==    by 0x41840B3: start_thread (pthread_create.c:477)
==4120961== 
==4120961== Conditional jump or move depends on uninitialised value(s)
==4120961==    at 0x80DE482: bt_att_chan_opt_valid (att.c:3902)
==4120961==    by 0x80E3410: gatt_req_send (gatt.c:2341)
==4120961==    by 0x80E7B08: gatt_find_type (gatt.c:3615)
==4120961==    by 0x80E9F0F: bt_gatt_discover (gatt.c:4307)
==4120961==    by 0x8088582: gatt_discover (server_test.c:119)
==4120961==    by 0x8088CA7: test_main (server_test.c:207)
==4120961==    by 0x809D821: bst_main (bstests_entry.c:218)
==4120961==    by 0x80874C5: _posix_zephyr_main (main.c:20)
==4120961==    by 0x81175B1: bg_thread_main (init.c:254)
==4120961==    by 0x808C918: z_thread_entry (thread_entry.c:36)
==4120961==    by 0x809AF19: posix_thread_starter (posix_core.c:305)
==4120961==    by 0x41840B3: start_thread (pthread_create.c:477)
==4120961== 
==4120961== Conditional jump or move depends on uninitialised value(s)
==4120961==    at 0x80D1B30: att_chan_matches_chan_opt (att.c:281)
==4120961==    by 0x80D2154: get_first_req_matching_chan (att.c:332)
==4120961==    by 0x80D40E1: att_req_send_process (att.c:825)
==4120961==    by 0x80DD81D: bt_att_req_send (att.c:3751)
==4120961==    by 0x80E3624: gatt_req_send (gatt.c:2366)
==4120961==    by 0x80E7B08: gatt_find_type (gatt.c:3615)
==4120961==    by 0x80E9F0F: bt_gatt_discover (gatt.c:4307)
==4120961==    by 0x8088582: gatt_discover (server_test.c:119)
==4120961==    by 0x8088CA7: test_main (server_test.c:207)
==4120961==    by 0x809D821: bst_main (bstests_entry.c:218)
==4120961==    by 0x80874C5: _posix_zephyr_main (main.c:20)
==4120961==    by 0x81175B1: bg_thread_main (init.c:254)
==4120961== 
d_01: @00:00:01.397095  ASSERTION FAIL [chan_opt <= BT_ATT_CHAN_OPT_ENHANCED_ONLY] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/att.c:281
d_01: @00:00:01.397095  @ WEST_TOPDIR/zephyr/lib/os/assert.c:43
```
Note that the same valgrind errors are also present when the test is run in the test docker image, where the test case passes.

### PR DESCRIPTION
**Pull request by hermabe**
The chan_opt field was not set, and on some platforms it ended up with an invalid value. Explicitly set the field on all GATT parameter structs and make the discovery params static.

Fixes #50520

Signed-off-by: Herman Berget <herman.berget@nordicsemi.no>

### CODE REVIEW

**Comment by hermabe** [comment]
I think we should run all the bsim tests with sanitizers in CI to catch these kinds of errors.

**Comment by jori-nordic** [comment]
> I think we should run all the bsim tests with sanitizers in CI to catch these kinds of errors.

Might be easier to do when we have a common bsim runner

**Comment by hermabe** [comment]
> > I think we should run all the bsim tests with sanitizers in CI to catch these kinds of errors.
> 
> Might be easier to do when we have a common bsim runner

Yes. We should merge the pytest plugin. I am not sure when Twister V2 is going to be done.

**Review by jori-nordic — DISMISSED** [review]

File: tests/bluetooth/bsim_bt/bsim_test_eatt_notif/src/server_test.c [hunk 1]
```diff
@@ -105,7 +105,7 @@ static uint8_t discover_func(struct bt_conn *conn,
 
 static void gatt_discover(void)
 {
-	struct bt_gatt_discover_params discover_params;
+	static struct bt_gatt_discover_params discover_params;
```
Comment (stephanosio) [inline tests/bluetooth/bsim_bt/bsim_test_eatt_notif/src/server_test.c:108]: what is the rationale behind this change?

Comment (hermabe) [reply tests/bluetooth/bsim_bt/bsim_test_eatt_notif/src/server_test.c:108]: - It zeroes out the struct, preventing uninitialized fields
- GATT param structs need to be valid until the response is received

It is not strictly needed in this case because the fields are explicitly set and we wait for the response in the function so an auto-variable is fine.

Comment (stephanosio) [reply tests/bluetooth/bsim_bt/bsim_test_eatt_notif/src/server_test.c:108]: > It zeroes out the struct, preventing uninitialized fields

that should be done with `struct bt_gatt_discover_params discover_params = { 0 };`

> GATT param structs need to be valid until the response is received

So we have a dangling pointer?

Comment (hermabe) [reply tests/bluetooth/bsim_bt/bsim_test_eatt_notif/src/server_test.c:108]: > > GATT param structs need to be valid until the response is received
>
> So we have a dangling pointer?

The param struct is a parameter in the response callback, and it is used in the stack to figure out what the response callback is and call it. The param struct must therefore be valid until the response callback is called. If it is a stack allocated variable that goes out of scope before the response callback is called, yes we have a dangling pointer. In this case that won't happen because `gatt_discover()` waits for a flag that is set in the response callback.

Comment (hermabe) [reply tests/bluetooth/bsim_bt/bsim_test_eatt_notif/src/server_test.c:108]: So `static` can be removed in this case and it won't change anything, but in general GATT param structs should be static.

Comment (alwa-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_eatt_notif/src/server_test.c:108]: If it does not need to be static, I would prefer it to not be. As you point out, static lifetime is not needed in this case. 

The lifetime requirement as documented on `bt_gatt_discover` follows.

> @p params must remain valid until start of callback where iter `attr` is `NULL` or callback will return `BT_GATT_ITER_STOP`.

**Review by Thalley — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@hermabe can you handle or resolve https://github.com/zephyrproject-rtos/zephyr/pull/50574#discussion_r978473566?

**Review by Thalley — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@jhedberg can you review this?

**Review by alwa-nordic — APPROVED** [review]
Side-note: I think our API requires zero-initialized `_params` structs.

```c
struct bt_gatt_discover_params discover_params = {};
```

The `_params` structs are meant to be extensible in a backward-compatible manner. New fields are added in such a way that they keep the old behavior when default initialized.

RFC: We should consider an API change to `end_handle` in various params structs, so that value `0` is replaced with `BT_ATT_LAST_ATTRIBUTE_HANDLE`. Or define default initializers that set sane values.

**Comment by Thalley** [comment]
> Side-note: I think our API requires zero-initialized `_params` structs.

I don't think it's strictly required, but it is certainly a good idea. If the struct is extended with new fields, those new fields would not be initialized in cases like this.
