### PR TITLE
drivers/ieee802154: Fix settings channel/tx power in upipe driver

### LINKED ISSUE #8528: rpl-mesh-qemu sample, the net inface init failed.
[net/rpl] [DBG] dio_timer: (0x20000df0): Sending DIO later because IPv6 link local address is not found 

CONFIG_NET_APP_SETTINGS=y
samples: rpl-mesh-qemu
_net_app_ieee802154_setup() function would return -EINVAL in line 51.
upipe_set_channel() and upipe_set_txpower() function should just "return 0;"

### PR DESCRIPTION
**Pull request by tbursztyka**
Being stopped or not should not be a blocker on these settings (real
hardware can get these settings configured while not being in rx/tx
mode for instance).

Fixes #8528

Signed-off-by: Tomasz Bursztyka <tomasz.bursztyka@linux.intel.com>

### CODE REVIEW

**Review by pfalcon — DISMISSED** [review]
> Fix settings channel/tx power in upipe driver

Can we please have the real name of the driver used: "uart_pipe" ?

**Review by jukkar — APPROVED** [review]

**Comment by pfalcon** [comment]
> the driver is named ieee802154_upipe.c

Then why this patch applies changes to ieee802154_uart_pipe.c? Why do we have both ieee802154_upipe.c and ieee802154_uart_pipe.c (which is an implication one could make based on your words, and which shows the kind of confusion I ask to avoid).

**Comment by tbursztyka** [comment]
> Then why this patch applies changes to ieee802154_uart_pipe.c 

Function names are shortened to upipe, not the file indeed, my mistake

**Comment by pfalcon** [comment]
> Function names are shortened to upipe, not the file indeed, my mistake

So, by now you should see the issue, leaving up to you whether to fix it or not. (Yeah, it's minor, but we have hundreds of commits from dozen of people, if each adds a bit of confusion, big confusion ensues overall.)

File: drivers/ieee802154/ieee802154_uart_pipe.c [hunk 1]
```diff
@@ -193,11 +193,8 @@ static int upipe_cca(struct device *dev)
```
Comment (jukkar) [inline drivers/ieee802154/ieee802154_uart_pipe.c]: Small typo in commit subject, s/ipe/pipe/

**Review by jukkar — CHANGES_REQUESTED** [review]

**Comment by jukkar** [comment]
recheck

**Review by jukkar — APPROVED** [review]
