### PR TITLE
samples: usb: mass: do application configuration before usb starts

### LINKED ISSUE #26279: littlefs: Unable to erase external flash.
**Describe the bug**
USB mass storage class fails with `CONFIG_APP_WIPE_STORAGE=y`.

**To Reproduce**
1. Apply below patch
``` diff
diff --git a/samples/subsys/usb/mass/prj.conf b/samples/subsys/usb/mass/prj.conf
index 6428d785f5..47bbb06e3b 100644
--- a/samples/subsys/usb/mass/prj.conf
+++ b/samples/subsys/usb/mass/prj.conf
@@ -10,6 +10,7 @@ CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
 CONFIG_USB_MASS_STORAGE=y
 CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
 CONFIG_USB_MASS_STORAGE_LOG_LEVEL_ERR=y
+CONFIG_APP_WIPE_STORAGE=y
 
 # If the target's code needs to do file operations, enable target's
 # FAT FS code. (Without this only the host can access the fs contents)
```
2. Connect both usb cables to the board.
3. build and flash the sample
`west build -b nrf52840dk_nrf52840 & west flash`
```
*** Booting Zephyr OS build zephyr-v2.3.0-442-g150e18de6e18  ***
Area 4 at 0x0 on MX25R64 for 65536 bytes
Erasing flash area ... 0
[00:00:00.005,157] <inf> main: The device is put in USB mass storage mode.

[00:00:00.011,169] <inf> littlefs: LittleFS version 2.2, disk version 2.0
[00:00:00.011,230] <inf> littlefs: FS at MX25R64:0x0 is 16 0x1000-byte blocks with 512 cycle
[00:00:00.011,230] <inf> littlefs: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
[00:00:01.195,281] <err> littlefs: WEST_TOPDIR/modules/fs/littlefs/lfs.c:997: Corrupted dir pair at {0x0, 0x1}
[00:00:01.195,434] <wrn> littlefs: can't mount (LFS -84); formatting
[00:00:01.195,831] <err> os: ***** USAGE FAULT *****
[00:00:01.195,831] <err> os:   Illegal use of the EPSR
[00:00:01.195,831] <err> os: r0/a1:  0x20002f08  r1/a2:  0xe000ed00  r2/a3:  0x2000388c
[00:00:01.195,861] <err> os: r3/a4:  0x00000000 r12/ip:  0xffffffff r14/lr:  0x0000a175
[00:00:01.195,861] <err> os:  xpsr:  0x60000000
[00:00:01.195,861] <err> os: Faulting instruction address (r15/pc): 0x00000000
[00:00:01.195,861] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:01.195,861] <err> os: Current thread: 0x20000538 (unknown)
[00:00:02.232,543] <err> os: Halting system
```
**Expected behavior**
I expect the provided sample to work with possible options delivered.

**Impact**
Unable to erase flash storage prio to usage.

**Environment:**
 - OS: Linux Mint
 - Toolchain: zephyr-sdk v0.11.2
- 150e18de6e (recent master)

Additional context:
If I do not connect the cable to the USB port when the device is flashed I can see:
```
*** Booting Zephyr OS build zephyr-v2.3.0-442-g150e18de6e18  ***
Area 4 at 0x0 on MX25R64 for 65536 bytes
Erasing flash area ... 0
[00:00:00.005,065] <inf> main: The device is put in USB mass storage mode.

[00:00:00.011,047] <inf> littlefs: LittleFS version 2.2, disk version 2.0
[00:00:00.011,108] <inf> littlefs: FS at MX25R64:0x0 is 16 0x1000-byte blocks with 512 cycle
[00:00:00.011,108] <inf> littlefs: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
Mount /lfs: 0
/lfs: bsize = 16 ; frsize = 4096 ; blocks = 16 ; bfree = 14
/lfs opendir: 0
End of files
[00:00:01.199,981] <err> littlefs: WEST_TOPDIR/modules/fs/littlefs/lfs.c:997: Corrupted dir pair at {0x0, 0x1}
[00:00:01.200,012] <wrn> littlefs: can't mount (LFS -84); formatting
[00:00:01.363,647] <inf> littlefs: /lfs mounted
```

Then when I connect the cable:

```
[00:00:20.397,796] <err> os: ***** MPU FAULT *****
[00:00:20.397,827] <err> os:   Instruction Access Violation
[00:00:20.397,827] <err> os: r0/a1:  0x2000388c  r1/a2:  0x00000000  r2/a3:  0x00005c75
[00:00:20.397,827] <err> os: r3/a4:  0x00005cf1 r12/ip:  0x00004180 r14/lr:  0x61000000
[00:00:20.397,827] <err> os:  xpsr:  0x00001000
[00:00:20.397,857] <err> os: Faulting instruction address (r15/pc): 0x20000260
[00:00:20.397,857] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:20.397,857] <err> os: Current thread: 0x20000538 (unknown)
[00:00:21.036,193] <err> os: Halting system
```

### PR DESCRIPTION
**Pull request by pabigot**
USB access to the flash device is not synchronized with the
application, so if the application needs to create a new file system
USB may read configuration state that is incorrect.  Wait until the
the application is done with the flash before starting USB.

Fixes #26279

### CODE REVIEW

File: samples/subsys/usb/mass/src/main.c [hunk 1]
```diff
@@ -125,3 +115,18 @@ void main(void)
 	flash_area_close(pfa);
 #endif
 }
+
+void main(void)
+{
+	int ret;
+
+	setup_flash();
```
Comment (emob-nordic) [inline samples/subsys/usb/mass/src/main.c:123]:
``` diff
diff --git a/samples/subsys/usb/mass/src/main.c b/samples/subsys/usb/mass/src/main.c
index a021f2befa..320b56f33e 100644
--- a/samples/subsys/usb/mass/src/main.c
+++ b/samples/subsys/usb/mass/src/main.c
@@ -47,7 +47,6 @@ static struct fs_mount_t fs_mnt = {
 
 static void setup_flash(void)
 {
-#if CONFIG_DISK_ACCESS_FLASH
 	struct fs_mount_t *mp = &fs_mnt;
 	unsigned int id = (uintptr_t)mp->storage_dev;
 	int rc;
@@ -113,14 +112,14 @@ static void setup_flash(void)
 
 out:
 	flash_area_close(pfa);
-#endif
 }
 
 void main(void)
 {
 	int ret;
-
+#if IS_ENABLED(CONFIG_DISK_ACCESS_FLASH)
 	setup_flash();
+#endif
 
 	ret = usb_enable(NULL);
 	if (ret != 0) {
```

**Review by eobalski — CHANGES_REQUESTED** [review]
This would be better I believe.

File: samples/subsys/usb/mass/src/main.c (hunk 1 above)
Comment (pabigot) [reply samples/subsys/usb/mass/src/main.c:123]: You'd get an "unreferenced function" warning when `CONFIG_DISK_ACCESS_FLASH` is not selected.

Comment (emob-nordic) [reply samples/subsys/usb/mass/src/main.c:123]: Hm. You are right, I forgot it. So maybe it would be better to put definition of this function inside `CONFIG_DISK_ACCESS_FLASH` ifdefs as well, not only the function body? I just don't like the fact that at first sight You can see that `setup_flash()` is called even when You build with `overlay-ram-disk.conf`

Comment (pabigot) [reply samples/subsys/usb/mass/src/main.c:123]: What if I rename it `setup_disk()`?

Comment (emob-nordic) [reply samples/subsys/usb/mass/src/main.c]: Could be as well. I will just post alternative solution and let other speak.
``` diff
diff --git a/samples/subsys/usb/mass/src/main.c b/samples/subsys/usb/mass/src/main.c
index a021f2befa..76ba1dc42f 100644
--- a/samples/subsys/usb/mass/src/main.c
+++ b/samples/subsys/usb/mass/src/main.c
@@ -43,11 +43,8 @@ static struct fs_mount_t fs_mnt = {
 #else
 #error No recognized file system
 #endif  /* file system */
-#endif  /* CONFIG_DISK_ACCESS_FLASH */
-
 static void setup_flash(void)
 {
-#if CONFIG_DISK_ACCESS_FLASH
 	struct fs_mount_t *mp = &fs_mnt;
 	unsigned int id = (uintptr_t)mp->storage_dev;
 	int rc;
@@ -113,14 +110,16 @@ static void setup_flash(void)
 
 out:
 	flash_area_close(pfa);
-#endif
 }
+#endif  /* CONFIG_DISK_ACCESS_FLASH */
 
 void main(void)
 {
 	int ret;
 
+#if IS_ENABLED(CONFIG_DISK_ACCESS_FLASH)
 	setup_flash();
+#endif
 
 	ret = usb_enable(NULL);
 	if (ret != 0) {
```

**Review by jfischer-no — APPROVED** [review]

**Review by eobalski — APPROVED** [review]
