### PR TITLE
net: openthread: Allow parents to handle sleepy end devices correctly

### LINKED ISSUE #12942: openthread: sleepy end device not supported by zephyr router
When using a zephyr router, a sleepy end device (SED) can attach fine, but ping doesn't work.
We suspect that the frame pending bit isn't being supported correctly.

@rlubos

### PR DESCRIPTION
**Pull request by rlubos**
Depends on #15642, hence DNM.

This PR implements Frame Pending bit management API for the Zephyrs OpenThread radio shim layer. The implementation is built on top of the new `configure` API of the Zephyrs ieee801254 radio driver.

An implementation of the `configure` API for `ieee802154_nrf` driver is attached as well.

Resolves #12942.

### CODE REVIEW

File: subsys/net/lib/openthread/platform/radio.c [hunk 1]
```diff
@@ -328,7 +365,20 @@ otError otPlatRadioClearSrcMatchShortEntry(otInstance *aInstance,
...
-	ARG_UNUSED(aShortAddress);
+
+	u8_t short_address[SHORT_ADDRESS_SIZE];
+	struct ieee802154_config config = {
+		.ack_fpb.enabled = false,
+		.ack_fpb.addr = short_address,
+		.ack_fpb.extended = false
+	};
+
+	short_address_to_le(short_address, aShortAddress);
```
Comment (tbursztyka) [inline subsys/net/lib/openthread/platform/radio.c]: Just use sys_put_le16() no need of short_address_to_le()

File: drivers/ieee802154/ieee802154_nrf5.c [hunk 2]
```diff
@@ -388,6 +388,49 @@ static void nrf5_iface_init(struct net_if *iface)
 	ieee802154_init(iface);
 }
 
+int nrf5_configure(struct device *dev, enum ieee802154_config_type type,
+		   const struct ieee802154_config *config)
+{
+	ARG_UNUSED(dev);
+
+	int err = 0;
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_nrf5.c]: looks like you could avoid such local variable

**Comment by rlubos** [comment]
@tbursztyka Fixed

**Comment by rlubos** [comment]
Dependencies got merged, rebased.

**Review by tbursztyka — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
LGTM
