### PR TITLE
BSD socket sendmsg() parameters were not verified in usermode

### LINKED ISSUE #25702: BSD socket sendmsg() did not verify params in usermode
**Describe the bug**
The BSD socket `sendmsg()` call did not check parameters when running in user mode.

### PR DESCRIPTION
**Pull request by jukkar**
Fixes #25702

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

File: subsys/net/lib/sockets/sockets.c [hunk 1]
```diff
@@ -615,9 +615,82 @@ static inline ssize_t z_vrfy_zsock_sendmsg(int sock,
 					   const struct msghdr *msg,
 					   int flags)
 {
-	/* TODO: Create a copy of msg_buf and copy the data there */
+	struct msghdr msg_copy;
+	size_t i;
+	int ret;
+
+	memcpy(&msg_copy, msg, sizeof(msg_copy));
```
Comment (andrewboie) [inline subsys/net/lib/sockets/sockets.c:622]: msg is a pointer to user memory, need to use z_user_from_copy()

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]

File: subsys/net/lib/sockets/sockets.c (hunk 1 above)
Comment (jukkar) [reply subsys/net/lib/sockets/sockets.c:622]: Yep, and we need to validate the socket descriptor too.

**Comment by jukkar** [comment]
Updated according to comments.

**Review by ceolin — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]
