### PR TITLE
drivers: flash: stm32 ospi flash driver waits for full chip erase

### LINKED ISSUE #56442: flash_stm32_ospi chip erase returns immediately, but chip remains busy
**Describe the bug**

Flash memory chip erase (which occurs when erase size >= flash size) returns immediately. Immediately subsequent calls to operate on flash fail because flash is busy.

Should the chip erase call return immediately, or block until the operation is complete? If it should return immediately despite the ongoing operation, what is the recommended way to check the status of the device for when the operation has completed?

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? B-L4S5I-IOT01A
 - What have you tried to diagnose or workaround this issue? Waiting a significant amount of time between erase / format (see "additional context" below). Reducing partition size to trigger sector erase instead of chip erase.
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit? No

**To Reproduce**
Steps to reproduce the behavior: modified littlefs sample

1. Modify [littlefs sample main.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/fs/littlefs/src/main.c#L267-L273) to reference the [ospi partition](https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/b_l4s5i_iot01a/b_l4s5i_iot01a.dts#L267-L270) 'store/store_partition' 
2. Modify [littlefs sample prj.conf](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/fs/littlefs/prj.conf#L8) to enable storage wipe `CONFIG_APP_WIPE_STORAGE=y`
3. `west build samples/subsys/fs/littlefs --board b_l4s5i_iot01a`

**Expected behavior**
Erase returns when erase is complete, or some way to know when the erase operation is complete.

**Impact**
Minor inconvenience. Users will need to add special logic to account for timed chip erase. It's not obvious that this is required though.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.3.0 ***
Sample program to r/w files on littlefs
Area 5 at 0x0 on ospi-nor-flash@0 for 8388608 bytes
E: Erasing flash area ... 0
I: LittleFS version 2.5, disk version 2.0
I: FS at ospi-nor-flash@0:0x0 is 2048 0x1000-byte blocks with 512 cycle
I: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
E: WEST_TOPDIR/modules/fs/littlefs/lfs.c:1234: Corrupted dir pair at {0x0, 0x1}
W: can't mount (LFS -84); formatting
E: OSPI AutoPoll failed
E: Erase failed : flash busy
E: format failed (LFS -5)
E: fs mount error (-5)
FAIL: mount id 5 at /lfs: -5
```

**Environment (please complete the following information):**
 - OS: OS X
 - Toolchain (e.g Zephyr SDK, ...): SDK 0.15.2 
 - Commit SHA or Version used: Zephyr 3.3.0

**Additional context**

According to the [MX25R6435F datasheet](https://www.macronix.com/Lists/Datasheet/Attachments/8868/MX25R6435F,%20Wide%20Range,%2064Mb,%20v1.6.pdf), the timed chip erase can take as little as 45 seconds and as much as 240 seconds. It also sets a WIP (write in progress) bit in the status register which indicates if a write operation is on-going.

### PR DESCRIPTION
**Pull request by FRASTM**
Add a function to wait for the full (bulk) Nor-octoflah erase command. When erasing the full octo-flash, the drivers waits until the operation is ready and the external NOR mem becomes ready itself. The full (bulk) erase operation lasts for several seconds.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/56442

To erase the NOR octoFlash, call the flash_erase  with size = full flash size, for example : 
    flash_erase(flash_dev, 0, 0x4000000);

Note that erasing a 64MB NOR flash will take (blocking) about 45s.

### CODE REVIEW

**Review by gautierg-st — DISMISSED** [review]

File: drivers/flash/flash_stm32_ospi.c [hunk 1]
```diff
@@ -900,7 +953,7 @@ static int flash_stm32_ospi_erase(const struct device *dev, off_t addr,
 	}
 
 	/* Maximise erase size : means the complete chip */
-	if (size > dev_cfg->flash_size) {
+	if (size >= dev_cfg->flash_size) {
```
Comment (de-nordic) [inline drivers/flash/flash_stm32_ospi.c:956]: I think this is dangerous. If sb messes up math and ends up with giving some stupid size, you are going to erase entire flash regardless of given offset.
This should be tied to `addr == 0`, and I am not sure whether `size >= dev_cfg->flash_size` is correct here and should rather be `size == dev_cfg->flash_size`, as doing anything beyond size of flash should be considered error.

File: drivers/flash/flash_stm32_ospi.c [hunk 2]
```diff
@@ -957,15 +1010,19 @@ static int flash_stm32_ospi_erase(const struct device *dev, off_t addr,
...
 			/* Chip erase */
-			LOG_DBG("Chip Erase");
 			cmd_erase.Instruction = (dev_cfg->data_mode == OSPI_OPI_MODE)
 					? SPI_NOR_OCMD_BULKE
 					: SPI_NOR_CMD_BULKE;
 			cmd_erase.AddressMode = HAL_OSPI_ADDRESS_NONE;
-			/* Full chip erase command */
+			/* Full chip erase (Bulk) command */
 			ospi_send_cmd(dev, &cmd_erase);
+			LOG_DBG("Chip Erase");
```
Comment (de-nordic) [inline drivers/flash/flash_stm32_ospi.c:1019]: The LOG_DBG should be reported the moment you decide the logic goes towards chip erase, not after it has already been invoked.

File: drivers/flash/flash_stm32_ospi.c [hunk 3]
```diff
@@ -957,15 +1010,19 @@ static int flash_stm32_ospi_erase(const struct device *dev, off_t addr,
...
+
 
 			size -= dev_cfg->flash_size;
+			/* Chip (Bulk) erase started, wait until WEL becomes 0 */
+			stm32_ospi_mem_erased(&dev_data->hospi,
```
Comment (de-nordic) [inline drivers/flash/flash_stm32_ospi.c:1024]: Does this return any error code?

File: drivers/flash/flash_stm32_ospi.c (hunk 2 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_ospi.c:1019]: ok, moving above

File: drivers/flash/flash_stm32_ospi.c (hunk 1 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_ospi.c:956]: Then I prefer to let 
```
	/* Maximise erase size : means the complete chip */
	if (size > dev_cfg->flash_size) {
		size = dev_cfg->flash_size;
	}
```
And the 	address is 0 in the erasing loop `if (size == dev_cfg->flash_size) {`

**Comment by FRASTM** [comment]
rebase on 63ed1d977a2b47d1820447f34ac5c9c8ed30f7ca 
update after review

**Comment by MaureenHelm** [comment]
@de-nordic @gautierg-st please revisit

**Review by de-nordic — APPROVED** [review]

**Review by erwango — APPROVED** [review]
