### PR TITLE
usb: fix possible deadlock in usb_transfer_sync()

### LINKED ISSUE #31091: usb: usb_transfer_sync deadlocks on disconnect/cancel transfer
`usb_transfer_sync()` blocks on semaphor that is normally released in a callback

```
static void usb_transfer_sync_cb(uint8_t ep, int size, void *priv)
{
	struct usb_transfer_sync_priv *pdata = priv;

	pdata->tsize = size;
	k_sem_give(&pdata->sem);
}

```

however when the transfer is interrupted (eg. by disconnecting the cable in my test setup with stm32) that callback is never called as we can see in `usb_transfer_work()`

```
static void usb_transfer_work(struct k_work *item)
{
...
done:
...
		/* Transfer completion callback */
		if (trans->status != -ECANCELED) {
			cb(ep, tsize, priv);
		}
	}
}
```

I do not see any obvious fix now, probably we can move the sync semaphore to the `usb_transfer_data` structure and check that case...

### PR DESCRIPTION
**Pull request by xhpohanka**
Syncing here is done with a semaphore declared on a function stack
and released in a callback. In case of a cancelled transfer (eg.
cable disconnect) the callback is never called.

The fix introduces a periodic check if a transfer is still valid.

Fixes #31091

### CODE REVIEW

File: subsys/usb/usb_transfer.c [hunk 1]
```diff
@@ -313,8 +313,22 @@ int usb_transfer_sync(uint8_t ep, uint8_t *data, size_t dlen, unsigned int flags
...
-	/* Semaphore will be released by the transfer completion callback */
-	k_sem_take(&pdata.sem, K_FOREVER);
+	/* Semaphore will be released by the transfer completion callback
+	 * which might not be called when transfer was cancelled
+	 */
+	while (1) {
+		struct usb_transfer_data *trans;
+
+		ret = k_sem_take(&pdata.sem, K_MSEC(100));
+		if (ret == 0)
```
Comment (pabigot) [inline subsys/usb/usb_transfer.c:323]: Coding style: need curly braces around the if block.

Comment (xhpohanka) [reply subsys/usb/usb_transfer.c:323]: I see, this is surprisingly different from linux kernel coding style, I will fix it later

File: subsys/usb/usb_transfer.c [hunk 2]
```diff
@@ -313,8 +313,22 @@ int usb_transfer_sync(uint8_t ep, uint8_t *data, size_t dlen, unsigned int flags
...
 
-	/* Semaphore will be released by the transfer completion callback */
-	k_sem_take(&pdata.sem, K_FOREVER);
+	/* Semaphore will be released by the transfer completion callback
+	 * which might not be called when transfer was cancelled
+	 */
+	while (1) {
+		struct usb_transfer_data *trans;
+
+		ret = k_sem_take(&pdata.sem, K_MSEC(100));
```
Comment (jfischer-no) [inline subsys/usb/usb_transfer.c:322]: Making this configurable is probably too much, but could you please add a define for this, `#define USB_TRANSFER_SYNC_TIMEOUT    100`?

File: subsys/usb/usb_transfer.c [hunk 3]
```diff
@@ -313,8 +313,22 @@ int usb_transfer_sync(uint8_t ep, uint8_t *data, size_t dlen, unsigned int flags
...
+		if (ret == 0)
+			break;
+
+		trans = usb_ep_get_transfer(ep);
+		if (!trans || trans->status != -EBUSY) {
+			LOG_DBG("Sync transfer cancelled, ep 0x%02x", ep);
```
Comment (jfischer-no) [inline subsys/usb/usb_transfer.c:328]: Does a bit higher LOG level make sense here, LOG_INF/LOG_WRN?

File: subsys/usb/usb_transfer.c (hunk 2 above)
Comment (xhpohanka) [reply subsys/usb/usb_transfer.c]: done, actually I did not think about the timeout value too much, 100ms is just first try

File: subsys/usb/usb_transfer.c (hunk 3 above)
Comment (xhpohanka) [reply subsys/usb/usb_transfer.c:331]: I'm not sure if it is necessary to warn here more. I think that the case with cancelled transfer is quite common and valid.

Comment (jfischer-no) [reply subsys/usb/usb_transfer.c:331]: It may be valid but not common and should be treated accordingly by the application. At least LOG_INF would be appropriate to make the developer aware, LOG_DBG is too noisy.

Comment (xhpohanka) [reply subsys/usb/usb_transfer.c]: ok, done

**Review by jfischer-no — APPROVED** [review]

**Review by nashif — APPROVED** [review]
