### PR TITLE
Bluetooth: host: Fix issues in use of big-handle from HCI events

### LINKED ISSUE #33312: [Coverity CID: 219721] Untrusted array index read in subsys/bluetooth/host/iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b4f5b9e23770f2c9cddf95fef7b9af32da309f7f/subsys/bluetooth/host/iso.c#L1386

Category: Insecure data handling
Function: `hci_le_big_complete`
Component: Bluetooth
CID: [219721](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=219721)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b4f5b9e23770f2c9cddf95fef7b9af32da309f7f/subsys/bluetooth/host/iso.c#L1386

```
1380         return err;
1381     }
1382    
1383     void hci_le_big_complete(struct net_buf *buf)
1384     {
1385         struct bt_hci_evt_le_big_complete *evt = (void *)buf->data;
>>>     CID 219721:  Insecure data handling  (TAINTED_SCALAR)
>>>     Using tainted variable "evt->big_handle" as an index into an array "bigs".
1386         struct bt_iso_big *big = &bigs[evt->big_handle];
1387    
1388         BT_DBG("BIG[%u] %p completed, status %u", big->handle, big, evt->status);
1389    
1390         if (evt->num_bis != big->num_bis) {
1391             BT_ERR("Invalid number of BIS, was %u expected %u", evt->num_bis, big->num_bis);
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #33313: [Coverity CID: 219728] Untrusted array index read in subsys/bluetooth/host/iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b4f5b9e23770f2c9cddf95fef7b9af32da309f7f/subsys/bluetooth/host/iso.c#L1421

Category: Insecure data handling
Function: `hci_le_big_sync_established`
Component: Bluetooth
CID: [219728](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=219728)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b4f5b9e23770f2c9cddf95fef7b9af32da309f7f/subsys/bluetooth/host/iso.c#L1421

```
1415     }
1416    
1417     void hci_le_big_sync_established(struct net_buf *buf)
1418     {
1419         struct bt_hci_evt_le_big_sync_established *evt = (void *)buf->data;
1420         uint16_t big_handle = sys_le16_to_cpu(evt->big_handle);
>>>     CID 219728:  Insecure data handling  (TAINTED_SCALAR)
>>>     Using tainted variable "big_handle" as an index into an array "bigs".
1421         struct bt_iso_big *big = &bigs[big_handle];
1422    
1423         BT_DBG("BIG[%u] %p sync established", big->handle, big);
1424    
1425         if (evt->status || evt->num_bis != big->num_bis) {
1426             big_disconnect(big);
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by joerchan**
Fix parsing BIG handle which is just one octet as a two octet field,
which could have caused problems on big-endian systems.

Validate the big_handle before received from the controller before
using it as an array into the bigs array.

Discover by coverity: Insecure data handling  (TAINTED_SCALAR)
  Using tainted variable "big_handle" as an index into an array "bigs".

Fixes: #33312
Fixes: #33313

### CODE REVIEW

File: subsys/bluetooth/host/iso.c [hunk 1]
```diff
@@ -1383,7 +1383,14 @@ int bt_iso_big_terminate(struct bt_iso_big *big)
 void hci_le_big_complete(struct net_buf *buf)
 {
 	struct bt_hci_evt_le_big_complete *evt = (void *)buf->data;
-	struct bt_iso_big *big = &bigs[evt->big_handle];
+	struct bt_iso_big *big;
+
+	if (evt->big_handle > ARRAY_SIZE(bigs)) {
```
Comment (jhedberg) [inline subsys/bluetooth/host/iso.c:1388]: Shouldn't this be `>=` (and in all the other places as well)?

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/iso.c [hunk 2]
```diff
@@ -1417,8 +1430,14 @@ void hci_le_big_terminate(struct net_buf *buf)
...
 {
 	struct bt_hci_evt_le_big_sync_established *evt = (void *)buf->data;
-	uint16_t big_handle = sys_le16_to_cpu(evt->big_handle);
-	struct bt_iso_big *big = &bigs[big_handle];
+	struct bt_iso_big *big;
+
+	if (evt->big_handle > ARRAY_SIZE(bigs)) {
+		BT_WARN("Invalid BIG handle");
+		return;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/host/iso.c:1438]: Similar here; we should terminate the pending BIG

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/iso.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/iso.c]: Yes, fixed that.

File: subsys/bluetooth/host/iso.c [hunk 3]
```diff
@@ -1383,7 +1383,14 @@ int bt_iso_big_terminate(struct bt_iso_big *big)
 void hci_le_big_complete(struct net_buf *buf)
 {
 	struct bt_hci_evt_le_big_complete *evt = (void *)buf->data;
-	struct bt_iso_big *big = &bigs[evt->big_handle];
+	struct bt_iso_big *big;
+
+	if (evt->big_handle > ARRAY_SIZE(bigs)) {
+		BT_WARN("Invalid BIG handle");
+		return;
+	}
```
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/iso.c]: I suppose you are right, you know this better than me.

How do I do that?

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/iso.c]: I guess we first need to find a way to mark a BIG as pending (there can only be a single BIG initiating or a single BIG syncing at one time (although we can have a BIG initiating and another BIG syncing at the same time), so I suggest adding a (atomic?) flag to the BIG struct with a `syncing` and a `initiating` bit and when this even arrives with an invalid handle, we iterate the array of BIGs and find the syncing/initiating (based on the event) and terminate it. 

To terminate an invalid BIG we would probably need to change the `struct bt_iso_big *big` parameter of `hci_le_terminate_big` and `hci_le_big_sync_term` to just be the (invalid) handle, and then also call `big_disconnect(big);` and `cleanup_big(big);` with the BIG we looked up so that we clean up the host as well as notifying the application.

File: subsys/bluetooth/host/iso.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/host/iso.c]: @joerchan while your new change works, isn't it simpler to just do as suggested by Johan and do `>=` rather than `! <`?

Comment (joerchan) [reply subsys/bluetooth/host/iso.c]: Sure, I just fixed this before I saw Johans comment.

I guess this is subjective, but in my head i find it easier to deal with negations of the expression rather than the opposite expression (as you can see by the fact I messed this up :P).
I can change to `>=` if that is preferred.

Comment (jhedberg) [reply subsys/bluetooth/host/iso.c]: `>=` is easier to read for me at least

Comment (jhedberg) [reply subsys/bluetooth/host/iso.c]: @jhedberg wrote:
> \>= is easier to read for me at least

@joerchan meaning, I'll wait for you to update to that before approving 😉

File: subsys/bluetooth/host/iso.c [hunk 4]
```diff
@@ -1140,7 +1153,9 @@ static void cleanup_big(struct bt_iso_big *big)
 
 	big->bis = NULL;
 	big->num_bis = 0;
-	atomic_clear(&big->initialized);
+	atomic_clear_bit(big->flags, BT_BIG_SYNCING);
+	atomic_clear_bit(big->flags, BT_BIG_PENDING);
+	atomic_clear_bit(big->flags, BT_BIG_INITIALIZED);
```
Comment (Thalley) [inline subsys/bluetooth/host/iso.c:1158]:
```suggestion
	atomic_clear(&big->flags);
```

File: subsys/bluetooth/host/iso.c [hunk 5]
```diff
@@ -1383,7 +1398,21 @@ int bt_iso_big_terminate(struct bt_iso_big *big)
...
 	struct bt_hci_evt_le_big_complete *evt = (void *)buf->data;
-	struct bt_iso_big *big = &bigs[evt->big_handle];
+	struct bt_iso_big *big;
+
+	if (!(evt->big_handle < ARRAY_SIZE(bigs))) {
+		BT_WARN("Invalid BIG handle");
+
+		big = big_lookup_flag(BT_BIG_PENDING);
+		if (big) {
+			cleanup_big(big);
```
Comment (Thalley) [inline subsys/bluetooth/host/iso.c:1408]: I think we need to do the same here as we do for per-adv and call the disconnected callbacks by calling `big_disconnect` before `cleanup_big`.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/iso.c [hunk 6]
```diff
@@ -1127,6 +1127,19 @@ static struct bt_iso_big *get_free_big(void)
 	return NULL;
 }
 
+static struct bt_iso_big *big_lookup_flag(int bit)
+{
+	for (int i = 0; i < ARRAY_SIZE(bigs); i++) {
+		if (!atomic_test_bit(bigs[i].flags, bit)) {
```
Comment (Thalley) [inline subsys/bluetooth/host/iso.c:1133]:
```suggestion
		if (atomic_test_bit(bigs[i].flags, bit)) {
```

File: subsys/bluetooth/host/iso.c (hunk 4 above)
Comment (joerchan) [reply subsys/bluetooth/host/iso.c:1158]: It's not the same type:
```
warning: passing argument 1 of 'atomic_clear' from incompatible pointer type [-Wincompatible-pointer-types]
 1156 |  atomic_clear(&big->flags);
 ```
 
 Could update to a memset of the struct?

File: subsys/bluetooth/host/iso.c (hunk 5 above)
Comment (joerchan) [reply subsys/bluetooth/host/iso.c:1408]: I'm unsure about the `bit_disconnect` you mentioned, if you see below here other if the number of BIS is invalid there is also just cleanup_big.

Is this correct?

File: subsys/bluetooth/host/iso.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/iso.c]: Is it correct now, I haven't done `big_disconnect` because other error handling in this function also did not do this. Is this something that needs to be improved?

File: subsys/bluetooth/host/iso.c (hunk 6 above)
Comment (joerchan) [reply subsys/bluetooth/host/iso.c]: Thank you for testing, fixed.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/iso.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/host/iso.c:1158]: Might just be `atomic_clear(big->flags);`. We could memset the entire struct as well as that's what we are basically doing anyhow.

File: subsys/bluetooth/host/iso.c (hunk 5 above)
Comment (Thalley) [reply subsys/bluetooth/host/iso.c:1408]: I think that's actually rather a missing `big_disconnect(big);` from below. I guess I was unsure whether or not to call the connected/disconnect callbacks for the broadcaster, but since we are also calling `bt_conn_set_state(bis->conn, BT_CONN_CONNECTED);` (which calls the `connected` callback), then we should also call the `disconnected` callback. 

So I suggest adding it to both places.

**Review by Thalley — CHANGES_REQUESTED** [review]
A few responses

File: subsys/bluetooth/host/iso.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/iso.c]: See https://github.com/zephyrproject-rtos/zephyr/pull/33461#discussion_r597510476

**Review by Thalley — APPROVED** [review]
