### PR TITLE
Bluetooth: shell: Fix null check in cmd_conn_phy_update

### LINKED ISSUE #34201: Fatal error when perform "bt phy-update" if there is not any connections at ./tests/bluetooth/shell
**Describe the bug**
*./tests/bluetooth/shell* is a Swiss-knife application, however, if there is not any connections but performs **bt phy-update**, it can cause a fatal error because of conn-check-missing. 

**To Reproduce**

**Expected behavior**
A warning message return is appreciated instead of system failure. 

**Impact**
I need to reset the board to make the board recover out of fatal error. 

**Logs and console output**

**Environment (please complete the following information):**
 - Commit SHA, d3a94fa8ab2457ae77b9268921a3ea907142db8f

**Additional context**

### PR DESCRIPTION
**Pull request by kaiser-ren**
When I used ./tests/bluetooth/shell, if there is not any connections established but perform **bt phy-update**, it can cause a fatal error because of conn-check-missing, null check for default_conn pointer is necessary in case causing a system failure.

Fixes #34201

### CODE REVIEW

**Comment by kaiser-ren** [comment]
Try to fix #34201

**Review by cvinayak — CHANGES_REQUESTED** [review]
Other commands like data length update, connection update, etc... all have this issue. Its best to address them all.

File: subsys/bluetooth/shell/bt.c [hunk 1]
```diff
@@ -2179,6 +2179,13 @@ static int cmd_conn_phy_update(const struct shell *shell, size_t argc,
 	struct bt_conn_le_phy_param param;
 	int err;
 
+	if (default_conn == NULL) {
+		z_shell_fprintf(shell, SHELL_ERROR,
+				"%s: at least, one connection is required\n",
+				shell->ctx->active_cmd.syntax);
+		return -EINVAL;
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:2186]: I'm not sure of the importance, but it seems that when bad arguments are sent to shell commands, we return `-ENOEXEC`. 

So I suggest we return that here as well.

**Review by Thalley — CHANGES_REQUESTED** [review]
I generally agree with @cvinayak regarding adding this everywhere, but I'm perfectly content to fix those in other PRs.

File: subsys/bluetooth/shell/bt.c (hunk 1 above)
Comment (kaiser-ren) [reply subsys/bluetooth/shell/bt.c:2186]: If we have a common way to handle this bad argument return, I will follow it.

**Review by joerchan — CHANGES_REQUESTED** [review]
The merge commits must be removed.

**Comment by Thalley** [comment]
@kaiser-ren Btw, you can link this PR to the issue by using one of the Github closing keywords in the pull request description: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

That way, when this is merged, the issue is automatically marked as done.

**Comment by kaiser-ren** [comment]
> @kaiser-ren Btw, you can link this PR to the issue by using one of the Github closing keywords in the pull request description: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> 
> That way, when this is merged, the issue is automatically marked as done.

Thanks. Apologize that this is my first zephyr pull request, it may take some time.

File: subsys/bluetooth/shell/bt.c (hunk 1 above)
Comment (jakub-uC) [reply subsys/bluetooth/shell/bt.c:2186]: It is not allowed to use function `z_shell_fprintf` inside the command handler. It is an internal function used by the shell.
You can implement it either:
```
shell_fprintf(shell, SHELL_ERROR,
				"%s: at least, one connection is required\n",
				shell->ctx->active_cmd.syntax);
```
or
```
shell_error(shell,  "%s: at least, one connection is required",
			    shell->ctx->active_cmd.syntax);
```

**Review by jakub-uC — CHANGES_REQUESTED** [review]

**Comment by kaiser-ren** [comment]
Here is a CI error, **Commit e8d025fca8:
3: UC4 Line exceeds max length (109>72): "For Link Layer PHY update, null check for default_conn pointer is necessary in case causing a system failure."**
I'm not sure how can I modify the commit message? And it's already being public on Zephyr repo.

**Comment by Thalley** [comment]
> Here is a CI error, **Commit e8d025fca8: 3: UC4 Line exceeds max length (109>72): "For Link Layer PHY update, null check for default_conn pointer is necessary in case causing a system failure."**
> I'm not sure how can I modify the commit message? And it's already being public on Zephyr repo.

You can modify your commit message but doing either `git commit --amend` or using `git rebase -i`

**Comment by joerchan** [comment]
@kaiser-ren You should read up on the contributing guidelines for the project, that will help you get this PR ready.
https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow

**Comment by kaiser-ren** [comment]
> > Here is a CI error, **Commit e8d025fca8: 3: UC4 Line exceeds max length (109>72): "For Link Layer PHY update, null check for default_conn pointer is necessary in case causing a system failure."**
> > I'm not sure how can I modify the commit message? And it's already being public on Zephyr repo.
> 
> You can modify your commit message but doing either `git commit --amend` or using `git rebase -i`

Thanks, fixed.

File: subsys/bluetooth/shell/bt.c [hunk 2]
```diff
@@ -2183,6 +2183,13 @@ static int cmd_conn_phy_update(const struct shell *shell, size_t argc,
 	param.pref_rx_phy = param.pref_tx_phy;
 	param.options = BT_CONN_LE_PHY_OPT_NONE;
 
+	if (default_conn == NULL) {
+		shell_fprintf(shell, SHELL_ERROR,
+				"%s: at least, one connection is required\n",
+				shell->ctx->active_cmd.syntax);
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:2189]:
```suggestion
	if (default_conn == NULL) {
		shell_error(shell, 
				"%s: at least, one connection is required\n",
				shell->ctx->active_cmd.syntax);
```

**Review by Thalley — CHANGES_REQUESTED** [review]
Please also reduce the commits to just one commit.

**Comment by joerchan** [comment]
@kaiser-ren Please find us on the zephyrproject slack channel and we can help you resolve the issues with git.

**Comment by joerchan** [comment]
@kaiser-ren The commit is empty.

**Comment by kaiser-ren** [comment]
Apologize very deeply to make this PR mess, finally, make CI happy except buildkite is still ongoing. @Thalley, already merged the commit into one.
This 1st PR makes me learn a lot, thanks for your guide and patient.

**Review by jakub-uC — APPROVED** [review]

File: subsys/bluetooth/shell/bt.c [hunk 3]
```diff
@@ -2141,6 +2141,13 @@ static int cmd_conn_phy_update(const struct shell *shell, size_t argc,
 	struct bt_conn_le_phy_param param;
 	int err;
 
+	if (default_conn == NULL) {
+		shell_error(shell,
+				"%s: at least, one connection is required\n",
+				shell->ctx->active_cmd.syntax);
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:2147]: Indentation seems slight off, but not something I would block this PR for

**Review by Thalley — APPROVED** [review]
Looks alright to me

File: subsys/bluetooth/shell/bt.c [hunk 4]
```diff
@@ -2141,6 +2141,13 @@ static int cmd_conn_phy_update(const struct shell *shell, size_t argc,
 	struct bt_conn_le_phy_param param;
 	int err;
 
+	if (default_conn == NULL) {
+		shell_error(shell,
+				"%s: at least, one connection is required\n",
```
Comment (nordic-krch) [inline subsys/bluetooth/shell/bt.c:2146]: `\n` is redundant. `shell_error` adds in.

Comment (kaiser-ren) [reply subsys/bluetooth/shell/bt.c:2146]: Thanks @nordic-krch . 
@nordic-krch and @Thalley , after this PR, I will create another PR to add the null check for conn_update() and conn_data_length_update(), how about I fix "\n" at the next PR and we keep this approval process going?  Sound good to every approver?

Comment (nordic-krch) [reply subsys/bluetooth/shell/bt.c:2146]: i think that you can remove `\n` in this PR, if there is no critical changes others reviewers don't need to re-review and approvals stays.

Comment (Thalley) [reply subsys/bluetooth/shell/bt.c:2146]: I agree with @nordic-krch

Comment (kaiser-ren) [reply subsys/bluetooth/shell/bt.c]: Roger, I've already done it.

**Review by cvinayak — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
