### PR TITLE
drivers: improve the arcv2_timer driver to update cycles correctly

### LINKED ISSUE #23476: tests/kernel/interrupt failed on ARC
**Describe the bug**
Running tests/kernel/interrupt on iotdk board, it will **stop at "test_prevent_interruption" and fail due to timeout.**

**To Reproduce**
1. sanitycheck -p iotdk --device-testing --device-serial /dev/ttyUSB0 -T tests/kernel/interrupt/
2. See error in hander.log file.

**Screenshots or console output**
```
*** Booting Zephyr OS build zephyr-v2.2.0-368-g22b9167acb52  ***
Running test suite interrupt_feature

starting test - test_isr_dynamic
PASS - test_isr_dynamic

starting test - test_nested_isr
Triggering irq : 93
isr0 running !!
Triggering irq : 92
isr1 ran !!
isr0 execution completed !!
PASS - test_nested_isr

**starting test - test_prevent_interruption
locking interrupts**
```

**Environment (please complete the following information):**
 - OS: fedora 28
 - Toolchain: zephyr-sdk-0.11.1
 - Commit ID: 22b9167a

### PR DESCRIPTION
**Pull request by vonhust**
referring the ARM's Systick driver, we did the following improvements:

* use 31 bits of 32-bit counter to avoid the rare but possible
  overflow of elapsed(). If 32 bits val are used, elpased() may
  return a wrong value. then wrong HW cycles.
* two ways to update the correct cycles
  - through systick timer irq
  - when systick timer irq cann't be handled because of irq
    locked/disabled, call z_timer_cycle_get_32->elapsed to update
    the correct cylces. no more than one counter-wrap is allowed.
* if elapsed() is not called too long (more than one counter-wrap) from
  systick tiemr irq or from z_timer_cycle_get_32. The lost of HW cycles
  is unavoidable.

* some detailed discussion can be found in #24332

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

Fixes #23476

### CODE REVIEW

**Review by andyross — APPROVED** [review]
This looks correct to me.  Though full disclosure: this gets subtle and edge cases like counter wraparound have been distressingly hard to get right in other drivers.  And a 32 bit wrap (or 31 -- nice trick, by the way) isn't likely to get hit in routine testing and might need to be whiteboxed to validate.

File: drivers/timer/arcv2_timer0.c [hunk 1]
```diff
@@ -279,29 +345,51 @@ void z_clock_set_timeout(s32_t ticks, bool idle)
...
+			last_load = delay;
 		}
-		timer0_limit_register_set(delay - 1);
-		last_load = delay;
-		timer0_control_register_set(_ARC_V2_TMR_CTRL_NH |
-							 _ARC_V2_TMR_CTRL_IE);
 	}
 
+	timer0_limit_register_set(last_load - 1);
+	timer0_count_register_set(0);
```
Comment (ruuddw) [inline drivers/timer/arcv2_timer0.c:390]: Could reprogramming the count register be avoided in some way? My concern is timer drift. There is some (variable) time between the read of count in elapsed() and the setting to 0 here. The earlier solution avoided reprogramming of the count register. Alternatively, can the call to timer0_count_register_set(0) be moved up, just after elapsed()? That reduces the amount of cycles between reading and resetting.

Comment (vonhust) [reply drivers/timer/arcv2_timer0.c:390]: I have ever considered about this, based on current mechanism, difficult to do that.

**Comment by carlescufi** [comment]
@ruuddw please approve if happy as-is

**Review by ruuddw — APPROVED** [review]
Thanks, with the reset of the timer count register moved close to the call to elapsed() I'm ok (assuming CI checks will pass).

**Comment by vonhust** [comment]
@ruuddw @andyross I changed the place of clearing counter in z_clock_set_timeout to reduce the cycles loss as few as possible. However didn't find a 0 loss solution by only changing LIMIT not COUNT.  Any ideas?

**Comment by ruuddw** [comment]
(with this location, the drift is likely lower than the timer accuracy anyway...)
The original implementation didn't touch count - but was less robust against long interrupt disable.
ARC has multiple timers (configurable HW IP, depending on the silicon design configuration), a combination of timer0 + RTC or timer1 (like for SMP) would likely be much simpler.
Not for this PR, but something to consider adding in the future.

File: drivers/timer/arcv2_timer0.c [hunk 2]
```diff
@@ -211,11 +270,18 @@ int z_clock_driver_init(struct device *device)
...
 
 	IRQ_CONNECT(IRQ_TIMER0, CONFIG_ARCV2_TIMER_IRQ_PRIORITY,
 		    timer_int_handler, NULL, 0);
 
 	timer0_limit_register_set(last_load - 1);
+	/* make timer irq pulse sensitive, and self-clear when it's handled
+	 * then we can clear the IP bit of CTRT in non-interrupt context,
+	 * without missing timer irq.
+	 */
+	z_arc_v2_irq_unit_sensitivity_set(IRQ_TIMER0, 1);
```
Comment (abrodkin) [inline drivers/timer/arcv2_timer0.c:284]: If you specify an IRQ line mode instead of meaningless `1` it's better to have `ARCV2_IRQ_MODE_PULSE` etc. Otherwise this very special setup (I never saw configuration of ARC Timer done via Pulse mode before so won't be surprised if it might produce unexpected results) might not attract attention of the next reader.

Also I don't quite understand the whole idea of switching to pulse-triggered IRQ from the ARC Timer. Which problem does it solve? And if it is still usable with all our current HW and simulation platforms. I'd strongly suggest to not use pulse-triggered IRQ source if possible.

**Review by abrodkin — CHANGES_REQUESTED** [review]
Sorry but with switch to pulse-sensitive IRQs from ARC Timer I'm pretty skeptical here and would like to see first high-level design description.

Moreover maybe indeed switch to much simpler implementation with 2 separate clock sources:
1. Systick source (for example ARC Timer0)
2. Wallclock (32-bit ARC Timer1 or even 64-bit ARC RTC)

File: drivers/timer/arcv2_timer0.c [hunk 3]
```diff
@@ -131,17 +163,40 @@ static ALWAYS_INLINE void timer0_limit_register_set(u32_t count)
...
 		val =  timer0_count_register_get();
 		ctrl = timer0_control_register_get();
 	} while (timer0_count_register_get() < val);
 
-	ov = (ctrl & _ARC_V2_TMR_CTRL_IP) ? last_load : 0;
-	return val + ov;
+	if (ctrl & _ARC_V2_TMR_CTRL_IP) {
+		overflow_cyc += last_load;
+		/* clear the IP bit of the control register */
+		timer0_control_register_set(_ARC_V2_TMR_CTRL_NH |
```
[the remark this answers is not in the document]
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c:195]: the overhead in elapsed() must b as small as possible to avoid cycle loss in set_timeout.
For readability concern, i can merge _ARCH_V2_TMR_CTRL_NH with other macro.

File: drivers/timer/arcv2_timer0.c [hunk 4]
```diff
@@ -211,11 +270,18 @@ int z_clock_driver_init(struct device *device)
...
 	last_load = CYC_PER_TICK;
+	overflow_cyc = 0;
+	announced_cycles = 0;
 
 	IRQ_CONNECT(IRQ_TIMER0, CONFIG_ARCV2_TIMER_IRQ_PRIORITY,
 		    timer_int_handler, NULL, 0);
 
 	timer0_limit_register_set(last_load - 1);
+	/* make timer irq pulse sensitive, and self-clear when it's handled
+	 * then we can clear the IP bit of CTRT in non-interrupt context,
```
[the remark this answers is not in the document]
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c:281]: good catch, i will modify it

File: drivers/timer/arcv2_timer0.c (hunk 2 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c:284]: I run the tests on nsim_em/nsim_sem/nsim_hs,  the results shows pulse trigger is ok. If real hardware is also ok, i think there will be no problem.

Why we need pulse trigger?
Because we need to update the overflow_cyc  in elapsed() when irq is locked. Without pulse trigger, the clear of IP bit will also clear the irq request, then when irq is unlocked, the timer irq will be lost, then no announcement of systick.  I think this is unacceptable for RTOS.

I have also considered to use software irq to keep the timer irq, but it will make things more complex.

The ARCv2 ISA also allows pulse trigger to do a self-clear of IRQ.

For wall clock , it relies on extra hardware. We can use one 32bit timer to do the same thing as ARM SysTick (24bit) does.

Comment (abrodkin) [reply drivers/timer/arcv2_timer0.c:284]: So I went once again over long discussion in https://github.com/zephyrproject-rtos/zephyr/pull/24332 and now is confused even more.

Yet I don't see any justification for that dark (or rather dirty) magic with IRQs except we may `busy_wait()` twice longer. But do we really want to trade that IMHO meaningless twice longer `busy_wait()` for:
1. More tricky driver logic
2. "Delayed" IRQ handling

I'd propose to just add a check in `busy_wait()` for too long periods. Moreover I think long `busy_wait()` which implicitly means spinning w/ all [not only timer] IRQs disabled is something you don't want to happen in good RTOS-based solution as responsiveness of it will be quite slow in some cases :)

So first I'd like to figure out if we're trying to solve a valid problem here or we're overengineering something which has no real use in a sane software design.

Maybe we even return to https://github.com/zephyrproject-rtos/zephyr/pull/24332 and continue discussion there before drafting fixes. @andyross @andrewboie what do you think?

File: drivers/timer/arcv2_timer0.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (abrodkin) [reply drivers/timer/arcv2_timer0.c:195]: No merging of 2 defines in one makes even less sense as it may mislead a reader.
Speaking of minimization of overhead I guess we already do a lot here as well as we'll possibly have prologue/epilogue generated by the compiler which we don't see in C-sources here. So another 2 instructions and few CPU cycles of overhead shouldn't hurt I guess.

**Comment by andrewboie** [comment]
I'm OK with establishing an upper bound on how long you can busy-wait for. I don't know what that value should specifically be, but I agree that in practice people busy-wait for very short time periods.

**Comment by vonhust** [comment]
@abrodkin , my understanding is your concern is about pulse trigger of ARC internal timer. Although it was rarely used before, and not clearly documented in ARCv2 ISA,  the pulse trigger of ARC internal timer should be supported,  nsim works, what we need to do is make a double check on hardware.  The self-clear of timer irq also avoids re-setting CTRL/clearing IP bit in isr, makes codes more generic. I don't think it's a trick.

The IP bit of CTRL takes two roles, COUNTER overflow and IP pending.  If in hardware two different bits for two different roles. Even pulse trigger is not supported, we also can separately clear IP pending bit in timer ISR. 

For k_busy_wait ,  i don't mind whether a limit check is added, because in other places, drivers, application  etc. because of poor codes, poor design,  the irq can still be locked for long time although we all know it's not right.  But current cycle based k_busy_wait can update the total cycles correctly, so when irq is unlocked , we can get the correct cycles and ticks.

And even a limit is added in k_busy_wait, this PR still works. In fact, this PR includes a fix of bugs found through k_busy_wait but not limited.

Again,
**the core concern of this PR is whether we can use pulse trigger for timer irq.**   If really can't work because of hardware limitation ,  i will move clear of IP bit out of elapsed() , and into timer isr. 

With this PR and some my previous PRs,  i got a clean sanitycheck results of test/kernel

**Comment by ruuddw** [comment]
@abrodkin I think the implementation is acceptable now. Similar to CM systick, and the drift is minimal. Losing ticks due to long interrupt disable times (also during busy wait) would not be normal, regular use (interrupt disable/busy waiting should normally be less than 2 tick periods).
I believe there is or has been some discussion on a counter api vs timer api - using a separate RTC / timer1 could be something to do for supporting the RTC/counter driver and not timer for _cycle_get_32.

**Comment by vonhust** [comment]
ping for merge, as the merge window is closing.

**Comment by andrewboie** [comment]
> ping for merge, as the merge window is closing.

@vonhust need @abrodkin to re-visit his current -1 review for that

**Comment by andrewboie** [comment]
> @abrodkin I think the implementation is acceptable now. Similar to CM systick, and the drift is minimal. Losing ticks due to long interrupt disable times (also during busy wait) would not be normal, regular use (interrupt disable/busy waiting should normally be less than 2 tick periods).

@ruuddw if you approve of the patch....can you please approve it in GitHub?

**Review by ruuddw — APPROVED** [review]
re-approved

**Review by abrodkin — APPROVED** [review]
