### PR TITLE
tests: drivers: adc: fix failing test for frdm_k64f

### LINKED ISSUE #8173: Driver tests failing with an assertion on frdm_k64f
The following driver tests are failing with an assertion on frdm_k64f:

tests/drivers/adc/adc_simple/peripheral.adc
```
***** Booting Zephyr OS v1.12.0-rc2-75-g7a18b08 *****                           
Running test suite _adc_test
===================================================================
starting test - test_adc

    Assertion failed at /home/maureen/zephyr/tests/drivers/adc/adc_simple/src/ma
Cannot get adc controller
FAIL - test_adc
```

A full regression with device testing was run on frdm_k64f on commit 7a18b083ebe4712fbb258d09c0f53a71b7f46678:
```
$ sanitycheck -p frdm_k64f --device-testing --device-serial /dev/ttyACM0 
Cleaning output directory /home/maureen/zephyr/sanity-out
Building testcase defconfigs...
256 tests selected, 55151 tests discarded due to filters
total complete:   27/ 256  10%  failed:    0

frdm_k64f                 samples/mpu/mpu_stack_guard_test/test              FAILED: timeout
	see: sanity-out/frdm_k64f/samples/mpu/mpu_stack_guard_test/test/handler.log

total complete:   46/ 256  17%  failed:    1

frdm_k64f                 samples/mpu/mpu_stack_guard_test/test_stack_guard  FAILED: timeout
	see: sanity-out/frdm_k64f/samples/mpu/mpu_stack_guard_test/test_stack_guard/handler.log

total complete:  112/ 256  43%  failed:    2

frdm_k64f                 tests/net/vlan/net.vlan                            FAILED: failed
	see: sanity-out/frdm_k64f/tests/net/vlan/net.vlan/handler.log

total complete:  126/ 256  49%  failed:    3

frdm_k64f                 samples/drivers/watchdog/test                      FAILED: timeout
	see: sanity-out/frdm_k64f/samples/drivers/watchdog/test/handler.log

total complete:  144/ 256  56%  failed:    4

frdm_k64f                 tests/net/utils/net.util                           FAILED: timeout
	see: sanity-out/frdm_k64f/tests/net/utils/net.util/handler.log

total complete:  158/ 256  61%  failed:    5

frdm_k64f                 tests/net/icmpv6/net.icmpv6                        FAILED: timeout
	see: sanity-out/frdm_k64f/tests/net/icmpv6/net.icmpv6/handler.log

total complete:  159/ 256  62%  failed:    6

frdm_k64f                 tests/benchmarks/sys_kernel/benchmark.kernel       FAILED: failed
	see: sanity-out/frdm_k64f/tests/benchmarks/sys_kernel/benchmark.kernel/handler.log

total complete:  173/ 256  67%  failed:    7

frdm_k64f                 tests/net/checksum_offload/net.offload             FAILED: failed
	see: sanity-out/frdm_k64f/tests/net/checksum_offload/net.offload/handler.log

total complete:  196/ 256  76%  failed:    8

frdm_k64f                 tests/net/lib/http_header_fields/net.http          FAILED: timeout
	see: sanity-out/frdm_k64f/tests/net/lib/http_header_fields/net.http/handler.log

total complete:  207/ 256  80%  failed:    9

frdm_k64f                 tests/net/trickle/net.trickle                      FAILED: timeout
	see: sanity-out/frdm_k64f/tests/net/trickle/net.trickle/handler.log

total complete:  208/ 256  81%  failed:   10

frdm_k64f                 tests/kernel/fifo/fifo_api/kernel.fifo.poll        FAILED: timeout
	see: sanity-out/frdm_k64f/tests/kernel/fifo/fifo_api/kernel.fifo.poll/handler.log

total complete:  222/ 256  86%  failed:   11

frdm_k64f                 tests/net/lib/mqtt_packet/net.mqtt.packet          FAILED: timeout
	see: sanity-out/frdm_k64f/tests/net/lib/mqtt_packet/net.mqtt.packet/handler.log

total complete:  235/ 256  91%  failed:   12

frdm_k64f                 tests/drivers/adc/adc_simple/peripheral.adc        FAILED: failed
	see: sanity-out/frdm_k64f/tests/drivers/adc/adc_simple/peripheral.adc/handler.log

total complete:  256/ 256  100%  failed:   13
243 of 256 tests passed with 0 warnings in 7090 seconds
```

### PR DESCRIPTION
**Pull request by nniranjhana**
Fixes #8173 

This test is failing for the frdm platform because
the ADC_DEVICE_NAME is different. Add #if statement
to correct for respective platform names.

Signed-off-by: Niranjhana N <niranjhana.n@intel.com>

### CODE REVIEW

**Comment by nashif** [comment]
this might fix initialisation and might get the test to pass, but do we read any valid values from ADC?

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
> this might fix initialisation and might get the test to pass, but do we read any valid values from ADC?

The channel needs to be configured too, similar to `tests/drivers/adc/adc_api/src/test_adc.c`

**Comment by nniranjhana** [comment]
@nashif yes, we might not be reading from ADC driver for this test case because, when @punitvara changed from `CONFIG_ADC_QMSI_SS` to `CONFIG_ADC_DW` in Kconfig, even though the API level changes are not yet done for the latter in the driver code, this adc_simple test still passed but the adc_api test hung.

@MaureenHelm thanks, made the changes here, similar to the other test.

**Comment by nashif** [comment]
> @nashif yes, we might not be reading from ADC driver for this test case because, when @punitvara changed from CONFIG_ADC_QMSI_SS to CONFIG_ADC_DW in Kconfig, even though the API level changes are not yet done for the latter in the driver code, this adc_simple test still passed but the adc_api test hung.

I was referring to frdm_k64f board and not being setup correctly for that board, nothing related to QMSI or DW

File: tests/drivers/adc/adc_simple/src/main.c [hunk 1]
```diff
@@ -19,7 +19,25 @@
 /* in millisecond */
 #define SLEEPTIME  2000
 
+#if defined(CONFIG_BOARD_FRDM_K64F)
+#define ADC_DEVICE_NAME "ADC_1"
```
Comment (MaureenHelm) [inline tests/drivers/adc/adc_simple/src/main.c]: Please use the config names rather than hardcoding the strings. Same as `tests/drivers/adc/adc_api/src/test_adc.c`,

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

**Review by MaureenHelm — APPROVED** [review]
