### PR TITLE
drivers: cleanup `__subsystem` tags

### LINKED ISSUE #72009: Required `_driver_api` suffix for `__subsystem` structs
**Describe the bug**
Structs tagged with `__subsystem` are required to have a `_driver_api` suffix to allow all build scripts (especially in userspace) to work properly.

The following in-tree definitions violate this:
https://github.com/zephyrproject-rtos/zephyr/blob/c2c95e18ed01b642b46b118f610b29f10a2227e3/include/zephyr/mgmt/ec_host_cmd/backend.h#L106
https://github.com/zephyrproject-rtos/zephyr/blob/c2c95e18ed01b642b46b118f610b29f10a2227e3/include/zephyr/drivers/emul_sensor.h#L28
https://github.com/zephyrproject-rtos/zephyr/blob/c2c95e18ed01b642b46b118f610b29f10a2227e3/include/zephyr/drivers/usb_c/usbc_ppc.h#L53
https://github.com/zephyrproject-rtos/zephyr/blob/c2c95e18ed01b642b46b118f610b29f10a2227e3/include/zephyr/drivers/emul_bbram.h#L26

The script `gen_kobject_list.py` used for userspace, simply removes the last 11 characters (`_driver_api`)
https://github.com/zephyrproject-rtos/zephyr/blob/c2c95e18ed01b642b46b118f610b29f10a2227e3/scripts/build/gen_kobject_list.py#L140-L141

**Expected behavior**
Keep it consistent, and throw a build error on violation.

**Impact**
As these are already in-tree, and can be used out-of-tree, a deprecation process might need to take place.

**Additional context**
Some reference PRs #71090 #71773

### PR DESCRIPTION
**Pull request by pdgendt**
In preparation of #71773 all drivers API structs should have a `__subsystem` tag. 
Additionally all `__subsystem` API structs are required to have a `_driver_api` suffix.

Fixes #72009

### CODE REVIEW

File: drivers/bbram/bbram_it8xxx2_emul.c [hunk 1]
```diff
@@ -45,7 +45,7 @@ static int it8xxx2_emul_backend_get_data(const struct emul *target, size_t offse
 	return 0;
 }
 
-static const struct emul_bbram_backend_api it8xxx2_emul_backend_api = {
+static const struct emul_bbram_driver_api it8xxx2_emul_backend_api = {
```
Comment (tbursztyka) [inline drivers/bbram/bbram_it8xxx2_emul.c:48]: shouldn't you have an typedef for the old name and declared as obsolete, for some transition time?

**Review by fabiobaltieri — APPROVED** [review]

File: drivers/bbram/bbram_it8xxx2_emul.c (hunk 1 above)
Comment (fabiobaltieri) [reply drivers/bbram/bbram_it8xxx2_emul.c:48]: would it work with the `scripts/build/gen_kobject_list.py`, regardless, simple enough but this should probably go through Arch WG for stable API change

**Review by MaureenHelm — APPROVED** [review]

File: drivers/bbram/bbram_it8xxx2_emul.c (hunk 1 above)
Comment (tbursztyka) [reply drivers/bbram/bbram_it8xxx2_emul.c:48]: the structure declaration is indeed public (see below),  the scope however is very thin. perhaps it's fine as it is.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Review by gmarull — APPROVED** [review]
For future: we should hide impl details from the user, forcing users to follow a naming scheme isn't a great design.

**Review by nashif — APPROVED** [review]

**Review by aaronemassey — APPROVED** [review]
