### PR TITLE
drivers: crypto: ataes132a: fix integer overflows in CRC and commands

### LINKED ISSUE #84683: [Coverity CID: 487763] Overflowed integer argument in drivers/crypto/crypto_ataes132a.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/drivers/crypto/crypto_ataes132a.c

Category: Insecure data handling
Function: `ataes132a_aes_ccm_encrypt`
Component: Drivers
CID: [487763](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487763)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/drivers/crypto/crypto_ataes132a.c#L524

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487763

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #84690: [Coverity CID: 487746] Overflowed constant in drivers/crypto/crypto_ataes132a_priv.h
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/drivers/crypto/crypto_ataes132a_priv.h

Category: Integer handling issues
Function: `ataes132a_atmel_crc`
Component: Drivers
CID: [487746](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487746)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/drivers/crypto/crypto_ataes132a_priv.h#L127

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487746

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by dleach02**
This commit addresses two integer handling issues in the ataes132a crypto driver identified by coverity scans.

1. In ataes132a_send_command, added a centralized validation check to ensure the 'nparams' value, when combined with the 5-byte packet overhead, does not exceed the 8-bit 'count' limit or the physical 64-byte command buffer. This prevents a potential wrap- around that would cause the chip to receive an invalid length byte.

2. In the Atmel CRC calculation, added an explicit cast to uint16_t during the bit-shift operation. This prevents unintended integer promotion and satisfies static analysis regarding potential overflows during the 16-bit CRC generation.

Fixes #84683
Fixes #84690

### CODE REVIEW

File: drivers/crypto/crypto_ataes132a.c [hunk 1]
```diff
@@ -52,12 +52,17 @@ static int ataes132a_send_command(const struct device *dev, uint8_t opcode,
 	uint8_t crc[2];
 	int i, i2c_return;
 
-	count = nparams + 5;
-	if (count > 64) {
+	/*
+	 * CID 487763: Validate nparams against both the 8-bit overflow
+	 * and the physical command buffer limit (64).
+	 */
+	if (nparams > (UINT8_MAX - 5) || (nparams + 5) > 64) {
```
Comment (valeriosetti) [inline drivers/crypto/crypto_ataes132a.c]: Sorry, I might be missing something, but doesn't this conditions translates to:
```suggestion
	if ((nparams > 250) || (nparams > 59)) {
```
?
If that's the case then the first condition is a bit useless IMO, isn't it?

**Review by valeriosetti — CHANGES_REQUESTED** [review]

File: drivers/crypto/crypto_ataes132a.c (hunk 1 above)
Comment (dleach02) [reply drivers/crypto/crypto_ataes132a.c]: I used a modification of your recommendation to make it clear to the human reader what we are checking for.

**Review by valeriosetti — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
@dleach02 YAY !!!
