### PR TITLE
net: ipv6: Drop pkt if src address is unspecified

### LINKED ISSUE #17450: net: IPv6/UDP datagram with unspecified addr and zero hop limit causes Zephyr to quit
If Zephyr echo server receives IPv6/UDP datagram with unspecified source IP address (::)  and hop limit set to zero it quits with log (89=EDESTADDRREQ):

```
[00:03:08.160,000] <err> net_echo_server_sample: UDP (IPv6): Failed to send 89
[00:03:08.160,000] <inf> net_echo_server_sample: Stopping...
```

This seems to be similar to issue #17427 but for IPv6.

[ipv6-udp-unspec-srcaddr-hoplimit-zero.pcap.gz](https://github.com/zephyrproject-rtos/zephyr/files/3376565/ipv6-udp-unspec-srcaddr-hoplimit-zero.pcap.gz)

### PR DESCRIPTION
**Pull request by jukkar**
If we receive IPv6 packet where source address is unspecified
(all zeros), then we need to drop it.

Fixes #17450

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

File: subsys/net/ip/ipv6.c [hunk 1]
```diff
@@ -383,6 +383,11 @@ enum net_verdict net_ipv6_input(struct net_pkt *pkt, bool is_loopback)
 		log_strdup(net_sprint_ipv6_addr(&hdr->src)),
 		log_strdup(net_sprint_ipv6_addr(&hdr->dst)));
 
+	if (net_ipv6_is_addr_unspecified(&hdr->src)) {
+		NET_DBG("DROP: src addr is %s", "unspecified");
```
Comment (tbursztyka) [inline subsys/net/ip/ipv6.c]: why the format string in this case?

Comment (jukkar) [reply subsys/net/ip/ipv6.c]: > why the format string in this case?

We can share the same string with IPv4 checks.

Comment (tbursztyka) [reply subsys/net/ip/ipv6.c]: ok, could be done for other drop message on src then

Comment (jukkar) [reply subsys/net/ip/ipv6.c]: > ok, could be done for other drop message on src then

I considered it but they look a bit different in IPv6 side so did not do it in this PR. We can do it separately if needed.

Comment (tbursztyka) [reply subsys/net/ip/ipv6.c]: sure

**Review by tbursztyka — APPROVED** [review]
