### PR TITLE
Arch arm cortex m swap locking

### LINKED ISSUE #22275: arm: cortex-R & M: CONFIG_USERSPACE: intermittent Memory region write access failures
**Describe the bug**

I am getting intermittent run-time failures such as:

     syscall z_hdlr_k_uptime_get failed check: Memory region 0x0002ff70 (size 8) write access denied
     ***** Hardware exception *****
     Current thread ID = 0x000221b0
     Faulting instruction address = 0x1a
     Fatal fault in thread 0x000221b0! Aborting.

In this example, k_uptime_get() was called, which is going to save its 64-bit return value into memory (due to the syscall macros).  The syscall gear is checking to see if the memory
address is valid.  The routines wind down into mpu_buffer_validate(), which will call is_user_accessible_region() and finally into get_region_ap().  The code
is failing because get_region_ap() has a critical code section which is not wrapped with an irq_lock()/irq_unlock().  In this failure, we write the MPU index register, then
take an external interrupt, go off to another thread for a while ( which is going to re-load the MPU entries), return to the current thread (again re-loading the MPU entries), and read the attribute register (for the wrong index) and fail.

In reading the current Cortex-M code, I don't see it protecting these critical sections either, so I'm left wondering if the 'M' class will save the index register during
interrupt processing.  If so, I would like to fix the 'R' code in a similar fashion.

There are several of these utility subroutines with this same critical code sections.

**To Reproduce**

I saw this on a Cortex-R based system.  Ioannis believes the problem exists in an 'M' based system as well.

This is an intermittent failure that will be hard to reproduce.  

A unit test might be to have a thread which is doing nothing more than calling k_uptime_get();  This will be calling the Z_SYSCALL_MEMORY_WRITE macro to check the destination buffer address.  Asynchronous to this, do something on a timer interrupt to send a message to a higher priority thread.  In my exact case, I was sending a message to a user mode work Q.  The higher priority thread could just read the message/work-item and wait again.  All we need to do is force the context switch to occur.  I think this test should fail fairly quickly.

**Expected behavior**
The memory access should have passed.  The location I was writing to was valid.

**Impact**
memory access fault.  System shuts down

**Screenshots or console output**
n/a

**Environment (please complete the following information):**
 - OS: Linux build environment
 - Toolchain GCC
 - Commi used: V 1.14  (however, we are in the process of upgrade to v2.1.0 now )

**Additional context**
discussed in devel mailing list #6695

### LINKED ISSUE #22685: armv8-m: userspace: syscall return sequence needs to be atomic
**Describe the bug**
The sequence of operations when returning from a Cortex-M system call is as follows:

1. Stack Limit Register is cleared (if we are on ARMv8-M)
2. Stack Pointer is set back to nPRIV (user) stack
3. thread.mode variable is set to nPRIV
4. CONTROL register nPRIV bit is set

The above sequence is executed in **thread PRIV mode** (cannot be executed in nPRIV mode, actually, as it leads to fault).

Now, if swap occurs between (1) and (2), or between (2) and (3) the PSPLIM will be set again to guard the privilege thread stack. This will cause a fault when the thread attempts to push to the user stack, which lies below the PRIV thread stack.

Note: ARMv7-M does not have this problem because it does not have stack pointer limit registers, so only steps (2), (3), (4) are executed.

For example: if swap occurs between (2) and (4) the processor returns to nPRIV mode, but the attempt to (over)write to the CONTROL Register is silently ignored; this is not a problem since the value is the correct one.

**Impact**
Undefined behavior and possible processor fault during system calls.

**Solution**

We cannot reverse the order of operations, because the PSP, PSPLIM cannot be written from nPRIV mode. 

As a result, we must ensure SWAP cannot occur during this sequence of operations.

### LINKED ISSUE #22720: armv8-m: userspace: some parts in userspace enter sequence need to be atomic
**Describe the bug**
A part of the execution sequence in z_arm_userspace_enter needs to prevent Zephyr from swapping -out and -in the current thread. This is required when building with support for Built-in stack overflow protection (ARMv8-M only).

When entering user space, a thread performs the following sequential actions:

a. Clears PSPLIM register
b. Sets PSP (back) to the user thread stack
c. Modifies mode variable to indicate nPRIV mode
d. Sets CONTROL.nPRIV to 1.

A context-switch occurring before (c) will set PSPLIM to the bottom of the PRIV stack. If this occurs after (b) the result will be stack-overflow.
 
**Expected behavior**
We expect z_arm_userspace_enter to perform without kernel crashing.

**Impact**
Under certain (corner-case) conditions z_arm_userspace_enter might crash.

**Additional context**
We need to prevent the kernel from switching -out and -in the thread, while it performs the "critical" execution sequence listed above.

### PR DESCRIPTION
**Pull request by ioannisg**
Fixed several bugs/issues for ARM Cortex-M, but contains some minor documentation updates and refactoring. In brief:

- Documents the exception mode for ARM Cortex-M (Documentation)
- Fixes race conditions for `mpu_buffer_validate()` calls
- Fixes race conditions and re-works the stack limit checking on ARMv8-M
- Enhances the protection via stack limit checking, enforcing it at all times, even during stack transitions
- Adds a "syscall-torture" test, to stress-test system calls in all supported architectures (witten by @andrewboie )

Fixes #22275 (for Cortex-M, but it seems fixed for other ARCHes)
Fixes #22685 
Fixes #22720

### CODE REVIEW

**Comment by andrewboie** [comment]
I can confirm that with this PR (which includes my syscall torture test) that the build passes.

`sanitycheck  -t userspace -p mps2_an385 -p mps2_an521`

File: arch/arm/core/aarch32/thread.c [hunk 1]
```diff
@@ -208,9 +208,17 @@ void configure_builtin_stack_guard(struct k_thread *thread)
 		__set_PSPLIM(0);
 		return;
 	}
-	u32_t guard_start = thread->arch.priv_stack_start ?
-			    (u32_t)thread->arch.priv_stack_start :
-			    (u32_t)thread->stack_obj;
+	/* Only configure PSPLIM to guard the privileged stack area, if
```
Comment (andrewboie) [inline arch/arm/core/aarch32/thread.c]: If the user thread overflows its own stack, won't it get an MPU violation anyway? I supposed the execption generated will be simpler to comprehend.
I'm OK with this as long as there logic to reprogram the PSPLIM location when going in/out of system calls.
We really need a test case to show that stack overflows during syscalls are caught properly, not sure if there is one.

File: arch/arm/core/aarch32/cortex_m/mpu/arm_mpu_v7_internal.h [hunk 2]
```diff
@@ -151,8 +151,16 @@ static inline u32_t mpu_region_get_size(u32_t index)
  */
 static inline int is_enabled_region(u32_t index)
 {
+	/* Lock IRQs to ensure RNR value is correct when reading RASR. */
```
Comment (andrewboie) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_mpu_v7_internal.h]: I suggest adding comments to other functions which use RNR/RASR/etc without locking interrupts, that they should be called with irqs locked.

File: arch/arm/core/aarch32/thread.c (hunk 1 above)
Comment (ioannisg) [reply arch/arm/core/aarch32/thread.c]: >> If the user thread overflows its own stack, won't it get an MPU violation anyway? I supposed the execption generated will be simpler to comprehend.

There is no MPU-based protection in this case; stack protection is done via stack-limit checking supported by the built-in feature in ARMv8-M.

>> I'm OK with this as long as there logic to reprogram the PSPLIM location when going in/out of system calls.

Yes there is, this was the main thing done in this PR; ensure PSPLIM is programmed at all times. (I guess that's a step towards functional safety...) Check the diff inside userspace.S.

>> We really need a test case to show that stack overflows during syscalls are caught properly, not sure if there is one.

We have that since Zephyr 2.0; it's inside tests/kernel/fatal
We have that for both MPU-based and SPLIM-based stack-protection.

Comment (andrewboie) [reply arch/arm/core/aarch32/thread.c]: > We have that since Zephyr 2.0; it's inside tests/kernel/fatal
> We have that for both MPU-based and SPLIM-based stack-protection.

It tests stack overflows for user and supervisor threads..but AFAICT it doesn't cover the scenario where we make a syscall, and the syscall overflows the privilege mode stack.

**Review by tyrantlizard77 — APPROVED** [review]

File: arch/arm/core/aarch32/thread.c (hunk 1 above)
Comment (ioannisg) [reply arch/arm/core/aarch32/thread.c]: Nope, it tests for system calls too, I wrote the test for the 2.0 release.

**Review by jhedberg — APPROVED** [review]

**Comment by ioannisg** [comment]
@nashif @galak might want to take a look on this one for the 2.2 release

**Comment by andrewboie** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/22691/commits/b07544ab78b69e04961058ba07250073f6158883 needs backporting to 1.14

**Comment by ioannisg** [comment]
> [b07544a](https://github.com/zephyrproject-rtos/zephyr/commit/b07544ab78b69e04961058ba07250073f6158883) needs backporting to 1.14

Not only this commit @andrewboie , I think we should backport the fixes around the PSPLIM updates, as well.

Not sure if we can merge the added tests, particularly the torture-test (for that we'd need to make sure it is passing for all ARCHEs)

**Comment by andrewboie** [comment]
> > [b07544a](https://github.com/zephyrproject-rtos/zephyr/commit/b07544ab78b69e04961058ba07250073f6158883) needs backporting to 1.14
> 
> Not only this commit @andrewboie , I think we should backport the fixes around the PSPLIM updates, as well.

Is armv8-m user mode even in 1.14? I don't see an mps2_an521 build target? I would not worry about this now. 

> Not sure if we can merge the added tests, particularly the torture-test (for that we'd need to make sure it is passing for all ARCHEs)

We have to fix the broken user mode on ARC and Cortex-M in the 1.14 branch. I'll deal with this.

**Comment by ioannisg** [comment]
> > > [b07544a](https://github.com/zephyrproject-rtos/zephyr/commit/b07544ab78b69e04961058ba07250073f6158883) needs backporting to 1.14
> > 
> > 
> > Not only this commit @andrewboie , I think we should backport the fixes around the PSPLIM updates, as well.
> 
> Is armv8-m user mode even in 1.14? I don't see an mps2_an521 build target? I would not worry about this now.
> 
> > Not sure if we can merge the added tests, particularly the torture-test (for that we'd need to make sure it is passing for all ARCHEs)
> 
> We have to fix the broken user mode on ARC and Cortex-M in the 1.14 branch. I'll deal with this.

v8-M user mode **is** supported in 1.14 (there's at least the nRF9160 and musca_a1 targets), but probaby not Qemu.

**Comment by andrewboie** [comment]
can you backport this PR then?

**Comment by ioannisg** [comment]
> can you backport this PR then?

The QEMU for ARMv8-M? Sure, I can. Aren't we strictly submitting bug-fixes, though?

**Comment by andrewboie** [comment]
> > can you backport this PR then?
> 
> The QEMU for ARMv8-M? Sure, I can. Aren't we strictly submitting bug-fixes, though?

No, what I'm asking is that *this PR* is backported to 1.14.
We are on the hook to backport bug fixes to that branch.

**Comment by ioannisg** [comment]
> > > can you backport this PR then?
> > 
> > 
> > The QEMU for ARMv8-M? Sure, I can. Aren't we strictly submitting bug-fixes, though?
> 
> No, what I'm asking is that _this PR_ is backported to 1.14.
> We are on the hook to backport bug fixes to that branch.

ah, right. Yeap, I will back port it manually, as soon as this is reviewed and merged to master
