### PR TITLE
drivers: ethernet: nxp_enet: Fix PHY configure for fixed-link config

### LINKED ISSUE #92399: <err> eth_nxp_enet_mac: phy_configure_link failed with error: -88
### Describe the bug

When a fixed link is configured, the `eth_nxp_enet` driver calls `ret = phy_configure_link(phy, speeds, 0);` (line 475), and it expects to receive `-ENOTSUP`. However, this behavior is likely broken after this [commit](https://github.com/zephyrproject-rtos/zephyr/commit/7505ef3f0425abbd482e20c44dff8d31c81845f4), because the `phy_configure_link` function now checks whether `DEVICE_API_GET(ethphy, dev)->cfg_link == NULL` and returns `-ENOSYS` instead. As a result, the driver's initialization fails, causing Ethernet to become non-functional.

### Regression

- [x] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell
<err> eth_nxp_enet_mac: phy_configure_link failed with error: -88
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ofirshe**
Update the driver to handle -ENOSYS from phy_configure_link(), which is now returned when the cfg_link callback is missing (e.g., in fixed-link PHYs).

Fixes [92399](https://github.com/zephyrproject-rtos/zephyr/issues/92399)

### CODE REVIEW

File: drivers/ethernet/eth_nxp_enet.c [hunk 1]
```diff
@@ -474,17 +474,17 @@ static int nxp_enet_phy_configure(const struct device *phy, uint8_t phy_mode)
 	/* Configure the PHY */
 	ret = phy_configure_link(phy, speeds, 0);
 
-	if (ret == -ENOTSUP) {
+	if (ret == -ENOSYS) {
```
Comment (maass-hamburg) [inline drivers/ethernet/eth_nxp_enet.c]: should test for both, as -ENOTSUP is still returned, if there is at least one other non fixed-link phy.

**Review by maass-hamburg — CHANGES_REQUESTED** [review]
Btw this code part is up for removal with https://github.com/zephyrproject-rtos/zephyr/pull/91572, but that will only be merged after the next release.

File: drivers/ethernet/eth_nxp_enet.c (hunk 1 above)
Comment (ofirshe) [reply drivers/ethernet/eth_nxp_enet.c]: fixed

**Review by maass-hamburg — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]
