### PR TITLE
Replace static_assert by BUILD_ASSERT_MSG

### LINKED ISSUE #11754: NRFX TWI driver does not compile with newlib
**Describe the bug**
When newlib C library is enabled the NRFX TWI driver fails with a build error.
Note that this will also impact TWIM version of the driver and NRFX QDEC driver.

Problem is caused by usage of ```static_assert``` in ```I2C_NRFX_TWI_DEVICE``` macro

Solution is to use ```BUILD_ASSERT_MSG``` instead.

**To Reproduce**
1. mkdir samples/sensor/ms5837/build
2. cd samples/sensor/ms5837/build
3. cmake -DBOARD=nrf52840_pca10056 -GNinja ..
4. ninja menuconfig -> enable newlib
5. ninja

**Expected behavior**
Build succeed 

**Environment (please complete the following information):**
 - OS: linux
 - Toolchain: Zephyr SDK 0.9.5
 - Commit: 3c4bb1012785fc7ae510585792ee1944d4827ccc

### PR DESCRIPTION
**Pull request by vanwinkeljan**
Replace static_assert in NRFX TWI, TWIM and QDEC drivers by
BUILD_ASSERT_MSG

fixes: #11754

Signed-off-by: Jan Van Winkel <jan.van_winkel@dxplore.eu>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

File: drivers/sensor/qdec_nrfx/qdec_nrfx.c [hunk 1]
```diff
@@ -91,9 +91,9 @@ static int qdec_nrfx_channel_get(struct device       *dev,
 	data->acc = 0;
 	irq_unlock(key);
 
-	static_assert(DT_NORDIC_NRF_QDEC_QDEC_0_STEPS > 0,
+	BUILD_ASSERT_MSG(DT_NORDIC_NRF_QDEC_QDEC_0_STEPS > 0,
 		      "only positive number valid");
```
Comment (Mierunski) [inline drivers/sensor/qdec_nrfx/qdec_nrfx.c]: Please align this line, so it looks this way:
```
BUILD_ASSERT_MSG(DT_NORDIC_NRF_QDEC_QDEC_0_STEPS > 0,
                 "only positive number valid");
```

File: drivers/sensor/qdec_nrfx/qdec_nrfx.c [hunk 2]
```diff
@@ -91,9 +91,9 @@ static int qdec_nrfx_channel_get(struct device       *dev,
...
-	static_assert(DT_NORDIC_NRF_QDEC_QDEC_0_STEPS <= 2148,
+	BUILD_ASSERT_MSG(DT_NORDIC_NRF_QDEC_QDEC_0_STEPS <= 2148,
 		      "overflow possible");
```
Comment (Mierunski) [inline drivers/sensor/qdec_nrfx/qdec_nrfx.c]: Same here

**Review by Mierunski — DISMISSED** [review]
Looks good, just small alignement fix

**Review by ioannisg — APPROVED** [review]
