### PR TITLE
drivers: clock_control: add on/off stubs to clock,agilex

### LINKED ISSUE #86062: `samples/hello_world` not working on `intel_socfpga_agilex_socdk/agilex`
**Describe the bug**
The Hello World sample stopped working on the `intel_socfpga_agilex_socdk/agilex` board target after 88830a3b. Reverting this commit makes the sample work again.

**To Reproduce**
1. west build -p -b intel_socfpga_agilex_socdk samples/hello_world
2. Run the sample as described in https://docs.zephyrproject.org/latest/boards/intel/socfpga/agilex_socdk/doc/index.html
3. See error

**Expected behavior**
The sample should output:
```
*** Booting Zephyr OS build v4.1.0-rc1-85-g31bd82de8983 ***
Hello World! intel_socfpga_agilex_socdk/agilex
```

**Impact**
Showstopper.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: e885c8c4

### PR DESCRIPTION
**Pull request by fkokosinski**
This PR fixes a regression caused by: 88830a3b.

Due to the stubs not being present in the clock ctrl driver, the ns16550 driver jumped to offset 0x0 when referring to `api->on`.

Fixes #86062.

### CODE REVIEW

File: drivers/clock_control/clock_agilex.c [hunk 1]
```diff
@@ -35,7 +35,19 @@ static int clk_get_rate(const struct device *dev,
...
 }
 
+static int clk_on_off(const struct device *dev,
+					     clock_control_subsys_t sys)
+{
+	ARG_UNUSED(dev);
+	ARG_UNUSED(sys);
+
+	/* On/off functionality is not supported */
+	return 0;
```
Comment (nordic-krch) [inline drivers/clock_control/clock_agilex.c:45]: shouldn't be -ENOTSUP?

Comment (fkokosinski) [reply drivers/clock_control/clock_agilex.c:45]: That's a tricky question, honestly, and it depends on how we look at trivial API calls implementations.

`-ENOTSUP` is defined as an error code for _unsupported values_: https://docs.zephyrproject.org/apidoc/latest/group__system__errno.html#ga91457bbf35f0f1085619a99423bb1f33, and there’s nothing really wrong with the `dev` or `sys` values that are passed through this call.

The `clock_control_on` call reserves negative return values for errors: https://docs.zephyrproject.org/apidoc/latest/group__clock__control__interface.html#gaec69b0989cefad79ffd5c92f060150b9

> Returns
>	0 on success, negative errno on failure.

Depending on how you look at this, one could argue that a trivial implementation is not really ending in a failure. We can of course add a `-ENOTSUP` here, and modify the NS16550 driver code to not error out upon receiving that errno from the clock control subsystem if that's what you think is better for the overall code organization.

Let me know what you think.

Comment (fabiobaltieri) [reply drivers/clock_control/clock_agilex.c:45]: Or maybe the API should return -ENOSYS if it's not implemented and then the caller can handle it in the same way as it handles `EALREADY`?

Anyway sorry folks, this should have been fixed before the release but I'm afraid it won't make the cut since there's still some ambiguity on the api, I've set the milestone to 4.2 and queued it for backport. Still open to discuss it if you can agree of how it should be fixed before EoD.

Comment (fkokosinski) [reply drivers/clock_control/clock_agilex.c]: @fabiobaltieri `-ENOSYS` sounds good. We've applied necessary changes to the NS16550 driver as well so that it handles `-ENOSYS` the same way it does `-EALREADY`.

Comment (fkokosinski) [reply drivers/clock_control/clock_agilex.c]: @fabiobaltieri Hard agree here. I've moved returning ENOSYS to the API header.

**Review by fabiobaltieri — APPROVED** [review]

**Comment by fkokosinski** [comment]
Hey @nordic-krch - could you PTAL at this PR? Thanks!

**Review by nordic-krch — APPROVED** [review]
