### PR TITLE
arch/xtensa: Clean up fatal error handling

### LINKED ISSUE #18140: xtensa passes NULL esf on fatal error
`xtensa_excintl_c()` and `z_irq_spurious()` in arch/xtensa/core/xtensa-asm2.c pass a NULL `esf` parameter to `z_xtensa_fatal_error()`. The expectation is that these should pass a valid exception stack frame pointer, which will allow dumping program state when the exception occurred.

The current dump_stack() function should be moved up to z_xtensa_fatal_error() and use the ESF for its information.

### PR DESCRIPTION
**Pull request by andyross**
Update the xtensa backend to work better with the new fatal error
architecture.  Move the stack frame dump (xtensa uses a variable-size
frame becuase we don't spill unused register windows, so it doesn't
strictly have an ESF struct) into z_xtensa_fatal_error().  Unify the
older exception logging with the newer one (they'd been sort of glomed
together in the recent rework), mostly using the asm2 code but with
the exception cause stringification and the PS register field
extraction from the older one.

Note that one shortcoming is that the way the dispatch code works, we
don't have access to the spilled frame from within the spurious error
handler, so this can't log the interrupted CPU state.  This isn't
fixable easily without adding overhead to every interrupt entry, so it
needs to stay the way it is for now.  Longer term we could exract the
caller frame from the window state and figure it out with some
elaborate assembly, I guess.

Fixes #18140

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

File: arch/xtensa/core/fatal.c [hunk 1]
```diff
@@ -78,49 +79,15 @@ static char *cause_str(unsigned int cause_code)
...
-	z_fatal_print("  INTLEVEL : %02d EXCM    : %d UM  : %d RING : %d WOE : %d",
-		      get_bits(0, 4, ps), get_bits(4, 1, ps),
-		      get_bits(5, 1, ps), get_bits(6, 2, ps),
-		      get_bits(18, 1, ps));
-#ifndef __XTENSA_CALL0_ABI__
-	z_fatal_print("  OWB      : %02d CALLINC : %d",
-		      get_bits(8, 4, ps), get_bits(16, 2, ps));
+#else
+	return "na";
 #endif
```
Comment (ceolin) [inline arch/xtensa/core/fatal.c]: shouldn't just return null if we don't have printk nor log available ?

Comment (andyross) [reply arch/xtensa/core/fatal.c]: Then I'd have to add extra code to optionally log this via z_fatal_print() (which in theory can exist even when printk/log don't) this instead of just printing the string it returns.  Seems like this is smaller and simpler.

File: arch/xtensa/core/fatal.c [hunk 2]
```diff
@@ -78,49 +79,15 @@ static char *cause_str(unsigned int cause_code)
...
-	z_fatal_print("Program state (PS):");
-	z_fatal_print("  INTLEVEL : %02d EXCM    : %d UM  : %d RING : %d WOE : %d",
-		      get_bits(0, 4, ps), get_bits(4, 1, ps),
-		      get_bits(5, 1, ps), get_bits(6, 2, ps),
-		      get_bits(18, 1, ps));
-#ifndef __XTENSA_CALL0_ABI__
-	z_fatal_print("  OWB      : %02d CALLINC : %d",
-		      get_bits(8, 4, ps), get_bits(16, 2, ps));
+#else
+	return "na";
```
Comment (dcpleung) [inline arch/xtensa/core/fatal.c]: probably need ARG_UNUSED(cause_code) in #else.

**Comment by andyross** [comment]
Rebased, add ARG_UNUSED()

**Review by ghost — APPROVED** [review]
