### PR TITLE
net: l2: ethernet: arp: Replace pending packet pointer with fifo

### LINKED ISSUE #50140: ARP handling causes dropped packets when multiple outgoing packets are queued
**Describe the bug**
The current ARP system in the zephyr networking stack has a very odd choice of operation, it will send an outgoing ARP request if an entry is not present, however it does not support assigning multiple packets to a handler, so in the case that a device sends multiple packets at once, e.g. 5, there will be 5 ARP requests sent out, when the first response is received, the queued first packet is sent out, the remaining 4 packets are completely ignored and eventually dropped.

**To Reproduce**
Use a networking application which sends multiple network packets in a go to a device not in the ARP table

**Expected behavior**
For one ARP request to be sent and when the response is received, for ALL pending packets that it applies to, to be sent out

**Impact**
Showstopper. I am actually amazed that there are products using the zephyr networking stack.

**Environment (please complete the following information):**
 - OS: Linux
 - Commit SHA or Version used: f1bafda5e594cc13a4efa1fbc44057104f89f8b6

### PR DESCRIPTION
**Pull request by thedjnK**
This fixes a bug with ARP and multiple outgoing packets with an IP that needed to be resolved, causing the first packet to go out and all others to be dropped after the timeout by having a FIFO of pending packets instead of a single packet.

Fixes #50140

I wonder if the fifo accesses should be semaphore protected e.g. to prevent an edge case of a received ARP being processed and an outgoing packet being queued at the same time?

### CODE REVIEW

File: subsys/net/l2/ethernet/arp.h [hunk 1]
```diff
@@ -54,10 +54,8 @@ struct arp_entry {
 	uint32_t req_start;
 	struct net_if *iface;
 	struct in_addr ip;
-	union {
-		struct net_pkt *pending;
-		struct net_eth_addr eth;
-	};
+	struct net_eth_addr eth;
+	struct k_fifo pending_queue;
```
Comment (rlubos) [inline subsys/net/l2/ethernet/arp.h:58]: Couldn't those still be in a union?

**Review by rlubos — COMMENTED** [review]
> I wonder if the fifo accesses should be semaphore protected e.g. to prevent an edge case of a received ARP being processed and an outgoing packet being queued at the same time?

It seems to me that not only the fifo should be protected with a mutex, but the entire `arp_update()` procedure. There is a short period, when the `arp_entry` is removed from `arp_pending_entries` but still not present in `arp_table`. If a `net_arp_prepare()` is issued by the Ethernet L2 in between, the whole ARP procedure would start over, while it could be avoided in the `arp_update` had a chance to complete.

File: subsys/net/l2/ethernet/arp.h (hunk 1 above)
Comment (nordicjm) [reply subsys/net/l2/ethernet/arp.h:58]: They can, yes. As part of a future update, I think it makes sense to rewrite this entirely, an ARP entry should only be storing the information it needs and an ARP request should only be storing the information it needs i.e. 2 different lists rather than combining them into 1.

Comment (rlubos) [reply subsys/net/l2/ethernet/arp.h:58]: Good point

**Review by rlubos — DISMISSED** [review]
LGTM

**Review by jukkar — COMMENTED** [review]
Minor nit about commit subject, could you please change it to
`net: arp: Replace pending packet pointer with fifo` 
as "l2: ethernet" is redundant information and not needed here.

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
