### PR TITLE
tests: posix: common: clock: remove poorly conditioned tests

### LINKED ISSUE #35703: posix_apis: fails at test_posix_realtime for mimxrt1024_evk
**Describe the bug**

    Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/clock.c:75: test_posix_realtime: (rts.tv_nsec not equal to mts.tv_nsec)

only this board has such issue, all other rt1xxx series boards are OK.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=board\mimxrt1024_evk
3. make

**Expected behavior**
pass

**Impact**
posix realtime

**Logs and console output**

```

*** Booting Zephyr OS build v2.6.0-rc1-323-gae4fb20f6733  ***

Running test suite posix_apis

===================================================================

START - test_posix_pthread_execution

Thread 0 starting with scheduling policy 0 & priority 15

Thread 1 starting with scheduling policy 0 & priority 15

Thread 2 starting with scheduling policy 0 & priority 15

Bounce test OK

Barrier test OK

 PASS - test_posix_pthread_execution in 0.643 seconds

===================================================================

START - test_posix_pthread_error_condition

 PASS - test_posix_pthread_error_condition in 0.1 seconds

===================================================================

START - test_posix_pthread_termination

Thread 0 starting with a priority of 4

Cancelling thread 0

Thread 1 starting with a priority of 3

Cancelling thread 1

Thread 1 could not be cancelled

Thread 2 starting with a priority of 2

Cancelling thread 2

Thread 3 starting with a priority of 1

Cancelling thread 3

Thread 3 could not be cancelled

 PASS - test_posix_pthread_termination in 1.14 seconds

===================================================================

START - test_posix_multiple_threads_single_key



Different threads set different values to same key:

thread 0: set value = -2147477408 and retrieved value = -2147477408

thread 1: set value = -2147477184 and retrieved value = -2147477184



 PASS - test_posix_multiple_threads_single_key in 0.17 seconds

===================================================================

START - test_posix_single_thread_multiple_keys



Single thread associates its value with different keys:

key 0: set value = -2147476984 and retrieved value = -2147476984

key 1: set value = -2147476984 and retrieved value = -2147476984



 PASS - test_posix_single_thread_multiple_keys in 0.17 seconds

===================================================================

START - test_posix_clock

POSIX clock APIs

POSIX clock APIs test done

 PASS - test_posix_clock in 2.5 seconds

===================================================================

START - test_posix_semaphore

 PASS - test_posix_semaphore in 5.1 seconds

===================================================================

START - test_posix_normal_mutex

mutex lock is taken

 PASS - test_posix_normal_mutex in 0.103 seconds

===================================================================

START - test_posix_recursive_mutex

recrusive mutex lock is taken

 PASS - test_posix_recursive_mutex in 0.3 seconds

===================================================================

START - test_posix_mqueue

 PASS - test_posix_mqueue in 0.11 seconds

===================================================================

START - test_posix_realtime

POSIX clock set APIs



    Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/clock.c:75: test_posix_realtime: (rts.tv_nsec not equal to mts.tv_nsec)

Nanoseconds not equal

 FAIL - test_posix_realtime in 0.17 seconds

===================================================================

START - test_posix_timer

POSIX timer test

Timer fires every 0 secs and  100000000 nsecs

Time remaining to fire 0 secs and  899000000 nsecs

Handler Signal value :20 for 1 times

Handler Signal value :20 for 2 times

Handler Signal value :20 for 3 times

Handler Signal value :20 for 4 times

Handler Signal value :20 for 5 times

Handler Signal value :20 for 6 times

Handler Signal value :20 for 7 times

Handler Signal value :20 for 8 times

Handler Signal value :20 for 9 times

Handler Signal value :20 for 10 times

Handler Signal value :20 for 11 times

Handler Signal value :20 for 12 times

 PASS - test_posix_timer in 2.111 seconds

===================================================================

START - test_posix_rw_lock



main acquire WR lock and 3 threads acquire RD lock

Thread 2 scheParent thread releasing WR lock

duling policParent thread acquiring WR lock again

Parent thread acquired WR lock again

y = 1 & prioParent thread releasing WR lock again



3 threads acquire WR lock

Main thread acquiring RD lock

Main thread acquired RD lock

rity 3 startMain thread releasing RD lock

ed

Thread 2 got RD lock

Thread 1 scThread 2 releasing RD lock

Thread 2 acquiring WR lock

Thread 2 acquired WR lock

heduling polThread 2 releasing WR lock

icy = 1 & priority 2 started

Thread 1 got RD lock

Thread 0 schThread 1 releasing RD lock

Thread 1 acquiring WR lock

Thread 1 acquired WR lock

eduling poliThread 1 releasing WR lock

cy = 1 & priority 1 started

Thread 0 got RD lock

Thread 0 releasing RD lock

Thread 0 acquiring WR lock

Thread 0 acquired WR lock

Thread 0 releasing WR lock

 PASS - test_posix_rw_lock in 0.79 seconds

===================================================================

START - test_nanosleep_NULL_NULL

 PASS - test_nanosleep_NULL_NULL in 0.1 seconds

===================================================================

START - test_nanosleep_NULL_notNULL

 PASS - test_nanosleep_NULL_notNULL in 0.1 seconds

===================================================================

START - test_nanosleep_notNULL_NULL

 PASS - test_nanosleep_notNULL_NULL in 0.1 seconds

===================================================================

START - test_nanosleep_notNULL_notNULL

 PASS - test_nanosleep_notNULL_notNULL in 0.1 seconds

===================================================================

START - test_nanosleep_req_is_rem

 PASS - test_nanosleep_req_is_rem in 0.1 seconds

===================================================================

START - test_nanosleep_n1_0

 PASS - test_nanosleep_n1_0 in 0.1 seconds

===================================================================

START - test_nanosleep_0_n1

 PASS - test_nanosleep_0_n1 in 0.1 seconds

===================================================================

START - test_nanosleep_n1_n1

 PASS - test_nanosleep_n1_n1 in 0.1 seconds

===================================================================

START - test_nanosleep_0_1

 PASS - test_nanosleep_0_1 in 0.1 seconds

===================================================================

START - test_nanosleep_0_1001

 PASS - test_nanosleep_0_1001 in 0.1 seconds

===================================================================

START - test_nanosleep_0_500000000

 PASS - test_nanosleep_0_500000000 in 0.501 seconds

===================================================================

START - test_nanosleep_1_0

 PASS - test_nanosleep_1_0 in 1.1 seconds

===================================================================

START - test_nanosleep_1_1

 PASS - test_nanosleep_1_1 in 1.1 seconds

===================================================================

START - test_nanosleep_1_1001

 PASS - test_nanosleep_1_1001 in 1.1 seconds

===================================================================

START - test_posix_pthread_create_negative

 PASS - test_posix_pthread_create_negative in 0.1 seconds

===================================================================

Test suite posix_apis failed.

===================================================================

PROJECT EXECUTION FAILED

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used:  v2.6.0-rc1-323-gae4fb20f6733

### PR DESCRIPTION
**Pull request by cfriedt**
The test assumed initial equality between CLOCK_MONOTONIC and CLOCK_REALTIME and also assumed coarse granularity for each clock. Neither of those assumptions are solid. 

Furthermore, the test failed on multiple vendor boards which caused some concern.

Remove the poorly conditioned tests and remove some comments / printks.

Fixes #35703

### CODE REVIEW

File: tests/posix/common/src/clock.c [hunk 1]
```diff
@@ -46,34 +46,16 @@ void test_posix_clock(void)
...
-	 */
-	k_usleep(1);
-
 	ret = clock_gettime(CLOCK_MONOTONIC, &mts);
 	zassert_equal(ret, 0, "Fail to get monotonic clock");
 
 	ret = clock_gettime(CLOCK_REALTIME, &rts);
 	zassert_equal(ret, 0, "Fail to get realtime clock");
 
-	zassert_equal(rts.tv_sec, mts.tv_sec, "Seconds not equal");
```
Comment (dleach02) [inline tests/posix/common/src/clock.c:74]: I'm not sure I would remove this one because if the seconds doesn't match then there is likely a problem that needs to be addressed or highlighted. The primary problem on this test case is the nanoseconds where the TICK counter has a good chance of incrementing between the two calls to clock_gettime() so the assumption that the calls would be equal is faulty. Having the test consider this would be useful but maybe we just drop that equal test or do what I suggested in the bug report and do a diff test.

File: tests/posix/common/src/clock.c [hunk 2]
```diff
@@ -46,34 +46,16 @@ void test_posix_clock(void)
...
-	/* Make sure the realtime and monotonic clocks start out the
-	 * same.  This is not true on posix and where there is a
-	 * realtime clock, so don't keep this code.
-	 */
-
 	int ret;
 	struct timespec rts, mts;
 	struct timeval tv;
 
-	printk("POSIX clock set APIs\n");
```
Comment (dleach02) [inline tests/posix/common/src/clock.c:58]: why are you removing this?

File: tests/posix/common/src/clock.c (hunk 1 above)
Comment (cfriedt) [reply tests/posix/common/src/clock.c:74]: POSIX has no requirement that the seconds counter be equal between CLOCK_MONOTONIC and CLOCK_REALTIME and they most likely will be completely different.

It just happens to the the case in the implementation that they both start at zero.

So it's testing out an implementation detail rather than expected behaviour.

It's a poorly conditioned test but also is something that should not be relied on - e.g. if CLOCK_REALTIME were ever connected to an RTC the assumption would be immediately broken.

File: tests/posix/common/src/clock.c (hunk 2 above)
Comment (cfriedt) [reply tests/posix/common/src/clock.c:58]: It seems weird to have additional printk's here especially when it isn't simply testing clock_set but also clock_get and other calls.

**Review by dleach02 — APPROVED** [review]

**Review by nashif — APPROVED** [review]
