### PR TITLE
drivers: timer : cortex_m_systick MAX_TICKS protection

### LINKED ISSUE #36766: tests-ci :kernel.tickless.concept.tickless_slice : test failed
**Describe the bug**
kernel.tickless.concept.tickless_slice test is failed on zephyr-v2.6.0-734-gc1cff7558928 on mimxrt1170_evk_cm7

see logs for details

**To Reproduce**
1. 
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt1170_evk_cm7  --sub-test kernel.tickless
```
2. See error

**Expected behavior**
test pass

**Impact**

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.6.0-734-gc1cff7558928  ***
Running test suite tickless_concept
===================================================================
START - test_tickless_sysclock
time 10, 8600
time 8610, 17200
PASS - test_tickless_sysclock in 4.267 seconds
===================================================================
START - test_tickless_slice
elapsed selapsed slice 4290, expected: <100, 110>
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/tickless/tickless_concept/src/main.c:58: thread_tslice: t <= SLICE_SIZE_LIMIT is false
elapsed slice 4300, expected: <100, 110>
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/tickless/tickless_concept/src/main.c:58: thread_tslice: t <= SLICE_SIZE_LIMIT is false
elapsed slice 0, expected: <100, 110>
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/tickless/tickless_concept/src/main.c:56: thread_tslice: t >= SLICE_SIZE is false
lice 8600, expected: <100, 110>
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/tickless/tickless_concept/src/main.c:58: thread_tslice: t <= SLICE_SIZE_LIMIT is false
FAIL - test_tickless_slice in 4.228 seconds
===================================================================
Test suite tickless_concept failed.
===================================================================
PROJECT EXECUTION FAILED

    
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: zephyr-v2.6.0-734-gc1cff7558928

### PR DESCRIPTION
**Pull request by hakehuang**
when CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC set to 960M and CONFIG_SYS_CLOCK_TICKS_PER_SEC set to 100
the MAX_TICKS will be zero or even a negative value, which is not expected, at this time the COUNTER_MAX is
so need add a protection here

fixes: #36766

there used to be a workaround, not a fix,

either change the CONFIG_SYS_CLOCK_TICKS_PER_SEC=200 or
CONFIG_PM to set the CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC to 32678

### CODE REVIEW

**Comment by hakehuang** [comment]
test on mimxrt1170_evk without default sys_tick settings
```
*** Booting Zephyr OS build v4.0.0-2778-g1b70bfa14e28 ***
Running TESTSUITE tickless_concept
===================================================================
START - test_tickless_slice
elapsed slice 110, expected: <100, 110>
elapsed slice 100, expected: <100, 110>
elapsed slice 100, expected: <100, 110>
elapsed slice 100, expected: <100, 110>
 PASS - test_tickless_slice in 0.607 seconds
===================================================================
START - test_tickless_sysclock
time 640, 850
time 860, 1060
 PASS - test_tickless_sysclock in 0.426 seconds
===================================================================
TESTSUITE tickless_concept succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [tickless_concept]: pass = 2, fail = 0, skip = 0, total = 2 duration = 1.033 seconds
 - PASS - [tickless_concept.test_tickless_slice] duration = 0.607 seconds
 - PASS - [tickless_concept.test_tickless_sysclock] duration = 0.426 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL

```

File: drivers/timer/cortex_m_systick.c [hunk 1]
```diff
@@ -17,7 +17,9 @@
 
 #define CYC_PER_TICK (sys_clock_hw_cycles_per_sec()	\
 		      / CONFIG_SYS_CLOCK_TICKS_PER_SEC)
-#define MAX_TICKS ((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)
+/* add MAX_TICKS protection */
+#define _COUNTER_MAX ((COUNTER_MAX > (2 * CYC_PER_TICK)) ? COUNTER_MAX : (2 * CYC_PER_TICK))
+#define MAX_TICKS ((k_ticks_t)(_COUNTER_MAX / CYC_PER_TICK) - 1)
```
Comment (andyross) [inline drivers/timer/cortex_m_systick.c:22]: This seems clumsy.  Can't you add a BUILD_ASSERT() in 64 bit precision instead?

**Comment by gramsay0** [comment]
@hakehuang here's an old attempt at this that may be a useful reference: https://github.com/zephyrproject-rtos/zephyr/commit/5cbf8d838e399dacf14d879a6adff2f4cdf8611a https://github.com/zephyrproject-rtos/zephyr/pull/66601

**Comment by hakehuang** [comment]
> @hakehuang here's an old attempt at this that may be a useful reference: [5cbf8d8](https://github.com/zephyrproject-rtos/zephyr/commit/5cbf8d838e399dacf14d879a6adff2f4cdf8611a) #66601

I guess the pr attempts to assert the setting in return we still need to increate the CONFIG_SYS_CLOCK_TICKS_PER_SEC to avoid this issue, and my attempt to still use the old setting, but downgrade the accuracy.

File: drivers/timer/cortex_m_systick.c (hunk 1 above)
Comment (hakehuang) [reply drivers/timer/cortex_m_systick.c:22]: build_assert only assert during building, it does not resolve the problem, so if we want to CONFIG_SYS_CLOCK_TICKS_PER_SEC to be 100 and still running in that high frequency(960M). let me try to find a better way to implement this.

**Review by andyross — COMMENTED** [review]
Driving back by.  Seems like the real bug here is that "- 1" subexpression that's rolling over when the quotient is zero.  Why is that there?  It's not mathematically correct.  Is it to handle latency slop in the reset code maybe?

Nonetheless if you want the expression to be safe, it's IMHO more clearly expressed as something like this, which clamps the quotient before the subtraction to guarantee no rollover:

```c
#define MAX_TICKS CLAMP(COUNTER_MAX / CYC_PER_TICK, 1, COUNTER_MAX) - 1
```

But your version seems fine too.  I'm just concerned about that term and where it came from.

**Comment by andyross** [comment]
Heh, it was my doing, back in 2018 during the timer rewrites: see commit c535300539611751a56eef32b1ed1ea7a8bfcc57

I think it's just been carried along voodoo-style ever since.  It's harmless (except for the possibility of rollover at high clock rates), but I really don't think it's needed.  Might be worth spinning a version that simply removes that subtraction and check that nothing breaks.

Basically I think the root cause here is a bug I wrote six years ago. :)

**Comment by andyross** [comment]
Also, just to be clear, the configuration being managed here is pathological: the clock rates is so high and the tick rate so low that it's not possible to deliver interrupts that slowly from the paltry 24 bit SysTick counter.  Such a configuration basically has no control over timer interrupt frequency and would be **much** better served with a regular tick interrupt (which is what it's getting anyway) that avoids all the runtime complexity.

**Comment by hakehuang** [comment]
> Also, just to be clear, the configuration being managed here is pathological: the clock rates is so high and the tick rate so low that it's not possible to deliver interrupts that slowly from the paltry 24 bit SysTick counter. Such a configuration basically has no control over timer interrupt frequency and would be **much** better served with a regular tick interrupt (which is what it's getting anyway) that avoids all the runtime complexity.

@andyross will you propose a consolidate solution? my fix is to use the maximum of the 24bit counter if the original setting exceed. I can close my PR, if so. Thanks for checking.

**Review by andyross — DISMISSED** [review]
To be clear: I don't think there's anything wrong with this fix.  It's just that (1) it's  working around a rollover condition that shouldn't have been there to begin with, just to (2) handle a pathological case where "the timer can't even count as high as one tick".

I don't know the Right solution there, but I guess in my head it would look nicer as a BUILD_ASSERT() that produces a "Tickless does nothing here, use a ticked kernel" error or something.

**Comment by hakehuang** [comment]
> (2) handle a pathological case where "the timer can't even count as high as one tick".
> 
> I don't know the Right solution there, but I guess in my head it would look nicer as a BUILD_ASSERT() that produces a "Tickless does nothing here, use a ticked kernel" error or something.

I add a message to show this, as warning will break CI.

**Comment by hakehuang** [comment]
@andyross please help to review again, thanks.

**Review by andyross — DISMISSED** [review]
Looks great here.

**Comment by hakehuang** [comment]
@teburd please help to check thanks

**Comment by hakehuang** [comment]
@teburd please help to review

**Comment by golowanow** [comment]
@hakehuang - FYI https://github.com/zephyrproject-rtos/zephyr/issues/84051#issuecomment-2594005845

**Comment by hakehuang** [comment]
> @hakehuang - FYI [#84051 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/84051#issuecomment-2594005845)

does this pr fix your issue?

**Comment by hakehuang** [comment]
@teburd can you help to  review this? thanks

**Comment by golowanow** [comment]
> > @hakehuang - FYI [#84051 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/84051#issuecomment-2594005845)
> 
> does this pr fix your issue?

together with #84050 they resolve both overflows and timing instability like these:
```
Time Measurements for multiq sched queues
Timing results: Clock frequency: 25 MHz
REC: sched.add.thread.ReadyQ_tail.min         - Add threads of decreasing priority, min.           :     387 cycles ,   15480 ns :
REC: sched.add.thread.ReadyQ_tail.max         - Add threads of decreasing priority, max.           : 4278577 cycles , 171143080 ns :
REC: sched.add.thread.ReadyQ_tail.avg         - Add threads of decreasing priority, avg.           :  384082 cycles , 15363280 ns :
REC: sched.add.thread.ReadyQ_tail.stddev      - Add threads of decreasing priority, stddev.        : 1220073 cycles , 48802920 ns :
ReadyQ.add.to.tail.0000.waiters          - Add thread of priority (0)     : 4261800 cycles , 170472023 ns
ReadyQ.add.to.tail.0001.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
ReadyQ.add.to.tail.0002.waiters          - Add thread of priority (0)     :     387 cycles ,    15490 ns
ReadyQ.add.to.tail.0003.waiters          - Add thread of priority (0)     :     387 cycles ,    15490 ns
ReadyQ.add.to.tail.0004.waiters          - Add thread of priority (0)     : 4261800 cycles , 170472000 ns
ReadyQ.add.to.tail.0005.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
ReadyQ.add.to.tail.0006.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
```

**Comment by hakehuang** [comment]
> > > @hakehuang - FYI [#84051 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/84051#issuecomment-2594005845)
> > 
> > 
> > does this pr fix your issue?
> 
> together with #84050 they resolve both overflows and timing instability like these:
> 
> ```
> Time Measurements for multiq sched queues
> Timing results: Clock frequency: 25 MHz
> REC: sched.add.thread.ReadyQ_tail.min         - Add threads of decreasing priority, min.           :     387 cycles ,   15480 ns :
> REC: sched.add.thread.ReadyQ_tail.max         - Add threads of decreasing priority, max.           : 4278577 cycles , 171143080 ns :
> REC: sched.add.thread.ReadyQ_tail.avg         - Add threads of decreasing priority, avg.           :  384082 cycles , 15363280 ns :
> REC: sched.add.thread.ReadyQ_tail.stddev      - Add threads of decreasing priority, stddev.        : 1220073 cycles , 48802920 ns :
> ReadyQ.add.to.tail.0000.waiters          - Add thread of priority (0)     : 4261800 cycles , 170472023 ns
> ReadyQ.add.to.tail.0001.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
> ReadyQ.add.to.tail.0002.waiters          - Add thread of priority (0)     :     387 cycles ,    15490 ns
> ReadyQ.add.to.tail.0003.waiters          - Add thread of priority (0)     :     387 cycles ,    15490 ns
> ReadyQ.add.to.tail.0004.waiters          - Add thread of priority (0)     : 4261800 cycles , 170472000 ns
> ReadyQ.add.to.tail.0005.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
> ReadyQ.add.to.tail.0006.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
> ```

oh, that's a different issue, the max_tick can not be zero which is this PR to resolve

**Comment by hakehuang** [comment]
@golowanow can you help to review and kindly approve this? @teburd seems not interest this area anymore

File: drivers/timer/cortex_m_systick.c [hunk 2]
```diff
@@ -17,9 +17,15 @@
 
 #define CYC_PER_TICK (sys_clock_hw_cycles_per_sec()	\
 		      / CONFIG_SYS_CLOCK_TICKS_PER_SEC)
-#define MAX_TICKS ((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)
+/* add MAX_TICKS protection */
+#define _MAX_TICKS ((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)
+#define MAX_TICKS ((_MAX_TICKS > 0) ? _MAX_TICKS : 1)
```
Comment (golowanow) [inline drivers/timer/cortex_m_systick.c:22]: I wonder are there configurations possible without `CONFIG_TIMEOUT_64BIT`, so `_MAX_TICKS` will be always positive here, isn't it? 

https://github.com/zephyrproject-rtos/zephyr/blob/09991d526a58f8a51ed9c59480b98a4f30c2053d/include/zephyr/sys_clock.h#L45-L49

Comment (hakehuang) [reply drivers/timer/cortex_m_systick.c:22]: @golowanow , you are right, update with
#define _MAX_TICKS (int)((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)

**Comment by hakehuang** [comment]
@andyross , @golowanow  please help to review and kindly approve. Thanks

File: drivers/timer/cortex_m_systick.c (hunk 2 above)
Comment (golowanow) [reply drivers/timer/cortex_m_systick.c:22]: >  (int)((k_ticks_t)

this type casting to int looks suspicious to me: does it  work correctly for both 32 and 64 bit k_ticks_t ?

Comment (hakehuang) [reply drivers/timer/cortex_m_systick.c:22]: @golowanow , for 32 bit k_ticks_t it is uint32_t, and it is not likely to be such scenario that COUNTER_MAX / CYC_PER_TICK > 0x80000000. for 64 bit it is already int.

**Review by golowanow — DISMISSED** [review]

**Comment by hakehuang** [comment]
@andyross can you help to review again. just a small change on 32 bit compatible. Thanks

**Comment by hakehuang** [comment]
@andyross please help to review

**Comment by hakehuang** [comment]
@andyross can you help to approve? there is only nick change since you last review. Thanks

**Comment by hakehuang** [comment]
@andyross please help to review, thanks

**Comment by dleach02** [comment]
Andy previously stated he was okay with this change.

**Review by dleach02 — DISMISSED** [review]

**Review by andyross — DISMISSED** [review]
Still good here.  Sorry this sat for so long.

File: drivers/timer/cortex_m_systick.c [hunk 3]
```diff
@@ -17,9 +17,15 @@
...
 #define CYC_PER_TICK (sys_clock_hw_cycles_per_sec()	\
 		      / CONFIG_SYS_CLOCK_TICKS_PER_SEC)
-#define MAX_TICKS ((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)
+/* add MAX_TICKS protection */
+#define _MAX_TICKS (int)((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)
+#define MAX_TICKS ((_MAX_TICKS > 0) ? _MAX_TICKS : 1)
 #define MAX_CYCLES (MAX_TICKS * CYC_PER_TICK)
 
+#if (COUNTER_MAX / CYC_PER_TICK) == 1
+#pragma message("tickless doesn nothing as CONFIG_SYS_CLOCK_TICKS_PER_SEC too low")
```
Comment (teburd) [inline drivers/timer/cortex_m_systick.c]:
```suggestion
#pragma message("tickless does nothing as CONFIG_SYS_CLOCK_TICKS_PER_SEC too low")
```

**Review by teburd — DISMISSED** [review]
Minor typo and absolutely not a blocker, otherwise looks good to me. Sorry I didn't see this before

**Comment by hakehuang** [comment]
update pre @teburd  comments on warning message.

the CI seems crashed @stephanosio
```
INFO    - 1) sample.kernel.synchronization on qomu/quicklogic_eos_s3 error (Build failure - error: missing binary operator before token "61440000")
INFO    - 2) sample.drivers.fpga_controller on quick_feather/quicklogic_eos_s3 error (Build failure - error: missing binary operator before token "61440000")
INFO    - 3) sample.drivers.fpga_controller.shell on quick_feather/quicklogic_eos_s3 error (Build failure - error: missing binary operator before token "61440000")
INFO    - 4) sample.kernel.synchronization on quick_feather/quicklogic_eos_s3 error (Build failure - error: missing binary operator before token "61440000")
INFO    - 5) sample.kernel.synchronization on ra8d1_vision_board/r7fa8d1bhecbd error (Build failure - error: missing binary operator before token "480000000")
INFO    - 6) sample.kernel.synchronization on rak3172/stm32wle5xx error (Build failure - error: missing binary operator before token "48000000")
INFO    - 7) sample.kernel.synchronization on rddrone_fmuk66/mk66f18 error (Build failure - error: missing binary operator before token "160000000")
INFO    - 8) drivers.spi.loopback.rtio on robokit1/same70q21b error (Build failure - error: missing binary operator before token "300000000")
INFO    - 9) sample.kernel.synchronization on robokit1/same70q21b error (Build failure - error: missing binary operator before token "300000000")
INFO    - 10) sample.sensor.thermometer on robokit1/same70q21b error (Build failure - error: missing binary operator before token "300000000")
```

**Comment by stephanosio** [comment]
> the CI seems crashed @stephanosio

@hakehuang It is a real problem caught by CI. See the raw logs:

```
2025-06-27T03:29:16.3211774Z In file included from <command-line>:
2025-06-27T03:29:16.3212535Z /__w/zephyr/zephyr/twister-out/mimxrt1180_evk_mimxrt1189_cm7/zephyr/samples/synchronization/sample.kernel.synchronization/zephyr/include/generated/zephyr/autoconf.h:5:44: error: missing binary operator before token "792000000"
2025-06-27T03:29:16.3213253Z     5 | #define CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC 792000000
2025-06-27T03:29:16.3213636Z       |                                            ^~~~~~~~~
2025-06-27T03:29:16.3214074Z /__w/zephyr/zephyr/include/zephyr/sys/time_units.h:82:49: note: in expansion of macro 'CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC'
2025-06-27T03:29:16.3214594Z    82 | #define sys_clock_hw_cycles_per_sec() (uint32_t)CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC
2025-06-27T03:29:16.3215022Z       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2025-06-27T03:29:16.3215435Z /__w/zephyr/zephyr/drivers/timer/cortex_m_systick.c:20:23: note: in expansion of macro 'sys_clock_hw_cycles_per_sec'
2025-06-27T03:29:16.3215906Z    20 | #define CYC_PER_TICK (sys_clock_hw_cycles_per_sec()     \
2025-06-27T03:29:16.3216256Z       |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2025-06-27T03:29:16.3216678Z /__w/zephyr/zephyr/drivers/timer/cortex_m_systick.c:27:20: note: in expansion of macro 'CYC_PER_TICK'
2025-06-27T03:29:16.3217098Z    27 | #if (COUNTER_MAX / CYC_PER_TICK) == 1
2025-06-27T03:29:16.3217392Z       |                    ^~~~~~~~~~~~
2025-06-27T03:29:16.3217681Z ninja: build stopped: subcommand failed.
```

**Comment by hakehuang** [comment]
> @hakehuang It is a real problem caught by CI. See the raw logs:

this is caused by
```
commit 98dba7da7ca536456594e57eca7fe89b2041c411
Author: Anisetti Avinash Krishna <anisetti.avinash.krishna@intel.com>
Date:   Mon Mar 24 15:31:03 2025 +0530

    include: zephyr: sys: time_units: Type cast SYS_CLOCK_HW_CYCLES_PER_SEC

    Type case CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC to uint32_t
    while defining sys_clock_hw_cycles_per_sec_runtime_get()
    to extend the range of frequency to 0xffffffff.

    Signed-off-by: Anisetti Avinash Krishna <anisetti.avinash.krishna@intel.com>

diff --git a/include/zephyr/sys/time_units.h b/include/zephyr/sys/time_units.h
index 4e57120a289..1b08e4c9617 100644
--- a/include/zephyr/sys/time_units.h
+++ b/include/zephyr/sys/time_units.h
@@ -79,7 +79,7 @@ static inline int z_impl_sys_clock_hw_cycles_per_sec_runtime_get(void)
 #if defined(CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME)
 #define sys_clock_hw_cycles_per_sec() sys_clock_hw_cycles_per_sec_runtime_get()
 #else
-#define sys_clock_hw_cycles_per_sec() CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC
+#define sys_clock_hw_cycles_per_sec() (uint32_t)CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC
 #endif

```

with this change `sys_clock_hw_cycles_per_sec()` can't be used in another macro, always report 
```
missing binary operator before token
```

I update the usage in my change, to avoid use this macro.

File: drivers/timer/cortex_m_systick.c [hunk 4]
```diff
@@ -17,11 +17,23 @@
...
+#if defined(CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME)
+extern unsigned int z_clock_hw_cycles_per_sec;
+#define CYC_PER_TICK (z_clock_hw_cycles_per_sec/CONFIG_SYS_CLOCK_TICKS_PER_SEC)
+#else
+#define CYC_PER_TICK (CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC/CONFIG_SYS_CLOCK_TICKS_PER_SEC)
+#endif
+
+/* add MAX_TICKS protection */
+#define _MAX_TICKS (int)((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)
+#define MAX_TICKS ((_MAX_TICKS > 0) ? _MAX_TICKS : 1)
```
Comment (gramsay0) [inline drivers/timer/cortex_m_systick.c:30]: Would it make sense to do an assert here, rather than truncate to 1?

It seems like you could end up in odd situations where `k_msleep()` might sleep for an order of magnitude longer than requested.
(As `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is also used in `Z_HZ_ticks` -> `k_ms_to_ticks_ceil32` -> `Z_TIMEOUT_MS` -> `k_msleep`)

Disclaimer: I also attempted a fix a while back https://github.com/zephyrproject-rtos/zephyr/commit/5cbf8d838e399dacf14d879a6adff2f4cdf8611a

Comment (hakehuang) [reply drivers/timer/cortex_m_systick.c:30]: @gramsay0, as the line 28 commented, we expect that if the CYC_PER_TICK is too large to fit into the systick, then we automatically set it to 1. I used to add a assert, but this will block the CI, as CI takes warn as failure rule. I would suggest that the clock system document such limitations.

Comment (gramsay0) [reply drivers/timer/cortex_m_systick.c:30]: Maybe that warning **_is_** a failure?

IMO it's a misconfiguration that can be caught at build time, rather than clamping the value and hoping the device will limp along

Comment (hakehuang) [reply drivers/timer/cortex_m_systick.c:30]: in twister it enable the compiler feature. I would not say this is a miss-configuration in general. In this case specific, the clock timer shall be carefully designed, and the tickless setting for systick timer is not a good option when we apply to ~1G clocks.

File: drivers/timer/cortex_m_systick.c [hunk 5]
```diff
@@ -17,11 +17,23 @@
...
-#define CYC_PER_TICK (sys_clock_hw_cycles_per_sec()	\
-		      / CONFIG_SYS_CLOCK_TICKS_PER_SEC)
-#define MAX_TICKS ((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)
+
+#if defined(CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME)
+extern unsigned int z_clock_hw_cycles_per_sec;
+#define CYC_PER_TICK (z_clock_hw_cycles_per_sec/CONFIG_SYS_CLOCK_TICKS_PER_SEC)
+#else
+#define CYC_PER_TICK (CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC/CONFIG_SYS_CLOCK_TICKS_PER_SEC)
+#endif
```
Comment (mmahadevan108) [inline drivers/timer/cortex_m_systick.c:26]: Changing the above portion of code does not seem to be needed. `sys_clock_hw_cycles_per_sec()` does the same.

File: drivers/timer/cortex_m_systick.c (hunk 4 above)
Comment (gramsay0) [reply drivers/timer/cortex_m_systick.c:30]: It's been a while since I looked at this, and I think I'm being pedantic.

Sensible values for `CONFIG_SYS_CLOCK_TICKS_PER_SEC` are usually >= 1000 (or sometimes 100 for emulated devices). AFAIK the only reason it's sometimes set to 1 is for performance testing, where you want as fewer ticks/ISRs as possible. In which case clamping to 1 tick is ideal

File: drivers/timer/cortex_m_systick.c (hunk 5 above)
Comment (hakehuang) [reply drivers/timer/cortex_m_systick.c:26]: [mmahadevan108](https://github.com/mmahadevan108) the sys_clock_hw_cycles_per_sec() can not used in macro after 98dba7da7ca536456594e57eca7fe89b2041c411 see analysis https://github.com/zephyrproject-rtos/zephyr/pull/83450#issuecomment-3011788241

**Review by dleach02 — APPROVED** [review]

**Comment by dleach02** [comment]
@andyross @teburd can we get your review and approval if acceptable

**Review by dkalowsk — APPROVED** [review]

**Comment by hakehuang** [comment]
@danieldegrasse can this be merged?

**Comment by danieldegrasse** [comment]
I'm ok with it, would like to see @andyross or @teburd revisit if possible

File: drivers/timer/cortex_m_systick.c [hunk 6]
```diff
@@ -17,11 +17,23 @@
...
+
+/* add MAX_TICKS protection */
+#define _MAX_TICKS (int)((k_ticks_t)(COUNTER_MAX / CYC_PER_TICK) - 1)
+#define MAX_TICKS ((_MAX_TICKS > 0) ? _MAX_TICKS : 1)
 #define MAX_CYCLES (MAX_TICKS * CYC_PER_TICK)
 
+#if (COUNTER_MAX / CYC_PER_TICK) == 1
+#pragma message("tickless does nothing as CONFIG_SYS_CLOCK_TICKS_PER_SEC too low")
```
Comment (wearyzen) [inline drivers/timer/cortex_m_systick.c:34]:
```suggestion
#pragma message("tickless does nothing as CONFIG_SYS_CLOCK_TICKS_PER_SEC is too low")
```

**Review by wearyzen — APPROVED** [review]

File: drivers/timer/cortex_m_systick.c (hunk 6 above)
Comment (cfriedt) [reply drivers/timer/cortex_m_systick.c:34]: @wearyzen - this can be merged as-is unless you would prefer the suggestion above to be made. If it's not blocking, then please go ahead and can mark this comment as resolved.

Comment (wearyzen) [reply drivers/timer/cortex_m_systick.c:34]: its not a blocker

File: drivers/timer/cortex_m_systick.c [hunk 7]
```diff
@@ -17,11 +17,23 @@
...
+#endif
```
Comment (cfriedt) [inline drivers/timer/cortex_m_systick.c:35]: @hakehuang - If `CONFIG_SYS_CLOCK_TICKS_PER_SEC` were equal to `COUNTER_MAX` would  `CONFIG_SYS_CLOCK_TICKS_PER_SEC` be too low? It seems like it would be quite high.

Also, I haven't spent a lot of time dealing with the systick in Zephyr, but am curious to know if there is sufficient test coverage for it and these transforms.

Comment (hakehuang) [reply drivers/timer/cortex_m_systick.c:35]: @cfriedt , this message notify that the CONFIG_SYS_CLOCK_TICKS_PER_SEC may be too low for system that running at ~1GHZ, like mimxrt1170_evk, and using systick as the timer will not fit such case well. and as a protection, we set this to 1, so that the system can still work with upmost accuracy. systick is not a good option for high frequency platform.
