### PR TITLE
Bluetooth: Controller: Ignore ticker_stop() return value

### LINKED ISSUE #58975: [Coverity CID: 318615] Unchecked return value in subsys/bluetooth/controller/ll_sw/ull_peripheral.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_peripheral.c

Category: Error handling issues
Function: `ull_periph_setup`
Component: Bluetooth
CID: [318615](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318615)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_peripheral.c#L444

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #58992: [Coverity CID: 318635] Unchecked return value in subsys/bluetooth/controller/ll_sw/ull_central.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_central.c#L862

Category: Error handling issues
Function: `ull_central_setup`
Component: Bluetooth
CID: [318635](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318635)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_central.c#L862

```
856     #endif /* CONFIG_BT_CTLR_ADV_EXT && CONFIG_BT_CTLR_PHY_CODED */
857     
858      /* Scanner stop can expire while here in this ISR.
859       * Deferred attempt to stop can fail as it would have
860       * expired, hence ignore failure.
861       */
>>>     CID 318635:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "ticker_stop" without checking return value (as is done elsewhere 9 out of 11 times).
862      ticker_stop(TICKER_INSTANCE_ID_CTLR, TICKER_USER_ID_ULL_HIGH,
863                  TICKER_ID_SCAN_STOP, NULL, NULL);
864     
865      /* Start central */
866      ticker_id_conn = TICKER_ID_CONN_BASE + ll_conn_handle_get(conn);
867      ticker_status = ticker_start_us(TICKER_INSTANCE_ID_CTLR,
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by mku514k**
Cast ticker_stop() calls to void where return value is not checked. This is to satisfy coverity and indicate that return value is not important.

Fixes #58992.
Fixes #58975.

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan.c [hunk 1]
```diff
@@ -1037,7 +1037,7 @@ static void isr_done_cleanup(void *param)
 	 * Deferred attempt to stop can fail as it would have
 	 * expired, hence ignore failure.
 	 */
-	ticker_stop(TICKER_INSTANCE_ID_CTLR, TICKER_USER_ID_LLL,
+	(void)ticker_stop(TICKER_INSTANCE_ID_CTLR, TICKER_USER_ID_LLL,
 		    TICKER_ID_SCAN_STOP, NULL, NULL);
```
Comment (fabiobaltieri) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_scan.c:1041]: Can you reindent the arguments?
