### PR TITLE
net: tcp: Change locking order in connection establishment

### LINKED ISSUE #35390: net.socket.tls.tls_ext: frdm_k64f test failure
**Describe the bug**
all testing fails

**To Reproduce**
in tests/net/socket/tls_ext
1. mkdir build; cd build
2. cmake -DBOARD=frdm_k64f ..
3. make; make flash

**Expected behavior**
test pass

**Impact**
https supporting

**Logs and console output**
```
    W: You have 1 IPv6 net_if addresses but 2 network interfaces

    W: Consider increasing CONFIG_NET_IF_MAX_IPV6_COUNT value.

    W: You have 1 IPv4 net_if addresses but 2 network interfaces

    W: Consider increasing CONFIG_NET_IF_MAX_IPV4_COUNT value.

    *** Booting Zephyr OS build zephyr-v2.5.0-3919-gcd9421a45e72  ***

    I: Initializing network

    I: IPv4 address: 192.0.2.1

    Running test suite tls_socket_api_extension

    ===================================================================

    START - test_tls_peer_verify_none

    E: TLS handshake error: -4e

    

        Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/tls_ext/src/main.c:366: test_common: (r equal to -1)

    failed to connect (113)

     FAIL - test_tls_peer_verify_none in 0.19 seconds

    ===================================================================

    START - test_tls_peer_verify_optional

    E: Identical connection handler 0x20003a70 already found.

    

        Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/tls_ext/src/main.c:281: test_common: (r equal to -1)

    failed to listen (120)

     FAIL - test_tls_peer_verify_optional in 0.18 seconds

    ===================================================================

    START - test_tls_peer_verify_required

    W: Failed to allocate TLS context

    

        Assertion failed at WEST_TOPDIR/zephyr/tests/net/socket/tls_ext/src/main.c:217: test_common: (r equal to -1)

    failed to create server socket (12)

     FAIL - test_tls_peer_verify_required in 0.17 seconds

    ===================================================================

    Test suite tls_socket_api_extension failed.

    ===================================================================

    PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: zephyr-v2.5.0-3919-gcd9421a45e72 / v2.6.0-rc1-159-g8717a0f678

### PR DESCRIPTION
**Pull request by jukkar**
When application calls TCP connect(), the call is blocked
by a semaphore which is then released when the connection
is established. Unfortunately the semaphore release was done
before the connection was marked as established. Depending
on the configuration options set, it is possible that after
the semaphore release, the thread that is waiting on connect()
is run immediately. Because of this, the connection bookeeping
still thought that the connection was not established even if
it was. A simple solution is to release the semaphore after
the connection is marked as established.

Fixes #35390

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

File: subsys/net/ip/tcp2.c [hunk 1]
```diff
@@ -1761,11 +1761,12 @@ static void tcp_in(struct tcp *conn, struct net_pkt *pkt)
 				}
 				conn_ack(conn, + len);
 			}
-			k_sem_give(&conn->connect_sem);
+
 			next = TCP_ESTABLISHED;
```
Comment (rlubos) [inline subsys/net/ip/tcp2.c:1765]: Indeed this change seems to fix the issue in the TLS tests, but I'm wondering, the actual TCP state is updated at line 1933, shouldn't the semaphore be fed after that? In case a higher priority thread takes precendence after feeding the semaphore, it might still fail at `net_tcp_queue_data` which verifies the TCP internal state.

Comment (jukkar) [reply subsys/net/ip/tcp2.c:1765]: Hmm, that is a good point. Indeed the application might start to send more data even if the TCP has not yet fully finished the connection establishment. I will rework the PR more.

**Review by rlubos — APPROVED** [review]
LGTM, thanks.

**Review by mniestroj — APPROVED** [review]
