### PR TITLE
usb: drivers: Fix Nordic driver ZLP handling.

### LINKED ISSUE #29364: cdc_acm_composite fails USB3CV test for Nordic platform.
**Describe the bug**
The issue was found when testing _cdc_acm_composite_ sample from the tree with USB3CV test tool.
The sample is failing _`TD 9.1: Device Descriptor Test`_.
This sample is using string descriptor for Device Product of exact 64 Bytes Length
(CONFIG_USB_DEVICE_PRODUCT).

When Hosts sends _`GetDescriptor(String iProduct)`_ request it cannot know what is the size of this descriptor
so it requires maximal possible value = 255 Bytes.

MicrosoftTeams-image (2)

Because the data length is exactly 64 Bytes the device shall end the data stage of the Control Transfer
by sending ZLP. This indicates that it has returned all data it had and no more data is available.

**To Reproduce**
Build and run _cdc_acm_composite_ sample form the tree and perform run USB3CV test on the sample

**Expected behavior**
The device shall send ZLP after 64 Bytes if the data available is multiple of 64 Bytes and Hosts asks for more.

**Impact**
Fails _`TD 9.1: Device Descriptor Test`_.

**Environment (please complete the following information):**
 - OS: USB3CV tests runs under WindowsOS however same behavior can be seen under Linux environment.
 - master branch was tested.

**Additional context**
Historical Issue reference:
#19272
#18646

### PR DESCRIPTION
**Pull request by eobalski**
This PR contains more than just a fix for ZLP handling as it was required to achieve the ZLP fix goal.

This PR removes fragmentation of IN transfers. Fragmentation made proper ZLP handling impossible.
If, for example, hosts requires 255 Bytes but only 64 Bytes are possible to send (#29364) then there is
no good way to guess where the ZLP flag should be added as the last write will be 64 Bytes long and
the driver does not know which chunk is being send in the current `usb_dc_ep_write'. Could be 2nd/3rd
if the whole data size is 128 or 192.

#18646 PR description says: 
_"ZLP flag should only be set if less data is sent
than requested by host and the length is a multiple
of wMaxPacketSize. Current implementation does not
check it correctly._

_For some platforms like nRF52, this patch will not
be enough to fix the problem. The driver must be informed
about the transfer type before sending the last packet,
without changing the API it is not possible."_

I guess the author was thinking about adding `bool zlp` to `usb_dc_ep_write()` function parameters.
This PR workarounds this issue and fixes that without changing of the API.

The PR removes `USB_DEVICE_DISABLE_ZLP_EPIN_HANDLING` config option which was
introduced only for Nordic driver. I think that it was incorrect assumption that nordic usbd hardware
sends ZLP by itself. Its not true - the **driver** has possibility to do so, not the **hardware**.
This possibility is not used in this PR because of the Zephyr USB stack compatibility
(refer to commit message).

Explanation for adding this option (provided in #19272 description) assumes that Linux Gadget zero
tests shall return _`Broken Pipe`_ if below patch applied:
``` diff
diff --git a/subsys/usb/class/loopback.c b/subsys/usb/class/loopback.c
index a49c51e691..fd6361f658 100644
--- a/subsys/usb/class/loopback.c
+++ b/subsys/usb/class/loopback.c
@@ -143,6 +143,9 @@ static int loopback_vendor_handler(struct usb_setup_packet *setup,
 	    (setup->bRequest == 0x5c)) {
 		LOG_DBG("Device-to-Host, wLength %d, data %p",
 			setup->wLength, *data);
+		if (setup->wLength == 1024) {
+			*len = 512;
+		}
 		return 0;
 	}
```
This is not true. The test output shall be: _`Bad message`_ meaning that the device returned less data than expected.

This PR resolves issues for both Linux Gadget zero tests as well as USB3CV tests.

Pros of this PR:
1. much better performance compared to previous solution with internal buffers for IN endpoints.
    - uses less RAM memory (at least less than 1024 Bytes - depends on classes used).
    - avoid copies to internal Endpoint buffers in the device driver controller (usb_dc_nrfx.c).
2. Uses Nordic LL driver (usbd_nrfx.c) more efficient (without braking the main stack requirements).
    - Does not fragment the data in the device driver controller (usb_dc_nrfx.c).

Fixes: #29364

### CODE REVIEW

File: drivers/usb/device/usb_dc_nrfx.c [hunk 1]
```diff
@@ -1723,27 +1713,6 @@ int usb_dc_ep_write(const uint8_t ep, const uint8_t *const data,
...
 	}
 
-	/* NRFX driver performs the fragmentation if buffer length exceeds
-	 * maximum packet size, however in current implementation, data is
-	 * copied to the internal buffer and must me fragmented here.
-	 * In case of fragmentation, a flag is set to prevent triggering
-	 * status stage which is handled by hardware, because there will be
-	 * another write coming.
-	 */
-	if (data_len > ep_ctx->cfg.max_sz) {
```
Comment (jfischer-phytec-iot) [inline drivers/usb/device/usb_dc_nrfx.c:1733]: Do we need to check data_len for the iso IN endpoint?

File: drivers/usb/device/usb_dc_nrfx.c [hunk 2]
```diff
@@ -1756,13 +1725,20 @@ int usb_dc_ep_write(const uint8_t ep, const uint8_t *const data,
 	}
 
 	ep_ctx->write_in_progress = true;
-	NRFX_USBD_TRANSFER_IN(transfer, ep_ctx->buf.data, ep_ctx->buf.len, 0);
+	NRFX_USBD_TRANSFER_IN(transfer, data, data_len, 0);
```
Comment (jfischer-phytec-iot) [inline drivers/usb/device/usb_dc_nrfx.c:1743]: I suspect there are buffer alignment requirements, should it be checked?

File: drivers/usb/device/usb_dc_nrfx.c (hunk 1 above)
Comment (emob-nordic) [reply drivers/usb/device/usb_dc_nrfx.c:1733]: Yes. Buffer size depends on the configuration, the device is not allowed to send more than mps, the host would not accept it.

File: drivers/usb/device/usb_dc_nrfx.c (hunk 2 above)
Comment (emob-nordic) [reply drivers/usb/device/usb_dc_nrfx.c:1743]: Im not sure, I'll check that.

Comment (emob-nordic) [reply drivers/usb/device/usb_dc_nrfx.c:1743]: I can't find any requirements for buffer alignment. Do You have something in mind?

Comment (emob-nordic) [reply drivers/usb/device/usb_dc_nrfx.c:1743]: I've briefly checked it with hid-mouse sample where the data are transfered directly using `usb_dc_ep_write` function. It works well. The data I was sending were not aligned 4.

**Review by jfischer-no — APPROVED** [review]

File: drivers/usb/device/usb_dc_nrfx.c [hunk 3]
```diff
@@ -820,6 +803,9 @@ static inline void usbd_work_process_setup(struct nrf_usbd_ep_ctx *ep_ctx)
 	usbd_setup->wLength = nrf_usbd_setup_wlength_get(NRF_USBD);
 	ep_ctx->buf.len = sizeof(struct usb_setup_packet);
 
+	/* Copy setup packet to driver internal structure */
+	memcpy(&usbd_ctx.setup, usbd_setup, sizeof(struct usb_setup_packet));
```
Comment (anangl) [inline drivers/usb/device/usb_dc_nrfx.c:807]: `usbd_ctx.setup = usbd_setup;` would be fine here. And probably such statement could be optimized well, as the structure is quite small.

**Review by anangl — APPROVED** [review]
LGTM
