### PR TITLE
kernel: work: Fix race in work queue thread

### LINKED ISSUE #64530: kernel: k_work_sync is modified after k_work_flush returns
**Describe the bug**
After a call to k_work_flush returns the k_work_sync struct may still be modified by the workq.

**To Reproduce**
The problem can be replicated by running the following code:
```c
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <assert.h>
#include <string.h>

#define LOG_LEVEL 4
LOG_MODULE_REGISTER(main);

K_THREAD_STACK_DEFINE(workq_stack, 2048);
struct k_work_q workq;

void work_handler(struct k_work *item)
{
	LOG_INF("Work running");
}

void main(void)
{
	LOG_INF("Staring Test");
	k_work_queue_init(&workq);
	k_work_queue_start(&workq, workq_stack, K_THREAD_STACK_SIZEOF(workq_stack), 10, NULL);

	struct k_work work;
	struct k_work_sync sync;

	k_work_init(&work, work_handler);

	LOG_INF("Submitting work to workq");
	int ret = k_work_submit_to_queue(&workq, &work);
	assert(ret >= 0);
	k_work_flush(&work, &sync);
	LOG_INF("k_work_flush finished");

	LOG_INF("Filling k_work with 0xff");
	struct k_work work_expected;
	memset(&work_expected, 0xff, sizeof(work_expected));
	memcpy(&work, &work_expected, sizeof(work));

	LOG_INF("Filling k_work_sync with 0xff");
	struct k_work_sync sync_expected;
	memset(&sync_expected, 0xff, sizeof(sync_expected));
	memcpy(&sync, &sync_expected, sizeof(sync));

	LOG_INF("Waiting");
	k_msleep(100);

	if (memcmp(&work, &work_expected, sizeof(work)) == 0) {
		LOG_INF("No changes to k_work detected");
	} else {
		LOG_ERR("Modification to k_work detected");
		LOG_HEXDUMP_ERR(&work_expected, sizeof(work_expected), "Expected: ");
		LOG_HEXDUMP_ERR(&work, sizeof(work), "Got: ");
	}

	if (memcmp(&sync, &sync_expected, sizeof(sync)) == 0) {
		LOG_INF("No changes to k_work_sync detected");
	} else {
		LOG_ERR("Modification to k_work_sync detected");
		LOG_HEXDUMP_ERR(&sync_expected, sizeof(sync_expected), "Expected: ");
		LOG_HEXDUMP_ERR(&sync, sizeof(sync), "Got: ");
	}

	while (1)
	{
		k_msleep(1000);
	}
}
```

**Expected behavior**
The struct k_work_sync is not modified by the workq after k_work_flush returns.

**Impact**
It is unclear when it is safe to reuse or free k_work_sync after a call to k_work_flush.

**Logs and console output**
Logs from the above program running on a K64F with Zephyr v3.3.0:
```
*** Booting Zephyr OS build zephyr-v3.3.0 ***
[00:00:00.000,000] <inf> main: Staring Test
[00:00:00.000,000] <inf> main: Submitting work to workq
[00:00:00.000,000] <inf> main: Work running
[00:00:00.000,000] <inf> main: k_work_flush finished
[00:00:00.000,000] <inf> main: Filling k_work with 0xff
[00:00:00.000,000] <inf> main: Filling k_work_sync with 0xff
[00:00:00.000,000] <inf> main: Waiting
[00:00:00.100,000] <inf> main: No changes to k_work detected
[00:00:00.100,000] <err> main: Modification to k_work_sync detected
[00:00:00.100,000] <err> main: Expected:
                               ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........
                               ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........
[00:00:00.100,000] <err> main: Got:
                               ff ff ff ff ff ff ff ff  ff ff ff ff fc ff ff ff |........ ........
                               ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........
```

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: Zephyr SDK
 - Commit SHA: 07c6af3b8c35c1e49186578ca61a25c76e2fb308 (v3.3.0)

### PR DESCRIPTION
**Pull request by Songjf-ttk**
After a call to `k_work_flush` returns the sync variable may still be modified by the workq.  This is because the work queue thread continues to modify the flag in sync even after `k_work_flush` returns.  This commit adds
`K_WORK_FLUSHING_BIT`, and with this bit, we moved the logic of waking up the caller from `handle_flush` to the `finalize_flush_locked` in workq, so that after waking up the caller, the workqueue will no longer operate on sync.

Fixes [#64530](https://github.com/zephyrproject-rtos/zephyr/issues/64530)

Signed-off-by: Junfan Song <sjf221100@gmail.com>

### CODE REVIEW

File: kernel/work.c [hunk 1]
```diff
@@ -671,19 +671,31 @@ static void work_queue_main(void *workq_ptr, void *p2, void *p3)
...
-		flag_clear(&work->flags, K_WORK_RUNNING_BIT);
-		if (flag_test(&work->flags, K_WORK_CANCELING_BIT)) {
-			finalize_cancel_locked(work);
+		/* If work is a synced work, its flag should not be
+		 * manipulated. Because after the handler is called,
+		 * thread scheduling will occur, and the function using
+		 * sync for synchronization will return. At this point,
+		 * both the calling thread and the work queue thread can
+		 * access sync. To ensure the consistency of sync, it is not
+		 * allowed for the work queue thread to modify sync anymore.
```
Comment (andyross) [inline kernel/work.c:682]: This seems incomplete?  This is going to skip the call to finalize_cancel_locked(), which as I read it is doing important stuff like list management and wakeups.  And I don't see where that handling is being done in other contexts.  Why is this safe?

**Review by andyross — COMMENTED** [review]
Some questions after a first read.  The work queue state management is indeed sorta... ponderously complicated.  And I totally buy that the linked bug is real.  I do worry that this fix isn't complete.  It looks like it fixes the modification race but leaves other stuff dangling?

**Comment by Songjf-ttk** [comment]
Hi @andyross, thanks for your review.  I have now modified the code, changing `K_WORK_SYNC_BIT` to `K_WORK_FLUSHING_BIT`,  specifically to fix the bugs introduced by flush.  To eliminate the inconsistency issues with sync,  I have delayed the call to `k_sem_give` from `handle_flush` to `finalize_flush_locked`.  This way,  after `k_work_flush` returns,  the workqueue thread will no longer modify sync.  Additionally,  I have added a check for `K_WORK_FLUSHING_BIT` in the workqueue,  so as not to affect the logic of the existing code:
```
if (flag_test(&work->flags, K_WORK_FLUSHING_BIT)) {
	finalize_flush_locked(work);
}
```

**Review by andyross — DISMISSED** [review]
This makes sense to me, thanks (with the caveat that races are hard and the fact that I can't see anything wrong doesn't mean it's not!).  FWIW: I salute your work in generating that flowchart, though think maybe it's a little overkill for the bug. :)

**Review by andyross — APPROVED** [review]
Refresh +1

**Review by peter-mitsis — APPROVED** [review]
