### PR TITLE
stm32 rtc driver using the stm32 LL_RTC Time Date init functions

### LINKED ISSUE #72888: stm32f207 fails executing the tests/drivers/rtc/rtc_api
**Describe the bug**
Executing the tests/drivers/rtc/rtc_api on the nucleo_f207zg target fails 


**To Reproduce**
1. west build -p auto -b nucleo_f207zg  tests/drivers/rtc/rtc_api
2. set `CONFIG_RTC_ALARM=n` or `CONFIG_RTC_ALARM=y`  as well
3. west flash

**Expected behavior**
```
SUITE PASS - 100.00% [rtc_api]: pass = 2, fail = 0, skip = 1, total = 3 duration = 4.005 seconds                                              
 - PASS - [rtc_api.test_set_get_time] duration = 0.001 seconds                                                                                
 - PASS - [rtc_api.test_time_counting] duration = 4.001 seconds                                                                               
 - SKIP - [rtc_api.test_y2k] duration = 0.003 seconds                                                                                         

```

**Impact**
Testcase failure

**Logs and console output**
```
Running TESTSUITE rtc_api                                                                                                                     
===================================================================                                                                           
START - test_set_get_time                                                                                                                     
                                                                                                                                              
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/rtc/rtc_api/src/test_time.c:65: rtc_api_test_set_get_time: ((timer_get >= RTC_TEST_G)
Got unexpected time                                                                                                                           
 FAIL - test_set_get_time in 0.023 seconds                                                                                                    
===================================================================                                                                           
START - test_time_counting                                                                                                                    
                                                                                                                                              
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/rtc/rtc_api/src/test_time_incrementing.c:41: rtc_api_test_time_counting: (timer_get_)
Time is decrementing                                                                                                                          
 FAIL - test_time_counting in 0.017 seconds                                                                                                   
===================================================================    
```                                                                       


**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) Ubuntu
 - Toolchain (e.g Zephyr SDK, ...) 0.16.3
 - Commit SHA d6d3c1098d5a46edaaa1f1e42133e5bb10698765

### PR DESCRIPTION
**Pull request by FRASTM**
Use the LL_RTC_TIME_Init and LL_RTC_DATE_Init and 
let the LL functions manage the Enter init mode and the Write Protection of the RTC calendar Registers

Increase the Timeout when executing the tests/drivers/rtc/rtc_api on stm32 targets
This will let test ends correctly when waiting for the alarm flags

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/72888

### CODE REVIEW

File: drivers/rtc/rtc_ll_stm32.c
Comment (ajarmouni-st) [inline drivers/rtc/rtc_ll_stm32.c:1]: In `rtc_stm32_alarm_set_time()`
```
	if ((mask == 0) && (timeptr == NULL)) {
		memset(&(p_rtc_alrm->ll_rtc_alrm), 0, sizeof(LL_RTC_AlarmTypeDef));
		p_rtc_alrm->user_callback = NULL;
		p_rtc_alrm->user_data = NULL;
		p_rtc_alrm->is_pending = false;
#if RTC_STM32_BACKUP_DOMAIN_WRITE_PROTECTION
		LL_PWR_EnableBkUpAccess();
#endif /* RTC_STM32_BACKUP_DOMAIN_WRITE_PROTECTION */
		if (rtc_stm32_is_active_alarm(RTC, id)) {
			LL_RTC_DisableWriteProtection(RTC);
			rtc_stm32_disable_alarm(RTC, id);
+                       rtc_stm32_disable_interrupt_alarm(RTC, id);
			LL_RTC_EnableWriteProtection(RTC);
		}
		LOG_DBG("Alarm %d has been disabled", id);
		goto disable_bkup_access;
	}
```

File: drivers/rtc/rtc_ll_stm32.c [hunk 1]
```diff
@@ -187,12 +187,29 @@ static inline ErrorStatus rtc_stm32_init_alarm(RTC_TypeDef *rtc, uint32_t format
 					LL_RTC_AlarmTypeDef *ll_alarm_struct, uint16_t id)
 {
 	ll_alarm_struct->AlarmDateWeekDaySel = RTC_STM32_ALRM_DATEWEEKDAYSEL_DATE;
-	/* RTC write protection is disabled & enabled again inside LL_RTC_ALMx_Init functions */
+	ll_alarm_struct->AlarmDateWeekDay = 0x01;
```
Comment (ajarmouni-st) [inline drivers/rtc/rtc_ll_stm32.c:190]: These lines are uncessary & potentially incorrect since the `AlarmDateWeekDaySel` & `AlarmDateWeekDay` fields of `LL_RTC_AlarmTypeDef` are initialized inside `rtc_stm32_init_ll_alrm_struct()`

**Review by ajarmouni-st — CHANGES_REQUESTED** [review]
can you please put the modifs related to RTC alarm in a separate commit?

File: drivers/rtc/rtc_ll_stm32.c
Comment (FRASTM) [reply drivers/rtc/rtc_ll_stm32.c:1]: `rtc_stm32_disable_interrupt_alarm` now added

File: drivers/rtc/rtc_ll_stm32.c (hunk 1 above)
Comment (FRASTM) [reply drivers/rtc/rtc_ll_stm32.c]: removed

**Comment by FRASTM** [comment]
rebase on ec0e2d6308680203bb58275062b79105016ea1b1

**Review by ajarmouni-st — CHANGES_REQUESTED** [review]

**Review by ajarmouni-st — DISMISSED** [review]

**Review by gautierg-st — DISMISSED** [review]

**Review by bjarki-andreasen — DISMISSED** [review]

**Review by ajarmouni-st — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]
