### PR TITLE
json: Skip unknown fields on parsing

### LINKED ISSUE #47988: JSON parser not consistent on extra data
For json strings containing additional objects that are not specified in the descriptor, the behavior of `json_obj_parse()` is inconsistent. It sometimes even is incorrect.

1. Extra objects are supported (`ret == 1`)

```c
struct test_struct_t {
  const char * str;
} ts;

const struct json_obj_descr test_descr[] = {
  JSON_OBJ_DESCR_PRIM(test_struct_t, str, JSON_TOK_STRING)
};

char encoded[] = "{"
  "\"str\":\"abc\","
  "\"dummy\":1"
  "}\n";

int ret = json_obj_parse(encoded, sizeof(encoded) - 1, test_descr, ARRAY_SIZE(test_descr), &ts);
```

2. Extra arrays are not supported (`ret == -EINVAL`)

```c
struct test_struct_t {
  const char * str;
} ts;

const struct json_obj_descr test_descr[] = {
  JSON_OBJ_DESCR_PRIM(test_struct_t, str, JSON_TOK_STRING)
};

char encoded[] = "{"
  "\"str\":\"abc\","
  "\"arr\": [1,2]"
  "}\n";

int ret = json_obj_parse(encoded, sizeof(encoded) - 1, test_descr, ARRAY_SIZE(test_descr), &ts);
```

3. Extra nested objects may manipulate desired objects specified in descriptor (`ret == 1`, but `ts.str == "def"` after parsing)

```c
struct test_struct_t {
  const char * str;
} ts;

const struct json_obj_descr test_descr[] = {
  JSON_OBJ_DESCR_PRIM(test_struct_t, str, JSON_TOK_STRING)
};

char encoded[] = "{"
  "\"extra\": {"
    "\"str\":\"def\""
  "},"
  "\"str\":\"abc\""
  "}\n";

int ret = json_obj_parse(encoded, sizeof(encoded) - 1, test_descr, ARRAY_SIZE(test_descr), &ts);
```

4. Nested extra objects will cause parsing to end prematurely with success return value (`ret == 6`and `ts.str1` not set after parsing although field is given in input)

```c
struct nested_test_struct_t {
  uint32_t num;
};

struct test_struct_t {
  const char * str1;
  nested_test_struct_t obj;
  const char * str2;
} ts;

const struct json_obj_descr nested_test_descr[] = {
  JSON_OBJ_DESCR_PRIM(nested_test_struct_t, num, JSON_TOK_NUMBER)
};

const struct json_obj_descr test_descr[] = {
  JSON_OBJ_DESCR_PRIM(test_struct_t, str1, JSON_TOK_STRING),
  JSON_OBJ_DESCR_OBJECT(test_struct_t, obj, nested_test_descr),
  JSON_OBJ_DESCR_PRIM(test_struct_t, str2, JSON_TOK_STRING)
};

char encoded[] = "{"
  "\"str2\":\"xyz\","
  "\"obj\": {"
    "\"num\":-2,"
    "\"extra\": {"
      "\"str1\":\"def\""
    "}"
  "},"
  "\"str1\":\"abc\""
  "}\n";

int ret = json_obj_parse(encoded, sizeof(encoded) - 1, test_descr, ARRAY_SIZE(test_descr), &ts);
```

Reason for these behaviors is that unknown/additional objects are not skipped, but tried to be parsed instead. In case of arrays this leads to parsing errors due to the unexpected array syntax. In case of objects, unknown parent fields are ignored and child fields are parsed.

### PR DESCRIPTION
**Pull request by mrfuchs**
Skip child objects and arrays that are not specified in the given object
descriptor when parsing a JSON input string.
This patch adds support for extra child arrays which previously were not
supported by the parser as opposed to additional child objects.

Fixes #47988

### CODE REVIEW

File: lib/os/json.c [hunk 1]
```diff
@@ -390,6 +390,42 @@ static int arr_next(struct json_obj *json, struct json_token *value)
...
+	int i = 1;
+
+	if (kv->value.type == JSON_TOK_ARRAY_START) {
+		while (arr_next(obj, &kv->value) >= 0) {
+			if (kv->value.type == JSON_TOK_ARRAY_END) {
+				i--;
+			} else if (kv->value.type == JSON_TOK_ARRAY_START) {
+				i++;
+			} else if (kv->value.type == JSON_TOK_OBJECT_START) {
+				skip_field(obj, kv);
```
Comment (Sir-Branch) [inline lib/os/json.c:405]: Given that this is part of OS library (maybe debatable the location?). I think we may not be allowed to use recursion due to MISRA C enforcement (#11425).

Maybe we can get away with not distinguishing between array and objects and just keeping a count (haven't tested as I'm away from my linux machine)
 
```
static void skip_field(struct json_obj *obj, struct json_obj_key_value *kv)
{
	int field_count = 1;
	if (kv->value.type == JSON_TOK_ARRAY_START || kv->value.type == JSON_TOK_ARRAY_END) {
		while (arr_next(obj, &kv->value) >= 0 && field_count > 0) {
			switch (descr->type) {
			case JSON_TOK_ARRAY_END:
			case JSON_TOK_OBJECT_END:
				field_count--;
				break;

			case JSON_TOK_OBJECT_START:
			case JSON_TOK_ARRAY_START:
				field_count++;
				break;
			}
		}
	}
}

```

**Review by Sir-Branch — COMMENTED** [review]
Thanks for putting together these changes!

File: lib/os/json.c (hunk 1 above)
Comment (mrfuchs) [reply lib/os/json.c:405]: > Given that this is part of OS library (maybe debatable the location?). I think we may not be allowed to use recursion due to MISRA C enforcement (#11425).

Wasn't aware of that. The library already makes use of recursion (cf.` obj_parse()`, `arr_parse()` and `decode_value()`), so I followed that approach for the `skip_field()` function.

> Maybe we can get away with not distinguishing between array and objects and just keeping a count (haven't tested as I'm away from my linux machine)

Not sure how the suggested code skips nested objects. It will fail for sample 4. in https://github.com/zephyrproject-rtos/zephyr/issues/47988#issue-1309117307.

File: lib/os/json.c [hunk 2]
```diff
@@ -390,6 +390,42 @@ static int arr_next(struct json_obj *json, struct json_token *value)
 	return element_token(value->type);
 }
 
+static void skip_field(struct json_obj *obj,
+		       struct json_obj_key_value *kv)
+{
+	int i = 1;
+
+	if (kv->value.type == JSON_TOK_ARRAY_START) {
+		while (arr_next(obj, &kv->value) >= 0) {
```
[the remark this answers is not in the document]
Comment (mrfuchs) [reply lib/os/json.c:399]: Good suggestion. Will change to this (because the evaluation order has to be the other way round):
```c
while (i > 0 && arr_next(obj, &kv->value) >= 0) {
```

File: lib/os/json.c [hunk 3]
```diff
@@ -390,6 +390,42 @@ static int arr_next(struct json_obj *json, struct json_token *value)
 	return element_token(value->type);
 }
 
+static void skip_field(struct json_obj *obj,
+		       struct json_obj_key_value *kv)
```
[the remark this answers is not in the document]
Comment (mrfuchs) [reply lib/os/json.c]: Changed to one line.

File: lib/os/json.c (hunk 1 above)
Comment (Sir-Branch) [reply lib/os/json.c:404]: > Wasn't aware of that. The library already makes use of recursion (cf. `obj_parse()`, `arr_parse()` and `decode_value()`), so I followed that approach for the `skip_field()` function.
> 

That's a good point, I've created #48102 to track it. I think this is due to when the json parser was added/written that it was not required. 

> Not sure how the suggested code skips nested objects. It will fail for sample 4. in https://github.com/zephyrproject-rtos/zephyr/issues/47988#issue-1309117307.

Apologies should have been:
```
static void skip_field(struct json_obj *obj, struct json_obj_key_value *kv)
{
	int field_count = 1;
	if (kv->value.type == JSON_TOK_ARRAY_START || kv->value.type == JSON_TOK_OBJECT_START) {
		while (field_count > 0 && arr_next(obj, &kv->value) >= 0) {
			switch (descr->type) {
			case JSON_TOK_ARRAY_END:
			case JSON_TOK_OBJECT_END:
				field_count--;
				break;

			case JSON_TOK_OBJECT_START:
			case JSON_TOK_ARRAY_START:
				field_count++;
				break;
			}
		}
	}
}
```
My though is it will continue to skip anything inside the initial array or object (by keeping track of start and end regardless of type - we don't care as we're skipping it- ) until the initial array or object end is reached. I'll do some testing later today or tomorrow.

Comment (mrfuchs) [reply lib/os/json.c]: I followed your advice to get rid of the recursive calls of `skip_field()`.

File: lib/os/json.c [hunk 4]
```diff
@@ -390,6 +390,29 @@ static int arr_next(struct json_obj *json, struct json_token *value)
...
+			case JSON_TOK_OBJECT_END:
+			case JSON_TOK_ARRAY_END:
+				field_count--;
+				break;
+			default:
+				break;
+			}
+		}
+	}
+}
```
Comment (pdgendt) [inline lib/os/json.c:414]: Can you capture `JSON_TOK_ERROR` here and use a return value to partly detect invalid input?

```c
static int skip_field(struct json_obj *obj, struct json_obj_key_value *kv)
{
	int field_count = 1;

	if (kv->value.type == JSON_TOK_OBJECT_START ||
	    kv->value.type == JSON_TOK_ARRAY_START) {
		while (field_count > 0 && lexer_next(&obj->lex, &kv->value)) {
			switch (kv->value.type) {
			case JSON_TOK_OBJECT_START:
			case JSON_TOK_ARRAY_START:
				field_count++;
				break;
			case JSON_TOK_OBJECT_END:
			case JSON_TOK_ARRAY_END:
				field_count--;
				break;
			case JSON_TOK_ERROR:
				return -EINVAL;
			default:
				break;
			}
		}
	} else {
		return -EINVAL;
	}

	return 0;
}
```

Comment (mrfuchs) [reply lib/os/json.c:414]: Good idea to check for `JSON_TOK_ERROR`!

Returning `-EINVAL` on value types other than object and array does not seem to be correct as an extra object could also be of primitive type, e.g. following code should return successfully with return code 1:

```cpp
struct test_struct_t {
    const char* str;
} ts;

const struct json_obj_descr test_descr[] = {
  JSON_OBJ_DESCR_PRIM(struct test_struct_t, str, JSON_TOK_STRING)
};

char encoded[] = "{"
    "\"other_str\":\"12\","
    "\"str\":\"abc\","
    "\"other_num\":34"
    "}\n";

int ret = json_obj_parse(encoded, sizeof(encoded) - 1, test_descr, ARRAY_SIZE(test_descr), &ts);
```

Comment (pdgendt) [reply lib/os/json.c:414]: The `default` would still continue to work? It's only in case of an errror.

**Review by pdgendt — APPROVED** [review]

**Comment by mrfuchs** [comment]
@bbilas, @mniestroj, could you review, please? Thanks!

**Review by bbilas — APPROVED** [review]
