### PR TITLE
Fix WS client Coverity issue

### LINKED ISSUE #20508: [Coverity CID :205634]Code maintainability issues in /samples/net/sockets/websocket_client/src/main.c
Static code scan issues seen in File: /samples/net/sockets/websocket_client/src/main.c
 Category: Code maintainability issues
 Function: setup_socket
 Component: Samples
 CID: 205634
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by rveerama1**
Close the socket and return the error.

Fixes #20508
Coverity CID :205634

### CODE REVIEW

File: samples/net/sockets/websocket_client/src/main.c [hunk 1]
```diff
@@ -100,6 +100,11 @@ static int setup_socket(sa_family_t family, const char *server, int port,
 				LOG_ERR("Failed to set %s secure option (%d)",
 					family_str, -errno);
 				ret = -errno;
+
+				close(*sock);
+				*sock = -1;
+
+				return ret;
```
Comment (tbursztyka) [inline samples/net/sockets/websocket_client/src/main.c]: it'suseless, it's done in line 133 already and with this it will miss the test in line 128

File: samples/net/sockets/websocket_client/src/main.c [hunk 2]
```diff
@@ -109,6 +114,11 @@ static int setup_socket(sa_family_t family, const char *server, int port,
 				LOG_ERR("Failed to set %s TLS_HOSTNAME "
 					"option (%d)", family_str, -errno);
 				ret = -errno;
+
+				close(*sock);
+				*sock = -1;
+
+				return ret;
```
Comment (tbursztyka) [inline samples/net/sockets/websocket_client/src/main.c]: same

File: samples/net/sockets/websocket_client/src/main.c (hunk 1 above)
Comment (rveerama1) [reply samples/net/sockets/websocket_client/src/main.c]: No if first setsockopt fails it will try to set second setsockopt.

File: samples/net/sockets/websocket_client/src/main.c (hunk 2 above)
Comment (rveerama1) [reply samples/net/sockets/websocket_client/src/main.c]: cal return yes, but close() was not called later stages. So I closed and returned.

File: samples/net/sockets/websocket_client/src/main.c (hunk 1 above)
Comment (tbursztyka) [reply samples/net/sockets/websocket_client/src/main.c]: have a goto  to line 128 then

File: samples/net/sockets/websocket_client/src/main.c (hunk 2 above)
Comment (tbursztyka) [reply samples/net/sockets/websocket_client/src/main.c]: the close is fine yes. my comments relate to the return ret only

File: samples/net/sockets/websocket_client/src/main.c (hunk 1 above)
Comment (rveerama1) [reply samples/net/sockets/websocket_client/src/main.c]: line 128 tells failed to created socket. In this case socket created succesfully, but failed to do setsockopt.

**Comment by rveerama1** [comment]
Otherwise simple goto makes nicer. I will update the PR.

File: samples/net/sockets/websocket_client/src/main.c (hunk 1 above)
Comment (tbursztyka) [reply samples/net/sockets/websocket_client/src/main.c]: Socket creation, imo, goes with configuring it as well.

File: samples/net/sockets/websocket_client/src/main.c (hunk 2 above)
Comment (rveerama1) [reply samples/net/sockets/websocket_client/src/main.c]: Modified a bit.

**Review by jukkar — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]
