### PR TITLE
Bluetooth: host: Fix ordering of TX sent callbacks

### LINKED ISSUE #21059: Bluetooth sent callback delayed more than ATT
**Describe the bug**
Previously the ATT was deferred to the system workqueue and the sent notifications and the ATT were practically in the same thread. "0a925bdf9c574bf57940ff41354806f851b6ccfe Bluetooth: L2CAP: Process fixed channels in the RX thread" moved ATT to the RX thread. It seems that sometimes the system work-queue is very slow to be scheduled. As such, the k_work submitted after the bt_recv_prio() received from the driver gets executed *after* the remote side has sent another request that gets propagated to the RX thread.

**To Reproduce**
1. mkdir build; cd build
2. cmake -Bbuild_vega -G"Eclipse CDT4 - Ninja" -DBOARD=rv32m1_vega_ri5cy /work/zephyr/zephyr-source/samples/bluetooth/peripheral_hr && ninja -Cbuild_vega
3. make

The logs on the peripheral_hr and central_hr as as below:

peripheral_hr(VEGA):
```
***** Booting Zephyr OS build v2.1.0-rc2 *****
Bluetooth initialized
Advertising successfully started
Connected
[00:00:00.020,000] <inf> bt_hci_core: HW Platform: reserved (0x0000)
[00:00:00.020,000] <inf> bt_hci_core: HW Variant: unknown (0x0000)
[00:00:00.020,000] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.1 Build 0
[00:00:00.020,000] <wrn> bt_hci_core: No static addresses stored in controller
[00:00:00.180,000] <inf> bt_hci_core: Identity: e6:16:fe:ac:a0:e2 (random)
[00:00:00.180,000] <inf> bt_hci_core: HCI: version 5.1 (0x0a) revision 0x0000, manufacturer 0x05f1
[00:00:00.180,000] <inf> bt_hci_core: LMP: version 5.1 (0x0a) subver 0xffff
[00:00:00.690,000] <wrn> bt_att: Ignoring unexpected request
```
central_hr(NRF52):
```
[DEVICE]: e6:16:fe:ac:a0:e2 (random), AD evt type 0, AD data len 11, RSSI -17
[AD]: 1 data_len 1
[AD]: 3 data_len 6
Connected: e6:16:fe:ac:a0:e2 (random)
[ATTRIBUTE] handle 25
Discover complete
[00:01:26.309,600] <err> bt_att: ATT Timeout
```
**Expected behavior**
The connection should be successful and notifications should be sent (by the peripheral) and received (by the central)

**Impact**
High

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: VEGA toolchain
 - Commit SHA or Version used: tag: v2.1.0-rc2

### PR DESCRIPTION
**Pull request by jhedberg**
Now that the TX callbacks happen from the system workqueue but fixed
channels get processed from the RX thread there's a risk that the
ordering of these gets messed up. This is particularly bad for ATT
when it's trying to enforce flow control.
    
To fix the issue store the completed TX packet information in a
per-connection list and process this list before processing any new
packets for the same connection. We still also schedule a workqueue
callback, which will simply do nothing for this list if bt_recv()
already took care of it.

Fixes #21059

### CODE REVIEW

**Review by alexandru-porosanu-nxp — APPROVED** [review]

**Review by joerchan — APPROVED** [review]

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -268,7 +268,15 @@ static void conn_update_timeout(struct k_work *work)
 		 * auto connect flag if it was set, instead just cancel
 		 * connection directly
 		 */
-		bt_hci_cmd_send(BT_HCI_OP_LE_CREATE_CONN_CANCEL, NULL);
+		if (conn->state == BT_CONN_CONNECT) {
+			bt_hci_cmd_send(BT_HCI_OP_LE_CREATE_CONN_CANCEL, NULL);
```
[the remark this answers is not in the document]
Comment (jhedberg) [reply subsys/bluetooth/host/conn.c]: This was for the previous revision where I reused conn_update_timeout(). I had to add explicit state checks that the function wouldn't do things it shouldn't when it was scheduled due to pending TX complete callbacks.

File: subsys/bluetooth/host/conn.c [hunk 2]
```diff
@@ -240,6 +240,60 @@ static int send_conn_le_param_update(struct bt_conn *conn,
...
+	BT_DBG("conn %p", conn);
+
+	while (1) {
+		struct bt_conn_tx *tx;
+		unsigned int key;
+		bt_conn_tx_cb_t cb;
+		void *user_data;
+
+		key = irq_lock();
+		if (sys_slist_is_empty(&conn->tx_complete)) {
```
Comment (Vudentz) [inline subsys/bluetooth/host/conn.c]: I wonder why you havent used sys_slist_get and just bail if tx is NULL?

Comment (jhedberg) [reply subsys/bluetooth/host/conn.c]: I did consider it. Doing separate is_empty & get_not_empty() means a few less cycles spent with interrupts locked. There's not a huge difference though.
