### PR TITLE
drivers: display: display_rm67612: fix coverity issues

### LINKED ISSUE #81921: [Coverity CID: 434706] Unchecked return value in drivers/display/display_rm67162.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/drivers/display/display_rm67162.c

Category: Error handling issues
Function: `rm67162_init`
Component: Drivers
CID: [434706](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434706)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/drivers/display/display_rm67162.c#L337

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434706

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #81929: [Coverity CID: 434687] Unsigned compared against 0 in drivers/display/display_rm67162.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/drivers/display/display_rm67162.c

Category: Control flow issues
Function: `rm67162_write_fb`
Component: Drivers
CID: [434687](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434687)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/drivers/display/display_rm67162.c#L370

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434687

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #81945: [Coverity CID: 434637] Structurally dead code in drivers/display/display_rm67162.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/drivers/display/display_rm67162.c#L533

Category: Control flow issues
Function: `rm67162_set_pixel_format`
Component: Drivers
CID: [434637](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434637)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/drivers/display/display_rm67162.c#L533

```
527              data->pixel_format = MIPI_DSI_PIXFMT_RGB888;
528              return 0;
529      default:
530              /* Other display formats not implemented */
531              return -ENOTSUP;
532      }
>>>     CID 434637:  Control flow issues  (UNREACHABLE)
>>>     This code cannot be reached: "if (data->pixel_format == 0...".
533      if (data->pixel_format == MIPI_DSI_PIXFMT_RGB888) {
534              param = MIPI_DCS_PIXEL_FORMAT_24BIT;
535              data->bytes_per_pixel = 3;
536      } else if (data->pixel_format == MIPI_DSI_PIXFMT_RGB565) {
537              param = MIPI_DCS_PIXEL_FORMAT_16BIT;
538              data->bytes_per_pixel = 2;
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNREACHABLE). ([CWE-561](http://cwe.mitre.org/data/definitions/561.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434637

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by danieldegrasse**
Fix a few Coverity issues discovered by static analysis

This PR was tested with `samples/drivers/display` on the RT1170 EVK, using the G1120B0MIPI shield

Fixes #81921
Fixes #81929 
Fixes #81945

### CODE REVIEW

**Review by faxe1008 — APPROVED** [review]

File: drivers/display/display_rm67162.c [hunk 1]
```diff
@@ -350,7 +350,7 @@ static int rm67162_write_fb(const struct device *dev, bool first_write,
 			const uint8_t *src, uint32_t len)
 {
 	const struct rm67162_config *config = dev->config;
-	uint32_t wlen = 0;
+	ssize_t wlen;
```
Comment (jfischer-no) [inline drivers/display/display_rm67162.c:357]: I am curious why we use ssize_t in the drivers, what C spec. introduced this type?

**Review by jfischer-no — APPROVED** [review]
