### PR TITLE
Bluetooth: controller: split: Fix NRF_CCM overrun

### LINKED ISSUE #21107: LL_ASSERT and 'Imprecise data bus error' in LL Controller
**Describe the bug**
I am using a custom board similar to the **nrf52840_pca10056** modified version of the **hci_usb sample** with addtion of a watchdog, mcumgr capability and logging. The main application on a linux host (bluez5.51) will search and (re)connect up to 9 peripheral devices.

For reconnection the application will regularly enable and disable scans. In the setup there are only 8 devices present to force simultaneous scanning and data exchange with the peripherals.

The FW (hci_usb) on the nrf52840 is crashing regularly (minutes - 4h) with one of the three following errors. Since the crashes happen in the same subsystem (bluetooth/controller/ll_sw/), all three different error logs are attached here. Every crash was seen at least two times.

**To Reproduce**
The crash is observed on a custom board similar to the **nrf52840_pca10056** modified version of the **hci_usb sample** with addtion of a watchdog, mcumgr capability and logging:
```
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUMGR=y
CONFIG_MCUMGR_SMP_UART=y
CONFIG_MCUMGR_CMD_IMG_MGMT=y
CONFIG_MCUMGR_CMD_OS_MGMT=y
CONFIG_BT_MAX_CONN=15
CONFIG_BLUETOOTH_INT_EP_MPS=64
CONFIG_LOG=y
CONFIG_UART_CONSOLE=y
```
The bug should be observable on the standard hci_usb sample for the nrf52840_pca10056 

**Debugging efforts**
I tried adding debug logs of the subsystem, but could not reproduce the bug with it enabled. 

**Expected behavior**
The crashes should not happen.

**Impact**
This is a major annoance to showstopper 

**zephyr log output**

See file below for complete logs.

1. This happens the most of all three errors
```
[03:36:46.588,989] <err> os: ***** BUS FAULT *****
[03:36:46.588,989] <err> os:   Imprecise data bus error
[03:36:46.589,019] <err> os: r0/a1:  0x20001b40  r1/a2:  0x20001aac  r2/a3:  0x20002060
[03:36:46.589,019] <err> os: r3/a4:  0x20008dcc r12/ip:  0x00021339 r14/lr:  0x00018e0d
[03:36:46.589,019] <err> os:  xpsr:  0x6100021b
[03:36:46.589,019] <err> os: Faulting instruction address (r15/pc): 0x00014686
[03:36:46.589,019] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[03:36:46.589,019] <err> os: Fault during interruptling
[03:36:46.589,050] <err> os: Current thread: 0x20004fa8 (unknown)
[03:36:46.652,160] <err> os: Halting system
```

```
addr2line -e zephyr/zephyr.elf 0x00014686
zephyr/subsys/bluetooth/controller/util/memq.c:100
```
https://github.com/zephyrproject-rtos/zephyr/blob/12948fdf37d53f5691e9da48f28bbeea466e5560/subsys/bluetooth/controller/util/memq.c#L100

2.
```
assert: 'rx' failed
[00:38:19.855,865] <err> os: r0/a1:  0x00000003  r1/a2:  0x0000000a  r2/a3:  0x00000001
[00:38:19.855,895] <err> os: r3/a4:  0x00011a01 r12/ip:  0x20002800 r14/lr:  0x00017d99
[00:38:19.855,895] <err> os:  xpsr:  0x6100001b
[00:38:19.855,895] <err> os: Faulting instruction address (r15/pc): 0x00017da4
[00:38:19.855,895] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
[00:38:19.855,895] <err> os: Fault during interruptling
[00:38:19.855,926] <err> os: Current thread: 0x20004fa8 (unknown)
[00:38:19.907,470] <err> os: Halting system
```

```
addr2line -e zephyr/zephyr.elf 0x00017da4
zephyr/subsys/bluetooth/controller/ll_sw/ull.c:1449 (discriminator 1)
```
https://github.com/zephyrproject-rtos/zephyr/blob/12948fdf37d53f5691e9da48f28bbeea466e5560/subsys/bluetooth/controller/ll_sw/ull.c#L1449

3.
```
assert: 'e' failed
[04:18:06.579,406] <err> os: r0/a1:  0x00000003  r1/a2:  0x0000000a  r2/a3:  0x00000001
[04:18:06.579,406] <err> os: r3/a4:  0x00011a01 r12/ip:  0x00000000 r14/lr:  0x0001e0b1
[04:18:06.579,406] <err> os:  xpsr:  0x61000011
[04:18:06.579,406] <err> os: Faulting instruction address (r15/pc): 0x0001e0bc
[04:18:06.579,406] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
[04:18:06.579,437] <err> os: Fault during interruptling
[04:18:06.579,437] <err> os: Current thread: 0x20004fa8 (unknown)
[04:18:06.630,981] <err> os: Halting system
```

```
addr2line -e zephyr/zephyr.elf 0x0001e0bc
zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c:586 (discriminator 1)
```
https://github.com/zephyrproject-rtos/zephyr/blob/12948fdf37d53f5691e9da48f28bbeea466e5560/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn.c#L586

Additional journal log of the linux host with the (full) zephyr logs included and some additional context from the linux side:
[journal_ll_ctrl_assert_bug.txt](https://github.com/zephyrproject-rtos/zephyr/files/3911492/journal_ll_ctrl_assert_bug.txt)

**Environment (please complete the following information):**
 - OS: MacOS (FW build), Linux (user of the external HCI controller)
 - Toolchain: gnuarmemb v7.3.1, updated today v9.2.1 no change
 - Commit SHA or Version used:  v2.1.0-rc1-316-g12948fdf37d5

**Additional context**
The more traffic is created, eg. sending indications from/reading/writing values of the remote devices, the more likely it is to trigger the bug.

The full logs show some hci command timeouts from the linux side, which mostly revolve around enableing/disableing scanning.

### PR DESCRIPTION
**Pull request by cvinayak**
Fix missing assignment of NRF_CCM->MAXPACKETSIZE register
for PDU sizes smaller than 251 bytes. If there is CRC errors
causing PDU length fields to be higher than configured PDU
buffer sizes in the controller, without the MAXPACKETSIZE
register set to correct PDU size, CCM module could overrun
the PDU buffer and cause memory corruption. This fix is
applicable for all nRF52 Series SoCs except nRF52832 SoC.

Fixes #21107.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@LeBlue FYI, please approve if the issue gets fixed. I assume you will need to run the tests for few days.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 1]
```diff
@@ -1019,6 +1018,14 @@ void *radio_ccm_rx_pkt_set(struct ccm *ccm, u8_t phy, void *pkt)
 #endif /* CONFIG_HAS_HW_NRF_RADIO_BLE_CODED */
 #endif /* CONFIG_BT_CTLR_PHY_CODED */
 	}
+
+#if !defined(CONFIG_SOC_NRF52832) && \
+	(CONFIG_BT_CTLR_DATA_LENGTH_MAX < ((RADIO_PDU_LEN_MAX) - 4))
+	u8_t max_len = (NRF_RADIO->PCNF1 & RADIO_PCNF1_MAXLEN_Msk) >>
```
Comment (joerchan) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:1024]: Isn't it better to accept this as an argument instead?
You are now dependent on the order of these functions:

```
		radio_pkt_configure(8, (max_rx_octets + 4), (phy << 1) | 0x01);

		radio_pkt_rx_set(radio_ccm_rx_pkt_set(&lll->ccm_rx, phy,
						      node_rx->pdu));
```

**Comment by carlescufi** [comment]
@aescolar @cvinayak this introduces an issue on the simulator, since the new register is not mapped

**Comment by carlescufi** [comment]
> Does it exist for a 52832? (that's what the nrf52_bsim tries to emulate)

No, actually that's true. The nRF52832 doesn't have this register. This must be a missing conditional compilation in the LL. @cvinayak ?

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:1024]: As the packet configure interface is the right place to pass the max length, and since the value is available in a global location, it would be wasted CPU cycles to pass as parameter. Other functions like tIFS switch interface do depend on order of hal function calls, hence this will not be an exception.

**Comment by cvinayak** [comment]
@carlescufi @aescolar it was an oversight with regards to the use of the SOC_NRF52832, replaced with the correct SOC_COMPATIBLE_NRF52832

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:1025]: Reading a HW register instead is definitely wasted CPU cycles. HW peripheral reads are slower than normal memory read, and the place where you call this function you have the right argument available. Leave it to the compiler to optimize the register values.

Comment (carlescufi) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:1025]: I tend to agree with @joerchan here from a cursory look, but consistency before anything else.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:1025]: Compiler does not optimize across c files. Remember that the added code is conditionally compiled in and compiler compiling the caller does not know that. Caller will always pass parameter if I pass as parameter. For 251 bytes PDUs the assignment of MAXPACKETSIZE is not necessary as CCM reset value is 251 bytes. Without parameter passing, the  builds with 251 bytes configured are optimal.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:1025]: This said, yes, LDR instruction use more cycles but looking at the compiler generated code they are interleaved with other LDR, STR or register operations, and my belief is, instruction pipeline would balance out any CPU cycle overhead.

Conditionally compiling a function signature is another option (used elsewhere in the controller), it was a personal choice here to avoid it, for a simple code block as this. 

There is a lot of scope to optimize the controller code, both for space and speed, but the effort required is high.

Do you know why LTO is not used in Zephyr? (IIRC, there used to be Kconfig before?)

**Comment by LeBlue** [comment]
@cvinayak 
> @LeBlue FYI, please approve if the issue gets fixed. I assume you will need to run the tests for few days.

I have modified the test setup and moved the peripherals on the edge of the radio reception range. Now the issue is observable (without the patch) after 10-20 mins (instead of several hours).

I am running the first version of this patch with 3 setups: the hci_uart sample, hci_usb sample and a custom hci_usb firmware for almost 20h with no issues. Since this is tested on the nrf52840 there should be no difference to the second patch version. I am quite sure that the issue #21107 is fixed with this patch.

If there is another iteration I can test it, too.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 1 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:1025]: For the record, I think I agree with @joerchan. But agree also that finding the most optimal code here requires a lot more work, which should/could be done at a later time.
On the subject of optimization (but not really related to this PR): the parameter 'phy' is not used for the nRF51-series.

**Review by kruithofa — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
