### PR TITLE
ARC: interrupt management fix for SMP case

### LINKED ISSUE #31298: tests/kernel/gen_isr_table failed on hsdk and nsim_hs_smp sometimes
**Describe the bug**
`tests/kernel/gen_isr_table` failed on `hsdk` and `nsim_hs_smp` sometimes, 
when test case `test_run_time_interrupt` run in slave cores.

**To Reproduce**
1. add extra config in `prj.conf` file `CONFIG_ARC_FIRQ_STACK=y` and `CONFIG_TEST_HW_STACK_PROTECTION=n` (see `testcase.yaml`)
2. west build -d build -b hsdk .\tests\kernel\gen_isr_table
3. west run

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.4.0-3009-gfc1b5de4c307  ***
START - Test gen_isr_tables
IRQ configuration (total lines 88):
Running test suite context
===================================================================
START - test_build_time_direct_interrupt
isr1 isr=0x900005e8 irq=87
isr2 isr=0x90000758 irq=86
Checking _irq_vector_table entry 71 for irq 87
triggering irq 87
isr1 ran
Checking _irq_vector_table entry 70 for irq 86
triggering irq 86
isr2 ran
 PASS - test_build_time_direct_interrupt
===================================================================
START - test_build_time_interrupt
_sw_isr_table at location 0x9000bc00
isr3 isr=0x90000548 irq=85 param=0xb01dface
Checking _sw_isr_table entry 69 for irq 85
triggering irq 85
isr3 ran with parameter 0xb01dface
isr4 isr=0x90000570 irq=84 param=0xca55e77e
Checking _sw_isr_table entry 68 for irq 84
triggering irq 84
isr4 ran with parameter 0xca55e77e
 PASS - test_build_time_interrupt
===================================================================
START - test_run_time_interrupt
ASSERTION FAIL [!arch_irq_is_enabled(irq)] @ WEST_TOPDIR/zephyr/arch/common/sw_isr_common.c:84
        IRQ 83 is enabled
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 2
E: Current thread: 0x90007bfc (ztest_thread)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK)
 - master branch（ zephyr-v2.4.0-3009-gfc1b5de4c307）

**Additional context**

```
ASSERTION FAIL [!arch_irq_is_enabled(irq)] @ WEST_TOPDIR/zephyr/arch/common/sw_isr_common.c:84
        IRQ 83 is enabled
```
z_isr_install assert whether irq_is_enabled, and slave cores never call initial code to disable the unused interrupt lines.
https://github.com/zephyrproject-rtos/zephyr/blob/7b6fe476917dc1ff0575e3cb6349cd646f304fc8/arch/common/sw_isr_common.c#L73-L86

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
## issue description

In case of SMP system interrupt infrastructure implementation for ARC has serious design flaws.

We have per-core interrupt controllers private for each core. They are used to control interrupts - enable/disable, set priority. The IDU (interrupt distribution unit) is setup to distribute interrupts to different cores in the round-robin manner.

The irq management functions (`irq_enable`, `irq_disable`, `irq_is_enabled`) setup/check interrupt controller state only for the core where they are called. This cause inconsistency - we may have interrupt enabled on one core and disabled it on another. Such approach makes common interrupts unusable in case of SMP - there is no correct way to enable/disable interrupt line, we will lose some interrupts if we simple use `irq_enable` or we will get unexpected interrupts if we use `irq_disable`. See #31298 for example.

Another issue is that we select round-robin interrupt distribution mode to all CPUs at the moment when secondary CPUs are not initialized (which happens quite late - after driver initialization).

## reworked implementation description

We manage interrupts (enable/disable) with IDU instead of per-core interrupt controller for the common interrupts. The per-core interrupts enabling/disabling is still managed by per-core interrupt controller.

We keep interrupt handling on all CPUs, and we do initial interrupt controller setup on all CPUs and enable round-robin interrupt distribution mode in IDU. We move IDU setup from SoC code to generic ARC code. The round round-robin mode is selected only after all system cores are initialized.

NOTE: this patch fixes only SMP interrupt enabling / disabling issue and doesn't address proper IRQ priority handling on SMP. Overall progress is tracked in #31415

Fixes: #31298

### CODE REVIEW

**Comment by evgeniy-paltsev** [comment]
DNM, till I do additional testing on ARC SMP HW boards with proper peripherals configuration.

File: arch/arc/core/irq_manage.c [hunk 1]
```diff
@@ -81,41 +81,111 @@ void z_arc_firq_stack_set(void)
...
+ *   --------------------------         --------------------------
+ *         |      |                             |      |
+ *         |    [core 0 private interrupts]     |    [core 1 private interrupts]
+ *         |                                    |
+ *        ---------------------------------------------
+ *        |     IDU (Interrupt Distribution Unit)     |
+ *        ---------------------------------------------
+ *                            |
+ *               [common (shared) interrupts]
+ */
```
Comment (ruuddw) [inline arch/arc/core/irq_manage.c:115]: Is it already documented somewhere how private and shared interrupts should be wired up (common vectors start at ARC_CONNECT_IDU_IRQ_START)?
This is not a hardware integration restriction, but a software imposed limitation, right? So it could be that hardware integrators to choose a different way of wiring up private/common interrupts.

File: drivers/interrupt_controller/intc_arcv2_irq_unit.c [hunk 2]
```diff
@@ -21,43 +21,132 @@
...
+		arc_core_intc_init_nolock(irq, _ARC_V2_INT_DISABLE);
+	}
 
-		z_arc_v2_aux_reg_write(_ARC_V2_IRQ_SELECT, irq);
-#ifdef CONFIG_ARC_SECURE_FIRMWARE
-		z_arc_v2_aux_reg_write(_ARC_V2_IRQ_PRIORITY,
-			 (CONFIG_NUM_IRQ_PRIO_LEVELS-1) |
-			 _ARC_V2_IRQ_PRIORITY_SECURE); /* lowest priority */
+	for (uint32_t irq = ARC_CONNECT_IDU_IRQ_START; irq < CONFIG_NUM_IRQS; irq++) {
+		arc_core_intc_init_nolock(irq, _ARC_V2_INT_ENABLE);
```
Comment (ruuddw) [inline drivers/interrupt_controller/intc_arcv2_irq_unit.c:128]: Could there be any common interrupts pending at this time, that first need to get cleared? Maybe from a warm reset?

Comment (evgeniy-paltsev) [reply drivers/interrupt_controller/intc_arcv2_irq_unit.c:128]: Shouldn't be an issue for warm reset as we firstly disable common lines in `arc_shared_intc_init` and only after that we enable it here, in `arc_core_private_intc_init`.

Also shouldn't be an issue for hard reset - as after reset all lines in core interrupt controller are enabled anyway.

File: arch/arc/core/irq_manage.c (hunk 1 above)
Comment (evgeniy-paltsev) [reply arch/arc/core/irq_manage.c:115]: Discussed internally - for now no changes required.

**Comment by evgeniy-paltsev** [comment]
Tested on HW - so removing DNM.

**Review by abrodkin — DISMISSED** [review]

**Review by abrodkin — APPROVED** [review]

**Review by ruuddw — APPROVED** [review]
minor comment: in the documentation/diagram only core 0 has private external interrupts, but any core may have these (not supported in Zephyr, though).
