### PR TITLE
arch/arm: Fix zero interrupt latency priority level

### LINKED ISSUE #8073: Zero Latency IRQ masked by interrupt locking
The Zero Latency IRQ feature is described as an interrupt that runs in a lower priority than the kernel reserved IRQs, but should not be  masked by interrupt locking

Currently Zero Latency IRQ is set to priority level 2, but interrupt locking will mask all interrupts except priority level 0 and 1.

This problem comes from the fact that previously the kernel reserved priority 0 and 1, but now it only reserves priority 0, this update should have moved the Zero Latency IRQ priority level down to priority level 1.

### PR DESCRIPTION
**Pull request by joerchan**
The zero interrupt priority is configured incorrectly and is blocked by irq_lock.
Setting it to the last of the reserved interrupt levels

Fixes #8073

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

File: arch/arm/core/irq_manage.c [hunk 1]
```diff
@@ -84,19 +84,18 @@ int _arch_irq_is_enabled(unsigned int irq)
  */
 void _irq_priority_set(unsigned int irq, unsigned int prio, u32_t flags)
 {
-	/* Hardware priority levels 0 and 1 reserved for Kernel use.
```
Comment (ioannisg) [inline arch/arm/core/irq_manage.c]: Is it not always true that the kernel reserves priority levels 0 and 1?

File: arch/arm/core/irq_manage.c [hunk 2]
```diff
@@ -84,19 +84,18 @@ int _arch_irq_is_enabled(unsigned int irq)
...
-	 * So we add 2 to the requested priority level. If we support
-	 * ZLI, 2 is also reserved so we add 3.
+	/* Hardware priority levels can be reserved for Kernel use.
+	 * So we add to the requested priority level.
```
Comment (ioannisg) [inline arch/arm/core/irq_manage.c]: This line is incomplete; please, specify what exactly is added.

File: arch/arm/core/irq_manage.c [hunk 3]
```diff
@@ -84,19 +84,18 @@ int _arch_irq_is_enabled(unsigned int irq)
...
 #if CONFIG_ZERO_LATENCY_IRQS
-	/* If we have zero latency interrupts, that makes priority level 2
+	/* If we have zero latency interrupts, the last priority level is
 	 * a case with special semantics; it is not masked by irq_lock().
 	 * Our policy is to express priority levels with special properties
 	 * via flags
 	 */
 	if (flags & IRQ_ZERO_LATENCY) {
-		prio = 2;
+		prio = _IRQ_PRIO_OFFSET - 1;
```
Comment (ioannisg) [inline arch/arm/core/irq_manage.c]: so, _IRQ_PRIO_OFFSET is 2 (when we configure for zero-latency IRQs), so this changes the priority setting from 2 to 1. Why do we want to do that?

File: arch/arm/core/irq_manage.c [hunk 4]
```diff
@@ -84,19 +84,18 @@ int _arch_irq_is_enabled(unsigned int irq)
...
-	/* Hardware priority levels 0 and 1 reserved for Kernel use.
-	 * So we add 2 to the requested priority level. If we support
-	 * ZLI, 2 is also reserved so we add 3.
+	/* Hardware priority levels can be reserved for Kernel use.
+	 * So we add to the requested priority level.
 	 */
 
 #if CONFIG_ZERO_LATENCY_IRQS
-	/* If we have zero latency interrupts, that makes priority level 2
+	/* If we have zero latency interrupts, the last priority level is
```
Comment (ioannisg) [inline arch/arm/core/irq_manage.c]: Just to clarify: last priority level == the lowest-level priority?

**Review by ioannisg — CHANGES_REQUESTED** [review]

**Comment by ioannisg** [comment]
Also, use standard format for commit message, i.e. "arch: arm: ....."

**Comment by ioannisg** [comment]
OK, I did some more investigation and I think that thanks to @joerchan we might have spotted a critical bug here:

According to my understanding:
In ARMv7-M, ARMv8-M Mainline MCUs, Prio-0 is reserved for fault-priorities, and Prio-1 is reserved for Zero-latency IRQs (if configured so).

So then 
- all inline-comment text is wrong and confusing, and
- irq_lock() definitely masks-out the zero-latency IRQs.

File: arch/arm/core/irq_manage.c (hunk 2 above)
Comment (ioannisg) [reply arch/arm/core/irq_manage.c]: I think we need to be explicit here. The deleted text is definitely outdated, buy we should not replace it with unclear text. IMO
- the comment is wrong for ARMv6-M, ARMv8-M Baseline: we do not reserve anything there
- For ARMv7-M, ARMv8-M Mainline Kernel reserves level-0 for faults, **and**, level-1 for zero-latency IRQs (if configured to do so)
- all the above are reflected to `_IRQ_PRIO_OFFSET` which is, thus, _added_ to the given _prio_ for normal (i.e. not Zero-latency) IRQs

I think the comment should contain all this information.

File: arch/arm/core/irq_manage.c (hunk 3 above)
Comment (ioannisg) [reply arch/arm/core/irq_manage.c]: After, doing the investigation, I think that this could be done a bit better. We should not require the Zero-latency IRQ level to be the _last_ reserved offset. Instead, we should have a #define for the _ZERO_LATENCY_IRQ_PRIO_OFFSET, as we have for _IRQ_PRIO_OFFSET.

**Review by ioannisg — CHANGES_REQUESTED** [review]

File: arch/arm/core/irq_manage.c (hunk 3 above)
Comment (joerchan) [reply arch/arm/core/irq_manage.c]: How about setting _EXC_ZERO_LATENCY_PRIO 1 in cortex_m/exc.h together with SVC/FAULT_PRIO?

File: arch/arm/core/irq_manage.c (hunk 2 above)
Comment (joerchan) [reply arch/arm/core/irq_manage.c]: The explicit text is what caused it to be outdated in the first place.
There is no need to tell which IRQs are reserved for what at this point, we only need to explain why we are offsetting them.

File: arch/arm/core/irq_manage.c (hunk 1 above)
Comment (joerchan) [reply arch/arm/core/irq_manage.c]: I can only see that priority level 0 is reserved for SVCs and FAULTs.

Comment (ioannisg) [reply arch/arm/core/irq_manage.c]: Yes, this comment is outdated, see my reply below.

File: arch/arm/core/irq_manage.c (hunk 2 above)
Comment (ioannisg) [reply arch/arm/core/irq_manage.c]: Well, before we were just "telling that Kernel uses 0 and 1" which was hardly possible to maintain, and was not educating the reader of the code. I think if we refer to the explicit reasons we add to the maintainability/educability  of the code.

However, no strong opinion. If you want to just explain in detail why we perform the offset, this is OK with me.

File: arch/arm/core/irq_manage.c (hunk 3 above)
Comment (ioannisg) [reply arch/arm/core/irq_manage.c]: This is also an option, yes. Note that we might need to do some more refactoring when calculating the final OFFSET.

File: arch/arm/core/irq_manage.c (hunk 4 above)
Comment (joerchan) [reply arch/arm/core/irq_manage.c]: I'll update the comment along with the use of the define to clarify.
I meant to say the lowest priority level of the reserved ones.

**Review by ioannisg — CHANGES_REQUESTED** [review]

**Review by ioannisg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
Looks good

**Review by galak — DISMISSED** [review]
Can you add more detail about all the changes and how they work in the commit message.  Since this is a non-trivial piece of code, would be good to have a detailed explanation of the changes.

**Comment by ioannisg** [comment]
Looks good, now. @galak , could you take another look?

File: include/arch/arm/cortex_m/exc.h [hunk 5]
```diff
@@ -34,6 +34,12 @@ extern "C" {
 #define _EXCEPTION_RESERVED_PRIO 0
 #endif
 
+#define _EXC_SVC_PRIO 0
+#define _EXC_FAULT_PRIO 0
+#ifdef CONFIG_ZERO_LATENCY_IRQS
```
Comment (galak) [inline include/arch/arm/cortex_m/exc.h]: How about we make this:

```
#ifdef CONFIG_ZERO_LATENCY_IRQS
#define _EXC_ZERO_LATENCY_IRQS_PRIO 1
#define _IRQ_PRIO_OFFSET (_EXCEPTION_RESERVED_PRIO + 1)
#else
#define _IRQ_PRIO_OFFSET (_EXCEPTION_RESERVED_PRIO)
#endif
```

and remove `_ZERO_LATENCY_IRQS_RESERVED_PRIO`

**Review by galak — CHANGES_REQUESTED** [review]
Lets remove _ZERO_LATENCY_IRQS_RESERVED_PRIO, see inline comment.

**Comment by joerchan** [comment]
@galak Updated with your suggestion.

**Review by ioannisg — APPROVED** [review]

**Comment by carlescufi** [comment]
@joerchan can you please create an issue specific to this and add a "Fixes #" comment to this PR description?

**Review by galak — APPROVED** [review]

**Comment by joerchan** [comment]
Fixes #8073

**Comment by carlescufi** [comment]
@joerchan thanks!

**Comment by galak** [comment]
> Fixes #8073

Can you add in the commit message:

Fixes: #8073
