### PR TITLE
Fix race with assertion in z_get_next_switch_handle()

### LINKED ISSUE #98796: Assertion race in z_get_next_switch_handle()
## Describe the bug

An assertion failure occurs in `z_get_next_switch_handle()` at 
kernel/sched.c:865 when running tests/kernel/smp_abort on SMP systems with
3 or more CPUs.

The assertion `old_thread->switch_handle == NULL` fails due to a race
condition where multiple CPUs simultaneously abort threads and use the 
shared dummy thread structure. While one CPU performs a context switch from 
the dummy thread (setting its `switch_handle`), another CPU may check the 
assertion expecting `switch_handle` to be NULL, causing it to fail.

- Target platform: ARM64 FVP (Fixed Virtual Platform) with 3+ CPUs
- The issue is timing-dependent and hardware-specific: it reproduces on 
  FVP but not on QEMU
- Adding debug traces can make the issue disappear due to timing changes
- This is a regression introduced by commit d4d51dc062bf ("kernel: Replace
  redundant switch_handle assignment with assertion")

## Regression

- [x] This is a regression.
- Introduced by: d4d51dc062bf ("kernel: Replace redundant switch_handle
  assignment with assertion")

## Steps to reproduce

1. Configure for an ARM64 FVP board with at least 3 CPUs
2. Build and run tests/kernel/smp_abort
3. The race condition requires precise timing where 3 CPUs simultaneously:
   - CPU0 aborts thread B
   - CPU1 aborts thread C
   - CPU2 aborts thread A
   - Multiple CPUs enter dummy thread state and perform context switches concurrently

## Relevant log output

```
ASSERTION FAIL [old_thread->switch_handle == NULL] @ kernel/sched.c:865
    old thread handle should be null.
```

## Impact

Intermittent – Occurs occasionally; hard to reproduce.
Causes CI to fail.

## Environment

- OS: Linux
- Toolchain: Zephyr SDK
- Platform: ARM64 FVP (Fixed Virtual Platform) with 3+ CPUs
- Commit: d4d51dc062bf or later

## Additional Context

The root cause is that the dummy thread structure is shared among all CPUs
in SMP systems. When multiple CPUs concurrently abort threads, they all use
the same dummy thread instance. The narrow timing window required for the
race makes it hardware-dependent and difficult to reproduce consistently.

The fix involves relaxing the assertion to allow `switch_handle` to be non-NULL when the old thread is the dummy thread: `old_thread->switch_handle ==
NULL || is_thread_dummy(old_thread)`, since the dummy thread can be legitimately clobbered by concurrent CPUs.

Fix available in PR #98682.

### PR DESCRIPTION
**Pull request by npitre**
Commit d4d51dc062bf ("kernel:  Replace redundant switch_handle assignment
with assertion") introduced an assertion check that may be triggered
on SMP systems with more than 2 CPUs.

Fixes #98796

### CODE REVIEW

**Review by wearyzen — COMMENTED** [review]
I was working on fixing the kernel.smp_abort failure on fvp_baser_aemv8r/fvp_aemv8r_aarch64/smp and this solution didn't work for me. What worked for me was having per core instance of the _thread_dummy and that fixed both, the test and the assertion.
I would be pushing the fix with my other changes at the end of the week but I can try to provide just this change if you want to try it.

**Comment by npitre** [comment]
Having a per-CPU instance of the dummy thread would certainly work. But
it is overkill. The dummy thread is meant to be just that: a dummy 
thread. Its only purpose is to be a stub that won't be freed while we 
schedule away from it. The thread structure is far from being small, 
especially on ARM64, so making it per-CPU is rather wasteful.

So if you are affected by the assertion on line 865 of kernel/sched.c 
and this PR doesn't solve it then you have a different issue that needs
further investigation.

**Review by peter-mitsis — APPROVED** [review]

**Comment by npitre** [comment]
@wearyzen: I tested fvp_baser_aemv8r/fvp_aemv8r_aarch64/smp and there is
indeed an additional issue independent from this one. See PR #98817 for
the fix.

**Review by wearyzen — APPROVED** [review]
Thanks this and the other [PR](https://github.com/zephyrproject-rtos/zephyr/pull/98817/files) together fix smp issue for cortex-r as well.

**Review by TaiJuWu — APPROVED** [review]

**Comment by TaiJuWu** [comment]
Thanks for the detailed analysis and catch the race issue.

File: kernel/sched.c [hunk 1]
```diff
@@ -862,7 +862,7 @@ void *z_get_next_switch_handle(void *interrupted)
 	K_SPINLOCK(&_sched_spinlock) {
 		struct k_thread *old_thread = _current, *new_thread;
 
-		__ASSERT(old_thread->switch_handle == NULL,
+		__ASSERT(old_thread->switch_handle == NULL || is_thread_dummy(old_thread),
 			"old thread handle should be null.");
```
Comment (TaiJuWu) [inline kernel/sched.c:866]: Nit: or dummy thread

**Review by cfriedt — APPROVED** [review]
