### PR TITLE
arch: deprecate `z_arch_esf_t` with `struct arch_esf`, introduce an arch-agnostic `exception.h` for it

### LINKED ISSUE #73454: Kernel: Includes: `fatal.h` does not include a header file that defines `z_arch_esf_t`
**Describe the bug**
[fatal.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/fatal.h) has 2 functions that use the `z_arch_esf_t` type: 

```c
void k_sys_fatal_error_handler(unsigned int reason, const z_arch_esf_t *esf);
void z_fatal_error(unsigned int reason, const z_arch_esf_t *esf);
```

but the type is not defined by any header files in the file. 

The type seems to rely on the specific architecture, and have multiple different definitions:
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/arch/arc/v2/exception.h#L23
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/arch/arm/cortex_a_r/exception.h#L78
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/arch/arm/cortex_m/exception.h#L122
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/arch/posix/arch.h#L45

and several others. 
Due to the different architectures, and due to the type not even being defined in similarly named files, it seems non-trivial to find the right header file to include. 

The main issue about this bug is that it will cause issues with certain tools such as `clangd` that cannot find the right includes for static analysis. 

Ideally `fatal.h` should include the files that it uses, and not rely on some specific header files being included before it. 

**To Reproduce**
N/A

**Expected behavior**
`fatal.h` should include a header file that defines the types that it use. 
Alternatively, `fatal.h` should not depend on any specific types for these functions. 

**Impact**
Annoynace

**Logs and console output**
From clangd:
```
Unknown type name 'z_arch_esf_t'
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: c1400536548bb861c630f81d8aced864f1a85ca1

**Additional context**
N/A

### LINKED ISSUE #73673: [RFC] create `struct arch_esf` that is public and deprecate `z_arch_esf_t`
## Introduction

Functions and types that start with the `z_` prefix are meant for internal use only, but we have `z_arch_esf_t` appearing in the public headers/APIs that is sort of an implicit requirement for all architectures.

There are functions/header files using `z_arch_esf_t` while not directly including any header file that defines this named struct.

To complicate the issues mentioned above, the underlying struct names aren't consistent across the archs, which means we can't actually declare the named struct without some macro magic:
- arc - `struct _irq_stack_frame`
- x86 - `struct nanoEsf`
- x86_64 - `struct x86_esf`
- xtensa - `int`
- testsuite - `struct esf`
- arm, arm64, riscv, mips, nios2, posix, sparc - `struct __esf`

### Problem description

This leads to #73454, and blocks #73587.

### Proposed change

Deprecate `z_arch_esf_t`, have all the architecture define `struct arch_esf` and declare this in the `arch_interface.h`

## Detailed RFC

Please see #73593

### Proposed change (Detailed)

Please see #73593

### Dependencies

Any external modules that uses `z_arch_esf_t` has to be updated to use the new `struct arch_esf`, i.e. https://github.com/zephyrproject-rtos/sof/pull/46

### Concerns and Unresolved Questions

TBD

## Alternatives

#73587 can be unblocked by using `void *`, #73454 can be worked around by using macros in the arch-agnostic exception header.

### PR DESCRIPTION
**Pull request by ycsin**
RFC #73673

Fixes #73454

Unblocks #73587

- SOF
  - https://github.com/zephyrproject-rtos/sof/pull/46

[Migration guide preview](https://builds.zephyrproject.io/zephyr/pr/73593/docs/releases/migration-guide-3.7.html#kernel)

### CODE REVIEW

File: include/zephyr/arch/exception.h [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+#elif defined(CONFIG_XTENSA)
+#include <zephyr/arch/xtensa/exception.h>
+#elif defined(CONFIG_MIPS)
+#include <zephyr/arch/mips/exception.h>
+#elif defined(CONFIG_ARCH_POSIX)
+#include <zephyr/arch/posix/exception.h>
+#elif defined(CONFIG_SPARC)
+#include <zephyr/arch/sparc/exception.h>
+#else
+#error "Unknown Architecture"
```
Comment (aescolar) [inline include/zephyr/arch/exception.h:34]: I wouldnt error out, as it would fail for out of tree architectures.
CC @daor-oti

Comment (ycsin) [reply include/zephyr/arch/exception.h:34]: Just want to point out that this isn't something new:

https://github.com/zephyrproject-rtos/zephyr/blob/127cb9edb6c6594e2f09dea7efb335db3cb1f43a/include/zephyr/arch/arch_inlines.h#L35-L37

https://github.com/zephyrproject-rtos/zephyr/blob/127cb9edb6c6594e2f09dea7efb335db3cb1f43a/include/zephyr/arch/cpu.h#L34-L36

Another PR is required if normalization is required

**Comment by Thalley** [comment]
CI issues seems to stem from this https://github.com/zephyrproject-rtos/zephyr/issues/73603

**Review by Thalley — COMMENTED** [review]
Do the changes in this PR (specifically the ones that modify the API in `include/zephyr`), constitute a breaking stable API change? 

Does the PR need to go through https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-breaking-api-changes ?

**Comment by ycsin** [comment]
> Do the changes in this PR (specifically the ones that modify the API in `include/zephyr`), constitute a breaking stable API change?
> 
> Does the PR need to go through https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-breaking-api-changes ?

Maybe - I'm not sure how to deprecate a named struct though, probably wrap its declaration with a Kconfig and generate warning message when the Kconfig is enabled?

**Comment by ycsin** [comment]
Removed all usage of `z_arch_esf_t` from zephyr base.

**Comment by nashif** [comment]
> Do the changes in this PR (specifically the ones that modify the API in `include/zephyr`), constitute a breaking stable API change?
> 
> Does the PR need to go through [docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-breaking-api-changes](https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-breaking-api-changes) ?

well well, z_ has been always used for private APIs, variables, obviously this was wrong used here (and we have a few others of this class), however, if this is deprecagted correctly, it is not a breaking API change and does not follow the process IMO, just the migration documentation.

This change is very welcome, wanted to do that for a long time, never got to it...

**Review by nashif — DISMISSED** [review]

**Comment by ycsin** [comment]
Let's see if `sof` is the only external module affected by this change

**Review by npitre — DISMISSED** [review]

**Review by andyross — DISMISSED** [review]
This looks perfect, thanks.

**Comment by ycsin** [comment]
Updated to git revision of `sof` to point at the hash after the merge of https://github.com/zephyrproject-rtos/sof/pull/46

File: doc/releases/migration-guide-3.7.rst [hunk 2]
```diff
@@ -59,6 +59,11 @@ Build System
 Kernel
 ******
 
+* All architectures are now required to define the new ``struct arch_esf``, which describes the members
```
Comment (aescolar) [inline doc/releases/migration-guide-3.7.rst:62]: Please add a 
```
(:github:`73593`).
```

File: include/zephyr/arch/exception.h (hunk 1 above)
Comment (aescolar) [reply include/zephyr/arch/exception.h:34]: We support out of tree architectures, SOCs, and boards. For out of tree architectures, because they are so rare, out of tree support gets a bit broken every now and then with this kind of changes. This can be worked around/hacked out of tree. But that does not mean we should just keep making it worse for no reason.
I don't think there is any benefit to add this check and error here. So I'd still ask you to not add it.

**Review by aescolar — DISMISSED** [review]

File: include/zephyr/arch/exception.h (hunk 1 above)
Comment (ycsin) [reply include/zephyr/arch/exception.h]: Fair enough, added 2 more commits that will make these headers more consistent

File: doc/releases/migration-guide-3.7.rst (hunk 2 above)
Comment (ycsin) [reply doc/releases/migration-guide-3.7.rst:62]: fixes

**Review by npitre — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by ycsin** [comment]
ping @andyross could you please take another look? Thanks

**Review by andyross — APPROVED** [review]

**Comment by Thalley** [comment]
Thanks for the quick fix @ycsin 

One thing I can see today is that now `zephyr/include/zephyr/arch/arm/cortex_m/exception.h` may be included before `sys_define_gpr_with_alias` has been defined. 

This effectively means that the new generic `exception.h` header cannot be included for ARM before `zephyr/include/zephyr/arch/arm/arch.h` has been included, as `zephyr/include/zephyr/arch/arm/arch.h` defines the `sys_define_gpr_with_alias` macro. 

I almost expect that if we fix the above, yet another include issue will appear. These type of include issues will continue to appear unless verified by a tool (attempting to fix or verify manually will be nearly impossible).

**Comment by Thalley** [comment]
> Thanks for the quick fix @ycsin
> 
> One thing I can see today is that now `zephyr/include/zephyr/arch/arm/cortex_m/exception.h` may be included before `sys_define_gpr_with_alias` has been defined.
> 
> This effectively means that the new generic `exception.h` header cannot be included for ARM before `zephyr/include/zephyr/arch/arm/arch.h` has been included, as `zephyr/include/zephyr/arch/arm/arch.h` defines the `sys_define_gpr_with_alias` macro.
> 
> I almost expect that if we fix the above, yet another include issue will appear. These type of include issues will continue to appear unless verified by a tool (attempting to fix or verify manually will be nearly impossible).

@ycsin are you looking into this? Otherwise I'll go ahead and create another issue :) 

If you are not already, you may want to use a tool like the `clang` `includer-cleaner` or `clangd` to catch future issues.

**Comment by ycsin** [comment]
> @ycsin are you looking into this? Otherwise I'll go ahead and create another issue :)

Not looking into this, please feel free to create another issue

**Comment by Thalley** [comment]
> > @ycsin are you looking into this? Otherwise I'll go ahead and create another issue :)
> 
> Not looking into this, please feel free to create another issue

The fix for this was quite simple, so decided to take a look at fixing it myself: https://github.com/zephyrproject-rtos/zephyr/pull/74106
