### PR TITLE
net: posix Fix name collision with __bswap

### LINKED ISSUE #44324: Compile error in byteorder.h
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/44190

<div type='discussions-op-text'>

<sup>Originally posted by **surfskidude** March 24, 2022</sup>
I cloned the latest today and I got a compile error when I compiled my existing code, which includes net/socket.h

In file included from /home/build/zephyrproject/zephyr/include/net/net_ip.h:27,
                 from /home/build/zephyrproject/zephyr/include/net/socket.h:27,
/home/build/zephyrproject/zephyr/include/sys/byteorder.h:22:36: error: expected declaration specifiers or ‘...’ before ‘(’ token
   22 | #define __bswap_16(x) ((uint16_t) ((((x) >> 8) & 0xff) | (((x) & 0xff) << 8)))
      |                                    ^
/home/build/zephyrproject/zephyr/include/sys/byteorder.h:26:36: error: expected declaration specifiers or ‘...’ before ‘(’ token
   26 | #define __bswap_32(x) ((uint32_t) ((((x) >> 24) & 0xff) | \
      |                                    ^
/home/build/zephyrproject/zephyr/include/sys/byteorder.h:36:36: error: expected declaration specifiers or ‘...’ before ‘(’ token
   36 | #define __bswap_64(x) ((uint64_t) ((((x) >> 56) & 0xff) | \
      |                                    ^

Build:
west build -p auto -b native_posix_64 myproject
</div>

### PR DESCRIPTION
**Pull request by Jonathan-Hamberg**
__bswap in zephyr/sys/byteorder.h conflicts with __bswap in host's byteswap.h. byteswap.h from host compiler used in posix_native_64 boards causes a compilation issue.

This commit renames __bswap to __z_bswap to prevent collision.

Before this commit a compilation error can be created by adding #include <byteswap.h> to samples/net/sockets/echo/src/socket_echo.c

This does not change external API to byteorder.h, but does change internal implementation which some other source files depend on.

Fixes #44324

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
(over to Base OS maintainers)

File: include/zephyr/sys/byteorder.h [hunk 1]
```diff
@@ -17,21 +17,21 @@
 #include <zephyr/toolchain.h>
 
 /* Internal helpers only used by the sys_* APIs further below */
-#define __bswap_16(x) ((uint16_t) ((((x) >> 8) & 0xff) | (((x) & 0xff) << 8)))
-#define __bswap_24(x) ((uint32_t) ((((x) >> 16) & 0xff) | \
+#define __z_bswap_16(x) ((uint16_t) ((((x) >> 8) & 0xff) | (((x) & 0xff) << 8)))
+#define __z_bswap_24(x) ((uint32_t) ((((x) >> 16) & 0xff) | \
```
Comment (jukkar) [inline include/zephyr/sys/byteorder.h:21]: Instead of lot of changes, why not do it something like this so that we do not need to change the name of the macro
```
#if !defined(__bswap_16)
#define __bswap_16 ....
#endif  
```

**Comment by cfriedt** [comment]
Way out of scope of this PR, but related to the root cause of this issue.

It would be nice if there were zero reliance / inclusion of host headers and libc at all in the Zephyr build for native (Linux) platforms.

That's kind of the air gap that we need for the to avoid C namespace collisions and to not at all link with the host libc.

It's not _that_ hard to generate syscall wrappers for Linux. Android does it for Bionic and those projects are Apache 2.0 / BSD licensed.

https://android.googlesource.com/platform/bionic/+/android-4.2.2_r1/libc/SYSCALLS.TXT

The scope is relatively small since we only support x86_64 (x86?) and aarch64 today.

**Review by aescolar — COMMENTED** [review]
Thanks @Jonathan-Hamberg
This is a just very mild rejection without even a -1. As this PR solves the problem, but maybe we should fix it in a nicer way:

If we take the description of these macros as is, it seems this code and the other files this PR is fixing should not be using these macros.
But, there may be a legitimate need for them:
There is a need to use the functionality, and we may not be able to just rely on the C library bswap_xx() (pico and newlib have it), minimal doesn't.
I see a couple of options:
a) the code which is using this uses the std C library bswap_xx() instead and sets the REQUIRES_FULL_LIBC kconfig.
b) We define them with a proper Zephyr public name, i.e. `BSWAP_32()`, and we convert the code to use those.

Note that this issue is due to Zephyr using the "reserved" namespace area of `__`, which in this case conflicts with some versions of glibc. But it could have been any other C library, as these macros are using the std library function names just prefixed with two `_`. 

Related to #58007

**Comment by andyross** [comment]
> It would be nice if there were zero reliance / inclusion of host headers and libc at all in the Zephyr build for native (Linux) platforms.

I'm tempted to agree in principle as a matter of engineering practice.  But the counterargument is that my experience when doing work/debugging/general-muckery with native_posix is that it's **extremely convenient** to be "Just Writing A Regular Linux Program" and to have access to native APIs in their native form without having to jump through a thunking layer or link into a different file or whatever.   It would be sad to give that up, though it's also true it exposes us to this kind of annoyance.

**Review by andyross — COMMENTED** [review]
It's always the simple syntax changes that become bikesheds.  But just to add my own layer of paint:

> This commit renames __bswap to __z_bswap to prevent collision.

FWIW "z_" is already an internal API prefix[1], so just "`z_bswap_32()`" is sufficient and cleaner.

[1] Though one we keep going back and forth on as to whether we want to keep it.   I think current zeitgeist is that we should go back to underscores, actually?  Regardless we've never exposed it as an API prefix to Zephyr app code so it's safe to use here.

**Comment by Jonathan-Hamberg** [comment]
@aescolar 
> a) the code which is using this uses the std C library bswap_xx() instead and sets the REQUIRES_FULL_LIBC kconfig. 
> b) We define them with a proper Zephyr public name, i.e. `BSWAP_32()`, and we convert the code to use those.

In regards to a) I see that sys/byteswap.h is used is several drivers.  I'm not sure if REQUIRES_FULL_LIBC would work in these scenarios for the use of a simple byteswap API.  It might add some complexity to this PR to add this sort of dependency.

From my perspective it seems easier to just use approach b) to prevent this name collision from happening.  Because __bswap_ is a macro it seems that BSWAP_32 might be more appropriate compared to z_bswap_32 which would seem to imply a function.  I wasn't able to find any reference to a naming scheme for macros in the zephyr naming convention online.  Please let me know if you have a preference?

> It would be nice if there were zero reliance / inclusion of host headers and libc at all in the Zephyr build for native (Linux) platforms.
In regards to this it seems that native_posix_64 should continue to have access to the host libc.  There is a board called native_sim that replaces the host libc with Zephyr's version.  This would also seem to resolve this problem if you are worried about conflicts with the host libc implementation, but I would like to make that byteswap.h is compatible with the native_posix_64 board.

**Comment by aescolar** [comment]
> In regards to a) I see that..

I think you are right..

So for b),
I don't think the project is extremely consistent today with the macro naming, but I think using capitalized names would be better if not a must for something we are fixing. I'd capitalize and would not use the Z_ prefix to be consistent with other public macros)*1
Maybe somebody who has paid more attention to this naming issues can comment or provide a better alternative but I'd go with `BSWAP_<size>`.
If it was me, I'd even go the extra mile and define Z_BSWAP (*2) in the gcc toolchain header calling into the equivalent builtin; and then have the generic one be defined something like:
```
#ifdef Z_BSAWP<size>
#define BSWAP_<size>(a)  Z_BSAWP<size>(a)
#else 
#define BSWAP_<size>(a) (the current and'oring circus)
#endif
```

*1 (Though @andyross is right that z_bswapxx() is already fixing the issue and probably better than __z_bswap, and I honestly feel quite uncomfortable with not namespacing Zephyr macros away, I think BSWAPxx() will be more consistent given the current project direction).
*2 (did somebody make a conscious decision to use Z_WHATEVER for the compiler specific version of the macro WHATEVER ? or did that just happen ?)

> I think current zeitgeist is that we should go back to underscores, actually?

If anything the issue this PR is solving would be a hint that we should not move in that direction.

**Comment by Jonathan-Hamberg** [comment]
@aescolar I've implemented the name change you've suggested for the swap calls.  Please let me know if there is anything else that should be addressed for this PR.

Just wanted to say thanks to everyone who reviewed this PR.  As it was my first one I really appreciate the warm welcome and positive suggestions.

File: include/zephyr/sys/byteorder.h [hunk 2]
```diff
@@ -17,21 +17,21 @@
 #include <zephyr/toolchain.h>
 
 /* Internal helpers only used by the sys_* APIs further below */
```
Comment (aescolar) [inline include/zephyr/sys/byteorder.h:19]: I forgot to mention, we should probably remove this line, as we are not anymore keeping this as internal

**Review by aescolar — DISMISSED** [review]
Thanks, if you could remove that comment that would be very nice. Otherwise it looks fine to me.

**Review by cfriedt — DISMISSED** [review]

**Review by aescolar — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by andyross — APPROVED** [review]
