### PR TITLE
Bluetooth: host: Fix ATT indication deadlock in RX thread

### LINKED ISSUE #28685: Bluetooth: Characteristic unsubscribe under indication load results in ATT timeout
**Describe the bug**

Conditions:
* Zephyr device acting as a GATT server
* Many indications are being generated in a loop in response to an event (accelerometer)
* GATT client attempts to unsubscribe from the indication characteristic while indications are queued

This sequence reliably results in an ATT timeout, normally due to a failure to allocate a buffer for the "write response" to the CCC write. The unsubscribe request in the below log is sent at ~00:02:07.
```
00> [00:02:03.931,365] <wrn> uc_bt_gatt: DATA: Subscribed 2
00> [00:02:37.906,616] <wrn> bt_conn: Unable to allocate buffer within timeout
00> [00:02:37.906,646] <err> bt_att: Unable to allocate buffer for op 0x13, 0
00> [00:02:37.919,097] <err> bt_att: ATT Timeout
00> [00:02:37.919,128] <wrn> uc_bt_gatt: DATA: Indication failed 14
00> [00:02:37.919,158] <wrn> uc_bt_gatt: DATA: Indication failed 14
00> [00:02:37.919,158] <wrn> uc_bt_gatt: DATA: Indication failed 14
00> [00:02:37.919,219] <wrn> uc_bt_gatt: DATA: Subscribed 0
00> [00:02:37.919,250] <err> bt_conn: not connected!
00> [00:02:37.919,281] <wrn> bt_att: No pending ATT request
00> [00:02:37.919,372] <err> bt_gatt: Error sending ATT PDU: -128
```

On the server, indications are broadcast normally to anyone that has subscribed through:
```
for (int i = 0; i < 10; i++) {
    indicate_params.attr = &uc_svc.attrs[DATA_ATTR_INDEX];
    indicate_params.data = message->data;
    indicate_params.len = message->len;
    indicate_params.func = uc_bt_data_indicate_cb;
    bt_gatt_indicate(NULL, &indicate_params);
}
```
With the `uc_bt_data_indicate_cb` printing the errors from the above log
```
if (err) {
	LOG_WRN("DATA: Indication failed %d", err);
}
```

Presumably all available TX buffers have been claimed by the indication loop, leaving no buffers for the write response.

Probably relevant Kconfig symbols
```
#define CONFIG_BT_CTLR_RX_BUFFERS 6
#define CONFIG_BT_CTLR_TX_BUFFERS 3
#define CONFIG_BT_CTLR_TX_BUFFER_SIZE 251
#define CONFIG_BT_CTLR_TX_PWR_PLUS_8 1
#define CONFIG_BT_CTLR_LE_ENC 1
#define CONFIG_BT_CTLR_CONN_PARAM_REQ 1
#define CONFIG_BT_CTLR_EXT_REJ_IND 1
#define CONFIG_BT_CTLR_SLAVE_FEAT_REQ 1
#define CONFIG_BT_CTLR_LE_PING 1
#define CONFIG_BT_CTLR_PRIVACY 1
#define CONFIG_BT_CTLR_RL_SIZE 8
#define CONFIG_BT_CTLR_EXT_SCAN_FP 1
#define CONFIG_BT_CTLR_DATA_LENGTH 1
#define CONFIG_BT_CTLR_DATA_LENGTH_MAX 251
#define CONFIG_BT_CTLR_MIN_USED_CHAN 1
#define CONFIG_BT_CTLR_CHAN_SEL_2 1
#define CONFIG_BT_HCI_CMD_COUNT 2
#define CONFIG_BT_RX_BUF_COUNT 3
#define CONFIG_BT_RX_BUF_LEN 76
#define CONFIG_BT_CONN_TX_MAX 3
#define CONFIG_BT_AUTO_DATA_LEN_UPDATE 1
#define CONFIG_BT_L2CAP_RX_MTU 252
#define CONFIG_BT_L2CAP_TX_BUF_COUNT 3
#define CONFIG_BT_L2CAP_TX_FRAG_COUNT 2
#define CONFIG_BT_L2CAP_TX_MTU 252
#define CONFIG_BT_ATT_ENFORCE_FLOW 1
#define CONFIG_BT_ATT_PREPARE_COUNT 0
#define CONFIG_BT_ATT_TX_MAX 3
```

**Expected behavior**
Server should respond with an acknowledgement to the CCC write, and any pending indications should be dropped.

While this is caused by insufficient `CONFIG_BT_CTLR_TX_BUFFERS`, it should be possible for the controller to iterate over queued packets on a characteristic if it is being unsubscribed from and dequeue them before trying to allocate the write response packet.

**Impact**
Annoyance, normally we don't unsubscribe until we are done with a connection.
While the connection is unusable after an ATT Timeout, reconnecting fixes the issue.

Increasing `CONFIG_BT_CTLR_TX_BUFFERS` from the default value also reduces the chances of the TX buffer starvation.

**Logs and console output**

Wireshark Capture of the server failing to respond (unacknowledged write is packet 1127)
[IndicateUnsub.zip](https://github.com/zephyrproject-rtos/zephyr/files/5280073/IndicateUnsub.zip)

**Environment (please complete the following information):**
 - Zephyr 2.4-rc3

**Workaround:**
Make sure that ATT requests cannot acquire all the buffers in the system setting CONFIG_BT_L2CAP_TX_BUF_COUNT  >= CONFIG_BT_ATT_TX_MAX + 2

### PR DESCRIPTION
**Pull request by joerchan**
Fix deadlock in RX thread when ATT all buffers are taken by ATT requests and the RX thread blocks waiting for an buffer.
Solve this by not having a reference to the ATT request buffer until the ATT response is received, instead get a new ATT buffer in the case where it has to be resent.

Fixes: #28685

Fix ATT transaction violation in indications if the application has not set a callback function. In this case the indication was not treated as a transaction, leading to transaction violation.

Fix security elevation not working properly when the elevation is done in a two-step, this can happen when MITM is not enforced and security level 3 is required on the attribute.

Fix SMP debug keys overwrite handling not allowing to overwrite debug keys with debug keys, and allowing debug keys to overwrite existing bond information.

### CODE REVIEW

**Comment by carlescufi** [comment]
Thanks for the PR @joerchan. This is quite a big change, so I'd like to ask you, what kind of regression tests have you performed on it?

**Comment by joerchan** [comment]
> Thanks for the PR @joerchan. This is quite a big change, so I'd like to ask you, what kind of regression tests have you performed on it?

I have run the EDTT test suite locally, and reproduced and verified the issues I'm fixing.
The change might look big, but most of the changes in gatt is just moving of code.

The PR can be split into smaller pieces, if that is preferable.

**Comment by carlescufi** [comment]
> > Thanks for the PR @joerchan. This is quite a big change, so I'd like to ask you, what kind of regression tests have you performed on it?
> 
> I have run the EDTT test suite locally, and reproduced and verified the issues I'm fixing.
> The change might look big, but most of the changes in gatt is just moving of code.

Sounds good, would you mind also running the throughput sample of nRF Connect SDK, as well as any others that might be applicable? I know that some of the samples there put the stack under heavy stress.

> The PR can be split into smaller pieces, if that is preferable.

I don't see any particular reason to do that in this case.

**Comment by carlescufi** [comment]
@Vudentz we'd like to try and get this in for 2.5, please take a look.

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -3828,14 +3827,7 @@ int bt_gatt_write_without_response_cb(struct bt_conn *conn, uint16_t handle,
...
 	cmd->handle = sys_cpu_to_le16(handle);
-
-	write = net_buf_append_bytes(buf, length, data, K_NO_WAIT, NULL, NULL);
-	if (write != length) {
-		BT_WARN("Unable to allocate length %u: only %zu written",
-			length, write);
-		net_buf_unref(buf);
-		return -ENOMEM;
-	}
+	net_buf_add_mem(buf, data, length);
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c:3886]: Actually this assumption that the response cannot be bigger than then a single buffer is incorrect for EATT, EATT can in fact have channels which MTU is bigger then MPS which is why net_buf_append_bytes was used so it can allocate multiple buffers if necessary.

File: subsys/bluetooth/host/att_internal.h [hunk 2]
```diff
@@ -263,14 +263,19 @@ typedef void (*bt_att_func_t)(struct bt_conn *conn, uint8_t err,
...
+
 /* ATT request context */
 struct bt_att_req {
 	sys_snode_t node;
 	bt_att_func_t func;
-	struct net_buf_simple_state state;
 	struct net_buf *buf;
 #if defined(CONFIG_BT_SMP)
-	bool retrying;
+	bt_att_write_buf_t write_buf;
```
Comment (Vudentz) [inline subsys/bluetooth/host/att_internal.h:275]: I wonder if it wouldn't be a better idea to push the resend logic to gatt.c then, since now we would need to callbacks back to it to encode the request again it might be better to have everything there and perhaps have something like bt_att_resend to prepend the request on the queue, anyway we can make this change later as well if we find it necessary.

**Review by Vudentz — CHANGES_REQUESTED** [review]
Lets just drop the commit that removes the use of net_buf_append_bytes then Im good with this set.

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:3886]: @Vudentz As far as I can tell the buf allocated is sized according to the MTU, not the MPS, and when sending the ATT PDU then L2CAP will handle splitting the MTU up into MPS sized fragment if needed. To me this looks like something that is handled properly and does not include GATT/ATT.

The reason why I removed the net_buf_append_bytes was because allocate_cb argument was set to NULL, which means that if this call would have had to allocate more buffers it would have crashed, because the allocate_cb is not checked for non-NULL.

And by not having the return value of net_buf_append_bytes the write_buf callback could be simplified since it does not have to handle failures at the moment.

Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c:3886]: @joerchan no it is not allocated according to the remote MTU, in EATT MTUs are not required to be symmetric, that would mean that one cannot take advantage of having bigger MTU because the code can only use a single buffer.

That said if net_buf_append_bytes does require a callback we should provide one, @asbjornsabo this might explain our crashes with EATT with some platforms as they might have bigger MTU then our buffer size.

Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c:3886]: This should take care of the allocation callback being NULL: https://github.com/zephyrproject-rtos/zephyr/pull/31493

**Comment by joerchan** [comment]
@Vudentz I have put back the use of net_buf_append_bytes.

I also found another issue where the buf for the ATT request was not always freed.
On master branch this can be seen when the buffer is successfully allocated, but the storage for the ATT request is not successful and returns error. In this case an error code is returned without the buffer being freed.

In order to fix this issue I put released of the ATT request buffer into the `bt_att_req_free` function, and eliminated the ATT internal `att_req_destroy` function.

The changes since last view can bee looked at here:
https://github.com/zephyrproject-rtos/zephyr/compare/3b4b9c62882a3eb72d4972e822b9b0c9a0a2c571..329c2e9358ae77c0ff301c8305364e1c1d6f7ede

Regarding the use of net_buf_append_bytes, I still don't understand why this should be there, and I think maybe you misunderstood what I said?
The size of the buf is determined by our L2CAP TX MTU, you said "no it is not allocated according to the remote MTU".
I'm sure that the condition write != len will never happen because we check this before we allocate the buffer, and either allocate a write-request, or a prepare-write-req with the L2CAP TX MTU.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/smp.c [hunk 3]
```diff
@@ -3059,6 +3057,13 @@ static int smp_send_pairing_req(struct bt_conn *conn)
 		return -EIO;
 	}
 
+	/* A higher security level is requested during the key distribution
+	 * phase, once pairing is complete a new pairing procedure will start.
+	 */
+	if (atomic_test_bit(smp->flags, SMP_FLAG_KEYS_DISTR)) {
+		return 0;
+	}
```
Comment (sjanc) [inline subsys/bluetooth/host/smp.c:3065]: SMP_FLAG_KEYS_DISTR is set from bt_smp_encrypt_change() so this depends on order of registering channels

since channels are registered via BT_L2CAP_CHANNEL_DEFINE macro order seems to depend on linker action

Comment (joerchan) [reply subsys/bluetooth/host/smp.c:3065]: I looked into the finished `zephyr.elf` and this is the order.
```
<att_fixed_chan>:
 <le_fixed_chan>:
<smp_fixed_chan>:
```
I'm pretty sure that the order is alphabetical, because the we seem to rely on this behavior for the static GATT service declararions, e.g:
```
<_1_gatt_svc>:
<_2_gap_svc>:

**Comment by joerchan** [comment]
> Sounds good, would you mind also running the throughput sample of nRF Connect SDK, as well as any others that might be applicable? I know that some of the samples there put the stack under heavy stress.

@carlescufi Done some smoke-tests with the throughput sample and the nrf desktop application, and didn't find any issues.

File: subsys/bluetooth/host/smp.c (hunk 3 above)
Comment (sjanc) [reply subsys/bluetooth/host/smp.c:3065]: fair enough :-)

**Comment by Vudentz** [comment]
> @Vudentz I have put back the use of net_buf_append_bytes.
> 
> I also found another issue where the buf for the ATT request was not always freed.
> On master branch this can be seen when the buffer is successfully allocated, but the storage for the ATT request is not successful and returns error. In this case an error code is returned without the buffer being freed.
> 
> In order to fix this issue I put released of the ATT request buffer into the `bt_att_req_free` function, and eliminated the ATT internal `att_req_destroy` function.
> 
> The changes since last view can bee looked at here:
> https://github.com/zephyrproject-rtos/zephyr/compare/3b4b9c62882a3eb72d4972e822b9b0c9a0a2c571..329c2e9358ae77c0ff301c8305364e1c1d6f7ede
> 
> Regarding the use of net_buf_append_bytes, I still don't understand why this should be there, and I think maybe you misunderstood what I said?
> The size of the buf is determined by our L2CAP TX MTU, you said "no it is not allocated according to the remote MTU".
> I'm sure that the condition write != len will never happen because we check this before we allocate the buffer, and either allocate a write-request, or a prepare-write-req with the L2CAP TX MTU.

The chan.tx.mtu doesn't need to match by our L2CAP TX MTU, that is precisely why net_buf_append_bytes is used, though it looks like we could use net_buf_append_bytes in other places like:
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/att.c#L1064

File: subsys/bluetooth/host/gatt.c [hunk 4]
```diff
@@ -3884,47 +3985,69 @@ static void gatt_prepare_write_rsp(struct bt_conn *conn, uint8_t err,
...
-	len = MIN(params->length, bt_att_get_mtu(conn) - sizeof(*req) - 1);
+	req = net_buf_add(buf, sizeof(*req));
+	req->handle = sys_cpu_to_le16(params->handle);
+	req->offset = sys_cpu_to_le16(params->offset);
 
-	buf = bt_att_create_pdu(conn, BT_ATT_OP_PREPARE_WRITE_REQ,
-				sizeof(*req) + len);
-	if (!buf) {
+	data = ((uint8_t *)params->data) + params->offset;
+	write = net_buf_append_bytes(buf, len - sizeof(*req), data,
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c:4001]: I can't quite understand why are you skipping the offset? The original code used params->data directly, the offset is meant for the server where to start writing not for the client.

File: subsys/bluetooth/host/gatt.c [hunk 5]
```diff
@@ -1910,44 +1910,75 @@ static void gatt_indicate_rsp(struct bt_conn *conn, uint8_t err,
...
-		req->user_data = params;
+	req->buf = buf;
 
-		err = bt_att_req_send(conn, req);
-		if (err) {
-			bt_att_req_free(req);
-		}
-	} else {
-		err = bt_att_send(conn, buf, NULL, NULL);
+	err = write_buf(buf, len, params);
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c:1959]: Btw, we could in theory just encode when the request is actually about to be sent, meaning we don't have to allocate a buffer instead att.c would allocate one just as it does when resending and call write_buf, actually perhaps we should use the encode instead of write_buf.

File: subsys/bluetooth/host/gatt.c [hunk 6]
```diff
@@ -1910,44 +1910,75 @@ static void gatt_indicate_rsp(struct bt_conn *conn, uint8_t err,
...
-		     bt_att_func_t func, void *params)
+static struct bt_att_req *gatt_req_alloc(bt_att_func_t func, void *params,
+					 bt_att_write_buf_t write_buf,
+					 uint8_t op,
+					 size_t len)
 {
+	struct bt_att_req *req;
+
+	/* Allocate new request */
+	req = bt_att_req_alloc(BT_ATT_TIMEOUT);
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c:1921]: We might be better off chaning bt_att_req_alloc to take all these parameters intead of having a wrapper on gatt.c that just initializes the structure.

File: subsys/bluetooth/host/gatt.c (hunk 4 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:4001]: The reason why I changed this code was because data pointer should not be modified, otherwise the encode function cannot properly re-encode it when resending.
But you are right, my change would not work properly in the case where the application has set an offset.

I have fixed this now, the data pointer is manipulated, as well as the length and offset like it was in the original code, except it is now  done once the prepare_write_rsp has been received.

There was also an off-by one error, and the EDTT tests did not catch this, I have tested it manually with the shell now.
Also added a fix to the shell for when the hex convert failed.

File: subsys/bluetooth/host/gatt.c (hunk 5 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:1959]: I have changed the name to 'encode'. However the change to just encode once sent I think is best to leave until after the release.

File: subsys/bluetooth/host/gatt.c (hunk 6 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:1921]: The reason why that wasn't possible at the moment was the bt_gatt_indicate. In order to make indications fit we will have to add a stack internal variable in the indication params to hold the resolved handle, since finding the handle is a rather complicated piece of code and should be kept out of the encode function IMO.

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]
