### PR TITLE
drivers: i2c: esp32: set timeout to allow clock stretching

### LINKED ISSUE #51351: I2C: ESP32 driver does not support longer clock stretching
**Describe the bug**

I'm trying to make the ESP32-C3 talk to a TI bq76952 battery management IC (full hardware design [here](https://github.com/LibreSolar/bms-c1)). Exactly the same firmware works fine with an STM32G0B1. With the ESP32-C3 almost all I2C communication attempts fail.

Below an example of a failed I2C transaction to read the device ID:

image

The same command looks like this with the STM32.

image

It can be observed that in both cases, the SCL is held low by the bq76952 towards the end (most probably because the device is busy with internal calculations). However, for the ESP32-C3 we suddenly see an 0xFF on the bus, which was not requested and does not belong there, whereas in case of the STM32 the communication continues after the clock stretching has finished.

**To Reproduce**

Custom board with ESP32-C3 and bq76952 is required, it will be difficult to reproduce with standard boards.

**Expected behavior**

The I2C communication handles clock stretching properly.

**Impact**

Communication with that chip does not work.

**Environment (please complete the following information):**

 - Commit SHA: f37ebf48ece1892771719321fca95156fd2e50c6

### PR DESCRIPTION
**Pull request by martinjaeger**
The ESP32 series MCUs allow to set a timeout which triggers an error if the SCL line is unchanged for the specified amount of time.

By default, the ESP-IDF HAL sets the timeout to an arbitrary value of 10 times the bus cycle.

This is not sufficient for chips like the TI bq76952, which pulls the SCL line low (clock stretching) for several 100 µs.

The timeout should also not be dependent on the chosen bitrate, as it is defined by the time a chip needs for internal calculation before it can provide requested data or continue communication.

This commit adds a property to devicetree to allow configuration of the scl timeout. This value is set via direct register access, as the ESP-IDF HAL does not provide access to the enable bit and does not give any information about the maximum size of the timeout (defined in I2C clock cycles in the register).

Fixes #51351

## Remarks / Questions

1. As mentioned in the comment, the `I2C_TIME_OUT_EN` did not work as expected for the ESP32-C3. Maybe someone from Espressif can double-check internally if clearing this bit should disable the timeout. The communication only worked with the value set to `0x1F`. The documentation is not very detailed, so maybe my understanding is wrong.
2. The timeout value for ESP32-C3 is only 5 bits wide, which means that the maximum number of clock cycles can be `0x1F = 31`. With an I2C peripheral clock speed of 40 MHz, that would result in a maximum timeout of less than 1 µs, if my calculation is correct. However, in reality it does not time out for >200 µs (see logic analyzer screenshots in the issue). And if the maximum timeout was actually 1µs it would probably not be able to communicate with the bq76952 at all. What did I understand wrong? Or does using the maximum value actually completely disable the timeout feature?

### CODE REVIEW

File: drivers/i2c/i2c_esp32.c [hunk 1]
```diff
@@ -272,6 +294,7 @@ static int i2c_esp32_configure(const struct device *dev, uint32_t dev_config)
 	}
 
 	i2c_hal_set_bus_timing(&data->hal, config->bitrate, i2c_get_clk_src(config->bitrate));
+	i2c_esp32_configure_timeout(dev);
```
Comment (sylvioalves) [inline drivers/i2c/i2c_esp32.c:297]: I will review this, but, have checked `i2c_hal_set_tout()` function? It sets the i2C timeout and might be used in here instead.

Comment (martinjaeger) [reply drivers/i2c/i2c_esp32.c:297]: Yes, I did, but it does not allow to completely disable the timeout function using the `I2C_TIME_OUT_EN` bit mentioned in the reference manual. My initial goal was to use that bit to disable it by default. Unfortunately, this did not have any effect during my tests.

Also the HAL function does not perform any checks whether the value is too large or not. And it expects the value in number of clocks format instead of milliseconds or another time unit. So I decided to access the registers directly, as we need to get the maximum size of the value from the reg define and the clock frequency by other means anyways.

File: drivers/i2c/i2c_esp32.c [hunk 2]
```diff
@@ -238,6 +239,27 @@ static int i2c_esp32_recover(const struct device *dev)
...
+{
+	const struct i2c_esp32_config *config = dev->config;
+
+	if (config->scl_timeout > 0) {
+		i2c_sclk_t sclk = i2c_get_clk_src(config->bitrate);
+		uint32_t clk_freq_mhz = I2C_LL_CLK_SRC_FREQ(sclk);
+		uint32_t timeout_cycles = MIN(I2C_TIME_OUT_REG_V,
+					      clk_freq_mhz / MHZ(1) * config->scl_timeout);
+		sys_clear_bits(I2C_TO_REG(config->index), I2C_TIME_OUT_REG);
+		sys_set_bits(I2C_TO_REG(config->index), timeout_cycles << I2C_TIME_OUT_REG_S);
```
Comment (teburd) [inline drivers/i2c/i2c_esp32.c:252]: Did you want to mask or limit the maximum timeout here? Doesn't seem bound anywhere other than by the shift. If timeout_cycles is large and a shift left is done the timeout could unexpectedly be quite low no?

**Review by teburd — APPROVED** [review]
cool feature, might be nice to set a maximum bound which I didn't see.

File: drivers/i2c/i2c_esp32.c (hunk 2 above)
Comment (martinjaeger) [reply drivers/i2c/i2c_esp32.c:252]: It's already bound by the `MIN(a, b)` above, which limits the value to the maximum amount of bits allowed for that section of the register. Also the `I2C_TIME_OUT_REG_S` is actually 0 for all current ESP32 chips, but wanted to keep it generic.

**Review by sylvioalves — APPROVED** [review]
