### PR TITLE
drivers: flash: nrf_qspi_nor: remove multithreading dependency

### LINKED ISSUE #26372: qspi driver does not work if multithreading is disabled
**Describe the bug**
Build `zephyr/samples/drivers/spi_flash`. Check that it works. Disable multithreading and observe crash with MPU fault.

I have modified the sample so it only performs the read operation (I found the problem while working with mcuboot, when it tries to read image header). I see that all addresses are set but at some point driver waits for completion (k_sem_take). System crashes at some point after this is called or when interrupt handler tries to restore main.

**To Reproduce**
In description.

**Expected behavior**
The driver should work. If it does not it should depend on specific system options that are required.

**Impact**
I need this driver in mcuboot. So far the bootloader works without multithreading. If I would have to enabled the multithreading the size of the bootloader will increase so the bug can be considered critical.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
master

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pabigot**
Replace semaphores with an atomic ready flag when used without multithreading enabled.

DNM until dependent PR is merged:
- [x] #28679 

Fixes #26372

Tested manually on samples/drivers/spi_flash and samples/subsys/fs/littlefs.

### CODE REVIEW

**Comment by ioannisg** [comment]
#28679 is now merged.

File: drivers/flash/nrf_qspi_nor.c [hunk 1]
```diff
@@ -83,8 +83,12 @@ struct qspi_cmd {
  *  device is enabled
```
Comment (ioannisg) [inline drivers/flash/nrf_qspi_nor.c:83]: Could you add some doxygen description for the ready variable in the single-thread case? I am not sure how this could be done "conditionally". Alternatively, you could move the documentation inline , in the stucture

File: drivers/flash/nrf_qspi_nor.c [hunk 2]
```diff
@@ -262,13 +276,23 @@ static inline void qspi_wait_for_completion(const struct device *dev,
 	struct qspi_nor_data *dev_data = get_dev_data(dev);
 
 	if (res == NRFX_SUCCESS) {
+#ifdef CONFIG_MULTITHREADING
 		k_sem_take(&dev_data->sync, K_FOREVER);
+#else /* CONFIG_MULTITHREADING */
+		while (!atomic_cas(&dev_data->ready, 1, 0)) {
+			/* spin */
```
Comment (ioannisg) [inline drivers/flash/nrf_qspi_nor.c:283]: Is the variable going to become ready in an IRQ context? If so, I wonder if we could replace the spin with cpu-idling. Otherwise, it should be as it is now

**Review by ioannisg — COMMENTED** [review]
LGTM. I left one minor comment, and one question about doing cpu-idling.

**Comment by ioannisg** [comment]
@de-nordic @nvlsianpu or @anangl mind helping out with a minor review here?

File: drivers/flash/nrf_qspi_nor.c (hunk 1 above)
Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c]: I hadn't even noticed the documentation hidden up there in a block.  Moved field doc into the structure and added the new field.

File: drivers/flash/nrf_qspi_nor.c (hunk 2 above)
Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c:287]: It is, and I have no idea how to idle the cpu and still detect completion without explicitly using `SEV/WFE` instructions which seems too low-level.  Is there existing arch API for this?

Comment (ioannisg) [reply drivers/flash/nrf_qspi_nor.c:287]: Yes, there is k_cpu_idle() which uses WFI in Cortex-M.

Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c:287]: And is that guaranteed reliable?  Normally I do `SEV;WFE` at a point where I know it's before the signal, to avoid a race condition of idling just after the flag was set.

Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c:287]: OK, it seems to work, gets rid of the ready flag.  Will update.

Comment (nvlsianpu) [reply drivers/flash/nrf_qspi_nor.c]: what is the guaranty that thread will be resumed only on a qspi complete operation event.

Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c]: That this is running the only "thread".  It also means there can't be any other pending interrupt activities that might wake it up instead.  Which is reasonable to expect with a threadless system, but does make `k_timer` unsupportable.  (I think `k_sleep()` can be made to work, though.)

If we go this way we won't be able to overlap operations that signal completion with an interrupt, though.  That's probably a limitation we'll have to live with; or we revert to the spin-wait solution and never idle; or to idle we'd need an event recording solution like [this](https://pabigot.github.io/nrfcxx/classnrfcxx_1_1event__set.html#details).

Comment (ioannisg) [reply drivers/flash/nrf_qspi_nor.c]: @pabigot do you need to lock interrupts before calling k_cpu_idle()? That's because k_cpu_idle() in Cortex-m uses WFI, not WFE. what will happen if the ISR fires before you manage to do CPSID inside arch_cpu_idle?

Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c]: Yeah, on further thought none of these solutions are quite what I want.  I'll rework this later this morning when I can test multiple alternatives.

**Review by nvlsianpu — APPROVED** [review]

File: drivers/flash/nrf_qspi_nor.c [hunk 3]
```diff
@@ -262,13 +280,58 @@ static inline void qspi_wait_for_completion(const struct device *dev,
...
+ * k_cpu_atomic_idle().
+ *
+ * k_cpu_idle() (apparently) returns with interrupts unlocked even if
+ * it entered with them locked.
+ *
+ * k_cpu_atomic_idle(key) is to be called with interrupts locked to
+ * state key, and restores that state before it returns (for most
+ * architectures).
+ *
+ * So, two alternatives that seem to make sense:
```
Comment (pabigot) [inline drivers/flash/nrf_qspi_nor.c:299]: After reviewing alternatives there are two ways that should be safe.

I prefer the first, which uses `k_cpu_atomic_idle()`, because (ignoring incomplete documentation and a bad example) it makes the most sense relative to preserving the `key`.

However it's been suggested that `k_cpu_atomic_idle()` on ARM should be avoided because it hasn't been reworked like `k_cpu_idle()` has.  Thus the second approach.

Both work.  Which one do people want, or something else?

Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c:299]: I'm now strongly against the one that uses `k_cpu_idle()` because the documentation for that function has:
```
 * @note In some architectures, before returning, the function unmasks interrupts
 * unconditionally.
```
which means its behavior is not predictable.  While this particular code is only ever going to run on Nordic (ARM), there's no promise that ARM will always behave the way it does today, and the code fragment can't be copied into another architecture and still be expected to work.

Comment (de-nordic) [reply drivers/flash/nrf_qspi_nor.c:299]: I have compiled LittleFS sample with the changes (not using `k_cpu_idle`) and with MULTITHREADING disabled and they seem to work fine.
I agree with @pabigot  argumentation that we should avoid using `k_cpu_idle`.
Shouldn't the `k_cpu_idle` be fixed to have consistent behavior across all architectures?

Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c]: Updated to leave only the `k_cpu_atomic_idle` solution.

**Review by galak — COMMENTED** [review]
Is someone stepping up to support CONFIG_MULTITHREADING=n?  I'm confused about us adding support for something we will than just remove after v2.5.0 is released.

**Comment by pabigot** [comment]
> Is someone stepping up to support CONFIG_MULTITHREADING=n? I'm confused about us adding support for something we will than just remove after v2.5.0 is released.

@galak This is part of a series of trials to assess the feasibility of supporting `CONFIG_MULTITHREADING=n`.  #28679 passed its trial, because #8393 was agreed to still be a bug and bugs should be fixed.

For `CONFIG_MULTITHREADING=n` to be useful the normal expectation for the flash subsystem must be that it will work.  Then #26372 is a bug, as it was when originally reported; so this fixes a bug, and should be reviewed and merged.

If attempts to make `CONFIG_MULTITHREADING=n` work in drivers where it doesn't are not reviewed or not merged because `CONFIG_MULTITHREADING=n` is deprecated then from my perspective it's already gone.  Any idea that it can be made to work in a topic branch that's merged when the entire problem is solved is, IMO, unrealistic.

**Review by de-nordic — APPROVED** [review]
Tested on nrf52840dk, LittleFS sample. Works fie.

Looks ok.

**Comment by de-nordic** [comment]
> For `CONFIG_MULTITHREADING=n` to be useful the normal expectation for the flash subsystem must be that it will work. Then #26372 is a bug, as it was when originally reported; so this fixes a bug, and should be reviewed and merged.

I agree with @pabigot that as long as `CONFIG_MULTITHREADING=n` is still there, this PR is valid bug fix that should get processed.

**Comment by nvlsianpu** [comment]
Even if  `CONFIG_MULTITHREADING=n` will be removed we can still consider multithreading with one thread only application, for which we can cut-out multithreading synchronization primitives like semaphores.

**Comment by ioannisg** [comment]
> > Is someone stepping up to support CONFIG_MULTITHREADING=n? I'm confused about us adding support for something we will than just remove after v2.5.0 is released.
> 
> @galak This is part of a series of trials to assess the feasibility of supporting `CONFIG_MULTITHREADING=n`. #28679 passed its trial, because #8393 was agreed to still be a bug and bugs should be fixed.
> 
> For `CONFIG_MULTITHREADING=n` to be useful the normal expectation for the flash subsystem must be that it will work. Then #26372 is a bug, as it was when originally reported; so this fixes a bug, and should be reviewed and merged.
> 
> If attempts to make `CONFIG_MULTITHREADING=n` work in drivers where it doesn't are not reviewed or not merged because `CONFIG_MULTITHREADING=n` is deprecated then from my perspective it's already gone. Any idea that it can be made to work in a topic branch that's merged when the entire problem is solved is, IMO, unrealistic.

@pabigot @galak 
IMHO the right policy lies somewhere in these lines:
- we shall always accept bug fixes for reported bugs, even for deprecated features.
- no need to have a topic branch (that is, no need to reject having incremental patches towards "fixing" single-threading mode), as long as the incremental patches do not impact the normal (multi-threaded) mode. So they could be easily removed if we finally decide to remove the feature. In this particular case, I am not against having a topic branch, but don't see is a a requirement.
- for any of the above, we do **not** need commitment from a person/company to maintain the single-threaded mode. If we don't find a maintainer by the deadline, we are going to remove the feature, as voted.

**Review by nvlsianpu — APPROVED** [review]

**Review by anangl — APPROVED** [review]
