### PR TITLE
drivers: can: mcan: Manually track available TX buffers

### LINKED ISSUE #61245: drivers: can: mcan: TX complete synchronisation
The MCAN driver operates in TX queue mode (`TXBC.TFQM = 1`).
In this mode `TXFQS.TFQPI` returns the first available buffer (usually buffer zero).

Hardware is free to re-use a buffer as soon as TX completes, it does not have to wait for the matching TX event to be processed.

If a TX completes and that TX buffer is re-used before processing the TX event, two TX events for the same buffer occur.
The first event calls the second events TX callback, and the second event results in a NULL pointer exception.

In a "normal" configuration, the TX event ISR will always preempt the queuing of a TX frame to the same TX buffer.
However, this issue could occur if:

 * Sending a message with ISRs temporarily disabled
 * The ISR is processed on a different core to the TX call

Here is an example to demonstrate the issue:

    #include <zephyr/drivers/can.h>

    static void tx_callback(const struct device *dev, int error, void *user_data)
    {
    }

    FUNC_NORETURN void main(void)
    {
        const struct device *dev = DEVICE_DT_GET(DT_CHOSEN(zephyr_canbus));
        struct can_frame tx_frame = { };

        can_set_mode(dev, CAN_MODE_LOOPBACK);
        can_start(dev);

        struct k_spinlock spinlock;
        k_spinlock_key_t key = k_spin_lock(&spinlock);

        can_send(dev, &tx_frame, K_NO_WAIT, tx_callback, NULL);

        /* Wait long enough for the first TX to complete */
        k_busy_wait(10000);

        can_send(dev, &tx_frame, K_NO_WAIT, tx_callback, NULL);

        k_spin_unlock(&spinlock, key);
        
        /* Crash */

        while (true) { k_sleep(K_FOREVER); }
    }

### PR DESCRIPTION
**Pull request by gramsay0**
The MCAN driver operates in TX queue mode (`TXBC.TFQM = 1`).
In this mode `TXFQS.TFQPI` returns the first available buffer (usually buffer zero).

Hardware is free to re-use a buffer as soon as TX completes, it does not have to wait for the matching TX event to be processed.

If a TX completes and that TX buffer is re-used before processing the TX event, two TX events for the same buffer occur.
The first event calls the second events TX callback, and the second event results in a NULL pointer exception.

In a "normal" configuration, the TX event ISR will always preempt the queuing of a TX frame to the same TX buffer.
However, this issue could occur if:

 * Sending a message with ISRs temporarily disabled
 * The ISR is processed on a different core to the TX call

The fix is to manually track which TX buffers are available, only freeing a buffer after the TX event has been processed.

The MCAN user manual states that this is allowed:

> The application may use register TXBRP instead of the Put Index and may place messages to any Tx Buffer without pending transmission request

Here is an example to demonstrate the issue:

    #include <zephyr/drivers/can.h>

    static void tx_callback(const struct device *dev, int error, void *user_data)
    {
    }

    FUNC_NORETURN void main(void)
    {
        const struct device *dev = DEVICE_DT_GET(DT_CHOSEN(zephyr_canbus));
        struct can_frame tx_frame = { };

        can_set_mode(dev, CAN_MODE_LOOPBACK);
        can_start(dev);

        struct k_spinlock spinlock;
        k_spinlock_key_t key = k_spin_lock(&spinlock);

        can_send(dev, &tx_frame, K_NO_WAIT, tx_callback, NULL);

        /* Wait long enough for the first TX to complete */
        k_busy_wait(10000);

        can_send(dev, &tx_frame, K_NO_WAIT, tx_callback, NULL);

        k_spin_unlock(&spinlock, key);
        
        /* Crash */

        while (true) { k_sleep(K_FOREVER); }
    }

There's a couple other minor tidy ups in this PR, happy to split into separate PRs if requested

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/61245

### CODE REVIEW

File: drivers/can/can_mcan.c [hunk 1]
```diff
@@ -921,20 +924,26 @@ int can_mcan_send(const struct device *dev, const struct can_frame *frame, k_tim
...
 
-	__ASSERT_NO_MSG(put_idx <= cbs->num_tx);
+	__ASSERT_NO_MSG(put_idx < cbs->num_tx);
 	cbs->tx[put_idx].function = callback;
 	cbs->tx[put_idx].user_data = user_data;
 
 	err = can_mcan_write_reg(dev, CAN_MCAN_TXBAR, BIT(put_idx));
 	if (err != 0) {
-		goto unlock;
+		goto err_free_tx_cb;
```
Comment (henrikbrixandersen) [inline drivers/can/can_mcan.c:936]: How about just setting `cbs->tx[put_idx].function = NULL;` here and avoid all the labels at the end of the function?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Thanks! Please open a corresponding issue to make a backport to v3.4 easier.

**Comment by gramsay0** [comment]
> Thanks! Please open a corresponding issue to make a backport to v3.4 easier.

Yep sure: https://github.com/zephyrproject-rtos/zephyr/issues/61245

File: drivers/can/can_mcan.c [hunk 2]
```diff
@@ -822,11 +825,11 @@ int can_mcan_send(const struct device *dev, const struct can_frame *frame, k_tim
 #endif /* !CONFIG_CAN_FD_MODE */
 		.efc = 1U,
 	};
-	uint32_t put_idx;
+	uint32_t put_idx = -1;
```
Comment (henrikbrixandersen) [inline drivers/can/can_mcan.c:828]: Strictly speaking, this variable is no longer holding the "put index" (at least not in the meaning from the M_CAN manual). Should we rename it?

File: drivers/can/can_mcan.c [hunk 3]
```diff
@@ -921,20 +924,25 @@ int can_mcan_send(const struct device *dev, const struct can_frame *frame, k_tim
...
+		goto err_unlock;
 	}
 
-unlock:
 	k_mutex_unlock(&data->tx_mtx);
+	return 0;
+
+err_unlock:
+	k_mutex_unlock(&data->tx_mtx);
+	k_sem_give(&data->tx_sem);
```
Comment (henrikbrixandersen) [inline drivers/can/can_mcan.c:945]: Wasn't this semaphore already "given" in line 516?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]

File: drivers/can/can_mcan.c [hunk 4]
```diff
@@ -507,12 +508,14 @@ static void can_mcan_tx_event_handler(const struct device *dev)
...
-
 		__ASSERT_NO_MSG(tx_idx <= cbs->num_tx);
 		tx_cb = cbs->tx[tx_idx].function;
+		user_data = cbs->tx[tx_idx].user_data;
 		cbs->tx[tx_idx].function = NULL;
-		tx_cb(dev, 0, cbs->tx[tx_idx].user_data);
+
+		k_sem_give(&data->tx_sem);
+
+		tx_cb(dev, 0, user_data);
```
[the remark this answers is not in the document]
Comment (henrikbrixandersen) [reply drivers/can/can_mcan.c:518]: We can do that in a follow-up PR, if needed.

File: drivers/can/can_mcan.c (hunk 2 above)
Comment (henrikbrixandersen) [reply drivers/can/can_mcan.c:828]: Let's keep the name for now.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]
Finding the root cause for this bug must have been quite tricky. Thanks also for the additional clean-up.

**Comment by gramsay0** [comment]
@henrikbrixandersen apologies for not replying, I have just returned from vacation.
Thanks for reviewing and getting this merged
