### PR TITLE
 tests: libc: Update libc testcases to solve coverity issues

### LINKED ISSUE #33794: [Coverity CID: 220442] Pointless string comparison in tests/lib/c_lib/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/169144afa1826511ee6ec3f53d590b2c0d39d3d4/tests/lib/c_lib/src/main.c

Category: Incorrect expression
Function: `test_strncmp`
Component: Tests
CID: [220442](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=220442)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/169144afa1826511ee6ec3f53d590b2c0d39d3d4/tests/lib/c_lib/src/main.c

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #33806: [Coverity CID: 220430] Operands don't affect result in tests/lib/c_lib/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/169144afa1826511ee6ec3f53d590b2c0d39d3d4/tests/lib/c_lib/src/main.c#L666

Category: Integer handling issues
Function: `test_strtoxl`
Component: Tests
CID: [220430](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=220430)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/169144afa1826511ee6ec3f53d590b2c0d39d3d4/tests/lib/c_lib/src/main.c

```
695         ret = strtol(buf13, &stop, 10);
696         zassert_equal(ret, 2147483640, "strtol base = 10 failed");
697    
698         retul = strtoul(buf14, stop1, 10);
699         zassert_not_equal(retul, 4294967299, "strtoul base = 10 failed");
700         retul = strtoul(buf15, &stop, 10);
>>>     CID 220430:    (CONSTANT_EXPRESSION_RESULT)
>>>     "retul != -42949673990LL" is always true regardless of the values of its operands. This occurs when converting to bool for an argument to a function call.
701         zassert_not_equal(retul, -42949673990, "strtoul base = 10 failed");
702         retul = strtoul(buf16, &stop, 10);
703         zassert_equal(retul, 4294967290, "strtoul base = 10 failed");
704     #endif
705     }
706    
693         ret = strtol(buf12, &stop, 10);
694         zassert_not_equal(ret, -2147483649, "strtol base = 10 failed");
695         ret = strtol(buf13, &stop, 10);
696         zassert_equal(ret, 2147483640, "strtol base = 10 failed");
697    
698         retul = strtoul(buf14, stop1, 10);
>>>     CID 220430:    (CONSTANT_EXPRESSION_RESULT)
>>>     "retul != 4294967299LL" is always true regardless of the values of its operands. This occurs when converting to bool for an argument to a function call.
699         zassert_not_equal(retul, 4294967299, "strtoul base = 10 failed");
700         retul = strtoul(buf15, &stop, 10);
701         zassert_not_equal(retul, -42949673990, "strtoul base = 10 failed");
702         retul = strtoul(buf16, &stop, 10);
703         zassert_equal(retul, 4294967290, "strtoul base = 10 failed");
704     #endif
660         zassert_not_equal(retul, 1037, "strtoul base = 10 failed");
661         retul = strtoul(buf9, &stop, 10);
662         zassert_not_equal(retul, 1037, "strtoul base = 10 failed");
663         retul = strtoul(buf10, &stop, 10);
664         zassert_not_equal(retul, 1037, "strtoul base = 10 failed");
665         retul = strtoul(buf17, stop1, 10);
>>>     CID 220430:    (CONSTANT_EXPRESSION_RESULT)
>>>     "retul != 4294967299LL" is always true regardless of the values of its operands. This occurs when converting to bool for an argument to a function call.
666         zassert_not_equal(retul, 4294967299, "strtoul base = 10 failed");
667    
668     #if LONG_MAX > 2147483647
669         char buf12[] = "-9223372036854775809";
670         char buf13[] = "9223372036854775800";
671         char buf14[] = "18446744073709551719";
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #33810: [Coverity CID: 220426] Out-of-bounds access in tests/lib/c_lib/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/169144afa1826511ee6ec3f53d590b2c0d39d3d4/tests/lib/c_lib/src/main.c#L536

Category: Memory - corruptions
Function: `test_memstr`
Component: Tests
CID: [220426](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=220426)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/169144afa1826511ee6ec3f53d590b2c0d39d3d4/tests/lib/c_lib/src/main.c#L536

```
530         zassert_is_null(memchr(str, 'a', 0), "memchr 0 error");
531         zassert_not_null(memchr(str, 'e', 10), "memchr serach e");
532         zassert_is_null(memchr(str, 'e', 1), "memchr e error");
533    
534         for (i = 0; i < 20; i++) {
535             for (j = 0; j < 20; j++) {
>>>     CID 220426:  Memory - corruptions  (OVERRUN)
>>>     Calling "memcpy" with "&arr[i]" and "0U" is suspicious because the function call may access "arr" at byte "i + 18446744073709551615U". [Note: The source code implementation of the function has been overridden by a builtin model.]
536                 memcpy(&arr[i], num, 0);
537                 ret = memcmp(&num[j], &arr[i], 0);
538                 zassert_true((ret == 0), "memcpy failed");
539                 memcpy(&arr[i], &num[j], 1);
540                 ret = memcmp(&num[j], &arr[i], 1);
541                 zassert_true((ret == 0), "memcpy failed");
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by yingmingx**
1. Refine some testcases for testing some libc functions, include
    strlen(),strcmp(),strncmp(),memcmp(),memstr(),memcpy(),memmove()
    strtol(),strtoul().
    2. Change some code to make the code style consistent.

Fixes #33794 
Fixes #33810 
Fixes #33806

Signed-off-by: Ying ming <mingx.ying@intel.com>

### CODE REVIEW

File: tests/lib/c_lib/src/main.c [hunk 1]
```diff
@@ -514,38 +502,96 @@ void test_checktype(void)
...
-	zassert_is_null(memchr(str, 'e', 1), "memchr e error");
-
-	for (i = 0; i < 20; i++) {
-		for (j = 0; j < 20; j++) {
-			memcpy(&arr[i], num, 0);
-			ret = memcmp(&num[j], &arr[i], 0);
-			zassert_true((ret == 0), "memcpy failed");
-			memcpy(&arr[i], &num[j], 1);
-			ret = memcmp(&num[j], &arr[i], 1);
-			zassert_true((ret == 0), "memcpy failed");
```
Comment (enjiamai) [inline tests/lib/c_lib/src/main.c:541]: Hi, I remember the previous code include this before @xiaofst modified it. Could you please take a look the original code before his PR? I'm afraid of something missing, thanks!

**Review by yingmingx — COMMENTED** [review]
Hi, enjia. This code you mentioned was writen by Jian last year and xiaofs improve the coverage on the basis of Jian's code. I redesigned this testcase, now the coverage of memchr(), memcpy(), memmove() is also 100%.

File: tests/lib/c_lib/src/main.c (hunk 1 above)
Comment (yingmingx) [reply tests/lib/c_lib/src/main.c:541]: Hi, enjia. This code you mentioned was writen by Jian last year and xiaofs improve the coverage on the basis of Jian's code. I redesigned this testcase, now the coverage of memchr(), memcpy(), memmove() is also 100%.

**Review by enjiamai — APPROVED** [review]

**Review by nashif — APPROVED** [review]
