### PR TITLE
shell: fix potential buffer overflow in shell_help_is_structured()

### LINKED ISSUE #102598: shell_help_is_structured() (can) crash when help message string is less than 4 bytes
### Describe the bug

`shell_help_is_structured()` casts what may just be a string (`help`) into a `struct shell_cmd_help` and tries to access its first 4 bytes (`uint32_t magic`). But what `help` points to may be smaller than 4 bytes (in the example below it is 3 bytes including the null termination).
Which in that case results in trying to read beyond the end of that buffer, which may not be readable memory anymore.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. mkdir build && cd build
2. cmake -GNinja -DBOARD=native_sim//64 ../samples/subsys/shell/shell_module/ -DCONFIG_ASAN=y -DCONFIG_NO_OPTIMIZATIONS=y
3. ninja
4. zephyr/zephyr.exe -uart_stdinout
5. kernel info
6. see crash

### Relevant log output

```shell
$ zephyr/zephyr.exe -uart_stdinout

uart:~$ kernel info
kernel info
kernel - Kernel commands
Subcommands:
  cycles     : Kernel cycles.
  log_level  : <module name> <severity (0-4)>
  sleep      : =================================================================
==3538549==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000458540 at pc 0x00000043213c bp 0x7223393fe590 sp 0x7223393fe580
READ of size 4 at 0x000000458540 thread T5
    #0 0x43213b in shell_help_is_structured include/zephyr/shell/shell.h:332
    #1 0x432b3b in help_item_print subsys/shell/shell_help.c:169
    #2 0x432e1b in z_shell_help_subcmd_print subsys/shell/shell_help.c:206
    #3 0x42368e in shell_internal_help_print subsys/shell/shell.c:69
    #4 0x4259e0 in exec_cmd subsys/shell/shell.c:525
    #5 0x4270cd in execute subsys/shell/shell.c:802
    #6 0x4283f9 in state_collect subsys/shell/shell.c:1045
    #7 0x429c0f in shell_process subsys/shell/shell.c:1507
    #8 0x429334 in shell_signal_handle subsys/shell/shell.c:1318
    #9 0x429661 in shell_thread subsys/shell/shell.c:1368
    #10 0x40b6e6 in z_thread_entry lib/os/thread_entry.c:60
...
0x000000458543 is located 0 bytes after global variable '*.LC3' defined in 'subsys/shell/modules/kernel_service/sleep.c' (0x458540) of size 3
  '*.LC3' is ascii string 'ms'
SUMMARY: AddressSanitizer: global-buffer-overflow include/zephyr/shell/shell.h:332 in shell_help_is_structured
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Ubuntu Linux 24.04
- Host gcc 14.2
- sha: main as of now b93fabaf25ef34fdb2f8d40d28e7337c40d14651

### Additional Context

Code introduced in 
https://github.com/zephyrproject-rtos/zephyr/commit/9ab0ea73a8c944dcb62c75d4a78aefbffcd8d113
and patched in
https://github.com/zephyrproject-rtos/zephyr/commit/66f5d701bd7058767bbcaf340f7b7c1caacca329

### PR DESCRIPTION
**Pull request by kartben**
The function was casting a char* help pointer to struct shell_cmd_help* and reading its 4-byte magic field. When the help string was shorter than 4 bytes, this caused a read past the end of the buffer.

The fix replaces the struct cast with a byte-by-byte comparison of the magic number.

It should be mentioned that a wise reviewer had [already pointed the potential issue](https://github.com/zephyrproject-rtos/zephyr/pull/91057#discussion_r2131719410) :) @mathieuchopstm 

Thanks @aescolar for the suggested fix! I can't think of another solution even if this one means a small increase in code size.

Fixes zephyrproject-rtos/zephyr#102598

### CODE REVIEW

**Review by aescolar — APPROVED** [review]

**Review by jakub-uC — APPROVED** [review]

File: include/zephyr/shell/shell.h [hunk 1]
```diff
@@ -326,10 +326,16 @@ struct shell_cmd_help {
...
-	const struct shell_cmd_help *structured = (const struct shell_cmd_help *)help;
+	const uint32_t magic32 = SHELL_STRUCTURED_HELP_MAGIC;
+	const char *magic = (const char *)&magic32;
 
-	return structured != NULL && IS_PTR_ALIGNED(structured, struct shell_cmd_help) &&
-	       structured->magic == SHELL_STRUCTURED_HELP_MAGIC;
+	/**
+	 * Check if what help points to starts with the structured help magic word,
+	 * but without assuming help is 32 bit aligned, or that if it is a string,
+	 * that it is at least 4 bytes long.
```
Comment (mathieuchopstm) [inline include/zephyr/shell/shell.h:335]: Nit: kinda harsh to understand. I'd propose the more verbose but more explicit:
```suggestion
	 * Check if what help points to starts with the structured help magic word,
	 * but without assuming help is 32 bit aligned. We check one byte at a time
	 * and abort as soon as a mismatch is found (indicating that help is a string)
	 * to avoid OOB reads, as help strings can be less than 4 bytes in length. 
```

**Review by mathieuchopstm — APPROVED** [review]
I guess I was overoptimistic when I said it *should never happen* :smile:

**Review by teburd — APPROVED** [review]
