### PR TITLE
posix: pthread: embed posix_thread_attr inside of posix_thread

### LINKED ISSUE #67178: tests: posix: pthread_attr_destroy() not consistently called after pthread_attr_init()
**Describe the bug**

Pthread stacks should be managed by `pthread_attr_init()` and `pthread_attr_destroy()`.

Dynamic thread stacks (including pooled thread stacks) were not done in Zephyr this way due to... difficulties getting that accepted in the first place (it took years), but also due to the implementation of the POSIX API, testsuite, and so on.

The model is clear - either use a `NULL` `pthread_attr_t *` and the implementation will manage the stack for the caller, or call `pthread_attr_init()` **with a matching call** to `pthread_attr_destroy()`.

In many areas in the POSIX testsuite, calls to `pthread_attr_destroy()` were missing or an assertion would occur prior to `pthread_attr_destroy()` being called.

It would seem that the testsuite leaks memory and resources substantially due to this.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? All
 - What have you tried to diagnose or workaround this issue? #67094 #67085
 - Is this a regression? No.
 
**To Reproduce**
1. Pull in #67223 (it's actually too late now, because that PR pulls in much of the cleanup from #67575)
2. Execute tests where there is a call to `pthread_attr_init()` but no matching call to `pthread_attr_destroy()`, or tests that assert before calling `pthread_attr_destroy()`
3. See error

**Expected behavior**
There should be no memory leaks

**Impact**
It's a showstopper for #51211 which is why I'm in such a hurry to fix it 😁 

**Logs and console output**
Would see things like
```shell
E: Unable to allocate thread stack
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.4
 - Commit: c0bb064d4e

**Additional context**

This bug will likely be comprised of several partial fixes
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/67094
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/67575
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/67223

### PR DESCRIPTION
**Pull request by cfriedt**
Rather than shadowing most of the fields from `pthread_attr_t` (`struct posix_thread_attr`) inside of `struct posix_thread`, just embed the structure itself.

Additionally, use `pthread_attr_init()` to allocate a thread stack (with `CONFIG_DYNAMIC_THREAD=y`) and `pthread_attr_destroy()` to destroy a thread stack, dramatically simplifying `pthread_create()`.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/67178

A series of 10 😀 
* if `pthread_attr.test_pthread_attr_large_stacksize` fails to allocate an 8MB stack, print a message and skip
* create a dedicated twister permutation for CONFIG_DYNAMIC_THREAD=n
* reduce verbosity from error to debug when trying to free a NULL (or otherwise invalid) thread stack
* create a wrapper to check if a pthread attr has been initialized
* check for async cancel type before async cancellation
* embed `pthread_attr_t` inside of `pthread_t` (actually `struct posix_thread_attr` inside of `struct posix_thread`)
* hold lock when calling `to_posix_thread()` (mitigate race conditions)
* add a setter / getter  for pthread queue ID (plus some assertions)
* tests: posix/common + libc/thrd: x86*: use a dynamic stack size of 4k
* tests: posix: common: use a define instead of a magic number

### CODE REVIEW

**Comment by cfriedt** [comment]
This is currently blocked by https://github.com/zephyrproject-rtos/zephyr/pull/67871

File: tests/posix/common/src/pthread_attr.c [hunk 1]
```diff
@@ -441,12 +441,25 @@ ZTEST(pthread_attr, test_pthread_attr_setstacksize)
...
-	zassert_ok(pthread_attr_getstacksize(&attr, &actual_size));
-	zassert_equal(actual_size, expect_size);
+	ret = pthread_attr_setstacksize(&attr, expect_size);
+	switch (ret) {
+	case 0:
+		zassert_ok(pthread_attr_getstacksize(&attr, &actual_size));
+		zassert_equal(actual_size, expect_size);
+		break;
+	case ENOMEM:
+		TC_PRINT("Failed to allocated thread stack of size %zu\n", expect_size);
```
Comment (cfriedt) [inline tests/posix/common/src/pthread_attr.c:455]: Just a note, this attempts to allocate an 8MB thread stack (which would predictably fail in most cases).

I don't know if there is necessarily a more graceful way to do this.

File: lib/posix/pthread.c [hunk 2]
```diff
@@ -432,80 +457,71 @@ int pthread_create(pthread_t *th, const pthread_attr_t *_attr, void *(*threadrou
...
 {
 	int err;
-	k_spinlock_key_t key;
 	pthread_barrier_t barrier;
 	struct posix_thread *t = NULL;
-	struct posix_thread_attr attr_storage;
-	struct posix_thread_attr *attr = (struct posix_thread_attr *)_attr;
 
-	if (!pthread_attr_is_valid(attr)) {
+	if (!pthread_attr_is_valid((struct posix_thread_attr *)_attr)) {
```
Comment (ycsin) [inline lib/posix/pthread.c:499]: I find it a bit misleading that `pthread_attr_is_valid` is used to check the `posix_thread_attr` instead of `pthread_attr_t`, but this is out of the scope of this PR/commit

**Review by ycsin — COMMENTED** [review]
The second commit is pretty loaded, I would probably split it into smaller ones..

File: lib/posix/pthread.c (hunk 2 above)
Comment (cfriedt) [reply lib/posix/pthread.c:499]: Need a respin anyway, so I'll make that change.

File: lib/posix/pthread.c [hunk 3]
```diff
@@ -85,13 +87,46 @@ BUILD_ASSERT(CONFIG_POSIX_PTHREAD_ATTR_STACKSIZE_BITS + CONFIG_POSIX_PTHREAD_ATT
...
+{
+	switch (t->qid) {
+	case POSIX_THREAD_READY_Q:
+	case POSIX_THREAD_RUN_Q:
+	case POSIX_THREAD_DONE_Q:
+		return t->qid;
+	default:
+		__ASSERT_NO_MSG(posix_thread_q_get(t) == POSIX_THREAD_READY_Q ||
+				posix_thread_q_get(t) == POSIX_THREAD_RUN_Q ||
+				posix_thread_q_get(t) == POSIX_THREAD_DONE_Q);
```
[the remark this answers is not in the document]
Comment (cfriedt) [reply lib/posix/pthread.c:125]: Ack - yeah, that was a find/replace error

File: lib/posix/pthread.c (hunk 2 above)
Comment (cfriedt) [reply lib/posix/pthread.c:499]: Oh wait - no, that's still completely valid. Is it misleading because we have an internal representation of `pthread_attr_t` (i.e. `struct posix_thread_attr`)? It should be quite safe.

Comment (ycsin) [reply lib/posix/pthread.c:499]: > It should be quite safe.

Yeah, it's just the naming, on first glance I thought that the `pthread_attr_is_valid()` should be accepting `pthread_attr_t` as arg, but it is actually expecting `posix_thread_attr`

**Comment by cfriedt** [comment]
> The second commit is pretty loaded, I would probably split it into smaller ones..

I might split out one more from the 'embed' commit

**Comment by cfriedt** [comment]
@ycsin - I think this is probably ready for another look

```shell
(.venv) cfriedt@ubuntu:~/zephyrproject/zephyr$ twister --retry-failed 3 -i -T tests/posix/common/ -T lib/libc/
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete:  442/ 442  100%  skipped:  231, failed:    0, error:    0
INFO    - 13 test scenarios (442 test instances) selected, 231 configurations skipped (217 by static filter, 14 at runtime).
INFO    - 211 of 442 test configurations passed (100.00%), 0 failed, 0 errored, 231 skipped with 0 warnings in 570.14 seconds
INFO    - In total 15618 test cases were executed, 17974 skipped on 41 out of total 673 platforms (6.09%)
INFO    - 209 test configurations executed on platforms, 2 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing JSON report /home/cfriedt/zephyrproject/zephyr/twister-out/twister.json
INFO    - Writing xunit report /home/cfriedt/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/cfriedt/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed
```

**Comment by cfriedt** [comment]
Will respin 🙄

File: lib/posix/pthread.c [hunk 4]
```diff
@@ -715,18 +737,30 @@ int pthread_attr_init(pthread_attr_t *_attr)
  */
 int pthread_getschedparam(pthread_t pthread, int *policy, struct sched_param *param)
 {
-	int priority;
+	int ret = 0;
+	uint32_t priority;
```
Comment (ycsin) [inline lib/posix/pthread.c:779]: `k_thread_priority_get()` returns `int`:

https://github.com/zephyrproject-rtos/zephyr/blob/117dc55233d36b829d5bf48521f8455864b59877/include/zephyr/kernel.h#L818

> A thread’s priority is an integer value, and can be either negative or non-negative.

File: tests/posix/common/src/pthread_attr.c [hunk 5]
```diff
@@ -441,12 +441,25 @@ ZTEST(pthread_attr, test_pthread_attr_setstacksize)
...
+		zassert_ok(pthread_attr_getstacksize(&attr, &actual_size));
+		zassert_equal(actual_size, expect_size);
+		break;
+	case ENOMEM:
+		TC_PRINT("Unable to allocate stack of size %zu (skipping)\n", expect_size);
+		ztest_test_skip();
+		return;
+	default:
+		zassert_true(ret == 0 || ret == ENOMEM, "pthread_attr_setstacksize() returned %d",
+			     ret);
```
[the remark this answers is not in the document]
Comment (cfriedt) [reply tests/posix/common/src/pthread_attr.c:460]: Fixed!

File: lib/posix/pthread.c [hunk 6]
```diff
@@ -284,52 +304,35 @@ int pthread_attr_setschedparam(pthread_attr_t *_attr, const struct sched_param *
...
+	int ret;
 	struct posix_thread_attr *attr = (struct posix_thread_attr *)_attr;
 
 	if (stackaddr == NULL) {
 		LOG_ERR("NULL stack address");
 		return EACCES;
 	}
 
-	if (!__attr_is_initialized(attr) || stacksize < PTHREAD_STACK_MIN ||
+	if (!__attr_is_initialized(attr) || stacksize == 0 || stacksize < PTHREAD_STACK_MIN ||
```
[the remark this answers is not in the document]
Comment (cfriedt) [reply lib/posix/pthread.c:350]: I tried that too. It causes some tests to fail. The issue is that `PTHREAD_STACK_MIN` evaluates to 0 on some platforms, which is somewhat counterintuitive.

File: lib/posix/pthread.c (hunk 4 above)
Comment (cfriedt) [reply lib/posix/pthread.c:779]: Fixed!

**Comment by cfriedt** [comment]
@ycsin - PTAL when you have some time. Just a couple of minor changes.

File: tests/posix/common/src/mutex.c [hunk 7]
```diff
@@ -195,4 +195,14 @@ ZTEST(mutex, test_mutex_timedlock)
 	zassert_ok(pthread_mutex_destroy(&mutex));
 }
 
-ZTEST_SUITE(mutex, NULL, NULL, NULL, NULL, NULL);
+static void before(void *arg)
```
Comment (andyross) [inline tests/posix/common/src/mutex.c:198]: This pattern seems a little boilerplatey.  Maybe a nonstatic "test_check_dyn_thread()" or something instead?

**Review by andyross — DISMISSED** [review]
Seems reasonable

File: tests/posix/common/src/mutex.c (hunk 7 above)
Comment (cfriedt) [reply tests/posix/common/src/mutex.c:198]: As much as I would like to, I just want to help this PR crawl past the finish line 😅 - another PR maybe?

**Review by ycsin — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Comment by cfriedt** [comment]
rebased to fix merge conflict in `tests/../mqueue.c`
OK to re-approve @ycsin, @jukkar, @andyross ?

**Review by ycsin — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
