### PR TITLE
include: zephyr: APIs doc: fix Doxygen \retval command usage

### LINKED ISSUE #65974: Docs: Incorrect uses of `@retval`
**Describe the bug**
The `@retval` keyword uses the first word as the value, and should only be used like `@retval 0 <text>` or `@retval -EINVAL <text>`. There are several functions that are using it incorrectly, where the first word is describing the return value instead. 

For example https://docs.zephyrproject.org/latest/kernel/services/synchronization/events.html#c.k_event_test where the return values part now looks weird: 
image

There are also cases where a function may return a set of specific error codes if negative, but an actual value if positive like https://docs.zephyrproject.org/latest/connectivity/bluetooth/api/audio.html#c.bt_audio_codec_cfg_set_frame_blocks_per_sdu. I am unsure what the correct solution for those functions are, but maybe they should similar to https://docs.zephyrproject.org/latest/hardware/cache/index.html#c.sys_cache_instr_line_size_get? 

Lastly, there are also cases where `-errno` is provided as the `@retval` which isn't really a value either. 

**To Reproduce**
N/A

**Expected behavior**
Expect the `@retval`s to be more specific in terms of the value that is returned, and specific in a way where the first word is correctly used as the value. 

**Impact**
Minor.

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: ea887af0aa112b1e707be84a299788a789b0c129

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JarmouniA**
Fix how Doxygen special command \retval is used in APIs doc text.

\retval: Starts a description for a function's return value with name `<return value>`, which needs to be attached and to not be a word that is part of the sentence, and each return value should have its own \retval.
Otherwise \retval is replaced with \return.

See https://www.doxygen.nl/manual/commands.html#cmdreturn
https://www.doxygen.nl/manual/commands.html#cmdretval
https://docs.rtems.org/docs/main/eng/coding-doxygen.html 

Doc preview https://builds.zephyrproject.io/zephyr/pr/98324/docs/doxygen/html/topics.html

### CODE REVIEW

File: include/zephyr/bluetooth/addr.h [hunk 1]
```diff
@@ -84,8 +84,8 @@ static inline int bt_addr_cmp(const bt_addr_t *a, const bt_addr_t *b)
 
 /** @brief Determine equality of two Bluetooth device addresses.
  *
- *  @retval #true if the two addresses are equal
- *  @retval #false otherwise
+ *  @retval true if the two addresses are equal
+ *  @retval false otherwise
```
Comment (Thalley) [inline include/zephyr/bluetooth/addr.h:88]: Since you are already touching so many `@retval`s, consider if it makes sense to fully fix some of the issues with `@retval` in the documentation: https://github.com/zephyrproject-rtos/zephyr/issues/65974

E.g. these need to be

```suggestion
 *  @retval true The two addresses are equal
 *  @retval false The two addresses are not equal
```

Comment (JarmouniA) [reply include/zephyr/bluetooth/addr.h:88]: There was a 1st attempt in #97876, but closed it since the changes seemed to be somewhat controversial & it was going to take considerable time to address each case individually.

File: include/zephyr/canbus/isotp.h [hunk 2]
```diff
@@ -275,7 +275,7 @@ void isotp_unbind(struct isotp_recv_ctx *rctx);
  * @param len     Size of the buffer.
  * @param timeout Timeout for incoming data.
  *
- * @retval Number of bytes copied on success
+ * @return Number of bytes copied on success
  * @retval ISOTP_RECV_TIMEOUT when "timeout" timed out
  * @retval ISOTP_N_* on error
```
Comment (Thalley) [inline include/zephyr/canbus/isotp.h:280]: It's a bit curious to use both `@return` and `@retval`, but I guess it works: 

Image

Although it may be better to have something like 

Image
(from e.g. https://man7.org/linux/man-pages/man2/send.2.html) 

i.e. making it clear that it either returns a value, or a set of errors. I don't see anything in doxygen that supports this though - @kartben thoughts?

File: include/zephyr/drivers/cellular.h [hunk 3]
```diff
@@ -237,7 +237,7 @@ __subsystem struct cellular_driver_api {
  * @retval 0 if successful.
  * @retval -EINVAL if any provided cellular network configuration is invalid or unsupported.
  * @retval -ENOTSUP if API is not supported by cellular network device.
- * @retval Negative errno-code otherwise.
+ * @retval <0 Negative errno-code otherwise.
```
Comment (Thalley) [inline include/zephyr/drivers/cellular.h:240]: This is also a bit weird where only a subset of the error codes are defined.

**Review by Thalley — COMMENTED** [review]
I'm not objecting to the changes in this PR; it's probably an overall improvement and it certainly fixes a lot of formatting issues. 

However, some of the changes from `retval` => `return` does seem like a step in the wrong direction, and a proper fix for the documentation of return values would have been better. Chances are that some of the changes here would have to be reverted back to `retval`, or that some of the `retval`s` should be removed and the text moved to the `return`.

File: include/zephyr/canbus/isotp.h (hunk 2 above)
Comment (kartben) [reply include/zephyr/canbus/isotp.h:280]: > It's a bit curious to use both @return and @retval, but I guess it works

Yeah the combination of `@return` and `@retval` probably looks "wrong" at first sight, but I do think it's actually great. See [here](https://docs.rtems.org/docs/main/eng/coding-doxygen.html#:~:text=Distinctive%20return%20values%20shall%20be%20documented%20with%20an%20%40retval%20entry.%20Document%20the%20most%20common%20return%20value%20first.%20Use%20%40return%20to%20describe%20the%20return%20of%20non%2Ddistinctive%20values.).

> i.e. making it clear that it either returns a value, or a set of errors. I don't see anything in doxygen that supports this though - @kartben thoughts?

Yeah probably not supported. I think "Returns" vs. "Returns values" is already not so bad though?

Comment (Thalley) [reply include/zephyr/canbus/isotp.h:280]: > I think "Returns" vs. "Returns values" is already not so bad though?

I don't think it is bad, I just think "Return Value" and "Errors" is better :)

**Review by jhedberg — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]
