### PR TITLE
net: ptp: add IEEE 802.3 transport, timestamping fixes, and regression coverage

### LINKED ISSUE #110645: [Backport] net: sockets: recvmsg() ancillary-data capacity check undercounts cmsg size
**Describe the bug**

`insert_pktinfo()` in `subsys/net/lib/sockets/sockets_inet.c` validates the
caller's `recvmsg()` `msg_control` buffer using only the ancillary *payload*
length, but then writes a full control message (aligned `cmsghdr` header + payload)
into that buffer. The capacity guard is:

```c
if (msg->msg_controllen < pktinfo_len) {
        return -EINVAL;
}
```

`pktinfo_len` is just the payload size (e.g. 12 bytes for an IPv4 `IP_PKTINFO`).
The element actually stored is `NET_CMSG_SPACE(pktinfo_len)` bytes — the aligned
`cmsghdr` header **plus** the aligned payload. So when an application calls
`recvmsg()` with a `msg_control` buffer whose length sits between the header size
and the full element size (e.g. 16–27 bytes on a 64-bit build), the check passes,
`NET_CMSG_FIRSTHDR()` returns a valid header, and the code then writes ~28 bytes
into the smaller buffer — writing past the end of `msg_control` by up to one
`cmsghdr` (~12 bytes).

This affects every ancillary element routed through `insert_pktinfo()`: IPv4/IPv6
`PKTINFO`, hop-limit / TTL, and `SO_TIMESTAMPING`, on sockets where the
corresponding receive option is enabled.

A second, related inconsistency: `update_msg_controllen()` summed the raw
`cmsg_len` rather than the aligned length (`NET_ALIGN_H(cmsg->cmsg_len)`), so the
reported consumed `msg_controllen` did not match the aligned stepping that
`NET_CMSG_NXTHDR()` uses.

**Expected behavior**

The capacity check should require the full aligned control-message size
(`NET_CMSG_SPACE(pktinfo_len)`) before writing, and return an error (`-ENOMEM`) if
the buffer is too small; `update_msg_controllen()` should sum the aligned lengths.

**Impact**

A `recvmsg()` with an undersized `msg_control` buffer on a socket with PKTINFO /
hop-limit / `SO_TIMESTAMPING` enabled writes a fixed number of bytes past the end
of the supplied control buffer.

**Affected code**

`subsys/net/lib/sockets/sockets_inet.c` — `insert_pktinfo()` and
`update_msg_controllen()`.

### PR DESCRIPTION
**Pull request by DBS06**
# Motivation

I started this work while trying to run the Zephyr PTP sample on a Nucleo-H563ZI with a GPS clock and a PTP-capable switch. That exposed a mix of correctness, timestamping, and usability issues: some paths did not work reliably on hardware, IEEE 802.3 / Layer-2 transport support was missing, and the native_sim/native_tap path was not a good enough stand-in for development and regression testing.

What began as a small hardware bring-up fix turned into a broader hardening pass of the PTP stack. Along the way I fixed several bugs in transport handling, timestamp propagation, foreign-master selection, and BTCA/state handling, and I added documentation, shell diagnostics, and regression coverage so the current behavior is easier to validate and maintain.

# Key Features

- Add IEEE 802.3 / Layer-2 PTP transport support (`EtherType 0x88f7`).
- Fix RX/TX timestamp handling across PTP sockets, AF_PACKET, and native_tap.
- Fix foreign-master tracking and BTCA tie-break behavior.
- Fix STM32H5 PTP reference-clock handling on Nucleo-H563ZI.
- Add `net ptp` shell diagnostics and improve sample/documentation usability.
- Add focused regression tests for PTP state, clock decision, foreign-master handling, message post-processing, and socket timestamping behavior.

# Why These Changes Were Needed

- The PTP stack only supported UDP transport paths. This PR adds IEEE 802.3 / Layer-2 transport support, including AF_PACKET open/send/receive paths, link-layer multicast addressing, and the protocol plumbing needed to run PTP without UDP.
- Layer-2 RX timestamping is not equally available on every path. The transport now tries `recvmsg()` first to collect `SO_TIMESTAMPING` control data, then falls back to `recvfrom()` plus a PHC read when ancillary RX timestamps are unavailable. `ptp_clock_synchronize()` now also guards against missing or out-of-range ingress timestamps instead of blindly using bad data.
- Foreign-master handling had correctness gaps. The first Announce is now stored, new Announce messages are compared against the previous latest record, negative BTCA comparisons no longer replace the current best foreign clock, and the BTCA receiver-port tie-break is corrected. This stabilizes role selection and avoids false BMCA/BTCA decisions.
- Sync / Follow_Up handling is hardened around TX timestamp callbacks. If a TX timestamp is missing or late, the affected Follow_Up is skipped and the stack continues with the next Sync cycle instead of getting stuck behind a bad timestamp.
- `eth_native_tap.c` needed to change because native_tap only queued TX timestamp callbacks for gPTP traffic. PTP socket traffic using `SO_TIMESTAMPING` therefore missed TX timestamps on native_sim. This PR fixes that by queueing TX callbacks for timestamped packets in general, updating packet timestamps on TX/RX, propagating timestamping flags through `net_context`, and adding AF_PACKET `recvmsg()` timestamp support with correct ancillary buffer accounting.
- `eth_stm32_hal_ptp.c` needed a separate fix for STM32H5. In "RM0481 Rev 4" the Ethernet chapter documents the timestamp engine as running from a dedicated PTP reference clock (`clk_ptp_ref_i`) separate from `eth_hclk`, and RCC Table 115 ("Kernel clock distribution overview") lists `ETH (ptp)` on `pll1_q_ck`. This PR therefore models an explicit `mac-clk-ptp` source for STM32H5 and uses that clock rate for PTP addend programming. On Nucleo-H563ZI, that corrected the large, repeating delay and offset errors seen when the addend was derived from the wrong clock (see below). This took me quite a lot of time to find out ;-)
- The sample and docs were also updated so this is easier to understand and reproduce: `LOG_INF` status prints, run-forever sample behavior, expanded README guidance, explicit PTP shell support, and documentation for transport/timestamping behavior.

# Testing

- Added unit/regression suites:
  `net.ptp.btca_state_machine`, `net.ptp.clock_decision`, `net.ptp.foreign_master`, `net.ptp.msg_post_recv`, and `net.ptp.state_matrix`.
- Added socket timestamping coverage for both UDP and AF_PACKET, including `recvmsg()` ancillary-data handling, `msg_controllen` accounting, and `MSG_CTRUNC` behavior.
- Informally validated with the PTP sample on Nucleo-H563ZI against `ptp4l`, a GPS clock (direct link), a PTP-capable switch, and a GPS clock through a PTP-capable switch. The exercised transports were UDP/IPv4, UDP/IPv6, and IEEE 802.3 / Layer-2.
- The attached artifacts are runtime logs rather than interactive `net ptp` shell transcripts, so the excerpts below use the actual sample output from those runs.

```console
# IEEE 802.3 / L2 excerpt
[00:00:00.051,000] <inf> net_config: Initializing network
[00:00:00.051,000] <inf> net_config: Waiting interface 1 (0x200013d4) to be up...
[00:00:01.852,000] <inf> phy_mii: PHY (0) Link speed 100 Mb, full duplex
[00:00:01.852,000] <inf> net_config: Interface 1 (0x200013d4) coming up
[00:00:01.852,000] <inf> net_config: IPv4 address: 192.168.0.100
[00:00:01.852,000] <dbg> ptp_clock: ptp_clock_init: PTP Clock 02:00:00:FF:FE:00:00:01 initialized
[00:00:01.852,000] <dbg> ptp_port: ptp_port_init: Port 1 initialized
[00:00:01.852,000] <dbg> ptp_port: port_enable: Port 1 opened
[00:00:01.852,000] <dbg> ptp_port: port_state_update: Port 1 changed state from INITIALIZING to LISTENING
[00:00:01.852,000] <inf> net_ptp_sample: Runs forever
[00:00:06.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:06.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:06.161,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Announce message
[00:00:06.161,000] <dbg> ptp_port: ptp_port_add_foreign_tt: Port 1 has a new foreign timeTransmitter 02:00:00:FF:FE:00:00:10-0002
[00:00:07.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:07.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:08.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:08.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:08.161,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Announce message
[00:00:08.161,000] <dbg> ptp_port: port_state_update: Port 1 changed state from LISTENING to TIME RECEIVER
[00:00:08.727,000] <dbg> ptp_port: port_delay_req_msg_transmit: Port 1 sends Delay_Req message
[00:00:08.727,000] <dbg> ptp_port: port_delay_req_timestamp_cb: Port 1 registered timestamp for 0 Delay_Req
[00:00:08.727,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Delay_Resp message
[00:00:09.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:09.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:10.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:10.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:10.160,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Announce message
[00:00:10.727,000] <dbg> ptp_port: port_delay_req_msg_transmit: Port 1 sends Delay_Req message
[00:00:10.727,000] <dbg> ptp_port: port_delay_req_timestamp_cb: Port 1 registered timestamp for 1 Delay_Req
[00:00:10.727,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Delay_Resp message
[00:00:10.727,000] <dbg> ptp_clock: ptp_clock_delay: Delay -7613ns
[00:00:11.155,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:11.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:11.156,000] <wrn> ptp_clock: Clock offset exceeds 1 second (t1=1774476010.144104188 t2=11.106004900 delay=-7613ns offset=-1774476009038091675ns phc_now=11.106402500 |t2-phc|=397600ns)
[00:00:11.156,000] <wrn> ptp_clock: Set clock time: 1774476010.144501775
[00:00:12.155,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:12.156,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:12.156,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 27500ns
[00:00:12.160,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Announce message
[00:00:12.727,000] <dbg> ptp_port: port_delay_req_msg_transmit: Port 1 sends Delay_Req message
[00:00:12.727,000] <dbg> ptp_port: port_delay_req_timestamp_cb: Port 1 registered timestamp for 2 Delay_Req
[00:00:12.727,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Delay_Resp message
[00:00:12.727,000] <dbg> ptp_clock: ptp_clock_delay: Delay 241ns

[...]
[00:00:19.155,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 1100ns
[00:00:20.155,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -164ns
[00:00:20.727,000] <dbg> ptp_clock: ptp_clock_delay: Delay 705ns
[00:00:29.153,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 24ns
[00:00:30.153,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -8ns
[00:00:30.727,000] <dbg> ptp_clock: ptp_clock_delay: Delay 617ns
[00:00:39.152,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -40ns
[00:00:40.152,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -32ns
[00:00:40.727,000] <dbg> ptp_clock: ptp_clock_delay: Delay 601ns
[01:25:54.670,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 2ns
[01:25:55.670,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 34ns
[01:25:56.352,000] <dbg> ptp_clock: ptp_clock_delay: Delay 637ns
[01:25:56.670,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -2ns
[01:25:57.670,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -30ns
[01:25:58.352,000] <dbg> ptp_clock: ptp_clock_delay: Delay 617ns
```

```console
# UDP / IPv4 excerpt
[00:00:01.752,000] <dbg> ptp_port: port_state_update: Port 1 changed state from INITIALIZING to LISTENING
[00:00:03.269,000] <dbg> ptp_port: port_state_update: Port 1 changed state from LISTENING to TIME RECEIVER
[00:00:03.485,000] <dbg> ptp_clock: ptp_clock_delay: Delay 51ns
[00:00:04.445,000] <wrn> ptp_clock: Clock offset exceeds 1 second (...)
[00:00:04.445,000] <wrn> ptp_clock: Set clock time: 1774389604.308807731
[00:00:05.444,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 28018ns
[00:00:05.485,000] <dbg> ptp_clock: ptp_clock_delay: Delay 617ns
[00:00:10.444,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 2493ns
[00:00:11.444,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 635ns
[00:00:11.485,000] <dbg> ptp_clock: ptp_clock_delay: Delay 671ns
[00:00:18.444,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -59ns
[00:00:19.444,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -1ns
[00:00:21.485,000] <dbg> ptp_clock: ptp_clock_delay: Delay 636ns
[00:00:24.444,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset 1ns
[00:00:25.444,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -1ns
[00:00:25.485,000] <dbg> ptp_clock: ptp_clock_delay: Delay 647ns
```

```console
# Nucleo-H563ZI behavior without the STM32H5 timer-rate fix
[00:00:09.826,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Announce message
[00:00:09.826,000] <dbg> ptp_port: port_state_update: Port 1 changed state from LISTENING to TIME RECEIVER
[00:00:09.827,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:09.827,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:10.512,000] <dbg> ptp_port: port_delay_req_msg_transmit: Port 1 sends Delay_Req message
[00:00:10.512,000] <dbg> ptp_port: port_delay_req_timestamp_cb: Port 1 registered timestamp for 0 Delay_Req
[00:00:10.513,000] <dbg> ptp_clock: ptp_clock_delay: Delay 171454959ns
[00:00:10.827,000] <wrn> ptp_clock: Clock offset exceeds 1 second (t1=67.480646204 t2=5.388464840 delay=171454959ns ...)
[00:00:10.827,000] <wrn> ptp_clock: Set clock time: 67.652311843
[00:00:11.826,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Announce message
[00:00:11.826,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:11.827,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:11.827,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -500042100ns
[00:00:12.512,000] <dbg> ptp_port: port_delay_req_msg_transmit: Port 1 sends Delay_Req message
[00:00:12.512,000] <dbg> ptp_port: port_delay_req_timestamp_cb: Port 1 registered timestamp for 1 Delay_Req
[00:00:12.513,000] <dbg> ptp_clock: ptp_clock_delay: Delay 171503451ns
[00:00:12.827,000] <wrn> ptp_clock: Clock offset exceeds 1 second (t1=69.480643844 t2=68.652121463 delay=171503451ns ...)
[00:00:12.827,000] <wrn> ptp_clock: Set clock time: 69.652360895
[00:00:13.826,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Announce message
[00:00:13.826,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:13.827,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -500042160ns
[00:00:14.512,000] <dbg> ptp_port: port_delay_req_msg_transmit: Port 1 sends Delay_Req message
[00:00:14.512,000] <dbg> ptp_port: port_delay_req_timestamp_cb: Port 1 registered timestamp for 2 Delay_Req
[00:00:14.513,000] <dbg> ptp_clock: ptp_clock_delay: Delay 171583643ns
[00:00:14.826,000] <wrn> ptp_clock: Clock offset exceeds 1 second (t1=71.480646204 t2=70.652169975 delay=171583643ns ...)
[00:00:14.826,000] <wrn> ptp_clock: Set clock time: 71.652440587
[00:00:15.826,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Announce message
[00:00:15.826,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Sync message
[00:00:15.826,000] <dbg> ptp_msg: ptp_msg_post_recv: Port 1 received Follow_Up message
[00:00:15.826,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -500042100ns
[00:00:16.512,000] <dbg> ptp_port: port_delay_req_msg_transmit: Port 1 sends Delay_Req message
[00:00:16.512,000] <dbg> ptp_port: port_delay_req_timestamp_cb: Port 1 registered timestamp for 3 Delay_Req
[00:00:16.513,000] <dbg> ptp_clock: ptp_clock_delay: Delay 171637873ns
[00:00:16.826,000] <wrn> ptp_clock: Clock offset exceeds 1 second (t1=73.480643804 t2=72.652250107 delay=171637873ns ...)
[00:00:16.826,000] <wrn> ptp_clock: Set clock time: 73.652494157
[00:00:17.826,000] <dbg> ptp_clock: ptp_clock_synchronize: Offset -500042180ns
```

The last excerpt is the reason for the STM32H5 PTP reference-clock fix: without it, the measured delay is off by roughly 170 ms and the clock keeps bouncing by about 500 ms instead of converging. RM0481 Rev 4 backs the final approach here: the IEEE 1588 section says the 64-bit PTP time is updated from `clk_ptp_ref_i`, and the RCC clock distribution tables list `ETH (ptp)` on `pll1_q_ck`.

If this PR is merged and the maintainers think it would be useful, would it be possible if I can add me as a maintainer for the PTP area? I plan to keep working on this part of the networking stack.

Fixes: #110645

### CODE REVIEW

**Comment by DBS06** [comment]
To be honest I don't understand why sonarcqube is still complaining, I addressed the blocking, medium and some minor issues and inside the report it's still the same old code which does not exist in the branch anymore.

File: subsys/net/lib/sockets/sockets_packet.c [hunk 1]
```diff
@@ -29,26 +29,21 @@ extern const struct socket_op_vtable sock_fd_op_vtable;
```
Comment (jukkar) [inline subsys/net/lib/sockets/sockets_packet.c:30]: About the commit `net: sockets: packet: format sockets_packet.c`, please ignore the clang-format compliance check comments, they are mostly garbage.

File: subsys/net/lib/sockets/sockets_packet.c [hunk 2]
```diff
@@ -338,6 +344,217 @@ ssize_t zpacket_recvfrom_ctx(struct net_context *ctx, void *buf, size_t max_len,
...
+		net_context_get_option(ctx, NET_OPT_RCVTIMEO, &timeout, NULL);
+	}
+
+	ret = zpacket_recvmsg_get_pkt(ctx, flags, timeout, &pkt);
+	if (ret < 0) {
+		errno = -ret;
+		return -1;
+	}
+
+	if (!pkt) {
```
Comment (jukkar) [inline subsys/net/lib/sockets/sockets_packet.c]: Please write this as `if (pkt == NULL) {` as the variable is not a boolean one (Misra rule)

File: subsys/net/lib/sockets/sockets_packet.c [hunk 3]
```diff
@@ -338,6 +344,217 @@ ssize_t zpacket_recvfrom_ctx(struct net_context *ctx, void *buf, size_t max_len,
 	return recv_len;
 }
 
+static int zpacket_insert_cmsg(struct net_msghdr *msg, int level, int type, const void *data,
+			       size_t data_len)
+{
+	struct net_cmsghdr *cmsg;
+	size_t cmsg_space = NET_CMSG_SPACE(data_len);
+
+	if (msg->msg_control == NULL || msg->msg_controllen < cmsg_space) {
```
Comment (jukkar) [inline subsys/net/lib/sockets/sockets_packet.c:373]: Just pondering here, would it make sense to return `-ENOMEM` if there is not enough space to store the data?

File: subsys/net/lib/sockets/sockets_inet.c [hunk 4]
```diff
@@ -1016,8 +1016,9 @@ static int insert_pktinfo(struct net_msghdr *msg, int level, int type,
 			  void *pktinfo, size_t pktinfo_len)
 {
 	struct net_cmsghdr *cmsg;
+	size_t cmsg_space = NET_CMSG_SPACE(pktinfo_len);
 
-	if (msg->msg_controllen < pktinfo_len) {
+	if (msg->msg_controllen < cmsg_space) {
 		return -EINVAL;
```
Comment (jukkar) [inline subsys/net/lib/sockets/sockets_inet.c]: I just wonder if we should return `-ENOMEM` in this case, @rlubos WDYT?

File: subsys/net/lib/sockets/sockets_packet.c (hunk 2 above)
Comment (rlubos) [inline subsys/net/lib/sockets/sockets_packet.c]: `pkt == NULL`

File: doc/connectivity/networking/api/net_shell.rst [hunk 5]
```diff
@@ -30,6 +30,8 @@ The following net-shell commands are implemented:
    :kconfig:option:`CONFIG_NET_PKT_FILTER` is set."
    "net gptp", "Print information about gPTP support. Only available if
    :kconfig:option:`CONFIG_NET_GPTP` is set."
+   "net ptp", "Print information about PTP support. Use ``net ptp <port>`` for detailed
+   per-port view. Only available if :kconfig:option:`CONFIG_PTP` is set."
```
Comment (jukkar) [inline doc/connectivity/networking/api/net_shell.rst]: Please keep the list in alphabetical order so this should be after the ping cmd.

File: subsys/net/lib/sockets/sockets_packet.c [hunk 6]
```diff
@@ -338,6 +344,217 @@ ssize_t zpacket_recvfrom_ctx(struct net_context *ctx, void *buf, size_t max_len,
...
+}
+
+static int zpacket_recvmsg_get_pkt(struct net_context *ctx, int flags, k_timeout_t timeout,
+				   struct net_pkt **pkt)
+{
+	if (flags & ZSOCK_MSG_PEEK) {
+		int res = k_fifo_wait_non_empty(&ctx->recv_q, timeout);
+
+		/* EAGAIN when timeout expired, EINTR when cancelled */
+		if (res && res != -EAGAIN && res != -EINTR) {
```
Comment (rlubos) [inline subsys/net/lib/sockets/sockets_packet.c]: `res != 0 && res != -EAGAIN && res != -EINTR`

File: drivers/ethernet/eth_native_tap.c [hunk 7]
```diff
@@ -16,7 +16,7 @@
  */
```
Comment (jukkar) [inline drivers/ethernet/eth_native_tap.c:16]: No need to changes in `net: format eth_native_tap.c`, clang-format is not doing a good job.

File: tests/net/socket/af_packet/src/main.c [hunk 8]
```diff
@@ -846,6 +853,81 @@ static void test_recv_common(int sock_type, int proto, bool success)
...
+			      "Unexpected msg_controllen %zu", msg.msg_controllen);
+		zassert_equal(cmsg->cmsg_level, ZSOCK_SOL_SOCKET, "Unexpected cmsg level");
+		zassert_equal(cmsg->cmsg_type, ZSOCK_SO_TIMESTAMPING, "Unexpected cmsg type");
+		zassert_equal(cmsg->cmsg_len, NET_CMSG_LEN(sizeof(struct net_ptp_time)),
+			      "Unexpected cmsg length %u", cmsg->cmsg_len);
+
+		memcpy(&timestamp, NET_CMSG_DATA(cmsg), sizeof(timestamp));
+		zassert_mem_equal(&timestamp, &test_rx_timestamp, sizeof(timestamp),
+				  "Unexpected timestamp payload");
+	}
```
Comment (rlubos) [inline tests/net/socket/af_packet/src/main.c]: Not sure why is it placed in an inner block?

File: subsys/net/lib/shell/ptp.c [hunk 9]
```diff
@@ -0,0 +1,373 @@
...
+#endif /* CONFIG_PTP */
+
+static int cmd_net_ptp_port(const struct shell *sh, size_t argc, char *argv[])
+{
+#if defined(CONFIG_PTP)
+	char *endptr = NULL;
+	long port_id;
+#endif
+
+#if defined(CONFIG_PTP)
```
Comment (rlubos) [inline subsys/net/lib/shell/ptp.c]: No need to have two separate `#if defined(CONFIG_PTP)` sections I think?

File: subsys/net/lib/shell/ptp.c [hunk 10]
```diff
@@ -0,0 +1,373 @@
...
+	return 0;
+}
+
+static int cmd_net_ptp(const struct shell *sh, size_t argc, char *argv[])
+{
+#if defined(CONFIG_PTP)
+	int arg = 1;
+#endif
+
+#if defined(CONFIG_PTP)
```
Comment (rlubos) [inline subsys/net/lib/shell/ptp.c]: Ditto. But TBH I don't think `arg` is even needed, just use `argv[1]` as above.

File: subsys/net/lib/shell/ptp.c [hunk 11]
```diff
@@ -0,0 +1,373 @@
...
+	ARG_UNUSED(argc);
+
+	if (argv[arg]) {
```
Comment (rlubos) [inline subsys/net/lib/shell/ptp.c]: `argv[1] != NULL`

File: subsys/net/lib/sockets/sockets_inet.c (hunk 4 above)
Comment (rlubos) [reply subsys/net/lib/sockets/sockets_inet.c]: Sounds fine

**Review by jukkar — DISMISSED** [review]
Thanks Philipp! I mainly reviewed generic network changes which look great, super nice to see that you created tests.

**Comment by DBS06** [comment]
> > Thanks a lot! Imho adding tests for new code, at least the basic ones, should be obligatory for a project the size as zephyr.
> 
> Very true, it was just nice to see test code already there without needing to ask separately.

I know, I almost always need to ask for test for the small part named Fuel-Gauge where I am one of the maintainers. But especially for these kind of

File: drivers/ethernet/eth_stm32_hal_ptp.c [hunk 12]
```diff
@@ -3,6 +3,8 @@
  * Copyright (c) 2020 Alexander Kozhinov <ak.alexander.kozhinov@gmail.com>
  * Copyright (c) 2021 Carbon Robotics
  * Copyright (c) 2025 STMicroelectronics
+ * Copyright (c) 2026 Philipp Steiner <philipp.steiner1987@gmail.com>
```
Comment (maass-hamburg) [inline drivers/ethernet/eth_stm32_hal_ptp.c]: Please note https://docs.zephyrproject.org/latest/contribute/guidelines.html#copyright-and-license-notices

also this change isn't substantial at least for that file

Comment (kartben) [reply drivers/ethernet/eth_stm32_hal_ptp.c]: > also this change isn't substantial at least for that file

it is substantial enough IMO (i.e it's far from a trivial change)

Comment (maass-hamburg) [reply drivers/ethernet/eth_stm32_hal_ptp.c]: renaming a variable (and changing the comments appropriately) is substantial enough?

Comment (DBS06) [reply drivers/ethernet/eth_stm32_hal_ptp.c]: I removed it

File: drivers/ethernet/eth_native_tap.c [hunk 13]
```diff
@@ -145,41 +172,44 @@ static void update_pkt_priority(struct gptp_hdr *hdr, struct net_pkt *pkt)
...
+	ARG_UNUSED(send);
+
+	return false;
+}
 #endif /* CONFIG_NET_GPTP */
 
 static int eth_send(const struct device *dev, struct net_pkt *pkt)
 {
 	struct eth_context *ctx = dev->data;
+	bool timestamp_queued = false;
```
Comment (maass-hamburg) [inline drivers/ethernet/eth_native_tap.c]: no intital val needed, as it is not used
```
	timestamp_queued = update_gptp(net_pkt_iface(pkt), pkt, true);
```

File: subsys/net/lib/ptp/port.h [hunk 14]
```diff
@@ -68,6 +69,10 @@ struct ptp_port {
 	enum ptp_port_state	       (*state_machine)(enum ptp_port_state state,
 							enum ptp_port_event event,
 							bool tt_diff);
+	/** True if a Sync was sent and corresponding Follow_Up is still pending. */
+	bool			       sync_fup_pending;
```
Comment (maass-hamburg) [inline subsys/net/lib/ptp/port.h]: try putting the bools together, for a more efficient mem use

File: subsys/net/lib/ptp/transport.c [hunk 15]
```diff
@@ -293,66 +387,188 @@ int ptp_transport_sendto(struct ptp_port *port, struct ptp_msg *msg, enum ptp_so
...
 			length = NET_IPV6_ADDR_SIZE;
 			memcpy(addr, ip, length);
 		}
+	} else if (IS_ENABLED(CONFIG_PTP_IEEE_802_3_PROTOCOL)) {
+		struct net_linkaddr *lladdr = net_if_get_link_addr(port->iface);
+
+		if (lladdr && lladdr->len <= NET_ETH_ADDR_LEN) {
+			length = lladdr->len;
+			memcpy(addr, lladdr->addr, length);
+		}
```
Comment (maass-hamburg) [inline subsys/net/lib/ptp/transport.c]:
```suggestion
		if (lladdr && lladdr->len == NET_ETH_ADDR_LEN) {
			length = NET_ETH_ADDR_LEN;
			memcpy(addr, lladdr->addr, length);
		}
```
is smaller really fine?

File: drivers/ethernet/eth_native_tap.c (hunk 13 above)
Comment (DBS06) [reply drivers/ethernet/eth_native_tap.c]: Done

File: subsys/net/lib/ptp/port.h (hunk 14 above)
Comment (DBS06) [reply subsys/net/lib/ptp/port.h]: Done

File: subsys/net/lib/ptp/transport.c (hunk 15 above)
Comment (DBS06) [reply subsys/net/lib/ptp/transport.c]: Done

**Comment by DBS06** [comment]
**Changelog 1.0**

After further intense testing by repeatedly connecting and disconnecting Ethernet cables and changing the network topology, I identified several additional bugs in the PTP link recovery, worker wakeup, and TX timestamp callback paths.

* Updated the PTP clock worker path so pollfd invalidation wakes the worker immediately, and repeated state-decision requests only trigger one wakeup while an event is already pending. This avoids the worker staying blocked on stale poll state after transport or link changes.
* Updated the existing `clock_decision` regression setup to enable `CONFIG_ZVFS` and `CONFIG_ZVFS_EVENTFD`, so the direct `clock.c` test path can exercise the eventfd-backed worker logic.
* Fixed a deadlock in `net_if` TX timestamp callback dispatch. Timestamp callbacks can now unregister themselves or other callbacks while dispatch is in progress without re-entering the callback-list lock. Inactive callbacks are skipped during iteration and pruned afterward.
* Added regression coverage for the TX timestamp callback edge cases above. The test now covers both self-unregister and unregister-other scenarios, and verifies callbacks are not invoked twice and packet references are still released correctly.
* Added a `ptp_clock_wakeup` unit test suite for the PTP clock worker wakeup path. It verifies pollfd invalidation is quiet before init, wakes the worker after init, and that repeated state-decision requests do not generate duplicate wakeups while one is already pending.
* Fixed PTP message lifetime leaks across link-down/link-up transitions by releasing retained `last_sync_fup`, pending `Delay_Req`, and foreign time transmitter announce records during port disable and teardown. This prevents the PTP message slab from being exhausted after repeated topology changes, which could otherwise stall the PTP worker thread and later cascade into packet cloning and RX buffer allocation failures.

File: tests/net/ptp/state_matrix/src/main.c
Comment (awojasinski) [inline tests/net/ptp/state_matrix/src/main.c:1]: Not a blocker but it is missing some cases like:

INITIALIZE event in every state should result in INITIALIZING
FAULT_DETECTED if in FAULTY state

File: subsys/net/lib/ptp/msg.c [hunk 16]
```diff
@@ -307,6 +379,17 @@ struct ptp_msg *ptp_msg_from_pkt(struct net_pkt *pkt)
 	return NULL;
 }
 
+struct ptp_msg *ptp_msg_from_pkt(struct net_pkt *pkt)
+{
+	struct ptp_msg *msg = msg_from_udp_pkt(pkt);
```
Comment (awojasinski) [inline subsys/net/lib/ptp/msg.c]: When user chose L2 it always calls UDP packet handling. Is it right?

**Review by awojasinski — COMMENTED** [review]
Overall looks great! thanks for your contribution, you did a lot of things that were on my TODO. I have only one concern in `ptp_msg_from_pkt()` I want to clarify.

File: tests/net/ptp/state_matrix/src/main.c
Comment (DBS06) [reply tests/net/ptp/state_matrix/src/main.c:1]: These cases are already covered by the full matrix test, but I agree that it is not very obvious at first glance.

`test_ptp_state_machine_full_matrix_tt_diff_false()` and `test_ptp_tr_state_machine_full_matrix_tt_diff_false()` iterate over the full cartesian product of `all_states[]` x `all_events[]`, so `INITIALIZE` is exercised for every state and `(FAULTY, FAULT_DETECTED)` is included as well.

For `INITIALIZE`, the expected helper handles it before the state switch, so every source state is expected to transition to `INITIALIZING`. For `FAULT_DETECTED` while already in `FAULTY`, the expected result is the self-loop back to `FAULTY`, which is also what the implementation does.

I can add a short comment or a couple of explicit spot-check asserts to make those two cases more visible if you think that would help readability.

File: subsys/net/lib/ptp/msg.c (hunk 16 above)
Comment (DBS06) [reply subsys/net/lib/ptp/msg.c]: Not exactly. The transport selection is a Kconfig `choice`, so only one PTP transport is enabled at build time, and the normal RX path is already transport-specific: with `CONFIG_PTP_IEEE_802_3_PROTOCOL=y`, `ptp_transport_recv()` goes straight to `transport_recv_l2_msg()`.

`ptp_msg_from_pkt()` is only used in the TX timestamp callback path. There I currently probe `msg_from_udp_pkt()` first and then fall back to `msg_from_l2_pkt()`. For an IEEE 802.3 frame the UDP probe returns `NULL` quickly, and the L2 helper does the actual parsing, so L2 traffic is not being interpreted as UDP.

That said, I agree the current ordering/name is a bit misleading. I can make it clearer by selecting the parser directly from the configured transport instead of doing a UDP-first probe.

**Comment by DBS06** [comment]
> Overall looks great! thanks for your contribution, you did a lot of things that were on my TODO. I have only one concern in `ptp_msg_from_pkt()` I want to clarify.

Thanks a lot for the review and the kind words, I really appreciate it.

I replied inline on `ptp_msg_from_pkt()`. I agree the current flow is not very obvious from the code as written. If you prefer, I can rework that helper to select the parser directly from the configured transport so the intent is clearer.

File: subsys/net/lib/ptp/msg.c (hunk 16 above)
Comment (awojasinski) [reply subsys/net/lib/ptp/msg.c]: Not sure about this quick return. You're right if the `CONFIG_NET_UDP` is not set but if someone will set that symbol the function will still use UDP parsing and waste time. Not sure if that scenario is possible.

I would prefer if you add preprocessor guards for `msg_from_udp_pkt()`

Comment (DBS06) [reply subsys/net/lib/ptp/msg.c]: Perfect, I totally agree and will do that asap, most likely tonight.

Comment (DBS06) [reply subsys/net/lib/ptp/msg.c]: Done. I updated it so `msg_from_udp_pkt()` is only built if `CONFIG_PTP_UDP_IPv4_PROTOCOL` or `CONFIG_PTP_UDP_IPv6_PROTOCOL` is selected. Same for `msg_from_l2_pkt()`, which will only built if `CONFIG_PTP_IEEE_802_3_PROTOCOL` is selected.

Furthermore, I removed the `LOG_ERR()`s in `msg_from_udp_pkt()`, because in the current design `ptp_msg_from_pkt()`, is used from the TX timestamp callbacks in `port_delay_req_timestamp_cb()` in `port.c` and this helper is part of the TX timestamp callback filtering path, so "this packet is not the expected PTP/UDP frame" is normal, not exceptional and `LOG_ERR()`/`LOG_WRN()` messages will be noisy and misleading.

File: subsys/net/ip/net_if.c [hunk 17]
```diff
@@ -6323,18 +6370,30 @@ void net_if_call_timestamp_cb(struct net_pkt *pkt)
...
 		if (((handle->iface == NULL) ||
 		     (handle->iface == net_pkt_iface(pkt))) &&
 		    (handle->pkt == NULL || handle->pkt == pkt)) {
 			handle->cb(pkt);
 		}
 	}
 
+	timestamp_cb_prune_locked();
+	timestamp_cb_dispatch_depth--;
+	if (timestamp_cb_dispatch_depth == 0U) {
```
Comment (jukkar) [inline subsys/net/ip/net_if.c]: Perhaps very unlikely but would it make sense to check that we do not underflow the value. For that the type of `timestamp_cb_dispatch_depth` should be set to int (there should be no need it to be unsigned anyway).

Comment (DBS06) [reply subsys/net/ip/net_if.c]: Good point. In `timestamp_cb_dispatch_depth` is only incremented and decremented under lock inside `net_if_call_timestamp_cb()`, so there should not be a normal underflow path. I changed it to `int`, made the "current dispatch" check depend on `depth > 0`, and guarded the decrement so we cannot silently wrap if that assumption is ever broken.

File: drivers/ethernet/eth_stm32_hal_common.c [hunk 18]
```diff
@@ -113,15 +113,15 @@ static int eth_initialize(const struct device *dev)
...
+	/* Set up gated and source clocks */
 	for (size_t n = 0; n < cfg->pclken_cnt; n++) {
-		if (n == cfg->kclk_sel_idx) {
+		if (IN_RANGE(cfg->pclken[n].bus, STM32_PERIPH_BUS_MIN, STM32_PERIPH_BUS_MAX)) {
+			ret = clock_control_on(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
+					       (clock_control_subsys_t)&cfg->pclken[n]);
+		} else {
 			ret = clock_control_configure(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
 						      (clock_control_subsys_t)&cfg->pclken[n],
 						      NULL);
```
Comment (erwango) [inline drivers/ethernet/eth_stm32_hal_common.c:124]: Nice! This could probably be extended to more drivers.
FYI @mathieuchopstm

File: drivers/ethernet/eth_stm32_hal_common.c [hunk 19]
```diff
@@ -113,15 +113,15 @@ static int eth_initialize(const struct device *dev)
...
-		} else {
-			ret = clock_control_on(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
-					       (clock_control_subsys_t)&cfg->pclken[n]);
 		}
```
Comment (tpambor) [inline drivers/ethernet/eth_stm32_hal_common.c:125]: This needs to be changed also in dwmac driver, https://github.com/zephyrproject-rtos/zephyr/blob/6182bc08c9d72e9e9aed8f5cf05a406fbfd25dd8/drivers/ethernet/eth_dwmac_stm32h7x.c#L95-L101

There was no `clock_control_configure` before, as no chip with `eth-ker` clock was supported, but with this change this is now required there as well.

**Review by awojasinski — DISMISSED** [review]
PTP subsys part and tests looks great! thanks for contribution

File: drivers/ethernet/eth_stm32_hal_common.c (hunk 19 above)
Comment (DBS06) [reply drivers/ethernet/eth_stm32_hal_common.c:125]: I can do that if you like?
Should I place it in the same commit?

**Comment by DBS06** [comment]
> PTP subsys part and tests looks great! thanks for contribution

Thanks a lot for your review!

File: drivers/ethernet/eth_stm32_hal_common.c (hunk 19 above)
Comment (maass-hamburg) [reply drivers/ethernet/eth_stm32_hal_common.c:125]: yes, otherwise bi-selectability is not ensured. if you do a breaking change, you have to fix it in the tree in the same commit

Comment (DBS06) [reply drivers/ethernet/eth_stm32_hal_common.c:125]: Perfect, I will do that asap!

Comment (DBS06) [reply drivers/ethernet/eth_stm32_hal_common.c:125]: Done

**Review by awojasinski — DISMISSED** [review]

**Comment by DBS06** [comment]
## Changelog 1.1

To inform you, I performed additional validation, including long-running tests (>1 week) and link disruption scenarios (disconnect/reconnect) in various and changing roles (Grandmaster, Time Receiver, with and without an intermediate ptp capable switch, with multiple Nucleo-H563ZI Boards).

With these changes, the PTP stack appears stable and free of observable errors, at least from my side.

The only issue identified during testing was an incorrect calculation of `steps_rm`, see details below:

- Rebased branch onto current `main` (previously >400 commits behind) and resolved merge conflicts
- Fix stale foreign Announce selection during GM handover:
  - Select the newest queued Announce instead of the oldest one
  - Prevent incorrect `steps_rm` values
  - Avoid mismatched GM information in `net ptp` after topology changes

### Code change

**`port.c:1431`**

from
```c
last = (struct ptp_announce_msg *)k_fifo_peek_head(&foreign->messages);
```
to
```c
last = (struct ptp_announce_msg *)k_fifo_peek_tail(&foreign->messages);
```

@awojasinski @jukkar @tpambor @maass-hamburg @aescolar Can you do a re-review? ;-)

**Review by awojasinski — APPROVED** [review]

**Review by tpambor — APPROVED** [review]

File: samples/net/ptp/README.rst [hunk 20]
```diff
@@ -36,35 +44,295 @@ Follow these steps to build the PTP sample application:
...
+    *** Booting Zephyr OS build ... ***
+    <inf> net_ptp_sample: Runs forever
+
+``Runs forever`` is expected because ``CONFIG_NET_SAMPLE_RUN_DURATION=0`` in
+the sample configuration.
+
+Step 5 - Attach to Zephyr shell
+-------------------------------
+
+If ``screen`` is installed:
```
Comment (jukkar) [inline samples/net/ptp/README.rst:314]: The manual instructions are nice, but it is also possible to automatically launch screen in Linux for example by this config option
```
CONFIG_UART_NATIVE_PTY_AUTOATTACH_DEFAULT_CMD="gnome-terminal -- screen %s" 
```
This way there is no need to try to figure out the pts from the output. Just a note, no need to update the PR just for this change, but you might consider follow-up PR adding this info.

**Review by jukkar — APPROVED** [review]

File: tests/net/ptp/clock_decision/CMakeLists.txt [hunk 21]
```diff
@@ -0,0 +1,24 @@
...
+  src/main.c
+  ${ZEPHYR_BASE}/subsys/net/lib/ptp/clock.c
+)
+
+target_include_directories(app PRIVATE
+  ${ZEPHYR_BASE}/subsys/net/lib/ptp
+)
+
+target_compile_definitions(app PRIVATE
+  CONFIG_PTP_LOG_LEVEL=3
```
Comment (aescolar) [inline tests/net/ptp/clock_decision/CMakeLists.txt:17]: Why are these being overriden from cmake instead of using kconfig? (for all tests)

File: tests/net/ptp/msg_post_recv/testcase.yaml [hunk 22]
```diff
@@ -0,0 +1,13 @@
...
+    - ptp
+    - unit
+  platform_allow:
+    - native_sim
+  integration_platforms:
+    - native_sim
+  depends_on: netif
+tests:
+  net.ptp.msg_post_recv:
+    min_ram: 32
```
Comment (aescolar) [inline tests/net/ptp/msg_post_recv/testcase.yaml:13]: These test configurations are a bit weird.
platform_allow should only be used if indeed a test can only be run in a given platform.
But if it can only run in one, there is no need to set integration_plaftorms to the same.
And less to set a ram requirement.

File: samples/net/ptp/README.rst (hunk 20 above)
Comment (DBS06) [reply samples/net/ptp/README.rst:314]: Will fix/add that in a follow-up PR

File: tests/net/ptp/clock_decision/CMakeLists.txt (hunk 21 above)
Comment (DBS06) [reply tests/net/ptp/clock_decision/CMakeLists.txt:17]: Good point. I used the CMake definitions because these are white-box unit tests that compile selected PTP implementation files directly into the test binary instead of enabling the full PTP subsystem. That made it easy to provide only the `CONFIG_PTP_*` constants needed by those files.

That said, I agree this is not the right style for Zephyr tests, especially for Kconfig choice/derived symbols like `CONFIG_PTP_CLOCK_TYPE` and `CONFIG_PTP_CLOCK_ACCURACY`. Since the PR is already merged, I will clean this up in a follow-up PR by moving the test configuration into the test Kconfig fragments (`prj.conf` / `extra_configs`) and keeping CMake only for source selection.

File: tests/net/ptp/msg_post_recv/testcase.yaml (hunk 22 above)
Comment (DBS06) [reply tests/net/ptp/msg_post_recv/testcase.yaml:13]: Agreed, this is over-specified. I used `native_sim` as the representative test platform, but these unit tests are not inherently tied to that platform.

I will clean this up in a follow-up PR: remove `platform_allow` for the generic PTP unit tests, keep `integration_platforms` only where it is useful as a CI hint, and drop the unnecessary `min_ram` setting. For any test that really is native-only, I will keep `platform_allow` and remove the redundant matching `integration_platforms`.
