### PR TITLE
ARM Cortex-M: Fix booting in no-multithreading mode 

### LINKED ISSUE #16210: ARM: initialization sequence might be not using all of interrupt stack
The interrupt stack is defined using the `K_THREAD_STACK_DEFINE(<requested size>) `kernel macro. In some architectures, for example the ARM architecture without requirement for stack start alignment, the size of the stack, defined with `K_THREAD_STACK_DEFINE() `is larger than `<requested size>` due to possibly a stack guard.

First, of, all, this is not yet needed - we do not support MPU-based stack-overflow protection in the ISR stack at the moment.
Then, the possible guard area is not taken into account in `reset.S`, so we do not use this area we have reserved for the interrupt stack. It's a (minor) memory wasting.

There are some straightforward ways to fix this issue;
- don't use K_THREAD_STACK_DEFINE for the ISR stack
- account for the actual size of the interrupt stack in reset.S
- ....

### LINKED ISSUE #26796: Interrupts on Cortex-M do not work with CONFIG_MULTITHREADING=n
**Describe the bug**
When `CONFIG_MULTITHREADING=n` then interrupts are initially disabled (see bug #8393) when they are enabled then usage fault happens immediately (seems that it happens during returning from interrupt).

**To Reproduce**
1. modify hello_world:
```
void main(void)
{
        /* enable interrupts */
	irq_unlock(0);
	printk("Hello World! %s\n", CONFIG_BOARD);
        /* wait for interrupt coming from LF clock being started. */
	k_busy_wait(1000000);

}
```

prj.conf:
```
CONFIG_MULTITHREADING=n
CONFIG_LOG=y
```

2. buid and run. I used nrf52840dk_nrf52840 board
```
*** Booting Zephyr OS build zephyr-v2.3.0-979-ga043d48c5472  ***
[00:00:02.426,116] <err> os: ***** USAGE FAULT *****
[00:00:02.426,116] <err> os:   Illegal load of EXC_RETURN into PC
[00:00:02.426,116] <err> os: r0/a1:  0x00000004  r1/a2:  0x00000001  r2/a3:  0x00000001
[00:00:02.426,116] <err> os: r3/a4:  0x00000000 r12/ip:  0x00000020 r14/lr:  0x000029db
[00:00:02.426,116] <err> os:  xpsr:  0x00000000
[00:00:02.426,147] <err> os: Faulting instruction address (r15/pc): 0xe000ed00
[00:00:02.426,147] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:02.426,147] <err> os: Current thread: 0x00000000 (unknown)
[00:00:03.378,143] <err> os: Halting system
```

**Expected behavior**
No error should appear.

**Impact**
Interrupts cannot be used when multithreading is off. User cannot use any driver (even out of tree which does not use kernel synchronization apis).

**Environment (please complete the following information):**
 - Commit a043d48c54726082521f3e335d807dc649cc02f3

### PR DESCRIPTION
**Pull request by ioannisg**
This PR fixes the issues with Cortex-M when building without multi-threading support. In particular
- it properly sets the PSP _back_ to the main stack so main() uses the main stack and ISRs will use the _interrupt_stack. This has never worked, but needs to work, in order to use IRQs in the no multi-threading case.
- configures FPU, MPU guards and PSPLIM accordingly, to mimic what is going on in the normal CONFIG_MULTITHREADING=y case. This allows to use FPU and HW stack overflow in main().
- adds the required hook in the kernel z_cstart() to make the change less intrusive; only Cortex-M is affected - no other functional cases.

I am going to add a simple test to verify the feature. **Test added**

Also this PR fixes a minor enhancement issue with the interrupt stack in reset.S.

Fixes #26796
Fixes #16210

### CODE REVIEW

**Comment by pabigot** [comment]
Using #27136 on current master I've confirmed broken `CONFIG_MULTITHREADING=n` support on:

* nucleo_l476rg (program dies after BOOT_BANNER)
* nrf52840dk_nrf52840 (program runs, but once interrupt fires everything stops)
* frdm_k64f (program dies after BOOT_BANNER)

Clearly `CONFIG_MULTITHREADING=n` is a poorly tested configuration, and the failure is *not* Nordic-specific.

With this patch using master button test (and default `CONFIG_MULTITHREADING=y`) all platforms pass.

With #27136 (`CONFIG_MULTITHREADING=n`) this PR on current master all platforms pass, so functional checks look good.  Review incoming.

**Comment by pabigot** [comment]
> With #27136 (`CONFIG_MULTITHREADING=n`) this PR on current master all platforms pass

however, if the explicit `irq_unlock(0)` added in that code is removed so interrupts are enabled in main the tests run but no button presses are detected.  All platforms.

So though this fixes #26796, it does not fix disabling multithreading.

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c [hunk 1]
```diff
@@ -86,6 +90,21 @@ void z_arm_configure_static_mpu_regions(void)
...
+		/* Main stack MPU guard to detect overflow.
+		 * Note:
+		 * FPU_SHARING and USERSPACE are not supported features
+		 * under CONFIG_MULTITHREADING=n, so the MPU guard (if
+		 * exists) is reserved aside of CONFIG_MAIN_STACK_SIZE
+		 * and there is no requirement for larger guard area (FP
+		 * context is not stacked).
+		 */
+		const struct k_mem_partition main_stack_guard_region = {
+		.start = (uint32_t)z_main_stack,
```
Comment (pabigot) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:103]: indentation?

**Review by pabigot — APPROVED** [review]
One style issue, and a couple typos in commit messages.  This definitely improves things, though not enough to make single-threaded code work without extra help (#8393).

* Patch 1: s/little intrucive/unintrusive/
* Patch 3: s/Cortex-M ARCHictecture/Cortex-M architecture/

**Comment by ioannisg** [comment]
@pabigot thanks for the review. Yeap, there are multiple typos and style fixes needed, I will revisit this PR and write also a test.

> One style issue, and a couple typos in commit messages. This definitely improves things, though not enough to make single-threaded code work without extra help (#8393).

This patch is not meant to fix all issues with NO MULTITHREADING; i.e. it does not automatically enable IRQs; I still leave this to the user. But at least, it makes things work, if one wants run main() with IRQs and APIs that do not depend on kernel. 

I am not against enabling IRQs automatically - we could do this in another RFC PR.

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 1 above)
Comment (ioannisg) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:103]: fixed

**Comment by ioannisg** [comment]
> One style issue, and a couple typos in commit messages. This definitely improves things, though not enough to make single-threaded code work without extra help (#8393).
> 
> * Patch 1: s/little intrucive/unintrusive/
> * Patch 3: s/Cortex-M ARCHictecture/Cortex-M architecture/

fixed now

**Comment by de-nordic** [comment]
I have built the `mcuboot` for nrf52840dk with the fix, with `CONFIG_MULTITHREADING=n` and serial recovery enabled.
I have been able to successfully upload and confirm test images via serial so the problem with serial not working in non-multithreading mode has gone.

File: kernel/init.c [hunk 2]
```diff
@@ -477,6 +477,13 @@ FUNC_NORETURN void z_cstart(void)
...
 	switch_to_main_thread(prepare_multithreading());
+#else
+#ifdef ARCH_SWITCH_TO_MAIN_NO_MULTITHREADING
+	/* Custom ARCH-specific routine to switch to main()
+	 * in the case of no multi-threading.
+	 */
+	arch_switch_to_main_no_multithreading(bg_thread_main,
+		NULL, NULL, NULL);
 #else
 	bg_thread_main(NULL, NULL, NULL);
```
Comment (anangl) [inline kernel/init.c:488]: Shouldn't the `#ifdef ARCH_SWITCH_TO_MAIN_NO_MULTITHREADING` end here, so that the execution falls into the `while (true)` loop below in case `bg_thread_main()` returns? See the end of `bg_thread_main()`:
https://github.com/zephyrproject-rtos/zephyr/blob/b8f4f2032c862979b6c0eaa28e008f1c998fb904/kernel/init.c#L261-L270.

File: arch/arm/core/aarch32/thread.c [hunk 3]
```diff
@@ -420,3 +430,48 @@ void arch_switch_to_main_thread(struct k_thread *main_thread, char *stack_ptr,
...
+#if defined(CONFIG_BUILTIN_STACK_GUARD)
+	char *psplim = (Z_THREAD_STACK_BUFFER(z_main_stack));
+	/* Clear PSPLIM before setting it to guard the main stack area. */
+	__set_PSPLIM(0);
+#endif
+
+	__asm__ volatile (
+	"mov  r0, %0\n\t"
+	"mov  r1, %1\n\t"
+	"mov  r2, %2\n\t"
```
Comment (anangl) [inline arch/arm/core/aarch32/thread.c:456]: Is it not possible to use local register variables here instead, I mean:
```
	register void* p1_input __asm__ ("r0") = p1;
	register void* p2_input __asm__ ("r1") = p2;
	register void* p3_input __asm__ ("r2") = p3;
	__asm__ volatile (
#ifdef CONFIG_BUILTIN_STACK_GUARD
	"msr  PSPLIM, %5\n\t"
#endif
	"msr  PSP, %3\n\t"
	"blx  %4\n\t" /* call main entry hook */
	:
	: "r" (p1_input), "r" (p2_input), "r" (p3_input),
	  "r" (psp), "r" (main_entry)
#ifdef CONFIG_BUILTIN_STACK_GUARD
	  , "r" (psplim)
#endif
	);
```
and avoid specifying those registers as clobbers?

File: kernel/init.c (hunk 2 above)
Comment (ioannisg) [reply kernel/init.c:488]: I think this is complicated to do and might not worth the effort.
Normally, if a function changes the stack pointer, it should not return to the caller (using the caller convention). Such functions should not return. That's what happens, practically in `switch_to_main_thread(prepare_multithreading());`
Might be ok if the caller does not use the stack, but it feels _too_ error prone.

Comment (anangl) [reply kernel/init.c:488]: Then maybe such infinite loop should be added to `z_arm_switch_to_main_no_multithreading()` so that this function indeed cannot return?

Comment (ioannisg) [reply kernel/init.c:488]: Yes, that I could do. I'll mimic the init.c  and add an irq_lock and a while(1)

File: arch/arm/core/aarch32/thread.c (hunk 3 above)
Comment (ioannisg) [reply arch/arm/core/aarch32/thread.c:456]: Sort of a matter of taste, no? I reduce to clobber list to r0-r2. Like this, it is similar to the function arch_switch_to_main_thread, in this file.

**Comment by ioannisg** [comment]
@anangl I addressed your comments, particularly the ones suggesting functional changes.
Uploaded the test that verifies the single-thread operation in ARM Cortex-M

**Comment by carlescufi** [comment]
@anangl could you take another look please?

**Review by MaureenHelm — APPROVED** [review]

**Comment by de-nordic** [comment]
I have used the newest changes from this PR to compile mcuboot in non-multithreading mode and serial recovery enabled, repeating the previous tests https://github.com/zephyrproject-rtos/zephyr/pull/27343#issuecomment-668119695 and everything seems to work correctly.

**Review by de-nordic — APPROVED** [review]

**Comment by ioannisg** [comment]
> I have used the newest changes from this PR to compile mcuboot in non-multithreading mode and serial recovery enabled, repeating the previous tests [#27343 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/27343#issuecomment-668119695) and everything seems to work correctly.

Thanks @de-nordic 
I think maybe we have a chance also to enabled IRQs before jumping to main, and then solve #8393 as well, for Cortex-M.

Is this something we would like to do, @pabigot @andyross ?

**Comment by ioannisg** [comment]
Adding DNM, cause I want @anangl to look at the patch, before getting it in.

**Comment by pabigot** [comment]
I do think interrupts should be enabled automatically: it's surprising when they aren't.

> before jumping to main

To clarify, that's before jumping to `bg_thread_main`, not to `main`, right?  Because drivers that initialize post-kernel may be counting on having interrupts work.

**Comment by ioannisg** [comment]
> I do think interrupts should be enabled automatically: it's surprising when they aren't.
> 
> > before jumping to main
> 
> To clarify, that's before jumping to `bg_thread_main`, not to `main`, right? Because drivers that initialize post-kernel may be counting on having interrupts work.

Yes, correct.
Again, I would do this for Cortex-M only, if there is an interest for it, but not a wide consensus to do this for all ARCHes.

**Comment by pabigot** [comment]
> Again, I would do this for Cortex-M only, if there is an interest for it, but not a wide consensus to do this for all ARCHes.

I think it needs to be consistent across architectures.

Also a decision on whether to enable interrupts should not delay merge of this PR.

**Comment by de-nordic** [comment]
> I think maybe we have a chance also to enabled IRQs before jumping to main, and then solve #8393 as well, for Cortex-M.

When you do a PR with that I can check the mcuboot for you.

**Review by andyross — COMMENTED** [review]
No complaints about the code, but I guess I don't understand why, if you have MULTITHREADING=n, you want the stack switch to happen?  The original idea was that Zephyr would launch on the interrupt stack and stay there, since there is only one thread that will never swap.

Is there a technical reason you can't handle a "nested" interrupt on this stack?

**Comment by ioannisg** [comment]
@andyross thanks. There are some advantages of keeping the two stacks (but I agree with you that a single stack would work too). Zephyr ARM architecture code heavily depends on the fact that the ISRs use a different stack from the thread mode; if we want to use the same stack, lots of things need to be re-worked, and I wanted to **avoid** this.

A good example is the stack overflow case (and in general, the fault handling). Assessing faults is done by inspecting the stack frame which is on PSP; if we want to use MSP in the no-multithreading case, fault inspection needs a re-write.

Also, ARM reset code uses the interrupt stack with the Process stack pointer. We don't want to modify this common code and create confusion. Since IRQs will use the Main stack pointer, we need to switch _back_ to using MSP in thread mode after initialization; this requires lots of #ifdef CONFIG_MULTITHREADING in the architecture code base.

Using a different stack pointer, depending on CONFIG_MULTITHREADING will also be a bit confusing for developers that need to debug Cortex-M code; they are used to see the main() running on PSP.

The interrupt stack gets defined in kernel code, same as the main stack, so we're reserving the area anyways, so not using it does not bring any benefit (unless we change kernel code for that, which i did not want to do). The point was to support this feature properly, with as few changes to the code base as possible.

File: arch/arm/core/aarch32/thread.c (hunk 3 above)
Comment (anangl) [reply arch/arm/core/aarch32/thread.c:456]: Well, it's not solely a matter of taste. The way it is now, the compiler is forced to use some other registers just for preparing values to be written to r0-r2 in the inline assembly code. Because of the above call to `z_arm_prepare_switch_to_main()`, the compiler anyway needs to store somewhere (probably in some higher registers) parameters p1-p3 that were passed in registers r1-r3, so in this particular case there will be probably no noticeable difference. By using local register variables, you make the compiler aware of what you in fact need for the inline assembler and you let it do the best register allocation it can. It could matter in some other cases for which this piece of code could be copied in some future, or if this function gets modified at some point.

File: arch/arm/core/aarch32/thread.c [hunk 4]
```diff
@@ -420,3 +430,54 @@ void arch_switch_to_main_thread(struct k_thread *main_thread, char *stack_ptr,
...
+	"mov  r4, %3\n\t"
+	"mov  r5, %5\n\t"
```
Comment (anangl) [inline arch/arm/core/aarch32/thread.c:458]: What if those registers get allocated for inputs `%4` or `%6`? Or `r4` for input `%5`?

Comment (ioannisg) [reply arch/arm/core/aarch32/thread.c:458]: Yes, these need to be clobbered

Comment (anangl) [reply arch/arm/core/aarch32/thread.c:458]: And that's also a reason why I think using local register variables is a better approach. You don't get into such problems, as the compiler cares about used registers itself.

Comment (ioannisg) [reply arch/arm/core/aarch32/thread.c:458]: Alright, I 'll switch to using local register values.
I have actually taken this approach in the system calls generation code.

Comment (ioannisg) [reply arch/arm/core/aarch32/thread.c]: Updated: I defined local register variables, to hold the required input, after the stack pointer has changed.
I had to use high registers, as the total constraints' set for Cortex-M0 was resulting to a non-feasible implementation.

Now I  still need to use manual "mov" instructions to copy the arguments to r0,r1,r2, since i don't clobber these registers any more. That's for extra safety.

**Comment by carlescufi** [comment]
Do not merge until the outcome of #27415 is decided.

File: arch/arm/core/aarch32/thread.c [hunk 5]
```diff
@@ -420,3 +445,58 @@ void arch_switch_to_main_thread(struct k_thread *main_thread, char *stack_ptr,
...
+#endif
+	"msr  PSP, %[_psp]\n\t"       /* __set_PSP(psp) */
+	"blx  %[_main_entry]\n\t"     /* main_entry(p1, p2, p3) */
+#if defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE)
+	"cpsid i\n\t"         /* disable_irq() */
+#elif defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
+	"msr BASEPRI, %[basepri]\n\t"/* __set_BASEPRI(_EXC_IRQ_DEFAULT_PRIO) */
+	"isb\n\t"
+#endif
+	"loop: b loop\n\t"    /* while (true); */
```
Comment (anangl) [inline arch/arm/core/aarch32/thread.c:487]: Is `isb` actually needed here?

File: tests/arch/arm/arm_no_multithreading/src/main.c [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+
+#if !defined(CONFIG_CPU_CORTEX_M)
+  #error test can only run on Cortex-M MCUs
+#endif
+
+extern K_THREAD_STACK_DEFINE(z_main_stack, CONFIG_MAIN_STACK_SIZE);
+
+static volatile int test_flag;
+
+void arm_isr_handler(void *args)
```
Comment (anangl) [inline tests/arch/arm/arm_no_multithreading/src/main.c:20]: Could be `static`.

**Review by anangl — APPROVED** [review]

**Comment by ioannisg** [comment]
> Do not merge until the outcome of #27415 is decided.

Not sure I agree with this principle, @carlescufi. The discussion of whether to support single-threading or not is legitimate, however, this PR is a bug fix of an existing feature in zephyr, it is only a bug fix, and affects nothing outside the single-threading case. What is the timeline for the decision in #27415? In the mean time, why do you suggest having a broken feature in Zephyr instead of a feature working fine, even if it is candidate for removal?

**Comment by pabigot** [comment]
> > Do not merge until the outcome of #27415 is decided.
> 
> Not sure I agree with this principle, @carlescufi.

I'm sure I do not agree.

The existing behavior is wrong on all ARM Cortex-M.  This fixes it.  Merging an acceptable low-risk fix seems appropriate even if the long-term presence of the feature is in doubt.  We're rapidly approaching feature freeze and need to start looking at stabilizing what we've got.  It would be bad to put this off for very long.

**Comment by carlescufi** [comment]
@ioannisg and @pabigot This introduces functionality that is strictly tied to `CONFIG_MULTITHREADING`, that was my reasoning for waiting to merge this. But since deciding on the future of that Kconfig variable might take time, I agree to merge this in the meantime.
