### PR TITLE
Bluetooth: host: Fix disconnect priority event handling

### LINKED ISSUE #32742: Bluetooth: GAP: LE connection complete event handling priority
**Describe the bug**
Controller send CONNECT_IND PDU, notify host by connection complete event (**evt code:0x3e, subcode:0x0a**), the timeout or error happen and notify the host by disconnection event(**evt code:0x05**). Rx thread put connection complete event in **rx.queue**, not process directly. At this time, Rx thread received the disconnection event, and process directly. 

So the Rx thread process event sequence is wrong: 

1. disconn event prio. 
2. process conn complete evt. 
3. process disconn event normal.

**The right state sequence is:**
```
bt_conn_connect -> bt_conn_connected; (conn evt)
bt_conn_connected->bt_conn_disconnect_complete( disconn evt prio)
bt_conn_disconnect_complete-> bt_conn_disconnected (disconn evt nomal)
```
**The wrong state sequence is:**
```
bt_conn_connect-> bt_conn_connected;(conn evt)
bt_conn_connected-> bt_conn_disconnected;(disconn evt normal)
```
**The error will happen:**
```
Unable to look up conn with handle %u. (return directly, lost the disconn evt prio)
Invalid (%u) old state(bt_conn_connected->bt_conn_disconnected).
```

Workaround ?
in bt_recv();
```
if (hdr->evt == BT_HCI_EVT_LE_META_EVENT) {
+			struct bt_hci_evt_le_meta_event *sub_event =
+				(struct bt_hci_evt_le_meta_event *)(buf->data
+					+ sizeof(struct bt_hci_evt_hdr));
+			switch (sub_event->subevent) {
+			case BT_HCI_EVT_LE_CONN_COMPLETE:
+			case BT_HCI_EVT_LE_ENH_CONN_COMPLETE:
+				hci_event(buf);
+				return 0;
+			default:
+				break;
+			}
+		}
```

### PR DESCRIPTION
**Pull request by joerchan**
Fix issue is host handling of connected and disconnected event.
Since the host wants the disconnected event to be processed as a
priority event as well as in reguler event context while the connected
event is always in reguler event context we can end up in a situation
where the disconnected priority event is processed before the connected
event.

Since the disconnected priority event is there to release unack'ed TX
pending on the connection in case the RX thread is blocked waiting
for TX resources, we need to keep this behavior. Otherwise this would
be a potential deadlock of the RX thread waiting for resources that can
only be released by the RX thread.
When this situation happens we know that there cannot be any pending TX
on this connection so we can safely skip releasing of unack'ed TX.

The second thing the disconnected priority event does is marking the TX
path on the connection as disconnected. We need to do the same in this
situation, so we make sure that the TX path is already marked
disconnected when providing the connected callback to the application.

This fixes a regression from 4be66bd33dec1edc82d35270c718f81443c42e8a.

Fixes: #32742

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -671,6 +671,33 @@ int bt_hci_disconnect(uint16_t handle, uint8_t reason)
...
+		}
+	}
+}
+
+static bool conn_handle_is_disconnected(uint16_t handle)
+{
+	/* Set one bit so that 0 can be used as a valid handle, only 12 bits
+	 * is used for valid handles.
+	 */
+	handle |= 0x8000;
```
Comment (Thalley) [inline subsys/bluetooth/host/hci_core.c:689]: Suggest to create a macro for this specific bit (or even setting all the top 4 bits), to avoid the "magic bit" case :D

**Review by Thalley — CHANGES_REQUESTED** [review]
I'm curious about the issue that is being fixed here: 

> Fix disconnect priority event given to the host before the connection complete event.

Is it really legal for a controller to send a disconnect event before a connection complete event? Or is this issue based on some other handling in the host? 

This commit feels like a workaround for something that shouldn't happen, so I'd appreciate if the issue could be further explained.

File: subsys/bluetooth/host/hci_core.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c]: @Thalley I've updated the description of the commit and the PR to better explain the problem and the fix.
It's not something the controller does, but a host handling of the events, that leads to the situation.

While the fix may not look particularly pretty it was the best I could come up with in the current design while keeping the same deadlock releasing behavior.

Also added a macro for valid bits as suggested.

Comment (Thalley) [reply subsys/bluetooth/host/hci_core.c]: Thanks - The commit message is very clear now :)

**Review by Thalley — APPROVED** [review]
LGTM

**Comment by jhedberg** [comment]
My initial thought was that it might have made sense to move part or all of the connected event handling into the priority context, but I assume that was considered and this other approach chosen as the more feasible & reasonable one?

**Comment by joerchan** [comment]
> My initial thought was that it might have made sense to move part or all of the connected event handling into the priority context, but I assume that was considered and this other approach chosen as the more feasible & reasonable one?

I did consider that, but it was further complicated by the advertising set terminated event handling with multiple advertisers, so it became a much more complicated solution than this.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@jhedberg please approve and merge if you are happy with Joakim's comment.

**Review by jhedberg — APPROVED** [review]

**Comment by Thalley** [comment]
@joerchan @jhedberg if the solution implemented here is subpar compared what you'd consider ideal, may I suggest to create a Github issue for a more long-term "proper" solution?

**Comment by joerchan** [comment]
@Thalley No, I don't consider it sub-par. This fix seemed like the best way to handle it.
