### PR TITLE
drivers: ethernet: stm32: fix multicast filter configuration

### LINKED ISSUE #54253: v3.3.0-rc1: stm32: IPv6 neighbour solicitation packets are not received without CONFIG_ETH_STM32_MULTICAST_FILTER
**Describe the bug**
With v3.3.0-rc1, zephyr no longer receives neighbour solicitation packets (destination MAC `33:33:ff:xx:yy:zz`) from stm32 ethernet MACs. With `CONFIG_ETH_STM32_MULTICAST_FILTER=y`, which I would expect to make multicast reception *more* restrictive, the packets are received again and neighbour discovery works as expected.

**To Reproduce**
Unfortunately not very clean, sorry about that, but I think it should be reproducible with any STM32 board with ethernet:
1. Build with:
   ```
   CONFIG_NETWORKING=y
   CONFIG_NET_L2_ETHERNET=y
   CONFIG_ETH_STM32_MULTICAST_FILTER=n
   ```
2. From an attached (linux) device, ping the zephyr device's (link-local) IPv6 address
4. In packet dumps, observe that the neighbour solicitations go unanswered
5. Build with `CONFIG_ETH_STM32_MULTICAST_FILTER=y`
6. Try again, neighbour discovery works

**Expected behavior**
IPv6 neighbour discovery works as expected even without the multicast filter enabled.

**Impact**
This effectively breaks IPv6 connectivity by default for stm32 based devices.

**Logs and console output**
N/A

**Environment**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: v3.3.0-rc1 (e9a59518fc)

**Additional context**
This is a pre-release, so maybe this is expected behaviour and just not documented in the changelog yet.

cc #53850/@cperera-aud

### PR DESCRIPTION
**Pull request by arbrauns**
With `CONFIG_ETH_STM32_MULTICAST_FILTER=n`, `MACFFR` was being set to 0 instead of `ETH_MULTICASTFRAMESFILTER_NONE`, blocking all multicast traffic.

Instead, reset all the relevant bits first, then set either `ETH_MULTICASTFRAMESFILTER_HASHTABLE` or `ETH_MULTICASTFRAMESFILTER_NONE` depending on Kconfig.

Fixes #54253.

cc @erwango

### CODE REVIEW

**Comment by arbrauns** [comment]
`git diff a5f9fc2~2 a5f9fc2` (the total diff of #53850) shows what happened here - the `tmp |= ETH_MULTICASTFRAMESFILTER_NONE;` line was removed completely instead of being gated by `!defined(CONFIG_ETH_STM32_MULTICAST_FILTER)`.

File: drivers/ethernet/eth_stm32_hal.c [hunk 1]
```diff
@@ -256,14 +256,16 @@ static inline void setup_mac_filter(ETH_HandleTypeDef *heth)
...
+		 ETH_MULTICASTFRAMESFILTER_PERFECT |
+		 ETH_MULTICASTFRAMESFILTER_NONE);
 
 #if defined(CONFIG_ETH_STM32_MULTICAST_FILTER)
 	/* enable multicast hash receive filter */
 	tmp |= ETH_MULTICASTFRAMESFILTER_HASHTABLE;
+#else
+	/* enable receiving all multicast frames */
+	tmp |= ETH_MULTICASTFRAMESFILTER_NONE;
 #endif /* CONFIG_ETH_STM32_MULTICAST_FILTER */
```
Comment (erwango) [inline drivers/ethernet/eth_stm32_hal.c:269]: For readability, consider use of `IS_ENABLED`.

```suggestion
	if (IS_ENABLED(CONFIG_ETH_STM32_MULTICAST_FILTER)) {
		/* enable multicast hash receive filter */
		tmp |= ETH_MULTICASTFRAMESFILTER_HASHTABLE;
	} else {
		/* enable receiving all multicast frames */
		tmp |= ETH_MULTICASTFRAMESFILTER_NONE;
	}
```

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/ethernet/eth_stm32_hal.c (hunk 1 above)
Comment (arbrauns) [reply drivers/ethernet/eth_stm32_hal.c]: Done, thanks!

File: drivers/ethernet/eth_stm32_hal.c [hunk 2]
```diff
@@ -256,15 +256,17 @@ static inline void setup_mac_filter(ETH_HandleTypeDef *heth)
 
 	/* disable multicast perfect filtering */
 	tmp &= ~(ETH_MULTICASTFRAMESFILTER_PERFECTHASHTABLE |
-#if !defined(CONFIG_ETH_STM32_MULTICAST_FILTER)
 		 ETH_MULTICASTFRAMESFILTER_HASHTABLE |
-#endif /* CONFIG_ETH_STM32_MULTICAST_FILTER */
-		 ETH_MULTICASTFRAMESFILTER_PERFECT);
+		 ETH_MULTICASTFRAMESFILTER_PERFECT |
+		 ETH_MULTICASTFRAMESFILTER_NONE);
```
Comment (erwango) [inline drivers/ethernet/eth_stm32_hal.c:261]: Nitpick:
IIUC, This fully resets the filtering bits configuration bits, leaving the state to 0, which matches "perfect filtering" definition.
If I'm correct, it would be nice to fix the comment as well, which is misleading.

Comment (arbrauns) [reply drivers/ethernet/eth_stm32_hal.c]: Oh yeah that comment isn't great, better now?

Comment (erwango) [reply drivers/ethernet/eth_stm32_hal.c]: From my understanding, it's more accurate now. Thanks

**Review by erwango — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
