### PR TITLE
drivers: spi:  RPi Pico PIO SPI code size and byte order.

### LINKED ISSUE #72954: drivers: spi: spi_rpi_pico_pio: Byte order is incorrect
**Describe the bug**
The PIO-based SPI driver for the Raspberry Pi Pico (and the RP2040 in general) sends data out the SPI bus in the wrong byte order when SPI_WORD_SET() is 16 or 32 bits, and reverses the byte order of the input data.  Data is passed to the SPI driver (tx buffer) in the byte order intended for transmission.  However, the little-endian PIO SPI driver treats the data as 16- or 32-bit integers, loading the data into the transmit FIFO in the reverse of the correct order and not correcting the reversed data in the receive FIFO.

 - Target platform:  Raspberry Pi Pico, Pico W  (Probably affects other RP2040 platforms as well.)
 - Work-around:  Modify calling code to re-order data (generally impractical, in my opinion).
 - Not a regression, bug in original code.

**To Reproduce**
1. The only readily available device that supports SPI_WORD_SET(32) in Zephyr is the TI TMAG5170 sensor.
2. Wire the TMAG5170 to the Raspberry Pi Pico (see "Additional context" for configuration).
3. Build samples/sensor/magn_polling, adding the boards/rpi_pico.overlay provided below, with the command `west build -p auto -b rpi_pico`
4. While monitoring the SPI bus, run the generated sample.

**Observed behavior**
The command to read the TEST_CONFIG register should be 0x8F000008, but is sent on the bus as 0x08 0x00 0x00 0x8F.  The input line receives 0xE0 0x00 0x00 0x8B, but the status message delivered to the application is 0x8B0000E0.  The TMAG5170 driver repeats the attempt to read the TEST_CONFIG register, never leaving the driver's init function.

**Expected behavior**
The data should be transmitted in the order provided, regardless of the CPU byte order:  0x8F 0x00 0x00 0x08, and the received data should be placed in the rx buffer in the order expected:  0xE0 0x00 0x00 0x8B.

**Impact**
The PIO SPI driver cannot operate correctly in either SPI_WORD_SET(16) or SPI_WORD_SET(32) configurations.

**Logs and console output**
Data as exchanged on the SPI bus (first two 32-bit exchanges):
```
Time [s],Packet ID,MOSI,MISO
0.0000392500,0,0x08,0xE0
0.0000472500,0,0x00,0x00
0.0000552500,0,0x00,0x00
0.0000632500,0,0x8F,0x8B
0.0000892500,0,0x08,0xE0
0.0000972500,0,0x00,0x00
0.0001052500,0,0x00,0x00
0.0001132500,0,0x8F,0x8B
```

**Environment (please complete the following information):**
 - OS:  Linux (Ubuntu 22.04.4 LTS)
 - Toolchain:  Zephyr SDK
 - Commit SHA:  5409c7c13041f4ed4fed0f212c4125f1e52aeca8

**Additional context**
boards/rpi_pico.overlay used to build sample:
```
/ {
	aliases {
		magn0 = &tmag5170;
	};
};

&pinctrl {
	pio0_spi0_default: pio0_spi0_default {
		/* gpio 9 is used for chip select, not assigned to the PIO */
		group1 {
			pinmux = <PIO0_P10>, <PIO0_P11>;
		};
		group2 {
			pinmux = <PIO0_P8>;
			input-enable;
		};
	};

};

&pio0 {
 	status = "okay";

	pio0_spi0: pio0_spi0 {
		pinctrl-0 = <&pio0_spi0_default>;
		pinctrl-names = "default";

		compatible = "raspberrypi,pico-spi-pio";
		status = "okay";
		#address-cells = <1>;
		#size-cells = <0>;
		clocks = <&clocks RPI_PICO_CLKID_CLK_SYS>;
		miso-gpios = <&gpio0 8 0>;
		cs-gpios = <&gpio0 9 GPIO_ACTIVE_LOW>;
		clk-gpios = <&gpio0 10 GPIO_ACTIVE_HIGH>;
		mosi-gpios = <&gpio0 11 GPIO_ACTIVE_HIGH>;
		tmag5170: tmag5170@0 {
			compatible = "ti,tmag5170";
			reg = <0>;
			operating-mode = <3>;
			spi-max-frequency = <1000000>; /* conservatively set to 1MHz */
		};
	};
};
```
TMAG5170 connections to RPI Pico:
 - CS to GPIO 9
 - CLK to GPIO 10
 - MOSI to GPIO 11
 - MISO to GPIO 8

### PR DESCRIPTION
**Pull request by ThreeEights**
Use minimized PIO code for 3-wire operation.

Input and output buffers are conventionally stored in bus byte order. For 16 and 32 bit transfers, this is effectively big-endian, so txbuf and rxbuf need to be read as such.  Those pointers also need to be declared uint8_t * instead of void *.
In addition, tx_count and rx_count are based on dts, and refer to whole transfers (8, 16, or 32 bits), not bytes.

Added rpi_pico.overlay to samples/sensor/magn_polling to demonstrate 32-bit word size, and updated the README.rst to make it independent of the specific sensor.

Fixes #72954

### CODE REVIEW

**Comment by ThreeEights** [comment]
Drat and darn:  Testing revealed a timing issue in 3-wire/SIO mode.  Previously, the TX logic could count on PIO instruction address being at the stalled pull instruction after the FIFO is empty, but that's not true with the refactored PIO code.  Due to the asynchronous nature of the PIO vs the CPU clocks, the test would sometimes fail and the RX logic would reset the state machine before the TX had completed.  The fix is to wait until the TX FIFO is empty, then sleep the number of clock ticks necessary to shift out all the data before starting the RX stage.

**Comment by ThreeEights** [comment]
@yonsch @soburi - When you have a chance, could you take a look at this pull request?  I'd like to ferret out any issues as soon as we can.

**Review by soburi — DISMISSED** [review]

**Comment by ThreeEights** [comment]
This fix is also needed for the next maintenance release of 3.7.

**Review by MaureenHelm — COMMENTED** [review]
Sensor changes are ok, but would like @yonsch to review the RPi SPI driver changes.

**Comment by soburi** [comment]
@yonsch 
Could you take a look?

File: drivers/spi/spi_rpi_pico_pio.c [hunk 1]
```diff
@@ -651,6 +572,8 @@ static void spi_pico_pio_txrx_3_wire(const struct device *dev)
 		}
 	}
 
+	k_sleep(K_TICKS(data->tx_period_ticks));
```
Comment (yonsch) [inline drivers/spi/spi_rpi_pico_pio.c:575]: Why is this needed?

Comment (ThreeEights) [reply drivers/spi/spi_rpi_pico_pio.c:575]: After the FIFO is drained and the state machine completes sending, the peripherals I was testing with (a BME280 and a TI TMAG5170 magnetometer) weren't getting the last bit.  The logic analyzer trace showed the GPIO line was changing state before that last bit was latched.  One more SPI clock period was needed before resetting the GPIO line for read mode.

Can you see a better place to insert that delay?

**Comment by ThreeEights** [comment]
@yonsch - Do you have any further comments on this pull request?

**Comment by soburi** [comment]
@yonsch 
ping

File: drivers/spi/spi_rpi_pico_pio.c (hunk 1 above)
Comment (yonsch) [reply drivers/spi/spi_rpi_pico_pio.c:575]: I'm just always suspicious of delays in driver code. Ideally the exact timings of the GPIO line should be handled by the PIO, and the CPU should just wait for the PIO to finish (I'm also doubtful that the tick resolution is high enough to actually produce a delay of the correct length).
That said, if you insist that this delay is necessary, please just add a short comment in the code explaining why the delay is needed - in a hypothetical future where we'll be debugging the timing of this code, finding this undocumented delay would be an unpleasant surprise :)

**Comment by MaureenHelm** [comment]
> @MaureenHelm @yonsch - This also needs the backport v3.6-branch label. (Am I allowed to add labels?)

Added.

**Comment by ThreeEights** [comment]
@yonsch - Please take a look when you get a chance and see if the changes to drivers/spi/spi_rpi_pico_pio.c meet your approval.  I took another look at the problem and redid the wait loop between the send and receive in 3-wire mode.
For those trying to follow along:  The issue is that the CPU has no way of knowing when the PIO's state machine has finished clocking out the sent data.  Since the SPI clock is typically running at a slower speed than the CPU (and thus PIO) clocks, some delay is needed to prevent the CPU from disabling the state machine (in order to switch to receive state) before the SPI clock is finished.  My solution was to include a delay of approximately one SPI clock cycle, to allow the state machine to complete before being reset.

**Comment by ThreeEights** [comment]
@MaureenHelm @soburi - I had to rebase my changes onto the tip of the main branch for the mainline code.  There's one update to samples/sensor/magn_polling/README.rst to fix a merge conflict, and the redone synchronization loop in drivers/spi/spi_rpi_pico_pio.c.  Can you please review my changes when you have an opportunity?

File: drivers/spi/spi_rpi_pico_pio.c [hunk 2]
```diff
@@ -622,33 +545,33 @@ static void spi_pico_pio_txrx_3_wire(const struct device *dev)
...
 				}
+				data->tx_count++;
 			}
 		}
-		while ((!pio_sm_is_tx_fifo_empty(data->pio, data->pio_sm)) ||
-		       (!spi_pico_pio_sm_complete(data))) {
+		/* Wait for the state machine to complete the cycle */
+		/* before resetting the PIO for reading.            */
+		do {
 			k_sleep(K_TICKS(data->tx_period_ticks));
```
Comment (yonsch) [inline drivers/spi/spi_rpi_pico_pio.c:572]: Looking at other drivers it seems that waiting on a bit without sleeping between iterations is legitimate. If any higher priority task needs to run it will get its runtime.

**Review by yonsch — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_rpi_pico_pio.c (hunk 2 above)
Comment (ThreeEights) [reply drivers/spi/spi_rpi_pico_pio.c:572]: I'm sorry, but I'm not following you.  Are you suggesting using a timer instead of k_sleep()?  Or perhaps I didn't explain the problem clearly:  Even after the last word has been shifted from the FIFO, clocked out by the PIO program, and the PIO program counter has returned to the starting point, a delay is still needed to allow the SPI bus signals to complete before the CPU can reset the PIO state machine to start the receive cycle.  I can't think of any way for the CPU to detect the state of the SPI bus, which is why I added the delay here.

I did try to minimize the needed delay, though perhaps waiting the full word size is excessive.  I'll test this with just one SPI clock cycle and see if that's enough.

Comment (ThreeEights) [reply drivers/spi/spi_rpi_pico_pio.c:572]: Only one SPI bit time is needed;  I tested it at both the fast end and the slow end of the BME280 clock range.  (The issue is more of a problem at slow SPI clock rates.)

**Comment by ThreeEights** [comment]
@yonsch - Have you had a chance to look at this again?

File: drivers/spi/spi_rpi_pico_pio.c (hunk 2 above)
Comment (yonsch) [reply drivers/spi/spi_rpi_pico_pio.c:572]: @ThreeEights what worries me is that putting delays in drivers may impact throughput. I once debugged a slow UART interface just to discover there was a similar delay adding a few milliseconds between each buffer sent.
Although throughput might not be a big issue here, I still think it's best not to have delays in driver code. The kernel's delay resolution is in ticks, and a tick is usually 1 or 0.5 ms. Since SPI works in the MHz range, the needed delay for one bit is in the microseconds range. My suggestion is to busy wait that delay instead of sleeping through it:
```
while ((!pio_sm_is_tx_fifo_empty(data->pio, data->pio_sm)) ||
			 (!spi_pico_pio_sm_complete(data)));
```

Comment (ThreeEights) [reply drivers/spi/spi_rpi_pico_pio.c:572]: @yonsch - I agree with everything you're saying here, but it's obvious I have not yet communicated what, exactly, is the problem.  The wait loop you show is the original code I had, with no sleep delay, which fails:
* The TX FIFO will be empty when the last data is transferred to the output shift register, before any bits have been sent.  The call to pio_sm_is_tx_fifo_empty() just ensures that all the queued data has been passed to the state machine.
* spi_pico_pio_sm_complete() compares the state machine's PC with the start address of the send program.  That tells the CPU that the SM has returned to the starting point, but the last clock transition has not yet propagated over the CLK line.
* When this loop completes, the next step is resetting the state machine to turn the data line around for receiving the response.
If the state machine is reset before the clock transition finishes, the data and clock lines are now out of sync and the next few exchanges are garbage.  I see this issue showing up with a BME280 sensor and an external CYW4343W WiFi module as well as the CYW43439 on the Pico W.
I'm open to suggestions for alternatives, but I've been unable to figure out any way for the CPU to detect that the clock signal has propagated to the peripheral.  Absent any other solution, I think the k_sleep() call in this case is justified:
* This only applies when running in 3-wire mode.
* The delay takes place after all the send data in this SPI transaction has been transmitted.
* For the RPI Pico and Pico W, CONFIG_SYS_CLOCK_TICKS_PER_SEC is 10000, which implies a tick time of 0.1 msec.
* For most of the SPI clock speed range, waiting for one "one bit time" amounts to 1 tick, or 100 microseconds.
Again, if you can think of any other way to let the SM finish without inserting this k_sleep(), please let me know.

Comment (yonsch) [reply drivers/spi/spi_rpi_pico_pio.c:572]: Okay, this satisfies me, so I'll let @soburi decide

Comment (ThreeEights) [reply drivers/spi/spi_rpi_pico_pio.c]: @yonsch @soburi This is a bit embarrassing, but it turns out I can move the necessary delay into the PIO program and remove the k_sleep() completely.  Once I can get all the compliance checks to pass, this should be a much cleaner solution.
Taking out the k_sleep(), the delay between the Send and Receive stages goes from an average of 265 microseconds to 170, with some cycles being substantially faster.

Comment (ThreeEights) [reply drivers/spi/spi_rpi_pico_pio.c]: @yonsch @soburi - Finally cleared up all the compliance and infrastructure update issues.  Can you please take another look at the revised code?

**Review by tbursztyka — APPROVED** [review]

**Review by soburi — APPROVED** [review]
Sorry for the late response.
I was busy preparing to speak at the open-source summit in Japan.

LGTM

**Review by yonsch — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
