### PR TITLE
tests: ztest: Fix issues due to test case of accessing NULL address

### LINKED ISSUE #31339: nsim_em: running tests/ztest/error_hook/ failed
To Reproduce
twister -p nsim_em -T tests/ztest/error_hook/
see error

*** Booting Zephyr OS build zephyr-v2.4.0-3009-gfc1b5de4c307  ***^M
Running test suite error_hook_tests^M

===================================================================^M
START - test_catch_assert_fail^M
ASSERTION FAIL [a != ((void *)0)] @ WEST_TOPDIR/zephyr/tests/ztest/error_hook/src/main.c:41^M
        parameter a should not be NULL!^M
Caught assert failed^M
Assert error expected as part of test case.^M
 PASS - test_catch_assert_fail^M

===================================================================^M
**START - test_catch_fatal_error^M
case type is 0^M
b is 11588^M
 FAIL - test_catch_fatal_error^M**

===================================================================^M
START - test_catch_assert_in_isr^M
ASSERTION FAIL [a != ((void *)0)] @ WEST_TOPDIR/zephyr/tests/ztest/error_hook/src/main.c:41^M
        parameter a should not be NULL!^M
Caught assert failed^M
Assert error expected as part of test case.^M
 PASS - test_catch_assert_in_isr^M

Environment (please complete the following information):

OS: Fedora33
Toolchain: zephyr-sdk-0.12.0
Commit ID: fc1b5de

### LINKED ISSUE #31419: tests/ztest/error_hook failed on ARC boards
**Describe the bug**
tests/ztest/error_hook failed on ARC boards

**To Reproduce**
1. west build -b nsim_em -d build tests/ztest/error_hook
2. west flash 
3. See error

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.4.0-3232-gf0145f9f3e37  ***
Running test suite error_hook_tests
===================================================================
START - test_catch_assert_fail
ASSERTION FAIL [a != ((void *)0)] @ WEST_TOPDIR/zephyr/tests/ztest/error_hook/src/main.c:41
        parameter a should not be NULL!
Caught assert failed
Assert error expected as part of test case.
 PASS - test_catch_assert_fail
===================================================================
START - test_catch_fatal_error
case type is 0
b is 11588
 FAIL - test_catch_fatal_error
===================================================================
START - test_catch_assert_in_isr
ASSERTION FAIL [a != ((void *)0)] @ WEST_TOPDIR/zephyr/tests/ztest/error_hook/src/main.c:41
        parameter a should not be NULL!
Caught assert failed
Assert error expected as part of test case.
 PASS - test_catch_assert_in_isr
===================================================================
START - test_catch_z_oops
E: ***** Exception vector: 0x6, cause code: 0x1, parameter 0x4
E: Address 0x80000af4
E: EV_ProtV
E: Memory read protection violation (MPU)
E:  r0: 0x80000aec  r1: 0x00000000  r2: 0x00000000  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x0000011d  r7: 0x00000000
E:  r8: 0x00000000  r9: 0x00000000 r10: 0x00000000 r11: 0x00000000
E: r12: 0x000037c0 r13: 0x8000003c  pc: 0x00000304
E:  blink: 0x000002f4 status32: 0x80184086
E: lp_end: 0x00000000 lp_start: 0x00000000 lp_count: 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x800008e4 (unknown)
Caught system error -- reason 0 1
Fatal error expected as part of test case.
 PASS - test_catch_z_oops
===================================================================
Test suite error_hook_tests failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (Zephyr SDK)
 - zephyr-v2.4.0-3232-gf0145f9f3e37

### PR DESCRIPTION
**Pull request by enjiamai**
Fix issue #31339 and #31419, test case fail due to access NULL did not
trigger a fatal error in some platform such as nsim_em and iotdk.

Fixes #31339 
Fixes #31419

Signed-off-by: Enjia Mai <enjiax.mai@intel.com>

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Comment by nashif** [comment]
the coverity issue seems to be a false positive, you are intentionally dereferencing a null pointer to cause a crash, which is fine, so just close it as false-positive/intentional.

**Comment by ruuddw** [comment]
Thanks, 0xffff_ffff fails on nsim_em. It still is a hardcoded value that might not fail on other platforms - @IRISZZW could you check if  other ARC boards also trigger an exception on reads to 0xffff_ffff?
Alternatively, you could try writing to the instruction space when MPU protects the code.
	void *a = (void *)&test_main;
	*(int *)a = 0xbad00bad;

**Comment by enjiamai** [comment]
> the coverity issue seems to be a false positive, you are intentionally dereferencing a null pointer to cause a crash, which is fine, so just close it as false-positive/intentional.

Hi, @nashif , beside coverity scan issue, this also aim to fix another problem, in some ARC platform such as nsim-em and iotdk board,  which dereferencing a null pointer won't trigger an fatal error. 

So should I close this coverity issue#31674 without fix it, and keep testing dereferencing a null pointer except the board which won't trigger fatal error?

**Comment by enjiamai** [comment]
> Thanks, 0xffff_ffff fails on nsim_em. It still is a hardcoded value that might not fail on other platforms - @IRISZZW could you check if other ARC boards also trigger an exception on reads to 0xffff_ffff?
> Alternatively, you could try writing to the instruction space when MPU protects the code.
> void *a = (void *)&test_main;
> *(int *)a = 0xbad00bad;

Hi @ruuddw, thanks, you suggestion is really a good idea, and the code looks better than hard code it. It works for almost the boards include nsim_em, but not work for iotdk.  As far as I tested 0xFFFF_FFFF works for iotdk too. I also try to access kobject, but not work for all boards. How do you think separating different tests by #if-else for this case?

**Comment by ruuddw** [comment]
Great, didn't realize you tested on other ARC boards already.
There's always exceptions: I forgot that the default configuration on iotdk is using the large PSRAM memory on it for both instructions and data. And, by default it protect ICCM as read-only, executable memory, but the full PSRAM as executable + R/W.
No need to create add an #if in your test for this -> it is something that should be repaired in the iotdk MPU setup (arc_mpu_regions.c): if PSRAM is used as instruction memory, the MPU should protect it...

**Comment by enjiamai** [comment]
> Great, didn't realize you tested on other ARC boards already.
> There's always exceptions: I forgot that the default configuration on iotdk is using the large PSRAM memory on it for both instructions and data. And, by default it protect ICCM as read-only, executable memory, but the full PSRAM as executable + R/W.
> No need to create add an #if in your test for this -> it is something that should be repaired in the iotdk MPU setup (arc_mpu_regions.c): if PSRAM is used as instruction memory, the MPU should protect it...

I really appreciate your suggestion and information for this, let me look into more detail then make it better, thank you!

File: tests/ztest/error_hook/src/main.c [hunk 1]
```diff
@@ -49,11 +49,11 @@ static void trigger_fault_illeagl_instuction(void)
...
 
-static void trigger_fault_access_null(void)
+static void trigger_fault_access(void)
 {
-	void *a = NULL;
+	void *a = (void *)0xFFFFFFFF;
 
-	/* access a null of address */
+	/* access a illeagal address */
 	int b = *((int *)a);
```
Comment (evgeniy-paltsev) [inline tests/ztest/error_hook/src/main.c:57]: We need to have volatile memory access here, otherwise it may be optimize out by compiler.

**Review by evgeniy-paltsev — DISMISSED** [review]

File: tests/ztest/error_hook/src/main.c (hunk 1 above)
Comment (enjiamai) [reply tests/ztest/error_hook/src/main.c]: Got it fixed, thanks very much for reviewing it and correcting on this.

**Comment by enjiamai** [comment]
For issue #31674, Coverity CID :216788, fix Null pointer dereferences,  our plan is not to fix it.
It is a false-positive/intentional test case code. Will close it with recording in coverity. @galak @nashif 
 
For nsim_em or iotdk test case failed issue, I suggest to access 0xffff_ffff to trigger an exception here to make test case pass at this moment.
And thanks very much for @ruuddw and @evgeniy-paltsev, I appreciate you know what's going on from you.
nsim_em => keep checking if it is possible with latest nSIM.
iotdk => maybe fix it in board config

**Review by ruuddw — APPROVED** [review]
Thanks, #if for the special case is probably the best solution for now.
We'll look into the iotdk MPU setup separately.

**Comment by evgeniy-paltsev** [comment]
@enjiamai I've launched testing on ARC platforms. I'll update about the results tomorrow.

**Comment by enjiamai** [comment]
> @enjiamai I've launched testing on ARC platforms. I'll update about the results tomorrow.

@evgeniy-paltsev Thanks you! Looking forward to your results on these boards.

**Comment by nashif** [comment]
@evgeniy-paltsev any updates?

**Comment by evgeniy-paltsev** [comment]
I've checked this change - now it works fine on ARC platforms, thanks.

**Comment by ruuddw** [comment]
Merge branch 'fix_coverity_explicit_deref_null' of https://github.com/enjiamai/zephyr into pr/enjiamai/31773
```diff
diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
index a0e3eef547..10e070173d 100644
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -4,7 +4,7 @@ steps:
     env:
       ZEPHYR_TOOLCHAIN_VARIANT: "zephyr"
       ZEPHYR_SDK_INSTALL_DIR: "/opt/sdk/zephyr-sdk-0.12.2"
-    parallelism: 40
+    parallelism: 20
     timeout_in_minutes: 180
     retry:
       manual: true
diff --git a/.github/workflows/twister_tests.yml b/.github/workflows/twister_tests.yml
index bbd3363892..19f747b043 100644
--- a/.github/workflows/twister_tests.yml
+++ b/.github/workflows/twister_tests.yml
@@ -1,7 +1,7 @@
 # Copyright (c) 2020 Intel Corporation.
 # SPDX-License-Identifier: Apache-2.0
 
-name: Twsiter TestSuite
+name: Twister TestSuite
 
 on:
   push:
diff --git a/arch/x86/core/intel64/locore.S b/arch/x86/core/intel64/locore.S
index f4e1ab8388..d715abfe9e 100644
--- a/arch/x86/core/intel64/locore.S
+++ b/arch/x86/core/intel64/locore.S
@@ -182,6 +182,15 @@ enter_code64:
 	movw %ax, %ss
 	movw %ax, %fs
 
+	/* On Intel processors, if GS is not zero and is being set to
+	 * zero, GS_BASE is also being set to zero. This would interfere
+	 * with the actual use of GS_BASE for usespace. To avoid accidentally
+	 * clearing GS_BASE, simply set GS to 0 at boot, so any subsequent
+	 * clearing of GS will not clear GS_BASE.
+	 */
+	mov $0, %eax
+	movw %ax, %gs
+
 	movw __x86_cpuboot_t_tr_OFFSET(%rbp), %ax
 	ltr %ax
 
diff --git a/boards/arm/nrf5340dk_nrf5340/CMakeLists.txt b/boards/arm/nrf5340dk_nrf5340/CMakeLists.txt
index 2b4a91df05..9f91d93271 100644
--- a/boards/arm/nrf5340dk_nrf5340/CMakeLists.txt
+++ b/boards/arm/nrf5340dk_nrf5340/CMakeLists.txt
@@ -97,7 +97,7 @@ if (CONFIG_BUILD_WITH_TFM)
 			COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_PROPERTY:tfm,BL2_BIN_FILE> ${CMAKE_BINARY_DIR}/mcuboot.bin
 
 			# Generate an intel hex file from the signed output binary
-			COMMAND srec_cat ${CMAKE_BINARY_DIR}/tfm_sign.bin
+			COMMAND ${SREC_CAT} ${CMAKE_BINARY_DIR}/tfm_sign.bin
 				-binary
 				-offset 0x10000
 				-o ${CMAKE_BINARY_DIR}/tfm_sign.hex
diff --git a/boards/arm/nrf9160dk_nrf9160/CMakeLists.txt b/boards/arm/nrf9160dk_nrf9160/CMakeLists.txt
index 018027ca6a..41598ef3f8 100644
--- a/boards/arm/nrf9160dk_nrf9160/CMakeLists.txt
+++ b/boards/arm/nrf9160dk_nrf9160/CMakeLists.txt
@@ -74,7 +74,7 @@ if (CONFIG_BUILD_WITH_TFM)
 		COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_PROPERTY:tfm,BL2_BIN_FILE> ${CMAKE_BINARY_DIR}/mcuboot.bin
 
 		# Generate an intel hex file from the signed output binary
-		COMMAND srec_cat ${CMAKE_BINARY_DIR}/tfm_sign.bin
+		COMMAND ${SREC_CAT} ${CMAKE_BINARY_DIR}/tfm_sign.bin
 		-binary
 		-offset 0x10000
 		-o ${CMAKE_BINARY_DIR}/tfm_sign.hex
diff --git a/boards/xtensa/intel_adsp_cavs15/tools/flash.sh b/boards/xtensa/intel_adsp_cavs15/tools/flash.sh
index 59becf2a8b..0eda1dc9d1 100755
--- a/boards/xtensa/intel_adsp_cavs15/tools/flash.sh
+++ b/boards/xtensa/intel_adsp_cavs15/tools/flash.sh
@@ -10,10 +10,10 @@ if [ -z "$2" ]
   then
     echo "Signing using default key"
     west sign -d ${BUILD} -t rimage
-else
+elif [ -n "$3" ] && [ -n "$4" ]
+  then
     echo "Signing with key " $key
-    west sign -d ${BUILD} -t rimage -- -k $2
+    west sign -d ${BUILD} -t rimage -p $4 -D $3 -- -k $2
 fi
-
 echo ${FLASHER} -f ${FIRMWARE}
 ${FLASHER} -f ${FIRMWARE} || /bin/true  2>&1
diff --git a/boards/xtensa/intel_adsp_cavs18/intel_adsp_cavs18_defconfig b/boards/xtensa/intel_adsp_cavs18/intel_adsp_cavs18_defconfig
index 943e7168dc..de2370e8d8 100644
--- a/boards/xtensa/intel_adsp_cavs18/intel_adsp_cavs18_defconfig
+++ b/boards/xtensa/intel_adsp_cavs18/intel_adsp_cavs18_defconfig
@@ -9,6 +9,7 @@ CONFIG_GEN_ISR_TABLES=y
 CONFIG_GEN_IRQ_VECTOR_TABLE=n
 
 CONFIG_XTENSA_RESET_VECTOR=y
+CONFIG_RESET_VECTOR_IN_BOOTLOADER=y
 
 CONFIG_XTENSA_USE_CORE_CRT1=y
 
diff --git a/boards/xtensa/intel_adsp_cavs20/intel_adsp_cavs20_defconfig b/boards/xtensa/intel_adsp_cavs20/intel_adsp_cavs20_defconfig
index e677f66de9..93544ff61f 100644
--- a/boards/xtensa/intel_adsp_cavs20/intel_adsp_cavs20_defconfig
+++ b/boards/xtensa/intel_adsp_cavs20/intel_adsp_cavs20_defconfig
@@ -9,6 +9,7 @@ CONFIG_GEN_ISR_TABLES=y
 CONFIG_GEN_IRQ_VECTOR_TABLE=n
 
 CONFIG_XTENSA_RESET_VECTOR=y
+CONFIG_RESET_VECTOR_IN_BOOTLOADER=y
 
 CONFIG_XTENSA_USE_CORE_CRT1=y
 
diff --git a/boards/xtensa/intel_adsp_cavs25/intel_adsp_cavs25_defconfig b/boards/xtensa/intel_adsp_cavs25/intel_adsp_cavs25_defconfig
index d762d26c31..df3bb38335 100644
--- a/boards/xtensa/intel_adsp_cavs25/intel_adsp_cavs25_defconfig
+++ b/boards/xtensa/intel_adsp_cavs25/intel_adsp_cavs25_defconfig
@@ -9,6 +9,7 @@ CONFIG_GEN_ISR_TABLES=y
 CONFIG_GEN_IRQ_VECTOR_TABLE=n
 
 CONFIG_XTENSA_RESET_VECTOR=y
+CONFIG_RESET_VECTOR_IN_BOOTLOADER=y
 
 CONFIG_XTENSA_USE_CORE_CRT1=y
 
diff --git a/doc/releases/release-notes-2.5.rst b/doc/releases/release-notes-2.5.rst
index 3255696a70..e776e3ea40 100644
--- a/doc/releases/release-notes-2.5.rst
+++ b/doc/releases/release-notes-2.5.rst
@@ -93,6 +93,40 @@ Deprecated in this release
 Removed APIs in this release
 ============================
 
+* Bluetooth
+
+  * The deprecated BT_LE_SCAN_FILTER_DUPLICATE define has been removed,
+    use BT_LE_SCAN_OPT_FILTER_DUPLICATE instead.
+  * The deprecated BT_LE_SCAN_FILTER_WHITELIST define has been removed,
+    use BT_LE_SCAN_OPT_FILTER_WHITELIST instead.
+  * The deprecated bt_le_scan_param::filter_dup argument has been removed,
+    use bt_le_scan_param::options instead.
+  * The deprecated bt_conn_create_le() function has been removed,
+    use bt_conn_le_create() instead.
+  * The deprecated bt_conn_create_auto_le() function has been removed,
+    use bt_conn_le_create_auto() instead.
+  * The deprecated bt_conn_create_slave_le() function has been removed,
+    use bt_le_adv_start() instead with bt_le_adv_param::peer set to the remote
+    peers address.
+  * The deprecated BT_LE_ADV_* macros have been removed,
+    use the BT_GAP_ADV_* enums instead.
+  * The deprecated bt_conn_security function has been removed,
+    use bt_conn_set_security instead.
+  * The deprecated BT_SECURITY_* defines NONE, LOW, MEDIUM, HIGH, FIPS have been
+    removed, use the L0, L1, L2, L3, L4 defines instead.
+  * The deprecated BT_HCI_ERR_AUTHENTICATION_FAIL define has been removed,
+    use BT_HCI_ERR_AUTH_FAIL instead.
+
+* Kernel
+
+  * The deprecated k_mem_pool API has been removed entirely (for the
+    past release it was backed by a k_heap, but maintained a
+    compatible API).  Now all instantiated heaps must be
+    sys_heap/k_heaps.  Note that the new-style heap is a general
+    purpose allocator and does not make the same promises about block
+    alignment/splitting.  Applications with such requirements should
+    look at porting their logic, or perhaps at the k_mem_slab utility.
+
 Stable API changes in this release
 ==================================
 
@@ -172,6 +206,26 @@ Drivers and Sensors
 
 * CAN
 
+  * We reworked the configuration API.
+    A user can now specify the timing manually (define prop segment,
+    phase segment1, phase segment2, and prescaler) or use a newly introduced
+    algorithm to calculate optimal timing values from a bitrate and sample point.
+    The bitrate and sample point can be specified in the device tree too.
+    It is possible to change the timing values at runtime now.
+
+  * We reworked the zcan_frame struct due to undefined behavior.
+    The std_id (11-bit) and ext_id (29-bit) are merged to a single id
+    field (29-bit). The union of both IDs was removed.
+
+  * We made the CANbus API CAN-FD compatible.
+    The zcan_frame data-field can have a size of >8 bytes now.
+    A flag was introduced to mark a zcan_frame as CAN-FD frame.
+    A flag was introduced that enables a bitrate switch in CAN-FD frames.
+    The configuration API supports an additional timing parameter for the CAN-FD
+    data-phase.
+
+  * drivers are converted to use the new DEVICE_DT_* macros.
+
 * Clock Control
 
 * Console
@@ -301,6 +355,9 @@ Build and Infrastructure
     should be using the new devicetree API introduced in Zephyr 2.3 and
     documented in :ref:`dt-from-c`. Information on flash partitions has moved
     to :ref:`flash_map_api`.
+  * It is now possible to resolve at build time the device pointer associated
+    with a device that is defined in devicetree, via ``DEVICE_DT_GET``.  See
+    :ref:`dt-get-device`.
 
 * West
 
diff --git a/drivers/adc/adc_stm32.c b/drivers/adc/adc_stm32.c
index 9fc96bd9c6..35731b3c0f 100644
--- a/drivers/adc/adc_stm32.c
+++ b/drivers/adc/adc_stm32.c
@@ -319,15 +319,15 @@ static int start_read(const struct device *dev,
 	}
 
 	uint32_t channels = sequence->channels;
-	if (channels > find_lsb_set(channels)) {
+	uint8_t index = find_lsb_set(channels) - 1;
+
+	if (channels > BIT(index)) {
 		LOG_ERR("Only single channel supported");
 		return -ENOTSUP;
 	}
 
 	data->buffer = sequence->buffer;
-	uint8_t index;
 
-	index = find_lsb_set(channels) - 1;
 	uint32_t channel = __LL_ADC_DECIMAL_NB_TO_CHANNEL(index);
 #if defined(CONFIG_SOC_SERIES_STM32H7X)
 	/*
diff --git a/drivers/can/can_mcux_flexcan.c b/drivers/can/can_mcux_flexcan.c
index ce06590571..a6f892b3ea 100644
--- a/drivers/can/can_mcux_flexcan.c
+++ b/drivers/can/can_mcux_flexcan.c
@@ -35,6 +35,14 @@ LOG_MODULE_REGISTER(can_mcux_flexcan);
 #error You must either set a sampling-point or timings (phase-seg* and prop-seg)
 #endif
 
+#if ((defined(FSL_FEATURE_FLEXCAN_HAS_ERRATA_5641) && FSL_FEATURE_FLEXCAN_HAS_ERRATA_5641) || \
+	(defined(FSL_FEATURE_FLEXCAN_HAS_ERRATA_5829) && FSL_FEATURE_FLEXCAN_HAS_ERRATA_5829))
+/* the first valid MB should be occupied by ERRATA 5461 or 5829. */
+#define RX_START_IDX 1
+#else
+#define RX_START_IDX 0
+#endif
+
 /*
  * RX message buffers (filters) will take up the first N message
  * buffers. The rest are available for TX use.
@@ -165,6 +173,7 @@ static int mcux_flexcan_set_mode(const struct device *dev, enum can_mode mode)
 	}
 
 	FLEXCAN_GetDefaultConfig(&flexcan_config);
+	flexcan_config.maxMbNum = FSL_FEATURE_FLEXCAN_HAS_MESSAGE_BUFFER_MAX_NUMBERn(0);
 	flexcan_config.clkSrc = config->clk_source;
 	flexcan_config.baudRate = clock_freq /
 	      (1U + data->timing.prop_seg + data->timing.phase_seg1 +
@@ -370,7 +379,7 @@ static int mcux_flexcan_attach_isr(const struct device *dev,
 	k_mutex_lock(&data->rx_mutex, K_FOREVER);
 
 	/* Find and allocate RX message buffer */
-	for (i = 0; i < MCUX_FLEXCAN_MAX_RX; i++) {
+	for (i = RX_START_IDX; i < MCUX_FLEXCAN_MAX_RX; i++) {
 		if (!atomic_test_and_set_bit(data->rx_allocs, i)) {
 			alloc = i;
 			break;
diff --git a/drivers/clock_control/Kconfig.stm32l4_l5_wb b/drivers/clock_control/Kconfig.stm32l4_l5_wb
index 183598559b..de37ea073f 100644
--- a/drivers/clock_control/Kconfig.stm32l4_l5_wb
+++ b/drivers/clock_control/Kconfig.stm32l4_l5_wb
@@ -9,27 +9,37 @@ config CLOCK_STM32_PLL_M_DIVISOR
 	int "PLL divisor"
 	depends on CLOCK_STM32_SYSCLK_SRC_PLL
 	default 1
-	range 1 8
+	range 1 8 if SOC_SERIES_STM32L4X || SOC_SERIES_STM32WBX
+	range 1 16 if SOC_SERIES_STM32L5X
 	help
-	  PLL divisor, allowed values: 1-8. With this ensure that the PLL
-	  VCO input frequency ranges from 4 to 16MHz.
+	  PLL divisor,
+	  L4: allowed values: 1-8. PLL VCO input ranges from 4 to 16MHz
+	  L5: allowed values: 1-16. PLL VCO input ranges from 4 to 16MHz
+	  WB: allowed values: 1-8. PLL VCO input ranges from 2.66 to 16MHz
 
 config CLOCK_STM32_PLL_N_MULTIPLIER
 	int "PLL multiplier"
 	depends on CLOCK_STM32_SYSCLK_SRC_PLL
 	default 20
-	range 8 86
+	range 8 86 if SOC_SERIES_STM32L4X || SOC_SERIES_STM32L5X
+	range 6 127 if SOC_SERIES_STM32WBX
 	help
-	  PLL multiplier, allowed values: 2-16. PLL output must not
-	  exceed 344MHz.
+	  PLL multiplier,
+	  L4: allowed values: 8-86. PLL VCO output ranges from 64 to 334MHz
+	  L5: allowed values: 8-86. PLL VCO output ranges from 64 to 334MHz
+	  WB: allowed values: 6-127. PLL VCO output ranges from 96 to 334MHz
 
 config CLOCK_STM32_PLL_P_DIVISOR
 	int "PLL P Divisor"
 	depends on CLOCK_STM32_SYSCLK_SRC_PLL
 	default 7
-	range 0 17
+	range 0 17 if SOC_SERIES_STM32L4X || SOC_SERIES_STM32L5X
+	range 0 32 if SOC_SERIES_STM32WBX
 	help
-	  PLL P Output divisor, allowed values: 0, 7, 17.
+	  PLL P Output divisor
+	  L4: allowed values: 0, 7, 17. PLLP do not exceed 80MHz
+	  L5: allowed values: 0, 7, 17. PLLP do not exceed 80MHz
+	  WB: allowed values: 0, 2-32. PLLP do not exceed 64MHz
 
 config CLOCK_STM32_PLL_Q_DIVISOR
 	int "PLL Q Divisor"
@@ -37,7 +47,10 @@ config CLOCK_STM32_PLL_Q_DIVISOR
 	default 2
 	range 0 8
 	help
-	  PLL Q Output divisor, allowed values: 0, 2, 4, 6, 8.
+	  PLL Q Output divisor
+	  L4: allowed values: 0, 2, 4, 6, 8. PLLQ do not exceed 80MHz
+	  L5: allowed values: 0, 2, 4, 6, 8. PLLQ do not exceed 80MHz
+	  WB: allowed values: 0, 2-8. PLLQ do not exceed 64MHz
 
 config CLOCK_STM32_PLL_R_DIVISOR
 	int "PLL R Divisor"
@@ -45,7 +58,10 @@ config CLOCK_STM32_PLL_R_DIVISOR
 	default 4
 	range 0 8
 	help
-	  PLL R Output divisor, allowed values: 0, 2, 4, 6, 8.
+	  PLL R Output divisor
+	  L4: allowed values: 0, 2, 4, 6, 8. PLLR do not exceed 80MHz
+	  L5: allowed values: 0, 2, 4, 6, 8. PLLR do not exceed 110MHz
+	  WB: allowed values: 0, 2-8. PLLR do not exceed 64MHz
 
 config CLOCK_STM32_LSE
 	bool "Low-speed external clock"
diff --git a/drivers/espi/host_subs_npcx.c b/drivers/espi/host_subs_npcx.c
index 63d96fb336..875e5b3295 100644
--- a/drivers/espi/host_subs_npcx.c
+++ b/drivers/espi/host_subs_npcx.c
@@ -235,9 +235,8 @@ static void host_kbc_ibf_isr(void *arg)
 	 * The high byte contains information from the host, and the lower byte
 	 * indicates if the host sent a command or data. 1 = Command.
 	 */
-	evt.evt_data = (inst_kbc->HIKMDI << NPCX_8042_DATA_POS) |
-		       (IS_BIT_SET(inst_kbc->HIKMST, NPCX_HIKMST_A2) <<
-				       NPCX_8042_TYPE_POS);
+	evt.evt_data = NPCX_8042_EVT_DATA(NPCX_8042_EVT_IBF, inst_kbc->HIKMDI,
+			IS_BIT_SET(inst_kbc->HIKMST, NPCX_HIKMST_A2));
 
 	LOG_DBG("%s: kbc data 0x%02x", __func__, evt.evt_data);
 	espi_send_callbacks(host_sub_data.callbacks, host_sub_data.host_bus_dev,
@@ -248,6 +247,9 @@ static void host_kbc_obe_isr(void *arg)
 {
 	ARG_UNUSED(arg);
 	struct kbc_reg *const inst_kbc = host_sub_cfg.inst_kbc;
+	struct espi_event evt = { ESPI_BUS_PERIPHERAL_NOTIFICATION,
+		ESPI_PERIPHERAL_8042_KBC, ESPI_PERIPHERAL_NODATA
+	};
 
 	/* Disable KBC OBE interrupt first */
 	inst_kbc->HICTRL &= ~BIT(NPCX_HICTRL_OBECIE);
@@ -255,11 +257,13 @@ static void host_kbc_obe_isr(void *arg)
 	LOG_DBG("%s: kbc status 0x%02x", __func__, inst_kbc->HIKMST);
 
 	/*
-	 * TODO: Notify application that host already read out data. We might
-	 * use E8042_SET_FLAG in espi_api_lpc_write_request() instead of setting
-	 * status of HIKMST here directly.
+	 * Notify application that host already read out data. The application
+	 * might need to clear status register via espi_api_lpc_write_request()
+	 * with E8042_CLEAR_FLAG opcode in callback.
 	 */
-	inst_kbc->HIKMST &= ~BIT(NPCX_HIKMST_ST1);
+	evt.evt_data = NPCX_8042_EVT_DATA(NPCX_8042_EVT_OBE, 0, 0);
+	espi_send_callbacks(host_sub_data.callbacks, host_sub_data.host_bus_dev,
+							evt);
 }
 
 static void host_kbc_init(void)
diff --git a/drivers/lora/sx12xx_common.c b/drivers/lora/sx12xx_common.c
index b62958e811..05c78b58dc 100644
--- a/drivers/lora/sx12xx_common.c
+++ b/drivers/lora/sx12xx_common.c
@@ -148,5 +148,14 @@ int sx12xx_init(const struct device *dev)
 	dev_data.events.RxDone = sx12xx_ev_rx_done;
 	Radio.Init(&dev_data.events);
 
+	/*
+	 * Automatically place the radio into sleep mode upon boot.
+	 * The required `lora_config` call before transmission or reception
+	 * will bring the radio out of sleep mode before it is used. The radio
+	 * is automatically placed back into sleep mode upon TX or RX
+	 * completion.
+	 */
+	Radio.Sleep();
+
 	return 0;
 }
diff --git a/drivers/sensor/max17055/max17055.c b/drivers/sensor/max17055/max17055.c
index d4fd7095b3..fe73f8980c 100644
--- a/drivers/sensor/max17055/max17055.c
+++ b/drivers/sensor/max17055/max17055.c
@@ -41,6 +41,18 @@ static int max17055_reg_read(struct max17055_data *priv, int reg_addr,
 	return 0;
 }
 
+/**
+ * @brief Convert current in MAX17055 units to milliamps
+ *
+ * @param rsense_mohms Value of Rsense in milliohms
+ * @param val Value to convert (taken from a MAX17055 register)
+ * @return corresponding value in milliamps
+ */
+static int current_to_ma(unsigned int rsense_mohms, int16_t val)
+{
+	return (val * 1.5625) / rsense_mohms;
+}
+
 /**
  * @brief Convert capacity in MAX17055 units to milliamps
  *
@@ -91,11 +103,11 @@ static int max17055_channel_get(const struct device *dev,
 		valp->val2 = tmp % 1000000;
 		break;
 	case SENSOR_CHAN_GAUGE_AVG_CURRENT: {
-		int cap_ma;
+		int current_ma;
 
-		cap_ma = capacity_to_ma(config->rsense_mohms,
-					priv->avg_current);
-		set_millis(valp, cap_ma);
+		current_ma = current_to_ma(config->rsense_mohms,
+					   priv->avg_current);
+		set_millis(valp, current_ma);
 		break;
 	}
 	case SENSOR_CHAN_GAUGE_STATE_OF_CHARGE:
diff --git a/drivers/wifi/esp/esp.c b/drivers/wifi/esp/esp.c
index 8e29d63563..3c534d76e1 100644
--- a/drivers/wifi/esp/esp.c
+++ b/drivers/wifi/esp/esp.c
@@ -398,7 +398,7 @@ MODEM_CMD_DEFINE(on_cmd_closed)
 				ESP_SOCK_CONNECTED, ESP_SOCK_CLOSE_PENDING);
 
 	if (!(old_flags & ESP_SOCK_CONNECTED)) {
-		LOG_WRN("Link %d already closed", link_id);
+		LOG_DBG("Link %d already closed", link_id);
 		goto socket_unref;
 	}
 
diff --git a/include/bluetooth/bluetooth.h b/include/bluetooth/bluetooth.h
index 9bb55788d3..a3100c4580 100644
--- a/include/bluetooth/bluetooth.h
+++ b/include/bluetooth/bluetooth.h
@@ -1489,11 +1489,6 @@ enum {
 	 * @note Requires @ref BT_LE_SCAN_OPT_CODED.
 	 */
 	BT_LE_SCAN_OPT_NO_1M = BIT(3),
-
-	BT_LE_SCAN_FILTER_DUPLICATE __deprecated =
-		BT_LE_SCAN_OPT_FILTER_DUPLICATE,
-	BT_LE_SCAN_FILTER_WHITELIST __deprecated =
-		BT_LE_SCAN_OPT_FILTER_WHITELIST,
 };
 
 enum {
@@ -1509,13 +1504,8 @@ struct bt_le_scan_param {
 	/** Scan type (BT_LE_SCAN_TYPE_ACTIVE or BT_LE_SCAN_TYPE_PASSIVE) */
 	uint8_t  type;
 
-	union {
-		/** Bit-field of scanning filter options. */
-		uint32_t filter_dup __deprecated;
-
-		/** Bit-field of scanning options. */
-		uint32_t options;
-	};
+	/** Bit-field of scanning options. */
+	uint32_t options;
 
 	/** Scan interval (N * 0.625 ms) */
 	uint16_t interval;
diff --git a/include/bluetooth/buf.h b/include/bluetooth/buf.h
index cc1e220f0a..35c3873d31 100644
--- a/include/bluetooth/buf.h
+++ b/include/bluetooth/buf.h
@@ -45,9 +45,6 @@ struct bt_buf_data {
 	uint8_t type;
 };
 
-/** Minimum amount of user data size for buffers passed to the stack. */
-#define BT_BUF_USER_DATA_MIN __DEPRECATED_MACRO 4
-
 #if defined(CONFIG_BT_HCI_RAW)
 #define BT_BUF_RESERVE MAX(CONFIG_BT_HCI_RESERVE, CONFIG_BT_HCI_RAW_RESERVE)
 #else
diff --git a/include/bluetooth/conn.h b/include/bluetooth/conn.h
index ae013c9d59..3f74e4c60d 100644
--- a/include/bluetooth/conn.h
+++ b/include/bluetooth/conn.h
@@ -542,7 +542,7 @@ struct bt_conn_le_create_param {
 	 *  Set zero to use the default @option{CONFIG_BT_CREATE_CONN_TIMEOUT}
 	 *  timeout.
 	 *
-	 *  @note Unused in @ref bt_conn_create_auto_le
+	 *  @note Unused in @ref bt_conn_le_create_auto
 	 */
 	uint16_t timeout;
 };
@@ -612,24 +612,6 @@ int bt_conn_le_create(const bt_addr_le_t *peer,
 		      const struct bt_le_conn_param *conn_param,
 		      struct bt_conn **conn);
 
-__deprecated static inline
-struct bt_conn *bt_conn_create_le(const bt_addr_le_t *peer,
-				  const struct bt_le_conn_param *conn_param)
-{
-	struct bt_conn *conn;
-	struct bt_conn_le_create_param param = BT_CONN_LE_CREATE_PARAM_INIT(
-						BT_CONN_LE_OPT_NONE,
-						BT_GAP_SCAN_FAST_INTERVAL,
-						BT_GAP_SCAN_FAST_INTERVAL);
-
-	if (bt_conn_le_create(peer, &param, conn_param,
-			      &conn)) {
-		return NULL;
-	}
-
-	return conn;
-}
-
 /** @brief Automatically connect to remote devices in whitelist.
  *
  *  This uses the Auto Connection Establishment procedure.
@@ -648,17 +630,6 @@ struct bt_conn *bt_conn_create_le(const bt_addr_le_t *peer,
 int bt_conn_le_create_auto(const struct bt_conn_le_create_param *create_param,
 			   const struct bt_le_conn_param *conn_param);
 
-__deprecated static inline
-int bt_conn_create_auto_le(const struct bt_le_conn_param *conn_param)
-{
-	struct bt_conn_le_create_param param = BT_CONN_LE_CREATE_PARAM_INIT(
-						BT_CONN_LE_OPT_NONE,
-						BT_GAP_SCAN_FAST_INTERVAL,
-						BT_GAP_SCAN_FAST_WINDOW);
-
-	return bt_conn_le_create_auto(&param, conn_param);
-}
-
 /** @brief Stop automatic connect creation.
  *
  *  @return Zero on success or (negative) error code on failure.
@@ -682,45 +653,6 @@ int bt_conn_create_auto_stop(void);
 int bt_le_set_auto_conn(const bt_addr_le_t *addr,
 			const struct bt_le_conn_param *param);
 
-/** @brief Initiate directed advertising to a remote device
- *
- *  Allows initiating a new LE connection to remote peer with the remote
- *  acting in central role and the local device in peripheral role.
- *
- *  The advertising type will either be BT_LE_ADV_DIRECT_IND, or
- *  BT_LE_ADV_DIRECT_IND_LOW_DUTY if the BT_LE_ADV_OPT_DIR_MODE_LOW_DUTY
- *  option was used as part of the advertising parameters.
- *
- *  In case of high duty cycle this will result in a callback with
- *  connected() with a new connection or with an error.
- *
- *  The advertising may be canceled with bt_conn_disconnect().
- *
- *  The caller gets a new reference to the connection object which must be
- *  released with bt_conn_unref() once done using the object.
- *
- *  @param peer  Remote address.
- *  @param param Directed advertising parameters.
- *
- *  @return Valid connection object on success or NULL otherwise.
- */
-__deprecated static inline
-struct bt_conn *bt_conn_create_slave_le(const bt_addr_le_t *peer,
-					const struct bt_le_adv_param *param)
-{
-	struct bt_le_adv_param adv_param = *param;
-
-	adv_param.options |= (BT_LE_ADV_OPT_CONNECTABLE |
-			      BT_LE_ADV_OPT_ONE_TIME);
-	adv_param.peer = peer;
-
-	if (!bt_le_adv_start(&adv_param, NULL, 0, NULL, 0)) {
-		return NULL;
-	}
-
-	return bt_conn_lookup_addr_le(param->id, peer);
-}
-
 /** Security level. */
 typedef enum __packed {
 	/** Level 0: Only for BR/EDR special cases, like SDP */
@@ -733,13 +665,6 @@ typedef enum __packed {
 	BT_SECURITY_L3,
 	/** Level 4: Authenticated Secure Connections and 128-bit key. */
 	BT_SECURITY_L4,
-
-	BT_SECURITY_NONE   __deprecated = BT_SECURITY_L0,
-	BT_SECURITY_LOW    __deprecated = BT_SECURITY_L1,
-	BT_SECURITY_MEDIUM __deprecated = BT_SECURITY_L2,
-	BT_SECURITY_HIGH   __deprecated = BT_SECURITY_L3,
-	BT_SECURITY_FIPS   __deprecated = BT_SECURITY_L4,
-
 	/** Bit to force new pairing procedure, bit-wise OR with requested
 	 *  security level.
 	 */
@@ -784,12 +709,6 @@ int bt_conn_set_security(struct bt_conn *conn, bt_security_t sec);
  */
 bt_security_t bt_conn_get_security(struct bt_conn *conn);
 
-static inline int __deprecated bt_conn_security(struct bt_conn *conn,
-						bt_security_t sec)
-{
-	return bt_conn_set_security(conn, sec);
-}
-
 /** @brief Get encryption key size.
  *
  *  This function gets encryption key size.
@@ -852,7 +771,7 @@ struct bt_conn_cb {
 	 *
 	 *  @p err can mean either of the following:
 	 *  - @ref BT_HCI_ERR_UNKNOWN_CONN_ID Creating the connection started by
-	 *    @ref bt_conn_create_le was canceled either by the user through
+	 *    @ref bt_conn_le_create was canceled either by the user through
 	 *    @ref bt_conn_disconnect or by the timeout in the host through
 	 *    @ref bt_conn_le_create_param timeout parameter, which defaults to
 	 *    @option{CONFIG_BT_CREATE_CONN_TIMEOUT} seconds.
diff --git a/include/bluetooth/hci.h b/include/bluetooth/hci.h
index 9b70047d3c..f59a77d32d 100644
--- a/include/bluetooth/hci.h
+++ b/include/bluetooth/hci.h
@@ -803,15 +803,6 @@ struct bt_hci_cp_le_set_random_address {
 	bt_addr_t bdaddr;
 } __packed;
 
-/* LE Advertising Types (LE Advertising Parameters Set)*/
-#define BT_LE_ADV_IND                  (__DEPRECATED_MACRO 0x00)
-#define BT_LE_ADV_DIRECT_IND           (__DEPRECATED_MACRO 0x01)
-#define BT_LE_ADV_SCAN_IND             (__DEPRECATED_MACRO 0x02)
-#define BT_LE_ADV_NONCONN_IND          (__DEPRECATED_MACRO 0x03)
-#define BT_LE_ADV_DIRECT_IND_LOW_DUTY  (__DEPRECATED_MACRO 0x04)
-/* LE Advertising PDU Types. */
-#define BT_LE_ADV_SCAN_RSP             (__DEPRECATED_MACRO 0x04)
-
 #define BT_HCI_ADV_IND                          0x00
 #define BT_HCI_ADV_DIRECT_IND                   0x01
 #define BT_HCI_ADV_SCAN_IND                     0x02
diff --git a/include/bluetooth/hci_err.h b/include/bluetooth/hci_err.h
index 476d3f4638..7740d27059 100644
--- a/include/bluetooth/hci_err.h
+++ b/include/bluetooth/hci_err.h
@@ -83,8 +83,6 @@ extern "C" {
 #define BT_HCI_ERR_OP_CANCELLED_BY_HOST         0x44
 #define BT_HCI_ERR_PACKET_TOO_LONG              0x45
 
-#define BT_HCI_ERR_AUTHENTICATION_FAIL __DEPRECATED_MACRO BT_HCI_ERR_AUTH_FAIL
-
 #ifdef __cplusplus
 }
 #endif
diff --git a/include/drivers/uart.h b/include/drivers/uart.h
index c6a2f625f7..56242f88ab 100644
--- a/include/drivers/uart.h
+++ b/include/drivers/uart.h
@@ -43,44 +43,50 @@ enum uart_line_ctrl {
  *
  * Receiving:
  * 1. To start receiving, uart_rx_enable has to be called with first buffer
- * 2. When receiving starts to current buffer, UART_RX_BUF_REQUEST will be
- *    generated, in response to that user can either:
+ * 2. When receiving starts to current buffer,
+ *    @ref uart_event_type::UART_RX_BUF_REQUEST will be generated, in response
+ *    to that user can either:
  *
  *    - Provide second buffer using uart_rx_buf_rsp, when first buffer is
  *      filled, receiving will automatically start to second buffer.
  *    - Ignore the event, this way when current buffer is filled UART_RX_DONE
  *      event will be generated and receiving will be stopped.
  *
- * 3. If some data was received and timeout occurred UART_RX_RDY event will be
- *    generated. It can happen multiples times for the same buffer. RX timeout
- *    is counted from last byte received i.e. if no data was received, there
- *    won't be any timeout event.
- * 4. After buffer is filled UART_RX_RDY will be generated, immediately
- *    followed by UART_RX_BUF_RELEASED indicating that current buffer is no
- *    longer used.
+ * 3. If some data was received and timeout occurred
+ *    @ref uart_event_type::UART_RX_RDY event will be generated. It can happen
+ *    multiples times for the same buffer. RX timeout is counted from last byte
+ *    received i.e. if no data was received, there won't be any timeout event.
+ * 4. After buffer is filled @ref uart_event_type::UART_RX_RDY will be
+ *    generated, immediately followed by
+ *    @ref uart_event_type::UART_RX_BUF_RELEASED indicating that current buffer
+ *    is no longer used.
  * 5. If there was second buffer provided, it will become current buffer and
  *    we start again at point 2.
  *    If no second buffer was specified receiving is stopped and
- *    UART_RX_DISABLED event is generated. After that whole process can be
- *    repeated.
+ *    @ref uart_event_type::UART_RX_DISABLED event is generated. After that
+ *    whole process can be repeated.
  *
- * Any time during reception UART_RX_STOPPED event can occur. if there is any
- * data received, UART_RX_RDY event will be generated. It will be followed by
- * UART_RX_BUF_RELEASED event for every buffer currently passed to driver and
- * finally by UART_RX_DISABLED event.
+ * Any time during reception @ref uart_event_type::UART_RX_STOPPED event can
+ * occur. if there is any data received, @ref uart_event_type::UART_RX_RDY
+ * event will be generated. It will be followed by
+ * @ref uart_event_type::UART_RX_BUF_RELEASED event for every buffer currently
+ * passed to driver and finally by @ref uart_event_type::UART_RX_DISABLED event.
  *
  * Receiving can be disabled using uart_rx_disable, after calling that
- * function, if there is any data received, UART_RX_RDY event will be generated.
- * UART_RX_BUF_RELEASED event will be generated for every buffer currently
- * passed to driver and finally UART_RX_DISABLED event will occur.
+ * function, if there is any data received,
+ * @ref uart_event_type::UART_RX_RDY event will be generated.
+ * @ref uart_event_type::UART_RX_BUF_RELEASED event will be generated for every
+ * buffer currently passed to driver and finally
+ * @ref uart_event_type::UART_RX_DISABLED event will occur.
  *
  * Transmitting:
  * 1. Transmitting starts by uart_tx function.
- * 2. If whole buffer was transmitted UART_TX_DONE is generated.
- *    If timeout occurred UART_TX_ABORTED will be generated.
+ * 2. If whole buffer was transmitted @ref uart_event_type::UART_TX_DONE is
+ *    generated. If timeout occurred @ref uart_event_type::UART_TX_ABORTED will
+ *    be generated.
  *
- * Transmitting can be aborted using uart_tx_abort, after calling that
- * function UART_TX_ABORTED event will be generated.
+ * Transmitting can be aborted using @ref uart_tx_abort, after calling that
+ * function @ref uart_event_type::UART_TX_ABORTED event will be generated.
  *
  */
 enum uart_event_type {
@@ -102,7 +108,8 @@ enum uart_event_type {
 	 *   This can happen multiple times in the same buffer.
 	 * - When provided buffer is full.
 	 * - After uart_rx_disable().
-	 * - After stopping due to external event (UART_RX_STOPPED).
+	 * - After stopping due to external event
+	 *   (@ref uart_event_type::UART_RX_STOPPED).
 	 */
 	UART_RX_RDY,
 	/**
@@ -204,13 +211,17 @@ struct uart_event {
 	enum uart_event_type type;
 	/** @brief Event data */
 	union uart_event_data {
-		/** @brief UART_TX_DONE and UART_TX_ABORTED events data. */
+		/** @brief @ref uart_event_type::UART_TX_DONE and
+		 *	   @ref uart_event_type::UART_TX_ABORTED events data.
+		 */
 		struct uart_event_tx tx;
-		/** @brief UART_RX_RDY event data. */
+		/** @brief @ref uart_event_type::UART_RX_RDY event data. */
 		struct uart_event_rx rx;
-		/** @brief UART_RX_BUF_RELEASED event data. */
+		/** @brief @ref uart_event_type::UART_RX_BUF_RELEASED event
+		 *	   data.
+		 */
 		struct uart_event_rx_buf rx_buf;
-		/** @brief UART_RX_STOPPED event data. */
+		/** @brief @ref uart_event_type::UART_RX_STOPPED event data. */
 		struct uart_event_rx_stop rx_stop;
 	} data;
 };
@@ -483,7 +494,8 @@ static inline int z_impl_uart_tx(const struct device *dev, const uint8_t *buf,
 /**
  * @brief Abort current TX transmission.
  *
- * UART_TX_DONE event will be generated with amount of data sent.
+ * @ref uart_event_type::UART_TX_DONE event will be generated with amount of
+ * data sent.
  *
  * @param dev UART device structure.
  *
@@ -510,12 +522,16 @@ static inline int z_impl_uart_tx_abort(const struct device *dev)
  *
  * Function sets given buffer as first buffer for receiving and returns
  * immediately. After that event handler, set using @ref uart_callback_set,
- * is called with UART_RX_RDY or UART_RX_BUF_REQUEST events.
+ * is called with @ref uart_event_type::UART_RX_RDY or
+ * @ref uart_event_type::UART_RX_BUF_REQUEST events.
  *
  * @param dev     UART device structure.
  * @param buf     Pointer to receive buffer.
  * @param len     Buffer length.
- * @param timeout Timeout in milliseconds. @ref SYS_FOREVER_MS disables timeout.
+ * @param timeout Inactivity period after receiving at least a byte which
+ *		  triggers  @ref uart_event_type::UART_RX_RDY event. Given in
+ *		  milliseconds. @ref SYS_FOREVER_MS disables timeout. See
+ *		  @ref uart_event_type for details.
  *
  * @retval -ENOTSUP If not supported.
  * @retval -EBUSY   RX already in progress.
@@ -541,7 +557,8 @@ static inline int z_impl_uart_rx_enable(const struct device *dev,
 }
 
 /**
- * @brief Provide receive buffer in response to UART_RX_BUF_REQUEST event.
+ * @brief Provide receive buffer in response to
+ * @ref uart_event_type::UART_RX_BUF_REQUEST event.
  *
  * Provide pointer to RX buffer, which will be used when current buffer is
  * filled.
@@ -576,10 +593,11 @@ static inline int uart_rx_buf_rsp(const struct device *dev, uint8_t *buf,
 /**
  * @brief Disable RX
  *
- * UART_RX_BUF_RELEASED event will be generated for every buffer scheduled,
- * after that UART_RX_DISABLED event will be generated. Additionally, if there
- * is any pending received data, the UART_RX_RDY event for that data will be
- * generated before the UART_RX_BUF_RELEASED events.
+ * @ref uart_event_type::UART_RX_BUF_RELEASED event will be generated for every
+ * buffer scheduled, after that @ref uart_event_type::UART_RX_DISABLED event
+ * will be generated. Additionally, if there is any pending received data, the
+ * @ref uart_event_type::UART_RX_RDY event for that data will be generated
+ * before the @ref uart_event_type::UART_RX_BUF_RELEASED events.
  *
  * @param dev UART device structure.
  *
diff --git a/include/fs/fs.h b/include/fs/fs.h
index 7aef7c78d3..f717e8cd45 100644
--- a/include/fs/fs.h
+++ b/include/fs/fs.h
@@ -220,6 +220,20 @@ struct fs_statvfs {
 #define FS_FSTAB_DECLARE_ENTRY(node_id)		\
 	extern struct fs_mount_t FS_FSTAB_ENTRY(node_id)
 
+/**
+ * @brief Initialize fs_file_t object
+ *
+ * Initialized the fs_file_t object; the function needs to be invoked
+ * on object before first use with fs_open.
+ *
+ * @param zfp Pointer to file object
+ *
+ */
+static inline void fs_file_t_init(struct fs_file_t *zfp)
+{
+	*zfp = (struct fs_file_t){ 0 };
+}
+
 /**
  * @brief Open or create file
  *
diff --git a/include/fs/fs_interface.h b/include/fs/fs_interface.h
index 889034ff70..d1a30da746 100644
--- a/include/fs/fs_interface.h
+++ b/include/fs/fs_interface.h
@@ -45,6 +45,8 @@ struct fs_mount_t;
 /**
  * @brief File object representing an open file
  *
+ * The object needs to be initialized with function fs_file_t_init().
+ *
  * @param Pointer to FATFS file object structure
  * @param mp Pointer to mount point structure
  */
diff --git a/lib/posix/fs.c b/lib/posix/fs.c
index 9c9af95c5a..90187eae53 100644
--- a/lib/posix/fs.c
+++ b/lib/posix/fs.c
@@ -107,7 +107,7 @@ int open(const char *name, int flags, ...)
 		return -1;
 	}
 
-	(void)memset(&ptr->file, 0, sizeof(ptr->file));
+	fs_file_t_init(&ptr->file);
 
 	rc = fs_open(&ptr->file, name, zmode);
 
diff --git a/samples/audio/sof/prj.conf b/samples/audio/sof/prj.conf
index 41bfe78400..2be9a027b5 100644
--- a/samples/audio/sof/prj.conf
+++ b/samples/audio/sof/prj.conf
@@ -3,7 +3,6 @@ CONFIG_SMP=n
 CONFIG_LOG=y
 CONFIG_MP_NUM_CPUS=1
 CONFIG_BUILD_OUTPUT_BIN=n
-CONFIG_RESET_VECTOR_IN_BOOTLOADER=y
 
 # Requires heap_info() be implemented, but no Zephyr wrapper
 CONFIG_DEBUG_MEMORY_USAGE_SCAN=n
diff --git a/samples/bluetooth/central_ht/src/main.c b/samples/bluetooth/central_ht/src/main.c
index 4f5d4136fe..2f68b1f5e6 100644
--- a/samples/bluetooth/central_ht/src/main.c
+++ b/samples/bluetooth/central_ht/src/main.c
@@ -228,7 +228,7 @@ static int scan_start(void)
 	 */
 	struct bt_le_scan_param scan_param = {
 		.type       = BT_LE_SCAN_TYPE_ACTIVE,
-		.filter_dup = BT_LE_SCAN_OPT_FILTER_DUPLICATE,
+		.options    = BT_LE_SCAN_OPT_FILTER_DUPLICATE,
 		.interval   = BT_GAP_SCAN_FAST_INTERVAL,
 		.window     = BT_GAP_SCAN_FAST_WINDOW,
 	};
diff --git a/samples/bluetooth/peripheral_hr/src/main.c b/samples/bluetooth/peripheral_hr/src/main.c
index 4d338abf0f..05319a4920 100644
--- a/samples/bluetooth/peripheral_hr/src/main.c
+++ b/samples/bluetooth/peripheral_hr/src/main.c
@@ -22,8 +22,6 @@
 #include <bluetooth/services/bas.h>
 #include <bluetooth/services/hrs.h>
 
-struct bt_conn *default_conn;
-
 static const struct bt_data ad[] = {
 	BT_DATA_BYTES(BT_DATA_FLAGS, (BT_LE_AD_GENERAL | BT_LE_AD_NO_BREDR)),
 	BT_DATA_BYTES(BT_DATA_UUID16_ALL,
@@ -37,7 +35,6 @@ static void connected(struct bt_conn *conn, uint8_t err)
 	if (err) {
 		printk("Connection failed (err 0x%02x)\n", err);
 	} else {
-		default_conn = bt_conn_ref(conn);
 		printk("Connected\n");
 	}
 }
@@ -45,11 +42,6 @@ static void connected(struct bt_conn *conn, uint8_t err)
 static void disconnected(struct bt_conn *conn, uint8_t reason)
 {
 	printk("Disconnected (reason 0x%02x)\n", reason);
-
-	if (default_conn) {
-		bt_conn_unref(default_conn);
-		default_conn = NULL;
-	}
 }
 
 static struct bt_conn_cb conn_callbacks = {
diff --git a/samples/bluetooth/peripheral_ht/src/main.c b/samples/bluetooth/peripheral_ht/src/main.c
index acccec6728..baab2b3dae 100644
--- a/samples/bluetooth/peripheral_ht/src/main.c
+++ b/samples/bluetooth/peripheral_ht/src/main.c
@@ -23,8 +23,6 @@
 
 #include "hts.h"
 
-struct bt_conn *default_conn;
-
 static const struct bt_data ad[] = {
 	BT_DATA_BYTES(BT_DATA_FLAGS, (BT_LE_AD_GENERAL | BT_LE_AD_NO_BREDR)),
 	BT_DATA_BYTES(BT_DATA_UUID16_ALL,
@@ -38,7 +36,6 @@ static void connected(struct bt_conn *conn, uint8_t err)
 	if (err) {
 		printk("Connection failed (err 0x%02x)\n", err);
 	} else {
-		default_conn = bt_conn_ref(conn);
 		printk("Connected\n");
 	}
 }
@@ -46,11 +43,6 @@ static void connected(struct bt_conn *conn, uint8_t err)
 static void disconnected(struct bt_conn *conn, uint8_t reason)
 {
 	printk("Disconnected (reason 0x%02x)\n", reason);
-
-	if (default_conn) {
-		bt_conn_unref(default_conn);
-		default_conn = NULL;
-	}
 }
 
 static struct bt_conn_cb conn_callbacks = {
diff --git a/samples/display/lvgl/README.rst b/samples/display/lvgl/README.rst
index fa6b1920bb..cf1e638aa0 100644
--- a/samples/display/lvgl/README.rst
+++ b/samples/display/lvgl/README.rst
@@ -49,7 +49,7 @@ Building and Running
 Example building for :ref:`nrf52840dk_nrf52840`:
 
 .. zephyr-app-commands::
-   :zephyr-app: samples/gui/lvgl
+   :zephyr-app: samples/display/lvgl
    :board: nrf52840dk_nrf52840
    :shield: adafruit_2_8_tft_touch_v2
    :goals: build flash
@@ -57,7 +57,7 @@ Example building for :ref:`nrf52840dk_nrf52840`:
 Example building for :ref:`native_posix`:
 
 .. zephyr-app-commands::
-   :zephyr-app: samples/gui/lvgl
+   :zephyr-app: samples/display/lvgl
    :board: native_posix
    :goals: build flash
 
diff --git a/samples/drivers/adc/boards/disco_l475_iot1.overlay b/samples/drivers/adc/boards/disco_l475_iot1.overlay
new file mode 100644
index 0000000000..f4b5729069
--- /dev/null
+++ b/samples/drivers/adc/boards/disco_l475_iot1.overlay
@@ -0,0 +1,12 @@
+/*
+ * SPDX-License-Identifier: Apache-2.0
+ *
+ * Copyright (c) 2020 Linaro Limited
+ */
+
+/ {
+	zephyr,user {
+		/* adjust channel number according to pinmux in board.dts */
+		io-channels = <&adc1 5>;
+	};
+};
diff --git a/samples/drivers/adc/sample.yaml b/samples/drivers/adc/sample.yaml
index ab10b8b4da..7b978ae584 100644
--- a/samples/drivers/adc/sample.yaml
+++ b/samples/drivers/adc/sample.yaml
@@ -4,9 +4,10 @@ tests:
   sample.drivers.adc:
     tags: ADC
     depends_on: adc
-    platform_allow: nucleo_l073rz
+    platform_allow: nucleo_l073rz disco_l475_iot1
     harness: console
+    timeout: 10
     harness_config:
-      type: single_line
+      type: one_line
       regex:
-        - "ADC reading(s): (.*)"
+        - "ADC reading: (.*)"
diff --git a/samples/drivers/adc/src/main.c b/samples/drivers/adc/src/main.c
index 35585c6fe5..338f892eed 100644
--- a/samples/drivers/adc/src/main.c
+++ b/samples/drivers/adc/src/main.c
@@ -98,7 +98,7 @@ void main(void)
 			return;
 		}
 
-		printk("ADC reading(s):");
+		printk("ADC reading:");
 		for (uint8_t i = 0; i < ADC_NUM_CHANNELS; i++) {
 			int32_t raw_value = sample_buffer[i];
 
diff --git a/samples/subsys/fs/littlefs/sample.yaml b/samples/subsys/fs/littlefs/sample.yaml
index b6d7883f67..8af39843e5 100644
--- a/samples/subsys/fs/littlefs/sample.yaml
+++ b/samples/subsys/fs/littlefs/sample.yaml
@@ -4,5 +4,5 @@ tests:
   sample.filesystem.littlefs:
     build_only: true
     platform_allow: nrf52840dk_nrf52840 particle_xenon disco_l475_iot1
-      mimxrt1064_evk
+      mimxrt1064_evk qemu_x86 native_posix
     tags: filesystem
diff --git a/samples/subsys/fs/littlefs/src/main.c b/samples/subsys/fs/littlefs/src/main.c
index b968343d47..a9c086e0f9 100644
--- a/samples/subsys/fs/littlefs/src/main.c
+++ b/samples/subsys/fs/littlefs/src/main.c
@@ -99,6 +99,8 @@ void main(void)
 
 	struct fs_file_t file;
 
+	fs_file_t_init(&file);
+
 	rc = fs_open(&file, fname, FS_O_CREATE | FS_O_RDWR);
 	if (rc < 0) {
 		printk("FAIL: open %s: %d\n", fname, rc);
diff --git a/scripts/ci/check_compliance.py b/scripts/ci/check_compliance.py
index 85c438e6a5..5ca6ad46e6 100755
--- a/scripts/ci/check_compliance.py
+++ b/scripts/ci/check_compliance.py
@@ -225,13 +225,14 @@ class KconfigCheck(ComplianceTest):
     doc = "See https://docs.zephyrproject.org/latest/guides/kconfig/index.html for more details."
     path_hint = ZEPHYR_BASE
 
-    def run(self):
+    def run(self, full=True):
         kconf = self.parse_kconfig()
 
         self.check_top_menu_not_too_long(kconf)
         self.check_no_pointless_menuconfigs(kconf)
         self.check_no_undef_within_kconfig(kconf)
-        self.check_no_undef_outside_kconfig(kconf)
+        if full:
+            self.check_no_undef_outside_kconfig(kconf)
 
     def get_modules(self, modules_file):
         """
@@ -453,7 +454,7 @@ https://docs.zephyrproject.org/latest/guides/kconfig/tips.html#menuconfig-symbol
         # Skip doc/releases, which often references removed symbols
         grep_stdout = git("grep", "--line-number", "-I", "--null",
                           "--perl-regexp", regex, "--", ":!/doc/releases",
-                          cwd=ZEPHYR_BASE)
+                          cwd=Path(GIT_TOP))
 
         # splitlines() supports various line terminators
         for grep_line in grep_stdout.splitlines():
@@ -569,6 +570,20 @@ UNDEF_KCONFIG_WHITELIST = {
     "WHATEVER",
 }
 
+class KconfigBasicCheck(KconfigCheck, ComplianceTest):
+    """
+    Checks is we are introducing any new warnings/errors with Kconfig,
+    for example using undefiend Kconfig variables.
+    This runs the basic Kconfig test, which is checking only for undefined
+    references inside the Kconfig tree.
+    """
+    name = "KconfigBasic"
+    doc = "See https://docs.zephyrproject.org/latest/guides/kconfig/index.html for more details."
+    path_hint = ZEPHYR_BASE
+
+    def run(self):
+        super().run(full=False)
+
 
 class Codeowners(ComplianceTest):
     """
diff --git a/scripts/ci/twister_ignore.txt b/scripts/ci/twister_ignore.txt
index 7c35aa108d..088f3e870d 100644
--- a/scripts/ci/twister_ignore.txt
+++ b/scripts/ci/twister_ignore.txt
@@ -5,6 +5,7 @@
 # are matched, then twister will not do a full run and optionally will only
 # run on changed tests or boards.
 #
+.buildkite/daily.yml
 .gitlint
 .checkpatch.conf
 .clang-format
diff --git a/scripts/pylib/twister/twisterlib.py b/scripts/pylib/twister/twisterlib.py
index 08c8eb7694..cf5c932471 100644
--- a/scripts/pylib/twister/twisterlib.py
+++ b/scripts/pylib/twister/twisterlib.py
@@ -3408,8 +3408,8 @@ class TestSuite(DisablePyTestCollectionMixin):
                                     'error',
                                     type="failure",
                                     message="failed")
-                            p = os.path.join(self.outdir, instance.platform.name, instance.testcase.name)
-                            log_file = os.path.join(p, "handler.log")
+                            log_root = os.path.join(self.outdir, instance.platform.name, instance.testcase.name)
+                            log_file = os.path.join(log_root, "handler.log")
                             el.text = self.process_log(log_file)
 
                         elif instance.results[k] == 'PASS' \
@@ -3445,9 +3445,9 @@ class TestSuite(DisablePyTestCollectionMixin):
                             type="failure",
                             message=instance.reason)
 
-                        p = ("%s/%s/%s" % (self.outdir, instance.platform.name, instance.testcase.name))
-                        bl = os.path.join(p, "build.log")
-                        hl = os.path.join(p, "handler.log")
+                        log_root = ("%s/%s/%s" % (self.outdir, instance.platform.name, instance.testcase.name))
+                        bl = os.path.join(log_root, "build.log")
+                        hl = os.path.join(log_root, "handler.log")
                         log_file = bl
                         if instance.reason != 'Build error':
                             if os.path.exists(hl):
diff --git a/scripts/twister b/scripts/twister
index a23f8253cf..c7619fe27c 100755
--- a/scripts/twister
+++ b/scripts/twister
@@ -1114,7 +1114,17 @@ def main():
         return
 
     if options.subset:
-        suite.instances = OrderedDict(sorted(suite.instances.items()))
+        # Test instances are sorted depending on the context. For CI runs
+        # the execution order is: "plat1-testA, plat1-testB, ...,
+        # plat1-testZ, plat2-testA, ...". For hardware tests
+        # (device_testing), were multiple physical platforms can run the tests
+        # in parallel, it is more efficient to run in the order:
+        # "plat1-testA, plat2-testA, ..., plat1-testB, plat2-testB, ..."
+        if options.device_testing:
+            suite.instances = OrderedDict(sorted(suite.instances.items(),
+                                key=lambda x: x[0][x[0].find("/") + 1:]))
+        else:
+            suite.instances = OrderedDict(sorted(suite.instances.items()))
 
         subset, sets = options.subset.split("/")
         subset = int(subset)
diff --git a/scripts/zephyr_module.py b/scripts/zephyr_module.py
index 18dedaf852..ed22b777d6 100755
--- a/scripts/zephyr_module.py
+++ b/scripts/zephyr_module.py
@@ -277,9 +277,15 @@ def main():
         # if user is providing a specific modules list.
         from west.manifest import Manifest
         from west.util import WestNotFound
+        from west.version import __version__ as WestVersion
+        from packaging import version
         try:
             manifest = Manifest.from_file()
-            projects = [p.posixpath for p in manifest.get_projects([])]
+            if version.parse(WestVersion) >= version.parse('0.9.0'):
+                projects = [p.posixpath for p in manifest.get_projects([])
+                            if manifest.is_active(p)]
+            else:
+                projects = [p.posixpath for p in manifest.get_projects([])]
         except WestNotFound:
             # Only accept WestNotFound, meaning we are not in a west
             # workspace. Such setup is allowed, as west may be installed
diff --git a/soc/arm/nordic_nrf/Kconfig.defconfig b/soc/arm/nordic_nrf/Kconfig.defconfig
index 121bc36539..281ff2e4bd 100644
--- a/soc/arm/nordic_nrf/Kconfig.defconfig
+++ b/soc/arm/nordic_nrf/Kconfig.defconfig
@@ -27,6 +27,9 @@ config SYS_CLOCK_TICKS_PER_SEC
 config ARCH_HAS_CUSTOM_BUSY_WAIT
 	default y
 
+config PM
+	default y if SYS_CLOCK_EXISTS && !HAS_NO_SYS_PM
+
 config BUILD_OUTPUT_HEX
 	default y
 
diff --git a/soc/arm/nordic_nrf/nrf53/Kconfig.soc b/soc/arm/nordic_nrf/nrf53/Kconfig.soc
index f6e73f637e..4056561662 100644
--- a/soc/arm/nordic_nrf/nrf53/Kconfig.soc
+++ b/soc/arm/nordic_nrf/nrf53/Kconfig.soc
@@ -96,6 +96,7 @@ config SOC_NRF5340_CPUNET
 	select HAS_HW_NRF_TWIS0
 	select HAS_HW_NRF_UARTE0
 	select HAS_HW_NRF_WDT
+	select HAS_NO_SYS_PM
 
 choice
 	prompt "nRF53x MCU Selection"
diff --git a/soc/arm/nuvoton_npcx/common/soc_espi.h b/soc/arm/nuvoton_npcx/common/soc_espi.h
index 54a8894e30..97d32cadd3 100644
--- a/soc/arm/nuvoton_npcx/common/soc_espi.h
+++ b/soc/arm/nuvoton_npcx/common/soc_espi.h
@@ -12,9 +12,23 @@ extern "C" {
 #endif
 
 /* 8042 event data format */
+#define NPCX_8042_EVT_POS 16U
 #define NPCX_8042_DATA_POS 8U
 #define NPCX_8042_TYPE_POS 0U
 
+/* 8042 event type format */
+#define NPCX_8042_EVT_IBF BIT(0)
+#define NPCX_8042_EVT_OBE BIT(1)
+
+/*
+ * The format of event data for KBC 8042 protocol:
+ * [23:16] - 8042 event type: 1: Input buffer full, 2: Output buffer empty.
+ * [15:8]  - 8042 data: 8-bit 8042 data.
+ * [0:7]   - 8042 protocol type: 0: data type, 1: command type.
+ */
+#define NPCX_8042_EVT_DATA(event, data, type) (((event) << NPCX_8042_EVT_POS) \
+	| ((data) << NPCX_8042_DATA_POS) | ((type) << NPCX_8042_TYPE_POS));
+
 /* ACPI event data format */
 #define NPCX_ACPI_DATA_POS 8U
 #define NPCX_ACPI_TYPE_POS 0U
diff --git a/subsys/bluetooth/controller/Kconfig.ll_sw_split b/subsys/bluetooth/controller/Kconfig.ll_sw_split
index 0a1aad05d8..27f26ac64d 100644
--- a/subsys/bluetooth/controller/Kconfig.ll_sw_split
+++ b/subsys/bluetooth/controller/Kconfig.ll_sw_split
@@ -201,6 +201,13 @@ config BT_CTLR_SCAN_SYNC_ISO_SET
 	help
 	  Maximum supported broadcast isochronous groups (BIGs) sync sets.
 
+config BT_CTLR_SCAN_ENABLE_STRICT
+	bool "Enforce Strict Scan Enable/Disable"
+	depends on BT_OBSERVER
+	help
+	  Enforce returning HCI Error Command Disallowed on enabling/disabling
+	  already enabled/disabled scanning.
+
 config BT_CTLR_ZLI
 	bool "Use Zero Latency IRQs"
 	depends on ZERO_LATENCY_IRQS
diff --git a/subsys/bluetooth/controller/hci/hci.c b/subsys/bluetooth/controller/hci/hci.c
index 66a3534bf2..a82bb877ab 100644
--- a/subsys/bluetooth/controller/hci/hci.c
+++ b/subsys/bluetooth/controller/hci/hci.c
@@ -1502,6 +1502,11 @@ static void le_set_scan_enable(struct net_buf *buf, struct net_buf **evt)
 	status = ll_scan_enable(cmd->enable);
 #endif /* !CONFIG_BT_CTLR_ADV_EXT */
 
+	if (!IS_ENABLED(CONFIG_BT_CTLR_SCAN_ENABLE_STRICT) &&
+	    (status == BT_HCI_ERR_CMD_DISALLOWED)) {
+		status = BT_HCI_ERR_SUCCESS;
+	}
+
 	*evt = cmd_complete_status(status);
 }
 
@@ -2973,6 +2978,11 @@ static void le_set_ext_scan_enable(struct net_buf *buf, struct net_buf **evt)
 
 	status = ll_scan_enable(cmd->enable, cmd->duration, cmd->period);
 
+	if (!IS_ENABLED(CONFIG_BT_CTLR_SCAN_ENABLE_STRICT) &&
+	    (status == BT_HCI_ERR_CMD_DISALLOWED)) {
+		status = BT_HCI_ERR_SUCCESS;
+	}
+
 	*evt = cmd_complete_status(status);
 }
 
diff --git a/subsys/bluetooth/controller/ll_sw/ull.c b/subsys/bluetooth/controller/ll_sw/ull.c
index 37a4844f11..ed3a1dbdbc 100644
--- a/subsys/bluetooth/controller/ll_sw/ull.c
+++ b/subsys/bluetooth/controller/ll_sw/ull.c
@@ -323,6 +323,9 @@ static inline void *mark_get(void *m);
 static inline void done_alloc(void);
 static inline void rx_alloc(uint8_t max);
 static void rx_demux(void *param);
+#if defined(CONFIG_BT_CTLR_LOW_LAT_ULL)
+static void rx_demux_yield(void);
+#endif /* CONFIG_BT_CTLR_LOW_LAT_ULL */
 #if defined(CONFIG_BT_CONN)
 static uint8_t tx_cmplt_get(uint16_t *handle, uint8_t *first, uint8_t last);
 static inline void rx_demux_conn_tx_ack(uint8_t ack_last, uint16_t handle,
@@ -1853,7 +1856,7 @@ static void rx_demux(void *param)
 
 #if defined(CONFIG_BT_CTLR_LOW_LAT_ULL)
 			if (!nack) {
-				ull_rx_sched();
+				rx_demux_yield();
 			}
 #else /* !CONFIG_BT_CTLR_LOW_LAT_ULL */
 			if (nack) {
@@ -1873,7 +1876,7 @@ static void rx_demux(void *param)
 						      link, node_tx);
 
 #if defined(CONFIG_BT_CTLR_LOW_LAT_ULL)
-				ull_rx_sched();
+				rx_demux_yield();
 #endif /* CONFIG_BT_CTLR_LOW_LAT_ULL */
 
 			}
@@ -1885,6 +1888,18 @@ static void rx_demux(void *param)
 #endif /* CONFIG_BT_CTLR_LOW_LAT_ULL */
 }
 
+#if defined(CONFIG_BT_CTLR_LOW_LAT_ULL)
+static void rx_demux_yield(void)
+{
+	static memq_link_t link;
+	static struct mayfly mfy = {0, 0, &link, NULL, rx_demux};
+
+	/* Kick the ULL (using the mayfly, tailchain it) */
+	mayfly_enqueue(TICKER_USER_ID_ULL_HIGH, TICKER_USER_ID_ULL_HIGH, 1,
+		       &mfy);
+}
+#endif /* CONFIG_BT_CTLR_LOW_LAT_ULL */
+
 #if defined(CONFIG_BT_CONN)
 static uint8_t tx_cmplt_get(uint16_t *handle, uint8_t *first, uint8_t last)
 {
diff --git a/subsys/bluetooth/host/conn.c b/subsys/bluetooth/host/conn.c
index c414e09ffc..c03851b060 100644
--- a/subsys/bluetooth/host/conn.c
+++ b/subsys/bluetooth/host/conn.c
@@ -2158,17 +2158,6 @@ int bt_conn_disconnect(struct bt_conn *conn, uint8_t reason)
 			bt_le_scan_update(false);
 		}
 		return 0;
-	case BT_CONN_CONNECT_DIR_ADV:
-		BT_WARN("Deprecated: Use bt_le_adv_stop instead");
-		conn->err = reason;
-		bt_conn_set_state(conn, BT_CONN_DISCONNECTED);
-		if (IS_ENABLED(CONFIG_BT_PERIPHERAL)) {
-			/* User should unref connection object when receiving
-			 * error in connection callback.
-			 */
-			return bt_le_adv_stop();
-		}
-		return 0;
 	case BT_CONN_CONNECT:
 #if defined(CONFIG_BT_BREDR)
 		if (conn->type == BT_CONN_TYPE_BR) {
diff --git a/subsys/bluetooth/mesh/cfg_cli.c b/subsys/bluetooth/mesh/cfg_cli.c
index c57d8bad37..65cc5e708c 100644
--- a/subsys/bluetooth/mesh/cfg_cli.c
+++ b/subsys/bluetooth/mesh/cfg_cli.c
@@ -1726,7 +1726,7 @@ int bt_mesh_cfg_mod_sub_get_vnd(uint16_t net_idx, uint16_t addr, uint16_t elem_a
 	}
 
 	return mod_member_list_get(OP_MOD_SUB_GET_VND, OP_MOD_SUB_LIST_VND,
-				   net_idx, addr, elem_addr, mod_id, CID_NVAL,
+				   net_idx, addr, elem_addr, mod_id, cid,
 				   status, subs, sub_cnt);
 }
 
diff --git a/subsys/fs/fs.c b/subsys/fs/fs.c
index 463a437f87..202d791219 100644
--- a/subsys/fs/fs.c
+++ b/subsys/fs/fs.c
@@ -143,25 +143,30 @@ int fs_open(struct fs_file_t *zfp, const char *file_name, fs_mode_t flags)
 		return -EINVAL;
 	}
 
+	if (zfp->mp != NULL) {
+		return -EBUSY;
+	}
+
 	rc = fs_get_mnt_point(&mp, file_name, NULL);
 	if (rc < 0) {
 		LOG_ERR("%s:mount point not found!!", __func__);
 		return rc;
 	}
 
-	zfp->mp = mp;
 	if (((mp->flags & FS_MOUNT_FLAG_READ_ONLY) != 0) &&
 	    (flags & FS_O_CREATE || flags & FS_O_WRITE)) {
 		return -EROFS;
 	}
 
-	CHECKIF(zfp->mp->fs->open == NULL) {
+	CHECKIF(mp->fs->open == NULL) {
 		return -ENOTSUP;
 	}
 
-	rc = zfp->mp->fs->open(zfp, file_name, flags);
+	zfp->mp = mp;
+	rc = mp->fs->open(zfp, file_name, flags);
 	if (rc < 0) {
 		LOG_ERR("file open error (%d)", rc);
+		zfp->mp = NULL;
 		return rc;
 	}
 
diff --git a/subsys/fs/fuse_fs_access.c b/subsys/fs/fuse_fs_access.c
index a56f1dd0b7..d6d7d04b85 100644
--- a/subsys/fs/fuse_fs_access.c
+++ b/subsys/fs/fuse_fs_access.c
@@ -468,6 +468,12 @@ static void fuse_fs_access_init(void)
 {
 	int err;
 	struct stat st;
+	size_t i = 0;
+
+	while (i < ARRAY_SIZE(files)) {
+		fs_file_t_init(&files[i]);
+		++i;
+	}
 
 	if (fuse_mountpoint == NULL) {
 		fuse_mountpoint = default_fuse_mountpoint;
diff --git a/subsys/fs/shell.c b/subsys/fs/shell.c
index dbbc7d01af..9025b3952b 100644
--- a/subsys/fs/shell.c
+++ b/subsys/fs/shell.c
@@ -188,6 +188,7 @@ static int cmd_trunc(const struct shell *shell, size_t argc, char **argv)
 		length = 0;
 	}
 
+	fs_file_t_init(&file);
 	err = fs_open(&file, path, FS_O_CREATE | FS_O_RDWR);
 	if (err) {
 		shell_error(shell, "Failed to open %s (%d)", path, err);
@@ -277,6 +278,7 @@ static int cmd_read(const struct shell *shell, size_t argc, char **argv)
 
 	shell_print(shell, "File size: %zd", dirent.size);
 
+	fs_file_t_init(&file);
 	err = fs_open(&file, path, FS_O_CREATE | FS_O_RDWR);
 	if (err) {
 		shell_error(shell, "Failed to open %s (%d)", path, err);
@@ -376,6 +378,7 @@ static int cmd_write(const struct shell *shell, size_t argc, char **argv)
 		arg_offset = 2;
 	}
 
+	fs_file_t_init(&file);
 	err = fs_open(&file, path, FS_O_CREATE | FS_O_RDWR);
 	if (err) {
 		shell_error(shell, "Failed to open %s (%d)", path, err);
diff --git a/subsys/net/ip/tcp2.c b/subsys/net/ip/tcp2.c
index edd7a1400f..39d8ffd58d 100644
--- a/subsys/net/ip/tcp2.c
+++ b/subsys/net/ip/tcp2.c
@@ -22,6 +22,8 @@ LOG_MODULE_REGISTER(net_tcp, CONFIG_NET_TCP_LOG_LEVEL);
 #include "net_private.h"
 #include "tcp2_priv.h"
 
+#define ACK_TIMEOUT_MS CONFIG_NET_TCP_ACK_TIMEOUT
+#define ACK_TIMEOUT K_MSEC(ACK_TIMEOUT_MS)
 #define FIN_TIMEOUT_MS MSEC_PER_SEC
 #define FIN_TIMEOUT K_MSEC(FIN_TIMEOUT_MS)
 
@@ -302,13 +304,19 @@ static void tcp_send(struct net_pkt *pkt)
 	if (is_6lo_technology(pkt)) {
 		struct net_pkt *new_pkt;
 
-		new_pkt = net_pkt_clone(pkt, TCP_PKT_ALLOC_TIMEOUT);
+		new_pkt = tcp_pkt_clone(pkt);
 		if (!new_pkt) {
+			/* The caller of this func assumes that the net_pkt
+			 * is consumed by this function. We call unref here
+			 * so that the unref at the end of the func will
+			 * free the net_pkt.
+			 */
+			tcp_pkt_unref(pkt);
 			goto out;
 		}
 
 		if (net_send_data(new_pkt) < 0) {
-			net_pkt_unref(new_pkt);
+			tcp_pkt_unref(new_pkt);
 		}
 
 		/* We simulate sending of the original pkt and unref it like
@@ -331,7 +339,7 @@ static void tcp_send_queue_flush(struct tcp *conn)
 
 	k_delayed_work_cancel(&conn->send_timer);
 
-	while ((pkt = tcp_slist(&conn->send_queue, get,
+	while ((pkt = tcp_slist(conn, &conn->send_queue, get,
 				struct net_pkt, next))) {
 		tcp_pkt_unref(pkt);
 	}
@@ -352,21 +360,24 @@ static int tcp_conn_unref(struct tcp *conn)
 	}
 #endif /* CONFIG_NET_TEST_PROTOCOL */
 
-	ref_count = atomic_dec(&conn->ref_count) - 1;
+	k_mutex_lock(&tcp_lock, K_FOREVER);
 
+	ref_count = atomic_dec(&conn->ref_count) - 1;
 	if (ref_count) {
 		tp_out(net_context_get_family(conn->context), conn->iface,
 		       "TP_TRACE", "event", "CONN_DELETE");
-		goto out;
+		goto unlock;
 	}
 
-	k_mutex_lock(&tcp_lock, K_FOREVER);
-
 	/* If there is any pending data, pass that to application */
 	while ((pkt = k_fifo_get(&conn->recv_data, K_NO_WAIT)) != NULL) {
-		net_context_packet_received(
-			(struct net_conn *)conn->context->conn_handler,
-			pkt, NULL, NULL, conn->recv_user_data);
+		if (net_context_packet_received(
+			    (struct net_conn *)conn->context->conn_handler,
+			    pkt, NULL, NULL, conn->recv_user_data) ==
+		    NET_DROP) {
+			/* Application is no longer there, unref the pkt */
+			tcp_pkt_unref(pkt);
+		}
 	}
 
 	if (conn->context->conn_handler) {
@@ -401,6 +412,7 @@ static int tcp_conn_unref(struct tcp *conn)
 
 	k_mem_slab_free(&tcp_conns_slab, (void **)&conn);
 
+unlock:
 	k_mutex_unlock(&tcp_lock);
 out:
 	return ref_count;
@@ -424,7 +436,7 @@ static bool tcp_send_process_no_lock(struct tcp *conn)
 	bool unref = false;
 	struct net_pkt *pkt;
 
-	pkt = tcp_slist(&conn->send_queue, peek_head,
+	pkt = tcp_slist(conn, &conn->send_queue, peek_head,
 			struct net_pkt, next);
 	if (!pkt) {
 		goto out;
@@ -450,8 +462,9 @@ static bool tcp_send_process_no_lock(struct tcp *conn)
 		bool forget = ACK == fl || PSH == fl || (ACK | PSH) == fl ||
 			RST & fl;
 
-		pkt = forget ? tcp_slist(&conn->send_queue, get, struct net_pkt,
-						next) : tcp_pkt_clone(pkt);
+		pkt = forget ? tcp_slist(conn, &conn->send_queue, get,
+					 struct net_pkt, next) :
+			tcp_pkt_clone(pkt);
 		if (!pkt) {
 			NET_ERR("net_pkt alloc failure");
 			goto out;
@@ -499,7 +512,7 @@ static void tcp_send_timer_cancel(struct tcp *conn)
 	k_delayed_work_cancel(&conn->send_timer);
 
 	{
-		struct net_pkt *pkt = tcp_slist(&conn->send_queue, get,
+		struct net_pkt *pkt = tcp_slist(conn, &conn->send_queue, get,
 						struct net_pkt, next);
 		if (pkt) {
 			NET_DBG("%s", log_strdup(tcp_th(pkt)));
@@ -679,7 +692,7 @@ static int tcp_data_get(struct tcp *conn, struct net_pkt *pkt, size_t *len)
 	}
 
 	if (conn->context->recv_cb) {
-		struct net_pkt *up = net_pkt_clone(pkt, TCP_PKT_ALLOC_TIMEOUT);
+		struct net_pkt *up = tcp_pkt_clone(pkt);
 
 		if (!up) {
 			ret = -ENOBUFS;
@@ -913,11 +926,11 @@ static int tcp_send_data(struct tcp *conn)
 		conn->unacked_len += len;
 
 		if (conn->data_mode == TCP_DATA_MODE_RESEND) {
-			net_stats_update_tcp_resent(net_pkt_iface(pkt), len);
+			net_stats_update_tcp_resent(conn->iface, len);
 			net_stats_update_tcp_seg_rexmit(conn->iface);
 		} else {
-			net_stats_update_tcp_sent(net_pkt_iface(pkt), len);
-			net_stats_update_tcp_seg_sent(net_pkt_iface(pkt));
+			net_stats_update_tcp_sent(conn->iface, len);
+			net_stats_update_tcp_seg_sent(conn->iface);
 		}
 	}
 
@@ -1058,11 +1071,24 @@ static void tcp_timewait_timeout(struct k_work *work)
 	net_context_unref(conn->context);
 }
 
+static void tcp_establish_timeout(struct tcp *conn)
+{
+	NET_DBG("Did not receive %s in %dms", "ACK", ACK_TIMEOUT_MS);
+	NET_DBG("conn: %p %s", conn, log_strdup(tcp_conn_state(conn, NULL)));
+
+	(void)tcp_conn_unref(conn);
+}
+
 static void tcp_fin_timeout(struct k_work *work)
 {
 	struct tcp *conn = CONTAINER_OF(work, struct tcp, fin_timer);
 
-	NET_DBG("Did not receive FIN in %dms", FIN_TIMEOUT_MS);
+	if (conn->state == TCP_SYN_RECEIVED) {
+		tcp_establish_timeout(conn);
+		return;
+	}
+
+	NET_DBG("Did not receive %s in %dms", "FIN", FIN_TIMEOUT_MS);
 	NET_DBG("conn: %p %s", conn, log_strdup(tcp_conn_state(conn, NULL)));
 
 	/* Extra unref from net_tcp_put() */
@@ -1083,39 +1109,45 @@ static struct tcp *tcp_conn_alloc(void)
 
 	ret = k_mem_slab_alloc(&tcp_conns_slab, (void **)&conn, K_NO_WAIT);
 	if (ret) {
+		NET_ERR("Cannot allocate slab");
 		goto out;
 	}
 
 	memset(conn, 0, sizeof(*conn));
 
+	if (CONFIG_NET_TCP_RECV_QUEUE_TIMEOUT) {
+		conn->queue_recv_data = tcp_rx_pkt_alloc(conn, 0);
+		if (conn->queue_recv_data == NULL) {
+			NET_ERR("Cannot allocate %s queue for conn %p", "recv",
+				conn);
+			goto fail;
+		}
+	}
+
+	conn->send_data = tcp_pkt_alloc(conn, 0);
+	if (conn->send_data == NULL) {
+		NET_ERR("Cannot allocate %s queue for conn %p", "send", conn);
+		goto fail;
+	}
+
 	k_mutex_init(&conn->lock);
 	k_fifo_init(&conn->recv_data);
+	k_sem_init(&conn->connect_sem, 0, UINT_MAX);
 
+	conn->in_connect = false;
 	conn->state = TCP_LISTEN;
-
 	conn->recv_win = tcp_window;
-
 	conn->seq = (IS_ENABLED(CONFIG_NET_TEST_PROTOCOL) ||
 		     IS_ENABLED(CONFIG_NET_TEST)) ? 0 : sys_rand32_get();
 
 	sys_slist_init(&conn->send_queue);
 
 	k_delayed_work_init(&conn->send_timer, tcp_send_process);
-
 	k_delayed_work_init(&conn->timewait_timer, tcp_timewait_timeout);
 	k_delayed_work_init(&conn->fin_timer, tcp_fin_timeout);
-
-	if (CONFIG_NET_TCP_RECV_QUEUE_TIMEOUT) {
-		conn->queue_recv_data = tcp_rx_pkt_alloc(conn, 0);
-	}
-
-	conn->send_data = tcp_pkt_alloc(conn, 0);
 	k_delayed_work_init(&conn->send_data_timer, tcp_resend_data);
 	k_delayed_work_init(&conn->recv_queue_timer, tcp_cleanup_recv_queue);
 
-	k_sem_init(&conn->connect_sem, 0, UINT_MAX);
-	conn->in_connect = false;
-
 	tcp_conn_ref(conn);
 
 	sys_slist_append(&tcp_conns, &conn->next);
@@ -1123,6 +1155,15 @@ out:
 	NET_DBG("conn: %p", conn);
 
 	return conn;
+
+fail:
+	if (CONFIG_NET_TCP_RECV_QUEUE_TIMEOUT && conn->queue_recv_data) {
+		tcp_pkt_unref(conn->queue_recv_data);
+		conn->queue_recv_data = NULL;
+	}
+
+	k_mem_slab_free(&tcp_conns_slab, (void **)&conn);
+	return NULL;
 }
 
 int net_tcp_get(struct net_context *context)
@@ -1535,6 +1576,11 @@ next_state:
 			tcp_out(conn, SYN | ACK);
 			conn_seq(conn, + 1);
 			next = TCP_SYN_RECEIVED;
+
+			/* Close the connection if we do not receive ACK on time.
+			 */
+			k_delayed_work_submit(&conn->establish_timer,
+					      ACK_TIMEOUT);
 		} else {
 			tcp_out(conn, SYN);
 			conn_seq(conn, + 1);
@@ -1544,6 +1590,7 @@ next_state:
 	case TCP_SYN_RECEIVED:
 		if (FL(&fl, &, ACK, th_ack(th) == conn->seq &&
 				th_seq(th) == conn->ack)) {
+			k_delayed_work_cancel(&conn->establish_timer);
 			tcp_send_timer_cancel(conn);
 			next = TCP_ESTABLISHED;
 			net_context_set_state(conn->context,
@@ -1773,8 +1820,12 @@ next_state:
 	 */
 	while (conn_handler && atomic_get(&conn->ref_count) > 0 &&
 	       (recv_pkt = k_fifo_get(recv_data_fifo, K_NO_WAIT)) != NULL) {
-		net_context_packet_received(conn_handler, recv_pkt, NULL, NULL,
-					    recv_user_data);
+		if (net_context_packet_received(conn_handler, recv_pkt, NULL,
+						NULL, recv_user_data) ==
+		    NET_DROP) {
+			/* Application is no longer there, unref the pkt */
+			tcp_pkt_unref(recv_pkt);
+		}
 	}
 
 	/* We must not try to unref the connection while having a connection
diff --git a/subsys/net/ip/tcp2_priv.h b/subsys/net/ip/tcp2_priv.h
index 94bb0ac35d..51257e7a86 100644
--- a/subsys/net/ip/tcp2_priv.h
+++ b/subsys/net/ip/tcp2_priv.h
@@ -20,12 +20,16 @@
 #define th_flags(_x) UNALIGNED_GET(&(_x)->th_flags)
 #define th_win(_x) UNALIGNED_GET(&(_x)->th_win)
 
-#define tcp_slist(_slist, _op, _type, _link)				\
+#define tcp_slist(_conn, _slist, _op, _type, _link)			\
 ({									\
+	k_mutex_lock(&conn->lock, K_FOREVER);				\
+									\
 	sys_snode_t *_node = sys_slist_##_op(_slist);			\
 									\
 	_type * _x = _node ? CONTAINER_OF(_node, _type, _link) : NULL;	\
 									\
+	k_mutex_unlock(&conn->lock);					\
+									\
 	_x;								\
 })
 
@@ -223,7 +227,14 @@ struct tcp { /* TCP connection */
 	struct k_delayed_work recv_queue_timer;
 	struct k_delayed_work send_data_timer;
 	struct k_delayed_work timewait_timer;
-	struct k_delayed_work fin_timer;
+	union {
+		/* Because FIN and establish timers are never happening
+		 * at the same time, share the timer between them to
+		 * save memory.
+		 */
+		struct k_delayed_work fin_timer;
+		struct k_delayed_work establish_timer;
+	};
 	union tcp_endpoint src;
 	union tcp_endpoint dst;
 	size_t send_data_total;
diff --git a/subsys/power/Kconfig b/subsys/power/Kconfig
index 84e180ffca..c6af5d6941 100644
--- a/subsys/power/Kconfig
+++ b/subsys/power/Kconfig
@@ -13,7 +13,7 @@ config SYS_POWER_MANAGEMENT
 menuconfig PM
 	bool "System Power management"
 	select TICKLESS_IDLE
-	depends on SYS_CLOCK_EXISTS && !SOC_NRF5340_CPUNET_QKAA
+	depends on SYS_CLOCK_EXISTS && !HAS_NO_SYS_PM
 	help
 	  This option enables the board to implement extra power management
 	  policies whenever the kernel becomes idle. The kernel informs the
@@ -52,6 +52,14 @@ source "subsys/logging/Kconfig.template.log_config"
 
 endif # PM
 
+config HAS_NO_SYS_PM
+	bool
+	help
+	  This option blocks selection of PM.  It can be selected in SOC
+	  targets where system power management is not supported, for example
+	  on support core of a multi-core device where SoC power management is
+	  the responsibility of a different core.
+
 config PM_DEVICE
 	bool "Device power management"
 	help
diff --git a/subsys/settings/src/settings_file.c b/subsys/settings/src/settings_file.c
index 89ad2608f8..8291cbd6f4 100644
--- a/subsys/settings/src/settings_file.c
+++ b/subsys/settings/src/settings_file.c
@@ -123,6 +123,8 @@ static int settings_file_load_priv(struct settings_store *cs, line_load_cb cb,
 
 	lines = 0;
 
+	fs_file_t_init(&file);
+
 	rc = fs_open(&file, cf->cf_name, FS_O_CREATE | FS_O_RDWR);
 	if (rc != 0) {
 		return -EINVAL;
@@ -240,6 +242,9 @@ static int settings_file_save_and_compress(struct settings_file *cf,
 	size_t new_name_len;
 	size_t val1_off;
 
+	fs_file_t_init(&rf);
+	fs_file_t_init(&wf);
+
 	if (fs_open(&rf, cf->cf_name, FS_O_CREATE | FS_O_RDWR) != 0) {
 		return -ENOEXEC;
 	}
@@ -360,7 +365,7 @@ static int settings_file_save_priv(struct settings_store *cs, const char *name,
 {
 	struct settings_file *cf = (struct settings_file *)cs;
 	struct line_entry_ctx entry_ctx;
-	struct fs_file_t  file;
+	struct fs_file_t file;
 	int rc2;
 	int rc;
 
@@ -368,6 +373,8 @@ static int settings_file_save_priv(struct settings_store *cs, const char *name,
 		return -EINVAL;
 	}
 
+	fs_file_t_init(&file);
+
 	if (cf->cf_maxlines && (cf->cf_lines + 1 >= cf->cf_maxlines)) {
 		/*
 		 * Compress before config file size exceeds
diff --git a/tests/kernel/mem_protect/mem_protect/src/mem_domain.c b/tests/kernel/mem_protect/mem_protect/src/mem_domain.c
index 4ed1f76ca5..141f312975 100644
--- a/tests/kernel/mem_protect/mem_protect/src/mem_domain.c
+++ b/tests/kernel/mem_protect/mem_protect/src/mem_domain.c
@@ -298,7 +298,7 @@ static void spin_entry(void *p1, void *p2, void *p3)
  * @see k_mem_domain_add_thread()
  */
 
-#ifdef CONFIG_SMP
+#if CONFIG_MP_NUM_CPUS > 1
 #define PRIO	K_PRIO_COOP(0)
 #else
 #define PRIO	K_PRIO_PREEMPT(1)
diff --git a/tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c b/tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c
index e0abea2f1b..3fbde46ed1 100644
--- a/tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c
+++ b/tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c
@@ -404,8 +404,11 @@ void test_msgq_empty(void)
 	 */
 	ret = k_msgq_cleanup(&msgq1);
 	zassert_equal(ret, -EBUSY, NULL);
+
 	/* put a message to wake that getting thread */
-	k_msgq_put(&msgq1, &data[0], K_NO_WAIT);
+	ret = k_msgq_put(&msgq1, &data[0], K_NO_WAIT);
+	zassert_equal(ret, 0, NULL);
+
 	k_thread_abort(tid);
 }
 
@@ -429,8 +432,9 @@ void test_msgq_full(void)
 	ret = k_sem_init(&end_sema, 0, 1);
 	zassert_equal(ret, 0, NULL);
 
+	ret = k_msgq_put(&msgq1, &data[0], K_NO_WAIT);
+	zassert_equal(ret, 0, NULL);
 
-	k_msgq_put(&msgq1, &data[0], K_NO_WAIT);
 	k_tid_t tid = k_thread_create(&tdata2, tstack2, STACK_SIZE,
 					put_full_entry, &msgq1, NULL,
 					NULL, pri, 0, K_NO_WAIT);
diff --git a/tests/kernel/profiling/profiling_api/testcase.yaml b/tests/kernel/profiling/profiling_api/testcase.yaml
index 77bb04c45c..1d41bcaca8 100644
--- a/tests/kernel/profiling/profiling_api/testcase.yaml
+++ b/tests/kernel/profiling/profiling_api/testcase.yaml
@@ -1,5 +1,7 @@
 tests:
   kernel.common.profiling:
     arch_exclude: nios2
-    platform_exclude: em_starterkit litex_vexriscv rv32m1_vega_zero_riscy rv32m1_vega_ri5cy
+    platform_exclude: em_starterkit
+      litex_vexriscv rv32m1_vega_zero_riscy rv32m1_vega_ri5cy
+      nrf5340dk_nrf5340_cpunet nrf5340pdk_nrf5340_cpunet
     tags: kernel
diff --git a/tests/kernel/tickless/tickless_concept/testcase.yaml b/tests/kernel/tickless/tickless_concept/testcase.yaml
index b027324124..76ecc8686e 100644
--- a/tests/kernel/tickless/tickless_concept/testcase.yaml
+++ b/tests/kernel/tickless/tickless_concept/testcase.yaml
@@ -3,5 +3,7 @@ tests:
     arch_exclude: nios2
     # FIXME: This test fails sporadically on all QEMU platforms, but fails
     # consistently when coverage is enabled. Disable until 14173 is fixed.
-    platform_exclude: qemu_x86_coverage litex_vexriscv rv32m1_vega_zero_riscy rv32m1_vega_ri5cy
+    platform_exclude: qemu_x86_coverage
+      litex_vexriscv rv32m1_vega_zero_riscy rv32m1_vega_ri5cy
+      nrf5340dk_nrf5340_cpunet nrf5340pdk_nrf5340_cpunet
     tags: kernel
diff --git a/tests/kernel/timer/timer_api/testcase.yaml b/tests/kernel/timer/timer_api/testcase.yaml
index 89763713a2..184f6ffacc 100644
--- a/tests/kernel/timer/timer_api/testcase.yaml
+++ b/tests/kernel/timer/timer_api/testcase.yaml
@@ -5,5 +5,7 @@ tests:
   kernel.timer.tickless:
     extra_args: CONF_FILE="prj_tickless.conf"
     arch_exclude: nios2 posix
-    platform_exclude: qemu_x86_coverage litex_vexriscv rv32m1_vega_zero_riscy rv32m1_vega_ri5cy
+    platform_exclude: qemu_x86_coverage
+      litex_vexriscv rv32m1_vega_zero_riscy rv32m1_vega_ri5cy
+      nrf5340dk_nrf5340_cpunet nrf5340pdk_nrf5340_cpunet
     tags: kernel timer userspace
diff --git a/tests/lib/cbprintf_fp/testcase.yaml b/tests/lib/cbprintf_fp/testcase.yaml
index 48b4d0d442..7a5c950698 100644
--- a/tests/lib/cbprintf_fp/testcase.yaml
+++ b/tests/lib/cbprintf_fp/testcase.yaml
@@ -24,6 +24,7 @@ tests:
         - "Hello with printf"
         - "Complete"
   lib.cbprintf_fp.printf_nl:
+    filter: TOOLCHAIN_HAS_NEWLIB == 1
     extra_configs:
       - CONFIG_APP_FORMATTER_PRINTF=y
       - CONFIG_NEWLIB_LIBC=y
@@ -43,6 +44,7 @@ tests:
         - "Hello with printfcb"
         - "Complete"
   lib.cbprintf_fp.printfcb_nl:
+    filter: TOOLCHAIN_HAS_NEWLIB == 1
     extra_configs:
       - CONFIG_APP_FORMATTER_PRINTFCB=y
       - CONFIG_NEWLIB_LIBC=y
diff --git a/tests/lib/gui/lvgl/src/main.c b/tests/lib/gui/lvgl/src/main.c
index 30b17c2a0c..e176b83651 100644
--- a/tests/lib/gui/lvgl/src/main.c
+++ b/tests/lib/gui/lvgl/src/main.c
@@ -91,6 +91,7 @@ void setup_fs(void)
 		return;
 	}
 
+	fs_file_t_init(&img);
 	ret = fs_open(&img, IMG_FILE_PATH, FS_O_CREATE | FS_O_WRITE);
 	if (ret < 0) {
 		TC_PRINT("Failed to open image file: %d\n", ret);
diff --git a/tests/subsys/fs/common/test_fs_open_flags.c b/tests/subsys/fs/common/test_fs_open_flags.c
index 3afc274ce3..9d17b0d677 100644
--- a/tests/subsys/fs/common/test_fs_open_flags.c
+++ b/tests/subsys/fs/common/test_fs_open_flags.c
@@ -141,6 +141,8 @@ void test_fs_open_flags(void)
 	};
 	int block = 1;
 
+	fs_file_t_init(&ts.file);
+
 	ZBEGIN("Attempt open non-existent");
 	ZOPEN(&ts, 0, -ENOENT);
 	ZOPEN(&ts, FS_O_WRITE, -ENOENT);
diff --git a/tests/subsys/fs/fat_fs_api/src/main.c b/tests/subsys/fs/fat_fs_api/src/main.c
index ab9d34b12a..b1c066a3cd 100644
--- a/tests/subsys/fs/fat_fs_api/src/main.c
+++ b/tests/subsys/fs/fat_fs_api/src/main.c
@@ -11,6 +11,8 @@ const char *test_fs_open_flags_file_path =  FATFS_MNTP"/the_file.txt";
 
 void test_main(void)
 {
+	fs_file_t_init(&filep);
+
 	ztest_test_suite(fat_fs_basic_test,
 			 ztest_unit_test(test_fat_mount),
 			 ztest_unit_test(test_fat_file),
diff --git a/tests/subsys/fs/fat_fs_api/src/test_fat_rd_only_mount.c b/tests/subsys/fs/fat_fs_api/src/test_fat_rd_only_mount.c
index 1925b6c0ff..e83168a89c 100644
--- a/tests/subsys/fs/fat_fs_api/src/test_fat_rd_only_mount.c
+++ b/tests/subsys/fs/fat_fs_api/src/test_fat_rd_only_mount.c
@@ -22,6 +22,7 @@ static void test_prepare(void)
 {
 	struct fs_file_t fs;
 
+	fs_file_t_init(&fs);
 	zassert_equal(fs_mount(&fatfs_mnt), 0, NULL);
 	zassert_equal(fs_open(&fs, "/NAND:/testfile.txt", FS_O_CREATE),
 		      0, NULL);
@@ -38,6 +39,8 @@ static void test_ops_on_rd(void)
 {
 	struct fs_file_t fs;
 	int ret;
+
+	fs_file_t_init(&fs);
 	/* Check fs operation on volume mounted with FS_MOUNT_FLAG_READ_ONLY */
 	fatfs_mnt.flags = FS_MOUNT_FLAG_READ_ONLY;
 	TC_PRINT("Mount as read-only\n");
diff --git a/tests/subsys/fs/fat_fs_api/src/test_fat_rename.c b/tests/subsys/fs/fat_fs_api/src/test_fat_rename.c
index 34cafea64a..280835a683 100644
--- a/tests/subsys/fs/fat_fs_api/src/test_fat_rename.c
+++ b/tests/subsys/fs/fat_fs_api/src/test_fat_rename.c
@@ -25,6 +25,8 @@ static int create_file(const char *path)
 {
 	struct fs_file_t fp;
 	int res = 0;
+
+	fs_file_t_init(&fp);
 	if (!check_file_dir_exists(path)) {
 		res = fs_open(&fp, path, FS_O_CREATE | FS_O_RDWR);
 		if (!res) {
diff --git a/tests/subsys/fs/fat_fs_dual_drive/src/main.c b/tests/subsys/fs/fat_fs_dual_drive/src/main.c
index 90e78d26b8..30837fcde6 100644
--- a/tests/subsys/fs/fat_fs_dual_drive/src/main.c
+++ b/tests/subsys/fs/fat_fs_dual_drive/src/main.c
@@ -15,6 +15,8 @@
 
 void test_main(void)
 {
+	fs_file_t_init(&filep);
+
 	ztest_test_suite(fat_fs_basic_test,
 			 ztest_unit_test(test_fat_mount),
 			 ztest_unit_test(test_fat_file),
diff --git a/tests/subsys/fs/fs_api/src/main.c b/tests/subsys/fs/fs_api/src/main.c
index 0527eb145a..5bd1847c44 100644
--- a/tests/subsys/fs/fs_api/src/main.c
+++ b/tests/subsys/fs/fs_api/src/main.c
@@ -72,6 +72,7 @@ void test_main(void)
 			 ztest_unit_test_setup_teardown(test_mount,
 							fs_setup,
 							dummy_teardown),
+			 ztest_unit_test(test_fs_file_t_init),
 			 ztest_unit_test(test_file_statvfs),
 			 ztest_unit_test(test_mkdir),
 			 ztest_unit_test(test_opendir),
diff --git a/tests/subsys/fs/fs_api/src/test_fs.h b/tests/subsys/fs/fs_api/src/test_fs.h
index f7ecb0aa90..2e423e4652 100644
--- a/tests/subsys/fs/fs_api/src/test_fs.h
+++ b/tests/subsys/fs/fs_api/src/test_fs.h
@@ -32,6 +32,7 @@ struct test_fs_data {
 	int reserve;
 };
 
+void test_fs_file_t_init(void);
 void test_fs_register(void);
 void test_mount(void);
 void test_file_statvfs(void);
diff --git a/tests/subsys/fs/fs_api/src/test_fs_dir_file.c b/tests/subsys/fs/fs_api/src/test_fs_dir_file.c
index bfdd38f3cc..50301042e8 100644
--- a/tests/subsys/fs/fs_api/src/test_fs_dir_file.c
+++ b/tests/subsys/fs/fs_api/src/test_fs_dir_file.c
@@ -78,6 +78,21 @@ static struct fs_file_t filep;
 static struct fs_file_t err_filep;
 static const char test_str[] = "hello world!";
 
+/**
+ * @brief Test fs_file_t_init initializer
+ */
+void test_fs_file_t_init(void)
+{
+	struct fs_file_t fst;
+
+	memset(&fst, 0xff, sizeof(fst));
+
+	fs_file_t_init(&fst);
+	zassert_equal(fst.mp, NULL, "Expected to be initialized to NULL");
+	zassert_equal(fst.filep, NULL, "Expected to be initialized to NULL");
+	zassert_equal(fst.flags, 0, "Expected to be initialized to 0");
+}
+
 /**
  * @brief Test mount interface of filesystem
  *
@@ -396,6 +411,7 @@ void test_file_open(void)
 	int ret;
 
 	TC_PRINT("\nOpen tests:\n");
+	fs_file_t_init(&filep);
 
 	TC_PRINT("\nOpen a file without a path\n");
 	ret = fs_open(&filep, NULL, FS_O_READ);
@@ -420,6 +436,10 @@ void test_file_open(void)
 	ret = fs_open(&filep, TEST_FILE, FS_O_READ);
 	zassert_equal(ret, 0, "Fail to open file");
 
+	TC_PRINT("\nDouble-open\n");
+	ret = fs_open(&filep, TEST_FILE, FS_O_READ);
+	zassert_equal(ret, -EBUSY, "Expected -EBUSY, got %d", ret);
+
 	TC_PRINT("\nReopen the same file");
 	ret = fs_open(&filep, TEST_FILE, FS_O_READ);
 	zassert_not_equal(ret, 0, "Reopen an opend file");
@@ -435,7 +455,7 @@ static int _test_file_write(void)
 	TC_PRINT("\nWrite tests:\n");
 
 	TC_PRINT("Write to an unopened file\n");
-	err_filep.mp = NULL;
+	fs_file_t_init(&err_filep);
 	brw = fs_write(&err_filep, (char *)test_str, strlen(test_str));
 	if (brw >= 0) {
 		return TC_FAIL;
@@ -500,7 +520,7 @@ static int _test_file_sync(void)
 	TC_PRINT("\nSync tests:\n");
 
 	TC_PRINT("sync an unopened file\n");
-	err_filep.mp = NULL;
+	fs_file_t_init(&err_filep);
 	ret = fs_sync(&err_filep);
 	if (!ret) {
 		return TC_FAIL;
@@ -513,6 +533,7 @@ static int _test_file_sync(void)
 		return TC_FAIL;
 	}
 
+	fs_file_t_init(&filep);
 	ret = fs_open(&filep, TEST_FILE, FS_O_RDWR);
 
 	for (;;) {
@@ -578,7 +599,7 @@ void test_file_read(void)
 	TC_PRINT("\nRead tests:\n");
 
 	TC_PRINT("Read an unopened file\n");
-	err_filep.mp = NULL;
+	fs_file_t_init(&err_filep);
 	brw = fs_read(&err_filep, read_buff, sz);
 	zassert_false(brw >= 0, "Can't read an unopened file");
 
@@ -637,7 +658,7 @@ static int _test_file_truncate(void)
 	TC_PRINT("\nTruncate tests: max file size is 128byte\n");
 
 	TC_PRINT("\nTruncate, seek, tell an unopened file\n");
-	err_filep.mp = NULL;
+	fs_file_t_init(&err_filep);
 	ret = fs_truncate(&err_filep, 256);
 	if (!ret) {
 		return TC_FAIL;
@@ -798,7 +819,7 @@ void test_file_close(void)
 	TC_PRINT("\nClose tests:\n");
 
 	TC_PRINT("Close an unopened file\n");
-	err_filep.mp = NULL;
+	fs_file_t_init(&err_filep);
 	ret = fs_close(&err_filep);
 	zassert_equal(ret, 0, "Should close an unopened file");
 
@@ -810,6 +831,12 @@ void test_file_close(void)
 	ret = fs_close(&filep);
 	zassert_equal(ret, 0, "Fail to close file");
 
+	TC_PRINT("Reuse fs_file_t from closed file");
+	ret = fs_open(&filep, TEST_FILE, FS_O_READ);
+	zassert_equal(ret, 0, "Expected open to succeed, got %d", ret);
+	ret = fs_close(&filep);
+	zassert_equal(ret, 0, "Expected close to succeed, got %d", ret);
+
 	TC_PRINT("\nClose a closed file:\n");
 	filep.mp = &test_fs_mnt_1;
 	ret = fs_close(&filep);
diff --git a/tests/subsys/fs/fs_api/src/test_fs_mount_flags.c b/tests/subsys/fs/fs_api/src/test_fs_mount_flags.c
index 0139917c76..92b1ed4009 100644
--- a/tests/subsys/fs/fs_api/src/test_fs_mount_flags.c
+++ b/tests/subsys/fs/fs_api/src/test_fs_mount_flags.c
@@ -18,7 +18,9 @@ static struct fs_mount_t mp = {
 void test_mount_flags(void)
 {
 	int ret = 0;
-	struct fs_file_t fs = { 0 };
+	struct fs_file_t fs;
+
+	fs_file_t_init(&fs);
 
 	/* Format volume and add some files/dirs to check read-only flag */
 	mp.flags = 0;
diff --git a/tests/subsys/fs/littlefs/src/test_lfs_basic.c b/tests/subsys/fs/littlefs/src/test_lfs_basic.c
index 5cfeeeb1e5..6fa51418fb 100644
--- a/tests/subsys/fs/littlefs/src/test_lfs_basic.c
+++ b/tests/subsys/fs/littlefs/src/test_lfs_basic.c
@@ -77,6 +77,7 @@ static int create_write_hello(const struct fs_mount_t *mp)
 	struct testfs_path path;
 	struct fs_file_t file;
 
+	fs_file_t_init(&file);
 	TC_PRINT("creating and writing file\n");
 
 	zassert_equal(fs_open(&file,
@@ -144,6 +145,7 @@ static int verify_hello(const struct fs_mount_t *mp)
 	struct testfs_path path;
 	struct fs_file_t file;
 
+	fs_file_t_init(&file);
 	TC_PRINT("opening and verifying file\n");
 
 	zassert_equal(fs_open(&file,
@@ -175,6 +177,7 @@ static int seek_within_hello(const struct fs_mount_t *mp)
 	struct testfs_path path;
 	struct fs_file_t file;
 
+	fs_file_t_init(&file);
 	TC_PRINT("seek and tell in file\n");
 
 	zassert_equal(fs_open(&file,
@@ -242,6 +245,7 @@ static int truncate_hello(const struct fs_mount_t *mp)
 	struct testfs_path path;
 	struct fs_file_t file;
 
+	fs_file_t_init(&file);
 	TC_PRINT("truncate in file\n");
 
 	zassert_equal(fs_open(&file,
@@ -332,6 +336,7 @@ static int sync_goodbye(const struct fs_mount_t *mp)
 	struct testfs_path path;
 	struct fs_file_t file;
 
+	fs_file_t_init(&file);
 	TC_PRINT("sync goodbye\n");
 
 	zassert_equal(fs_open(&file,
@@ -395,6 +400,7 @@ static int verify_goodbye(const struct fs_mount_t *mp)
 	struct testfs_path path;
 	struct fs_file_t file;
 
+	fs_file_t_init(&file);
 	TC_PRINT("verify goodbye\n");
 
 	zassert_equal(fs_open(&file,
diff --git a/tests/subsys/fs/littlefs/src/test_lfs_dirops.c b/tests/subsys/fs/littlefs/src/test_lfs_dirops.c
index aaaefa58e0..4f3c7e13ee 100644
--- a/tests/subsys/fs/littlefs/src/test_lfs_dirops.c
+++ b/tests/subsys/fs/littlefs/src/test_lfs_dirops.c
@@ -62,6 +62,7 @@ static int check_mkdir(struct fs_mount_t *mp)
 	struct fs_file_t file;
 	struct testfs_path fpath;
 
+	fs_file_t_init(&file);
 	zassert_equal(fs_open(&file,
 			      testfs_path_extend(testfs_path_copy(&fpath,
 								  &dpath),
diff --git a/tests/subsys/fs/littlefs/src/test_lfs_perf.c b/tests/subsys/fs/littlefs/src/test_lfs_perf.c
index 456159a298..080b96035d 100644
--- a/tests/subsys/fs/littlefs/src/test_lfs_perf.c
+++ b/tests/subsys/fs/littlefs/src/test_lfs_perf.c
@@ -36,6 +36,7 @@ static int write_read(const char *tag,
 	int rc;
 	int rv = TC_FAIL;
 
+	fs_file_t_init(&file);
 	TC_PRINT("clearing %s for %s write/read test\n",
 		 mp->mnt_point, tag);
 	if (testfs_lfs_wipe_partition(mp) != TC_PASS) {
diff --git a/tests/subsys/fs/littlefs/src/testfs_mount_flags.c b/tests/subsys/fs/littlefs/src/testfs_mount_flags.c
index 5e87c2eb50..c0693c1c89 100644
--- a/tests/subsys/fs/littlefs/src/testfs_mount_flags.c
+++ b/tests/subsys/fs/littlefs/src/testfs_mount_flags.c
@@ -26,6 +26,7 @@ void test_fs_mount_flags(void)
 	int ret = 0;
 	struct fs_file_t fs;
 
+	fs_file_t_init(&fs);
 	cleanup(mp);
 
 	/* Test FS_MOUNT_FLAG_NO_FORMAT flag */
diff --git a/tests/subsys/fs/littlefs/src/testfs_util.c b/tests/subsys/fs/littlefs/src/testfs_util.c
index d2b5233c3c..5067284852 100644
--- a/tests/subsys/fs/littlefs/src/testfs_util.c
+++ b/tests/subsys/fs/littlefs/src/testfs_util.c
@@ -232,6 +232,7 @@ int testfs_build(struct testfs_path *root,
 		if (TESTFS_BCMD_IS_FILE(cp)) {
 			struct fs_file_t file;
 
+			fs_file_t_init(&file);
 			rc = fs_open(&file,
 				     testfs_path_extend(root,
 							cp->name,
@@ -296,6 +297,7 @@ static int check_layout_entry(struct testfs_path *pp,
 	if (statp->type == FS_DIR_ENTRY_FILE) {
 		struct fs_file_t file;
 
+		fs_file_t_init(&file);
 		rc = fs_open(&file, pp->path, FS_O_CREATE | FS_O_RDWR);
 		if (rc < 0) {
 			TC_PRINT("%s: content check open failed: %d\n",
diff --git a/tests/subsys/fs/multi-fs/src/test_common_dir.c b/tests/subsys/fs/multi-fs/src/test_common_dir.c
index d9f0da5c38..afdf960df3 100644
--- a/tests/subsys/fs/multi-fs/src/test_common_dir.c
+++ b/tests/subsys/fs/multi-fs/src/test_common_dir.c
@@ -19,6 +19,7 @@ int test_mkdir(const char *dir_path, const char *file)
 	struct fs_file_t filep;
 	char file_path[PATH_MAX] = { 0 };
 
+	fs_file_t_init(&filep);
 	res = sprintf(file_path, "%s/%s", dir_path, file);
 	__ASSERT_NO_MSG(res < sizeof(file_path));
 
@@ -48,6 +49,7 @@ int test_mkdir(const char *dir_path, const char *file)
 	TC_PRINT("Testing write to file %s\n", file_path);
 	res = test_file_write(&filep, "NOTHING");
 	if (res) {
+		fs_close(&filep);
 		return res;
 	}
 
diff --git a/tests/subsys/fs/multi-fs/src/test_fat_file.c b/tests/subsys/fs/multi-fs/src/test_fat_file.c
index 3658b10b68..1517638fdc 100644
--- a/tests/subsys/fs/multi-fs/src/test_fat_file.c
+++ b/tests/subsys/fs/multi-fs/src/test_fat_file.c
@@ -14,6 +14,7 @@ static const char *test_str = "Hello world FAT";
 
 void test_fat_open(void)
 {
+	fs_file_t_init(&test_file);
 	zassert_true(test_file_open(&test_file, TEST_FILE_PATH) == TC_PASS,
 		NULL);
 }
diff --git a/tests/subsys/fs/multi-fs/src/test_littlefs_file.c b/tests/subsys/fs/multi-fs/src/test_littlefs_file.c
index b57293a60b..ccdae8ca8a 100644
--- a/tests/subsys/fs/multi-fs/src/test_littlefs_file.c
+++ b/tests/subsys/fs/multi-fs/src/test_littlefs_file.c
@@ -14,6 +14,7 @@ static const char *test_str = "Hello world LITTLEFS";
 
 void test_littlefs_open(void)
 {
+	fs_file_t_init(&test_file);
 	zassert_true(test_file_open(&test_file, TEST_FILE_PATH) == TC_PASS,
 		NULL);
 }
diff --git a/tests/subsys/power/power_mgmt/testcase.yaml b/tests/subsys/power/power_mgmt/testcase.yaml
index dde4d74e18..81ed406a88 100644
--- a/tests/subsys/power/power_mgmt/testcase.yaml
+++ b/tests/subsys/power/power_mgmt/testcase.yaml
@@ -2,8 +2,11 @@ tests:
   subsys.power.device_pm:
     # arch_irq_unlock(0) can't work correctly on these arch
     arch_exclude: arc xtensa
-    # When CONFIG_TICKLESS_IDLE enable, these platforms don't provide timer driver
+    # When CONFIG_TICKLESS_IDLE enable, some of these platforms don't
+    # provide a timer driver.  Other platforms are excluded because
+    # they lack some other required feature.
     platform_exclude: rv32m1_vega_ri5cy rv32m1_vega_zero_riscy litex_vexriscv
+       nrf5340dk_nrf5340_cpunet nrf5340pdk_nrf5340_cpunet
     integration_platforms:
       - qemu_x86
       - mps2_an385
diff --git a/tests/subsys/power/power_mgmt_soc/prj.conf b/tests/subsys/power/power_mgmt_soc/prj.conf
index 9133ac9c15..2d3ce58717 100644
--- a/tests/subsys/power/power_mgmt_soc/prj.conf
+++ b/tests/subsys/power/power_mgmt_soc/prj.conf
@@ -3,3 +3,4 @@ CONFIG_ZTEST=y
 CONFIG_PM=y
 CONFIG_THREAD_NAME=y
 CONFIG_PM_DEBUG=y
+CONFIG_IDLE_STACK_SIZE=640
diff --git a/tests/subsys/settings/fs/src/settings_test_fs.c b/tests/subsys/settings/fs/src/settings_test_fs.c
index a095fdabfe..e1e3523337 100644
--- a/tests/subsys/settings/fs/src/settings_test_fs.c
+++ b/tests/subsys/settings/fs/src/settings_test_fs.c
@@ -151,6 +151,8 @@ int fsutil_read_file(const char *path, off_t offset, size_t len, void *dst,
 	int rc;
 	ssize_t r_len = 0;
 
+	fs_file_t_init(&file);
+
 	rc = fs_open(&file, path, FS_O_CREATE | FS_O_RDWR);
 	if (rc != 0) {
 		return rc;
@@ -172,6 +174,8 @@ int fsutil_write_file(const char *path, const void *data, size_t len)
 	struct fs_file_t file;
 	int rc;
 
+	fs_file_t_init(&file);
+
 	rc = fs_open(&file, path, FS_O_CREATE | FS_O_RDWR);
 	if (rc != 0) {
 		return rc;
* Unmerged path tests/ztest/error_hook/src/main.c

```
