### PR TITLE
logging: Fix corruption in log panic when scheduler was active

### LINKED ISSUE #16931: logging: Assertion when in panic mode
**Describe the bug**
`ASSERTION FAIL [out_ctx->control_block->offset <= out_ctx->size] @ ./subsys/logging/log_output.c:102` occurrs after using `LOG_PANIC()` in multithreaded application.

**To Reproduce**
1. Use multiple threads (at least one should be **preemptive**). Threads should log something.
2. Put logger in panic mode.
3. Observe assert caused by thread switching in `out_func` (`log_output.c`).

Adding `k_sched_lock()` and `k_sched_unlock()` around `out_func `content makes everything work fine - problem is probably caused by thread switching after adding to `out_ctx ->buf ` and before `log_output_flush(out_ctx)`.

**Expected behavior**
`LOG_PANIC()` should work without assert.

**Impact**
Cannot use `LOG_PANIC()` in application.

**Additional context**
Tested using log RTT backend (`LOG_BACKEND_RTT`, `LOG_BACKEND_RTT_MODE_DROP`) on nrf52_pca10040.
Zephyr commit hash: 7e64ac737daead12d2dbdda5daec04188243a81c

### PR DESCRIPTION
**Pull request by nordic-krch**
Logger had false assumption that once log_panic is called then
context switch will never occur and was not protecting against
reentrancy in panic mode. Added interrupt locking when accessing
unprotected part.

Fixes #16931.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

File: subsys/logging/log_core.c [hunk 1]
```diff
@@ -204,7 +204,9 @@ static inline void msg_finalize(struct log_msg *msg,
 	irq_unlock(key);
 
 	if (panic_mode) {
+		key = irq_lock();
```
Comment (pdunaj) [inline subsys/logging/log_core.c]: Will it work if backend is interrupt driven? It can happen that locked irqs will deadlock the backend.

Comment (nordic-krch) [reply subsys/logging/log_core.c]: when panic in log is entered then all backends are informed and they are obliged to swtich to irqless mode or shut down.

**Review by pdunaj — APPROVED** [review]

**Comment by ioannisg** [comment]
@MarekPieta pls, add your review

**Review by MarekPieta — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
Although overuse of lock/unlock is not favorable, this particular case is under panic mode, so this won't, hopefully, happen all the time.

**Comment by ioannisg** [comment]
@nashif @andyross pls, check this one

File: subsys/logging/log_core.c [hunk 2]
```diff
@@ -530,7 +532,7 @@ void log_panic(void)
 
 	if (!IS_ENABLED(CONFIG_LOG_IMMEDIATE)) {
 		/* Flush */
-		while (log_process(false) == true) {
+		while (log_process(false)) {
```
Comment (ioannisg) [inline subsys/logging/log_core.c]: This change is not reflected in the commit message; why was this required?

Comment (MarekPieta) [reply subsys/logging/log_core.c]: In general, comparing `variable == true` is not good practice. Identifier `true` is one specific value. C assumes that any non-zero value is true.

Comment (nordic-krch) [reply subsys/logging/log_core.c]: yes, that was suggested by @MarekPieta

Comment (ioannisg) [reply subsys/logging/log_core.c]: @MarekPieta I was, interested in knowing why this change was included in this patch, without being related to the actual bug-fix, and without being reflected in the commit message :)

But since you bring this up, here's the API declaration:

```
/**
 * @brief Process one pending log message.
 *
 * @param bypass If true message is released without being processed.
 *
 * @retval true There is more messages pending to be processed.
 * @retval false No messages pending.
 */
bool log_process(bool bypass);
```
The function is supposed to return false, or true, so checking explicitly for true, here, does not seem to be a problem IMHO.

Comment (nordic-krch) [reply subsys/logging/log_core.c]: @ioannisg i've removed that change. PR contains only changes related to commit message.

**Comment by nordic-krch** [comment]
@ioannisg maybe you could merge this one?

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg maybe you could merge this one?

Right @nordic-krch, this needs to go in; fixes a medium-prio bug. But, now, after looking at it once more, I am a bit concerned; you "protect" log_process() inside irq_lock(), irq_unlock(), however, log_process() is calling irq_unlock() inside its body. This is already confusing enough, but, to my understanding, it might also be "dangerious" as it is cancelling the external irq locking. What do you think?

**Comment by nordic-krch** [comment]
@ioannisg `log_process` has unlock-lock pair to protect accessing the list with log messages. It's a pair so it's rather not dangerous.

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg `log_process` has unlock-lock pair to protect accessing the list with log messages. It's a pair so it's rather not dangerous.

Right, my bad, it is not dangerous; the internal lock returns already a set BASEPRI. So it's just (a bit) confusing
