### PR TITLE
manifest: hostap: Enable server certificate verification

### LINKED ISSUE #88697: hostap: tls: Implement server name verification
**Describe the bug**

MbedTLS 3.6.3 now mandates servername checking unless explicitly disabled and this causes TLS handshake to fail, see https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.3.

A temporary WAR https://github.com/zephyrproject-rtos/zephyr/pull/88679 to disable this has been raised, but this is a security loophole, we need to implement this in the hostap. Which already supports https://github.com/zephyrproject-rtos/hostap/blob/main/wpa_supplicant/wpa_supplicant.conf#L1329 (`domain_suffix_match`) option and this needs to be plumbed down till MbedTLS.

**To Reproduce**

1. Build and Run `wifi-enterprise` snippet in `samples/net/wifi/shell` on a nRF7002DK board
2. Test EAP-TLS
3. Handshake fails without the above PR (WAR)

**Expected behavior**
TLS should pass but also in a secure way (not with the WAR)

**Impact**
Security vulnerability.

**Logs and console output**
NA

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: Latest main 86293ebe114

**Additional context**
NA

### PR DESCRIPTION
**Pull request by D-Triveni**
Enable hostname validation for server certificate verification.

Fixes #88697

### CODE REVIEW

**Comment by krish2718** [comment]
I only see the revert, so, how would this feature work without any support to configure the cert details?

File: include/zephyr/net/wifi_mgmt.h [hunk 1]
```diff
@@ -723,6 +723,10 @@ struct wifi_connect_req_params {
 	uint8_t ignore_broadcast_ssid;
 	/** Parameter used for frequency band */
 	enum wifi_frequency_bandwidths bandwidth;
+	/** Domain suffix match */
+	const uint8_t *domain_suffix_match;
```
Comment (krish2718) [inline include/zephyr/net/wifi_mgmt.h]: Please add helpful text and also wpa_supplicant supports passing multiple names too, we should mention that too.

File: include/zephyr/net/wifi_mgmt.h [hunk 2]
```diff
@@ -723,6 +723,10 @@ struct wifi_connect_req_params {
...
+	/** Length of domain suffix match, maximum 32 bytes */
```
Comment (krish2718) [inline include/zephyr/net/wifi_mgmt.h]: why max is 32 bytes? FQDN's can be longer esp. multiple names.

File: include/zephyr/net/wifi_mgmt.h (hunk 1 above)
Comment (krish2718) [reply include/zephyr/net/wifi_mgmt.h]: also maybe this should be a user friendly name not wpa_supplicant internal name, e.g., 
```suggestion
    /** Domain name in server certificate will be verified if this is provided */
	const uint8_t *server_cert_domain;
```

**Review by krish2718 — COMMENTED** [review]
we can also add `domain_match` to have a stricter subdomain check.

**Comment by MaochenWang1** [comment]
Is domain_match a more suitable parameter for certificate verification than domain_suffix_match?

**Comment by krish2718** [comment]
> Is domain_match a more suitable parameter for certificate verification than domain_suffix_match?

https://github.com/zephyrproject-rtos/zephyr/pull/98190#pullrequestreview-3393595804 IMHO we can add both and leave it to the user how strict the check needs to be.

**Review by krish2718 — DISMISSED** [review]

File: include/zephyr/net/wifi_mgmt.h [hunk 3]
```diff
@@ -723,6 +723,16 @@ struct wifi_connect_req_params {
 	uint8_t ignore_broadcast_ssid;
 	/** Parameter used for frequency band */
 	enum wifi_frequency_bandwidths bandwidth;
+
+	/** Full domain name to verify in the server certificate */
```
Comment (krish2718) [inline include/zephyr/net/wifi_mgmt.h:727]: Please update https://docs.zephyrproject.org/latest/connectivity/networking/api/wifi.html#wi-fi-enterprise-test-x-509-certificate-management add a new sub-section with overview and details on how to use these options.

Comment (D-Triveni) [reply include/zephyr/net/wifi_mgmt.h:727]: Done

**Review by krish2718 — DISMISSED** [review]

File: modules/hostap/src/supp_api.c [hunk 4]
```diff
@@ -969,6 +969,22 @@ static int wpas_add_and_config_network(struct wpa_supplicant *wpa_s,
 				goto out;
 			}
 
+			if (params->server_cert_domain_exact_len > 0) {
+				if (!wpa_cli_cmd_v("set_network %d domain_match \"%s\"",
+						   resp.network_id,
+						   params->server_cert_domain_exact)) {
```
Comment (jukkar) [inline modules/hostap/src/supp_api.c:975]: Is this pointer valid for the whole duration of the connect?

File: include/zephyr/net/wifi_mgmt.h [hunk 5]
```diff
@@ -723,6 +723,16 @@ struct wifi_connect_req_params {
 	uint8_t ignore_broadcast_ssid;
```
Comment (jukkar) [inline include/zephyr/net/wifi_mgmt.h:723]: We no longer place the "Fixes:  xxxx" to the commit message but to the PR description so Fixes from commit msg can be removed.

File: modules/hostap/src/supp_api.c (hunk 4 above)
Comment (D-Triveni) [reply modules/hostap/src/supp_api.c:975]: Yes, the pointer is valid for the entire connect process.

**Review by jukkar — DISMISSED** [review]

**Review by jukkar — APPROVED** [review]

**Review by krish2718 — APPROVED** [review]

**Review by MaochenWang1 — APPROVED** [review]
