### PR TITLE
VCP and MICP: AICS and VOCS count fix

### LINKED ISSUE #59523: [Coverity CID: 321088] Logically dead code in subsys/bluetooth/audio/vcp_vol_rend.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/ce3317d03e46e1a218af3e712383d9216c48a992/subsys/bluetooth/audio/vcp_vol_rend.c

Category: Control flow issues
Function: `prepare_vocs_inst`
Component: Bluetooth
CID: [321088](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=321088)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/ce3317d03e46e1a218af3e712383d9216c48a992/subsys/bluetooth/audio/vcp_vol_rend.c#L289

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_DEADCODE). ([CWE-561](http://cwe.mitre.org/data/definitions/561.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #59531: [Coverity CID: 321207] Logically dead code in subsys/bluetooth/audio/vcp_vol_rend.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/ce3317d03e46e1a218af3e712383d9216c48a992/subsys/bluetooth/audio/vcp_vol_rend.c

Category: Control flow issues
Function: `prepare_aics_inst`
Component: Bluetooth
CID: [321207](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=321207)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/ce3317d03e46e1a218af3e712383d9216c48a992/subsys/bluetooth/audio/vcp_vol_rend.c#L333

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_DEADCODE). ([CWE-561](http://cwe.mitre.org/data/definitions/561.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by Thalley**
Add early returns if the count is 0. 

This does not change anything as the function themselves are not called when it is 0, but this fixes a coverity issue. 

fixes https://github.com/zephyrproject-rtos/zephyr/issues/59523
fixes https://github.com/zephyrproject-rtos/zephyr/issues/59531

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/audio/micp_mic_dev.c [hunk 1]
```diff
@@ -116,6 +116,10 @@ static int prepare_aics_inst(struct bt_micp_mic_dev_register_param *param)
 	int j;
 	int err;
 
+	if (CONFIG_BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT == 0) {
```
Comment (cvinayak) [inline subsys/bluetooth/audio/micp_mic_dev.c:119]:
```suggestion
	if (!IS_ENABLED(CONFIG_BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT ) || CONFIG_BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT == 0) {
```

Similarly others?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/micp_mic_dev.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/audio/micp_mic_dev.c:119]: They should give the same result, right? IMO `IS_ENABLED` makes more sense to use for bool values.

e.g. if I do 
```c
if (CONFIG_BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT > 100) {
    qq; /* invalid code */
}
```

I still get a compiler warning, even if `CONFIG_BT_MICP_MIC_DEV_AICS_INSTANCE_COUNT < 100`. So I think that `CONFIG_FOO > X` for ints yields the same as `IS_ENABLED(CONFIG_FOO)` for bools, i.e. it is compiled but not linked

**Review by MariuszSkamra — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
