### PR TITLE
drivers: clock: stm32: overdrive after sysclock

### LINKED ISSUE #62130: Setup override after setting up sysclock
**Describe the bug**
Unable to boot Zephyr on STM32F7 with 216MHz fomr MCUboot

**Expected behavior**
Normal boot procedure

**Impact**
Showstopper, CPU doesn't boot.

**Logs and console output**
Before log output

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: 07c6af3b 
 - Version used v3.3

**Additional context**
According to the reference manual the overdrive can be enabled when the sysclock source is set and  the PLL has been turned on:

image

I believe the following code block (including the FLASH ACR LATENCY) should be moved below `set_up_plls();`

https://github.com/zephyrproject-rtos/zephyr/blob/64e841152737507c62f9daa8009be0a0dbfcdc99/drivers/clock_control/clock_stm32_ll_common.c#L726-L739

I'm having issues in combination with MCUboot, standalone I don't have any issues.

### PR DESCRIPTION
**Pull request by maxvankessel**
According to the reference manual the overdrive should be enabled after setup of the sysclock (HSE or HSI) and enabling the PLL (PLLON). The flash latency should be enabled after the PLL has been turned on, but before switching the system clock to the PLL.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/62130

### CODE REVIEW

**Comment by maxvankessel** [comment]
I rather not have my email in the signoff message in the commit, is this an issue?

**Comment by erwango** [comment]
> I rather not have my email in the signoff message in the commit, is this an issue?

Yes, that's an issue. But if this is a blocker, nvm. We can take up your work, but it will likely take more time.

**Comment by maxvankessel** [comment]
Signoff messages is amended

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 1]
```diff
@@ -59,6 +60,24 @@ void config_pll_sysclock(void)
 				    pllm(STM32_PLL_M_DIVISOR),
 				    STM32_PLL_N_MULTIPLIER,
 				    pllp(STM32_PLL_P_DIVISOR));
+
+#if defined(CONFIG_SOC_SERIES_STM32F7X)
+	/* Assuming we stay on Power Scale default value: Power Scale 1 */
+	if (CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC > 180000000) {
+		/* Enable the PLL (PLLON) before setting overdrive */
+		LL_RCC_PLL_Enable();
```
Comment (erwango) [inline drivers/clock_control/clock_stm32f2_f4_f7.c:68]: `LL_RCC_PLL_Enable()` is already part of `set_up_plls()`
Why not moving this to `set_up_plls()` just after `LL_RCC_PLL_Enable`.
Or just move it after `set_up_plls()`

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/clock_control/clock_stm32f2_f4_f7.c (hunk 1 above)
Comment (maxvankessel) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:68]: This was my thought train:
So I moved the overdrive part out of the common driver and into the f2_f4_f7 driver, which in my opinion is keeping the common clean. Changes made to the common driver should not impact this "side step" only for the F7, so that's why I added an extra `LL_RCC_PLL_Enable()`.  

So if you want this to change, the overdrive part will move back into the common driver and into the funtion `set_up_plls()`. Is this what you want?

Comment (erwango) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:68]: > which in my opinion is keeping the common clean

That's nice of you.

> Changes made to the common driver should not impact this "side step" only for the F7, so that's why I added an extra `LL_RCC_PLL_Enable()`.

One point is that you're skipping the `while (LL_RCC_PLL_IsReady() != 1U)` step, which I think should be added. So I agree with you that this additional step should be quick, impacts only F7 and has a quite marginal impact (no pm support on F7, so happens only at boot).

Comment (maxvankessel) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:68]: I see what you mean. This is on purpose, the PLLRDY bit indicates the PLL is locked.
And according to the reference manual this is not needed before changing the overdrive.

image

image

Comment (erwango) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:68]: ok, then can you add a quick comment about it ? (to save time for the next one reading this code) and this will be fine for me.

Comment (maxvankessel) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:68]: Yeah sure!

**Review by erwango — DISMISSED** [review]

**Review by erwango — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
