### PR TITLE
soc: k64f MPU configured to always allow ENET

### LINKED ISSUE #16639: eth: pinging frdm k64f eventually leads to unresponsive ethernet device
**Describe the bug**
Pinging the frdm_k64f board works for a while, but eventually leads to the board not responding to any ethernet requests. The board also becomes unable to send ping requests to a host. This unresponsiveness persists until the board is reset.

I am reasonably sure that this issue is not specific to ICMP as I have observed the same unresponsive behaviour doing UDP stuff - ICMP is just the most reliable way of provoking the issue.

This issue could be an mcux variant of #11255

Issue is seen on latest master and on v1.14.0 tag.

**To Reproduce**
1. cd samples/net/socket/echo_client
2. west -b frdm_k64f -d build
3. west flash --runner jlink
4. sudo ping 192.0.2.2 -i 0.001
5. ping responses will eventually stop

**Expected behavior**
I expect the frdm_k64f to not become unresponsive 

**Impact**
The project I'm working on is based on the frdm_k64f and will rely heavily on a stable ethernet connection. This issue is therefore a showstopper for me, especially since it seems to require a device reset to restore functionality.

**Screenshots or console output**
Wireshark log of when communication stops.

Screenshot from 2019-06-05 16-55-39

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.10.0
 - Commit: 82497eca2b9f15940cc68defe570a828433bba83

### PR DESCRIPTION
**Pull request by agansari**
Because NXP MPU's regions are dynamically enabled/disabled, ENET
device's access maybe restricted when switching out of a task.
Background DMA transfers from RAM to MAC/PHY may happen during MPU
region reconfiguration or core idling.
Enabled ENET (Kinetis MPU Master 3) to always have access to RAM address
space.

Fixes #16639

Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>

### CODE REVIEW

File: soc/arm/nxp_kinetis/k6x/nxp_mpu_regions.c [hunk 1]
```diff
@@ -8,10 +8,12 @@
 
 static const struct nxp_mpu_region mpu_regions[] = {
 	/* Region 0 */
+	/* Debugger acces can't be disabled; ENET devices will not be able to
```
Comment (ioannisg) [inline soc/arm/nxp_kinetis/k6x/nxp_mpu_regions.c]: access

**Review by ioannisg — APPROVED** [review]
Looks good, thanks for the patch. I left a comment for a typo fix.

**Comment by ioannisg** [comment]
Tested on hardware, locally (sanity check of arm, userspace, net and kernel tests on frdm_k64f)
