### PR TITLE
drivers: nxp_enet: Implement unique-mac property with HWINFO api

### LINKED ISSUE #88336: NXP frdm-rw612 is not using factory MAC address for Ethernet
**Describe the bug**
* The `frdm-rw612` does not use the factory set MAC address for the Ethernet interface when it starts. It by default uses random MAC address for the Ethernet interface. The factory MAC address is printed on top of the Ethernet socket in the board.
* The Wi-Fi interface properly uses the factory set MAC for its interface.

**Expected behavior**
* User gets by default the factory set MAC address for the Ethernet interface

**Impact**
* Using the Ethernet interface is annoying as the DHCP address changes constantly because DHCP server gives new IP address to the device after every boot
* As a workaround it is possible to set the `local-mac-address` property but this requires manual work and is rather pointless as the device has a dedicated MAC address for the Ethernet interface so it should use it automatically.

### PR DESCRIPTION
**Pull request by decsny**
Since the idea of the `nxp,unique-mac` property for this driver is that it will use some silicon ID for the lower 3 bytes of the mac address, and this is exactly what the hwinfo api can do, use this generic api to implement the driver. If the hwinfo is unimplemented, I kept the existing hardcoded values as a fallback.

Also, switched a couple in tree boards to be defined by default to use this property for testing coverage. One has HWINFO implemented (RW612) and one does not (RT1050).

### CODE REVIEW

**Comment by theadib** [comment]
hi @decsny I am not sure how the UUID is organized and if the 3 bytes create enough uniqueness.
In my other PR for the MCXN series I used the CRC24 to spread the MAC addresses using the whole HW UUID.
On the K64 series implementation it was a XOR combination which might also create duplicates.
HTH, Adib

**Comment by decsny** [comment]
> hi @decsny I am not sure how the UUID is organized and if the 3 bytes create enough uniqueness. In my other PR for the MCXN series I used the CRC24 to spread the MAC addresses using the whole HW UUID. On the K64 series implementation it was a XOR combination which might also create duplicates. HTH, Adib

What is "enough uniqueness" to you? If you read the DT binding description, you can see that the property is just "likely unique", and meant for testing purposes, it's not an actual provisioning strategy. I'm enabling the property for the platforms that don't have it hardcoded in the driver is the purpose of this PR, nothing more.

**Comment by maass-hamburg** [comment]
I'm in favor in making using HWINFO the default variant, that is used when no other source is used, like at the stm32 ethernet driver. https://github.com/zephyrproject-rtos/zephyr/blob/24f9ca7178a13273844bbe710a0bb37db179ad03/drivers/ethernet/eth_stm32_hal.c#L796-L820

**Comment by decsny** [comment]
> I'm in favor in making using HWINFO the default variant, that is used when no other source is used, like at the stm32 ethernet driver.
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/24f9ca7178a13273844bbe710a0bb37db179ad03/drivers/ethernet/eth_stm32_hal.c#L796-L820

For this driver, that is what this PR does.

**Comment by decsny** [comment]
> I'm in favor in making using HWINFO the default variant, that is used when no other source is used, like at the stm32 ethernet driver.
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/24f9ca7178a13273844bbe710a0bb37db179ad03/drivers/ethernet/eth_stm32_hal.c#L796-L820

The decision to error if no option was chosen was not unintentional, and I'm not interested to open up debates about that on this ticket, it's not the point of this PR.

**Comment by maass-hamburg** [comment]
> > hi @decsny I am not sure how the UUID is organized and if the 3 bytes create enough uniqueness. In my other PR for the MCXN series I used the CRC24 to spread the MAC addresses using the whole HW UUID. On the K64 series implementation it was a XOR combination which might also create duplicates. HTH, Adib
> 
> What is "enough uniqueness" to you? If you read the DT binding description, you can see that the property is just "likely unique", and meant for testing purposes, it's not an actual provisioning strategy. I'm enabling the property for the platforms that don't have it hardcoded in the driver is the purpose of this PR, nothing more.

If you buy f.e. 3 dev boards from the same batch and by chance the id is consecutive, the mac addresses should be different

**Comment by theadib** [comment]
as said, I do not know how the NXP UUID is generated.
On the STM32 theyr 96bit UID is composed of x,y position on the wafer, wafer number, lot number.
if for the 3 bytes the lot number is chosen (and not the wafer position) then it is likely that 2 chips from the same belt generate the same MAC address, which is very unfortunate.
I did not find information in the NXP UM how the UUID is build.
in my opinion a simple hash function over the whole UUID i.e. CRC24 should be used here.
Adib.

File: drivers/ethernet/eth_nxp_enet.c [hunk 1]
```diff
@@ -640,12 +641,28 @@ static const struct device *eth_nxp_enet_get_phy(const struct device *dev)
...
+
+	ret = hwinfo_get_device_id(id_buf, sizeof(id_buf));
+	if (ret == sizeof(id_buf)) {
+		id |= FIELD_PREP(0xFF0000, id_buf[2]);
+		id |= FIELD_PREP(0x00FF00, id_buf[1]);
+		id |= FIELD_PREP(0x0000FF, id_buf[0]);
+	} else {
+		/* Either implemented wrong, implemented insufficiently, or not at all */
+		/* This is fallback for platforms that don't have HWINFO properly */
+		id = ETH_NXP_ENET_UNIQUE_ID;
```
Comment (mmahadevan108) [inline drivers/ethernet/eth_nxp_enet.c:661]: This fallback option is encapsulated within the `#ifdef CONFIG_HWINFO` block. Shoud this instead be in the `#else` section?

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet.c:661]: what #else section?

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet.c:661]: The code is correct as far as I know, which is why I wrote it this way, if you think it's wrong for some reason then please articulate why

**Review by jukkar — APPROVED** [review]
Thanks @decsny, this works for me and is useful for testing purposes. It is a bit confusing that the MAC address printed on top of the Ethernet port in frdm-rw612 is not used, but at least the MAC address does not change between boots which is the main point here.

**Comment by decsny** [comment]
> Thanks @decsny, this works for me and is useful for testing purposes. It is a bit confusing that the MAC address printed on top of the Ethernet port in frdm-rw612 is not used, but at least the MAC address does not change between boots which is the main point here.

It might be that that address is fused somewhere, which is the purpose of the `nxp,fused-mac` option property, which is better IMO. I didn't even notice that sticker TBH. Usually the evk boards have 00:00:00:00:00:00 fused out of box, and perhaps this one is an exception, so I didn't even think about this at the moment. That's a different PR I guess, I'll make an internal ticket about it specifically.

**Comment by dleach02** [comment]
> > Thanks @decsny, this works for me and is useful for testing purposes. It is a bit confusing that the MAC address printed on top of the Ethernet port in frdm-rw612 is not used, but at least the MAC address does not change between boots which is the main point here.
> 
> It might be that that address is fused somewhere, which is the purpose of the `nxp,fused-mac` option property, which is better IMO. I didn't even notice that sticker TBH. Usually the evk boards have 00:00:00:00:00:00 fused out of box, and perhaps this one is an exception, so I didn't even think about this at the moment. That's a different PR I guess, I'll make an internal ticket about it specifically.

The actual MAC address is the better option, but it requires a manufacturing process that ensures some level of uniqueness. You can see on the MCXN947 board that we, NXP, are still using the Freescale vendor prefix of 00049f. It is highly doubtful that we have managed 16M unique IDs in this time frame and probably get away with not doing this because we are not actually shipping end products but demos. 

But for the boards we manufacture, it is probably safe to assume that if there is a sticker of a MAC address that the address has been programmed somewhere and that should ultimately be the default address to use.

**Comment by decsny** [comment]
I decided that I'm going to see what's this sticker business about on this PR, so putting the DNM

**Comment by jukkar** [comment]
If I recall correctly, the wlan mac address printed on back side of frdm-rw612 board, is properly and automatically set to the wlan0 interface when the device boots.

**Comment by decsny** [comment]
@jukkar I seem to have started what essentially seems a breadth-first-search going on internally at NXP to find anybody who knows what this sticker is about or where that mac address might be stored, so for now I removed the DNM.  I'm not sure what's the deal with the sticker yet, sorry. I'll leave your issue open until I find out about it but for now I'll limit the scope of this PR.

**Comment by decsny** [comment]
And to be clear, I did find documentation about the wireless MAC sticker on the back of the board, but this one on the ethernet port is currently a completely unexplained mystery it seems,. Hopefully we can find out who is the sticker master and what they are doing on this board

File: drivers/ethernet/eth_nxp_enet.c (hunk 1 above)
Comment (mmahadevan108) [reply drivers/ethernet/eth_nxp_enet.c:661]: The `#else` on line 678 since its the else for platforms that do not have HWINFO. Maybe we need to retain this fallback and add similar fallback to line 678?

Comment (ghost) [reply drivers/ethernet/eth_nxp_enet.c:661]: @mmahadevan108 probably wants to fallback on to `ETH_NXP_ENET_UNIQUE_ID` if `HW_INFO` is not selected:
```diff
diff --git a/drivers/ethernet/eth_nxp_enet.c b/drivers/ethernet/eth_nxp_enet.c
index 1395d9a2415..748ae301cb9 100644
--- a/drivers/ethernet/eth_nxp_enet.c
+++ b/drivers/ethernet/eth_nxp_enet.c
@@ -641,16 +641,17 @@ static const struct device *eth_nxp_enet_get_phy(const struct device *dev)
 	return config->phy_dev;
 }
 
-/* we enable HWINFO from kconfig if the relevant DT prop is in the tree */
-#ifdef CONFIG_HWINFO
 /* Note this is not universally unique, it just is probably unique on a network */
 static inline void nxp_enet_unique_mac(uint8_t *mac_addr)
 {
 	uint8_t id_buf[3];
 	uint32_t id = 0;
-	int ret;
+	int ret -1;
 
+	/* we enable HWINFO from kconfig if the relevant DT prop is in the tree */
+#ifdef CONFIG_HWINFO
 	ret = hwinfo_get_device_id(id_buf, sizeof(id_buf));
+#endif
 	if (ret == sizeof(id_buf)) {
 		id |= FIELD_PREP(0xFF0000, id_buf[2]);
 		id |= FIELD_PREP(0x00FF00, id_buf[1]);
@@ -674,9 +675,6 @@ static inline void nxp_enet_unique_mac(uint8_t *mac_addr)
 	mac_addr[4] = FIELD_GET(0x00FF00, id);
 	mac_addr[5] = FIELD_GET(0x0000FF, id);
 }
-#else
-#define nxp_enet_unique_mac(...)
-#endif
 
 #ifdef CONFIG_SOC_FAMILY_NXP_IMXRT
 #include <fsl_ocotp.h>
```

Comment (maass-hamburg) [reply drivers/ethernet/eth_nxp_enet.c:661]: HWINFO is selected if the prop is set, there is no need for a alternative. also there is a weak implementation, that will hwinfo_get_device_id fail if there is no real implementaion

**Review by maass-hamburg — APPROVED** [review]

File: drivers/ethernet/eth_nxp_enet.c (hunk 1 above)
Comment (decsny) [reply drivers/ethernet/eth_nxp_enet.c:661]: > HWINFO is selected if the prop is set, there is no need for a alternative. also there is a weak implementation, that will hwinfo_get_device_id fail if there is no real implementaion

yes, exactly

Comment (mmahadevan108) [reply drivers/ethernet/eth_nxp_enet.c:661]: `HWINFO` is selected when `nxp,unique-mac` is defined. What about the case when this is not defined and `HWINFO` is not selected. 
Don't we need a fallback for that case and set `id` to  `ETH_NXP_ENET_UNIQUE_ID`

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet.c:661]: no because then this whole code won't even be compiled since it's not going to be used, that's why there is an #if

Comment (mmahadevan108) [reply drivers/ethernet/eth_nxp_enet.c:661]: So no unique mac will be provided when HWINFO is not enabled?

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet.c:661]: Technically... but the dependency is the other way around, HWINFO will be enabled if unique mac is going to be used...

Comment (mmahadevan108) [reply drivers/ethernet/eth_nxp_enet.c:661]: Then I would have expected this property to be defined on a wider group of boards. With the current implementation it looks like we will be removing this option from a bunch of boards that currently support this.

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet.c:661]: No, I'm not going to do that, there is like 4 different ways to get the mac address and the goal should be to evenly distribute those methods across representative platforms

And I have no idea what you're talking about when you say it looks like this is removing support, I thought it's clear that this PR is only adding support. Where do you see code being removed? Can you point to the line number

Comment (mmahadevan108) [reply drivers/ethernet/eth_nxp_enet.c:661]: This block will not be used when `HWINFO` is not defined. https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/ethernet/eth_nxp_enet.c#L59-L69

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet.c:661]: Yes, because that would mean that `nxp,unique-mac` is not being used. So why should those macros be used? Are they used anywhere else?

Comment (mmahadevan108) [reply drivers/ethernet/eth_nxp_enet.c:661]: I get it, thanks for explaining.

**Review by mmahadevan108 — APPROVED** [review]
