### PR TITLE
Bluetooth: host: Periodic scanner drop incomplete data

### LINKED ISSUE #54072: Bluetooth: Host: Periodic scanner does not differentiate between partial and incomplete data
**Describe the bug**
When the periodic scanner is reconstructing the periodic advertising data to report to the application, it only checks if the data_status is marked as complete or not, it does not differentiate between incomplete and partial data, see [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/scan.c#L766-L835). In the case where the controller does not receive the data complete packet and the data_status is marked as "incomplete, no more data to come", the data of the next incoming periodic advertising event is appended to the truncated data resulting in incorrect data being passed to the application. 

**To Reproduce**
This is quite a difficult bug to reproduce as it relies on a packet being dropped. The test environment where this was discovered had a very high RSSI just above the threshold of the radios sensitivity which increased the likely of the packet not being received. 

1. Establish a synchronization between a periodic advertiser and scanner. The periodic advertiser should be advertising known data that is long enough to be split across multiple packets.
2. Repeatedly check the data received by the scanner and compare it with the expected advertised data.
3. When one of the packets to construct the data is not received the data should differ between the received data and the expected data

**Expected behavior**
The incomplete data should not be passed up to the application and should be dropped.

**Impact**
The application does not receive the correct data from the host.

**Logs and console output**
Expected data:
```
\xfa\xffY\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{\|}~\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf60\xffY\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,\x03'
```
Received data:
```
\xfa\xffY\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{\|}~\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xfa\xffY\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{\|}~\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf60\xffY\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,\x03'
```

In the following logs, the data total data length of the advertised data was 300bytes, which was split into 3 packets: 247, 3, 50. After logging the data length of the incoming periodic advertisement packets before they're reconstructed, it can be seen in the following logs that right before the test failed, a packet of data length 50 (the final data in the sequence) was dropped. This resulted in the data being 250 bytes longer than expected as it appended 247, 3, 247, 3 and 50 bytes to the data buffer for the advertisement report. (I've indented the events of interest)
```
\*\*\* Booting Zephyr OS build v3.2.99-ncs1-1495-gaf6add53aa1f \*\*\*
 
[00:00:01.836,822] <inf> bt_hci_core: hci_vs_init: HW Platform: Nordic Semiconductor (0x0002)
[00:00:01.836,883] <inf> bt_hci_core: hci_vs_init: HW Variant: nRF53x (0x0003)
[00:00:01.836,914] <inf> bt_hci_core: hci_vs_init: Firmware: Standard Bluetooth controller (0x00) Version 184.62253 Build 1392531289
[00:00:01.839,080] <inf> bt_hci_core: bt_dev_show_info: Identity: D6:30:BF:22:A4:15 (random)
[00:00:01.839,111] <inf> bt_hci_core: bt_dev_show_info: HCI: version 5.3 (0x0c) revision 0x221c, manufacturer 0x0059
[00:00:01.839,141] <inf> bt_hci_core: bt_dev_show_info: LMP: version 5.3 (0x0c) subver 0x221c
[00:00:07.969,604] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 247
[00:00:07.969,726] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 3
[00:00:07.969,848] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 50
[00:00:08.276,550] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 247
[00:00:08.276,672] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 3
[00:00:08.276,794] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 50
[00:00:08.351,409] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 247
[00:00:08.351,501] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 3
[00:00:08.351,654] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 50
[00:00:09.415,588] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 247
[00:00:09.415,740] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 3
[00:00:09.415,863] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 50
        [00:00:09.718,414] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 247
        [00:00:09.718,536] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 3
        [00:00:09.793,792] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 247
        [00:00:09.793,914] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 3
        [00:00:09.794,036] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 50
[00:00:09.868,743] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 247
[00:00:09.868,865] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 3
[00:00:09.868,988] <err> bt_scan: bt_hci_le_per_adv_report: evt len: 50
```
On further investigation I found in repeated failures the data_status on the packet before the dropped packet had data status set to 2: data incomplete no more to come as expected, it just isn't handled by the host.

**Environment:**
 - OS: Linux (Ubuntu 20.04)
 - Target: nrf5340dk
 - Toolchain: NCS 
 - SHA: [af6add53](https://github.com/zephyrproject-rtos/zephyr/tree/af6add53aa1f357e5216a6207af0572b53830783)

### PR DESCRIPTION
**Pull request by Pieloaf**
This changes the periodic scanner to drop periodic adv reports with incomplete data. This avoids incorrect data being sent to application in the case where the periodic adv data is not successfully received by the scanner.

Fixes #54072

### CODE REVIEW

File: subsys/bluetooth/host/scan.c [hunk 1]
```diff
@@ -805,6 +805,11 @@ void bt_hci_le_per_adv_report(struct net_buf *buf)
 			 */
 			bt_hci_le_per_adv_report_recv(per_adv_sync, &buf->b, &info);
 		} else {
+			if (evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_INCOMPLETE) {
+				per_adv_sync->report_truncated = true;
```
Comment (jori-nordic) [inline subsys/bluetooth/host/scan.c:809]: can you add a `LOG_DBG` as is done a L815?

**Review by jori-nordic — DISMISSED** [review]

**Comment by Pieloaf** [comment]
most recent force push was a rebase to align with main

**Review by jori-nordic — APPROVED** [review]

**Review by jori-nordic — CHANGES_REQUESTED** [review]
I forgot on the first pass:
Commit title should be: `Bluetooth: host: drop incomplete data in periodic scanner`

File: subsys/bluetooth/host/scan.c [hunk 2]
```diff
@@ -805,6 +805,14 @@ void bt_hci_le_per_adv_report(struct net_buf *buf)
...
 			bt_hci_le_per_adv_report_recv(per_adv_sync, &buf->b, &info);
 		} else {
+			if (evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_INCOMPLETE) {
+				LOG_WRN("Received incomplete advertising data. "
+					"Advertising report dropped.");
+
+				per_adv_sync->report_truncated = true;
+				net_buf_simple_reset(&per_adv_sync->reassembly);
+				return;
+			}
```
Comment (Thalley) [inline subsys/bluetooth/host/scan.c:815]: Given that we `return` here, shouldn't this block be put into an `else if`, instead of the current approach?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/scan.c (hunk 2 above)
Comment (Pieloaf) [reply subsys/bluetooth/host/scan.c:815]: Yeah I wondered that as well, but did it this way since it was done the same way in [the lines below it ](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/scan.c#L808-L817). But can move it to its own if else if that is preferred.

Comment (Thalley) [reply subsys/bluetooth/host/scan.c:815]: I would prefer an `else if` here. 

It is a bit tricky given the existing structure, but ideally it should have been
```c
if (evt->status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_COMPLETE) {
    /* do stuff */
} else if (evt->status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_INCOMPLETE) {
    /* do stuff */
} else if (evt->status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_COMPLETE) {
   /* do stuff */ 
}
```

Comment (Pieloaf) [reply subsys/bluetooth/host/scan.c]: I've restructured the function a bit to follow the structure you suggested. Let me know if it looks ok.

File: subsys/bluetooth/host/scan.c [hunk 3]
```diff
@@ -798,29 +798,40 @@ void bt_hci_le_per_adv_report(struct net_buf *buf)
...
-			}
-			net_buf_simple_add_mem(&per_adv_sync->reassembly, buf->data, evt->length);
-			if (evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_COMPLETE) {
+			per_adv_sync->report_truncated = true;
+			net_buf_simple_reset(&per_adv_sync->reassembly);
+			return;
+		}
+
+		if (evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_COMPLETE) {
+			if(per_adv_sync->reassembly.len == 0) {
```
Comment (Thalley) [inline subsys/bluetooth/host/scan.c:813]:
```suggestion
			if (per_adv_sync->reassembly.len == 0) {
```

File: subsys/bluetooth/host/scan.c [hunk 4]
```diff
@@ -798,29 +798,40 @@ void bt_hci_le_per_adv_report(struct net_buf *buf)
...
 			}
+		} else if (evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_INCOMPLETE) {
+			LOG_WRN("Received incomplete advertising data. "
+				"Advertising report dropped.");
+
+			per_adv_sync->report_truncated = true;
+			net_buf_simple_reset(&per_adv_sync->reassembly);
+
+		} else if { evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_PARTIAL
+			net_buf_simple_add_mem(&per_adv_sync->reassembly, buf->data, evt->length);
```
Comment (Thalley) [inline subsys/bluetooth/host/scan.c:832]:
```suggestion
		} else if ( evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_PARTIAL) {
			net_buf_simple_add_mem(&per_adv_sync->reassembly, buf->data, evt->length);
```

**Review by Thalley — CHANGES_REQUESTED** [review]
I think this new structure is easier to read - Thanks! 

A few bugs in the code though

**Comment by Pieloaf** [comment]
> I think this new structure is easier to read - Thanks!
> 
> A few bugs in the code though

Yeah sorry I tested it in a different environment locally and fixed those bugs there but missed them when I pushed from the environment Im making the PR from, working on it now.

**Comment by Thalley** [comment]
Hmm, unless I'm mistaken, it actually doesn't look like we are setting `CONFIG_BT_PER_ADV_SYNC_BUF_SIZE > 0` anywhere or testing that code at all. 

We should add at test for that before we merge this PR

**Comment by Pieloaf** [comment]
Oh hmmm, good catch. The environment I'm testing it in is using that code since I'm getting the warning messages I've added when packets are dropped, but yes it should be tested properly in CI

**Comment by Thalley** [comment]
> Oh hmmm, good catch. The environment I'm testing it in is using that code since I'm getting the warning messages I've added when packets are dropped, but yes it should be tested properly in CI

Could I bother you to add this as a babblesim test or something? At the very least we should build the code in CI :D

**Comment by Pieloaf** [comment]
> > Oh hmmm, good catch. The environment I'm testing it in is using that code since I'm getting the warning messages I've added when packets are dropped, but yes it should be tested properly in CI
> 
> Could I bother you to add this as a babblesim test or something? At the very least we should build the code in CI :D

I've not used babblesim before but I can try get a simple test setup with it today. Should I make a second PR for it or is ok as part of this one?

**Comment by Thalley** [comment]
> > > Oh hmmm, good catch. The environment I'm testing it in is using that code since I'm getting the warning messages I've added when packets are dropped, but yes it should be tested properly in CI
> > 
> > 
> > Could I bother you to add this as a babblesim test or something? At the very least we should build the code in CI :D
> 
> I've not used babblesim before but I can try get a simple test setup with it today. Should I make a second PR for it or is ok as part of this one?

The test should be added in this PR IMO

**Comment by Pieloaf** [comment]
@Thalley I wrote a babble sim test at the end of last week but I'm getting an I/O error when trying to set the advertising data. I referenced other bsim tests for it and I'm not sure where I'm going wrong. If I push the changes here would you mind taking a look if you have the time?

**Comment by jori-nordic** [comment]
> @Thalley I wrote a babble sim test at the end of last week but I'm getting an I/O error when trying to set the advertising data. I referenced other bsim tests for it and I'm not sure where I'm going wrong. If I push the changes here would you mind taking a look if you have the time?

I can help you out, contact me on teams

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c [hunk 5]
```diff
@@ -21,6 +21,29 @@ extern enum bst_result_t bst_result;
...
+	0x67, 0x68, 0x69, 0x6A, 0x6B, 0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75,
+	0x76, 0x77, 0x78, 0x79, 0x7A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F, 0x80, 0x81, 0x82, 0x83, 0x84,
+	0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93,
+	0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2,
+	0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1,
+	0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0,
+	0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF,
+	0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE,
+	0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED,
+	0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB};
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:41]: I'm curious about this array: Is the data specifically defined? 

Just wondering why it's done this way, instead of "just" filling it with an array like
```c
for (size_t i = 0U; i < ARRAY_SIZE(mfg_data); i++) {
    mfg_data[i] = i;
}
```

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c [hunk 6]
```diff
@@ -21,6 +21,29 @@ extern enum bst_result_t bst_result;
...
+
+
+static const struct bt_data ad[] = {BT_DATA(BT_DATA_MANUFACTURER_DATA, mfg_data, 254),
+				    BT_DATA(BT_DATA_MANUFACTURER_DATA, mfg_data, 254)};
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:45]:
```suggestion
static const struct bt_data ad[] = {BT_DATA_BYTES(BT_DATA_MANUFACTURER_DATA, mfg_data),
				    BT_DATA_BYTES(BT_DATA_MANUFACTURER_DATA, mfg_data)};
```

Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:45]: Should we also consider trying with the maximum size of 1650?

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c [hunk 7]
```diff
@@ -145,6 +168,20 @@ static void start_per_adv_set(struct bt_le_ext_adv *adv)
...
+	int err;
+
+	printk("Setting Periodic Advertising Data...");
+	err = bt_le_per_adv_set_data(adv, ad, ARRAY_SIZE(ad));
+	if (err) {
+		printk("Failed to set periodic advertising data: %d\n",
+		       err);
+		return;
+	}
+	printk("done.\n");
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:182]:
```suggestion
	}
	
	printk("done.\n");
```

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c [hunk 8]
```diff
@@ -276,6 +313,31 @@ static void main_per_adv_conn_privacy_advertiser(void)
 	PASS("Periodic advertiser passed\n");
 }
 
+static void main_per_adv_long_data_advertiser(void)
+{
+#if (CONFIG_BT_PER_ADV_SYNC_BUF_SIZE > 0)
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:318]: `CONFIG_BT_PER_ADV_SYNC_BUF_SIZE` only applies to the sync receiver, right? What's the argument for guarding the advertiser side?

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c [hunk 9]
```diff
@@ -22,12 +22,35 @@ extern enum bst_result_t bst_result;
...
+	0x67, 0x68, 0x69, 0x6A, 0x6B, 0x6C, 0x6D, 0x6E, 0x6F, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75,
+	0x76, 0x77, 0x78, 0x79, 0x7A, 0x7B, 0x7C, 0x7D, 0x7E, 0x7F, 0x80, 0x81, 0x82, 0x83, 0x84,
+	0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93,
+	0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2,
+	0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1,
+	0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF, 0xC0,
+	0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF,
+	0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE,
+	0xDF, 0xE0, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED,
+	0xEE, 0xEF, 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB};
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:42]: Instead of defining this both places, I'd suggest to just put it in the `common.h` file

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c [hunk 10]
```diff
@@ -22,12 +22,35 @@ extern enum bst_result_t bst_result;
...
+
+
+static const struct bt_data ad[] = {BT_DATA(BT_DATA_MANUFACTURER_DATA, mfg_data, 254),
+				    BT_DATA(BT_DATA_MANUFACTURER_DATA, mfg_data, 254)};
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:46]: We only need the `mfg_data` and not the `bt_data` to compare, right?

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c [hunk 11]
```diff
@@ -134,9 +157,43 @@ static void term_cb(struct bt_le_per_adv_sync *sync,
...
+static void recv_cb(struct bt_le_per_adv_sync *recv_sync,
+		    const struct bt_le_per_adv_sync_recv_info *info,
+		    struct net_buf_simple *buf)
+{
+	if (TEST_FLAG(flag_per_adv_recv)) {
+		return;
+	}
+
+	char le_addr[BT_ADDR_LE_STR_LEN];
+	uint8_t buf_data_len;
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:169]: Declare at top of scope please

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c [hunk 12]
```diff
@@ -134,9 +157,43 @@ static void term_cb(struct bt_le_per_adv_sync *sync,
...
+		FAIL("Unexpected adv data received\n");
+	}
+
+	net_buf_simple_pull(buf, ad[0].data_len);
+	buf_data_len = (uint8_t)net_buf_simple_pull_le16(buf);
+
+	if (buf->data[0]-1 != ad[1].data_len ||
+		memcmp(buf->data, ad[1].data, ad[1].data_len)) {
+		FAIL("Unexpected adv data received\n");
+	}
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:188]: Suggest to use `bt_data_parse` as that will also validate the length checks, and make it easier to perform the comparison for each LTV structure

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c [hunk 13]
```diff
@@ -280,6 +337,29 @@ static void main_per_adv_conn_privacy_syncer(void)
...
+
+	create_pa_sync(&sync);
+
+	printk("Waiting to receive periodic advertisment...\n");
+	WAIT_FOR_FLAG(flag_per_adv_recv);
+
+	printk("Waiting for periodic sync lost...\n");
+	WAIT_FOR_FLAG(flag_per_adv_sync_lost);
+#endif
+	PASS("Periodic advertising syncer passed\n");
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:360]:
```suggestion
	PASS("Periodic advertising long data syncer passed\n");
```

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c [hunk 14]
```diff
@@ -276,6 +313,31 @@ static void main_per_adv_conn_privacy_advertiser(void)
...
+	/* Advertise for a bit */
+	k_sleep(K_SECONDS(10));
+
+	stop_per_adv_set(per_adv);
+	stop_ext_adv_set(per_adv);
+
+	delete_adv_set(per_adv);
+	per_adv = NULL;
+#endif
+	PASS("Periodic advertiser passed\n");
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:338]:
```suggestion
	PASS("Periodic long data advertiser passed\n");
```

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c [hunk 15]
```diff
@@ -307,6 +387,15 @@ static const struct bst_test_instance per_adv_syncer[] = {
 		.test_tick_f = test_tick,
 		.test_main_f = main_per_adv_conn_privacy_syncer
 	},
+	{
+		.test_id = "per_adv_long_data_syncer",
+		.test_descr = "Periodic advertising sync test with maximum "
+			      "data length. Test is used to verify that "
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:393]: What does `maximum data length` refer to here? We are not sending 1650 octets, so I guess it refers to the maximum data in a single LTV (bt_data) struct? If so, that can be done with just a single bt_data struct, but you are using two, so the description here doesn't seem to match the actual test case implementation

**Review by Thalley — CHANGES_REQUESTED** [review]
Generally the implementation changes look good, and it's nice with the test case. Had a few comments for some improvements

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c (hunk 9 above)
Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:42]: This was my very first approach but then ran into issue with compiling it getting errors that it was "defined more than once" but both times it pointed to common.h so I had moved it to the individual files, but I'll see if I can work around it and move it back to common.h

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c (hunk 8 above)
Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:318]: Could use either of these for advertiser:
`CONFIG_BT_CTLR_ADV_DATA_LEN_MAX`
`CONFIG_BT_CTLR_ADV_DATA_CHAIN`
which I did initially use the ADV_DATA_LEN_MAX > 31 but set them both to the SYNC_BUF_SIZE, since it was only used in this test and they both used the same conf file. But for readability I can change it back

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c (hunk 5 above)
Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:41]: I initially had it like this with 
```C
for (size_t i = 0U; i < ARRAY_SIZE(mfg_data); i++) {
    mfg_data[i] = i;
}

// manufacturer data
mfg_data[0] = 0xFF;
mgf_data[1] = 0xFF; 
```
But looking at other cases which set mfg_data, I couldn't find a single case where the data wasn't specifically defined so changed it to match. But can change it back.

Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:41]: Ah, so one of the `0xff` is for the type? 

If using `BT_DATA` or `BT_DATA_BYTES` the type and length will be set by the macros, and don't need to be specified in the data itself.

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c (hunk 7 above)
Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:182]: The other functions in the test don't space the printk("done.\n") from the brace which is why i hadn't done it here
[1](https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c#LL106), [2](https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c#L119), [3](https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c#L132)...

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c (hunk 10 above)
Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:46]: oh actually yeah that would make more sense.

**Comment by Thalley** [comment]
@Pieloaf the commit "header" of the second commit should also be `tests: bluetooth` instead of `bluetooth: host`

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c (hunk 6 above)
Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:45]: I did try with 1650, but I could only send up to 1004 bytes. After that the application wasn't receiving the data, it may have been due to the periodic adv parameters im not sure but just reduced as it wasn't a test to ensure the advertiser can advertise maximum per adv data but that the scanner reassembles the split data correctly

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c (hunk 9 above)
Comment (alwa-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:42]: Possible solutions:
 - Make the variable const and add header guards. (I prefer this.)
 - Declare the variable extern in the header. Define the variable in common.c.
 - Wrap the variable in a static inline function. The variable must be static const.

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c (hunk 6 above)
Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c]: I was getting build errors with BT_DATA_BYTES as it was expecting a char/uint8_t not a uint8_t *
Looking at other instances where BT_DATA_BYTES is used the data bytes are inline in the function and not a pointer to an array of the data. So have left it as BT_DATA

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c [hunk 16]
```diff
@@ -145,6 +145,25 @@ static void start_per_adv_set(struct bt_le_ext_adv *adv)
 	printk("done.\n");
 }
 
+#if (CONFIG_BT_CTLR_ADV_DATA_CHAIN)
+static void set_per_adv_data(struct bt_le_ext_adv *adv)
+{
+	int err;
+	const struct bt_data ad[] = {
+		BT_DATA(BT_DATA_MANUFACTURER_DATA, mfg_data, 254),
+		BT_DATA(BT_DATA_MANUFACTURER_DATA, mfg_data, 254)};
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:154]: Is there any issue with using `BT_DATA_BYTES` on an `extern`? Otherwise I suggest to do
```suggestion
		BT_DATA_BYTES(BT_DATA_MANUFACTURER_DATA, mfg_data),
		BT_DATA_BYTES(BT_DATA_MANUFACTURER_DATA, mfg_data)};
```

If that is not possible, I suppose `sizeof(mfg_data)` also won't work instead of hardcoding the size to `254`

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c [hunk 17]
```diff
@@ -134,9 +135,37 @@ static void term_cb(struct bt_le_per_adv_sync *sync,
...
+		return;
+	}
+
+	bt_addr_le_to_str(info->addr, le_addr, sizeof(le_addr));
+	printk("PER_ADV_SYNC[%u]: [DEVICE]: %s advertisment received\n",
+	       bt_le_per_adv_sync_get_index(recv_sync), le_addr);
+
+	while (buf->len > 0) {
+		buf_data_len = (uint8_t)net_buf_simple_pull_le16(buf);
+		if (buf->data[0]-1 != ARRAY_SIZE(mfg_data) ||
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_syncer.c:155]:
```suggestion
		if (buf->data[0] - 1 != sizeof(mfg_data) ||
```

The length field is in octets, and not number of elements. Of course when using `uint8_t` that's the same, but in case that `mfg_data` would every change type from `uint8_t`, using `ARRAY_SIZE` wouldn't work

**Review by Thalley — CHANGES_REQUESTED** [review]

File: tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c (hunk 16 above)
Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:154]: Sorry I replied to one of the older comments regarding this but yes: 
I was getting build errors with BT_DATA_BYTES as it was expecting a char/uint8_t not a uint8_t *
Looking at other instances where BT_DATA_BYTES is used the data bytes are inline in the function and not a pointer to an array of the data. So have left it as BT_DATA 

But yeah using sizeof(mfg_data) sounds good

Comment (Pieloaf) [reply tests/bluetooth/bsim_bt/bsim_test_per_adv/src/per_adv_advertiser.c:154]: should this also use ARRAY_SIZE instead of sizeof 
re: your other comment?

File: subsys/bluetooth/host/scan.c [hunk 18]
```diff
@@ -805,6 +805,14 @@ void bt_hci_le_per_adv_report(struct net_buf *buf)
 			 */
 			bt_hci_le_per_adv_report_recv(per_adv_sync, &buf->b, &info);
 		} else {
+			if (evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_INCOMPLETE) {
+				LOG_WRN("Received incomplete advertising data. "
+					"Advertising report dropped.");
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/scan.c]: This condition is expected during normal operation due to noise in the environment, right? Then it should not be a warning.

Comment (Pieloaf) [reply subsys/bluetooth/host/scan.c]: should it be replaced with a LOG_DBG?

**Review by Thalley — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

File: subsys/bluetooth/host/scan.c [hunk 19]
```diff
@@ -805,6 +805,14 @@ void bt_hci_le_per_adv_report(struct net_buf *buf)
 			 */
 			bt_hci_le_per_adv_report_recv(per_adv_sync, &buf->b, &info);
 		} else {
+			if (evt->data_status == BT_HCI_LE_ADV_EVT_TYPE_DATA_STATUS_INCOMPLETE) {
+				LOG_DBG("Received incomplete advertising data. "
+					"Advertising report dropped.");
```
[the remark this answers is not in the document]
Comment (Pieloaf) [reply subsys/bluetooth/host/scan.c]: I'm not sure exactly what it would be used for, it was something I considered when making the change, if the data should just be passed to the application as incomplete and reset the buffer or drop the data before resetting the before. 
I chose to drop the data as the same was already being done for the extended scanner: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/scan.c#L634-L640

[the remark this answers is not in the document]
Comment (jhedberg) [reply subsys/bluetooth/host/scan.c]: Ok. I have a feeling we might later have to add this back, possibly through an optional `Kconfig` option, in case an app for whatever reason wants to see even these packets.

[the remark this answers is not in the document]
Comment (jhedberg) [reply subsys/bluetooth/host/scan.c]: Anyway, I'm fine with making this consistent with the extended scanner for now.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/scan.c (hunk 19 above)
[the remark this answers is not in the document]
Comment (sjanc) [reply subsys/bluetooth/host/scan.c]: I think the reason is to not have to cache on controller side,  you may have up to 7 chains with ~2.4s spacing for each of scanned device

[the remark this answers is not in the document]
Comment (Pieloaf) [reply subsys/bluetooth/host/scan.c]: I can create a separate issue/PR with a kconfig for this after its merged if that suits?

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/scan.c]: I remember we discussed this in detail when it was added. 

We definitely wanted to provide reassembled data to the upper layers, so they did not have to implement reassembly themselves. 

I don't fully recall the argument to drop partial reports, rather than providing them to the upper layers. Perhaps the idea was that we wanted to avoid providing an advertising report where the length field of the report, did not match the actual report, as that would also mean that something `bt_data_parse` would not work with the received report.

**Review by jori-nordic — APPROVED** [review]
