### PR TITLE
arm cortex_m: cmsis.h - Fix IRQn_Type enum

### LINKED ISSUE #41012: irq_enable() doesn’t support enabling NVIC IRQ number more than 127
**Describe the bug**
We are updating kscan driver for MEC172x microchip device. The kscan peripheral is routed to NVIC 135. In the driver init function we enable NVIC 135 by calling the function irq_enable() and passing the IRQ number from the device instance. 

The function irq_enable() casts the IRQ number input to IRQn_type enum (defined in cortex_m/[cmsis.h](https://github.com/MicrochipTech/zephyr/blob/main/include/arch/arm/aarch32/cortex_m/cmsis.h)) which results as a signed 8-bit number. The function will write the NVIC Set Enable register only if the signed 8-bit number is not negative. The NVIC irq 135 results in a negative number (see register R0, R3 in snapshot which shows the conversion). Hence the NVIC register is not written.

Attached screenshot of the debugger window inside function irq_enable()

The platform we are using is mec172xevb_assy6906

Note that if we add one last member to the IRQn_type structure (as the below line), then the issue gets resolved, as compiler no longer treats IRQn_type as 8-bit.

max_IRQn = 0x100,

We are unable to submit the MEC172x kscan driver without this fix in Zephyr core.
screenshot-irq_enable_debug

### PR DESCRIPTION
**Pull request by jvasanth1**
Fixed issue [#41012](https://github.com/zephyrproject-rtos/zephyr/issues/41012) based on bbolen's comment. 
Defined custom IRQn_Type in zephyr/soc/arm/microchip_mec/mec172x/soc.h. This will ensure NVIC numbers
more than 127 will work correctly with irq_enable() API.

Fixes #41012

Signed-off-by: Jay Vasanth <jay.vasanth@microchip.com>

### CODE REVIEW

**Review by MaureenHelm — COMMENTED** [review]
Why aren't we updating the Microchip MEC HAL module to get this typedef?

From https://packs.download.microchip.com/:
image

**Review by stephanosio — COMMENTED** [review]
For some reason, it looks like the MEC17xx support, unlike MEC1501, has been implemented such that the "HAL files" are part of the main Zephyr repository instead of an external HAL repository (i.e. `hal_microchip`).

In that sense, it would be appropriate to place the "CMSIS definitions" in the `soc.h` or other SoC-specific header file ([note that we have other SoCs doing something similar](https://github.com/zephyrproject-rtos/zephyr/search?q=extension%3Ah+IRQn)).

As for whether the "HAL files" should have been part of the main Zephyr repository, it is quite questionable; but, I assume there were reasons for doing so ...

**Comment by jvasanth1** [comment]
Hi Maureen,

Stephanos is correct. MEC17xx is implemented with the hal files part of main Zephyr repository.

Here is the background:

Google did not accept the Nuvoton HAL for the Nuvoton NPCX series and the ITE HAL for IT83xxx.
MEC172x on Zephyr is being used by Google.
Google refuses to use the HAL provided by Microchip.

In order for Google to continue with MEC172x on Zephyr, Microchip had to implement the MEC172x SoC to not depend upon a MCHP HAL.  Development of a Zephyr HAL for MEC172x has ceased.

This exposed an issue with Zephyr code architecture.
For ARM Cortex-Mx parts, the main Zephyr code tree uses a cmsis.h that uses default settings for the IRQn_Typedef enum if external headers do not define __NVIC_PRIO_BITS.
The default definition of IRQn_Typedef results in an 8-bit sized enum because GCC flags are enabled to make each enum as small as possible.  There is a GCC flag to force enum’s to be the size of a full integer (32-bits on Cortex-Mx).
Issue was not observed before because the Nuvoton and ITE SoC’s that also do not use HAL’s only have < 128 interrupt sources fitting in a singed 8-bit value.

Hence we are proposing the following resolution in this pull request:
MEC172x will not use a HAL.
No need to change zephyr/arch/arm/aarch32/cortex_m/cmsis.h
Add the required CMSIS defines to zephyr/soc/arm/microchip_mec/mec172x/soc.h
__NVIC_PRIO_BITS, and others
Add typedef enum IRQn { …} IRQn_Type.

Please help in approving this pull request.

File: soc/arm/microchip_mec/mec172x/soc.h [hunk 1]
```diff
@@ -24,6 +24,224 @@
...
+ *       transition (Thumb -> ARM mode), unaligned, etc.
+ * -9 through -6 are not implemented (reserved).
+ * -5 System call via SVC instruction.
+ * -4 Debug Monitor.
+ * -3 not implemented (reserved).
+ * -2 PendSV for system service.
+ * -1 SysTick NVIC system timer.
+ * Numbers >= 0 are external peripheral interrupts.
+ */
+typedef enum IRQn {
```
Comment (albertofloyd) [inline soc/arm/microchip_mec/mec172x/soc.h:57]: @jvasanth1 I believe this should be typedef enum { 
...
} IRQn_Type

See https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/arm/ti_simplelink/cc32xx/soc.h

**Comment by albertofloyd** [comment]
@MaureenHelm  @stephanosio since MEC172x HAL is not used, can this approach be used as is similar to what is done in other Soc?

**Review by bbolen — APPROVED** [review]
From what I see from the 172x datasheet I found online, this seems to look okay to me.

File: soc/arm/microchip_mec/mec172x/soc.h (hunk 1 above)
Comment (jvasanth1) [reply soc/arm/microchip_mec/mec172x/soc.h]: updated in the latest push
[soc/arm/microchip_mec/mec172x/soc.h](https://github.com/MicrochipTech/zephyr/blob/IRQn_Type_fix/soc/arm/microchip_mec/mec172x/soc.h)

**Review by stephanosio — APPROVED** [review]
