### PR TITLE
drivers: pwm: Fix compile issues with Atmel SAM PWM driver

### LINKED ISSUE #36095: drivers: pwm: sam: compilation failure for sam_v71b_xult
**Describe the bug**
When building for the sam_v71b_xult with the `pwm_sam` driver enabled, the build fails.

**To Reproduce**
1. `west build -p=auto -b sam_v71b_xult zephyr/samples/hello_world/ -t menuconfig`
2. Enable the `pwm_sam` driver
3. `west build -p=auto -b sam_v71b_xult zephyr/samples/hello_world/`

**Expected behavior**
The sample builds with enabled pwm driver.

**Impact**
Can not use the `pwm_sam` driver for the sam_v71b_xult board.

**Logs and console output**
Relevant build failure message:
```
/home/christoph/git/zephyr/drivers/pwm/pwm_sam.c:64:5: error: 'Pwm' has no member named 'PWM_CH_NUM'
   64 |  pwm->PWM_CH_NUM[ch].PWM_CMR = PWM_CMR_CPRE_CLKA_Val;
      |     ^~
/home/christoph/git/zephyr/drivers/pwm/pwm_sam.c:69:5: error: 'Pwm' has no member named 'PWM_CH_NUM'
   69 |  pwm->PWM_CH_NUM[ch].PWM_CPRDUPD = period_cycles;
      |     ^~
/home/christoph/git/zephyr/drivers/pwm/pwm_sam.c:70:5: error: 'Pwm' has no member named 'PWM_CH_NUM'
   70 |  pwm->PWM_CH_NUM[ch].PWM_CDTYUPD = pulse_cycles;
```

**Environment (please complete the following information):**
 - OS: Debian 11 Testing
 - Zephyr SDK
 - Commit 4113a43bfff48f58bf5300163e2efbe046f1e5f8 (current main at filing of this issue)

**Additional context**
This is very likely related to the Atmel SoC HAL which defines these structs. There are very similar defines available, which define no struct, but bit masks for the corresponding registers. I am currently working on a fix for this.

### PR DESCRIPTION
**Pull request by galak**
The was a missing comma in the DEVICE_DT_INST_DEFINE macro and the
SAME71 HAL tweaks the name of a struct so we have to work around that.

Fixes #36095

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@Urist-McGit  FYI

**Review by gmarull — APPROVED** [review]

**Comment by nandojve** [comment]
Thanks @galak for address this.

I'll look around PWM_CH_NUM to see if it is necessary fix on hal_atmel. It is important make a fix that solve for all M7 series SAME70/V70/V71 and both revision A/B.

**Comment by galak** [comment]
> I'll look around PWM_CH_NUM to see if it is necessary fix on hal_atmel. It is important make a fix that solve for all M7 series SAME70/V70/V71 and both revision A/B.

From the HAL repo:
```
asf/sam/include/same70/component/pwm.h:       PwmChNum PWM_CH_NUM[PWMCHNUM_NUMBER]; /**< Offset: 0x200 PWM Channel Mode Register (ch_num = 0) */
asf/sam/include/same70b/component/pwm.h:       PwmChNum PWM_CH_NUM[PWMCHNUM_NUMBER]; /**< Offset: 0x200 PWM Channel Mode Register */
asf/sam/include/samv71/component/pwm.h:       PwmChNum PwmChNum[PWMCHNUM_NUMBER]; /**< Offset: 0x200 PWM Channel Mode Register (ch_num = 0) */
asf/sam/include/samv71b/component/pwm.h:       PwmChNum PwmChNum[PWMCHNUM_NUMBER]; /**< Offset: 0x200 PWM Channel Mode Register */
```

**Comment by galak** [comment]
I tested this on sam_e70_xplained &  sam_v71b_xult

File: drivers/pwm/pwm_sam.c [hunk 1]
```diff
@@ -37,6 +37,13 @@ static int sam_pwm_get_cycles_per_sec(const struct device *dev, uint32_t pwm,
 	return 0;
 }
 
+/* The SAMV71 HALs change the name of the field, so we need to
+ * define it this way to match how the other SoC variants name it
+ */
+#if defined(CONFIG_SOC_SERIES_SAMV71)
+#define PWM_CH_NUM PwmChNum
+#endif
```
Comment (mnkp) [inline drivers/pwm/pwm_sam.c:45]: In a PR which I've just submitted #zephyrproject-rtos/hal_atmel/pull/15 (I've noticed this one too late) I've patched the HAL rather than the driver. I'm not sure which approach is better but we probably should align on one. It's unfortunate that Atmel HAL headers are low quality.

Comment (stephanosio) [reply drivers/pwm/pwm_sam.c:45]: Noting that there will be too many patches required to support all SAM family devices (i.e. `sam3*`, `sam4*`, `sam7*`), I wonder if we should just do [what we did for the SAM0 family](https://github.com/zephyrproject-rtos/zephyr/blob/ce003ffa458586a830b8d861b2b2ae580b6658ef/soc/arm/atmel_sam0/common/sercom_fixup_samd5x.h).

Comment (galak) [reply drivers/pwm/pwm_sam.c:45]: @mnkp I was thinking that since we don't have a clear way of getting fixes back upstream like we would for STM or NXP devices doing something like what @stephanosio is suggesting would make sense.

Comment (nandojve) [reply drivers/pwm/pwm_sam.c:45]: I take look at all SAM3/4/7 PWM and it is almost same IP block. There are differences related to DMA and others small improvements on some SoC. I believe if we follow SAM4S datasheet (minimal implementation), everything that we made will works for all others. Any other improvement can be easy added after. DMA is handled by different controllers: PDC or XDMAC. In this case, DMA need to be handled with different registers. The SAM4L must be excluded at Kconfig because don't have PWM feature.

My preference is direct adjust Atmel headers to make code easy to read and avoid #if blocks. Otherwise we start to create "garbage" on Zephyr tree and people can think that right thing to do. I don't have objections to @stephanosio suggestion but I think that king adjust should be made at hal_atmel, if majority think that is the right path.

Conflicts:

Only on SAM4E/SAME7x/V7x
0x24 PWM DMA Register
0xA0 PWM Spread Spectrum Register
0xA4 PWM Spread Spectrum Update Register
0xC0 PWM Fault Protection Value 2 Register

Only on SAM4E/SAM3X
0x100–0x128 Reserved for PDC registers

For any other, above is reserved.

Comment (mnkp) [reply drivers/pwm/pwm_sam.c:45]: I also would prefer to avoid #if blocks in the driver. They do make code less readable. For me patching hal_atmel or following suggestion from @stephanosio would be a better choice.

Some years ago I opened a ticket with Atmel requesting fixes to some of the header files. There were quite a few issues. About the same time I was contacted by an Atmel engineer here on GitLab who was working on improving their header generation flow. He was friendly, helpful and aware that they need to do a better job. But at the end only half of the problems were fixed. And the headers are still low quality. It doesn't look like things changed much under control of Microchip.

Comment (nandojve) [reply drivers/pwm/pwm_sam.c:45]: I don't expect MCHP will fix headers. In general, Manufacturers prefer invest on new things once current it is working. I already found a bug in the TWIM driver for SAM4L years ago. After a year or more, they fixed. Since we only need harmonize, I think it is better fix by demand, like in this case. The fix don't need be by a batch patch for all SoC at same time.

My preference is fixing on hal_atmel headers because we have a better history to tell e avoid complicated and dedicated zephyr headers, over time.

Thanks @galak for add #36187.

Comment (galak) [reply drivers/pwm/pwm_sam.c:45]: Going to discuss the general topic of how we should handle HAL fixes when there is no clear upstream process for that HAL in the Process Meeting.

Comment (ioannisg) [reply drivers/pwm/pwm_sam.c:45]: Discussed briefly in the Process Meeting: the recommendation is to use the approach proposed above in this thread by @stephanosio , using the fixup files in the Zephyr main tree. We should capture this in the project documentation.

Comment (galak) [reply drivers/pwm/pwm_sam.c:45]: @stephanosio @nandojve any suggestions on how I should move the "PWM" fixup over into the soc?

Comment (nandojve) [reply drivers/pwm/pwm_sam.c:45]: Hi @galak ,

I believe you should add a fixup like pointed by @stephanosio to drop the below fragment:

```
#if defined(CONFIG_SOC_SERIES_SAMV71)
#define PWM_CH_NUM PwmChNum
#endif
```

at
`zephyr/soc/arm/atmel_sam/common/<driver>_fixup.h`

We work with this approach on a incremental way, so ,you can only fix the current interest. No need to fixup everything.
This allows us to harmonize SAM/SAM0 drivers fast. Later anyone can rework and move to hal_atmel.

Comment (galak) [reply drivers/pwm/pwm_sam.c]: Updated with pwm_fixup.h

**Review by nandojve — APPROVED** [review]
Tested on SAMV71 using `samples/basic/blinky_pwm` and `samples/basic/fade_led`.
It was necessary reconfigure led0 as pwm_led_0.

**Review by stephanosio — APPROVED** [review]
LGTM

For future reference, `PwmChNum` is also used by the `samv71b` (currently not supported in Zephyr) and `same70*` HALs (though the latter is currently patched: see https://github.com/zephyrproject-rtos/hal_atmel/commit/b643931c0514db5df2d597d312b995152f4b3e1e).

Since we have decided to go with the fix-up header approach, we should not patch the `same70*` headers when we are applying the next DFP version and, instead, update the fix-up header(s) accordingly.

**Comment by nandojve** [comment]
> LGTM
> 
> For future reference, `PwmChNum` is also used by the `samv71b` (currently not supported in Zephyr) and `same70*` HALs (though the latter is currently patched: see [zephyrproject-rtos/hal_atmel@b643931](https://github.com/zephyrproject-rtos/hal_atmel/commit/b643931c0514db5df2d597d312b995152f4b3e1e)).
> 
> Since we have decided to go with the fix-up header approach, we should not patch the `same70*` headers when we are applying the next DFP version and, instead, update the fix-up header(s) accordingly.

NAK on this. One thing is have a way to speed up development to test and create new things or fix broken drivers. Like this case. Other thing is not touch anymore on headers. There is no sense on that.

BTW samv71b is supported, see board DTS.

**Comment by stephanosio** [comment]
> NAK on this. One thing is have a way to speed up development to test and create new things or fix broken drivers. Like this case. Other thing is not touch anymore on headers. There is no sense on that.

Unless there is a way for us to upstream the patches we make in `hal_atmel`, we should refrain from modifying it; otherwise, we have to manually keep track of these patches and apply them whenever we import a new version of DFP, which can be quite cumbersome and prone to human errors.

That is my (and I suppose others too) rationale behind using the Zephyr-side fix-up headers instead of patching each DFP in `hal_atmel`.

**Comment by nandojve** [comment]
> > NAK on this. One thing is have a way to speed up development to test and create new things or fix broken drivers. Like this case. Other thing is not touch anymore on headers. There is no sense on that.
> 
> Unless there is a way for us to upstream the patches we make in `hal_atmel`, we should refrain from modifying it; otherwise, we have to manually keep track of these patches and apply them whenever we import a new version of DFP, which can be quite cumbersome and prone to human errors.

Hi @stephanosio , I was thinking more about it. Yes, we don't have a way to upstream to MCHP our patches. However, I think we should not refrain to fix SAM headers. Let's explore options since we have two main groups: SAM0 and SAM.

SAM0 headers are far better than SAM headers. At hal_atmel, I think I only saw 1 patch, so those are almost as is. I'm assuming that people commit DFP as is. All new MCHP devices are using SAM0 IPs. These means that what have been doing on SAM0 fix-ups are majority wraps because there are two clocks variants, no header patches itself.

SAM's devices are another history. They share some IPs but data structure on headers are sometimes complete different and, in some cases, are missing defines. The devices that are Cortex-M4, the last update were on 2016. I believe there will no changes on that because new devices are using SAM0 peripherals and MCHP will not invest time to fix that. In this case, everything that we do it is in fact fixed. Cortex-M7 DFP version were from 2019 and, I believe, newer devices probably will use SAM0 peripherals too. We can assume they have learned the lesson related to DFP. Since there wasn't newer DFP since there it is possible assume that are current stable now. This means, no new updates too.

That said, I don't see why we need add files on Zephyr main tree. I'm assume that there is no intention to add any other SAM4 device at hal_atmel. If there is, I can help to track and patch headers. I've been doing since 2.1 and, probably, I will continue.

I like have flexibility but I think the goal is avoid to create a mess like were with soc-fixup in past, before devicetree macros that we know today. That was months of hard work to test and make sure everything is OK. I really don't want to be on same situation in future. If for some reason MCHP change any structs, we need add new fixups anyway. It will be commutative fixes, multiple definitions for same thing and it will be hard to read. For many SAM, it were needed to rework a lot of structs to make it compatible with current drivers.

At end, we don't need update all hal_atmel DFP structs/defines too, just because MCHP lunched a new DFP. We can add the fix itself for that SoC on a incremental way. So, we don't loose work and don't need track it. Doing fixes by fixup will be a lot of files that will introduce unnecessary complexity. That is my main concern and this is why I do prefer patch headers for SAM.
