### PR TITLE
net: icmpv6: Drop ICMPv6 packet if NS header is NULL

### LINKED ISSUE #6217: echo server crash from corrupt ICMPv6 NS packet
Defensics test case: ICMPv6.NDP.Neighbor-solicitation.Neighbor-Solicitation.IPv6-Packet.payload.protocol.icmpv6-message.ndp-neighbor-solicitation.element - 9192

This test case crashes echo server in QEMU.

[net/core] [DBG] net_rx_thread: (0x004037c0): Received pkt 0x00406d78 len 62
[net/ipv6] [DBG] net_ipv6_process_pkt: (0x004037c0): IPv6 packet len 48 received from fe80::8c0:deff:fefc:102f to ff02::1:ff00:1
[net/ipv6] [DBG] process_icmpv6_pkt: (0x004037c0): ICMPv6 Neighbor Solicitation received type 135 code 0
[net/icmpv6] [ERR] net_icmpv6_get_ns_hdr: {assert: 'frag' failed}
[net/ipv6] [ERR] handle_ns_input: {assert: 'ns_hdr' failed}
***** CPU Page Fault (error code 0x00000000)
Supervisor thread read address 0x00000004
PDE: 0x025 Present, Read-only, User, Execute Enabled
PTE: 0x00 Non-present, Read-only, Supervisor, Execute Enabled
Current thread ID = 0x004037c0
Faulting segment:address = 0x0008:0x0000c20e
eax: 0x00000000, ebx: 0x00000000, ecx: 0x00000004, edx: 0x0040c400
esi: 0x00000030, edi: 0x0040c4e0, ebp: 0x0040c43c, esp: 0x0040c400
eflags: 0x246
Fatal fault in essential thread! Spinning...
Terminate emulator due to fatal kernel error

[icmpv6-ns-9192.zip](https://github.com/zephyrproject-rtos/zephyr/files/1727016/icmpv6-ns-9192.zip)

### PR DESCRIPTION
**Pull request by rmstoi**
This commit fixes the crash of echo_server from malformed
ICMPv6 NS packet.

Fixes #6217

Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>

### CODE REVIEW

File: subsys/net/ip/ipv6.c [hunk 1]
```diff
@@ -1367,7 +1367,10 @@ static enum net_verdict handle_ns_input(struct net_pkt *pkt)
 	size_t left_len;
 
 	ns_hdr = net_icmpv6_get_ns_hdr(pkt, &nshdr);
-	NET_ASSERT(ns_hdr);
+	if (!ns_hdr) {
+		NET_DBG("NULL NS header - dropping");
```
Comment (tbursztyka) [inline subsys/net/ip/ipv6.c]: NET_ERR maybe?

Comment (rmstoi) [reply subsys/net/ip/ipv6.c]: ok, I will push updated patch

**Review by tbursztyka — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
