### PR TITLE
Bluetooth: Host: Fix bt_recv_thread_id assignment

### LINKED ISSUE #43448: Deadlock detection in `bt_att_req_alloc` ineffective when `CONFIG_BT_RECV_IS_RX_THREAD=n`
This continues bug #39624, that was only partially fixed in #40056, commit https://github.com/zephyrproject-rtos/zephyr/pull/40056/commits/54522ff54f25363114938827c6d19866a0c596e9.

#### Description of bug

The above mentioned fix attempts to detect the situation when `bt_att_req_alloc()` is invoked on the same thread that runs `att_handle_rsp`. It attempts to do so by noting the thread that first ran `bt_recv`, assuming the same thread will house all calls to `bt_att_req_free`. This turns out not to be correct. It is evident from the call stack provided below that `bt_att_req_free` can be called from other threads than the one that runs `bt_recv`.

#### Impact
It's possible for the application and services to deadlock the Bluetooth stack by calling Bluetooth APIs in Bluetooth event handlers.

#### Rationale for original fix (in https://github.com/zephyrproject-rtos/zephyr/pull/40056/commits/54522ff54f25363114938827c6d19866a0c596e9)

Completely removing blocking behavior was considered and rejected to maintain backwards compatibility.

`bt_att_req_alloc` can be called many times by the application before the first time `bt_att_req_free` runs. It's therefore too late to note the thread id in `bt_att_req_free`. Instead, the decision was made to note the thread id further up the stack. `bt_recv` was chosen erroneously.

#### Possible fixes
 - Capture the thread ID of BT RX somewhere else. `hci_acl()` seems suitable. Also don't block on the System work queue.

#### Abstract call stacks that lead to `bt_att_req_free`
`##` denotes a fork or join.
```
[thread ISR]
bt_recv
{bt_dev.rx_queue put no_wait}
##

[thread BT RX]
{bt_dev.rx_queue get wait_forever}
hci_rx_thread
hci_acl
##

[thread BT RX]
bt_recv
hci_acl
##

hci_acl
bt_conn_recv
bt_acl_recv
bt_l2cap_recv
l2cap_chan_recv
##

l2cap_chan_recv
bt_att_recv
##

l2cap_chan_recv
l2cap_chan_recv_queue
{chan.rx_queue put no_wait}
[thread System work queue]
{chan.rx_queue get no_wait}
l2cap_rx_process
l2cap_chan_le_recv
l2cap_chan_le_recv_seg
l2cap_chan_le_recv_sdu
bt_att_recv
##

bt_att_recv
att_handle_...
att_handle_rsp
bt_att_req_free
```

### PR DESCRIPTION
**Pull request by LingaoM**
The above mentioned fix attempts to detect the situation when
bt_att_req_alloc() is invoked on the same thread that runs
att_handle_rsp. It attempts to do so by noting the thread that
first ran bt_recv, assuming the same thread will house all calls
to bt_att_req_free. This turns out not to be correct. It is
evident from the call stack provided below that bt_att_req_free
can be called from other threads than the one that runs bt_recv.

Fixes: #43448

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

### CODE REVIEW

**Review by alwa-nordic — DISMISSED** [review]

**Review by jhedberg — CHANGES_REQUESTED** [review]
I’m not following the logic here. Please provide a better description. 

Other issues:

why are you only setting the variable for ACL data and not for any other HCI pa jets (like events)? And even if that’s the right thing to do, why are you not changing the name of the variable, considering that its name doesn’t reflect its usage anymore. 

Also, please fix the English grammar of the commit title. Either change the last word to “assigned” or simply remove the words “not correctly”

**Comment by carlescufi** [comment]
> I’m not following the logic here. Please provide a better description.

I think it's because `hci_acl()` always executes from the relevant context for ATT, whereas `bt_recv()` does not.

**Review by jhedberg — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

File: subsys/bluetooth/host/hci_core.h [hunk 1]
```diff
@@ -479,4 +479,4 @@ void bt_hci_le_df_cte_req_failed(struct net_buf *buf);
 /** First thread that called bt_recv. NULL if not yet called.
  *  Updated non-atomically; may be used only to compare to current thread id.
  */
-extern k_tid_t bt_recv_thread_id;
+extern k_tid_t hci_acl_thread_id;
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/hci_core.h:482]: This variable name must start with "`bt_`". It's the namespace for this file.

I'm not too happy about the new name since `hci_acl` is an hidden internal / static function. But I will approve `bt_hci_acl_thread_id` if others like it. I think `bt_acl_cb_thread` is better. This variable has always been leaking implementation and would benefit from an abstraction. If anybody has any idea, speak up.

File: subsys/bluetooth/host/att.c [hunk 2]
```diff
@@ -3234,7 +3234,7 @@ struct bt_att_req *bt_att_req_alloc(k_timeout_t timeout)
 {
 	struct bt_att_req *req = NULL;
 
-	if (k_current_get() == bt_recv_thread_id) {
+	if (k_current_get() == hci_acl_thread_id) {
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/att.c:3237]: I think we also have to check if the current context is the system work queue.

**Review by alwa-nordic — DISMISSED** [review]
The commit message must be adapted to make sense without looking at the issue. The current commit message is an excerpt from the issue but it lacks context. Here is a sample message:

> The intended purpose of `bt_recv_thread_id` was to identify the thread that should later call `bt_att_req_free` (other than the system work queue). That thread must not be blocked in `bt_att_req_alloc`. Depending on the kconfig settings `CONFIG_BT_RECV_IS_RX_THREAD`, this may not be the same thread that calls `bt_recv`. On the other hand, `hci_acl` is always in that thread.
>
> This change removes `bt_recv_thread_id` and replaces it with .....
>
> Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/43448

File: subsys/bluetooth/host/hci_core.h (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.h:482]: @alwa-nordic we don't generally enforce names-spacing for stack-internal symbols, but we don't forbid it either. In fact, it's especially encouraged for internal symbols that are exported between multiple c-files. So I support this suggestion.

Comment (alwa-nordic) [reply subsys/bluetooth/host/hci_core.h:482]: > Is this value intended for other uses than ATT?

No. This variable is a hack. It has no intended use. We would like to get rid of it if we can.

> Does the issue it solves exist for other fixed L2CAP channels? Does it exist for dynamic L2CAP channels?

Maybe. The GATT API is affected because (1.) it promises to be async, and (2.) it ends up in an allocation call with timeout K_NO_WAIT. If (1.) wasn't true, the deadlock would be the API users fault for calling blocking API from BT RX context.

> Is there any other thread besides the "hci_acl" that calls bt_att_recv?

Possibly; the system work queue. This call path exist:

```
l2cap_rx_process
l2cap_chan_le_recv
l2cap_chan_le_recv_seg
l2cap_chan_le_recv_sdu
bt_att_recv
```

> Is it possible, and does it make sense to move this value to att.c and rename it to something like bt_att_recv_thread_id? Or do we want to keep it more generic?

I assume you are thinking of moving the capture of `k_current_get`? I looked a bit around and I think it can go into `bt_att_accept`. `bt_att_accept` initializes a connection's `struct bt_att`, so it must have been called before the application can make any GATT-request functions, right?

Comment (Thalley) [reply subsys/bluetooth/host/hci_core.h:482]: > I assume you are thinking of moving the capture of `k_current_get`? I looked a bit around and I think it can go into `bt_att_accept`. `bt_att_accept` initializes a connection's `struct bt_att`, so it must have been called before the application can make any GATT-request functions, right?

Correct. It looks like the call to `k_current_get` could/should be moved to some ATT function instead.

Comment (alwa-nordic) [reply subsys/bluetooth/host/hci_core.h:482]: Ok. We can move the variable to `att.c` and capture the thread id in `bt_att_accept`. The most meaningful variable I have in mind is the following:

```c
/** The thread ATT response handlers likely run on.
 *
 *  Blocking this thread while waiting for an ATT request to resolve can cause a
 *  deadlock.
 * 
 *  This can happen if the application queues ATT requests in the context of a
 *  callback from the Bluetooth stack. This is because queuing an ATT request
 *  will block until a request-resource is available, and the callbacks run on
 *  the same thread as the ATT response handler that frees request-resources.
 *
 *  The intended use of this value is to detect the above situation.
 */
static k_tid_t att_handle_rsp_thread;
```

@LingaoM Do you think this will function correctly?

Comment (carlescufi) [reply subsys/bluetooth/host/hci_core.h:482]: @LingaoM ping

**Comment by carlescufi** [comment]
@alwa-nordic @jhedberg @jori-nordic please review

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]
Just read the issue, looks alright, just checking that https://github.com/zephyrproject-rtos/zephyr/pull/43953#discussion_r829949477 doesn't go unanswered. Can you clarify why we need to check for the syswq @alwa-nordic ?
