### PR TITLE
net: Fix mDNS and LLMNR responders

### LINKED ISSUE #96201: MDNS responder broken by commit b60ae6f
### Describe the bug

Since commit b60ae6f, the default hostname zephyr.local is not resolved anymore, when zephyr is acting as MDNS responder.

### Regression

- [ ] This is a regression.

### Steps to reproduce

ping zephyr.local

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rlubos**
Align with `dns_unpack_query()` change (skip initial dot from DNS labels) from https://github.com/zephyrproject-rtos/zephyr/commit/b60ae6fb1ac24339cde1c568a61a089517a9b3ef.

Fixes #96201

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]

File: subsys/net/lib/dns/llmnr_responder.c [hunk 1]
```diff
@@ -192,23 +192,19 @@ static void setup_dns_hdr(uint8_t *buf, uint16_t answers, uint16_t dns_id)
...
 
-	while ((dot = strchr(dot, '.'))) {
-		if (!prev) {
-			prev = dot++;
-			continue;
-		}
+	/* For the length of the first label. */
+	query->len += 1;
 
+	while ((dot = strchr(dot, '.'))) {
```
Comment (pdgendt) [inline subsys/net/lib/dns/llmnr_responder.c]: Since you're touching this

```suggestion
	while ((dot = strchr(dot, '.')) != NULL) {
```

File: subsys/net/lib/dns/mdns_responder.c [hunk 2]
```diff
@@ -274,23 +274,19 @@ static void setup_dns_hdr(uint8_t *buf, uint16_t answers)
...
 
-	while ((dot = strchr(dot, '.'))) {
-		if (!prev) {
-			prev = dot++;
-			continue;
-		}
+	/* For the length of the first label. */
+	query->len += 1;
 
+	while ((dot = strchr(dot, '.'))) {
```
Comment (pdgendt) [inline subsys/net/lib/dns/mdns_responder.c]:
```suggestion
	while ((dot = strchr(dot, '.')) != NULL) {
```

**Comment by rlubos** [comment]
Thanks @pdgendt, fixed both

**Review by pdgendt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
