### PR TITLE
drivers: adc: stm32: Disable ADC before calibration

### LINKED ISSUE #40936: STM32 ADC gets stuck in Calibration
**Describe the bug**
Here https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/adc/adc_stm32.c#L595 we try to calibrate the ADC, but at least on STM32G4, the ADC is not permitted to be calibrated unless the ADC is disabled. 

image

I discovered this bug while trying to use the sensor here: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/stm32_temp/stm32_temp.c#L116 which requests calibration. I saw the thread in question get stuck here: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/adc/adc_stm32.c#L337

I need help confirming this ADC disabled requirement on other STM32 models.

### PR DESCRIPTION
**Pull request by pdietl**
The STM32 docs state that the ADC may not be calibrated unless
the ADC is disabled (ADEN=0). This commit implements this constraint

Fixes #40936

Signed-off-by: Pete Dietl <petedietl@gmail.com>

### CODE REVIEW

File: drivers/adc/adc_stm32.c [hunk 1]
```diff
@@ -592,7 +592,12 @@ static int start_read(const struct device *dev,
 	!defined(CONFIG_SOC_SERIES_STM32F1X) && \
 	!defined(STM32F3X_ADC_V2_5) && \
 	!defined(CONFIG_SOC_SERIES_STM32L1X)
+		LL_ADC_Disable(adc);
```
Comment (FRASTM) [inline drivers/adc/adc_stm32.c:595]: Few lines above, the ADC has just been enabled after setting the oversampling bits, for the STM32L0x, but it seems that all soc requires ADSTART =0. 
Could we find and common combination to avoid disabling/waiting/enabling/disabling/re-enabling ?

Comment (pdietl) [reply drivers/adc/adc_stm32.c:595]: That is true for the G4 at least. Should we check the data sheets for all other STM32s? It seems like we can combine disabling the ADC for oversampling calibration setting.

image

Comment (pdietl) [reply drivers/adc/adc_stm32.c:595]: @FRASTM in regards to your comment in the issue, in  RM0008, it recommends calibrating once after power-on, so I suppose that is why requesting calibration before starting an ADC read is not supported in the code. Do you concur?

**Review by mbolivar-nordic — COMMENTED** [review]
@erwango I'm not sure what review you are requesting from me -- this looks like a pure SoC internal implementation change. But no objections.

**Comment by erwango** [comment]
> @erwango I'm not sure what review you are requesting from me -- this looks like a pure SoC internal implementation change. But no objections.

Followed a gh suggestion blindly. But indeed, I'm not sure what was the rationale. Let me remove you ;-)

**Comment by pdietl** [comment]
@FRASTM Just poking to make sure you saw my reply to your comment. I think fulfil your suggestion, if we assume that we don't want to allow additional calibration of an ADC after the initial calibration for the STM32F1 (as is currently implemented in the code), then I think I should be able to perform the setting of the oversampling bits and perform a calibration while the ADC is disabled, and then re-enable it after both are finished. Is this a better solution?

**Review by FRASTM — APPROVED** [review]
@pdietl as a second step PR,  your proposal to group is welcome

**Review by erwango — CHANGES_REQUESTED** [review]
Nack'ed to avoid merge before I can review

**Comment by pdietl** [comment]
> @pdietl as a second step PR, your proposal to group is welcome

I misunderstood and did it all at once 😅

**Comment by pdietl** [comment]
@FRASTM poke.

**Comment by pdietl** [comment]
@erwango can you review please :)

**Review by erwango — CHANGES_REQUESTED** [review]
@pdietl I'm sorry but this change is confusing as not exactly fitting the description.
I agree that current driver implementation doesn't help to make things clear, and this is what brings me to be extra careful on the claims and the changes.

**Comment by pdietl** [comment]
@erwango Should I remove the changes of combining the previous block with adc disabling? I can add that as another PR.

**Comment by erwango** [comment]
> @erwango Should I remove the changes of combining the previous block with adc disabling? I can add that as another PR.

This would be a good start. Thanks

**Comment by pdietl** [comment]
@erwango done

**Review by erwango — APPROVED** [review]

**Comment by pdietl** [comment]
Who can merge?

**Comment by erwango** [comment]
> Who can merge?

Need two +1 before merge. I asked @FRASTM to review again due to initial code change, so right now you still miss one +1
@FRASTM would you mind reviewing this once again?

**Comment by pdietl** [comment]
poke @FRASTM

**Review by FRASTM — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
