### PR TITLE
tests/bsim: Fix not detecting failures and hotfix l2cap buffer leak

### LINKED ISSUE #71507: tests/bsim/bluetooth/host/l2cap/credits/tests_scripts/l2cap_credits[_ecred].sh broken in main
**Describe the bug**
These two tests
tests/bsim/bluetooth/host/l2cap/credits/tests_scripts/l2cap_credits.sh 
tests/bsim/bluetooth/host/l2cap/credits/tests_scripts/l2cap_credits_ecred.sh 
are currently failing in main

**To Reproduce**
1. tests/bsim/bluetooth/host/l2cap/compile.sh
2. tests/bsim/bluetooth/host/l2cap/credits/tests_scripts/l2cap_credits.sh

**Expected behavior**
No failure

**Impact**
Broken CI in main for bsim tests

**Logs and console output**
```
...
d_00: @00:00:00.638712  [00:00:00.638,702] <dbg> main: l2cap_chan_send: chan 0x81d52a0 conn 0 data 0x81d5200 len 130
d_00: @00:00:00.638712 ERROR: (ZEPHYR_BASE/tests/bsim/bluetooth/host/l2cap/credits/src/main.c:47): No more memory
d_00: @00:00:00.638712  The TESTCASE FAILED (test return code 2)
```

**Environment (please complete the following information):**
 - OS: Linux, CI
 - Toolchain host gcc 11/12
 - Commit SHA or Version used: Main as of now 4959a0241e3fd23875fac825a37228c3883633dd

**Additional context**
Introduced by https://github.com/zephyrproject-rtos/zephyr/commit/43de309b3e72e7784da9557d091a9bd71a46d7dc

### LINKED ISSUE #71508: failing bsim tests do not fail CI
**Describe the bug**
Failing bsim tests are currently not failing CI

**To Reproduce**
Submit a test which fails and see it not fail CI

**Expected behavior**
Failing CI

**Impact**
Failures can get in

**Logs and console output**
N/A

**Environment (please complete the following information):**
- OS: Linux, CI
- Toolchain host gcc 11/12
-  Commit SHA or Version used: Main as of now 4959a0241e3fd23875fac825a37228c3883633dd

**Additional context**
Introduced by https://github.com/zephyrproject-rtos/zephyr/commit/b0339136c1813f616e766ff04f88d08d7cabf418

### PR DESCRIPTION
**Pull request by aescolar**
b0339136c1813f616e766ff04f88d08d7cabf418
Broke the check for failed bsim tests.
Let's fix it.

---

And while CI was not failing, 43de309b3e72e7784da9557d091a9bd71a46d7dc.
broke 2 l2cap bsim tests. => Let's fix the issue

Fixes #71508
Fixes #71507

### CODE REVIEW

**Review by alxelax — DISMISSED** [review]

**Review by PavelVPV — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

**Review by alxelax — DISMISSED** [review]

**Review by PavelVPV — DISMISSED** [review]

**Review by jori-nordic — APPROVED** [review]

**Comment by aescolar** [comment]
@PavelVPV @alxelax now with a forward fix instead of a revert, thanks to @jori-nordic

**Review by alxelax — APPROVED** [review]

File: subsys/bluetooth/host/l2cap.c [hunk 1]
```diff
@@ -2017,7 +2017,7 @@ static int l2cap_chan_le_send_sdu(struct bt_l2cap_le_chan *ch,
 		sent += ret;
 
 		/* If the current buffer has been fully consumed, destroy it */
-		if (ret == rem_len) {
+		if (sent == rem_len) {
```
Comment (Thalley) [inline subsys/bluetooth/host/l2cap.c:2020]: Is `rem` in `rem_len` short for `remaining`?

Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:2020]: yes

**Review by PavelVPV — APPROVED** [review]
