### PR TITLE
Disable LSAN "at exit" leak checking when building for 64-bit targets with GCC

### LINKED ISSUE #20122: Deadlock in ASAN leak detection on exit
**Describe the bug**

Running sanitycheck with address sanitizer (ASAN) enabled could lead to deadlock on native_posix_64 board. The deadlock occurs during program exit and if the leak sanitizer (LSAN) functionality is disabled the deadlock does not occur. 

Note that the problem does not occur on native_posix board as LSAN is not supported on i386.

**To Reproduce**

Based on PR https://github.com/zephyrproject-rtos/zephyr/pull/19093

1. sanitycheck -N -p native_posix_64 --enable-asan --enable-lsan
2. wait for deadlock

**Expected behavior**
No deadlock occurs 

**Impact**
LSAN functionality can not be used in CI run

**Environment**
 - OS: Linux
 - Toolchain: Host (gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0)
 - Version: PR https://github.com/zephyrproject-rtos/zephyr/pull/19093 with as base c1ea45280bffc4a43037a56893a6644bc6520e46

Note that deadlock is also seen in CI runs

**Additional context**

_GDB Debug info:_
```
(gdb) i th
  Id   Target Id                                                Frame
* 1    Thread 0x7f32e9966780 (LWP 24999) "zephyr.exe"           0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  2    Thread 0x7f32e42fe700 (LWP 25002) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  3    Thread 0x7f32e3afd700 (LWP 25003) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  4    Thread 0x7f32e32fc700 (LWP 25004) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  5    Thread 0x7f32e4aff700 (LWP 25005) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  6    Thread 0x7f32e2afb700 (LWP 25006) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  7    Thread 0x7f32e22fa700 (LWP 25007) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  8    Thread 0x7f32e1af9700 (LWP 25008) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  9    Thread 0x7f32e12f8700 (LWP 25009) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  10   Thread 0x7f32e0af7700 (LWP 25010) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  11   Thread 0x7f32e02f6700 (LWP 25011) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  12   Thread 0x7f32dfaf5700 (LWP 25012) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  13   Thread 0x7f32df2f4700 (LWP 25013) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  14   Thread 0x7f32deaf3700 (LWP 25014) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  15   Thread 0x7f32de2f2700 (LWP 25015) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
  16   Thread 0x7f32ddaf1700 (LWP 25016) "zephyr.exe" (Exiting) 0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
(gdb) bt
#0  0x00007f32e88b9eee in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
#1  0x00007f32e88c842c in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
#2  0x00007f32e88c8758 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
#3  0x00007f32e7e51615 in __cxa_finalize (d=0x7f32e8b0f420) at cxa_finalize.c:83
#4  0x00007f32e87dce03 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
#5  0x00007ffe29e7ceb0 in ?? ()
#6  0x00007f32e9787b73 in _dl_fini () at dl-fini.c:138
Backtrace stopped: frame did not save the PC
(gdb)
```

### PR DESCRIPTION
**Pull request by vanwinkeljan**
Disable "at exit" memory leak check by LSAN if building for a 64-bit target with GCC.
This is need to fix a potential deadlock in GCCs libasan implementation.

Fixes #20122

These commits where separated from PR #19093

### CODE REVIEW

File: subsys/debug/asan.c [hunk 1]
```diff
@@ -0,0 +1,20 @@
+/*
+ * Copyright (c) 2019 Jan Van Winkel <jan.van_winkel@dxplore.eu>
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <sanitizer/asan_interface.h>
```
Comment (aescolar) [inline subsys/debug/asan.c]: Is this include still needed?

**Review by aescolar — COMMENTED** [review]
Just one nit

File: subsys/debug/asan.c (hunk 1 above)
Comment (vanwinkeljan) [reply subsys/debug/asan.c]: It is not a hard requirement, but it contains the declaration  __asan_default_options

Comment (aescolar) [reply subsys/debug/asan.c]: Ok.. my thinking was that if this header is renamed or moved in any version of the library it would break for whoever faces it. While the declaration below would not cause trouble unless the function types themselves would change.
So it would seem safer to not have this include line?

Comment (vanwinkeljan) [reply subsys/debug/asan.c]: removed include file

File: CODEOWNERS [hunk 2]
```diff
@@ -337,6 +337,7 @@
 /subsys/bluetooth/mesh/                   @jhedberg @trond-snekvik @joerchan @Vudentz
 /subsys/cpp/                              @pabigot @vanwinkeljan
 /subsys/debug/                            @nashif
+/subsys/debug/asan.c                      @vanwinkeljan
```
[the remark this answers is not in the document]
Comment (vanwinkeljan) [reply CODEOWNERS]: done

**Review by aescolar — APPROVED** [review]

**Comment by andrewboie** [comment]
Have you reported this issue to upstream GCC, since from reading the linked GH issue this appears to be a compiler bug? I'd feel better about this workaround if we had some kind of confirmation that we have correctly root-caused it, and this isn't due to some weird race condition in our own code.

**Comment by vanwinkeljan** [comment]
> Have you reported this issue to upstream GCC

No but looks like there is a similar issue flagged:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88791

> ... and this isn't due to some weird race condition in our own code

I would assume  not as all threads are stuck in libasan code.

**Review by tyrantlizard77 — APPROVED** [review]
