### PR TITLE
Bluetooth: controller: nRF5x: Fix lll LF clock wait

### LINKED ISSUE #30480: Bluetooth: Controller: Advertising can only be started 2^16 times
**Describe the bug**
On Nordic devices, Bluetooth advertising can only be started ~2^16 times before all calls to `bt_le_adv_start` return `-EIO`.

```
rc = bt_le_adv_start(adv_param, adv_data, adv_data_len, scan_rsp_data, scan_rsp_len);
if (rc < 0) {
	LOG_ERR("Advertising failed to start: %d", rc);
	return;
}
k_sleep(K_MSEC(50));
rc = bt_le_adv_stop();
if (rc < 0) {
	LOG_ERR("Advertising failed to stop: %d", rc);
	return;
}
```
Will eventually result in :
```
[00:00:08.656,616] <wrn> bt_hci_core: opcode 0x200a status 0x03
[00:00:08.656,646] <err> bt_hci_core: Failed to start advertiser
[00:00:08.656,646] <err> app: Advertising failed to start: -5
```

The root cause of this issue is the failure to release `onoff_manager` dependencies in `lll_clock.c`
Each time advertising is started, we wait until the LF clock is ready:
`ll_adv_enable` -> `lll_clock_wait` -> `blocking_on` -> `onoff_request`

Each call to `blocking_on` adds an additional dependency via `onoff_request` that is never released with a call to `onoff_release`.
Eventually the `refs` counter will reach `UINT16_MAX`, which will cause `onoff_request` to always return `-EAGAIN`.

**To Reproduce**
Add the following to `clock_ready` in `lll_clock.c` to reduce reproduction time:
If the `refs` were being properly released, there is still a headroom of ~156 to allow for normal operation.
```
static bool first = true;
if (first) {
	printk("Overriding refs\n");
	mgr->refs = 65400;
	first = false;
}
```
Repeatedly call `bt_le_adv_start` and `bt_le_adv_stop` until `-EIO` is always observed.

**Expected behavior**
Advertising sets should be able to be started and stopped any number of times without errors.

**Impact**
This bug can only be recovered from by rebooting the device, as nothing will naturally reduce the reference count.
If a reboot is not triggered, the device can no longer be interacted with via Bluetooth.
For devices without physical access to the PCB, this bug bricks the device.

**Logs and console output**
Standard error messages are included above.

**Environment (please complete the following information):**
 - Zephyr 2.4

### PR DESCRIPTION
**Pull request by cvinayak**
Fix lll_clock_wait function to wait for LF clock to settle
only once after power up.

Regression introduced in commit 2b4763076eab ("bluetooth:
controller: Adapt to onoff clock control").

Fixes #30480.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by nordic-krch — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_clock.c [hunk 1]
```diff
@@ -66,10 +66,27 @@ int lll_clock_init(void)
...
+	mgr = z_nrf_clock_control_get_onoff(CLOCK_CONTROL_NRF_SUBSYS_LF);
+	err = blocking_on(mgr, LFCLOCK_TIMEOUT_MS);
+	if (err) {
+		return err;
+	}
+
+	err = onoff_release(mgr);
+	if (err <= 0) {
+		return -EIO;
+	}
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_clock.c:87]: @nordic-krch updated to fail if 0 or less, as it is required that LF clock remains on.

**Review by nordic-krch — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
