### PR TITLE
Bluetooth: controller: fix comparison of unsigned int to larger then or equal to 0

### LINKED ISSUE #58962: [Coverity CID: 318600] Macro compares unsigned to 0 in subsys/bluetooth/controller/ll_sw/ull_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c

Category: Integer handling issues
Function: `ll_iso_test_sdu_alloc`
Component: Bluetooth
CID: [318600](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318600)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L639

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #58979: [Coverity CID: 318621] Macro compares unsigned to 0 in subsys/bluetooth/controller/ll_sw/ull_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c

Category: Integer handling issues
Function: `ll_iso_read_test_counters`
Component: Bluetooth
CID: [318621](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318621)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L881

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #58983: [Coverity CID: 318625] Macro compares unsigned to 0 in subsys/bluetooth/controller/ll_sw/ull_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c

Category: Integer handling issues
Function: `ll_iso_test_end`
Component: Bluetooth
CID: [318625](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318625)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L1221

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #58985: [Coverity CID: 318627] Macro compares unsigned to 0 in subsys/bluetooth/controller/ll_sw/ull_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c

Category: Integer handling issues
Function: `ll_iso_receive_test`
Component: Bluetooth
CID: [318627](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318627)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L839

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #58986: [Coverity CID: 318628] Macro compares unsigned to 0 in subsys/bluetooth/controller/ll_sw/ull_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c

Category: Integer handling issues
Function: `ll_remove_iso_path`
Component: Bluetooth
CID: [318628](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318628)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L583

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #58996: [Coverity CID: 318640] Macro compares unsigned to 0 in subsys/bluetooth/controller/ll_sw/ull_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L747

Category: Integer handling issues
Function: `ll_iso_test_sdu_emit`
Component: Bluetooth
CID: [318640](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318640)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L747

```
741                             (sdu_frag->sdu.status == ISOAL_SDU_STATUS_VALID))) {
742                      cis->hdr.test_mode.rx_sdu_counter++;
743              }
744     
745              status = ISOAL_STATUS_OK;
746     
>>>     CID 318640:  Integer handling issues  (NO_EFFECT)
>>>     This greater-than-or-equal-to-zero comparison of an unsigned value is always true. "handle >= 0".
747      } else if (IS_SYNC_ISO_HANDLE(handle)) {
748              /* FIXME: Implement for sync receiver */
749              status = ISOAL_STATUS_ERR_SDU_EMIT;
750      } else {
751              /* Handle is out of range */
752              status = ISOAL_STATUS_ERR_SDU_EMIT;
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #58998: [Coverity CID: 318642] Macro compares unsigned to 0 in subsys/bluetooth/controller/ll_sw/ull_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L318

Category: Integer handling issues
Function: `ll_setup_iso_path`
Component: Bluetooth
CID: [318642](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=318642)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/7b2034aaecc4cb2a261973b10b2fa608b29d398c/subsys/bluetooth/controller/ll_sw/ull_iso.c#L318

```
312              stream_sync_delay = 0U; /* FIXME: */
313              framed = 0U; /* FIXME: pick the framing value from context */
314              max_octets = lll_iso->max_pdu;
315     #endif /* CONFIG_BT_CTLR_ADV_ISO */
316     
317     #if defined(CONFIG_BT_CTLR_SYNC_ISO)
>>>     CID 318642:  Integer handling issues  (NO_EFFECT)
>>>     This greater-than-or-equal-to-zero comparison of an unsigned value is always true. "handle >= 0".
318      } else if (IS_SYNC_ISO_HANDLE(handle)) {
319              struct ll_sync_iso_set *sync_iso;
320              struct lll_sync_iso *lll_iso;
321              uint16_t stream_handle;
322     
323              stream_handle = LL_BIS_SYNC_IDX_FROM_HANDLE(handle);
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by kruithofa**
Bluetooth: controller: fix comparison of unsigned int to larger then 0

Fixes a coverity issue where an unsigned integer is compared to be larger then or equal to 0

fixes #58998 
fixes #58986 
fixes #58985 
fixes #58996 
fixes #58983 
fixes #58979 
fixes #58962

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_iso_types.h [hunk 1]
```diff
@@ -9,11 +9,18 @@
 #define LL_BIS_ADV_HANDLE_BASE BT_CTLR_ADV_ISO_STREAM_HANDLE_BASE
 #define LL_BIS_ADV_IDX_FROM_HANDLE(conn_handle) \
 	((conn_handle) - (LL_BIS_ADV_HANDLE_BASE))
+/* Conditional compile to prevent coverity issue CWE570, comparison of unsigned int to 0 */
+#if defined(LL_BIS_ADV_HANDLE_BASE)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_iso_types.h:13]: If `LL_BIS_ADV_HANDLE_BASE` is defined, but is defined as 0, is `#if defined(LL_BIS_ADV_HANDLE_BASE)` still applied? 

I am wondering if this should have been `#if LL_BIS_ADV_HANDLE_BASE > 0` instead

**Review by Thalley — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_iso_types.h [hunk 2]
```diff
@@ -9,11 +9,18 @@
...
 #define LL_BIS_ADV_IDX_FROM_HANDLE(conn_handle) \
 	((conn_handle) - (LL_BIS_ADV_HANDLE_BASE))
+/* Conditional compile to prevent coverity issue CWE570, comparison of unsigned int to 0 */
+#if (LL_BIS_ADV_HANDLE_BASE > 0)
 #define IS_ADV_ISO_HANDLE(conn_handle) \
 	(((conn_handle) >= (LL_BIS_ADV_HANDLE_BASE)) && \
 	 ((conn_handle) <= ((LL_BIS_ADV_HANDLE_BASE) + \
 			    (BT_CTLR_ADV_ISO_STREAM_MAX) - 1U)))
 #else
+#define IS_ADV_ISO_HANDLE(conn_handle) \
```
Comment (erbr-ot) [inline subsys/bluetooth/controller/ll_sw/ull_iso_types.h:19]: If LL_BIS_ADV_HANDLE_BASE is NOT > 0 then it is 0 - right?

File: subsys/bluetooth/controller/ll_sw/ull_iso_types.h [hunk 3]
```diff
@@ -9,11 +9,18 @@
...
+	((conn_handle) <= ((LL_BIS_ADV_HANDLE_BASE) + \
```
Comment (erbr-ot) [inline subsys/bluetooth/controller/ll_sw/ull_iso_types.h:20]: so LL_BIS_ADV_HANDLE_BASE is not 'needed' here?

Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_iso_types.h:20]: Correct, but I would like to keep it this way so that the two formulas are as similar as possible

**Review by erbr-ot — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
