### PR TITLE
Bluetooth: Host: Fix RPA timer not running

### LINKED ISSUE #18150: [zephyr 1.14] Host does not change the RPA
**Describe the bug**
It happens (about 30%) that Zephyr host does not change the RPA. 

**To Reproduce**
To speed up RPA address rotation, set RPA timeout to 30 seconds ```CONFIG_BT_RPA_TIMEOUT=30```
0. Test using Zephyr bluetooth/shell app for both devices. peripheral (a) - (b) central
1a. bt init
1b. bt init
2a. bt clear all
2b. bt clear all
3a. bt advertise on
3b. bt connect REMOTE_RPA_ADDR (random)
4b. bt security 2
5b. bt disconnect
6. Observe Zephyr peripheral (a) does not change the RPA address

**Expected behavior**
Zephyr changes it's RPA every CONFIG_BT_RPA_TIMEOUT

**Screenshots or console output**
Observe RPA rotation that in frames #263 - #289
```
< HCI Command: LE Set Advertise Enable (0x08|0x000a) plen 1                                                                                                                                                                                                               #287 109.140400
        Advertising: Disabled (0x00)
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #288 109.140500
      LE Set Advertise Enable (0x08|0x000a) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Set Random Address (0x08|0x0005) plen 6                                                                                                                                                                                                                 #289 109.140900
        Address: 74:78:B8:C4:F8:AB (Resolvable)
          Identity type: Random (0x01)
          Identity: DD:AD:FB:8F:B7:AE (Static)
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #290 109.140900
      LE Set Random Address (0x08|0x0005) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Set Advertise Enable (0x08|0x000a) plen 1                                                                                                                                                                                                               #291 109.141200
        Advertising: Enabled (0x01)
```
After the connection, pairing, disconnection
```
< HCI Command: LE Add Device To Resolving List (0x08|0x0027) plen 39                                                                                                                                                                                                      #346 144.508200
        Address type: Random (0x01)
        Address: FE:69:8F:77:2F:49 (Static)
        Peer identity resolving key: 0fc94333d8498d9ac666b564b3f46abe
        Local identity resolving key: ebe0fd9e7d7dc8adf3c0f358006bc903
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #347 144.508400
      LE Add Device To Resolving List (0x08|0x0027) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Set Privacy Mode (0x08|0x004e) plen 8                                                                                                                                                                                                                   #348 144.508700
        01 49 2f 77 8f 69 fe 01                          .I/w.i..        
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #349 144.508800
      LE Set Privacy Mode (0x08|0x004e) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Set Address Resolution Enable (0x08|0x002d) plen 1                                                                                                                                                                                                      #350 144.509100
        Address resolution: Enabled (0x01)
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #351 144.509100
      LE Set Address Resolution Enable (0x08|0x002d) ncmd 1
        Status: Success (0x00)
> ACL Data RX: Handle 0 flags 0x02 dlen 21                                                                                                                                                                                                                                #352 144.509400
      SMP: Signing Information (0x0a) len 16
        Signature key: ef07c2b4509b247828ef6754bf6f5806
> HCI Event: Disconnect Complete (0x05) plen 4                                                                                                                                                                                                                            #353 149.849800
        Status: Success (0x00)
        Handle: 0
        Reason: Remote User Terminated Connection (0x13)
< HCI Command: LE Set Advertise Enable (0x08|0x000a) plen 1                                                                                                                                                                                                               #354 150.116400
        Advertising: Enabled (0x01)
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #355 150.116600
      LE Set Advertise Enable (0x08|0x000a) ncmd 1
        Status: Success (0x00)
> HCI Event: LE Meta Event (0x3e) plen 31                                                                                                                                                                                                                                 #356 717.366800
      LE Enhanced Connection Complete (0x0a)
        Status: Success (0x00)
        Handle: 0
        Role: Slave (0x01)
        Peer address type: Resolved Random (0x03)
        Peer address: FE:69:8F:77:2F:49 (Static)
        Local resolvable private address: 74:78:B8:C4:F8:AB (Resolvable)
          Identity type: Random (0x01)
          Identity: DD:AD:FB:8F:B7:AE (Static)
        Peer resolvable private address: 6E:63:9E:67:6D:9B (Resolvable)
          Identity type: Random (0x01)
          Identity: FE:69:8F:77:2F:49 (Static)
        Connection interval: 50.00 msec (0x0028)
        Connection latency: 0.00 msec (0x0000)
        Supervision timeout: 4000 msec (0x0190)
        Master clock accuracy: 0x07
< HCI Command: LE Set Random Address (0x08|0x0005) plen 6                                                                                                                                                                                                                 #357 717.367100
        Address: 65:FE:FA:57:AC:5A (Resolvable)
          Identity type: Random (0x01)
          Identity: DD:AD:FB:8F:B7:AE (Static)
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #358 717.367200
      LE Set Random Address (0x08|0x0005) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Set Advertise Enable (0x08|0x000a) plen 1                                                                                                                                                                                                               #359 717.367600
        Advertising: Enabled (0x01)
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #360 717.367700
      LE Set Advertise Enable (0x08|0x000a) ncmd 1
        Status: Connection Limit Exceeded (0x09)
```

Note the timestamps between LE Set Advertise Enable and LE Enhanced Connection Complete
```
> HCI Event: Command Complete (0x0e) plen 4                                                                                                                                                                                                                               #355 150.116600
      LE Set Advertise Enable (0x08|0x000a) ncmd 1
        Status: Success (0x00)
> HCI Event: LE Meta Event (0x3e) plen 31                                                                                                                                                                                                                                 #356 717.366800
      LE Enhanced Connection Complete (0x0a)
        Status: Success (0x00)
        Handle: 0
        Role: Slave (0x01)
        Peer address type: Resolved Random (0x03)
        Peer address: FE:69:8F:77:2F:49 (Static)
        Local resolvable private address: 74:78:B8:C4:F8:AB (Resolvable)
          Identity type: Random (0x01)
          Identity: DD:AD:FB:8F:B7:AE (Static)
        Peer resolvable private address: 6E:63:9E:67:6D:9B (Resolvable)
          Identity type: Random (0x01)
          Identity: FE:69:8F:77:2F:49 (Static)
        Connection interval: 50.00 msec (0x0028)
        Connection latency: 0.00 msec (0x0000)
        Supervision timeout: 4000 msec (0x0190)
        Master clock accuracy: 0x07
```
it's almost 10 minutes and Zephyr does not changed it's RPA address

[gap_priv_conn_bi_01_c.btsnoop.log](https://github.com/zephyrproject-rtos/zephyr/files/3485904/gap_priv_conn_bi_01_c.btsnoop.log)


**Environment (please complete the following information):**
 - nrf52840

### PR DESCRIPTION
**Pull request by joerchan**
The RPA timer should always be running, even with privacy supported by
the controller. In order to select an IRK to generate the private
the controller is instructed by provided an identity address.
If we want to advertise privately without providing an identity address
the host has to set the private address.

Fixes: #18150

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
This one will be added to host conformance backporting.

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by joerchan** [comment]
Re-requested reviews because I added another commit to write the KConfig defined RPA timeout to the controller.

**Review by carlescufi — APPROVED** [review]
LGTM

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -4230,6 +4230,22 @@ static int le_init(void)
 
 #if defined(CONFIG_BT_SMP)
 	if (BT_FEAT_LE_PRIVACY(bt_dev.le.features)) {
+		struct bt_hci_cp_le_set_rpa_timeout *cp;
+		buf = bt_hci_cmd_create(BT_HCI_OP_LE_SET_RPA_TIMEOUT,
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: Add an empty line after the variable definition (general coding style used throughout the tree)

File: subsys/bluetooth/host/hci_core.c [hunk 2]
```diff
@@ -4230,6 +4230,22 @@ static int le_init(void)
...
+					sizeof(*cp));
+		if (!buf) {
+			return -ENOBUFS;
+		}
+
+		cp = net_buf_add(buf, sizeof(*cp));
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: You could remove this empty line since the it kind of belongs together with what follows

File: subsys/bluetooth/host/hci_core.c [hunk 3]
```diff
@@ -4231,6 +4230,22 @@ static int le_init(void)
...
+		cp->rpa_timeout = sys_cpu_to_le16(CONFIG_BT_RPA_TIMEOUT);
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: I think you'll need an `#if defined(CONFIG_BT_PRIVACY)` somewhere before using the above Kconfig variable - I think that's why CI is currently failing.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Some minor cosmetic things and then a comment on the CI failure

File: subsys/bluetooth/host/hci_core.c (hunk 3 above)
Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c]: You are right, fixed.

**Review by jhedberg — APPROVED** [review]
