### PR TITLE
drivers: spi: stm32: Skip pinctrl setup for subghzspi

### LINKED ISSUE #41581: STM32 subghzspi fails pinctrl setup
**Describe the bug**
The subghzspi driver fails during initialization when setting up pinctrl.

It fails because subghzspi doesn't have any pinctrl states so `pinctrl_apply_state(..., PINCTRL_STATE_DEFAULT)` returns `-ENOENT` to indicate that the "default" state was not found, which is treated as an error by the driver. Modifying the code so that `-ENOENT` is not treated as an error or so that pinctrl setup is not done if `pcfg->state_cnt == 0` solves the problem.

I attempted a workaround by adding some "no-op" pinctrl in the subghzspi node, but this is not possible because `pinctrl-0` and `pinctrl-names` are blacklisted by its devicetree binding.

**To Reproduce**
Build and run the `subsys/lorawan/class_a` sample for `nucleo_stm32wl55jc` on a recent main.

```
*** Booting Zephyr OS build v2.7.99-2798-g66fef3123625  ***
[00:00:00.000,000] <err> spi_ll_stm32: SPI pinctrl setup failed (-2)
[00:00:00.000,000] <err> sx126x: Cannot get pointer to SUBGHZSPI device
[00:00:00.035,000] <err> os: ***** BUS FAULT *****
[00:00:00.035,000] <err> os:   Instruction bus error
[00:00:00.035,000] <err> os: r0/a1:  0x00000000  r1/a2:  0x200005a4  r2/a3:  0x20001f80
[00:00:00.035,000] <err> os: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x08003a4f
[00:00:00.035,000] <err> os:  xpsr:  0x61000000
[00:00:00.035,000] <err> os: Faulting instruction address (r15/pc): 0x09f7f6b4
[00:00:00.035,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.035,000] <err> os: Current thread: 0x20000348 (unknown)
[00:00:00.091,000] <err> os: Halting system
```

### PR DESCRIPTION
**Pull request by abxy**
Subghzspi instances cannot have any pinctrl configs,
they are blacklisted by the dts binding. This caused an
initialization failure of the spi_ll_stm32 driver for
subghzspi instance because no "default" pinctrl was found.
    
This commit solves the problem by skipping the pinctrl setup
for subghzpi devices. The use_subghzpi_nss property is used
to identify a subghzspi device, as this is a required boolean
property only available in the subghzspi binding this is a
perfect indicator for such instances.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/41581

### CODE REVIEW

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -823,6 +823,17 @@ static const struct spi_driver_api api_funcs = {
...
 
+static inline bool spi_stm32_is_subghzspi(const struct device *dev)
+{
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_spi_subghz)
+	const struct spi_stm32_config *cfg = dev->config;
+
+	return cfg->use_subghzspi_nss;
+#endif
+
+	return false;
```
Comment (fabiobaltieri) [inline drivers/spi/spi_ll_stm32.c:834]: I would put this in an #else case. The case where this results in two unconditional return does not feel quite right.

File: drivers/spi/spi_ll_stm32.c [hunk 2]
```diff
@@ -823,6 +823,17 @@ static const struct spi_driver_api api_funcs = {
...
 };
 
+static inline bool spi_stm32_is_subghzspi(const struct device *dev)
+{
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_spi_subghz)
+	const struct spi_stm32_config *cfg = dev->config;
+
+	return cfg->use_subghzspi_nss;
+#endif
+
```
Comment (FRASTM) [inline drivers/spi/spi_ll_stm32.c:833]: plus  ` ARG_UNUSED(dev) ` ?

**Review by FRASTM — COMMENTED** [review]
LGTM

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (abxy) [reply drivers/spi/spi_ll_stm32.c:834]: Agreed.

File: drivers/spi/spi_ll_stm32.c (hunk 2 above)
Comment (abxy) [reply drivers/spi/spi_ll_stm32.c]: Done.

**Review by fabiobaltieri — APPROVED** [review]

**Comment by erwango** [comment]
@abxy Would you mind rebasing ? There's something wrong with CI that prevent to have all green.

**Review by erwango — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
LGTM
