### PR TITLE
Bluetooth: Controller: Fix corruption during BIG_CHANNEL_MAP_IND

### LINKED ISSUE #64497: Bluetooth controller: Controller state corruption during BIS channel map indication
**Describe the bug**
The BT controller can/will get corrupted when the controller prepares to send a BIG_CHANNEL_MAP_IND . Resulting in undefined misbehavior after.

In detail:
`radio_pkt_big_ctrl_get()` returns a statically allocated buffer of type pdu_big_ctrl, but the callers expect a full pdu_bis, and use it as such, overflowing the statically allocated buffer, and smashing other variables after.

**To Reproduce**
Steps to reproduce the behavior (tricky) :
* Fetch this branch https://github.com/aescolar/zephyr/commit/282f06645efcc24c3b13242b5c14fb17bc5b2321 
* BOARD=nrf5340bsim_nrf5340_cpuapp WORK_DIR=${ZEPHYR_BASE}/bsim_out nice tests/bsim/bluetooth/compile.nrf5340bsim_nrf5340_cpuapp.sh 
* BOARD=nrf5340bsim_nrf5340_cpuapp tests/bsim/bluetooth/ll/bis/tests_scripts/broadcast_iso.sh 
* Note: The exact behavior, and therefore a visible failure will depend on how the compiler decides to layout the variables in memory.

**Expected behavior**
No controller status corruption.

**Impact**
Crash/undefined behavior after preparing a BIG_CHANNEL_MAP_IND, or other control procedures.

**Logs and console output**
```
[..]
d_01: @00:00:07.613373  (CPU:0): Periodic Advertising and ISO Channel Map Update...success.
d_01: @00:00:07.626771 ERROR: (modules/bsim_hw_models/nrf_hw_models/src/HW_models/NHW_TIMER.c:532): nhw_timer_regw_sideeffects_CC: Attempted to access non existing register TIMER4.CC[31] (>= 8)
```
See in this screenshot the status just before smashing sw_tifs_toggle in the memcpy():
image

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 22.04)
 - Toolchain (e.g Zephyr SDK, ...): Host gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
 - Commit SHA or Version used: 
   * The issue is in main as of now
   * But to reproduce fetch this branch:  ( https://github.com/aescolar/zephyr/commit/282f06645efcc24c3b13242b5c14fb17bc5b2321 )

### PR DESCRIPTION
**Pull request by aescolar**
radio_pkt_big_ctrl_get() returns a statically allocated
buffer of type pdu_big_ctrl, but the callers expect a
buffer where a whole PDU for a BIG control packet can fit
(not just space for the payload),
and use it as such, overflowing this statically
allocated buffer, and smashing other variables after.

Let's fix it by allocating a buffer of the correct size
to fit a BIG control PDU.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/64497

### CODE REVIEW

**Review by cvinayak — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 1]
```diff
@@ -673,7 +673,7 @@ void *radio_pkt_decrypt_get(void)
 /* Dedicated Rx PDU Buffer for Control PDU independent of node_rx with BIS Data
  * PDU buffer
  */
-static uint8_t pkt_big_ctrl[sizeof(struct pdu_big_ctrl)];
+static uint8_t pkt_big_ctrl[sizeof(struct pdu_bis)];
```
Comment (kruithofa) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:676]: it would be good to explain why we use the size of a pdu_bis structure, and not the pdu_big_ctrl structure

Comment (aescolar) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:676]: The buffer use is now clarified in the comment. I hope you like it :)

**Review by kruithofa — DISMISSED** [review]

**Review by cvinayak — DISMISSED** [review]

**Review by kruithofa — DISMISSED** [review]

**Review by cvinayak — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
