### PR TITLE
drivers: serial: stm32: Make it compatible with runtime PM on console

### LINKED ISSUE #63367: stm32: pm: Console device stuck if runtime PM device is enabled
**Describe the bug**

Console will hang when enabling Runtime Device Power Mgmt on STM32 devices

When runtime PM device is enabled, console will drive device enable/disable (since https://github.com/zephyrproject-rtos/zephyr/pull/53979)
On STM32 UART, enabling PM enables IT handling.

Since clock is not enabled on IT expiry, UART is stuck in ISR.

**To Reproduce**
Enable PM_DEVICE_RUNTIME_EXCLUSIVE and CONSOLE on STM32

**Expected behavior**
Console should work seemlessly

**Impact**
Cannot use console on STM32 with CONFIG_PM_DEVICE_RUNTIME_EXCLUSIVE=y

### PR DESCRIPTION
**Pull request by erwango**
Since #53979, runtime PM can be applied on serial device used by console. While it should be transparent on serial driver side as the application (console in this case) is driving the PM runtime requests, on STM32 it requires some modification on serial driver as UART interrupts are generated to handle internal power management house cleaning. When these interrupts are generated, PM runtime should also be driven to ensure clock availability when treating the uart ISR. On STM32, some additional changes are required

Fixes #63367

### CODE REVIEW

**Review by gautierg-st — DISMISSED** [review]

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -674,6 +675,11 @@ static void uart_stm32_poll_out_visitor(const struct device *dev, void *out, pol
 		/* Enable TC interrupt so we can release suspend
```
Comment (JordanYates) [inline drivers/serial/uart_stm32.c:675]: Comment is no longer on the appropriate code piece

Comment (erwango) [reply drivers/serial/uart_stm32.c]: Fixed, thanks

File: drivers/serial/uart_stm32.c [hunk 2]
```diff
@@ -671,9 +672,15 @@ static void uart_stm32_poll_out_visitor(const struct device *dev, void *out, pol
...
 
+		/* Resume device if needed before enabling IT */
+		if (pm_device_runtime_is_enabled(dev)) {
+			(void)pm_device_runtime_get(dev);
+		}
+
 		/* Enable TC interrupt so we can release suspend
 		 * constraint when done
 		 */
+
```
Comment (fabiobaltieri) [inline drivers/serial/uart_stm32.c:683]: leftover?

**Review by fabiobaltieri — DISMISSED** [review]

File: drivers/serial/uart_stm32.c (hunk 2 above)
Comment (erwango) [reply drivers/serial/uart_stm32.c]: Yep. Fixed. Thanks

**Review by fabiobaltieri — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
