### PR TITLE
shell: mqtt: fix uint32_t compared against 0

### LINKED ISSUE #59563: [Coverity CID: 321096] Unsigned compared against 0 in subsys/shell/backends/shell_mqtt.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/ce3317d03e46e1a218af3e712383d9216c48a992/subsys/shell/backends/shell_mqtt.c

Category: Control flow issues
Function: `mqtt_evt_handler`
Component: Shell
CID: [321096](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=321096)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/ce3317d03e46e1a218af3e712383d9216c48a992/subsys/shell/backends/shell_mqtt.c#L590

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by ycsin**
Fix unsigned compared against 0 reported by coverity check. CID: 321096

fixes #59563

### CODE REVIEW

**Review by kartben — DISMISSED** [review]

File: subsys/shell/backends/shell_mqtt.c [hunk 1]
```diff
@@ -581,18 +583,19 @@ static void mqtt_evt_handler(struct mqtt_client *const client, const struct mqtt
 
 		while (payload_left > 0) {
 			/* Attempt to claim `payload_left` bytes of buffer in rb */
-			size = ring_buf_put_claim(&sh_mqtt->rx_rb, &sh_mqtt->rx_rb_ptr,
+			size = (size_t)ring_buf_put_claim(&sh_mqtt->rx_rb, &sh_mqtt->rx_rb_ptr,
 						  payload_left);
```
Comment (pdgendt) [inline subsys/shell/backends/shell_mqtt.c:587]: Nit: `payload_lef` indentation

Comment (ycsin) [reply subsys/shell/backends/shell_mqtt.c]: ooops, fixed, thanks

**Review by pdgendt — APPROVED** [review]

**Review by kartben — APPROVED** [review]
