### PR TITLE
arc: stack guard: bug fix with multi push stack situation

### LINKED ISSUE #29139: tests/kernel/fatal/exception failed on nsim_sem_mpu_stack_guard board
**To Reproduce**
1. west build -b nsim_sem_mpu_stack_guard -p auto tests/kernel/fatal/exception
2. west flash
3. See error

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.4.0-557-gdc37f988e030  ***
Running test suite fatal
===================================================================
START - test_fatal
test alt thread 1: generic CPU exception
E: ***** Exception vector: 0x8, cause code: 0x0, parameter 0x0
E: Address 0x3c4
E: EV_SWI
E:  r0: 0x00000000  r1: 0x00000000  r2: 0x00000000  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x00000000  r7: 0xfffffff5
E:  r8: 0x00000000  r9: 0x00000000 r10: 0x00000000 r11: 0x00000000
E: r12: 0x000003bc r13: 0x00000000  pc: 0x000003c4
E:  blink: 0x00000f5c status32: 0x80300002
E: lp_end: 0x00000000 lp_start: 0x00000000 lp_count: 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 0
test alt thread 2: initiate kernel oops
E:  r0: 0x00000003  r1: 0x00000000  r2: 0x00000031  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x00000000  r7: 0xfffffff5
E:  r8: 0x80000110  r9: 0x00000031 r10: 0x80000040 r11: 0x80000110
E: r12: 0x000003d4 r13: 0x00000000  pc: 0x000003e6
E:  blink: 0x00000f5c status32: 0x00300002
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 3
test alt thread 3: initiate kernel panic
E:  r0: 0x00000004  r1: 0x00000000  r2: 0x00000031  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x00000000  r7: 0xfffffff5
E:  r8: 0x80000110  r9: 0x00000031 r10: 0x80000040 r11: 0x80000110
E: r12: 0x000003e8 r13: 0x00000000  pc: 0x000003fa
E:  blink: 0x00000f5c status32: 0x00300002
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 4
test alt thread 4: fail assertion
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/tests/kernel/fatal/exception/src/main.c:124
        intentionally failed assertion
E:  r0: 0x00000004  r1: 0x0000007c  r2: 0x80000040  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000001  r6: 0x00000020  r7: 0xffffffff
E:  r8: 0x80000110  r9: 0x00000031 r10: 0x80000040 r11: 0x80000110
E: r12: 0x00001000 r13: 0x0000c5f0  pc: 0x00001580
E:  blink: 0x00000452 status32: 0x80300602
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 4
test alt thread 5: initiate arbitrary SW exception
E:  r0: 0x7fffffff  r1: 0x00000000  r2: 0x00000031  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x00000000  r7: 0xfffffff5
E:  r8: 0x80000110  r9: 0x00000031 r10: 0x80000040 r11: 0x80000110
E: r12: 0x000003fc r13: 0x000029fe  pc: 0x00000418
E:  blink: 0x00000f5c status32: 0x00300002
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 2147483647: Unknown error on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 2147483647
test stack HW-based overflow - supervisor 1
E: ***** Exception vector: 0x6, cause code: 0x2, parameter 0x4
E: Address 0x80001554
E: EV_ProtV
E: Memory write protection violation (MPU)
E:  r0: 0x00000000  r1: 0x00000000  r2: 0x00000000  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x00000000  r7: 0x00000005
E:  r8: 0x80000110  r9: 0x00000031 r10: 0x80000040 r11: 0x80000110
E: r12: 0x000000d8 r13: 0x000029fe  pc: 0x00000078
E:  blink: 0x0000008c status32: 0x80300002
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 2
test stack HW-based overflow - supervisor 2
E: ***** Exception vector: 0x6, cause code: 0x2, parameter 0x4
E: Address 0x80001554
E: EV_ProtV
E: Memory write protection violation (MPU)
E:  r0: 0x00000000  r1: 0x00000000  r2: 0x00000000  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x00000000  r7: 0x00000005
E:  r8: 0x80000110  r9: 0x00000031 r10: 0x80000040 r11: 0x80000110
E: r12: 0x000000d8 r13: 0x000029fe  pc: 0x00000078
E:  blink: 0x0000008c status32: 0x80300002
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 2
test stack HW-based overflow - user 1
E: ***** Exception vector: 0x6, cause code: 0x2, parameter 0x4
E: Address 0x80001554
E: EV_ProtV
E: Memory write protection violation (MPU)
E:  r0: 0x00000000  r1: 0x00000000  r2: 0x00000000  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x00000000  r7: 0x00000000
E:  r8: 0x00000000  r9: 0x00000000 r10: 0x00000000 r11: 0x00000000
E: r12: 0x000000d8 r13: 0x00000000  pc: 0x00000078
E:  blink: 0x0000008c status32: 0x80300082
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 2
test stack HW-based overflow - user 2
E: ***** Exception vector: 0x6, cause code: 0x2, parameter 0x4
E: Address 0x80001554
E: EV_ProtV
E: Memory write protection violation (MPU)
E:  r0: 0x00000000  r1: 0x00000000  r2: 0x00000000  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x00000000  r7: 0x00000000
E:  r8: 0x00000000  r9: 0x00000000 r10: 0x00000000 r11: 0x00000000
E: r12: 0x000000d8 r13: 0x00000000  pc: 0x00000078
E:  blink: 0x0000008c status32: 0x80300082
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 2
test stack HW-based overflow - user priv stack 1
E: ***** Exception vector: 0x6, cause code: 0x2, parameter 0x4
E: Address 0x80001158
E: EV_ProtV
E: Memory write protection violation (MPU)
E:  r0: 0x00000000  r1: 0x00000000  r2: 0x00000000  r3: 0x00000000
E:  r4: 0x00000000  r5: 0x00000000  r6: 0x000000b8  r7: 0x8000150c
E:  r8: 0x00000000  r9: 0x00000000 r10: 0x00000000 r11: 0x00000000
E: r12: 0x0000010c r13: 0x800002e8  pc: 0x00000078
E:  blink: 0x0000008c status32: 0x80300002
E: lp_end: 0x00000000 lp_start: 0x00000030 lp_count: 0x80000040
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80000040 (unknown)
Caught system error -- reason 0
Wrong crash type got 0 expected 2
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: [dc37f988](https://github.com/zephyrproject-rtos/zephyr/commit/dc37f988e03029d43fb3c92d4f2f966e0c90e435)

### PR DESCRIPTION
**Pull request by IRISZZW**
accessing the stack below guard_end is always a bug. some
instrustions (like enter_s {r13-r26, fp, blink}) push a collection
of registers on to the stack. In this situation, the fault_addr will
less than guard_end, but sp will greater than guard_end.

```
|------stack base-------| <--- high address
|                       |
|                       | <--- sp
|------stack top--------|
|------guard_end--------|
|                       | <--- fault_addr
|                       |
|------guard_start------| <--- low address
```

the max number of multi push operation is 16 registers, and one
register is 4 byte, so sp should no greater than guard_end + 64.

Fix: #29139

### CODE REVIEW

File: arch/arc/core/fault.c [hunk 1]
```diff
@@ -91,7 +91,14 @@ static bool z_check_thread_stack_fail(const uint32_t fault_addr, uint32_t sp)
...
 	  */
-	if (sp <= guard_end && fault_addr < guard_end &&
+
+	 /* accessing the stack below guard_end is always a bug.
+	  * the "+ 64" is there due to some instrustions (like
+	  * enter_s {r13-r26, fp, blink}) push a collection of registers
+	  * on to the stack, the max value is 16 registers, and one register
+	  * is 4 byte, so we need 64.
+	  */
+	if (sp <= (guard_end + 64) && fault_addr < guard_end &&
```
Comment (abrodkin) [inline arch/arc/core/fault.c:101]: Please use a definition instead of hard-coded `64`. And for newly added `#define` add a comment explaining its value.

**Review by abrodkin — CHANGES_REQUESTED** [review]

File: arch/arc/core/fault.c (hunk 1 above)
Comment (ruuddw) [reply arch/arc/core/fault.c:101]: Hmm, don't really like this offset, not sure it handles all cases (e.g. other sp relative indexing cases - not sure if that's possible, but in assembly code it could be valid.)
Is the check of the fault address not enough? That's what indicates an access to the guard area. If an additional check on sp is required, why not check if sp is within the base-top region?

Comment (IRISZZW) [reply arch/arc/core/fault.c:101]: @ruuddw This function performs an assessment whether a memory fault (on a given memory address) is the result of a stack overflow of the current thread. so, it hard to cover all cases, peculiarly some malicious codes which change sp directly.

Comment (ruuddw) [reply arch/arc/core/fault.c]: My point was more why is there the check on sp at all? Is it needed? The 64 bytes magic number feels like a patch that solves this testcase, but might not be robust for other testcases. Hence my proposed other check for sp, to still have some additional checking but more robust. But, strictly speaking it shouldn't be required, checking EFA should be enough I think.

Comment (IRISZZW) [reply arch/arc/core/fault.c]: checking EFA is not enough, thinking about this situation: we define a pointer, point to guard area, and operate it. we need to distinguish this situation with stack overflow. In stack overflow situation, the sp <= (guard_end + 64). Linux has done some  
similar checking, I take a reference from it: https://elixir.bootlin.com/linux/v2.6.39.4/source/arch/x86/mm/fault.c#L1108. 
This checking is not enough but necessary.

Comment (ruuddw) [reply arch/arc/core/fault.c]: Well, any access to the guard area could be considered a stack issue: they are likely stack indexed accesses or related.
Can't there be false positives with the offset of 64 bytes as well?
Also, with MPU minimal regions of 32 bytes, 64 bytes could also be larger than the guard region (or very small stacks...).

**Review by ruuddw — APPROVED** [review]

**Review by YuguoWH — APPROVED** [review]

**Review by abrodkin — CHANGES_REQUESTED** [review]

File: arch/arc/core/fault.c [hunk 2]
```diff
@@ -31,6 +31,13 @@ static const struct z_exc_handle exceptions[] = {
 #endif
 
 #if defined(CONFIG_MPU_STACK_GUARD)
+
+/* The large cushion allows instructions like enter_s to work.
+ * "enter_s {r13-r26, fp, blink}" pushes max 16 registers, one register
+ * is 4 byte, so cushion should no greater than 64
+ */
+#define STACK_GUARD_CUSHION 64
```
[the remark this answers is not in the document]
Comment (ruuddw) [reply arch/arc/core/fault.c:39]: And when SecureShield is configured, the full register file can get pushed to the stack (when a normal interrupt preempts a secure mode thread).
As discussed before, maybe the complete SP check can be removed? Trade-off here is if we prefer 'false' classifications of MPU stack guard area accesses as stack error or as general mpu error. The faults get caught anyway, this is just about classification: don't see a strong need for the extra check to only report stack pointer accesses to guard area as stack error, instead of all accesses. E.g. overflow to an array/pointer to a stack object: is it a stack error or general MPU error?
What semantics do other architectures handle?

[the remark this answers is not in the document]
Comment (IRISZZW) [reply arch/arc/core/fault.c:39]: only arc and arm have MPU_STACK_GUARD, and arm didn't do special handler for this case. But I believe they will have similar problem.

https://github.com/zephyrproject-rtos/zephyr/blob/41b7e5da7b453ce6ec648e29825f3e71048b498a/arch/arm/core/aarch32/thread.c#L213-L219

I have run sanity check with removal of the SP check, and all tests passed. So should me just remove it ?

[the remark this answers is not in the document]
Comment (ruuddw) [reply arch/arc/core/fault.c:39]: My preference would be to simply remove it: any access to a stack guard can be argued to be a stack violation...
And, it would be more robust over different scenario's of hardware pushing context to the stack.
@abrodkin: what do you think?

[the remark this answers is not in the document]
Comment (abrodkin) [reply arch/arc/core/fault.c:39]: Agree, given we already have a lot of complex stuff in many places it would be good at least no introduce more of that w/o very good reason. That's said let's just remove `SP` check here completely: if there's an attempt to access memory in a "guarded" area for any reason we should get an exception and get to the real root cause.

BTW it's not clear to me how this change (even if we accept it as was initially proposed) fixes https://github.com/zephyrproject-rtos/zephyr/issues/29139. Don't we just need to allocate a larger stack in that faulty test?

[the remark this answers is not in the document]
Comment (ruuddw) [reply arch/arc/core/fault.c:39]: The test tests if a stack overflow is reported as stack error: it currently is reported as MPU memory error and the test fails.
I believe there are no tests that test if a general pointer access to the guard area is reported as stack or MPU error (at most it is tested if an exception is raised, not what type of exception) -> so no risk of false positives in the tests.

**Review by ruuddw — APPROVED** [review]
Good we converged on the best solution, this looks fine now.

**Review by abrodkin — COMMENTED** [review]
Why do we keep mentioning `SP` even if we no longer care of that?
Maybe just stop at saying " Treat any MPU exceptions within the guard region as a stack overflow"?

@ruuddw?

**Comment by ruuddw** [comment]
> Why do we keep mentioning `SP` even if we no longer care of that?
> Maybe just stop at saying " Treat any MPU exceptions within the guard region as a stack overflow"?

You mean in the code comment? I think that's ok - it explains why checking the sp does not always work.

**Review by abrodkin — APPROVED** [review]

**Comment by ruuddw** [comment]
Any reason for not merging this PR? It will make twister for all nsim boards clean again.
