### PR TITLE
subsys/fs/littlefs: fix Coverity issues

### LINKED ISSUE #18392: [Coverity CID :203494]Integer handling issues in /subsys/fs/littlefs_fs.c
Static code scan issues seen in File: /subsys/fs/littlefs_fs.c
 Category: Integer handling issues
 Function: littlefs_mount
 Component: Other
 CID: 203494
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #18458: [Coverity CID :203422]Memory - illegal accesses in /tests/subsys/fs/littlefs/src/testfs_util.c
Static code scan issues seen in File: /tests/subsys/fs/littlefs/src/testfs_util.c
 Category: Memory - illegal accesses
 Function: testfs_path_init
 Component: Tests
 CID: 203422
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by pabigot**
Closes #18392 by asserting if the block size is not positive.

Closes #18458.  The diagnosis here was not relevant as an in-range EOS
is written before the buffer is used, but using the non-terminated
length is slightly more clear about intent and may avoid a read overrun
of the mount point.

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>

### CODE REVIEW

File: subsys/fs/littlefs_fs.c [hunk 1]
```diff
@@ -595,6 +595,7 @@ static int littlefs_mount(struct fs_mount_t *mountp)
 	if (block_size == 0) {
 		block_size = get_block_size(fs->area);
 	}
+	__ASSERT_NO_MSG(block_size > 0);
```
Comment (ioannisg) [inline subsys/fs/littlefs_fs.c]: This won't make you skip the coverity report of divide-by-zero, imho.
If this should never happen, could we return after the ASSERT?

Comment (pabigot) [reply subsys/fs/littlefs_fs.c]: Well, I guess.  There's lots of places in Zephyr where if you make it past an ASSERT you're going to blow up.  And really I don't think you can have a flash area with no regions with a positive block size.   But since we're trying to placate Coverity I think the rework should do it.

**Review by ioannisg — APPROVED** [review]

**Review by wentongwu — APPROVED** [review]
