### PR TITLE
net: Fix inet_pton when offloading is enabled

### LINKED ISSUE #12441: include: net: Link error when inet_pton() is used and wifi offloading is enabled
**Describe the bug**
When wifi offloading is enabled on the cc3220sf_launchxl, a call to inet_pton() would cause a link error similar to the following:

```
    ../app/libapp.a(main.c.obj): In function `zsock_inet_pton':
    /home/zephyr-work/samples/net/mqtt_publisher/build/zephyr/include/generated/syscalls/socket.h:33: undefined reference to `_impl_zsock_inet_pton'
```

**To Reproduce**
1. add a call to inet_pton in main()
2. mkdir build; cd build
2. cmake .. -DBOARD=cc3220xl_launchxl
3. make

**Expected behavior**
I expect the code to build.

**Impact**
This prevents applications from using inet_pton() when wifi offloading is enabled.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK  0.9.5
 - Commit SHA where this was reproduced: b3bb689cab6826e7a9162c2d4dfc3b3687adc0ae

### PR DESCRIPTION
**Pull request by vanti**
When offloading is enabled, a call to inet_pton() results in a call to
zsock_inet_pton() based on its implementation in include/net/socket.h.
This eventually leads to a call to _impl_zsock_inet_pton(), which is
not defined when offloading is enabled.

In this commit, we have chosen to directly call net_addr_pton() in
inet_pton() in the offload case to be efficient, and keep the
implementation as it is when offload is not enabled.

Fixes #12441

Signed-off-by: Vincent Wan <vincent.wan@linaro.org>

### CODE REVIEW

File: include/net/socket.h [hunk 1]
```diff
@@ -275,6 +280,21 @@ struct addrinfo {
 };
 
 #include <net/socket_offload.h>
+
+static inline int inet_pton(sa_family_t family, const char *src, void *dst)
```
Comment (GAnthony) [inline include/net/socket.h]: As we discussed offline, the other alternative would have been to add this into the socket_offload_ops.h table, but this looks like the simpler approach.

**Review by GAnthony — APPROVED** [review]
LGTM.

**Review by jukkar — COMMENTED** [review]
Is there similar issue with a call to inet_ntop()?

File: include/net/socket.h (hunk 1 above)
Comment (vanti) [reply include/net/socket.h]: Yes, if we decide to truly offload this operation in the future (by calling into a SimpleLink-based API), we can revisit this and add that extra function pointer.

**Review by jukkar — APPROVED** [review]
