### PR TITLE
tests: drivers: dma: configure alignment based on devicetree

### LINKED ISSUE #98949: tests: drivers: dma: alignment not configurable
### Describe the bug

I am writing a DMA driver for Tenstorrent hardware. Our DMA expects a data alignment of 64 bytes, however the upstream test suite hardcodes the alignment to be 32 bytes. Our DMA hardware can not support this.

The fix would be to read the alignment size from the devicetree, to allow it to be configured to 64 bytes.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Run upstream DMA tests for Tenstorrent's DMA driver on Tenstorrent hardware, and it will fail due to the data being misaligned.

```
../zephyr/scripts/twister -i -p tt_blackhole@p100a/tt_blackhole/smc --device-testing --west-flash --flash-before --device-serial-pty /tmp/tt-console --alt-config-root test-conf/tests -T ../zephyr/tests -s drivers.dma.chan_blen_transfer -vvv
```

### Relevant log output

```shell
*** Booting Zephyr OS build v4.2.0-4835-gb4d5cd3c4746 ***
Running TESTSUITE dma_m2m_sg
===================================================================
START - test_dma_m2m_sg
DMA memory to memory transfer started
Preparing DMA Controller
Platform does not support dma request channel, using Kconfig DMA_SG_CHANNEL_NR
dma block 0 block_size 8192, source addr 0x10027d60, dest addr 0x1001fd60
set next block pointer to 0x10029e54
dma block 1 block_size 8192, source addr 0x10027d60, dest addr 0x10021d60
set next block pointer to 0x10029e74
dma block 2 block_size 8192, source addr 0x10027d60, dest addr 0x10023d60
set next block pointer to 0x10029e94
dma block 3 block_size 8192, source addr 0x10027d60, dest addr 0x10025d60
Configuring the scatter-gather transfer on channel 0
Starting the transfer on channel 0 and waiting completion
giving xfer_sem
Verify RX buffer should contain the full TX buffer string.
rx_data[0]

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/dma/scatter_gather/src/test_dma_sg.c:159: dma_m2m_sg_test_dma_m2m_sg: (test_sg() == TC_PASS) is false

 FAIL - test_dma_m2m_sg in 0.001 seconds
===================================================================
TESTSUITE dma_m2m_sg failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -   0.00% [dma_m2m_sg]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.001 seconds
 - FAIL - [dma_m2m_sg.test_dma_m2m_sg] duration = 0.001 seconds

------ TESTSUITE SUMMARY END ------
```

### Impact

Not sure

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexapostolu**
Configure data buffer alignment based on devicetree `dma_buf_addr_alignment` property.

Fixes #98949

### CODE REVIEW

File: tests/drivers/dma/chan_link_transfer/src/test_dma.c [hunk 1]
```diff
@@ -126,6 +127,7 @@ static int test_task(int minor, int major)
 		return TC_FAIL;
 	}
 	k_sleep(K_MSEC(2000));
+
```
Comment (cfriedt) [inline tests/drivers/dma/chan_link_transfer/src/test_dma.c]: Should drop the formatting change - but only worry about it if there are additional changes required.

**Review by cfriedt — DISMISSED** [review]
Just a nit (non-blocking) - otherwise LGTM.

File: tests/drivers/dma/chan_blen_transfer/Kconfig [hunk 2]
```diff
@@ -25,3 +25,7 @@ config DMA_LOOP_TRANSFER_NUMBER_OF_DMAS
 config DMA_TRANSFER_BURST16
 	bool "Enable loop transfers of 16-beat bursts"
 	default y
+
+config DMA_BLEN_ALIGNMENT
+	int "TX and RX data alignment in bytes"
+	default 32
```
Comment (JarmouniA) [inline tests/drivers/dma/chan_blen_transfer/Kconfig]:
```suggestion
	default 32
	default DCACHE_LINE_SIZE if DCACHE && (DCACHE_LINE_SIZE>0)
```
ditto for other instances.

File: tests/drivers/dma/chan_blen_transfer/src/test_buffers.c [hunk 3]
```diff
@@ -8,5 +8,6 @@
 
 #include "test_buffers.h"
 
-__aligned(32) char tx_data[TEST_BUF_SIZE] = "It is harder to be kind than to be wise........";
-__aligned(32) char rx_data[TEST_BUF_SIZE] = { 0 };
+__aligned(CONFIG_DMA_BLEN_ALIGNMENT) char tx_data[TEST_BUF_SIZE] =
```
Comment (JarmouniA) [inline tests/drivers/dma/chan_blen_transfer/src/test_buffers.c]:
```suggestion
static __aligned(CONFIG_DMA_BLEN_ALIGNMENT) char tx_data[TEST_BUF_SIZE] =
```

File: tests/drivers/dma/chan_blen_transfer/src/test_buffers.c [hunk 4]
```diff
@@ -8,5 +8,6 @@
...
+	"It is harder to be kind than to be wise........";
+__aligned(CONFIG_DMA_BLEN_ALIGNMENT) char rx_data[TEST_BUF_SIZE] = {0};
```
Comment (JarmouniA) [inline tests/drivers/dma/chan_blen_transfer/src/test_buffers.c]:
```suggestion
static __aligned(CONFIG_DMA_BLEN_ALIGNMENT) char rx_data[TEST_BUF_SIZE] = {0};
```

File: tests/drivers/dma/chan_blen_transfer/src/test_buffers.c (hunk 3 above)
Comment (teburd) [reply tests/drivers/dma/chan_blen_transfer/src/test_buffers.c]: We have DT attributes for these sorts of buffer alignments/sizing requirements already I believe

https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/dma/dma-controller.yaml#L31

**Review by teburd — CHANGES_REQUESTED** [review]
I think its fine to actually make this configurable... but changing this here needs more time to cook than the next release. It's broken many end users in the past mucking around with things here. @hakehuang and NXP in particular. I want more time for this to cook than the next release. This isn't fixing any application facing bugs, its fixing a test case issue.

File: tests/drivers/dma/chan_blen_transfer/src/test_buffers.c (hunk 3 above)
Comment (JarmouniA) [reply tests/drivers/dma/chan_blen_transfer/src/test_buffers.c]: Who should have the priority, DCache line size of DMA-required alignment? (or just take the bigger one I guess)

**Comment by alexapostolu** [comment]
Thanks for the feedback, I can make the alignment use the DT attribute instead of a KConfig, and have it ready for 4.4.0

**Comment by alexapostolu** [comment]
@teburd @JarmouniA This is ready for another review, thanks

**Review by hakehuang — COMMENTED** [review]
for chan_link_transfer case, need add mimxrt595_evk_mimxrt595s_cm33.overlay with the tst_dma dts node support.

File: tests/drivers/dma/chan_link_transfer/boards/mimxrt595_evk_mimxrt595s_cm33.overlay [hunk 5]
```diff
@@ -0,0 +1,7 @@
+/*
+ * Copyright (c) 2025 Tenstorrent AI ULC
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+tst_dma0: &edma0 {};
```
Comment (hakehuang) [inline tests/drivers/dma/chan_link_transfer/boards/mimxrt595_evk_mimxrt595s_cm33.overlay]:
```suggestion
tst_dma0: &dma0 {};
```

**Review by hakehuang — COMMENTED** [review]
mimxrt595 does not use `edma0` but `dma0`

File: tests/drivers/dma/scatter_gather/src/test_dma_sg.c [hunk 6]
```diff
@@ -66,7 +66,7 @@ static int test_sg(void)
 
 	memset(rx_data, 0, sizeof(rx_data));
 
-	dma = DEVICE_DT_GET(DT_ALIAS(dma0));
+	dma = DEVICE_DT_GET(DT_NODELABEL(tst_dma0));
```
Comment (JarmouniA) [inline tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: Please do not change this, some boards may be relying on aliases defined in the board's DTS to run tests.

File: tests/drivers/dma/scatter_gather/testcase.yaml [hunk 7]
```diff
@@ -21,7 +21,7 @@ tests:
       - adp_xc7k/ae350
       - adp_xc7k/ae350/clic
       - bg29_rb4420a
-    filter: dt_alias_exists("dma0")
+    filter: dt_nodelabel_enabled("tst_dma0")
```
Comment (JarmouniA) [inline tests/drivers/dma/scatter_gather/testcase.yaml:24]: ditto

File: tests/drivers/dma/cyclic/src/test_dma_cyclic.c [hunk 8]
```diff
@@ -48,7 +48,7 @@ static int test_cyclic(void)
 		tx_data[i] = i;
 	}
 
-	dma = DEVICE_DT_GET(DT_ALIAS(dma0));
+	dma = DEVICE_DT_GET(DT_NODELABEL(tst_dma0));
```
Comment (JarmouniA) [inline tests/drivers/dma/cyclic/src/test_dma_cyclic.c:53]: ditto

**Review by JarmouniA — DISMISSED** [review]

File: tests/drivers/dma/scatter_gather/src/test_dma_sg.c (hunk 6 above)
Comment (alexapostolu) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: Got it, I'll revert it. Although is there a reason the `scatter_gather` and `cyclic` uses an alias but the other test suites use the node label? I just thought it might be better if it was consistent

Comment (alexapostolu) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: Or alternatively, if I keep this change and add a note about this on the 4.4 migration guide, will that be acceptable?

Comment (JarmouniA) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: > Although is there a reason the scatter_gather and cyclic uses an alias but the other test suites use the node label?

No specific reason really.

Comment (JarmouniA) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: > Or alternatively, if I keep this change and add a note about this on the 4.4 migration guide, will that be acceptable?

To keep this change, you will also have to look in DTS of all in-tree boards and define the new node label for the ones defining the previously used aliases.

Comment (alexapostolu) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: Just to clarify, that means finding all boards that contain alias `dma0 = &<...>`, and adding an overlay file for them in each DMA test directory?

If so, I can make that change, grep only shows 3 `dma0` aliases that aren't already in the tests directory

Comment (JarmouniA) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: > Just to clarify, that means finding all boards that contain alias dma0 = &<...>,

Yes,

> and adding an overlay file for them in each DMA test directory?

You can just add the node label in the DTS.

Comment (alexapostolu) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: Okay I can do that. But isn't it better to have the `tst_dma0: &dma0 {}` label in a overlay inside the `tests/` directory rather than in the DTS?

Comment (JarmouniA) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: You will be adding a file for just 1 node label...

Comment (cfriedt) [reply tests/drivers/dma/scatter_gather/src/test_dma_sg.c:70]: That's generally OK and pretty common for testsuites. I don't see it as being problematic.

File: tests/drivers/dma/scatter_gather/testcase.yaml (hunk 7 above)
Comment (cfriedt) [reply tests/drivers/dma/scatter_gather/testcase.yaml:24]: That's generally OK and pretty common for testsuites. I don't see it as being problematic.

File: tests/drivers/dma/cyclic/src/test_dma_cyclic.c (hunk 8 above)
Comment (cfriedt) [reply tests/drivers/dma/cyclic/src/test_dma_cyclic.c:53]: That's generally OK and pretty common for testsuites. I don't see it as being problematic.

**Review by hakehuang — DISMISSED** [review]
all NXP test is clean

**Comment by alexapostolu** [comment]
Rebased to fix merge conflits

**Review by hakehuang — APPROVED** [review]

**Review by teburd — APPROVED** [review]
Good changes, thanks!
