### PR TITLE
net_if: Remove expired router from list of active routers

### LINKED ISSUE #21339: Expired IPv6 router causes an infinite loop
An expired IPv6 router causes an infinite loop where iface_router_run_timer() repeatedly scheduled a work item with negative delay.

Environment: Zephyr v2.0.0 on native_posix, SDK 0.10.3. This bug also manifests itself on newer versions (current master 3765e46a40) and on ARM Cortex-M hardware.

Steps to reproduce on v2.0.0:
- Use samples/net/eth_native_posix
- Remove CONFIG_NET_CONFIG_* from prj.conf to get SLAAC
- Run net-setup.sh from net-tools
- Start radvd with a config like this:

>     interface zeth
>     {
>         AdvSendAdvert on;
>         MinRtrAdvInterval 3;
>         MaxRtrAdvInterval 4;
>         AdvDefaultLifetime 7;
>     
>         prefix 2001:db8::/64
>         {
>             AdvValidLifetime infinity;
>             AdvPreferredLifetime infinity;
>         };
>     };

- Start eth_native_posix sample and wait until it gets a prefix
- Stop radvd from working with ctrl-z (not ctrl-c)
- Wait for the router to time out (7 seconds)
- Observe iface_router_expired and iface_router_run_timer getting called repeatedly (you might have added a printk there)
    
On master this problem still exists, but the infinite loop doesn't happen until the router re-appears. I'm not exactly sure why.

### PR DESCRIPTION
**Pull request by ghost**
An expired IPv6 router would cause an infinite loop where
iface_router_run_timer() repeatedly scheduled a work item. In some
conditions it would schedule with negative delay, in other conditions
the infinite loop wouldn't happen until a router was added again.

Get rid of the router from active_router_timers when it is removed.

Fixes #21339

### CODE REVIEW

File: subsys/net/ip/net_if.c [hunk 1]
```diff
@@ -591,7 +591,7 @@ static void iface_router_expired(struct k_work *work)
 		}
 
 		iface_router_notify_deletion(router, "has expired");
-
+		sys_slist_find_and_remove(&active_router_timers, &router->node);
```
Comment (tbursztyka) [inline subsys/net/ip/net_if.c]: since it is already looping on active_router_timers, you should be able to call sys_slist_remove() with the relevant changes if needed (previous node pointer needed ?)

**Review by tbursztyka — CHANGES_REQUESTED** [review]
good catch

File: subsys/net/ip/net_if.c (hunk 1 above)
Comment (jonasn-ge) [reply subsys/net/ip/net_if.c]: Good point, I'll rewrite it with sys_slist_remove()

**Review by tbursztyka — APPROVED** [review]

**Review by jukkar — CHANGES_REQUESTED** [review]
Looks good, minor nit-pick to the commit subject, please write it like this "net: iface: Remove expired router from list of active routers"

**Review by jukkar — APPROVED** [review]
