### PR TITLE
x86: memory management adjustments

### LINKED ISSUE #17782: network tests failing with 'unexpected eof' with code coverage enabled in qemu_x86 (TSS)
``` 
$ ./scripts/sanitycheck --coverage -p qemu_x86 -T tests/net/
JOBS: 4
Cleaning output directory /home/camelot/zephyrproject/zephyr/sanity-out
Building testcase defconfigs...
Filtering test cases...
51 tests selected, 21150 tests discarded due to filters
total complete:    9/  51  17%  failed:    0

qemu_x86                  tests/net/iface/net.iface.no_userspace_allowed     FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/iface/net.iface.no_userspace_allowed/handler.log

total complete:   10/  51  19%  failed:    1

qemu_x86                  tests/net/iface/net.iface.with_userspace           FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/iface/net.iface.with_userspace/handler.log

total complete:   19/  51  37%  failed:    2

qemu_x86                  tests/net/lib/mqtt_packet/net.mqtt.packet          FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/lib/mqtt_packet/net.mqtt.packet/handler.log

total complete:   34/  51  66%  failed:    3

qemu_x86                  tests/net/socket/getaddrinfo/net.socket            FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/getaddrinfo/net.socket/handler.log

total complete:   35/  51  68%  failed:    4

qemu_x86                  tests/net/socket/getnameinfo/net.socket            FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/getnameinfo/net.socket/handler.log

total complete:   36/  51  70%  failed:    5

qemu_x86                  tests/net/socket/misc/net.socket                   FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/misc/net.socket/handler.log

total complete:   37/  51  72%  failed:    6

qemu_x86                  tests/net/socket/net_mgmt/net.socket.mgmt          FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/net_mgmt/net.socket.mgmt/handler.log

total complete:   38/  51  74%  failed:    7

qemu_x86                  tests/net/ptp/clock/net.ptp.clock                  FAILED: timeout
	see: sanity-out/qemu_x86/tests/net/ptp/clock/net.ptp.clock/handler.log

total complete:   39/  51  76%  failed:    8

qemu_x86                  tests/net/socket/register/net.socket.register.tls  FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/register/net.socket.register.tls/handler.log

total complete:   40/  51  78%  failed:    9

qemu_x86                  tests/net/socket/select/net.socket                 FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/select/net.socket/handler.log

total complete:   41/  51  80%  failed:   10

qemu_x86                  tests/net/socket/tcp/net.socket.tcp                FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/tcp/net.socket.tcp/handler.log

total complete:   42/  51  82%  failed:   11

qemu_x86                  tests/net/socket/udp/net.socket.udp                FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/udp/net.socket.udp/handler.log

total complete:   47/  51  92%  failed:   12

qemu_x86                  tests/net/utils/net.util                           FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/utils/net.util/handler.log

total complete:   51/  51  100%  failed:   13

```
Enabling CONFIG_COVERAGE exposes test failures with networking tests under tests/net/. We need these be able to build and run successfully to assess code coverage of the network stack.

Upon further inspection, 5 of these are failing on line 395 in arch/x86/core/ia32/crt0.S
- tests/net/iface 
- tests/net/socket/tcp
- tests/net/utils
- tests/net/socket/udp
- tests/net/socket/net_mgmt

Reproduce with:

``` sanitycheck --coverage -p qemu_x86 -T tests/net/ ```

### LINKED ISSUE #17783: network tests failing with code coverage enabled in qemu_x86 (coverage.c)
``` 
$ ./scripts/sanitycheck --coverage -p qemu_x86 -T tests/net/
JOBS: 4
Cleaning output directory /home/camelot/zephyrproject/zephyr/sanity-out
Building testcase defconfigs...
Filtering test cases...
51 tests selected, 21150 tests discarded due to filters
total complete:    9/  51  17%  failed:    0

qemu_x86                  tests/net/iface/net.iface.no_userspace_allowed     FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/iface/net.iface.no_userspace_allowed/handler.log

total complete:   10/  51  19%  failed:    1

qemu_x86                  tests/net/iface/net.iface.with_userspace           FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/iface/net.iface.with_userspace/handler.log

total complete:   19/  51  37%  failed:    2

qemu_x86                  tests/net/lib/mqtt_packet/net.mqtt.packet          FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/lib/mqtt_packet/net.mqtt.packet/handler.log

total complete:   34/  51  66%  failed:    3

qemu_x86                  tests/net/socket/getaddrinfo/net.socket            FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/getaddrinfo/net.socket/handler.log

total complete:   35/  51  68%  failed:    4

qemu_x86                  tests/net/socket/getnameinfo/net.socket            FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/getnameinfo/net.socket/handler.log

total complete:   36/  51  70%  failed:    5

qemu_x86                  tests/net/socket/misc/net.socket                   FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/misc/net.socket/handler.log

total complete:   37/  51  72%  failed:    6

qemu_x86                  tests/net/socket/net_mgmt/net.socket.mgmt          FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/net_mgmt/net.socket.mgmt/handler.log

total complete:   38/  51  74%  failed:    7

qemu_x86                  tests/net/ptp/clock/net.ptp.clock                  FAILED: timeout
	see: sanity-out/qemu_x86/tests/net/ptp/clock/net.ptp.clock/handler.log

total complete:   39/  51  76%  failed:    8

qemu_x86                  tests/net/socket/register/net.socket.register.tls  FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/register/net.socket.register.tls/handler.log

total complete:   40/  51  78%  failed:    9

qemu_x86                  tests/net/socket/select/net.socket                 FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/select/net.socket/handler.log

total complete:   41/  51  80%  failed:   10

qemu_x86                  tests/net/socket/tcp/net.socket.tcp                FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/tcp/net.socket.tcp/handler.log

total complete:   42/  51  82%  failed:   11

qemu_x86                  tests/net/socket/udp/net.socket.udp                FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/udp/net.socket.udp/handler.log

total complete:   47/  51  92%  failed:   12

qemu_x86                  tests/net/utils/net.util                           FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/utils/net.util/handler.log

total complete:   51/  51  100%  failed:   13

```

Enabling CONFIG_COVERAGE exposes test failures with networking tests under tests/net/. We need these be able to build and run successfully to assess code coverage of the network stack.

Upon further inspection, 5 of these are failing on line 271 in subsys/testsuite/coverage/coverage.c
- tests/net/socket/getnameinfo
- tests/net/socket/getaddrinfo
- tests/net/socket/misc
- tests/net/socket/select
- tests/net/ptp/clock

Reproduce with: 
``` sanitycheck --coverage -p qemu_x86 -T tests/net/ ```

### LINKED ISSUE #17784: failing network tests with code coverage enabled in qemu_x86 not failing when run with gdb
```
$ ./scripts/sanitycheck --coverage -p qemu_x86 -T tests/net/
JOBS: 4
Cleaning output directory /home/camelot/zephyrproject/zephyr/sanity-out
Building testcase defconfigs...
Filtering test cases...
51 tests selected, 21150 tests discarded due to filters
total complete:    9/  51  17%  failed:    0

qemu_x86                  tests/net/iface/net.iface.no_userspace_allowed     FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/iface/net.iface.no_userspace_allowed/handler.log

total complete:   10/  51  19%  failed:    1

qemu_x86                  tests/net/iface/net.iface.with_userspace           FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/iface/net.iface.with_userspace/handler.log

total complete:   19/  51  37%  failed:    2

qemu_x86                  tests/net/lib/mqtt_packet/net.mqtt.packet          FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/lib/mqtt_packet/net.mqtt.packet/handler.log

total complete:   34/  51  66%  failed:    3

qemu_x86                  tests/net/socket/getaddrinfo/net.socket            FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/getaddrinfo/net.socket/handler.log

total complete:   35/  51  68%  failed:    4

qemu_x86                  tests/net/socket/getnameinfo/net.socket            FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/getnameinfo/net.socket/handler.log

total complete:   36/  51  70%  failed:    5

qemu_x86                  tests/net/socket/misc/net.socket                   FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/misc/net.socket/handler.log

total complete:   37/  51  72%  failed:    6

qemu_x86                  tests/net/socket/net_mgmt/net.socket.mgmt          FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/net_mgmt/net.socket.mgmt/handler.log

total complete:   38/  51  74%  failed:    7

qemu_x86                  tests/net/ptp/clock/net.ptp.clock                  FAILED: timeout
	see: sanity-out/qemu_x86/tests/net/ptp/clock/net.ptp.clock/handler.log

total complete:   39/  51  76%  failed:    8

qemu_x86                  tests/net/socket/register/net.socket.register.tls  FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/register/net.socket.register.tls/handler.log

total complete:   40/  51  78%  failed:    9

qemu_x86                  tests/net/socket/select/net.socket                 FAILED: handler_crash
	see: sanity-out/qemu_x86/tests/net/socket/select/net.socket/handler.log

total complete:   41/  51  80%  failed:   10

qemu_x86                  tests/net/socket/tcp/net.socket.tcp                FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/tcp/net.socket.tcp/handler.log

total complete:   42/  51  82%  failed:   11

qemu_x86                  tests/net/socket/udp/net.socket.udp                FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/socket/udp/net.socket.udp/handler.log

total complete:   47/  51  92%  failed:   12

qemu_x86                  tests/net/utils/net.util                           FAILED: unexpected eof
	see: sanity-out/qemu_x86/tests/net/utils/net.util/handler.log

total complete:   51/  51  100%  failed:   13

```
Enabling CONFIG_COVERAGE exposes test failures with networking tests under tests/net/. We need these be able to build and run successfully to assess code coverage of the network stack.

Upon further inspection, 2 of these don't seem to fail when run with gdb, but continue to fail when running sanitycheck.
- tests/net/socket/register
- tests/net/lib/mqtt_packet

Reproduce with:
``` sanitycheck --coverage -p qemu_x86 -T tests/net/ ```

### PR DESCRIPTION
**Pull request by tyrantlizard77**
- The memory map for ia32 SOC was using the first megabyte. This has reserved memory regions in it, relocate the start of memory for ia32 to 1MB.
- Generate page tables at runtime. Delete old buggy MMU table generation script
- qemu_x86 config adjustments
- Enable very early console for qemu_x86_coverage
- X86 now handles all its arch-specific initialization tasks before z_cstart() is called.

Please see individual commit messages for details.

Fixes: #17783
Fixes: #17782 
Fixes: #17784

### CODE REVIEW

**Comment by andrewboie** [comment]
@andyross @gnuless initially I tried lifting above just the first megabyte, but still ran into issues. Moving above 2MB seems to have resolved it. I wasn't expecting any reserved memory regions between 1MB-2MB, maybe some quirk of QEMU?

**Review by ghost — APPROVED** [review]

**Comment by andrewboie** [comment]
NVS fs test is failing, not entirely sure how to fix

```
c[?7l[2J[0mSeaBIOS (version rel-1.12.0-0-ga698c8995f-prebuilt.qemu.org)
Booting from ROM..***** Booting Zephyr OS build zephyr-v1.14.0-2843-g72fb988a685e *****
Running test suite test_nvs
===================================================================
starting test - test_nvs_init

    Assertion failed at ZEPHYR_BASE/tests/subsys/fs/nvs/src/main.c:72: test_nvs_init: (err == 0 is false)
Unable to get page info: -22
FAIL - test_nvs_init
===================================================================
starting test - test_nvs_write

    Assertion failed at ZEPHYR_BASE/tests/subsys/fs/nvs/src/main.c:111: test_nvs_write: (err == 0 is false)
nvs_init call failure: -22
FAIL - test_nvs_write
===================================================================
starting test - test_nvs_corrupted_write

    Assertion failed at ZEPHYR_BASE/tests/subsys/fs/nvs/src/main.c:151: test_nvs_corrupted_write: (err == 0 is false)
nvs_init call failure: -22
FAIL - test_nvs_corrupted_write
===================================================================
starting test - test_nvs_gc

    Assertion failed at ZEPHYR_BASE/tests/subsys/fs/nvs/src/main.c:221: test_nvs_gc: (err == 0 is false)
nvs_init call failure: -22
FAIL - test_nvs_gc
===================================================================
starting test - test_nvs_gc_3sectors

    Assertion failed at ZEPHYR_BASE/tests/subsys/fs/nvs/src/main.c:46: setup: (err == 0 is false)
nvs_clear call failure: -13
FAIL - test_nvs_gc_3sectors
===================================================================
starting test - test_nvs_corrupted_sector_close_operation

    Assertion failed at ZEPHYR_BASE/tests/subsys/fs/nvs/src/main.c:46: setup: (err == 0 is false)
nvs_clear call failure: -13
FAIL - test_nvs_corrupted_sector_close_operation
===================================================================
Test suite test_nvs failed.
===================================================================
PROJECT EXECUTION FAILED
[00:00:00.000,000] [1;31m<err> fs_nvs: Unable to get page info[0m
[00:00:00.000,000] [1;31m<err> fs_nvs: Unable to get page info[0m
[00:00:00.000,000] [1;31m<err> fs_nvs: Unable to get page info[0m
[00:00:00.000,000] [1;31m<err> fs_nvs: NVS not initialized[0m
[00:00:00.000,000] [1;31m<err> fs_nvs: NVS not initialized[0m
```

**Comment by andrewboie** [comment]
The first megabyte should be enough. I wrote a test program to probe writes in the first 2MB and found these address ranges would not have any effect if writes were done to them:

0x000a0000 -> 0x000b8000
0x000c0000 -> 0x000ca000
0x000cd000 -> 0x000e8000
0x000f0000 -> 0x00100000

0x00100000 and above should be fine.

**Review by dcpleung — APPROVED** [review]

**Comment by andrewboie** [comment]
I combined this with my other patch which generates page tables at runtime, as lifting to 1MB exposed bugs in the old page table generation script, and I'd rather just remove it.

**Review by dcpleung — APPROVED** [review]

**Review by wentongwu — APPROVED** [review]

File: arch/x86/core/ia32/x86_mmu.c [hunk 1]
```diff
@@ -344,6 +364,173 @@ void z_x86_mmu_set_flags(struct x86_mmu_pdpt *pdpt, void *ptr, size_t size,
...
+		 "unaligned address provided");
+	__ASSERT((rgn->size & MMU_PAGE_MASK) == 0U,
+		 "unaligned size provided");
+
+	addr = rgn->address;
+
+#ifdef CONFIG_X86_KPTI
+	/* MMU_ENTRY_RUNTIME_USER is a special flag; it indicates that the
+	 * region isn't acessible to user mode at boot, but may be granted
+	 * access later. The implications are that the PDPT/PD entries will
```
Comment (andrewboie) [inline arch/x86/core/ia32/x86_mmu.c]: incorrect, it just ensures that the page directory/tables are created

**Comment by nvlsianpu** [comment]
> NVS fs test is failing, not entirely sure how to fix, @nvlsianpu any tips?

Is this still failing?

**Comment by andrewboie** [comment]
> 
> 
> > NVS fs test is failing, not entirely sure how to fix, @nvlsianpu any tips?
> 
> Is this still failing?

No, I figured it out.

**Review by keylime-unicorn — APPROVED** [review]

File: arch/x86/core/ia32/x86_mmu.c [hunk 2]
```diff
@@ -344,6 +360,169 @@ void z_x86_mmu_set_flags(struct x86_mmu_pdpt *pdpt, void *ptr, size_t size,
...
+#ifdef CONFIG_X86_KPTI
+__aligned(0x20) struct x86_mmu_pdpt z_x86_user_pdpt;
+#endif
+
+extern char z_shared_kernel_page_start[];
+
+static inline bool is_within_system_ram(uintptr_t addr)
+{
+	return (addr >= DT_PHYS_RAM_ADDR) &&
+		(addr < (DT_PHYS_RAM_ADDR + (DT_RAM_SIZE * 1024U)));
```
Comment (andyross) [inline arch/x86/core/ia32/x86_mmu.c]: Should probably do this in 64 bit math.  Physical RAM on PAE systems can routinely blow past 4G and result in an overflow here (and thus incorrect behavior) for "correct" devicetree settings.  We don't have to support using it, but we shouldn't break if devicetree authors (or EFI/e820/multiboot loaders, etc...) don't understand our limitations.

File: arch/x86/core/ia32/x86_mmu.c [hunk 3]
```diff
@@ -344,6 +360,169 @@ void z_x86_mmu_set_flags(struct x86_mmu_pdpt *pdpt, void *ptr, size_t size,
...
+	union x86_mmu_pde_pt *pde;
+	struct x86_mmu_pt *pt;
+	union x86_mmu_pte *pte;
+
+#ifdef CONFIG_X86_KPTI
+	/* If we are generating a page table for user mode, and this address
+	 * does not have the user flag set, and this address falls outside
+	 * of system RAM, then don't bother generating any tables for it,
+	 * we will never need them later as memory domains are limited to
+	 * regions within system RAM.
```
Comment (andyross) [inline arch/x86/core/ia32/x86_mmu.c]: Described like that, this sounds like it should be an __ASSERT() and not a silent ignore condition.  What's the circumstance where this can legitimately happen in practice?

File: arch/x86/core/ia32/x86_mmu.c [hunk 4]
```diff
@@ -344,6 +360,169 @@ void z_x86_mmu_set_flags(struct x86_mmu_pdpt *pdpt, void *ptr, size_t size,
...
+	/* Execute disable bit needs special handling, we should only set it
+	 * at the page directory level if ALL pages have XD set (instead of
+	 * just one).
+	 *
+	 * Use the 'ignored2' field to store a marker on whether any
+	 * configured region allows execution, the CPU never looks at
+	 * or modifies it.
+	 */
+	if ((flags & MMU_ENTRY_EXECUTE_DISABLE) == 0) {
+		pde->ignored2 = 1;
```
Comment (andyross) [inline arch/x86/core/ia32/x86_mmu.c]: Style: given the subtlety, wouldn't be a bad idea to wrap the usage of ignored2 into an API like "set/get_page_partial_nx()" or something.

File: dts/x86/ia32.dtsi [hunk 5]
```diff
@@ -28,18 +28,17 @@
 	};
 
 
-	flash0: flash@1000 {
+	flash0: flash@100000 {
```
Comment (andyross) [inline dts/x86/ia32.dtsi]: This all seems fine, low memory is a booby trap, in particular the 640k-1M region which has the MMIO mappings for legacy devices.  Note that real hardware does have (and require) this memory though, so it's likely we'll have to come back here at some point and put in some kind of mapping/allocation layer to allow us to get to it.  But loading the binary at 1M is IMHO absolutely the right choice.

File: arch/x86/core/ia32/crt0.S [hunk 6]
```diff
@@ -308,10 +308,8 @@ __csSet:
 	outb %al, $0xA1		/* set i8259 slave mask (IRQs 8-15) */
 #endif
 
-	/* Jump to C portion of kernel initialization and never return */
-
-	jmp	z_cstart
-
+	/* call C portion of kernel initialization and never return */
+	call	z_x86_prep_c
```
Comment (andyross) [inline arch/x86/core/ia32/crt0.S]: Love it.

**Review by andyross — COMMENTED** [review]
Some notes.  The overflow case on physical RAM size is the only thing I think is really needed.

File: arch/x86/core/ia32/x86_mmu.c (hunk 3 above)
Comment (andrewboie) [reply arch/x86/core/ia32/x86_mmu.c]: MMIO memory ranges. They don't need tables in the user page tables, only the kernel ones.

File: arch/x86/core/ia32/x86_mmu.c (hunk 2 above)
Comment (andrewboie) [reply arch/x86/core/ia32/x86_mmu.c]: There is no support in Zephyr for PAE itself (and there never will be), we only use PAE tables for the NX bit and nothing else.

All kinds of things will break if we are working with memory addresses that don't fit in a uintptr_t, not just here.

I'm gonna add a BUILD_ASSERT() that RAM is <= 4GB.

File: arch/x86/core/ia32/crt0.S (hunk 6 above)
Comment (andrewboie) [reply arch/x86/core/ia32/crt0.S]: Eventually, we should nuke z_kernel_arch_init() for all arches

File: arch/x86/core/ia32/x86_mmu.c (hunk 2 above)
Comment (andrewboie) [reply arch/x86/core/ia32/x86_mmu.c]: > "correct" devicetree settings.

We don't need to do this.
DTS enforces already that these values fit, if I try to kick up QEMU's RAM size to be above 4GB I get a build error:

> Error: qemu_x86.dts.pre.tmp:31.21-43 Value out of range for 32-bit array element

I don't think we need to do anything here. We are never going to support PAE in the 32-bit port, we only use PAE tables for the NX bit.
