### PR TITLE
stm32f4 i2c bug fixes for I2C hangs due to EMC problems (ported from 1.14 #23663)

### LINKED ISSUE #22751: STM32F407 I2C driver hangs
The STM32F407 I2C driver hangs from time to time where it waits on the semaphore in the driver.  When that happens the signal on the bus looks like this (SDA = yellow, SCL = green);

i2c_error

To work around it I added a timeout to the k_sem_take calls, but I have not found the real cause of the problem. On the scope is to see it must go wrong real early, because it generates a start-stop without any data. 

This is on the 1.14 branch, but I cherry-picked most commits (like the new timeout handling) from master. The target is a STM32F407 so it uses the V1 driver. Also not using IRQ's but polling causes the problem to happen less but it still happens.

### PR DESCRIPTION
**Pull request by lowlander**
This is a port of the I2C 1.14 patch (#23663) for master that fixes #22751. It adds timeouts to the read write functions, and resets the I2C device if a timeout happens. It is needed on my hardware (high EMC environment) to prevent hangs of the I2C bus due to EMC spikes.  

In user space we have extra code that checks the SDA/SCL pins on error and generates extra clock signals to make sure possible hung slave devices get back in a know state. This is hard to port to the driver because it doesn't really have access to the GPIO's, or does someone have an idea how to do that?

Also I have a "random" 500ms timeout, it would be nice if the Zephyr system calls would have a timeout parameter, so the application can decide what an acceptable timeout is for the transfer.

### CODE REVIEW

**Comment by jonasn-ge** [comment]
I have tested this PR on a STM32F429 system that has problems with I2C locking up, cherry-picked to v2.2.0. It makes the spontaneous I2C lockups go away, and also recovers the bus from hanging after I tie SDA to ground for a while. Nice work, @lowlander!

You may want to set a better PR title.

**Comment by lowlander** [comment]
@jonasn-ge I updated the title, but since it was mentioned in the 1.14 PR and in the incident the maintainers probably would have found it.

**Comment by lowlander** [comment]
@MaureenHelm @erwango  @carlescufi @ABOSTM could you give this PR a look (pinging you since you all looked/commented on the 1.14 version of this PR) ?

File: drivers/i2c/i2c_ll_stm32_v1.c [hunk 1]
```diff
@@ -28,6 +28,18 @@ LOG_MODULE_REGISTER(i2c_ll_stm32_v1);
 #define I2C_REQUEST_READ        0x01
 #define HEADER                  0xF0
 
+static void ll_i2c_generate_start_condition(I2C_TypeDef *i2c)
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32_v1.c:33]: Let it be `stm32_i2c_generate_start_condition` and reserve `ll` namespace for pure LL API abstraction when needed.

File: drivers/i2c/i2c_ll_stm32_v1.c [hunk 2]
```diff
@@ -64,8 +66,51 @@ static void stm32_i2c_enable_transfer_interrupts(struct device *dev)
 	LL_I2C_EnableIT_BUF(i2c);
 }
 
+static void ll_i2c_reset(struct device *dev)
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32_v1.c:69]: Same comment here, let's use `stm32` namespace here.

File: drivers/i2c/i2c_ll_stm32_v1.c [hunk 3]
```diff
@@ -64,8 +66,51 @@ static void stm32_i2c_enable_transfer_interrupts(struct device *dev)
...
+{
+	const struct i2c_stm32_config *cfg = DEV_CFG(dev);
+	I2C_TypeDef *i2c = cfg->i2c;
+	uint16_t cr1, cr2, oar1, oar2, trise, ccr;
+#if  defined(I2C_FLTR_ANOFF) && defined(I2C_FLTR_DNF)
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32_v1.c:74]: Nit
```suggestion
#if defined(I2C_FLTR_ANOFF) && defined(I2C_FLTR_DNF)
```

File: drivers/i2c/i2c_ll_stm32_v1.c [hunk 4]
```diff
@@ -64,8 +66,51 @@ static void stm32_i2c_enable_transfer_interrupts(struct device *dev)
...
+	stm32_i2c_disable_transfer_interrupts(dev);
+
+	/* save all important registers before reset */
+	cr1 = LL_I2C_ReadReg(i2c, CR1);
+	cr2 = LL_I2C_ReadReg(i2c, CR2);
+	oar1 = LL_I2C_ReadReg(i2c, OAR1);
+	oar2 = LL_I2C_ReadReg(i2c, OAR2);
+	ccr = LL_I2C_ReadReg(i2c, CCR);
+	trise = LL_I2C_ReadReg(i2c, TRISE);
+#if  defined(I2C_FLTR_ANOFF) && defined(I2C_FLTR_DNF)
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32_v1.c:89]: Ditto
```suggestion
#if defined(I2C_FLTR_ANOFF) && defined(I2C_FLTR_DNF)
```

File: drivers/i2c/i2c_ll_stm32_v1.c [hunk 5]
```diff
@@ -64,8 +66,51 @@ static void stm32_i2c_enable_transfer_interrupts(struct device *dev)
...
+	LL_I2C_WriteReg(i2c, CR1, cr1);
+	LL_I2C_WriteReg(i2c, CR2, cr2);
+
+	/* bit 14 of OAR1 must always be 1 */
+	oar1 |= (1 << 14);
+	LL_I2C_WriteReg(i2c, OAR1, oar1);
+	LL_I2C_WriteReg(i2c, OAR2, oar2);
+	LL_I2C_WriteReg(i2c, CCR, ccr);
+	LL_I2C_WriteReg(i2c, TRISE, trise);
+#if  defined(I2C_FLTR_ANOFF) && defined(I2C_FLTR_DNF)
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32_v1.c:107]: ditto
```suggestion
#if defined(I2C_FLTR_ANOFF) && defined(I2C_FLTR_DNF)
```

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for taking time to fix this in master!
A couple of minor comments

**Review by erwango — APPROVED** [review]

**Review by ydamigos — APPROVED** [review]

**Review by pabigot — APPROVED** [review]
No objections.  Elsewhere there's an issue related to adding a configurable timeout at the I2C subsystem level, via Kconfig, and at that point we'll have to unify its behavior with that of drivers that define their own (all different).  I can't say that'll be addressed before 2.4 though so let's get this in now.
