### PR TITLE
Bluetooth: host: Fix extended advertising feature bit check

### LINKED ISSUE #35596: Bluetooth: Cannot connect if extended advertising is enabled in `prj.conf`
**Describe the bug**

A Zephyr program compiled with the following in `prj.conf`:

```
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_EXT_ADV=y
CONFIG_BT_PER_ADV=y
```

Calling `bt_conn_le_create` after discovering a peer returns -5 (`-EIO`) when compiled with the above config. Removing or setting to `n` the `CONFIG_BT_EXT_ADV` option and recompiling corrects the behaviour.

CONFIG_BT_EXT_ADV | CONFIG_BT_PER_ADV | Return value of `bt_conn_le_create`
:---:|:---:|:---:
n | n | 0
n | y | 0
y | n | -5
y | y | -5

**To Reproduce**
1. Compile [the code in this gist](https://gist.github.com/chrisswinchatt-arm/e1bb45e088def70db0aed158c3b44d4f)
2. Flash to the boards; I tested with `nucleo_wb55rg`, `disco_l475_iot1` and `nrf52840_mdk`; which is central and which is peripheral doesn't matter
3. Use serial console to send A to one board to tell it to advertise and S to the other to tell it to scan
4. The error is shown on the serial console of the scanning board when it attempts to connect

**Expected behavior**
It should be possible for a single program to support both connect & periodic sync.

**Impact**
Showstopper

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.5.0-2959-g9a14f627426b  ***
Initialising...
Press A to start advertising or S to start scanning
Scanning for 10 seconds
Connecting to Issue (80:e1:26:1b:76:02)
bt_conn_le_create: error -5
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) Windows
 - Toolchain (e.g Zephyr SDK, ...): Zephyr / West
 - Commit SHA or Version used: 9a14f627426ba1e25e75d8ea3ebbdcccc4d9b2a7

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by joerchan**
Fix CONFIG_BT_EXT_ADV_LEGACY_SUPPORT option which optimizes the host
to skip checking the feature bit of the controller to check for
extended advertising commands.
This was broken because of how this was implented using an undef of the
feature bit, which was not replicated in scan.c, adv.c and id.c once
this was split out from hci_core.

Instead of doing this wierd way of redefining the feature check macro
do it in a proper way by defining a new macro.

Fixes: #35596

### CODE REVIEW

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -633,7 +628,7 @@ int bt_le_create_conn_legacy(const struct bt_conn *conn)
 int bt_le_create_conn(const struct bt_conn *conn)
 {
 	if (IS_ENABLED(CONFIG_BT_EXT_ADV) &&
-	    BT_FEAT_LE_EXT_ADV(bt_dev.le.features)) {
+		    printk("Ext create conn\n");
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:631]: Remove?

Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c:631]: My partial staging was wrong here, I removed the wrong line. Removed the printk, and added back the feature bit check.

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
