### PR TITLE
ec_host_cmd: Fix unused return value from k_sem_take call

### LINKED ISSUE #29018: [Coverity CID :214881] Unchecked return value in subsys/mgmt/ec_host_cmd/ec_host_cmd_handler.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/mgmt/ec_host_cmd/ec_host_cmd_handler.c

Category: Error handling issues
Function: `handle_host_cmds_entry`
Component: Other
CID: [214881](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=214881)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by laurenmurphyx64**
Fixes Coverity issue 214881.

Fixes #29018

Signed-off-by: Lauren Murphy <lauren.murphy@intel.com>

### CODE REVIEW

File: subsys/mgmt/ec_host_cmd/ec_host_cmd_handler.c [hunk 1]
```diff
@@ -69,7 +69,10 @@ static void handle_host_cmds_entry(void *arg1, void *arg2, void *arg3)
 		k_sem_give(rx.dev_owns);
 
 		/* Wait until and RX messages is received on host interace */
-		k_sem_take(rx.handler_owns, K_FOREVER);
+		if (k_sem_take(rx.handler_owns, K_FOREVER) < 0) {
```
Comment (jettr) [inline subsys/mgmt/ec_host_cmd/ec_host_cmd_handler.c:72]: Based on the documentation and waiting K_FOREVER, I didn't find a scenario where this could actually return anything other than 0 (it would instead always just wait forever).

I am still okay with this change though

**Review by jettr — COMMENTED** [review]
If we can't take this code path ever, but we are only fixing this because of coverity, should we add a comment saying that this path should never occur?

File: subsys/mgmt/ec_host_cmd/ec_host_cmd_handler.c (hunk 1 above)
Comment (laurenmurphyx64) [reply subsys/mgmt/ec_host_cmd/ec_host_cmd_handler.c:72]: I've updated the PR to add a comment to indicate that the path will never be taken. Let me know if the wording should be changed up!

PS: During a discussion about this issue, we were surprised to find a [bug](https://github.com/zephyrproject-rtos/zephyr/issues/29244) where k_sem_take with K_FOREVER could be coerced to return EAGAIN - the error code reserved for timing out. The bug seems to be in k_thread_resume, though, not k_sem_take, and it happens under a strange condition. So I agree with what you said - there should be no way for your call to return anything but 0.

Comment (jettr) [reply subsys/mgmt/ec_host_cmd/ec_host_cmd_handler.c:72]: Nice find, and thanks for the added comment!

**Review by jettr — APPROVED** [review]

**Review by jenmwms — APPROVED** [review]
