### PR TITLE
net: pkt: Make sure iface is not null when accessing L2

### LINKED ISSUE #20088: tests/net/icmpv6/ failed on mimxrt1050_evk board.
**Describe the bug**
It was the same error as #20007, for the test cases in tests/net/ directory, there is always an error "Unaligned memory access".

**To Reproduce**
1.  west build -b=mimxrt1050_evk -p=auto tests/net/icmpv6/
2.  west flash
3.  See error

**Screenshots or console output**
***** Booting Zephyr OS build zephyr-v2.0.0-1408-g83708567c9d9 *****

Running test suite test_icmpv6_fn
starting test - test_icmpv6
E: ***** USAGE FAULT *****
E: Unaligned memory access
E: r0/a1: 0x00000068 r1/a2: 0xf88899e5 r2/a3: 0x00000000
E: r3/a4: 0x00000000 r12/ip: 0x00000012 r14/lr: 0x60008117
E: xpsr: 0x81000000
E: Faulting instruction address (r15/pc): 0x600081c4
E: >>> ZEPHYR FATAL ERROR 0: CPU exception
E: Current thread: 0x800013d4 (unknown)
E: Halting system

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain : zephyr-sdk-0.10.3
 - Commit ID: 83708567

### PR DESCRIPTION
**Pull request by jukkar**
It is possible that the network interface is not set when we
check the interface in net_pkt.c:pkt_buffer_length(). For example
in icmpv6 unit test the interface is left as NULL as the test does
not care about what network interface is used. For real hw like
mimxrt1050_evk, which supports Ethernet, we need to add additional
checks for the interface being non-null.

Fixes #20088

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

File: subsys/net/ip/net_pkt.c [hunk 1]
```diff
@@ -966,7 +966,7 @@ static size_t pkt_buffer_length(struct net_pkt *pkt,
 		max_len = MAX(max_len, NET_IPV4_MTU);
 	} else { /* family == AF_UNSPEC */
 #if defined (CONFIG_NET_L2_ETHERNET)
-		if (net_if_l2(net_pkt_iface(pkt)) ==
+		if (net_pkt_iface(pkt) && net_if_l2(net_pkt_iface(pkt)) ==
```
Comment (tbursztyka) [inline subsys/net/ip/net_pkt.c]: why not instead doing the check always in net_if_l2()? 

That said, iface should not be null in real hw, unit tests are indeed doing tricky things something for simplification.

Comment (jukkar) [reply subsys/net/ip/net_pkt.c]: Sure, we can add that check to L2.

**Review by pfalcon — APPROVED** [review]
Maybe this should be ASSERT after all (re: discussion that happened at TSC F2F, such an assert would need to be reviewed later and hopefully be still kept config-opt driven, so if needed, code space could be saved).

**Comment by tbursztyka** [comment]
yep, maybe an NET_ASSERT() would be preferable. What's your opinion on that @jukkar ?

**Comment by jukkar** [comment]
> yep, maybe an NET_ASSERT() would be preferable. What's your opinion on that @jukkar ?

I do not think ASSERT() is good here, it would cause a crash and the test that this fix is trying to fix would still fail.

**Review by MaureenHelm — APPROVED** [review]
