### PR TITLE
Bluetooth: Host: Fix deadlock calling API functions from SMP callbacks

### LINKED ISSUE #20833: Bluetooth: Deadlock in Host API from SMP callbacks.
**Describe the bug**
Deadlock in Bluetooth Host. Deadlock could happen from the SMP
callbacks when calling Bluetooth API functions. This is because the
callbacks was given directly from the HCI TX thread. If the calling
API function resulted in trying to send a new HCI command it would post
this HCI command to the HCI TX thread and then wait for command complete
event. This would result in the HCI TX thread blocked waiting for the
itself to process the command.

Reproduce:
Call bt_conn_le_conn_param_update from pairing_complete callback.

Workaround:
Avoid calling blocking functions from SMP pairing_complete and pairing_failed callbacks
Instead post follow up work to different context using `k_work_submit` or similar.

**Expected behavior**
Bluetooth API should be able to be called from callbacks.

**Impact**
Will result in HCI command timeout in `bt_hci_send_sync`. This will lead to ASSERT if enabled.
Handling of HCI command timeout does not exist in the host.

**Environment (please complete the following information):**
commit: 6eb48088ed7e3083a57afa2a1bd57ae902886cc7

### PR DESCRIPTION
**Pull request by joerchan**
Fix deadlock in Bluetooth Host. Deadlock could happen from the SMP
callbacks when calling Bluetooth API functions. This is because the
callbacks was given directly from the HCI TX thread. If the calling
API function resulted in trying to send a new HCI command it would post
this HCI command to the HCI TX thread and then wait for command complete
event. This would result in the HCI TX thread blocked waiting for the
itself to process the command.

Example:
Calling bt_conn_le_conn_param_update from pairing_complete callback.

Fixes: #20833

### CODE REVIEW

**Comment by carlescufi** [comment]
>This is because the callbacks was given directly from the HCI TX thread

But the code actually says: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/conn.c#L1245

Which is right?

**Comment by joerchan** [comment]
> > This is because the callbacks was given directly from the HCI TX thread
> 
> But the code actually says: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/conn.c#L1245
> 
> Which is right?

`bt_conn_notify_tx` is called either through `conn_cleanup` from  `bt_conn_preprace_events`
or from `process_events`. Both of these paths are from `hci_tx_thread`. So TX thread is right, and it seems RX thread is wrong.

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -1210,17 +1210,6 @@ int bt_conn_send_cb(struct bt_conn *conn, struct net_buf *buf,
...
-#if defined(CONFIG_BT_PRIVACY)
-	    cb == smp_id_sent ||
-#endif /* CONFIG_BT_PRIVACY */
-#if defined(CONFIG_BT_SIGNING)
-	    cb == smp_sign_info_sent ||
-#endif /* CONFIG_BT_SIGNING */
-#if !defined(CONFIG_BT_SMP_SC_PAIR_ONLY)
-	    cb == smp_ident_sent ||
-#endif /* CONFIG_BT_SMP_SC_PAIR_ONLY */
-#endif /* CONFIG_BT_SMP */
```
Comment (jhedberg) [inline subsys/bluetooth/host/conn.c]: Would it be wise to add a code comment here to avoid re-introducing a similar bug? Something like "note: SMP functions are not considered internal since they may cause application callbacks". Or perhaps: "Only functions which are known to not block on anything that may depend on the TX thread itself (thereby causing a deadlock) are considered internal in this context. This means that e.g. SMP callbacks cannot be considered internal, since they may perform application callbacks (which we don't control)."

Comment (joerchan) [reply subsys/bluetooth/host/conn.c]: That's a good point. Added comment based on your suggestion.

**Comment by joerchan** [comment]
> > This is because the callbacks was given directly from the HCI TX thread
> 
> But the code actually says: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/conn.c#L1245
> 
> Which is right?
> 
> EDIT: TX thread is correct, we could probably fix the comment at the same time.

Fixed this comment to say TX thread.

**Review by jhedberg — APPROVED** [review]

**Review by Vudentz — APPROVED** [review]
LGTM
