### PR TITLE
drivers: uart: Refactor nrf uart shim

### LINKED ISSUE #7755: getchar sample not working on nRF5x
[This commit](https://github.com/zephyrproject-rtos/zephyr/commit/05c45e359a94e96353dfac1f0abeccf6893e988a#diff-fb209e20d9cf9e70b3dbd2748ae43f90) broke the `samples/subsys/console/getchar` sample.

### PR DESCRIPTION
**Pull request by jakub-uC**
Replace all register defines and calls with Nordic nrfx HAL.

Fixes #7755 

Signed-off-by: Jakub Rzeszutko <Jakub.Rzeszutko@nordicsemi.no>

### CODE REVIEW

File: arch/arm/soc/nordic_nrf/include/nrf_common.h [hunk 1]
```diff
@@ -61,30 +61,4 @@
...
 #define NRF52_IRQ_FPU_IRQn                     38
 
-/**
- * @file UART baudrate divisors for nRFx family processors.
- *
- * Based on Nordic MDK included header file: nrf52_bitfields.h
- * Uses the UARTE_BAUDRATE macros since they are more precise.
- */
-
-#define NRF_UART_BAUDRATE_300                  0x00014000
```
Comment (carlescufi) [inline arch/arm/soc/nordic_nrf/include/nrf_common.h]: The reason that I added those is that the ones in the MDK for UART were not very accurate, so i used the ones for UARTE

Comment (carlescufi) [reply arch/arm/soc/nordic_nrf/include/nrf_common.h]: Can you verify that, with the refactor, these same values will be used?

Comment (jarz-nordic) [reply arch/arm/soc/nordic_nrf/include/nrf_common.h]: I do not want to mix these defines in uart_nrf5.c file. I will use UARTE defines in new shim for uarte.
In m opinion inaccuracy in UART defines is not so signifacant to cause any problem during the serial transsmition. We do not see complains in SDK releases about this.

File: drivers/serial/uart_nrf5.c [hunk 2]
```diff
@@ -305,13 +250,13 @@ static unsigned char uart_nrf5_poll_out(struct device *dev,
 	 */
 
 	/* reset transmitter ready state */
-	uart->EVENTS_TXDRDY = 0;
+	nrf_uart_event_clear(uart, NRF_UART_EVENT_TXDRDY);
```
Comment (carlescufi) [inline drivers/serial/uart_nrf5.c]: This has been recently changed upstream to be done **after** the `while` loop due to a race condition. Can you take a look?

**Review by carlescufi — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_nrf5.c (hunk 2 above)
Comment (carlescufi) [reply drivers/serial/uart_nrf5.c]: I am talking about [this change](https://github.com/zephyrproject-rtos/zephyr/commit/05c45e359a94e96353dfac1f0abeccf6893e988a#diff-fb209e20d9cf9e70b3dbd2748ae43f90) see however issue #7755, which seems to have been introduced by it. Hence I believe we need to incorporate that fix but also resolve the issue it introduces.

Comment (lemrey) [reply drivers/serial/uart_nrf5.c]: It seems that the change you mentioned is included in this PR: the register used to be cleared at the end of the function, now it is cleared before. That seems to have broken the console in master (see issue [#7755](https://github.com/zephyrproject-rtos/zephyr/issues/7755)) but it seems to be working fine in this PR.

File: drivers/serial/uart_nrf5.c [hunk 3]
```diff
@@ -221,29 +162,34 @@ static int uart_nrf5_init(struct device *dev)
...
+			   NRF_UART_PARITY_EXCLUDED,
+			   NRF_UART_HWFC_DISABLED);
 #endif /* CONFIG_UART_NRF5_FLOW_CONTROL */
 
 	DEV_DATA(dev)->baud_rate = CONFIG_UART_NRF5_BAUD_RATE;
 
 	/* Set baud rate */
-	err = baudrate_set(dev, DEV_DATA(dev)->baud_rate,
-		     DEV_CFG(dev)->sys_clk_freq);
+	err = baudrate_set(dev, DEV_DATA(dev)->baud_rate);
```
Comment (anangl) [inline drivers/serial/uart_nrf5.c]: It seems pointless to dedicate the `baud_rate` field for this. You can use `CONFIG_UART_NRF5_BAUD_RATE` directly here.

File: drivers/serial/uart_nrf5.c [hunk 4]
```diff
@@ -221,29 +162,34 @@ static int uart_nrf5_init(struct device *dev)
...
-	uart->EVENTS_RXDRDY = 0;
+	nrf_uart_event_clear(uart, NRF_UART_EVENT_TXDRDY);
+	nrf_uart_event_clear(uart, NRF_UART_EVENT_RXDRDY);
 
-	uart->TASKS_STARTTX = 1;
-	uart->TASKS_STARTRX = 1;
+	nrf_uart_task_trigger(uart, NRF_UART_TASK_STARTTX);
+	nrf_uart_task_trigger(uart, NRF_UART_TASK_STARTRX);
 
 	dev->driver_api = &uart_nrf5_driver_api;
```
Comment (anangl) [inline drivers/serial/uart_nrf5.c]: This should be done by the `DEVICE_AND_API_INIT` macro which should be used instead of `DEVICE_INIT` at the end of this file.

File: drivers/serial/uart_nrf5.c [hunk 5]
```diff
@@ -196,7 +136,7 @@ static int baudrate_set(struct device *dev,
  */
 static int uart_nrf5_init(struct device *dev)
 {
-	volatile struct _uart *uart = UART_STRUCT(dev);
+	NRF_UART_Type *uart = UART_STRUCT(dev);
 	struct device *gpio_dev;
```
Comment (anangl) [inline drivers/serial/uart_nrf5.c]: Binding of this device might fail but this is not checked (and should be at least with an assertion).
I can't place a comment on line 143.

**Review by anangl — CHANGES_REQUESTED** [review]

**Comment by anangl** [comment]
In a separate commit `uart_nrf5.c` should be renamed to `uart_nrfx_uart.c` (as `uart_nrfx_uarte.c` is supposed to appear soon). I think it would be good to make it part of this PR.
Occurences of "nrf5" and "NRF5" in names of functions, Kconfig entries etc. should be updated, too (to "nrfx" or "nrf", accordingly).

File: drivers/serial/uart_nrf5.c (hunk 2 above)
Comment (carlescufi) [reply drivers/serial/uart_nrf5.c]: Ah true @lemrey I misread the code.

**Review by carlescufi — APPROVED** [review]

File: drivers/serial/Kconfig.nrfx [hunk 6]
```diff
@@ -17,53 +17,61 @@ menuconfig UART_NRF5
...
 	  has to be configured.
 
-config UART_NRF5_GPIO_TX_PIN
+config UART_NRFX_UART_GPIO_TX_PIN
 	int "TX Pin Number"
 	range 0 47 if SOC_NRF52840_QIAA
 	range 0 31
-	depends on UART_NRF5
+	depends on UART_NRFX_UART
 	depends on GPIO_NRF5
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: This is unnecessary. The `_TX_PIN` option only allows to select a pin number, it does not need GPIO_NRF5 to do so.
This applies to the other pin configs here as well.

File: drivers/serial/uart_nrfx_uart.c [hunk 7]
```diff
@@ -0,0 +1,443 @@
...
+/**
+ * @brief Set the baud rate
+ *
+ * This routine set the given baud rate for the UART.
+ *
+ * @param dev UART device struct
+ * @param baudrate Baud rate
+ * @param sys_clk_freq_hz System clock frequency in Hz
+ *
+ * @return N/A
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: This description is outdated (parameters and return value).

File: drivers/serial/uart_nrfx_uart.c [hunk 8]
```diff
@@ -0,0 +1,443 @@
...
+ */
+
+static int baudrate_set(struct device *dev)
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: The `baudrate` parameter should stay. Without it `baudrate_set` looks weird.

File: drivers/serial/uart_nrfx_uart.c [hunk 9]
```diff
@@ -0,0 +1,443 @@
...
+{
+	nrf_uart_baudrate_t nrf_baudrate; /* calculated baudrate divisor */
+
+	/* Use the common nRF5 macros */
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: I don't really understand what the comment is telling me. But for sure, this "5" should be gone.

File: drivers/serial/uart_nrfx_uart.c [hunk 10]
```diff
@@ -0,0 +1,443 @@
...
+/**
+ * @brief Poll the device for input.
+ *
+ * @param dev UART device struct
+ * @param c Pointer to character
+ *
+ * @return 0 if a character arrived, -1 if the input buffer if empty.
+ */
+
+static inline int uart_nrf5_poll_in(struct device *dev, unsigned char *c)
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: Again, "nrf5" should no longer occur. Below as well.

File: drivers/serial/uart_nrfx_uart.c [hunk 11]
```diff
@@ -0,0 +1,443 @@
...
+				  CONFIG_UART_NRFX_UART_GPIO_CTS_PIN,
+				  (GPIO_DIR_IN));
+
+	nrf_uart_hwfc_pins_set(NRF_UART0,
+			       CONFIG_UART_NRFX_UART_GPIO_RTS_PIN,
+			       CONFIG_UART_NRFX_UART_GPIO_CTS_PIN);
+#ifdef CONFIG_UART_NRFX_UART_PARITY_BIT
+	nrf_uart_configure(NRF_UART0,
+			   NRF_UART_PARITY_INCLUDED,
+			   NRF_UART_HWFC_ENABLED);
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]:
```
	nrf_uart_configure(NRF_UART0,
#ifdef CONFIG_..._PARITY_BIT
			   NRF_UART_PARITY_INCLUDED,
#else
			   NRF_UART_PARITY_EXCLUDED,
#endif
#ifdef CONFIG_..._FLOW_CONTROL
			   NRF_UART_HWFC_ENABLED);
#else
			   NRF_UART_HWFC_DISABLED);
#endif
```
Less error-prone.

File: drivers/serial/uart_nrfx_uart.c [hunk 12]
```diff
@@ -0,0 +1,443 @@
...
+ * @brief Initialize UART channel
+ *
+ * This routine is called to reset the chip in a quiescent state.
+ * It is assumed that this function is called only once per UART.
+ *
+ * @param dev UART device struct
+ *
+ * @return 0 on success
+ */
+static int uart_nrfx_uart_init(struct device *dev)
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: `uart_nrfx_init` should be sufficient.

File: drivers/serial/uart_nrfx_uart.c [hunk 13]
```diff
@@ -0,0 +1,443 @@
...
+{
+	struct device *gpio_dev;
+	int err;
+
+	gpio_dev = device_get_binding(CONFIG_GPIO_NRF5_P0_DEV_NAME);
+
+	__ASSERT(gpio_dev, "UART binding failed");
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: "Cannot find %s", CONFIG_GPIO_NRF5_P0_DEV_NAME).

File: drivers/serial/Kconfig.nrfx [hunk 14]
```diff
@@ -5,7 +5,7 @@
 # SPDX-License-Identifier: Apache-2.0
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: This header needs to be updated ("nrf5"),

**Review by anangl — CHANGES_REQUESTED** [review]

File: drivers/serial/Kconfig.nrfx [hunk 15]
```diff
@@ -17,53 +17,61 @@ menuconfig UART_NRF5
...
+config UART_NRFX_UART_CLK_FREQ
 	int
 	default 16000000
-	depends on UART_NRF5
+	depends on UART_NRFX_UART
 
-config UART_NRF5_FLOW_CONTROL
+config UART_NRFX_UART_PARITY_BIT
+        bool "Parity bit enabled"
+        default n
```
[the remark this answers is not in the document]
Comment (jarz-nordic) [reply drivers/serial/Kconfig.nrfx]: Ok,
The same I will remove for UART_NRFX_FLOW_CONTROL

File: drivers/serial/uart_nrfx_uart.c (hunk 11 above)
Comment (jarz-nordic) [reply drivers/serial/uart_nrfx_uart.c]: good point!

**Comment by jarz-nordic** [comment]
Code has been updated according to your comments.

File: arch/arm/soc/nordic_nrf/nrf51/dts.fixup [hunk 16]
```diff
@@ -1,9 +1,9 @@
 /* SoC level DTS fixup file */
 
 #define CONFIG_NUM_IRQ_PRIO_BITS	ARM_V6M_NVIC_E000E100_ARM_NUM_IRQ_PRIORITY_BITS
-#define CONFIG_UART_NRF5_IRQ_PRI	NORDIC_NRF_UART_40002000_IRQ_0_PRIORITY
-#define CONFIG_UART_NRF5_BAUD_RATE	NORDIC_NRF_UART_40002000_CURRENT_SPEED
-#define CONFIG_UART_NRF5_NAME		NORDIC_NRF_UART_40002000_LABEL
+#define CONFIG_UART_NRFX_IRQ_PRI	NORDIC_NRF_UART_40002000_IRQ_0_PRIORITY
+#define CONFIG_UART_NRFX_BAUD_RATE	NORDIC_NRF_UART_40002000_CURRENT_SPEED
+#define CONFIG_UART_NRFX_NAME		NORDIC_NRF_UART_40002000_LABEL
```
Comment (anangl) [inline arch/arm/soc/nordic_nrf/nrf51/dts.fixup]: `#define CONFIG_UART_0_IRQ_PRI` and so on.

File: samples/application_development/out_of_tree_board/boards/arm/nrf52840_pca10056/nrf52840_pca10056_defconfig [hunk 17]
```diff
@@ -9,7 +9,7 @@ CONFIG_ARM_MPU_NRF52X=y
 
 # enable uart driver
 CONFIG_SERIAL=y
-CONFIG_UART_NRF5=y
+CONFIG_UART_NRFX=y
```
Comment (anangl) [inline samples/application_development/out_of_tree_board/boards/arm/nrf52840_pca10056/nrf52840_pca10056_defconfig]: `CONFIG_UART_0_NRF_UART=y`

File: drivers/serial/Kconfig.nrfx [hunk 18]
```diff
@@ -0,0 +1,79 @@
...
+
+if UART_0_NRF_UART
+
+config UART_0_NRF_PARITY_BIT
+        bool "Parity bit enabled"
+        help
+          Enable parity bit.
+
+config UART_0_NRF_FLOW_CONTROL
+	bool "Enable Flow Control"
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: "Enable flow control"

File: drivers/serial/Kconfig.nrfx [hunk 19]
```diff
@@ -0,0 +1,79 @@
...
+	depends on ((SOC_SERIES_NRF52X || SOC_SERIES_NRF51X) && (!SOC_NRF52810))
+    select NRF_UART_PERIPHERAL
+	help
+	  Enable nRF UART without EasyDMA on port 0.
+endchoice
+
+if UART_0_NRF_UART
+
+config UART_0_NRF_PARITY_BIT
+        bool "Parity bit enabled"
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: "Enable parity bit", to be consistent with "Enable flow control".

File: drivers/serial/Kconfig.nrfx [hunk 20]
```diff
@@ -0,0 +1,79 @@
...
+        help
+          Enable parity bit.
+
+config UART_0_NRF_FLOW_CONTROL
+	bool "Enable Flow Control"
+	help
+	  Enable Flow Control. If selected, additionally two pins, RTS and CTS
+	  has to be configured.
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: have

File: drivers/serial/Kconfig.nrfx [hunk 21]
```diff
@@ -0,0 +1,79 @@
...
+
+if UART_NRFX
+
+choice
+	prompt "UART Port 0 Driver type"
+
+config UART_0_NRF_UART
+	bool "nRF UART 0"
+	depends on ((SOC_SERIES_NRF52X || SOC_SERIES_NRF51X) && (!SOC_NRF52810))
+    select NRF_UART_PERIPHERAL
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: This indentation should be corrected.

File: drivers/serial/Kconfig.nrfx [hunk 22]
```diff
@@ -0,0 +1,79 @@
+# Kconfig.nrfx - NRFX UART configuration
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: nrfx

File: drivers/serial/uart_nrfx_uart.c [hunk 23]
```diff
@@ -0,0 +1,419 @@
...
+static int uart_nrfx_init(struct device *dev)
+{
+	struct device *gpio_dev;
+	int err;
+
+	gpio_dev = device_get_binding(CONFIG_GPIO_NRF5_P0_DEV_NAME);
+
+	__ASSERT(gpio_dev,
+			 "UART init failed. Cannot find %s",
+			 CONFIG_GPIO_NRF5_P0_DEV_NAME);
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: This indentation is a bit weird. One TAB too far?

File: drivers/serial/uart_nrfx_uart.c [hunk 24]
```diff
@@ -0,0 +1,419 @@
...
+				  CONFIG_UART_0_NRF_RX_PIN,
+				  (GPIO_DIR_IN));
+
+	nrf_uart_txrx_pins_set(NRF_UART0,
+			       CONFIG_UART_0_NRF_TX_PIN,
+			       CONFIG_UART_0_NRF_RX_PIN);
+
+	nrf_uart_configure(NRF_UART0,
+#ifdef CONFIG_UART_0_NRF_PARITY_BIT
+					   NRF_UART_PARITY_INCLUDED,
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: again, weird indentation

**Review by anangl — CHANGES_REQUESTED** [review]

File: drivers/serial/Kconfig.nrfx [hunk 25]
```diff
@@ -0,0 +1,79 @@
...
+	depends on UART_0_NRF_FLOW_CONTROL
+	help
+	  The GPIO pin to use for RTS.
+
+endif # UART_0_NRF_UART
+
+endif # UART_NRFX
+
+config NRF_UART_PERIPHERAL
+    bool "When set uart_nrfx_uart.c will be added to the project."
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: This should be a hidden setting (not to be changed by a user directly). By adding a prompt you make it visible, in menuconfig for instance.

**Review by anangl — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_nrfx_uart.c (hunk 23 above)
Comment (jarz-nordic) [reply drivers/serial/uart_nrfx_uart.c]: I used 4 character tab instead of 8, I will fix it.

File: drivers/serial/uart_nrfx_uart.c (hunk 24 above)
Comment (jarz-nordic) [reply drivers/serial/uart_nrfx_uart.c]: fixed

File: drivers/serial/Kconfig.nrfx (hunk 21 above)
Comment (jarz-nordic) [reply drivers/serial/Kconfig.nrfx]: fixed

File: drivers/serial/Kconfig.nrfx (hunk 20 above)
Comment (jarz-nordic) [reply drivers/serial/Kconfig.nrfx]: fixed

File: drivers/serial/Kconfig.nrfx (hunk 19 above)
Comment (jarz-nordic) [reply drivers/serial/Kconfig.nrfx]: fixed

File: drivers/serial/Kconfig.nrfx (hunk 18 above)
Comment (jarz-nordic) [reply drivers/serial/Kconfig.nrfx]: fixed

File: samples/application_development/out_of_tree_board/boards/arm/nrf52840_pca10056/nrf52840_pca10056_defconfig (hunk 17 above)
Comment (jarz-nordic) [reply samples/application_development/out_of_tree_board/boards/arm/nrf52840_pca10056/nrf52840_pca10056_defconfig]: fixed

File: arch/arm/soc/nordic_nrf/nrf51/dts.fixup (hunk 16 above)
Comment (jarz-nordic) [reply arch/arm/soc/nordic_nrf/nrf51/dts.fixup]: fixed

File: drivers/serial/Kconfig.nrfx [hunk 26]
```diff
@@ -0,0 +1,79 @@
...
+	depends on UART_0_NRF_FLOW_CONTROL
+	help
+	  The GPIO pin to use for RTS.
+
+endif # UART_0_NRF_UART
+
+endif # UART_NRFX
+
+config NRF_UART_PERIPHERAL
+	bool "When set uart_nrfx_uart.c will be added to the project."
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx]: This entry should not contain a prompt (see [my previous comment](https://github.com/zephyrproject-rtos/zephyr/pull/7681#pullrequestreview-126702201)).

File: drivers/serial/uart_nrfx_uart.c [hunk 27]
```diff
@@ -24,17 +24,15 @@ static uart_irq_callback_t m_irq_callback; /**< Callback function pointer */
  *
  * @param dev UART device struct
  * @param baudrate Baud rate
- * @param sys_clk_freq_hz System clock frequency in Hz
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: This change (as well as a few more below) should not be contained in this commit as it has nothing to do with the nrf5 renaming. Move all the changes related to shim refactoring to the first commit.

File: drivers/serial/uart_nrfx_uart.c [hunk 28]
```diff
@@ -0,0 +1,419 @@
...
+/**
+ * @brief Poll the device for input.
+ *
+ * @param dev UART device struct
+ * @param c Pointer to character
+ *
+ * @return 0 if a character arrived, -1 if the input buffer if empty.
+ */
+
+static inline int uart_nrfx_poll_in(struct device *dev, unsigned char *c)
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: All these functions cannot be "inline", since you fill the `uart_driver_api` structure with pointers to them. Some compilers might complain about it. Besides, it may confuse the ones reading the source code.

**Review by anangl — CHANGES_REQUESTED** [review]

**Comment by anangl** [comment]
@jarz Commit messages needs to be updated.
The first one does not mention the addition of parity bit support nor the simplification of the shim based on the fact that there is only one instance of the UART.
The second one does not really describe the actual changes made.

File: arch/arm/soc/nordic_nrf/nrf51/dts.fixup [hunk 29]
```diff
@@ -1,9 +1,9 @@
 /* SoC level DTS fixup file */
 
 #define CONFIG_NUM_IRQ_PRIO_BITS	ARM_V6M_NVIC_E000E100_ARM_NUM_IRQ_PRIORITY_BITS
-#define CONFIG_UART_NRF5_IRQ_PRI	NORDIC_NRF_UART_40002000_IRQ_0_PRIORITY
-#define CONFIG_UART_NRF5_BAUD_RATE	NORDIC_NRF_UART_40002000_CURRENT_SPEED
-#define CONFIG_UART_NRF5_NAME		NORDIC_NRF_UART_40002000_LABEL
+#define CONFIG_UART_0_IRQ_PRI	NORDIC_NRF_UART_40002000_IRQ_0_PRIORITY
+#define CONFIG_UART_0_BAUD_RATE	NORDIC_NRF_UART_40002000_CURRENT_SPEED
```
[the remark this answers is not in the document]
Comment (jarz-nordic) [reply arch/arm/soc/nordic_nrf/nrf51/dts.fixup]: done

**Comment by jarz-nordic** [comment]
I've reworked commits.

File: arch/arm/soc/nordic_nrf/nrf51/dts.fixup (hunk 29 above)
[the remark this answers is not in the document]
Comment (anangl) [reply arch/arm/soc/nordic_nrf/nrf51/dts.fixup]: It looks like it is not.
Maybe something eats your TABs? Some starving process, a philosopher? ;-)

File: drivers/serial/uart_nrfx_uart.c [hunk 30]
```diff
@@ -325,54 +324,42 @@ DEVICE_DECLARE(uart_nrfx_uart0);
...
 {
 	struct device *gpio_dev;
 	int err;
 
 	gpio_dev = device_get_binding(CONFIG_GPIO_NRF5_P0_DEV_NAME);
 
-	__ASSERT(gpio_dev, "UART binding failed");
+	__ASSERT(gpio_dev,
+		 "UART init failed. Cannot find %s",
+		 CONFIG_GPIO_NRF5_P0_DEV_NAME);
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: This change should also be moved to the first commit.

File: drivers/serial/uart_nrf5.c [hunk 31]
```diff
@@ -263,19 +108,17 @@ static int uart_nrf5_init(struct device *dev)
  * @return 0 if a character arrived, -1 if the input buffer if empty.
  */
 
-static int uart_nrf5_poll_in(struct device *dev, unsigned char *c)
+static inline int uart_nrf5_poll_in(struct device *dev, unsigned char *c)
```
Comment (anangl) [inline drivers/serial/uart_nrf5.c]: These "inline" keywords were supposed to disappear completely. Three of them still appear in this commit and are removed in the second one.

**Review by anangl — CHANGES_REQUESTED** [review]

**Comment by jarz-nordic** [comment]
I apologize, it should be good now.

File: drivers/serial/uart_nrfx_uart.c [hunk 32]
```diff
@@ -0,0 +1,419 @@
...
+/**
+ * @brief Output a character in polled mode.
+ *
+ * @param dev UART device struct
+ * @param c Character to send
+ *
+ * @return Sent character
+ */
+static unsigned char uart_nrfx_poll_out(struct device *dev,
+					       unsigned char c)
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: Almost there. Just correct this indentation and it will be fine.

**Review by anangl — CHANGES_REQUESTED** [review]

**Comment by jarz-nordic** [comment]
done

**Review by anangl — APPROVED** [review]
