### PR TITLE
kernel: Fix timeout issue with SYSTEM_CLOCK_SLOPPY_IDLE

### LINKED ISSUE #41422: The option CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE blocks k_sleep when CONFIG_PM is enabled
**Describe the bug**
If CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE and CONFIG_PM options are enabled together then k_sleep does not return.
According to documentation only uptime can be affected by enabling CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE option.

Platform is STM32WB55 Nucleo development board.
For blinky sample when CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE and CONFIG_PM options are set then LED is turn on all the time.
Without CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE option LED blinking is seen as expected.
Adding a few printk revealed that there is no code executed after call to k_msleep.

**To Reproduce**
Build simple blinky application with CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE and CONFIG_PM options enabled.

**Expected behavior**
The CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE should have no effect on sleep functionality..

**Impact**
annoyance

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA f92542ecf3e465861ae63fc05932fb229b527801

**Additional context**
Maybe it is a problem with following line in the next_timeout (in timeout.c) - it looks that `ret` will be always equal to -1 when CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE is set:
```C
	int32_t ret = to == NULL ? MAX_WAIT
		: CLAMP(to->dticks - ticks_elapsed, 0, MAX_WAIT);
```

### PR DESCRIPTION
**Pull request by ceolin**
We can't simply use CLAMP to set the next timeout because
when CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE is set, MAX_WAIT is
a negative number and then CLAMP will be called with
the higher boundary lower the lower boundary.

Fixes #41422

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

File: kernel/timeout.c [hunk 1]
```diff
@@ -68,8 +68,14 @@ static int32_t next_timeout(void)
 {
 	struct _timeout *to = first();
 	int32_t ticks_elapsed = elapsed();
-	int32_t ret = to == NULL ? MAX_WAIT
-		: CLAMP(to->dticks - ticks_elapsed, 0, MAX_WAIT);
+	int32_t ret;
+
+	if ((to == NULL) ||
+	    ((int64_t)(to->dticks - ticks_elapsed) > (int64_t)INT_MAX)) {
```
Comment (andyross) [inline kernel/timeout.c:74]: You want the cast interior to this subtraction.  If CONFIG_TIMEOUT_64BIT=n then the result will be computed in 32 bit precision and thus the comparison will be always false, which is not what you want.

Also IIRC the bug being addressed here is that to->dticks may be equal to K_TICKS_FOREVER (== -1).   Won't this still break?  Imagine ticks_elapsed == 2, so dticks of FOREVER will be -1 - 2 == "-3", which is less than INT_MAX so it will fail to clamp to MAX_WAIT correctly.

But then, it seems like another comment in the bug claims that in fact dticks is **never** set to K_TICKS_FOREVER (which might be true!  Refactoring elsewhere might have left dead code here).  In which case I'm confused about why we need the change at all.

**Review by andyross — CHANGES_REQUESTED** [review]
One precision bug when using 32 bit timeouts.  Also some confusion about how this is supposed to work.

File: kernel/timeout.c (hunk 1 above)
Comment (ceolin) [reply kernel/timeout.c:74]: the problem is that MAX_WAIT is `K_TICKS_FOREVER` when this option is set. In this case
```
CLAMP(to->dticks - ticks_elapsed, 0, MAX_WAIT)
```
MAX_WAIT will be < to->dticks - ticks_elapsed and consequently the returned value will always be `K_TICKS_FOREVER`.

Comment (ceolin) [reply kernel/timeout.c:74]: just to be clear the bug is *NOT* for `to->dticks == K_TICKS_FOREVER`

Comment (andyross) [reply kernel/timeout.c:74]: Ah, that's right.  Got it.  Still needs the precision fix though: as written with 32 bit timeouts it's impossible to compute dticks-elapsed to be >INT_MAX.

**Review by andyross — APPROVED** [review]
