### PR TITLE
Bluetooth: controller: Introduce config for avoiding SDU fragmentation

### LINKED ISSUE #59605: Bluetooth: Controller: Assert when creating CIG for unidir 7.5ms CIS
**Describe the bug**
Using the BAP 16_1_1 
image

hits an assert when using the hci_rpmsg sample with the `nrf5340_cpunet_iso-bt_ll_sw_split.conf`. 

**To Reproduce**
1. Checkout https://github.com/zephyrproject-rtos/zephyr/pull/59107
2. Build and flash hci_rpmsg with the above .conf file to the nRF5340 netcore
3. Build and flash the audio shell to the appcore

On the peripheral do:
```
bt init sync
bap init
bt advertise on
```

On the central do
```
bt init sync
bap init
bap preset sink 16_1_1
bt connect <addr of peripheral>
bap discover
cap_initiator discover
cap_initiator unicast-start sources 0
```

That should trigger a HCI timeout on the appcore and
```
ASSERTION FAIL [c_latency <= cig->c_latency] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_central_iso.c:480
```

on the netcore. This is not triggered by the BSIM test in https://github.com/zephyrproject-rtos/zephyr/pull/59073, but it is unclear if it is due to the patches in https://github.com/zephyrproject-rtos/zephyr/pull/59107 or due to bsim vs nRF5340. 

**Expected behavior**
Expect the request to create the CIG to pass or be rejected with an error instead of an assert. 

**Impact**
Showstopper

**Logs and console output**
See attached log. The CIG parameters can be seen by
```
[00:02:15.638,732] <dbg> bt_iso: hci_le_set_cig_params: id 0, latency 8, interval 7500, sca 0, packing 0, framing 0, num_cis 1
[00:02:15.638,763] <dbg> bt_iso: hci_le_set_cig_params: [0]: id 0, c_phy 2, c_sdu 30, c_rtn 2, p_phy 2, p_sdu 0, p_rtn 0
```
[central.txt](https://github.com/zephyrproject-rtos/zephyr/files/11833929/central.txt)

**Environment (please complete the following information):**
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/59107

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mtpr-ot**
The CIS Central uses the algorithm described in BT Core 5.4 Vol 6, Part G, Section 2.2 to calculate the Max_PDU value for framed mode.

However, HAP needs the Max_PDU to be calculated according to "Core enhancement for ISOAL CR" coming with the "Atlanta" update. With this update, the fragmentation is controlled via a parameter at CIG creation.

Enabling CONFIG_BT_CTLR_CONN_ISO_AVOID_SEGMENTATION will set the ISO_Interval to 7.5 ms for a 10 ms framed CIG, and calculate Max_PDU to 45/65 for 16/24 kHz.

Fixes #59605

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 1]
```diff
@@ -1111,29 +1120,51 @@ static void set_bn_max_pdu(bool framed, uint32_t iso_interval,
...
 		 *   MaxDrift (Max. allowed SDU delivery timing drift) = 100 ppm
 		 */
-		max_drift = DIV_ROUND_UP(SDU_MAX_DRIFT_PPM * sdu_interval, 1000000U);
-		ceil_f = DIV_ROUND_UP(iso_interval + max_drift, sdu_interval);
-		ceil_f_x_max_sdu = DIV_ROUND_UP(max_sdu * (iso_interval + max_drift),
-						    sdu_interval);
-
-		/* Strategy: Keep lowest possible BN.
-		 * TODO: Implement other strategies, possibly as policies.
+		max_drift_us = DIV_ROUND_UP(SDU_MAX_DRIFT_PPM * sdu_interval, 1000000U);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:1133]: Plesae do the below in all occurrences.

```suggestion
		max_drift_us = DIV_ROUND_UP(SDU_MAX_DRIFT_PPM * sdu_interval, USEC_PER_SEC);
```

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 2]
```diff
@@ -234,6 +234,15 @@ uint8_t ll_cig_parameters_commit(uint8_t cig_id, uint16_t *handles)
 			cig->iso_interval = BT_HCI_ISO_INTERVAL_MIN;
 		}
 
+#if defined(CONFIG_BT_CTLR_CONN_ISO_AVOID_SEGMENTATION)
+		/* Check if this is a HAP usecase which requires higher link bandwidth to ensure
+		 * segmentation is not invoked in ISO-AL.
+		 */
+		if (cig->central.framing && cig->c_sdu_interval == 10000U) {
+			cig->iso_interval = 6; /* 7500 us */
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:242]: May have defines for `10000U` and `6` ?

**Review by cvinayak — APPROVED** [review]
minor nitpick in the hack that is hardcoding the 7.5ms ISO interval... otherwise LGTM.

**Review by kruithofa — APPROVED** [review]
