### PR TITLE
samples: bluetooth: Fix bt_le_scan_stop() error checking in central_multilink sample

### LINKED ISSUE #84187: Incorrect output printed in bt_le_scan_stop() evaluation in central_multilink sample
Central multilink example outputs "Scanning successfully stopped" when it is not and does not print the error message in central_multilink example
 
Instead of evaluating `if (bt_le_scan_stop())`, the if statement should evaluate `if (bt_le_scan_stop() == 0)` in [samples/bluetooth/central_multilink/src/central_multilink.c:78](https://github.com/zephyrproject-rtos/zephyr/blob/d46546e2d82b43326bad4fee14487a35861d207f/samples/bluetooth/central_multilink/src/central_multilink.c#L78).

### PR DESCRIPTION
**Pull request by ghost**
Fixes #84187 
The logic in central_multilink example outputs "Scanning successfully stopped" when the stop call has failed as the bt_le_scan_stop() call returns 0 when successful and error when unsuccessful.

### CODE REVIEW

**Comment by jhedberg** [comment]
@ramana-g-123 thanks for the pull request! The change itself looks great, however please fix the commit message to be compliant with Zephyr requirements:

 - Add a prefix to the subject. This can be e.g. "samples: bluetooth: ..."
 - Remove the issue reference from the subject and instead have a short version of what the actual change is there, e.g. "samples: bluetooth: Fix bt_le_scan_stop() error checking"
 - Add a Signed-off-by line. git will do this automatically for you when you pass `-s` to `git commit`.
 - Add the issue reference to the PR description. GitHub recognizes this in the format "Fixes #...." and will link the two automatically together then.

**Review by rugeGerritsen — DISMISSED** [review]

File: samples/bluetooth/central_multilink/src/central_multilink.c [hunk 1]
```diff
@@ -75,7 +75,7 @@ static void device_found(const bt_addr_le_t *addr, int8_t rssi, uint8_t type,
 		return;
 	}
 
-	if (bt_le_scan_stop()) {
+	if (bt_le_scan_stop() == 0) {
 		printk("Scanning successfully stopped\n");
```
Comment (sjanc) [inline samples/bluetooth/central_multilink/src/central_multilink.c:79]: Hmm isn't the check correct but printed error message is wrong?

Comment (jhedberg) [reply samples/bluetooth/central_multilink/src/central_multilink.c:79]: Looking at the more general flow of the function, I believe the purpose is to proceed to the `bt_conn_le_create()` step when scanning was stopped, so we shouldn't return from the function in a success case. So it does seem like @sjanc is right, i.e. the log message is wrong. Since the function has an `err` variable, I'd also take advantage of it in the same go:
```c
err = bt_le_scan_stop();
if (err != 0) {
	printk("Failed to stop scanning (err %d)\n", err);
	return;
}
```

@ramana-g-123 can you update the PR accordingly? Thanks.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: samples/bluetooth/central_multilink/src/central_multilink.c (hunk 1 above)
Comment (cvinayak) [reply samples/bluetooth/central_multilink/src/central_multilink.c:79]: Agree with @sjanc and @jhedberg, on failure to stop scanning the control should not proceed further to setup a connection. Hence, it is the message that is incorrect. 

@ramana-g-123 Thank you for noticing the issue.

**Review by cvinayak — DISMISSED** [review]

File: samples/bluetooth/central_multilink/src/central_multilink.c (hunk 1 above)
Comment (ramana-g-123) [reply samples/bluetooth/central_multilink/src/central_multilink.c:79]: I believe we can also try this approach of printing the error if it's present:
```
	err = bt_le_scan_stop();
	if (err) {
		printk("%s: Stop LE scan failed (err %d)\n", __func__, err);
		return;
	}
```

**Comment by cvinayak** [comment]
> @ramana-g-123 thanks for the pull request! The change itself looks great, however please fix the commit message to be compliant with Zephyr requirements:
> 
>     * Add a prefix to the subject. This can be e.g. "samples: bluetooth: ..."
> 
>     * Remove the issue reference from the subject and instead have a short version of what the actual change is there, e.g. "samples: bluetooth: Fix bt_le_scan_stop() error checking"
> 
>     * Add a Signed-off-by line. git will do this automatically for you when you pass `-s` to `git commit`.
> 
>     * Add the issue reference to the PR description. GitHub recognizes this in the format "Fixes #...." and will link the two automatically together then.

Code looks good now... @ramana-g-123 please follow above suggestion to have single commit in this PR.

**Comment by jhedberg** [comment]
@ramana-g-123 you still need a commit message body. You can find more info here: https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

**Review by alwa-nordic — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]

**Comment by jhedberg** [comment]
@ramana-g-123 the commit message still isn't compliant, causing the Compliance check to fail: "Commit message body line exceeds max length (160>75)". Once that's fixed I think we can merge it.

**Comment by jhedberg** [comment]
@ramana-g-123 you don't need to close/re-open pull requests like this. Just a force-push is enough.

**Review by jhedberg — APPROVED** [review]

**Comment by ramana-g-123** [comment]
Hey @jhedberg , sorry for the previous commit I was unable to run compliance_checks.py with the following issue even after installing all the packages needed using [requirements.txt](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/requirements.txt)
```
  File "C:\Zephyr_RTOS\zephyr\scripts\ci\check_compliance.py", line 29, in <module>
    import magic
  File "C:\Zephyr_RTOS\zephyr\myenv\Lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "C:\Zephyr_RTOS\zephyr\myenv\Lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Review by Thalley — APPROVED** [review]

**Review by rugeGerritsen — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Comment by Thalley** [comment]
> Hey @jhedberg , sorry for the previous commit I was unable to run compliance_checks.py with the following issue even after installing all the packages needed using [requirements.txt](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/requirements.txt)
> 
> ```
>   File "C:\Zephyr_RTOS\zephyr\scripts\ci\check_compliance.py", line 29, in <module>
>     import magic
>   File "C:\Zephyr_RTOS\zephyr\myenv\Lib\site-packages\magic\__init__.py", line 209, in <module>
>     libmagic = loader.load_lib()
>   File "C:\Zephyr_RTOS\zephyr\myenv\Lib\site-packages\magic\loader.py", line 49, in load_lib
>     raise ImportError('failed to find libmagic.  Check your installation')
> ImportError: failed to find libmagic.  Check your installation
> ```

@ramana-g-123 did you install the `requirements-compliance.txt` as well?

**Comment by ramana-g-123** [comment]
Hey @Thalley , I think requirements.txt has requirements-compliance.txt in it. And yeah I did install requirements-compliance.txt alone also and checked faced the same issue

**Comment by Thalley** [comment]
> Hey @Thalley , I think requirements.txt has requirements-compliance.txt in it. And yeah I did install requirements-compliance.txt alone also and checked faced the same issue

Hmm, interestingly, it looks like the missing `libmagic` is not in the requirements.txt, but rather a lib from https://docs.zephyrproject.org/latest/develop/getting_started/index.html#install-dependencies. Not sure how well it works on Windows then. You could try https://pypi.org/project/python-libmagic/ - I wonder if we should defer to that package then, unless check_compliance.py won't run on Windows for other reasons. 

@kartben any suggestions/input?
