### PR TITLE
posix: clock: fix seconds calculation

### LINKED ISSUE #52975: posix: clock: current method of capturing elapsed time leads to loss in seconds
**Describe the bug**
Although it is a boundary, before the 64-bit tick counter rolls-over, the value of the monotonic clock (seconds field) should equal `UINT64_MAX / CONFIG_SYS_CLOCK_TICKS_PER_SEC` (integer division).

Currently, it seems to be off by an order of magnitude (test case provided in PR).

**Please also mention any information which could help others to understand
the problem you're facing**:
 - **What target platform are you using?** all
 - **What have you tried to diagnose or workaround this issue?** written a test case
 - **Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?** No

**To Reproduce**
1. apply changes in referenced PR
2. un-apply changes to `lib/posix/clock.c`
3. `west build -p auto -b qemu_x86_64 -t run tests/posix/common`

**Expected behavior**
```
*** Booting Zephyr OS build zephyr-v3.2.0-2459-gdffb02fd134e ***
Running TESTSUITE posix_apis
===================================================================
START - test_clock_gettime_rollover
CONFIG_SYS_CLOCK_TICKS_PER_SEC: 100
rollover_s: 184467440737095516
t-1: {184467440737095516, 140000000}
t+0: {184467440737095516, 150000000}
t+1: {0, 0}
 PASS - test_clock_gettime_rollover in 0.063 seconds
 ===================================================================
 ```

**Impact**
That really depends on the application. It can be an annoyance for some but a showstopper for others.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.2.0-2459-gdffb02fd134e ***
Running TESTSUITE posix_apis
===================================================================
START - test_clock_gettime_rollover
CONFIG_SYS_CLOCK_TICKS_PER_SEC: 100
rollover_s: 184467440737095516
t-1: {18446744073709551, 596000000}

    Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/clock.c:169: posix_apis_test_clock_gettime_rollover: rollover_s not equal to ts[0].tv_sec

 FAIL - test_clock_gettime_rollover in 0.025 seconds
 ===================================================================
 ```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): any
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.15.2
 - Commit SHA or Version used: bba9fc98535567008728143cc3b8c029670d84c6

**Additional context**
This issue was encountered while writing tests to verify the fixes in
- https://github.com/zephyrproject-rtos/zephyr/pull/41602
- https://github.com/zephyrproject-rtos/zephyr/pull/41814
and while working on
- https://github.com/zephyrproject-rtos/zephyr/issues/52825

### PR DESCRIPTION
**Pull request by cfriedt**
The previous method used to calculate seconds in `clock_gettime()` seemed to have an inaccuracy that grew with time, causing the seconds to be off by an order of magnitude when ticks would roll over.

Edit: technically, this is likely a bug in `z_tmcvt()`.

Fixes #52975

### CODE REVIEW

**Comment by cfriedt** [comment]
cc @AndreyDodonov-EH, @too1

**Comment by cfriedt** [comment]
* woops - turned off automatic code formatting to reduce the scope of the diff, but then left a dangling `{`. It's fixed now.

File: lib/posix/clock.c [hunk 1]
```diff
@@ -48,8 +48,8 @@ int z_impl_clock_gettime(clockid_t clock_id, struct timespec *ts)
 	}
 
 	uint64_t ticks = k_uptime_ticks();
-	uint64_t elapsed_secs = k_ticks_to_ms_floor64(ticks) / MSEC_PER_SEC;
-	uint64_t nremainder = ticks - k_ms_to_ticks_floor64(MSEC_PER_SEC * elapsed_secs);
+	uint64_t elapsed_secs = ticks / CONFIG_SYS_CLOCK_TICKS_PER_SEC;
+	uint64_t nremainder = ticks - elapsed_secs * CONFIG_SYS_CLOCK_TICKS_PER_SEC;
```
Comment (andyross) [inline lib/posix/clock.c:52]: This doesn't look right.  The conversion function should be precise and reduce to the division already on all systems where that's possible.  The bug is in the second line I think, where it feeds the result back into the reverse conversion; that's going to lose bits in configurations where the tick rate isn't divisible by ms.  Can you check that just the second line fixes the issue?

Also... I haven't pulled up the whole file to check, but I have a hard time believing that that nremainder value is anything but a footgun in an implementation of clock_gettime().  There shouldn't be any state held, and if we want higher precision values we should start there instead of back-converting from coarser units like seconds.

My notion of an idealized implementation here should be as simple as `uint64_t ns = k_ticks_to_us_floor64(k_uptime_ticks())`, and then just doing division/modulus ops to extract tv_nsec and tv_sec.

Comment (cfriedt) [reply lib/posix/clock.c:52]: @andyross - with just the second line, we get a failure of
```
START - test_clock_gettime_rollover
CONFIG_SYS_CLOCK_TICKS_PER_SEC: 100
rollover_s: 184467440737095516
t-1: {18446744073709551, 596000000}
```

**Comment by cfriedt** [comment]
Rebased after changes in #53147

**Comment by cfriedt** [comment]
* Rebased after #53177

**Comment by cfriedt** [comment]
@andyross - if there is a doubt in your mind, this should probably help. Almost looks like a Christmas tree, so Merry Christmas! 🎅 ❄️ ☃️ 🎄 
Screen Shot 2022-12-20 at 9 54 01 AM
[generator.cpp.txt](https://github.com/zephyrproject-rtos/zephyr/files/10269557/generator.cpp.txt)

**Comment by cfriedt** [comment]
* use `uint64_t` instead of `int64_t` in `sys_clock_tick_set()` - no reason it should be signed

File: lib/posix/clock.c (hunk 1 above)
Comment (xyzzy42) [reply lib/posix/clock.c:52]: IMHO, the routines in time_units.h should have the set of `k_ticks_to_secs_*()` functions.  It's milli, micro, and nano, but not full seconds.  I guess the thought was that conversion to seconds is simple enough, one should write out the division, as is done here.  But as soon as you toss in rates determined at run time or non-integral clock speeds, it would be nice to not make everyone write their own code for it.

**Comment by xyzzy42** [comment]
> That's with `CONFIG_SYS_CLOCK_TICKS_PER_SEC=100`. The error factor vanishes with `CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000` or `CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000`. However, it is exacerbated when `CONFIG_SYS_CLOCK_TICKS_PER_SEC=10`.

I don't get how those numbers came from `CONFIG_SYS_CLOCK_TICKS_PER_SEC=100`? 
```c
    const uint64_t rollover_s = UINT64_MAX / CONFIG_SYS_CLOCK_TICKS_PER_SEC;
    …
    curr_tick = rollover_s * CONFIG_SYS_CLOCK_TICKS_PER_SEC;
    cout << curr_tick << "\t" << method1() << "\t" << method2() << endl;
```
Shouldn't the final value of curr_tick be 18446744073709551600 and not 18446744073709500000?

Anyway, the existing code has an obvious bug if `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is less than 1000.  Converting to ms as an (unnecessary) intermediate step to seconds overflows, even though neither the tick count nor the time in seconds will overflow.  This is because ms will be a larger number than ticks.

Another bug is in the test code.  It finds the second in which the 64-bit tick counter overflows.  But the result will be stored in a timespec.  This is allowed to have a **32-bit signed** seconds field.  This will overflow before the tick counter unless `CONFIG_SYS_CLOCK_TICKS_PER_SEC`  is > 2,000,000,000.  In other words, rollover_s can overflow `ts->tv_sec`.

File: lib/posix/clock.c (hunk 1 above)
Comment (xyzzy42) [reply lib/posix/clock.c:52]: > My notion of an idealized implementation here should be as simple as `uint64_t ns = k_ticks_to_us_floor64(k_uptime_ticks())`,

You meant `_to_ns` of course.  This expression does overflow before a 64-bit cycle counter overflows, for clock rates < 1 GHz.  It does take some 584 years to do this.  So realistically, it ought to be good enough for any reasonable value of a timeout or time delta or timestamp.

However, @cfriedt's test looks at values around where the cycle counter overflows, which is large enough to trigger the overflow.

**Comment by cfriedt** [comment]
> > That's with `CONFIG_SYS_CLOCK_TICKS_PER_SEC=100`. The error factor vanishes with `CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000` or `CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000`. However, it is exacerbated when `CONFIG_SYS_CLOCK_TICKS_PER_SEC=10`.
> 
> I don't get how those numbers came from `CONFIG_SYS_CLOCK_TICKS_PER_SEC=100`? 
> ```c
>     const uint64_t rollover_s = UINT64_MAX / CONFIG_SYS_CLOCK_TICKS_PER_SEC;
>     …
>     curr_tick = rollover_s * CONFIG_SYS_CLOCK_TICKS_PER_SEC;
>     cout << curr_tick << "\t" << method1() << "\t" << method2() << endl;
> ```
> Shouldn't the final value of curr_tick be 18446744073709551600 and not 18446744073709500000?

That's only to get an arbitrary `curr_tick` less than `rollover_s` (with up to 1s of ticks to spare).

I realized that my for-loop boundary conditions were not in correct units. Still illustrates the issue in any case.

`for(curr_tick = 0; curr_tick < rollover_s`

> Anyway, the existing code has an obvious bug if `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is less than 1000.  Converting to ms as an (unnecessary) intermediate step to seconds overflows, even though neither the tick count nor the time in seconds will overflow.  This is because ms will be a larger number than ticks.

👍

> Another bug is in the test code.  It finds the second in which the 64-bit tick counter overflows.  But the result will be stored in a timespec.  This is allowed to have a **32-bit signed** seconds field.  This will overflow

Given that Zephyr will own the POSIX headers, that's a good point. We should enforce that it's 64-bit (a recommendation for the 2038 problem).

https://pubs.opengroup.org/onlinepubs/9699919799/functions/time.html

Thanks for the review.

**Review by jeremybettis — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]

**Comment by xyzzy42** [comment]
The overflow test doesn't respect `CONFIG_SYS_CLOCK_MAX_TIMEOUT_DAYS`.   It assumes the 64-bit tick counter is the only possible overflow, but I don't think that is guaranteed.
