### PR TITLE
kernel: mmu: Fix static analysis issue

### LINKED ISSUE #65375: [Coverity CID: 322696] Inequality comparison against NULL in kernel/mmu.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/kernel/mmu.c

Category: Incorrect expression
Function: `z_phys_map`
Component: Kernel
CID: [322696](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=322696)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/mmu.c#L780

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_BAD_COMPARE). ([CWE-480](http://cwe.mitre.org/data/definitions/480.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by peter-mitsis**
Instead of performing a set of relative address comparisons using pointers of type 'uint8_t *', we leverage the existing IN_RANGE() macro and perform the comparisons using 'uintptr_t'.

Fixes #65375

### CODE REVIEW

**Comment by npitre** [comment]
This is not equivalent code. The middle `&&` should remain a `||`.
Note the preceding comment: "if either end of region is within virtual 
memory space ..."

**Comment by peter-mitsis** [comment]
> This is not equivalent code. The middle `&&` should remain a `||`. Note the preceding comment: "if either end of region is within virtual memory space ..."

D'oh! You are absolutely right! Thank goodness for reviews.

**Review by npitre — APPROVED** [review]

File: kernel/mmu.c [hunk 1]
```diff
@@ -781,10 +781,13 @@ void z_phys_map(uint8_t **virt_ptr, uintptr_t phys, size_t size, uint32_t flags)
...
 		 */
-		if (((dest_addr >= Z_VIRT_RAM_START) &&
-		     (dest_addr < Z_VIRT_RAM_END)) ||
-		    (((dest_addr + aligned_size) >= Z_VIRT_RAM_START) &&
-		     ((dest_addr + aligned_size) < Z_VIRT_RAM_END))) {
+
+		if (IN_RANGE(aligned_phys,
+			      (uintptr_t)Z_VIRT_RAM_START,
+			      (uintptr_t)(Z_VIRT_RAM_END - 1)) ||
+		    IN_RANGE(aligned_phys + aligned_size - 1,
```
Comment (dcpleung) [inline kernel/mmu.c:788]: I think you can skip the minus 1 here, as you have remove 1 byte from the end value. Or else the comparison would be off by 1 byte.

Comment (peter-mitsis) [reply kernel/mmu.c:788]: I think that it is needed. The _IN_RANGE()_ macro uses a _<=_ comparison for the upper bound and _Z_VIRT_RAM_END_ is simply "start address + size". Furthermore, in the corner case where that would take us to the very end of the addresses, without the "-1", our end address would wrap around to zero. With the "-1", we ensure that we remain within the boundaries.

Comment (dcpleung) [reply kernel/mmu.c:788]: Ahh... pointer math is confusing.

**Review by dcpleung — APPROVED** [review]
