### PR TITLE
pm: cc13x2_cc26x2: Implement their own constraint

### LINKED ISSUE #38362: soc: ti cc13x2-cc26x2: PM standby + radio interaction regression
**Description**
Hello, my project uses the TI CC13x2/CC26x2 platform and I have discovered a critical regression regarding power management after upgrading my Zephyr stack: the radio module won't work anymore after a PM Standby state wakeup  (actually, the entire program enters an infinite busy wait inside RFCDoorbellSendTo).

I have identified the root cause to be 65e4add74ecae7281299ffb0a90292e6536ccc41, because it eliminated the code which checks for disallowed the PM state (see Additional Context for explaination and potential solution).

**To Reproduce**
To reproduce, I used two `cc1352r1_launchxl`s and the echo example.
1. checkout https://github.com/niflostancu/zephyr/tree/cc13x2_radio_standby_bug (modified example to allow standby).
2. For the server board: `west build --pristine -b cc1352r1_launchxl samples/net/sockets/echo_server -- -DOVERLAY_CONFIG="overlay-802154-subg.conf" && west flash`
3. For the client board: `west build --pristine -b cc1352r1_launchxl samples/net/sockets/echo_client -- -DOVERLAY_CONFIG="overlay-802154-subg.conf" && west flash`
4. Use debugger on the client board, see it getting stuck on `RFCDoorbellSendTo`.

**Expected behavior**
The radio should work after waking up from standby.

**Impact**
This is a showstopper for anyone using the CC13x2/26x2 radio and power management.

**Logs and console output**
```
pwndbg> bt
#0  0x0000b546 in NOROM_RFCDoorbellSendTo (pOp=pOp@entry=67174401) at .../rfc.c:104
#1  0x0000c9b2 in RF_abortCmd (...) at .../RFCC26X2_multiMode.c:3818
#2  0x00014332 in RF_flushCmd (...) at .../C26X2_multiMode.c:5134
#3  0x00013ad2 in ieee802154_cc13xx_cc26xx_subg_stop (...) at .../ieee802154_cc13xx_cc26xx_subg.c:518
#4  0x0000a77e in ieee802154_cc13xx_cc26xx_subg_tx (...) at .../ieee802154_cc13xx_cc26xx_subg.c:371
```

**Environment:**
 - OS: Arch Linux
 - Zephyr SDK 0.13.0
 - Commit e1481fee4a

**Additional context**
The removed code (https://github.com/zephyrproject-rtos/zephyr/commit/65e4add74ecae7281299ffb0a90292e6536ccc41#diff-d848b34b5a2e740d33ff20ca9bc29306704d50e2798e931d178ac187e559d3cb) contains several state disallow sequences:
```c
if ((constraints & (1 <<
		PowerCC26XX_DISALLOW_STANDBY)) != 0) {
	disallowed = true;
}
```
The `DISALLOW_STANDBY` is set whenever the radio core is up (see [RFCC26X2_multiMode.c](https://github.com/zephyrproject-rtos/hal_ti/blob/master/simplelink/source/ti/drivers/rf/RFCC26X2_multiMode.c#L3031)), but `Power_sleep` doesn't check it to stop the standby procedure.
I think the solution would be to set a pm_constraint for  whenever a radio interface is up (I can come with a pull request).

The same happens with `PowerCC26XX_DISALLOW_IDLE` which, I see, is set when the XOSC_HF is pending to be configured.
Does zephyr do this? Someone should check if this case happens, too :D

### PR DESCRIPTION
**Pull request by ceolin**
TI Hal has its own constraint API that is used by its drivers. These
constraints need to be correlated with Zephyr constraints to be
constraints set in the HAL be visible on Zephyr and vice-versa.

Fixes #38362

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

File: subsys/pm/pm_ctrl.c [hunk 1]
```diff
@@ -18,7 +18,7 @@ LOG_MODULE_DECLARE(power);
 
 static atomic_t power_state_disable_count[PM_STATES_LEN];
 
-void pm_constraint_set(enum pm_state state)
+__weak void pm_constraint_set(enum pm_state state)
```
Comment (gmarull) [inline subsys/pm/pm_ctrl.c:21]: nit: this should go into a separate commit, since from now on constraint can be overridden.

Since usage of `__weak` is now being debated, an alternative could be a Kconfig option like `CONFIG_PM_CUSTOM_CONSTRAINTS`, selected by SoC code. See https://github.com/zephyrproject-rtos/zephyr/pull/37435#issuecomment-916564329

Comment (ceolin) [reply subsys/pm/pm_ctrl.c:21]: I was aware of it. The problem is that we have weak linkage all over the project and not a clear a plan to get rid of this. Probably instead of adding more KConfig symbols that can easily became a mess, we should add some kind of PM API that can be implemented by platform and applications and have some well defined precedence.
This solution will not get into 2.7 release, so instead of adding an extra KConfig symbol that will need to lead with later this fix is simpler and has less impact.

Of course, if  the direction to go regarding weak symbol is that, I definitely can change it.  My only point it that this seems to over complicate it.

Comment (cfriedt) [reply subsys/pm/pm_ctrl.c:21]: If adding the weak symbol fixes the issue for 2.7.0, then i think it's fine to add. Does it need to be in a separate commit?

**Review by cfriedt — APPROVED** [review]
Looks fine to me - @ceolin or @niflostancu - are able to verify with hardware that this fixes #38362?

**Comment by ceolin** [comment]
Just split  the commit as suggested.

**Review by gmarull — APPROVED** [review]
