### PR TITLE
drivers: espi: xec: Validate channels espi configuration

### LINKED ISSUE #24162: eSPI KConfig overrides espi_config API channel selection in eSPI driver
**Describe the bug**
eSPI KConfig channel enables overrides anything client driver is requesting.
i.e KConfig indicates following channels are supported 
VW_CHANNEL
OOB_CHANNEL
FLASH_CHANNEL

If user decides only to enable only VW channel and Peripheral channel, eSPI driver still sends the wrong channel capabilities to eSPI partner. (VW/PC/OOB).

**To Reproduce**
1) Change initialization in samples/drivers/espi/src/main.c  under espi_init
2) Reduce the amount of channels support

3) build 
mkdir build; cd build
 cmake -DBOARD=board\mec15xx
make

4) Run the driver sample. 
All channels supported by the driver are advertised as enabled instead only the ones selected by client driver via espi_config API.

**Expected behavior**
Only the channels selected by the client driver should be advertised.

**Impact**
This deviates from eSPI API intention and slows debug due mismatched capabilities sicne eSPI analyzer to debug early handshake issues.

### PR DESCRIPTION
**Pull request by albertofloyd**
Ensure driver's client channel configuration selection is used.
Fixes: #24162

### CODE REVIEW

**Review by scottwcpg — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

File: drivers/espi/espi_mchp_xec.c [hunk 1]
```diff
@@ -232,6 +233,41 @@ static int espi_xec_configure(struct device *dev, struct espi_cfg *cfg)
 		cap1 |= (iomode << MCHP_ESPI_GBL_CAP1_IO_MODE_POS);
 	}
 
+	/* Validdate and translate eSPI API channels to MEC capabilities */
```
Comment (nashif) [inline drivers/espi/espi_mchp_xec.c:236]: Validate

**Review by nashif — APPROVED** [review]
