### PR TITLE
soc: ti: simplelink: cc13x2x7_cc26x2x7: Add poweroff support

### LINKED ISSUE #4: Need to add HAS_POWEROFF to cc13x2x7_cc26x2x7 Kconfig
**Describe the bug**
Compiling the sys_poweroff example from https://github.com/zephyrproject-rtos/zephyr/blob/a317f194b9d42e5dd0538d6e0657252bf7bcca1c/samples/boards/ti/cc13x2_cc26x2/system_off/src/main.c#L62 does not work (undefined symbol sys_poweroff).

**To Reproduce**
See https://openbeagle.org/jkridner/bcf-sensortest/-/commit/d37a3e0e7104b2b4fe334836b845c2de4f78281e

**Expected behavior**
Series should be one that defines CONFIG_HAS_POWEROFF per https://docs.zephyrproject.org/4.1.0/kconfig.html.

**Impact**
Unable to test power consumption in poweroff on BeagleConnect Freedom

**Logs and console output**
See https://openbeagle.org/jkridner/bcf-sensortest/-/jobs/64999

### PR DESCRIPTION
**Pull request by Ayush1325**
- Tested on BeagleConnect Freedom with samples/boards/ti/cc13x2_cc26x2/system_off
- Fixes https://github.com/beagleboard/zephyr/issues/4

### CODE REVIEW

**Comment by Ayush1325** [comment]
cc @jadonk

File: soc/ti/simplelink/cc13x2x7_cc26x2x7/poweroff.c [hunk 1]
```diff
@@ -0,0 +1,16 @@
+/*
+ * Copyright (c) 2023 Nordic Semiconductor ASA
```
Comment (bogdanovs) [inline soc/ti/simplelink/cc13x2x7_cc26x2x7/poweroff.c:2]: Fix year in Copyright

Comment (Ayush1325) [reply soc/ti/simplelink/cc13x2x7_cc26x2x7/poweroff.c:2]: This file is a copy of `soc/ti/simplelink/cc13x2_cc26x2/poweroff.c` and no changes have been made to it's contents. Do I still need to change the year of that copyright? Specially since I am not affiliated with `Nordic Semiconductor ASA`?

Comment (bogdanovs) [reply soc/ti/simplelink/cc13x2x7_cc26x2x7/poweroff.c:2]: No keep it as is.

**Review by bogdanovs — APPROVED** [review]

**Review by jadonk — APPROVED** [review]

**Review by vaishnavachath — APPROVED** [review]
