### PR TITLE
usb: device: allow uneven SN to be obtained from HWINFO

### LINKED ISSUE #69585: usb_update_sn_string_descriptor generates only even-length strings
**Describe the bug**
When CONFIG_USB_DEVICE_SN is set to odd-length string (e.g. "CHANGEMEPLZ" :), which is 11 characters):
  - the usb_update_sn_string_descriptor generates  1 byte too long (12 chars)
  - failing usb_fix_ascii_sn_string_descriptor check for string length equality
  - the generated USB serial remains compilation-time set fixed.

**To Reproduce**
0. Take any USB sameple (e.g. samples/subsys/usb/console)
1. Add to prj.conf line `CONFIG_USB_DEVICE_SN="CHANGEMEPLZ"`
2. build & run
3. See the connected device usb serial -- it would be "CHANGEMEPLZ"

**Expected behavior**
It should be some random string by default, e.g "A1B2C3D4E5F".

**Impact**
Annoyance

**Additional context**
The easiest fix is to add to the default `usb_update_sn_string_descriptor` implementation line:
```
sn[sizeof(CONFIG_USB_DEVICE_SN)-1] = 0;
```
right before the final return, which will make string length right -- at expense of not using the lowest entropy bits.

Alternate solution is to change the return to:
```
return &sn[1-sizeof(CONFIG_USB_DEVICE_SN)%2];
```
which will use string of the right length and use the lowest entropy bits, but looks little bit cryptic.

### PR DESCRIPTION
**Pull request by jfischer-no**
If the length of the string literal reserved for the serial number descriptor is odd, the string is not used because its length is always even and therefore one character longer. Fix this by using the shortest length for the copy.

Fixes: #69585

### CODE REVIEW

File: subsys/usb/device/usb_descriptor.c [hunk 1]
```diff
@@ -347,12 +347,11 @@ static void usb_fix_ascii_sn_string_descriptor(struct usb_sn_descriptor *sn)
...
 
 	if (runtime_sn_len != default_sn_len) {
-		LOG_ERR("the new SN descriptor doesn't have the same "
+		LOG_WRN("the new SN descriptor doesn't have the same "
 			"length as CONFIG_USB_DEVICE_SN");
-		return;
 	}
 
-	memcpy(sn->bString, runtime_sn, runtime_sn_len);
+	memcpy(sn->bString, runtime_sn, MIN(runtime_sn_len, default_sn_len));
```
Comment (tmon-nordic) [inline subsys/usb/device/usb_descriptor.c:354]: What about the trailing bytes? Shouldn't bLength be reduced to reflect shorter string?

**Review by tmon-nordic — COMMENTED** [review]
I cannot understand the commit message. Why does it specifically refer to odd length, when the code is more about "different length"?

File: subsys/usb/device/usb_descriptor.c (hunk 1 above)
Comment (datacompboy) [reply subsys/usb/device/usb_descriptor.c:354]: the `sn->bString` already has the original string with zero byte there; so memcpy here always copy non-zero bytes only.
The leftover byte in `runtime_sn` will be ignored, which means that for the SN generation used not the lowest bits of entropy; but we talk about 4 bits loss here only.

**Comment by datacompboy** [comment]
> I cannot understand the commit message. Why does it specifically refer to odd length, when the code is more about "different length"?

Default implementation of `usb_update_sn_string_descriptor` returns string with length of `2*(int)(default_sn_len+1)/2)`, so the result is incorrect for serial numbers of odd lengths, resulting string is 1 character longer.

**Review by tmon-nordic — APPROVED** [review]

**Review by kartben — APPROVED** [review]
LGTM
