### PR TITLE
pm: fix NULL pointer dereference with stats

### LINKED ISSUE #89228: Null reference pointer when using CONFIG_PM_STATS
**Describe the bug**
the test `pm.states.api.dts` causes a segmentation fault due to a NULL pointer if `CONFIG_PM_STATS=y`.

In `pm_system_suspend()`:

```
	pm_state_set(z_cpus_pm_state[id]->state, z_cpus_pm_state[id]->substate_id);
	pm_stats_stop();

	/* Wake up sequence starts here */
	pm_stats_update(z_cpus_pm_state[id]->state);
```

The routine `pm_state_set()` eventually calls `pm_system_resume()` which sets the `z_cpus_pm_state[id]` to NULL.  `pm_stats_update()` then causes the segmentation fault.

**To Reproduce**
Run

```
./scripts/twister -ivc -s pm.states.api.dts -x CONFIG_PM_STATS=y -x CONFIG_STATS=y
```

**Expected behavior**
The PM tests should not crash.

**Logs and console output**
Twister output:
```
INFO    - 1/1 native_sim/native         tests/subsys/pm/power_states_api/pm.states.api.dts FAILED Failed (rc=-11) (native 0.353s <host>)
```

### PR DESCRIPTION
**Pull request by dsseng**
Fix null pointer dereference in pm_system_suspend

Fixes #89228

Signed-off-by: Dmitrii Sharshakov <d3dx12.xx@gmail.com>

### CODE REVIEW

File: subsys/pm/pm.c [hunk 1]
```diff
@@ -230,7 +230,8 @@ bool pm_system_suspend(int32_t kernel_ticks)
 
 	if (IS_ENABLED(CONFIG_PM_STATS)) {
 		pm_stats_stop();
-		pm_stats_update(z_cpus_pm_state[id]->state);
+		pm_stats_update(z_cpus_pm_state[id] ?
+				z_cpus_pm_state[id]->state : PM_STATE_ACTIVE);
```
Comment (dsseng) [inline subsys/pm/pm.c:234]: Just like in the following code we assume we're active once resumed if not known:

```c
	SYS_PORT_TRACING_FUNC_EXIT(pm, system_suspend, ticks,
				   z_cpus_pm_state[id] ?
				   z_cpus_pm_state[id]->state : PM_STATE_ACTIVE);
```

**Review by bjarki-andreasen — APPROVED** [review]

**Review by JordanYates — APPROVED** [review]
