### PR TITLE
tests/kernel/sched/schedule_api: Fix static analysis volatile warning

### LINKED ISSUE #18446: [Coverity CID :203532]Incorrect expression in /tests/kernel/sched/schedule_api/src/user_api.c
Static code scan issues seen in File: /tests/kernel/sched/schedule_api/src/user_api.c
 Category: Incorrect expression
 Function: test_user_k_is_preempt
 Component: Tests
 CID: 203532
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by andyross**
We were testing the value of a volatile variable inside a zassert,
which static analysis doesn't like.  In principle, it might be
volatile because it's an MMIO register or something and the read is a
side effect, and an assertion will be optionally compiled.  (Except
here the value is just regular memory marked volatile for
threadsafety, and zassert will never be elided in a test, but the tool
doesn't know that).

Refactor a little so we always read the variable in a way the tool can
detect is consistent.

Fixes #18446

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]

File: tests/kernel/sched/schedule_api/src/user_api.c [hunk 1]
```diff
@@ -9,7 +9,7 @@
 struct k_thread user_thread;
 K_SEM_DEFINE(user_sem, 0, 1);
 
-ZTEST_BMEM volatile bool thread_was_preempt;
+ZTEST_BMEM volatile int thread_was_preempt;
```
Comment (MaureenHelm) [inline tests/kernel/sched/schedule_api/src/user_api.c]: why did you change the type from `bool` to `int`?

Comment (andyross) [reply tests/kernel/sched/schedule_api/src/user_api.c]: To make it a machine word, some architectures generate more code for bytewise reads, and being volatile it's going to be repeated every time.  But really there's no particularly strong reason to have it in the commit.
