### PR TITLE
reserved-memory: Fix layering violation

### LINKED ISSUE #38886: devicetree/memory.h probably should not exist as-is
**Describe the bug**

Originally introduced in #35460. I have no idea how I missed all of this in review, but it showed up while I was working on release notes.

Marking high because it affects a stable API (devicetree.h) and these concerns ought to be fixed before we include the new API in the v2.7 LTS release with known mistakes from an API perspective.

1. we should not be adding any include/devicetree/foo.h headers for manual inclusion; they should be included at the bottom of devicetree.h. So either devicetree/memory.h is in the wrong place or it needs to be included from devicetree.h.
2. At least some of the contents are in the wrong place. Specifically `#define DT_RESERVED_MEM_GET_PTR(node_id) _DT_RESERVED_START(node_id)` refers to `_DT_RESERVED_START`, which is defined in include/linker/devicetree_reserved.h. This is a layering violation as devicetree.h macros should not depend on contents of higher layer headers.
3. No documentation was added to doc/reference/devicetree/api.rst for the macros in devicetree/memory.h
4. No explicit test coverage under tests/lib/devicetree exists; we require all macros to have API tests and docs.

Given the above, my suspicion is that these macros should probably all go to linker/devicetree_reserved.h. This is not an officially documented API (in the sense of https://docs.zephyrproject.org/latest/reference/api/overview.html) and can therefore basically do whatever it wants without getting into as much trouble from an API stability perspective.

**Environment (please complete the following information):**
 - Commit SHA or Version used: v2.7.0-rc3

### PR DESCRIPTION
**Pull request by carlocaione**
Move memory.h out of the way in a more "private" space
(include/linker/devicetree_reserved.h) to prevent polluting the
devicetree space.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

Fixes: #38886

### CODE REVIEW

File: include/linker/devicetree_reserved.h [hunk 1]
```diff
@@ -57,3 +57,109 @@
...
+ *      };
+ *
+ * Example usage:
+ *
+ *     DT_RESERVED_MEM_GET_PTR(DT_NODELABEL(n)) // (uint8_t *) 0x42000000
+ *
+ * @param node_id node identifier
+ * @return pointer to the beginning of the reserved-memory region
+ */
+#define DT_RESERVED_MEM_GET_PTR(node_id) _DT_RESERVED_START(node_id)
```
Comment (mbolivar-nordic) [inline include/linker/devicetree_reserved.h:81]: Can you also do a sed to rename these to `LINKER_DT` instead of `DT` so we don't pollute the `DT_` namespace?

**Review by mbolivar-nordic — COMMENTED** [review]
Thanks, just one more namespace request. Hoping we can catch this in time for 2.7.

File: include/linker/devicetree_reserved.h (hunk 1 above)
Comment (carlocaione) [reply include/linker/devicetree_reserved.h]: done

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
Thanks so much for the fast fix!

**Comment by cfriedt** [comment]
@carlocaione @mbolivar-nordic 
Is `qemu_cortex_a53` / aarch64 syscon the places that touched these reserved memory definitions? If so,  I would be happy to stamp.

**Comment by carlocaione** [comment]
> @carlocaione @mbolivar-nordic 
> 
> Is `qemu_cortex_a53` / aarch64 syscon the places that touched these reserved memory definitions? If so,  I would be happy to stamp. 

Yes, currently only these two samples / tests are using the definitions.

**Review by cfriedt — APPROVED** [review]
