### PR TITLE
tests: drivers: disk: Replace the MAX function with if and else

### LINKED ISSUE #51146: Running test: drivers:  disk: disk_access with  RAM disk  fails
Exploring option to enable RAM filesystem, attempted running RAM disk test case.
The test fails for certain sectors.
Is this a configuration error? 

SUITE FAIL -   0.00% [disk_driver]: pass = 0, fail = 2, skip = 0, total = 2 durs
 - FAIL - [disk_driver.test_read] duration = 0.032 seconds
 - FAIL - [disk_driver.test_write] duration = 0.041 seconds

**To Reproduce**

1. Modify test code to enable RAM disk 
```
- CONFIG_DISK_DRIVER_SDMMC=y
+CONFIG_DISK_DRIVER_RAM=y
+CONFIG_DISK_RAM_VOLUME_SIZE=16

```
3. cd tests/drivers/disk/disk_access$
4. west build -c -p -b mec172xevb_assy6906
5. west_flash

Running TESTSUITE disk_driver
===================================================================
Disk reports 32 sectors
Disk reports sector size 512
START - test_read
Testing reads of 8 sectors
E: Sector 39 is outside the range 32
Testing reads of 1 sectors
Testing reads of 29 sectors
E: Sector 16 is outside the range 32

    Assertion failed at WEST_TOPDIR/zephyr_albertofloyd/tests/drivers/disk/disk)
Failed to read from mid disk sector
 FAIL - test_read in 0.032 seconds
===================================================================
START - test_write
Testing writes of 8 sectors
E: Sector 39 is outside the range 32
Testing writes of 1 sectors
Testing writes of 29 sectors
E: Sector 16 is outside the range 32

    Assertion failed at WEST_TOPDIR/zephyr_albertofloyd/tests/drivers/disk/disk)
Failed to write to mid disk sector
 FAIL - test_write in 0.041 seconds
===================================================================
TESTSUITE disk_driver failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -   0.00% [disk_driver]: pass = 0, fail = 2, skip = 0, total = 2 durs
 - FAIL - [disk_driver.test_read] duration = 0.032 seconds
 - FAIL - [disk_driver.test_write] duration = 0.041 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED

### PR DESCRIPTION
**Pull request by hunterhu3000**
As the parameter of "MAX" is uint32, the nagetive number will be bigger than 0. The MAX function does not work as expected. So change it to if/else form.

Fixes #51146

Signed-off-by: Hu Zhenyu <zhenyu.hu@intel.com>

### CODE REVIEW

**Review by danieldegrasse — DISMISSED** [review]

File: tests/drivers/disk/disk_access/src/main.c [hunk 1]
```diff
@@ -147,7 +150,11 @@ static void test_sector_write(uint8_t *wbuf, uint8_t *rbuf, uint32_t num_sectors
 	rc = write_sector_checked(wbuf, rbuf, 0, num_sectors);
 	zassert_equal(rc, 0, "Failed to write to sector zero");
 	/* Write to a sector in the "middle" of the disk */
-	sector = MAX(((disk_sector_count / 2) - num_sectors), 0);
+	if ( disk_sector_count / 2 > num_sectors )
+                sector = disk_sector_count / 2 - num_sectors;
+        else
+                sector = 0;
```
Comment (gmarull) [inline tests/drivers/disk/disk_access/src/main.c:156]: all if/elses need `{}`, also please don't mix tabs and spaces...

**Review by gmarull — DISMISSED** [review]

File: tests/drivers/disk/disk_access/src/main.c (hunk 1 above)
Comment (hunterhu3000) [reply tests/drivers/disk/disk_access/src/main.c:158]: Yes, CI found that problem.
I have updated the format. 
Thanks

**Comment by hunterhu3000** [comment]
All CI checks are passed, thanks to review.

**Review by danieldegrasse — APPROVED** [review]

**Review by nashif — APPROVED** [review]
