### PR TITLE
arch/xtensa: Fix nested interrupt entry

### LINKED ISSUE #57009: xtensa: nested interrupts not be working correctly
I am observing weird exceptions during windows underflow/overflow and sometimes weird memory access (e.g. 0xffff0000). This all goes away when I mask all interrupt in `EXCINT_HANDLER`. Upon closer inspection into the interrupt handling code, it seems like the stashed registers may be overwritten from earlier interrupts:

1. First level 1 interrupt comes it. The IRQ BSA is stored in the thread stack and inside `EXCINT_HANDLER`, `CROSS_STACK_CALL` would change the stack pointer to the interrupt stack.
2. During handling of the first level 1 interrupt, a higher priority interrupt can fired and we will handle the second interrupt. This is due to `PS.EXCM` being cleared and `PS.INTLEVEL` being set to 1 at https://github.com/zephyrproject-rtos/zephyr/blob/a1d21ca69bf471b06ebaad6ce2ec74a9b32724ef/arch/xtensa/include/xtensa-asm2-s.h#L321-L339
3. The code goes on to `CROSS_STACK_CALL` to switch stack from the thread stack to the interrupt stack. At https://github.com/zephyrproject-rtos/zephyr/blob/a1d21ca69bf471b06ebaad6ce2ec74a9b32724ef/arch/xtensa/include/xtensa-asm2-s.h#L255-L258, the stack pointer is moved back to the beginning of first IRQ BSA.
4. If a higher priority interrupt comes in at the same time, the new IRQ BSA is being created, overwriting the first IRQ BSA created in step 1. This is due to stack pointer being moved back to the before the first IRQ BSA.
5. When we finish processing the second interrupt, it goes back to continue handling the first interrupt but with the wrong context.

Note that the issue happens when there are quite a bit of level 1 interrupts being serviced, interleaving with level 2 interrupts.

@andyross Any thoughts?

### PR DESCRIPTION
**Pull request by andyross**
The "cross stack call" mechanism has intermediate states where the stack frames are not valid for our own interrupt entry code, which causes corruption if an interrupt races at exactly the right time. Leave interrupts masked until just before the call.

The fix is midly complicated by the fact that we RELY on nested window exception frames to spill registers from the interruptee, so have to do the masking with PS.INTLEVEL, which requires a register to save its contents, which we don't have since everything needs to happen in one 4-register window.  But thankfully our Zephyr-reserved EPS register is guaranteed to be available through this process.

Fixes #57009

### CODE REVIEW

**Comment by andyross** [comment]
Proposed fix for #57009 

This is working for me in the "seems correct by construction and appears not to break anything" sense.  But what I don't have yet is a stress rig to do lots of nested calls with arbitrary timing to validate that it actually fixes the bug.  Please test.

File: arch/xtensa/include/xtensa-asm2-s.h [hunk 1]
```diff
@@ -330,13 +337,19 @@ _xstack_returned_\@:
...
+	 * resulting frames are invalid/non-reentrant, so we can't
+	 * allow nested interrupts.  But we do need EXCM unmasked, as
+	 * we use CALL/ENTRY instructions in the process and need to
+	 * handle exceptions to spill caller/interruptee frames.  Use
+	 * PS.INTLEVEL at maximum to mask all interrupts and stash the
+	 * current value in our designated EPS register (which is
+	 * guaranteed unused across the call)
 	 */
-	rsr.PS a0
+	rsil a0, 0xf
```
Comment (ceolin) [inline arch/xtensa/include/xtensa-asm2-s.h:349]: `XCHAL_NMILEVEL` ?

**Review by ceolin — APPROVED** [review]

File: arch/xtensa/include/xtensa-asm2-s.h (hunk 1 above)
Comment (andyross) [reply arch/xtensa/include/xtensa-asm2-s.h:349]: In theory it shouldn't matter.  In practice NMILEVEL is set in a core-isa.h header and could be wrong if we mess up the toolchain setup.

FWIW, by my read the ISA spec is pretty clear that INTLEVEL can have any value from 0 to 15.  It's the inbound interrupts that might be implemented only at certain levels.

**Review by dcpleung — APPROVED** [review]
