### PR TITLE
drivers: sensor: tdk: icm42688: fix wrap-around

### LINKED ISSUE #84673: ICM42688: wrap-around on negative values
**Potential wrap-around on micro value**

In the ICM42688 driver, file `zephyr/drivers/sensor/tdk/icm42688/icm42688.h`

When converting raw values from a register to a specific unit (acceleration, rotation rate, temperature), a wrap around will occur for negative values if the prototype of the function is fully respected.

Affects the ICM42688 IMU driver. The functions involved are:

```C
void icm42688_accel_g(struct icm42688_cfg *cfg, int32_t in, int32_t *out_g, uint32_t *out_ug);
void icm42688_gyro_dps(const struct icm42688_cfg *cfg, int32_t in, int32_t *out_dps, uint32_t *out_udps);
void icm42688_temp_c(int32_t in, int32_t *out_c, uint32_t *out_uc);
```

**To Reproduce**

The functions involved are not directly used, or are used by passing a signed integer to the micro value instead of an unsigned integer as advertised by the prototype. As a result the bug is not directly visible, unless one directly calls the conversion functions.

The following code reproduces the error. Note that `icm42688_temp_c()` is directly copied from the file `icm42688.h` in order to make a standalone example:

```C
#include <stdio.h>
#include <stdint.h>

/**
 * @brief Convert icm42688 temp value to useful celsius values
 *
 * @param cfg icm42688_cfg current device configuration
 * @param in raw data value in int32_t format
 * @param out_c whole celsius output in int32_t
 * @param out_uc micro (1/1000000) celsius as uint32_t
 */
static inline void icm42688_temp_c(int32_t in, int32_t *out_c, uint32_t *out_uc)
{
	int64_t sensitivity = 13248; /* value equivalent for x100 1c */

	/* Offset by 25 degrees Celsius */
	int64_t in100 = (in * 100) + (25 * sensitivity);

	/* Whole celsius */
	*out_c = in100 / sensitivity;

	/* Micro celsius */
	*out_uc = ((in100 - (*out_c) * sensitivity) * INT64_C(1000000)) / sensitivity;
}

void test_raw_to_celsius(int32_t raw, const char *label)
{
	int32_t out_c;   // whole celsius [C]
	uint32_t out_uc; // micro celsius [uC]
	icm42688_temp_c(raw, &out_c, &out_uc);
	float temperature = (float)out_c + (float)out_uc * 1e-6f;

	printf("%-16s    raw: %d  whole: %+2d  micro: %10u  temperature: %+9.3f [C]\n", label, raw,
	       out_c, out_uc, temperature);
}

int main(int argc, char **argv)
{
	int32_t zero_degC_raw = -3312; // (0 [C] - 25 [C]) * 132.48

	// zero degree Celsius
	test_raw_to_celsius(zero_degC_raw, "zero deg C:");

	// Slightly above zero Celsius: 1/132.48 = 0.007548 [C]
	test_raw_to_celsius(zero_degC_raw + 1, "zero+ deg C:");

	// Slightly below zero Celsius: -1/132.48 = -0.007548 [C]
	test_raw_to_celsius(zero_degC_raw - 1, "zero- deg C:");

	return 0;
}
```

Compiling and executing gives the following result, where the negative temperature is clearly wrong:
```
zero deg C:         raw: -3312  whole: +0  micro:          0  temperature:    +0.000 [C]
zero+ deg C:        raw: -3311  whole: +0  micro:       7548  temperature:    +0.008 [C]
zero- deg C:        raw: -3313  whole: +0  micro: 4294959748  temperature: +4294.960 [C]
```

Declaring `out_uc` as a signed value fixes the conversion:
```
zero deg C:         raw: -3312  whole: +0  micro:          0  temperature:    +0.000 [C]
zero+ deg C:        raw: -3311  whole: +0  micro:       7548  temperature:    +0.008 [C]
zero- deg C:        raw: -3313  whole: +0  micro:      -7548  temperature:    -0.008 [C]
```

**Expected behavior**

Negative values should be reported properly, especially after converting to floating point.

**Impact**

Invalid values read from sensor if the prototype of the function is respected. Can be avoided by passing signed integers, or re-interpreting the unsigned micro value as a signed micro value.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: native or Zephyr SDK 0.16.8
 - Commit SHA: 4455cd7351ba2990aa6cb44bc09803b154d4a3f5

### PR DESCRIPTION
**Pull request by ctourner**
On the driver for the TDK InvenSense ICM-42688 IMU.

When converting raw values to integer and fractional (micro) parts, the fractional part must be a signed integer.

- Fix prototypes where the fractional part was declared as unsigned.
- Fix comments which did not match the declared type.

The values affected are:
- acceleration converted to [g]
- rotation rate converted to [deg/s]
- temperature converted to [Celsius]

Fixes: #84673

### CODE REVIEW

File: drivers/sensor/tdk/icm42688/icm42688.h [hunk 1]
```diff
@@ -412,10 +412,10 @@ int icm42688_read_all(const struct device *dev, uint8_t data[14]);
  * @param cfg icm42688_cfg current device configuration
  * @param in raw data value in int32_t format
  * @param out_g whole G's output in int32_t
- * @param out_ug micro (1/1000000) of a G output as uint32_t
+ * @param out_ug micro (1/1000000) of a G output as int32_t
  */
 static inline void icm42688_accel_g(struct icm42688_cfg *cfg, int32_t in, int32_t *out_g,
-				    uint32_t *out_ug)
+				    int32_t *out_ug)
```
Comment (yperess) [inline drivers/sensor/tdk/icm42688/icm42688.h:418]: This function doesn't appear to be used anywhere, @teburd added it. I'd like to wait for his take but I would just remove it since this isn't a public header anyway and there are no Zephyr tree uses of this function.

File: drivers/sensor/tdk/icm42688/icm42688.h [hunk 2]
```diff
@@ -449,10 +449,10 @@ static inline void icm42688_accel_g(struct icm42688_cfg *cfg, int32_t in, int32_
  * @param cfg icm42688_cfg current device configuration
  * @param in raw data value in int32_t format
  * @param out_dps whole deg/s output in int32_t
- * @param out_udps micro (1/1000000) deg/s as uint32_t
+ * @param out_udps micro (1/1000000) deg/s as int32_t
  */
 static inline void icm42688_gyro_dps(const struct icm42688_cfg *cfg, int32_t in, int32_t *out_dps,
-				     uint32_t *out_udps)
+				     int32_t *out_udps)
```
Comment (yperess) [inline drivers/sensor/tdk/icm42688/icm42688.h:455]: Same here, function isn't used. Will wait for @teburd to weigh in.

**Review by yperess — CHANGES_REQUESTED** [review]

File: drivers/sensor/tdk/icm42688/icm42688.h (hunk 2 above)
Comment (ctourner) [reply drivers/sensor/tdk/icm42688/icm42688.h:455]: Same here.

**Comment by yperess** [comment]
@ctourner I'm OK with merging and removing dead code later, please file a bug so we keep track of the dead code and reference this PR. Once that's done I'm happy to approve this change.

**Review by MaureenHelm — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Review by yperess — APPROVED** [review]

File: drivers/sensor/tdk/icm42688/icm42688.h (hunk 1 above)
Comment (yperess) [reply drivers/sensor/tdk/icm42688/icm42688.h:418]: Ack
