### PR TITLE
tcp2: Implement a blocking connect

### LINKED ISSUE #26695: net: TCP2: connect() returns 0 without waiting for handshake completion
**Describe the bug**
When using `CONFIG_NET_TCP2=y`:
A call to BSD `connect()` or `zsock_connect()` returns 0 immediately after sending SYN, without waiting for TCP handshake completion. Specifically it does not wait for [SYN,ACK] reply from server.
That leads to client assuming connection is established. Immediately sending data after `connect()`, results with an error -128 (ENOTCONN).

**To Reproduce**
The bug can be reproduced on MQTT sample at path: samples/net/mqtt_publisher.
The sample uses `mqtt_connect()`, which calls `connect()`  followed immediately by writing to the socket (`send()`).
This works with `CONFIG_NET_TCP1=y`, but fails with `CONFIG_NET_TCP2=y`.

The bug was reproduced on the following boards:
- stm32f746g_disco (using the on board ethernet)
- nucleo_l432kc (using SLIP over usart1)

**Expected behavior**
`connect()` should return with 0 only after completing the TCP handshake, i.e. receiving [SYN,ACK].

**Impact**
This is a showstopper. You should be able to send immediately after `connect()` returns successfully.

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 18.04
 - Toolchain: Zephyr SDK

### PR DESCRIPTION
**Pull request by ozhuraki**
In order to implement a blocking connect, add a semaphore
and block on it in net_tcp_connect().

The semaphore is released when ESTABLISHED state is reached.

In case tcp_conn_unref() is called while waiting on the semaphore,
defer the unreference, tcp_conn_unref() will be called from
net_tcp_connect().

Fixes #26695

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
This certainly works for current stack. But it won't work if we get the user mode networking done because there we would need to separate the userspace application by IPC from core stack. Of course we are not yet there, just pondering should make the code so that it would be easier to split the stuff.

Edit: lets go with this solution and figure out what needs to be done with usermode networking later. The plans are still so vague that it is difficult to know what direction to take. Can you fix the compile warning so that sanity is happy.

File: subsys/net/ip/tcp2.c [hunk 1]
```diff
@@ -1129,20 +1129,19 @@ static void tcp_in(struct tcp *conn, struct net_pkt *pkt)
...
 		 */
-		if (FL(&fl, &, ACK, th && th_ack(th) == conn->seq)) {
+		if (FL(&fl, &, SYN | ACK, th && th_ack(th) == conn->seq)) {
 			tcp_send_timer_cancel(conn);
-			next = TCP_ESTABLISHED;
-			net_context_set_state(conn->context,
-					      NET_CONTEXT_CONNECTED);
-			if (FL(&fl, &, PSH)) {
+			conn_ack(conn, th_seq(th) + 1);
+			if (len) {
```
Comment (tbursztyka) [inline subsys/net/ip/tcp2.c:1147]: have an empty line before the if (since previous line it not doing anything with len)

File: subsys/net/ip/tcp2.c [hunk 2]
```diff
@@ -1458,6 +1469,17 @@ int net_tcp_connect(struct net_context *context,
 	 */
 	tcp_in(conn, NULL);
 
+#if !defined(CONFIG_NET_TEST_PROTOCOL)
+	conn->in_connect = true;
+	if (k_sem_take(&conn->connect_sem, timeout) != 0 &&
```
Comment (tbursztyka) [inline subsys/net/ip/tcp2.c:1474]: empty line before if

File: subsys/net/ip/tcp2.c [hunk 3]
```diff
@@ -280,11 +280,20 @@ static void tcp_send_queue_flush(struct tcp *conn)
 
 static int tcp_conn_unref(struct tcp *conn)
 {
-	int ref_count = atomic_dec(&conn->ref_count) - 1;
-	int key;
+	int key, ref_count = atomic_get(&conn->ref_count);
 
 	NET_DBG("conn: %p, ref_count=%d", conn, ref_count);
 
+#if !defined(CONFIG_NET_TEST_PROTOCOL)
```
Comment (sjg20) [inline subsys/net/ip/tcp2.c:287]: if() instead of #if ?

File: subsys/net/ip/tcp2_priv.h [hunk 4]
```diff
@@ -201,6 +201,8 @@ struct tcp { /* TCP connection */
 	size_t send_retries;
 	struct k_delayed_work timewait_timer;
 	struct net_if *iface;
+	struct k_sem connect_sem;
```
Comment (sjg20) [inline subsys/net/ip/tcp2_priv.h:204]: comments?

**Review by sjg20 — APPROVED** [review]

**Comment by mniestroj** [comment]
Why don't we use `cb` parameter of `net_tcp_connect()` (both in TCP and TCP2) to notify about established connection? What we are really missing in #26695 is that posix `connect()` should block by default, not necessarily `net_tcp_connect()`. Such behavior could be implemented by waiting on semaphore in `zsock_connect_ctx()`.

In Linux userspace there is also a possibility to change socket file descriptor to non-blocking mode. Then you can call `connect()`, which won't block. `poll()` can be used on such file descriptor to get notification about connection being established. This gives userspace a mechanism for timeout, as file descriptor can be closed when userspace decides it takes too long to connect. If at some point we would like such mechanism in Zephyr, then it would be much easier to put all the logic in the `zsock_connect_ctx()` and decide whether to use semaphore (blocking mode) or signal `poll()` in `cb` implementation passed to `net_context_connect()`.

**Comment by johngrey-dev** [comment]
This will be the better solution, but for now the module is unusable. 
Temporarily solving it as currently suggested will be extremely helpful.

Thank you!

> Why don't we use `cb` parameter of `net_tcp_connect()` (both in TCP and TCP2) to notify about established connection? What we are really missing in #26695 is that posix `connect()` should block by default, not necessarily `net_tcp_connect()`. Such behavior could be implemented by waiting on semaphore in `zsock_connect_ctx()`.
> 
> In Linux userspace there is also a possibility to change socket file descriptor to non-blocking mode. Then you can call `connect()`, which won't block. `poll()` can be used on such file descriptor to get notification about connection being established. This gives userspace a mechanism for timeout, as file descriptor can be closed when userspace decides it takes too long to connect. If at some point we would like such mechanism in Zephyr, then it would be much easier to put all the logic in the `zsock_connect_ctx()` and decide whether to use semaphore (blocking mode) or signal `poll()` in `cb` implementation passed to `net_context_connect()`.

**Comment by jukkar** [comment]
> Why don't we use `cb` parameter of `net_tcp_connect()` (both in TCP and TCP2) to notify about established connection? What we are really missing in #26695 is that posix `connect()` should block by default, not necessarily `net_tcp_connect()`. Such behavior could be implemented by waiting on semaphore in `zsock_connect_ctx()`.

Indeed, that sounds actually a better solution. I think we need to revisit this fix anyway if I manage to figure out how to implement the user mode networking support. As we are understaffed atm and this fix works, I am merging this as is. Patches are welcome to implement this differently.

**Review by jukkar — APPROVED** [review]
