### PR TITLE
stm32: sdmmc: Add IT mode and HW flow control

### LINKED ISSUE #39136: SD disk access runs into TXUNDERRUN and RXOVERRUN of SDMMC driver
When using the SD disk access on a STM32H735 under load, the driver faults due to TXUNDERRUN (in case of writing to the SD card) and RXOVERRUN (in case of reading from the SD card) errors.

**To Reproduce**
1. Activate ethernet
2. Start downloading stuff and write it immediately to the SD card

**Expected behavior**
The data should be written without any issues to the SD card.

**Impact**
It basically makes the disk access unusable in case there is any other load on the chip. The basic cause is in the HAL itself, which uses a polling mode to get the data out:
https://github.com/zephyrproject-rtos/hal_stm32/blob/5c8275071ec1cf160bfe8c18bbd9330a7d714dc8/stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_sd.c#L923

**Environment (please complete the following information):**
 - STM32H735G Discovery Kit
 - Zephyr Version fcb73bd4f68b0cf545591bf80328f79a4ea399bf

**Additional context**
I found a workaround for this issue. In the chip there is a hardware flow control unit available, which is disabled by default. Setting Bit 17 of SDMMC_CLKCR (HWFC_EN) activates this and then the issue is gone. Of course this is still not really a nice solution, as an active polling is pretty bad for the overall system performance. I suppose the proper solution would be to use DMA for read and write operations to the SD card.

### PR DESCRIPTION
**Pull request by erwango**
Fixes #39136

Convert existing SDMMC polling mode to IT driver r/w procedures.
Additionally, add a Kconfig option to enable HWFC feature.

### CODE REVIEW

**Review by jfischer-no — APPROVED** [review]

File: drivers/disk/sdmmc_stm32.c [hunk 1]
```diff
@@ -135,19 +177,32 @@ static int stm32_sdmmc_access_read(struct disk_info *disk, uint8_t *data_buf,
 {
 	const struct device *dev = disk->dev;
 	struct stm32_sdmmc_priv *priv = dev->data;
-	int err;
+	int err = 0;
```
Comment (FRASTM) [inline drivers/disk/sdmmc_stm32.c:180]: no need to set to 0,  the 'err' is the return code of the HAL_SD_ReadBlocks_IT

File: drivers/disk/sdmmc_stm32.c [hunk 2]
```diff
@@ -156,18 +211,32 @@ static int stm32_sdmmc_access_write(struct disk_info *disk,
...
```
Comment (FRASTM) [inline drivers/disk/sdmmc_stm32.c:214]: no need to set to 0, the 'err' is the return code of the HAL_SD_WriteBlocks_IT

**Review by FRASTM — APPROVED** [review]
`int err = 0;` to confirm, else LGTM
