### PR TITLE
tests: arch: arm: arm_interrupt: remove side effect in assertion

### LINKED ISSUE #23582: [Coverity CID :208918] Side effect in assertion in tests/arch/arm/arm_interrupt/src/arm_interrupt.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/arch/arm/arm_interrupt/src/arm_interrupt.c#L104

Category: Incorrect expression
Function: `test_arm_interrupt`
Component: Tests
CID: [208918](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=208918)

Details:

```
98         __DSB();
99         __ISB();
100    
101         /* Verify that the spurious ISR has led to the fault and the
102          * expected reason variable is reset.
103          */
>>>     CID 208918:  Incorrect expression  (ASSERT_SIDE_EFFECT)
>>>     Argument "expected_reason" of z_zassert() has a side effect because the variable is volatile.  The containing function might work differently in a non-debug build.
104         zassert_true(expected_reason == -1,
105             "expected_reason has not been reset\n");
106         NVIC_DisableIRQ(i);
107    
108         arch_irq_connect_dynamic(i, 0 /* highest priority */,
109             arm_isr_handler,
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by ioannisg**
Remove a side effect in an assertion check of the
expected reason after spurious interrupt handling.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

Fixes #23582

### CODE REVIEW

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c [hunk 1]
```diff
@@ -101,7 +101,8 @@ void test_arm_interrupt(void)
 	/* Verify that the spurious ISR has led to the fault and the
 	 * expected reason variable is reset.
 	 */
-	zassert_true(expected_reason == -1,
+	reason = expected_reason;
+	zassert_true(reason == -1,
```
Comment (stephanosio) [inline tests/arch/arm/arm_interrupt/src/arm_interrupt.c]: Maybe `zassert_equal(reason, -1, ...)` could be a better choice?

Comment (ioannisg) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c]: Let's change it to that then :)
Done

**Review by stephanosio — APPROVED** [review]
LGTM

**Review by nashif — APPROVED** [review]

**Comment by andrewboie** [comment]
I suggest just marking the Coverity as a false-positive; it thinks zassert_* functions are conditionally compiled because they have "assert" in their name when they actually aren't.

We'll continue to get Coverity failures over and over like this until these APIs are renamed
