### PR TITLE
Bluetooth: Mesh: Fix OOB upload in Fw Distribution server

### LINKED ISSUE #63798: Bluetooth: Mesh: Fw Distribution Server issues with OOB upload
**Describe the bug**
There are few issues with OOB upload in Fw Distribution Server that were caught by PTS:
1. Fw Distribution Server is unable to receive Upload OOB Start message due to incorrect check of the message length: https://github.com/zephyrproject-rtos/zephyr/blob/47822586e41a76d834e4432c2bcc75ab17fcfaca/subsys/bluetooth/mesh/dfd_srv.c#L746 It uses `BT_MESH_LEN_EXACT` while should have been `BT_MESH_LEN_MIN`.
2. When receiving Upload OOB Start message after failed upload started by Upload Start message, the Fw Distribution server doesn't release the already reserved slot which make the server to fail processing the message once it runs out of available slots.
3. If another Upload OOB Start message is received before the Check Firmware OOB procedure is completed (`bt_mesh_dfd_srv_oob_check_complete()` wasn't called yet), the Fw Distribution server will process this message again which will result in an invalid state in server.
4. When the Check Firmware OOB procedure is completed (a user called `bt_mesh_dfd_srv_oob_check_complete()`) and the firmware was already received, the server will call `oob_progress_get` callback to get the progress from a user application. But the user application doesn't know yet that the firmware is already received. This will happen after `bt_mesh_dfd_srv_oob_check_complete()` returns status. Thus, the server returns wrong progress when sends status to the Fw Distribution client.

**To Reproduce**
Affected tests:
- DFU/SR/FD/BV-06-C
- DFU/SR/FD/BV-13-C
- DFU/SR/FD/BV-14-C
- DFU/SR/FD/BV-15-C
- DFU/SR/FD/BV-16-C
- DFU/SR/FD/BV-17-C
- DFU/SR/FD/BV-18-C
- DFU/SR/FD/BV-22-C

**Impact**
Qualification of Mesh DFU v1.0.0.

### PR DESCRIPTION
**Pull request by PavelVPV**
The PR fixes bugs related to OOB upload.

This PR also adds support for the following PTS test:
- DFU/SR/FD/BV-06-C
- DFU/SR/FD/BV-13-C
- DFU/SR/FD/BV-14-C
- DFU/SR/FD/BV-15-C
- DFU/SR/FD/BV-16-C
- DFU/SR/FD/BV-17-C
- DFU/SR/FD/BV-18-C
- DFU/SR/FD/BV-22-C

Fixes #63798

### CODE REVIEW

File: tests/bluetooth/tester/src/btp_mesh.c [hunk 1]
```diff
@@ -21,7 +21,7 @@
 
 #include <zephyr/logging/log.h>
 #define LOG_MODULE_NAME bttester_mesh
-LOG_MODULE_REGISTER(LOG_MODULE_NAME, CONFIG_BTTESTER_LOG_LEVEL);
+LOG_MODULE_REGISTER(LOG_MODULE_NAME, 4);//CONFIG_BTTESTER_LOG_LEVEL);
```
Comment (Balaklaka) [inline tests/bluetooth/tester/src/btp_mesh.c:24]: Should this be reverted back.

File: tests/bluetooth/tester/src/btp_mesh.c [hunk 2]
```diff
@@ -162,13 +162,118 @@ static int dfd_srv_send(struct bt_mesh_dfd_srv *srv,
...
+					const struct bt_mesh_dfu_slot *slot)
+{
+	uint8_t progress;
+
+	if (dfd_srv_oob_ctx.started) {
+		progress = dfd_srv_oob_ctx.progress;
+
+		dfd_srv_oob_ctx.progress = MIN(dfd_srv_oob_ctx.progress + 25, 99);
+
+		if (dfd_srv_oob_ctx.progress == 99) {
```
Comment (Balaklaka) [inline tests/bluetooth/tester/src/btp_mesh.c:219]: Should this be >= or <=, or is it correct with exact 99. dfd_srv_oob_ctx.progress can be less than 99.

File: subsys/bluetooth/mesh/dfd_srv.c [hunk 3]
```diff
@@ -761,7 +761,7 @@ const struct bt_mesh_model_op _bt_mesh_dfd_srv_op[] = {
 	{ BT_MESH_DFD_OP_APPLY, BT_MESH_LEN_EXACT(0), handle_apply },
 	{ BT_MESH_DFD_OP_UPLOAD_GET, BT_MESH_LEN_EXACT(0), handle_upload_get },
 	{ BT_MESH_DFD_OP_UPLOAD_START, BT_MESH_LEN_MIN(16), handle_upload_start },
-	{ BT_MESH_DFD_OP_UPLOAD_START_OOB, BT_MESH_LEN_EXACT(2), handle_upload_start_oob },
+	{ BT_MESH_DFD_OP_UPLOAD_START_OOB, BT_MESH_LEN_MIN(2), handle_upload_start_oob },
```
Comment (alxelax) [inline subsys/bluetooth/mesh/dfd_srv.c:780]: I guess commit message mistyping. It should be `This message _at least_ 2 bytes long, but can be longer, thus
BT_MESH_LEN_EXACT shouldn't be used.` or `This message _at least_ 2 bytes long, but can be longer, thus
BT_MESH_LEN_MIN should be used.`

File: tests/bluetooth/tester/src/btp_mesh.c [hunk 4]
```diff
@@ -162,13 +162,118 @@ static int dfd_srv_send(struct bt_mesh_dfd_srv *srv,
...
+
+	return BT_MESH_DFD_SUCCESS;
+}
+
+static void dfd_srv_cancel_oob_upload(struct bt_mesh_dfd_srv *srv,
+				      const struct bt_mesh_dfu_slot *slot)
+{
+	LOG_DBG("Cancel OOB Upload");
+
+	dfd_srv_oob_ctx.started = false;
```
Comment (alxelax) [inline tests/bluetooth/tester/src/btp_mesh.c:206]: Shouldn't it cancel submitted work\works?

File: tests/bluetooth/tester/src/btp_mesh.c (hunk 2 above)
Comment (alxelax) [reply tests/bluetooth/tester/src/btp_mesh.c:219]: ASFAIK The image is ready for storing if progress is exactly 99. After storing it will be 100.

File: tests/bluetooth/tester/src/btp_mesh.c [hunk 5]
```diff
@@ -162,13 +162,118 @@ static int dfd_srv_send(struct bt_mesh_dfd_srv *srv,
...
+	.start_oob_upload = dfd_srv_start_oob_upload,
+	.cancel_oob_upload = dfd_srv_cancel_oob_upload,
+	.oob_progress_get = dfd_srv_oob_progress_get,
+#endif
 };
 
 static struct bt_mesh_dfd_srv dfd_srv = BT_MESH_DFD_SRV_INIT(&dfd_srv_cb);
+
+#ifdef CONFIG_BT_MESH_DFD_SRV_OOB_UPLOAD
+#define SUPPORTED_SCHEME "http"
```
Comment (alxelax) [inline tests/bluetooth/tester/src/btp_mesh.c:245]: Shouldn't it be `https`?
http commands are used but seems URI has https scheme (at least in 3.2.1 Construction of the Request URI)

**Review by alxelax — CHANGES_REQUESTED** [review]
Seems Ok but requires a bit more changes.

File: tests/bluetooth/tester/src/btp_mesh.c (hunk 4 above)
Comment (PavelVPV) [reply tests/bluetooth/tester/src/btp_mesh.c:206]: This situation will unlikely happen. They are not scheduled with delay.

File: tests/bluetooth/tester/src/btp_mesh.c (hunk 5 above)
Comment (PavelVPV) [reply tests/bluetooth/tester/src/btp_mesh.c:245]: Then we need to support Firmware Check Over HTTPS and Firmware Retrieval over HTTPS procedures according to sections 6.2.2.2 and 6.2.2.3. But we don't support them.

**Review by alxelax — DISMISSED** [review]

**Review by alxelax — DISMISSED** [review]

**Comment by jhedberg** [comment]
@PavelVPV is this something you think should be merged for 3.5? If so, please set the target milestone appropriately.

**Review by Balaklaka — APPROVED** [review]

File: tests/bluetooth/tester/src/btp_mesh.c [hunk 6]
```diff
@@ -162,13 +162,119 @@ static int dfd_srv_send(struct bt_mesh_dfd_srv *srv,
...
+{
+	int status;
+	int err;
+
+	if (dfd_srv_oob_ctx.uri_len < 4 || memcmp(dfd_srv_oob_ctx.uri, SUPPORTED_SCHEME,
+						  strlen(SUPPORTED_SCHEME))) {
+		status = BT_MESH_DFD_ERR_URI_NOT_SUPPORTED;
+	} else if (dfd_srv_oob_ctx.uri_len < 7 || memcmp(dfd_srv_oob_ctx.uri,
+							 SUPPORTED_SCHEME "://",
+							 strlen(SUPPORTED_SCHEME) + 3)) {
```
Comment (ludvigsj) [inline tests/bluetooth/tester/src/btp_mesh.c:258]: If this passes PTS then I guess it's fine, but I think returning SUCCESS for e.g. "https://?:?" (which this does as far as I can tell) is wrong, and can fail if PTS changes. At the very least, make a comment here about this so that if this fails in the future when PTS becomes more diligent then we easily can find where to fix it?

Comment (PavelVPV) [reply tests/bluetooth/tester/src/btp_mesh.c]: Fixed

**Comment by jhedberg** [comment]
> > @PavelVPV is this something you think should be merged for 3.5? If so, please set the target milestone appropriately.
> 
> Added milestone (hope it is not too late).

Is this fixing any bugs? I don't see any "Fixes: ..." entry.

**Review by ludvigsj — APPROVED** [review]

**Comment by PavelVPV** [comment]
> > > @PavelVPV is this something you think should be merged for 3.5? If so, please set the target milestone appropriately.
> > 
> > 
> > Added milestone (hope it is not too late).
> 
> Is this fixing any bugs? I don't see any "Fixes: ..." entry.

Sorry, added now.

**Review by jhedberg — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
