### PR TITLE
usb: console: Notify user about incorrect configuration

### LINKED ISSUE #10693: samples/subsys/usb/console: Console routed to UART of no USB
When testing samples/subsys/usb/console, "Hello World" is routed to UART console if USB console is not there.
I don't know if this is intended behavior, but this could be confusing when testing.

### PR DESCRIPTION
**Pull request by finikorg**
Since setting USB console port name is moved to DTS users have
problems enabling it. Notify user that the console is not set.

Fixes #10693

Signed-off-by: Andrei Emeltchenko <andrei.emeltchenko@intel.com>

### CODE REVIEW

File: samples/subsys/usb/console/src/main.c [hunk 1]
```diff
@@ -6,9 +6,19 @@
...
+#include <misc/util.h>
+#include <string.h>
 
 void main(void)
 {
+	if (strncmp(CONFIG_UART_CONSOLE_ON_DEV_NAME, CONFIG_CDC_ACM_PORT_NAME,
+		    min(strlen(CONFIG_UART_CONSOLE_ON_DEV_NAME),
+			strlen(CONFIG_CDC_ACM_PORT_NAME)))) {
+		printk("Error: Console device name is not USB ACM\n");
+
```
Comment (aurel32) [inline samples/subsys/usb/console/src/main.c]: I guess you want to first check that both lengths are equal, and then compare the strings, otherwise `foobar0` and `foobar` will match.

In addition to that, both `CONFIG_UART_CONSOLE_ON_DEV_NAME` and `CONFIG_CDC_ACM_PORT_NAME` are fixed values, so Coverity will report a `Pointless string comparison` issue. I don't have a solution for that.

Comment (finikorg) [reply samples/subsys/usb/console/src/main.c]: Added length comparison also.

**Review by aurel32 — APPROVED** [review]
Looks all good, thanks for the quick update.

**Review by nashif — APPROVED** [review]
