### PR TITLE
drivers: flash: stm32 octospi supports the 4Bytes address mode

### LINKED ISSUE #76432: flash_stm32_ospi: Command to enter 4-Byte Address Mode is missing, Winbond flash W25Q512 is not working correctly
**Describe the bug**
QSPI Flash Winbond W25Q512 connected to STM32U5 is not working correctly. The Flash test fails and the bytes written are misaligned.

**To Reproduce**
Use a board with STM32 controller that has an octo spi port and connect the Flash in QSPI mode (Only CLK, CS, D0...D3 used of Octo SPI port).

1. Compile the Flash Shell sample: west build -p always -b your_board samples/drivers/flash_shell
2. Flash it to the Board: west flash
3. In the shell find the correct flash device with "device list" command and execute the flash test:
"flash test ospi-nor-flash@70000000 0x2000000 0x4000 1"
4.  Test Fails with "Verification ERROR!"

**Expected behavior**
Flash Test passes, data written is identical to data read.

**Impact**
Showstopper, Flash device not usable

**Logs and console output**
Log Output: 
> *** Booting Zephyr OS build v3.7.0-228-g52672923e445 ***
> uart:~$ 
> flash test ospi-nor-flash@70000000 0x2000000 0x4000 1
> Erase OK.
> Write OK.
> Verification ERROR!
> Erase-Write-Verify test done.
> 
> uart:~$ 
> flash erase ospi-nor-flash@70000000 0x0 0x1000
> Erase success.
> 
> uart:~$ 
> flash write ospi-nor-flash@70000000 0x0 0x00112233 0x44556677 
> Write OK.
> Verification ERROR!
> 
> uart:~$ 
> flash read ospi-nor-flash@70000000 0x0 0x20
> 00000000: 88 88 88 33 22 11 00 77  66 55 44 ff ff ff ff ff |...3"..w fUD.....|
> 00000010: 88 88 88 33 22 11 00 77  66 55 44 ff ff ff ff ff |...3"..w fUD.....|

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain Zephyr SDK
 -  Latest Main Branch, Zephyr 3.7.99

**Solution**
I have traced this down to flash_stm32_ospi.c
It uses 4 Byte Address mode for this flash (which is correct), but misses to send the "Enter 4-Byte Address Mode" Command to the Flash. By default this Flash chip starts in 3 Byte Address mode, which causes the data misalignment.
With this patch the flash is working correctly, but I don't know if this is ok/required for all QSPI flash types:
[0001-Patch-for-4-Byte-Address-activation-on-Winbond-Flash.patch](https://github.com/user-attachments/files/16414472/0001-Patch-for-4-Byte-Address-activation-on-Winbond-Flash.patch)

Log Output with patch above:

> flash test ospi-nor-flash@70000000 0x2000000 0x4000 1
> Erase OK.
> Write OK.
> Verified OK.
> Erase-Write-Verify test done.

### PR DESCRIPTION
**Pull request by FRASTM**
Add the 4Bytes program mode to the stm32_ospi driver to enter 4-Byte Address Mode (SPI_NOR_CMD_4BA) when flash is supporting it. This is given by the JESD216 SFDP table.
Based on the stm32 qspi driver.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/76432

### CODE REVIEW

**Comment by arnebdr** [comment]
I have tested the changes of this pull request (with latest Zephyr Main Branch) and it is effective for our hardware. The winbond flash is working with these changes. Without it the flash test still fails as described above.
It would be great if we could merge this pull request to fix this issue. If I can help in any way please let me know.

**Comment by FRASTM** [comment]
re-opening at this PR is  fixing winbond flash access

File: drivers/flash/flash_stm32_ospi.c [hunk 1]
```diff
@@ -2002,8 +2046,29 @@ static int spi_nor_process_bfp(const struct device *dev,
...
+
+		if (jesd216_bfp_decode_dw16(php, bfp, &dw16) == 0) {
+			/*
+			 * According to JESD216, the bit0 of dw16.enter_4ba
+			 * portion of flash description register 16 indicates
+			 * if it is enough to use 0xB7 instruction without
+			 * write enable to switch to 4 bytes addressing mode.
+			 * If bit 1 is set, a write enable is needed.
+			 */
+			if (dw16.enter_4ba & 0x3) {
```
Comment (de-nordic) [inline drivers/flash/flash_stm32_ospi.c:2064]: Shouldn't here be '& 0x01'? Currently this will also enter on 'enter_4ba == 0x02', which would not confirm that command is supported.

Comment (GeorgeCGV) [reply drivers/flash/flash_stm32_ospi.c:2064]: Current logic is fine.

For `dw16.enter_4ba`:

* If `1` - issue instruction `0xB7` (_write enable `0x06` is not required_)
* If `2` - issues write enable `0x06`, then `0xB7`

File: drivers/flash/flash_stm32_ospi.c [hunk 2]
```diff
@@ -1845,6 +1845,49 @@ static int stm32_ospi_write_status_register(const struct device *dev, uint8_t re
...
+	uint8_t statReg;
+	struct flash_stm32_ospi_data *data = dev->data;
+	OSPI_HandleTypeDef *hospi = &data->hospi;
+	uint8_t nor_mode = OSPI_SPI_MODE;
+	uint8_t nor_rate = OSPI_STR_TRANSFER;
+	OSPI_RegularCmdTypeDef s_command = ospi_prepare_cmd(nor_mode, nor_rate);
+
+	if (write_enable) {
+		if (stm32_ospi_write_enable(data, nor_mode, nor_rate) < 0) {
+			LOG_ERR("program_addr_4b failed to write_enable");
```
Comment (GeorgeCGV) [inline drivers/flash/flash_stm32_ospi.c:1859]: I would suggest removing logs here or replacing them with `LOG_DBG`.
The error is captured upon invocation, and related output is generated.

File: drivers/flash/flash_stm32_ospi.c [hunk 3]
```diff
@@ -1845,6 +1845,49 @@ static int stm32_ospi_write_status_register(const struct device *dev, uint8_t re
...
+	if (nor_mode != OSPI_OPI_MODE) {
+		/* force 1-line InstructionMode for any non-OSPI transfer */
+		s_command.InstructionMode = HAL_OSPI_INSTRUCTION_1_LINE;
+	}
+	s_command.AddressMode = HAL_OSPI_ADDRESS_NONE;
+	s_command.DataMode = HAL_OSPI_DATA_NONE;
+	s_command.DummyCycles = 0U;
+
+	if (HAL_OSPI_Command(hospi, &s_command, HAL_OSPI_TIMEOUT_DEFAULT_VALUE) != HAL_OK) {
+		LOG_ERR("OSPI Address Mode Change cmd failed");
```
Comment (GeorgeCGV) [inline drivers/flash/flash_stm32_ospi.c:1875]: Here as well.

File: drivers/flash/flash_stm32_ospi.c [hunk 4]
```diff
@@ -1845,6 +1845,49 @@ static int stm32_ospi_write_status_register(const struct device *dev, uint8_t re
...
+		return -EIO;
+	}
+
+	/* Check that ADS Bit in Status Reg 3 is now set indicating 4 Byte Address mode */
+	if (stm32_ospi_read_status_register(dev, 3, &statReg)) {
+		LOG_ERR("Status reg read failed");
```
Comment (GeorgeCGV) [inline drivers/flash/flash_stm32_ospi.c:1881]: Ditto.

Comment (FRASTM) [reply drivers/flash/flash_stm32_ospi.c:1881]: changed

File: drivers/flash/flash_stm32_ospi.c (hunk 3 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_ospi.c:1875]: changed

File: drivers/flash/flash_stm32_ospi.c (hunk 2 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_ospi.c:1859]: changed

File: drivers/flash/flash_stm32_ospi.c [hunk 5]
```diff
@@ -2002,8 +2046,29 @@ static int spi_nor_process_bfp(const struct device *dev,
...
+			/*
+			 * According to JESD216, the bit0 of dw16.enter_4ba
+			 * portion of flash description register 16 indicates
+			 * if it is enough to use 0xB7 instruction without
+			 * write enable to switch to 4 bytes addressing mode.
+			 * If bit 1 is set, a write enable is needed.
+			 */
+			if (dw16.enter_4ba & 0x3) {
+				if (stm32_ospi_program_addr_4b(dev, dw16.enter_4ba & 2)) {
+					LOG_ERR("Unable to enter 4B mode.\n");
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/flash/flash_stm32_ospi.c:2066]: removing "\n"

File: drivers/flash/flash_stm32_ospi.c (hunk 1 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_ospi.c:2064]: keeping "dw16.enter_4ba & 0x3"

**Review by GeorgeCGV — APPROVED** [review]

**Review by erwango — APPROVED** [review]

File: drivers/flash/flash_stm32_ospi.c [hunk 6]
```diff
@@ -1845,6 +1845,49 @@ static int stm32_ospi_write_status_register(const struct device *dev, uint8_t re
 	return ospi_write_access(dev, &s_command, regs_p, size);
 }
 
+static int stm32_ospi_program_addr_4b(const struct device *dev, bool write_enable)
+{
+	uint8_t statReg;
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_ospi.c:1850]: prefer snake case `stat_reg`

File: drivers/flash/flash_stm32_ospi.c [hunk 7]
```diff
@@ -1845,6 +1845,49 @@ static int stm32_ospi_write_status_register(const struct device *dev, uint8_t re
...
+	s_command.DataMode = HAL_OSPI_DATA_NONE;
+	s_command.DummyCycles = 0U;
+
+	if (HAL_OSPI_Command(hospi, &s_command, HAL_OSPI_TIMEOUT_DEFAULT_VALUE) != HAL_OK) {
+		LOG_DBG("OSPI Address Mode Change cmd failed");
+		return -EIO;
+	}
+
+	/* Check that ADS Bit in Status Reg 3 is now set indicating 4 Byte Address mode */
+	if (stm32_ospi_read_status_register(dev, 3, &statReg)) {
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_ospi.c:1880]: `< 0` or `!= 0`.

File: drivers/flash/flash_stm32_ospi.c [hunk 8]
```diff
@@ -1845,6 +1845,49 @@ static int stm32_ospi_write_status_register(const struct device *dev, uint8_t re
...
+		LOG_DBG("Status reg read failed");
+		return -EIO;
+	}
+
+	if (statReg & 0x01) {
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_ospi.c:1885]: `stat_reg & 1U != 0U`

File: drivers/flash/flash_stm32_ospi.c (hunk 1 above)
Comment (etienne-lms) [inline drivers/flash/flash_stm32_ospi.c:2064]: `16.enter_4ba & 0x3U != 0U`

File: drivers/flash/flash_stm32_ospi.c [hunk 9]
```diff
@@ -2002,8 +2046,29 @@ static int spi_nor_process_bfp(const struct device *dev,
...
+		if (jesd216_bfp_decode_dw16(php, bfp, &dw16) == 0) {
+			/*
+			 * According to JESD216, the bit0 of dw16.enter_4ba
+			 * portion of flash description register 16 indicates
+			 * if it is enough to use 0xB7 instruction without
+			 * write enable to switch to 4 bytes addressing mode.
+			 * If bit 1 is set, a write enable is needed.
+			 */
+			if (dw16.enter_4ba & 0x3) {
+				if (stm32_ospi_program_addr_4b(dev, dw16.enter_4ba & 2)) {
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_ospi.c:2065]: Test the function return value against either `< 0` or `!= 0`.

The function expects 2nd argument as a boolean. To be somewhat strict with coding style reqs,  prefer `dw16.enter_4ba & 2U != 0U`.

**Review by etienne-lms — COMMENTED** [review]
Some minor comments.
