### PR TITLE
Arch arm fix new thread init

### LINKED ISSUE #13465: tests/lib/mem_alloc/testcase.yaml#libraries.libc.minimal: Bus fault at test_malloc
**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=frdm_k64f -DARCH=arm ..
3. make
4. make run

**Screenshots or console output**
```
******** delaying boot 1000ms (per build configuration) *****
***** Booting Zephyr OS v1.14.0-rc1-248-gd5b2834f58 (delayed boot 1000ms) *****
Running test suite test_c_lib_dynamic_memalloc
===================================================================
starting test - test_malloc
***** BUS FAULT *****
  Precise data bus error
  BFAR Address: 0x20001158
  NXP MPU error, port 3
      Mode: User, Data Address: 0x20001158
      Type: Read, Master: 0, Regions: 0x8800
***** Hardware exception *****
Current thread ID = 0x20000b3c
Faulting instruction address = 0x7ee
Fatal fault in thread 0x20000b3c! Aborting.
```

**Environment (please complete the following information):**
 - OS: fedora29
 - Toolchain: zephyr
 - Commit SHA or Version used: d5b2834f58e11b59c640f00f3f2ca2fb85d3a48c

### PR DESCRIPTION
**Pull request by ioannisg**
Fixes #13465 

In brief, the patch does the following:
- moves the reservation of userspace thread local data into the arm-specific `_new_thread()`
- corrects the value saved, eventually in `stack_info.size`, which was causing MPU errors, as the user local data were falling outside the MPU-programmed thread stack,
- improves the documentation of _ARCH_THREAD_STACK_SIZEOF, to stress that it gives the area available for the thread operation (i.e. excluding the guard).
- misc stuff, e.g. an assert statement when programming the built-in guard in ARMv8-M.

Priority is high, as the priority of the bug reported in #13465.

### CODE REVIEW

File: arch/arm/core/thread.c [hunk 1]
```diff
@@ -56,22 +56,53 @@ void _new_thread(struct k_thread *thread, k_thread_stack_t *stack,
...
+	/* Top of actual stack must be moved below the user local data. */
+	top_of_stack_offset = (u32_t)
+		(pStackMem + stackSize - ((char *)p_local_data));
+
+#endif /* CONFIG_THREAD_USERSPACE_LOCAL_DATA */
+#endif /* CONFIG_USERSPACE */
+
 #if CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT && CONFIG_USERSPACE
-	char *stackEnd = pStackMem + stackSize - MPU_GUARD_ALIGN_AND_SIZE;
+	/* This is required to work-around the case where the thread
```
Comment (ioannisg) [inline arch/arm/core/thread.c]: @andrewboie this work-around is "kept" here, but it is only needed since we do not call k_thread_create() with size argument coming from K_THREAD_STACK_SIZEOF. I believe we need to fix this; enforce all calls to k_thread_create() have the stack parameter taken from K_THREAD_STACK_SIZEOF(x), where x = K_THREAD_STACK_DEFINED(<some size>)

**Review by tyrantlizard77 — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
