### PR TITLE
drivers: can: mcan: add static initializer macros for timing parameters

### LINKED ISSUE #58429: drivers: can: mcan: wrong min/max timing parameters used in all in-tree frontends
**Describe the bug**
The minimum/maximum CAN timing parameters specified by Bosch M_CAN manual does not match those used by the various frontend drivers. Some of the errors are likely typos (they don't correspond the the datasheet for the given MCU either), some are wrong in the MCU datasheet as well.

Some of the asserts within the Bosch M_CAN backend driver regarding timing parameters are wrong as well.

**To Reproduce**
1. Inspect the code of the various Bosch M_CAN driver frontends
2. Compare their minimum/maximum timing parameters to those found in the Bosch M_CAN IP core manual
3. Compare their minimum/maximum timing parameters to those found in the MCU datasheet
4. See errors

**Expected behavior**
Minimum/maximum CAN timing parameters should reflect hardware limitations.

**Impact**
Invalid timing parameters may be calculated and written to the hardware, results unknown.

**Environment (please complete the following information):**
 - OS: Plan 9
 - Toolchain Zephyr SDK
 - Commit SHA: 147d4067e6def349d3c0a420d897db0350f36a5c

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Add static initializers for the Bosch M_CAN minimum/maximum CAN timing parameter values and use these in all frontend drivers.

Fixes: #58429

### CODE REVIEW

**Review by pdgendt — DISMISSED** [review]

File: drivers/can/can_stm32h7.c [hunk 1]
```diff
@@ -168,41 +168,20 @@ static const struct can_driver_api can_stm32h7_driver_api = {
 	/* Timing limits are per the STM32H7 Reference Manual (RM0433 Rev 7),
 	 * section 56.5.7, FDCAN nominal bit timing and prescaler register
 	 * (FDCAN_NBTP).
+	 *
+	 * Beware that the reference manual contain a bug regarding the minimum
```
Comment (martinjaeger) [inline drivers/can/can_stm32h7.c:172]: Nits:
```suggestion
	 * Beware that the reference manual contains a bug regarding the minimum
```

**Review by martinjaeger — DISMISSED** [review]

File: drivers/can/can_stm32h7.c (hunk 1 above)
Comment (henrikbrixandersen) [reply drivers/can/can_stm32h7.c]: Fixed, thanks.

**Review by martinjaeger — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
