### PR TITLE
Bluetooth: SMP: Fix setting key distribution bits for no-bonding

### LINKED ISSUE #54104: Bluetooth: Host: Bonding information distribution in the non-bondable mode
**Describe the bug**
The Zephyr Bluetooth Host (SMP module) seems to violate the Bluetooth specification in the following pairing corner case. With the Bonding Flag (BF) cleared in the Pairing Response, the stack should also set the key distribution flags to zero for the key distribution initiator and the responder. In this case, the specification requires no bonding information distribution (IRK, Identity Address, LTK, etc.).

This requirement is based on the 9.4.2 section, Part C, Vol 3 of the Bluetooth Core specification v5.3:

> 
> 9.4.2 Non-bondable mode
>  
> 9.4.2.1 Description
> A device in the non-bondable mode does not allow a bond to be created with a peer device.
>  
> 9.4.2.2 Conditions
> If a device does not support pairing as defined in the Security Manager section then it is considered to be in non-bondable mode. **If Security Manager pairing is supported, the Host shall set the Bonding_Flags to ‘No Bonding’ as defined in [Vol 3] Part H, Section 3.5.1 and bonding information shall not be exchanged or stored.**

**To Reproduce**
Set the non-bondable mode for the Bluetooth Peripheral device using the following configuration ```CONFIG_BT_BONDABLE=n``` and pair with the Central device (e.g. Android device) that requests bonding in the Pairing Request. Observe in the sniffer trace or HCI logs that bonding information is exchanged between devices.

**Expected behavior**
Bonding information shall not be exchanged in the non-bondable mode.

### PR DESCRIPTION
**Pull request by jhedberg**
9.4.2 section, Part C, Vol 3 of the Bluetooth Core specification v5.3 states the following in the case that the device is in non-bondable mode:

If Security Manager pairing is supported, the Host shall set the Bonding_Flags to ‘No Bonding’ as defined in [Vol 3] Part H, Section 3.5.1 and bonding information shall not be exchanged or stored.

Fixes #54104

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
Note: this is only build tested. I don't have time to runtime test it, so someone needs to do that before this can be merged.

File: subsys/bluetooth/host/smp.c [hunk 1]
```diff
@@ -2860,18 +2860,21 @@ static uint8_t smp_pairing_req(struct bt_smp *smp, struct net_buf *buf)
...
 	if ((rsp->auth_req & BT_SMP_AUTH_BONDING) &&
 	    (req->auth_req & BT_SMP_AUTH_BONDING)) {
 		atomic_set_bit(smp->flags, SMP_FLAG_BOND);
 	} else if (IS_ENABLED(CONFIG_BT_BONDING_REQUIRED)) {
 		/* Reject pairing req if not both intend to bond */
 		LOG_DBG("Bonding required");
 		return BT_SMP_ERR_UNSPECIFIED;
+	} else {
+		rsp->init_key_dist = 0;
+		rsp->resp_key_dist = 0;
```
Comment (Thalley) [inline subsys/bluetooth/host/smp.c:2872]: I'm a little confused about this. 

The spec does state, as you write in the commit message, that 
> bonding information shall not be exchanged or stored

"Bonding information" is then defined as 
> The security and identity information as defined in [Vol 3] Part H, Section 2.4.1 is also known as the bonding information

"Security information" is then defined as 
> security information (LTK, EDIV, and Rand)

But in 5.3, vol 3, Part H, 2.4.4.2 Encryption setup using LTK it also states
> The Central must have the security information (LTK, EDIV, and Rand) distributed by the Peripheral in LE legacy pairing or the LTK generated in LE Secure Connections to setup an encrypted session.

So if bonding is not supported, then we shall not exchange the security information, but the spec also states that the security information shall be exchanged to encrypt the link (as I read it anyhow). Doesn't this (wrongly) imply that if you don't support bonding, you cannot encrypt the link? :s 

Am I missing something?

Comment (sjanc) [reply subsys/bluetooth/host/smp.c:2872]: #AutoPTS autotest run zephyr GAP SM

**Comment by sjanc** [comment]
#AutoPTS autotest run zephyr GAP SM

**Comment by sjanc** [comment]
#AutoPTS run zephyr GAP SM

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/54429#issuecomment-1415980882 after 02:07:56.

**Comment by Thalley** [comment]
> Note: this is only build tested. I don't have time to runtime test it, so someone needs to do that before this can be merged.

We could add a babblesim test with `CONFIG_BT_BONDABLE=n` and verify that encryption still works with the changes in this PR with both legacy and LESC

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Failed tests:
GAP     GAP/BOND/BON/BV-02-C            BTP ERROR - ERRATA Request ID 15828
GAP     GAP/BOND/BON/BV-04-C            BTP ERROR
GAP     GAP/BOND/NBON/BV-02-C           INCONC
GAP     GAP/SEC/SEM/BV-56-C             BTP ERROR
GAP     GAP/SEC/SEM/BV-62-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-63-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-64-C             BTP TIMEOUT - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-65-C             FAIL - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-66-C             INCONC - ERRATA TSE18349
GAP     GAP/SEC/SEM/BV-67-C             FAIL - ERRATA TSE18349
SM      SM/CEN/KDU/BI-02-C              INCONC - ERRATA TSE19199
SM      SM/CEN/KDU/BI-03-C              INCONC - ERRATA TSE19199

File: subsys/bluetooth/host/smp.c (hunk 1 above)
Comment (seko-nordic) [reply subsys/bluetooth/host/smp.c:2872]: One will not be able to re-encrypt the link after re-connection without re-pairing. That is exactly what is no-bonding about. It is still possible to encrypt the link in the end of pairing with STK in case of legacy pairing or LTK for LESC.

**Comment by sjanc** [comment]
#AutoPTS run zephyr GAP/BOND/NBON/BV-02-C GAP/SEC/SEM/BV-56-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/zephyrproject-rtos/zephyr/pull/54429#issuecomment-1418704489 after 09:40:38.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Failed tests:
GAP     GAP/BOND/NBON/BV-02-C           INCONC

**Comment by sjanc** [comment]
this seems to trigger issue on autopts (should be fixed by https://github.com/intel/auto-pts/pull/855) 
and from what I can  tell, previously this test was passing by mistake (PTS isn't verifying bond flag i pair req)

I'll rerun check after fix in autopts is merged

**Comment by sjanc** [comment]
#AutoPTS run zephyr GAP/BOND/NBON/BV-02-C

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.

**Review by sjanc — APPROVED** [review]

**Review by kapi-no — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

File: subsys/bluetooth/host/smp.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/host/smp.c:2872]: @jhedberg @alwa-nordic Any comments here? Am I misreading something, or is there a spec issue here?

Comment (jhedberg) [reply subsys/bluetooth/host/smp.c:2872]: > @jhedberg @alwa-nordic Any comments here? Am I misreading something, or is there a spec issue here?

I'm not sure I completely understand your concern. The situation is like @seko-nordic described in his earlier comment. You'll be able to encrypt, but just for the same connection that you run the SMP procedure over. That's how SMP with no-bonding is expected to behave.

Comment (Thalley) [reply subsys/bluetooth/host/smp.c:2872]: I agree, but my concern is not with this PR, but the text in the specifications. To me it seems that the definitions of bonding information and security information don't match up.
