### PR TITLE
Bluetooth: Controller: Fix ISO Data sn nesn on flush

### LINKED ISSUE #54342: Bluetooth: Controller: Connected ISO Central causes Peripheral to drop ISO data PDUs
**Describe the bug**
When central_iso and peripheral_iso samples are transmitting in a noisy environment and central flushes retransmitted ISO PDU, it does not update the SN value. This causes the peripheral to drop the new ISO PDU in the next CIG/CIS event.

In an audio application, this presents itself as pops/clicks in received audio due to missing packets on the audio sink side.

**To Reproduce**
1. mkdir build/central_iso; cd build/central_iso
2. cmake -DBOARD=nrf52840dk_nrf52840 ../../samples/bluetooth/central_iso
3. ninja
4. ninja flash
5. Repeat steps 1 - 4 for samples/bluetooth/peripheral_iso
6. observe in terminal window for peripheral_iso device, that it is receiving ISO packets
7. Try moving device far apart
8. Retransmissions cause sink device to skip receiving next ISO data

**Expected behavior**
Retransmissions that are received by sink device but ack not received by central should not cause the next ISO data to be dropped by peripheral device.

**Impact**
annoyance, as the quality of audio is poorer than actual in noisy environments

**Logs and console output**
None

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: v3.3.0-rc1

**Additional context**
NA

### PR DESCRIPTION
**Pull request by cvinayak**
Fix sn and nesn values of ISO data when starting a new burst. When central retransmitted but did not get an ack, it did not update the sn correctly causing the peripheral to drop the next ISO data PDU.

Fixes #54342

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_central_iso.c [hunk 1]
```diff
@@ -812,7 +812,15 @@ static void isr_done(void *param)
...
 	cis_lll = param;
 
-	/* Generate ISO Data Invalid Status */
+	/* Adjust sn when flushing Tx */
+	bn = bn_tx;
+	while (bn <= cis_lll->tx.bn) {
+		cis_lll->sn++;
+
+		bn++;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_central_iso.c:821]: This basically adds the difference between `bn` and `cis_lll->tx.bn`, right? 

Would it be simpler to do
```c
cis_lll->sn += cis_lll->tx.bn - bn
```

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_peripheral_iso.c [hunk 2]
```diff
@@ -530,7 +530,21 @@ static void isr_rx(void *param)
...
+
+		/* Adjust sn when flushing Tx. Stop at sn != nesn, hence
+		 * (bn < cis_lll->tx.bn).
+		 */
+		bn = bn_tx;
+		while (bn < cis_lll->tx.bn) {
+			cis_lll->sn++;
+
+			bn++;
+		}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_peripheral_iso.c:545]: Ditto. 

Perhaps since we are doing the exact same thing, this action could even be put into a function or macro.

**Review by Thalley — DISMISSED** [review]
LGTM, but added a suggestion on a possible improvement

**Review by kruithofa — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_central_iso.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_central_iso.c:821]: Yes. I wanted to keep it simple as current usecase where BN=1. Will do some testing and update the PR.

**Review by Thalley — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
