### PR TITLE
drivers: sensor: bosch: bme680: fix: overflowed value return value

### LINKED ISSUE #84751: [Coverity CID: 487643] Overflowed return value in drivers/sensor/bosch/bme680/bme680.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/drivers/sensor/bosch/bme680/bme680.c

Category: Insecure data handling
Function: `bme680_calc_gas_wait`
Component: Drivers
CID: [487643](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487643)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/drivers/sensor/bosch/bme680/bme680.c#L213

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487643

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by fabocode**
- Check if the value exceeds the limits of the variable

Fixes #84751

### CODE REVIEW

File: drivers/sensor/bosch/bme680/bme680.c [hunk 1]
```diff
@@ -207,7 +207,9 @@ static uint8_t bme680_calc_gas_wait(uint16_t dur)
 			dur = dur / 4;
 			factor += 1;
 		}
-		durval = dur + (factor * 64);
+		uint16_t max_duration = dur + (factor * 64);
+
+		durval = max_duration > 0xff ? 0xff : max_duration;
```
Comment (yperess) [inline drivers/sensor/bosch/bme680/bme680.c:212]: nit: can use `durval = CLAMP(max_duration, 0, 0xff);`

**Review by yperess — DISMISSED** [review]

File: drivers/sensor/bosch/bme680/bme680.c (hunk 1 above)
Comment (fabocode) [reply drivers/sensor/bosch/bme680/bme680.c:212]: Thanks for the tip! I think this case is applicable to use the CLAMP() macro.

**Review by ubieda — APPROVED** [review]

**Review by yperess — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
