### PR TITLE
 drivers: flash: flash_shell.c: Fix parsing of `flash read`

### LINKED ISSUE #101115: The parsing of the `flash read` command expects an hexadecimal byte count size without `0x`
### Describe the bug

The command `flash read` from the flash shell expects an hexadecimal byte count size without `0x`. That leads to unexpected behaviour.

A pull request has been made for this issue. #101010 

### Regression

- [ ] This is a regression.

### Steps to reproduce

To reproduce, you need a board with a flash, or the native flash driver.

1. Enable the flash shell
2. Run `flash read` with a size greater or equal to 10.

### Relevant log output

```shell
uart:~$ flash read s25fl032p@0 0 9
00000000: ff ff ff ff ff ff ff ff  ff                      |........ .       |

uart:~$ flash read s25fl032p@0 0 10
00000000: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: any
- Zephyr: main

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mrjimenez**
The parsing of the number of bytes to read in the read command was being done in hexadecimal, causing unexpected behavior.

Now the number can be interpreted in decimal or hexadecimal if prefixed with 0x.

Also fixes the help test of the `flash read` command.

### CODE REVIEW

**Comment by de-nordic** [comment]
@mrjimenez Would it be possible to log a bug for that and link it to the PR?

**Review by de-nordic — APPROVED** [review]
Looks OK.
You have won very nice looking PR number 101010.

**Review by maass-hamburg — APPROVED** [review]

File: drivers/flash/flash_shell.c [hunk 1]
```diff
@@ -792,62 +790,46 @@ static void device_name_get(size_t idx, struct shell_static_entry *entry)
...
+	SHELL_CMD_ARG(erase, &dsub_device_name, "[<device>] <page address> [<size>]", cmd_erase, 2,
+		      2),
+	SHELL_CMD_ARG(read, &dsub_device_name, "[<device>] <address> [<byte count>]", cmd_read, 2,
+		      2),
+	SHELL_CMD_ARG(test, &dsub_device_name, "[<device>] <address> <size> <repeat count>",
+		      cmd_test, 4, 1),
+	SHELL_CMD_ARG(write, &dsub_device_name, "[<device>] <address> <dword> [<dword>...]",
+		      cmd_write, 3, BUF_ARRAY_CNT),
+	SHELL_CMD_ARG(load, &dsub_device_name, "[<device>] <address> <size>", cmd_load, 3, 1),
+	SHELL_CMD_ARG(page_info, &dsub_device_name, "[<device>] <address>", cmd_page_info, 2, 1),
```
Comment (pdgendt) [inline drivers/flash/flash_shell.c:810]: Since you're touching these, might be even nicer to use `SHELL_HELP`.

Comment (mrjimenez) [reply drivers/flash/flash_shell.c:810]: I have another pr in the queue that will conflict if I change these, but sure, I can do it after it goes in.
