### PR TITLE
linker: Split nocache memory sections into loadable and non-loadable

### LINKED ISSUE #94812: `nocache` data is included in ROM section
### Describe the bug

Placing buffers into the `nocache` section, uses flash or ROM space.

### Regression

- [x] This is a regression by https://github.com/zephyrproject-rtos/zephyr/pull/87826

### Steps to reproduce

Apply this simple patch to the `hello_world` sample:

```diff
diff --git a/samples/hello_world/src/main.c b/samples/hello_world/src/main.c
index c550ab461cb..afcf27289b4 100644
--- a/samples/hello_world/src/main.c
+++ b/samples/hello_world/src/main.c
@@ -5,10 +5,17 @@
  */

 #include <stdio.h>
+#include <zephyr/kernel.h>
+
+K_HEAP_DEFINE_NOCACHE(buf, 10000);

 int main(void)
 {
        printf("Hello World! %s\n", CONFIG_BOARD_TARGET);

+       void *ptr = k_heap_alloc(&buf, 10, K_FOREVER);
+       k_heap_free(&buf, ptr);
+
        return 0;
 }
```

Build with nocache enabled

```shell
$ west build -p -b mimxrt1064_evk samples/hello_world -- -DCONFIG_NOCACHE_MEMORY=y
```

Inspect `rom_report`:

```shell
$ west build -t rom_report
...
    ├── samples                                                                                 10072  20.07%  -
    │   └── hello_world                                                                         10072  20.07%  -
    │       └── src                                                                             10072  20.07%  -
    │           └── main.c                                                                      10072  20.07%  -
    │               ├── buf                                                                        20   0.04%  0x80004038 k_heap_area
    │               ├── kheap_buf                                                          ---> 10000  19.93%  0x80000000 nocache
    │               └── main                                                                       52   0.10%  0x70002595 text
```

And `ram_report`:

```shell
$ west build -t ram_report
...
└── samples                                                                                     10020  48.42%  -
    └── hello_world                                                                             10020  48.42%  -
        └── src                                                                                 10020  48.42%  -
            └── main.c                                                                          10020  48.42%  -
                ├── buf                                                                            20   0.10%  0x80004038 k_heap_area
                └── kheap_buf                                                              ---> 10000  48.32%  0x80000000 nocache
```

### Relevant log output

```shell
f9168ae46409bb4a7908c48f4385cb3ac4bc6888 is the first bad commit
commit f9168ae46409bb4a7908c48f4385cb3ac4bc6888
Author: Julian Achatzi <mail@achatzi.pro>
Date:   Fri Mar 28 14:55:31 2025 +0100

    arch: common: Make nocache region loadable

    The `nocache` is not loadable, thus data stored therein cannot be
    initialized by the startup code. This might be needed in special
    cases. E.g. One might have a buffer which one wants to DMA into,
    and which is a member of a struct. Other members of the struct one
    may want to have initialized by the startup code.
    The buffer thus should be placed in the `nocache` region, but for
    the other members of the buffer to be initialized by the startup
    code, the `nocache` region needs to be loadable.

    Fix it by making the `nocache` region loadable. Adding a KConfig
    symbol to do this optionally was considered, but deemed unnecessary
    during the PR.

    Signed-off-by: Julian Achatzi <mail@achatzi.pro>

 arch/common/nocache.ld              | 5 +++--
 include/zephyr/linker/linker-defs.h | 1 +
 kernel/xip.c                        | 6 ++++++
 3 files changed, 10 insertions(+), 2 deletions(-)
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Ubuntu 24.04
- Toolchain: Zephyr SDK 0.16.8
- Current main 347fb0a75a1fc637b6f7bf00e951ae57c89c2c47

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pdgendt**
Commit f9168ae46409bb4a7908c48f4385cb3ac4bc6888 made all non-cached memory loadable by default.

However as nocache memory is typically used for reserving larger buffers to be shared between peripherals, this comes at fairly large cost towards ROM usage.

This commit creates two distinct sections for both loadable and non-loadable nocache memory sections.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/94812

### CODE REVIEW

**Review by JarmouniA — COMMENTED** [review]
All code that uses `_nocache_ram_start\_nocache_ram_end` to check if a buffer is in linker-defined nocache region, will have to be updated to check the loadable section as well.
Ex.
https://github.com/zephyrproject-rtos/zephyr/blob/80ab4b810021cef2185d62f6fa63593b6972f628/soc/st/stm32/common/stm32_cache.c#L34

**Comment by pdgendt** [comment]
> All code that uses `_nocache_ram_start\_nocache_ram_end` to check if a buffer is in linker-defined nocache region, will have to be update to check the loadable section as well. Ex.

Hmn good point, maybe I can make the loaded nocache a part of this.

File: include/zephyr/linker/section_tags.h [hunk 1]
```diff
@@ -53,9 +53,11 @@
 
 #if defined(CONFIG_NOCACHE_MEMORY)
 #define __nocache __in_section_unique(_NOCACHE_SECTION_NAME)
+#define __nocache_load __in_section_unique(_NOCACHE_LOAD_SECTION_NAME)
```
Comment (JarmouniA) [inline include/zephyr/linker/section_tags.h:56]: Isn't the distinction between load/noload variables supposed to be handled automatically?
Also, these attributes are not always used, there is code that uses `__attribute__((__section__` directly
https://github.com/zephyrproject-rtos/zephyr/blob/db15de527442c4842c52e125e3d2e29b7b1f6e04/tests/drivers/spi/spi_loopback/src/spi.c#L70

Comment (pdgendt) [reply include/zephyr/linker/section_tags.h:56]: I don't think this works with the way cortex-m defines the `nocache` section, but there are probably others with more knowledge than me that can answer that, maybe @tejlmand ?

For the manual cases, I can't comment on those.

File: kernel/xip.c
Comment (cfriedt) [inline kernel/xip.c:1]: This part I find a little confusing. Can you elablorate slightly just in review comments @pdgendt ?

Comment (pdgendt) [reply kernel/xip.c:1]: You mean the change in this file? Or even the original code? I updated this because of renaming the sections, and specifically adding the loadable nocache section.

Comment (cfriedt) [reply kernel/xip.c:1]: Nevermind, it was just this file, but it makes sense to me now.

**Review by cfriedt — APPROVED** [review]

**Comment by tejlmand** [comment]
Discussed at Toolchain WG: 2025-09-01.
Proceed with proposed solution seems to best way forward considered the limited need for initialized nocache data.

**Review by nashif — APPROVED** [review]

File: include/zephyr/linker/section_tags.h (hunk 1 above)
Comment (JarmouniA) [reply include/zephyr/linker/section_tags.h:56]: Can we replace all instances of `__attribute__((__section__(".nocache")))` with `__nocache` as part of this PR?
