### PR TITLE
random: entropy: Fix invalid memory access

### LINKED ISSUE #26435: Suspicious source code with subsys/random/random32_entropy_device: seg fault risk
**Describe the bug**
In the source code subsys/random/random32_entropy_device, static function rand_get: risk of seg fault if output requested length is not modulo 4.

**To Reproduce**
NA
**Expected behavior**
Shall be fixed to avoid seg fault with length % 4 != 0 as input

**Impact**
NA

**Screenshots or console output**
NA

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain : zephyr-sdk-0.11.3
 - Commit SHA 979e124e21fb05cfedf8ed12078983d40e2f0b6c

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ceolin**
In sys_rand_get() if the entropy hardware unlikely return error, the
fallgback is using the system timer to and fill the given buffer with
that data.

The problem what that k_cycle_get_32() returns a four bytes integer and
depending the sizeof of the buffer we need copy the right amount of
data. That was not being done properly leading to invalid read/write
memory access.

Fixes #26435

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

File: subsys/random/rand32_entropy_device.c [hunk 1]
```diff
@@ -86,14 +86,9 @@ static int rand_get(uint8_t *dst, size_t outlen, bool csrand)
...
-				(void)memcpy(&(dst[random_num]),
-						&random_num, blocksize);
-			} else {
-				*((uint32_t *)&dst[len]) = random_num;
-			}
-
+			(void)memcpy(&(dst[len]), &random_num,
+				(outlen - len > blocksize) ? blocksize :
+				outlen - len);
 			len += blocksize;
```
Comment (pabigot) [inline subsys/random/rand32_entropy_device.c:92]: While the above works IMO it would be more clear to do something like:

    size_t copylen = outlen - len;

    if (copylen > blocksize) {
        copylen = blocksize;
    }
    (void)memcpy(&dst[len], &random_num, copylen);
    len += copylen;

because adding `blocksize` when only `outlen - len` was copied is confusing.

Comment (ceolin) [reply subsys/random/rand32_entropy_device.c:92]: I don't mind change, but both ways would just finish the loop that is why I didn't bother changing it

Comment (ceolin) [reply subsys/random/rand32_entropy_device.c]: just done :)

File: subsys/random/rand32_entropy_device.c [hunk 2]
```diff
@@ -85,16 +85,14 @@ static int rand_get(uint8_t *dst, size_t outlen, bool csrand)
...
 		while (len < outlen) {
-			random_num = k_cycle_get_32();
-			if ((outlen-len) < sizeof(random_num)) {
-				blocksize = len;
-				(void)memcpy(&(dst[random_num]),
-						&random_num, blocksize);
-			} else {
-				*((uint32_t *)&dst[len]) = random_num;
+			size_t copylen = outlen - len;
+			if (copylen > blocksize) {
```
Comment (pabigot) [inline subsys/random/rand32_entropy_device.c:89]: You'll need an empty line here to make checkpatch happy.

**Review by pabigot — APPROVED** [review]

File: subsys/random/rand32_entropy_device.c (hunk 1 above)
Comment (pabigot) [reply subsys/random/rand32_entropy_device.c]: Thanks.

As I said, it works, it just means `len` is not the number of bytes copied into `dst` as it is throughout the loop up to the last point.  So somebody who needed to modify this to use `len` after the loop could waste a lot of time figuring out it was wrong.

I don't think it's good to make it harder for people to maintain and evolve code.  That's not a sign of a quality software system.

**Review by dleach02 — APPROVED** [review]
