### PR TITLE
soc: espressif: esp32s3: Adjust DRAM size for .bss.sector_buffers to prevent overflow with larger images

### LINKED ISSUE #80138: DRAM overflow of .bss.sector_buffers when slot partition is bigger then 4MB on esp32s3 (N16R8) with Zephyr
After adjusting my flash map, I noticed the following error.

This error occurs whenever either of the two slot partitions is assigned more than 4MB. In the case above, it was assigned 6MB.

A comparison of the ´zephyr_pre0.map´ from both compilations shows that sector_buffers requires more DRAM.

As a workaround, I increased ´BOOTLOADER_DRAM_SEG_LEN´ in ´zephyr/soc/espressif/esp32s3/memory.h´ by 0x2000. The error no longer occurs, but I am not sure about the side effects in regards to secure boot and other security features.

This issue is originally opened at mcuboot repo:
https://github.com/mcu-tools/mcuboot/issues/2094

Update:
I've gathered a few more insights:

The sector_buffers reserve 12 bytes for each sector (4KB of flash) for both arrays. So, <(partition_size / 4000) * 12 * 2> bytes are allocated in .bss.sector_buffers. This explains why the DRAM overflows when the partition size exceeds a certain limit.

To fix this, the limit would need to adjusted based on the number of sectors.

**To Reproduce**

1. build any example project with esp32s3 with --sysbuild
2. increase any image-slot to a size > 4MB

**Expected behavior**
BOOTLOADER_DRAM_SEG_LEN should also consider the maximal sectors and adjust respectively.

**Impact**

We cannot use our full flash storage for image OTA.

**Logs and console output**

```log
/usr/local/zephyr-sdk-0.16.8/xtensa-espressif_esp32s3_zephyr-elf/bin/../lib/gcc/xtensa-espressif_esp32s3_zephyr-elf/12.2.0/../../../../xtensa-espressif_esp32s3_zephyr-elf/bin/ld.bfd: zephyr/zephyr_pre0.elf section '.bss' will not fit in region 'dram_seg'
/usr/local/zephyr-sdk-0.16.8/xtensa-espressif_esp32s3_zephyr-elf/bin/../lib/gcc/xtensa-espressif_esp32s3_zephyr-elf/12.2.0/../../../../xtensa-espressif_esp32s3_zephyr-elf/bin/ld.bfd: DRAM segment data does not fit.
/usr/local/zephyr-sdk-0.16.8/xtensa-espressif_esp32s3_zephyr-elf/bin/../lib/gcc/xtensa-espressif_esp32s3_zephyr-elf/12.2.0/../../../../xtensa-espressif_esp32s3_zephyr-elf/bin/ld.bfd: region `dram_seg' overflowed by 7152 bytes
```

**Environment:**
 - Soc: ESP32S3 (N16R8)
 - Toolchain: xtensa-espressif_esp32s3_zephyr
 - Commit (manifest-rev): 03959a20f7834ffe50a51df2b2e45ef87d1b610b

### PR DESCRIPTION
**Pull request by FacepalmMute**
This pull request solves the issue descried in https://github.com/zephyrproject-rtos/zephyr/issues/80138

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/80138

### CODE REVIEW

File: soc/espressif/esp32s3/memory.h [hunk 1]
```diff
@@ -47,9 +48,22 @@
  */
 #define BOOTLOADER_USER_DRAM_END DRAM_BUFFERS_START
 
+/* Calculate required DRAM size for .bss.sector_buffers to adjust BOOTLOADER_DRAM_SEG_LEN
```
Comment (marekmatej) [inline soc/espressif/esp32s3/memory.h:51]: I think it is much more straightforward to simply increase the `BOOTLOADER_DRAM_SEG_LEN` value to support the "worst case" scenario.
All the MCUboot segments - except the `BOOTLOADER_IRAM_LOADER` - will be rewritten by the last stage of the bootloader anyway.

**Review by marekmatej — CHANGES_REQUESTED** [review]
Good approach in general, but let's make it simpler.

File: soc/espressif/esp32s3/memory.h (hunk 1 above)
Comment (FacepalmMute) [reply soc/espressif/esp32s3/memory.h:51]: Simple is good 👍

In the worst-case scenario, we could have an ESP32S3 N32R8V with 32MB of flash. A crazy user might allocate approximately 16MB for the image partition. This would mean that sector_buffers might use around 0x10000 in the worst case.

So can i just add `0x10000` to `BOOTLOADER_DRAM_SEG_LEN` ?

Comment (marekmatej) [reply soc/espressif/esp32s3/memory.h]: Since we can't support random "crazy user" let's be realistic now. The biggest partition size for the 32MB flash would be ~12MB, which is an addition of `0xC000` to the actual DRAM size, so with `0x15000` we should be fine.

**Review by marekmatej — APPROVED** [review]

**Review by wmrsouza — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Review by uLipe — APPROVED** [review]

**Review by marekmatej — APPROVED** [review]

**Review by sylvioalves — APPROVED** [review]
