### PR TITLE
drivers: usb_dc_rpi_pico: don't call usb_dc_ep_start_read() on transf…

### LINKED ISSUE #66283: rpi_pico: First USB packet lost after reset due to wrong toggle bit
I found an issue in the USB device driver for the rpi_pico aka RP2040. After startup, I receive an BULK_OUT tranfers from the host PC with DATA0. But here, the Zephyr driver already expects DATA1 which leads to the the packet being dismissed the warning `udc_rpi: data seq` being logged.

After some debugging and comparing to other drivers, I found that the issue is that we already start a transfer on `usb_dc_ep_enable` which leads to the misaligned data toggle. This is at least the case when we use the `usb_transfer` with the `usb_transfer_ep_callback`.

And indeed, when looking into other drivers, e.g. the one for the DesignWare DC, we see that this code is not executed in the case that we have registered the `usb_transfer_ep_callback`:
```
	if (USB_EP_DIR_IS_OUT(ep) &&
	    usb_dw_ctrl.out_ep_ctrl[ep_idx].cb != usb_transfer_ep_callback) {
		/* Start reading now, except for transfer managed eps */
		usb_dw_prep_rx(ep, 0);
	}
```
When I change the following code
https://github.com/zephyrproject-rtos/zephyr/blob/227905ac4df141441ddea6a301cb9bd80821d2ca/drivers/usb/device/usb_dc_rpi_pico.c#L655

to
```
if ((USB_EP_DIR_IS_OUT(ep) && ep != USB_CONTROL_EP_OUT) &&
	    (ep_state->cb != usb_transfer_ep_callback)) {
```
it seems to work flawlessly.

### PR DESCRIPTION
**Pull request by Manu3l0us**
…er-managed endpoints during setup and properly reset next_pid.

The previous behaviour led to an issue where we already expected data1 on the first transfer instead of data0. The DesignWare USB DC actually implements the same behaviour. Also, the next_pid flag has to be reset on setting up the endpoint.

Fixes: #66283

### CODE REVIEW

**Review by tmon-nordic — DISMISSED** [review]

File: drivers/usb/device/usb_dc_rpi_pico.c [hunk 1]
```diff
@@ -640,6 +640,7 @@ int usb_dc_ep_enable(const uint8_t ep)
 	/* clear buffer state (EP0 starts with PID=1 for setup phase) */
 
 	*ep_state->buf_ctl = (USB_EP_GET_IDX(ep) == 0 ? USB_BUF_CTRL_DATA1_PID : 0);
+	ep_state->next_pid = (USB_EP_GET_IDX(ep) == 0 ? 1 : 0);
```
Comment (jfischer-no) [inline drivers/usb/device/usb_dc_rpi_pico.c:643]: This is a bit confusing (also the comment above, DATA0 PID follows SETUP PID), maybe it works because setup packet can always be received and driver below does not call udc_rpi_start_xfer() for control out endpoint and next PID is explicitly updated in udc_rpi_handle_setup(). Can you change these two lines, 642 and 643, to
```c

	*ep_state->buf_ctl = USB_BUF_CTRL_DATA0_PID;
	ep_state->next_pid = 0;
```
and test it?

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/device/usb_dc_rpi_pico.c (hunk 1 above)
Comment (Manu3l0us) [reply drivers/usb/device/usb_dc_rpi_pico.c]: Okay, I changed it according to your suggestion and it works on my side.

File: drivers/usb/device/usb_dc_rpi_pico.c [hunk 2]
```diff
@@ -652,7 +653,8 @@ int usb_dc_ep_enable(const uint8_t ep)
 		*ep_state->ep_ctl = val;
 	}
 
-	if (USB_EP_DIR_IS_OUT(ep) && ep != USB_CONTROL_EP_OUT) {
+	if ((USB_EP_DIR_IS_OUT(ep) && ep != USB_CONTROL_EP_OUT) &&
+	    (ep_state->cb != usb_transfer_ep_callback)) {
```
[the remark this answers is not in the document]
Comment (Manu3l0us) [reply drivers/usb/device/usb_dc_rpi_pico.c]: Fixed

**Review by tmon-nordic — APPROVED** [review]

File: drivers/usb/device/usb_dc_rpi_pico.c (hunk 1 above)
Comment (jfischer-no) [reply drivers/usb/device/usb_dc_rpi_pico.c]: But do **you** think it is the right way and makes sense? Not that you changed it just because I suggested it.

Comment (Manu3l0us) [reply drivers/usb/device/usb_dc_rpi_pico.c]: It makes sense to me. As you said, next_pid for control is forced in udc_rpi_handle_setup. I had another close look at the code and I'm confident that this is the right way.

**Review by jfischer-no — APPROVED** [review]
Thank you

**Comment by Manu3l0us** [comment]
Is there still anything missing from my side or what's the status on this PR?
