### PR TITLE
devicetree: make DT_PROP_HAS_IDX expand to 0 or 1

### LINKED ISSUE #29833: Test DT_INST_PROP_HAS_IDX() inside the macros for multi instances
I'm fixing interrupt handling inside LIS2DH sensor driver, which has recently been made multi instance.
The LIS2DH driver should be done in a way to use two interrupts (drdy on INT1 and other vtriggers on INT2) defined in DT, like:

    lis2dh@18 {
        compatible = "st,lis2dh";
        reg = <0x18>;
        label = "LIS2DH";
        irq-gpios = <&arduino_header 5 GPIO_ACTIVE_HIGH>, <&arduino_header 6 GPIO_ACTIVE_HIGH> ;
    };

In the code I'm writing someling like this:

    .irq1_dev_name = COND_CODE_1(DT_INST_PROP_HAS_IDX(inst, irq_gpios, 0),> \
                                                              (DT_INST_GPIO_LABEL_BY_IDX(inst, irq_gpios, 0)),     \
                                                               (NULL) ),    \

    .irq2_dev_name = COND_CODE_1(DT_INST_PROP_HAS_IDX(inst, irq_gpios, 1),> \
                                                              (DT_INST_GPIO_LABEL_BY_IDX(inst, irq_gpios, 1)),     \
                                                               (NULL) ),    \

But COND_CODE_1 requires something different as it gives following errors when building:

  ../include/sys/util_internal.h:52:14: error: pasting "_XXXX" and "(" does not give a valid 
  preprocessing token
   52 |  __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |              ^~~~~
  ../include/sys/util_macro.h:112:2: note: in expansion of macro 'Z_COND_CODE_1'
  112 |  Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |  ^~~~~~~~~~~~~
  /local/home/visconti/Projects/zephyrproject/zephyr/drivers/sensor/lis2dh/lis2dh.c:414:20: note: in 
   expansion of macro 'COND_CODE_1'
    414 |   .irq1_dev_name = COND_CODE_1(DT_INST_PROP_HAS_IDX(inst, irq_gpios, 0), \
       |                    ^~~~~~~~~~~ 

Is it possible to create new macros for handling such cases?
Thanks

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
We have a use case for checking the results of a DT_PROP_HAS_IDX()
call with COND_CODE_1(). That won't work because its expansion is an
integer comparison; COND_CODE_1() expects a literal 1 or 0.

Adjust the macro implementation so it expands to a literal 1 or 0.
Make this work even when the index argument needs an expansion while
we're at it.

Fixes: #29833
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

### CODE REVIEW

**Comment by avisconti** [comment]
@mbolivar-nordic 
This commit won't break anything, right?
It shouldn't, as the result of a comparison (a < b) is anyway 0 or 1.

**Comment by avisconti** [comment]
@mbolivar-nordic 
What I can tell you right now is that code is now buildng correctly. I will do more testing and investigation. I can try immediately to give you my feedback on the commit itself, which looks simple.

File: include/devicetree.h [hunk 1]
```diff
@@ -1921,8 +1922,35 @@
...
+ * This and the following macros are used to pasting things together
+ * with "##" *after* forcing expansion on each argument.
+ *
+ * We could try to use something like UTIL_CAT(), but the compiler
+ * error messages from the util macros can be extremely long when they
+ * are misused. This unfortunately happens often with devicetree.h,
+ * since its macro-based API is fiddly and can be hard to get right.
+ *
+ * Keeping things brutally simple here hopefully makes some errors
+ * easier to read.
```
Comment (avisconti) [inline include/devicetree.h:1938]: I agree to easy up debugging macros misusing errors.

**Review by avisconti — COMMENTED** [review]
I just leave a comment for the moment. 

It LGTM, but I don't feel much confident with this macros. Though, I am testing it on my side and once that everything works I'll approve the PR in an experimental way. I leave to other experts the burden to provide better feedbacks here.

**Comment by mbolivar-nordic** [comment]
> This commit won't break anything, right?

No, it won't break anything. If it does, I'll fix it :). However, we use this same `_EXISTS` + `IS_ENABLED` trick in several places in this API so I'm sure it's fine.

**Review by pabigot — APPROVED** [review]
I'd expect a macro that's named to express a binary proposition like `has` to be suitable for use as a parameter to something expecting 0 or 1, so this makes sense.

**Review by avisconti — APPROVED** [review]
I'm proceeding in my coding an it will take some more time, but for what concern this macro modification it seems to work fine and giving the correct result.

**Review by galak — APPROVED** [review]
