### PR TITLE
Fix DCMIPP parallel interface based RGB565 & GC2145 CSI RGB565 formats

### LINKED ISSUE #98839: STM32 DCMIPP (dump pipe) exposed RGB565 format has wrong colors
### Describe the bug

An RGB565 frame generated by the STM32 DCMIPP pipeline over pipe dump does not show correct colors when using RGB565 enabled sensors such as OV5640.

On platform such as STM32N6, STM32MP13 but also STM32H7RS(*), connecting a sensor which output RGB565 format and capturing it via the dump pipe leads to having wrong colors being shown.

It turns out that, while the STM32MP135F-DK has such camera (GC2145), an additionnal bug within the GC2145 was hiding the DCMIPP issue, since on GC2145 the color formatting was reversed, leading to DCMIPP bug being "corrected/hidden" by another bug within the GC2145.

(*) Camera pipeline isn't yet enabled for the STM32H7RS, but the PR is going to be pushed for that shortly. Preparing this allowed to see the issue by using STM32H7RS + ST_B_CAMS_OMV OV5640 based camera shield.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by avolmat-st**
While preparing addition of the camera pipeline into the STM32H7RS, I ran the OV5640 sensor (st_b_cams_omv shield) on it and noticed that the colors were not correct.

It turns out that both DCMIPP parallel interface configuration is not correct in case of RGB565 format. As indicated in the 1st commit of this PR, the expected RGB565 format by the DCMIPP in parallel is cycled swapped compared to the RGB565 defined by Zephyr for RGB565 (and from sensors). For this reason it is necessary to apply a cycle swap on the input of the DCMIPP in case of parallel interface based in RGB565.

The MP135F-DK board is also using this format in parallel but issue was not seen so far due to a 2nd bug this time within the GC2145 driver when used in RGB565 / CSI mode (The MP135F-DK embeds a CSI to parallel bridge). The GC2145 (in CSI mode) was outputting RGB565 but in Big Endian formatting instead of the common Little Endian formatting defined by MIPI. This was leading swapped cycles at the input of the DCMIPP, hence "hiding" the DCMIPP issue.

This PR corrects both GC2145 and DCMIPP side and I can confirm now that DCMIPP can properly work with the default OV5640 sensor / drive on the STM32H7RS soc. (this support will be pushed in a separate PR since this STM32H7RS / Camera is not to be considered as a fix).

Fixes: #98839

### CODE REVIEW

**Review by josuah — DISMISSED** [review]
It looks like it does not affect any DCMI-based peripheral which lack the CSI support.

Maybe this also affects YUYV (2 bytes as well).

Thanks!

**Comment by avolmat-st** [comment]
> It looks like it does not affect any DCMI-based peripheral which lack the CSI support.
> 
> Maybe this also affects YUYV (2 bytes as well).
> 
> Thanks!

Yes, this won't affect DCMI based board and any other existing GC2145 based board apart from the st_mb1897 which I think is the only one that has CSI based GC2145. So far it seems that this is only on RGB565 and not YUV variants.

File: drivers/video/video_stm32_dcmipp.c [hunk 1]
```diff
@@ -328,7 +328,26 @@ static int stm32_dcmipp_conf_parallel(const struct device *dev,
 	HAL_StatusTypeDef hal_ret;
 
 	parallel_cfg.Format           = input_fmt->dcmipp_format;
-	parallel_cfg.SwapCycles       = DCMIPP_SWAPCYCLES_DISABLE;
+	/*
+	 * On parallel interface, the DCMIPP expects data in RGB565_BE, aka
+	 *		D7 D6 D5 D4 D3 D2 D1 D0
+	 *
+	 * cycle 1:	R4 R3 R2 R1 D0 G5 G4 G3
```
Comment (ngphibang) [inline drivers/video/video_stm32_dcmipp.c]: Should be `R4 R3 R2 R1 R0 G5 G4 G3` ?

File: drivers/video/video_stm32_dcmipp.c [hunk 2]
```diff
@@ -328,7 +328,26 @@ static int stm32_dcmipp_conf_parallel(const struct device *dev,
...
+	 * cycle 2:	G2 G1 G0 B4 B3 B2 B1 B0
+	 *
+	 * Use swapped cycle mode for RGB565 which correspond to the commonly
+	 * used RGB565 LE, aka
+	 *
+	 *		D7 D6 D5 D4 D3 D2 D1 D0
+	 *
+	 * cycle 1:	G2 G1 G0 B4 B3 B2 B1 B0
+	 * cycle 2:	R4 R3 R2 R1 D0 G5 G4 G3
```
Comment (ngphibang) [inline drivers/video/video_stm32_dcmipp.c]: Should be `R4 R3 R2 R1 R0 G5 G4 G3` ?

**Review by ngphibang — DISMISSED** [review]
LGTM

File: drivers/video/video_stm32_dcmipp.c (hunk 1 above)
Comment (avolmat-st) [reply drivers/video/video_stm32_dcmipp.c]: Oups, thanks. Fixed.

File: drivers/video/video_stm32_dcmipp.c (hunk 2 above)
Comment (avolmat-st) [reply drivers/video/video_stm32_dcmipp.c]: Itto

**Review by ngphibang — APPROVED** [review]

**Review by josuah — APPROVED** [review]
