### PR TITLE
bluetooth: shell: refactor shell print for Bluetooth-specific context

### LINKED ISSUE #41796: shell_print crashes the board on `bt bonds` and `bt connections`
- board - Particle Xenon
- Zephyr ver (using `main` ref in west.yml) - c51aa88046ca5c9d687e3e6802b32ddd57dd6de4
- toolchain zephyr 0.13.2

My project is mostly (using the Just Works pairing method by not running `bt_conn_auth_cb_register`) the same as `peripheral_hids`. The problem is that:

- I erase the flash `nrfjprog -e`
- flash the board

Then I run following commands in the RTT shell:

```
rtt:~$ bt bonds
bt bonds
Bonded devices:
Total 0
rtt:~$ bt connections 
bt connections
Connected devices:
[00:00:19.206,909] <err> os: ***** USAGE FAULT *****
[00:00:19.206,909] <err> os:   Unaligned memory access
[00:00:19.206,909] <err> os: r0/a1:  0x00028d8f  r1/a2:  0x00001000  r2/a3:  0x00032f6f
[00:00:19.206,939] <err> os: r3/a4:  0x00028d8f r12/ip:  0x0000000a r14/lr:  0x0002626f
[00:00:19.206,939] <err> os:  xpsr:  0x21000000
[00:00:19.206,939] <err> os: Faulting instruction address (r15/pc): 0x00026076
[00:00:19.206,939] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:19.206,970] <err> os: Current thread: 0x200010a0 (shell_rtt)
[00:00:19.531,158] <err> os: Halting system
```

Running `addr2line -e zephyr/zephyr.elf 0x00026076` puts me here `/home/mc/gits/magknob-zephyr-ble/zephyr/include/sys/atomic_builtin.h:243`

Assume I also paired the board with an iPhone. Then running `bt bonds` crashes the board also.

```
rtt:~$ Connected 6C:6D:7D:A0:83:C4 (random)
Security changed: 6C:6D:7D:A0:83:C4 (random) level 2
bt bonds
bt bonds
Bonded devices:
[00:00:54.425,994] <err> os: ***** USAGE FAULT *****
[00:00:54.425,994] <err> os:   Unaligned memory access
[00:00:54.425,994] <err> os: r0/a1:  0x00028d8f  r1/a2:  0x00001000  r2/a3:  0x00032f3f
[00:00:54.425,994] <err> os: r3/a4:  0x00028d8f r12/ip:  0x0000000a r14/lr:  0x0002626f
[00:00:54.426,025] <err> os:  xpsr:  0x21000000
[00:00:54.426,025] <err> os: Faulting instruction address (r15/pc): 0x00026076
[00:00:54.426,025] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:54.426,025] <err> os: Current thread: 0x200010a0 (shell_rtt)
[00:00:54.747,894] <err> os: Halting system
```

The address points me to `/home/mc/gits/magknob-zephyr-ble/zephyr/include/sys/atomic_builtin.h:243` again.

The crash doesn't happen if I comment out the `shell_print` in this function (which gets run by `cmd_bonds`):

```c
static void bond_info(const struct bt_bond_info *info, void *user_data)
{
    char addr[BT_ADDR_LE_STR_LEN];
    int *bond_count = user_data;

    bt_addr_le_to_str(&info->addr, addr, sizeof(addr));
    shell_print(ctx_shell, "Remote Identity: %s", addr);  // < if I comment this out, it works
    (*bond_count)++;
}
```

In general I can pair with iPhone for the first time (when prompted for pairing) but after disconnecting and trying to reconnect I get:

```
rtt:~$ Connected 78:7F:AE:13:34:85 (random)
Security failed: 78:7F:AE:13:34:85 (random) level 1 err 2
Disconnected from 78:7F:AE:13:34:85 (random) (reason 0x13)
```

That's for *Just Works*. When using setup reconnecting works fine. I need to pair without any pin though. This might be a separate issue but maybe connected...?

### PR DESCRIPTION
**Pull request by ndrs-pst**
This PR aims to eliminate the dependency on `ctx_shell` in the Bluetooth `host/shell/*`, making the code more maintainable.
- Introduced `bt_shell_private.c` and `bt_shell_private.h` to provide common functions for the Bluetooth shell.
- Limit the usage of `ctx_shell` to cases where printing requires it and `sh` is not available. 
(Interim commit before switch to `bt_shell_*`) 
- Refactor shell print to eliminate `ctx_shell` usage in the Bluetooth `host/shell/*`.

Fixes #41796

### CODE REVIEW

**Review by Thalley — DISMISSED** [review]
I don't think this is the right direction (but please do convince me if you believe so). 

Some of the changes are welcome, but the idea of a `bt_shell` is IMO not. 

In your commit message you mention that you want to remove the code footprint, but you also mention an increase cost of this new bt_shell. Aren't those two sentences conflicting? 

The BT shell definitely needs improvement. I created a issue https://github.com/zephyrproject-rtos/zephyr/issues/70945 related to this, that requests the removed of the `ctx_shell`. The removal of the `ctx_shell` would directly conflict with the majority of this PR, as all the `bt_shell` functions you've defined will simply call the shell functions directly (as they would need the shell pointer again). 

Could you provide some data on the codesize that you've increase/decreased?

**Comment by ndrs-pst** [comment]
@Thalley Thank you for your feedback. It's good to hear that you're addressing `ctx_shell`. 😃 

> Aren't those two sentences conflicting?

At first glance, this might seem controversial.
Currently, many shell print require passing parameters like `sh` and `color` repeatedly.
By centralizing these interactions within specific `bt_shell` functions, we streamline the code.

> Could you provide some data on the codesize that you've increase/decreased?

By picking up `periodic_adv_conn` sample with `nrf52840dk` boards and adding `CONFIG_BT_SHELL=y`
the footprint of `shell\*` which get from `rom_report` shown that 

| MODULE  | FLASH SIZE (BEFORE) | FLASH SIZE (AFTER) | INCREASE/DECREASE |
| ------------- | --------------------------- | ---------------------------------- | ---- |
| `bluetooth\shell\*`  | 15,795 B | 14,963 B | -832 B |
| `bt.c`  | 13,251 B | 12,275 B | -976 B |
| `bt_shell_private.c`  | 0 B | 144 B | +144 B |

Here is the footprint from each wrapper
bt_shell_private

**Comment by ndrs-pst** [comment]
To stretch further, I think the functions that should be improved are
`shell_fprintf_impl(sh, color, fmt, ##__VA_ARGS__)` itself to have a wrapper for the color parameter.

```
void __printf_like(2, 3) shell_fprintf_error_impl(const struct shell *sh, const char *fmt, ...);
void __printf_like(2, 3) shell_fprintf_info_impl(const struct shell *sh, const char *fmt, ...);
void __printf_like(2, 3) shell_fprintf_print_impl(const struct shell *sh, const char *fmt, ...);
void __printf_like(2, 3) shell_fprintf_warn_impl(const struct shell *sh, const char *fmt, ...);
```

Since in reality the same message printed out inside the shell is always fixed to a specific color, and if we prioritize the code size, this should make sense.

Otherwise, every time, for example in Cortex-M, `r1` needs to be allocated to pass the `color` value (while r0 is for `sh`), which causes the caller code to save the previously used `r1`.

**Comment by Thalley** [comment]
Just tried your PR with the BT shell test application for the `nrf5340dk_nrf5340_cpuapp` board and got the following results:

With PR
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      317356 B         1 MB     30.27%
             RAM:       52992 B       448 KB     11.55%
        IDT_LIST:          0 GB        32 KB      0.00%
```

Without PR
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      318668 B         1 MB     30.39%
             RAM:       52992 B       448 KB     11.55%
        IDT_LIST:          0 GB        32 KB      0.00%
```

So while I do not agree with the direction of this PR, as we really need to get rid of `ctx_shell`, I can't disagree with the 1312 Bytes saved. 

I'm not at a point where I'll approve, but I'm also not going to reject this change. I'd like to get input from the other BT collaborators on this.

**Comment by ndrs-pst** [comment]
@Thalley, thank you for the additional information. It seems we should start by getting rid of `ctx_shell` and then find a way to reduce the footprint.

**Comment by ndrs-pst** [comment]
> To stretch further, I think the functions that should be improved are `shell_fprintf_impl(sh, color, fmt, ##__VA_ARGS__)` itself to have a wrapper for the color parameter.
> 
> ```
> void __printf_like(2, 3) shell_fprintf_error_impl(const struct shell *sh, const char *fmt, ...);
> void __printf_like(2, 3) shell_fprintf_info_impl(const struct shell *sh, const char *fmt, ...);
> void __printf_like(2, 3) shell_fprintf_print_impl(const struct shell *sh, const char *fmt, ...);
> void __printf_like(2, 3) shell_fprintf_warn_impl(const struct shell *sh, const char *fmt, ...);
> ```
> 
> Since in reality the same message printed out inside the shell is always fixed to a specific color, and if we prioritize the code size, this should make sense.
> 
> Otherwise, every time, for example in Cortex-M, `r1` needs to be allocated to pass the `color` value (while r0 is for `sh`), which causes the caller code to save the previously used `r1`.

@Thalley Just a reminder that this stretch was merged in this PR: https://github.com/zephyrproject-rtos/zephyr/pull/75340. 👀

**Comment by ndrs-pst** [comment]
@Thalley I just added another commit that introduces `CONFIG_BT_SHELL_BACKEND` for Bluetooth shell output when the shell context is unavailable (e.g., in callbacks).

While exploring ways to eliminate `ctx_shell`, could we initialize it during startup and hide it from other shell commands?
Since `ctx_shell` is currently used in multiple places like `audio/shell`, `mesh/shell`, and `services/ias/shell`.

**Comment by Thalley** [comment]
> While exploring ways to eliminate `ctx_shell`, could we initialize it during startup and hide it from other shell commands?

Question is, initialize it to what? 
The challenge (and main issue) with the `ctx_shell` is that it's not a constant. It's just a variable assigned to _some_ shell, of which there can be more 1 or more. That's one of the issue mentioned in https://github.com/zephyrproject-rtos/zephyr/issues/70945

**Comment by ndrs-pst** [comment]
Thanks for the feedback! Please correct me if I'm wrong, the usage of `BT_SHELL` mostly resides with the `SERIAL` or `RTT` backend. Even though it's possible, I'm not sure about the use case for using `MQTT` or `TELNET` to remotely access `BT_SHELL`.

---
As for the previous question, I believe we can initialize it to `backend_name`, which is in `CONFIG_BT_SHELL_BACKEND`, by utilizing `shell_backend_get_by_name("backend_name")`. Even though we can have one or more shells, why can't we specify unsolicited output to just one specific backend?" 🤔

File: subsys/bluetooth/host/shell/bt_shell_private.c [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+/*
+ * Copyright (c) 2024 Nordic Semiconductor ASA
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include "bt_shell_private.h"
+
+extern const struct shell *ctx_shell;
```
Comment (jhedberg) [inline subsys/bluetooth/host/shell/bt_shell_private.c:16]: Wouldn't `bt_shell` be more appropriate, since this is now basically an internal API?

Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt_shell_private.c:16]: That's also fine!
FWIW, I borrowed the name from `#include "net_shell_private.h"`, so I was following that pattern. 😄

**Comment by Thalley** [comment]
> As for the previous question, I believe we can initialize it to `backend_name`, which is in `CONFIG_BT_SHELL_BACKEND`, by utilizing `shell_backend_get_by_name("backend_name")`. Even though we can have one or more shells, why can't we specify unsolicited output to just one specific backend?"

I'm not an expert in the shells, but the current `ctx_shell` is not a backend, but just a reference to a `struct shell`. Multiple `struct shell`s can use the same backend as far as I can tell, so not sure how you are expecting to use a specific backend. 

If you have 2 or more shells that each may call the BT shell command handler, then currently the `ctx_shell` only refers to one at them at any one time and may chance between them whenever `ctx_shell` is reassigned. This is clearly not ideal. 
Question is whether, and how, doing command X on shell S1 that trigger callback Y should send the string from the callback to just S1 or also S2 (another shell instance)?

**Comment by ndrs-pst** [comment]
> If you have 2 or more shells that each may call the BT shell command handler, then currently the `ctx_shell` only refers to one at them at any one time and may chance between them whenever `ctx_shell` is reassigned. This is clearly not ideal.

Yeah, that's why I'm bringing up the real use case. Even if we have two or more shells, do we really need to support BT shell responses for every situation? It feels like we're trying to cover cases that might not happen often. 😃

> just S1 or also S2 (another shell instance)?

As you mentioned as an alternative in #70945. A kind of `shell_wall_print` may look like this

---

```
void bt_shell_wall_print_impl(const char *fmt, ...)
{
	va_list args;
	int count;
	const struct shell *sh;

	va_start(args, fmt);
	count = shell_backend_count_get();
	for (int i = 0; i < count; i++) {
	    va_list args_copy;

	    va_copy(args_copy, args);   /* Create a copy of 'args' to safely reuse */
	    sh = shell_backend_get(i);
	    shell_vfprintf(sh, SHELL_NORMAL, fmt, args_copy);

	    va_end(args_copy);          /* Clean up to prevent resource leaks */
	}
	va_end(args);
}
```

I'm OK if that's the way we can move forward.
Since the priority of this PR is to reduce the footprint and get closer to getting rid of `ctx_shell`.

**WDYT?**

**Comment by Thalley** [comment]
> > If you have 2 or more shells that each may call the BT shell command handler, then currently the `ctx_shell` only refers to one at them at any one time and may chance between them whenever `ctx_shell` is reassigned. This is clearly not ideal.
> 
> Yeah, that's why I'm bringing up the real use case. Even if we have two or more shells, do we really need to support BT shell responses for every situation? It feels like we're trying to cover cases that might not happen often. 😃

It's hard to tell how people use these APIs, but the API does allow for such behavior, and thus any solution to our "problems" should consider what's possible, even if it will only happen with madmen :D 

> As you mentioned as an alternative in #70945. A kind of `shell_wall_print` may look like this
> 
> ```
> void bt_shell_wall_print_impl(const char *fmt, ...)
> {
> 	va_list args;
> 	int count;
> 	const struct shell *sh;
> 
> 	va_start(args, fmt);
> 	count = shell_backend_count_get();
> 	for (int i = 0; i < count; i++) {
> 	    va_list args_copy;
> 
> 	    va_copy(args_copy, args);   /* Create a copy of 'args' to safely reuse */
> 	    sh = shell_backend_get(i);
> 	    shell_vfprintf(sh, SHELL_NORMAL, fmt, args_copy);
> 
> 	    va_end(args_copy);          /* Clean up to prevent resource leaks */
> 	}
> 	va_end(args);
> }
> ```
> 
> I'm OK if that's the way we can move forward. Since the priority of this PR is to reduce the footprint and get closer to getting rid of `ctx_shell`.
> 
> **WDYT?**

I think the `wall` implementation looks fine :) @alwa-nordic was the one who originally suggested that idea, so maybe he has some input here too

**Comment by ndrs-pst** [comment]
@alwa-nordic Thanks for the comment.
I'll address `host/shell` first and leave the others, e.g. `mesh/shell` and `audio/shell`, as they are.

**Comment by ndrs-pst** [comment]
Here we go! Finally, this PR is re-opened for review. 😃
Ping @Thalley, @jhedberg, and @alwa-nordic.

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/shell/bt_shell_private.c [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+{
+	int count;
+	const struct shell *sh;
+
+	count = shell_backend_count_get();
+	for (int i = 0; i < count; i++) {
+		sh = shell_backend_get(i);
+		shell_help(sh);
+	}
+}
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt_shell_private.c:55]: Since these 2 prints on all shells, should they have `wall` in the name too?

**Review by Thalley — COMMENTED** [review]
Looks good. Since BT is pretty much the only shell to do this, I think it makes sense to keep it in BT. One comment/question

**Comment by Thalley** [comment]
Found one other place where "ctx_shell" was used outside of BT, but that was easy to just remove: https://github.com/zephyrproject-rtos/zephyr/pull/81395

File: subsys/bluetooth/host/shell/bt_shell_private.c (hunk 2 above)
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt_shell_private.c:55]: Since the intention was to replace the `shell_*` functions that depended on `ctx_shell` with the appropriate `bt_shell_*` functions (in-short just adding `bt_` prefix) so I think it's no need to have `wall` in the name. :)

Comment (Thalley) [reply subsys/bluetooth/host/shell/bt_shell_private.c:55]: That seems to be inconsistent with `bt_shell_wall_vfprintf` which servers the same purpose, but has `wall` in the name, right?

File: subsys/bluetooth/host/shell/bt_shell_private.h [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+void bt_shell_hexdump(const uint8_t *data, size_t len);
+
+/**
+ * @brief Prints the current command help.
+ * (Bluetooth context specific)
+ *
+ * Function will print a help string with: the currently entered command
+ * and subcommands (if they exist).
+ */
+void bt_shell_help(void);
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt_shell_private.h:57]: `bt_shell_help` should only ever use the shell that tried to do something. I see that we have a case where `cmd_connect_le` is called from a callback. 

In that case (where `sh == NULL`), I would just not print this at all :) It's pretty useless in a callback (and with `wall`), since it related to a specific command.

File: subsys/bluetooth/host/shell/bt_shell_private.c [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+/*
+ * Copyright (c) 2024 Nordic Semiconductor ASA
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <zephyr/shell/shell_backend.h>
+#include "bt_shell_private.h"
+
+void bt_shell_wall_vfprintf(enum shell_vt100_color color, const char *fmt, va_list args)
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt_shell_private.c:17]:
```suggestion
static void wall_vfprintf(enum shell_vt100_color color, const char *fmt, va_list args)
```

File: subsys/bluetooth/host/shell/bt.c [hunk 5]
```diff
@@ -597,13 +597,13 @@ static void scan_recv(const struct bt_le_scan_recv_info *info, struct net_buf_si
...
-				cmd_scan_off(ctx_shell);
+				cmd_scan_off(NULL);
 
 				/* "name" is what would be in argv[0] normally */
-				cmd_scan_filter_clear_name(ctx_shell, 1, (char *[]){"name"});
+				cmd_scan_filter_clear_name(NULL, 1, (char *[]){"name"});
 
 				/* "connect" is what would be in argv[0] normally */
-				cmd_connect_le(ctx_shell, 1, (char *[]){"connect"});
+				cmd_connect_le(NULL, 1, (char *[]){"connect"});
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt.c:606]: I think it's troublesome that we call these shell command handlers with a NULL shell. 

I fully understand that without the `ctx_shell`, we do not have a shell to use in those cases, but I think that we may need to refactor these calls in a way that they do not require a shell then, i.e. move the functionality from `cmd_connect_le` in a new function that is shell-less, and then call that function both here and in `cmd_connect_le`. 

Otherwise we end up in a situation where we cannot always assume that `sh != NULL`, and then we need to add `sh == NULL` checks everywhere. 

This will also remove the need for the `bt_shell_help` function

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/shell/bt_shell_private.c (hunk 4 above)
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt_shell_private.c:17]: Got it will address on the next push

File: subsys/bluetooth/host/shell/bt_shell_private.c (hunk 2 above)
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt_shell_private.c:55]: |shell (variant)|bt_shell (variant) (before)|bt_shell (variant) (opt 1)|bt_shell (variant) (opt 2)|
|---|---|---|---|
|shell_fprintf   |bt_shell_fprintf   |bt_shell_fprintf   |bt_shell_**wall**_fprintf   |
|shell_fprintf_info|bt_shell_fprintf_info   |bt_shell_fprintf_info   |bt_shell_**wall**_fprintf_info   |
|shell_fprintf_print|bt_shell_fprintf_print   |bt_shell_fprintf_print   |bt_shell_**wall**_fprintf_print   |
|shell_fprintf_warn |bt_shell_fprintf_warn|bt_shell_fprintf_warn|bt_shell_**wall**_fprintf_warn|
|shell_fprintf_error|bt_shell_fprintf_error|bt_shell_fprintf_error|bt_shell_**wall**_fprintf_error|
|shell_hexdump|bt_shell_hexdump|bt_shell_**wall**_hexdump|bt_shell_**wall**_hexdump|
|shell_help|bt_shell_help|bt_shell_**wall**_help|bt_shell_**wall**_help|
|shell_info|bt_shell_info|bt_shell_info|bt_shell_**wall**_info|
|shell_print|bt_shell_print|bt_shell_print|bt_shell_**wall**_print|
|shell_warn|bt_shell_warn|bt_shell_warn|bt_shell_**wall**_warn|
|shell_error|bt_shell_error|bt_shell_error|bt_shell_**wall**_error|

---

Just bring out the table of print functions provided by `bt_shell_private.h`.
Which option are we going to choose: opt1, opt2, or something else?

File: subsys/bluetooth/host/shell/bt_shell_private.h (hunk 3 above)
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt_shell_private.h:57]: So, `bt_shell_help()` shouldn't be implemented, right? :)

Comment (Thalley) [reply subsys/bluetooth/host/shell/bt_shell_private.h:57]: I would say so, yeah. It's not useful to wall user errors :)

File: subsys/bluetooth/host/shell/bt_shell_private.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/host/shell/bt_shell_private.c:55]: Since they are all `wall` in the end, then either the current, or opt 2. 

The main issue I had is that we had a single function using the `wall` name which seemed inconsistent as they are all `wall` variants. 

Of course since `bt_shell_wall_vfprintf` was an internal/static function not exposed by the header, it is less of any issue. 

So I'm OK with the current version or opt 2

File: subsys/bluetooth/host/shell/bt.c (hunk 5 above)
Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c:606]: Yeah, this looks exactly what I hoped for :)

File: subsys/bluetooth/host/shell/bt_shell_private.c (hunk 2 above)
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt_shell_private.c:55]: Thanks for the insight! I'll go with the current version. 🫡

File: subsys/bluetooth/host/shell/bt.c [hunk 6]
```diff
@@ -595,15 +596,17 @@ static void scan_recv(const struct bt_le_scan_recv_info *info, struct net_buf_si
...
+				__maybe_unused int ercd;
+
 				auto_connect.connect_name = false;
 
-				cmd_scan_off(ctx_shell);
+				bt_do_scan_off();
 
 				/* "name" is what would be in argv[0] normally */
-				cmd_scan_filter_clear_name(ctx_shell, 1, (char *[]){"name"});
+				cmd_scan_filter_clear_name(NULL, 1, (char *[]){"name"});
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt.c:606]: Ditto; this should be a function so we don't call command handlers with a `NULL` sh

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/shell/bt.c [hunk 7]
```diff
@@ -227,18 +229,18 @@ static void active_scan_timeout(struct k_work *work)
...
-		shell_error(ctx_shell, "Failed to stop scan (err %d)", err);
+		bt_shell_error("Failed to stop scan (err %d)", err);
 	}
 
 #if defined(CONFIG_BT_CENTRAL)
 	if (auto_connect.connect_name) {
 		auto_connect.connect_name = false;
 		/* "name" is what would be in argv[0] normally */
-		cmd_scan_filter_clear_name(ctx_shell, 1, (char *[]){ "name" });
+		cmd_scan_filter_clear_name(NULL, 1, (char *[]){ "name" });
```
[the remark this answers is not in the document]
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt.c]: Got it

File: subsys/bluetooth/host/shell/bt.c (hunk 6 above)
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt.c]: Got it

**Comment by ndrs-pst** [comment]
Changes made as requested—hope this looks good!

**Review by Thalley — DISMISSED** [review]

**Comment by Thalley** [comment]
Excellent job and great that you updated it so fast :)

File: subsys/bluetooth/host/shell/bt_shell_private.c
[the remark this answers is not in the document]
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt_shell_private.c:1]: It's true that this C-file isn't Bluetooth-specific, but since it's designed to address a Bluetooth-related problem, keeping it focused on Bluetooth is fine for now. If similar needs arise elsewhere, it can be refactored into a generic API later.

🤞 Once this is merged, I'll open another PR for `audio/shell`, `mesh/shell`, and `classic/shell` too.

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/shell/bt_shell_private.c
[the remark this answers is not in the document]
Comment (jhedberg) [reply subsys/bluetooth/host/shell/bt_shell_private.c:1]: @jakub-uC @carlescufi any comments on this? How easily could this generic API be accepted as part of the shell subsystem?

[the remark this answers is not in the document]
Comment (jhedberg) [reply subsys/bluetooth/host/shell/bt_shell_private.c:1]: @jakub-uC @carlescufi I'm still waiting for some response to the above question.

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/shell/bt_shell_private.c:1]: Since the `ctx_shell` is only used in BT context, I think we can move forward with this PR. We can later port these to a non-BT place if there's any use for it

**Comment by Thalley** [comment]
@ndrs-pst I think this PR actually solves https://github.com/zephyrproject-rtos/zephyr/issues/41796 - Should we add `fixes https://github.com/zephyrproject-rtos/zephyr/issues/41796` in the PR description here?

File: subsys/bluetooth/host/shell/bt.c [hunk 8]
```diff
@@ -1783,9 +1788,9 @@ static int cmd_scan_filter_set_addr(const struct shell *sh, size_t argc,
 		uint8_t tmp;
 
 		if (c != ':' && char2hex(c, &tmp) < 0) {
-			shell_error(ctx_shell,
-					"Invalid address string: %s\n",
-					addr_arg);
+			shell_error(sh,
+				    "Invalid address string: %s\n",
+				    addr_arg);
```
Comment (jhedberg) [inline subsys/bluetooth/host/shell/bt.c:1793]: Can't this be just one line?

File: subsys/bluetooth/host/shell/bt.c [hunk 9]
```diff
@@ -125,8 +126,8 @@ static void print_le_addr(const char *desc, const bt_addr_le_t *addr)
 
 	bt_addr_le_to_str(addr, addr_str, sizeof(addr_str));
 
-	shell_print(ctx_shell, "%s address: %s (%s)", desc, addr_str,
-		    addr_desc);
+	bt_shell_print("%s address: %s (%s)", desc, addr_str,
+		       addr_desc);
```
Comment (jhedberg) [inline subsys/bluetooth/host/shell/bt.c:130]: Merge to one line?

File: subsys/bluetooth/host/shell/bt.c [hunk 10]
```diff
@@ -396,14 +395,14 @@ static bool data_verbose_cb(struct bt_data *data, void *user_data)
 		 * the rest is unknown and printed as single bytes
 		 */
 		if (data->data_len < BT_UUID_SIZE_32) {
-			shell_fprintf(ctx_shell, SHELL_WARNING,
-				      "BT_DATA_SVC_DATA32 data length too short (%u)",
-				      data->data_len);
+			bt_shell_fprintf_warn(
+				"BT_DATA_SVC_DATA32 data length too short (%u)",
+				data->data_len);
```
Comment (jhedberg) [inline subsys/bluetooth/host/shell/bt.c:400]: Seems like at least the string literal should be mergeable to the first line

File: subsys/bluetooth/host/shell/bt.c [hunk 11]
```diff
@@ -418,22 +417,22 @@ static bool data_verbose_cb(struct bt_data *data, void *user_data)
 		 * the rest is unknown and printed as single bytes
 		 */
 		if (data->data_len < BT_UUID_SIZE_128) {
-			shell_fprintf(ctx_shell, SHELL_WARNING,
-				      "BT_DATA_SVC_DATA128 data length too short (%u)",
-				      data->data_len);
+			bt_shell_fprintf_warn(
+				"BT_DATA_SVC_DATA128 data length too short (%u)",
+				data->data_len);
```
Comment (jhedberg) [inline subsys/bluetooth/host/shell/bt.c:422]: Same here

**Review by jhedberg — COMMENTED** [review]
Some style comments. I'm still a bit concerned with the total silence from the shell maintainers.

File: subsys/bluetooth/host/shell/bt.c [hunk 12]
```diff
@@ -857,8 +856,8 @@ static void identity_resolved(struct bt_conn *conn, const bt_addr_le_t *rpa,
 	bt_addr_le_to_str(identity, addr_identity, sizeof(addr_identity));
 	bt_addr_le_to_str(rpa, addr_rpa, sizeof(addr_rpa));
 
-	shell_print(ctx_shell, "Identity resolved %s -> %s", addr_rpa,
-	      addr_identity);
+	bt_shell_print("Identity resolved %s -> %s", addr_rpa,
+		       addr_identity);
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c:860]: Hmm, the way that it's formatted looks like clang-format, but where the line length is set to 80 instead of 100. Chances are that the author is using a misconfigured auto-formatter

**Comment by ndrs-pst** [comment]
> @ndrs-pst I think this PR actually solves #41796 - Should we add `fixes https://github.com/zephyrproject-rtos/zephyr/issues/41796` in the PR description here?

Got it.

File: subsys/bluetooth/host/shell/bt.c (hunk 12 above)
[the remark this answers is not in the document]
Comment (ndrs-pst) [reply subsys/bluetooth/host/shell/bt.c:860]: As far as I can recall, I used the in-tree `.clang-format` with some manual adjustments to align it with the previous one.
For the next push, I'll change it according to the clang-format suggestion.

**Review by Thalley — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
Approving, but there's potential cleanup still to be done in follow-up PRs (see my inline comments). Please also engage actively with the shell maintainers to make this a generic API eventually. Thanks.

File: subsys/bluetooth/host/shell/bt.c [hunk 13]
```diff
@@ -833,18 +824,18 @@ static void disconnected(struct bt_conn *conn, uint8_t reason)
...
 	return true;
 }
 
 static void le_param_updated(struct bt_conn *conn, uint16_t interval,
 			     uint16_t latency, uint16_t timeout)
 {
-	shell_print(ctx_shell, "LE conn param updated: int 0x%04x lat %d "
-		     "to %d", interval, latency, timeout);
+	bt_shell_print("LE conn param updated: int 0x%04x lat %d "
+		       "to %d", interval, latency, timeout);
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c:838]: Agreed. If the author has setup clang-format in their IDE with only formatting changed lines using the .clang-format from Zephyr, these would have been formatted like you want.

**Comment by ndrs-pst** [comment]
Thank you for the approval and feedback!
I'll address the potential cleanup you mentioned in a follow-up PR.
Cheers 🎉
