### PR TITLE
LE Audio: Unicast client release fix

### LINKED ISSUE #56110: LE Audio: BAP Unicast Client cannot release stream if server caches
**Describe the bug**
If we as the unicast client call `bt_bap_stream_release`, but the unicast server caches the ASE, then we never go into the idle state and the `bt_bap_stream_ops.released` callback is never called. Even if we call `bt_bap_stream_release` again for the same stream, it may just go into the codec configured state again. 

**To Reproduce**
N/A

**Expected behavior**
When calling `bt_bap_stream_release` we should, unless rejected by the server, consider the state change into codec configured the same way we do for the idle state, i.e. cleanup everything and call the `released` callback. 

**Impact**
If a unicast server caches the codec configuration, we will never be able to release a stream, which can be a showstopper as the only way out of this state is an ACL disconnect. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 82efb21e91a241d62608d5dd841fcadfc6afef96

**Additional context**
In the BAP unicast client implementation we already have the `release_requested` boolean which we should be able to utilize to handle state transitions into the codec configured state properly. 
Ideally it would something as simple as
```
if (release_requested) {
    consider stream released
} else {
    consider stream to be in codec configured state
}
```

### PR DESCRIPTION
**Pull request by Thalley**
Fixes an issue with releasing a stream as the unicast client. 

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/56110

### CODE REVIEW

File: subsys/bluetooth/audio/bap_unicast_client.c [hunk 1]
```diff
@@ -51,6 +50,7 @@ struct bt_bap_unicast_client_ep {
 
 	/* Bool to help handle different order of CP and ASE notification when releasing */
 	bool release_requested;
+	bool cp_ntf_pending;
```
Comment (larsgk) [inline subsys/bluetooth/audio/bap_unicast_client.c:53]: is this initialized somewhere?

**Review by MariuszSkamra — COMMENTED** [review]
LGTM, I've tested the peripheral side with this PR, haven't see any issues.
I'll approve once @larsgk comment will be resolved

File: subsys/bluetooth/audio/bap_unicast_client.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/audio/bap_unicast_client.c:53]: Nice catch - I had wrongly expected the `struct bt_bap_unicast_client_ep` to be memset on reset, but it only resets a few fields. 

Added initialization of `release_requested` and `cp_ntf_pending`

**Review by larsgk — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]

**Review by nashif — APPROVED** [review]
