### PR TITLE
arch: common: timing: Fix timing cycles 32bit rollover

### LINKED ISSUE #84051: tests: benchmarks: invalid queue timings on mps2/an385 (qemu)
**Describe the bug**
Invalid queue benchmark time measurements observed on mps2/an385 (qemu simulation).

**To Reproduce**
`twister -p mps2/an385 -vv -j 1 -T tests/benchmarks/sched_queues`
`twister -p mps2/an385 -vv -j 1 -T tests/benchmarks/wait_queues`
similar results for `mps2/an521/cpu0`

**Expected behavior**
correct time measurements and benchmark results.

**Impact**
* invalid benchmark values.
* possible incorrect timings on the platform(s)

**Logs and console output**
`twister -p mps2/an385 -vv -j 1 -T tests/benchmarks/sched_queues`
```
twister - DEBUG - run test: mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq
twister - DEBUG - Reset instance status from 'passed' to None before run.
twister - DEBUG - Spawning QEMUHandler Thread for mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq
twister - DEBUG - Running mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq (qemu)
twister - DEBUG - Spawning QEMUHandler Thread for mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq
twister - DEBUG - QEMU (1103361): *** Booting Zephyr OS build v4.0.0-3379-g0df6736bb9f6 ***
twister - DEBUG - QEMU (1103361): Time Measurements for multiq sched queues
twister - DEBUG - QEMU (1103361): Timing results: Clock frequency: 25 MHz
twister - DEBUG - QEMU (1103361): REC: sched.add.thread.ReadyQ_tail.min         - Add threads of decreasing priority, min.           :     393 cycles ,   15720 ns :
twister - DEBUG - QEMU (1103361): REC: sched.add.thread.ReadyQ_tail.max         - Add threads of decreasing priority, max.           : 18446744073693168 cycles , 3607117184 ns :
twister - DEBUG - QEMU (1103361): REC: sched.add.thread.ReadyQ_tail.avg         - Add threads of decreasing priority, avg.           :   39820 cycles , 1592800 ns :
twister - DEBUG - QEMU (1103361): REC: sched.add.thread.ReadyQ_tail.stddev      - Add threads of decreasing priority, stddev.        : 290614440 cycles , 3034643008 ns :
twister - DEBUG - QEMU (1103361): REC: sched.remove.thread.ReadyQ_head.min      - Remove threads of decreasing priority, min.        :     352 cycles ,   14080 ns :
twister - DEBUG - QEMU (1103361): REC: sched.remove.thread.ReadyQ_head.max      - Remove threads of decreasing priority, max.        : 18446744073676388 cycles , 3606445984 ns :
twister - DEBUG - QEMU (1103361): REC: sched.remove.thread.ReadyQ_head.avg      - Remove threads of decreasing priority, avg.        : 184467440735439 cycles , 3944431704 ns :
twister - DEBUG - QEMU (1103361): REC: sched.remove.thread.ReadyQ_head.stddev   - Remove threads of decreasing priority, stddev.     : 416111575 cycles , 3759561112 ns :
twister - DEBUG - QEMU (1103361): REC: sched.add.thread.ReadyQ_head.min         - Add threads of increasing priority, min.           :     393 cycles ,   15720 ns :
twister - DEBUG - QEMU (1103361): REC: sched.add.thread.ReadyQ_head.max         - Add threads of increasing priority, max.           : 18446744073676391 cycles , 3606446104 ns :
twister - DEBUG - QEMU (1103361): REC: sched.add.thread.ReadyQ_head.avg         - Add threads of increasing priority, avg.           : 184467440733462 cycles , 3944352624 ns :
twister - DEBUG - QEMU (1103361): REC: sched.add.thread.ReadyQ_head.stddev      - Add threads of increasing priority, stddev.        : 377361135 cycles , 2209543512 ns :
twister - DEBUG - QEMU (1103361): REC: sched.remove.thread.ReadyQ_tail.min      - Remove threads of increasing priority, min.        :     352 cycles ,   14080 ns :
twister - DEBUG - QEMU (1103361): REC: sched.remove.thread.ReadyQ_tail.max      - Remove threads of increasing priority, max.        : 18446744073676349 cycles , 3606444424 ns :
twister - DEBUG - QEMU (1103361): REC: sched.remove.thread.ReadyQ_tail.avg      - Remove threads of increasing priority, avg.        : 184467440734768 cycles , 3944404864 ns :
twister - DEBUG - QEMU (1103361): REC: sched.remove.thread.ReadyQ_tail.stddev   - Remove threads of increasing priority, stddev.     : 424670937 cycles , 4101935592 ns :
twister - DEBUG - QEMU (1103361): ===================================================================
twister - DEBUG - QEMU (1103361): PROJECT EXECUTION SUCCESSFUL
twister - DEBUG - HARNESS:Console:EXPECTED:'PROJECT EXECUTION SUCCESSFUL'
twister - DEBUG - QEMU (1103361) complete with passed (None) after 2.4397289752960205 seconds
twister - DEBUG - No timeout, return code from QEMU (None): 0
twister - DEBUG - return code from QEMU (None): 0
twister - DEBUG - run status: mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq passed

```

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain  Zephyr SDK 0.17.0
 - Commit SHA 0df6736

### PR DESCRIPTION
**Pull request by golowanow**
Fix arch_timing_cycles_get() to prevent overflow on 32bit cycles rollover.

The issue is observable, for example when `tests/benchmarks/wait_queues` or `tests/benchmarks/sched_queues` are executed on qemu for `mps2/an385` and the benchmark has its iterations large enough as the default `BENCHMARK_NUM_ITERATIONS=1000`.

Fixes #84051

### CODE REVIEW

**Comment by golowanow** [comment]
`twister -p mps2/an385 -vv -j 1 -T tests/benchmarks/sched_queues`
#### after the fix:
```
twister - DEBUG - run test: mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq
twister - DEBUG - Reset instance status from 'passed' to None before run.
twister - DEBUG - Spawning QEMUHandler Thread for mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq
twister - DEBUG - Running mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq (qemu)
twister - DEBUG - Spawning QEMUHandler Thread for mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq
twister - DEBUG - QEMU (1107691): *** Booting Zephyr OS build v4.0.0-3379-g0df6736bb9f6 ***
twister - DEBUG - QEMU (1107691): Time Measurements for multiq sched queues
twister - DEBUG - QEMU (1107691): Timing results: Clock frequency: 25 MHz
twister - DEBUG - QEMU (1107691): REC: sched.add.thread.ReadyQ_tail.min         - Add threads of decreasing priority, min.           :     393 cycles ,   15720 ns :
twister - DEBUG - QEMU (1107691): REC: sched.add.thread.ReadyQ_tail.max         - Add threads of decreasing priority, max.           : 4261807 cycles , 170472280 ns :
twister - DEBUG - QEMU (1107691): REC: sched.add.thread.ReadyQ_tail.avg         - Add threads of decreasing priority, avg.           :  383920 cycles , 15356800 ns :
twister - DEBUG - QEMU (1107691): REC: sched.add.thread.ReadyQ_tail.stddev      - Add threads of decreasing priority, stddev.        : 1219538 cycles , 48781520 ns :
twister - DEBUG - QEMU (1107691): REC: sched.remove.thread.ReadyQ_head.min      - Remove threads of decreasing priority, min.        :     352 cycles ,   14080 ns :
twister - DEBUG - QEMU (1107691): REC: sched.remove.thread.ReadyQ_head.max      - Remove threads of decreasing priority, max.        : 4261803 cycles , 170472120 ns :
twister - DEBUG - QEMU (1107691): REC: sched.remove.thread.ReadyQ_head.avg      - Remove threads of decreasing priority, avg.        :  298656 cycles , 11946240 ns :
twister - DEBUG - QEMU (1107691): REC: sched.remove.thread.ReadyQ_head.stddev   - Remove threads of decreasing priority, stddev.     : 1087289 cycles , 43491560 ns :
twister - DEBUG - QEMU (1107691): REC: sched.add.thread.ReadyQ_head.min         - Add threads of increasing priority, min.           :     393 cycles ,   15720 ns :
twister - DEBUG - QEMU (1107691): REC: sched.add.thread.ReadyQ_head.max         - Add threads of increasing priority, max.           : 4261807 cycles , 170472280 ns :
twister - DEBUG - QEMU (1107691): REC: sched.add.thread.ReadyQ_head.avg         - Add threads of increasing priority, avg.           :  341306 cycles , 13652240 ns :
twister - DEBUG - QEMU (1107691): REC: sched.add.thread.ReadyQ_head.stddev      - Add threads of increasing priority, stddev.        : 1156092 cycles , 46243680 ns :
twister - DEBUG - QEMU (1107691): REC: sched.remove.thread.ReadyQ_tail.min      - Remove threads of increasing priority, min.        :     352 cycles ,   14080 ns :
twister - DEBUG - QEMU (1107691): REC: sched.remove.thread.ReadyQ_tail.max      - Remove threads of increasing priority, max.        : 4261803 cycles , 170472120 ns :
twister - DEBUG - QEMU (1107691): REC: sched.remove.thread.ReadyQ_tail.avg      - Remove threads of increasing priority, avg.        :  341270 cycles , 13650800 ns :
twister - DEBUG - QEMU (1107691): REC: sched.remove.thread.ReadyQ_tail.stddev   - Remove threads of increasing priority, stddev.     : 1156092 cycles , 46243680 ns :
twister - DEBUG - QEMU (1107691): ===================================================================
twister - DEBUG - QEMU (1107691): PROJECT EXECUTION SUCCESSFUL
twister - DEBUG - HARNESS:Console:EXPECTED:'PROJECT EXECUTION SUCCESSFUL'
twister - DEBUG - QEMU (1107691) complete with passed (None) after 2.4361228942871094 seconds
twister - DEBUG - No timeout, return code from QEMU (None): 0
twister - DEBUG - return code from QEMU (None): 0
twister - DEBUG - run status: mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.multiq passed
```
#### instead of what is without the fix:
```
REC: sched.add.thread.ReadyQ_tail.min         - Add threads of decreasing priority, min.           :     393 cycles ,   15720 ns :
REC: sched.add.thread.ReadyQ_tail.max         - Add threads of decreasing priority, max.           : 18446744073693168 cycles , 3607117184 ns :
REC: sched.add.thread.ReadyQ_tail.avg         - Add threads of decreasing priority, avg.           :   39820 cycles , 1592800 ns :
REC: sched.add.thread.ReadyQ_tail.stddev      - Add threads of decreasing priority, stddev.        : 290614440 cycles , 3034643008 ns :
...
``` 

#### Although, the benchmark metrics on the simulated platform are weird/unstable
e.g. with `CONFIG_BENCHMARK_VERBOSE=y` it looks like this:
```
Time Measurements for multiq sched queues
Timing results: Clock frequency: 25 MHz
REC: sched.add.thread.ReadyQ_tail.min         - Add threads of decreasing priority, min.           :     387 cycles ,   15480 ns :
REC: sched.add.thread.ReadyQ_tail.max         - Add threads of decreasing priority, max.           : 4278577 cycles , 171143080 ns :
REC: sched.add.thread.ReadyQ_tail.avg         - Add threads of decreasing priority, avg.           :  384082 cycles , 15363280 ns :
REC: sched.add.thread.ReadyQ_tail.stddev      - Add threads of decreasing priority, stddev.        : 1220073 cycles , 48802920 ns :
ReadyQ.add.to.tail.0000.waiters          - Add thread of priority (0)     : 4261800 cycles , 170472023 ns
ReadyQ.add.to.tail.0001.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
ReadyQ.add.to.tail.0002.waiters          - Add thread of priority (0)     :     387 cycles ,    15490 ns
ReadyQ.add.to.tail.0003.waiters          - Add thread of priority (0)     :     387 cycles ,    15490 ns
ReadyQ.add.to.tail.0004.waiters          - Add thread of priority (0)     : 4261800 cycles , 170472000 ns
ReadyQ.add.to.tail.0005.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
ReadyQ.add.to.tail.0006.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
...
```

**Comment by golowanow** [comment]
> #### Although, the benchmark metrics on the simulated platform are weird/unstable
```
ReadyQ.add.to.tail.0003.waiters          - Add thread of priority (0)     :     387 cycles ,    15490 ns
ReadyQ.add.to.tail.0004.waiters          - Add thread of priority (0)     :  4261800 cycles , 170472000 ns
ReadyQ.add.to.tail.0005.waiters          - Add thread of priority (0)     :     387 cycles ,    15486 ns
```
as @gramsay0 [suggested](https://github.com/zephyrproject-rtos/zephyr/issues/84051#issuecomment-2593815811), these strange time spikes at `mps2/an385` can be mitigated with `CONFIG_SYS_CLOCK_TICKS_PER_SEC=3` as well as the overflow itself, but the overflow reappears when `BENCHMARK_NUM_ITERATIONS` is increased e.g. to `10000` (without the fix proposed):
```
Spawning QEMUHandler Thread for mps2/an385/zephyr/tests/benchmarks/sched_queues/benchmark.sched_queues.scalable
QEMU (1122946): *** Booting Zephyr OS build v4.0.0-3379-g0df6736bb9f6 ***
QEMU (1122946): Time Measurements for scalable sched queues
QEMU (1122946): Timing results: Clock frequency: 25 MHz
QEMU (1122946): REC: sched.add.thread.ReadyQ_tail.min         - Add threads of decreasing priority, min.           :     704 cycles ,   28160 ns :
QEMU (1122946): REC: sched.add.thread.ReadyQ_tail.max         - Add threads of decreasing priority, max.           :    1964 cycles ,   78560 ns :
QEMU (1122946): REC: sched.add.thread.ReadyQ_tail.avg         - Add threads of decreasing priority, avg.           :    1518 cycles ,   60720 ns :
QEMU (1122946): REC: sched.add.thread.ReadyQ_tail.stddev      - Add threads of decreasing priority, stddev.        :     224 cycles ,    8960 ns :
QEMU (1122946): REC: sched.remove.thread.ReadyQ_head.min      - Remove threads of decreasing priority, min.        :     496 cycles ,   19840 ns :
QEMU (1122946): REC: sched.remove.thread.ReadyQ_head.max      - Remove threads of decreasing priority, max.        :    1571 cycles ,   62840 ns :
QEMU (1122946): REC: sched.remove.thread.ReadyQ_head.avg      - Remove threads of decreasing priority, avg.        :    1081 cycles ,   43240 ns :
QEMU (1122946): REC: sched.remove.thread.ReadyQ_head.stddev   - Remove threads of decreasing priority, stddev.     :     232 cycles ,    9280 ns :
QEMU (1122946): REC: sched.add.thread.ReadyQ_head.min         - Add threads of increasing priority, min.           :     691 cycles ,   27640 ns :
QEMU (1122946): REC: sched.add.thread.ReadyQ_head.max         - Add threads of increasing priority, max.           :    1824 cycles ,   72960 ns :
QEMU (1122946): REC: sched.add.thread.ReadyQ_head.avg         - Add threads of increasing priority, avg.           :    1388 cycles ,   55520 ns :
QEMU (1122946): REC: sched.add.thread.ReadyQ_head.stddev      - Add threads of increasing priority, stddev.        :     241 cycles ,    9640 ns :
QEMU (1122946): REC: sched.remove.thread.ReadyQ_tail.min      - Remove threads of increasing priority, min.        :     496 cycles ,   19840 ns :
QEMU (1122946): REC: sched.remove.thread.ReadyQ_tail.max      - Remove threads of increasing priority, max.        : 1844674406942457 cycles , 773134056 ns :
QEMU (1122946): REC: sched.remove.thread.ReadyQ_tail.avg      - Remove threads of increasing priority, avg.        : 18446744070582 cycles , 2971305072 ns :
QEMU (1122946): REC: sched.remove.thread.ReadyQ_tail.stddev   - Remove threads of increasing priority, stddev.     : 346412746 cycles , 971607952 ns :
```

**Comment by gramsay0** [comment]
@golowanow good point, this is a separate bug.

Since `arch_timing_counter_get` uses `k_cycle_get_32` maybe `arch_timing_cycles_get` should just be:
```
return ((uint32_t)*end - (uint32_t)*start);
```
i.e. the same as https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/arm/core/cortex_m/timing.c#L106

**Comment by golowanow** [comment]
> ```
> return ((uint32_t)*end - (uint32_t)*start);
> ```
yeah, the benchmark works the same way with it:
```
Time Measurements for multiq sched queues
Timing results: Clock frequency: 25 MHz
REC: sched.add.thread.ReadyQ_tail.min         - Add threads of decreasing priority, min.           :     387 cycles ,   15480 ns :
REC: sched.add.thread.ReadyQ_tail.max         - Add threads of decreasing priority, max.           : 4261800 cycles , 170472000 ns :
REC: sched.add.thread.ReadyQ_tail.avg         - Add threads of decreasing priority, avg.           :  213457 cycles , 8538280 ns :
REC: sched.add.thread.ReadyQ_tail.stddev      - Add threads of decreasing priority, stddev.        :  928753 cycles , 37150120 ns :
ReadyQ.add.to.tail.0000.waiters          - Add thread of priority (0)     :     387 cycles ,    15487 ns
ReadyQ.add.to.tail.0001.waiters          - Add thread of priority (0)     :     387 cycles ,    15483 ns
...
ReadyQ.add.to.tail.0028.waiters          - Add thread of priority (4)     :     387 cycles ,    15496 ns
ReadyQ.add.to.tail.0029.waiters          - Add thread of priority (4)     : 4261799 cycles , 170471998 ns
ReadyQ.add.to.tail.0030.waiters          - Add thread of priority (4)     :     387 cycles ,    15487 ns
ReadyQ.add.to.tail.0031.waiters          - Add thread of priority (4)     :     387 cycles ,    15483 ns
ReadyQ.add.to.tail.0032.waiters          - Add thread of priority (4)     :     387 cycles ,    15488 ns
ReadyQ.add.to.tail.0033.waiters          - Add thread of priority (4)     :     387 cycles ,    15496 ns
ReadyQ.add.to.tail.0034.waiters          - Add thread of priority (4)     :     387 cycles ,    15484 ns
ReadyQ.add.to.tail.0035.waiters          - Add thread of priority (5)     : 4261800 cycles , 170472024 ns
ReadyQ.add.to.tail.0036.waiters          - Add thread of priority (5)     :     387 cycles ,    15483 ns
ReadyQ.add.to.tail.0037.waiters          - Add thread of priority (5)     :     387 cycles ,    15488 ns
...
```

**Review by gramsay0 — DISMISSED** [review]

File: arch/common/timing.c [hunk 1]
```diff
@@ -28,7 +28,7 @@ timing_t arch_timing_counter_get(void)
 uint64_t arch_timing_cycles_get(volatile timing_t *const start,
 				volatile timing_t *const end)
 {
-	return (*end - *start);
+	return ((uint32_t)*end - (uint32_t)*start);
```
Comment (hakehuang) [inline arch/common/timing.c:31]: why limited to uint32? the timing_t may be uint64_t

Comment (golowanow) [reply arch/common/timing.c:31]: > why limited to uint32? the timing_t may be uint64_t

`arch_timing_counter_get()` is already 32bit here (`k_cycle_get_32()`)  isn't it ?

Comment (hakehuang) [reply arch/common/timing.c:31]: typedef uint64_t timing_t;

Comment (peter-mitsis) [reply arch/common/timing.c:31]: As I understand it, arch_timing_counter_get() uses k_cycle_get_32() because we can not be certain that architecture supports k_cycle_get_64().

What if we did something like ...

```
timing_t arch_timing_counter_get(void)
{
#if CONFIG_TIMER_HAS_64BIT_CYCLE_COUNTER
	return k_cycle_get_64();
#else
	return k_cycle_get_32();
#endif
}

uint64_t arch_timing_cycles_get(volatile timing_t *const start,
				volatile timing_t *const end)
{
#if CONFIG_TIMER_HAS_64BIT_CYCLE_COUNTER
	return (*end - *start);
#else
	return ((uint32_t)*end - (uint32_t)*start);
#endif

}
```

This would then allow us to get the 64-bit behavior if it is available, but still fall back to 32-bit behavior if it is not.

Comment (golowanow) [reply arch/common/timing.c:31]: yeah, it should be better to have ifdefed 32/64 bit variants. i'll try to change both these functions this way.

**Review by gramsay0 — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
