### PR TITLE
modem: fix socket descriptor leak

### LINKED ISSUE #26819: drivers: modem: SARA modem driver leaks sockets
**Describe the bug**
When calling `close` on a socket, the ublox sara driver only issues the `+USOCL` command if the socket is UDP, or if it's TCP *and* connected.

I am porting existing POSIX software to Zephyr. This code calls `close()` on a socket descriptor if `connect()` fails. The result on Zephyr is that the sockets allocated internally by the module are never released. On Linux the file descriptor will be released.

**To Reproduce**
1. Use the SARA-R4 driver
2. Create a TCP socket with `socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)`
3. Note the ID of the socket (modem logging helps)
4. Call `close` on the socket
5. See that the socket is not released, no `+USOCL` is issued to the module
6. Repeat step 2
7. See that a new, different socket is allocated by the module. There are now two existing sockets inside the SARA.

**Expected behavior**
Calling `close` on a socket should release its resources, independent on whether it is connected or not.

**Impact**
Eventually the module runs out of internal sockets and new `socket` calls fail. The R4 only supports 7 sockets.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain gnuarmemb
 -  a18a73c19b (master as of the creation of this ticket)

### PR DESCRIPTION
**Pull request by peltsu**
`z_free_fd()` is called twice then you `close()`. For example in ublox sara r4 driver `offload_close()` calls  `modem_socket_put()` where `z_free_fd()` is called first time. Then this same function is called another time in socket.c in `z_impl_zsock_close()` after this function has called `offload_close()` in ublox sara r4 driver. This causes socket descriptor leak. 

Fixes #26819

Signed-off-by: peltsu1324@gmail.com

### CODE REVIEW

File: drivers/modem/modem_socket.c [hunk 1]
```diff
@@ -233,7 +233,6 @@ void modem_socket_put(struct modem_socket_config *cfg, int sock_fd)
```
Comment (jukkar) [inline drivers/modem/modem_socket.c:233]: You need to fix the commit subject and body.
Write there something like:
```
modem: fix socket descriptor leak

z_free_fd() is called twice then you close(). For example in ublox sara r4 driver
offload_close() calls modem_socket_put() where z_free_fd() is called first time.
Then this same function is called another time in socket.c in z_impl_zsock_close()
after this function has called offload_close() in ublox sara r4 driver.
This causes socket descriptor leak.

Fixes #26819

Signed-off-by: <here your mail etc>
```

**Comment by jukkar** [comment]
> [peltsu](/peltsu) changed the title ~fix modem socket descriptor leak~ modem: fix socket descriptor leak

Unfortunately github does not propagate changes in PR description to the actual commit. You will need to force push a new version of the patch.

**Comment by jukkar** [comment]
@peltsu sorry for long delay. The signed-off-by line needs tweaking, the sanitychecker now complains about
```
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

a4f50ed8df92d70c52dd890a19f25984b48d4751: author email (Akseli <akseli.peltola@wizense.com>) needs to match one of the signed-off-by entries.
a4f50ed8df92d70c52dd890a19f25984b48d4751: author email (Akseli <akseli.peltola@wizense.com>) does not follow the syntax: First Last <email>.
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details
```

**Review by jukkar — APPROVED** [review]
Sorry, I had totally missed this PR.

**Review by mniestroj — APPROVED** [review]
LGTM
