### PR TITLE
drivers/flash/nrf_qspi_nor: Fix qspi_sfdp_read error path

### LINKED ISSUE #39923: qspi_sfdp_read fails errata work around
The ERRATA workaround returns 0 at (when using a NRF53 for example):
https://github.com/zephyrproject-rtos/zephyr/blob/54516743732a081deda5b32339f850bf89e69846/drivers/flash/nrf_qspi_nor.c#L64

In all cases of using this define the result is tested against 0. But at https://github.com/zephyrproject-rtos/zephyr/blob/54516743732a081deda5b32339f850bf89e69846/drivers/flash/nrf_qspi_nor.c#L772
it is tested against NRFX_SUCCESS which is not 0 but has a offset.

### PR DESCRIPTION
**Pull request by de-nordic**
The commit fixes processing of a return value from the ANOMALY_122_INIT
call.

Fixes #39923.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Comment by de-nordic** [comment]
@Driesdenijs please take a look.

**Review by nvlsianpu — COMMENTED** [review]
This patch does much more than mentioned in the only commit message.

I think that fixing issue of testing the return value of ANOMALY_122_init in place where
it was incorrect would be enough, but give me a few minutes to analyze by myself.

File: drivers/flash/nrf_qspi_nor.c [hunk 1]
```diff
@@ -357,14 +357,13 @@ static void qspi_handler(nrfx_qspi_evt_t event, void *p_context)
 #if NRF52_ERRATA_122_PRESENT
 static bool qspi_initialized;
 
-static int anomaly_122_init(const struct device *dev)
+static nrfx_err_t anomaly_122_init(const struct device *dev)
```
Comment (anangl) [inline drivers/flash/nrf_qspi_nor.c:360]: I see no benefit in changing the type of `anomaly_122_init` return value. This function is not a part of nrfx, so there is no need for it to return an `nrfx_err_t` value. 
Fixing of #39923, as mentioned in its description, requires only correction in this line: https://github.com/zephyrproject-rtos/zephyr/blob/54516743732a081deda5b32339f850bf89e69846/drivers/flash/nrf_qspi_nor.c#L772 so I don't see the point in making that many modifications as this PR does.

**Review by anangl — CHANGES_REQUESTED** [review]

File: drivers/flash/nrf_qspi_nor.c [hunk 2]
```diff
@@ -603,11 +603,13 @@ static int qspi_sfdp_read(const struct device *dev, off_t offset,
 		.io3_level = true,
 	};
 
-	int res = ANOMALY_122_INIT(dev);
+	int ret = ANOMALY_122_INIT(dev);
+	int res = NRFX_SUCCESS;
```
Comment (anangl) [inline drivers/flash/nrf_qspi_nor.c:607]:
```suggestion
	nrfx_err_t res = NRFX_SUCCESS;
```

**Review by anangl — APPROVED** [review]

File: drivers/flash/nrf_qspi_nor.c [hunk 3]
```diff
@@ -603,11 +603,13 @@ static int qspi_sfdp_read(const struct device *dev, off_t offset,
...
 
-	int res = ANOMALY_122_INIT(dev);
+	int ret = ANOMALY_122_INIT(dev);
+	nrfx_err_t res = NRFX_SUCCESS;
 
-	if (res != NRFX_SUCCESS) {
-		LOG_DBG("ANOMALY_122_INIT: %x", res);
-		goto out;
+	if (ret != 0) {
+		LOG_DBG("ANOMALY_122_INIT: %x", ret);
```
Comment (anangl) [inline drivers/flash/nrf_qspi_nor.c:610]:
```suggestion
		LOG_DBG("ANOMALY_122_INIT: %d", ret);
```

Comment (de-nordic) [reply drivers/flash/nrf_qspi_nor.c]: Fixed.

**Comment by de-nordic** [comment]
@nvlsianpu @carlescufi  please review.

**Review by carlescufi — APPROVED** [review]
