### PR TITLE
drivers: can: sjw == 0 in can_set_timing should not change sjw

### LINKED ISSUE #32331: Use of unitialized variables in can_set_bitrate()
**Describe the bug**
The function can_set_bitrate() doesn't set timing.sjw and timing_data.sjw. 
The variables are uninitialized and parsed to can_set_timing(), which uses the uninitialized values to set sjw parameters.
Functions that calls can_set_bitrate() will also have this bug. (i.e. can_configure()).

The function was added in pull request #28345.

**To Reproduce**
west build -p auto -b ... samples/subsys/canbus/canopen
(I'm working on a board that hasn't yet been upstreamed)

### PR DESCRIPTION
**Pull request by alexanderwachter**
If the supplied sjw in the timing parameters is zero,
the sjw parameter should not be changed.
This fixes the uninitialized swj in can_set_bitrate.

Fix: #32331

### CODE REVIEW

**Comment by alexanderwachter** [comment]
@henrikbrixandersen @karstenkoenig can you test on HW.

ping @talih0

**Comment by talih0** [comment]
> swj

nit typo in commit message

File: include/drivers/can.h [hunk 1]
```diff
@@ -728,12 +730,16 @@ static inline int can_set_bitrate(const struct device *dev,
 		return -EINVAL;
 	}
 
+	timing.sjw = 0;
```
Comment (karstenkoenig) [inline include/drivers/can.h:733]: I don't know, this seems sort of hacky way to do it. 
Only to allow 0 as a valid value for timing.sjw all `set_timing` functions get some backup storage for an old sjw value that should be properly initialized but isn't really guaranteed to be. In the mcp2515 case it will be initialized to 0 which is valid (sjw of 1), but even that made me wonder if I am missing a detail.
Wouldn't the proper change be to add a sjw parameter to can_set_bitrate? Don't want to break the interface eh?

**Comment by karstenkoenig** [comment]
> @henrikbrixandersen @karstenkoenig can you test on HW.
> 
> ping @talih0

Sorry I actually can't properly test on HW right now, I only have a single device I can operate in loopback and that already missed the frequency scaler issue that caused https://github.com/zephyrproject-rtos/zephyr/issues/33978 :-(
I'll need to get myself a more trusted slcan device so I can test against that

File: include/drivers/can.h (hunk 1 above)
Comment (alexanderwachter) [reply include/drivers/can.h:733]: The sjw always gets initialized by the device-tree. That is why the approach is valid. The reason why I don't want to have a parameter is that the user would have to extract it from the device-tree or come up with a new value. Not changing it was the best solution IMO.

Comment (karstenkoenig) [reply include/drivers/can.h:733]: Fair enough I forgot that it is always required in the devicetree. Could you instead of plain 0 add a define to the can.h header?
#define CAN_SJW_NOCHANGE 0?

I find the code really hard to read when just comparing against 0, then it at least makes sense what the intention is in the drivers

File: drivers/can/can_mcp2515.c [hunk 2]
```diff
@@ -335,8 +335,11 @@ static int mcp2515_set_timing(const struct device *dev,
 	/* CNF1; SJW<7:6> | BRP<5:0> */
 	__ASSERT(timing->prescaler > 0, "Prescaler should be bigger than zero");
 	uint8_t brp = timing->prescaler - 1;
-	const uint8_t sjw = (timing->sjw - 1) << 6;
-	uint8_t cnf1 = sjw | brp;
+	if (timing->sjw > 0) {
+		dev_data->sjw = (timing->sjw - 1) << 6;
```
Comment (karstenkoenig) [inline drivers/can/can_mcp2515.c:339]: Can you move the assert check into here instead of checking it for a wider range? Then it's still aligned with the datasheet and the 0 / CAN_SJW_NOCHANGE could just be ignored cleanly
```suggestion
		__ASSERT((timing->sjw >= 1) && (timing->sjw <= 4),
		"1 <= SJW <= 4");
		dev_data->sjw = (timing->sjw - 1) << 6;
```

File: drivers/can/can_mcp2515.c [hunk 3]
```diff
@@ -363,8 +366,7 @@ static int mcp2515_set_timing(const struct device *dev,
 	const uint8_t rx0_ctrl = BIT(6) | BIT(5) | BIT(2);
 	const uint8_t rx1_ctrl = BIT(6) | BIT(5);
 
-	__ASSERT((timing->sjw >= 1) && (timing->sjw <= 4),
-		 "1 <= SJW <= 4");
+	__ASSERT(timing->sjw <= 4, "1 <= SJW <= 4");
```
Comment (karstenkoenig) [inline drivers/can/can_mcp2515.c:369]:
```suggestion
```

**Review by karstenkoenig — CHANGES_REQUESTED** [review]
Please consider using a macro with a name instead of plain 0 to indicate the special case :-)

**Comment by galak** [comment]
@alexanderwachter any updates here?

**Comment by henrikbrixandersen** [comment]
@alexanderwachter ping?

File: include/drivers/can.h (hunk 1 above)
Comment (alexanderwachter) [reply include/drivers/can.h]: Done

File: drivers/can/can_mcp2515.c (hunk 3 above)
Comment (alexanderwachter) [reply drivers/can/can_mcp2515.c:369]: Why removing this check?

**Review by henrikbrixandersen — APPROVED** [review]

File: drivers/can/can_mcp2515.c (hunk 3 above)
Comment (karstenkoenig) [reply drivers/can/can_mcp2515.c:369]: I suggested to move it into the section where `dev_data->sjw` actually gets written, into the `if (timing->sjw != CAN_SJW_NO_CHANGE)` block
but it's ok the way it is

**Review by karstenkoenig — APPROVED** [review]

File: include/drivers/can.h (hunk 1 above)
Comment (karstenkoenig) [reply include/drivers/can.h]: thanks :+1:

**Comment by karstenkoenig** [comment]
Did a quick trial run with a pca10100 dk from nordic + mcp2515 and an slcan based peer
