### PR TITLE
drivers: usb: udc: Add SAM USBC driver

### LINKED ISSUE #74665: Port `usb_dc_sam_usbc` to `USB_DEVICE_STACK_NEXT`
In order for the `USB_DEVICE_STACK_NEXT` to become the default, existing USB device drivers must be ported to it.
See #42066 for additional details.

Note that if this driver is not ported by Zephyr 4.0.0, this hardware will not work with the default USB stack in 4.0.0.

### PR DESCRIPTION
**Pull request by nandojve**
## Summary

  Add USB Device (USBC) driver for SAM4L enabling USB device_next stack support for these MCUs.

  - New USBC driver: `drivers/usb/udc/udc_sam_usbc.c`
  - Supports Full-Speed (12 Mbps)
  - Direct DMA
  - Remote wakeup support

  ## Test Plan

  - [x] CDC ACM sample tested on sam4l_ek
  - [x] usbtest validation passed

  Fixes: #74665
  ~~Depends on: #103769~~

### CODE REVIEW

File: drivers/usb/udc/Kconfig.sam_usbc [hunk 1]
```diff
@@ -0,0 +1,27 @@
+# Copyright (c) 2025-2026 Gerson Fernando Budke <nandojve@gmail.com>
+# SPDX-License-Identifier: Apache-2.0
+
+config UDC_SAM_USBC
+	bool "Driver for SAM USBC family USB device controller"
```
Comment (JarmouniA) [inline drivers/usb/udc/Kconfig.sam_usbc]:
```suggestion
	bool "SAM USBC family USB device controller driver"
```
non-blocking

File: tests/subsys/secure_storage/psa/its/src/main.c [hunk 2]
```diff
@@ -9,11 +9,10 @@
 
 /* The flash must be erased after this test suite is run for the write-once entry test to pass. */
 #if !defined(CONFIG_BUILD_WITH_TFM) && defined(CONFIG_FLASH_PAGE_LAYOUT) &&                        \
-	DT_HAS_CHOSEN(zephyr_flash_controller) &&                                                  \
 	DT_FIXED_PARTITION_EXISTS(DT_NODELABEL(storage_partition))
 static int erase_flash(void)
 {
-	const struct device *const fdev = DEVICE_DT_GET(DT_CHOSEN(zephyr_flash_controller));
+	const struct device *const fdev = FIXED_PARTITION_DEVICE(storage_partition);
```
Comment (JarmouniA) [inline tests/subsys/secure_storage/psa/its/src/main.c]:
```suggestion
	const struct device *const fdev = FIXED_PARTITION_MTD(storage_partition);
```

**Review by JarmouniA — DISMISSED** [review]

File: tests/subsys/secure_storage/psa/its/src/main.c
Comment (tomi-font) [inline tests/subsys/secure_storage/psa/its/src/main.c:1]: cc @petejohanson-adi

File: tests/subsys/secure_storage/psa/its/src/main.c (hunk 2 above)
Comment (tomi-font) [reply tests/subsys/secure_storage/psa/its/src/main.c]: +1

File: tests/subsys/secure_storage/psa/its/src/main.c
Comment (jfischer-no) [reply tests/subsys/secure_storage/psa/its/src/main.c:1]: @nandojve Please move this commit to own PR to not block it or this PR.

File: dts/bindings/usb/atmel,sam-usbc.yaml [hunk 3]
```diff
@@ -1,5 +1,5 @@
 # Copyright (c) 2018 Aurelien Jarno
-# Copyright (c) 2020*2023 Gerson Fernando Budke <nandojve@gmail.com>
+# Copyright (c) 2020-2026 Gerson Fernando Budke <nandojve@gmail.com>
```
Comment (jfischer-no) [inline dts/bindings/usb/atmel,sam-usbc.yaml]: It do not seems to be necessary to change this line. btw, it can be just
`# Copyright Gerson Fernando Budke <nandojve@gmail.com>`, https://docs.zephyrproject.org/latest/contribute/guidelines.html#copyright-and-license-notices

File: drivers/usb/udc/udc_sam_usbc.c [hunk 4]
```diff
@@ -0,0 +1,1589 @@
...
+#include <zephyr/drivers/pinctrl.h>
+#include <zephyr/drivers/usb/udc.h>
+#include <zephyr/sys/barrier.h>
+
+#include <zephyr/logging/log.h>
+LOG_MODULE_REGISTER(udc_sam_usbc, CONFIG_UDC_DRIVER_LOG_LEVEL);
+
+#define DT_DRV_COMPAT atmel_sam_usbc
+
+typedef Usbc Usbc_t;
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c]: Please do not add yet another typedef.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 5]
```diff
@@ -0,0 +1,1589 @@
...
+	};
+	uint32_t bk_ctrl_stat;
+	uint32_t ep_ctrl_stat;
+};
+
+BUILD_ASSERT(sizeof(struct sam_usbc_desc_table) == NUM_OF_EP_MAX * 2,
+	     "Broken endpoint buffer descriptor");
+
+struct udc_sam_usbc_config {
+	volatile Usbc_t *base;
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c]: `Usbc *base;`, volatile should not be necessary. All the `__I`, `__O`, and `__IO` in Usbc should expand to volatile. The driver do not use base to access anything.

File: tests/subsys/secure_storage/psa/its/src/main.c
Comment (nandojve) [reply tests/subsys/secure_storage/psa/its/src/main.c:1]: #103769

File: drivers/usb/udc/udc_sam_usbc.c [hunk 6]
```diff
@@ -0,0 +1,1589 @@
...
+	for (int ep = 0; ep < NUM_OF_EP_MAX; ep++) {
+		priv->bank_buf[ep][0] = NULL;
+		priv->bank_buf[ep][1] = NULL;
+	}
+}
+
+/*
+ * Physical endpoint allocation for REPNB redirection.
+ *
+ * The SAM USBC uses REPNB (Redirected Endpoint Number) to allow virtual
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c:216]: Honestly, I did not believe it until I found "virtual endpoints" in the datasheet.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 7]
```diff
@@ -0,0 +1,1589 @@
...
+
+	{
+		struct sam_usbc_desc_table *dt = sam_usbc_get_desc(dev, 0, 0);
+
+		LOG_DBG("EP0 desc: addr=%p setup=%p sizes=%08x",
+			(void *)dt->ep_pipe_addr, (void *)priv->setup,
+			dt->sizes);
+		LOG_DBG("EP0 regs: UECFG[0]=%08x UECON[0]=%08x UERST=%08x",
+			base->UECFG[0], base->UECON[0], base->UERST);
+	}
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c]: Please move it to something like `static inline void udc_sam_ep0_desc_dbg()`, or just move `struct sam_usbc_desc_table *dt = sam_usbc_get_desc(dev, 0, 0);` to the top of the function.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 8]
```diff
@@ -0,0 +1,1589 @@
...
+
+	udc_unlock_internal(dev);
+}
+
+/* Handle SETUP packet reception in ISR */
+static void sam_usbc_handle_setup_isr(const struct device *dev)
+{
+	const struct udc_sam_usbc_config *config = dev->config;
+	struct udc_sam_usbc_data *priv = udc_get_private(dev);
+	volatile Usbc_t *base = config->base;
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c]: Please check all the 'volatile' usage, it should not be necessary.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 9]
```diff
@@ -0,0 +1,1589 @@
...
+{
+	base->USBCON &= ~USBC_USBCON_FRZCLK;
+
+	while (base->USBCON & USBC_USBCON_FRZCLK) {
+		;
+	}
+}
+
+static inline struct sam_usbc_desc_table *sam_usbc_get_desc(
+	const struct device *dev, const uint8_t ep_idx, const uint8_t bank)
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c]: Maybe just wrap parameters.
```diff
diff --git a/drivers/usb/udc/udc_sam_usbc.c b/drivers/usb/udc/udc_sam_usbc.c
index 1394c82509b..a9d835289bc 100644
--- a/drivers/usb/udc/udc_sam_usbc.c
+++ b/drivers/usb/udc/udc_sam_usbc.c
@@ -189,8 +189,9 @@ static ALWAYS_INLINE void sam_usbc_unfreeze_clk(volatile Usbc_t *const base)
 	}
 }
 
-static inline struct sam_usbc_desc_table *sam_usbc_get_desc(
-	const struct device *dev, const uint8_t ep_idx, const uint8_t bank)
+static inline struct sam_usbc_desc_table *sam_usbc_get_desc(const struct device *dev,
+							    const uint8_t ep_idx,
+							    const uint8_t bank)
 {
 	const struct udc_sam_usbc_config *config = dev->config;
 

```

File: drivers/usb/udc/udc_sam_usbc.c [hunk 10]
```diff
@@ -0,0 +1,1589 @@
...
+	 * [phys_ep][bank_idx] where bank_idx is 0 or 1 for dual-bank.
+	 */
+	struct net_buf *bank_buf[NUM_OF_EP_MAX][2];
+	/*
+	 * Physical endpoint allocation tracking for REPNB redirection.
+	 * When virtual EP IN and OUT have same number (e.g., 0x81 and 0x01),
+	 * they must use different physical endpoints. REPNB redirects
+	 * transactions for virtual EP m to physical EP n.
+	 */
+	uint8_t phys_ep_used;           /* Bitmask of allocated physical EPs */
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c]: Perhaps it makes sense to move it to the end of the struct to avoid holes.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 11]
```diff
@@ -0,0 +1,1589 @@
...
+ */
+static uint32_t dev_ep_sta_dbg[2][NUM_OF_EP_MAX];
+
+static void sam_usbc_isr_sta_dbg(volatile Usbc_t *base, uint8_t ep_idx, uint32_t sr)
+{
+	if (base->UESTA[ep_idx] != dev_ep_sta_dbg[0][ep_idx]) {
+		dev_ep_sta_dbg[0][ep_idx] = base->UESTA[ep_idx];
+		dev_ep_sta_dbg[1][ep_idx] = 0;
+
+		LOG_INF("ISR[%d] CON=%08x INT=%08x INTE=%08x "
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c]: This is called from ISR context, do you really want it to be LOG_INF? It could be very verbose, INF is the default log level in Zephyr.

File: boards/atmel/sam/sam4l_ek/sam4l_ek.yaml [hunk 12]
```diff
@@ -19,5 +19,6 @@ supported:
   - spi
   - uart
   - usb_device
+  - usbd
```
Comment (jfischer-no) [inline boards/atmel/sam/sam4l_ek/sam4l_ek.yaml:22]: Can you add this board to a few integration_platforms of the samples/subsys/usb and tests/drivers/udc?

File: drivers/usb/udc/udc_sam_usbc.c [hunk 13]
```diff
@@ -0,0 +1,1589 @@
...
+static void sam_usbc_handle_ep_isr(const struct device *dev, const uint8_t ep_idx)
+{
+	const struct udc_sam_usbc_config *config = dev->config;
+	volatile Usbc_t *base = config->base;
+	uint32_t sr = base->UESTA[ep_idx];
+	uint32_t con = base->UECON[ep_idx];
+
+	if (IS_ENABLED(CONFIG_UDC_DRIVER_LOG_LEVEL_DBG)) {
+		sam_usbc_ep_isr_sta(base, ep_idx);
+	}
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c:823]: IIRC it will not work and there will be a build error. You need something like:https://github.com/zephyrproject-rtos/zephyr/blob/cb5b9e9a0586bd431372f2560200276f974dfae6/drivers/usb/udc/udc_common.c#L17-L21

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: dts/bindings/usb/atmel,sam-usbc.yaml (hunk 3 above)
Comment (nandojve) [reply dts/bindings/usb/atmel,sam-usbc.yaml]: I prefer keep the way it is.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 4 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: This `typedef` is necessary to comply with `cost *` format.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 5 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: dropped volatile

File: drivers/usb/udc/udc_sam_usbc.c (hunk 8 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: dropped volatile

File: drivers/usb/udc/udc_sam_usbc.c (hunk 10 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: done

File: drivers/usb/udc/udc_sam_usbc.c (hunk 9 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: done

File: drivers/usb/udc/Kconfig.sam_usbc (hunk 1 above)
Comment (nandojve) [reply drivers/usb/udc/Kconfig.sam_usbc]: done

File: drivers/usb/udc/udc_sam_usbc.c (hunk 7 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: fixed dropping first LOG_DBG()

File: drivers/usb/udc/udc_sam_usbc.c (hunk 11 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: fixed

File: boards/atmel/sam/sam4l_ek/sam4l_ek.yaml (hunk 12 above)
Comment (nandojve) [reply boards/atmel/sam/sam4l_ek/sam4l_ek.yaml:22]: I added in samples but in test is complete impossible because tests require a USB-HOST there!

File: drivers/usb/udc/udc_sam_usbc.c (hunk 13 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c:823]: I prefer keep it. The `if (IS_ENABLED(CONFIG_UDC_DRIVER_LOG_LEVEL_DBG)) {` is working very fine, no errors and no warnings.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 14]
```diff
@@ -0,0 +1,1584 @@
...
+	}									 \
+										 \
+	static struct sam_usbc_desc_table					 \
+		sam_usbc_dt_##n[DT_INST_PROP(n, num_bidir_endpoints) * 2]	 \
+		__aligned(16);							 \
+										 \
+	static struct udc_ep_config						 \
+		ep_cfg_out_##n[DT_INST_PROP(n, num_bidir_endpoints)];		 \
+	static struct udc_ep_config						 \
+		ep_cfg_in_##n[DT_INST_PROP(n, num_bidir_endpoints)];		 \
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c]: I wonder if these needs static initializers.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 15]
```diff
@@ -0,0 +1,1584 @@
...
+		k_thread_create(&priv->thread_data,				 \
+				udc_sam_usbc_stack_##n,				 \
+				K_THREAD_STACK_SIZEOF(udc_sam_usbc_stack_##n),	 \
+				udc_sam_usbc_thread_##n,			 \
+				(void *)dev, NULL, NULL,			 \
+				K_PRIO_COOP(CONFIG_UDC_SAM_USBC_THREAD_PRIORITY),\
+				K_ESSENTIAL,					 \
+				K_NO_WAIT);					 \
+		k_thread_name_set(&priv->thread_data, dev->name);		 \
+	}									 \
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c]: Are you interested in migrating to the new strategy for creating threads, which appeared just 2 month ago in https://github.com/zephyrproject-rtos/zephyr/pull/99685?

Then all of this can move out of the macro.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 16]
```diff
@@ -0,0 +1,1584 @@
...
+{
+	k_sched_lock();
+	udc_lock_internal(dev, K_FOREVER);
+}
+
+/* UDC API: Unlock */
+static void udc_sam_usbc_unlock(const struct device *dev)
+{
+	udc_unlock_internal(dev);
+	k_sched_unlock();
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c:1399]: Just to make sure I grasped the need for `k_sched_lock/unlock()`: this helps with making sure USB meets timing? What was making `udc_lock/unlock_internal()` unsufficient?

File: drivers/usb/udc/udc_sam_usbc.c [hunk 17]
```diff
@@ -0,0 +1,1584 @@
...
+/* Driver preinit - called at boot */
+static int udc_sam_usbc_driver_preinit(const struct device *dev)
+{
+	const struct udc_sam_usbc_config *config = dev->config;
+	struct udc_sam_usbc_data *priv = udc_get_private(dev);
+	struct udc_data *data = dev->data;
+	uint16_t mps = 1023;
+	int err;
+
+	k_mutex_init(&data->mutex);
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c]: Already done via `Z_MUTEX_INITIALIZER(udc_data_##n.mutex),`?

File: drivers/usb/udc/udc_sam_usbc.c [hunk 18]
```diff
@@ -0,0 +1,1584 @@
...
+
+	/* Enable USB Generic clock */
+	SCIF->GCCTRL[GEN_CLK_USBC] = 0;
+	SCIF->GCCTRL[GEN_CLK_USBC] = SCIF_GCCTRL_OSCSEL(SCIF_GC_USES_CLK_HSB) |
+				     SCIF_GCCTRL_CEN;
+
+	/* Wait for clock to be usable */
+	while (!(base->USBSTA & USBC_USBSTA_CLKUSABLE)) {
+		;
+	}
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c:1261]: Worth adding a timeout/sys_timepoint and return `-ETIMEDOUT`?

Clock issues are PCB prototypes usual culprits.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 19]
```diff
@@ -0,0 +1,1584 @@
...
+	/* Free the physical endpoint allocation */
+	free_phys_ep(dev, ep_cfg->addr);
+
+	LOG_DBG("Disable ep 0x%02x (was phys EP%d)", ep_cfg->addr, phys_ep);
+
+	return 0;
+}
+
+/* UDC API: Set endpoint halt (STALL) */
+static int udc_sam_usbc_ep_set_halt(const struct device *dev,
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c]: USB reviews often ask for `const struct device *const dev`, just in case this saves one review cycle.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 20]
```diff
@@ -0,0 +1,1584 @@
...
+{
+	/* SAM4L USBC only supports Full-Speed */
+	return UDC_BUS_SPEED_FS;
+}
+
+/* UDC API: Enable controller */
+static int udc_sam_usbc_enable(const struct device *dev)
+{
+	const struct udc_sam_usbc_config *config = dev->config;
+	Usbc_t *base = config->base;
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c]: I have seen some USB reviews ask for the "dispatch variables" made `* const`, possibly going to be asked here as well and on other static initializers.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 21]
```diff
@@ -0,0 +1,1584 @@
...
+	SAM_USBC_EVT_XFER_NEW,
+	/* Transfer for specific endpoint is finished */
+	SAM_USBC_EVT_XFER_FINISHED,
+};
+
+struct udc_sam_usbc_data {
+	struct k_thread thread_data;
+	struct k_event events;
+	atomic_t xfer_new;
+	atomic_t xfer_finished;
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c:78]: AFAIU, there is no TOCTOU problem between `events` and `xfer_new/finished` because the latter are atomic bitmasks, well handled throught he code, so bursts of several events never risk corrupting the logic.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 22]
```diff
@@ -0,0 +1,1584 @@
...
+	base->USBCON |= USBC_USBCON_FRZCLK;
+}
+
+static ALWAYS_INLINE void sam_usbc_unfreeze_clk(Usbc_t *const base)
+{
+	base->USBCON &= ~USBC_USBCON_FRZCLK;
+
+	while (base->USBCON & USBC_USBCON_FRZCLK) {
+		;
+	}
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c:184]: Proposing introducing a timeout in case this was not considered, not saying this is needed as no idea about how this particular hardware works.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 23]
```diff
@@ -0,0 +1,1584 @@
...
+	return ep_num;
+}
+
+/* Get physical EP for a virtual address, returns NOT_ALLOC_VIRT_EP if not allocated */
+static inline uint8_t virt_to_phys_ep(const struct device *dev, const uint8_t virt_addr)
+{
+	struct udc_sam_usbc_data *priv = udc_get_private(dev);
+
+	return priv->virt_to_phys[virt_addr_to_idx(virt_addr)];
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c:244]: If there are a lot of CDC ACM, could this return an invalid memory access? Worth adding an `__ASSERT()` in `virt_addr_to_idx()` just in case?

File: drivers/usb/udc/udc_sam_usbc.c [hunk 24]
```diff
@@ -0,0 +1,1584 @@
...
+	struct k_event events;
+	atomic_t xfer_new;
+	atomic_t xfer_finished;
+	/*
+	 * Per-endpoint per-bank buffer tracking for scatter-gather DMA.
+	 * Tracks which net_buf is assigned to each bank of each endpoint.
+	 * Required because we cannot derive net_buf* from buf->data alone.
+	 * [phys_ep][bank_idx] where bank_idx is 0 or 1 for dual-bank.
+	 */
+	struct net_buf *bank_buf[NUM_OF_EP_MAX][2];
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c]: Did I miss something or are these set but never read anywhere?
Does this mean it could go away?

File: drivers/usb/udc/udc_sam_usbc.c [hunk 25]
```diff
@@ -0,0 +1,1584 @@
...
+
+struct sam_usbc_desc_table {
+	uint8_t *ep_pipe_addr;
+	union {
+		uint32_t sizes;
+		struct sam_usbc_udesc_sizes udesc_sizes;
+	};
+	uint32_t bk_ctrl_stat;
+	uint32_t ep_ctrl_stat;
+};
```
Comment (josuah) [inline drivers/usb/udc/udc_sam_usbc.c:48]: Is this something passed to hardware? Does it mean `__packed` if so?

**Review by josuah — COMMENTED** [review]
Trying to move this driver review forward with some feedback.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 14 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: These are static arrays without explicit initializers, so they're BSS-zeroed by the C standard. The preinit function fully populates them (caps, addr, etc.) before they're used. Same pattern as every other UDC driver.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 24 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: This is used in the dual-bank design which is not implemented in this PR.
I complete remove to make this PR clean.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 22 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c:184]: Added a comment to make it clear.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 23 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c:244]: Done!

File: drivers/usb/udc/udc_sam_usbc.c (hunk 19 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: done

File: drivers/usb/udc/udc_sam_usbc.c (hunk 20 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: Done!

File: drivers/usb/udc/udc_sam_usbc.c (hunk 16 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c:1399]: Added comment to clarify

File: drivers/usb/udc/udc_sam_usbc.c (hunk 17 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: dropped the redundant one

File: drivers/usb/udc/udc_sam_usbc.c (hunk 15 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: I prefer do this in a follow up PR. I still need to implement more things and then I can move to the new pattern.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 25 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c:48]: This is a hardware DMA descriptor - the USBC peripheral reads/writes these directly. The fields are all naturally 32-bit aligned (pointer + three uint32_t), so the compiler won't insert padding. The BUILD_ASSERT already guards against unexpected sizing (must be exactly 16 bytes).

Adding **__packed** would:
  - Document the hardware contract explicitly
  - But could generate worse code (byte-by-byte access on some architectures) since **__packed** tells the compiler it can't assume alignment.

This is why I still prefer not add the **__packed**

Comment (josuah) [reply drivers/usb/udc/udc_sam_usbc.c:48]: Thank you for the walk-through that is interesting.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 14 above)
Comment (josuah) [reply drivers/usb/udc/udc_sam_usbc.c]: I completely forgot that, fooled myself from the presence of indentation... my bad.

Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: No worries, I'll send an update today with the fixes.

File: drivers/usb/udc/udc_sam_usbc.c [hunk 26]
```diff
@@ -0,0 +1,1578 @@
...
+	 * Must be 4-byte aligned for USB DMA to work correctly.
+	 * Must be the last field - DMA may overrun the buffer.
+	 */
+	uint8_t setup[8] __aligned(4);
+};
+
+BUILD_ASSERT(offsetof(struct udc_sam_usbc_data, setup) +
+	     sizeof(((struct udc_sam_usbc_data *)0)->setup) ==
+	     sizeof(struct udc_sam_usbc_data),
+	     "setup[] must be last field (DMA overrun protection)");
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_sam_usbc.c]: Perhaps it would work without padding or __aligned. Anyway it looks to complicated. Even if it is the last field, it may "overrun" something else. Is it not better to define an aligned setup array, with appropriate size that DMA may not overrun? It does not have to be in the struct udc_sam_usbc_data, can be placed in UDC_SAM_USBC_DEVICE_DEFINE(n) macro, and have a pointer to the array in struct udc_sam_usbc_config.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 4 above)
Comment (jfischer-no) [reply drivers/usb/udc/udc_sam_usbc.c]: > /* typedef is used to checkpatch identify the type */

I do not see it complaining.

> This typedef is necessary to comply with cost * format.

No.

File: dts/bindings/usb/atmel,sam-usbc.yaml (hunk 3 above)
Comment (jfischer-no) [reply dts/bindings/usb/atmel,sam-usbc.yaml]: There is no reason to update this file. The content of dts/bindings/usb/atmel,sam-usbc.yaml seems to be far below the level of originality, not sure what are you trying to archive.

Comment (nandojve) [reply dts/bindings/usb/atmel,sam-usbc.yaml]: Since I'm working on this driver and have the rights to update. There is no reason to me not to do it. The documentation points that is not necessary but still a right that authors have to update the entries.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 4 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: I use zephyr checkpatch hooks when using git. The rules conflict with the CI rules.
So, this is necessary.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 26 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: After doing research on this topic and analyzing the options my conclusion is that this is the recommended solution. There is no documentation about the internal USB-DMA overrun size so, it is not possible to know how big can the corruption. Any other attempt, even including padding after, may result in problems in the future when compiler change. Changing the place of the variable will not change the USB-DMA implementation which can create the same problem.

After moving any value before the setup makes the code work correctly and alignment is necessary to make sure that DMA work correctly.

What bothers me is seeing that some tests are failing precisely because of BUILD_ASSERT(). I think the correct question would be: How some build passes and how some build fails? I mean, how that check can "eventually" fail? Maybe we have a bigger problem then the DMA doing overrun.

```
INFO    - 416/973 sam4l_ek/sam4lc4c         sample.usbd.loopback                               NOT RUN (build <zephyr>)
INFO    - 417/973 sam4l_ek/sam4lc4c         sample.usbd.shell                                  NOT RUN (build <zephyr>)
INFO    - 418/973 sam4l_ek/sam4lc4c         sample.usbd.console                                NOT RUN (build <zephyr>)
INFO    - 419/973 sam4l_ek/sam4lc4c         sample.usb.legacy.webusb                           NOT RUN (build <zephyr>)
INFO    - 420/973 sam4l_ek/sam4lc4c         sample.usbd.hid-keyboard.out-report                NOT RUN (build <zephyr>)
INFO    - 421/973 sam4l_ek/sam4lc4c         sample.usb.legacy.console                          NOT RUN (build <zephyr>)
INFO    - 422/973 sam4l_ek/sam4lc4c         sample.usbd.hid-keyboard.large-report              NOT RUN (build <zephyr>)
INFO    - 423/973 sam4l_ek/sam4lc4c         sample.usb.legacy.hid-mouse                        NOT RUN (build <zephyr>)
INFO    - 424/973 sam4l_ek/sam4lc4c         sample.usb_device_next.cdc-acm-workqueue           NOT RUN (build <zephyr>)
INFO    - 425/973 sam4l_ek/sam4lc4c         sample.usbd.hid-keyboard.large-out-report          NOT RUN (build <zephyr>)
INFO    - 426/973 sam4l_ek/sam4lc4c         sample.usb_device_next.midi                        NOT RUN (build <zephyr>)
INFO    - 427/973 sam4l_ek/sam4lc4c         sample.usbd.hid-keyboard                           NOT RUN (build <zephyr>)
INFO    - 428/973 sam4l_ek/sam4lc4c         sample.usb_device_next.cdc-acm                     NOT RUN (build <zephyr>)
INFO    - 429/973 sam4l_ek/sam4lc4c         sample.subsys.usb.uvc.encoder.jpeg                 FILTERED (runtime filter)
...
INFO    - 464/973 sam4l_ek/sam4lc4c         sample.tracing.transport.usb.ctf                   ERROR Build failure (build <zephyr>)
INFO    - /__w/zephyr/zephyr/twister-out/sam4l_ek_sam4lc4c/zephyr/samples/subsys/tracing/sample.tracing.transport.usb.ctf/build.log
...
[109/172] Building C object zephyr/subsys/usb/device_next/CMakeFiles/subsys__usb__device_next.dir/usbd_msg.c.obj
[110/172] Linking C static library zephyr/subsys/usb/device_next/libsubsys__usb__device_next.a
[111/172] Building C object zephyr/drivers/usb/udc/CMakeFiles/drivers__usb__udc.dir/udc_common.c.obj
[112/172] Building C object zephyr/drivers/usb/udc/CMakeFiles/drivers__usb__udc.dir/udc_sam_usbc.c.obj
FAILED: zephyr/drivers/usb/udc/CMakeFiles/drivers__usb__udc.dir/udc_sam_usbc.c.obj 
ccache /opt/toolchains/zephyr-sdk-0.17.4/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DKERNEL -DK_HEAP_MEM_POOL_SIZE=0 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -D_POSIX_THREAD_SAFE_FUNCTIONS=200809L -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/drivers/usb/common -I/__w/zephyr/zephyr/twister-out/sam4l_ek_sam4lc4c/zephyr/samples/subsys/tracing/sample.tracing.transport.usb.ctf/zephyr/include/generated/zephyr -I/__w/zephyr/zephyr/include -I/__w/zephyr/zephyr/twister-out/sam4l_ek_sam4lc4c/zephyr/samples/subsys/tracing/sample.tracing.transport.usb.ctf/zephyr/include/generated -I/__w/zephyr/zephyr/soc/atmel/sam -I/__w/zephyr/zephyr/lib/libc/picolibc/include -I/__w/zephyr/zephyr/lib/posix/c_lib_ext/getopt -I/__w/zephyr/zephyr/soc/atmel/sam/common/. -I/__w/zephyr/zephyr/soc/atmel/sam/sam4l/. -I/__w/zephyr/zephyr/kernel/include -I/__w/zephyr/zephyr/arch/arm/include -I/__w/zephyr/zephyr/subsys/tracing/include -I/__w/zephyr/zephyr/subsys/tracing/ctf/. -I/__w/zephyr/modules/hal/cmsis_6/CMSIS/Core/Include -I/__w/zephyr/zephyr/modules/cmsis_6/. -I/__w/zephyr/modules/hal/atmel/include -I/__w/zephyr/modules/hal/atmel/asf/sam/include/sam4l -isystem /__w/zephyr/zephyr/lib/libc/common/include -Wshadow -fno-strict-aliasing -Werror -Os -imacros /__w/zephyr/zephyr/twister-out/sam4l_ek_sam4lc4c/zephyr/samples/subsys/tracing/sample.tracing.transport.usb.ctf/zephyr/include/generated/zephyr/autoconf.h -fno-printf-return-value -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft --sysroot=/opt/toolchains/zephyr-sdk-0.17.4/arm-zephyr-eabi/arm-zephyr-eabi -imacros /__w/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/zephyr/zephyr/samples/subsys/tracing=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -specs=picolibc.specs -std=c17 -MD -MT zephyr/drivers/usb/udc/CMakeFiles/drivers__usb__udc.dir/udc_sam_usbc.c.obj -MF zephyr/drivers/usb/udc/CMakeFiles/drivers__usb__udc.dir/udc_sam_usbc.c.obj.d -o zephyr/drivers/usb/udc/CMakeFiles/drivers__usb__udc.dir/udc_sam_usbc.c.obj -c /__w/zephyr/zephyr/drivers/usb/udc/udc_sam_usbc.c
In file included from /__w/zephyr/zephyr/include/zephyr/toolchain.h:52,
                 from /__w/zephyr/zephyr/include/zephyr/kernel_includes.h:23,
                 from /__w/zephyr/zephyr/include/zephyr/kernel.h:17,
                 from /__w/zephyr/zephyr/include/zephyr/drivers/usb/udc.h:15,
                 from /__w/zephyr/zephyr/drivers/usb/udc/udc_common.h:15,
                 from /__w/zephyr/zephyr/drivers/usb/udc/udc_sam_usbc.c:7:
/__w/zephyr/zephyr/include/zephyr/toolchain/gcc.h:87:36: error: static assertion failed: "setup[] must be last field (DMA overrun protection)"
   87 | #define BUILD_ASSERT(EXPR, MSG...) _Static_assert((EXPR), "" MSG)
      |                                    ^~~~~~~~~~~~~~
/__w/zephyr/zephyr/drivers/usb/udc/udc_sam_usbc.c:100:1: note: in expansion of macro 'BUILD_ASSERT'
  100 | BUILD_ASSERT(offsetof(struct udc_sam_usbc_data, setup) +
      | ^~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

CC: @stephanosio ^

File: dts/bindings/usb/atmel,sam-usbc.yaml (hunk 3 above)
Comment (jfischer-no) [reply dts/bindings/usb/atmel,sam-usbc.yaml]: Okay. Then, I will not accept that until you fix it and address all my comments. Also, please stop marking unresolved comments resolved, it is counterproductive.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 4 above)
Comment (jfischer-no) [reply drivers/usb/udc/udc_sam_usbc.c]: No. I fetched you PR and removed `typedef Usbc Usbc_t;`, no complains from checkpatch. Also note that using typedef is not recommend and `_t`post-fix is against coding style.

File: drivers/usb/udc/udc_sam_usbc.c (hunk 26 above)
Comment (jfischer-no) [reply drivers/usb/udc/udc_sam_usbc.c]: >What bothers me is seeing that some tests are failing precisely because of BUILD_ASSERT(). I think the correct question would be: How some build passes and how some build fails?

What I said.

>Perhaps it would work without padding or __aligned.

Just look at `struct k_thread` or `struct k_event`, the size of these depends on build configuration. Event if they would be aligned, `struct udc_sam_usbc_data` has holes.

File: dts/bindings/usb/atmel,sam-usbc.yaml (hunk 3 above)
Comment (nandojve) [reply dts/bindings/usb/atmel,sam-usbc.yaml]: undo

File: drivers/usb/udc/udc_sam_usbc.c (hunk 4 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: removed

File: drivers/usb/udc/udc_sam_usbc.c (hunk 26 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbc.c]: align the struct and removed the BUILD_ASSERT

Comment (jfischer-no) [reply drivers/usb/udc/udc_sam_usbc.c]: Since BUILD_ASSERT is removed, I think you can keep the `__aligned(4)`;.

**Review by jfischer-no — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
