### PR TITLE
posix: fix pthread for SMP platforms

### LINKED ISSUE #36736: kernel: SMP global lock (and therefore irq_lock) works incorrectly on SMP platforms
**Describe the bug**
While debugging #36652 I've bumped into a situation when two threads are executing code protected with `SMP global lock` on two CPUs simultaneously (which shouldn't be happening)

The SMP global lock is widely used in Zephyr via `irq_lock` abstraction layer on SMP systems.

The SMP global_lock implementation looks quite suspicious. We have two complimentary `z_smp_global_lock`/`z_smp_global_lock` functions (which is OK) and one outstanding `z_smp_release_global_lock` which is called from `do_swap`.

The `z_smp_release_global_lock` previously had complimentary `z_smp_reacquire_global_lock` function which reacquired (if it is required) SMP global_lock on the thread brought online. However it was removed during huge scheduler rewrite 1acd8c2996c3a1ae0691247deff8c32519307f17

This seems to be incorrect as after thread swap (and call `z_smp_release_global_lock`) and swap back we will get `global_lock_count` inconsistent with `global_lock` value - the `global_lock` is reset by `z_smp_release_global_lock`, but thread's `global_lock_count` value is kept the same and all other calls to `z_smp_global_lock` and `z_smp_global_unlock1 by this thread won't work correctly.

This is one example of issue (among many possible ones):

```
CPU0                                                       CPU1
[1] lock - call z_smp_global_lock
[2] scheduled out, z_smp_release_global_lock call          lock - call z_smp_global_lock
                                                           we take global_lock here as it was
							   unlocked by z_smp_release_global_lock
							   on CPU0
[3] scheduled in
[4] unlock - call z_smp_global_unlock
    **Ooops!!!** - here we actually unlock global_lock
    taken by another CPU (CPU1)
```

This looks like a bug introduced by 1acd8c2996c3a1ae0691247deff8c32519307f17.

Here is the current implementation of SMP global_lock code [kernel/smp.c](https://github.com/zephyrproject-rtos/zephyr/blob/zephyr-v2.6.0/kernel/smp.c)
```
static atomic_t global_lock;

unsigned int z_smp_global_lock(void)
{
	unsigned int key = arch_irq_lock();

	if (!_current->base.global_lock_count) {
		while (!atomic_cas(&global_lock, 0, 1)) {
		}
	}

	_current->base.global_lock_count++;

	return key;
}

void z_smp_global_unlock(unsigned int key)
{
	if (_current->base.global_lock_count) {
		_current->base.global_lock_count--;

		if (!_current->base.global_lock_count) {
			atomic_clear(&global_lock);
		}
	}

	arch_irq_unlock(key);
}

/* Called from within z_swap(), so assumes lock already held */
void z_smp_release_global_lock(struct k_thread *thread)
{
	if (!thread->base.global_lock_count) {
		atomic_clear(&global_lock);
	}
}
```

**Impact**
The SMP kernel works incorrectly which may lead to hangs (i.e #36652) / incorrect execution / data loss / etc.

### LINKED ISSUE #37109: Zephyr POSIX layer uses swapping with an interrupt lock held
Zephyr POSIX layer actively uses swapping with an interrupt lock held.

According to @andyross ([link](https://github.com/zephyrproject-rtos/zephyr/issues/36736#issuecomment-875945758))

> THAT we need to get fixed ASAP. It really should just never happen, it was a quirk about the old API that we'd like to deprecate if possible.

Such mechanism is used (at least) in 

- lib/posix/pthread_cond.c
- lib/posix/pthread_mutex.c
- lib/posix/pthread_barrier.c

and rest of POSIX code relies on the APIs implemented in these files.

Here is an example of code using swapping with an interrupt lock held (in `lib/posix/pthread_cond.c`)

```
int pthread_cond_signal(pthread_cond_t *cv)
{
	int key = irq_lock();

	_ready_one_thread(&cv->wait_q);
	z_reschedule_irqlock(key);

	return 0;
}
```

The swapping with an interrupt lock held is broken and problems with it were discussed in #36736

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
We shouldn't use swapping with an interrupt lock held as it works incorrectly on SMP platforms (see #36736 for details)

Fix that by replacing irq_lock (which is defined to SMP global lock on SMP systems) with spinlock for pthread subsystem.

NOTE: we fix that in a simple way with single spinlock for mutex / cond_var / barrier. That could be improved later (i.e. split it for several spinlocks).

Fixes: #36736
Fixes: #37109

### CODE REVIEW

File: lib/posix/pthread_mutex.c [hunk 1]
```diff
@@ -22,13 +24,14 @@ static const pthread_mutexattr_t def_attr = {
 
 static int acquire_mutex(pthread_mutex_t *m, k_timeout_t timeout)
 {
-	int rc = 0, key = irq_lock();
+	int rc = 0;
+	k_spinlock_key_t key = k_spin_lock(&_z_pthread_spinlock);
```
Comment (cfriedt) [inline lib/posix/pthread_mutex.c:28]: I believe this will break the `PTHREAD_MUTEX_RECURSIVE` use case and result in deadlock - at least that's what [the docs](https://docs.zephyrproject.org/latest/reference/kernel/smp/smp.html?#spinlocks) lead me to believe.

@evgeniy-paltsev - Can you please supply a test case that verifies expected behaviour?

**Review by cfriedt — CHANGES_REQUESTED** [review]
After reviewing the documentation, I'm concerned that spinlocks within `acquire_mutex()` and `pthread_cond_signal()` may result in deadlock. Test cases should be supplied (if they do not already exist) specifically for recursive locking and signalling.

Not as concerned with `pthread_barrier_wait()`, but I'm not convinced it's safe yet.

**Review by cfriedt — APPROVED** [review]

File: lib/posix/pthread_mutex.c [hunk 2]
```diff
@@ -9,6 +9,8 @@
 #include <wait_q.h>
 #include <posix/pthread.h>
 
+struct k_spinlock _z_pthread_spinlock = {};
```
Comment (pfalcon) [inline lib/posix/pthread_mutex.c:12]: Is this empty initializer really needed? I don't see such pattern to be used elsewhere, and thus it's confusing. (And the only effect would likely be putting that variable into .data instead of .bss section, again, why?)

**Review by pfalcon — COMMENTED** [review]
Some minor comments.

File: lib/posix/pthread_barrier.c [hunk 3]
```diff
@@ -9,9 +9,11 @@
 #include <ksched.h>
 #include <wait_q.h>
 
+extern struct k_spinlock _z_pthread_spinlock;
```
[the remark this answers is not in the document]
Comment (evgeniy-paltsev) [reply lib/posix/pthread_barrier.c]: I wasn't aware about such rule - I've dropped this underscore - it was added only to make this name more unique.

**Review by pfalcon — APPROVED** [review]
