### PR TITLE
kernel: overhaul unused stack measurement

### LINKED ISSUE #17852: Cmsis_rtos_v2_apis test failed on iotdk board.
**Describe the bug**
The cmsis_rtos_v2_apis test failed on iotdk board, we found that it will occur "Zephyr fatal error 2: Stack overflow" when running cmsis_rots_v2_apis test.

**To Reproduce**
1. source zephyr-env.sh
2. west build -b iotdk -p=auto tests/cmsis_rtos_v2
3. screen /dev/ttyUSB0 115200
4. west flash

**Screenshots or console output**
image

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr SDK
 - Commit ID: e806bd977955

### PR DESCRIPTION
**Pull request by tyrantlizard77**
The existing stack_analyze APIs had some problems:

1. Not properly namespaced
2. Accepted the stack object as a parameter, yet the stack object
   does not contain the necessary information to get the associated
   buffer region, the thread object is needed for this
3. Caused a crash on certain platforms that do not allow inspection
   of unused stack space for the currently running thread
4. No user mode access

We deprecate these functions and add a new API
k_thread_stack_space_get() which addresses all of these issues.

A helper API log_stack_usage() also added which resembles
STACK_ANALYZE() in functionality.

Fixes: #17852

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

File: include/debug/stack.h [hunk 1]
```diff
@@ -82,11 +83,28 @@ static inline void stack_analyze(const char *name, const char *stack,
...
+{
+#if defined(CONFIG_INIT_STACKS) && defined(CONFIG_THREAD_STACK_INFO)
+	size_t unused, size = thread->stack_info.size;
+
+	LOG_MODULE_DECLARE(os, CONFIG_KERNEL_LOG_LEVEL);
+
+	if (k_thread_stack_space_get(thread, &unused) == 0) {
+		unsigned int pcnt = ((size - unused) * 100U) / size;
+
+		LOG_INF("%p (%s):\tunused %zu\tusage %zu / %zu (%u %%)",
```
Comment (nashif) [inline include/debug/stack.h]: How about we get the thread name using k_thread_name_get() if name is NULL, or we could just set the thread name for those threads and remove the argument completely. The macro predates the support for setting thread names...

Comment (andrewboie) [reply include/debug/stack.h]: do you want this done here or can it be in a separate PR?
I hesitate to make this function depend on 3 separate kconfigs but perhaps we must

Comment (nashif) [reply include/debug/stack.h]: You do not need to depend on CONFIG_THREAD_NAME here afaik, you can just do:
```
tname = k_thread_name_get(thread);
if (tname != NULL) {
   ...
}
```
Having free-style thread names here as in the old macro is not great, we should just set the thread name in one place, so it matches everything else, afaik thread names are now also being used in exceptions and other places. And since this is a debug feature, the extra overhead is acceptable.

Comment (andrewboie) [reply include/debug/stack.h]: @nashif this is now done

**Comment by andrewboie** [comment]
@vonhust this should fix ARC issues with the cmsis_rtos_v2 tests

File: include/debug/stack.h [hunk 2]
```diff
@@ -82,11 +83,33 @@ static inline void stack_analyze(const char *name, const char *stack,
...
 
+static inline void log_stack_usage(const struct k_thread *thread)
+{
+#if defined(CONFIG_INIT_STACKS) && defined(CONFIG_THREAD_STACK_INFO)
+	size_t unused, size = thread->stack_info.size;
+	const char *tname;
+
+	LOG_MODULE_DECLARE(os, CONFIG_KERNEL_LOG_LEVEL);
+
+	tname = k_thread_name_get((k_tid_t)thread);
```
Comment (nordic-krch) [inline include/debug/stack.h]: used only inside if, can be moved there

**Comment by ruuddw** [comment]
The NO_UNUSED_STACK_INSPECTION is a clean solution for the ARC hardware stack boundary checking. Alternative would be to temporarily disable the checking, or have call a arch specific check function. But disabling might require introducing more locking complexity. Something we can consider for ARC later.

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Comment by joerchan** [comment]
CC: @rakons  @rugeGerritsen

**Review by andyross — APPROVED** [review]
Some nitpicks.  One note about dead code that would probably be worth addressing.

File: kernel/thread.c [hunk 3]
```diff
@@ -882,3 +883,85 @@ void irq_offload(irq_offload_routine_t routine, void *parameter)
...
+		 *
+		 * FIXME: thread->stack_info.start ought to reflect
+		 * this!
+		 */
+		checked_stack += 4;
+		size -= 4;
+	}
+
+	if (IS_ENABLED(CONFIG_STACK_GROWS_UP)) {
+		for (size_t i = size; i > 0; i--) {
```
[the remark this answers is not in the document]
Comment (andrewboie) [reply kernel/thread.c]: > Both loops check every byte in checked_stack[] between index "0" and "size - 1" and count the number that are equal to 0xAA.

The way the logic is currently implemented, we just check until we no longer encounter a consecutive 0xAA, breaking out when that is the case. If the stack grows up I think we need to start looking at the highest address and go backwards.

I copypasted this from the deprecated other implementation in include/debug/stack.h. I agree it should just be removed, there's no way to get code  coverage on it, which would negatively impact our reports.

File: arch/Kconfig [hunk 4]
```diff
@@ -218,6 +218,13 @@ config STACK_GROWS_UP
 	  Select this option if the architecture has upward growing thread
 	  stacks. This is not common.
 
+config NO_UNUSED_STACK_INSPECTION
+	bool
+	help
+	  Selected if the architecture will generate a fault if unused stack
+	  memory (the region between the current stack pointer and the stack
+	  base address) generates a fault if examined.
```
[the remark this answers is not in the document]
Comment (andrewboie) [reply arch/Kconfig]: fixed

File: kernel/thread.c [hunk 5]
```diff
@@ -882,3 +883,85 @@ void irq_offload(irq_offload_routine_t routine, void *parameter)
...
 #endif
+
+#if defined(CONFIG_INIT_STACKS) && defined(CONFIG_THREAD_STACK_INFO)
+int z_impl_k_thread_stack_space_get(const struct k_thread *thread,
+				    size_t *unused_ptr)
+{
+	const u8_t *start = (u8_t *)thread->stack_info.start;
+	size_t size = thread->stack_info.size;
+	size_t unused = 0;
+	u8_t sp;
```
[the remark this answers is not in the document]
Comment (andrewboie) [reply kernel/thread.c]: done.

File: include/kernel.h [hunk 6]
```diff
@@ -834,6 +834,31 @@ static inline void k_thread_resource_pool_assign(struct k_thread *thread,
...
+ * on a platform which selects CONFIG_NO_UNUSED_STACK_INSPECTION, an error
+ * will be generated.
+ *
+ * @param thread Thread to inspect stack information
+ * @param unused_ptr Output parameter, filled in with the unused stack space
+ *	of the target thread in bytes.
+ * @return 0 on success
+ * @return -EBADF Bad thread object (user mode only)
+ * @return -EPERM No permissions on thread object (user mode only)
+ * #return -EINVAL Forbidden by hardware policy
```
[the remark this answers is not in the document]
Comment (andrewboie) [reply include/kernel.h]: added

File: include/debug/stack.h (hunk 2 above)
Comment (andrewboie) [reply include/debug/stack.h]: moved

**Comment by andrewboie** [comment]
> The NO_UNUSED_STACK_INSPECTION is a clean solution for the ARC hardware stack boundary checking. Alternative would be to temporarily disable the checking, or have call a arch specific check function. But disabling might require introducing more locking complexity. Something we can consider for ARC later.

Added a TODO note about this.

File: subsys/shell/modules/kernel_service.c [hunk 7]
```diff
@@ -153,8 +172,8 @@ SHELL_STATIC_SUBCMD_SET_CREATE(sub_kernel,
 #if defined(CONFIG_REBOOT)
 	SHELL_CMD(reboot, &sub_kernel_reboot, "Reboot.", NULL),
 #endif
-#if defined(CONFIG_INIT_STACKS) && defined(CONFIG_THREAD_MONITOR) \
-				&& defined(CONFIG_THREAD_STACK_INFO)
+#if defined(CONFIG_INIT_STACKS) && defined(CONFIG_THREAD_STACK_INFO) && \
```
Comment (nordic-krch) [inline subsys/shell/modules/kernel_service.c]: just a hint - `SHELL_COND_CMD` macro could be utilized here, no potential dead code  since commands get compiled even when features are disabled.
```
#if defined(CONFIG_INIT_STACKS) && defined(CONFIG_THREAD_MONITOR) \
				&& defined(CONFIG_THREAD_STACK_INFO)
#define STACKS_AND_THREADS_CMDS 1
#endif

SHELL_STATIC_SUBCMD_SET_CREATE(sub_kernel,
	SHELL_CMD(cycles, NULL, "Kernel cycles.", cmd_kernel_cycles),
	SHELL_COND_CMD(CONFIG_REBOOT, reboot, &sub_kernel_reboot, "Reboot.", NULL),
	SHELL_COND_CMD(STACKS_AND_THREADS_CMDS, stacks, NULL,
			"List threads stack usage.", cmd_kernel_stacks),
	SHELL_COND_CMD(STACKS_AND_THREADS_CMDS, threads, NULL,
			"List kernel threads.", cmd_kernel_threads),
	SHELL_CMD(uptime, NULL, "Kernel uptime.", cmd_kernel_uptime),
	SHELL_CMD(version, NULL, "Kernel version.", cmd_kernel_version),
	SHELL_SUBCMD_SET_END /* Array terminated. */
);
```

**Review by nordic-krch — APPROVED** [review]

**Review by ruuddw — APPROVED** [review]
