### PR TITLE
driver: intc: plic: fix trigger type register bit calculation

### LINKED ISSUE #65846: drivers: intc: plic: calculation of IRQ's bit position in the trigger-type register is wrong
**Describe the bug**
The current calculation of the IRQ's bit position in the trigger-type register is wrong according to the Andes' [reference manual](https://www.andestech.com/wp-content/uploads/AX45MP-1C-Rev.-5.0.0-Datasheet.pdf):

image
image

https://github.com/zephyrproject-rtos/zephyr/blob/a51bd53cef2b2b6cacb1dc7a366adb45565659f3/drivers/interrupt_controller/intc_plic.c#L137-L143

Specifically, L142 is missing the `"modulo 32"`:
https://github.com/zephyrproject-rtos/zephyr/blob/a51bd53cef2b2b6cacb1dc7a366adb45565659f3/drivers/interrupt_controller/intc_plic.c#L142

target platform: custom Andes board

**To Reproduce**
Not reproducible on upstream applications afaik.

**Expected behavior**
PLIC driver should read the correct bit for the IRQ

**Impact**
Showstopper for application requiring edge-triggered interrupt

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.4
 - Commit SHA: a51bd53cef2b2b6cacb1dc7a366adb45565659f3

### PR DESCRIPTION
**Pull request by ycsin**
The current IRQ bit position calculation for the trigger type register is wrong according to the datasheets, the fix opts for bit mask instead of modulo, as the former is faster.

[**Telink B91 Reference Manual**](http://wiki.telink-semi.cn/doc/ds/DS-TLSR9518-E_Datasheet%20for%20Telink%20Multi-Standard%20Wireless%20SoC%20TLSR9518.pdf)

image

[**Andes AX45MP Reference Manual**](https://www.andestech.com/wp-content/uploads/AX45MP-1C-Rev.-5.0.0-Datasheet.pdf)

image
image

fixes #65846

### CODE REVIEW

File: drivers/interrupt_controller/intc_plic.c [hunk 1]
```diff
@@ -139,7 +139,7 @@ static int riscv_plic_is_edge_irq(const struct device *dev, uint32_t local_irq)
 	const struct plic_config *config = dev->config;
 	mem_addr_t trig_addr = config->trig + local_irq_to_reg_offset(local_irq);
 
-	return sys_read32(trig_addr) & BIT(local_irq);
+	return sys_read32(trig_addr) & BIT(local_irq & PLIC_REG_MASK);
```
Comment (cfriedt) [inline drivers/interrupt_controller/intc_plic.c:142]: LGTM. It would be nice if this were a bit more testable though.

**Review by cfriedt — APPROVED** [review]
It would be ideal if we had a test

**Review by fkokosinski — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]
