### PR TITLE
soc: mcxw: Fix SWD debug/flash issue on MCXW72 target

### LINKED ISSUE #104780: frdm_mcxw72: SWD debug/flash fails after flashing (linkserver/J-Link) requires ISP erase
### Board / SoC
- Board: `frdm_mcxw72`

### Problem description
After flashing **any** sample application to `frdm_mcxw72`, subsequent debug/flash attempts via SWD stop working. To recover, I must switch the board to **ISP mode** and **erase** it. This happens with both **LinkServer** and **J-Link**.

0ec724838d49043d456a10e5632766174f950094 is the first bad commit
commit 0ec724838d49043d456a10e5632766174f950094
Author: Yassine El Aissaoui <yassine.elaissaoui@nxp.com>
Date:   Mon Feb 9 15:49:53 2026 +0100

    soc: mcxw: Add Power management support on connectivity apps

    - Update low power state exit latency to match SDK
    - Enable NBU wakeup source
    - Configure 32MHz crystal osc
    - Shutdown NBU when it's not used

    Signed-off-by: Yassine El Aissaoui <yassine.elaissaoui@nxp.com>

 dts/arm/nxp/mcx/nxp_mcxw71.dtsi            |  5 ++++
 dts/arm/nxp/mcx/nxp_mcxw72.dtsi            |  5 ++++
 dts/arm/nxp/mcx/nxp_mcxw7x_common.dtsi     |  5 ++--
 dts/bindings/arm/nxp,nbu.yaml              | 11 +++++++-
 soc/nxp/common/nxp_nbu.c                   | 29 +++++++++++++++++++-
 soc/nxp/mcx/mcxw/mcxw7xx/Kconfig.defconfig |  7 +++++
 soc/nxp/mcx/mcxw/mcxw7xx/power.c           | 43 ++++++++++++++----------------
 soc/nxp/mcx/mcxw/mcxw7xx/soc.c             | 31 +++++++++++++++++++++
 soc/nxp/mcx/mcxw/mcxw7xx/soc.h             |  6 ++---
 9 files changed, 112 insertions(+), 30 deletions(-)

[x] is_regression

it is OK on v4.3.0-6618-ga6fb8b8a19f9, need bisect further

### Steps to reproduce
```sh
west build -b frdm_mcxw72 samples/hello_world
west flash --runner linkserver

# run flash again
west flash --runner linkserver
```

### Observed behavior
The second `west flash` fails with SWD connection errors (Wire Ack Fault / cannot provide power to DAP bus).

### Expected behavior
Re-flashing / debugging should continue to work without requiring an ISP erase.

### Error log
```text
(.venv) ubuntu@ubuntu-5410-zephyr-14:~/zephyrproject/zephyr/samples/hello_world$ west flash --runner linkserver --probe "ADOSX1THNR4SP"
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner linkserver
RUNNER - gdb_port = 3333, semih port = 8888
-- runners.linkserver: LinkServer: /usr/local/LinkServer/LinkServer, version v25.9.134
INFO: Exact match for MCXW727C:MCX-W72-EVK found
INFO: Selected device MCXW727CxxxA:MCX-W72-EVK
INFO: Getting available probes
INFO: Selecting probe by serial substring
INFO: Selected probe #1 ADOSX1THNR4SP (MCU-LINK on-board (r0E3) CMSIS-DAP V3.165)
INFO: MCU-Link firmware update `check`: Probe ([ADOSX1THNR4SP] [MCU-LINK on-board (r0E3) CMSIS-DAP V3.165]) is already running the same firmware version as the included firmware version [3.165]
(.venv) ubuntu@ubuntu-5410-zephyr-14:~/zephyrproject/zephyr/samples/hello_world$ west flash --runner linkserver --probe "ADOSX1THNR4SP"
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner linkserver
RUNNER - gdb_port = 3333, semih port = 8888
-- runners.linkserver: LinkServer: /usr/local/LinkServer/LinkServer, version v25.9.134
INFO: Exact match for MCXW727C:MCX-W72-EVK found
INFO: Selected device MCXW727CxxxA:MCX-W72-EVK
INFO: Getting available probes
INFO: Selecting probe by serial substring
INFO: Selected probe #1 ADOSX1THNR4SP (MCU-LINK on-board (r0E3) CMSIS-DAP V3.165)
INFO: MCU-Link firmware update `check`: Probe ([ADOSX1THNR4SP] [MCU-LINK on-board (r0E3) CMSIS-DAP V3.165]) is already running the same firmware version as the included firmware version [3.165]
CRITICAL: Critical error
ERRMSG: Exception: Flash operation exited with code 1
FATAL ERROR: command exited with status 255: /usr/local/LinkServer/LinkServer flash --probe ADOSX1THNR4SP MCXW727C:MCX-W72-EVK load --addr 268435456 /home/ubuntu/zephyrproject/zephyr/samples/hello_world/build/zephyr/zephyr.bin

```

### Workaround
- Switch the board to ISP mode and erase the device. After that, flashing/debugging works again.

### Additional notes
- J-Link shows the same behavior.

### Environment (please fill if needed)
- Zephyr version (commit / tag): v4.3.0-7061-g02191db6fe3a
- Zephyr SDK version / toolchain: Zephyr
- Host OS: Ubuntu

### PR DESCRIPTION
**Pull request by yeaissa**
Resolved an issue where repeated flash/debug cycles would fail, requiring the board to be placed in ISP mode before it could be programmed again.

https://github.com/zephyrproject-rtos/zephyr/issues/104780

### CODE REVIEW

File: soc/nxp/mcx/mcxw/mcxw7xx/soc.c [hunk 1]
```diff
@@ -340,6 +340,10 @@ static int soc_nbu_init(void)
 	/* Force low power entry request to the radio domain */
 	RF_CMC1->RADIO_LP |= RF_CMC1_RADIO_LP_CK(0x2);
 	RFMC->RF2P4GHZ_CTRL |= RFMC_RF2P4GHZ_CTRL_LP_ENTER(0x1U);
+#endif
+#if !defined(CONFIG_SOC_MCXW716C)
```
Comment (butok) [inline soc/nxp/mcx/mcxw/mcxw7xx/soc.c:353]: Does the MCXW71 not have this field?

Comment (yeaissa) [reply soc/nxp/mcx/mcxw/mcxw7xx/soc.c:353]: right, MCXW71 doesn't have it.

Comment (butok) [reply soc/nxp/mcx/mcxw/mcxw7xx/soc.c:353]: How to reproduce this issue?
My frdm-mcxw72 does not have it. Am I lucky ;)?

**Review by butok — DISMISSED** [review]

**Review by ZhaoxiangJin — DISMISSED** [review]

**Review by George-Stefan — DISMISSED** [review]

**Review by axelnxp — DISMISSED** [review]

File: soc/nxp/mcx/mcxw/mcxw7xx/soc.c (hunk 1 above)
Comment (hakehuang) [reply soc/nxp/mcx/mcxw/mcxw7xx/soc.c:353]: issue reproduce steps https://github.com/zephyrproject-rtos/zephyr/issues/104780

**Review by hakehuang — DISMISSED** [review]
this fixes does not work for me on v4.3.0-7151-g4225661e2c3c. @yeaissa 
see below

```
((.venv) ) ubuntu@zephyr-test-06:~/zephyrproject/zephyr/samples/hello_world$ west flash -r linkserver --probe "ADOSX1THNR4SP"
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner linkserver
RUNNER - gdb_port = 3333, semih port = 8888
-- runners.linkserver: LinkServer: /usr/local/LinkServer/LinkServer, version v25.3.31
INFO: Exact match for MCXW727C:MCX-W72-EVK found
INFO: Selected device MCXW727CxxxA:MCX-W72-EVK
INFO: Getting available probes
INFO: Selecting probe by serial substring
INFO: Selected probe #5 ADOSX1THNR4SP (MCU-LINK on-board (r0E3) CMSIS-DAP V3.165)
INFO: MCU-Link firmware update `check`: Probe ([ADOSX1THNR4SP] [MCU-LINK on-board (r0E3) CMSIS-DAP V3.165]) is running a firmware version which is newer than the included firmware version [3.156]
((.venv) ) ubuntu@zephyr-test-06:~/zephyrproject/zephyr/samples/hello_world$ west flash -r linkserver --probe "ADOSX1THNR4SP"
-- west flash: rebuilding
ninja: no work to do.
-- west flash: using runner linkserver
RUNNER - gdb_port = 3333, semih port = 8888
-- runners.linkserver: LinkServer: /usr/local/LinkServer/LinkServer, version v25.3.31
INFO: Exact match for MCXW727C:MCX-W72-EVK found
INFO: Selected device MCXW727CxxxA:MCX-W72-EVK
INFO: Getting available probes
INFO: Selecting probe by serial substring
INFO: Selected probe #5 ADOSX1THNR4SP (MCU-LINK on-board (r0E3) CMSIS-DAP V3.165)
INFO: MCU-Link firmware update `check`: Probe ([ADOSX1THNR4SP] [MCU-LINK on-board (r0E3) CMSIS-DAP V3.165]) is running a firmware version which is newer than the included firmware version [3.156]
CRITICAL: Critical error
ERRMSG: Exception: Flash operation exited with code 1
FATAL ERROR: command exited with status 255: /usr/local/LinkServer/LinkServer flash --probe ADOSX1THNR4SP MCXW727C:MCX-W72-EVK load --addr 268435456 /home/ubuntu/zephyrproject/zephyr/samples/hello_world/build/zephyr/zephyr.bin
```

**Review by hakehuang — APPROVED** [review]

File: soc/nxp/mcx/mcxw/mcxw7xx/soc.c [hunk 2]
```diff
@@ -340,6 +343,11 @@ static int soc_nbu_init(void)
...
+	/* Allow wakeup from the debugger */
+	RFMC->RF2P4GHZ_CFG |= RFMC_RF2P4GHZ_CFG_FORCE_DBG_PWRUP_ACK_MASK;
+	CMC_EnableDebugOperation(MCXW7_CMC_ADDR, true);
```
Comment (mmahadevan108) [inline soc/nxp/mcx/mcxw/mcxw7xx/soc.c:356]: How about enclosing this code within 
`#if IS_ENABLED(CONFIG_DEBUG))`

**Review by axelnxp — APPROVED** [review]

File: soc/nxp/mcx/mcxw/mcxw7xx/soc.c (hunk 2 above)
Comment (axelnxp) [reply soc/nxp/mcx/mcxw/mcxw7xx/soc.c:356]: I think we prefer a consistent behavior, in case of flashing issue, it could be hard for someone to narrow it down to this code. Also, I'm pretty sure @hakehuang doesn't build with `CONFIG_DEBUG` in CI but uses the default configuration (which makes sense), so it wouldn't fix the problem.
In the MCUXSDK, we made this configuration the default.

**Review by mmahadevan108 — APPROVED** [review]
