### PR TITLE
drivers: spi: stm32h7: add a small delay after enabling

### LINKED ISSUE #57219: drivers: spi: stm32: STM32H7 SPI don't work when when the core clock is high (>200Mhz)
STM32H7 SPI driver doesn't work when the core clock is high (>200Mhz).

I am using STM32H743VI (custom board) and STM32H723ZG (nucleo_H723ZG) with LSM6DSL, when I set the main clock to be above 200Mhz, I can't read out the chip ID from LSM6DSL.

Workaround that I have tried:
* reduce SPI speed (I have tried 10M, 5M, 1M, no luck)
* reduce APB clock by increasing `hpre`, `d2ppre1`. helpful, but still can't get by 200Mhz. Notably, when I'm using 3.3V with nucleo_H723ZG, getting 200Mhz is easy. With 1.8V, I have to reduce APB to less than 10Mhz and some configurations may work.
* As noted above, it seems that this issue could be voltage related, 3.3V IO is slightly better than 1.8V IO.
* Also tried older Zephyr up to 3.0, still doesn't work

How to reproduce:
* Use nucleo_H723ZG at 3.3V, connect LSM6DSL to SPI 1 pins.
* Apply `400mhz.diff` as attached.
* Build and flash using `west build -b nucleo_h743zi samples/sensor/lsm6dsl/ && west flash -r stm32cubeprogrammer`
* Run serial monitor
* It would say `sensor: device not ready.`
* Further inspection shows that the CHIP_ID read from LSM6DSL wrong.

As a comparison, apply `200mhz.diff` at 3.3V, it would print gyroscope and accelerometer values as expected.

Environment (please complete the following information):
 - OS: macOS
 - Toolchain: Zephyr SDK
 - Zephyr v3.3.0 or 07c6af3b8c35c1e49186578ca61a25c76e2fb308

[200mhz.diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/11319679/200mhz.diff.txt)
[400mhz.diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/11319680/400mhz.diff.txt)

### PR DESCRIPTION
**Pull request by gautierg-st**
Add a small delay after enabling SPI to prevent transfer stalling.
Fixes #57219

### CODE REVIEW

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -643,6 +643,13 @@ static int transceive(const struct device *dev,
 
 	LL_SPI_Enable(spi);
 
+#if CONFIG_SOC_SERIES_STM32H7X
+	/*
+	 * Add a small delay after enabling to prevent transfer stalling at high
+	 * system clock frequency (see errata sheet ES0392).
+	 */
+	k_busy_wait(1);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:651]:
```suggestion
	k_busy_wait(1U * USEC_PER_MSEC);
```

File: drivers/spi/spi_ll_stm32.c [hunk 2]
```diff
@@ -643,6 +643,13 @@ static int transceive(const struct device *dev,
 
 	LL_SPI_Enable(spi);
 
+#if CONFIG_SOC_SERIES_STM32H7X
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:646]: Should it be `#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32h7_spi)` ?
(ie are we sure this is series specific and not related to the IP)

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_ll_stm32.c (hunk 2 above)
Comment (gautierg-st) [reply drivers/spi/spi_ll_stm32.c:646]: I don't see anything similar in the errata of STM32U5 or H5 that also use this compatible. So I'd say this is series specific.

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (gautierg-st) [reply drivers/spi/spi_ll_stm32.c]: Done

**Review by erwango — APPROVED** [review]

**Review by tagunil — CHANGES_REQUESTED** [review]
I'd like to see the delay value question clarified, as it could break some of my use cases. ES0392 says one SCK cycle should be enough.

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c]: My bad, this is indeed a wrong understanding from my part.
@gautierg-st Please add and use a define which mention the unit for clarity.

**Review by erwango — CHANGES_REQUESTED** [review]
See https://github.com/zephyrproject-rtos/zephyr/pull/58227#discussion_r1205612220

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (gautierg-st) [reply drivers/spi/spi_ll_stm32.c]: Done

**Review by tagunil — APPROVED** [review]
LGTM

**Review by erwango — APPROVED** [review]

**Review by nashif — APPROVED** [review]
