### PR TITLE
tests: drivers: clock_control: Fix tests for nrf52832

### LINKED ISSUE #41806: tests: driver: clock: nrf: Several failures on nrf52dk_nrf52832
**Describe the bug**
Several tests related to clock driver fails on nrf52dk_nrf52832. It looks like the board hangs after some initial commands and the test is terminated by a timeout. Following scenarios are failing:
drivers.clock.drivers.clock.clock_control_nrf5
drivers.clock.drivers.clock.clock_control_nrf5_lfclk_rc
drivers.clock.drivers.clock.nrf5_clock_calibration
drivers.clock.nrf_lf_clock_start_synth_stable

**To Reproduce**
1. connect nrf52dk_nrf52832 (e.g. as /dev/ttyACM0)
2.  run `./scripts/twister -p nrf52dk_nrf52832 --device-testing --device-serial /dev/ttyACM0 --ninja -T tests/drivers/clock_control/ -v`
3. See error

**Expected behavior**
Tests passes

**Impact**
Not clear

**Logs and console output**
```
17:11 $ ./scripts/twister -p nrf52dk_nrf52832 --device-testing --device-serial /dev/ttyACM0 --ninja -T tests/drivers/clock_control/ -v
ZEPHYR_BASE unset, using "/home/maciej/zephyrproject2/zephyr"
Renaming output directory to /home/maciej/zephyrproject2/zephyr/twister-out.31
INFO    - Zephyr version: v2.7.99-3217-gc71dd808345b
INFO    - JOBS: 4
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testcase list...
INFO    - 28 test scenarios (28 configurations) selected, 14 configurations discarded due to filters.

Device testing on:

| Platform         | ID   | Serial device   |
|------------------|------|-----------------|
| nrf52dk_nrf52832 |      | /dev/ttyACM0    |

INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    -  1/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_synth_available PASSED (device 3.456s)
INFO    -  2/14 nrf52dk_nrf52832          tests/drivers/clock_control/onoff/drivers.clock.clock_control_onoff PASSED (device 4.387s)
INFO    -  3/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_synth_no_wait PASSED (device 5.097s)
INFO    -  4/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_clock_calibration/drivers.clock.nrf5_clock_calibration FAILED Timeout (device 65.230s)
ERROR   - see: /home/maciej/zephyrproject2/zephyr/twister-out/nrf52dk_nrf52832/tests/drivers/clock_control/nrf_clock_calibration/drivers.clock.nrf5_clock_calibration/handler.log
INFO    -  5/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_synth_stable FAILED Timeout (device 68.428s)
ERROR   - see: /home/maciej/zephyrproject2/zephyr/twister-out/nrf52dk_nrf52832/tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_synth_stable/build.log
INFO    -  6/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_rc_available PASSED (device 3.346s)
INFO    -  7/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_rc_no_wait PASSED (device 4.574s)
INFO    -  8/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_rc_stable PASSED (device 5.238s)
INFO    -  9/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_xtal_no_wait PASSED (device 6.069s)
INFO    - 10/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_xtal_available PASSED (device 5.008s)
INFO    - 11/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_lf_clock_start/drivers.clock.nrf_lf_clock_start_xtal_stable PASSED (device 6.449s)
INFO    - 12/14 nrf52dk_nrf52832          tests/drivers/clock_control/nrf_onoff_and_bt/drivers.clock.nrf_onoff_and_bt PASSED (device 26.930s)
INFO    - 13/14 nrf52dk_nrf52832          tests/drivers/clock_control/clock_control_api/drivers.clock.clock_control_nrf5_lfclk_rc FAILED Timeout (device 63.458s)
ERROR   - see: /home/maciej/zephyrproject2/zephyr/twister-out/nrf52dk_nrf52832/tests/drivers/clock_control/clock_control_api/drivers.clock.clock_control_nrf5_lfclk_rc/handler.log
INFO    - 14/14 nrf52dk_nrf52832          tests/drivers/clock_control/clock_control_api/drivers.clock.clock_control_nrf5 FAILED Timeout (device 63.364s)
ERROR   - see: /home/maciej/zephyrproject2/zephyr/twister-out/nrf52dk_nrf52832/tests/drivers/clock_control/clock_control_api/drivers.clock.clock_control_nrf5/handler.log

INFO    - 10 of 14 test configurations passed (71.43%), 4 failed, 14 skipped with 0 warnings in 364.38 seconds
INFO    - In total 37 test cases were executed, 42 skipped on 1 out of total 418 platforms (0.24%)
INFO    - 14 test configurations executed on platforms, 0 test configurations were only built.

```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA or Version used c71dd80834

### PR DESCRIPTION
**Pull request by nordic-krch**
Fixes (actually disabling) tests which were failing on nrf52832. The root cause is in different HW behavior on nrf52832 where restarting LF clock clears RTC COUNTER register. It is unexpected and disrupts system clock leading to hanging.

Fixes #41806.

### CODE REVIEW

**Comment by PerMac** [comment]
I can confirm that it fixes the issue.

**Review by PerMac — APPROVED** [review]

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c [hunk 1]
```diff
@@ -23,24 +23,34 @@ struct device_data {
 	uint32_t subsys_cnt;
 };
 
+#if DT_HAS_COMPAT_STATUS_OKAY(nordic_nrf_clock)
+static const struct device_subsys_data subsys_data[] = {
+	{
+		.subsys = (void *)CLOCK_CONTROL_NRF_SUBSYS_HF,
```
Comment (anangl) [inline tests/drivers/clock_control/clock_control_api/src/test_clock_control.c:29]: nit: this typecasting is unnecessary.

**Review by anangl — APPROVED** [review]

**Comment by nordic-krch** [comment]
@carlescufi can you merge?

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 1 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: done

**Comment by nordic-krch** [comment]
@nashif @carlescufi can you merge this one?
