### PR TITLE
drivers: interrupt_controller: intc_gpio_stm32: Assert against invalid exti lines

### LINKED ISSUE #103573: drivers: intc_gpio_stm32: possible buffer overflow when invalid LL_EXTI_LINE_n is provided
### Describe the bug

I am looking at [intc_gpio_stm32.c's ll_exti_line_to_linenum(uint32_t)](https://elixir.bootlin.com/zephyr/v4.3.0/source/drivers/interrupt_controller/intc_gpio_stm32.c#L85) function:

Calling `ll_exti_line_to_linenum(0)` returns `0xFFFFFFFF`, but this behaviour is never caught when usign it for example in [stm32_gpio_intc_set_irq_callback](https://elixir.bootlin.com/zephyr/v4.3.0/source/drivers/interrupt_controller/intc_gpio_stm32.c#L254).

This could lead to array-out-of-bounds sorts of behavior.

Zephyr Version is 4.3.0

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by x-moe-x**
Unchecked indexing into intc_gpio_data.cb could lead to overflow in the following functions:

- stm32_gpio_intc_set_irq_callback
- stm32_gpio_intc_remove_irq_callback

Fixes zephyrproject-rtos/zephyr#103573

### CODE REVIEW

**Review by etienne-lms — DISMISSED** [review]

File: drivers/interrupt_controller/intc_gpio_stm32.c [hunk 1]
```diff
@@ -85,11 +85,19 @@ static inline uint32_t stm32_exti_linenum_to_src_cfg_line(gpio_pin_t linenum)
...
+ * @returns EXTI line number (n) for LL_EXTI_LINE_n define
  */
 static inline gpio_pin_t ll_exti_line_to_linenum(stm32_gpio_irq_line_t line)
 {
-	return LOG2(line);
+	const gpio_pin_t line_num = LOG2CEIL(line);
+
+	__ASSERT_NO_MSG(IS_POWER_OF_TWO(line) && line_num < NUM_EXTI_LINES);
+
+	return line_num;
```
Comment (mathieuchopstm) [inline drivers/interrupt_controller/intc_gpio_stm32.c]:
```suggestion
	//// includes (line != 0) check
	__ASSERT(IS_POWER_OF_TWO(line), "Invalid/corrupted LL_EXTI_LINE_n value");
	__ASSERT_NO_MSG(LOG2(line) < NUM_EXTI_LINES);

	return LOG2(line);
```
(the `////` comment is informative only, not an actual suggestion)

File: drivers/interrupt_controller/intc_gpio_stm32.c [hunk 2]
```diff
@@ -85,11 +85,19 @@ static inline uint32_t stm32_exti_linenum_to_src_cfg_line(gpio_pin_t linenum)
 }
 
 /**
- * @returns EXTI line number for LL_EXTI_LINE_n define
+ * @brief Translate EXTI line to line number
+ *
+ * @param line LL_EXTI_LINE_n, has to be a power of 2
+ *
+ * @returns EXTI line number (n) for LL_EXTI_LINE_n define
```
Comment (mathieuchopstm) [inline drivers/interrupt_controller/intc_gpio_stm32.c]: no need to update this, the semantics are documented on L181

**Comment by KozhinovAlexander** [comment]
@x-moe-x I see some notes from @mathieuchopstm Since I am only in member role here, it would be better you follow primarily @mathieuchopstm requests. I can only support therefore.

**Review by KozhinovAlexander — APPROVED** [review]

**Review by mathieuchopstm — APPROVED** [review]

**Review by erwango — APPROVED** [review]
