### PR TITLE
Bluetooth: audio: Expand AICS API

### LINKED ISSUE #55552: Support for mode and state changes in AICS API
**Describe the bug**
there are some tests (mandatory...) in AICS that require runtime changes in eg. gain mode or mutable but currently implementation doesn't allow to change what was registered on init

This is affecting some of mandatory qualification test cases.

**Expected behavior**
Provide API that will allow to properly implement Upper Tester interface.

This is currently affecting following qualification test cases:
AICS/SR/SGGIT/CP/BI-03-C
AICS/SR/SGGIT/CP/BI-04-C

### PR DESCRIPTION
**Pull request by szymon-czapracki**
This PR adds new API functions for AICS
Setting automatic/manual only gain modes.
Setting mute disabled.

Auto-pts tests:
1/2   AICS    AICS/SR/SGGIT/CP/BI-03-C   PASS           36.713                  
2/2   AICS    AICS/SR/SGGIT/CP/BI-04-C   PASS           37.512

### CODE REVIEW

File: include/zephyr/bluetooth/audio/aics.h [hunk 1]
```diff
@@ -364,6 +373,24 @@ int bt_aics_unmute(struct bt_aics *inst);
...
+ */
+int bt_aics_gain_set_manual_only(struct bt_aics *inst);
+
+/**
+ * @brief Set automatic only gain mode in Audio Input Control Service.
+ *
+ * @param inst          The instance pointer.
+ *
+ * @return 0 on success, errno value on fail.
+ */
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/aics.h:391]: Maybe we should add some documentation about this disabling support for setting the gain via `bt_aics_gain_set` or from clients

**Review by Thalley — CHANGES_REQUESTED** [review]
Minor request for more documentation

File: include/zephyr/bluetooth/audio/aics.h [hunk 2]
```diff
@@ -345,6 +345,15 @@ int bt_aics_type_get(struct bt_aics *inst);
  */
 int bt_aics_status_get(struct bt_aics *inst);
 
+/**
+ * @brief Disable mute in the Audio Input Control Service.
+ *
+ * @param inst          The instance pointer.
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/aics.h:351]: I think perhaps we should add something like

```suggestion
 * @brief Disable mute in the Audio Input Control Service.
 *
 * Calling bt_aics_unmute() or bt_aics_mute() will enable mute again and set the
 * mute state to either unmuted or muted. 
 *
 * @param inst          The instance pointer.
```

File: tests/bluetooth/tester/src/btp_vcp.c [hunk 3]
```diff
@@ -290,6 +307,34 @@ static uint8_t aics_auto_gain(const void *cmd, uint16_t cmd_len,
...
+		}
+	}
+
+	return BTP_STATUS_SUCCESS;
+}
+
+static uint8_t aics_man_gain_only(const void *cmd, uint16_t cmd_len,
+			      void *rsp, uint16_t *rsp_len)
+{
+	LOG_DBG("AICS auto gain only set");
```
Comment (Thalley) [inline tests/bluetooth/tester/src/btp_vcp.c:327]:
```suggestion
	LOG_DBG("AICS main gain only set");
```

File: tests/bluetooth/tester/src/btp_vcp.c [hunk 4]
```diff
@@ -248,6 +251,20 @@ static uint8_t aics_mute(const void *cmd, uint16_t cmd_len,
 	return BTP_STATUS_SUCCESS;
 }
 
+static uint8_t aics_mute_disable(const void *cmd, uint16_t cmd_len,
+			     void *rsp, uint16_t *rsp_len)
```
Comment (Thalley) [inline tests/bluetooth/tester/src/btp_vcp.c:255]:
```suggestion
static uint8_t aics_mute_disable(const void *cmd, uint16_t cmd_len,
				 void *rsp, uint16_t *rsp_len)
```

File: tests/bluetooth/tester/src/btp_vcp.c [hunk 5]
```diff
@@ -290,6 +307,34 @@ static uint8_t aics_auto_gain(const void *cmd, uint16_t cmd_len,
 	return BTP_STATUS_SUCCESS;
 }
 
+static uint8_t aics_auto_gain_only(const void *cmd, uint16_t cmd_len,
+			      void *rsp, uint16_t *rsp_len)
```
Comment (Thalley) [inline tests/bluetooth/tester/src/btp_vcp.c:311]:
```suggestion
static uint8_t aics_auto_gain_only(const void *cmd, uint16_t cmd_len,
				   void *rsp, uint16_t *rsp_len)
```

File: tests/bluetooth/tester/src/btp_vcp.c [hunk 6]
```diff
@@ -290,6 +307,34 @@ static uint8_t aics_auto_gain(const void *cmd, uint16_t cmd_len,
...
+		if (bt_aics_gain_set_auto_only(included.aics[i]) != 0) {
+			return BTP_STATUS_FAILED;
+		}
+	}
+
+	return BTP_STATUS_SUCCESS;
+}
+
+static uint8_t aics_man_gain_only(const void *cmd, uint16_t cmd_len,
+			      void *rsp, uint16_t *rsp_len)
```
Comment (Thalley) [inline tests/bluetooth/tester/src/btp_vcp.c:325]:
```suggestion
static uint8_t aics_man_gain_only(const void *cmd, uint16_t cmd_len,
				  void *rsp, uint16_t *rsp_len)
```

**Review by Thalley — CHANGES_REQUESTED** [review]

**Review by Thalley — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]
