### PR TITLE
net: lib: sntp: `SNTP_UNCERTAINTY` consistent time sources

### LINKED ISSUE #105101: SNTP: response parsing fails with `SNTP_UNCERTAINTY=y`
### Describe the bug

Attempts to query the SNTP time with `CONFIG_SNTP_UNCERTAINTY=y` now always fail with `-EINVAL`.

PR #97688 fixed the transmit timestamp by switching from device uptime to `SYS_CLOCK_REALTIME`, but inadvertently broke the timestamp comparison used to validate server responses.
https://github.com/zephyrproject-rtos/zephyr/blob/fb350217cc199e7e6c5a40b4e50a04adbf038f8b/subsys/net/lib/sntp/sntp.c#L100-L110
`dest_ts_us` and `orig_ts_us` are now in different time bases, so the naive comparison is invalid.

### Regression

- [x] This is a regression.

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### PR DESCRIPTION
**Pull request by JordanYates**
When comparing time sources for `CONFIG_SNTP_UNCERTAINTY` to validate the server responses, `dest_ts_us` and `orig_ts_us` need to be constructed from the same time sources and have the same offsets applied in order for math operations to be valid.

Fixes #105101

### CODE REVIEW

**Review by pdgendt — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

File: subsys/net/lib/sntp/sntp.c [hunk 1]
```diff
@@ -96,8 +96,16 @@ static int32_t parse_response(uint8_t *data, uint16_t len, struct sntp_time *exp
 	}
```
Comment (jukkar) [inline subsys/net/lib/sntp/sntp.c:96]: The "Fixes ...." line can be removed from commit message, zephyr no longer uses these in commit messages.

**Review by jukkar — APPROVED** [review]
