### PR TITLE
drivers: usb: Prevent from perpetual locked state

### LINKED ISSUE #89990: STM32: USB: USB CDC IN Endpoint stuck forever after receiving Clear feature - endpoint halt request
**Describe the bug**

I have a stm32wb55rg based device with enabled USB CDC, that is connected to PC over a USB hub. After the device reset and successful enumeration in host system, application is opening a port to communicate with the device over CDC. During enumeration process, the device schedules [sending the ZLP packet](https://github.com/zephyrproject-rtos/zephyr/blob/cab2f9d27f3e433d274fd18a6418da4af6dc0920/subsys/usb/device/class/cdc_acm.c#L400).
Normally, after opening a serial port, the host starts polling the In Endpoint right away, reads the ZLP and communication proceeds without any issues. But sometimes before the host starts polling it sends 'Clear feature - endpoint halt' request first, and then starts polling the IN Endpoint. 
This request is handled by calling [usb_dc_ep_clear_stall](https://github.com/zephyrproject-rtos/zephyr/blob/cab2f9d27f3e433d274fd18a6418da4af6dc0920/subsys/usb/device/usb_device.c#L1080). Underneath, it causes [setting the endpoint's status to NAK](https://github.com/zephyrproject-rtos/hal_stm32/blob/6e4716f8ac2c6e6159a958a836e1dcca06804456/stm32cube/stm32wbxx/drivers/src/stm32wbxx_ll_usb.c#L662), which effectively cancels any pending transfer without releasing associated resources, that is the queued ZLP packet transfer and endpoint's write semaphore. As a result, it is impossible to schedule any new transfer, because there is an unfinished transfer that due to NAK status will never be completed.

**To Reproduce**
This situation seems to happen randomly from around once per 5 to once per 100 following cycles:

1. Reset the device
2. Open serial port from host application
3. Send any message from the device to host over CDC

**Expected behavior**
Message sent from the device to the host should be read by the application that opened the serial port.

**Impact**
Unable to perform two way communication with the device. Messages from the host to the device are sent successfully.

**Logs and console output**
The following screenshot presents logs from the described situation. The host sends request b'0201000082000000' and starts polling IN endpoint, but the status is NAK forever, ZLP packet is not read.
Image

**Environment (please complete the following information):**
I was only able to reproduce this bug on a PC with Debian GNU/Linux 11 bullseye 5.10.0-28-amd64 and the device connected over a USB hub (reproduces with a few different USB hubs). 

**Additional context**

### PR DESCRIPTION
**Pull request by ptrcr**
The USB CDC driver is unable to process any bulk IN transfers after receiving 'Clear Feature - Endpoint Halt' request from host due to perpetual locked state caused by previously scheduled transfer, that will never be finished, as the endpoint's state is set to NAK. Fix by cancelling the transfer and releasing the resources blocking from scheduling next transfer upon receiving 'Clear Feature - Endpoint Halt' request.

Fixes #89990

### CODE REVIEW

File: subsys/usb/device/usb_device.c [hunk 1]
```diff
@@ -1077,6 +1077,11 @@ static bool usb_halt_endpoint_req(struct usb_setup_packet *setup, bool halt)
 			}
 		} else {
 			LOG_INF("Clear halt ep 0x%02x", ep);
+			/* usb_dc_ep_clear_stall effectively will cancel the transfer.
+			 * Remove transfer from the queue to prevent perpetual locked state.
+			 */
+			usb_cancel_transfer(ep);
```
Comment (jfischer-no) [inline subsys/usb/device/usb_device.c:1083]: >usb_dc_ep_clear_stall effectively will cancel the transfer

That is likely problematic and will break things. Have you checked how all the drivers and class implementations would behave?

File: drivers/usb/device/usb_dc_stm32.c [hunk 2]
```diff
@@ -740,6 +740,14 @@ int usb_dc_ep_clear_stall(const uint8_t ep)
...
 	}
 
+	/* The DataInCallback will never be called at this point for any pending
+	 * transaction associated with this endpoint as it's status has been set to NAK.
+	 * Reset the IN semaphore to prevent perpetual locked state.
+	 */
+	if (USB_EP_DIR_IS_IN(ep) && ep_state->ep_type != EP_TYPE_ISOC) {
+		k_sem_give(&ep_state->write_sem);
+	}
+
```
Comment (jfischer-no) [inline drivers/usb/device/usb_dc_stm32.c:750]: Instead of giving up, the driver could restart the current transfer. It is still unclear from your report what is going on with your device and host. There could be a check `if(!ep_state->ep_stalled)` to not call HAL_PCD_EP_ClrStall() if the Clear Feature request is spurious.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

**Review by jfischer-no — DISMISSED** [review]

**Review by nashif — DISMISSED** [review]

**Review by ydamigos — DISMISSED** [review]

**Comment by kartben** [comment]
Is this intentional that it's targeting the 3.7 branch? We would typically get the fix in the `main` branch and then backport.

**Comment by jfischer-no** [comment]
> Is this intentional that it's targeting the 3.7 branch? We would typically get the fix in the `main` branch and then backport.

Sorry, I did not notice it at all. @ptrcr ~~Please rebase on main branch.~~ Fixed it for you.

**Review by jfischer-no — APPROVED** [review]

**Review by marwaiehm-st — APPROVED** [review]

**Comment by kartben** [comment]
Thanks @jfischer-no :)

**Comment by ptrcr** [comment]
Sorry @jfischer-no I did not notice the edited version of your comment and rebased again.

**Comment by ptrcr** [comment]
@kartben Should I open another Pull Request to v3.7 branch once this PR is merged?

**Comment by kartben** [comment]
> @kartben Should I open another Pull Request to v3.7 branch once this PR is merged?

With the GitHub labels I just added, all the backport pull requests should be automatically created when this PR merges!

**Review by ydamigos — APPROVED** [review]

File: drivers/usb/device/usb_dc_stm32.c [hunk 3]
```diff
@@ -869,6 +869,10 @@ int usb_dc_ep_clear_stall(const uint8_t ep)
 		return -EINVAL;
 	}
 
+	if (!ep_state->ep_stalled) {
```
Comment (etienne-lms) [inline drivers/usb/device/usb_dc_stm32.c:872]: `if (ep_state->ep_stalled == 0U) {` ?

**(edited: fixed typo)**
