### PR TITLE
drivers: some minor fixes

### LINKED ISSUE #38125: [Coverity CID: 239582] Unchecked return value in drivers/display/ssd1306.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/fe2014ae1f4a7861771f86d500ac516fb5f59776/drivers/display/ssd1306.c

Category: Error handling issues
Function: `ssd1306_init`
Component: Drivers
CID: [239582](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=239582)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/fe2014ae1f4a7861771f86d500ac516fb5f59776/drivers/display/ssd1306.c#L411

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by gmarull**
Fixes #38125

### CODE REVIEW

File: drivers/display/ssd1306.c [hunk 1]
```diff
@@ -408,7 +408,13 @@ static int ssd1306_init(const struct device *dev)
 	}
 
 	if (config->reset.port) {
-		gpio_pin_configure_dt(&config->reset, GPIO_OUTPUT_INACTIVE);
+		int ret;
+
+		ret = gpio_pin_configure_dt(&config->reset,
+					    GPIO_OUTPUT_INACTIVE);
+		if (ret < 0) {
```
Comment (jfischer-no) [inline drivers/display/ssd1306.c:415]: Treat anything other than 0 (successful) as error.

**Review by jfischer-no — DISMISSED** [review]

File: drivers/display/ssd1306.c (hunk 1 above)
Comment (gmarull) [reply drivers/display/ssd1306.c:415]: As I already mentioned [here](https://github.com/zephyrproject-rtos/zephyr/pull/38021#discussion_r696761297) this is not something that should be done per function documentation:

```
 * @retval 0 If successful.
 * @retval -ENOTSUP if any of the configuration options is not supported
 *                  (unless otherwise directed by flag documentation).
 * @retval -EINVAL Invalid argument.
 * @retval -EIO I/O error when accessing an external GPIO chip.
 * @retval -EWOULDBLOCK if operation would block.
```

So `ret < 0` is perfectly correct, and I'm not willing to change it.

**Review by cfriedt — APPROVED** [review]

**Review by vanwinkeljan — APPROVED** [review]
