### PR TITLE
drivers: serial: nrf: Make pull-ups on UART pins configurable

### LINKED ISSUE #36782: drivers: serial: nrfx: Enforced pull-ups on RXD and CTS conflict on many custom boards
**Describe the bug**
After #36366 was merged RXD and CTS pins have configured pullups, while they were floating before. This PR solved an issue with UART interfaces not being connected to anything. In most embedded devices however UART is used to communicate with peripheral chips, like 4G modems, WiFi chips (ESP-AT), sensors, other MCUs, etc. In all those cases when UART is always connected, having pullups enabled increases average power consumption (UART signal needs to fight the pullup to set a defined state). Additionally some of the PCB designs and/or peripheral chips already have pullups or pulldowns already in hardware. In some cases this will mean that peripheral chip won't have enough signal strength to fight configured pullups. In other cases there might be pulldowns on those lines, conflicting with pullups configured in nRF MCU (which is the case in one of my custom boards, resulting non-working offloaded WiFi).

**To Reproduce**
Use Zephyr from tip of `main` branch.

**Expected behavior**
By default there should be no pull ups and no pull downs. This is the default for every GPIO when no DT flags are configured, so I expect the same behavior (floating lines) for UART IOs. Pullup or pulldown should be configured only on explicit request from user (e.g. by adding/configuring device-tree properties).

**Impact**
Showstopper for existing projects that rely on UART lines to be floating by default. As an example in one of the projects I am working on this breaks communication between nRF and ESP8266 (offloaded WiFi).

**Proposed solution**
Revert #36366 to have floating lines by default and implement device-tree flags for configuring pullups/pulldowns on user choice.

### PR DESCRIPTION
**Pull request by anangl**
This is a follow-up to commit 3656ba5ae9448f7132fe51dc4a595665e549fb84.

Do not enforce pull-up resistors to be enabled on RXD and CTS pins
in nRF UART drivers, as in certain hardware designs this may be
undesirable or may even make certain hardware not working.
Instead, provide devicetree properties that allow enabling of those
resistors when it is actually needed.

Fixes #36782

### CODE REVIEW

**Review by gmarull — APPROVED** [review]
LGTM, only one note: it looks like this changes the previous default (pull-ups ON), is this intended?

File: drivers/serial/uart_nrfx_uarte.c [hunk 1]
```diff
@@ -1954,6 +1948,11 @@ static int uarte_nrfx_pm_control(const struct device *dev,
 		    (UARTE_PROP(idx, pin_prop)),			       \
 		    (NRF_UARTE_PSEL_DISCONNECTED))
 
+#define UARTE_PULL(idx, pull_up_prop) \
+	COND_CODE_1(UARTE_HAS_PROP(idx, pull_up_prop), \
```
Comment (mbolivar-nordic) [inline drivers/serial/uart_nrfx_uarte.c:1952]: In general DT_PROP should be used instead of DT_HAS_PROP in the case of boolean properties. It will expand to 0 or 1 depending on if the property is present.

**Comment by nordic-krch** [comment]
What about adding these new properties to nordic DKs?

**Comment by anangl** [comment]
> LGTM, only one note: it looks like this changes the previous default (pull-ups ON), is this intended?

@gmarull Yes. The intent is to enable the pull-ups only when it is at least potentially necessary.

> What about adding these new properties to nordic DKs?

@nordic-krch I added a commit that enables pull-ups on pins assigned to UARTs that are not connected to anything on Nordic DKs. I don't think there's a need to enable pull-ups in other cases, in particular for UARTs that are connected to the Interface MCUs. Please have a look.

File: drivers/serial/uart_nrfx_uarte.c (hunk 1 above)
Comment (anangl) [reply drivers/serial/uart_nrfx_uarte.c]: Changed to `UARTE_PROP`.

**Review by mniestroj — APPROVED** [review]
LGTM. Thanks a lot!

File: drivers/serial/uart_nrfx_uart.c [hunk 2]
```diff
@@ -996,7 +996,9 @@ static int uart_nrfx_init(const struct device *dev)
 	nrf_gpio_cfg_output(TX_PIN);
 
 	if (RX_PIN_USED) {
-		nrf_gpio_cfg_input(RX_PIN, NRF_GPIO_PIN_PULLUP);
+		nrf_gpio_cfg_input(RX_PIN,
+			HAS_PROP(rx_pull_up) ? NRF_GPIO_PIN_PULLUP
```
Comment (mniestroj) [inline drivers/serial/uart_nrfx_uart.c:1000]: I've got a second look and propably this HAS_PROP needs to be replaced by PROP.

Comment (anangl) [reply drivers/serial/uart_nrfx_uart.c:1000]: Right. Thanks for catching this. I'll fix it promptly.

File: boards/arm/nrf21540dk_nrf52840/nrf21540dk_nrf52840.dts [hunk 3]
```diff
@@ -166,6 +166,7 @@ arduino_serial: &uart1 {
 	status = "okay";
 	current-speed = <115200>;
 	rx-pin = <33>;
+	rx-pull-up;
```
Comment (nordic-krch) [inline boards/arm/nrf21540dk_nrf52840/nrf21540dk_nrf52840.dts:169]: it should also be added to `uart0` which is connected to segger chip but becomes floating after flipping `nRF only` switch. Original fix was due to increased power consumption after flipping this switch.

Comment (anangl) [reply boards/arm/nrf21540dk_nrf52840/nrf21540dk_nrf52840.dts:171]: Updated.

**Review by mbolivar-nordic — APPROVED** [review]
