### PR TITLE
MCXN ethernet fixes and improvements

### LINKED ISSUE #92652: "No new RX buf available" error in sample Echo and HttpServer applications when running on FRDM_N947 boards
### Describe the bug

We've been struggling to get the NXP FRDM_N947 boards to run an http server with any reliability.

We've switched to the recent 4.2.00-rc1 tag as nothing works without the pull requests #91312 and #90181

Regardless we end up with RX buffer issues when payloads are greater than 131 bytes.

### Regression

- [ ] This is a regression.

### Steps to reproduce

To recreate the issue we simply build the unmodified Echo or HttpServer sample apps and run them on a board (only statis IP address config has changed to our network).

For the HttpServer, simply loading the sample app page starts with the uptime and network statistics being updated every seconds until it eventually freezes anywhere from 20 seconds to 4 mins. Once it stops, the console logging is printing out that it failed to allocate an Rx buffer.

For Echo, again using the latest codebase with only the IP address changed. We connect to the listening 4242 port with a C# client that is configurable to send different payload sizes in a repeated loop with controllable delay between the sends.

It generally fails with "No new RX buf available" after a few hundred sends on a single connection when the payload is greater than 131 bytes. Anything above 131 bytes fails reasonably quickly and anything below tends to work until I stop testing.

I've tried setting the TCP Window values to 500, 1000, 1500 and played with the network buffer size but those settings don't help any.

Example config changes

```
CONFIG_NET_BUF_DATA_SIZE=2048
CONFIG_NET_TCP_MAX_SEND_WINDOW_SIZE=1500
CONFIG_NET_TCP_MAX_RECV_WINDOW_SIZE=1500
```

### Relevant log output

```shell
IPV6_V6ONLY option is on, turning it off.
Sharing same socket between IPv6 and IPv4
Single-threaded TCP echo server waits for a connection on port 4242...
[00:00:00.602,000] <err> phy_mii: Failed to reset PHY (0): -116
*** Booting Zephyr OS build 4bd1d39c67df ***
[00:00:00.603,000] <inf> net_config: Initializing network
[00:00:00.603,000] <inf> net_config: IPv4 address: 10.80.80.80
[00:00:00.703,000] <inf> net_config: IPv6 address: 2001:db8::1
[00:00:00.703,000] <inf> net_config: IPv6 address: 2001:db8::1
[00:00:00.703,000] <dbg> net_sock: zsock_socket_internal: (0x30001a50): socket: ctx=0x300020d0, fd=3
[00:00:44.359,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:00:44.359,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:00:44.359,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
...
...
[00:01:28.493,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x3000860c, st=0, user_data=0
[00:01:28.538,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x300085c8, st=0, user_data=0
[00:01:28.539,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x3000860c, st=0, user_data=0
[00:01:28.540,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x300085c8, st=0, user_data=0
[00:01:28.541,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x3000860c, st=0, user_data=0
[00:01:28.541,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x300085c8, st=0, user_data=0
[00:01:28.542,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x3000860c, st=0, user_data=0
[00:01:28.543,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x300085c8, st=0, user_data=0
[00:01:28.544,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x3000860c, st=0, user_data=0
[00:01:28.547,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x300085c8, st=0, user_data=0
[00:01:28.547,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x30008694, st=0, user_data=0
[00:01:28.548,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x300085c8, st=0, user_data=0
[00:01:28.549,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x30008694, st=0, user_data=0
[00:01:28.550,000] <dbg> net_sock: zsock_received_cb: (0x30001748): ctx=0x30002178, pkt=0x300085c8, st=0, user_data=0
[00:01:31.784,000] <err> eth_nxp_enet_qos_mac: No new RX buf available
[00:01:31.784,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:31.784,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:31.784,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:31.884,000] <err> eth_nxp_enet_qos_mac: No new RX buf available
[00:01:31.884,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:31.884,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:31.884,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:31.985,000] <err> eth_nxp_enet_qos_mac: No new RX buf available
[00:01:31.985,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:31.985,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:31.985,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.085,000] <err> eth_nxp_enet_qos_mac: No new RX buf available
[00:01:32.085,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.085,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.085,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.186,000] <err> eth_nxp_enet_qos_mac: No new RX buf available
[00:01:32.186,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.186,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.186,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.287,000] <err> eth_nxp_enet_qos_mac: No new RX buf available
[00:01:32.288,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.288,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:32.288,000] <err> eth_nxp_enet_qos_mac: Rx descriptor does not have first descriptor flag, drop
[00:01:33.551,000] <err> eth_nxp_enet_qos_mac: No new RX buf available
[00:01:33.767,000] <err> eth_nxp_enet_qos_mac: No new RX buf available
---- Closed the serial port COM10 ----
```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

- OS: Windows 11
- Workspace: [4.2.00+0-rc1]
- Zephyr SDK: 0.17.0
- Commit/Tag: 4.2.00-rc1

### Additional Context

We are not modifying anything in the code or the hardware. clean code from 4.2.00-rc1 and default FRDM_N947 board from NXP.

Note:  <err> phy_mii: Failed to reset PHY (0): -116 doesn't look to be related but maybe the FRDM_N947 board DTS is missing setting the correct PHY driver, however packets are sending and receiving so looks like the chip (LAN8741) defaults work from reset.

### PR DESCRIPTION
**Pull request by decsny**
Main commit is to fix the deadlock causing everything to lock up randomly. (Fixes #92652)
```
There was a deadlock occurring, exposed by http server sample because of
situations like this caused by tx done work being blocked in deadlock:
1) The TX would be started by some thread and the driver TX sem would be
   taken.
2) The http server socket would get scheduled on the system workqueue to
   send something, claim the network TX interface mutex,
   and be blocked taking the semaphore.
3) The RX traffic class handler would get blocked trying to claim the
   network interface TX mutex, while trying to send an ACK in the TCP
   callback. This means the RX packets would not be processed.
4) Lots of RX unable to allocate packets errors would happen, and all RX
   would be dropped. This was the main symptom of the deadlock, which
   made it look like a memory leak but actually had nothing to do with
   the RX code nor any memory leak.
5) The TX DMA would finish and schedule the TX DMA done work onto the
   system work queue, behind the http server socket which is blocked on
   the waiting for the driver TX semaphore.
6) If the TX DMA done work would have ran, that's what gives the TX
   driver semaphore. So this is the reason for the deadlock of all these
   different threads and work items, the misqueue in the system
   workqueue.

Fix by just calling the TX DMA done code directly from the ISR, it
should be ISR safe, and really not a lot of code to execute, just
freeing some net buffers and the packet and updating the stats.
An optimization can be made later if needed, but for now,
solving the deadlock is a more urgent priority.
```

Rest of the commits are refactoring the RX code path, and some optimizations in the RX code path, namely:
1) Process as many descriptors as possible during the RX work, by walking through the whole descriptor ring until a DMA owned descriptor is reached, meaning we can even process descriptors that are sent by DMA while we are in the RX work handler.
2) Don't drop packets just because we didn't receive all the frames by the time the RX work runs. We can receive the frames and finish the packet once we get the rest of the frames. I don't see any valid reason for dropping the packet in that case as it was.

### CODE REVIEW

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 1]
```diff
@@ -141,12 +142,10 @@ static int eth_nxp_enet_qos_tx(const struct device *dev, struct net_pkt *pkt)
 	return 0;
 }
 
-static void tx_dma_done(struct k_work *work)
+static void tx_dma_done(const struct device *dev)
 {
-	struct nxp_enet_qos_tx_data *tx_data =
```
Comment (dleach02) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:146]: This change is avoiding using a workq to do packet reference freeing in the ISR. It is unfortunate that we can't use the workq for something that is truly a background low priority activity.

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:146]: An alternative which I considered if the optimization is important is to make another workqueue for the TX, but it seems a bit like overkill to have a whole thread just to do a bit of code that only does a few memory frees.

I think the http server is really more at fault here, as it was the thing blocking the system workqueue.  It seems like it shouldn't be an issue to give a semaphore from a sysworkq item, but I can see the argument now for sure that it could lead to confusing deadlocks in case of other programming mistakes. Seeing as how I spent basically a whole week trying to debug a memory leak in the RX code until realizing there was no memory leak and it was actually a  deadlock that had something to do with the TX side. So for the sake of avoiding more situations like this for people to debug, I think we might as well avoid it by not giving a semaphore from the wild west that could become of the system work queue.

**Review by mmahadevan108 — DISMISSED** [review]

**Comment by laodzu** [comment]
So I can confirm that this fixes the hangs on the frdm_mcxn947n board for me. Good work, thanks!

**Comment by decsny** [comment]
> So I can confirm that this fixes the hangs on the frdm_mcxn947n board for me. Good work, thanks!

I have just found this morning that by plugging into a newer more intense/busy network that there is still some problems getting exposed, which I am working on fixing, so I put a DNM until then. I actually already found/fixed one of the problems which was a subtle typo in this PR. But I am also finding some other really subtle issues that are rarely appearing. So I would not rely on this PR just yet.  I might add also a few other commits that add some new error handling code.

**Comment by decsny** [comment]
I think it was one of the optional commits that were optimizing the RX path were either introducing problems or exposing them due to things going through more continuously, so I just dropped them for now

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 2]
```diff
@@ -714,8 +737,12 @@ static int eth_nxp_enet_qos_mac_init(const struct device *dev)
 	/* Work upon a reception of a packet to a buffer */
 	k_work_init(&data->rx.rx_work, eth_nxp_enet_qos_rx);
 
-	/* Work upon a complete transmission by a channel's TX DMA */
-	k_work_init(&data->tx.tx_done_work, tx_dma_done);
+	/* This driver cannot work without interrupts. */
```
Comment (dleach02) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:740]: Why is this test moved to the bottom?

Comment (decsny) [reply drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:740]: see commit message

**Review by dleach02 — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by EmilioCBen — APPROVED** [review]
