### PR TITLE
usb: stm32h7: Add USB FS support for STM32H743/753

### LINKED ISSUE #33365: Add STM32H7 Series USB Device Support
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
This request addresses USB device driver support on the STM32H7 series. It is not currently supported by Zephyr.

**Describe why you are asking for this support?**
I have attempted to bring up USB device support myself (see below), but need help understanding where some of the pieces belong (clock and peripheral config) as well as hoping to get support from people more expert in the STM USB implementation.

I am willing, to the best of my abilities, to support this functionality if it makes it into Zephyr.

**Additional context**
[STM32H7 Overview](https://www.st.com/content/st_com/en/products/microcontrollers-microprocessors/stm32-32-bit-arm-cortex-mcus/stm32-high-performance-mcus/stm32h7-series.html)
[USB hardware and PCB guidelines using STM32 MCUs - Application note](https://www.st.com/content/ccc/resource/technical/document/application_note/group0/0b/10/63/76/87/7a/47/4b/DM00296349/files/DM00296349.pdf/jcr:content/translations/en.DM00296349.pdf)

**My Efforts So Far**
I have started work in [this development branch](https://github.com/JeremyBCD/zephyr/tree/initial-stm32h7-usb-support). I started with trying to bring up the USB FS peripheral on the NUCLEO-H753. I added it to the `stm32h7.dtsi` and to `nucleo_h753zi.dts`. (One area where I need help is in understanding how to populate some of the values in the DTS entry for this peripheral, how to find all of the appropriate register values).

With these changes, the `samples/subsys/usb/hid` sample would compile, but the peripheral failed to initialize.

```
[00:00:05.006,000] <dbg> main.main: Enabling usb...
[00:00:05.006,000] <dbg> usb_device.usb_enable: lock usb_enable_lock mutex
[00:00:05.006,000] <dbg> usb_dc_stm32.usb_dc_set_status_callback: 
[00:00:05.006,000] <dbg> usb_dc_stm32.usb_dc_attach: 
[00:00:05.006,000] <dbg> usb_dc_stm32.usb_dc_stm32_init: Pinctrl signals configuration
[00:00:05.006,000] <dbg> usb_dc_stm32.usb_dc_stm32_init: HAL_PCD_Init
[00:00:05.025,000] <err> usb_dc_stm32: PCD_Init failed, 1
[00:00:05.025,000] <dbg> usb_device.usb_enable: unlock usb_enable_lock mutex
[00:00:05.025,000] <err> main: Failed to enable USB
```

Comparing the init and config in Zephyr to a working USB STM32H7 project in STM32CubeIDE, I tried [adding some USB peripheral config](https://github.com/zephyrproject-rtos/zephyr/commit/cfbae200d207de127d75c561a923378947b6eef7#diff-7a5d66205e5accac60a0807d93fadb04c9143e0faa8e88ea7f47f7c6a5c378f6) that seemed to be missing for H7.

With these changes, the device will now initialize! There is even different behavior on startup if a USB host is attached. Specifically, the device is suspended.

```
[00:00:00.006,000] <dbg> main.main: Starting application
[00:00:05.006,000] <dbg> main.main: Enabling usb...
[00:00:05.006,000] <dbg> usb_device.usb_enable: lock usb_enable_lock mutex
[00:00:05.006,000] <dbg> usb_dc_stm32.usb_dc_set_status_callback: 
[00:00:05.006,000] <dbg> usb_dc_stm32.usb_dc_attach: 
[00:00:05.006,000] <dbg> usb_dc_stm32.usb_dc_stm32_init: Pinctrl signals configuration
[00:00:05.006,000] <dbg> usb_dc_stm32.usb_dc_stm32_init: HAL_PCD_Init
[00:00:05.059,000] <dbg> usb_dc_stm32.usb_dc_stm32_init: HAL_PCD_Start
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_configure: ep 0x00, previous ep_mps 64, ep_mps 64, ep_type 0
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_configure: ep 0x80, previous ep_mps 64, ep_mps 64, ep_type 0
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_set_callback: ep 0x00
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_set_callback: ep 0x80
[00:00:05.062,000] <dbg> usb_device.composite_setup_ep_cb: set cb, ep: 0x81
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_set_callback: ep 0x81
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_enable: ep 0x00
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_enable: HAL_PCD_EP_Open(0x00, 64, 0)
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_enable: ep 0x80
[00:00:05.062,000] <dbg> usb_dc_stm32.usb_dc_ep_enable: HAL_PCD_EP_Open(0x80, 64, 0)
[00:00:05.062,000] <dbg> usb_device.usb_enable: unlock usb_enable_lock mutex
[00:00:05.068,000] <dbg> usb_dc_stm32.HAL_PCD_SuspendCallback: 
[00:00:05.068,000] <inf> usb_hid: Device suspended
[00:00:05.068,000] <dbg> main.status_cb: status 5 unhandled
```

Unsurprisingly, the device does not enumerate.

At this point I'm not sure what's missing. Some fundamental incompatibility of the H7 USB device that's not obvious from looking at their header and example files, or something with the configuration of the Zephyr stack in terms of device registers, interrupts, and pinouts.

### PR DESCRIPTION
**Pull request by JeremyBCD**
Fixes: #33365

Changes are based on work by @IvoBCD and suggestions from @shlomow.

* Configures the STM32H7 USB2_OTG Peripheral in USB FS mode.
* Enabled for and tested on NUCLEO-H743 and NUCLEO-H753.
* Tested working with `hid` and `cdc_acm` samples.

### CODE REVIEW

File: drivers/usb/device/usb_dc_stm32.c [hunk 1]
```diff
@@ -293,11 +295,16 @@ static int usb_dc_stm32_clock_enable(void)
 #if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_usbphyc)
 	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_OTGHSULPI);
 	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_OTGPHYC);
+#else
+#ifdef CONFIG_SOC_SERIES_STM32H7X
+	__HAL_RCC_USB2_OTG_FS_ULPI_CLK_DISABLE();
+	__HAL_RCC_USB2_OTG_FS_ULPI_CLK_SLEEP_DISABLE();
```
Comment (erwango) [inline drivers/usb/device/usb_dc_stm32.c:301]: For coherency vs other parts of the driver, please use LL API : `LL_AHB1_GRP1_DisableClock(LL_AHB1_GRP1_PERIPH_USB2OTGHSULPI);`

File: drivers/usb/device/usb_dc_stm32.c [hunk 2]
```diff
@@ -375,6 +382,26 @@ static int usb_dc_stm32_init(void)
...
 
+#if defined(CONFIG_SOC_SERIES_STM32H7X)
+	/* Currently assuming FS mode. Need to disable the ULPI clock on USB2 and
+	 * enable the FS clock. Need to make this dependent on HS or FS config.
+	 */
+
+	__HAL_RCC_USB2_OTG_FS_ULPI_CLK_DISABLE();
+	__HAL_RCC_USB2_OTG_FS_ULPI_CLK_SLEEP_DISABLE();
+	__HAL_RCC_USB2_OTG_FS_CLK_ENABLE();
+	__HAL_RCC_USB2_OTG_FS_CLK_SLEEP_ENABLE();
```
Comment (erwango) [inline drivers/usb/device/usb_dc_stm32.c:393]: Please use LL API

File: dts/arm/st/h7/stm32h743.dtsi [hunk 3]
```diff
@@ -14,6 +14,20 @@
 				erase-block-size = <DT_SIZE_K(128)>;
 			};
 		};
+
+		usbotg_fs: usb@40080000 {
+			compatible = "st,stm32-otghs";
```
Comment (erwango) [inline dts/arm/st/h7/stm32h743.dtsi:19]:
```suggestion
			compatible = "st,stm32-otgfs";
```

File: drivers/usb/device/usb_dc_stm32.c (hunk 1 above)
Comment (erwango) [inline drivers/usb/device/usb_dc_stm32.c:301]: Please check if still required after fixing the compatible to "otgfs"

File: drivers/usb/device/usb_dc_stm32.c [hunk 4]
```diff
@@ -350,7 +357,7 @@ static int usb_dc_stm32_init(void)
 	usb_dc_stm32_state.pcd.Init.ep0_mps = PCD_EP0MPS_64;
 	usb_dc_stm32_state.pcd.Init.low_power_enable = 0;
 #else /* USB_OTG_FS || USB_OTG_HS */
-#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_otghs)
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_otghs) && !defined(CONFIG_SOC_SERIES_STM32H7X)
```
Comment (erwango) [inline drivers/usb/device/usb_dc_stm32.c:360]: Please check if still required after fixing compatible to otgfs

File: boards/arm/nucleo_h743zi/nucleo_h743zi.dts [hunk 5]
```diff
@@ -64,6 +64,11 @@
 	status = "okay";
 };
 
+&usbotg_fs {
```
Comment (erwango) [inline boards/arm/nucleo_h743zi/nucleo_h743zi.dts:67]: Please update boards documentation

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks fro this addition! This will be welcomed by H7 users.
I've left few comments, but mainline is:
- Fix compatible to otgfs and see what simplification this brings in the changes you've made
- Please use LL API when possible.

File: drivers/usb/device/usb_dc_stm32.c (hunk 1 above)
Comment (JeremyBCD) [reply drivers/usb/device/usb_dc_stm32.c]: I've switched everything to use the LL API.

File: drivers/usb/device/usb_dc_stm32.c (hunk 2 above)
Comment (JeremyBCD) [reply drivers/usb/device/usb_dc_stm32.c]: I've switched everything to use the LL API.

File: dts/arm/st/h7/stm32h743.dtsi (hunk 3 above)
Comment (JeremyBCD) [reply dts/arm/st/h7/stm32h743.dtsi]: Changed this and the interrupt name to use `fs` instead of `hs`.

File: drivers/usb/device/usb_dc_stm32.c (hunk 4 above)
Comment (JeremyBCD) [reply drivers/usb/device/usb_dc_stm32.c]: This was no longer necessary when using `otgfs`, removed.

File: boards/arm/nucleo_h743zi/nucleo_h743zi.dts (hunk 5 above)
Comment (JeremyBCD) [reply boards/arm/nucleo_h743zi/nucleo_h743zi.dts:67]: I've updated the doc and board yaml files to indicate `usb_device` support.

File: drivers/usb/device/usb_dc_stm32.c (hunk 1 above)
Comment (JeremyBCD) [reply drivers/usb/device/usb_dc_stm32.c]: This was no longer necessary with `otgfs`, removed.

**Comment by JeremyBCD** [comment]
@erwango Thank you for the review! Was able to switch to "otgfs" which did indeed simplify the changes. Switched everything to the LL API.

File: boards/arm/nucleo_h743zi/doc/index.rst [hunk 6]
```diff
@@ -123,6 +123,8 @@ features:
 +-------------+------------+-------------------------------------+
 | WATCHDOG    | on-chip    | independent watchdog                |
 +-------------+------------+-------------------------------------+
+| USB         | on-chip    | usb_device                          |
```
Comment (explora26) [inline boards/arm/nucleo_h743zi/doc/index.rst:126]:
```suggestion
| USB OTG FS  | on-chip    | USB device                          |
```

File: boards/arm/nucleo_h753zi/doc/index.rst [hunk 7]
```diff
@@ -121,6 +121,9 @@ features:
 +-----------+------------+-------------------------------------+
 | SPI       | on-chip    | spi                                 |
 +-----------+------------+-------------------------------------+
+| USB       | on-chip    | usb_device                          |
```
Comment (explora26) [inline boards/arm/nucleo_h753zi/doc/index.rst:124]:
```suggestion
| USB OTG FS| on-chip    | USB device                          |
```

File: boards/arm/nucleo_h753zi/doc/index.rst [hunk 8]
```diff
@@ -121,6 +121,9 @@ features:
...
++-----------+------------+-------------------------------------+
+
```
Comment (explora26) [inline boards/arm/nucleo_h753zi/doc/index.rst:126]: Remove this blank line
```suggestion

```

File: boards/arm/nucleo_h743zi/doc/index.rst (hunk 6 above)
Comment (JeremyBCD) [reply boards/arm/nucleo_h743zi/doc/index.rst:126]: I don't know that it makes sense to make this distinction here. "USB" versus "USB OTG FS". We don't make that level of distinction elsewhere. The "usb_device" is very specific, it matches our terminology elsewhere as well.

File: boards/arm/nucleo_h753zi/doc/index.rst (hunk 8 above)
Comment (JeremyBCD) [reply boards/arm/nucleo_h753zi/doc/index.rst:126]: Good catch, fixed.

File: boards/arm/nucleo_h753zi/doc/index.rst (hunk 7 above)
Comment (JeremyBCD) [reply boards/arm/nucleo_h753zi/doc/index.rst:124]: As above, I don't think this change is necessary.

File: drivers/usb/device/usb_dc_stm32.c [hunk 9]
```diff
@@ -321,7 +323,7 @@ static uint32_t usb_dc_stm32_get_maximum_speed(void)
 	if (!strncmp(USB_MAXIMUM_SPEED, "high-speed", 10)) {
 		speed = USB_OTG_SPEED_HIGH;
 	} else if (!strncmp(USB_MAXIMUM_SPEED, "full-speed", 10)) {
-#if USB_OTG_HS_EMB_PHY
+#if defined(CONFIG_SOC_SERIES_STM32H7X) || defined(USB_OTG_HS_EMB_PHY)
 		speed = USB_OTG_SPEED_HIGH_IN_FULL;
 #else
```
Comment (erwango) [inline drivers/usb/device/usb_dc_stm32.c:328]: This part is a little crap (using series Kconfig flag to modify dts extracted value), but I don't see better way to do it without modifying the code around.

**Review by erwango — APPROVED** [review]

**Review by loicpoulain — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

File: drivers/usb/device/usb_dc_stm32.c (hunk 9 above)
Comment (JeremyBCD) [reply drivers/usb/device/usb_dc_stm32.c:328]: Also, this, and some other parts, would need to get refactored to support actually running the device in high speed mode.

**Comment by BitLoose** [comment]
HI, does this support USB 2.0 Class 2 (i.e. 192 KHz audio) on the STM32H7 range of MCUs?
