### PR TITLE
misc: Add k_panic on assert

### LINKED ISSUE #12410: Assert and printk not printed on RTT
**Describe the bug**
Log messages are printed, but assert message is not printed out. As a result, it gives impression that device hanged, but does not give any clue why. You can see that it was an assertion, by opening debugger and stopping after the device hanged:
```
>> ninja debug
gdb> c
gdb> (CTRL + C)
```

**To Reproduce**
 Happens for any assert in Zephyr subsystems.
Can be reproduced on hello_world with small modification:

```
#include <zephyr.h>
#include <misc/printk.h>
#include <assert.h>

#define HELLO_LOG_LEVEL 4
#include <logging/log.h>
LOG_MODULE_REGISTER(hello, HELLO_LOG_LEVEL);

void main(void)
{
	for (int i=0; i<5; i++) {
		LOG_WRN("test %d", i);
	}

	k_sleep(100);

	__ASSERT(false, "Asserted!");

	printk("Hello World! %s\n", CONFIG_BOARD);
}
```

Output:
```
[00000000] <wrn> hello: test 0
[00000000] <wrn> hello: test 1
[00000000] <wrn> hello: test 2
[00000000] <wrn> hello: test 3
[00000000] <wrn> hello: test 4

```

Assert message `ASSERTION FAIL ...` is not printed. Is is the same with `__ASSERT_NO_MSG` or if instead of assert there is just a call to `printk()`;

**Environment:**
In configuration, printk is processed by logger: `CONFIG_LOG_PRINTK=y`

Full config:
```
CONFIG_ASSERT=y
CONFIG_ASSERT_LEVEL=2

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_RTT_MODE_DROP=y
CONFIG_LOG_MODE_NO_OVERFLOW=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_PRINTK_MAX_STRING_LENGTH=256
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_BACKEND_RTT_MESSAGE_SIZE=256
CONFIG_LOG_STRDUP_BUF_COUNT=64
CONFIG_LOG_STRDUP_MAX_STRING=64
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024

CONFIG_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
```

### PR DESCRIPTION
**Pull request by nordic-krch**
Replaced forever loop in assert with k_panic. Forever loop was preventing logs to be printed and had 
behavior dependent on the context (low prioriy thread - system continue to work, irq - system is blocked).

I've used `extern void k_panic(void)` though k_panic is a macro. That makes linker happy but not sure if that's the best we can have here. `__assert.h` is included by `kernel.h` so we cannot get `#include <kernel.h> here.

Fixes #12410.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by pdunaj — APPROVED** [review]

**Comment by pdunaj** [comment]
I would like to point out that this fix is very important. At the moment when FW is crashing on assert there is no indication of the problem. This is especially painful for long run tests.

If you think this could/should be fixed in a better way then my comment is:

- fix it like is now so we could have assert that works,
- work on the better fix later on if needed.

Unfortunately we (and I guess nobody who is doing any serious project using Zephyr) cannot wait weeks for working assert.

File: include/misc/__assert.h [hunk 1]
```diff
@@ -86,10 +86,9 @@
 extern void posix_exit(int exit_code);
 #define __ASSERT_POST posix_exit(1)
 #else
+extern void k_panic(void);
```
Comment (andrewboie) [inline include/misc/__assert.h]: This is definitely not going to work, the build is going to look for a symbol at link time, but instead we need the expansion:

`#define k_panic()	_k_except_reason(_NANO_ERR_KERNEL_PANIC)`

Which gets expanded again as _k_except_reason is itself a macro.

Need to shuffle includes around to make this work.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]

File: include/misc/__assert.h (hunk 1 above)
Comment (nordic-krch) [reply include/misc/__assert.h]: yes, it does not work. not sure why it compiled in one example i've tried initially. Instead of shuffling includes i could make assert.c file with `void assert_post_action()`. What do you think?

Comment (andrewboie) [reply include/misc/__assert.h]: I'm not quite sure I understand what you are proposing but the test you want to run to prove your changes work is tests/kernel/fatal

**Comment by nordic-krch** [comment]
i would like to standarize assert behavior as current forever loop is not desired. Moving post action behavior to c file will solve includes problem.

Pobierz aplikację Outlook dla systemu iOS<https://aka.ms/o0ukef>

________________________________
Od: Andrew Boie <notifications@github.com>
Wysłano: poniedziałek, stycznia 28, 2019 7:21 PM
Do: zephyrproject-rtos/zephyr
DW: Chruściński, Krzysztof; Author
Temat: Re: [zephyrproject-rtos/zephyr] misc: Add k_panic on assert (#12732)


@andrewboie commented on this pull request.

________________________________

In include/misc/__assert.h<https://github.com/zephyrproject-rtos/zephyr/pull/12732#discussion_r251534407>:

> @@ -86,10 +86,9 @@
 extern void posix_exit(int exit_code);
 #define __ASSERT_POST posix_exit(1)
 #else
+extern void k_panic(void);


I'm not quite sure I understand what you are proposing but the test you want to run to prove your changes work is tests/kernel/fatal

**Comment by nordic-krch** [comment]
Created `lib/os/assert.c` with `assert_post_action()` function. This way there is no include ordering issue.

**Comment by Qbicz** [comment]
Thanks for this fix @nordic-krch. I can build it. However, when I run test as described in #12410, assert is not printed and also any log/printk before assert is not printed out. Execution reaches `_NanoFatalErrorHandler` and `LOG_PANIC()`, but when it enters `log_process()`, it thinks no backend is attached and returns before processing messages.

At the same time, adding `k_sleep(100)` just before assert makes it work:
```
ASSERTION FAIL [0] @ ../../src/main.c:15
***** Kernel Panic! *****
Current thread ID = 0x20004cf8
Faulting instruction address = 0x6ff4
```

Tested on nRF52840.

**Comment by nordic-krch** [comment]
@Qbicz thanks for trying it out. What you see is not related to that issue. I've created bug for that: #12851

**Comment by Qbicz** [comment]
You are right, this is a separate issue. Looks fine for me.

**Review by Qbicz — APPROVED** [review]

**Comment by Qbicz** [comment]
@andrewboie can you revisit?

**Review by tyrantlizard77 — APPROVED** [review]
