### PR TITLE
soc: arm: stm32[l4|wb]: fix power state exit

### LINKED ISSUE #26896: STM32: mcu goes to sleep inadvertently when using PM.
**Describe the bug**
When using the (experimental) STM32L4 power management, the `deepsleep` enable bit (sleep in Zephyr terms) is not set back to `sleep` (idle in zephyr terms) when waking up, resulting in the next `WFI` call also going to sleep.

**To Reproduce**
1. use stm32l* PM
2. Do a long wait to go to sleep.
3. Do a short wait that should not go do sleep but idle.
4. System goes to sleep anyway

**Expected behavior**
System only goes to sleep when executing `sys_set_power_state` with the appropriate power state.

**Fix**

In the soc specific power.c, add  `LL_LPM_EnableSleep` to `_sys_pm_power_state_exit_post_ops`. This sets the system configuration bit to use regular sleep (idle) instead of deepsleep when executing WFI.

I found this bug while porting powermanagement to the STM32L5, but I think the behavior should be the same on the other STM32 cores.

edit: fixed some potential confusion with idle/sleep/deepsleep terminology.

### PR DESCRIPTION
**Pull request by jdascenzio**
When we wake-up of deep sleep power state, we want to disable it.
Otherwise, when the cpu will go next to idle mode during a
SYS_POWER_STATE_ACTIVE, it will go into deep sleep mode
instead of a sleep mode.

fixes: #26896

Signed-off-by: Julien D'Ascenzio <jdascenzio@paratronic.fr>

### CODE REVIEW

**Review by FRASTM — APPROVED** [review]

**Comment by erwango** [comment]
@jdascenzio can you add `fixes: https://github.com/zephyrproject-rtos/zephyr/issues/26896` to your issue?
This would help getting it merged for current release

**Comment by jdascenzio** [comment]
> @jdascenzio can you add `fixes: #26896` to your commit message?
> This would help getting it merged for current release

I add `fixes: #26896` to the commit message.
I hadn't seen that this problem had already been discovered ...

File: soc/arm/st_stm32/stm32l4/power.c [hunk 1]
```diff
@@ -93,6 +93,7 @@ void _sys_pm_power_state_exit_post_ops(enum power_states state)
 	case SYS_POWER_STATE_SLEEP_3:
 #endif /* CONFIG_HAS_SYS_POWER_STATE_SLEEP_3 */
 		LL_LPM_DisableSleepOnExit();
+		LL_LPM_EnableSleep();
```
Comment (erwango) [inline soc/arm/st_stm32/stm32l4/power.c:96]: Would you be able to check if the problem also applies to stm32wb series (the other series power enabled in zephyr)?

Comment (jdascenzio) [reply soc/arm/st_stm32/stm32l4/power.c:96]: It's the same cortex M4, so in my opinion, It must affect stm32wb series too but I don't have a board with STM32WB to test it.... Do you want me to make the same patch for stm32wb and integrate it into this commit?

Comment (FRASTM) [reply soc/arm/st_stm32/stm32l4/power.c:96]: yes, please @jdascenzio, could you apply this for the stm32wb as well.
Both soc have similar power saving mgt, so `LL_LPM_EnableSleep();`  is applicable to power.c of the stm32wb on `_sys_pm_power_state_exit_post_ops`

**Comment by jdascenzio** [comment]
I added stm32wb to the patch

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
maybe could the PR title also mention stm32WB

**Review by MaureenHelm — APPROVED** [review]
