### PR TITLE
Bluetooth: BAP: Add control point cbs to BASS

### LINKED ISSUE #82921: The bap scan delegator module's remove source operation does not return a gatt error when the sink is PA and/or BIS synchronized as it should according to the BAP spec
# The bap scan delegator module's remove source operation does not return a gatt error when the sink is PA and/or BIS synchronized as it should according to the BAP spec

**Describe the bug**

The BAP specicification version 1.02 section 6.5.8. says the following:

*The Broadcast Assistant shall initiate the Remove Source operation only if the Broadcast Assistant has determined that the Scan Delegator collocated with the Broadcast Sink is not synchronized to a PA and/or a BIS, as defined by the values of the PA_Sync_State field and/or the BIS_Sync_State[i] field for the Broadcast Receive State characteristic, which contains the Source_ID that the Broadcast Assistant intends to use in the Remove Source operation.*

The function scan_delegator_rem_src is used to handle the remove source operation initiated by a broadcast assistant.

The current version of the bap_scan_delegator function scan_delegator_rem_src terminates periodic advertisement synchronization if it is active. But section 6.5.8 in the bap specification version 1.0.2 says that the broadcast assistant must only remove the source if the broadcast assistant has determined that the sink is neither periodic advertisement synkronized and/or bis synkronised.

The scan_delegator_rem_src function should therefore not terminate any synkronization, but return a gatt error instead.

**To Reproduce**

Setup:

* 1 Broadcast source.
* 1 Broadcast assistant.
* 1 Broadcast sink with the BASS service.

1. Use the assistant to add and start bis synkronization with the broadcast source.
2. Use the assistant to remove the source.
   1. This should make the broadcast sink return a gatt error to the assistant. But it does not.

**Expected behavior**

That the broadcast sink returns a gatt error when the broadcast assistant attempts to remove a source that is periodical advertisement synkronized and/or BIS synkronized.

**Impact**

1. The BAP specification for the remove source operation is not followed.
2. Broadcast assistant developer are not made aware that the BAP specification is not followed for the remove operation because they do not get a gatt error.

**Logs and console output**

None.

**Environment (please complete the following information):**

 - OS: Zephyr
 - Zephyr
 - SHA:e1b43207224e2226dc692bd294afaf869e05a201

**Additional context**

None.

### PR DESCRIPTION
**Pull request by niym-ot**
For the control point operations, add/modify/
remove source, callbacks are added so that Application can decide whether to accept/reject the control point operations.

Fixes: #82921

### CODE REVIEW

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 1]
```diff
@@ -970,6 +979,16 @@ static int scan_delegator_mod_src(struct bt_conn *conn,
 		}
 	}
 
+	if (scan_delegator_cp_cbs != NULL && scan_delegator_cp_cbs->modify_source != NULL) {
+		err = scan_delegator_cp_cbs->modify_source(conn, state);
+		if (err < 0) {
+			LOG_DBG("Modify Source rejected with reason %d", err);
+			(void)memcpy(state, &backup_state, sizeof(backup_state));
+			k_mutex_unlock(&internal_state->mutex);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:987]: Missing error check for `k_mutex_unlock` - Suggest to just add an ASSERT for this

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 2]
```diff
@@ -1121,6 +1140,16 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
 
 	state = &internal_state->state;
 
+	if (conn != NULL && scan_delegator_cp_cbs != NULL &&
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1143]: Could you move the comment below for `conn == NULL` up to this? 

Also consider making a single `conn != NULL` block and merge the callback and the PA sync stuff into that

**Review by Thalley — CHANGES_REQUESTED** [review]
Some minor comments, but otherwise LGTM

File: include/zephyr/bluetooth/audio/bap.h [hunk 3]
```diff
@@ -793,6 +793,59 @@ struct bt_bap_scan_delegator_cb {
...
+	 * through the BASS Control Point Add Source procedure.
+	 *
+	 * @param conn       Pointer to the connection that initiated the request,
+	 *                   or NULL if locally triggered.
+	 * @param recv_state Pointer to the requested receive state to be added.
+	 *
+	 * @return 0 to accept, or negative error code to reject.
+	 */
+	int (*add_source)(struct bt_conn *conn,
+			  const struct bt_bap_scan_delegator_recv_state *recv_state);
```
[the remark this answers is not in the document]
Comment (niym-ot) [reply include/zephyr/bluetooth/audio/bap.h:817]: Will modify to return the GATTATT error

For this "We may also need to consider that BASS on Zephyr (today) supports both write with, and without response, and that a reject may not reach the client.",  how should we proceed ?

[the remark this answers is not in the document]
Comment (Thalley) [reply include/zephyr/bluetooth/audio/bap.h:817]: > how should we proceed ?

Good question :) 

Could be that we just do nothing - If the client writes without response, we can't really do anything about it anyhow.

File: include/zephyr/bluetooth/audio/bap.h [hunk 4]
```diff
@@ -793,6 +793,59 @@ struct bt_bap_scan_delegator_cb {
...
+	 *
+	 * These callbacks notify the application when a request comes
+	 * in to add a source. The application can return BT_ATT_ERR_SUCCESS to
+	 * accept or a valid GATT/ATT error code to reject the request.
+	 *
+	 * @param conn       Pointer to the connection that initiated the request,
+	 *                   or NULL if locally triggered.
+	 * @param recv_state Pointer to the requested receive state to be added.
+	 *
+	 * @return BT_ATT_ERR_SUCCESS to accept, or a valid GATT/ATT error code to reject.
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:812]: It needs to be either a GATT or an ATT error code. 

ATT error codes are positive, but `BT_GATT_ERR` negates it. 
For `BT_ATT_ERR_SUCCESS` it doesn't matter, but it does when we return the value in the function. 

Looking at the code, it seems that it shall be a BT_ATT_ERR value, and not a negative value since you always apply `BT_GATT_ERR` on it

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 5]
```diff
@@ -743,6 +744,14 @@ static int scan_delegator_add_src(struct bt_conn *conn,
 			     subgroup->metadata_len);
 	}
 
+	if (scan_delegator_cp_cbs != NULL && scan_delegator_cp_cbs->add_source != NULL) {
+		err = scan_delegator_cp_cbs->add_source(conn, state);
+		if (err != BT_ATT_ERR_SUCCESS) {
+			LOG_DBG("add_source callback rejected: 0x%02x", err);
+			return BT_GATT_ERR(err);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:751]: If the application returns e.g. `-1` (for some reason), this will end up being `1` which will return a success to the remote device. 

We could consider doing
```suggestion
			return err > 0 ? BT_GATT_ERR(err) : err;
```

To convert it to an negative value if not already, as a precaution. What do you think?

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 6]
```diff
@@ -1122,22 +1144,38 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
...
+			err = pa_sync_term_request(conn, &internal_state->state);
+			if (err != 0) {
+				LOG_DBG("PA sync term from %p was rejected with reason %d", (void *)conn,
+					err);
 
-		k_mutex_lock(&internal_state->mutex, K_FOREVER);
+				return BT_GATT_ERR(BT_ATT_ERR_WRITE_REQ_REJECTED);
+			}
+
+			k_mutex_lock(&internal_state->mutex, K_FOREVER);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1177]: Missing error check for `k_mutex_lock`. I am aware that you just moved it, but we should do an `_ASSERT(mutex_err == 0, "Failed to lock mutex: %d", mutex_err);` check here as well

File: include/zephyr/bluetooth/audio/bap.h (hunk 4 above)
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:812]:
```suggestion
	 * @return BT_ATT_ERR_SUCCESS to accept, or a valid BT_ATT_ERR_* error code to reject.
```

Should be written for all of them

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 7]
```diff
@@ -743,6 +744,14 @@ static int scan_delegator_add_src(struct bt_conn *conn,
 			     subgroup->metadata_len);
 	}
 
+	if (scan_delegator_cp_cbs != NULL && scan_delegator_cp_cbs->add_source != NULL) {
+		err = scan_delegator_cp_cbs->add_source(conn, state);
+		if (err != BT_ATT_ERR_SUCCESS) {
+			LOG_DBG("add_source callback rejected: 0x%02x", err);
+			return err > 0 ? BT_GATT_ERR(err) : err;
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:751]:
```suggestion
			/* Convert to a negative value if not already */
			return err > 0 ? BT_GATT_ERR(err) : err;
```

One alternative we can also consider is to assert on a negative value if we expect a BT_ATT_ERR value.

Comment (niym-ot) [reply subsys/bluetooth/audio/bap_scan_delegator.c:751]: As you told , Application tend to send -1 as error codes. Do we have to assert or can we convert as above ? what you think

Comment (Thalley) [reply subsys/bluetooth/audio/bap_scan_delegator.c:751]: I think it's fair with an assert when we document it. 

The problem with a blind conversion is that `-1` would end up as `BT_ATT_ERR_INVALID_HANDLE`, which may/may not be a spec violation. I don't know if there are any specific rules w.r.t. sending ATT error responses. 

Your first iteration that just sent `BT_ATT_ERR_WRITE_REQ_REJECTED` made sense as well, as that is semantically what is going on. The only return values that makes sense for the application to send is `BT_ATT_ERR_WRITE_REQ_REJECTED`, `BT_ATT_ERR_PROCEDURE_IN_PROGRESS` and possibly `BT_ATT_ERR_UNLIKELY`, where `BT_ATT_ERR_WRITE_REQ_REJECTED` is likely the only one that will really get used. 

We could also force, via asserts or other methods, to only allow one of the 2/3 above, but it also seems like an unnecessary restriction.

File: include/zephyr/bluetooth/audio/bap.h [hunk 8]
```diff
@@ -2527,6 +2580,38 @@ int bt_bap_scan_delegator_register(struct bt_bap_scan_delegator_cb *cb);
...
+ * Only a single callback structure can be registered at a time.
+ * Attempting to register when one is already set will return -EALREADY.
+ *
+ * Passing a NULL pointer will result in -EINVAL being returned.
+ *
+ * @param cb Pointer to a structure containing the callbacks.
+ *
+ * @return 0 on success,
+ *         -EINVAL if @p cb is NULL,
+ *         -EALREADY if callbacks have already been registered.
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:2598]:
```suggestion
 * @retval 0 Success,
 * @retval -EINVAL @p cb is NULL,
 * @retval -EALREADY Callbacks have already been registered.
```

File: include/zephyr/bluetooth/audio/bap.h [hunk 9]
```diff
@@ -2527,6 +2580,38 @@ int bt_bap_scan_delegator_register(struct bt_bap_scan_delegator_cb *cb);
...
+
+/**
+ * @brief Unregister Scan Delegator callbacks.
+ *
+ * This function unregisters the previously registered callbacks for the Scan Delegator.
+ *
+ * @param cb Pointer to the callback structure to unregister.
+ *           Must match the one previously registered.
+ *
+ * @return 0 on success, -EINVAL if cb is NULL or doesn't match the registered callbacks.
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:2610]:
```suggestion
 * @retval 0 Success
 * @retval -EINVAL @p cb is NULL or doesn't match the registered callbacks.
```

File: include/zephyr/bluetooth/audio/bap.h [hunk 10]
```diff
@@ -793,6 +793,59 @@ struct bt_bap_scan_delegator_cb {
 	void (*scanning_state)(struct bt_conn *conn, bool is_scanning);
 };
 
+/**
+ * @brief Struct to hold callbacks for the Scan Delegator
+ *
+ */
+struct bt_bap_scan_delegator_cp_cb {
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:800]: Why do we need a new struct for this btw? Why not use `bt_bap_scan_delegator_cb`?

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 11]
```diff
@@ -1122,22 +1148,39 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
...
 
-			return BT_GATT_ERR(BT_ATT_ERR_WRITE_REQ_REJECTED);
-		}
+			/* Terminate PA sync */
+			err = pa_sync_term_request(conn, &internal_state->state);
+			if (err != 0) {
+				LOG_DBG("PA sync term from %p was rejected with reason %d",
+					(void *)conn, err);
+				return BT_GATT_ERR(BT_ATT_ERR_WRITE_REQ_REJECTED);
+			}
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1179]: It's interesting that we now mix return value types. Is that intentional? Should we be consistent?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 11 above)
Comment (niym-ot) [reply subsys/bluetooth/audio/bap_scan_delegator.c:1179]: this was part of the code which was already there. should i change to BT_GATT_ERR(err)

File: include/zephyr/bluetooth/audio/bap.h (hunk 10 above)
Comment (niym-ot) [reply include/zephyr/bluetooth/audio/bap.h:800]: As discussed initially, this struct was to separate out the external requests coming in (add/modify/rem).

Comment (Thalley) [reply include/zephyr/bluetooth/audio/bap.h:800]: But why do we need a separate struct for this? Other requests are already handled by `bt_bap_scan_delegator_cb`, so why not extend that instead?

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 11 above)
Comment (niym-ot) [reply subsys/bluetooth/audio/bap_scan_delegator.c:1179]: to make it consistent, will set to BT_GATT_ERR(BT_ATT_ERR_WRITE_REQ_REJECTED)

Comment (Thalley) [reply subsys/bluetooth/audio/bap_scan_delegator.c:1179]: Right, then we just treat any non-0 value as an error (of course that brings us back to whether the return type should be boolean, but let's just keep it as an int for consistency with the other existing callbacks for now)

File: include/zephyr/bluetooth/audio/bap.h [hunk 12]
```diff
@@ -791,6 +791,52 @@ struct bt_bap_scan_delegator_cb {
...
+	 *
+	 * These callbacks notify the application when a request comes
+	 * in to add a source. The application can return BT_ATT_ERR_SUCCESS to
+	 * accept or any non-zero value to reject the request.
+	 *
+	 * @param conn       Pointer to the connection that initiated the request,
+	 *                   or NULL if locally triggered.
+	 * @param recv_state Pointer to the requested receive state to be added.
+	 *
+	 * @return BT_ATT_ERR_SUCCESS to accept, or any non-zero value to reject.
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:805]: Suggest to adopt and be consistent with the above callbacks:
```suggestion
	 * @return 0 in case of accept, or other value to reject.
```

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 13]
```diff
@@ -743,6 +743,14 @@ static int scan_delegator_add_src(struct bt_conn *conn,
 			     subgroup->metadata_len);
 	}
 
+	if (scan_delegator_cbs != NULL && scan_delegator_cbs->add_source != NULL) {
+		err = scan_delegator_cbs->add_source(conn, state);
+		if (err != BT_ATT_ERR_SUCCESS) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:748]: Ditto here for consistency:
```suggestion
		if (err != 0) {
```

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 14]
```diff
@@ -1122,22 +1143,37 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
...
-		/* Terminate PA sync */
-		err = pa_sync_term_request(conn, &internal_state->state);
-		if (err != 0) {
-			LOG_DBG("PA sync term from %p was rejected with reason %d", (void *)conn,
-				err);
+		if (state->pa_sync_state == BT_BAP_PA_STATE_INFO_REQ ||
+			state->pa_sync_state == BT_BAP_PA_STATE_SYNCED) {
+			/* Unlock mutex to avoid potential deadlock on app callback */
+			err = k_mutex_unlock(&internal_state->mutex);
+			__ASSERT(err == 0, "Failed to unlock mutex: %d", err);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1164]: @jthm-ot added the unlock of the mutex before calling the app callbacks. I assume we should be consistent here as well? 

Either we always unlock the mutex first, or we don't.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 15]
```diff
@@ -970,6 +978,31 @@ static int scan_delegator_mod_src(struct bt_conn *conn,
...
+		if (err != 0) {
+			LOG_DBG("Modify Source rejected with reason 0x%02x", err);
+
+			err = k_mutex_lock(&internal_state->mutex, SCAN_DELEGATOR_BUF_SEM_TIMEOUT);
+			__ASSERT(err == 0, "Failed to lock mutex: %d", err);
+
+			(void)memcpy(state, &backup_state, sizeof(backup_state));
+
+			err = k_mutex_unlock(&internal_state->mutex);
+			__ASSERT(err == 0, "Failed to unlock mutex: %d", err);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:997]: This can be tricky. 

If the application called any function in `scan_delegator_cbs->modify_source` that modifies the state, then the receive state:

 - Starts in State A (backup_state is in State A
 - The receive state updates to State B while parsing the request
 - scan_delegator_cbs->modify_source calls `bt_bap_scan_delegator_mod_src` and the receive state ends up in State C but the application, for some reason, returns an error code here, and we store receive state to state A, but where we have sent a notification to the remote device when we switched to state C. 

So not only do we risk reverting the change done in the call to `bt_bap_scan_delegator_mod_src`, we also change the state back to a different state than what `bt_bap_scan_delegator_mod_src` have triggered a notification for. Depending on the configured thread priorities, the notification may be sent before we store the state. 

When we do `(void)memcpy(state, &backup_state, sizeof(backup_state));` we could could clear the `updated` flag, but only if the flag was not set at the beginning of this function... 

It's quite messy that we allow state changes (via `bt_bap_scan_delegator_mod_src`) in callbacks. 
@jthm-ot @niym-ot  what do you think we should do here? 

An "easy" solution is to keep the mutex while we call the callback and thus not allow state-change functions to be called while in callbacks.

Comment (niym-ot) [reply subsys/bluetooth/audio/bap_scan_delegator.c]: Mutex is kept on hold while calling the app callbacks

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 16]
```diff
@@ -1122,22 +1145,41 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
...
-		__ASSERT(err == 0, "Failed to unlock mutex: %d", err);
+	if (conn != NULL) {
 
-		/* Terminate PA sync */
-		err = pa_sync_term_request(conn, &internal_state->state);
-		if (err != 0) {
-			LOG_DBG("PA sync term from %p was rejected with reason %d", (void *)conn,
-				err);
+		if (scan_delegator_cbs != NULL &&
+			scan_delegator_cbs->remove_source != NULL) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1151]:
```suggestion
		if (scan_delegator_cbs != NULL && scan_delegator_cbs->remove_source != NULL) {
```

Maximum column width is 100 in Zephyr

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 17]
```diff
@@ -1122,22 +1145,41 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
...
 
-		k_mutex_lock(&internal_state->mutex, K_FOREVER);
+			err = scan_delegator_cbs->remove_source(conn, src_id);
+			if (err != 0) {
+				LOG_DBG("Remove Source rejected with reason 0x%02x", err);
+				return BT_GATT_ERR(BT_ATT_ERR_WRITE_REQ_REJECTED);
+			}
+
+			err = k_mutex_lock(&internal_state->mutex, SCAN_DELEGATOR_BUF_SEM_TIMEOUT);
+			__ASSERT(err == 0, "Failed to lock mutex: %d", err);		}
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1164]: Shouldn't the mutex be kept here as well?

Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1164]: The end bracket should be on the next line

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 18]
```diff
@@ -1122,22 +1145,41 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
...
+
+		if (state->pa_sync_state == BT_BAP_PA_STATE_INFO_REQ ||
+			state->pa_sync_state == BT_BAP_PA_STATE_SYNCED) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1167]:
```suggestion
		if (state->pa_sync_state == BT_BAP_PA_STATE_INFO_REQ ||
		    state->pa_sync_state == BT_BAP_PA_STATE_SYNCED) {
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 19]
```diff
@@ -1122,22 +1145,35 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
...
+			err = pa_sync_term_request(conn, &internal_state->state);
+			if (err != 0) {
+				LOG_DBG("PA sync term from %p was rejected with reason %d",
+					(void *)conn, err);
+				return BT_GATT_ERR(BT_ATT_ERR_WRITE_REQ_REJECTED);
+			}
 
-		k_mutex_lock(&internal_state->mutex, K_FOREVER);
+			err = k_mutex_lock(&internal_state->mutex, SCAN_DELEGATOR_BUF_SEM_TIMEOUT);
+			__ASSERT(err == 0, "Failed to lock mutex: %d", err);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1175]: What about here with the mutex as well? 

I think we should either keep the mutex for all callbacks, or none of them, since they are called in the same context.

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 20]
```diff
@@ -970,6 +979,19 @@ static int scan_delegator_mod_src(struct bt_conn *conn,
 		}
 	}
 
+	if (scan_delegator_cbs != NULL && scan_delegator_cbs->modify_source != NULL) {
+		err = scan_delegator_cbs->modify_source(conn, state);
+		if (err != 0) {
+			LOG_DBG("Modify Source rejected with reason 0x%02x", err);
+			(void)memcpy(state, &backup_state, sizeof(backup_state));
+
+			err = k_mutex_unlock(&internal_state->mutex);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_scan_delegator.c:988]: Not specifically related to this line but I just remembered: 

```c
 * A thread is permitted to lock a mutex it has already locked. The operation
 * completes immediately and the lock count is increased by 1.
```

So the issue stated by https://github.com/zephyrproject-rtos/zephyr/pull/89466#discussion_r2079761922 isn't solvable by mutexes :( If we want to reject application modifying the receive state in the callbacks, then I think we need to apply a different lock.

Comment (niym-ot) [reply subsys/bluetooth/audio/bap_scan_delegator.c]: Semaphore Approach is used

Excerpt from discussion with Emil
https://discord.com/channels/720317445772017664/1370333359343013979

Many Approaches like additional mutexes, a semaphore, atomic variables or even just a good old bool is possible

The lock approach is the simpler of the 2, but also more restraining. Today we are doing 
1) Incoming request
2) Parse request and add/update receive state
3) Provide the receive state to app and ask for accept, and if rejected, restore state

It should be possible to do 
1) Incoming request
2) Parse request 
3) Provide the request to app and ask for accept, and if rejected, return error
4) If not rejected, add/update the state

Another approach is the larger change to not do any local changes to receives states until the application has accepted the requests. There's no risk of the application doing any weird stuff to the receive state in the callbacks, as the stack does not yet hold ownership of it. The downside of option 2 (besides the additional work), is that we cannot verify the request against the receive state before calling the new callbacks you are requesting, as the receive state may still change in the app callback (unless we take ownership at the beginning of the request and then we are back to where the application cannot modify the receive state in the callback).

**Review by Thalley — COMMENTED** [review]
Overall changes LGTM, but seems to have broken a BSIM test. Please let me know if you need help with this

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 20 above)
Comment (niym-ot) [reply subsys/bluetooth/audio/bap_scan_delegator.c:988]: As discussed,
Changing to Semaphore have more challenges at Application level
Sticking to mutex solution while we discuss a better overall solution (Asynchronous callbacks)

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 21]
```diff
@@ -1122,22 +1145,30 @@ static int scan_delegator_rem_src(struct bt_conn *conn,
...
+				__ASSERT(err == 0, "Failed to unlock mutex: %d", err);
+				return BT_GATT_ERR(BT_ATT_ERR_WRITE_REQ_REJECTED);
+			}
 		}
 
-		k_mutex_lock(&internal_state->mutex, K_FOREVER);
+		if (state->pa_sync_state == BT_BAP_PA_STATE_INFO_REQ ||
+		    state->pa_sync_state == BT_BAP_PA_STATE_SYNCED) {
+			/* Terminate PA sync */
+			err = pa_sync_term_request(conn, &internal_state->state);
```
Comment (jthm-ot) [inline subsys/bluetooth/audio/bap_scan_delegator.c:1163]: You have chosen to keep the mutex locked on pa_sync_term_request call (-> pa_sync_term_req callback). I think it will be ok and then only unlock mutex before pa_sync_request call where there is a pontial risk of deadlock. To be consistent you should then remove the mutex unlock the other place where pa_sync_tern_request is called (scan_delegator_mod_src)

**Review by jthm-ot — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 21 above)
Comment (Thalley) [reply subsys/bluetooth/audio/bap_scan_delegator.c:1163]: Can you elaborate on when the deadlock can happen?

Comment (Thalley) [reply subsys/bluetooth/audio/bap_scan_delegator.c:1163]: Nvm: If the application waits for a condition in the callback, then there can be a deadlock indeed. 

e.g.
1) pa_sync_term_request called with mutex taken
2) Application triggers a k_work item in the callback and blocks the callback until the item has finished
3) The k_work item calls a Scan Delegator API function, which will fail
4) The block from 2) is never lifted

So that can be a deadlock indeed, but arguably only if the application does 2 things wrong: A) it blocks in a callback in the BT RX thread, and B) it does not lift the block when the error happens

Or did you have another scenario in mind?

**Review by Thalley — APPROVED** [review]

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 21 above)
Comment (niym-ot) [reply subsys/bluetooth/audio/bap_scan_delegator.c:1157]: made it consistent Deadlock can only happen on k_work item in the application callback as i understand

Comment (jthm-ot) [reply subsys/bluetooth/audio/bap_scan_delegator.c:1157]: No. That's exactly what I was thinking of :-) When the app does those 2 things. But only on pa_sync_req callback is a Scan Delegator API function normally called (bt_bap_scan_delegator_set_pa_state)
I dont think a Scan Delegator API function call is needed on  pa_sync_term_req

**Review by jthm-ot — APPROVED** [review]

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 21 above)
Comment (Thalley) [reply subsys/bluetooth/audio/bap_scan_delegator.c:1157]: > I dont think a Scan Delegator API function call is needed on pa_sync_term_req

Not needed, but often done ;)

But yeah, that's a generic issue with any callback, which is why you generally should never do blocking operations in callbacks
