### PR TITLE
Bluetooth: GATT: Skip certain attributes when discovering descriptors

### LINKED ISSUE #14265: Bluetooth GATT descriptor discovery returns all attributes
**Describe the bug**
Running a GATT Descriptor discovery i.e. `bt_gatt_discover_params.type = BT_GATT_DISCOVER_DESCRIPTOR` results in the discovery callback being triggered for every attribute in the ATT table instead of only the descriptor.

**Expected behavior**
Instead of returning all attributes, the discovery shall only return descriptors (like service, characteristic discovery and similar)

**Impact**
Showstopper

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.9.5
 - Commit SHA: 1.13-branch@c478b5bb6e

### PR DESCRIPTION
**Pull request by Vudentz**
When discovering descriptor Find Information procedure is used which
does not allow any filtering by the server so it will return all
attributes in the given range including services and characteristics.

Fixes #14265

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

**Review by sjanc — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -2252,6 +2252,14 @@ static void gatt_find_info_rsp(struct bt_conn *conn, u8_t err,
 			continue;
 		}
 
+		/* Skip attributes that are not considered descriptors */
+		if (!bt_uuid_cmp(&u.uuid, BT_UUID_GATT_PRIMARY) ||
```
Comment (carlescufi) [inline subsys/bluetooth/host/gatt.c]: I assume there's no direct use of `Find Information Request/Response` by the application.
But what about characteristic values? those will still come through won't they? does this make sense?

**Review by carlescufi — CHANGES_REQUESTED** [review]

**Comment by carlescufi** [comment]
I am not convinced this is a bug when using Find Info Req/Rsp, because there is simply no way for the client to filter out non-descriptor attributes unless it knows the handle ranges

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Well we can't possible filter all of the characteristics, that table would be too big besides that would have to include vendor one as well so I don't think it is doable, we could perhaps add some state tracking for the declaration and then skip the next handle.

Comment (carlescufi) [reply subsys/bluetooth/host/gatt.c]: Right but is it worth it? Shouldn't the user know to pass the correct range when discovering descriptors?

**Comment by Vudentz** [comment]
> I am not convinced this is a bug when using Find Info Req/Rsp, because there is simply no way for the client to filter out non-descriptor attributes unless it knows the handle ranges

I went back and forth with the thought if that should be handle in the stack or not, in the end I think it is simpler to filter this on the stack rather then on the application thus why I submitted this anyway.

**Comment by carlescufi** [comment]
> > I am not convinced this is a bug when using Find Info Req/Rsp, because there is simply no way for the client to filter out non-descriptor attributes unless it knows the handle ranges
> 
> I went back and forth with the thought if that should be handle in the stack or not, in the end I think it is simpler to filter this on the stack rather then on the application thus why I submitted this anyway.

Right, but there won't be any real way for the app to know whether the returned attributes are descriptors or not, correct? I think this merits at least a change in the doc reflecting this.

**Comment by Vudentz** [comment]
> Right, but there won't be any real way for the app to know whether the returned attributes are descriptors or not, correct? I think this merits at least a change in the doc reflecting this.

Sure, I will update the documentation with the new behavior.

**Comment by Vudentz** [comment]
@carlescufi @paulgavrikov Ive added the documentation for the discover types and also include a new one that supports discovering any type of attribute.

**Review by carlescufi — APPROVED** [review]
Looks good now, thanks!

**Comment by paulgavrikov** [comment]
Looks good

**Review by jhedberg — APPROVED** [review]
