### PR TITLE
bluetooth: classic: sdp: Fix buffer length check in attribute parsing

### LINKED ISSUE #110849: bluetooth: classic: sdp: bt_sdp_parse_attribute() reads one byte past the buffer end
**Describe the bug**

`bt_sdp_parse_attribute()` in `subsys/bluetooth/host/classic/sdp.c` validates the
input buffer length before pulling fields, but the guard reserves space for only
two of the three values it goes on to read. The check is:

```c
if (buf->len < (sizeof(uint8_t) + sizeof(attr->id))) {
        LOG_WRN("Malformed packet");
        return -EBADMSG;
}
```

That requires only 3 bytes (a 1-byte type marker plus the 2-byte `attr->id`), but
the function then unconditionally pulls **four** bytes:

```c
net_buf_simple_pull_u8(buf);            /* type marker  — 1 byte */
attr->id = net_buf_simple_pull_be16(buf);   /* attribute id — 2 bytes */
type = net_buf_simple_pull_u8(buf);     /* descriptor   — 1 byte */
```

With a buffer of exactly 3 bytes, the first two pulls consume everything, leaving
`buf->len == 0`, and the third `net_buf_simple_pull_u8()` reads `buf->data[0]` one
byte past the logical end of the buffer. `net_buf_simple_pull_u8()` reads the byte
*before* `net_buf_simple_pull()` adjusts the length, and the only bounds guard in
`net_buf_simple_pull()` is an `__ASSERT_NO_MSG()`, which compiles to nothing in
the default (non-assert) build — so nothing stops the over-read.

This buffer comes from parsing SDP records, including discovery-response records
whose contents and descriptor bytes are supplied by the remote peer, so a peer can
shape a record to be exactly 3 bytes and trigger the over-read.

**Expected behavior**

The length check should account for all three values read after it, i.e. require
`sizeof(uint8_t) + sizeof(attr->id) + sizeof(type)` (4 bytes) before pulling, and
return `-EBADMSG` otherwise.

**Impact**

A 3-byte SDP attribute record causes a one-byte read past the end of the parse
buffer. In an assert-enabled build the `__ASSERT_NO_MSG()` in
`net_buf_simple_pull()` fires and panics.

**Affected code**

`subsys/bluetooth/host/classic/sdp.c` — `bt_sdp_parse_attribute()`.

### PR DESCRIPTION
**Pull request by lylezhu2012**
Fix insufficient buffer length validation in bt_sdp_parse_attribute(). The original check only verified space for the type byte and attribute ID, but did not account for the type variable itself that is read from the buffer immediately after the check.

This could lead to a buffer over-read if the buffer contains exactly sizeof(uint8_t) + sizeof(attr->id) bytes but not enough for the additional type field.

Add sizeof(type) to the length check to ensure all required data is present before parsing.

Fixes: #110849

### CODE REVIEW

File: subsys/bluetooth/host/classic/sdp.c [hunk 1]
```diff
@@ -3164,7 +3164,7 @@ static int bt_sdp_parse_attribute(struct net_buf_simple *buf, struct bt_sdp_attr
 	int err;
 	uint8_t *src;
 
-	if (buf->len < (sizeof(uint8_t) + sizeof(attr->id))) {
+	if (buf->len < (sizeof(uint8_t) + sizeof(attr->id) + sizeof(type))) {
```
Comment (chengkai15) [inline subsys/bluetooth/host/classic/sdp.c:3167]: @lylezhu2012 The fix is correct

However, the pattern of a single upfront length check covering multiple subsequent pull operations is fragile — this bug itself is evidence of that coupling. 

Consider either checking before each pull, or   defining a SDP_ATTR_MIN_LEN constant to document the invariant?

Comment (lylezhu2012) [reply subsys/bluetooth/host/classic/sdp.c:3167]: > the pattern of a single upfront length check covering multiple subsequent pull operations is fragile

Aside from the issue that is fixed by this PR, the remaining data length is checked before each pull in function `bt_sdp_parse_attribute`.

> Consider either checking before each pull, or defining a SDP_ATTR_MIN_LEN constant to document the invariant?

The remaining data length should be checked before each pull.

**Review by gzh-terry — APPROVED** [review]

**Review by chengkai15 — APPROVED** [review]
