### PR TITLE
Bluetooth: Audio: Fix ASCS CP subscribe in discovery

### LINKED ISSUE #54139: Bluetooth: Audio: race hazard bt_audio_discover() callback vs unicast_client_ase_cp_discover()
`bt_audio_discover()` has a callback when an ASE is discovered on a remote device
`unicast_client_ase_cp_discover()` asynchronously subscribes to notifications of ASE state changes

There's no way of the application knowing when `unicast_client_ase_cp_discover()` has completed so that it is safe to call `bt_audio_stream_config()`

This causes occasional race hazards when stream configuration occurs before state changes are notified.

I'm working on a PR to resolve this, probably calling the discovery callback **after** notifications have been enabled.

Relevant lines in mainline:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/unicast_client.c#L1882
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/unicast_client.c#L1799

### PR DESCRIPTION
**Pull request by Thalley**
During discovery the unicast client subscribes to the ASCS CP characteristic. However, this was done asynchronously at the end of the discovery, and the discovery complete callback was called before the subscription was done.

Since the unicast client relies on the auto CCC discovery, the actual subscription takes place a few connection intervals after the unicast_client_ep_set_cp function was called. The result of this is that the actual subscription was missing when the unicast client application starts performing BAP operations.

The change done here postpones the discovery callback until after the CP subscription has taken place, ensuring that the unicast client correctly receives the CP notifications when performing BAP operations. This also allows the unicast client to use the discovery parameter in the
bt_audio_discover_params struct, rather than yet another discovery parameter struct, saving some memory.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54139

### CODE REVIEW

**Review by kruithofa — DISMISSED** [review]
LGTM

File: subsys/bluetooth/audio/unicast_client.c [hunk 1]
```diff
@@ -83,7 +83,6 @@ static struct bt_gatt_subscribe_params avail_ctx_subscribe[CONFIG_BT_MAX_CONN];
  * needs to be done in serial to avoid using the same discover parameters
```
Comment (Chris-StJohn-Bose) [inline subsys/bluetooth/audio/unicast_client.c:83]: this comment should be adjusted now that cp_disc[] has been removed

File: subsys/bluetooth/audio/unicast_client.c [hunk 2]
```diff
@@ -1809,9 +1826,7 @@ static uint8_t unicast_client_cp_discover_func(struct bt_conn *conn,
 	LOG_DBG("conn %p attr %p handle 0x%04x", conn, attr, chrc->value_handle);
 
 	params->err = 0;
```
Comment (Chris-StJohn-Bose) [inline subsys/bluetooth/audio/unicast_client.c:1828]: is it still necessary to clear params->err here?

File: subsys/bluetooth/audio/unicast_client.c [hunk 3]
```diff
@@ -1208,9 +1224,10 @@ static void unicast_client_ep_set_cp(struct bt_conn *conn, uint16_t handle)
 		cp_subscribe[index].value_handle = handle;
 		cp_subscribe[index].ccc_handle = 0x0000;
 		cp_subscribe[index].end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE;
-		cp_subscribe[index].disc_params = &cp_disc[index];
+		cp_subscribe[index].disc_params = &params->discover;
 		cp_subscribe[index].notify = unicast_client_cp_notify;
 		cp_subscribe[index].value = BT_GATT_CCC_NOTIFY;
+		cp_subscribe[index].subscribe = unicast_client_cp_sub_cb;
 		atomic_set_bit(cp_subscribe[index].flags,
 			       BT_GATT_SUBSCRIBE_FLAG_VOLATILE);
```
Comment (Chris-StJohn-Bose) [inline subsys/bluetooth/audio/unicast_client.c:1233]: bt_gatt_subscribe() failure should be handled. Suggest something like:
```
params->err = bt_gatt_subscribe(...);
if (params->err) {
    unicast_client_cp_sub_cb(NULL, params->err, params)
}
```

File: subsys/bluetooth/audio/unicast_client.c [hunk 4]
```diff
@@ -1208,9 +1224,10 @@ static void unicast_client_ep_set_cp(struct bt_conn *conn, uint16_t handle)
 		cp_subscribe[index].value_handle = handle;
```
Comment (Chris-StJohn-Bose) [inline subsys/bluetooth/audio/unicast_client.c:1224]: I don't see where `cp_subscribe[?].value_handle` is cleared. Perhaps it isn't.

I think it's harmless to always subscribe to CCC here. If `cp_subscribe[?].value_handle` is re-used from one connection to another then it's essential.

Either way `params->func(conn, NULL, NULL, params)` needs to be called eventually so if we keep this `if ()` there should be an `else` clause?

**Review by Chris-StJohn-Bose — COMMENTED** [review]
Generally good and I think it will resolve #54139 but some error cases need to be handled.

File: subsys/bluetooth/audio/unicast_client.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/audio/unicast_client.c:83]: The comment still applies to `loc_cc_disc` and `avail_ctx_cc_disc`

File: subsys/bluetooth/audio/unicast_client.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/audio/unicast_client.c:1226]: Assuming that `bt_audio_discover` is always called for a new connection (which it should, given that the BAP implementation does not really support bonded information yet), then it does not need to be cleared.

Ideally we probably should clear it, and all the other connection-based values, on disconnect. However adding that is a separate issue, and something I'd rather do in a separate PR (ideally after https://github.com/zephyrproject-rtos/zephyr/pull/54363/commits/f35c89d855cca74aaaeff222708469ec76de7d2d has been merged, to make it easier).

File: subsys/bluetooth/audio/unicast_client.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/audio/unicast_client.c]: Nope :) Good catch

File: subsys/bluetooth/audio/unicast_client.c (hunk 4 above)
Comment (Chris-StJohn-Bose) [reply subsys/bluetooth/audio/unicast_client.c:1226]: my worry is what happens if a client connects, discovers, disconnects, connects to a different server, discovers?

Do connection indices get re-used? I think they might. Will cp_subscribe[0].value_handle be zero? Probably not.

**Review by Chris-StJohn-Bose — APPROVED** [review]
LGTM with caveat that discover-and-disconnect followed by connect-and-discover is probably not handled properly (as discussed) but agree this is probably just "the tip of the iceberg"

File: subsys/bluetooth/audio/unicast_client.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/audio/unicast_client.c:1226]: > Do connection indices get re-used? I think they might

Correct

> Will cp_subscribe[0].value_handle be zero? Probably not.

Correct, but it will get overwritten with the actual handle. 

I don't disagree that we should clear the data, I only suggest that we postpone that until my other PR has been merged, which would make it significantly easier to handle. The lack of clearing of data here shouldn't affect the issue that this PR is fixing

**Review by kruithofa — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]
