### PR TITLE
Verify memory controller node while determining a running application partition.

### LINKED ISSUE #99762: mcumgr: Image management incorrectly identifies active slot when slots are on different flash devices
### Describe the bug

When MCUboot is configured with `slot0_partition` and `slot1_partition` on different flash devices (e.g., slot 1 on external flash), mcumgr image management cannot correctly identify the active application partition. This results in uploading new firmware to the wrong slot, corrupting the currently running image and making the device unbootable.

### Regression

- [x] This is a regression.

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Additional Context

The `FIXED_PARTITION_IS_RUNNING_APP_PARTITION` macro used in `img_mgmt_active_slot()` only compares the partition offset against `CONFIG_FLASH_LOAD_OFFSET` without considering which flash device the partition resides on.

https://github.com/zephyrproject-rtos/zephyr/blob/32615695ad1b96670be8f2a38a8a9fd27e2d8ae5/subsys/dfu/img_util/flash_img.c#L26-L28

When two partitions on different flash devices have overlapping offset ranges that include `CONFIG_FLASH_LOAD_OFFSET`, the macro can incorrectly identify a partition on external flash as the running partition.

In Zephyr versions prior to v4.3.0, the implementation used exact equality, so this could accidentally work in multi-device configurations when the slot offsets differed between flash devices.

### PR DESCRIPTION
**Pull request by tomchy**
Verify memory controller node while determining a running application partition.
Currently the check uses only offsets, which may give false results if there is a partition on the external memory with a matching offset range.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/99762

### CODE REVIEW

File: include/zephyr/storage/flash_map.h [hunk 1]
```diff
@@ -465,6 +465,31 @@ uint8_t flash_area_erased_val(const struct flash_area *fa);
...
+ *
+ * @param label DTS node label of a partition
+ *
+ * @return Pointer to a device.
+ */
+#define FIXED_PARTITION_MTD(label) \
+	COND_CODE_1( \
+		DT_FIXED_SUBPARTITION_EXISTS(DT_NODELABEL(label)), \
+			(DT_MTD_FROM_FIXED_SUBPARTITION(DT_NODELABEL(label))), \
+			(DT_MTD_FROM_FIXED_PARTITION(DT_NODELABEL(label))))
```
Comment (JarmouniA) [inline include/zephyr/storage/flash_map.h:479]:
```suggestion
			(DT_MTD_FROM_FIXED_PARTITION(DT_NODELABEL(label))))

```

**Review by JarmouniA — COMMENTED** [review]
API minor version should be incremented.

**Review by nvlsianpu — APPROVED** [review]

**Review by masz-nordic — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]
