### PR TITLE
net: sockets: Fix getsockname() fucntion and add tests to cover it

### LINKED ISSUE #61545: net: getsockname: fails for bound socket
**Describe the bug**
`getsockname()` fails, setting `errno` to `EINVAL` when there is no connection handler, even when a socket has been bound with `bind()`.

The exact snippet is
https://github.com/zephyrproject-rtos/zephyr/blob/038351ad2615531e0e1ddbc47d907f16bb62ea50/subsys/net/lib/sockets/sockets.c#L2390-L2393

So either the connection handler is not getting set within the call to `bind()` or this check is invalid.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `qemu_x86`
 - What have you tried to diagnose or workaround this issue? step-debugged, found broken check
 - Is this a regression? Unsure.

**To Reproduce**
1. see sample code below

**Expected behavior**
`getsockname()` should return successfully, returning the assigned sockaddr

**Impact**
This is very clearly broken, and will affect any service using an ephemeral port number that wishes to obtain the assigned port number from the network subsystem.

**Logs and console output**
```
*** Booting Zephyr OS build v3.4.0-rc2-150-g83587a3cbca9 ***
I: Type 'quit' to quit
E: getsockname: 22
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK v0.16.1
 - Commit SHA or Version used: e0e7f5888f63555fbfa028331dfaf450d004d965

**Additional context**
Discovered in the context of working on #59669

Sample code:
```cpp
		/* Create a socket */
		ret = socket(af, SOCK_STREAM, 0);
		if (ret < 0) {
			LOG_ERR("socket: %d", errno);
			ret = -errno;
			break;
		}
		fd = ret;

		if (setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &(int){1}, sizeof(int)) < 0) {
			LOG_ERR("setsockopt: %d", errno);
			ret = -errno;
			break;
		}

		/* Bind to the specified address */
		if (bind(fd, &addr4, len) < 0) {
			LOG_ERR("bind: %d", errno);
			ret = -errno;
			break;
		}

		if (*port == 0) {
			/* ephemeral port - read back the port number */
			len = sizeof(addr4);
			ret = getsockname(fd, &addr4, &len);
			if (ret < 0) {
				LOG_ERR("getsockname: %d", errno);
				ret = -errno;
				break;
			}
			*port = addr4.sin_port;
		}
```

### PR DESCRIPTION
**Pull request by rlubos**
This PR relies on FIN handling being fixed in https://github.com/zephyrproject-rtos/zephyr/pull/61353, as this interferes with the tests (the issue (context leak) was already present in the test suite, but it did not manifest itself until new tests involving TCP were added). So DNM for now.

This PR fixes `getsockname()` function operation, and adds tests to cover its functionality. 

Additionally, the PR fixes a corner case encountered in the TCP implementation which prevented the tests from running properly (i. e. tests were leaking net/TCP context, interfering with each other.

Fixes #61545

### CODE REVIEW

**Comment by rlubos** [comment]
@ssharks Please specifically have a look at a fix in e2964b7986cd7533093af1377264d88daa03ad63. The issue was easily reproducible in those simple test cases, where both client and server ran from a single thread.

File: subsys/net/ip/tcp.c [hunk 1]
```diff
@@ -2347,25 +2347,32 @@ static enum net_verdict tcp_in(struct tcp *conn, struct net_pkt *pkt)
...
+			    conn->accepted_conn->accept_cb == NULL) {
+				/* In case of no accept_cb registered,
+				 * application will not take ownership of the
+				 * connection. To prevent connection leak, unref
+				 * the TCP context and put the connection into
+				 * active close (TCP_FIN_WAIT_1).
 				 */
-				conn->accepted_conn = NULL;
+				net_tcp_put(conn->context);
+				break;
```
Comment (ssharks) [inline subsys/net/ip/tcp.c:2363]: This break will skip any possible data received with the ACK. Are you deliberately ignoring this? This means that it might be retransmitted in FIN1 where it will receive a reset

**Review by ssharks — COMMENTED** [review]
Nice find, please think carefully on the case where the ACK contains data.

File: subsys/net/ip/tcp.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/ip/tcp.c:2363]: In case there is no `accept_cb`, the data would not be processed anyway, as there would be no `recv_cb` registered, so yeah, `break` here was intentional. I think that a potential RST in FIN1 state in such case may actually be a reasonable choice, as this clearly indicates that the data was **not** delivered. WDYT?

Comment (ssharks) [reply subsys/net/ip/tcp.c:2363]: Sounds like this ok, it would be code wist pretty nasty to send a RST from this point and go to TIME_WAIT.

**Review by ssharks — APPROVED** [review]

**Comment by rlubos** [comment]
Rebased on top of https://github.com/zephyrproject-rtos/zephyr/pull/61353.

File: tests/net/socket/misc/src/main.c [hunk 2]
```diff
@@ -421,13 +423,161 @@ void test_ipv6_getpeername(void)
...
+	sock_c = socket(family, SOCK_STREAM, IPPROTO_TCP);
+	zassert_true(sock_c >= 0, "socket open failed");
+	sock_s = socket(family, SOCK_STREAM, IPPROTO_TCP);
+	zassert_true(sock_s >= 0, "socket open failed");
+
+	/* Verify that unbound/unconnected socket has no local address set */
+	ret = getsockname(sock_c, &local_addr, &local_addr_len);
+	zassert_equal(ret, -1, "getsockname shouldn've failed");
+	ret = getsockname(sock_s, &local_addr, &local_addr_len);
+	zassert_equal(ret, -1, "getsockname shouldn've failed");
```
Comment (jukkar) [inline tests/net/socket/misc/src/main.c:456]: Should we also make sure that errno is set correctly?

File: tests/net/socket/misc/src/main.c [hunk 3]
```diff
@@ -421,13 +423,161 @@ void test_ipv6_getpeername(void)
...
+	sock_c = socket(family, SOCK_DGRAM, IPPROTO_UDP);
+	zassert_true(sock_c >= 0, "socket open failed");
+	sock_s = socket(family, SOCK_DGRAM, IPPROTO_UDP);
+	zassert_true(sock_s >= 0, "socket open failed");
+
+	/* Verify that unbound/unconnected socket has no local address set */
+	ret = getsockname(sock_c, &local_addr, &local_addr_len);
+	zassert_equal(ret, -1, "getsockname shouldn've failed");
+	ret = getsockname(sock_s, &local_addr, &local_addr_len);
+	zassert_equal(ret, -1, "getsockname shouldn've failed");
```
Comment (jukkar) [inline tests/net/socket/misc/src/main.c:523]: ditto

File: subsys/net/ip/tcp.c [hunk 4]
```diff
@@ -2379,25 +2379,32 @@ static enum net_verdict tcp_in(struct tcp *conn, struct net_pkt *pkt)
...
 			}
 
+			conn->accepted_conn->accept_cb(
+				conn->context,
+				&conn->accepted_conn->context->remote,
+				sizeof(struct sockaddr), 0,
+				conn->accepted_conn->context);
+
+			/* Make sure the accept_cb is only called once. */
+			conn->accepted_conn = NULL;
```
Comment (jukkar) [inline subsys/net/ip/tcp.c:2405]: Just wondering if there could be race here when calling accept_cb and setting it to null. One safer way would be to set the accepted_conn to null before calling it.

File: tests/net/socket/misc/src/main.c (hunk 2 above)
Comment (rlubos) [reply tests/net/socket/misc/src/main.c]: I've added extra checks for errno.

File: subsys/net/ip/tcp.c (hunk 4 above)
Comment (rlubos) [reply subsys/net/ip/tcp.c]: Hmm possibly. I've added a local copy of `accept_cb` pointer and call it now after the `accepted_conn` is cleared. Please check if it matches what you thought of.

**Review by jukkar — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
