### PR TITLE
 drivers: sensor: st: Fix uninitialized variable in lsm6dsv16x

### LINKED ISSUE #81956: [Coverity CID: 434610] Uninitialized scalar variable in drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c

Category: Uninitialized variables
Function: `lsm6dsv16x_enable_xl_int`
Component: Drivers
CID: [434610](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434610)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c#L50

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434610

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNINIT). ([CWE-457](http://cwe.mitre.org/data/definitions/457.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by rruuaanng**
Fix uninitialized ret variables scanned by Coverity.

from:
https://github.com/zephyrproject-rtos/zephyr/issues/81956

### CODE REVIEW

**Review by teburd — DISMISSED** [review]

**Review by MaureenHelm — COMMENTED** [review]
Thanks for the fix. Could you please mention the sensor in the commit message? Something like this:

```
drivers: sensor: st: Fix uninitialized variable in lsm6dsv16x

Fix uninitialized ret variables scanned by Coverity.

Signed-off-by: James Roy <rruuaanng@outlook.com>
```

**Review by avisconti — APPROVED** [review]
Good catch, thanks!

**Comment by avisconti** [comment]
> Thanks for the fix. Could you please mention the sensor in the commit message? Something like this:
> 
> ```
> drivers: sensor: st: Fix uninitialized variable in lsm6dsv16x
> 
> Fix uninitialized ret variables scanned by Coverity.
> 
> Signed-off-by: James Roy <rruuaanng@outlook.com>
> ```

And in the commit message add:

Fix #81956

**Review by avisconti — CHANGES_REQUESTED** [review]
LGTM, just implement the small suggestions

**Review by jilaypandya — COMMENTED** [review]
The hit is actually on a different line alltogether, or ?

Is this not where the issue is?
https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd158e7cec50761fece73b1d4835a2e/drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c#L50

The solution most probably is as follows, or?
`lsm6dsv16x_pin_int_route_t val = {};
`

**Comment by rruuaanng** [comment]
> The hit is actually on a different line alltogether, or ?
> 
> Is this not where the issue is?
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd158e7cec50761fece73b1d4835a2e/drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c#L50
> 
> The solution most probably is as follows, or? `lsm6dsv16x_pin_int_route_t val = {}; `

Good catch! I'll change to it.

File: drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c [hunk 1]
```diff
@@ -26,7 +26,7 @@ static int lsm6dsv16x_enable_xl_int(const struct device *dev, int enable)
 {
 	const struct lsm6dsv16x_config *cfg = dev->config;
 	stmdev_ctx_t *ctx = (stmdev_ctx_t *)&cfg->ctx;
-	int ret;
+	int ret = 0;
```
Comment (jilaypandya) [inline drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c:29]: This change is not required, since we are not reading this value before assigning something to it.

File: drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c [hunk 2]
```diff
@@ -72,7 +72,7 @@ static int lsm6dsv16x_enable_g_int(const struct device *dev, int enable)
...
```
Comment (jilaypandya) [inline drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c:75]: same goes for here and below as well.

File: drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c (hunk 1 above)
Comment (rruuaanng) [reply drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c:29]: I think I changed it, but that doesn't matter. Let's just keep it, shall we?

Comment (jilaypandya) [reply drivers/sensor/st/lsm6dsv16x/lsm6dsv16x_trigger.c:29]: I would revert it, coz imho it's unrelated to the issue afaik.

**Comment by rruuaanng** [comment]
> @rruuaanng can you also address this issue? [#82068 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/82068#issuecomment-2501158953)

I've change it. Please to see my commit message

**Comment by avisconti** [comment]
> > @rruuaanng can you also address this issue? [#82068 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/82068#issuecomment-2501158953)
> 
> I've change it. Please to see my commit message

Actually I requested to add also following line:

```
Fix #81956
```

**Comment by rettichschnidi** [comment]
> And in the commit message add:
> 
> Fix #81956

@avisconti According to the [most recent Zephyr documentation](https://docs.zephyrproject.org/latest/contribute/guidelines.html#adding-links), this should no longer be done:

> Do not include [GitHub references](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls) in the commit message directly, as it can lose meaning in case the repository is forked, for example. Instead, if the change addresses a specific GitHub issue, include in the Pull Request message a line of the form:

**Review by jilaypandya — APPROVED** [review]
LGTM

**Comment by avisconti** [comment]
> > And in the commit message add:
> > Fix #81956
> 
> @avisconti According to the [most recent Zephyr documentation](https://docs.zephyrproject.org/latest/contribute/guidelines.html#adding-links), this should no longer be done:
> 
> >

I see. Sorry for the noise.

**Review by avisconti — APPROVED** [review]

**Review by jeppenodgaard — APPROVED** [review]
