### PR TITLE
flash: spi_nor: fix building on XCC

### LINKED ISSUE #37734: xtensa xcc build spi_nor.c fail
**Describe the bug**
'''
FAILED: zephyr/drivers/flash/CMakeFiles/drivers__flash.dir/spi_nor.c.obj 
C:\usr\xtensa\XtDevTools\install\tools\RI-2021.6-win32\XtensaTools\bin\xt-xcc.exe -DBUILD_VERSION=zephyr-v2.6.0-641-gcc0abee3db73 -DKERNEL -D_FORTIFY_SOURCE=2 -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -IE:/work/zephyr/include -Izephyr/include/generated 
-IE:/work/soc/xtensa/ -IE:/work/k/soc/xtens/include -IE:/work/include -IE:/work/modules/hal/xtensa/include -IE:/work/modules/hal/xtensa/zephyr/soc/ -isystem E:/work/zephyr/lib/libc/minimal/include -Os -imacros E:/work/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -imacrosE:/work/zephyr/include/toolchain/xcc_missing_defs.h -fms-extensions -imacros E:/work/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Werror=implicit-int -fno-pic -fno-strict-overflow -ffunction-sections -fdata-sections -mlongcalls -std=c99 -MD -MT zephyr/drivers/flash/CMakeFiles/drivers__flash.dir/spi_nor.c.obj -MF zephyr\drivers\flash\CMakeFiles\drivers__flash.dir\spi_nor.c.obj.d -o zephyr/drivers/flash/CMakeFiles/drivers__flash.dir/spi_nor.c.obj -c E:/work/zephyr/drivers/flash/spi_nor.c
Signal: caughtError: Signal caught in phase CGPREP -- processing aborted
 in CGPREP phase.
xt-xcc.exe ERROR:  C:/usr/xtensa/XtDevTools/install/tools/RI-2021.6-win32/XtensaTools/libexec/xcc/be.exe returned non-zero status 3  
[53/87] Building C object zephyr/kernel/CMakeFiles/kernel.dir/errno.c.obj
ninja: build stopped: subcommand failed.
'''
function:
```
static int spi_nor_erase(const struct device *dev, off_t addr, size_t size)
{
	const size_t flash_size = dev_flash_size(dev);
	int ret = 0;

	/* erase area must be subregion of device */
	if ((addr < 0) || ((size + addr) > flash_size)) {
		return -ENODEV;
	}

	/* address must be sector-aligned */
	if (!SPI_NOR_IS_SECTOR_ALIGNED(addr)) {
		return -EINVAL;
	}

	/* size must be a multiple of sectors */
	if ((size % SPI_NOR_SECTOR_SIZE) != 0) {
		return -EINVAL;
	}

	acquire_device(dev);
	ret = spi_nor_write_protection_set(dev, false);

	while ((size > 0) && (ret == 0)) {
		spi_nor_cmd_write(dev, SPI_NOR_CMD_WREN);

		if (size == flash_size) {
			/* chip erase */
			spi_nor_cmd_write(dev, SPI_NOR_CMD_CE);
			size -= flash_size;
		} else {
			const struct jesd216_erase_type *erase_types =
				dev_erase_types(dev);
			const struct jesd216_erase_type *bet = NULL;

			for (uint8_t ei = 0; ei < JESD216_NUM_ERASE_TYPES; ++ei) {
				const struct jesd216_erase_type *etp =
					&erase_types[ei];

				if ((etp->exp != 0)
				    && SPI_NOR_IS_ALIGNED(addr, etp->exp)
				    && SPI_NOR_IS_ALIGNED(size, etp->exp)
				    && ((bet == NULL)
					|| (etp->exp > bet->exp))) {
					bet = etp;
				}
			}
			if (bet != NULL) {
				spi_nor_cmd_addr_write(dev, bet->cmd, addr, NULL, 0);
				addr += BIT(bet->exp);
				size -= BIT(bet->exp);
			} else {
				LOG_DBG("Can't erase %zu at 0x%lx",
					size, (long)addr);
				ret = -EINVAL;
			}
		}
		spi_nor_wait_until_ready(dev); ------------------------------------------------------->here
	}

	int ret2 = spi_nor_write_protection_set(dev, true);

	if (!ret) {
		ret = ret2;
	}

	release_device(dev);

	return ret;
}
```
my fix:
```
static int spi_nor_erase(const struct device *dev, off_t addr, size_t size)
{
	const size_t flash_size = dev_flash_size(dev);
	int ret = 0;

	/* erase area must be subregion of device */
	if ((addr < 0) || ((size + addr) > flash_size)) {
		return -ENODEV;
	}

	/* address must be sector-aligned */
	if (!SPI_NOR_IS_SECTOR_ALIGNED(addr)) {
		return -EINVAL;
	}

	/* size must be a multiple of sectors */
	if ((size % SPI_NOR_SECTOR_SIZE) != 0) {
		return -EINVAL;
	}

	acquire_device(dev);
	ret = spi_nor_write_protection_set(dev, false);

	while ((size > 0) && (ret == 0)) {
		spi_nor_cmd_write(dev, SPI_NOR_CMD_WREN);

		if (size == flash_size) {
			/* chip erase */
			spi_nor_cmd_write(dev, SPI_NOR_CMD_CE);
			size -= flash_size;
		} else {
			const struct jesd216_erase_type *erase_types =
				dev_erase_types(dev);
			const struct jesd216_erase_type *bet = NULL;

			for (uint8_t ei = 0; ei < JESD216_NUM_ERASE_TYPES; ++ei) {
				const struct jesd216_erase_type *etp =
					&erase_types[ei];

				if ((etp->exp != 0)
				    && SPI_NOR_IS_ALIGNED(addr, etp->exp)
				    && SPI_NOR_IS_ALIGNED(size, etp->exp)
				    && ((bet == NULL)
					|| (etp->exp > bet->exp))) {
					bet = etp;
				}
			}
			if (bet != NULL) {
				spi_nor_cmd_addr_write(dev, bet->cmd, addr, NULL, 0);
				addr += BIT(bet->exp);
				size -= BIT(bet->exp);
			} else {
				LOG_DBG("Can't erase %zu at 0x%lx",
					size, (long)addr);
				ret = -EINVAL;
			}
		}
		ret  = spi_nor_wait_until_ready(dev); ----------------------------------------------->
	}

	int ret2 = spi_nor_write_protection_set(dev, true);

	if (!ret) {
		ret = ret2;
	}

	release_device(dev);

	return ret;
}
```

Actually I don’t understand why there is such a issue, but my compiler does have such a issue.
I feel it is a side effect of code optimization.

### PR DESCRIPTION
**Pull request by dcpleung**
For some reason, XCC fails to build complaining segfault
during CGPREP phase. Adding an assignment to a volatile
return value seems to fix this. This provides an easily
revertable commit to workaround the issue.

Fixes #37734

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by nvlsianpu — COMMENTED** [review]
After reading [the issue](#37734) description I'm not convinced to this patch - the issue describes problem as missing of `ret` assignment a few lines below somehow. Also syntax which is "fixed" here is quite frequent everywhere else - so issue might happen in any other peace.

File: drivers/flash/spi_nor.c [hunk 1]
```diff
@@ -640,7 +640,11 @@ static int spi_nor_erase(const struct device *dev, off_t addr, size_t size)
 	acquire_device(dev);
 	ret = spi_nor_write_protection_set(dev, false);
 
-	while ((size > 0) && (ret == 0)) {
+	while (size > 0) {
+		if (ret != 0) {
+			break;
+		}
```
Comment (stephanosio) [inline drivers/flash/spi_nor.c:646]: It would be good to add a `FIXME` or `NOTE` here so that others do not try to re-phrase it back the way it was, and also that we do not forget to revert this once the XCC is fixed.

**Comment by dcpleung** [comment]
Changed to use volatile variable as it is more easily reverted. Also add a FIXME comment.

**Review by stephanosio — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]
