### PR TITLE
lora: sx12xx_common: force sleep on boot

### LINKED ISSUE #31567: lora: SX126x  modems consume excess power until used for first time
**Describe the bug**

The SX126x modems all consume excess power until used for TX or RX for the first time due to not entering sleep mode on boot.
The normal application flow when using LoRa is:

```
int main(void) {
    for(;;) {
        /* Config function transitions modem out of sleep mode */
        lora_config(...);

        /* TX and RX done callbacks transition modem to sleep mode */
        lora_send(...); // lora_recv(...)

        k_sleep(K_SECOND(1));
    }
}
```

The common init function `sx12xx_init` only calls `Radio.Init()`.
For the sx1276 modem this is sufficient as `SX1276Init` puts the modem into `RF_OPMODE_SLEEP`, the lowest power mode.
The sx126x modem does not explicitly move to any state in `RadioInit`, so it is left in the standard mode out of boot, `STDBY`.
This mode consumes an extra 600uA over `SLEEP`.

This is mostly an issue for applications which enable the driver to reduce the power consumption, but have to send/receive in order to actually see reduced power consumption.

**To Reproduce**
Steps to reproduce the behavior in `zephyr/samples/drivers/lora/send`:

1. add `k_sleep(K_SECONDS(3));` above `lora_config`
2. west build -b board zephyr/samples/drivers/lora/send
2. west flash

Observe the increased power consumption before the first send:
SX1262Excess

**Expected behavior**
When not using the LoRa functionality, power consumption shouldn't depend on whether it has previously been used or not.

**Impact**
Minor, mitigated by using the modem at least once.

**Environment (please complete the following information):**
 - Zephyr v2.4

### PR DESCRIPTION
**Pull request by JordanYates**
Force sx12xx modems into sleep mode on boot. This is the default state
of the modem when not being used due to the TX/RX complete callbacks.
This reduces current consumption by 600uA before the modems are used
for the first time.

As sleep is the normal state after TX/RX when using the LoRa API, it is
garaunteed that this will not change the behaviour of application code.
LoRaWAN starts by calling Radio.Init(), which resets the modem, so any
sleep configuration we do here is discarded.

Fixes #31567.

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

### CODE REVIEW

**Review by mniestroj — APPROVED** [review]

File: drivers/lora/sx12xx_common.c [hunk 1]
```diff
@@ -148,5 +148,13 @@ int sx12xx_init(const struct device *dev)
 	dev_data.events.RxDone = sx12xx_ev_rx_done;
 	Radio.Init(&dev_data.events);
 
+	/* Automatically place the radio into sleep mode upon boot.
```
Comment (Mani-Sadhasivam) [inline drivers/lora/sx12xx_common.c:151]: Nit. Please start the comment from next line.

**Review by Mani-Sadhasivam — APPROVED** [review]

File: drivers/lora/sx12xx_common.c (hunk 1 above)
Comment (JordanYates) [reply drivers/lora/sx12xx_common.c:151]: This seems to be a matter of personal preference. On other PR's I have been asked to use this form :). A quick regex search on this form (`\/\*[^\r\*\/]+$`) brings up over 4000 occurrences.

Comment (JordanYates) [reply drivers/lora/sx12xx_common.c:151]: I will update this usage as the other occurrence in this file uses the newline form
