### PR TITLE
stm32 spi driver adds the frame format 

### LINKED ISSUE #38683: stm32g0b1: spi: MOSI signal goes high before and after transmitting data
I noticed this issue while using the ws2812_spi LED strip driver on a nucleo_g0b1re board.

The led_ws2812 sample can be used to reproduce the issue. This [patch](https://github.com/simonguinot/zephyr/commit/3a9b09aced5643bd30f7ea2404401f2928c773ac) is needed to add support for the nucleo_g0b1re board to the led_ws2812 sample.

When running this sample, then the MOSI signal goes high for 80 microseconds before and after transmitting data:

stm32g0b1-spi1-mosi-high-before-after-transmission

stm32g0b1-spi1-mosi-high-zoom

The issue is that this high "preamble" state is interpreted as a high bit by the first WS2812 LED of the strip. And then the signal of all the LEDs is shifted by one bit, which results in visual glitches.

Note that from a SPI protocol standpoint, the MOSI signal is correct because the clock signal is off during this extra "high" states. Thus, this won't affect a real SPI device. But the WS2812 strip LED controller is not a SPI device. It doesn't use the clock signal. SPI is used here as a hack on a single wire (MOSI) to generate a control signal for the LEDs.

In addition, the issue is not systematic. It depends on the last data sent over MOSI. If the last 4 bytes are zero, then there are no high "preamble" state when sending the next buffer of data.

I also tried disabling DMA and interrupts but this doesn't affect the issue.

### PR DESCRIPTION
**Pull request by FRASTM**
this PR includes the support of the Format (TI vs MOTOROLA) of the SPI frame
The spi frame format is a property added to the spi device through an overlay for the led_strip sample on ws2812
`$ west build -p auto -b nucleo_l476rg samples/drivers/led_ws2812/`

After the new https://github.com/zephyrproject-rtos/zephyr/pull/39990

fixes https://github.com/zephyrproject-rtos/zephyr/issues/38683

 Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
stm32F1xx and some of the stm32L1 MCUs do not support the frame format.

**Comment by FRASTM** [comment]
includes overlay for nucleo_g071rb board

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -938,6 +938,15 @@ static void spi_stm32_irq_config_func_##id(const struct device *dev)		\
 #define STM32_SPI_USE_SUBGHZSPI_NSS_CONFIG(id)
 #endif
 
+#if !defined(CONFIG_SOC_SERIES_STM32F1X) \
+	&& (!defined(CONFIG_SOC_SERIES_STM32L1X) || defined(SPI_CR2_FRF))
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:942]: Rather than silently converting property to 0 for these cases, it should rather be notified at binding level,
and then generate an error if an unsupported case is configured

**Review by erwango — CHANGES_REQUESTED** [review]
otherwise LGTM

File: drivers/spi/spi_ll_stm32.c [hunk 2]
```diff
@@ -938,6 +938,15 @@ static void spi_stm32_irq_config_func_##id(const struct device *dev)		\
...
+#define STM32_SPI_USE_FRAME_FORMAT(id)				\
+	DT_INST_PROP_OR(id, frame_format, SPI_FRAME_FORMAT_TI)	\
```
Comment (ABOSTM) [inline drivers/spi/spi_ll_stm32.c:944]: You should add explicit comparison with 
`DT_INST_PROP_OR(...) == SPI_FRAME_FORMAT_TI ? ...`

**Review by ABOSTM — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_ll_stm32.c (hunk 2 above)
Comment (FRASTM) [reply drivers/spi/spi_ll_stm32.c]: changed to have SPI_FRAME_FORMAT_MOTOROLA as default

**Review by ABOSTM — APPROVED** [review]
LGTM

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:942]: We should generate an error if TI format selected but not supported

File: drivers/spi/spi_ll_stm32.c [hunk 3]
```diff
@@ -938,6 +938,15 @@ static void spi_stm32_irq_config_func_##id(const struct device *dev)		\
 #define STM32_SPI_USE_SUBGHZSPI_NSS_CONFIG(id)
 #endif
 
+#if !defined(CONFIG_SOC_SERIES_STM32F1X) \
+	&& (!defined(CONFIG_SOC_SERIES_STM32L1X) || defined(SPI_CR2_FRF))
+#define STM32_SPI_USE_FRAME_FORMAT(id) (DT_INST_PROP_OR(id, frame_format, \
+	SPI_FRAME_FORMAT_MOTOROLA) == SPI_FRAME_FORMAT_MOTOROLA) \
+	? LL_SPI_PROTOCOL_MOTOROLA : LL_SPI_PROTOCOL_TI
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:945]:
```suggestion
#define STM32_SPI_USE_FRAME_FORMAT(id)  \
	(DT_INST_PROP(id, frame_format) == SPI_FRAME_FORMAT_MOTOROLA) ? \
	LL_SPI_PROTOCOL_MOTOROLA : LL_SPI_PROTOCOL_TI
```

File: drivers/spi/spi_ll_stm32.c [hunk 4]
```diff
@@ -938,6 +938,15 @@ static void spi_stm32_irq_config_func_##id(const struct device *dev)		\
...
+#else
+#error "SPI Frame Format is not supported"
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:947]:
```suggestion
#error "SPI Frame Format (TI) is not supported"
```

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/spi/spi_ll_stm32.c (hunk 4 above)
Comment (FRASTM) [reply drivers/spi/spi_ll_stm32.c:947]: some stm32L15x (like cat1 or cat 2)  only have SPI Motorola mode
some others like stm32F1xx have No frame format nor TI neither Motorola)

Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:947]: > some others like stm32F1xx have No frame format nor TI neither Motorola)

Well then it is an issue as SPI API assumes you have to support one or the other.
cf https://github.com/zephyrproject-rtos/zephyr/pull/39990

**Comment by FRASTM** [comment]
change to get the frame format info from the spi config 
and not as a SPI instance configuration
It requires a new `.frame_format` field in the `include/drivers/spi.h`  set by the `<frame-format>` entry of the device DTS

**Comment by FRASTM** [comment]
Since the PR https://github.com/zephyrproject-rtos/zephyr/pull/39990, the frame_format property is missing in the spi_config structure
 		`.frame_format = DT_PROP(node_id, frame_format),	`
However there bit [15] in the **.operation** bitfield
` *     format              [ 15 ]      - Motorola or TI frame format (optional).`
but it seems not immediately compatible with the frame-format as described in the dts/bindings/spi/spi-device.yaml

**Comment by FRASTM** [comment]
rebase on f882d43b56e909465dd2c2dc904512f1e2c5cef7

**Comment by tbursztyka** [comment]
> @tbursztyka Since the PR #39990, the frame_format property is missing in the spi_config structure as follows: `.frame_format = DT_PROP(node_id, frame_format), ` However there is a bit [15] in the **.operation** bitfield ` * format [ 15 ] - Motorola or TI frame format (optional).` but it seems not immediately compatible with the frame-format as described in the dts/bindings/spi/spi-device.yaml

there isn't a property match between dts and spi_config. in dts it's frame_format, and in in spi_config.operation it's a bit there. Where is the issue?

File: drivers/spi/spi_ll_stm32.c [hunk 5]
```diff
@@ -480,6 +480,22 @@ static int spi_stm32_configure(const struct device *dev,
 		return -ENOTSUP;
 	}
 
+	/* configure the frame format Motorola (default) or TI */
+	if (config->frame_format == SPI_FRAME_FORMAT_TI) {
```
Comment (tbursztyka) [inline drivers/spi/spi_ll_stm32.c:484]: (config.operation & SPI_FRAME_FORMAT_TI) == SPI_FRAME_FORMAT_TI

**Comment by tbursztyka** [comment]
@FRASTM  looks like I forgot to update SPI_CONFIG_DT() macro. see pr #41641

**Comment by FRASTM** [comment]
rebase
get the PR https://github.com/zephyrproject-rtos/zephyr/pull/41641 
--> the stm32 drivers takes the frame_format from the DTS property : operation bitfield

File: drivers/spi/spi_ll_stm32.c [hunk 6]
```diff
@@ -480,6 +480,22 @@ static int spi_stm32_configure(const struct device *dev,
...
+#else
+		LOG_ERR("Frame Format TI not supported");
+		/* on stm32F1 or some stm32L1 without SPI_CR2_FRF */
+		return -ENOTSUP;
+#endif
+	} else {
+#if defined(LL_SPI_PROTOCOL_MOTOROLA) && defined(SPI_CR2_FRF)
+		/* on stm32F1 or stm32L1 (cat1,2) do not raise an error, it is default state */
+		LL_SPI_SetStandard(spi, LL_SPI_PROTOCOL_MOTOROLA);
+#endif
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:496]: This has to be changed otherwise will result on empty `else` which will be rejected by static analysis tools

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
rebase
+ changed to have else flagged by #if defined(LL_SPI_PROTOCOL_MOTOROLA) && defined(SPI_CR2_FRF)

File: drivers/spi/spi_ll_stm32.c [hunk 7]
```diff
@@ -480,6 +480,22 @@ static int spi_stm32_configure(const struct device *dev,
...
+#ifdef LL_SPI_PROTOCOL_TI
+		LL_SPI_SetStandard(spi, LL_SPI_PROTOCOL_TI);
+#else
+		LOG_ERR("Frame Format TI not supported");
+		/* on stm32F1 or some stm32L1 without SPI_CR2_FRF */
+		return -ENOTSUP;
+#endif
+#if defined(LL_SPI_PROTOCOL_MOTOROLA) && defined(SPI_CR2_FRF)
+	} else {
+		/* on stm32F1 or stm32L1 (cat1,2) do not raise an error, it is default state */
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:494]: Please remove this comment. This is indeed true, but confusing, given the code configuration.

**Review by erwango — APPROVED** [review]
