### PR TITLE
tests/kernel/gen_isr_table: Add special configuration for nRF9160 and nRF5340

### LINKED ISSUE #26302: Test gen_isr_tables from ./tests/kernel/gen_isr_table/ fails on nrf9160dk_nrf9160
**Describe the bug**
Test gen_isr_tables from ./tests/kernel/gen_isr_table/ fails on nrf9160dk_nrf9160

**To Reproduce**
1. Run in zephyr dir ./scripts/sanitycheck --testcase-root ./tests/kernel/gen_isr_table --device-testing -p nrf9160dk_nrf9160 -v -v --device-serial /dev/ttyACM0
2. See error

**Expected behavior**
The test passes

**Impact**
Not clear

**Screenshots or console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v2.3.0-460-g28f4f2af0b74  ***
DEBUG   - DEVICE: starting test - Test gen_isr_tables
DEBUG   - DEVICE: IRQ configuration (total lines 65):
DEBUG   - DEVICE: isr1 isr=0x000004cd irq=64
DEBUG   - DEVICE: isr2 isr=0x000004f5 irq=63
DEBUG   - DEVICE: Checking _irq_vector_table entry 64 for irq 64
DEBUG   - DEVICE: triggering irq 64
DEBUG   - DEVICE: isr1 ran
DEBUG   - DEVICE: Checking _irq_vector_table entry 63 for irq 63
DEBUG   - DEVICE: triggering irq 63
DEBUG   - DEVICE: interrupt 63 didn't run once, ran 0 times
DEBUG   - DEVICE: FAIL - main
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
```

**Environment**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: e64f75bae1

**Additional context**
The test passes on nrf52dk_nrf52832 and nrf52840dk_nrf52840

### PR DESCRIPTION
**Pull request by anangl**
On nRF9160 and application core in nRF5340, not all interrupts with highest numbers are implemented, so the test cannot just use the last 6 ones. This patch adds a Kconfig option that can be used to limit the number of interrupts reported to the test and uses this option for nRF9160 and nRF5340 SoCs.
The existing workaround that limits the number of interrupts for ARC EMSDP is also changed to use this Kconfig option.

Fixes #26302.

### CODE REVIEW

File: tests/kernel/gen_isr_table/Kconfig [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+source "Kconfig.zephyr"
+
+config TEST_NUM_IRQS
+	int
+	# On nRF9160 and application core in nRF5340, not all interrupts with
+	# highest numbers are implemented. Thus, limit the number of interrupts
+	# reported to the test, so that it does not try to use some unavailable
+	# ones.
+	default 33 if SOC_NRF5340_CPUAPP || SOC_NRF9160
+	default NUM_IRQS
```
Comment (andyross) [inline tests/kernel/gen_isr_table/Kconfig:16]: Style: given that this is completely internal to the test, is it really clearer to put this all the way up here in a kconfig vs. just having this in the C code:

```c
#if defined(CONFIG_SOC_NRF5340_CPUAPP) || defined(CONFIG_SOC_NRF9160)
#define TEST_NUM_IRQS 33
#else 
#define TEST_NUM_IRQS NUM_IRQS
#endif 
```

**Review by andyross — APPROVED** [review]
Not loving the idea of a per-test kconfig just to predicate one number on one extra case, but no reason to reject.

File: tests/kernel/gen_isr_table/Kconfig (hunk 1 above)
Comment (anangl) [reply tests/kernel/gen_isr_table/Kconfig]: @andyross Thank you for reviewing and adding this comment. Indeed, handling of these specific cases entirely in the C code is clearer, and eliminates the need of having this dirty workaround of defining the `NUM_IRQS` option for architectures that don't use it. I think I focused too much on adding a Kconfig option after reading https://github.com/zephyrproject-rtos/zephyr/pull/25405#discussion_r428483278.
I refactored this PR. Would you mind taking one more look?

**Review by andyross — APPROVED** [review]

File: tests/kernel/gen_isr_table/src/main.c [hunk 2]
```diff
@@ -36,13 +36,22 @@ extern uint32_t _irq_vector_table[];
...
+#define TEST_NUM_IRQS	CONFIG_NUM_IRQS
 #endif
 
-#define IRQ_LINE(offset)	(CONFIG_NUM_IRQS - ((offset) + 1))
-#define TABLE_INDEX(offset)	(IRQ_TABLE_SIZE - ((offset) + 1))
-#define TRIG_CHECK_SIZE         6
+#define TEST_IRQ_TABLE_SIZE 	(IRQ_TABLE_SIZE - \
+				 (CONFIG_NUM_IRQS - TEST_NUM_IRQS))
+#define IRQ_LINE(offset)	(TEST_NUM_IRQS - ((offset) + 1))
+#define TABLE_INDEX(offset)	(TEST_IRQ_TABLE_SIZE - ((offset) + 1))
```
Comment (ioannisg) [inline tests/kernel/gen_isr_table/src/main.c:53]: This is not a no-op, @anangl , TABLE_SIZE is now different from what it was before. Are you sure this is not breaking ARC? Or is it actually a fix? If so it should be reflected in the commit msg

**Review by ioannisg — CHANGES_REQUESTED** [review]

File: tests/kernel/gen_isr_table/src/main.c (hunk 2 above)
Comment (ioannisg) [reply tests/kernel/gen_isr_table/src/main.c:53]: Hm, OK, I see that IRQ_TABLE_SIZE is defined as 
`#define IRQ_TABLE_SIZE (CONFIG_NUM_IRQS - CONFIG_GEN_IRQ_START_VECTOR)` so it might have been picking the overwrite of CONFIG_NUM_IRQS in the earlier solution (@anangl confirm?)

Comment (anangl) [reply tests/kernel/gen_isr_table/src/main.c:53]: Previously, `CONFIG_NUM_IRQS` was redefined. And this redefinition influenced the value of `IRQ_TABLE_SIZE`, because this macro references `CONFIG_NUM_IRQS` in its [definition](https://github.com/zephyrproject-rtos/zephyr/blob/a2d4292a96e0e3f710374b6da6d3d5060bccc905/include/sw_isr_table.h#L73). I wanted to get rid of this `#undef CONFIG_NUM_IRQS`, and that's why I needed to use `TEST_IRQ_TABLE_SIZE`, which differs from `IRQ_TABLE_SIZE` by the difference between `CONFIG_NUM_IRQS` and `TEST_NUM_IRQS`.

Comment (anangl) [reply tests/kernel/gen_isr_table/src/main.c:53]: > Hm, OK, I see that IRQ_TABLE_SIZE is defined as
> `#define IRQ_TABLE_SIZE (CONFIG_NUM_IRQS - CONFIG_GEN_IRQ_START_VECTOR)` so it might have been picking the overwrite of CONFIG_NUM_IRQS in the earlier solution (@anangl confirm?)

I see that I was writing my comment in parallel with you adding yours. Yes, I confirm.

**Review by ioannisg — APPROVED** [review]
