### PR TITLE
Stm32h7 flash support

### LINKED ISSUE #29831: flash support for stm32h7 SoC
I'm trying to compile mcuboot for *nucleo_h743zi* board, I modified nucleo_h743zi.dts to provide the partitions layout
[see dts diff](https://github.com/zephyrproject-rtos/zephyr/files/5495464/compile_flash_driver.diff.txt)

When compiling I get the following error:
```
west build -p auto -b nucleo_h743zi -d build_h743/mcuboot ../bootloader/mcuboot/boot/zephyr/
-- west build: generating a build system
Including boilerplate (Zephyr base (cached)): /home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: /home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr
-- Zephyr version: 2.4.99 (/home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr)
-- Found west (found suitable version "0.7.3", minimum required is "0.7.1")
-- Board: nucleo_h743zi
-- Cache files will be written to: /home/nicolas/.cache/zephyr
-- Found toolchain: zephyr (/home/nicolas/.local/opt/zephyr-sdk-0.11.4)
-- Found dtc: /home/nicolas/.local/opt/zephyr-sdk-0.11.4/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/boards/arm/nucleo_h743zi/nucleo_h743zi.dts
-- Found devicetree overlay: /home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr/dts.overlay
-- Found devicetree overlay: /home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr/dts.overlay
-- Found devicetree overlay: /home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr/dts.overlay
-- Found devicetree overlay: /home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr/dts.overlay
-- Generated zephyr.dts: /home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/build_h743/mcuboot/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/build_h743/mcuboot/zephyr/include/generated/devicetree_unfixed.h
Parsing /home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr/Kconfig
Loaded configuration '/home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/boards/arm/nucleo_h743zi/nucleo_h743zi_defconfig'
Merged configuration '/home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr/prj.conf'

warning: FLASH_MAP (defined at subsys/storage/flash_map/Kconfig:10) has direct dependencies FLASH_HAS_DRIVER_ENABLED with value n, but is currently being y-selected by the following symbols:
 - MCUBOOT_DEVICE_SETTINGS (defined at /home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr/Kconfig:523), with value y, direct dependencies y (value: y)

error: Aborting due to Kconfig warnings

CMake Error at /home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/cmake/kconfig.cmake:239 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/cmake/app/boilerplate.cmake:590 (include)
  /home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:40 (include_boilerplate)
  CMakeLists.txt:44 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/home/nicolas/.virtualenvs/zephyr/bin/python3 -B/home/nicolas/work/siema/be/VOG/src/zephyrproject/zephyr/build_h743/mcuboot -S/home/nicolas/work/siema/be/VOG/src/zephyrproject/bootloader/mcuboot/boot/zephyr -GNinja
```

So I modified drivers/flash/Kconfig.stm32 to select FLASH_PAGE_LAYOUT and FLASH_HAS_PAGE_LAYOUT when SOC_SERIES_STM32H7X is selected. [See Kconfig.stm32 diff](https://github.com/zephyrproject-rtos/zephyr/files/5495464/compile_flash_driver.diff.txt).  
Unfortunately that fails miserably because the flash controller regmap has changed in the stm32h7, and the drivers/flash/flash_stm32.c seems to reference old regmap layout.

Am I missing something or is flash operations not supported yet on Zephyr OS for stm32h7 devices ?

I'm fairly new to Zephyr OS and I'm willing to give a try at adding support for this if no one else is working on it. Where should I direct my questions regarding the development of this ? Slack, Mailing list or this bug ?

Thanks.
Nicolas.

### PR DESCRIPTION
**Pull request by nicovince**
Added support to read/write flash on stm32h743.

Tested on a nucleo_h743zi with samples/drivers/flash_shell.

Fixes #29831

### CODE REVIEW

**Comment by explora26** [comment]
Please notice that MCUBoot is not support due to the minimum flash write size over 8 bytes.
https://github.com/mcu-tools/mcuboot/issues/713

**Comment by nicovince** [comment]
> Please notice that MCUBoot is not support due to the minimum flash write size over 8 bytes.
> [mcu-tools/mcuboot#713](https://github.com/mcu-tools/mcuboot/issues/713)

Indeed, after publishing my PR, I tried to play with MCUBoot, and noticed that the swap would fail. As far as I could test, I did not notice any issues while playing around with flash_shell sample.

File: drivers/flash/flash_stm32.c [hunk 1]
```diff
@@ -141,6 +144,9 @@ int flash_stm32_wait_flash_idle(const struct device *dev)
 	}
 #if defined(CONFIG_SOC_SERIES_STM32G0X)
 	while ((FLASH_STM32_REGS(dev)->SR & FLASH_SR_BSY1)) {
+#elif defined(CONFIG_SOC_SERIES_STM32H7X)
+	while ((FLASH_STM32_REGS(dev)->SR1 & (FLASH_SR_BSY | FLASH_SR_QW))
+	       || (FLASH_STM32_REGS(dev)->SR2 & (FLASH_SR_BSY | FLASH_SR_QW))) {
```
Comment (erwango) [inline drivers/flash/flash_stm32.c:149]: Only checking the QW bit should be sufficient.
Though, you should check that _both_ banks are not busy (but only under #if DUAL_BANK).

File: drivers/flash/flash_stm32h7x.c [hunk 2]
```diff
@@ -0,0 +1,219 @@
...
+#include <init.h>
+#include <soc.h>
+
+#include "flash_stm32.h"
+
+#define LOG_DOMAIN flash_stm32h7
+#define LOG_LEVEL CONFIG_FLASH_LOG_LEVEL
+#include <logging/log.h>
+LOG_MODULE_REGISTER(LOG_DOMAIN);
+#define STM32H7X_SECTOR_SHIFT 17
```
Comment (erwango) [inline drivers/flash/flash_stm32h7x.c:20]: Some H7 references use 8K sectors.

File: drivers/flash/flash_stm32h7x.c [hunk 3]
```diff
@@ -0,0 +1,219 @@
...
+}
+
+static int erase_sector(const struct device *dev, uint32_t sector)
+{
+	FLASH_TypeDef *regs = FLASH_STM32_REGS(dev);
+	int rc;
+	uint32_t tmp;
+	volatile uint32_t *cr;
+
+	if (sector <= 7) {
```
Comment (erwango) [inline drivers/flash/flash_stm32h7x.c:38]: For 8K sectors, Bank2 starts at sector 128.

File: drivers/flash/flash_stm32h7x.c [hunk 4]
```diff
@@ -0,0 +1,219 @@
...
+		cr = &regs->CR1;
+	} else {
+		cr = &regs->CR2;
+	}
```
Comment (erwango) [inline drivers/flash/flash_stm32h7x.c:42]: Only if DUAL_BANK

File: drivers/flash/flash_stm32h7x.c [hunk 5]
```diff
@@ -0,0 +1,219 @@
...
+		if (k_uptime_get() > timeout_time) {
+			LOG_ERR("Timeout! val: %d", 100);
+			return -EIO;
+		}
+	}
+
+	return 0;
+}
+
+static int write_4dwords(const struct device *dev,
```
Comment (erwango) [inline drivers/flash/flash_stm32h7x.c:131]: Some H7 references will use 128 bits programming length

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for this contribution! STM32H7 is not the easiest piece of the family and its flash controller block is no exception.

I'm affraid there are numerous changes to be addressed for driver completion.
Proposed driver does not takes sufficiently into account:
- Series heterogeneity (Single vs Dual Bank, number of sectors, size of sectors, programming size, ..)
- Dual Bank simultaneous operation support

Considering these points, for more flexibility in implementation and final readability, I would advise to create a dedicated stm32h7 driver (ie not based on flash_stm32.c).
Though, I don't request to implement the full series support with all its variants (not all of these are supported today in zephyr). But at least the driver should be able to detect if the H7 variant is supported or not.

File: drivers/flash/flash_stm32.c [hunk 6]
```diff
@@ -274,6 +280,26 @@ static int flash_stm32_write_protection(const struct device *dev, bool enable)
...
+	}
+    /* Bank 2 */
+	if (enable) {
+		regs->CR2 |= FLASH_CR_LOCK;
+	} else {
+		if (regs->CR2 & FLASH_CR_LOCK) {
+			regs->KEYR2 = FLASH_KEY1;
+			regs->KEYR2 = FLASH_KEY2;
+		}
+	}
```
[the remark this answers is not in the document]
Comment (nicovince) [reply drivers/flash/flash_stm32.c:301]: This is due to the API 
```c
typedef int (*flash_api_write_protection)(const struct device *dev,
                                          bool enable);
```
There are no parameters indicating on which part of the flash the write protection should occurs, therefore I lock both banks and lose the ability to operate on both banks.
I did not see how I could address this without changing the API.
Do you have any suggestions ?

File: drivers/flash/flash_stm32.c [hunk 7]
```diff
@@ -52,6 +52,9 @@ LOG_MODULE_REGISTER(flash_stm32, CONFIG_FLASH_LOG_LEVEL);
 /* STM32G4: maximum erase time of 24.47ms for a 2K sector */
 #elif defined(CONFIG_SOC_SERIES_STM32G4X)
 #define STM32_FLASH_MAX_ERASE_TIME	25
+/* TODO:STM32H7: maximum erase time of XXX ms for a 128K sector */
```
[the remark this answers is not in the document]
Comment (nicovince) [reply drivers/flash/flash_stm32.c:55]: Why removing the `/*` and `*/` ?

[the remark this answers is not in the document]
Comment (erwango) [reply drivers/flash/flash_stm32.c:55]: Copy/paste issue. These should be kept indeed

File: drivers/flash/flash_stm32.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/flash/flash_stm32.c:301]: Right.
One alternative would be to use 2 different devices, but I'm ok to limit the driver to sequential usage of banks as a first step.

File: drivers/flash/flash_stm32h7x.c (hunk 2 above)
Comment (nicovince) [reply drivers/flash/flash_stm32h7x.c:20]:
```diff
-#define STM32H7X_SECTOR_SHIFT 17
+
+#define LOG2CEIL(x) ((((x) <= 2048) ? 11 : (((x) <= 4096)?12:(((x) <= 8192) ? \
+       13 : (((x) <= 16384) ? 14 : (((x) <= 32768) ? 15:(((x) <= 65536) ? \
+       16 : (((x) <= 131072) ? 17 : (((x) <= 262144) ? 18:(((x) <= 524288) ? \
+       19 : (((x) <= 1048576) ? 20 : (((x) <= 2097152) ? \
+       21 : (((x) <= 4194304) ? 22 : (((x) <= 8388608) ? \
+       23 : (((x) <= 16777216) ? 24 : (((x) <= 33554432) ? \
+       25 : (((x) <= 67108864) ? 26 : (((x) <= 134217728) ? \
+       27 : (((x) <= 268435456) ? 28 : (((x) <= 536870912) ? \
+       29 : (((x) <= 1073741824) ? 30 : (((x) <= 2147483648) ? \
+       31 : 32))))))))))))))))))))))
+#define STM32H7X_SECTOR_SHIFT LOG2CEIL(FLASH_BANK_SIZE / FLASH_SECTOR_TOTAL)
```
What do you think about this ? I copied the macro LOG2CEIL from `include/linker/linker-tool-mwdt.h`
This way the SECTOR_SHIFT is computed automatically for every devices in the family.

File: drivers/flash/flash_stm32h7x.c (hunk 3 above)
Comment (erwango) [reply drivers/flash/flash_stm32h7x.c:38]: This would work indeed

File: drivers/flash/flash_stm32h7x.c (hunk 2 above)
Comment (erwango) [reply drivers/flash/flash_stm32h7x.c:20]: What about simplifying a bit things and use the following in `get_sector` function:
```
static unsigned int get_sector(off_t offset)
{
	return offset / FLASH_SECTOR_SIZE;
}
```

File: drivers/flash/flash_stm32.c (hunk 1 above)
Comment (erwango) [reply drivers/flash/flash_stm32.c:149]: I'm "unresolving" this until I can see it has been actually resolved.

File: drivers/flash/flash_stm32h7x.c (hunk 5 above)
Comment (nicovince) [reply drivers/flash/flash_stm32h7x.c:131]: Rewriting the function to write_ndwords and taking an extra parameters n to define the number of double words to be written

**Comment by nicovince** [comment]
Hi, thanks for your thorough review.

> I would advise to create a dedicated stm32h7 driver (ie not based on flash_stm32.c).

I thought about it initially but I was afraid to have a lot of copy/paste from flash_stm32.c, so I decided to go with with the approach used for flash_stm32wbx.c: using ifdef to remove functions definitions from flash_stm32.c and defining them into flash_stm32wbx.c.
The downside is the multiple ifdef popping arround in flash_stm32.c
If that is not acceptable I'll see how i can improve it, maybe splitting flash_stm32.c into flash_stm32_cmn.c and flash_stm32_v2.c ? (there is already a v1).

Otherwise I've addressed the various suggestions you've made, and hopefully fixed the buildkite/zephyr.

I noticed an issue when using samples/drivers/flash_shell/, if i try to `flash write_pattern 0x20000 256` twice, on next reset I see the content which has been erased but the pattern is not there anymore. If you have any idea let me know.

Do you want me to update the PR with the commits I made to address your suggestions or shall I wait to have the issue above fixed ?

Thanks

**Comment by erwango** [comment]
> I thought about it initially but I was afraid to have a lot of copy/paste from flash_stm32.c, so I decided to go with with the approach used for flash_stm32wbx.c: using ifdef to remove functions definitions from flash_stm32.c and defining them into flash_stm32wbx.c.
The downside is the multiple ifdef popping arround in flash_stm32.c
If that is not acceptable I'll see how i can improve it, maybe splitting flash_stm32.c into flash_stm32_cmn.c and flash_stm32_v2.c ? (there is already a v1).

If we consider the fact that H7 flash driver might require in the end to support simultaneous operations to 2 banks, I think that we'll end up hacking a lot flash_stm32.c file and I'd prefer to avoid this situation. 
Also, I don't think splitting flash_stm32.c would be that great (flash_stm32_v1.c is used together with flash_stm32.c for F0, F1, F3 and L0), it is a different split as you're proposing for v2.
So in the end, the simplest is to opt for a monolithic flash_stm32_h7.c (this might require some file renaming to minimize confusion with other stm32 flash dirvers, but I'll take care of that part).

**Comment by nicovince** [comment]
@erwango, I have addressed the various suggestions you've made, and properly invalidated data cache on erased sectors.

Please, let me know if I have missed something.

Thanks.

File: drivers/flash/flash_stm32h7x.c [hunk 8]
```diff
@@ -0,0 +1,534 @@
...
+	SCB_InvalidateDCache_by_Addr((uint32_t *)(CONFIG_FLASH_BASE_ADDRESS
+						  + offset), len);
+}
+
+
+static int flash_stm32h7_erase(const struct device *dev, off_t offset,
+			       size_t len)
+{
+	int rc;
+	off_t flush_offset = get_sector(offset) * FLASH_SECTOR_SIZE;
```
Comment (erwango) [inline drivers/flash/flash_stm32h7x.c:377]: I'm a bit puzzled by this line given that get_sector(offset) = offset / FLASH_SECTOR_SIZE.
A subtlety I didn't catch maybe?

File: drivers/flash/flash_stm32h7x.c [hunk 9]
```diff
@@ -0,0 +1,534 @@
...
+	size_t flush_len = (((get_sector(offset + len) + 1) * FLASH_SECTOR_SIZE)
```
Comment (erwango) [inline drivers/flash/flash_stm32h7x.c:378]: I'm also confused here. Why length to be used in SCB_InvalidateDCache_by_Addr would be different from len?

File: drivers/flash/flash_stm32h7x.c [hunk 10]
```diff
@@ -0,0 +1,534 @@
...
+		memset(unaligned_datas, 0xff, sizeof(unaligned_datas));
+		for (i = 0; i < len && i < nbytes; ++i) {
+			unaligned_datas[suboffset + i] = ((uint8_t *)data)[i];
+		}
+		rc = write_ndwords(dev, offset,
+				   (const uint64_t *)unaligned_datas,
+				   ndwords);
+		i = 32;
+		offset += 32;
+	}
```
Comment (erwango) [inline drivers/flash/flash_stm32h7x.c:288]: I don't think this is something we'd like to do.
If write request offset is not aligned on flash blocks boundaries we should reject and warn user, as done in other drivers.

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for this new version, this is going in the good direction.
This seems overall fine, except the comments or clarifications required bellow.
One point I'm not sure is that if we should consider writing unaligned blocks. I think as a first version it would be better to reject as done on other drivers, unless there is a good reason to do so.
Btw, it will be required to remove the now unrelated first commits and start wit the commit that add the new driver

**Comment by nicovince** [comment]
> One point I'm not sure is that if we should consider writing unaligned blocks. I think as a first version it would be better to reject as done on other drivers, unless there is a good reason to do so.
Since the flash words are pretty larges (32 bytes), I thought it was relevant, I don't mind removing it.

**Comment by erwango** [comment]
> Since the flash words are pretty larges (32 bytes), I thought it was relevant, I don't mind removing it.

This is a fair point, but I'm not sure that upper layers are able to deal with this, While I'm sure they're able to deal with various write bloc sizes (this is why we provide a `flash_parameters.write_block_size `). Anyway, if this appear to be possible and requested, it could be added later. Let's start with a safe implementation.

File: drivers/flash/flash_stm32h7x.c [hunk 11]
```diff
@@ -0,0 +1,534 @@
...
+	int64_t timeout_time = k_uptime_get() + STM32H7_FLASH_TIMEOUT;
+	int rc;
+
+	rc = flash_stm32_check_status(dev);
+	if (rc < 0) {
+		return -EIO;
+	}
+#ifdef DUAL_BANK
+	while ((FLASH_STM32_REGS(dev)->SR1 & FLASH_SR_QW)
+	       || (FLASH_STM32_REGS(dev)->SR2 & FLASH_SR_QW))
```
[the remark this answers is not in the document]
Comment (nicovince) [reply drivers/flash/flash_stm32h7x.c:101]: Are you sure ?
I want to wait while QW bit is set in either of the bank, not both of them simultaneously.

File: drivers/flash/flash_stm32h7x.c (hunk 8 above)
Comment (nicovince) [reply drivers/flash/flash_stm32h7x.c:377]: I noticed an issue when playing around with `zephyr/samples/drivers/flash_shell/`:

If i write a few bytes at the beginning of a sector, then do a `flash write_pattern` at an address further away in that sector, I would still see the few bytes written at the beginning of the sector even though `write_pattern` performs an erase on the sector.

So, with this line I'm telling the driver I want to invalidate the cache at the first address of the sector which has been erased.

File: drivers/flash/flash_stm32h7x.c (hunk 9 above)
Comment (nicovince) [reply drivers/flash/flash_stm32h7x.c:378]: Same issue as above.
Although I suspect there is still a bug lying somewhere because if I do a write_pattern with a length of 256 at offset 0, then a write_pattern of length 32 at offset 0, I still see the data at offet 32 to 63.

**Comment by nicovince** [comment]
@erwango, I have addressed your suggested changes, except for [this one](https://github.com/zephyrproject-rtos/zephyr/pull/30043#discussion_r530468924).

Thanks for your review.

File: drivers/flash/flash_stm32h7x.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/flash/flash_stm32h7x.c:101]: My bad, this is fine indeed.

File: drivers/flash/flash_stm32h7x.c (hunk 8 above)
Comment (erwango) [reply drivers/flash/flash_stm32h7x.c:369]: Ok, I'll check that

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for the update, few more comments

File: drivers/flash/flash_stm32h7x.c (hunk 9 above)
Comment (erwango) [reply drivers/flash/flash_stm32h7x.c:372]: Ok, I saw that as well.
I would tend to say this is related to a bug in upper layers since this cannot be seen if `flash erase` is run manually between two `flash write_pattern`

File: drivers/flash/flash_stm32h7x.c [hunk 12]
```diff
@@ -0,0 +1,528 @@
...
+bool flash_stm32_valid_range(const struct device *dev, off_t offset,
+			     uint32_t len,
+			     bool write)
+{
+	if (write) {
+		if ((offset % FLASH_NB_32BITWORD_IN_FLASHWORD * 4) != 0) {
+			LOG_ERR("Write offset not aligned on flashword length. "
+				"Offset: 0x%x, flashword length: %d",
+				offset, FLASH_NB_32BITWORD_IN_FLASHWORD * 4);
+			return -EINVAL;
```
Comment (erwango) [inline drivers/flash/flash_stm32h7x.c:69]: Function is bool.

**Review by erwango — CHANGES_REQUESTED** [review]
Final comments on my side.
Would you mind :
- refactor the PR in order to have only one commit for the driver (no fix commts...)
- add the minimum flash descriptions in dtsi files for available H7 SoCs
- rebase on master in order to solve the merge conflict

Txs!

**Comment by nicovince** [comment]
>     * add the minimum flash descriptions in dtsi files for available H7 SoCs

I'm not sure to understand exactly what that means. Is it related to the write-block-size/erase-block-size properties ?

**Comment by erwango** [comment]
> I'm not sure to understand exactly what that means. Is it related to the write-block-size/erase-block-size properties ?

Yes!

File: boards/arm/nucleo_h743zi/nucleo_h743zi.dts [hunk 13]
```diff
@@ -112,7 +113,52 @@
 		     &eth_txd1_pb13>;
 };
 
+
```
Comment (erwango) [inline boards/arm/nucleo_h743zi/nucleo_h743zi.dts:116]: Remove this line

File: boards/arm/nucleo_h743zi/nucleo_h743zi.dts [hunk 14]
```diff
@@ -112,7 +113,52 @@
...
 &spi1 {
 	status = "okay";
 	pinctrl-0 = <&spi1_sck_pa5 &spi1_miso_pa6 &spi1_mosi_pb5>;
 };
+
+&flash0 {
+	/*
+	 * For more information, see:
+	 * https://docs.zephyrproject.org/latest/reference/devicetree/index.html#fixed-flash-partitions
```
Comment (erwango) [inline boards/arm/nucleo_h743zi/nucleo_h743zi.dts:125]: This link is obsolete (I should add again, as this is at least the 2nd time the link used for this doc changes).
Let's remove the whole comment as this is now a common feature and there is no specific reason to comment it more than other dts pieces.
We might need to clean this up from other boards as well.

**Review by erwango — CHANGES_REQUESTED** [review]
Sorry if that was not clear but "one commit for the driver" and ... other commits can be kept :-)
Anyway, now that everything is squashed, it will be easy to split into:
- 1 dts/ commit
- 1 soc/ commit
- 1 drivers/ commit
     -> For this one, please rename to something like drivers/flash: Add support for ....
         and add the "Fixes #29831" as part of the commit message. This way, related issue will be closed automatically once PR is 
         merged
- 1 board commit

Txs!

**Comment by nicovince** [comment]
Latest push should have fixed the buildkite/zephyr. Sorry about that...

File: drivers/flash/flash_stm32h7x.c [hunk 15]
```diff
@@ -0,0 +1,531 @@
...
+
+static int flash_stm32h7_erase(const struct device *dev, off_t offset,
+			       size_t len)
+{
+	int rc;
+	off_t flush_offset = get_sector(offset) * FLASH_SECTOR_SIZE;
+	size_t flush_len = (((get_sector(offset + len) + 1) * FLASH_SECTOR_SIZE)
+			    - flush_offset);
+
+	if (!flash_stm32_valid_range(dev, offset, len, false)) {
```
Comment (ABOSTM) [inline drivers/flash/flash_stm32h7x.c:378]: From my point of view erase is a kind of write (we write 0xFF to a location) and thus last parameter of flash_stm32_valid_range() should be true. Write is opposed to read (and not opposed to erase).

File: drivers/flash/flash_stm32h7x.c [hunk 16]
```diff
@@ -0,0 +1,531 @@
...
+{
+	ARG_UNUSED(dev);
+
+	return &flash_stm32h7_parameters;
+}
+
+static const struct flash_pages_layout stm32h7_flash_layout[] = {
+	{ .pages_count = FLASH_SECTOR_TOTAL, .pages_size = FLASH_SECTOR_SIZE },
+#ifdef DUAL_BANK
+	{ .pages_count = FLASH_SECTOR_TOTAL, .pages_size = FLASH_SECTOR_SIZE },
```
Comment (ABOSTM) [inline drivers/flash/flash_stm32h7x.c:467]: I think you will face the same issue I have on STM32G4 #30231
There may be some discontinuity between bank1 and bank2 on some chip, when dual bank, with smaller flash .
Ex: stm32h747zi has 2M flash but stm32h747IG has only 1M flash, in this case real number of sector will be smaller, and by the way you cannot rely on FLASH_SECTOR_SIZE which is defined to 8 for all soc STM32H747xx.

**Review by ABOSTM — CHANGES_REQUESTED** [review]

File: drivers/flash/flash_stm32h7x.c (hunk 16 above)
Comment (nicovince) [reply drivers/flash/flash_stm32h7x.c:467]: I've had a look at files under `modules/hal/stm32/stm32cube/stm32h7xx/soc`, and all SOCs defining `DUAL_BANK` have a 1MB `FLASH_BANK_SIZE` (based on the comments).
So as far as I understand it the h7 family would not be impacted by this fragmented issue. What do you think ?

Comment (ABOSTM) [reply drivers/flash/flash_stm32h7x.c:467]: Unfortunately, it seems thoses files are erroneous. As I said, stm32h747IG has only 1M flash (512 HB per bank).
I submitted an internal ticket to change FLASH_SIZE definition.
And so h7 family is impacted by potential discontinuity.
As FLASH_SIZE (as well as FLASH_BANK_SIZE) is not reliable for now, you can use `LL_GetFlashSize()`

Comment (ABOSTM) [reply drivers/flash/flash_stm32h7x.c:467]: @nicovince, after discussion with @erwango,
we propose you to not implement discontinuity management in this PR,
and I will do it in a separate PR.

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@nicovince would you moind rebasing to fix CI issue ?

**Comment by nicovince** [comment]
> @nicovince would you mind rebasing to fix CI issue ?

Done.

File: drivers/flash/flash_stm32h7x.c (hunk 16 above)
Comment (nicovince) [reply drivers/flash/flash_stm32h7x.c:467]: Ok, my bad.

I'll look into it then. How can I test my code on this particular chip ?

**Comment by nvlsianpu** [comment]
@nicovince reopen?

**Comment by nicovince** [comment]
> @nicovince reopen?

I'm still trying to figure out why the CI built successfully when I finalized this PR and why it failed later...
I'm pretty new to zephyr development, what shoud i do ? 
Repoen #29831 and create a new PR, or continue on this one ?

**Comment by nvlsianpu** [comment]
Reopen this time means submit another PR.

**Comment by erwango** [comment]
> I'm still trying to figure out why the CI built successfully when I finalized this PR and why it failed later...

@nicovince, there is a trick indeed.
My understanding of what happened is the following: 
In CI, only a limited subset of platforms vs samples/tests are build. On top of that a specific run is launched for each impacted board (based on path board/foor/bar).
On daily builds, all test/samples vs platforms combinations are run. And I guess this is where the _m4 targets builds were launched.

By the way, I'm looking at the issue.
Definition of flash controller on H7 M4 cores have some consequences that should be checked.
I'm not sure exactly how this should be fixed.
I propose to push a new PR with your commits when I'm done

**Comment by nicovince** [comment]
@erwango, I was getting to the same conclusion.

I started modifying the dtsi in order to take into account the different flash address based on the core (0x800_0000 for m7, 0x810_0000 for the m4), and the dts compilation passes, but another failure rises at linking stage regarding the cache invalidation call (SCB_).
Setting that call under ifdnef CORE_CM4 does the trick...
Is there an invalidate cache call on M4 cores ?

**Comment by erwango** [comment]
> Is there an invalidate cache call on M4 cores ?

No. No flash cache mgmt on H7 M4 cores it seems. 
Anyway, there are few more hickups on the M4 core flash driver support.
So I ended up thinking that flash driver support on M4 core should be disabled cleanly for now on.

**Comment by GiancarloPerroni** [comment]
Hi, I ve some questions:

- Is for M4 core a flash-drviver support foreseen? When?
- what is necessary to do in order to adapt M7 driver to make it running with M4?

Thank you in advance for any answer.
