### PR TITLE
soc: nxp: imxrt: fix FlexSPI clock after DTS change

### LINKED ISSUE #106762: nxp: flexspi: peformance drop on NXP iMXRT1176 based board
### Describe the bug

On a custom board (NXP iMXRT1176 based MCU) after this commit https://github.com/zephyrproject-rtos/zephyr/commit/b1afb494b0c3b34534772bed0f10a3a61502dee5 and doing similar changes in the device tree for my custom board like were done for the evk. There is a huge performance drop for me in shell response. It seems that FlexSPI is now misconfigured. Somebody else in discord reported: Before that commit it was running on 132 MHz for me, now it is set to 24 MHz only.

I can add next week more information about my board configuration if needed.

### Regression

- [x] This is a regression.

### Steps to reproduce

I can add next week more information about my board configuration if needed.

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- Windows
- ZephyrSDK 1.0.0
- https://github.com/zephyrproject-rtos/zephyr/commit/b1afb494b0c3b34534772bed0f10a3a61502dee5

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ofirshe**
After commit b1afb494b0c, zephyr,flash points to the soc-nv-flash child node instead of the
nxp,imx-flexspi-nor controller. This shifts the DTS hierarchy by one level, so
DT_PARENT(DT_CHOSEN(zephyr_flash)) now returns the flash controller node, not the FlexSPI bus node.

Fixes [106762](https://github.com/zephyrproject-rtos/zephyr/issues/106762)

### CODE REVIEW

File: boards/nxp/mimxrt1010_evk/init.c [hunk 1]
```diff
@@ -7,7 +7,7 @@
 
 void SystemInitHook(void)
 {
-#if DT_SAME_NODE(DT_NODELABEL(flexspi), DT_PARENT(DT_CHOSEN(zephyr_flash)))
+#if DT_SAME_NODE(DT_NODELABEL(flexspi), DT_GPARENT(DT_CHOSEN(zephyr_flash)))
```
Comment (JarmouniA) [inline boards/nxp/mimxrt1010_evk/init.c]:
```suggestion
#if DT_SAME_NODE(DT_NODELABEL(flexspi), DT_PARENT(DT_CHOSEN(zephyr_flash_controller)))
```
seems better

File: soc/nxp/imxrt/imxrt118x/soc.c [hunk 2]
```diff
@@ -612,15 +612,15 @@ __weak void clock_init(void)
 
 #endif /* CONFIG_MCUX_LPTMR_TIMER || CONFIG_COUNTER_MCUX_LPTMR */
 
-#if !(DT_NODE_HAS_COMPAT(DT_PARENT(DT_CHOSEN(zephyr_flash)), nxp_imx_flexspi_nor)) &&  \
+#if !(DT_NODE_HAS_COMPAT(DT_GPARENT(DT_CHOSEN(zephyr_flash)), nxp_imx_flexspi_nor)) &&  \
```
Comment (JarmouniA) [inline soc/nxp/imxrt/imxrt118x/soc.c]: Incorrect, `nxp,imx-flexspi-nor` is the flash controller's compatible.
```suggestion
#if !(DT_NODE_HAS_COMPAT(DT_CHOSEN(zephyr_flash_controller), nxp_imx_flexspi_nor)) &&  \
```

File: soc/nxp/imxrt/imxrt118x/soc.c [hunk 3]
```diff
@@ -612,15 +612,15 @@ __weak void clock_init(void)
...
 	defined(CONFIG_MEMC_MCUX_FLEXSPI) && DT_NODE_HAS_STATUS(DT_NODELABEL(flexspi), okay)
 	/* Configure FLEXSPI1 using SYS_PLL3_PFD0_CLK */
 	rootCfg.mux = kCLOCK_FLEXSPI1_ClockRoot_MuxSysPll3Pfd0;
 	rootCfg.div = 3;
 	CLOCK_SetRootClock(kCLOCK_Root_Flexspi1, &rootCfg);
 #endif
 
-#if !(DT_NODE_HAS_COMPAT(DT_PARENT(DT_CHOSEN(zephyr_flash)), nxp_imx_flexspi_nor)) &&  \
+#if !(DT_NODE_HAS_COMPAT(DT_GPARENT(DT_CHOSEN(zephyr_flash)), nxp_imx_flexspi_nor)) &&  \
```
Comment (JarmouniA) [inline soc/nxp/imxrt/imxrt118x/soc.c]: ditto

File: soc/nxp/imxrt/imxrt11xx/soc.c [hunk 4]
```diff
@@ -555,15 +555,15 @@ __weak void clock_init(void)
 #endif
 #endif
 
-#if !(DT_NODE_HAS_COMPAT(DT_PARENT(DT_CHOSEN(zephyr_flash)), nxp_imx_flexspi)) &&  \
+#if !(DT_NODE_HAS_COMPAT(DT_GPARENT(DT_CHOSEN(zephyr_flash)), nxp_imx_flexspi)) &&  \
```
Comment (JarmouniA) [inline soc/nxp/imxrt/imxrt11xx/soc.c]:
```suggestion
#if !(DT_NODE_HAS_COMPAT(DT_PARENT(DT_CHOSEN(zephyr_flash_controller)), nxp_imx_flexspi)) &&  \
```

File: soc/nxp/imxrt/imxrt11xx/soc.c [hunk 5]
```diff
@@ -555,15 +555,15 @@ __weak void clock_init(void)
...
 	defined(CONFIG_MEMC_MCUX_FLEXSPI) && DT_NODE_HAS_STATUS_OKAY(DT_NODELABEL(flexspi))
 	/* Configure FLEXSPI1 using OSC_RC_48M_DIV2 */
 	rootCfg.mux = kCLOCK_FLEXSPI1_ClockRoot_MuxOscRc48MDiv2;
 	rootCfg.div = 1;
 	CLOCK_SetRootClock(kCLOCK_Root_Flexspi1, &rootCfg);
 #endif
 
-#if !(DT_NODE_HAS_COMPAT(DT_PARENT(DT_CHOSEN(zephyr_flash)), nxp_imx_flexspi)) &&  \
+#if !(DT_NODE_HAS_COMPAT(DT_GPARENT(DT_CHOSEN(zephyr_flash)), nxp_imx_flexspi)) &&  \
```
Comment (JarmouniA) [inline soc/nxp/imxrt/imxrt11xx/soc.c]:
```suggestion
#if !(DT_NODE_HAS_COMPAT(DT_PARENT(DT_CHOSEN(zephyr_flash_controller)), nxp_imx_flexspi)) &&  \
```

**Review by JarmouniA — CHANGES_REQUESTED** [review]

File: soc/nxp/imxrt/imxrt118x/soc.c (hunk 2 above)
Comment (butok) [reply soc/nxp/imxrt/imxrt118x/soc.c]: Agree. `DT_CHOSEN(zephyr_flash_controller) `is more universal than `DT_GPARENT(DT_CHOSEN(zephyr_flash)`

**Review by JarmouniA — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]
