### PR TITLE
drivers: uart: mcux_flexcomm: Avoid reading registers when no clock

### LINKED ISSUE #102678: uart_mcux_flexcomm driver should wait for a register check if the uart isn't enabled
### Describe the bug

When exiting from a low power mode if a recoverable fault happens (not hard-fault) during the wakeup sequence, the function **mcux_flexcomm_poll_out()** tries to send information about the reset reason using the uart. 
The main problem is that the **mcux_flexcomm_poll_out()** is trying to read some status registers from the uart but the clocks haven't been reconfigured **causing an infinite wait** while reading the register in this line:

while (!(USART_GetStatusFlags(config->base) & kUSART_TxFifoNotFullFlag)) {}

while (!(USART_GetStatusFlags(config->base) & kUSART_TxFifoEmptyFlag)) {}

A time-out should be added to this conditions to interrupt the infinite wait or check if the clocks are configured previous to check for the uart registers

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by davidmissael**
The uart_mcux_flexcomm driver must avoid reading registers from the uart when the clocks are not enabled. This will cause and infinite wait state blocking execution.
Fixes #102678

### CODE REVIEW

**Comment by Holt-Sun** [comment]
Please fix the compliance check issue.

File: drivers/serial/uart_mcux_flexcomm.c [hunk 1]
```diff
@@ -165,13 +165,17 @@ static void mcux_flexcomm_poll_out(const struct device *dev,
...
+	timeout = 0;
 
 	/* Wait until space is available in TX FIFO, as per API description:
 	 * This routine checks if the transmitter is full.
 	 * When the transmitter is not full, it writes a character to the data register.
 	 * It waits and blocks the calling thread otherwise.
 	 */
-	while (!(USART_GetStatusFlags(config->base) & kUSART_TxFifoNotFullFlag)) {
+	while ((!(USART_GetStatusFlags(config->base) & kUSART_TxFifoNotFullFlag)) || timeout < 1000) {
+		timeout++;
```
Comment (DerekSnell) [inline drivers/serial/uart_mcux_flexcomm.c]: If this while loop times out, the driver should return with an error.  It should not continue to write to the TX FIFO

**Review by DerekSnell — DISMISSED** [review]
Hi @davidmissael ,
I realize this is only in Draft state right now, but this needs some work.  Also the commit message and PR title are misleading.  This change does not avoid reading registers if there is no clock.  It does not check if the clock is active.  Right now, it just adds a time out.

File: drivers/serial/uart_mcux_flexcomm.c (hunk 1 above)
Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: Hi @DerekSnell yes this does not solves the issue, this was only a place holder to have the PR active (that's why I tagged it as draft), I'm working on this and the intention is to check if the clocks are active previous to wait for the FIFOs. I got stuck in other activities but this is under my radar and I'm planning to have the first implementation no later the next week

File: drivers/serial/uart_mcux_flexcomm.c [hunk 2]
```diff
@@ -161,26 +162,87 @@ static int mcux_flexcomm_poll_in(const struct device *dev, unsigned char *c)
...
 
+static uint32_t mcux_flexcomm_get_id(const USART_Type *base)
+{
+	uint32_t id = 0;
+
+#ifdef CONFIG_TRUSTED_EXECUTION_SECURE
+	/* If trust-zone is enabled then check for the secured
+	 * address offset.
+	 */
+	if (base == (USART_Type *)FLEXCOMM0) {
```
Comment (Holt-Sun) [inline drivers/serial/uart_mcux_flexcomm.c]: Please explain why only handle instance 0,1,2,3 and 14, what about others?

File: drivers/serial/uart_mcux_flexcomm.c [hunk 3]
```diff
@@ -161,26 +162,87 @@ static int mcux_flexcomm_poll_in(const struct device *dev, unsigned char *c)
 	return ret;
 }
 
+static uint32_t mcux_flexcomm_get_id(const USART_Type *base)
```
Comment (Holt-Sun) [inline drivers/serial/uart_mcux_flexcomm.c]: Is there any chance to use [FLEXCOMM_GetInstance](https://github.com/zephyrproject-rtos/hal_nxp/blob/125d3a401db81445db940f502991cb45d3c4a9e3/mcux/mcux-sdk-ng/drivers/flexcomm/fsl_flexcomm.c#L83)?

Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: Hi @Holt-Sun thanks for the recommendation. I have an implementation using this API you are suggesting, however @DerekSnell recommends to use the driver clock_control and the API clock_control_get_rate since we are not sure if all the soc are using CLOCK_GetFlexCommClkFreq to get the clock frequency. 
   Using this API has its challenge since it requires to get the subsystem argument and this does not match with the index retrieved from FLEXCOMM_GetInstance, so we need to crate a function to transform the indexes in order to get the right subsystem from the device->base. The sybsystems are defined at "mcux_lpc_syscon_clock.h". I'm evaluating this implementation and try to get a solution.
There's another issue with the RW612 I discussed with Derek. The flexcomm14 has not the right index, if you use the API you recommended (FLEXCOMM_GetInstance), this will retrieve the index 4 instead of the index 14 and this will cause an issue when using the flexcomm14.

File: drivers/serial/uart_mcux_flexcomm.c (hunk 2 above)
Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: Yes it was a mistake just thinking about the RW612. I removed this approach and evaluating using the FLEXCOMM_GetInstance or the clock_control_get_rate.

File: drivers/serial/uart_mcux_flexcomm.c (hunk 3 above)
Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: Hi @Holt-Sun using driver clock_control to verify the flexcomm's clock source complicated a lot the implementation, it also requires to get a device tree node from a driver within another driver and Im not pretty sure fi this is allowed architecturally speaking in zephyr.
I used the API recommended by you **FLEXCOMM_GetInstance** to get the ID and check the specific flexcomm frequency. Plase take a look on the commit.

File: drivers/serial/uart_mcux_flexcomm.c [hunk 4]
```diff
@@ -165,22 +166,44 @@ static void mcux_flexcomm_poll_out(const struct device *dev,
...
+	flexcomm_id = FLEXCOMM_GetInstance(config->base);
+#ifdef CONFIG_SOC_RW612
+	/* RW61x has a gap in flexcomms numbering, if the flexcomm14 is
+	 * received as base address, the API FLEXCOMM_GetInstance will
+	 * return the instance 4 and this will cause the clock frequency
+	 * check to return 0
 	 */
-	while (!(USART_GetStatusFlags(config->base) & kUSART_TxFifoNotFullFlag)) {
+	if (flexcomm_id == 4) {
+		flexcomm_id = 14;
```
Comment (Holt-Sun) [inline drivers/serial/uart_mcux_flexcomm.c]: Hardcoding this mapping in the Zephyr UART driver is very fragile.

File: drivers/serial/uart_mcux_flexcomm.c [hunk 5]
```diff
@@ -165,22 +166,44 @@ static void mcux_flexcomm_poll_out(const struct device *dev,
...
-
-	/* Wait until space is available in TX FIFO, as per API description:
-	 * This routine checks if the transmitter is full.
-	 * When the transmitter is not full, it writes a character to the data register.
-	 * It waits and blocks the calling thread otherwise.
+	uint32_t flexcomm_id;
+
+	/* Get the flexcomm's id using the received base address */
+	flexcomm_id = FLEXCOMM_GetInstance(config->base);
+#ifdef CONFIG_SOC_RW612
```
Comment (zejiang0jason) [inline drivers/serial/uart_mcux_flexcomm.c]: I see some other platforms also have such issue, like RT600. Need also consider them.

https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/mcux-sdk-ng/devices/RT/RT600/MIMXRT685S/drivers/fsl_clock.h#L82-L86

https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/mcux-sdk-ng/devices/RT/RT600/MIMXRT685S/drivers/fsl_clock.c#L605-L618

File: drivers/serial/uart_mcux_flexcomm.c [hunk 6]
```diff
@@ -165,22 +166,44 @@ static void mcux_flexcomm_poll_out(const struct device *dev,
...
+	/* RW61x has a gap in flexcomms numbering, if the flexcomm14 is
+	 * received as base address, the API FLEXCOMM_GetInstance will
+	 * return the instance 4 and this will cause the clock frequency
+	 * check to return 0
```
Comment (butok) [inline drivers/serial/uart_mcux_flexcomm.c]: Should this logic be added to FLEXCOMM_GetInstance()?

Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: I see 2 options, add this logic in the FLEXCOMM_GetInstance() as you mentioned or fix the array in the definition of **FLEXCOMM_BASE_ADDRS**. For example, for the case of the RW612 this array is defined at RW612_COMMON.h but the array only has the flexcomms available for the platform consecutive like:

https://github.com/zephyrproject-rtos/hal_nxp/blob/22a92524af8ff98fcfbbbdb345509b76729344b1/mcux/mcux-sdk-ng/devices/Wireless/RW/RW612/RW612_COMMON.h#L1163

The API FLEXCOMM_GetInstance() uses this array to get the flexcomm index, that's why the flexcomm14 returns a 4 instead a 14, because is in the position 4 in the array. The array must include NULL pointers where there is not a flexcomm, and this should apply for all platforms. 

What could be and acceptable solution? @Holt-Sun @butok @zejiang0jason

File: drivers/serial/uart_mcux_flexcomm.c (hunk 5 above)
Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: Hi @zejiang0jason I saw the same issue. What could be the best solution?
I think we need to fix the array in the definition of FLEXCOMM_BASE_ADDRS. For example, for the case of the RW612 this array is defined at RW612_COMMON.h but the array only has the flexcomms available for the platform consecutive like:

https://github.com/zephyrproject-rtos/hal_nxp/blob/22a92524af8ff98fcfbbbdb345509b76729344b1/mcux/mcux-sdk-ng/devices/Wireless/RW/RW612/RW612_COMMON.h#L1163


The API FLEXCOMM_GetInstance() uses this array to get the flexcomm index, that's why the flexcomm14 returns a 4 instead a 14, because is in the position 4 in the array. The array must include NULL pointers where there is not a flexcomm, and this should apply for all platforms.

File: drivers/serial/uart_mcux_flexcomm.c (hunk 4 above)
Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: Agree. Jason showed some platforms with the same problem.

File: drivers/serial/uart_mcux_flexcomm.c (hunk 3 above)
Comment (Holt-Sun) [reply drivers/serial/uart_mcux_flexcomm.c]: In this driver we already have both the clock controller device and the clock subsystem in the instance config, so using clock_control_get_rate() does not require looking up another DT node at runtime. It is already wired into the driver configuration.

Also, the sparse-numbering issue is a good reason to avoid relying on FLEXCOMM_GetInstance() here. For example, the RT600 HAL implementation of CLOCK_GetFlexCommClkFreq() already treats FLEXCOMM IDs as real hardware IDs and explicitly handles 0..7, 14, and 15. By contrast, FLEXCOMM_GetInstance() returns the index in FLEXCOMM_BASE_ADDRS. On sparse-numbered SoCs those are not equivalent, which is why the RW612 and RT600 cases become fragile.

So my suggestion is: using the existing Zephyr clock_control_get_rate() wiring in this driver avoids the sparse-ID mismatch and keeps the logic at the Zephyr driver layer

```
static void mcux_flexcomm_poll_out(const struct device *dev,
					     unsigned char c)
{
	const struct mcux_flexcomm_config *config = dev->config;
	uint32_t clock_rate;

	/* Avoid touching UART registers while the peripheral clock is unavailable.
	 * Some clock drivers report this as an error, while others return 0 Hz.
	 */
	if ((clock_control_get_rate(config->clock_dev, config->clock_subsys,
				    &clock_rate) != 0) || (clock_rate == 0U)) {
		return;
	}
        .......
}
```

Comment (zejiang0jason) [reply drivers/serial/uart_mcux_flexcomm.c]: Hello @davidmissael , could you please update like this? we can run CI to test all platforms, thanks.

Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: Thank you, I did not notice the "clock_control_get_rate" API it was exposed to the drivers. I tracked this interface to get the original function (for the mcux) **mcux_lpc_syscon_clock_control_get_subsys_rate** and that where I was stuck. Thanks so much for the clarification.
I tested and it worked in my platform. Once CI test finishes we can try to merge it.

**Review by Holt-Sun — DISMISSED** [review]

File: drivers/serial/uart_mcux_flexcomm.c [hunk 7]
```diff
@@ -21,6 +21,7 @@
 #include <fsl_usart.h>
 #include <soc.h>
 #include <fsl_device_registers.h>
+#include <fsl_flexcomm.h>
```
Comment (hakehuang) [inline drivers/serial/uart_mcux_flexcomm.c]: this file is not needed

**Review by zejiang0jason — DISMISSED** [review]

File: drivers/serial/uart_mcux_flexcomm.c (hunk 7 above)
Comment (davidmissael) [reply drivers/serial/uart_mcux_flexcomm.c]: Removed, thanks

**Review by mmahadevan108 — APPROVED** [review]

**Review by zejiang0jason — APPROVED** [review]

**Review by Holt-Sun — APPROVED** [review]

**Review by hakehuang — APPROVED** [review]
