### PR TITLE
tests: Bluetooth: fix att_mtu warnings on gcc-12

### LINKED ISSUE #55669: Bluetooth test: host/att/mtu_update fails to build w gcc12
**Describe the bug**
tests/bluetooth/bsim/host/att/mtu_update  fails to build with gcc 12 due to its new memcpy checks

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja  -DBOARD=nrf52_bsim -DCONF_FILE=prj.conf -DCMAKE_C_FLAGS="-Werror" ${ZEPHYR_BASE}/tests/bluetooth/bsim/host/att/mtu_update 
3. ninja 

**Expected behavior**
It builds without scary warnings/errors

**Impact**
* Prevents regression for users using gcc-12

**Logs and console output**
```
FAILED: CMakeFiles/app.dir/../zephyr/samples/bluetooth/mtu_update/central/src/central_mtu_update.c.obj 
ccache /usr/bin/gcc -DKERNEL -DNRF52833_XXAA -D_POSIX_C_SOURCE=200809 -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -D__ZEPHYR__=1 -I${ZEPHYR_BASE}/../zephyrproject/modules/bsim_hw_models/nrf_hw_models/src/nrfx/mdk_replacements -I${ZEPHYR_BASE}/include -I${ZEPHYR_BASE}/bsim_out/tests/bluetooth/bsim/host/att/mtu_update/prj.conf/zephyr/include/generated -I${ZEPHYR_BASE}/soc/posix/inf_clock -I${ZEPHYR_BASE}/boards/posix/nrf52_bsim -I${ZEPHYR_BASE}/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/nrfx_glue -I${ZEPHYR_BASE}/subsys/bluetooth -I${ZEPHYR_BASE}/../zephyrproject/modules/hal/nordic/nrfx -I${ZEPHYR_BASE}/../zephyrproject/modules/hal/nordic/nrfx/drivers/include -I${ZEPHYR_BASE}/../zephyrproject/modules/hal/nordic/nrfx/mdk -I${ZEPHYR_BASE}/modules/hal_nordic/nrfx/. -I${ZEPHYR_BASE}/../zephyrproject/modules/bsim_hw_models/nrf_hw_models/src/HW_models -I${ZEPHYR_BASE}/../zephyrproject/modules/bsim_hw_models/nrf_hw_models/src/nrfx/nrfx_replacements -I${ZEPHYR_BASE}/../zephyrproject/modules/crypto/tinycrypt/lib/include -I${ZEPHYR_BASE}/../bsim/components/libUtilv1/src -I${ZEPHYR_BASE}/../bsim/components/libPhyComv1/src "-Werror" -fno-strict-aliasing -O0 -imacros ${ZEPHYR_BASE}/bsim_out/tests/bluetooth/bsim/host/att/mtu_update/prj.conf/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -gdwarf-4 -fdiagnostics-color=always -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=${ZEPHYR_BASE}/tests/bluetooth/bsim/host/att/mtu_update=CMAKE_SOURCE_DIR -fmacro-prefix-map=${ZEPHYR_BASE}=ZEPHYR_BASE -fmacro-prefix-map=${ZEPHYR_BASE}/../zephyrproject=WEST_TOPDIR -ffunction-sections -fdata-sections -fprofile-arcs -ftest-coverage -fno-inline -m32 -include ${ZEPHYR_BASE}/arch/posix/include/posix_cheats.h -fno-freestanding -fshort-enums -std=c11 -MD -MT CMakeFiles/app.dir${ZEPHYR_BASE}/samples/bluetooth/mtu_update/central/src/central_mtu_update.c.obj -MF CMakeFiles/app.dir${ZEPHYR_BASE}/samples/bluetooth/mtu_update/central/src/central_mtu_update.c.obj.d -o CMakeFiles/app.dir${ZEPHYR_BASE}/samples/bluetooth/mtu_update/central/src/central_mtu_update.c.obj -c ${ZEPHYR_BASE}/samples/bluetooth/mtu_update/central/src/central_mtu_update.c
${ZEPHYR_BASE}/samples/bluetooth/mtu_update/central/src/central_mtu_update.c: In function ‘discover_func’:
${ZEPHYR_BASE}/samples/bluetooth/mtu_update/central/src/central_mtu_update.c:85:17: error: ‘memcpy’ reading 17 bytes from a region of size 4 [-Werror=stringop-overread]
   85 |                 memcpy(&uuid, BT_UUID_GATT_CCC, sizeof(uuid));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ${ZEPHYR_BASE}/samples/bluetooth/mtu_update/central/src/central_mtu_update.c:22:
${ZEPHYR_BASE}/include/zephyr/bluetooth/uuid.h:110:52: note: source object ‘<Ub090>’ of size 4
  110 |         ((struct bt_uuid *) ((struct bt_uuid_16[]) {BT_UUID_INIT_16(value)}))
      |                                                    ^
${ZEPHYR_BASE}/include/zephyr/bluetooth/uuid.h:901:9: note: in expansion of macro ‘BT_UUID_DECLARE_16’
  901 |         BT_UUID_DECLARE_16(BT_UUID_GATT_CCC_VAL)
      |         ^~~~~~~~~~~~~~~~~~
${ZEPHYR_BASE}/samples/bluetooth/mtu_update/central/src/central_mtu_update.c:85:31: note: in expansion of macro ‘BT_UUID_GATT_CCC’
   85 |                 memcpy(&uuid, BT_UUID_GATT_CCC, sizeof(uuid));
      |                               ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Environment**
 - OS: Linux
 - Toolchain: gcc 12.1.0 (Ubuntu's gcc-12 package)
 - Commit SHA: 68955ebdb6d8a9c6598810446fecc316209089e1 (latest HEAD)

### PR DESCRIPTION
**Pull request by jori-nordic**
The warnings are correct, we were copying 17 bytes from a 4-byte source.

Fixes #55669

### CODE REVIEW

**Comment by aescolar** [comment]
@jori-nordic the warning is gone with that change

**Comment by jori-nordic** [comment]
seems the test doesn't pass anymore, I'll fix it

File: samples/bluetooth/mtu_update/central/src/central_mtu_update.c [hunk 1]
```diff
@@ -82,7 +82,8 @@ static uint8_t discover_func(struct bt_conn *conn, const struct bt_gatt_attr *at
 			printk("Discover failed (err %d)\n", err);
 		}
 	} else if (!bt_uuid_cmp(discover_params.uuid, BT_UUID_MTU_TEST_NOTIFY)) {
-		memcpy(&uuid, BT_UUID_GATT_CCC, sizeof(uuid));
+		memset(&uuid, 0, sizeof(uuid));
+		memcpy(&uuid, BT_UUID_GATT_CCC, sizeof(struct bt_uuid_16));
 		discover_params.uuid = &uuid.uuid;
```
Comment (Thalley) [inline samples/bluetooth/mtu_update/central/src/central_mtu_update.c:87]: It should also be possible to do 
```
static const struct bt_uuid *ccc_uuid = BT_UUID_GATT_CCC;

discover_params.uuid = ccc_uuid;
```

As an alternative (that's how we often do it in the LE Audio implementation)

Comment (jori-nordic) [reply samples/bluetooth/mtu_update/central/src/central_mtu_update.c:87]: but muh memory!
I'll align it with yours then :)

**Review by Thalley — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

File: samples/bluetooth/mtu_update/central/src/central_mtu_update.c (hunk 1 above)
Comment (alwa-nordic) [reply samples/bluetooth/mtu_update/central/src/central_mtu_update.c]: Out of scope of course: Would it work to have a c-file with `const struct bt_uuid ccc_uuid`, etc..? With an accompanying header with `extern const struct bt_uuid ccc_uuid`. The linker will strip out unused symbols, right? I think this will actually save ROM and RAM.

Comment (Thalley) [reply samples/bluetooth/mtu_update/central/src/central_mtu_update.c]: > EDIT: Oh. It's a bit more complicated, since bt_uuid is a "superclass", so it must be a pointer.

Yeah, the `bt_uuid` is not that easy to work with :D That type has also caused countless coverity false positives due to how it's implemented

Comment (alwa-nordic) [reply samples/bluetooth/mtu_update/central/src/central_mtu_update.c]: I though trough it again, and removed the EDIT. We should just have the real types on the objects (e.g. bt_uuid_16). And maybe define a macro for doing the CONAINTER_OF-inverse `&ccc_uuid.uuid`.

Comment (Thalley) [reply samples/bluetooth/mtu_update/central/src/central_mtu_update.c]: > I though trough it again, and removed the EDIT. We should just have the real types on the objects (e.g. bt_uuid_16). And maybe define a macro for doing the CONAINTER_OF-inverse `&ccc_uuid.uuid`.

That would certainly make it easier to work with. I am not familiar with the design decisions on why it is how it is now, but I assume it's a form of optimization.

**Review by carlescufi — APPROVED** [review]
