### PR TITLE
logging: rtt: Do not retry on error in non blocking mode

### LINKED ISSUE #28211: "High" current drawn when ussing RTT log back-end with CONFIG_LOG_IMMEDIATE and CONFIG_LOG_BACKEND_RTT_MODE_DROP
**Describe the bug**
When a log statement is executed with `CONFIG_LOG_IMMEDIATE`, `CONFIG_LOG_BACKEND_RTT_MODE_DROP=y` set and RTT log back-end selected, a great deal of current is used.

**To Reproduce**
1. Get any sample application where the MCU is mostly IDLE:
  * `CONFIG_LOG_IMMEDIATE=y`
  * `CONFIG_LOG_BACKEND_RTT=y`
  * `CONFIG_LOG_BACKEND_RTT_MODE_DROP=y`
2. Attach a current probe to the board
3. Detach any debug probe
4. Restart the application

On an application that wakes up every second and produce some log the following is observed:
image

**Expected behavior**
RTT log should be equivalent to a memcpy, so the core should wake up for a short amount of time and then go back to sleep. With an application that wake up every second and do some logging, the current profile should look like:
image

**Impact**
This is a real show stopper, the current consumption increases by ~x50

### PR DESCRIPTION
**Pull request by kurddt**
Retry in non blocking mode can lead to a quite long (busy) wait.
Fixes #28211

### CODE REVIEW

File: subsys/logging/log_backend_rtt.c [hunk 1]
```diff
@@ -201,7 +201,8 @@ static void on_write(int retry_cnt)
 static int data_out_block_mode(uint8_t *data, size_t length, void *ctx)
 {
 	int ret = 0;
-	int retry_cnt = CONFIG_LOG_BACKEND_RTT_RETRY_CNT;
+	int retry_cnt = IS_ENABLED(CONFIG_LOG_BACKEND_RTT_MODE_BLOCK) ?
```
Comment (nordic-krch) [inline subsys/logging/log_backend_rtt.c:204]: can you add a comment which would explain that this function is also used in drop mode if operations are synchronous?

Comment (kurddt) [reply subsys/logging/log_backend_rtt.c:206]: done

**Review by nordic-krch — APPROVED** [review]
looks good. thanks

**Comment by MaureenHelm** [comment]
Does this PR fix #28211? If so, please update the PR description to use the "Fixes #nnnn" keyword. See [here](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

**Review by MaureenHelm — APPROVED** [review]
