### PR TITLE
net: context: Fix the ICMP error on udp

### LINKED ISSUE #70020: net: ICMP error occurs when accessing simultaneously over UDP
**Describe the bug**

We are implementing a CoAP Server using the zephyr's CoAP library. 
When executing a test program that continuously sends CoAP GET requests to this CoAP server from two CoAP clients, the following error may be detected:

 ` Mar 10 10:36:31.436 WARN ** 10.30.5.20:50338 <-> 10.30.5.10:5683 UDP : coap_socket_recv: ICMP: Connection refused`

 - What target platform are you using?
    - Xilinx Artix-7 FPGA  (Soft core: ARM Cortex-M3)
 - What have you tried to diagnose or workaround this issue?
   - After receiving an ICMP error on the CoAP client side, we are trying to retries.
 - Is this a regression? If yes, have you been able to "git bisect" it to a specific commit?
   - No

**To Reproduce**
Since our platform is not a generic platform, we will provide replication steps using STM32 F429 board.

1. add extra conf (extra.conf)
    ```
    CONFIG_NET_IPV6=n
    CONFIG_NET_CONFIG_NEED_IPV6=n
    CONFIG_NET_IPV4=y
    CONFIG_NET_CONFIG_NEED_IPV4=y
    CONFIG_NET_CONFIG_MY_IPV4_ADDR="10.30.5.10"
    CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.0.0"
    CONFIG_NET_CONFIG_MY_IPV4_GW="10.30.5.1"
    ```
2. To induce ICMP errors, as they are timing-dependent, we are applying the following patch to ensure that the issue occurs promptly.
    ```
    diff --git a/subsys/net/ip/net_context.c b/subsys/net/ip/net_context.c
    index ae7a4a4e84..19418ad358 100644
    --- a/subsys/net/ip/net_context.c
    +++ b/subsys/net/ip/net_context.c
    @@ -2411,6 +2411,8 @@ static int recv_udp(struct net_context *context,
                    return ret;
            }
     
    +       k_sleep(K_MSEC(1));
    +
            if (IS_ENABLED(CONFIG_NET_IPV6) &&
                net_context_get_family(context) == AF_INET6) {
                    if (net_sin6_ptr(&context->local)->sin6_addr) {
    ```
3. build
   ```
   rm -rf build & west build -b nucleo_f429zi zephyr/samples/net/sockets/coap_server -- -DEXTRA_CONF_FILE=${PWD}/right-upper.conf
   ```
4. flash
    ```
     west flash
    ```
5. confirm to ready fo coap server
    ```
    *** Booting Zephyr OS build v3.6.0-674-g826ac0755b41 ***
   [00:00:00.011,000] <inf> net_config: Initializing network
   [00:00:00.011,000] <inf> net_config: Waiting interface 1 (0x20000ea8) to be up...
   [00:00:02.011,000] <inf> net_config: Interface 1 (0x20000ea8) coming up
   [00:00:02.011,000] <inf> net_config: IPv4 address: 10.30.5.10
   [00:00:02.013,000] <inf> net_coap_service_sample: CoAP service coap_server started
   uart:~$  
    ```
6. Execute the following script on two console
    ```
    while true
    do
	    coap-client -m get coap://10.30.5.10/test
    done
    ```
7. ICMP error occurs
    ```
    Mar 10 19:22:55.714 WARN ** 10.30.5.20:46563 <-> 10.30.5.10:5683 UDP : coap_socket_recv: ICMP: Connection refused
    ```

**Expected behavior**
No ICMP errors occurs

**Impact**
annoyance

**Logs and console output**
We captured packets using `wireshark` when this error occurred, and the following error message was replied from the CoAP Server side:

coap-icmp-error

Detail of ICMP error packet:  (`Dst port: 5683` is default port number of CoAP Server)

**Environment (please complete the following information):**
 - OS:
   - 22.04.4 LTS (Build OS) 
 - Toolchain (e.g Zephyr SDK, ...)
   - zephyr-sdk-0.16.3
 - Commit SHA
   - 826ac07

### PR DESCRIPTION
**Pull request by sasataku**
This commit fixes the ##70020.

When receiving a UDP packet, net_conn_input() searches for a matching connection within `conn_used`.

However, when receiving UDP packets simultaneously from multiple clients, we may encounter a situation where the connection that was supposed to be bound cannot be found within `conn_used`, and raise the ICMP error.

This is because, within recv_udp(), to avoid the failure of bind_default(), we temporarily remove it from `conn_used` using net_conn_unregister().

If the context already has a connection handler, it means it's already registered. In that case, all we have to do is 1) update the callback registered in the net_context and 2) update the user_data using net_conn_change_callback().

Since net_conn_change_callback() takes the _other_ callback function, net_context_packet_received() (I know it's confusing), this must be the same function passed in net_conn_register() down below.

-----

Fixes #70020

### CODE REVIEW

**Comment by sasataku** [comment]
I've tested the some zephyr test that called net_context_recv() as below, and all passed.

- tests/net/context
   ```
   SUITE PASS - 100.00% [net_context]: pass = 15, fail = 0, skip = 0, total = 15 duration = 5.015 seconds
   ```
- tests/net/ipv6
  ```
  SUITE PASS - 100.00% [net_ipv6]: pass = 26, fail = 0, skip = 0, total = 26 duration = 2.456 seconds
   ```
- tests/net/tcp
   ```
   SUITE PASS - 100.00% [net_tcp]: pass = 18, fail = 0, skip = 0, total = 18 duration = 6.268 seconds
   ```
-  tests/net/traffic_class
   ```
   SUITE PASS - 100.00% [net_traffic_class]: pass = 11, fail = 0, skip = 0, total = 11 duration = 0.183 seconds
   ```
- tests/net/virtual/
   ```
   SUITE PASS - 100.00% [net_virtual]: pass = 10, fail = 0, skip = 0, total = 10 duration = 0.010 seconds
   ```

File: subsys/net/ip/net_context.c [hunk 1]
```diff
@@ -2401,9 +2401,21 @@ static int recv_udp(struct net_context *context,
...
 	ARG_UNUSED(timeout);
 
+	/* If the context already has a connection handler, it means it's
+	 * already registered. In that case, all we have to do is 1) update
+	 * the callback registered in the net_context and 2) update the
+	 * user_data using net_conn_change_callback().
+	 *
+	 * Since net_conn_change_callback() takes the _other_ callback
+	 * function, net_context_packet_received() (I know it's confusing),
+	 * this must be the same function passed in net_conn_register() down below.
```
Comment (jukkar) [inline subsys/net/ip/net_context.c:2411]: This comment needs some clarification, it is a bit difficult to follow, could you formulate it better. Also remove the `(I know it's confusing)` sentence.

File: subsys/net/ip/net_context.c [hunk 2]
```diff
@@ -2401,9 +2401,21 @@ static int recv_udp(struct net_context *context,
...
+	 */
 	if (context->conn_handler) {
-		net_conn_unregister(context->conn_handler);
-		context->conn_handler = NULL;
+		context->recv_cb = cb;
+		ret = net_conn_change_callback(context->conn_handler,
+					 net_context_packet_received,
+					 user_data);
```
Comment (jukkar) [inline subsys/net/ip/net_context.c:2417]: Please fix the indentation here, these two lines should start the same column as the `context->conn_handler`

File: subsys/net/ip/net_context.c [hunk 3]
```diff
@@ -2401,9 +2401,21 @@ static int recv_udp(struct net_context *context,
```
Comment (jukkar) [inline subsys/net/ip/net_context.c:2401]: Could you change the `This commit fixes the #70020.` from the commit message into `Fixes #70020` and place it before the signed-off-by line. This way it is easier to grep the log later if one needs to figure out the exact commit that fixed it. See examples in other commits in the tree

**Review by jukkar — COMMENTED** [review]
Looks good. Could you also fix the `recv_raw()` which has the same issue? Just add separate commit for that in this PR.

File: subsys/net/ip/net_context.c (hunk 3 above)
Comment (sasataku) [reply subsys/net/ip/net_context.c:2401]: Okay, I will fix it.

File: subsys/net/ip/net_context.c (hunk 1 above)
Comment (sasataku) [reply subsys/net/ip/net_context.c:2411]: Okay. I will update the comment.

File: subsys/net/ip/net_context.c (hunk 2 above)
Comment (sasataku) [reply subsys/net/ip/net_context.c:2417]: Sorry for missing it. I will fix the indentation.

**Comment by sasataku** [comment]
> Some of the network tests did not like this change, could you check the CI logs?

This commit results in the failure of `test_dgram_connected()`.
https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/net/socket/udp/src/main.c#L1307

I suspect this is because the remote address set by the `connect()` after the `bind()` is not being reflected in the connection.
I'm currently considering a corrective approach, and I believe we need a function to update the remote address and flags set only within `net_conn_register()`.

**Comment by sasataku** [comment]
> This commit results in the failure of test_dgram_connected().

I've updated the PR for resolve the  failure of `test_dgram_connected()`.
However I had other unit test failure, so I will investigate it.

File: subsys/net/ip/net_context.c [hunk 4]
```diff
@@ -2401,9 +2401,29 @@ static int recv_udp(struct net_context *context,
...
+		ret = net_conn_change_callback(context->conn_handler,
+					       net_context_packet_received,
+					       user_data);
+		if (ret) {
+			goto end;
+		}
+		ret = net_conn_change_remote(context->conn_handler,
+					     context->flags & NET_CONTEXT_REMOTE_ADDR_SET ?
+								&context->remote : NULL,
+					     ntohs(net_sin(&context->remote)->sin_port));
```
Comment (yashi) [inline subsys/net/ip/net_context.c:2425]: How about having `net_conn_update()` and do both.  Because we don't have any user of `net_conn_change_callback()` in tree and it's not a public API anyway.

So that a call-site will become something like:

```c
if (context->conn_handler) {
    ret = net_conn_update();
} else {
    ret = bind_default();
    if (ret >= 0) {
        ret = net_conn_register();
    }
}

return ret;
```

@jukkar any thoughts?

Comment (yashi) [reply subsys/net/ip/net_context.c:2425]: I think having a static version of `net_conn_change_callback()` and `net_conn_change_remote()` in connection.c is fine. I assume that it's better to have `net_conn_update()` for net_context.c to consume.

**Comment by sasataku** [comment]
I've passed the all unit tests.

File: subsys/net/ip/connection.c [hunk 5]
```diff
@@ -280,6 +280,7 @@ int net_conn_register(uint16_t proto, uint8_t family,
 {
```
Comment (jukkar) [inline subsys/net/ip/connection.c:280]: Minor nit, but you should put the `Fixes #70020` to only one commit that has the actual fix. It looks like it is the 2nd one, all the other commits do not have to mention that.
So in the first commit, you can remove the
```
This is a prepared commit for fixes https://github.com/zephyrproject-rtos/zephyr/issues/70020.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/70020
```
lines.

File: subsys/net/ip/net_context.c (hunk 4 above)
Comment (jukkar) [reply subsys/net/ip/net_context.c:2425]: @yashi good point, I like your `net_conn_update()` idea, we could do it like that.

File: subsys/net/ip/connection.c (hunk 5 above)
Comment (sasataku) [reply subsys/net/ip/connection.c:280]: Thank you. I will update the commit log.

File: subsys/net/ip/net_context.c (hunk 4 above)
Comment (sasataku) [reply subsys/net/ip/net_context.c:2425]: Thank you for your review.
I will update the PR based on `net_conn_update()` idea.

File: subsys/net/ip/net_context.c [hunk 6]
```diff
@@ -2401,53 +2401,68 @@ static int recv_udp(struct net_context *context,
...
-		context->conn_handler = NULL;
-	}
+		context->recv_cb = cb;
+		ret = net_conn_update(context->conn_handler,
+				      net_context_packet_received,
+				      user_data,
+				      context->flags & NET_CONTEXT_REMOTE_ADDR_SET ?
+						&context->remote : NULL,
+				      ntohs(net_sin(&context->remote)->sin_port));
+	} else {
```
Comment (jukkar) [inline subsys/net/ip/net_context.c:2422]: The else branch is certainly one option, it is just that there is lot of code to indent which makes the lines longer. We could avoid the else branch like it was originally. For example like this:
```
if (context->conn_handler != NULL) {
	context->recv_cb = cb;
	ret = net_conn_update(context->conn_handler,
			      net_context_packet_received,
			      user_data,
			      context->flags & NET_CONTEXT_REMOTE_ADDR_SET ?
					&context->remote : NULL,
			      ntohs(net_sin(&context->remote)->sin_port));
	return ret;
}
```

File: subsys/net/ip/net_context.c [hunk 7]
```diff
@@ -2512,25 +2512,38 @@ static int recv_raw(struct net_context *context,
...
 
-	ret = bind_default(context);
-	if (ret) {
-		return ret;
-	}
+		ret = bind_default(context);
+		if (ret) {
+			return ret;
+		}
```
Comment (jukkar) [inline subsys/net/ip/net_context.c:2535]: Same thing here, no need for the else branch, just return after calling `net_conn_update()`

File: subsys/net/ip/net_context.c (hunk 6 above)
Comment (sasataku) [reply subsys/net/ip/net_context.c]: Okay, fixed.

File: subsys/net/ip/net_context.c (hunk 7 above)
Comment (sasataku) [reply subsys/net/ip/net_context.c]: Fixed

**Review by jukkar — APPROVED** [review]
LGTM.

@sasataku thank you for your contribution, it is much appreciated!

**Review by rlubos — APPROVED** [review]

**Comment by sasataku** [comment]
@jukkar
You're welcome. I'm also happy to contribute to zephyr project.
