### PR TITLE
Bluetooth: Mesh: Fix heartbeat sending on Friendship established/lost

### LINKED ISSUE #18194: [zephyr 1.14][MESH/NODE/CFG/HBP/BV-05-C] Zephyr does not send Heartbeat message on friendship termination
**Describe the bug**
Test case MESH/NODE/CFG/HBP/BV-05-C Lower Tester 1 requires Zephyr to send Heartbeat message once friendship was terminated with Lower Tester 2.

Mesh Profile 3.6.7.2 Publishing Heartbeat messages
```
Triggered publishing of Heartbeat messages is enabled by 
the Heartbeat Publication Features state (see Section 4.2.17.5):
...
• If the Low Power bit is set to 1, a Heartbeat message shall be
 published when the node establishes or loses Friendship (see Section 3.6.6.1).
```

**To Reproduce**
1. Run MESH/NODE/CFG/HBP/BV-05-C test case

**Expected behavior**
Zephyr sends Heartbeat triggered by friendship termination

**Impact**
Failing MESH/NODE/CFG/HBP/BV-05-C test case

**Screenshots or console output**
```
[00:08:53.500,640] <err> bt_mesh_lpn: No response from Friend after 4 retries
[00:08:53.500,640] <dbg> bt_mesh_lpn.clear_friendship: force 0 disable 0
[00:08:53.500,640] <dbg> bt_mesh_lpn.send_friend_clear: 
[00:08:53.631,225] <dbg> bt_mesh_lpn.lpn_set_state: established -> clear
[00:08:54.738,067] <dbg> bt_mesh_lpn.lpn_timeout: state: clear
[00:08:54.738,067] <dbg> bt_mesh_lpn.clear_friendship: force 0 disable 0
[00:08:54.738,067] <dbg> bt_mesh_lpn.send_friend_clear: 
[00:08:54.892,913] <dbg> bt_mesh_lpn.lpn_set_state: clear -> clear
Friendship (as LPN) lost with Friend 0x0003
[00:08:55.995,452] <dbg> bt_mesh_lpn.lpn_timeout: state: clear
[00:08:55.995,452] <dbg> bt_mesh_lpn.clear_friendship: force 0 disable 0
```

### PR DESCRIPTION
**Pull request by jhedberg**
Mesh Profile 3.6.7.2 Publishing Heartbeat messages:
    
```
Triggered publishing of Heartbeat messages is enabled by
the Heartbeat Publication Features state (see Section 4.2.17.5):
...
- If the Low Power bit is set to 1, a Heartbeat message shall be
published when the node establishes or loses Friendship (see Section 3.6.6.1).
```
  
Fixes #18194

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
@jhedberg can you please add this to the PR with Host Conformance issues manually instead of using the backport bot?

https://github.com/zephyrproject-rtos/zephyr/pull/18122

**Comment by jhedberg** [comment]
> @jhedberg can you please add this to the PR with Host Conformance issues manually instead of using the backport bot?

Sure, the bot will likely fail anyway since master has moved mesh from `subsys/bluetooth/host/mesh` to `subsys/bluetooth/mesh`

**Comment by jhedberg** [comment]
@MariuszSkamra it'd be good if you could test and verify that this fixes the failing tests, the patches are now also included in #18122 which may be the better PR to run the tests on since that matches what'll end up in LTS.

File: subsys/bluetooth/mesh/lpn.c [hunk 1]
```diff
@@ -222,8 +222,12 @@ static void clear_friendship(bool force, bool disable)
 		lpn->old_friend = lpn->frnd;
 	}
 
-	if (lpn_cb && lpn->frnd != BT_MESH_ADDR_UNASSIGNED) {
-		lpn_cb(lpn->frnd, false);
+	if (lpn->frnd != BT_MESH_ADDR_UNASSIGNED) {
+		bt_mesh_heartbeat_send();
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/lpn.c]: If I'm reading this correctly, I think there's a problem here. As `lpn_set_state()` isn't called yet, we'll be populating the heartbeat with the old LPN state here, mistakenly sending out a heartbeat with the pre-clear LPN flag, instead of the new one.

File: subsys/bluetooth/mesh/lpn.c [hunk 2]
```diff
@@ -958,6 +962,8 @@ int bt_mesh_lpn_friend_update(struct bt_mesh_net_rx *rx,
 
 		BT_INFO("Friendship established with 0x%04x", lpn->frnd);
 
+		bt_mesh_heartbeat_send();
+
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/lpn.c]: Looks like the same issue is here, with the `friend_response_received` being called below.

**Comment by jhedberg** [comment]
@trond-snekvik looks like you're right, good catch - I'll try to fix it

**Comment by jhedberg** [comment]
@trond-snekvik actually you discovered a bigger issue: the code shouldn't be setting the flag based on `BT_MESH_LPN_DISABLED`. That state just tells us we're not actively trying to look for Friends, whereas the spec associates the flag with a Friendship being established or not.

**Comment by jhedberg** [comment]
@trond-snekvik I've pushed updated (however only compile-tested) versions of the patches. Looks more reasonable?

**Review by carlescufi — APPROVED** [review]

**Comment by trond-snekvik** [comment]
Yep, looks resolved. About this `established` flag though, isn't that just a duplication of `lpn->state >= BT_MESH_LPN_ESTABLISHED`, or is there some more nuance to it?

**Review by trond-snekvik — APPROVED** [review]

**Review by MariuszSkamra — CHANGES_REQUESTED** [review]
Just as you wrote, the Heartbeat Publication is triggered by Heartbeat Publication Features state. So before you send Heartbeat message, you should check whether, 3rd bit (Low Power) is set in Heartbeat Publication Features.
```
diff --git a/subsys/bluetooth/host/mesh/lpn.c b/subsys/bluetooth/host/mesh/lpn.c
index 5ac3ad1ef3..b45b956b1e 100644
--- a/subsys/bluetooth/host/mesh/lpn.c
+++ b/subsys/bluetooth/host/mesh/lpn.c
@@ -200,6 +200,8 @@ static int send_friend_clear(void)
 static void clear_friendship(bool force, bool disable)
 {
        struct bt_mesh_lpn *lpn = &bt_mesh.lpn;
+       struct bt_mesh_cfg_srv *cfg = bt_mesh_cfg_get();
+       struct bt_mesh_subnet *sub;
 
        BT_DBG("force %u disable %u", force, disable);
 
@@ -246,7 +248,10 @@ static void clear_friendship(bool force, bool disable)
         */
        lpn->groups_changed = 1U;
 
-       bt_mesh_heartbeat_send();
+       sub = bt_mesh_subnet_get(cfg->hb_pub.net_idx);
+       if ((cfg->hb_pub.feat & BT_MESH_FEAT_LOW_POWER) && sub) {
+               bt_mesh_heartbeat_send();
+       }
 
        if (disable) {
                lpn_set_state(BT_MESH_LPN_DISABLED);
@@ -921,6 +926,7 @@ int bt_mesh_lpn_friend_update(struct bt_mesh_net_rx *rx,
 {
        struct bt_mesh_ctl_friend_update *msg = (void *)buf->data;
        struct bt_mesh_lpn *lpn = &bt_mesh.lpn;
+       struct bt_mesh_cfg_srv *cfg = bt_mesh_cfg_get();
        struct bt_mesh_subnet *sub = rx->sub;
        u32_t iv_index;
 
@@ -960,7 +966,10 @@ int bt_mesh_lpn_friend_update(struct bt_mesh_net_rx *rx,
 
                BT_INFO("Friendship established with 0x%04x", lpn->frnd);
 
-               bt_mesh_heartbeat_send();
+               if (cfg->hb_pub.feat & BT_MESH_FEAT_LOW_POWER) {
+                       bt_mesh_heartbeat_send();
+               }
 
                if (lpn_cb) {
                        lpn_cb(lpn->frnd, true);
```

with this,  MESH/NODE/CFG/HBP/BV-05-C is passing

File: subsys/bluetooth/mesh/transport.c [hunk 3]
```diff
@@ -1506,3 +1506,52 @@ void bt_mesh_rpl_clear(void)
...
+	struct bt_mesh_net_tx tx = {
+		.sub = bt_mesh_subnet_get(cfg->hb_pub.net_idx),
+		.ctx = &ctx,
+		.src = bt_mesh_model_elem(cfg->model)->addr,
+		.xmit = bt_mesh_net_transmit_get(),
+	};
+
+	hb.init_ttl = cfg->hb_pub.ttl;
+
+	if (bt_mesh_relay_get() == BT_MESH_RELAY_ENABLED) {
```
Comment (MariuszSkamra) [inline subsys/bluetooth/mesh/transport.c]: Is that correct? Shouldn't the current cfg->hb_pub.feat status be returned? Does not mean that any test case is failing because of this but I'm just asking.

As written in 4.3.2.63 Config Hearbeat Publication Status:
"The Features field shall identify the Heartbeat Publication Features state (see Section 4.2.17.5)."

**Review by MariuszSkamra — CHANGES_REQUESTED** [review]

**Comment by jhedberg** [comment]
> Just as you wrote, the Heartbeat Publication is triggered by Heartbeat Publication Features state. So before you send Heartbeat message, you should check whether, 3rd bit (Low Power) is set in Heartbeat Publication Features.

@MariuszSkamra good point, and thanks for the refresher on how heartbeat publication is supposed to work 😄 

I'll update the PR in a moment.

File: subsys/bluetooth/mesh/transport.c (hunk 3 above)
Comment (jhedberg) [reply subsys/bluetooth/mesh/transport.c]: @MariuszSkamra I always understood cfg->hb_pub.feat as the triggers for sending the message, but not for controlling the content of the message. I'll need to double-check the spec and test spec.

**Comment by jhedberg** [comment]
```
+       sub = bt_mesh_subnet_get(cfg->hb_pub.net_idx);
+       if ((cfg->hb_pub.feat & BT_MESH_FEAT_LOW_POWER) && sub) {
+               bt_mesh_heartbeat_send();
```

@MariuszSkamra the checking for the subnet is redundant. The configuration server will not allow enabling heartbeat publication on a subnet we're not on, and the `bt_mesh_subnet_del()` function will implicitly disable heartbeat publication if the subnet matches. I can see you just copied the subnet check from `cfg_srv.c` but it looks like it's unnecessary there as well.

**Comment by jhedberg** [comment]
@MariuszSkamra actually, ignore my previous comment - the check for subnet is essentially a check for whether publication is enabled or not. The subnet index will be invalid if publication is disabled. Let me see if there'd be a more intuitive way to do this check to avoid this kind of confusion of its purpose.

File: subsys/bluetooth/mesh/transport.c (hunk 3 above)
Comment (jhedberg) [reply subsys/bluetooth/mesh/transport.c]: 4.2.17.5 Heartbeat Publication Features: "The Heartbeat Publication Features state determines the features that trigger sending Heartbeat messages when changed."

4.3.2.63 Config Heartbeat Publication Status: "Bit field indicating features that trigger Heartbeat messages when changed"

So from that perspective this code looks correct.

**Comment by jhedberg** [comment]
@MariuszSkamra I've pushed updated patches. Theres one new one for fixing the checking of active heartbeat publication. Could you take a look?

**Comment by jhedberg** [comment]
@jhedberg wrote:
> The subnet index will be invalid if publication is disabled

This wasn't even true: the foundation model spec has no special requirements on touching the net key index value when disabling publication (I suppose since there's no "invalid" value in the spec for a key index, although we do have an internal one due to using 16 bits instead of 12). The spec only says the other values should be set to 0 when the destination is set to the unassigned address, which is why our implementation doesn't touch the key index at all in this case. So the correct way to check for enabled publication is indeed to check for the destination address.

**Comment by jhedberg** [comment]
> About this established flag though, isn't that just a duplication of lpn->state >= BT_MESH_LPN_ESTABLISHED, or is there some more nuance to it?

@trond-snekvik no, I think you're right. That's a work for another PR however. I wouldn't do the `>= LPN_ESTABLISHED` though, but instead explicitly check for the three "established" states - that way we don't create an implicit dependency on the ordering of the enum definition.

**Comment by jhedberg** [comment]
@trond-snekvik I take back what I just said: some of those three states are used prior to establishing friendship, so the separate established flag is needed to know what the next transition should be. E.g. we'll be in WAIT_UPDATE also for the first friend update, but the friendship isn't considered established until we get that update.

**Comment by trond-snekvik** [comment]
I see, thanks for the clarification!

**Review by MariuszSkamra — APPROVED** [review]
