### PR TITLE
Log immediate rtt crash

### LINKED ISSUE #14191: Logger corrupts itself on rescheduling
**Describe the bug**
I wanted to run a simple demo for scheduling. Created a three threads:
- infinite loop doing log and busy looping for some time (priority 0)
- infinite loop doing log then busy looping then sleep (priority -1)
- just like previous one but sleeping was slightly off so it could come while previous is executing (priority -2)

For capturing logs I am using synchronous logs (no thread) and RTT backend.

When I demo for some time I seen logs from threads and then silence. I suspected logger has some problem when one thread overtakes the other. I left two cooperative threads only and issue still occurs.

I stepped the program seen logger is caught on assertion in `out_func` in `log_output.c`.
```
assert(out_ctx->control_block->offset <= out_ctx->size);
```

These threads are cooperative but inside logger you have some mutexes. When any mutex is released rescheduling can happen. I suspect that some data structures in logger are not protected correctly and get broken when one thread is interrupted in the middle of printing.

**To Reproduce**
Check above.

**Expected behavior**
Logger should work always.

**Impact**
This is not a showstopper but not merely an annoyance. Logger is commonly used debugging tool.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
745326266d9c32ba3aa67d5af1f727059d9a88e3 (ncs zephyr) based on d9876be

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by nordic-krch**
Backend was not initialized to work in synchronous mode if LOG_IMMEDIATE was enabled. That causes use of rtt_lock which uses mutex. That lead to assert in application.

Fixes #14191.

### CODE REVIEW

File: subsys/logging/log_backend_rtt.c [hunk 1]
```diff
@@ -232,14 +231,14 @@ static void log_backend_rtt_init(void)
 	}
 
 	host_present = true;
-	panic_mode = 0;
+	sync_mode = IS_ENABLED(CONFIG_LOG_IMMEDIATE) ? true : false;
```
Comment (nordic-krch) [inline subsys/logging/log_backend_rtt.c]: mutex was used in case of LOG_IMMEDIATE. That probably could trigger rescheduling inside synchronous operation. Not sure how that was handled by kernel since interrupts where locked when this function was called.

**Review by pdunaj — APPROVED** [review]
