### PR TITLE
drivers: clock_control: nrf: Add missing flags clearing

### LINKED ISSUE #91895: clock_control_nrf: set_starting_state() returns -EPERM during BLE advertising
### Describe the bug

With BLE advertising active on nRF54L15, reading the die-temperature sensor twice in a row hangs.
`temp_nrf5_sample_fetch()` never returns on the second call because its wait semaphore is never released.
Tracing shows that `onoff_release()` returns `-EIO` (HFCLK manager in `ONOFF_STATE_ERROR`) after `set_starting_state()` in `clock_control_nrf.c` returns `-EPERM` during an HFCLK start triggered while BLE is toggling the clock.

The issue happens only when BLE is advertising. I enabled the clock control logs and added some printk statements inside onoff. It fails on `onoff_release()` and if I try to read the temperature sensor again, the thread gets stuck as it is waiting for `&data->device_sync_sem` semaphore forever.

Board: Custom board, very similar to nrf54l15dk/nrf54l15/cpuapp

### Regression

- [ ] This is a regression.

### Steps to reproduce

As I am working with a custom board, it's not easy to give the steps to reproduce. The result should be the same for `nrf54l15dk/nrf54l15/cpuapp`.
1. Use any BLE example with `nrf54l15dk/nrf54l15/cpuapp` target
2. Enable following configs :
```
CONFIG_BT_SETTINGS=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=24
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_SHELL=y
CONFIG_SENSOR_SHELL=y
CONFIG_BT_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKENDS=y
```
3. Connect via UART shell
4. Start BLE advertising:
```
bt init
bt advertise on
```
5. Run `sensor get temp@d7000`. It should give a proper response.
6. Run `sensor get temp@d7000` again. Now it will be stuck.

### Relevant log output

```shell
yucca:~$ sensor get temp@d7000
channel type=12(die_temp) index=0 shift=5 num_samples=1 value=4790800000ns (31.749999)
[00:00:03.930,496] <dbg> clock_control: clkstarted_handle: hfclk: Clock started
[00:00:04.037,056] <dbg> clock_control: clkstarted_handle: hfclk: Clock started
One off request: 0
One off release: -5
[00:00:04.874,464] <dbg> clock_control: clkstarted_handle: hfclk: Clock started
yucca:~$ sensor get temp@d7000
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: MacOs
- Toolchain: Zephyr SDK
- Zephyr Commit: 2f2eaf7b6f

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nordic-krch**
When BT dedicated API was turning off the HF clock it was not resetting status flags. When onoff API was attempting to request HF clock after that it was detecting unexpected state as status flag was indicating as if HF clock was on.

Fixes #91895

### CODE REVIEW

File: drivers/clock_control/clock_control_nrf.c [hunk 1]
```diff
@@ -442,6 +442,10 @@ void z_nrf_clock_bt_ctlr_hf_release(void)
 	hfclk_users &= ~HF_USER_BT;
 	/* Skip stopping if generic is still requesting the clock. */
 	if (!(hfclk_users & HF_USER_GENERIC)) {
+		struct nrf_clock_control_sub_data *sub_data =
+			get_sub_data(CLOCK_DEVICE, CLOCK_CONTROL_NRF_TYPE_HFCLK);
+
+		sub_data->flags = CLOCK_CONTROL_STATUS_OFF;
```
Comment (anangl) [inline drivers/clock_control/clock_control_nrf.c:451]: Maybe a comment explaining why it only needs to be done for the `bt_ctrl` special path would be helpful here (I assume that normally this happens in `set_off_state()` that is called from `stop()`, what is not the case for BT)?

Comment (nordic-krch) [reply drivers/clock_control/clock_control_nrf.c:451]: Comment added.

**Review by anangl — APPROVED** [review]

**Review by adamkondraciuk — APPROVED** [review]

**Review by nika-nordic — APPROVED** [review]
FYI @mif1-nordic
