### PR TITLE
usb: device_next: fix CDC NCM datagram pointers processing 

### LINKED ISSUE #81960: net: perf: Running on MacOS and NRF52840-DK
Note: long discussion in [Discord Subsystems USB](https://discord.com/channels/720317445772017664/1305952695995334657),  prior to filing a bug

**Describe the bug**

My ultimate goal is to use USB-CDC NCM as a networking adapter to communicate with iPadOS via UDP sockets.  I am struggling to get this stack working, so my first step is to get the net/zperf sample to compile and be recognized by MacOS as a network device.

The current state is that I am using a nRF52840-DK as a reference board and while I can compile and run zperf, I have found a few issues that in the sample with stack overflow and once these are fixed, MacOS recognizes the NCM device but does not show it as Active so it cannot be connected to.  Instead, I see:

image

and attempts to get the device manually connected (Limit IP address tracking -> Off, TCP/IP Configure IPv4 -> Manually, IP Address 192.0.2.2) have not worked.

See also:

Discussion on CDC-ECM working with MacOS (NetworkConnection Management needed)
https://github.com/zephyrproject-rtos/zephyr/issues/69209

Platforms such as macOS, iOS and iPadOS will not perform DHCP negotiation with autoconf fallback without the interface being "connected".
https://github.com/zephyrproject-rtos/zephyr/discussions/69211 @donusry-privoro

 - What target platform are you using?

MacOS Sequoia 15.1.1, Apple M1
nRF52840-DK

 - What have you tried to diagnose or workaround this issue?

Switch to USB-Next Device Stack
Simplify approach to use off the shelf sample rather than writing code from scratch
Increase log level
Long discussions on Discord with @josuah 
Review all previous discussions I could find of USB ECM/NCM and MacOS/iPadOS
Increase Stack Sizes to mitigate stack overflows in off the shelf sample code
Run under Ozone debugger
Install Arch Linux and use it to get a 'Linux eye view' of networking and usb device diagnostics
Patch usbd_cdc_ncm.c to set errno = ENOTSUP; in usbd_cdc_ncm_ctd(...) per discussion with @josuah 

 - Is this a regression?

No, AFAIK until recently MacOS/iPadOS interoperability was not possible due to ECM limitations in the USB Previous stack.

**To Reproduce**

```
west build -p -b nrf52840dk/nrf52840 samples/net/zperf -DEXTRA_CONF_FILE="overlay-usbd_next.conf" -DDTC_OVERLAY_FILE="usbd_next_ncm.overlay"
west flash
```

Modifications to prj.conf to deal with memfault stack overflows detected when running under Ozone debugger with RTT debug logging enabled.  Found stack overflows on both netmgmt and usbd threads.

```
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_NET_MGMT_EVENT_STACK_SIZE=4096
CONFIG_USBD_THREAD_STACK_SIZE=4096
```

Modifications to pro.conf to add DBG_LOG levels and switch to using RTT logging:

```
CONFIG_DEBUG=y
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_PRINTK=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_PRINTK=y

CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_RTT_MODE_DROP=y

CONFIG_USBD_LOG_LEVEL_DBG=y
CONFIG_UDC_DRIVER_LOG_LEVEL_DBG=y
CONFIG_USBD_CDC_NCM_LOG_LEVEL_DBG=y

CONFIG_NET_STATISTICS=y
CONFIG_NET_IF_LOG_LEVEL_DBG=y
CONFIG_NET_L2_ETHERNET_LOG_LEVEL_DBG=y
CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=y
CONFIG_NET_CONN_LOG_LEVEL_DBG=y
CONFIG_NET_CONTEXT_LOG_LEVEL_DBG=y
CONFIG_NET_TCP_LOG_LEVEL_DBG=y
```

**Expected behavior**

An 'out of the box' example of USB CDC ECM/NCM that interoperates with MacOS, either samples/net/zperf or samples/net/sockets/echo_server, preferably including autoconf or dhcp so that it 'just works'.

**Impact**

Weeks into trying to get Zephyr USB CDC ECM or NCM to work with no joy :-)

**Logs and console output**

```
- - - - - - - - - - - - - - - - - TARGET RESET - - - - - - - - - - - - - - - - -
[00:00:00.432,434] <dbg> cdc_ncm: usbd_cdc_ncm_preinit: CDC NCM device initialized
[00:00:00.433,776] <dbg> net_tcp: net_tcp_init: (main): Workq started. Thread ID: 0x20002bd8
[00:00:00.434,509] <dbg> net_if: net_if_init: (main): 
[00:00:00.435,089] <dbg> net_if: init_iface: (main): On iface 0x2000173c
[00:00:00.435,546] <dbg> net_ethernet: ethernet_init: (main): Initializing Ethernet L2 0x20003bb8 for iface 1 (0x2000173c)
[00:00:00.436,279] <dbg> net_if: update_operational_state: (main): iface 1 (0x2000173c), oper state DOWN admin DOWN carrier OFF dormant OFF
[00:00:00.437,011] <dbg> cdc_ncm: cdc_ncm_iface_init: CDC NCM interface initialized
[00:00:00.437,530] <dbg> net_if: net_if_ipv6_calc_reachable_time: (main): min_reachable:15000 max_reachable:45000
[00:00:00.438,476] <dbg> net_if: net_if_post_init: (main): 
[00:00:00.438,842] <dbg> net_if: net_if_up: (main): iface 1 (0x2000173c)
[00:00:00.439,300] <dbg> cdc_ncm: cdc_ncm_iface_start: Start interface 1
[00:00:00.439,758] <dbg> net_if: update_operational_state: (main): iface 1 (0x2000173c), oper state DOWN admin DOWN carrier ON dormant OFF
[00:00:00.440,551] <dbg> net_if: net_if_ipv4_maddr_add: (main): interface 1 (0x2000173c) address 224.0.0.1 added
[00:00:00.441,162] <dbg> net_if: update_operational_state: ([00:00:00.441,558] <inf> cdc_ncm: USB configuration is not enabled
[00:00:00.441,925] <dbg> cdc_ncm: cdc_ncm_send_speed_change: Cannot send speed change (-16)
[00:00:00.442,443] <dbg> cdc_ncm: ncm_send_notification: Cannot send speed change (-16)
per state DOWN admin DOWN carrier OFF dormant OFF
[00:00:00.437,011] <dbg> cdc_ncm: cdc_ncm_iface_init: CDC NCM interface initialized
[00:00:00.437,530] <dbg> net_if: net_if_ipv6_calc_reachable_time: (main): min_reachable:15000 max_reachable:45000
[00:00:00.438,476] <dbg> net_if: net_if_post_init: (main): 
[00:00:00.438,842] <dbg> net_if: net_if_up: (main): iface 1 (0x2000173c)
[00:00:00.439,300] <dbg> cdc_ncm: cdc_ncm_iface_start: Start interface 1
[00:00:00.439,758] <dbg> net_if: update_operational_state: (main): iface 1 (0x2000173c), oper state DOWN admin DOWN carrier ON dormant OFF
[00:00:00.440,551] <dbg> net_if: net_if_ipv4_maddr_add: (main): interface 1 (0x2000173c) address 224.0.0.1 added
[00:00:00.441,162] <dbg> net_if: update_operational_state: ([ain): iface 1 (0x2000173c), oper state UP admin UP carrier ON dormant OF[00:00:01.067,260] <inf> cdc_ncm: USB configuration is not enabled
[00:00:01.076,385] <dbg> cdc_ncm: cdc_ncm_send_speed_change: Cannot send speed change (-16)
[00:00:01.811,370] <inf> cdc_ncm: USB configuration is not enabled
[00:00:00.438,293] <dbg> cdc_ncm: _maddr_add: (main): [1] interface 1 (0x2000173c) address ff02::1:ff2e:8e8 added
[00:00:00.454,589] <dbg> net_if: net_if_tx: (tx_q[0]): Processing (pkt 0x20022ca8, prio 1) network packet iface 1 (0x2000173c)
[00:00:00.455,383] <dbg> net_ethernet: ethernet_fill_header: (tx_q[0]): iface 1 (0x2000173c) src 02:00:00:2E:08:E8 dst 33:33:00:00:00:16 type 0x86dd len 14
[00:00:00.456,207] <dbg> cdc_ncm: cdc_ncm_send: Configuration is not enabled or interface not ready (0 / 1)
[00:00:00.456,878] <dbg> net_if: join_mcast_solicit_node: (main): Join solicit node address ff02::1:ff2e:8e8 (ifindex 1)
[00:00:00.457,580] <dbg> net_if: net_if_ipv6_start_dad: (main): Interface 0x2000173c ll addr 02:00:00:2E:08:E8 tentative IPv6 addr fe80::ff:fe2e:8e8
[00:00:00.458,496] <dbg> net_if: net_if_tx: (tx_q[0]): Processing (pkt 0x20022ca8, prio 1) network packet iface 1 (0x2000173c)
[00:00:00.459,259] <dbg> net_ethernet: ethernet_fill_header: (tx_q[0]): iface 1 (0x2000173c) src 02:00:00:2E:08:E8 dst 33:33:FF:2E:08:E8 type 0x86dd len 14
[00:00:00.460,083] <dbg> cdc_ncm: cdc_ncm_send: Configuration is not enabled or interface not ready (0 / 1)
[00:00:00.460,723] <dbg> net_if: net_if_start_rs: (main): Starting ND/RS for iface 0x2000173c
[00:00:00.461,425] <dbg> net_if: net_if_tx: (tx_q[0]): Processing (pkt 0x20022ca8, prio 1) network packet iface 1 (0x2000173c)
[00:00:00.462,219] <dbg> net_ethernet: ethernet_fill_header: (tx_q[0]): iface 1 (0x2000173c) src 02:00:00:2E:08:E8 dst 33:33:00:00:00:02 type 0x86dd len 14
[00:00:00.463,073] <dbg> cdc_ncm: cdc_ncm_send: Configuration is not enabled or interface not ready (0 / 1)
[00:00:00.463,897] <dbg> net_sock_svc: socket_service_thread: (): Service WEST_TOPDIR/zephyr/subsys/net/lib/zperf/zperf_tcp_receiver.c:44 has 6 pollable sockets
[00:00:00.464,691] <dbg> net_sock_svc: socket_service_thread: (): Service WEST_TOPDIR/zephyr/subsys/net/lib/zperf/zperf_udp_receiver.c:51 has 2 pollable sockets
[00:00:00.465,423] <dbg> net_sock_svc: socket_service_thread: (): Monitoring 8 socket entries
*** Booting Zephyr OS build v4.0.0-827-g305ceba9204d ***
[00:00:02.250,640] <dbg> net_if: dad_timeout: (sysworkq): DAD succeeded for 2001:db8::1 at interface 1
[00:00:02.605,987] <inf> cdc_ncm: USB configuration is not enabled
[00:00:02.615,142] <dbg> cdc_ncm: cdc_ncm_send_speed_change: Cannot send speed change (-16)
[00:00:02.637,725] <dbg> net_if: dad_timeout: (sysworkq): DAD succeeded for 2001:db8::1 at interface 1
[00:00:02.650,207] <inf> net_config: IPv6 address: 2001:db8::1
[00:00:02.711,029] <dbg> cdc_ncm: usbd_cdc_ncm_enable: Configuration enabled
[00:00:02.104,187] <inf> cdc_ncm: USB configuration is not enabled
[00:00:02.104,583] <dbg> cdc_ncm: cdc_ncm_send_speed_change: Cannot send speed change (-16)
[00:00:02.105,072] <dbg> cdc_ncm: ncm_send_notification: Cannot send speed change (-16)
[00:00:02.105,651] <dbg> net_if: dad_timeout: (sysworkq): DAD succeeded for fe80::ff:fe1d:2706 at interface 1
[00:00:02.106,292] <dbg> net_if: rs_timeout: (sysworkq): RS no respond iface 0x2000173c count 1
[00:00:02.106,872] <dbg> net_if: net_if_start_rs: (sysworkq): Starting ND/RS for iface 0x2000173c
[00:00:02.107,604] <dbg> net_if: net_if_tx: (tx_q[0]): Processing (pkt 0x20024568, prio 1) network packet iface 1 (0x2000173c)
[00:00:02.108,398] <dbg> net_ethernet: ethernet_fill_header: (tx_q[0]): iface 1 (0x2000173c) src 02:00:00:1D:27:06 dst 33:33:00:00:00:02 type 0x86dd len 14
[00:00:02.109,252] <dbg> cdc_ncm: cdc_ncm_send: Configuration is not enabled or interface not ready (0 / 1)
[00:00:02.109,985] <dbg> cdc_ncm: usbd_cdc_ncm_init: CDC NCM class initialized
[00:00:02.110,534] <inf> net_config: Initializing network
[00:00:02.110,931] <dbg> net_if: net_if_ipv4_addr_add: (main): [0] interface 1 (0x2000173c) address 192.0.2.1 type MANUAL added
[00:00:02.111,633] <inf> net_config: IPv4 address: 192.0.2.1
[00:00:02.112,121] <dbg> net_if: net_if_ipv6_addr_add: (main): [1] interface 1 (0x2000173c) address 2001:db8::1 type MANUAL added
[00:00:02.112,884] <dbg> net_if: net_if_ipv6_maddr_add: (main): [2] interface 1 (0x2000173c) address ff02::1:ff00:1 added
[00:00:02.113,800] <dbg> net_if: net_if_tx: (tx_q[0]): Processing (pkt 0x20024568, prio 1) network packet iface 1 (0x2000173c)
[00:00:02.114,593] <dbg> net_ethernet: ethernet_fill_header: (tx_q[0]): iface 1 (0x2000173c) src 02:00:00:1D:27:06 dst 33:33:00:00:00:16 type 0x86dd len 14
[00:00:02.115,447] <dbg> cdc_ncm: cdc_ncm_send: Configuration is not enabled or interface not ready (0 / 1)
[00:00:02.116,119] <dbg> net_if: join_mcast_solicit_node: (main): Join solicit node address ff02::1:ff00:1 (ifindex 1)
[00:00:02.116,790] <dbg> net_if: net_if_ipv6_start_dad: (main): Interface 0x2000173c ll addr 02:00:00:1D:27:06 tentative IPv6 addr 2001:db8::1
[00:00:02.117,675] <dbg> net_if: net_if_tx: (tx_q[0]): Processing (pkt 0x20024568, prio 1) network packet iface 1 (0x2000173c)
[00:00:02.118,408] <dbg> net_ethernet: ethernet_fill_header: (tx_q[0]): iface 1 (0x2000173c) src 02:00:00:1D:27:06 dst 33:33:FF:00:00:01 type 0x86dd len 14
[00:00:02.119,232] <dbg> cdc_ncm: cdc_ncm_send: Configuration is not enabled or interface not ready (0 / 1)
[00:00:02.205,657] <inf> cdc_ncm: USB configuration is not enabled
[00:00:02.214,782] <dbg> cdc_ncm: cdc_ncm_send_speed_change: Cannot send speed change (-16)
[00:00:02.226,196] <dbg> cdc_ncm: ncm_send_notification: Cannot send speed change (-16)
[00:00:02.313,385] <dbg> cdc_ncm: usbd_cdc_ncm_enable: Configuration enabled
[00:00:02.337,402] <dbg> cdc_ncm: ncm_send_notification: Speed change sent
[00:00:02.347,473] <dbg> cdc_ncm: usbd_cdc_ncm_cth: 1: 128 28 0 0
[00:00:02.356,567] <dbg> cdc_ncm: usbd_cdc_ncm_cth: GET_NTB_PARAMETERS
[00:00:02.429,443] <dbg> cdc_ncm: usbd_cdc_ncm_request: finished 81 len 16
[00:00:02.447,387] <dbg> cdc_ncm: ncm_send_notification: Connected status sent
[00:00:02.461,425] <dbg> cdc_ncm: usbd_cdc_ncm_request: finished 81 len 8
[00:00:02.707,519] <inf> cdc_ncm: New configuration, interface 1 alternate 1
[00:00:03.107,666] <dbg> net_if: rs_timeout: (sysworkq): RS no respond iface 0x2000173c count 2
[00:00:03.146,514] <dbg> net_ethernet: ethernet_fill_header: (tx_q[0]): iface 1 (0x2000173c) src 02:00:00:1D:27:06 dst 33:33:00:00:00:02 type 0x86dd len 14
[00:00:04.131,713] <dbg> net_if: rs_timeout: (sysworkq): RS no respond iface 0x2000173c count 3
```

**Environment (please complete the following information):**

 - OS: MacOS Sequoia 15.1.1, Apple M1
 - Toolchain: Zephyr SDK,Zephyr OS build v4.0.0-827-g305ceba9204d
 - Commit SHA: 305ceba9204d9a7ee4bae0a6103ef4cbd9a1c54e

### PR DESCRIPTION
**Pull request by jfischer-no**
The implementation should not assume that NDP is placed immediately
after NTH. According to the specification (revision 1.0), NDP can be
anywhere in the transfer buffer. There is also always a "terminating
zero datagram pointer entry", which we should also use to terminate the
datagram processing loop.

Fixes: #81960

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]

File: subsys/usb/device_next/class/usbd_cdc_ncm.c [hunk 1]
```diff
@@ -518,14 +519,15 @@ static int cdc_ncm_acl_out_cb(struct usbd_class_data *const c_data,
...
+		LOG_ERR("Bulk OUT transfer error or zero length");
 		net_buf_unref(buf);
 		atomic_clear_bit(&data->state, CDC_NCM_OUT_ENGAGED);
 		return 0;
 	}
 
 	ret = check_frame(data, buf);
 	if (ret < 0) {
-		LOG_DBG("check frame failed (%d)", ret);
+		LOG_ERR("check frame failed (%d)", ret);
```
Comment (tmon-nordic) [inline subsys/usb/device_next/class/usbd_cdc_ncm.c:530]: What's the real reason behind this? Is this so unexpected condition? Deliberately malformed packets are really common on networks.

I would drop this commit, otherwise the rest seems fine.

Comment (jfischer-no) [reply subsys/usb/device_next/class/usbd_cdc_ncm.c:530]: It would not be a mailformed network packet, but a mailformed NTB, so this should be logged as error. We do not check Ethernet packets and do not care about them at all.

File: subsys/usb/device_next/class/usbd_cdc_ncm.c [hunk 2]
```diff
@@ -33,7 +33,7 @@ LOG_MODULE_REGISTER(cdc_ncm, CONFIG_USBD_CDC_NCM_LOG_LEVEL);
 
 enum {
 	CDC_NCM_IFACE_UP,
-	CDC_NCM_CLASS_ENABLED,
+	CDC_NCM_DATA_IFACE_ENABLED,
```
Comment (tmon-nordic) [inline subsys/usb/device_next/class/usbd_cdc_ncm.c:36]: In "usb: device_next: do not stop when OUT transfer has zero length" commit message you cannot really refer to the commit by its SHA, because the SHA will change when the patches enter mainline. The solution would be to split that away from this PR and update the commit message after the underlying commit is in main.

Comment (jfischer-no) [reply subsys/usb/device_next/class/usbd_cdc_ncm.c:36]: Yes, I screwed up again. Changed commit message.

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
