### PR TITLE
Bluetooth: Host: Fix type mismatch in bt_gatt_cancel

### LINKED ISSUE #41268: `bt_gatt_cancel` type mismatch
Current implementation follows. Note comment about type mismatch (added here).
```c
void bt_gatt_cancel(struct bt_conn *conn, void *params)
{
	bt_att_req_cancel(conn, params);
//      ------------------------^
//      Type mismatch
//      `params` is `bt_gatt_.._params *`
//       but `bt_att_req_cancel` expects `bt_att_req *`
}
```

**Impact**
`bt_gatt_cancel` is completely non-functioning and possibly invokes undefined behavior.

**Fixes**
Two alternative PR's are provided. One removes `bt_gatt_cancel`. And one fixes it.

I believe `bt_gatt_cancel` has no value for our users and should be removed. It has been broken for some time now and no one complained, so it can be considered to have had a deprecation period.

### PR DESCRIPTION
**Pull request by alwa-nordic**

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -4650,7 +4650,10 @@ int bt_gatt_unsubscribe(struct bt_conn *conn,
 
 void bt_gatt_cancel(struct bt_conn *conn, void *params)
 {
-	bt_att_req_cancel(conn, params);
+	struct bt_att_req *req;
```
Comment (joerchan) [inline subsys/bluetooth/host/gatt.c:4653]: I think we should explain how canceling works when having multiple requests with the same parameters.
Which order, how many submits.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -4650,7 +4650,10 @@ int bt_gatt_unsubscribe(struct bt_conn *conn,
...
+
+	req = bt_att_find_req_by_user_data(params);
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:4655]: There may be a race condition here. E.g. Applicaiton thread is preempted here by BT TX thread. BT TX thread sends the `req`. High priority stuff happens. BT RX thread now runs and gets the response. BT RX calls callback in application which calls `bt_gatt_write` and allocates the same `req`. Control goes back to application thread and `req` is now bad.

Maybe the "High priority stuff happens." is not something that practically happens. But this code is clearly fragile and I would not be surprised if a more likely race is found. Anyone have thoughts what on synchronization to use here?

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:4653]: We can specify that the cancel will stop one of the requests (or none is all are sent). Which request is canceled is moot since they are indistinguishable to both the application and the remote peer.

We can be conservative and forbid multiple requests with the same params object. I think this is the simpler contract to explain.

File: subsys/bluetooth/host/gatt.c (hunk 2 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:4655]: k_sched_lock/unlock would be acceptable here. As long as there is nothing that unschedules the thread between.
From what I can tell there is nothing that would block in bt_att_req_free.

File: subsys/bluetooth/host/att.c [hunk 3]
```diff
@@ -3145,3 +3145,20 @@ void bt_att_req_cancel(struct bt_conn *conn, struct bt_att_req *req)
...
+static struct bt_att_req *bt_att_find_req_by_att_user_data(struct bt_att *att, void *user_data)
+{
+	struct bt_att_req *req;
+
+	SYS_SLIST_FOR_EACH_CONTAINER(&att->reqs, req, node) {
+		if (req->user_data == user_data) {
+			return req;
+		}
+	}
+	return NULL;
```
Comment (Thalley) [inline subsys/bluetooth/host/att.c:3158]:
```suggestion
	}
	
	return NULL;
```

File: subsys/bluetooth/host/att.c [hunk 4]
```diff
@@ -3145,3 +3145,20 @@ void bt_att_req_cancel(struct bt_conn *conn, struct bt_att_req *req)
 
 	bt_att_req_free(req);
 }
+
+static struct bt_att_req *bt_att_find_req_by_att_user_data(struct bt_att *att, void *user_data)
```
Comment (Thalley) [inline subsys/bluetooth/host/att.c:3149]:
```suggestion
static struct bt_att_req *bt_att_find_req_by_att_user_data(struct bt_att *att, const void *user_data)
```

File: subsys/bluetooth/host/att.c [hunk 5]
```diff
@@ -3145,3 +3145,20 @@ void bt_att_req_cancel(struct bt_conn *conn, struct bt_att_req *req)
...
+
+	SYS_SLIST_FOR_EACH_CONTAINER(&att->reqs, req, node) {
+		if (req->user_data == user_data) {
+			return req;
+		}
+	}
+	return NULL;
+}
+
+struct bt_att_req *bt_att_find_req_by_user_data(struct bt_conn *conn, void *user_data)
```
Comment (Thalley) [inline subsys/bluetooth/host/att.c:3161]:
```suggestion
struct bt_att_req *bt_att_find_req_by_user_data(struct bt_conn *conn, const void *user_data)
```

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/host/gatt.c:4653]: Alternatively we can cancel all requests from the parameters if there are multiple.

**Review by Thalley — CHANGES_REQUESTED** [review]
Minor code style comments

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:4653]: > The list is ordered

Good point. The order in relation to other requests matters. `att->reqs` is in sending order. So the request issued first will be canceled. Do we have a real preference for one behavior over another?

What is the use case for this method? I'm wondering if anybody uses this, since it was broken and nobody noticed. Maybe we could deprecate this?

Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:4653]: I don't have a preference no.
Deprecating would be an option, it is a while since this was broken, like 2.2/2.3 maybe.

Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:4653]: I found a new problem with `bt_gatt_cancel`. It does not return any status. So the application does not know if it can free/reuse `params`. I can add a call to `req->func` with an error code. But there is no appropriate error code for "canceled", so it's awkward.

I think `att_handle_rsp` has the same problem. If the ongoing is canceled (`chan->req == &cancel`), `req->func` is never called, so the application is never told to recycle `user_data`/`params`.

Unless I'm confused about the above, I believe it's best to deprecate the canceling feature. At least until we have a concrete use case. @joerchan Could you help me look at whether `bt_gatt_unsubscribe` really needs to call `bt_gatt_cancel`? I have a feeling the design would be cleaner if we just treat unsubscribe as a request and sequence it like any other.

Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:4653]: You mean you wish to just pend the write to unsubscribe, while the write to subscribe is in progress?
I don't see a problem with that solution. `bt_gatt_subscribe` remove it from the list already, so you'll have to see if that is OK, and how `gatt_write_ccc_rsp` handles that case.

And what would happen if you try to subscribe while unsubscribe is in progress maybe?

File: subsys/bluetooth/host/gatt.c [hunk 6]
```diff
@@ -4650,7 +4650,23 @@ int bt_gatt_unsubscribe(struct bt_conn *conn,
...
+	if (req) {
+		func = req->func;
+		bt_att_req_cancel(conn, req);
+	}
+
+	k_sched_unlock();
+
+	if (req) {
+		func(conn, BT_ATT_ERR_UNLIKELY, NULL, 0, params);
+	}
```
Comment (Thalley) [inline subsys/bluetooth/host/gatt.c:4669]: Minor comment: It feels unnecessary to store `func` in a variable instead of doing
```suggestion
	struct bt_att_req *req;

	k_sched_lock();

	req = bt_att_find_req_by_user_data(conn, params);
	if (req) {
		bt_att_req_cancel(conn, req);
	}

	k_sched_unlock();

	if (req) {
		req->func(conn, BT_ATT_ERR_UNLIKELY, NULL, 0, params);
	}
```

**Review by Thalley — APPROVED** [review]
LGTM with one minor comment

File: subsys/bluetooth/host/gatt.c (hunk 6 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:4669]: `func` must be saved. `bt_att_req_cancel` calls `bt_att_req_free`. (A bit surprising, I agree. It's not what the function name says.)

It's a common pattern in this module that we free the `req` before calling into callbacks. This because the callback might result in the application performing a new request, which will allocate a `req` again.

Comment (Thalley) [reply subsys/bluetooth/host/gatt.c:4669]: By `free` I suppose you mean reset, right? 

Otherwise we shouldn't do a check for `if (req)` { func(...);}`. 

If we store the func, then perhaps it should be changed to 
```suggestion
	struct bt_att_req *req;
	bt_att_func_t func = NULL;
	
	k_sched_lock();

	req = bt_att_find_req_by_user_data(conn, params);
	if (req) {
		func = req->func;
		bt_att_req_cancel(conn, req);
	}

	k_sched_unlock();

	if (func) {
		func(conn, BT_ATT_ERR_UNLIKELY, NULL, 0, params);
	}
```

Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:4669]: I made the two ifs have the same predicate for readability. My intention is the visual appearance that it is the same conditional, interleaved by a unconditional call to `k_sched_unlock`.

File: subsys/bluetooth/host/gatt.c [hunk 7]
```diff
@@ -4651,20 +4651,19 @@ int bt_gatt_unsubscribe(struct bt_conn *conn,
 void bt_gatt_cancel(struct bt_conn *conn, void *params)
 {
 	struct bt_att_req *req;
-	bt_att_func_t func;
-
+	bt_att_func_t func = NULL;
+
```
Comment (Thalley) [inline subsys/bluetooth/host/gatt.c:4655]: Looks like you accidentally added a tab here :) 

Suggest to set your editor to remove all trailing whitespace.

**Review by Thalley — CHANGES_REQUESTED** [review]

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
