### PR TITLE
Bluetooth: Fix buffer allocation when under syswq

### LINKED ISSUE #18705: SMP fails to allocate buffer and pairing times out
If you replace the `k_sleep(MSEC_PER_SEC);` with `k_sleep(10)` in `samples/bluetooth/peripheral` and then do the following:

1. Connect from a mobile app
2. Enable Battery Level notifications
3. Initiate pairing by trying to read any of the 128-bit UUID characteristics in the custom service

Then the pairing will not complete because SMP is unable to allocate a packet.
The error message printed will be:

```
[00:01:35.083,007] <err> bt_smp: Unable to allocate Ident Info buffer
```
or
```
[00:00:29.879,852] <err> bt_att: Unable to allocate buffer for op 0x0b
[00:00:29.879,852] <err> bt_att: Unable to allocate buffer for op 0x01
```

### PR DESCRIPTION
**Pull request by Vudentz**
With the changes to make move L2CAP channels to be processed under syswq and the addition of checks not to block with K_FOREVER it is now possible that bt_conn_create_pdu would return NULL which has to handled by the caller. In addition to that processing under syswq would not pend waiting for a buffer when using K_FOREVER so this introduces alternative APIs to use so protocols such as SMP can pass its own timeout.

Fixes #18705

### CODE REVIEW

**Review by carlescufi — CHANGES_REQUESTED** [review]
This doesn't seem to fix it, I still get a disconnection from the phone instead of a successful pairing procedure

**Comment by joerchan** [comment]
Should you add fixes: https://github.com/zephyrproject-rtos/zephyr/pull/18704 ?

**Comment by Vudentz** [comment]
> Should you add fixes: #18704 ?

That is not an issue though it is the PR itself, or did you mean to past something else?

**Comment by carlescufi** [comment]
> > Should you add fixes: #18704 ?
> 
> That is not an issue though it is the PR itself, or did you mean to past something else?

Edited it myself with the correct issue number.

**Review by carlescufi — APPROVED** [review]
Fixes the issue, I can notify at full speed and bond now

File: subsys/bluetooth/host/att.c [hunk 1]
```diff
@@ -1942,6 +1942,28 @@ static att_type_t att_op_get_type(u8_t op)
 		return ATT_COMMAND;
 	}
 
+#if !defined(CONFIG_BT_GATT_CLIENT)
```
Comment (joerchan) [inline subsys/bluetooth/host/att.c]: Complete the list and just get rid of the rest of the function?

**Comment by ioannisg** [comment]
We need a bit of more approvals, here.

**Review by joerchan — COMMENTED** [review]
There are a few places in smp.c where the return value when we don't buffers are not checked.
`smp_send_pairing_random`
`sc_smp_send_dhkey_check`
`smp_send_pairing_confirm`

`bt_smp_distribute_keys` This one returns many times, in buffer error failure, in this case there is no error returned. 

An error returned will result in an SMP Error packet being sent, with reason Unspecified.
Is it so that failing to allocate SMP buffer will always be either allocated, or wait until SMP timeout.
So then all of these errors should be handled, but they are not all handled in the same way?

File: subsys/bluetooth/host/att.c (hunk 1 above)
Comment (Vudentz) [reply subsys/bluetooth/host/att.c]: Yep, Ive been thinking about that, though that means one has to remember to add new opcodes there as well but I guess it is faster to use the switch statement as well.

File: subsys/bluetooth/host/l2cap.c [hunk 2]
```diff
@@ -415,6 +423,9 @@ static int l2cap_le_conn_req(struct bt_l2cap_le_chan *ch)
 
 	buf = l2cap_create_le_sig_pdu(NULL, BT_L2CAP_LE_CONN_REQ,
 				      ch->chan.ident, sizeof(*req));
+	if (!buf) {
+		return -ENOMEM;
```
[the remark this answers is not in the document]
Comment (Vudentz) [reply subsys/bluetooth/host/l2cap.c]: I usually use ENOMEM for that, not sure if changing would make much difference to be honest.

**Comment by Vudentz** [comment]
All the calls to smp_creat_pdu do check for NULL return:

smp_send_pairing_random:
	rsp_buf = smp_create_pdu(conn, BT_SMP_CMD_PAIRING_RANDOM, sizeof(*req));
	if (!rsp_buf) {
		return BT_SMP_ERR_UNSPECIFIED;
	}

sc_smp_send_dhkey_check:
	buf = smp_create_pdu(smp->chan.chan.conn, BT_SMP_DHKEY_CHECK,
			     sizeof(*req));
	if (!buf) {
		return BT_SMP_ERR_UNSPECIFIED;
	}

smp_send_pairing_confirm:
	buf = smp_create_pdu(conn, BT_SMP_CMD_PAIRING_CONFIRM, sizeof(*req));
	if (!buf) {
		return BT_SMP_ERR_UNSPECIFIED;
	}

Not sure what you are refering to @joerchan, we may have to return a different error if we can't get buffer allocated in time but that is a different matter.

**Comment by joerchan** [comment]
@vudentz I mean that the return code of smp_send_pairing_confirm, and the other ones I mentioned, is ignored

File: subsys/bluetooth/host/l2cap.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/l2cap.c]: Right, I see that this module use ENOMEM consistently. So ignore that comment.

File: subsys/bluetooth/host/att.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/att.c]: I think the switch statement is better, it's more robust to ifdefs in the handlers array.

File: subsys/bluetooth/host/smp.c [hunk 3]
```diff
@@ -1949,7 +1954,7 @@ static void bt_smp_distribute_keys(struct bt_smp *smp)
 			keys->local_csrk.cnt = 0U;
 		}
 
-		smp_send(smp, buf, sign_info_sent, NULL);
+		smp_send(smp, buf, smp_sign_info_sent, NULL);
```
Comment (joerchan) [inline subsys/bluetooth/host/smp.c]: Need same change in `smp_br_distribute_keys`

File: subsys/bluetooth/host/smp.c [hunk 4]
```diff
@@ -3251,7 +3272,7 @@ static u8_t smp_pairing_random(struct bt_smp *smp, struct net_buf *buf)
 
 	atomic_set_bit(&smp->allowed_cmds, BT_SMP_DHKEY_CHECK);
 	atomic_set_bit(smp->flags, SMP_FLAG_DHCHECK_WAIT);
-	smp_send_pairing_random(smp);
+	return smp_send_pairing_random(smp);
 #endif /* CONFIG_BT_PERIPHERAL */
 
 	return 0;
```
Comment (joerchan) [inline subsys/bluetooth/host/smp.c]: Dead return `0` here if CONFIG_BT_PERIPHERAL is defined, Likely build warning/failure here.
It would be a failure if you end up on this return with no peripheral defined. 
```
#else
return BT_SMP_ERR_UNPSECIFIED
#endif /*CONFIG_BT_PERIPHERAL */
```

Comment (Vudentz) [reply subsys/bluetooth/host/smp.c]: I guess we should be using BT_SMP_ERR_PAIRING_NOTSUPP since we cannot pair as peripheral.

Comment (joerchan) [reply subsys/bluetooth/host/smp.c]: Sounds good.

**Review by joerchan — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by carlescufi** [comment]
@Vudentz you have a `!fixup` commit in there
