### PR TITLE
ARCMWDT: Fix macroses for section definition

### LINKED ISSUE #74421: ARCMWDT: linker generates errors while building C++ tests
**Describe the bug**
Some C++ tests are not successful for Synopsys RMX platform with arcmwdt compiler.
Linker generates error: ``` symbol not found: ONLY_IF_RO ```.

 - What target platform are you using?
    nsim_arc_v/rmx100 with arcmwdt compiler

**To Reproduce**
1. west build -p -b nsim_arc_v/rmx100 tests/lib/cpp/cxx/ -T cpp.main.cpp14
2. See error

**Expected behavior**
No build error for pointed test

**Logs and console output**
``` 
lldac: error: /home/user/sandbox/zephyrproject/zephyr/build/zephyr/linker_zephyr_pre0.cmd:441: symbol not found: ONLY_IF_RO
lldac: error: /home/user/sandbox/zephyrproject/zephyr/build/zephyr/linker_zephyr_pre0.cmd:596: symbol not found: ONLY_IF_RW
``` 

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: arcmwdt
 - origin/main

### PR DESCRIPTION
**Pull request by kokas-a**
With adding support for ARC-V architecture some additional changes in section definitions are required.

This PR fixes https://github.com/zephyrproject-rtos/zephyr/issues/74421

### CODE REVIEW

**Review by nashif — APPROVED** [review]

File: include/zephyr/linker/linker-tool-mwdt.h [hunk 1]
```diff
@@ -90,9 +89,10 @@
  */
 #ifdef CONFIG_XIP
 #define SECTION_DATA_PROLOGUE(name, options, align) \
-	name options ALIGN(8) align :
+	name options ALIGN(8) : align
```
Comment (evgeniy-paltsev) [inline include/zephyr/linker/linker-tool-mwdt.h:92]: So this new syntax is suitable for both ARC and RISC-V isa targets?

Comment (kokas-a) [reply include/zephyr/linker/linker-tool-mwdt.h:92]: yes

Comment (evgeniy-paltsev) [reply include/zephyr/linker/linker-tool-mwdt.h:92]: Ok, can confirm - it works even for old MWDT versions.

**Review by evgeniy-paltsev — APPROVED** [review]

**Review by abrodkin — APPROVED** [review]
