### PR TITLE
spi: spi_nrfx_spim: limit clock frequency by inst

### LINKED ISSUE #34402: spi: spi_nrfx_spim: wrong clock frequency selected
**Describe the bug**

When using a chipset that has SPI modules with different maximum clock speeds, the clock selection is made based on the module with the highest clock, not the module being used.

As an example, the nRF52840 supports 32MHz SPI only on SPI3, while SPI0, SPI1 and SPI2 are limited to 8MHz.
If a peripheral with a maximum clock rate of 16MHz is placed on SPI0, `get_nrf_spim_frequency` will return `NRF_SPIM_FREQ_16M`, not the `NRF_SPIM_FREQ_8M` which is actually the highest supported frequency.

This results in our hypothetic peripheral running at some undefined clock speed.

The cause of this is that `get_nrf_spim_frequency` uses `SPIM_FREQUENCY_FREQUENCY_M32` (which is a global SOC define) to determine the maximum clock frequency, not the SPI instance itself.

**Expected behavior**

The SPI module should select the highest valid clock speed for the hardware being used. It should not be possible for the clock speed to be some undefined value.

**Impact**
This is an annoyance, as the board devicetree must specify the maximum SPI module clock speed on each peripheral, instead of the actual clock speed that the peripherals support.

**Environment (please complete the following information):**
 - Zephyr v2.5

### PR DESCRIPTION
**Pull request by JordanYates**
Limit the maximum SPI frequency to that supported by the instance
hardware. This stops peripherals supporting >8MHz on slow instances
from wrapping around on the clock frequency for undefined behaviour.

Fixes #34402

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

### CODE REVIEW

File: drivers/spi/spi_nrfx_spim.c [hunk 1]
```diff
@@ -143,12 +149,13 @@ static int configure(const struct device *dev,
 
 	ctx->config = spi_cfg;
 	spi_context_cs_configure(ctx);
+	freq = get_nrf_spim_frequency(get_dev_config(dev)->max_freq,
+				      spi_cfg->frequency);
```
Comment (jfischer-no) [inline drivers/spi/spi_nrfx_spim.c:153]: Why not
```c
freq = get_nrf_spim_frequency(MIN(spi_cfg->frequency,
                                  get_dev_config(dev)->max_freq));
```
?

Comment (JordanYates) [reply drivers/spi/spi_nrfx_spim.c:153]: I preferred to keep all the selection logic inside `get_nrf_spim_frequency`, instead of splitting it across two locations.

Comment (jfischer-no) [reply drivers/spi/spi_nrfx_spim.c:153]: I does not select anything, just limits input value. I do not see any reason here to change get_nrf_spim_frequency().

File: drivers/spi/spi_nrfx_spim.c [hunk 2]
```diff
@@ -144,11 +146,14 @@ static int configure(const struct device *dev,
 	ctx->config = spi_cfg;
 	spi_context_cs_configure(ctx);
 
+	/* Limit the frequency to that supported by the SPIM instance */
+	freq = get_nrf_spim_frequency(MIN(spi_cfg->frequency,
+				      get_dev_config(dev)->max_freq));
```
Comment (anangl) [inline drivers/spi/spi_nrfx_spim.c:151]: This indentation is a bit misleading. It should be:
```
	freq = get_nrf_spim_frequency(MIN(spi_cfg->frequency,
					  get_dev_config(dev)->max_freq));
```

**Review by anangl — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]
