### PR TITLE
Bluetooth: CTS: Fix issue with writing without subscription

### LINKED ISSUE #93551: BLE CTS service returns ERR_UNLIKELY after a write if no client has subscribed to notifications
### Describe the bug

Writing a new time to the CTS service returns an ERR_UNLIKELY (0xE) when no client subscribed to notifications.
That is because `write_ct()` calls `bt_cts_send_notification()` which returns a non zero error code without subscriber.
```
	err = bt_cts_send_notification(BT_CTS_UPDATE_REASON_MANUAL);
	if (err) {
		return BT_GATT_ERR(BT_ATT_ERR_UNLIKELY);
	}
```
The time is set as expected and a read does return the expected time.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Do **not** subscribe to the Current Time Service notifications.
2. Write new time to the Current Time Service, e.g. 0xE90707150E2C00010003 for 21 Jul 2025 14:44:00 (with nrf connect app or any other means)
3. Check logs containing `Error 14 (0xe): GATT ERR UNLIKELY`

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Thalley**
The write_ct function calls bt_cts_send_notification and if bt_cts_send_notification fails to send a notification (e.g. if there are no clients subscribed), it would return an error, and thus send a ATT error response to the client, even if the value was actually written.

This commit changes the behavior so that the notification does not affect the return value (as it is not directly linked to the write itself), but rather just logs it if it fails to send the notification.

The notification can failed to be send for 2 main reasons: 1) The application returns an error on fill_current_cts_time 2) bt_gatt_notify fails to notify due to missing buffers

The first we cannot do much about. For the latter we can either just live with the missing notification, or implement a retry if we run out of buffers. For this simple fix the former was chosen, but can be revisited if it turns out to be a significant problem.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/93551

### CODE REVIEW

File: subsys/bluetooth/services/cts.c [hunk 1]
```diff
@@ -152,8 +153,8 @@ static ssize_t write_ct(struct bt_conn *conn, const struct bt_gatt_attr *attr, c
 	}
 
 	err = bt_cts_send_notification(BT_CTS_UPDATE_REASON_MANUAL);
-	if (err) {
-		return BT_GATT_ERR(BT_ATT_ERR_UNLIKELY);
+	if (err != 0 && err != -ENOTCONN) {
+		LOG_DBG("New value was not notified to clients: %d", err);
```
Comment (cvinayak) [inline subsys/bluetooth/services/cts.c]:
```suggestion
		LOG_WRN("New value was not notified to clients: %d", err);
```

**Review by cvinayak — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]
