### PR TITLE
kernel: fix error propagation for device deferred initialization

### LINKED ISSUE #91095: device_init doesn't pass on negative error codes from drivers
### Describe the bug

Context: I have a custom device driver which is configured with the `zephyr,deferred-init` property in the devicetree.

I noticed when checking the return code of `device_init()` that although the driver's initialisation was failing and should be returning `-EIO`, this value was not being passed on to my application.

Looking through the codebase, `device_init()` ultimately calls `do_device_init()`, which converts negative error codes returned by the driver into positive codes.

Is this behaviour correct? It does seem contrary to the documentation.

This function also sets the initialised state to `true` irrespective of the return code from the driver.

```
static int do_device_init(const struct device *dev)
{
	int rc = 0;

	if (dev->ops.init != NULL) {
		rc = dev->ops.init(dev);
		/* Mark device initialized. If initialization
		 * failed, record the error condition.
		 */
		if (rc != 0) {
			if (rc < 0) {
				rc = -rc;
			}
			if (rc > UINT8_MAX) {
				rc = UINT8_MAX;
			}
			dev->state->init_res = rc;
		}
	}

	dev->state->initialized = true;

	if (rc == 0) {
		/* Run automatic device runtime enablement */
		(void)pm_device_runtime_auto_enable(dev);
	}

	return rc;
}
```

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ljd42**
This fix propagates the failure code returned from the device initialization function to the application when deferred initialization is used. Previously, `device_init()` mistakenly returned `errno` instead of `-errno`.

A test has been added to test.kernel.device to verify the changes  (fail before the fix, pass after).

Fix: #91095

### CODE REVIEW

**Comment by ljd42** [comment]
@andyross or @peter-mitsis: A relative straightforward PR, but no urgency. Thanks!

File: kernel/init.c [hunk 1]
```diff
@@ -311,24 +311,19 @@ static int do_device_init(const struct device *dev)
 {
 	int rc = 0;
 
+	/* device initialization has been invoked */
+	dev->state->initialized = true;
+
```
Comment (cfriedt) [inline kernel/init.c]: Can we continue to mark the device as initialized _after_ it has been initialized? I.e. keep this after the init call?

File: tests/kernel/device/src/main.c [hunk 2]
```diff
@@ -415,6 +422,38 @@ ZTEST(device, test_deferred_init)
...
+ * @ingroup kernel_device_tests
+ */
+ZTEST(device, test_deferred_init_failure)
+{
+	int ret;
+	const struct device *dev = FAKEDEFERDRIVER2;
+
+	zassert_false(device_is_ready(dev));
+	ret = device_init(dev);
+	zassert_true(ret == -EIO);
```
Comment (cfriedt) [inline tests/kernel/device/src/main.c]:
```suggestion
	zassert_equal(ret, -EIO);
```

File: tests/kernel/device/src/main.c [hunk 3]
```diff
@@ -415,6 +422,38 @@ ZTEST(device, test_deferred_init)
...
+	zassert_false(device_is_ready(dev));
+	zassert_true(dev->state->init_res == EIO);
```
Comment (cfriedt) [inline tests/kernel/device/src/main.c]:
```suggestion
	zassert_equal(dev->state->init_res, EIO);
```

File: tests/kernel/device/src/main.c [hunk 4]
```diff
@@ -415,6 +422,38 @@ ZTEST(device, test_deferred_init)
...
+
+	ret = device_init(dev);
+	zassert_true(ret == -EALREADY);
+	zassert_true(dev->state->init_res == EIO);
```
Comment (cfriedt) [inline tests/kernel/device/src/main.c]:
```suggestion
	zassert_equal(ret, -EALREADY);
	zassert_equal(dev->state->init_res, EIO);
```

File: kernel/init.c [hunk 5]
```diff
@@ -311,24 +311,19 @@ static int do_device_init(const struct device *dev)
 {
 	int rc = 0;
 
+	/* device initialization has been invoked */
+	dev->state->initialized = true;
```
Comment (andyross) [inline kernel/init.c]: Seems questionable to me to flag this **before** making the init call.  Are you sure this is what the docs require?  Maybe the docs are just wrong?

**Review by andyross — COMMENTED** [review]
Question on the initialized flag semantics.  Also pedantry: you want to introduce the test after the fix in the commit sequence, otherwise the PR introduces a bisection failure.

File: kernel/init.c (hunk 5 above)
Comment (peter-mitsis) [inline kernel/init.c]: It is not yet obvious to me why the setting of this `initialized` field to true was moved here. Doing so, does raise a potential race condition concern here to me.

The routine `device_is_ready()` checks both `initialized` and `init_res`. If there is a context switch between setting `initialized` to true and a failing call to dev->ops.init(), device_is_ready() might mistakenly think that the device is ready, when it has not yet finished initialization.

Is this possible? I'm not sure, but I wanted to raise this just in case.

File: kernel/init.c [hunk 6]
```diff
@@ -311,24 +311,19 @@ static int do_device_init(const struct device *dev)
...
-			if (rc < 0) {
-				rc = -rc;
-			}
-			if (rc > UINT8_MAX) {
-				rc = UINT8_MAX;
-			}
-			dev->state->init_res = rc;
+			int res = (rc < 0) ? -rc : rc;
+
+			dev->state->init_res = (res <= UINT8_MAX) ? res : UINT8_MAX;
```
Comment (peter-mitsis) [inline kernel/init.c]: Two things jump out at me here.

The first is that unless I am missing something, this just gives the same behavior as the original code. If that is true, how does that fix anything?

The second is a logical corner case. If the return code `rc` from `dev->ops.init()` is ever INT_MIN (0x80000000), then `-rc` is the same as `rc`, and the value that we save will be 0x0--a false success path. Would it be worthwhile to have an assert that covers that?

**Review by peter-mitsis — COMMENTED** [review]
A couple of comments--hopefully they are useful.

**Review by cfriedt — COMMENTED** [review]
Sorry - I started a review of this quite a while ago but didn't finish. Please see my comments as well.

**Comment by ljd42** [comment]
> Question on the initialized flag semantics. Also pedantry: you want to introduce the test after the fix in the commit sequence, otherwise the PR introduces a bisection failure.

For bugs, introducing the test first, then the fix, has the advantage to give an audit trail. (fail before the fix, pass after). This can be useful for certification process/audit (IEC 61508 and the like).

If that's a problem from a git/zephyr way of working, happy to reorder... I have anyway some reviews findings from Cris to include for the test :wink:

File: kernel/init.c (hunk 5 above)
Comment (ljd42) [reply kernel/init.c]: We have investigated in length in #91095  if the documentation or the code is wrong (fixing doc is easier). Based on the original PR/review and code context, we agree that the code is wrong.

Regarding the moving the flag. I'm afraid this is one of this idea that sounded brilliant, but in retrospect, turns to be a stupid one! Will fix.

Comment (ljd42) [reply kernel/init.c]: ACK. 

This is a possible race condition. (to be pedantic, even at the 'right' place, we'd still have some race has we're not using any memory barrier). I will revert that change.

File: kernel/init.c (hunk 1 above)
Comment (ljd42) [reply kernel/init.c]: yes, yes and yes.

File: kernel/init.c (hunk 6 above)
Comment (ljd42) [reply kernel/init.c]: The original code flips the sign of `rc` if the device init fails, and returns it. So `do_device_init()` returns +errno. The proposed change uses an intermediate variable `res` for computing the +errno value to stored in init_res, but do not modify rc. So `do_device_init()` will return `-errno`.  I should have mention it in the commit. 

About the assert: I completely agree!

File: tests/kernel/device/src/main.c (hunk 2 above)
Comment (ljd42) [reply tests/kernel/device/src/main.c]: Damn, I should have come to it myself.... But I guess, there's a few more tests there we could improve too :wink:

File: tests/kernel/device/src/main.c (hunk 3 above)
Comment (ljd42) [reply tests/kernel/device/src/main.c]: ACK

File: tests/kernel/device/src/main.c (hunk 4 above)
Comment (ljd42) [reply tests/kernel/device/src/main.c]: NACK.
I'm guessing you meant:
```
zassert_equal(ret, -EALREADY);
zassert_equal(dev->state->init_res, EIO);
```

File: kernel/init.c (hunk 6 above)
Comment (peter-mitsis) [reply kernel/init.c]: Aaah ... I finally see what my eyes kept glazing over on the previous pass with regards to the signedness of `rc`.

File: tests/kernel/device/src/main.c (hunk 2 above)
Comment (kartben) [reply tests/kernel/device/src/main.c]: Indeed, and for those that do `zassert_true(ret == 0)` then `zassert_ok(ret)` would be the preferred alternative :)

**Comment by andyross** [comment]
> For bugs, introducing the test first, then the fix, has the advantage to give an audit trail. (fail before the fix, pass after). This can be useful for certification process/audit (IEC 61508 and the like).

Right, but it breaks "git bisect" by introducing an unrelated/phantom failure in the tree, which is an actual software tool we need to run with some regularity.  Human audits can always make do with an extra patch reversion or whatever.  Please reorder :)

**Comment by ljd42** [comment]
> Right, but it breaks "git bisect" by introducing an unrelated/phantom failure in the tree, which is an actual software tool we need to run with some regularity. Human audits can always make do with an extra patch reversion or whatever. Please reorder :)

@andyross: I have already re-ordered the commits in the atest push: the commit for the test comes now after the commit for the code change.

**Review by JarmouniA — DISMISSED** [review]

File: kernel/init.c [hunk 7]
```diff
@@ -313,20 +313,16 @@ static int do_device_init(const struct device *dev)
...
-				rc = -rc;
-			}
-			if (rc > UINT8_MAX) {
-				rc = UINT8_MAX;
-			}
-			dev->state->init_res = rc;
+			__ASSERT(rc != INT_MIN, "init(dev) failed, but init_res will be 0");
+			int res = (rc < 0) ? -rc : rc;
+
+			dev->state->init_res = (res <= UINT8_MAX) ? res : UINT8_MAX;
```
Comment (cfriedt) [inline kernel/init.c]: Does something like this work?
```suggestion
#include <stdlib.h>
...
			dev->state->init_res = CLAMP(abs(rc), 0, UINT8_MAX);
```

Comment (ljd42) [reply kernel/init.c]: @cfriedt : Ok, this makes the reading easier. But the code is located in the kernel/  folder, and none of the files there use stdlib.h. So, I'm not sure if it's a good idea. 

A `CLAMP()` macro is available  in sys/util.h, and is used in sched.c for instance. There's no `abs()` however.

**Review by peter-mitsis — DISMISSED** [review]

**Comment by dkalowsk** [comment]
@cfriedt please re-reivew

File: kernel/init.c (hunk 7 above)
Comment (cfriedt) [reply kernel/init.c]: If you would prefer to stick to freestanding C, then locally, just

```cpp
/* avoid pulling in stdlib */
#undef _abs
#define _abs(x) ((x) < 0 ? (-(x)) : (x))
```

Sort of like what you had already, but also a bit more readable.

Comment (ljd42) [reply kernel/init.c]: I am going to implement your proposed changes, Chris, as it improves the code reading.

**Comment by ljd42** [comment]
~~This PR is now targeting Zephyr v4.3.~~ As it is a fix, it's OK for 4.2. Will do the patch this week-end.

File: kernel/init.c (hunk 7 above)
Comment (ljd42) [reply kernel/init.c]: Implemented.

**Comment by ljd42** [comment]
Chris's suggestion to use CLAMP() has been implemented.

**Review by cfriedt — DISMISSED** [review]
LGTM - the only thing I didn't notice earlier is that `<zephyr/sys/util.h>` isn't explicitly included, but if it builds, it builds.

**Comment by ljd42** [comment]
> LGTM - the only thing I didn't notice earlier is that `<zephyr/sys/util.h>` isn't explicitly included, but if it builds, it builds.

Correct. 
<zephyr/sys/util.h> is pulled by <zephyr/init.h>. So it's not needed explicitly.

File: kernel/init.c [hunk 8]
```diff
@@ -41,6 +41,11 @@
 #include <zephyr/internal/syscall_handler.h>
 LOG_MODULE_REGISTER(os, CONFIG_KERNEL_LOG_LEVEL);
 
+/* avoid pulling in stdlib */
+#undef _abs
+#define _abs(x) ((x) < 0 ? (-(x)) : (x))
```
Comment (andyross) [inline kernel/init.c]: Style: not loving this.  That `#undef` seems like an admission that there is a known collision with another symbol, in which case this is a bug.  If it's not colliding, letting the preprocessor detect and warn on the redefinition is the correct way to be sure continues not to collide. 

Also: this isn't actually used to compute an "absolute value" in a semantic sense.  It's to handle the variant signedness conventions of an error return value, which are logically enumerates and not integers on which you do math.  IMHO the logic belongs below where you're processing the error value, ideally with a comment explaining e.g. "init_res stores the POSITIVE value of the resulting errno".

File: kernel/init.c [hunk 9]
```diff
@@ -313,20 +318,14 @@ static int do_device_init(const struct device *dev)
...
 		if (rc != 0) {
-			if (rc < 0) {
-				rc = -rc;
-			}
-			if (rc > UINT8_MAX) {
-				rc = UINT8_MAX;
-			}
-			dev->state->init_res = rc;
+			__ASSERT(rc != INT_MIN, "init(dev) failed, but init_res will be 0");
+			dev->state->init_res = CLAMP(_abs(rc), 0, UINT8_MAX);
```
Comment (andyross) [inline kernel/init.c]: Confused on the clamp.  Why clamp?  I mean, there's no semantic value to an errno of 256, right?  An overflow is an error no matter what.  So why waste the instruction bytes on the extra condition?  Truncating is no less an error.

**Review by andyross — CHANGES_REQUESTED** [review]
Sorry, some nits on the error code handling that rise just to my -1 threshold.  The preprocessor one is the only fatal one though, I'm willing to be convinced on the translation code for the number.

File: kernel/init.c (hunk 8 above)
Comment (ljd42) [reply kernel/init.c]: > That #undef seems like an admission that there is a known collision with another symbol [...]

I have checked that there's no collision before making the change...  While the intend is clear (local override), I wondered if that #undef was a common technique to use within the Zephyr kernel :sweat_smile:  It is used elsewhere, and I trusted Chris suggestion.

I'm absolutely with you on this. A redefinition causes indeed a build error. That's the way to go!

> Also: this isn't actually used to compute an "absolute value" in a semantic sense.  [...] 

Yes, I agree.

File: kernel/init.c (hunk 9 above)
Comment (ljd42) [reply kernel/init.c]: At first glance, the  suggested change seemed to require less mental cycles to process than the first version with the two conditional expressions...

>  An overflow is an error no matter what.  [...] Truncating is no less an error.

I agree with your line of reasoning. But note that the code currently in tree also truncates to UINT8_MAX:
https://github.com/zephyrproject-rtos/zephyr/blob/fdd02c5105d2a40cf6410cf89ccd22c43a48399e/kernel/init.c#L322-L328

From what I can see, it does so because dev->state->init_res is an uint8_t. It's better to store 255 in case of an overflow - even if that is bogus - than 0 if the value happens to be a multiple of 256.

Archeological note: this piece of code is present since 2021, and has been introduced with Zephyr 2.6. See device.c::z_sys_init_run_level()

**Comment by ljd42** [comment]
I found a radical solution that minimizes the code change, and should address all review comments discussed so far. I hope that works for you.

**Comment by ljd42** [comment]
I know where all busy, and it's holiday time.  Hence gentle ping @andyross @cfriedt

**Review by bjarki-andreasen — APPROVED** [review]
LGTM

**Review by cfriedt — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]
approving the changes.  Does this need a call out in the release notes though?  Seems like a rather big change.

**Comment by ljd42** [comment]
@dkalowsk : yes, absolutely. This needs to be called out in the **Release note and migration guide**. This has been analyzed in the linked issue, before we decide how to go about it. Just point me to the doc to edit, and I'll take care of it. 

Quoting from #91095:

> Of course, the change will potentially impact code **using deferred initialization**.  I see 3 groups:
>
>  -  group 1: does not care to check the return value of device_init() => no impact. But they should really start checking 😉
>   - group 2: implement the error checking following the spec. Error condition is never detected => positive impact as error > condition are now detected that weren't previously.
>  - group 3: has implemented a workaround for the faulty error condition => they need to remove their workaround. We should put a note in the migration guide.

**Comment by cfriedt** [comment]
@andyross @peter-mitsis - I think we need an approval from either of you as assignee

**Comment by dkalowsk** [comment]
> @dkalowsk : yes, absolutely. This needs to be called out in the **Release note and migration guide**. This has been analyzed in the linked issue, before we decide how to go about it. Just point me to the doc to edit, and I'll take care of it.

@ljd42  check under `docs/releases/release-notes-4.3.txt` and maybe also the migration.txt for the release.

**Review by andyross — APPROVED** [review]
Had to be summoned from discord.  No more complaints.

**Review by peter-mitsis — APPROVED** [review]
