### PR TITLE
drivers: usb_dc_nrfx: Use dedicated work queue for handling ISR events

### LINKED ISSUE #17697: usb_dc_nrfx driver gets stuck after USB3CV HID Tests are performed on hid sample
**Describe the bug**
After USB3CV HID Tests are performed on the nrf52840_pca1005 board running the _hid_ sample, the device becomes no longer responsive: another attempt to run the test suite fails, the sample no longer sends any reports. The device is stuck and even replugging of the USB cable doesn't help, only a reset can bring it to the normal operation.
A short investigation shows that the USB device stack gets stuck in [this loop](https://github.com/zephyrproject-rtos/zephyr/blob/efae1a5e10512e28f174ad908ac40b4b5eedc4b5/subsys/usb/usb_device.c#L1043) because the usb_dc_nrfx driver continuously returns the `-EAGAIN` error, and the driver does it because its `write_in_progress` flags is still `true` ([see this](https://github.com/zephyrproject-rtos/zephyr/blob/efae1a5e10512e28f174ad908ac40b4b5eedc4b5/drivers/usb/device/usb_dc_nrfx.c#L1657)).

**To Reproduce**
1. cd samples/subsys/usb/hid
2. mkdir build; cd build
3. cmake -GNinja -DBOARD=nrf52840_pca10056 ..
4. ninja flash
5. Run the "HID Tests" suite from the USB3CV tool, the suite passes.
6. See that the device no longer works. 

**Expected behavior**
The device working the same way before and after the "HID Tests" suite is executed.

**Impact**
potential showstopper

**Environment (please complete the following information):**
 - OS: Linux for building the sample, Windows for running the test suite
 - Toolchain: Zephyr SDK 0.10.1
 - Commit SHA: efae1a5e10512e28f174ad908ac40b4b5eedc4b5 (current master)

### PR DESCRIPTION
**Pull request by anangl**
This patch introduces a dedicated work queue for handling the events
from ISR (i.e. for notifying the USB device stack, for executing the
enpoints callbacks, etc.). The system work queue cannot be used for
this purpose as it might be used in applications for scheduling USB
transfers and this could lead to a deadlock when the USB device stack
would not be notified about certain event because of a system work
queue item waiting for a USB transfer to be finished.

The FIFO named so far `work_queue` is renamed to `usbd_evt_fifo`
to better indicate its purpose and to avoid confusion.

Fixes #17697

### CODE REVIEW

File: drivers/usb/device/usb_dc_nrfx.c [hunk 1]
```diff
@@ -262,7 +261,19 @@ struct nrf_usbd_ctx {
...
+/* Work queue used for handling the ISR events (i.e. for notifying the USB
+ * device stack, for executing the endpoints callbacks, etc.) out of the ISR
+ * context.
+ * The system work queue cannot be used for this purpose as it might be used in
+ * applications for scheduling USB transfers and this could lead to a deadlock
+ * when the USB device stack would not be notified about certain event because
+ * of a system work queue item waiting for a USB transfer to be finished.
+ */
+static struct k_work_q usbd_work_queue;
+static K_THREAD_STACK_DEFINE(usbd_work_queue_stack, 1024);
```
Comment (carlescufi) [inline drivers/usb/device/usb_dc_nrfx.c]: Should the stack size be a Kconfig option? `NRF_USBD_STACK_SIZE`?

**Review by carlescufi — APPROVED** [review]

File: drivers/usb/device/usb_dc_nrfx.c (hunk 1 above)
Comment (jfischer-phytec-iot) [reply drivers/usb/device/usb_dc_nrfx.c]: NRF_USBD_DRIVER_WQUEUE_SIZE?

Comment (anangl) [reply drivers/usb/device/usb_dc_nrfx.c]: Yes, good point. I'll add such option.

Comment (anangl) [reply drivers/usb/device/usb_dc_nrfx.c]: Added.

**Review by masz-nordic — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]

**Comment by anangl** [comment]
@nashif @carlescufi CI failed in a strange way. At least the [failure](https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/46473/2/tests) seems not to be related to the changes from this PR. Is this a known issue?
