### PR TITLE
net: lwm2m: rework error handing in content formaters

### LINKED ISSUE #41996: LWM2M writing too long strings trigger post_write_cb with previously written value
**Describe the bug**
You get no error or warning if you try to write a too long string from a LWM2M server, instead the code will silently use the last written value (that had a good length), and trigger post_write_cb and the like with that value, effectily making it look like you wrote the same value once again.

**To Reproduce**
We can define an IPSO object with a field of type String, and set its resource to some static char array, and using the size of that array as the size of the resource. We can also register eg. post_write callback for this field.

If we then write that field from a LWM2M server with a string that is longer than the resource array, we don't get an error. Instead, the resource array is simply not overwritten with the new value, but keeps the old value, and then carries on processing the write as if that value is the newly written value. This will then trigger eg. post_write callback with the previous value, making it look like we write the same value again.

**Expected behavior**
I would expect the lwm2m engine to throw an error if the string is too long, not allowing the write, and stopping the processing of it.

https://github.com/zephyrproject-rtos/zephyr/blob/875c75c4f9f75927cec94c580d16d42eb5d26c0e/subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c#L632-L634

The above code has a TODO regarding this, and does return 0, indicating that nothing was written. But lwm2m engine does not take this into account:

https://github.com/zephyrproject-rtos/zephyr/blob/f2ca6a8c22052eac8f10cdda41d477716f85eb02/subsys/net/lib/lwm2m/lwm2m_engine.c#L2555-L2558

ignoring the return from the engine_get_string, and just assuming the `write_buf` was written to.

This would be easy to fix, changing the code above to:

```c
case LWM2M_RES_TYPE_STRING:
	if (engine_get_string(&msg->in, write_buf, write_buf_len) <= 0) {
		/* -EEXIST will generate Bad Request LWM2M response. */
		return -EEXIST;
	}
	len = strlen((char *)write_buf);
	break;
```

Using either `== 0` or `<= 0` depending on what we want to cover.

**Impact**
I have found no other way to actually check and error on the length of a string. I have tried adding a longer validate buffer, and that works in some sense, but basically only delaying the problem, since the exakt same problem will occur when the written string is longer than the validate buffer.

I can design other guards for this, or adding more fields for the length etc, but it's not pretty or clean. I can also design my code to not care about the multiple writes of the same value, but the problem is really that the user of the server thinks that the new, too long, value was actually written.

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Toolchain: gnuarmemb
 - Zephyr version: Tested on tag `v2.7.0-ncs1`, but also check Zephyr main and saw no fix to this.
 - LWM2M server: Eclipse Leshan, but with our own modifications

### PR DESCRIPTION
**Pull request by rlubos**
This PR introduces a set of changes to improve error detection in content encoders/decoders;
* Modify the encoders/decoders generic API, to return `ssize_t` instead of `size_t`, therefore allowing to report error conditions (typically -ENOMEM for encoders when we run out of memory in a packer, or -ENODATA for decoders when there is no expected data in received packet),
* Align all of the existing encoders/decoders with the API changes, adding additional error checks where appropriate,
* Add a set of unit tests for each content type encoder/decoder,
* And finally fix a couple of minor bug detected by the aforementioned tests.

Fixes #41996.

### CODE REVIEW

**Comment by rlubos** [comment]
CC @jheiskan81 @VeijoPesonen @SeppoTakalo feel free to review

**Comment by rlubos** [comment]
@jukkar My bad, I didn't notice `ssize_t` is limited to -1 only by the specification. I agree we should not use it to return other negative values to avoid confision and I'm not really a fan of using `errno` for this use case.

> Just pondering here that would it make sense to use normal int value to tell error (<0), and 0 as success and then have a separate size_t value returned as a parameter, what do you think?

I think we could use the `int` for the return value, I just wonder do we really need that extra parameter for returning the size written? Those functions work with datagrams, which size is limited to 64K so in theory there's no way we'll overflow `int` if we return the number of bytes written/read directly through the return value (we could use `int32_t` just to be 100% sure).

**Comment by jukkar** [comment]
> I think we could use the `int` for the return value, I just wonder do we really need that extra parameter for returning the size written? Those functions work with datagrams, which size is limited to 64K so in theory there's no way we'll overflow `int` if we return the number of bytes written/read directly through the return value (we could use `int32_t` just to be 100% sure).

In that case, we could just return int as it can handle all the values returned.

**Comment by rlubos** [comment]
@jukkar I've updated the APIs to use `int` instead. Additionally added a couple of commits addressing nits found by the CI.

**Review by jheiskan81 — APPROVED** [review]
Looks good for me.

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by rlubos** [comment]
@carlescufi Any chance to get this in before code freeze?

File: subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c [hunk 1]
```diff
@@ -926,7 +924,7 @@ int do_write_op_tlv(struct lwm2m_message *msg)
 		 * We need tlv.type to determine how to proceed.
 		 */
 		len = oma_tlv_get(&tlv, &msg->in, true);
-		if (len == 0) {
+		if (len < 0) {
```
Comment (VeijoPesonen) [inline subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c:927]: Empty data is ok?

Comment (rlubos) [reply subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c:927]: For TLV there's never a case where there is no data (i. e. 0 is returned) - either there is at least TLV header (and thus the return value is non-zero positive), or an error code is returned.

**Review by VeijoPesonen — APPROVED** [review]
One question - otherwise looks good to me.

File: subsys/net/lib/lwm2m/lwm2m_rw_plain_text.c [hunk 2]
```diff
@@ -219,20 +224,20 @@ static size_t get_s32(struct lwm2m_input_context *in, int32_t *value)
...
+static int get_string(struct lwm2m_input_context *in, uint8_t *value,
+		      size_t buflen)
 {
 	uint16_t in_len;
 
 	coap_packet_get_payload(in->in_cpkt, &in_len);
 
 	if (in_len > buflen) {
-		/* TODO: generate warning? */
+		LOG_WRN("Buffer too small to accommodate string, truncating");
```
Comment (SeppoTakalo) [inline subsys/net/lib/lwm2m/lwm2m_rw_plain_text.c:240]: Should this be `LOG_ERR()` as we actually failed to generate the correct content.

**Review by SeppoTakalo — APPROVED** [review]

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 3]
```diff
@@ -3160,12 +3182,20 @@ int lwm2m_perform_read_op(struct lwm2m_message *msg, uint16_t content_format)
...
 
 				/* perform read operation on this resource */
 				ret = lwm2m_read_handler(obj_inst, res,
 							 obj_field, msg);
-				if (ret < 0) {
+				if (ret == -ENOMEM) {
+					/* No point continuing if there's no
+					 * memory left in a message.
+					 */
+					return ret;
```
[the remark this answers is not in the document]
Comment (rlubos) [reply subsys/net/lib/lwm2m/lwm2m_engine.c:3197]: Allowing to continue when `ENOMEM` is reported would require further rework fo the content writers - TLV or JSON will insert appropriate metadata in the packet first (TLV header, JSON tokens). If we fail to write the payload afterward, we still end up with a malformed packed (it should be required from content writers to undo any changes done to the packet). Therefore for now I've decided to treat `ENOMEM` as fatal.

Another thing is whether handling the requests partially is ok - responding with an error message could hint the server that it should query each resource individually, otherwise the event would go unnoticed, resulting in outdated reasource values on the server side.

File: subsys/net/lib/lwm2m/lwm2m_rw_plain_text.c (hunk 2 above)
Comment (rlubos) [reply subsys/net/lib/lwm2m/lwm2m_rw_plain_text.c:240]: I can increse log severity level, it might make sense.

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 4]
```diff
@@ -2545,72 +2560,69 @@ int lwm2m_write_handler(struct lwm2m_engine_obj_inst *obj_inst,
...
-			}
-
 			len = ret;
 			break;
 
 		case LWM2M_RES_TYPE_STRING:
-			engine_get_string(&msg->in, write_buf, write_buf_len);
+			ret = engine_get_string(&msg->in, write_buf,
+						write_buf_len);
 			len = strlen((char *)write_buf);
```
Comment (petterssonandreas) [inline subsys/net/lib/lwm2m/lwm2m_engine.c:2569]: Isn't this potentially bad? If `engine_get_string` produced an error, which we now can see by checking `ret`, we have no idea what `write_buf` actually contains right? Of course, this is only a read, but it could potentially read indefinitely, right, since we have no way of knowing that the string is terminated?

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 5]
```diff
@@ -2545,72 +2560,69 @@ int lwm2m_write_handler(struct lwm2m_engine_obj_inst *obj_inst,
...
 			break;
 
 		case LWM2M_RES_TYPE_U32:
 		case LWM2M_RES_TYPE_TIME:
-			engine_get_s64(&msg->in, &temp64);
+			ret = engine_get_s64(&msg->in, &temp64);
 			*(uint32_t *)write_buf = temp64;
```
Comment (petterssonandreas) [inline subsys/net/lib/lwm2m/lwm2m_engine.c:2575]: This seems bad, do we really want to write the data to `write_buf` without checking `ret` first to make sure we didn't get any errors? Similarly for all the other types.

File: subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c [hunk 6]
```diff
@@ -537,48 +526,63 @@ static size_t put_float(struct lwm2m_output_context *out,
...
 	struct oma_tlv tlv;
-	size_t size = oma_tlv_get(&tlv, in, false);
+	int size;
 	int64_t temp;
+	int ret;
+
+	size = oma_tlv_get(&tlv, in, false);
+	if (size < 0) {
+		return size;
+	}
```
Comment (petterssonandreas) [inline subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c:573]: I prefer this early return, because that makes it clear what we do for errors. But we don't use early return in the other get functions, so maybe convert all to early returns?

File: subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c [hunk 7]
```diff
@@ -537,48 +526,63 @@ static size_t put_float(struct lwm2m_output_context *out,
...
 
 	*value = 0;
 	if (size > 0) {
```
Comment (petterssonandreas) [inline subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c:576]: Do we need this if? Or should the if above include 0 also?

Do we really want to set `*value = 0;` even if `size` is 0?

**Review by petterssonandreas — COMMENTED** [review]
I am not too familiar with the code, but I (quite quickly) reviewed the parts that I addressed in https://github.com/zephyrproject-rtos/zephyr/issues/41996, but I found some issues that I think should be addressed.

File: subsys/net/lib/lwm2m/lwm2m_engine.c (hunk 5 above)
Comment (rlubos) [reply subsys/net/lib/lwm2m/lwm2m_engine.c:2583]: You're right, this isn't right to write the value in case of error, I've added additional error check before write here and in other cases.

File: subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c (hunk 6 above)
Comment (rlubos) [reply subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c:573]: I've updated other functions to return early as well, instead of nesting code within if.

File: subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c (hunk 7 above)
Comment (rlubos) [reply subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c]: Yeah, this check seems redundant now, I"ve remoted that if. `size` shouldn't be 0 for TLVs, as it's always expected to have at least the TLV header - so it'd be either a positive value, or a negative error code.
Finally, after a second check it doesn't seem to be needed to pre-initialize the returned  value to 0, the function shouldn't write anything in case of error.

**Comment by rlubos** [comment]
@petterssonandreas Thank you for the feedback, I've addressed your comments.

**Comment by carlescufi** [comment]
This PR fixes #41996, so merging it in the 3.0.0 window.

**Review by carlescufi — APPROVED** [review]
