### PR TITLE
Bluetooth: GATT: Consistent permission handling of discovered attribute

### LINKED ISSUE #29083: Bluetooth: Host: Inconsistent permission value during discovery procedure
**Describe the bug**
After calling Zephyr Bluetooth API, bt_gatt_discover(), GATT client expects a response structured as Attribute, which contains one permission field (see below). However, it is always 0 now. It might be caused because the GATT server response does not update this attribute permission.

--
struct bt_gatt_attr {
/** Attribute UUID */
const struct bt_uuid *uuid;
...
/** Attribute user data */
void *user_data;
/** Attribute handle */
u16_t handle;
/** Attribute permissions */
u8_t perm;
};

**To Reproduce**
1. call Zephyr API, bt_gatt_discover() with discover type as the primary service
2. Read the permission field in the response (structured as Attribute) in the callback

**Expected behavior**
The Attribute Permissions shall be read-only (BT_GATT_PERM_READ).

**Impact**
annoyance

**Logs and console output**
None

**Environment (please complete the following information):**
- Zephyr 2.4.0
- nRF52840 DK

**Additional context**
None

### PR DESCRIPTION
**Pull request by joerchan**
Be consistent in the permission handling of the discovered attribute
in the temporary object given in the discovery callback.
For characteristics the permission field was set to READ, while for
all other attributes it was set to 0.
    
Fixes: #29083

Document which fields in the attribute parameter in the discovery
callback contains valid information.
Document the type of the user_data so that the application can cast
this to a valid type in order to retrieve the information.

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -2781,11 +2781,11 @@ static void gatt_find_type_rsp(struct bt_conn *conn, uint8_t err,
 		value.end_handle = end_handle;
 		value.uuid = params->uuid;
 
-		attr.uuid = &uuid_svc.uuid;
-		attr.handle = start_handle;
-		attr.user_data = &value;
+		attr = (&(struct bt_gatt_attr)BT_GATT_ATTRIBUTE(
+			&uuid_svc.uuid, 0, NULL, NULL, &value));
+		attr->handle = start_handle;
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:2786]: What's the advantage of doing this instead of passing a reference to a stack variable? You're just increasing stack usage with the extra pointer variable.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -2874,9 +2874,8 @@ static void read_included_uuid_cb(struct bt_conn *conn, uint8_t err,
 		goto next;
 	}
 
-	attr = (&(struct bt_gatt_attr) {
-		.uuid = BT_UUID_GATT_INCLUDE,
-		.user_data = &value, });
+	attr = (&(struct bt_gatt_attr)BT_GATT_ATTRIBUTE(
+		BT_UUID_GATT_INCLUDE, 0, NULL, NULL, &value));
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:2878]: I'd convert this as well to a stack variable and a reference

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/gatt.c]: I wanted to use the BT_GATT_ATTRIBUTE to initialize it. But need to have it together with the declaration.
I've moved it up now.

Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: You don't *need* to do it as part of the declaration, but if you don't you need an explicit `(struct bt_gatt_attr)` typecast in front. I think this begs the question whether we should include that typecast as part of the definition. That would also simplify places wanting to construct these pointers to anonymous variables.

Comment (joerchan) [reply subsys/bluetooth/host/gatt.c]: Thank you for mentioning that. Then I got what I wanted to do.

While including the cast would be useful I think we should do that separately and consistently.
We do have other init macros that should use the same pattern then in my opinion.

**Review by jhedberg — APPROVED** [review]
