### PR TITLE
xcc: fix building errors related to logging

### LINKED ISSUE #43087: XCC build failures for all intel_adsp tests/platforms
When trying to build any testcase/sample using the XCC toolchain (xt-xcc) for any of the intel_adsp boards (although i suspect this will happen for any target) there is a build failure related to `#pragma GCC diagnostic not allowed inside functions`

Please also mention any information which could help others to understand
the problem you're facing:
 - targeted any intel_adsp target and affects all testcases/samples
 - Occurs with XCC toolchain
 
**Expected behavior**
Testcase successfully build when using twister

**Impact**
Currently unable to test any intel_adsp platform with XCC

**Logs and console output**
Sample partial output for one testcase below (errors are the same for all testcases).. (same pragma related error is repeated throughout the logs):
```
INFO    -  93/388 intel_adsp_cavs25         tests/benchmarks/sched/benchmark.kernel.scheduler  FAILED Build failure (build)
-- Application: /zephyrproject/zephyr/tests/benchmarks/sched
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter 
-- Cache files will be written to: /zephyrproject/zephyr/.cache
-- Zephyr version: 3.0.99 (/zephyrproject/zephyr)
-- Found west (found suitable version "0.12.0", minimum required is "0.7.1")
-- Board: intel_adsp_cavs25
-- Found host-tools: zephyr 0.13.2 (/opt/toolchains/zephyr-sdk-0.13.2)
-- Found dtc: /opt/toolchains/zephyr-sdk-0.13.2/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6")
-- Found toolchain: xcc (/opt/toolchains/xcc/install/tools)
-- Found BOARD.dts: //zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs25/intel_adsp_cavs25.dts
-- Generated zephyr.dts: //zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: //zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: /zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/include/generated/device_extern.h
-- Including generated dts.cmake file: /zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/dts.cmake
Parsing //zephyrproject/zephyr/Kconfig
Loaded configuration '/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs25/intel_adsp_cavs25_defconfig'
Merged configuration '/zephyrproject/zephyr/tests/benchmarks/sched/prj.conf'
Configuration saved to '/zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/.config'
Kconfig header saved to '/zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 4.2.0
-- The CXX compiler identification is GNU 4.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/toolchains/xcc/install/tools/RG-2017.8-linux/XtensaTools/bin/xt-xcc
-- Configuring done
-- Generating done
-- Build files have been written to: /zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler
[1/134] Generating include/generated/version.h
-- Zephyr version: 3.0.99 (/zephyrproject/zephyr), build: 8c7d8ecc9aae
[2/134] Preparing syscall dependency handling

[3/134] Generating ../../../../include/generated/core-isa-dM.h
[4/134] Generating ../../../../include/generated/zsr.h
[5/134] Generating misc/generated/syscalls_subdirs.trigger
[6/134] Generating misc/generated/syscalls.json, misc/generated/struct_tags.json
[7/134] Generating include/generated/syscall_dispatch.c, include/generated/syscall_list.h
[8/134] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h, include/generated/otype-to-size.h
[9/134] Generating include/generated/driver-validation.h
[10/134] Building C object zephyr/CMakeFiles/offsets.dir/arch/xtensa/core/offsets/offsets.c.obj
[11/134] Generating include/generated/offsets.h
[12/134] Generating linker_zephyr_pre0.cmd
[13/134] Generating linker_zephyr_pre1.cmd
[14/134] Building ASM object zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/xtensa-asm2-util.S.obj
[15/134] Building ASM object zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/window_vectors.S.obj
[16/134] Building ASM object zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/crt1.S.obj
[17/134] Building ASM object zephyr/arch/arch/xtensa/core/startup/CMakeFiles/arch__xtensa__core__startup.dir/memerror-vector.S.obj
[18/134] Building ASM object zephyr/arch/arch/xtensa/core/startup/CMakeFiles/arch__xtensa__core__startup.dir/memctl_default.S.obj
[19/134] Building ASM object zephyr/arch/arch/xtensa/core/startup/CMakeFiles/arch__xtensa__core__startup.dir/reset-vector.S.obj
[20/134] Linking ASM static library zephyr/arch/arch/xtensa/core/startup/libarch__xtensa__core__startup.a
[21/134] Building C object zephyr/kernel/CMakeFiles/kernel.dir/fatal.c.obj
FAILED: zephyr/kernel/CMakeFiles/kernel.dir/fatal.c.obj 
/opt/toolchains/xcc/install/tools/RG-2017.8-linux/XtensaTools/bin/xt-xcc -DKERNEL -D_FORTIFY_SOURCE=2 -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I../../../../../../kernel/include -I../../../../../../arch/xtensa/include -I../../../../../../include -Izephyr/include/generated -I../../../../../../soc/xtensa/intel_adsp/cavs_v25 -I../../../../../../soc/xtensa/intel_adsp/common/include -I../../../../../../subsys/testsuite/include -isystem ../../../../../../lib/libc/minimal/include -Os -imacros /zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -imacros/zephyrproject/zephyr/include/toolchain/xcc_missing_defs.h -fms-extensions -imacros /zephyrproject/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -fgnu89-inline -Werror=implicit-int -fno-pic -ffunction-sections -fdata-sections -mlongcalls -std=c99 -MD -MT zephyr/kernel/CMakeFiles/kernel.dir/fatal.c.obj -MF zephyr/kernel/CMakeFiles/kernel.dir/fatal.c.obj.d -o zephyr/kernel/CMakeFiles/kernel.dir/fatal.c.obj -c /zephyrproject/zephyr/kernel/fatal.c
/zephyrproject/zephyr/kernel/fatal.c: In function ‘k_sys_fatal_error_handler’:
/zephyrproject/zephyr/kernel/fatal.c:43: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/fatal.c:43: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/fatal.c:43: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/fatal.c: In function ‘z_fatal_error’:
/zephyrproject/zephyr/kernel/fatal.c:108: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/fatal.c:108: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/fatal.c:107: error: ‘__auto_type’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/fatal.c:107: error: (Each undeclared identifier is reported only once
/zephyrproject/zephyr/kernel/fatal.c:107: error: for each function it appears in.)
/zephyrproject/zephyr/kernel/fatal.c:107: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/fatal.c:107: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/fatal.c:107: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/kernel/fatal.c:108: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/fatal.c:107: error: ‘_v1’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/fatal.c:107: error: ‘_v2’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/fatal.c:107: error: ‘_v3’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/fatal.c:123: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/fatal.c:123: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/fatal.c:122: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/fatal.c:122: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/fatal.c:123: error: #pragma GCC diagnostic not allowed inside functions
[22/134] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj
FAILED: zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj 
/opt/toolchains/xcc/install/tools/RG-2017.8-linux/XtensaTools/bin/xt-xcc -DKERNEL -D_FORTIFY_SOURCE=2 -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I../../../../../../kernel/include -I../../../../../../arch/xtensa/include -I../../../../../../include -Izephyr/include/generated -I../../../../../../soc/xtensa/intel_adsp/cavs_v25 -I../../../../../../soc/xtensa/intel_adsp/common/include -I../../../../../../subsys/testsuite/include -isystem ../../../../../../lib/libc/minimal/include -Os -imacros /zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -imacros/zephyrproject/zephyr/include/toolchain/xcc_missing_defs.h -fms-extensions -imacros /zephyrproject/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -fgnu89-inline -Werror=implicit-int -fno-pic -ffunction-sections -fdata-sections -mlongcalls -std=c99 -MD -MT zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj -MF zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj.d -o zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj -c /zephyrproject/zephyr/kernel/mutex.c
/zephyrproject/zephyr/kernel/mutex.c: In function ‘adjust_owner_prio’:
/zephyrproject/zephyr/kernel/mutex.c:88: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:88: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:85: error: ‘__auto_type’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:85: error: (Each undeclared identifier is reported only once
/zephyrproject/zephyr/kernel/mutex.c:85: error: for each function it appears in.)
/zephyrproject/zephyr/kernel/mutex.c:85: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:85: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/mutex.c:85: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/kernel/mutex.c:85: error: expected ‘;’ before ‘_v4’
/zephyrproject/zephyr/kernel/mutex.c:88: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:85: error: ‘_v1’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:85: error: ‘_v2’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:85: error: ‘_v3’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:85: error: ‘_v4’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c: In function ‘z_impl_k_mutex_lock’:
/zephyrproject/zephyr/kernel/mutex.c:118: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:118: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:116: error: ‘__auto_type’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:116: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:116: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/mutex.c:116: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/kernel/mutex.c:116: error: expected ‘;’ before ‘_v4’
/zephyrproject/zephyr/kernel/mutex.c:118: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:116: error: ‘_v1’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:116: error: ‘_v2’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:116: error: ‘_v3’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:116: error: ‘_v4’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:140: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:140: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:140: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:140: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:148: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:148: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:148: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:148: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/mutex.c:148: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:151: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:151: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:150: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:150: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/mutex.c:150: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/kernel/mutex.c:151: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:160: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:160: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:160: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:160: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/mutex.c:160: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:170: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:170: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:170: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:170: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c: In function ‘z_impl_k_mutex_unlock’:
/zephyrproject/zephyr/kernel/mutex.c:227: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:227: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:227: error: ‘__auto_type’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:227: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:227: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/mutex.c:227: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:227: error: ‘_v1’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:227: error: ‘_v2’ undeclared (first use in this function)
/zephyrproject/zephyr/kernel/mutex.c:248: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:248: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:247: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/kernel/mutex.c:247: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/kernel/mutex.c:247: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/kernel/mutex.c:248: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/kernel/mutex.c:247: error: ‘_v3’ undeclared (first use in this function)
[23/134] Building C object zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/xtensa-asm2.c.obj
FAILED: zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/xtensa-asm2.c.obj 
/opt/toolchains/xcc/install/tools/RG-2017.8-linux/XtensaTools/bin/xt-xcc -DKERNEL -D_FORTIFY_SOURCE=2 -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I../../../../../../kernel/include -I../../../../../../arch/xtensa/include -I../../../../../../arch/xtensa/core/include -I../../../../../../include -Izephyr/include/generated -I../../../../../../soc/xtensa/intel_adsp/cavs_v25 -I../../../../../../soc/xtensa/intel_adsp/common/include -I../../../../../../subsys/testsuite/include -isystem ../../../../../../lib/libc/minimal/include -Os -imacros /zephyrproject/zephyr/twister-out/intel_adsp_cavs25/tests/benchmarks/sched/benchmark.kernel.scheduler/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -imacros/zephyrproject/zephyr/include/toolchain/xcc_missing_defs.h -fms-extensions -imacros /zephyrproject/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -fgnu89-inline -Werror=implicit-int -fno-pic -ffunction-sections -fdata-sections -mlongcalls -std=c99 -MD -MT zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/xtensa-asm2.c.obj -MF zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/xtensa-asm2.c.obj.d -o zephyr/arch/arch/xtensa/core/CMakeFiles/arch__xtensa__core.dir/xtensa-asm2.c.obj -c /zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c: In function ‘z_irq_spurious’:
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:89: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:89: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:88: error: ‘__auto_type’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:88: error: (Each undeclared identifier is reported only once
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:88: error: for each function it appears in.)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:88: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:88: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:89: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:88: error: ‘_v1’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:88: error: ‘_v2’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c: In function ‘z_xtensa_dump_stack’:
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:100: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:100: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: ‘__auto_type’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: expected ‘;’ before ‘_v4’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:100: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: ‘_v1’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: ‘_v2’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: ‘_v3’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:97: error: ‘_v4’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:105: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:105: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:103: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:103: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:103: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:103: error: expected ‘;’ before ‘_v4’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:105: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:111: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:111: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:109: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:109: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:109: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:109: error: expected ‘;’ before ‘_v4’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:111: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:117: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:117: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:115: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:115: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:115: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:115: error: expected ‘;’ before ‘_v4’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:117: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:124: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:124: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:121: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:121: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:121: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:124: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:127: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:127: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:127: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:127: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c: In function ‘xtensa_excint1_c’:
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:213: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:213: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:212: error: ‘__auto_type’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:212: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:212: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:213: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:212: error: ‘_v1’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:212: error: ‘_v2’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:227: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:227: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:227: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:230: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:230: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:228: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:228: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:228: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:230: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:228: error: ‘_v3’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:232: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:232: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:231: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:231: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:232: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:233: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:233: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:233: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:233: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:238: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:238: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: expected ‘;’ before ‘_v1’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: expected ‘;’ before ‘_v2’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: expected ‘;’ before ‘_v3’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: expected ‘;’ before ‘_v4’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: expected ‘;’ before ‘_v5’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: expected ‘;’ before ‘_v6’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: expected ‘;’ before ‘_v7’
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:238: error: #pragma GCC diagnostic not allowed inside functions
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: ‘_v4’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: ‘_v5’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: ‘_v6’ undeclared (first use in this function)
/zephyrproject/zephyr/arch/xtensa/core/xtensa-asm2.c:234: error: ‘_v7’ undeclared (first use in this function)

```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain XCC
 - Commit SHA: f401be157f9aa7f959f18dbf371bab7db0134a5b

**Additional context**
This was initially introduced in https://github.com/zephyrproject-rtos/zephyr/pull/42165 and was reverted (which resolved the issues) now this seems to have been reintroduced within the past day and the potential fixes in https://github.com/zephyrproject-rtos/zephyr/pull/42686 do not seem to fix the errors.

### PR DESCRIPTION
**Pull request by dcpleung**
XCC is based on very old GCC (sigh...) that there is no auto type, and _Pragma cannot be used within functions. The latest logging changes related to argument evaluation resulted in build errors regarding these. See individual commits for more details.

### CODE REVIEW

**Comment by cgturner1** [comment]
i did test these with XCC for all adsp targets with the issues mentioned in #43087 and now everything builds as expected without the _pragma related errors

File: include/logging/log_msg2.h [hunk 1]
```diff
@@ -34,6 +35,12 @@ typedef uint64_t log_timestamp_t;
 typedef uint32_t log_timestamp_t;
 #endif
 
+#if !defined(CONFIG_LOG) && \
+	!GCC_VERSION_AT_LEAST(4, 9, 0) && \
+	!CLANG_VERSION_AT_LEAST(3, 8, 0)
```
Comment (andyross) [inline include/logging/log_msg2.h:40]: Nitpick: abstraction-wise, might be better to have toolchain.h define "TOOLCHAIN_HAS_AUTO_TYPE" or somesuch instead of putting the logic here in logging.

File: include/logging/log_msg2.h [hunk 2]
```diff
@@ -388,8 +395,11 @@ do { \
 			   _level, _data, _dlen, \
 			   FOR_EACH_IDX(Z_LOG_LOCAL_ARG_NAME, (,), __VA_ARGS__)); \
 } while (0)
-#endif /* CONFIG_LOG2_ALWAYS_RUNTIME */
+#endif /* CONFIG_LOG2_ALWAYS_RUNTIME || LOG_DISABLED_OLD_TOOLCHAIN_WORKAROUND */
 
+#ifdef LOG_DISABLED_OLD_TOOLCHAIN_WORKAROUND
+#undef LOG_DISABLED_OLD_TOOLCHAIN_WORKAROUND
+#endif
```
Comment (andyross) [inline include/logging/log_msg2.h:402]: Why undef it?  Not understanding this part.  This header has an include guard anyway, so it's not like you're going to have variant/duplicate definitions of this floating around a compilation unit.

**Review by andyross — DISMISSED** [review]
Some nitpicks but nothing worth blocking merge over

File: include/logging/log_msg2.h (hunk 1 above)
Comment (dcpleung) [reply include/logging/log_msg2.h:40]: It also guards against using `_Pragma()` within functions, so not exactly about auto type only.

File: include/logging/log_msg2.h (hunk 2 above)
Comment (dcpleung) [reply include/logging/log_msg2.h:402]: In general, just like to clean up things that should not be used after this.

File: include/logging/log_msg2.h (hunk 1 above)
Comment (nordic-krch) [reply include/logging/log_msg2.h:40]: i'm also for moving flags to toolchain.h.
`TOOLCHAIN_HAS_AUTO_TYPE`, `TOOLCHAIN_HAS_C11_GENERIC`, maybe `TOOLCHAIN_HAS_DIAGNOSTIC_PRAGMAS` (seems that this was introduced in 4.6).

It's already third place i'm aware of where we do that (one in PR https://github.com/zephyrproject-rtos/zephyr/blob/9705d17e11cd119269d3e7ddba505af8dac0d56b/include/event_manager/event_manager_priv.h#L33).

**Review by andyross — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]
