### PR TITLE
Bluetooth: Host: Fix SC not being sent

### LINKED ISSUE #61033: Bluetooth: Host: No space to store CCC when GATT client loses bond and CCC Lazy Loading is enabled
**Describe the bug**
When previously bonded GATT client reconnects and `CONFIG_BT_SETTINGS_CCC_LAZY_LOADING` is enabled, CCC configuration is loaded from Settings. If GATT client had lost bond and `CONFIG_BT_GATT_AUTO_SEC_REQ` is disabled, GATT client can stay connected without reestablishing security. However, when this GATT client tries to write CCC on previously used Attribute it can't do that and following log message appears: `LOG_WRN("No space to store CCC cfg");`. It happens because the `find_ccc_cfg` function in `subsys/bluetooth/host/gatt.c` returns error. That's because the existing CCC for the GATT client can't be overwritten as the security is not reestablished (as expected) and also there is no space to store new CCC configuration, because `cfg` array length in `struct _bt_gatt_ccc` is set to `CONFIG_BT_MAX_CONN` which is often equal to 1. When `CONFIG_BT_SETTINGS_CCC_LAZY_LOADING` is disabled, the `cfg` array length is set to `CONFIG_BT_MAX_PAIRED + CONFIG_BT_MAX_CONN` and the issue doesn't replicate, because there is enough space to store new CCC configuration.

**To Reproduce**
1. Build and flash `zephyr/samples/bluetooth/peripheral` sample with `BT_GATT_AUTO_SEC_REQ` disabled.
2. Pair with the sample from your Bluetooth central (e.g. phone). The phone automatically writes Service Changed CCC. You can also manually write some others CCC (e.g. Battery Service) using e.g. nRF Connect app.
3. Unpair your phone.
4. Reconnect your phone without pairing (you can do that via nRF Connect app)
5. Write Service Changed CCC or some other CCC that you have written in step 2.
6. See that the CCC write fails with warning message: `No space to store CCC cfg`.

You can verify that it doesn't reproduce if `CONFIG_BT_SETTINGS_CCC_LAZY_LOADING` is disabled.

**Expected behavior**
The CCC write should succeed regardless of `CONFIG_BT_SETTINGS_CCC_LAZY_LOADING` being enabled or no. The phone doesn't want to overwrite the existing CCC. It wants to write new one as it has lost bond.

**Impact**
Google Fast Pair Service protocol (https://developers.google.com/nearby/fast-pair/specifications/introduction) requires using GATT before bonding. Because of that, if a Phone loses bond, it is unable to bond again using Fast Pair, because it is unable to write CCC when `CONFIG_BT_SETTINGS_CCC_LAZY_LOADING` is enabled.

**Environment (please complete the following information):**
 - OS: Linux
 - Commit SHA: b37ce40878ec52295afe6350d17712d60eb6639a (recent one)

### LINKED ISSUE #61427: GATT server fails to elevate security when there is insufficient security to send a notification/indication
**Describe the bug**
This issue is created due to several of our existing BabbleSims failing when merging Zephyr version 3.4.99 - tests that depend on service changed indications to some extent and are failing due to them not being sent after reconnecting.

The bug was found when transitioning from Zephyr 3.3.99 to Zephyr 3.4.99 and commit cfd368fef1, “Bluetooth: Host: Fix GATT server handling of CCC” is of particular interest here.

Overall, this happens when a device reconnects, and the GATT server is checking the security level of a CCC that was written while the link was encrypted. With the change in commit cfd368fef1 the security is not elevated by the GATT server for CCCs that were written with an encrypted connection and checked for  a change upon reconnect (while the connection is still unencrypted).

Specifically, it all happens in **gatt.c** when the **bt_gatt_connected()** is called. It traverses all characteristics with a call to **update_ccc()** with a pointer to a **struct conn_data**, which holds a **sec** member, containing the maximum security required for any of the CCCs.
In **update_ccc()** the newly introduced **bt_gatt_ccc_cfg_is_matching_conn()** function is called, that in turn compares the CCC's **link_encrypted** member with the encryption level of the connection and return false if they differ. The false return value will cause **update_ccc()** to skip the CCC hence, the **struct conn_data** pointer’s **sec** member is never updated.
When the call to **update_ccc()** has finished, the **bt_gatt_connected()** function checks its **sec** value, which, in this case, is left untouched, that is, security level 1. Consequently, it will not call **bt_conn_set_security()** with the higher level required by the CCC as intended and the notification/indication will not be sent to the client.

**To Reproduce**
1.	Pair two devices (which implies security level 2).
2.	Let the Central subscribe to a service changed indication from the Peripheral.
3.	Disconnect link.
4.	Change something in the Peripheral’s GATT database to trigger the service changed indication.
5.	Reconnect the two devices (without encrypting, i.e. security level is 1).
6.	Observe that the Peripheral’s GATT server does not elevate the security and the Central’s client receives no notification.

**Expected behavior**
When reconnecting, the GATT server must check the CCCs and if a CCC requires encryption the GATT server shall request encryption.
Refer comment excerpt from gatt.c:
`	/* BLUETOOTH CORE SPECIFICATION Version 5.1 | Vol 3, Part C page 2192:
	 *
	 * 10.3.1.1 Handling of GATT indications and notifications
	 *
	 * A client “requests” a server to send indications and notifications
	 * by appropriately configuring the server via a Client Characteristic
	 * Configuration Descriptor. Since the configuration is persistent
	 * across a disconnection and reconnection, security requirements must
	 * be checked against the configuration upon a reconnection before
	 * sending indications or notifications. When a server reconnects to a
	 * client to send an indication or notification for which security is
	 * required, the server shall initiate or request encryption with the
	 * client prior to sending an indication or notification. If the client
	 * does not have an LTK indicating that the client has lost the bond,
	 * enabling encryption will fail.
	 */`

Specifically, the **sec** member passed to **update_ccc()** must be updated to the security level required. This will trigger the **bt_gatt_connected()** to call **bt_conn_set_security()** in order to encrypt the connection.
Subsequently, the **bt_gatt_encrypt_change()** is called when the link is encrypted and **update_ccc()** is then called, this time triggering a service changed notification.

**Impact**
Can cause missing GATT notifications/indications, unless the Central explicitly enables encryption for other reasons.

**Environment**
 - OS: Debian 11.
 - Toolchain Zephyr SDK, BabbleSim, gcc.
 - Based on Zephyr 3.4.99 + non-related cherry-picks.

**Additional context**
Requires:
CONFIG_BT_GATT_AUTO_SEC_REQ
CONFIG_BT_GATT_SERVICE_CHANGED
CONFIG_BT_SMP

### PR DESCRIPTION
**Pull request by theob-pro**
Fix an issue where the service changed indication is not sent if a previously bonded peer reconnect but doesn't restore the security. Fixes #61427. Also Fixes #61033.

To do so it revert a previous PR (https://github.com/zephyrproject-rtos/zephyr/pull/57163).

Also add a new test to reproduce the issue and update the test from the reverted PR.

### CODE REVIEW

**Review by carlescufi — CHANGES_REQUESTED** [review]
Please keep the commit message generated by `git revert` instead of rewriting it.

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c [hunk 1]
```diff
@@ -0,0 +1,189 @@
...
+
+	conn = g_conn;
+	g_conn = NULL;
+	ASSERT(conn, "Test error: no g_conn!\n");
+	bt_conn_unref(conn);
+}
+
+static void connected(struct bt_conn *conn, uint8_t err)
+{
+	ASSERT((!g_conn || (conn == g_conn)), "Unexpected new connection.");
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c:61]: Suggest to use `if` instead of ASSERT as ASSERT can be disabled (and I guess we always want this check?)

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c [hunk 2]
```diff
@@ -0,0 +1,189 @@
...
+	int err;
+	int32_t timeout = 0;
+	int32_t num_events = 0;
+
+	struct bt_le_ext_adv_start_param start_params = {};
+
+	start_params.timeout = timeout;
+	start_params.num_events = num_events;
+
+	err = bt_le_ext_adv_start(adv, &start_params);
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c:155]:
```suggestion
	err = bt_le_ext_adv_start(adv, BT_LE_EXT_ADV_START_DEFAULT);
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c [hunk 3]
```diff
@@ -0,0 +1,189 @@
...
+	ASSERT(!err, "bt_le_ext_adv_start failed (%d)\n", err);
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c:156]: Ditto, use `if` instead of ASSERT (IMO) - Applies everywhere

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 4]
```diff
@@ -0,0 +1,195 @@
...
+DEFINE_FLAG(flag_discovered);
+DEFINE_FLAG(flag_subscribed);
+DEFINE_FLAG(flag_indicated);
+
+enum GATT_HANDLES {
+	SC,
+	CCC,
+	NUM_HANDLES,
+};
+static uint16_t gatt_handles[NUM_HANDLES] = {0};
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:33]:
```suggestion
};

static uint16_t gatt_handles[NUM_HANDLES] = {0};
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 5]
```diff
@@ -0,0 +1,195 @@
...
+
+static struct bt_gatt_subscribe_params subscribe_params;
+
+static void sc_subscribed(struct bt_conn *conn,
+		       uint8_t err,
+		       struct bt_gatt_subscribe_params *params)
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:39]: Indentation

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+{
+	LOG_ERR("%s", __func__);
+	SET_FLAG(flag_subscribed);
+}
+
+static uint8_t sc_indicated(struct bt_conn *conn,
+		      struct bt_gatt_subscribe_params *params,
+		      const void *data,
+		      uint16_t length)
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:48]: Indentation

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+	subscribe_params.notify = sc_indicated;
+
+	err = bt_gatt_subscribe(get_g_conn(), &subscribe_params);
+	ASSERT(!err, "bt_gatt_subscribe failed (%d)\n", err);
+
+	WAIT_FOR_FLAG(flag_subscribed);
+}
+
+
+static uint8_t discover_func(struct bt_conn *conn,
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:74]:
```suggestion
}

static uint8_t discover_func(struct bt_conn *conn,
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 8]
```diff
@@ -0,0 +1,195 @@
...
+			     const struct bt_gatt_attr *attr,
+			     struct bt_gatt_discover_params *params)
+{
+	int err;
+
+	if (attr == NULL) {
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:80]:
```suggestion
{
	if (attr == NULL) {
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 9]
```diff
@@ -0,0 +1,195 @@
...
+		return BT_GATT_ITER_STOP;
+	}
+
+	if (params->type == BT_GATT_DISCOVER_CHARACTERISTIC) {
+		const struct bt_gatt_chrc *chrc = (struct bt_gatt_chrc *)attr->user_data;
+		const struct bt_uuid_16 ccc_uuid = BT_UUID_INIT_16(BT_UUID_GATT_CCC_VAL);
+
+		if (bt_uuid_cmp(chrc->uuid, BT_UUID_GATT_SC) == 0) {
+			LOG_DBG("found sc");
+			gatt_handles[SC] = chrc->value_handle;
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:97]:
```suggestion
		if (bt_uuid_cmp(chrc->uuid, BT_UUID_GATT_SC) == 0) {
		        int err;
		        
			LOG_DBG("found sc");
			gatt_handles[SC] = chrc->value_handle;
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 10]
```diff
@@ -0,0 +1,195 @@
...
+	 *
+	 * to pass the test, the central will wait to receive the service
+	 * changed indication
+	 */
+
+	int err;
+	struct bt_conn_auth_info_cb bt_conn_auth_info_cb = {};
+
+	bt_conn_auth_info_cb.pairing_failed = pairing_failed;
+	bt_conn_auth_info_cb.pairing_complete = pairing_complete;
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:160]:
```suggestion
	struct bt_conn_auth_info_cb bt_conn_auth_info_cb = {
		.pairing_failed = pairing_failed,
		.pairing_complete = pairing_complete,
	};
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 11]
```diff
@@ -0,0 +1,195 @@
...
+
+	scan_connect_to_first_result();
+	wait_connected();
+
+	/* wait for service change indication */
+	WAIT_FOR_FLAG(flag_indicated);
+
+	PASS("PASS\n");
+
+}
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:195]:
```suggestion
	PASS("PASS\n");
}
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/main.c [hunk 12]
```diff
@@ -0,0 +1,58 @@
+/*
+ * Copyright (c) 2023 Nordic Semiconductor ASA
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include "bstests.h"
+#include "bs_bt_utils.h"
+
+#define BS_SECONDS(dur_sec)    ((bs_time_t)dur_sec * 1000000)
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/main.c:10]:
```suggestion
#define BS_SECONDS(dur_sec)    ((bs_time_t)dur_sec * USEC_PER_SEC)
```
Also, BS_SECONDS isn't a great name for something that's microseconds

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/main.c [hunk 13]
```diff
@@ -0,0 +1,58 @@
...
+#define TEST_TIMEOUT_SIMULATED BS_SECONDS(60)
+
+extern void central(void);
+extern void peripheral(void);
+
+void test_tick(bs_time_t HW_device_time)
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/main.c:16]:
```suggestion
static void test_tick(bs_time_t HW_device_time)
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/main.c [hunk 14]
```diff
@@ -0,0 +1,58 @@
...
+{
+	bs_trace_debug_time(0, "Simulation ends now.\n");
+	if (bst_result != Passed) {
+		bst_result = Failed;
+		bs_trace_error("Test did not pass before simulation ended.\n");
+	}
+}
+
+void test_init(void)
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/main.c:25]:
```suggestion
static void test_init(void)
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c [hunk 15]
```diff
@@ -0,0 +1,93 @@
...
+LOG_MODULE_REGISTER(test_peripheral, LOG_LEVEL_DBG);
+
+#include "bs_bt_utils.h"
+
+#define UUID_1                                                                                     \
+	BT_UUID_DECLARE_128(0xdb, 0x1f, 0xe2, 0x52, 0xf3, 0xc6, 0x43, 0x66, 0xb3, 0x92, 0x5d,      \
+			    0xc6, 0xe7, 0xc9, 0x59, 0x9d)
+#define UUID_2                                                                                     \
+	BT_UUID_DECLARE_128(0x3f, 0xa4, 0x7f, 0x44, 0x2e, 0x2a, 0x43, 0x05, 0xab, 0x38, 0x07,      \
+			    0x8d, 0x16, 0xbf, 0x99, 0xf1)
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c:27]: Suggest to format these as 2 x 8

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c [hunk 16]
```diff
@@ -0,0 +1,93 @@
...
+
+static void new_svc_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
+{
+	ARG_UNUSED(attr);
+
+	LOG_DBG("%s", __func__);
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c:33]: Unless disabled, `LOG_DBG` should prepend the function name to the log statement by itself

**Review by Thalley — CHANGES_REQUESTED** [review]

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c (hunk 1 above)
Comment (Thalley) [reply tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c:61]: Oh. I don't redefining a common macro like `ASSERT` is a good idea either :D 

```
if (expr) {
    FAIL(...);
}
```

Isn't a large chunk of code to have, and it makes it very clear what is going on. 

If you want to keep it as a macro like above, then I suggest to rename it `BSIM_ASSERT` or `BS_BT_UTIL_ASSERT` or something like that, so it isn't confused with the _actual_ `ASSERT`

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c (hunk 15 above)
Comment (theob-pro) [reply tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c:27]: Sorry, I did not get it, can you show me?

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c (hunk 1 above)
Comment (theob-pro) [reply tests/bsim/bluetooth/host/gatt/sc_indicate/src/bs_bt_utils.c:61]: You're right, I will rename it.

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c (hunk 15 above)
Comment (Thalley) [reply tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c:27]: Sure, so instead of the current
```c

#define UUID_1                                                                                     \
	BT_UUID_DECLARE_128(0xdb, 0x1f, 0xe2, 0x52, 0xf3, 0xc6, 0x43, 0x66, 0xb3, 0x92, 0x5d,      \
			    0xc6, 0xe7, 0xc9, 0x59, 0x9d)
#define UUID_2                                                                                     \
	BT_UUID_DECLARE_128(0x3f, 0xa4, 0x7f, 0x44, 0x2e, 0x2a, 0x43, 0x05, 0xab, 0x38, 0x07,      \
			    0x8d, 0x16, 0xbf, 0x99, 0xf1)
```

You could have 

```c

#define UUID_1                                                                                     \
	BT_UUID_DECLARE_128(0xdb, 0x1f, 0xe2, 0x52, 0xf3, 0xc6, 0x43, 0x66,                        \ 
			    0xb3, 0x92, 0x5d, 0xc6, 0xe7, 0xc9, 0x59, 0x9d)
#define UUID_2                                                                                     \
	BT_UUID_DECLARE_128(0x3f, 0xa4, 0x7f, 0x44, 0x2e, 0x2a, 0x43, 0x05,                        \
			    0xab, 0x38, 0x07,, 0x8d, 0x16, 0xbf, 0x99, 0xf1)
```

Just to make it appear a little nicer

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 17]
```diff
@@ -0,0 +1,194 @@
...
+
+	WAIT_FOR_FLAG(flag_subscribed);
+}
+
+static uint8_t discover_func(struct bt_conn *conn,
+			     const struct bt_gatt_attr *attr,
+			     struct bt_gatt_discover_params *params)
+{
+	if (attr == NULL) {
+		for (int i = 0; i < ARRAY_SIZE(gatt_handles); i++) {
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:79]:
```suggestion
		for (size_t i = 0U; i < ARRAY_SIZE(gatt_handles); i++) {
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 18]
```diff
@@ -0,0 +1,194 @@
...
+			LOG_DBG("handle[%d] = 0x%x", i, gatt_handles[i]);
+			BSIM_ASSERT(gatt_handles[i] != 0, "did not find all handles\n");
+		}
+		(void)memset(params, 0, sizeof(*params));
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:83]:
```suggestion
		}
		
		(void)memset(params, 0, sizeof(*params));
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c [hunk 19]
```diff
@@ -0,0 +1,194 @@
...
+		const struct bt_gatt_chrc *chrc = (struct bt_gatt_chrc *)attr->user_data;
+		const struct bt_uuid_16 ccc_uuid = BT_UUID_INIT_16(BT_UUID_GATT_CCC_VAL);
+
+		if (bt_uuid_cmp(chrc->uuid, BT_UUID_GATT_SC) == 0) {
+			int err;
+
+			LOG_DBG("found sc");
+			gatt_handles[SC] = chrc->value_handle;
+
+			params->uuid = &ccc_uuid.uuid;
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/central.c:99]: `ccc_uuid` is a local variable, but the `params` supplied to `bt_gatt_discover` should be valid until it completes, so suggest to make it a static

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/main.c [hunk 20]
```diff
@@ -0,0 +1,58 @@
...
+ * Copyright (c) 2023 Nordic Semiconductor ASA
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include "bstests.h"
+#include "bs_bt_utils.h"
+
+#define BS_SECONDS_TO_MS(dur_sec)    ((bs_time_t)dur_sec * USEC_PER_SEC)
+#define TEST_TIMEOUT_SIMULATED BS_SECONDS_TO_MS(60)
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/main.c:11]:
```suggestion
#define BS_SECONDS_TO_US(dur_sec)    ((bs_time_t)dur_sec * USEC_PER_SEC)
#define TEST_TIMEOUT_SIMULATED BS_SECONDS_TO_US(60)
```

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c [hunk 21]
```diff
@@ -0,0 +1,89 @@
...
+	/* add a new service to trigger the service changed indication */
+	err = bt_gatt_service_register(&svc);
+	BSIM_ASSERT(!err, "bt_gatt_service_register failed (%d)\n", err);
+	LOG_DBG("New service added");
+
+	start_adv(adv);
+	wait_connected();
+
+	/* wait so indication is sent */
+	k_sleep(K_SECONDS(10));
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c:86]: There's a callback for indications, so you could use that instead of waiting an arbitrary time.

You also don't need to wait at all, since you can PASS and return from this function without the application stops working

**Review by Thalley — CHANGES_REQUESTED** [review]

File: tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c (hunk 21 above)
Comment (theob-pro) [reply tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c:86]: > There's a callback for indications, so you could use that instead of waiting an arbitrary time.

We don't have access to the callback because the indication is triggered by the stack itself. I am not using `bt_indicate` and so I can't use a custom callback.

> You also don't need to wait at all, since you can PASS and return from this function without the application stops working

You're right, I'll remove the `k_sleep`.

Comment (Thalley) [reply tests/bsim/bluetooth/host/gatt/sc_indicate/src/peripheral.c]: > We don't have access to the callback because the indication is triggered by the stack itself. I am not using bt_indicate and so I can't use a custom callback.

Ah, right. Maybe we should add that as a GATT callback (i.e. add to `struct bt_gatt_cb`)?

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by demantmrrv — APPROVED** [review]
Verified code is reverted.

**Review by carlescufi — APPROVED** [review]
