### PR TITLE
posix + tests: correct timing functions to use CLOCK_REALTIME

### LINKED ISSUE #88587: posix: pthread: condition variables always wait on clock monotonic
**Describe the bug**

Two issues in one:

1. The [POSIX spec indicates](https://pubs.opengroup.org/onlinepubs/9799919799/functions/pthread_cond_clockwait.html) that the default clock used for condition variables should be `CLOCK_REALTIME`. However, Zephyr effectively [always uses](https://github.com/zephyrproject-rtos/zephyr/blob/8d6ab28ff772a1cb10b53b1db1902d9716edaa13/lib/posix/options/cond.c#L232) `CLOCK_MONOTONIC`.

2. Additionally, when a `pthread_condattr_t` is initialized as using any clock id, the clock id in that attribute is [ignored](https://github.com/zephyrproject-rtos/zephyr/blob/8d6ab28ff772a1cb10b53b1db1902d9716edaa13/lib/posix/options/cond.c#L171) in subsequent calls to `pthread_cond_timedwait()`.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? any
 - What have you tried to diagnose or workaround this issue? just inspeced the source
 - Is this a regression? No

**To Reproduce**

Can fill in later, if necessary. It's pretty evident from the source though.

**Expected behavior**
Should be able to specify which clock to use for `pthread_cond_timedwait()`, as long as `POSIX_CLOCK_SELECTION` is enabled.

**Impact**
This will throw conformant applications a bit of a curveball in terms of timing expectations.

**Logs and console output**

**Environment (please complete the following information):**

 - OS: any
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK v0.17.0
 - Commit SHA or Version used: d453fb94075c5d107f521f8a1ebaf85f3ead32d7

**Additional context**
Discovered in the context of https://github.com/zephyrproject-rtos/zephyr/pull/88547

### PR DESCRIPTION
**Pull request by cfriedt**
Use `CLOCK_REALTIME` by default as per the POSIX specification for the following functions:

* `mq_timedreceive()`
* `mq_timedsend()`
* `pthread_cond_timedwait()`
* `pthread_mutex_timedlock()`
* `pthread_rwlock_timedrdlock()`
* `pthread_rwlock_timedwrlock()`
* `sem_timedwait()`

and additionally for the following non-portable functions:

* `pthread_timedjoin_np()`

Fixes #88587

Should be merged after #88767 and #88769

### CODE REVIEW

**Comment by cfriedt** [comment]
An aside, I think it would be really useful to have an API call to perform common operations on `timespec` objects, sort of like https://github.com/solemnwarning/timespec, that additionally reports when an overflow has occurred.

That API and function signatures are good, but I would almost prefer if the entire implementation were in a header file, as static inlines, and additionally be able to use `__builtin_add_overflow()` and friends, as long as C11 was available.

https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html

**Review by ycsin — COMMENTED** [review]
Looks like there's some cleanup + code refactoring in the same commit, would it be possible to split this into smaller units?

**Comment by cfriedt** [comment]
> Looks like there's some cleanup + code refactoring in the same commit, would it be possible to split this into smaller units? 

It's not easy. There are a lot of dependencies. Little to do with cleanup, but all of it is required to get CLOCK_REALTIME as the default.

**Review by ycsin — DISMISSED** [review]

File: lib/posix/options/posix_clock.h [hunk 1]
```diff
@@ -1,19 +1,82 @@
...
-#include <zephyr/posix/posix_types.h>
+#include <zephyr/sys/__assert.h>
+#include <zephyr/sys_clock.h>
+#include <zephyr/sys/util.h>
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+static inline bool is_timespec_valid(const struct timespec *ts)
```
Comment (jukkar) [inline lib/posix/options/posix_clock.h:24]: Perhaps mark these with functions/macros below that are currently missing doxygen comments by `/** @cond INTERNAL_HIDDEN */`

Comment (cfriedt) [reply lib/posix/options/posix_clock.h]: Fixed!

**Comment by cfriedt** [comment]
* removed clever macro-based timespec functions due to compliance warnings 🫠

File: tests/posix/timers/src/clock.c [hunk 2]
```diff
@@ -29,35 +33,6 @@ static const bool settable[] = {
...
-	{                                                                                          \
-		return _tp_op(_a, _b, _op);                                                        \
-	}
-
-_decl_op(bool, tp_eq, ==);     /* a == b */
-_decl_op(bool, tp_lt, <);      /* a < b */
-_decl_op(bool, tp_gt, >);      /* a > b */
-_decl_op(bool, tp_le, <=);     /* a <= b */
-_decl_op(bool, tp_ge, >=);     /* a >= b */
-_decl_op(int64_t, tp_diff, -); /* a - b */
```
Comment (cfriedt) [inline tests/posix/timers/src/clock.c:50]: Had to remove these to avoid
```
MACRO_WITH_FLOW_CONTROL: Macros with flow control statements should be avoided
```

Comment (ycsin) [reply tests/posix/timers/src/clock.c:50]: some of these aren't in the `posix_clock.h` header file, causing the compilation error in CI

Comment (cfriedt) [reply tests/posix/timers/src/clock.c:50]: Fixed!

**Comment by cfriedt** [comment]
* replaced `tp_ge()` in `posix_clock.h`

**Review by ycsin — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

File: lib/posix/options/cond.c [hunk 3]
```diff
@@ -163,27 +170,39 @@ int pthread_cond_broadcast(pthread_cond_t *cvar)
...
+	}
+
+	return cond_wait(cv, mut, abstime);
 }
 
 int pthread_cond_init(pthread_cond_t *cvar, const pthread_condattr_t *att)
 {
-	struct k_condvar *cv;
+	struct posix_cond *cv;
+	struct posix_condattr *attr = (struct posix_condattr *)attr;
```
[the remark this answers is not in the document]
Comment (kartben) [reply lib/posix/options/cond.c:189]: #89076 :)
