### PR TITLE
drivers: net: loopback: Set interface name to lo

### LINKED ISSUE #89423: Network interface name for loopback interface is not proper
**Describe the bug**

The network interface name of the loopback interface is `dummy0` by default.

**Expected behavior**

It makes more sense if we name the loopback interface as `lo`. This is then also similar how Linux names the loopback interface.

**Impact**

It is more logical for the end user if the loopback interface name is set same way as in other OS.

### PR DESCRIPTION
**Pull request by jukkar**
Set the loopback interface name to "lo" instead of using the default "dummy0" as the former is a more appropriate.

Fixes #89423

### CODE REVIEW

File: drivers/net/loopback.c [hunk 1]
```diff
@@ -72,6 +72,15 @@ static void loopback_init(struct net_if *iface)
 			LOG_ERR("Failed to register IPv6 loopback address");
 		}
 	}
+
+	if (IS_ENABLED(CONFIG_NET_INTERFACE_NAME)) {
+		int ret;
+
+		ret = net_if_set_name(iface, "lo");
+		if (ret < 0) {
+			LOG_ERR("Failed to set loopback interface name");
```
Comment (pdgendt) [inline drivers/net/loopback.c:81]: I do prefer to have the error value alongside the message.

```suggestion
			LOG_ERR("Failed to set loopback interface name (%d)", ret);
```

**Review by pdgendt — APPROVED** [review]

**Comment by basmevissen** [comment]
Can this fix please also be applied to the v4.1-branch?

**Review by kartben — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
