### PR TITLE
samples: driver: watchdog: rework how callback support is handled

### LINKED ISSUE #29991: Watchdog Example not working as expected on a Nordic chip
In the [Watchdog Example](https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/drivers/watchdog/src/main.c) the example shows that it is possible to trigger a callback on a watchdog trigger before the hardwired watchdog action. The callback re-feeds the watchdog and prints a whole line to the log.

At least on a Nordic nrf52 chip, this does not work as shown in the example!

**Expected Outcome:**
The log shows the line "Handled things..ready to reset" before the device gets reset

**Seen Outcome:**
Only the first 1 character is shown: `A▒*** Booting Zephyr OS build zephyr-v2.4.0  ***`
(Note: Character 3 and later are already the next startup)

https://devzone.nordicsemi.com/f/nordic-q-a/38926/wdt-and-error-handler states the following:

> And when checking if the watchdog callback function is called, remember that this function is called two cycles of the 32 kHz clock before the reset is done, so it is a very little time to do something. 

This leads me to the conclusion, that the Watchdog Example (at least on a Nordic nRF52) does not work as expected!

**Suggestions:**
1. Add a note to the example indicating that this does not behave as expected on all devices
1. IMO the line `static bool handled_event;` should be changed to `static bool handled_event = false;` to make sure it does not have a random value!

### PR DESCRIPTION
**Pull request by pabigot**
Nordic watchdog does support a callback, but it has a time limit that is too tight for the way this sample uses it.  Add infrastructure to bypass using the callback in this sample.

Also add more diagnostics explaining the status of callback use in the sample.

Fixes #29991

### CODE REVIEW

**Comment by pabigot** [comment]
Output on Nordic now:
```
*** Booting Zephyr OS build v2.5.0-rc2-1-gadae83d98b40  ***                    
Watchdog sample application                                                     
Callback in RESET_SOC disabled for this platform                                
Feeding watchdog 5 times                                                        
Feeding watchdog...                                                             
Feeding watchdog...                                                             
Feeding watchdog...                                                             
Feeding watchdog...                                                             
Feeding watchdog...                                                             
Waiting for reset...                                                            
*** Booting Zephyr OS build v2.5.0-rc2-1-gadae83d98b40  *** 
....
````

**Review by nashif — APPROVED** [review]

**Comment by mnkp** [comment]
I will copy/paste my comment from the linked issue

> The current implementation of watchdog sample application is incorrect and violates original design of watchdog API. It is not possible to reliably support scenario when watchdog timeout triggers a callback and SoC reset at the same time. The watchdog API was not designed to be used this way.
>
> The scenario where watchdog timeout triggers a callback followed by SoC reset can only be supported in a reliable manner by a multistage watchdog. This requires dedicated hardware support and can be enabled by CONFIG_WDT_MULTISTAGE Kconfig option. In this case the first stage should be configured to trigger a callback, and the second stage to trigger SoC reset.
>
> Unfortunately, none of the existing drivers seems to implement support for multistage watchdog.

I believe that a proper way to fix the sample is to split the test in two testcases:
- watchdog timeout triggers a callback
- watchdog timeout triggers a SoC reset

None of the drivers supports CONFIG_WDT_MULTISTAGE Kconfig option, so for now we don't need to worry about the scenario where watchdog triggers a callback followed by SoC reset.

File: samples/drivers/watchdog/src/main.c [hunk 1]
```diff
@@ -88,12 +93,19 @@ void main(void)
 	wdt_config.window.min = 0U;
 	wdt_config.window.max = WDT_MAX_WINDOW;
 
+#if (WDT_DISABLE_CALLBACK - 0)
```
Comment (carlescufi) [inline samples/drivers/watchdog/src/main.c:96]: What's with the `- 0`?

Comment (pabigot) [reply samples/drivers/watchdog/src/main.c:96]: Avoids a syntax error when `WDT_DISABLE_CALLBACK` is undefined.

Comment (pabigot) [reply samples/drivers/watchdog/src/main.c:96]: The condition then expands to:

    #if - 0

which is false.

File: samples/drivers/watchdog/src/main.c [hunk 2]
```diff
@@ -88,12 +93,19 @@ void main(void)
...
+	printk("Callback in RESET_SOC disabled for this platform\n");
+	(void)wdt_callback;
```
Comment (anangl) [inline samples/drivers/watchdog/src/main.c:98]: `wdt_config.callback` is left uninitialized in this path, so it can contain some garbage from the stack and thus a callback may get executed but from some unexpected location. This may get unnoticed because the watchdog reset comes right after, but...
Perhaps it will be the safest to add the default initialization of `wdt_config` to `{0}`, as for `CONFIG_WDT_MULTISTAGE` the structure contains also the `next` field which is not used in this sample.

**Review by carlescufi — APPROVED** [review]

File: samples/drivers/watchdog/src/main.c (hunk 2 above)
Comment (pabigot) [reply samples/drivers/watchdog/src/main.c]: Absolutely correct; I didn't look closely enough at what this had been doing.

Switched to an initialization idiom that's more robust.  Also inverted the logic of the callback-support flag to be more clear.

**Review by anangl — APPROVED** [review]

**Comment by mnkp** [comment]
> Nordic watchdog does support a callback, but it has a time limit that is too tight for the way this sample uses it.

To put things into perspective. In the testcase user asks the driver via a watchdog API to execute a callback and reset the SoC at the specific time in the future if the watchdog is not fed. Both, execution of the callback and SoC reset are scheduled to happen at the same time. According to what we ask for it is the Nordic driver that behaves correctly since it does execute the callback and resets the SoC at about the same time. The other drivers misbehave.
