### PR TITLE
Change Led driver PCA9633 to enable the device at init

### LINKED ISSUE #37180: Led driver PCA9633 does nok take chip out from sleep
Hi

The Zephyr driver for PCA9633 does not set MODE1 register bit 4 on initialization resulting in the driver not working.

**To Reproduce**
1. Build example samples\drivers\led_pca9633 for NRF52840
2. Connect PCA9633 to i2c pins
3. Flash firmware with west flash
4. Observe output pins on PCA9633 not changing state.
5. on Zephyr shell run:
```
uart:~$ i2c read_byte I2C_0 0x60 0x00
Output: 0x11
uart:~$ i2c write_byte I2C_0 0x60 0x00 0x01
```
6. Observe output pins on PCA9633 changing state.

### PR DESCRIPTION
**Pull request by daniel-nicolai-hansten**
Update of LED Driver for PCA9633 to take the IC out from sleep at driver initialization.
Fixes #37180

### CODE REVIEW

File: drivers/led/pca9633.c [hunk 1]
```diff
@@ -184,7 +186,13 @@ static int pca9633_led_init(const struct device *dev)
...
 		return -EINVAL;
 	}
-
+	if (i2c_reg_update_byte(data->i2c, DT_INST_REG_ADDR(0),
+				PCA9633_MODE1,
+				PCA9633_MODE1_SLEEP,
+				~PCA9633_MODE1_SLEEP)) {
+		LOG_ERR("LED reg update failed");
+		return -EIO;
+	}
```
Comment (Mani-Sadhasivam) [inline drivers/led/pca9633.c:195]: new line

File: drivers/led/pca9633.c [hunk 2]
```diff
@@ -184,7 +186,13 @@ static int pca9633_led_init(const struct device *dev)
 		LOG_DBG("Failed to get I2C device");
 		return -EINVAL;
 	}
-
```
Comment (Mani-Sadhasivam) [inline drivers/led/pca9633.c:187]: Add a comment on what this register setting is doing. Like
`Turn Oscillator ON`

**Review by Mani-Sadhasivam — CHANGES_REQUESTED** [review]
Please add a proper commit subject and description. The `Fixes` tag could be added to the commit description itself.

**Comment by gmarull** [comment]
Thanks for this fix, please, format commit message correctly, e.g. `drivers: led: pca9633: exit sleep mode on init` and add a description of the problem (see https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines)

**Comment by daniel-nicolai-hansten** [comment]
> Thanks for this fix, please, format commit message correctly, e.g. `drivers: led: pca9633: exit sleep mode on init` and add a description of the problem (see https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines)

Done

**Comment by daniel-nicolai-hansten** [comment]
> 
> 
> > Thanks for this fix, please, format commit message correctly, e.g. `drivers: led: pca9633: exit sleep mode on init` and add a description of the problem (see https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines)
> 
> Done

I think the sign off message are correct now. Please rerun the checks

**Comment by daniel-nicolai-hansten** [comment]
> 
> 
> > > Thanks for this fix, please, format commit message correctly, e.g. `drivers: led: pca9633: exit sleep mode on init` and add a description of the problem (see https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines)
> > 
> > 
> > Done
> 
> I think the sign off message are correct now. Please rerun the checks

I have now fixed the Autor formatting in my git. Please rerun the checks

**Comment by daniel-nicolai-hansten** [comment]
> 
> 
> > > > Thanks for this fix, please, format commit message correctly, e.g. `drivers: led: pca9633: exit sleep mode on init` and add a description of the problem (see https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines)
> > > 
> > > 
> > > Done
> > 
> > 
> > I think the sign off message are correct now. Please rerun the checks
> 
> I have now fixed the Autor formatting in my git. Please rerun the checks

Added body to commit message and leaving line 2 blank.

**Review by gmarull — APPROVED** [review]

**Review by Mani-Sadhasivam — APPROVED** [review]
