### PR TITLE
Bluetooth: BAP: Shell: Add BASS service data to ext-adv

### LINKED ISSUE #70834: LE Audio: BAP shell not setting the BASS service data
**Describe the bug**
As per the BAP spec, the scan delegator device should add the BASS service data in the extended advertising data when it requests a broadcast assistant to scan for it. For testing purposes that's usually (always?) the case with the shell, and we should populate the extended advertising data with the BASS service data. 

**To Reproduce**
N/A

**Expected behavior**
The behavior of `audio_ad_data_add` should add the BASS service data when appropriate. 

**Impact**
Very minor

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 98aa10d6eab8df6938c0dc949bd12bc244bb52e1

**Additional context**
image

### PR DESCRIPTION
**Pull request by niym-ot**
As per the BAP spec, the scan delegator device should add the BASS service data in the extended advertising data when it requests a broadcast assistant to scan for it. For testing purposes that's usually the case with the shell, extended advertising data shall be populated with the BASS service data.

Fixes #70834

### CODE REVIEW

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/shell/bap.c [hunk 1]
```diff
@@ -3876,6 +3876,11 @@ static ssize_t connectable_ad_data_add(struct bt_data *data_array,
 		ad_len++;
 	}
 
+	if (IS_ENABLED(CONFIG_BT_BAP_SCAN_DELEGATOR)) {
+		ad_len += bap_scan_delegator_ad_data_add(&data_array[ad_len],
+								data_array_size - ad_len);
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap.c:3881]: Indentation is off

```suggestion
		ad_len += bap_scan_delegator_ad_data_add(&data_array[ad_len],
							 data_array_size - ad_len);
```

**Review by Thalley — CHANGES_REQUESTED** [review]
Minor comment, otherwise LGTM

**Review by Thalley — APPROVED** [review]

**Review by larsgk — APPROVED** [review]
