### PR TITLE
drivers: eth_mcux: event corrected init->reset

### LINKED ISSUE #16089: Mcux Ethernet driver does not detect carrier anymore (it's alway on)
**Describe the bug**
Mcux Ethernet driver used to be able to detect carrier state, but something somewhere has changed and it thinks the carrier is always on now.

**To Reproduce**
Do not plug the Ethernet cable to your device
Use samples/net/sockets/echo_client

1. mkdir build; cd build
2. Change the prj.conf so it becomes:
```CONFIG_NET_CONFIG_SETTINGS=y
#CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::2"
#CONFIG_NET_CONFIG_PEER_IPV6_ADDR="2001:db8::1"
#CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.2"
#CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.1"
CONFIG_NET_DHCPV4=y
CONFIG_NET_L2_ETHERNET_MGMT=y
CONFIG_NET_MGMT_EVENT_LOG_LEVEL_DBG=y
CONFIG_NET_DHCPV4_LOG_LEVEL_DBG=y
```
3. cmake -DBOARD=board\frdm_k64f
4. make
5. Dhcp starts right away to send discover
6. Plug the Ethernet cable: no changes. Eventually the discover timeout will restart and dhcp will be successful but that's the wrong behavior: it should receive a if_up net_mgmt event then starts dhcp discover.

**Expected behavior**
Carrier on/off (and thus net if up/down state) should be detected

**Impact**
Unable to test properly code that rely on carrier off/on and net if up/down events on that device.

### PR DESCRIPTION
**Pull request by agansari**
Fixes #16089

Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>

### CODE REVIEW

File: drivers/ethernet/eth_mcux.c [hunk 1]
```diff
@@ -913,6 +916,9 @@ static void eth_iface_init(struct net_if *iface)
 	context->iface = iface;
 
 	ethernet_init(iface);
+	net_eth_carrier_off(iface);
```
Comment (jukkar) [inline drivers/ethernet/eth_mcux.c]: Might be easier to just call `net_if_flag_set(iface, NET_IF_NO_AUTO_START);` here so that the network interface init does not take the interface up in the first place.

**Comment by agansari** [comment]
@jukka made the change you requested, can you have another look?

**Review by jukkar — APPROVED** [review]
LGTM

**Comment by ioannisg** [comment]
@tbursztyka could you check if this patch fixes the bug you reported in #16089 ?

**Review by pfalcon — APPROVED** [review]

**Comment by pfalcon** [comment]
Ping @jukkar, hopefully this can be merged.

**Comment by ioannisg** [comment]
> 
> 
> Ping @jukkar, hopefully this can be merged.

Waiting for @tbursztyka to report back

**Comment by pfalcon** [comment]
> Waiting for @tbursztyka to report back

Well, that's nice to see if this patch really "Fixes #16089", or it should be reopened. It's the review-approved patch from the driver maintainer otherwise, so...

**Review by tbursztyka — APPROVED** [review]
seems to work properly yes

**Comment by pfalcon** [comment]
I also tested this on a board. With master 06a79cc82ef83df70d33ca19a6c84f746865481f, the Ethernet communication works for me - pings, dumb_http_server sample, that's probably why I didn't notice any issue with this, - but I indeed don't see messages like `[00:00:12.001,000] <inf> eth_mcux: Enabled 100M full-duplex mode.` from the driver, like it was (months) before.

With the above master + this patch, the messages are there:

~~~
[00:03:21.020,000] <inf> eth_mcux: Enabled 100M full-duplex mode.
Connection #110 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #111 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #112 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #113 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #114 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #115 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #116 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #117 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #118 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #119 from 192.0.2.2
Connection from 192.0.2.2 closed
[00:03:32.021,000] <inf> eth_mcux: Link down
~~~

(Me connecting and disconnecting the cable.)

**Comment by pfalcon** [comment]
Thanks for fixing it, @agansari !

**Comment by ioannisg** [comment]
> 
> 
> Thanks for fixing it, @agansari !

and thanks @tbursztyka @pfalcon for testing this

**Comment by ioannisg** [comment]
@jukkar @pfalcon does tnis need to be back-ported to 1.14.1? If so, please, add label.

**Comment by agansari** [comment]
@ioannisg i added the label, it should be back-ported
