### PR TITLE
sockets: getaddrinfo: Fix possible crash when callback is delayed

### LINKED ISSUE #39242: net: sockets: Zephyr Fatal in dns_resolve_cb if dns request was attempted in offline state
**Describe the bug**

In case if dns resolving was attempted in offline state,
going back online triggers Zephyr Fatal.

Source of the crash:
subsys\net\lib\sockets\getaddrinfo.c

The reason is that `dns_resolve_cb` tries to give semaphore which doesn't exist anymore.
Error lifecycle:
- `z_impl_z_zsock_getaddrinfo_internal ` creates semaphore as part of `struct getaddrinfo_state ai_state;`
- it waits for the semaphore: `k_sem_take(&ai_state.sem, K_MSEC(CONFIG_NET_SOCKETS_DNS_TIMEOUT + 100));`
- if semaphore was not given, it returns: `if (ret == -EAGAIN) {return DNS_EAI_AGAIN;}`, thus deallocating the semaphore
- we are back online (e.g. wifi network is back up, cable plugged, etc.), and thread rx_q eventually calls `dns_resolve_cb`
- `dns_resolve_cb` tries to give the semaphore:  `k_sem_give(&state->sem);`. But it doesn't exist anymore. ZEPHYR FATAL.

**To Reproduce**
1. Any platform with network connectivity 
2. Call zsock_getaddrinfo when the internet is not present.
3. After  K_MSEC(CONFIG_NET_SOCKETS_DNS_TIMEOUT + 100) get back online (platform-depedent)

**Expected behavior**
No crash occurs.

**Impact**
It is showstopper, because there can be many reasons for network disconnects and business logic doesn't have to check low-level connection state (loose coupling).

Imagine if your PC goes offline (e.g. wi-fi network down), meanwhie you attempt to make a `git push`. Or send an e-mail.
Then you go back online and enjoy BSOD.

**Logs and console output**
```
[00:00:14.225,128] <err> os: ***** HARD FAULT *****
[00:00:14.231,018] <err> os:   Fault escalation (see below)
[00:00:14.237,609] <err> os: ***** BUS FAULT *****
[00:00:14.243,408] <err> os:   Precise data bus error
[00:00:14.249,481] <err> os:   BFAR Address: 0x6174626f
[00:00:14.255,798] <err> os: r0/a1:  0x64656e69  r1/a2:  0x0006a504  r2/a3:  0x6174626f
[00:00:14.265,045] <err> os: r3/a4:  0x20746f4e r12/ip:  0x000000fe r14/lr:  0x000659d3 
[00:00:14.274,261] <err> os:  xpsr:  0x21000000
[00:00:14.279,846] <err> os: Faulting instruction address (r15/pc): 0x000657a6
[00:00:14.288,208] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:14.296,478] <err> os: Current thread: 0x20016018 (rx_q[0])
[00:00:14.308,715] <err> os: Halting system
```
**Environment (please complete the following information):**
Interestingly enough, faulting instruction resolves to zephyr/include/sys/dlist.h:513 (with addr2line tool), and 
r14/lr:  0x000659d3  to kernel/include/ksched.h:167
Probably because scheduler crashes on an attempt to access some random address as semaphore.

**Additional context**
Minimalistic and most robust fix would be to make structure with semaphore static, e.g.
in `z_impl_z_zsock_getaddrinfo_internal`:
`static struct getaddrinfo_state ai_state;`

### PR DESCRIPTION
**Pull request by rlubos**
In case system workqueue processing is delayed for any reason, and
resolver callback is exectued after `getaddrinfo()` call already timed
out, the system would crash as the callback makes use of the user data
allocated on a stack within `getaddrinfo()` funtcion.

Prevent that, by cancelling the DNS request explicitly from the
`getaddrinfo()` context, therefore preventing the resolver callback
from being executed after the `getaddrinfo()` call ends.

Fixes #39242

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
CC @AndreyDodonov-EH

File: subsys/net/lib/sockets/getaddrinfo.c [hunk 1]
```diff
@@ -51,6 +51,7 @@ struct getaddrinfo_state {
 	int status;
 	uint16_t idx;
 	uint16_t port;
+	uint16_t dns_id;
```
Comment (pdgendt) [inline subsys/net/lib/sockets/getaddrinfo.c:54]: Should this value be set to a default value in `z_impl_z_zsock_getaddrinfo_internal`?

**Review by pdgendt — APPROVED** [review]
One question, but non-blocking.

Also small nit: there are some typos in the commit message

File: subsys/net/lib/sockets/getaddrinfo.c [hunk 2]
```diff
@@ -51,6 +51,7 @@ struct getaddrinfo_state {
 	int status;
```
Comment (jukkar) [inline subsys/net/lib/sockets/getaddrinfo.c:51]: Please add `net: ` prefix to commit subject. Also I don't think it is needed to put back-ticks \` to commit message.

**Review by jukkar — COMMENTED** [review]
Looks ok, minor nits to commit msg.

File: subsys/net/lib/sockets/getaddrinfo.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/lib/sockets/getaddrinfo.c:54]: I can set this to 0, I see that's what the resolver module does in case of failure.

File: subsys/net/lib/sockets/getaddrinfo.c (hunk 2 above)
Comment (rlubos) [reply subsys/net/lib/sockets/getaddrinfo.c:51]: Thanks, I've updated the commit message.

Comment (pdgendt) [reply subsys/net/lib/sockets/getaddrinfo.c:51]: Still a typo in "exectued"

**Review by jukkar — APPROVED** [review]
