### PR TITLE
ARM: only allow OOPS and STACK_CHK_FAIL from user mode

### LINKED ISSUE #17591: ARM: z_arch_except() is too permissive in user mode
Steps to reproduce:

Pull #17589
And run tests/kernel/mem_protect/userspace
All cases need to succeed.

Right now, ARM will accept *any* reason code.
It should only accept kernel oops, or stack check fail. Other codes should be forced into an oops.

Impact: user mode is able to induce kernel panics, which indicate the entire system needs to be halted. user mode is also able to fake other exception types.

### PR DESCRIPTION
**Pull request by ioannisg**
Fixes #17591 

Includes @andrewboie 's commit that implements the respective test (for feature coverage).

Currently implemented for ARM (but an x86 fix is also present in #17587, AFAICS, so that commit could also be added here.)

Update: #17587 is merged, so this should already work for x86 as well.

### CODE REVIEW

**Comment by ioannisg** [comment]
Not sure if we want to back-port this @andrewboie

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 1]
```diff
@@ -1171,6 +1205,13 @@ void test_main(void)
 			 ztest_unit_test(test_stack_buffer),
 			 ztest_user_unit_test(test_unimplemented_syscall),
 			 ztest_user_unit_test(test_bad_syscall),
+#if defined(CONFIG_ARM) || defined(CONFIG_X86)
```
Comment (andrewboie) [inline tests/kernel/mem_protect/userspace/src/main.c]: eh, put an #ifndef CONFIG_ARC and leave a comment /* FIXME: #17590 */

**Review by tyrantlizard77 — COMMENTED** [review]
ARM changes look fine.
Would like the ifdef in the test changed to exclude ARC

**Comment by andrewboie** [comment]
> Not sure if we want to back-port this @andrewboie

Yeah we probably should, as the bug is more serious on ARM than on x86.

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 1 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: Fixed

**Comment by ioannisg** [comment]
> ARM changes look fine.
> Would like the ifdef in the test changed to exclude ARC

@andrewboie pls, review the revised version.

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 2]
```diff
@@ -1119,6 +1119,40 @@ void test_object_recycle(void)
 	zassert_true(perms_count == 1, "invalid number of thread permissions");
 }
 
+#if !defined(CONFIG_ARC) /* FIXME: #17590 */
```
Comment (andrewboie) [inline tests/kernel/mem_protect/userspace/src/main.c]: these functions aren't static so strictly speaking you don't need to ifdef around !CONFIG_ARC

**Review by tyrantlizard77 — APPROVED** [review]

File: tests/kernel/mem_protect/userspace/src/main.c (hunk 2 above)
Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: sure

**Review by tyrantlizard77 — APPROVED** [review]

File: tests/kernel/mem_protect/userspace/src/main.c [hunk 3]
```diff
@@ -1171,6 +1202,13 @@ void test_main(void)
 			 ztest_unit_test(test_stack_buffer),
 			 ztest_user_unit_test(test_unimplemented_syscall),
 			 ztest_user_unit_test(test_bad_syscall),
+#if !defined(CONFIG_ARC) /* FIXME: #17590 */
```
Comment (yashi) [inline tests/kernel/mem_protect/userspace/src/main.c]: I don't think you can do this because `ztest_test_suite()` itself is a defined macro.  You get: 
```
.../tests/kernel/mem_protect/userspace/./src/main.c: found invalid #endif in ztest_test_suite()
```
 when you run `./scripts/sanitycheck -vvv -p qemu_cortex_m3 -T tests/kernel/mem_protect/userspace`

Comment (ioannisg) [reply tests/kernel/mem_protect/userspace/src/main.c]: right @yashi , this was overlooked, and spotted, later, also by @andrewboie .- I'll try to work on a quick fix

Comment (andrewboie) [reply tests/kernel/mem_protect/userspace/src/main.c]: I don't know why this check exists, to be honest
