### PR TITLE
ARC: Check that ISR and exception stacks are proper aligned

### LINKED ISSUE #37704: hello world doesn't work on qemu_arc_em when CONFIG_ISR_STACK_SIZE=1048510
**Describe the bug**
hello world sample doesn't work on qemu_arc_em when CONFIG_ISR_STACK_SIZE=1048510

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=qemu_arc_em -DCONFIG_ISR_STACK_SIZE=1048510 ..
3. make run

### PR DESCRIPTION
**Pull request by evgeniy-paltsev**
`CONFIG_ISR_STACK_SIZE` and `CONFIG_ARC_EXCEPTION_STACK_SIZE` are used in arc asembler code without C wrapper on them with following manner:

```
#define INIT_STACK z_interrupt_stacks
#define INIT_STACK_SIZE CONFIG_ISR_STACK_SIZE

	mov_s sp, INIT_STACK
	add sp, sp, INIT_STACK_SIZE
```

In result we can get stack unaligned if we have `CONFIG_ISR_STACK_SIZE` or `CONFIG_ARC_EXCEPTION_STACK_SIZE`
values unaligned. 

There is no point to have unaligned stack size - so let's check against such configurations in compile time.

Fixes: #37704

### CODE REVIEW

File: include/zephyr/arch/arc/arch.h [hunk 1]
```diff
@@ -89,6 +89,14 @@ extern "C" {
 #define ARCH_STACK_PTR_ALIGN	4
 #endif /* CONFIG_64BIT */
 
+#if CONFIG_ISR_STACK_SIZE % ARCH_STACK_PTR_ALIGN
```
Comment (stephanosio) [inline include/zephyr/arch/arc/arch.h:92]: FWIW, there is `BUILD_ASSERT` for this.

Comment (evgeniy-paltsev) [reply include/zephyr/arch/arc/arch.h]: Yep, the `BUILD_ASSERT` was disabled for MWDT toolchain previously - that's why we've used `#error` directive arch.h for that. But it's enabled now, so we can use it.

Changed for `BUILD_ASSERT` usage.

**Review by ruuddw — APPROVED** [review]

**Review by abrodkin — APPROVED** [review]
