### PR TITLE
zms: add more robustiness in extreme cases

### LINKED ISSUE #84874: ZMS power cut corner case causing cycle count to wrap around and sector to be interpreted as a closed one
**Describe the bug**
Consider a ZMS fs with > 2 sectors.
Assume sectors 0, 1 are closed, 2 is open and 3 is empty.
If sector 2 gets closed, garbage collection is initiated, moving items from sector 0 to sector 3. Assume a power cut happens during the move of items.

During re-initialization at the next boot, GC will be restarted. Before items are starting to be moved, the cycle count of sector 2 is incremented modulo 256.

Assume power cuts continue to happen during the GC is in progress 256 times in a row. At that time, the cycle count will eventually have wrapped around and now be equal to the cycle count of the close ATE, which now indicates that this is a valid closed sector instead of an empty one. That means all sectors will be marked as closed the next time the ZMS is initialized and thus cause corruption.

Suggested fix: in `zms_add_empty_ate`, make sure that the cycle counter that is to be written is not equal to whatever value is currently in the close ATE slot.

In fact, I don't really see right now why 256 different values are needed. It seems that 2 values (0 or 1) would be enough, and every `zms_add_empty_ate` could simply set to the cycle counter to the opposite of the one present in the close ATE.

**To Reproduce**
Initialize a system as above, set breakpoints in the flash_write function to be able to easily cut power when appropriate and perform the mentioned steps.

**Expected behavior**
Memory should not become corrupt.

**Impact**
The memory becomes corrupt.

**Logs and console output**
N/A

**Environment (please complete the following information):**
- OS: N/A
- Toolchain: N/A
- Commit SHA or Version used: 87f11d7efac17c279e7cf19f03f0f0e85173b628

**Additional context**
N/A

@rghaddab

### PR DESCRIPTION
**Pull request by rghaddab**
When power cuts during a GC operation the sector is erased again in the next reboot cycle and the cycle_cnt of the empty ATE is incremented. If the same power cut happens 255 times in a row the empty ATE cycle_cnt will become equal to the close ATE which causes a memory corruption. Fix this by checking the close ATE cycle_cnt before incrementing the empty ATE cycle_cnt.

Fixes: #84874

### CODE REVIEW

File: subsys/fs/zms/zms.c [hunk 1]
```diff
@@ -723,6 +723,40 @@ static int zms_add_gc_done_ate(struct zms_fs *fs)
...
+ */
+static inline int zms_verify_and_increment_cycle_cnt(struct zms_fs *fs, uint64_t addr,
+						     uint8_t *cycle_cnt)
+{
+	int rc;
+	uint64_t close_addr;
+	struct zms_ate close_ate;
+
+	close_addr = zms_close_ate_addr(fs, addr);
+	/* read the second ate in the sector to get the close ATE */
```
Comment (nordicjm) [inline subsys/fs/zms/zms.c:743]: Capitalise first letter of comments (i.e. all comments)

**Review by nordicjm — DISMISSED** [review]

File: subsys/fs/zms/zms.c [hunk 2]
```diff
@@ -723,6 +723,40 @@ static int zms_add_gc_done_ate(struct zms_fs *fs)
 	return zms_flash_ate_wrt(fs, &gc_done_ate);
 }
 
+/* This function verifies that the cycle_cnt of the close ATE will not be equal
+ * to the cycle_cnt of the empty ATE after incrementing it.
+ * This is possible only in these extreme conditions:
+ * 1- A Garbage collection operation is interrupted due to a power cut
+ * 2- When rebooting the sector is erased (cycle_cnt incremented)
```
Comment (Emill) [inline subsys/fs/zms/zms.c:730]: Should be a comma after "When rebooting".

Comment (Emill) [inline subsys/fs/zms/zms.c:730]: Should be a comma after "When rebooting".

File: subsys/fs/zms/zms.c [hunk 3]
```diff
@@ -723,6 +723,40 @@ static int zms_add_gc_done_ate(struct zms_fs *fs)
...
+ * 3- Garbage collection restarts again and got interrupted again by a power cut
+ * 4- Steps [1..3] occurred 255 times in a row
```
Comment (Emill) [inline subsys/fs/zms/zms.c:732]: Steps [2..3] instead of [1..3].

**Review by Emill — APPROVED** [review]
The code seems to solve the problem now!

**Review by Emill — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
