### PR TITLE
drivers: sensor: lis2dh: make the driver multi-instance

### LINKED ISSUE #27753: drivers: sensor: lis2dh: compilation issue struct lis2dh_config' has no member named 'spi_conf'
**Describe the bug**
While pushing PR #27013,  Buildkite highlight a compilation issue in lis2dh.

Note: Even if issue is not directly linked to the PR #27013,
the PR highlight this issue because it enabled adc for stm32f3_disco, which is a condition (depends on) for sanitycheck 
 to compile for this board.

**To Reproduce**
1. west build -p auto -b stm32f3_disco tests/drivers/build_all/ -- -DCONF_FILE=sensors_trigger_i_z.conf
2. See error

**Expected behavior**
Compilation successful.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
```
FAILED: zephyr/drivers/sensor/lis2dh/CMakeFiles/drivers__sensor__lis2dh.dir/lis2dh_spi.c.obj
C:\gnuarmemb\bin\arm-none-eabi-gcc.exe -DBUILD_VERSION=zephyr-v2.3.0-2029-g5449436515cd -DCORE_CM4 -DHSE_VALUE=8000000 -DKERNEL -DSTM32F303xC -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D_FORTIFY_SOURCE=2 -D__PROGRAM_START -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I../include -Izephyr/include/generated -I../soc/arm/st_stm32/stm32f3 -I../drivers -I../soc/arm/st_stm32/common -I../subsys/testsuite/include -IC:/zephyr/zephyr_project/modules/hal/cmsis/CMSIS/Core/Include -IC:/zephyr/zephyr_project/modules/hal/st/sensor/stmemsc/iis3dhhc_STdC/driver -IC:/zephyr/zephyr_project/modules/hal/st/sensor/stmemsc/lis2mdl_STdC/driver -IC:/zephyr/zephyr_project/modules/hal/st/sensor/stmemsc/lsm6dso_STdC/driver -IC:/zephyr/zephyr_project/modules/hal/stm32/stm32cube/stm32f3xx/soc -IC:/zephyr/zephyr_project/modules/hal/stm32/stm32cube/stm32f3xx/drivers/include -IC:/zephyr/zephyr_project/modules/hal/stm32/stm32cube/stm32f3xx/drivers/include/Legacy -isystem ../lib/libc/minimal/include -isystem c:/gnuarmemb/bin/../lib/gcc/arm-none-eabi/9.2.1/include -isystem c:/gnuarmemb/bin/../lib/gcc/arm-none-eabi/9.2.1/include-fixed -Os -imacrosC:/zephyr/zephyr_project/zephyr/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -imacrosC:/zephyr/zephyr_project/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-address-of-packed-member -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=C:/zephyr/zephyr_project/zephyr/tests/drivers/build_all=CMAKE_SOURCE_DIR -fmacro-prefix-map=C:/zephyr/zephyr_project/zephyr=ZEPHYR_BASE -fmacro-prefix-map=C:/zephyr/zephyr_project=WEST_TOPDIR -ffunction-sections -fdata-sections -std=c99 -nostdinc -MD -MT zephyr/drivers/sensor/lis2dh/CMakeFiles/drivers__sensor__lis2dh.dir/lis2dh_spi.c.obj -MF zephyr\drivers\sensor\lis2dh\CMakeFiles\drivers__sensor__lis2dh.dir\lis2dh_spi.c.obj.d -o zephyr/drivers/sensor/lis2dh/CMakeFiles/drivers__sensor__lis2dh.dir/lis2dh_spi.c.obj   -c C:/zephyr/zephyr_project/zephyr/drivers/sensor/lis2dh/lis2dh_spi.c
C:/zephyr/zephyr_project/zephyr/drivers/sensor/lis2dh/lis2dh_spi.c: In function 'lis2dh_raw_read':
C:/zephyr/zephyr_project/zephyr/drivers/sensor/lis2dh/lis2dh_spi.c:26:41: error: 'const struct lis2dh_config' has no member named 'spi_conf'
   26 |  const struct spi_config *spi_cfg = &cfg->spi_conf;
      |                                         ^~
C:/zephyr/zephyr_project/zephyr/drivers/sensor/lis2dh/lis2dh_spi.c: In function 'lis2dh_raw_write':
C:/zephyr/zephyr_project/zephyr/drivers/sensor/lis2dh/lis2dh_spi.c:72:41: error: 'const struct lis2dh_config' has no member named 'spi_conf'
   72 |  const struct spi_config *spi_cfg = &cfg->spi_conf;
```

**Environment (please complete the following information):**
 - OS:  Windows
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA: 5449436515cd2098abeeda3bb22ff6b88ae0c384

**1st Analysist**
In file lis2dh.h, the member `spi_conf ` of struct `lis2dh_config` is defined under compilation switch.
And it is defined only if sensor is okay in spi DT node, but only if sensor is not okay in i2c DT node.
```
struct lis2dh_config {
	char *bus_name;
	int (*bus_init)(struct device *dev);
#if DT_ANY_INST_ON_BUS_STATUS_OKAY(i2c)
	uint16_t i2c_slv_addr;
#elif DT_ANY_INST_ON_BUS_STATUS_OKAY(spi)
	struct spi_config spi_conf;
#if DT_INST_SPI_DEV_HAS_CS_GPIOS(0)
	const char *gpio_cs_port;
	uint8_t cs_gpio;
	uint8_t cs_gpio_flags;
#endif /* DT_INST_SPI_DEV_HAS_CS_GPIOS(0) */
#endif /* DT_ANY_INST_ON_BUS_STATUS_OKAY(spi) */

};
```

Is it allowed to have 2 sensors, one on i2c the other on spi ? 
Whatever, in stm32f3_disco board, there is a sensor defined in i2c DT node.
Thus it fails when compilling spi source:  lis2dh/lis2dh_spi.c

Maybe in such case both `i2c_slv_addr` and `spi_conf` should be defined at the same time ?
like that:
```
struct lis2dh_config {
	char *bus_name;
	int (*bus_init)(struct device *dev);
#if DT_ANY_INST_ON_BUS_STATUS_OKAY(i2c)
	uint16_t i2c_slv_addr;
#endif /* DT_ANY_INST_ON_BUS_STATUS_OKAY(i2c) */
#if DT_ANY_INST_ON_BUS_STATUS_OKAY(spi)
	struct spi_config spi_conf;
```
This at least solve the compilation issue.

### PR DESCRIPTION
**Pull request by avisconti**
Make this driver multi-instance and use the new API.
Fixes #27753.

Tested on x_nucleo_iks01a3 shield for both I2C and SPI. I used two different shields where the DIL24 was configured for I2C (first shield) and SPI (second shield).

### CODE REVIEW

**Review by MaureenHelm — APPROVED** [review]

**Review by ABOSTM — APPROVED** [review]
I am not sure to be of a great help for the review of this driver, but I tested the patch and it solves my compilation issue.
LGTM

File: drivers/sensor/lis2dh/lis2dh.h [hunk 1]
```diff
@@ -202,13 +197,11 @@ struct lis2dh_config {
...
+
+#if DT_ANY_INST_ON_BUS_STATUS_OKAY(spi)
 	struct spi_config spi_conf;
-#if DT_INST_SPI_DEV_HAS_CS_GPIOS(0)
-	const char *gpio_cs_port;
-	uint8_t cs_gpio;
-	uint8_t cs_gpio_flags;
-#endif /* DT_INST_SPI_DEV_HAS_CS_GPIOS(0) */
+	const char *cs_gpios_label;
 #endif /* DT_ANY_INST_ON_BUS_STATUS_OKAY(spi) */
```
Comment (mbolivar-nordic) [inline drivers/sensor/lis2dh/lis2dh.h:205]: It would save a bit of flash to put the I2C and SPI configuration in a union since the device can only be supported on one bus at a time, but it's not a big deal.

**Review by mbolivar-nordic — APPROVED** [review]

File: drivers/sensor/lis2dh/lis2dh.h (hunk 1 above)
Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh.h:205]: Yes, correct. I changed topic right now and I do not have time to retest both i2c and spi (it is a must for me the re-testing). But I have in plan to add multi-instance to at least the newer ST sensor we support in zephyr. For those I will for sure take into account your good suggestion! Thanks!

File: drivers/sensor/lis2dh/lis2dh.h [hunk 2]
```diff
@@ -15,27 +15,22 @@
 #include <drivers/sensor.h>
 #include <string.h>
 
-#define LIS2DH_BUS_ADDRESS		DT_INST_REG_ADDR(0)
-#define LIS2DH_BUS_DEV_NAME		DT_INST_BUS_LABEL(0)
+#define DT_DRV_COMPAT st_lis2dh
```
Comment (ifillonneau) [inline drivers/sensor/lis2dh/lis2dh.h:18]: Is it adviced to set DT_DRV_COMPAT in header file?
I already have some issues trying to set it in some header files so I am wondering it is a correct manner to do.

Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh.h:18]: Well, actually before it was in the spi and i2c sensor driver .c file, but I moved it in .h as it is common to both. But it is a valid point. It seems I'm the only one to define it in a header file. I can move it back to the .c files.
@mbolivar-nordic any feedback here?

Comment (carlescufi) [reply drivers/sensor/lis2dh/lis2dh.h:18]: I don't think it's a good idea in general to have it in a header file because you likely want that macro defined only for the particular .c file where you are using DT macros. You could also surround it with `#ifndef DT_DRV_COMPAT` I guess, but I personally think it's cleaner to move it to the .c file, although I will defer to @mbolivar-nordic.

Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh.h:18]: @carlescufi 
OK, clear! I'll do a quick change right now!
I will also incorporate the change requested by @mbolivar-nordic here above

**Comment by avisconti** [comment]
Incorporated all suggestions, re-tested and re-pushed.
Thanks!

File: drivers/sensor/lis2dh/lis2dh.h (hunk 1 above)
Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh.h]: Incorporated this change in new push

File: drivers/sensor/lis2dh/lis2dh.h (hunk 2 above)
Comment (mbolivar-nordic) [reply drivers/sensor/lis2dh/lis2dh.h]: > Is it adviced to set DT_DRV_COMPAT in header file?

Looks like this is just an internal header used as shared code by the driver implementation, so I don't think there's any reason not to define DT_DRV_COMPAT here. There is no policy for or against this that I am aware of.

**Review by mbolivar-nordic — APPROVED** [review]
My comments are addressed :+1:
