### PR TITLE
drivers: usb: udc: add Smartbond UDC driver

### LINKED ISSUE #74662: drivers: usb: Port `usb_dc_smartbond` to `UDC API`
In order for the `USB_DEVICE_STACK_NEXT` to become the default, existing USB device drivers must be ported to it.
See #42066 for additional details.

Note that if this driver is not ported by Zephyr 4.0.0, this hardware will not work with the default USB stack in 4.0.0.

Example ports:
- udc_kinetis and udc_nrf PR #38679
- udc_it82xx2 PR #65792
- udc_dwc2 PR  #64943
- udc_stm32 PR #53408
- udc_mcux PR #70401

Skeleton file to use as a starting point:
https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/usb/udc/udc_skeleton.c

Documentation:
https://docs.zephyrproject.org/latest/connectivity/usb/device_next/usb_device.html
https://docs.zephyrproject.org/latest/connectivity/usb/device_next/api/index.html

### PR DESCRIPTION
**Pull request by kasjer**
Code adds USB UDC driver for Smartbond device.

Code was NOT tested with ISO endpoints yet.
It was tested with console, mass, and cdc_acm applications

Additionally small fix in DMA power management was needed.

Function dma_smartbond_set_channel_status() used incorrect
condition to release state lock.
In initialization function dma_smartbond_init() function
dma_smartbond_set_channel_status() was called for each DMA
channel and tried to release lock that was never taken.

Fixes #74662 

Signed-off-by: Jerzy Kasenberg <jerzy.kasenberg@codecoup.pl>

### CODE REVIEW

File: drivers/usb/udc/udc_smartbond.c [hunk 1]
```diff
@@ -0,0 +1,1784 @@
...
+	const uint16_t mps = 1023;
+	int err;
+
+	dev_state->dev = dev;
+
+	/*
+	 * You do not need to initialize it if your driver does not use
+	 * udc_lock_internal() / udc_unlock_internal(), but implements its
+	 * own mechanism.
+	 */
```
Comment (tmon-nordic) [inline drivers/usb/udc/udc_smartbond.c:1664]: Looks like stale template comment that should be removed.

Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: comment removed

**Comment by ydamigos** [comment]
Please add  `usbd` as supported peripheral in DA1469x boards' yaml file.

**Comment by kasjer** [comment]
> Please add `usbd` as supported peripheral in DA1469x boards' yaml file.

done

File: drivers/usb/udc/udc_smartbond.c [hunk 2]
```diff
@@ -0,0 +1,1768 @@
...
+		}
+	} else if (ep_idx != 0) {
+		/* If max_packet_size would fit in FIFO no need
+		 * for FIFO level warning interrupt.
+		 */
+		regs->rxc &= ~USB_USB_RXC1_REG_USB_RFWL_Msk;
+		USB->USB_FWMSK_REG &= ~(BIT(ep_idx - 1 + USB_USB_FWMSK_REG_USB_M_RXWARN31_Pos));
+	}
+
+	regs->rxc |= USB_USB_RXC1_REG_USB_RX_EN_Msk;
```
Comment (ydamigos) [inline drivers/usb/udc/udc_smartbond.c:397]: Could we reduce rxc register accesses?

File: drivers/usb/udc/udc_smartbond.c [hunk 3]
```diff
@@ -0,0 +1,1768 @@
...
+		 * Whole packet will be put in FIFO by DMA.
+		 * Set LAST bit before start.
+		 */
+		start_tx_dma(buf->data, &regs->txd, size);
+		regs->txc |= USB_USB_TXC1_REG_USB_LAST_Msk;
+	} else {
+		fill_tx_fifo(ep_state);
+	}
+
+	regs->txc |= USB_USB_TXC1_REG_USB_TX_EN_Msk;
```
[the remark this answers is not in the document]
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: done

File: drivers/usb/udc/udc_smartbond.c (hunk 2 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: donw

**Comment by kasjer** [comment]
Build fails due to unrelated change #73189 (issue #79594)

**Review by ydamigos — DISMISSED** [review]

**Review by tmon-nordic — DISMISSED** [review]

**Review by ioannis-karachalios — DISMISSED** [review]

**Review by andrzej-kaczmarek — DISMISSED** [review]

File: drivers/usb/udc/udc_smartbond.c [hunk 4]
```diff
@@ -0,0 +1,1764 @@
...
+	return 0;
+}
+
+/*
+ * This is called in the context of udc_ep_enqueue() and must
+ * not block. The driver can immediately claim the buffer if the queue is empty,
+ * but usually it is offloaded to a thread or work queue to handle transfers
+ * in a single location. Please refer to existing driver implementations
+ * for examples.
+ */
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:595]: Please remove the comments copied from the udc_skeleton.c.

File: boards/renesas/da14695_dk_usb/da14695_dk_usb.yaml [hunk 5]
```diff
@@ -9,9 +9,18 @@ toolchain:
...
   - watchdog
   - i2c
   - spi
   - usb_device
+  - rtc
+  - crypto
+  - dma
+  - mipi_dbi
+  - display
+  - memc
```
Comment (jfischer-no) [inline boards/renesas/da14695_dk_usb/da14695_dk_usb.yaml:24]: It does not belong in this PR and you need to remove them from this commit. (These are test features)

File: drivers/usb/udc/udc_smartbond.c [hunk 6]
```diff
@@ -0,0 +1,1764 @@
...
+#define VBUS_IRQ(inst)     DT_INST_IRQ_BY_IDX(inst, 1, irq)
+#define VBUS_IRQ_PRI(inst) DT_INST_IRQ_BY_IDX(inst, 1, priority)
+
+/*
+ * Minimal transfer size needed to use DMA. For short transfers
+ * it may be simpler to just fill hardware FIFO with data instead
+ * of programming DMA registers.
+ */
+#define DMA_MIN_TRANSFER_SIZE(inst) DT_INST_PROP(inst, dma_min_transfer_size)
+#define FIFO_READ_THRESHOLD(inst)   DT_INST_PROP(inst, fifo_read_threshold)
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:43]: Please move them to the bottom, just above `#define UDC_SMARTBOND_DEVICE_DEFINE(n) `

File: drivers/usb/udc/udc_smartbond.c [hunk 7]
```diff
@@ -0,0 +1,1764 @@
...
+
+/* Size of hardware RX and TX FIFO. */
+#define EP0_FIFO_SIZE 8
+#define EP_FIFO_SIZE  64
+
+#define EP_MAX DT_INST_PROP(0, num_bidir_endpoints)
+_Static_assert(EP_MAX > 0 && EP_MAX <= 4, "num-bidir-endpoints out of range");
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:50]: Please move it to the bottom, above #define UDC_SMARTBOND_DEVICE_DEFINE(n). Also it does not take instance number in the account, which is probably okay on your platform, but still not correct. Use BUILD_ASSERT. The check is likely not necessary. There other ways to get number of endpoints.

File: drivers/usb/udc/udc_smartbond.c [hunk 8]
```diff
@@ -0,0 +1,1764 @@
...
+	struct dma_block_config tx_block_cfg;
+	struct dma_block_config rx_block_cfg;
+} usbd_dma_cfg = {
+	.tx_chan = DT_DMAS_CELL_BY_NAME(DT_NODELABEL(usbd), tx, channel),
+	.tx_slot_mux = DT_DMAS_CELL_BY_NAME(DT_NODELABEL(usbd), tx, config),
+	.tx_dev = DEVICE_DT_GET(DT_DMAS_CTLR_BY_NAME(DT_NODELABEL(usbd), tx)),
+	.rx_chan = DT_DMAS_CELL_BY_NAME(DT_NODELABEL(usbd), rx, channel),
+	.rx_slot_mux = DT_DMAS_CELL_BY_NAME(DT_NODELABEL(usbd), rx, config),
+	.rx_dev = DEVICE_DT_GET(DT_DMAS_CTLR_BY_NAME(DT_NODELABEL(usbd), rx)),
+};
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:125]: Please move the instantiation  of usbd_dma_cfg to the bottom, either as part of  UDC_SMARTBOND_DEVICE_DEFINE(n) or above it.

File: drivers/usb/udc/udc_smartbond.c [hunk 9]
```diff
@@ -0,0 +1,1764 @@
...
+		USB->USB_ALTMSK_REG =
+			USB_USB_ALTMSK_REG_USB_M_RESET_Msk | USB_USB_ALTMSK_REG_USB_M_RESUME_Msk;
+		usb_clock_off(dev_state);
+		udc_submit_event(dev_state->dev, UDC_EVT_SUSPEND, 0);
+	}
+}
+
+static void udc_smartbond_isr(const struct device *dev)
+{
+	struct usb_dc_state *dev_state = dev->data;
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:1276]: Please name it `struct udc_smartbond_data;` and use `struct udc_smartbond_data *data = udc_get_private(dev);` or struct udc_smartbond_data *priv = udc_get_private(dev);` consistently.

File: drivers/usb/udc/udc_smartbond.c [hunk 10]
```diff
@@ -0,0 +1,1764 @@
...
+	if (GET_BIT(int_status, USB_USB_MAEV_REG_USB_ALT)) {
+		handle_alt_ev(dev_state);
+	}
+}
+
+/**
+ * USB functionality can be disabled from HOST and DEVICE side.
+ * Host side is indicated by VBUS line.
+ * Device side is decided by pair of calls usb_dc_attach()/usb_dc_detach,
+ * USB will only work when application calls usb_dc_attach() and VBUS is present.
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:1348]: usb_dc_attach()?

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/udc/udc_smartbond.c (hunk 10 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: change to reflect API calls udc_enable/udc_disable

File: drivers/usb/udc/udc_smartbond.c (hunk 9 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: dev_state change to data in all places

File: drivers/usb/udc/udc_smartbond.c (hunk 8 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: DMA configuration split into config (from DT) and data (that can change) and generated with along instance of device

File: drivers/usb/udc/udc_smartbond.c (hunk 6 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: Suggestion applied

File: drivers/usb/udc/udc_smartbond.c [hunk 11]
```diff
@@ -0,0 +1,1764 @@
...
+		ep0_out_config->stat.data1 = 1;
+		ep0_in_config->stat.halted = 0;
+		ep0_in_config->stat.data1 = 1;
+		REG_SET_BIT(USB_TXC0_REG, USB_TOGGLE_TX0);
+		REG_CLR_BIT(USB_EPC0_REG, USB_STALL);
+		LOG_DBG("Setup %02x %02x %02x %02x %02x %02x %02x %02x", dev_state->setup_buffer[0],
+			dev_state->setup_buffer[1], dev_state->setup_buffer[2],
+			dev_state->setup_buffer[3], dev_state->setup_buffer[4],
+			dev_state->setup_buffer[5], dev_state->setup_buffer[6],
+			dev_state->setup_buffer[7]);
```
[the remark this answers is not in the document]
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: Applied, thanks for suggestion

File: drivers/usb/udc/udc_smartbond.c [hunk 12]
```diff
@@ -0,0 +1,1764 @@
...
+		       size) < 0) {
+		LOG_ERR("Failed to reload RX DMA");
+	} else {
+		dma_start(usbd_dma_cfg.rx_dev, usbd_dma_cfg.rx_chan);
+	}
+}
+
+static void start_rx_packet(struct usb_dc_state *dev_state, struct smartbond_ep_state *ep_state)
+{
+	struct udc_ep_config *ep_config = &ep_state->config;
```
[the remark this answers is not in the document]
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: Suggestion applied

File: drivers/usb/udc/udc_smartbond.c [hunk 13]
```diff
@@ -0,0 +1,1764 @@
...
+	const struct udc_smartbond_config *cfg = dev_state->dev->config;
```
[the remark this answers is not in the document]
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: done

File: drivers/usb/udc/udc_smartbond.c [hunk 14]
```diff
@@ -0,0 +1,1749 @@
...
+	 * Loop checks TCOUNT all the time since this value is saturated to 31
+	 * and can't be read just once before.
+	 */
+	while ((regs->txs & USB_USB_TXS1_REG_USB_TCOUNT_Msk) > 0 && remaining > 0) {
+		regs->txd = *src++;
+		ep_state->last_packet_size++;
+		remaining--;
+	}
+
+	if (ep_idx != 0) {
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:297]: Wondering why you do not need to handle it for control endpoints?
Also, for constructs like this, you can just reverse the logic and just return. The code below will look a bit more relaxed.

```c
	if (ep_idx == 0) {
		/* Not needed for control endpoints because they are fancy. */
		return;
	}
```

File: drivers/usb/udc/udc_smartbond.c [hunk 15]
```diff
@@ -0,0 +1,1749 @@
...
+		return true;
+	} else {
+		return false;
+	}
+}
+
+static void start_rx_dma(const struct usb_smartbond_dma_config *dma_cfg, volatile void *src,
+			 void *dst, uint16_t size)
+{
+	if (dma_reload(dma_cfg->rx_dev, dma_cfg->rx_chan, (uint32_t)src, (uint32_t)dst, size) < 0) {
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:345]: This line looks confusing. I doubt volatile above makes any sense. `uintptr_t` would be a more appropriate type.

File: drivers/usb/udc/udc_smartbond.c [hunk 16]
```diff
@@ -0,0 +1,1749 @@
...
+		.num_of_eps = DT_INST_PROP(n, num_bidir_endpoints),                                \
+		.dma_cfg =                                                                         \
+			{                                                                          \
+				.tx_chan = DT_INST_DMAS_CELL_BY_NAME(n, tx, channel),              \
+				.tx_slot_mux = DT_INST_DMAS_CELL_BY_NAME(n, tx, config),           \
+				.tx_dev = DEVICE_DT_GET(DT_INST_DMAS_CTLR_BY_NAME(n, tx)),         \
+				.rx_chan = DT_INST_DMAS_CELL_BY_NAME(n, rx, channel),              \
+				.rx_slot_mux = DT_INST_DMAS_CELL_BY_NAME(n, rx, config),           \
+				.rx_dev = DEVICE_DT_GET(DT_INST_DMAS_CTLR_BY_NAME(n, rx)),         \
+			},                                                                         \
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:1725]:
```c
		.dma_cfg = {                                                                          \
			.tx_chan = DT_INST_DMAS_CELL_BY_NAME(n, tx, channel),              \
			.tx_slot_mux = DT_INST_DMAS_CELL_BY_NAME(n, tx, config),           \
			.tx_dev = DEVICE_DT_GET(DT_INST_DMAS_CTLR_BY_NAME(n, tx)),         \
			.rx_chan = DT_INST_DMAS_CELL_BY_NAME(n, rx, channel),              \
			.rx_slot_mux = DT_INST_DMAS_CELL_BY_NAME(n, rx, config),           \
			.rx_dev = DEVICE_DT_GET(DT_INST_DMAS_CTLR_BY_NAME(n, rx)),         \
		}, 
```

File: drivers/usb/udc/udc_smartbond.c [hunk 17]
```diff
@@ -0,0 +1,1749 @@
...
+	};                                                                                         \
+                                                                                                   \
+	static struct usb_smartbond_data udc_data_##n = {                                          \
+		.udc_data =                                                                        \
+			{                                                                          \
+				.mutex = Z_MUTEX_INITIALIZER(udc_data_##n.udc_data.mutex),         \
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:1731]:
```c

		.udc_data = {                                                                          \
			.mutex = Z_MUTEX_INITIALIZER(udc_data_##n.udc_data.mutex), 
```

File: drivers/usb/udc/udc_smartbond.c (hunk 16 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: This strange formatting was done by `clang-format` tool. I wander if you have power to make someone change `.clang-format` to make it more consistent for nested structure initialization.

Fixed anyway.

File: drivers/usb/udc/udc_smartbond.c (hunk 17 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: done

File: drivers/usb/udc/udc_smartbond.c (hunk 15 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: Change as suggested. It was done this way because function start_rx_dma was called with address of volatile register.
Now casting is done in placed where start_rx_dma is called instead.

File: drivers/usb/udc/udc_smartbond.c (hunk 14 above)
Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c]: Suggestion applied. Added explanation why this case does not apply. Additional check also added for cases where enabling FIFO level interrupt may not be needed.

File: drivers/usb/udc/udc_smartbond.c [hunk 18]
```diff
@@ -0,0 +1,1754 @@
...
+static int udc_smartbond_ep_dequeue(const struct device *dev, struct udc_ep_config *const ep_cfg)
+{
+	const uint8_t ep = ep_cfg->addr;
+	unsigned int lock_key;
+	struct net_buf *buf;
+
+	LOG_INF("ep 0x%02x dequeue all", ep);
+
+	lock_key = irq_lock();
+
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_smartbond.c:624]: That looks too easy, do you need to find and cancel DMA transfers in progress?

Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c:624]: Your are right, can you give me a quick tip on how to trigger this case so I can verify that it works correctly?

Comment (kasjer) [reply drivers/usb/udc/udc_smartbond.c:648]: Fixed (scenario when this happens not tested though).

Comment (jfischer-no) [reply drivers/usb/udc/udc_smartbond.c:648]: There are few, (There was a simple one using shell commands to enqueue transfers, I have to bring it back). You can try CDC ACM sample, build it with CONFIG_SHELL and CONFIG_USBD_SHELL enabled. On Zephyr side enter shell command `usbd select sample_usbd`.
```

python3
>>> import usb
>>> dev = usb.core.find(idVendor=0x2fe3, idProduct=0x0001)
>>> dev.detach_kernel_driver(0)
>>> #to set DTR
>>> dev.ctrl_transfer(0x21, 0x22, 3, 0, 0)
0
>>> #Read all DCD and DSR notifications
>>> dev.read(0x81, 100)
array('B', [161, 32, 0, 0, 0, 0, 2, 0, 1, 0])
>>> dev.read(0x81, 100)
array('B', [161, 32, 0, 0, 0, 0, 2, 0, 3, 0])
>>> #On Zephyr side 'usbd disable' should trigger dequeue transfers for endpoint 0x01
```

**Review by jfischer-no — APPROVED** [review]

**Review by ydamigos — APPROVED** [review]

**Review by ioannis-karachalios — APPROVED** [review]
