### PR TITLE
Bluetooth: host: Document settings_load is required to finalize init

### LINKED ISSUE #36037: bt_init returning success when Bluetooth initialization does not get finalized.
**Describe the bug**
`bt_enable` is returning success when not initialized.
Caused by [`bt_init` returning early](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/hci_core.c#L3435) and [not calling `bt_finalize_init`](https://github.com/zephyrproject-rtos/zephyr/blob/38eaabc9c75c9a0932bbd272952dc81a2f2939ef/subsys/bluetooth/host/hci_core.c#L3441) if `CONFIG_BT_SETTINGS=y` is and `bt_dev.id_count` is 0.

**To Reproduce**
1. set `CONFIG_BT_SETTINGS=y`
2. call `bt_enable` whoult calling `settings_load`

**Expected behavior**
Either returning a non-zero error code if this is an error condition, or finalizing the Bluetooth initializing if it is not.

**Impact**
It causes functions like `bt_le_ext_adv_start` to return `EAGAIN` because the `BT_DEV_READY` [does not get set](https://github.com/zephyrproject-rtos/zephyr/blob/38eaabc9c75c9a0932bbd272952dc81a2f2939ef/subsys/bluetooth/host/hci_core.c#L3407) even though it seems that Bluetooth got enabled successfully.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: NRF Sdk
 - v1.5.0

### PR DESCRIPTION
**Pull request by joerchan**
Document that calling settings_load is required when the application is
not creating and managing the identities of the stack itself.
The application will not be able to use all features of the stack before
the identities have been loaded.

Fixes: #36037

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

File: include/bluetooth/bluetooth.h [hunk 1]
```diff
@@ -130,6 +130,11 @@ typedef void (*bt_ready_cb_t)(int err);
  * Enable Bluetooth. Must be the called before any calls that
  * require communication with the local Bluetooth hardware.
  *
+ * When CONFIG_BT_SETTINGS has been enabled and the application is not managing
+ * identities of the stack itself then the application must call settings_load()
+ * before the stack is fully enabled.
+ * See bt_id_create() for more information.
```
Comment (LingaoM) [inline include/bluetooth/bluetooth.h:136]:
```suggestion

* When @option{CONFIG_BT_SETTINGS} has been enabled and the application is not managing 
* identities of the stack itself then the application must call @ref settings_load() 
* before the stack is fully enabled. 
* See @ref bt_id_create() for more information.

```

Comment (joerchan) [reply include/bluetooth/bluetooth.h:136]: Thanks.

Just FYI: It is possible to do multiline suggestion, you just have to hold down the mouse-key and drag down across the lines that your comment should apply for.

**Review by LingaoM — APPROVED** [review]
