### PR TITLE
drivers/rtc/rtc_mc146818: Fix RTC driver for QEMU boards

### LINKED ISSUE #59448: drivers: rtc: mc146818: driver fails multiple tests from rtc_api testsuite
**Describe the bug**

The `rtc_mc146818` driver is broken (and has actually always been broken). It's unclear to me how this driver was even merged (#56334) in the state that it was in (literally failing every test in the testsuite).

Some notes:
1. The testsuite itself is broken
  - possibly incorrect bit in the API documentation `int tm_year;	/**< Year - 1900 */`
    - based on stepping through code, it appears that the reference is actually assumed to be 1970 due to the use of `gmtime_r()` in the testsuite, although that is perhaps accidental
  - should exercise as many features / code paths as possible, so please enable these
    - `CONFIG_RTC_ALARM=y`
    - `CONFIG_RTC_UPDATE=y`
    - `CONFIG_RTC_CALIBRATION=y`
  - does the testsuite run in CI?
  - I would suggest adding to `prj.conf` to reduce CI churn
3. This driver needs to be fixed
  - I'm not actually able to get the ISR to trigger
    - likely necessary in order to successfully pass a Y2K rollover test
  - `test_alarm` does not work
  - `test_alarm_callback` does not work
  - `test_update_callback` does not work
  -  the driver should probably be using `if (IS_ENABLED(..)) { ... }` in several places instead of `#ifdef`s

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?: `qemu_x86`, `qemu_x86_64`
 - What have you tried to diagnose or workaround this issue? run / added tests / fixed bugs
 - Is this a regression? No. It has been broken since the initial commit

**To Reproduce**
1. `west build -p auto -b qemu_x86 -t run tests/drivers/rtc/rtc_api -- -DCONFIG_RTC_ALARM=y -DCONFIG_RTC_UPDATE=y -DCONFIG_RTC_CALIBRATION=y`
2. See error

**Expected behavior**
The testsuite should pass for all existing drivers within the tree.

**Impact**
Showstopper for now, because I would expect this RTC device to work on a tier0 platform. We were hoping to use this for additional POSIX improvements.

**Logs and console output**
```shell
west build -p auto -b qemu_x86 -t run tests/drivers/rtc/rtc_api -- -DCONFIG_RTC_ALARM=y -DCONFIG_RTC_UPDATE=y -DCONFIG_RTC_CALIBRATION=y
...
SeaBIOS (version zephyr-v1.0.0-0-g31d4e0e-dirty-20200714_234759-fv-az50-zephyr)
Booting from ROM..
*** Booting Zephyr OS build v3.4.0-167-g327eb119b6bc ***
Running TESTSUITE rtc_api
===================================================================
START - test_alarm

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/rtc/rtc_api/src/test_alarm.c:129: rtc_api_test_alarm: (ret == 1 is false)
Alarm should be pending
 FAIL - test_alarm in 13.017 seconds
===================================================================
START - test_alarm_callback

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/rtc/rtc_api/src/test_alarm_callback.c:145: rtc_api_test_alarm_callback: (callback_called_status == true is false)
Alarm callback should have been called
 FAIL - test_alarm_callback in 13.020 seconds
===================================================================
START - test_set_get_calibration

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/rtc/rtc_api/src/test_calibrate.c:54: rtc_api_test_set_get_calibration: (ret == 0 is false)
Failed to set calibration
 FAIL - test_set_get_calibration in 0.001 seconds
===================================================================
START - test_set_get_time
 PASS - test_set_get_time in 0.001 seconds
===================================================================
START - test_time_counting
 PASS - test_time_counting in 10.196 seconds
===================================================================
START - test_update_callback

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/rtc/rtc_api/src/test_update_callback.c:52: rtc_api_test_update_callback: (counter < 12 && counter > 8 is false)
Invalid update callback called counter
 FAIL - test_update_callback in 15.021 seconds
===================================================================
TESTSUITE rtc_api failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  33.33% [rtc_api]: pass = 2, fail = 4, skip = 0, total = 6 duration = 51.256 seconds
 - FAIL - [rtc_api.test_alarm] duration = 13.017 seconds
 - FAIL - [rtc_api.test_alarm_callback] duration = 13.020 seconds
 - FAIL - [rtc_api.test_set_get_calibration] duration = 0.001 seconds
 - PASS - [rtc_api.test_set_get_time] duration = 0.001 seconds
 - PASS - [rtc_api.test_time_counting] duration = 10.196 seconds
 - FAIL - [rtc_api.test_update_callback] duration = 15.021 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.1
 - Commit SHA or Version used: ae114855f90405b886bbb98935db1b50432740cc

**Additional context**
Originally discovered while working on #59402 but that PR was merged before additional changes could be made.

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
This commit fixes the driver, allowing it to pass
the RTC API test suite for set/get time, alarms and the update callback (the hw does not support calibration)

This requires an additional flag to the HPET module which disables legacy IRQs, allowing the RTCs IRQ to be raised.

Furthermore, the commit cleans up the RTC in the devicetree for the IA32 dtsi and the qemu_x64 dts files, and updates the yaml files for QEMU to indicate the support for the RTC subsystem.

Fixes #59448

### CODE REVIEW

**Comment by bjarki-trackunit** [comment]
Proof of it working @cfriedt  :D

```
[0/1] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: qemu32,+nx,+pae
SeaBIOS (version zephyr-v1.0.0-0-g31d4e0e-dirty-20200714_234759-fv-az50-zephyr)
Booting from ROM..
*** Booting Zephyr OS build zephyr-v3.4.0-974-g7fba7d395750 ***
Running TESTSUITE rtc_api
===================================================================
START - test_alarm
 PASS - test_alarm in 26.041 seconds
===================================================================
START - test_alarm_callback
 PASS - test_alarm_callback in 26.040 seconds
===================================================================
START - test_set_get_time
 PASS - test_set_get_time in 0.001 seconds
===================================================================
START - test_time_counting
 PASS - test_time_counting in 9.689 seconds
===================================================================
START - test_update_callback
 PASS - test_update_callback in 15.020 seconds
===================================================================
START - test_y2k
 PASS - test_y2k in 2.010 seconds
===================================================================
TESTSUITE rtc_api succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [rtc_api]: pass = 6, fail = 0, skip = 0, total = 6 duration = 78.801 seconds
 - PASS - [rtc_api.test_alarm] duration = 26.041 seconds
 - PASS - [rtc_api.test_alarm_callback] duration = 26.040 seconds
 - PASS - [rtc_api.test_set_get_time] duration = 0.001 seconds
 - PASS - [rtc_api.test_time_counting] duration = 9.689 seconds
 - PASS - [rtc_api.test_update_callback] duration = 15.020 seconds
 - PASS - [rtc_api.test_y2k] duration = 2.010 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

File: drivers/rtc/rtc_mc146818.c [hunk 1]
```diff
@@ -545,26 +463,29 @@ static int rtc_mc146818_update_set_callback(const struct device *dev,
 static void rtc_mc146818_isr(const struct device *dev)
 {
 	struct rtc_mc146818_data * const dev_data = dev->data;
+	uint8_t regc;
 
-	ARG_UNUSED(dev_data);
```
Comment (cfriedt) [inline drivers/rtc/rtc_mc146818.c:549]: Undelete this line

**Review by cfriedt — COMMENTED** [review]
Tiny fix

File: drivers/rtc/rtc_mc146818.c (hunk 1 above)
Comment (bjarki-trackunit) [reply drivers/rtc/rtc_mc146818.c:549]: Tiny fix applied

**Comment by bjarki-trackunit** [comment]
@dcpleung @andyross 

I need help solving a timeout occurring for a library named p4workq, which times out if `no-legacy-irq;` is used for the HPET for the QEMU boards. The test timing out is a stress test, but it seems it is a bug rather than an increased workload causing the timeout.

I am running the test using `west twister -p qemu_x86_tiny -T zephyr/tests/lib/p4workq`

The stress test has a define `#define MAX_EVENTS` which scales the amount of work which needs to be done. I ran the test for a few different values:

100 -> 13.27 seconds
300 -> 13.10 seconds
400 -> 13.37 seconds
410 -> timed out after 64 seconds...

I am enabling `no-legacy-irq;` to allow the QEMU q35 RTC's IRQ to fire.

I need help to move forward :)

File: drivers/rtc/rtc_mc146818.c [hunk 2]
```diff
@@ -51,7 +51,6 @@
 #define RTC_UIP		RTC_REG_A
 #define RTC_DATA	RTC_REG_B
 #define RTC_FLAG	RTC_REG_C
-#define RTC_ALARM_MDAY	RTC_REG_D
```
Comment (cfriedt) [inline drivers/rtc/rtc_mc146818.c:54]: How much of this file actually needed to be changed in order for the fix to work?

At a glance, it seems that most of the changes here are cosmetic (formatting, name changes, ...). Is it possible to reduce the change to only what is required for the fix?

File: boards/x86/qemu_x86/qemu_x86.dts [hunk 3]
```diff
@@ -132,6 +132,10 @@
 	status = "okay";
 };
 
+&rtc {
```
Comment (cfriedt) [inline boards/x86/qemu_x86/qemu_x86.dts:135]: This could likely be moved to the RTC testsuite in a board overlay, since it is causing unrelated things to fail, maybe with a comment saying why it's necessary.

File: dts/x86/intel/ia32.dtsi [hunk 4]
```diff
@@ -64,6 +64,7 @@
 			reg = <0xfed00000 0x400>;
 			interrupts = <2 IRQ_TYPE_FIXED_EDGE_RISING 4>;
 			interrupt-parent = <&intc>;
+			no-legacy-irq;
```
Comment (cfriedt) [inline dts/x86/intel/ia32.dtsi:67]: This can likely also be added in the testsuite in a board overlay, maybe with a descriptive comment, in order to avoid breaking unrelated things.

File: dts/x86/intel/ia32.dtsi [hunk 5]
```diff
@@ -75,8 +76,7 @@
 			interrupt-parent = <&intc>;
 			alarms-count = <1>;
 
-			status = "okay";
+			status = "disabled";
```
Comment (cfriedt) [inline dts/x86/intel/ia32.dtsi:79]: This can likely also be added in the testsuite in a board overlay, maybe with a descriptive comment, in order to avoid breaking unrelated things.

**Review by cfriedt — CHANGES_REQUESTED** [review]
It looks like a lot of changes in the driver are potentially unrelated to the actual fix.

I would suggest separating any cosmetic changes, and functional changes to separate commits.

Other than that, I think to avoid breaking other things (libp4work or whatever it is), it might be better to make the necessary DT adjustments in a board overlay in the testsuite.

Also, is it possible to ensure the driver is built and tested in CI? Do we have it in a build all test somewhere?

File: drivers/rtc/rtc_mc146818.c (hunk 2 above)
Comment (bjarki-trackunit) [reply drivers/rtc/rtc_mc146818.c:54]: These changes are the bare minimum required to get the driver to an acceptable state. The driver still needs a once over to clean it up, which I agree is not within the scope of this PR

File: boards/x86/qemu_x86/qemu_x86.dts (hunk 3 above)
Comment (bjarki-trackunit) [reply boards/x86/qemu_x86/qemu_x86.dts:135]: I will move it to the test suite, and make sure the RTC tests are built

File: dts/x86/intel/ia32.dtsi (hunk 4 above)
Comment (bjarki-trackunit) [reply dts/x86/intel/ia32.dtsi:67]: This will also go to the test suite

File: dts/x86/intel/ia32.dtsi (hunk 5 above)
Comment (bjarki-trackunit) [reply dts/x86/intel/ia32.dtsi:79]: I don't think this should be in the test suite, I don't know what criteria we use to determine if a node is enabled in the dtsi file, but for an RTC, I would expect it to be disabled by default

Comment (bjarki-trackunit) [reply dts/x86/intel/ia32.dtsi]: Removed this change from the PR

**Review by cfriedt — DISMISSED** [review]
Tests are passing 🙌

**Comment by cfriedt** [comment]
I realize I just approved this, but it looks like a few of the RTC kconfig options are missing from `tests/drivers/rtc/rtc_api/prj.conf`

From what I understand all of the rtcs exercised in this testsuite support all of the options, so might be better to add them there as well.

**Comment by bjarki-trackunit** [comment]
@cfriedt

Only the mandatory tests from the test suite are run by default, which is why the features RTC_ALARM and RTC_UPDATE and RTC_CALIBRATE are not included in the main .prj Features are selected in the board overlays. The MC146818 only supports RTC_ALARM and RTC_UPDATE, not RTC_CALIBRATE :)

**Comment by cfriedt** [comment]
> @cfriedt
> 
> Only the mandatory tests from the test suite are run by default, which is why the features RTC_ALARM and RTC_UPDATE and RTC_CALIBRATE are not included in the main .prj Features are selected in the board overlays. The MC146818 only supports RTC_ALARM and RTC_UPDATE for example, not RTC_CALIBRATE :) 

Sure, but just remember we need code paths tested, even if they are disabled by default

File: drivers/rtc/rtc_mc146818.c [hunk 6]
```diff
@@ -583,26 +506,30 @@ struct rtc_driver_api rtc_mc146818_driver_api = {
...
-			rtc_mc146818_isr, NULL,
-			DT_INST_IRQ(0, sense));
-	irq_enable(DT_INST_IRQN(0));
-
-	return 0;
-}
+#define RTC_MC146818_INIT_FN_DEFINE(n)						\
+	static int rtc_mc146818_init##n(const struct device *dev)		\
+	{									\
+		rtc_write(RTC_REG_A, 0);					\
```
Comment (akanisetti) [inline drivers/rtc/rtc_mc146818.c:512]: Clearing RTC_REG_A is blocking RTC time update on real hardware.

Comment (bjarki-trackunit) [reply drivers/rtc/rtc_mc146818.c:512]: I see, the QEMU board has no oscillator connected to the RTC (the clock therefore runs regardless of divider settings), my theory is that your RTC is connected to an oscillator. Could you check if setting the DV2, DV1 and DV0 bits according to the RTC's clock input? If that works, I will expand the dts and driver with input clock support :)

Comment (akanisetti) [reply drivers/rtc/rtc_mc146818.c:512]: Yes, setting DV2-0 according to RTC clock allows it run. Freq on my hardware is 32.786KHz so DV sequence is 0-1-0.

Comment (bjarki-trackunit) [reply drivers/rtc/rtc_mc146818.c]: I have added input clock frequency configuration to the driver and devicetree (See [commit](https://github.com/zephyrproject-rtos/zephyr/pull/60321/commits/f33e973278b587cd764916181a1f34ffc9a51ad7)). Please test it out :)

Comment (akanisetti) [reply drivers/rtc/rtc_mc146818.c]: It is working👍

Comment (bjarki-trackunit) [reply drivers/rtc/rtc_mc146818.c]: Awesome :)

**Review by cfriedt — DISMISSED** [review]

**Review by cfriedt — DISMISSED** [review]

**Comment by cfriedt** [comment]
is @akanisetti able to review / approve as well?

**Review by akanisetti — APPROVED** [review]

**Comment by cfriedt** [comment]
@bjarki-trackunit - you might need to find another reviewer with approve privileges.

**Comment by bjarki-trackunit** [comment]
@henrikbrixandersen @erwango Could you please review this PR? :)

File: drivers/rtc/rtc_mc146818.c [hunk 7]
```diff
@@ -113,6 +113,11 @@
 #define MIN_YEAR_DIFF	0 /* YEAR - 1900 */
 #define MAX_YEAR_DIFF	99 /* YEAR - 1999 */
 
+/* Input clock frequency mapped to divider bits */
+#define RTC_IN_CLK_DIV_BITS_4194304 (0b000 << 4)
+#define RTC_IN_CLK_DIV_BITS_1048576 (0b001 << 4)
+#define RTC_IN_CLK_DIV_BITS_32768   (0b010 << 4)
```
Comment (nordicjm) [inline drivers/rtc/rtc_mc146818.c:119]: not acceptable to use C23 features

**Review by nordicjm — CHANGES_REQUESTED** [review]

**Comment by bjarki-trackunit** [comment]
@nordicjm @cfriedt Could you kindly re-review? :)

File: tests/drivers/rtc/rtc_api/boards/qemu_x86_64.overlay [hunk 8]
```diff
@@ -0,0 +1,18 @@
+/*
+ * Copyright (c) 2023 Bjarki Arge Andreasen
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*
+ * The RTC IRQ is not routed to the IOAPIC if the legacy
+ * IRQ bit is set. The IRQ is required for alarm
+ * operation and the update callbadk.
```
Comment (cfriedt) [inline tests/drivers/rtc/rtc_api/boards/qemu_x86_64.overlay:10]: Nit: spelling mistake

**Review by cfriedt — DISMISSED** [review]
One tiny spelling mistake - I'll re-approve when fixed.

**Review by nordicjm — APPROVED** [review]

**Comment by bjarki-trackunit** [comment]
@cfriedt pretty please :D

**Review by cfriedt — APPROVED** [review]
