### PR TITLE
Bluetooth: L2CAP: Set NULL callback for PDUs

### LINKED ISSUE #76738: Sending Bluetooth L2CAP messages after reconnecting sometimes leads to crashes due to uninitalized net_buf callback
**Describe the bug**

When sending Bluetooth L2CAP messages over a dynamic channel (with `bt_l2cap_chan_send()`), the callback closure in the `net_buf` userdata is never initialized (unlike with static channels). This leads to `bt_conn_tx_processor()` reading out an invalid callback pointer (this manifests as 0x1 on my device) which later gets called, triggering a crash in `tx_notify()` when calling the callback.

The TODO comment "add sdu_sent callback on last PDU" in `conn.c:1039` seems relevant, since the exact problem is that this PDU has never had its callback set. I don't know why that is though, since `l2cap_data_pull` should add the callback for dynamic channels, but this doesn't seem to happen in all cases.

The issue goes away when I manually zero the `net_buf` user_data before passing the buffer to `bt_l2cap_chan_send()`.

**To Reproduce**

1. device A connects to device B (`bt_conn_le_create()`)
2. device A creates L2CAP channel with device B (`bt_l2cap_chan_connect()`)
3. device A and device B send packets (sending another one as soon as the `chan_ops.sent` callback is called) (`bt_l2cap_chan_send()`)
4. power cycle device A
5. go to 1 until the crash occurs on device B

I don't have a small enough sample yet that I can share here since this occurred in an internal code base, but if necessary I can try and strip it down.

**Expected behavior**

Zephyr should not crash.

**Impact**

Annoyance, leads to occasional power cycles needed

**Logs and console output**

These logs where done with warn log level and certain log messages patched to be WRN instead of DBG since with debug log level lead to a lot of log output being dropped due to buffer overruns.

```
receiver:bt:l2cap: accepting channel connection
receiver:bt:l2cap: channel connected
[00:00:58.524,719] <wrn> bt_conn: conn 0x20000fc0: not connected
[00:00:59.391,998] <wrn> bt_conn: tx_process: pop: cb 0x1 userdata 0 buf 0x20007488 (ref 1)
[00:00:59.392,028] <wrn> bt_conn: tx_process: conn 0x20000fc0 buf 0x20007488 (last)
[00:00:59.392,028] <wrn> bt_conn: send_buf: invalid callback, cb = 0x1
[00:00:59.434,844] <wrn> bt_conn: tx_notify: invalid cb: conn 0x20000fc0 tx 0x20001b1c cb 0x1 user_data 0
[00:00:59.434,875] <err> os: ***** MPU FAULT *****
[00:00:59.434,875] <err> os:   Data Access Violation
[00:00:59.434,875] <err> os:   MMFAR Address: 0xd
[00:00:59.434,906] <err> os: r0/a1:  0x00000000  r1/a2:  0xffffffff  r2/a3:  0x00000000
[00:00:59.434,906] <err> os: r3/a4:  0x00000001 r12/ip:  0x20001cac r14/lr:  0x00009b0b
[00:00:59.434,936] <err> os:  xpsr:  0x61000000
[00:00:59.434,936] <err> os: Faulting instruction address (r15/pc): 0x0000002c
[00:00:59.434,967] <err> os: >>> ZEPHYR FATAL ERROR 19: Unknown error on CPU 0
[00:00:59.434,997] <err> os: Current thread: 0x20001898 (unknown)
[00:01:00.841,003] <err> os: Halting system
```

The crash dump link register points to `/home/ferdinand/Documents/Work/UWB/UDK1/zephyrproject/zephyr/subsys/bluetooth/host/conn.c:299`, which means this crash happened why trying to call the invalid `cb`.

Logging patch:

```patch
diff --git a/subsys/bluetooth/host/conn.c b/subsys/bluetooth/host/conn.c
index 31d08048571..b86d65c1b56 100644
--- a/subsys/bluetooth/host/conn.c
+++ b/subsys/bluetooth/host/conn.c
@@ -278,7 +278,7 @@ static void tx_notify(struct bt_conn *conn)
                        return;
                }
 
-               LOG_DBG("tx %p cb %p user_data %p", tx, tx->cb, tx->user_data);
+               if (tx->cb == (void*)1) LOG_WRN("tx_notify: invalid cb: conn %p tx %p cb %p user_data %p", conn, tx, tx->cb, tx->user_data);
 
                /* Copy over the params */
                cb = tx->cb;
@@ -648,6 +648,7 @@ static int send_buf(struct bt_conn *conn, struct net_buf *buf,
                return -ENOMEM;
        }
 
+       if (cb == (void*)1) LOG_WRN("send_buf: invalid callback, cb = %p", cb);
        tx->cb = cb;
        tx->user_data = ud;
 
@@ -1041,10 +1042,10 @@ void bt_conn_tx_processor(void)
                 * We still allocate one TX context per-fragment though.
                 */
                conn->get_and_clear_cb(conn, buf, &cb, &ud);
-               LOG_DBG("pop: cb %p userdata %p", cb, ud);
+               if (cb == (void*)1) LOG_WRN("tx_process: pop: cb %p userdata %p buf %p (ref %d)", cb, ud, buf, buf->ref);
        }
 
-       LOG_DBG("TX process: conn %p buf %p (%s)",
+       if (cb == (void*)1) LOG_WRN("tx_process: conn %p buf %p (%s)",
                conn, buf, last_buf ? "last" : "frag");
 
        int err = send_buf(conn, buf, buf_len, cb, ud);

```

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: arm-zephyr-eabi-gcc (Zephyr SDK 0.16.6) 12.2.0
 - Commit SHA or Version used: 3.7.0 (642b308bfc0)

**Additional context**

Target: `nrf52840dk/nrf52840`
Config (`prj.conf`):

```
CONFIG_GPIO=y
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ATT_PREPARE_COUNT=1
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_CTLR_ADVANCED_FEATURES=y
CONFIG_BT_CTLR_CONN_RSSI=y
CONFIG_BT_SMP=y
CONFIG_BT_L2CAP_DYNAMIC_CHANNEL=y
CONFIG_BT_L2CAP_TX_MTU=65
CONFIG_BT_BUF_ACL_RX_SIZE=71
CONFIG_CRC=y
CONFIG_STD_C23=y
CONFIG_REBOOT=y
CONFIG_LOG=y
CONFIG_BT_LOG_LEVEL_WRN=y
CONFIG_EXCEPTION_STACK_TRACE=y
CONFIG_COMPILER_OPT="-g"
```

### PR DESCRIPTION
**Pull request by jori-nordic**
It was not being set, and thus if the user_data contained garbage from
before, then conn.c would attempt to call that garbage.

Static channels don't have this issue, as every "SDU" fits into one PDU.

Watch the test fail:
- Add `CONFIG_NO_RUNTIME_CHECKS=y` to `prj.conf`
- Revert the last commit "Bluetooth: L2CAP: Set NULL callback for PDUs"

### CODE REVIEW

File: include/zephyr/bluetooth/l2cap.h [hunk 1]
```diff
@@ -600,6 +600,10 @@ int bt_l2cap_chan_disconnect(struct bt_l2cap_chan *chan);
  *  on the stack's global buffer pool (sized
  *  @kconfig{CONFIG_BT_L2CAP_TX_BUF_COUNT}).
  *
+ *  @note The buffer's user_data _will_ be overwritten by this function. Do not
```
Comment (Thalley) [inline include/zephyr/bluetooth/l2cap.h:603]: Consider
```suggestion
 *  @warning The buffer's user_data _will_ be overwritten by this function. Do not
```

File: subsys/bluetooth/host/conn.c [hunk 2]
```diff
@@ -861,7 +862,7 @@ static bool dont_have_viewbufs(void)
 #endif	/* CONFIG_BT_CONN_TX */
 }
 
-static bool dont_have_methods(struct bt_conn *conn)
+__maybe_unused static bool dont_have_methods(struct bt_conn *conn)
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:865]: Is `__maybe_unused` necessary? We have many `static` functions that are guarded by e.g. `IS_ENABLED` that don't require this. 

Maybe `CHECKIF` should use `IS_ENABLED` rather than `#if`.

Comment (Thalley) [reply subsys/bluetooth/host/conn.c:865]: An alternative is to also use a regular `if` for guarding this call. We don't really have any guidelines on when to use one over the other, but my rule of thumb is that I use `CHECKIF` for values that are always incorrect and/or checkable by the caller (such as values out of range, etc.), but not for state-related checks. 

It's OK to keep as is though, assuming that coverity likes `__maybe_unused`

File: subsys/bluetooth/host/l2cap.c [hunk 3]
```diff
@@ -3068,6 +3070,20 @@ int bt_l2cap_chan_disconnect(struct bt_l2cap_chan *chan)
 	return 0;
 }
 
+__maybe_unused static bool user_data_not_empty(const struct net_buf *buf)
+{
+	size_t ud_len = sizeof(struct closure);
+	uint8_t *ud = net_buf_user_data(buf);
```
Comment (Thalley) [inline subsys/bluetooth/host/l2cap.c:3076]: Ew, `net_buf_user_data` casts away the `const` from `buf`. 

Nevertheless, this could be
```suggestion
	const uint8_t *ud = net_buf_user_data(buf);
```

but is OK to keep

File: subsys/bluetooth/host/l2cap.c [hunk 4]
```diff
@@ -938,14 +938,16 @@ struct net_buf *l2cap_data_pull(struct bt_conn *conn,
...
-				     UINT_TO_POINTER(lechan->tx.cid));
-		}
+	if (L2CAP_LE_CID_IS_DYN(lechan->tx.cid)) {
+		bool sdu_end = last_frag && last_seg;
+
+		LOG_DBG("adding `sdu_sent` callback");
+		/* No user callbacks for SDUs */
+		make_closure(pdu->user_data,
+			     sdu_end ? l2cap_chan_sdu_sent : NULL,
+			     sdu_end ? UINT_TO_POINTER(lechan->tx.cid) : NULL);
```
Comment (Thalley) [inline subsys/bluetooth/host/l2cap.c:950]: Since the addition of the `l2cap_chan_sdu_sent` callback is now conditional, maybe the log statement should reflect that. As the commit is now, "adding `sdu_sent` callback" may be logged even when the callback is set to NULL.

File: subsys/bluetooth/host/l2cap.c [hunk 5]
```diff
@@ -3068,6 +3070,20 @@ int bt_l2cap_chan_disconnect(struct bt_l2cap_chan *chan)
 	return 0;
 }
 
+__maybe_unused static bool user_data_not_empty(const struct net_buf *buf)
+{
+	size_t ud_len = sizeof(struct closure);
+	uint8_t *ud = net_buf_user_data(buf);
+
+	for (size_t i; i < ud_len; i++) {
```
Comment (Thalley) [inline subsys/bluetooth/host/l2cap.c:3078]:
```suggestion
	for (size_t i = 0U; i < ud_len; i++) {
```

**Review by Thalley — CHANGES_REQUESTED** [review]
Missing initialization of loop variable needs to be fixed; the others are optional

File: subsys/bluetooth/host/conn.c (hunk 2 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/conn.c:865]: I use CHECKIF so the people that _have_ to go fast can skip the user-data checkloop.

File: subsys/bluetooth/host/l2cap.c (hunk 4 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:950]: That's true. I had two log messages before, but moved around the ifs and forgot this log message.

File: subsys/bluetooth/host/l2cap.c (hunk 5 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:3078]: dont know what you mean, it works on my machine 🤪

File: tests/bsim/bluetooth/host/l2cap/userdata/src/main_l2cap_userdata.c [hunk 6]
```diff
@@ -14,8 +14,15 @@ extern enum bst_result_t bst_result;
 static struct bt_conn *default_conn;
 
 #define PSM 0x80
+#define DATA_SIZE 500
```
Comment (jori-nordic) [inline tests/bsim/bluetooth/host/l2cap/userdata/src/main_l2cap_userdata.c:17]: this is to make sure we have many K-Frames (PDUs) to send an SDU. Since the bug was discovered with K-frames in the middle of an SDU.

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Comment by jori-nordic** [comment]
Sneak peek: @alwa-nordic and I are trying to get rid of `user_data` entirely https://github.com/jori-nordic/zephyr/pull/3/commits/295fc0871b230ea58c679162c7b6db3e40535575
