### PR TITLE
Bluetooth: controller: Fix Enc Setup overlap with Length Update

### LINKED ISSUE #15733: Bluetooth: controller: Central Encryption setup overlaps Length Request procedure
During the investigation of #15570 it has been discovered that fix in #15335 is broken.

Below is a copy of the central issue (https://github.com/zephyrproject-rtos/zephyr/issues/15570#issuecomment-487487731):

Case 2:
Central and Peripheral try to establish encryption
Both devices have bonding information.
Peripheral disconnects the link with MIC failure after receiving LL_LENGTH_RSP during encryption procedure.
Happens every time, devices are stuck in reconnect loop.

Problem 3:
Central initiates Encryption procedure before it has finished it's previously initiated Length Update Procedure

Problem 4:
Central Responds to peer initiated Length Procedure after it has sent LL_ENC_REQ PDU.
The central shall only send Disconnect or Encryption related PDUs at this point.

Problem 5:
Peripheral should have disconnected the link when receiving the Encryption request, before it has responded to the Length request.

Sniffer log: (3, 4 and 5)
mic_error_disconnect_on_reconnect

[mic_failure_sniffer_traces.zip](https://github.com/zephyrproject-rtos/zephyr/files/3126462/mic_failure_sniffer_traces.zip)

### PR DESCRIPTION
**Pull request by cvinayak**
Fix the encryption setup queueing implementation to avoid
overlapping with local initiated Length Update Procedure.

Fixes #15733.
Relates to #15335, and #15186.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ctrl.c [hunk 1]
```diff
@@ -9363,21 +9373,25 @@ static void prepare_pdu_data_tx(struct connection *conn,
...
 #endif /* CONFIG_BT_CTLR_DATA_LENGTH */
-	      0) && (conn->pkt_tx_head != conn->pkt_tx_ctrl))) {
+#if defined(CONFIG_BT_CTLR_LE_ENC)
+	      conn->pause_tx ||
+	      /* Encryption setup queued */
+	      (pause_tx = is_enc_req_pause_tx(conn)) ||
+#endif /* CONFIG_BT_CTLR_LE_ENC */
+	      0) &&
+	    /* Encryption setup queued or data paused */
+	    (pause_tx || (conn->pkt_tx_head != conn->pkt_tx_ctrl)))) {
```
Comment (mped-oticon) [inline subsys/bluetooth/controller/ll_sw/ctrl.c]: +1 for comments, that helps a lot.
But it is not obvious if all the corner cases of this massive-if are properly handled.

For complex branching like this, I personally like to factor out the logical meaning across const booleans, and let the booleans derive from the previous ones. With those, I can name them and comment on them to attain more readability.

**Review by mped-oticon — APPROVED** [review]
I can't really tell if this fixes anything though, because the code is still complex.
But I will not gate the change because of readability.

File: subsys/bluetooth/controller/ll_sw/ctrl.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ctrl.c]: I agree this is complex (have been on my mind, and gave it almost a week before I pushed ;-) ). It is this way trying to short circuit as early as possible to reduce CPU usage. But I may be incorrect based on how the compiler/linker could optimize if the code was written in a more readable fashion.

Example, a connection with only empty) packets use less CPU in comparison to when data is in the queue. And during a active encryption procedure, the call to is_enc_req_pause_tx is completely bypassed by conn->pause_tx, etc.

I am open to alternative implementations that meet the constraints.
