### PR TITLE
drivers: i2c: sam0: add support for I2C_MSG_RESTART

### LINKED ISSUE #55172: atmel sam0 I2C cannot read registers at a select address and must read entire chip
**Describe the bug**

When trying to read a single register via sam0 i2c bus, an extra address byte is sent on the wire.

I2C devices support reading a single byte by first writing the address with the RW bit set high, followed by writing a second byte which sets up an internal pointer register, followed by a subsequent read for clocking in the data from the remote device. The i2c_sam0 driver does not support this feature. the implementation of i2c_transfer intentionally sends the address byte with the start of every i2c_msg.

As partial workaround, I am able to use the driver to read the entire chip in one shot in order to target the register I want. However, not being able to select a specific register with a control byte write means I cannot use this driver to manage interrupts in a practical way (which are Clear on Read).

**To Reproduce**

Build any board that uses the i2c_sam0.c driver and enable the I2C_SHELL. Then try to read a single byte on the bus with the shell command i2c read_byte sercom@xxxxxxxxx ADDR REG and observe that 2 address bytes are sent on the wire.

**Other notes**

moved to issue from: https://github.com/zephyrproject-rtos/zephyr/discussions/55170

### PR DESCRIPTION
**Pull request by attie-argentum**
This PR reinstates support for I2C repeated starts, that was accidentally removed in the re-shuffle in de18f97...

Fixes #55172

### CODE REVIEW

File: drivers/i2c/i2c_sam0.c [hunk 1]
```diff
@@ -155,7 +155,20 @@ static void i2c_sam0_isr(const struct device *dev)
...
+			 * writing to i2c->ADDR for the next message will cause a repeated
+			 * start condition. this is different to continue_next, as the
+			 * data->msg.size is already at zero (not one), and
+			 * i2c_sam0_transfer() is responsible for advancing to the next
+			 * message, not this ISR.
+			 */
+			if ((data->num_msgs <= 1)
+			    || (data->msgs[0].flags & I2C_MSG_STOP)
+			    || !(data->msgs[1].flags & I2C_MSG_RESTART)) {
+				i2c->CTRLB.bit.CMD = 3;
```
Comment (nandojve) [inline drivers/i2c/i2c_sam0.c:169]: Since this is a complex operation I don't mind to have a description about what 3 means, like

```diff
+				/* 3 - Execute acknowledge action succeeded
+				 *     by issuing a Stop condition
+				 */
				i2c->CTRLB.bit.CMD = 3;
```

**Review by nandojve — CHANGES_REQUESTED** [review]

**Comment by attie-argentum** [comment]
@nandojve - thanks for the suggestion, I've reworked the comment to discuss this subtlety.

**Review by nandojve — APPROVED** [review]

**Review by teburd — APPROVED** [review]
