### PR TITLE
tests: posix: common: clock: exclude ehl_crb from test posix realtime

### LINKED ISSUE #33544: ehl_crb: portability.posix.common.posix_realtime failed.
**Bug Description**
The `posix_realtime` test in the /tests/posix/common test suite is failing due to assert:

```
Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/clock.c:75: test_posix_realtime: (rts.tv_nsec not equal to mts.tv_nsec)
```

This is observed in the other configurations of [testcase.yml](https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/posix/common/testcase.yaml) 
- portability.posix.common
- portability.posix.common.newlib
- portability.posix.common.tls
- portability.posix.common.tls.newlib

**To Reproduce**
1. Example for a single configuration: west build -b ehl_crb -p auto tests/posix/common/
    --DCONFIG_NEWLIB_LIBC=n
2. copy binary to USB/PXE boot media
3. boot

**Logs and console output**
Booting Zephyr OS build zephyr-v2.5.0-1430-g911ba334a06a
...
START - test_posix_recursive_mutex
recrusive mutex lock is taken
PASS - test_posix_recursive_mutex in 0.4 seconds

START - test_posix_mqueue
PASS - test_posix_mqueue in 0.11 seconds

**START - test_posix_realtime
POSIX clock set APIs
Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/clock.c:75: test_posix_realtime: (rts.tv_nsec not equal to mts.tv_nsec)
Nanoseconds not equal
FAIL - test_posix_realtime in 0.19 seconds**

START - test_posix_timer
POSIX timer test
Timer fires every 0 secs and  100000000 nsecs
Time remaining to fire 0 secs and  899000000 nsecs
Handler Signal value :20 for 1 times
Handler Signal value :20 for 2 times
Handler Signal value :20 for 3 times
Handler Signal value :20 for 4 times
Handler Signal value :20 for 5 times
Handler Signal value :20 for 6 times
Handler Signal value :20 for 7 times
Handler Signal value :20 for 8 times
Handler Signal value :20 for 9 times
Handler Signal value :20 for 10 times
Handler Signal value :20 for 11 times
Handler Signal value :20 for 12 times
PASS - test_posix_timer in 2.112 seconds

**Environment (please complete the following information):**
 - OS: Fedora33
 - Toolchain: zephyr-sdk-0.12.3
 - Commit ID: 911ba334a06a

### PR DESCRIPTION
**Pull request by jenmwms**
> The ehl_crb board uses HPET timer which is susceptible to the bug
> of nonequal monotonic clock and realtime clock at the nanosecond
> level because it is slower. This excludes the board from ns-level
> check. Other boards can still use the ns-level check.

Edit: 
The ehl_crb board has hardware issue that prevents this test from
being able to pass this otherwise-correct test. So exclude ehl_crb
from the testcase.yaml.

Fixes #33544.

Signed-off-by: Jennifer Williams <jennifer.m.williams@intel.com>

### CODE REVIEW

File: tests/posix/common/src/clock.c [hunk 1]
```diff
@@ -72,8 +72,13 @@ void test_posix_realtime(void)
 	zassert_equal(ret, 0, "Fail to get realtime clock");
 
 	zassert_equal(rts.tv_sec, mts.tv_sec, "Seconds not equal");
-	zassert_equal(rts.tv_nsec, mts.tv_nsec, "Nanoseconds not equal");
 
+#ifdef CONFIG_BOARD_EHL_CRB
```
Comment (jhedberg) [inline tests/posix/common/src/clock.c:76]: Since you say the issue is with HPET, would it make more sense to test for `CONFIG_HPET_TIMER` instead of a specific board?

Comment (dcpleung) [reply tests/posix/common/src/clock.c:76]: HPET implementation can run at high frequency. IIRC, most PC HPET timer are running at 19.2MHz or 25MHz.

Comment (nashif) [reply tests/posix/common/src/clock.c:76]: please just exclude it in the testcase.yaml

**Review by nashif — CHANGES_REQUESTED** [review]

File: tests/posix/common/src/clock.c (hunk 1 above)
Comment (jenmwms) [reply tests/posix/common/src/clock.c]: Thanks for asking. It seemed more an issue with EHL but also HPET timer so wasn't quite sure. Great to have feedback. 

But turns out this is not a favored way to approach this issue anyway. fwiw I was trying to preserve the rest of the test_posix_realtime() for EHL as well since we only had issue at a particular granularity and could still exercise most of the test otherwise. Alas, this is not correct so I've adapted to the feedback (moved to exclude the platform in testcase.yaml). Thanks all!

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]

**Review by chen-png — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
