### PR TITLE
Bluetooth: Controller: Fix extended scanning assertion

### LINKED ISSUE #67365: Bluetooth Controller: Not able to find extended advertising until after a few minutes after no BLE devices in the area for ~30 minutes
**Describe the bug**
If we leave the scanner in an area without BLE devices for about 30 minutes and then turn on an advertiser with extended advertising it takes about 2-4 minutes until the extended advertiser is seen. Even adding 20+ advertisers, none are found until after this 2-4 minute delay.

The applications here use periodic advertising and syncing. Periodic advertising may not be needed, as the issue seems to be with extended scanning, however it could be caused due to periodic syncing.

It's not enough to leave the scanner without BLE devices for just a few minutes, about 30 minutes it has to be left idle/without BLE devices.

**Please also mention any information which could help others to understand
the problem you're facing:**
 - What target platform are you using?
   - nRF52833 
 - What have you tried to diagnose or workaround this issue:
   - Been debugging and looking around a bit in the BLE controller when it happens and it seems as the scanner finds the `ADV_EXT_IND` but fails moving to and looking for the `AUX_ADV_IND`.
 - Is this a regression?
   - Issue both in Zephyr 3.3 and main branch

**To Reproduce**
Right now I can only reproduce in our BLE AoA Locator application only. It's based on Zephyr 3.3, however I have successfully replaced the BLE Controller from Zephyr main and can still reproduce the issue. So I think it's safe to say the issue still exists in Zephyr main.

I'm in progress of trying to create a sample application based on `samples/bluetooth/direction_finding_connectionless_rx` to reproduce the issue but so far have not succeeded.

**Below is the steps to reproduce**
1. Put a scanner and an advertiser inside a shielded box.
2. Turn on advertiser.
3. Wait for it it sync.
4. Turn off advertiser
5. Wait ~30 minutes
6. Turn on advertiser
7. Now it will take 3-4 minutes until the scanner prints out scan info and manages to sync with the advertiser.

**Expected behavior**
Finding extended advertising without large delay.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper):
- We have customer in field with this issue so for us important to find a solution as soon as possible.

**Environment (please complete the following information):**
 - OS: Linux
 - Commit SHA: main as of day of issue creation 72c6ffb2d04bf1d9c23e0ef71464b3693d96ba98

**Other**
Initially discussed here with @cvinayak: https://discord.com/channels/720317445772017664/733036837576376341/1187715776690524190

### PR DESCRIPTION
**Pull request by cvinayak**
Fix extended scanning assertion after long duration.

Fixes #67365.

### CODE REVIEW

**Review by PavelVPV — APPROVED** [review]

**Review by alxelax — COMMENTED** [review]
Could I get any elaboration why some timing in mesh tests was increased? 
Were there collisions, where it happens, what was collided?
Now it seems like magic numbers. How to maintain it further if don't have any clue the reasons.

File: tests/bsim/bluetooth/mesh/src/test_provision.c [hunk 1]
```diff
@@ -1009,11 +1009,11 @@ static void test_provisioner_pb_remote_client_parallel(void)
 	/* scanning device with dev index 3 */
 	uuid[6] = '0' + 3;
 	uuid_to_provision_remote = uuid;
-	ASSERT_OK(bt_mesh_rpr_scan_start(&rpr_cli, &srv, uuid, 5, 1, &scan_status));
+	ASSERT_OK(bt_mesh_rpr_scan_start(&rpr_cli, &srv, uuid, 15, 1, &scan_status));
 	ASSERT_EQUAL(BT_MESH_RPR_SUCCESS, scan_status.status);
 	ASSERT_EQUAL(BT_MESH_RPR_SCAN_SINGLE, scan_status.scan);
 	ASSERT_EQUAL(1, scan_status.max_devs);
-	ASSERT_EQUAL(5, scan_status.timeout);
+	ASSERT_EQUAL(15, scan_status.timeout);
```
Comment (alxelax) [inline tests/bsim/bluetooth/mesh/src/test_provision.c:1016]: Commit message says the scanner time is delayed, but there is scanning time in 3 times bigger than before.

Comment (PavelVPV) [reply tests/bsim/bluetooth/mesh/src/test_provision.c:1016]: I extended it by 10 seconds as the unprovisioned beacon interval is 10 second so if it misses the first beacon, the second one it should receive.

**Comment by PavelVPV** [comment]
> Could I get any elaboration why some timing in mesh tests was increased? Were there collisions, where it happens, what was collided? Now it seems like magic numbers. How to maintain it further if don't have any clue the reasons.

Lost packet like in other our tests.

File: tests/bsim/bluetooth/mesh/src/test_provision.c (hunk 1 above)
Comment (cvinayak) [reply tests/bsim/bluetooth/mesh/src/test_provision.c:1016]: Should we use a factor of the MESH_INTERVAL define or a define derived from it? I.e instead of magic numbers?

Comment (alxelax) [reply tests/bsim/bluetooth/mesh/src/test_provision.c:1016]: I meant the tests fall from time to time due to collisions when something new is added or changed. After this, some fixes with delays appear. Furthermore, the reason for them is forgotten after some time, and difficult to understand whether it is valid or not anymore.

**Review by alxelax — APPROVED** [review]
