### PR TITLE
drivers: bluetooth: stm32wb: Set HCI driver compatible with HCI_RAW mode

### LINKED ISSUE #46075: BT HCI Raw on STM32WB55RG
**Describe the bug**
Hi,
I need to do some Direct Test Mode for BT and I tried to build Zephyr hci_raw module to run one of prepared example from Zephyr: /zephyr/samples/bluetooth/hci_uart/.
It seems that there are some kind of dependencies and it's impossible to build HCI_Raw on STM32WB55RG.
I used sources and configuration from example and tried to build it, but it failed while linking, due to undefined references to:
'bt_hci_cmd_create' and 'bt_hci_cmd_send_sync' in /zephyr/drivers/bluetooth/hci/ipm_stm32wb.c, looks like this driver depends on HCI Core, which excludes HCI Raw.
I wasn't able to use other drivers too (maybe my configuration for other drivers wasn't full - I tried: CONFIG_BT_H4 instead of CONFIG_BT_STM32_IPM, which is taken by default). 
Is there any possibility to build HCI Raw with STM32WB55RG and run Direct Test Mode?

**To Reproduce**
Build example: /zephyr/samples/bluetooth/hci_uart/ on STM32WB55RG.

**Expected behavior**
I can build and run HCI Raw module on WB55RG.

### PR DESCRIPTION
**Pull request by erwango**
Current implementation of stm32wb HCI driver uses functions of hci_core driver to send specific messages.
This makes the driver incompatible with BT_HCI_RAW mode.

Provide some adaptations to allow use of BT_HCI_RAW mode on STM32WB
- Remove the HCI_RESET sending as this is available in hci_core.
- Put sending of ACI_HAL_* messages under !BT_HCI_RAW as these messages are not needed for test mode.

Add a c2h chosen to allow building hci_uart sample.

Fixes #46075

### CODE REVIEW

**Comment by erwango** [comment]
@r2r0

**Comment by sebachm94** [comment]
Hi @erwango!
I've tried the changes you made and seems that, it's working! I was able to build one of samples (/zephyr/samples/bluetooth/hci_uart/) on my NUCLEO-WB55RG. I've sent some HCI commands to Core over UART and it responds. There is anything else you wish me to check?

PS.
Thank you for solving the issue quickly!

**Comment by erwango** [comment]
> I've tried the changes you made and seems that, it's working! I was able to build one of samples (/zephyr/samples/bluetooth/hci_uart/) on my NUCLEO-WB55RG. I've sent some HCI commands to Core over UART and it responds. There is anything else you wish me to check?

Thanks for the test and the heads up!
I'll clean this draft and convert to PR. Would you mind reviewing and +1 once its ready ?

**Comment by sebachm94** [comment]
Sure, just ping me when it's ready! :)

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 1]
```diff
@@ -63,14 +63,14 @@ struct aci_set_ble_addr {
 	uint8_t value[6];
 } __packed;
 
+#ifndef CONFIG_BT_HCI_RAW
```
Comment (jhedberg) [inline drivers/bluetooth/hci/ipm_stm32wb.c:66]: Would it make sense to use `#ifdef CONFIG_BT_HCI_HOST` instead of `#ifndef CONFIG_BT_HCI_RAW`? In practice those should give the same result.

Alternatively, any chance you could use `#if !defined(CONFIG...)` instead of `#ifndef`? Maybe it's just me me, but I read `#ifndef` too easily as `#ifdef` (since that's the common paradigm).

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/ipm_stm32wb.c (hunk 1 above)
Comment (erwango) [reply drivers/bluetooth/hci/ipm_stm32wb.c:66]: Your both points make sense. I'll opt for `#ifdef CONFIG_BT_HCI_HOST` which is more direct from logical perspective.

Comment (erwango) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Fixed.

**Review by jhedberg — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by sebachm94 — APPROVED** [review]
