### PR TITLE
mgmt/osdp: Fix couple of issues identified by coverity

### LINKED ISSUE #33092: [Coverity CID :215392] Logically dead code in subsys/mgmt/osdp/src/osdp_cp.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/subsys/mgmt/osdp/src/osdp_cp.c

Category: Control flow issues
Function: `cp_build_command`
Component: Other
CID: [215392](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=215392)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/subsys/mgmt/osdp/src/osdp_cp.c

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #33095: [Coverity CID :215379] Out-of-bounds write in subsys/mgmt/osdp/src/osdp_cp.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/subsys/mgmt/osdp/src/osdp_cp.c

Category: Memory - corruptions
Function: `cp_decode_response`
Component: Other
CID: [215379](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=215379)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/subsys/mgmt/osdp/src/osdp_cp.c

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by sidcha**
Fix couple of issues identified by coverity.

Fixes: #33095
Fixes: #33092

### CODE REVIEW

**Review by nashif — APPROVED** [review]

File: subsys/mgmt/osdp/src/osdp_cp.c [hunk 1]
```diff
@@ -101,37 +101,10 @@ static int cp_build_command(struct osdp_pd *pd, uint8_t *buf, int max_len)
 
 	switch (pd->cmd_id) {
 	case CMD_POLL:
-		if (max_len < CMD_POLL_LEN) {
```
Comment (ceolin) [inline subsys/mgmt/osdp/src/osdp_cp.c:104]: Can you add an explicit `__fallthrough`  on this empty cases ? Other than that looks great to me

**Review by ceolin — APPROVED** [review]

File: subsys/mgmt/osdp/src/osdp_cp.c (hunk 1 above)
Comment (cbsiddharth) [reply subsys/mgmt/osdp/src/osdp_cp.c:104]: Added.
