### PR TITLE
Bluetooth: controller: split: Fix radio in use during flash op

### LINKED ISSUE #22945: Bluetooth: controller: ASSERTION FAIL Radio is on during flash operation
**Describe the bug**
Flash operations on nrf52840_pca10056 tests/bluetooth/shell raises ASSERTION FAIL.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=nrf52840_pca10056 ../tests/bluetooth/shell
3. make

**Expected behavior**
There shall be no assertion and flash operations succeed.

**Impact**
showstopper

**Screenshots or console output**
```
uart:~$ bt init
Bluetooth initialized
uart:~$ bt[00:00:03.854,278] <inf> fs_nvs: 8 Sectors of 4096 bytes
[00:00:03.854,309] <inf> fs_nvs: alloc wra: 1, fc0
[00:00:03.854,309] <inf> fs_nvs: data wra: 1, 34
[00:00:03.857,086] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[00:00:03.857,086] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
[00:00:03.857,086] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.2 Build 0
[00:00:03.857,666] <inf> bt_hci_core: No ID address. App must call settings_load()
[00:00:03.868,041] <inf> bt_hci_core: Identity: ea:c8:5c:41:6e:de (random)
[00:00:03.868] <inf> bt_hci_core: LMP: version 5.1 (0x0a) subver 0xffff
...
...
uart:~$ bt connect 62:aa:1d:d4:2a:de (random)
Connection pending
Connected: 62:aa:1d:d4:2a:de (random)
Remote LMP version 5.1 (0x0a) subversion 0xffff manufacturer 0x05f1
LE Features: 0x000000000001417f 
[00:00:22.419,464] <inf> bt_hci_core: PHY updated (0x0): status: 0x00, tx: 2, rx: 2
[00:00:22.429,077] <inf> bt_hci_core: Data Length (0x0): max. tx: 27 (328us), max. rx: 27 (164us)
[00:00:22.436,584] <inf> bt_hci_core: Data Length (0x0): max. tx: 27 (328us), max. rx: 27 (328us)
LE conn  param req: int (0x0018, 0x0028) lat 0 to 42
LE conn param updated: int 0x0028 lat 0 to 42
...
...
uart:~$ bt conn-update 6 6 0 64
conn update initiated.
LE conn param updated: int 0x0006 lat 0 to 100
uart:~$ 
...
...
uart:~$ flash test 0xf8000 0x1000 100
Erase OK.
Write OK.
...
...
Erase OK.
Write OK.
ASSERTION FAIL [ll_radio_state_is_idle()] @ ZEPHYR_BASE/drivers/flash/soc_flash_nrf.c:287
        Radio is on during flash operation.

ASSERTION FAIL [!arch_is_in_isr()] @ ../../kernel/include/ksched.h:262

ASSERTION FAIL [!arch_is_in_isr()] @ ../../kernel/include/ksched.h:262
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.11.1
 - Commit SHA or Version used: a9bfd28a39

**Additional context**
Add any other context about the problem here. None.

### PR DESCRIPTION
**Pull request by cvinayak**
Fix a race condition in radio abort requested by flash
driver. It is possible that during abort function execution,
PPI setup to start radio fires. Hence, check explicitly in
cleanup function for radio being in use and disable it.

Fixes #22945.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
Is #22926 related to this? (it also deals with Bluetooth + flash coexistence)

**Comment by cvinayak** [comment]
This is not related to #22926, I stumbled on the issue in this PR during analysis of #22926.

**Review by thoh-ot — DISMISSED** [review]
We need time to review the impact of the ticker changes.

**Comment by cvinayak** [comment]
Ticker fixes are related, when the radio assert is handled, the flashing times out as ticker is not scheduling both the connection and flash instances. There is periodic Worker and Job executions but both the instances are skipped always.

image

And this leads to:
```
...
Write OK.
Erase OK.
Write OK.
Erase OK.
Write internal ERROR!
```

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 1]
```diff
@@ -654,15 +654,18 @@ static u8_t ticker_resolve_collision(struct ticker_node *nodes,
 		while (id_head != TICKER_NULL) {
 			struct ticker_node *ticker_next = &nodes[id_head];
 
+			/* Accumulate ticks_to_expire for each node */
+			acc_ticks_to_expire += ticker_next->ticks_to_expire;
+			if (acc_ticks_to_expire > ticker->ticks_slot) {
+				break;
```
Comment (mtpr-ot) [inline subsys/bluetooth/controller/ticker/ticker.c]: Am I right in saying that this is an optimization - breaking here? (instead of possibly traversing more tickers)

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 2]
```diff
@@ -1400,8 +1402,9 @@ static inline void ticker_job_worker_bh(struct ticker_instance *instance,
 				/* Reload ticks_to_expire with one period */
 				ticker->ticks_to_expire =
 					ticker->ticks_periodic;
+				ticker->ticks_to_expire +=
+					ticker_remainder_inc(ticker);
```
Comment (mtpr-ot) [inline subsys/bluetooth/controller/ticker/ticker.c]: Correct, this is needed for Nordic!

**Review by mtpr-ot — APPROVED** [review]
Looks good, thanks for fixing. All automated tests pass on our side (ticker unittests, EDTT tests and target integration tests)

**Comment by jhedberg** [comment]
@mtpr-ot I'm tempted to merge this, but does your addition of @thoh-ot as reviewer mean that I should wait for feedback from him before merging?

**Comment by jhedberg** [comment]
> @mtpr-ot I'm tempted to merge this, but does your addition of @thoh-ot as reviewer mean that I should wait for feedback from him before merging?

Nevermind. I see that an earlier review from @thoh-ot is blocking merging this either way.
