### PR TITLE
usb: bluetooth: do not start transfers when USB bus is suspended 

### LINKED ISSUE #40776: HCI_USB with nRF52840 dongle disconnect after 30 s
Hi,

**Describe the bug**

I try to connect simultaneous 12 BLE devices to a Linux PC with Bluez.
Commercial controllers cannot go beyond 5 connections. I am using an nRF52840 dongle.

I use the hci_usb sample flashed by dfu.

On the PC, the 12 connections are made without problems with bluetoothctl.
Only after about 30s, a device disconnects.
It is not necessarily the same and it is possible to reconnect afterwards but this disconnection is a problem for my application.

It is not at the level of the devices, nor of the bluetoothctl commands since everything works with a commercial BLE controller (only for 5 devices).

Before the disconnection, the bluetoothctl "info" command line indicates that the device is connected and displays the list of all BLE services. 

I also tested with the nRF52832 DK board and the hci_uart example for the same result.

Is there a way to solve this problem? 

**Logs and console output**

With btmon, I get the disconnection reason : Remote User Terminated Connection
HCI Command: Disconnect (0x01|0x0006) plen 3                                            
        Handle: 0
        Reason: Remote User Terminated Connection (0x13)

**Environment:**

OS: Linux Mint, bluez 
Toolchain: Zephyr SDK: Zephyr from master or v2.7.99.

**Additional context**

None

### PR DESCRIPTION
**Pull request by jfischer-no**
Do not start transfers when USB bus is suspended.
If the bus is suspended, initiate remote-wakeup and
wait until the bus is operational.

Allow to disable option USB_DEVICE_REMOTE_WAKEUP.

Fixes: #40776

### CODE REVIEW

File: subsys/usb/class/bluetooth.c [hunk 1]
```diff
@@ -126,6 +126,20 @@ static void hci_tx_thread(void)
...
+			}
+			/*
+			 * Let's wait until operation is resumed.
+			 * This is independent of usb_wakeup_request() result,
+			 * as long as device is suspended it should not start
+			 * any transfers.
+			 */
+			while (suspended) {
+				k_sleep(K_MSEC(1));
+			}
```
Comment (cvinayak) [inline subsys/usb/class/bluetooth.c:141]: 1. I assume `suspended` is volatile?
2. Can `k_sem_take` construct be used instread of `k_sleep` wait?

Comment (jfischer-no) [reply subsys/usb/class/bluetooth.c:141]: > Can k_sem_take construct be used instread of k_sleep wait?

Why and for what benefit?

Comment (carlescufi) [reply subsys/usb/class/bluetooth.c:141]: To avoid having to wake up periodically to check. Instead you'd have some other code asynchronously post `k_sem_give()`.

Comment (carlescufi) [reply subsys/usb/class/bluetooth.c:141]: The `volatile` is necessary if `suspended` is being set from a different context that can be preempted or that can preempt, so I agree with @cvinayak that this might be required.

Comment (cvinayak) [reply subsys/usb/class/bluetooth.c:141]: As we are in a while loop, without `suspended` being quailified as volatile would mean a register storage will be used and no fresh memory access will happen, potentially causing a deadlock in this while loop.

Use of semaphore signal  on change to `suspended` will avoid an upto 1 ms latency in the USB transport on wakeup.

**Review by cvinayak — DISMISSED** [review]

File: subsys/usb/class/bluetooth.c (hunk 1 above)
Comment (jfischer-no) [reply subsys/usb/class/bluetooth.c:141]: >To avoid having to wake up periodically to check. Instead you'd have some other code asynchronously post k_sem_give().

This some code would add unnecessary complexity.

**Comment by jfischer-no** [comment]
>As we are in a while loop, without suspended being quailified as volatile would mean a register storage will be used and no fresh memory access will happen, potentially causing a deadlock in this while loop.

I simply cannot agree with that. Why should suspended become register storage-class specifier without volatile and by whom? Why should this thread when it sleeps prevent others from updating memory? Rather, it could happen that _not updated_ suspended == true condition will be unnoticed.

>Use of semaphore signal on change to suspended will avoid an upto 1 ms latency in the USB transport on wakeup.

1 ms is minimum expected resume time (resume signaling TDRSMUP 1ms .. 15ms + some recovery time), here on average (1 root hub in between) of 5ms, and then it does not mean that controller event arrives immediately by the host.

File: subsys/usb/class/bluetooth.c (hunk 1 above)
Comment (cvinayak) [reply subsys/usb/class/bluetooth.c:141]: It is not complex and most simplest synchronization (there many more such use across zephyr, I believe), see for example here: https://github.com/zephyrproject-rtos/zephyr/blob/a3c91034cd5aa54c5f605044ee7bbacfd395c0be/drivers/clock_control/clock_control_nrf.c#L381-L406

**Comment by cvinayak** [comment]
> Why should suspended become register storage-class specifier without volatile and by whom

Atleast in ARM, arithmetic and logic operations are performed as register operands

> Why should this thread when it sleeps prevent others from updating memory?

The sleep does not prevent the updating of memory, but on resumption in the loop then the updated memory shall be loaded into register everytime.

`suspended` being global and the loop having a function should make the compiler generate code to reload `suspended` everytime, but using the `volatile` qualifier make implementation explicit, see for example when the function is not present then there is no reload (of r3 register) in the generated code:
image

Now with volatile added:
image

**Comment by jfischer-no** [comment]
> > Why should suspended become register storage-class specifier without volatile and by whom
> 
> Atleast in ARM, arithmetic and logic operations are performed as register operands

That is not what I mean.

> > Why should this thread when it sleeps prevent others from updating memory?
> 
> The sleep does not prevent the updating of memory, but on resumption in the loop then the updated memory shall be loaded into register everytime.
> 
> `suspended` being global and the loop having a function should make the compiler generate code to reload `suspended` 

suspended has static storage-class specifier, no side effects, no mem based io.

>everytime, but using the `volatile` qualifier make implementation explicit, see for example when the function is not present then there is no reload (of r3 register) in the generated code: ...
> 
> Now with volatile added: ...

I am not sure what you are comparing, but it is more than:
```diff
diff --git a/subsys/usb/class/bluetooth.c b/subsys/usb/class/bluetooth.c
index b6a93012fbd..eee1e7dbd09 100644
--- a/subsys/usb/class/bluetooth.c
+++ b/subsys/usb/class/bluetooth.c
@@ -42,7 +42,7 @@ static struct k_thread tx_thread_data;
 
 /* HCI USB state flags */
 static bool configured;
-volatile static bool suspended;
+static bool suspended;
 
 static uint8_t ep_out_buf[USB_MAX_FS_BULK_MPS];
```
With arm-none-eabi-gcc 10.3.1, I do not see any difference, with or without volatile. Of course, it can be different with other compilers, but IMHO unlikely with modern compilers and this code.

**Comment by cvinayak** [comment]
The comparison is " the function is not present " in side the while loop. in C99 standard (if my memory serves right), compiler assumes that global variable could be modified by an external function inside the loop, hence you do not see the difference between volatile and no volatile, but as soon as compiler is able to see the contents of the function inside the while loop it can take a decision not to load the register from memory.

**Review by carlescufi — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Comment by cfriedt** [comment]
@jfischer-no - is the issue also present in `v2.7-branch`?

**Comment by cfriedt** [comment]
> @jfischer-no - is the issue also present in `v2.7-branch`?

Looks to be that way based on comments in the linked issue. I'll add the backport.

**Comment by jfischer-no** [comment]
> Looks to be that way based on comments in the linked issue. I'll add the backport.

@cfriedt Zephyr 2.7.0 is not affected, see https://github.com/zephyrproject-rtos/zephyr/issues/40776#issuecomment-983521465
