### PR TITLE
drivers: flash: flash_mcux_flexspi: add support for W25Q512NW-IQ/IN

### LINKED ISSUE #80592: Not possible to write beyond 16MB using flash sample on RT1170 EVKB
**Describe the bug**
It is currently not possible to write beyond 16MB of address space using the flash shell sample on the RT1170 EVKB, despite the flash chip being 64MB.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `mimxrt1170_evkb//cm7`

**To Reproduce**
1. `west build -p always -b mimxrt1170_evk@B//cm7 samples/drivers/flash_shell
2. `west flash`
3. Attempt to read or write to address beyond `0xFFFFFF`
4. Reads will return `0x0`, writes will fail silently (or report verification errors)

**Expected behavior**
Flash writes should not fail beyond 8MB

**Impact**
MCUBoot support may be affected, otherwise applications using the flash will be limited to 16MB.

### PR DESCRIPTION
**Pull request by danieldegrasse**
Add support for the W25Q512NW-IQ/IN with the FLEXSPI, using a custom
LUT table.

This PR also corrects the FLEXSPI frequency check for the RT1170 SOC, which was previously reclocking the FlexSPI to 24 MHz when running in XIP mode.

~Note this change depends on #80016, and contains commits from that PR until it merges~

Tested on `mimxrt1170_evk//cm7` and `mimxrt1170_evk@B//cm7` with `samples/drivers/flash_shell`

Fixes #80592

### CODE REVIEW

**Comment by decsny** [comment]
you might want to run clang format on the lines you are adding, you can run clang format on a line range

File: drivers/flash/flash_mcux_flexspi_nor.c [hunk 1]
```diff
@@ -1008,6 +1008,37 @@ static int flash_flexspi_nor_check_jedec(struct flash_flexspi_nor_data *data,
 		/* Device uses bit 1 of status reg 2 for QE */
 		return flash_flexspi_nor_quad_enable(data, flexspi_lut,
 						     JESD216_DW15_QER_VAL_S2B1v5);
+	case 0x60ef:
```
Comment (de-nordic) [inline drivers/flash/flash_mcux_flexspi_nor.c:1011]: I have just noticed that device identification here is done by two bytes only, which is not correct.
The W25Q512 IQ, full id 0xef6020 or 0xef8020 (the second bytes indicate QE fixed/select),  has the same two bytes as w25Q128 0xef6019.
This means that the below identification may by mistake set 4 byte address config to 3 byte address device, which neither supports 133MHz operation nor configured commands.

Comment (danieldegrasse) [reply drivers/flash/flash_mcux_flexspi_nor.c:1011]: Good catch- would you like me to add a commit to this PR extending the device ID check for all the flash chips here?

Comment (de-nordic) [reply drivers/flash/flash_mcux_flexspi_nor.c:1011]: I think that this can be too much of a  change for this PR, just add if within case to filter out the w25Q128, using the last byte, or configure it properly. 
I do not think it is proper to fix everything in this PR and you will have to go through docs to gather info which will probably delay the PR till  you are ready.

Comment (danieldegrasse) [reply drivers/flash/flash_mcux_flexspi_nor.c:1011]: Ok, I've added a check to skip configuration if the full ID does not match the W25Q512NW. I don't have hardware to verify on at the moment, but reading the datasheet I believe the vendor ID should be read as `0x2060ef`

**Review by de-nordic — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Comment by decsny** [comment]
should this have bug label and 4.0 milestone
