### PR TITLE
usb: device_next: support BOS descriptor with vendor request code

### LINKED ISSUE #76224: usb: device_next: unable to handle vendor requests in address state
**Describe the bug**
The design of the USB `device_next` stack prevents the use of MSOSv2 descriptors.

The device-to-host vendor request targeting the device for the `bMS_VendorCode` is sent in the `address` state, which causes `usbd_config_get_current()` (called from `usbd_class_get_by_req()` to determine which class implementation to forward the vendor request to) to return `NULL`, as no configuration has been set yet.

**Expected behavior**
Vendor requests targeting the device should be allowed in the `address` state.

Another possible solution could be to add a dedicated, application-level usbd callback for handling requests targeting the device. This would likely allow for a nicer application architecture.

**Impact**
Unable to use MSOSv2 descriptors with USB `device_next`.

**Environment (please complete the following information):**
 - OS: Any
 - Toolchain: Any
 - Commit SHA: v3.7.0-rc3

**Additional context**
Discord thread on this topic: https://discord.com/channels/720317445772017664/733037537982939236/1265216134970478685

### PR DESCRIPTION
**Pull request by jfischer-no**
Support BOS descriptor with vendor request code and add WebUSB sample for the new USB device stack.

### CODE REVIEW

File: subsys/usb/device_next/usbd_ch9.c [hunk 1]
```diff
@@ -913,6 +913,55 @@ static int std_request_to_host(struct usbd_context *const uds_ctx,
 	return ret;
 }
 
+static struct usbd_desc_node *usbd_get_bos_vreq(struct usbd_context *const uds_ctx,
+						const uint8_t vcode)
+{
+	struct usbd_desc_node *desc_nd;
+
+	SYS_DLIST_FOR_EACH_CONTAINER(&uds_ctx->descriptors, desc_nd, node) {
```
Comment (tmon-nordic) [inline subsys/usb/device_next/usbd_ch9.c:921]: Why abuse the descriptors list? I think it would be better to just have a separate list for the vendor requests. The vendor requests should not be limited to BOS-only, but generally any vendor (here: application developer) should be able to provide their own vendor commands in application.

File: samples/subsys/usb/webusb/src/msosv2.h [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+				MIN(net_buf_tailroom(buf), sizeof(msosv2_desc)));
+
+		return 0;
+	}
+
+	return -ENOTSUP;
+}
+
+USBD_DESC_BOS_VREQ_DEFINE(bos_vreq_msosv2, sizeof(bos_msosv2_desc), &bos_msosv2_desc,
+			  SAMPLE_MSOS2_VENDOR_CODE, msosv2_to_host_cb, NULL);
```
Comment (tmon-nordic) [inline samples/subsys/usb/webusb/src/msosv2.h:114]: Why this is defined in a header?

File: samples/subsys/usb/webusb/src/webusb.h [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+				MIN(net_buf_tailroom(buf), sizeof(webusb_origin_url)));
+
+		return 0;
+	}
+
+	return -ENOTSUP;
+}
+
+USBD_DESC_BOS_VREQ_DEFINE(bos_vreq_webusb, sizeof(bos_cap_webusb), &bos_cap_webusb,
+			  SAMPLE_WEBUSB_VENDOR_CODE, webusb_to_host_cb, NULL);
```
Comment (tmon-nordic) [inline samples/subsys/usb/webusb/src/webusb.h:88]: Why this is defined in a header?

File: samples/subsys/usb/webusb/src/msosv2.h [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+#define WEBUSB_DEVICE_INTERFACE_GUID \
+	'{', 0x00, 'F', 0x00, 'A', 0x00, '6', 0x00, '1', 0x00, '1', 0x00, \
+	'C', 0x00, 'C', 0x00, '3', 0x00, '-', 0x00, '7', 0x00, '0', 0x00, \
+	'5', 0x00, '7', 0x00, '-', 0x00, '4', 0x00, '2', 0x00, 'E', 0x00, \
+	'E', 0x00, '-', 0x00, '9', 0x00, 'D', 0x00, '8', 0x00, '2', 0x00, \
+	'-', 0x00, '4', 0x00, '9', 0x00, '1', 0x00, '9', 0x00, '6', 0x00, \
+	'3', 0x00, '9', 0x00, '5', 0x00, '6', 0x00, '2', 0x00, 'B', 0x00, \
+	'3', 0x00, '}', 0x00, 0x00, 0x00, 0x00, 0x00
+
+struct msosv2_descriptor {
```
Comment (tmon-nordic) [inline samples/subsys/usb/webusb/src/msosv2.h:30]: Would it be possible to somehow take the advantage of the new stack to enable automatic `struct msosv2_function_subset_header` insertion when there is more than 1 interface?

The old stack did have https://github.com/zephyrproject-rtos/zephyr/pull/66449 as a solution, but that's fragile approach.

**Review by tmon-nordic — CHANGES_REQUESTED** [review]

File: subsys/usb/device_next/usbd_ch9.c (hunk 1 above)
Comment (jfischer-no) [reply subsys/usb/device_next/usbd_ch9.c:921]: > Why abuse the descriptors list? 

It is a descriptor and it does not abusing anything.

> I think it would be better to just have a separate list for the vendor requests. The vendor requests should not be limited to BOS-only, but generally any vendor (here: application developer) should be able to provide their own vendor commands in application.

There are no requirements in the specification to allow arbitrary vendor request with recipient device. Using the BOS platform capability is the most portable.

File: samples/subsys/usb/webusb/src/msosv2.h (hunk 2 above)
Comment (jfischer-no) [reply samples/subsys/usb/webusb/src/msosv2.h:114]: Why not? Or what is the problem? This is limited to a specific part and can be used as a template.

File: samples/subsys/usb/webusb/src/msosv2.h (hunk 4 above)
Comment (jfischer-no) [reply samples/subsys/usb/webusb/src/msosv2.h:30]: I do not think we can handle it. IMO it is better to write a comprehensive documentation about it, with some examples. I think the average user has no idea where and how to use MSOSv2 descriptors.

File: subsys/usb/device_next/usbd_ch9.c (hunk 1 above)
Comment (tmon-nordic) [reply subsys/usb/device_next/usbd_ch9.c:921]: How is this a descriptor? This is not descriptor in any way, just a way for application to register vendor commands. USB specification doesn't require the devices to implement any optional functionality (vendor commands are optional functionality). In this context the specification states "A device vendor may also define requests supported by the device.".

What do you mean by "most portable"? What does portability have to do with a stack functionality to allow application developer to support vendor commands?

File: samples/subsys/usb/webusb/src/msosv2.h (hunk 4 above)
Comment (tmon-nordic) [reply samples/subsys/usb/webusb/src/msosv2.h:30]: Comprehensive documentation is not a real solution but a way to avoid having to come up with a real solution. While the average user might not have idea about individual MSOSv2 descriptors, it would be good to provide "just-working" experience (if possible).

File: samples/subsys/usb/webusb/src/msosv2.h (hunk 2 above)
Comment (tmon-nordic) [reply samples/subsys/usb/webusb/src/msosv2.h:114]: Everything compilation unit that includes this header will have the variables in the corresponding object file.

**Review by henrikbrixandersen — COMMENTED** [review]
I would prefer a generic way to register vendor requests targeting the device (not a class nor an interface) from the application code. This could easily be used for handling MSOSv2 vendor requests, but wouldn't be limited to that (not all vendor requests would require a BOS).

File: subsys/usb/device_next/usbd_ch9.c (hunk 1 above)
Comment (jfischer-no) [reply subsys/usb/device_next/usbd_ch9.c:921]: Please familiarize yourself with how MSOS2 and WebUSB use the BOS descriptor, I am pretty sure you will understand it.

File: samples/subsys/usb/webusb/src/msosv2.h (hunk 2 above)
Comment (jfischer-no) [reply samples/subsys/usb/webusb/src/msosv2.h:114]: There is only that include it. So where is the problem?

**Comment by carlescufi** [comment]
@tmon-nordic @henrikbrixandersen can you please take another look?

File: samples/subsys/usb/webusb-next/src/msosv2.h [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+	'{', 0x00, 'F', 0x00, 'A', 0x00, '6', 0x00, '1', 0x00, '1', 0x00, \
+	'C', 0x00, 'C', 0x00, '3', 0x00, '-', 0x00, '7', 0x00, '0', 0x00, \
+	'5', 0x00, '7', 0x00, '-', 0x00, '4', 0x00, '2', 0x00, 'E', 0x00, \
+	'E', 0x00, '-', 0x00, '9', 0x00, 'D', 0x00, '8', 0x00, '2', 0x00, \
+	'-', 0x00, '4', 0x00, '9', 0x00, '1', 0x00, '9', 0x00, '6', 0x00, \
+	'3', 0x00, '9', 0x00, '5', 0x00, '6', 0x00, '2', 0x00, 'B', 0x00, \
+	'3', 0x00, '}', 0x00, 0x00, 0x00, 0x00, 0x00
+
+struct msosv2_descriptor {
+	struct msosv2_descriptor_set_header header;
```
Comment (tmon-nordic) [inline samples/subsys/usb/webusb-next/src/msosv2.h:31]: If not implement it right now, at least add a TODO: Add subset header when there is more than one interface.

See #66449 for more information.

**Review by tmon-nordic — CHANGES_REQUESTED** [review]
The new bRequest registration seems fine, just few things to fix.

File: include/zephyr/usb/usbd.h [hunk 6]
```diff
@@ -597,6 +647,21 @@ static inline void *usbd_class_get_private(const struct usbd_class_data *const c
...
+/**
+ * @brief Define a vendor request with recipient device
+ *
+ * @param name      Vendor request identifier
+ * @param vcode     Vendor request code
+ * @param vto_host  Vendor callback for to-host direction request
+ * @param vto_dev   Vendor callback for to-device direction request
+ */
+#define USBD_VREQUEST_DEFINE(name, vcode, vto_host, vto_dev)			\
+	static struct usbd_vreq_node name = {					\
```
[the remark this answers is not in the document]
Comment (jfischer-no) [reply include/zephyr/usb/usbd.h:663]: Then the user does not know the real structure name. This makes sense for more abstract macros, but not here.

File: samples/subsys/usb/webusb-next/src/msosv2.h (hunk 5 above)
Comment (jfischer-no) [reply samples/subsys/usb/webusb-next/src/msosv2.h:33]: I have aligned it with the descriptor in the legacy sample and added a comment.

**Review by tmon-nordic — APPROVED** [review]

**Comment by carlescufi** [comment]
@henrikbrixandersen PTAL

**Review by henrikbrixandersen — APPROVED** [review]
