### PR TITLE
drivers/flash: Add flash_get_parameters call to flash API

### LINKED ISSUE #22063: fs/NVS: NVS is not compatible with flash memories which have 0x00 as erased
**This is informative issue**, not a bu really
NVS design assumes 0xff as memory erased state. So it will doesn't work on devices which has 0x00 as erased byte state (e.g. some stm32 embedded. ~~and native_posix with the flash simulator~~ )

**To Reproduce**
~~Try NVS sample using native_posix target~~
[EDIT]: native_posix was fixed
Try NVS sample using a target which have 0x00 as erased byte flash value.

### PR DESCRIPTION
**Pull request by de-nordic**
Provided call returns const pointer to flash_parameters structure that can be used for passing memory parameters from drivers.

Resolves #22063

### CODE REVIEW

File: drivers/flash/Kconfig [hunk 1]
```diff
@@ -42,6 +42,33 @@ config FLASH_PAGE_LAYOUT
...
+	help
+	  Select value that corresponds to value of erased flash cell.
+
+config FLASH_ERASE_BYTE_FF
+	bool "Erased flash value is 0xFF"
+
+config FLASH_ERASE_BYTE_00
+	bool "Erased flash value is 0x00"
+
+endchoice
```
Comment (de-nordic) [inline drivers/flash/Kconfig:57]: Not sure whether the selection is needed or the default value should be just hardcoded to 0xff. Please advice.

Comment (nvlsianpu) [reply drivers/flash/Kconfig:57]: I would resign from FLASH_ERASE_BYTE_VAL - just implement the API for all the driver in the codebase.

File: include/drivers/flash.h [hunk 2]
```diff
@@ -296,6 +299,28 @@ static inline size_t z_impl_flash_get_write_block_size(struct device *dev)
...
+__syscall u8_t flash_get_erase_value(const struct device *dev);
+
+static inline u8_t z_impl_flash_get_erase_value(const struct device *dev)
+{
+#if defined(CONFIG_FLASH_ERASE_VAL)
+	const struct flash_driver_api *api =
+		(const struct flash_driver_api *)dev->driver_api;
+
+	return api->erase_value;
+#else
```
Comment (nvlsianpu) [inline include/drivers/flash.h:319]: else not needed - introduce this API to all driver instead.

**Review by nvlsianpu — CHANGES_REQUESTED** [review]

File: include/drivers/flash.h (hunk 2 above)
Comment (de-nordic) [reply include/drivers/flash.h:324]: So what you mean is: this is not configurable all drivers fill in the erase_value as an requirement?

Comment (nvlsianpu) [reply include/drivers/flash.h:324]: ^^ yes

Comment (nvlsianpu) [reply include/drivers/flash.h:324]: similar as FLASH_PAGE_LAYOUT

Comment (de-nordic) [reply include/drivers/flash.h:324]: OK, if for example the NVS is in use, which requires to know the erase value, then this should be enabled by the dependency, etc?

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
I like how code looks like now.
Is it possible to make `erased_val` configurable for flash simulator via DTS?
Is it then possible to add test-case with either 0xff and 0x00 erase_value for nvs test (https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/subsys/fs/nvs/testcase.yaml)?

**Comment by de-nordic** [comment]
> 
> 
> I like how code looks like now.
> Is it possible to make `erased_val` configurable for flash simulator via DTS?
> Is it then possible to add test-case with either 0xff and 0x00 erase_value for nvs test (https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/subsys/fs/nvs/testcase.yaml)?

Yes. Now the sim flash will have `erase-value` param that allows selection of flash erase value.

**Review by nvlsianpu — APPROVED** [review]
just resolve the conflicts as https://github.com/zephyrproject-rtos/zephyr/pull/25679 imposed badly on nearly all of PRs. :confused:

File: include/drivers/flash.h [hunk 3]
```diff
@@ -79,6 +79,9 @@ __subsystem struct flash_driver_api {
 	flash_api_pages_layout page_layout;
 #endif /* CONFIG_FLASH_PAGE_LAYOUT */
 	const size_t write_block_size;
+#if defined(CONFIG_FLASH_ERASE_VALUE)
+	const u8_t erase_value;
```
Comment (pabigot) [inline include/drivers/flash.h:83]: In theory it may not be possible to determine this value at compile time.  If we generalize QSPI to the point where it supports all flash serial memories that are JESD216 compatible we won't know whether the flash is NOR or NAND until runtime.

I think this should use a function rather than a constant to accommodate that possibility.

File: drivers/flash/Kconfig [hunk 4]
```diff
@@ -42,6 +42,13 @@ config FLASH_PAGE_LAYOUT
 	help
 	  Enables API for retrieving the layout of flash memory pages.
 
+config FLASH_ERASE_VALUE
```
Comment (pabigot) [inline drivers/flash/Kconfig:45]: Why is this feature conditional?  If drivers can't rely on the API call always being there then they can't guarantee to work on all devices where the erase value might vary.

Also this is misleading in that people will expect this to be the configured erase value, not a flag that enables an API to retrieve the actual erase value.  If it's going to be optional it should be `FLASH_ERASE_VALUE_API`.

File: drivers/flash/soc_flash_rv32m1.c [hunk 5]
```diff
@@ -142,6 +142,9 @@ static const struct flash_driver_api flash_mcux_api = {
 	.page_layout = flash_mcux_pages_layout,
 #endif
 	.write_block_size = FSL_FEATURE_FLASH_PFLASH_BLOCK_WRITE_UNIT_SIZE,
+#if IS_ENABLED(CONFIG_FLASH_ERASE_VALUE)
```
Comment (pabigot) [inline drivers/flash/soc_flash_rv32m1.c:145]: For all these: if people accept that my argument that the value needs to support a runtime determination then all these need to move to the device-specific flash or ram structure.

**Review by pabigot — CHANGES_REQUESTED** [review]
Two major design points to discuss:
* Should the API be available always, or only when specifically enabled;
* Should the implementation support flash devices where we don't know at compile time what the erase value is for a specific device, e.g. determining it from SFDP parameters.

File: include/drivers/flash.h (hunk 3 above)
Comment (pabigot) [reply include/drivers/flash.h:83]: As a follow-up: can somebody identify a device where the erase value is not 0xFF?  I'm not sure NOR vs NAND produces a difference.

**Comment by nvlsianpu** [comment]
@pabigot 
> Should the implementation support flash devices where we don't know at compile time what the erase value is for a specific device, e.g. determining it from SFDP parameters.

Driver implementation might recognize erase-value in the runtime.

**Comment by pabigot** [comment]
> Driver implementation might recognize erase-value in the runtime.

Yeah, but then the value can't be stored in the API structure, which is `const` and the same for all devices used by the API.  In that case we need it to be accessed through a function, not by reading the common structure.

**Comment by nvlsianpu** [comment]
@pabigot ^^understood, right

File: drivers/flash/Kconfig (hunk 4 above)
Comment (nvlsianpu) [reply drivers/flash/Kconfig:45]: Generally disabling stuff helps to make footprint smaller - maybe in this case no worth as this will be just a few bytes per a driver instance.

So this can be always available IMO.
Otherwise I think it should be rather default 'y'

**Comment by Laczen** [comment]
Maybe the idea of extending the api with a `get_flash_erased_value()` is not the best approach. Maybe it is better/easier to extend the api with a function `flash_iserased(dev, addr, size)` that would do the compare inside the flash driver.

**Comment by pabigot** [comment]
> Maybe it is better/easier to extend the api with a function `flash_iserased(dev, addr, size)` that would do the compare inside the flash driver.

It's true that the motivation for this API change has not been documented as clealy as it could be.

There is a use for initializing a buffer with the intent that any elements not specifically assigned otherwise will not mutate the content of the flash, essentially preserving the unerased parts.  That's currently handled in one situation by first reading the region, modifying parts, and writing the whole thing back.

Is that an approach that would solve #22063 without changing the flash API?

Even in that case knowing the erase value would be necessary to verify that the technique won't break (e.g. flash already has 0xAA instead of 0xFF and user wants to write 0xF3 to set bits 0..3, but the result would be 0xA2 which has the wrong value in bits 0..3).

**Comment by Laczen** [comment]
@pabigot, I think this case is different, nvs is searching for the end of the fs by searching for a unwritten value. The read and rewrite to update the flash data will not help.
@pabigot, regarding the read and rewrite for mcuboot support, it might be a bad idea to support this in general, the result might be that flash wear is a lot faster than expected or the method is not supported at all by the hardware. Mcuboot afaik always states that they do not need byte access write, if mcuboot does need read and write back it would be best to add this in mcuboot.

File: include/drivers/flash.h (hunk 3 above)
Comment (de-nordic) [reply include/drivers/flash.h:83]: > 
> As a follow-up: can somebody identify a device where the erase value is not 0xFF? I'm not sure NOR vs NAND produces a difference.
> 

No I have failed to identify any FLASH/EEPROM devices that have erase values different from the 0xFF.

**Comment by de-nordic** [comment]
@Laczen @nvlsianpu @pabigot I have search for information on flash and eeproms to find if there is device that does erase to non-1 value but I have failed to identify any. 
There are FRAM (FeRAM) devices and MRAM, but they behave like RAM generally which means that they do not require erase prior to write.

Maybe this PR should be dropped. I can not find an example of non-1 erase value.
OK, so NVS would not work with some other erase values: yes but we do not have example of such.
In case of FRAM and MRAM, the NVS will not work on them either because they do not have "erase value", support for them  could be emulated via flash API if we add erase functions for them that would default the RAM to all 1 (which will cost us some time).

**Comment by nvlsianpu** [comment]
> Mcuboot afaik always states that they do not need byte access write, if mcuboot does need read and write back it would be best to add this in mcuboot.

Mcuboot doesn't and won't use any read-modify-write to flash. It just need to know what the erased value is for working properly on SoC of 0x00 and 0xFF erased values

**Comment by nvlsianpu** [comment]
@de-nordic +1 for introducing this API.
cc @utzig

**Comment by de-nordic** [comment]
> 
> 
> @de-nordic +1 for introducing this API.
> cc @utzig

@nvlsianpu  I still voice my concern regarding other technologies of NV type memories, but I am modifying the PR to implement @pabigot suggestions regarding the callback instead of data member.  Additionally I will change it from erase specific callback to `flash_get_capabilities`, `flash_get_params` or similar, that could be used in more general way to obtain flash parameters that could be defined during compilation or run-time.

I am also looking into NVS driver to figure out how would it be possible to make it work with non-volatile memories that does not require erase prior to write.

File: include/drivers/flash.h (hunk 3 above)
Comment (utzig) [reply include/drivers/flash.h]: > As a follow-up: can somebody identify a device where the erase value is not 0xFF? I'm not sure NOR vs NAND produces a difference.
> 
> ans: per #22063 "some stm32 embedded"

all STM32L0x and STM32L1x, and AFAIK Cypress PSOC 062/064.

**Comment by carlescufi** [comment]
@pabigot can you re-review please?

**Comment by nvlsianpu** [comment]
Maybe for memories which have not defined erase-value (or erase is not an operation for them) API can return -ENOSUP etc.

**Comment by de-nordic** [comment]
> 
> 
> @pabigot can you re-review please?

There are no changes yet. I am still working o it. @pabigot I will let you know when I will have something to present, although I would like to hear your point of view on current support of NV type memories in Zephyr and whether flash/eeprom api shouldn't be merged under one NV API that would also cover capabilities of other type of NV memories.
Actually I would also encourage @nvlsianpu  and @Laczen, to voice their opinions on the subject as they are more experienced, than me, with the Zephyr API and NV memory usage within the system.
Thanks in advance!

File: include/drivers/flash.h (hunk 3 above)
Comment (de-nordic) [reply include/drivers/flash.h]: Thanks @utzig for the information, I have been able to go through some of the documents related to the MCUs (ST) you have mentioned. I have just skimmed the documentation, but what seems to be here the case is that the ST MCUs,  does not require erase and have its' flash  accessible via MCU address space the same way as "SRAM" (with proper register setup). So for them the erase_value would not have solved the problem. Some ST expert voice would be useful here.

Comment (nvlsianpu) [reply include/drivers/flash.h]: These STM32Lx NVMC performs flash erase operation as well. Most of SoC have access to embedded  flash via memory addresses (nRF as well).  So situuation is allmost the same as for nRF52, Erase value is just different,

**Comment by henrikbrixandersen** [comment]
> I think it's something to consider but @henrikbrixandersen initiated that API and should weigh in on whether its operations can be supported with the flash API. I assume in that situation we'd need to define the expected behavior of erase: should it do nothing, or should it write a constant to remove any information present (I would propose the latter).

We had the discussion of whether to use the flash API for EEPROM devices (and whether to add an erase API function) back when the EEPROM API was introduced. Please see #19972 for details.

File: tests/drivers/flash_simulator/prj.conf [hunk 6]
```diff
@@ -1,5 +1,6 @@
 CONFIG_ZTEST=y
 CONFIG_FLASH=y
+CONFIG_FLASH_ERASE_VALUE=y
```
Comment (nvlsianpu) [inline tests/drivers/flash_simulator/prj.conf]:
```suggestion
CONFIG_FLASH_GET_PARAMETERS_API=y
```

**Review by nvlsianpu — CHANGES_REQUESTED** [review]

File: tests/drivers/flash_simulator/prj.conf (hunk 6 above)
Comment (nvlsianpu) [reply tests/drivers/flash_simulator/prj.conf]: fix in proper commit

File: drivers/flash/Kconfig [hunk 7]
```diff
@@ -42,6 +42,13 @@ config FLASH_PAGE_LAYOUT
 	help
 	  Enables API for retrieving the layout of flash memory pages.
 
+config FLASH_GET_PARAMETERS_API
+	bool "Flash parameters are avaialble via flash_get_parameters"
```
Comment (hakonfam) [inline drivers/flash/Kconfig:46]:
```suggestion
	bool "Flash parameters are available via flash_get_parameters"
```

File: include/drivers/flash.h [hunk 8]
```diff
@@ -36,12 +36,20 @@ struct flash_pages_layout {
 };
 #endif /* CONFIG_FLASH_PAGE_LAYOUT */
 
+/**
+ * Flash memory parameters
+ */
+struct flash_parameters {
+	uint8_t erase_value; /* Pattern representing of erased flash */
```
Comment (hakonfam) [inline include/drivers/flash.h:43]: I guess it should be either
`Pattern representation of erased flash`
or
`Pattern representing erased flash` 
?

**Review by hakonfam — COMMENTED** [review]
some nits

File: include/drivers/flash.h (hunk 8 above)
Comment (pabigot) [reply include/drivers/flash.h]: Or "byte value read back from erased area"

File: include/drivers/flash.h [hunk 9]
```diff
@@ -36,12 +36,20 @@ struct flash_pages_layout {
 };
 #endif /* CONFIG_FLASH_PAGE_LAYOUT */
 
+/**
+ * Flash memory parameters
+ */
+struct flash_parameters {
+	uint8_t erase_value; /* Pattern representing erased flash */
```
Comment (pabigot) [inline include/drivers/flash.h:43]: Or "Byte value of erased flash".  Not terribly important, but "pattern" to me suggests a mask rather than a value.

File: include/drivers/flash.h [hunk 10]
```diff
@@ -296,6 +307,25 @@ static inline size_t z_impl_flash_get_write_block_size(struct device *dev)
 	return api->write_block_size;
 }
 
+
+/**
+ *  @brief  Get pointer to flash_parameters structure
+ *
+ *  @return pointer to flash_parameters structure characteristic for
```
Comment (pabigot) [inline include/drivers/flash.h:314]: ... or NULL if parameters are not available.

File: include/drivers/flash.h [hunk 11]
```diff
@@ -296,6 +307,25 @@ static inline size_t z_impl_flash_get_write_block_size(struct device *dev)
...
+ */
+#if defined(CONFIG_FLASH_GET_PARAMETERS_API)
+__syscall const struct flash_parameters *flash_get_parameters(const struct device *dev);
+
+static inline const struct flash_parameters *z_impl_flash_get_parameters(const struct device *dev)
+{
+	const struct flash_driver_api *api =
+		(const struct flash_driver_api *)dev->driver_api;
+
+	return api->get_parameters();
```
Comment (pabigot) [inline include/drivers/flash.h:325]: Because this API is optional, it'd be easy for out-of-tree drivers to not provide it, and never notice that somebody enabled the option.  There should at minimum be an `__ASSERT()` that the API field has been filled out, but I'd still rather see:

    return (api->get_parameters == NULL) ? NULL : api->get_parameters();

to at least let the application be able to recover in that situation.

Which then gets back to the question of whether `flash_get_parameters()` should always be available, and just return `NULL` if the option isn't enabled.  I don't recall what the resolution of that discussion was, if we reached one.

File: tests/drivers/flash_simulator/prj.conf (hunk 6 above)
Comment (pabigot) [reply tests/drivers/flash_simulator/prj.conf]: Agree, this doesn't belong in this commit.

File: tests/drivers/flash_simulator/src/main.c [hunk 12]
```diff
@@ -266,6 +269,15 @@ static void test_double_write(void)
 	zassert_equal(-EIO, rc, "Unexpected error code (%d)", rc);
 }
 
+static void test_get_erase_value(void)
+{
+	const struct flash_parameters *fp = flash_get_parameters(flash_dev);
+
+	zassert_equal(fp->erase_value, FLASH_SIMULATOR_ERASE_VALUE,
+		      "Eipected erase value %hhx",
```
Comment (pabigot) [inline tests/drivers/flash_simulator/src/main.c:277]: s/Eipected/Expected/.

Also `%x` not `%hhx`.  The value gets promoted to unsigned int in the call, no need for unusual length modifiers.

**Review by pabigot — CHANGES_REQUESTED** [review]
I think I'd like the API to return `NULL` when the parameters are not available, and allow drivers to not populate the implementation pointer in that case.

Alternatively if all drivers must implement this API, then there needs to be an `__ASSERT()` in the impl wrapper so that drivers that don't set the field don't call through a null pointer.

File: include/drivers/flash.h (hunk 11 above)
Comment (de-nordic) [reply include/drivers/flash.h:325]: I will make it permanent addition to API. I think it is not worth making this optional as checking whether this returns  NULL, after calls, is too much of a hassle.

Comment (de-nordic) [reply include/drivers/flash.h:325]: Even if turning this off saves us ~8 bytes of flash, the checking for NULL every time when the structure is requested would probably cost us as much more. And NULL processing at runtime is problematic because this is a thing that  is supposed to describe some property, what if it is not there? Stop running?

File: include/drivers/flash.h (hunk 10 above)
Comment (de-nordic) [reply include/drivers/flash.h:312]: No NULL, withdrawing from making this optional.

File: include/drivers/flash.h [hunk 13]
```diff
@@ -79,6 +87,7 @@ __subsystem struct flash_driver_api {
 	flash_api_pages_layout page_layout;
 #endif /* CONFIG_FLASH_PAGE_LAYOUT */
 	const size_t write_block_size;
+	flash_api_get_parameters get_parameters;
```
Comment (pabigot) [inline include/drivers/flash.h:90]: OK, so since we're adding API unconditionally, this raises new questions.

`write_block_size` is clearly a parameter of the flash.  Shouldn't it move to this structure?

Then we can deprecate `flash_get_write_block_size()` and implement it temporarily using `flash_get_parameters()`.

I realize this starts down a slippery slope, but it looks like maybe we should start sliding.

File: include/drivers/flash.h [hunk 14]
```diff
@@ -36,12 +36,20 @@ struct flash_pages_layout {
...
+	uint8_t erase_value; /* Byte value of erased flash */
+};
+
 typedef int (*flash_api_read)(struct device *dev, off_t offset, void *data,
 			      size_t len);
 typedef int (*flash_api_write)(struct device *dev, off_t offset,
 			       const void *data, size_t len);
 typedef int (*flash_api_erase)(struct device *dev, off_t offset, size_t size);
 typedef int (*flash_api_write_protection)(struct device *dev, bool enable);
+typedef const struct flash_parameters* (*flash_api_get_parameters)(void);
```
Comment (pabigot) [inline include/drivers/flash.h:52]: Thinking again: this needs to take a `struct device *dev` parameter.  There's an outside chance of a generic flash driver for which different devices have different properties.

If we were not to do that (and I really do think we should) we could instead just store the pointer to the structure in the API structure, as is currently done for `write_block_size`.

**Review by pabigot — CHANGES_REQUESTED** [review]
Looks like this is one of those things that looks easy but creates more questions every time we iterate.

In this case I notice we have an existing flash property that should go into the new structure, unless there's a good reason why it shouldn't.  Also we should support having different parameters for different flash devices.

File: include/drivers/flash.h (hunk 13 above)
Comment (de-nordic) [reply include/drivers/flash.h:90]: I have been thinking about moving the `write_block_size` to flash_parameters, though I am not sure whether this, as it would also men depreciation of existing API, in this PR.
@pabigot Should we do that now? Why is it slippery slope?

File: include/drivers/flash.h (hunk 14 above)
Comment (de-nordic) [reply include/drivers/flash.h:52]: OK, I will change this.

File: include/drivers/flash.h (hunk 13 above)
Comment (pabigot) [reply include/drivers/flash.h:90]: Well, we don't *have* to deprecate the API, we can just implement in terms of the new API and leave it.  But it could be deprecated since it'd be redundant with the value in the parameter structure.

"Slippery" because we should also look at what's in the page layout description and see what else should be exposed.  Like whether there's a fixed minimum erase size.

I think that should be left for a separate PR, but that moving `write_block_size` is appropriate as it justifies the move to an aggregate parameter structure (we had just one value, now we have two, so we should generalize).

Comment (de-nordic) [reply include/drivers/flash.h:90]: OK, I will mote the `write_block_size` into the `flash_parameters` structure within this PR.

File: drivers/flash/flash_gecko.c [hunk 15]
```diff
@@ -178,6 +184,14 @@ void flash_gecko_page_layout(struct device *dev,
 }
 #endif /* CONFIG_FLASH_PAGE_LAYOUT */
 
+static const struct flash_parameters *
+flash_gecko_get_parameters(const struct device *dev)
+{
+	ARG_UNUSED(dev);
+
+	return (const struct flash_parameters *)&flash_gecko_parameters;
```
Comment (pabigot) [inline drivers/flash/flash_gecko.c:192]: The cast of the address is unnecessary and confusing.  Please remove from all drivers.

File: drivers/flash/flash_sam0.c [hunk 16]
```diff
@@ -417,11 +434,7 @@ static const struct flash_driver_api flash_sam0_api = {
 #ifdef CONFIG_FLASH_PAGE_LAYOUT
 	.page_layout = flash_sam0_page_layout,
 #endif
-#if CONFIG_SOC_FLASH_SAM0_EMULATE_BYTE_PAGES
-	.write_block_size = 1,
-#else
-	.write_block_size = FLASH_PAGE_SIZE,
-#endif
+	.get_parameters = flash_sam0_get_parameters,
```
Comment (pabigot) [inline drivers/flash/flash_sam0.c:437]: I have a slight preference for having the unconditional fields appear before any conditional fields, so would put this before `.page_layout`.  Just a suggestion.

File: drivers/flash/flash_stm32.c [hunk 17]
```diff
@@ -57,6 +57,18 @@ LOG_MODULE_REGISTER(flash_stm32, CONFIG_FLASH_LOG_LEVEL);
 
 #define CFG_HW_FLASH_SEMID	2
 
+static const struct flash_parameters flash_stm32_parameters = {
+#endif
```
Comment (pabigot) [inline drivers/flash/flash_stm32.c:61]: This looks out of place.

File: drivers/flash/spi_nor.c [hunk 18]
```diff
@@ -84,6 +84,12 @@ struct spi_nor_data {
 	struct k_sem sem;
 };
 
+
```
Comment (pabigot) [inline drivers/flash/spi_nor.c:87]: unexpected blank line

File: drivers/flash/nrf_qspi_nor.c [hunk 19]
```diff
@@ -33,6 +33,10 @@
 
 LOG_MODULE_REGISTER(qspi_nor, CONFIG_FLASH_LOG_LEVEL);
 
+static const struct flash_parameters qspi_flash_parameters = {
+	.erase_value = 0xff,
```
Comment (pabigot) [inline drivers/flash/nrf_qspi_nor.c:38]: missing `.write_block_size`.  Multiple drivers.

**Review by pabigot — COMMENTED** [review]
More preliminary feedback; many drivers need to be fixed to move the `write_block_size` from the API structure to the parameters.

File: drivers/flash/nrf_qspi_nor.c (hunk 19 above)
Comment (de-nordic) [reply drivers/flash/nrf_qspi_nor.c:38]: Eh. Failed to properly apply patches between branches...

File: drivers/flash/flash_stm32.c (hunk 17 above)
Comment (de-nordic) [reply drivers/flash/flash_stm32.c:61]: Fixed.

File: drivers/flash/flash_sam0.c (hunk 16 above)
Comment (de-nordic) [reply drivers/flash/flash_sam0.c:437]: My personal preference is to initialize fields, if possible, in the order of appearance. This makes easier for me to figure out if I have missed something, etc. Looks messier when a lot of c preprocessor is involved but still easier to figure out. Do you want me to change it?

File: drivers/flash/flash_gecko.c (hunk 15 above)
Comment (de-nordic) [reply drivers/flash/flash_gecko.c]: Yes. I do not even remember anymore, why I am doing this casting...

File: drivers/flash/spi_nor.c (hunk 18 above)
Comment (de-nordic) [reply drivers/flash/spi_nor.c]: Fixed

File: drivers/flash/flash_sam0.c (hunk 16 above)
Comment (pabigot) [reply drivers/flash/flash_sam0.c:437]: Initializing in the order of definition isn't just a preference; it's a requirement for C++.  What I meant was to move the `get_parameters` definition up next to the other ones, and keep the optional ones at the end.  Since it's new, it doesn't matter whether it goes at the end or is inserted: the relative order of everything else remains unchanged.

Comment (pabigot) [reply drivers/flash/flash_sam0.c:437]: > Do you want me to change it?

Yes, but I'm not going to block if you don't.

Comment (de-nordic) [reply drivers/flash/flash_sam0.c]: OK I will do this.

Comment (de-nordic) [reply drivers/flash/flash_sam0.c]: For C99 the order of definition of structure fields, when using "designators", does not matter.

**Comment by Laczen** [comment]
@de-nordic, it seems that the flash api extension is getting defined.

IMO the best way to use this extension in nvs is to extend the nvs fs structure with a pointer to the flash parameters and to set this during nvs_init. If any of the required flash parameters is missing raise a cfg error and keep the nvs flash_device = null. In the nvs routines use the nvs pointer to flash parameters  (so the get_flash_param() is only used in nvs_init and not inside any other nvs routines).

**Comment by de-nordic** [comment]
> 
> IMO the best way to use this extension in nvs is to extend the nvs fs structure with a pointer to the flash parameters and to set this during nvs_init. If any of the required flash parameters is missing raise a cfg error and keep the nvs flash_device = null. In the nvs routines use the nvs pointer to flash parameters (so the get_flash_param() is only used in nvs_init and not inside any other nvs routines).

I will look into this.

File: drivers/flash/Kconfig (hunk 7 above)
Comment (nvlsianpu) [reply drivers/flash/Kconfig]: not configurable anymore

Comment (de-nordic) [reply drivers/flash/Kconfig]: Yes it has been thrown out.

**Comment by de-nordic** [comment]
@Laczen does the changes to NVS follow your idea?

**Comment by Laczen** [comment]
> @Laczen does the changes to NVS follow your idea?

Yes, this is completely what I was thinking. I don't know if it is possible to use a `const struct *flash_parameters`, it might be easier to use when it's not `const` and gets assigned during init (and a check is made on the write_block_size).

**Comment by de-nordic** [comment]
> 
> Yes, this is completely what I was thinking. I don't know if it is possible to use a `const struct *flash_parameters`.

@Laczen  How do you want to use it? I do not encourage anyone to modify contents of `flash_parameters` outside of drivers.

**Comment by pabigot** [comment]
> Yes, this is completely what I was thinking. I don't know if it is possible to use a `const struct *flash_parameters`.

That should be easy to do: you return a pointer to const, but keep the structure in RAM and initialize it when the device is initialized.

I agree the API should not provide a pointer to non-const.  I'd like to document that the caller has the choice of caching the pointer, or copying the information desired to a different data structure with a guarantee it will never change.

**Comment by Laczen** [comment]
> > Yes, this is completely what I was thinking. I don't know if it is possible to use a `const struct *flash_parameters`.
> 
> @Laczen How do you want to use it? I do not encourage anyone to modify contents of `flash_parameters` outside of drivers.

Exactly how you are using it. Probably my remark is a result of limited c knowledge, can you assign the `const struct *flash_parameters` in nvs_init() ?

**Comment by de-nordic** [comment]
> 
> 
> > > Yes, this is completely what I was thinking. I don't know if it is possible to use a `const struct *flash_parameters`.
> > 
> > 
> > @Laczen How do you want to use it? I do not encourage anyone to modify contents of `flash_parameters` outside of drivers.
> 
> Exactly how you are using it. Probably my remark is a result of limited c knowledge, can you assign the `const struct *flash_parameters` in nvs_init() ?

Yes, `const` qualifier 'protects' here the structure as it is in the part that declares pointed type. If you want to protect pointer, you need to move `const`:
`struct *const flash_parameters`
or you can have both:
`const struct *const flash_parameters`

**Comment by de-nordic** [comment]
@pabigot 

> 
> 
>(...) I'd like to document that the caller has the choice of caching the pointer, or copying the information desired to a different data structure with a guarantee it will never change.

You want this in the doxygen of the `flash_get_parameters()` ?

**Comment by pabigot** [comment]
> > (...) I'd like to document that the caller has the choice of caching the pointer, or copying the information desired to a different data structure with a guarantee it will never change.
> 
> You want this in the doxygen of the `flash_get_parameters()` ?

I think so, yes, assuming you and others think this is worth making clear.  I'd like to have this API raised during the API telecon today for visibility.  But also we should confirm that nobody has a use case for the values changing for a given device while the system is running.

**Comment by de-nordic** [comment]
> 
> I think so, yes, assuming you and others think this is worth making clear. I'd like to have this API raised during the API telecon today for visibility. But also we should confirm that nobody has a use case for the values changing for a given device while the system is running.

I do not think there is a case for the contents of `flash_parameters` to get modified at runtime. I will add the note to documentation, but we will need to wait until it gets clarified.

**Comment by Laczen** [comment]
> > > > Yes, this is completely what I was thinking. I don't know if it is possible to use a `const struct *flash_parameters`.
> > > 
> > > 
> > > @Laczen How do you want to use it? I do not encourage anyone to modify contents of `flash_parameters` outside of drivers.
> > 
> > 
> > Exactly how you are using it. Probably my remark is a result of limited c knowledge, can you assign the `const struct *flash_parameters` in nvs_init() ?
> 
> Yes, `const` qualifier 'protects' here the structure as it is in the part that declares pointed type. If you want to protect pointer, you need to move `const`:
> `struct *const flash_parameters`
> or you can have both:
> `const struct *const flash_parameters`

OK, thanks for the clarification

**Comment by nvlsianpu** [comment]
NVS changes looks ok

File: drivers/flash/flash_stm32.c [hunk 20]
```diff
@@ -57,6 +57,10 @@ LOG_MODULE_REGISTER(flash_stm32, CONFIG_FLASH_LOG_LEVEL);
 
 #define CFG_HW_FLASH_SEMID	2
 
+static const struct flash_parameters flash_stm32_parameters = {
+	.erase_value = 0xff,
```
Comment (erwango) [inline drivers/flash/flash_stm32.c:68]: This doesn't apply to all series.
On a handfull, this should be 0x00.
I'll get back to you with the references

Comment (de-nordic) [reply drivers/flash/flash_stm32.c:68]: OK, thanks for looking into this.

Comment (de-nordic) [reply drivers/flash/flash_stm32.c:68]: @utzig has mentioned same thing here: https://github.com/zephyrproject-rtos/zephyr/pull/25947#discussion_r438000040 though I do not know how does it apply to our stm32 drivers.

Comment (de-nordic) [reply drivers/flash/flash_stm32.c:68]: @erwango Can you advise me on the stm32 characteristic values for `erase_value`?

Comment (erwango) [reply drivers/flash/flash_stm32.c:68]: @de-nordic After check, only L0/L1 use 0x00 as erase value (I guess reason is they have an EEPROM and this is easier to use same erase value for both).
Since L0/L1 have no flash driver yet, proposed code is fine. Maybe adding a warning comment in case of L0/L1 future addition would be a nice thing though.

Comment (de-nordic) [reply drivers/flash/flash_stm32.c:68]: @erwango Thanks for the information. Will add warning information.

**Comment by carlescufi** [comment]
@pabigot @nvlsianpu could you take another look please?

File: drivers/flash/flash_simulator.c [hunk 21]
```diff
@@ -343,15 +350,23 @@ static void flash_sim_page_layout(struct device *dev,
...
 static const struct flash_driver_api flash_sim_api = {
 	.read = flash_sim_read,
 	.write = flash_sim_write,
 	.erase = flash_sim_erase,
 	.write_protection = flash_wp_set,
-	.write_block_size = FLASH_SIMULATOR_PROG_UNIT,
 #ifdef CONFIG_FLASH_PAGE_LAYOUT
 	.page_layout = flash_sim_page_layout,
 #endif
+	.get_parameters = flash_sim_get_parameters,
```
Comment (pabigot) [inline drivers/flash/flash_simulator.c:369]: Placement of this one isn't the same as the others.

File: include/drivers/flash.h [hunk 22]
```diff
@@ -293,7 +304,30 @@ static inline size_t z_impl_flash_get_write_block_size(struct device *dev)
...
+
+
+/**
+ *  @brief  Get pointer to flash_parameters structure
+ *
+ *  Returned pointer points to a structure that should be considered
+ *  constant through a runtime, regardless if it is defined in RAM or
+ *  Flash.
+ *  Developer is free to cache the structure pointer or copy its contents,
+ *  although a pointer if preferred method of access.
```
Comment (pabigot) [inline include/drivers/flash.h:318]: I'd make this end at "copy its contents."  The rest is opinion that isn't good advice for some uses.  If you want it anyway just change "if preferred" to "is the preferred".

**Review by pabigot — APPROVED** [review]
OK as is, a couple minor cleanups identified.

File: drivers/flash/flash_simulator.c (hunk 21 above)
Comment (de-nordic) [reply drivers/flash/flash_simulator.c:369]: Done

File: include/drivers/flash.h (hunk 22 above)
Comment (de-nordic) [reply include/drivers/flash.h]: Done

**Review by Laczen — APPROVED** [review]

**Comment by de-nordic** [comment]
@Laczen @pabigot Thanks for reviewing.

File: drivers/flash/flash_stm32.c (hunk 20 above)
Comment (andysan) [reply drivers/flash/flash_stm32.c:69]: There is a PR for an L0 driver (https://github.com/zephyrproject-rtos/zephyr/pull/25245) that will hit this issue. The easiest way to distinguish between the EEPROM and FLASH implementations is probably to check for the FLASH_CR_LOCK (erase value 0xff) or FLASH_PECR_PELOCK (erase value 0x00). It's not exactly pretty, but it avoids hard-coding the SOC family.

Comment (Laczen) [reply drivers/flash/flash_stm32.c:69]: > There is a PR for an L0 driver (#25245) that will hit this issue. The easiest way to distinguish between the EEPROM and FLASH implementations is probably to check for the FLASH_CR_LOCK (erase value 0xff) or FLASH_PECR_PELOCK (erase value 0x00). It's not exactly pretty, but it avoids hard-coding the SOC family.

@andysan, does this mean that also for L0 the flash erase value is 0xff?

**Review by nvlsianpu — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
