### PR TITLE
net: lwm2m: Fix unused return value from sys_mutex calls

### LINKED ISSUE #26988: [Coverity CID :211473] Unchecked return value in subsys/net/lib/lwm2m/lwm2m_engine.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/476fc405e7/subsys/net/lib/lwm2m/lwm2m_engine.c#L3781

Category: Error handling issues
Function: `retransmit_request`
Component: Networking
CID: [211473](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=211473)

Details:

```
3775             goto next;
3776         }
3777    
3778         LOG_INF("Resending message: %p", msg);
3779         msg->send_attempts++;
3780    
>>>     CID 211473:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "sys_mutex_lock" without checking return value (as is done elsewhere 17 out of 21 times).
3781         sys_mutex_lock(&client_ctx->send_lock, K_FOREVER);
3782    
3783         if (msg->ctx == NULL) {
3784             LOG_INF("Response for %p already handled", msg);
3785             goto next_locked;
3786         }
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #26989: [Coverity CID :211477] Unchecked return value in subsys/net/lib/lwm2m/lwm2m_engine.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/476fc405e7/subsys/net/lib/lwm2m/lwm2m_engine.c#L1011

Category: Error handling issues
Function: `lwm2m_send_message`
Component: Networking
CID: [211477](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=211477)

Details:

```
1005         if (msg->type == COAP_TYPE_CON) {
1006             coap_pending_cycle(msg->pending);
1007         }
1008    
1009         msg->send_attempts++;
1010    
>>>     CID 211477:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "sys_mutex_lock" without checking return value (as is done elsewhere 17 out of 21 times).
1011         sys_mutex_lock(&msg->ctx->send_lock, K_FOREVER);
1012         rc = send(msg->ctx->sock_fd, msg->cpkt.data, msg->cpkt.offset, 0);
1013         sys_mutex_unlock(&msg->ctx->send_lock);
1014         if (rc < 0) {
1015             if (msg->type == COAP_TYPE_CON) {
1016                 coap_pending_clear(msg->pending);
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by rlubos**
Fixes coverity issues 211473 and 211477.

Fixes #26988
Fixes #26989

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 1]
```diff
@@ -1008,9 +1008,12 @@ int lwm2m_send_message(struct lwm2m_message *msg)
...
 	msg->send_attempts++;
 
-	sys_mutex_lock(&msg->ctx->send_lock, K_FOREVER);
+	ret = sys_mutex_lock(&msg->ctx->send_lock, K_FOREVER);
+	__ASSERT(ret == 0, "sys_mutex_lock failed with %d", ret);
 	rc = send(msg->ctx->sock_fd, msg->cpkt.data, msg->cpkt.offset, 0);
-	sys_mutex_unlock(&msg->ctx->send_lock);
+	ret = sys_mutex_unlock(&msg->ctx->send_lock);
+	__ASSERT(ret == 0, "sys_mutex_unlock failed with %d", ret);
+	(void)ret;
```
Comment (jukkar) [inline subsys/net/lib/lwm2m/lwm2m_engine.c:1016]: Perhaps `ARG_UNUSED(ret);` here

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 2]
```diff
@@ -3797,7 +3802,9 @@ static void retransmit_request(struct k_work *work)
 	}
 
 next_locked:
-	sys_mutex_unlock(&client_ctx->send_lock);
+	ret = sys_mutex_unlock(&client_ctx->send_lock);
+	__ASSERT(ret == 0, "sys_mutex_unlock failed with %d", ret);
+	(void)ret;
```
Comment (jukkar) [inline subsys/net/lib/lwm2m/lwm2m_engine.c:3807]: same here

**Comment by rlubos** [comment]
@jukkar Thanks, fixed.

**Review by ioannisg — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
