### PR TITLE
arch/x86: Fix stack alignment for user threads

### LINKED ISSUE #31018: up_squared: tests/kernel/pipe/pipe_api failed.
**To Reproduce**
1. west build -b up_squared -p auto tests/kernel/pipe/pipe_api
2. west flash ~/up_squared.sh
3. see error

**Logs and console output**
Booting Zephyr OS build zephyr-v2.4.0-2674-g4ca7942411f7
Running test suite pipe_api

**START - test_pipe_thread2thread**
E: General protection fault (code 0x0)
E: RAX: 0x0000000000cac000 RBX: 0x0000000000000000 RCX: 0x0000000000000000 RDX: 0x0000000000000000
E: RSI: 0xffffffffffffffff RDI: 0x0000000000118420 RBP: 0x0000000000d42fa8 RSP: 0x0000000000d42f18
E:  R8: 0x0000000000100be1  R9: 0x8000000000000006 R10: 0x0000000000000000 R11: 0x0000000000000246
E: R12: 0x0000000000118420 R13: 0xffffffffffffffff R14: 0x0000000000000000 R15: 0x0000000000000000
E: RSP: 0x0000000000d42f18 RFLAGS: 0x0000000000010286 CS: 0x003b CR3: 0x0000000000cac000
E: RIP: 0x0000000000100784
**E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x118060 (unknown)
E: Halting system**

**Environment (please complete the following information):**
 - OS: Fedora32
 - Toolchain: zephyr-sdk-0.12.0
 - Commit ID: 4ca7942411f7

### PR DESCRIPTION
**Pull request by andyross**
The x86_64 SysV ABI requires 16 byte alignment for the stack pointer
during execution of normal code.  That means that on entry to an
ABI-compatible C function (which is reached via a CALL instruction
that pushes the return address) the RSP register must be MISaligned by
exactly 8 bytes.  The kernel mode thread setup got this right, but we
missed the equivalent condition in userspace entry.

The end result was a misaligned stack, which is surprisingly robust
for most use.  But recent toolchains have starting doing some more
elaborate vectorization, and the resulting SSE instructions started
failing in userspace on the misaliged loads.

Note that there's a comment about optimization: we're doing the stack
alignment in the "wrong place" and are needlessly wasting bytes in
some cases.  We should see the raw stack boundaries where we are
setting up RSP values.  Add a FIXME to this effect, but don't touch
anything as this patch is a targeted bugfix.

Also fix a somewhat embarassing 32-bit-ism that would have truncated
the address of a userspace stack that we tried to put above 4G.

Fixes #31018

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Review by ceolin — APPROVED** [review]
Is there any way to make ` Z_STACK_PTR_ALIGN` aware of this ? Is just weird need to fix the alignment after call this macro that is supposed to do this.

File: arch/x86/core/userspace.c [hunk 1]
```diff
@@ -96,6 +96,13 @@ FUNC_NORETURN void arch_user_mode_enter(k_thread_entry_t user_entry,
 				      _current->stack_info.size -
 				      _current->stack_info.delta);
 
+	/* x86_64 SysV ABI requires 16 byte stack alignment, which
```
Comment (dcpleung) [inline arch/x86/core/userspace.c:99]: Wondering if this should be enabled only for `CONFIG_X86_64 || CONFIG_SSE` since 32-bit does not seem to require this.

Comment (andyross) [reply arch/x86/core/userspace.c:99]: That's an excellent point, will fix.  But not SSE I don't think: in 32 bit mode there's no stack alignment requirement so if the compiler did want to autovectorize it would be responsible for aligning the stack on its own and wouldn't need this anyway.

**Review by nashif — APPROVED** [review]
