### PR TITLE
usb: cdc: Do not duplicate USB transfer slots for OUT transfers

### LINKED ISSUE #26725: USB suspend-resume process is not properly handled
**Describe the bug**
The USB subsystem does not properly handle the suspend-resume process.

When a USB device is suspended, all on-going transfers are cancelled:

https://github.com/zephyrproject-rtos/zephyr/blob/0651688dd350851ab5e00265d1170f3f015e77c0/subsys/usb/usb_device.c#L1017-L1025

The CDC ACM device class implementation, for instance, does not restore the cancelled USB transfer upon the resume event and this results in the USB transfer remaining in cancelled state:

https://github.com/zephyrproject-rtos/zephyr/blob/0651688dd350851ab5e00265d1170f3f015e77c0/subsys/usb/class/cdc_acm.c#L437-L440

This causes the USB device to become unresponsive.

**To Reproduce**
1. Build and flash `samples/subsys/usb/cdc_acm`
2. Open the board USB device serial port and see that everything is echoed.
3. Close the board USB device serial port
3. Suspend the board USB device.
4. Resume the board USB device.
5. Open the board USB device serial port and see that the device does not echo anything back.

**Expected behavior**
USB endpoint transfers are in working state after device is resumed.

**Impact**
USB suspend-resume process does not work, and any attempt by the host to suspend the device will result in the device being unusable until the device is re-enumerated (and configured).

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.11.3
 - Commit SHA: cbb252adef08ba482b14ef2ab562baf879956c93

**Additional context**
Note that this issue is not specific to the CDC ACM device class; a quick glance over other device class implementations suggest that they will be affected by this issue as long as the USB transfers are cancelled when a suspend event is received.

Also note that the `USB_DC_DISCONNECTED` event is not implemented or, as far as I can tell, does not work on any platforms.

### LINKED ISSUE #26970: usb: overflow of USB transfers leads to clogging
**Describe the bug**
After #26747 was merged I observed that some samples (hid-cdc, cdc_acm_composite) don't work anymore.
If USB stack is calling read transfer on every SUSPEND->RESUME it will quickly run out of transfer slots making it unable to finish the enumeration and make the device unusable.

Increasing the number of USB transfer slots does not help much. The issue could be seen when switching from virtual machine to native machine many times. Sooner or later there will be shortage of USB transfers and the device will no longer work.
``` diff 
diff --git a/subsys/usb/usb_transfer.c b/subsys/usb/usb_transfer.c
index 230337783b..9317b3bc8b 100644
--- a/subsys/usb/usb_transfer.c
+++ b/subsys/usb/usb_transfer.c
@@ -13,7 +13,7 @@
 
 LOG_MODULE_REGISTER(usb_transfer, CONFIG_USB_DEVICE_LOG_LEVEL);
 
-#define MAX_NUM_TRANSFERS           4 /** Max number of parallel transfers */
+#define MAX_NUM_TRANSFERS           20 /** Max number of parallel transfers */
 
 struct usb_transfer_sync_priv {
 	int tsize;
```

**Environment (please complete the following information):**
 - OS: Linux Mint
 - zephyr-sdk v0.11.2
 - 98bcc51b09 
 - Board: nrf52840dk_nrf52840. I haven't tested it with other boards but it also may happen.

**Additional context**
**EDIT**:
sample: cdc_acm_composite
board: nrf53840dk_nrf52840

Patch applied:
``` diff
diff --git a/subsys/usb/class/cdc_acm.c b/subsys/usb/class/cdc_acm.c
index 0f5f2ff50c..b0f8e2d0d6 100644
--- a/subsys/usb/class/cdc_acm.c
+++ b/subsys/usb/class/cdc_acm.c
@@ -416,6 +416,8 @@ static void cdc_acm_do_cb(struct cdc_acm_dev_data_t *dev_data,
 		LOG_DBG("Device connected");
 		break;
 	case USB_DC_CONFIGURED:
+		LOG_ERR("Configured, create transfer on ep 0x%02x",
+			cfg->endpoint[ACM_OUT_EP_IDX].ep_addr);
 		cdc_acm_read_cb(cfg->endpoint[ACM_OUT_EP_IDX].ep_addr, 0,
 				dev_data);
 		dev_data->tx_ready = true;
@@ -435,6 +437,8 @@ static void cdc_acm_do_cb(struct cdc_acm_dev_data_t *dev_data,
 		break;
 	case USB_DC_RESUME:
 		if (dev_data->usb_status == USB_DC_SUSPEND) {
+			LOG_ERR("Suspend->Resume, create transfer on ep 0x%02x",
+				cfg->endpoint[ACM_OUT_EP_IDX].ep_addr);
 			cdc_acm_read_cb(cfg->endpoint[ACM_OUT_EP_IDX].ep_addr,
 					0, dev_data);
 			dev_data->usb_status = USB_DC_CONFIGURED;
diff --git a/subsys/usb/usb_transfer.c b/subsys/usb/usb_transfer.c
index 230337783b..fa74db6ddb 100644
--- a/subsys/usb/usb_transfer.c
+++ b/subsys/usb/usb_transfer.c
@@ -127,7 +127,10 @@ static void usb_transfer_work(struct k_work *item)
 		}
 
 		/* we expect mote data, clear NAK */
-		usb_dc_ep_read_continue(ep);
+		ret = usb_dc_ep_read_continue(ep);
+		if (ret) {
+			LOG_ERR("Transfer error %d, ep 0x%02x", ret, ep);
+		}
 	}
 
 done:
@@ -203,6 +206,8 @@ int usb_transfer(uint8_t ep, uint8_t *data, size_t dlen, unsigned int flags,
 
 	key = irq_lock();
 
+	// usb_cancel_transfer(ep);
+
 	for (i = 0; i < ARRAY_SIZE(ut_data); i++) {
 		if (!k_sem_take(&ut_data[i].sem, K_NO_WAIT)) {
 			trans = &ut_data[i];
@@ -211,7 +216,12 @@ int usb_transfer(uint8_t ep, uint8_t *data, size_t dlen, unsigned int flags,
 	}
 
 	if (!trans) {
-		LOG_ERR("No transfer slot available");
+		LOG_ERR("No transfer slot available, print all transfers");
+
+		for (i = 0; i < ARRAY_SIZE(ut_data); i++) {
+			LOG_ERR("Transfer on ep 0x%02x, status:%d",
+				ut_data[i].ep, ut_data[i].status);
+		}
 		ret = -ENOMEM;
 		goto done;
 	}
```
**Output:**
```
*** Booting Zephyr OS build zephyr-v2.3.0-1124-g98bcc51b0925  ***
[00:00:00.005,126] <inf> cdc_acm_composite: Wait for DTR
[00:00:00.009,155] <inf> usb_cdc_acm: Device suspended
[00:00:00.009,185] <inf> usb_cdc_acm: Device suspended
[00:00:00.208,496] <err> usb_cdc_acm: Suspend->Resume, create transfer on ep 0x02
[00:00:00.208,526] <err> usb_nrfx: Endpoint 0x02 is not enabled
[00:00:00.208,526] <inf> usb_cdc_acm: Define resumed
[00:00:00.208,526] <err> usb_cdc_acm: Suspend->Resume, create transfer on ep 0x01
[00:00:00.208,557] <err> usb_nrfx: Endpoint 0x01 is not enabled
[00:00:00.208,557] <inf> usb_cdc_acm: Define resumed
[00:00:00.879,730] <err> usb_cdc_acm: Configured, create transfer on ep 0x02
[00:00:00.879,730] <inf> usb_cdc_acm: Device configured
[00:00:00.879,760] <err> usb_cdc_acm: Configured, create transfer on ep 0x01
[00:00:00.879,760] <inf> usb_cdc_acm: Device configured
[00:00:01.205,718] <inf> cdc_acm_composite: DTR set, start test
[00:00:06.393,188] <err> usb_transfer: No transfer slot available, print all transfers
[00:00:06.393,218] <err> usb_transfer: Transfer on ep 0x02, status:-16
[00:00:06.393,218] <err> usb_transfer: Transfer on ep 0x01, status:-16
[00:00:06.393,218] <err> usb_transfer: Transfer on ep 0x02, status:-16
[00:00:06.393,218] <err> usb_transfer: Transfer on ep 0x01, status:-16
```

### PR DESCRIPTION
**Pull request by eobalski**
This commit fixes an issue when more than one USB transfer is
reserved for same OUT endpoint.

There are 2 scenarios when this could happen:
- The Host sends SET_CONFIGURATION(1) request twice.
- The Host triggers Suspend->Resume->Configured
  event sequence for the device.

USB tranfers are not canceled on SUSPEND event
when the device was not configred previously.

Because of that USB transfer slot is reserved twice
for the same OUT endpoint and lead to shortage of USB
transfer slots quickly.

Without this patch CDC ACM class reserves duplicated USB
transfer slots for one transfer. The sequence of
Suspend->Resume events is genereted alongside with
Configured and the stack will shortly run out of transfer
slots.

If the Host, for some reason, decides to send
SET_CONFIGURATION request twice the same issue is seen.
This patch prevents from reserving additional USB transfer
slots twice.

Fixes #26970

### CODE REVIEW

**Comment by emob-nordic** [comment]
I can drop e77a1b8 if needed.

**Comment by emob-nordic** [comment]
@stephanosio Could You please have a look as well?

File: subsys/usb/class/cdc_acm.c [hunk 1]
```diff
@@ -416,29 +418,38 @@ static void cdc_acm_do_cb(struct cdc_acm_dev_data_t *dev_data,
 		LOG_DBG("Device connected");
 		break;
 	case USB_DC_CONFIGURED:
-		cdc_acm_read_cb(cfg->endpoint[ACM_OUT_EP_IDX].ep_addr, 0,
-				dev_data);
+		LOG_INF("Device configured");
+		if (!dev_data->configured) {
+			LOG_ERR("create transfer on ep 0x%02x",
```
Comment (anangl) [inline subsys/usb/class/cdc_acm.c:423]: I guess it was supposed to be `LOG_INF`.

File: subsys/usb/class/cdc_acm.c [hunk 2]
```diff
@@ -416,29 +418,38 @@ static void cdc_acm_do_cb(struct cdc_acm_dev_data_t *dev_data,
...
 		if (dev_data->usb_status == USB_DC_SUSPEND) {
-			cdc_acm_read_cb(cfg->endpoint[ACM_OUT_EP_IDX].ep_addr,
-					0, dev_data);
-			dev_data->usb_status = USB_DC_CONFIGURED;
-			LOG_INF("Define resumed");
+			if (dev_data->configured) {
+				LOG_INF("from suspend");
+				cdc_acm_read_cb(cfg->endpoint[ACM_OUT_EP_IDX].ep_addr,
+						0, dev_data);
+				dev_data->usb_status = USB_DC_CONFIGURED;
```
Comment (anangl) [inline subsys/usb/class/cdc_acm.c:451]: Instead of using such cheating here, it would be better to use the introduced `configured` flag in `cdc_acm_fifo_fill()` to check if the device is ready to send. I mean to replace:
https://github.com/zephyrproject-rtos/zephyr/blob/c0d7b39c7f402f044530fe25000d4dee6f9aae98/subsys/usb/class/cdc_acm.c#L568
And actually, after such change, the `usb_status` field could be removed entirely - there is no longer a need to check above if `usb_status` is `USB_DC_SUSPEND`, as the transfer is started only when the `configured` flag is set.

Comment (emob-nordic) [reply subsys/usb/class/cdc_acm.c:451]: I'm not sure I got You right. If We change it like this:
``` diff
-	if (dev_data->usb_status != USB_DC_CONFIGURED) {
+	if (dev_data->configured) {
		LOG_WRN("Device not configured, drop %d bytes", len);
		return 0;
	}
```
And the HOST will do:
Suspend->Resume->Configured->Suspend
The cdc will try to send even  `SUSPEND` was received last (we should not send then).
`cdc_acm_fifo_fill` must schedule work only when the last state was `USB_DC_CONFIGURED`

File: subsys/usb/class/cdc_acm.c (hunk 1 above)
Comment (emob-nordic) [reply subsys/usb/class/cdc_acm.c:423]: I think `LOG_DBG` would be even better.

**Comment by pabigot** [comment]
#26970 explains why I can't combine the CDC ACM composite sample with a USB console and get anything useful.  The fix here seems to solve that.

File: subsys/usb/class/cdc_acm.c (hunk 2 above)
Comment (anangl) [reply subsys/usb/class/cdc_acm.c:451]: Right, my mistake. The `configured` flag alone is not sufficient.
But my point was actually to make it clearer when the device is allowed to send. The current solution with stored `status` is IMO artificial. Especially when you need to change the `usb_staus` field to `USB_DC_CONFIGURED` after getting the callback with `USB_DC_RESUME` parameter. I think it would be better to use a flag like `can_send` instead. Alternatively, a `suspended` flag could be used (and then data could be sent `if (dev_data->configured && !dev_data->suspended)`).

File: subsys/usb/class/cdc_acm.c [hunk 3]
```diff
@@ -416,29 +418,38 @@ static void cdc_acm_do_cb(struct cdc_acm_dev_data_t *dev_data,
...
 		dev_data->rx_irq_ena = true;
 		dev_data->usb_status = status;
-		LOG_INF("Device configured");
+		dev_data->configured = true;
 		break;
 	case USB_DC_DISCONNECTED:
 		LOG_INF("Device disconnected");
 		cdc_acm_reset_port(dev_data);
 		dev_data->usb_status = status;
+		dev_data->configured = false;
```
Comment (anangl) [inline subsys/usb/class/cdc_acm.c:438]: It seems that this should be done also on receiving the callback with `USB_DC_RESET` status, so perhaps `cdc_acm_reset_port()` would be a better place for clearing this flag?

File: subsys/usb/class/cdc_acm.c (hunk 2 above)
Comment (emob-nordic) [reply subsys/usb/class/cdc_acm.c]: Updated.

**Comment by emob-nordic** [comment]
@stephanosio @jfischer-phytec-iot Could You please have a look? This PR is fixing an issue.

File: subsys/usb/usb_transfer.c [hunk 4]
```diff
@@ -245,6 +248,9 @@ int usb_transfer(uint8_t ep, uint8_t *data, size_t dlen, unsigned int flags,
 	} else {
 		/* ready to read, clear NAK */
 		ret = usb_dc_ep_read_continue(ep);
```
Comment (jfischer-phytec-iot) [inline subsys/usb/usb_transfer.c:250]: Please drop this commit. btw, line above is an other issue, mostly usb_dc_ep_read_continue from situation without and OUT event returns an error.

File: subsys/usb/class/cdc_acm.c [hunk 5]
```diff
@@ -419,42 +423,45 @@ static void cdc_acm_do_cb(struct cdc_acm_dev_data_t *dev_data,
...
 	case USB_DC_SUSPEND:
 		LOG_INF("Device suspended");
-		dev_data->usb_status = status;
+		dev_data->suspended = true;
 		break;
 	case USB_DC_RESUME:
-		if (dev_data->usb_status == USB_DC_SUSPEND) {
-			cdc_acm_read_cb(cfg->endpoint[ACM_OUT_EP_IDX].ep_addr,
+		LOG_INF("Device resumed");
+		if (dev_data->suspended) {
```
[the remark this answers is not in the document]
Comment (emob-nordic) [reply subsys/usb/class/cdc_acm.c:456]: If we want to correctly detect spurious `RESUME` events then we can't do that. Imagine a situation:
`Connected->Suspend->Resume` -> The device was not yet configured and the `Resume` event is not spurious. In fact the device was suspended during the enumeration and its possible.

We could clear `dev_data->suspended = false` on each `Resume` event but then we would not trace spurious `Resume`'s. I think we can do so but I know You wanted to highlight those spurious things recently so I decided not to do so.

File: subsys/usb/class/cdc_acm.c [hunk 6]
```diff
@@ -419,42 +423,45 @@ static void cdc_acm_do_cb(struct cdc_acm_dev_data_t *dev_data,
 	/* Check the USB status and do needed action if required */
 	switch (status) {
 	case USB_DC_ERROR:
-		LOG_DBG("Device error");
+		LOG_INF("Device error");
```
[the remark this answers is not in the document]
Comment (emob-nordic) [reply subsys/usb/class/cdc_acm.c]: done.

File: subsys/usb/usb_transfer.c (hunk 4 above)
Comment (emob-nordic) [reply subsys/usb/usb_transfer.c]: dropped.

**Review by jfischer-no — APPROVED** [review]

**Review by pabigot — APPROVED** [review]
Fixes `hid-cdc` now, fixed the problem I had three weeks ago then.

**Comment by ioannisg** [comment]
@emob-nordic #26725 seems already closed. Is this PR description accurate?

**Comment by emob-nordic** [comment]
@ioannisg Yes, #26725 is already closed but by the PR that introduced bug with duplicate transfers. I will remove it from the description if You insist.
