### PR TITLE
Bluetooth: host: disallow scan with timeout when BT_PRIVACY=y

### LINKED ISSUE #73634: Bluetooth: Host: Scanner never updates its RPA when timeout != 0
**Describe the bug**
When `scan_params.timeout != 0` the RPA never updates.

**To Reproduce**
Run the test case added in https://github.com/zephyrproject-rtos/zephyr/pull/73633

**Expected behavior**
The RPA updates.

**Impact**
It will become possible to track the scanning device.
Adding support for concurrent and scanning and initiating with a timeout will become harder.

### PR DESCRIPTION
**Pull request by jori-nordic**
See comment in code.

Fixes #73634

### CODE REVIEW

**Review by alwa-nordic — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

File: include/zephyr/bluetooth/bluetooth.h [hunk 1]
```diff
@@ -2283,6 +2283,10 @@ BUILD_ASSERT(BT_GAP_SCAN_FAST_WINDOW == BT_GAP_SCAN_FAST_INTERVAL_MIN,
  *       In order to enable directed advertiser reports then
  *       @kconfig{CONFIG_BT_SCAN_WITH_IDENTITY} must be enabled.
  *
+ * @note Setting the `param.timeout` parameter is not supported when
+ *       @kconfig{CONFIG_BT_PRIVACY} is enabled. Supplying a nonzero timeout
+ *       will result in an -EINVAL error code.
```
Comment (Thalley) [inline include/zephyr/bluetooth/bluetooth.h:2288]: It only affects active scan, right? 

```suggestion
 * @note Setting the `param.timeout` parameter is not supported when
 *       @kconfig{CONFIG_BT_PRIVACY} is enabled when the param.type is @ref BT_LE_SCAN_TYPE_ACTIVE. Supplying a nonzero timeout
 *       will result in an -EINVAL error code.
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: include/zephyr/bluetooth/bluetooth.h (hunk 1 above)
Comment (jori-nordic) [reply include/zephyr/bluetooth/bluetooth.h]: Yes, that's right.

**Review by jhedberg — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
