### PR TITLE
modem: modem_cmux: Increase modem cmux buf size

### LINKED ISSUE #63813: Bug: modem_cellular.c fails to resume sim7080 modem
**Describe the bug**
The modem_cellular.c driver fails to resume on the SIM7880 driver due to two bugs:
1. The AT+CMUX request is malformed
2. The modem_cmux module has a to small buffer for control channel commands

**To Reproduce**
1. (only follow to reproduce with logs) Apply this PR  https://github.com/zephyrproject-rtos/zephyr/pull/63675
2. Add `CONFIG_MODEM_MODULES_LOG_LEVEL_DBG=y` to the `net/cellular_modem` sample
3. Build and run the sample `net/cellular_modem` for a board containing a SIMCOM SIM7080 modem.
4. Observe the error `<wrn> modem_cmux; Command acknowledge buffer overrun`
5. Observe nothing happening until the sample fails.

**Expected behavior**
Sample should build and run without the error occurring.

**Impact**
The modem_cellular.c can not support the SIM7080 modem.

**Logs and console output**
Provided by @kartben 
```
[00:00:12.603,000] <dbg> modem_cmux: modem_cmux_process_received_byte: Received frame
[00:00:12.605,000] <dbg> modem_chat: modem_chat_log_received_command: OK
[00:00:12.605,000] <dbg> modem_chat: modem_chat_script_next: simcom_sim7080_dial_chat_script: step: 2
[00:00:12.605,000] <dbg> modem_chat: modem_chat_script_next: sending: AT+CFUN=1
[00:00:12.621,000] <dbg> modem_cmux: modem_cmux_process_received_byte: Received frame
[00:00:12.623,000] <dbg> modem_chat: modem_chat_log_received_command: OK
[00:00:12.623,000] <dbg> modem_chat: modem_chat_script_next: simcom_sim7080_dial_chat_script: step: 3
[00:00:12.623,000] <dbg> modem_chat: modem_chat_script_next: sending: ATD*99***1#
[00:00:12.624,000] <dbg> modem_chat: modem_chat_script_stop: simcom_sim7080_dial_chat_script: complete
[00:00:12.624,000] <inf> modem_cellular: event script success
[00:00:12.624,000] <inf> modem_cellular: switch from run dial script to await registered
[00:00:12.633,000] <dbg> modem_cmux: modem_cmux_process_received_byte: Received frame
[00:00:12.633,000] <wrn> modem_cmux: Command acknowledge buffer overrun
[00:00:12.633,000] <dbg> modem_cmux: modem_cmux_process_received_byte: Received frame
```
With patch which adds logging
```
[00:00:12.605,000] <inf> modem_cellular: switch from run dial script to await registered
[00:00:12.614,000] <dbg> modem_cmux: modem_cmux_log_received_frame: ch:0,cr:0,pf:0,type:UIH
[00:00:12.615,000] <dbg> modem_cmux: modem_cmux_log_received_frame: data:
                                     e3 07 07 8d 01                                   |.....
[00:00:12.615,000] <dbg> modem_cmux: modem_cmux_log_received_command: ea:1,cr:1,type:MSC
[00:00:12.615,000] <dbg> modem_cmux: modem_cmux_log_received_command: data:
                                     07 8d 01                                         |...
[00:00:12.615,000] <wrn> modem_cmux: Command acknowledge buffer overrun
[00:00:12.619,000] <dbg> modem_cmux: modem_cmux_log_received_frame: ch:1,cr:0,pf:1,type:UIH
[00:00:12.619,000] <dbg> modem_cmux: modem_cmux_log_received_frame: data:
                                     0d 0a 43 4f 4e 4e 45 43  54 20 31 35 30 30 30 30 |..CONNEC T 150000
                                     30 30 30 0d 0a                                   |000..
```

**Environment:**
 - OS: Linux
 - Toolchain Zephyr SDK
 - b1cc4e9a148b87b59e45222cbed36d8c1950abb6

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
This PR fixes two issues preventing the `modem_cellular.c` driver from connecting and configuring CMUX for the  SIMCOM SIM7080 modem.

1. Increases the buffer used for commands in the control channel within an instance of the
modem_cmux module. The buffer was not large enough to store an MSC command if the optional break signals where included. This commit fixes the issue and updates the test suite to use the max size MSC message.

2. Adjust `AT+CMUX` chat script requests to only contain required parameters.

Fixes #63813

### CODE REVIEW

**Review by rerickson1 — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

File: subsys/modem/modem_cmux.c [hunk 1]
```diff
@@ -23,7 +23,7 @@ LOG_MODULE_REGISTER(modem_cmux, CONFIG_MODEM_MODULES_LOG_LEVEL);
 #define MODEM_CMUX_DATA_FRAME_SIZE_MIN		(MODEM_CMUX_FRAME_SIZE_MAX + \
 						 MODEM_CMUX_DATA_SIZE_MIN)
 
-#define MODEM_CMUX_CMD_DATA_SIZE_MAX		(0x04)
+#define MODEM_CMUX_CMD_DATA_SIZE_MAX		(0x08)
```
Comment (kartben) [inline subsys/modem/modem_cmux.c:26]: Confirmed as working. I had initially tested with 0x10 but 0x08 seems to be enough to get rid of the buffer overrun I was seeing otherwise.

**Review by kartben — APPROVED** [review]
thanks!

**Review by jhedberg — APPROVED** [review]

File: subsys/modem/modem_cmux.c (hunk 1 above)
Comment (bjarki-trackunit) [reply subsys/modem/modem_cmux.c:26]: Nice :) I replicated the exact data that was sent from your modem in the unit test which is why I decided to go with a smaller buffer with confidence :)

File: drivers/modem/modem_cellular.c [hunk 2]
```diff
@@ -1365,8 +1364,7 @@ MODEM_CHAT_SCRIPT_CMDS_DEFINE(simcom_sim7080_init_chat_script_cmds,
 			      MODEM_CHAT_SCRIPT_CMD_RESP("AT+CGSN", imei_match),
 			      MODEM_CHAT_SCRIPT_CMD_RESP("", ok_match),
 			      MODEM_CHAT_SCRIPT_CMD_RESP("AT+CGMM", cgmm_match),
-			      MODEM_CHAT_SCRIPT_CMD_RESP_NONE("AT+CMUX=0,0,5,127,10,3,30,10,2",
-							      0));
+			      MODEM_CHAT_SCRIPT_CMD_RESP_NONE("AT+CMUX=0,0,5,127", 300));
```
[the remark this answers is not in the document]
Comment (bjarki-trackunit) [reply drivers/modem/modem_cellular.c:1367]: The defaults are 0,0,600 as the maximum frame size is set to 127. The maximum frame size is important as the modem_cmux instance internal buffer is scaled to this value. The T1 and N2 are not used or not configurable for the SIM7080, so it really won't matter what we set them to. I would prefer them and T2 to be default.
