### PR TITLE
fs: fuse: ensure S_IFxxx macros are available

### LINKED ISSUE #76932: Compilation error on Ubuntu 24.04 when CONFIG_FUSE_FS_ACCESS=y
**Describe the bug**

When trying to enable FUSE FS support (CONFIG_FUSE_FS_ACCESS=y), I get compilation errors due to `‘S_IFDIR` and a bunch of other macros not being declared

**To Reproduce**

Build for `native_sim_64` with `CONFIG_FUSE_FS_ACCESS=y`

**Expected behavior**

no compilation error

**Impact**

can't use Fuse FS access feature 

**Logs and console output**

```
[7/11] Building C object zephyr/subsys/fs/CMakeFiles/FS_FUSE.dir/fuse_fs_access.c.obj
FAILED: zephyr/subsys/fs/CMakeFiles/FS_FUSE.dir/fuse_fs_access.c.obj
ccache /usr/bin/gcc -DKERNEL -DK_HEAP_MEM_POOL_SIZE=0 -DLV_CONF_INCLUDE_SIMPLE=1 -DLV_CONF_PATH=/home/kartben/zephyrproject/zephyr/modules/lvgl/include/lv_conf.h -D_FILE_OFFSET_BITS=64 -D__ZEPHYR__=1 -I/home/kartben/zephyrproject/zephyr/build/zephyr/include/generated/zephyr -I/home/kartben/zephyrproject/zephyr/include -I/home/kartben/zephyrproject/zephyr/build/zephyr/include/generated -I/home/kartben/zephyrproject/zephyr/soc/native/inf_clock -I/home/kartben/zephyrproject/zephyr/boards/native/native_sim -I/home/kartben/zephyrproject/zephyr/scripts/native_simulator/common/src/include -I/home/kartben/zephyrproject/zephyr/scripts/native_simulator/native/src/include -I/usr/include/fuse -I/home/kartben/zephyrproject/modules/lib/gui/lvgl/src -I/home/kartben/zephyrproject/zephyr/modules/lvgl/include -Wshadow -fno-strict-aliasing -Og -imacros /home/kartben/zephyrproject/zephyr/build/zephyr/include/generated/zephyr/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/home/kartben/zephyrproject/zephyr/samples/subsys/smf/smf_calculator=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/kartben/zephyrproject/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/kartben/zephyrproject=WEST_TOPDIR -ffunction-sections -fdata-sections -m64 -fPIC -fvisibility=hidden -fno-freestanding -std=c11 -MD -MT zephyr/subsys/fs/CMakeFiles/FS_FUSE.dir/fuse_fs_access.c.obj -MF zephyr/subsys/fs/CMakeFiles/FS_FUSE.dir/fuse_fs_access.c.obj.d -o zephyr/subsys/fs/CMakeFiles/FS_FUSE.dir/fuse_fs_access.c.obj -c /home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c: In function ‘fuse_fs_access_getattr’:
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c:101:33: error: ‘S_IFDIR’ undeclared (first use in this function); did you mean ‘S_ISDIR’?
  101 |                 stat->st_mode = S_IFDIR | S_IRWX_DIR;
      |                                 ^~~~~~~
      |                                 S_ISDIR
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c:101:33: note: each undeclared identifier is reported only once for each function it appears in
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c:115:33: error: ‘S_IFREG’ undeclared (first use in this function); did you mean ‘S_ISREG’?
  115 |                 stat->st_mode = S_IFREG | S_IRW_FILE;
      |                                 ^~~~~~~
      |                                 S_ISREG
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c: In function ‘fuse_fs_access_readmount’:
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c:138:24: error: ‘S_IFDIR’ undeclared (first use in this function); did you mean ‘S_ISDIR’?
  138 |         stat.st_mode = S_IFDIR | S_IRWX_DIR;
      |                        ^~~~~~~
      |                        S_ISDIR
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c: In function ‘fuse_fs_access_readdir’:
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c:213:24: error: ‘S_IFDIR’ undeclared (first use in this function); did you mean ‘S_ISDIR’?
  213 |         stat.st_mode = S_IFDIR | S_IRWX_DIR;
      |                        ^~~~~~~
      |                        S_ISDIR
/home/kartben/zephyrproject/zephyr/subsys/fs/fuse_fs_access.c:235:40: error: ‘S_IFREG’ undeclared (first use in this function); did you mean ‘S_ISREG’?
  235 |                         stat.st_mode = S_IFREG | S_IRW_FILE;
      |                                        ^~~~~~~
      |                                        S_ISREG
```

**Environment (please complete the following information):**

 - OS: Ubuntu 24.04
 - Toolchain (e.g Zephyr SDK, ...): SDK 0.16.8 
 - Commit SHA or Version used: #857adb28e378a99dac02a574d35fae36c00dd624 but likely not a recent bug.

**Additional context**
Fix merged in main already #76900

### PR DESCRIPTION
**Pull request by kartben**
set _XOPEN_SOURCE appropriately to avoid compilation errors due to missing S_IFxxx macros on some systems.

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]

**Review by aescolar — APPROVED** [review]
Out of curiosity in which distro did you see this problem?

**Comment by kartben** [comment]
> Out of curiosity in which distro did you see this problem?
> 

Ubuntu 24.04 😶 on WSL

File: subsys/fs/fuse_fs_access.c [hunk 1]
```diff
@@ -15,6 +18,7 @@
 #include <stdlib.h>
 #include <string.h>
 #include <sys/mount.h>
+#include <sys/stat.h>
```
Comment (aescolar) [inline subsys/fs/fuse_fs_access.c:21]: Is this really needed?

**Comment by aescolar** [comment]
> Ubuntu 24.04

Thanks, I can also repro in plain Ubuntu 24.04 :)

File: subsys/fs/fuse_fs_access.c (hunk 1 above)
Comment (kartben) [reply subsys/fs/fuse_fs_access.c:21]: It's not needed to fix the compilation error, indeed, so I don't know whether it's good practice or not to add this include? I think that's where the macros are actually declared?

Comment (aescolar) [reply subsys/fs/fuse_fs_access.c:21]: I'd consider it more correct to include it yes.

**Comment by aescolar** [comment]
@kartben would you be so kind as to create an issue so we can backport this fix?
