### PR TITLE
net: tftp: Coverity fixes

### LINKED ISSUE #65360: [Coverity CID: 323108] Copy into fixed size buffer in subsys/net/lib/tftp/tftp_client.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/net/lib/tftp/tftp_client.c

Category: Security best practices violations
Function: `send_err`
Component: Networking
CID: [323108](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=323108)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/tftp/tftp_client.c#L158

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_STRING_OVERFLOW). ([CWE-120](http://cwe.mitre.org/data/definitions/120.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #65369: [Coverity CID: 323084] Unchecked return value from library in subsys/net/lib/tftp/tftp_client.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/net/lib/tftp/tftp_client.c

Category: Error handling issues
Function: `send_request`
Component: Networking
CID: [323084](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=323084)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/tftp/tftp_client.c#L225

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #65371: [Coverity CID: 323076] Unchecked return value from library in subsys/net/lib/tftp/tftp_client.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/net/lib/tftp/tftp_client.c

Category: Error handling issues
Function: `tftp_get`
Component: Networking
CID: [323076](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=323076)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/tftp/tftp_client.c#L296

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by rlubos**
Fix a few minor issues spotted by Coverity.

Fixes #65360
Fixes #65369
Fixes #65371

### CODE REVIEW

File: subsys/net/lib/tftp/tftp_client.c [hunk 1]
```diff
@@ -222,7 +222,11 @@ static int send_request(int sock, struct tftpc *client,
 		}
 
 		/* Limit communication to the specific address:port */
-		connect(sock, &from_addr, from_addr_len);
+		if (connect(sock, &from_addr, from_addr_len) < 0) {
+			LOG_ERR("connect failed, err %d", errno);
+			ret = -errno;
```
Comment (jukkar) [inline subsys/net/lib/tftp/tftp_client.c:230]: It might make sense to switch the ordering of these statements as the errno might get set in logger. Also I am proposing that all the error values are printed as <0 just to make sure the value sinks in to the reader.
So suggesting
```
ret = -errno;
LOG_ERR("...", ret);
```

File: subsys/net/lib/tftp/tftp_client.c [hunk 2]
```diff
@@ -293,7 +293,10 @@ int tftp_get(struct tftpc *client, const char *remote_file, const char *mode)
 
 			if (client->callback == NULL) {
 				LOG_ERR("No callback defined.");
-				send_err(sock, client, TFTP_ERROR_DISK_FULL, NULL);
+				if (send_err(sock, client, TFTP_ERROR_DISK_FULL, NULL) < 0) {
+					LOG_ERR("Failed to send error response, err: %d",
+						errno);
```
Comment (jukkar) [inline subsys/net/lib/tftp/tftp_client.c:305]: Here too, I suggest printing `-errno`

**Review by jukkar — COMMENTED** [review]
Looks good, minor nits about the printouts.

File: subsys/net/lib/tftp/tftp_client.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/lib/tftp/tftp_client.c:229]: That's good point, updated the commit as suggested.

**Review by jukkar — DISMISSED** [review]

File: subsys/net/lib/tftp/tftp_client.c [hunk 3]
```diff
@@ -155,8 +155,11 @@ static inline int send_err(int sock, struct tftpc *client, int err_code, char *e
 
 	/* Copy the Error String. */
 	if (err_msg != NULL) {
-		strcpy(client->tftp_buf + req_size, err_msg);
-		req_size += strlen(err_msg);
+		size_t copy_len = MIN(sizeof(client->tftp_buf) - req_size,
+				      strlen(err_msg));
```
Comment (pdgendt) [inline subsys/net/lib/tftp/tftp_client.c:159]: The `MIN` macro might have the effect of calling it twice.

```suggestion
		size_t copy_len = strlen(err_msg);
		if (copy_len > sizeof(client->tftp_buf) - req_size) {
			copy_len = sizeof(client->tftp_buf) - req_size;
		}
```

**Review by pdgendt — APPROVED** [review]

File: subsys/net/lib/tftp/tftp_client.c (hunk 3 above)
Comment (rlubos) [reply subsys/net/lib/tftp/tftp_client.c]: Thanks, updated as suggested.

**Review by jukkar — APPROVED** [review]
