### PR TITLE
Infineon: edge devices: Correct cm33/ns support 

### LINKED ISSUE #106589: soc:infineon:pse84: the core clock update fails if clocks are secured
### Describe the bug

Stems from https://github.com/zephyrproject-rtos/zephyr/issues/106232 

The bug fix done for the above bug is correct but does not work if the clocks are secured and SRF is not in place to request a read of the clock frequency from the non secure side. 

Therefore we need to use a different api that can use the info from device tree to properly update the Core Clock values.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lauracarlesso**
Correct the regression issues that was introduced with https://github.com/zephyrproject-rtos/zephyr/pull/106234 for TF-m without SRF and clean up the cm33/ns init code. 
Additionally use the correct start up files for the secure/non secure cases..

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/106589

### CODE REVIEW

File: soc/infineon/edge/pse84/soc_pse84_m33_ns.c [hunk 1]
```diff
@@ -10,44 +10,17 @@
...
 #include <zephyr/device.h>
+#include <zephyr/devicetree.h>
 #include <zephyr/init.h>
 #include <zephyr/kernel.h>
 
-/*
- * This function will allow execute from sram region.
- */
-#ifdef CONFIG_ARM_MPU
-void disable_mpu_rasr_xn(void)
```
Comment (teburd) [inline soc/infineon/edge/pse84/soc_pse84_m33_ns.c:20]: Do we no longer need the mpu changes? I assume not but wanted to verify

**Review by teburd — APPROVED** [review]

File: soc/infineon/edge/pse84/soc_pse84_m33_ns.c (hunk 1 above)
Comment (lauracarlesso) [reply soc/infineon/edge/pse84/soc_pse84_m33_ns.c:20]: No, in KConfig we have CPU_HAS_CUSTOM_FIXED_SOC_MPU_REGIONS enabled for all cores/partitions and in CMakeLists.txt we have zephyr_sources(mpu_regions.c) unconditionally included. 
So the initialization is done properly with that mechanism.

**Review by sreeramIfx — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]
