### PR TITLE
posix: clock_nanosleep implementation

### LINKED ISSUE #59949: posix: implement `clock_nanosleep()`
There are currently 20 missing POSIX functions with trivial implementations, `clock_nanosleep()` is one of them.

> clock_nanosleep - high resolution sleep with specifiable clock
> 
> If the flag TIMER_ABSTIME is not set in the flags argument, the clock_nanosleep() function shall cause the current thread to be suspended from execution until either the time interval specified by the rqtp argument has elapsed, or a signal is delivered to the calling thread and its action is to invoke a signal-catching function, or the process is terminated. The clock used to measure the time shall be the clock specified by clock_id.
> 
> If the flag TIMER_ABSTIME is set in the flags argument, the clock_nanosleep() function shall cause the current thread to be suspended from execution until either the time value of the clock specified by clock_id reaches the absolute time specified by the rqtp argument, or a signal is delivered to the calling thread and its action is to invoke a signal-catching function, or the process is terminated. If, at the time of the call, the time value specified by rqtp is less than or equal to the time value of the specified clock, then clock_nanosleep() shall return immediately and the calling process shall not be suspended.
> 
> The suspension time caused by this function may be longer than requested because the argument value is rounded up to an integer multiple of the sleep resolution, or because of the scheduling of other activity by the system. But, except for the case of being interrupted by a signal, the suspension time for the relative clock_nanosleep() function (that is, with the TIMER_ABSTIME flag not set) shall not be less than the time interval specified by rqtp, as measured by the corresponding clock. The suspension for the absolute clock_nanosleep() function (that is, with the TIMER_ABSTIME flag set) shall be in effect at least until the value of the corresponding clock reaches the absolute time specified by rqtp, except for the case of being interrupted by a signal.
> 
> The use of the clock_nanosleep() function shall have no effect on the action or blockage of any signal.
> 
> The clock_nanosleep() function shall fail if the clock_id argument refers to the CPU-time clock of the calling thread. It is unspecified whether clock_id values of other CPU-time clocks are allowed.

See https://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_nanosleep.html

See RFC #51211 for more info.

### PR DESCRIPTION
**Pull request by TomFinet**
Implementation of the clock_nanosleep function.

Fixes #59949

### CODE REVIEW

File: tests/posix/common/src/clock.c [hunk 1]
```diff
@@ -123,3 +123,163 @@ ZTEST(posix_apis, test_realtime)
 	zassert_true(rts.tv_nsec >= tv.tv_usec * NSEC_PER_USEC,
 			"gettimeofday didn't provide correct result");
 }
+
+ZTEST(posix_apis, test_clock_nanosleep_errors_errno) {
```
Comment (cfriedt) [inline tests/posix/common/src/clock.c:127]: @TomFinet - thanks for your contribution!

It might be better to place this test into `tests/posix/common/src/nanosleep.c` and with that I think a lot of test code can likely be re-used with slight modification.

E.g. fector out code to an `errors_common()` function, modify the `common()` function as well. You should be able to specify a clock source and flags to the common functions.

**Review by cfriedt — CHANGES_REQUESTED** [review]
Looks good - please just fix compliance issues, failed tests, and please refactor tests in nanosleep.c

File: lib/posix/clock.c [hunk 2]
```diff
@@ -106,6 +105,66 @@ int clock_settime(clockid_t clock_id, const struct timespec *tp)
...
+	k_spinlock_key_t key;
+	const bool update_rmtp = rmtp != NULL;
+
+	if (clock_id != CLOCK_REALTIME && clock_id != CLOCK_MONOTONIC) {
+		errno = EINVAL;
+		return -1;
+	}
+
+	if ((flags & TIMER_ABSTIME) != TIMER_ABSTIME) {
+		return nanosleep(rqtp, rmtp);
```
Comment (cfriedt) [inline lib/posix/clock.c:129]: In most implementations I would guess that `nanosleep(rqtp, rmtp)` is probably shorthand for `clock_nanosleep(CLOCK_MONOTONIC, 0, rqtp, rmtp)`.

But sticking with this for now is ok.

I sort of wonder, wouldn't it be easier to cover the absolute time to a relative time first and then just make `nanosleep()` do the heavy lifting?

**Review by cfriedt — CHANGES_REQUESTED** [review]
It seems this PR includes a significant amount of code formatting / whitespace changes.

Can you please make the whitespace changes in a separate commit, if necessary, or simply undo the formatting changes in your current code commit?

File: lib/posix/clock.c (hunk 2 above)
Comment (TomFinet) [reply lib/posix/clock.c:129]: Yeh, as you say `nanosleep` is a special case of `clock_nanosleep`. So I think it would make sense for `nanosleep` to just `return clock_nanosleep(CLOCK_.REALTIME, 0, rqtp, rmtp)`.

I would need to change `clock_nanosleep` to handle both relative and absolute times. But would cut down on a lot of redundancy that exists between `nanosleep` and `clock_nanosleep` at the moment.

Converting an absolute timeout into a relative one would look something like:

1. call `clock_gettime()`
2. compute difference between absolute time and current time.
3. call `nanosleep` with a delay of this difference. 

If we are preempted between 1 and 3, then we will sleep for longer than wanted. An absolute sleep avoids this, issue and that is why I feel we should leave it in.

Comment (TomFinet) [reply lib/posix/clock.c:129]: Could we not instead convert relative time to absolute time in clock_nanosleep?

Comment (cfriedt) [reply lib/posix/clock.c:129]: Of course - whatever you are more comfortable with 👍

**Review by cfriedt — APPROVED** [review]
LGTM & thanks for your contribution :-)

**Review by mbolivar-ampere — APPROVED** [review]
