### PR TITLE
shell: kernel: fix reset command echo abrupt termination

### LINKED ISSUE #35325: Shell: Kernel: Reboot: echo is abruptly terminated
**Describe the bug**
When the `kernel reboot cold` or `kernel reboot warm` command is input quickly (by a production test system) the kernel reboot command's echo is abruptly terminated 10% of the time by the system's reset.

**To Reproduce**
1. Add line `CONFIG_REBOOT=y` to `samples\subsys\shell\shell_module\prj.conf`
2. west build -p -b nrf52dk_nrf52832 -s samples\subsys\shell\shell_module -d build
3. Input the `kernel reboot cold` or `kernel reboot warm` command at or near to max baud rate.

**Expected behavior**
Kernel reboot command's echo completes successfully every time.

**Impact**
Our production line test fails 10% of the time when using this command.

### PR DESCRIPTION
**Pull request by nwsetec**
Allow time for the shell to successfully echo the reboot command input
before the reboot abruptly terminates it. This can help external
systems that interact with the shell and require the reboot command's
echo to successfully complete to synchronise with the device.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/35325

Signed-off-by: Nick Ward <nick.ward@setec.com.au>

### CODE REVIEW

File: subsys/shell/modules/kernel_service.c [hunk 1]
```diff
@@ -220,6 +220,9 @@ static int cmd_kernel_reboot_warm(const struct shell *shell,
 {
 	ARG_UNUSED(argc);
 	ARG_UNUSED(argv);
+#if (CONFIG_KERNEL_SHELL_REBOOT_DELAY > 0)
```
Comment (jakub-uC) [inline subsys/shell/modules/kernel_service.c:223]: To be considered if `IS_ENABLED` is better. @nordic-krch  any thoughts?

Comment (nordic-krch) [reply subsys/shell/modules/kernel_service.c:223]: `IS_ENABLED` cannot be used because it is not binary value you might do
```
if (CONFIG_KERNEL_SHELL_REBOOT_DELAY > 0) {
   k_sleep();
}
```
but compilation will fail when CONFIG_REBOOT is not defined. So i guess it should stay as is.

**Review by nordic-krch — APPROVED** [review]

**Review by jakub-uC — APPROVED** [review]
