### PR TITLE
dts/st: enables possibility to define Flash and SRAM out of tree

### LINKED ISSUE #9978: soc: stm32: Extra tree soc configuration is blocked by /dts/arm/st/mem.h
After configuring an extra tree SOC based on documentation from #9776 "Move soc code under ZEPHYR_PROJECT/soc" , the build stopps with:
```
.../mem.h:128:2: error: #error "Flash, RAM, and CCM sizes not defined for this chip"
 #error "Flash, RAM, and CCM sizes not defined for this chip"
  ^~~~~
```

### PR DESCRIPTION
**Pull request by erwango**
In case of out of tree SoC, mem.h will trigger and error since
it is not aware of new SoC CONFIG_SOC_<reference>.
Modify error condition in order to generate the error only if
the flash and error size are not defined at this point (even in
out of tree case).

Fixes #9978

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

File: dts/arm/st/mem.h [hunk 1]
```diff
@@ -125,7 +125,11 @@
 #define DT_FLASH_SIZE		__SIZE_K(256)
 #define DT_SRAM_SIZE		__SIZE_K(64)
 #else
-#error "Flash, RAM, and CCM sizes not defined for this chip"
+#ifndef DT_FLASH_SIZE
```
Comment (galak) [inline dts/arm/st/mem.h]: can we do this as:
#if !defined(DT_FLASH_SIZE) and !defined(DT_SRAM_SIZE)

Comment (galak) [reply dts/arm/st/mem.h]: Also, wonder if we should put this check at the very top of the file.

**Review by galak — DISMISSED** [review]
Some minor style feedback.
