### PR TITLE
soc: stm32l0: enable DMA clock to fix Hardfault linked to DBGMCU bits

### LINKED ISSUE #37119: tests: kernel tests hardfault on nucleo_l073rz
**Describe the bug**
Hardfault occurs on nucleo_l073rz, while executing some tests on automatic test bench.
Mainly kernel tests, but not exclusively.
HardFault is reproducible easily under some circumstances (see analysis below).
List of faulty tests
  
>  tests/arch/arm/arm_runtime_nmi/arch.interrupt.arm.nmi, nucleo_l073rz 
>    tests/benchmarks/latency_measure/benchmark.kernel.latency.stm32, nucleo_l073rz 
>    tests/kernel/context/kernel.common, nucleo_l073rz 
>    tests/kernel/fifo/fifo_api/kernel.fifo, nucleo_l073rz 
>    tests/kernel/fifo/fifo_timeout/kernel.fifo.timeout, nucleo_l073rz 
>    tests/kernel/interrupt/arch.interrupt, nucleo_l073rz 
>    tests/kernel/lifo/lifo_usage/kernel.lifo.usage, nucleo_l073rz 
>    tests/kernel/mbox/mbox_api/kernel.mailbox.api, nucleo_l073rz 
>    tests/kernel/mem_heap/k_heap_api/kernel.k_heap_api, nucleo_l073rz 
>    tests/kernel/mem_protect/sys_sem/kernel.memory_protection.sys_sem.nouser, nucleo_l073rz 
>    tests/kernel/mem_protect/userspace/kernel.memory_protection.userspace, nucleo_l073rz 
>    tests/kernel/mem_slab/mslab_api/kernel.memory_slabs.api, nucleo_l073rz 
>    tests/kernel/mem_slab/mslab_concept/kernel.memory_slabs.concept, nucleo_l073rz 
>    tests/kernel/msgq/msgq_api/kernel.message_queue, nucleo_l073rz 
>    tests/kernel/msgq/msgq_usage/kernel.message_queue_usage, nucleo_l073rz 
>    tests/kernel/mutex/mutex_api/kernel.mutex, nucleo_l073rz 
>    tests/kernel/mutex/sys_mutex/system.mutex.nouser, nucleo_l073rz 
>    tests/kernel/pending/kernel.objects, nucleo_l073rz 
>    tests/kernel/pipe/pipe/kernel.pipe, nucleo_l073rz 
>    tests/kernel/pipe/pipe_api/kernel.pipe.api, nucleo_l073rz 
>    tests/kernel/profiling/profiling_api/kernel.common.profiling, nucleo_l073rz 
>    tests/kernel/sched/deadline/kernel.scheduler.deadline, nucleo_l073rz 
>    tests/kernel/sleep/kernel.common.timing, nucleo_l073rz 
>    tests/kernel/threads/dynamic_thread/kernel.threads.dynamic, nucleo_l073rz 
>    tests/kernel/threads/thread_init/kernel.threads.init, nucleo_l073rz 
>    tests/kernel/threads/tls/kernel.threads.tls, nucleo_l073rz 
>    tests/kernel/threads/tls/kernel.threads.tls.userspace, nucleo_l073rz 
>    tests/kernel/timer/timer_monotonic/kernel.timer.monotonic, nucleo_l073rz 
>    tests/kernel/workq/work/kernel.work.api, nucleo_l073rz 
>    tests/kernel/workq/work_queue/kernel.workqueue, nucleo_l073rz 
>    tests/lib/time/libraries.libc.time, nucleo_l073rz 
>    tests/subsys/logging/log_core_additional/logging.add.async, nucleo_l073rz 
>    tests/subsys/pm/power_mgmt/subsys.pm.device_pm, nucleo_l073rz

**To Reproduce**
1. Enable debug and PowerManagement in prj.conf:  CONFIG_DEBUG=y and CONFIG_PM=y  (to force the bug systematically)
2. west build -p auto -b nucleo_l073rz tests/kernel/mutex/mutex_api/
3. west flash

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.6.0-1131-ge287639479d7  ***
Running test suite mutex_api
===================================================================
START - test_mutex_lock_unlock
 PASS - test_mutex_lock_unlock in 0.2 seconds
===================================================================
START - test_mutex_reent_lock_forever
access resource from main thread
access resource from main thread
E: ***** HARD FAULT *****
E: r0/a1:  0x2000077c  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x08007575
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x08003c32
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x200003e0 (idle 00)
E: Halting system
```

**Environment (please complete the following information):**
 - OS:  Linux and Windows
 - Toolchain Zephyr SDK
 - Commit SHA 35011489229b5acb049f325fcca3a38ba012fdd4

### PR DESCRIPTION
**Pull request by ABOSTM**
soc: stm32l0: enable DMA clock to fix Hardfault linked to DBGMCU bits

On STM32L0, there are some hardfault when DBGMCU bit Sleep, Stop
or Standby are enabled. See #37119
For unclear reason, enabling DMA clock fixes this issue.
(similarly than #38561, DMA clock comes with DBGMCU bits)

Fixes #37119

### CODE REVIEW

File: soc/arm/st_stm32/stm32l0/soc.c [hunk 1]
```diff
@@ -52,6 +52,13 @@ static int stm32l0_init(const struct device *arg)
 	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);
 	LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE1);
 
+	/* On STM32L0, there are some hardfault when enabling DBGMCU bit:
+	 * Sleep, Stop or Standby. See #37119
```
Comment (erwango) [inline soc/arm/st_stm32/stm32l0/soc.c:56]: Please use full length adresses (https://github.com/zephyrproject-rtos/zephyr/pull/37119).
(For those not familiar with github)

**Review by erwango — CHANGES_REQUESTED** [review]
Nitpick

File: soc/arm/st_stm32/stm32l0/soc.c [hunk 2]
```diff
@@ -52,6 +52,13 @@ static int stm32l0_init(const struct device *arg)
...
+	 * For unclear reason, enabling DMA clock fixes this issue
+	 * (similarly than it fixes #34324)
+	 */
+	__HAL_RCC_DMA1_CLK_ENABLE();
```
Comment (tagunil) [inline soc/arm/st_stm32/stm32l0/soc.c:60]: Wouldn't it be better to use a LL call here? Something like LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_DMA1);

Comment (FRASTM) [reply soc/arm/st_stm32/stm32l0/soc.c]: would it be safe to keep DMA reset ?

File: soc/arm/st_stm32/stm32l0/soc.c (hunk 1 above)
Comment (ABOSTM) [reply soc/arm/st_stm32/stm32l0/soc.c]: Done

File: soc/arm/st_stm32/stm32l0/soc.c (hunk 2 above)
Comment (ABOSTM) [reply soc/arm/st_stm32/stm32l0/soc.c]: Not a major difference, but OK. done

**Review by FRASTM — COMMENTED** [review]
This is a WA, should this be combined with the DBGEN bit of the APB2EN 
LL_APB2_GRP1_IsEnabledClock(LL_APB2_GRP1_PERIPH_DBGMCU) ...

**Review by erwango — APPROVED** [review]

File: soc/arm/st_stm32/stm32l0/soc.c (hunk 2 above)
Comment (ABOSTM) [reply soc/arm/st_stm32/stm32l0/soc.c]: > would it be safe to keep DMA reset ?

Keeping reset signal of the DMA sound to me like an intermediate state, and it is not supposed to be kept hold.
So I think it is safer to release this signal. It is the way I tested, and it is working well up to now.
Lets keep it

**Comment by ABOSTM** [comment]
> This is a WA, should this be combined with the DBGEN bit of the APB2EN
> LL_APB2_GRP1_IsEnabledClock(LL_APB2_GRP1_PERIPH_DBGMCU) ...

I cannot combined with such condition because, DBGMCU clock (and bit) may be set later (for example in stm32_power_init())

**Review by FRASTM — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Comment by tagunil** [comment]
For now it looks like the merged commit enables DBGMCU instead of DMA. Is that also helps with the issue?

**Comment by ABOSTM** [comment]
> For now it looks like the merged commit enables DBGMCU instead of DMA. Is that also helps with the issue?

Right, sorry for this mistake, and thanks for pointing out.
Fixe available: #38703
