### PR TITLE
net: Change the net_linkaddr struct to not use pointers

### LINKED ISSUE #86652: net: ip: Link Layer Address of DGRAM packets received by sockets might be corrupted
**Describe the bug**

While our Wi-Fi STA with hostap is running zperf download Peak Throughput test, when AP starts group rekey process,
it sends EAPOL M1 packet to us and expects M2 packet. But hostap receives a packet with wrong link address. (It should be AP's mac address. But it is mac address of zperf client device like PC backend)
The root cause is that struct `net_linkaddr lladdr_src->addr` in `struct net_pkt` is a pointer rather than local storage.
It is assigned in `ethernet_recv()`, pointing to payload L2 header of EAPOL pkt. But then the L2 header is removed in payload after l2_processed. (`net_pkt_set_l2_processed(1)` in `process_data()`)
Then for the `AF_PACKET` family, the EAPOL pkt goes through
`net_packet_socket_input()->net_packet_socket_input()->net_conn_input()->conn_raw_socket()`.
In `conn_raw_socket()` it is cloned. And the cloned pkt will be sent to sockets' `recv_q`. The original pkt will be freed.
But during the pkt clone in `clone_pkt_attributes()`, `clone_pkt->lladdr_src->addr` is directly value set by
`orig_pkt->lladdr_src->addr`, which points to original buffer, which will be freed and override.
(There is `clone_pkt_lladdr()` trying to fix this issue. But it only fixes the RAW socket issue. Because DGRAM socket packet is cloned after L2 processed, which means it does not have L2 header. And `lladdr_src`, at least in Wi-Fi case, points to L2 header of pkt payload. So for DGRAM packet, `clone_pkt_lladdr()` cannot find offset for lladdr and it will remain pointing to original pkt payload)

Simple example for DGRAM AF_PACKET helping to understand
`orig_pkt->lladdr_src->addr`  Pointing to  `orig_pkt->buffer->data => net_pkt_pull(orig_pkt, L2_hdr size) =>
clone_pkt->lladdr_src->addr` Pointing to `orig_pkt->buffer->data => clone_pkt_lladdr() => net_pkt_find_offset(orig_pkt->lladdr_src->addr)` fail because pkt's L2_hdr is removed

**To Reproduce**

1. Build Wi-Fi STA example with hostap.
2. Set external AP's group rekey period to 10 seconds.
3. Do wifi connect with external AP.
4. Do zperf download peak throughput test longer than AP's group rekey period.
We will disconnect after when AP wants to do group rekey.

**Expected behavior**

We do rekey and zperf download continuously.

**Impact**

Wi-Fi is disconnected.
Besides, there is risk of corrupted link layer address on all AF_PACKET DGRAM packets

**Logs and console output**

```
<dbg> wpa_supp: wpa_printf_impl: ml: Not associated - Delay processing of received EAPOL frame (state=COMPLETED bssid=xx:xx:xx:xx:xx:xx)
<inf> wpa_supp: ml: CTRL-EVENT-DISCONNECTED
```

**Environment (please complete the following information):**
-OS: Linux
-Toolchain: Zephyr SDK
-Version: Zephyr 4.0
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

### PR DESCRIPTION
**Pull request by jukkar**
Previously the net_linkaddr struct had pointers to the link address. This is error prone and difficult to handle if cloning the packet as those pointers can point to wrong place. Mitigate this issue by allocating the space for link address in net_linkaddr struct. This will increase the size of the net_pkt by 4 bytes for IEEE 802.15.4 where the link address length is 8, but there no increase in size if link address is 6 bytes like in Ethernet/Wi-Fi.

Fixes #86652

### CODE REVIEW

**Comment by pdgendt** [comment]
According to the contribution guidelines, commits should not have `Fixes #XXXXX` in the body.

File: include/zephyr/net/net_linkaddr.h [hunk 1]
```diff
@@ -146,6 +131,32 @@ static inline int net_linkaddr_set(struct net_linkaddr_storage *lladdr_store,
 	return 0;
 }
 
+/**
+ *
+ * @brief Copy link address from one variable to another.
+ *
+ * @param lladdr_dst The link address structure destination.
+ * @param lladdr_src The link address structure to source.
```
Comment (rlubos) [inline include/zephyr/net/net_linkaddr.h:139]: Param names here don't match with the actual params.

File: subsys/net/ip/icmpv6.c [hunk 2]
```diff
@@ -145,8 +145,8 @@ static int icmpv6_handle_echo_request(struct net_icmp_ctx *ctx,
 	 * that it is set properly using a value from neighbor cache.
 	 * Same for source as it points to original pkt ll src address.
 	 */
-	net_pkt_lladdr_dst(reply)->addr = NULL;
-	net_pkt_lladdr_src(reply)->addr = NULL;
+	memset(net_pkt_lladdr_dst(reply)->addr, 0, sizeof(net_pkt_lladdr_dst(reply)->addr));
```
Comment (rlubos) [inline subsys/net/ip/icmpv6.c:148]: I wonder, shouldn't we set `len` to 0 too, as now neigbor cache check seems to rely on this field?

File: subsys/net/ip/ipv6_nbr.c [hunk 3]
```diff
@@ -1210,7 +1212,7 @@ static int handle_ns_input(struct net_icmp_ctx *ctx,
 	const struct in6_addr *na_src;
 	const struct in6_addr *na_dst;
 	struct in6_addr *tgt;
-	struct net_linkaddr_storage src_lladdr_s;
+	struct net_linkaddr src_lladdr_s;
```
Comment (rlubos) [inline subsys/net/ip/ipv6_nbr.c:1215]: It doesn't seem we still need the second struct here? We could call `read_llao()` directly with `src_lladdr` I think?

File: subsys/net/ip/route.c [hunk 4]
```diff
@@ -1079,13 +1079,15 @@ int net_route_packet(struct net_pkt *pkt, struct in6_addr *nexthop)
 	 * destination address to be the nexthop recipient.
 	 */
 	if (is_ll_addr_supported(net_pkt_iface(pkt))) {
-		net_pkt_lladdr_src(pkt)->addr = net_pkt_lladdr_if(pkt)->addr;
```
Comment (rlubos) [inline subsys/net/ip/route.c:1082]: Maybe just memcpy entire struct, instead of copying each field separately? Same below.

File: subsys/net/ip/icmpv6.c (hunk 2 above)
Comment (jukkar) [reply subsys/net/ip/icmpv6.c:148]: Yes, definitely we need to set the len to 0, otherwise the address is considered valid. Will fix.

File: subsys/net/ip/ipv6_nbr.c (hunk 3 above)
Comment (jukkar) [reply subsys/net/ip/ipv6_nbr.c:1215]: Yes, very true, will fix.

**Comment by jukkar** [comment]
* CI fixes
* Added info to migration guide
* I created some helpers to setup `net_linkaddr` and made the code to use those. This avoids the constant memcpy and setting the length/type of the link address

File: include/zephyr/net/net_linkaddr.h [hunk 5]
```diff
@@ -146,6 +131,78 @@ static inline int net_linkaddr_set(struct net_linkaddr_storage *lladdr_store,
...
+	return 0;
+}
+
+/**
+ * @brief Clear link address.
+ *
+ * @param lladdr The link address structure.
+ * @return 0 if ok, <0 if error
+ */
+static inline int net_linkaddr_clear(struct net_linkaddr *lladdr)
```
Comment (alexanderwachter) [inline include/zephyr/net/net_linkaddr.h:165]: This function could just call the create function with the src members as parameters

**Comment by jukkar** [comment]
* Updated according to comments
* More CI fixes

**Comment by jukkar** [comment]
* CI fixes

**Comment by jukkar** [comment]
* More CI fixes

File: doc/releases/migration-guide-4.2.rst [hunk 6]
```diff
@@ -133,6 +133,17 @@ Bluetooth Host
 Networking
 **********
 
+* The struct :c:struct:`net_linkaddr_storage` has been renamed to struct
```
Comment (pdgendt) [inline doc/releases/migration-guide-4.2.rst:136]: This struct doesn't exist anymore, so I don't think this directive actually works.

```suggestion
* The struct ``net_linkaddr_storage`` has been renamed to struct
```

**Review by pdgendt — COMMENTED** [review]
Small comment, otherwise LGTM

File: doc/releases/migration-guide-4.2.rst (hunk 6 above)
Comment (jukkar) [reply doc/releases/migration-guide-4.2.rst:136]: Good point, will fix that.

**Comment by jukkar** [comment]
* Updated the text in migration guide

**Review by pdgendt — APPROVED** [review]

**Review by maass-hamburg — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
