### PR TITLE
eswifi dns resolving fixes

### LINKED ISSUE #27931: Address resolving when eswifi is used causes MPU FAULT
**Describe the bug**
NULL pointer dereference exists in `socket_offload_getaddrinfo` when `eswifi` is used and DNS resolver is enabled.
`dns_offload` is NULL because `socket_offload_dns_register` isn't called in `eswifi` driver.
`NET_SOCKETS_OFFLOAD` has been enabled by default in d8e63e716153e398fea2a16bffa81c48851eb860.

**To Reproduce**
With eswifi modem:
Enable `CONFIG_DNS_RESOLVER` and try to resolve address, for example by running `sntp_simple()` (with `CONFIG_SNTP` enabled).

**Expected behavior**
Address should be resolved successfully.

**Impact**
Crash. Applications using DNS resolver don't work anymore.

**Logs and console output**
```
[00:00:04.668,000] <err> os: ***** MPU FAULT *****
[00:00:04.668,000] <err> os:   Instruction Access Violation
[00:00:04.668,000] <err> os: r0/a1:  0x080224e5  r1/a2:  0x080227c5  r2/a3:  0x20002ef4
[00:00:04.668,000] <err> os: r3/a4:  0x2000b4b0 r12/ip:  0x2000b558 r14/lr:  0x080174d3
[00:00:04.668,000] <err> os:  xpsr:  0x000b0000
[00:00:04.668,000] <err> os: Faulting instruction address (r15/pc): 0x2000b558
[00:00:04.668,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:04.668,000] <err> os: Current thread: 0x20002d68 (unknown)
[00:00:04.725,000] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubunt 20.04
 - Toolchain: Zephyr SDK
 - Commit SHA: c2122313c3ff89b7d939941db618dab650b1f9c3

### PR DESCRIPTION
**Pull request by loicpoulain**
Fixes for #27931

### CODE REVIEW

File: drivers/wifi/eswifi/eswifi_socket_offload.c [hunk 1]
```diff
@@ -575,8 +575,102 @@ NET_SOCKET_REGISTER(eswifi, AF_UNSPEC, eswifi_socket_is_supported,
...
+	/* Allocate out res (addrinfo) struct.	Just one. */
+	*res = calloc(1, sizeof(struct zsock_addrinfo));
+	ai = *res;
+	if (!ai) {
+		err = EAI_MEMORY;
+		goto done_unlock;
+	}
+
+	/* Now, alloc the embedded sockaddr struct: */
+	ai_addr = calloc(1, sizeof(struct sockaddr));
```
Comment (jukkar) [inline drivers/wifi/eswifi/eswifi_socket_offload.c:626]: You should never instantiate `struct sockaddr` type variables as they might not have enough space for all the IPv[4|6] fields. So depending on the type of the address, you should instead create `struct sockaddr_in` or `struct sockaddr_in6` variable and then do a cast of `struct sockaddr` to correct size struct.

Comment (loicpoulain) [reply drivers/wifi/eswifi/eswifi_socket_offload.c]: Indeed, fixed now.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by tbursztyka — APPROVED** [review]
