### PR TITLE
Bugfix/98281 drivers flash common failed test

### LINKED ISSUE #98281: tests: tests/drivers/flash/common: frdm_mcxw23/mcxw236: failed: Unknown Error
**Describe the bug**
below case are failed
drivers.flash.common.test_storage_partition.flash_driver.flash_copy

test is failed on v4.3.0-rc1 on frdm_mcxw23/mcxw236
testcase path is tests/drivers/flash/common

see logs for details

**To Reproduce**
1. 
```
scripts/twister -p frdm_mcxw23/mcxw236  -T tests/drivers/flash/common -s tests/drivers/flash/common
```
or
```
# west twister -p frdm_mcxw23/mcxw236 -T tests/drivers/flash/common --sub-test tests/drivers/flash/common
```
2. See error

```
Unknown Error
```

**Expected behavior**
test pass

**Impact**

**Logs and console output**

```

    
```

```
?pJ&F!@*** Booting Zephyr OS build v4.3.0-rc1 ***
Running TESTSUITE flash_driver
===================================================================
START - test_flash_copy
Test will run on device flash-controller@34000
E: ***** BUS FAULT *****
E:   Precise data bus error
E:   BFAR Address: 0x40015400
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x40015000
E: r3/a4:  0x000fe000 r12/ip:  0x13009aaf r14/lr:  0x00002c37
E:  xpsr:  0x81000000
E: Faulting instruction address (r15/pc): 0x00002bbe
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20004050 (test_flash_copy)
E: Halting system


```

**Environment (please complete the following information):**
 - OS: (e.g. Linux ): Linux
 - Toolchain (e.g Zephyr SDK): zephyr
 - Commit SHA or Version used: v4.3.0-rc1
     
this is never pass since flash enabled

### PR DESCRIPTION
**Pull request by AllenZhang-NXP**
1. Added clear_flash_caches function for MCXW2XX in drivers/flash/soc_flash_mcux.c.
MCXW2XX ROMAPI provide the function FLASH_CacheClear to clear the cache.
The SMSCM is not supported on MCXW2XX platform.

2. Add clock enablement for flash controller.
kCLOCK_Sysctl must be enabled for FLASH_CacheClear,
FLASH_CacheSpeculationControl and FLASH_CheckECC to have an effect.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/98281

### CODE REVIEW

**Comment by hakehuang** [comment]
board test PASS.
```
2025-10-29 05:41:47,884 - twister - DEBUG - DEVICE: $ *** Booting Zephyr OS build v4.3.0-rc1-26-gd532584034f0 ***
2025-10-29 05:41:47,885 - twister - DEBUG - DEVICE: Running TESTSUITE flash_driver
2025-10-29 05:41:47,890 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:47,892 - twister - DEBUG - DEVICE: START - test_flash_copy
2025-10-29 05:41:47,897 - twister - DEBUG - DEVICE: Test will run on device flash-controller@34000
2025-10-29 05:41:48,045 - twister - DEBUG - DEVICE: PASS - test_flash_copy in 0.148 seconds
2025-10-29 05:41:48,051 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,053 - twister - DEBUG - DEVICE: START - test_flash_erase
2025-10-29 05:41:48,057 - twister - DEBUG - DEVICE: Test will run on device flash-controller@34000
2025-10-29 05:41:48,069 - twister - DEBUG - DEVICE: PASS - test_flash_erase in 0.013 seconds
2025-10-29 05:41:48,075 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,077 - twister - DEBUG - DEVICE: START - test_flash_fill
2025-10-29 05:41:48,081 - twister - DEBUG - DEVICE: Test will run on device flash-controller@34000
2025-10-29 05:41:48,157 - twister - DEBUG - DEVICE: PASS - test_flash_fill in 0.076 seconds
2025-10-29 05:41:48,162 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,165 - twister - DEBUG - DEVICE: START - test_flash_flatten
2025-10-29 05:41:48,169 - twister - DEBUG - DEVICE: Test will run on device flash-controller@34000
2025-10-29 05:41:48,246 - twister - DEBUG - DEVICE: PASS - test_flash_flatten in 0.077 seconds
2025-10-29 05:41:48,252 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,254 - twister - DEBUG - DEVICE: START - test_flash_page_layout
2025-10-29 05:41:48,259 - twister - DEBUG - DEVICE: Test will run on device flash-controller@34000
2025-10-29 05:41:48,264 - twister - DEBUG - DEVICE: start_offset=0xf0000        size=8192       index=120
2025-10-29 05:41:48,265 - twister - DEBUG - DEVICE: page_count=127
2025-10-29 05:41:48,270 - twister - DEBUG - DEVICE: PASS - test_flash_page_layout in 0.012 seconds
2025-10-29 05:41:48,276 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,278 - twister - DEBUG - DEVICE: START - test_get_size
2025-10-29 05:41:48,282 - twister - DEBUG - DEVICE: Test will run on device flash-controller@34000
2025-10-29 05:41:48,286 - twister - DEBUG - DEVICE: SKIP - test_get_size in 0.005 seconds
2025-10-29 05:41:48,292 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,295 - twister - DEBUG - DEVICE: START - test_read_unaligned_address
2025-10-29 05:41:48,299 - twister - DEBUG - DEVICE: Test will run on device flash-controller@34000
2025-10-29 05:41:48,317 - twister - DEBUG - DEVICE: PASS - test_read_unaligned_address in 0.018 seconds
2025-10-29 05:41:48,322 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,325 - twister - DEBUG - DEVICE: START - test_supply_gpios_control
2025-10-29 05:41:48,330 - twister - DEBUG - DEVICE: Test will run on device flash-controller@34000
2025-10-29 05:41:48,336 - twister - DEBUG - DEVICE: SKIP - test_supply_gpios_control in 0.006 seconds
2025-10-29 05:41:48,342 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,345 - twister - DEBUG - DEVICE: TESTSUITE flash_driver succeeded
2025-10-29 05:41:48,348 - twister - DEBUG - DEVICE: ------ TESTSUITE SUMMARY START ------
2025-10-29 05:41:48,357 - twister - DEBUG - DEVICE: SUITE PASS - 100.00% [flash_driver]: pass = 6, fail = 0, skip = 2, total = 8 duration = 0.355 seconds
2025-10-29 05:41:48,363 - twister - DEBUG - DEVICE: - PASS - [flash_driver.test_flash_copy] duration = 0.148 seconds
2025-10-29 05:41:48,369 - twister - DEBUG - DEVICE: - PASS - [flash_driver.test_flash_erase] duration = 0.013 seconds
2025-10-29 05:41:48,374 - twister - DEBUG - DEVICE: - PASS - [flash_driver.test_flash_fill] duration = 0.076 seconds
2025-10-29 05:41:48,380 - twister - DEBUG - DEVICE: - PASS - [flash_driver.test_flash_flatten] duration = 0.077 seconds
2025-10-29 05:41:48,387 - twister - DEBUG - DEVICE: - PASS - [flash_driver.test_flash_page_layout] duration = 0.012 seconds
2025-10-29 05:41:48,392 - twister - DEBUG - DEVICE: - SKIP - [flash_driver.test_get_size] duration = 0.005 seconds
2025-10-29 05:41:48,399 - twister - DEBUG - DEVICE: - PASS - [flash_driver.test_read_unaligned_address] duration = 0.018 seconds
2025-10-29 05:41:48,406 - twister - DEBUG - DEVICE: - SKIP - [flash_driver.test_supply_gpios_control] duration = 0.006 seconds
2025-10-29 05:41:48,409 - twister - DEBUG - DEVICE: ------ TESTSUITE SUMMARY END ------
2025-10-29 05:41:48,415 - twister - DEBUG - DEVICE: ===================================================================
2025-10-29 05:41:48,419 - twister - DEBUG - DEVICE: RunID: 9f7f08cb814599e75a62554caa63510f
2025-10-29 05:41:48,421 - twister - DEBUG - DEVICE: PROJECT EXECUTION SUCCESSFUL

```

**Comment by decsny** [comment]
you need to link this PR to an issue in order to get it merged during this release window

File: drivers/flash/soc_flash_mcux.c [hunk 1]
```diff
@@ -119,6 +119,12 @@ static status_t is_area_readable(uint32_t addr, size_t len)
 
 #define SOC_FLASH_NEED_CLEAR_CACHES 1
 #ifdef CONFIG_SOC_FAMILY_MCXW
+#ifdef CONFIG_SOC_SERIES_MCXW2XX
+static void clear_flash_caches(void)
+{
+	FLASH_CacheClear();
+}
+#elif
```
Comment (mmahadevan108) [inline drivers/flash/soc_flash_mcux.c:127]: Not related to this PR. However we should start seeing how to move SOC specific defines out of the driver.

**Review by mmahadevan108 — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by butok — APPROVED** [review]

File: drivers/flash/soc_flash_mcux.c (hunk 1 above)
Comment (jhedberg) [inline drivers/flash/soc_flash_mcux.c:127]: The above should be `#else` instead of `#elif`, shouldn't it? Looks like this broke CI on main: 
```
zephyr/drivers/flash/CMakeFiles/drivers__flash.dir/soc_flash_mcux.c.obj -c /__w/zephyr/zephyr/drivers/flash/soc_flash_mcux.c
/__w/zephyr/zephyr/drivers/flash/soc_flash_mcux.c:127:6: error: #elif with no expression
  127 | #elif
      |      ^
/__w/zephyr/zephyr/drivers/flash/soc_flash_mcux.c: In function 'flash_mcux_erase':
/__w/zephyr/zephyr/drivers/flash/soc_flash_mcux.c:207:17: error: implicit declaration of function 'clear_flash_caches' [-Werror=implicit-function-declaration]
  207 |                 clear_flash_caches();
      |                 ^~~~~~~~~~~~~~~~~~
```

Could you please come up with a hotfix quickly? Otherwise we have to revert this PR.

Comment (jhedberg) [reply drivers/flash/soc_flash_mcux.c:127]: Two questions that this raises, however: why wasn't this caught by CI in this PR, and why didn't you catch it in your local testing (seems like even a local build test should have caught it)

Comment (AllenZhang-NXP) [reply drivers/flash/soc_flash_mcux.c:127]: Hi @jhedberg , sorry for the trouble, I asked @butok to help to create the PR (I am not able to do the single sign-on in github right now, maybe due to the VPN issue). Thanks @butok for the help.

This is a typo, when I run 'west build -p auto -b frdm_mcxw23 tests/drivers/flash/common', there're no failures reported.
Seems the compiler match the CONFIG_SOC_SERIES_MCXW2XX then the #elif will not be considered
If I run 'west build -p auto -b frdm_mcxw71 tests/drivers/flash/common', then the issue will be reported.
I only build the example for MCXW23 and did not try the other platform.
For CI, I am not sure whether it build this example for other platforms, maybe not.
