### PR TITLE
net: tcp2: Fix llvm issue when printing mss

### LINKED ISSUE #29997: format specifies type 'unsigned short' but the argument has type 'int' error in network stack
**Describe the bug**
Build failure when building with llvm:

```
[ 82%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/connection.c.obj
[ 83%] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/tcp2.c.obj
/home/nashif/Work/zephyrproject/zephyr/subsys/net/ip/tcp2.c:885:2: error: format specifies type 'unsigned short' but the argument has type 'int' [-Werror,-Wformat]
        conn_send_data_dump(conn);
        ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/ip/./tcp2_priv.h:102:3: note: expanded from macro 'conn_send_data_dump'
                conn_mss((_conn)));                                     \
                ^~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/include/net/net_core.h:49:6: note: expanded from macro 'NET_DBG'
                        ##__VA_ARGS__)
```

**To Reproduce**

export ZEPHYR_TOOLCHAIN_VARIANT=llvm
west build -b qemu_x86 tests/net/socket/poll

**Expected behavior**
clean build

### PR DESCRIPTION
**Pull request by jukkar**
llvm uses wrong int type for some reason, force cast to uint16_t

Fixes #29997

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]

**Review by galak — APPROVED** [review]

File: subsys/net/ip/tcp2_priv.h [hunk 1]
```diff
@@ -99,7 +99,7 @@
 		"send_win=%hu, mss=%hu",				\
 		(_conn), net_pkt_get_len((_conn)->send_data),		\
 		conn->unacked_len, conn->send_win,			\
-		conn_mss((_conn)));					\
+		(uint16_t)conn_mss((_conn)));				\
```
Comment (pabigot) [inline subsys/net/ip/tcp2_priv.h:102]: How can llvm be complaining about this?  `conn_mss` produces either a value from `tcp_options::mss` which is `uint16_t`, or a constant that's explicitly cast to `uint16_t`.   Is a preprocessor define causing something to not be what it appears to be?

Within that limit: ideally the code would not be assuming that `uint16_t` is a short.  If the `h` length modifier is to be used, the argument should be cast to `unsigned short`.  Otherwise just use `%u`, it'll work out due to the implicit conversion to `int` (and, if the value actually isn't representable in `uint16_t` the resulting output might show what's going on).

Not blocking, just don't think this has been fully investigated.
