### PR TITLE
drivers: soc_flash_mcux check before reading

### LINKED ISSUE #24429: LPC55S69 flash faults when reading unwritten areas
Unlike nearly all Zephyr-supported devices, the internal flash memory on the LPC55S69 faults instead of returning a pattern (usually 0xFF or 0x00) on unwritten flash.

The drive implements read using `memcpy`, which on this device receives a fault instead of copying the data.

The flash controller is able to perform a read without faulting. It is undetermined whether the flash_read operation should return an error, or just read a pattern like most devices.

This is preventing MCUboot from working on this device, as MCUboot needs to be able to probe the flash to see if an image has been written there. MCUboot uses the flash driver, so making flash_read not fault, but either return an error, or read uninitialized data would be sufficient.

The easiest way to reproduce this is to build `samples/drivers/flash_shell` and read past the end of the programmed image. Most reliably, issue a full flash erase before programming (this depends on the flash tool, for the Segger, the `erase` command is sufficient).
```
uart:~$ flash read 0x40000 16
[00:00:21.801,000] <err> os: ***** BUS FAULT *****
[00:00:21.801,000] <err> os:   Precise data bus error
[00:00:21.801,000] <err> os:   BFAR Address: 0x40000
[00:00:21.801,000] <err> os: r0/a1:  0x30001060  r1/a2:  0x00040000  r2/a3:  0x00000010
[00:00:21.801,000] <err> os: r3/a4:  0x30001060 r12/ip:  0x30000171 r14/lr:  0x10008cc5
[00:00:21.801,000] <err> os:  xpsr:  0x81000200
[00:00:21.801,000] <err> os: Faulting instruction address (r15/pc): 0x100087b6
[00:00:21.801,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:21.801,000] <err> os: Current thread: 0x30000438 (unknown)
[00:00:21.870,000] <err> os: Halting system
```

(the code at 0x10008cc5 is the instruction following the call to `memcpy` within `flash_mcux_read`).

**Expected behavior**
The driver should either return a specific error, or read the uninitialized flash contents.

**Impact**
This prevents porting MCUboot to this target.

### PR DESCRIPTION
**Pull request by agansari**
LPC55xxx SoCs don't allow reading erased areas, the flash memory
controller (FMC) will trigger an ECC error for that area. To prevent
reading unwritten areas the low level FMC command of margin checking is
used, this will fail if the area to be read is not correctly written.

Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>

Fixes #24429

### CODE REVIEW

**Comment by d3zd3z** [comment]
I see both advantages and disadvantages of doing it this way.

- advantage: The read is verified using device parameters to better determine if it was written fully. This improves handling of situations where an untimely powerdown caused written data to be read back correctly at some temperatures, and fail in different conditions.
- disadvantage: This probably makes reading a lot slower.

There is also a controller-based read command, but we were only able to get that to work with ECC off, which kind of defeats the purpose of having the ECC.

I'll give this code a test a little later today.

**Comment by d3zd3z** [comment]
Also, I suspect that read margin check can fail when the data would otherwise be readable. I think ideal would be a read command that reads, with the ecc check, and fails if the ecc fails. Basically what regular read does, but without the bus fault. I'm not sure if the controller actually supports this.

**Comment by d3zd3z** [comment]
I'd say the only thing is that we should document somewhere the new error codes we are returning. The API is just documented as returning a negative error, but it might be nice to document this behavior, for when the next device comes up that does ecc checks on read.

**Comment by d3zd3z** [comment]
In addition, this doesn't make MCUboot work with this device. It is likely possible to make it work, but I need to track down all of the places in mcuboot that assume a read error is a failure.

**Comment by d3zd3z** [comment]
I'm now wondering if it might be better behavior in this driver, to detect the all-erased state, and fill the user's buffer with all 0xFF, and return success. This would at least make this device behave the same as every other flash device.

File: drivers/flash/soc_flash_mcux.c [hunk 1]
```diff
@@ -87,6 +159,12 @@ static int flash_mcux_read(struct device *dev, off_t offset,
 	 */
 	addr = offset + priv->pflash_block_base;
 
+#ifdef CONFIG_CHECK_BEFORE_READING
+	if (is_area_readable(addr, len)) {
+		return -EIO;
```
Comment (d3zd3z) [inline drivers/flash/soc_flash_mcux.c:164]: Above, you return various errors from `is_area_readable`, which this then just always collapses into `-EIO`.

**Review by d3zd3z — CHANGES_REQUESTED** [review]

File: drivers/flash/soc_flash_mcux.c (hunk 1 above)
Comment (agansari) [reply drivers/flash/soc_flash_mcux.c]: you are right, forgot to update the read function

Comment (agansari) [reply drivers/flash/soc_flash_mcux.c]: fixed in new push

**Comment by agansari** [comment]
> I'd say the only thing is that we should document somewhere the new error codes we are returning. The API is just documented as returning a negative error, but it might be nice to document this behavior, for when the next device comes up that does ecc checks on read.

I've added another commit that adds these explanations in flash api, not sure that's okay.

**Comment by agansari** [comment]
> I'm now wondering if it might be better behavior in this driver, to detect the all-erased state, and fill the user's buffer with all 0xFF, and return success. This would at least make this device behave the same as every other flash device.

This can be done, but I'm not sure it's a good ideea, would take some time to do the check and flash at boot time, and having such a feature the cleared memory would get lost whenever there's a full erase.
This sounds more like a workaround, checking before reading is prevention.

**Comment by agansari** [comment]
> I'm now wondering if it might be better behavior in this driver, to detect the all-erased state, and fill the user's buffer with all 0xFF, and return success. This would at least make this device behave the same as every other flash device.

Another workaround would be to fill the data pointer with 0xFF in the read function when the area is empty.

**Comment by d3zd3z** [comment]
> This can be done, but I'm not sure it's a good ideea, would take some time to do the check and flash at boot time, and having such a feature the cleared memory would get lost whenever there's a full erase. This sounds more like a workaround, checking before reading is prevention.

The thing is, this driver now has behavior that is completely different from every other flash device supported on Zephyr. I suspect it isn't just MCUboot that isn't going to easily work with this. In order to be able to use this in MCUboot, I would need to make a wrapper around the flash operations. There is already an API in mcuboot that distinguishes between erased an other data (part of the flash_area api borrowed from MyNewt). Perhaps something like this could be done there as well, which would make this a little more useful.

Ideally, we would be able to distinguish, but I think we're just too divergent from what applications using the flashes in MCUs are typically expecting, including as far as I can tell, every other device built with ECC.

**Comment by agansari** [comment]
@d3zd3z i've made another change to return 0xFF when reading an erased area in order to make it behave like most flash devices.
I prefer this alternative to writing 0xFF when board is initialized and then hide an erase and write actual data.

Would this change make it integrate with MCUboot better?

**Comment by d3zd3z** [comment]
> I prefer this alternative to writing 0xFF when board is initialized and then hide an erase and write actual data.

In general, it is best to try to make the driver match as closely to how the device works. I realize we're not quite doing that by faking out reads. But hiding erases seems even more distant from the device's behavior. Also, we don't necessarily know that this driver is the only thing operating on the flash. For example, in a factory, the initial programming may be done over SWD, and that system probably wouldn't write 0xFF.

I'll try to get around to testing this with MCUboot soon.

**Comment by d3zd3z** [comment]
I've done a little bit of testing, and at least the scanning part seems to work. It still won't actually execute the images, which I still need to investigate.

File: drivers/flash/soc_flash_mcux.c [hunk 2]
```diff
@@ -87,9 +174,21 @@ static int flash_mcux_read(struct device *dev, off_t offset,
...
+	rc = is_area_readable(addr, len);
+#endif
 
-	return 0;
+	if (!rc) {
+		memcpy(data, (void *) addr, len);
+#ifdef CONFIG_CHECK_BEFORE_READING
+	} else if (rc == -ENODATA) {
+		/* Erased area, return dummy data as an erased page. */
+		memset(data, 0xFFFFFFFF, len);
```
Comment (nvlsianpu) [inline drivers/flash/soc_flash_mcux.c:186]:
```suggestion
		memset(data, 0xFF, len);
		
```

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
For me it is hard to judge on implementation of `static uint32_t get_cmd_status(uint32_t cmd, uint32_t addr, size_t len)` function as I don't know targeted hardware (And don't have time to read the spec.)
Despite that rest of this PR looks sane to me.

File: drivers/flash/soc_flash_mcux.c (hunk 2 above)
Comment (agansari) [reply drivers/flash/soc_flash_mcux.c]: thank you @nvlsianpu i've made the changes you suggested

**Review by nvlsianpu — APPROVED** [review]

**Review by d3zd3z — APPROVED** [review]
