### PR TITLE
tests: Change the result compare method in pin_get_config()

### LINKED ISSUE #47921: tests: pin_get_config failed on it8xxx2_evb
**Describe the bug**
Test case tests/drivers/gpio/gpio_basic_api failed in daily test. When setting a GPIO to high, and then get the GPIO result, the result is not as expected.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? it8xxx2_evb
 - What have you tried to diagnose or workaround this issue? Provide PR https://github.com/zephyrproject-rtos/zephyr/pull/47923 to fix it.

**To Reproduce**
1.  twister  -p it8xxx2_evb --device-testing --west-flash="../../itetool/loader.sh" --device-serial=/dev/ttyUSB0 -T tests/drivers/gpio/gpio_basic_api/ -vv -X gpio_loopback

**Expected behavior**
The test can pass

**Impact**
1 test case failed in daily test

**Logs and console output**
```
DEBUG   - DEVICE: START - test_gpio_port
DEBUG   - DEVICE: Validate device GPIO_A
DEBUG   - DEVICE: Check GPIO_A output 0 connected to input 1
DEBUG   - DEVICE: OUT 0 to IN 1 linkage works
DEBUG   - DEVICE: - bits_physical
DEBUG   - DEVICE: - pin_physical
DEBUG   - DEVICE: - check_raw_output_levels
DEBUG   - DEVICE: - check_logic_output_levels
DEBUG   - DEVICE: - check_input_levels
DEBUG   - DEVICE: - bits_logical
DEBUG   - DEVICE: - check_pulls
DEBUG   - DEVICE: @@@ flags_set = a0000
DEBUG   - DEVICE: @@@ flags_get = a1000
DEBUG   - DEVICE:
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:653: pin_get_config: (flags_set not equal to flags_get)
DEBUG   - DEVICE: flags are different
DEBUG   - DEVICE: FAIL - test_gpio_port in 0.54 seconds
```
flags_set means (GPIO_OUTPUT | GPIO_OUTPUT_INIT_HIGH) 
flags_get means (GPIO_OUTPUT | GPIO_OUTPUT_INIT_HIGH) and GPIO_VOLTAGE_3P3

When setting the flags, the voltage infomation is not given, but when get the flags, it8xxx2_evb filled in this information automatically.
So we only need to compare the bit of GPIO_OUTPUT and GPIO_OUTPUT_INIT_HIGH in the test, instead of 
```
zassert_equal(flags_set, flags_get, "flags are different");
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**
Add any other context that could be relevant to your issue, such as pin setting,
target configuration, ...

### PR DESCRIPTION
**Pull request by hunterhu3000**
Fixes #47921
When setting a GPIO to certain value, and then get the GPIO value, on some
platforms, such as ITE, these two values may not be the same. For example
setting GPIO_OUTPUT | GPIO_OUTPUT_INT_HIGH, it will read back
GPIO_OUTPUT | GPIO_OUTPUT_INT_HIGH | GPIO_VOLTAGE_3P3. This is as expected,
as GPIO_VOLTAGE is a read only property. So when comparing the gpio set
and get values, it is necessary to filter the read only bits first and
then compare to the set value.

Signed-off-by: Hu Zhenyu <zhenyu.hu@intel.com>

### CODE REVIEW

**Comment by hunterhu3000** [comment]
This PR is to fix https://github.com/zephyrproject-rtos/zephyr/issues/47921

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Please change the Git commit log to describe the actual changes.

**Comment by FRASTM** [comment]
This fixes the pb as reported by issues https://github.com/zephyrproject-rtos/zephyr/issues/47921 and https://github.com/zephyrproject-rtos/zephyr/issues/48007

In any case the test should also PASS when  `CONFIG_GPIO_GET_CONFIG=n`
--> flag `pin_get_config() `with `#ifdef CONFIG_GPIO_GET_CONFIG`

**Comment by MaureenHelm** [comment]
> This PR is to fix #47921

Please add "Fixes #47921" to the PR description. This will link the Issue and close it automatically when the PR gets merged.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by FRASTM** [comment]
When the function to get the gpio pin config was introduced by the  PR #43225, flags was supposed to give the position of the gpio : in/out GPIO_OPEN_DRAIN/ GPIO_PULL_DOWN/GPIO_PULL_UP
I guess this information should fit the [GPIO input/output configuration flags](https://docs.zephyrproject.org/latest/hardware/peripherals/gpio.html?highlight=gpio_flags_t#overview) 
If the purpose is to know about high or low states only of the gpio, what is the benefit of gpio_stm32_get_config() function when reading the 
```
	otype = LL_GPIO_GetPinOutputType(gpio, pin_ll);
	pupd = LL_GPIO_GetPinPull(gpio, pin_ll);
	mode = LL_GPIO_GetPinMode(gpio, pin_ll);
```

**Comment by mmahadevan108** [comment]
cc @semihalf-barnas-michal

**Comment by semihalf-barnas-michal** [comment]
> If the purpose is to know about high or low states only of the gpio, what is the benefit of gpio_stm32_get_config() function

Exactly, the gpio_get_config should return all (supported) flags set for the gpio, not only input or output. So this PR hides the problem with the stm32 driver instead of fixing it.
There is probably some problem in the implementation of stm32 driver, some flags are missing or are reading invalid enums for specific stm boards.

> In any case the test should also PASS when `CONFIG_GPIO_GET_CONFIG=n`
> suggestion : flag `pin_get_config() `with `#ifdef CONFIG_GPIO_GET_CONFIG`

Or just wrap the whole test with the ifdef. It may be better to not have this test run, when it's not implemented, instead of returning the positive.

**Comment by hunterhu3000** [comment]
> This fixes the pb as reported by issues #47921 and #48007
> 
> In any case the test should also PASS when `CONFIG_GPIO_GET_CONFIG=n` suggestion : flag `pin_get_config() `with `#ifdef CONFIG_GPIO_GET_CONFIG`
OK

**Comment by hunterhu3000** [comment]
> gpio_stm32_get_config

I think the user can use pin_get_config to get more infomation than just the high/low input/output. But some of the infomation is read only and may not be used in gpio_pin_configure. So in the test, it is enough to check the high/low input/output.

**Comment by hunterhu3000** [comment]
> > If the purpose is to know about high or low states only of the gpio, what is the benefit of gpio_stm32_get_config() function
> 
> Exactly, the gpio_get_config should return all (supported) flags set for the gpio, not only input or output. So this PR hides the problem with the stm32 driver instead of fixing it. There is probably some problem in the implementation of stm32 driver, some flags are missing or are reading invalid enums for specific stm boards.
> 
> > In any case the test should also PASS when `CONFIG_GPIO_GET_CONFIG=n`
> > suggestion : flag `pin_get_config() `with `#ifdef CONFIG_GPIO_GET_CONFIG`
> 
> Or just wrap the whole test with the ifdef. It may be better to not have this test run, when it's not implemented, instead of returning the positive.

I think #48007 is another issue. This PR will not fix it, as the set value of #48007 is 0xa0000 but the get value is 0x20000b74. 0xa0000 & 0x20000b74 is 0, so the assertion in this PR cannot pass. For #48007, we need to check gpio_stm32_get_config(), it seems does not follow the zephyr definition

**Comment by semihalf-barnas-michal** [comment]
> I think #48007 is another issue

Yes, there seems to be a bug in the driver implementation. Both issues are connected to my PR, but definitely different root cause.

**Comment by semihalf-barnas-michal** [comment]
> I will modify my patch to avoid this case

Thanks

**Comment by semihalf-barnas-michal** [comment]
That looks great

**Review by cfriedt — DISMISSED** [review]
LGTM

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c [hunk 1]
```diff
@@ -633,11 +633,17 @@ static int bits_logical(void)
 
 /* gpio_pin_get_config()
  */
+#ifdef CONFIG_GPIO_GET_CONFIG
```
Comment (FRASTM) [inline tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:636]: Better include the comment line in the 
#ifdef CONFIG_GPIO_GET_CONFIG

**Review by FRASTM — COMMENTED** [review]
else LGTM

**Comment by mmahadevan108** [comment]
> > This PR is to fix #47921
> 
> Please add "Fixes #47921" to the PR description. This will link the Issue and close it automatically when the PR gets merged. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

@hunterhu3000 as suggested earlier please add `Fixes #47921` to the description. This will then automatically close the issue when this PR gets merged.

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c [hunk 2]
```diff
@@ -633,11 +633,17 @@ static int bits_logical(void)
...
 static int pin_get_config(void)
 {
 	gpio_flags_t flags_get = 0;
 	gpio_flags_t flags_set;
 	int rc;
+	gpio_flags_t flags_mask = GPIO_INT_MASK | GPIO_OUTPUT_INIT_LOGICAL |
+				  GPIO_OUTPUT_INIT_HIGH | GPIO_OUTPUT_INIT_LOW |
+				  GPIO_OUTPUT | GPIO_INPUT |
+				  GPIO_PULL_UP | GPIO_PULL_DOWN |
+				  GPIO_SINGLE_ENDED | GPIO_LINE_OPEN_DRAIN | GPIO_ACTIVE_LOW;
```
Comment (henrikbrixandersen) [inline tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:646]: So the idea is to mask out SoC-specific GPIO flags? Why not just use `GENMASK` to generate a bit mask excluding those? The above would need to be updated every time we add a new flag?

```
/**
 * @brief Provides a type to hold GPIO devicetree flags.
 *
 * All GPIO flags that can be expressed in devicetree fit in the low 16
 * bits of the full flags field, so use a reduced-size type to record
 * that part of a GPIOS property.
 *
 * The lower 8 bits are used for standard flags. The upper 8 bits are reserved
 * for SoC specific flags.
 */
typedef uint16_t gpio_dt_flags_t;

/**
 * @brief Provides a type to hold GPIO configuration flags.
 *
 * This type is sufficient to hold all flags used to control GPIO
 * configuration, whether pin or interrupt.
 */
typedef uint32_t gpio_flags_t;

```

Comment (semihalf-barnas-michal) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:646]: > So the idea is to mask out SoC-specific GPIO flags?

In this case the problem was with voltage flags from device-tree. If you don't specify any voltage (so flag is GPIO_VOLTAGE_DEFAULT), you can read a real voltage from board registers (GPIO_VOLTAGE_3P3).

Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c]: OK, use GENMASK

**Comment by hunterhu3000** [comment]
@henrikbrixandersen Could you please review my latest patch? If if is OK, thanks to +1.

**Review by cfriedt — CHANGES_REQUESTED** [review]

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c [hunk 3]
```diff
@@ -672,6 +683,8 @@ void test_gpio_port(void)
 		      "bits_logical failed");
 	zassert_equal(check_pulls(), TC_PASS,
 		      "check_pulls failed");
+#ifdef CONFIG_GPIO_GET_CONFIG
```
[the remark this answers is not in the document]
Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c]: Updated. Thanks to review

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c [hunk 4]
```diff
@@ -672,6 +683,7 @@ void test_gpio_port(void)
 		      "bits_logical failed");
 	zassert_equal(check_pulls(), TC_PASS,
 		      "check_pulls failed");
-	zassert_equal(pin_get_config(), TC_PASS,
-		      "pin_get_config failed");
+	if (IS_ENABLED(CONFIG_GPIO_GET_CONFIG))
+		zassert_equal(pin_get_config(), TC_PASS,
```
Comment (FRASTM) [inline tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:687]: In case of CONFIG_GPIO_GET_CONFIG=n, the pin_get_config might definitively be not supported in the driver, then giving compilation warning --> function is undeclared 
This is not exactly the same as 
```
#ifdef CONFIG_GPIO_GET_CONFIG
 	zassert_equal(pin_get_config(), TC_PASS,
 		      "pin_get_config failed");
#endif /* CONFIG_GPIO_GET_CONFIG */
```

Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:687]: Yes, we'd better to roll back

Comment (cfriedt) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:687]: Should be `IS_ENABLED(..) && api->get_config != NULL`

**Comment by FRASTM** [comment]
BTW if you could please include the change in the [tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c](https://github.com/zephyrproject-rtos/zephyr/pull/48159/commits/717e6d26f7d57264def8fe67a956b864bd3e7735#diff-0cf45b2fd058a429827c4bfe9c9602d63aa2cce9b39e3779a8bfb354ba08e331)
to handle the correct error code from the gpio_pin_get_config return
```
rc = gpio_pin_get_config(dev, PIN_OUT, &flags_get);
	if (rc == -ENOSYS) {
		return TC_PASS;
	}
```

**Comment by hunterhu3000** [comment]
> BTW if you could please include the change in the [tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c](https://github.com/zephyrproject-rtos/zephyr/pull/48159/commits/717e6d26f7d57264def8fe67a956b864bd3e7735#diff-0cf45b2fd058a429827c4bfe9c9602d63aa2cce9b39e3779a8bfb354ba08e331) to handle the correct error code from the gpio_pin_get_config return
> 
> ```
> rc = gpio_pin_get_config(dev, PIN_OUT, &flags_get);
> 	if (rc == -ENOSYS) {
> 		return TC_PASS;
> 	}
> ```

I have another question, why ENOSYS is regarded as PASS？

**Comment by FRASTM** [comment]
> > BTW if you could please include the change in the [tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c](https://github.com/zephyrproject-rtos/zephyr/pull/48159/commits/717e6d26f7d57264def8fe67a956b864bd3e7735#diff-0cf45b2fd058a429827c4bfe9c9602d63aa2cce9b39e3779a8bfb354ba08e331) to handle the correct error code from the gpio_pin_get_config return
> > ```
> > rc = gpio_pin_get_config(dev, PIN_OUT, &flags_get);
> > 	if (rc == -ENOSYS) {
> > 		return TC_PASS;
> > 	}
> > ```
> 
> I have another question, why ENOSYS is regarded as PASS？

The reason for this is in the [gpio_pin_get_config](https://docs.zephyrproject.org/latest/doxygen/html/group__gpio__interface.html#ga133284b60a13c6dc50b87c1d04259f5e)
 The gpio_pin_get_config()  [zephyr/include/zephyr/drivers/gpio.h](https://github.com/zephyrproject-rtos/zephyr/blob/352fde1271c568fa24cb48b4aed20f97b25945b1/include/zephyr/drivers/gpio.h#L881-L883) return code is _not_ ENOTSUP 
```
	if (api->pin_get_config == NULL)
		return -ENOSYS;
```

**Comment by hunterhu3000** [comment]
If getting current pin configuration is not implemented by the driver, then we should not run this test. Returning fail will remind us there might be a  problem or not running the test next time if it is as expected, while returning pass will cover the problem. @FRASTM

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c [hunk 5]
```diff
@@ -633,27 +633,35 @@ static int bits_logical(void)
...
+	 * GPIO_ACTIVE_LOW/HIGH		bit 0
+	 */
+	gpio_flags_t flags_mask = GENMASK(26, 16) | GENMASK(5, 4) | GENMASK(2, 0);
+
 	flags_set = GPIO_OUTPUT_HIGH;
 	rc = gpio_pin_configure(dev, PIN_OUT, flags_set);
 	zassert_equal(rc, 0, "pin configure failed");
 
 	rc = gpio_pin_get_config(dev, PIN_OUT, &flags_get);
-	if (rc == -ENOTSUP) {
```
Comment (cfriedt) [inline tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:647]: This should probably be kept. The reason is that there could be multiple GPIO drivers and one of them might support this feature, while the other does not.

That's the main reason why I kept the `gpio_get_direction()` tests in a separate suite.

**Review by cfriedt — CHANGES_REQUESTED** [review]
Sorry to ask for another rev. Please see my comment above.

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c (hunk 5 above)
Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:647]: Only one GPIO driver gpio_stm32_get_config() will return ENOTSUP. When the runtime pm is not defined, the function will return ENOTSUP, and the gpio_pin_configure will not be performed. To my understanding, at this time, the test case should be regarded as TC_FAIL. Do you agree?

**Comment by hunterhu3000** [comment]
Rebased to the latest. Thanks to review

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c (hunk 5 above)
Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c]: This part is modified in https://github.com/zephyrproject-rtos/zephyr/pull/48159/files. So in this PR, I will not touch this.

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c (hunk 4 above)
Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:686]: > pin_get_config
Updated. It seems the CONFIG_GPIO_GET_CONFIG for the function pin_get_config should be remove as well

**Comment by hunterhu3000** [comment]
As there is a long history of this PR, I'd like to summarize it below:
1. henrikbrixandersen/MaureenHelm/mmahadevan108 asked to change the commit log -> done
2. FRASTM think this PR can fix #48007, but they are two different problems. #48077 is fixed by #48159 later.
3. semihalf-barnas-michal pointed out that the patch cannot cover the corner case such as 0xFFFFFFFF -> fixed
4. semihalf-barnas-michal to add "#ifdef CONFIG_GPIO_GET_CONFIG" -> done
5. henrikbrixandersen asked to use GENMASK instead of OR -> done
6. cfriedt asked to use "if (IS_ENABLED(CONFIG_..))" instead of "#ifdef CONFIG_GPIO_GET_CONFIG" -> done
7. FRASTM asked to chaged the ENOTSUP to ENOSYS -> cfriedt disagree this. So nothing is done on this PR. The modification was done in #48159

**Comment by hunterhu3000** [comment]
@mnkp @FRASTM @MaureenHelm @henrikbrixandersen @cfriedt @semihalf-barnas-michal 
Could you please help to review and +1? Thanks.

**Review by FRASTM — DISMISSED** [review]

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c [hunk 6]
```diff
@@ -639,6 +639,16 @@ static int pin_get_config(void)
...
 
+	/* GPIO_INT_MASK		bit 26-21
+	 * GPIO_OUTPUT_INIT_HIGH, LOW	bit 19, 18
+	 * GPIO_OUTPUT, GPIO_INPUT	bit 17, 16
+	 * GPIO_PULL_DOWN, GPIO_PULL_UP	bit 5, 4
+	 * GPIO_LINE_OPEN_DRAIN/SOURCE	bit 2
+	 * GPIO_SINGLE_ENDED/PUSH_PULL	bit 1
+	 * GPIO_ACTIVE_LOW/HIGH		bit 0
+	 */
+	gpio_flags_t flags_mask = GENMASK(26, 16) | GENMASK(5, 4) | GENMASK(2, 0);
```
[the remark this answers is not in the document]
Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:650]: These values cannot be used directly, as they are bits, not direct values, eg.
#define GPIO_INT_HIGH_1       (1U << 26)
#define GPIO_PULL_UP            (1 << 4)

[the remark this answers is not in the document]
Comment (henrikbrixandersen) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:650]: Isn't the purpose to exclude all vendor/SoC specific flags? How about just `GENMASK(31, 16) | GENMASK(7, 0)`?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (cfriedt) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:650]: Alternatively, just explicitly define macros used in the variable by or'ing them all together. I'm sure that was the first rev. I agree with what Brix says as well though, this should only include non-vendor-specific flags.

[the remark this answers is not in the document]
Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:650]: The bits in the flags is discontinuous，eg bit 26~31 is not defined and maybe used some day in the future. If we use GENMASK(31,16), this test case may fail some day, if bit 31 is defined as a read only property.
```
#define GPIO_ACTIVE_LOW         (1 << 0)
#define GPIO_ACTIVE_HIGH        (0 << 0)
#define GPIO_SINGLE_ENDED       (1 << 1)
#define GPIO_PUSH_PULL          (0 << 1)
#define GPIO_LINE_OPEN_DRAIN    (1 << 2)
#define GPIO_LINE_OPEN_SOURCE   (0 << 2)
#define GPIO_PULL_UP            (1 << 4)
#define GPIO_PULL_DOWN          (1 << 5)

#define GPIO_VOLTAGE_POS        11
#define GPIO_VOLTAGE_MASK       (3U << GPIO_VOLTAGE_POS)
#define GPIO_VOLTAGE_DEFAULT    (0U << GPIO_VOLTAGE_POS)
#define GPIO_VOLTAGE_1P8        (1U << GPIO_VOLTAGE_POS)
#define GPIO_VOLTAGE_3P3        (2U << GPIO_VOLTAGE_POS)
#define GPIO_VOLTAGE_5P0        (3U << GPIO_VOLTAGE_POS)

#define GPIO_INPUT              (1U << 16)
#define GPIO_OUTPUT             (1U << 17)
#define GPIO_OUTPUT_INIT_LOW    (1U << 18)
#define GPIO_OUTPUT_INIT_HIGH   (1U << 19)
#define GPIO_OUTPUT_INIT_LOGICAL (1U << 20)

#define GPIO_INT_DISABLE               (1U << 21)
#define GPIO_INT_ENABLE                (1U << 22)
#define GPIO_INT_LEVELS_LOGICAL        (1U << 23)
#define GPIO_INT_EDGE                  (1U << 24)
#define GPIO_INT_LOW_0                 (1U << 25)
#define GPIO_INT_HIGH_1                (1U << 26)
```
I agree it is not good to use the magic numbers. If so we need to double he macro numbers and define like this:
```
#define GPIO_ACTIVE_SHIFT       0
#define GPIO_PULL_UP_SHIFT     4
GENMASK(GPIO_INT_HIGH_1_SHIFT, GPIO_INPUT_SHIFT)
```
I think it is also not friendly to the code reader. As the reader still does not know what is between GPIO_INT_HIGH_1_SHIFT and GPIO_INPUT_SHIFT.
Maybe using the first version(bit or, not the GENMASK) is better.

[the remark this answers is not in the document]
Comment (cfriedt) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c]: I like that GPIO_VOLTAGE_MASK exists. Couldn't we just do something similar for padconf, Input-Output, and int

[the remark this answers is not in the document]
Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c]: I have uploaded a new version, is that what you mean?

[the remark this answers is not in the document]
Comment (hunterhu3000) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c]: @cfriedt could you please help to review this patch? Thanks

**Review by cfriedt — APPROVED** [review]

**Comment by hunterhu3000** [comment]
@henrikbrixandersen Could you please review and +1 so that the PR can be merged to the mainline earlier, thanks.

**Review by FRASTM — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
