### PR TITLE
arch: arm64: fix crash on SMP secondary CPUs when PAC is enabled

### LINKED ISSUE #106723: arm64: SMP secondary CPUs crash with FPAC exception when PAC is enabled
Secondary CPUs crash with an FPAC (Pointer Authentication failure) exception
during boot when CONFIG_ARM_PAC is enabled on SMP configurations.

The crash occurs in arch_secondary_cpu_init() which is declared FUNC_NORETURN
in its extern declaration but lacks the attribute on the definition. The compiler
generates a PACIASP/AUTIASP pair and the AUTIASP fails on secondary CPUs.

Reproducible on fvp_base_revc_2xaem/v9a/smp and fvp_corstone1000/a320/smp
with the arch.arm64.pacbti test.

Fix: #106722

### PR DESCRIPTION
**Pull request by npitre**
Secondary CPUs crash with an FPAC (Pointer Authentication failure) exception
during boot when CONFIG_ARM_PAC is enabled on SMP configurations.

arch_secondary_cpu_init() never returns but its definition lacks
FUNC_NORETURN. The compiler generates a PACIASP/AUTIASP pair and
turns the final fn(arg) into a tail-call (AUTIASP + BR). The
AUTIASP causes the PAC authentication failure.

This fix marks the definition FUNC_NORETURN with CODE_UNREACHABLE,
matching the extern declaration. The compiler then generates a plain BLR
without the AUTIASP epilogue.

Also removes a dead arch_cache_init() call that was placed after the
noreturn call in z_arm64_secondary_prep_c().

Fixes #106723

### CODE REVIEW

File: arch/arm64/core/smp.c [hunk 1]
```diff
@@ -137,7 +137,7 @@ void arch_cpu_start(int cpu_num, k_thread_stack_t *stack, int sz,
 }
 
 /* the C entry of secondary cores */
-void arch_secondary_cpu_init(int cpu_num)
+FUNC_NORETURN void arch_secondary_cpu_init(int cpu_num)
```
Comment (JiafeiPan) [inline arch/arm64/core/smp.c]: Maybe we could define it to be

```suggestion
FUNC_NORETURN void arch_secondary_cpu_init(void)
{
    int cpu_num = arm64_cpu_boot_params.cpu_num;
```
as it is called at [here](https://github.com/zephyrproject-rtos/zephyr/pull/106722/changes#diff-b21b7616af8e0a88d0db9abcd4395f219a8999798eb1bfbf8a13a5009c7f294cR60) without any parameter

**Review by JiafeiPan — CHANGES_REQUESTED** [review]

File: arch/arm64/core/smp.c (hunk 1 above)
Comment (npitre) [reply arch/arm64/core/smp.c]: Done. Also moved the declaration into boot.h along with z_arm64_mm_init() to consolidate the scattered extern declarations.

**Review by JiafeiPan — APPROVED** [review]

**Review by wearyzen — APPROVED** [review]
