### PR TITLE
drivers: video: fix uninitialized struct in ov9655_init()

### LINKED ISSUE #91243: [Coverity CID: 525180] Uninitialized scalar variable in drivers/video/ov9655.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/fd6b05c81b86a1ffe465d56ded7b73a9fdb7f14b/drivers/video/ov9655.c

Category: Uninitialized variables
Function: `ov9655_init`
Component: Drivers
CID: [525180](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=525180)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/fd6b05c81b86a1ffe465d56ded7b73a9fdb7f14b/drivers/video/ov9655.c#L388

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=525180

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNINIT). ([CWE-457](http://cwe.mitre.org/data/definitions/457.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by sudarsan-22**
Zero-initialize fmt to fix Coverity CID 525180.

CID: 525180

### CODE REVIEW

**Comment by avolmat-st** [comment]
Thank you for your patch. Could you clarify what is reported by Coverity concerning this fmt variable ?

Having a look at it, I think that it could actually be set to something like 
fmt = {
   . pixelformat = ...,
   .width = ...
   .height = ....
 }
 and remove the default setting at the end of the ov9655_init function since this is const anyway.
 
 What do you think ?

**Comment by sudarsan-22** [comment]
> Thank you for your patch. Could you clarify what is reported by Coverity concerning this fmt variable ?
> 
> Having a look at it, I think that it could actually be set to something like fmt = { . pixelformat = ..., .width = ... .height = .... } and remove the default setting at the end of the ov9655_init function since this is const anyway.
> 
> What do you think ?

Coverity flagged fmt as potentially uninitialized (CID 525180). You're right — using a designated initializer is cleaner. I’ll update the patch accordingly and remove the redundant assignments.
risk passing garbage values for .type and .pitch

**Comment by ngphibang** [comment]
I think the best fix is as proposed by @avolmat-st , otherwise I think we could choose to not fix as fmt's fields are anyway already initialized (this is kind of false alarm or low priority of coverity).

There are other CIDs seems falling within the same category, it is best if you could do all in the same PR (or same commit) ?

https://github.com/zephyrproject-rtos/zephyr/issues/90488#event-18043423548
https://github.com/zephyrproject-rtos/zephyr/issues/90495#event-18043423466
https://github.com/zephyrproject-rtos/zephyr/issues/90471#issuecomment-2954315078
https://github.com/zephyrproject-rtos/zephyr/issues/90493#event-18079186685

Thank you !

**Comment by sudarsan-22** [comment]
Gentle Remainder

**Comment by ngphibang** [comment]
@sudarsan-22 It seems you forgot to push new changes since then ?

**Comment by sudarsan-22** [comment]
> @sudarsan-22 It seems you forgot to push new changes since then ?

Pushed the Coverity fixes now, please take a look. Thanks!

**Review by josuah — DISMISSED** [review]
I think @ngphibang pointed at this change you planned to make:

> using a designated initializer is cleaner. I’ll update the patch accordingly and remove the redundant assignments
> -- https://github.com/zephyrproject-rtos/zephyr/pull/91403#issuecomment-2961671616

But batch-setting `fmt = {0}` seems like a viable solution too!

**Comment by avolmat-st** [comment]
> > Thank you for your patch. Could you clarify what is reported by Coverity concerning this fmt variable ?
> > Having a look at it, I think that it could actually be set to something like fmt = { . pixelformat = ..., .width = ... .height = .... } and remove the default setting at the end of the ov9655_init function since this is const anyway.
> > What do you think ?
> 
> Coverity flagged fmt as potentially uninitialized (CID 525180). You're right — using a designated initializer is cleaner. I’ll update the patch accordingly and remove the redundant assignments. risk passing garbage values for .type and .pitch

Finally latest patch is simply setting it to { 0 } right ? I kind of understood from your reply that you'd update the code to set directly the pixelformat , width, height, buf type to avoid setting the fmt twice. Did I misunderstood ?

At least for ov9655.c, I'd prefer fixing it as:

struct video_format fmt = {
    .type = VIDEO_BUF_TYPE_OUTPUT,
    .pixelformat = VIDEO_PIX_FMT_YUYV,
    .width = 160,
    .height = 120,
};

pitch should be kept to 0 since this field is set by the receiver, not the sensor.

**Review by avolmat-st — CHANGES_REQUESTED** [review]
Could you fix the init of the ov9655.c ?

**Comment by sudarsan-22** [comment]
> Could you fix the init of the ov9655.c ?

yes, i make it as a zero

**Comment by ngphibang** [comment]
It seems there are some thing misunderstood here. I think @avolmat-st means, the fix should be 

```
struct video_format fmt = {
    .pixelformat = VIDEO_PIX_FMT_YUYV or RGB565 depending on sensors
    .width = X,
    .height = Y,
};
```
instead of 

`struct video_format fmt = {0};` as being done.

The advantage of this is we can do it in one go and we don't set the field that should not be set like `.pitch`

**Comment by sudarsan-22** [comment]
> It seems there are some thing misunderstood here. I think @avolmat-st means, the fix should be
> 
> ```
> struct video_format fmt = {
>     .type = VIDEO_BUF_TYPE_OUTPUT,
>     .pixelformat = VIDEO_PIX_FMT_YUYV or RGB565 depending on sensors
>     .width = X,
>     .height = Y,
> };
> ```
> 
> instead of
> 
> `struct video_format fmt = {0};` as being done.
> 
> The advantage of this is we can do it in one go and we don't set the field that should not be set like `.pitch`

@ngphibang  Thanks for the clarification! In this case, some of the struct members are conditionally set based on runtime checks (e.g., resolution selection via ov5640_is_dvp()), so initializing with { 0 } makes it clearer and avoids redundant assignments. I agree it's more readable and leaves room for future extensions without touching the later logic.

**Comment by avolmat-st** [comment]
> > It seems there are some thing misunderstood here. I think @avolmat-st means, the fix should be
> > ```
> > struct video_format fmt = {
> >     .type = VIDEO_BUF_TYPE_OUTPUT,
> >     .pixelformat = VIDEO_PIX_FMT_YUYV or RGB565 depending on sensors
> >     .width = X,
> >     .height = Y,
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > instead of
> > `struct video_format fmt = {0};` as being done.
> > The advantage of this is we can do it in one go and we don't set the field that should not be set like `.pitch`
> 
> @ngphibang Thanks for the clarification! In this case, some of the struct members are conditionally set based on runtime checks (e.g., resolution selection via ov5640_is_dvp()), so initializing with { 0 } makes it clearer and avoids redundant assignments. I agree it's more readable and leaves room for future extensions without touching the later logic.

As far as I am concerned, I am only talking about the ov9655 here. Not all drivers.

The ov9655_init function is basically doing the following stuff:
1. declare a struct video_fmt structure
2. do various stuff, unrelated to this struct video_fmt
3. assign 3 fields within the struct video_fmt (pixelformat, width, height)
4. call the video_set_fmt function using that struct video_fmt structure declared at step 1.

So, nothing is happening between 1. and 3. related to struct video_fmt so what is the merit to first initialize it to {0} at step 1 if we change it again at step 3. Our proposal is thus to initialize it at step 1 straight with proper values pixelformat, width, height and thus get rid of step 3.

So something like this:
```
static int ov9655_init(const struct device *dev)
{
        const struct ov9655_config *config = dev->config;
        /* Set default camera format (QQVGA, YUYV) */
        struct video_format fmt; = {
              .pixelformat = VIDEO_PIX_FMT_YUYV,
              .width = 160,
              .height = 120;
       };
        uint32_t pid;
        int ret;

       (...)

       return ov9655_set_fmt(dev, &fmt);
}
```

and remove the block

```
        /* Set default camera format (QQVGA, YUYV) */
        fmt.pixelformat = VIDEO_PIX_FMT_YUYV;
        fmt.width = 160;
        fmt.height = 120;
```
which is right before the 
```
       return ov9655_set_fmt(dev, &fmt);
}
```

**Comment by ngphibang** [comment]
> resolution selection via ov5640_is_dvp())

Except the ov5640, other drivers could be done I think.

```
        struct video_format fmt; = {
              .pixelformat = ,
              .width = ,
              .height = ;
       };
```

**Comment by sudarsan-22** [comment]
> > resolution selection via ov5640_is_dvp())
> 
> Except the ov5640, other drivers could be done I think.
> 
> ```
>         struct video_format fmt; = {
>               .pixelformat = ,
>               .width = ,
>               .height = ;
>        };
> ```

done

**Comment by sudarsan-22** [comment]
> > > It seems there are some thing misunderstood here. I think @avolmat-st means, the fix should be
> > > ```
> > > struct video_format fmt = {
> > >     .type = VIDEO_BUF_TYPE_OUTPUT,
> > >     .pixelformat = VIDEO_PIX_FMT_YUYV or RGB565 depending on sensors
> > >     .width = X,
> > >     .height = Y,
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > instead of
> > > `struct video_format fmt = {0};` as being done.
> > > The advantage of this is we can do it in one go and we don't set the field that should not be set like `.pitch`
> > 
> > 
> > @ngphibang Thanks for the clarification! In this case, some of the struct members are conditionally set based on runtime checks (e.g., resolution selection via ov5640_is_dvp()), so initializing with { 0 } makes it clearer and avoids redundant assignments. I agree it's more readable and leaves room for future extensions without touching the later logic.
> 
> As far as I am concerned, I am only talking about the ov9655 here. Not all drivers.
> 
> The ov9655_init function is basically doing the following stuff:
> 
>     1. declare a struct video_fmt structure
> 
>     2. do various stuff, unrelated to this struct video_fmt
> 
>     3. assign 3 fields within the struct video_fmt (pixelformat, width, height)
> 
>     4. call the video_set_fmt function using that struct video_fmt structure declared at step 1.
> 
> 
> So, nothing is happening between 1. and 3. related to struct video_fmt so what is the merit to first initialize it to {0} at step 1 if we change it again at step 3. Our proposal is thus to initialize it at step 1 straight with proper values pixelformat, width, height and thus get rid of step 3.
> 
> So something like this:
> 
> ```
> static int ov9655_init(const struct device *dev)
> {
>         const struct ov9655_config *config = dev->config;
>         /* Set default camera format (QQVGA, YUYV) */
>         struct video_format fmt; = {
>               .pixelformat = VIDEO_PIX_FMT_YUYV,
>               .width = 160,
>               .height = 120;
>        };
>         uint32_t pid;
>         int ret;
> 
>        (...)
> 
>        return ov9655_set_fmt(dev, &fmt);
> }
> ```
> 
> and remove the block
> 
> ```
>         /* Set default camera format (QQVGA, YUYV) */
>         fmt.pixelformat = VIDEO_PIX_FMT_YUYV;
>         fmt.width = 160;
>         fmt.height = 120;
> ```
> 
> which is right before the
> 
> ```
>        return ov9655_set_fmt(dev, &fmt);
> }
> ```

thank you for your clarification

File: drivers/video/mt9m114.c [hunk 1]
```diff
@@ -527,7 +527,8 @@ static int mt9m114_init_controls(const struct device *dev)
 static int mt9m114_init(const struct device *dev)
 {
 	const struct mt9m114_config *cfg = dev->config;
-	struct video_format fmt;
+	struct video_format fmt = {
+		.pixelformat = VIDEO_PIX_FMT_RGB565, .width = 480, .height = 272};
```
Comment (josuah) [inline drivers/video/mt9m114.c]: That is exactly what was meant, remove the manual initialization below and use the C struct initializer syntax. Thank you!

If wanting to go beyond, Zephyr authors typically like having this style of initializer for readability:
```c
	struct video_format fmt = {
		.pixelformat = VIDEO_PIX_FMT_RGB565,
		.width = 480,
		.height = 272
	};
```

If passing that through clang-format though... It folds it like this:

```c
	struct video_format fmt = {
		.pixelformat = VIDEO_PIX_FMT_RGB565, .width = 480, .height = 272};
```

To get the "expanded" formatting like below, it is possible to add a comma after the last  element like this (note the comma added after 272):

```c
	struct video_format fmt = {
		.pixelformat = VIDEO_PIX_FMT_RGB565,
		.width = 480,
		.height = 272,
	};
```

This way, if clang-format (and other tools) will preserve the "expand" syntax.
Of course it is also possible to just format it manually.

Comment (josuah) [reply drivers/video/mt9m114.c]: I hope you do not mind us asking you to do so many modifications to your PRs. Just wanted to say that contribution is appreciated and hope you are also fine with us requesting all these changes!

Comment (sudarsan-22) [reply drivers/video/mt9m114.c]: > I hope you do not mind us asking you to do so many modifications to your PRs. Just wanted to say that contribution is appreciated and hope you are also fine with us requesting all these changes!

I'm absolutely fine with the changes — it's helping me learn a lot. Thanks for the valuable feedback!

Comment (sudarsan-22) [reply drivers/video/mt9m114.c]: > That is exactly what was meant, remove the manual initialization below and use the C struct initializer syntax. Thank you!
> 
> If wanting to go beyond, Zephyr authors typically like having this style of initializer for readability:
> 
> ```c
> 	struct video_format fmt = {
> 		.pixelformat = VIDEO_PIX_FMT_RGB565,
> 		.width = 480,
> 		.height = 272
> 	};
> ```
> 
> If passing that through clang-format though... It folds it like this:
> 
> ```c
> 	struct video_format fmt = {
> 		.pixelformat = VIDEO_PIX_FMT_RGB565, .width = 480, .height = 272};
> ```
> 
> To get the "expanded" formatting like below, it is possible to add a comma after the last element like this (note the comma added after 272):
> 
> ```c
> 	struct video_format fmt = {
> 		.pixelformat = VIDEO_PIX_FMT_RGB565,
> 		.width = 480,
> 		.height = 272,
> 	};
> ```
> 
> This way, if clang-format (and other tools) will preserve the "expand" syntax. Of course it is also possible to just format it manually.

Got it! thanks for your comments

**Review by avolmat-st — APPROVED** [review]
LGTM. Thanks !!

**Review by ngphibang — APPROVED** [review]

**Review by josuah — APPROVED** [review]
