### PR TITLE
drivers: ethernet: stm32: Disable HW checksum by default

### LINKED ISSUE #57629: stm32f7: ICMP checksum is 0 with Ethernet HAL V2 on some PHYs
**Describe the bug**
There's something wrong with the way checksums are handled when enabling `CONFIG_ETH_STM32_HAL_API_V2`, with the result being that with some PHYs, Ethernet does not work at all. This is easily observed by pinging a board exhibiting this issue, and observing that all ICMP replies have a 0 checksum. Note that this behavior apparently breaks all network traffic, not just ICMP packets. 

We're seeing this on a custom board of ours where we have an STM32F767ZI connected to the management port of a switch IC over RMII, but not on a Nucleo F767ZI development kit. @driechers have apparently observed the same problem on a Nucleo F756ZG based on [his comment](https://github.com/zephyrproject-rtos/zephyr/issues/46596#issuecomment-1533169513) on #46596.

Disabling `CONFIG_ETH_STM32_HAL_API_V2` avoids the problem, but is less robust in other ways, and is hence not a solution, at least not for our application. 

**To Reproduce**
1. Use a board with STM32F7 (and likely H7) and a problematic PHY (e.g. at least not Nucleo F767ZI)
2. Enable `CONFIG_ETH_STM32_HAL_API_V2`
3. Flash an Ethernet-enabled application to the board
4. Ping the board from a connected PC
5. Observe that Wireshark sees the replies, but that the checksum of the ICMP packet is 0:
```
Frame 968: 74 bytes on wire (592 bits), 74 bytes captured (592 bits) on interface \Device\NPF_{D5F26515-0661-4924-B26D-309CFEEA8792}, id 0
Ethernet II, Src: STMicroe_20:34:38 (00:80:e1:20:34:38), Dst: Private_38:28:c5 (80:6d:97:38:28:c5)
    Destination: Private_38:28:c5 (80:6d:97:38:28:c5)
    Source: STMicroe_20:34:38 (00:80:e1:20:34:38)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 10.0.37.239, Dst: 10.0.37.1
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
    Total Length: 60
    Identification: 0x0000 (0)
    000. .... = Flags: 0x0
    ...0 0000 0000 0000 = Fragment Offset: 0
    Time to Live: 64
    Protocol: ICMP (1)
    Header Checksum: 0x1bd2 [validation disabled]
    [Header checksum status: Unverified]
    Source Address: 10.0.37.239
    Destination Address: 10.0.37.1
Internet Control Message Protocol
    Type: 0 (Echo (ping) reply)
    Code: 0
    Checksum: 0x0000 incorrect, should be 0x516a
        [Expert Info (Warning/Checksum): Bad checksum [should be 0x516a]]
    [Checksum Status: Bad]
    Identifier (BE): 1 (0x0001)
    Identifier (LE): 256 (0x0100)
    Sequence Number (BE): 1009 (0x03f1)
    Sequence Number (LE): 61699 (0xf103)
    Data (32 bytes)
        Data: 6162636465666768696a6b6c6d6e6f7071727374757677616263646566676869
        [Length: 32]
```

**Expected behavior**
Packets should have a proper checksum, independent of whether they are calculated in software or hardware. 

**Workaround**
By disabling hardware checksumming with this patch, things work as expected:
```
diff --git a/drivers/ethernet/eth_stm32_hal.c b/drivers/ethernet/eth_stm32_hal.c
index 75b48daff5..da1ced69a5 100644
--- a/drivers/ethernet/eth_stm32_hal.c
+++ b/drivers/ethernet/eth_stm32_hal.c
@@ -1202,7 +1202,7 @@ static int eth_initialize(const struct device *dev)
        memset(&tx_config, 0, sizeof(ETH_TxPacketConfig));
        tx_config.Attributes = ETH_TX_PACKETS_FEATURES_CSUM |
                                ETH_TX_PACKETS_FEATURES_CRCPAD;
-       tx_config.ChecksumCtrl = ETH_CHECKSUM_IPHDR_PAYLOAD_INSERT_PHDR_CALC;
+       tx_config.ChecksumCtrl = ETH_CHECKSUM_DISABLE;
        tx_config.CRCPadCtrl = ETH_CRC_PAD_INSERT;
 #endif /* CONFIG_SOC_SERIES_STM32H7X || CONFIG_ETH_STM32_HAL_API_V2 */
```

**Impact**
With the workaround, things work as expected, and this hence isn't a showstopper, but it still feels like a pretty significant issue that needs a proper fix. 

**Environment (please complete the following information):**
 - OS: Windows 11
 - Toolchain: Zephyr SDK 0.15.0
 - Zephyr: v3.3.0

### PR DESCRIPTION
**Pull request by icsys-omh**
This change disables hardware checksums by default for V2 of the HAL Ethernet driver and for STM32H7, to be equivalent to the default configuration on V1 of the driver.

Hardware checksums can be enabled with CONFIG_ETH_STM32_HW_CHECKSUM Kconfig, but note that at least on some boards, enabling this will lead to invalid checksums (e.g. all 0) in outgoing packets, and hence loss of network communication. On such boards, this change makes networking functional by default, even with the V2 driver enabled. This therefore fixes #57629.

### CODE REVIEW

File: drivers/ethernet/eth_stm32_hal.c [hunk 1]
```diff
@@ -1203,7 +1203,11 @@ static int eth_initialize(const struct device *dev)
 	memset(&tx_config, 0, sizeof(ETH_TxPacketConfig));
 	tx_config.Attributes = ETH_TX_PACKETS_FEATURES_CSUM |
 				ETH_TX_PACKETS_FEATURES_CRCPAD;
+#if defined(CONFIG_ETH_STM32_HW_CHECKSUM)
 	tx_config.ChecksumCtrl = ETH_CHECKSUM_IPHDR_PAYLOAD_INSERT_PHDR_CALC;
+#else
+	tx_config.ChecksumCtrl = ETH_CHECKSUM_DISABLE;
+#endif
```
Comment (erwango) [inline drivers/ethernet/eth_stm32_hal.c:1210]: For readability, as this code section is already cluttered with #ifdef's, I'd suggest: 
```
	tx_config.ChecksumCtrl = IS_ENABLED(CONFIG_ETH_STM32_HW_CHECKSUM) ?
				ETH_CHECKSUM_IPHDR_PAYLOAD_INSERT_PHDR_CALC : ETH_CHECKSUM_DISABLE;
```

**Review by erwango — DISMISSED** [review]
Thanks for addressing this issue that we weren't able to catch.

One question on my side:
The bug that you're fixing was actually a misalignment in this code (that you're fixing):
`ChecksumCtrl` was defined while `eth_stm32_hal_get_capabilities` was not reporting HW checksum capabilities.

Is that possible that the functional issue was coming from this misalignment ?
And then maybe, with this fix, `CONFIG_ETH_STM32_HW_CHECKSUM=y` could be used safely in your use case also ?

**Review by erwango — APPROVED** [review]

**Comment by icsys-omh** [comment]
> One question on my side: The bug that you're fixing was actually a misalignment in this code (that you're fixing): `ChecksumCtrl` was defined while `eth_stm32_hal_get_capabilities` was not reporting HW checksum capabilities.
> 
> Is that possible that the functional issue was coming from this misalignment ? And then maybe, with this fix, `CONFIG_ETH_STM32_HW_CHECKSUM=y` could be used safely in your use case also ?

Thanks for the feedback! I actually didn't notice that difference, and you are indeed right: With the change in this PR, it seems I can enable HW_CHECKSUM and that things keep working. For now I updated this PR with just the formatting change you suggested, but perhaps it would make sense to enable HW checksums by default for V2?

It is also not quite clear to me why I seemed to observe a difference between different boards. Any thoughts on that? I'm not sure it matters much in practice, though - this change should be good anyway.

**Comment by erwango** [comment]
> perhaps it would make sense to enable HW checksums by default for V2?

In current Zephyr delivery we are V2 as default, which is already a great deal and, thanks to you, that's one bug less that users will see on this transition. 
I'm totally in favor to set HW checksum by default, but I'd prefer we go step by step and wait next release to avoid mixing issues that could be due to HW checksum or API version.

**Comment by erwango** [comment]
@Desvauxm-st can you review ?

**Review by gautierg-st — APPROVED** [review]

**Comment by cperera-aud** [comment]
Hi @erwango , hope you're doing well, we have been trying to port our application which works with Zephyr 3.2 to Zephyr 3.4. Our application runs on a STM32H7. However unfortunately we ran into an issue with the ethernet stm32 HAL driver specifically due to this change: https://github.com/zephyrproject-rtos/zephyr/commit/80bfed3b4484761aaece2d188a4e8ef6d31e6ae1. 

In our application its causing the outgoing IPv4/UDP packets to have a checksum of zero. In our application we're doing a network stack bypass to improve the performance and latency (audio over ethernet). We were relying on the MAC to populate the checksums for the IPv4/UDP headers. 

In the STM32H7 reference manual I can see that its actually supported:

image

My question is, I can see that in https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/ethernet/Kconfig.stm32_hal#L140, CONFIG_ETH_STM32_HW_CHECKSUM is not supported for STM32H7. Based on what's mentioned in the reference manual shouldn't CONFIG_ETH_STM32_HW_CHECKSUM be allowed to be supported on STM32H7. Certainly if I put back the change to enable the HW checksum as in Zephyr 3.2 our application works well in Zephyr 3.4.

Your input on this matter will be greatly appreciated.

**Comment by erwango** [comment]
^^@Desvaux-st

**Comment by Desvauxm-st** [comment]
@cperera-aud 

do you try to enable CONFIG_ETH_STM32_HW_CHECKSUM  ?
(CONFIG_ETH_STM32_HW_CHECKSUM=y in prj.conf )

**Comment by cperera-aud** [comment]
@Desvauxm-st, Yes I tried that but the build set CONFIG_ETH_STM32_HW_CHECKSUM to n. Today I made a local change to enable CONFIG_ETH_STM32_HW_CHECKSUM and it worked well with my application which runs on a STM32H7. The checksums were set as expected by the MAC.

**Comment by Desvauxm-st** [comment]
OK Good

**Comment by cperera-aud** [comment]
Hi @Desvauxm-st , @erwango ,

I have created a PR for the proposed changes for STM32H7: https://github.com/zephyrproject-rtos/zephyr/pull/67095. I think given that CONFIG_ETH_STM32_HW_CHECKSUM is an optional feature, whoever can opt to use it for STM32H7 or not. Having the HW offload the checksum calculation is important for a time critical application like audio over ethernet/IP which is what we're working on.
