### PR TITLE
kernel: make `k_msgq_put` become scheduler point

### LINKED ISSUE #79617: `k_msgq_put` does not wake up higher priority thread waiting on message queue with `k_poll`
**Describe the bug**

My application is using message queues with CONFIG_POLL. Project uses cooperative scheduling only and is build for embedded ARM target (Cortex-M). I noticed that placing new event on message queue with `k_msgq_put` does not immediately wake up higher priority thread polling on same message queue. 

I think issue that `k_msgq_put` is missing rescheduling on CONFIG_POLL path. When comparing `k_msgq_put` and `k_sem_give`, I see that message queue CONFIG_POLL code does not request rescheduling the same way is semaphore code path does:
 - message queue: https://github.com/zephyrproject-rtos/zephyr/blob/029540abece01361f52025534594a0b333cf0afd/kernel/msg_q.c#L161
 - semaphore: https://github.com/zephyrproject-rtos/zephyr/blob/029540abece01361f52025534594a0b333cf0afd/kernel/sem.c#L111

As workaround for my application, I've used dummy `k_sem_give` call after `k_msgq_put` call to enforce rescheduling.

**To Reproduce**

I used following test to reproduce issue outside my application code. 

```
K_MSGQ_DEFINE(msgq_high_prio_thread, sizeof(unsigned int), 4, 4);

static K_THREAD_STACK_DEFINE(high_prio_stack_area, 4096);
static struct k_thread high_prio_data;

static void high_prio_main(void *param1, void *param2, void *param3)
{
    static struct k_poll_event poll_events[1];

    // Setup wake-up for message queue
    k_poll_event_init(&poll_events[0],
                      K_POLL_TYPE_MSGQ_DATA_AVAILABLE,
                      K_POLL_MODE_NOTIFY_ONLY,
                      &msgq_high_prio_thread);

    // Wait for data on message queue
    // Note: buggy, does not wake up by k_msgq_put() even though low priority thread put message to queue.
    (void)k_poll(poll_events, 1, K_FOREVER);

    if (poll_events[0].state == K_POLL_STATE_MSGQ_DATA_AVAILABLE)
    {
        printf("success!");
    }
}

int main(void)
{
    int low_prio_thread_priority = 1;
    int high_prio_thread_priority = -2; // Coop priority
    unsigned int data_to_high_prio = 0x1234;

    k_thread_priority_set(k_current_get(), low_prio_thread_priority);

    // Create high priority thread
    (void)k_thread_create(&high_prio_data, high_prio_stack_area,
                          K_THREAD_STACK_SIZEOF(high_prio_stack_area),
                          high_prio_main,
                          NULL, NULL, NULL,
                          high_prio_thread_priority, 0, K_NO_WAIT);
    k_sleep(K_MSEC(1));

    // Send message to high-priority thread
    (void)k_msgq_put(&msgq_high_prio_thread, &data_to_high_prio, K_NO_WAIT);

    // Uncomment following line for enable rescheduling workaround
    //{ struct k_sem dummy_sem; k_sem_init(&dummy_sem, 1, 1); k_sem_give(&dummy_sem); }

    // Busy loop to prevent rescheduling to high-priority task (should have rescheduled inside k_msgq_put())
    while (1);
}
```

**Expected behavior**

I expect `k_msgq_put()` to reschedule to higher priority thread that is waiting on target message queue using `k_poll`.

**Impact**

As I have workaround, this is just an annoyance.

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: gnuarmemb
 - Commit SHA 029540abece01361f52025534594a0b333cf0afd

**Additional context**

### PR DESCRIPTION
**Pull request by TaiJuWu**
Fix: https://github.com/zephyrproject-rtos/zephyr/issues/79617

### CODE REVIEW

File: kernel/msg_q.c [hunk 1]
```diff
@@ -178,7 +182,11 @@ int z_impl_k_msgq_put(struct k_msgq *msgq, const void *data, k_timeout_t timeout
 
 	SYS_PORT_TRACING_OBJ_FUNC_EXIT(k_msgq, put, msgq, timeout, result);
 
-	k_spin_unlock(&msgq->lock, key);
+	if (resched) {
+		z_reschedule(&msgq->lock, key);
+	} else {
+		k_spin_unlock(&msgq->lock, key);
+	}
```
Comment (andyross) [inline kernel/msg_q.c:189]: FWIW I'm not a fan of this pattern, which is common but has been preserved only for compatibility.  Basically what this is saying is that "k_msgq_put() is a scheduling point if there was a thread waiting, **but not if there wasn't**", which is confusing to document and reason about.  (The difference in behavior being whether or not it will allow a third runnable higher priority thread to run or not).

Ideally an operation would be either a scheduling point or not, without this kind of logic.  Again we don't currently do that in many places because of history, and because changing scheduler behavior is often perceived as a compatibility bug.    But as we evolve it should be in that direction IMHO.

**Review by andyross — COMMENTED** [review]
No complaints in general to making this a scheduling point, but:

1. Please correct the commit message.  This isn't changing wakeup behavior, just whether or not a reschedule happens.
2. Flip the order of the two commits to avoid a bisection glitch (the test fails in the current tree, right?)
3. Add documentation to k_msgq_put() to make it clear that the call will reschedule.
4. See nitpick about the "predicated reschedule()" anti-pattern that IMHO we don't want to perpetuate.

File: kernel/msg_q.c (hunk 1 above)
Comment (TaiJuWu) [reply kernel/msg_q.c:189]: Thanks for your explanation. It is very useful for me.

**Review by andyross — DISMISSED** [review]
I'm out of complaints, thanks!

File: tests/integration/kernel/src/main.c [hunk 2]
```diff
@@ -302,6 +306,38 @@ ZTEST(kernel, test_mutex_usage)
 	k_thread_abort(tid2);
 }
 
+static void high_prio_main(void *param1, void *param2, void *param3)
```
Comment (nashif) [inline tests/integration/kernel/src/main.c:309]: msgq tests should go into `tests/kernel/msgq/`

**Review by nashif — CHANGES_REQUESTED** [review]
please put tests in the right place.

File: tests/integration/kernel/src/main.c (hunk 2 above)
Comment (TaiJuWu) [reply tests/integration/kernel/src/main.c:309]: Hi @nashif ,
This test include two behavior `poll`, `message` and require run on only 1 cpu so I think it is better here than `msgq`.
WDYT?

**Comment by TaiJuWu** [comment]
Hi @peter-mitsis ,

Let me share the performace impact for this change.
This benchmark comes from `tests/benchmarks/app_kernel`

With this PR
|Method|       time |
|------------------------------------------------------------------------|----------|
| enqueue 1 byte msg in MSGQ                                                        |      7362|
| enqueue 4 bytes msg in MSGQ                                                      |      8514|
| enqueue 192 bytes msg in MSGQ                                                  |     80706|
| enqueue 1 byte msg in MSGQ to a waiting higher priority task    |     34498|
| enqueue 4 bytes in MSGQ to a waiting higher priority task          |     35650|
| enqueue 192 bytes in MSGQ to a waiting higher priority task      |    107841



Without this PR
|Method|       time |
|------------------------------------------------------------------------|----------|
| enqueue 1 byte msg in MSGQ                                       |      6530|
| enqueue 4 bytes msg in MSGQ                                      |      7682|
| enqueue 192 bytes msg in MSGQ                                    |     79874|
| enqueue 1 byte msg in MSGQ to a waiting higher priority task     |     34434|
| enqueue 4 bytes in MSGQ to a waiting higher priority task        |     35586|
| enqueue 192 bytes in MSGQ to a waiting higher priority task      |    107777|

The performance is not significantly affected when the message size exceeds 192B.
Do we still need to conditional `z_reschedule()` here since I also think it is tricky thing for condition `z_reschedule()`.
I also can image there will similiar issue for the old implementation (https://github.com/zephyrproject-rtos/zephyr/commit/80cd1f933d3a1779122a37063e4bd88ae343f093).

I can image below
1. Thread A is created with high priority
2. Thread B put message but there is no thread on waiting queue
3. Thread B continue to work.

**Comment by andyross** [comment]
> I don't think that an unconditional z_reschedule() is the right approach; it seems too heavy handed for when there is an uncontested resource

reschedule() doesn't call down directly into swap, it has its own test of the run queue to see if something needs to happen.   It should be cheap and if it's missing a case we should fix that.

File: tests/integration/kernel/src/main.c (hunk 2 above)
Comment (nashif) [reply tests/integration/kernel/src/main.c:309]: can also go into `tests/kernel/poll/`, `tests/integration/kernel` is not the right place, we need this per module/kernel feature and all in one place related to the primitive being changed.

Comment (TaiJuWu) [reply tests/integration/kernel/src/main.c]: Done.

**Comment by TaiJuWu** [comment]
Update: only move test into `test/kernel/msgq`

**Review by andyross — APPROVED** [review]
Refresh +1

**Comment by mmahadevan108** [comment]
@peter-mitsis, can you please re-review

**Review by peter-mitsis — APPROVED** [review]

**Review by nashif — APPROVED** [review]
