### PR TITLE
drivers: counter: sam_tc: Big fix for alarm 1

### LINKED ISSUE #85018: drivers: counter: sam: The alarm 1 do not generate interrupt
**Describe the bug**
The counter driver for Atmel SAM works fine on Alarm 0. When switch to Alarm 1 the interrupt is never generated.

**To Reproduce**
Build the samples/drivers/counter/alarm and check that counter is working.
Change the line from 0 to 1. https://github.com/zephyrproject-rtos/zephyr/blob/94cd7865a99d4c19a7e33dc4cd48b9bb9d70ac42/samples/drivers/counter/alarm/src/main.c#L14
Build the application again and test. The interrupt never happen.

**Expected behavior**
The counter should work on RB (Alarm 1) the same way that work on RA (Alarm 0).

**Impact**
Alarm 1 do not work.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK 0.17.0
 - Commit mainline

### PR DESCRIPTION
**Pull request by MCHP-MPU-Solutions-SHA**
Issue: the alarm 1 do not generate interrupt
There are three compare registers in a SAM TC channel:
RA --> alarm 0
RB --> alarm 1
RC --> top_value
By default the RB/TOIB was configured as an input and no longer generates interrupt.
Set the direction of TIOB to output for alarm 1 interrupt.

Fixes zephyrproject-rtos/zephyr#85018

Many thanks.
Xing.

### CODE REVIEW

File: drivers/counter/counter_sam_tc.c [hunk 1]
```diff
@@ -356,6 +356,7 @@ static DEVICE_API(counter, counter_sam_driver_api) = {
 
 #define COUNTER_SAM_TC_CMR(n)	\
 		 (TC_CMR_TCCLKS(DT_INST_PROP_OR(n, clk, 0)) \
+		| TC_CMR_WAVEFORM_EEVT_XC0 \
```
Comment (nandojve) [inline drivers/counter/counter_sam_tc.c:359]: Add the below in the commit message body:

```diff
Set the direction of TIOB to output for alarm 1 interrupt.
+
+Fixes zephyrproject-rtos/zephyr#85018
+
Signed-off-by: CHEN Xing <xing.chen@microchip.com>
```

**Review by nandojve — CHANGES_REQUESTED** [review]
Test on `sam_v71_xult/samv71q21`: Ok

File: drivers/counter/counter_sam_tc.c (hunk 1 above)
Comment (MCHP-MPU-Solutions-SHA) [reply drivers/counter/counter_sam_tc.c:359]: Updated, please help check.

**Review by nandojve — APPROVED** [review]
Hi Xing,

Thank you so much for this patch!

**Review by pdgendt — APPROVED** [review]

**Comment by MCHP-MPU-Solutions-SHA** [comment]
> Hi Xing,
> 
> Thank you so much for this patch!

You are welcome!

**Comment by jfischer-no** [comment]
The CI is failing on sam4l_wm400_cape, `west twister -p sam4l_wm400_cape/sam4lc4b -s drivers.counter.basic_api`, after commit (8f5daca5e56514284a45a19964a25a9c52b9d783). For example https://github.com/zephyrproject-rtos/zephyr/actions/runs/16775544341/job/47501188595?pr=87269

**Comment by MCHP-MPU-Solutions-SHA** [comment]
Are we talking about this compiling error:
INFO    - 1) drivers.counter.basic_api on sam4l_wm400_cape/sam4lc4b error (Build failure - error: 'TC_CMR_WAVEFORM_EEVT_XC0' undeclared here (not in a function); did you mean 'TC_CMR_WAVEFORM_EEVT_Msk'?)

I will update zephyrproject-rtos/hal_atmel repo for fixing it, then re-open this PR.

**Comment by MCHP-MPU-Solutions-SHA** [comment]
Create PR [#49](https://github.com/zephyrproject-rtos/hal_atmel/pull/49) for zephyrproject-rtos/hal_atmel.

Will update (update the revision of hal_atmel in west.yml) and re-open this PR once PR #49 has been merged.

**Comment by pdgendt** [comment]
> Create PR [#49](https://github.com/zephyrproject-rtos/hal_atmel/pull/49) for zephyrproject-rtos/hal_atmel.
> 
> Will update (update the revision of hal_atmel in west.yml) and re-open this PR once PR #49 has been merged.

You can already create the PR referring to your PR, see https://docs.zephyrproject.org/latest/develop/modules.html#submitting-changes-to-modules
