### PR TITLE
overhaul thread stack specification

### LINKED ISSUE #13637: Introduce supervisor-only stack declaration macros
We currently assume that any given stack object may be used by a thread which can enter user mode. However, this assumption wastes memory for threads which always exist in supervisor mode.

Introduce some new stack declaration macros similar to K_THREAD_STACK_DEFINE which declare supervisor-only thread stacks:

- These stacks will not reserve memory for a privileged mode stack for syscalls, either by adding extra memory to the stack object (x86, ARC) or reservation of privileged stack buffer elsewhere (ARM)
- These stacks will be registered as a distinct kernel object type, such that if a thread with one of these stacks attempts to drop to user mode, or be created with the K_USER flag, will result in an error.
- These stacks will not have their sizes adjusted so that memory protection hardware regions can be set on them; for example there will be no rounding up to the nearest power of 2 (ARM) or page boundary (x86)
- Supervisor thread stack overflow guard regions will still be supported

We should use these macros in the kernel to declare the interrupt stack and the idle thread stack.

### LINKED ISSUE #13651: ARC does not set thread->stack_info correctly
**Describe the bug**
For any given thread, thread->stack_info.start / thread->stack_info.size represents the area within the stack that is read/writable by the user.

However, I've found that on ARC, this is not the case.

**To Reproduce**
Pull #13650 and run on nsim_em, observe crash.

**Expected behavior**
Test should pass, the user thread should have read/write access to this region in its own stack.

### LINKED ISSUE #14269: Enforce usage of K_THREAD_STACK_SIZEOF macro in k_thread_create()
**Describe the bug**
There is some inconsistency in how the macros related to Thread stack definition are actually user in Zephyr applications/samples/tests/subsystems. Ideally, we want to 
- define a Thread stack object using `stack obj = K_THREAD_STACK_DEFINE`(sym, `nominal size`)
- call `k_thread_create `with stack_size = `K_THREAD_STACK_SIZEOF(stack obj)`

In this way we guarantee that `k_thread_stack_create `is given the amount of stack area (in bytes) that can actually be used by the thread, excluding, for instance, a privileged stack guard (in ARM builds).

However, this is not always the case: in several cases (including even the _main thread) k_thread_stack_create is passed `nominal_size`, instead of K_THREAD_STACK_SIZE_OF(sym). If privileged stack guards are to be used on ARM builds with requirement for power-of-two start/size alignment of stack objects, then this is a **_bug_**, because `k_thread_stack_define` is supplied with a size value that is larger that what the thread can actually use: this is because in that case no extra area is allocated for the guard.

In ARM builds with CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT && USERSPACE we have a work-around for this, but it effectively eats up 32-bytes from the stack objects. 

**Expected behavior**
- Always call `k_thread_stack_create()` with argument `stack_size = K_THREAD_STACK_SIZEOF(stack object)`, where, `stack object = K_THREAD_STACK_DEFINE(nominal size)`
- Document this properly in the doc

### LINKED ISSUE #25635: ARM: TLS pointer may not be set correctly
**Describe the bug**

It's expected that given the following code:

```
#define SIZE       4096
struct k_thread thread;
K_THREAD_STACK_DEFINE(stack, SIZE);
```

That it is valid to pass either `SIZE` or `K_THREAD_STACK_SIZEOF(stack)` to a `k_thread_create()` call's stack size argument.

This is not the case for ARM Cortex-M. If `SIZE` is passed in, the math is performed improperly and the TLS pointer gets set to memory *after* the end of the stack object. This will result in either MPU faults when trying to access TLS (at the moment, limited to getting/setting `errno`) or data corruption.

The following test code illustrates the issue. Only ARM Cortex-M seems to be affected.

```
diff --git a/tests/kernel/mem_protect/userspace/src/main.c b/tests/kernel/mem_protect/userspace/src/mai
index 4eb34e0407..71f8862ddc 100644
--- a/tests/kernel/mem_protect/userspace/src/main.c
+++ b/tests/kernel/mem_protect/userspace/src/main.c
@@ -1131,6 +1131,43 @@ void test_object_recycle(void)
        zassert_true(perms_count == 1, "invalid number of thread permissions");
 }

+#define TLS_SIZE       4096
+struct k_thread tls_thread;
+K_THREAD_STACK_DEFINE(tls_stack, TLS_SIZE);
+
+void tls_entry(void *p1, void *p2, void *p3)
+{
+       printk("tls_entry\n");
+}
+
+void test_tls_pointer(void)
+{
+       k_thread_create(&tls_thread, tls_stack, TLS_SIZE, tls_entry,
+                       NULL, NULL, NULL, 1, K_USER, K_FOREVER);
+
+       printk("tls pointer for thread %p: %p\n",
+              &tls_thread, (void *)tls_thread.userspace_local_data);
+
+       printk("stack buffer reported bounds: [%p, %p)\n",
+              (void *)tls_thread.stack_info.start,
+              (void *)(tls_thread.stack_info.start +
+                       tls_thread.stack_info.size));
+
+       printk("stack object bounds: [%p, %p)\n",
+              tls_stack, tls_stack + sizeof(tls_stack));
+
+       uintptr_t tls_start = (uintptr_t)tls_thread.userspace_local_data;
+       uintptr_t tls_end = tls_start +
+               sizeof(struct _thread_userspace_local_data);
+
+       if ((tls_start < (uintptr_t)tls_stack) ||
+           (tls_end > (uintptr_t)tls_stack + sizeof(tls_stack))) {
+               printk("tls area out of bounds\n");
+               ztest_test_fail();
+       }
+}
+
+
 void test_main(void)
 {
        struct k_mem_partition *parts[] = {&part0, &part1,
@@ -1184,7 +1221,8 @@ void test_main(void)
                         ztest_unit_test(test_stack_buffer),
                         ztest_user_unit_test(test_unimplemented_syscall),
                         ztest_user_unit_test(test_bad_syscall),
-                        ztest_unit_test(test_object_recycle)
+                        ztest_unit_test(test_object_recycle),
+                        ztest_unit_test(test_tls_pointer)
                         );
        ztest_run_test_suite(userspace);
 }
```

**To Reproduce**
Run above test code. You will see:

```
===================================================================
starting test - test_tls_pointer
tls pointer for thread 0x200088a8: 0x2001d018
stack buffer reported bounds: [0x2001c020, 0x2001d000)
stack object bounds: [0x2001c000, 0x2001d000)
tls area out of bounds
FAIL - test_tls_pointer
```

**Expected behavior**
Passing test. TLS region should be within bounds of the stack object.

**Impact**
Workaround is possible by always using `K_THREAD_STACK_SIZEOF()`, but users who don't know about this could get MPU faults or data corruption.

My PR #24714 fixes this as I rewrote all the relevant code.
For 1.14 branch I need a more targeted solution.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
This PR attempts to centralize stack management to common code, introduce kernel-only stacks which use less memory, and document best practices for new architecture ports.

Major changes in this PR:
* arch_new_thread() API has been revised. Some extraneous parameters have been removed, and the kernel now pre-computes an initial stack pointer which uses as much space as possible and takes into account random offsets and thread-local storage. One change related to this credit goes to @ceolin. arch_new_thread() no longer needs to call back into the kernel to set stack boundaries.
* The arch interface for thread stacks has changed. The macros for declaring stacks are all centralized. Arches now define the required stack pointer alignment, the alignment of stack objects, and a macro to convert a requested stack buffer size into the actual object size needed by HW. For any given arch the definitions are much simpler.
* New macros introduced for declaring kernel-only stacks, all are prefixed with K_KERNEL_STACK. Stacks that are capable of hosting user mode are now placed in a designated section so that they can be recognized at runtime.
* Improvements to the test case for thread stacks, now no longer part of the userspace test.
* Additional thread stack memory reserved due to rounding up to size/alignment requirements is now fully used.
* arches, drivers, subsystems, and library code updated to use kernel-only stacks where appropriate, potentially saving large amounts of memory if user mode is enabled.

Please see individual commit messages for more details.

Fixes: #13651
Fixes: #13637
Fixes: #25635

Note about naming: I chose `K_KERNEL_STACK_*` for the supervisor-only stack macros and left `K_THREAD_STACK_*` alone, as to not break existing code (you can use K_THREAD_STACK for everything at the expense of memory)

Other than avoiding breakages, I have no particular attachment to these names though. There is already unfortunately another type of kernel object called `k_stack`.

This also closes #14269 (making it obsolete, and removing relevant workaround for ARMv7-M)

### CODE REVIEW

**Comment by andrewboie** [comment]
This will need some HW testing on frdm_k64f as we don't have an emulator which supports the NXP MPU. Trying to get my board working but having some issues with it.

**Comment by andrewboie** [comment]
Note about naming: I chose `K_KERNEL_STACK_*` for the supervisor-only stack macros and left `K_THREAD_STACK_*` alone, as to not break existing code (you can use K_THREAD_STACK for everything at the expense of memory)

Other than avoiding breakages, I have no particular attachment to these names though.

**Review by aescolar — APPROVED** [review]
+1 for POSIX ARCH change. No claims about anything else

**Comment by andrewboie** [comment]
@abrodkin @ruuddw @vonhust ARC changes are ready for you guys to take a look at.

File: include/kernel.h [hunk 1]
```diff
@@ -506,9 +506,16 @@ struct _thread_stack_info {
...
 	/* Stack Size - Thread writable stack buffer size. Represents
 	 * the size of the actual area, starting from the start member,
-	 * that should be writable by the thread
+	 * that should be writable by the thread. This includes any TLS storage
+	 * and random offsets applied to the initial stack pointer.
 	 */
 	size_t size;
+
+	/* A positive adjustment value to the size member, removing any storage
+	 * used for TLS or random stack base offsets. (start + size - offset)
```
Comment (ruuddw) [inline include/kernel.h:515]: Should 'offset' in the comments here be 'delta'?

File: kernel/init.c [hunk 2]
```diff
@@ -317,8 +317,10 @@ static void init_idle_thread(int i)
  * @return N/A
```
Comment (ruuddw) [inline kernel/init.c:317]: N/A -> stack pointer

File: kernel/thread.c [hunk 3]
```diff
@@ -436,32 +435,106 @@ static inline size_t adjust_stack_size(size_t stack_size)
...
+		return 0;
 	}
 
-	return stack_size - fuzz;
+	return fuzz;
 }
 #if defined(CONFIG_STACK_GROWS_UP)
 	/* This is so rare not bothering for now */
 #error "Stack pointer randomization not implemented for upward growing stacks"
 #endif /* CONFIG_STACK_GROWS_UP */
```
Comment (ruuddw) [inline kernel/thread.c:446]: Should STACK_GROWS_UP be deprecated? I don;t believe the other cache pointer calculations work in that case.

File: kernel/thread.c [hunk 4]
```diff
@@ -436,32 +435,106 @@ static inline size_t adjust_stack_size(size_t stack_size)
...
+			 k_thread_entry_t entry,
+			 void *p1, void *p2, void *p3,
+			 int prio, u32_t options, const char *name)
 {
+	char *stack_ptr;
+
 	Z_ASSERT_VALID_PRIO(prio, entry);
 
 #ifdef CONFIG_USERSPACE
+	__ASSERT((options & K_USER) == 0 || z_stack_is_user_capable(stack),
```
Comment (ruuddw) [inline kernel/thread.c:535]: is an ASSERT enough or should it always be checked & some error returned?

**Comment by ruuddw** [comment]
> @abrodkin @ruuddw @vonhust ARC changes are ready for you guys to take a look at.

Yes, I noticed and started reviewing. Added some quick (minor) comments. Looks like a good refactoring and clean-up.  What (ARC) targets did you already test? We can check on others that you don't have.

File: include/toolchain/gcc.h [hunk 5]
```diff
@@ -462,5 +462,21 @@ do {                                                                    \
 		_value_a_ < _value_b_ ? _value_a_ : _value_b_; \
 	})
 
+/**
+ * @brief Calculate power of two ceiling for some value
+ *
+ * @param x Unsigned long value
```
Comment (ceolin) [inline include/toolchain/gcc.h:468]: Though this macro was already here, it is worth to document that if x == 0 the result is undefined.

File: include/sys/thread_stack.h [hunk 6]
```diff
@@ -50,8 +50,45 @@ struct __packed z_thread_stack_element {
...
  * hardware requirements.
+ *
+ * @param ptr Proposed stack pointer address
+ * @return Properly aligned stack pointer address
+ */
+static inline char *z_stack_ptr_align(char *ptr)
+{
+	return (char *)ROUND_DOWN(ptr, ARCH_STACK_PTR_ALIGN);
+}
+#define Z_STACK_PTR_ALIGN(ptr) ((uintptr_t)z_stack_ptr_align((char *)(ptr)))
```
Comment (ceolin) [inline include/sys/thread_stack.h:61]: MISRA-C would probably happier if we use `u8_t*` or `uint8_t*` since `char` is signed. This is not a blocker just commenting it here to see if there is  anything against using `u8_t` instead of `char` in these situations.

File: kernel/thread.c (hunk 3 above)
Comment (andrewboie) [reply kernel/thread.c:446]: at the moment, lots of things (independent of this PR) probably don't work with upward growing stacks, as this is never a configuration that has been tested.

I would not object to completely removing it, but I think we should do that in another PR. As it stands, we'll get a build error if enabled.

File: include/sys/thread_stack.h (hunk 6 above)
Comment (andrewboie) [reply include/sys/thread_stack.h:61]: sure I can change to u8_t *

**Comment by andrewboie** [comment]
> What (ARC) targets did you already test? We can check on others that you don't have.

@ruuddw so far just on nsim_em, nsim_sem, nsim_sem_mpu_stack_guard. Will be testing on HSDK this week.

Updated version of this PR coming, thanks for the review. I'm going to make a change where we just pass the computed delta offset instead of specifying a particular stack pointer, as this will be a pain point otherwise for systems that wish to map the stack in virtual memory.

File: kernel/thread.c (hunk 4 above)
Comment (andrewboie) [reply kernel/thread.c:535]: This API is currently void and propagates no return value. We'd have to change that. Assertions in arch_user_mode_enter() aren't propagated either.

This isn't an API that user mode can invoke however, it's supervisor-only.

File: include/kernel.h [hunk 7]
```diff
@@ -506,9 +506,16 @@ struct _thread_stack_info {
 
 	/* Stack Size - Thread writable stack buffer size. Represents
 	 * the size of the actual area, starting from the start member,
-	 * that should be writable by the thread
+	 * that should be writable by the thread. This includes any TLS storage
+	 * and random offsets applied to the initial stack pointer.
```
Comment (ioannisg) [inline include/kernel.h:510]: To clarify, @andrewboie:
You are changing the semantics of 'size', right? This now seems to be 'immutable', while before, the 'size' was adjusted to reflect any reductions due to user-local data storage or round-down adjustments due to randomization, at least for Cortex-M. Or that was generic?

IMO we need to answer the following question:
- Shall the 'stack_info.size' have an 1-1 correspondence to the area that **will eventually** be configured with User RW privileges when the thread enters user mode, or any time the thread switches-in? If so, I wonder if all the 'reduction' due to initial randomization of the stack pointer should be configured as user-accessible, or not... I am OK with both 'yes' or 'no' as long as we specify this.

- Just a note: in Cortex-M we must also round the buffer area down, to make sure it respects the minimum MPU alignment requirements. E.g. for ARMv8-M we have 32-byte alignment requirement. This applies to start and end of the MPU region. We enforce the alignment of the 'start' via K_THREAD_STACK_DEFINE, but the SIZE can by anything, AFAIU. So if the SIZE is not 32-byte aligned, we _anyway_ need to do some round-down of the stack buffer size, and this area cannot be classified as writable by the user thread and shall not be reflected in stack_info.size.

My suggestion to make the specification a bit more clear:

`Thread writable stack buffer size. Represents the size of the actual buffer, starting from the 'start' member, that should be writable by the thread. This comprises of the thread stack area, any area reserved for local thread data storage, as well as any area left-out due to random adjustments applied to the initial thread stack pointer during thread initialization.`

File: include/kernel.h [hunk 8]
```diff
@@ -506,9 +506,16 @@ struct _thread_stack_info {
...
 	 */
 	size_t size;
+
+	/* A positive adjustment value to the size member, removing any storage
```
Comment (ioannisg) [inline include/kernel.h:514]: Change 'positive' to 'non-negative', since this in general may be zero.

Comment (ioannisg) [reply include/kernel.h:514]: Suggestion:
`Non-negative adjustment value to the thread's writable stack buffer, reflecting any area reserved for local thread data storage, or left-out due to random adjustments applied to the initial thread stack pointer during thread initialization. (start + size - offset) is the initial stack pointer of a thread.`

File: tests/kernel/threads/thread_stack/prj.conf [hunk 9]
```diff
@@ -0,0 +1,5 @@
+CONFIG_ZTEST=y
+CONFIG_INIT_STACKS=y
+CONFIG_THREAD_STACK_INFO=y
+CONFIG_APPLICATION_DEFINED_SYSCALL=y
+CONFIG_TEST_USERSPACE=y
```
Comment (ioannisg) [inline tests/kernel/threads/thread_stack/prj.conf:5]: Do you intentionally leave HW_STACK_PROTECTION off the list here (might be already default but it makes sense to explicitly add it here, no?)

File: include/kernel.h [hunk 10]
```diff
@@ -749,10 +756,9 @@ extern void k_thread_foreach_unlocked(
  * K_FP_REGS, and K_SSE_REGS. Multiple options may be specified by separating
  * them using "|" (the logical OR operator).
  *
- * Historically, users often would use the beginning of the stack memory region
- * to store the struct k_thread data, although corruption will occur if the
- * stack overflows this region and stack protection features may not detect this
- * situation.
+ * The stack_size parameter must be the same size value used when the stack
+ * object was defined, or the return value of K_THREAD_STACK_SIZEOF() on the
+ * stack object.
```
Comment (ioannisg) [inline include/kernel.h:761]: This is very nice @andrewboie , it really clears it up. I have a suggestion to make it more explicit:
(and, btw, K_THREAD_STACK_SIZEOF is now renamed to K_KERNEL_STACK_SIZEOF.)

```
The stack_size parameter must be the same size value used when the stack
object was defined using K_KERNEL_STACK_DEFINE(), or, equivalently, the
return value of K_KERNEL_STACK_SIZEOF() on the stack object.
```

So, to summarize:
- `STACKSIZE` (value in bytes) shall **always** be equal to:
-  `K_KERNEL_STACK_SIZEOF(stack_obj)`, where `stack_obj `is defined as `K_KERNEL_STACK_DEFINE(stack_obj, STACKSIZE)`
- and we are only allowed to call `k_thread_create `with either of the two options as arguments, and
- these options are equivalent :)

Or, inverted:
K_KERNEL_STACK_SIZEOF(stack_obj) shall always return the `size` value used when defining stack_obj as `K_KERNEL_STACK_DEFINE(stack_obj, size)`

Do you agree?

Comment (andrewboie) [reply include/kernel.h:761]: It's a little more complex than this.

For some invocation `K_THREAD_STACK_DEFINE(my_stack, X)`, the return value of `K_THREAD_STACK_SIZEOF(my_stack)` is *not* guaranteed to be `X`. They can be different values, they are not guaranteed to be the same. What will happen on some systems is that `K_THREAD_STACK_SIZEOF(my_stack)` is equal to 'X' *rounded up* to some alignment value.

However, `k_thread_create(my_thread, my_stack, Y, ...)` is guaranteed to work properly (and identically) if Y is either `X` or `K_THREAD_STACK_SIZEOF(my_stack)`.

What actually is equivalent, with some `K_THREAD_STACK_DEFINE(my_stack, X)`, is that `K_THREAD_STACK_SIZEOF(my_stack)` equals `Z_THREAD_STACK_SIZE_ADJUST(X)`. `setup_thread_stack()` in thread.c performs this calculation, which is how it is able to take either as the stack size value.

File: tests/kernel/threads/thread_stack/prj.conf (hunk 9 above)
Comment (andrewboie) [reply tests/kernel/threads/thread_stack/prj.conf:5]: this test does not exercise HW_STACK_PROTECTION. It does implictly get enabled if ztest is active, but there is no specific scenario for it in this test suite. We test that stuff in other suites (tests/kernel/fatal IIRC)

File: include/kernel.h (hunk 8 above)
Comment (andrewboie) [reply include/kernel.h:514]: size_t is unsigned so I probably don't need to mention negative numbers at all :) I'll revise.

File: include/kernel.h (hunk 7 above)
Comment (andrewboie) [reply include/kernel.h:510]: My intention is that there is a 1:1 correspondence with the region programmed for User RW access, across all arches. There's no need to make the random region invisible to the user, we can include it and TLS. Your doc suggestion looks great I'll incorporate it.

File: include/toolchain/gcc.h (hunk 5 above)
Comment (andrewboie) [reply include/toolchain/gcc.h:468]: agreed. On GCC it actually return 1 as expected, but this is UB. I'll update the docs.

File: include/kernel.h (hunk 10 above)
Comment (andrewboie) [reply include/kernel.h:761]: > (and, btw, K_THREAD_STACK_SIZEOF is now renamed to K_KERNEL_STACK_SIZEOF.)

They are the same if user mode is not enabled, but differ slightly if user mode is enabled:

``
#define K_THREAD_STACK_SIZEOF(sym)	(sizeof(sym) - K_THREAD_STACK_RESERVED)
```
and 
```
#define K_KERNEL_STACK_SIZEOF(sym) (sizeof(sym) - K_KERNEL_STACK_RESERVED)
```

Key difference being that `K_THREAD_STACK_RESERVED` and `K_KERNEL_STACK_RESERVED` can differ (for example on x86 no memory for page tables or the privilege elevation stack is reserved for kernel-only stacks)

File: include/sys/thread_stack.h (hunk 6 above)
Comment (andrewboie) [reply include/sys/thread_stack.h:61]: Hi @ceolin I'd like to punt on this part, as there is a bunch of other existing stack code currently using char * as the data type for the raw stack buffer. Can you file a GH issue on this and I'll get to it in another PR?

**Comment by andrewboie** [comment]
Update:

- I dropped the patches which convert subsystems and drivers to use kernel-only stacks. It adds an insane amount of reviewers and makes review very difficult (GH doesn't support huge PRs very well). I can send that out again once this lands.
- Rebased on the latest code, there were a lot of conflicts
- I added a test scenario to prove that various size-related identities hold
- Addressed review comments, please let me know if I missed anything.

**Comment by andrewboie** [comment]
>  I'm going to make a change where we just pass the computed delta offset instead of specifying a particular stack pointer, as this will be a pain point otherwise for systems that wish to map the stack in virtual memory.

On further thought, this is fine how it is -- any policy for mapping a stack in virtual memory will be done in the core kernel, we are not going to leave virtual address space management to the arch code. So if the kernel wants to memory map stacks, the core kernel can do that and send the virtual address to the arch code using the current scheme.

However, one thing I want to do is revise the ARM code to only use separate privilege mode stacks if the MPU is power-of-two, we currently do it for all ARM targets which is not ideal.

File: include/sys/thread_stack.h (hunk 6 above)
Comment (ceolin) [reply include/sys/thread_stack.h:61]: yep, I can track it in a MISRA-C issue. This is not the only place doing it.

**Comment by andrewboie** [comment]
@ioannisg @ruuddw pushing to get this in maybe this week if you have some time for review.

> However, one thing I want to do is revise the ARM code to only use separate privilege mode stacks if the MPU is power-of-two, we currently do it for all ARM targets which is not ideal.

Touched on this topic during the call; consensus I believe is we can do this as a further enhancement. I left as-is in the current code.

**Review by nashif — APPROVED** [review]

**Comment by ioannisg** [comment]
> @ioannisg @ruuddw pushing to get this in maybe this week if you have some time for review.
> 
> > However, one thing I want to do is revise the ARM code to only use separate privilege mode stacks if the MPU is power-of-two, we currently do it for all ARM targets which is not ideal.
> 
> Touched on this topic during the call; consensus I believe is we can do this as a further enhancement. I left as-is in the current code.

 @andrewboie will do a review  pass as soon as possible.

**Comment by YuguoWH** [comment]
@andrewboie @ruuddw , I ran some tests and no errors found at emsdp, iotdk, nsim_em, nsim_hs. 
However there is one error found with both **nsim_sem** and **nsim_sem_mpu_stack_guard** while running **tests/lib/mem_alloc/libraries.libc.newlib**. 

Error message:

> zephyr/lib/libc/newlib/libc-hooks.c: In function 'malloc_prepare':
> zephyr/lib/libc/newlib/libc-hooks.c:54:19: error: implicit declaration of function 'Z_ARC_MPU_SIZE_ALIGN'; did you mean 'Z_ARC_MPU_ALIGN'? [-Werror=implicit-function-declaration]
>    54 | #define HEAP_BASE Z_ARC_MPU_SIZE_ALIGN(USED_RAM_END_ADDR)
>         |                   ^~~~~~~~~~~~~~~~~~~~
> zephyr/lib/libc/newlib/libc-hooks.c:79:29: note: in expansion of macro 'HEAP_BASE'
>    79 |  z_malloc_partition.start = HEAP_BASE;
>         |                             ^~~~~~~~~
> 

(Z_ZRC_MPU_SIZE_ALIGN was previous defined in include/arch/arc/arch.h and is removed in this PR)

**Review by jenmwms — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Comment by andrewboie** [comment]
> @andrewboie @ruuddw , I ran some tests and no errors found at emsdp, iotdk, nsim_em, nsim_hs.
> However there is one error found with both **nsim_sem** and **nsim_sem_mpu_stack_guard** while running **tests/lib/mem_alloc/libraries.libc.newlib**.
> 
> Error message:
> 
> > zephyr/lib/libc/newlib/libc-hooks.c: In function 'malloc_prepare':
> > zephyr/lib/libc/newlib/libc-hooks.c:54:19: error: implicit declaration of function 'Z_ARC_MPU_SIZE_ALIGN'; did you mean 'Z_ARC_MPU_ALIGN'? [-Werror=implicit-function-declaration]
> > 54 | #define HEAP_BASE Z_ARC_MPU_SIZE_ALIGN(USED_RAM_END_ADDR)
> > |                   ^~~~~~~~~~~~~~~~~~~~
> > zephyr/lib/libc/newlib/libc-hooks.c:79:29: note: in expansion of macro 'HEAP_BASE'
> > 79 |  z_malloc_partition.start = HEAP_BASE;
> > |                             ^~~~~~~~~
> 
> (Z_ZRC_MPU_SIZE_ALIGN was previous defined in include/arch/arc/arch.h and is removed in this PR)

Confirmed, a recent change to the newlib code introduced this. I wonder how this got past CI, seems we have a testing gap. I pushed a fix and tested locally on the nsim targets, should be good.

**Comment by abrodkin** [comment]
> 
> 
> > @andrewboie @ruuddw , I ran some tests and no errors found at emsdp, iotdk, nsim_em, nsim_hs.
> > However there is one error found with both **nsim_sem** and **nsim_sem_mpu_stack_guard** while running **tests/lib/mem_alloc/libraries.libc.newlib**.
> > Error message:
> > > zephyr/lib/libc/newlib/libc-hooks.c: In function 'malloc_prepare':
> > > zephyr/lib/libc/newlib/libc-hooks.c:54:19: error: implicit declaration of function 'Z_ARC_MPU_SIZE_ALIGN'; did you mean 'Z_ARC_MPU_ALIGN'? [-Werror=implicit-function-declaration]
> > > 54 | #define HEAP_BASE Z_ARC_MPU_SIZE_ALIGN(USED_RAM_END_ADDR)
> > > |                   ^~~~~~~~~~~~~~~~~~~~
> > > zephyr/lib/libc/newlib/libc-hooks.c:79:29: note: in expansion of macro 'HEAP_BASE'
> > > 79 |  z_malloc_partition.start = HEAP_BASE;
> > > |                             ^~~~~~~~~
> > 
> > 
> > (Z_ZRC_MPU_SIZE_ALIGN was previous defined in include/arch/arc/arch.h and is removed in this PR)
> 
> Confirmed, a recent change to the newlib code introduced this. I wonder how this got past CI, seems we have a testing gap. I pushed a fix and tested locally on the nsim targets, should be good.

How that could be tested by us? I.e. just this PR as it is or there's a dependency on some other change for newlib?

**Comment by andrewboie** [comment]
> How that could be tested by us? I.e. just this PR as it is or there's a dependency on some other change for newlib?

`sanitycheck  -p nsim_sem -p nsim_em -p nsim_sem_mpu_stack_guard -T tests/lib/mem_alloc` should do the trick with this PR applied.

**Comment by dleach02** [comment]
@andrewboie, I ran the test on my frdm-k64f board and I'm getting an assert. Haven't had time to debug it yet but this is the message:

```
START - test_stack_buffer
Reserved space (thread stacks): 32
Reserved space (kernel stacks): 32
CONFIG_ISR_STACK_SIZE 2048
irq stack 0: 0x20001140 size 2080
Provided stack size: 512

testing user_stack
stack may host user thread, size in metadata is 544
Stack object 0x20001cc0[544]
 - Testing supervisor mode
   - Thread reports buffer 0x20001ce0 size 512
   - check read/write to stack buffer
   - Carved-out space in buffer: 0
   - Unused objects space: 0
self-reported unused stack space: 144
target thread unused stack space: 144
 - Testing user mode (direct launch)
   - Thread reports buffer 0x20001ce0 size 512
   - check read/write to stack buffer

    Assertion failed at ../src/main.c:187: stack_buffer_scenarios: (check_perms(stack_start - 1, 1, 0) is false)
user mode access to memory 0x20001cbf before start of stack object
 FAIL - test_stack_buffer
===================================================================
Test suite userspace failed.

```

**Comment by andrewboie** [comment]
@dleach02 thanks for testing, I think we have found an issue with the NXP MPU Implementation which we unfortuantely don't have emulator coverage. This assertion will fail if thread->stack_info is not set to the true bounds of the user stack region, or we have programmed the MPU not to exactly cover it. Suspecting the latter, digging deeper...

File: include/kernel.h [hunk 11]
```diff
@@ -527,11 +527,20 @@ struct _thread_stack_info {
...
+	 * the thread. This comprises of the thread stack area, any area reserved
+	 * for local thread data storage, as well as any area left-out due to
+	 * random adjustments applied to the initial thread stack pointer during
+	 * thread initialization.
 	 */
 	size_t size;
+
+	/* Adjustment value to the size member, removing any storage
+	 * used for TLS or random stack base offsets. (start + size - delta)
+	 * is the initial stack pointer for a thread. May be 0.
```
Comment (ioannisg) [inline include/kernel.h:541]: make it clear that "may be 0" refers to delta, not to the "initial stack pointer for a thread"

File: include/arch/arm/aarch32/arch.h [hunk 12]
```diff
@@ -150,98 +150,56 @@ extern "C" {
...
-#define ARCH_THREAD_STACK_ARRAY_DEFINE(sym, nmemb, size) \
-	struct z_thread_stack_element __noinit \
-		__aligned(STACK_ALIGN) \
-		sym[nmemb][ARCH_THREAD_STACK_LEN(size)]
+#ifdef CONFIG_MPU_STACK_GUARD
+/* Kernel-only stacks need an MPU guard region programmed at the beginning of
+ * the stack object, so align the object appropriately.
+ */
+#define ARCH_KERNEL_STACK_RESERVED	MPU_GUARD_ALIGN_AND_SIZE
+#define ARCH_KERNEL_STACK_OBJ_ALIGN	Z_MPU_GUARD_ALIGN
```
Comment (ioannisg) [inline include/arch/arm/aarch32/arch.h:176]: @andrewboie why is this not MAX(MAX(Z_THREAD_MIN_STACK_ALIGN, Z_MPU_GUARD_ALIGN) ??

File: include/arch/arm/aarch32/arch.h [hunk 13]
```diff
@@ -150,98 +150,56 @@ extern "C" {
...
-#if defined(CONFIG_USERSPACE) && \
-	defined(CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT)
-#define ARCH_THREAD_STACK_MEMBER(sym, size) \
-	struct z_thread_stack_element __aligned(POW2_CEIL(size)) \
-		sym[POW2_CEIL(size)]
-#else
-#define ARCH_THREAD_STACK_MEMBER(sym, size) \
-	struct z_thread_stack_element __aligned(STACK_ALIGN) \
-		sym[size+MPU_GUARD_ALIGN_AND_SIZE]
+/* On arm, the MPU guard can take a few different forms: completely
```
Comment (ioannisg) [inline include/arch/arm/aarch32/arch.h:179]: Arm

**Comment by andrewboie** [comment]
> 
> 
> @dleach02 thanks for testing, I think we have found an issue with the NXP MPU Implementation which we unfortuantely don't have emulator coverage. This assertion will fail if thread->stack_info is not set to the true bounds of the user stack region, or we have programmed the MPU not to exactly cover it. Suspecting the latter, digging deeper...

The culprit has been identified, and ARM now properly sets the stack MPU region based exactly on what's in thread->stack_info. Passing for me now on frdm_k64f with updated PR.

File: include/arch/arm/aarch32/arch.h (hunk 12 above)
Comment (andrewboie) [reply include/arch/arm/aarch32/arch.h:176]: It's like this because Z_MPU_GUARD_ALIGN is always equal to or larger than Z_THREAD_MIN_STACK_ALIGN.

Z_THREAD_MIN_STACK_ALIGN is defined as "Denotes the minimum required alignment of a thread stack." (not necessarily a kernel-only stack) and is either defined to the smallest MPU region (if userspace) or the stack pointer alignment (if not).

Z_MPU_GUARD_ALIGN is always the smallest MPU region necessary to program a guard:
```
#if defined(CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT)
#define Z_MPU_GUARD_ALIGN (MAX(MPU_GUARD_ALIGN_AND_SIZE, \
	MPU_GUARD_ALIGN_AND_SIZE_FLOAT))
#else
#define Z_MPU_GUARD_ALIGN MPU_GUARD_ALIGN_AND_SIZE
#endif
```

Z_MPU_GUARD_ALIGN is, by design, supposed to capture the necessary alignment to instantiate a stack guard at the lowest address. If it doesn't there is a problem with its definition.

File: include/kernel.h (hunk 11 above)
Comment (andrewboie) [reply include/kernel.h]: fixed.

File: doc/guides/porting/arch.rst [hunk 14]
```diff
@@ -478,38 +568,189 @@ To enable the :option:`CONFIG_HW_STACK_PROTECTION` feature, the system must
...
-* :c:macro:`_ARCH_THREAD_STACK_SIZEOF()`
+:option:`CONFIG_HW_STACK_PROTECTION` only catches stack overflows for
+supervisor threads. This is not required to catch stack overflow from user
+threads; :option:`CONFIG_USERSPACE` is orthogonal.
 
-For systems that implement stack protection using a Memory Protection Unit
-(MPU) or Memory Management Unit (MMU), this is typically done by declaring a
-guard memory region immediately before the stack area.
+This feature only detects supervisor mode stack overflows, it doesn't
+guarantee that the kernel is has not been corrupted. Any stack overflow
```
[the remark this answers is not in the document]
Comment (andrewboie) [reply doc/guides/porting/arch.rst]: fixed.

File: include/arch/arm/aarch32/arch.h (hunk 13 above)
Comment (andrewboie) [reply include/arch/arm/aarch32/arch.h]: fixed.

**Comment by andrewboie** [comment]
Updated based on @ioannisg comments.

Also, based on an offline discussion with @dleach02, I've simplified ARM to always have K_THREAD_STACK_RESERVED be 0. It's simpler this way since ARM is unconditionally generating separate privilege stacks.

File: include/arch/arm/aarch32/arch.h (hunk 12 above)
Comment (ioannisg) [reply include/arch/arm/aarch32/arch.h:176]: That's correct thanks. Hadn't seen the #ifdef CONFIG_MPU_STACK_GUARD on top.
By the way, why there is no #else here? Don't you want to have these arch specific defines in Arm arch.c when no guard feature is enabled ?

Comment (andrewboie) [reply include/arch/arm/aarch32/arch.h:176]: > By the way, why there is no #else here? Don't you want to have these arch specific defines in Arm arch.c when no guard feature is enabled ?

I'm not sure I understand what you mean.
If `CONFIG_MPU_STACK_GUARD` is not enabled, we don't need the other definitions like `Z_MPU_GUARD_ALIGN` as there are no stack guards programmed. All the C code logic for guards is also #ifdef'ed around `CONFIG_MPU_STACK_GUARD`. I could add #else cases defined as 0 I suppose but nothing would be using it.

The core kernel only uses the definitions prefixed with `ARCH_`.

Comment (andrewboie) [reply include/arch/arm/aarch32/arch.h:176]: It's fair to say that a lot of the intermediate definitions in this header are just feeding into getting the `ARCH_` definitions set right. This patch simplifies arch.h somewhat but there's probably more cleanup and proper namespacing that could be done.

**Comment by dleach02** [comment]
@andrewboie, I'm still working through the code on the Arm side but you indicate that the Arm is unconditionally creating separate privilege stacks. Does that mean that the image in the /docs of what the memory looks like for guards/privilege stack/user stack is incorrect? I'm thinking it is based on what I've seen being programmed in the NXP MPU.

**Comment by andrewboie** [comment]
> @andrewboie, I'm still working through the code on the Arm side but you indicate that the Arm is unconditionally creating separate privilege stacks. Does that mean that the image in the /docs of what the memory looks like for guards/privilege stack/user stack is incorrect? I'm thinking it is based on what I've seen being programmed in the NXP MPU.

The doc is a guide to the best known method for configuring this stuff for the different memory management hardware capabilities. It will not be too bad to convert ARM to the desired scheme, it has been done for ARC already, but @ioannisg and I discussed it and we agreed it could be a future fix after this lands, this PR is already very complex.

I wouldn't want to amend the documentation to the current ARM scheme since those docs are for bringing up new arches.

File: include/arch/arm/aarch32/arch.h (hunk 12 above)
Comment (ioannisg) [reply include/arch/arm/aarch32/arch.h:176]: Well, I meant to have something like: 
```
#else /* !CONFIG_MPU_STACK_GUARD */
#define ARCH_KERNEL_STACK_OBJ_ALIGN	ARCH_STACK_PTR_ALIGN
#endif
```

I guess this is not an issue because if ARCH_KERNEL_STACK_OBJ_ALIGN is not defined then Z_KERNEL_STACK_OBJ_ALIGN is already set to ARCH_STACK_PTR_ALIGN the kernel header. But for ease of reading it would be nice if the arm arch.h already defines the ARCH_KERNEL_STACK_OBJ_ALIGN in all scenarios.

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c [hunk 15]
```diff
@@ -209,9 +209,8 @@ void z_arm_configure_dynamic_mpu_regions(struct k_thread *thread)
 	LOG_DBG("configure user thread %p's context", thread);
 	if (thread->arch.priv_stack_start) {
 		/* K_USER thread stack needs a region */
-		uint32_t base = (uint32_t)thread->stack_obj;
-		uint32_t size = thread->stack_info.size +
-			(thread->stack_info.start - base);
+		uint32_t base = (uint32_t)thread->stack_info.start;
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:212]: Yeap, this is now required, since stack_info.start and .size are, now, modified, when the thread enters user mode.
Should we add an ASSERT that thread->stack_obj equals stack_info.start?

File: doc/guides/porting/arch.rst [hunk 16]
```diff
@@ -460,8 +460,97 @@ be derived from the linker scripts of other architectures. Some sections might
...
+stack pointer, which is some combination of CPU and ABI requirements. This
+is defined in architecture headers with :c:macro:`ARCH_STACK_PTR_ALIGN` and
+is typically something small like 4, 8, or 16 bytes.
+
+Two types of thread stacks exist:
+
+- "kernel" stacks defined with :c:macro:`K_KERNEL_STACK_DEFINE()` and related
+  APIs, which can host kernel threads running in supervisor mode or
+  used as the stack for interrupt/exception handling. These have significantly
+  relaxed alignment requirements and use less reserved data.
```
Comment (ioannisg) [inline doc/guides/porting/arch.rst:484]: Well, actually it is not only that: the main point is that the script that generates a privilege stack for each defined thread stack _skips_ doing it for kernel stacks. Maybe worth mentioning.

File: doc/guides/porting/arch.rst [hunk 17]
```diff
@@ -460,8 +460,97 @@ be derived from the linker scripts of other architectures. Some sections might
...
+
+Stack objects all have the following layout, with some regions potentially
+zero-sized depending on configuration. There are always two main parts:
+reserved memory at the beginning, and then the stack buffer itself. The
+bounds of some areas can only be determined at runtime in the context of
+its associated thread object. Other areas are entirely computable at build
+time.
+
+Some architectures may need to carve-out reserved memory at runtime from the
+stack buffer, instead of unconditionally reserving it at build time.
```
Comment (ioannisg) [inline doc/guides/porting/arch.rst:517]: In some use-cases, it is not "instead of" but "besides", right? Cause we do both. E.g. for FPU_SHARING in ARM

File: doc/guides/porting/arch.rst [hunk 18]
```diff
@@ -478,38 +568,189 @@ To enable the :option:`CONFIG_HW_STACK_PROTECTION` feature, the system must
...
+Two forms of HW-based stack overflow detection are supported: dedicated
+CPU features for this purpose, or special read-only guard regions immediately
+preceding stack buffers.
 
-* :c:macro:`_ARCH_THREAD_STACK_DEFINE()`
-* :c:macro:`_ARCH_THREAD_STACK_ARRAY_DEFINE()`
-* :c:macro:`_ARCH_THREAD_STACK_MEMBER()`
-* :c:macro:`_ARCH_THREAD_STACK_SIZEOF()`
+:option:`CONFIG_HW_STACK_PROTECTION` only catches stack overflows for
+supervisor threads. This is not required to catch stack overflow from user
```
Comment (ioannisg) [inline doc/guides/porting/arch.rst:576]: Agree, but maybe clarify that user threads during system calls do require to catch stack overflows. Effectively, during sys calls they are sup threads, but maybe clarify this.

File: doc/guides/porting/arch.rst [hunk 19]
```diff
@@ -478,38 +568,189 @@ To enable the :option:`CONFIG_HW_STACK_PROTECTION` feature, the system must
...
+  be able to be placed before it, with support for carve-outs if necessary.
+
+* The memory protection hardware must be able to program a region that exactly
+  covers the thread's stack buffer, tracked in ``thread.stack_info``. This
+  implies that :c:macro:`ARCH_THREAD_STACK_SIZE_ADJUST()` will need to round
+  up the requested stack size so that a region may cover it, and that
+  :c:macro:`ARCH_THREAD_STACK_OBJ_ALIGN()` is also specified per the
+  granularity of the memory protection hardware.
+
+This become more complicated if the memory protection hardware requires that
```
Comment (ioannisg) [inline doc/guides/porting/arch.rst:652]: becomes*

File: doc/guides/porting/arch.rst [hunk 20]
```diff
@@ -478,38 +568,189 @@ To enable the :option:`CONFIG_HW_STACK_PROTECTION` feature, the system must
...
+read-only region when the thread is created.
+
+* If the thread is a supervisor thread, the privilege elevation region is just
+  extra stack memory. An overflow will eventually crash into the guard region.
+
+* If the thread is running in user mode, a memory protection region will be
+  configured to allow user threads access to the stack buffer, but nothing
+  before or after it. An overflow in user mode will crash into the privilege
+  elevation stack, which the user thread has no access to. An overflow when
+  handling a system call will crash into the guard region.
```
Comment (ioannisg) [inline doc/guides/porting/arch.rst:692]: Maybe worth stating that in _this_ case we not only detect the overflows, but protect the kernel from corruption. Maybe implicit, or maybe worth mentioning

File: include/sys/thread_stack.h [hunk 21]
```diff
@@ -61,31 +100,204 @@ struct __packed z_thread_stack_element {
...
+
+#define K_KERNEL_STACK_SIZEOF(sym) (sizeof(sym) - K_KERNEL_STACK_RESERVED)
+
+static inline char *Z_KERNEL_STACK_BUFFER(k_thread_stack_t *sym)
 {
-	return ARCH_THREAD_STACK_BUFFER(sym);
+	return (char *)sym + K_KERNEL_STACK_RESERVED;
 }
+#ifndef CONFIG_USERSPACE
+#define K_THREAD_STACK_RESERVED		K_KERNEL_STACK_RESERVED
```
Comment (ioannisg) [inline include/sys/thread_stack.h:172]: fix indentation

**Comment by ioannisg** [comment]
> Updated based on @ioannisg comments.
> 
> Also, based on an offline discussion with @dleach02, I've simplified ARM to always have K_THREAD_STACK_RESERVED be 0. It's simpler this way since ARM is unconditionally generating separate privilege stacks.

@andrewboie although, I am not against this simplification, I'd like to point out that now K_THREAD_STACK_RESERVED for ARMv8-M, will be 32 when CONFIG_USERSPACE=n and 0 when CONFIG_USERSPACE=y, while the HW does not impose any relevant constraints that justify this difference. This might be confusing for a developer that builds his code with / without USERSPACE enabled and sees different available stack for their _supervisor_ threads (assuming that they use K_THREAD_STACK_DEFINE).

We had always been treating the (CONFIG_USERSPACE && CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT) as _the_ special case.

File: doc/guides/porting/arch.rst [hunk 22]
```diff
@@ -478,38 +568,189 @@ To enable the :option:`CONFIG_HW_STACK_PROTECTION` feature, the system must
...
+   +------------------------------+
+   | Guard region (if enabled)    |
+   +------------------------------+
+   | Guard carve-out (if needed)  |
+   |..............................|
+   | Privilege elevation stack    |
+   +------------------------------| <- thread.stack_obj +
+   | Stack buffer                 |      K_THREAD_STACK_RESERVED =
+   .                              .      thread.stack_info.start
+
```
Comment (dleach02) [inline doc/guides/porting/arch.rst:681]: @andrewboie @ioannisg 

Is this diagram correct for Arm platforms? In the discussion thread Andrew commented "It's simpler this way since ARM is unconditionally generating separate privilege stacks". And from what I can see the Arm thread privilege stack is coming from a separate object (haven't quite wrapped my head around that).

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 15 above)
Comment (andrewboie) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:212]: No I do not think we should do that. It would break things if, for example, we moved the privilege elevation stack within the object.

File: include/sys/thread_stack.h (hunk 21 above)
Comment (andrewboie) [reply include/sys/thread_stack.h:172]: I see no problem with indentation in my text editor (VS Code) can you elaborate.

File: doc/guides/porting/arch.rst (hunk 22 above)
Comment (andrewboie) [reply doc/guides/porting/arch.rst:681]: As I said earlier: The doc is a guide to the best known method for configuring this stuff for the different memory management hardware capabilities.

Arm isn't currently following the best known method. It generates separate privilege mode stacks for all ARM platforms.

I do not want to change the diagrams in the porting guide to reflect the current state of ARM as that would give people doing new arch ports the wrong idea.

File: doc/guides/porting/arch.rst (hunk 17 above)
Comment (andrewboie) [reply doc/guides/porting/arch.rst:517]: I changed to "Some architectures may need to carve-out reserved memory at runtime from the
stack buffer, instead of unconditionally reserving it at build time, or to
supplement an existing reserved area (as is the case with the ARM FPU)."

> > Updated based on @ioannisg comments.
> > Also, based on an offline discussion with @dleach02, I've simplified ARM to always have K_THREAD_STACK_RESERVED be 0. It's simpler this way since ARM is unconditionally generating separate privilege stacks.
> 
> @andrewboie although, I am not against this simplification, I'd like to point out that now K_THREAD_STACK_RESERVED for ARMv8-M, will be 32 when CONFIG_USERSPACE=n and 0 when CONFIG_USERSPACE=y, while the HW does not impose any relevant constraints that justify this difference. This might be confusing for a developer that builds his code with / without USERSPACE enabled and sees different available stack for their _supervisor_ threads (assuming that they use K_THREAD_STACK_DEFINE).
> 
> We had always been treating the (CONFIG_USERSPACE && CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT) as _the_ special case.
> 
> If you do this simplification, it means you favor consistency across the different cortex-m variants.
> But maybe it is better to favor consistency across building with/without USERSPACE for each cortex-m variant.
> In both cases you need to sacrifice something.

I'd like to know what you would like me to do to move forward.

If we reserve data, then we have two guard regions, one in the privilege stack and one in the regular stack, with the regular stack guard wasted when the thread drops to user mode.

If we do not reserve data, then the situation is as described above.

IMO the right way to fix this is to convert ARM to not use privilege mode stack generation when it doesn't need to, which I believe we agreed was the next step.

File: doc/guides/porting/arch.rst (hunk 20 above)
Comment (andrewboie) [reply doc/guides/porting/arch.rst:692]: I don't think this deep into an example of one way to configure the stack object layout is the best place to expand on this topic.

File: include/sys/thread_stack.h (hunk 21 above)
Comment (andrewboie) [reply include/sys/thread_stack.h:172]: https://imgur.com/a/oCTMJvY

**Comment by andrewboie** [comment]
> > Updated based on @ioannisg comments.
> > Also, based on an offline discussion with @dleach02, I've simplified ARM to always have K_THREAD_STACK_RESERVED be 0. It's simpler this way since ARM is unconditionally generating separate privilege stacks.
> 
> @andrewboie although, I am not against this simplification, I'd like to point out that now K_THREAD_STACK_RESERVED for ARMv8-M, will be 32 when CONFIG_USERSPACE=n and 0 when CONFIG_USERSPACE=y, while the HW does not impose any relevant constraints that justify this difference. This might be confusing for a developer that builds his code with / without USERSPACE enabled and sees different available stack for their _supervisor_ threads (assuming that they use K_THREAD_STACK_DEFINE).
> 
> We had always been treating the (CONFIG_USERSPACE && CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT) as _the_ special case.
> 
> If you do this simplification, it means you favor consistency across the different cortex-m variants.
> But maybe it is better to favor consistency across building with/without USERSPACE for each cortex-m variant.
> In both cases you need to sacrifice something.

I need direction on what we need to do for this PR to get it merged.

If we reserve data, then there is a guard instantiated in two places, with the one in the stack object wasted when we drop to user mode. If we don't, we have the above situation.

The proper fix in my view is to convert ARM to not generate privilege stacks when it shouldn't, which I believe we agreed to do after this PR. If there's something you would like me to do for this PR to ease your concerns please share it.

File: doc/guides/porting/arch.rst (hunk 16 above)
Comment (andrewboie) [reply doc/guides/porting/arch.rst]: now reads: "These have significantly relaxed alignment requirements and use less reserved data. No memory is reserved for prvilege elevation stacks."

File: doc/guides/porting/arch.rst (hunk 20 above)
Comment (andrewboie) [reply doc/guides/porting/arch.rst:695]: I can put some detail in the toplevel "HW-based stack overflow detection" section though

Comment (andrewboie) [reply doc/guides/porting/arch.rst:695]: I added "Stack overflows in user mode are recoverable (from the kernel's perspective)
and require no special configuration; :option:`CONFIG_HW_STACK_PROTECTION`
only applies to catching overflows when the CPU is in sueprvisor mode.

File: doc/guides/porting/arch.rst (hunk 18 above)
Comment (andrewboie) [reply doc/guides/porting/arch.rst:578]: Next paragraph now reads: "This feature only detects supervisor mode stack overflows, including stack
overflows when handling system calls"

File: doc/guides/porting/arch.rst (hunk 19 above)
Comment (andrewboie) [reply doc/guides/porting/arch.rst]: fixed

File: doc/guides/porting/arch.rst (hunk 22 above)
Comment (andrewboie) [reply doc/guides/porting/arch.rst:684]: This is the bug link for this ARM issue: https://github.com/zephyrproject-rtos/zephyr/issues/24048

Comment (dleach02) [reply doc/guides/porting/arch.rst:684]: Understand. Thank you for the clarification (and confirmation).

File: include/sys/thread_stack.h (hunk 21 above)
Comment (dleach02) [reply include/sys/thread_stack.h:172]: @ioannisg, I think this is a side affect of github defaulting the tabs to 4 and @andrewboie using tabs between words. There is some sort of addon you can use to get this github display to use 8 for tabs or Andrew could use spaces between words. I'm not sure though what our general style guide is on this part.

Comment (ioannisg) [reply include/sys/thread_stack.h:172]: Yeap, if so, please disregard :)

**Review by dleach02 — APPROVED** [review]

File: arch/arm/core/aarch32/thread.c [hunk 23]
```diff
@@ -29,112 +36,67 @@
...
-			- MPU_GUARD_ALIGN_AND_SIZE;
-		stackSize -= MPU_GUARD_ALIGN_AND_SIZE_FLOAT
-			- MPU_GUARD_ALIGN_AND_SIZE;
+	struct __basic_sf *iframe;
+
+#ifdef CONFIG_MPU_STACK_GUARD
+#if defined(CONFIG_USERSPACE) && \
+		defined(CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT)
+	if (z_stack_is_user_capable(stack)) {
+		/* Guard area is carved-out of the buffer, instead of reserved,
```
Comment (ioannisg) [inline arch/arm/core/aarch32/thread.c:48]: @andrewboie is this now needed for the other ARM variants, too?
Just double-checking..

**Review by ioannisg — APPROVED** [review]
Approving this, assuming @andrewboie will fix the last issue spotted.

For issues that might occur, there's plenty of time to fix until release.

File: arch/arm/core/aarch32/thread.c (hunk 23 above)
Comment (andrewboie) [reply arch/arm/core/aarch32/thread.c]: Addressed now.
Missed this in testing as we lack an ARMv8 target with SPLIM disabled that runs tests/kernel/threads/thread_stack

**Review by jenmwms — APPROVED** [review]

**Comment by maksimmasalski** [comment]
@andrewboie Does that fixes #26865 ?

**Comment by andrewboie** [comment]
@maksimmasalski no it does not but I'll find some time for it this week, easy fix
