### PR TITLE
Bluetooth: Controller: nrf54lx: Fix address resolution wait

### LINKED ISSUE #100101: BLE device bricked after disconnect with CONFIG_BT_APP_PASSKEY=y on nRF54L15 (Zephyr 4.3.0)
### Describe the bug

**Summary**
After enabling CONFIG_BT_APP_PASSKEY=y, the device becomes bricked after each BLE disconnect on nRF54L15. Even after reset and BLE initialization, the core enters a bricked state—only erasing firmware helps.
Environment

Zephyr version: 4.3.0
Hardware: Nordic nRF54L15
Configuration: BLE with passkey enabled

**Steps to Reproduce**

Enable `CONFIG_BT_APP_PASSKEY=y `in prj.conf
Build and flash the application
Connect via BLE and disconnect
Observe device becomes unresponsive

**Expected Behavior**
Device should handle BLE disconnections gracefully and remain responsive.
**Actual Behavior**
Device enters a bricked state after disconnect. Debugger shows the core stuck in an infinite loop.
Troubleshooting Attempted

Disabled `CONFIG_BT_SETTINGS=n` → No effect
Disabled `CONFIG_BT_CTLR_PRIVACY=n `→ Resolves the issue (but not ideal)

**Debug Output**
The core is stuck in an infinite loop in 
`zephyr/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c`
in the radio_ar_has_match() function:

```
uint32_t radio_ar_has_match(void)
{
	if (!radio_bc_has_match()) {
		return 0U;
	}

	nrf_aar_int_enable(NRF_AAR, AAR_INTENSET_END_Msk);

	// Infinite loop - never returns:
	while (NRF_AAR->EVENTS_END == 0U) {
		cpu_sleep();
	}

	nrf_aar_int_disable(NRF_AAR, AAR_INTENCLR_END_Msk);
	NVIC_ClearPendingIRQ(nrfx_get_irq_number(NRF_AAR));

	if (NRF_AAR->EVENTS_RESOLVED && !NRF_AAR->EVENTS_NOTRESOLVED) {
		return 1U;
	}

	return 0U;
}
```

The `NRF_AAR->EVENTS_END` event never gets set, causing the `cpu_sleep()` loop to never exit.
**Current Workaround**
Disable privacy:
properties `CONFIG_BT_CTLR_PRIVACY=n`
This resolves the issue but likely disables an important security feature.

### PR DESCRIPTION
**Pull request by cvinayak**
Fix address resolution wait to not be infinite loop and instead exit with a reasonable count down value.

Fixes #100101

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 1]
```diff
@@ -2723,6 +2723,23 @@ void radio_ar_status_reset(void)
...
+	 */
+	uint32_t countdown = 200U;
+
+	while ((NRF_AAR->EVENTS_END == 0U) && (countdown != 0U)) {
+		countdown--;
+
+#if !defined(CONFIG_SOC_SERIES_NRF54LX)
+		/* We do not sleep on target SoC. */
+		cpu_sleep();
+#endif /* !CONFIG_SOC_SERIES_NRF54LX */
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: IS_ENABLED?

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 2]
```diff
@@ -2723,6 +2723,23 @@ void radio_ar_status_reset(void)
 	hal_radio_nrf_ppi_channels_disable(BIT(HAL_TRIGGER_AAR_PPI));
 }
 
+static void ar_end_wait(void)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:2696]: What is `ar`? :)

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:2696]: Address Resolution.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 3]
```diff
@@ -2693,6 +2723,25 @@ void radio_ar_status_reset(void)
...
+	/* An arbitrary iteration which seems sufficient testing on target with one IRK to resolve.
+	 * We should ideally be not be waiting anyway, and in theory be resolved before we are here.
+	 */
+	uint32_t countdown = 200U;
+
+	while ((NRF_AAR->EVENTS_END == 0U) && (countdown != 0U)) {
+		countdown--;
+
+		/* We do not sleep on target SoC. */
+		if (!IS_ENABLED(CONFIG_SOC_SERIES_NRF54LX)) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Should this be


```suggestion
	/* We do not sleep on target SoC. */
	if (!IS_ENABLED(CONFIG_SOC_SERIES_NRF54LX)) {
		while ((NRF_AAR->EVENTS_END == 0U) && (countdown != 0U)) {
			countdown--;

```

The `while` loop doesn't really do anything when `CONFIG_SOC_SERIES_NRF54LX=y` except iterating 200 without a `cpu_sleep()` (which the compiler may actually remove anyways?)

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: You are right... I will follow up on this.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 4]
```diff
@@ -2723,6 +2723,23 @@ void radio_ar_status_reset(void)
 	hal_radio_nrf_ppi_channels_disable(BIT(HAL_TRIGGER_AAR_PPI));
 }
 
+static void ar_end_wait(void)
+{
+	/* An arbitrary iteration which seems sufficient testing on target with one IRK to resolve.
+	 * We should ideally be not be waiting anyway, and in theory be resolved before we are here.
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: done

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 5]
```diff
@@ -2723,6 +2723,23 @@ void radio_ar_status_reset(void)
...
+	 */
+	uint32_t countdown = 200U;
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:2703]: Keeping as-is for now.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 6]
```diff
@@ -2723,6 +2723,25 @@ void radio_ar_status_reset(void)
...
+
+	while ((NRF_AAR->EVENTS_END == 0U) && (countdown != 0U)) {
+		countdown--;
+
+		/* We do not sleep on target SoC. */
+		if (!IS_ENABLED(CONFIG_SOC_SERIES_NRF54LX)) {
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Correct use of not to sleep on target. we will sleep in simulation platforms.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: ok .`NRF_AAR->EVENTS_END` has `volatile` scope and compiler will not optimize the loop.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 7]
```diff
@@ -2723,6 +2723,23 @@ void radio_ar_status_reset(void)
...
+
+	while ((NRF_AAR->EVENTS_END == 0U) && (countdown != 0U)) {
+		countdown--;
+
+#if !defined(CONFIG_SOC_SERIES_NRF54LX)
+		/* We do not sleep on target SoC. */
+		cpu_sleep();
+#endif /* !CONFIG_SOC_SERIES_NRF54LX */
+	}
+}
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:2716]: This is ok... `radio_ar_has_match()` will be used by caller to check the results of the address resolution.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Not sure I understand your comment - Can you elaborate?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: defined as `__IOM uint32_t EVENTS_END;` in the `NRF_AAR_Type` structure, where `__IOM` is `#define __IOM    volatile`

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: I need more information :)

What I suggested was to put the entire loop inside `IS_ENABLED(CONFIG_SOC_SERIES_NRF54LX)`, instead of having the entire loop content inside `IS_ENABLED(CONFIG_SOC_SERIES_NRF54LX)`. It's cleaner and more readable

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: The loop is needed for all target SoCs (and all bsim targets including nrf54l15bsim) except that nRF54L15 SoC silicon shall not CPU sleep.

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Aaah, I see that 

```c
	while (NRF_AAR->EVENTS_END == 0) {
		cpu_sleep();
	}
```

Was moved now. Thought it made no sense to have a while loop just to sleep, and that it was an error ⁠

In that case it makes sense, but we really should have a comment explaining why we have a loop just doing cpu_sleep() for the other platforms

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Update: I do see that we actually have that already, so never mind :D

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: I do still think it makes sense to put the `IS_ENABLED` as an outer check; even if `compiler will not optimize the loop.` is true, then it's an improvement in readability IMO (but not a blocker)

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Actually even if `NRF_AAR->EVENTS_END has volatile scope and compiler will not optimize the loop.` is true, wouldn't it still be optimized in terms of CPU size since it's effectively behind a `if (0)` even if the code size doesn't change due to `volatile`?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Add some explanation.

**Review by Thalley — APPROVED** [review]

**Review by aescolar — APPROVED** [review]
