### PR TITLE
eSPI: Userspace and API fixes

### LINKED ISSUE #23750: eSPI API needs to be updated since it's passing parameters by value
Several eSPI API functions are passing parameters by value instead by reference.
This won;t work if a board supports eSPI and MPU

### PR DESCRIPTION
**Pull request by ceolin**
* Implement missing verification handler
* Fix two implementation handler names
* Pass struct by reference in syscall APIs

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/23750

### CODE REVIEW

File: drivers/espi/espi_handlers.c [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+
+       return z_impl_espi_receive_vwire(dev, signal, level);
+}
+#include <syscalls/espi_receive_vwire_mrsh.c>
+
+static inline int z_vrfy_espi_read_request(struct device *dev,
+					   struct espi_request_packet *req)
+{
+       Z_OOPS(Z_SYSCALL_DRIVER_ESPI(dev, read_request));
+       Z_OOPS(Z_SYSCALL_MEMORY_WRITE(req, sizeof(*req)));
```
Comment (andrewboie) [inline drivers/espi/espi_handlers.c]: you need to copy. otherwise TOCTOU attacks on req->data are possible.

File: drivers/espi/espi_handlers.c [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+       return z_impl_espi_read_request(dev, req);
+}
+#include <syscalls/espi_read_request_mrsh.c>
+
+static inline int z_vrfy_espi_write_request(struct device *dev,
+					    struct espi_request_packet *req)
+{
+       Z_OOPS(Z_SYSCALL_DRIVER_ESPI(dev, read_request));
+       Z_OOPS(Z_SYSCALL_MEMORY_READ(req, sizeof(*req)));
+       Z_OOPS(Z_SYSCALL_MEMORY_READ(req->data, req->len));
```
Comment (andrewboie) [inline drivers/espi/espi_handlers.c]: same as above

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
any time you validate something inside a struct passed to the syscall by reference, requires that struct to be copied first. otherwise TOCTOU attacks could occur since the calling context can modify it at any time.

File: drivers/espi/espi_handlers.c (hunk 2 above)
Comment (andrewboie) [reply drivers/espi/espi_handlers.c]: there's more, a lot of these need to be modified.

Comment (ceolin) [reply drivers/espi/espi_handlers.c]: Oww indeed, I was sure I was missing something. Thanks for pointing it.

Comment (ceolin) [reply drivers/espi/espi_handlers.c]: Btw that is one thing that I was thinking about. We really need to copy_to/from in these structs with pointers fields since we don't want end up writing/reading invalid memory due TOCTOU.
But all pointers are potentially problematic, we will of course ensure that the calling thread has right permission to that address but the pointer contents can be successive to TOCTOU right ?

I *think* Linux always copy_to/from pointers in syscalls

File: drivers/espi/espi_handlers.c [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+#include <syscalls/espi_get_channel_status_mrsh.c>
+
+static inline int z_vrfy_espi_read_lpc_request(struct device *dev,
+					       enum lpc_peripheral_opcode op,
+					       u32_t *data)
+{
+       Z_OOPS(Z_SYSCALL_DRIVER_ESPI(dev, read_lpc_request));
+       Z_OOPS(Z_SYSCALL_MEMORY_WRITE(data, sizeof(*data)));
+
+       return z_impl_espi_read_lpc_request(dev, op, data);
```
Comment (franciscomunoz) [inline drivers/espi/espi_handlers.c]: @Ceolin It is Friday and I would like to ask a dump question.  Function `espi_read_lpc_request` is has the out parameter `data`.  I've started looking at a few syscalls in linux (https://elixir.bootlin.com/linux/latest/source/kernel/sys.c) and for out parameters each syscall call first creates a temp variable in their execution context, then perform the underlying function call. Afterwards, the information from the temp variable is passed to the client using copy_to_user.  Shouldn't we be doing the same for out parameters? By the way I really appreciate the time you guys are investing on this !

Comment (ceolin) [reply drivers/espi/espi_handlers.c]: Hey, that is not dumb at all :) Andrew asked me to fix it in this PR.

Creating a temporary variable we protects against TOCTOU. For example, we have a struct with a buffer, during the verification we check if the caller has access to the struct memory and to the buffer, but if we don't make copies, it is possible to other thread with access to that struct change the buffer's address to point to something that the caller has no access but as the copy will occur in kernel mode this will succeed .

Comment (andrewboie) [reply drivers/espi/espi_handlers.c]: > Hey, that is not dumb at all :) Andrew asked me to fix it in this PR.

Well, I had noted some issues with input parameters, but I think there is an issue with syscalls that have out parameters, and not just with this PR.

For syscalls that have output memory buffers, a lot of them currently do Z_SYSCALL_MEMORY_WRITE() on an out parameter before invoking the implementation function, and pass the out pointer directly to it.

This verifies that the caller has access to this memory, but may be unsafe. It should be safe if the output parameter is truly only used for output by the implementation. That is to say, this output buffer is ONLY written to, never read.

But if the system call uses this memory for internal working state, it's possible that there are preemption or SMP scenarios where this working state could get corrupted by some thread that has access to this memory, causing undefined behavior which at worst case could crash the kernel.

In addition, to properly implement in the future security features like SMAP, the kernel should never touch user memory at all except in designated copy_to_user()/copy_from_user() functions.

@ceolin I think we need to audit our system calls that have out parameters and change verifiers that look like this:

```
int z_vrfy_some_syscall(int *out_param)
{
    Z_OOPS(Z_SYSCALL_MEMORY_WRITE(out_param));
    return z_impl_some_syscall(out_param);
}
```
to
```
int z_vrfy_some_syscall(int *out_param)
{
    int local_out_param;
    int ret;
  
    ret = z_impl_some_syscall(&local_out_param);
	Z_OOPS(z_user_to_copy(out_param, &local_out_param, sizeof(*out_param)));
    return ret;
}
```
This might be a lot of syscalls that need to be fixed. I'll open a GH issue.

Comment (andrewboie) [reply drivers/espi/espi_handlers.c]: https://github.com/zephyrproject-rtos/zephyr/issues/23877

File: drivers/espi/espi_handlers.c (hunk 2 above)
Comment (andrewboie) [reply drivers/espi/espi_handlers.c]: > I think Linux always copy_to/from pointers in syscalls

Yes I believe we need to do the same.

**Review by albertofloyd — COMMENTED** [review]
eSPI API and driver code changes look good.
However, when running sample code it fails in OOB portion, debug in progress.

**Comment by ceolin** [comment]
> eSPI API and driver code changes look good.
> However, when running sample code it fails in OOB portion, debug in progress.

Can you show the log ? It is in the send or receive function ?

**Comment by ceolin** [comment]
@andrewboie just updated all verification handlers, could you please take a look again

**Comment by albertofloyd** [comment]
> eSPI API and driver code changes look good.
> However, when running sample code it fails in OOB portion, debug in progress.

Problem is unrelated to these changes

**Review by albertofloyd — APPROVED** [review]

File: drivers/espi/espi_handlers.c [hunk 4]
```diff
@@ -0,0 +1,226 @@
...
+static inline int z_vrfy_espi_write_lpc_request(struct device *dev,
+						enum lpc_peripheral_opcode op,
+						u32_t *data)
+{
+	u32_t data_copy;
+
+	Z_OOPS(Z_SYSCALL_DRIVER_ESPI(dev, write_lpc_request));
+	Z_OOPS(Z_SYSCALL_MEMORY_READ(data, sizeof(*data)));
+
+	data_copy = *data;
```
Comment (andrewboie) [inline drivers/espi/espi_handlers.c]: slightly better to remove the "Z_OOPS(Z_SYSCALL_MEMORY_READ(data, sizeof(*data)))" line and just use `z_user_to_copy()`

File: drivers/espi/espi_handlers.c [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+static inline int z_vrfy_espi_write_request(struct device *dev,
+					    struct espi_request_packet *req)
+{
+	int ret;
+	struct  espi_request_packet req_copy;
+
+	Z_OOPS(Z_SYSCALL_DRIVER_ESPI(dev, write_request));
+	Z_OOPS(z_user_from_copy(&req_copy, req,
+				sizeof(struct espi_request_packet)));
+	Z_OOPS((req_copy.data = z_user_alloc_from_copy(req->data, req->len))
```
Comment (andrewboie) [inline drivers/espi/espi_handlers.c]: I'm not comfortable with all the heap allocations here and in other verification functions. Are they absolutely necessary?

Also any heap error should never Z_OOPS(), at most return -ENOMEM

File: drivers/espi/espi_handlers.c [hunk 6]
```diff
@@ -0,0 +1,226 @@
...
+	return z_impl_espi_send_vwire(dev, signal, level);
+}
+#include <syscalls/espi_send_vwire_mrsh.c>
+
+static inline int z_vrfy_espi_receive_vwire(struct device *dev,
+					    enum espi_vwire_signal signal,
+					    u8_t *level)
+{
+	Z_OOPS(Z_SYSCALL_DRIVER_ESPI(dev, receive_vwire));
+	Z_OOPS(Z_SYSCALL_MEMORY_WRITE(level, sizeof(*level)));
```
Comment (andrewboie) [inline drivers/espi/espi_handlers.c]: is level an input or output parameter?
if output you can just use `z_user_to_copy()`

File: drivers/espi/espi_handlers.c (hunk 5 above)
Comment (ceolin) [reply drivers/espi/espi_handlers.c]: I was not sure about it too. The only thing doing that is that a lot of syscalls will may return ENOMEM now. Btw, I've asked it in the ticket you've opened.

Comment (ceolin) [reply drivers/espi/espi_handlers.c]: these buffers are user memory, these are the ones that we must copy. Otherwise it may happen of another thread change this inner buffer to point to a memory that the caller has no access and it will succeed.

File: drivers/espi/espi_handlers.c (hunk 6 above)
Comment (ceolin) [reply drivers/espi/espi_handlers.c]: will change that.

File: drivers/espi/espi_handlers.c (hunk 5 above)
Comment (ceolin) [reply drivers/espi/espi_handlers.c]: @andrew another problem in returning ENOMEM is how to propagate it in void syscalls

Comment (ceolin) [reply drivers/espi/espi_handlers.c]: > these buffers are user memory, these are the ones that we must copy. Otherwise it may happen of another thread change this inner buffer to point to a memory that the caller has no access and it will succeed.

this assumption is wrong, we have already copied the address to the local variable. But another thread still can tamper the buffer's contents.

Comment (andrewboie) [reply drivers/espi/espi_handlers.c:117]: Oops I hit edit instead of replying.

Anyway, "but another thread still can tamper the buffer's contents." I don't see this as a problem. Can you expand if you disagree?

Comment (ceolin) [reply drivers/espi/espi_handlers.c:117]: From my understanding it is the same reason we have to make a copy of parameters passed by reference. Lets take this example:
```
static inline int z_vrfy_espi_config(struct device *dev, struct espi_cfg *cfg)
{
	struct  espi_cfg cfg_copy;

	Z_OOPS(Z_SYSCALL_DRIVER_ESPI(dev, config));
	Z_OOPS(z_user_from_copy(&cfg_copy, cfg,
				sizeof(struct espi_cfg)));

	return z_impl_espi_config(dev, &cfg_copy);
}
```
Here we make a `cfg` copy because the implementation will use it to configuration and in this case if another thread change `cfg` values we will end up having a problem, that can be just a misconfiguration or something else. One function could use a given buffer to do the same kind of work, for instance one drive needs a blob to configure itself. But as you have  showed me, the policy is the implementation don't do logical  decisions based on given buffer, so we just need to ensure that everybody is following it (that I believe is the case)

File: drivers/espi/espi_handlers.c (hunk 6 above)
Comment (ceolin) [reply drivers/espi/espi_handlers.c:80]: I've kept this one, It is better to check memory permission before calling the implementation because if the memory is invalid we don't even make the call.

**Comment by ceolin** [comment]
@andrewboie could you take a look again ? I've kept some of the memory check instead of using z_user_to_copy to avoid call the implementation handler if the given memory is invalid

File: drivers/espi/espi_handlers.c [hunk 7]
```diff
@@ -0,0 +1,213 @@
...
+{
+	int ret;
+	u32_t data_copy;
+
+	Z_OOPS(Z_SYSCALL_DRIVER_ESPI(dev, read_lpc_request));
+	Z_OOPS(Z_SYSCALL_MEMORY_WRITE(data, sizeof(*data)));
+
+	ret = z_impl_espi_read_lpc_request(dev, op, &data_copy);
+
+	*data = data_copy;
```
Comment (andrewboie) [inline drivers/espi/espi_handlers.c:44]: should just do z_user_to_copy() here and omit the Z_SYSCALL_MEMORY_WRITE above.

Comment (ceolin) [reply drivers/espi/espi_handlers.c:44]: @andrewboie  if I do that I'll need to call `z_impl_espi_read_lpc_request` even if the given memory was invalid, because the check will occur after the call. It seems better to check the memory before the call so we don't execute it if the parameter is invalid. Don't you think ?

Comment (andrewboie) [reply drivers/espi/espi_handlers.c:44]: Is that actually a requirement? Please think about this, I don't actually believe it is.

Consider later modifications to support SMAP where user memory access is strictly controlled through accessor functions instead of `*data = data_copy`

Comment (ceolin) [reply drivers/espi/espi_handlers.c:44]: that is not a requirement *I think*, though it is a possible waste of resource. Though I'm fine we move it to use the copy function. But definitely will be cases where a function should not be executed if a given memory is invalid. In that case we will require the memory access check + `z_user_to_copy`.

Comment (andrewboie) [reply drivers/espi/espi_handlers.c:44]: > But definitely will be cases where a function should not be executed if a given memory is invalid. In that case we will require the memory access check + z_user_to_copy.

Can you provide an example of this?

Comment (ceolin) [reply drivers/espi/espi_handlers.c:44]: I can come up with other question, can you ensure that this will never be necessary ? I can imagine a driver (or a generic code) that change status everytime is called. Entropy for instance, you can probably starve an internal buffer calling it with a wrong memory that will never be used.

Is that a real case / threat, probably not, but it seems suspicious execute a call that shouldn't be executed because it was given wrong parameters.
I can understand SMAP argument and since we are not discussing concrete cases I'll change it, but we should keep an eye on this possible case IMHO.

Comment (andrewboie) [reply drivers/espi/espi_handlers.c:44]: To me it is not problematic for an API call to be executed, succeed, and then a memory error generated when attempting to copy some result back to memory accessible by user mode. I don't see it fundamentally different from having a coding mistake the next line after the API call which then induces an error. These kinds of issues are always coding mistakes which is why we Z_OOPS().

Comment (ceolin) [reply drivers/espi/espi_handlers.c]: pr changed, can you look it again ?

**Review by tyrantlizard77 — APPROVED** [review]

**Review by franciscomunoz — APPROVED** [review]
