### PR TITLE
Bluetooth: Controller: Various fixes for CIS termination handling

### LINKED ISSUE #59173: Bluetooth: Controller: No CIS established event if CIS failed to be established on peripheral
**Describe the bug**
If the peripheral host accepts a CIS request that then fails to be established, the host seemingly never receives a Disconnect event. 

**To Reproduce**
N/A

**Expected behavior**
The spec states:

> When the Controller receives the HCI_LE_Accept_CIS_Request command, the Controller sends the HCI_Command_Status event to the Host. An HCI_LE_CIS_Established event will be generated when the CIS is established or is considered lost before being established.

**Impact**
Can put the host into a non-working state, which requires a complete reset. 

**Logs and console output**N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 1b7ef97c31f4b734cae9cfb2b251c1b86b40d109

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Tronil**
Handling of CIS termination had several issues, most notably:

- it depended on allocating a termination node from the general rx node pool, causing asserts if the pool was exhausted
- CIS established events was not always generated when required, potentially causing CIS Centrals to get stuck without being able to create any new CISes
- Cancelling a CIS Create procedure only worked correctly if the CIS Create was currently active and happened to belong to the same CIS
- CIG state handling often (always?) assumed a CIG with only one CIS

ll_conn_iso_stream now has a dedicated termination node, same as ll_conn and ll_sync_iso_set

LLCP statemachine for Cis Create procedure has been reworked to ensure a notification node for CIS Established is available as early as possible. In addition, it should now always be sent when needed

Introduced ull_central_iso_all_cises_terminated() to check if all CISes in a CIG has been terminated (or not created yet) - which is now used for updating the CIG state

ull_cp_cc_cancel() now takes the CIS to cancel as an argument so it doesn't end up canceling an entirely different CIS Create procedure; In addition it now works for queued procedures as well

Flushing a (central) CIS Create procedure in LLCP will now properly generate a CIS Established event (with an error)

Fixes #59173

### CODE REVIEW

**Review by erbr-ot — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 1]
```diff
@@ -459,6 +459,12 @@ static MFIFO_DEFINE(pdu_rx_free, sizeof(void *), PDU_RX_CNT);
 #define BT_CTLR_SCAN_SYNC_ISO_SET 0
 #endif
 
+#if defined(CONFIG_BT_CTLR_CONN_ISO_STREAMS)
+#define BT_CTLR_CONN_ISO_STREAMS CONFIG_BT_CTLR_CONN_ISO_STREAMS
+#else
+#define BT_CTLR_CONN_ISO_STREAMS 0
+#endif
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull.c]: Consider the shorter version

```
#define BT_CTLR_CONN_ISO_STREAMS                                                                  \
	COND_CODE_1(CONFIG_BT_CTLR_CONN_ISO_STREAMS, (CONFIG_BT_CTLR_CONN_ISO_STREAMS), (0))
```

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 2]
```diff
@@ -508,7 +514,7 @@ static struct {
 	(sizeof(memq_link_t) *                                                 \
 	 (RX_CNT + 2 + BT_CTLR_MAX_CONN + BT_CTLR_ADV_SET +                    \
 	  (BT_CTLR_ADV_ISO_SET * 2) + (BT_CTLR_SCAN_SYNC_SET * 2) +            \
-	  (BT_CTLR_SCAN_SYNC_ISO_SET * 2) +                                    \
+	  (BT_CTLR_SCAN_SYNC_ISO_SET * 2) + BT_CTLR_CONN_ISO_STREAMS +         \
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull.c:517]: `BT_CTLR_SCAN_SYNC_ISO_SET` is multiplied by 2, should `BT_CTLR_CONN_ISO_STREAMS` be too?

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 3]
```diff
@@ -744,6 +747,13 @@ void ll_cis_create(uint16_t cis_handle, uint16_t acl_handle)
 
 	(void)memset(&cis->hdr, 0U, sizeof(cis->hdr));
 
+	/* Allocate new terminate link if needed (only needed if CIS is re-used) */
+	if (!cis->node_rx_terminate.rx.hdr.link) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c]:
```suggestion
	if (cis->node_rx_terminate.rx.hdr.link == NULL) {
```

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 4]
```diff
@@ -1022,6 +1032,30 @@ int ull_central_iso_cis_offset_get(uint16_t cis_handle,
...
+			if (cis->established) {
+				return false;
+			}
+
+			/* Check if CIS is being created */
+			conn = ll_connected_get(cis->lll.acl_handle);
+			if (conn && ull_lp_cc_is_enqueued(conn, cis)) {
+				return false;
+			}
+		}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:1054]: Should we break here, if we have identified the CIG?


```suggestion
			}
			
			break;
		}
```

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 5]
```diff
@@ -438,43 +439,44 @@ uint8_t ll_terminate_ind_send(uint16_t handle, uint8_t reason)
...
-							node_terminate);
+					node_terminate->hdr.handle = handle;
+					node_terminate->hdr.type = NODE_RX_TYPE_TERMINATE;
+					*((uint8_t *)node_terminate->pdu) =
+						BT_HCI_ERR_LOCALHOST_TERM_CONN;
 
-						/* We're no longer initiating a connection */
-						cis->group->state = CIG_STATE_CONFIGURABLE;
+					ll_rx_put_sched(node_terminate->hdr.link,
+						node_terminate);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]:
```suggestion
					ll_rx_put_sched(node_terminate->hdr.link,
							node_terminate);
```

or
```suggestion
					ll_rx_put_sched(node_terminate->hdr.link, node_terminate);
```

given that Zephyr uses 100 as column width

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 6]
```diff
@@ -1897,8 +1899,50 @@ static void conn_cleanup_finalize(struct ll_conn *conn)
 	struct lll_conn *lll = &conn->lll;
 	uint32_t ticker_status;
 
+#if defined(CONFIG_BT_CTLR_PERIPHERAL_ISO) || defined(CONFIG_BT_CTLR_CENTRAL_ISO)
+	if (ull_cp_cc_is_active(conn)) {
+		/* CIS creation procedure active, notify LLCP */
+		ull_cp_cc_acl_disconnect(conn);
+	}
+#endif /* CONFIG_BT_CTLR_PERIPHERAL_ISO || CONFIG_BT_CTLR_CENTRAL_ISO */
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: Looks like IS_ENABLED can be used here

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 7]
```diff
@@ -1897,8 +1899,50 @@ static void conn_cleanup_finalize(struct ll_conn *conn)
...
+
+	/* Set LLCP state - flushes control procedures */
 	ull_cp_state_set(conn, ULL_CP_DISCONNECTED);
 
+#if defined(CONFIG_BT_CTLR_PERIPHERAL_ISO) || defined(CONFIG_BT_CTLR_CENTRAL_ISO)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c:1912]: Can IS_ENABLED be used here?

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 8]
```diff
@@ -1897,8 +1899,50 @@ static void conn_cleanup_finalize(struct ll_conn *conn)
...
+	/* Find and clean non-established, allocated CISes associated with this ACL conn */
+	for (uint8_t handle = LL_CIS_HANDLE_BASE; handle <= LL_CIS_HANDLE_LAST; handle++) {
+		struct ll_conn_iso_stream *cis;
+		struct ll_conn_iso_group *cig;
+
+		cis = ll_conn_iso_stream_get(handle);
+		cig = cis->group;
+		if (cig && cig->lll.num_cis && cis->lll.acl_handle == conn->lll.handle) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]:
```suggestion
		if (cig != NULL && cig->lll.num_cis != 0U && cis->lll.acl_handle == conn->lll.handle) {
```

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 9]
```diff
@@ -1897,8 +1899,50 @@ static void conn_cleanup_finalize(struct ll_conn *conn)
...
+			if (IS_PERIPHERAL(cig)) {
+				/* Remove data paths associated with this CIS for both directions.
+				 * Disable them one at a time to make sure both are removed, even if
+				 * only one is set.
+				 */
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c:1929]: Suggest to expand on this by stating that this only applies for peripherals and not centrals, so that it doesn't look like a mistake; possibly with a reference to where it is stated in the core spec

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 10]
```diff
@@ -1897,8 +1899,50 @@ static void conn_cleanup_finalize(struct ll_conn *conn)
...
+				ll_remove_iso_path(handle, BIT(BT_HCI_DATAPATH_DIR_HOST_TO_CTLR));
+				ll_remove_iso_path(handle, BIT(BT_HCI_DATAPATH_DIR_CTLR_TO_HOST));
+
+				ll_conn_iso_stream_release(cis);
+				cig->lll.num_cis--;
+
+				if (!cig->lll.num_cis) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]:
```suggestion
				if (cig->lll.num_cis == 0U) {
```

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c [hunk 11]
```diff
@@ -136,6 +136,10 @@ struct ll_conn_iso_stream *ll_conn_iso_stream_acquire(void)
 
 	if (cis) {
 		(void)memset(&cis->hdr, 0U, sizeof(cis->hdr));
+
+		cis->node_rx_terminate.rx.hdr.link = ll_rx_link_alloc();
+		/* Link allocation should never fail */
+		LL_ASSERT(cis->node_rx_terminate.rx.hdr.link);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]:
```suggestion
		LL_ASSERT(cis->node_rx_terminate.rx.hdr.link != NULL);
```

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c [hunk 12]
```diff
@@ -146,6 +150,13 @@ void ll_conn_iso_stream_release(struct ll_conn_iso_stream *cis)
 	cis->cis_id = 0;
 	cis->group = NULL;
 
+	if (cis->node_rx_terminate.rx.hdr.type == NODE_RX_TYPE_NONE &&
+	    cis->node_rx_terminate.rx.hdr.link) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]:
```suggestion
	    cis->node_rx_terminate.rx.hdr.link != NULL) {
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 13]
```diff
@@ -1387,14 +1387,43 @@ bool ull_cp_cc_awaiting_established(struct ll_conn *conn)
...
 
-#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
-bool ull_cp_cc_cancel(struct ll_conn *conn)
+bool ull_cp_cc_is_active(struct ll_conn *conn)
 {
 	struct proc_ctx *ctx;
 
+#if defined(CONFIG_BT_CTLR_PERIPHERAL_ISO)
+	ctx = llcp_rr_peek(conn);
+	if (ctx && ctx->proc == PROC_CIS_CREATE) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]:
```suggestion
	if (ctx != NULL && ctx->proc == PROC_CIS_CREATE) {
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 14]
```diff
@@ -1387,14 +1387,43 @@ bool ull_cp_cc_awaiting_established(struct ll_conn *conn)
 	return false;
 }
 
-#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
-bool ull_cp_cc_cancel(struct ll_conn *conn)
+bool ull_cp_cc_is_active(struct ll_conn *conn)
 {
 	struct proc_ctx *ctx;
 
+#if defined(CONFIG_BT_CTLR_PERIPHERAL_ISO)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]: IS_ENABLED?

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 15]
```diff
@@ -1387,14 +1387,43 @@ bool ull_cp_cc_awaiting_established(struct ll_conn *conn)
...
+	ctx = llcp_rr_peek(conn);
+	if (ctx && ctx->proc == PROC_CIS_CREATE) {
+		return llcp_rp_cc_is_active(ctx);
+	}
+#endif /* CONFIG_BT_CTLR_PERIPHERAL_ISO */
+
+#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]: IS_ENABLED?

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 16]
```diff
@@ -1387,14 +1387,43 @@ bool ull_cp_cc_awaiting_established(struct ll_conn *conn)
...
+	return false;
+}
+
+#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
+bool ull_cp_cc_cancel(struct ll_conn *conn, struct ll_conn_iso_stream *cis)
+{
+	struct proc_ctx *ctx;
+
+	ctx = llcp_lr_peek(conn);
+	if (ctx && ctx->proc == PROC_CIS_CREATE &&
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]:
```suggestion
	if (ctx != NULL && ctx->proc == PROC_CIS_CREATE &&
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 17]
```diff
@@ -1387,14 +1387,43 @@ bool ull_cp_cc_awaiting_established(struct ll_conn *conn)
...
+	    ctx->data.cis_create.cis_handle == cis->lll.handle) {
 		return llcp_lp_cc_cancel(conn, ctx);
+	} else {
+		/* Look through queue */
+		ctx = llcp_lr_peek_cc(conn, cis->lll.handle);
+		if (ctx) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]:
```suggestion
		if (ctx != NULL) {
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 18]
```diff
@@ -1423,6 +1452,29 @@ void ull_cp_cc_established(struct ll_conn *conn, uint8_t error_code)
 	}
 #endif /* CONFIG_BT_CTLR_CENTRAL_ISO */
 }
+
+void ull_cp_cc_acl_disconnect(struct ll_conn *conn)
+{
+	struct proc_ctx *ctx;
+
+#if defined(CONFIG_BT_CTLR_PERIPHERAL_ISO)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]: IS_ENABLED?

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 19]
```diff
@@ -1423,6 +1452,29 @@ void ull_cp_cc_established(struct ll_conn *conn, uint8_t error_code)
...
+	ctx = llcp_rr_peek(conn);
+	if (ctx && ctx->proc == PROC_CIS_CREATE) {
+		ctx->data.cis_create.error = BT_HCI_ERR_CONN_FAIL_TO_ESTAB;
+		llcp_rp_cc_acl_disconnect(conn, ctx);
+		llcp_rr_check_done(conn, ctx);
+	}
+#endif /* CONFIG_BT_CTLR_PERIPHERAL_ISO */
+
+#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]: IS_ENABLED?

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 20]
```diff
@@ -1423,6 +1452,29 @@ void ull_cp_cc_established(struct ll_conn *conn, uint8_t error_code)
...
 #endif /* CONFIG_BT_CTLR_CENTRAL_ISO */
 }
+
+void ull_cp_cc_acl_disconnect(struct ll_conn *conn)
+{
+	struct proc_ctx *ctx;
+
+#if defined(CONFIG_BT_CTLR_PERIPHERAL_ISO)
+	ctx = llcp_rr_peek(conn);
+	if (ctx && ctx->proc == PROC_CIS_CREATE) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]:
```suggestion
	if (ctx != NULL && ctx->proc == PROC_CIS_CREATE) {
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 21]
```diff
@@ -1423,6 +1452,29 @@ void ull_cp_cc_established(struct ll_conn *conn, uint8_t error_code)
...
+		ctx->data.cis_create.error = BT_HCI_ERR_CONN_FAIL_TO_ESTAB;
+		llcp_rp_cc_acl_disconnect(conn, ctx);
+		llcp_rr_check_done(conn, ctx);
+	}
+#endif /* CONFIG_BT_CTLR_PERIPHERAL_ISO */
+
+#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
+	ctx = llcp_lr_peek(conn);
+	if (ctx && ctx->proc == PROC_CIS_CREATE) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]:
```suggestion
	if (ctx != NULL && ctx->proc == PROC_CIS_CREATE) {
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 22]
```diff
@@ -1387,14 +1387,43 @@ bool ull_cp_cc_awaiting_established(struct ll_conn *conn)
...
 	ctx = llcp_lr_peek(conn);
 	if (ctx && ctx->proc == PROC_CIS_CREATE) {
+		return llcp_lp_cc_is_active(ctx);
+	}
+#endif /* CONFIG_BT_CTLR_CENTRAL_ISO */
+	return false;
+}
+
+#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
+bool ull_cp_cc_cancel(struct ll_conn *conn, struct ll_conn_iso_stream *cis)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]:
```suggestion
bool ull_cp_cc_cancel(struct ll_conn *conn, const struct ll_conn_iso_stream *cis)
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 23]
```diff
@@ -1437,11 +1489,23 @@ bool ull_lp_cc_is_active(struct ll_conn *conn)
 	return false;
 }
 
-bool ull_lp_cc_is_enqueued(struct ll_conn *conn)
+bool ull_lp_cc_is_enqueued(struct ll_conn *conn, struct ll_conn_iso_stream *cis)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]:
```suggestion
bool ull_lp_cc_is_enqueued(struct ll_conn *conn, const struct ll_conn_iso_stream *cis)
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 24]
```diff
@@ -1437,11 +1489,23 @@ bool ull_lp_cc_is_active(struct ll_conn *conn)
...
-	ctx = llcp_lr_peek_proc(conn, PROC_CIS_CREATE);
+	if (cis) {
+		cis_handle = cis->lll.handle;
+	} else {
+		cis_handle = LLL_HANDLE_INVALID;
+	}
+
+	ctx = llcp_lr_peek_cc(conn, cis_handle);
+
+	if (ctx && cis && ctx->data.cis_create.error != BT_HCI_ERR_SUCCESS) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c]:
```suggestion
	if (ctx != NULL && cis != NULL && ctx->data.cis_create.error != BT_HCI_ERR_SUCCESS) {
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.h [hunk 25]
```diff
@@ -202,7 +202,7 @@ bool ull_cp_cc_awaiting_established(struct ll_conn *conn);
 /**
  * @brief Cancel ongoing create cis procedure
  */
-bool ull_cp_cc_cancel(struct ll_conn *conn);
+bool ull_cp_cc_cancel(struct ll_conn *conn, struct ll_conn_iso_stream *cis);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.h]: May be worth documenting that `cis` can be NULL

File: subsys/bluetooth/controller/ll_sw/ull_llcp.h [hunk 26]
```diff
@@ -225,15 +225,25 @@ void ull_cp_cc_reject(struct ll_conn *conn, uint8_t error_code);
...
+/**
+ * @brief Local CIS creation ongoing.
+ */
 bool ull_lp_cc_is_active(struct ll_conn *conn);
 
 /**
  * @brief CIS creation ongoing or enqueued.
  */
-bool ull_lp_cc_is_enqueued(struct ll_conn *conn);
+bool ull_lp_cc_is_enqueued(struct ll_conn *conn, struct ll_conn_iso_stream *cis);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.h]: May be worth documenting that `cis` can be NULL

File: subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c [hunk 27]
```diff
@@ -710,6 +724,12 @@ void llcp_rp_cc_run(struct ll_conn *conn, struct proc_ctx *ctx, void *param)
 	rp_cc_execute_fsm(conn, ctx, RP_CC_EVT_RUN, param);
 }
 
+bool llcp_rp_cc_is_active(struct proc_ctx *ctx)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c]:
```suggestion
bool llcp_rp_cc_is_active(const struct proc_ctx *ctx)
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c [hunk 28]
```diff
@@ -1028,14 +1093,14 @@ static void lp_cc_st_wait_notify_cancel(struct ll_conn *conn, struct proc_ctx *c
 {
 	switch (evt) {
 	case LP_CC_EVT_RUN:
-		if (llcp_ntf_alloc_is_available()) {
+		if (!ctx->node_ref.rx && llcp_ntf_alloc_is_available()) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c]:
```suggestion
		if (ctx->node_ref.rx == NULL && llcp_ntf_alloc_is_available()) {
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c [hunk 29]
```diff
@@ -1028,14 +1093,14 @@ static void lp_cc_st_wait_notify_cancel(struct ll_conn *conn, struct proc_ctx *c
...
 			ctx->node_ref.rx = llcp_ntf_alloc();
 
 			/* Mark node as RETAIN to trigger put/sched */
 			ctx->node_ref.rx->hdr.type = NODE_RX_TYPE_RETAIN;
-			ctx->state = LP_CC_STATE_WAIT_ESTABLISHED;
-
-			llcp_lp_cc_established(conn, ctx);
+		}
+		if (ctx->node_ref.rx) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c]:
```suggestion
		if (ctx->node_ref.rx != NULL) {
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c [hunk 30]
```diff
@@ -197,6 +197,31 @@ struct proc_ctx *llcp_lr_peek_proc(struct ll_conn *conn, uint8_t proc)
...
+#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
+struct proc_ctx *llcp_lr_peek_cc(struct ll_conn *conn, uint16_t cc_handle)
+{
+	/* This function is called from both Thread and Mayfly (ISR),
+	 * make sure only a single context have access at a time.
+	 */
+
+	struct proc_ctx *ctx, *tmp;
+
+	bool key = shared_data_access_lock();
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_local.c:209]: `shared_data_access_lock` has a return type of `uint32_t`, but is always returning a boolean value. Is that intentional? 

And is `key` an appropriate name for a boolean value?

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c [hunk 31]
```diff
@@ -234,6 +259,11 @@ void llcp_lr_flush_procedures(struct ll_conn *conn)
 	/* Flush all pending procedures */
 	ctx = lr_dequeue(conn);
 	while (ctx) {
+#if defined(CONFIG_BT_CTLR_CENTRAL_ISO)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_local.c]: IS_ENABLED?

File: tests/bluetooth/controller/mock_ctrl/src/ull_central_iso.c [hunk 32]
```diff
@@ -0,0 +1,24 @@
...
+#include "hal/ccm.h"
+
+#include "util/mem.h"
+#include "util/memq.h"
+
+#include "isoal.h"
+#include "ull_iso_types.h"
+#include "lll.h"
+#include "lll_conn_iso.h"
+#include "ull_conn_iso_types.h"
```
Comment (Thalley) [inline tests/bluetooth/controller/mock_ctrl/src/ull_central_iso.c:19]: This seems excessive for what this file contains. A copy and paste?

**Review by Thalley — CHANGES_REQUESTED** [review]
Mostly reviewed the code style and format, as the inner workings are beyond my understanding

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull.c:517]: Only one, as this PR introduces allocation of a `memq_link_t` of one per ISO stream from the pool.

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 33]
```diff
@@ -744,6 +747,13 @@ void ll_cis_create(uint16_t cis_handle, uint16_t acl_handle)
 
 	(void)memset(&cis->hdr, 0U, sizeof(cis->hdr));
 
+	/* Allocate new terminate link if needed (only needed if CIS is re-used) */
+	if (!cis->node_rx_terminate.rx.hdr.link) {
+		cis->node_rx_terminate.rx.hdr.link = ll_rx_link_alloc();
+		/* Failure should not be possible, but assert just in case */
+		LL_ASSERT(cis->node_rx_terminate.rx.hdr.link);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c]:
```suggestion
		LL_ASSERT_DBG(cis->node_rx_terminate.rx.hdr.link);
```

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 4 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:1054]: Correct me, we are iterating through all CIS; many CISes can be associated to a CIG, hence, need to complete through the CIS handles.

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c (hunk 11 above)
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]:
```suggestion
		LL_ASSERT_DBG(cis->node_rx_terminate.rx.hdr.link != NULL);
```

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c [hunk 34]
```diff
@@ -1116,6 +1127,27 @@ void ull_conn_iso_start(struct ll_conn *conn, uint16_t cis_handle,
 	cis->lll.active = 1U;
 }
 
+void ull_conn_iso_cis_terminate_done(struct node_rx_pdu *rx)
+{
+	DECLARE_MAYFLY_ARRAY(mfys, cis_disabled_cb, CONFIG_BT_CTLR_CONN_ISO_GROUPS);
+	struct ll_conn_iso_stream *cis;
+
+	cis = ll_conn_iso_stream_get(rx->hdr.handle);
+	LL_ASSERT(rx == &cis->node_rx_terminate.rx);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]:
```suggestion
	LL_ASSERT_DBG(rx == &cis->node_rx_terminate.rx);
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c [hunk 35]
```diff
@@ -818,8 +846,26 @@ void llcp_lp_cc_offset_calc_reply(struct ll_conn *conn, struct proc_ctx *ctx)
...
+	/* Flushing queued procedure; CIS Create always has to result in a
+	 * corresponding HCI_LE_CIS_Established event, so generate that now
+	 */
+	if (ctx->data.cis_create.error == BT_HCI_ERR_SUCCESS) {
+		ctx->data.cis_create.error = BT_HCI_ERR_CONN_FAIL_TO_ESTAB;
+	}
+
+	/* FIXME - we currently have no way to recover if we cannot allocate a node here */
+	ctx->node_ref.rx = llcp_ntf_alloc();
+	LL_ASSERT(ctx->node_ref.rx);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c]:
```suggestion
	LL_ASSERT_ERR(ctx->node_ref.rx);
```

**Comment by Tronil** [comment]
> Does this patch cover #59173 as well?

It should, yes

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 1 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull.c]: COND_CODE_1() requires CONFIG_BT_CTLR_CONN_ISO_STREAMS to expand to 1 as far as I can see?

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 2 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull.c:517]: As the comment above this block states, sync_iso reserves two links to cover both sync established and sync lost. In this case it is only used for termination, so we only need one.

**Review by cvinayak — CHANGES_REQUESTED** [review]
LGTM, some nitpicks

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 4 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:1054]: No we need to loop through all CIS structures to find all CISes associated with a particular CIG. The only link between the CISes and the CIG is the `group` pointer in `struct ll_conn_iso_stream`, so all CISes need to be checked.

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull.c]: That is true, but effectively works the same as `defined(CONFIG_BT_CTLR_CONN_ISO_STREAMS)`.

For correctness, it probably should be 

```c
#define BT_CTLR_CONN_ISO_STREAMS                                                                  \
	COND_CODE_1(defined(CONFIG_BT_CTLR_CONN_ISO_STREAMS), (CONFIG_BT_CTLR_CONN_ISO_STREAMS), (0))
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp.h (hunk 25 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.h]: For this particular function it actually doesn't make sense with a cis that is NULL (and is in fact not allowed). For ull_lp_cc_is_enqueued it can be NULL if you don't care which CIS is enqueued (I'll update the comment there).

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c (hunk 30 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_local.c:209]: That is the current architecture of LLCP (I simply copied that from existing code); You would have to ask someone like @erbr-ot or @thoh-ot. In any case, I don't think this PR is the proper place to address something like that

File: tests/bluetooth/controller/mock_ctrl/src/ull_central_iso.c (hunk 32 above)
Comment (Tronil) [reply tests/bluetooth/controller/mock_ctrl/src/ull_central_iso.c:19]: No, that is unfortunately what is needed to include  ull_conn_iso_types.h

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c (hunk 30 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_local.c:209]: Fair point since it an existing issue

File: tests/bluetooth/controller/mock_ctrl/src/ull_central_iso.c (hunk 32 above)
Comment (Thalley) [reply tests/bluetooth/controller/mock_ctrl/src/ull_central_iso.c:19]: Yikes :) Seems like the controller headers could benefit from following https://github.com/include-what-you-use/include-what-you-use :D

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 3 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 5 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 6 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 7 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c:1912]: In this case it would mean adding an if statement where none exists and it is already indented quite heavily in some parts - so I think it would make it less readable

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 8 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Done

**Review by cvinayak — DISMISSED** [review]
Good for me once some of @Thalley  requested changes are addressed.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 9 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c:1929]: Added a note stating that it is only relevant for the peripheral and why

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 10 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c (hunk 11 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c (hunk 12 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_conn_iso.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 13 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 14 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Yes - updated

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 15 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Yes - updated

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 17 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 18 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Yes - updated

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 19 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Yes - updated

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 20 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 21 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 22 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 23 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 24 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.h (hunk 26 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.h]: Comment has been updated to state what cis == NULL means

File: subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c (hunk 27 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c (hunk 28 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c (hunk 29 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_cc.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c (hunk 31 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_local.c]: Yes - updated

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 1 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull.c]: Updated to use COND_CODE_1

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 16 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Done

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 1 above)
Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/ull.c]: Hmm it doesn't seem to work correctly / as expected. I have reverted it back to the simple form; I don't really have time to dig in to it right now

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 7 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c:1912]: Your arguments, to me, sounds more like this following loop should have been put into a separate function (or functions) :) I agree that the indentation would be an issue, but it would be the same level of indentation that we have in e.g. lines 400-500 in this file (which also gets marked by Sonar). 

Our coding guidelines (inherited from https://www.kernel.org/doc/html/v4.10/process/coding-style.html) does state 

Image

However I will not be blocking this PR based on this, due to the timing (would prefer to get this in for 4.3).

**Review by Thalley — APPROVED** [review]
Any outstanding formatting issues etc. I don't consider blocking for this PR. LGTM

**Review by cvinayak — APPROVED** [review]
