### PR TITLE
Bluetooth: host: Log SC LTK in pairing procedure without bonding

### LINKED ISSUE #50691: Bluetooth: Host: CONFIG_BT_LOG_SNIFFER_INFO doesn't work as intended without bonding
**Describe the bug**
The help text of `CONFIG_BT_LOG_SNIFFER_INFO` says that it will enable logging of e.g. the LTK and private keys. While this is mostly true, the LTK is not logged if the link isn't bonding (triggered by e.g. setting `CONFIG_BT_BONDABLE=n`). 

**To Reproduce**
1. Build the BT shell (`zephyr/tests/bluetooth/shell`) with `CONFIG_BT_BONDABLE=n`
2. Connect to a device and do `bt security 2` to encrypt the link
3. See missing logging of the LTK

**Expected behavior**
Expected to see the LTK regardless of bonding, as debugging a non-bonded connection is equally valid. 

**Impact**
Annoyance

**Logs and console output**

Central with bonding:
```
uart:~$ bt security 2
LE conn param updated: int 0x0018 lat 0 to 42
Security changed: 5E:C8:43:72:21:1E (random) level 2
Identity resolved 5E:C8:43:72:21:1E (random) -> C2:35:E5:CA:5E:A1 (random)
Bonded with C2:35:E5:CA:5E:A1 (random)
[00:01:19.844,970] <inf> bt_keys: SC LTK: 0xca1505d416abfc96ab0db3cba088c6b8
uart:~$ 
```

Peripheral with bonding:
```
Security changed: 59:48:1E:1B:D4:30 (random) level 2
Identity resolved 59:48:1E:1B:D4:30 (random) -> D7:8C:A2:75:B6:07 (random)
Bonded with D7:8C:A2:75:B6:07 (random)
[00:02:24.922,943] <inf> bt_keys: SC LTK: 0xca1505d416abfc96ab0db3cba088c6b8
uart:~$ 
```

Central without bonding:
```
uart:~$ bt security 2
Security changed: 4E:22:41:2D:FE:6F (random) level 2
Paired with 4E:22:41:2D:FE:6F (random)
uart:~$ 
```

Peripheral without bonding:
```
Security changed: 71:46:D3:9B:A6:7A (random) level 2
Paired with 71:46:D3:9B:A6:7A (random)
uart:~$ 
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: 489e8eb02c2a7bd46a9e73ee1a07a9bd20a61e98

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by joerchan**
Log the LE Secure Connection (SC) LTK in a pairing procedure without bonding when CONFIG_BT_LOG_SNIFFER_INFO is enabled.

Fixes: #50691

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/smp.c [hunk 1]
```diff
@@ -5840,6 +5840,12 @@ void bt_smp_update_keys(struct bt_conn *conn)
 				     sizeof(conn->le.keys->ltk.rand));
 			(void)memset(conn->le.keys->ltk.ediv, 0,
 				     sizeof(conn->le.keys->ltk.ediv));
+		} else if (IS_ENABLED(CONFIG_BT_LOG_SNIFFER_INFO)) {
+			uint8_t ltk[16];
+
+			sys_memcpy_swap(ltk, smp->tk, keys->enc_size);
+			BT_INFO("SC LTK: 0x%s (No bonding)",
+				bt_hex(ltk, keys->enc_size));
```
Comment (Thalley) [inline subsys/bluetooth/host/smp.c:5848]:
```suggestion
			sys_memcpy_swap(ltk, smp->tk, conn->le.keys->enc_size);
			BT_INFO("SC LTK: 0x%s (No bonding)",
				bt_hex(ltk, conn->le.keys->enc_size));
```

**Review by Thalley — CHANGES_REQUESTED** [review]
Works, but giving a compile error

**Review by Thalley — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]
