### PR TITLE
kernel: Improve precision of ticks and ms conversions

### LINKED ISSUE #8898: Failed test: kernel.timer.timer_periodicity on nrf51/nrf52
Test tests/kernel/timer/timer_api/kernel.timer failing on nrf51:

```
***** delaying boot 1000ms (per build configuration) *****
 ***** Booting Zephyr OS 1.12.99 (delayed boot 1000ms) *****
 Running test suite timer_api
 ===================================================================
 starting test - test_timer_duration_period
 PASS - test_timer_duration_period
 ===================================================================
 starting test - test_timer_period_0
 PASS - test_timer_period_0
 ===================================================================
 starting test - test_timer_expirefn_null
 PASS - test_timer_expirefn_null
 ===================================================================
 starting test - test_timer_periodicity

     Assertion failed at zephyr.git/tests/kernel/timer/timer_api/src/main.c:171: test_timer_periodicity: (((delta) >= (50)) && ((delta) <= (50) + (1))) is false

 FAIL - test_timer_periodicity
 ===================================================================
 starting test - test_timer_status_get
 PASS - test_timer_status_get
 ===================================================================
 starting test - test_timer_status_get_anytime
 PASS - test_timer_status_get_anytime
 ===================================================================
 starting test - test_timer_status_sync

     Assertion failed at zephyr.git/tests/kernel/timer/timer_api/src/main.c:53: duration_expire: k_uptime_delta(&tdata.timestamp) >= 50 is false

 ASSERTION FAIL [!(thread->base.user_options & (1 << 0))] @ zephyr.git/arch/arm/core/thread_abort.c:37:
 	essential thread aborted

```

### LINKED ISSUE #9459: tests/posix/timer fails on nRF51/52
The test in tests/posix/timer results in _assertion failure_.

This test started failing after this commit: 3c7f990367f38c84b20e7888042ea9429cfae8a6

**Arch:** ARM
**Board:** nrf51/52 - nrf51_pca10028:arm, nrf52_pca10040:arm, nrf52840_pca10056:arm

**Error console log:**
```
 ***** Booting Zephyr OS 1.12.99 (delayed boot 1000ms) *****
 Running test suite test_posix_timer
 ===================================================================
 starting test - test_timer
 POSIX timer test
 Timer fires every 0 secs and  100000000 nsecs
 Time remaining to fire 0 secs and  888000000 nsecs
 Handler Signal value :20 for 1 times
 Handler Signal value :20 for 2 times
 Handler Signal value :20 for 3 times
 Handler Signal value :20 for 4 times
 Handler Signal value :20 for 5 times
 Handler Signal value :20 for 6 times
 Handler Signal value :20 for 7 times
 Handler Signal value :20 for 8 times
 Handler Signal value :20 for 9 times
 Handler Signal value :20 for 10 times
 Handler Signal value :20 for 11 times
 
 Assertion failed at .. /tests/posix/timer/src/main.c:87: test_timer: (total_secs_timer not equal to secs_elapsed)
 POSIX timer test has failed
 FAIL - test_time
===================================================================
===================================================================
PROJECT EXECUTION FAILED
```

### LINKED ISSUE #9466: tests/kernel/context/testcase.yaml#kernel.common.k_sleep fails on nrf52_pca10040 and nrf52840_pca10056
Execution log:
```
Running test suite context
===================================================================
starting test - test_kernel_interrupts
PASS - test_kernel_interrupts
===================================================================
starting test - test_kernel_timer_interrupts
SKIP - test_kernel_timer_interrupts
===================================================================
starting test - test_kernel_ctx_thread
Testing k_current_get() from an ISR and thread
Testing k_is_in_isr() from an ISR
Testing k_is_in_isr() from a preemptible thread
PASS - test_kernel_ctx_thread
===================================================================
starting test - test_busy_wait
Thread busy waiting for 20000 usecs
Thread busy waiting completed
PASS - test_busy_wait
===================================================================
starting test - test_k_sleep
 thread sleeping for 50 milliseconds
 thread back from sleep
FAIL - thread_sleep@684. timestamp out of range, got 70

    Assertion failed at /home/kspoorth/work/latest_zephyr/tests/kernel/context/src/main.c:753: test_k_sleep: (rv not equal to 0)
 *** thread timed out waiting for thread on k_sleep().
FAIL - test_k_sleep
===================================================================
starting test - test_kernel_cpu_idle_atomic
SKIP - test_kernel_cpu_idle_atomic
===================================================================
starting test - test_kernel_cpu_idle
PASS - test_kernel_cpu_idle
===================================================================
starting test - test_k_yield
PASS - test_k_yield
===================================================================
starting test - test_kernel_thread
PASS - test_kernel_thread
===================================================================
===================================================================

PROJECT EXECUTION FAILED

```

Platforms: nrf52_pca10040 and nrf52840_pca10056
Latest commit on which the failure is seen: afa0e0026fb94d37f50dc53f9d0981b1dc5c306b

### LINKED ISSUE #9468: tests/kernel/mem_pool/mem_pool_concept/testcase.yaml#kernel.memory_pool fails on nrf52840_pca10056, nrf52_pca10040 and  nrf51_pca10028
Execution log:
```
Running test suite mpool_concept
===================================================================
starting test - test_mpool_alloc_wait_prio

    Assertion failed at /home/kspoorth/work/latest_zephyr/tests/kernel/mem_pool/mem_pool_concept/src/test_mpool_alloc_wait.c:24: tmpool_alloc_wait_timeout: k_mem_pool_alloc(&mpool1, &block, BLK_SIZE_MIN, TIMEOUT) == -EAGAIN is false

FAIL - test_mpool_alloc_wait_prio
===================================================================
starting test - test_mpool_alloc_size_roundup

    Assertion failed at /home/kspoorth/work/latest_zephyr/tests/kernel/mem_pool/mem_pool_concept/src/test_mpool_alloc_size.c:36: test_mpool_alloc_size_roundup: k_mem_pool_alloc(&mpool1, &block[i], TEST_SIZE, K_NO_WAIT) == 0 is false

FAIL - test_mpool_alloc_size_roundup
===================================================================
starting test - test_mpool_alloc_merge_failed_diff_size
PASS - test_mpool_alloc_merge_failed_diff_size
===================================================================
starting test - test_mpool_alloc_merge_failed_diff_parent

    Assertion failed at /home/kspoorth/work/latest_zephyr/tests/kernel/mem_pool/mem_pool_concept/src/test_mpool_merge_fail_diff_parent.c:33: test_mpool_alloc_merge_failed_diff_parent: k_mem_pool_alloc(&mpool1, &block[i], BLK_SIZE_MIN, K_NO_WAIT) == 0 is false

FAIL - test_mpool_alloc_merge_failed_diff_parent
===================================================================
===================================================================
PROJECT EXECUTION FAILED
```

Steps to reproduce:
cd tests/kernel/mem_pool/mem_pool_concept
mkdir build && cd build
cmake -DBOARD=nrf51_pca10028 .. && make flash

Latest commit: afa0e0026fb94d37f50dc53f9d0981b1dc5c306b

Platforms tested: nrf52840_pca10056, nrf52_pca10040 and  nrf51_pca10028

### PR DESCRIPTION
**Pull request by carlescufi**
The following 2 improvements are contained in this patch:

- When converting from ms to ticks, instead of using hardware cycles
  per tick, use hardware cycles per second. This ensures that the
  multiplication is done before the division, increasing precision.
- When converting from ticks to ms, instead of using cycles per tick
  and cycles per sec, use ticks per sec. This too increases the
  precision.

The concept is to make the dividend as large as possible compared to the
divisor in order to lose as little precision as possible.

Fixes #8898
Fixes #9459
Fixes #9466
Fixes #9468

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: include/kernel.h [hunk 1]
```diff
@@ -1363,7 +1363,8 @@ static ALWAYS_INLINE s32_t _ms_to_ticks(s32_t ms)
 	/* use 64-bit math to keep precision */
 	return (s32_t)ceiling_fraction(
 		(s64_t)ms * sys_clock_hw_cycles_per_sec,
-		(s64_t)MSEC_PER_SEC * sys_clock_hw_cycles_per_tick);
+		((s64_t)MSEC_PER_SEC * sys_clock_hw_cycles_per_sec) /
+		 sys_clock_ticks_per_sec);
```
Comment (cvinayak) [inline include/kernel.h]: I think I had an extra space prefixed here.

Comment (carlescufi) [reply include/kernel.h]: you did, fixed now

**Review by cvinayak — APPROVED** [review]

**Comment by carlescufi** [comment]
@nashif not sure about the failures, seem related to stack overflow

**Review by nashif — APPROVED** [review]
