### PR TITLE
soc: esp32: fix memory-mapped reading address

### LINKED ISSUE #52764: boards: esp32c3_devkitm: unable to read memory-mapped flash memory
**Describe the bug**
It's fairly clear from the TRM [1] that external flash should be mapped to address `0x3c000000` (section 3.1) and inspecting `build/zephyr/zephyr.map` indeed shows that is the offset for simple binaries. However, doing an experiment shows that only a portion of memory seems to be mapped.

[1] https://www.espressif.com/sites/default/files/documentation/esp32-c3_technical_reference_manual_en.pdf

**Please also mention any information which could help others to understand
the problem you're facing**:
 - **What target platform are you using?**: `esp32c3_devkitm`
 - **What have you tried to diagnose or workaround this issue?**: I actually would prefer not to hack a workaround. This should be a bug that gets fixed.
 - **Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?**: no, it looks like it's always been broken
 - ...

**To Reproduce**

Flash a program to the device
```
west build -p auto -b esp32c3_devkitm -t flash samples/hello_world -- \
  -DCONFIG_FLASH=y \
  -DCONFIG_SHELL=y \
  -DCONFIG_FLASH_PAGE_LAYOUT=y \
  -DCONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=n \
  -DCONFIG_CRC=y \
  -DCONFIG_CRC_SHELL=y \
  -DCONFIG_HEAP_MEM_POOL_SIZE=16384
```

Open a terminal with this (your exact tty device might vary):
```
minicom -D /dev/tty.usbserial-1130 -b 115200
```

Run the following commands:
```
flash erase flash-controller@60002000 0x00210000 0x1000
flash load flash-controller@60002000 0x00210000 0x20
```

On the host, run
```
# generate 0x01 to 0x20 in binary
for i in `seq 1 32`; do printf "%02x " $i; done | xxd -r -p - > /tmp/output.bin
crc32 /tmp/output.bin
# 87e6ec25
# write 32-bytes to the image-scratch partition
dd if=/tmp/output.bin of=/dev/tty.usbserial-1130 bs=32 count=1
```

Then on the device,
```
uart:~$ flash read flash-controller@60002000 0x00210000 0x20
00210000: 01 02 03 04 05 06 07 08  09 0a 0b 0c 0d 0e 0f 10 |........ ........|
00210010: 11 12 13 14 15 16 17 18  19 1a 1b 1c 1d 1e 1f 20 |........ ....... |
```

I was under the assumption that the `image-scratch` partition would have been mapped in at `0x3c000000 + 0x00210000`, but then this just reads 0 ((I would expect 1).
 ```
devmem 0x3c210000 8
Using data width 8
Read value 0x0
```

Note: if the `devmem dump` command is available (#52747), then the entire region can be dumped with
```
uart:~$ devmem dump -a 0x3c210000 -s 32 -w 32
3C210000: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........|
3C210010: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........|
```

The fact that it's returning zero indicates to me that the area of memory has not been mapped. How does one ensure that external flash is mapped on this device?

Ultimately, I would expect the same CRC of `87e6ec25`, but there is a mismatch (since `devmem` fails to read back the same data, that is understandable).
```
crc 0x3c210000 32
0x190a55ad
```

**Expected behavior**
I would imagine that data written to memory-mapped flash could be read-back via memory reads.

**Impact**
It's a showstopper for the `icev_wireless`, which I hope to demonstrate at RISC-V Summit.

**Logs and console output**
See above

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Any
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.15.2
 - Commit SHA or Version used: dc26a617d792f0a41b96c1965f1a967372caf8cb

**Additional context**
To give some more context, I need to be able to load a 104090-byte FPGA bitstream into flash and then program the FPGA over SPI (the former already works, and the only thing preventing the latter from working is this issue). Draft PR for `icev_wireless` is #52765.

### PR DESCRIPTION
**Pull request by sylvioalves**
ESP32 flash_mmap() function requires `_rodata_reserved_start` address
to be at the beginning of RODATA. This allows adding memory-mapped flash
areas.

This also adds a sample code describing a way to use it.

Fixes #52764

### CODE REVIEW

**Review by cfriedt — APPROVED** [review]

File: samples/boards/esp32/flash_memory_mapped/src/main.c [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+	size_t size = FIXED_PARTITION_SIZE(scratch_partition);
+
+	flash_device = DEVICE_DT_GET(DT_CHOSEN(zephyr_flash_controller));
+	if (!device_is_ready(flash_device)) {
+		printk("%s: device not ready.\n", flash_device->name);
+		return 0;
+	}
+
+	/* map selected region */
+	spi_flash_mmap(address, size, SPI_FLASH_MMAP_DATA, &mem_ptr, &handle);
```
Comment (marekmatej) [inline samples/boards/esp32/flash_memory_mapped/src/main.c:35]: here it would be useful to check the proper (64kB) alignment of the source address. Something like `if (((64*1024)-1) & address)`

**Review by marekmatej — APPROVED** [review]
Except of comments LGTM
