### PR TITLE
tests: work_queue: initialize msg

### LINKED ISSUE #50343: uninitialized variable in kernel.workqueue test
**Describe the bug**

```
/__w/zephyr/zephyr/tests/kernel/workq/work_queue/src/main.c: In function 'msg_provider_thread':
/__w/zephyr/zephyr/tests/kernel/workq/work_queue/src/main.c:735:9: error: 'msg' may be used uninitialized [-Werror=maybe-uninitialized]
  735 |         k_msgq_put(&triggered_from_msgq_test.msgq, &msg, K_NO_WAIT);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**

```
scripts/twister -v -N -M -p qemu_x86_tiny@768 -s tests/kernel/workq/work_queue/kernel.workqueue
```

**Expected behavior**

No uninitialised vars

**Impact**

Uninitialised vars

**Logs and console output**

```
Loading Zephyr default modules (Zephyr base).
-- Application: /__w/zephyr/zephyr/tests/kernel/workq/work_queue
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter 
-- Cache files will be written to: /__w/zephyr/zephyr/.cache
-- Zephyr version: 3.2.0-rc2 (/__w/zephyr/zephyr)
-- Found west (found suitable version "0.13.1", minimum required is "0.7.1")
-- Board: qemu_x86_tiny, Revision: 768
-- Found host-tools: zephyr 0.15.0 (/opt/toolchains/zephyr-sdk-0.15.0)
-- Found toolchain: zephyr 0.15.0 (/opt/toolchains/zephyr-sdk-0.15.0)
-- Found Dtc: /opt/toolchains/zephyr-sdk-0.15.0/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /__w/zephyr/zephyr/boards/x86/qemu_x86/qemu_x86_tiny.dts
-- Found devicetree overlay: /__w/zephyr/zephyr/boards/x86/qemu_x86/qemu_x86_tiny_768.overlay
unit address and first address in 'reg' (0x100000) don't match for /memory@0
-- Generated zephyr.dts: /__w/zephyr/zephyr/twister-out/qemu_x86_tiny@768/tests/kernel/workq/work_queue/kernel.workqueue/zephyr/zephyr.dts
-- Generated devicetree_generated.h: /__w/zephyr/zephyr/twister-out/qemu_x86_tiny@768/tests/kernel/workq/work_queue/kernel.workqueue/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: /__w/zephyr/zephyr/twister-out/qemu_x86_tiny@768/tests/kernel/workq/work_queue/kernel.workqueue/zephyr/dts.cmake

warning: X86_COMMON_PAGE_TABLE (defined at arch/x86/Kconfig:333) was assigned the value 'y' but got
the value 'n'. Check these unsatisfied dependencies: USERSPACE (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_X86_COMMON_PAGE_TABLE and/or look up
X86_COMMON_PAGE_TABLE in the menuconfig/guiconfig interface. The Application Development Primer,
Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be
helpful too.

Parsing /__w/zephyr/zephyr/Kconfig
Loaded configuration '/__w/zephyr/zephyr/boards/x86/qemu_x86/qemu_x86_tiny_defconfig'
Merged configuration '/__w/zephyr/zephyr/boards/x86/qemu_x86/qemu_x86_tiny_768.conf'
Merged configuration '/__w/zephyr/zephyr/tests/kernel/workq/work_queue/prj.conf'
Configuration saved to '/__w/zephyr/zephyr/twister-out/qemu_x86_tiny@768/tests/kernel/workq/work_queue/kernel.workqueue/zephyr/.config'
Kconfig header saved to '/__w/zephyr/zephyr/twister-out/qemu_x86_tiny@768/tests/kernel/workq/work_queue/kernel.workqueue/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/toolchains/zephyr-sdk-0.15.0/x86_64-zephyr-elf/bin/x86_64-zephyr-elf-gcc
CMake Warning at ../../../../subsys/random/CMakeLists.txt:11 (message):
  

      Warning: CONFIG_TEST_RANDOM_GENERATOR is not a truly random generator.
      This capability is not secure and it is provided for testing purposes only.
      Use it carefully.


-- Configuring done
-- Generating done
-- Build files have been written to: /__w/zephyr/zephyr/twister-out/qemu_x86_tiny@768/tests/kernel/workq/work_queue/kernel.workqueue
[1/150] Preparing syscall dependency handling

[2/150] Generating include/generated/version.h
-- Zephyr version: 3.2.0-rc2 (/__w/zephyr/zephyr), build: v3.2.0-rc2
[3/150] Generating misc/generated/syscalls_subdirs.trigger
[4/150] Generating misc/generated/syscalls.json, misc/generated/struct_tags.json
[5/150] Generating include/generated/syscall_dispatch.c, include/generated/syscall_list.h
[6/150] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h, include/generated/otype-to-size.h
[7/150] Generating include/generated/driver-validation.h
[8/150] Building C object zephyr/CMakeFiles/offsets.dir/arch/x86/core/offsets/offsets.c.obj
[9/150] Generating include/generated/offsets.h
[10/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc32c_sw.c.obj
[11/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc32_sw.c.obj
[12/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc16_sw.c.obj
[13/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc8_sw.c.obj
[14/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc7_sw.c.obj
[15/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/dec.c.obj
[16/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/hex.c.obj
[17/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/timeutil.c.obj
[18/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_packaged.c.obj
[19/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf.c.obj
[20/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/notify.c.obj
[21/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/multi_heap.c.obj
[22/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/printk.c.obj
[23/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/sem.c.obj
[24/150] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/logging/log_minimal.c.obj
[25/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/fdtable.c.obj
[26/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/onoff.c.obj
[27/150] Building C object zephyr/CMakeFiles/zephyr.dir/misc/generated/configs.c.obj
[28/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/rb.c.obj
[29/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/thread_entry.c.obj
[30/150] Generating linker_zephyr_pre0.cmd
[31/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_complete.c.obj
[32/150] Generating linker_zephyr_pre1.cmd
[33/150] Building C object CMakeFiles/app.dir/src/main.c.obj
FAILED: CMakeFiles/app.dir/src/main.c.obj 
ccache /opt/toolchains/zephyr-sdk-0.15.0/x86_64-zephyr-elf/bin/x86_64-zephyr-elf-gcc -DKERNEL -DPERF_OPT -DTC_RUNID=997fe94e4fba5b9d7b7baa5674ce2397 -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/include -Izephyr/include/generated -I/__w/zephyr/zephyr/soc/x86/ia32 -I/__w/zephyr/zephyr/subsys/testsuite/include -I/__w/zephyr/zephyr/subsys/testsuite/ztest/include -I/__w/zephyr/zephyr/modules/hal_nxp/. -isystem /__w/zephyr/zephyr/lib/libc/minimal/include -isystem /opt/toolchains/zephyr-sdk-0.15.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/12.1.0/include -isystem /opt/toolchains/zephyr-sdk-0.15.0/x86_64-zephyr-elf/bin/../lib/gcc/x86_64-zephyr-elf/12.1.0/include-fixed -m32  -fno-strict-aliasing -O0 -imacros /__w/zephyr/zephyr/twister-out/qemu_x86_tiny@768/tests/kernel/workq/work_queue/kernel.workqueue/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -gdwarf-4 -fdiagnostics-color=always -m32 -Wa,--divide --sysroot=/opt/toolchains/zephyr-sdk-0.15.0/x86_64-zephyr-elf/x86_64-zephyr-elf -imacros /__w/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -Werror -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/zephyr/zephyr/tests/kernel/workq/work_queue=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -fprofile-arcs -ftest-coverage -fno-inline -mno-mmx -mno-sse -std=c99 -nostdinc -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj -c /__w/zephyr/zephyr/tests/kernel/workq/work_queue/src/main.c
/__w/zephyr/zephyr/tests/kernel/workq/work_queue/src/main.c: In function 'msg_provider_thread':
/__w/zephyr/zephyr/tests/kernel/workq/work_queue/src/main.c:735:9: error: 'msg' may be used uninitialized [-Werror=maybe-uninitialized]
  735 |         k_msgq_put(&triggered_from_msgq_test.msgq, &msg, K_NO_WAIT);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /__w/zephyr/zephyr/include/zephyr/kernel.h:5881,
                 from /__w/zephyr/zephyr/tests/kernel/workq/work_queue/src/main.c:18:
zephyr/include/generated/syscalls/kernel.h:1129:19: note: by argument 2 of type 'const void *' to 'k_msgq_put' declared here
 1129 | static inline int k_msgq_put(struct k_msgq * msgq, const void * data, k_timeout_t timeout)
      |                   ^~~~~~~~~~
/__w/zephyr/zephyr/tests/kernel/workq/work_queue/src/main.c:733:14: note: 'msg' declared here
  733 |         char msg[MSG_SIZE];
      |              ^~~
cc1: all warnings being treated as errors
[34/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/assert.c.obj
[35/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/heap-validate.c.obj
[36/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/bitarray.c.obj
[37/150] Building C object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/cpuhalt.c.obj
[38/150] Building ASM object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/ia32/excstub.S.obj
[39/150] Building C object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/cpuid.c.obj
[40/150] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/testsuite/coverage/coverage.c.obj
[41/150] Building ASM object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/ia32/crt0.S.obj
[42/150] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/tracing/tracing_none.c.obj
[43/150] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/heap.c.obj
[44/150] Building ASM object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/ia32/intstub.S.obj
[45/150] Building C object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/spec_ctrl.c.obj
[46/150] Building C object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/prep_c.c.obj
[47/150] Building C object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/ia32/irq_manage.c.obj
[48/150] Building C object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/early_serial.c.obj
[49/150] Building C object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/x86_mmu.c.obj
[50/150] Building C object zephyr/arch/arch/x86/core/CMakeFiles/arch__x86__core.dir/fatal.c.obj
ninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr SDK 0.15.0
 - Commit SHA: 2829de75d1ae88dc53bc6e85d8f8e59ac3cca8d3

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Make sure msg is initialized before being used, fixes compiler warning:

  main.c:735:9: error: 'msg' may be used uninitialized

Fixes #50343

### CODE REVIEW

File: tests/kernel/workq/work_queue/src/main.c [hunk 1]
```diff
@@ -730,14 +730,14 @@ static void msg_provider_thread(void *p1, void *p2, void *p3)
 	ARG_UNUSED(p2);
 	ARG_UNUSED(p3);
 
-	char msg[MSG_SIZE];
+	char msg[MSG_SIZE] = {0};
```
Comment (stephanosio) [inline tests/kernel/workq/work_queue/src/main.c:733]: Nit: spacing

```suggestion
	char msg[MSG_SIZE] = { 0 };
```

File: tests/kernel/workq/work_queue/src/main.c [hunk 2]
```diff
@@ -730,14 +730,14 @@ static void msg_provider_thread(void *p1, void *p2, void *p3)
...
 
 	k_msgq_put(&triggered_from_msgq_test.msgq, &msg, K_NO_WAIT);
 }
 
 static void triggered_from_msgq_work_handler(struct k_work *work)
 {
-	char msg[MSG_SIZE];
+	char msg[MSG_SIZE] = {0};
```
Comment (stephanosio) [inline tests/kernel/workq/work_queue/src/main.c:740]:
```suggestion
	char msg[MSG_SIZE] = { 0 };
```

File: tests/kernel/workq/work_queue/src/main.c (hunk 1 above)
Comment (fabiobaltieri) [reply tests/kernel/workq/work_queue/src/main.c]: Done.

File: tests/kernel/workq/work_queue/src/main.c (hunk 2 above)
Comment (fabiobaltieri) [reply tests/kernel/workq/work_queue/src/main.c]: Done.

**Review by stephanosio — DISMISSED** [review]

**Review by dcpleung — DISMISSED** [review]

File: tests/kernel/workq/work_queue/src/main.c [hunk 3]
```diff
@@ -730,14 +730,14 @@ static void msg_provider_thread(void *p1, void *p2, void *p3)
...
-	char msg[MSG_SIZE];
+	char msg[MSG_SIZE] = { 0 };
 
 	k_msgq_put(&triggered_from_msgq_test.msgq, &msg, K_NO_WAIT);
 }
 
 static void triggered_from_msgq_work_handler(struct k_work *work)
 {
-	char msg[MSG_SIZE];
+	char msg[MSG_SIZE] = { 0 };
```
Comment (andyross) [inline tests/kernel/workq/work_queue/src/main.c:740]: No need to initialize this one, right?  k_msgq_get() is going to fill it.  This is a common idiom; there should be no warning condition about passing an uninitialized local array via a non-const pointer, right?

**Review by andyross — DISMISSED** [review]
Pedantic nitpick

File: tests/kernel/workq/work_queue/src/main.c (hunk 3 above)
Comment (fabiobaltieri) [reply tests/kernel/workq/work_queue/src/main.c:740]: Hey you are right! Sorry got carried on and did not realize the two calls were different.

**Comment by fabiobaltieri** [comment]
> Pedantic nitpick

Ah not at all, flash space adds up for initializing stuff that does not need to... I mean it's only a test but I think there's value in having the right patterns throughout the code base.

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
