### PR TITLE
subsys: display: cfb: Fix tile drawing processing

### LINKED ISSUE #92860: subsys: display: cfb: tests: tests fail
### Describe the bug

Running the cfb tests fails.
I'm trying to run them for native_sim.

### Regression

- [ ] This is a regression.

### Steps to reproduce

`west build -p auto -b native_sim/native/64 zephyr/tests/subsys/display/cfb/basic -t run`

### Relevant log output

```shell
*** Booting Zephyr OS build v4.2.0-rc1-253-gde001f7c14b6 ***
Running TESTSUITE clear
===================================================================
START - test_clear_false
ASSERTION FAIL [(desc->pitch * 4U * desc->height) <= desc->buf_size] @ WEST_TOPDIR/zephyr/drivers/display/display_sdl.c:183
        Input buffer too small
@ WEST_TOPDIR/zephyr/lib/os/assert.c:43
[00:00:00.000,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:00.000,000] <err> os: Current thread: 0x4769a0 (test_clear_false)
[00:00:00.000,000] <err> os: Halting system
Exiting due to fatal error
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: Linux
- Toolchain: Zephyr SDK
- Commit: master

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by soburi**
There is a bug in the CFB tile drawing process, so we will fix it.

We will also modify testcase.yaml to make it easier to perform testing using twister.

Fix #92860
But still fail circle drawing tests.

#96313 is required to be merged prior.

### CODE REVIEW

**Review by VynDragon — DISMISSED** [review]
Ran sample with added call to invert area
 bl616 + SSd1322 htiled
 esp32s3 + ch1116 vtiled.
all good.

**Comment by soburi** [comment]
@JarmouniA 

Could you take a look, please?

File: subsys/fb/cfb.c [hunk 1]
```diff
@@ -245,13 +245,11 @@ static uint8_t draw_char_htmono(const struct char_framebuffer *fb,
...
 		for (size_t g_x = 0; g_x < fptr->width; g_x++) {
 			const int16_t fb_x = x + g_x;
-			const size_t fb_pixel_index = fb_y * fb->x_res + fb_x;
-			const size_t fb_byte_index = fb_pixel_index / 8;
+			const size_t fb_byte_index = (fb_x / 8) + (fb_y * (fb->x_res / 8));
 			uint8_t byte;
 			uint8_t pixel_value;
 
 			if (fb_x < 0 || fb->x_res <= fb_x || fb_y < 0 || fb->y_res <= fb_y) {
-				g_y++;
```
Comment (JarmouniA) [inline subsys/fb/cfb.c:254]: Could you put this in a separate commit?

File: subsys/fb/cfb.c [hunk 2]
```diff
@@ -245,13 +245,11 @@ static uint8_t draw_char_htmono(const struct char_framebuffer *fb,
 
 		for (size_t g_x = 0; g_x < fptr->width; g_x++) {
 			const int16_t fb_x = x + g_x;
-			const size_t fb_pixel_index = fb_y * fb->x_res + fb_x;
-			const size_t fb_byte_index = fb_pixel_index / 8;
+			const size_t fb_byte_index = (fb_x / 8) + (fb_y * (fb->x_res / 8));
```
Comment (JarmouniA) [inline subsys/fb/cfb.c]: Unnecessary change and unrelated to the fixes.

Comment (JarmouniA) [reply subsys/fb/cfb.c]: Also can give a different (incorrect?) result if fb->x_res is not divisible by 8

File: subsys/fb/cfb.c (hunk 1 above)
Comment (soburi) [reply subsys/fb/cfb.c:254]: Thank you for your review, and sorry for my late response.

I split the commit.

File: subsys/fb/cfb.c (hunk 2 above)
Comment (soburi) [reply subsys/fb/cfb.c]: > Unnecessary change and unrelated to the fixes.

Reverted.

> Also can give a different (incorrect?) result if fb->x_res is not divisible by 8


Since additional tests are required, this PR will not be addressed.
A separate issue has been created.

https://github.com/zephyrproject-rtos/zephyr/issues/104106

**Review by JarmouniA — APPROVED** [review]

**Review by VynDragon — APPROVED** [review]
