### PR TITLE
dts: nrf: dts.fixup cleanup for nRF series

### LINKED ISSUE #10658: Cannot use SPI_0 on nRF52810
After the SPI driver configuration was moved to device tree (see #9781), the SPI_0 device became unusable on nRF52810. Compilation fails with a bunch of errors like this:
```
zephyr/include/generated/generated_dts_board.h:305:34: error: 'NORDIC_NRF_SPI_40003000_SCK_PIN' undeclared (first use in this function); did you mean 'NORDIC_NRF_SPI_40004000_SCK_PIN'?
 #define CONFIG_SPI_0_NRF_SCK_PIN NORDIC_NRF_SPI_40003000_SCK_PIN
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This is because, unlike in other chips from the nRF52 family, the base address of the SPIM0 peripheral in nRF52810 is [0x40004000](https://github.com/zephyrproject-rtos/zephyr/blob/master/dts/arm/nordic/nrf52810.dtsi#L85), not 0x40003000 as expected by [the common nrf52 fixup file](https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/nordic_nrf/nrf52/dts_fixup.h#L78).

### PR DESCRIPTION
**Pull request by Mierunski**
All dts defines for nRF series are now extracted through aliases instead of dts.fixup files.
I left NAME defines for compatibility with examples and other drivers.
I moved WNCM14A2A dts.fixups to board level, but they should also be replaced with aliases and overlay files at example level.

Fixes #10658

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
So the use of non-CONFIG_ defines is something we've been trying to avoid.  I guess if we want to go in this direction, we should start create DT_ prefix defines

**Comment by Mierunski** [comment]
Should I use for example DT_NRF_I2C or DT_I2C ?

**Comment by anangl** [comment]
@Mierunski DT_ is sufficient IMO. We'll have then:
```
IRQ_CONNECT(DT_I2C_0_IRQ, DT_I2C_0_IRQ_PRIORITY, ...

gpio0 = get_device_binding(DT_GPIO_0_LABEL);
```
Should work.

**Comment by galak** [comment]
> @Mierunski DT_ is sufficient IMO. We'll have then:
> 
> ```
> IRQ_CONNECT(DT_I2C_0_IRQ, DT_I2C_0_IRQ_PRIORITY, ...
> 
> gpio0 = get_device_binding(DT_GPIO_0_LABEL);
> ```
> Should work.

As I think about this more, I worry about this since we are using a convention based on aliases, I guess I'd rather us focus our efforts on using code generation to remove dts.fixup and not introduce a new convention related to aliases (I know we do this some already for GPIOs w/LEDs & BUTTONs).

**Comment by Mierunski** [comment]
Using code generation will be next step

**Comment by Mierunski** [comment]
@galak @anangl I changed prefix do DT_

**Review by anangl — APPROVED** [review]

**Comment by anangl** [comment]
@Mierunski _boards/arm/nrf52840_pca10056/dts.fixup_ should be also renamed to _dts_fixup.h_

**Comment by Mierunski** [comment]
@anangl Fixed

**Comment by carlescufi** [comment]
@galak can you revisit please?

**Review by carlescufi — APPROVED** [review]

**Comment by galak** [comment]
> @galak @anangl I changed prefix to DT_

As I mentioned before, I'd rather us stick with the dts fixup file for now and not introduce this style of DT_ usage.  Lets focus on the code generation solution.

**Comment by anangl** [comment]
@galak Merging this PR will not preclude switching to code generation in the future. And these changes would help us a lot since maintaining the fixups in their current form is a real pain. We don't introduce any new mechanism, we just want to use the functionality already present and used in Zephyr to save some time that we would otherwise need to waste on these fixups.

**Comment by carlescufi** [comment]
> @galak Merging this PR will not preclude switching to code generation in the future. And these changes would help us a lot since maintaining the fixups in their current form is a real pain. We don't introduce any new mechanism, we just want to use the functionality already present and used in Zephyr to save some time that we would otherwise need to waste on these fixups.

@galak I agree with @anangl here. This PR is mostly about cleaning up the fixup files in order to save time on their maintenance. Is there something we can do in order to reduce this maintenance burden while at the same time deferring the tough decisions until the code generation changes are merged? This might take a while and in the meantime it would be beneficial that we did not have to spend so much time on those.

**Comment by Mierunski** [comment]
> Additionally, what happens if I have a GPIO expander over I2C, should I give it an alias of dt-i2c-3? What happens when a new nordic SoC has a 3rd I2C controller, now the defines we generate using this method aren't unique.

I don't understand why someone would want to name GPIO expander dt-i2c-3? But if someone really wanted to do such a thing, same could be done with dts_fixup:
```
#define CONFIG_I2C_3_DEV_NAME		NORDIC_NRF_I2C_40003000_SEMTECH_SX1509B_3E_LABEL
#define CONFIG_I2C_3_ADDR		NORDIC_NRF_I2C_40003000_SEMTECH_SX1509B_3E_BASE_ADDRESS
#define CONFIG_I2C_3_MASTER_DEV_NAME	NORDIC_NRF_I2C_40003000_SEMTECH_SX1509B_3E_BUS_NAME
```
I really don't see any point in doing it. It's a gpio expander, more suited alias would be something like dt-gpio-sx1509b-0
I don't really think it would be possible to get a gpio expander with alias name dt-i2c through PR.


> With this PR nordic platforms are different from all the others in how dts_fixups.h are used and defined vs all other SoC/boards.

It is not a new concept, See PR: #7012 especially files in boards: [    zephyr/boards/arm/frdm_k64f/frdm_k64f.dts](https://github.com/galak/zephyr/blob/1d6da0991759a229458b0155e6c679d1d2404fe9/boards/arm/frdm_k64f/frdm_k64f.dts)

It is easier for us to have defines straight from dts to code, instead of longer path dts->dts_fixup.h->code and I don't see how it has any negative effect on the whole project. It is already used and it's time-saving.

**Comment by galak** [comment]
> It is not a new concept, See PR: #7012 especially files in boards: [ zephyr/boards/arm/frdm_k64f/frdm_k64f.dts](https://github.com/galak/zephyr/blob/1d6da0991759a229458b0155e6c679d1d2404fe9/boards/arm/frdm_k64f/frdm_k64f.dts)
> 
> It is easier for us to have defines straight from dts to code, instead of longer path dts->dts_fixup.h->code and I don't see how it has any negative effect on the whole project. It is already used and it's time-saving.

Setting aliases like the frdm_k64f.dts and using them beyond the convention we have for LED & BUTTONs is a completely different thing.  I've got no issue if you want to add aliases for your devices into the .dts files.  We don't have any other cases I'm aware of that we directly use aliased defines in the generated file for things like address/irq/irq priority.

**Comment by galak** [comment]
> I don't understand why someone would want to name GPIO expander dt-i2c-3? But if someone really wanted to do such a thing, same could be done with dts_fixup:
> 
> ```
> #define CONFIG_I2C_3_DEV_NAME		NORDIC_NRF_I2C_40003000_SEMTECH_SX1509B_3E_LABEL
> #define CONFIG_I2C_3_ADDR		NORDIC_NRF_I2C_40003000_SEMTECH_SX1509B_3E_BASE_ADDRESS
> #define CONFIG_I2C_3_MASTER_DEV_NAME	NORDIC_NRF_I2C_40003000_SEMTECH_SX1509B_3E_BUS_NAME
> ```
> I really don't see any point in doing it. It's a gpio expander, more suited alias would be something like dt-gpio-sx1509b-0
> I don't really think it would be possible to get a gpio expander with alias name dt-i2c through PR.
> 
> >

This isn't the greatest example, but one of the issues that dts_fixup.h is dealing with is how to map a given device to an instance id.  That mapping needs to working across SoC instances where the same driver ends up being used.  So using something like aliases as the means to do this mapping is fragile in my opinion.  I was trying to provide a psuedo-real example to show that fragility.

**Comment by Mierunski** [comment]
> This isn't the greatest example, but one of the issues that dts_fixup.h is dealing with is how to map a given device to an instance id. That mapping needs to working across SoC instances where the same driver ends up being used. So using something like aliases as the means to do this mapping is fragile in my opinion. I was trying to provide a psuedo-real example to show that fragility.

I don't see how using dts_fixup is less fragile than using aliases. If you put a wrong alias name it stops working, and if you put wrong define in dts_fixup it also stops working.

**Comment by anangl** [comment]
@galak
> I don't see how maintaining the fixups is that much of a pain. Once the fixup is set for a given set of peripherals I doesnt change much. So the maintenance burden seems pretty low. You are introducing a new convention of how drivers and dts naming is expected to be handled.

The thing is that we are still lacking dts entries for several peripherals, thus when writing "maintaining the fixups in their current form" I actually meant adding new items to the fixup files. For instance, I need to add nodes for our PWM peripheral. We have got 4 instances of this peripheral, each instance has 4 channels and for every channel I need to provide the possibility of assigning a pin (all are optional). So I will end up with a bunch of such constructs as these for [UART optional pins](https://github.com/zephyrproject-rtos/zephyr/blob/master/soc/arm/nordic_nrf/nrf52/dts_fixup.h#L17). But it doesn't end there, things get even worse when the access to the peripherals can be made from secure and non secure domain in Armv8-m:  in this case for each peripheral I need to double the fixups since there are two base addresses. Any update of such structure (during the PR review for instance) becomes complicated and error-prone. This I consider a pain. And actually a waste of time as the fixups are supposed to disappear at some point (but that point might still be quite far away in the future). By using aliases we could make the process of moving drivers' configuration to dts simpler, and therefore faster.

I think I see your point regarding introducing a new convention. Although it was not our intention, I agree, by using DT_ prefixes we would differ too much from the others. And people might get confused because of this. What about getting back to CONFIG_ prefixes? This way the code in drivers would look the same as presently. The only difference would be the fixups being generated automatically via aliases instead of written down in the dts_fixup.h file. We could provide a comment in this file instead of the actual fixups to help people understand this. The content of the generated_dts_board.h file would be almost the same. Could such solution appear acceptable to you?

**Comment by anangl** [comment]
@galak See also #10658. We would not have got into this trouble if we used aliases to generate fixups automatically. This is a similar problem as the one with secure and non secure accesses I mentioned before - fixups are strictly dependent on the peripheral base addresses. With the current form of the fixup file we will need another `#if` to fix this issue.

File: boards/arm/nrf52840_pca10056/dts_fixup.h [hunk 1]
```diff
@@ -0,0 +1,19 @@
+/* Board level DTS fixup file */
+
+#define DT_WNCM14A2A_UART_DRV_NAME			DT_NORDIC_NRF_UARTE_40028000_WNCM14A2A_BUS_NAME
```
Comment (galak) [inline boards/arm/nrf52840_pca10056/dts_fixup.h]: Why is this here?  We moved wcm14a2a out of the board.dts:

commit edefd7dc7d5f6b6eed1408d46fd53c0cacc01e69
Author: Kumar Gala <kumar.gala@linaro.org>
Date:   Thu Nov 15 09:58:49 2018 -0600

    boards: nrf52840_pca10056: move modem configurtion to overlay

File: drivers/i2c/i2c_nrfx_twi.c [hunk 2]
```diff
@@ -136,29 +136,29 @@ static int init_twi(struct device *dev, const nrfx_twi_config_t *config)
 	return 0;
 }
 
-#define I2C_NRFX_TWI_DEVICE(idx)					\
-	static int twi_##idx##_init(struct device *dev)			\
-	{								\
-		IRQ_CONNECT(DT_I2C_##idx##_IRQ,			\
```
Comment (galak) [inline drivers/i2c/i2c_nrfx_twi.c]: We'll need to rebase this once the I2C PRI fix (#11427) goes in.

File: drivers/i2c/i2c_nrfx_twi.c [hunk 3]
```diff
@@ -136,29 +136,29 @@ static int init_twi(struct device *dev, const nrfx_twi_config_t *config)
...
+		};							   \
+		return init_twi(dev, &config);				   \
+	}								   \
+	static struct i2c_nrfx_twi_data twi_##idx##_data = {		   \
+		.sync = _K_SEM_INITIALIZER(twi_##idx##_data.sync, 0, 1)	   \
+	};								   \
+	static const struct i2c_nrfx_twi_config twi_##idx##_config = {	   \
+		.twi = NRFX_TWI_INSTANCE(idx)				   \
+	};								   \
+	DEVICE_AND_API_INIT(twi_##idx, DT_NORDIC_NRF_I2C_I2C_##idx##_LABEL,\
```
Comment (galak) [inline drivers/i2c/i2c_nrfx_twi.c]: technically I wouldn't change the name right now since sensor drivers still use CONFIG_I2C_x_NAME.  But I'm ok if you want to.

File: soc/arm/nordic_nrf/nrf52/dts_fixup.h [hunk 4]
```diff
@@ -2,166 +2,30 @@
...
-#if defined(DT_NORDIC_NRF_CC310_5002A000_BASE_ADDRESS)
-#define DT_CC310_CTL_BASE_ADDR	DT_NORDIC_NRF_CC310_5002A000_BASE_ADDRESS
-#define DT_CC310_CTL_NAME		DT_NORDIC_NRF_CC310_5002A000_LABEL
-#define DT_CC310_BASE_ADDR		DT_ARM_CRYPTOCELL_310_5002B000_BASE_ADDRESS
-#define DT_CC310_NAME		DT_ARM_CRYPTOCELL_310_5002B000_LABEL
-#define DT_CC310_IRQ		DT_ARM_CRYPTOCELL_310_5002B000_IRQ_0
-#define DT_CC310_IRQ_PRI		DT_ARM_CRYPTOCELL_310_5002B000_IRQ_0_PRIORITY
-#endif
-
-#define DT_WNCM14A2A_UART_DRV_NAME			DT_NORDIC_NRF_UARTE_40028000_WNCM14A2A_BUS_NAME
```
Comment (galak) [inline soc/arm/nordic_nrf/nrf52/dts_fixup.h]: Ah, this should move to  samples/net/lwm2m_client/dts_fixup.h

**Review by galak — DISMISSED** [review]
Some minor cleanups and comments

File: soc/arm/nordic_nrf/nrf51/dts_fixup.h [hunk 5]
```diff
@@ -57,26 +28,9 @@
 #define DT_QDEC_LED_PRE		DT_NORDIC_NRF_QDEC_40012000_LED_PRE
 #define DT_QDEC_STEPS		DT_NORDIC_NRF_QDEC_40012000_STEPS
```
Comment (anangl) [inline soc/arm/nordic_nrf/nrf51/dts_fixup.h]: These macros defined for QDEC should be removed.

File: soc/arm/nordic_nrf/nrf52/dts_fixup.h [hunk 6]
```diff
@@ -2,166 +2,30 @@
...
 
-#define DT_SPI_3_BASE_ADDRESS       DT_NORDIC_NRF_SPI_4002B000_BASE_ADDRESS
-#define CONFIG_SPI_3_NAME               DT_NORDIC_NRF_SPI_4002B000_LABEL
-#define CONFIG_SPI_3_IRQ_PRI            DT_NORDIC_NRF_SPI_4002B000_IRQ_0_PRIORITY
-#define DT_SPI_3_IRQ                DT_NORDIC_NRF_SPI_4002B000_IRQ_0
-#define DT_SPI_3_NRF_SCK_PIN	DT_NORDIC_NRF_SPI_4002B000_SCK_PIN
-#define DT_SPI_3_NRF_MOSI_PIN	DT_NORDIC_NRF_SPI_4002B000_MOSI_PIN
-#define DT_SPI_3_NRF_MISO_PIN	DT_NORDIC_NRF_SPI_4002B000_MISO_PIN
-#define DT_SPI_3_NRF_CSN_PIN	DT_NORDIC_NRF_SPI_4002B000_CSN_PIN
+#define DT_QDEC_NAME			DT_NORDIC_NRF_QDEC_QDEC_0_LABEL
```
Comment (anangl) [inline soc/arm/nordic_nrf/nrf52/dts_fixup.h]: Do we need this? It does not seem to be used anywhere (apart from the driver that is updated in this PR).
Same story with `DT_USBD_NRF_NAME`.

File: soc/arm/nordic_nrf/nrf52/dts_fixup.h [hunk 7]
```diff
@@ -2,166 +2,30 @@
...
-#define DT_UART_1_CTS_PIN		DT_NORDIC_NRF_UARTE_40028000_CTS_PIN
-#endif
+#define CONFIG_UART_0_NAME		DT_NORDIC_NRF_UART_UART_0_LABEL
+#define CONFIG_UART_1_NAME		DT_NORDIC_NRF_UART_UART_1_LABEL
 
 #define DT_FLASH_DEV_NAME			DT_NRF_NRF52_FLASH_CONTROLLER_4001E000_LABEL
 
-#define DT_GPIO_P0_DEV_NAME		DT_NORDIC_NRF_GPIO_50000000_LABEL
+#define DT_GPIO_P0_DEV_NAME		DT_NORDIC_NRF_GPIO_GPIO_0_LABEL
 #if CONFIG_HAS_HW_NRF_GPIO1
```
Comment (anangl) [inline soc/arm/nordic_nrf/nrf52/dts_fixup.h]: I think we don't need this dependency on a Kconfig symbol here. `DT_GPIO_P1_DEV_NAME` can be defined without any conditions, just like `DT_GPIO_P0_DEV_NAME` is.

File: drivers/i2c/i2c_nrfx_twim.c [hunk 8]
```diff
@@ -137,26 +137,26 @@ static int init_twim(struct device *dev, const nrfx_twim_config_t *config)
...
+		};							    \
+		return init_twim(dev, &config);				    \
+	}								    \
+	static struct i2c_nrfx_twim_data twim_##idx##_data = {		    \
+		.sync = _K_SEM_INITIALIZER(twim_##idx##_data.sync, 0, 1)    \
+	};								    \
+	static const struct i2c_nrfx_twim_config twim_##idx##_config = {    \
+		.twim = NRFX_TWIM_INSTANCE(idx)				    \
+	};								    \
+	DEVICE_AND_API_INIT(twim_##idx, DT_NORDIC_NRF_I2C_I2C_##idx##_LABEL,\
```
Comment (anangl) [inline drivers/i2c/i2c_nrfx_twim.c]: This `DT_` macro could be moved to the next line to improve readability (same story in _i2c_nrfx_twi.c_) and the `\` characters below should be aligned with the above ones.

**Review by anangl — CHANGES_REQUESTED** [review]

**Comment by anangl** [comment]
You can also add "Fixes #10658" in the PR description.

File: drivers/serial/uart_nrfx_uarte.c [hunk 9]
```diff
@@ -502,42 +502,45 @@ static int uarte_instance_init(struct device *dev,
...
+	static const struct uarte_nrfx_config uarte_##idx##_config = {	       \
+		.uarte_regs = (NRF_UARTE_Type *)			       \
+			DT_NORDIC_NRF_UARTE_UART_##idx##_BASE_ADDRESS,	       \
+		UARTE_##idx##_CONFIG_INIT				       \
+	};								       \
+	static int uarte_##idx##_init(struct device *dev)		       \
+	{								       \
+		const struct uarte_init_config init_config = {		       \
+			.pseltxd = DT_NORDIC_NRF_UARTE_UART_##idx##_TX_PIN,     \
+			.pselrxd = DT_NORDIC_NRF_UARTE_UART_##idx##_RX_PIN,     \
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uarte.c]: All these `\` characters in the macro should be aligned (see also line 524). Currently these three lines exceed the 80 characters length limit.

**Comment by Mierunski** [comment]
@galak @anangl All changes should be fixed now

File: soc/arm/nordic_nrf/nrf52/dts_fixup.h [hunk 10]
```diff
@@ -2,150 +2,24 @@
...
-#define CONFIG_WDT_0_NAME		DT_NORDIC_NRF_WATCHDOG_40010000_LABEL
-#define DT_WDT_NRF_IRQ		DT_NORDIC_NRF_WATCHDOG_40010000_IRQ_WDT
-#define DT_WDT_NRF_IRQ_PRI		DT_NORDIC_NRF_WATCHDOG_40010000_IRQ_WDT_PRIORITY
+#define DT_SPI_0_NAME			DT_NORDIC_NRF_SPI_SPI_0_LABEL
+#define DT_SPI_1_NAME			DT_NORDIC_NRF_SPI_SPI_1_LABEL
+#define DT_SPI_2_NAME			DT_NORDIC_NRF_SPI_SPI_2_LABEL
+#define DT_SPI_3_NAME			DT_NORDIC_NRF_SPI_SPI_3_LABEL
 
-#if defined(DT_NORDIC_NRF_CC310_5002A000_BASE_ADDRESS)
-#define DT_CC310_CTL_BASE_ADDR	DT_NORDIC_NRF_CC310_5002A000_BASE_ADDRESS
```
Comment (ioannisg) [inline soc/arm/nordic_nrf/nrf52/dts_fixup.h]: Seems there are no "_NAME" defines for crypto. Is this intentional?

**Review by anangl — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
This looks fine now.

**Review by galak — APPROVED** [review]
