### PR TITLE
json: Fix multidimensional array support

### LINKED ISSUE #50801: JSON parser fails on multidimensional arrays
The following code examples are based on the current test case `test_json_decoding_array_array()`:

https://github.com/zephyrproject-rtos/zephyr/blob/489e8eb02c2a7bd46a9e73ee1a07a9bd20a61e98/tests/lib/json/src/main.c#L258-L271

1. Encoding data using an array-array descriptor

Encoding the sample data that is given in `test_json_decoding_array_array()` will fail - `json_obj_encode_buf()` won't even return.

```c++
struct elt {
  const char *name;
  int height;
};
struct array {
  struct elt objects;
};
struct obj_array_array {
  struct array objects_array[4];
  size_t objects_array_len;
};
static const struct json_obj_descr elt_descr[] = {
  JSON_OBJ_DESCR_PRIM(struct elt, name, JSON_TOK_STRING),
  JSON_OBJ_DESCR_PRIM(struct elt, height, JSON_TOK_NUMBER),
};
static const struct json_obj_descr array_descr[] = {
  JSON_OBJ_DESCR_OBJECT(struct array, objects, elt_descr),
};
static const struct json_obj_descr array_array_descr[] = {
  JSON_OBJ_DESCR_ARRAY_ARRAY(struct obj_array_array, objects_array, 4,
                             objects_array_len, array_descr, ARRAY_SIZE(array_descr)),
};

int ret;
struct obj_array_array obj_array_array_ts;
char encoded[] = "{\"objects_array\":["
                  "[{\"height\":168,\"name\":\"Simón Bolívar\"}],"
                  "[{\"height\":173,\"name\":\"Pelé\"}],"
                  "[{\"height\":195,\"name\":\"Usain Bolt\"}]]"
                 "}";
char buffer[sizeof(encoded) * 2];
ret = json_obj_parse(encoded, sizeof(encoded), array_array_descr, ARRAY_SIZE(array_array_descr), &obj_array_array_ts);
// now encode data again
ret = json_obj_encode_buf(array_array_descr, ARRAY_SIZE(array_array_descr), &obj_array_array_ts, buffer, sizeof(buffer));
```

As a side note, the encoded JSON string found in `test_json_decoding_array_array()` does not match the given descriptor as it describes a one-dimensional array. However, `json_obj_parse()` currently accepts that kind of (bad) input.
A correct JSON string would look like this:

```c++
char encoded[] = "{\"objects_array\":["
                  "{\"height\":168,\"name\":\"Simón Bolívar\"},"
                  "{\"height\":173,\"name\":\"Pelé\"},"
                  "{\"height\":195,\"name\":\"Usain Bolt\"}]"
                 "}";
```

2. Encoding a two-dimensional array

`json_obj_encode_buf()` does not return for this code encoding a two-dimensional array:

```c++
struct obj_array_array_array {
  struct obj_array_array objects_array_array[3];
  size_t objects_array_array_len;
};
const struct json_obj_descr array_array_array_descr[] = {
  JSON_OBJ_DESCR_ARRAY_ARRAY(struct obj_array_array_array, objects_array_array, 3,
                             objects_array_array_len, array_array_descr,
                             ARRAY_SIZE(array_array_descr)),
};

struct obj_array_array_array oaaa = {
  .objects_array_array = {
    [0] = {
      .objects_array = {
        [0] = { { .name = "Simón Bolívar",   .height = 168 } },
        [1] = { { .name = "Pelé",            .height = 173 } },
        [2] = { { .name = "Usain Bolt",      .height = 195 } },
      },
      .objects_array_len = 3
    },
    [1] = {
      .objects_array = {
        [0] = { { .name = "Muggsy Bogues",   .height = 160 } },
        [1] = { { .name = "Hakeem Olajuwon", .height = 213 } },
      },
      .objects_array_len = 2
    },
    [2] = {
      .objects_array = {
        [0] = { { .name = "Alex Honnold",    .height = 180 } },
        [1] = { { .name = "Hazel Findlay",   .height = 157 } },
        [2] = { { .name = "Daila Ojeda",     .height = 158 } },
        [3] = { { .name = "Albert Einstein", .height = 172 } },
      },
      .objects_array_len = 4
    },
  },
  .objects_array_array_len = 3,
};
const char encoded[] = "{\"objects_array_array\":["
  "[{\"name\":\"Simón Bolívar\",\"height\":168},"
   "{\"name\":\"Pelé\",\"height\":173},"
   "{\"name\":\"Usain Bolt\",\"height\":195}],"
  "[{\"name\":\"Muggsy Bogues\",\"height\":160},"
   "{\"name\":\"Hakeem Olajuwon\",\"height\":213}],"
  "[{\"name\":\"Alex Honnold\",\"height\":180},"
   "{\"name\":\"Hazel Findlay\",\"height\":157},"
   "{\"name\":\"Daila Ojeda\",\"height\":158},"
   "{\"name\":\"Albert Einstein\",\"height\":172}]"
  "]}";
char buffer[sizeof(encoded) * 2];
int ret;

ret = json_obj_encode_buf(array_array_array_descr, ARRAY_SIZE(array_array_array_descr),
                          &oaaa, buffer, sizeof(buffer));
```

3. Decoding a two-dimensional array

`json_obj_parse()` returns `-EINVAL` for this code decoding a two-dimensional array:

```c++
struct obj_array_array_array oaaa = {0};
char encoded[] = "{\"objects_array_array\":["
  "[{\"name\":\"Simón Bolívar\",\"height\":168},"
   "{\"name\":\"Pelé\",\"height\":173},"
   "{\"name\":\"Usain Bolt\",\"height\":195}],"
  "[{\"name\":\"Muggsy Bogues\",\"height\":160},"
   "{\"name\":\"Hakeem Olajuwon\",\"height\":213}],"
  "[{\"name\":\"Alex Honnold\",\"height\":180},"
   "{\"name\":\"Hazel Findlay\",\"height\":157},"
   "{\"name\":\"Daila Ojeda\",\"height\":158},"
   "{\"name\":\"Albert Einstein\",\"height\":172}]"
  "]}";
int ret;

ret = json_obj_parse(encoded, sizeof(encoded), array_array_array_descr,
                     ARRAY_SIZE(array_array_array_descr), &oaaa);
```

---

Note: Results are the same when using this slightly modified descriptor - which seems more correct - for the 2-dimensional array:

```c++
struct elt {
  const char *name;
  int height;
};
struct obj_array {
  struct elt objects_array[4];
  size_t objects_array_len;
};
struct obj_array_array {
  struct obj_array objects_array_array[3];
  size_t objects_array_array_len;
};
static const struct json_obj_descr elt_descr[] = {
  JSON_OBJ_DESCR_PRIM(struct elt, name, JSON_TOK_STRING),
  JSON_OBJ_DESCR_PRIM(struct elt, height, JSON_TOK_NUMBER),
};
static const struct json_obj_descr array_descr[] = {
  JSON_OBJ_DESCR_OBJ_ARRAY(struct obj_array, objects_array, 4,
                           objects_array_len, elt_descr, ARRAY_SIZE(elt_descr)),
};
static const struct json_obj_descr array_array_descr[] = {
  JSON_OBJ_DESCR_ARRAY_ARRAY(struct obj_array_array, objects_array_array, 3,
                             objects_array_array_len, array_descr,
                             ARRAY_SIZE(array_descr)),
};
```

### PR DESCRIPTION
**Pull request by mrfuchs**
This patch fixes support for encoding and decoding multidimensional arrays
as described by the JSON_OBJ_DESCR_ARRAY_ARRAY() macro.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/50801

### CODE REVIEW

**Comment by carlescufi** [comment]
@mrfuchs can you take a look at the CI failures?

File: tests/lib/json/src/main.c [hunk 1]
```diff
@@ -450,6 +486,130 @@ ZTEST(lib_json_test, test_json_obj_arr_decoding)
...
 }
 
+ZTEST(lib_json_test, test_json_2dim_arr_obj_encoding)
+{
+	struct obj_array_2dim obj_array_array_ts = {
+		.objects_array_array = {
+			[0] = {
+				.elements = {
+					[0] = { .name = "Simón Bolívar",   .height = 168 },
+					[1] = { .name = "Pelé",            .height = 173 },
```
Comment (andyross) [inline tests/lib/json/src/main.c:496]: What's our policy on UTF-8 in source code?  IIRC that's a C11 feature, right?

**Review by andyross — DISMISSED** [review]
Saw this languishing and figured I should give it an approval, even though it's not really my area (we don't really have a maintainer for JSON right now, I guess?).

Language wonks (@stephanosio @keith-packard ?) might care about the unicode string literals, though they seem harmless to me.

File: tests/lib/json/src/main.c (hunk 1 above)
Comment (stephanosio) [reply tests/lib/json/src/main.c:496]: There is no policy on the usage of Unicode characters in source files, as far as I know (cc @tejlmand @nashif).

The support for non-ASCII characters in source files is implementation defined; but, I do not think there are any modern compilers (as in, released after 2000) that outright reject the source files that contain non-ASCII characters.

As for the UTF-8 encoded characters in the string literals, as far as I can see, they are never put through any locale-aware functions, and the validation inputs and outputs are in the same file (i.e. must use the same encoding), this should not be a problem in itself.

Comment (keith-packard) [reply tests/lib/json/src/main.c:496]: It looks like C is slowly moving to accepting utf-8 in source code. As for source code, gcc has the `-finput-charset` and `-fexec-charset` command line options, which should probably be set to `UTF-8` to avoid problems building in locales using a different charset, in which case it's hard to know exactly what the compiler would do with utf-8 sequences in strings. I recall having adventures when building Java applications on Windows as the default charset there was UTF-16. Not sure what C compilers do in the Windows world.

Comment (keith-packard) [reply tests/lib/json/src/main.c:496]: If you want to avoid all issues, you would need to use octal escaped sequences for utf-8 in strings. For tests, that's probably a reasonable plan.

**Comment by dariis** [comment]
@mrfuchs Thank you, it worked for me :+1:

**Comment by mrfuchs** [comment]
> Saw this languishing and figured I should give it an approval, even though it's not really my area

Thank you! Unfortunately, I had to update this PR. Would you review it once more, please?

> (we don't really have a maintainer for JSON right now, I guess?).

Yes, it's difficult to get JSON PRs approved - my last PR #47989 also got closed due to a lack of reviewers.
@Sir-Branch asked for being the official JSON maintainer, but has become inactive lately. Sometimes @martinjaeger helps reviewing changes to the JSON library.

> Language wonks (@stephanosio @keith-packard ?) might care about the unicode string literals, though they seem harmless to me.

I didn't really pay attention to that. I just reused the test data that was already there.

**Comment by mrfuchs** [comment]
I noticed that my original patch would still not fix parsing arrays of objects. That's why I moved these lines inside the loop...

https://github.com/zephyrproject-rtos/zephyr/blob/55dc3986060ab3ef29aeeee3ba168bd65bdb23ba/lib/os/json.c#L578-L583

... and added a test for it (cf96b83). However, after adding the new unit test, CI failed again (cf. #36696 and [#24372#issuecomment-617392567](https://github.com/zephyrproject-rtos/zephyr/issues/24372#issuecomment-617392567)). So, I fixed this issue in 55dc398 to make CI work again.

**Comment by mrfuchs** [comment]
Reopening due to #58493.

**Review by keith-packard — CHANGES_REQUESTED** [review]
Please switch the non-ascii text in the tests to use octal escape sequences to avoid potential compiler issues on platforms not defaulting to utf-8 text encodings.

**Comment by mrfuchs** [comment]
> I would like to inquire about the current status of this fix as I am experiencing the same issue [...]

Will update this PR soon to follow @keith-packard's suggestion re. non-ascii text in the unit tests.

File: tests/lib/json/src/main.c (hunk 1 above)
Comment (mrfuchs) [reply tests/lib/json/src/main.c]: Updated the unit tests accordingly.

**Comment by mrfuchs** [comment]
@andyross, @keith-packard, I updated the unit tests. Could you review? Thanks!

**Review by keith-packard — COMMENTED** [review]
The commit message on the first patch (fixing the bugs) provides no information about what was broken and how the change addresses that. Makes reviewing the patch pretty hard.

**Comment by keith-packard** [comment]
> @andyross, @keith-packard, I updated the unit tests. Could you review? Thanks!

Unit test changes to use octal escapes look good!

**Review by keith-packard — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
