### PR TITLE
Settings: Fixes for compiler warnings

### LINKED ISSUE #17031: Compiler warnings in settings module in Zephyr 1.14
@nvlsianpu 

We are getting a number of Compiler Warnings when building Zephyr 1.14 (See below).
The variable rc is not initialized in these functions and could potentially get returned without being set to a value. In actual fact it may not be possible for this to happen due to the values passed into these functions being correct, but the Compiler cannot determine this, and it would be safer to actively prevent this possibility in the functions themselves.

Can you please advise on the best way to correct these warnings?
It seems that simply initializing the rc variables to an invalid value when they are declared would achieve this - do you agree?

Regards,
Declan Traill
Setec Pty Ltd

[50/254] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/settings/src/settings_store.c.obj
C:/Users/declan.traill/RVMN101/zephyr/subsys/settings/src/settings_store.c: In function 'settings_cmp':
C:/Users/declan.traill/RVMN101/zephyr/subsys/settings/src/settings_store.c:113:9: warning: 'rc' may be used uninitialized in this function [-Wmaybe-uninitialized]
  return rc;
         ^~
[52/254] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/settings/src/settings_line.c.obj
C:/Users/declan.traill/RVMN101/zephyr/subsys/settings/src/settings_line.c: In function 'settings_line_raw_read_until':
C:/Users/declan.traill/RVMN101/zephyr/subsys/settings/src/settings_line.c:272:19: warning: 'rc' may be used uninitialized in this function [-Wmaybe-uninitialized]
   return (rc) ? 0 : 1;
          ~~~~~~~~~^~~
C:/Users/declan.traill/RVMN101/zephyr/subsys/settings/src/settings_line.c: In function 'settings_entry_copy':
C:/Users/declan.traill/RVMN101/zephyr/subsys/settings/src/settings_line.c:444:9: warning: 'rc' may be used uninitialized in this function [-Wmaybe-uninitialized]
  return rc;
         ^~
[55/254] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/settings/src/settings_fcb.c.obj
C:/Users/declan.traill/RVMN101/zephyr/subsys/settings/src/settings_fcb.c: In function 'settings_fcb_save':
C:/Users/declan.traill/RVMN101/zephyr/subsys/settings/src/settings_fcb.c:270:5: warning: 'rc' may be used uninitialized in this function [-Wmaybe-uninitialized]
  if (rc) {
     ^

### PR DESCRIPTION
**Pull request by DeclanTraill**
@nvlsianpu
Fixes #17031:
Compiler warnings in settings module in Zephyr 1.14

### CODE REVIEW

**Review by Qbicz — APPROVED** [review]
LGTM

**Review by ioannisg — APPROVED** [review]
Looks ok to me.

File: subsys/settings/src/settings_fcb.c [hunk 1]
```diff
@@ -249,7 +249,7 @@ static int settings_fcb_save(struct settings_store *cs, const char *name,
 	struct settings_fcb *cf = (struct settings_fcb *)cs;
 	struct fcb_entry_ctx loc;
 	int len;
-	int rc;
+	int rc = -EINVAL;
```
Comment (ioannisg) [inline subsys/settings/src/settings_fcb.c]: I wonder: line 270 indicates that whatever the error reason has been in fcb_append, we return EINVAL.
Is this the right thing?

**Comment by ioannisg** [comment]
@nvlsianpu please, review

File: subsys/settings/src/settings_fcb.c (hunk 1 above)
Comment (nvlsianpu) [reply subsys/settings/src/settings_fcb.c]: In line 270 error-code can be different in order to reflect storage internal error or that storage became full.
-EINVAL is still OK IMO as it signal an error.

**Review by nvlsianpu — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by ioannisg** [comment]
@nashif @MaureenHelm , I've moved this to Ready - it's now reviewed and also has a bug report for 1.14
