### PR TITLE
Bluetooth: Audio: Fix issue with supporting bidir CIS in ASCS

### LINKED ISSUE #50780: LE Audio: Bidirectional handling of 2 audio streams as the unicast server when streams are configured separately not working as intended
**Describe the bug**
If a unicast server have 2 ASEs; 1 sink and 1 source, and the client sets up the sink endpoint first into the streaming state with, and then sets up the source endpoint with the same CIS, then the unicast server does not handle that well. 

This is because the ISO QoS are stored in the `bt_audio_stream` struct, and the stream isn't bound to the endpoint until after the endpoint has been configured by the client. 

Basically when the CIS is connected for the sink endpoint, it does not have any TX capabilities (because those are in the stream that hasn't been configured yet), and thus we see
```c
<dbg> bt_iso: hci_le_cis_established: iso_chan 0x20033bd0 tx (nil) rx 0x20033bec
```

It is not possibly to post-connection to supply the TX `bt_iso_chan_io_qos`, and thus the TX will never work as the code is today. 

Arguably it is a bit odd request from the client, as it has not yet set up the QoS for the source endpoint, so it does not know if the server will actually accept the CIS TX parameters at this point. 

**To Reproduce**
See above and the log

**Expected behavior**
The unicast server should be able to use the CIS for both directions in this case, and will need to find some way of setting some parameters for the CIS object so that it can send on the source stream. 

**Impact**
Low; it is an unlikely request from a client, and would simply stop the server from sending data. 

**Logs and console output**
```

Advertising started
[00:00:11.560,363] <inf> bt_id: RPA: 51:1D:E6:54:E4:79
Connected: C0:07:E8:63:12:31 (public)
LE data len updated: TX (len: 251 time: 2120) RX (len: 27 time: 328)
Remote LMP version 5.2 (0x0b) subversion 0x5244 manufacturer 0x07e8
LE Features: 0x00000021f701472f
[00:00:50.590,911] <dbg> bt_has: connected: conn 0x20029890 err 0
[00:00:50.592,590] <wrn> bt_hci_core: opcode 0x2022 status 0x0c
[00:00:50.592,620] <err> bt_hci_core: Failed to set data len (-5)
LE PHY updated: TX PHY LE 2M, RX PHY LE 2M
LE conn param updated: int 0x0018 lat 0 to 42
Security changed: C0:07:E8:63:12:31 (public) level 2
Paired with C0:07:E8:63:12:31 (public)
[00:00:56.885,833] <dbg> bt_has: security_changed: conn 0x20029890 level 2 err 0
uart:~$
uart:~$
[00:01:07.096,618] <dbg> bt_pacs: snk_cfg_changed: attr 0x7cf80 value 0x0001
[00:01:07.186,614] <dbg> bt_pacs: snk_loc_cfg_changed: attr 0x7cfbc value 0x0001
[00:01:07.246,612] <dbg> bt_pacs: src_cfg_changed: attr 0x7cff8 value 0x0001
[00:01:07.306,640] <dbg> bt_pacs: src_loc_cfg_changed: attr 0x7d034 value 0x0001
[00:01:07.366,638] <dbg> bt_pacs: available_context_cfg_changed: attr 0x7d070 value 0x0001
[00:01:07.426,635] <dbg> bt_pacs: supported_context_cfg_changed: attr 0x7d0ac value 0x0001
[00:01:12.436,737] <dbg> bt_ascs: ascs_cp_cfg_changed: attr 0x7cf30 value 0x0001
[00:01:12.496,734] <dbg> bt_ascs: ascs_ase_cfg_changed: attr 0x7ceb8 value 0x0001
[00:01:12.556,732] <dbg> bt_ascs: ascs_ase_cfg_changed: attr 0x7cef4 value 0x0001
[00:01:12.616,729] <dbg> bt_ascs: ascs_ase_cfg_changed: attr 0x7ce40 value 0x0001
[00:01:12.676,727] <dbg> bt_ascs: ascs_ase_cfg_changed: attr 0x7ce7c value 0x0001
[00:01:12.736,724] <dbg> bt_ascs: ascs_ase_read: conn 0x20029890 attr 0x7cea4 buf 0x200589a4 len 63 offset 0
[00:01:12.737,365] <dbg> bt_ascs: ascs_ep_init: ep 0x20032890 id 0x03
[00:01:12.737,579] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032890 id 0x03 state idle
[00:01:12.796,722] <dbg> bt_ascs: ascs_ase_read: conn 0x20029890 attr 0x7cee0 buf 0x200589a4 len 63 offset 0
[00:01:12.796,875] <dbg> bt_ascs: ascs_ep_init: ep 0x20032cf8 id 0x04
[00:01:12.797,058] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032cf8 id 0x04 state idle
[00:01:12.856,719] <dbg> bt_ascs: ascs_ase_read: conn 0x20029890 attr 0x7ce2c buf 0x200589a4 len 63 offset 0
[00:01:12.856,842] <dbg> bt_ascs: ascs_ep_init: ep 0x20031fc0 id 0x01
[00:01:12.857,086] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20031fc0 id 0x01 state idle
[00:01:12.916,748] <dbg> bt_ascs: ascs_ase_read: conn 0x20029890 attr 0x7ce68 buf 0x200589a4 len 63 offset 0
[00:01:12.916,870] <dbg> bt_ascs: ascs_ep_init: ep 0x20032428 id 0x02
[00:01:12.917,083] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032428 id 0x02 state idle
ASE Codec Config: conn 0x20029890 ep 0x20032428 dir 1, cap 0x2000140c
[00:01:19.157,257] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 30 op Config Codec (0x01)
[00:01:19.157,287] <dbg> bt_ascs: ascs_config: num_ases 1
[00:01:19.157,318] <dbg> bt_ascs: ascs_config: ase 0x02 cc_len 19
[00:01:19.157,348] <dbg> bt_ascs: ase_config: ase 0x20032424 latency 0x02 phy 0x02 codec 0x06 cid 0x0000 vid 0x0000 codec config len 0x13
[00:01:19.157,470] <dbg> bt_ascs: ascs_ep_set_codec: ep 0x20032428 codec id 0x06 cid 0x0000 vid 0x0000 len 19
[00:01:19.157,501] <dbg> bt_ascs: ascs_codec_config_store: #0 type 0x01 len 1
[00:01:19.157,531] <dbg> bt_ascs: ascs_codec_config_store: data
				08                                               |.
[00:01:19.157,562] <dbg> bt_ascs: ascs_codec_config_store: #1 type 0x02 len 1
[00:01:19.157,562] <dbg> bt_ascs: ascs_codec_config_store: data
				01                                               |.
[00:01:19.157,592] <dbg> bt_ascs: ascs_codec_config_store: #2 type 0x03 len 4
[00:01:19.157,623] <dbg> bt_ascs: ascs_codec_config_store: data
				01 00 00 00                                      |....
[00:01:19.157,684] <dbg> bt_ascs: ascs_codec_config_store: #3 type 0x04 len 2
[00:01:19.157,714] <dbg> bt_ascs: ascs_codec_config_store: data
				64 00                                            |d.
[00:01:19.157,714] <dbg> bt_ascs: ascs_codec_config_store: #4 type 0x05 len 1
[00:01:19.157,745] <dbg> bt_ascs: ascs_codec_config_store: data
				01                                               |.
codec 0x06 cid 0x0000 vid 0x0000 count 5
data #0: type 0x01 len 1
data #1: type 0x02 len 1
data #2: type 0x03 len 4
00000000: 01 00 00                                         |...              |
data #3: type 0x04 len 2
00000000: 64                                               |d                |
data #4: type 0x05 len 1
ASE Codec Config stream 0x2002e270
Default stream: 1
[00:01:19.585,601] <dbg> bt_ascs: ase_stream_add: ase 0x20032424 stream 0x2002e270
[00:01:19.585,662] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x02 op Config Codec (0x01) code Success (0x00) reason None (0x00)
[00:01:19.585,693] <dbg> bt_audio_stream: bt_audio_stream_attach: conn 0x20029890 stream 0x2002e270 ep 0x20032428 codec 0x20032434
[00:01:19.585,723] <dbg> bt_ascs: ascs_ep_set_state: ep 0x20032428 id 0x02 idle -> codec-configured
[00:01:19.585,723] <dbg> bt_ascs: ase_status_changed: ase 0x20032424 conn 0x20029890
[00:01:19.586,059] <dbg> bt_ascs: ase_process: ase 0x20032424, ep 0x20032428, ep.stream 0x2002e270
[00:01:19.586,090] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032428 id 0x02 state codec-configured
[00:01:19.586,120] <dbg> bt_ascs: ascs_ep_get_status_config: dir 0x01 unframed_supported 0x01 phy 0x02 rtn 0 latency 60 pd_min 20000 pd_max 40000 codec 0x06
[00:01:19.586,151] <dbg> bt_ascs: ascs_codec_data_add: #0: data type 0x01 len 1
[00:01:19.586,181] <dbg> bt_ascs: ascs_codec_data_add: data
				08                                               |.
[00:01:19.586,242] <dbg> bt_ascs: ascs_codec_data_add: #1: data type 0x02 len 1
[00:01:19.586,273] <dbg> bt_ascs: ascs_codec_data_add: data
				01                                               |.
[00:01:19.586,303] <dbg> bt_ascs: ascs_codec_data_add: #2: data type 0x03 len 4
[00:01:19.586,334] <dbg> bt_ascs: ascs_codec_data_add: data
				01 00 00 00                                      |....
[00:01:19.586,364] <dbg> bt_ascs: ascs_codec_data_add: #3: data type 0x04 len 2
[00:01:19.586,395] <dbg> bt_ascs: ascs_codec_data_add: data
				64 00                                            |d.
[00:01:19.586,425] <dbg> bt_ascs: ascs_codec_data_add: #4: data type 0x05 len 1
[00:01:19.586,456] <dbg> bt_ascs: ascs_codec_data_add: data
				01                                               |.
QoS: stream 0x2002e270 0x20032804
QoS: interval 10000 framing 0x00 phy 0x02 sdu 100 rtn 5 latency 20 pd 40000
[00:01:43.967,346] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 18 op Config QoS (0x02)
[00:01:43.967,376] <dbg> bt_ascs: ascs_qos: num_ases 1
[00:01:43.967,407] <dbg> bt_ascs: ascs_qos: ase 0x02
[00:01:43.967,437] <dbg> bt_ascs: ase_qos: ase 0x20032424 cig 0x01 cis 0x01 interval 10000 framing 0x00 phy 0x02 sdu 100 rtn 5 latency 20 pd 40000
[00:01:43.967,468] <dbg> bt_ascs: ase_stream_qos: stream 0x2002e270 ep 0x20032428 qos 0x20032804
[00:01:43.981,170] <dbg> bt_ascs: audio_iso_get_or_new: ascs 0x20031fb0 cig_id 0x01 cis_id 0x01
[00:01:43.981,201] <dbg> bt_ascs: ascs_ep_stream_bind_audio_iso: stream 0x2002e270, dir 1 audio_iso 0x20033bd0
[00:01:43.981,231] <dbg> bt_ascs: ascs_ep_set_state: ep 0x20032428 id 0x02 codec-configured -> qos-configured
[00:01:43.981,231] <dbg> bt_ascs: ase_status_changed: ase 0x20032424 conn 0x20029890
[00:01:43.981,292] <dbg> bt_audio_stream: bt_audio_stream_iso_listen: stream 0x2002e270 conn 0x20029890
[00:01:43.981,323] <dbg> bt_iso: bt_iso_server_register: 0x200138f8
[00:01:43.981,384] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x02 op Config QoS (0x02) code Success (0x00) reason None (0x00)
[00:01:43.981,689] <dbg> bt_ascs: ase_process: ase 0x20032424, ep 0x20032428, ep.stream 0x2002e270
[00:01:43.981,719] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032428 id 0x02 state qos-configured
[00:01:43.981,750] <dbg> bt_ascs: ascs_ep_get_status_qos: dir 0x01 codec 0x06 interval 10000 framing 0x00 phy 0x02 rtn 5 latency 20 pd 40000
Enable: stream 0x2002e270 meta_count 2
[00:01:51.527,496] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 11 op Enable (0x03)
[00:01:51.527,526] <dbg> bt_ascs: ascs_enable: num_ases 1
[00:01:51.527,557] <dbg> bt_ascs: ascs_enable: ase 0x02 meta->len 7
[00:01:51.527,557] <dbg> bt_ascs: ase_enable: ase 0x20032424 buf->len 7
[00:01:51.527,587] <dbg> bt_ascs: ascs_ep_set_metadata: ep 0x20032428 len 7 codec 0x20032434
[00:01:51.527,618] <dbg> bt_ascs: ascs_parse_metadata: #1 type 0x02 len 2
[00:01:51.527,648] <dbg> bt_ascs: ascs_parse_metadata: #2 type 0x05 len 1
[00:01:51.527,679] <wrn> bt_ascs: CCID 1 is unknown
[00:01:51.527,709] <dbg> bt_ascs: ascs_codec_store_metadata: #0: data: 0400
[00:01:51.527,740] <dbg> bt_ascs: ascs_codec_store_metadata: #1: data: 01
[00:01:51.532,836] <dbg> bt_ascs: ascs_ep_set_state: ep 0x20032428 id 0x02 qos-configured -> enabling
[00:01:51.532,867] <dbg> bt_ascs: ase_status_changed: ase 0x20032424 conn 0x20029890
[00:01:51.532,928] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x02 op Enable (0x03) code Success (0x00) reason None (0x00)
[00:01:51.533,264] <dbg> bt_ascs: ase_process: ase 0x20032424, ep 0x20032428, ep.stream 0x2002e270
[00:01:51.533,294] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032428 id 0x02 state enabling
[00:01:51.533,325] <dbg> bt_ascs: ascs_codec_data_add: #0: meta type 0x02 len 2
[00:01:51.533,355] <dbg> bt_ascs: ascs_codec_data_add: meta
				04 00                                            |..
[00:01:51.533,386] <dbg> bt_ascs: ascs_codec_data_add: #1: meta type 0x05 len 1
[00:01:51.533,416] <dbg> bt_ascs: ascs_codec_data_add: meta
				01                                               |.
[00:01:51.533,416] <dbg> bt_ascs: ascs_ep_get_status_enable: dir 0x01 cig 0x01 cis 0x01
[00:01:51.617,706] <dbg> bt_iso: hci_le_cis_req: acl_handle 0 cis_handle 2 cig_id 1 cis 1
[00:01:51.617,767] <dbg> bt_iso: iso_accept: 0x2002a960
[00:01:51.617,797] <dbg> bt_audio_stream: bt_audio_stream_iso_accept: acl 0x20029890
[00:01:51.617,828] <dbg> bt_audio_stream: bt_audio_stream_iso_accept: iso_chan 0x20033bd0
[00:01:51.617,828] <dbg> bt_iso: bt_iso_chan_add: iso 0x2002a960 chan 0x20033bd0
[00:01:51.617,858] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x20033bd0 iso 0x2002a960 disconnected -> connecting
[00:01:51.800,323] <dbg> bt_iso: hci_le_cis_established: status 0 handle 2
[00:01:51.800,354] <dbg> bt_iso: hci_le_cis_established: iso_chan 0x20033bd0 tx (nil) rx 0x20033bec
[00:01:51.800,415] <dbg> bt_iso: bt_iso_connected: 0x2002a960
[00:01:51.800,750] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x20033bd0 iso 0x2002a960 connecting -> connected
[00:01:51.800,781] <dbg> bt_ascs: ascs_iso_connected: stream 0x2002e270 ep 0x20032428 dir 1
[00:01:51.800,811] <dbg> bt_ascs: ascs_ep_set_state: ep 0x20032428 id 0x02 enabling -> streaming
[00:01:51.800,842] <dbg> bt_ascs: ase_status_changed: ase 0x20032424 conn 0x20029890
[00:01:51.800,933] <dbg> bt_ascs: ase_process: ase 0x20032424, ep 0x20032428, ep.stream 0x2002e270
[00:01:51.800,964] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032428 id 0x02 state streaming
[00:01:51.800,994] <dbg> bt_ascs: ascs_codec_data_add: #0: meta type 0x02 len 2
[00:01:51.801,025] <dbg> bt_ascs: ascs_codec_data_add: meta
				04 00                                            |..
[00:01:51.801,086] <dbg> bt_ascs: ascs_codec_data_add: #1: meta type 0x05 len 1
[00:01:51.801,116] <dbg> bt_ascs: ascs_codec_data_add: meta
				01                                               |.
[00:01:51.801,147] <dbg> bt_ascs: ascs_ep_get_status_enable: dir 0x01 cig 0x01 cis 0x01
uart:~$
uart:~$
uart:~$
uart:~$
uart:~$ audio send
Unable to send: 22
[00:04:18.085,906] <dbg> bt_iso: bt_iso_chan_send: Channel not able to send
uart:~$
uart:~$
[00:04:27.260,864] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 3 op Receiver Start Ready (0x04)
[00:04:27.260,894] <dbg> bt_ascs: ascs_start: num_ases 1
[00:04:27.260,925] <dbg> bt_ascs: ascs_start: ase 0x02
[00:04:27.260,955] <dbg> bt_ascs: ase_start: ase 0x20032424
[00:04:27.260,986] <wrn> bt_ascs: Invalid operation in state: streaming
[00:04:27.261,016] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x02 op Receiver Start Ready (0x04) code Invalid ASE State (0x04) reason None (0x00)
uart:~$
ASE Codec Config: conn 0x20029890 ep 0x20032890 dir 2, cap 0x200013e4
[00:11:16.320,312] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 30 op Config Codec (0x01)
[00:11:16.320,343] <dbg> bt_ascs: ascs_config: num_ases 1
[00:11:16.320,373] <dbg> bt_ascs: ascs_config: ase 0x03 cc_len 19
[00:11:16.320,373] <dbg> bt_ascs: ase_config: ase 0x2003288c latency 0x02 phy 0x02 codec 0x06 cid 0x0000 vid 0x0000 codec config len 0x13
[00:11:16.320,526] <dbg> bt_ascs: ascs_ep_set_codec: ep 0x20032890 codec id 0x06 cid 0x0000 vid 0x0000 len 19
[00:11:16.320,526] <dbg> bt_ascs: ascs_codec_config_store: #0 type 0x01 len 1
[00:11:16.320,556] <dbg> bt_ascs: ascs_codec_config_store: data
				08                                               |.
[00:11:16.320,587] <dbg> bt_ascs: ascs_codec_config_store: #1 type 0x02 len 1
[00:11:16.320,617] <dbg> bt_ascs: ascs_codec_config_store: data
				01                                               |.
[00:11:16.320,648] <dbg> bt_ascs: ascs_codec_config_store: #2 type 0x03 len 4
[00:11:16.320,678] <dbg> bt_ascs: ascs_codec_config_store: data
				01 00 00 00                                      |....
[00:11:16.320,709] <dbg> bt_ascs: ascs_codec_config_store: #3 type 0x04 len 2
[00:11:16.320,739] <dbg> bt_ascs: ascs_codec_config_store: data
				64 00                                            |d.
[00:11:16.320,770] <dbg> bt_ascs: ascs_codec_config_store: #4 type 0x05 len 1
[00:11:16.320,800] <dbg> bt_ascs: ascs_codec_config_store: data
				01                                               |.
codec 0x06 cid 0x0000 vid 0x0000 count 5
data #0: type 0x01 len 1
data #1: type 0x02 len 1
data #2: type 0x03 len 4
00000000: 01 00 00                                         |...              |
data #3: type 0x04 len 2
00000000: 64                                               |d                |
data #4: type 0x05 len 1
ASE Codec Config stream 0x2002e294
Default stream: 2
[00:11:16.748,901] <dbg> bt_ascs: ase_stream_add: ase 0x2003288c stream 0x2002e294
[00:11:16.748,962] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x03 op Config Codec (0x01) code Success (0x00) reason None (0x00)
[00:11:16.748,962] <dbg> bt_audio_stream: bt_audio_stream_attach: conn 0x20029890 stream 0x2002e294 ep 0x20032890 codec 0x2003289c
[00:11:16.749,023] <dbg> bt_ascs: ascs_ep_set_state: ep 0x20032890 id 0x03 idle -> codec-configured
[00:11:16.749,023] <dbg> bt_ascs: ase_status_changed: ase 0x2003288c conn 0x20029890
[00:11:16.749,359] <dbg> bt_ascs: ase_process: ase 0x2003288c, ep 0x20032890, ep.stream 0x2002e294
[00:11:16.749,389] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032890 id 0x03 state codec-configured
[00:11:16.749,420] <dbg> bt_ascs: ascs_ep_get_status_config: dir 0x02 unframed_supported 0x01 phy 0x02 rtn 0 latency 60 pd_min 20000 pd_max 40000 codec 0x06
[00:11:16.749,450] <dbg> bt_ascs: ascs_codec_data_add: #0: data type 0x01 len 1
[00:11:16.749,481] <dbg> bt_ascs: ascs_codec_data_add: data
				08                                               |.
[00:11:16.749,542] <dbg> bt_ascs: ascs_codec_data_add: #1: data type 0x02 len 1
[00:11:16.749,572] <dbg> bt_ascs: ascs_codec_data_add: data
				01                                               |.
[00:11:16.749,603] <dbg> bt_ascs: ascs_codec_data_add: #2: data type 0x03 len 4
[00:11:16.749,633] <dbg> bt_ascs: ascs_codec_data_add: data
				01 00 00 00                                      |....
[00:11:16.749,664] <dbg> bt_ascs: ascs_codec_data_add: #3: data type 0x04 len 2
[00:11:16.749,694] <dbg> bt_ascs: ascs_codec_data_add: data
				64 00                                            |d.
[00:11:16.749,725] <dbg> bt_ascs: ascs_codec_data_add: #4: data type 0x05 len 1
[00:11:16.749,755] <dbg> bt_ascs: ascs_codec_data_add: data
				01                                               |.
uart:~$
uart:~$
[00:11:31.260,711] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 18 op Config QoS (0x02)
[00:11:31.260,742] <dbg> bt_ascs: ascs_qos: num_ases 1
[00:11:31.260,772] <dbg> bt_ascs: ascs_qos: ase 0x03
[00:11:31.260,803] <dbg> bt_ascs: ase_qos: ase 0x2003288c cig 0xff cis 0xff interval 0 framing 0x00 phy 0x00 sdu 0 rtn 0 latency 0 pd 0
[00:11:31.260,803] <dbg> bt_ascs: ase_stream_qos: stream 0x2002e294 ep 0x20032890 qos 0x20032c6c
[00:11:31.260,833] <dbg> bt_audio_stream: bt_audio_valid_qos: Interval not within allowed range: 0 (255-1048575)
[00:11:31.260,864] <err> bt_ascs: QoS failed: err -22
[00:11:31.260,894] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x03 op Config QoS (0x02) code Invalid Configuration Value (0x09) reason None (0x00)
uart:~$
uart:~$
QoS: stream 0x2002e294 0x20032c6c
QoS: interval 10000 framing 0x00 phy 0x02 sdu 100 rtn 5 latency 20 pd 40000
[00:12:21.181,884] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 18 op Config QoS (0x02)
[00:12:21.181,915] <dbg> bt_ascs: ascs_qos: num_ases 1
[00:12:21.181,945] <dbg> bt_ascs: ascs_qos: ase 0x03
[00:12:21.181,945] <dbg> bt_ascs: ase_qos: ase 0x2003288c cig 0x01 cis 0x01 interval 10000 framing 0x00 phy 0x02 sdu 100 rtn 5 latency 20 pd 40000
[00:12:21.181,976] <dbg> bt_ascs: ase_stream_qos: stream 0x2002e294 ep 0x20032890 qos 0x20032c6c
[00:12:21.195,526] <dbg> bt_ascs: audio_iso_get_or_new: ascs 0x20031fb0 cig_id 0x01 cis_id 0x01
[00:12:21.195,556] <dbg> bt_ascs: ascs_ep_stream_bind_audio_iso: stream 0x2002e294, dir 2 audio_iso 0x20033bd0
[00:12:21.195,587] <dbg> bt_ascs: ascs_ep_set_state: ep 0x20032890 id 0x03 codec-configured -> qos-configured
[00:12:21.195,587] <dbg> bt_ascs: ase_status_changed: ase 0x2003288c conn 0x20029890
[00:12:21.195,648] <dbg> bt_audio_stream: bt_audio_stream_iso_listen: stream 0x2002e294 conn 0x20029890
[00:12:21.195,678] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x03 op Config QoS (0x02) code Success (0x00) reason None (0x00)
[00:12:21.196,014] <dbg> bt_ascs: ase_process: ase 0x2003288c, ep 0x20032890, ep.stream 0x2002e294
[00:12:21.196,044] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032890 id 0x03 state qos-configured
[00:12:21.196,075] <dbg> bt_ascs: ascs_ep_get_status_qos: dir 0x02 codec 0x06 interval 10000 framing 0x00 phy 0x02 rtn 5 latency 20 pd 40000
uart:~$
uart:~$
uart:~$
uart:~$
uart:~$
Enable: stream 0x2002e294 meta_count 2
[00:12:37.832,244] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 11 op Enable (0x03)
[00:12:37.832,275] <dbg> bt_ascs: ascs_enable: num_ases 1
[00:12:37.832,305] <dbg> bt_ascs: ascs_enable: ase 0x03 meta->len 7
[00:12:37.832,305] <dbg> bt_ascs: ase_enable: ase 0x2003288c buf->len 7
[00:12:37.832,336] <dbg> bt_ascs: ascs_ep_set_metadata: ep 0x20032890 len 7 codec 0x2003289c
[00:12:37.832,366] <dbg> bt_ascs: ascs_parse_metadata: #1 type 0x02 len 2
[00:12:37.832,397] <dbg> bt_ascs: ascs_parse_metadata: #2 type 0x05 len 1
[00:12:37.832,427] <wrn> bt_ascs: CCID 1 is unknown
[00:12:37.832,458] <dbg> bt_ascs: ascs_codec_store_metadata: #0: data: 0400
[00:12:37.832,489] <dbg> bt_ascs: ascs_codec_store_metadata: #1: data: 01
[00:12:37.837,585] <dbg> bt_ascs: ascs_ep_set_state: ep 0x20032890 id 0x03 qos-configured -> enabling
[00:12:37.837,615] <dbg> bt_ascs: ase_status_changed: ase 0x2003288c conn 0x20029890
[00:12:37.837,677] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x03 op Enable (0x03) code Success (0x00) reason None (0x00)
[00:12:37.838,012] <dbg> bt_ascs: ase_process: ase 0x2003288c, ep 0x20032890, ep.stream 0x2002e294
[00:12:37.838,043] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032890 id 0x03 state enabling
[00:12:37.838,073] <dbg> bt_ascs: ascs_codec_data_add: #0: meta type 0x02 len 2
[00:12:37.838,104] <dbg> bt_ascs: ascs_codec_data_add: meta
				04 00                                            |..
[00:12:37.838,134] <dbg> bt_ascs: ascs_codec_data_add: #1: meta type 0x05 len 1
[00:12:37.838,165] <dbg> bt_ascs: ascs_codec_data_add: meta
				01                                               |.
[00:12:37.838,195] <dbg> bt_ascs: ascs_ep_get_status_enable: dir 0x02 cig 0x01 cis 0x01
uart:~$
uart:~$
uart:~$
Start: stream 0x2002e294
[00:12:46.742,401] <dbg> bt_ascs: ascs_cp_write: conn 0x20029890 attr 0x7cf1c buf 0x200581f8 len 3 op Receiver Start Ready (0x04)
[00:12:46.742,431] <dbg> bt_ascs: ascs_start: num_ases 1
[00:12:46.742,462] <dbg> bt_ascs: ascs_start: ase 0x03
[00:12:46.742,492] <dbg> bt_ascs: ase_start: ase 0x2003288c
[00:12:46.745,971] <dbg> bt_ascs: ascs_ep_set_state: ep 0x20032890 id 0x03 enabling -> streaming
[00:12:46.746,002] <dbg> bt_ascs: ase_status_changed: ase 0x2003288c conn 0x20029890
[00:12:46.746,063] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x03 op Receiver Start Ready (0x04) code Success (0x00) reason None (0x00)
[00:12:46.746,368] <dbg> bt_ascs: ase_process: ase 0x2003288c, ep 0x20032890, ep.stream 0x2002e294
[00:12:46.746,398] <dbg> bt_ascs: ascs_ep_get_status: ep 0x20032890 id 0x03 state streaming
[00:12:46.746,459] <dbg> bt_ascs: ascs_codec_data_add: #0: meta type 0x02 len 2
[00:12:46.746,459] <dbg> bt_ascs: ascs_codec_data_add: meta
				04 00                                            |..
[00:12:46.746,520] <dbg> bt_ascs: ascs_codec_data_add: #1: meta type 0x05 len 1
[00:12:46.746,551] <dbg> bt_ascs: ascs_codec_data_add: meta
				01                                               |.
[00:12:46.746,582] <dbg> bt_ascs: ascs_ep_get_status_enable: dir 0x02 cig 0x01 cis 0x01
uart:~$
uart:~$
uart:~$
uart:~$ audio send
Unable to send: 22
[00:12:51.374,206] <dbg> bt_iso: bt_iso_chan_send: Channel not able to send
uart:~$ audio
init                 select_broadcast     create_broadcast
start_broadcast      stop_broadcast       delete_broadcast
broadcast_scan       accept_broadcast     sync_broadcast
stop_broadcast_sink  term_broadcast_sink  discover
preset               config               qos
enable               metadata             start
disable              stop                 release
list                 connect              select_unicast
send                 set_location         add_context
uart:~$ audio sel
select_broadcast  select_unicast
uart:~$ audio select_unicast
select_unicast: wrong parameter count
select_unicast - <stream>
uart:~$ audio select_unicast 2
Invalid index
uart:~$ audio select_unicast 1
Default stream: 2
uart:~$ audio send
Unable to send: 22
[00:13:10.733,215] <dbg> bt_iso: bt_iso_chan_send: Channel not able to send
uart:~$ audio select_unicast 0
Default stream: 1
uart:~$ audio select_unicast 0
Default stream: 1
uart:~$ audio select_unicast 1
Default stream: 2
uart:~$ audio send
Unable to send: 22
[00:14:05.878,509] <dbg> bt_iso: bt_iso_chan_send: Channel not able to send
uart:~$
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: a5ce3da6ab425d104d73d34f47352ae721c5d216

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
If 2 ASEs shared the same CIS and the first ASE had the CIS connected before the second ASE was QoS configured, then the CIS was missing either the TX or RX pointer, causing it to be considered unidirectional by the ISO layer.

This commit fixes this issue by configuring the (static) pointers at an earlier time, so that the RX and TX QoS pointers are always valid.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

fixes https://github.com/zephyrproject-rtos/zephyr/issues/50780

### CODE REVIEW

**Review by kruithofa — DISMISSED** [review]

**Review by MariuszSkamra — APPROVED** [review]

File: subsys/bluetooth/audio/ascs.c [hunk 1]
```diff
@@ -1147,11 +1157,13 @@ static struct bt_ascs_ase *ase_new(struct bt_ascs *ascs, uint8_t id)
 		}
 		i = id;
 		ase = &ascs->ases[i - 1];
+		audio_iso = &ascs->isos[i - 1];
 		goto done;
 	}
 
 	for (i = 0; i < ASE_COUNT; i++) {
 		ase = &ascs->ases[i];
+	audio_iso = &ascs->isos[i];
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/ascs.c:1166]: indent

File: subsys/bluetooth/audio/ascs.c [hunk 2]
```diff
@@ -1163,6 +1175,7 @@ static struct bt_ascs_ase *ase_new(struct bt_ascs *ascs, uint8_t id)
 
 done:
 	ase_init(ase, i);
+	audio_iso_init(audio_iso);
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/ascs.c:1178]: I think that `audio_iso_get_or_new` is better place to init the structure members

**Review by MariuszSkamra — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/ascs.c [hunk 3]
```diff
@@ -1136,8 +1124,30 @@ static void ase_init(struct bt_ascs_ase *ase, uint8_t id)
...
+	 * ever want to use it for TX, and ditto for RX. They cannot be
+	 * initialized after the CIS has been connected
+	 */
+	audio_iso->iso_chan.ops = &ascs_iso_ops;
+	audio_iso->iso_chan.qos = &audio_iso->iso_qos;
+	audio_iso->iso_chan.qos->tx = &audio_iso->source_io_qos;
+	audio_iso->iso_chan.qos->tx->path = &audio_iso->source_path;
+	audio_iso->iso_chan.qos->tx->path->cc = audio_iso->source_path_cc;
+
+	audio_iso->iso_chan.ops = &ascs_iso_ops;
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/ascs.c:1141]: initialized already in line 1135

File: subsys/bluetooth/audio/ascs.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/audio/ascs.c:1178]: That is better, thanks. 

Alternatively, since are just assigning constant value, we could do it within a `SYS_INIT`.

File: subsys/bluetooth/audio/ascs.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/audio/ascs.c]: Thanks fixed. Moved the lines so it's clearer what is going on.

**Review by MariuszSkamra — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]

**Comment by Thalley** [comment]
@carlescufi  This is blocking https://github.com/zephyrproject-rtos/zephyr/pull/51513, can we please merge?
