### PR TITLE
Disallow STACK SENTINEL in single-thread builds

### LINKED ISSUE #35764: tests: kernel: threads: no multithreading: fails with CONFIG_STACK_SENTINEL=y
**Describe the bug**
no_multithreading test is failing when CONFIG_STACK_SENTINEL is enabled

**To Reproduce**
1. build no_multithreading test 
2. cmake -DBOARD=nrf52840dk_nrf52840
3. make

**Expected behavior**
The test should pass.

**Impact**
Low. This is a custom configuration

**Logs and console output**
```

E: ***** Debug monitor exception *****
Null-pointer exception?
E: r0/a1:  0x00000000  r1/a2:  0x00002421  r2/a3:  0x00000020
E: r3/a4:  0x00000000 r12/ip:  0x00000020 r14/lr:  0x00002427
E:  xpsr:  0x61000010
E: Faulting instruction address (r15/pc): 0x000036ba
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Fault during interrupt handling

E: Current thread: (nil) (unknown)
E: Halting system

```

### PR DESCRIPTION
**Pull request by ioannisg**
Fixes #35764

### CODE REVIEW

File: kernel/thread.c [hunk 1]
```diff
@@ -328,6 +328,7 @@ static inline int z_vrfy_k_thread_name_copy(k_tid_t thread,
 #endif /* CONFIG_USERSPACE */
 
 
+#ifdef CONFIG_MULTITHREADING
 #ifdef CONFIG_STACK_SENTINEL
```
Comment (galak) [inline kernel/thread.c:332]: Can this just be `if defined(CONFIG_MULTITHREADING) && defined(CONFIG_STACK_SENTINEL)`

**Review by galak — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
