### PR TITLE
Bluetooth: shell: Fix missing check for buffer allocation

### LINKED ISSUE #74725: [Coverity CID: 366280] Dereference null return value in subsys/bluetooth/shell/bt.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/dcf42917c550714d2457947538b9e29d083e872e/subsys/bluetooth/shell/bt.c

Category: Null pointer dereferences
Function: `cmd_hci_cmd`
Component: Bluetooth
CID: [366280](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=366280)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/dcf42917c550714d2457947538b9e29d083e872e/subsys/bluetooth/shell/bt.c#L1247

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=366280

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NULL_RETURNS). ([CWE-476](http://cwe.mitre.org/data/definitions/476.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by jhedberg**
In practice this allocation is very unlikely to fail, however being consistent with checking for a failure keeps Coverity happy.

Fixes #74725

### CODE REVIEW

**Review by LingaoM — DISMISSED** [review]

**Review by ubieda — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

File: subsys/bluetooth/shell/bt.c [hunk 1]
```diff
@@ -1244,6 +1244,10 @@ static int cmd_hci_cmd(const struct shell *sh, size_t argc, char *argv[])
 		}
 
 		buf = bt_hci_cmd_create(BT_OP(ogf, ocf), len);
+		if (buf == NULL) {
+			shell_error(sh, "Unable to allocate HCI buffer");
+			return -ENOMEM;
+		}
 		net_buf_add_mem(buf, hex_data, len);
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:1251]:
```suggestion
		}
		
		net_buf_add_mem(buf, hex_data, len);
```

Because you usually request that as well ;)

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/shell/bt.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/shell/bt.c:1251]: > Because you usually request that as well ;)

That was actually a conscious choice after going back-and-fort a bit. I can imagine arguments both ways, e.g. whitespace should be used to group "things belonging together" and these 6 lines "belong together". That said, the encoding into the buffer could very well be seen as a separate logical chunk, so I'll add the empty line :)

**Review by Thalley — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by ubieda — APPROVED** [review]
