### PR TITLE
Bluetooth: Controller: Fix Periodic Sync Failed to be Established

### LINKED ISSUE #40209: Bluetooth: First AUX_SYNC_IND never received, missing event send to host
**Describe the bug**
After call `ll_sync_create` the AUX_SYNC_IND PDU should be received within 6 periodic advertising events. If that does not happen, controller should generate `HCI_LE_Periodic_Advertising_Sync_Established` with status set to `0x3E Connection Failed To Be Established / Synchronization Timeout`.

Also host does not have appropriate implementation to handle this situation.

**To Reproduce**
1. Build direction_finding_connectionless_tx sample as an advertiser.
2. Build direction_finding_connectionless_rx sample as a scanned.
3. Run both.
4. Disable advertiser just after periodic advertising sync create is called.

**Expected behavior**
There should be received an event `HCI_LE_Periodic_Advertising_Sync_Established` by host.

**Impact**
Moderate, it is related with periodic advertising only.

### PR DESCRIPTION
**Pull request by cvinayak**
Fix Periodic Advertising Synchronize implementation to
generate Synchronization Failed to be Established event
when 6 AUX_SYNC_IND PDUs are not received when establishing
synchronization.

Fixes #40209

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/hci/hci.c [hunk 1]
```diff
@@ -6036,18 +6036,18 @@ static void le_per_adv_sync_established(struct pdu_data *pdu_data,
...
+	if (se->status == BT_HCI_ERR_OP_CANCELLED_BY_HOST) {
 		return;
 	}
 
-	scan = node_rx->hdr.rx_ftr.param;
+	sep->handle = sys_cpu_to_le16(node_rx->hdr.handle);
 
-	sep->sid = scan->per_scan.sid;
 	/* Resolved address, if private, has been populated in ULL */
+	scan = node_rx->hdr.rx_ftr.param;
```
Comment (ppryga) [inline subsys/bluetooth/controller/hci/hci.c:6047]: The comment `/* Resolved address, if private, has been populated in ULL */` seems to not belong to the line.

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 2]
```diff
@@ -1370,10 +1370,37 @@ void ll_rx_mem_release(void **node_rx)
 		{
 			struct node_rx_sync *se =
 				(void *)((struct node_rx_pdu *)rx_free)->pdu;
+			uint8_t status = se->status;
+
+			/* Below status codes use node_rx_sync_estab, hence
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull.c:1375]: This comment is a bit unclear for me. Maybe: 
`/* Below status codes are only allowed codes for node_rx_sync_estab, hence release of node memory and optional sync cleanup. */`

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 3]
```diff
@@ -1370,10 +1370,37 @@ void ll_rx_mem_release(void **node_rx)
...
+			 * release the node_rx memory.
+			 */
+			if ((status == BT_HCI_ERR_SUCCESS) ||
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull.c:1378]: I suggest to add 
```
else {
        LL_ASSERT(1);
}
```
at the end of the `if` statement. 
If there is no assert, not allowed error codes will pass unnoticed.

File: subsys/bluetooth/controller/ll_sw/ull_sync.c [hunk 4]
```diff
@@ -548,19 +550,21 @@ void ull_sync_setup(struct ll_scan_set *scan, struct ll_scan_aux_set *aux,
 	lll->event_counter = si->evt_cntr;
 	lll->phy = aux->lll.phy;
 
+	interval = sys_le16_to_cpu(si->interval);
+	interval_us = interval * CONN_INT_UNIT_US;
+
+	sync->timeout_reload = RADIO_SYNC_EVENTS((sync->timeout * 10U * 1000U),
+						 interval_us);
+
+	sync->sync_expire = 6U;
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_sync.c:559]: Can you change `6U` to macro?

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 5]
```diff
@@ -1370,10 +1370,37 @@ void ll_rx_mem_release(void **node_rx)
...
+
+					break;
+				}
+
+				/* pick the sync context to be released */
+				sync = scan->per_scan.sync;
+
+				ull_sync_setup_cleanup(scan);
+
+				ull_sync_release(sync);
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull.c:1402]:
```suggestion
                               /* Pick the sync context in case is has to be released */
				sync = scan->per_scan.sync;
				ull_sync_setup_cleanup(scan);

				if (status != BT_HCI_ERR_SUCCESS) {
        				ull_sync_release(sync);
				}
```

File: subsys/bluetooth/controller/ll_sw/ull_sync.c [hunk 6]
```diff
@@ -654,6 +658,25 @@ void ull_sync_setup(struct ll_scan_set *scan, struct ll_scan_aux_set *aux,
 		  (ret == TICKER_STATUS_BUSY));
 }
 
+void ull_sync_setup_cleanup(struct ll_scan_set *scan)
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_sync.c:661]: The comment: `/* Reset the sync context allocated to scan contexts */` describes the function better than its name.
```suggestion
void ull_sync_reset_in_scan_ctx(struct ll_scan_set *scan)
```

**Review by ppryga-nordic — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_sync.c [hunk 7]
```diff
@@ -548,19 +550,21 @@ void ull_sync_setup(struct ll_scan_set *scan, struct ll_scan_aux_set *aux,
 	lll->event_counter = si->evt_cntr;
 	lll->phy = aux->lll.phy;
 
+	interval = sys_le16_to_cpu(si->interval);
+	interval_us = interval * CONN_INT_UNIT_US;
+
+	sync->timeout_reload = RADIO_SYNC_EVENTS((sync->timeout * 10U * 1000U),
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_sync.c:556]:
```suggestion
	/* Convert from 10ms unit to us */
	sync->timeout_reload = RADIO_SYNC_EVENTS((sync->timeout * 10U * USEC_PER_MSEC),
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull.c:1375]: Updated.

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull.c:1379]: Done.

File: subsys/bluetooth/controller/hci/hci.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/hci/hci.c:6046]: Updated.

File: subsys/bluetooth/controller/ll_sw/ull_sync.c (hunk 7 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_sync.c]: Updated.

File: subsys/bluetooth/controller/ll_sw/ull_sync.c (hunk 6 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_sync.c:663]: The naming is inline with `*_cleanup` used like in `ull_central_cleanup` to remove connection context associated with scan context during connection establishment.

File: subsys/bluetooth/controller/ll_sw/ull.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull.c:1379]: To me it doesn't look resolved: @ppryga do you agree?

Comment (ppryga) [reply subsys/bluetooth/controller/ll_sw/ull.c:1379]: It looks ok, I've forgotten that the `status` may have `BT_HCI_ERR_OP_CANCELLED_BY_HOST` value.

File: subsys/bluetooth/controller/ll_sw/ull_sync.c (hunk 6 above)
Comment (ppryga) [reply subsys/bluetooth/controller/ll_sw/ull_sync.c:663]: `void ull_central_cleanup(struct node_rx_hdr *rx_free)` does really cleanup of a `rx_free`. The `ull_sync_setup_cleanup` just assigns `NULL` to `sync` member. It does not release the `sync`. The automatic release of the sync is something that I would expect when see call to the function.

It could be misleading when someone reads the code. You have to remember the content of the function or put limited trust in what you may expect until you check the implementation.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_sync.c]: I have renamed it to `ull_sync_setup_complete`. `reset` is associated with HCI or HAL reset implementations.

**Review by Thalley — APPROVED** [review]
LGTM

**Review by ppryga-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
