### PR TITLE
mgmt: updatehub: Fix json arrays

### LINKED ISSUE #69297: Zephyr UpdateHub sample issues
**I've been working with the OTA updatehub sample built for mimxrt1060_evk.**

I've come across some issues with json parse in the mcuboot updatehub agent. When a package is uploaded for a rollout using updatehub-ce in a docker container. The device does a check to pull the update down i get the following error in a minicom terminal window...
`` minicom -D /dev/ttyACM0`` 

``` [00:00:02.503,000] <inf> eth_mcux: ETH_0 enabled 100M full-duplex mode.
[00:00:02.503,000] <inf> main: UpdateHub sample app started
[00:00:02.503,000] <inf> main: Confirming the boot image
[00:00:02.503,000] <inf> main: Network disconnected
[00:00:04.527,000] <inf> main: Network connected
[00:00:04.527,000] <inf> main: Starting UpdateHub polling mode
[00:00:04.527,000] <inf> updatehub: SHA-256 verification on download and from flash
[00:00:04.532,000] <inf> updatehub: Probe metadata received
[00:00:04.532,000] <err> updatehub: Could not parse json
[00:01:04.536,000] <inf> updatehub: Probe metadata received
[00:01:04.537,000] <err> updatehub: Could not parse json
[00:02:04.541,000] <inf> updatehub: Probe metadata received
[00:02:04.541,000] <err> updatehub: Could not parse json
[00:03:04.546,000] <inf> updatehub: Probe metadata received
[00:03:04.546,000] <err> updatehub: Could not parse json
 ```

However the update would not fail imedietly but after a minute (interval to check for an update again) it would try pull the meta data about the update once again and fail in the same way.
I decided to by-pass the cleanup that happens if the json parse fails and now all checks to do with meta data from the json parse fail and print their error messages... 
```
 <err> updatehub: Could not parse json 
 <err> updatehub: Could not parse json 
 <err> updatehub: SHA256 size is invalid 
 <err> eth_mcux: ENET_GetRxFrameSize return: 4001 
```
and with this change the update fails and doesn't try again after the minute.
 

**To Reproduce**
-Following the steps from https://docs.zephyrproject.org/latest/samples/subsys/mgmt/updatehub/README.html
The only difference being building for a mimxrt1060_evk board. 

- Run docker container for updatehub-ce 
 ``docker run -it -p 8080:8080 -p 5683:5683/udp --rm updatehub/updatehub-ce:latest ``
- In browser connect to ``localhost:8080`` or ``local ip``
- Create package using uhu from signed image as per the examples intructions
- Upload package ``zephyr-update.pkg`` on the updatehub dashboard
- Create rollout and the update never fails nor completes
- For update to fail with previously mentioned errors lines 878, 884, 893, 906, 922
 need to be commented out, can be found at ``~zephyproject/zephyr/subsys/mgmt/updatehub/updatehub.c``
  
I have also check using uhu if my metadata is valid:

image

**Expected behaviour**
- Update never completing, fail at a json parse which can be seen through a minicom -D /dev/ttyACM0
- If code commented out update failing and reporting back to updatehub that it failed

**Impact**
Due to this issue I haven't been able to continue on with working with this sample

**Environment**
 - OS: Linux
 - Toolchain: Zephyr SDK 
 - Zephyr version 3.5.0

### PR DESCRIPTION
**Pull request by nandojve**
After the changes introduced by #50816 the UpdateHub could not decode anymore the JSON object. This introduce missing parsing definitions to allow JSON parser undertood the correct UpdateHub probe object.

Fixes #69297

Before evaluate it is recommended take a look at [UpdateHub zephyr guide](https://docs.updatehub.io/zephyr-project/zephyr-project-guide) and make sure your device have a network connection. Remember that by default UpdateHub sample get IP automatically.

Steps to Evaluate:

Run updatehub-ce docker
```
sudo docker run -it -p 8080:8080 -p 5683:5683/udp --rm updatehub/updatehub-ce:latest
```

Build SoC bootloader and flash
```
west build -b frdm_k64f -d build/mcuboot-frdm_k64f bootloader/mcuboot/boot/zephyr
west flash -d build/mcuboot-frdm_k64f
```

Build UpdateHub sample, sign and flash
```
west build -b frdm_k64f -d build/app zephyr/samples/subsys/mgmt/updatehub -- -DOVERLAY_CONFIG=overlay-prj.conf
west sign -t imgtool -d build/app -- --version 1.0.0 --pad --key bootloader/mcuboot/root-rsa-2048.pem
west flash -d build/app --hex-file build/app/zephyr/zephyr.signed.hex
```

Sign and package using **uhu**
```
west sign --no-hex --bin -B build/zephyr-2.0.0.bin -t imgtool -d build/app -- --version 2.0.0 --key bootloader/mcuboot/root-rsa-2048.pem
uhu package archive --output build/zephyr-2.0.0.pkg
```

On the UpdateHub-CE UI go to **packages** and upload the `zephyr-2.0.0.pkg`
On the UpdateHub-CE UI go to **rollouts** and create the rollout

CC: @otavio

Note

The below error is on investigation and seems to be unrelated to UpdateHub since it is an internal API provided by dfu subsystem.
```
I: Firmware download complete
E: Could not mark partition to upgrade
```

### CODE REVIEW

**Review by otavio — APPROVED** [review]

File: subsys/mgmt/updatehub/updatehub.c [hunk 1]
```diff
@@ -847,19 +847,31 @@ enum updatehub_response z_impl_updatehub_probe(void)
 				   recv_probe_sh_string_descr,
 				   ARRAY_SIZE(recv_probe_sh_string_descr),
 				   &metadata_any_boards) < 0) {
-			LOG_ERR("Could not parse json");
+			LOG_ERR("Could not parse the any json");
```
Comment (nordicjm) [inline subsys/mgmt/updatehub/updatehub.c:850]: the original here is correct, the replacement is incorrect

File: subsys/mgmt/updatehub/updatehub.c [hunk 2]
```diff
@@ -847,19 +847,31 @@ enum updatehub_response z_impl_updatehub_probe(void)
...
+				struct resp_probe_objects *obj =
+					&metadata_any_boards.objects[i].objects[j].objects;
+				LOG_DBG("\tMode: %s\n\tSHA: %s\n\tSize: %d",
+					obj->mode, obj->sha256sum, obj->size);
+			}
+		}
+
 		if (metadata_any_boards.objects_len != 2) {
-			LOG_ERR("Could not parse json");
+			LOG_ERR("The any objects size is incorrect");
```
Comment (nordicjm) [inline subsys/mgmt/updatehub/updatehub.c:868]: Something like `Object length of "any boards metadata" is incorrect`

File: subsys/mgmt/updatehub/updatehub.c [hunk 3]
```diff
@@ -868,14 +880,26 @@ enum updatehub_response z_impl_updatehub_probe(void)
...
+				struct resp_probe_objects *obj =
+					&metadata_some_boards.objects[i].objects[j].objects;
+				LOG_DBG("\tMode: %s\n\tSHA: %s\n\tSize: %d\n",
+					obj->mode, obj->sha256sum, obj->size);
+			}
+		}
+
 		if (metadata_some_boards.objects_len != 2) {
-			LOG_ERR("Could not parse json");
+			LOG_ERR("The some objects size is incorrect");
```
Comment (nordicjm) [inline subsys/mgmt/updatehub/updatehub.c:902]: e.g. `Object length of "some boards metadata" is incorrect`

**Review by nordicjm — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
