### PR TITLE
drivers: flash: stm32 qspi: Make delayed data sampling configurable

### LINKED ISSUE #99099: STM32 QSPI sample shifting prevents communication with GD25Q128E flash chip
### Describe the bug

We have a custom board with STM32G473VET6 MCU and GD25Q128EWIGR SPI flash connected to QSPI. With the upcoming Zephyr v4.3 communication with the chip stopped working properly (in terms of init process and filesystem access).

Releases v3.7 LTS, v4.2 and v4.3-rc{1,2} have been tested:
* v3.7.0 OK
* v4.2.0 OK
* v4.3.0-rc1 NOK
* v4.3.0-rc2 NOK

git bisect lead to identifying cause of behavior change to be commit b147d78c2f183c6ded5342e77fe8af5d97433779 which enabled sample shifting (SSHIFT) for non-dual flash configurations.

Disabling SSHIFT fixes the issue in our case.

Working around with dummy cycles and QSPI CLK does not really solve the problem:
* setting dummy cycles for SFDP from fixed 8 to 7 does help in this case only
* setting dummy cycles for JEDEC ID reading from default 8 to 7 does _not_ help
  * ```st,read-id-dummy-cycles = <N>;```
* lowering dummy cycles for data access not tested -- default 0 dummy cycles
* changing QSPI CLK from 104 MHz to 1 MHz does _not_ help
* SPI bus width is not set (i.e. 1-bit); tested with 4 bits too
  * ```spi-bus-width = <N>;```
* all of the above tested in different mixups
* the only way communication, filesystem and filesystem tests (read/write/verify) were working again was disabling sample shifting

### Regression

- [x] This is a regression.

### Steps to reproduce

1. clean build the firmware (new build dir, west update)
2. flash & run the firmware
3. observe zephyr shell for flash_stm32_qspi and littlefs entries
4. read JEDED ID with flash_read_jedec_id()

### Relevant log output

```shell
## OK
uart:~$ kernel reboot cold
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.000,000] <inf> flash_stm32_qspi: qspi-nor-flash@90000000: SFDP v 1.6 AP ff with 2 PH
[00:00:00.000,000] <inf> flash_stm32_qspi: PH0: ff00 rev 1.6: 16 DW @ 30
[00:00:00.000,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.001,000] <inf> flash_stm32_qspi: qspi-nor-flash@90000000: 16 MiBy flash
[00:00:00.001,000] <inf> flash_stm32_qspi: PH1: ffc8 rev 1.0: 3 DW @ 90
[00:00:00.001,000] <inf> flash_stm32_qspi: NOR quad-flash at 0x90000000 (0x1000000 bytes)
[00:00:00.299,000] <inf> littlefs: littlefs partition at /lfs
[00:00:00.299,000] <inf> littlefs: LittleFS version 2.11, disk version 2.1
[00:00:00.301,000] <inf> littlefs: FS at qspi-nor-flash@90000000:0x0 is 4096 0x1000-byte blocks with 512 cycle
[00:00:00.301,000] <inf> littlefs: partition sizes: rd 16 ; pr 16 ; ca 64 ; la 64
[00:00:00.302,000] <inf> littlefs: Automount /lfs succeeded

## NOK
uart:~$ kernel reboot cold
[00:00:00.001,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.001,000] <err> flash_stm32_qspi: SFDP magic a0888ca6 invalid
[00:00:00.300,000] <inf> littlefs: littlefs partition at /lfs
[00:00:00.300,000] <inf> littlefs: LittleFS version 2.11, disk version 2.1
[00:00:00.300,000] <err> littlefs: can't open flash area 0, err -19
[00:00:00.300,000] <err> fs: fs mount error (-19)
[00:00:00.300,000] <err> littlefs: Automount /lfs failed: -19
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Linux Ubuntu 24.04 LTS
- toolchain: Zephyr SDK 0.16.9 and 0.17.4
- commits tested:
  - git bisect: from v3.7.1/9f824289b28d7aea2eee74f62787c385a5005453 to v4.3.0-rc2 (~13.7k commits)
  - manual verification: v3.7.0, v4.2.0, v4.3.0-rc2

### Additional Context

```
&quadspi {
	pinctrl-0 = <&quadspi1_clk_pa3 &quadspi1_bk1_ncs_pa2
		     &quadspi1_bk1_io0_pb1 &quadspi1_bk1_io1_pb0
		     &quadspi1_bk1_io2_pa7 &quadspi1_bk1_io3_pa6>;
	pinctrl-1 = <&analog_pa3 &analog_pa2
		     &analog_pb1 &analog_pb0
		     &analog_pa7 &analog_pa6>;
	pinctrl-names = "default", "sleep";
	status = "okay";

	gd25q128e: qspi-nor-flash@90000000 {
		compatible = "st,stm32-qspi-nor";
		reg = <0x90000000>;
		size = <DT_SIZE_M(128)>;
		qspi-max-frequency = <DT_FREQ_M(104)>;
		label = "ext_flash";
		status = "okay";

		partitions {
			compatible = "fixed-partitions";
			#address-cells = <1>;
			#size-cells = <1>;
			storage_partition: partition@0 {
				label = "storage";
				reg = <0x00000000 DT_SIZE_M(16)>;
			};
		};
	};
};
```

```
/ {
	fstab {
		compatible = "zephyr,fstab";
		lfs_cfg: lfs {
			compatible = "zephyr,fstab,littlefs";
			mount-point = "/lfs";
			partition = <&storage_partition>;
			read-size = <16>;
			prog-size = <16>;
			cache-size = <64>;
			lookahead-size = <64>;
			block-cycles = <512>;
			automount;
		};
	};
};
```

Needed before v4.3:
```
/ {
	soc {
			quadspi: spi@a0001000 {
					compatible = "st,stm32-qspi";
					#address-cells = <1>;
					#size-cells = <0>;
					reg = <0xa0001000 0x400>, <0x90000000 DT_SIZE_M(256)>;
					interrupts = <95 0>;
					clocks = <&rcc STM32_CLOCK_BUS_AHB3 0x00000100>;
					status = "disabled";
			};
	};
};
```

Disabling SSHIFT for testing, v4.3.0-rc2:
```
diff --git a/drivers/flash/flash_stm32_qspi.c b/drivers/flash/flash_stm32_qspi.c
index e853d91d9a7..49f75d5c1df 100644
--- a/drivers/flash/flash_stm32_qspi.c
+++ b/drivers/flash/flash_stm32_qspi.c
@@ -1631,10 +1631,10 @@ static int flash_stm32_qspi_init(const struct device *dev)
        dev_data->hqspi.Init.ClockPrescaler = prescaler;
        /* Give a bit position from 0 to 31 to the HAL init minus 1 for the DCR1 reg */
        dev_data->hqspi.Init.FlashSize = find_lsb_set(dev_cfg->flash_size) - 2;
-       dev_data->hqspi.Init.SampleShifting = QSPI_SAMPLE_SHIFTING_HALFCYCLE;
        dev_data->hqspi.Init.ChipSelectHighTime = dev_cfg->cs_high_time - 1;
 #if STM32_QSPI_DOUBLE_FLASH
        dev_data->hqspi.Init.DualFlash = QSPI_DUALFLASH_ENABLE;
+       dev_data->hqspi.Init.SampleShifting = QSPI_SAMPLE_SHIFTING_HALFCYCLE;

        /*
         * When the DTS has <dual-flash>, it means Dual Flash Mode
```

Setting SFDP dummy cycles for testing, example for 7, v4.3.0-rc2:
```
diff --git a/drivers/flash/flash_stm32_qspi.c b/drivers/flash/flash_stm32_qspi.c
index e853d91d9a7..ccf76d95347 100644
--- a/drivers/flash/flash_stm32_qspi.c
+++ b/drivers/flash/flash_stm32_qspi.c
@@ -495,7 +495,7 @@ static int qspi_read_sfdp(const struct device *dev, off_t addr, void *data,
                .Instruction = JESD216_CMD_READ_SFDP,
                .Address = addr,
                .AddressSize = QSPI_ADDRESS_24_BITS,
-               .DummyCycles = 8,
+               .DummyCycles = 7,
                .InstructionMode = QSPI_INSTRUCTION_1_LINE,
                .AddressMode = QSPI_ADDRESS_1_LINE,
                .DataMode = QSPI_DATA_1_LINE,
```

Output for SFDP reading with 7 dummy cycles:
```
[00:00:00.001,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.001,000] <inf> flash_stm32_qspi: qspi-nor-flash@90000000: SFDP v 1.6 AP ff with 2 PH
[00:00:00.001,000] <inf> flash_stm32_qspi: PH0: ff00 rev 1.6: 16 DW @ 30
[00:00:00.001,000] <inf> flash_stm32_qspi: Reading SFDP
[00:00:00.001,000] <inf> flash_stm32_qspi: qspi-nor-flash@90000000: 16 MiBy flash
[00:00:00.001,000] <inf> flash_stm32_qspi: PH1: ffc8 rev 1.0: 3 DW @ 90
[00:00:00.001,000] <inf> flash_stm32_qspi: NOR quad-flash at 0x90000000 (0x1000000 bytes)
[00:00:00.300,000] <inf> littlefs: littlefs partition at /lfs
[00:00:00.300,000] <inf> littlefs: LittleFS version 2.11, disk version 2.1
[00:00:00.302,000] <inf> littlefs: FS at qspi-nor-flash@90000000:0x0 is 4096 0x1000-byte blocks with 512 cycle
[00:00:00.302,000] <inf> littlefs: partition sizes: rd 16 ; pr 16 ; ca 64 ; la 64
[00:00:00.302,000] <err> littlefs: WEST_TOPDIR/modules/fs/littlefs/lfs.c:1386: Corrupted dir pair at {0x1, 0x0}
[00:00:00.302,000] <wrn> littlefs: can't mount (LFS -84); formatting
[00:00:00.302,000] <wrn> littlefs: WEST_TOPDIR/modules/fs/littlefs/lfs.c:2109: Superblock 0x0 has become unwritable
[00:00:00.302,000] <err> littlefs: format failed (LFS -28)
[00:00:00.302,000] <err> fs: fs mount error (-28)
[00:00:00.302,000] <err> littlefs: Automount /lfs failed: -28
```

Making sure flash is erased and rebooting in case SFDP looks ok:
```
uart:~$ flash erase ext_flash 0 1000000
uart:~$ flash erase qspi-nor-flash@90000000 0 1000000
uart:~$ flash read qspi-nor-flash@90000000 0 128
00000000: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000010: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000020: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000030: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000040: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000050: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000060: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000070: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000080: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000090: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000000A0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000000B0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000000C0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000000D0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000000E0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000000F0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000100: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000110: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00000120: ff ff ff ff ff ff ff ff                          |........         |

uart:~$ flash read qspi-nor-flash@90000000 1000 128
00001000: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001010: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001020: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001030: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001040: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001050: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001060: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001070: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001080: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001090: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000010A0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000010B0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000010C0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000010D0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000010E0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
000010F0: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001100: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001110: ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff |........ ........|
00001120: ff ff ff ff ff ff ff ff                          |........         |

uart:~ kernel reboot cold
```

JEDEC ID testing:
```
// CONFIG_FLASH_JESD216_API=y
const struct device *flash_dev = device_get_binding("ext_flash");
uint8_t jedec_id[3];
int ret = flash_read_jedec_id(flash_dev, jedec_id);
if (ret == 0) {
    // expected 18 C8 40
}
```

### PR DESCRIPTION
**Pull request by adazot**
PR #92742 enabled STM32 QSPI delayed data sampling (SSHIFT) for single flash mode. This caused communication issues with our flash chip starting with SFDP reading. From my point of view this is regression introduced in v4.3.

The only reliable solution found was to disable SSHIFT. SSHIFT is not configurable in the current codebase.

This PR implements configurable SSHIFT (ssht-enable), similarly to what XSPI and OSPI drivers implement.

Fixes #99099

### CODE REVIEW

**Review by JarmouniA — DISMISSED** [review]
The original behavior was that Sample Shifting is enabled on all platforms using dual-flash. Then it got enabled for all platforms https://github.com/zephyrproject-rtos/zephyr/commit/b147d78c2f183c6ded5342e77fe8af5d97433779. Now you are disabling it on all platforms, which is not right.
You need to add the new property to all in-tree platforms using dual-flash to restore the original setting.

**Comment by JarmouniA** [comment]
Cc @taltenbach

File: drivers/flash/flash_stm32_qspi.c [hunk 1]
```diff
@@ -1840,7 +1839,9 @@ static struct flash_stm32_qspi_data flash_stm32_qspi_dev_data = {
 		.Instance = (QUADSPI_TypeDef *)DT_REG_ADDR(STM32_QSPI_NODE),
 		.Init = {
 			.FifoThreshold = STM32_QSPI_FIFO_THRESHOLD,
-			.SampleShifting = QSPI_SAMPLE_SHIFTING_NONE,
+			.SampleShifting = (DT_PROP(STM32_QSPI_NODE, ssht_enable)
+					? QSPI_SAMPLE_SHIFTING_HALFCYCLE
+					: QSPI_SAMPLE_SHIFTING_NONE),
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_qspi.c]: You could remove the outer parentheses (despite ospi/xspi drivers add them)

**Review by etienne-lms — COMMENTED** [review]
I think it would be more consistent to place commit *"dts: bindings: stm32 qspi: add ssht-enable property"* before commit *"drivers: flash: stm32 qspi: Make delayed data sampling configurable"* in your series.
That said, LGTM.

**Comment by JarmouniA** [comment]
> You need to add the new property to all in-tree platforms using dual-flash to restore the original setting.

This is also not sufficient. Downstream users, with dual-flash setups, who relied on the feature being enabled by default, will have to add the new property in DT. So an entry in the migration guide is needed.

File: doc/releases/migration-guide-4.3.rst [hunk 2]
```diff
@@ -167,6 +167,13 @@ Phy
   clock-reference. The selection directly depends on the value on OTGHSSEL (OTG_HS PHY kernel
   clock source selection) located in the RCC_CCIPR2 register.
 
+QSPI
+===
+* Nodes with compatible property :dtcompatible:`st,stm32-qspi` configured with ``dual-flash``
```
Comment (JarmouniA) [inline doc/releases/migration-guide-4.3.rst]:
```suggestion
* :dtcompatible:`st,stm32-qspi` compatible nodes configured with ``dual-flash``
```

**Review by JarmouniA — DISMISSED** [review]

**Review by JarmouniA — DISMISSED** [review]

File: dts/bindings/qspi/st,stm32-qspi.yaml [hunk 3]
```diff
@@ -59,6 +59,12 @@ properties:
 
       For example
          dma-names = "tx_rx";
+  ssht-enable:
```
Comment (etienne-lms) [inline dts/bindings/qspi/st,stm32-qspi.yaml:63]: For consistency, prefer with an empty line above.

File: doc/releases/migration-guide-4.3.rst [hunk 4]
```diff
@@ -167,6 +167,14 @@ Phy
   clock-reference. The selection directly depends on the value on OTGHSSEL (OTG_HS PHY kernel
   clock source selection) located in the RCC_CCIPR2 register.
 
+QSPI
+===
+
+* :dtcompatible:`st,stm32-qspi` compatible nodes configured with ``dual-flash`` property
```
Comment (etienne-lms) [inline doc/releases/migration-guide-4.3.rst]: Is it really only the dual-flash devices that need to set `ssht-enable`?

**Review by etienne-lms — COMMENTED** [review]
It seems there are other boards that need to be updated with

File: doc/releases/migration-guide-4.3.rst (hunk 4 above)
Comment (JarmouniA) [reply doc/releases/migration-guide-4.3.rst]: It was the original behavior before https://github.com/zephyrproject-rtos/zephyr/commit/b147d78c2f183c6ded5342e77fe8af5d97433779

File: dts/bindings/qspi/st,stm32-qspi.yaml (hunk 3 above)
Comment (adazot) [reply dts/bindings/qspi/st,stm32-qspi.yaml:63]: missed that, thanks

File: doc/releases/migration-guide-4.3.rst [hunk 5]
```diff
@@ -167,6 +167,14 @@ Phy
   clock-reference. The selection directly depends on the value on OTGHSSEL (OTG_HS PHY kernel
   clock source selection) located in the RCC_CCIPR2 register.
 
+QSPI
+===
```
Comment (erwango) [inline doc/releases/migration-guide-4.3.rst]: This should be moved to `doc/releases/migration-guide-4.4.rst`

File: dts/bindings/qspi/st,stm32-qspi.yaml [hunk 6]
```diff
@@ -59,6 +59,12 @@ properties:
...
+    type: boolean
+    description: |
+      Enables Sample Shifting half-cycle.
+
+      It is recommended to be enabled in STR mode and disabled in DTR mode.
```
Comment (erwango) [inline dts/bindings/qspi/st,stm32-qspi.yaml:68]: Is it only a recommendation and it can be useful to do otherwise in some cases, if you know what you're doing ?
Or is it kind of mandatory and then it can set automatically depending on the mode ?

**Review by erwango — CHANGES_REQUESTED** [review]

File: doc/releases/migration-guide-4.3.rst (hunk 5 above)
Comment (adazot) [reply doc/releases/migration-guide-4.3.rst]: done, not pushed

File: doc/releases/migration-guide-4.3.rst (hunk 4 above)
Comment (adazot) [reply doc/releases/migration-guide-4.3.rst]: now with v4.3 sample shifting is always on. Shall I still keep ``ssht-enable`` only for dual-flash configurations?

Comment (JarmouniA) [reply doc/releases/migration-guide-4.3.rst]: > Shall I still keep ssht-enable only for dual-flash configurations?

Yes, and the 1st 3 commits will be backported to v4.3

File: dts/bindings/qspi/st,stm32-qspi.yaml (hunk 6 above)
Comment (adazot) [reply dts/bindings/qspi/st,stm32-qspi.yaml:68]: To be honest this is just copied from the XSPI/OSPI, assuming number of data lines does not really matter, and to be consistent between all drivers. Conceptually this still does make sense to me. In STR shifting shouldn't harm, in DTR quite the opposite. But in a specific case different setting could help. Like in my case now and reason for this pull request -- STR with sample shifting breaks communication. So I think as a recommendation this is still valid, and is still valid to be a recommendation only.

**Review by JarmouniA — APPROVED** [review]

**Review by erwango — APPROVED** [review]
