### PR TITLE
drivers: adc: stm32 adc driver disable before calibration

### LINKED ISSUE #54932: stm32 ADC init stage before adc_stm32_calib need disable ADC
**Describe the bug**
In stm32 adc init stage befor adc_stm32_calib need disable adc, here is the code:
https://github.com/zephyrproject-rtos/zephyr/blob/0aa4e38bbe806be684992d6782745da3109c9e06/drivers/adc/adc_stm32.c#L1219

 - STM32G0B1RC
 - bootloader use ADC then bootup application it will loop wait calibration done.

**Additional context**
In RM0555 Rev 5 pdf page 347:
Software calibration procedure
1.Ensure that ADEN = 0, ADVREGEN = 1 and DMAEN = 0.
2.Set ADCAL = 1.
3.Wait until ADCAL = 0 (or until EOCAL = 1). This can be handled by interrupt if the
interrupt is enabled by setting the EOCALIE bit in the ADC_IER register
4.The calibration factor can be read from bits 6:0 of ADC_DR or ADC_CALFACT
registers.

and in function start_read at adc_stm32.c
https://github.com/zephyrproject-rtos/zephyr/blob/0aa4e38bbe806be684992d6782745da3109c9e06/drivers/adc/adc_stm32.c#L865
declared can not calibrate the ADC while the ADC is enable, so in stm32 adc init befor adc_stm32_calib, it need disable ADC before adc_stm32_calib function.

### PR DESCRIPTION
**Pull request by FRASTM**
In the adc_stm32_init() function, when adc_stm32_calib() is called, the ADC is not yet enabled but still disabled.
This patch makes sure to Disable the ADC before  its calibration.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54932

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

File: drivers/adc/adc_stm32.c [hunk 1]
```diff
@@ -1255,6 +1255,7 @@ static int adc_stm32_init(const struct device *dev)
 	 * Calibration of F1 and F3 (ADC1_V2_5) series has to be started
 	 * after ADC Module is enabled.
 	 */
+	adc_stm32_disable(adc);
 	adc_stm32_calib(dev);
```
Comment (erwango) [inline drivers/adc/adc_stm32.c:1259]: Non blocking: I wonder if we shouldn't a complete reset here (which means adding reset props and all)

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]
