### PR TITLE
The type of ssize_t should be signed

### LINKED ISSUE #17378: samples: net: echo-server: no return packet
**Describe the bug**
Echo server doesn't reply back the payload to the sender.
It looks like a side effect of this patch according to _git bisect_ - 2a63e34

**To Reproduce**
Followed steps in https://docs.zephyrproject.org/latest/guides/networking/qemu_setup.html#basic-setup

Send TCP from echo-client

**Expected behavior**
Echo-server should reply the packet with received payload

**Impact**
Basic functionality is broken.

**Environment (please complete the following information):**
 - OS: Qemu_x86
 - Toolchain: Zephyr SDK

### PR DESCRIPTION
**Pull request by jukkar**
Fixes #17378

### CODE REVIEW

File: lib/libc/minimal/include/sys/types.h [hunk 1]
```diff
@@ -15,7 +15,9 @@ typedef unsigned int mode_t;
 #if !defined(__ssize_t_defined)
 #define __ssize_t_defined
 
+#define unsigned signed
```
Comment (andrewboie) [inline lib/libc/minimal/include/sys/types.h]: what is the root cause which makes this necessary?
surely there is a better way to fix this

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]

File: lib/libc/minimal/include/sys/types.h (hunk 1 above)
Comment (jukkar) [reply lib/libc/minimal/include/sys/types.h]: The `include/toolchain/xcc_missing_defs.h` has this comment
```
/*
 * xcc already defines __SIZE_TYPE__ as "unsigned int" but there is no way
 * to safeguard that here with preprocessor equality.
 */
```

Comment (jukkar) [reply lib/libc/minimal/include/sys/types.h]: The commit 2a63e34 says
```
types.h was wrongly defining unsigned as signed and following
undefining it. This definition was not being used anywhere though.
```
so it seems that the change was actually not fixing anything. Thus the simplest solution is just to revert that commit and figure out other solution if that is really needed.

Comment (jukkar) [reply lib/libc/minimal/include/sys/types.h]: The original commit that introduced the define/undef magic is this one 458e2ed1330d7e08c56bf5073ae3feadcfe8059d

**Review by tyrantlizard77 — APPROVED** [review]
Looking at the GCC headers, they do the same trick of redefining unsigned.
It's gross, but oh well.

File: lib/libc/minimal/include/sys/types.h (hunk 1 above)
Comment (ceolin) [reply lib/libc/minimal/include/sys/types.h]: Indeed that commit was not fixing the problem. One to define ssize_t is based on SIZE_MAX that is part of C standard. ssize_t is just part of POSIX standard.

```
#if __SIZE_MAX__ == __UINT32_MAX__
#define SSIZE_MAX       __INT_MAX__
#elif __SIZE_MAX__ == __UINT64_MAX__
#define SSIZE_MAX       __INT64_MAX__
#else
#error "unexpected __SIZE_MAX__ value"
#endif
```

That' being said it seems that this can have some caveats that is not clear to me.
The problem with the undefine trick is that it *may* (not sure if the standard cover only macro or all identifier) violates C standard 
```
If the program removes (with #undef) any macro definition of an identifier in the first
group listed above, the behavior is undefined.
```
But it is violating other code guidelines (aka MISRA) for sure.

**Comment by ceolin** [comment]
> Looking at the GCC headers, they do the same trick of redefining unsigned.
> It's gross, but oh well.

gcc is doing it only in its testsuite, and to be honest gcc defines ssize_t in other ways in its testsuite.
Only for BEOS port that gcc exports this type, and does in this way:

`gcc/ginclude/stddef.h:typedef long ssize_t;`

The problem with this hack (besides the one I've mentioned), is that a compiler can do

```
typedef unsigned int uint;
typedef uint size_t;
```

Then this thing won't work

**Review by ceolin — APPROVED** [review]
That's being said, is better to have it then leave it broken :)
