### PR TITLE
Bluetooth: Controller: nRF54Lx: Fix Radio Tx Power set

### LINKED ISSUE #99588: Bluetooth: Controller: nRF54Lx Radio Tx Power incorrect
### Describe the bug

Default Radio Tx Power on nRF54L15dk has been observed to be higher than 0 dBm.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Build Bluetooth peripheral_hr sample for nRF54Lx
2. Power Profile using PPK II kit
3. Current consumption is high for Radio transmissions.

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Linux
- Toolchain: Zephyr SDK
- Commit SHA: (please specify exact revision)
- Version: main branch

### Additional Context

This bug is relevant for recent changes and may relate to the fix proposed in PR #99582: https://github.com/zephyrproject-rtos/zephyr/pull/99582. Likely affects Bluetooth controller users on nRF54Lx devices.

### PR DESCRIPTION
**Pull request by cvinayak**
Fix incorrectly high Radio Tx Power being set as default.

Fixes #99588.

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 1]
```diff
@@ -311,29 +311,14 @@ void radio_phy_set(uint8_t phy, uint8_t flags)
...
-#elif defined(CONFIG_SOC_COMPATIBLE_NRF5340_CPUNET)
-	uint32_t value;
-
-	/* NOTE: TXPOWER register only accepts upto 0dBm, hence use the HAL
-	 * floor value for the TXPOWER register. Permit +3dBm by using high
-	 * voltage being set for radio.
-	 */
-	value = hal_radio_tx_power_floor(power);
-	NRF_RADIO->TXPOWER = value;
+#if defined(CONFIG_SOC_COMPATIBLE_NRF5340_CPUNET)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:319]: Consider IS_ENABLED

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h [hunk 2]
```diff
@@ -67,43 +67,77 @@ static inline uint32_t hal_radio_phy_mode_get(uint8_t phy, uint8_t flags)
...
 
-static inline uint32_t hal_radio_tx_power_max_get(void)
+static inline int8_t hal_radio_tx_power_max_get(void)
 {
-	return RADIO_TXPOWER_TXPOWER_Pos4dBm;
+	return 4; /* +4 dBm */
 }
 
-static inline uint32_t hal_radio_tx_power_floor(int8_t tx_power_lvl)
+static inline int8_t hal_radio_tx_power_floor(int8_t tx_power_lvl)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h:80]: I assume all the numbers from this function is based on some specification somewhere?

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h:80]: In `hal_radio_tx_power_value` we use defined values as return values, but the code was also changed to use literal values. Does it make sense to define the values instead of the literal values?

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf52833.h [hunk 3]
```diff
@@ -443,71 +443,128 @@ static inline uint32_t hal_radio_phy_mode_get(uint8_t phy, uint8_t flags)
...
+	return -40; /* -40 dBm */
+}
+
+static inline int8_t hal_radio_tx_power_max_get(void)
+{
+	return 8; /* +8 dBm */
 }
 
-static inline uint32_t hal_radio_tx_power_max_get(void)
+static inline int8_t hal_radio_tx_power_floor(int8_t tx_power_lvl)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf52833.h:456]: I wondered if there was a smarter way to implement these functions. Asked Copilot and got 

```c
static inline int8_t hal_radio_tx_power_floor(int8_t tx_power_lvl)
{
    /* Allowed TX power levels in descending order. Keep the -40 sentinel last. */
    static const int8_t levels[] = {8, 7, 6, 5, 4, 3, 2, 0, -4, -8, -12, -16, -20, -40};
    const size_t n = sizeof(levels) / sizeof(levels[0]);

    for (size_t i = 0; i < n; ++i) {
        if (tx_power_lvl >= levels[i]) {
            return levels[i];
        }
    }

    /* Should never get here because -40 is last, but return a fallback to be safe. */
    return levels[n - 1];
}
```

In number of lines it's certainly short, and it does avoid duplication of values, e.g. 

```c
	if (tx_power_lvl >= 7) {
		return 7;
	}
```

Is slightly more error prone if the 2 literal value are not the same. 

I'm OK either way, and I'm not sure about the sideeffects w.r.t. performance and code size

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf52.h [hunk 4]
```diff
@@ -408,71 +408,128 @@ static inline uint32_t hal_radio_phy_mode_get(uint8_t phy, uint8_t flags)
...
+	return 8; /* +8 dBm */
 }
 
-static inline uint32_t hal_radio_tx_power_max_get(void)
+static inline int8_t hal_radio_tx_power_floor(int8_t tx_power_lvl)
 {
-	return RADIO_TXPOWER_TXPOWER_Pos8dBm;
+	if (tx_power_lvl >= 8) {
+		return 8;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf52.h:425]: I do wonder that if these values are related to the hardware, is it something that should belong in device tree?

**Review by Thalley — APPROVED** [review]
Overall the changes look OK, but had a few comments/questions

**Review by carlescufi — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:319]: The header file does not get included for function.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h [hunk 5]
```diff
@@ -67,43 +67,77 @@ static inline uint32_t hal_radio_phy_mode_get(uint8_t phy, uint8_t flags)
 	return mode;
 }
 
-static inline uint32_t hal_radio_tx_power_min_get(void)
+static inline int8_t hal_radio_tx_power_min_get(void)
 {
-	return RADIO_TXPOWER_TXPOWER_Neg30dBm;
+	return -30; /* -30 dBm */
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h:72]: This has been like this before. Not changing.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf52833.h (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf52833.h:456]: Actually, use of `for` loop seems optimal... will consider this...

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h:80]: There is scope for improvement... will consider to enhance this code...

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h [hunk 6]
```diff
@@ -67,43 +67,77 @@ static inline uint32_t hal_radio_phy_mode_get(uint8_t phy, uint8_t flags)
...
+	if (tx_power_lvl >= -16) {
+		return -16;
+	}
+
+	if (tx_power_lvl >= -20) {
+		return -20;
+	}
+
+	/* Note: The -30 dBm power level is deprecated so ignore it! */
+	return -40;
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf51.h:111]: not changing

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf52.h (hunk 4 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_sim_nrf52.h:425]: These values are h/w specific... yes, in theory should be inherited from devicetree... not sure if they are there now.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:319]: Not sure I follow - Can you elaborate?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c:319]: `hal_radio_tx_power_high_voltage_set()`  is defined `static inline` in 

https://github.com/cvinayak/zephyr/blob/d95a862c62939a375a602d8eb3c7c37aba7cfde8/subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5340.h#L569-L574

and that header file is only included for nrf5340 build.
