### PR TITLE
soc: esp32c6: fix wifi by proper interrupt handling

### LINKED ISSUE #83784: apsta_mode example fail to run on ESP32C6.
**Describe the bug**

apsta_mode example fail to run on esp32c6_devkitc board.
The example doesn't have overlay file for this dev kit yet, so i create a new file `esp32c6_devkitc.overlay` based on similar ESP32 overlay.
Nothing else was changed(Kconfig, code)
```
&wifi {
	status = "okay";
};

/ {
	wifi_ap: wifi_ap {
		compatible = "espressif,esp32-wifi";
		status = "okay";
	};
};
```
From the log, it seem like it fails to send TX packet
**To Reproduce**

Run this Example with above overlay file
**Expected behavior**

Should run this example normally
**Impact**

**Logs and console output**

```
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:2
load:0x40800000,len:0x284ec
0x40800000: _esp32c6_vector_table at ??:?

load:0x40828500,len:0x3f8c
0x40828500: ?? at /home/bacphan/zephyrproject/modules/hal/espressif/components/esp_hw_support/sleep_modes.c:234

SHA-256 comparison failed:
Calculated: 94ca3e56a36618baf92e9b897ac669ccf792e4d8fd1af35927bbdcb9c8c61480
Expected: 00000000403b0000000000000000000000000000000000000000000000000000
Attempting to boot anyway...
entry 0x4080375e
0x4080375e: __start at /home/bacphan/zephyrproject/zephyr/soc/espressif/common/loader.c:247

I (110) soc_init: ESP Simple boot
I (110) soc_init: compile time Jan 10 2025 15:43:40
I (110) spi_flash: detected chip: boya
I (111) spi_flash: flash io: dio
W (112) spi_flash: Detected size(16384k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (125) soc_init: chip revision: v0.1
I (128) flash_init: SPI Speed      : 80MHz
I (132) flash_init: SPI Mode       : DIO
I (136) flash_init: SPI Flash Size : 16MB
I (139) soc_random: Enabling RNG early entropy source
I (144) boot: DRAM: lma 0x00000020 vma 0x40800000 len 0x284ec  (165100)
0x40800000: _esp32c6_vector_table at ??:?

I (150) boot: DRAM: lma 0x00028514 vma 0x40828500 len 0x3f8c   (16268)
0x40828500: ?? at /home/bacphan/zephyrproject/modules/hal/espressif/components/esp_hw_support/sleep_modes.c:234

I (157) boot: padd: lma 0x0002c4b8 vma 0x00000000 len 0x3b40   (15168)
I (163) boot: IMAP: lma 0x00030000 vma 0x42800000 len 0xedd8   (60888)
0x42800000: _image_drom_vaddr at ??:?

I (169) boot: padd: lma 0x0003ede0 vma 0x00000000 len 0x1218   (4632)
I (175) boot: IMAP: lma 0x00040000 vma 0x42000000 len 0x4df30  (319280)
0x42000000: ieee80211_ampdu_reorder at ??:?

I (182) boot: Image with 6 segments
I (185) boot: DROM segment: paddr=00030000h, vaddr=42800000h, size=0EDE0h ( 60896) map
I (192) boot: IROM segment: paddr=00040000h, vaddr=42000000h, size=4DF2Eh (319278) map
I (211) soc_random: Disabling RNG early entropy source
I (212) boot: Jumping to the main image...
I (243) heap_runtime: ESP heap runtime init at 0x4083e150 size 249 kB.
[00:00:00.037,000] <inf> wifi_init: rx ba win: 6
[00:00:00.037,000] <inf> wifi_init: WiFi IRAM OP enabled
*** Booting Zephyr OS build v4.0.0-1926-g7c4abb1eb9fd ***
[00:00:05.038,000] <inf> MAIN: Turning on AP Mode
[00:00:05.038,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: Started DHCPv4 server, address pool:
[00:00:05.038,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     0: 192.168.4.11
[00:00:05.038,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     1: 192.168.4.12
[00:00:05.038,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     2: 192.168.4.13
[00:00:05.038,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     3: 192.168.4.14
[00:00:05.038,000] <inf> MAIN: DHCPv4 server started...

[00:00:05.131,000] <err> esp32_wifi: Failed to send packet
[00:00:05.131,000] <err> esp32_wifi: Failed to send packet
[00:00:05.131,000] <err> esp32_wifi: Failed to send packet
[00:00:05.131,000] <err> esp32_wifi: Failed to send packet
[00:00:05.132,000] <inf> MAIN: AP Mode is enabled. Waiting for station to connect
[00:00:05.132,000] <inf> MAIN: Connecting to SSID: SSID

[00:00:05.132,000] <inf> MAIN: AP Mode is disabled.
[00:00:05.133,000] <err> esp32_wifi: Failed to send packet
[00:00:05.133,000] <err> esp32_wifi: Failed to send packet
[00:00:05.133,000] <err> esp32_wifi: Failed to send packet
[00:00:05.133,000] <err> esp32_wifi: Failed to send packet
[00:00:06.134,000] <err> esp32_wifi: Failed to send packet
[00:00:07.135,000] <err> esp32_wifi: Failed to send packet
[00:00:07.537,000] <inf> MAIN: Disconnected from SSID
```
**Environment (please complete the following information):**

Latest commit on main

**Additional context**

### LINKED ISSUE #85466: Can not scan wifi on wifi shell example with esp32c6 devkit
**Describe the bug**
Running wifi shell example on ESP32C6, "wifi scan" command does not return any SSID even after a minute.
**To Reproduce**

Run wifi shell example
**Expected behavior**

Should return list of SSID
**Impact**

**Logs and console output**

```
EESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x18 (JTAG_CPU),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x20000824
SPIWP:0xee
mode:DIO, clock div:2
load:0x40800000,len:0x270d0
load:0x408270e0,len:0x3b20
SHA-256 comparison failed:
Calculated: 905396eb39a02e4c5b6ba99331940f4bfcf0c1e2e36bf9ed07389268fd5256dc
Expected: 00000000d0530000000000000000000000000000000000000000000000000000
Attempting to boot anyway...
entry 0x408037bc
I (54) soc_init: ESP Simple boot
I (54) soc_init: compile time Feb  9 2025 21:31:25
I (55) spi_flash: detected chip: boya
I (55) spi_flash: flash io: dio
W (56) spi_flash: Detected size(16384k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (69) soc_init: chip revision: v0.1
I (72) flash_init: SPI Speed      : 80MHz
I (76) flash_init: SPI Mode       : DIO
I (79) flash_init: SPI Flash Size : 16MB
I (83) soc_random: Enabling RNG early entropy source
I (88) boot: DRAM: lma 0x00000020 vma 0x40800000 len 0x270d0  (159952)
I (94) boot: DRAM: lma 0x000270f8 vma 0x408270e0 len 0x3b20   (15136)
I (100) boot: IRAM: lma 0x0002ac28 vma 0x00000000 len 0x53d0   (21456)
I (106) boot: IMAP: lma 0x00030000 vma 0x42800000 len 0x190f0  (102640)
I (113) boot: IRAM: lma 0x000490f8 vma 0x00000000 len 0x6f00   (28416)
I (119) boot: IMAP: lma 0x00050000 vma 0x42000000 len 0x55ea8  (351912)
I (125) boot: Image with 6 segments
I (128) boot: DROM segment: paddr=00030000h, vaddr=42800000h, size=190F0h (102640) map
I (136) boot: IROM segment: paddr=00050000h, vaddr=42000000h, size=55EA8h (351912) map
I (155) soc_random: Disabling RNG early entropy source
I (155) boot: libc heap size 220 kB.

[00:00:00.029,000] <err> entropy: Error enabling TRNG clock
*** Booting Zephyr OS build v4.0.0-4840-g67e07b7a4116 ***
uart:~$ wifi scan
Scan requested
uart:~$
```

**Environment (please complete the following information):**
Latest commit on main branch zephyr

**Additional context**

A little out of topic, but this is the 3rd issue with Wifi on ESP32 zephyr i encounter, just in 1 month, and every issue is a very basic one like scanning or connecting or being AP. I really want to use Zephyr in my new project, but this is wasting me so much time. I feel like everything is barely glued together.

### LINKED ISSUE #86258: ESP32-C6: Enabling CONFIG_WATCHDOG=y breaks WiFi
**Describe the bug**

As the title indicates. Wifi works normally on ESP32-C6, unless setting CONFIG_WATCHDOG=y, which if set results in no wifi communications. Router log indicates no activity.

**To Reproduce**

Any wifi sample; set CONFIG_WATCHDOG=y

**Expected behavior**

Using the watchdog timer should not break wifi.

**Impact**

showstopper

**Logs and console output**

From samples/net/wifi/apsta_mode with the following patch for C6;
```
Subject: [PATCH] Add esp32c6 to apsta sample

---
 .../wifi/apsta_mode/boards/esp32c6_devkitc.conf | 17 +++++++++++++++++
 .../apsta_mode/boards/esp32c6_devkitc.overlay   | 10 ++++++++++
 2 files changed, 27 insertions(+)
 create mode 100644 samples/net/wifi/apsta_mode/boards/esp32c6_devkitc.conf
 create mode 100644 samples/net/wifi/apsta_mode/boards/esp32c6_devkitc.overlay

diff --git a/samples/net/wifi/apsta_mode/boards/esp32c6_devkitc.conf b/samples/net/wifi/apsta_mode/boards/esp32c6_devkitc.conf
new file mode 100644
index 00000000000..f1f8556ee47
--- /dev/null
+++ b/samples/net/wifi/apsta_mode/boards/esp32c6_devkitc.conf
@@ -0,0 +1,17 @@
+CONFIG_BOOTLOADER_MCUBOOT=y
+CONFIG_WIFI=y
+CONFIG_GPIO=y
+
+CONFIG_NETWORKING=y
+CONFIG_NET_L2_ETHERNET=y
+
+CONFIG_ESP32_WIFI_STA_AUTO_DHCPV4=y
+CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=32
+CONFIG_HEAP_MEM_POOL_SIZE=98304
+
+CONFIG_WIFI_ESP32=y
+CONFIG_ESP32_WIFI_AP_STA_MODE=y
+CONFIG_WIFI_NM=y
+CONFIG_WIFI_NM_MAX_MANAGED_INTERFACES=2
+
+
diff --git a/samples/net/wifi/apsta_mode/boards/esp32c6_devkitc.overlay b/samples/net/wifi/apsta_mode/boards/esp32c6_devkitc.overlay
new file mode 100644
index 00000000000..a53651c69a2
--- /dev/null
+++ b/samples/net/wifi/apsta_mode/boards/esp32c6_devkitc.overlay
@@ -0,0 +1,10 @@
+&wifi {
+	status = "okay";
+};
+
+/ {
+	wifi_ap: wifi_ap {
+		compatible = "espressif,esp32-wifi";
+		status = "okay";
+	};
+};
-- 
2.48.1
```

Success (```#CONFIG_WATCHDOG is not set```):

```
*** Booting Zephyr OS build v4.1.0-rc2-19-gee8266797c17 ***
[00:00:05.039,000] <inf> MAIN: Turning on AP Mode
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: Started DHCPv4 server, address pool:
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 0: 192.168.4.11
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 1: 192.168.4.12
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 2: 192.168.4.13
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 3: 192.168.4.14
[00:00:05.039,000] <inf> MAIN: DHCPv4 server started...

[00:00:05.089,000] <err> esp32_wifi: Failed to send packet
[00:00:05.090,000] <err> esp32_wifi: Failed to send packet
[00:00:05.090,000] <err> esp32_wifi: Failed to send packet
[00:00:05.090,000] <err> esp32_wifi: Failed to send packet
[00:00:05.090,000] <inf> MAIN: AP Mode is enabled. Waiting for station to connect
[00:00:05.090,000] <inf> MAIN: Connecting to SSID: ANET

[00:00:05.091,000] <err> esp32_wifi: Failed to send packet
[00:00:05.091,000] <err> esp32_wifi: Failed to send packet
[00:00:05.091,000] <err> esp32_wifi: Failed to send packet
[00:00:05.091,000] <err> esp32_wifi: Failed to send packet
[00:00:06.091,000] <err> esp32_wifi: Failed to send packet
[00:00:07.092,000] <err> esp32_wifi: Failed to send packet
[00:00:10.240,000] <inf> net_dhcpv4: Received: 192.168.1.84
[00:00:10.240,000] <inf> MAIN: Connected to ANET
```

Failure (```CONFIG_WATCHDOG=y```):
```
*** Booting Zephyr OS build v4.1.0-rc2-19-gee8266797c17 ***
[00:00:05.039,000] <inf> MAIN: Turning on AP Mode
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: Started DHCPv4 server, address pool:
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 0: 192.168.4.11
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 1: 192.168.4.12
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 2: 192.168.4.13
[00:00:05.039,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 3: 192.168.4.14
[00:00:05.039,000] <inf> MAIN: DHCPv4 server started...

[00:00:05.091,000] <err> esp32_wifi: Failed to send packet
[00:00:05.091,000] <err> esp32_wifi: Failed to send packet
[00:00:05.091,000] <err> esp32_wifi: Failed to send packet
[00:00:05.092,000] <err> esp32_wifi: Failed to send packet
[00:00:05.092,000] <inf> MAIN: AP Mode is enabled. Waiting for station to connect
[00:00:05.092,000] <inf> MAIN: Connecting to SSID: ANET

[00:00:05.093,000] <err> esp32_wifi: Failed to send packet
[00:00:05.093,000] <err> esp32_wifi: Failed to send packet
[00:00:05.093,000] <err> esp32_wifi: Failed to send packet
[00:00:05.093,000] <err> esp32_wifi: Failed to send packet
[00:00:06.093,000] <err> esp32_wifi: Failed to send packet
[00:00:07.094,000] <err> esp32_wifi: Failed to send packet
```

### PR DESCRIPTION
**Pull request by sylvioalves**
Current interrupt allocator is not taking into account reserved areas.
In case of esp32c6, Wi-Fi isn't properly configured, causing instability or even non-functional feature.
This adds the reserved area ranges for all risc-v based SoC and unify the slot finding based on interrupt source.
This also fix the scenario where Wi-Fi is disconnected and esp_wifi_send() is called.

Fixes #86258
Fixes #85466
Fixes #83784

### CODE REVIEW

**Comment by sylvioalves** [comment]
This fix some issues regarding esp32c6 Wi-Fi. Will confirm whether the ranges are fully correct.

**Comment by ASerbinski** [comment]
I can confirm that this fixes the issue I reported here; https://github.com/zephyrproject-rtos/zephyr/issues/86258

**Review by wmrsouza — DISMISSED** [review]

**Review by marekmatej — DISMISSED** [review]

File: drivers/interrupt_controller/intc_esp32c3.c [hunk 1]
```diff
@@ -35,129 +33,116 @@ LOG_MODULE_REGISTER(intc_esp32c3, CONFIG_LOG_DEFAULT_LEVEL);
...
-}
+	/* Check if the derived IRQ is usable first */
+	for (int j = 0; j < ESP32C3_INTC_SRCS_PER_IRQ; j++) {
+		int idx = ESP_INTR_IDX(irq, j);
 
-#elif defined(CONFIG_SOC_SERIES_ESP32C6)
+		/* Ensure idx is within a valid range */
+		if (idx >= (ESP_INTC_AVAILABLE_IRQS * ESP32C3_INTC_SRCS_PER_IRQ)) {
+			continue;
+		}
```
Comment (martinjaeger) [inline drivers/interrupt_controller/intc_esp32c3.c:85]: I suggest to use `ARRAY_SIZE` just in case the array is declared differently in the future.

```suggestion
		/* Ensure idx is within a valid range */
		if (idx >= ARRAY_SIZE(esp_intr_irq_alloc)) {
			continue;
		}
```

**Review by martinjaeger — CHANGES_REQUESTED** [review]

**Comment by fabiobaltieri** [comment]
hey, tagging 4.2, bit too big for this stage, let's backport it once 4.0 is released

**Comment by sylvioalves** [comment]
@fabiobaltieri We have another PR that refactors ESP32 interrupt allocator for both riscv and xtensa in a single manager. That PR will be submitted after 4.1 release. This PR addresses esp32c6 Wi-Fi issues and is intended only for this release. I know it is a bit late now but was worth submitting anyway. I have to think whether we can/should backport it later or not. Will check.

**Review by raffarost — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Hey, been pointed out that the issue that this fixes is actually a regression that has been introduced in this cycle (https://github.com/zephyrproject-rtos/zephyr/pull/83213 apparently), so I now think this should be merged before the release. @kartben what do you think? @martinjaeger can you unblock? I really don't want to delay this further at this point.

**Review by kartben — DISMISSED** [review]

**Review by martinjaeger — DISMISSED** [review]
Well, I think that the style issues could still have been quickly fixed. But I agree it's good to get this into the release.

File: drivers/interrupt_controller/intc_esp32c3.c [hunk 2]
```diff
@@ -35,129 +33,116 @@ LOG_MODULE_REGISTER(intc_esp32c3, CONFIG_LOG_DEFAULT_LEVEL);
...
-/* Interrupt overview for ESP32C6:
- * - 0, 3, 4, and 7 are used by the CPU for core-local interrupts (CLINT)
- * - 1 is used for Wi-Fi in Espressif HAL
- * - 2, 5, 6, 8 .. 31 are available for Zephyr
- * - 31 is reserved for disabled interrupts
+/*
+ * Interrupt reserved mask
+ * 0 is reserved
+ * 1 is for Wi-Fi
+ * 3, 4 and 7 are unavailable for PULP CPU as they are bound to Core-Local Interrupts (CLINT)
```
[the remark this answers is not in the document]
Comment (sylvioalves) [reply drivers/interrupt_controller/intc_esp32c3.c:47]: Parallel Ultra Low Power

**Comment by sylvioalves** [comment]
@martinjaeger I only skip renaming files and Kconfig, just maintaining as it has been.

File: drivers/interrupt_controller/intc_esp32c3.c [hunk 3]
```diff
@@ -1,8 +1,8 @@
 /*
- * Copyright (c) 2021 Espressif Systems (Shanghai) Co., Ltd.
- *
- * SPDX-License-Identifier: Apache-2.0
- */
+* Copyright (c) 2021-2025 Espressif Systems (Shanghai) Co., Ltd.
+*
+* SPDX-License-Identifier: Apache-2.0
+*/
```
Comment (martinjaeger) [inline drivers/interrupt_controller/intc_esp32c3.c:5]: The previous indentation was correct.

**Review by martinjaeger — DISMISSED** [review]
Still don't understand the advantage of using a one-dimensional array instead of the previously used two-dimensional array, which would avoid the complicated calculations to translate the tuple `(irq, slot)` into an index, but I won't block because of this.

**Review by wmrsouza — APPROVED** [review]

**Review by raffarost — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
