### PR TITLE
net: http_server: Support reason phrase for chunked encoded response

### LINKED ISSUE #99722: net: http_server: No suuport for reason-phrase for chunked encoded response
### Describe the bug

When using the Zephyr HTTP server, I’ve observed that for dynamic resources, the response status line is sent as HTTP/1.1 200 without a reason-phrase (e.g., "OK"). For static resources, the correct format HTTP/1.1 200 OK is used.

Expected behavior:
According to RFC 9110, the reason-phrase in the status line is optional. However, many HTTP clients, proxies, and test suites expect the traditional, human-readable reason-phrase to be present for compatibility. For best interoperability and consistency, it would be preferable if all Zephyr HTTP responses included the reason-phrase.

### Regression

- [ ] This is a regression.

### Steps to reproduce

This can be easily seen on Wireshark capture of HTTP transaction.

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

-OS: Linux
Version: 3.7

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kfirous**
Add support for including HTTP reason phrases in chunked transfer-encoded responses

Fixes #99722

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
Thanks for the PR! Generally no objections, but since reason phrase is optional in the response, I think we should make this feature configurable with Kconfig? It seems to be quite costly memory-wise. Compared to main, on `nucleo_h723zg` it consumes extra ~2,5 kB of FLASH.

File: subsys/net/lib/http/http_server_http1.c [hunk 1]
```diff
@@ -196,9 +196,148 @@ static int handle_http1_static_resource(
 	ret; })
 
 #define RESPONSE_TEMPLATE_DYNAMIC_PART1                                                            \
-	"HTTP/1.1 %d\r\n"                                                                          \
+	"HTTP/1.1 %d %s\r\n"                                                                       \
 	"Transfer-Encoding: chunked\r\n"
 
+static const char *http_status_reason_phrase(enum http_status status)
```
Comment (carlescufi) [inline subsys/net/lib/http/http_server_http1.c]:
```suggestion
static const char *http_status_str(enum http_status status)
```

File: subsys/net/lib/http/http_server_http1.c [hunk 2]
```diff
@@ -219,7 +358,8 @@ static int http1_send_headers(struct http_client_ctx *client, enum http_status s
 	}
 
 	/* Send response code and transfer encoding */
-	snprintk(http_response, sizeof(http_response), RESPONSE_TEMPLATE_DYNAMIC_PART1, status);
+	snprintk(http_response, sizeof(http_response), RESPONSE_TEMPLATE_DYNAMIC_PART1, status,
+		 http_status_reason_phrase(status));
```
Comment (carlescufi) [inline subsys/net/lib/http/http_server_http1.c]:
```suggestion
		 http_status_str(status));
```

File: subsys/net/lib/http/http_server_http1.c (hunk 1 above)
Comment (kfirous) [reply subsys/net/lib/http/http_server_http1.c]: Thanks! Fixed

File: subsys/net/lib/http/http_server_http1.c (hunk 2 above)
Comment (kfirous) [reply subsys/net/lib/http/http_server_http1.c]: Thanks! Fixed

File: subsys/net/lib/http/Kconfig [hunk 3]
```diff
@@ -231,6 +231,16 @@ config HTTP_SERVER_STATIC_FS_RESPONSE_SIZE
 	  Please note that it is allocated on the stack of the HTTP server thread,
 	  so CONFIG_HTTP_SERVER_STACK_SIZE has to be sufficiently large.
 
+config HTTP_SERVER_COMPLETE_STATUS_PHRASES
+	bool "Complete HTTP status reason phrases"
+	default n
```
Comment (rlubos) [inline subsys/net/lib/http/Kconfig]: Please remove `default n`, it's implicit.

File: subsys/net/lib/http/http_server_http1.c [hunk 4]
```diff
@@ -196,16 +196,45 @@ static int handle_http1_static_resource(
...
+}
+
 static int http1_send_headers(struct http_client_ctx *client, enum http_status status,
 			      const struct http_header *headers, size_t header_count,
 			      struct http_resource_detail_dynamic *dynamic_detail)
 {
 	int ret;
 	bool content_type_sent = false;
-	char http_response[MAX(sizeof(RESPONSE_TEMPLATE_DYNAMIC_PART1) + sizeof("xxx"),
+	char http_response[MAX(sizeof(RESPONSE_TEMPLATE_DYNAMIC_PART1) + 64,
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_http1.c]: We try to avoid having magic constants that do not really explain the purpose of the value.
So here I would suggest something like this
```
#if defined(CONFIG_HTTP_SERVER_COMPLETE_STATUS_PHRASES)
#define MAX_STATUS_STR_LEN 64
#else
#define MAX_STATUS_STR_LEN 0
#endif

char http_response[MAX(sizeof(RESPONSE_TEMPLATE_DYNAMIC_PART1) + sizeof("xxx") +
                   MAX_STATUS_STR_LEN),
```
so I would leave the sizeof() that tries to tell that the status code is 3 chars long.

File: subsys/net/lib/http/http_server_http1.c [hunk 5]
```diff
@@ -196,16 +196,45 @@ static int handle_http1_static_resource(
 	ret; })
 
 #define RESPONSE_TEMPLATE_DYNAMIC_PART1                                                            \
-	"HTTP/1.1 %d\r\n"                                                                          \
+	"HTTP/1.1 %d %s\r\n"                                                                       \
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_http1.c]: In order to avoid confusion in the HTTP parser that receives this data, I would not place empty char after the status code (happens if `CONFIG_HTTP_SERVER_COMPLETE_STATUS_PHRASES` is not set).
So better would be
```
"HTTP/1.1 %d%s%s\r\n"
```

File: subsys/net/lib/http/http_server_http1.c (hunk 4 above)
Comment (rlubos) [inline subsys/net/lib/http/http_server_http1.c]: No status string is close to 64 bytes, no need to allocate that much. I'd suggest to define a symbol that represents the maximum length of a status string, and just add it to the response length, something like:
```c
#if defined(CONFIG_HTTP_SERVER_COMPLETE_STATUS_PHRASES)
#define REASON_PHRASE_MAX_LENGTH sizeof("Internal Server Error")
#else
#define REASON_PHRASE_MAX_LENGTH 0
#endif   
```

File: subsys/net/lib/http/http_server_http1.c [hunk 6]
```diff
@@ -219,7 +248,8 @@ static int http1_send_headers(struct http_client_ctx *client, enum http_status s
 	}
 
 	/* Send response code and transfer encoding */
-	snprintk(http_response, sizeof(http_response), RESPONSE_TEMPLATE_DYNAMIC_PART1, status);
+	snprintk(http_response, sizeof(http_response), RESPONSE_TEMPLATE_DYNAMIC_PART1, status,
+		 http_status_str(status));
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_http1.c:260]: and then here add extra space if `CONFIG_HTTP_SERVER_COMPLETE_STATUS_PHRASES` is enabled like this
```
IS_ENABLED(CONFIG_HTTP_SERVER_COMPLETE_STATUS_PHRASES) ? " " : "", http_status_str(status));
```

File: subsys/net/lib/http/Kconfig (hunk 3 above)
Comment (jukkar) [inline subsys/net/lib/http/Kconfig]: The "default n" can be omitted because options are "n" by default so we do not add these lines to Kconfig files.

File: subsys/net/lib/http/http_server_http1.c (hunk 5 above)
Comment (rlubos) [inline subsys/net/lib/http/http_server_http1.c]: So now we're adding a dummy space after the status code if the reason phrases are disabled, that doesn't sound right. 

I see two options here, either replace the space inbetween code and string with `%s` and let the `snprintk()` below specify a space or an empty string based on configuration, or simply have two templates and use them in `snprintk()` conditionally.

File: subsys/net/lib/http/http_server_http1.c (hunk 6 above)
Comment (kfirous) [reply subsys/net/lib/http/http_server_http1.c:260]: Done

File: subsys/net/lib/http/Kconfig (hunk 3 above)
Comment (kfirous) [reply subsys/net/lib/http/Kconfig]: Removed

File: subsys/net/lib/http/http_server_http1.c (hunk 5 above)
Comment (kfirous) [reply subsys/net/lib/http/http_server_http1.c]: Went for the first option as @jukkar suggested.

**Review by rlubos — APPROVED** [review]
Thanks!

**Review by jukkar — APPROVED** [review]
