### PR TITLE
drivers/timer/cortex_m_systick: Avoid division by zero

### LINKED ISSUE #100040: timer: cortex_m_systick: Compilation error if CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME is defined
### Describe the bug

Timer cortex_m_systick fails to build if CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME is defined

Regression of commit b9a39a77d37e105043177c3b732daf7db661d5fb

### Regression

- [x] This is a regression.

### Steps to reproduce

west build -p -b qemu_cortex_m3 samples/hello_world -- -DCONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME=y

### Relevant log output

```shell
/home/user/projects/zephyrproject/zephyr/drivers/timer/cortex_m_systick.c:23:48: error: division by zero in #if
   23 | #define CYC_PER_TICK (z_clock_hw_cycles_per_sec/CONFIG_SYS_CLOCK_TICKS_PER_SEC)
      |                                                ^
/home/user/projects/zephyrproject/zephyr/drivers/timer/cortex_m_systick.c:33:20: note: in expansion of macro 'CYC_PER_TICK'
   33 | #if (COUNTER_MAX / CYC_PER_TICK) == 1
```

### Impact

Not sure

### Environment

v4.30 Release

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ydamigos**
Preprocessor evaluates CYC_PER_TICK as zero in condition `(COUNTER_MAX / CYC_PER_TICK) == 1` when
CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME is defined.

This commit skips the check when
CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME is defined.

Fixes: #100040

### CODE REVIEW

File: drivers/timer/cortex_m_systick.c [hunk 1]
```diff
@@ -30,9 +30,11 @@ extern unsigned int z_clock_hw_cycles_per_sec;
 #define MAX_TICKS ((_MAX_TICKS > 0) ? _MAX_TICKS : 1)
 #define MAX_CYCLES (MAX_TICKS * CYC_PER_TICK)
 
+#if !defined(CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME)
 #if (COUNTER_MAX / CYC_PER_TICK) == 1
 #pragma message("tickless does nothing as CONFIG_SYS_CLOCK_TICKS_PER_SEC too low")
 #endif
+#endif
```
Comment (mathieuchopstm) [inline drivers/timer/cortex_m_systick.c]: Maybe the check could be added to the existing #ifdef block? i.e.:

```c
#if defined(CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME)
extern unsigned int z_clock_hw_cycles_per_sec;
#define CYC_PER_TICK (z_clock_hw_cycles_per_sec/CONFIG_SYS_CLOCK_TICKS_PER_SEC)
#else
#define CYC_PER_TICK (CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC/CONFIG_SYS_CLOCK_TICKS_PER_SEC)
#if (COUNTER_MAX / CYC_PER_TICK) == 1
#pragma message("tickless does nothing as CONFIG_SYS_CLOCK_TICKS_PER_SEC too low")
#endif
#endif
```

Comment (ydamigos) [reply drivers/timer/cortex_m_systick.c]: Done

**Review by mathieuchopstm — DISMISSED** [review]

**Review by wearyzen — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Review by hakehuang — DISMISSED** [review]

**Review by mathieuchopstm — APPROVED** [review]

**Review by hakehuang — APPROVED** [review]

**Review by teburd — APPROVED** [review]
