### PR TITLE
drivers: can: mcux_flexcan: Update to support rt1170

### LINKED ISSUE #37691: samples/subsys/canbus/isotp/sample.subsys.canbus.isotp fails to build on mimxrt1170_evk_cm7
After the SDK 2.10.0 update for NXP HAL we now get:

`./scripts/twister -s samples/subsys/canbus/isotp/sample.subsys.canbus.isotp -p mimxrt1170_evk_cm7`

gets:

```
/home/galak/git/zephyr/drivers/can/can_mcux_flexcan.c: In function 'mcux_flexcan_init':
/home/galak/git/zephyr/drivers/can/can_mcux_flexcan.c:727:10: error: passing argument 3 of 'FLEXCAN_TransferCreateHandle' from incompatible pointer type [-Werror=incompatible-pointer-types]
  727 |          mcux_flexcan_transfer_callback, data);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          |
      |          void (*)(CAN_Type *, flexcan_handle_t *, status_t,  uint32_t,  void *) {aka void (*)(CAN_Type *, struct _flexcan_handle *, int,  unsigned int,  void *)}
In file included from /home/galak/git/zephyr/drivers/can/can_mcux_flexcan.c:15:
/home/galak/git/modules/hal/nxp/mcux/drivers/imx/./fsl_flexcan.h:2034:63: note: expected 'flexcan_transfer_callback_t' {aka 'void (*)(CAN_Type *, struct _flexcan_handle *, int,  long long unsigned int,  void *)'} but argument is of type 'void (*)(CAN_Type *, flexcan_handle_t *, status_t,  uint32_t,  void *)' {aka 'void (*)(CAN_Type *, struct _flexcan_handle *, int,  unsigned int,  void *)'}
 2034 |                                   flexcan_transfer_callback_t callback,
      |   
```

### PR DESCRIPTION
**Pull request by dleach02**
The RT1170 platform adjusted the result parameter in the callback
function to be a uint64_t. The adjustment is to conditionally change
the callback definition and then cast the result value to a size that
fits the reported values across the various SOCs.

With error results, cast result to uint64_t and modified the called
function to print a uint64_t value.

With the RX/TX status, result is a MB value that doesn't exceed 64
so the result value is cast down to a uint32_t.

Fixes #37691

Signed-off-by: David Leach <david.leach@nxp.com>

### CODE REVIEW

File: drivers/can/can_mcux_flexcan.c [hunk 1]
```diff
@@ -643,32 +643,43 @@ static inline void mcux_flexcan_transfer_rx_idle(const struct device *dev,
 	}
 }
 
+#if (defined(FSL_FEATURE_FLEXCAN_HAS_PN_MODE) && FSL_FEATURE_FLEXCAN_HAS_PN_MODE) || \
```
Comment (CristXu) [inline drivers/can/can_mcux_flexcan.c:646]: Maybe we can use the MACRO from SDK directly, like this: 
static **FLEXCAN_CALLBACK(mcux_flexcan_transfer_callback)**
and this macro is expand to:
**_#if (defined(FSL_FEATURE_FLEXCAN_HAS_PN_MODE) && FSL_FEATURE_FLEXCAN_HAS_PN_MODE) || \
    (defined(FSL_FEATURE_FLEXCAN_HAS_MEMORY_ERROR_CONTROL) && FSL_FEATURE_FLEXCAN_HAS_MEMORY_ERROR_CONTROL)
#define FLEXCAN_CALLBACK(x) \
    void(x)(CAN_Type * base, flexcan_handle_t * handle, status_t status, uint64_t result, void *userData)
typedef void (*flexcan_transfer_callback_t)(
    CAN_Type *base, flexcan_handle_t *handle, status_t status, uint64_t result, void *userData);
#else
#define FLEXCAN_CALLBACK(x) \
    void(x)(CAN_Type * base, flexcan_handle_t * handle, status_t status, uint32_t result, void *userData)
typedef void (*flexcan_transfer_callback_t)(
    CAN_Type *base, flexcan_handle_t *handle, status_t status, uint32_t result, void *userData);
#endif_**

Comment (dleach02) [reply drivers/can/can_mcux_flexcan.c:646]: Okay. I missed that.

Comment (dleach02) [reply drivers/can/can_mcux_flexcan.c]: done

**Review by hakehuang — APPROVED** [review]
Test PASS on my board

**Review by CristXu — APPROVED** [review]
