### PR TITLE
drivers: timer: reduce max cycles of riscv machine timer

### LINKED ISSUE #31985: riscv: Long execution time when TICKLESS_KERNEL=y
**Describe the bug**
Running a CPU bound test on RISC-V appears to take almost 30 times
longer when `TICKLESS_KERNEL=y` compared to `TICKLESS_KERNEL=n`.

`crypto.tinycrypt` test case on `qemu_riscv32` takes 142 s or 5 s depending
on `TICKLESS_KERNEL`. Similar for `tests/lib/heap`.

**To Reproduce**
```
$ twister --platform qemu_riscv32 -v -T tests/crypto/tinycrypt -x=CONFIG_TICKLESS_KERNEL=n
INFO    - 1/1 qemu_riscv32              tests/crypto/tinycrypt/crypto.tinycrypt            PASSED (qemu 5.061s)

$ twister --platform qemu_riscv32 -v -T tests/crypto/tinycrypt -x=CONFIG_TICKLESS_KERNEL=y
INFO    - 1/1 qemu_riscv32              tests/crypto/tinycrypt/crypto.tinycrypt            PASSED (qemu 142.436s)
```

Both tests use the same QEMU command line.

**Expected behavior**
It was expected that the two runs above have comparable execution times. Since
this is an emulation the host computer time may not be directly related to the
target system time. However, the difference is rather large.

For reference, doing the same with the `--platform qemu_cortex_m3` gives 6 s
and 5 s.

**Impact**
`TICKLESS_KERNEL` is enabled by default on RISC-V boards using the Machine Timer.

**Environment (please complete the following information):**
- Toolchain: Zephyr SDK 0.12.1
- Zephyr version: v2.5.0-rc2-46-g4d4a636555cd

**Additional context**
The behavior has also been observed when running on RISC-V hardware
(board not in tree).

Would be interesting to know if it reproduces on other RISC-V boards.

### PR DESCRIPTION
**Pull request by katsuster**
If next_timeout() returns INT_MAX and pass it to
z_clock_set_timeout(), and machine goes to freeze or slow down.
Bad scenario as follows:

- If an argument int32_t ticks is set large value 0xffffffff,
    ticks = MAX(MIN(ticks - 1, (int32_t)MAX_TICKS), 0);
  replaces it into MAX_TICKS.
- uint32_t cyc will be set near by 0xffffffff
  (this is 0xfffd7280 in 100 ticks per second).
- Add adjustment to cyc, adjustment max value is MAX_CYC.
  (cyc = 0xffff14fd)
- Over 0x80000000 value of uint32_t is considered as negative
  value of int32_t.
    if ((int32_t)(cyc + last_count - now) < MIN_DELAY)
  This condition is always true.
- Because cyc += CYC_PER_TICK will get overflow, driver sets mtimecmp
  near value of current mtime.
  (cyc = 0x00007fc0)
- Next timer interrupt will happen soon after return from interrupt
  handler.
- By repeating these events, machine cannot go to next instruction,
  and it's going to freeze or slow down.

Fixed #32711

### CODE REVIEW

File: drivers/timer/riscv_machine_timer.c [hunk 1]
```diff
@@ -10,7 +10,7 @@
 
 #define CYC_PER_TICK ((uint32_t)((uint64_t)sys_clock_hw_cycles_per_sec()	\
 			      / (uint64_t)CONFIG_SYS_CLOCK_TICKS_PER_SEC))
-#define MAX_CYC 0xffffffffu
+#define MAX_CYC 0x7fffffffu
```
Comment (andyross) [inline drivers/timer/riscv_machine_timer.c:13]: FWIW, as I read the code this was a signedness bug.  The tick argument to z_clock_set_timeout() is an int32_t, so the old value was -1.  I'd just use INT_MAX here, and let it be a signed value for clarity.  The "u" suffix isn't actually doing anything useful.

**Review by andyross — APPROVED** [review]
One nitpick if you want to change it, but looks fine.

File: drivers/timer/riscv_machine_timer.c (hunk 1 above)
Comment (katsuster) [reply drivers/timer/riscv_machine_timer.c]: Thanks for review. Indeed, I fixed it to INT_MAX.

**Review by ghost — APPROVED** [review]
