### PR TITLE
Bluetooth: Mesh: Fix build warning with Warray-bounds

### LINKED ISSUE #29634: Build error: (Bluetooth: Mesh: split prov.c into two separate modules #28457)
**Description**
When building New BT Mesh Provisioning  changes (Bluetooth: Mesh: split prov.c into two separate modules #28457)

**To Reproduce**
Compiled existing, previously working provisioning app.

**Expected behavior**
Clean compilation 

**Impact**
Unsure potential showstopper as still assessing impact

**Logs and console output**
In file included from c:\gnu_arm_embedded\arm-none-eabi\include\string.h:180,
                 from ../../include/bluetooth/bluetooth.h:21,
                 from ../zephyrNew/subsys/bluetooth/mesh/prov.c:17:
../zephyrNew/subsys/bluetooth/mesh/prov.c: In function 'bt_mesh_prov_reset_state':
../zephyrNew/subsys/bluetooth/mesh/prov.c:61:2: warning: '__builtin_memset' offset [52, 292] from the object at 'bt_mesh_prov_link' is out of the bounds of referenced subobject 'dhkey' with type 'uint8_t[32]' {aka 'unsigned char[32]'} at offset 19 [-Warray-bounds]
   61 |  memset(&bt_mesh_prov_link.dhkey, 0,

**Environment (please complete the following information):**
 - OS: Windows 10
 - GNU Arm Embedded Toolchain: Version 9-2020-q2-update
 - C2.4.99 just merged latest changes

### PR DESCRIPTION
**Pull request by LingaoM**
../zephyrNew/subsys/bluetooth/mesh/prov.c: In function
'bt_mesh_prov_reset_state': ../zephyrNew/subsys/bluetooth/mesh/prov.c:61:2:
warning: '__builtin_memset' offset [52, 292] from the object at
'bt_mesh_prov_link' is out of the bounds of referenced subobject 'dhkey'
with type 'uint8_t[32]' {aka 'unsigned char[32]'} at offset 19 [-Warray-bounds]
61 | memset(&bt_mesh_prov_link.dhkey, 0,

Fixes: #29634

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

### CODE REVIEW

**Comment by LingaoM** [comment]
@WilliamGFish Please confirm whether this PR can solve your problem?

File: subsys/bluetooth/mesh/prov.c [hunk 1]
```diff
@@ -58,8 +59,8 @@ int bt_mesh_prov_reset_state(void (*func)(const uint8_t key[64]))
 		bt_mesh_attention(NULL, 0);
 	}
 
-	memset(&bt_mesh_prov_link.dhkey, 0,
-	       sizeof(bt_mesh_prov_link) - offsetof(struct bt_mesh_prov_link, dhkey));
+	(void)memset((char *)&bt_mesh_prov_link + offset, 0,
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/prov.c:62]: Could you please cast to (uint8_t *) here instead of `char *`? `char` is technically of undefined width.

Comment (LingaoM) [reply subsys/bluetooth/mesh/prov.c]: Done.

**Review by trond-snekvik — APPROVED** [review]

File: subsys/bluetooth/mesh/prov.c [hunk 2]
```diff
@@ -50,6 +50,7 @@ int bt_mesh_prov_reset_state(void (*func)(const uint8_t key[64]))
 {
 	int err;
 	static struct bt_pub_key_cb pub_key_cb;
+	const int offset = offsetof(struct bt_mesh_prov_link, dhkey);
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/prov.c:53]: IIRC the official return type of `offsetof()` is `size_t` and not `int`

File: subsys/bluetooth/mesh/prov.c [hunk 3]
```diff
@@ -58,8 +59,8 @@ int bt_mesh_prov_reset_state(void (*func)(const uint8_t key[64]))
 		bt_mesh_attention(NULL, 0);
 	}
 
-	memset(&bt_mesh_prov_link.dhkey, 0,
-	       sizeof(bt_mesh_prov_link) - offsetof(struct bt_mesh_prov_link, dhkey));
+	(void)memset((uint8_t *)&bt_mesh_prov_link + offset, 0,
+	       sizeof(bt_mesh_prov_link) - offset);
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/prov.c:63]: It looks like (at least in the GitHub web UI) that the split line is not correctly aligned right after `memset(` on the first line.

**Review by jhedberg — CHANGES_REQUESTED** [review]
A couple of really minor style comments, otherwise this looks good to me

File: subsys/bluetooth/mesh/prov.c (hunk 3 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/prov.c]: Done.

**Review by jhedberg — APPROVED** [review]
