### PR TITLE
gpio: gpio_intel_apl: fix if condition leading to dead code

### LINKED ISSUE #13880: [Coverity CID :190933]Control flow issues in /drivers/gpio/gpio_intel_apl.c
Static code scan issues seen in File: /drivers/gpio/gpio_intel_apl.c
 Category: Control flow issues
 Function: gpio_intel_apl_config
 Component: Drivers
 CID: 190933
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by dcpleung**
GPIO_INT_ACTIVE_LOW is 0 which means it cannot be simply AND-ed.
So fix the condition.

Fixes #13880

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

File: drivers/gpio/gpio_intel_apl.c [hunk 1]
```diff
@@ -243,7 +243,7 @@ static int gpio_intel_apl_config(struct device *dev, int access_op,
 	/* setup interrupt if desired */
 	if (flags & GPIO_INT) {
 		/* invert signal for interrupt controller */
-		if (flags & GPIO_INT_ACTIVE_LOW) {
+		if ((flags & GPIO_INT_ACTIVE_LOW) == GPIO_INT_ACTIVE_LOW) {
```
Comment (andyross) [inline drivers/gpio/gpio_intel_apl.c]: So... `if(flags & 0) == 0)` ...?   That doesn't seem right either. :)

Surely there should be separate macros for the "GPIO_INT_ACTIVITY" field mask vs. the "LOW/HI" enumerants, no?

**Review by andyross — CHANGES_REQUESTED** [review]
Something still seems mixed up

File: drivers/gpio/gpio_intel_apl.c (hunk 1 above)
Comment (dcpleung) [reply drivers/gpio/gpio_intel_apl.c]: Ah... shouldn't have written code during meetings... :P

Fixed it in new push.

File: drivers/gpio/gpio_intel_apl.c [hunk 2]
```diff
@@ -243,7 +243,7 @@ static int gpio_intel_apl_config(struct device *dev, int access_op,
 	/* setup interrupt if desired */
 	if (flags & GPIO_INT) {
 		/* invert signal for interrupt controller */
-		if (flags & GPIO_INT_ACTIVE_LOW) {
+		if (!(flags & GPIO_INT_ACTIVE_HIGH)) {
```
Comment (galak) [inline drivers/gpio/gpio_intel_apl.c]: Can we make this a bit more explicit:

`((flags & GPIO_INT_ACTIVE_HIGH)) == GPIO_INT_ACTIVE_LOW) {`

Comment (andyross) [reply drivers/gpio/gpio_intel_apl.c]: If we do it that way, the "proper" way to do it would be to have a GPIO_INT_ACTIVE_MASK macro to select the field, which then gets tested against _LOW and _HIGH values.

But it's a 1-bit boolean, so I think having a single name for the bit is fine.  If anything I think the bug in our API is that GPIO_INT_ACTIVE_LOW exists at all.  But API cleanup is out of scope now I'm sure.

**Review by andyross — APPROVED** [review]

File: drivers/gpio/gpio_intel_apl.c (hunk 2 above)
Comment (galak) [reply drivers/gpio/gpio_intel_apl.c]: agreed, post 1.14, I'm thinking we should have a set of macro's since I've seen someone coverity issues like this one.

Comment (dcpleung) [reply drivers/gpio/gpio_intel_apl.c]: Pushed a new update for this.

I remember there was a PR about creating a trigger mask. I can't seem to find it now.

**Review by galak — APPROVED** [review]

File: drivers/gpio/gpio_intel_apl.c (hunk 2 above)
Comment (galak) [reply drivers/gpio/gpio_intel_apl.c]: > I remember there was a PR about creating a trigger mask. I can't seem to find it now.

I think in the future we should have helper functions like:

`is_gpio_active_high(x)`
`is_gpio_active_low(x)`

and remove the guess work from the drivers.

**Review by tyrantlizard77 — APPROVED** [review]
