### PR TITLE
drivers: udc: add opaque pointer to store upper layer private data

### LINKED ISSUE #74291: Multiple USB contexts for same device lead to bus faults
**Describe the bug**
USBD shell module uses `zephyr_udc0` node
https://github.com/zephyrproject-rtos/zephyr/blob/d45605e6a3dfe68e43207d15e3bfc003cbfaa72f/subsys/usb/device_next/usbd_shell.c#L48-L50
and so do all USB samples
https://github.com/zephyrproject-rtos/zephyr/blob/d45605e6a3dfe68e43207d15e3bfc003cbfaa72f/samples/subsys/usb/common/sample_usbd_init.c#L19-L21

This leads to multiple issues, like handling SETUP packets twice in:
https://github.com/zephyrproject-rtos/zephyr/blob/d45605e6a3dfe68e43207d15e3bfc003cbfaa72f/subsys/usb/device_next/usbd_core.c#L193-L199

Because the first SETUP handler will free the buffer, this leads to BUS FAULT on second time the handler is called.

**To Reproduce**
1. CONF_FILE=usbd_next_prj.conf west build --pristine -b nrf54h20dk/nrf54h20/cpuapp -d build-usb-cdc-acm-54h20/ ~/zephyrproject/zephyr/samples/subsys/usb/cdc_acm -- -DCONFIG_SHELL=y -DCONFIG_USBD_SHELL=y
2. cd build-usb-cdc-acm-54h20
3. west flash
4. Connect nRF54H20 USB to host and observe BUS FAULT on UART (J-Link on debugger USB)

**Expected behavior**
Build should fail if there is more than 1 context for the same udc device.

**Impact**
Wasted time trying to understand what is going on (multiple context pointing to same device).

**Logs and console output**
```
*** Booting Zephyr OS build v3.6.0-6257-gd45605e6a3df ***
[00:00:00.022,014] <inf> LD_DVFS_LIB: Trim ABB for default voltage.
[00:00:00.022,018] <inf> LD_DVFS_LIB: Waiting for backend init
[00:00:00.022,040] <inf> NRFS_BACKEND: Bound to sysctrl.
[00:00:00.022,054] <inf> LD_DVFS_LIB: nrfs_dvfs_init
[00:00:00.022,058] <inf> LD_DVFS_LIB: nrfs_dvfs_init_prepare_request
[00:00:00.022,131] <inf> cdc_acm_echo: USB device support enabled
[00:00:00.022,135] <inf> cdc_acm_echo: Wait for DTR
[00:00:00.022,245] <inf> LD_DVFS_LIB: nrfs_dvfs_evt_handler
[00:00:00.022,249] <inf> LD_DVFS_LIB: DVFS handler EVT_INIT_DONE
[00:00:00.022,257] <inf> LD_DVFS_LIB: DVFS handler EVT_INIT_DONE handled
[00:00:00.022,266] <inf> LD_DVFS_LIB: DVFS init done.
[00:00:00.022,570] <inf> cdc_acm_echo: USBD message: VBUS ready
[00:00:00.054,340] <inf> cdc_acm_echo: USBD message: Device suspended
[00:00:00.220,251] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:00.600,531] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:00.674,722] <err> os: ***** BUS FAULT *****
[00:00:00.674,727] <err> os:   Precise data bus error
[00:00:00.674,729] <err> os:   BFAR Address: 0x0
[00:00:00.674,737] <err> os: r0/a1:  0x2f011b28  r1/a2:  0x2f017778  r2/a3:  0x00000000
[00:00:00.674,742] <err> os: r3/a4:  0x00000008 r12/ip:  0x2f0154fc r14/lr:  0x0e0ad411
[00:00:00.674,744] <err> os:  xpsr:  0x21000000
[00:00:00.674,750] <err> os: Faulting instruction address (r15/pc): 0x0e0ac7da
[00:00:00.674,761] <err> os: >>> ZEPHYR FATAL ERROR 25: Unknown error on CPU 0
[00:00:00.674,772] <err> os: Current thread: 0x2f012640 (usbd)
[00:00:00.798,732] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.5
 - Commit SHA or Version used: d45605e6a3dfe68e43207d15e3bfc003cbfaa72f

**Additional context**
The same runtime issue happens when `tests/subsys/usb/device_next` is build with `build_all.conf` configuration.

### PR DESCRIPTION
**Pull request by jfischer-no**
Add an opaque pointer to store upper layer private data and initialize it with the USB device context during controller initialization. Use the pointer in event processing to get the correct context.

Fixes: #74291

### CODE REVIEW

File: include/zephyr/drivers/usb/udc.h [hunk 1]
```diff
@@ -347,12 +351,13 @@ static inline bool udc_is_suspended(const struct device *dev)
  *
  * @param[in] dev      Pointer to device struct of the driver instance
  * @param[in] event_cb Event callback from the higher layer (USB device stack)
+ * @param[in] ul_priv  Opaque pointer to upper layer private data
```
Comment (tmon-nordic) [inline include/zephyr/drivers/usb/udc.h:354]: It is somewhat inconsistent that the same thing is referred first as "higher layer" and then as "upper layer".

I would also name it `event_ctx` or `event_cb_ctx` to make it clear that `event_cb` is closely related to `ul_priv`.

Comment (jfischer-no) [reply include/zephyr/drivers/usb/udc.h]: Indeed, renamed it to event_ctx.

File: include/zephyr/drivers/usb/udc.h [hunk 2]
```diff
@@ -169,6 +169,8 @@ struct udc_event {
 	};
 	/** Pointer to device struct */
 	const struct device *dev;
+	/** Opaque pointer to higher layer context */
+	const void *ctx;
```
Comment (tmon-nordic) [inline include/zephyr/drivers/usb/udc.h:173]: Is this necessary here? Why not grab the pointer from `dev->data->event_ctx`?

Comment (jfischer-no) [reply include/zephyr/drivers/usb/udc.h:173]: But then it needs to be abstracted to something like udc_get_event_context(). If it is part of the event, it is easier to handle and we are not introducing a new interface.

Comment (tmon-nordic) [reply include/zephyr/drivers/usb/udc.h:173]: Does it need to be abstracted? Can't the `event_cb` simply take the `event_ctx` as extra parameter?

Comment (jfischer-no) [reply include/zephyr/drivers/usb/udc.h]: No, it can only put a message into a queue.  I added udc_get_event_ctx(), seems to be more performant.

**Review by tmon-nordic — APPROVED** [review]

**Review by nashif — APPROVED** [review]
