### PR TITLE
drivers: can: only copy frame data for non-RTR frames

### LINKED ISSUE #57002: can: incorrect RTR flag handling in incoming frames
Hello @henrikbrixandersen, @alexanderwachter, @martinjaeger 

I've just discovered that almost all CAN bus drivers assume that an incoming CAN frame with the RTR flag has a valid payload and copies data from FIFOs/registers up onto the stack.

Unfortunately this behavior is incorrect, since RTR mean that some data should be transferred FROM the node, not TO.

Thus, trying to copy CAN's frame data in the case of RTR is nothing but a waste of resources at best, or a security problem at worst ("disclose sensitive data"), since the payload from some old frame will be copied almost everywhere and/or machine check can be raised on some odd hardware.

Regards
Andrey VOLKOV
Linux Socketcan co-founder

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Only copy frame data for non-RTR frames as RTR frames do not carry any data.

Fixes: #57002

### CODE REVIEW

**Comment by manuargue** [comment]
> All driver/test changes were tested _except_ for the changes to the following drivers, for which I do not have access to hardware. Any help in verifying these changes would be appreciated:
> 
> * NXP S32 (@manuargue)

hi @henrikbrixandersen, thanks for the fixes. Are there any particular tests that should be run to verify these changes?

**Comment by henrikbrixandersen** [comment]
> hi @henrikbrixandersen, thanks for the fixes. Are there any particular tests that should be run to verify these changes?

Hi! Running the `tests/drivers/can/api` test suite with hardware-in-the-loop should be sufficient.

**Review by manuargue — APPROVED** [review]
CAN tests passing on `mr_canhubk3` (mcux_flexcan.c) and `s32z270dc2_rtu0_r52` (nxp_s32_canxl.c)
Changes LGTM, approving for the NXP S32 parts

**Comment by henrikbrixandersen** [comment]
> CAN tests passing on `mr_canhubk3` (mcux_flexcan.c) and `s32z270dc2_rtu0_r52` (nxp_s32_canxl.c)
> 
> Changes LGTM, approving for the NXP S32 parts

Thanks!

File: drivers/can/can_mcp251xfd.c [hunk 1]
```diff
@@ -30,7 +30,7 @@ LOG_MODULE_REGISTER(can_mcp251xfd, CONFIG_CAN_LOG_LEVEL);
 static void mcp251xfd_canframe_to_txobj(const struct can_frame *src, int mailbox_idx,
 					struct mcp251xfd_txobj *dst)
 {
-	dst->flags = 0;
+	memset(dst, 0, sizeof(*dst));
```
Comment (talih0) [inline drivers/can/can_mcp251xfd.c:33]: The device will only the transmit the payload set by the DLC. I don't think we need zero to initialize the whole frame.

**Review by aaillet — APPROVED** [review]
`tests/drivers/can/api` runs fine on H3ULCB
R-Car driver changes LGTM

File: drivers/can/can_mcp251xfd.c [hunk 2]
```diff
@@ -208,7 +208,7 @@ static int mcp251xfd_fifo_write(const struct device *dev, int mailbox_idx,
 
 static void mcp251xfd_rxobj_to_canframe(struct mcp251xfd_rxobj *src, struct can_frame *dst)
 {
-	memset(dst, 0, offsetof(struct can_frame, data));
+	memset(dst, 0, sizeof(*dst));
```
Comment (talih0) [inline drivers/can/can_mcp251xfd.c:211]: I'm not sure if we need this one either.. Imo the user shouldn't try to read the data outside the DLC.

Is the concern that RTR frames have a non-zero DLC? Maybe we should drop these invalid packets in the driver?

Comment (henrikbrixandersen) [reply drivers/can/can_mcp251xfd.c:211]: The DLC of an RTR frame tells the recipient how much data to reply with. Please see the linked issue for the bug report.

Comment (talih0) [reply drivers/can/can_mcp251xfd.c:211]: But in this case, if the RTR flag is set the user should know that the data is invalid. I don't see why we need to zero out data bytes.

File: drivers/can/can_mcp251xfd.c (hunk 1 above)
Comment (talih0) [reply drivers/can/can_mcp251xfd.c:33]: Could we then just zero out upto the data field? (the way I did on the receiver side)

Comment (henrikbrixandersen) [reply drivers/can/can_mcp251xfd.c:33]: No. The intent is to not leak uninitialized data from the ISR stack/kernel thread stack to the application/user mode thread - and vice versa.

File: drivers/can/can_mcp251xfd.c (hunk 2 above)
Comment (henrikbrixandersen) [reply drivers/can/can_mcp251xfd.c:211]: Otherwise we can leak uninitialized stack contents to the application/user mode thread.

**Review by jhedberg — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

File: drivers/can/can_mcp251xfd.c (hunk 1 above)
Comment (talih0) [reply drivers/can/can_mcp251xfd.c:33]: For the transmit side, we should modify the spi transfer length so that it doesn't include the data buffer when RTR flag is set. This way we don't have to zero initialize the data. If you want, I can send in a separate patch for this so that you don't have to get everyone to approve again.

Comment (talih0) [reply drivers/can/can_mcp251xfd.c:33]: Btw I tested your patch on the mikroe mcp2518fd click and API test passes fine. (Although the receive rtr tests are skipped now because CAN_FILTER_RTR is not supported). I'll work on a patch to add this.

**Review by martinjaeger — APPROVED** [review]

File: drivers/can/can_mcp251xfd.c (hunk 1 above)
Comment (henrikbrixandersen) [reply drivers/can/can_mcp251xfd.c:33]: > For the transmit side, we should modify the spi transfer length so that it doesn't include the data buffer when RTR flag is set. This way we don't have to zero initialize the data. If you want, I can send in a separate patch for this so that you don't have to get everyone to approve again.

@talih0 Yes, that sounds like a nice improvement. Please submit this as a separate PR and let's try to get that into v3.5.0 as well.
