### PR TITLE
net: telnet: Fix character mode handling

### LINKED ISSUE #34197: samples: telnet: Tab completion not working in telnet shell
**Describe the bug**
When connecting via telnet to the system shell, tab completion does not function.  Tab completion works fine on the standard UART shell.

**To Reproduce**
Build the telnet sample application, and attempt to interact with the console using tab completion.  Note that no commands are completed, and the tab is echoed locally with no effect.

**Expected behavior**
Commands should be auto-completed when tab is pressed.

**Impact**
Annoyance

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: host
 - GIT head

**Additional context**
The root of the problem is that Zephyr's telnet server doesn't understand raw mode.  All connections stay in line buffered mode, and if the telnet client is manually switched to raw character mode (`^]mode char`) no keypresses are registered by Zephyer except `\n` and `\r`.

### PR DESCRIPTION
**Pull request by rlubos**
If the telnet client operates in a character mode, it may send
individual characters in packets. Such packets were dropped in the
telnet shell backend instead of being process by the shell engine.

Fixes #34197

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

File: subsys/shell/shell_telnet.c [hunk 1]
```diff
@@ -196,14 +196,16 @@ static void telnet_recv(struct net_context *client,
 	}
 
 	len = net_pkt_remaining_data(pkt);
-	if (len < TELNET_MIN_MSG) {
-		LOG_DBG("Packet smaller than minimum length");
+	if (len == 0) {
```
Comment (jukkar) [inline subsys/shell/shell_telnet.c:199]: Will this ever happen, I mean in what case the length would be 0, did you see this in testing?

**Comment by madscientist159** [comment]
@rlubos Mostly works, but am getting an error (apparently non fatal) at every keypress:

`<err> net_pkt: Uncontiguous data cannot be linearized`

**Comment by jukkar** [comment]
> Mostly works, but am getting an error (apparently non fatal) at every keypress:

I saw these messages recently when debugging some other part of the system. In that case the reason was that the cursor was not set properly, IIRC cursor was pointing at the end of the msg, and the code was trying to read more data. Might not be the same case here.

File: subsys/shell/shell_telnet.c (hunk 1 above)
Comment (rlubos) [reply subsys/shell/shell_telnet.c:199]: Not really, more of a precaution from my side, if you think it's safe to remove such check I can do it.

**Comment by rlubos** [comment]
> @rlubos Mostly works, but am getting an error (apparently non fatal) at every keypress:
> 
> `<err> net_pkt: Uncontiguous data cannot be linearized`

What platform do you use? I've tested with qemu and native_posix and I could not reproduce this.

File: subsys/shell/shell_telnet.c (hunk 1 above)
Comment (jukkar) [reply subsys/shell/shell_telnet.c:199]: I checked the tcp code and the callback is not called if there is no data and connection is still up. So the length should never be 0 in this part of the code.

Comment (rlubos) [reply subsys/shell/shell_telnet.c]: Ok, I have removed the check.

**Review by jukkar — COMMENTED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

**Comment by madscientist159** [comment]
> What platform do you use? I've tested with qemu and native_posix and I could not reproduce this.

This is running on an FPGA with a LiteX Ethernet peripheral.  Connection is made from a Linux system with telnet, then switched into character mode via `[^ mode char`.

**Comment by rlubos** [comment]
@madscientist159 Did you observe the same error before this path? From what I see, this log is printed by `net_pkt_get_data()` which is called in `telnet_handle_command()`. In both cases (before and after this path), the telnet shell will only try to parse the command if more than 2 bytes were received, so I'm a bit confused why would it show up now and not before.

Unfortunately, I don't have the exact hardware to reproduce the issue so I'm theorizing a bit here. When I tested the char mode I noticed that the telnet client would send each character in an individual frame with 1 byte of application payload. That's what Zephyr received and in that case, according to the logic in `telnet_recv()`, it shouldn't even bother with parsing the commnad. So perhaps there's some issue with the driver you use, that it does not set up the packet correctly so that `net_pkt_remaining_data()` returns more data than there's actually available, so we end up in `net_pkt_get_data()` with only one byte available? net_pkt logic is quite complex stuff so it's hard to tell w/o the debugger...

**Review by carlescufi — APPROVED** [review]

**Comment by madscientist159** [comment]
@rlubos After a revup to the latest Zephyr which pulls in this patch I'm not seeing the warnings any more.  Thanks for the quick fix on the telnet issues!
