### PR TITLE
drivers: spi: stm32: fix h7 issue with spi_hold_on_cs

### LINKED ISSUE #86975: X-NUCLEO-WB05KN1 shield not seems to work on different nucleo boards
**Describe the bug**
A nucleo wb05kn1 shield is placed in Arduino header from Nucleo H743ZI2 and the peripheral_hr sample is build with the shield argument "x_nucleo_wb05kn1_spi". The sample does not work, it is stuck in bt_spi_open when trying to receive header. 

I have tried to add an overlay to the STM32H7 like the ones in the shield folder without any luck. 

I also tried to place shield on Nucleo F401RE with same result.
I also tried on nRF52840 DK and here it work as expected.

**To Reproduce**

1. Place shield on one of the following Nucleo boards
2. Build Bluetooth sample such as peripheral_hr with the shield argument
3. See error

**Expected behavior**
I would expect that it works just like on the nRF52840 DK

**Impact**
Showstopper

**Logs and console output**

**Environment (please complete the following information):**
OS: Linux
Toolchain: Zephyr SDK
Zephyr version: Tried both latest and Zephyr 3.7

**Additional context**
The overlay file I tried to add the STM32H7
```
 &spi1_sck_pa5 {
	/delete-property/ bias-pull-down;
	bias-pull-up;
};

&spi1_miso_pa6 {
	slew-rate = "high-speed";
};

&spi1_mosi_pb5 {
	slew-rate = "high-speed";
};

/ {
	chosen {
		zephyr,bt-c2h-uart = &usart3;
	};
};
```

### PR DESCRIPTION
**Pull request by gautierg-st**
STM32H7 spi_loopback test fails since the introduction of a test enabling SPI_HOLD_ON_CS.
This uncovered an issue where the SPI ISR is constantly called if the SPI is not disabled, even if the interrupt enable register is completely cleared.
A workaround is to disable the SPI IRQ at the NVIC level when SPI_HOLD_ON_CS is used.

### CODE REVIEW

**Comment by decsny** [comment]
I should mention by the way, that the test might run but is not actually testing the CS unless you enable it in the overlay for the platform and dedicate another loopback for the CS to a gpio. Otherwise it is just doing testing like the old normal loopback transfers which doesn't actually require a CS loopback, with the only difference is that flag being set in the spi_config. I am enabling it for example on https://github.com/zephyrproject-rtos/zephyr/pull/91381 for two NXP platforms.

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -1514,18 +1530,33 @@ static int spi_stm32_pm_action(const struct device *dev,
...
 {									\
 	IRQ_CONNECT(DT_INST_IRQN(id),					\
 		    DT_INST_IRQ(id, priority),				\
 		    spi_stm32_isr, DEVICE_DT_INST_GET(id), 0);		\
 	irq_enable(DT_INST_IRQN(id));					\
-}
+}									\
+	IF_ENABLED(CONFIG_SOC_SERIES_STM32H7X,				\
+(static void spi_stm32_irq_enable_func_##id(const struct device *dev)	\
+{									\
```
Comment (etienne-lms) [inline drivers/spi/spi_ll_stm32.c]: `ARG_UNUSED(dev)`? (seem to be missing also right above).
Or maybe simply remove argument `dev`.

**Comment by FRASTM** [comment]
fixes https://github.com/zephyrproject-rtos/zephyr/issues/86975

File: drivers/spi/spi_ll_stm32.h [hunk 2]
```diff
@@ -24,6 +24,10 @@ struct spi_stm32_config {
 	const struct pinctrl_dev_config *pcfg;
 #ifdef CONFIG_SPI_STM32_INTERRUPT
 	irq_config_func_t irq_config;
+#ifdef CONFIG_SOC_SERIES_STM32H7X
+	irq_config_func_t irq_config_enable;
+	irq_config_func_t irq_config_disable;
+#endif /* CONFIG_SOC_SERIES_STM32H7X */
```
Comment (mathieuchopstm) [inline drivers/spi/spi_ll_stm32.h]: AFAIU, the `irq_config` functions just exist to have a place where the `IRQ_CONNECT` can be placed. Storing the IRQn in the `config` and calling `irq_enable`/`irq_disable` directly would be simpler (and *I think* cheaper).

Comment (gautierg-st) [reply drivers/spi/spi_ll_stm32.h]: Done

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (gautierg-st) [reply drivers/spi/spi_ll_stm32.c]: Not necessary now that we directly `irq_enable/irq_disable` with the `irq_line` stored in config.

**Review by mathieuchopstm — APPROVED** [review]

**Review by etienne-lms — APPROVED** [review]

**Comment by HoZHel** [comment]
> fixes #86975

I tested the changes on Nucleo-H755ZI-Q with X-Nucleo_WB05KN1 (SPI communication), and still it doesn't work.
Have you already tested?

**Comment by HoZHel** [comment]
> > fixes #86975
> 
> I tested the changes on Nucleo-H755ZI-Q with X-Nucleo_WB05KN1 (SPI communication), and still it doesn't work. Have you already tested?

I confirm that it works fine. Sorry for the confusion. I guess there was a loose connection between the shield and Arduino pins which resulted in failure at
`if (k_sem_take(&sem_initialised, K_SECONDS(CONFIG_BT_SPI_BOOT_TIMEOUT_SEC)) < 0) { return -EIO; }`

**Review by HoZHel — APPROVED** [review]

**Review by erwango — APPROVED** [review]
