### PR TITLE
stm32f3_disco internal (die) temperature sensor

### LINKED ISSUE #50152: SMT32: incorrect internal temperature value
**Describe the bug**
 Fix the internal temperature sensor value (Die temp) incorrect when reading internal  temperature from ADC. 

This ticket is to fix the incorrect temperature sensor (Die temp) value in the ADC device-tree node for the stm32 series below:

- stm32U5
- stm32L1
- stm32L4
- stm32L0

Acquired values seems inconsistent and not compatible. Example for the stm32U5 (b_u585i_iot02a), here is the required configuration of the ADC and the die temp nodes:

	adc1: adc@42028000 {
			compatible = "st,stm32-adc";
			reg = <0x42028000 0x400>;
			clocks = <&rcc STM32_CLOCK_BUS_AHB2 0x00000400>;
			interrupts = <37 0>;
			status = "disabled";
			vref-mv = <3300>;
			#io-channel-cells = <1>;
			has-temp-channel;
			has-vref-channel;
			has-vbat-channel;
		};

	die_temp: dietemp {
		compatible = "st,stm32-temp-cal";
		ts-cal1-addr = <0x0BFA0710>;
		ts-cal2-addr = <0x0BFA0742>;
		ts-cal1-temp = <30>;
		ts-cal2-temp = <130>;
		ts-cal-vrefanalog = <3000>;
		ts-cal-resolution = <14>;
		io-channels = <&adc1 19>;
	};
On running sample we get: 

*** Booting Zephyr OS build v3.2.0-rc1-18-g687816ba42c9  ***
STM32 Die temperature sensor test
Current temperature: -173.3 �°C
Current temperature: -126.2 �°C
Current temperature: -128.2 �°C
Current temperature: -128.8 �°C
Current temperature: -128.8 �°C
Current temperature: -126.9 �°C
Current temperature: -126.2 �°C
Current temperature: -126.5 �°C
Current temperature: -126.9 �°C

**To Reproduce**
1. west build -p auto -b nucleo_wl55jc samples/sensor/stm32_temp_sensor/
2. west flash
3. see error

**Logs and console output**
see description

**Environment (please complete the following information):**
 - OS: linux
 - Toolchain Toolchain Zephry SDK 0.15.0
 - latest main

### PR DESCRIPTION
**Pull request by FRASTM**
Configures the ADC channel and common registers to give a correct die-temperature sensor value

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/50152

On the stm32F3 disco board, the VDD = VDDA = VREF+ = 3V   (cf MB1035)

Thanks to this PR the die temperature on the stm32f3_disco platform with samples/sensor/stm32_temp_sensor/ is measured at
Current temperature: 32.7 °C

Signed-off-by: Francois Ramu [francois.ramu@st.com](mailto:francois.ramu@st.com)

### CODE REVIEW

File: drivers/adc/adc_stm32.c [hunk 1]
```diff
@@ -1201,7 +1204,7 @@ static int adc_stm32_init(const struct device *dev)
 	defined(CONFIG_SOC_SERIES_STM32L5X) || \
 	defined(CONFIG_SOC_SERIES_STM32WBX) || \
 	defined(CONFIG_SOC_SERIES_STM32G0X) || \
-	defined(CONFIG_SOC_SERIES_STM32G4X) || \
+	defined(CONFIG_SOC_SERIPCLKES_STM32G4X) || \
```
Comment (erwango) [inline drivers/adc/adc_stm32.c:1207]: This looks like an edition issue

File: drivers/adc/adc_stm32.c [hunk 2]
```diff
@@ -1151,15 +1151,18 @@ static int adc_stm32_init(const struct device *dev)
...
 	defined(CONFIG_SOC_SERIES_STM32G0X) || \
 	defined(CONFIG_SOC_SERIES_STM32G4X) || \
 	defined(CONFIG_SOC_SERIES_STM32H7X)
 	LL_ADC_SetCommonClock(__LL_ADC_COMMON_INSTANCE(adc),
-			      LL_ADC_CLOCK_SYNC_PCLK_DIV4);
+			LL_ADC_CLOCK_SYNC_PCLK_DIV4);
+#elif defined(STM32F3X_ADC_V1_1)
+	LL_ADC_SetCommonClock(__LL_ADC_COMMON_INSTANCE(adc),
+			LL_ADC_CLOCK_SYNC_PCLK_DIV1);
+
```
Comment (erwango) [inline drivers/adc/adc_stm32.c:1165]: Remove this line

File: drivers/adc/adc_stm32.c [hunk 3]
```diff
@@ -1151,15 +1151,18 @@ static int adc_stm32_init(const struct device *dev)
...
 	defined(CONFIG_SOC_SERIES_STM32WBX) || \
 	defined(CONFIG_SOC_SERIES_STM32G0X) || \
 	defined(CONFIG_SOC_SERIES_STM32G4X) || \
 	defined(CONFIG_SOC_SERIES_STM32H7X)
 	LL_ADC_SetCommonClock(__LL_ADC_COMMON_INSTANCE(adc),
-			      LL_ADC_CLOCK_SYNC_PCLK_DIV4);
+			LL_ADC_CLOCK_SYNC_PCLK_DIV4);
+#elif defined(STM32F3X_ADC_V1_1)
+	LL_ADC_SetCommonClock(__LL_ADC_COMMON_INSTANCE(adc),
+			LL_ADC_CLOCK_SYNC_PCLK_DIV1);
```
Comment (erwango) [inline drivers/adc/adc_stm32.c:1164]: Align indentation on previous code

Comment (erwango) [inline drivers/adc/adc_stm32.c:1164]: This misses a proper justification.
"Set the synchronous clock mode to HCLK/1 (DIV1)
since AHB ahb-prescaler = <1> in the RCC_CFGR"
This is AHB prescaler board specific setting. Fixing one case statically will likely break other cases.

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/adc/adc_stm32.c (hunk 2 above)
Comment (FRASTM) [reply drivers/adc/adc_stm32.c]: blank line removed

File: drivers/adc/adc_stm32.c (hunk 3 above)
Comment (FRASTM) [reply drivers/adc/adc_stm32.c]: note mis-alignment on line 1168

File: drivers/adc/adc_stm32.c [hunk 4]
```diff
@@ -1151,15 +1151,22 @@ static int adc_stm32_init(const struct device *dev)
...
 	defined(CONFIG_SOC_SERIES_STM32G0X) || \
 	defined(CONFIG_SOC_SERIES_STM32G4X) || \
 	defined(CONFIG_SOC_SERIES_STM32H7X)
 	LL_ADC_SetCommonClock(__LL_ADC_COMMON_INSTANCE(adc),
 			      LL_ADC_CLOCK_SYNC_PCLK_DIV4);
+#elif defined(STM32F3X_ADC_V1_1)
+	/*
+	 * Set the synchronous clock mode to
+	 * HCLK/1 (DIV1) if AHB ahb-prescaler = <1> in the RCC_CFGR
+	 * or HCLK/2 (DIV2) are valid
```
Comment (erwango) [inline drivers/adc/adc_stm32.c:1166]: Comment and reason for the change is not clear. Same in commit message

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/adc/adc_stm32.c (hunk 4 above)
Comment (FRASTM) [reply drivers/adc/adc_stm32.c]: changing comment to DIV1 or DIV2 as possible values for synchronous clock

**Review by erwango — APPROVED** [review]
Ack.
Better flexibility with ADC prescaler will be available in https://github.com/zephyrproject-rtos/zephyr/pull/48938

**Review by ABOSTM — APPROVED** [review]
