### PR TITLE
Bluetooth: Mesh: Fix matching for all elements of an LPN

### LINKED ISSUE #11731: Mesh friend doesn't forward packets to LPNs non-primary elements
The Zephyr BT Mesh friend only forwards packets that 
1. have their destination in the LPN's subscription list 
or 
2. [Are destined for the first element in the LPN.](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/mesh/friend.c#L1193)

This makes the friend queue reject packets that are supposed to go to non-primary elements. The friend module needs to store the LPNs element count in addition to its primary address when the friend request comes in, and take this into account when matching addresses for the LPN.

**To Reproduce**
Make an LPN node with more than one element connect to the friend, and try to send a message from the friend to the LPN's second element. It'll fail [the check on line 1193](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/mesh/friend.c#L1193) and reject the message.

**Expected behavior**
According to section 3.5.5 of the spec, the friend should forward packets destined for all the elements on the LPN node. 

**Impact**
Can't publish to models that aren't in the primary element

### PR DESCRIPTION
**Pull request by jhedberg**
When we're acting as a Friend for an LPN, we need to consider all
elements of the LPN. The information of how many elements the LPN has
is provided in the Friend Request message, however until now the code
did not do anything with this information.

Fix the issue by tracking the number of elements for each LPN and
update the unicast address matching code to take this into account.

Fixes #11731

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

File: subsys/bluetooth/host/mesh/friend.c [hunk 1]
```diff
@@ -1190,7 +1192,7 @@ static bool friend_lpn_matches(struct bt_mesh_friend *frnd, u16_t net_idx,
 	}
 
 	if (BT_MESH_ADDR_IS_UNICAST(addr)) {
-		if (addr == frnd->lpn) {
+		if (addr >= frnd->lpn && addr < (frnd->lpn + frnd->num_elem)) {
```
Comment (Vudentz) [inline subsys/bluetooth/host/mesh/friend.c]: Perhaps it would be a good idea to have a helper function to resolve valid friend addresses like above.

Comment (jhedberg) [reply subsys/bluetooth/host/mesh/friend.c]: Perhaps. Currently there are two places needing it.

**Comment by jhedberg** [comment]
Note: I still need to double-check the friendship security credentials handling, since that's stored using the primary element of the LPN.

**Comment by jhedberg** [comment]
> Note: I still need to double-check the friendship security credentials handling, since that's stored using the primary element of the LPN.

I've now gone through the relevant parts of the code and this aspect seems to be fine.

File: subsys/bluetooth/host/mesh/friend.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/mesh/friend.c]: Fixed now

**Comment by jhedberg** [comment]
I've now also added a check that we don't get a bogus num_elem that would cause an overflow into the non-unicast range of addresses. This shouldn't influence the testing @trond-snekvik is doing however.

**Review by Vudentz — APPROVED** [review]
LGTM
