### PR TITLE
Bluetooth: Rework the HCI header set

### LINKED ISSUE #58214: Bluetooth: Host: hci.h header include depends on conn.h
**Describe the bug**
Samples, application and controller implementation needing `hci.h` header include has dependency on `conn.h` which makes host connection data types be included in source code compilations.

Dependency introduced in 0f06c7d

Refer to https://github.com/zephyrproject-rtos/zephyr/pull/58154#discussion_r1203243070

**To Reproduce**
NA

**Expected behavior**
`hci.h` should not include `conn.h` .

**Impact**
annoyance. stable API change?

**Logs and console output**
NA

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK,
 - Commit SHA or Version used: 5181b53

**Additional context**
NA

### PR DESCRIPTION
**Pull request by carlescufi**
Bluetooth: Rework the HCI header set

    In order to have clean, self-contained HCI headers that do not have any
    dependencies towards the Host or any other part of the system (except
    types), reorganize the headers in the following way:

    - Split out the macros and structs from hci.h to a new hci_types.h
    - Merge the existing hci_err.h into the new hci_types.h

Fixes #58214.

### CODE REVIEW

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/controller/hci/hci.c [hunk 1]
```diff
@@ -21,6 +21,7 @@
 #include <zephyr/bluetooth/hci_vs.h>
 #include <zephyr/bluetooth/buf.h>
 #include <zephyr/bluetooth/bluetooth.h>
+#include <zephyr/bluetooth/conn.h>
```
Comment (jhedberg) [inline subsys/bluetooth/controller/hci/hci.c:24]: Why should the controller depend on conn.h? Isn’t that a purely host-specific API? What we discussed last week was that hci.h should get split into two files, so that one contains strictly only HCI protocol definitions (structs & defines) and nothing else.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/hci/hci.c (hunk 1 above)
Comment (carlescufi) [reply subsys/bluetooth/controller/hci/hci.c:24]: Will rework as per the Discord discussion.

**Review by jhedberg — DISMISSED** [review]

**Comment by cvinayak** [comment]
@carlescufi  I did some more clean up in Controller in a new commit in this PR: 7af43d235ff66cd0bde8a7d7deb7a93994865e8f

**Review by cvinayak — APPROVED** [review]

**Comment by cvinayak** [comment]
Controller does continue to include `<zephyr/bluetooth/conn.h`  and `<zephyr/bluetooth/iso.h` (in c source files, not in include headers) for connection role definitions and ISO packing (sequential or interleaved), respectively. These exceptions in the Controller C source file should be addressed outside the scope of this PR. Otherwise, the changes in this PR looks good to me.

**Review by kruithofa — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]
