### PR TITLE
soc: arm: nordic_nrf: nrf52: Add workaround for anomaly 132

### LINKED ISSUE #21493: System tick is not running
**Describe the bug**
From time to time I observe the following issue on my Zephyr device:
Timestamps for logs are not increasing and application is not running.
It looks like the system tick is not working.

**To Reproduce**
Issue replicated rarely when device is connected via JLink.
I replicated it with two nrf52832 based devices (both use custom boards).
The boards are in use for longer period of time and the issue was not replicated before in similar test conditions.

**Impact**
When this occurrs, the device is unusable.

**Screenshots or console output**
```
[00000000] <inf> event_manager: e: module_state_event module:main state:READY
[00000000] <wrn> leds: No effect set
[00000000] <inf> bt_ctlr_hci_driver: BLE controller build revision:
b6 f6 35 94 8a ca fb 4c  d2 fd c2 c0 b8 20 ae f0 |..5....L ..... ..
15 1c 18 40                                      |...@
[00000000] <inf> hid_state: Init HID state!
[00000000] <inf> power_manager: Activate power manager
[00000000] <wrn> power_manager: Constant latency enabled
[00000000] <inf> event_manager: e: module_state_event module:board state:READY
[00000000] <inf> event_manager: e: module_state_event module:buttons state:READY
[00000000] <inf> event_manager: e: module_state_event module:click_detector state:READY
[00000000] <inf> event_manager: e: module_state_event module:leds state:READY
[00000000] <inf> event_manager: e: module_state_event module:battery_meas state:READY
[00000000] <inf> event_manager: e: module_state_event module:fn_keys state:READY
[00000000] <inf> bt_hci_core: No ID address. App must call settings_load()
[00000000] <inf> ble_state: Bluetooth initialized
[00000000] <inf> ble_state: LLPM enabled
[00000000] <inf> event_manager: e: module_state_event module:ble_state state:READY
[00000000] <inf> hids: Service initialized
[00000000] <inf> event_manager: e: module_state_event module:ble_adv state:READY
[00000000] <inf> event_manager: e: module_state_event module:bas state:READY
[00000000] <inf> event_manager: e: module_state_event module:hids state:READY
[00000000] <inf> config: Settings load thread started
[00000000] <inf> bt_settings: Saving ID
[00000000] <inf> config: Settings loaded
[00000000] <inf> event_manager: e: module_state_event module:config state:READY
[00000000] <inf> ble_bond: Device has 5 identities
[00000000] <inf> ble_bond: Selected BLE peers
[00000000] <inf> event_manager: e: ble_peer_operation_event SELECTED bt_app_id=1 bt_stack_id=2
[00000000] <inf> event_manager: e: module_state_event module:ble_bond state:READY
[00000000] <inf> ble_adv: Advertising stopped
[00000000] <inf> ble_adv: Use fast advertising
[00000000] <inf> ble_adv: Advertising started
[00000000] <inf> event_manager: e: led_event led_id:0 effect:0x3e248
[00000000] <inf> event_manager: e: ble_peer_search_event inactive
```

**Environment:**
Zephyr commit hash: 0297756342fb60e6a64813aac046f4d241cbd369

### PR DESCRIPTION
**Pull request by nordic-krch**
Added delay before starting low frequency clock for the first time to
ensure that anomaly conditions are not met. Delay is configurable and
might be disabled.

Fixes #21493.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by nordic-krch** [comment]
@MarekPieta fyi, a workaround is applied which is fixed delay at startup to ensure that app gets out of danger zone. You may need to tune the delay for application.

File: drivers/clock_control/nrf_power_clock.c [hunk 1]
```diff
@@ -228,6 +228,21 @@ static struct clock_control_async_data *list_get(sys_slist_t *list)
 	return async_data;
 }
 
+static inline void anomaly_132_workaround(nrf_clock_task_t start_tsk)
+{
```
Comment (ulfalizer) [inline drivers/clock_control/nrf_power_clock.c]: Could maybe do

```c
#if CONFIG_NRF52_ANOMALY_132_DELAY_US != 0
// Function body
#endif
```

and remove the `CONFIG_NRF52_ANOMALY_132_DELAY_US` in the `if (...)`. Undefined macros evaluate to 0.

File: drivers/clock_control/nrf_power_clock.c [hunk 2]
```diff
@@ -280,6 +295,11 @@ static int clock_async_start(struct device *dev,
 				config->start_handler(dev) : true;
 		if (do_start) {
 			DBG(dev, subsys, "Triggering start task");
+
+			if (IS_ENABLED(CONFIG_NRF52_ANOMALY_132_WORKAROUND)) {
+				anomaly_132_workaround(config->start_tsk);
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: Passing of the start task to `anomaly_132_workaround` is a bit misleading. IMO it would be clearer to check the task in the `if` right above, as this anomaly applies to LFCLK only.

File: drivers/clock_control/nrf_power_clock.c [hunk 3]
```diff
@@ -228,6 +228,21 @@ static struct clock_control_async_data *list_get(sys_slist_t *list)
...
 
+static inline void anomaly_132_workaround(nrf_clock_task_t start_tsk)
+{
+	static bool once;
+
+	#ifndef CONFIG_NRF52_ANOMALY_132_DELAY_US
+	#define CONFIG_NRF52_ANOMALY_132_DELAY_US 0
+	#endif
+
+	if ((start_tsk == NRF_CLOCK_TASK_LFCLKSTART) && !once &&
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: Just curious. Is the generated code shorter when the task is checked? It feels more natural to check `type` (`subsys`) instead.

File: drivers/clock_control/nrf_power_clock.c (hunk 2 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: drivers/clock_control/nrf_power_clock.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: drivers/clock_control/nrf_power_clock.c (hunk 3 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: change to subsys, it's better and cleaner.

**Review by anangl — APPROVED** [review]

File: drivers/clock_control/nrf_power_clock.c (hunk 1 above)
Comment (pabigot) [reply drivers/clock_control/nrf_power_clock.c]: As `CONFIG_FOO` macros are sometimes defined to an empty sequence Ibecause that's enough to get `#ifdef ` to work), the most robust way to do this sort of test is:
```
#if (CONFIG_NRF52_ANOMALY_132_DELAY_US - 0)
// feature
#endif
```
This will work for undefined, defined to empty sequence, defined to 0, and defined to non-zero integer, which covers the normal range of possibilities.  Only the last (defined to non-zero integer) causes the feature to be included.

Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

**Review by pabigot — APPROVED** [review]
At a future time if it may become necessary restart LFCLK (e.g. to change the source), at which point this would need to be revised.  But this looks good for now.

File: drivers/clock_control/nrf_power_clock.c (hunk 1 above)
Comment (ulfalizer) [reply drivers/clock_control/nrf_power_clock.c]: Kconfig itself skips outputting macros for `n`-valued symbols and symbols with unsatisfied dependencies at least.

The Linux kernel just does stuff like `#if CONFIG_PGTABLE_LEVELS >= 3`.

File: soc/arm/nordic_nrf/nrf52/Kconfig.soc [hunk 4]
```diff
@@ -361,3 +361,21 @@ config NRF_ENABLE_ICACHE
...
 	default y
+
+config NRF52_ANOMALY_132_DELAY_US
+	int "Anomaly 132 workaround delay (microseconds)"
+	default 220
+	depends on NRF52_ANOMALY_132_WORKAROUND
+	help
+	  Due to Anomaly 132 LF RC source may not start if restarted in certain
+	  window after stopping (230 us to 330 us). Software reset also stops the
+	  clock so if clock is initiated in certain window, it may also fail to
```
Comment (ioannisg) [inline soc/arm/nordic_nrf/nrf52/Kconfig.soc]: it -> the clock

File: soc/arm/nordic_nrf/nrf52/Kconfig.soc [hunk 5]
```diff
@@ -361,3 +361,21 @@ config NRF_ENABLE_ICACHE
...
+	  start at reboot. A delay is added before starting LF clock to ensure that
+	  anomaly conditions are not met. Delay should be long enough to ensure that
+	  clock is started later than 330 us after reset. If crystal oscillator(XO)
```
Comment (ioannisg) [inline soc/arm/nordic_nrf/nrf52/Kconfig.soc]: If this is the case, could we just make the default 330us, instead? Then the solution is deterministic.

File: soc/arm/nordic_nrf/nrf52/Kconfig.soc [hunk 6]
```diff
@@ -361,3 +361,21 @@ config NRF_ENABLE_ICACHE
 	bool "Enable the instruction cache (I-Cache)"
 	depends on SOC_NRF52832 || SOC_NRF52833 || SOC_NRF52840
 	default y
+
+config NRF52_ANOMALY_132_DELAY_US
+	int "Anomaly 132 workaround delay (microseconds)"
+	default 220
```
Comment (ioannisg) [inline soc/arm/nordic_nrf/nrf52/Kconfig.soc]: Should we have a range here, to prevent high numbers that might have bad effects, (e.g. to watchdog)?

**Review by ioannisg — COMMENTED** [review]
Looks much better than the previous solution proposal:
I added some comments in the text.

File: soc/arm/nordic_nrf/nrf52/Kconfig.soc (hunk 4 above)
Comment (nordic-krch) [reply soc/arm/nordic_nrf/nrf52/Kconfig.soc]: done

File: soc/arm/nordic_nrf/nrf52/Kconfig.soc (hunk 6 above)
Comment (nordic-krch) [reply soc/arm/nordic_nrf/nrf52/Kconfig.soc]: done

File: soc/arm/nordic_nrf/nrf52/Kconfig.soc (hunk 5 above)
Comment (nordic-krch) [reply soc/arm/nordic_nrf/nrf52/Kconfig.soc]: i agree, if someone starts tweaking startup time it may have it shorter than empty app and if he is tweaking then sooner or later he will find out this delay and tune it.

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@ioannisg please review and merge

**Review by ioannisg — APPROVED** [review]
