### PR TITLE
soc: nordic: common: dmm: Fix allocation algorithm

### LINKED ISSUE #96835: tests: boards: nrf: dmm: boards.nrf.dmm.more_chunks fails at H20
### Describe the bug

**Describe the bug**
Tests 
- tests/boards/nrf/dmm/boards.nrf.dmm.more_chunks fails

Observed for `nrf54h20dk/nrf54h20/cpuapp`.

**To Reproduce**
1. haven nrf54h20dk/nrf54h20/cpuapp connected
2. go to your zephyr dir
3. call `./scripts/twister -T  tests/boards/nrf/dmm -pnrf54h20dk/nrf54h20/cpuapp --device-testing --device-serial /dev/ttyACM0 -v --inline-logs --west-flash="--erase"`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v4.2.0-4717-g5ad9494835ab ***
Running TESTSUITE dmm
===================================================================
START - test_check_dev_cache_in_allocate
aligned buffer in prepare buf:0x2f89c040 size:16 took 1.687us (540 cycles)
buffer in release buf:0x2f89c040 size:16 took 1.943us (622 cycles)
aligned buffer in prepare buf:0x2f89c040 size:128 took 2.312us (740 cycles)
buffer in release buf:0x2f89c040 size:128 took 4.168us (1334 cycles)
 PASS - test_check_dev_cache_in_allocate in 0.026 seconds
===================================================================
START - test_check_dev_cache_in_preallocate
aligned buffer in prepare buf:0x2f89c020 size:16 took 1.196us (383 cycles)
buffer in release buf:0x2f89c020 size:16 took 0.712us (228 cycles)
 PASS - test_check_dev_cache_in_preallocate in 0.013 seconds
===================================================================
START - test_check_dev_cache_out_allocate
aligned buffer out prepare size:16 buf:0x2f89c040 took 1.993us (638 cycles)
buffer out release buf:0x2f89c040 size:16 took 1.346us (431 cycles)
not aligned buffer out prepare size:16 buf:0x2f89c040 took 2.321us (743 cycles)
buffer out release buf:0x2f89c040 size:16 took 1.346us (431 cycles)
aligned buffer out prepare size:128 buf:0x2f89c040 took 3.221us (1031 cycles)
buffer out release buf:0x2f89c040 size:128 took 1.346us (431 cycles)
not aligned buffer out prepare size:128 buf:0x2f89c040 took 5.62us (1620 cycles)
buffer out release buf:0x2f89c040 size:128 took 1.340us (429 cycles)
 PASS - test_check_dev_cache_out_allocate in 0.052 seconds
===================================================================
START - test_check_dev_cache_out_preallocate
aligned buffer out prepare size:16 buf:0x2f89c000 took 1.275us (408 cycles)
buffer out release buf:0x2f89c000 size:16 took 0.562us (180 cycles)
 PASS - test_check_dev_cache_out_preallocate in 0.013 seconds
===================================================================
START - test_check_dev_nocache_in_allocate
aligned buffer in prepare buf:0x2fc12028 size:16 took 1.478us (473 cycles)
buffer in release buf:0x2fc12028 size:16 took 2.740us (877 cycles)
not aligned buffer in prepare buf:0x2fc12028 size:16 took 1.850us (592 cycles)
buffer in release buf:0x2fc12028 size:16 took 6.581us (2106 cycles)
aligned buffer in prepare buf:0x2fc12028 size:128 took 2.368us (758 cycles)
buffer in release buf:0x2fc12028 size:128 took 42.687us (13660 cycles)
not aligned buffer in prepare buf:0x2fc12028 size:128 took 1.909us (611 cycles)
buffer in release buf:0x2fc12028 size:128 took 41.493us (13278 cycles)
 PASS - test_check_dev_nocache_in_allocate in 0.052 seconds
===================================================================
START - test_check_dev_nocache_in_preallocate
aligned buffer in prepare buf:0x2fc12010 size:16 took 0.553us (177 cycles)
buffer in release buf:0x2fc12010 size:16 took 0.512us (164 cycles)
 PASS - test_check_dev_nocache_in_preallocate in 0.013 seconds
===================================================================
START - test_check_dev_nocache_out_allocate
aligned buffer out prepare size:16 buf:0x2fc12028 took 3.62us (980 cycles)
buffer out release buf:0x2fc12028 size:16 took 1.353us (433 cycles)
not aligned buffer out prepare size:16 buf:0x2fc12028 took 7.590us (2429 cycles)
buffer out release buf:0x2fc12028 size:16 took 1.365us (437 cycles)
aligned buffer out prepare size:128 buf:0x2fc12028 took 13.587us (4348 cycles)
buffer out release buf:0x2fc12028 size:128 took 1.418us (454 cycles)
not aligned buffer out prepare size:128 buf:0x2fc12028 took 49.462us (15828 cycles)
buffer out release buf:0x2fc12028 size:128 took 1.421us (455 cycles)
 PASS - test_check_dev_nocache_out_allocate in 0.053 seconds
===================================================================
START - test_check_dev_nocache_out_preallocate
aligned buffer out prepare size:16 buf:0x2fc12000 took 0.546us (175 cycles)
buffer out release buf:0x2fc12000 size:16 took 0.559us (179 cycles)
 PASS - test_check_dev_nocache_out_preallocate in 0.013 seconds
===================================================================
START - test_check_multiple_alloc_and_free
Stats start_address:0x2fc12028 current use:0% max use:7%
 PASS - test_check_multiple_alloc_and_free in 0.006 seconds
===================================================================
START - test_stress_allocator_cache

0% remaining:2000 ms
0% remaining:1000 ms
0% remaining:0 ms
Ztress execution report:
 context 0:
 - executed:9845, preempted:0
 - ticks initial:4, optimized:4
 context 1:
 - executed:6220, preempted:2850
 - ticks initial:4, optimized:4
 context 2:
 - executed:2519, preempted:1786
 - ticks initial:4, optimized:4
Average CPU load:94%, measurements:30
Executed 22260 allocation operation. Failed to allocate 0 times.

    Assertion failed at ../../../../../../../../../zephyr/tests/boards/nrf/dmm/src/main.c:549: stress_allocator: (curr_use not equal to curr_use2)
Unexpected usage got:2 exp:0
 FAIL - test_stress_allocator_cache in 3.063 seconds
===================================================================
START - test_stress_allocator_nocache

0% remaining:2000 ms
0% remaining:1000 ms
0% remaining:0 ms
Ztress execution report:
 context 0:
 - executed:7115, preempted:0
 - ticks initial:4, optimized:4
 context 1:
 - executed:2870, preempted:1928
 - ticks initial:4, optimized:4
 context 2:
 - executed:634, preempted:542
 - ticks initial:4, optimized:4
Average CPU load:97%, measurements:30
Executed 9389 allocation operation. Failed to allocate 6105 times.

    Assertion failed at ../../../../../../../../../zephyr/tests/boards/nrf/dmm/src/main.c:549: stress_allocator: (curr_use not equal to curr_use2)
Unexpected usage got:8 exp:0
 FAIL - test_stress_allocator_nocache in 3.065 seconds
===================================================================
TESTSUITE dmm failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  81.82% [dmm]: pass = 9, fail = 2, skip = 0, total = 11 duration = 6.369 seconds
 - PASS - [dmm.test_check_dev_cache_in_allocate] duration = 0.026 seconds
 - PASS - [dmm.test_check_dev_cache_in_preallocate] duration = 0.013 seconds
 - PASS - [dmm.test_check_dev_cache_out_allocate] duration = 0.052 seconds
 - PASS - [dmm.test_check_dev_cache_out_preallocate] duration = 0.013 seconds
 - PASS - [dmm.test_check_dev_nocache_in_allocate] duration = 0.052 seconds
 - PASS - [dmm.test_check_dev_nocache_in_preallocate] duration = 0.013 seconds
 - PASS - [dmm.test_check_dev_nocache_out_allocate] duration = 0.053 seconds
 - PASS - [dmm.test_check_dev_nocache_out_preallocate] duration = 0.013 seconds
 - PASS - [dmm.test_check_multiple_alloc_and_free] duration = 0.006 seconds
 - FAIL - [dmm.test_stress_allocator_cache] duration = 3.063 seconds
 - FAIL - [dmm.test_stress_allocator_nocache] duration = 3.065 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.17.0
 - Commit SHA or Version used: `v4.2.0-4717-g5ad9494835ab`

### PR DESCRIPTION
**Pull request by nordic-krch**
There were some corner cases and stress test could fail. Reworking tail bits handling to make the stress test pass.

Fixes  #96835.

### CODE REVIEW

File: tests/boards/nrf/dmm/src/main.c [hunk 1]
```diff
@@ -522,6 +522,10 @@ static void stress_allocator(void *mem_reg, bool cached)
 	int rv;
 	uint32_t curr_use;
 
+	if (mem_reg == NULL) {
+		ztest_test_skip();
+	}
+
```
Comment (bjarki-andreasen) [inline tests/boards/nrf/dmm/src/main.c:528]: To save CI a bit, we should probably not build and run this test suite if DMM is not enabled. Can testcase.yaml not be used to filter? or is there a reason to build and run this suite even though DMM is not enabled?

**Review by bjarki-andreasen — CHANGES_REQUESTED** [review]

File: tests/boards/nrf/dmm/src/main.c (hunk 1 above)
Comment (nordic-krch) [reply tests/boards/nrf/dmm/src/main.c:528]: It's used to confirm that dmm API turns into empty calls when SoC does not support it. I think it is worth keeping it because in some drivers DMM API is called unconditionally and test on that board ensures that it works.

Comment (bjarki-andreasen) [reply tests/boards/nrf/dmm/src/main.c:528]: ok

**Review by bjarki-andreasen — DISMISSED** [review]

**Comment by nordic-krch** [comment]
@anangl can you take a look?

File: soc/nordic/common/dmm.c [hunk 2]
```diff
@@ -135,32 +135,20 @@ static void tail_mask_set(atomic_t *tail_mask, size_t num_bits, size_t off)
...
-	 */
-	atomic_or(&tail_mask[idx], BIT_MASK(32 - tail_off) << tail_off);
-
-
-	size_t rem_tail = tail_bits - (32 - tail_off);
-	atomic_t *mask = &tail_mask[idx + 1];
+	tail_off = tail_off % 32;
+	while (tail_bits > 0) {
+		uint32_t rem_bits = MIN(32 - tail_off, tail_bits);
+		uint32_t bits = MIN(tail_bits, rem_bits);
```
Comment (anangl) [inline soc/nordic/common/dmm.c]:
```suggestion
		uint32_t bits = MIN(32 - tail_off, tail_bits);
```

File: soc/nordic/common/dmm.c [hunk 3]
```diff
@@ -189,33 +177,36 @@ static uint32_t num_bits_get(atomic_t *tail_mask, size_t off)
...
+			atomic_set(t_mask, 0);
+		} else {
+			mask = BIT_MASK(bits) << tail_off;
 			atomic_and(t_mask, ~mask);
-			num_bits += tmp_bits;
-		} while ((tmp_bits == 32) && (t_mask != &tail_mask[HEAP_NUM_WORDS - 1]));
-	}
+		}
+
+		if (((bits + tail_off) < 32) || (bits == 0)) {
```
Comment (anangl) [inline soc/nordic/common/dmm.c]: `tail_off` is by definition < 32 (it's a result of `% 32`), so the second condition is redundant.

File: soc/nordic/common/dmm.c [hunk 4]
```diff
@@ -189,33 +177,36 @@ static uint32_t num_bits_get(atomic_t *tail_mask, size_t off)
...
+			return num_bits;
+		}
+
+		tail_off = 0;
+		t_mask++;
+	} while (t_mask != &tail_mask[HEAP_NUM_WORDS]);
```
Comment (anangl) [inline soc/nordic/common/dmm.c]: Wouldn't it make sense to simplify this function a bit more? I guess the following should work for all cases and perhaps even for `HEAP_NUM_WORDS == 1` it would get quite nicely optimized:
```
	uint32_t num_bits = 1;
	size_t tail_off = off + 1;
	size_t idx = tail_off / 32;
	atomic_t *t_mask = &tail_mask[idx];

	do {
		uint32_t mask = (uint32_t)*t_mask >> tail_off;

		if (mask == UINT32_MAX) {
			num_bits += 32;
			atomic_set(t_mask, 0);
		} else {
			uint32_t bits = __builtin_ctz(~mask);

			if (bits == 0) {
				break;
			}

			num_bits += bits;
			atomic_and(t_mask, ~(BIT_MASK(bits) << tail_off));

			if (bits + tail_off < 32) {
				break;
			}

			tail_off = 0;
		}

		t_mask++;
	} while (t_mask != &tail_mask[HEAP_NUM_WORDS]);

	return num_bits;
```

Comment (nordic-krch) [reply soc/nordic/common/dmm.c]: I had to add `tail_off = tail_off % 32` before loop and then tests were passing. I've also changed while condition to
`while ((HEAP_NUM_WORDS > 1) && (t_mask != &tail_mask[HEAP_NUM_WORDS]));` as it reduces function size by 30 bytes so compiler is not able to detect based on the address comparison.

Comment (anangl) [reply soc/nordic/common/dmm.c]: Right, I don't know really how I managed to drop `tail_off = tail_off % 32`...

**Review by anangl — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]
