### PR TITLE
arch: arc: fix the bug of mpu stack guard when no USERSPACE

### LINKED ISSUE #15163: nsim_*_mpu_stack_guard fails if CONFIG_USERSPACE=n but CONFIG_HW_STACK_PROTECTION=y
For example, with tests/posix/common:

```
Console now belongs to UART, hit CRTL-] to return to simulator.
***** Booting Zephyr OS v1.14.0-rc3-100-g94b8f14eca13 *****
Running test suite posix_apis
===================================================================
starting test - test_posix_pthread_execution
Thread 0 starting with scheduling policy 0 & priority 15
Thread 1 starting with scheduling policy 0 & priority 15
Thread 2 starting with scheduling policy 0 & priority 15
Bounce test OK
Barrier test OK
PASS - test_posix_pthread_execution
===================================================================
starting test - test_posix_pthread_termination
Thread 0 starting with a priority of 4
Cancelling thread 0
Thread 1 starting with a priority of 3
Cancelling thread 1
Thread 1 could not be cancelled
Exception vector: 0x6, cause code: 0x2, parameter 0x4
Address 0x8000bbc0
***** Stack Check Fail! *****
Current thread ID = 0x800003ec
Fatal fault in thread 0x800003ec! Aborting.
Thread 3 starting with a priority of 1
Cancelling thread 3
Thread 3 could not be cancelled

    Assertion failed at /home/apboie/projects/zephyr3/zephyr/tests/posix/common/src/pthread.c:419: test_posix_pthread_termination: (ret not equal to ESRCH)
cancelled a terminated thread!
FAIL - test_posix_pthread_termination
===================================================================
starting test - test_posix_multiple_threads_single_key

Different threads set different values to same key:
thread 0: set value = -2147479816 and retrieved value = -2147479816
thread 1: set value = -2147479560 and retrieved value = -2147479560

PASS - test_posix_multiple_threads_single_key
===================================================================
starting test - test_posix_single_thread_multiple_keys

Single thread associates its value with different keys:
Exception vector: 0x6, cause code: 0x2, parameter 0x4
Address 0x8000d3e4
***** Stack Check Fail! *****
Current thread ID = 0x8000064c
Fatal fault in thread 0x8000064c! Aborting.

```

### PR DESCRIPTION
**Pull request by vonhust**
* fix the stack allocation and initialization
  for mpu stack guard when USERSPACE is not configured
* fixes #15163

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

### CODE REVIEW

File: arch/arc/core/thread.c [hunk 1]
```diff
@@ -165,6 +165,7 @@ void z_new_thread(struct k_thread *thread, k_thread_stack_t *stack,
 	 */
 	pInitCtx->status32 |= _ARC_V2_STATUS32_US;
 #else /* For no USERSPACE feature */
+	pStackMem += STACK_GUARD_SIZE;
```
Comment (ruuddw) [inline arch/arc/core/thread.c]: It would be good to use the macro's from arc/arch.h or even better generic zephyr stack macro's in this file as much as possible. E.g. should this be STACK_GUARD_SIZE,  or Z_ARCH_THREAD_STACK_RESERVED?
Also at other places in this file, e.g. calculation of stack_AdjSize in line 84/86

File: include/arch/arc/arch.h [hunk 2]
```diff
@@ -79,87 +80,70 @@ extern "C" {
...
+#endif
 
-#if CONFIG_ARC_MPU_VER == 2
 
-#define Z_ARCH_THREAD_STACK_DEFINE(sym, size) \
-	struct _k_thread_stack_element __noinit \
-		__aligned(POW2_CEIL(STACK_SIZE_ALIGN(size))) \
-		sym[POW2_CEIL(STACK_SIZE_ALIGN(size)) + \
-		+  STACK_GUARD_SIZE + CONFIG_PRIVILEGED_STACK_SIZE]
+/* MPUv2 requires size must be power of 2 and >= 2048 */
```
Comment (ruuddw) [inline include/arch/arc/arch.h]: There are two alignement requirements for MPUv2 : size is power of two, and start is aligned to its size. I think the macro is more introduced for the latter requirmentent  -> suggest to update comment to include the alignment requirement on region size.

File: include/arch/arc/arch.h [hunk 3]
```diff
@@ -79,87 +80,70 @@ extern "C" {
...
+#define Z_ARCH_THREAD_STACK_SIZE(size) POW2_CEIL(STACK_SIZE_ALIGN(size))
```
Comment (ruuddw) [inline include/arch/arc/arch.h]: Confusing name of macro. This only applies to MPUv2, and the macro is only used in MPUv2 stack settings. Suggest to rename into something like Z_ARCH_THREAD_STACK_SIZE_PWR2 or including _MPUv2_

File: include/arch/arc/arch.h [hunk 4]
```diff
@@ -79,87 +80,70 @@ extern "C" {
...
 
+#if  defined(CONFIG_USERSPACE) && CONFIG_ARC_MPU_VER == 2
```
Comment (ruuddw) [inline include/arch/arc/arch.h]: Please add a comment on rationale/explanation  for the alignment requirements: user stack and guard are protected using MPU regions, so need to adhere to MPU start, size alignment.
And something similar for the no-userspace guard below: kernel stacks are not MPU protected, only guard needs to be aligned.

File: include/arch/arc/arch.h [hunk 5]
```diff
@@ -79,87 +80,70 @@ extern "C" {
...
+#define Z_ARCH_THREAD_STACK_ARRAY_LEN(size) \
+		(Z_ARCH_THREAD_STACK_SIZE(size) + \
+		MAX(Z_ARCH_THREAD_STACK_SIZE(size), \
+		POW2_CEIL(Z_ARCH_THREAD_STACK_RESERVED)))
+#elif defined(CONFIG_MPU_STACK_GUARD) && CONFIG_ARC_MPU_VER == 2
+#define Z_ARCH_THREAD_STACK_ALIGN(size)	(STACK_ALIGN)
+#define Z_ARCH_THREAD_STACK_LEN(size) \
+		(size + Z_ARCH_THREAD_STACK_RESERVED)
+#define Z_ARCH_THREAD_STACK_ARRAY_LEN(size) \
+		(Z_ARCH_THREAD_STACK_SIZE(size) + \
```
Comment (ruuddw) [inline include/arch/arc/arch.h]: Is the power-of-two alignement for stack size required here? Isn't stack size aligment (STACK_SIZE_ALIGN) enough to guarantee the guard address and size match MPU alignment requirements?

**Review by ruuddw — COMMENTED** [review]
This fixes the mpu_guards without userspace case, and improves structure/maintainability in general.
Few suggestions to improve, still.

File: include/arch/arc/arch.h (hunk 4 above)
Comment (vonhust) [reply include/arch/arc/arch.h]: done

File: include/arch/arc/arch.h (hunk 3 above)
Comment (vonhust) [reply include/arch/arc/arch.h]: done

File: include/arch/arc/arch.h (hunk 2 above)
Comment (vonhust) [reply include/arch/arc/arch.h]: done

File: arch/arc/core/thread.c (hunk 1 above)
Comment (vonhust) [reply arch/arc/core/thread.c]: done

File: include/arch/arc/arch.h (hunk 5 above)
Comment (vonhust) [reply include/arch/arc/arch.h]: done

File: include/arch/arc/arch.h (hunk 3 above)
Comment (andrewboie) [reply include/arch/arc/arch.h]: Z_ARCH_ namespace is reserved for kernel <--> arch API.
Since this is ARC-specific and only used by ARC internally, call it something else.

File: include/arch/arc/arch.h [hunk 6]
```diff
@@ -68,8 +68,9 @@ extern "C" {
 	#define STACK_GUARD_SIZE 0
 #endif /* CONFIG_MPU_STACK_GUARD */
 
-#define STACK_SIZE_ALIGN(x)	MAX(STACK_ALIGN, x)
 
+#define STACK_SIZE_ALIGN(x) \
```
Comment (andrewboie) [inline include/arch/arc/arch.h]: Please use existing macros for rounding values up or down. ROUND_UP() ROUND_DOWN() in include/misc/util.h

File: include/arch/arc/arch.h [hunk 7]
```diff
@@ -79,87 +80,77 @@ extern "C" {
...
-		__aligned(POW2_CEIL(STACK_SIZE_ALIGN(size))) \
-		sym[POW2_CEIL(STACK_SIZE_ALIGN(size)) + \
-		+  STACK_GUARD_SIZE + CONFIG_PRIVILEGED_STACK_SIZE]
 
+#if  defined(CONFIG_USERSPACE) && CONFIG_ARC_MPU_VER == 2
+/* MPUv2 requires
+ *  - region size must be power of 2 and >= 2048
+ *  - region start must be aligned to its size
+ */
+#define Z_ARCH_THREAD_STACK_SIZE_PWR2(size) POW2_CEIL(STACK_SIZE_ALIGN(size))
```
Comment (andrewboie) [inline include/arch/arc/arch.h]: Do not introduce new Z_ARCH_ macros. Call this something else.

File: include/arch/arc/arch.h [hunk 8]
```diff
@@ -79,87 +80,77 @@ extern "C" {
...
+/*
+ * user stack and guard are protected using MPU regions, so need to adhere to
+ * MPU start, size alignment
+ */
+#define Z_ARCH_THREAD_STACK_ALIGN(size)	Z_ARCH_THREAD_STACK_SIZE_PWR2(size)
```
Comment (andrewboie) [inline include/arch/arc/arch.h]: Do not introduce new Z_ARCH_ macros, call this something else. Z_ARCV2_ is fine.

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]

**Comment by andrewboie** [comment]
This patch doesn't build.

For nsim_em_mpu_stack_guard on tests/kernel/sched/schedule_api:

```
[  8%] Building C object CMakeFiles/app.dir/src/main.c.obj
In file included from /projects/zephyr3/zephyr/include/arch/cpu.h:19,
                 from /projects/zephyr3/zephyr/include/kernel_includes.h:34,
                 from /projects/zephyr3/zephyr/include/kernel.h:17,
                 from /projects/zephyr3/zephyr/include/zephyr.h:18,
                 from /projects/zephyr3/zephyr/tests/kernel/sched/schedule_api/src/test_sched.h:10,
                 from /projects/zephyr3/zephyr/tests/kernel/sched/schedule_api/src/main.c:7:
/projects/zephyr3/zephyr/tests/kernel/sched/schedule_api/src/main.c:11:29: error: conflicting types for 'tstacks'
 K_THREAD_STACK_ARRAY_DEFINE(tstacks, MAX_NUM_THREAD, STACK_SIZE);
                             ^~~~~~~
/projects/zephyr3/zephyr/include/arch/arc/arch.h:141:3: note: in definition of macro 'Z_ARCH_THREAD_STACK_ARRAY_DEFINE'
   sym[nmemb][Z_ARCH_THREAD_STACK_ARRAY_LEN(size)]
   ^~~
/projects/zephyr3/zephyr/tests/kernel/sched/schedule_api/src/main.c:11:1: note: in expansion of macro 'K_THREAD_STACK_ARRAY_DEFINE'
 K_THREAD_STACK_ARRAY_DEFINE(tstacks, MAX_NUM_THREAD, STACK_SIZE);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /projects/zephyr3/zephyr/tests/kernel/sched/schedule_api/src/main.c:7:
/projects/zephyr3/zephyr/tests/kernel/sched/schedule_api/src/test_sched.h:18:2: note: previous declaration of 'tstacks' was here
  tstacks[MAX_NUM_THREAD][K_THREAD_STACK_LEN(STACK_SIZE)];
  ^~~~~~~
make[2]: *** [CMakeFiles/app.dir/build.make:63: CMakeFiles/app.dir/src/main.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/app.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

File: include/arch/arc/arch.h (hunk 3 above)
Comment (vonhust) [reply include/arch/arc/arch.h]: already changed

File: include/arch/arc/arch.h (hunk 6 above)
Comment (vonhust) [reply include/arch/arc/arch.h]: done

File: include/arch/arc/arch.h (hunk 7 above)
Comment (vonhust) [reply include/arch/arc/arch.h]: done

File: include/arch/arc/arch.h (hunk 8 above)
Comment (vonhust) [reply include/arch/arc/arch.h]: done

**Comment by andrewboie** [comment]
I think for the build failure I found, the test case is making unwarranted assumptions as to the structure of the thread stack array. We should probably change the test case to a more generic extern definition.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by vonhust** [comment]
@andrewboie , I suggest to add a specific macro for stack array, e.g. Z_ARCH_THREAD_STACK_ARRAY_LEN, as it has more strict requirement than single stack item, at least in ARC MPUv2

**Review by ioannisg — APPROVED** [review]

**Review by ruuddw — APPROVED** [review]
Latest changes to PR do not trigger the schedule_api build issue, but introduce additional alignment overhead that isn't required. It would be better to fix the test, but ok to do that only later (1.15, as part of larger stack info / allocation changes). For ARC, MPU stack guards are not likely to be used anyway, since there is the option of HW stack bounds checking.

File: include/arch/arc/arch.h [hunk 9]
```diff
@@ -79,87 +79,78 @@ extern "C" {
...
+#else
+/*
+ * MPUv3, no-mpu and no USERSPACE share the same macro definitions.
+ * For MPU STACK_GUARD  kernel stacks do not need a MPU region to protect,
+ * only guard needs to be protected and aligned. For MPUv3,MPU_STACK_GUARD
+ * requires start 32 bytes aligned, also for size which is decided by stack
+ * array and USERSPACE; For MPUv2, MPU_STACK_GUARD requires
+ * start 2048 bytes aligned, also for size which is decided by stack array.
+ *
+ * When no-mpu and no USERSAPCE/MPU_STACK_GUARD, everything is 4 bytes
```
Comment (ruuddw) [inline include/arch/arc/arch.h]: typo: USERSAPCE -> USERSPACE

Comment (vonhust) [reply include/arch/arc/arch.h]: done
