### PR TITLE
net: mqtt: Fix possible socket leak with websocket transport

### LINKED ISSUE #75334: TLS Context is not getting release when tcp connection closed due to data retransmissions exceeded
Dear Team,

I would like to share some observations I made while working on an IoT Application using MQTT over Secure WebSocket on Zephyr 3.6.0.
Logs : 
```

[2024-06-29 08:36:28.191] [00:30:14.401,000] <dbg> net_if: net_if_tx: (tcp_work): Processing (pkt 0x240293f8, prio 0) network packet iface 0x24001a80/1
[2024-06-29 08:36:28.191] [00:30:14.402,000] <dbg> net_tcp: tcp_send_data: (tcp_work): conn: 0x2402a718 total=1610, unacked_len=1440, send_win=4266, mss=1440
[2024-06-29 08:36:28.191] [00:30:14.402,000] <dbg> net_tcp: tcp_send_data: (tcp_work): conn: 0x2402a718 send_data_timer=0, send_data_retries=8
[2024-06-29 08:36:28.205] [00:30:14.659,000] <dbg> net_tcp: tcp_resend_data: (tcp_work): send_data_retries=9
[2024-06-29 08:36:28.205] [00:30:14.659,000] <dbg> net_tcp: tcp_resend_data: (tcp_work): conn: 0x2402a718 close, data retransmissions exceeded
[2024-06-29 08:36:28.205] [00:30:14.659,000] <dbg> net_tcp: tcp_conn_close_debug: (tcp_work): conn: 0x2402a718 closed by TCP stack (tcp_resend_data():1869)
[2024-06-29 08:36:28.205] [00:30:14.659,000] <dbg> net_tcp: tcp_conn_close_debug: (tcp_work): ESTABLISHED->CLOSED
[2024-06-29 08:36:28.205] [00:30:14.659,000] <dbg> net_sock: zsock_received_cb: (tcp_work): ctx=0x24004234, pkt=(nil), st=-116, user_data=(nil)
[2024-06-29 08:36:28.205] [00:30:14.659,000] <dbg> net_sock: zsock_received_cb: (tcp_work): Marked socket 0x24004234 as peer-closed
[2024-06-29 08:36:28.205] [00:30:14.659,000] <dbg> net_tcp: tcp_conn_unref: (tcp_work): conn: 0x2402a718, ref_count=2
[2024-06-29 08:36:28.219] [00:30:14.662,000] <dbg> net_tcp: net_tcp_recv: (IoT MQTT Input Task): context: 0x24004234, cb: 0x8018591, user_data: 0x74
[2024-06-29 08:36:28.219] [00:30:14.665,000] <err> net_mqtt_rx: [CID 0x24030738]: Transport read error: -5
[2024-06-29 08:36:28.219] [00:30:14.665,000] <inf> net_mqtt_websocket: Closing socket 5
[2024-06-29 08:36:28.219] [00:30:14.666,000] <dbg> net_tcp: net_tcp_recv: (IoT MQTT Input Task): context: 0x24004234, cb: 0x8018591, user_data: 0x74
[2024-06-29 08:36:28.219] [00:30:14.669,000] <err> net_websocket: [0x24003620] Failed to send close message (err -113).
[2024-06-29 08:36:28.219] [00:30:14.669,000] <err> net_mqtt_websocket: Websocket disconnect failed (-1)
[2024-06-29 08:36:28.457] [00:30:14.669,000] <inf> net_mqtt_sock_tls: Closing socket 3

```
During the process, I noticed that the underlying TCP connection failed when it exceeded the retransmission limit. Subsequently, the WebSocket was expected to close with the underlying TLS connection.

In Zephyr 3.6.0, the following code is executed to close the MQTT connection with the underlying WebSocket and TLS connection:

int mqtt_client_websocket_disconnect(struct mqtt_client *client)
{
    int ret;
    NET_INFO("Closing socket %d", client->transport.websocket.sock);
    ret = websocket_disconnect(client->transport.websocket.sock);

    if (ret < 0) {
        NET_ERR("Websocket disconnect failed (%d)", ret);
        return ret;
    }
    if (client->transport.type == MQTT_TRANSPORT_NON_SECURE_WEBSOCKET) {
        ret = mqtt_client_tcp_disconnect(client);
    }
#if defined(CONFIG_MQTT_LIB_TLS)
    else if (client->transport.type == MQTT_TRANSPORT_SECURE_WEBSOCKET) {
        ret = mqtt_client_tls_disconnect(client);
    }
#endif
    return ret;
}

The function websocket_disconnect leads to close => websocket_internal_disconnect => websocket_send_msg. Here, websocket_send_msg attempts to send WEBSOCKET_OPCODE_CLOSE on an already closed TCP connection, which is expected to fail. Consequently, the entire call stack fails.

ret = websocket_send_msg(ctx->sock, NULL, 0, WEBSOCKET_OPCODE_CLOSE,
                 true, true, SYS_FOREVER_MS);

As a result, mqtt_client_websocket_disconnect does not release (or disconnect) the TLS socket (tls_context).

When comparing the same flow in Zephyr 3.2.0, the call stack is as follows:

tls_release() at sockets_tls.c:465 0x8019d24
ztls_close_ctx() at sockets_tls.c:2,016 0x8052292
close() at fdtable.c:275 0x801735e
websocket_internal_disconnect() at websocket.c:418 0x80557a0
websocket_close_vmeth() at websocket.c:430 0x80557a0
close() at fdtable.c:275 0x801735e
websocket_disconnect() at websocket.c:405 0x80557c6
mqtt_client_websocket_disconnect() at mqtt_transport_websocket.c:171 0x80245a2
client_disconnect() at mqtt.c:54 0x8024072

In this case, tls_context is released as expected.

In Zephyr 3.6.0, if we call mqtt_client_tls_disconnect(client);, it will close and release tls_context.

My question is, do we really need the following code in Zephyr 3.6.0 in the function mqtt_client_websocket_disconnect()?

if (ret < 0) {
    NET_ERR("Websocket disconnect failed (%d)", ret);
    return ret;
}

I would appreciate any assistance on this matter.

Best Regards.

### PR DESCRIPTION
**Pull request by rlubos**
In case underlying TCP/TLS connection is already down, the websocket_disconnect() call is expected to fail, as it involves communication. Therefore, mqtt_client_websocket_disconnect() should not quit early in such cases, as it could lead to an underlying socket leak.

Fixes #75334

### CODE REVIEW

File: subsys/net/lib/mqtt/mqtt_transport_websocket.c [hunk 1]
```diff
@@ -174,8 +174,7 @@ int mqtt_client_websocket_disconnect(struct mqtt_client *client)
 
 	ret = websocket_disconnect(client->transport.websocket.sock);
 	if (ret < 0) {
-		NET_ERR("Websocket disconnect failed (%d)", ret);
-		return ret;
+		NET_DBG("Websocket disconnect failed (%d)", ret);
```
Comment (pdgendt) [inline subsys/net/lib/mqtt/mqtt_transport_websocket.c:177]: This can change the return value, which can now become `0`. Is this an issue?

**Review by pdgendt — APPROVED** [review]

File: subsys/net/lib/mqtt/mqtt_transport_websocket.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/lib/mqtt/mqtt_transport_websocket.c:177]: Not really, the only consequence is that we won't get redundant log in case `websocket_disconnect()` fails. The ultimate goal of the function is to close the underlying socket so I think it's ok to return 0 if that succeeds.

**Review by jukkar — APPROVED** [review]
