### PR TITLE
soc: arm: st_stm32: stm32f0: take into account SW_VECTOR_RELAY

### LINKED ISSUE #28289: tests: arch: arm: arm_sw_vector_relay: fails on nucleo_f091rc
**Describe the bug**
tests: arch: arm: arm_sw_vector_relay: fails on nucleo_f091rc

**To Reproduce**
1. west -p auto -b nucleo_f091rc tests/arch/arm/arm_sw_vector_relay/
2. west flash
3. See error

**Expected behavior**
Test passed

**Logs and console output**
```
*** Booting Zephyr OS build v2.4.0-rc1-22-gf60a11368632  ***
Running test suite arm_sw_vector_relay
===================================================================
START - test_arm_sw_vector_relay

    Assertion failed at WEST_TOPDIR/zephyr/tests/arch/arm/arm_sw_vector_relay/src/arm_sw_vector_relay.c:64: test_arm_sw_vector_relay: (_vector_table_pointer == (uint32_t)_vector_start is false)
vector table pointer not pointing to vector start, 0xffffffff, 0x80000bc

 FAIL - test_arm_sw_vector_relay
===================================================================
Test suite arm_sw_vector_relay failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS:  Linux, and Windows
 - Toolchain Zephyr SDK
 - Commit SHA: d6fa062a7d3fe322dd50d4e4371f49b6283a0185

### PR DESCRIPTION
**Pull request by ABOSTM**
soc: arm: st_stm32: stm32f0: take into account SW_VECTOR_RELAY

This STM32 serie redefines function relocate_vector_table()
It should take into account features:
SW_VECTOR_RELAY and SW_VECTOR_RELAY_CLIENT

fixes #28289

Signed-off-by: Alexandre Bourdiol <alexandre.bourdiol@st.com>

### CODE REVIEW

**Review by ioannisg — CHANGES_REQUESTED** [review]
Thanks for the PR @ABOSTM 
There's an issue with SW_VECTOR_RELAY_CLIENT, though: currently it is blocked for STM32F0, because it has a dependency on ! CONFIG_CORTEX_M0_HAS_VECTOR_TABLE_REMAP. This needs to be updated.

You can cherry-pick the commit from #28403 and amend it to further remove the relevant dependency in SW_VECTOR_RELAY_CLIENT.

File: soc/arm/st_stm32/stm32f0/soc.c [hunk 1]
```diff
@@ -36,7 +39,9 @@
  */
 void relocate_vector_table(void)
 {
-#ifndef CONFIG_IS_BOOTLOADER
+#if defined(CONFIG_SW_VECTOR_RELAY) || defined(CONFIG_SW_VECTOR_RELAY_CLIENT)
+	_vector_table_pointer = _vector_start;
+#elif !defined(CONFIG_IS_BOOTLOADER)
```
Comment (b0661) [inline soc/arm/st_stm32/stm32f0/soc.c:44]: I assume this fails in case the application is started by a bootloader and and the application sets CONFIG_SW_VECTOR_.... In this scenario the vector table in use is the vector table in FLASH from the bootloader. The vector table of the application (also in FLASH) is just not used.

Comment (ioannisg) [reply soc/arm/st_stm32/stm32f0/soc.c:44]: SW_VECTOR_RELAY is an option to be used by bootloaders; we specify this is the Kconfig definition.
SW_VECTOR_RELAY_CLIENT shall only be used on images that are booted by a bootloader which has been built using SW_VECTOR_RELAY; we also specify this.

So, right, in your scenario the application will fail but this is really a misuse of the feature.

Comment (b0661) [reply soc/arm/st_stm32/stm32f0/soc.c:44]: Thanks for the explanation. Didn´t know that.  

> So, right, in your scenario the application will fail but this is really a misuse of the feature.

Going after your explanation the application will only fail if the bootloader did _NOT_ set CONFIG_SW_VECTOR_RELAY=y.

I think this needs some in code commenting to make the whole thing understandable.

Comment (ioannisg) [reply soc/arm/st_stm32/stm32f0/soc.c:44]: I think that the fact that having SW_VECTOR_RELAY and SW_VECTOR_RELAY_**CLIENT**, makes it intuitive that these should be used coupled with each-other. But sure, I am all up for more enhanced code commenting, either here, or in the help text of the Kconfig definitions of these options. Ur welcome to send an enhancement PR.

**Comment by ABOSTM** [comment]
> You can cherry-pick the commit from #28403 and amend it to further remove the relevant dependency in SW_VECTOR_RELAY_CLIENT.

Unfortunately I can't: when fetching your zephyr fork (ioannisg/zephyr), I get git error:
`couldn't execute "git": file name too long` 
Probably because I am working on windows which is known for such limitations.
It then fully block further my git repo. I need to remove your fork to be able to work again with git.
So I would be great if you can made the change.

**Comment by ABOSTM** [comment]
I integrated modification of #28403 in this current PR,
plus I get ride of `!CPU_CORTEX_M0_HAS_VECTOR_TABLE_REMAP dependency`.

File: arch/arm/core/aarch32/cortex_m/Kconfig [hunk 2]
```diff
@@ -281,7 +282,7 @@ config SW_VECTOR_RELAY
 config SW_VECTOR_RELAY_CLIENT
 	bool "Enable Software Vector Relay (client)"
 	default y if BOOTLOADER_MCUBOOT
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/Kconfig:284]: @ABOSTM this needs a modification. Rationale:

If you leave as is, then the feature will _always_ be `default y`, in a Cortex-M0 (without VTOR) platform, when we build an image to be loaded by MCUboot. We do not want that by default for this STM32 platform that has HW-based vector table remap mechanism. We want the feature to be available by not default.

So I propose:

config SW_VECTOR_RELAY_CLIENT
    bool "Enable Software Vector Relay (client)"
    depends on !CPU_CORTEX_M_HAS_VTOR
    default y if BOOTLOADER_MCUBOOT and !CPU_CORTEX_M0_HAS_VECTOR_TABLE_REMAP
    help

Comment (ABOSTM) [reply arch/arm/core/aarch32/cortex_m/Kconfig]: Thanks, Done.

**Review by ioannisg — APPROVED** [review]

File: soc/arm/st_stm32/stm32f0/soc.c [hunk 3]
```diff
@@ -36,7 +39,9 @@
  */
 void relocate_vector_table(void)
 {
-#ifndef CONFIG_IS_BOOTLOADER
+#if defined(CONFIG_SW_VECTOR_RELAY) || defined(CONFIG_SW_VECTOR_RELAY_CLIENT)
```
Comment (erwango) [inline soc/arm/st_stm32/stm32f0/soc.c:42]: Please also rework the above function's brief to explicit the assumptions and intentions.
I agree all symbols are documented but the addition makes it rather complex.

**Review by erwango — CHANGES_REQUESTED** [review]

**Review by b0661 — CHANGES_REQUESTED** [review]
> Please also rework the above function's brief to explicit the assumptions and intentions.

File: soc/arm/st_stm32/stm32f0/soc.c (hunk 3 above)
Comment (ABOSTM) [reply soc/arm/st_stm32/stm32f0/soc.c:47]: Done

**Review by erwango — APPROVED** [review]

**Comment by ioannisg** [comment]
@b0661 please, re-review

**Review by b0661 — APPROVED** [review]
