### PR TITLE
driver: serial: uart_stm32: Calculate suitable PRESCALER value for lpuart

### LINKED ISSUE #39608: stm32: lpuart: 9600 baudrate doesn't work
`lpuart1` won't work when it is set to 9600 baudrate on `nucleo_g0b1re` board, in fact it will not work for anything below ~15k baudrate by calculation.

image

The `LPUARTDIV` based on the formula above is ~1,706,666, which doesn't fit into a 20bit `BRR` register and was truncated into 658,091 instead after the `LPUART_BRR_MASK` mask, see pictures below.

image

image
image
image

### PR DESCRIPTION
**Pull request by ycsin**
Current driver set a fixed prescaler value for the lpuart that caused certain baudrate configurations to fail due to LPUARTDIV overflow the LPUART_BRR register.

This PR attempt to calculate a suitable PRESCALER for the selected baudrate, throws error and set the closest possible PRESCALER value if it couldn't get an optimal one.

fixes #39608

### CODE REVIEW

**Review by ABOSTM — COMMENTED** [review]
1 minor comment otherwise LGTM

**Review by ABOSTM — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -92,13 +108,45 @@ static inline void uart_stm32_set_baudrate(const struct device *dev,
...
+			 * lower than the LPUART_BRR_MIN_VALUE, that means this is the closest
+			 * we can get
+			 */
+			lpuartdiv = LPUARTDIV_CALC(clock_rate, 0, baud_rate);
+			if (lpuartdiv < LPUART_BRR_MIN_VALUE) {
+				presc_idx = 0;
+			} else {
+				presc_idx = ARRAY_SIZE(USART_PRESCALER_TAB) - 1;
+			}
+			LOG_ERR("Unable to set %s to %d", dev->name, baud_rate);
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:136]: If there is no way to find a prescaler that allows to match the expected baud rate, user needs to review his application settings. Computing an approx baudrate feels useless to me.

File: drivers/serial/uart_stm32.c [hunk 2]
```diff
@@ -92,13 +108,45 @@ static inline void uart_stm32_set_baudrate(const struct device *dev,
...
 	}
 
-
 #if HAS_LPUART_1
 	if (IS_LPUART_INSTANCE(UartInstance)) {
+		uint32_t lpuartdiv;
+#ifdef USART_PRESC_PRESCALER
+		uint8_t presc_idx;
+
+		for (presc_idx = 0; presc_idx < ARRAY_SIZE(USART_PRESCALER_TAB); presc_idx++) {
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:117]:
```suggestion
		for (presc_idx = 0; presc_idx < ARRAY_SIZE(LPUART_PRESCALER_TAB); presc_idx++) {
```

File: drivers/serial/uart_stm32.c [hunk 3]
```diff
@@ -92,13 +108,45 @@ static inline void uart_stm32_set_baudrate(const struct device *dev,
...
+			lpuartdiv = LPUARTDIV_CALC(clock_rate, presc_idx, baud_rate);
+			if (lpuartdiv >= LPUART_BRR_MIN_VALUE && lpuartdiv <= LPUART_BRR_MASK) {
+				break;
+			}
+		}
+
+		if (presc_idx == ARRAY_SIZE(USART_PRESCALER_TAB)) {
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:124]:
```suggestion
		if (presc_idx == ARRAY_SIZE(LPUART_PRESCALER_TAB)) {
```

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_stm32.c (hunk 1 above)
Comment (ycsin) [reply drivers/serial/uart_stm32.c:136]: > Computing an approx baudrate feels useless to me.

I agree

**Review by erwango — APPROVED** [review]

File: drivers/serial/uart_stm32.c [hunk 4]
```diff
@@ -92,13 +108,36 @@ static inline void uart_stm32_set_baudrate(const struct device *dev,
...
+				break;
+			}
+		}
+
+		if (i == ARRAY_SIZE(USART_PRESCALER_TAB)) {
+			LOG_ERR("Failed get a suitable PRESCALER value for %s", dev->name);
+			return;
+		}
+
+		LL_LPUART_SetPrescaler(UartInstance, i);
```
[the remark this answers is not in the document]
Comment (ycsin) [reply drivers/serial/uart_stm32.c]: > `LL_LPUART_SetPrescaler(UartInstance, LL_LPUART_PRESCALER(USART_PRESCALER_TAB[presc_idx]));`

I've tried this with a c compiler and it seems like the compiler isn't able to resolve this

[the remark this answers is not in the document]
Comment (ABOSTM) [reply drivers/serial/uart_stm32.c]: OK, so let's go for the 1st proposal, using CMSIS offset:
` (presc_idx << USART_PRESC_PRESCALER_Pos)`
I checked: currently bitfield is contiguous for all STM32 series. So proposal above is safe.

[the remark this answers is not in the document]
Comment (ycsin) [reply drivers/serial/uart_stm32.c]: @ABOSTM could you please check if the latest patch addressed your request?

File: drivers/serial/uart_stm32.c [hunk 5]
```diff
@@ -92,13 +120,38 @@ static inline void uart_stm32_set_baudrate(const struct device *dev,
...
+				break;
+			}
+		}
+
+		if (presc_idx == ARRAY_SIZE(LPUART_PRESCALER_TAB)) {
+			LOG_ERR("Unable to set %s to %d", dev->name, baud_rate);
+			return;
+		}
+
+		presc_idx = (presc_idx << USART_PRESC_PRESCALER_Pos);
```
Comment (ABOSTM) [inline drivers/serial/uart_stm32.c:141]: I would prefer you assign the new shifted value to a new variable : 
* after shift,  it is no more an index, so presc_idx doesn't match any more
* after the shift there is no guarantee it is still an uint8_t. 

So assigning the new value to a new uint32_t variable would be better.

**Review by ABOSTM — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_stm32.c (hunk 5 above)
Comment (ycsin) [reply drivers/serial/uart_stm32.c]: fixed

**Review by ABOSTM — APPROVED** [review]
LGTM.

**Comment by ycsin** [comment]
For some reason the buildkite failed but didnt really specify which build failed, rebased and added DNM to wait for CI green

**Comment by ycsin** [comment]
Remove `DNM` as CI passed

**Review by FRASTM — APPROVED** [review]

**Comment by ycsin** [comment]
Thanks @cfriedt

**Comment by ycsin** [comment]
@cfriedt @erwango Is this eligible for backport to 2.7? Without this PR, choosing lower baudrate for the lpuart will just fail silently.

**Comment by cfriedt** [comment]
@ycsin - should be eligible and it looks like it would not have been included before the version branch was made.

@ycsin / @erwango - can either of you please test to see if the bug exists on v2.7-branch?

**Comment by ycsin** [comment]
> @ycsin - should be eligible and it looks like it would not have been included before the version branch was made.
> 
> @ycsin / @erwango - can either of you please test to see if the bug exists on v2.7-branch?

It should, I'm on 2.7 RC3
