### PR TITLE
drivers: serial: uart_emul: support interrupt-driven receive

### LINKED ISSUE #63415: drivers: uart_emul: unable to connect to console
**Describe the bug**
The `uart_emul` driver currently does not support being picked as the `zephyr,console` device because it silently fails at runtime. This is a slight improvement from before #63000 was merged, because in that case, it would just get stuck in an infinite loop, which is a _different_ and technically worse kind of silently failing at runtime.

An "unspoken" requirement for the Zephyr console is that it the underlying UART device must support interrupt-enabled receive. The `uart_emul` driver does not.

While using `uart_emul` as a zephyr console is likely an unusual choice, it has some advantages in that it allows us to perform testing at the ZTest level in C. Writing ZTests in C allows for a far greater breadth and depth of tests above the twister console test harness level.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? any
 - What have you tried to diagnose or workaround this issue? found the root cause and fixed the issue
 - Is this a regression? No, it was just not part of the initial implementation.
 - ...

**To Reproduce**
1. run the test added in #62998 without the associated `uart_emul.c` changes.
2. See error

**Expected behavior**
Tests should pass. The `uart_emul` driver should be usable by other OS facilities more or less as if it were a fully featured uart.

There are likely other improvements to be made for `uart_emul`, eventually, but for now, this enables a sufficient amount of functionality, and gets development unstuck.

**Impact**
It's a showstopper at the moment because having functional tests should be a strong requirement for PRs relating to core Zephyr components like this (i.e. `zephyr,console`). Additionally, switching between `uart_emul` and the regular console device is the only convenient method for me to provide verifiable results that the changes in #62998 work, aside from running on custom silicon.

**Logs and console output**
Note: console output stops because the test in question has failed.
```shell
west build -p auto -b qemu_riscv64 -t run tests/drivers/console_switching
-- west build: running target run
[0/1] To exit from QEMU enter: 'CTRL+a, x'[QEMU] CPU: riscv64
*** Booting Zephyr OS build zephyr-v3.4.0-4277-gae0d63471be1 ***
Running TESTSUITE console_switching
===================================================================
START - test_read


```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Linux
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK v0.16.1
 - Commit SHA or Version used: 927f09c1b62849e04624609b70528dd2f9394f7e

**Additional context**

### PR DESCRIPTION
**Pull request by cfriedt**
Previously, the uart_emul device did not support interrupt-driven receive, which is an unwritten requirement for hooking up a uart to the Zephyr console driver.

The console is a fairly high-traffic "device" and we should be able to perform more extensive testing on it. There were few options aside from matching twister output against a regular expression. With this change, we can use the emulation uart within the body of a ZTest.

Testing Done:
```shell
west build -p auto -b qemu_riscv64 -t run tests/drivers/console_switching
...
*** Booting Zephyr OS build zephyr-v3.4.0-4277-gae0d63471be1 ***
Running TESTSUITE console_switching
===================================================================
START - test_read
read "Hello, uart_emul0!" from uart_emul0
read "Hello, uart_emul1!" from uart_emul1
read "Hello, uart_emul0!" from uart_emul0
read "Hello, uart_emul1!" from uart_emul1
 PASS - test_read in 0.005 seconds
===================================================================
START - test_write
wrote "Hello, uart_emul0!" to uart_emul0
wrote "Hello, uart_emul1!" to uart_emul1
wrote "Hello, uart_emul0!" to uart_emul0
wrote "Hello, uart_emul1!" to uart_emul1
 PASS - test_write in 0.003 seconds
===================================================================
TESTSUITE console_switching succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [console_switching]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.008 seconds
 - PASS - [console_switching.test_read] duration = 0.005 seconds
 - PASS - [console_switching.test_write] duration = 0.003 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

Fixes #63415

### CODE REVIEW

**Comment by cfriedt** [comment]
* truncated a line in the commit message  to avoid `37: UC4 Commit message body line exceeds max length (106>75): "SUITE PASS - 100.00% [console_switching]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.008 seconds"`

File: drivers/serial/uart_emul.c [hunk 1]
```diff
@@ -31,8 +38,15 @@ struct uart_emul_data {
...
 	struct ring_buf *tx_rb;
 	struct k_spinlock tx_lock;
+
+	bool irq_en;
+	struct uart_emul_work irq_work;
+	uart_irq_callback_user_data_t irq_cb;
+	void *irq_cb_user_data;
 };
 
+static void uart_emul_irq_handler(struct k_work *work);
```
Comment (dcpleung) [inline drivers/serial/uart_emul.c:48]: I don't see it being used before the actual implementation. So remove this.

**Review by dcpleung — COMMENTED** [review]
I think the additions can be wrapped around `CONFIG_UART_INTERRUPT_DRIVER` to minimize footprint.

**Comment by cfriedt** [comment]
* switch from `IF_ENABLED()` to `#ifdef`
* make private API implementation `static`

**Comment by cfriedt** [comment]
retested
```
*** Booting Zephyr OS build v3.5.0-rc1-38-g3e24c7ed6548 ***
Running TESTSUITE console_switching
===================================================================
START - test_read
read "Hello, uart_emul0!" from uart_emul0
read "Hello, uart_emul1!" from uart_emul1
read "Hello, uart_emul0!" from uart_emul0
read "Hello, uart_emul1!" from uart_emul1
 PASS - test_read in 0.005 seconds
===================================================================
START - test_write
wrote "Hello, uart_emul0!" to uart_emul0
wrote "Hello, uart_emul1!" to uart_emul1
wrote "Hello, uart_emul0!" to uart_emul0
wrote "Hello, uart_emul1!" to uart_emul1
 PASS - test_write in 0.003 seconds
===================================================================
TESTSUITE console_switching succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [console_switching]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.008 seconds
 - PASS - [console_switching.test_read] duration = 0.005 seconds
 - PASS - [console_switching.test_write] duration = 0.003 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Review by dcpleung — DISMISSED** [review]

File: drivers/serial/uart_emul.c [hunk 2]
```diff
@@ -99,14 +113,108 @@ int uart_emul_config_get(const struct device *dev, struct uart_config *cfg)
...
+	}
+
+	return ret;
+}
+
+static int uart_emul_irq_rx_ready(const struct device *dev)
+{
+	struct uart_emul_data *data = dev->data;
+
+	if (!data->irq_en) {
```
Comment (nick-kraus) [inline drivers/serial/uart_emul.c:139]: This will return 1 even when there is no data in the ring buffer, which violates the uart.h API description of the function: 'Check if UART RX buffer has at least one pending character (i.e. uart_fifo_read() will succeed and return non-zero)'.

**Review by nick-kraus — COMMENTED** [review]
I had just made a [similar change](https://github.com/nick-kraus/zephyr/commit/5d2a4e4378b21921649c3c7573d81bc99e60d0f5) to the UART emul driver when I noticed this pull request on the main repo. I have some code relying on the interrupt UART API and was going to use the emulation driver for testing.

I added one comment, but also wanted to mention that when building with this commit I got a Kconfig error saying UART_INTERRUPT_DRIVEN got the value 'n' because of unsatisfied dependencies. I believe that adding `select SERIAL_SUPPORT_INTERRUPT` to the Kconfig.emul file is the appropriate fix.

**Comment by cfriedt** [comment]
> I had just made a [similar change](https://github.com/nick-kraus/zephyr/commit/5d2a4e4378b21921649c3c7573d81bc99e60d0f5) to the UART emul driver when I noticed this pull request on the main repo. I have some code relying on the interrupt UART API and was going to use the emulation driver for testing.

Cool - I see that you've added interrupt driven transmit too. That's great - would it be reasonable to add it after this?

This was originally part of #62998 and I moved it to a separate PR to narrow the scope of the other one.

> I added one comment, but also wanted to mention that when building with this commit I got a Kconfig error saying UART_INTERRUPT_DRIVEN got the value 'n' because of unsatisfied dependencies. I believe that adding `select SERIAL_SUPPORT_INTERRUPT` to the Kconfig.emul file is the appropriate fix.

Good catch, thanks.  I'll add it.

File: drivers/serial/uart_emul.c (hunk 2 above)
Comment (cfriedt) [reply drivers/serial/uart_emul.c:139]: Fixed!

**Comment by nick-kraus** [comment]
> Cool - I see that you've added interrupt driven transmit too. That's great - would it be reasonable to add it after this?

Yeah I think its useful to add. My version was simply synchronous calls so I can change it to use the work queue, I'd be happy to do that work once this PR lands.

I'd like to add the bit about uart error handling if you're amenable as well, helps me test some additional code paths. Once again for after this PR is merged in.

File: drivers/serial/uart_emul.c (hunk 2 above)
Comment (cfriedt) [reply drivers/serial/uart_emul.c:139]: Fixed!

**Review by nick-kraus — APPROVED** [review]

**Review by ycsin — DISMISSED** [review]

File: drivers/serial/uart_emul.c [hunk 3]
```diff
@@ -31,9 +38,16 @@ struct uart_emul_data {
 
 	struct ring_buf *tx_rb;
 	struct k_spinlock tx_lock;
+
+#ifdef CONFIG_UART_INTERRUPT_DRIVEN
+	bool irq_en;
```
Comment (faxe1008) [inline drivers/serial/uart_emul.c:43]: Considering that there is a change on the horizon introducing interrupt driven transmit maybe rename to `rx_irq_en`?

File: drivers/serial/uart_emul.c [hunk 4]
```diff
@@ -127,6 +235,15 @@ uint32_t uart_emul_put_rx_data(const struct device *dev, uint8_t *data, size_t s
 	key = k_spin_lock(&drv_data->rx_lock);
 	count = ring_buf_put(drv_data->rx_rb, data, size);
 	k_spin_unlock(&drv_data->rx_lock, key);
+
+#ifdef CONFIG_UART_INTERRUPT_DRIVEN
+	if (count > 0 && drv_data->irq_en) {
+		if (!ring_buf_is_empty(drv_data->rx_rb)) {
```
Comment (faxe1008) [inline drivers/serial/uart_emul.c:241]: Does not the check here also need to be spinlock protected?

File: drivers/serial/uart_emul.c [hunk 5]
```diff
@@ -168,6 +285,20 @@ uint32_t uart_emul_flush_tx_data(const struct device *dev)
 	return count;
 }
 
+static int uart_emul_init(const struct device *dev)
+{
+	ARG_UNUSED(dev);
```
Comment (faxe1008) [inline drivers/serial/uart_emul.c:290]: Just for my own curiosity: The compilers that I tried with did not complain at all. Is this a common accepted pattern in zephyr to avoid a ton of macro branching?

File: drivers/serial/uart_emul.c (hunk 3 above)
Comment (cfriedt) [reply drivers/serial/uart_emul.c]: Fixed!

**Review by ycsin — APPROVED** [review]

**Review by faxe1008 — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by kartben** [comment]
Hey @cfriedt, I think we are in feature freeze right now :)
@jhedberg @fabiobaltieri

**Comment by cfriedt** [comment]
> Hey @cfriedt, I think we are in feature freeze right now :)
> @jhedberg @fabiobaltieri 

Sure - there are no samples being added here.

**Comment by kartben** [comment]
Right but this definitely sounds to me like it's more than "stabilization and cosmetic changes, bug and doc fixes".
In any case, this should have probably followed the minimum review period of 2 days.

**Comment by jhedberg** [comment]
> Sure - there are no samples being added here.

As the name suggests, feature freeze is primarily about stopping to add new features into the tree. Anyway, this PR is marked as fixing a bug, so in that respect it qualifies for merging.

**Comment by cfriedt** [comment]
> Right but this definitely sounds to me like it's more than "stabilization and cosmetic changes, bug and doc fixes".

This was used to diagnose and fix an infinite loop in an isr (#63000) that was a problem in just about every Zephyr device in existence. #63000 was split from #62998 to make code easier to review.

#62998 itself is used to improve diagnostics and system remediation on devices that serve billions of people every day.

> In any case, this should have probably followed the minimum review period of 2 days.

Technically speaking, this code has already been already under review for 2 weeks. This was split from #62998 to make code easier to review.

I appreciate your concern, but these were far from a cosmetic changes.
