### PR TITLE
tests: kernel: cpu_exception: Make expected reason code generic.

### LINKED ISSUE #54335: tests/kernel/fatal/no-multithreading/kernel.no-mt.cpu_exception failing on qemu_cortex_m3
**Describe the bug**
The testcase kernel.no-mt.cpu_exception fails on qemu_cortex_m3

**To Reproduce**
twister -W -vvv -p qemu_cortex_m3 -T tests/kernel/fatal/no-multithreading/

**Expected behavior**
Passing testcase

**Impact**
Failing testcase

**Logs and console output**
```Running TESTSUITE fatal_no_mt
===================================================================
START - test_fatal
cpu exception
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x0000000e  r1/a2:  0x0000000a  r2/a3:  0x90000000
E: r3/a4:  0x20000c3c r12/ip:  0x00000043 r14/lr:  0x000003d7
E:  xpsr:  0x40000000
E: Faulting instruction address (r15/pc): 0x20000c3c
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: (nil) (unknown)
Caught system error -- reason 0
Unexpected reason (exp: 35)
===================================================================
RunID: fe85d68e207c79fb1fd8a25f70d0e1c2
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.15.2
 - Commit SHA: `60a20471b561a0a3a74b377991fe1976c2ea83d7`

### PR DESCRIPTION
**Pull request by aasthagr**
Change expected reason code for cpu exception to be generic and in compliance with a3774fd51a716ffafeddfb017f9c25a046013132

Fixes #54335

Signed-off-by: Aastha Grover <aastha.grover@intel.com>

### CODE REVIEW

File: tests/kernel/fatal/no-multithreading/src/main.c [hunk 1]
```diff
@@ -30,7 +30,7 @@ void k_sys_fatal_error_handler(unsigned int reason, const z_arch_esf_t *pEsf)
 static void entry_cpu_exception(void)
 {
 #if defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
-	expected_reason = K_ERR_ARM_USAGE_ILLEGAL_EPSR;
+	expected_reason = K_ERR_CPU_EXCEPTION;
```
Comment (dcpleung) [inline tests/kernel/fatal/no-multithreading/src/main.c:33]: You can just remove the whole `#if` since both are the same.

**Review by dcpleung — CHANGES_REQUESTED** [review]

File: tests/kernel/fatal/no-multithreading/src/main.c (hunk 1 above)
Comment (aasthagr) [reply tests/kernel/fatal/no-multithreading/src/main.c:32]: Makes sense completely.Done.

**Review by dcpleung — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
@andyross Could you take a quick look at this PR?

**Review by andyross — APPROVED** [review]
Seems obviously correct, though I'm likewise confused how the earlier PR managed to break this without being caught before merge?

**Review by JordanYates — APPROVED** [review]

**Comment by aasthagr** [comment]
> Seems obviously correct, though I'm likewise confused how the earlier PR managed to break this without being caught before merge?

Probably coz filtering of testcases in CI is quite strict. Maybe we need to expand the scope of test plan?
