### PR TITLE
drivers: i2c: nrfx: Fix log level is ignored

### LINKED ISSUE #18085: I2C log level ignored
**Describe the bug**
Can't turn off logging for i2c driver (i2c_nrfx_twi.c) even if the CONFIG_I2C_LOG_LEVEL_OFF is set (and CONFIG_I2C_LOG_LEVEL=0).

According to this note for LOG_MODULE_REGISTER
`@note The module's state is defined, and the module is registered,
       only if LOG_LEVEL for the current source file is non-zero or
       it is not defined and CONFIG_LOG_DEFAULT_LEVEL is non-zero.
       In other cases, this macro has no effect.`

and this lines from i2c_nrfx_twi.c
`#define LOG_LEVEL CONFIG_I2C_LOG_LEVEL
#include <logging/log.h>
LOG_MODULE_REGISTER(i2c_nrfx_twi);`

macro should not register this file and no logs should be printed.

**Environment (please complete the following information):**
 - OS: Linux
 - Commit SHA or Version used - zephyr-v1.14.0-2943-g8e9bf88d66

### PR DESCRIPTION
**Pull request by creiter32**
Fixes the problem that the log level set in Kconfig is ignored.

Signed-off-by: Christoph Reiter <christoph.reiter@infineon.com>

NOTE: git blame points to this commit https://github.com/zephyrproject-rtos/zephyr/commit/f7dac85d15fbecaa5736a1c4cb807a6c8b5e8afe as last chaninging the lines so other drivers may be affected too.

Closes #18085.

### CODE REVIEW

**Review by nordic-krch — APPROVED** [review]

File: drivers/i2c/i2c_nrfx_twi.c [hunk 1]
```diff
@@ -9,9 +9,8 @@
 #include <dt-bindings/i2c/i2c.h>
 #include <nrfx_twi.h>
 
-#define LOG_LEVEL CONFIG_I2C_LOG_LEVEL
 #include <logging/log.h>
-LOG_MODULE_REGISTER(i2c_nrfx_twi);
+LOG_MODULE_REGISTER(i2c_nrfx_twi, CONFIG_I2C_LOG_LEVEL);
```
Comment (anangl) [inline drivers/i2c/i2c_nrfx_twi.c:13]: Would you mind adding a corresponding fix for `i2c_nrfx_twim.c` to this commit?

**Comment by anangl** [comment]
Closes #18085.

**Review by anangl — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by pabigot** [comment]
Is anybody going to undertake to change the 315 in-tree files that use the same legacy idiom and presumably have the same problem?  Or was this truly isolated to I2C for NRFX for some reason?
