### PR TITLE
ext: silabs: rename ramfunc section to match Zephyr's

### LINKED ISSUE #13192: silabs flash_gecko driver warning (will fail in CI)
Reproduce by:

```
cd samples/drivers/flash_shell/
mkdir build
cd build/
cmake -DBOARD=efr32mg_sltb004a ..
make
```

output is:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:       45740 B         1 MB      4.36%
            SRAM:       11708 B       256 KB      4.47%
        IDT_LIST:          88 B         2 KB      4.30%
/opt/zephyr-sdk-0.9.5/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-zephyr-eabi/gcc/arm-zephyr-eabi/6.2.0/real-ld: warning: orphan section `.ram' from `libzephyr.a(em_msc.c.obj)' being placed in section `.ram'.
```

### PR DESCRIPTION
**Pull request by mnkp**
Functions which have to be located in RAM are placed by SiLabs library code in section '.ram'. Corresponding section used by Zephyr is called '.ramfunc'. This patch renames SiLabs section name to match Zephyr's.

This solution was chosen over adding '.ram' function to Zephyr linker scripts not to pollute them. However, this patch needs to be reapplied every time SiLabs library version is updated.

Fixes #13192

### CODE REVIEW

File: ext/hal/silabs/gecko/emlib/inc/em_ramfunc.h [hunk 1]
```diff
@@ -143,7 +143,7 @@ extern "C" {
 
 #elif defined(__GNUC__)
 /* Simplicity Studio, Atollic and Vanilla armgcc */
-#define SL_RAMFUNC_DECLARATOR          __attribute__ ((section(".ram")))
+#define SL_RAMFUNC_DECLARATOR          __attribute__ ((section(".ramfunc")))
```
Comment (mnkp) [inline ext/hal/silabs/gecko/emlib/inc/em_ramfunc.h]: I preserved the method used by SiLabs to keep modifications to minimum. Zephyr is using a different approach: `__attribute__((long_call, section(".ramfunc")))`. Without the `long_call` keyword the linker will create the so called veneers in case the range of the branch instruction is insufficient. With the `long_call` keyword compiler will always use the long jump. BL instruction on processors that support Thumb-2 technology has a range of 16MB.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by nashif — APPROVED** [review]
