### PR TITLE
usb: mass_storage: cleanup, fixes to pass USBCV MSC Test

### LINKED ISSUE #14302: USB MSC fails USB3CV tests
**Describe the bug**
USB mass storage sample with RAM disk fails USB3CV (#11803) MSC specific tests:
- [x] Error Recovery
- [x] Case 3
- [x] Case 12
- [x] CB Length
- [x] Command Set

**To Reproduce**
Flash `mass` sample with RAM overlay to nrf52840_pca10056.

**Expected behavior**
USB3CV MSC tests pass.

**Impact**
No immediate impact, but this has to be solved before MSC class is considered ready.

**Screenshots or console output**
Three unique errors are thrown in tests:

1. Error Recovery
```
Issuing required command (Test Unit Ready) to verify device has recovered
Issuing CBW (attempt #1):
|----- CBW LUN                  = 0x0
|----- CBW Flags                = 0x0
|----- CBW Data Transfer Length = 0x0
|----- CBW CDB Length           = 0x6
|----- CBW CDB-00 = 0x0
|----- CBW CDB-01 = 0x0
|----- CBW CDB-02 = 0x0
|----- CBW CDB-03 = 0x0
|----- CBW CDB-04 = 0x0
|----- CBW CDB-05 = 0x0
Issuing CSW : try 1
CSW Bulk Request timed out!

ERROR
Failed CSW phase : should have been success or stall
FAIL
(5.3.4) The CSW status value must be 0x00, 0x01, or 0x02.

Re-enumerating device
Detected hard error, issuing BOT MSC Reset

ERROR
Failed to execute required command (Test Unit Ready) after BOT MSC Reset
FAIL
(5.7.2) All devices must either support or properly fail the commands marked 
 as optional in 4.2 based on PDT. Devices that support or properly fail all the commands 
 marked as optional for Bootable devices will be reported as Bootable.
```

2. Case 3, Case 12, CB Length, Command Set:
```
Issuing INQUIRY
Issuing CBW (attempt #1):
|----- CBW LUN                  = 0x0
|----- CBW Flags                = 0x80
|----- CBW Data Transfer Length = 0x24
|----- CBW CDB Length           = 0x6
|----- CBW CDB-00 = 0x12
|----- CBW CDB-01 = 0x0
|----- CBW CDB-02 = 0x0
|----- CBW CDB-03 = 0x0
|----- CBW CDB-04 = 0x24
|----- CBW CDB-05 = 0x0
Issuing DATA IN
DATA Bulk Request timed out!

ERROR
Failed DATA phase : should have been success or stall!
FAIL
(5.2.3) Devices must consider the CBW meaningful if no reserved bits 
 are set, the LUN number indicates a LUN supported by the device, 
 bCBWCBLength is in the range of 1 through 16, and the length and 
 content of the CBWCB field are appropriate to the SubClass.

Re-enumerating device
Detected hard error, issuing BOT MSC Reset

ERROR
Failed INQUIRY request
FAIL
(5.7.1) All devices must support the commands marked as required in 4.2 based 
 on PDT. Devices that support all the commands marked as required for Bootable devices will 
 be reported as Bootable.
```

3. Command Set:
```
Issuing Command Set Test for Op Code 0x12, Test Variation #3
Issuing CBW (attempt #1):
|----- CBW LUN                  = 0x0
|----- CBW Flags                = 0x80
|----- CBW Data Transfer Length = 0x2
|----- CBW CDB Length           = 0x6
|----- CBW CDB-00 = 0x12
|----- CBW CDB-01 = 0x0
|----- CBW CDB-02 = 0x0
|----- CBW CDB-03 = 0x0
|----- CBW CDB-04 = 0x2
|----- CBW CDB-05 = 0x0
Issuing DATA IN
DATA Bulk Request timed out!

ERROR
Failed DATA phase : should have been success or stall!

FAIL
(5.2.3) Devices must consider the CBW meaningful if no reserved bits 
 are set, the LUN number indicates a LUN supported by the device, 
 bCBWCBLength is in the range of 1 through 16, and the length and 
 content of the CBWCB field are appropriate to the SubClass.

ERROR
READ CAPACITY(10) not supported.
```

**Environment (please complete the following information):**
 - OS: Windows x64 7 Professional SP1
 - PC: Dell Optiplex 9020
 - DK: nrf52840_pca10056
 - Toolchain: Zephyr SDK 0.9.5
 - Zephyr b87920bf3c789ad4eeebb749d9a06ae72f15d589

### PR DESCRIPTION
**Pull request by jfischer-no**
usb: mass_storage: cleanup, fixes to pass USBCV MSC Test

drivers: usb_dc_nrfx: always reset data toggle in usb_dc_ep_enable 
  Data toggle should be reset after SetConfiguration or SetInterface request.
  Always reset data toggle in usb_dc_ep_enable.
  (fixes Case x from #14302 issue)

usb: mass_storage:
  Use sys_get_be32, sys_put_be32 where possible.
  Check dCBWDataTransferLength for every read command.
   (fixes Command Set Test #14302 issue)

cherry-picked from #23188 and #23191 and tested on nRF52840
resolves #14302 for nRF driver

There is more to do but I wanted to have it passes MSC Tests first.

### CODE REVIEW

**Comment by nordic-auko** [comment]
Tested on nRF52840 on windows 10. No issues seen.

**Review by nordic-auko — APPROVED** [review]

**Review by finikorg — APPROVED** [review]
LGTM

File: subsys/usb/class/mass_storage.c [hunk 1]
```diff
@@ -491,6 +491,11 @@ static bool infoTransfer(void)
 
 static void fail(void)
 {
+	if (cbw.DataLength) {
+		/* Stall data stage */
+		usb_ep_set_stall(mass_ep_data[MSD_IN_EP_IDX].ep_addr);
+	}
+
```
Comment (emob-nordic) [inline subsys/usb/class/mass_storage.c]: Why this approach now? That was literally the case You mentioned before, endpoint is stalled and there is attempt to send the data over stalled endpoint.

File: subsys/usb/class/mass_storage.c [hunk 2]
```diff
@@ -422,10 +422,26 @@ static void memoryRead(void)
 	}
 }
 
+static bool check_cbw_data_length(void)
+{
+	if (!cbw.DataLength) {
+		LOG_WRN("Zero length in CBW");
+		csw.Status = CSW_FAILED;
```
Comment (emob-nordic) [inline subsys/usb/class/mass_storage.c]: call fail() instead?
Probably could also be in lines: [451](https://github.com/zephyrproject-rtos/zephyr/pull/23307/commits/7fdcdd8d2eec497231d0ba0f35cd19d91f448f23#diff-7726e7e0e855220e1de8c888a9b06c4eR451), [484](https://github.com/zephyrproject-rtos/zephyr/pull/23307/commits/7fdcdd8d2eec497231d0ba0f35cd19d91f448f23#diff-7726e7e0e855220e1de8c888a9b06c4eR484)

**Review by eobalski — COMMENTED** [review]
Should we close #23191 ?

File: drivers/usb/device/usb_dc_nrfx.c [hunk 3]
```diff
@@ -1573,6 +1573,7 @@ int usb_dc_ep_enable(const u8_t ep)
 		return -EINVAL;
 	}
 
+	nrfx_usbd_ep_dtoggle_clear(ep_addr_to_nrfx(ep));
```
[the remark this answers is not in the document]
Comment (jfischer-phytec-iot) [reply drivers/usb/device/usb_dc_nrfx.c]: No, toggle bit should be cleared every time regardless endpoint is configured or not.

File: subsys/usb/class/mass_storage.c (hunk 1 above)
Comment (jfischer-phytec-iot) [reply subsys/usb/class/mass_storage.c]: Because it follows the exiting practice in the code, see also https://github.com/zephyrproject-rtos/zephyr/pull/23191#discussion_r388332142, and did not found a detailed definition of endpoint state after clear halt. I tested it for one day before I opened PR. I am also still working on mass_storage.c and will open an other cleanup PR.

File: subsys/usb/class/mass_storage.c (hunk 2 above)
Comment (jfischer-phytec-iot) [reply subsys/usb/class/mass_storage.c]: Well this is explicitly for the case `Zero length in CBW` and I wanted not to mix it with the `fail()`.

**Comment by jfischer-phytec-iot** [comment]
> Should we close #23191 ?

generally, no. As I know github will rebase/handle it very well.
