### PR TITLE
drivers/sensor: lps25hb: Fix int32 overflow in the val2 part

### LINKED ISSUE #46615: drivers: lps25hb driver returning wrong fractional part of a pressure
During my work with lps25hb pressure sensor I have faced problem that fractional part of the measurement is completely wrong. During debug I figured out that we are probably overflowing `int32_t` range during computations in this function:
lps25hb_problem
Since this sensor is returning 24 bit wide result - when we multiply it million times - it will clearly overflow.

So my local solution for now is:
suggested_change
To give compiler the idea that we need 64 bit value in order to proceed with calculations. As far as I have tested it - it works like a charm.

What do you guys think? Is it a good solution? Should I create a pull request for that?

### PR DESCRIPTION
**Pull request by avisconti**
The val2 calculation was done using (1000000 / 40960) as multiplying factor, which was sometimes leading to a int32 overflow. So, let's use the equivalent (but smaller) (3125 / 128).

Fix #46615
Mimic what already done in #38090 (c3050a5aa)

### CODE REVIEW

**Review by MaureenHelm — APPROVED** [review]

File: drivers/sensor/st/lps25hb/lps25hb.c [hunk 1]
```diff
@@ -69,9 +69,14 @@ static int lps25hb_sample_fetch(const struct device *dev,
...
-	/* val = raw_val / 40960 */
+	/* Pressure sensitivity is 4096 LSB/hPa */
+	/* Also convert hPa into kPa */
 	val->val1 = raw_val / 40960;
-	val->val2 = ((int32_t)raw_val * 1000000 / 40960) % 1000000;
+
+	/* For the decimal part use (3125 / 128) as a factor instead of
+	 * (1000000 / 40960) to avoid int32 overflow
+	 */
+	val->val2 = (raw_val % 40960) * 3125 / 128;
```
Comment (ubieda) [inline drivers/sensor/st/lps25hb/lps25hb.c:79]: Should the modulo operator be applied after the scaling factor?

Comment (avisconti) [reply drivers/sensor/st/lps25hb/lps25hb.c:79]: No, no. First you calculate the rest of the division, then apply the proper scaling factor.

**Review by ubieda — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
