### PR TITLE
disk: sdmmc: support L4 series with shared DMA channel

### LINKED ISSUE #91216: disk: sdmmc_stm32: compilation failures on L4 with DMA
### Describe the bug

Attempting to compile the `sdmmc_stm32` on STM32L4's with DMA support results in compilation errors.
The DMA support in the file is hardcoded for one particular SoC family (F4 based on 6076991f).
This looks to be due to manually using HAL DMA functions, rather than the common DMA abstraction (like `spi_ll_stm32.c` for example).

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell
/home/jordan/code/workspace/zephyr/drivers/disk/sdmmc_stm32.c:217:44: warning: implicit declaration of function '__LL_DMA_GET_STREAM_INSTANCE' [-Wimplicit-function-declaration]
  217 |         handle->Instance                 = __LL_DMA_GET_STREAM_INSTANCE(dma->reg, dma->channel_nb);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jordan/code/workspace/zephyr/drivers/disk/sdmmc_stm32.c:217:42: warning: assignment to 'DMA_Channel_TypeDef *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  217 |         handle->Instance                 = __LL_DMA_GET_STREAM_INSTANCE(dma->reg, dma->channel_nb);
      |                                          ^
/home/jordan/code/workspace/zephyr/drivers/disk/sdmmc_stm32.c:218:21: error: 'DMA_InitTypeDef' has no member named 'Channel'
  218 |         handle->Init.Channel             = dma->cfg.dma_slot * DMA_CHANNEL_1;
      |                     ^
/home/jordan/code/workspace/zephyr/drivers/disk/sdmmc_stm32.c:218:64: error: 'DMA_CHANNEL_1' undeclared (first use in this function); did you mean 'DAC_CHANNEL_1'?
  218 |         handle->Init.Channel             = dma->cfg.dma_slot * DMA_CHANNEL_1;
      |                                                                ^~~~~~~~~~~~~
      |                                                                DAC_CHANNEL_1
/home/jordan/code/workspace/zephyr/drivers/disk/sdmmc_stm32.c:218:64: note: each undeclared identifier is reported only once for each function it appears in
/home/jordan/code/workspace/zephyr/drivers/disk/sdmmc_stm32.c:223:44: error: 'DMA_PFCTRL' undeclared (first use in this function)
  223 |         handle->Init.Mode                = DMA_PFCTRL;
...
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

 - Zephyr v4.1

### Additional Context

Example devicetree configuration:
```
&sdmmc1 {
	status = "okay";
	pinctrl-0 = <&sdmmc1_d0_pc8 &sdmmc1_d1_pc9 &sdmmc1_d2_pc10
		&sdmmc1_d3_pc11 &sdmmc1_ck_pc12 &sdmmc1_cmd_pd2>;
	pinctrl-names = "default";
	cd-gpios = <&gpioc 7 GPIO_ACTIVE_LOW>;
	pwr-gpios = <&gpiob 5 GPIO_ACTIVE_HIGH>;
	disk-name = "SD";
	bus-width = <4>;
	clk-div = <4>;

	dmas = <&dma2 4 1 (STM32_DMA_PERIPH_TX | STM32_DMA_PRIORITY_HIGH)>,
		<&dma2 5 1 (STM32_DMA_PERIPH_RX | STM32_DMA_PRIORITY_HIGH)>;
	dma-names = "tx", "rx";
};
```

### PR DESCRIPTION
**Pull request by JordanYates**
Update the driver to support DMA operations on L4 series devices, with
a shared DMA channel. Split channels do not work on these chips, since
there is no dedicated TX and RX channels on the DMA, so configuring two
channels with SDMMC as the peripheral results in a non-functional
configuration.

Fixes #91216.

### CODE REVIEW

**Comment by JordanYates** [comment]
Code has been tested on a custom STM32L451RE design, successfully writing, reading-back and erasing a random block, returning to low power idle when done.

File: drivers/disk/sdmmc_stm32.c [hunk 1]
```diff
@@ -457,6 +513,12 @@ static int stm32_sdmmc_access_write(struct disk_info *disk,
 
 	k_sem_take(&priv->thread_lock, K_FOREVER);
 
+#ifdef STM32_SDMMC_USE_DMA_SHARED
+	/* Initialise the shared DMA channel for the current direction */
+	priv->dma_txrx_handle.Init.Direction = LL_DMA_DIRECTION_MEMORY_TO_PERIPH;
+	err = HAL_DMA_Init(&priv->dma_txrx_handle);
```
Comment (etienne-lms) [inline drivers/disk/sdmmc_stm32.c]:
```suggestion
	if (HAL_DMA_Init(&priv->dma_txrx_handle) != HAL_OK) {
		err = -EIO;
		goto end;
	}

File: tests/drivers/disk/disk_access/boards/stm32l496g_disco_stm32l496xx.overlay [hunk 2]
```diff
@@ -0,0 +1,7 @@
+/* SPDX-License-Identifier: Apache-2.0 */
+
+&sdmmc1 {
+	/* Channel 5 request 7 on DMA2 */
+	dmas = <&dma2 5 7 (STM32_DMA_PRIORITY_HIGH)>;
```
Comment (etienne-lms) [inline tests/drivers/disk/disk_access/boards/stm32l496g_disco_stm32l496xx.overlay]: Could remove parentheses. Ditto in *dts/bindings/mmc/st,stm32-sdmmc.yaml*

File: drivers/disk/sdmmc_stm32.c [hunk 3]
```diff
@@ -410,6 +462,10 @@ static int stm32_sdmmc_access_read(struct disk_info *disk, uint8_t *data_buf,
 
 	k_sem_take(&priv->sync, K_FOREVER);
 
+#ifdef STM32_SDMMC_USE_DMA_SHARED
+	HAL_DMA_DeInit(&priv->dma_txrx_handle);
```
Comment (etienne-lms) [inline drivers/disk/sdmmc_stm32.c:470]: This makes `dma_stop()` being called (from `stm32_sdmmc_dma_deinit()`) after `HAL_DMA_DeInit()`. It is ok?

File: drivers/disk/sdmmc_stm32.c [hunk 4]
```diff
@@ -251,13 +285,24 @@ static int stm32_sdmmc_dma_init(struct stm32_sdmmc_priv *priv)
...
 static int stm32_sdmmc_dma_deinit(struct stm32_sdmmc_priv *priv)
 {
 	int ret;
+
+#ifdef STM32_SDMMC_USE_DMA_SHARED
+	struct sdmmc_dma_stream *dma_txrx = &priv->dma_txrx;
+
+	ret = dma_stop(dma_txrx->dev, dma_txrx->channel);
+	if (ret != 0) {
+		LOG_ERR("Failed to stop tx DMA transmission");
```
Comment (etienne-lms) [inline drivers/disk/sdmmc_stm32.c]:
```suggestion
		LOG_ERR("Failed to stop txrx DMA transmission");
```
Or maybe `"Failed to stop shared DMA transmission"`

File: drivers/disk/sdmmc_stm32.c (hunk 3 above)
Comment (JordanYates) [reply drivers/disk/sdmmc_stm32.c:470]: Yes, but only because `dma_stop` doesn't actually do anything useful when `stream->hal_override == true`, which means it should just be removed all together. I will validate on hardware tomorrow and fix.

Comment (JordanYates) [reply drivers/disk/sdmmc_stm32.c:470]: Alright, it does one useful task, it marks the channel as free in the DMA subsystem.
Updated with some comments explaining.

File: drivers/disk/sdmmc_stm32.c [hunk 5]
```diff
@@ -251,29 +288,39 @@ static int stm32_sdmmc_dma_init(struct stm32_sdmmc_priv *priv)
...
+	struct sdmmc_dma_stream *dma_txrx = &priv->dma_txrx;
+
+	ret = dma_stop(dma_txrx->dev, dma_txrx->channel);
+	__ASSERT(ret == 0, "Shared DMA channel index corrupted");
+#else
 	struct sdmmc_dma_stream *dma_tx = &priv->dma_tx;
 	struct sdmmc_dma_stream *dma_rx = &priv->dma_rx;
 
 	ret = dma_stop(dma_tx->dev, dma_tx->channel);
+	__ASSERT(ret == 0, "TX DMA channel index corrupted");
```
Comment (etienne-lms) [inline drivers/disk/sdmmc_stm32.c:316]: Unless asserting the return value in debug build mode is always sufficient,  i think it would be worth:
```c
	int ret = 0;

	(...)

	if (dma_stop(dma_tx->dev, dma_tx->channel) != 0) {
		LOG_ERR("Failed to stop tx DMA transmission");		
		ret = -EIO;
	}
	HAL_DMA_DeInit(&priv->dma_tx_handle);

	if (dma_stop(dma_xx->dev, dma_rx->channel) != 0) {
		LOG_ERR("Failed to stop rx DMA transmission");		
		ret = -EIO;
	}
	HAL_DMA_DeInit(&priv->dma_rx_handle);
#endif

	return ret;		
}

**Review by danieldegrasse — DISMISSED** [review]

**Comment by danieldegrasse** [comment]
@etienne-lms can you revisit?

File: drivers/disk/sdmmc_stm32.c [hunk 6]
```diff
@@ -87,11 +89,16 @@ struct stm32_sdmmc_priv {
 	const struct reset_dt_spec reset;
 
 #if STM32_SDMMC_USE_DMA
+#ifdef STM32_SDMMC_USE_DMA_SHARED
```
Comment (etienne-lms) [inline drivers/disk/sdmmc_stm32.c]:
```suggestion
#if STM32_SDMMC_USE_DMA_SHARED
```

File: drivers/disk/sdmmc_stm32.c [hunk 7]
```diff
@@ -236,6 +264,15 @@ static int stm32_sdmmc_dma_init(struct stm32_sdmmc_priv *priv)
 
 	LOG_DBG("using dma");
 
+#ifdef STM32_SDMMC_USE_DMA_SHARED
```
Comment (etienne-lms) [inline drivers/disk/sdmmc_stm32.c]:
```suggestion
#if STM32_SDMMC_USE_DMA_SHARED
```
etc...

**Review by etienne-lms — CHANGES_REQUESTED** [review]
Main issue (IIUC) is all occurrences of `#ifdef STM32_SDMMC_USE_DMA_SHARED` to replace with `#if STM32_SDMMC_USE_DMA_SHARED` in **drivers/disk/sdmmc_stm32.c**.

**(edited: sorry for this late feedback)**

File: drivers/disk/sdmmc_stm32.c (hunk 6 above)
Comment (JordanYates) [reply drivers/disk/sdmmc_stm32.c]: Fixed

File: drivers/disk/sdmmc_stm32.c (hunk 5 above)
Comment (JordanYates) [reply drivers/disk/sdmmc_stm32.c:316]: It is an assertion because there is no code path that results in an error through that function unless RAM is corrupted.
```
	if (id >= config->max_streams) {
		return -EINVAL;
	}

	if (stream->hal_override) {
		stream->busy = false;
		return 0;
	}
```
If ID is invalid in the normal case the setup functions will already error out with log messages.
If we're trying to protect against RAM corruption, there are many other problems...

Comment (etienne-lms) [reply drivers/disk/sdmmc_stm32.c:316]: OK

**Review by etienne-lms — APPROVED** [review]

**Review by etienne-lms — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]
