### PR TITLE
net: conn_mgr: sntp: logging: backend: net: extend usage

### LINKED ISSUE #89643: logging backebd: net: dhcp: CONFIG_NET_IPV4_ACD leads to lots of warnings
**Describe the bug**
When `CONFIG_NET_IPV4_ACD` is activated together with:
```
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_DHCPV4=y

CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_NET=y
CONFIG_LOG_BACKEND_NET_USE_DHCPV4_OPTION=y
CONFIG_POSIX_C_LANG_SUPPORT_R=y
```

and the server for the logging backend net (syslog) is set via the dhcp option during boot
a lot of warnings are generated at boot (see log output). 

Behavior is similar, when the ethernet cable is disconnected and then connected again.

This is because the log backend net gets activated before having a valid ipv4 address assinged. ACD leads to the ip address not being valid until it had been checked.

**To Reproduce**
1. add the following options to the `prj.conf` of the hawkbit sample:
```
CONFIG_NET_IPV4_ACD=y
CONFIG_NET_LOG=y

# Enable Syslog
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_NET=y
CONFIG_LOG_BACKEND_NET_USE_DHCPV4_OPTION=y
CONFIG_POSIX_C_LANG_SUPPORT_R=y

CONFIG_NET_CONFIG_LOG_LEVEL_DBG=y
```

2. set the dhcpv4 option for the log server in your dhcpv4 server
3. west build -p -b stm32h573i_dk samples/subsys/mgmt/hawkbit -- -DCONF_FILE="prj.conf overlay-runtime.conf" && west flash
4. see see logs via uart

**Expected behavior**
no warnings

**Impact**
lots of warnings

**Logs and console output**
```
[1970-01-01 00:00:00.445,000] <inf> phy_mii: PHY (0) ID 7C131
*** Booting Zephyr OS build v4.1.0-3648-g9204ae54e77e ***
[1970-01-01 00:00:00.447,000] <inf> net_config: Initializing network
[1970-01-01 00:00:00.447,000] <inf> net_config: Waiting interface 1 (0x20001000) to be up...
[1970-01-01 00:00:04.948,000] <inf> phy_mii: PHY (0) Link speed 100 Mb, full duplex
[1970-01-01 00:00:04.948,000] <inf> net_config: Interface 1 (0x20001000) coming up
[1970-01-01 00:00:04.948,000] <inf> net_config: Running dhcpv4 client...
[1970-01-01 00:00:13.015,000] <inf> net_dhcpv4: Received: 10.102.66.11
[1970-01-01 00:00:13.015,000] <inf> net_config: IPv4 address: 10.102.66.11
[1970-01-01 00:00:13.015,000] <inf> net_config: Lease time: 4000 seconds
[1970-01-01 00:00:13.015,000] <inf> net_config: Subnet: 255.255.255.0
[1970-01-01 00:00:13.015,000] <inf> net_config: Router: 0.0.0.0
[1970-01-01 00:00:14.015,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.015,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.015,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.015,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.015,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.015,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.015,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.015,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.016,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.024,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.024,000] <wrn> net_ctx: DROP: src addr is unspecified
[1970-01-01 00:00:14.033,000] <wrn> net_ctx: DROP: src addr is unspecified
....
```

**Environment (please complete the following information):**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by maass-hamburg**
log backend net:
- When used when used with CONFIG_NET_IPV4_ACD and CONFIG_LOG_BACKEND_NET_USE_DHCPV4_OPTION a lot of warnings about dropped packages are generated, this fixes it. When used with the connection manager it is completely fixed, without it just at startup.
- can now use the connection manager to enable and disable the backend

net config init sntp:
- add option to use the connection manager

connection manager:
- set to unstable as it is used by multiple parts in zephyr and numerous samples

Fixes: #89643

### CODE REVIEW

File: subsys/net/lib/config/init.c [hunk 1]
```diff
@@ -553,17 +553,8 @@ int net_config_init_app(const struct device *dev, const char *app_info)
...
 	 * and running before syslog messages can be sent to network.
 	 */
-	if (IS_ENABLED(CONFIG_LOG_BACKEND_NET) &&
-	    IS_ENABLED(CONFIG_LOG_BACKEND_NET_AUTOSTART)) {
-		const struct log_backend *backend = log_backend_net_get();
-
-		if (!log_backend_is_active(backend)) {
-			if (backend->api->init != NULL) {
-				backend->api->init(backend);
-			}
```
Comment (jukkar) [inline subsys/net/lib/config/init.c:563]: I think the idea here was that if the logging is not yet initialized, we need to do it here.

File: subsys/logging/backends/log_backend_net.c [hunk 2]
```diff
@@ -338,9 +338,18 @@ static void panic(struct log_backend const *const backend)
 	panic_mode = true;
```
Comment (jukkar) [inline subsys/logging/backends/log_backend_net.c:339]: Typo in commit `logging: backend: net: avoid automatic enabling`
s/fixis/fixes/
s/than/then/
Also please start sentences with capital letters

File: subsys/net/lib/config/init.c [hunk 3]
```diff
@@ -553,17 +553,8 @@ int net_config_init_app(const struct device *dev, const char *app_info)
 	/* This is activated late as it requires the network stack to be up
```
Comment (jukkar) [inline subsys/net/lib/config/init.c:554]: Typo in commit `net: config: init: remove second init of syslog`
s/durring/during/

File: subsys/net/lib/dhcpv4/dhcpv4.c [hunk 4]
```diff
@@ -1200,9 +1200,10 @@ static bool dhcpv4_parse_options(struct net_pkt *pkt,
 			log_server.sin_family = AF_INET;
 			log_backend_net_set_ip((struct sockaddr *)&log_server);
 
-#ifdef CONFIG_LOG_BACKEND_NET_AUTOSTART
-			log_backend_net_start();
-#endif
+			if (IS_ENABLED(CONFIG_LOG_BACKEND_NET_AUTOSTART) &&
+			    !IS_ENABLED(CONFIG_NET_CONFIG_SETTINGS)) {
+				log_backend_net_start();
+			}
```
Comment (jukkar) [inline subsys/net/lib/dhcpv4/dhcpv4.c]: Not sure how this is related to "avoiding automatic enabling"
Is there now two separate changes in this commit, one for automatic enabling and one for ACD?

File: include/zephyr/net/conn_mgr_connectivity.h [hunk 5]
```diff
@@ -26,7 +26,7 @@ extern "C" {
  * @brief Connection Manager Connectivity API
```
Comment (jukkar) [inline include/zephyr/net/conn_mgr_connectivity.h:26]: For the commit `net: conn_mgr: set to unstable`, please add information to commit msg why this change is needed.

File: subsys/net/lib/config/init.c (hunk 1 above)
Comment (maass-hamburg) [reply subsys/net/lib/config/init.c:563]: this is part of the https://github.com/zephyrproject-rtos/zephyr/pull/89275. When CONFIG_LOG_BACKEND_NET_AUTOSTART is enabled, than the log backend net has the autostart flag set and will be automatically init by the logging subsystem

File: subsys/logging/backends/log_backend_net.c (hunk 2 above)
Comment (maass-hamburg) [reply subsys/logging/backends/log_backend_net.c:339]: done

File: subsys/net/lib/dhcpv4/dhcpv4.c (hunk 4 above)
Comment (maass-hamburg) [reply subsys/net/lib/dhcpv4/dhcpv4.c]: split the commit in two.

File: include/zephyr/net/conn_mgr_connectivity.h (hunk 5 above)
Comment (maass-hamburg) [reply include/zephyr/net/conn_mgr_connectivity.h:26]: done

**Review by rlubos — APPROVED** [review]

**Comment by maass-hamburg** [comment]
ping @jukkar

**Review by jukkar — APPROVED** [review]
