### PR TITLE
Fix Coverity Issues

### LINKED ISSUE #7712: [Coverity CID :186063] Null pointer dereferences in /subsys/disk/disk_access.c
Static code scan issues seen in File: /subsys/disk/disk_access.c
 Category: Null pointer dereferences
 Function: disk_access_ioctl
 Component: Other
 CID: 186063
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #7716: [Coverity CID :186058] Null pointer dereferences in /tests/kernel/fifo/fifo_timeout/src/main.c
Static code scan issues seen in File: /tests/kernel/fifo/fifo_timeout/src/main.c
 Category: Null pointer dereferences
 Function: test_multiple_threads_get_data
 Component: Tests
 CID: 186058
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #7718: [Coverity CID :186056] Null pointer dereferences in /subsys/disk/disk_access.c
Static code scan issues seen in File: /subsys/disk/disk_access.c
 Category: Null pointer dereferences
 Function: disk_access_write
 Component: Other
 CID: 186056
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #7726: [Coverity CID :186045] Null pointer dereferences in /subsys/disk/disk_access.c
Static code scan issues seen in File: /subsys/disk/disk_access.c
 Category: Null pointer dereferences
 Function: disk_access_status
 Component: Other
 CID: 186045
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #7728: [Coverity CID :186043] Incorrect expression in /tests/posix/fs/src/test_fs_dir.c
Static code scan issues seen in File: /tests/posix/fs/src/test_fs_dir.c
 Category: Incorrect expression
 Function: test_lsdir
 Component: Tests
 CID: 186043
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #7731: [Coverity CID :186040] Resource leaks in /tests/posix/fs/src/test_fs_dir.c
Static code scan issues seen in File: /tests/posix/fs/src/test_fs_dir.c
 Category: Resource leaks
 Function: test_lsdir
 Component: Tests
 CID: 186040
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #7740: [Coverity CID :186029] Null pointer dereferences in /subsys/disk/disk_access.c
Static code scan issues seen in File: /subsys/disk/disk_access.c
 Category: Null pointer dereferences
 Function: disk_access_read
 Component: Other
 CID: 186029
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #7742: [Coverity CID :186027] Null pointer dereferences in /subsys/disk/disk_access.c
Static code scan issues seen in File: /subsys/disk/disk_access.c
 Category: Null pointer dereferences
 Function: disk_access_init
 Component: Other
 CID: 186027
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by ramakrishnapallala**
Fixes #7742 
Fixes #7740 
Fixes #7726 
Fixes #7718 
Fixes #7712 
Fixes #7731 
Fixes #7728
Fixes #7716

### CODE REVIEW

**Review by spoorthik — COMMENTED** [review]
Just for my understanding, can you please share the issue reported?

File: subsys/disk/disk_access.c [hunk 1]
```diff
@@ -57,7 +57,7 @@ int disk_access_init(const char *pdrv)
 	struct disk_info *disk = disk_access_get_di(pdrv);
 	int rc = -EINVAL;
 
-	if ((disk != NULL) || (disk->ops != NULL) ||
+	if ((disk != NULL) && (disk->ops != NULL) &&
```
Comment (lpereira) [inline subsys/disk/disk_access.c]: Ooh, good one.

**Review by lpereira — APPROVED** [review]

**Review by nashif — APPROVED** [review]
