### PR TITLE
intel_adsp: bbzero/bmemcpy with picolibc fix

### LINKED ISSUE #54224: Issues with picolibc on xtensa platforms
**Describe the bug**
On CAVS 15, 18 and 25 tests/posix/ fails.

**To Reproduce**
Build and run test on CAVS 15, 18 or 25. Twister options given in our CI:
```
-W --hardware-map ../../cavs/cavs.map --device-testing -x=CONFIG_BOOT_DELAY=500 -T tests/posix/ -v --no-skipped-report
```

**Expected behavior**
Passes.

**Impact**
Annoyance.

**Logs and console output**
```
INFO    - 1) tests/posix/eventfd_basic/portability.posix.eventfd_basic.picolibc on intel_adsp_cavs18 error (No Console Output(Timeout))
INFO    - 2) tests/posix/eventfd_basic/portability.posix.eventfd_basic.picolibc.posix_api on intel_adsp_cavs18 error (No Console Output(Timeout))
INFO    - 3) tests/posix/fs/portability.posix.fs.picolibc on intel_adsp_cavs18 error (No Console Output(Timeout))
INFO    - 4) tests/posix/fs/portability.posix.fs.tls.picolibc on intel_adsp_cavs18 error (No Console Output(Timeout))
INFO    - 5) tests/posix/common/portability.posix.common.picolibc on intel_adsp_cavs18 error (No Console Output(Timeout))
INFO    - 6) tests/posix/getopt/portability.posix.getopt.picolibc on intel_adsp_cavs18 error (No Console Output(Timeout))
```

**Environment (please complete the following information):**
 - OS: Linux
 - Zephyr SDK
 - [https://github.com/zephyrproject-rtos/zephyr/commit/ef9d5bbddfa53ac5636437df8c4e720aaff974d5](url)

### PR DESCRIPTION
**Pull request by teburd**
When building with picolibc and gcc, the loops to do zeroing/copying get replaced by gcc with calls to memset/memcpy. This fails this early in the boot process and results in an illegal instruction exception.

Marking the variables being manipulated in the calls as volatile prevents the compiler from optimizing the loops (replacing them with memset/memcpy).

Fixes #54224 for me

Signed-off-by: Tom Burdick <thomas.burdick@intel.com>

### CODE REVIEW

**Review by nashif — DISMISSED** [review]

**Review by stephanosio — DISMISSED** [review]

**Review by tmleman — DISMISSED** [review]

**Review by jxstelter — DISMISSED** [review]

**Review by softwarecki — DISMISSED** [review]

File: soc/xtensa/intel_adsp/common/include/soc.h [hunk 1]
```diff
@@ -69,11 +69,11 @@ static ALWAYS_INLINE void z_idelay(int n)
...
 static ALWAYS_INLINE void bmemcpy(void *dest, void *src, size_t bytes)
 {
-	uint32_t *d = (uint32_t *)dest;
-	uint32_t *s = (uint32_t *)src;
+	volatile uint32_t *d = (uint32_t *)dest;
+	volatile uint32_t *s = (uint32_t *)src;
 
 	z_xtensa_cache_inv(src, bytes);
-	for (size_t i = 0; i < (bytes >> 2); i++)
+	for (volatile size_t i = 0; i < (bytes >> 2); i++)
```
Comment (keith-packard) [inline soc/xtensa/intel_adsp/common/include/soc.h:76]: You don't need the volatile attribute on the loop index, it's sufficient to use volatile on the pointers.

File: soc/xtensa/intel_adsp/common/include/soc.h [hunk 2]
```diff
@@ -82,9 +82,9 @@ static ALWAYS_INLINE void bmemcpy(void *dest, void *src, size_t bytes)
 /* bzero used by bootloader */
 static ALWAYS_INLINE void bbzero(void *dest, size_t bytes)
 {
-	uint32_t *d = (uint32_t *)dest;
+	volatile uint32_t *d = (uint32_t *)dest;
 
-	for (size_t i = 0; i < (bytes >> 2); i++)
+	for (volatile size_t i = 0; i < (bytes >> 2); i++)
 		d[i] = 0;
```
Comment (keith-packard) [inline soc/xtensa/intel_adsp/common/include/soc.h:88]: Same here -- no need for the volatile attribute on the loop index.

**Review by keith-packard — DISMISSED** [review]

File: soc/xtensa/intel_adsp/common/include/soc.h (hunk 1 above)
Comment (keith-packard) [reply soc/xtensa/intel_adsp/common/include/soc.h:76]: It's not required; the code is just less optimal.

**Review by nashif — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
