### PR TITLE
Bluetooth: host: Add RPA in directed advertisement support

### LINKED ISSUE #14743: Directed advertising to Android does not work
**Describe the bug**
I bond the device with various host and then use direct advertising to reconnect.
I am able to connect to Windows 7 with Intel drivers and Windows 10. I am also able to connect to Nordic dongle (pca10059) though Zephyr's option scan with identity must be enabled.

I am unable to connect (using the direct advertising) to an Android devices. I have tried Samsung Galaxy S8 (Android 9.0) and Moto G5 (Android 8.1.0).

Maybe the problem is how these device perform scanning?

**To Reproduce**
See description.

**Expected behavior**
Direct advertising should work.

**Impact**
showstopper

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
ncs zephyr: e7a0e5263fb5081d548e69a823bf622cf23b83b6 (19de7ec upstream)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by joerchan**
In order to advertise directed to a privacy enabled central the
initiator field of the directed adv packet needs to set to an RPA.
To instruct the controller to use an RPA in the initiator field own
address type should be set to either 0x02 or 0x03.
Since it is not certain that a remote device supports address resolution
of the initiator address we add an option to turn this on and give the
application the responsibility to check if peer supports this.

Fixes #14743

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -5345,6 +5344,17 @@ int bt_le_adv_start_internal(const struct bt_le_adv_param *param,
 			}
 
 			bt_addr_le_copy(&set_param.direct_addr, peer);
+
+			if (IS_ENABLED(CONFIG_BT_SMP) &&
+			    !IS_ENABLED(CONFIG_BT_PRIVACY) &&
+			    BT_FEAT_LE_PRIVACY(bt_dev.le.features) &&
+			    param->options & BT_LE_ADV_OPT_DIR_ADDR_RPA) {
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: put parentheses around (foo & bar) to make it clear that you didn't intend to use &&

File: subsys/bluetooth/host/settings.c [hunk 2]
```diff
@@ -180,12 +180,6 @@ static int set(int argc, char **argv, void *value_ctx)
 	return 0;
 }
 
-#if defined(CONFIG_BT_PRIVACY)
-#define ID_SIZE_MAX sizeof(bt_dev.irk)
-#else
-#define ID_SIZE_MAX sizeof(bt_dev.id_addr)
-#endif
```
Comment (jhedberg) [inline subsys/bluetooth/host/settings.c]: This doesn't seem related, and it was actually removed by one of my own PRs recently.

**Review by jhedberg — CHANGES_REQUESTED** [review]

**Comment by jhedberg** [comment]
There's something I don't understand here. The HCI spec says the following about values 0x02 and 0x03 for the `Own_Address_Type` parameter:
"
0x02 Controller generates the Resolvable Private Address based on the local IRK from the resolving list. If the resolving list contains no matching entry, use the public address.

0x03 Controller generates the Resolvable Private Address based on the local IRK from the resolving list. If the resolving list contains no matching entry, use the random address from LE_Set_Advertising_Set_Random_Address.
"

Now, as you say we don't have a local IRK, so based on the above our behaviour should be exactly the same as if 0x00 or 0x01 would have been given, right? So why do we go through the trouble to say 0x02 or 0x03 when we know the controller will fall back to just normal public/random address?

Another thing that's bothering me is that it should be abundantly clear what API features are workarounds for broken devices (which seems to be the case here - please correct me if I'm wrong), however it's not at all clear from the public API additions. To me the text you've added in the API sounds like this is normal behaviour for privacy-enabled centrals. Am I misunderstanding something here?

File: include/bluetooth/bluetooth.h [hunk 3]
```diff
@@ -277,6 +277,16 @@ enum {
...
 	 */
 	BT_LE_ADV_OPT_DIR_MODE_LOW_DUTY = BIT(4),
+
+	/** Enable use of Private Resolvable Address in directed advertisements
+	 *  when CONFIG_BT_PRIVACY is not enabled.
+	 *  This is required if the remote device is privacy enabled and
+	 *  supports address resolution of directed advertisement.
+	 *  It is the responsibility of the application to check that the remote
+	 *  device supports address resolution of directed advertisements by
+	 *  reading it's Central Address Resolution characteristic.
```
Comment (carlescufi) [inline include/bluetooth/bluetooth.h]: *its

File: include/bluetooth/bluetooth.h [hunk 4]
```diff
@@ -277,6 +277,16 @@ enum {
 	 *  bt_conn_create_slave_le().
 	 */
 	BT_LE_ADV_OPT_DIR_MODE_LOW_DUTY = BIT(4),
+
+	/** Enable use of Private Resolvable Address in directed advertisements
+	 *  when CONFIG_BT_PRIVACY is not enabled.
+	 *  This is required if the remote device is privacy enabled and
```
Comment (carlescufi) [inline include/bluetooth/bluetooth.h]: privacy-enabled

File: include/bluetooth/bluetooth.h [hunk 5]
```diff
@@ -277,6 +277,16 @@ enum {
 	 *  bt_conn_create_slave_le().
 	 */
 	BT_LE_ADV_OPT_DIR_MODE_LOW_DUTY = BIT(4),
+
+	/** Enable use of Private Resolvable Address in directed advertisements
```
Comment (carlescufi) [inline include/bluetooth/bluetooth.h]: *Resolvable Private Address (RPA)
Please specify that this only affects InitA/TgtA and *not* AdvA

**Review by carlescufi — CHANGES_REQUESTED** [review]
Looks good, just doc issues

**Comment by jhedberg** [comment]
@joerchan for the record, @carlescufi helped clarify the situation with own_addr_type and the peer_addr being linked even when we don't have a local IRK. I.e. 0x02/0x03 is not quite the same as 0x00/0x01 when we don't have an IRK ourselves. The requested clarifications by @carlescufi are helpful in this regard.

**Review by carlescufi — APPROVED** [review]
LGTM now, thanks!

File: include/bluetooth/bluetooth.h (hunk 3 above)
Comment (jhedberg) [reply include/bluetooth/bluetooth.h]: @joerchan this doesn't seem to be fixed yet?

**Review by jhedberg — APPROVED** [review]
Besides the typo that's not yet fixed this PR is fine with me
