### PR TITLE
net: sockets: Make sure that getaddrinfo() cannot hang forever

### LINKED ISSUE #15197: Socket-based DNS API will hang device if DNS query is not answered
**Describe the bug**
Using the socket-based DNS query APIs located here: 
If a query is generated and sent, but never returned, the Zephyr device will stay in that state forever.

The cause of this is the K_FOREVER here and a bit lower (in the IPV6 code): The whole reason I started investigating this, is that an actual DNS query sent via the Socket-based APIs which is never returned by the server will hang the Zephyr device. We have an edge gateway setup where containers are loaded which handle NAT64, DNS64, joining BLE 6lowpan devices as well as OpenThread. This issue was identified when the DNS64 container spins up a bit later than the BLE joiner. The perfect example of this would be when the gateway software is updated and it requires a restart, but the IoT nodes are up and running at the time.

The K_FOREVER semaphore taken here and a bit lower are the cause of the hang: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/sockets/getaddrinfo.c#L119

**To Reproduce**
This is harder to reproduce with native Zephyr samples, because most of them do not use the Socket-based APIs for DNS, and if they do use them, they are natively setup for running in QEMU which has no routing behavior and requires modification for actual networking hardware like FRDM-K64F, etc.

**Expected behavior**
Device should never hang forever.  Pick an expected timeout time and let's generate a timeout so the caller of the DNS function can decide how to react.

**Impact**
Any device using the socket-based APIs for DNS can be easily hung if the UDP packet for the DNS query is lost, etc.  Also if DNS entry is not correct, developer will never get any notification other than an unresponsive device.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Toolchain: Zephyr SDK 0.10.0
 - Commit SHA: https://github.com/zephyrproject-rtos/zephyr/commit/0734b4fcaaea62e5f887d932a79b31507d61429d

### PR DESCRIPTION
**Pull request by jukkar**
If for some reason the DNS resolver callback is not called properly
then make sure that semaphore will not block forever.

Fixes #15197

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by jukkar** [comment]
@mike-scott please try and report if this fixes the issue you are seeing.

**Comment by mike-scott** [comment]
@jukkar thanks will test

**Comment by mike-scott** [comment]
Initial test shows me:
```
[4] [2019-04-05 09:08:38] LwM2M registration
[4] [2019-04-05 09:08:38] [00:00:33.332,427] \x1b[0m<inf> net_lwm2m_rd_client: LWM2M Client: mike-bt:sn:9e0172e3\x1b[0m
[4] [2019-04-05 09:08:38] [00:00:33.332,427] \x1b[0m<inf> fota_lwm2m: setup complete.\x1b[0m
[4] [2019-04-05 09:08:39] [00:00:34.069,274] \x1b[0m<inf> net_lwm2m_rd_client: RD Client started with endpoint 'mike-bt:sn:9e0172e3' with client lifetime 30\x1b[0m
[4] [2019-04-05 09:08:41] [00:00:36.174,804] \x1b[1;31m<err> net_lwm2m_engine: Unable to resolve address\x1b[0m
[4] [2019-04-05 09:08:41] [00:00:36.174,804] \x1b[1;31m<err> net_lwm2m_rd_client: Cannot init LWM2M engine (-2)\x1b[0m
[4] [2019-04-05 09:08:41] ***** BUS FAULT *****
[4] [2019-04-05 09:08:41]   Imprecise data bus error
[4] [2019-04-05 09:08:41] ***** Hardware exception *****
[4] [2019-04-05 09:08:41] Current thread ID = 0x20004c08
[4] [2019-04-05 09:08:41] Faulting instruction address = 0x25d28
[4] [2019-04-05 09:08:41] Fatal fault in thread 0x20004c08! Aborting.
```
and
```
$ $ZEPHYR_SDK_INSTALL_DIR/arm-zephyr-eabi/bin/arm-zephyr-eabi-addr2line -e build/dm-lwm2m-96b_nitrogen/zephyr/zephyr.elf 0x25d28
zephyr/include/misc/dlist.h:211
```

Reviewing the code to see what's happening.

File: subsys/net/lib/sockets/getaddrinfo.c [hunk 1]
```diff
@@ -111,43 +124,31 @@ int z_impl_z_zsock_getaddrinfo_internal(const char *host, const char *service,
...
+	if (ret == 0) {
+		/* If the DNS query for reason fails so that the
+		 * dns_resolve_cb() would not be called, then we want the
+		 * semaphore to timeout so that we will not hang forever.
+		 * So make the sem timeout longer than the DNS timeout so that
+		 * we do not need to start to cancel any pending DNS queries.
+		 */
+		int ret = k_sem_take(&ai_state.sem,
+				     CONFIG_NET_SOCKETS_DNS_TIMEOUT +
+				     K_MSEC(100));
```
Comment (mike-scott) [inline subsys/net/lib/sockets/getaddrinfo.c]: This is an issue (though not what is causing my crash).
CONFIG_NET_SOCKETS_DNS_TIMEOUT as it's passed in here is used for each resolver attempt.  We could in theory have several DNS servers defined, so this value is used several times for an overall total of:
CONFIG_NET_SOCKETS_DNS_TIMEOUT * SERVER_COUNT (DNS + MDNS servers)

**Review by mike-scott — CHANGES_REQUESTED** [review]

File: subsys/net/lib/sockets/getaddrinfo.c (hunk 1 above)
Comment (jukkar) [reply subsys/net/lib/sockets/getaddrinfo.c]: The resolver does not wait all the results from all the servers, it just waits results from at least one server. So there should be no issue here regarding this.

Comment (mike-scott) [reply subsys/net/lib/sockets/getaddrinfo.c]: You are correct.  I looked closely at the resolve.c code.  It only continues iterating through the DNS_SERVER list *if* there's a problem in dns_write().  As soon as it hits a successful return value it stops and waits for results or a timeout.

**Comment by mike-scott** [comment]
So my crash is due to using the system work queue to trigger periodic events in the LwM2M engine.

The system work queue thread priority won't be interrupted normally.  So the k_sem_take() doesn't get prempted by the query_timeout which performs the callback which calls k_sem_give() ...

I need to fix this on my end.  But these changes look good.  I tested them using a normal thread to handle periodic services.

**Comment by mike-scott** [comment]
@jukkar This PR fixes my testing of this patch: https://github.com/zephyrproject-rtos/zephyr/pull/15231/commits/01d51d38737223e771b9521e9d0b5b09d3643976

**Review by mike-scott — APPROVED** [review]
LGTM.  @pfalcon should also take a look.

**Review by pfl — APPROVED** [review]

**Comment by pfalcon** [comment]
Hello @jukkar, you broke getaddrinfo() behavior with this patch. If it's passed AF_UNSPEC, it should resolve both IPv4 and IPv6 addresses. That's why the original code has 2 calls to dns_get_addr_info(). You replaced them with 1 call, so it can't work correctly.
