### PR TITLE
Bluetooth: Fix RX thread deadlock

### LINKED ISSUE #23364: Bluetooth: bt_recv deadlock on supervision timeout with pending GATT Write Commands
**Describe the bug**
Performing GATT write commands from a peripheral as fast as possible from the main loop while the peer central is performing GATT service discovery and a supervision timeout puts the system in a deadlock.

Preliminary analysis shows the below callpath leading to the deadlock:
```
recv_thread
- bt_recv
-- hci_acl
--- bt_conn_recv
---- bt_l2cap_recv
----- l2cap_chan_recv
------ chan->ops->recv
------- bt_att_recv
-------- handler->func
--------- att_read_req
---------- bt_att_create_pdu
----------- bt_l2cap_send_cb
------------ bt_conn_send_cb
------------- conn_tx_alloc
```

The deadlock is caused by use of all `free_tx` by the below callpath:
```
bt_gatt_write_without_response_cb
- bt_att_create_pdu
- bt_att_send (with cb)
-- att_send
--- bt_l2cap_send_cb
---- bt_conn_send_cb
----- conn_tx_alloc
```

**To Reproduce**
1. Apply the attached patch to the upstream/master repo
2. mkdir build; cd build
3. cmake -GNinja -DBOARD=nrf52_pca10040 ../samples/bluetooth/peripheral
4. ninja
5. ninja flash

On a linux PC use BlueZ and hci_usb (nrf52840_pca10056) as the controller. (The issue should be reproducible using internal controller too, not tried though).

1. `bluetoothctl scan on`
2. `<ctrl-c>`
3. `bluetoothctrl connect <bdaddr of the peripheral sample>`
4. Take the peripheral device away to cause supervision timeout
5. Try few times (issue reproducible in 1 in 5 supervision timeout tries)

**Expected behavior**
Peripheral sample should gracefully disconnect with reason as supervision timeout and resume to connectable advertisements.

**Impact**
showstopper

**Screenshots or console output**
Below log is for the modified host by adding timeout in `conn_tx_alloc`
```
*** Booting Zephyr OS build v2.2.0-rc3-68-gbf8caf395646  ***
Bluetooth initialized
Advertising successfully started
Connected: e5:e0:45:33:29:e6 (random)
[00:00:00.007,354] <inf> fs_nvs: 6 Sectors of 4096 bytes
[00:00Write: count= 0, len= 0, rate= 0 bps.
:00.007,354] <inf> fs_nvs: alloc wra: 0, f70
[00:00:00.007,354] <inf> fs_nvs: data wra: 0, 124
[00:00:00.008,789] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.008,789] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
[00:00:00.008,819] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.2 Build 0
[00:00:00.009,094] <inf> bt_hci_core: No ID address. App must call settings_load()
[00:00:00.011,230] <err> settings: set-value failure. key: bt/ccc/38cada5db6360 error(-2)
[00:00:00.012,359] <inf> bt_hci_core: Identity: c1:ab:66:13:11:2e (random)
[00:00:00.012,359] <inf> bt_hci_core: HCI: version 5.1 (0x0a) revision 0x0000, manufacturer 0x05f1
[00:00:00.012,359] <inf> bt_hci_core: LMP: version 5.1 (0x0a) subver 0xffff
Write: count= 58, len= 13256, rate= 107932 bps.

D1

D0

D3

D2

D4

D5
conn_tx_alloc timeout.
Write cmd failed (-55).
conn_tx_alloc timeout.

D6

D99
Disconnected (reason 0x08)
Write cmd failed (-57).

```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: gnuarmemb gcc version 9.2.0 (Arch Repository)
 - Commit SHA or Version used: bf8caf3956

**Additional context**

Patch file: 
[0001-Peripheral-with-Write-Commands.patch.txt](https://github.com/zephyrproject-rtos/zephyr/files/4311067/0001-Peripheral-with-Write-Commands.patch.txt)

btmon log:
[btmon_recv_thread_stall.txt](https://github.com/zephyrproject-rtos/zephyr/files/4311511/btmon_recv_thread_stall.txt)

### LINKED ISSUE #26467: Bluetooth: Race-condition on persistent connectable advertiser
**Describe the bug**
Race-condition in persistent connectable advertiser, the advertiser will not resuming connectable advertiser if the last bt_conn_unref happens from something other than the disconnected callback.
An example of this happening is when the disconnect happens while application is calling bt_gatt_notify.
The  last bt_conn_unref can then be from gatt.c notify_cb called from application main thread.

**To Reproduce**
Issue was discovered while fixing https://github.com/zephyrproject-rtos/zephyr/issues/2336

From @cvinayak:
https://github.com/cvinayak/zephyr/commit/0b01ebdd559c009416458c583f122647d98d2bd1

Above branch will make it easy to reproduce (its a branch with the patch in the issue description applied).

Steps to reproduce (timing related):
1. build and flash the peripheral sample from the branch.
2. build and flash a vanilla central_hr sample in another board.
3. When central_hr connects and peripheral sample prints out `Connected: <bdaddr>`, reset the central_hr board to cause linkloss (linkloss needs to occur during service discovery).
4. peripheral sample will get stuck in conn_tx_alloc function in host/conn.c 

Reproducible in latest master too (62b985409e):
https://github.com/cvinayak/zephyr/commit/55153bed706b662018e5a07e20a7e26d4f6ed463

With the bug-fix for the deadlock in place the connectable advertiser was not restarting advertising after disconnect.

**Expected behavior**
If there are connection objects available the connectable advertiser should be advertising.

**Impact**
Advertiser not active when it should be.

**Workaround**
Stop and start the advertiser again, or use OPT_ONE_TIME and handle in application manually.

### PR DESCRIPTION
**Pull request by joerchan**
Fix host RX thread being deadlocked. The deadlock occurs because the
RX thread is stuck waiting in conn_tx_alloc with K_FOREVER but if the
connection is disconnected only the RX thread can unblock it in the
handling of the disconnect event.

Fixes this deadlock by splitting the processing of the
disconnected event into two parts.
The part needed to unblock the RX is to release resources held by
unack'ed TX packets and mark the connection state as not connected
anymore.
The RX thread waiting for free_tx fifo and the TX thread waiting for
the bt_dev.le.pkts semaphore will both check the connected state after
having acquired them and will abort if disconnected.
The rest of the processing will be handled at normal RX thread
priority like normal.

The HCI drivers need to be updated to deliver the disconnected event
from both priority and normal RX context.

Also fix an issue with the advertiser not resuming connectable
advertiser if the last bt_conn_unref happens from something other
than the disconnected callback.
In this case this last bt_conn_unref was from gatt.c notify_cb called
from application main thread.

Fixes: #23364
Fixes: #26467

### CODE REVIEW

**Comment by carlescufi** [comment]
@erwango @cvinayak @thoh-ot @alexandru-porosanu-nxp could you please test this with your respective Bluetooth platforms please? At the very least connection and disconnection multiple times, ideally with ongoing traffic.

File: subsys/bluetooth/host/conn_internal.h [hunk 1]
```diff
@@ -9,6 +9,7 @@
  */
 typedef enum __packed {
 	BT_CONN_DISCONNECTED,
+	BT_CONN_DISCONNECTED_PRIO,
```
Comment (Vudentz) [inline subsys/bluetooth/host/conn_internal.h:12]: I wonder if we coultn't just reuse BT_CONN_DISCONNECT for this, at least that would be consistent with the state when we initiate the disconnect, or we need to distinct of remote vs locally initiated?

File: subsys/bluetooth/host/conn.c [hunk 2]
```diff
@@ -1774,8 +1774,11 @@ void bt_conn_set_state(struct bt_conn *conn, bt_conn_state_t state)
 			 */
 			bt_conn_unref(conn);
 			break;
+		case BT_CONN_CONNECTED:
+		case BT_CONN_DISCONNECT:
 		case BT_CONN_DISCONNECTED:
-			/* Cannot happen, no transition. */
+			/* Cannot happen. */
+			BT_WARN("no valid (%u) old state", state);
```
Comment (Vudentz) [inline subsys/bluetooth/host/conn.c:1773]: Id replace no valid/invalid

**Comment by alexandru-porosanu-nxp** [comment]
> @erwango @cvinayak @thoh-ot @alexandru-porosanu-nxp could you please test this with your respective Bluetooth platforms please? At the very least connection and disconnection multiple times, ideally with ongoing traffic.

Yep, I can do that; I'm thinking of using peripheral_hr (VEGA) & central_hr (NRF) and hack one of them to disconnect and reconnect at about 5-10s interval. If you have a better scenario in mind, let me know and I'll try to figure out how to do it...

File: drivers/bluetooth/hci/h4.c [hunk 3]
```diff
@@ -272,6 +272,8 @@ static inline void read_payload(void)
 	}
 
 	prio = (rx.type == H4_EVT && bt_hci_evt_is_prio(rx.evt.evt));
+	normal = (rx.type == H4_ACL ||
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply drivers/bluetooth/hci/h4.c:275]: Alternative suggestion, use a recv type and demux to both bt_recv_prio and bt_recv as suitable.

```
enum bt_recv_type {
    BT_RECV_TYPE_NORMAL = 0x00,
    BT_RECV_TYPE_PRIO = 0x02,
    BT_RECV_TYPE_BOTH = 0x03
}

u8_t bt_hci_evt_recv_type(u8_t evt)
{
    switch (evt) {
    case BT_HCI_EVT_CMD_COMPLETE:
    case BT_HCI_EVT_CMD_STATUS:
        /* fallthrough */
#if defined(CONFIG_BT_CONN)
    case BT_HCI_EVT_NUM_COMPLETED_PACKETS:
    case BT_HCI_EVT_DATA_BUF_OVERFLOW:
#endif
        return BT_RECV_TYPE_PRIO;

#if !defined(CONFIG_BT_HCI_RAW)
    case BT_HCI_EVT_DISCONN_COMPLETE:
        return BT_RECV_TYPE_BOTH;
#endif
    }
    return BT_RECV_TYPE_NORMAL;
}
```

in the drivers:
```
if (rx.type == H4_EVT) {
    recv_type = bt_hci_evt_recv_type(rx.evt.evt);
} else {
    recv_type = BT_RECV_TYPE_NORMAL;
}

switch (recv_type) {
case BT_RECV_TYPE_PRIO:
    bt_recv_prio(buf);
    break;
case BT_RECV_TYPE_BOTH:
    bt_recv_prio(buf);
    /* fall through */
case BT_RECV_TYPE_NORMAL:
default:
    bt_recv(buf);
    break;
}
```

File: subsys/bluetooth/controller/hci/hci_driver.c [hunk 4]
```diff
@@ -105,6 +123,8 @@ static void prio_recv_thread(void *p1, void *p2, void *p3)
 		}
 
 		if (node_rx) {
+			bool evt_is_normal = true;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/hci/hci_driver.c:126]: Where is this assigned to false?

File: subsys/bluetooth/controller/hci/hci_driver.c [hunk 5]
```diff
@@ -113,15 +133,24 @@ static void prio_recv_thread(void *p1, void *p2, void *p3)
 			/* Find out and store the class for this node */
 			node_rx->hdr.user_meta = hci_get_class(node_rx);
 
-			buf = process_prio_evt(node_rx);
+			buf = process_prio_evt(node_rx, &evt_is_normal);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/hci/hci_driver.c:136]: returning a bt_recv_type and handling the call to bt_recv_prio or bt_recv in a switch case is cleaner.

**Review by cvinayak — DISMISSED** [review]
I believe this PR fixes the stall issue, as I can see `recv_thread` loop twice under the scenarios where applications main thread and host's thread where waiting for tx_free counts. Previously, `recv_thread` would only run with k_fifo_get in conn_tx_alloc was updated to have a timeout.

File: subsys/bluetooth/host/conn_internal.h (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/conn_internal.h:12]: For locally initiated it would be in the "DISCONNECT" already then, when receiving the HCI_DISCONNECT_COMPLETE event, so it would end up with a same state transition. `bt_conn_set_state` would return immediately in that case.

**Comment by erwango** [comment]
Testing on nucleo_wb55rg, I face an issue on disconnect (while HRM notifications are on)
`[00:00:24.124,000] <wrn> bt_hci_core: Unhandled event 0x00 len 2: 0813  `
Then, impossible to reconnect.
Works fine on master

**Comment by joerchan** [comment]
> Testing on nucleo_wb55rg, I face an issue on disconnect (while HRM notifications are on)
> `[00:00:24.124,000] <wrn> bt_hci_core: Unhandled event 0x00 len 2: 0813 `
> Then, impossible to reconnect.
> Works fine on master ([fae5d96](https://github.com/zephyrproject-rtos/zephyr/commit/fae5d96618632458e15c5c33dd81bb860126ad1b))
> 
> EDIT: I'm seeing the same behavior with disco_l475_iot1 (different BT controller, different HCI driver)

Thanks @erwango. Yes the HCI driver shouldn't matter. It is because the bt_recv_prio is doing net_buf_mem_pull on the buf, the state needs to be saved and restored.
It doesn't happen in the hci_driver.c because it doesn't re-use the buf.

Pushed a fix for this issue.

**Comment by erwango** [comment]
> > Testing on nucleo_wb55rg, I face an issue on disconnect (while HRM notifications are on)
> > `[00:00:24.124,000] <wrn> bt_hci_core: Unhandled event 0x00 len 2: 0813 `
> > Then, impossible to reconnect.
> > Works fine on master ([fae5d96](https://github.com/zephyrproject-rtos/zephyr/commit/fae5d96618632458e15c5c33dd81bb860126ad1b))
> > EDIT: I'm seeing the same behavior with disco_l475_iot1 (different BT controller, different HCI driver)
> 
> Thanks @erwango. Yes the HCI driver shouldn't matter. It is because the bt_recv_prio is doing net_buf_mem_pull on the buf, the state needs to be saved and restored.
> It doesn't happen in the hci_driver.c because it doesn't re-use the buf.
> 
> Pushed a fix for this issue.

Ok, I'm not able to reproduce anymore.
I've tried to test more and it's working so far. 2 times, I had trouble to restart HRM notifications, but second request went through (not sure this is related of even a zephyr issue).

**Comment by alexandru-porosanu-nxp** [comment]
> > @erwango @cvinayak @thoh-ot @alexandru-porosanu-nxp could you please test this with your respective Bluetooth platforms please? At the very least connection and disconnection multiple times, ideally with ongoing traffic.
> 
> Yep, I can do that; I'm thinking of using peripheral_hr (VEGA) & central_hr (NRF) and hack one of them to disconnect and reconnect at about 5-10s interval. If you have a better scenario in mind, let me know and I'll try to figure out how to do it...

I changed the scenario a bit and did about 10 connect/disconnect with NXP IoT toolbox to the VEGA board running peripheral_hr. So far, no issues.

**Comment by jhedberg** [comment]
In general this does seem like the right way to solve the issue. However, could we consider some other name for the new bt_conn state? "Priority' is appropriate for a thread or context, but not a state IMO. Something like PRE_DISCONNECT, or DISCONNECT_1 and DISCONNECT_2 would make more sense to me.

**Comment by jhedberg** [comment]
I think I'd also like to generalise this more. I didn't look through the driver changes, but you can't e.g. assume that the host won't change the parsing state of the net_buf, so net_buf_simple_save/restore may need to be used on the driver side.

That said, I don't think it's particularly clean to have the driver have to deal with this. The two-stage processing details would really be best to be left to the host. However, this will require even more redesign of the HCI driver interface. What we would need is a for the host to inject net_bufs to the "root" of the RX threaad. That way you could always feed the disconnect through bt_recv_prio() to the host, and the host would then re-inject it to itself through the RX thread. Another use case that might benefit from this is the ECDH emulation that hci_ecc.c does, i.e. it might make sense to have it feed the HCI events through the RX thread instead of its own.

**Comment by joerchan** [comment]
> That said, I don't think it's particularly clean to have the driver have to deal with this. The two-stage processing details would really be best to be left to the host. However, this will require even more redesign of the HCI driver interface. What we would need is a for the host to inject net_bufs to the "root" of the RX threaad.

I was considering this, but this is complicated by the BT_RECV_IS_RX_THREAD option. All the drivers that don't select this one has the same handling for bt_recv and bt_recv_prio. We could move the processing of this to bt_recv in that case.
The drivers that select this option is the zephyr controller and the H4. Maybe we could remove this option from H4 to further simplify it.

File: subsys/bluetooth/host/conn_internal.h [hunk 6]
```diff
@@ -212,6 +213,13 @@ void bt_conn_disconnect_all(u8_t id);
 /* Look up an existing connection */
 struct bt_conn *bt_conn_lookup_handle(u16_t handle);
 
+static inline bool bt_conn_is_handle_valid(struct bt_conn *conn)
```
[the remark this answers is not in the document]
Comment (joerchan) [reply subsys/bluetooth/host/conn_internal.h:216]: The fact that the state is used to determine if the handle has been assigned should remain hidden IMO. I prefer to give conn as the argument.

[the remark this answers is not in the document]
Comment (jhedberg) [reply subsys/bluetooth/host/conn_internal.h:216]: Agreed

**Comment by joerchan** [comment]
@jhedberg @carlescufi Pushed a commit with suggestion for moving the bt_recv/bt_recv_prio handling to the Host when BT_RECV_IS_RX_THREAD is not defined.
If we agree to do this I can rebase it properly. Not exactly sure what should be done when this option is defined. The HCI driver is the one with the most complicated bt_recv/bt_recv_prio handling.

**Comment by joerchan** [comment]
CC: @rugeGerritsen This affects the nRF BLE Controller.

**Comment by joerchan** [comment]
> In general this does seem like the right way to solve the issue. However, could we consider some other name for the new bt_conn state? "Priority' is appropriate for a thread or context, but not a state IMO. Something like PRE_DISCONNECT, or DISCONNECT_1 and DISCONNECT_2 would make more sense to me.

I've been trying to come up with sensible names, it's not easy.
I would prefer to leave DISCONNECTED state name as is, since this is also the initial state.
The _1 and _2 versions I'm not sure if you meant for what is now DISCONNECTED_PRIO, and DISCONNECTED, or DISCONNECT, and DISCONNECTED_PRIO

Best I could come up with:
`BT_CONN_DISCONNECT_CMD` (HCI command has been sent)
`BT_CONN_DISCONNECT_EVT`  (HCI disconnect complete event has been received).
`BT_CONN_DISCONNECTED`
or possibly:
`BT_CONN_DISCONNECT_SENT`
`BT_CONN_DISCONNECT_RCVD`
`BT_CONN_DISCONNECTED`

@carlescufi @jhedberg Thoughts?

File: drivers/bluetooth/hci/ipm_stm32wb.c [hunk 7]
```diff
@@ -202,7 +202,11 @@ static void bt_ipm_rx_thread(void)
 		if (hcievt->evtserial.type == HCI_EVT &&
 		    bt_hci_evt_is_prio(hcievt->evtserial.evt.evtcode)) {
 			bt_recv_prio(buf);
-		} else {
+		}
+
+		if (hcievt->evtserial.type == HCI_ACL ||
+		    (hcievt->evtserial.type == HCI_EVT &&
+		     bt_hci_evt_is_normal(hcievt->evtserial.evt.evtcode))) {
```
[the remark this answers is not in the document]
Comment (joerchan) [reply drivers/bluetooth/hci/ipm_stm32wb.c]: Code moved to hci_core.c now.

File: drivers/bluetooth/hci/rpmsg.c [hunk 8]
```diff
@@ -152,9 +152,13 @@ void bt_rpmsg_rx(u8_t *data, size_t len)
...
 		BT_DBG("Calling bt_recv(%p)", buf);
-		if (prio) {
+
+		if (pkt_indicator == RPMSG_EVT && bt_hci_evt_is_prio(evt)) {
 			bt_recv_prio(buf);
-		} else {
+		}
+
+		if (pkt_indicator == RPMSG_ACL ||
+		    (pkt_indicator == RPMSG_EVT && bt_hci_evt_is_normal(evt))) {
```
[the remark this answers is not in the document]
Comment (joerchan) [reply drivers/bluetooth/hci/rpmsg.c]: code moved to hci_core.c now.

File: drivers/bluetooth/hci/spi.c [hunk 9]
```diff
@@ -388,7 +388,11 @@ static void bt_spi_rx_thread(void)
 			if (rxmsg[PACKET_TYPE] == HCI_EVT &&
 			    bt_hci_evt_is_prio(rxmsg[EVT_HEADER_EVENT])) {
 				bt_recv_prio(buf);
-			} else {
+			}
+
+			if (rxmsg[PACKET_TYPE] == HCI_ACL ||
+			    (rxmsg[PACKET_TYPE] == HCI_ACL &&
```
[the remark this answers is not in the document]
Comment (joerchan) [reply drivers/bluetooth/hci/spi.c]: code moved to hci_core.c now, so the typo is resolved.

File: drivers/bluetooth/hci/userchan.c [hunk 10]
```diff
@@ -111,7 +111,10 @@ static void rx_thread(void *p1, void *p2, void *p3)
 
 		if (frame[0] == H4_EVT && bt_hci_evt_is_prio(frame[1])) {
 			bt_recv_prio(buf);
-		} else {
+		}
```
[the remark this answers is not in the document]
Comment (joerchan) [reply drivers/bluetooth/hci/userchan.c]: Moved to hci_core.c now.

File: include/drivers/bluetooth/hci_driver.h [hunk 11]
```diff
@@ -33,18 +33,17 @@ enum {
 };
 
 /**
- * @brief Check if an HCI event is high priority or not.
+ * @brief Check if an HCI shall be given from high priority context.
```
[the remark this answers is not in the document]
Comment (joerchan) [reply include/drivers/bluetooth/hci_driver.h]: Fixed

File: subsys/bluetooth/controller/hci/hci_driver.c (hunk 5 above)
Comment (joerchan) [reply subsys/bluetooth/controller/hci/hci_driver.c:137]: @carlescufi @jhedberg opinions on removing bt_recv_is_prio and and bt_recv_is_normal with a bt_recv_type as suggested?
I prefer my way, but not a strong opinion.
Related comment: https://github.com/zephyrproject-rtos/zephyr/pull/25954#discussion_r435038613

Comment (joerchan) [reply subsys/bluetooth/controller/hci/hci_driver.c:137]: I prefer if (is_normal) over if (type == normal || type == both)

File: drivers/bluetooth/hci/h4.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (carlescufi) [reply drivers/bluetooth/hci/h4.c:275]: At some point before the PR was posted I suggested the same, and I think I still prefer that now, so I agree with you @cvinayak. 
I'd like to get @jhedberg's opinion as well.

File: include/drivers/bluetooth/hci_driver.h [hunk 12]
```diff
@@ -33,18 +33,17 @@ enum {
...
- * @brief Check if an HCI event is high priority or not.
+ * @brief Check if an HCI event shall be given from high priority context.
  *
- * Helper for the HCI driver to know which events are ok to be passed
- * through the RX thread and which must be given to bt_recv_prio() from
- * another context (e.g. ISR). If this function returns true it's safe
- * to pass the event through the RX thread, however if it returns false
- * then this risks a deadlock.
+ * Helper for the HCI driver to know which events shall be given to
+ * bt_recv_prio() from another context than the RX thread (e.g. ISR).
```
Comment (carlescufi) [inline include/drivers/bluetooth/hci_driver.h:39]:
```suggestion
 * bt_recv_prio(), which depending on the driver might be called from another context than the RX thread (e.g. ISR).
```

File: drivers/bluetooth/hci/h4.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (carlescufi) [reply drivers/bluetooth/hci/h4.c:275]: That said I think instead of an enum we could use a mask to simplify checks?

```
#define BT_EVT_TYPE_PRIO BIT(0)
#define BT_EVT_TYPE_NORMAL BIT(1)

if (type & BT_EVT_TYPE_PRIO) bt_recv_prio();
if (type & BT_EVT_TYPE_NORMAL) bt_recv_normal();

File: subsys/bluetooth/controller/hci/hci_driver.c (hunk 5 above)
Comment (carlescufi) [reply subsys/bluetooth/controller/hci/hci_driver.c:137]: I prefer a bitmask, see my previous comment.
@jhedberg feedback welcome here as well.

File: subsys/bluetooth/host/conn.c (hunk 2 above)
Comment (carlescufi) [reply subsys/bluetooth/host/conn.c:1773]: Agreed, please replace `no valid` with `invalid`

File: subsys/bluetooth/host/conn_internal.h [hunk 13]
```diff
@@ -9,6 +9,7 @@
  */
 typedef enum __packed {
```
Comment (carlescufi) [inline subsys/bluetooth/host/conn_internal.h:10]: Why is this packed by the way?

**Comment by carlescufi** [comment]
@jhedberg 

>I think I'd also like to generalise this more. I didn't look through the driver changes, but you can't e.g. assume that the host won't change the parsing state of the net_buf, so net_buf_simple_save/restore may need to be used on the driver side.

I think that in the case of an event that is **both** prio and normal we could guarantee that the host will leave it untouched.

>That said, I don't think it's particularly clean to have the driver have to deal with this. The two-stage processing details would really be best to be left to the host. 

In an ideal world, I completely agree. But the problem is the combined builds and the h4 driver, where the driver and stack are already tightly coupled by the fact that `CONFIG_BT_RECV_IS_RX_THREAD=y`

>That way you could always feed the disconnect through bt_recv_prio() to the host, and the host would then re-inject it to itself through the RX thread

That won't work in the combined build. You would be reordering data and events, because at the point you receive the disconnected event through `bt_recv_prio()` there might well be data and other events that are queued inside `hci_driver.c` in non-net_buf format yet, and that haven't been processed into the queue that ends up creating the sequence of calls to `bt_recv()`.

**Review by carlescufi — COMMENTED** [review]
@joerchan 
My preference would be to unify the "disconnection in progress" state into a single one:

- `BT_CONN_DISCONNECTING`: Applies to both having called `bt_hci_disconnect` or having recieved the first disconnect event through `bt_recv_prio`
- `BT_CONN_DISCONNECTED`: Final disconnection complete processed

if that is not possible then I would suggest:

- `BT_CONN_DISCONNECTING_LOC` (or `BT_CONN_DISC_LOCAL`): Applies to having called `bt_hci_disconnect` 
- `BT_CONN_DISCONNECTING_REM` (or `BT_CONN_DISC_REMOTE`): Applies to having recieved the first disconnect event through `bt_recv_prio`
- `BT_CONN_DISCONNECTED`: Final disconnection complete processed

**Comment by carlescufi** [comment]
I just realized, for the drivers where `CONFIG_BT_RECV_IS_RX_THREAD=n`, this breaks the priority handling of num complete (and now disconnect), which is still required. If those drivers just call `bt_recv()` and the RX thread is blocked then posting it to the rx queue won't help. You still need to be able to execute the processing of the event from another context, which in this case is whoever calls `bt_recv_prio()`

File: subsys/bluetooth/host/hci_core.c [hunk 14]
```diff
@@ -6355,49 +6411,39 @@ int bt_recv(struct net_buf *buf)
...
 #else
-		net_buf_put(&bt_dev.rx_queue, buf);
+		struct bt_hci_evt_hdr *hdr = (void *)buf->data;
+
+		if (bt_hci_evt_is_prio(hdr->evt)) {
+			hci_event_prio(buf);
+		}
+
+		if (bt_hci_evt_is_normal(hdr->evt)) {
+			net_buf_put(&bt_dev.rx_queue, buf);
```
Comment (carlescufi) [inline subsys/bluetooth/host/hci_core.c:6425]: Is this safe after the `net_buf` has been processed by `hci_event_prio`? i.e. has its internal state not been modified?

File: subsys/bluetooth/host/conn_internal.h (hunk 13 above)
Comment (joerchan) [reply subsys/bluetooth/host/conn_internal.h:10]: I think it is to make it an uint8_t instead of a uint32_t in the bt_conn definition, since it is declared as bt_conn_state_t state;
But not sure that is the original thought behind this.

File: subsys/bluetooth/host/hci_core.c (hunk 14 above)
Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c:6425]: It should be, because `hci_event_prio` will save the state and restore it before returning.

**Comment by joerchan** [comment]
> @joerchan
> My preference would be to unify the "disconnection in progress" state into a single one:
> 
> * `BT_CONN_DISCONNECTING`: Applies to both having called `bt_hci_disconnect` or having recieved the first disconnect event through `bt_recv_prio`
> * `BT_CONN_DISCONNECTED`: Final disconnection complete processed
> 
> if that is not possible then I would suggest:
> 
> * `BT_CONN_DISCONNECTING_LOC` (or `BT_CONN_DISC_LOCAL`): Applies to having called `bt_hci_disconnect`
> * `BT_CONN_DISCONNECTING_REM` (or `BT_CONN_DISC_REMOTE`): Applies to having recieved the first disconnect event through `bt_recv_prio`
> * `BT_CONN_DISCONNECTED`: Final disconnection complete processed

The reason why I added a new state instead of re-using `BT_CONN_DISCONNECT` state is that that would introduce a no state change in `bt_conn_set_state` since the event is generated when initiating locally as well.
Using remote/local might be confusing since it might be related to who initiated the disconnect (hci status codes: `BT_HCI_ERR_REMOTE_USER_TERM_CONN` and  `BT_HCI_ERR_LOCALHOST_TERM_CONN`). So I think using cmd/evt or sent/rcvd would be better.

**Comment by joerchan** [comment]
@carlescufi @jhedberg Updated according to what we agreed on. The use of flags didn't turn out as clean as I would have wanted it, but maybe it is good enough.

File: include/drivers/bluetooth/hci_driver.h [hunk 15]
```diff
@@ -32,33 +32,39 @@ enum {
...
- * another context (e.g. ISR). If this function returns true it's safe
- * to pass the event through the RX thread, however if it returns false
- * then this risks a deadlock.
+ * @note Some events can be processed in both contexts.
  *
  * @param evt HCI event code.
  *
- * @return true if the event can be processed in the RX thread, false
- *         if it cannot.
+ * @return true if the event shall be processed by bt_recv_prio, false
```
Comment (jhedberg) [inline include/drivers/bluetooth/hci_driver.h:49]: Needs updating to flags

**Review by jhedberg — CHANGES_REQUESTED** [review]
Looks generally good. Just one documentation issue spotted. I’ll still try to do another more thorough review later.

File: include/drivers/bluetooth/hci_driver.h (hunk 15 above)
Comment (joerchan) [reply include/drivers/bluetooth/hci_driver.h]: Updated.

**Review by jhedberg — APPROVED** [review]

**Comment by mtpr-ot** [comment]
The ADV resume commit f24c38c306 (in local 2.2.1 backport version) fixes our ADV race condition, +1 from me.

**Comment by joerchan** [comment]
> The ADV resume commit [f24c38c](https://github.com/zephyrproject-rtos/zephyr/commit/f24c38c3069c1202641902fc9de8a71ce5752977) (in local 2.2.1 backport version) fixes our ADV race condition, +1 from me.

Great. I have created a separate bug-report in case others run into the issue, they can then see that it has been fixed.

**Review by carlescufi — APPROVED** [review]
