### PR TITLE
net: fix for assert on enabling socket CAN

### LINKED ISSUE #37132: Assert on enabling Socket CAN
Assert while running socket can application seen during interface initialization.

ASSERTION FAIL [net_if_get_link_addr(iface)->addr != ((void *)0)] @ WEST_TOPDIR/zephyr/subsys/net/ip/net_if.c:3993

Flags added in prj.conf of socket can application,    CONFIG_ASSERT=y

**Expected behavior**
Socket CAN does not require interface link address to be assigned, above check is not applicable for socket can interfaces.
As this address is NULL for socket CAN interface it results in assertion.

**Logs and console output**
ASSERTION FAIL [net_if_get_link_addr(iface)->addr != ((void *)0)] @ WEST_TOPDIR/zephyr/subsys/net/ip/net_if.c:3993
[00:00:00.138,092] <err> os: Faulting instruction address (r15/pc): 0x6000f8bc
[00:00:00.146,820] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:00.155,334] <err> os: Current thread: 0x60081160 (unknown)
[00:00:00.162,841] <err> os: Halting system

Note:
This check was introduced part of commit id "1e4f268ea94066cfc60c80019cf515b2baafc167".

### PR DESCRIPTION
**Pull request by rbabub**
Socket CAN does not require interface link address to be
assigned, check is not applicable for socket CAN
interfaces. As this address is NULL for socket CAN interface
it results in assertion.

Fixes #37132

Signed-off-by: Ramesh Babu B <ramesh.babu.b@intel.com>

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]

File: subsys/net/ip/net_if.c [hunk 1]
```diff
@@ -3990,7 +3990,11 @@ int net_if_up(struct net_if *iface)
 	/* In many places it's assumed that link address was set with
 	 * net_if_set_link_addr(). Better check that now.
 	 */
-	NET_ASSERT(net_if_get_link_addr(iface)->addr != NULL);
+	if (IS_ENABLED(CONFIG_NET_SOCKETS_CAN)) {
```
Comment (rlubos) [inline subsys/net/ip/net_if.c:3993]: I don't think that's enough, with such condition we'll skip the LL address verification for any interface, not only the CAN ones.

@alexanderwachter In the corresponding issue, you've mentioned `is_socket_can(iface)`, I don't see such a function in the tree though? Was this just a suggestion to create one or does the function exist somewhere under a different name? I think such a functionality could be achieved with the following code snippet as well?:
```
net_if_l2(iface) == &NET_L2_GET_NAME(CANBUS)
```

**Comment by alexanderwachter** [comment]
Can you add a check if the interface is of type SocketCAN?

File: subsys/net/ip/net_if.c (hunk 1 above)
Comment (alexanderwachter) [reply subsys/net/ip/net_if.c:3993]: There is no such function yet. That was just an example as pseudo code

**Comment by rbabub** [comment]
> Can you add a check if the interface is of type SocketCAN?

ya sure. 

Condition check:
net_if_l2(iface) == &NET_L2_GET_NAME(CANBUS_RAW)

File: subsys/net/ip/net_if.c [hunk 2]
```diff
@@ -3990,7 +3990,12 @@ int net_if_up(struct net_if *iface)
 	/* In many places it's assumed that link address was set with
 	 * net_if_set_link_addr(). Better check that now.
 	 */
-	NET_ASSERT(net_if_get_link_addr(iface)->addr != NULL);
+	if (IS_ENABLED(CONFIG_NET_SOCKETS_CAN) &&
+	    (net_if_l2(iface) == &NET_L2_GET_NAME(CANBUS_RAW)))	{
```
Comment (rlubos) [inline subsys/net/ip/net_if.c:3994]: @alexanderwachter There's `CANBUS_RAW_L2` and `CANBUS_L2` - should the LL address check be skipped for both or is the current solution enough?

Comment (alexanderwachter) [reply subsys/net/ip/net_if.c:3994]: RAW only. The other is 6loCAN, which is IPv6 over CAN. It has a 14bit address.

**Review by rlubos — APPROVED** [review]

**Comment by jhedberg** [comment]
Looks alright to me, but why are so many CI checks failing? @rbabub are you looking at those and planning to fix them?

**Comment by cfriedt** [comment]
LGTM - please check the compilation errors @rbabub

**Comment by rbabub** [comment]
> LGTM - please check the compilation errors @rbabub

ok sure.

**Comment by rbabub** [comment]
All checks are passed, could you please review and provide approval.

**Review by cfriedt — APPROVED** [review]
