### PR TITLE
net: ipv6: Drop RA with MTU out of valid range

### LINKED ISSUE #6342: echo server: incorrect Ethernet FCS and checksum in echo response when running in QEMU
This test case fails with echo server in QEMU. echo server responds to echo request with malformed response. In the response Ethernet Frame Check Sequence and ICMPv6 checksum are incorrect.
[icmpv6-71191-replay.zip](https://github.com/zephyrproject-rtos/zephyr/files/1752359/icmpv6-71191-replay.zip)
[icmpv6-71191.zip](https://github.com/zephyrproject-rtos/zephyr/files/1752360/icmpv6-71191.zip)

### PR DESCRIPTION
**Pull request by rmstoi**
This commit fixes incorrect Ethernet frame check sequence and ICMPv6
checksum caused by MTU set to zero in RA

Fixes #6342

Signed-off-by: Ruslan Mstoi <ruslan.mstoi@intel.com>

### CODE REVIEW

File: subsys/net/ip/ipv6.c [hunk 1]
```diff
@@ -46,6 +46,12 @@
  */
 #define MAX_REACHABLE_TIME 3600000
 
+/* IPv6 minimum link MTU specified in RFC 8200 section 5
+ * Packet Size Issues
+ */
+#define MIN_MTU 1280
```
Comment (jukkar) [inline subsys/net/ip/ipv6.c]: The patch is fine, it is just that the name of these defines need to be more clear so that we do not get confused what MTU we mean here as there can be several MTU in the system. There is already a define called NET_IPV6_MTU which is set to 1280 that should be used here directly or by setting "#define MIN_IPV6_MTU NET_IPV6_MTU", also use MAX_IPV6_MTU instead of MAX_MTU.

**Review by jukkar — CHANGES_REQUESTED** [review]

File: subsys/net/ip/ipv6.c (hunk 1 above)
Comment (rmstoi) [reply subsys/net/ip/ipv6.c]: I've made requested changes, new commit pushed.

**Review by jukkar — APPROVED** [review]
