### PR TITLE
drivers: flash: 4 byte address mode fix, if write enable is required

### LINKED ISSUE #57498: QSPI doesn't enter 4 byte mode
**Describe the bug**
I'm using a STM32H757 with a mt25ql512abb1ew9 external flash connected with QSPI. When trying to enter 4 byte addressing mode, it fails. The problem is this line:
https://github.com/zephyrproject-rtos/zephyr/blob/96a90550c48619d07eec8ba57fdd331148a21018/drivers/flash/flash_stm32_qspi.c#L960
In the debugger I can see that enter_4ba is 0x36. According to chapter 6.4.19 of the JESD216F.02 standard document, this also allows to enter the 4 byte addressing mode with the 0xb7 command, but it requires an additional 0x06 write enable command before it. Looks like it doesn't require it immediately before the 0xb7 command, because it works when I just patch the line with "if (true)".

**To Reproduce**
1. compile any project with a STM32 and a QSPI configuration, and with a flash IC which has this BFP byte
2. west debug
3. set a breakpoint to flash_stm32_qspi.c:960
4. verify that bit 0 is not set, see screenshot:
Screenshot_20230502_225450
and so qspi_program_addr_4b is not called and not switched to 4 byte address mode.

**Expected behavior**
It should also test for bit 1 and then switch to 4 byte address mode, probably best with a previous write enable command, for ICs that expect it immediately before the 0xb7 command.

**Impact**
I patched it locally, so only an annoyance for me.

### PR DESCRIPTION
**Pull request by Frank-Buss**
Fixes #57498

If bit 1 is set, then a write enable is required before sending the 0xb7 instruction to enable the 4 byte address mode, which this PR implements.

### CODE REVIEW

File: drivers/flash/flash_stm32_qspi.c [hunk 1]
```diff
@@ -717,8 +717,22 @@ static int setup_pages_layout(const struct device *dev)
...
+	/* Send write enable command, if required */
+	if (write_enable) {
+		QSPI_CommandTypeDef cmd_write_en = {
+			.Instruction = SPI_NOR_CMD_WREN,
+			.InstructionMode = QSPI_INSTRUCTION_1_LINE,
+		};
+		ret = qspi_send_cmd(dev, &cmd_write_en);
+		if (ret != 0) {
+			return ret;
+		}
```
Comment (erwango) [inline drivers/flash/flash_stm32_qspi.c:733]: Why not using `qspi_write_enable()` ?

File: drivers/flash/flash_stm32_qspi.c [hunk 2]
```diff
@@ -956,9 +970,10 @@ static int spi_nor_process_bfp(const struct device *dev,
 			 * portion of flash description register 16 indicates
 			 * if it is enough to use 0xB7 instruction without
 			 * write enable to switch to 4 bytes addressing mode.
+			 * If bit 1 is set, a write enable is needed.
 			 */
-			if (dw16.enter_4ba & 0x1) {
-				rc = qspi_program_addr_4b(dev);
+			if (dw16.enter_4ba & 0x3) {
```
Comment (erwango) [inline drivers/flash/flash_stm32_qspi.c:975]: This is slightly different from commit description.
With this change 4 byte address node is enabled only if bit 1 and 0 are set. From the description provided in #57498, it's not clear to me if this is what is requested by jedec spec.

Comment (Frank-Buss) [reply drivers/flash/flash_stm32_qspi.c:975]: No, the "if" expression is true, if at least bit 0 or bit 1 is 1, it is not necessary that both bits are set. This is the JEDEC description:
Screenshot_20230503_172829
So the code is right. The specification is a bit confusing, looks like it is all exclusive, because of the "x" don't care other bits, but obviously the 0x36 I read is not all exclusive or. But makes sense I guess, because a general 4 byte address mode doesn't preclude a special instruction (bit 5).

File: drivers/flash/flash_stm32_qspi.c (hunk 1 above)
Comment (Frank-Buss) [reply drivers/flash/flash_stm32_qspi.c:733]: qspi_write_enable also polls the status register. In flash_stm32_qspi_write for example, there is also a dedicated extra command send for it, I guess to avoid waiting for the status, which is done later. I guess in the end it doesn't matter, but if we take the specification literally "issue write enable instruction 06h, then issue instruction B7h", then we shouldn't poll the status register after sending the write enable instruction, so the current code should be right. But I can replace it with the qspi_write_enable as well, if you think this is better. For the code it would look nicer.

Comment (Frank-Buss) [reply drivers/flash/flash_stm32_qspi.c:733]: Maybe a "status" parameter for the qspi_write_enable function would be useful, then the caller of the function can decide if the status should be tested after the command. This could simplify some of the other code in flash_stm32_qspi_write as well. But not sure if this really makes it much more readable, and the C compiler probably optimizes it all out anyway.
What is the policy for PRs in Zephyr? Is it ok to refactor and add features at the same time?

Comment (erwango) [reply drivers/flash/flash_stm32_qspi.c:733]: > What is the policy for PRs in Zephyr? Is it ok to refactor and add features at the same time?

As long as you split refactoring and additions in different commits it is ok (of course a complete driver overhaul may deserve a specific PR, but this is not the case here).

> the specification literally "issue write enable instruction 06h, then issue instruction B7h", then we shouldn't poll the status register after sending the write enable instruction, so the current code should be right.

Ok, I guess we can keep it that way then.

**Review by erwango — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
