### PR TITLE
drivers: display: co5300: Fix address alignment issue

### LINKED ISSUE #104000: display_check: ASSERTION FAIL / kernel panic in test_display_by_capture on mimxrt700_evk (mimxrt798s/cm33_cpu0, co5300@0)
### Describe the bug
Running the display capture-based test (`display_check`) on NXP MIMXRT700 EVK (mimxrt798s/cm33_cpu0) consistently hits a `picolibc` assertion failure and then a Zephyr fatal error (kernel panic) in `test_display_by_capture`.

- [x] is_regression

### To Reproduce
1. Build:

```sh
west build -p -b mimxrt700_evk/mimxrt798s/cm33_cpu0 tests/drivers/display/display_check -T tests.drivers.display.check.shield
```

2. Flash/run on hardware.

### Expected behavior
`tests/drivers/display/display_check` should complete and the `display_test` testsuite should pass.

### Actual behavior
The device asserts and panics very early in `test_display_by_capture`.

### Logs
```text
==== Test  started at 2026-02-12 18:58:58.886793 ====
============================================
START - test_display_by_capture
I: Display test for co5300@0
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/lib/libc/picolibc/assert.c:27
E: r0/a1:  0x00000004  r1/a2:  0x0000001b  r2/a3:  0x50110000
E: r3/a4:  0x00000004 r12/ip:  0x00000074 r14/lr:  0x38006f7d
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x3800f390
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x30180ac0 (test_display_by_capture)
E: Halting system
I: mfd_pca9422_work_handler: sub_int[0]=0x80,  [1]=0x0
I: mfd_pca9422_work_handler: sub_mask[0]=0x7f, [1]=0xff
I: TMA525B entered application mode
*** Booting Zephyr OS build v4.3.0-4324-gc5ca54c7dfa0 ***
Running TESTSUITE display_test
===================================================================
START - test_display_by_capture
I: Display test for co5300@0
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/lib/libc/picolibc/assert.c:27
E: r0/a1:  0x00000004  r1/a2:  0x0000001b  r2/a3:  0x50110000
E: r3/a4:  0x00000004 r12/ip:  0x00000074 r14/lr:  0x38006f7d
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x3800f390
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x30180ac0 (test_display_by_capture)
E: Halting system
```

### environment
* Board: `mimxrt700_evk/mimxrt798s/cm33_cpu0`
* Display device reported by test: `co5300@0`
* Zephyr version string from boot: `v4.3.0-4324-gc5ca54c7dfa0`

### PR DESCRIPTION
**Pull request by KATE-WANG-NXP**
The CO5300 display controller of zc143ac72mipi shield requires the start coordinate and the size(width/height) of the updated area to be even for each frame update. Also the DCNano DBI controller on MIMXRT700 EVK which performs the frame update requires the frame buffer address to be 64-byte aligned. So the CO5300 driver maintains an internal buffer, for each write, the update area are copied to the internal buffer first, then the descriptor shall be adjusted to the even value AND make sure the the address of the actual updated area are aligned properly.

This PR is to fix https://github.com/zephyrproject-rtos/zephyr/issues/104000

### CODE REVIEW

File: drivers/display/display_co5300.c [hunk 1]
```diff
@@ -118,23 +120,30 @@ static void co5300_copy_and_adjust_coordinates(const struct device *dev,
...
 		local_desc->height = desc->height;
 	}
+
+	*local_x = x;
+	local_desc->width = desc->width;
+	dst = data->frame_ptr
+		+ (*local_y * data->frame_pitch * data->bytes_per_pixel)
+		+ (*local_x * data->bytes_per_pixel);
+
+	while ((*local_x % 2 != 0) || (((uint32_t)dst & (config->addr_align - 1)) != 0U)) {
```
Comment (JarmouniA) [inline drivers/display/display_co5300.c:140]: need to validate that addr_align is > 0

**Review by JarmouniA — DISMISSED** [review]

File: drivers/display/display_co5300.c (hunk 1 above)
Comment (hakehuang) [inline drivers/display/display_co5300.c:140]: This loop assumes `addr_align` is a power of two because it uses `(addr_align - 1)` as a bit mask, but the new `BUILD_ASSERT()` only checks for non-zero. Also, if the row start is not already compatible with the requested alignment, repeatedly decrementing `local_x` can underflow when `x` is near 0. Can we either enforce `addr_align` as power-of-two (and ideally validate the layout assumptions that make this terminate before column 0), or add bounds handling here so we never walk past the left edge?

**Review by hakehuang — CHANGES_REQUESTED** [review]
board testing is OK on v4.3.0-8662-gbc8fa6a044c7

File: drivers/display/display_co5300.c (hunk 1 above)
Comment (KATE-WANG-NXP) [reply drivers/display/display_co5300.c:140]: Yes this borderline case can happen, that is x decrements to 0 and the address alignment still cannot be met, in this case the address alignment and stride alignment configurations must be incompatible, so I added another check in CO5300_DEVICE_INIT instead of check it in the code

**Review by JarmouniA — APPROVED** [review]

**Comment by KATE-WANG-NXP** [comment]
Hi all, please help review, thanks

File: drivers/display/display_co5300.c (hunk 1 above)
Comment (KATE-WANG-NXP) [reply drivers/display/display_co5300.c:140]: @hakehuang Updated according to your comment, please help review

File: drivers/display/display_co5300.c [hunk 2]
```diff
@@ -118,23 +120,30 @@ static void co5300_copy_and_adjust_coordinates(const struct device *dev,
...
+		dst -= data->bytes_per_pixel;
+		(*local_x)--;
```
Comment (zejiang0jason) [inline drivers/display/display_co5300.c:142]: is it potential risk that this calculation makes `*local_x` < 0?

Comment (KATE-WANG-NXP) [reply drivers/display/display_co5300.c:142]: no, the pitch align check in CO5300_DEVICE_INIT makes sure that the start address of each line must suffice the check in line 140. This is added according to hake's comment 2 weeks ago, he has the same concern

**Review by hakehuang — APPROVED** [review]
