### PR TITLE
Bluetooth: SMP: Fix peripheral security request with authenticated keys

### LINKED ISSUE #17732: cannot use bt_conn_security in connected callback
**Describe the bug**
I preprogrammed a BLE SC bonding on a central and a peripheral device and wanted to enable encryption when the connection is established. For doing this, I called `bt_conn_security` in the connected callback. This seems to result in an error which terminates the connection.

**To Reproduce**
* have to devices already bonded with BLE SC
* both have corresponding `bt_keys` objects with keys: 34, flags: 17
* in the `connected` callback of one or both devices, add
```
int ret = bt_conn_security(conn, BT_SECURITY_FIPS);
if (ret) {
    LOG_INF("Kill connection: insufficient security %i", ret);
    bt_conn_disconnect(conn, BT_HCI_ERR_INSUFFICIENT_SECURITY);
} else {
    LOG_INF("bt_conn_security successful");
}
```
* let peripheral advertise, central connects on receipt of adv.
* the devices disconnect shortly after
* if both device enforce encryption like this, `bt_conn_security` fails on the peripheral with code -22 (EINVAL) causing the app the kill the connection
* if only one of both devices enforces encryption,
    * central gets disconnected with code 8 (BT_HCI_ERR_CONN_TIMEOUT)
    * peripheral gets disconnected with code 61 (BT_HCI_ERR_TERM_DUE_TO_MIC_FAIL)

**Expected behavior**
* the devices set up the security level successfully and stay connected.

**Impact**
* I have to restructure my whole app idea if I cannot find a workaround.

**Screenshots or console output**
Are posted here: https://github.com/zephyrproject-rtos/zephyr/issues/15256#issuecomment-514254728
and here: https://github.com/zephyrproject-rtos/zephyr/issues/15256#issuecomment-514256427

### PR DESCRIPTION
**Pull request by joerchan**
The call to bt_conn_security will send a SMP security request for
peripheral, and for central it will initiate LL encryption.
A call to bt_conn_security with no IO capabilities but authenticated
keys has been distributed, would succeed on central side, but fail on
peripheral side with error code -22.

The keys could have been either:
 - Preprogrammed
 - IO capabilities may have changed.
 - OOB bonding may been used.

Fix so that Peripheral can send a security request if the bond
information is already established.

Fixes: #17732

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]
LGTM, as discussed privately with @joerchan, this is in my opinion the correct approach to fix this

File: subsys/bluetooth/host/smp.c [hunk 1]
```diff
@@ -4845,6 +4845,39 @@ bool bt_smp_get_tk(struct bt_conn *conn, u8_t *tk)
...
+	    !(conn->le.keys->flags & BT_KEYS_AUTHENTICATED) &&
+	    !(conn->le.keys->keys & BT_KEYS_LTK_P256) &&
+	    !(conn->le.keys->enc_size == BT_SMP_MAX_ENC_KEY_SIZE)) {
+		return false;
+	}
+
+	return true;
+}
+
+
```
Comment (Vudentz) [inline subsys/bluetooth/host/smp.c]: Extra empty line.

Comment (joerchan) [reply subsys/bluetooth/host/smp.c]: Fixed.
