### PR TITLE
Bluetooth: Host: BT scan failure when connecting by name in shell

### LINKED ISSUE #78659: Bluetooth: Shell: Bluetooth scan failed (err -22) in audio_shell after trying to connect to a device by name
**Describe the bug**
In audio_shell, after initializing Bluetooth successfully (`bt init`), attempting to connect to a device by name (`bt connect-name <device_name>`) fails with the error message: `Bluetooth scan failed (err -22)`.

**To Reproduce**
1. Update branch to the latest on upstream.
2. Build and flash audio_shell to a board.
3. Initialize Bluetooth using `bt init`.
4. Attempt to connect to a device by name using `bt connect-name <device_name>`.
5. Observe the error message: `Bluetooth scan failed (err -22)`. 

**Expected behavior**
The device should connect successfully without any errors.

**Impact**
Minor problem in audio shell that prevents connecting to a device by name.

**Logs and console output**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by babrsn**
Added a timeout for active scans (instead of using the host's scan timeout) in the shell by submitting a k_work that stops the scan after a specified period.

Fixes #78659

### CODE REVIEW

File: subsys/bluetooth/shell/bt.c [hunk 1]
```diff
@@ -76,6 +76,11 @@ static struct bt_conn_auth_info_cb auth_info_cb;
  */
 #define HCI_CMD_MAX_PARAM 65
 
+#define DEFAULT_SCAN_TIMEOUT_MSEC 10000
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:79]:
```suggestion
#define DEFAULT_SCAN_TIMEOUT_SEC 10
```

File: subsys/bluetooth/shell/bt.c [hunk 2]
```diff
@@ -3299,6 +3331,10 @@ static int cmd_connect_le_name(const struct shell *sh, size_t argc, char *argv[]
 	/* Set boolean to tell the scan callback to connect to this name */
 	auto_connect.connect_name = true;
 
+	/* Schedule the k_work to act as a timeout */
+	k_work_reschedule(&active_scan_timeout_wrk, K_MSEC(DEFAULT_SCAN_TIMEOUT_MSEC));
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:3335]:
```suggestion
	k_work_reschedule(&active_scan_timeout_wrk, K_SECONDS(DEFAULT_SCAN_TIMEOUT_SEC));
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/shell/bt.c [hunk 3]
```diff
@@ -76,6 +76,11 @@ static struct bt_conn_auth_info_cb auth_info_cb;
  */
 #define HCI_CMD_MAX_PARAM 65
 
+#define DEFAULT_SCAN_TIMEOUT_MSEC 10000
+
+static struct k_work_delayable active_scan_timeout_wrk;
+static bool active_scan_timeout_echeduled;
```
[the remark this answers is not in the document]
Comment (babrsn) [reply subsys/bluetooth/shell/bt.c:82]: Ok.

File: subsys/bluetooth/shell/bt.c [hunk 4]
```diff
@@ -76,6 +76,11 @@ static struct bt_conn_auth_info_cb auth_info_cb;
  */
 #define HCI_CMD_MAX_PARAM 65
 
+#define DEFAULT_SCAN_TIMEOUT_MSEC 10000
+
+static struct k_work_delayable active_scan_timeout_wrk;
```
[the remark this answers is not in the document]
Comment (babrsn) [reply subsys/bluetooth/shell/bt.c:81]: Ok.

File: subsys/bluetooth/shell/bt.c [hunk 5]
```diff
@@ -1555,6 +1576,12 @@ static int cmd_active_scan_on(const struct shell *sh, uint32_t options,
 		shell_print(sh, "Bluetooth active scan enabled");
 	}
 
+	if (timeout != 0) {
+		/* Schedule the k_work to act as a timeout */
+		k_work_reschedule(&active_scan_timeout_wrk, K_MSEC(timeout * 1000));
```
[the remark this answers is not in the document]
Comment (babrsn) [reply subsys/bluetooth/shell/bt.c:1581]: Done.

File: subsys/bluetooth/shell/bt.c (hunk 2 above)
Comment (babrsn) [reply subsys/bluetooth/shell/bt.c:3335]: Done.

File: subsys/bluetooth/shell/bt.c [hunk 6]
```diff
@@ -76,6 +76,10 @@ static struct bt_conn_auth_info_cb auth_info_cb;
  */
 #define HCI_CMD_MAX_PARAM 65
 
+#define DEFAULT_SCAN_TIMEOUT_SEC 10
+
+static struct k_work_delayable active_scan_timeout_work;
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:81]: The struct should be moved to lines 223 in the `#if defined(CONFIG_BT_OBSERVER)` part. 

The reason is that if someone build the shell with `CONFIG_BT_OBSERVER=n` then this would give a warning as being unused

File: subsys/bluetooth/shell/bt.c [hunk 7]
```diff
@@ -1276,6 +1292,8 @@ static int cmd_init(const struct shell *sh, size_t argc, char *argv[])
 		}
 	}
 
+	k_work_init_delayable(&active_scan_timeout_work, active_scan_timeout);
+
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:1296]: You can actually defined the `k_work` as 

```c
static K_WORK_DELAYABLE_DEFINE(active_scan_timeout_work, active_scan_timeout);
```

Then you both declare and initialize it in one go

File: subsys/bluetooth/shell/bt.c [hunk 8]
```diff
@@ -1587,6 +1610,11 @@ static int cmd_scan_off(const struct shell *sh)
 {
 	int err;
 
+	if (k_work_delayable_remaining_get(&active_scan_timeout_work) > 0) {
+		/* Cancel the pending scan timeout work */
+		k_work_cancel_delayable(&active_scan_timeout_work);
+	}
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:1616]: Can't we always just attempt to cancel it? Do we need to check the state first?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/shell/bt.c (hunk 6 above)
Comment (babrsn) [reply subsys/bluetooth/shell/bt.c:81]: Ok.

File: subsys/bluetooth/shell/bt.c (hunk 7 above)
Comment (babrsn) [reply subsys/bluetooth/shell/bt.c:1296]: OK.

File: subsys/bluetooth/shell/bt.c [hunk 9]
```diff
@@ -1245,6 +1243,26 @@ static void bt_ready(int err)
...
+
+#if defined(CONFIG_BT_CENTRAL)
+	if (auto_connect.connect_name) {
+		auto_connect.connect_name = false;
+		/* "name" is what would be in argv[0] normally */
+		cmd_scan_filter_clear_name(ctx_shell, 1, (char *[]){ "name" });
+	}
+#endif /* CONFIG_BT_CENTRAL */
+}
```
Comment (Thalley) [inline subsys/bluetooth/shell/bt.c:1264]: I think that if you move this file to before line 228 then you can omit the prototype of it, right?

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/shell/bt.c (hunk 9 above)
Comment (babrsn) [reply subsys/bluetooth/shell/bt.c:1264]: Yes, do you think it would be better if I moved it?

Comment (Thalley) [reply subsys/bluetooth/shell/bt.c:1264]: Slightly, but not necessary :)

Comment (babrsn) [reply subsys/bluetooth/shell/bt.c:1264]: Ok :)

**Review by Thalley — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

**Comment by Thalley** [comment]
@babrsn needs a rebase

**Comment by babrsn** [comment]
> @babrsn needs a rebase

Done.

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
