### PR TITLE
net: ip: icmp: Change net_icmp_handler_t return type to enum net_verdict

### LINKED ISSUE #104781: net: icmp: Not possible to have 2 concurrent ping contexts
### Describe the bug

Running the following snippet together with a `net ping` shell command will call the incorrect handler (all ICMP handlers will be passed all responses).

### Regression

- [ ] This is a regression.

### Steps to reproduce

Run a `net ping` shell command together with another ICMP context.

```shell
uart:~$ net ping 1.1.1.1
```

With some pseudo-code _(UNTESTED)_

```c
static int icmp_cb(struct net_icmp_ctx *ctx, struct net_pkt *pkt,
		   struct net_icmp_ip_hdr *ip_hdr, struct net_icmp_hdr *icmp_hdr,
		   void *user_data)
{
	LOG_INF("Got ping response");

	return 0;
}

int main(void)
{
	struct net_icmp_ctx ctx;
	struct net_sockaddr_in dst;
	int ret;

	(void)net_icmp_init_ctx(&ctx, NET_AF_INET, NET_ICMPV4_ECHO_REPLY, 0, icmp_cb);

	k_msleep(10000);

	dst.sin_addr.s_addr = 0x08080808; /* 8.8.8.8 */

	while (true) {
		ret = net_icmp_send_echo_request_no_wait(&ctx, NULL, (struct net_sockaddr *)&dst,
							 NULL, NULL);
		if (ret < 0) {
			LOG_ERR("Failed to send ICMP (%d)", ret);
		}
		k_msleep(1500);
	}

	return 0;
}
```

### Relevant log output

```shell
uart:~$ net ping 1.1.1.1
PING 1.1.1.1
28 bytes from 1.1.1.1 to 172.149.20.69: icmp_seq=1 ttl=56 time=26 ms
32 bytes from 172.149.20.16 to 172.149.20.69: icmp_seq=106 ttl=64 time=1847 ms
28 bytes from 1.1.1.1 to 172.149.20.69: icmp_seq=2 ttl=56 time=12 ms
[00:05:06.981,933] <err> net_pkt: Uncontiguous data cannot be linearized
[00:05:06.981,964] <err> net_icmpv4: ICMPv4 handling failure (-5)
[00:05:07.968,353] <err> net_pkt: Uncontiguous data cannot be linearized
[00:05:07.968,383] <err> net_icmpv4: ICMPv4 handling failure (-5)
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: Ubuntu 24.04
- Toolchain: Zephyr SDK 0.17.4
- `main` @ 6006d5c3a5baa3918bbaa46e7ddb36a1d4053237

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pdgendt**
Update the return type of the ICMP callback handler to enum net_verdict.
This fixes an issue where currently all ICMP handler are passed the same
pkt. Handlers could have modified the passed packet resulting in undefined
behavior.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/104781

### CODE REVIEW

**Review by sylvioalves — DISMISSED** [review]

File: modules/openthread/platform/infra_if.c [hunk 1]
```diff
@@ -264,10 +264,10 @@ static int handle_icmp6_input(struct net_icmp_ctx *ctx, struct net_pkt *pkt,
 
 exit:
 	if (error == OT_ERROR_NONE) {
-		return 0;
+		return NET_OK;
```
Comment (rlubos) [inline modules/openthread/platform/infra_if.c]: Shouldn't the default behavior be to return `NET_CONTINUE` in case the handler did not modify the packet in any way? At least in this example, it seems that OTBR registers a separate handler for some ND ICMPv6 messages simply to forward them to the OT stack.

CC @Cristib05

File: subsys/net/ip/ipv6_nbr.c [hunk 2]
```diff
@@ -1500,25 +1500,25 @@ static int handle_ns_input(struct net_icmp_ctx *ctx,
 
 	if (!net_ipv6_send_na(net_pkt_iface(pkt), na_src,
 			      na_dst, tgt, flags)) {
-		return 0;
+		return NET_OK;
```
Comment (rlubos) [inline subsys/net/ip/ipv6_nbr.c]: Same when it comes to handlers registered by the core net stack. If it consumes the packet, any other listener for a given message type that could be registered elsewhere will not get it. This case seems trickier, as the packet cursor seems to be modified be the handler, but it could be easily restored before exit I guess.

File: subsys/net/ip/icmpv4.c [hunk 3]
```diff
@@ -501,15 +501,15 @@ static int icmpv4_handle_echo_request(struct net_icmp_ctx *ctx,
 
 	net_stats_update_icmp_sent(net_pkt_iface(reply));
 
-	return 0;
+	return NET_OK;
```
Comment (pdgendt) [inline subsys/net/ip/icmpv4.c]: Not sure here if it should be `NET_CONTINUE` instead?

File: subsys/net/ip/icmpv6.c [hunk 4]
```diff
@@ -179,7 +179,7 @@ static int icmpv6_handle_echo_request(struct net_icmp_ctx *ctx,
 
 	net_stats_update_icmp_sent(net_pkt_iface(reply));
 
-	return 0;
+	return NET_OK;
```
Comment (pdgendt) [inline subsys/net/ip/icmpv6.c]: ditto

File: subsys/net/ip/icmpv4.c (hunk 3 above)
Comment (rlubos) [reply subsys/net/ip/icmpv4.c]: If we stick to the approach that `NET_CONTINUE` should be the defalult behavior then I think it should (even though it'd be silly if some other system component replied to pings, it may collect them for some other reason).
IMHO `NET_OK` only makes sense if we're certain no one else would need the message (like ping reply that matched the sender ID).

File: subsys/net/ip/icmpv4.c [hunk 5]
```diff
@@ -743,19 +744,19 @@ static int icmpv4_handle_dst_unreach(struct net_icmp_ctx *ctx,
 			net_sprint_ipv4_addr(&ip_hdr->src), ret, mtu);
 	}
 
-	return 0;
+	return NET_OK;
```
Comment (rlubos) [inline subsys/net/ip/icmpv4.c]: `NET_CONTINUE` as well?

**Review by rlubos — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
