### PR TITLE
usb: cdc_acm: fix suspend handling in CDC ACM class

### LINKED ISSUE #17488: CDC_ACM USB on nRF device fails after suspend
**Describe the bug**
After a suspend and resume the USB serial port is no longer responsive. Possibly related to #16599.

**To Reproduce**
1. build samples/subsys/usb/cdc_acm for the nrf52840_pca10056 board
2. enable Logging and set USB_DRIVER_LOG_LEVEL_DBG=y USB_DEVICE_LOG_LEVEL_INF=y USB_CDC_ACM_LOG_LEVEL_INF=y
3. set CDC_ACM_IAD=y to allow Windows to correctly use the device
4. plug into Windows 10 PC, device is recognized and works
5. enter sleep mode on PC, device is suspended
6. after device resumes communication fails.
7. replugging the USB port returns it to correct operation

**Expected behavior**
When the PC resumes I expect the USB serial port to be operating.

**Impact**
Serious concern. We are developing a therapy product where the PCs will often be suspended. Forcing the user to replug the device every time will be a huge inconvenience.

**Screenshots or console output**
Comments in the log file below are preceeded by a \#
```
## initial open terminal program
[00:01:01.226,684] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read done: 7
--- 105 messages dropped ---
[00:01:01.226,715] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 7
[00:01:01.226,776] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:01:01.227,081] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:01:01.227,081] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:01:01.227,142] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:01:01.227,203] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete
[00:01:01.227,508] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:34 rt:33 v:3 i:0 l:0
[00:01:01.227,508] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:01:01.227,569] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:01:01.227,630] <dbg> cdc_acm_echo.main: DTR set
[00:01:01.227,691] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:32 rt:33 v:0 i:0 l:7
[00:01:01.227,722] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:01:01.227,813] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read request
[00:01:01.227,874] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read done: 7
[00:01:01.227,935] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 7
[00:01:01.227,966] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:01:01.228,027] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x81, len 10
[00:01:01.228,179] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:01:01.228,210] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:01:01.228,240] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:01:01.228,332] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete
[00:01:01.232,452] <dbg> usb_nrfx.usbd_event_transfer_data: write complete, ep 0x81
[00:01:01.232,513] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x81, len 10
[00:01:01.240,447] <dbg> usb_nrfx.usbd_event_transfer_data: write complete, ep 0x81
[00:01:02.253,570] <inf> cdc_acm_echo: Baudrate detected: 115200
[00:01:02.253,601] <dbg> cdc_acm_echo.interrupt_handler: tty fifo -> ringbuf 0 bytes
[00:01:02.253,631] <dbg> cdc_acm_echo.interrupt_handler: Ring buffer empty, disable TX IRQ

## send one byte
[00:01:50.326,690] <dbg> usb_nrfx.usbd_event_transfer_data: read request, ep 0x01
[00:01:50.326,751] <dbg> usb_nrfx.usbd_event_transfer_data: read complete, ep 0x01, len 1
[00:01:50.326,873] <dbg> cdc_acm_echo.interrupt_handler: tty fifo -> ringbuf 1 bytes
[00:01:50.326,904] <dbg> cdc_acm_echo.interrupt_handler: ringbuf -> tty fifo 1 bytes
[00:01:50.326,965] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x82, len 1
[00:01:50.327,026] <dbg> usb_nrfx.usbd_event_transfer_data: write complete, ep 0x82
[00:01:50.327,087] <dbg> cdc_acm_echo.interrupt_handler: Ring buffer empty, disable TX IRQ

## close terminal program
[00:02:25.489,318] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:34 rt:33 v:2 i:0 l:0
[00:02:25.489,318] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:02:25.489,379] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0

## suspend (Windows 10 sleep)
[00:03:26.299,346] <dbg> usb_nrfx.usbd_event_handler: SUSPEND state detected
[00:03:26.299,407] <dbg> usb_nrfx.usbd_work_process_pwr_events: USB Suspend state
[00:03:26.299,407] <dbg> usb_nrfx.usb_dc_ep_disable: EP disable: 0x81
[00:03:26.299,407] <dbg> usb_nrfx.usb_dc_ep_disable: EP disable: 0x01
[00:03:26.299,438] <dbg> usb_nrfx.usb_dc_ep_disable: EP disable: 0x82

## resume
[00:03:29.906,646] <dbg> usb_nrfx.usbd_event_handler: RESUMING from suspend
[00:03:29.906,677] <dbg> usb_nrfx.usbd_work_process_pwr_events: USB resume
[00:03:29.962,127] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:32 rt:33 v:0 i:0 l:7
[00:03:29.962,127] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:03:29.962,219] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read request
[00:03:29.962,310] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read done: 7
[00:03:29.962,341] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 7
[00:03:29.962,371] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:03:29.962,615] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:03:29.962,615] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:03:29.962,677] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:03:29.962,921] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete

## open terminal program
[00:05:37.272,491] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
--- 13 messages dropped ---
[00:05:37.273,895] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:05:37.273,956] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete
[00:05:37.274,383] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:32 rt:33 v:0 i:0 l:7
[00:05:37.274,383] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:05:37.274,475] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read request
[00:05:37.274,536] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read done: 7
[00:05:37.274,566] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 7
[00:05:37.274,627] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:05:37.274,963] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:05:37.274,993] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:05:37.275,024] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:05:37.275,085] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete
[00:05:37.275,360] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:34 rt:33 v:3 i:0 l:0
[00:05:37.275,390] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:05:37.275,451] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:05:37.275,695] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:32 rt:33 v:0 i:0 l:7
[00:05:37.275,695] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:05:37.275,787] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read request
[00:05:37.275,878] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read done: 7
[00:05:37.275,909] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 7
[00:05:37.275,970] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:05:37.276,367] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:05:37.276,367] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:05:37.276,428] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:05:37.276,489] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete

## send one byte
[00:06:19.868,652] <dbg> usb_nrfx.usbd_event_transfer_data: read request, ep 0x01
# no other response

## close terminal program
[00:07:25.223,388] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:34 rt:33 v:2 i:0 l:0
[00:07:25.223,388] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:07:25.223,419] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0

## open terminal program
# Note error and timing of messages
[00:08:21.548,461] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:08:21.548,461] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:08:21.548,492] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:08:51.550,201] <err> usb_nrfx: Unexpected event (nrfx_usbd): 3, ep 0x80
[00:08:51.550,231] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:08:51.550,231] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:08:51.550,292] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:09:21.552,307] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:09:21.552,307] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:09:21.552,337] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:09:51.553,924] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:09:51.553,924] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:09:51.553,985] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:10:21.555,450] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:32 rt:33 v:0 i:0 l:7
[00:10:21.555,450] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:10:21.555,541] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read request
[00:10:51.557,250] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:10:51.557,250] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:10:51.557,312] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:11:21.577,697] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:34 rt:33 v:2 i:0 l:0
[00:11:21.577,697] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:11:21.577,758] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0

## unplug
[00:13:42.596,862] <dbg> usb_nrfx.usbd_event_handler: SUSPEND state detected
[00:13:42.596,923] <dbg> usb_nrfx.usbd_work_process_pwr_events: USB Suspend state
[00:13:42.683,258] <dbg> usb_nrfx.usbd_event_handler: RESUMING from suspend
[00:13:42.683,288] <dbg> usb_nrfx.hf_clock_enable: HF clock stop success (0)
[00:13:42.683,288] <dbg> usb_nrfx.usbd_work_process_pwr_events: USB Removed

## plug in
[00:14:04.800,598] <dbg> usb_nrfx.usbd_work_process_pwr_events: USB detected
[00:14:04.800,628] <dbg> usb_nrfx.hf_clock_enable: HF clock start success (-68)
[00:14:04.801,666] <dbg> usb_nrfx.usbd_work_process_pwr_events: USB Powered
[00:14:04.804,748] <dbg> usb_nrfx.usbd_event_handler: SUSPEND state detected
[00:14:04.804,779] <dbg> usb_nrfx.usbd_work_process_pwr_events: USB Suspend state
[00:14:05.193,115] <dbg> usb_nrfx.usbd_event_handler: RESUMING from suspend
[00:14:05.193,176] <dbg> usb_nrfx.usbd_work_process_pwr_events: USB resume
--- 30 messages dropped ---
[00:14:05.291,198] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 18
--- 6 messages dropped ---
[00:14:05.293,640] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
--- 10 messages dropped ---
[00:14:05.294,219] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:6 rt:128 v:770 i:1033 l:4
[00:14:05.294,219] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:14:05.294,281] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 4
[00:14:05.294,403] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete
[00:14:05.294,616] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:6 rt:128 v:770 i:1033 l:44
[00:14:05.294,647] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:14:05.294,677] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 44
[00:14:05.294,799] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete
[00:14:05.306,701] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:14:05.306,701] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:14:05.306,762] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:14:05.306,823] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete
[00:14:05.307,128] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:34 rt:33 v:0 i:0 l:0
[00:14:05.307,128] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:14:05.307,189] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:14:05.307,434] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:32 rt:33 v:0 i:0 l:7
[00:14:05.307,464] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:14:05.307,556] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read request
[00:14:05.307,617] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl read done: 7
[00:14:05.307,678] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 7
[00:14:05.307,739] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 0
[00:14:05.308,044] <dbg> usb_nrfx.usbd_work_process_setup: SETUP: r:33 rt:161 v:0 i:0 l:7
[00:14:05.308,044] <dbg> usb_nrfx.usb_dc_ep_read: ep_read: ep 0x00, maxlen 8
[00:14:05.308,105] <dbg> usb_nrfx.usb_dc_ep_write: ep_write: ep 0x80, len 7
[00:14:05.308,197] <dbg> usb_nrfx.usbd_event_transfer_ctrl: ctrl write complete

```

**Environment (please complete the following information):**
 - OS: Linux (build), Windows 10 Pro (test)
 - Toolchain: zephyr-sdk-0.10.1
 - Commit SHA or Version used:  1.14.99,  f1b349aa72476802dac8e49b410ae34aaf24df4b

### PR DESCRIPTION
**Pull request by jfischer-no**
usb: cdc_acm: update state after RESUME event 
Update state after RESUME event.
Use LOG_INF for important events and log a
warning if the data is discarded.
Fixes #17488

samples: cdc_acm: rework sample logging 
Use  LOG_LEVEL_INF as defautl log level and use LOG_INF
for important messages. Relax while loop and
give CPU resources to low priority threads like logging.

### CODE REVIEW

File: samples/subsys/usb/cdc_acm/src/main.c [hunk 1]
```diff
@@ -83,16 +83,19 @@ void main(void)
...
-	LOG_DBG("Wait for DTR");
+	LOG_INF("Wait for DTR");
 
 	while (true) {
 		uart_line_ctrl_get(dev, LINE_CTRL_DTR, &dtr);
 		if (dtr) {
 			break;
+		} else {
+			/* Give CPU resources to low priority threads. */
+			k_sleep(100);
```
Comment (carlescufi) [inline samples/subsys/usb/cdc_acm/src/main.c]: why not `k_yield()` ?

Comment (jfischer-phytec-iot) [reply samples/subsys/usb/cdc_acm/src/main.c]: _Calling k_yield() puts the thread at the back of the scheduler’s prioritized list of ready threads, and then invokes the scheduler. All ready threads whose priority is higher or equal to that of the yielding thread are then allowed to execute before the yielding thread is rescheduled. If no such ready threads exist, the scheduler immediately reschedules the yielding thread without context switching.
Calling k_sleep() makes the thread unready for a specified time period. Ready threads of all priorities are then allowed to execute; however, there is no guarantee that threads whose priority is lower than that of the sleeping thread will actually be scheduled before the sleeping thread becomes ready once again._

I am not sure, but k_sleep() seems to be a better solution.

**Review by finikorg — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

**Comment by carlescufi** [comment]
@jfischer-phytec-iot 

I ran the following test on my Windows 10:

1. Enable `CONFIG_CDC_ACM_IAD=y`
2. Build and flash the sample in `samples/subsys/usb/cdc_acm`
3. Connect the USB cable
4. Open the CDC ACM serial port, type characters
5. Close the serial port
6. Suspend the Windows machine
7. Wake up the Windows machine
8. Open the CDC ACM serial pot, type characters

So this seems like it's working

@emob-nordic can you check as well?

**Review by carlescufi — APPROVED** [review]
