### PR TITLE
Bluetooth: Controller: fix uninitialized variable

### LINKED ISSUE #35157: [Coverity CID: 221380] Uninitialized scalar variable in subsys/bluetooth/controller/ll_sw/ull_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/0622bde3bf22926544c1aaef4c01dfa23d79f26e/subsys/bluetooth/controller/ll_sw/ull_iso.c#L163

Category: Uninitialized variables
Function: `ll_setup_iso_path`
Component: Bluetooth
CID: [221380](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=221380)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/0622bde3bf22926544c1aaef4c01dfa23d79f26e/subsys/bluetooth/controller/ll_sw/ull_iso.c#L192

```
157                                      sink_sdu_emit_hci, sink_sdu_write_hci);
158      } else {
159              /* TBD call vendor specific function to set up ISO path */
160      }
161     
162      if (!err) {
>>>     CID 221380:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized value "sink_hdl".
163              dp->sink_hdl = sink_hdl;
164              isoal_sink_enable(sink_hdl);
165      } else {
166              return BT_HCI_ERR_CMD_DISALLOWED;
167      }
168     
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by asmk-ot**
Fixes #35157
[Coverity CID: 221380]

Signed-off-by: Asger Munk Nielsen <asmk@oticon.com>

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_iso.c [hunk 1]
```diff
@@ -99,9 +99,6 @@ uint8_t ll_setup_iso_path(uint16_t handle, uint8_t path_dir, uint8_t path_id,
 	ARG_UNUSED(codec_config_len);
 	ARG_UNUSED(codec_config);
 
-	isoal_sink_handle_t sink_hdl;
-	isoal_status_t err = 0;
```
Comment (wopu-ot) [inline subsys/bluetooth/controller/ll_sw/ull_iso.c:103]: Suggestion: change here to
```
	isoal_sink_handle_t sink_hdl = 0;
	isoal_status_t err = ISOAL_STATUS_ERR_SINK_ALLOC;
```
and keep rest of the code as is. Initializing `sink_hdl` should technically not be necessary but may help guard against non-ideal compiler heuristics. That change would also resolve the issue with the current code that it reports success even if no path was set up (e.g., if only BIS is enabled).

Comment (carlescufi) [reply subsys/bluetooth/controller/ll_sw/ull_iso.c:103]: @asmk-ot could you take a look at the proposal above? Thanks!

**Review by nashif — APPROVED** [review]
