### PR TITLE
fixed I2S driver for SAI peripheral, and tested on mimxrt1170_evk

### LINKED ISSUE #42434: NXP I2S (SAI) driver bugs
**Describe the bug**
The I2S driver for NXP's SAI peripheral has multiple bugs that prevent the driver from working properly.  Including DMA does not transmit, and FIFO under/overruns.

Please also mention any information which could help others to understand
the problem you're facing:
testing on MIMXRT1170_EVK

**To Reproduce**
The test fails running \tests\drivers\i2s\i2s_speed.  This board uses CONFIG_I2S_TEST_SEPARATE_DEVICES=y and connects two SAI peripherals by shorting signals externally on the EVK.  These are the HW changes required to run this test:
	- Remove jumper J8 and resistor R78
	- Short BCLK J9-pin1  (SAI1_RX_BCLK)  to J66-pin1  (SAI4_TX_BCLK)
	- Short SYNC J9-pin5  (SAI1_RX_SYNC)  to J64-pin1  (SAI4_TX_SYNC)
	- Short Data J61-pin1 (SAI1_RX_DATA)  to J63-pin1  (SAI4_TX_DATA)

with Kconfig:
```
CONFIG_I2S_MCUX_SAI=y
CONFIG_I2S_TEST_SEPARATE_DEVICES=y
CONFIG_I2S_LOG_LEVEL_OFF=y

```
devicetree overlay:
```
&sai2 {
	label = "I2S_3";
};

&sai4 {
	label = "I2S_1";
	status = "okay";
	clocks = < &ccm 0x2003 0x2184 0x6 >;
	podf = < 0x4 >;
};

&enet {
	status = "disabled";
};

```
pinmux:
```
#if DT_NODE_HAS_STATUS(DT_NODELABEL(sai1), okay) && CONFIG_I2S_MCUX_SAI
	#if CONFIG_I2S_TEST_SEPARATE_DEVICES
	
		CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);      /* LPCG on: LPCG is ON. */

		IOMUXC_SetPinMux(
		  IOMUXC_GPIO_AD_18_SAI1_RX_SYNC,         /* GPIO_AD_18 is configured as SAI1_RX_SYNC */
		  0U);                                    /* Software Input On Field: Input Path is determined by functionality */
		IOMUXC_SetPinMux(
		  IOMUXC_GPIO_AD_19_SAI1_RX_BCLK,         /* GPIO_AD_19 is configured as SAI1_RX_BCLK */
		  0U);                                    /* Software Input On Field: Input Path is determined by functionality */
		IOMUXC_SetPinMux(
		  IOMUXC_GPIO_AD_20_SAI1_RX_DATA00,       /* GPIO_AD_20 is configured as SAI1_RX_DATA00 */
		  0U);                                    /* Software Input On Field: Input Path is determined by functionality */
		IOMUXC_SetPinMux(
		  IOMUXC_GPIO_LPSR_09_SAI4_TX_DATA,       /* GPIO_LPSR_09 is configured as SAI4_TX_DATA */
		  7U);                                    /* Software Input On Field: Input Path is determined by functionality */
		IOMUXC_SetPinMux(
		  IOMUXC_GPIO_LPSR_10_SAI4_TX_SYNC,       /* GPIO_LPSR_10 is configured as SAI4_TX_SYNC */
		  7U);                                    /* Software Input On Field: Input Path is determined by functionality */
		IOMUXC_SetPinMux(
		  IOMUXC_GPIO_LPSR_12_SAI4_TX_BCLK,       /* GPIO_LPSR_12 is configured as SAI4_TX_BCLK */
		  7U);                                    /* Software Input On Field: Input Path is determined by functionality */
	#endif
#endif

```
west build -b mimxrt1170_evk_cm7 tests\drivers\i2s\i2s_speed

**Expected behavior**
The i2s_speed test should pass with SAI driver transmitting and receiving properly using DMA.

**Impact**
showstopper for I2S/SAI users

### LINKED ISSUE #42436: NXP eDMA overrun errors on SAI RX
**Describe the bug**
The I2S driver for NXP peripheral SAI has RX overrun errors when using the DMA.  This is because the driver dma_mcux_edma.c does not properly support the dma_reload() API when source_gather_en is enabled.  Without using source_gather_en feature and having eDMA hardware automatically switch to a new RX buffer, the FIFO has overruns during RX.  The fix needed updates dma_mcux_edma_reload() to work with linked TCDs in gather mode.

**To Reproduce**
See [NXP I2S (SAI) driver bugs](https://github.com/zephyrproject-rtos/zephyr/issues/42434 ) for test and HW setup to replicate.

**Expected behavior**
i2s_speed test app succeeds with SAI/eDMA without any RX overruns.

**Impact**
showstopper for SAI/eDMA users

### PR DESCRIPTION
**Pull request by DerekSnell**
Update includes several driver fixes.  Tested with Zephyr i2s_speed test application, and added board-specific files and readme to test to replicate the test setup.

test built with command:
`west build -b mimxrt1170_evk_cm7 tests\drivers\i2s\i2s_speed`

fixes #42434
fixes #42436

This branch is based on open PR [Update LPUART async support to fix build failures #44962 ](https://github.com/zephyrproject-rtos/zephyr/pull/44962)

### CODE REVIEW

**Comment by hakehuang** [comment]
@DerekSnell  LGTM, please remember to revert the temp commit 24d5b179707cab7c41a5f58e8f1a62efe947eabd

File: drivers/i2s/i2s_mcux_sai.c [hunk 1]
```diff
@@ -431,72 +533,13 @@ static int i2s_mcux_config(const struct device *dev, enum i2s_dir dir,
...
-		}
-	} else {
-		if (i2s_cfg->options & I2S_OPT_BIT_CLK_SLAVE) {
-			config.masterSlave =
-				kSAI_Bclk_Slave_FrameSync_Master;
-		} else {
-			config.masterSlave = kSAI_Master;
-		}
-	}
+	const bool is_mclk_master = i2s_cfg->options & I2S_OPT_BIT_CLK_MASTER;
```
Comment (NickolasLapp) [inline drivers/i2s/i2s_mcux_sai.c:536]: This line is broken because `I2S_OPT_BIT_CLK_MASTER` is 0, so this is always zero.
https://github.com/zephyrproject-rtos/zephyr/blob/e9b288b7137e5fb6ded18334aaa5a5f9c23ebb17/include/zephyr/drivers/i2s.h#L177

This needs to be a check for `i2s_cfg->options & I2S_OPT_BIT_CLK_SLAVE` or something similar.

File: drivers/i2s/i2s_mcux_sai.c [hunk 2]
```diff
@@ -333,13 +434,14 @@ static void enable_mclk_direction(const struct device *dev, bool dir)
 	const struct i2s_mcux_config *dev_cfg = dev->config;
 	uint32_t offset = dev_cfg->mclk_pin_offset;
 	uint32_t mask = dev_cfg->mclk_pin_mask;
-	uint32_t *gpr =  (uint32_t *)DT_REG_ADDR(DT_NODELABEL(iomuxcgpr)) + offset;
+	uint32_t *gpr = (uint32_t *)DT_REG_ADDR(DT_NODELABEL(iomuxcgpr)) + offset;
```
Comment (NickolasLapp) [inline drivers/i2s/i2s_mcux_sai.c:437]: This is not producing the correct result. Offset is the raw offset (in bytes), but the order of operations is adding `offset` uint32_t's, so the resultant gpr register is off by 4x.
On the RT1060 this results in register 0x400ac010 being written, when it should be 0x400ac004

Should be: 
```suggestion
	uint32_t *gpr = (uint32_t *)(DT_REG_ADDR(DT_NODELABEL(iomuxcgpr)) + offset);
```

**Review by NickolasLapp — CHANGES_REQUESTED** [review]

File: drivers/i2s/i2s_mcux_sai.c (hunk 2 above)
Comment (DerekSnell) [reply drivers/i2s/i2s_mcux_sai.c]: updated, thanks @NickolasLapp

**Review by danieldegrasse — APPROVED** [review]

**Review by NickolasLapp — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
Test passing on my modified board
