### PR TITLE
drivers: enet: eth_nxp_enet_qos_mac: handle errors in RX queue worker

### LINKED ISSUE #89435: ETH NXP MCXN: eth_nxp_enet_qos: DMA RX halt after no DMA buffer available
**Describe the bug**
the eth_nxp_enet_qos is used for MCXN947 that I use.
In the ethernet module; by default there are 4 DMA buffer positions reserved.
In the "after DMA completed" interrupt the work to handle that buffers is redirected to a work_queue.
The queue handler checks the buffer status by checking the DMA descriptors.

The DMA module uses on next rx packet the next free buffer.

Now in my case the DMA stops to receive packets after all buffers have been filled in one moment.
That means when there is not a single free buffer available.

This is very unfortunate. The DMA should restart when there is free buffer.

I discovered weird overload behavior since I started working with MCXN947.
This bug report is for the RX DMA direction only

I debuged a bit into the problem.
When the last buffer if given from the DMA to the ISR in the register DMA Channel 0 Status (DMA_CH0_STATUS): The "Receive Buffer Unavailable" is asserted

Description according to the datasheet:
```
Receive Buffer Unavailable
This bit indicates that the application owns the next descriptor in the Receive list, and the DMA cannot
acquire it. The Rx process is suspended. To resume processing Rx descriptors, the application should
change the ownership of the descriptor and issue a Receive Poll Demand command. If this command is
not issued, the Rx process resumes when the next recognized incoming packet is received. In ring mode,
the application should advance the Receive Descriptor Tail Pointer register of a channel. This bit is set only
when the DMA owns the previous Rx descriptor.
Access restriction applies. Self-set to 1 on internal event. Setting 1 clears. Setting 0 has no effect.
0b - Receive Buffer Unavailable status not detected
1b - Receive Buffer Unavailable status detected
```

currently all status flags are cleared by the driver, no error handling.

**To Reproduce**
The default buffer size is 4:
`CONFIG_ETH_NXP_ENET_QOS_RX_BUFFER_DESCRIPTORS=4`

I have a small python script to send some udp packets:
```
import socket

ip = "10.2.19.1"
port = 12345

for loop in range(4):
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        data = loop.to_bytes(8, byteorder='big')
        sock.sendto(data, (ip, port))
```
usually all the packets has been transmitted until the workqueue handles the received buffers.

That means it is really good reproducible to bring the DMA to halt.
Just make the number of packets sent >= number of RX buffers.

**Expected behavior**
A restart of RX DMA when free buffer available.

The driver should only clear the "Receiver Buffer Unavailable" when it freed buffer and then emit the "Receive Poll Command" according to the datasheet.

**Impact**

The network stack does not work as expected.
No Receive possible.
Workaround is a reboot.

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Ubuntu 
 - Toolchain SDK 0.17.0
 - Zephyr 4.1.99 as of May 3rd

**Additional context**

### PR DESCRIPTION
**Pull request by theadib**
Handle each error individually.
Do not skip RX loop on first error.
Revise DMA buf size to CONFIG_NET_BUF_DATA_SIZE.

fixes #89435

I am working on FRDM_MCXN947

### CODE REVIEW

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 1]
```diff
@@ -190,12 +195,16 @@ static void eth_nxp_enet_qos_rx(struct k_work *work)
 		pkt = net_pkt_rx_alloc(K_NO_WAIT);
 
 		if (!pkt) {
-			LOG_ERR("Could not alloc RX pkt");
-			goto error;
+			LOG_ERR("Could not alloc new RX pkt");
+			/* error: can not forward this buffer, drop this buffer, reuse immediately
+			 */
+			net_pkt_unref(pkt);
```
Comment (pdgendt) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:201]: Why call `net_pkt_unref(NULL);`?

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 2]
```diff
@@ -177,6 +181,7 @@ static void eth_nxp_enet_qos_rx(struct k_work *work)
 	struct net_buf *buf;
 	size_t pkt_len;
 
+	LOG_DBG("iteration work:%p, rx_data:%p, data:%p", work, rx_data, data);
 	/* We are going to find all of the descriptors we own and update them */
 	for (int i = 0; i < NUM_RX_BUFDESC; i++) {
```
Comment (stanislav-poboril) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:186]: This should not go from the descriptor with index 0 to NUM_RX_BUFDESC - 1.
Instead, it should begin from the position which is after the position we have processed the last time (accounting for descriptor ring wrapping at the end).

DMA receives into 0, 1, 2, 3, 0, 1, 2, 3, 0.... and we should follow processing it 0, 1, 2, 3, 0...

For example, imagine there are 4 receive descriptors and this situation:

DMA copies first received frame (or its part) to the buffer held by descriptor with index 0.
Next index 1, then index 2.
We read out those frames.
Now forget about "Receive Buffer Unavailable" situation for a moment.
The next frame is longer than 2 * CONFIG_NET_BUF_DATA_SIZE.
DMA will put first CONFIG_NET_BUF_DATA_SIZE bytes into the buffer pointed by the descriptor with index 3.
RDESC3 will have FD flag (first descriptor - first buffer of a frame) set.
Then DMA will copy next CONFIG_NET_BUF_DATA_SIZE bytes into the buffer pointed by the descriptor with index 0. RDESC3 will have neither FD nor LD flags set.
The rest of the frame's bytes will be copied into the buffer of descriptor with index 1. RDESC3 will have LD (last descriptor - last buffer of a frame) set.

We should read buffers 3, 2, 1 and compose net_pkt with fragments in this order.

Back to the "Receive Buffer Unavailable", RX DMA will suspend in this case until we reset tail pointer.
I don't know if we will be fast enough, maybe such frame will be lost anyway.
The manual suggests to have at least such a number of descriptors that two frames of max length could fit before we start to read them.

But even if each frame can completely fit into a single buffer, imagine we are for example receiving UDP datagrams.
Going from index 0 can shuffle their order unnecessarily. Or it can require reordering of TCP segments at the TCP/IP stack side.

So we should maintain next read index in struct nxp_enet_qos_rx_data.

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 3]
```diff
@@ -190,12 +195,15 @@ static void eth_nxp_enet_qos_rx(struct k_work *work)
 		pkt = net_pkt_rx_alloc(K_NO_WAIT);
```
Comment (stanislav-poboril) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:195]: Since the code bellow can skip descriptors if something fails, we should make sure there is FD flag set in RDESC3, marking first buffer of a received frame, when allocating net_pkt for this descriptor's buffer.
Otherwise such descriptor should be also skipped and returned to DMA.

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 4]
```diff
@@ -226,25 +237,39 @@ static void eth_nxp_enet_qos_rx(struct k_work *work)
 		if (net_recv_data(data->iface, pkt)) {
```
Comment (stanislav-poboril) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:237]: We should pass this pkt to the TCP/IP stack only if the LD (last descriptor - last buffer of a frame) is set.
Otherwise we must keep adding fragments from other descriptors to the allocated pkt and provide it to upper layers once having pkt with all fragments of a complete buffer.

Frame in 3 descriptors:
FD flag - allocate pkt, add first fragment
no flag - add fragment to previously allocated pkt
LD flag - add fragment to pkt and call net_recv_data.

Frame in 1 descriptor:
FD and LD flag - allocate pkt, add the only fragment and call net_recv_data.

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 5]
```diff
@@ -226,25 +237,39 @@ static void eth_nxp_enet_qos_rx(struct k_work *work)
...
 
-error:
-	net_pkt_unref(pkt);
-	eth_stats_update_errors_rx(data->iface);
+	if (ENET_QOS_REG_GET(DMA_CH_DMA_CHX_STAT, RBU, dma_ch0_stat)) {
+		LOG_DBG("handle RECEIVE BUFFER UNDERRUN in worker");
+		base->DMA_CH[0].DMA_CHX_STAT = ENET_QOS_REG_PREP(DMA_CH_DMA_CHX_STAT, RBU, 0b1);
+
+		/* When the DMA reaches the tail pointer, it suspends. Set to last descriptor */
+		base->DMA_CH[0].DMA_CHX_RXDESC_TAIL_PTR = ENET_QOS_REG_PREP(
```
Comment (stanislav-poboril) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:266]: This could be possibly be just rewritten to the same value it already has:

base->DMA_CH[0].DMA_CHX_RXDESC_TAIL_PTR = base->DMA_CH[0].DMA_CHX_RXDESC_TAIL_PTR;

I don't know what is better.

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 6]
```diff
@@ -254,22 +279,39 @@ static void eth_nxp_enet_qos_mac_isr(const struct device *dev)
...
+	uint32_t mac_interrupts = base->MAC_INTERRUPT_STATUS;
+	uint32_t mac_rx_tx_status = base->MAC_RX_TX_STATUS;
+	uint32_t dma_interrupts = base->DMA_INTERRUPT_STATUS;
+	uint32_t dma_ch0_interrupts = base->DMA_CH[0].DMA_CHX_STAT;
 
-	base->DMA_CH[0].DMA_CHX_STAT = 0xFFFFFFFF;
+	/* clear pending bits except RBU
+	 * handle the receive underrun in the worker
+	 */
+	base->DMA_CH[0].DMA_CHX_STAT =
```
Comment (stanislav-poboril) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:290]: If RBU happens without RI, this handler will not be fired unless enet_qos_start enables interrupts also for AIE and RBUE.
(Although RBU flag will be set in DMA channel status register.)

RBU then needs to be cleared along with AIS flag, so it will maybe complicate handling RBU in RX thread.

When RBU flag is set without RI:
DMA attempted to receive a frame which does not fit into all buffers of all RX descriptors combined.
Then interrupt will not fire without the enablement above, and all descriptors will be owned by application and none of the descriptors will have LD flag set.

**Review by stanislav-poboril — CHANGES_REQUESTED** [review]
Thank you @theadib for this work.
My comments are mostly about these two situations:
- Processing of the received buffers should be in a ring fashion with wrapping instead of always starting from 0.
- Received frames can be stored in multiple descriptors' buffers if buffers are short. So either it should be correctly reassembled from such fragments. Or this could perhpas be ignored if we disallow configuration of buffers which do not fit frames of maximum length.

**Comment by theadib** [comment]
Hello @stanislav-poboril , thanks for your time reviewing this PR.
Yes, I know there might be issue with ethernet packets spanning over multiple DMA buffer will be a problem.
This PR I would like to address the issue that DMA just aborts on buffer under run.
I have this test case described in the reference Bug report that leads to this situation.
This PR solves that situation (only).
So I focus on the RBU situation.


There is an issue pending #89581
Probably this is for the case ethernet frame is larger than DMA buffer.
Then 
- the queue must be read from head to tail,
- care must be taken to only submit buffer from first packet to last packet, or dropped completly.

If I have time and a test case then I can continue to work on that.
But I can not solve all in one go.
I only have FRDM_MCXN947 for testing.

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c (hunk 4 above)
Comment (theadib) [reply drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:245]: I force pushed a version to just drop these DMA buffers.
left for implementation in other PR.

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c (hunk 6 above)
Comment (theadib) [reply drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c]: The code now clears all flags in the ISR but forwards an atomic variable containing RBU information to the worker.
Now the worker is called when RBU is set without RI.

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c (hunk 3 above)
Comment (theadib) [reply drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:203]: now the DMA buffers are dopped.
Awaiting the next PR.

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 7]
```diff
@@ -254,22 +288,46 @@ static void eth_nxp_enet_qos_mac_isr(const struct device *dev)
...
-	volatile uint32_t mac_rx_tx_status = base->MAC_RX_TX_STATUS;
-	volatile uint32_t dma_interrupts = base->DMA_INTERRUPT_STATUS;
-	volatile uint32_t dma_ch0_interrupts = base->DMA_CH[0].DMA_CHX_STAT;
+	uint32_t mac_interrupts = base->MAC_INTERRUPT_STATUS;
+	uint32_t mac_rx_tx_status = base->MAC_RX_TX_STATUS;
+	uint32_t dma_interrupts = base->DMA_INTERRUPT_STATUS;
+	uint32_t dma_ch0_interrupts = base->DMA_CH[0].DMA_CHX_STAT;
 
-	mac_interrupts; mac_rx_tx_status;
+	/* clear pending bits except RBU
```
Comment (stanislav-poboril) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c:296]: Now RBU is also cleared here, so maybe the first part of the comment is a little confusing.

**Comment by stanislav-poboril** [comment]
> Yes, I know there might be issue with ethernet packets spanning over multiple DMA buffer will be a problem. This PR I would like to address the issue that DMA just aborts on buffer under run. I have this test case described in the reference Bug report that leads to this situation. This PR solves that situation (only). So I focus on the RBU situation.

Hello @theadib, I agree, thanks.
I did some experiments with the head to tail reading and frames spanning multiple buffers, so I may work on that after this PR is merged.

**Review by stanislav-poboril — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]
