### PR TITLE
bluetooth: shell: fix AD length validation

### LINKED ISSUE #99979: [Coverity CID: 434615] Unsigned compared against 0 in subsys/bluetooth/host/shell/bt.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/main/subsys/bluetooth/host/shell/bt.c

Category: Control flow issues
Function: `ead_update_ad`
Component: Bluetooth
CID: [434615](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434615)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/shell/bt.c#L5014

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434615

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

Also see the related [Coverity documentation](https://docs.zephyrproject.org/latest/contributing/coverity.html) for more information.

### PR DESCRIPTION
**Pull request by SrivastavaOm29**
Fix validation of AD length handling in the Bluetooth shell. Reject zero-length AD fields before subtracting the AD type size.

The previous implementation compared an unsigned length against zero after subtraction, making the error path unreachable.

Fixes #99979

### CODE REVIEW

File: subsys/bluetooth/host/shell/bt.c [hunk 1]
```diff
@@ -5176,13 +5176,13 @@ int ead_update_ad(void)
...
 		ad = &ad_structs[ad_structs_idx];
 
-		/* the data_len from bt_data struct doesn't include the size of the type */
-		ad->data_len = bt_shell_ead_data[idx] - 1;
-
-		if (ad->data_len < 0) {
-			/* if the len is less than 0 that mean there is not even a type field */
-			bt_shell_error("Failed to update AD due to malformed AD.");
-			return -ENOEXEC;
+		/* bt_shell_ead_data[idx] includes the AD type byte. */
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt.c]: Took me a little time to understand the `bt_shell_ead_data` array and the comment here. Suggest to expand on it a bit


```suggestion
		/* bt_shell_ead_data[idx] points to the start of an encrypted advertising tuple, so bt_shell_ead_data[idx] is the length field, bt_shell_ead_data[idx + 1] is the type field and bt_shell_ead_data[idx + 2] is the start of the value */
```

File: subsys/bluetooth/host/shell/bt.c [hunk 2]
```diff
@@ -5176,13 +5176,13 @@ int ead_update_ad(void)
...
+		if (bt_shell_ead_data[idx] > 0) {
+				ad->data_len = bt_shell_ead_data[idx] - 1;
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt.c]: It's failing our compliance check because you've added too many tabs :) Looks like you've added 2 tabs per indentation level, which is incorrect (should be one). 

Tabs in Zephyr is 8 spaces btw :)

**Review by Thalley — CHANGES_REQUESTED** [review]
Thanks for your PR; please fix the tab/indentation issues

File: subsys/bluetooth/host/shell/bt.c (hunk 1 above)
Comment (SrivastavaOm29) [reply subsys/bluetooth/host/shell/bt.c]: Thanks. I have made the required changes as suggested by you.

File: subsys/bluetooth/host/shell/bt.c (hunk 2 above)
Comment (SrivastavaOm29) [reply subsys/bluetooth/host/shell/bt.c]: I've fixed the indentation issues as well.

**Review by Thalley — APPROVED** [review]

**Review by HaavardRei — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
