### PR TITLE
net: Fix inet_pton IPv4 implementation

### LINKED ISSUE #84593: Zephyr posix inet_pton incorrect conversions.
**Describe the bug**
Zephyr implementation of inet_pton is probably not working properly for IP v4 addresses.
For example for the ip4 ip string in the format "192.168.1.400", the inet_pton function should return avalue other than 1. 
Instead, inet_pton returns 1 and in the address structure the result ip is malformed.

**To Reproduce**

issue code like below:

```
  struct in_addr addr;
  char stripv4[] = "192.168.1.400";
  int ret = inet_pton(AF_INET, stripv4, &addr);
  if (ret == 1) {
    LOG_INF("Parsed test IP from string: %s to %d.%d.%d.%d", stripv4,
            addr.s4_addr[0], addr.s4_addr[1], addr.s4_addr[2], addr.s4_addr[3]);
  }
```

**Expected behavior**
Log information should not show as the ret value should be different than 1

**Impact**
Instead, log system with minimal logs turned on, presents :
"I: Parsed test IP from string: 192.168.1.400 to 192.168.1.144"
The parsed IP address from the string is incorrect, returned value should be different than 1.

This annoyance involves adding additional sanity checks for IP addresses as they are wrongly parsed from the string.

**Environment (please complete the following information):**

We are using Zephyr 3.7.1

**Additional context**

### PR DESCRIPTION
**Pull request by jukkar**
The conversion from IPv4 string presentation to numeric value did not check if the individual address value was between 0 and 255 inclusive.

Add also test case for this.

Fixes #84593

### CODE REVIEW

File: subsys/net/ip/utils.c [hunk 1]
```diff
@@ -349,8 +349,14 @@ int z_impl_net_addr_pton(sa_family_t family, const char *src,
 
 		for (i = 0; i < sizeof(struct in_addr); i++) {
 			char *endptr;
+			int val;
 
-			addr->s4_addr[i] = strtol(src, &endptr, 10);
+			val = strtol(src, &endptr, 10);
+			if (val < 0 || val > 255) {
```
Comment (pdgendt) [inline subsys/net/ip/utils.c:355]:
```suggestion
			if (val < 0 || val > UINT8_MAX) {
```

File: tests/net/socket/misc/src/main.c [hunk 2]
```diff
@@ -51,6 +51,9 @@ ZTEST_USER(socket_misc_test_suite, test_inet_pton)
 
 	res = zsock_inet_pton(AF_INET6, "a:b:c:d:0:1:2:3z", buf);
 	zassert_equal(res, 0, "");
+
+	res = zsock_inet_pton(AF_INET, "192.0.2.400", buf);
+	zassert_equal(res, 0, "");
```
Comment (pdgendt) [inline tests/net/socket/misc/src/main.c:56]: Reading the implementation, I think you can easily read beyond the data. If the data is provided from an external source, and for example `"0.0"` is passed, this will call `strtol` to the data after the string (twice).

**Comment by cfriedt** [comment]
I've always been curious as to why these `zsock_inet_pton()` and `zsock_inet_ntop()` were implemented as `__syscall`s. There are no kernel or private resources to synchronize on.

On machines with an mmu or mpu, there would be a fault of reading or writing outside of the allowed addressable memory.

In any case, the only thing I can suggest is to look at some of the degenerate cases such as the one that @pdgendt highlighted. But also, it would be good to cross-reference against e.g. the glibc or musl implementations or picolibc. See what kinds of invalid input those detect and try to match common behaviour.

Ofc, one could technically implement a bunch of exhaustive tests in the POSIX test suite, but it would be nice if the native Zephyr call were just compliant.

**Comment by jukkar** [comment]
Added more checks (from stackoverflow) and added tests.
Just wondering should we disallow perfectly valid IPv4 addresses like `0`, `1`, `0.0` etc. (so values < 256). Atm we do not support the "plain int" addresses like `2130706433` which is `127.0.0.1`

File: tests/net/socket/misc/src/main.c [hunk 3]
```diff
@@ -51,6 +51,24 @@ ZTEST_USER(socket_misc_test_suite, test_inet_pton)
...
+	zassert_equal(res, 1, "");
+
+	res = zsock_inet_pton(AF_INET, "0", buf);
+	zassert_equal(res, 1, "");
+
+	res = zsock_inet_pton(AF_INET, "1", buf);
+	zassert_equal(res, 1, "");
+
+	res = zsock_inet_pton(AF_INET, "256", buf);
+	zassert_equal(res, 0, "");
```
Comment (pdgendt) [inline tests/net/socket/misc/src/main.c:71]: Is this valid?

Comment (cfriedt) [reply tests/net/socket/misc/src/main.c:71]: Iirc this function returns 1 if a valid address is matched, so I think the test seems to be checking that it's invalid (which looks right to me). Not sure if my intuition agrees with other implementations ATM tho

File: subsys/net/ip/utils.c [hunk 4]
```diff
@@ -349,8 +349,49 @@ int z_impl_net_addr_pton(sa_family_t family, const char *src,
 
 		for (i = 0; i < sizeof(struct in_addr); i++) {
```
Comment (pdgendt) [inline subsys/net/ip/utils.c:350]: The function currently loops all characters 3 times, an alternative with a single loop:

```c
		struct in_addr *addr = (struct in_addr *)dst;
		uint8_t index = 0, digits = 0;
		uint16_t value = 0;

		(void)memset(addr, 0, sizeof(struct in_addr));

		while (index < sizeof(struct in_addr)) {
			if (*src == '\0' || *src == '.') {
				if (digits == 0 || value > UINT8_MAX) {
					return -EINVAL;
				}

				addr->s4_addr[index] = value;

				if (*src == '\0') {
					break;
				}

				index++;
				digits = 0;
				value = 0;
			} else if ('0' <= *src && *src <= '9') {
				if (++digits > 3) {
					/* Number too large */
					return -EINVAL;
				}
				value *= 10;
				value += *src - '0';
			} else {
				/* Invalid character */
				return -EINVAL;
			}

			src++;
		}
```

Comment (cfriedt) [reply subsys/net/ip/utils.c:350]: I asked chatgpt to generate a list of invalid IPv4 addresses. I think most things should be covered above, but a couple that stood out:

- empty segments (e.g. 192..1.0 - above, we would need to check that digits is also > 0)
- preceding zeros or non-singular zero (e.g. 192.168.000.1 or 192.168.0.01 - if the first digit of an octet is zero, the octet must be of length 1)

Comment (pdgendt) [reply subsys/net/ip/utils.c:350]: Empty segments is checked with `digits == 0`. I thought about preceding zeroes, but didn't wanted to add the complexity..

Can be checked with the following code if the delimiter or the end was found.
```c
if ((digits > 1 && value < 10) || (digits > 2 && value < 100) {
	/* Preceding zeroes */
	return -EINVAL;
}
```

File: tests/net/socket/misc/src/main.c [hunk 5]
```diff
@@ -51,6 +51,24 @@ ZTEST_USER(socket_misc_test_suite, test_inet_pton)
 
 	res = zsock_inet_pton(AF_INET6, "a:b:c:d:0:1:2:3z", buf);
 	zassert_equal(res, 0, "");
+
+	res = zsock_inet_pton(AF_INET, "192.0.2.400", buf);
+	zassert_equal(res, 0, "");
+
+	res = zsock_inet_pton(AF_INET, "0.0", buf);
```
Comment (rlubos) [inline tests/net/socket/misc/src/main.c:58]: I might have missed some discussion, but I'm not sure I follow why should these be considered a valid IP addresses? Even checked with native Linux app, and they're all rejected by `inet_pton()`:
```
inet_pton returned 0 for 0.0
inet_pton returned 0 for 0.1
inet_pton returned 0 for 0
inet_pton returned 0 for 1
```

Comment (cfriedt) [reply tests/net/socket/misc/src/main.c:58]: I think they probably are not valid IP addresses.

Comment (jukkar) [reply tests/net/socket/misc/src/main.c:58]: Ok, lets ban these short addresses then. I have seen these used as IP addresses but it probably was not with `inet_pton` but with some other tool.

Comment (piotrParf) [reply tests/net/socket/misc/src/main.c:58]: I do not think they are invalid at all, they may be unusable. Those adresses may be invalid on the public internet or have a designated not "free for all" usage.
The IANA list: https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml for example lists addresses 0.0.0.0 and its subnet as valid but to limited use.

**Comment by jukkar** [comment]
* Updated according to comments

**Review by rlubos — APPROVED** [review]

File: subsys/net/ip/utils.c [hunk 6]
```diff
@@ -335,24 +335,63 @@ int z_impl_net_addr_pton(sa_family_t family, const char *src,
...
+		 *    - Separated by dots (.)
+		 *    - No leading zeros in each octet
+		 */
 
-			addr->s4_addr[i] = strtol(src, &endptr, 10);
+		while (index < sizeof(struct in_addr)) {
+			if (*src == '\0' || *src == '.') {
+				if (*src == '.') {
+					count++;
+				}
```
Comment (pdgendt) [inline subsys/net/ip/utils.c:355]: You could move the `index++` here and verify that `index == sizeof(struct in_addr)` after the loop, that way you can remove `count` altogether.

**Review by pdgendt — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
