### PR TITLE
tests: Bluetooth: Mesh: restore tinycrypt mesh bsim

### LINKED ISSUE #82323: Bluetooth: Mesh: Revert removal of tests with TinyCrypt
## Introduction

After https://github.com/zephyrproject-rtos/zephyr/pull/79931 PR the Bluetooth mesh option with TinyCrypt crypto library `CONFIG_BT_MESH_USES_TINYCRYPT` has been deprecated. Due to the Zephyr deprecation procedure all tests (unit and BabbleSim) that use this option were switched from TinyCrypt to PSA Crypto API with mbedTLS library (`CONFIG_BT_MESH_USES_MBEDTLS_PSA`).

### Problem description

Managing the encryption keys in the Bluetooth mesh with TinyCrypt and PSA Crypto API is different. The TinyCrypt keys are kept in RAM as a plain text, while PSA Crypto API provides key ids and the mesh stack doesn't have direct access to the keys. This also applies to the way the keys are stored in a non-volatile memory. When a mesh device boots up, it restores TinyCrypt keys as plain text by reading them through the settings subsystem. With PSA Crypto API only key ids are restored by the mesh stack. This makes impossible to flash a new firmware with mesh stack built with PSA Crypto API support on top of mesh stack built with TinyCrypt without proper precautions. As a minimum viable solution, users must unprovision mesh devices before flashing the new firmware with PSA Crypto API support.

The `CONFIG_BT_MESH_USES_TINYCRYPT` option stays for 2 more releases, however we can't guarantee that even minum viable solution works since all tests were removed.

The key points to revert tests are:
- Users may still rely on the TinyCrypt-based option for legacy projects or ongoing deployments. Ensuring tests remain for TinyCrypt helps maintain backward compatibility for these users during the transition period. It gives confidence that the feature works as intended, even if it’s deprecated, until the complete removal occurs.
- This introduces a risk of regressions or untested code paths, when shared components of the mesh stack are modified.
- Testing both options within the same release ensures that users can verify the correctness of their transition processes (e.g., unprovisioning/reprovisioning devices). Without these tests, debugging issues related to mixed environments becomes much harder.
- Keeping tests enables better documentation, helping users understand how to migrate and verify their setups. This avoids potential confusion or misconfigurations during the transition.
- Keeping tests during the deprecation period ensures that the feature is not only present but also functional and reliable until its formal removal.

### Proposed change

We want to provide smooth and predictable transition for users which we can't guarantee without running tests with TinyCrypt. Therefore we would like to revert the removal of the Bluetooth mesh tests (unit + bsim) with TinyCrypt and keep them running until TinyCrypt is finally removed.

### PR DESCRIPTION
**Pull request by alxelax**
Commit restores ble mesh bsim tests with tinycrypt.

### CODE REVIEW

File: tests/bsim/bluetooth/mesh/src/test_brg.c [hunk 1]
```diff
@@ -246,22 +246,26 @@ static void bridge_entry_remove(uint16_t src, uint16_t dst, uint16_t net_idx1, u
...
-	int err;
 
 	LOG_INF("Configuring bridge...");
 
+	ASSERT_OK(
+		bt_mesh_cfg_cli_net_transmit_set(0, BRIDGE_ADDR, BT_MESH_TRANSMIT(2, 20), &status));
+	if (status != BT_MESH_TRANSMIT(2, 20)) {
+		FAIL("Net transmit set failed (status %u)", status);
+	}
+
```
Comment (omkar3141) [inline tests/bsim/bluetooth/mesh/src/test_brg.c:257]: This seems unrelated to bringing TC support back?

File: tests/bsim/bluetooth/mesh/tests_scripts/blob_mdls/blob_srv_persistence.sh [hunk 2]
```diff
@@ -36,27 +36,27 @@ RunTestFlash blob_recover_phase \
    blob_cli_stop -flash_rm blob_srv_stop -flash_rm -- -argstest expected-phase=4
 
 # The same test but with PSA crypto
-overlay="overlay_pst_conf_overlay_psa_conf"
+overlay="overlay_pst_conf_overlay_ss_conf_overlay_psa_conf"
```
Comment (omkar3141) [inline tests/bsim/bluetooth/mesh/tests_scripts/blob_mdls/blob_srv_persistence.sh:39]: Change the comment as well?

File: tests/bsim/bluetooth/mesh/prj.conf [hunk 3]
```diff
@@ -74,4 +74,5 @@ CONFIG_BT_TESTING=y
 # Needed for RPR tests due to huge amount of retransmitted messages
 CONFIG_BT_MESH_MSG_CACHE_SIZE=64
 
-CONFIG_MBEDTLS_PSA_KEY_SLOT_COUNT=64
+# Enable tinycrypt as a crypto backend
```
Comment (omkar3141) [inline tests/bsim/bluetooth/mesh/prj.conf:77]: Is it necessary to remove "CONFIG_MBEDTLS_PSA_KEY_SLOT_COUNT"?

Comment (alxelax) [reply tests/bsim/bluetooth/mesh/prj.conf:77]: It is set in psa overlay. No necessity to keep the option in the file which it doesn't belong.

File: tests/bsim/bluetooth/mesh/src/test_brg.c (hunk 1 above)
Comment (alxelax) [reply tests/bsim/bluetooth/mesh/src/test_brg.c:257]: Nop. When TC is back, some collisions happen. This change adds more transmission attempts to solve this. The change doesn't have sense without TC.

File: tests/bsim/bluetooth/mesh/tests_scripts/blob_mdls/blob_srv_persistence.sh (hunk 2 above)
Comment (alxelax) [reply tests/bsim/bluetooth/mesh/tests_scripts/blob_mdls/blob_srv_persistence.sh:39]: comment is correct and doesn't require changes

**Review by omkar3141 — DISMISSED** [review]

**Review by PavelVPV — DISMISSED** [review]

**Review by PavelVPV — APPROVED** [review]

**Review by omkar3141 — APPROVED** [review]
