### PR TITLE
Bluetooth: GATT: Fix byte order for database hash

### LINKED ISSUE #17857: GATT: Incorrect byte order for GATT database hash
**Describe the bug**
bt_smp_aes_cmac uses BE data, while Core 5.1, Vol 3, Part F, 3.3.1 says
"Multi-octet fields within the GATT profile shall be sent least
significant octet first (little-endian) with the exception of the
Characteristic Value field. The Characteristic Value and any fields
within it shall be little-endian unless otherwise defined in the
specification which defines the characteristic."

**To Reproduce**
Run GATT/SR/GAS/BV-02-C test case

**Expected behavior**
Test case pass

**Impact**
Result db hash is in BE order, Test case fail

### PR DESCRIPTION
**Pull request by MariuszSkamra**
Core 5.1, Vol 3, Part F, 3.3.1
"Multi-octet fields within the GATT profile shall be sent least
significant octet first (little-endian) with the exception of the
Characteristic Value field. The Characteristic Value and any fields
within it shall be little-endian unless otherwise defined in the
specification which defines the characteristic."

Fixes: GATT/SR/GAS/BV-02-C
Fixes: #17857
Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by ioannisg** [comment]
@MariuszSkamra @carlescufi is this to be back-ported?

**Review by Vudentz — APPROVED** [review]
LGTM

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -420,6 +420,13 @@ static void db_hash_gen(bool store)
 		return;
 	}
 
+	/**
+	 * Core 5.1, Vol 3, Part F, 3.3.1 says that multi-octet Characteristic
+	 * Values shall be LE unless otherwise defined in specification,
+	 * but bt_smp_aes_cmac uses BE data so we swap
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c]: Id adjust reflect this text to include that although the spec doesn't states the endianess of the hash the PTS does expect it to be in little endianess while cmac always calculates the hash in big endianess.

Comment (MariuszSkamra) [reply subsys/bluetooth/host/gatt.c]: OK

**Review by joerchan — APPROVED** [review]
Looks good. Maybe we should document in `bt_smp_aes_cmac` that is expects data (and key?) in BE format?

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -420,6 +420,15 @@ static void db_hash_gen(bool store)
 		return;
 	}
 
+	/**
+	 * Core 5.1 does not states the endianess of the hash.
```
Comment (ioannisg) [inline subsys/bluetooth/host/gatt.c]: Does not state

**Review by ioannisg — COMMENTED** [review]
Just a minor typo in the comment, from my side.

**Comment by MariuszSkamra** [comment]
> Just a minor typo in the comment, from my side.

done
