### PR TITLE
kernel/sched: Fix SMP must-wait-for-switch conditions in abort/join

### LINKED ISSUE #58116: kernel: thread: race condition between create and join
**Describe the bug**
While investigating #56163 and digging through pthreads, testing showed that `k_thread_create()` and `k_thread_join()` also exhibit a race condition when re-using the same `struct k_thread`s over and over again.

It's not something regularly seen in production at the moment, and was only detected by accident. Originally reported [here](https://github.com/zephyrproject-rtos/zephyr/pull/57637#issuecomment-1556168811).

On the kernel side, this mainly seems to be an issue with smp platforms.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `qemu_x86_64`, `qemu_cortex_a53_smp`, `qemu_riscv64_smp`, `qemu_riscv32_smp`
 - What have you tried to diagnose or workaround this issue? Wrote a testsuite (#58115). Note, pthreads are disabled in this suite currently, so all failures are `k_thread` at the moment. It happens on all libc configurations and most smp platforms.
 - Is this a regression? Probably not although it's hard to say. 
 - ...

**To Reproduce**
1. `twister -i -T tests/posix/pthread_pressure`
2. see errors

**Expected behavior**
Tests passing ideally 100% of the time on all platforms.

**Impact**
It seems to be the opposite of what several contributors and maintainers expect, and is possibly just a corner case that did not receive a lot of traffic.

**Logs and console output**
E.g.
```
ERROR   - *** Booting Zephyr OS build zephyr-v3.3.0-4124-gf67ff9c38640 ***
Running TESTSUITE pthread_pressure
===================================================================
START - test_k_thread_create_join
I: NUM_THREADS: 2
I: TEST_NUM_CPUS: 2
I: TEST_DURATION_S: 10
I: TEST_DELAY_US: 0
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/kernel/sched.c:1785
	aborted _current back from dead
E:      a0: 0000000000000004    t0: 0000000000000000
E:      a1: 00000000000006f9    t1: 0000000000000009
E:      a2: 0000000080009d98    t2: 0000000000000000
E:      a3: 0000000000000000    t3: 0000000000000001
E:      a4: 0000000000000000    t4: 0000000000000023
E:      a5: 0000000000000001    t5: 000000008000b2b0
E:      a6: 0000000000000001    t6: 0000000080006514
E:      a7: 0000000000000001
E:      ra: 00000000800063c4
E:    mepc: 00000000800017e0
E: mstatus: 0000000a00021880
E: 
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: (nil) (unknown)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.1
 - Commit SHA or Version used: d01780fc9403166d250ded3d02372a7e1a9db4fd (main), v2.7.4

**Additional context**
#56163
#57637

### PR DESCRIPTION
**Pull request by andyross**
[This is @carlocaione's one-line fix from #58116 with some added refactoring from me to clean up docs and use some of the spiffy new APIs for spinning and barriers.]

As discovered by Carlo Caione, the k_thread_join code had a case where
it detected it had been called on a thread already marked _THREAD_DEAD
and exited early.  That's not sufficient.  The thread state is mutated
from the thread itself on its exit path.  It may still be running!

Just like the code in z_swap(), we need to spin waiting on the other
CPU to write the switch handle before knowing it's safe to return,
otherwise the calling context might (and did) do something like
immediately k_thread_create() a new thread in the "dead" thread's
struct while it was still running on the other core.

There was also a similar case in k_thread_abort() which had the same
issue: it needs to spin waiting on the other CPU to kill the thread
via the same mechanism.

Fixes #58116

### CODE REVIEW

File: kernel/include/kswap.h [hunk 1]
```diff
@@ -154,8 +156,12 @@ static ALWAYS_INLINE unsigned int do_swap(unsigned int key,
 		void *newsh = new_thread->switch_handle;
 
 		if (IS_ENABLED(CONFIG_SMP)) {
-			/* Active threads MUST have a null here */
+			/* Active threads must have a null here.  And
+			 * it must be seen before the scheduler lock
+			 * is released!
+			 */
 			new_thread->switch_handle = NULL;
+			barrier_dmem_fence_full(); /* write barrier */
```
Comment (andyross) [inline kernel/include/kswap.h:164]: Hilariously, after I was the one who said we should just merge the full barrier API first for simplicity and worry about read/write (ARM, traditional) and/or acquire/release/consume (C++ terms, sigh) complexity later...

...I hit a spot where there's a clear use for finer barrier control within mere days.  Still don't think it's wrong to have the conservative API though.

**Comment by cfriedt** [comment]
Taking a look right now.

**Review by npitre — APPROVED** [review]
Looks good and is holding up in testing.

**Comment by cfriedt** [comment]
It's a definite improvement. I think there are still a few cracks in pthreads  where water is getting through, but k_threads look good to me
https://pastebin.com/yEJ2CbAF

**Review by cfriedt — APPROVED** [review]

**Comment by andyross** [comment]
FWIW, after the expected Keystone Cops hijinks getting the scripting to work, I have a rig with 32 of these running on arm64 in parallel.  They've been going a little over an hour now without issue, which is more testing in aggregate than either riscv platform got.   I'll let it run for the rest of the afternoon, but it seems pretty clear that @carlocaione found the single issue that was affecting that particular test.  The remaining pthread crashes are almost certainly higher level.

**Comment by cfriedt** [comment]
pthreads definitions has some windows where there are race conditions. 

My next question: @andyross , @carlocaione , @npitre - is there a list of PR's that should be backported to v2.7-branch, because this issue was first discovered there 😁

**Comment by andyross** [comment]
Regarding backports: this relies on brand new APIs, so it's not going to backport cleanly.  @carlocaione 's original one-line fix is what we probably want in older branches.  Though it's worth pointing out that as interesting as this was as a bug, it's actually going to be extremely rare in practice.  Even arm64  was going through **millions** of thread create/join cycles before it tripped.  Real apps just aren't ever going to do that; I'd view this as fairly low priority as a backport candidate.

**Comment by cfriedt** [comment]
> Regarding backports: this relies on brand new APIs, so it's not going to backport cleanly.  @carlocaione 's original one-line fix is what we probably want in older branches.  Though it's 

I'll give that a shot then
