### PR TITLE
Bluetooth: Controller: Separate SDU interval for C_to_P and P_to_C

### LINKED ISSUE #74544: Bluetooth: Controller: ISO: Does not support differen SDU intervals/latencies in each direction
**Describe the bug**
When create a CIG the application can choose to have difference SDU intervals and maximum transport latency in each direction, e.g. 10ms SDU interval from central to peripheral and 7.5ms SDU interval from peripheral to central. 

However doing this seems to trigger an assert. 

**To Reproduce**
1. Checkout https://github.com/zephyrproject-rtos/zephyr/pull/74495
2. Build and run https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bsim/bluetooth/audio/test_scripts/bap_unicast_client_async_group.sh
3. See error

**Expected behavior**
Expect the controller to either work with different values for each direction, or at the very least it should return an error. It should not assert. 

**Impact**
Annoyance as this is a arguably a corner case for most use cases. 

**Logs and console output**
```
======== BAP Unicast Client Aync Group parameters test =========

d_00: @00:00:00.000000  *** Booting Zephyr OS build v3.7.0-rc1-30-g1c84b5d85358 ***
d_00: @00:00:00.000000  [00:00:00.000,000] <dbg> bt_tbs: tbs_inst_init: inst 0x8259f60 index 0x00 provider_name Unknown
d_00: @00:00:00.000000  [00:00:00.000,000] <dbg> bt_tbs: tbs_inst_init: inst 0x825a4a0 index 0xff provider_name Generic TBS
d_00: @00:00:00.000000  [00:00:00.000,000] <dbg> bt_ots: bt_gatt_ots_l2cap_init: Initialized OTS L2CAP
d_00: @00:00:00.005768  [00:00:00.005,767] <inf> bt_hci_core: HW Platform: Nordic Semiconductor (0x0002)
d_00: @00:00:00.005768  [00:00:00.005,767] <inf> bt_hci_core: HW Variant: nRF52x (0x0002)
d_00: @00:00:00.005768  [00:00:00.005,767] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 3.7 Build 0
d_00: @00:00:00.005768  [00:00:00.005,767] <wrn> bt_id: vs_read_static_addr: No static addresses stored in controller
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_smp: bt_smp_init: LE SC enabled
d_00: @00:00:00.006488  [00:00:00.006,469] <inf> bt_hci_core: Identity: CC:AB:C3:77:B1:7A (random)
d_00: @00:00:00.006488  [00:00:00.006,469] <inf> bt_hci_core: HCI: version 5.4 (0x0d) revision 0x0000, manufacturer 0x05f1
d_00: @00:00:00.006488  [00:00:00.006,469] <inf> bt_hci_core: LMP: version 5.4 (0x0d) subver 0xffff
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_bap_unicast_client: bt_bap_unicast_client_new_audio_iso: New bap_iso 0x825d220
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_bap_unicast_client: unicast_group_add_stream: group 0x825d460 stream 0xf732a25c qos 0xf732a23c iso 0x825d220 dir 2
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_bap_iso: bt_bap_iso_bind_stream: bap_iso 0x825d220 stream 0xf732a25c dir source
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_bap_iso: bt_bap_iso_get_ep: iso 0x825d220 dir sink
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_bap_unicast_client: unicast_group_add_stream: group 0x825d460 stream 0xf732a284 qos 0xf732a24c iso 0x825d220 dir 1
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_bap_iso: bt_bap_iso_bind_stream: bap_iso 0x825d220 stream 0xf732a284 dir sink
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_bap_iso: bt_bap_iso_get_ep: iso 0x825d220 dir source
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_bap_unicast_client: bt_audio_cig_create: group 0x825d460
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_iso: bt_iso_chan_add: iso 0x82582c0 chan 0x825d220
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_iso: hci_le_set_cig_params: id 0, latency C to P 100, latency P to C 75, interval C to P 10000, interval P to C 7500, sca 0, packing 0, framing 0, num_cis 1
d_00: @00:00:00.006488  [00:00:00.006,469] <dbg> bt_iso: hci_le_set_cig_params: [0]: id 0, c_phy 2, c_sdu 40, c_rtn 2, p_phy 2, p_sdu 30, p_rtn 2
d_00: @00:00:00.006488  ASSERTION FAIL [iso_interval % sdu_interval == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_central_iso.c:1225
d_00: @00:00:00.006488  @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_central_iso.c:1225
d_00: @00:00:00.006488  [00:00:00.006,469] <err> os: z_fatal_error: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
d_00: @00:00:00.006488  [00:00:00.006,469] <err> os: z_fatal_error: Current thread: 0x8267b80 (sysworkq)
d_00: @00:00:00.006488  [00:00:00.006,469] <err> os: k_sys_fatal_error_handler: Halting system
d_00: @00:00:00.006488 ERROR: Exiting due to fatal error
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/74495

**Additional context**
image

### PR DESCRIPTION
**Pull request by cvinayak**
Support for separate SDU interval for C_to_P and P_to_C directions when setting CIG parameters.

Relates to #64186 and may fix #74495 bsim failure.
Fixes #74544.

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 1]
```diff
@@ -228,19 +229,19 @@ uint8_t ll_cig_parameters_commit(uint8_t cig_id, uint16_t *handles)
...
 		 * framed mode must be forced.
 		 */
-		cig->iso_interval = cig->c_sdu_interval / ISO_INT_UNIT_US;
+		iso_interval_us = cig->c_sdu_interval;
 
-		if (cig->iso_interval < BT_HCI_ISO_INTERVAL_MIN) {
+		if (iso_interval_us < 5000U) {
 			/* ISO_Interval is below minimum (5 ms) */
-			cig->iso_interval = BT_HCI_ISO_INTERVAL_MIN;
+			iso_interval_us = 5000U;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:236]: Suggest to keep the use of the defined HCI values but add a macro or something similar to 
```c
/**
 * @brief Convert periodic advertising interval (N * 1.25 ms) to milliseconds
 *
 * 5 / 4 represents 1.25 ms unit.
 */
#define BT_GAP_PER_ADV_INTERVAL_TO_MS(interval) ((interval) * 5 / 4)
```

like
```c
#define HCI_ISO_INTERVAL_TO_US(_interval) (USEC_PER_MSEC * (_interval) * 5 / 4)
```

Edit: Just noticed `ISO_INT_UNIT_US`, so this could also be 
```c
#define HCI_ISO_INTERVAL_TO_US(_interval) ((_interval) * ISO_INT_UNIT_US)
```

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 2]
```diff
@@ -228,19 +229,19 @@ uint8_t ll_cig_parameters_commit(uint8_t cig_id, uint16_t *handles)
...
 		}
 
 #if defined(CONFIG_BT_CTLR_CONN_ISO_AVOID_SEGMENTATION)
 		/* Check if this is a HAP usecase which requires higher link bandwidth to ensure
 		 * segmentation is not invoked in ISO-AL.
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:241]: Unrelated to this PR, but how can the controller determine which LE Audio profile is being used? :s

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 3]
```diff
@@ -250,10 +251,11 @@ uint8_t ll_cig_parameters_commit(uint8_t cig_id, uint16_t *handles)
 			 */
 			force_framed = true;
 		}
+	} else {
+		iso_interval_us = cig->iso_interval * ISO_INT_UNIT_US;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:255]: Out of curiosity, what is the `INT` in `ISO_INT_UNIT_US`?

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 4]
```diff
@@ -360,29 +362,43 @@ uint8_t ll_cig_parameters_commit(uint8_t cig_id, uint16_t *handles)
...
+					goto ll_cig_parameters_commit_retry;
+				}
 				cis->lll.tx.bn = bn;
 				cis->lll.tx.max_pdu = max_pdu;
 			} else {
 				cis->lll.tx.bn = 0U;
 			}
 
 			if (rx) {
+				uint32_t iso_interval_adjust_us;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:387]: Just a thank you for postfixing the unit to the variables :) Makes it a lot easier to follow IMO

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 5]
```diff
@@ -1170,9 +1189,9 @@ static void ticker_op_cb(uint32_t status, void *param)
 }
 #endif /* CONFIG_BT_CTLR_CENTRAL_SPACING  == 0 */
 
-static void set_bn_max_pdu(bool framed, uint32_t iso_interval,
-			   uint32_t sdu_interval, uint16_t max_sdu, uint8_t *bn,
-			   uint8_t *max_pdu)
+static uint32_t set_bn_max_pdu(bool framed, uint32_t iso_interval,
+			       uint32_t iso_interval_cig, uint32_t sdu_interval,
+			       uint16_t max_sdu, uint8_t *bn, uint8_t *max_pdu)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:1194]: Not sure if I agree that the naming of this function implies that it returns the iso interval in microseconds. 

Suggest a better name and/or documentation.

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 6]
```diff
@@ -1222,13 +1241,17 @@ static void set_bn_max_pdu(bool framed, uint32_t iso_interval,
 		}
 	} else {
 		/* For unframed, ISO_Interval must be N x SDU_Interval */
-		LL_ASSERT(iso_interval % sdu_interval == 0);
+		if ((iso_interval % sdu_interval) != 0) {
+			iso_interval += iso_interval_cig;
+		}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:1246]: Can you help me understand this? 

If the ISO interval is not a multiple of SDU interval, then we add the `iso_interval_cig`? 

The comment is not really making sense anymore, but I also don't understand this addition of `iso_interval_cig`

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:243]: Good question, @wopu-ot  ?

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c]: Updated.

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:389]: Yeah, the spec doesn't make it easy either. Lots of switching between us, ms and 1.25ms units :D

**Review by Thalley — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
