### PR TITLE
driver/sensors: lis2dh: Fix I2C and SPI bus communication

### LINKED ISSUE #22348: LIS2DH SPI Support
The LIS2DH works well with I2C devices such as the Thingy52, however when testing with a Ruuvitag which has the the sensor on the SPI bus readings are wrong. 

The driver looks like it doesn't not configure the SPI bus correctly as it missues the CS controller and CS pin configurations. An example of the correct configuration type can be found for the lis2ds12 driver.

1. git clone https://github.com/theBASTI0N/zephyr-ruuvi.git /boards/arm/nrf52_ruuvi
2. cd ~/xephyrproject/zephyr/
3. west build -b nrf52_ruuvi samples/sensor/lis2dh
4. See readings, I used:
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

There is no error in stating the device cannot be found, however the reading are wrong.

The output is:

SEGGER J-Link V6.60f - Real time terminal output
J-Link OB-SAM3U128-V2-NordicSemi compiled Jan  7 2019 14:07:15 V1.0, SN=682061953
Process: JLinkExe
*** Booting Zephyr OS build zephyr-v2.1.0-1478-g702ebb321225  ***
Polling at 0.5 Hz
#1 @ 12600 ms: x -0.009576 , y -0.009576 , z -0.009576
#2 @ 13901 ms: x -0.009576 , y -0.009576 , z -0.009576
#3 @ 15202 ms: x -0.009576 , y -0.009576 , z -0.009576
#4 @ 16503 ms: x -0.009576 , y -0.009576 , z -0.009576
#5 @ 17804 ms: x -0.009576 , y -0.009576 , z -0.009576
#6 @ 19106 ms: x -0.009576 , y -0.009576 , z -0.009576
#7 @ 20407 ms: x -0.009576 , y -0.009576 , z -0.009576
#8 @ 21708 ms: x -0.009576 , y -0.009576 , z -0.009576
#9 @ 23009 ms: x -0.009576 , y -0.009576 , z -0.009576
#10 @ 24310 ms: x -0.009576 , y -0.009576 , z -0.009576

The makes using the lis2dh12 on the ruuvitag almost impossible.

Environment
 - OS:Debian 10
 - Toolchain Zephyr SDK
 - Version 2.1.99

### PR DESCRIPTION
**Pull request by avisconti**
Add I2C and SPI bus communication routines in separate files,
and register one or the other as read/write callbacks based
on bus selection in DTS.

This commit fixes #22348 as well, as the SPI part is handling in the proper way the CS GPIO part.

TESTED on x_nucleo_iks01a2 shield for I2C and x_nucleo_iks01a3 shield for SPI.

### CODE REVIEW

File: drivers/sensor/lis2dh/lis2dh.c [hunk 1]
```diff
@@ -323,18 +267,34 @@ static const struct sensor_driver_api lis2dh_driver_api = {
...
 	struct lis2dh_data *lis2dh = dev->driver_data;
+	const struct lis2dh_config *cfg = dev->config->config_info;
 	int status;
+	u8_t id;
 	u8_t raw[6];
 
-	status = lis2dh_bus_configure(dev);
+	lis2dh->bus = device_get_binding(cfg->bus_name);
+	if (!lis2dh->bus) {
+		LOG_DBG("master not found: %s", cfg->bus_name);
```
Comment (MaureenHelm) [inline drivers/sensor/lis2dh/lis2dh.c]: Recommend changing this to `LOG_ERR`

File: drivers/sensor/lis2dh/lis2dh.c [hunk 2]
```diff
@@ -323,18 +267,34 @@ static const struct sensor_driver_api lis2dh_driver_api = {
...
+	cfg->bus_init(dev);
+
+	status = lis2dh->hw_tf->read_reg(dev, LIS2DH_REG_WAI, &id);
 	if (status < 0) {
+		LOG_ERR("Failed to read chip id.");
 		return status;
 	}
 
+	if (id != LIS2DH_CHIP_ID) {
+		LOG_DBG("Invalid chip ID: %02x\n", id);
```
Comment (MaureenHelm) [inline drivers/sensor/lis2dh/lis2dh.c]: This should also be `LOG_ERR`

File: drivers/sensor/lis2dh/lis2dh.c [hunk 3]
```diff
@@ -378,13 +339,38 @@ int lis2dh_init(struct device *dev)
...
+	.bus_init = lis2dh_spi_init,
+	.spi_conf.frequency = DT_INST_0_ST_LIS2DH_SPI_MAX_FREQUENCY,
+	.spi_conf.operation = (SPI_OP_MODE_MASTER | SPI_MODE_CPOL |
+			       SPI_MODE_CPHA | SPI_WORD_SET(8) |
+			       SPI_LINES_SINGLE),
+	.spi_conf.slave     = DT_INST_0_ST_LIS2DH_BASE_ADDRESS,
+#if defined(DT_INST_0_ST_LIS2DH_CS_GPIOS_CONTROLLER)
+	.gpio_cs_port	    = DT_INST_0_ST_LIS2DH_CS_GPIOS_CONTROLLER,
+	.cs_gpio	    = DT_INST_0_ST_LIS2DH_CS_GPIOS_PIN,
+
```
Comment (MaureenHelm) [inline drivers/sensor/lis2dh/lis2dh.c]: Remove the extra blank line

File: drivers/sensor/lis2dh/lis2dh_spi.c [hunk 4]
```diff
@@ -0,0 +1,183 @@
...
+
+#if 0
+static struct spi_config lis2dh_spi_conf = {
+	.frequency = DT_INST_0_ST_LIS2DH_SPI_MAX_FREQUENCY,
+	.operation = (SPI_OP_MODE_MASTER | SPI_MODE_CPOL |
+		      SPI_MODE_CPHA | SPI_WORD_SET(8) | SPI_LINES_SINGLE),
+	.slave     = DT_INST_0_ST_LIS2DH_BASE_ADDRESS,
+	.cs        = NULL,
+};
+#endif
```
Comment (MaureenHelm) [inline drivers/sensor/lis2dh/lis2dh_spi.c]: Remove the dead block

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

File: drivers/sensor/lis2dh/lis2dh.c (hunk 1 above)
Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh.c]: Done, but ... what's the rule behind it? The errno (EINVAL in this case)?

File: drivers/sensor/lis2dh/lis2dh.c (hunk 2 above)
Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh.c]: done

File: drivers/sensor/lis2dh/lis2dh_spi.c (hunk 4 above)
Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh_spi.c]: Oops! Forfgot to clean this out.

**Review by MaureenHelm — APPROVED** [review]

**Comment by MaureenHelm** [comment]
@erwango please review

**Review by erwango — CHANGES_REQUESTED** [review]
Nitpick on indentation, otherwise is fine.
I've been able to test I2C sample and compile a SPI sample (no HW to test though).

**Comment by avisconti** [comment]
> I've been able to test I2C sample and compile a SPI sample (no HW to test though).

I used the DIL24 of x_nucleo_iks01a3 shield. It has to be configured with the proper zero-ohm resistors to have SPI instead of I2C (the default).

File: drivers/sensor/lis2dh/lis2dh_trigger.c [hunk 5]
```diff
@@ -158,7 +160,7 @@ static int lis2dh_start_trigger_int2(struct device *dev)
 
 	setup_int2(dev, true);
 
-	return lis2dh_reg_write_byte(dev, LIS2DH_REG_INT2_CFG,
+	return lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_INT2_CFG,
 				     LIS2DH_ANYM_CFG);
```
[the remark this answers is not in the document]
Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh_trigger.c]: ack

[the remark this answers is not in the document]
Comment (avisconti) [reply drivers/sensor/lis2dh/lis2dh_trigger.c]: ack

**Comment by erwango** [comment]
@avisconti can you check indentation on similar functions as well?
There are multiple spots to be fixed.

**Comment by avisconti** [comment]
> @avisconti can you check indentation on similar functions as well?
> There are multiple spots to be fixed.

You mean even in the parts I have not directly committed? Or in my commit itself?

File: drivers/sensor/lis2dh/lis2dh.c [hunk 6]
```diff
@@ -224,7 +169,7 @@ static int lis2dh_acc_odr_set(struct device *dev, u16_t freq)
 		odr--;
 	}
 
-	return lis2dh_reg_write_byte(dev, LIS2DH_REG_CTRL1,
+	return data->hw_tf->write_reg(dev, LIS2DH_REG_CTRL1,
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh.c [hunk 7]
```diff
@@ -260,10 +205,9 @@ static int lis2dh_acc_range_set(struct device *dev, s32_t range)
 
 	lis2dh->scale = lis2dh_reg_val_to_scale[fs];
 
-	return lis2dh_reg_field_update(dev, LIS2DH_REG_CTRL4,
-				       LIS2DH_FS_SHIFT,
+	return lis2dh->hw_tf->update_reg(dev, LIS2DH_REG_CTRL4,
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh.c [hunk 8]
```diff
@@ -146,7 +96,7 @@ static int lis2dh_sample_fetch(struct device *dev, enum sensor_channel chan)
 	 * since status and all accel data register addresses are consecutive,
 	 * a burst read can be used to read all the samples
 	 */
-	status = lis2dh_burst_read(dev, LIS2DH_REG_STATUS,
+	status = lis2dh->hw_tf->read_data(dev, LIS2DH_REG_STATUS,
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh.c [hunk 9]
```diff
@@ -323,18 +267,34 @@ static const struct sensor_driver_api lis2dh_driver_api = {
...
+		LOG_ERR("Invalid chip ID: %02x\n", id);
+		return -EINVAL;
+	}
+
 	if (IS_ENABLED(DT_INST_0_ST_LIS2DH_DISCONNECT_SDO_SA0_PULL_UP)) {
-		status = lis2dh_reg_field_update(dev, LIS2DH_REG_CTRL0,
-						 LIS2DH_SDO_PU_DISC_SHIFT,
-						 LIS2DH_SDO_PU_DISC_MASK, 1);
+		status = lis2dh->hw_tf->update_reg(dev, LIS2DH_REG_CTRL0,
+						 LIS2DH_SDO_PU_DISC_MASK,
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh.c [hunk 10]
```diff
@@ -349,16 +309,17 @@ int lis2dh_init(struct device *dev)
 	(void)memset(raw, 0, sizeof(raw));
 	raw[0] = LIS2DH_ACCEL_EN_BITS;
 
-	status = lis2dh_burst_write(dev, LIS2DH_REG_CTRL1, raw,
+	status = lis2dh->hw_tf->write_data(dev, LIS2DH_REG_CTRL1, raw,
 				    sizeof(raw));
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh.c [hunk 11]
```diff
@@ -349,16 +309,17 @@ int lis2dh_init(struct device *dev)
...
+
 	if (status < 0) {
 		LOG_ERR("Failed to reset ctrl registers.");
 		return status;
 	}
 
 	/* set full scale range and store it for later conversion */
 	lis2dh->scale = lis2dh_reg_val_to_scale[LIS2DH_FS_IDX];
-	status = lis2dh_reg_write_byte(dev, LIS2DH_REG_CTRL4,
+	status = lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_CTRL4,
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh.c [hunk 12]
```diff
@@ -378,13 +339,37 @@ int lis2dh_init(struct device *dev)
 		    LIS2DH_ODR_IDX, (u8_t)LIS2DH_LP_EN_BIT, lis2dh->scale);
 
 	/* enable accel measurements and set power mode and data rate */
-	return lis2dh_reg_write_byte(dev, LIS2DH_REG_CTRL1,
+	return lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_CTRL1,
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh.c [hunk 13]
```diff
@@ -378,13 +339,37 @@ int lis2dh_init(struct device *dev)
...
+	.i2c_slv_addr = DT_INST_0_ST_LIS2DH_BASE_ADDRESS,
+#else
+#error "BUS MACRO NOT DEFINED IN DTS"
+#endif
+};
 
-DEVICE_AND_API_INIT(lis2dh, DT_INST_0_ST_LIS2DH_LABEL, lis2dh_init, &lis2dh_driver,
-		    NULL, POST_KERNEL, CONFIG_SENSOR_INIT_PRIORITY,
+DEVICE_AND_API_INIT(lis2dh, DT_INST_0_ST_LIS2DH_LABEL, lis2dh_init, &lis2dh_data,
+		    &lis2dh_config, POST_KERNEL, CONFIG_SENSOR_INIT_PRIORITY,
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh_i2c.c [hunk 14]
```diff
@@ -0,0 +1,92 @@
...
+#include <logging/log.h>
+
+#include "lis2dh.h"
+
+#ifdef DT_ST_LIS2DH_BUS_I2C
+
+LOG_MODULE_DECLARE(lis2dh, CONFIG_SENSOR_LOG_LEVEL);
+
+static int lis2dh_i2c_read_data(struct device *dev, u8_t reg_addr,
+				 u8_t *value, u8_t len)
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh_i2c.c]: Fix indentation here and for other function headers

File: drivers/sensor/lis2dh/lis2dh_spi.c [hunk 15]
```diff
@@ -0,0 +1,173 @@
...
+#include <string.h>
+#include "lis2dh.h"
+#include <logging/log.h>
+
+#ifdef DT_ST_LIS2DH_BUS_SPI
+
+LOG_MODULE_DECLARE(lis2dh, CONFIG_SENSOR_LOG_LEVEL);
+
+static int lis2dh_raw_read(struct device *dev, u8_t reg_addr,
+			    u8_t *value, u8_t len)
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh_spi.c]: Fix indentation here and for other function headers below

File: drivers/sensor/lis2dh/lis2dh_trigger.c [hunk 16]
```diff
@@ -39,8 +39,7 @@ static int lis2dh_trigger_drdy_set(struct device *dev, enum sensor_channel chan,
 	/* cancel potentially pending trigger */
 	atomic_clear_bit(&lis2dh->trig_flags, TRIGGED_INT1);
 
-	status = lis2dh_reg_field_update(dev, LIS2DH_REG_CTRL3,
-					 LIS2DH_EN_DRDY1_INT1_SHIFT,
+	status = lis2dh->hw_tf->update_reg(dev, LIS2DH_REG_CTRL3,
 					 LIS2DH_EN_DRDY1_INT1, 0);
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh_trigger.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh_trigger.c [hunk 17]
```diff
@@ -68,37 +67,40 @@ static int lis2dh_start_trigger_int1(struct device *dev)
...
 
 	/* power down temporarily to align interrupt & data output sampling */
-	status = lis2dh_reg_read_byte(dev, LIS2DH_REG_CTRL1, &ctrl1);
+	status = lis2dh->hw_tf->read_reg(dev, LIS2DH_REG_CTRL1, &ctrl1);
 	if (unlikely(status < 0)) {
 		return status;
 	}
-	status = lis2dh_reg_write_byte(dev, LIS2DH_REG_CTRL1,
+	status = lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_CTRL1,
 				       ctrl1 & ~LIS2DH_ODR_MASK);
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh_trigger.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh_trigger.c [hunk 18]
```diff
@@ -210,7 +214,7 @@ int lis2dh_acc_slope_config(struct device *dev, enum sensor_attribute attr,
 		LOG_INF("int2_ths=0x%x range_g=%d ums2=%u", reg_val,
 			    range_g, slope_th_ums2 - 1);
 
-		status = lis2dh_reg_write_byte(dev, LIS2DH_REG_INT2_THS,
+		status = lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_INT2_THS,
 					       reg_val);
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh_trigger.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh_trigger.c [hunk 19]
```diff
@@ -223,7 +227,7 @@ int lis2dh_acc_slope_config(struct device *dev, enum sensor_attribute attr,
 
 		LOG_INF("int2_dur=0x%x", val->val1);
 
-		status = lis2dh_reg_write_byte(dev, LIS2DH_REG_INT2_DUR,
+		status = lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_INT2_DUR,
 					       val->val1);
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh_trigger.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh_trigger.c [hunk 20]
```diff
@@ -318,7 +322,7 @@ static void lis2dh_thread_cb(void *arg)
 		u8_t reg_val;
 
 		/* clear interrupt 2 to de-assert int2 line */
-		status = lis2dh_reg_read_byte(dev, LIS2DH_REG_INT2_SRC,
+		status = lis2dh->hw_tf->read_reg(dev, LIS2DH_REG_INT2_SRC,
 					      &reg_val);
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh_trigger.c]: Fix indentation here

File: drivers/sensor/lis2dh/lis2dh_trigger.c [hunk 21]
```diff
@@ -428,43 +447,36 @@ int lis2dh_init_interrupt(struct device *dev)
...
 
+	/* enable interrupt 2 on int2 line */
+	status = lis2dh->hw_tf->update_reg(dev, LIS2DH_REG_CTRL6,
+					   LIS2DH_EN_INT2_INT2,
+					   LIS2DH_EN_INT2_INT2);
+
 	/* latch int2 line interrupt */
-	status = lis2dh_reg_write_byte(dev, LIS2DH_REG_CTRL5,
+	status = lis2dh->hw_tf->write_reg(dev, LIS2DH_REG_CTRL5,
 				       LIS2DH_EN_LIR_INT2);
```
Comment (erwango) [inline drivers/sensor/lis2dh/lis2dh_trigger.c]: Fix indentation here

**Review by erwango — CHANGES_REQUESTED** [review]
@avisconti I think I tagged all the occurrences. Please have a look.

**Comment by avisconti** [comment]
@erwango 
I think I addressed all identation issue now.
THanks for reviewing

**Comment by avisconti** [comment]
@erwango 
Sorry, there were still three lines with indentation issues.

**Comment by avisconti** [comment]
@erwango @MaureenHelm 
But is the v2.2.0 already out? I don't see it.
if not, are we on time to include also this fix?

**Review by erwango — APPROVED** [review]

**Comment by avisconti** [comment]
According to discussion in #22348 this fix is solving the bug, as the requester is able to use the sensor in SPI mode. The fact that it is not able to build the driver with trigger enabled is for sure due to the fact he's using a zephyr version prior the new GPIO API. I have tested the triggers on my side on two different shields and they are working fine.

**Comment by erwango** [comment]
@avisconti I think this is too late given that we're in the rc3 stage. But that's up to @jhedberg to settle on this.
