### PR TITLE
Arch arm fix sp corrupt in jump to main

### LINKED ISSUE #14471: MPU fault during application startup
**Describe the bug**
Application can hit mpu fault before starting main thread. This is caused by stack misuse. In function `z_arch_switch_to_main_thread` thread entry is provided as forth argument (`_main`). Then within the function stack pointer is changed:
https://github.com/zephyrproject-rtos/zephyr/blob/269935dca9e139d365631979fbecf6d080cba758/arch/arm/include/kernel_arch_func.h#L106

After stack is changed, call to thread entry occurs which is using `_main` as the argument. If variable is stored on stack, it will be fetched from stack but at that point this is already different stack and value is corrupted:
https://github.com/zephyrproject-rtos/zephyr/blob/269935dca9e139d365631979fbecf6d080cba758/arch/arm/include/kernel_arch_func.h#L115
So `_main` variable will be corrupted.

**To Reproduce**
Modify hello_world example by using following prj.conf:
```
CONFIG_MPU_STACK_GUARD=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_LOG=y
```

1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52840_pca10056 ..
3. ninja flash
```
Fatal fault in essential thread! Spinning...
***** MPU FAULT *****
  Instruction Access Violation
***** Hardware exception *****
Current thread ID = 0x200005d8
Faulting instruction address = 0x20001b48
Fatal fault in essential thread! Spinning...
```

**Expected behavior**
Sample should start.

**Impact**
Suddenly system crashes during initialization.

### PR DESCRIPTION
**Pull request by ioannisg**
Fixes #14471 

Reverts, partially, the changes introduced in (bbe1a19), concerning moving the implementation into C functions. Apparently, we did not catch issues when compiling without any optimization flags, where local variables are stored, anyways, in the stack (and the stack pointer changes inside the function). We revert using assembly, now. An ISB is also added, before branching to main thread. Finally, the patch is also adding some inline documentation to ease reading.

A second patch is also provided, that moves the MPU re-programming a bit higher in the code, with no functional/behavioral changes.

### CODE REVIEW

**Comment by ioannisg** [comment]
@nordic-krch could you do some related testing, and see if this works for you now?

File: arch/arm/include/kernel_arch_func.h [hunk 1]
```diff
@@ -103,16 +98,32 @@ z_arch_switch_to_main_thread(struct k_thread *main_thread,
...
-	 * If stack protection is enabled, make sure to set it
-	 * before jumping to thread entry function
+	 * Set PSP to the highest address of the main stack
+	 * before enabling interrupts and jumping to main.
 	 */
-	z_arch_configure_dynamic_mpu_regions(main_thread);
-#endif
-	z_thread_entry(_main, 0, 0, 0);
+	__asm__ volatile (
+	"mov   r4,  %0     \n\t"   /* Store _main in R4 */
```
Comment (carlescufi) [inline arch/arm/include/kernel_arch_func.h]: Any reason why you use r4 here instead of storing it in r0 directly and using any other registr to set BASEPRI later?

Comment (ioannisg) [reply arch/arm/include/kernel_arch_func.h]: Hm, right :)

Well, I thought this is a bit more robust against "someone" going there and inserting a "bl <some routine> after setting PSP and before branching to z_thread_entry. E.g. something related to tracing, bench-marking, profiling, etc.

**Comment by nordic-krch** [comment]
i've tested reported case and it works fine.

File: arch/arm/include/kernel_arch_func.h (hunk 1 above)
Comment (ioannisg) [reply arch/arm/include/kernel_arch_func.h]: @carlescufi, modified patch to use R0 (and R1 for BASEPRI), based on your suggestion

**Review by tyrantlizard77 — APPROVED** [review]

**Review by galak — APPROVED** [review]
