### PR TITLE
net: Remove unpacked structure references from packed structs

### LINKED ISSUE #16587: build failures with gcc 9.x
**Describe the bug**
warnings with new compilers that turn into errors when building using sanitycheck

```
In file included from /home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:16:
/home/nashif/Work/zephyrproject/zephyr/include/net/net_pkt.h: In function ‘net_pkt_set_src_ipv6_addr’:
/home/nashif/Work/zephyrproject/zephyr/include/net/net_pkt.h:824:9: error: taking address of packed member of ‘struct net_ipv6_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  824 |         &NET_IPV6_HDR(pkt)->src);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c: In function ‘arp_hdr_check’:
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:537:32: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  537 |      net_ipv4_is_addr_loopback(&arp_hdr->src_ipaddr)) {
      |                                ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c: In function ‘net_arp_input’:
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:590:9: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  590 |         &arp_hdr->src_ipaddr,
      |         ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:602:30: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  602 |       net_ipv4_is_addr_mcast(&arp_hdr->src_ipaddr)) {
      |                              ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:608:42: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  608 |   addr = if_get_addr(net_pkt_iface(pkt), &arp_hdr->dst_ipaddr);
      |                                          ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:635:8: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  635 |        &arp_hdr->src_ipaddr,
      |        ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:655:27: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  655 |   if (net_ipv4_is_my_addr(&arp_hdr->dst_ipaddr)) {
      |                           ^~~~~~~~~~~~~~~~~~~~
/home/nashif/Work/zephyrproject/zephyr/subsys/net/l2/ethernet/arp.c:657:8: error: taking address of packed member of ‘struct net_arp_hdr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  657 |        &arp_hdr->src_ipaddr,
      |        ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [zephyr/subsys/net/l2/ethernet/CMakeFiles/subsys__net__l2__ethernet.dir/build.make:63: zephyr/subsys/net/l2/ethernet/CMakeFiles/subsys__net__l2__ethernet.dir/arp.c.obj] Error 1
```
**To Reproduce**

Build for native_posix on Fedora 30 with new compiler

### PR DESCRIPTION
**Pull request by rlubos**
This PR proposes a solution for the "unaligned access to the packed struct member warning" issue within networking code.

The generic approach for the problem is similar in most cases covered in this PR:
* Replace `struct in_addr`/`struct in6_addr` within packed structs with raw buffers,
* Provide `_raw` variants of the most commonly used functions (IPv4/6 copy and compare) and use them where applicable,
* ~~For other cases, create a local copy of `struct in_addr`/`struct in6_addr` on stack, copy the IP address from the actual packet, and work with the local copy istead of referencing possibly unaligned address from the packet.~~

The only exception for the above scheme is the ieee802154 case - here IMO there's no need to use __packed qualifier for the structure that generated warnings, for the reason explained in the commit message.

The only warning left when building networking code is the following in the `mmu.c` file (this will likely cause CI failures):
```
/home/robert/repos/zephyrproject/zephyr/kernel/mmu.c: In function 'free_page_frame_list_put':
/home/robert/repos/zephyrproject/zephyr/kernel/mmu.c:333:42: warning: taking address of packed member of 'struct z_page_frame' may result in an unaligned pointer value [-Waddress-of-packed-member]
  333 |  sys_slist_append(&free_page_frame_list, &pf->node);
      | 
```

Fixes #16587

### CODE REVIEW

File: subsys/net/l2/ethernet/arp.c [hunk 1]
```diff
@@ -535,11 +535,15 @@ static inline struct net_pkt *arp_prepare_reply(struct net_if *iface,
 
 static bool arp_hdr_check(struct net_arp_hdr *arp_hdr)
 {
+	struct in_addr src_ip;
+
+	memcpy(&src_ip, arp_hdr->src_ipaddr, sizeof(src_ip));
```
Comment (jukkar) [inline subsys/net/l2/ethernet/arp.c:540]: Do we really need intermediate variable here, can't we just do
```
net_ipv4_is_addr_loopback(UNLIGNED_GET(...));
```
here?

File: subsys/net/l2/ethernet/arp.c [hunk 2]
```diff
@@ -568,6 +573,9 @@ enum net_verdict net_arp_input(struct net_pkt *pkt,
 		return NET_DROP;
 	}
 
+	net_ipv4_addr_copy_raw((uint8_t *)&src_ip, arp_hdr->src_ipaddr);
```
Comment (jukkar) [inline subsys/net/l2/ethernet/arp.c:576]: same question here

**Review by jukkar — COMMENTED** [review]
This looks mostly reasonable, I am a bit worried about the extra memcpy to intermediate variable we do in various places and was wondering if we could get away with those copies by using `UNALIGNED_GET()` macro.

File: subsys/net/l2/ethernet/arp.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/l2/ethernet/arp.c:540]: I don't think we could use `UNALIGNED_GET()` in this case, the function expects a pointer, but this macro returns a value, and it's not possible to obtain the address of the result, it ends up in a compilation error:
```
error: lvalue required as unary '&' operand
```
I tried however a different approach - instead of using the local copy, simply feed the function with the raw buffer address, typecasted into `in_addr *` in this case - the compiler had no issue with that. All these little address check functions use `UNALIGNED_GET()` macro internally to access the structure fields anyway, so I think it should be safe to provide it even with an unaligned address, but maybe I miss something, I don't know.

But yeah, now that all of the "hotspots" are identified, we can think of possible optimizations.

**Review by carlescufi — COMMENTED** [review]
First take after a quick look

File: include/net/net_ip.h [hunk 3]
```diff
@@ -737,6 +737,18 @@ static inline bool net_ipv4_is_ll_addr(const struct in_addr *addr)
...
+/**
+ *  @brief Copy an IPv4 address raw buffer
+ *
+ *  @param dest Destination IP address.
+ *  @param src Source IP address.
+ */
+static inline void net_ipv4_addr_copy_raw(uint8_t *dest,
+					  const uint8_t *src)
+{
+	net_ipaddr_copy((struct in_addr *)dest, (const struct in_addr *)src);
```
[the remark this answers is not in the document]
Comment (carlescufi) [reply include/net/net_ip.h:749]: Scratch that, `UNALIGNED_PUT` ends up referring to the type of `dest`.

File: subsys/net/l2/ethernet/arp.c (hunk 1 above)
Comment (carlescufi) [reply subsys/net/l2/ethernet/arp.c:540]: I would say that we try to not do both, which is clearly overkill:
- if we use a buffer variable, let's not use `GET_UNALIGNED` on it
- if we use the raw packed variable, let's use `GET_UNALIGNED` on it

**Comment by rlubos** [comment]
I've pushed an updated version of the PR, where I removed the `struct in_addr`/`struct in6_addr` where I found it appropriate, as requested. This also reduced the memory footprint - the `rom_report` states that after the changes the actual footprint of the `net` subsystem is actually slightly smaller, by 94 bytes.

I've rebased the PR, and resolved any new issues that showed up after the rebase. I think it's the time to pull the PR from the draft stage.

**Comment by rlubos** [comment]
After discussing with @carlescufi we've decided to drop the warning override removal from this PR, and address remaining issues separately in other PR. This one will only focus on the networking part.

**Review by cfriedt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
