### PR TITLE
some fixes for mwdt toolchain

### LINKED ISSUE #36465: samples/compression/lz4 failed with arcmwdt toolchian
**Describe the bug**
samples/compression/lz4 failed with arcmwdt toolchian

**To Reproduce**
1. west build -b nsim_em -d build samples/compression/lz4
2. See error

**Logs and console output**
```
west build -b nsim_em -d build samples/compression/lz4
-- west build: generating a build system
Including boilerplate (Zephyr base): /SCRATCH2/Watson/zephyrproject/zephyr/cmake/app/boilerplate.cmake
-- Application: /SCRATCH2/Watson/zephyrproject/zephyr/samples/compression/lz4
-- Zephyr version: 2.6.99 (/SCRATCH2/Watson/zephyrproject/zephyr), build: zephyr-v2.6.0-474-gb4faf7fe6320
-- Found Python3: /depot/Python/Python-3.7.0/bin/python3.7 (found suitable exact version "3.7.0") found components: Interpreter 
-- Found west (found suitable version "0.11.0", minimum required is "0.7.1")
-- Board: nsim_em
-- Cache files will be written to: /u/zhiwei/.cache/zephyr
-- Using toolchain: zephyr 0.12.3 (/SCRATCH2/svc-arcoss_auto/tools/zephyr-sdk/0.12.3)
-- Found dtc: /SCRATCH2/svc-arcoss_auto/tools/zephyr-sdk/0.12.3/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found BOARD.dts: /SCRATCH2/Watson/zephyrproject/zephyr/boards/arc/nsim/nsim_em.dts
-- Generated zephyr.dts: /SCRATCH2/Watson/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /SCRATCH2/Watson/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_unfixed.h
-- Generated device_extern.h: /SCRATCH2/Watson/zephyrproject/zephyr/build/zephyr/include/generated/device_extern.h
Parsing /SCRATCH2/Watson/zephyrproject/zephyr/Kconfig
Loaded configuration '/SCRATCH2/Watson/zephyrproject/zephyr/boards/arc/nsim/nsim_em_defconfig'
Merged configuration '/SCRATCH2/Watson/zephyrproject/zephyr/samples/compression/lz4/prj.conf'
Configuration saved to '/SCRATCH2/Watson/zephyrproject/zephyr/build/zephyr/.config'
Kconfig header saved to '/SCRATCH2/Watson/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h'
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
-- The ASM compiler identification is unknown
-- Found assembler: /global/apps/mwdt_2021.03/MetaWare/arc/bin/ccac
-- Warning: Did not find file Compiler/-ASM
CMake Warning at ../../../cmake/linker/arcmwdt/target.cmake:137 (message):
  MWDT toolchain does not support

             CONFIG_LINKER_ORPHAN_SECTION_WARN
Call Stack (most recent call first):
  ../../../CMakeLists.txt:246 (toolchain_ld_baremetal)


-- Configuring done
-- Generating done
-- Build files have been written to: /SCRATCH2/Watson/zephyrproject/zephyr/build
-- west build: building application
[1/110] Preparing syscall dependency handling

[7/110] Building C object zephyr/CMakeFiles/offsets.dir/arch/arc/core/offsets/offsets.c.obj
FAILED: zephyr/CMakeFiles/offsets.dir/arch/arc/core/offsets/offsets.c.obj 
/global/apps/mwdt_2021.03/MetaWare/arc/bin/ccac -DBUILD_VERSION=zephyr-v2.6.0-474-gb4faf7fe6320 -DKERNEL -D__LINUX_ERRNO_EXTENSIONS__ -D__ZEPHYR__=1 -I../kernel/include -I../arch/arc/include -I../include -Izephyr/include/generated -I../soc/arc/snps_nsim -I../lib/libc/newlib/include -I/SCRATCH2/Watson/zephyrproject/modules/lib/lz4/lib -Os -imacros /SCRATCH2/Watson/zephyrproject/zephyr/build/zephyr/include/generated/autoconf.h -Hnocrt -fno-common -g -Hnocopyr -HL -Hnosdata -Hoff=Stackcheck_alloca -imacros /SCRATCH2/Watson/zephyrproject/zephyr/include/toolchain/zephyr_stdint.h -Wformat -Wformat-security -Wno-format-zero-length -Wno-main-return-type -Wno-unaligned-pointer-conversion -Wno-incompatible-pointer-types-discards-qualifiers -Wno-typedef-redefinition -Wno-pointer-sign -Wpointer-arith -Wno-sometimes-uninitialized -Wno-shift-overflow -Wno-missing-braces -Wno-self-assign -Wno-address-of-packed-member -Wno-unused-function -Wno-initializer-overrides -Wno-section -Wno-unknown-warning-option -Wno-unused-variable -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -Werror=implicit-int -ffunction-sections -fdata-sections -arcv2em -core3 -Xdiv_rem=radix2 -Xmpy_option=mpyd -Xbitscan -Xswap -Xbarrel_shifter -Xshift_assist -Xdsp2 -Xdsp_complex -Xdsp_divsqrt=radix2 -Xdsp_itu -Xdsp_accshift=full -Xfpus_div -Xfpu_mac -Xfpuda -Xfpus_mpy_slow -Xfpus_div_slow -Xbitstream -Xtimer0 -Xtimer1 -std=gnu99 -MD -MT zephyr/CMakeFiles/offsets.dir/arch/arc/core/offsets/offsets.c.obj -MF zephyr/CMakeFiles/offsets.dir/arch/arc/core/offsets/offsets.c.obj.d -o zephyr/CMakeFiles/offsets.dir/arch/arc/core/offsets/offsets.c.obj   -c /SCRATCH2/Watson/zephyrproject/zephyr/arch/arc/core/offsets/offsets.c
In file included from /SCRATCH2/Watson/zephyrproject/zephyr/arch/arc/core/offsets/offsets.c:25:
In file included from ../include/kernel.h:17:
In file included from ../include/kernel_includes.h:17:
In file included from ../include/zephyr/types.h:11:
../lib/libc/newlib/include/stdint.h:15:10: fatal error: 'newlib.h' file not found
#include <newlib.h>
         ^~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /depot/Python/Python-3.7.0/bin/cmake --build /SCRATCH2/Watson/zephyrproject/zephyr/build
```

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (arcmwdt)
 - Commit SHA: b4faf7fe63201ad26b9c4ddf4742ad750c9f2d7a

**Additional context**
samples/compression/lz4 need `CONFIG_NEWLIB_LIBC=y`, while arcmwdt toolchain not support newlib, 
we need to add a filter in sample.yaml: `filter: TOOLCHAIN_HAS_NEWLIB == 1`

### LINKED ISSUE #36466: tests/kernel/mem_protect/mem_protect failed with arcmwdt toolchain
**Describe the bug**
tests/kernel/mem_protect/mem_protect failed with arcmwdt toolchain

**To Reproduce**
1. west build -b nsim_em -d build tests/kernel/mem_protect/mem_protect
2. west flash
3. See error

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.6.0-474-gb4faf7fe6320  ***
Running test suite memory_protection_test_suite
===================================================================
START - test_permission_inheritance
E: ***** Exception vector: 0x6, cause code: 0x1, parameter 0x4
E: Address 0x8000cb48
E: EV_ProtV
E: Memory read protection violation (MPU)
E:  r0: 0x8000cb48  r1: 0xa5  r2: 0x0  r3: 0x0
E:  r4: 0x0  r5: 0x0  r6: 0x8f  r7: 0x0
E:  r8: 0x0  r9: 0x0 r10: 0x0 r11: 0x0
E: r12: 0x4 r13: 0x0  pc: 0xda
E:  blink: 0xca status32: 0x80186886
E: lp_end: 0x62fc lp_start: 0x627c lp_count: 0x0
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x8000ca00 (unknown)
Caught system error -- reason 0 1
fatal error expected as part of test case
 PASS - test_permission_inheritance in 0.12 seconds

......

===================================================================
START - test_mem_part_assign_bss_vars_zero

    Assertion failed at /SCRATCH2/Watson/zephyrproject/zephyr/tests/kernel/mem_protect/mem_protect/src/mem_partition.c:33: test_mem_part_assign_bss_vars_zero: zeroed_var == 0 is false

 FAIL - test_mem_part_assign_bss_vars_zero in 0.8 seconds
===================================================================
START - test_mem_part_auto_determ_size
 PASS - test_mem_part_auto_determ_size in 0.2 seconds
===================================================================

......

===================================================================
Test suite memory_protection_test_suite failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: (Linux)
 - Toolchain (arcmwdt)
 - Commit SHA: b4faf7fe63201ad26b9c4ddf4742ad750c9f2d7a

### PR DESCRIPTION
**Pull request by IRISZZW**
- samples: compression: lz4: add TOOLCHAIN_HAS_NEWLIB filter

    samples\compression\lz4 rely on CONFIG_NEWLIB_LIBC=y, let's
    add TOOLCHAIN_HAS_NEWLIB filter for it.

- tests: mem_protest: workaround aggressive optimization

    We have some static variables var, zeroed_var and bss_var
    in mem_partition.c and we only assert the value of them in
    the same file, so the compiler may pre-calculate it in compile
    stage, it's fine usually.
    But for variable zeroed_var (= 20420), we force to put it in bss
    section in link stage, the value will change in bss clean stage, so
    we will get a wrong result.
    Let's add volatile for these variables to disable pre-calculation.

fixes: #36465 #36466

### CODE REVIEW

File: tests/kernel/mem_protect/mem_protect/src/mem_partition.c [hunk 1]
```diff
@@ -7,9 +7,9 @@
 #include <kernel.h>
 #include "mem_protect.h"
 
-static K_APP_DMEM(ztest_mem_partition) int var = 1356;
-static K_APP_BMEM(ztest_mem_partition) int zeroed_var = 20420;
-static K_APP_BMEM(ztest_mem_partition) int bss_var;
+static volatile K_APP_DMEM(ztest_mem_partition) int var = 1356;
```
Comment (ruuddw) [inline tests/kernel/mem_protect/mem_protect/src/mem_partition.c:10]: Can you add some comments to indicate why the 'volatile' was added here?
That's to avoid users copy the example and leave the volatile while in their application it might not be required, it is only for this test.

**Comment by ruuddw** [comment]
In general ok, but there are few typo's in the descriptions (complie, chage, disbale).

**Review by abrodkin — APPROVED** [review]

**Review by Navin-Sankar — APPROVED** [review]

File: tests/kernel/mem_protect/mem_protect/src/mem_partition.c (hunk 1 above)
Comment (IRISZZW) [reply tests/kernel/mem_protect/mem_protect/src/mem_partition.c:13]: added.

**Comment by IRISZZW** [comment]
> In general ok, but there are few typo's in the descriptions (complie, chage, disbale).

my fault, fixed, thanks.

**Review by ruuddw — APPROVED** [review]
