### PR TITLE
arch: sw_isr: store device info in the table and add funtions to access

### LINKED ISSUE #63465: arch: riscv: support for multi-instance multi-level interrupt
**Describe the bug**
Despite the multi-instance interrupt being supported by the Zephyr's multi-level interrupt encoding scheme, see [Multi-level Interrupt handling](https://docs.zephyrproject.org/latest/kernel/services/interrupts.html#id2), multiple instances of [`intc_plic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_plic.c) is currently not possible due to the way that the `irq` number is passed into the `riscv_plic_*` APIs, see [1](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/common/soc_common_irq.c#L49), [2](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/common/soc_common_irq.c#L70), [3](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/common/soc_common_irq.c#L91), [4](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/common/soc_common_irq.c#L107).

The multi-level encoded `irq` has its level 1 information stripped off before passed into an interrupt controller:

https://github.com/zephyrproject-rtos/zephyr/blob/e11bc94a44adabc6e29c74e2c903083e42bf0991/soc/riscv/riscv-privileged/common/soc_common_irq.c#L41-L53

This made it impossible for any driver, including out-of-tree ones, to differentiate an `irq` that is originated from one instance and another.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
    - Out-of-tree RISCV board
 - What have you tried to diagnose or workaround this issue?
    - There is no other way around modifying Zephyr source

**To Reproduce**
1. Build an out-of-tree RISCV board with interrupt controller driver that support multiple instances
2. Have some devices or software that depend on more than one interrupt controllers
3. Only one interrupt controller and its dependants work

**Expected behavior**
Both interrupt controllers and their dependants should work, since that is supported by Zephyr multi-level interrupt scheme.

**Impact**
Showstopper for applications that require multiple instances of interrupt controller on RISCV arch.

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephyr SDK
 - Commit SHA e11bc94a44adabc6e29c74e2c903083e42bf0991

### PR DESCRIPTION
**Pull request by ycsin**
Change the internal function to `get_parent_entry`, which returns the entire entry of table.

Store the parent interrupt controller device in the `irq_parent_offset` table, and added 2 helper functions to:

1. determine the parent interrupt controller based on the IRQ
2. determine the IRQ of the parent interrupt controller

Declare the `struct _irq_parent_entry` in the header and added so that it can be used to test the functions in testsuites.

> [!NOTE]  
> This change will increase the LUT size for build with multi-level enabled by `CONFIG_NUM_x_LEVEL_AGGREGATORS * sizeof(struct device)`

___

> [!NOTE]  
> This PR is spined off from #62907, to hopefully make it easier to review, and is required to fix #63465

> [!IMPORTANT]
> Blocking #62907

### CODE REVIEW

File: arch/common/sw_isr_common.c [hunk 1]
```diff
@@ -16,12 +16,30 @@
...
 #ifdef CONFIG_MULTI_LEVEL_INTERRUPTS
 
-struct irq_parent_offset {
-	unsigned int irq;
-	unsigned int offset;
-};
+/* Filter out interrupt controllers with `has-multi-instance` prop */
+#define _FILTER_INTC(node_id)                                                                      \
+	COND_CODE_1(DT_NODE_HAS_PROP(node_id, interrupt_controller),                               \
+		    (DT_PROP_OR(node_id, has_multi_instance, 0)), (0))
```
Comment (cfriedt) [inline arch/common/sw_isr_common.c:22]: TL;DR - The one issue I have here is with `has_multi_instance`. DT is implicitly multi-instance. Instead of using `has_multi_instance`, I would suggest rather using something like `DT_NUM_INST_STATUS_OKAY()` which conveys multi-instance status without an additional DT property. The number of instances of a dt-compat is implicitly part of DT, so it's not really necessary to explicitly add this property that should always be true.

File: dts/bindings/interrupt-controller/interrupt-controller.yaml [hunk 2]
```diff
@@ -12,3 +12,6 @@ properties:
     type: int
     required: true
     description: Number of items to expect in an interrupt specifier
+  "has-multi-instance":
```
Comment (galak) [inline dts/bindings/interrupt-controller/interrupt-controller.yaml:15]: What's the intent of this property?

**Review by galak — DISMISSED** [review]
We should NOT add a property for `has-multi-instance` to the devicetree, but scan the tree in some way to get the count of instances to determine its greater than 1.

**Comment by ycsin** [comment]
@cfriedt @galak the `has-multi-instance` prop was misleading, I was using it as a shortcut to get the controller that this implementation supports.

This implementation doesn't support `INTMUX`, i.e. [intc_rv32m1_intmux](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_rv32m1_intmux.c), a single instance of it has multiple interrupts as child:

https://github.com/zephyrproject-rtos/zephyr/blob/b4da11f92967256e6a451f519c739ec95ea6175d/dts/riscv/openisa/rv32m1.dtsi#L88-L177

I've updated the filter to grab the interrupt controller that is the child of `/soc` instead, to filter out the root interrupt controllers

**Review by cfriedt — APPROVED** [review]

**Review by jhedberg — DISMISSED** [review]

**Comment by jhedberg** [comment]
@galak could you take another look?

**Comment by fabiobaltieri** [comment]
(changing the assignees since this does not change any bindings anymore)

**Review by cfriedt — DISMISSED** [review]

File: include/zephyr/sw_isr_table.h [hunk 3]
```diff
@@ -87,6 +94,25 @@ extern struct z_shared_isr_table_entry z_shared_sw_isr_table[];
...
 unsigned int z_get_sw_isr_table_idx(unsigned int irq);
 
+/**
+ * @brief Helper function used to get the parent interrupt controller device based on passed IRQ.
+ *
+ * @param irq IRQ number in its zephyr format
+ *
+ * @return corresponding interrupt controller device in _sw_isr_table
+ */
+const struct device *z_get_sw_isr_device_from_irq(unsigned int irq);
```
Comment (nashif) [inline include/zephyr/sw_isr_table.h:104]: did not do any extensive review, but this caught my attention, we should avoid declaring such function in public headers and give the impression they are public APIs anyone can use. Please move those to where they are being used or putting them in some private header.

**Review by nashif — DISMISSED** [review]

File: arch/common/include/sw_isr_common.h [hunk 4]
```diff
@@ -0,0 +1,57 @@
+/*
```
Comment (ycsin) [inline arch/common/include/sw_isr_common.h:1]: I've moved the helper functions into an internal header, is this what you meant? @nashif

Comment (nashif) [reply arch/common/include/sw_isr_common.h:1]: yeah, I may have overreacted to the sight of z_ APIs, it seems this header is full of them already. Need to spend some time on this and see what the status of the header and if it needs to be in the public domain in the first place. thanks.

**Comment by ycsin** [comment]
rebased

**Review by cfriedt — DISMISSED** [review]

**Review by fkokosinski — COMMENTED** [review]
LGTM in general, one minor question.

Note that I'm reviewing this from the perspective of https://github.com/zephyrproject-rtos/zephyr/pull/62907.

File: arch/common/shared_irq.c [hunk 5]
```diff
@@ -4,6 +4,8 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
+#include "include/sw_isr_common.h"
```
[the remark this answers is not in the document]
Comment (fkokosinski) [reply arch/common/shared_irq.c:7]: > Do you mean targeting the `include` path directly and just do

Yup, exactly

[the remark this answers is not in the document]
Comment (ycsin) [reply arch/common/shared_irq.c:7]: I have no preference over having it relative or targetted with `target_include_directories`, do you prefer the latter? Is the latter a standard practice for such private headers?

[the remark this answers is not in the document]
Comment (cfriedt) [reply arch/common/shared_irq.c:7]: Yeah, it's not completely formalized yet (and it would be great if tooling could automatically sort headers), but this has been around for a while. Based on Google's C++ coding guidelines.

https://github.com/zephyrproject-rtos/zephyr/issues/41543

File: arch/common/CMakeLists.txt [hunk 6]
```diff
@@ -2,6 +2,10 @@
 
 zephyr_library()
 
+target_include_directories(${ZEPHYR_CURRENT_LIBRARY} PRIVATE
```
Comment (ycsin) [inline arch/common/CMakeLists.txt:5]: I hope I'm doing it this correctly

File: arch/common/CMakeLists.txt [hunk 7]
```diff
@@ -2,6 +2,8 @@
 
 zephyr_library()
 
+zephyr_library_include_directories(include)
```
Comment (ycsin) [inline arch/common/CMakeLists.txt:5]: @fkokosinski I've added this and the header path used in the source isn't relative anymore

**Comment by ycsin** [comment]
Rebased for the fix in #64630 to remove the workaround

File: arch/common/sw_isr_common.c
Comment (cfriedt) [inline arch/common/sw_isr_common.c:1]: This file (and the CMakeLists.txt) need some serious cleanup. Please do that in this PR. Maybe as separate commits.

1. remove the `#ifdef CONFIG_DYNAMIC_INTERRUPTS` / `#endif` in this file (we are more sophisticated than that in Zephyr)
2. adjust `CMakeLists.txt` to use `zephyr_library_sources_ifdef(CONFIG_DYNAMIC_INTERRUPTS sw_isr_common.c)`
3. `#define CAT_2ND_LVL_LIST(i, base) ...` does not need to be surrounded by `#ifdef CONFIG_2ND_LEVEL_INTERRUPTS` / `#endif`
4. Same as above with `#define CAT_3RD_LVL_LIST(i, base) ...`
5. `get_parent_offset()` should be static (and get rid of the `#ifdef CONFIG_MULTI_LEVEL_INTERRUPTS` / `#endif`
6. Use more `if (IS_ENABLED(CONFIG_MULTI_LEVEL_INTERRUPTS)` or `if (! IS_ENABLED(CONFIG_MULTI_LEVEL_INTERRUPTS)`
7. Use more `if (IS_ENABLED(CONFIG_3RD_LEVEL_INTERRUPTS)` and `if (! IS_ENABLED(CONFIG_3RD_LEVEL_INTERRUPTS)`
...

Comment (cfriedt) [reply arch/common/sw_isr_common.c:1]: Just to be more consistent code structure it would be a bit nicer to see `if (IS_ENABLED(CONFIG_2ND_LEVEL_INTERRUPTS)` instead of `if (IS_ENABLED(CONFIG_MULTI_LEVEL_INTERRUPTS)`. They are basically a logical equivalence, but that should be encoded in Kconfig rather than being skipped in code.

Comment (ycsin) [reply arch/common/sw_isr_common.c:1]: Can't fully remove `CONFIG_3RD_LEVEL_INTERRUPTS` because some Kconfigs used by the 3rd level variable `_lvl3_irq_list` initialization isn't defined

File: arch/common/multilevel_irq.c [hunk 8]
```diff
@@ -0,0 +1,167 @@
...
+	= { LISTIFY(CONFIG_NUM_2ND_LEVEL_AGGREGATORS, CAT_2ND_LVL_LIST, (,),
+		CONFIG_2ND_LVL_ISR_TBL_OFFSET) };
+
+#define CAT_3RD_LVL_LIST(i, base) \
+	INIT_IRQ_PARENT_OFFSET(INTC_DT_IRQN_GET(CONFIG_3RD_LVL_INTR_0##i##_OFFSET), \
+			       CONFIG_3RD_LVL_INTR_0##i##_OFFSET, IRQ_INDEX_TO_OFFSET(i, base))
+
+#ifdef CONFIG_3RD_LEVEL_INTERRUPTS
+
+const struct _irq_parent_entry _lvl3_irq_list[CONFIG_NUM_3RD_LEVEL_AGGREGATORS]
```
Comment (cfriedt) [inline arch/common/multilevel_irq.c:63]: Does this need to be conditionally defined?

E.g. can we remove the ifdef above, use `if (IS_ENABLED())` elsewhere, and let the linker discard unused code and data?

Comment (ycsin) [reply arch/common/multilevel_irq.c:63]: yeah it fails to compile as the initialization used some undefined macros when 3rd level isn't enabled

**Review by cfriedt — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]
LGTM from the perspective of https://github.com/zephyrproject-rtos/zephyr/pull/62907.

**Comment by carlescufi** [comment]
@dcpleung can you take a look?

**Review by dcpleung — APPROVED** [review]
TBH... we should probably start looking into DAG or tree-like hierarchy for multi-level interrupts so we can avoid making this even complicated in the future.

**Comment by ycsin** [comment]
> TBH... we should probably start looking into DAG or tree-like hierarchy for multi-level interrupts so we can avoid making this even complicated in the future.

Where can I read more about this? Any existing implementation?

**Comment by dcpleung** [comment]
Maybe the Linux kernel? The idea is (probably) simple, where each interrupt controller is a node in a tree. For multi-level interrupts, each node is a child of some other node (except the root node). So you can have arbitrary levels of interrupts, and each controller can trace back to the root controller. Though, this is an overhaul of interrupt handling and is going to be a huge project... for soul(s) brave enough to tackle it.

**Comment by cfriedt** [comment]
> Maybe the Linux kernel?

Yep. Linux would suffice. Of course, it's mostly about the model. The model will also drastically simplify shared interrupts with a marginal increase in complexity. It's also more stateful.

Zephyr's multi-level model (maybe surprisingly) started out simple too, of course 🤪
