### PR TITLE
drivers: sensor: adxl372: update driver

### LINKED ISSUE #49019: Fix multiple issues with adxl372 driver
**Describe the bug**
The adxl372 driver has many issues, it uses a Kconfig to select if it uses SPI or I2C interface which leads to undefined operation, this should be handled in the dts instead. It also does not support multiple instances, nor can it cope with 2 devices on SPI and I2C simultaneously, therefore the driver needs to be updated and fixed to support this and prevent firmware from crashing at start up.

**Impact**
Showstopper

### PR DESCRIPTION
**Pull request by amiclaus**
Handle SPI/I2c interface in the dts.

Support multiple instances.

Tested with nucleo_f446re.

Fixes #49019

### CODE REVIEW

File: drivers/sensor/adxl372/adxl372.c [hunk 1]
```diff
@@ -777,18 +670,74 @@ static int adxl372_probe(const struct device *dev)
...
+	data->hpf = ADXL372_HPF_CORNER_0,
+#elif CONFIG_ADXL372_HPF_CORNER1
+	data->hpf = ADXL372_HPF_CORNER_1,
+#elif CONFIG_ADXL372_HPF_CORNER2
+	data->hpf = ADXL372_HPF_CORNER_2,
+#elif CONFIG_ADXL372_HPF_CORNER3
+	data->hpf = ADXL372_HPF_CORNER_3,
+#elif CONFIG_ADXL372_HPF_DISABLE
+	data->hpf = ADXL372_HPF_DISABLED,
+#endif
```
Comment (MaureenHelm) [inline drivers/sensor/adxl372/adxl372.c:711]: These options should be converted to devicetree properties to allow configuring them on a per-instance basis.

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Thank you for the patch!

**Review by amiclaus — COMMENTED** [review]
- moved requested options from Kconfig to dts.

File: dts/bindings/sensor/adi,adxl372-common.yaml [hunk 2]
```diff
@@ -0,0 +1,43 @@
+# Copyright (c) 2022 Analog Devices Inc.
+# SPDX-License-Identifier: Apache-2.0
+
+properties:
+    odr:
+      type: int
+      required: false
+      default: 0
```
Comment (MaureenHelm) [inline dts/bindings/sensor/adi,adxl372-common.yaml:8]: Default property values need justification (e.g., is it the power on reset value?) in the description. See here for more details: https://docs.zephyrproject.org/latest/build/dts/bindings.html#rules-for-default-values

File: dts/bindings/sensor/adi,adxl372-common.yaml [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+      description: |
+            Accelerometer sampling frequency (ODR)
+      enum:
+        - 0 #400Hz
+        - 1 #800Hz
+        - 2 #1600Hz
+        - 3 #3200Hz
+        - 4 #6400Hz
```
Comment (MaureenHelm) [inline dts/bindings/sensor/adi,adxl372-common.yaml:16]: Please document the encodings in the description so they get included in the rendered documentation. https://docs.zephyrproject.org/latest/build/dts/api/bindings.html

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

**Review by amiclaus — COMMENTED** [review]
- moved most of the device configuration parameters to the `adxl372_dev_config` structure.
- updated bindings documentation for default property values and encodings.

**Review by MaureenHelm — DISMISSED** [review]

File: drivers/sensor/adxl372/adxl372.c [hunk 4]
```diff
@@ -881,25 +771,19 @@ static int adxl372_probe(const struct device *dev)
...
-		return -EINVAL;
-	}
-#endif
-#ifdef CONFIG_ADXL372_SPI
-	if (!spi_is_ready(&cfg->spi)) {
-		LOG_ERR("SPI bus %s not ready!", cfg->spi.bus->name);
-		return -EINVAL;
+	ret = cfg->bus_init(dev);
+	if (ret < 0) {
+		LOG_ERR("Failed to initialize sensor bus\n");
```
Comment (nordicjm) [inline drivers/sensor/adxl372/adxl372.c:784]: \n not needed with LOG_ macros

**Review by nordicjm — COMMENTED** [review]
Tested build for board with sensor, builds, not able to test on device as I do not have the board.

**Review by amiclaus — COMMENTED** [review]
- fixed indentation for the new lines of code added
- removed empty line
- removed `\n` for LOG_ macro

**Review by MaureenHelm — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]
