### PR TITLE
net: tcp: Add exponential backoff for ZWP probing

### LINKED ISSUE #48471: net: tcp: Persistent timer for window probing does not implement exponential backoff
**Describe the bug**
The persistent timer responsible for sending Zero Window Probes should increase it's interval exponentially as stated in RFC 1122. Currently it sends probes at constant rate:
```
            The transmitting host SHOULD send the first zero-window
            probe when a zero window has existed for the retransmission
            timeout period (see Section 4.2.2.15), and SHOULD increase
            exponentially the interval between successive probes.
```

**To Reproduce**
This needs a specially crafted TCP server, that receives the data but does not consume it, which eventually results in reporting a zero window. The issue was reported by one of the Maxwell Pro tests.

**Expected behavior**
RFC compliance.

**Impact**
No major impact.

### PR DESCRIPTION
**Pull request by rlubos**
Persist timer should implement exponential backoff, as per RFC 1122:

    The transmitting host SHOULD send the first zero-window
    probe when a zero window has existed for the retransmission
    timeout period (see Section 4.2.2.15), and SHOULD increase
    exponentially the interval between successive probes.

Implement this, by following Linux behaviour, and simply double the
timeout or each probe transmission.

Additionally, prevent resetting the persist timer in case an
acknowledgment is received with zero window size, and the timer is
already running.

Fixes #48471

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
A side note, when testing Linux behavior it turned out that Linux appears to silently give up on the connection after sending 10 probes (consecutive FIN packet resulted with RST reply), although I don't really think we should follow this behavior?

File: subsys/net/ip/tcp.c [hunk 1]
```diff
@@ -1346,8 +1346,10 @@ static void tcp_send_zwp(struct k_work *work)
 	tcp_derive_rto(conn);
 
 	if (conn->send_win == 0) {
+		conn->zwp_retries++;
 		(void)k_work_reschedule_for_queue(
-			&tcp_work_q, &conn->persist_timer, K_MSEC(TCP_RTO_MS));
+			&tcp_work_q, &conn->persist_timer,
+			K_MSEC(TCP_RTO_MS << conn->zwp_retries));
```
Comment (jukkar) [inline subsys/net/ip/tcp.c:1352]: Should we put some upper limit to the doubling, it might be too much to increase the timeout indefinetly, WDYT?

Comment (rlubos) [reply subsys/net/ip/tcp.c:1352]: I was thinking of it but dropped the idea given that Linux didn't seem to bother. I think we can add some limit however anyway, we'd just need to come up with some reasonable values, as this doesn't seem to be covered by the spec.

How about locking the retransmission counter at the value of 10? This could give ~100 seconds between probes with an initial RTO of 200ms?

Comment (jukkar) [reply subsys/net/ip/tcp.c:1352]: I wonder why there is the limit of 10, I am fine if we do not check the counter limit. I would prefer that we limit the delay between probes to some max value, not sure what that could be.

Comment (ssharks) [reply subsys/net/ip/tcp.c:1352]: The send retry and zwp look very similar in behavior if I read it correctly. Is it possible to rework it a little so you can save a timer and counter?

Comment (rlubos) [reply subsys/net/ip/tcp.c:1352]: > I wonder why there is the limit of 10, I am fine if we do not check the counter limit. I would prefer that we limit the delay between probes to some max value, not sure what that could be.

We can set the max timeout as well, sure. I guess we'd just need to choose some arbitrary value, how about 120 s?

> The send retry and zwp look very similar in behavior if I read it correctly. Is it possible to rework it a little so you can save a timer and counter?

I'm afraid it wouldn't be a trivial change, we'd need to reconfigure the timer every time it's set based on the current context. Plus I'm not really sure if it's possible with the current implementation, I see the following blockers:
*  `send_timer` is used whenever a packet is going to be sent for a local address (corresponding commit: https://github.com/zephyrproject-rtos/zephyr/commit/798588e7092741996a5e27e4d0f411e60a35a606), it'd interfere with probes
* `send_data_timer` is checked and canceled when an ACK is received (https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp.c#L2181), and if the ACK carried zero window the timer would be already set for ZWP. I'd rather avoid reworking that mechanism not to introduce some regression.

Comment (ssharks) [reply subsys/net/ip/tcp.c:1352]: In order to merge both functions you might need to add a ZWP next to the RESEND state.

Comment (rlubos) [reply subsys/net/ip/tcp.c:1352]: > In order to merge both functions you might need to add a ZWP next to the RESEND state.

Can we keep it in a backlog as a possible future improvement? The problem this PR is trying to solve is rather a simple one, I wouldn't like to overcomplicate it with risky changes (I'll OoO for 2 weeks soon).

Comment (rlubos) [reply subsys/net/ip/tcp.c]: I've pushed a change that adds 2-minute cap on the retry timer.

**Review by jukkar — APPROVED** [review]

**Review by ssharks — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]
