### PR TITLE
drivers: ieee802154: rf2xx: Fix OpenThread ACK error

### LINKED ISSUE #23595: RF2XX driver Openthread ACK handling
**Describe the bug**

When using the RF2XX IEEE802.15.4 driver with OpenThread on a NXP K64 platform, I am regularly seeing the following messages:
```
[01:00:38.018,000] <err> net_otPlat_radio: Failed to read ACK frame.
[01:00:38.018,000] <inf> ieee802154_rf2xx: ACK packet not handled.
```

**Expected behavior**
ACKs are handled just fine.

**Impact**
OpenThread works as expected, but I am not sure whether there is still a problem lingering.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK, 0.11.2
 - Commit SHA: https://github.com/zephyrproject-rtos/zephyr/commit/c1c54b13a6ec93c74d674e365e3e0cae80de531c

### PR DESCRIPTION
**Pull request by nandojve**
At OpenThread stack on **ieee802154_radio_handle_ack** method the **net_pkt_read** fail because **net_pkt_cursor** wasn't proper initialized. This ensures that **net_pkt_cursor** is initialized for any ack frame.
Another hidden problem fixed was the **frags** property on **net_buf**. Now it is defined as NULL to ensures that no fragments are available.

This uses commit from #23249
Fixes #23595

### CODE REVIEW

**Review by jukkar — APPROVED** [review]
LGTM

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 1]
```diff
@@ -43,18 +43,20 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME);
...
+#define RF2XX_ACK_FRAME_PENDING_BIT       (1 << 4)
+#define RF2XX_FRAME_CTRL_ACK_REQUEST_BIT  (1 << 5)
 
 static u8_t rf2xx_ack_psdu[RF2XX_ACK_FRAME_LEN] = { 0 };
 static struct net_buf rf2xx_ack_frame = {
 	.data  = rf2xx_ack_psdu,
 	.size  = RF2XX_ACK_FRAME_LEN,
 	.len   = RF2XX_ACK_FRAME_LEN,
 	.__buf = rf2xx_ack_psdu,
+	.frags = NULL,
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: that's superfluous afaik, all non-assigned attributes get zero-ed by default. But it's ok to leave it, if it is more readable

**Review by tbursztyka — APPROVED** [review]
