### PR TITLE
net: http_server: No Error ENETDOWN

### LINKED ISSUE #99792: HTTP Server Shows Error Log Message when iface goes down
### Describe the bug

After #99242 the HTTP Server shows an Error Log Message Every time the iface goes down.

### Regression

- [ ] This is a regression.

### Steps to reproduce

west build --board=stm32h573i_dk/stm32h573xx samples/net/sockets/http_server

Take the iface down, using the net shell command or plugging out the ethernet cable.

### Relevant log output

```shell
[2025-11-13 08:27:05.648] <err> net_http_server: Listening socket error, aborting.
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

OS: Windows
Toolchain: Zephyr SDK 0.17.4
Zephyr: v4.3.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Jowllel**
Set Log Level to Info when the HTTP socket reports ENETDOWN, instead of logging an error each time the network is down.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/99792

### CODE REVIEW

File: subsys/net/lib/http/http_server_core.c [hunk 1]
```diff
@@ -612,8 +612,12 @@ static int http_server_run(struct http_server_ctx *ctx)
...
 
-				/* Listening socket error, abort. */
-				LOG_ERR("Listening socket error, aborting.");
+				if (sock_error == ENETDOWN) {
+					LOG_INF("Socket ENETDOWN");
+				} else {
+					LOG_ERR("Listening socket error, aborting. %d", sock_error);
+				}
+
 				ret = -sock_error;
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_core.c]: As we typically print the error values as <0, I suggest following changes
```
	ret = -sock_error;

	if (ret == -ENETDOWN) {
		LOG_INF("Network is down");
	} else {
		LOG_ERR("Listening socket error, aborting (%d)", ret);
	}
```

**Review by jukkar — COMMENTED** [review]
LGTM, some minor nits.

File: subsys/net/lib/http/http_server_core.c [hunk 2]
```diff
@@ -612,8 +612,14 @@ static int http_server_run(struct http_server_ctx *ctx)
...
 				}
 
-				/* Listening socket error, abort. */
-				LOG_ERR("Listening socket error, aborting.");
+				ret = -sock_error;
+
+				if (ret == -ENETDOWN) {
+					LOG_INF("Network is down");
+				} else {
+					LOG_ERR("Listening socket error, aborting. %d", sock_error);
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_core.c]: Please use the format `"Listening socket error, aborting (%d)", ret);`

File: subsys/net/lib/http/http_server_core.c [hunk 3]
```diff
@@ -612,8 +612,14 @@ static int http_server_run(struct http_server_ctx *ctx)
...
+				}
+
 				ret = -sock_error;
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_core.c]: and remove this line as it is no longer needed

**Review by rlubos — DISMISSED** [review]

File: subsys/net/lib/http/http_server_core.c [hunk 4]
```diff
@@ -612,9 +612,14 @@ static int http_server_run(struct http_server_ctx *ctx)
...
 				}
 
-				/* Listening socket error, abort. */
-				LOG_ERR("Listening socket error, aborting.");
 				ret = -sock_error;
+
+				if (ret == -ENETDOWN) {
+					LOG_INF("Network is down");
+				} else {
+					LOG_ERR("Listening socket error, aborting. %d", ret);
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_core.c]: Minor nit, but I would really like that you read the comments so please change this to
```
LOG_ERR("Listening socket error, aborting (%d)", ret);
```

**Review by jukkar — CHANGES_REQUESTED** [review]

**Review by rlubos — APPROVED** [review]

File: subsys/net/lib/http/http_server_core.c [hunk 5]
```diff
@@ -612,9 +612,14 @@ static int http_server_run(struct http_server_ctx *ctx)
...
 				}
 
-				/* Listening socket error, abort. */
-				LOG_ERR("Listening socket error, aborting.");
 				ret = -sock_error;
+
+				if (ret == -ENETDOWN) {
+					LOG_INF("Network is down");
+				} else {
+					LOG_ERR("Listening socket error, aborting. (%d)", ret);
```
Comment (jukkar) [inline subsys/net/lib/http/http_server_core.c:620]: I wonder why you could not take my original suggestion so we would have avoided all this ping-pong with multiple versions. There is still unnecessary "." at the end but lets ignore it for now.

**Review by jukkar — APPROVED** [review]

File: subsys/net/lib/http/http_server_core.c (hunk 5 above)
Comment (Jowllel) [reply subsys/net/lib/http/http_server_core.c:620]: Ah I'm so sorry. I missed the details completely, should've just copied your suggestion over.
