### PR TITLE
net: sockets: packet: Make it possible to receive packets when unbound 

### LINKED ISSUE #89047: Packet sockets require binding
**Describe the bug**

Using the packet sockets require binding of the socket to an interface to receive packets. See https://github.com/zephyrproject-rtos/zephyr/blob/b469fc188b4fc87c64e598618c07d717bc570c9d/subsys/net/ip/connection.c#L686

**To Reproduce**

Create a packet socket and try to receive a packet without binding. 

**Expected behavior**

Packets from all Interfaces should be received.

**Impact**

Medium 

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain clang
 - Commit SHA main

**Additional context**

### PR DESCRIPTION
**Pull request by rlubos**
Packet sockets should receive packets from all interfaces if not explicitly bound. This PR introduces changes needed to make this happen and associated test cases.

Fixes #89047

### CODE REVIEW

**Comment by rlubos** [comment]
@go2sh FYI, if you have some time, please review

**Review by jukkar — DISMISSED** [review]

File: subsys/net/ip/connection.c [hunk 1]
```diff
@@ -679,13 +699,13 @@ enum net_verdict net_conn_packet_input(struct net_pkt *pkt, uint16_t proto)
...
 
-		if (!(conn->flags & NET_CONN_LOCAL_ADDR_SET)) {
-			continue;
-		}
-
-		local = (struct sockaddr_ll *)&conn->local_addr;
-		if (local->sll_ifindex != net_if_get_by_iface(net_pkt_iface(pkt))) {
-			continue;
+		/* Unbound sockets should collect packets from all interfaces. */
+		if (conn->flags & NET_CONN_LOCAL_ADDR_SET) {
```
Comment (pdgendt) [inline subsys/net/ip/connection.c:703]: Strictly speaking this falls under the [required Misra 14.4 rule](https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html).

```suggestion
		if ((conn->flags & NET_CONN_LOCAL_ADDR_SET) != 0U) {
```

File: subsys/net/lib/sockets/sockets_packet.c [hunk 2]
```diff
@@ -40,6 +40,43 @@ static inline int k_fifo_wait_non_empty(struct k_fifo *fifo,
...
+				union net_ip_header *ip_hdr,
+				union net_proto_header *proto_hdr,
+				int status,
+				void *user_data)
+{
+	NET_DBG("ctx=%p, pkt=%p, st=%d, user_data=%p", ctx, pkt, status,
+		user_data);
+
+	/* if pkt is NULL, EOF */
+	if (!pkt) {
```
Comment (pdgendt) [inline subsys/net/lib/sockets/sockets_packet.c:54]:
```suggestion
	if (pkt == NULL) {
```

File: subsys/net/lib/sockets/sockets_packet.c [hunk 3]
```diff
@@ -40,6 +40,43 @@ static inline int k_fifo_wait_non_empty(struct k_fifo *fifo,
...
+		struct net_pkt *last_pkt = k_fifo_peek_tail(&ctx->recv_q);
+
+		if (!last_pkt) {
```
Comment (pdgendt) [inline subsys/net/lib/sockets/sockets_packet.c:57]:
```suggestion
		if (last_pkt == NULL) {
```

File: subsys/net/ip/net_context.c [hunk 4]
```diff
@@ -2999,6 +2974,26 @@ static int recv_dgram(struct net_context *context,
...
+	/* If the context already has a connection handler, it means it's
+	 * already registered. In that case, all we have to do is 1) update
+	 * the callback registered in the net_context and 2) update the
+	 * user_data and local/remote address and port using net_conn_update().
+	 *
+	 * The callback function passed to net_conn_update() must be the same
+	 * function as the one passed to net_conn_register(), not the callback
+	 * set for the net context passed by recv_udp().
+	 */
+	if (context->conn_handler) {
```
Comment (pdgendt) [inline subsys/net/ip/net_context.c:2986]:
```suggestion
	if (context->conn_handler != NULL) {
```

File: subsys/net/ip/net_context.c [hunk 5]
```diff
@@ -867,11 +863,13 @@ int net_context_bind(struct net_context *context, const struct sockaddr *addr,
...
 	 * means that it's already bound to an interface/port, and we
 	 * don't support rebinding connection to new address/port in
-	 * the code below.
+	 * the code below. Doesn't apply for packet sockets.
 	 * TODO: Support rebinding.
 	 */
-	if (context->conn_handler) {
-		return -EISCONN;
+	if (addr->sa_family != AF_PACKET) {
+		if (context->conn_handler) {
```
Comment (pdgendt) [inline subsys/net/ip/net_context.c:870]:
```suggestion
		if (context->conn_handler != NULL) {
```

File: subsys/net/ip/connection.c [hunk 6]
```diff
@@ -396,23 +414,18 @@ int net_conn_register(uint16_t proto, enum net_sock_type type, uint8_t family,
...
 	conn->type = type;
 	conn->family = family;
 	conn->context = context;
 
-	/*
-	 * Since the net_conn_change_remote() updates the flags in connection,
-	 * must to be called after set the flags to connection.
-	 */
+	ret = net_conn_change_local(conn, local_addr, local_port);
+	if (ret) {
```
Comment (pdgendt) [inline subsys/net/ip/connection.c:425]:
```suggestion
	if (ret < 0) {
```

File: subsys/net/ip/connection.c [hunk 7]
```diff
@@ -476,6 +491,11 @@ int net_conn_update(struct net_conn_handle *handle,
 
 	net_conn_change_callback(conn, cb, user_data);
 
+	ret = net_conn_change_local(conn, local_addr, local_port);
+	if (ret) {
```
Comment (pdgendt) [inline subsys/net/ip/connection.c:495]:
```suggestion
	if (ret < 0) {
```

**Review by pdgendt — DISMISSED** [review]
Sorry to be nitpicking again, we should try to find a way to check this rule in the compliance checks...

I'll still approve as the file already has many similar issues...

**Comment by rlubos** [comment]
@pdgendt Agreed, would be nice if compliance would check for those. All comments should be addressed, hopefully I did not mess up what goes where.

File: subsys/net/ip/connection.c [hunk 8]
```diff
@@ -383,10 +357,54 @@ int net_conn_register(uint16_t proto, enum net_sock_type type, uint8_t family,
...
 		}
 
-		flags |= NET_CONN_LOCAL_ADDR_SET;
+		conn->flags |= NET_CONN_LOCAL_ADDR_SET;
+	} else {
+		conn->flags &= ~NET_CONN_LOCAL_ADDR_SPEC;
+		conn->flags &= ~NET_CONN_LOCAL_ADDR_SET;
+	}
+
+	if (local_port) {
```
Comment (pdgendt) [inline subsys/net/ip/connection.c:369]:
```suggestion
	if (local_port > 0U) {
```

File: subsys/net/ip/connection.c [hunk 9]
```diff
@@ -322,37 +322,12 @@ static int net_conn_change_remote(struct net_conn *conn,
...
-	conn = conn_get_unused();
-	if (!conn) {
-		NET_ERR("Not enough connection contexts. "
-			"Consider increasing CONFIG_NET_MAX_CONN.");
-		return -ENOENT;
-	}
+	NET_DBG("[%zu] connection handler %p changed local",
+		conn - conns, conn);
 
 	if (local_addr) {
```
Comment (pdgendt) [inline subsys/net/ip/connection.c:332]:
```suggestion
	if (local_addr != NULL) {
```

File: subsys/net/ip/connection.c [hunk 10]
```diff
@@ -383,10 +357,54 @@ int net_conn_register(uint16_t proto, enum net_sock_type type, uint8_t family,
...
+	struct net_conn *conn;
+	int ret;
+
+	conn = conn_find_handler(context != NULL ? net_context_get_iface(context) : NULL,
+				 proto, family, remote_addr, local_addr,
+				 remote_port, local_port,
+				 context != NULL ?
+					net_context_is_reuseport_set(context) :
+					false);
+	if (conn) {
```
Comment (pdgendt) [inline subsys/net/ip/connection.c:398]:
```suggestion
	if (conn != NULL) {
```

File: subsys/net/ip/connection.c [hunk 11]
```diff
@@ -383,10 +357,54 @@ int net_conn_register(uint16_t proto, enum net_sock_type type, uint8_t family,
...
+		NET_ERR("Identical connection handler %p already found.", conn);
+		return -EADDRINUSE;
+	}
+
+	conn = conn_get_unused();
+	if (!conn) {
```
Comment (pdgendt) [inline subsys/net/ip/connection.c:404]:
```suggestion
	if (conn == NULL) {
```

**Review by pdgendt — COMMENTED** [review]
A few more

**Review by pdgendt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
