### PR TITLE
storage: flash_map: Fix partition device retrieval

### LINKED ISSUE #26397: storage: flash_map: Only works on limited compatibles
**Describe the bug**

When attempting to use the flash_map API, correct flash_area structures are only correctly generated for a list of in tree compatibles (`soc_nv_flash`, `jedec_spi_nor`, `nordic_qspi_nor`). For compatibles other than these, the `fa_dev_name` field is initialized to NULL.

If an alternate compatible implementing the flash API is provided, no error or warning is displayed at compile time.
Furthermore, no runtime checking on the validity of `fa_dev_name` or the retrieved `struct device *` is performed when reading or writing to flash, leading to runtime hard faults with `device_get_binding` fails. This can be checked through `flash_area_get_sectors` however, which will return -ENODEV in the error case.

The problem is the `DT_FLASH_DEV_FROM_PART` macro in `flash_map_default.c`.
```
#define DT_FLASH_DEV_FROM_PART(part) \
	IS_SOC_NV_FLASH(part, \
	IS_JEDEC_SPI_NOR(part, \
	IS_NORDIC_QSPI_NOR(part, NULL)))
```
Where the NULL case is used for alternate compatibles.

**Expected behavior**
Alternate implementations of the flash API should be able to use the flash_map API to access fixed partitions.

**Impact**
flash_map cannot be used with out of tree flash implementations, or even many of the in-tree implementations.

**Environment (please complete the following information):**
 - Zephyr 2.3

### PR DESCRIPTION
**Pull request by JordanYates**
Change the default behaviour of the flash partition choice when no
matching compatible is found. The new default is the grandparent node
of the fixed-partition.

As the grandparent node is what the jedec_spi_nor and nordic_qspi_nor
compatibles were selecting, remove these as separate checks.

This allows the flash_map API to be used for implementations of the
flash API other than the 3 originally specified (soc_nv_flash,
jedec_spi_nor & nordic_qspi_nor).

Fixes #26397

Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

### CODE REVIEW

**Comment by JordanYates** [comment]
This pull request is predicated on the assumption that the correct flash device for all fixed-partition instances is the grandparent node of that partition.

**Review by nvlsianpu — COMMENTED** [review]
looks good to me.
Would be great to have either @galak or @de-nordic review here.

File: subsys/storage/flash_map/flash_map_default.c [hunk 1]
```diff
@@ -18,21 +18,14 @@
 	COND_CODE_1(DT_NODE_HAS_COMPAT(GPARENT(part), soc_nv_flash), \
 		    (DT_LABEL(DT_PARENT(GPARENT(part)))), (_else_code))
```
Comment (pabigot) [inline subsys/storage/flash_map/flash_map_default.c:19]: I like the refactoring, but there's a lot of gratuitous indirection defining macros that are themselves used in only one location.  I believe the change can be simplified to:
```
diff --git a/subsys/storage/flash_map/flash_map_default.c b/subsys/storage/flash_map/flash_map_default.c
index d7bfd04072..3ab39e1e3f 100644
--- a/subsys/storage/flash_map/flash_map_default.c
+++ b/subsys/storage/flash_map/flash_map_default.c
@@ -13,26 +13,11 @@
 /* Get the grand parent of a node */
 #define GPARENT(node_id) DT_PARENT(DT_PARENT(node_id))
 
-/* if 'soc-nv-flash' return controller label or punt to _else_code */
-#define IS_SOC_NV_FLASH(part, _else_code) \
-       COND_CODE_1(DT_NODE_HAS_COMPAT(GPARENT(part), soc_nv_flash), \
-                   (DT_LABEL(DT_PARENT(GPARENT(part)))), (_else_code))
-
-/* if 'jedec,spi-nor' return controller label or punt to _else_code */
-#define IS_JEDEC_SPI_NOR(part, _else_code) \
-       COND_CODE_1(DT_NODE_HAS_COMPAT(GPARENT(part), jedec_spi_nor), \
-                   (DT_LABEL(GPARENT(part))), (_else_code))
-
-/* if 'nordic,qspi-nor' return controller label or punt to _else_code */
-#define IS_NORDIC_QSPI_NOR(part, _else_code) \
-       COND_CODE_1(DT_NODE_HAS_COMPAT(GPARENT(part), nordic_qspi_nor), \
-                   (DT_LABEL(GPARENT(part))), (_else_code))
-
 /* return flash controller label based on matching compatible or NULL */
-#define DT_FLASH_DEV_FROM_PART(part) \
-       IS_SOC_NV_FLASH(part, \
-       IS_JEDEC_SPI_NOR(part, \
-       IS_NORDIC_QSPI_NOR(part, NULL)))
+#define DT_FLASH_DEV_FROM_PART(part)                                   \
+       DT_LABEL(COND_CODE_1(DT_NODE_HAS_COMPAT(GPARENT(part), soc_nv_flash), \
+                            (DT_PARENT(GPARENT(part))),                \
+                            (GPARENT(part))))
 
 #define FLASH_AREA_FOO(part)                           \
        {.fa_id = DT_FIXED_PARTITION_ID(part),          \
```

**Review by pabigot — CHANGES_REQUESTED** [review]
I think this can be simplified even more; would you consider this solution?

File: subsys/storage/flash_map/flash_map_default.c (hunk 1 above)
Comment (JordanYates) [reply subsys/storage/flash_map/flash_map_default.c:19]: The advantage of how it is currently done is that it is simple to add further special cases should they become necessary again. That said, I don't know how likely that is, and I don't have strong opinions one way or the other.

Comment (pabigot) [reply subsys/storage/flash_map/flash_map_default.c:19]: My thought is that everything we've added has been a grandparent, except soc_nv_flash which is a great-grandparent.  If something else needs great-grandparent we can abstract the conditional with a `NEEDS_GGPARENT()`.  And whatever we get we need its label, so that can be lifted out to the top rather than repeated in each branch.

However we should get input from others; if the original approach is preferred I'll withdraw the NAK.

Comment (de-nordic) [reply subsys/storage/flash_map/flash_map_default.c:19]: @JordanYates I agree with @pabigot  here. Can you make the change so that we could proceed with the review?

Comment (JordanYates) [reply subsys/storage/flash_map/flash_map_default.c]: done

Comment (de-nordic) [reply subsys/storage/flash_map/flash_map_default.c]: Thanks!

**Review by pabigot — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Comment by de-nordic** [comment]
Built and checked on nrf52840.
