### PR TITLE
drivers: intc: plic: add support for multiple instances

### LINKED ISSUE #62441: [RFC][RISCV] Support for multiple instances of multi-level interrupt controller
## Introduction

Hi all, I'm looking at our custom [`intc_plic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_plic.c) implementation and really feel like we should do something upstream to minimize the gap between upstream & our codebase, our [`intc_plic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_plic.c) has some patch to support multi-instance, alongside with some hacks to the RISCV's [`irq_manage.c`](https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/riscv/core/irq_manage.c) to complete that change, all only works under a very specific configurations.

### Problem description

As far as I can tell, Zephyr's build system and/or the RISCV's [`arch_irq_connect_dynamic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/riscv/core/irq_manage.c#L35) install approach do not support such multi-instance & multi-level interrupt controller driver. For [`intc_plic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_plic.c) to support multiple instances, we need to be able to discern the IRQs between the instances, and install them accordingly into the [`_sw_isr_table`](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/sw_isr_table.h#L44). To do that we will need to extend the existing LUT in the `sw_isr_common` to record the corresponding interrupt controller device along with its IRQN & ISR table offset.

### Proposed change

Some ideas, starting from the easiest one..

1. Allow soc/driver implementation of the (RISCV's) `arch_irq_connect_dynamic`, to facilitate custom implementation downstream - #62442
2. Update the `sw_isr_common` and headers so that we can discern the parent interrupt controller device from the multi-level IRQN, update `intc_plic` to support multiple instances & pass in unmodified version of the `irq` number from RISCV's `soc_common_irq` when PLIC & multilevel is enabled - https://github.com/zephyrproject-rtos/zephyr/pull/62907

### LINKED ISSUE #62956: [driver][intc_plic] should have used SYS_IO APIs instead of accessing the regs directly
**Describe the bug**
The RISCV PLIC driver (`intc_plic`) currently access its memory mapped registers directly, whereas it should be using SOC specific sys_io APIs which have the necessary operations to access them safely.

**To Reproduce**
1. Build anything that uses `intc_plic`
2. The driver is accessing the registers directly, which can cause issue for custom board using SOC-specific RISCV SYS_IO APIs

**Expected behavior**
The driver should use `sys_read*` & `sys_write*` when accessing these memory mapped registers.

**Impact**
This can be a showstopper for custom RISCV boards that have to use SOC-specific SYS_IO APIs to access its registers properly

**Environment (please complete the following information):**
 - Current main: 8951bab7e741f3750532d4af68497b9af06a453c

### LINKED ISSUE #63465: arch: riscv: support for multi-instance multi-level interrupt
**Describe the bug**
Despite the multi-instance interrupt being supported by the Zephyr's multi-level interrupt encoding scheme, see [Multi-level Interrupt handling](https://docs.zephyrproject.org/latest/kernel/services/interrupts.html#id2), multiple instances of [`intc_plic`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_plic.c) is currently not possible due to the way that the `irq` number is passed into the `riscv_plic_*` APIs, see [1](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/common/soc_common_irq.c#L49), [2](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/common/soc_common_irq.c#L70), [3](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/common/soc_common_irq.c#L91), [4](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/riscv/riscv-privileged/common/soc_common_irq.c#L107).

The multi-level encoded `irq` has its level 1 information stripped off before passed into an interrupt controller:

https://github.com/zephyrproject-rtos/zephyr/blob/e11bc94a44adabc6e29c74e2c903083e42bf0991/soc/riscv/riscv-privileged/common/soc_common_irq.c#L41-L53

This made it impossible for any driver, including out-of-tree ones, to differentiate an `irq` that is originated from one instance and another.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
    - Out-of-tree RISCV board
 - What have you tried to diagnose or workaround this issue?
    - There is no other way around modifying Zephyr source

**To Reproduce**
1. Build an out-of-tree RISCV board with interrupt controller driver that support multiple instances
2. Have some devices or software that depend on more than one interrupt controllers
3. Only one interrupt controller and its dependants work

**Expected behavior**
Both interrupt controllers and their dependants should work, since that is supported by Zephyr multi-level interrupt scheme.

**Impact**
Showstopper for applications that require multiple instances of interrupt controller on RISCV arch.

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephyr SDK
 - Commit SHA e11bc94a44adabc6e29c74e2c903083e42bf0991

### PR DESCRIPTION
**Pull request by ycsin**
1. Refactored the build_all test added in #62541
2. Refactored the `intc_plic` driver to be multi-instance ready
3. Updated the `sw_isr_*` so that it also records the device pointer of the interrupt controllers & provide functions to do a lookup for the controller using the IRQN, as well as getting the ISR table offset for a controller
4. Updated the `intc_plic` driver to use the functions in the `sw_isr` so that it can differentiate parent controller from IRQN, and invoke the correct ISR with the correct offset from `sw_isr_*`
   - Modified some description in the `riscv_plic` header file, previously the driver expects the trimmed IRQN returned by `irq_from_level_2` as there can only be one controller, with multi-instance, we need the full multi-level-encoded IRQN, so that the driver can determine the right controller with `z_get_sw_isr_device` using the 1st level IRQ.
6. Added a build_all test for multi-instance on `qemu_riscv*` as no QEMU machine supports more than one PLIC. Not sure if this is helpful.

fixes #62441
fixes #62956
fixes #63465

### CODE REVIEW

File: drivers/interrupt_controller/intc_plic.c [hunk 1]
```diff
@@ -146,54 +187,58 @@ void riscv_plic_set_priority(uint32_t irq, uint32_t priority)
  * This routine returns the RISCV PLIC-specific interrupt line causing an
  * interrupt.
  *
+ * @param dev Optional device pointer to get the interrupt line's controller
+ *
  * @return PLIC-specific interrupt line causing an interrupt.
  */
-int riscv_plic_get_irq(void)
+unsigned int riscv_plic_get_irq(const struct device *dev)
```
Comment (cfriedt) [inline drivers/interrupt_controller/intc_plic.c:194]: It would be better to add a new function called something like `uint32_t riscv_plic_get_irq_by_dev(const struct device *dev)` instead of modifying the signature of the existing code.

With that, `unsigned int riscv_plic_get_irq(void)` can become a 1-line wrapper around the new function (passing `NULL`) and fewer 1-line changes are needed in e.g. unrelated gpio drivers

File: dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml [hunk 2]
```diff
@@ -12,7 +12,7 @@ properties:
     type: int
     description: Number of external interrupts supported
     required: true
-  riscv,trigger-reg-offset:
-    type: int
-    default: 4224
-    description: Offset of the trigger type register if supported
+
+  support-edge-interrupt:
```
Comment (cfriedt) [inline dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml:16]: Is just a feature that is always available? Do we even need a Devicetree property here? If it's always available, then the Devicetree property is superfluous (and should probably just be removed).

Comment (cfriedt) [reply dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml:16]: @fkokosinski - can you weigh in here?

File: tests/drivers/build_all/interrupt_controller/intc_plic/app.edge_interrupt.overlay [hunk 3]
```diff
@@ -7,7 +7,7 @@
  /{
 	soc {
 		plic: interrupt-controller@c000000 {
-			riscv,trigger-reg-offset = < 0x00001080 >;
+			support-edge-interrupt;
```
Comment (cfriedt) [inline tests/drivers/build_all/interrupt_controller/intc_plic/app.edge_interrupt.overlay:10]: possibly remove, depending on what the consensus is.

File: drivers/interrupt_controller/intc_plic.c [hunk 4]
```diff
@@ -46,17 +76,20 @@ static int save_irq;
...
-		volatile uint32_t *trig = (volatile uint32_t *)PLIC_EDGE_TRIG_TYPE;
+	const struct plic_config *config = dev->config;
+
+	if (config->trig != 0) {
+		volatile uint32_t *trig = (volatile uint32_t *) config->trig;
 
-		trig += (irq >> PLIC_EDGE_TRIG_SHIFT);
-		return *trig & BIT(irq);
+		trig += (local_irq >> PLIC_EDGE_TRIG_SHIFT);
+		return *trig & BIT(local_irq);
```
Comment (cfriedt) [inline drivers/interrupt_controller/intc_plic.c:92]: should use `sys_write32(..)`

File: drivers/interrupt_controller/intc_plic.c [hunk 5]
```diff
@@ -73,8 +106,10 @@ static int riscv_plic_is_edge_irq(uint32_t irq)
  */
 void riscv_plic_irq_enable(uint32_t irq)
 {
+	const struct device *dev = get_plic_dev_from_irq(irq);
+	const struct plic_config *config = dev->config;
+	volatile uint32_t *en = (volatile uint32_t *) config->irq_en;
```
Comment (cfriedt) [inline drivers/interrupt_controller/intc_plic.c:111]: will also need to use `sys_read32(..)` / `sys_write32(..)`

Please file a bug for that too.

File: drivers/interrupt_controller/intc_plic.c [hunk 6]
```diff
@@ -202,49 +247,72 @@ static void plic_irq_handler(const void *arg)
...
+static int plic_init(const struct device *dev)
 {
-
-	volatile uint32_t *en = (volatile uint32_t *)PLIC_IRQ_EN;
-	volatile uint32_t *prio = (volatile uint32_t *)PLIC_PRIO;
-	volatile struct plic_regs_t *regs =
-	    (volatile struct plic_regs_t *)PLIC_REG;
-	int i;
+	const struct plic_config *config = dev->config;
+	volatile uint32_t *en = (volatile uint32_t *) config->irq_en;
```
Comment (cfriedt) [inline drivers/interrupt_controller/intc_plic.c:263]: Also `sys_read32()` / `sys_write32()`

File: drivers/interrupt_controller/intc_plic.c (hunk 5 above)
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c:111]: #62956

File: drivers/interrupt_controller/intc_plic.c (hunk 4 above)
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c:92]: #62956

File: drivers/interrupt_controller/intc_plic.c (hunk 6 above)
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c:270]: #62956

File: drivers/interrupt_controller/intc_plic.c (hunk 1 above)
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c]: fixed

File: dts/bindings/interrupt-controller/interrupt-controller.yaml [hunk 7]
```diff
@@ -12,3 +12,6 @@ properties:
     type: int
     required: true
     description: Number of items to expect in an interrupt specifier
+  "has-multi-instance":
```
Comment (ycsin) [inline dts/bindings/interrupt-controller/interrupt-controller.yaml:15]: This is needed for the DT macro in `sw_isr_common.c` to get the device pointer of a root interrupt controller.
Alternatively this might be replaceable by Kconfigs (`INTC_HAS_MULTI_INSTANCE`, selected by interrupt controller that supports multi-instance, but not necessarily enabled) to only compile the multi-instance related code when `INTC_ENABLE_MULTI_INSTANCE` is enabled

File: dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml (hunk 2 above)
Comment (fkokosinski) [reply dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml:16]: Hi @cfriedt. I've looked around a bit and found out that in the Linux irqchip driver implementation for PLIC SiFive platforms (fu540, fu740; HiFive Unleashed and HiFive Unmatched, respectively) also don't support the edge mode: https://github.com/torvalds/linux/blob/master/drivers/irqchip/irq-sifive-plic.c#L565-L581.

This IMO really suggests that it's not a bug in the documentation that SiFive provides for their chips, and that they really lack the support of edge-triggered interrupts, so I would suggest to  leave the `support-edge-interrupt` property as currently defined by this PR.

**Comment by ycsin** [comment]
rebased

File: drivers/interrupt_controller/intc_plic.c [hunk 8]
```diff
@@ -22,12 +22,15 @@
 #include <zephyr/irq.h>
 
 #define PLIC_BASE_ADDR(n) DT_INST_REG_ADDR(n)
+#define PLIC_REG_PRIO_OFFSET 0x0
```
Comment (carlocaione) [inline drivers/interrupt_controller/intc_plic.c:26]: should this be `0x1000`?

File: drivers/interrupt_controller/intc_plic.c [hunk 9]
```diff
@@ -22,12 +22,15 @@
...
 #define PLIC_REG_TRIG_TYPE_OFFSET 0x1080
+#define PLIC_REG_IRQ_EN_OFFSET 0x2000
+#define PLIC_REG_REGS_OFFSET 0x200000
```
Comment (carlocaione) [inline drivers/interrupt_controller/intc_plic.c]: Can you use one single alignment style?

File: arch/common/sw_isr_common.c
Comment (carlocaione) [inline arch/common/sw_isr_common.c:1]: I think the changes in this file should be submitted as a standalone PR because it is not strictly related to PLIC at all.

File: drivers/interrupt_controller/intc_plic.c (hunk 8 above)
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c:26]: https://github.com/zephyrproject-rtos/zephyr/blob/a2b238eee77cf9137db858618eb2881c53963330/dts/riscv/virt.dtsi#L168-L171

prio offset should be 0, 0x1000 is the offset of pending bits according to the specs

File: drivers/interrupt_controller/intc_plic.c (hunk 9 above)
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c]: These macros will have a single alignment style in the end, is that acceptable? I didnt adopt the existing alignment style as it tends to go out of alignment in the long run

File: dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml (hunk 2 above)
Comment (cfriedt) [reply dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml:16]: @keith-packard  - any insider info here from your previous role?

Comment (cfriedt) [reply dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml:16]: @fkokosinski

https://www.kernel.org/doc/Documentation/devicetree/bindings/interrupt-controller/sifive%2Cplic-1.0.0.yaml

Seems to suggest that SiFive's PLIC *does* support edge triggering in the kernel (and that all of them do), and it was signed-off by Paul & Palmer, so I'm inclined to lean toward going with it.

> The PLIC supports both edge-triggered and level-triggered interrupts

What it does say is different in some implementations is whether interrupts are queued or dropped if triggered while they are already pended, which can probably be handled in code, in a somewhat generic way. Good to be aware of, in any case.

File: arch/common/sw_isr_common.c
Comment (cfriedt) [reply arch/common/sw_isr_common.c:1]: That's probably a healthy thing. If it can be done independently, lets do that

File: dts/bindings/interrupt-controller/interrupt-controller.yaml (hunk 7 above)
Comment (cfriedt) [reply dts/bindings/interrupt-controller/interrupt-controller.yaml:15]: Consistent with Zephyr's driver model, it's better to leave the gate assuming that drivers can be multi-instance. That's also a DT thing, and not a Kconfig thing. The number of instances of a dt-compat is implicitly part of DT. So I would say that it's better to proceed under the assumption that this is always `true`. There is no real need to reiterate something explicitly that is implicit in devicetree.

If this is part of the `sw_isr_common.c`, please make the necessary adjustments to the other PR.

File: dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml (hunk 2 above)
Comment (keith-packard) [reply dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml:16]: > @keith-packard - any insider info here from your previous role?

Afraid I'd have to read through documentation I no longer have access to -- I don't specifically remember anything about PLIC interrupt configurations...

Comment (cfriedt) [reply dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml:16]: > Hi @cfriedt. I've looked around a bit and found out that in the Linux irqchip driver implementation for PLIC SiFive platforms (fu540, fu740; HiFive Unleashed and HiFive Unmatched, respectively) also don't support the edge mode: https://github.com/torvalds/linux/blob/master/drivers/irqchip/irq-sifive-plic.c#L565-L581.

Yea, that's the thing - some datasheets do, and some datasheets don't, but the memory map in Linux does support the register, and it's a "quirk" in Linux. Andes and telink support the register and document it in their datasheet. SiFive supports it in their SoC's, but it's undocumented / "reserved", almost as if it were a kind of copy-paste issue from the PLIC spec. 

> SiFive SOCs include an implementation of the Platform-Level Interrupt Controller (PLIC)..  the PLIC supports both edge-triggered and level-triggered interrupts..

http://archive.lwn.net:8080/linux-kernel/b4ddcb20-6109-22ac-4691-c2c012ea112a@wdc.com/T/

I very much suspect that it has been a bit of a contentious topic. The spec was (unintentionally) ambiguous and it's possible that some vendors had one interpretation, while others had another interpretation.

> This IMO really suggests that it's not a bug in the documentation that SiFive provides for their chips, and that they really lack the support of edge-triggered interrupts, so I would suggest to leave the `support-edge-interrupt` property as currently defined by this PR.

https://github.com/torvalds/linux/blob/master/drivers/irqchip/irq-sifive-plic.c#L565-L581.

Of course, we now know that the opposite is true, as we have read. SiFive does, in fact, support edge triggering (via a "quirk"), even though their datasheet does not mention it in the memory map, which is the same "documentation bug" in the PLIC spec itself. Even the ESP32-C3 interrupt controller supports both edge and level-triggered interrupts.

Also important to note, is that `riscv,plic0` and `sifive,plic-1.0.0` are deprecated bindings for "legacy" systems, while all newer compatibles are hard-coded to support edge triggering and use a binding that also hard-codes this support. I would say, that this was a chosen "documentation bug" workaround rather than revising the already-ratified PLIC spec.

https://github.com/torvalds/linux/blob/master/drivers/irqchip/irq-sifive-plic.c#L565-L581

So, IMHO, I think this was a bit of a "documentation bug" that unfortunately caused some misinterpretations of the specification and likely had some undesirable fallout. It happens.

Comment (ycsin) [reply dts/bindings/interrupt-controller/sifive,plic-1.0.0.yaml:16]: The parameter is dropped in #63273

File: tests/drivers/build_all/interrupt_controller/intc_plic/app.edge_interrupt.overlay (hunk 3 above)
Comment (ycsin) [reply tests/drivers/build_all/interrupt_controller/intc_plic/app.edge_interrupt.overlay:10]: The parameter is dropped in #63273

File: dts/bindings/interrupt-controller/interrupt-controller.yaml (hunk 7 above)
Comment (ycsin) [reply dts/bindings/interrupt-controller/interrupt-controller.yaml]: this prop is removed in #63172

**Comment by cfriedt** [comment]
Going to add `DNM` here until #63172 is merged. Feel free to review in any case.

**Review by cfriedt — DISMISSED** [review]
Pre-emptively acking. Please remember to rebase once #63172 is merged (for sw_isr_common changes)

File: arch/common/sw_isr_common.c [hunk 10]
```diff
@@ -16,12 +16,38 @@
...
-};
+/*
+ * Insert code if the node_id is an interrupt controller
+ */
+#define Z_IF_DT_IS_INTC(node_id, code)                                                             \
+	IF_ENABLED(DT_NODE_HAS_PROP(node_id, interrupt_controller), (code))
+
+/*
+ * Expands to node_id if its IRQN is equal to `irq`, nothing otherwise
+ * This only works for `irq` between 0 & 255, see `IS_EQ`
```
Comment (ycsin) [inline arch/common/sw_isr_common.c:27]: This will support up to 4095 after #63496 is merged

**Comment by jhedberg** [comment]
> Pre-emptively acking. Please remember to rebase once #63172 is merged (for sw_isr_common changes)

#63172 wasn't flagged for 3.5 even though this PR is. I fixed the milestone for the other PR, but it's getting quite late in the game for 3.5 to introduce such big changes.

**Review by cfriedt — DISMISSED** [review]

**Comment by ycsin** [comment]
rebased on top of #63172, following the changes over there

**Review by cfriedt — DISMISSED** [review]

**Review by fkokosinski — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
