### PR TITLE
drivers: dma: fix error when suspend and resume not supported

### LINKED ISSUE #44106: test of dma drivers fails on dma_m2m_loop_test
**Describe the bug**
the testcase : tests/drivers/dma/loop_transfer fails on all stm32 target boards on the test_loop_suspend_resume()

After the merge of the https://github.com/zephyrproject-rtos/zephyr/pull/43738/ the testcase fails because the stm32 dma has no suspend/resume mode, 
Probably also failing on any target where the dma_api_suspend suspend; 	dma_api_resume resume; are not implemented ( -ENOSYS If not implemented. returned) as described in the include/drivers/dma.h 

Please also mention any information which could help others to understand
the problem you're facing:
 - all the stm32 targets that can execute the tests/drivers/dma/loop_transfer test.
 - this comes as a regression after the change in the test_loop_suspend_resume() function of the tests/drivers/dma/loop_transfer/src/test_dma_loop.c

**To Reproduce**
1. west build -p auto -b nucleo_wb55rg tests/drivers/dma/loop_transfer/
3. west flash

**Expected behavior**
```
START - test_dma_m2m_loop_suspend_resume
DMA memory to memory transfer started on DMAMUX_1
Preparing DMA Controller
this platform do not support the dma channel
Starting the transfer on channel 11 and waiting for 1 second
Suspended transfers
dma suspend not supported
 PASS - test_dma_m2m_loop_suspend_resume in 0.21 seconds
===================================================================
Test suite dma_m2m_loop_test succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```
**Impact**
test campaign failure

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-1639-ga4d438444771  ***
Running test suite dma_m2m_loop_test
===================================================================
START - test_dma_m2m_loop
DMA memory to memory transfer started on DMAMUX_1
Preparing DMA Controller
this platform do not support the dma channel
Starting the transfer on channel 11 and waiting for 1 second
Each RX buffer should contain the full TX buffer string.
RX data Loop 0: The quick brown fox jumps over the lazy dog
RX data Loop 1: The quick brown fox jumps over the lazy dog
RX data Loop 2: The quick brown fox jumps over the lazy dog
RX data Loop 3: The quick brown fox jumps over the lazy dog
RX data Loop 4: The quick brown fox jumps over the lazy dog
Finished: DMA
 PASS - test_dma_m2m_loop in 1.49 seconds
===================================================================
START - test_dma_m2m_loop_suspend_resume
DMA memory to memory transfer started on DMAMUX_1
Preparing DMA Controller
this platform do not support the dma channel
Starting the transfer on channel 11 and waiting for 1 second
dma suspend not supported
E: Transfer Error.
I: tc: 0, ht: 0, te: 0, gi: 0

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/dma/loop_transfer/src/)
DMA could not proceed, an error occurred

 FAIL - test_dma_m2m_loop_suspend_resume in 0.40 seconds
===================================================================
Test suite dma_m2m_loop_test failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - Commit SHA : 1d3dbd49e14e9dec14a6bfa4d69fa56b62406784

**Additional context**

### PR DESCRIPTION
**Pull request by FRASTM**
update dma loop test to avoid error in the suspend/resume
testcase when the dma drivers does not provide the service.
The test_loop_suspend_resume function exits immediately
with transfer_count set to a oversized value, so that
dma is stopped and testcase ends properly.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/44106

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by teburd** [comment]
@FRASTM see #43984

**Comment by FRASTM** [comment]
Test campaign passed on the stm32xx
```
test,arch,platform,status,extra_args,handler,handler_time,ram_size,rom_size
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_f746zg,passed,,na,5.27608060836792,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_wb55rg,passed,,na,4.607640981674194,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_g071rb,passed,,na,4.2939393520355225,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,stm32l562e_dk,passed,,na,5.861671209335327,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_g474re,passed,,na,4.631453037261963,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_wl55jc,passed,,na,6.1563029289245605,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,stm32f3_disco,passed,,na,5.721297025680542,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_f429zi,passed,,na,5.399385452270508,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_l152re,passed,,na,9.70708680152893,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_f091rc,passed,,na,5.150474786758423,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_f103rb,passed,,na,5.766777276992798,0,0
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,disco_l475_iot1,passed,,na,5.9741127490997314,0,0
```

**Comment by teburd** [comment]
There would be a message, but it should return TC_PASS https://github.com/zephyrproject-rtos/zephyr/pull/43984/files#diff-ebead0703869e01965e37503d35285f963630eebeb50b22fcbcaac7d51205f6bR268 if -ENOSYS is returned which should be the default if the function pointer is NULL
https://github.com/zephyrproject-rtos/zephyr/pull/43984/files#diff-ebead0703869e01965e37503d35285f963630eebeb50b22fcbcaac7d5

**Comment by teburd** [comment]
I see the issue I think, the isr is getting called right after irq_unlock() and before test case returns resulting in the zassert failing in the isr. I have a fix in the works

**Comment by teburd** [comment]
please try with my latest push, it works for me on stm32f3_disco

**Comment by FRASTM** [comment]
> please try with my latest push, it works for me on stm32f3_disco

that works for me too, tested on the nucleo_wb55rg or  nucleo_h743zi  (with DMAMUX) aand nucleo_l476rg (no DMAMUX)

**Comment by FRASTM** [comment]
Let's keep the https://github.com/zephyrproject-rtos/zephyr/pull/43984 instead
to fix the https://github.com/zephyrproject-rtos/zephyr/issues/44106

**Comment by FRASTM** [comment]
During the tests/drivers/dma/loop_transfer/test_dma_m2m_loop, the immediately after the dma_start, the irq is pending before the dma suspend comes. The channel is disabled and irq flag are off when _isr_wrapper arrives.

**Comment by teburd** [comment]
I think its fair to bail on the ISR if its stopped

**Review by teburd — DISMISSED** [review]

**Comment by hakehuang** [comment]
@FRASTM  this fix is in driver, so the PR title shall be changed to 'driver: dma'

**Review by erwango — CHANGES_REQUESTED** [review]
> @FRASTM this fix is in driver, so the PR title shall be changed to 'driver: dma'

I'm in line with @hakehuang, please fix the title

File: drivers/dma/dma_stm32.c [hunk 1]
```diff
@@ -574,16 +584,16 @@ DMA_STM32_EXPORT_API int dma_stm32_stop(const struct device *dev, uint32_t id)
 	if (id >= config->max_streams) {
 		return -EINVAL;
 	}
+	dma_stm32_clear_stream_irq(dev, id);
```
Comment (erwango) [inline drivers/dma/dma_stm32.c:587]: Please break a line before this.

File: drivers/dma/dma_stm32.c [hunk 2]
```diff
@@ -574,16 +584,16 @@ DMA_STM32_EXPORT_API int dma_stm32_stop(const struct device *dev, uint32_t id)
...
 
+	dma_stm32_disable_stream(dma, id);
 #if !defined(CONFIG_DMAMUX_STM32) || defined(CONFIG_SOC_SERIES_STM32H7X)
 	LL_DMA_DisableIT_TC(dma, dma_stm32_id_to_stream(id));
 #endif /* CONFIG_DMAMUX_STM32 */
```
Comment (erwango) [inline drivers/dma/dma_stm32.c:593]: Please break a line after this

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
changing commit (and PR) title 
rebase

**Review by teburd — DISMISSED** [review]

**Comment by FRASTM** [comment]
rebased on 005968a81

File: drivers/dma/dma_stm32.c [hunk 3]
```diff
@@ -574,15 +583,16 @@ DMA_STM32_EXPORT_API int dma_stm32_stop(const struct device *dev, uint32_t id)
 		return -EINVAL;
 	}
 
+	dma_stm32_clear_stream_irq(dev, id);
+
+	dma_stm32_disable_stream(dma, id);
```
Comment (erwango) [inline drivers/dma/dma_stm32.c:588]: Please break a line after this

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
rebase on 48877f8bdcd92f7e14a72ab4c830989f15f1e884
change after review

**Comment by FRASTM** [comment]
```
Running test suite dma_m2m_loop_test
===================================================================
START - test_dma_m2m_loop
DMA memory to memory transfer started on DMAMUX_1
Preparing DMA Controller
this platform do not support the dma channel
Starting the transfer on channel 11 and waiting for 1 second
Each RX buffer should contain the full TX buffer string.
RX data Loop 0: The quick brown fox jumps over the lazy dog
The quick brown fox jumps over the lazy dog
...
Finished: DMA
PASS - test_dma_m2m_loop in 0.609 seconds
===================================================================
START - test_dma_m2m_loop_suspend_resume
DMA memory to memory transfer started on DMAMUX_1
Preparing DMA Controller
this platform do not support the dma channel
Starting the transfer on channel 11 and waiting for 1 second
suspend not supported PASS - test_dma_m2m_loop_suspend_resume in 0.19 seconds
===================================================================
Test suite dma_m2m_loop_test succeeded
===================================================================
RunID: a423c9eab27d9d8cd3fd5372fd6e0605
PROJECT EXECUTION SUCCESSFUL
```

File: drivers/dma/dma_stm32.c [hunk 4]
```diff
@@ -102,7 +102,16 @@ static void dma_stm32_irq_handler(const struct device *dev, uint32_t id)
 		stream->busy = false;
 	}
 
-	/* the dma stream id is in range from STM32_DMA_STREAM_OFFSET..<dma-requests> */
+	/* do not continue if dma channel is not enabled */
+#ifdef CONFIG_DMA_STM32_V1
+	if (!LL_DMA_IsEnabledStream(dma, dma_stm32_id_to_stream(id))) {
```
Comment (erwango) [inline drivers/dma/dma_stm32.c:107]: A new `stm32_dma_is_enabled_stream()` would be nice.
As we already have `stm32_dma_enable_stream()` and `stm32_dma_disable_stream()`

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/dma/dma_stm32.c (hunk 4 above)
Comment (FRASTM) [reply drivers/dma/dma_stm32.c]: changed: 
checking the channel busy is better because the stm32F4x or stm32F7x (dma  of type V1) could fail in irq endlessly

**Review by erwango — DISMISSED** [review]

**Comment by FRASTM** [comment]
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_f746zg,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_wb55rg,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,stm32l562e_dk,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_g474re,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_wl55jc,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,stm32f3_disco,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_f429zi,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_l152re,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_f091rc,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,nucleo_f103rb,passed,
tests/drivers/dma/loop_transfer/drivers.dma.loop_transfer,arm,disco_l475_iot1,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,nucleo_f746zg,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,nucleo_wb55rg,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,stm32l562e_dk,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,nucleo_g474re,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,nucleo_wl55jc,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,stm32f3_disco,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,nucleo_f429zi,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,nucleo_l152re,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,nucleo_f091rc,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,nucleo_f103rb,passed,
tests/drivers/dma/chan_blen_transfer/drivers.dma.chan_blen_transfer,arm,disco_l475_iot1,passed,

**Comment by erwango** [comment]
@teburd Would you mind having another look ?

**Comment by FRASTM** [comment]
This PR has been set to DNM because it makes the stm32U5 trig DMA interrupt endlessly

**Comment by teburd** [comment]
Let me know, happy to accept the patch if it solves problems for st, sorry I missed the mention above

**Comment by carlescufi** [comment]
@erwango @gmarull please take a look

**Review by erwango — APPROVED** [review]

**Review by gmarull — APPROVED** [review]
