### PR TITLE
Making telnet functional with esWiFi

### LINKED ISSUE #25621: ESWiFi does not populate info about remote when invoking callback
**Describe the bug**
It was observed that telnet does not work with on the STM32 disco IOT board which has support for "esWiFi" driver. Upon further inspection, it was found that the driver does not populate information about the remote, including port and ip which causes the NET stack to fail. 

**To Reproduce**
1. west build -p auto -b disco_l475_iot1 samples\net\telnet
2. See error

**Expected behavior**
WiFi driver should pass remote information when invoking CB so that NET stack doesn't fail. 

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: GNU Arm Toolchain
 - V2.3.0 RC

### PR DESCRIPTION
**Pull request by bwasim**
Telnet was found non-functional with "eswifi", a "net offloaded" driver. The telnet client was able to successfully connect with the Zephyr server. However, the telnet connection was forcibly closed by Zephyr as soon as telnet_command_send_reply was called. 

The problem occurred because information about the "remote" in the "net_context" was not populated during connection, which resulted in **-40** error.

Resolved and tested telnet with Disco IOT board..  

Fixes #25621

### CODE REVIEW

**Comment by bwasim** [comment]
@jukkar , Can you please review this also ? Thanks..

File: drivers/wifi/eswifi/eswifi_offload.c [hunk 1]
```diff
@@ -484,8 +484,10 @@ void eswifi_offload_async_msg(struct eswifi_dev *eswifi, char *msg, size_t len)
 			return;
 		}
 
-		sin_addr = &net_sin(&socket->peer_addr)->sin_addr;
+		struct sockaddr_in *peer = net_sin(&socket->peer_addr);
+		sin_addr = &peer->sin_addr;
 		memcpy(&sin_addr->s4_addr, ip, 4);
+		peer->sin_port = port;
```
Comment (jukkar) [inline drivers/wifi/eswifi/eswifi_offload.c:492]: Typically the port and other values in sockaddr are in network byte order. Here the port is clearly in host byte order which looks wrong. So it looks like this should be `peer->sin_port = htons(port);` instead. You can use for example net-shell (use "net conn" command) to check what is the remote port value.

File: subsys/shell/shell_telnet.c [hunk 2]
```diff
@@ -245,6 +245,10 @@ static void telnet_accept(struct net_context *client,
 
 	sh_telnet->client_ctx = client;
 
+	/* Save information about remote. */
```
Comment (jukkar) [inline subsys/shell/shell_telnet.c:248]: This is in wrong place. It is not telnet shell's responsibility to set something like this. For non-offloading case, the remote value is set by `NET_CONN_CB(tcp_syn_rcvd)` in net_context.c when the connection is established.

**Review by jukkar — CHANGES_REQUESTED** [review]

File: subsys/shell/shell_telnet.c (hunk 2 above)
Comment (bwasim) [reply subsys/shell/shell_telnet.c:248]: Yes, this change was somewhat "iffy" to me also.. But I did it here instead of the offloading driver because it felt somewhat "generic".. 

I agree that it makes more sense for the offloading driver to fill out this info.. Will update..

**Review by jukkar — APPROVED** [review]

**Review by loicpoulain — APPROVED** [review]
LGTM, but should it be fixed for other wifi drivers?

**Comment by bwasim** [comment]
> LGTM, but should it be fixed for other wifi drivers?

Seems that the "winc1500" driver needs similar updates, but I will be hesitant to do them myself as I have no means of testing that driver..

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@bwasim if this is fixing a bug, then it could be merged in v2.3.0. You just need to raise an associated issue.

**Comment by bwasim** [comment]
> @bwasim if this is fixing a bug, then it could be merged in v2.3.0. You just need to raise an associated issue.

@erwango, Created https://github.com/zephyrproject-rtos/zephyr/issues/25621
