### PR TITLE
drivers: can: mcux: flexcan: move to per-instance message buffer configuration

### LINKED ISSUE #92798: can: can_mcux_flexcan.c allows a mailbox overrun resulting in an imprecise data bus fault
### Describe the bug

I'm on commit hash: 

can_mcux_flexcan.c lacks proper bounds checking to ensure that send calls don't overrun outside of the area allocated by the flexcan peripheral for message buffers.

On line 737 of can_mcux_flexcan.c inside of mcux_flexcan_send, there is this section of code:
```
for (alloc = 0; alloc < MCUX_FLEXCAN_MAX_TX; alloc++) {
	if (!atomic_test_and_set_bit(data->tx_allocs, alloc)) {
		break;
	}
}

data->tx_cbs[alloc].function = callback;
data->tx_cbs[alloc].arg = user_data;
xfer.mbIdx = ALLOC_IDX_TO_TXMB_IDX(alloc);
```

As you can see, the driver simply iterates from 0 to `MCUX_FLEXCAN_MAX_TX`. `MCUX_FLEXCAN_MAX_TX` is set by the following:
```
#define MCUX_FLEXCAN_MAX_TX (MCUX_FLEXCAN_MAX_MB - MCUX_FLEXCAN_MAX_RX)
```
```
#define MCUX_FLEXCAN_MAX_MB FSL_FEATURE_FLEXCAN_HAS_MESSAGE_BUFFER_MAX_NUMBERn(0)
```
```
#define FSL_FEATURE_FLEXCAN_HAS_MESSAGE_BUFFER_MAX_NUMBERn(x) (64)
```
```
#define MCUX_FLEXCAN_MAX_RX (CONFIG_CAN_MAX_FILTER + RX_START_IDX)
```

However, if the peripheral is configured to use 64 byte message buffers, a maximum of 64 buffers is wrong.

From the datasheet, the max message buffer would be 13:

Image

Additionally, even if this max were set correctly, it doesn't seem great to just assume we will have an open buffer. In the case of no open buffer, this code just assumes the last one as the buffer to use. Really, this code should error out if it can't find an open buffer.

Regardless, `alloc` ends up being set incorrectly and eventually triggers a data bus error within the `FLEXCAN_SetFDTxMbConfig` call when it tries to access memory outside of the message buffer space.

In my case, this is always when it hits mailbox 14. It's probably unlikely to hit this if your CAN bus is operating normally as you won't reach the higher mailbox numbers. However, when the CAN peripheral is in an error state, the mailboxes just stack up until you overflow.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Enable CAN FD on the can_mcux_flexcan.c driver, put the CAN bus into an error state so that mailboxes are not being cleared (not strictly necessary, but makes it easier to hit this case), send messages until mailboxes overflow.

Edit: I'm not sure the error state is actually a part of this or would actually work. I think I'm overflowing just through normal operation.

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

Commit: 0285cf4235cec506e0c7d4e1f9e63d2de5fca783
Device: Custom IMXRT1064 board

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by william-tang914**
This change refactors the FlexCAN driver to use per-instance message buffer configuration instead of global Kconfig options. The driver now calculates message buffer allocation at compile time based on device tree properties for each FlexCAN instance.
    
Key changes:
- Remove global CAN_MAX_MB Kconfig option and associated range constraint
- Add max_mb, rx_mb, and tx_mb fields to mcux_flexcan_config structure
- Move callback arrays and atomic allocation bitmaps from static global arrays to per-instance static arrays generated by macros
- Update data structure to use pointers to per-instance arrays instead of fixed-size embedded arrays
- Add compile-time validation to ensure sufficient message buffers are available for required RX filters
    
This approach allows different FlexCAN instances to have different message buffer configurations based on their hardware capabilities and device tree settings, improving memory efficiency and flexibility. The change maintains backward compatibility while enabling better resource utilization across different SoC variants.
    
Fixes #92798

### CODE REVIEW

File: drivers/can/can_mcux_flexcan.c [hunk 1]
```diff
@@ -1432,20 +1425,54 @@ static DEVICE_API(can, mcux_flexcan_fd_driver_api) = {
...
 									\
 	static void mcux_flexcan_irq_config_##id(const struct device *dev); \
 	static void mcux_flexcan_irq_enable_##id(void); \
 	static void mcux_flexcan_irq_disable_##id(void); \
 									\
+	static struct mcux_flexcan_rx_callback flexcan_rx_cbs_##id	\
+			[FLEXCAN_INST_RX_MB(id)] = {0};			\
+									\
+	static struct mcux_flexcan_tx_callback flexcan_tx_cbs_##id	\
+			[FLEXCAN_INST_TX_MB(id)] = {0};			\
```
Comment (zejiang0jason) [inline drivers/can/can_mcux_flexcan.c:1512]: just query, do we need to consider the case that `FLEXCAN_INST_RX_MB(id)` or `FLEXCAN_INST_TX_MB(id)` is 0?

Comment (william-tang914) [reply drivers/can/can_mcux_flexcan.c:1512]: In previous, Kconfig symbol CAN_MAX_FILTER is confined to be greater than 0, but there was no constraint that MCUX_FLEXCAN_MAX_TX not be 0.
If MCUX_FLEXCAN_MAX_TX is 0, compiler will report following warning 
```
zephyrproject/zephyr/drivers/can/can_mcux_flexcan.c:1041:32: warning: array subscript 'alloc' is outside the bounds of an interior zero-length array 'struct mcux_flexcan_tx_callback[0]' [-Wzero-length-bounds]
 1041 |         function = data->tx_cbs[alloc].function;
```
For safety, I think it would be better to confine `FLEXCAN_INST_TX_MB(id)` and `FLEXCAN_INST_RX_MB(id)` greater than 0.

**Review by zejiang0jason — DISMISSED** [review]

File: boards/nxp/mr_canhubk3/doc/index.rst [hunk 2]
```diff
@@ -143,12 +143,9 @@ flexcan5         | PTC11  | PTC11_CAN0_RX  P22/P23
    and support maximum 32 message buffers for concurrent active instances with 8 bytes
    payload. We need to pay attention to configuration options:
 
-   1. :kconfig:option:`CONFIG_CAN_MAX_MB` must be less or equal than the
+   1. :kconfig:option:`CONFIG_CAN_MAX_FILTER` must be less or equal than the
```
Comment (henrikbrixandersen) [inline boards/nxp/mr_canhubk3/doc/index.rst]: `CONFIG_CAN_MAX_FILTER` no longer exists.

File: dts/bindings/can/nxp,flexcan.yaml [hunk 3]
```diff
@@ -39,3 +40,8 @@ properties:
     type: int
     required: true
     description: CAN engine clock source
+
+  nxp,max-mb:
```
Comment (henrikbrixandersen) [inline dts/bindings/can/nxp,flexcan.yaml]: There's no need to prefix this with a vendor prefix ("nxp") as the binding is specific to that vendor.

I suggest naming this property `number-of-mb` to match the IP options listed on https://www.nxp.com/products/nxp-product-information/ip-block-licensing/flexcan-controller:FLEXCAN-CONTROLLER - and since it conveys its purpose better (the IP instance has a fixed number of MBs, which is what we are trying to describe here).

File: dts/bindings/can/nxp,flexcan.yaml [hunk 4]
```diff
@@ -39,3 +40,8 @@ properties:
...
+    type: int
+    required: true
+    description: Maximum number of 8-byte payload message buffers FlexCAN instance supported
```
Comment (henrikbrixandersen) [inline dts/bindings/can/nxp,flexcan.yaml]: Please adjust the description accordingly.

File: dts/bindings/can/nxp,flexcan-fd.yaml [hunk 5]
```diff
@@ -27,3 +29,9 @@ compatible: "nxp,flexcan-fd"
 
 include: ["nxp,flexcan.yaml", "can-fd-controller.yaml", "pinctrl-device.yaml",
           "nxp,rdc-policy.yaml"]
+
+properties:
+  nxp,max-mb-fd:
+    type: int
+    required: true
+    description: Maximum number of 64-byte payload message buffers FlexCAN FD instance supported
```
Comment (henrikbrixandersen) [inline dts/bindings/can/nxp,flexcan-fd.yaml]: Same applies here.

File: drivers/can/Kconfig.mcux [hunk 6]
```diff
@@ -28,27 +28,9 @@ config CAN_MCUX_FLEXCAN_WAIT_TIMEOUT
...
-	default 16
-	depends on SOC_SERIES_S32K3 || SOC_SERIES_S32K1 || SOC_SERIES_S32ZE
-	range 1 96 if SOC_SERIES_S32K3
-	range 1 32 if SOC_SERIES_S32K1 && !SOC_S32K142W && !SOC_S32K144W
-	range 1 64 if SOC_S32K142W || SOC_S32K144W
-	range 1 128 if SOC_SERIES_S32ZE
-	help
-	  Defines maximum number of message buffers for concurrent active instances.
-
 config CAN_MAX_FILTER
```
Comment (henrikbrixandersen) [inline drivers/can/Kconfig.mcux]: This needs rebasing.

File: drivers/can/can_mcux_flexcan.c [hunk 7]
```diff
@@ -1478,20 +1425,56 @@ static DEVICE_API(can, mcux_flexcan_fd_driver_api) = {
...
+	static ATOMIC_DEFINE(flexcan_tx_allocs_##id, FLEXCAN_INST_TX_MB(id));	\
+									\
 	static const struct mcux_flexcan_config mcux_flexcan_config_##id = { \
 		DEVICE_MMIO_NAMED_ROM_INIT(flexcan_mmio, DT_DRV_INST(id)),	\
 		.common = CAN_DT_DRIVER_CONFIG_INST_GET(id, 0, FLEXCAN_MAX_BITRATE(id)), \
 		.clock_dev = DEVICE_DT_GET(DT_INST_CLOCKS_CTLR(id)),	\
 		.clock_subsys = (clock_control_subsys_t)		\
 			DT_INST_CLOCKS_CELL(id, name),			\
 		.clk_source = DT_INST_PROP(id, clk_source),		\
+		.max_mb = FLEXCAN_INST_MAX_MB(id),			\
```
Comment (henrikbrixandersen) [inline drivers/can/can_mcux_flexcan.c]: Please reflect the updated DT naming in the C code as well.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]

File: dts/bindings/can/nxp,flexcan.yaml (hunk 3 above)
Comment (william-tang914) [reply dts/bindings/can/nxp,flexcan.yaml]: Thank you for the suggestion. I didn’t even know such a webpage existed.

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by william-tang914** [comment]
I reproduced original issue https://github.com/zephyrproject-rtos/zephyr/issues/92798 by connect only one node to CAN bus. Now code code will be blocked by TX semaphore if there is no TX MB. So I think original issue shall be fixed.

https://github.com/nxp-upstream/zephyr/blob/8936a0bbcf3b6bad2d1ca8d102c068bad4f56642/drivers/can/can_mcux_flexcan.c#L747-L749

**Review by manuargue — APPROVED** [review]
