### PR TITLE
net: socket: packet: Fix memory leak

### LINKED ISSUE #34462: samples: net: sockets: packet: reception stops working after a while
**Describe the bug**
When running `samples/net/sockets/packet` the reception stops working after about 14 packets were received.

**To Reproduce**
1. `west build -b native_posix_64 zephyr/samples/net/sockets/packet`
2. On one terminal, run `sudo ./net-setup.sh` from the `net-tools` repo.
3. On the first terminal, type `west build -t run`.
4. Start sending packets to `zeth` interface (I used ping).

**Expected behavior**
All the packets are received correctly, and the print log `net_pkt_sock_sample.recv_packet_socket: Received` is printed for every packet.

**Logs and console output**
```
UART_0 connected to pseudotty: /dev/pts/4
WARNING: Using a test - not safe - entropy source
*** Booting Zephyr OS build zephyr-v2.5.0-2383-gf59cba331553  ***
[00:00:00.000,000] <inf> net_pkt_sock_sample: Packet socket sample is running
[00:00:00.000,000] <inf> net_pkt_sock_sample: Waiting for packets ...
[00:00:00.060,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 130 bytes
[00:00:00.960,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 130 bytes
[00:00:05.010,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:10.020,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:15.030,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:20.040,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:25.050,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:25.620,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 213 bytes
[00:00:26.640,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 213 bytes
[00:00:27.660,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 213 bytes
[00:00:28.680,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 213 bytes
[00:00:30.060,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:35.070,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:40.080,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:45.090,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:50.100,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:00:55.110,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:00.120,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:05.130,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:10.140,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:15.150,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:17.520,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 70 bytes
[00:01:20.160,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:25.170,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:30.180,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:32.220,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 42 bytes
[00:01:33.300,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 42 bytes
[00:01:34.320,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 42 bytes
[00:01:35.190,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:35.340,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 42 bytes
[00:01:36.360,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 42 bytes
[00:01:37.380,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 42 bytes
[00:01:38.400,000] <dbg> net_pkt_sock_sample.recv_packet_socket: Received 42 bytes
[00:01:39.530,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:40.200,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:40.550,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:41.570,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:42.590,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:43.610,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:45.210,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:50.220,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:53.270,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:54.290,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:55.230,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:01:55.310,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:56.330,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:57.350,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:01:58.370,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:02:00.240,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:05.250,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:10.260,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:15.270,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:20.280,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:25.290,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:25.730,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:02:26.750,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:02:27.770,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:02:28.790,000] <wrn> net_conn: pkt cloning failed, pkt 0x5645dbd534a0 dropped
[00:02:30.300,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:35.310,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:40.320,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:45.330,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:50.340,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:02:55.350,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:03:00.360,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:03:05.370,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:03:10.380,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:03:15.390,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:03:20.400,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:03:25.410,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:03:30.420,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
[00:03:35.430,000] <dbg> net_pkt_sock_sample.send_packet_socket: Sent 100 bytes
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr SDK 0.11.4
 - Commit SHA: `f59cba331553be094c23f1fb2839e76c403f6bfc` (19.4.2021)

### PR DESCRIPTION
**Pull request by jukkar**
The conn_raw_input() in connection.c will clone the incoming
packet so that it is possible to receive socket data in
multiple packet sockets. This is all fine except that if the
socket is never calling recv(), then the cloned net_pkt is never
processed and we will have a memory leak.

What this all means in practice, is that we should call recv()
to every packet socket in order to flush the socket for any
incoming data even if the socket is just sending data.

Fixes #34462

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

File: subsys/net/ip/net_context.c [hunk 1]
```diff
@@ -1581,6 +1581,8 @@ static int context_sendto(struct net_context *context,
 			}
 		}
 
+		net_context_set_state(context, NET_CONTEXT_CONNECTED);
```
Comment (mniestroj) [inline subsys/net/ip/net_context.c:1584]: Why do we need to set NET_CONTEXT_CONNECTED in sendto()? So far this state was only set in TCP and in offloaded network drivers (probably also in case of TCP). I have no experience with AF_PACKET, but it doesn't sound right to set this state in sendto(). At least we don't do this in case of UDP, which is also packet/datagram based and supports sendto().

File: subsys/net/ip/net_context.c [hunk 2]
```diff
@@ -2043,6 +2045,8 @@ static int recv_raw(struct net_context *context,
 		return ret;
 	}
 
+	net_context_set_state(context, NET_CONTEXT_LISTENING);
```
Comment (mniestroj) [inline subsys/net/ip/net_context.c:2048]: Does it mean that all data before first `recv()` call will be dropped? If yes and we assume a case that someone wants to:
1) create a AF_PACKET socket
2) send request
3) receive reply

then we there is race condition here...

**Review by mniestroj — COMMENTED** [review]
I have search through packet(7) and raw(7) man pages, as I was never using those before. I haven't found any logic about which socket (if multiple were created) should be able to receive data. Adding a logic that socket will be receiving data only after first recv() doesn't seem to be described/documented. As it is undefined (not documented), then current implementation of samples/net/sockets/packet/src/packet.c is also undefined (which #34462 was filed as a result). I think that this sample implementation should be reworked to use single socket to send and receive. But then, why should we receive on this socket data that we have just sent? Just wondering if this is a valid application use case and if the same can be implemented on Linux.

But still, I am no expert with AF_PACKET and stuff.

File: subsys/net/ip/net_context.c (hunk 2 above)
Comment (jukkar) [reply subsys/net/ip/net_context.c:2048]: I realized after sending this last night that there needs to be some rework in this part. I will revisit this in next version.

File: subsys/net/ip/net_context.c (hunk 1 above)
Comment (jukkar) [reply subsys/net/ip/net_context.c:1584]: > Why do we need to set NET_CONTEXT_CONNECTED in sendto()?

I will rework this part, I used the connected state just to make it different from listening state.

**Comment by jukkar** [comment]
> I think that this sample implementation should be reworked to use single socket to send and receive.

The original problem was that if there was both AF_PACKET socket and normal UDP recv socket open in the system, the received data was only given to AF_PACKET socket. This is not good as both sockets should receive the data in this case. This issue was fixed in #30934

That fix lead to memory leak in packet socket sample as the received data was cloned to both sockets that are opened in the packet socket sample. Because the packet socket sample application was not reading the sending socket (why would it), the system was slowly running out of RX buffers. The fix is not to give received data to a socket that is only sending. The sample application is quite artificial but should still work just fine as nothing really prevents developer to use the socket API like this. It is actually good that the sample app caught this issue.
I will need to rework the checks a bit in next version, to avoid any race conditions.

**Comment by mniestroj** [comment]
>The original problem was that if there was both AF_PACKET socket and normal UDP recv socket open in the system, the received data was only given to AF_PACKET socket. This is not good as both sockets should receive the data in this case.

Thanks for context. Is it specified somewhere in man pages of Linux socket or recv APIs, that all listening sockets should receive data? So far my feeling was that data should be received by only single socket at a time.

>Because the packet socket sample application was not reading the sending socket (why would it), the system was slowly running out of RX buffers. The fix is not to give received data to a socket that is only sending.

So the question is how to make send-only socket. I didn't found information about that myself. My initial thought was to use bind() for that, similar as we do it for UDP sockets in https://github.com/zephyrproject-rtos/zephyr/blob/38126f90c932d6618d14cc550c05f6c5a42d37a7/subsys/net/lib/sockets/sockets.c#L386-L400.

> The sample application is quite artificial but should still work just fine as nothing really prevents developer to use the socket API like this.

If all created AF_PACKET sockets are receiving by default, which is what I understand from Linux man pages, then application should be able to receive data on both sockets. This would be also in line with "This is not good as both sockets should receive the data in this case." that you have written above about AF_PACKET and UDP sockets. The fact that application does not call recv() on one of the socket and this results in using all the network packets, sounds like a desirable thing to do from network stack perspective.

Maybe calling recv() periodically to drain all waiting packets on a "sending" socket would be the way to "fix"? I mean we need a mechanism to say "do not receive any packets on this socket" and I think that this should be explicit, not implicit to the first call of recv().

**Comment by jukkar** [comment]
> Is it specified somewhere in man pages of Linux socket or recv APIs, that all listening sockets should receive data? So far my feeling was that data should be received by only single socket at a time.

I have not see that but I think it is a common sense that if there is a socket listener, any data sent to it is received.

> My initial thought was to use bind() for that, similar as we do it for UDP sockets in

bind() can be called for sending socket too

> Maybe calling recv() periodically to drain all waiting packets on a "sending" socket would be the way to "fix"?

I actually did it like this first but then realized that if application is only meant to send stuff, then it is not expected to call recv().

**Comment by jukkar** [comment]
> > Maybe calling recv() periodically to drain all waiting packets on a "sending" socket would be the way to "fix"?
> 
> I actually did it like this first but then realized that if application is only meant to send stuff, then it is not expected to call recv().

After debugging this more, I realized that we actually install receive callback when doing a bind. So if a bind is called for a socket, then it can always receive data. This means that we cannot actually check the net_context state value like I had in the patches.
To fix this memory leak, the only option seems to be to also read the sending socket in the application as it might get data too.

**Comment by jukkar** [comment]
Reworked the patch and made the packet socket sample to read the sending socket so that we do not leak any received data there.

File: samples/net/sockets/packet/src/packet.c [hunk 3]
```diff
@@ -186,6 +190,12 @@ static int send_packet_socket(struct packet_data *packet)
 			}
 		}
 
+		/* If we have received any data, flush it here in order to
+		 * not to leak memory in IP stack.
+		 */
+		(void)recv(packet->send_sock, recv_buffer, sizeof(recv_buffer),
+			   0);
```
Comment (mniestroj) [inline samples/net/sockets/packet/src/packet.c:197]: `MSG_DONTWAIT` could be passed instead of using `fcntl`, so this patch/code would be shorter. The more important thing is that `MSG_DONTWAIT`  would affect only `recv()` operation and keep `send()` blocking, as previously. So choosing `fcntl` vs `MSG_DONTWAIT` depends on desired behavior.

Comment (jukkar) [reply samples/net/sockets/packet/src/packet.c:197]: > `MSG_DONTWAIT` could be passed instead of using `fcntl`

Sure, good point.

**Comment by jukkar** [comment]
Updated according to comments.

File: samples/net/sockets/packet/src/packet.c [hunk 4]
```diff
@@ -186,6 +187,12 @@ static int send_packet_socket(struct packet_data *packet)
 			}
 		}
 
+		/* If we have received any data, flush it here in order to
+		 * not to leak memory in IP stack.
+		 */
+		(void)recv(packet->send_sock, recv_buffer, sizeof(recv_buffer),
+			   MSG_DONTWAIT);
+
```
Comment (mniestroj) [inline samples/net/sockets/packet/src/packet.c:195]: Maybe it would be better to even recv() in a loop? In theory we might miss some packet (for some reason it would stuck longer in networking stack) and in the next run it would be good to drain as long as we get valid packets:
```
	do {
		ret = recv(packet->send_sock, recv_buffer, sizeof(recv_buffer),
			   MSG_DONTWAIT);
	while (ret == -EAGAIN);
```

Comment (jukkar) [reply samples/net/sockets/packet/src/packet.c:195]: Sure, that is good idea.

**Review by mniestroj — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
