### PR TITLE
storage: flash_map: Fix checking unsigned for negative value

### LINKED ISSUE #28171: [Coverity CID :214224] Unsigned compared against 0 in subsys/storage/flash_map/flash_map.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/27e1fd69f987d3082229b3368a87d59ffdcab5a4/subsys/storage/flash_map/flash_map.c#L285

Category: Control flow issues
Function: `flash_area_check_int_sha256`
Component: Other
CID: [214224](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=214224)

Details:

```
279         const struct device *dev;
280         int to_read;
281         int pos;
282         int rc;
283    
284         if (!fa || !fac || !fac->match || !fac->rbuf ||
>>>     CID 214224:  Control flow issues  (NO_EFFECT)
>>>     This less-than-zero comparison of an unsigned value is never true. "fac->off < 0U".
285             fac->clen <= 0 || fac->off < 0 || fac->rblen <= 0) {
286             return -EINVAL;
287         }
288    
289         if (!is_in_flash_area_bounds(fa, fac->off, fac->clen)) {
290             return -EINVAL;
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by de-nordic**
The unsigned size_t type variables have been checked for having
negative values.

Fixes #28171, Coverity-CID: 214224

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Review by nandojve — APPROVED** [review]

**Review by pabigot — APPROVED** [review]

File: subsys/storage/flash_map/flash_map.c [hunk 1]
```diff
@@ -281,8 +281,8 @@ int flash_area_check_int_sha256(const struct flash_area *fa,
 	int pos;
 	int rc;
 
-	if (!fa || !fac || !fac->match || !fac->rbuf ||
-	    fac->clen <= 0 || fac->off < 0 || fac->rblen <= 0) {
+	if (fa == NULL || fac == NULL || fac->match == NULL ||
+	    fac->rbuf == NULL || fac->clen == 0 || fac->rblen == 0) {
```
Comment (ioannisg) [inline subsys/storage/flash_map/flash_map.c:285]: check on fac->off is missing, why?

Comment (nashif) [reply subsys/storage/flash_map/flash_map.c:285]: maybe it is too offensive? :-D

Comment (ioannisg) [reply subsys/storage/flash_map/flash_map.c:285]: Still, I think @de-nordic needs to address the question :)

Comment (pabigot) [reply subsys/storage/flash_map/flash_map.c:285]: (Hah!) And the problem this PR is addressing is that `off` is an unsigned type, so it can never be negative.

Comment (ioannisg) [reply subsys/storage/flash_map/flash_map.c:285]: OK thanks for clarifying this @pabigot . This was not intuitive, since other similar checks in this line have been reworked from inequality checks (<= 0) to equality (==) so I was thinking this should be the same and was just overlooked (possibly because it was too offensive :) )

Comment (de-nordic) [reply subsys/storage/flash_map/flash_map.c:285]: @ioannisg off is very positive when negative.

Comment (nandojve) [reply subsys/storage/flash_map/flash_map.c:285]: Hi folks, It was not intentional flash_area_check -> offset be offensive.

Comment (ioannisg) [reply subsys/storage/flash_map/flash_map.c:285]: Maybe this can be refactored, then :)

Comment (de-nordic) [reply subsys/storage/flash_map/flash_map.c:285]: Maybe leave it, it is funny :), it is one of these things that give you smile when you scan the code :)

**Review by nvlsianpu — APPROVED** [review]
