### PR TITLE
Bluetooth: Controller: Add Kconfig for minimal time reservation 

### LINKED ISSUE #49465: Bluetooth: Controller: Periodic adv. sync. degraded performance on latest main branch
**Describe the bug**
In the below table it can be seen that current main branch of Zephyr is not working as we expect. We expect the performance to be as with nRF Connect 2.0 or **_better_**.
This is tested with https://github.com/zephyrproject-rtos/zephyr/pull/49429 code, which is a small addition to the main branch as of today.
15 Tags nRF Connect 2.0             |  15 Tags Zephyr main
:-------------------------:|:-------------------------:
ncs_2-0-15-tags             |  zephyr-main-15-tags
20 Tags nRF Connect 2.0             |  20 Tags Zephyr main
ncs_2-0-20-tags             |  zephyr-main-20-tags

One difference I can see in the logs are that for Zephyr main branch I get many prints as below.
That is sync_term callback but the le address is invalid (garbage). 
```
PER_ADV_SYNC[4]: [DEVICE]: 00:D9:AC:00:00:00 (public-id) sync terminated reason: 62
[00:00:17.917,205] <err> u_df_scan: Got sync_term from none queued tag!
```

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? - Zephyr SDK and NRF52833
 - Is this a regression? - Bisect is in progress...

**To Reproduce**
Build below application based on the `direction_finding_connectionless_rx` sample (the application does not enable CTE sampling by default but can still reproduce the issue).
[aoa_receiver_multiple_configureable.zip](https://github.com/zephyrproject-rtos/zephyr/files/9416562/aoa_receiver_multiple_configureable.zip)

There are some options in the top of the main.c file, default is using periodic adv. list. which is also from where the images above are taken using.

NOTE if you build for other commits than https://github.com/zephyrproject-rtos/zephyr/pull/49429 the line `CONFIG_BT_CTLR_SYNC_PERIODIC_SKIP_ON_SCAN_AUX=y` needs to be commented out in prj.conf

Have about 10 tags sending periodic advertisements (I used about 50ms interval and about 30 bytes per. adv. data payload, this is probably not needed) for example use `direction_finding_connectionless_tx` sample, the `periodic_adv` should also work, but I have not tried.

**Expected behavior**
Equal behaviour or better in Zephyr main branch compared to Zephyr version used in nRF Connect 2.0

**Impact**
Degraded performance when tracking many tags in an application

**Logs and console output**
[ncs_2-0-20-tags.log](https://github.com/zephyrproject-rtos/zephyr/files/9416248/ncs_2-0-log-20-tags.log)
[ncs-2-0-15-tags.log](https://github.com/zephyrproject-rtos/zephyr/files/9416249/ncs-2-0-15-tags.log)
[zephyr-main-15-tags.log](https://github.com/zephyrproject-rtos/zephyr/files/9416250/zephyr-main-15-tags.log)
[zephyr-main-20-tags.log](https://github.com/zephyrproject-rtos/zephyr/files/9416251/zephyr-main-20-tags.log)

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: Used the code as in https://github.com/zephyrproject-rtos/zephyr/pull/49429

### PR DESCRIPTION
**Pull request by cvinayak**
Add Kconfig to use minimal time reservation for auxiliary
and sync PDU reception. A peer device could be scheduling
multiple advertising sets in a short duration with small
PDUs hence using the minimal time reservation would avoid
skipping closely scheduled reception of multiple auxiliary
PDUs.

Add implementation in Periodic Sync LLL abort to use near
fair scheduling to ensure overlapping multiple Periodic
Sync set each get to use the radio and not lead to Sync
Loss.

The implementation is used when overlap in radio event
happens in unreserved time space of the event. An abort
count is maintain in each Periodic Sync instance and is
used to decide whether the current event or the next
event is to be aborted when they overlap.

Fixes #49465.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by stephanosio** [comment]
Rebased to fix CI failure

File: subsys/bluetooth/controller/ll_sw/lll_sync.h [hunk 1]
```diff
@@ -32,6 +32,14 @@ struct lll_sync {
 	uint8_t sca:3;
 #endif /* CONFIG_BT_CTLR_SYNC_ISO */
 
+	/* Counter used by LLL abort of event when in unreserved time space to
+	 * provide near fair scheduling of overlapping multiple Periodic
+	 * Sync sets.
+	 */
+#if defined(CONFIG_BT_CTLR_SCAN_AUX_SYNC_RESERVE_MIN)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/lll_sync.h:39]:
```suggestion
#if defined(CONFIG_BT_CTLR_SCAN_AUX_SYNC_RESERVE_MIN)
	/* Counter used by LLL abort of event when in unreserved time space to
	 * provide near fair scheduling of overlapping multiple Periodic
	 * Sync sets.
	 */
```

Kinda makes more sense to have the comment next to the field

File: subsys/bluetooth/controller/ll_sw/lll_sync.h [hunk 2]
```diff
@@ -66,3 +74,4 @@ void lll_sync_prepare(void *param);
 enum sync_status lll_sync_cte_is_allowed(uint8_t cte_type_mask, uint8_t filter_policy,
 					 uint8_t rx_cte_time, uint8_t rx_cte_type);
 extern uint16_t ull_sync_lll_handle_get(struct lll_sync *lll);
+extern struct lll_sync *ull_sync_lll_is_valid_get(struct lll_sync *lll);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/lll_sync.h:77]: The name makes sense, but the `is_valid` part in the middle threw me off at first. 

Would
```suggestion
extern struct lll_sync *ull_sync_lll_get_valid(struct lll_sync *lll);
```

Make sense?

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c [hunk 3]
```diff
@@ -467,21 +467,60 @@ static int is_abort_cb(void *next, void *curr, lll_prepare_cb_t *resume_cb)
...
+		if (lll_sync_curr->abort_count < lll_sync_next->abort_count) {
+			if (lll_sync_curr->abort_count < UINT8_MAX) {
+				lll_sync_curr->abort_count++;
 			}
+
+			/* Abort current event as next event has higher abort
+			 * count.
+			 */
+			return -ECANCELED;
+		}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:512]: Do we ever risk both `lll_sync_curr->abort_count` and `lll_sync_next->abort_count` to become `UINT8_MAX`? In which case, neither of them can increment, and the events will never get aborted? 
```
lll_sync_curr->abort_count < lll_sync_next->abort_count

File: subsys/bluetooth/controller/ll_sw/lll_sync.h (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/lll_sync.h]: done

File: subsys/bluetooth/controller/ll_sw/lll_sync.h (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/lll_sync.h:77]: `_is_valid` is widely used in Zephyr compare to `_get_valid`, as the return here is a reference hence I have used `_is_valid_get`. Keep the code as-is.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync.c:512]: By implementation a max of 250 periodic sync are supported  (limited by ticker's use of uint8_t for ids, and 5 other reserved tickers).

the `abort_count` (max at 249) will not reach UINT8_MAX.

Say both does reach UINT8_MAX, then `return 0` is returned here:
https://github.com/zephyrproject-rtos/zephyr/pull/49579/commits/3259230635fe357755a8ee53eae61d48fdf1fd8b#diff-3b747a1cde6e2938850148bd938b27771b7a9cc2be571792ebf3d5ddfbeb5918R526-R529

current event (that occurs first in timeline) will always continue and next event will always be aborted (eventually leading to sync loss). As UINT8_MAX will not be reached, there is no issue.

**Review by Thalley — DISMISSED** [review]

**Review by Thalley — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
