### PR TITLE
drivers: display: sdl: Ensure draw is performed from init thread

### LINKED ISSUE #71410: SDL display driver doesn't support API calls from a thread other than main
**Describe the bug**

Trying to call display functions (ex `display_write`) from a thread other than `main` does not seem to work.

**To Reproduce**
1. change `samples/drivers/display/src/main.c` so that the contents of main() is effectively executed in a different thread
2. build and run on native_sim --> screen is black

**Expected behavior**

SDL driver should work in a multithreaded environment, just like other display drivers.

**Impact**

can't run custom GUI code that requires a dedicated thread using native sim 

**Environment (please complete the following information):**

Linux  x86_64, 3.6.99 f419ea7990998ee13476d5c206a6bdb83a4a0567

### PR DESCRIPTION
**Pull request by faxe1008**
Add a thread to the SDL display driver to ensure that init and renderer calls are performed from the same thread.

Fixes #71410.

Ping @Finomnis @PetervdPerk-NXP

### CODE REVIEW

File: drivers/display/display_sdl.c [hunk 1]
```diff
@@ -49,32 +77,42 @@ static inline uint32_t mono_pixel_order(uint32_t order)
...
-#endif /* SDL_DISPLAY_DEFAULT_PIXEL_FORMAT */
-		;
+static void sdl_task_thread(void *p1, void *p2, void *p3)
+{
+	const struct device *dev = p1;
+	struct sdl_display_data *disp_data = dev->data;
+	const struct sdl_display_config *config = dev->config;
+	struct sdl_display_task task;
+	bool use_accelerator =
+		COND_CODE_0(CONFIG_SDL_DISPLAY_USE_HARDWARE_ACCELERATOR, (false), (true));
```
Comment (pdgendt) [inline drivers/display/display_sdl.c:115]:
```suggestion
	bool use_accelerator = IS_ENABLED(CONFIG_SDL_DISPLAY_USE_HARDWARE_ACCELERATOR);
```

File: drivers/display/display_sdl.c [hunk 2]
```diff
@@ -49,32 +77,42 @@ static inline uint32_t mono_pixel_order(uint32_t order)
...
-	IF_DISABLED(CONFIG_SDL_DISPLAY_USE_HARDWARE_ACCELERATOR, (use_accelerator = false));
+	K_SPINLOCK(&disp_data->lock) {
+		switch (task->op) {
+		case SDL_WRITE:
+			sdl_display_write_bottom(task->write.desc->height, task->write.desc->width,
+						task->write.x, task->write.y, disp_data->renderer,
+						disp_data->mutex, disp_data->texture,
+						disp_data->background_texture, disp_data->buf,
+						disp_data->display_on,
+						task->write.desc->frame_incomplete);
```
Comment (pdgendt) [inline drivers/display/display_sdl.c:92]: Nit indentation
```suggestion
			sdl_display_write_bottom(task->write.desc->height, task->write.desc->width,
						 task->write.x, task->write.y, disp_data->renderer,
						 disp_data->mutex, disp_data->texture,
						 disp_data->background_texture, disp_data->buf,
						 disp_data->display_on,
						 task->write.desc->frame_incomplete);
```

File: drivers/display/display_sdl.c [hunk 3]
```diff
@@ -49,32 +77,42 @@ static inline uint32_t mono_pixel_order(uint32_t order)
...
+			break;
+		case SDL_BLANKING_OFF:
+			sdl_display_blanking_off_bottom(disp_data->renderer, disp_data->texture,
+						disp_data->background_texture);
```
Comment (pdgendt) [inline drivers/display/display_sdl.c:96]:
```suggestion
			sdl_display_blanking_off_bottom(disp_data->renderer, disp_data->texture,
							disp_data->background_texture);
```

File: drivers/display/display_sdl.c (hunk 1 above)
Comment (faxe1008) [reply drivers/display/display_sdl.c]: Done.

File: drivers/display/display_sdl.c (hunk 2 above)
Comment (faxe1008) [reply drivers/display/display_sdl.c]: Done.

File: drivers/display/display_sdl.c (hunk 3 above)
Comment (faxe1008) [reply drivers/display/display_sdl.c]: Done.

**Review by pdgendt — DISMISSED** [review]

File: drivers/display/display_sdl.c [hunk 4]
```diff
@@ -509,34 +597,57 @@ static int sdl_display_clear(const struct device *dev)
...
+	struct sdl_display_task task = {
+		.op = SDL_BLANKING_OFF,
+	};
 
 	LOG_DBG("Turning display blacking off");
 
-	disp_data->display_on = true;
+	K_SPINLOCK(&disp_data->lock) {
+		disp_data->display_on = true;
+	}
```
Comment (aescolar) [inline drivers/display/display_sdl.c:619]:
```suggestion
	disp_data->display_on = true;
```
In native_sim a SW thread cannot be interrupted while executing simple instructions like this.
Anyhow, setting a variable to 1/0 is atomic in any platform I know of :)
So this is just overhead.
Same in `sdl_display_blanking_on()`

File: drivers/display/display_sdl.c [hunk 5]
```diff
@@ -49,32 +77,42 @@ static inline uint32_t mono_pixel_order(uint32_t order)
...
-static int sdl_display_init(const struct device *dev)
+static void exec_sdl_task(const struct device *dev, const struct sdl_display_task *task)
 {
-	const struct sdl_display_config *config = dev->config;
 	struct sdl_display_data *disp_data = dev->data;
-	bool use_accelerator = true;
-	LOG_DBG("Initializing display driver");
 
-	IF_DISABLED(CONFIG_SDL_DISPLAY_USE_HARDWARE_ACCELERATOR, (use_accelerator = false));
+	K_SPINLOCK(&disp_data->lock) {
```
Comment (aescolar) [inline drivers/display/display_sdl.c:84]: Minor:
* native_sim is not SMP capable (and by design it won't be) => this is just a `irq_lock()`
* In native_sim we purposely do not allow asynchronous mechanisms to generate interrupts into Zephyr, which means no other Zephyr thread will call into exec_sdl_task() while this is executing even with interrupts unlocked.

=> this lock is not needed, but the harm of having is just more complex code and a bit of overhead. I'm  not rejecting the PR due to this.

This also applies to all other `K_SPINLOCK`s added in this PR

File: drivers/display/display_sdl.c [hunk 6]
```diff
@@ -91,11 +129,48 @@ static int sdl_display_init(const struct device *dev)
 
 	if (rc != 0) {
 		LOG_ERR("Failed to create SDL display");
-		return -EIO;
+		return;
```
Comment (aescolar) [inline drivers/display/display_sdl.c:132]: Honest question: Do you expect anything sensible will happen from here on? or should this just `nsi_print_error_and_exit()` here?

File: drivers/display/display_sdl.c [hunk 7]
```diff
@@ -509,34 +597,57 @@ static int sdl_display_clear(const struct device *dev)
 		return -EINVAL;
 	}
 	LOG_DBG("size: %zu, bgcolor: %hhu", size, bgcolor);
-	memset(disp_data->buf, bgcolor, size);
+
+	K_SPINLOCK(&disp_data->lock) {
```
Comment (aescolar) [inline drivers/display/display_sdl.c:601]: sidenote: calls to memset are atomic in native_sim

**Review by VynDragon — DISMISSED** [review]
Tested functionaility, works. Looks like it makes sense and i see no issue with code.

File: drivers/display/display_sdl.c [hunk 8]
```diff
@@ -273,26 +356,30 @@ static int sdl_display_write(const struct device *dev, const uint16_t x,
...
+		} else if (disp_data->current_pixel_format == PIXEL_FORMAT_L_8) {
+			sdl_display_write_l8(disp_data->buf, desc, buf);
+		}
 	}
 
-	sdl_display_write_bottom(desc->height, desc->width, x, y, disp_data->renderer,
-				 disp_data->mutex, disp_data->texture,
-				 disp_data->background_texture, disp_data->buf,
-				 disp_data->display_on, desc->frame_incomplete);
+	if (k_current_get() == &disp_data->sdl_thread) {
```
Comment (aescolar) [inline drivers/display/display_sdl.c:377]: Honest question: Given that it seems this sdl_thread is a thread meant only to call the bottom , how do you expect this to happen?
(same comment for sdl_display_blanking_*)

**Review by aescolar — DISMISSED** [review]
Thank you very much @faxe1008

File: drivers/display/Kconfig.sdl [hunk 9]
```diff
@@ -80,4 +80,16 @@ config SDL_DISPLAY_TRANSPARENCY_GRID_CELL_COLOR_2
 	help
 	  The color of the even cells in the transparency grid.
 
+config SDL_DISPLAY_THREAD_STACK_SIZE
```
[the remark this answers is not in the document]
Comment (faxe1008) [reply drivers/display/Kconfig.sdl]: Done.

File: drivers/display/display_sdl.c [hunk 10]
```diff
@@ -38,6 +59,13 @@ struct sdl_display_data {
 	enum display_pixel_format current_pixel_format;
 	uint8_t *buf;
 	uint8_t *read_buf;
+
+	struct k_spinlock lock;
+	struct k_thread sdl_thread;
+
+	K_KERNEL_STACK_MEMBER(sdl_thread_stack, CONFIG_SDL_DISPLAY_THREAD_STACK_SIZE);
```
[the remark this answers is not in the document]
Comment (faxe1008) [reply drivers/display/display_sdl.c]: Done.

File: drivers/display/Kconfig.sdl [hunk 11]
```diff
@@ -80,4 +80,16 @@ config SDL_DISPLAY_TRANSPARENCY_GRID_CELL_COLOR_2
...
+	int "Stack size for SDL display thread"
+	default 1024
+	help
+	  The size of the thread stack used for dispatching drawing operations.
+
+config SDL_DISPLAY_THREAD_PRIORITY
+	int "SDL display thread priority"
+	default 0
+	help
+	  The thread priority of the drawing thread.
```
[the remark this answers is not in the document]
Comment (faxe1008) [reply drivers/display/Kconfig.sdl]: Done.

File: drivers/display/display_sdl.c (hunk 4 above)
Comment (faxe1008) [reply drivers/display/display_sdl.c:619]: Done.

File: drivers/display/display_sdl.c (hunk 7 above)
Comment (faxe1008) [reply drivers/display/display_sdl.c:601]: Done.

**Comment by PetervdPerk-NXP** [comment]
Screenshot 2025-03-31 133142
Running my code with both `SDL_DISPLAY_USE_HARDWARE_ACCELERATOR=n` and `SDL_DISPLAY_USE_HARDWARE_ACCELERATOR=y` gives me this checkerboard.

The code seems to be running and accepting inputs based on looking on the console output.

File: drivers/display/display_sdl.c (hunk 6 above)
Comment (faxe1008) [reply drivers/display/display_sdl.c:132]: Was not sure if the `nsi_` function are to be used within the driver, will change.

Comment (faxe1008) [reply drivers/display/display_sdl.c:133]: Done.

File: drivers/display/display_sdl.c (hunk 5 above)
Comment (faxe1008) [reply drivers/display/display_sdl.c]: Good point, I removed the spinlock.

File: drivers/display/display_sdl.c (hunk 8 above)
Comment (faxe1008) [reply drivers/display/display_sdl.c:372]: Very good question. Currently the handling of input events happens in another thread:
https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/native/common/sdl/sdl_events.c#L20

So when adding logging to see where write, SDL event handling and input callback are invoked I get this:
```
sdl_display_write  THREAD ID: 0x61cb80
sdl_handle_events  THREAD ID: 0x510980
sdl_input_callback THREAD ID: 0x510980
```

I feel like this needs to also happen within the sdl thread that I am adding here, since there is also manipulation of the renderer going on within `sdl_handle_window_event` (https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/native/common/sdl/sdl_events_bottom.c#L16) . Eventually this means that `sdl_input_callback ` callback will happen in the same thread as `sdl_display_write` if one selects `CONFIG_INPUT_MODE_SYNCHRONOUS`. Currently since the msgq can only hold one item this would be an issue, I think. Maybe @Finomnis can chime in here since this concern was originally raised by him.

File: drivers/display/display_sdl.c [hunk 12]
```diff
@@ -273,26 +356,30 @@ static int sdl_display_write(const struct device *dev, const uint16_t x,
...
 
-	sdl_display_write_bottom(desc->height, desc->width, x, y, disp_data->renderer,
-				 disp_data->mutex, disp_data->texture,
-				 disp_data->background_texture, disp_data->buf,
-				 disp_data->display_on, desc->frame_incomplete);
+	if (k_current_get() == &disp_data->sdl_thread) {
+		exec_sdl_task(dev, &task);
+	} else {
+		k_msgq_put(disp_data->task_msgq, &task, K_FOREVER);
+		k_sem_take(&disp_data->task_sem, K_FOREVER);
```
[the remark this answers is not in the document]
Comment (aescolar) [reply drivers/display/display_sdl.c:376]: Would it not be enough to have a mutex that ensures only 1 job is placed in the queue at a time?
Meaning, you could invert how you use the semaphore, and instead of initializing it to 0, initialize it to 1, attempt to grab it before calling k_msgq_put() , and have (like right now) sdl_task_thread release it.

[the remark this answers is not in the document]
Comment (faxe1008) [reply drivers/display/display_sdl.c:376]: @aescolar do I understand correctly that you suggest the mutex to prevent this scenario:

```
A calls write
A calls msgq_put
B calls write
B calls msgq_put
A task item is processed, semaphore is given
B calls sem take -> B assumes task is finishes but actually only A is processed, B goes out of scope and corrupts the var on stack
```

So the mutex "ensures" that insertion into the msgq and giving of the semaphore happens in unison?

[the remark this answers is not in the document]
Comment (aescolar) [reply drivers/display/display_sdl.c:376]: That was the scenario in my mind, yes

[the remark this answers is not in the document]
Comment (faxe1008) [reply drivers/display/display_sdl.c:378]: Applied your suggestion :^)

File: drivers/display/display_sdl.c [hunk 13]
```diff
@@ -517,26 +603,44 @@ static int sdl_display_clear(const struct device *dev)
...
 	disp_data->display_on = true;
 
-	sdl_display_blanking_off_bottom(disp_data->renderer, disp_data->texture,
-					disp_data->background_texture);
+	if (k_current_get() == &disp_data->sdl_thread) {
+		exec_sdl_task(dev, &task);
+	} else {
+		k_mutex_lock(&disp_data->task_mutex, K_FOREVER);
+		k_sem_take(&disp_data->task_sem, K_FOREVER);
+		k_msgq_put(disp_data->task_msgq, &task, K_FOREVER);
```
[the remark this answers is not in the document]
Comment (aescolar) [reply drivers/display/display_sdl.c:618]: Yes. Sorry @faxe1008, my bad.
With the new mutex as is now, the "old" semaphore should stay as it was, to ensure the task is done with the data before returning and corrupting task data in the stack.
A question, about the mutex, do we need to protect also the display_data (dev->data) modification ?

[the remark this answers is not in the document]
Comment (faxe1008) [reply drivers/display/display_sdl.c]: Reverted that change. Yeah the mutex needs to protect that as well.

**Review by pdgendt — DISMISSED** [review]

**Comment by aescolar** [comment]
> Yeah the mutex needs to protect that as well.

@faxe1008  I look forward to that last change, so I approve :)

File: drivers/display/Kconfig.sdl [hunk 14]
```diff
@@ -80,4 +80,10 @@ config SDL_DISPLAY_TRANSPARENCY_GRID_CELL_COLOR_2
 	help
 	  The color of the even cells in the transparency grid.
 
+config SDL_DISPLAY_THREAD_PRIORITY
+	int "SDL display thread priority"
+	default 0
```
Comment (Finomnis) [inline drivers/display/Kconfig.sdl:85]: I'd put the default priority way lower, I'd almost argue I'd put it to the lowest priority possible. Otherwise low priority threads calling draw functions would cause a priority inversion.

Is there a way to use priority inheritance to bump this priority dynamically when higher priority threads are waiting for this?

Comment (aescolar) [reply drivers/display/Kconfig.sdl:85]: @Finomnis note this is only for native_sim, where you are not constrained like in an embedded device. 
But more importantly note that this thread would only get unblocked if the thread that wants to draw has just been scheduled. So even though this thread has high priority, it is only running as a result of that requesting thread running.

Comment (Finomnis) [reply drivers/display/Kconfig.sdl:85]: Ok :)

Comment (faxe1008) [reply drivers/display/Kconfig.sdl]: Changed the default priority to `NUM_PREEMPT_PRIORITIES`.

File: drivers/display/display_sdl.c [hunk 15]
```diff
@@ -288,11 +371,16 @@ static int sdl_display_write(const struct device *dev, const uint16_t x,
 	} else if (disp_data->current_pixel_format == PIXEL_FORMAT_L_8) {
 		sdl_display_write_l8(disp_data->buf, desc, buf);
 	}
+	k_mutex_unlock(&disp_data->task_mutex);
```
Comment (aescolar) [inline drivers/display/display_sdl.c:374]: Shouldn't this mutex remain locked all the way until the end of the function to also protect the read in the direct call to `exec_sdl_task()`?

**Review by aescolar — APPROVED** [review]

**Review by JarmouniA — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Comment by pdgendt** [comment]
@faxe1008 note for the future: do not add `Fixes #....` to the commit message body as per [the guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#adding-links).
