### PR TITLE
net: sockets: Add SOCK_RAW support for AF_INET/AF_INET6 sockets

### LINKED ISSUE #86827: IPPROTO_RAW wrongly used with AF_PACKET
**Describe the bug**
Zephyr specifies the use of `IPPROTO_RAW` with `AF_PACKET` sockets. This is not in line how Linux specifies this. `IPPROTO_RAW´ is specified as sub type for IP frames. [[1]](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml#protocol-numbers-1) Used as EtherType this specifies an old length field type. [[2]](https://www.iana.org/assignments/ieee-802-numbers/ieee-802-numbers.xhtml#ieee-802-numbers-1)

**To Reproduce**
Use AF_PACKET socket.

**Expected behavior**
`IPPROTO_RAW` is not treated as a protocol with `AF_PACKET` sockets, but with AF_INET/AF_INET6 through a SOCK_RAW socket.

**Impact**
Incompatibility (and maintaining this). overhead when using AF_PACKET.

**Logs and console output**
None.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: df5318479b914d320f52870c6dfd0420779fc5c0

**Additional context**
None.

### PR DESCRIPTION
**Pull request by rlubos**
Introduce support for raw IP sockets. 

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/86827

### CODE REVIEW

**Comment by jukkar** [comment]
Just wondering should we have a page in network documentation or doxygen comments in the code that describes how the various options are working (I am referring to the table in the issue of the PR). We mostly follow Linux but there are some deviations so perhaps these should be mentioned somewhere.

**Comment by rlubos** [comment]
> Just wondering should we have a page in network documentation or doxygen comments in the code that describes how the various options are working (I am referring to the table in the issue of the PR). We mostly follow Linux but there are some deviations so perhaps these should be mentioned somewhere.

That's a good idea, we have a dedicated documentation page for sockets, perhaps it'd make most sense to add a table in there summarizing what socket types we do support.

File: subsys/net/ip/connection.c [hunk 1]
```diff
@@ -635,6 +635,37 @@ static enum net_verdict conn_raw_socket(struct net_pkt *pkt,
...
+
+	net_pkt_cursor_backup(pkt, &cur);
+	net_pkt_cursor_init(pkt);
+
+	NET_DBG("[%p] raw IP match found cb %p ud %p", conn, conn->cb,
+		conn->user_data);
+
+	raw_pkt = net_pkt_clone(pkt, CLONE_TIMEOUT);
+	if (!raw_pkt) {
+		return;
```
Comment (jukkar) [inline subsys/net/ip/connection.c:652]: Cursor will be incorrect now. Perhaps have here goto to the end of the function as the cursor is restored there.

File: subsys/net/ip/connection.c [hunk 2]
```diff
@@ -757,6 +797,10 @@ enum net_verdict net_conn_input(struct net_pkt *pkt,
 				if (proto != ETH_P_ALL && proto != IPPROTO_RAW) {
 					continue; /* wrong protocol */
 				}
+			} else if (IS_ENABLED(CONFIG_NET_SOCKETS_INET_RAW) && raw_ip_pkt) {
+				if (conn->proto != 0) {
```
Comment (jukkar) [inline subsys/net/ip/connection.c:801]: Should we do the check like this
```
if (conn->proto != IPPROTO_IP) {
```
to make it clear what we are checking against (value 0 is a bit vague).

File: subsys/net/ip/connection.c [hunk 3]
```diff
@@ -793,6 +837,15 @@ enum net_verdict net_conn_input(struct net_pkt *pkt,
 
 				continue; /* packet was consumed */
 			}
+		} else if (IS_ENABLED(CONFIG_NET_SOCKETS_INET_RAW) && raw_ip_pkt) {
```
Comment (jukkar) [inline subsys/net/ip/connection.c:840]: Note that few lines above, the code is still checking `IPPROTO_RAW` for packet socket, we need to remove/change those checks from packet socket

File: subsys/net/ip/net_context.c [hunk 4]
```diff
@@ -466,6 +466,9 @@ static int net_context_check(sa_family_t family, enum net_sock_type type,
 			}
 			break;
 		case SOCK_RAW:
+			if (!IS_ENABLED(CONFIG_NET_SOCKETS_INET_RAW)) {
+				NET_DBG("RAW IP sockets disabled.");
+			}
```
Comment (jukkar) [inline subsys/net/ip/net_context.c:471]: Should we return
`return -EPROTONOSUPPORT;`
here?

File: subsys/net/ip/net_context.c [hunk 5]
```diff
@@ -2164,6 +2167,57 @@ static int context_setup_udp_packet(struct net_context *context,
...
+						      struct net_ipv4_hdr);
+		struct net_ipv4_hdr *ipv4_hdr;
+		uint8_t hdr_len;
+
+		net_pkt_cursor_init(pkt);
+		net_pkt_set_overwrite(pkt, true);
+
+		ipv4_hdr = (struct net_ipv4_hdr *)net_pkt_get_data(pkt, &ipv4_access);
+		if (!ipv4_hdr) {
+			return -ENOBUFS;
```
Comment (jukkar) [inline subsys/net/ip/net_context.c:2194]: Should we restore the cursor?

File: subsys/net/ip/net_context.c [hunk 6]
```diff
@@ -2164,6 +2167,57 @@ static int context_setup_udp_packet(struct net_context *context,
...
+		if (net_if_need_calc_tx_checksum(net_pkt_iface(pkt),
+						 NET_IF_CHECKSUM_IPV4_HEADER)) {
+			ipv4_hdr->chksum = 0;
+			ipv4_hdr->chksum = net_calc_chksum_ipv4(pkt);
+			net_pkt_set_data(pkt, &ipv4_access);
+		}
+
+		net_pkt_set_ll_proto_type(pkt, ETH_P_IP);
+	} else {
+		net_pkt_set_ip_hdr_len(pkt, sizeof(struct net_ipv6_hdr));
```
Comment (jukkar) [inline subsys/net/ip/net_context.c:2214]: Should we make similar things here as what is being done for IPv4 above?

File: subsys/net/lib/sockets/sockets_inet.c [hunk 7]
```diff
@@ -664,6 +680,11 @@ ssize_t zsock_sendmsg_ctx(struct net_context *ctx, const struct msghdr *msg,
 	k_timepoint_t buf_timeout, end;
 	int status;
 
+	if (net_context_get_type(ctx) == SOCK_RAW) {
```
Comment (jukkar) [inline subsys/net/lib/sockets/sockets_inet.c:683]: Why do we prevent `sendmsg` for raw sockets?

File: subsys/net/lib/sockets/sockets_inet.c [hunk 8]
```diff
@@ -1479,6 +1503,11 @@ ssize_t zsock_recvmsg_ctx(struct net_context *ctx, struct msghdr *msg,
 	enum net_sock_type sock_type = net_context_get_type(ctx);
 	size_t i, max_len = 0;
 
+	if (net_context_get_type(ctx) == SOCK_RAW) {
```
Comment (jukkar) [inline subsys/net/lib/sockets/sockets_inet.c:1506]: Why prevent `recvmsg` for raw sockets?

**Review by jukkar — COMMENTED** [review]
Some minor comments.
I am thinking about the tests, how can we verify that we have tested all combinations? Should we have a table in the test describing what we are testing and have a dedicated test function for each "cell" in the table, WDYT?

**Comment by rlubos** [comment]
> I am thinking about the tests, how can we verify that we have tested all combinations? Should we have a table in the test describing what we are testing and have a dedicated test function for each "cell" in the table, WDYT?

I can refer to the table from the issue, and extend the test suite a bit. We'll likely duplicate some tests, but that's probably not a big deal. And now I think we should also add tests verifying that all this still works if we enable AF_PACKET support.

File: subsys/net/lib/sockets/sockets_inet.c (hunk 7 above)
Comment (rlubos) [reply subsys/net/lib/sockets/sockets_inet.c:683]: Probably no good reason now that I think of it, I can drop this restriction and add some tests for sendmsg()/recvmsg().

File: subsys/net/ip/connection.c (hunk 3 above)
Comment (rlubos) [reply subsys/net/ip/connection.c:840]: Yes, do you want me to extend this PR with `AF_PACKET/IPPROTO_RAW` removal?

**Comment by rlubos** [comment]
I have addressed the initial feedback, will work on extending the testsuite even more.

File: subsys/net/ip/connection.c (hunk 3 above)
Comment (jukkar) [reply subsys/net/ip/connection.c:841]: I think we need to remove the `IPPROTO_RAW` from `AF_PACKET`, that was actually the point of the actual issue.

**Comment by rlubos** [comment]
In last push:
* Dropped AF_PACKET/IPPROTO_RAW socket support.
* Added table in sockets documentation with the summary of what is supported, let's see how it renders

**Review by jukkar — COMMENTED** [review]
The documentation looks great. I think we need to mention in migration doc that the AF_PACKET will not accept IPPROTO_RAW as a protocol any more.

**Comment by rlubos** [comment]
Ok this should be more or less ready, changes since last week:
* Refined the table in the socket documentation so that it renders better
* Added migration guide entry about removed IPPROTO_RAW support from AF_PACKET
* Added more test cases. I've also added summary in the test suite, based on table created by @jukkar, to make sure that all AF_INET/SOCK_RAW functionalities mentioned there are covered

**Comment by rlubos** [comment]
CI fixes

**Review by jukkar — DISMISSED** [review]

**Comment by jukkar** [comment]
@pdgendt please take a look if you have time

**Comment by jukkar** [comment]
cc: @go2sh please try if it solves your issues

**Review by pdgendt — DISMISSED** [review]
Some minor comments

**Review by pdgendt — APPROVED** [review]

File: subsys/net/ip/ipv4.c [hunk 9]
```diff
@@ -383,6 +383,12 @@ enum net_verdict net_ipv4_input(struct net_pkt *pkt, bool is_loopback)
 		net_sprint_ipv4_addr(&hdr->src),
 		net_sprint_ipv4_addr(&hdr->dst));
 
+	ip.ipv4 = hdr;
+
+	if (IS_ENABLED(CONFIG_NET_SOCKETS_INET_RAW)) {
+		(void)net_conn_input(pkt, &ip, hdr->proto, NULL);
```
[the remark this answers is not in the document]
Comment (rlubos) [reply subsys/net/ip/ipv4.c]: Technically `net_conn_input()` shouldn't ever fail at that stage, but on the other hands it's probably cleaner to verify the result regardless in case this behavior changes for whatever reason in the future. I've updated this part.

File: subsys/net/ip/ipv6.c [hunk 10]
```diff
@@ -762,6 +762,12 @@ enum net_verdict net_ipv6_input(struct net_pkt *pkt, bool is_loopback)
 
 	net_pkt_set_ipv6_ext_len(pkt, ext_len);
 
+	ip.ipv6 = hdr;
+
+	if (IS_ENABLED(CONFIG_NET_SOCKETS_INET_RAW)) {
+		(void)net_conn_input(pkt, &ip, current_hdr, NULL);
```
[the remark this answers is not in the document]
Comment (rlubos) [reply subsys/net/ip/ipv6.c]: Ditto

File: subsys/net/ip/net_context.c [hunk 11]
```diff
@@ -2164,6 +2168,57 @@ static int context_setup_udp_packet(struct net_context *context,
...
+		NET_PKT_DATA_ACCESS_CONTIGUOUS_DEFINE(ipv4_access,
+						      struct net_ipv4_hdr);
+		struct net_ipv4_hdr *ipv4_hdr;
+		uint8_t hdr_len;
+
+		net_pkt_cursor_init(pkt);
+		net_pkt_set_overwrite(pkt, true);
+
+		ipv4_hdr = (struct net_ipv4_hdr *)net_pkt_get_data(pkt, &ipv4_access);
+		if (!ipv4_hdr) {
```
[the remark this answers is not in the document]
Comment (rlubos) [reply subsys/net/ip/net_context.c]: Fixed

**Review by jukkar — APPROVED** [review]
