### PR TITLE
debug: openocd: Fix building for SMP platforms

### LINKED ISSUE #18124: synchronization example fails to build for SMP platforms
Initially reported by Shippable here https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/47829/3/console while reviewing https://github.com/zephyrproject-rtos/zephyr/pull/17992.

Yet could be reproduced for any other SMP platform, for example `qemu_x86_64`:
```
# mkdir build
# cd build
# cmake -DBOARD=qemu_x86_64 ../samples/synchronization/
```
Enable OpenOCD support (`CONFIG_OPENOCD_SUPPORT=y`).

```
# make
...
[ 60%] Built target app
In file included from .../include/kernel_includes.h:16,
                 from .../include/kernel.h:17,
                 from .../kernel/include/kernel_structs.h:10,
                 from .../subsys/debug/openocd.c:7:
.../subsys/debug/openocd.c:39:35: error: 'struct z_kernel' has no member named 'current'
  [OPENOCD_OFFSET_K_CURR_THREAD] = offsetof(struct z_kernel, current),
                                   ^~~~~~~~
.../subsys/debug/openocd.c:66:2: warning: #warning Please define OPENOCD_OFFSET_T_STACK_PTR for this architecture [-Wcpp]
 #warning Please define OPENOCD_OFFSET_T_STACK_PTR for this architecture
  ^~~~~~~

```

### PR DESCRIPTION
**Pull request by abrodkin**
struct k_thread *current is only defined for !SMP platforms
leading to the following build-time failure:

| openocd.c:39:35: error: 'struct z_kernel' has no member named 'current'
|  [OPENOCD_OFFSET_K_CURR_THREAD] = offsetof(struct z_kernel, current),
                                   ^~~~~~~~

Disable calculation of meaningless offset then.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/18124.

### CODE REVIEW

File: subsys/debug/openocd.c [hunk 1]
```diff
@@ -36,7 +36,9 @@ __attribute__((used, section(".openocd_dbg")))
 size_t _kernel_openocd_offsets[] = {
 	/* Version 0 starts */
 	[OPENOCD_OFFSET_VERSION] = 1,
+#ifndef CONFIG_SMP
```
Comment (galak) [inline subsys/debug/openocd.c]: is this going to cause issues w/openocd and the assumed layout of this data?  Wondering if setting the value to 0 is better?

Comment (ruuddw) [reply subsys/debug/openocd.c]: 0 is probably better, though might break things as well (don't know if openocd/gdb zephyr awareness relies on this).
Openocd Zephyr-SMP support might require more. Maybe instead of working around this, do not allow/use combination of SMP and openocd zephyr awareness for now?

**Comment by abrodkin** [comment]
@galak @ruuddw so maybe something like this until we really make sure OpenOCD works with Zephyr-aware on SMP systems?
```
diff --git a/subsys/debug/Kconfig b/subsys/debug/Kconfig
index a55d0f3350..a5dff0ad4f 100644
--- a/subsys/debug/Kconfig
+++ b/subsys/debug/Kconfig
@@ -223,6 +223,7 @@ config EXCEPTION_STACK_TRACE

 config OPENOCD_SUPPORT
        bool "OpenOCD support [EXPERIMENTAL]"
+       depends on !SMP
        select THREAD_MONITOR
        select THREAD_NAME
        help
```

File: subsys/debug/openocd.c (hunk 1 above)
Comment (MaureenHelm) [reply subsys/debug/openocd.c]: `OPENOCD_UNIMPLEMENTED` would be better than zero, but I also like @abrodkin's idea to handle this in KConfig.

**Comment by ioannisg** [comment]
@nashif @galak @ruuddw could you finalize reviewing this bug-fix of a a high priority bug?

**Comment by ioannisg** [comment]
Moving to next release since the review was not finalized for v.2.0.0

**Comment by galak** [comment]
Any updates on this?

**Comment by abrodkin** [comment]
@EvgeniiDidin could you please take a look at this one since you anyways deal with OpenOCD/GDB thingy these days?

**Comment by galak** [comment]
@abrodkin, @EvgeniiDidin  any update on this?

**Comment by EvgeniiDidin** [comment]
Hi, 

I tested SMP Zephyr smp/pi example with these changes on HSDK(4 core) board using OpenOCD/ gdb. It is possible to load and start the application on all cores, also I was able to get callee registers from stack. But after stopping execution "continue" command failed with next message:
```
(gdb) c
Cannot execute this command without a live selected thread.
```
I guess it is related to the lack of  current_thread{id} values in OpenOCD, which come from "current" struct. 

If  incomplete smp aware support is permissible for Zephyr/OpenOCD,  this commit is fine. Otherwise we should disable  simultaneous usage of CONFIG_SMP and CONFIG_OPENOCD options.

**Comment by galak** [comment]
@abrodkin, @EvgeniiDidin any update on this?

**Comment by abrodkin** [comment]
@galak I think the most recent comment of Eugeniy (https://github.com/zephyrproject-rtos/zephyr/pull/18125#issuecomment-559171331) still valid. We either declare SMP mode doesn't support additional OpenOCD-related visibility options or ignore pointer to the "current thread" implemented in this commit. I now lean towards making `CONFIG_OPENOCD` incompatible with `CONFIG_SMP` as at least it won't introduce any funky behavior.

**Comment by ruuddw** [comment]
Let's prevent openocd and SMP / multiple CPUs in kconfig.
SMP/multi-core is simply not yet supported. See also PR #23503 : adds a #error in openocd.c.

**Review by nashif — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
LGTM but I need @andrewboie, @MaureenHelm, @galak or @nashif  to approve
