### PR TITLE
Bluetooth: controller: Fix ticker previous slot value

### LINKED ISSUE #19515: Bluetooth: Controller: assertion failed
The problem is related with master device that has connected peripheral. 
If one starts to write to master device flash e.g. do DFU procedure and in the meantime: disconects periperhal, after that connects it again, then assertion in callback: ticker_success_assert will fail. 

Source of the problem is schedule of two ticker starts to the same ticker node (in thic case it is ticker 0). First one is scheduled by work_in_time_slice (soc_flash_nrf.c) and second one by event_common_prepare(ctrl.c) sourced in isr_rx_scan(ctrl.c). Eventually ticker_job_list_insert when iterates second time on ticker 0 below condition is true:
```
if (((ticker->req - ticker->ack) & 0xff) != 0U) {
	ticker_job_op_cb(user_op, TICKER_STATUS_FAILURE);
	continue;
}
```

It seems that isr_rx_scan triggered sequence compets with flash write request for ticker 0. According to what I have found, the ticker start requested by flash operation (even it is immediate) it does not happen. The time delay between flash write request for ticker 0 and control request is changeable and varies between 12-40ms). It seems to me that there is noting happening in between requests. 

**To Reproduce**
To reproduce the issue, you may use nrf_desktop application and nrf script hid_configurator.
1. Build the application for master and peripheral with enabled built type ZDebugMCUBoot.
2. Connect peripheral to master.
3. Start DFU on master device by call to hid_configurator:
''' sudo python3 configurator_cli.py dongle dfu PATH_TO_BUILD_DIR/zephyr/app_update.bin'''
4. Disconnect the peripheral during DFU.
5. Connect peripheral during DFU.

**Expected behavior**
DFU should progress and peripheral shoudl re-connect to master. Master should start forwarding data to PC it is attached to.

**Impact**
For nrf_desktop it is annoying - must be very careful to not re-connect the peripheral during DFU procedure (even. put peripheral in deep sleep and wake it up).

**Console output**
'''
[00805915] <err> bt_ctlr_llsw_ctrl: assert: 'status == 0' failed
[00805915] <err> os: r0/a1:  0x00000003  r1/a2:  0x20008a60  r2/a3:  0x00000000
[00805916] <err> os: r3/a4:  0x0000000b r12/ip:  0x00000000 r14/lr:  0x000272eb
[00805916] <err> os:  xpsr:  0x61000029
[00805917] <err> os: Faulting instruction address (r15/pc): 0x00040366
[00805917] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops
[00805918] <err> os: Current thread: 0x2000319c (unknown)
[05022033] <err> os: Halting system
'''

**Environment (please complete the following information):**
- NCS commit used: e877d0158c50a7b9a801c3ca68ebe16e7462209f (west updated from NCS).
 - Zephyr commit used: 1c3a001f62e6c51693b67e4f7ee7f66111d31801 (at the moment it was not possible to verify it with latest release of Zephyr).

### PR DESCRIPTION
**Pull request by cvinayak**
Fix ticker previous slot value with elapsed ticks value from
the time stopped ticker has expired. When a ticker is
stopped, if it was in its reserved time space, then the
currently occupied slot (was set to 0) should be the amount
of time that has elapsed in the expired and stopped ticker's
reserved time space and beyond until the stop.
This is required to ensure that any other new ticker does
not get scheduled over the stopped ticker's reserved time
space.

Fixes #19515.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@ppryga fyi

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 1]
```diff
@@ -1109,8 +1109,12 @@ static inline void ticker_job_node_manage(struct ticker_instance *instance,
 		ticker->req = ticker->ack;
 
 		if (instance->ticker_id_slot_previous == user_op->id) {
+			u32_t ticks_now = cntr_cnt_get();
+
 			instance->ticker_id_slot_previous = TICKER_NULL;
-			instance->ticks_slot_previous = 0U;
+			instance->ticks_slot_previous = ticks_elapsed +
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ticker/ticker.c]: should this be ```MIN(ticker->ticks_slot, (ticks_elapsed + ticker_ticks_diff_get(ticks_now, instance->ticks_current)))``` ?

Comment (cvinayak) [reply subsys/bluetooth/controller/ticker/ticker.c]: @mtpr-ot do review when possible, this is a critical bug fix.

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ticker/ticker.c]: > should this be `MIN(ticker->ticks_slot, (ticks_elapsed + ticker_ticks_diff_get(ticks_now, instance->ticks_current)))` ?

I think doing the MIN is right.

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ticker/ticker.c]: > @mtpr-ot do review when possible, this is a critical bug fix.

It looks good. I am testing here, and when the MIN is added and tests passed, I will approve.

**Review by mtpr-ot — CHANGES_REQUESTED** [review]
Looks good, but do prefer the MIN(...) version

File: subsys/bluetooth/controller/ticker/ticker.c (hunk 1 above)
Comment (mtpr-ot) [reply subsys/bluetooth/controller/ticker/ticker.c]: > > @mtpr-ot do review when possible, this is a critical bug fix.
> 
> It looks good. I am testing here, and when the MIN is added and tests passed, I will approve.

Testing passes here.

**Review by mtpr-ot — APPROVED** [review]
Approved
