### PR TITLE
gpio/it8xxx2: do not set flag if register does not exist

### LINKED ISSUE #54366: tests: pin_get_config failed on it8xxx2_evb, again
**Describe the bug**
Test case `tests/drivers/gpio/gpio_basic_api` failed in daily test. 
When setting a GPIO to high, and then getting the GPIO result, the result is not as expected.
The test fails, noticing the discrepancy between the set flags and the gotten flags. However, on this board, the discrepancy is the expected and correct result.

The `it8xxx2_evb` board uses some flags as read-only flags, informing the receiver and user about e.g. the voltage used for the pin. Thus, on this board and possibly some others, the assertion that set flags on a GPIO port will be the same as gotten flags on the same port is incorrect.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
   - `it8xxx2_evb`, also called `IT81302 MECC`
 - What have you tried to diagnose or workaround this issue?
   - To diagnose it, I have locally modified the test in question to verify what flags were set and gotten.
     - Set flags: `1010 0000 0000 0000 0000`
     - Got flags: `1010 0001 0000 0000 0000`
   - I have not tried to workaround this issue, as it's an issue in the test.
 - Is this a regression? 
   - Yes. 
   - The test has worked between commits [99ab3fb](https://github.com/zephyrproject-rtos/zephyr/commit/99ab3fba5454b8ef6bbb6ff6ca7f48d1173691f6) and [b2962d2](https://github.com/zephyrproject-rtos/zephyr/pull/52156/commits/b2962d241fc814c0a05d3d76bb71f3119f087c2b)
   - The [b2962d2](https://github.com/zephyrproject-rtos/zephyr/pull/52156/commits/b2962d241fc814c0a05d3d76bb71f3119f087c2b) has changed how the test in question works. The operation of this test should be returned to the previous state, keeping in mind that the mask originally used has been deprecated.
   - The conversation about solving this issue can be found in [Issue 47921](https://github.com/zephyrproject-rtos/zephyr/issues/47921), which had found this problem originally, and the [PR 47923](https://github.com/zephyrproject-rtos/zephyr/pull/47923), which fixed it.

**To Reproduce**
1. Prepare the `it8xxx2_evb` for the test, looping `OUT 0` to `IN 1` (`gpio_loopback` fixture).
2. Run `<path/to/twister/>twister  -p it8xxx2_evb --device-testing --west-flash="<path/to/loader/>itetool/loader.sh" --device-serial=<tty_port_connected_to_the_board> -T <path/to/tests/>tests/drivers/gpio/gpio_basic_api/ --fixture=gpio_loopback`

**Expected behavior**
The test in question (`gpio_port.test_gpio_port`) passes.

**Impact**
  - Annoyance
  - Loss of daily test result clarity
  - Possible further impacts if, during further Zephyr development, there is a mistaken expectation of reading the same flags as one has set on every board.

**Logs and console output**
```
***** delaying boot 1ms (per build configuration) *****
*** Booting Zephyr OS build v3.3.0-rc1-42-ge55fd536c821 (delayed boot 1ms) ***
Running TESTSUITE gpio_port
===================================================================
START - test_gpio_port
Validate device gpio@f01601
Check gpio@f01601 output 0 connected to input 1
OUT 0 to IN 1 linkage works
- bits_physical
- pin_physical
- check_raw_output_levels
- check_logic_output_levels
- check_input_levels
- bits_logical
- check_pulls
==== NON-STANDARD LOGGING START ====
RC:  0
GET: 659456
SET: 655360
==== NON-STANDARD LOGGING ENDED ====
Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:652: pin_get_config: (flags_get not equal to flags_set)
flags are different
FAIL - test_gpio_port in 0.043 seconds
===================================================================
TESTSUITE gpio_port failed.
Running TESTSUITE gpio_port_cb_mgmt
===================================================================
START - test_gpio_callback_add_remove
callback_2 triggered: 1
callback_1 triggered: 1
callback_2 triggered: 1
PASS - test_gpio_callback_add_remove in 3.615 seconds
===================================================================
START - test_gpio_callback_enable_disable
callback_2 triggered: 1
callback_1 triggered: 1
callback_2 triggered: 1
callback_1 triggered: 1
PASS - test_gpio_callback_enable_disable in 3.617 seconds
===================================================================
START - test_gpio_callback_self_remove
callback_remove_self triggered: 1
callback_1 triggered: 1
callback_1 triggered: 1
PASS - test_gpio_callback_self_remove in 2.514 seconds
===================================================================
TESTSUITE gpio_port_cb_mgmt succeeded
Running TESTSUITE gpio_port_cb_vari
===================================================================
START - test_gpio_callback_variants
callback triggered: 1
OUT init a0001, IN cfg 3400000, cnt 1
callback triggered: 1
OUT init 60000, IN cfg 5400000, cnt 1
callback triggered: 1
OUT init 60000, IN cfg 5c00000, cnt 1
callback triggered: 1
OUT init a0001, IN cfg 3c00000, cnt 1
E: Level trigger mode not supported
Mode 4400000 not supported
E: Level trigger mode not supported
Mode 2400000 not supported
E: Level trigger mode not supported
Mode 4c00000 not supported
E: Level trigger mode not supported
Mode 2c00000 not supported
callback triggered: 1
callback triggered: 2
OUT init a0001, IN cfg 7400000, cnt 2
PASS - test_gpio_callback_variants in 5.564 seconds
===================================================================
TESTSUITE gpio_port_cb_vari succeeded
------ TESTSUITE SUMMARY START ------
SUITE FAIL -   0.00% [gpio_port]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.043 seconds
- FAIL - [gpio_port.test_gpio_port] duration = 0.043 seconds
SUITE PASS - 100.00% [gpio_port_cb_mgmt]: pass = 3, fail = 0, skip = 0, total = 3 duration = 9.746 seconds
- PASS - [gpio_port_cb_mgmt.test_gpio_callback_add_remove] duration = 3.615 seconds
- PASS - [gpio_port_cb_mgmt.test_gpio_callback_enable_disable] duration = 3.617 seconds
- PASS - [gpio_port_cb_mgmt.test_gpio_callback_self_remove] duration = 2.514 seconds
SUITE PASS - 100.00% [gpio_port_cb_vari]: pass = 1, fail = 0, skip = 0, total = 1 duration = 5.564 seconds
- PASS - [gpio_port_cb_vari.test_gpio_callback_variants] duration = 5.564 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: 1f525c7f46fdbf078374a80a1d418d9b
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 as the controller
 - Toolchain: Zephyr SDK
 - Commit SHA: [e55fd536c8](https://github.com/zephyrproject-rtos/zephyr/commit/e55fd536c821e17535d07e3bc6db9c99b57b8d54)

**Additional context**
  - `gpio_loopback` fixture is set, which means that `OUT 0` and `IN 1` `GPIO` ports are connected.

### PR DESCRIPTION
**Pull request by Dino-Li**
Since not all GPIOs support voltage selection, voltage flag is only set if voltage selection register is present.

fixes: #54366

Signed-off-by: Dino Li <Dino.Li@ite.com.tw>

### CODE REVIEW

File: drivers/gpio/gpio_ite_it8xxx2.c [hunk 1]
```diff
@@ -481,10 +481,12 @@ static int gpio_ite_get_config(const struct device *dev,
 	reg_1p8v = &IT8XXX2_GPIO_GCRX(
 			gpio_1p8v[gpio_config->index][pin].offset);
 	mask_1p8v = gpio_1p8v[gpio_config->index][pin].mask_1p8v;
```
Comment (brockus-zephyr) [inline drivers/gpio/gpio_ite_it8xxx2.c:483]: mask_1p8v is only used in the condition.  No need to assign it to a value if it is not used.  Move it to inside the new register exclusion condition.

File: drivers/gpio/gpio_ite_it8xxx2.c [hunk 2]
```diff
@@ -481,10 +481,12 @@ static int gpio_ite_get_config(const struct device *dev,
...
-	if (*reg_1p8v & mask_1p8v) {
-		flags |= IT8XXX2_GPIO_VOLTAGE_1P8;
-	} else {
-		flags |= IT8XXX2_GPIO_VOLTAGE_3P3;
+	if (reg_1p8v != &IT8XXX2_GPIO_GCRX(0)) {
```
Comment (brockus-zephyr) [inline drivers/gpio/gpio_ite_it8xxx2.c:484]: To the casual reader, it does not feel intuitively obvious why this condition is being made.  I would personally prefer to see a short comment so the meaning is clear.

**Review by brockus-zephyr — CHANGES_REQUESTED** [review]

File: drivers/gpio/gpio_ite_it8xxx2.c (hunk 1 above)
Comment (Dino-Li) [reply drivers/gpio/gpio_ite_it8xxx2.c]: Done

File: drivers/gpio/gpio_ite_it8xxx2.c (hunk 2 above)
Comment (Dino-Li) [reply drivers/gpio/gpio_ite_it8xxx2.c:487]: Done

**Review by brockus-zephyr — APPROVED** [review]

**Review by GTLin08 — APPROVED** [review]
