### PR TITLE
drivers: serial: stm32 uart driver avoid LOG_ when going to sleep

### LINKED ISSUE #54427: stm32 uart driver LOG_ msg crashes when entering sleep mode
**Describe the bug**
When going to sleep mode, the stm32 uart driver does not accept LOG msg
In uart_stm32_pm_action() when action is PM_DEVICE_ACTION_SUSPEND, the pinctrl_apply_state() might be not possible when usart pins are not defined for sleep mode, Then LOG_WRN is called but failed as system is going to sleep (console usart)

**To Reproduce**
1. west build -p -b nucleo_g474re -- -DOVERLAY_CONFIG="prj_tickless.conf"  tests/kernel/timer/timer_api
2. west flash
3. See error

**Expected behavior**
test PASSED

**Impact**
CI failure

**Logs and console output**
```
*** Booting Zephyr OS build v3.3.0-rc1-89-gfcd60cf789b1 ***
Running TESTSUITE timer_api
===================================================================
START - test_sleep_abs
E: ***** MPU FAULT *****
E:   Stacking error (context area might be not valid)
E:   Data Access Violation
E:   MMFAR Address: 0x20001478
E: r0/a1:  0x0a21fe80  r1/a2:  0x3b9ac9ff  r2/a3:  0xa30fb570
E: r3/a4:  0x2300e9d3 r12/ip:  0xfd72f7ff r14/lr:  0x46044e0e
E:  xpsr:  0x2106fa00
E: Faulting instruction address (r15/pc): 0x460d480e
E: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
E: Current thread: 0x20000330 (idle)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Toolchain  Zephyr SDK 0.15.0
 - Commit SHA  fcd60cf789b1acd1cd29dcd8db2dba86572bdbfa

**Additional context**
The MPU FAULT comes on the nucleo_g474re when the usart1 is enabled in the board DTS, but has no pin-ctrl for the sleep mode. Then when entering the sleep mode with that test case, the pins of the usart1 cannot be moved and the 
LOG_WRN is called and crashes.
Changing the LOG_WRN to _LOG_DBG_ or _LOG_INF_ does not fix the pb, when the CONFIG_UART_LOG_LEVEL_DBG=y is set.
Disabling the faulty usart or Defining its pins for sleep mode is a WA avoiding the _-ENOENT_ return code on  pinctrl_apply_state(config->pcfg, PINCTRL_STATE_SLEEP).

### PR DESCRIPTION
**Pull request by FRASTM**
When the LOG_WRN is used on stm32 uart driver it could block execution : when pin state for sleep mode is not defined by the DTS even if no error is raised, LOG_ msg is crashing when entering sleep mode.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54427

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
$ west build -p auto -b nucleo_g474re -- -DOVERLAY_CONFIG="prj_tickless.conf" tests/kernel/timer/timer_api/

```
===================================================================
TESTSUITE timer_api succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [timer_api]: pass = 15, fail = 0, skip = 0, total = 15 durs
 - PASS - [timer_api.test_sleep_abs] duration = 0.014 seconds
 - PASS - [timer_api.test_time_conversions] duration = 0.070 seconds
 - PASS - [timer_api.test_timeout_abs] duration = 0.002 seconds
 - PASS - [timer_api.test_timer_duration_period] duration = 0.326 seconds
 - PASS - [timer_api.test_timer_expirefn_null] duration = 0.326 seconds
 - PASS - [timer_api.test_timer_k_define] duration = 0.702 seconds
 - PASS - [timer_api.test_timer_period_0] duration = 0.202 seconds
 - PASS - [timer_api.test_timer_period_k_forever] duration = 0.202 seconds
 - PASS - [timer_api.test_timer_periodicity] duration = 0.252 seconds
 - PASS - [timer_api.test_timer_remaining] duration = 0.051 seconds
 - PASS - [timer_api.test_timer_restart] duration = 0.276 seconds
 - PASS - [timer_api.test_timer_status_get] duration = 0.001 seconds
 - PASS - [timer_api.test_timer_status_get_anytime] duration = 0.326 seconds
 - PASS - [timer_api.test_timer_status_sync] duration = 0.352 seconds
 - PASS - [timer_api.test_timer_user_data] duration = 0.301 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -1319,7 +1319,7 @@ static int uart_stm32_async_rx_enable(const struct device *dev,
 	}
 
 	if (data->dma_rx.enabled) {
-		LOG_WRN("RX was already enabled");
+		LOG_ERR("RX was already enabled");
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:1322]: Is LOG_ERR really required here ?
Also this change is not justified/documented

File: drivers/serial/uart_stm32.c [hunk 2]
```diff
@@ -1786,16 +1786,24 @@ static int uart_stm32_pm_action(const struct device *dev,
 		/* Stop device clock. Note: fixed clocks are not handled yet. */
 		err = clock_control_off(data->clock, (clock_control_subsys_t)&config->pclken[0]);
 		if (err != 0) {
-			LOG_ERR("Could not enable (LP)UART clock");
+			/*
+			 * Warn without console output when going to sleep,
+			 * "Could not enable (LP)UART clock"
+			 * but don't block PM suspend
+			 */
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:1793]: Not being able to clock off is an error. Logging it is justified and won't have negative side effect (an error is already returned).
I think LOG_ERR should be kept in this case.

File: drivers/serial/uart_stm32.c [hunk 3]
```diff
@@ -1786,16 +1786,24 @@ static int uart_stm32_pm_action(const struct device *dev,
...
-			/* Warn but don't block PM suspend */
-			LOG_WRN("(LP)UART pinctrl sleep state not available ");
-		} else if (err < 0) {
+		if ((err < 0) && (err != -ENOENT)) {
+			/*
+			 * If returning -ENOENT, no pins wher defined for sleep mode :
+			 * Warn without console output when going to sleep,
+			 * "(LP)UART pinctrl sleep state not available"
+			 * but don't block PM suspend.
+			 * Else return the error.
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:1805]: I agree with the change: 
Logging in -ENOENT case requires console which leads to an issue as we're in the process of falling asleep. Console may not be available and we don't want to wake up the system.

However, the comment is confusing as it doesn't describe what we're doing (no if/else is done, no "warn w/o console" is done neither).

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_stm32.c (hunk 1 above)
Comment (FRASTM) [reply drivers/serial/uart_stm32.c]: removed

**Review by dcpleung — APPROVED** [review]

**Review by erwango — APPROVED** [review]
