### PR TITLE
Bluetooth: Userchan: Parse multiple hci packets

### LINKED ISSUE #61762: Can not decode multiple hci packets on the virtual TCP controller
**Describe the bug**
After the update to add an optional external Bluetooth TCP virtual controller for the native board I found out that if multiple HCI packets are recieved on a single TCP payload only the first one is decoded and the rest are ignored.

This happens typically when multiple HCI packets are queued in a short amount of time and sent over the Bluetooth TCP virtual controller at once.

**To Reproduce**

1. Compile the sample `samples/bluetooth/direct_adv`
2. Follow instructions from [here](https://docs.zephyrproject.org/latest/connectivity/bluetooth/bluetooth-tools.html#running-on-a-virtual-controller-and-native-posix) to connect to a virtual controller,
3. As packets are lost the connection will be lost.

**Expected behavior**
That the virtual controller can connect to the Zephyr application over bluetooth when multiple hci packets are recieved
on a single tcp payload.

**Impact**
Cannot use the virtual controller functionality correctly.

**Logs and console output**
```
** Booting Zephyr OS build v3.4.99 ***
[00:00:00.000,000] <inf> fs_nvs: nvs_mount: 4 Sectors of 4096 bytes
[00:00:00.000,000] <inf> fs_nvs: nvs_mount: alloc wra: 0, fa0
[00:00:00.000,000] <inf> fs_nvs: nvs_mount: data wra: 0, 3f
[00:00:00.380,000] <wrn> bt_ecc: bt_pub_key_gen: ECC HCI commands not available
[00:00:00.380,000] <inf> bt_hci_core: bt_init: No ID address. App must call settings_load()
Bluetooth initialized
[00:00:00.380,000] <inf> bt_hci_core: bt_dev_show_info: Identity: DA:4C:10:DE:17:01 (public)
[00:00:00.380,000] <inf> bt_hci_core: bt_dev_show_info: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x00e0
[00:00:00.380,000] <inf> bt_hci_core: bt_dev_show_info: LMP: version 5.3 (0x0c) subver 0x0000
Advertising successfully started
Connected
Disconnected (reason 0x13)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Commit SHA:  https://github.com/zephyrproject-rtos/zephyr/commit/33c922a771aee12e329de1a10c6fc65b0e01ed4a

### PR DESCRIPTION
**Pull request by vChavezB**
After conducting tests with a a virtual Bluetooth controller over TCP it was noticed that some HCI packets may arrive on the same buffer if sent over a short period of time.
This update ensures the hci packets are parsed correctly in the case multiple packets are in the same recieving buffer according to how HCI packets are decoded in the Bluetooth Spec v5.2 Part E.

This should fix https://github.com/zephyrproject-rtos/zephyr/issues/61762

Open for suggestions and discussion on how to address this the best way.

### CODE REVIEW

File: drivers/bluetooth/hci/userchan.c [hunk 1]
```diff
@@ -93,6 +93,53 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+	switch (packet_type) {
+	/* Bluetooth spec 5.2 Vol 4, Part E - 5.4.1 HCI Command Packet */
+	case H4_CMD:
+		payload_size = packet_buff[3];
+		header_size = 3;
+		break;
+	/* Bluetooth spec 5.2 Vol 4, Part E - 5.4.2 ACL Data Packets */
+	case H4_ACL:
+		payload_size = packet_buff[4] << 8 | packet_buff[3];
+		header_size = 4;
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:117]:
```suggestion
		header_size = BT_HCI_ACL_HDR_SIZE;
```
or
```suggestion
		header_size = sizeof(struct bt_hci_acl_hdr);
```

File: drivers/bluetooth/hci/userchan.c [hunk 2]
```diff
@@ -93,6 +93,53 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+	uint16_t payload_size = 0;
+	uint8_t header_size = 0;
+	const uint8_t packet_type_len = 1;
+
+	switch (packet_type) {
+	/* Bluetooth spec 5.2 Vol 4, Part E - 5.4.1 HCI Command Packet */
+	case H4_CMD:
+		payload_size = packet_buff[3];
+		header_size = 3;
+		break;
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:113]: There is some information missing from when you are doing `[3]` or `[2]`. I assume that is has something to do with the header sizes? 

Suggest to use defined values, rather than magic numbers, to retrieve the payload sizes

File: drivers/bluetooth/hci/userchan.c [hunk 3]
```diff
@@ -134,27 +181,45 @@ static void rx_thread(void *p1, void *p2, void *p3)
...
+			if (!buf) {
+				LOG_DBG("Discard adv report due to insufficient buf");
+				continue;
+			}
+
+			buf_tailroom = net_buf_tailroom(buf);
+			buf_add_len = decoded_len-1;
+			if (buf_tailroom < buf_add_len) {
+				LOG_ERR("Not enough space in buffer %zu/%zu",
+						buf_add_len, buf_tailroom);
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:210]:
```suggestion
				LOG_ERR("Not enough space in buffer %zu/%zu",
					buf_add_len, buf_tailroom);
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/userchan.c (hunk 1 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c:117]: Thanks for bringing this up. Just a remark...for the HCI H4 SCO, I did not find a definition, should I add it to https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/bluetooth/hci_types.h ? 

e.g., 

```c
#define BT_HCI_SCO_HDR_SIZE 3
```

Comment (Thalley) [reply drivers/bluetooth/hci/userchan.c:117]: Yes, please add the `BT_HCI_SCO_HDR_SIZE` along side the actual header - Something similar to 
```c
struct bt_hci_acl_hdr {
	uint16_t handle;
	uint16_t len;
} __packed;
```

File: drivers/bluetooth/hci/userchan.c [hunk 4]
```diff
@@ -93,6 +100,56 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+	case H4_EVT:
+		/* Data_Total_Length */
+		payload_size = packet_buff[H4_EVT_PAYLOAD_SIZE_OFF];
+		header_size = BT_HCI_EVT_HDR_SIZE;
+		break;
+	/* Bluetooth spec 5.2 Vol 4, Part E - 5.4.5 HCI ISO Data Packets */
+	case H4_ISO:
+		/* ISO_Data_Load_Length parameter */
+		payload_size =  sys_get_le16(&packet_buff[H4_ISO_PAYLOAD_SIZE_OFF]) & 0x3FFF;
+		header_size = BT_HCI_ISO_HDR_SIZE;
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:143]: I wonder if it would make more sense to actually extract the header in each case, and use the `len` field in each header to extract the `payload_size`. That might be better than using these offsets and so on. 

So it would be something like 

```c
	case H4_ACL:
		/* Data Total Length */
		const struct bt_hci_acl_hdr *hdr = &packet_buff[sizeof(packet_type)];

		payload_size = sys_get_le16(hdr->len);
		header_size = sizeof(hdr);
		break;
```

Though it may require some endianess handling or something for this to properly work.

File: drivers/bluetooth/hci/userchan.c [hunk 5]
```diff
@@ -93,6 +100,56 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+ * @brief Decode the length of an HCI H4 packet
+ * @details Decodes packet length according to Bluetooth spec v5.2 Vol 4 Part E
+ * @param packet_type	Type of packet according to Bluetooth spec v5.2 Vol 4, Part A Table 2.1
+ * @param packet_buff	Pointer to packet buffer
+ */
+static uint16_t decode_hci_packet_length(uint8_t packet_type, const uint8_t *packet_buff)
+{
+	uint16_t payload_size = 0;
+	uint8_t header_size = 0;
+	const uint8_t packet_type_len = 1;
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:113]:
```suggestion
	const uint8_t packet_type_len = sizeof(packet_type);
```

File: drivers/bluetooth/hci/userchan.c (hunk 4 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: Yes 👍 , I was checking the source code of how the hci structs are handled and its similar to what you mention

See for example

https://github.com/zephyrproject-rtos/zephyr/blob/2d65acca3a76b968657c2e796512558e93f2ed23/drivers/bluetooth/hci/h4.c#L127C3-L127C3.

File: drivers/bluetooth/hci/userchan.c [hunk 6]
```diff
@@ -93,6 +95,61 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+		break;
+	case H4_SCO:
+		const struct bt_hci_sco_hdr *hdr = &packet_buff[sizeof(packet_type)];
+
+		/* Data_Total_Length */
+		payload_size = hdr->len;
+		header_size = BT_HCI_SCO_HDR_SIZE;
+		break;
+	case H4_EVT:
+		const struct bt_hci_evt_hdr *hdr = &packet_buff;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:133]: This doesn't seem correct. You have the packet type as the first byte and the packet-specific header comes after that. In all other cases you read `&packet_buff[1]` but here you read `&packet_buff[0]`. Actually, I don't see any reason why you need two parameters to this function. Just pass the original buffer and inside the function you can then do `uint8_t type = buf[0];`.

File: drivers/bluetooth/hci/userchan.c [hunk 7]
```diff
@@ -93,6 +95,61 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+
+		/* Parameter Total Length */
+		payload_size = hdr->param_len;
+		header_size = BT_HCI_CMD_HDR_SIZE;
+		break;
+	case H4_ACL:
+		const struct bt_hci_acl_hdr *hdr = &packet_buff[sizeof(packet_type)];
+
+		/* Data Total Length */
+		payload_size = sys_get_le16(&hdr->len);
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:122]: This generates unnecessarily complicated code. Just do `size = sys_le16_to_cpu(hdr->len);`. The structs are packed, so accessing the struct members generates automatically alignment-safe code (if needed by the CPU architecture).

File: drivers/bluetooth/hci/userchan.c [hunk 8]
```diff
@@ -93,6 +95,61 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+ * @brief Decode the length of an HCI H4 packet
+ * @details Decodes packet length according to Bluetooth spec v5.2 Vol 4 Part E
+ * @param packet_type	Type of packet according to Bluetooth spec v5.2 Vol 4, Part A Table 2.1
+ * @param packet_buff	Pointer to packet buffer
+ */
+static uint16_t decode_hci_packet_length(uint8_t packet_type, const uint8_t *packet_buff)
+{
+	uint16_t payload_size = 0;
+	uint8_t header_size = 0;
+	const uint8_t packet_type_len = sizeof(packet_type);
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:108]: This seems like an unnecessary variable (doesn't add much to readability, and the way you've named it it's even longer than`sizeof(packet_type)`.

File: drivers/bluetooth/hci/userchan.c [hunk 9]
```diff
@@ -93,6 +95,61 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+/**
+ * @brief Decode the length of an HCI H4 packet
+ * @details Decodes packet length according to Bluetooth spec v5.2 Vol 4 Part E
+ * @param packet_type	Type of packet according to Bluetooth spec v5.2 Vol 4, Part A Table 2.1
+ * @param packet_buff	Pointer to packet buffer
+ */
+static uint16_t decode_hci_packet_length(uint8_t packet_type, const uint8_t *packet_buff)
+{
+	uint16_t payload_size = 0;
+	uint8_t header_size = 0;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:107]: Call these `len` instead of `size`.

File: drivers/bluetooth/hci/userchan.c [hunk 10]
```diff
@@ -93,6 +95,61 @@ static struct net_buf *get_rx(const uint8_t *buf)
 	return NULL;
 }
 
+/**
+ * @brief Decode the length of an HCI H4 packet
+ * @details Decodes packet length according to Bluetooth spec v5.2 Vol 4 Part E
+ * @param packet_type	Type of packet according to Bluetooth spec v5.2 Vol 4, Part A Table 2.1
+ * @param packet_buff	Pointer to packet buffer
+ */
+static uint16_t decode_hci_packet_length(uint8_t packet_type, const uint8_t *packet_buff)
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:104]: I'd just call this function `packet_len()`

File: include/zephyr/bluetooth/hci_types.h [hunk 11]
```diff
@@ -37,6 +37,14 @@ extern "C" {
 #define BT_HCI_SYNC_HANDLE_INVALID 0xffff
 #define BT_HCI_PAWR_SUBEVENT_MAX 128
 
+/* Bluetooth spec 5.2 Vol 4, Part E - 5.4.3 HCI Synchronous Data Packets */
+struct bt_hci_sco_hdr {
+	uint16_t  conn_handle;
+	uint8_t  len;
+} __packed;
```
Comment (jhedberg) [inline include/zephyr/bluetooth/hci_types.h:44]: Please follow the same struct alignment style as elsewhere in the headers, so that the struct member names are aligned. That means two spaces after `uint8_t` but only one after `uint16_t`.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/userchan.c (hunk 7 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c:122]: Does the packed attribute deal with endianness ? Thats the reason I thought parts like these ones are needed in the current bluetooths stack 

https://github.com/zephyrproject-rtos/zephyr/blob/2d65acca3a76b968657c2e796512558e93f2ed23/drivers/bluetooth/hci/h4.c#L127C3-L127C3

https://github.com/zephyrproject-rtos/zephyr/blob/2d65acca3a76b968657c2e796512558e93f2ed23/drivers/bluetooth/hci/h4.c#L140C2-L140C2

File: drivers/bluetooth/hci/userchan.c (hunk 6 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c:133]: Yes, sorry mistake on my part while changing to the suggestions of the other reviewer.

File: include/zephyr/bluetooth/hci_types.h (hunk 11 above)
Comment (vChavezB) [reply include/zephyr/bluetooth/hci_types.h]: changed

File: drivers/bluetooth/hci/userchan.c (hunk 7 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: I changed the other comment reviews accordingly but this one is still is not clear to me.

Could you be more specific on your suggestion? 

>  Just do `size = sys_le16_to_cpu(hdr->len)`

I understood either:

1. Should I change the name of the variable `payload_len` to `size` ?
2. Should I obtain the size of the payload via `size = sys_le16_to_cpu(hdr->len);` before the switch case? Its a trivial change and only the edge case for the struct `bt_hci_cmd_hdr` has to be taken into account (`param_len`).


Sorry for the misunderstanding on my part, looking forward for your comments.

File: drivers/bluetooth/hci/userchan.c [hunk 12]
```diff
@@ -93,6 +95,60 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+ */
+static uint16_t packet_len(const uint8_t *packet_buff)
+{
+	uint16_t payload_len = 0;
+	uint8_t header_len = 0;
+	const uint8_t packet_type = packet_buff[0];
+
+	switch (packet_type) {
+	case H4_CMD:
+		const struct bt_hci_cmd_hdr *hdr = &packet_buff[sizeof(packet_type)];
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:111]:
```suggestion
	const uint8_t packet_type = packet_buff[0];
	const uint8_t *packet_hdr = &packet_buff[sizeof(packet_type)];

	switch (packet_type) {
	case H4_CMD:
		const struct bt_hci_cmd_hdr *hdr = packet_hdr;
```

Since they all share the same offset, consider making doing it a single time.

File: include/zephyr/bluetooth/hci_types.h [hunk 13]
```diff
@@ -37,6 +37,14 @@ extern "C" {
 #define BT_HCI_SYNC_HANDLE_INVALID 0xffff
 #define BT_HCI_PAWR_SUBEVENT_MAX 128
 
+/* Bluetooth spec 5.2 Vol 4, Part E - 5.4.3 HCI Synchronous Data Packets */
```
[the remark this answers is not in the document]
Comment (vChavezB) [reply include/zephyr/bluetooth/hci_types.h]: Changed. Checked the numbering of the sections in the sepc and they are the same so I just changed the text to v5.4

File: drivers/bluetooth/hci/userchan.c [hunk 14]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+	const uint8_t packet_type = packet_buff[0];
+
+	switch (packet_type) {
+	case H4_CMD: {
+		const struct bt_hci_cmd_hdr *hdr = packet_hdr;
+
+		/* Parameter Total Length */
+		payload_len = hdr->param_len;
+		header_len = BT_HCI_CMD_HDR_SIZE;
+		break;
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:118]: Final comment: Just a thought, not a request:
We could also just do
```suggestion
		return sizeof(packet_type) + BT_HCI_CMD_HDR_SIZE + hdr->param_len;
```

and similar for all cases, to omit the 2 local variables (`payload_len` and `header_len`). This could reduce the size of this function by 14 lines 

Up to you if you want to change this, or leave it as is

**Review by Thalley — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]

File: drivers/bluetooth/hci/userchan.c (hunk 7 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: Ok, I think I overthought the comment. Changed to using `sys_le16_to_cpu` instead of `sys_get_le16` and the lenght member of the respective hci header struct instead of the address.

File: drivers/bluetooth/hci/userchan.c [hunk 15]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
 	return NULL;
 }
 
+/**
+ * @brief Decode the length of an HCI H4 packet
+ * @details Decodes packet length according to Bluetooth spec v5.4 Vol 4 Part E
+ * @param packet_buff	Pointer to a HCI packet buffer
+ * @return Length of the HCI packet in bytes, zero if no valid packet found.
+ */
+static uint16_t packet_len(const uint8_t *packet_buff)
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:104]: Sorry if this is getting a bit overly pedantic, but I'd prefer if we stick to existing variable naming conventions and also avoid unnecessarily long names. This helps keep the code more readable (for someone who has read a lot of other Bluetooth subsystem code). and also avoids excessively long lines.

Just call the input parameter `const uint8_t *buf`

File: drivers/bluetooth/hci/userchan.c [hunk 16]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+{
+	uint16_t payload_len = 0;
+	uint8_t header_len = 0;
+	const uint8_t packet_type = packet_buff[0];
+	const uint8_t *packet_hdr = &packet_buff[sizeof(packet_type)];
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:109]:
```c
const uint8_t type = buf[0];
const uint8_t hdr = &buf[sizeof(type)];
```

File: drivers/bluetooth/hci/userchan.c [hunk 17]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+
+	switch (packet_type) {
+	case H4_CMD: {
+		const struct bt_hci_cmd_hdr *hdr = (const struct bt_hci_cmd_hdr *)packet_hdr;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:113]:
```c
const struct bt_hci_cmd_hdr *cmd = (const struct bt_hci_cmd_hdr *)hdr;
```

File: drivers/bluetooth/hci/userchan.c [hunk 18]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+
+		/* Parameter Total Length */
+		payload_len = hdr->param_len;
+		header_len = BT_HCI_CMD_HDR_SIZE;
+		break;
+	}
+	case H4_ACL: {
+		const struct bt_hci_acl_hdr *hdr = (const struct bt_hci_acl_hdr *)packet_hdr;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:121]:
```c
const struct bt_hci_acl_hdr *acl = (const struct bt_hci_acl_hdr *)hdr;
```

File: drivers/bluetooth/hci/userchan.c [hunk 19]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+
+		/* Data Total Length */
+		payload_len = sys_le16_to_cpu(hdr->len);
+		header_len = BT_HCI_ACL_HDR_SIZE;
+		break;
+	}
+	case H4_SCO: {
+		const struct bt_hci_sco_hdr *hdr = (const struct bt_hci_sco_hdr *)packet_hdr;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:129]:
```c
const struct bt_hci_sco_hdr *sco = (const struct bt_hci_sco_hdr *)hdr;
```

File: drivers/bluetooth/hci/userchan.c [hunk 20]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+
+		/* Data_Total_Length */
+		payload_len = hdr->len;
+		header_len = BT_HCI_SCO_HDR_SIZE;
+		break;
+	}
+	case H4_EVT: {
+		const struct bt_hci_evt_hdr *hdr = (const struct bt_hci_evt_hdr *)packet_hdr;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:137]:
```c
const struct bt_hci_evt_hdr *evt = (const struct bt_hci_evt_hdr *)hdr;
```

File: drivers/bluetooth/hci/userchan.c [hunk 21]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+
+		/* Parameter Total Length */
+		payload_len = hdr->len;
+		header_len = BT_HCI_EVT_HDR_SIZE;
+		break;
+	}
+	case H4_ISO: {
+		const struct bt_hci_iso_hdr *hdr = (const struct bt_hci_iso_hdr *)packet_hdr;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:145]:
```c
const struct bt_hci_iso_hdr *iso = (const struct bt_hci_iso_hdr *)hdr;
```

File: drivers/bluetooth/hci/userchan.c [hunk 22]
```diff
@@ -93,6 +95,67 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+
+		/* ISO_Data_Load_Length parameter */
+		payload_len =  bt_iso_hdr_len(sys_le16_to_cpu(hdr->len));
+		header_len = BT_HCI_ISO_HDR_SIZE;
+	}
+	/* If no valid packet type found */
+	default:
+		return 0;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/userchan.c:153]: Might make sense to add a `LOG_WRN("Unknown packet type 0x%02x", type)` before the return.

**Review by jhedberg — CHANGES_REQUESTED** [review]
One more review round (thanks for your patience!). After that I think this is ready to be merged.

I think it'd also make sense to split the `hci_types.h` changes into its own commit (still in this same PR) before the `userchan.c` commit, since those changes are not strictly related to the userchan driver.

File: include/zephyr/bluetooth/hci_types.h [hunk 23]
```diff
@@ -37,6 +37,14 @@ extern "C" {
 #define BT_HCI_SYNC_HANDLE_INVALID 0xffff
 #define BT_HCI_PAWR_SUBEVENT_MAX 128
 
+/* Bluetooth spec v5.4 Vol 4, Part E - 5.4.3 HCI Synchronous Data Packets */
+struct bt_hci_sco_hdr {
+	uint16_t conn_handle;
```
[the remark this answers is not in the document]
Comment (jhedberg) [reply include/zephyr/bluetooth/hci_types.h:42]: Ok, I just checked and the HCI spec uses `Connection_Handle` both for SCO and ISO, but just `Handle` for ACL. However, since the ISO struct already uses simply `handle` I'd follow that convention for SCO as well.

File: drivers/bluetooth/hci/userchan.c (hunk 15 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c:104]: Oh no problem, I am aware that style and naming conventions are highly dependent on organisations policies. As I am still not that familiar with the codebase of Zephyr I know this could come up.

File: include/zephyr/bluetooth/hci_types.h (hunk 23 above)
[the remark this answers is not in the document]
Comment (vChavezB) [reply include/zephyr/bluetooth/hci_types.h]: changed

File: drivers/bluetooth/hci/userchan.c (hunk 22 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: added

File: drivers/bluetooth/hci/userchan.c (hunk 16 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: changed

File: drivers/bluetooth/hci/userchan.c (hunk 18 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: changed

File: drivers/bluetooth/hci/userchan.c (hunk 20 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: changed

File: drivers/bluetooth/hci/userchan.c (hunk 21 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: changed

**Comment by vChavezB** [comment]
Added last suggestions. Pending separation of commits...

File: drivers/bluetooth/hci/userchan.c [hunk 24]
```diff
@@ -93,6 +95,68 @@ static struct net_buf *get_rx(const uint8_t *buf)
 	return NULL;
 }
 
+/**
+ * @brief Decode the length of an HCI H4 packet
+ * @details Decodes packet length according to Bluetooth spec v5.4 Vol 4 Part E
+ * @param buff	Pointer to a HCI packet buffer
+ * @return Length of the HCI packet in bytes, zero if no valid packet found.
+ */
+static uint16_t packet_len(const uint8_t *buff)
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:104]:
```suggestion
static uint16_t packet_len(const uint8_t *buf)
```

Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c]: good catch, changed

**Comment by vChavezB** [comment]
I have separated the commits.

File: drivers/bluetooth/hci/userchan.c [hunk 25]
```diff
@@ -93,6 +95,68 @@ static struct net_buf *get_rx(const uint8_t *buf)
...
+		header_len = BT_HCI_EVT_HDR_SIZE;
+		break;
+	}
+	case H4_ISO: {
+		const struct bt_hci_iso_hdr *iso = (const struct bt_hci_iso_hdr *)hdr;
+
+		/* ISO_Data_Load_Length parameter */
+		payload_len =  bt_iso_hdr_len(sys_le16_to_cpu(iso->len));
+		header_len = BT_HCI_ISO_HDR_SIZE;
+	}
```
Comment (Thalley) [inline drivers/bluetooth/hci/userchan.c:150]:
```suggestion
		payload_len =  bt_iso_hdr_len(sys_le16_to_cpu(iso->len));
		header_len = BT_HCI_ISO_HDR_SIZE;
		break;
	}
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/userchan.c (hunk 25 above)
Comment (vChavezB) [reply drivers/bluetooth/hci/userchan.c:150]: Thanks for noticing this, have been changing different parts that I must have deleted the break while refactoring.

Comment (Thalley) [reply drivers/bluetooth/hci/userchan.c]: Yeah, it existed earlier :D

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
