### PR TITLE
drivers: flash: stm32 xspi flash read with memcopy when executing

### LINKED ISSUE #92883: stm32h573i_dk and similar: MCUBoot with external flash not able to update image
### Describe the bug

When trying to run the "boards/st/hello_world_xip" sample from https://github.com/zephyrproject-rtos/zephyr/pull/88579 (or the upcoming Zephyr release) with the following lines added to prj.conf:
````
CONFIG_FLASH=y
CONFIG_LOG=y
CONFIG_FLASH_LOG_LEVEL_ERR=y
````
The external flash initialisation fails with the following log message: "flash_stm32_xspi: XSPI Init failed"

However, the flash API is used to update or manage the MCUBoot images. (E.g. Flash Image API, MCUboot image contol API, IMG_MANAGER). So if the external flash isn't initialised, the image can't be updated or swapped.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Use https://github.com/zephyrproject-rtos/zephyr/pull/88579 or the upcoming Zephyr release, if the PR is already merged into main.
2. Add the following lines to prj.conf of the "boards/st/hello_world_xip" sample
````
CONFIG_FLASH=y
CONFIG_LOG=y
CONFIG_FLASH_LOG_LEVEL_ERR=y
````
3. build the sample: ```west build -p -b stm32h573i_dk samples/boards/st/hello_world_xip/ --sysbuild --   -DSB_CONFIG_BOOTLOADER_MCUBOOT=y```
4. flash the sample to a stm32h573i_dk board: ```west flash```
5. Open UART Port of the ST-Link and the error should appear in the log.

### Relevant log output

```shell
flash_stm32_xspi: XSPI Init failed
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- OS: Windows
- Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/88579

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by FRASTM**
When the application is executed in external flash, the read operation cannot be in indirect mode but with memcopy.
When executing in external flash, the  **CONFIG_STM32_APP_IN_EXT_FLASH** is set, the application knows the external flash reading is done with memcopy.

Note that writing or erasing the external flash being executed is not possible during the execution on the external flash.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/92883

### CODE REVIEW

**Comment by FRASTM** [comment]
run the  samples/sysbuild/with_mcuboot/  on the  stm32h573i_dk with --sysbuild and mcuboot shell : 

CONFIG_SHELL=y
CONFIG_FLASH_SHELL=y
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SHELL=y
CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y
CONFIG_MCUBOOT_IMG_MANAGER=y

```
*** Booting Zephyr OS build v4.2.0-678-g399f8f8b181f ***
Address of sample 0x90000000
Hello sysbuild with mcuboot! stm32h573i_dk
uart:~$ mcuboot
swap type: none
confirmed: 1

primary area (2):
  version: 0.0.0+0
  image size: 76984
  magic: unset
  swap type: none
  copy done: unset
  image ok: unset

secondary area (3):
  version: 0.0.0+0
  image size: 78008
  magic: unset
  swap type: none
  copy done: unset                                                                                                   
  image ok: unset                                                                                                    
[00:00:04.089,000] <inf> mcuboot_util: Image index: 0, Swap type: none                                               
uart:~$ 
```


(with a second image downloaded on slot1_partition)

**Comment by FRASTM** [comment]
same change to apply to the

-  ./drivers/flash/flash_stm32_ospi 
-  ./drivers/flash/flash_stm32_qspi

when reading with the CONFIG_STM32_APP_IN_EXT_FLASH set

File: drivers/flash/flash_stm32_xspi.c [hunk 1]
```diff
@@ -1186,29 +1186,32 @@ static int flash_stm32_xspi_read(const struct device *dev, off_t addr,
 		return 0;
 	}
 
-#ifdef CONFIG_STM32_MEMMAP
+#if defined(CONFIG_STM32_MEMMAP) || defined(CONFIG_STM32_APP_IN_EXT_FLASH)
+	/*
+	 * When executing in external flash, read immediately with memcopy
+	 * No need to check the memory mapped mode : it is necessarily set
+	 */
```
Comment (JarmouniA) [inline drivers/flash/flash_stm32_xspi.c]:
```suggestion
	/* When the call is made by an app executing in external flash, skip the memory-mapped mode check */
```
This comment should be moved to just before the `ifdef CONFIG_STM32_MEMMAP`

File: drivers/flash/flash_stm32_xspi.c [hunk 2]
```diff
@@ -1274,13 +1277,10 @@ static int flash_stm32_xspi_read(const struct device *dev, off_t addr,
...
 
 	ret = xspi_read_access(dev, &cmd, data, size);
-	goto read_end;
-#endif
-
-read_end:
 	xspi_unlock_thread(dev);
 
 	return ret;
+#endif
```
Comment (JarmouniA) [inline drivers/flash/flash_stm32_xspi.c]:
```suggestion
#endif /* CONFIG_STM32_MEMMAP || CONFIG_STM32_APP_IN_EXT_FLASH */
```

File: drivers/flash/flash_stm32_xspi.c [hunk 3]
```diff
@@ -1186,29 +1186,32 @@ static int flash_stm32_xspi_read(const struct device *dev, off_t addr,
 		return 0;
 	}
 
-#ifdef CONFIG_STM32_MEMMAP
+#if defined(CONFIG_STM32_MEMMAP) || defined(CONFIG_STM32_APP_IN_EXT_FLASH)
```
Comment (JarmouniA) [inline drivers/flash/flash_stm32_xspi.c:1189]:
```suggestion
#if defined(CONFIG_STM32_MEMMAP) || (defined(CONFIG_STM32_APP_IN_EXT_FLASH) && defined(CONFIG_XIP))
```
This is needed in my opinion, since the app image can be stored in ext flash but then be executed in RAM (after being copied there by MCUboot). In that case, we are not sure if the Flash is still MemMapped, because the app can exit Memmap mode and use a storage partition in external Flash for ex. Does this make sense?
https://github.com/zephyrproject-rtos/zephyr/blob/00e217da7d841e1ff163377535f1ac46b701a9cc/share/sysbuild/image_configurations/MAIN_image_default.cmake#L40
But maybe CONFIG_XIP is not the appropriate flag to check, since it is not disabled in SINGLE_APP_RAM_LOAD mode for ex.
https://github.com/zephyrproject-rtos/zephyr/blob/00e217da7d841e1ff163377535f1ac46b701a9cc/share/sysbuild/image_configurations/MAIN_image_default.cmake#L42
I'm no longer sure of the exact semantics of Zephyr XiP at this point, I think it just means "app is executed where it was last loaded, RAM, Flash, PSRAM...by either flashloader or bootloader" or something close to this.

@nordicjm Any thoughts on this? what am I getting wrong?

File: drivers/flash/flash_stm32_xspi.c (hunk 2 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_xspi.c]: added

File: drivers/flash/flash_stm32_xspi.c (hunk 1 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_xspi.c]: done

File: drivers/flash/flash_stm32_xspi.c (hunk 3 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_xspi.c:1189]: waiting for @nordicjm   comment

Comment (JarmouniA) [reply drivers/flash/flash_stm32_xspi.c:1189]: We will perhaps need to check for MCUboot modes instead, to know if Memmap mode is still required after the image has started executing, see https://github.com/zephyrproject-rtos/zephyr/pull/85254#discussion_r2255129303

It appears that XiP semantics in Zephyr needs real clarification in the docs & Kconfig help text, especially in relationship to the usage of a bootloader that can move the app image around, and Zephyr Code Relocation as well.

Comment (nordicjm) [reply drivers/flash/flash_stm32_xspi.c:1189]: to be honest I think the comment about single loader is wrong, it is executing from RAM, it should have XIP set to n, XIP means running from flash, the help text is clear on that:
```
        help
          This option allows the kernel to operate with its text and read-only
          sections residing in ROM (or similar read-only memory). Not all boards
          support this option so it must be used with care; you must also
          supply a linker command file when building your image. Enabling this
          option increases both the code and data footprint of the image.
```

Comment (JarmouniA) [reply drivers/flash/flash_stm32_xspi.c:1189]: > XIP means running from flash, the help text is clear on that

But is the help text still accurate today, compared to when XiP was first introduced?

Comment (nordicjm) [reply drivers/flash/flash_stm32_xspi.c:1189]: > > XIP means running from flash, the help text is clear on that
> 
> But is the help text still accurate today, compared to when XiP was first introduced?

yes, you are still running from read only media (one could argue that you could erase the flash sector you are running meaning it's not read only but that's not going to go well)

**Review by JarmouniA — APPROVED** [review]
I guess we can address the MCUboot modes issue https://github.com/zephyrproject-rtos/zephyr/pull/93762/files#r2255256603 in a later PR since it's an advanced usecase in my opinion.

**Review by erwango — APPROVED** [review]

File: drivers/flash/flash_stm32_xspi.c [hunk 4]
```diff
@@ -1186,29 +1186,31 @@ static int flash_stm32_xspi_read(const struct device *dev, off_t addr,
...
 	__ASSERT_NO_MSG(stm32_xspi_is_memorymap(dev));
-
+#endif /* CONFIG_STM32_MEMMAP */
 	uintptr_t mmap_addr = STM32_XSPI_BASE_ADDRESS + addr;
 
 	LOG_DBG("Memory-mapped read from 0x%08lx, len %zu", mmap_addr, size);
 	memcpy(data, (void *)mmap_addr, size);
-	ret = 0;
-	goto read_end;
+	return ret;
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_xspi.c:1213]: I think an explicit `return 0` would be better.
(non blocking comment)

File: drivers/flash/flash_stm32_xspi.c [hunk 5]
```diff
@@ -1186,29 +1186,31 @@ static int flash_stm32_xspi_read(const struct device *dev, off_t addr,
...
-	xspi_lock_thread(dev);
+	/*
+	 * When the call is made by an app executing in external flash,
+	 * skip the memory-mapped mode check
+	 */
+#ifdef CONFIG_STM32_MEMMAP
 
 	/* Do reads through memory-mapping instead of indirect */
 	if (!stm32_xspi_is_memorymap(dev)) {
 		ret = stm32_xspi_set_memorymap(dev);
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_xspi.c:1200]: I think `stm32_xspi_set_memorymap()` needs to be protected from concurrent accesses.

**Review by etienne-lms — CHANGES_REQUESTED** [review]

**Comment by etienne-lms** [comment]
Gosh... too late sorry.
@FRASTM, @erwango, could you have a look at https://github.com/zephyrproject-rtos/zephyr/pull/93762#discussion_r2315434225.

File: drivers/flash/flash_stm32_xspi.c (hunk 5 above)
Comment (etienne-lms) [reply drivers/flash/flash_stm32_xspi.c:1200]: Fix proposal (if needed) at https://github.com/zephyrproject-rtos/zephyr/pull/95425.
