### PR TITLE
tests/drivers/counter/counter_basic_api: allow equality in assert

### LINKED ISSUE #25363: tests/drivers/counter/counter_basic_api: Assertion failed on STM32 boards
**Describe the bug**
On several STM32 boards (nucleo_f746zg, nucleo_l4r5zi, nucleo_wb55rg, stm32f3_disco)
test tests/drivers/counter/counter_basic_api fails due to 'Assertion failed'

**To Reproduce**
1. west -v build -p auto  -b nucleo_f746zg tests/drivers/counter/counter_basic_api
2. See error

**Expected behavior**
Test Passed

**Screenshots or console output**

> starting test - test_single_shot_alarm_notop
> Testing RTC_0
> D: Set Alarm: 2
> 
> 
>     Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/counter/counter_basic_api/src/test_counter.c:279: alarm_handler: (diff < counter_us_to_ticks(dev, processing_limit_us) is false)
> Unexpected distance between reported alarm value(2) and actual counter value (2), top:-1 (processing time limit (2 us) might be exceeded?
> FAIL - test_single_shot_alarm_notop

### PR DESCRIPTION
**Pull request by ABOSTM**
Since introduction of #24374, test **tests/drivers/counter/counter_basic_api**  fails on STM32 boards.
Due to 1Hz frequency of RTC used, the 'diff' could be 0.
But then 'counter_us_to_ticks(dev, processing_limit_us)' is also 0.
We should allow the equality in the assert.

fixes #25363

### CODE REVIEW

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 1]
```diff
@@ -276,7 +276,7 @@ static void alarm_handler(struct device *dev, u8_t chan_id, u32_t counter,
 			(counter + top - now) : (counter - now);
 	}
 
-	zassert_true(diff < counter_us_to_ticks(dev, processing_limit_us),
+	zassert_true(diff <= counter_us_to_ticks(dev, processing_limit_us),
```
Comment (nordic-krch) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c:279]: so i wonder how does it help? assert checks if counter handler was processed within given time from which hardware event occured. Limit was set to arbitrary value 1ms as it was expected that it should be more than enough for the processor to handle that event. If it is not enough then limit should be increased or maybe it actually shows some issue with the specific counter implementation.

**Comment by nordic-krch** [comment]
regarding commit message: I usually see `tests: drivers: counter: ...`

File: tests/drivers/counter/counter_basic_api/src/test_counter.c (hunk 1 above)
Comment (ABOSTM) [reply tests/drivers/counter/counter_basic_api/src/test_counter.c:279]: Yes equal help because with 1Hz, the convertion `counter_us_to_ticks(dev, processing_limit_us)` give 0 ticks and `diff  `is also equal to 0.

**Comment by ABOSTM** [comment]
> regarding commit message: I usually see `tests: drivers: counter: ...`

Done

**Review by pabigot — APPROVED** [review]
Agreed, this problem was encountered in another context where the difference could be zero, though I can't find the reference right now.

**Review by carlescufi — APPROVED** [review]
