### PR TITLE
drivers: hwinfo: Fix mcux device id

### LINKED ISSUE #48447: `hwinfo devid` does not work correctly for NXP devices using `nxp,lpc-uid` device binding
**Describe the bug**
`hwinfo devid` does not correctly retrieve the device UUID for NXP SoC's using the `nxp,lpc-uid` device binding and corresponding driver `drivers/hwinfo/hwinfo_mcux_syscon.c`.

The bug was introduced in #36457

Primary problem is `memcpy` is used to read bytes from an address on the AHB bus (not in RAM). In such case `memcpy` does not perform correctly -- only bytes on word-aligned (32-bit) memory addresses are read.

Secondary problem is not converting from SoC endianness (little endian) to big endian (as expected by `hwinfo devid` command).

**To Reproduce**
For the following use a board with NXP SoC for which `hwinfo devid` uses the `nxp,lpc-uid` binding and driver (`hwinfo_mcux_syscon.c`). In my case I used a custom i.MX RT685 board but Zephyr supported board `mimxrt685_evk` can also be used.
 
1. Build and flash a project for which `HWINFO` driver and shell is enabled
2. Read the device id with `hwinfo devid`
```
$ hwinfo devid
Length: 16
ID: 0x44000000f20000009c00000061000000
```
3. Compare result when using debugger to view SoC device memory
In this example, showing UUID[0-3] of i.MX RT685 starting from `0x40002F50`:
image
 
Memory view as 32-bit (big endian) representation
image

It is clear `hwinfo devid` did not read the UUID correctly, but some similarities can be seen.

**Expected behavior**
The ID printed by `hwinfo devid` should match what is in the device.

**Environment**
 - OS: MacOS
 - Toolchain: Zephyr SDK
 - Zephyr version 3.1.0

### PR DESCRIPTION
**Pull request by brycewilkins**
This fixes an issue where the unique device identifier is incorrectly
copied from an address on the AHB bus to memory using memcpy.

I verified corrected behavior by comparing `hwinfo devid` command
output to memory view of the SoC using the debugger.

Fixes #48447

Signed-off-by: Bryce Wilkins <bryce.wilkins@gmail.com>

### CODE REVIEW

File: drivers/hwinfo/hwinfo_mcux_syscon.c [hunk 1]
```diff
@@ -22,7 +27,15 @@ ssize_t z_impl_hwinfo_get_device_id(uint8_t *buffer, size_t length)
 		length = DT_INST_REG_SIZE(0);
 	}
 
-	memcpy(buffer, uid_addr, length);
+	if (length > sizeof(dev_id.id)) {
```
Comment (alexanderwachter) [inline drivers/hwinfo/hwinfo_mcux_syscon.c:30]: Why two checks?

File: drivers/hwinfo/hwinfo_mcux_syscon.c [hunk 2]
```diff
@@ -10,9 +10,14 @@
...
 #include <zephyr/sys/byteorder.h>
 
+struct uid {
+	uint32_t id[4];
+};
+
 ssize_t z_impl_hwinfo_get_device_id(uint8_t *buffer, size_t length)
 {
-	uint8_t *uid_addr = (uint8_t *) DT_INST_REG_ADDR(0);
+	uint32_t *uid_addr = (uint32_t *) DT_INST_REG_ADDR(0);
```
Comment (alexanderwachter) [inline drivers/hwinfo/hwinfo_mcux_syscon.c:19]: Needs to be volatile if you want to prevent optimizations and unaligned access.

**Review by alexanderwachter — CHANGES_REQUESTED** [review]

File: drivers/hwinfo/hwinfo_mcux_syscon.c (hunk 1 above)
Comment (brycewilkins) [reply drivers/hwinfo/hwinfo_mcux_syscon.c:30]: I originally thought `nxp,lpc-uid` binding could support larger than 128b UUID, in which case it would exceed the size of `struct uid` and I wanted to ensure no writing outside the space reserved for `id`.

On second look it seems `nxp,lpc-uid` is specifically a 128b UUID. I'll remove this secondary length check and add a comment for `id` member of `struct uid`.

File: drivers/hwinfo/hwinfo_mcux_syscon.c (hunk 2 above)
Comment (brycewilkins) [reply drivers/hwinfo/hwinfo_mcux_syscon.c]: Thanks for the reminder -- updated and pushed new commit.

File: drivers/hwinfo/hwinfo_mcux_syscon.c (hunk 1 above)
Comment (alexanderwachter) [reply drivers/hwinfo/hwinfo_mcux_syscon.c]: I would rather define the array size from the device tree reg size property.

File: drivers/hwinfo/hwinfo_mcux_syscon.c [hunk 3]
```diff
@@ -22,7 +28,11 @@ ssize_t z_impl_hwinfo_get_device_id(uint8_t *buffer, size_t length)
 		length = DT_INST_REG_SIZE(0);
 	}
 
-	memcpy(buffer, uid_addr, length);
+	for(size_t i = 0 ; i < length / 4 ; i++) {
```
Comment (alexanderwachter) [inline drivers/hwinfo/hwinfo_mcux_syscon.c:31]: Missed that. This could copy too less. I think it is faster to just copy all of them.

**Review by alexanderwachter — CHANGES_REQUESTED** [review]

File: drivers/hwinfo/hwinfo_mcux_syscon.c (hunk 1 above)
Comment (brycewilkins) [reply drivers/hwinfo/hwinfo_mcux_syscon.c]: Updated with a macro using `DT_INST_REG_SIZE(0)` for the number of UUID words.

File: drivers/hwinfo/hwinfo_mcux_syscon.c (hunk 3 above)
Comment (brycewilkins) [reply drivers/hwinfo/hwinfo_mcux_syscon.c:31]: Correct -- I wrote it to only copy the words that will `memcpy`'d into `buffer`. But I agree with you it is clearer to copy all the UUID words to the struct, and from there `memcpy` what will fit into `buffer`.

I have swapped the order of a `length` check and use the `dev_id.id` size, which is similar to other implementations and isolates the `DT_INST_REG_SIZE(0)` to a single instance.

File: drivers/hwinfo/hwinfo_mcux_syscon.c [hunk 4]
```diff
@@ -10,19 +10,30 @@
 #include <string.h>
 #include <zephyr/sys/byteorder.h>
 
+#define uid_word_count (DT_INST_REG_SIZE(0) / 4)
```
Comment (alexanderwachter) [inline drivers/hwinfo/hwinfo_mcux_syscon.c:13]:
```suggestion
#define UID_WORD_COUNT (DT_INST_REG_SIZE(0) / sizeof(uint32_t))
```

**Review by alexanderwachter — CHANGES_REQUESTED** [review]
Almost there.
Macros need to be all capital.

File: drivers/hwinfo/hwinfo_mcux_syscon.c (hunk 4 above)
Comment (brycewilkins) [reply drivers/hwinfo/hwinfo_mcux_syscon.c]: Fixed!

Thanks for prompt reviews!

**Review by alexanderwachter — DISMISSED** [review]
Looks good now. Thanks for the fix!

**Comment by brycewilkins** [comment]
> Looks good now. Thanks for the fix!

@alexanderwachter I had to push again to fix a style issue I didn't check for earlier. I'm not sure why but after pushing it says I dismissed your (stale) review. I think this needs your ✅ again. Sorry about that!

**Review by alexanderwachter — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]
