### PR TITLE
fs: Clarify description of fs_open when no access bits given

### LINKED ISSUE #64030: fs_open error log
The documentation suggests to use `fs_open` with `flags=0` and presumably `fs_opendir` to detect existence/non-existence of a file.
In case the file does not exists the `fs.c` logs an error: [LOG_ERR("file open error (%d)", rc)](https://github.com/zephyrproject-rtos/zephyr/blob/b732c6d564e542fd25b63041ec713346e01711aa/subsys/fs/fs.c#L166). Since this is the intended outcome it surely is not an error.

There will be false positives in the log, if as suggested by the documentation `fs_open` is used to detect existence/non-existence of a file.

Ideally `fs_` would:
- [ ] <del>Either not log an error if the file/directory does not exist in such circumstance
- [ ] <del>Or provide an additional API function to detect existence/non-existence of files/directories
- [ ] If instead an alternative exists (for example `fs_stat`), the documentation may be updated to say so clearly.

I am opening the issue, because I do not know how to filter out real errors from the false positive.
I would imagine something like:
```
	rc = mp->fs->open(zfp, file_name, flags);
        bool false_positive = (rc == NOT_EXISTS && flags == 0);
	if (rc < 0 && !false_positive) {
		LOG_ERR("file open error (%d)", rc);
        }
	if (rc < 0) {
		zfp->mp = NULL;
		return rc;
	}
```

- [ ] <del>Ideally something similar could be done for `fs_opendir`

Thanks in advance.

### PR DESCRIPTION
**Pull request by de-nordic**
Added note warnign that fs_open should not be used for checking whether file exists or not and fs_stat should be used instead.

Fixes #64030

### CODE REVIEW

**Comment by de-nordic** [comment]
FYI @clamattia

File: include/zephyr/fs/fs.h [hunk 1]
```diff
@@ -262,8 +262,11 @@ static inline void fs_dir_t_init(struct fs_dir_t *zdp)
  *   - @c FS_O_CREATE create file if it does not exist
  *   - @c FS_O_APPEND move to end of file before each write
  *
- * If @p flags are set to 0 the function will attempt to open an existing file
- * with no read/write access; this may be used to e.g. check if the file exists.
+ * If @p flags are set to 0 the function will attempt to open file with
+ * no read/write access; although this could be used to check if a file exists,
+ * this will, when logging is enabled for file systems, log error when file
+ * would not be found and will require file to be closed in case when found.
+ * The fs_stat should be used for checking whether file exists or not.
```
Comment (kartben) [inline include/zephyr/fs/fs.h:269]: If the only anticipated usage of using no flag is a makeshift and error-prone equivalent of fs_stat then maybe the warning should be made more to the point by saying something like the below? (also making it a more visible `@warning`

```suggestion
 * @warning If @p flags are set to 0 the function will attempt to open file with
            no read/write access. While this can be used to check if a file
            exists, it is recommended to use @see fs_stat instead.
```

**Review by kartben — CHANGES_REQUESTED** [review]

**Review by kartben — DISMISSED** [review]

**Comment by de-nordic** [comment]
@kartben you have convinced me, with the "makeshift and error-prone", to take your change... partially, as I have removed the suggested usage to check for file existence.

**Comment by kartben** [comment]
> @kartben you have convinced me, with the "makeshift and error-prone", to take your change... partially, as I have removed the suggested usage to check for file existence.

:)
I'm confused by your latest force-push -- it seems it's back to a previous state?

**Review by Laczen — COMMENTED** [review]
What about making it clear from the start:
```
 * If @p flags are set to 0 the function will attempt to open file with
 * no read/write access. This should not be used to check if a file
 * exists as this will generate a log error when the file is not found
 * and requires the file to be closed when it is present. Instead use
 * fs_stat to check if a file exists.
```

**Comment by de-nordic** [comment]
> > @kartben you have convinced me, with the "makeshift and error-prone", to take your change... partially, as I have removed the suggested usage to check for file existence.
> 
> :) I'm confused by your latest force-push -- it seems it's back to a previous state?

No, I have taken the warning part but removed suggestion for using fs_open to check if file exists at all.

**Review by kartben — DISMISSED** [review]

File: include/zephyr/fs/fs.h [hunk 2]
```diff
@@ -262,8 +262,8 @@ static inline void fs_dir_t_init(struct fs_dir_t *zdp)
  *   - @c FS_O_CREATE create file if it does not exist
  *   - @c FS_O_APPEND move to end of file before each write
  *
- * If @p flags are set to 0 the function will attempt to open an existing file
- * with no read/write access; this may be used to e.g. check if the file exists.
+ * @warning If @p flags are set to 0 the function will attempt to open file with
+ *          no read/write access.
```
Comment (Laczen) [inline include/zephyr/fs/fs.h:266]: Why does this have a @warning ? It seems to be an allowed usage pattern but why does it have a warning,

**Comment by de-nordic** [comment]
> What about making it clear from the start:
> 
> ```
>  * If @p flags are set to 0 the function will attempt to open file with
>  * no read/write access. This should not be used to check if a file
>  * exists as this will generate a log error when the file is not found
>  * and requires the file to be closed when it is present. Instead use
>  * fs_stat to check if a file exists.
> ```

I, unfortunately, find this usage to be a hack. I know that this works but if the usage would be intended we would have to silence the error for that specific case. Additionally, if the file exists you have to actually close it afterwards, which is another possibility for mistake and leaving open handlers.
fs_open should be used for opening files.

We still need to fix some test cases that provide no flags, when checking whether they can open a file.

File: include/zephyr/fs/fs.h (hunk 2 above)
Comment (de-nordic) [reply include/zephyr/fs/fs.h:266]: Because you will open file but will not be able to read/write to it.
Maybe. Because backends may interpret some of open flags differently, for example create may imply write on one backend but not another.

Comment (Laczen) [reply include/zephyr/fs/fs.h:266]: The problem I have with the `@warning` is that (without some extra information) the user does not know what is warned against.

Comment (de-nordic) [reply include/zephyr/fs/fs.h:266]: I don't know, seems that the info no lack of read/write access is enough.

Comment (Laczen) [reply include/zephyr/fs/fs.h:266]: I agree, but when adding the `@warning` it should warn against something. Either remove the warning or add something like: `When issued on a existing file the file needs to be closed afterwards. When issued on a non-existing file an error message will be generated`

Comment (de-nordic) [reply include/zephyr/fs/fs.h]: I do not want to mention error message, because any subsystem called by driver may actually render error messages, or not depending on Kconfig, so it is pointless to provide such message here.

File: include/zephyr/fs/fs.h [hunk 3]
```diff
@@ -252,6 +252,8 @@ static inline void fs_dir_t_init(struct fs_dir_t *zdp)
  * @brief Open or create file
  *
  * Opens or possibly creates a file and associates a stream with it.
+ * Successfully opened file, when no longer in use, should be closed
+ * with fs_close.
```
Comment (kartben) [inline include/zephyr/fs/fs.h:256]: Nit:

```suggestion
 * with fs_close().
```

**Review by kartben — DISMISSED** [review]

**Comment by clamattia** [comment]
@de-nordic What is the state on this? Was it decided, that it is not needed?
Thanks and have a good day.

**Comment by de-nordic** [comment]
@kartben I have taken in your Nit.

**Comment by de-nordic** [comment]
> @kartben I have taken in your Nit.

Can you take a look again?

**Review by kartben — APPROVED** [review]

**Comment by de-nordic** [comment]
> This should go into 3.6 as it is a documentation improvement. Thanks @de-nordic! and sorry that I dropped the ball.

Thanks! No problem.

**Review by henrikbrixandersen — APPROVED** [review]
