### PR TITLE
usb: stm32wb: Properly lock Sem5 before initializing USB.

### LINKED ISSUE #25880: stm32wb: Unable to use BLE and USB host simultaneously.
**Describe the bug**

I'm developing an application that is exposing HID devices over USB and BLE (HID over GATT), using an stm32wb55rg dev kit as my current target board.

Currently, I can use one or the other (USB or BLE) successfully w/ Zephyr  `master`, but trying to enable *both* results in the USB stack failing to work... `dmesg` on my laptop shows errors pertaining to failure to enumerate the USB device.

I have an open PR #25850 that appears to fix this by properly locking Sem0 before setting up the USB clock settings on stm32wb.

**To Reproduce**
1. Develop an application that does both `usb_hid_register_device`/`usb_hid_init` and `bt_enable` exposting GATT services.
2. Build and deploy that application to an stm32wb device (stm32wb55rg)
3. Connect the USB client plug to a host system.
4. See that the HID device does *not* appear on the host system, nor does any inspection of the USB peripheral running Zephyr work as expected (e.g. `lsusb`).

**Expected behavior**
An application can support both USB and BLE simultaneously w/ this chipset.

**Impact**
Basic USB + BLE does not work. My application can't have working USB at all if BLE is enabled.

**Screenshots or console output**

Can provide `dmesg` output on failure as needed.

**Environment (please complete the following information):**
 - OS: Linux host connecting to the USB peripheral
 - Zephyr SDK, `master` of Zephyr itself.
 - Commit 3852e081261854849341f2cdd89b0da222089e96 triggered the problem.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by petejohanson**
* AN5289 notes that Sem5 should be held before configuring
  CLK48 for USB timing.

Fixes #25880

Signed-off-by: Pete Johanson <peter@peterjohanson.com>

With this fix, I can enable my stm32wb55rg board as *both* a USB peripheral and start the BLE stack.

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]
Txs for this fix!
I think it would be worth getting this one in V2.3.0. To do so, can you raise an associated issue ?

Also, please implement the semaphore release on detach.
I know this function is only used for tests for now, but this will be cleaner to have the sem release somewhere in the driver and it could start being used later on and also out of tree.

**Comment by petejohanson** [comment]
@erwango The same application note mentions holding sem0 temporarily when disabling the clock stuff during USB detach. I assume you'd want that full logic implemented, not just the release of Sem5?

**Comment by petejohanson** [comment]
@erwango I've pushed the *basic* semaphore lock release in the detach, but it's unclear to me the Sem0 usage here:

Screenshot from 2020-06-01 14-04-55

In particular, not sure about the "wait for free interrupt" logic they note, and I haven't had a chance to dig for exact examples from ST on that piece.

**Comment by erwango** [comment]
@petejohanson ok, txs. That seems unclear indeed, let me know your findings and we'll see what to do.

**Comment by petejohanson** [comment]
@erwango Yeah... so looking through all the samples in https://github.com/STMicroelectronics/STM32CubeWB is no use...

```
❯ grep CFG_HW_RNG_SEMID -r * | grep Lock
Projects/P-NUCLEO-WB55.Nucleo/Applications/Zigbee/Zigbee_DoorLock_Client_Router/Core/Inc/hw_conf.h:*  When using the RNG, it is good enough to use CFG_HW_RNG_SEMID to control CLK48.
Projects/P-NUCLEO-WB55.Nucleo/Applications/Zigbee/Zigbee_DoorLock_Client_Router/Core/Inc/hw_conf.h:#define CFG_HW_RNG_SEMID                                        0
Projects/P-NUCLEO-WB55.Nucleo/Applications/Zigbee/Zigbee_DoorLock_Server_Coord/Core/Inc/hw_conf.h:*  When using the RNG, it is good enough to use CFG_HW_RNG_SEMID to control CLK48.
Projects/P-NUCLEO-WB55.Nucleo/Applications/Zigbee/Zigbee_DoorLock_Server_Coord/Core/Inc/hw_conf.h:#define CFG_HW_RNG_SEMID 
```

No actual examples of them locking  or releasing that semaphore. Lots of examples in there of them locking semaphore 5 so fix the issue w/ the clock and USB... none for the detach case.

**Comment by erwango** [comment]
> @erwango Yeah... so looking through all the samples in https://github.com/STMicroelectronics/STM32CubeWB is no use...
> 
> ```
> ❯ grep CFG_HW_RNG_SEMID -r * | grep Lock
> Projects/P-NUCLEO-WB55.Nucleo/Applications/Zigbee/Zigbee_DoorLock_Client_Router/Core/Inc/hw_conf.h:*  When using the RNG, it is good enough to use CFG_HW_RNG_SEMID to control CLK48.
> Projects/P-NUCLEO-WB55.Nucleo/Applications/Zigbee/Zigbee_DoorLock_Client_Router/Core/Inc/hw_conf.h:#define CFG_HW_RNG_SEMID                                        0
> Projects/P-NUCLEO-WB55.Nucleo/Applications/Zigbee/Zigbee_DoorLock_Server_Coord/Core/Inc/hw_conf.h:*  When using the RNG, it is good enough to use CFG_HW_RNG_SEMID to control CLK48.
> Projects/P-NUCLEO-WB55.Nucleo/Applications/Zigbee/Zigbee_DoorLock_Server_Coord/Core/Inc/hw_conf.h:#define CFG_HW_RNG_SEMID 
> ```
> 
> No actual examples of them locking or releasing that semaphore. Lots of examples in there of them locking semaphore 5 so fix the issue w/ the clock and USB... none for the detach case.

Ok, let's be pragmatic here. Let the code as is, but please put a TODO in usb_detach so one doesn't loose too much time if this function gets used.

**Comment by petejohanson** [comment]
@erwango Works for me. I've just pushed an updated version with a note about the remaining detach logic that may be needed. Thanks again!

File: drivers/usb/device/usb_dc_stm32.c [hunk 1]
```diff
@@ -110,6 +110,9 @@ LOG_MODULE_REGISTER(usb_dc_stm32);
  */
 #ifdef USB
 
+#define CFG_HW_RCC_CRRCR_CCIPR_SEMID	5
+#define CFG_HW_RCC_RNG_SEMID		0
```
Comment (erwango) [inline drivers/usb/device/usb_dc_stm32.c:114]: Let's remove this one for now.

**Review by erwango — CHANGES_REQUESTED** [review]
One last change and this should be good to go

File: drivers/usb/device/usb_dc_stm32.c (hunk 1 above)
Comment (petejohanson) [reply drivers/usb/device/usb_dc_stm32.c]: Done.

**Review by erwango — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
