### PR TITLE
modem: hl7800: fix power off

### LINKED ISSUE #54288: modem: hl7800: power off draws excessive current
After calling `mdm_hl7800_power_off` there is excessive current draw.
This is because the UART and control IO are not de-asserted properly. This causes the HL7800 to not shut off.

### PR DESCRIPTION
**Pull request by rerickson1**
Ensure DNS resolver is stopped if modem is turned off.
All IO connected to the HL7800 need to be de-asserted
in order for the HL7800 to power off.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/54288

### CODE REVIEW

**Review by rlubos — DISMISSED** [review]

File: drivers/modem/hl7800.c [hunk 1]
```diff
@@ -5468,29 +5484,53 @@ int32_t mdm_hl7800_reset(void)
...
+	ARG_UNUSED(item);
+	int ret;
+#if defined(CONFIG_DNS_RESOLVER)
+	struct dns_resolve_context *dnsCtx;
 
-	LOG_INF("Powering off modem");
-	wakeup_hl7800();
-	hl7800_stop_rssi_work();
+	LOG_DBG("Shutdown DNS resolver");
+	dnsCtx = dns_resolve_get_default();
```
Comment (ycsin) [inline drivers/modem/hl7800.c:5495]: not sure if this camelCase is intended?

Comment (rerickson1) [reply drivers/modem/hl7800.c]: Fixed, this was a historical copy paste thing.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
