### PR TITLE
nRF GPIO: Fix get_config not returning initial output setting

### LINKED ISSUE #88293: tests: drivers: gpio: gpio_basic_api: drivers.gpio.2pin fails on nrf54h20dk@0.9.0/nrf54h20/cpuapp and cpuard
**Describe the bug**
Tests 
- tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin

Observed for `nrf54h20dk@0.9.0/nrf54h20/cpuapp` and `nrf54h20dk@0.9.0/nrf54h20/cpurad`.

**To Reproduce**
1. haven rf54h20dk@0.9.0/nrf54h20/cpuapp connected
2. go to your zephyr dir
3. call `./scripts/twister -T tests/drivers/gpio/gpio_basic_api -p nrf54h20dk@0.9.0/nrf54h20/cpuapp --device-testing --device-serial /dev/ttyACM0 -v --inline-logs --west-flash="--erase"`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v4.1.0-2034-g8f2f97ce320a ***
Running TESTSUITE after_flash_gpio_config_trigger
===================================================================
START - test_gpio_config_trigger
 PASS - test_gpio_config_trigger in 0.011 seconds
===================================================================
START - test_gpio_config_twice_trigger
 PASS - test_gpio_config_twice_trigger in 0.011 seconds
===================================================================
TESTSUITE after_flash_gpio_config_trigger succeeded
Running TESTSUITE gpio_port
===================================================================
START - test_gpio_port
Validate device gpio@938000 and gpio@938000
Check gpio@938000 output 6 connected to gpio@938000 input 7
OUT 6 to IN 7 linkage works
- bits_physical
- pin_physical
- check_raw_output_levels
- check_logic_output_levels
- check_input_levels
- bits_logical
- check_pulls

    Assertion failed at ../../../../../../../../../zephyr/tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:660: pin_get_config: (flags_get not equal to flags_set)
flags are different
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.17.0
 - Commit SHA or Version used: `v4.1.0-2034-g8f2f97ce320a`

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
The nRF GPIO hardware does not store the initial output value set resulting from gpio_pin_configure() and thus, when gpio_get_config() is used, the initial value is not returned.

This commit reads the output value, and converts this to the corresponding INIT flag in the config

fixes: #88293

### CODE REVIEW

File: drivers/gpio/gpio_nrfx.c [hunk 1]
```diff
@@ -119,6 +122,7 @@ static int gpio_nrfx_pin_configure(const struct device *port, gpio_pin_t pin,
 	uint8_t ch;
 	bool free_ch = false;
 	const struct gpio_nrfx_cfg *cfg = get_port_cfg(port);
+	struct gpio_nrfx_data *data = get_port_data(port);
```
Comment (aescolar) [inline drivers/gpio/gpio_nrfx.c:125]:
```suggestion
#ifdef CONFIG_GPIO_GET_CONFIG
	struct gpio_nrfx_data *data = get_port_data(port);
#endif
```
Otherwise data is unused

[the remark this answers is not in the document]
Comment (bjarki-andreasen) [reply drivers/gpio/gpio_nrfx.c]: thanks :)

**Review by aescolar — DISMISSED** [review]

File: drivers/gpio/gpio_nrfx.c [hunk 2]
```diff
@@ -163,6 +166,10 @@ static int gpio_nrfx_pin_configure(const struct device *port, gpio_pin_t pin,
 		nrf_gpio_port_out_clear(cfg->port, BIT(pin));
 	}
 
+#ifdef CONFIG_GPIO_GET_CONFIG
+	get_port_data(port)->output_init = (flags & GPIO_OUTPUT_INIT_HIGH) ? 1 : 0;
```
Comment (anangl) [inline drivers/gpio/gpio_nrfx.c:170]: Initialization values are specified per pin, not per port, so they would need to be stored separately for all pins. But wouldn't it be easier to just return the current output value in `gpio_nrfx_pin_get_config()`? I took a quick look at some other drivers and they do so. The 2pin test would pass then (and actually, the test itself seems to be not perfect in this regard, as `GPIO_OUTPUT_INIT_*` flags are not really part of a pin configuration, so they should be filtered out from the value returned from `gpio_pin_get_config()`).

**Review by anangl — CHANGES_REQUESTED** [review]

**Review by anangl — APPROVED** [review]

**Review by aescolar — APPROVED** [review]
