### PR TITLE
arch: arm: nxp: mpu: fix constant expression result errors

### LINKED ISSUE #13836: [Coverity CID :190987]Integer handling issues in /arch/arm/core/cortex_m/mpu/nxp_mpu.c
Static code scan issues seen in File: /arch/arm/core/cortex_m/mpu/nxp_mpu.c
 Category: Integer handling issues
 Function: _mpu_sram_partitioning
 Component: Architectures
 CID: 190987
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #13865: [Coverity CID :190950]Integer handling issues in /arch/arm/core/cortex_m/mpu/nxp_mpu.c
Static code scan issues seen in File: /arch/arm/core/cortex_m/mpu/nxp_mpu.c
 Category: Integer handling issues
 Function: _mpu_sram_partitioning
 Component: Architectures
 CID: 190950
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by ioannisg**
This commit fixes two Constant Expression Result errors,
in the NXP MPU driver due to incompatible integer types.

Fixes #13836.
Fixes #13865.

Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

File: arch/arm/core/cortex_m/mpu/nxp_mpu.c [hunk 1]
```diff
@@ -203,12 +203,10 @@ static int _mpu_sram_partitioning(u8_t index,
...
-		_region_allocate_and_init(index,
-			(const struct nxp_mpu_region *)&added_sram_region);
-
-	if (index == -EINVAL) {
-		return index;
+	if (_region_allocate_and_init(index,
+			(const struct nxp_mpu_region *)&added_sram_region)
+		== -EINVAL) {
+		return -EINVAL;
 	}
```
Comment (MaureenHelm) [inline arch/arm/core/cortex_m/mpu/nxp_mpu.c]: Would a better fix be:
```c
	if (_region_allocate_and_init(index,
			(const struct nxp_mpu_region *)&added_sram_region)
		< 0) {
		return -EINVAL;
	}
```
??

Comment (ioannisg) [reply arch/arm/core/cortex_m/mpu/nxp_mpu.c]: Yes, that's fine, i will apply this.

**Review by ioannisg — COMMENTED** [review]
@MaureenHelm, updated, based on your suggestion, pls, revisit.

**Review by MaureenHelm — APPROVED** [review]
