### PR TITLE
Arch arm core fix fault report nxp mpu

### LINKED ISSUE #7706: ARM NXP hardware stack overflows do not report _NANO_ERR_STACK_CHK_FAIL or provide MPU fault information
When stack guard pages are enabled and a thread overflows its stack, the error reported is as follows, causing tests/kernel/fatal to work improperly:

```
test stack overflow - timer irq
***** BUS FAULT *****
  Executing thread ID (thread): 0x2000002c
  Faulting instruction address:  0x1b6e
  Imprecise data bus error
Caught system error -- reason 0

    Assertion failed at /home/apboie/projects/zephyr/tests/kernel/fatal/src/main.c:224: test_fatal: )
bad reason code got 0 expected 2
```

Reason code 0 is _NANO_ERR_CPU_EXCEPTION, the expected code of 2 is _NANO_ERR_STACK_CHK_FAIL.

I reproduced this on frdm_k64f.

We need to fix this:
* There is logic in fault.c for dumping out MPU faults, but it is never called even though this is an MPU access violation. The user will not know that the fault was due to illegal memory access.
* If the MPU fault was due to access violation within the region used for the stack guard, the reason code provided to _NanoFatalErrorHandler should be _NANO_ERR_STACK_CHK_FAIL and not _NANO_ERR_HW_EXCEPTION.

I'm committing a FIXME workaround to the fatal test until this is fixed.

### LINKED ISSUE #13342: arm: user thread stack overflows do not report _NANO_ERR_STACK_CHK_FAIL
**Describe the bug**
A stack overflow of a user thread on ARM should report to _NanoFatalErrorHandler() a reason code of _NANO_ERR_STACK_CHK_FAIL. Instead it is reporting _NANO_ERR_HW_EXCEPTION.

**To Reproduce**
Run tests/kernel/fatal, with pr #13343 and the ifdefs for CONFIG_ARM removed.

**Expected behavior**
Passing test.

**Impact**
Stack overflows are not reported as such, wasting or confounding developer time.

I expect this issue affects both ARM and NXP MPUs.

### LINKED ISSUE #13432: ARM: Fault Handling Mechanism and how to correctly report Stack Corruptions
We seem to  have technical challenges for both the MPU-based stack corruption detection, as well as for the detection based on the ARMv8-M stack pointer LIMIT registers.

First, about MPU. The way we implement the guard area, for stack corruption is somewhat problematic for SUPERVISOR threads. 
The reason is simple; when there is a stack overflow, and the area is violated by Push instructions, the stack frame is _NOT_ loaded in the guard area.
This means, that we cannot "by design" extract safely the instruction address that caused the error! Now, we might be lucky enough,
and there was an (at least) 8-byte "slack" between SP and Guard at the time we did the Push that overflowed the stack.
In that case, the "assumed" stack context will have the upper 8-byte part of the stack frame correct (and we will be able to read the address)!
This will be the PC and XPSR. But, in general, we cannot be sure about the faulty instruction address, and, of course, we can not do any "decoding" to see what type of instruction it was.
This is not a tragedy, but we must state this clearly. I think, the same applies for USER threads,
because the processor MODE changes after we branch to the MPU exception; the stacking occurs earlier, and... same problem.

Fortunately, the processor does report "Precise data access violation" _and_ "Stacking Error", _and_ the violated address.
It is safe to report a stack corruption in this scenario, because it could only have been the following:
- The "normal" case: thread tried to push to stack, violated the guard and stacking also (naturally) failed
- The "crazy" case: thread tried to explicitly write to the stack guard area (for some crazy reason), MPU fault raised, and (only) its Stacking caused the overflow.
  But it _was_ an overflow, and it was due to thread's operations, so it is ok to report it.

Things we WON'T report, now, as Stack corruptions:
- Standard stacking error due to interrupt entry. This IS actually a minor problem, cause, practically, the thread stack did run out of space, but
  we only caught it through an un-related exception. We can decide if we want to report this as a Stack Fail. Note, however, that we won't have the instruction address, of course,
  but, also, we won't have the violated address in this case (it is not a Direct Address Violation). **_So we need to decide what to do with that._**
  
- The "crazy" scenario, where thread tried to explicitly write to the stack guard area, so an MPU fault raised but not together with Stacking error (i.e. there was lots of stack area remaining,
  to stack the MPU fault context frame). I think this is OK to not report it as Stack Limit Check fail.
  

Second, about ARMv8-M and the built-in stack overflow checking:
Here the things are slightly different. First, we do not have a guard; just a limit on the PSP.
If a stack overflow occurs, we definitely know it was the right stack overflow (due to STMDB sp! that made the SP try to go beyond the preset limit).
So we are safe to report Stack Limit Check Fail, but we won't have a stack frame to present to the user at all!

---

My proposal is to just report to the user that the instruction address may be trash, and report Stacking && Direct Violation errors as stack corruptions (if memory addresses are within the guard areas)

### PR DESCRIPTION
**Pull request by ioannisg**
Fixes #7706 
Fixes #13342 
Closes #13432 

This PR
- investigates stack corruptions, not only or precise memory violations, but also on stacking errors
-  refactors fault.c, so the assessment of stack fail is moved to thread.c, as it accesses kernel structures,
- allows reporting thread stack corruption for user threads stacks,
- improves error messages and inline documentation related to ARM memory faults,

### CODE REVIEW

**Comment by andrewboie** [comment]
Hmm, this might not be as robust as it could be.
Would it be possible instead to have evaluate_current_thread_stack_corruption() take the faulting thread's stack pointer at the moment of exception, and test whether it falls within the bounds of the thread's appropriate stack buffer? You would need to know whether the thread was running in user mode *at the time* to determine which buffer to check, since the thread could be have been in a system call.

**Comment by ioannisg** [comment]
> 
> 
> Hmm, this might not be as robust as it could be. I'd rather not rely completely on the guard areas, they are just useful to trigger the exception.
> 
> Would it be possible instead to have evaluate_current_thread_stack_corruption() take the faulting thread's stack pointer at the moment of exception, and test whether it falls within the bounds of the thread's appropriate stack buffer? You would need to know whether the thread was running in user mode _at the time_ to determine which buffer to check, since the thread could be have been in a system call.

@andrewboie your suggestion seems reasonable (I only tried to align the impl for NXP MPU with what we already had for ARM MPU). I guess I just need to add the additional inspection of stack pointers. The infrastructure to test the execution mode before the fault is already present.

**Comment by ioannisg** [comment]
@agross-linaro  please take some time to review this one :)
@andrewboie I addressed your concerns about the robustness of stack corruption reports. By requiring an MPU/BusFault to be _always_ a stacking error, we catch all possible scenarios of stack corruption. Besides checking the violated address, we additionally check that the stack pointer is below the boundaries of the "allowed" stack area. This ensures we never not miss a case that is is a stack corruption. Please, check the details in `arch/arm/core/thread.c`

File: arch/arm/core/fault.c [hunk 1]
```diff
@@ -273,6 +254,46 @@ static u32_t _MpuFault(NANO_ESF *esf, int fromHardFault)
...
+			 * the stack pointer has actually moved. We might
+			 * face problems with un-stacking the frame, upon
+			 * exception return, if we do not have sufficient
+			 * permissions to read the corrupted stack frame.
+			 * Therefore, we move the stack manually to the
+			 * minimum allowed position for the stack pointer.
+			 */
+			__set_PSP(min_stack_ptr);
+
+			reason = _NANO_ERR_STACK_CHK_FAIL;
```
Comment (agross-linaro) [inline arch/arm/core/fault.c]: my only concern here is that we faulted when we were pushing on a stack.  If we unwind that and return from exception, we're no longer just back to where it was before it faulted, we're actually another stack frame back, and worse... we used some of the stack contents to set the current PC.

**Review by agross-oss — COMMENTED** [review]
still a little concerned about the unwinding of the stack to avoid unstacking errors.

File: arch/arm/core/fault.c (hunk 1 above)
Comment (andrewboie) [reply arch/arm/core/fault.c]: I'm confused on the scenario.
A stack overflow is a fatal error for the thread. k_thread_abort() gets called, even though we return from the exception the PendSV should kick in, if we actually ever return to the faulting thread context then that is a bug.

Comment (ioannisg) [reply arch/arm/core/fault.c]: > 
> 
> my only concern here is that we faulted when we were pushing on a stack. If we unwind that and return from exception, we're no longer just back to where it was before it faulted, we're actually another stack frame back, and worse... we used some of the stack contents to set the current PC.

This is true. But then, we are aborting this thread. The stack is un-usable, anyways. There is no way we should recover a thread that overloaded its stack. So, I don't see a problem with that.

Comment (ioannisg) [reply arch/arm/core/fault.c]: > I'm confused on the scenario.
> A stack overflow is a fatal error for the thread. k_thread_abort() gets called, even though we return from the exception the PendSV should kick in, if we actually ever return to the faulting thread context then that is a bug.

@andrewboie , this is confusing, indeed. We should have the PendSV interrupt _tail-chained_ after the MPUfault; unfortunately, I do not observe this in my testing. In fact, I see the unstacking occurring, first, and a new fault popping up, because of the faulty unstacking.

On the other hand, I think that with my patch the code is more robust and standalone; we do not rely on the tail-chained pendSV to kick in. We direclty restore the PSP to "some area" that is safe to be used. I can't see a problem with that.

Comment (ioannisg) [reply arch/arm/core/fault.c]: To conclude, @andrewboie @agross-linaro , my big concern, here, is to understand _why_ the re-adjustment of PSP is not needed for Cortext-M3 and Cortex-M4; the patch, itself, is fairly safe, IMHO.

File: arch/arm/core/fault.c [hunk 2]
```diff
@@ -273,6 +254,49 @@ static u32_t _MpuFault(NANO_ESF *esf, int fromHardFault)
...
+			/* When MemManage Stacking Error has occurred, the
+			 * the stack context frame might be corrupted but
+			 * the stack pointer has actually moved. We might
+			 * face problems with un-stacking the frame, upon
+			 * exception return, if we do not have sufficient
+			 * permissions to read the corrupted stack frame.
+			 * Therefore, we move the stack manually to the
+			 * minimum allowed position for the stack pointer.
+			 */
+			__set_PSP(min_stack_ptr);
```
Comment (ioannisg) [inline arch/arm/core/fault.c]: @agross-linaro could you please try to test the patch on Musca_a, with and without the PSP re-adjustment in this line?

File: arch/arm/core/fault.c (hunk 1 above)
Comment (andrewboie) [reply arch/arm/core/fault.c]: > We should have the PendSV interrupt _tail-chained_ after the MPUfault; unfortunately, I do not observe this in my testing. In fact, I see the unstacking occurring, first, and a new fault popping up, because of the faulty unstacking.

We should treat this as a high-priority bug I think.

**Comment by ioannisg** [comment]
@agross-linaro @andrewboie here is a summary of my study on this:

- first, this PR now includes _all_ possible cases, where thread stacks overflow, i.e. including the case when we _just_ have a stacking error due to some (random) interrupt that causes stacking. 
- second, regarding the Unstacking Error: the errors are expected - I managed to reproduce them on **_both_** ARMv7 and ARMv8 . The root cause of the Unstacking errors lies in the following explanation, in the ARMv8 spec:
>E2.1.231  PopStack(EXC_RETURN_Type excReturn)
// NOTE: All stack accesses are performed as Unprivileged accesses if
// returning to thread mode and CONTROL.nPRIV is 1 for the destination
// Security state.

When we overflow a User stack, we will be returning to user mode, so trying to pop from the area beyond the end of the stack triggers MPU Unstacking Errors.

@agross-linaro it is easy to reproduce; just comment out the setting of PendSV to pending - this will make MPUFault attempt to return, and the Unstacking error will fire.

- the reason why we do not see this problem in ARMv7, is the fact that the PendSV gets tail-chained, so we skip the unstacking-stacking operations when going from the MPUFault() to PendSV(). PendSV, finally, performs a context-switch to some other thread, so when we finally return to Thread mode, we do not encounter issues with unstacking.

But: tail-chaining does not seem to work in the same way in ARMv8. We still investigate why, however:

IMO, we should not really depend on the proper functioning of tail-chaining, to hide the unstacking errors: it is much more robusst and safe to manually bring up the PSP to the beginning of the thread stack, just in case the tail-chaining is skipped. We shall never ever expect to keep alive a thread that managed to overflow its stack, for whatever reason. It is a fatal error, the thread must be aborted, therefore, its stack is useless and OK to temporarily  overwrite.

That said, I think we need to move forward with the solution proposed in this PR.

As a follow-up action, I will add some related commenting inside the code to justify the manual adjustment of PSP based on the above argumentation

File: arch/arm/core/thread.c [hunk 3]
```diff
@@ -165,3 +165,98 @@ void configure_builtin_stack_guard(struct k_thread *thread)
...
+ *
+ * @param fault_addr memory address on which memory access violation
+ *                   has been reported. It can be invalid (-EINVAL),
+ *                   if only Stacking error has been reported.
+ * @param psp        current address the PSP points to
+ *
+ * @return The lowest allowed stack frame pointer, if error is a
+ *         thread stack corruption, otherwise return 0.
+ */
+u32_t evaluate_current_thread_stack_corruption(const u32_t fault_addr,
```
Comment (andrewboie) [inline arch/arm/core/thread.c]: this function isn't properly namespaced, needs a z_ prefix
The name of this function is excessively long.

**Comment by andrewboie** [comment]
> IMO, we should not really depend on the proper functioning of tail-chaining, to hide the unstacking errors:

We need to prove that tail-chaining works in all cases, or get rid of it and start doing context switching on ARM in a way that is closer to how other other arches do it. Having it be an ongoing source of flakiness is not good IMO

File: arch/arm/core/thread.c (hunk 3 above)
Comment (ioannisg) [reply arch/arm/core/thread.c]: Fixed. Thanks.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by agross-oss — APPROVED** [review]
