### PR TITLE
dts: bindings: Add zephyr,mapped-partition binding, and demonstrate usage of it

### LINKED ISSUE #103355: boards/dts: `fixed-partition` issues with lack of being memory-mapped
### Describe the bug

Zephyr previously has used the `fixed-partitions` binding which it has inherited from Linux, this binding does not mandate the use of ranges (though does not rule it out) which means that the partitions are not mapped to the same address bus as the CPU meaning they are not memory mapped. In linux, this is not a problem because the processors likely have MMUs which mean that the address is virtual anyhow, but in zephyr this is not the case, applications for e.g. cortex M devices must be built for the absolute address that the NVM (usually flash) resides at, applications cannot be remapped and are not built with PIC, therefore the build system (and subsystems which use flash) need to know the memory mapped address of the NVM partitions to be able to use and run from them.

The traditional way of zephyr dealing with this is it cannot do it using DTS alone, the build system must have the chosen flash node set in order to get the flash base address, it then needs to have the chosen flash partition node set in order to get an offset, it then needs to add these together in order to link at the address (the alternate is manually setting the flash load address which leads to issues like area overflowing their bounds - an issue going back over 6 years https://github.com/zephyrproject-rtos/zephyr/issues/27471 and which in itself is also error prone due to either having to specify a constant value which can get out of date with board changes, or having to use dt functions in Kconfig to add/subtract values from dt). This is the same when dealing with flash partitions, the compatible has to be read and checked, then it must go up through the parents one at a time to find one with one specific compatible which can be seen here https://github.com/zephyrproject-rtos/zephyr/blob/v4.3-branch/include/zephyr/devicetree/fixed-partitions.h#L80 this isn't flexible and goes against the whole idea of memory mapped devices in devicetree. This has only expanded further with the introduction of fixed-subpartitions which was introduced to allow grouping of partitions and support use-cases like having a single set of partitions which would support usage with and without a bootloader (and preventing overflowing into over partitions) or optional partition sets which can be changed using aliases/chosen nodes instead of needing to delete whole partitions then re-create them - this required parsing through yet another layer of going up parent dt nodes, though does make use of the dt `ranges` property to be relative to the parent fixed-partition node. However there is an issue with this in that for each layer, a new set of macrobatics is needed, so for fixed-subpartition inside of a fixed-subpartition, the macro in-tree will not work, it would need to have all of the inner checks which go up an additional layer of dt parentage and checking compatibles (needed because of the lack of `ranges` mapping with the `fixed-partitions` parent/grand-parent) which is unworkable for out of tree users, sometimes needing many layers, and a gigantic spread of mess to users that look at the macro and attempt to work on it.

The method for setting the flash base address and flash load offset is also echoed by how the RAM device is also picked, actually NVM devices and RAM devices _must_ be 1KiB sized and aligned due to this redirection of values, this causes wasted resources and makes some setups actually non-viable due to insufficient memory on lower end MCUs - none of which would be a problem if dt parts were used as-is without having to go through Kconfig manipulation to be viable.

Thus a way of fixing these issues is needed whereby partitions for **memory-mapped** devices are correctly described in devicetree without needing implicit knowledge of multiple layers of bindings to make sense of what their values actually mean which dt alone cannot provide. As memory mapped devices are part of the same address space as the CPU, the dt `ranges` property should be used to achieve this and zephyr should be updated to use this new system when building - the old `fixed-partitions` system should still function for non-memory mapped devices, and in a deprecated state for memory-mapped devices to allow users to update to the new system. When the dt maintainers of the linux kernel were asked about it, their responses indicate that for memory mapped devices they too agree that these should be using `ranges` to indicate that they are part of the CPU memory mapped space too as per the discussion on https://lore.kernel.org/devicetree-spec/aY_XxHMzWyJLqWog@zatzit/

One thing that likely has left to this being overlooked for so long is that a good portion of MCU devices have flash (or other) storage devices that start at 0x0, meaning that for the most part it has co-incidentally matched up with the actual offsets of the partitions anyhow.

Issue list:

- [ ] NXP @butok see https://github.com/zephyrproject-rtos/zephyr/pull/103222 for one board fix, please apply to all others
- [x] Nordic @nordicjm https://github.com/zephyrproject-rtos/zephyr/pull/103222
- [x] Raspberry pi @soburi https://github.com/zephyrproject-rtos/zephyr/pull/103222
- [ ] STM32 @erwango https://github.com/zephyrproject-rtos/zephyr/pull/103652 (in progress)

Related fixes:
- [ ] flashdisk and tests fixes: https://github.com/zephyrproject-rtos/zephyr/pull/103631
- [ ] Legacy scheme fallback fix: https://github.com/zephyrproject-rtos/zephyr/pull/103587

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

https://devicetree-specification.readthedocs.io/en/latest/chapter2-devicetree-basics.html#ranges

### PR DESCRIPTION
**Pull request by nordicjm**
Adds a new binding which represents a memory-mapped XIP NVM (flash etc.) partition mapping, and adds supports for it throughout the tree. Includes updating nrf52840 to use this new binding

- [x] MCUboot update needed
- [x] Release notes update
- [x] Fix deprecation warning with old binding
- [x] Remove `ranges` handling for `fixed-partitions` and `fixed-subpartitions`
- [x] Add test to devicetree API test
- [x] Add deprecation note on FIXED_PARTITION_* macros

Fixes #103355

### CODE REVIEW

**Comment by JarmouniA** [comment]
> instead of `zephyr,xip-partition` perhaps something like `zephyr,mm-partition` or `zephyr,mapped-partition` would be better, because some partitions using this binding (e.g. storage) will not be used for "execute in place/xip", just for memory-mapped access to the partition.

Indeed, XiP is a software config thing (CONFIG_XIP), the hardware is just memory-mapped and can be used for just data or executing code as well.

File: include/zephyr/storage/flash_map.h
Comment (JarmouniA) [inline include/zephyr/storage/flash_map.h:1]: API patch version should be incremented.

Comment (nordicjm) [reply include/zephyr/storage/flash_map.h:1]: done

File: dts/arm/nordic/nrf52840.dtsi [hunk 1]
```diff
@@ -44,7 +44,21 @@
 		};
 	};
 
+	flash0: memory@0 {
+		compatible = "soc-nv-flash";
+		erase-block-size = <4096>;
+		write-block-size = <4>;
+		reg = <0x00000000 DT_SIZE_K(1024)>;
+		ranges = <0x0 0x00000000 DT_SIZE_K(1024)>;
+		flash-peripheral-dev = <&flash_controller>;
```
Comment (erwango) [inline dts/arm/nordic/nrf52840.dtsi]: There are cases where flash controller bindings include `soc-nv-flash` and then flash node and flash controllers node are the same node. See https://github.com/zephyrproject-rtos/zephyr/blame/bdb8a8bf3035649032680545b69d0662a04b33b1/boards/nxp/mimxrt685_evk/mimxrt685_evk_mimxrt685s_cm33.dts#L264 for instance.

I'm not sure why this was made this way initially on nxp drivers, but in case of multi instance flash drivers I worked on recently in https://github.com/zephyrproject-rtos/zephyr/pull/103009, I had to use similar pattern since otherwise I had no way to retrieve `write-block-size` in flash-controller driver (required by API of flash drivers)

In those cases, this new property will lead to circular dependency, which I guess will lead to script generation issues:
```
	w25q16jvuxim: w25q16jvuxim@0 {
		compatible = "nxp,imx-flexspi-nor";
		[...]
		flash-peripheral-dev = <&w25q16jvuxim>;
		[...]
```

Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: The above is actually invalid, as can be seen from the fixed-partition files, the soc-nv-flash compatible **is** mandatory, and that is not changed here https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/devicetree/fixed-partitions.h#L86 plus things like MCUboot look specifically for this node. Anyhow from the discussions I've had with @bjarki-andreasen this wouldn't be an issue anyhow because an external flash would have 2 nodes: a flash node at the top level (which would be the soc-nv-flash node, this specifies the XIP address, write/erase block sizes) and has a reference to the other device, the other device would be the one above which would be the child node on the "flexspi" bus (which has the reg property of the underlying memory mapped flash itself - this mirrors how flash devices work anyhow whereby you have the flash memory itself, then the controller on a bus which the MCU talks to in order to read/write/erase it - they are in the same package inside of the SPI memory chip but fundamentally they are different things)

Comment (erwango) [reply dts/arm/nordic/nrf52840.dtsi]: I'm fine if this is covered, and I'm generally in line with having something that maps hw, but could you clarify the node layout you'd propose for external flash? This is not yet clear to me atm. Specially how an ext flash controller driver would retrieve node properties (as today, it is not a child node per se).

Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: here is a quick mash-up of updating the nrf5340 to do that:
```
diff --git a/boards/nordic/nrf5340dk/nrf5340dk_nrf5340_cpuapp.dts b/boards/nordic/nrf5340dk/nrf5340dk_nrf5340_cpuapp.dts
index 7c14fabd114..4808fc05c29 100644
--- a/boards/nordic/nrf5340dk/nrf5340dk_nrf5340_cpuapp.dts
+++ b/boards/nordic/nrf5340dk/nrf5340dk_nrf5340_cpuapp.dts
@@ -34,3 +34,31 @@
 
 /* Include default memory partition configuration file */
 #include <nordic/nrf5340_cpuapp_partition.dtsi>
+
+/delete-node/ &slot1_partition;
+
+/ {
+	flash2: memory@10000000 {
+		compatible = "soc-nv-flash";
+		erase-block-size = <0x1000>;
+		write-block-size = <4>;
+		reg = <0x10000000 0x100000>;
+		ranges = <0x0 0x10000000 0x100000>;
+		flash-peripheral-dev = <&mx25r64>;
+		status = "okay";
+		#address-cells = <1>;
+		#size-cells = <1>;
+
+		partitions {
+			ranges;
+			#address-cells = <1>;
+			#size-cells = <1>;
+
+			slot1_partition: partition@0 {
+				compatible = "zephyr,mapped-partition";
+				label = "image-1";
+				reg = <0x0 0x74000>;
+			};
+		};
+	};
+};
```
In here you would then have slot0 on the internal flash like normal, but slot1 on the external flash (which is memory mapped). Tested `smp_svr` with it to upload an image and update using MCUboot and the new image is booted (though note that the QSPI flash driver for this is not doing things through XIP anyway and instead uses direct register calls), `flash_map list` shows:
```
ID | Device     | Device Name               | Offset     | Size
-----------------------------------------------------------------------
 0   0x00033f7c   flash-controller@39000      0x0          0x10000       
 1   0x00033f7c   flash-controller@39000      0x10000      0x74000       
 2   0x00033f7c   flash-controller@39000      0xf8000      0x8000        
 3   0x00033f1c   mx25r6435f@0                0x0          0x74000       
```
For non-memory mapped interfaces e.g. normal SPI then the existing fixed-partitions binding would continue to be used, because the CPU doesn't have them mapped anyhow

File: scripts/dts/gen_defines.py [hunk 2]
```diff
@@ -568,7 +568,9 @@ def write_pinctrls(node: edtlib.Node) -> None:
 def write_fixed_partitions(node: edtlib.Node) -> None:
     # Macros for child nodes of each fixed-partitions node.
```
Comment (tejlmand) [inline scripts/dts/gen_defines.py]: function is named `write_fixed_partitions()` but now includes also `mapped-partitions`.

Should we perhaps keep to functions, just so we have full flexibility for future enhancement of the Zephyr specific binding.
Or perhaps rename the function to something more generic.

As minimum, comment should be updated to reflect changes.

File: include/zephyr/devicetree/fixed-partitions.h [hunk 3]
```diff
@@ -50,7 +50,9 @@ extern "C" {
  * @return a node identifier for the partition with that label property
  */
 #define DT_NODE_BY_FIXED_PARTITION_LABEL(label) \
```
Comment (tejlmand) [inline include/zephyr/devicetree/fixed-partitions.h:52]: mixing fixed partitions and mapped partitions could be limiting in future if mapped partitions evolve.

Also, having a dedicated `DT_NODE_BY_MAPPED_PARTITION_LABEL()` macro might be easier / self-explanatory for new users coming to Zephyr / those who has not been part of the fixed-partitions vs. mapped partitions discussion.

Comment also applies to other ` DT_x_FIXED_PARTITION_x` macros.

File: tests/drivers/flash/erase_blocks/src/main.c [hunk 4]
```diff
@@ -26,7 +27,7 @@ LOG_MODULE_REGISTER(test_flash);
 #endif
 
 #define TEST_FLASH_PART_OFFSET \
-	DT_REG_ADDR(TEST_FLASH_PART_NODE)
+	FIXED_PARTITION_NODE_OFFSET(TEST_FLASH_PART_NODE)
```
Comment (tejlmand) [inline tests/drivers/flash/erase_blocks/src/main.c]: using `FIXED_PARTITION_NODE_OFFSET` on what is a mapped partition has potential to be confusing to the reader / developer having to implement this.

**Review by tejlmand — CHANGES_REQUESTED** [review]
Looks good.

But as we are now introducing mapped-partitions then I think we should also introduce corresponding `DT_x_MAPPED_PARTITION_x` macros.

That will make it easier for users who have not been part of the discussion to find and use the proper macro for mapped partitions.
Also seeing mapped partitions in macro names in code will help users in knowing what to look for in corresponding devicetree files.

Under the hood, the `DT_x_MAPPED_PARTITION_x` and `DT_x_FIXED_PARTITION_x` macros can of course share implementation if that make sense.

File: include/zephyr/devicetree/fixed-partitions.h (hunk 3 above)
Comment (nordicjm) [reply include/zephyr/devicetree/fixed-partitions.h:52]: The problem with that is FIXED_PARTITION_* is widespread, it's been what zephyr has had for over 10 years, so to move away from that is possible, but then it means any usage would have to check the compatible and then either call FIXED_PARTITION_* or MAPPED_PARTITION_* (which is what the FIXED_PARTITION_* macros have been updated to do) which would need updating everywhere, for partitions that should be used in the same way

File: tests/drivers/flash/erase_blocks/src/main.c (hunk 4 above)
Comment (nordicjm) [reply tests/drivers/flash/erase_blocks/src/main.c]: this has actually always been the offset with fixed partitions since the offset macro just gets the offset from the flash node (inside of the parts using the flash device, you need an offset of the flash partition of the flash device itself, not the absolute address)

Comment (tejlmand) [reply tests/drivers/flash/erase_blocks/src/main.c]: i'm not talking about the functionality or the change of macros, only about the macro naming.

File: include/zephyr/devicetree/fixed-partitions.h (hunk 3 above)
Comment (tejlmand) [reply include/zephyr/devicetree/fixed-partitions.h:52]: or we can make a slow transition.
Introducing new `DT_x_FIXED_PARTITION_x` macros, while still support the existing use of fixed partitions macros.

Then, if / when we want we can deprecate the existing macros, because in the future afaiu we will no longer be using `fixed-partitions`.

File: boards/adafruit/feather_adalogger_rp2040/adafruit_feather_adalogger_rp2040.dts [hunk 5]
```diff
@@ -77,7 +77,6 @@
 		compatible = "fixed-partitions";
 		#address-cells = <1>;
 		#size-cells = <1>;
-		ranges;
```
Comment (kylebonnici) [inline boards/adafruit/feather_adalogger_rp2040/adafruit_feather_adalogger_rp2040.dts:80]: Should second_stage_bootloader and code_partition be mapped to address space of &flash? if so ranges should not be removed. this applies to a number of removal of range in other files. For now I will only comment on this occurrence

File: boards/nordic/nrf21540dk/nrf21540dk_nrf52840.dts [hunk 6]
```diff
@@ -273,21 +273,24 @@ fem_spi: &spi3 {
 
 &flash0 {
 	partitions {
-		compatible = "fixed-partitions";
+		ranges;
```
Comment (kylebonnici) [inline boards/nordic/nrf21540dk/nrf21540dk_nrf52840.dts:276]: should we consider 

```suggestion
		compatible = "zephyr,mapped-partitions"; // where zephyr,mapped-partitions extends fixed-partitions and makes ranges mandatory?
		ranges;
```

this way we avoid having to redefine the compatible = "zephyr,mapped-partition"; per child node

File: dts/arm/nordic/nrf52840.dtsi [hunk 7]
```diff
@@ -421,17 +437,9 @@
 
 		flash_controller: flash-controller@4001e000 {
 			compatible = "nordic,nrf52-flash-controller";
-			reg = <0x4001e000 0x1000>;
+			reg = <0x4001e000 0x1000>, <0x00000000 DT_SIZE_K(1024)>;
```
Comment (kylebonnici) [inline dts/arm/nordic/nrf52840.dtsi]: if `<0x00000000 DT_SIZE_K(1024)>` is not going to be used to:
-  derive the link between memory nodes and the controllers i.e. replace `flash-peripheral-dev` or 
- used to enforce that  any node that point to the controller using `flash-peripheral-dev` is in the range of a reg entry of this node

then I am not in favor of adding this as this will be hard to enforce and will eventually lead to inconsistent files or cases where this is out of sync and plain wrong.

File: boards/adafruit/feather_adalogger_rp2040/adafruit_feather_adalogger_rp2040.dts (hunk 5 above)
Comment (nordicjm) [reply boards/adafruit/feather_adalogger_rp2040/adafruit_feather_adalogger_rp2040.dts:80]: Note: this reverts the previous change of making them linked, to go back to the original way it was done with most boards in zephyr, not that I think it's right and not that I think based on the comments from the linux mailing list that it shouldn't be allowed, but the decision in the architecture working group was to use a new binding so that's what has been done here - this board has just has the `ranges` part reverted as part of that, it has not been moved to the new binding so adding ranges back would be part of that, for the board maintainer to do after this PR is merged

File: boards/nordic/nrf21540dk/nrf21540dk_nrf52840.dts (hunk 6 above)
Comment (nordicjm) [reply boards/nordic/nrf21540dk/nrf21540dk_nrf52840.dts:276]: No, it should be a compatible per partition, that way different compatibles can be used in future if something else is created, and it means you get a precise run in the DT_FOREACH loops and can directly identify a device with macros. If you rely on parent, or parent of parent, or parent of parent of parent... for compatibles then you have a nightmare using macrobatics to work out what the device actually is - that's fine in linux when you do that at run-time in C or using some build system magic but in zephyr with just macros it is not ok

File: dts/arm/nordic/nrf52840.dtsi (hunk 7 above)
Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: You suggest leaving this off and just having the linkage from the memory to the peripheral using a phandle?

Comment (kylebonnici) [reply dts/arm/nordic/nrf52840.dtsi]: Yes, as I fear this will end up being code debt

File: scripts/dts/gen_defines.py (hunk 2 above)
Comment (nordicjm) [reply scripts/dts/gen_defines.py]: Updated function name

File: include/zephyr/devicetree/fixed-partitions.h (hunk 3 above)
Comment (nordicjm) [reply include/zephyr/devicetree/fixed-partitions.h:52]: Added new macros and deprecated old ones

File: tests/drivers/flash/erase_blocks/src/main.c (hunk 4 above)
Comment (nordicjm) [reply tests/drivers/flash/erase_blocks/src/main.c]: As above

File: dts/arm/nordic/nrf52840.dtsi (hunk 7 above)
Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: Removed second reg values

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+      This should be in the format <OFFSET SIZE>, where OFFSET is the offset of the flash
+      partition relative to the base address of the parent memory, and SIZE is the size of the
+      partition in bytes.
+
+examples:
+  - |
+    &flash0 {
+            flash-peripheral-dev = <&flash_interface>;
+            reg = <0x00000000 DT_SIZE_K(1024)>;
+            ranges = <0x0 0x00000000 DT_SIZE_K(1024)>;
```
Comment (bjarki-andreasen) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml]: Is the flash0 here, with compatible soc-nv-flash, not always a child of the controller (flash-peripheral-dev) in this case? The phandle makes sense if the `soc-nv-flash` node is moved somewhere else, but it does not look like we are doing that. Maybe just enforce the NVM nodes are children of their controllers?

Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: I moved flash0 to the top level outside of the flash controller peripheral as per your comments, so in the dts file flash0 is top level then the flash controller is inside `soc {};` whereas in the old method the flash controller was in the same place and flash0 was a child node of the flash controller. I guess the example can be updated to remove the `&` to make it more clear

File: dts/arm/nordic/nrf52840.dtsi (hunk 1 above)
Comment (erwango) [reply dts/arm/nordic/nrf52840.dtsi]: So, IIUC, flash driver should be instanciated on base of `soc-nv-flash` compatible devices.
So it will easily access `write-block-size` as a proerty of the node itself and other properties required for the driver configuration should be accessed though phandle provided in `flash-peripheral-dev = <&mx25r64>;`, and eventually parent of this device (XSPI controller).
Looks reasonable. I need to check implementation of the actual driver instantiation more in details.

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 8 above)
Comment (bjarki-andreasen) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: Updating the sample to include
```
/ {
        flash0: flash@0 {
                ...
        };
};
```
would definitely be helpful I think.

**Comment by mbolivar** [comment]
> hal_espressif uses zephyr macros (which, to be honest, I thought hal repos were not meant to do), which have been deprecated here and would need updating

I thought this was true too but I can't find anything about it in the modules docs -- anyone else have a reference?

I know for sure that binary blobs aren't allowed to use zephyr symbols, but that's ofc a different rule.

File: scripts/dts/gen_dts_cmake.py [hunk 9]
```diff
@@ -116,17 +116,29 @@ def main():
 
     compatible2paths = defaultdict(list)
     for node in edt.nodes:
+        output_compat = False
         cmake_props.append(f'"DT_NODE|{node.path}" TRUE')
 
         for label in node.labels:
             cmake_props.append(f'"DT_NODELABEL|{label}" "{node.path}"')
 
+        if node.compats:
```
Comment (mbolivar) [inline scripts/dts/gen_dts_cmake.py]: The commit log doesn't name a specific board that led to this patch and I'd like to investigate further -- can you please give an example?

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 10]
```diff
@@ -0,0 +1,109 @@
+description: |
+  Memory-mapped partition of a flash (or other non-volatile storage) memory.
+
+  The ``zephyr,mapped-partition`` node should be children of the NVM memory node. Note also that
+  the NVM memory node is usually different from the node representing the NVM controller IP block,
+  and the NVM memory node should have a ``flash-peripheral-dev`` phandle property specifying the
+  NVM peripheral device and a ``ranges`` property specifying the full range of the NVM area
+  (usually the same as the ``reg`` property with a 0x0 prepended before the offset value). Nested
+  ``zephyr,mapped-partition`` nodes are supported, and should have ``ranges`` properties set to
+  indicate their range to their child nodes.
```
Comment (mbolivar) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml]: Unless there've been changes since I last checked, these are plain text and not rst, and therefore shouldn't use double-backticks like this

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 11]
```diff
@@ -0,0 +1,109 @@
+description: |
+  Memory-mapped partition of a flash (or other non-volatile storage) memory.
+
+  The ``zephyr,mapped-partition`` node should be children of the NVM memory node. Note also that
+  the NVM memory node is usually different from the node representing the NVM controller IP block,
+  and the NVM memory node should have a ``flash-peripheral-dev`` phandle property specifying the
```
Comment (mbolivar) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml]: I'm not aware of any such devices, but I'd like to ask the community of reviewers if we are limiting ourselves here by saying that each controller can control only one flash device. What if a single controller IP could control multiple flash memories? Is that a thing to worry about, or should we just deal with it later?

cc @erwango @anangl @nandojve @sylvioalves

File: dts/bindings/mtd/soc-nv-flash.yaml [hunk 12]
```diff
@@ -12,3 +12,10 @@ properties:
   write-block-size:
     type: int
     description: address alignment required by flash write operations
+
+  flash-peripheral-dev:
```
Comment (mbolivar) [inline dts/bindings/mtd/soc-nv-flash.yaml]: Remove `-dev`

File: dts/bindings/mtd/soc-nv-flash.yaml [hunk 13]
```diff
@@ -12,3 +12,10 @@ properties:
...
+    type: phandle
+    description: |
+      Phandle to the flash peripheral whose driver functions are used to interact with this flash
+      node. Required for devices that have partitions using the ``zephyr,mapped-partitions``
+      compatible.
```
Comment (mbolivar) [inline dts/bindings/mtd/soc-nv-flash.yaml]: Can you please try to rephrase this to be driver-agnostic? This feels like it is hardware description, not software configuration, so it shouldn't be talking about drivers.

File: scripts/dts/gen_defines.py [hunk 14]
```diff
@@ -1066,6 +1068,22 @@ def write_global_macros(edt: edtlib.EDT):
 
                         out_dt_define(macro, val)
                         out_dt_define(macro + "_EXISTS", 1)
+            elif compat == "zephyr,mapped-partition":
+                parent = node.parent
+
+                while "soc-nv-flash" not in parent.compats:
+                    parent = parent.parent
```
Comment (mbolivar) [inline scripts/dts/gen_defines.py]: The binding description at time of this review says:

```
The ``zephyr,mapped-partition`` node should be children of the NVM memory node.
```

But here, the code is referring to a specific compatible that is not documented in the binding.

I think this needs to be documented clearly so users (myself included) can understand what the intent is here.

File: include/zephyr/devicetree/mapped-partition.h [hunk 15]
```diff
@@ -0,0 +1,190 @@
+/**
+ * @file
+ * @brief Flash Devicetree macro public API header file, for memory-mapped partitions.
```
Comment (mbolivar) [inline include/zephyr/devicetree/mapped-partition.h:3]: Any new DT APIs need to be pulled into `<zephyr/devicetree.h>`; look at the bottom  of the file for what I mean

**Review by mbolivar — COMMENTED** [review]
Thank you @nordicjm -- this is looking like the right way to go from my perspective. Some initial review comments while I'm still chewing on the bulk of this.

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 11 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: It can, and that is actually the case in the nrf5340, so you can have multiple flash memories, and they each have a phandle to the same controller

File: scripts/dts/gen_defines.py (hunk 14 above)
Comment (nordicjm) [reply scripts/dts/gen_defines.py]: It is documented in the header files as those are the ones using it (mapped partition and flash map headers)

File: scripts/dts/gen_dts_cmake.py (hunk 9 above)
Comment (nordicjm) [reply scripts/dts/gen_dts_cmake.py]: With this patch:
```
diff --git a/scripts/dts/gen_dts_cmake.py b/scripts/dts/gen_dts_cmake.py
index 1c6ad65f5e7..ac6120ff91f 100755
--- a/scripts/dts/gen_dts_cmake.py
+++ b/scripts/dts/gen_dts_cmake.py
@@ -124,6 +124,7 @@ def main():
 
         if node.compats:
             # Manually output compatibles for nodes that have no properties
+            print(f"fail: {node.path}")
             cmake_value = to_cmake_list(node.compats)
 
             cmake_prop = f'DT_PROP|{node.path}|compatible'
```
configure hello_world for `nrf52840dk/nrf52840` and it gives:
```
fail: /
fail: /soc
fail: /soc/interrupt-controller@e000e100
fail: /soc/timer@e000e010
fail: /soc/ficr@10000000
fail: /soc/uicr@10001000
fail: /soc/memory@20000000
fail: /soc/clock@40000000
fail: /soc/power@40000000
fail: /soc/power@40000000/gpregret1@4000051c
fail: /soc/power@40000000/gpregret1@4000051c/boot_mode@0
fail: /soc/power@40000000/gpregret2@40000520
fail: /soc/power@40000000/regulator@40000578
fail: /soc/power@40000000/regulator@40000580
fail: /soc/radio@40001000
fail: /soc/radio@40001000/ieee802154
fail: /soc/radio@40001000/bt_hci_controller
fail: /soc/uart@40002000
fail: /soc/i2c@40003000
fail: /soc/spi@40003000
fail: /soc/i2c@40004000
fail: /soc/spi@40004000
fail: /soc/nfct@40005000
fail: /soc/gpiote@40006000
fail: /soc/adc@40007000
fail: /soc/timer@40008000
fail: /soc/timer@40009000
fail: /soc/timer@4000a000
fail: /soc/rtc@4000b000
fail: /soc/temp@4000c000
fail: /soc/random@4000d000
fail: /soc/ecb@4000e000
fail: /soc/ccm@4000f000
fail: /soc/watchdog@40010000
fail: /soc/rtc@40011000
fail: /soc/qdec@40012000
fail: /soc/comparator@40013000
fail: /soc/egu@40014000
fail: /soc/egu@40015000
fail: /soc/egu@40016000
fail: /soc/egu@40017000
fail: /soc/egu@40018000
fail: /soc/egu@40019000
fail: /soc/timer@4001a000
fail: /soc/timer@4001b000
fail: /soc/pwm@4001c000
fail: /soc/pdm@4001d000
fail: /soc/acl@4001e000
fail: /soc/flash-controller@4001e000
fail: /soc/ppi@4001f000
fail: /soc/mwu@40020000
fail: /soc/pwm@40021000
fail: /soc/pwm@40022000
fail: /soc/spi@40023000
fail: /soc/rtc@40024000
fail: /soc/i2s@40025000
fail: /soc/usbd@40027000
fail: /soc/uart@40028000
fail: /soc/qspi@40029000
fail: /soc/qspi@40029000/mx25r6435f@0
fail: /soc/pwm@4002d000
fail: /soc/spi@4002f000
fail: /soc/gpio@50000000
fail: /soc/gpio@50000300
fail: /soc/crypto@5002a000
fail: /pin-controller
fail: /entropy_bt_hci
fail: /sw-pwm
fail: /cpus/cpu@0
fail: /cpus/cpu@0/itm@e0000000
fail: /clocks/hfxo
fail: /memory@0
fail: /memory@0/partitions/partition@0
fail: /memory@0/partitions/partition@c000
fail: /memory@0/partitions/partition@82000
fail: /memory@0/partitions/partition@f8000
fail: /leds
fail: /pwmleds
fail: /buttons
fail: /connector
fail: /analog-connector
```
so the partitions are the important one here though ironically the power one is also. Also there was this one I hit also with defaults from bindings not being used: https://github.com/zephyrproject-rtos/zephyr/issues/104478

File: dts/bindings/mtd/soc-nv-flash.yaml (hunk 13 above)
Comment (nordicjm) [reply dts/bindings/mtd/soc-nv-flash.yaml]: It is needed if mapped-partitions are used so that's why I mentioned that, so I can't really make this required until all board are updated (and doing that would break out of tree boards anyway for those still using fixed-partitions). So at most I could remove the comment and just fail in the python/C code if it's not present?

File: include/zephyr/devicetree/mapped-partition.h (hunk 15 above)
Comment (nordicjm) [reply include/zephyr/devicetree/mapped-partition.h:3]: Added

File: dts/bindings/mtd/soc-nv-flash.yaml (hunk 12 above)
Comment (nordicjm) [reply dts/bindings/mtd/soc-nv-flash.yaml]: Removed

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 10 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: Replaced with single backticks

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 8 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: Sample updated

File: include/zephyr/arch/arm/cortex_m/scripts/linker.ld [hunk 16]
```diff
@@ -34,23 +34,28 @@
...
+#else
+#define ROM_ADDR (CONFIG_FLASH_BASE_ADDRESS + CONFIG_FLASH_LOAD_OFFSET)
+#endif
+
 #if CONFIG_FLASH_LOAD_SIZE > 0
 #define ROM_SIZE (CONFIG_FLASH_LOAD_SIZE - ROM_END_OFFSET)
 #else
 #define ROM_SIZE (CONFIG_FLASH_SIZE * 1024 - CONFIG_FLASH_LOAD_OFFSET - ROM_END_OFFSET)
 #endif
+#endif
```
Comment (tejlmand) [inline include/zephyr/arch/arm/cortex_m/scripts/linker.ld]: this can be tricky for the eyes to connect to original `#if` due to the nested `#if`.
```suggestion
#endif /* defined(CONFIG_FLASH_USES_MAPPED_PARTITION) */
```

File: Kconfig.zephyr [hunk 17]
```diff
@@ -99,6 +99,17 @@ config USE_DT_CODE_PARTITION
...
 DT_CHOSEN_Z_CODE_PARTITION := zephyr,code-partition
 DT_CHOSEN_Z_FLASH := zephyr,flash
+DT_COMPAT_Z_MAPPED_PARTITION := zephyr,mapped-partition
+
+config FLASH_USES_MAPPED_PARTITION
+	bool
+	default $(dt_node_has_compat,$(dt_chosen_path,$(DT_CHOSEN_Z_CODE_PARTITION)),$(DT_COMPAT_Z_MAPPED_PARTITION))
+	depends on USE_DT_CODE_PARTITION
+	help
+	  Temporary Kconfig to indicate if underlying chosen chosen flash partition uses the
```
Comment (tejlmand) [inline Kconfig.zephyr:109]: Just a slightly worry that in n-years from now we'll be looking at this text and think `Temporary, yeah right.`.

Perhaps sufficient to mention that it will be remove in future, which is already stated below..

**Review by tejlmand — DISMISSED** [review]
lgtm.

Two very minor suggestions.

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 18]
```diff
@@ -0,0 +1,126 @@
...
+    type: array
+    required: true
+    description: |
+      This should be in the format <OFFSET SIZE>, where OFFSET is the offset of the flash
+      partition relative to the base address of the parent memory, and SIZE is the size of the
+      partition in bytes.
+
+examples:
+  - |
+    flash0: memory@0 {
```
Comment (bjarki-andreasen) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml]: root memory nodes with name `memory` are reserved for volatile storage according to the dt spec, we can use `flash@0`, or `mapped-memory@0` or pretty much anything, `zephyr-memory@0` just not `memory`

Comment (bjarki-andreasen) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: I would prefer `zephyr-memory@0`

**Review by bjarki-andreasen — COMMENTED** [review]
Looks really good, one note on the naming of the root node, other than that it looks complete

File: scripts/dts/gen_dts_cmake.py (hunk 9 above)
Comment (mbolivar) [reply scripts/dts/gen_dts_cmake.py]: That example doesn't make sense to me, sorry.

I took `/soc/interrupt-controller@e000e100` as an example with this script:

```
#!/usr/bin/env python

from devicetree import edtlib
import pickle

edt = pickle.load(open("build/zephyr/edt.pickle", "rb"))
node = edt.get_node("/soc/interrupt-controller@e000e100")

print(f"{node.props['compatible']=}")
print(f"{node.compats=}")
```

and I get:

```
node.props['compatible']=Property(spec=<PropertySpec compatible type 'string-array'>, val=['arm,v7m-nvic'], node=<Node /soc/interrupt-controller@e000e100 in '/home/mbolivar/zp/zephyr/build/zephyr/zephyr.dts.pre', binding /home/mbolivar/zp/zephyr/dts/bindings/interrupt-controller/arm,v7m-nvic.yaml>)
node.compats=['arm,v7m-nvic']
```

Furthermore, it looks like commit ac348a7ab5a379468e2cace1d05cf10332980e7f back in January was making a mistake. Notice how that commit adds:

```diff
+            # Manually output compatibles for nodes that have no properties
+            cmake_value = ''
+            for val in node.compats:
+                cmake_value = f'{cmake_value}{val};'
+            cmake_prop = f'DT_PROP|{node.path}|compatible'
+            cmake_props.append(f'"{cmake_prop}" "{escape(cmake_value)}"')
```

while, for example, commit 0907a05baf062e0029f37e4601ad6715d1a2cf1a was updating `compatible2paths`, which ends up getting used in the CMake property setting:

```
    for comp in compatible2paths:
        cmake_path = to_cmake_list(compatible2paths[comp])

        cmake_comp = f'DT_COMP|{comp}'
        cmake_props.append(f'"{cmake_comp}" "{cmake_path}"')
```

lower down.

It looks like ac348a7ab5a379468e2cace1d05cf10332980e7f is maybe confusing `DT_PROP|{path}|compatible` with `DT_COMP|{compatible}`?

The commit log from that commit is:

```
scripts: dts: gen_dts_cmake: Output compatibles for no prop. nodes

Seemingly partitions (fixed-partitions) have no properties when
the edt file is loaded, work around this issue by outputting
compatibles for nodes that have them but have no properties, also
fixes some other outputs for misc. devices
```

Which feels hacky and special-case-y. The corresponding pull request https://github.com/zephyrproject-rtos/zephyr/pull/101171 doesn't have a clear write-up or an issue referenced, so it's still not clear to me what the real issue is here.

Can you please help me understand this a bit more? It feels like hacks are getting piled on top of hacks, here.

**Review by mbolivar — CHANGES_REQUESTED** [review]
I'm still bogged down on what's going on in the churn in this discussion:

https://github.com/zephyrproject-rtos/zephyr/pull/104398#discussion_r2881753451

I left details in that comment. We need to sort this out instead of just piling on more hacks.

File: include/zephyr/devicetree/mapped-partition.h
Comment (JarmouniA) [inline include/zephyr/devicetree/mapped-partition.h:1]: missing API versioning.

File: scripts/dts/gen_dts_cmake.py (hunk 9 above)
Comment (nordicjm) [reply scripts/dts/gen_dts_cmake.py]: Basically there is divergence from what you see in dts to what you see in the pickled output, so in dts (specifically with partitions), here is the base dts file and if I configure hello_world for this: https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-memory_map.dtsi#L128, in the pickled output from the commit above with your changes in October 2025, I get this:
```
...
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_PROP|/soc/mram@e000000|compatible" "nordic,mram")
...
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_NODE|/soc/mram@e000000/partitions" TRUE)
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_REG|/soc/mram@e000000/partitions|NUM" "0")
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_REG|/soc/mram@e000000/partitions|ADDR" "")
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_REG|/soc/mram@e000000/partitions|SIZE" "")
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_NODE|/soc/mram@e000000/partitions/partition@30000" TRUE)
...
```
If I switch to main, I get this:
```
...
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_PROP|/soc/mram@e000000|compatible" "nordic,mram")
...
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_NODE|/soc/mram@e000000/partitions" TRUE)
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_PROP|/soc/mram@e000000/partitions|compatible" "fixed-partitions")
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_REG|/soc/mram@e000000/partitions|NUM" "0")
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_REG|/soc/mram@e000000/partitions|ADDR" "")
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_REG|/soc/mram@e000000/partitions|SIZE" "")
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_UNIT_ADDR|/soc/mram@e000000/partitions" "NONE")
set_target_properties(${DEVICETREE_TARGET} PROPERTIES "DT_NODE|/soc/mram@e000000/partitions/partition@30000" TRUE)
...
```
Notice how in the top, the mram device has a compatible and in CMake you can get that by using the dt functions, but in the second despite there being a valid binding and the compatible being correct, the pickled output wrongly does not show a compatible for the partitions node, meaning in CMake you do not know what device it is, whilst in the second output it does, and it works like every other node. So that addressed that issues that for some reason some nodes wrongly do not have compatibles output in the pickled output, which was blocking multiple use-cases in zephyr and MCUboot.

That is not the same as `DT_COMP|` which is used to list devices that have that compatible so you can e.g. parse through them, the usage for the above is to get the compatible of a device you already know e.g. from a chosen node and aligns with the pickled output of other devices (which is not something I added)

With the fix if you do `DT_NODE_HAS_COMPAT(node, zephyr_mapped_partition)` on a `zephyr,mapped-partition` node, you get a 1, without it, you get a 0 (which would be a bug)

File: include/zephyr/arch/arm/cortex_m/scripts/linker.ld (hunk 16 above)
Comment (nordicjm) [reply include/zephyr/arch/arm/cortex_m/scripts/linker.ld]: Added

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 18 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: Changed to flash@* since don't want to encroach on the dts spec meaning of memory

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 11 above)
Comment (nandojve) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: There is the _27.Static Memory Controller (SMC)_ controller from SAM4S/E that is interesting 
https://www.microchip.com/en-us/product/atsam4e16e , it can handle SRAM, PSRAM, PROM,
EPROM, EEPROM, LCD Module, NOR Flash and NAND Flash using the EBI (External BUS Interface). I think if this one can be supported we cover a lot but maybe not everything.

I did not though too much about this binding but it came to my mind that this is some kind of generic binding `zephyr,mapped-partition` and it could be used by any memory technology like NAND, NOR, EEPROM, FRAM, SRAM, DDR etc, right?

Is there any restrictions of usage? I mean, code generation etc will be fully dedicated to NVM or this will be fully controller independent that can be used by SMC, _20.5 Enhanced Embedded Flash Controller (EEFC)_, etc and the memory technology is independent too?

Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: Anything that is memory mapped yes (I assume that controller is similar to the one in the SAMA5D31 which was fascinating to see boot directly from an SD card image recently when the NAND had a corrupt image...) though I'm unsure if things like those would be memory mapped or not. This binding doesn't deal with writing however, it can be thought of as a software part on top to limit the size of an area that the flash driver will use through flash map, and does rely on the flash device in dts having the `soc-nv-flash` compatible (which is inherited from fixed-partitions).

> Is there any restrictions of usage? I mean, code generation etc will be fully dedicated to NVM or this will be fully controller independent that can be used by SMC, 20.5 Enhanced Embedded Flash Controller (EEFC), etc and the memory technology is independent too?

There is some information in the `soc-nv-flash` binding that can be used like erase block size, write block size, erase value etc. but other that that so long as it is uses the flash device API then it should be fine (there's other memory technologies doing this like MRAM, RRAM, etc.)

File: scripts/dts/gen_defines.py [hunk 19]
```diff
@@ -1066,6 +1068,25 @@ def write_global_macros(edt: edtlib.EDT):
 
                         out_dt_define(macro, val)
                         out_dt_define(macro + "_EXISTS", 1)
+            elif compat == "zephyr,mapped-partition":
+                parent = node.parent
+
```
Comment (bjarki-andreasen) [inline scripts/dts/gen_defines.py:1073]: We could enforce "ranges" property here, something
```
if not parent.ranges:
    err(f"zephyr,mapped-partition parent node lacks ranges property: {parent.path}")
```

Comment (kylebonnici) [reply scripts/dts/gen_defines.py:1073]: @bjarki-andreasen in that case I would rather see a binding on `partitions` that makes the `ranges` required 

an alternative zephyr would add documentation and claim `partitions` as special node type that required `ranges` and that children must be of some binding type `zephyr,mapped-partition`. And extend document to keep comment from @nordicjm  in mind https://github.com/zephyrproject-rtos/zephyr/pull/104398/changes#r2870940772

I would prefer the first option as this would use existing validation tools and concepts and one does not need to reimplement this logic on other tooling to validate, visualize error etc... dts files. + IMO it improves readability for end users.

Comment (nordicjm) [reply scripts/dts/gen_defines.py:1073]: > @bjarki-andreasen in that case I would rather see a binding on partitions that makes the ranges required

I don't think such a thing is possible in a binding - note that a `partitions {}` node is actually completely optional for mapped partitions, it's provided as fixed-partitions uses it so that one can `/delete-node/ &partitions;` then remake them, but it's not needed at all for mapped partitions, or I guess one could even have multiple layers of them to delete specific groupings

Comment (kylebonnici) [reply scripts/dts/gen_defines.py:1073]: @nordicjm should we consider in binding adding some boolean enforcing that the user of this binding must ensure that the addresses are CPU mapped. This will make the below concept more generic and recursive.... 

```
if not parent.ranges:
    err(f"zephyr,mapped-partition parent node lacks ranges property: {parent.path}")
```

**Review by tejlmand — DISMISSED** [review]

**Review by bjarki-andreasen — DISMISSED** [review]
Nice work!

File: scripts/dts/gen_defines.py (hunk 19 above)
Comment (kylebonnici) [reply scripts/dts/gen_defines.py:1073]: @nordicjm @mbolivar @bjarki-andreasen PR to add a generic way to enforce CPU mapped addresses with bindings

https://github.com/zephyrproject-rtos/zephyr/pull/105093

File: dts/bindings/mtd/zephyr,mapped-partition.yaml
Comment (mathieuchopstm) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml:1]: I think there needs to be an e.g., `zephyr,mapped-partitions` that can be a  (mostly) mechanical replacement for `fixed-partitions`. It would obviously not duplicated the properties - it would just `include` this very binding inside its `child-bindings` (and/or these child binding's `child-bindings`, etc for as many levels as we want) which IIRC is possible. *this would not be a fully mechanical replacement because `ranges;` still need to be added*, but would make the migration much less of a chore in a majority of cases.

The alternative is to repeat `zephyr,mapped-partition` boilerplate everywhere - as can already be seen in this PR! - which I find wasteful and which is a regression from `fixed-partitions`.

File: dts/arm/nordic/nrf52840.dtsi [hunk 20]
```diff
@@ -44,7 +44,21 @@
 		};
 	};
 
+	flash0: flash@0 {
+		compatible = "soc-nv-flash";
+		erase-block-size = <4096>;
+		write-block-size = <4>;
```
Comment (mathieuchopstm) [inline dts/arm/nordic/nrf52840.dtsi]: How is the flash driver supposed to obtain the value of these properties (notably `write-block-size`)?

The Nordic flash driver is not affected because it straight up ignores the values:
https://github.com/zephyrproject-rtos/zephyr/blob/db95825469fd0c17fe374120bd459e499026b5a8/drivers/flash/soc_flash_nrf.c#L55-L62 

but this is certainly not the case of many other flash drivers (for `write-block-size` at least)


Also, it's a bit odd for a `soc-nv-flash` to be outside `/soc`... though the only real guideline I could find about DT structure is here: https://docs.kernel.org/devicetree/bindings/writing-bindings.html
> ### Board/SoC .dts Files
> **DO put all MMIO devices under a bus node and not at the top-level.**
> DO use non-empty ‘ranges’ to limit the size of child buses/devices. 64-bit platforms don’t need all devices to have 64-bit address and size.

which I understand as *put all MMIO devices under `/soc` rather than `/`*

File: dts/arm/nordic/nrf52840.dtsi [hunk 21]
```diff
@@ -44,7 +44,21 @@
...
+		reg = <0x00000000 DT_SIZE_K(1024)>;
+		ranges = <0x0 0x00000000 DT_SIZE_K(1024)>;
+		flash-peripheral = <&flash_controller>;
+		status = "okay";
+		#address-cells = <1>;
+		#size-cells = <1>;
+	};
+
 	soc {
+		compatible = "simple-bus";
```
Comment (mathieuchopstm) [inline dts/arm/nordic/nrf52840.dtsi:48]: Not related to the PR's core changes(?), but are you sure this is necessary? `#include <arm/armv7-m.dtsi>` should already be setting the property to this value

File: include/zephyr/arch/arm/cortex_m/scripts/linker.ld [hunk 22]
```diff
@@ -34,23 +34,28 @@
...
 #if defined(CONFIG_ROM_END_OFFSET)
 #define ROM_END_OFFSET CONFIG_ROM_END_OFFSET
 #else
 #define ROM_END_OFFSET 0
 #endif
 
+#if defined(CONFIG_FLASH_USES_MAPPED_PARTITION)
+#define ROM_ADDR (DT_REG_ADDR(DT_CHOSEN(zephyr_code_partition)))
+#define ROM_SIZE (DT_REG_SIZE(DT_CHOSEN(zephyr_code_partition)) - ROM_END_OFFSET)
+#else
```
Comment (mathieuchopstm) [inline include/zephyr/arch/arm/cortex_m/scripts/linker.ld:46]:
```suggestion
#else /* defined(CONFIG_FLASH_USES_MAPPED_PARTITION) */
```

File: Kconfig.zephyr [hunk 23]
```diff
@@ -99,30 +99,37 @@ config USE_DT_CODE_PARTITION
...
 	  a future release, check the Zephyr 4.4 migration notes.
 
 config FLASH_LOAD_OFFSET
 	# Only user-configurable when USE_DT_CODE_PARTITION is disabled
 	hex "Kernel load offset" if !USE_DT_CODE_PARTITION
-	default $(dt_chosen_reg_addr_hex,$(DT_CHOSEN_Z_CODE_PARTITION)) \
-		if FLASH_CODE_PARTITION_ADDRESS_INVALID
-	default $(sub_hex, $(dt_chosen_reg_addr_hex,$(DT_CHOSEN_Z_CODE_PARTITION)), \
-			   $(dt_chosen_reg_addr_hex,$(DT_CHOSEN_Z_FLASH))) if USE_DT_CODE_PARTITION
+	default $(dt_chosen_reg_addr_hex,$(DT_CHOSEN_Z_CODE_PARTITION)) if USE_DT_CODE_PARTITION
```
Comment (mathieuchopstm) [inline Kconfig.zephyr:131]: If I understand correctly, there's only one formula anymore because `FLASH_LOAD_OFFSET` is ignored by the ARM linker script when `FLASH_USES_MAPPED_PARTITION=y`... but what about other users? (though, there doesn't seem to be any other ***today***)

It sounds much more solid to keep handling the two cases different cases at this level and avoid arch-level hacks. Otherwise, *if this symbol becomes necessary somewhere else*, that other place will have to duplicate the hacks. And when the deprecated mechanism is eventually removed, it will also be much simpler to do if everything is done in a single place.

File: dts/arm/nordic/nrf52840.dtsi (hunk 20 above)
Comment (mathieuchopstm) [reply dts/arm/nordic/nrf52840.dtsi]: I can't edit review comments without completely breaking formatting (thanks ✨ new merge experience ✨ ) so I'll add it as tail: is there anything wrong with having the flash as a child of the flash-controller?

I do understand that currently most (all?) flash controllers are lacking an empty `ranges;` but other than that... does having them as child of the controller really cause any issue?

File: doc/releases/migration-guide-4.4.rst
Comment (mathieuchopstm) [inline doc/releases/migration-guide-4.4.rst:1]: There seems to be some things in commit `doc: release: migration_guide: 4.4: Add note on flash map` that should be squashed to `doc: release: migration_guide: 4.4: Update note on NVM change`

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 24]
```diff
@@ -0,0 +1,122 @@
...
+
+            /*
+             * The 'partitions' grouping is optional, it allows for clearing all partitions in a
+             * device (e.g. using a dtc overlay file) but is not required. If used, then it needs
+             * a `ranges;` property and to specify the #address-cells and #size-cells properties
+             */
+            partitions {
+                    ranges;
+                    #address-cells = <1>;
+                    #size-cells = <1>;
```
Comment (mathieuchopstm) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml:71]: Will this even be accepted by the Zephyr tooling... and should it? `partitions` lacks a binding now as far as I can tell

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 25]
```diff
@@ -0,0 +1,122 @@
+description: |
+  Memory-mapped partition of a flash (or other non-volatile storage) memory.
+
+  The `zephyr,mapped-partition` node should be children of the NVM memory node. Note also that
+  the NVM memory node is usually different from the node representing the NVM controller IP block,
+  and the NVM memory node should have a `flash-peripheral` phandle property specifying the
+  NVM peripheral device and a `ranges` property specifying the full range of the NVM area
+  (usually the same as the `reg` property with a 0x0 prepended before the offset value). Nested
+  `zephyr,mapped-partition` nodes are supported, and should have `ranges` properties set to
+  indicate their range to their child nodes.
```
Comment (mathieuchopstm) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml]: Wording does not take into account that this can be under a `partitions` subnode. If the proposal of `zephyr,mapped-partitionS` is not accepted, then this needs to be updated because 

> The `zephyr,mapped-partition` node should be children of the NVM memory node.

does not match half of the examples here, and pretty much every usage in the PR

File: include/zephyr/devicetree/mapped-partition.h [hunk 26]
```diff
@@ -0,0 +1,189 @@
...
+/**
+ * @brief Get the node identifier of the NVM memory for a partition.
+ * @param node_id node identifier for a zephyr,mapped-partition node.
+ * @return the node identifier of the internal memory that contains the zephyr,mapped-partition
+ *         node, or @ref DT_INVALID_NODE if it doesn't exist.
+ */
+#define DT_MEM_FROM_MAPPED_PARTITION(node_id)						\
+	COND_CODE_1(DT_NODE_HAS_COMPAT(DT_CAT(node_id, _NVM_DEVICE), soc_nv_flash),	\
+				       (DT_CAT(node_id, _NVM_DEVICE)),			\
+				       (DT_INVALID_NODE))
```
Comment (mathieuchopstm) [inline include/zephyr/devicetree/mapped-partition.h:97]: The description does not match the implementation (c.f. comment from @mbolivar here https://github.com/zephyrproject-rtos/zephyr/pull/104398#discussion_r2881769971) and my reply.

File: scripts/dts/gen_defines.py (hunk 14 above)
Comment (mathieuchopstm) [reply scripts/dts/gen_defines.py]: Where is it documented? The examples showing nodes with a `soc-nv-flash` is not "documentation": there needs to be something that explicitly says *"one of the parents must have `soc-nv-flash` compatible"*, or this constraint is not part of the API contract.

**Review by mathieuchopstm — DISMISSED** [review]
Various things together could warrant a -1, but the `write-block-size`/`erase-block-size` point deserves one by itself. *The vast majority of flash drivers in tree today* (if we are pedantic) need to consume this property, but as far as I understand, the proposal is for this property to be in a completely distinct and separate node from the one that is actually instantiated and needs the property's value.

This is the point that was raised here: https://github.com/zephyrproject-rtos/zephyr/pull/104398#discussion_r2853155754

but not really answered by @nordicjm as far as I can tell. In fact, the example given which uses `flash-peripheral-dev = <&mx25r64>;` exhibits exactly the same issue as the flash driver being migrated by this PR: ***it ignores the `erase-block-size`/`write-block-size` properties!***

https://github.com/zephyrproject-rtos/zephyr/blob/e7c454caf8192d9063b7ce1ec8497a04d11e97de/drivers/flash/nrf_qspi_nor.c#L1156-L1167

If I understand what @nordicjm suggested (my understanding is the same as @erwango, but not confirmed by @nordicjm), the proposal is to instantiate the `soc-nv-flash` node (with a new compatible) instead of the flash controller node... but this means that there would be two different ways of making flash drivers?
* `flash-controller` in `/soc` instantiated by flash driver, pointed to by a trivial `soc-nv-flash` node that is not instantiated
* `flash-controller` in `/soc` which is actually an empty shell, pointed to by a complex `"vnd,xxx-flash", "soc-nv-flash"` node that gets instantiated

This approach doesn't sound very robust nor future-proof - instead, I would expect a single approach to be defined then require everyone to stick to it. But as it is now, I don't see any clear indication of there being such a "canonical approach", so I can only assume there isn't any. If so, then what is the way forward for "non-compliant" drivers?

Note that there is at least one driver in tree which does consume its child's property so this is **NOT** a non-issue that can be brushed away:
https://github.com/zephyrproject-rtos/zephyr/blob/e7c454caf8192d9063b7ce1ec8497a04d11e97de/dts/arm/nxp/s32/nxp_s32k344_m7.dtsi#L66-L83
(note that `nxp,c40-flash` is just `soc-nv-flash` with `const` values for the erase/write block size)
https://github.com/zephyrproject-rtos/zephyr/blob/e7c454caf8192d9063b7ce1ec8497a04d11e97de/drivers/flash/flash_mcux_c40.c#L366-L374
https://github.com/zephyrproject-rtos/zephyr/blob/e7c454caf8192d9063b7ce1ec8497a04d11e97de/drivers/flash/flash_mcux_c40.c#L329

And for the record:
```
$ find drivers/flash -name *.c | wc -l
101
$ grep "write_block_size" -l drivers/flash/*.c | wc -l
79
$ grep "erase_block_size" -l drivers/flash/*.c | wc -l
38
```
Though this needs to be taken with a grain of salt because:
* internal flash drivers *can cheat and locate the flash node in another way* (in fact, many do...)
* external flash drivers cannot afford such a luxury... but a good chunk of them ignore the properties(!)

So *in practice*, there shouldn't be too many drivers that will be disturbed, but ***if we are pedantic*** a lot of drivers that should be undisturbed are "not properly implemented" today.

---

TL;DR: there is a lack of clarity about (1) how drivers should be implemented under this new model, and (2) what is the way forward for drivers that are affected by the changes brought by the new model - I think these questions should be addressed before PR is merged.

File: scripts/dts/gen_defines.py [hunk 27]
```diff
@@ -565,10 +565,12 @@ def write_pinctrls(node: edtlib.Node) -> None:
                           f"DT_{ph.z_path_id}")
 
 
-def write_fixed_partitions(node: edtlib.Node) -> None:
-    # Macros for child nodes of each fixed-partitions node.
+def write_partition_data(node: edtlib.Node) -> None:
+    # Macros for partition nodes (fixed-partitions, fixed-subpartitions, zephyr,mapped-partition)
 
-    if not (node.parent and ("fixed-partitions" in node.parent.compats or "fixed-subpartitions" in node.parent.compats)):
+    if not (node.parent and ("fixed-partitions" in node.parent.compats or \
```
Comment (etienne-lms) [inline scripts/dts/gen_defines.py]:
```suggestion
    if not (node.parent and ("fixed-partitions" in node.parent.compats or

File: include/zephyr/storage/flash_map.h
Comment (etienne-lms) [inline include/zephyr/storage/flash_map.h]: Could you update the description, here and in some of the other updated macros below.

File: include/zephyr/storage/flash_map.h [hunk 28]
```diff
@@ -404,7 +425,13 @@ uint8_t flash_area_erased_val(const struct flash_area *fa);
  *
  * @return fixed-partition address, as defined for the partition in DTS.
  */
-#define FIXED_PARTITION_NODE_ADDRESS(node) DT_REG_ADDR(node)
+#define PARTITION_NODE_ADDRESS(node)						\
+	COND_CODE_1(DT_NODE_HAS_COMPAT(node, zephyr_mapped_partition),		\
+		    (DT_MAPPED_PARTITION_OFFSET(node)),				\
```
Comment (etienne-lms) [inline include/zephyr/storage/flash_map.h]: `DT_MAPPED_PARTITION_OFFSET()` or `DT_MAPPED_PARTITION_ADDR()`?

File: include/zephyr/storage/flash_map.h [hunk 29]
```diff
@@ -448,8 +487,12 @@ uint8_t flash_area_erased_val(const struct flash_area *fa);
  *
  * @return const struct device type pointer
  */
-#define FLASH_AREA_DEVICE(label) \
-	DEVICE_DT_GET(DT_MTD_FROM_FIXED_PARTITION(DT_NODE_BY_FIXED_PARTITION_LABEL(label)))
+#define FLASH_AREA_DEVICE(label) 							\
+	COND_CODE_1(DT_NODE_HAS_COMPAT(node, zephyr_mapped_partition),			\
```
Comment (etienne-lms) [inline include/zephyr/storage/flash_map.h]:
```suggestion
	COND_CODE_1(DT_NODE_HAS_COMPAT(DT_NODELABEL(label), zephyr_mapped_partition),			\

File: include/zephyr/storage/flash_map.h [hunk 30]
```diff
@@ -458,23 +501,27 @@ uint8_t flash_area_erased_val(const struct flash_area *fa);
...
-			(DT_MTD_FROM_FIXED_PARTITION(node))))
+#define PARTITION_NODE_DEVICE(node)							\
+	COND_CODE_1(DT_NODE_HAS_COMPAT(node, zephyr_mapped_partition),			\
+		    (DEVICE_DT_GET(DT_MTD_FROM_MAPPED_PARTITION(node))),		\
+		    (DEVICE_DT_GET(COND_CODE_1(DT_FIXED_SUBPARTITION_EXISTS(node),	\
+				   (DT_MTD_FROM_FIXED_SUBPARTITION(node)),		\
+				   (DT_MTD_FROM_FIXED_PARTITION(node))))))
+
+/** Deprecated macro, replace with PARTITION_NODE_DEVICE() */
+#define FIXED_PARTITION_NODE_DEVICE(node) PARTITION_NODE_DEVICE(node __DEPRECATED_MACRO
```
Comment (etienne-lms) [inline include/zephyr/storage/flash_map.h]: Typo
```suggestion
#define FIXED_PARTITION_NODE_DEVICE(node) PARTITION_NODE_DEVICE(node) __DEPRECATED_MACRO

File: subsys/storage/flash_map/flash_map_default.c [hunk 31]
```diff
@@ -49,6 +70,24 @@ const struct flash_area *flash_map = default_flash_map;
...
  */
+#define DEFINE_PARTITION(part) DEFINE_PARTITION_1(part, DT_DEP_ORD(part))
+#define DEFINE_PARTITION_1(part, ord)								\
+	COND_CODE_1(DT_NODE_HAS_STATUS_OKAY(DT_MTD_FROM_FIXED_PARTITION(part)),			\
+		    (DEFINE_PARTITION_0(part, ord)), ())
+#define DEFINE_PARTITION_0(part, ord)								\
+	const struct flash_area DT_CAT(global_zephyr_mapped_partition_ORD_, ord) = {		\
+		.fa_id = DT_FIXED_PARTITION_ID(part),						\
+		.fa_off = FIXED_PARTITION_NODE_OFFSET(part),					\
+		.fa_dev = DEVICE_DT_GET(DT_MTD_FROM_FIXED_PARTITION(part)),			\
```
Comment (etienne-lms) [inline subsys/storage/flash_map/flash_map_default.c]: Typo?
Replace `_FIXED_PARTITION` occurrences with `_MAPPED_PARTITION`.

File: tests/lib/devicetree/api/app.overlay [hunk 32]
```diff
@@ -942,6 +942,88 @@
...
+					reg = <0x000f8000 0x00008000>;
+					ranges = <0x0 0x000f8000 0x00008000>;
+					#address-cells = <1>;
+					#size-cells = <1>;
+
+					partition@0 {
+						compatible = "zephyr,mapped-partition";
+						label = "mapped-partition-5";
+						reg = <0x00000000 0x00003000>;
+						ranges = <0x0 0x00000000 0x00003000>;
```
Comment (etienne-lms) [inline tests/lib/devicetree/api/app.overlay]: Test seems to always use a 0x0 offset (`ranges` first argument) and range parent address (2nd arg) being exactly he node 'reg` address value.
Would it make sens to check for example here: `ranges = <0x0 0x1000 0x2000>` (with subnode updated)?

`

File: subsys/secure_storage/Kconfig.its_store [hunk 33]
```diff
@@ -8,12 +8,14 @@ DT_ITS_PARTITION := $(dt_chosen_path,secure_storage_its_partition)
...
+DT_COMPAT_Z_MAPPED_PARTITION := zephyr,mapped-partition
 
 config SECURE_STORAGE_ITS_STORE_IMPLEMENTATION_ZMS
 	bool "ITS store module implementation using ZMS for storage"
 	depends on FLASH_HAS_DRIVER_ENABLED \
-	 && $(dt_path_enabled,$(DT_ITS_PARTITION)) \
-	 && $(dt_node_has_compat,$(dt_node_parent,$(DT_ITS_PARTITION)),fixed-partitions)
+		&& $(dt_path_enabled,$(DT_ITS_PARTITION)) \
+		&& ($(dt_node_has_compat,$(dt_node_parent,$(DT_ITS_PARTITION)),fixed-partitions) \
+		|| $(dt_node_has_compat,$(DT_ITS_PARTITION),$(DT_COMPAT_Z_MAPPED_PARTITION)))
```
Comment (etienne-lms) [inline subsys/secure_storage/Kconfig.its_store:18]: IMHO it would be nice to indent the last line with 4 more space chars.
Ditto for changed lines in `SECURE_STORAGE_ITS_STORE_IMPLEMENTATION_SETTINGS` below.

File: dts/bindings/mtd/zephyr,mapped-partition.yaml
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:1]: No way, `fixed-partitions` is a bad design, the compatible for mapped-partition is purposely per partition, it means you can change to a different compatible if you have something different, this was done by design

File: dts/arm/nordic/nrf52840.dtsi (hunk 20 above)
Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: > I can't edit review comments without completely breaking formatting (thanks ✨ new merge experience ✨ ) so I'll add it as tail: is there anything wrong with having the flash as a child of the flash-controller?
> 
> I do understand that currently most (all?) flash controllers are lacking an empty ranges; but other than that... does having them as child of the controller really cause any issue?

This was brought up at the architecture group call, I would suggest watching the recording there, but essentially was something @bjarki-andreasen and @henrikbrixandersen mentioned and there were no objections, it is set up this way to match the hardware since flash is memory mapped directly to the CPU and does not come through the flash controller peripheral (to read it anyway)

File: dts/arm/nordic/nrf52840.dtsi (hunk 21 above)
Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi:48]: This flattens files which have duplicate flash info, see https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/nordic/nrf52840_qfaa.dtsi and https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/nordic/nrf52840_qiaa.dtsi which then both include https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm/nordic/nrf52840.dtsi

File: Kconfig.zephyr (hunk 23 above)
Comment (nordicjm) [reply Kconfig.zephyr:131]: Kconfig is the wrong place for setting flash offsets, it's always been bad and it has been the plan to replace it with dts for years as part of the build system cleanup

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 24 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:71]: yes? A node does not need a binding to be grouping things

File: Kconfig.zephyr (hunk 23 above)
Comment (maass-hamburg) [reply Kconfig.zephyr:131]: the riscv linker uses this symbol:
https://github.com/zephyrproject-rtos/zephyr/blob/2cded8e10d4ded1573baadfd44bf68841567e943/include/zephyr/arch/riscv/common/linker.ld#L44-L83

also it has some special handling if `jedec,spi-nor` is mmaped.

I'm unsure how migration is going to work there.

File: dts/arm/nordic/nrf52840.dtsi (hunk 20 above)
Comment (bjarki-andreasen) [reply dts/arm/nordic/nrf52840.dtsi]: The way I envisioned this to be solved was to have the flash device point to the parent of zephyr,mapped-partition, (a node with binding soc-nv-flash for example), and get the write/erase block sizes like this:
```
/ {
        flash0: flash@0 {
                compatible = "soc-nv-flash";
                erase-block-size = <1024>;
                write-block-size = <4>;
                ranges <0x0 0x0 0x10000>;
                address-cells = <1>;
                size-cells = <1>;

                partition@0 {
                        compatible = zephyr,mapped-partition;
                };
                
                ...
        };
};

&flash_controller {
        ...
        memories = <&flash0 ...>;
};
```
This allows the flash controller to keep a list of the memory areas it controls, from where it can get properties relevant for each block of flash. flash_controller could point to two non consecutive areas, areas with different erase-block-size etc.

Its similar to the current approach, but this does not rely on "reverse lookup" to find the flash or other memory areas managed by the flash controller.

Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: That would not work in the stm32 case whereby there might be something like 2 16KiB sectors followed by a 32KiB sector followed by a 64KiB sector, with someone wanting to use them all as one partition. Though I would say in that case there is no difference in this PR to as it stands in main right now, neither can represent the partitions and erase/write block sizes, hence why the erase/write block sizes for those parts are just absent

Comment (JarmouniA) [reply dts/arm/nordic/nrf52840.dtsi]: > That would not work in the stm32 case whereby there might be something like 2 16KiB sectors followed by a 32KiB sector followed by a 64KiB sector, with someone wanting to use them all as one partition.

We can have multiple "soc-nv-flash" compatible nodes in that case representing each contiguous segment with the same sector size.

Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: But you cannot have a partition that spans multiple of them, the partition is the child node of the flash, it cannot be a node that spans multiple flash nodes

Comment (JarmouniA) [reply dts/arm/nordic/nrf52840.dtsi]: > But you cannot have a partition that spans multiple of them, the partition is the child node of the flash, it cannot be a node that spans multiple flash nodes

Yeah, but does it make sense to have a partition with different sector sizes?

Comment (nandojve) [reply dts/arm/nordic/nrf52840.dtsi]: I think this is not about if make sense or not. This is a problem that must be addressed. For instance, sometimes you have different sector sizes but you can align those sectors to use the same "page" like 2k or 4k to erase blocks instead use a single instruction that erase the full sector. The devices that the NVM controller does not provide that flexibility it is mandatory to align the partition with the sector.

File: Kconfig.zephyr (hunk 23 above)
Comment (nordicjm) [reply Kconfig.zephyr:131]: Yes I noticed that, I have other commits for updating the other linker scripts and CMake generator files which will be posted after this is merged, the riscv one is essentially a bunch of hacks and diverges from everything else

File: scripts/dts/gen_defines.py (hunk 14 above)
Comment (nordicjm) [reply scripts/dts/gen_defines.py]: Note: this is the same as it is in the fixed-partitions file https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/devicetree/fixed-partitions.h#L80

File: subsys/secure_storage/Kconfig.its_store (hunk 33 above)
Comment (nordicjm) [reply subsys/secure_storage/Kconfig.its_store:18]: Kconfig is tab indentation for options, not space, not aligned

File: include/zephyr/devicetree/mapped-partition.h
Comment (nordicjm) [reply include/zephyr/devicetree/mapped-partition.h:1]: I do not believe so, no other files in the devicetree folder have API versioning

File: scripts/dts/gen_defines.py (hunk 27 above)
Comment (nordicjm) [reply scripts/dts/gen_defines.py]: Fixed

File: include/zephyr/storage/flash_map.h
Comment (nordicjm) [reply include/zephyr/storage/flash_map.h]: Done

File: include/zephyr/storage/flash_map.h (hunk 28 above)
Comment (nordicjm) [reply include/zephyr/storage/flash_map.h]: Fixed

File: include/zephyr/storage/flash_map.h (hunk 29 above)
Comment (nordicjm) [reply include/zephyr/storage/flash_map.h]: Fixed

File: include/zephyr/storage/flash_map.h (hunk 30 above)
Comment (nordicjm) [reply include/zephyr/storage/flash_map.h]: Fixed

File: subsys/storage/flash_map/flash_map_default.c (hunk 31 above)
Comment (nordicjm) [reply subsys/storage/flash_map/flash_map_default.c]: Fixed

File: tests/lib/devicetree/api/app.overlay (hunk 32 above)
Comment (nordicjm) [reply tests/lib/devicetree/api/app.overlay]: Have not looked at this yet, will look later

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 25 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: I have updated the description to indicate it is a descendant node

File: doc/releases/migration-guide-4.4.rst
Comment (nordicjm) [reply doc/releases/migration-guide-4.4.rst:1]: Squashed

File: include/zephyr/arch/arm/cortex_m/scripts/linker.ld (hunk 22 above)
Comment (nordicjm) [reply include/zephyr/arch/arm/cortex_m/scripts/linker.ld:46]: the #if is 3 lines, no other #else in the file has it, I don't think that really improves readability

File: dts/bindings/mtd/zephyr,mapped-partition.yaml
Comment (mathieuchopstm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:1]: Nothing would prevent you from using `zephyr,mapped-partition` on the nodes themselves if you wanted to. But it seems most people won't need to, and having a shorthand for these people would be very valuable.

Can you elaborate on how `fixed-partitions` is a bad design (on this specific point only) because I don't see the issue?

File: dts/arm/nordic/nrf52840.dtsi (hunk 20 above)
Comment (mathieuchopstm) [reply dts/arm/nordic/nrf52840.dtsi]: > The way I envisioned this to be solved was to have the flash device point to the parent of zephyr,mapped-partition, (a node with binding soc-nv-flash for example), and get the write/erase block sizes like this:
> 
> ```
> / {
>         flash0: flash@0 {
>                 compatible = "soc-nv-flash";
>                 erase-block-size = <1024>;
>                 write-block-size = <4>;
>                 ranges <0x0 0x0 0x10000>;
>                 address-cells = <1>;
>                 size-cells = <1>;
> 
>                 partition@0 {
>                         compatible = zephyr,mapped-partition;
>                 };
>                 
>                 ...
>         };
> };
> 
> &flash_controller {
>         ...
>         memories = <&flash0 ...>;
> };
> ```

How do you get from `&flash0` to `&flash_controller` in this situation? (Reminder that adding `flash-peripheral = <&flash_controller>;` on the `&flash0` node will create a dependency loop which Zephyr currently cannot handle)

File: dts/arm/nordic/nrf52840.dtsi (hunk 21 above)
Comment (mathieuchopstm) [reply dts/arm/nordic/nrf52840.dtsi:48]: I understand that. I'm just puzzled as to why `compatible = "simple-bus"` was needed in these `nrf52840_qXXX.dtsi` files (and thus now in `nrf52840.dtsi`).

File: include/zephyr/arch/arm/cortex_m/scripts/linker.ld (hunk 22 above)
Comment (mathieuchopstm) [reply include/zephyr/arch/arm/cortex_m/scripts/linker.ld:46]: The newline between the `#endif` after `#define ROM_ADDR` and `#if CONFIG_FLASH_LOAD_SIZE > 0` makes it look like that `#endif` corresponds to the top `#if defined(USES_MAPPED_PARTITION)` when it actually corresponds to the `#if !defined(CONFIG_XIP) && (CONFIG_FLASH_SIZE==0)`. This is really confusing.

You're right that a comment on the `#else` isn't super helpful - instead, it should be a comment on the `#endif`.

File: include/zephyr/arch/arm/cortex_m/scripts/linker.ld [hunk 34]
```diff
@@ -34,23 +34,28 @@
...
+#if !defined(CONFIG_XIP) && (CONFIG_FLASH_SIZE == 0)
+#define ROM_ADDR RAM_ADDR
+#else
+#define ROM_ADDR (CONFIG_FLASH_BASE_ADDRESS + CONFIG_FLASH_LOAD_OFFSET)
+#endif
```
Comment (mathieuchopstm) [inline include/zephyr/arch/arm/cortex_m/scripts/linker.ld]:
```suggestion
#endif /* !CONFIG_XIP && CONFIG_FLASH_SIZE == 0 */
```

File: Kconfig.zephyr (hunk 23 above)
Comment (mathieuchopstm) [reply Kconfig.zephyr:131]: After reading again, nevermind, this is as I expected (and as it was before #103222) - ignore my comment.

> Yes I noticed that, I have other commits for updating the other linker scripts and CMake generator files which will be posted after this is merged, the riscv one is essentially a bunch of hacks and diverges from everything else

Why split in multiple pieces? Isn't RISC-V going to be broken then? :thinking:

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 24 above)
Comment (mathieuchopstm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:71]: It was more about having properties than having children. I know some are special-cased and always handled, but I never remember which ones...

Comment (mathieuchopstm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:71]: It was more about having properties than having children. I know some are special-cased and always handled, but I never remember which ones...

File: Kconfig.zephyr (hunk 23 above)
Comment (nordicjm) [reply Kconfig.zephyr:131]: > Why split in multiple pieces? Isn't RISC-V going to be broken then? 🤔

It isn't broken, the PR here introduces the new binding and show it working with a single single core target and with a target that has 2 flashes inside of 2 cores for a minimal introduction, I don't really want to turn what is already a very large PR of 22 commits and 199 file changes (already huge due to reverting the `fixed-partition` changes) into something which is even larger, I am still waiting 5+ days for Marti to review something which I've pinged him for to progress this so I assume when he looks at this PR he baulks at the size of it and I don't blame him, so making it even harder to get people to look at it is not really wanted...

File: dts/arm/nordic/nrf52840.dtsi (hunk 20 above)
Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: There are discussions going on (and have been for quite some time) as to how to get something here that works for Zephyr, and is also valid dts, each time an idea comes up however it might be valid dts but it has something wrong with it in that there is a missing linkage between e.g. a partition and one of the nodes, be it flash memory or flash controller, so I will see if there is something that comes out in the next few hours and if so update the whole PR, if not then I will just get rid of the changes moving the flash memory node out and that can be looked at in future (and ideally by someone else, I am fully loaded with other tasks right now and even updating this PR is having to back seat, and has already consumed a lot of time)

File: dts/bindings/mtd/zephyr,mapped-partition.yaml
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:1]: A compatible should apply to one node, not a blanket set. E.g. if you have 2 lis3dh sensors, you don't create a node with the compatible named sensors then have 2 dummy entries under it with no compatibles, you create 2 full nodes which you can then add to in overlay files or elsewhere, no difference here

File: dts/arm/nordic/nrf52840.dtsi (hunk 20 above)
Comment (nordicjm) [reply dts/arm/nordic/nrf52840.dtsi]: Right so after discussing with @bjarki-andreasen and @kylebonnici this is now back to similar to the existing topology in dts, you have a flash controller which has a flash memory child node which has a partition (or multiple) child node, the flash controller sets the ranges for the flash's memory address space, and the partition nodes inherit it, this should alleviate the problems with the above of lack of linkage

File: dts/bindings/mtd/zephyr,mapped-partition.yaml
Comment (JarmouniA) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:1]: > No way, `fixed-partitions` is a bad design, the compatible for mapped-partition is purposely per partition, it means you can change to a different compatible if you have something different, this was done by design

When you have a node with child-binding, it can have child nodes without compatibles that will follow the child-binding, AND child nodes with compatibles that will follow their own binding.
https://docs.zephyrproject.org/latest/build/dts/bindings-syntax.html#child-binding

Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:1]: which is fine for things that want to use it, not for these though

**Comment by nordicjm** [comment]
@erwango @mbolivar @tejlmand @bjarki-andreasen @mathieuchopstm @etienne-lms please review, compliance error is due to formatting and will be fixed when other repo commits are merged

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 35]
```diff
@@ -0,0 +1,132 @@
...
+    type: array
+    required: true
+    description: |
+      This should be in the format <OFFSET SIZE>, where OFFSET is the offset of the flash
+      partition relative to the base address of the parent memory, and SIZE is the size of the
+      partition in bytes.
+
+examples:
+  - |
+    flash_controller: flash-controller@4001e000 {
```
Comment (bjarki-andreasen) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml:51]: Maybe add a comment here indicating that this is an example of an NVM controller
```
/*
 * The NVM controller node defines the ranges which map the NVM memory nodes to the CPU address
 * space.
 */
flash_controller: flash-controller@4001e000 {
```

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 36]
```diff
@@ -0,0 +1,132 @@
...
+            reg = <0x4001e000 0x1000>
+            ranges = <0x0 0x0 DT_SIZE_K(1024)>, <0x10000000 0x10000000 DT_SIZE_K(256)>;
+            #address-cells = <1>;
+            #size-cells = <1>;
+
+            flash0: flash@0 {
```
Comment (bjarki-andreasen) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml:66]:
```
/*
 * An NVM memory node describes a consecutive block of non volatile physical memory.
 * Partitions are added to the this node, adhering to physical limitations like write-block-size.
 * An empty `ranges;` property is required to ensure any partition added to the NVM memory is mapped
 * correctly, and a nodelabel should be defined make it easier for applications to add add partitions to the
 * NVM memory node.
 */
flash0: flash@0 {
```

**Review by bjarki-andreasen — COMMENTED** [review]
see comments

**Review by tejlmand — DISMISSED** [review]

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 36 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:66]: Updated

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 35 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:51]: Updated

**Review by bjarki-andreasen — DISMISSED** [review]

File: dts/bindings/mtd/zephyr,mapped-partition.yaml
Comment (mathieuchopstm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:1]: > A compatible should apply to one node, not a blanket set.

OK

> E.g. if you have 2 lis3dh sensors, you don't create a node with the compatible named sensors then have 2 dummy entries under it with no compatibles, you create 2 full nodes which you can then add to in overlay files or elsewhere, no difference here

There is still a difference here because `partitions` is not an empty node (it has properties). But fine...

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 37]
```diff
@@ -0,0 +1,144 @@
...
+      partition in bytes.
+
+examples:
+  - |
+    /*
+     * The NVM controller node defines the ranges which map the NVM memory nodes to the CPU address
+     * space.
+     */
+    flash_controller: flash-controller@4001e000 {
+            reg = <0x4001e000 0x1000>
```
Comment (mathieuchopstm) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml:53]: Maybe this could have: `compatible = "vnd,flash-controller"` - must say I haven't looked at other generic bindings so maybe not

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 38]
```diff
@@ -0,0 +1,144 @@
...
+            /*
+             * An NVM memory node describes a consecutive block of non volatile physical memory.
+             * Partitions are added to the this node, adhering to physical limitations like
+             * write-block-size. An empty `ranges;` property is required to ensure any partition
+             * added to the NVM memory is mapped correctly to the CPU address space, and a
+             * nodelabel should be defined make it easier for applications to add add partitions
+             * to the NVM memory node.
+             */
+            flash0: flash@0 {
+                    reg = <0x0 DT_SIZE_K(1024)>;
```
Comment (mathieuchopstm) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml:68]: And maybe these could have `compatible = "soc-nv-flash"` since that's what they should be.

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 39]
```diff
@@ -0,0 +1,144 @@
...
+
+examples:
+  - |
+    /*
+     * The NVM controller node defines the ranges which map the NVM memory nodes to the CPU address
+     * space.
+     */
+    flash_controller: flash-controller@4001e000 {
+            reg = <0x4001e000 0x1000>
+            ranges = <0x0 0x0 DT_SIZE_K(1024)>, <0x10000000 0x10000000 DT_SIZE_K(256)>;
```
Comment (mathieuchopstm) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml]: I would expect these to be on `flash0`/`flash1` instead to be more in line with DT Spec (having `ranges;` here says *"the `flash0` and `flash1` nodes are on the same bus as `flash-controller`"*, and `ranges = <0x0 0xREGADDR DT_SIZE_K(...)>;` on each flash memory node says *"the partition at `partition offset 0` (new address space) is at physical address `0xREGADDR` (on common parent bus of `flash0` and `flash-controller`)"*)

File: doc/releases/release-notes-4.4.rst [hunk 40]
```diff
@@ -401,6 +401,10 @@ New Drivers
     (:github:`101926`)
   * :dtcompatible:`nxp,ocotp` (:github:`102567` & :github:`103089`)
 
+* Partitions
+
+  * Added new :dtcompatible:`zephyr,mapped-partition` compatible for memory-mapped partitions.
```
Comment (mathieuchopstm) [inline doc/releases/release-notes-4.4.rst]: Nit: add
```
(:github:`104398`)
```

**Review by mathieuchopstm — COMMENTED** [review]
Blocking comments addressed. The way forward is now clear:
* add `ranges` on flash controllers such that the children (=flash memory nodes) are in the global address space
* add `ranges` on flash memory nodes such that the children (=partitions) are in the global address space (possibly adding a `ranges;` + `#address-cells` on the empty intermediary `partitions` node)
* no change in drivers since no change in DT layout

A few nits but otherwise LGTM

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 39 above)
Comment (bjarki-andreasen) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: I can see that make sense, this way the flash0 / flash1 nodes can be in any (or none) address space of the controller, be that page offset or something, while the children of flash0 (the partitions) are placed in the global address space.

Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: Added distinct ranges

File: doc/releases/release-notes-4.4.rst (hunk 40 above)
Comment (nordicjm) [reply doc/releases/release-notes-4.4.rst]: Added

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 38 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:68]: Good idea, added

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 37 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml:53]: Also good, added

File: dts/bindings/mtd/zephyr,mapped-partition.yaml [hunk 41]
```diff
@@ -0,0 +1,147 @@
...
+                                    reg = <0xf8000 0x8000>;
+                                    status = "disabled";
+                             };
+                    };
+            };
+
+            flash1: flash@10000000 {
+                    compatible = "soc-nv-flash"
+                    reg = <0x10000000 DT_SIZE_K(256)>;
+                    ranges = <0x10000000 0x10000000 DT_SIZE_K(256)>;
```
Comment (mathieuchopstm) [inline dts/bindings/mtd/zephyr,mapped-partition.yaml]: Shouldn't it be `ranges = <0x0 0x10000000 DT_SIZE_K(256)>;`:
```dts
ranges = <0x0 /* "address" 0 in "partition offset" address space... */
          0x10000000 /* ...is accessible @ address 0x1000'0000 in parent address */
          DT_SIZE_K(256)>;
```

This would match the description of the binding too:
> Note that the NVM memory node and NVM controller nodes must have `ranges` properties [...] (usually the same as the `reg` property with a 0x0 prepended before the offset value).

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 39 above)
Comment (mathieuchopstm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: I think `ranges;` on the flash controller would be sufficient

**Review by mathieuchopstm — COMMENTED** [review]
Otherwise LGTM

**Review by tejlmand — DISMISSED** [review]

File: dts/bindings/mtd/zephyr,mapped-partition.yaml (hunk 41 above)
Comment (nordicjm) [reply dts/bindings/mtd/zephyr,mapped-partition.yaml]: Fixed both points

**Review by tejlmand — DISMISSED** [review]

**Review by mathieuchopstm — DISMISSED** [review]

File: scripts/dts/gen_defines.py [hunk 42]
```diff
@@ -1066,6 +1068,25 @@ def write_global_macros(edt: edtlib.EDT):
...
+                out_comment("parent NVM identifier:")
+                out_dt_define(f"{node.z_path_id}_NVM_DEVICE", f"DT_{parent.z_path_id}")
+
+                if "label" in node.props:
+                    label = node.props["label"].val
+                    macro = f"COMPAT_{str2ident(compat)}_LABEL_{str2ident(label)}"
+                    val = f"DT_{node.z_path_id}"
+
+                    out_dt_define(macro, val)
+                    out_dt_define(macro + "_EXISTS", 1)
```
Comment (mathieuchopstm) [inline scripts/dts/gen_defines.py:1089]: Per SonarQube analysis:
```suggestion
                    out_dt_define(macro + "_EXISTS", "1")
```

**Review by bjarki-andreasen — DISMISSED** [review]

File: include/zephyr/devicetree/mapped-partition.h
Comment (JarmouniA) [reply include/zephyr/devicetree/mapped-partition.h:1]: fair #105486

File: Kconfig.zephyr [hunk 43]
```diff
@@ -99,30 +99,37 @@ config USE_DT_CODE_PARTITION
...
+	  fixed-partitions and should not be relied upon outside of the zephyr build system and
+	  will be removed in future.
+
+config FLASH_CODE_PARTITION_USING_FIXED_PARTITIONS
+	bool
+	default y if XIP && \
+		$(dt_chosen_has_compat,$(dt_node_parent,$(dt_chosen_path,$(DT_CHOSEN_Z_CODE_PARTITION))),fixed-partitions) || \
+		$(dt_chosen_has_compat,$(dt_node_parent,$(dt_chosen_path,$(DT_CHOSEN_Z_CODE_PARTITION))),fixed-subpartitions)
 	depends on USE_DT_CODE_PARTITION
 	select DEPRECATED
```
Comment (henrikbrixandersen) [inline Kconfig.zephyr]: I think we need to wait with deprecating this until after all in-tre boards have been migrated away from using fixed-partitions. Otherwise we'll ship with boards triggering a deprecation warning.

Comment (nordicjm) [reply Kconfig.zephyr]: Have un-deprecated this

File: scripts/dts/gen_defines.py (hunk 42 above)
Comment (nordicjm) [reply scripts/dts/gen_defines.py:1089]: Will fix in a separate PR

**Review by mbolivar — DISMISSED** [review]

**Review by mbolivar — APPROVED** [review]

**Review by maass-hamburg — APPROVED** [review]

**Review by kylebonnici — APPROVED** [review]
LGTM

**Review by henrikbrixandersen — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]
