### PR TITLE
drivers: regulator: common: apply startup_delay when enabled at boot

### LINKED ISSUE #102508: drivers: regulator: fixed: drivers.regulator.fixed fails
### Describe the bug

Test `tests/drivers/regulator/fixed/drivers.regulator.fixed`  fails.

Observed for: 
- `nrf52840dk/nrf52840`
- `nrf5340dk/nrf5340/cpuapp`
- `nrf9160dk@0.14.0/nrf9160`

### Regression

- [x] This is a regression.

### Steps to reproduce

1. have `nrf52840dk/nrf52840` connected
2. go to your zephyr dir
3. call `./scripts/twister -s drivers.regulator.fixed -p nrf52840dk/nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs --west-flash="--erase" --fixture gpio_loopback`
4. See console output with error

### Relevant log output

```shell
*** Booting Zephyr OS build v4.3.0-3938-ga600317285ff ***
Running TESTSUITE regulator_fixed
===================================================================
START - test_enable_disable

    Assertion failed at zephyr/tests/drivers/regulator/fixed/src/main.c:25: regulator_fixed_test_enable_disable: k_uptime_get() >= startup_delay_ms is false

 FAIL - test_enable_disable in 0.017 seconds
===================================================================
TESTSUITE regulator_fixed failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -   0.00% [regulator_fixed]: pass = 0, fail = 1, skip = 0, total = 1 duration = 0.017 seconds
 - FAIL - [regulator_fixed.test_enable_disable] duration = 0.017 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: 91837146802f189b9fd5ba6d085f22fc
PROJECT EXECUTION FAILED
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: Ubuntu 20.04.1 LTS
- Toolchain Zephyr SDK 0.17.0
- Commit SHA or Version used: a600317285ff82884055c2135a2ec39af7d42191

### Additional Context

Probably introduced by: https://github.com/zephyrproject-rtos/zephyr/commit/9c3b2f06489f05251461c2b979e1d12db06fd38d

### PR DESCRIPTION
**Pull request by mohittalwar23**
When a regulator is configured with regulator-boot-on, commit e572a6f7c6f
changed regulator_fixed and regulator_gpio to configure the GPIO pin as
GPIO_OUTPUT_ACTIVE during init, then pass is_enabled=true to
regulator_common_init().

This causes the startup_delay_us to be silently skipped since the delay
only exists in the else-if branch, never reached when is_enabled=true.

Fixes #102508

### CODE REVIEW

File: drivers/regulator/regulator_common.c [hunk 1]
```diff
@@ -89,6 +89,7 @@ int regulator_common_init(const struct device *dev, bool is_enabled)
 		if ((config->flags & REGULATOR_BOOT_OFF) != 0U) {
 			return regulator_disable(dev);
 		}
+		regulator_delay(config->startup_delay_us);
```
Comment (seov-nordic) [inline drivers/regulator/regulator_common.c]: This is a neat fix for the issue this PR addresses, but I am unsure if it is generally good 🤔 
You see, the regulator might already be enabled before any of the init code (both common and the specific regulator above it) is executed, whether by a bootloader or in hardware on startup. In that case, adding delay here wouldn't make sense.

I am unsure though how else #102508 could be solved other than forcing a delay whenever the regulator stays/gets enabled. But since it affects only `regulator-fixed` and `regulator-gpio` (stemming from not knowing the current regulator state due to GPIO limitations) I think we'd be better off adding that delay to those only?

```c
if (should_enable && cfg->common.startup_delay_us > 0U) {
	k_usleep(cfg->common.startup_delay_us);
}
```

Comment (mohittalwar23) [reply drivers/regulator/regulator_common.c]: Thanks for the review @seov-nordic.

You raise a valid concern about the general case. However in the current 
codebase, `is_enabled=true` is only passed by `regulator_fixed` and 
`regulator_gpio` after they themselves configure the GPIO as 
`GPIO_OUTPUT_ACTIVE` — so the delay is relevant there.

That said, I understand the concern about future drivers. I can move the 
delay to `regulator_fixed.c` and `regulator_gpio.c` directly as you 
suggested:
```c
if (should_enable && cfg->common.startup_delay_us > 0U) {
    k_usleep(cfg->common.startup_delay_us);
}
```

Would you prefer that approach? Happy to update the PR.

Comment (seov-nordic) [reply drivers/regulator/regulator_common.c]: > However in the current codebase, `is_enabled=true` is only passed by `regulator_fixed` and `regulator_gpio`

This isn't true. See, for example, https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/regulator/regulator_npm13xx.c#L718, where `enabled` might be true (already enabled in HW on startup, by bootloader, etc.). In this case the delay you added in `regulator_common` is redundant.

I'd prefer you do the changes in the affected drivers (fixed, gpio) rather than common, yes, thanks :)

Comment (mohittalwar23) [reply drivers/regulator/regulator_common.c]: Moved the startup delay from regulator_common.c into
regulator_fixed.c and regulator_gpio.c directly.

 The delay now applies only where we know the GPIO
was just actively configured, not in the shared common path where
the regulator may already have been enabled by hardware or a bootloader.

**Review by seov-nordic — APPROVED** [review]

**Review by nordic-auko — APPROVED** [review]
