### PR TITLE
LwM2M float32/64 formatting fixes

### LINKED ISSUE #16154: Fix various issues with handling of floating values within the LWM2M subsystem
**Describe the bug**
- Regardless of its representation (_TLV_, _JSON_), it's not possible to pass a value > -1.0 and < 0.0 (ex: -0.5).  There's no _sign_ field in the [_float32_value_](https://github.com/zephyrproject-rtos/zephyr/blob/master/include/net/lwm2m.h#L345) and [_float64_value_](https://github.com/zephyrproject-rtos/zephyr/blob/master/include/net/lwm2m.h#L358) so the only way to represent a value such as -0.5 is :
```c
struct float32_value lFloatValue; /* val1  and val2 are integers (s32_t) */
lFloatValue.val1 = 0;
lFloatValue.val2 = -500000;
```
However [only the sign of _val1_ is considered for _TLV_](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/lwm2m/lwm2m_util.c#L79) while the _JSON_ representation simply formats the value as [_("%d.%d",lFloatValue.val1, lFloatValue.val2)_](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/lwm2m/lwm2m_rw_json.c#L500) ("0.-500000") thus resulting in an exception when attempting to parse the value on the other side.
- Using the _JSON_ representation it is not possible to represent a value with leading zeroes for _val2_ (ex: 0.05). Indeed as such value should be reprensented as:
```c
struct float32_value lFloatValue; /* val1  and val2 are integers (s32_t) */
lFloatValue.val1 = 0;
lFloatValue.val2 = 50000; /* 0.05*1000000 */
```
However as previously stated the value will simply end up being formated as [_("%d.%d",lFloatValue.val1, lFloatValue.val2)_](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/lwm2m/lwm2m_rw_json.c#L500) ("0.500000" instead of "0.050000")
- At least some mantissas are one bit too short using the TLV reprensentation. Trying the represent 0.05 (0x3D4CCCCD using IEEE 754 single precision) ends up as 0.049999997 (0x3D4CCCCC) on the other side

**To Reproduce**

- Use the _Leshan_ lwm2m server demo as the server backend
```bash
wget https://hudson.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/leshan-server-demo.jar
sudo java -jar ./leshan-server-demo.jar -wp 80
```
- Select _Single-value_ in the top right drop-down menu as _JSON_ or _TLV_ based on the test case
- Use the zephyr lwm2m client example and change the value of the temperature object as described by the following cases:

| Representation  | val1 | val2 | Expected value | Value retrieved by _Leshan_ |
| ------------- | ------------- | ------------- |------------- |------------- |
| _TLV_  | 0  | -500000 | -0.5 | 0.5 |
| _JSON_ | 0  | -500000 | -0.5 | Exception |
| _JSON_ | 0  | 50000 | 0.05 | 0.5 |
| _TLV_  | 0  | 50000 | 0.05 | 0.049999997 |

### PR DESCRIPTION
**Pull request by mike-scott**
- Fix plain text formatting of float32/64 to handle decimal portion and val2 negative sign correctly.
- JSON now uses the same float32/64 handling as plain text
- Fix TLV float32/64 to handle negative val2 when val1 is 0.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/16154

### CODE REVIEW

File: subsys/net/lib/lwm2m/lwm2m_rw_plain_text.c [hunk 1]
```diff
@@ -125,16 +125,50 @@ static size_t put_float32fix(struct lwm2m_output_context *out,
 			     struct lwm2m_obj_path *path,
 			     float32_value_t *value)
 {
-	return plain_text_put_format(out, "%d.%d",
-				     value->val1, value->val2);
+	size_t len;
+	char buf[sizeof("000000\n")]; /* account for nul */
```
Comment (jukkar) [inline subsys/net/lib/lwm2m/lwm2m_rw_plain_text.c]: What the "account for nul" means here? Note that the sizeof("...") automatically adds +1 for \0

**Review by jukkar — APPROVED** [review]
LGTM

**Review by ioannisg — APPROVED** [review]
