### PR TITLE
Bluetooth: ascs: Fix ASE Codec Config PDU length validation

### LINKED ISSUE #55747: Bluetooth: ascs: Invalid number of ASEs returned in error response - expected 0xFF
**Describe the bug**
In the test case `test_sink_ase_codec_configure_invalid_length_2` the ASE Control Operation is performed with number of ASEs 0x01 while the parameter arrays passed by client exceed it. As per spec:
 ```
ASCS_v1.0; 5 ASE Control operations
"A client-initiated ASE Control operation shall be defined as an invalid length operation(...)
 if the Number_of_ASEs parameter value does not match the number of parameter arrays written by
 the client"
```

**To Reproduce**
1. fetch this PR: https://github.com/zephyrproject-rtos/zephyr/pull/55229
2. Run `./scripts/twister -v -T tests/bluetooth/audio/ascs --enable-valgrind` 
4. See error `FAIL - [ascs_ase_control_test_suite.test_sink_ase_codec_configure_invalid_length_2] duration = 0.000 seconds`

**Expected behavior**
Test shall pass.

**Actual output**
The `Number_of_ASEs` returned in error is set to `0x01` which is not compliant with specification

### LINKED ISSUE #55748: Bluetooth: ascs: Invalid number of ASEs returned in error response - expected 0xFF #2
**Describe the bug**
In the test case `test_sink_ase_codec_configure_invalid_length_4` the ASE Control Operation is performed with number of ASEs 0x01 while there are more data past declared codec specific configuration. As per spec:

```
 *  ASCS_v1.0; 5 ASE Control operations
 *  "A client-initiated ASE Control operation shall be defined as an invalid length operation
 *   if the total length of all parameters written by the client is not equal to the total length
 *   of all fixed parameters plus the length of any variable length parameters for that operation"
```

**To Reproduce**
1. fetch this PR: https://github.com/zephyrproject-rtos/zephyr/pull/55229
2. Run `./scripts/twister -v -T tests/bluetooth/audio/ascs --enable-valgrind` 
4. See error `FAIL - [ascs_ase_control_test_suite.test_sink_ase_codec_configure_invalid_length_4] duration = 0.000 seconds`

**Expected behavior**
Test shall pass.

**Actual output**
The `Number_of_ASEs` returned in error is set to `0x01` which is not compliant with specification

### PR DESCRIPTION
**Pull request by MariuszSkamra**
This moves ASE Control PDU length validation before request processing.
If the PDU length is not as expected, the operation shall be considered as invalid. Thus shall be rejected.

ASCS_v1.0; 5 ASE Control operations
"A client-initiated ASE Control operation shall be defined as an
 invalid length operation if the total length of all parameters
 written by the client is not equal to the total length of all
 fixed parameters plus the length of any variable length
 parameters for that operation"

Fixes: #55747
Fixes: #55748

### CODE REVIEW

**Review by sjanc — DISMISSED** [review]

File: subsys/bluetooth/audio/ascs.c [hunk 1]
```diff
@@ -1564,46 +1564,71 @@ int bt_ascs_config_ase(struct bt_conn *conn, struct bt_bap_stream *stream, struc
...
+
+	if (!codec_config_len_is_valid(buf)) {
+		return BT_GATT_ERR(BT_ATT_ERR_INVALID_ATTRIBUTE_LEN);
+	}
+
+	req = net_buf_simple_pull_mem(buf, sizeof(*req));
+
+	LOG_DBG("num_ases %u", req->num_ases);
+
+	for (i = 0; i < req->num_ases; i++) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/ascs.c:1626]: Since this line is already "modified" by the commit, suggest to do 

```suggestion
	for (uint8_t i = 0U; i < req->num_ases; i++) {
```

**Review by Thalley — DISMISSED** [review]

**Review by Thalley — APPROVED** [review]

**Review by sjanc — APPROVED** [review]
