### PR TITLE
driver: timer: npcx: fix dead code flow for K_TICKS_FOREVER.

### LINKED ISSUE #33018: [Coverity CID :219677] Logically dead code in drivers/timer/npcx_itim_timer.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/drivers/timer/npcx_itim_timer.c

Category: Control flow issues
Function: `npcx_itim_start_evt_tmr_by_tick`
Component: Drivers
CID: [219677](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=219677)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/drivers/timer/npcx_itim_timer.c#L142

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by MulinChao**
Fix dead code flow if ticks is K_TICKS_FOREVER. Please refer [issue 33018](https://github.com/zephyrproject-rtos/zephyr/issues/33018) for more detail.

Fixes #33018 

Signed-off-by: Mulin Chao <mlchao@nuvoton.com>

### CODE REVIEW

**Review by keith-zephyr — APPROVED** [review]

**Comment by MulinChao** [comment]
Hi All:
This PR is fixing the coverity issue related to dead code. Any comment is appreciated. Thanks.

File: drivers/timer/npcx_itim_timer.c [hunk 1]
```diff
@@ -134,7 +134,7 @@ static int npcx_itim_start_evt_tmr_by_tick(int32_t ticks)
 	 * Get desired cycles of event timer from the requested ticks which
 	 * round up to next tick boundary.
 	 */
-	if (ticks <= 0) {
+	if (ticks <= 0 && ticks != K_TICKS_FOREVER) {
 		ticks = 1;
 	}
```
Comment (jackrosenthal) [inline drivers/timer/npcx_itim_timer.c:140]: it seems this could be expressed cleaner by moving to the if/else branches below:

```
if (ticks == K_TICKS_FOREVER) {
...
} else {
        if (ticks <= 0) {
                ticks = 1;
         }
...
}
```

**Review by jackrosenthal — APPROVED** [review]

File: drivers/timer/npcx_itim_timer.c (hunk 1 above)
Comment (MulinChao) [reply drivers/timer/npcx_itim_timer.c]: Indeed. It looks cleaner. I will modify it later.

Comment (MulinChao) [reply drivers/timer/npcx_itim_timer.c]: Done.
