### PR TITLE
modules: lvgl: retain last event for button/pointer device

### LINKED ISSUE #62512: lvgl input driver returning key-off immediately after key-on
**Describe the bug**

The new input driver code has a non blocking call to get data off the queue (https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/lvgl/input/lvgl_common_input.c#L19), but does not check if the queue was empty. The LVGL callback has no way of detecting that the new data is invalid either, so in practice for touch events this result in the touch getting detected and immediately released in the subsequent call. This also means that dragging across the screen does not work.

The kscan lvgl driver was handling this correctly, by keeping a local copy of the last event and giving it back to the callback if no new data was available.

lvgl_input_read_cb should be modified to behave in a similar way, saving a copy of the last valid message in the common structure and reusing it if ``k_msgq_get returns with no messages available.

@faxe1008 do you have time to look into this? Sent you some more details on discord too.

Thanks!!

**To Reproduce**
Build the lvgl sample, touch and hold the button, the button press animation is suppressed after one frame, the button should stay highlighted until release.

### LINKED ISSUE #62754: lvgl: Input subsys port possibly not working as expected.
**Describe the bug**
- Scrolling a list of items sometimes triggers unexpected/accidental clicks on the items in the list.
- I think there is a bug/problem in the input port that feeds LVGL with touch input.
- Possibly due to the change from kscan to input subsys.

Initially I had the issue using the `input_cst816s.c` but I can also reproduce the issue in `native_posix` using SDL, so it's likely not a driver issue.

I have made modifications to the https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/display/lvgl sample in order to reproduce. Just replace the [main.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/display/lvgl/src/main.c) with [this main.c](https://gist.github.com/jakkra/1e75712a8ed69645351b0fc5684137d8)

I have tested this sample application using:
- Zephyr 3.4.0 (LVGL 8.2.0) => Working as expected
- Zephyr (almost main 4cf5d5cf8b84221310677706441b9324d04521d7) (LVGL 8.3.7) => **Not** working as expected
- LVGL PC Simulator (LVGL 8.3.7) => Working as expected

The above tests does indicate the issue is not in the updated LVGL version, but in the Zephyr port.
My suspicion is that it's due to the new input subsys that replaced kscan for LVGL input handling, but it's more of a guess. 

One random idea/guess is that in the new input subsys it's feeding X, Y and button press as three different events and not as one, maybe this could cause LVGL to think there was a click? https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/input/input_sdl_touch.c#L25-L27

**To Reproduce**
1. Replace main.c in https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/display/lvgl [with this main.c](https://gist.github.com/jakkra/1e75712a8ed69645351b0fc5684137d8)
2. west build -b native_posix
3. west build -t run
4. Use your mouse and scroll the list. Notice the behavior of clicks during scrolling.

**Expected behavior**
No clicks triggering on list items during scrolling of the list.

**Impact**
LVGL not working good for input on main

**Logs and console output**
Here is a screen recording of the three different versions listed above.
First thing I do is to click on a list item, after than I only scroll the list. Expected behaviour is one initial print of a item click.
[Screencast from 2023-09-18 00:44:42.webm](https://github.com/zephyrproject-rtos/zephyr/assets/4318648/6412d123-1eb9-4ed7-8dc3-f16a21a84bd9)

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.16.1
 - Commit SHA or Version used: 4cf5d5cf8b84221310677706441b9324d04521d7

**Additional context**
Note that LVGL input does not work on current main due to https://github.com/zephyrproject-rtos/zephyr/issues/62753, so test with the commit I specified as that's before the breaking change.

### PR DESCRIPTION
**Pull request by faxe1008**
Adds saving of the last lv_indev_data_t for button and pointer type devices. This is needed because there is currently no way to tell LVGL in the read callback that no event is pending. Preservation of the last state is expected to happen in the port layer for the input devices. This resolves issue #62512 (and also: #62754)

The encoder device does not need buffering of the last event, it is expected that the `enc_diff` field on the `lv_indev_data_t` is zero if the encoder was not moved.

**Note**: To sensibly test this first [issues/62753](https://github.com/zephyrproject-rtos/zephyr/issues/62753) needs to be addressed (changing of the init level of the devices).

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/62512
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/62754

### CODE REVIEW

**Comment by faxe1008** [comment]
@jakkra Can you also please verify that your issue (#62756), is fixed by this? You need to patch back the init levels for the devices tho:

```
diff --git a/modules/lvgl/input/lvgl_button_input.c b/modules/lvgl/input/lvgl_button_input.c
index cda8b04c74..f76ab2f37b 100644
--- a/modules/lvgl/input/lvgl_button_input.c
+++ b/modules/lvgl/input/lvgl_button_input.c
@@ -102,7 +102,7 @@ static int lvgl_button_input_init(const struct device *dev)
 	};                                                                                         \
 	static struct lvgl_button_input_data lvgl_button_input_data_##inst;                        \
 	DEVICE_DT_INST_DEFINE(inst, lvgl_button_input_init, NULL, &lvgl_button_input_data_##inst,  \
-			      &lvgl_button_input_config_##inst, POST_KERNEL,                       \
+			      &lvgl_button_input_config_##inst, APPLICATION,                       \
 			      CONFIG_LV_Z_INPUT_INIT_PRIORITY, NULL);

 DT_INST_FOREACH_STATUS_OKAY(LVGL_BUTTON_INPUT_DEFINE)
diff --git a/modules/lvgl/input/lvgl_encoder_input.c b/modules/lvgl/input/lvgl_encoder_input.c
index caa8ced1b8..26a2724ccb 100644
--- a/modules/lvgl/input/lvgl_encoder_input.c
+++ b/modules/lvgl/input/lvgl_encoder_input.c
@@ -74,7 +74,7 @@ static int lvgl_encoder_input_init(const struct device *dev)
 	};                                                                                         \
 	static struct lvgl_common_input_data lvgl_common_input_data_##inst;                        \
 	DEVICE_DT_INST_DEFINE(inst, lvgl_encoder_input_init, NULL, &lvgl_common_input_data_##inst, \
-			      &lvgl_encoder_input_config_##inst, POST_KERNEL,                      \
+			      &lvgl_encoder_input_config_##inst, APPLICATION,                      \
 			      CONFIG_LV_Z_INPUT_INIT_PRIORITY, NULL);

 DT_INST_FOREACH_STATUS_OKAY(LVGL_ENCODER_INPUT_DEFINE)
diff --git a/modules/lvgl/input/lvgl_pointer_input.c b/modules/lvgl/input/lvgl_pointer_input.c
index 6d13d13cb7..a9d3794dda 100644
--- a/modules/lvgl/input/lvgl_pointer_input.c
+++ b/modules/lvgl/input/lvgl_pointer_input.c
@@ -147,6 +147,6 @@ static int lvgl_pointer_input_init(const struct device *dev)
 	static struct lvgl_pointer_input_data lvgl_pointer_input_data_##inst;                      \
 	DEVICE_DT_INST_DEFINE(inst, lvgl_pointer_input_init, NULL,                                 \
 			      &lvgl_pointer_input_data_##inst, &lvgl_pointer_input_config_##inst,  \
-			      POST_KERNEL, CONFIG_LV_Z_INPUT_INIT_PRIORITY, NULL);
+			      APPLICATION, CONFIG_LV_Z_INPUT_INIT_PRIORITY, NULL);

 DT_INST_FOREACH_STATUS_OKAY(LVGL_POINTER_INPUT_DEFINE)
```

**Comment by jakkra** [comment]
Thanks @faxe1008 now works like a charm!

**Comment by faxe1008** [comment]
Rebased this against the proper fix of [#62753](https://github.com/zephyrproject-rtos/zephyr/issues/62753), the patch above should not be needed anymore @jakkra .

File: modules/lvgl/input/lvgl_button_input.c [hunk 1]
```diff
@@ -45,13 +50,30 @@ static void lvgl_button_process_event(const struct device *dev, struct input_eve
...
+	const struct device *dev = drv->user_data;
+	const struct lvgl_common_input_config *cfg = dev->config;
+	struct lvgl_button_input_data *button_data = dev->data;
+
+	if (k_msgq_get(cfg->event_msgq, data, K_NO_WAIT) != 0) {
+		*data = button_data->previous_state;
+		goto release;
+	}
+
+	button_data->previous_state = *data;
```
Comment (fabiobaltieri) [inline modules/lvgl/input/lvgl_button_input.c:64]: Normally I'd expect a `memcpy` for copying a struct data... though I guess assignment works but it feels out of place. @gmarull are you aware of any drawback of this? Don't think it's covered by either our or Linux style guide but I may be missing something.

File: modules/lvgl/input/lvgl_encoder_input.c [hunk 2]
```diff
@@ -38,9 +38,18 @@ static void lvgl_encoder_process_event(const struct device *dev, struct input_ev
 	}
 }
 
+static void lvgl_encoder_read_cb(lv_indev_drv_t *drv, lv_indev_data_t *data)
+{
+	const struct device *dev = drv->user_data;
+	const struct lvgl_common_input_config *cfg = dev->config;
+
+	k_msgq_get(cfg->event_msgq, data, K_NO_WAIT);
```
[the remark this answers is not in the document]
Comment (faxe1008) [reply modules/lvgl/input/lvgl_encoder_input.c:46]: Yeah this one I am not to sure about - https://docs.lvgl.io/8.3/porting/indev.html?highlight=input%20interface#encoder
Maybe its sufficient to only keep the previous `lv_indev_data_t->state` in the data? Or is shaving of like 20 bytes not worth doing this over also using an indev_data?

File: modules/lvgl/input/lvgl_button_input.c (hunk 1 above)
Comment (faxe1008) [reply modules/lvgl/input/lvgl_button_input.c:64]: Yeah while writing this I took inspiration from the kscan driver one. I also had a version with memcpy at some point, my suspicion is that the compiler will optimise this to a memcpy anyway. But since we most likely can/dont want to make assumption about the compilers optimizers I'll make it explicit :^)

File: modules/lvgl/input/lvgl_encoder_input.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_encoder_input.c:46]: Looks like it's sufficient to keep that bit, but then if you keep a while indev_data you may as well move it up to the common structure and get away without a custom data structure per event type and simplify the code a bit. Up to you, it's not like LVGL runs on very constrained devices anyway.

File: modules/lvgl/input/lvgl_button_input.c (hunk 1 above)
Comment (fabiobaltieri) [reply modules/lvgl/input/lvgl_button_input.c:64]: sounds good

File: modules/lvgl/input/lvgl_button_input.c [hunk 3]
```diff
@@ -45,13 +50,30 @@ static void lvgl_button_process_event(const struct device *dev, struct input_eve
...
 
+static void lvgl_button_read_cb(lv_indev_drv_t *drv, lv_indev_data_t *data)
+{
+	const struct device *dev = drv->user_data;
+	const struct lvgl_common_input_config *cfg = dev->config;
+	struct lvgl_button_input_data *button_data = dev->data;
+
+	if (k_msgq_get(cfg->event_msgq, data, K_NO_WAIT) != 0) {
+		*data = button_data->previous_state;
+		goto release;
```
[the remark this answers is not in the document]
Comment (faxe1008) [reply modules/lvgl/input/lvgl_button_input.c]: Done :^)

**Comment by faxe1008** [comment]
Reverted back to using the common structure, the gains (~20 bytes per encoder device) did not justify the code duplication.

File: modules/lvgl/input/lvgl_common_input.c [hunk 4]
```diff
@@ -26,8 +26,16 @@ static void lvgl_input_read_cb(lv_indev_drv_t *drv, lv_indev_data_t *data)
 {
 	const struct device *dev = drv->user_data;
 	const struct lvgl_common_input_config *cfg = dev->config;
+	struct lvgl_common_input_data *common_data = dev->data;
+
+	if (k_msgq_get(cfg->event_msgq, data, K_NO_WAIT) != 0) {
+		memcpy(data, &common_data->previous_event, sizeof(lv_indev_data_t));
+		data->enc_diff = 0; /* For encoders, clear last movement */
```
Comment (fabiobaltieri) [inline modules/lvgl/input/lvgl_common_input.c:33]: Do you think we should only do this for encoder events? I know it does not matter but I'm thinking if the struct changes to a union this may introduce some nasty bug, may be worth playing safe and check `indev_drv->type here`

Comment (faxe1008) [reply modules/lvgl/input/lvgl_common_input.c]: Sure safeguarding never a bad idea :^)

**Review by fabiobaltieri — APPROVED** [review]
Good stuff thanks for fixing this.

**Review by gmarull — APPROVED** [review]
