### PR TITLE
net: mqtt_sn: Fix several minor issues

### LINKED ISSUE #89432: MQTT-SN client issues
With NCS 3.0.0 I got the updated MQTT-SN client.

As far as I can tell, it implements the gateway search procedure, but it introduces issue 1. 
Issues 2. and 3. are old, but 3. is also linked to 1.

1. mqtt_sn_transport_udp.c, tp_udp_init()
- The part that deals with broadcasts (IP_ADD_MEMBERSHIP, IP_MULTICAST_TTL) seems to require CONFIG_NET_IPV4_IGMP=y, but selecting CONFIG_MQTT_SN_xxx does not select it.
- The code does not work in my case - ESP32 WiFi AT WiFi board, but I cannot disable it.

2. mqtt_sn_transport_udp.c, get_ip_str()
- should use zsock_inet_ntop, not inet_ntop - introduces dependency for no good reason.

3. mqtt_sn.c, mqtt_sn_client_init()
- IMO this function should fail if call to "transport->init(transport)" fails.

### PR DESCRIPTION
**Pull request by rlubos**
A set of minor fixes for the MQTT SN library and dependencies. For details, please check commit messages.

Fixes #89432

### CODE REVIEW

**Review by pdgendt — DISMISSED** [review]

File: subsys/net/lib/mqtt_sn/mqtt_sn_transport_udp.c [hunk 1]
```diff
@@ -25,11 +25,13 @@ static char *get_ip_str(const struct sockaddr *sa, char *s, size_t maxlen)
 {
 	switch (sa->sa_family) {
 	case AF_INET:
-		inet_ntop(AF_INET, &(((struct sockaddr_in *)sa)->sin_addr), s, maxlen);
+		zsock_inet_ntop(AF_INET, &(((struct sockaddr_in *)sa)->sin_addr),
```
Comment (BeckmaR) [inline subsys/net/lib/mqtt_sn/mqtt_sn_transport_udp.c:28]: Maybe a stupid question and I'm on mobile, but if this removes a dependency, shouldn't a header include or a config be removed as well?

Comment (rlubos) [reply subsys/net/lib/mqtt_sn/mqtt_sn_transport_udp.c:28]: True, there was one redundant header include left in the file. We can remove POSIX requirement from the sample as well, will update.

**Review by pdgendt — APPROVED** [review]

**Review by mpecar — APPROVED** [review]
This fixes everything in #89432

**Review by jukkar — APPROVED** [review]

**Review by BeckmaR — APPROVED** [review]

**Review by maass-hamburg — APPROVED** [review]
