### PR TITLE
random: rand32_ctr_drbg: fix bug preventing initialization

### LINKED ISSUE #43792: mimxrt1050_evk: failed to run tests/net/socket/tls and tests/subsys/jwt
**Describe the bug**
tests/net/socket/tls and tests/subsys/jwt on mimxrt1050_evk failed on this commit: f44b3dc4dfef4ba0adde064e910f35521f09232f

**To Reproduce**
1. twister -p mimxrt1050_evk --device-testing --device-serial /dev/ttyACM0 -T tests/net/socket/tls/ -T tests/subsys/jwt/
Or use west:
1. west build -b mimxrt1050_evk tests/net/socket/tls/ or west build -b mimxrt1050_evk tests/subsys/jwt/
2. west flash

**Expected behavior**
Test case should pass smoothly.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-1072-gc31cb0075ad1  ***
Running test suite lib_jwt_test
===================================================================
START - test_jwt
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x00000000  r1/a2:  0x8000a758  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0xee119966 r14/lr:  0x6000f659
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80000608 (test_jwt)
E: Halting system
```
and:
```
*** Booting Zephyr OS build zephyr-v3.0.0-1072-gc31cb0075ad1  ***
Running test suite socket_tls
===================================================================
START - test_so_type
PASS - test_so_type in 1.1 seconds
===================================================================
START - test_so_protocol
PASS - test_so_protocol in 1.1 seconds
===================================================================
START - test_v4_msg_waitall
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x00000000  r1/a2:  0x800164f0  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x17d56d71 r14/lr:  0x60031079
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80008d80 (unknown)
E: Halting system
```
**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.13.2
 - Commit f44b3dc4dfef4ba0adde064e910f35521f09232f

### LINKED ISSUE #43841: tests-ci : net: socket: tls.preempt test Timeout
**Describe the bug**
tls.preempt test is Timeout on zephyr-v3.0.0-1108-ge65e26162199 on mimxrt1060_evk

see logs for details

**To Reproduce**
1. 
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt1060_evk  --sub-test net.socket
```
2. See error

**Expected behavior**
test pass

**Impact**

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-1108-ge65e26162199  ***
Running test suite socket_tls
===================================================================
START - test_so_type
PASS - test_so_type in 1.2 seconds
===================================================================
START - test_so_protocol
PASS - test_so_protocol in 1.2 seconds
===================================================================
START - test_v4_msg_waitall
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x00000000  r1/a2:  0x800164f8  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0xab84aa67 r14/lr:  0x6003110f
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80008d80 (unknown)
E: Halting system

    
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: zephyr-v3.0.0-1108-ge65e26162199

### LINKED ISSUE #43842: tests-ci : libraries: encoding: jwt test Timeout
**Describe the bug**
jwt test is ***** USAGE FAULT ***** on zephyr-v3.0.0-1108-ge65e26162199 on mimxrt1060_evk

see logs for details

test apps:  tests/subsys/jwt

**To Reproduce**
1. 
```
scripts/twister --device-testing --device-serial /dev/ttyACM0 -p mimxrt1060_evk  --sub-test libraries.encoding
```
2. See error

**Expected behavior**
test pass

**Impact**

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.0.0-1108-ge65e26162199  ***
Running test suite lib_jwt_test
===================================================================
START - test_jwt
E: ***** USAGE FAULT *****
E:   Illegal use of the EPSR
E: r0/a1:  0x00000000  r1/a2:  0x8000a758  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0xee119966 r14/lr:  0x6000f675
E:  xpsr:  0x60000000
E: Faulting instruction address (r15/pc): 0x00000000
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x80000608 (test_jwt)
E: Halting system

    
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux )
 - Toolchain (e.g Zephyr SDK)
 - Commit SHA or Version used: zephyr-v3.0.0-1108-ge65e26162199

### LINKED ISSUE #44092: rand32_ctr_drbg fails to call the respective initialization routing
**Describe the bug**
f44b3dc4dfe changed where initialization of entropy_dev to occur at compile time but the logic in z_impl_sys_csrand_get() calls the initialization routine IF entropy_dev is NULL. In the init routine it will assign the device object to entropy_dev and properly initialize the context object. 

Using an initialized context object results in a crash.

**To Reproduce**
1. west build -b mimxrt1050_evk -p always tests/net/socket/tls/
2. See error

**Impact**
Code crashes from an indirect call to a NULL address when getting sys_csrand_get() data.

### PR DESCRIPTION
**Pull request by dleach02**
Bug introduced that prevented the logic from initializing the
context structure. Without this initialization, the application
will crash on repeated request for ctr_drbg random data.

Fixes: #44092
Fixes: #43792
Fixes: #43841
Fixes: #43842

Signed-off-by: David Leach <david.leach@nxp.com>

### CODE REVIEW

File: subsys/random/rand32_ctr_drbg.c [hunk 1]
```diff
@@ -51,6 +55,15 @@ static int ctr_drbg_initialize(void)
 {
 	int ret;
 
+	entropy_dev = DEVICE_DT_GET(DT_CHOSEN(zephyr_entropy));
+	if (!entropy_dev) {
```
Comment (gmarull) [inline subsys/random/rand32_ctr_drbg.c:59]: This condition can never hold true, DEVICE_DT_GET always returns a non-null reference (otherwise it would result in a build failure).

**Review by gmarull — CHANGES_REQUESTED** [review]

File: subsys/random/rand32_ctr_drbg.c (hunk 1 above)
Comment (dleach02) [reply subsys/random/rand32_ctr_drbg.c:59]: Fair enough. Actually better if there is a build failure. So I'll take out the !entropy_dev, which was similar to what it was before.

**Review by ghost — DISMISSED** [review]

**Comment by LixinGuoX** [comment]
Look good to me and verified on mimxrt1050_evk.

**Review by ceolin — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by gmarull — APPROVED** [review]
