### PR TITLE
fix bugs in mcux i2s and dma

### LINKED ISSUE #59802: drivers: dma: dma_mcux_lpc: uses wrong transfer size for I2S
**Describe the bug**
In a change that went in between v3.3 and v3.4, the dma_mcux_lpc driver was changed to support transfers larger than one descriptor allowed for (which is 1024 words).

That change introduced a regression which causes I2S to not work on chips like RT595.

The regression is due to how the DMA transfer size is computed. The old version used the dest_data_size for transfer size (which really isn't correct either, like if it was doing an I2S RX ) but the latest version uses MIN(dest_data_size, source_data_size). The I2S driver (i2s_mcux_flexcomm), when doing TX, always sets source_data_size to 1, but dest_data_size to 1 or 4, depending on the bits in the I2S config, with 4 being typical for 16-bit PCM two channel. The result of the bug is that the DMA transfers 1 byte to the I2S FIFO, when it is expecting 4.

**To Reproduce**

I had expected the i2s_speed test under tests/drivers/i2s to catch this, but it did not. My only guess as to why is because the bug impacts both the I2S TX and RX the same way, so the RX would up getting what it expected, even though it was actually being clocked out incorrectly.

The RT595EVK config configures flexcomm3 for TX and flexcomm1 for RX, but makes them actually share  DATA, WS, and CLK.

To reproduce the problem, I created a config such that flexcomm1 was TX, flexcomm3 was unused, and I was transmitting I2S intended for the TFA9896 amp on the board. Putting the I2S output on an analyzer, it was clear that the data was incorrect when writing to the I2S one byte at a time when it was expected 4 (two channels of 16-bits each).

**Expected behavior**
Data sent to i2s_write() should show up correctly on I2S bus.

**Impact**
Breaks I2S on RT595EVK.

**Environment (please complete the following information):**
- Zephyr SDK for RT595EVK, v3.4 of Zephyr @ commit 356c8cbe63ae01b3ab438382639d25bb418a0213 (v3.4.0 release)

### LINKED ISSUE #59803: drivers: i2s: i2s_mcux_flexcomm: multiple bugs
**Describe the bug**
While testing a driver for the speaker amp on the RT595EVK, I found multiple bugs in the i2s_mcux_flexcomm driver:

1. the size passed in i2s_write() is ignored. it is always transferring the mem_block size configured for the stream. so if the block passed to i2s_write() was only partially filled, garbage could be sent out to i2s.
2. if the values for CONFIG_I2S_MCUX_FLEXCOMM_RX_BLOCK_COUNT and CONFIG_I2S_MCUX_FLEXCOMM_TX_BLOCK_COUNT were to be set to non-defaults and not the same, the msg queue buffers would be incorrectly sized.
3. related to bug https://github.com/zephyrproject-rtos/zephyr/issues/59802, the source_data_size and dest_data_size should be set to be the same because the DMA controller can only set one size for each transfer.

I've not checked the history but I believe these bugs have existed for a while (since Zephyr v3.3 at least).

**To Reproduce**
Since the driver for the TFA9896 isn't currently in Zephyr, it's not easy to reproduce with existing configs. I ported the TFA9896 driver from the NXP SDK for RT595EVK to Zephyr and found these bugs while testing the driver.

**Expected behavior**
1. size for i2s_write should be honored
2. CONFIG for TX_BLOCK_COUNT and RX_BLOCK_COUNT should work when they are not the same value
3. source_data_size and dest_data_size should be set to be the same

**Impact**
When DMA driver is changed to address bug https://github.com/zephyrproject-rtos/zephyr/issues/59802, new asserts will cause I2S driver to fail.
The other bugs can be worked around but are annoying and incorrect.

**Environment (please complete the following information):**
- Zephyr v3.4.0 release

### PR DESCRIPTION
**Pull request by mjchen0**
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/59802
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/59803

### CODE REVIEW

**Comment by dleach02** [comment]
@hakehuang can you run a regression test on RT595

**Comment by hakehuang** [comment]
the existing testcases i2s_speed can not catch such issue, as I can run pass with i2s_speed test with/without this fixes

```
*** Booting Zephyr OS build zephyr-v3.4.0-974-g7fba7d395750 ***
Running TESTSUITE drivers_i2s_speed
===================================================================
START - test_i2s_transfer_long
20 TX blocks sent
20 RX blocks received
 PASS - test_i2s_transfer_long in 0.120 seconds
===================================================================
START - test_i2s_transfer_short
0->OK
1->OK
2->OK
1<-OK
2<-OK
3<-OK
 PASS - test_i2s_transfer_short in 0.021 seconds
===================================================================
TESTSUITE drivers_i2s_speed succeeded
Running TESTSUITE drivers_i2s_speed_both_rxtx
===================================================================
START - test_i2s_dir_both_transfer_long
I2S_DIR_BOTH value is not supported.
 SKIP - test_i2s_dir_both_transfer_long in 0.004 seconds
===================================================================
START - test_i2s_dir_both_transfer_short
I2S_DIR_BOTH value is not supported.
 SKIP - test_i2s_dir_both_transfer_short in 0.004 seconds
===================================================================
TESTSUITE drivers_i2s_speed_both_rxtx succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [drivers_i2s_speed]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.141 seconds
 - PASS - [drivers_i2s_speed.test_i2s_transfer_long] duration = 0.120 seconds
 - PASS - [drivers_i2s_speed.test_i2s_transfer_short] duration = 0.021 seconds

SUITE SKIP -   0.00% [drivers_i2s_speed_both_rxtx]: pass = 0, fail = 0, skip = 2, total = 2 duration = 0.008 seconds
 - SKIP - [drivers_i2s_speed_both_rxtx.test_i2s_dir_both_transfer_long] duration = 0.004 seconds
 - SKIP - [drivers_i2s_speed_both_rxtx.test_i2s_dir_both_transfer_short] duration = 0.004 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
I: Device flexcomm@109000 inited
I: Device flexcomm@107000 inited
*** Booting Zephyr OS build zephyr-v3.4.0-976-ge17597821848 ***
Running TESTSUITE drivers_i2s_speed
===================================================================
START - test_i2s_transfer_long
20 TX blocks sent
20 RX blocks received
 PASS - test_i2s_transfer_long in 0.033 seconds
===================================================================
START - test_i2s_transfer_short
0->OK
1->OK
2->OK
1<-OK
2<-OK
3<-OK
 PASS - test_i2s_transfer_short in 0.008 seconds
===================================================================
TESTSUITE drivers_i2s_speed succeeded
Running TESTSUITE drivers_i2s_speed_both_rxtx
===================================================================
START - test_i2s_dir_both_transfer_long
I2S_DIR_BOTH value is not supported.
 SKIP - test_i2s_dir_both_transfer_long in 0.004 seconds
===================================================================
START - test_i2s_dir_both_transfer_short
I2S_DIR_BOTH value is not supported.
 SKIP - test_i2s_dir_both_transfer_short in 0.004 seconds
===================================================================
TESTSUITE drivers_i2s_speed_both_rxtx succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [drivers_i2s_speed]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.041 seconds
 - PASS - [drivers_i2s_speed.test_i2s_transfer_long] duration = 0.033 seconds
 - PASS - [drivers_i2s_speed.test_i2s_transfer_short] duration = 0.008 seconds

SUITE SKIP -   0.00% [drivers_i2s_speed_both_rxtx]: pass = 0, fail = 0, skip = 2, total = 2 duration = 0.008 seconds
 - SKIP - [drivers_i2s_speed_both_rxtx.test_i2s_dir_both_transfer_long] duration = 0.004 seconds
 - SKIP - [drivers_i2s_speed_both_rxtx.test_i2s_dir_both_transfer_short] duration = 0.004 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL


```

File: drivers/dma/dma_mcux_lpc.c [hunk 1]
```diff
@@ -281,8 +281,14 @@ static int dma_mcux_lpc_configure(const struct device *dev, uint32_t channel,
...
 	dma_data = dev->data;
 	block_config = config->head_block;
-	width = MIN(config->source_data_size, config->dest_data_size);
-	max_xfer = NXP_LPC_DMA_MAX_XFER * width;
+	/* The DMA controller deals with just one transfer
+	 * size, though the API provides separate sizes
+	 * for source and dest. So assert that the source
+	 * and dest sizes are the same.
+	 */
+	assert(config->dest_data_size == config->source_data_size);
```
Comment (mmahadevan108) [inline drivers/dma/dma_mcux_lpc.c:289]: This assert may cause failures in some of the other drivers that use this driver. I would suggest removing it and updating the comment.

Comment (mjchen0) [reply drivers/dma/dma_mcux_lpc.c:289]: If the caller has the dest_data_size == source_data_size, then the assert won't trip, and it won't trip if asserts are not enabled.

If the caller has different values for src and dest sizes, then it's a problem they need to think about and fix.
The old driver (prior to the change to support chaining for long transfers) used MIN. The driver
that supports the long transfers used MAX. This changing of behavior already broke existing drivers silently (e.g. the I2S usage). I think it'd be better to detect such problems as soon as possible, instead of silently doing something they might not be expecting and possibly setting the size the opposite of what the caller intended.

Comment (mmahadevan108) [reply drivers/dma/dma_mcux_lpc.c:289]: I know we will have to update the SPI driver to address this. Let me know if you would like me to send you a patch.

File: drivers/dma/dma_mcux_lpc.c [hunk 2]
```diff
@@ -492,6 +498,9 @@ static int dma_mcux_lpc_configure(const struct device *dev, uint32_t channel,
 				dst_inc,
 				block_config->block_size);
 	}
+	/* DMA controller requires that the address be aligned to transfer size */
```
Comment (mmahadevan108) [inline drivers/dma/dma_mcux_lpc.c:501]: I am not aware of such a alignment requirement. 
There is a requirement for the DMA descriptors which this driver addresses.

File: drivers/i2s/i2s_mcux_flexcomm.c [hunk 3]
```diff
@@ -19,7 +19,7 @@
```
Comment (dbaluta) [inline drivers/i2s/i2s_mcux_flexcomm.c:19]: Ideally you should add only one patch per issue addressed. This way the code would be much easier to understand and review.

There are exceptions if the changes are tightly related. Not sure if this the case.

Comment (mjchen0) [reply drivers/i2s/i2s_mcux_flexcomm.c:19]: The primary bug is the change/regression in the DMA driver. But the fix to the DMA driver includes an assert, which is there to prevent future mistakes from happening silently. That assert would immediately break the I2S driver, which is why the two commits are combined in this PR.

I could take out the I2S one, but it would have to be merged first. I'm still relatively new to Zephyr (and github) development so I don't know if pull requests can be dependent on one another. Let me know if there's still a preference in having the I2S change be a separate Pull Request.

File: drivers/dma/dma_mcux_lpc.c (hunk 2 above)
Comment (mjchen0) [reply drivers/dma/dma_mcux_lpc.c:501]: In the RT500 Reference Manual, section 16.4.2.4 says:

> 16.4.2.4 Address alignment for data transfers
> Transfers of 16 bit width require an address alignment to a multiple of 2 bytes. Transfers of 32 bit width require an address alignment to a multiple of 4 bytes. Transfers of 8 bit width can be at any address

File: drivers/dma/dma_mcux_lpc.c (hunk 1 above)
Comment (mjchen0) [reply drivers/dma/dma_mcux_lpc.c:289]: I can add that. I thought I had checked the SPI driver, since we use that too, but I think we didn't catch it because our usage of SPI is always using 1-byte dest_data_size (src_data_size is fixed at 1).

**Comment by mmahadevan108** [comment]
@mjchen0. Thank you for submitting the PR. The changes look fine to me.

**Review by mmahadevan108 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

File: drivers/dma/dma_mcux_lpc.c (hunk 1 above)
Comment (decsny) [reply drivers/dma/dma_mcux_lpc.c:288]: I think also the UART driver will be fine because destination and source data sizes will both be 1 always

**Review by EmilioCBen — APPROVED** [review]
