### PR TITLE
drivers: ieee802154: Rem trx_state variable

### LINKED ISSUE #23198: rf2xx driver uses mutex in ISR
**Describe the bug**

The ieee802154_rf2xx driver is using a mutex in ISR context:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/ieee802154/ieee802154_rf2xx.c#L85-L87

With CONFIG_ASSERT=y, the kernel will  report

```
ASSERTION FAIL [!arch_is_in_isr()] @ ZEPHYR_BASE/kernel/include/ksched.h:262
``` 

The MCR driver handles this differently, I think.

FYI: @nandojve

### PR DESCRIPTION
**Pull request by nandojve**
The rx timeout timer callback need update **trx_state** variable and this variable is protected by a **mutex**. Because of that, when compiling the system with **CONFIG_ASSERT=y** the system reports _ASSERTION FAIL [!arch_is_in_isr()] @ ZEPHYR_BASE/kernel/include/ksched.h:262_.

This refactor the driver remove **trx_state** variable dependency and consequently removes **phy_mutex** and **rx timeout timer** to be compliant with kernel rules.

Fixes: #23198

This PR includes #22511

### CODE REVIEW

**Comment by nandojve** [comment]
The changes were tested with two **atsamr21** boards running `samples/net/socktets/echo_[client|server]`. The system seems to be working without any problems. Below a line printing from server side that shows number of packets after some time.

`[02:19:11.140,000] <inf> net_echo_server_sample: IPv6 UDP: Sent 305000 packets`

@markus-becker-tridonic-com can you check if everything is OK from your side and give us a feedback, please.

**Comment by nandojve** [comment]
@jhedberg

File: drivers/ieee802154/ieee802154_rf2xx_iface.c [hunk 1]
```diff
@@ -7,7 +7,11 @@
  */
 
 #define LOG_MODULE_NAME ieee802154_rf2xx_iface
+#if defined(CONFIG_IEEE802154_DRIVER_LOG_LEVEL)
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx_iface.c]: Why this ifdef?
#define LOG_LEVEL CONFIG_IEEE802154_DRIVER_LOG_LEVEL  
should be sufficient.

File: drivers/ieee802154/ieee802154_rf2xx_iface.c [hunk 2]
```diff
@@ -7,7 +7,11 @@
  */
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx_iface.c]: in you commit title add "for rf2xx driver"

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 3]
```diff
@@ -7,7 +7,11 @@
  */
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: add "for rf2x driver" in your commit title

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 4]
```diff
@@ -7,7 +7,11 @@
...
 
 #define LOG_MODULE_NAME ieee802154_rf2xx
+#if defined(CONFIG_IEEE802154_DRIVER_LOG_LEVEL)
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: same as previous patch, no need of ifdef.

File: drivers/ieee802154/ieee802154_rf2xx.c [hunk 5]
```diff
@@ -230,26 +257,35 @@ static void rf2xx_thread_main(void *arg)
...
-						    RF2XX_TRX_PHY_STATE_CMD_RX_AACK_ON);
-				/*if (ctx->trx_state == RF2XX_TRX_PHY_BUSY_TX)*/
+
+				if (ctx->trx_model != RF2XX_TRX_MODEL_231) {
+					rf2xx_trx_rx(dev);
+				} else {
+					/* Ensures that automatically ACK will be sent
+					* when requested
+					*/
+					while (rf2xx_iface_reg_read(dev,
```
Comment (tbursztyka) [inline drivers/ieee802154/ieee802154_rf2xx.c]: when you start to have too many if/for/while imbrication, it's time to refactor a bit for readability

File: drivers/ieee802154/ieee802154_rf2xx_iface.c (hunk 1 above)
Comment (nandojve) [reply drivers/ieee802154/ieee802154_rf2xx_iface.c]: Rollback

File: drivers/ieee802154/ieee802154_rf2xx.c (hunk 4 above)
Comment (nandojve) [reply drivers/ieee802154/ieee802154_rf2xx.c]: Rollback

File: drivers/ieee802154/ieee802154_rf2xx_iface.c (hunk 2 above)
Comment (nandojve) [reply drivers/ieee802154/ieee802154_rf2xx_iface.c]: Done.

File: drivers/ieee802154/ieee802154_rf2xx.c (hunk 3 above)
Comment (nandojve) [reply drivers/ieee802154/ieee802154_rf2xx.c]: Done.

File: drivers/ieee802154/ieee802154_rf2xx.c (hunk 5 above)
Comment (nandojve) [reply drivers/ieee802154/ieee802154_rf2xx.c]: Done on fd54e41

**Comment by javier-moreno-tridonic-com** [comment]
@nandojve Hi, I've tested this on our hardware and so far we haven't encountered any more problems.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by tbursztyka — APPROVED** [review]
