### PR TITLE
native: Added arch,soc & board to run Zephyr natively in a POSIX OS

### LINKED ISSUE #1891: Native Port
**_Reported by Gajinder Vij:_**

Simulator to improve testability

A native port to Host Operating Systems (Windos and UNIX) would greatly simplify a series of tasks that are currently burdensome, since running natively as an Operating System process has a lot of advantages when developing high-level code:

- Very fast turnaround build and test time (native compilation and execution of a native executable)
- Tight coupling with the Host OS' TCP/IP stack for networking tests
- Full integration with Desktop-grade IDEs (Microsoft Visual Studio for example)
- Suitability for simple CI and regression testing
- Ability to use Valgrind and other Desktop tools to profile the RTOS
- Integration with libraries like SDL for simulated input and GUI design and testing
- Direct access to the native filesystem for on-the-fly replacement of files

Other IoT RTOSs already have support for this:

- RIOT OS: https://github.com/RIOT-OS/RIOT/tree/master/cpu/native
- Mynewt: https://github.com/apache/incubator-mynewt-core/tree/master/hw/mcu/native/src
- Contiki: https://github.com/contiki-os/contiki/tree/master/platform/native

This feature has been requested by a company evaluating Zephyr RTOS, as it is critical to their testing infrastructure and development model. 

Customer story: 

_"Our testing/CI system requires that the code under test can be built into an OS native application currently. Zephyr however does not support "native" ports, or ports on top of other scheduling APIs. We would have to make a port of Zephyr on top of Win32/pthreads which is an significant effort. We cannot readily use the existing Zephyr simulation model (QEMU/instruction set simulation based). "_

(Imported from Jira ZEP-332)

### PR DESCRIPTION
**Pull request by aescolar**
**Proof of concept of a native port of Zephyr to run on a POSIX OS.**

It includes:
A new arch (posix) which relies on pthreads to emulate the context switching
A new soc for it (inf_clock) which emulates a CPU running at an infinely high
 clock (so when the CPU is awaken it runs till completion in 0 time).
A new board, which provides a trivial system tick timer and irq generation, to be able to run as a standalone console program.

<del>Note that this does not provide Kconfig and Makefiles to integrate with the
default built system.</del>

All this is work in progress.
<del>The garbage/ folder is not meant to be merged ever (please ignore it)</del>

Origin: Original

Fixes #1891

Signed-off-by: Alberto Escolar Piedras <alpi@oticon.com>

<del>I haven't dug in the build system, so you cannot configure it to build thru the normal build flow. But I append a trivial Makefile in the garbage folder you can use to build it. If you want to try it, in the repo root, run
export COMPILE_OUTPUT_DIR=foobar/
make -f garbage/Makefile compile
that will build the philosophers app into foobar/zephyr_posix_exe
you can then run that binary directly (or in gdb if you want).
If you want to build another sample app, modify garbage/c_files_list accordingly</del>

Please note that all of it is quite hacky at this point. The aim of this pull request is to start a discussion about the fitness of the approach, and to gather comments (if you have many, please focus on the most important matters and ignore typos and similar)

***[updated 2017/11/28]*** : see nashif's comment below for how to build. Note that now sanitycheck can also be used: ```sanitycheck -p simple_process```

### CODE REVIEW

**Comment by nashif** [comment]
just noticed that when building the synchronisation sample, it is going really fast where it should be sleeping for half a second, any idea what is going on?

**Review by tyrantlizard77 — COMMENTED** [review]
I understand this is WIP code but a few things stand out:

1) Coding style. We have a particular coding style for Zephyr that this patch doesn't follow at all. https://www.zephyrproject.org/doc/contribute/contribute_guidelines.html#coding-style Need you to fix this ASAP, and verify that it is in compliance using checkpatch,pl

2) The complete lack of interrupts is very concerning. This basically means that all threads become cooperative, and irq_lock() is a no-op. It seems to me that it will be quite easy to write code that works well in this particular environment, but will not work at all on real HW due to concurrency problems.  I would really suggest trying a different approach here, possibly something that uses POSIX signals to emulate timer interrupts.

3) Sanitycheck integration. The way you are going to prove that this works is by showing that all of our unit tests pass at runtime using the sanitycheck tool. On other arches it does this by running them under QEMU. I'd like to see support added to sanitycheck to run all the test cases in posix environment.

**Comment by pfalcon** [comment]
>  it is going really fast where it should be sleeping for half a second, any idea what is going on?

Description says:

> emulates a CPU running at an infinely high clock

I wonder if that's it ;-).

**Comment by pfalcon** [comment]
The feature is absolutely great, +1 for having it. It didn't look at the code yet.

**Comment by lpereira** [comment]
I will read the code more carefully, but I agree with @pfalcon: this is indeed a welcome feature; thanks for working on it.

From a quick glance, though, I'd like to add to comments made already.

I suggest steering clear of signals to simulate interrupts.  Being asynchronous, their [handling is tricky](http://man7.org/linux/man-pages/man7/signal-safety.7.html) and very prone to headaches.  It might be cleaner to just have a thread that blocks on a read to a [socketpair](http://man7.org/linux/man-pages/man2/socketpair.2.html) or a [pipe](http://man7.org/linux/man-pages/man2/pipe.2.html) and call the appropriate ISRs (this would simulate better an interrupt context, anyway).

In fact, it might be a good idea to have a main loop of sorts, to handle things like timers (even the system timer), interrupts, and power management; this will make the port a lot cleaner.  Supporting something like a tickless kernel would be pretty easy.  Writing a main loop that is portable can be quite tricky, so I suggest using a library such as [libuv](http://libuv.org/) or [libevent](http://libevent.org/).

Another thing to consider is to, instead of using pthread threads to simulate a Zephyr thread, is to perform the context switch yourself, either using [swapcontext() / makecontext()](http://man7.org/linux/man-pages/man3/makecontext.3.html), or using [_setjmp() / _longjmp()](http://man7.org/linux/man-pages/man3/longjmp.3.html); the reason being that this is going to be closer to what ports for real hardware do, and thus yield more consistent results.  I do this on a [personal project to implement coroutines](https://lwan.ws/), and it works pretty well.

**Comment by andrewboie** [comment]
> I suggest steering clear of signals to simulate interrupts. Being asynchronous, their handling is tricky and very prone to headaches. It might be cleaner to just have a thread that blocks on a read to a socketpair or a pipe and call the appropriate ISRs (this would simulate better an interrupt context, anyway)

My though process here was that indeed signals are tricky, but so are real interrupt handlers, both can be delivered at any time unless specifically suppressed and code needs to be careful to properly lock around them in critical sections. I'm not immediately seeing how doing this in the context of a dedicated thread would be a better simulation, especially if we are trying to simulate nested interrupts.

**Comment by pfalcon** [comment]
+1 for @andrewboie's comment - signals are indeed async, and that's why they're closest thing to the real IRQs on POSIX.

**Comment by aescolar-ot** [comment]
Thanks for looking into this.
Let me describe a bit better what is done and why:

This solution is based on some assumptions about what it is that we try to do, 
but it is layered so that one can reuse the arch or soc if he shares their assumptions. One can build a different soc or board if he doesn't share the next ones.
The division in arch/soc/board is not really trying to match what would be different in real SOC/boards but these layers of assumptions.

The arch only emulates the thread creation and context switching. It is based on POSIX threads.
It works by spawning 1 pthread per zephyr thread, and keeps all blocked but one to emulate the fact that Zephyr is meant for a single thread CPU.

The next thing, and this is the first big assumption is in the SOC:
The CPU runs at an infinetitely high clock. So each time the cpu awakes, it runs till completion before the HW moves in time at all (even a "delta" cycle).
The SOC part provides the irq enabling/disabling, CPU "booting", awaking and halting.
NOTE: There is interrupts. In this quick proof of concept (because the board only provides 1 IRQ, there wasn't yet a need to mask/enable disable them. [please ignore the comments inside _arch_irq_lock/unlock they are missleading]).
But by the inf cpu clock assumption, an IRQ cannot come while the CPU is awake.

The next thing is the board, which assumes you do not want in any way to link the simulated time to real time. [@nashif That is why half a simulated second passes very fast in real time]. The board provides all HW models, including IRQ controller, and therefore also the IRQ handling.
The board would be the part one would always replace completely when wanting to run Zephyr in/with a simulation framework.
The one provided is almost the most trivial/barebones thing which is enough to run those sample apps. It just provides the printk hook, a system timer/ticker and a trivial irq controller & handler.

**Comment by aescolar-ot** [comment]
Now the background for these assumptions == What it is that we try and don't try to do with a soc/board like this.
(Note that I start now talking about all assumptions together; But remember that if for some use case you do not share some, you only need to add a new board or soc).
- The main target of this is fast functional regression testing, simulations in which we have the full functionality of the code, and functional debugging of the code. [*1]
- We want to run tests _fast_ (as in several minutes of simulated time per wall time second)
- We want full reproducibility between runs. Therefore any "randomness" must be controlled.
- We want to be able to run in a debugger and get exactly the same results. It should not matter if you stop in a breakpoint, go to a meeting, and 1 hour later continue where you left it. [*2]
- We do not try to use real host peripherals, but simulated HW or HW models.
- We do not try to replace a cycle accurate instruction set simulator (ISS), dev boards, or QEMU, but to complement them. We want to allow to do *1 and *2 easily and fast.


The aim is NOT to debug HW/SW races, missed HW programming deadlines, or cases in which an interrupt comes when you did not expect it. I think, the proper way to debug that would be with a cycle accurate ISS (or a dev board).
Note that as we compile natively to x86, we dont have any way of knowing how long time that code would have taken to execute in the real target.
Note also that a workstation CPU runs at 3+GHz, and the native kernel time slices feel like an eternity for our embedded code.
[If you let HW models run in one thread simultaneously with the app/os code in another thread, and use an asynchronous mechanism to throw something from one to the other you will see things like a few seconds of simulated time pass before the kernel/app reacts to a time critical interrupt. Moreover, it will depend greatly on the machine you use and its load]

Philosophical background:
Lot's of bugs are functional bugs. Specially the higher you go up in the application/network stack, your bugs are more functional bugs and less related to the exact moment an interrupt comes.
Most networking protocol bugs will not depend on exactly when an interrupt come but about the content of a packet or when did it comes relative to some protocol hanshake or FSM state.
We have been using this kind of native port for quite some time in another OS, and we are very happy with what it provides us.

**Comment by aescolar-ot** [comment]
One comment more, to clarify. If you want to slow down things to run in real time, because you want to, say, talk with a real server and have real timeouts, all you need to do is have a different board with a minor difference.
In here
https://github.com/aescolar-ot/zephyr/blob/native_posix_wip/boards/posix/simple_process/hw_models.c#L22
(or wherever your HW model would advance time), you would do a nanosleep() of the difference between the time you wanted to wait, and the amount of time you actually spent since the last time you advanced time.

**Comment by aescolar-ot** [comment]
@nashif @carlescufi : Now the simple_process board will by default runs in real time.
You can set it to run as before by defining PULL_THE_HANDBRAKE to 0 in
https://github.com/aescolar-ot/zephyr/blob/e44029b62bd5d6f338391f9581fd1967a1f848c6/boards/posix/simple_process/hw_models.c#L16

**Comment by andrewboie** [comment]
I see where you're coming from but it still doesn't sit well with me that all threads which would normally be preemptible are forced to be non-preemptible under this target.

I suppose we'll have to see how things look when we start running test cases under sanitycheck. I have a feeling a lot of stuff is not going to work due to the assumptions you have made about timing (or complete lack thereof)

The coding style issues are a dealbreaker and must be addressed.

**Comment by aescolar-ot** [comment]
Thanks @andrewboie,
Regarding the coding style: that is the easiest thing to fix [as I commented all this started and still kind of is a proof of concept, so there is quite a few shortcuts. Not setting my editor to a different style was one of them :)]

Regarding the assumption of timing, if you can think of some particular case which could cause trouble, it could be useful to start looking into it.

Would it help, to imagine this target as if it were a real development board which has an outrageously high CPU clock compared to the final target, but that people likes using because it provides very nice debugging capabilities and costs nothing?
In such a target, similarly (almost) all interrupts would come when the app/os has gone to idle. So you would have the same issue with no interrupts context switches in threads. The threads are still pre-emptible. They are just lucky it does not happen.
The case in which I would expect problems is if somebody has code that assumes that N NOPS after doing something the HW will be ready, or if there is a busy wait until a register is set (but as that would be very HW dependent I expect either it won't matter because it would be in unused drivers, or that people would be able to accept an ifdef).
I saw there is a k_busy_wait(), and I guess that will require an ARCH_HAS_CUSTOM_BUSY_WAIT kind of ifdef.

**Comment by andrewboie** [comment]
> if you can think of some particular case which could cause trouble, it could be useful to start looking into it.

Get sanitycheck working with this port.

> Would it help, to imagine this target as if it were a real development board which has an outrageously high CPU clock compared to the final target, but that people likes using because it provides very nice debugging capabilities and costs nothing?

Not really, since if I understand this port correctly, something like k_sleep(500) will return immediately and not 500 milliseconds later. Even very fast CPUs can be tuned such that timer APIs work as expected.

**Comment by aescolar-ot** [comment]
To the best of my understanding k_sleep() works as it is supposed to. You can just try the sync app with the latest commit I made.
The only reason Anas saw things happening very fast is because the first "board" was running in simulated time. Which is much faster than real time, but the app and kernel code was executing exactly the same path it executes now.

**Comment by nashif** [comment]
> To the best of my understanding k_sleep() works as it is supposed to. You can just try the sync app with the latest commit I made.

yes, works better now with latest commit.

**Comment by carlescufi** [comment]
Here's my 2 cents about this after taking a quick glance at the code and discussing with @aescolar-ot offline. I believe we need to distinguish exactly what we want to achieve with a "native" or "POSIX" port. In my eyes what **developers and users** expect from a native port is the following:

* Develop Zephyr **applications** or **high-level libraries** (i.e. not kernel or low-level drivers) without the need for ISA emulation (i.e. QEMU) or hardware
* Ability to use all development tools available for desktop applications
* Ability to interface with external devices (in particular IP-enabled but BLE or Thread could be a possibility as well) to test the embedded application under a desktop development environment but communicating with real devices
* Faithful (as much as possible) replication of the execution environment that one would find in the real hardware, including timeouts, race conditions and memory but **not** CPU execution speed. This in particular I derive from the current batch of emulators doing the rounds in mobile application development (iOS/Android)
* Fast turnaround time and simplified development when developing, in the future, display-enabled applications where the GUI is part of the app itself (i.e. integration with SDL or similar in the future)

On the other hand, @aescolar-ot has another set of goals in mind, a bit different from the ones above:

* Very fast, non-realtime simulation of hardware (and in particular) network topologies. This includes the ability to "fast-forward" time or let it run freely at high speeds to simulate hours or months of execution in seconds or minutes
* Hardware and network-oriented simulation, without regard for the faithfulness of the firmware code execution in terms of context switches, preemption and, of course, CPU speed

Please correct me if I'm wrong, @aescolar-ot so we can all be on the same page. But assuming what I stated is correct, then I think we have 2 ways to move forward:

1) Create 2 separate archs or ports: a "native" one that corresponds to the Zephyr users' expectations and a "sim" one that is used for high-speed simulation
2) Create a single one that is configurable to behave as one or the other based on Kconfig settings

**Comment by aescolar-ot** [comment]
Thanks @carlescufi. I agree that there seems to be some misunderstanding about what the aim of the port should be. Different people can have different objectives in mind.
That was the reason why I layered the arch/soc/board in that way, to allow for reuse of the lower parts, and creating different soc/boards if need be.
So I was aiming close to the 2nd option you proposed.

Let me mention that I do share objectives 1) ,2) and 5) in your first list:
+ a couple more: 6) ability to regression test fast ; 7) fully controlled integration tests (with "external" test code which can monitor and modify the app and OS state/variables); 8) fully reproducible tests ; 9) ability to debug and instrument without affecting the result (ability to freeze the whole universe in a breakpoint); 10) ability to plug to external tools which may be able to run much faster or much slower than real time.

Regarding Carles 4th point, that is what QEMU is partially meant to provide (you run the same image, with the same memory layout, but do on the fly "translation" to the native instruction set. And there is no intent to provide timing realism apart from the feeling given by the system time running at ≈ real time).

So you can say that the spectrum is roughly like:
| <- What I want to use this port for
| <- QEMU
| 
| <- Instruction Set Simulation
|
| <- HW RTL simulations / emulation (Cadence Palladium like)

Where the y axis is a tradeoff of accuracy vs speed +visibility+debug ability.
And please note that I target speeds up of more than x100, although as proven by the latest commit, there is nothing preventing slowing down things, so you can have a HW model/driver which actually interfaces with a real ethernet card, socket or similar.

**Comment by lpereira** [comment]
I'll be happy if I can run Zephyr under [rr](http://rr-project.org/), Valgrind, or built with [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) or UndefinedBehaviorSanitizer.  I've debugged quite a few parts of Zephyr by taking the code out, building it for Linux, and using these things to find my way out.

Other things that could be used with this port are tools like [afl](http://lcamtuf.coredump.cx/afl/) or [libfuzzer](https://llvm.org/docs/LibFuzzer.html), that are helpful to find those bugs that a test suite alone are unable to.

Being able to use these tools without bending the world would be an invaluable debugging aid.  So much so that, for me, this trumps every other requirement (such as simulating nested interrupts, or anything resembling "real hardware" too much).

**Comment by nashif** [comment]
@aescolar-ot  what is the status with this PR? Do you need any help?

**Comment by aescolar-ot** [comment]
@nashif Some help would be very welcome. It seems there is a bit of work ahead before this could be merged (please correct me or add as needed):
1. Use the build system (== create kconfig and makefiles)
2. Include in sanitycheck
3. Debug and fix anything sanitycheck may reveal
4. Beautify the code (refactor things a bit better, code style, silly names, etc)

Regarding 1. and 2. I'm thinking that any of you would be able to do it much faster than me, as you know the setup while for me that would be an up hill reverse engineering task.
Regarding 3. and 4. it would be logical that it would be me.

Would any of you be willing to take 1. and maybe also 2.?

**Comment by pfalcon** [comment]
@aescolar-ot : Let me try to chime in, mostly just focusing your attention on what was said before. In your list above, p.0 should be:

0. Rework to follow the native Zephyr codestyle.

That would help more people to look at your patch (so far what one immediately sees is codestyle violation in every 2nd line, then there's https://en.wikipedia.org/wiki/Fail-fast approach).

**Comment by nashif** [comment]
> Beautify the code (refactor things a bit better, code style, silly names, etc)

You can speed this up by running your code through uncrustify :)

install uncrustify
`uncrustify --replace --no-backup -l C -c $ZEPHYR_BASE/scripts/uncrustify.conf *.c`

**Comment by aescolar-ot** [comment]
@pfalcon thanks.
Forgive my ignorance but, why does the coding style prevent reviewing the code?
Regarding the fail fast approach, what did you mean?

Anyhow, now checkpatch is happier. Just note that:
* I did not clean up the code in the garbage folder as that is meant to be thrown away as soon as 1. is done)
* I ignored NEW_TYPEDEFS : as that is also in the other archs, I assume it is not a problem
* I also ignored PREFER_KERNEL_TYPES in the board, as the board is not really meant to see kernel types

@nashif Thanks :)

**Comment by aescolar-ot** [comment]
@pfalcon Is the code now good enough to review? :)

**Comment by nashif** [comment]
> Forgive my ignorance but, why does the coding style prevent reviewing the code?

Eyes are trained to see the code in a certain form I guess. I do not think it prevents review, but the style issue will be a distraction for sure.

**Comment by pfalcon** [comment]
@aescolar-ot : Looks much better now, thanks (there're more codestyle issues there definitely, but at least not in every 2nd line ;-) ). Did you consider to squash the "codestyle fix" commit into previous commit(s)?

Hope to try the patch later this week.

**Comment by aescolar-ot** [comment]
Thanks @pfalcon 
> Did you consider to squash the "codestyle fix" commit into previous commit(s)?

Is that the preferred way? I can just rebase the 3 commits together if people prefers it that way..

>there're more codestyle issues there definitely

Ok, please point them out then so I can fix them (or if you see some general issue just comment it)

**Comment by jukkar** [comment]
> Ok, please point them out then so I can fix them (or if you see some general issue just comment it)

One style issue that caught my eye was the non indented comment blocks inside functions.

Anyway, looking forward to try this with valgrind. Thanks for the patches.

**Comment by aescolar-ot** [comment]
@jukkar Uhm, but, if the tab is 8 chars long, indenting the comment inside a couple of levels of indentation leaves very little space for a comment text. Is that the preferred way?

Note that the (p)threads are not cleaned yet so valgrind will complain there of a leak.

Anyhow, I just committed a trivial change to the board system timer model that will stop the whole thing after 5 seconds, in case you want to try also gcov (or something else which requires a graceful exit):
image

**Comment by nashif** [comment]
@aescolar-ot I am looking at add the necessary Makefile/Kconfig files to make this build without garabge, jfyi, will see if it would be easy enough :)

**Comment by aescolar-ot** [comment]
@nashif Thanks!

**Comment by pfalcon** [comment]
Note that tying to build this PR merged into the latest master leads to errors like:

~~~
include/syscall.h:13:26: fatal error: syscall_list.h: No such file or directory
~~~

So yep, adhoc build system doesn't scale, and integrating it into the normal build process would be the next step ;-).

File: arch/posix/core/fatal.c [hunk 1]
```diff
@@ -0,0 +1,221 @@
...
+	default:
+		return "unknown";
+	}
+}
+#endif
+
+FUNC_NORETURN void _Fault(const NANO_ESF *esf)
+{
+#ifdef CONFIG_PRINTK
+	/* Unfortunately, completely unavailable on Nios II/e cores */
```
[the remark this answers is not in the document]
Comment (aescolar-ot) [reply arch/posix/core/fatal.c]: Correct. It is a copy pasted + pruned version to start with

**Comment by aescolar-ot** [comment]
This PR is now rebased on top of today's master.
@pfalcon => the include/syscall.h thing is "fixed"
@anasnashif Beware that now the syscall autogenerated headers are on the garbage folder too

**Comment by nashif** [comment]
so I have this almost building (using Cmake), but the main() hacks needs some work still. I decided to make this work with cmake and not invest time on this using kbuild which will be obsoleted soon.

**Comment by aescolar-ot** [comment]
@nashif Thanks!

**Comment by nashif** [comment]
my branch with cmake integration with still a few hacks is here: https://github.com/nashif/zephyr/tree/native_posix

I tried building a few tests and sample, looks like we are missing a few essentials kernel interfaces, for example, trying to build the shell application:

`/home/nashif/Work/github/zephyr/subsys/shell/modules/kernel_service.c:43: undefined reference to `_timer_cycle_get_32'`

This can be seen in many tests, samples.

I suggest to start going over samples and tests and checking them out and see what is missing and what else we need to support.

In my branch you can now run:
```
mkdir build && cd build
cmake -DBOARD=simple_process ..
make run
```

**Comment by nashif** [comment]
some of the obvious samples/tests are running without problem, this is great, for example all crypto tests, json test and a few simple kernel tests. I enabled coverage reports with gcov and that works as well, so all great sofar.

**Comment by aescolar-ot** [comment]
Just a list of things I see need to be done to be able to merge or would be nice to do [feel free to expand, I will be adding things]:
* posix core/arch:
  * Add threads abort
  * Index threads in a more portable way
* soc/board:
  * add a CONFIG_ARCH_AS_CUSTOM_BUSY_WAIT and implement one for this board 
  * Add irq_offload() 
  * mature simple_process board (refactor/cleanup, add proper drivers and interrupts plugging & handler)
* build:
  * linker script to use proper template
* tests:
  * replace busy wait loops with k_busy_wait

File: arch/Kconfig [hunk 2]
```diff
@@ -33,6 +33,11 @@ config RISCV32
 config XTENSA
 	bool "Xtensa architecture"
 
+config ARCH_POSIX
+	bool "POSIX (native) architecture"
+	select ATOMIC_OPERATIONS_C
```
Comment (andrewboie) [inline arch/Kconfig]: why not use ATOMIC_OPERATIONS_BUILTIN?

File: arch/posix/core/fatal.c [hunk 3]
```diff
@@ -0,0 +1,223 @@
...
+#endif
+
+	void _SysFatalErrorHandler(unsigned int reason,
+			const NANO_ESF *pEsf);
+	_SysFatalErrorHandler(reason, esf);
+}
+
+#if defined(CONFIG_EXTRA_EXCEPTION_INFO) && defined(CONFIG_PRINTK) \
+		&& defined(ALT_CPU_HAS_EXTRA_EXCEPTION_INFO)
+static char *cause_str(u32_t cause_code)
```
Comment (andrewboie) [inline arch/posix/core/fatal.c]: don't see why we need this since we are not invoking x86 CPU exceptions

File: arch/posix/core/fatal.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (andrewboie) [reply arch/posix/core/fatal.c]: don't think we need this function, or maybe a much smaller one which just calls NanoFatalErrorHandler()

File: arch/posix/core/posix_core.c [hunk 4]
```diff
@@ -0,0 +1,272 @@
...
+ */
+static void *pc_thread_starter(void *arg)
+{
+	posix_thread_status_t *ptr = (posix_thread_status_t *) arg;
+
+	/*we detach ourselves so nobody needs to join to us*/
+	pthread_detach(pthread_self());
+
+	if (pthread_mutex_lock(&pc_mtx_threads)) {
+/*
```
Comment (andrewboie) [inline arch/posix/core/posix_core.c]: comment blocks inside functions should have the indentation aligned

File: arch/posix/core/posix_core.c [hunk 5]
```diff
@@ -0,0 +1,272 @@
...
+ */
+	if (pthread_mutex_lock(&pc_mtx_threads)) {
+		ps_print_error_and_exit(
+			"Posix arch core: error on pthread_mutex_lock()\n");
+	}
+}
+
+/*
+ * NOTE:
+ * This will work with or without CONFIG_ARCH_HAS_CUSTOM_SWAP_TO_MAIN defined
```
Comment (andrewboie) [inline arch/posix/core/posix_core.c]: native is its own arch, so how would this ever be enabled?

File: arch/posix/core/posix_core.c [hunk 6]
```diff
@@ -0,0 +1,272 @@
...
+ */
+
+/*
+ * NOTE:
+ * we may want to define CONFIG_ARCH_HAS_THREAD_ABORT
+ * and implement a k_thread_abort() to kill threads which are finished.
```
Comment (andrewboie) [inline arch/posix/core/posix_core.c]: I think we might need to something.
What happens if a thread aborts, and that thread object is then re-used?

File: arch/posix/soc/inf_clock/soc.c [hunk 7]
```diff
@@ -0,0 +1,213 @@
...
+	if (POSIX_ARCH_SOC_DEBUG_PRINTS) {
+		ps_print_trace(
+			"Posix arch core: Zephyr init started (%lu)\n",
+			zephyr_thread);
+	}
+
+	pthread_detach(zephyr_thread);
+
+	/*Start Zephyr:*/
+	_PrepC(); /*this does not return*/
```
Comment (andrewboie) [inline arch/posix/soc/inf_clock/soc.c]: just call _Cstart() here and delete the _PrepC() function

File: cmake/ccache.cmake [hunk 8]
```diff
@@ -3,7 +3,7 @@
 
 if(USE_CCACHE STREQUAL "0")
 else()
-  find_program(CCACHE_FOUND ccache)
+  find_program(CCACHE_FOUNDX ccache)
```
Comment (andrewboie) [inline cmake/ccache.cmake]: what does this change do?

File: include/toolchain/gcc.h [hunk 9]
```diff
@@ -27,7 +27,17 @@
 #define FUNC_ALIAS(real_func, new_alias, return_type) \
 	return_type new_alias() ALIAS_OF(real_func)
 
+#if defined(CONFIG_ARCH_POSIX)
+/*let's not segfault if this were to happen for some reason*/
+#define CODE_UNREACHABLE \
+{\
+	void exit(int status); \
+	exit(1);\
```
Comment (andrewboie) [inline include/toolchain/gcc.h]: would a call to k_panic() work? would help users comprehend that something bad happened and where it occurred.

File: misc/Kconfig [hunk 10]
```diff
@@ -179,6 +179,13 @@ config BUILD_OUTPUT_BIN
 	  Build a binary in BIN format. This will build a zephyr.bin file need
 	  by some platforms.
 
+config BUILD_OUTPUT_EXE
+	bool "Build a binary in ELF format with .exe extension"
+	default n
+	help
+	  Build a binary in ELF format that can run in the host system. This
+	  will build a zephyr.exe file.
```
Comment (andrewboie) [inline misc/Kconfig]: i'm not sure a hard-coded .exe extension is such a good idea, .exe is strongly associated to most people with DOS/Windows, maybe call it "zephyr.native" or just "zephyr"?

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]

File: include/toolchain/gcc.h (hunk 9 above)
Comment (andrewboie) [reply include/toolchain/gcc.h]: alternatively, put an __ASSERT() here instead?

File: arch/posix/core/fatal.c (hunk 3 above)
Comment (aescolar-ot) [reply arch/posix/core/fatal.c]: The whole fatal.c needs a cleanup (I started copying the nios one, but most of it was not necessary). => added to list of TODOs

File: arch/posix/core/posix_core.c (hunk 4 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: Will do

File: arch/posix/core/posix_core.c (hunk 5 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: just added it to its Kconfig file with the last commit

File: arch/posix/core/posix_core.c (hunk 6 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: It would be nice to do something yep. (it is in the TODO)
Although how it is now, an aborted thread just waits forever in pc_wait_until_allowed() after it has been swap'ed out.

File: arch/posix/soc/inf_clock/soc.c (hunk 7 above)
Comment (aescolar-ot) [reply arch/posix/soc/inf_clock/soc.c]: Ok, will do

File: cmake/ccache.cmake (hunk 8 above)
Comment (aescolar-ot) [reply cmake/ccache.cmake]: => @nashif

File: include/toolchain/gcc.h (hunk 9 above)
Comment (aescolar-ot) [reply include/toolchain/gcc.h]: Uhm, for ASSERT that assumes misc/__assert.h has been included at that point.
regarding k_panic() also needs kernel.h.
What about just replacing the exit call with a ps_print_error_and_exit("CODE_UNREACHABLE reached from %s:%d", __FILE__ , __LINE__);
+ #include "posix_soc_if.h" at the top?

File: misc/Kconfig (hunk 10 above)
Comment (aescolar-ot) [reply misc/Kconfig]: => @nashif

File: arch/Kconfig (hunk 2 above)
Comment (aescolar-ot) [reply arch/Kconfig]: ATOMIC_OPERATIONS_BUILTIN was my first proposal (in garbage/autoconf.h). 
@nashif any reason why you set it ATOMIC_OPERATIONS_C in Kconfig?

File: misc/Kconfig (hunk 10 above)
Comment (nashif) [reply misc/Kconfig]: well, at least on windows the .exe would be accurate here, .exe is for executable, has really nothing to do with windows, in Linux this has been used in other environments (C# for example). Anyways, we can make this OS dependent, i.e. on windows it will be .exe, on macs it would be .app and on linux just zephyr. The idea with .exe was to make it immediately visible that this is a runnable binary on the host. (just calling it zephyr might not deliver this message)

File: cmake/ccache.cmake (hunk 8 above)
Comment (nashif) [reply cmake/ccache.cmake]: yep, leftover from debugging., will remove

File: boards/posix/simple_process/CMakeLists.txt [hunk 11]
```diff
@@ -0,0 +1,10 @@
+zephyr_library()
```
Comment (carlescufi) [inline boards/posix/simple_process/CMakeLists.txt]: I dislike this "simple_process" name. In time it might not be that simple anymore, and in any case I think something like `boards/posix/process` would be better.

File: arch/Kconfig [hunk 12]
```diff
@@ -33,6 +33,13 @@ config RISCV32
 config XTENSA
 	bool "Xtensa architecture"
 
+config ARCH_POSIX
```
Comment (carlescufi) [inline arch/Kconfig]: I wonder if we should instead build a tree here:
```
ARCH_NATIVE
|-- ARCH_POSIX
|---- SOC_POSIX
|------ SOC_POSIX_MACOS
|------ SOC_POSIX_MACOS
|-- ARCH_WINX
|---- SOC_WIN32
...
```

File: arch/posix/CMakeLists.txt [hunk 13]
```diff
@@ -0,0 +1,15 @@
+zephyr_cc_option_ifdef(CONFIG_LTO -flto)
+
+zephyr_ld_option_ifdef(CONFIG_COVERAGE
+	-lgcov
+	)
+zephyr_compile_options(
+  -m32
```
Comment (carlescufi) [inline arch/posix/CMakeLists.txt]: Will this work on 32-bit Linux? Do we event want to bother with 32-bit Linux? I'd be in favour of dropping support for it, but we'd need a basic check in place.

File: arch/posix/include/posix_soc_if.h [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+
+
+#include "soc_irq.h" /*Must exist and define _ARCH_IRQ/ISR_* macros*/
+
+unsigned int _arch_irq_lock(void);
+void _arch_irq_unlock(unsigned int key);
+void _arch_irq_enable(unsigned int irq);
+void _arch_irq_disable(unsigned int irq);
+int  _arch_irq_is_enabled(unsigned int irq);
+unsigned int ps_irq_lock(void);
```
Comment (carlescufi) [inline arch/posix/include/posix_soc_if.h]: Do we really need this "`ps_`" prefix here? If we do then I would be in favour of using "`posix_`" or "`native_`" if it's common to all native builds.

File: arch/posix/include/posix_core.h [hunk 15]
```diff
@@ -0,0 +1,44 @@
...
+
+#if defined(CONFIG_ARCH_HAS_THREAD_ABORT)
+	/* The kernel may indicate that a thread has been aborted several */
+	/* times */
+	int aborted;
+#endif
+} posix_thread_status_t;
+
+
+void pc_new_thread(posix_thread_status_t *ptr);
```
Comment (carlescufi) [inline arch/posix/include/posix_core.h]: Why "`pc_`" here? See my other comment about posix/native prefixes.

File: arch/posix/core/posix_core.c [hunk 16]
```diff
@@ -0,0 +1,556 @@
...
+
+#define PC_ALLOC_CHUNK_SIZE 64
+#define PC_REUSE_ABORTED_ENTRIES 0
+/* tests/kernel/threads/scheduling/schedule_api fails when setting
+ * PC_REUSE_ABORTED_ENTRIES => don't set it by now
+ */
+
+static int pc_threads_table_size;
+typedef struct {
+	enum {NotUsed = 0, Used, Aborting, Aborted, Failed} state;
```
Comment (carlescufi) [inline arch/posix/core/posix_core.c]: I don't think we allow camel case, use caps

File: arch/posix/core/posix_core.c [hunk 17]
```diff
@@ -0,0 +1,556 @@
...
+#define NO_MEM_ERR PREFIX"Can't allocate memory\n"
+
+#define PC_ALLOC_CHUNK_SIZE 64
+#define PC_REUSE_ABORTED_ENTRIES 0
+/* tests/kernel/threads/scheduling/schedule_api fails when setting
+ * PC_REUSE_ABORTED_ENTRIES => don't set it by now
+ */
+
+static int pc_threads_table_size;
+typedef struct {
```
Comment (carlescufi) [inline arch/posix/core/posix_core.c]: do you really need a new type here?

File: arch/posix/core/posix_core.c [hunk 18]
```diff
@@ -0,0 +1,556 @@
...
+static void *pc_thread_starter(void *arg);
+static void pc_preexit_cleanup(void);
+
+/**
+ * Helper function, run by a thread is being aborted
+ */
+static void pc_abort_tail(int this_th_nbr)
+{
+	if (POSIX_ARCH_DEBUG_PRINTS) {
+		ps_print_trace(
```
Comment (carlescufi) [inline arch/posix/core/posix_core.c]: In general for all calls to `ps_print_trace`, why not use DBG()-style macros that use SYSLOG instead? This would be more consistent with the rest of subsystems

File: arch/posix/core/posix_core.c [hunk 19]
```diff
@@ -0,0 +1,556 @@
...
+static void pc_wait_until_allowed(int this_th_nbr);
+static void *pc_thread_starter(void *arg);
+static void pc_preexit_cleanup(void);
+
+/**
+ * Helper function, run by a thread is being aborted
+ */
+static void pc_abort_tail(int this_th_nbr)
+{
+	if (POSIX_ARCH_DEBUG_PRINTS) {
```
Comment (carlescufi) [inline arch/posix/core/posix_core.c]: Use a macro instead of if statements in all these cases, similar to: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/common/log.h#L40

File: arch/posix/core/posix_core.c [hunk 20]
```diff
@@ -0,0 +1,556 @@
...
+#define PC_ALLOC_CHUNK_SIZE 64
+#define PC_REUSE_ABORTED_ENTRIES 0
+/* tests/kernel/threads/scheduling/schedule_api fails when setting
+ * PC_REUSE_ABORTED_ENTRIES => don't set it by now
+ */
+
+static int pc_threads_table_size;
+typedef struct {
+	enum {NotUsed = 0, Used, Aborting, Aborted, Failed} state;
+	bool running;     /*is this the currently running thread*/
```
Comment (carlescufi) [inline arch/posix/core/posix_core.c]: For all `/*text*/` comments: this should be `/* text */` instead

File: arch/posix/core/posix_core.c [hunk 21]
```diff
@@ -0,0 +1,556 @@
...
+				__func__);
+	}
+	pc_preexit_cleanup();
+	pthread_exit(NULL);
+}
+
+/**
+ * Handler called when any thread is cancelled or exits
+ */
+static void pc_cleanupHandler(void *arg)
```
Comment (carlescufi) [inline arch/posix/core/posix_core.c]: No camel case

File: arch/posix/core/swap.c [hunk 22]
```diff
@@ -0,0 +1,105 @@
...
+
+
+	_kernel.current = _kernel.ready_q.cache;
+
+	/*
+	 * Here a "real" arch would load all processor registers for the thread
+	 * to run. In this arch case, we just block this thread until allowed to
+	 * run later, and signal to whomever is allowed to run to continue.
+	 */
+	{
```
Comment (carlescufi) [inline arch/posix/core/swap.c]: are those braces needed?

File: arch/posix/include/kernel_arch_thread.h [hunk 23]
```diff
@@ -0,0 +1,60 @@
...
+#ifndef _ASMLANGUAGE
+#include <zephyr/types.h>
+
+struct _caller_saved {
+	/*
+	 * Nothing here
+	 */
+};
+
+typedef struct _caller_saved _caller_saved_t;
```
Comment (carlescufi) [inline arch/posix/include/kernel_arch_thread.h]: In general for all those new types you've created, the preferred approach is to use `struct` instead and remove the `_t`

File: arch/posix/soc/inf_clock/Kconfig.soc [hunk 24]
```diff
@@ -0,0 +1,13 @@
+
+
+config SOC_POSIX
```
Comment (carlescufi) [inline arch/posix/soc/inf_clock/Kconfig.soc]: See my comment about arch/soc Kconfig tree

File: boards/posix/simple_process/hw_models_top.c [hunk 25]
```diff
@@ -0,0 +1,137 @@
...
+#include "irq_ctrl.h"
+#include "posix_board_if.h"
+#include "posix_soc_if.h"
+
+
+static hwtime_t device_time; /*The actual time as known by the device*/
+static hwtime_t end_of_time = NEVER; /*When will this device stop*/
+
+/* List of HW model timers: */
+extern hwtime_t HWTimer_timer; /*When does the timer_model want to be called*/
```
Comment (carlescufi) [inline boards/posix/simple_process/hw_models_top.c]: no camel case

File: boards/posix/simple_process/hw_models_top.c [hunk 26]
```diff
@@ -0,0 +1,137 @@
+/*
```
Comment (carlescufi) [inline boards/posix/simple_process/hw_models_top.c]: It's unclear to me why this can't be in drivers/ instead of in boards/. Maybe I'm missing something, but won't this be common to all `boards/posix/*` boards?

File: boards/posix/simple_process/irq_ctrl.c [hunk 27]
```diff
@@ -0,0 +1,271 @@
+/*
```
Comment (carlescufi) [inline boards/posix/simple_process/irq_ctrl.c]: Similar to my comment earlier, why can't this be in `arch/posix/`?

Comment (carlescufi) [reply boards/posix/simple_process/irq_ctrl.c]: Same about many of the files after this

File: boards/posix/simple_process/hw_models_top.h [hunk 28]
```diff
@@ -0,0 +1,32 @@
...
+#include <stdint.h>
+#include <inttypes.h>
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+typedef uint64_t hwtime_t;
+#define NEVER UINT64_MAX
+#define PRItime PRIu64
```
Comment (carlescufi) [inline boards/posix/simple_process/hw_models_top.h]: no camel case

File: boards/posix/simple_process/irq_ctrl.h [hunk 29]
```diff
@@ -0,0 +1,45 @@
...
+void hw_irq_ctrl_disable_irq(unsigned int irq);
+int hw_irq_ctrl_is_irq_enabled(unsigned int irq);
+void hw_irq_ctrl_clear_irq(unsigned int irq);
+void hw_irq_ctrl_enable_irq(unsigned int irq);
+void hw_irq_ctrl_set_irq(unsigned int irq);
+void hw_irq_ctrl_raise_im(unsigned int irq);
+void hw_irq_ctrl_raise_im_from_sw(unsigned int irq);
+
+
+#define N_IRQs 32
```
Comment (carlescufi) [inline boards/posix/simple_process/irq_ctrl.h]: No camel case

File: drivers/console/Kconfig [hunk 30]
```diff
@@ -198,6 +198,15 @@ config XTENSA_SIM_CONSOLE
 	help
 	  Use simulator console to print messages.
 
+config POSIX_SP_CONSOLE
```
Comment (carlescufi) [inline drivers/console/Kconfig]: Can this be made generic instead of being tied to the "single process" board?

File: drivers/console/posix_sp_console.c [hunk 31]
```diff
@@ -0,0 +1,35 @@
...
+	/* Let's ensure that even if we are redirecting to a file, we get stdout
+	 * and stderr line buffered (default for console). Note that glibc
+	 * ignores size. But just in case we set a reasonable number in case
+	 * somebody tries to compile against a different library
+	 */
+	setvbuf(stdout, NULL, _IOLBF, 512);
+	setvbuf(stderr, NULL, _IOLBF, 512);
+
+	extern void __printk_hook_install(int (*fn)(int));
+	__printk_hook_install(putchar);
```
Comment (carlescufi) [inline drivers/console/posix_sp_console.c]: will this always print to stdout?

**Review by carlescufi — CHANGES_REQUESTED** [review]
Thanks for this @aescolar-ot. In general I think this is a really good PR, I have some overall comments on the structure and nitpicks on the coding style, but I'll leave the integration with the actual POSIX subsystems to the kernel experts.

File: arch/Kconfig (hunk 12 above)
Comment (carlescufi) [reply arch/Kconfig]: @galak thoughts?

Comment (aescolar-ot) [reply arch/Kconfig]: This port arch/soc & board is meant to be both for Unix/Linux and MacOS (I haven't tried it on MacOS, but everything I wrote should hopefully be POSIX compliant, including the simple_process board)
Regarding Windows, its threading is quite different than pthreads. So I guess if somebody wants that, they would need to build an ARCH_WIN and so forth.
Nesting ARCH_POSIX and a possible ARCH_WIN below an ARCH_NATIVE would seem to be about categorizing without a functional need. Also the current source tree does not seem to support it.

File: arch/posix/CMakeLists.txt (hunk 13 above)
Comment (aescolar-ot) [reply arch/posix/CMakeLists.txt]: It should. There we are just telling the compiler that the target is i386 (a 32 bit binary). You can also use that if your compile host is a x86, like you can compile from a 32 bit x86 for an ARM target.
The reason to have that switch is to ensure ints and pointers are 32 bits which is the assumption in Zephyr.

File: arch/posix/core/posix_core.c (hunk 17 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: Need, no..

File: arch/posix/core/posix_core.c (hunk 16 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: Uhm, checkpatch did not complain. Can somebody (@nashif ) confirm that there should not be camel case at all, and enums should be in caps?

File: arch/posix/core/posix_core.c (hunk 20 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: Ok, another one I don't think checkpatch complained about..

File: arch/posix/core/posix_core.c (hunk 19 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: Makes sense. There is a lot of spurious code for this prints

File: arch/posix/core/swap.c (hunk 22 above)
Comment (aescolar-ot) [reply arch/posix/core/swap.c]: Not anymore :) => will remove

File: arch/posix/include/kernel_arch_thread.h (hunk 23 above)
Comment (aescolar-ot) [reply arch/posix/include/kernel_arch_thread.h]: This is just like in all other archs. Those structures are part of the kernel-arch IF.

File: arch/posix/include/posix_soc_if.h (hunk 14 above)
Comment (aescolar-ot) [reply arch/posix/include/posix_soc_if.h]: pc = posix core
ps = posix soc
pb = posix board
The prefix is just for "namespacing", and indicating which layer/module implements the function.
Using 2 letters was just to keep it short.

File: boards/posix/simple_process/CMakeLists.txt (hunk 11 above)
Comment (aescolar-ot) [reply boards/posix/simple_process/CMakeLists.txt]: I'm ok with calling it any sane name. But before changing it, I would prefer if you could first reach some agreement with other people who has a strong opinion about it so we don't need to change it back and forth.

File: boards/posix/simple_process/hw_models_top.c (hunk 26 above)
Comment (aescolar-ot) [reply boards/posix/simple_process/hw_models_top.c]: Nope, this is not common to all boards. This is just one way of doing it, even if a generic way.
The thing here is that, AFAIK, HW models do not fit anywhere in the current zephyr tree. So I just assumed the logical place for them was hidden inside the board folder, to keep the thing contained.

File: boards/posix/simple_process/irq_ctrl.c (hunk 27 above)
Comment (aescolar-ot) [reply boards/posix/simple_process/irq_ctrl.c]: Please see my comment from the 5th of October above about the arch/soc/board layering in this arch. 
The idea is that the arch & SOC provide what almost everybody would want to reuse no matter what HW they are emulating. But if they want to, say, emulate an ARM's NVIC, they would include that NVIC model in their board.
( I do have another board with a different POSIX IRQ controller ).

File: drivers/console/Kconfig (hunk 30 above)
Comment (aescolar-ot) [reply drivers/console/Kconfig]: It is not tied to the simple process board.
If you want to use it on another board you can just modify line 205 to
  depends on BOARD_SIMPLE_PROCESS || BOARD_BANANA

File: drivers/console/posix_sp_console.c (hunk 31 above)
Comment (aescolar-ot) [reply drivers/console/posix_sp_console.c]: Yes, that's what the stdc putchar does. ( it is a simple driver meant for the "simple process" board )

File: arch/posix/core/posix_core.c (hunk 18 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: All this prints are only meant to debug the core itself for somebody who is trying to change it / fix it (The define is at the top of the file). 
So I don't think it makes much sense to have those traces ever on, or have them configurable/dependent of SYS_LOG

File: arch/Kconfig (hunk 12 above)
Comment (carlescufi) [reply arch/Kconfig]: I'm not quite convinced about Windows, since it's not only the threading, but also the build system and other basic changes that will be common to all native builds. That said I can't really hold the argument without actually trying a Windows native port, so I will let the others voice their opinion.

File: arch/posix/core/posix_core.c (hunk 17 above)
Comment (carlescufi) [reply arch/posix/core/posix_core.c]: The approach is to avoid new typedefs completely except for very particular cases (slist is an example). I would prefer if you could remove those and use `struct` instead.

File: arch/posix/include/posix_soc_if.h (hunk 14 above)
Comment (carlescufi) [reply arch/posix/include/posix_soc_if.h]: I personally dislike those prefixes. Could we simply use `posix_` everywhere, regardless of the core/soc/board distinction?

File: boards/posix/simple_process/CMakeLists.txt (hunk 11 above)
Comment (carlescufi) [reply boards/posix/simple_process/CMakeLists.txt]: @nashif @galak can you weigh in?

File: boards/posix/simple_process/irq_ctrl.c (hunk 27 above)
Comment (carlescufi) [reply boards/posix/simple_process/irq_ctrl.c]: I read the comment and I'm not quite convinced. Why can't the different hardware models for interrupts live in subfolders in `arch/posix/`, just like we have for say, `arm/`, where we have `arm/core/` and then `arm/soc`?

File: drivers/console/Kconfig (hunk 30 above)
Comment (carlescufi) [reply drivers/console/Kconfig]: I can't imagine this being different for any other POSIX board. Why not simply make it depend on `ARCH_POSIX` instead?

File: drivers/console/posix_sp_console.c (hunk 31 above)
Comment (carlescufi) [reply drivers/console/posix_sp_console.c]: OK

File: arch/posix/core/posix_core.c (hunk 18 above)
Comment (carlescufi) [reply arch/posix/core/posix_core.c]: Sure, but that is also true for the native kernel, why not have something like `K_DEBUG`? https://github.com/zephyrproject-rtos/zephyr/blob/master/kernel/sched.c#L155

File: arch/posix/core/posix_core.c (hunk 17 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: will do

File: arch/posix/core/posix_core.c (hunk 18 above)
Comment (aescolar-ot) [reply arch/posix/core/posix_core.c]: Will do

File: boards/posix/simple_process/irq_ctrl.c (hunk 27 above)
Comment (aescolar-ot) [reply boards/posix/simple_process/irq_ctrl.c]: Ok. Let's separate the irq controller from the discussion one second.
The thing is: HW models did not exist in Zephyr or fit anywhere. 
So I placed the HW models for a board in boards/posix/<board_name>, and it's drivers in the drivers folder as for any other driver.
The idea in general is that, if for example, somebody models a given real peripheral, he can reuse the real driver from the drivers folder. But the HW model itself is not the driver, and I don't think it should be placed in the driver folder.
If you have some better idea where HW models should be placed please tell. But I guess it would need to be a completely new place, say native_hw_models/ , or something like that.
Please note that with time, I expect there will be many, very diverse hw models, based on different ways of modelling the HW, some meant for simulators or external tools, others like for the simple_process being just simple models.
Maybe we can just start how it is now, and if we see a need later we can move the hw models somewhere else.

The IRQ controller HW model is a bit special here because it is very linked with the SW IRQ handling (effectively its driver), which is normally part of the arch/soc. But in this case both the irq hw model and the irq handler are part of the board because of the layering explained in that other comment.

File: arch/posix/core/posix_core.c [hunk 32]
```diff
@@ -0,0 +1,536 @@
...
+
+#define PC_ALLOC_CHUNK_SIZE 64
+#define PC_REUSE_ABORTED_ENTRIES 0
+/* tests/kernel/threads/scheduling/schedule_api fails when setting
+ * PC_REUSE_ABORTED_ENTRIES => don't set it by now
+ */
+
+static int pc_threads_table_size;
+struct pc_threads_table_el {
+	enum {NotUsed = 0, Used, Aborting, Aborted, Failed} state;
```
Comment (aescolar-ot) [inline arch/posix/core/posix_core.c]: Can somebody (@nashif ) confirm that there should not be camel case at all, and enums should be in caps?

Comment (nashif) [reply arch/posix/core/posix_core.c]: yes please, no CamelCase

File: arch/posix/include/posix_soc_if.h (hunk 14 above)
Comment (nashif) [reply arch/posix/include/posix_soc_if.h]: pc sounds like 'personal computer' :) Agree with @carlescufi here, posix makes more sense now that I think about it.

File: CMakeLists.txt [hunk 33]
```diff
@@ -64,6 +64,9 @@ zephyr_include_directories(
   ${STDINCLUDE}
 )
 
+if(NOT CONFIG_ARCH_POSIX)
+	set(TOPT -T)
+endif()
```
[the remark this answers is not in the document]
Comment (SebastianBoe) [reply CMakeLists.txt]: wget https://github.com/SebastianBoe/zephyr/commit/39df57f864a01cd4916eea0177abc8de8f4f9bcb.patch
git am 39df57f864a01cd4916eea0177abc8de8f4f9bcb.patch

File: CMakeLists.txt [hunk 34]
```diff
@@ -95,10 +98,30 @@ zephyr_compile_options(
...
   -Wno-format-zero-length
+  -imacros ${AUTOCONF_H}
+)
+
+
+# FIXME
+if(CONFIG_ARCH_POSIX)
+zephyr_compile_options(
+  -Wno-undef
+  -Wno-implicit-function-declaration
```
Comment (SebastianBoe) [inline CMakeLists.txt]: Would it work to move these two into arch/posix/CMakeLists.txt ?

Motivation is same as above.

File: CMakeLists.txt [hunk 35]
```diff
@@ -95,10 +98,30 @@ zephyr_compile_options(
...
+  )
+else()
```
Comment (SebastianBoe) [inline CMakeLists.txt]: We need to try to get rid of this else.

-Wno-main can be applied to POSIX and non-POSIX alike I figure, it's just a warning.

I have verified that keeping -ffreestanding here and adding -fno-freestanding to posix/CMakeLists.txt gives us the desired behaviour.

File: CMakeLists.txt [hunk 36]
```diff
@@ -95,10 +98,30 @@ zephyr_compile_options(
...
+zephyr_compile_options(
   -Wno-main
   -ffreestanding
-  -include ${AUTOCONF_H}
+  )
+endif()
+
+if(CONFIG_ARCH_POSIX)
```
Comment (SebastianBoe) [inline CMakeLists.txt]: I assume we can get rid of this "if POSIX" since I assume COVERAGE already
depends on POSIX through Kconfig.

File: CMakeLists.txt [hunk 37]
```diff
@@ -114,13 +137,15 @@ zephyr_compile_options(
...
+if(NOT CONFIG_ARCH_POSIX)
 zephyr_ld_options(
   -nostartfiles
   -nodefaultlibs
   -nostdlib
   -static
   -no-pie
-  )
+)
+endif()
```
Comment (SebastianBoe) [inline CMakeLists.txt]: You need to get rid of this if statement for the same reasons as above, I assume this can easily be done with at least one of the techniques mentioned above.

File: CMakeLists.txt [hunk 38]
```diff
@@ -774,7 +824,17 @@ add_custom_command(
   # NB: COMMENT only works for some CMake-Generators
 )
 
-add_subdirectory(cmake/qemu)
+if(EMU_PLATFORM STREQUAL "qemu")
+	add_subdirectory(cmake/qemu)
+elseif(EMU_PLATFORM STREQUAL "native")
+    add_custom_target(run
```
Comment (SebastianBoe) [inline CMakeLists.txt]: We should be consistent with qemu.

so

add_subdirectory(cmake/native)

File: arch/posix/CMakeLists.txt [hunk 39]
```diff
@@ -0,0 +1,15 @@
+zephyr_cc_option_ifdef(CONFIG_LTO -flto)
+
+zephyr_ld_option_ifdef(CONFIG_COVERAGE
+	-lgcov
+	)
```
Comment (SebastianBoe) [inline arch/posix/CMakeLists.txt]: When you use zephyr_ld_option the build system will silently omit -lgcov if the toolchain does not support it.

I assume that is not desired behaviour and that you want to use

zephyr_link_libraries(-lgcov)

instead.

File: arch/posix/CMakeLists.txt [hunk 40]
```diff
@@ -0,0 +1,15 @@
...
+zephyr_compile_options(
+  -m32
+  -MMD -MP -D_POSIX_C_SOURCE=199309
```
Comment (SebastianBoe) [inline arch/posix/CMakeLists.txt]: zephyr_compile_definitions(_POSIX_C_SOURCE=199309)

Comment (SebastianBoe) [reply arch/posix/CMakeLists.txt]: (Or perhaps even better just put this in the cheat file)

File: arch/posix/CMakeLists.txt [hunk 41]
```diff
@@ -0,0 +1,15 @@
...
+  ${TOOLCHAIN_C_FLAGS}
+  ${ARCH_FLAG}
+  -include ${PROJECT_SOURCE_DIR}/arch/posix/include/posix_cheats.h
```
Comment (SebastianBoe) [inline arch/posix/CMakeLists.txt]: This construct should only be used when there is no reasonable way to express this with  #include pragmas.

I don't know the context, but I hope that adding this has not been done lightly.

At the very least, there should be a disclaimer in the file explaining why it was necessary to use -include so that when -include causes issues in the future the guy that needs to deal with that can decide whether getting rid of -include is the simplest solution.

**Review by SebastianBoe — CHANGES_REQUESTED** [review]

File: arch/posix/CMakeLists.txt (hunk 41 above)
Comment (aescolar-ot) [reply arch/posix/CMakeLists.txt]: The reason to do it this way, is because in this manner it is transparent to the application.
Otherwise posix_cheats.h needs to be included in all the applications' files which define main( ), and in any app file which uses the pthreads like API provided by Zephyr ( include/posix/pthread.h / kernel/pthread.c ) [And any future API added to Zephyr which will clash with the native POSIX API] . It would also need to be included in a few zephyr kernel files.

But I do agree that a comment explaining this would help => will add it.

File: arch/posix/CMakeLists.txt (hunk 40 above)
Comment (aescolar-ot) [reply arch/posix/CMakeLists.txt]: I don't think it would be good to put it in the cheat file (this macro is meant for the native standard headers) => I like more your first proposal

File: arch/posix/CMakeLists.txt (hunk 39 above)
Comment (aescolar-ot) [reply arch/posix/CMakeLists.txt]: => @nashif

File: CMakeLists.txt (hunk 38 above)
Comment (aescolar-ot) [reply CMakeLists.txt]: => @nashif

File: CMakeLists.txt (hunk 36 above)
Comment (aescolar-ot) [reply CMakeLists.txt]: => @nashif

File: arch/posix/CMakeLists.txt (hunk 41 above)
Comment (SebastianBoe) [reply arch/posix/CMakeLists.txt]: I suspect it is possible to solve the main problem by changing the entry point
and that it is possible to solve the API problem by modifying include paths,
but I am OK with this change as long as it is documented in such a way that
we can fix it later.

File: boards/posix/doc/board.rst [hunk 42]
```diff
@@ -0,0 +1,158 @@
+.. _simple_process:
+
+Native POSIX execution (Simpe_process)
```
Comment (dbkinder) [inline boards/posix/doc/board.rst]: s/Simpe/Simple/

File: boards/posix/doc/board.rst [hunk 43]
```diff
@@ -0,0 +1,158 @@
+.. _simple_process:
```
Comment (dbkinder) [inline boards/posix/doc/board.rst]: Perhaps a more meaningful doc link name would be ``native_posix`` ?

File: .shippable.yml [hunk 44]
```diff
@@ -28,6 +28,7 @@ build:
         options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"
 
     ci:
+      - sudo apt-get install gcovr gcc-6-multilib
```
[the remark this answers is not in the document]
Comment (dbkinder) [reply .shippable.yml]: Yes,  the posix board doc is a fine place to explain dependencies and usage.  There may be a need to branch it into multiple docs if there are significant differences on the host platform OS. Is this only going to work on Linux and maybe macOS systems, not Windows, (but maybe Windows Subsystem for Linux).

File: boards/posix/doc/board.rst [hunk 45]
```diff
@@ -0,0 +1,158 @@
...
+
+Debugging
+=========
+
+As the resulting executable is a native application it can be debuged and
+instrumented like any other native program. The program is compiled with debug
+information, so it can be run directly in for example gdb or instrumented with
+valgrind.
+
+Note that as the execution is fully deterministic (there is no asynchronous or
```
Comment (dbkinder) [inline boards/posix/doc/board.rst]: Change to:

    Because the execution of your Zephyr application is fully deterministic
    (there are no asynchronous or random components), you can execute the
    code multiple times and get the exact same result and instrumenting the
    code does not affect the execution of the code.

File: boards/posix/doc/board.rst [hunk 46]
```diff
@@ -0,0 +1,158 @@
...
+
+Overview
+********
+
+Using this board, Zephyr applications can be compiled together with
+the Zephyr kernel as exectuables for the native / host OS.
+In this manner one can debug and instrument the code with better visibility
+and debug-ability. The resulting application is just a normal console
+executable.
+
```
Comment (dbkinder) [inline boards/posix/doc/board.rst]: This is a good place to add a section documenting host system dependencies:  Does this only work on Linux hosts?  What about macOS or Windows Subsystem for Linux (or msys2)?

Also, document software and libraries: you mention installing gcc-multilib package on Ubuntu below.

**Review by dbkinder — CHANGES_REQUESTED** [review]
Thanks for getting the docs started.  I see some good discussions and explanations in the PR comments that could be included here too

File: arch/Kconfig [hunk 47]
```diff
@@ -163,6 +176,15 @@ config ARCH_HAS_USERSPACE
 config ARCH_HAS_EXECUTABLE_PAGE_BIT
 	bool
 
+#
+# Other architecture related options
+#
+
+config ARCH_REQUIRES_LIBC
+
```
Comment (aescolar-ot) [inline arch/Kconfig]: missing:
	bool

File: arch/posix/core/thread.c [hunk 48]
```diff
@@ -0,0 +1,89 @@
...
+	thread_status = (posix_thread_status_t *)
+		STACK_ROUND_DOWN(stack_memory + stack_size
+				- sizeof(*thread_status));
+
+	/* _thread_entry() arguments */
+	thread_status->entry_point = thread_func;
+	thread_status->arg1 = arg1;
+	thread_status->arg2 = arg2;
+	thread_status->arg3 = arg3;
+#if defined(CONFIG_ARCH_HAS_THREAD_ABORT)
```
Comment (nvlsianpu) [inline arch/posix/core/thread.c]: CONFIG_ARCH_HAS_THREAD_ABORT is something not configurable for POSIX arch. I;m OK with this #ifdef here, but maybe preprocessor assertion will be better.

File: arch/posix/include/asm_inline_gcc.h [hunk 49]
```diff
@@ -0,0 +1 @@
+/* EMTPTY ON PURPOSE. Why do the intel and ARM arch have 2 versions of it? */
```
Comment (nvlsianpu) [inline arch/posix/include/asm_inline_gcc.h]: @nashif  has zephyr a convention on this.

File: arch/posix/include/asm_inline.h [hunk 50]
```diff
@@ -0,0 +1,24 @@
...
+
+#ifndef _ASM_INLINE_H
+#define _ASM_INLINE_H
+
+#if !defined(CONFIG_ARCH_POSIX)
+#error The arch/posix/include/asm_inline.h is only for the POSIX architecture
+#endif
+
+#if defined(__GNUC__)
+#include <asm_inline_gcc.h> /* The empty one.. */
```
Comment (nvlsianpu) [inline arch/posix/include/asm_inline.h]: Are this and next line referencing the same header?

File: arch/posix/core/thread.c (hunk 48 above)
Comment (aescolar-ot) [reply arch/posix/core/thread.c]: Uhm, why do consider it not configurable? [The code should work with it set or not, even if the config file sets it always by default]

File: arch/posix/include/asm_inline.h (hunk 50 above)
Comment (aescolar-ot) [reply arch/posix/include/asm_inline.h]: Nope, one is ./arch/posix/include/asm_inline.h , the other ./include/arch/posix/asm_inline.h.

File: arch/posix/include/asm_inline_gcc.h (hunk 49 above)
Comment (aescolar-ot) [reply arch/posix/include/asm_inline_gcc.h]: I was a bit puzzled when I saw those other archs having 2 versions of the file which share a lot of the content.. I would be happy if somebody could give an explanation.
In the meanwhile I created the empty one so there would no problems with includes.

File: arch/posix/core/thread.c (hunk 48 above)
Comment (nvlsianpu) [reply arch/posix/core/thread.c]: that I understand - but i see that this patch intention is to have it always selected.  let keep it as is.

File: boards/posix/simple_process/CMakeLists.txt (hunk 11 above)
Comment (nashif) [reply boards/posix/simple_process/CMakeLists.txt]: maybe just call it **native**

File: boards/posix/simple_process/doc/board.rst [hunk 51]
```diff
@@ -0,0 +1,179 @@
...
+As simulated time does not pass while the CPU is running, it also means no HW
+interrupts will interrupt the threads' execution unless the SW enables or
+unmasks them.
+This is intentional, as it provides a deterministic environment to develop and
+debug.
+But note that this may hide issues in the SW that may only be triggered in the
+real platform.
+
+This native port of Zephyr is not meant to, and could not possibly
+help debuggin races between HW and SW, or similar timing related issues.
```
Comment (dbkinder) [inline boards/posix/simple_process/doc/board.rst]: ``help debug``

File: boards/posix/simple_process/doc/board.rst [hunk 52]
```diff
@@ -0,0 +1,179 @@
...
+   :goals: build
+   :compact:
+
+
+Running
+=======
+
+The result of the compilation is an executable (zephyr.exe) placed in the
+zephyr/ subdirectory of the build folder.
+Run the zephyr.exe executable as you would any other Linux console application.
```
Comment (dbkinder) [inline boards/posix/simple_process/doc/board.rst]: does the developer need to do a chmod +x on zephyr.exe?

File: boards/posix/simple_process/doc/board.rst [hunk 53]
```diff
@@ -0,0 +1,179 @@
...
+If you want your application to gracefully finish when it reaches some point,
+you may add a conditionally compiled (CONFIG_BOARD_SIMPLE_PROCESS) call to
+``main_clean_up(exit_code)`` at that point.
+
+
+Debugging
+=========
+
+Since the Zephyr executable is a native application, it can be debuged and
+instrumented like any other native program. The program is compiled with debug
```
Comment (dbkinder) [inline boards/posix/simple_process/doc/board.rst]: change ``like`` to ``as``

**Review by dbkinder — CHANGES_REQUESTED** [review]
getting closer

File: boards/posix/simple_process/doc/board.rst (hunk 52 above)
Comment (aescolar-ot) [reply boards/posix/simple_process/doc/board.rst]: No, it is executable already

File: boards/posix/simple_process/doc/board.rst [hunk 54]
```diff
@@ -0,0 +1,179 @@
...
+a native application on the host OS, without emulation.  Instead,
+you use native host tools for compiling, debugging, and analyzing your
+Zephyr application, eliminating the need for architecture-specific
+target hardware in the early phases of development.
+
+Host system dependencies
+========================
+
+This port is designed to run in POSIX compatible operating systems.
+It has only been tested on Linux, but should also be compatible with MacOS.
```
[the remark this answers is not in the document]
Comment (aescolar-ot) [reply boards/posix/simple_process/doc/board.rst]: Thank you very much David

File: boards/posix/simple_process/doc/board.rst [hunk 55]
```diff
@@ -0,0 +1,179 @@
...
+
+Host system dependencies
+========================
+
+This port is designed to run in POSIX compatible operating systems.
+It has only been tested on Linux, but should also be compatible with macOS.
+
+.. note::
+
+   Remember that you must have the 32-bit C library installed in your system
```
Comment (dbkinder) [inline boards/posix/simple_process/doc/board.rst]: Reading this again, saying "remember" implies you've told them this before.  So let's just say, ``You must have ...``

File: boards/posix/simple_process/doc/board.rst [hunk 56]
```diff
@@ -0,0 +1,179 @@
...
+the issue of code execution speed is ignored.
+The board uses a different time than real time: simulated time.
+This simulated time is, in principle, not linked to the host time.
+
+The Zephyr application sees the code executing as if the CPU were running at
+an infinitely high clock, and fully decoupled from the underlying host CPU
+speed.
+No simulated time passes while the application or kernel code execute.
+
+The CPU boot is emulated by creating the Zephyr initialiation thread and
```
Comment (dbkinder) [inline boards/posix/simple_process/doc/board.rst]: ``initialization``

File: boards/posix/simple_process/doc/board.rst [hunk 57]
```diff
@@ -0,0 +1,179 @@
...
+letting it run. This in turn may spawn more Zephyr threads.
+Eventually the SW will run to completion, that is, it will set the CPU
+back to sleep.
+
+At this point, control is transferred back to the HW models and the simulation
+time can be advanced.
+
+When the HW models raise an interrupt, the CPU wakes back: the interrupt
```
Comment (dbkinder) [inline boards/posix/simple_process/doc/board.rst]: ``wakes back up`` or ``awakens``

**Review by dbkinder — CHANGES_REQUESTED** [review]
a few more issues in the doc

**Review by nashif — CHANGES_REQUESTED** [review]
I do not think it is a good idea to make this distinction here and by default forcing us to add CONFIG_SIMPLE_PROCESS_SLOWDOWN_TO_REAL_TIME to all samples we have right now and anything we might add in the future. Instead, have the normal speed by default and make it faster for example using the test config in tests/include/test.config for tests.

Lets keep all of those sample simple and working with the default configuration options.

**Review by dbkinder — APPROVED** [review]
+1 for docs, thanks.

**Review by nashif — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
