### PR TITLE
soc: fix some configuration error of arc emsdp

### LINKED ISSUE #25510: arc EMSDP failed in tests/kernel/gen_isr_table
**Describe the bug**
ARC EMSDP failed in tests/kernel/gen_isr_table because of wrong irq info.

**To Reproduce**
1. ./scripts/sanitycheck -p emsdp --device-testing --device-serial /dev/ttyUSB0 -T tests/kernel/gen_isr_table
2. See error

### PR DESCRIPTION
**Pull request by vonhust**
* arc emsdp has 112 interrupts at maximum, not 128
  * arc emsdp's console will use irq 108/107 which will
    conflict with irqs used in tests/kernel/gen_isr_table (emsdp has 112 irqs),
    so add a workaround for emsdp.

Fixes #25510

### CODE REVIEW

File: tests/kernel/gen_isr_table/src/main.c [hunk 1]
```diff
@@ -32,6 +32,14 @@ extern u32_t _irq_vector_table[];
 #define ISR5_OFFSET	4
 #define ISR6_OFFSET	5
```
Comment (abrodkin) [inline tests/kernel/gen_isr_table/src/main.c:34]: Is there any other way to fixing a problem rather than adding board-specific dependencies in generic tests? This significantly complicates maintenance of both test and boards involved.

**Review by abrodkin — CHANGES_REQUESTED** [review]
Please add a reference for the documentation where this technical detail is stated. Even though this document might not be public (which we need to fix I guess) it's good to refer to even internal documents so that the next reader may double-check it if needed.

Note there's publicly available "User's manual" for the EM SDP (see https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/docs/ARC_EM_SDP_User_Guide.pdf) but it doesn't seem to include "SoC" configuration details as we're talking about FPGA here and there're a couple of different FPGA images shipped with the board.

**Comment by vonhust** [comment]
> Please add a reference for the documentation where this technical detail is stated. Even though this document might not be public (which we need to fix I guess) it's good to refer to even internal documents so that the next reader may double-check it if needed.
> 
> Note there's publicly available "User's manual" for the EM SDP (see https://github.com/foss-for-synopsys-dwc-arc-processors/ARC-Development-Systems-Forum/wiki/docs/ARC_EM_SDP_User_Guide.pdf) but it doesn't seem to include "SoC" configuration details as we're talking about FPGA here and there're a couple of different FPGA images shipped with the board.


No info in doc, 112 comes from the tcf file of emsdp configurations.

File: tests/kernel/gen_isr_table/src/main.c (hunk 1 above)
Comment (vonhust) [reply tests/kernel/gen_isr_table/src/main.c:34]: This test needs target-specific irq info.  Using the last several irq makes senses for most targets as they are rarely used.  EMSDP is an exception whose USB-JTAG use 108/107 irq.  In some way, it's not a good design in hardware.

**Comment by ruuddw** [comment]
The ARC EM-SDP board has an FGPA with different platform packages. These differ in the CPU subsystem that is used. The CPU subsystem configuration is not in the common EM SDP User Manual, but in the platform package documentation:
- EMx Sensor & Control subsystem: number_of_interrupts 98 (78 external)
- EMxD Data Fusion Subsystem: number_of_interrupts 96 (77 external)
- EM7D ESP: number of interrupts 97 (77 external)

Please fix accordingly.

**Review by ruuddw — CHANGES_REQUESTED** [review]
Different variants have different number of interrupts, see comment.

**Review by ruuddw — APPROVED** [review]
Thanks for updating.

**Comment by ruuddw** [comment]
Thanks Wayne - was there an issue for the emsdp failing test? Please add the link and mark this as a bugfix for 2.3.

**Review by abrodkin — APPROVED** [review]

File: tests/kernel/gen_isr_table/src/main.c [hunk 2]
```diff
@@ -32,6 +32,14 @@ extern u32_t _irq_vector_table[];
...
 
+#if defined(CONFIG_SOC_ARC_EMSDP)
```
Comment (nashif) [inline tests/kernel/gen_isr_table/src/main.c:35]: I would do this workaround in the testcase.yaml instead of here. Lets keep the test soc code free.

Comment (vonhust) [reply tests/kernel/gen_isr_table/src/main.c:35]: ok, will do that

Comment (vonhust) [reply tests/kernel/gen_isr_table/src/main.c:35]: I think we can't  change  CONFIG_NUM_IRQS in testcase.yaml.  For emsdp's case , the console irq will use irq 107/108,  if change CONFIG_NUM_IRQS to 105 globally,  console's irq cannot be used , then no console out.


A fast fix is just like what i did, although it's ugly.

A better fix is to let IRQ_LINE not rely on CONFIG_NUM_IRQS,  but a value may be redefined by application or boards, e.g,  CONFIG_TEST_NUM_IRQS whose default val is CONFIG_NUM_IRQS.
