### PR TITLE
drivers/entropy: stm32: RNG  configuration on some MCUs

### LINKED ISSUE #45866: drivers/entropy: stm32: non-compliant RNG configuration on some MCUs
**Describe the bug**
On some STM32 MCUs, such as the STM32H723 or STM32L5, the RNG peripheral must be configured according to specific values provided in the reference manual to obtain best latency and to be compliant with NIST. This includes:
* Writing appropriate values to CONFIG1, CONFIG2 and CONFIG3 fields in RNG_CR register.
* Writing a proper value in RNG_HTCR register. 

However, it seems that the RNG driver:
* Does not write CONFIGx fields, although their reset value does not correspond to the recommended configuration.
* Does not properly follow the process specified in the reference manual to write to RNG_HTCR. Indeed, CONDRST is not set before writing to RNG_HTCR, even though the [RM0468](https://www.st.com/resource/en/reference_manual/rm0468-stm32h723733-stm32h725735-and-stm32h730-value-line-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) states (p. 1440):
> Writing in RNG_HTCR is taken into account only if CONDRST bit is set, and CONFIGLOCK bit is cleared in RNG_CR. Writing to this register is ignored if CONFIGLOCK=1.

**To Reproduce**
N/A

**Expected behavior**
The STM32 RNG peripheral should be properly configured. 

**Impact**
RNG configuration is not compliant with NIST and entropy generation latency might not be ideal. 

**Environment**
 Commit e9d3791

**Additional context**
Note that I unfortunately have no STM32 MCU with a RNG peripheral having such configuration fields at my disposal, so this issue is only based on my understanding of the reference manual and the driver implementation. In case the issue turns out to be real, I am willing to create a PR but I won't be able to test the fix on real hardware.

### PR DESCRIPTION
**Pull request by FRASTM**
for the entropy/ RNG of some stm32 mcus (like stm32L5x and stm32U5 and stm32H723) when the RNG peripheral has a 
Health Test Control and COND the sequence to
Two properties are defined by the RNG node : 
```
			health-test-magic = <0x17590abc>;
 			health-test-config = <0x9aae>;
```
According to the ref man, the sequence for writing the RNG_HTCR requires to LL_RNG_EnableCondReset before and LL_RNG_DisableCondReset after writing the RNG_HTCR.
According to the ref Man : "When CONDRST is set to 0 by software its value goes to 0 when the reset process is done.
It takes about 2 AHB clock cycles + 2 RNG clock cycles."
This PR adds a loop to wait for the bit to be read as 0.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/45866

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
tested with  west build -p auto -b xxx tests/drivers/entropy/api/ 
on  nucleo_u575zi_q and nucleo_l552ze_q
```
*** Booting Zephyr OS build v3.1.0-rc2-12-g74ae95ce7ba9  ***
Running TESTSUITE entropy_api
===================================================================
START - test_entropy_get_entropy
random device is 0x8005b94, name is RNG
  0x8b
  0x47
  0x02                                           
  0x8f                                           
  0x52                                           
  0x2c                                           
  0xf2                                           
  0x01
  0x03
 PASS - test_entropy_get_entropy in 0.10 seconds
===================================================================
TESTSUITE entropy_api succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL  
```

File: drivers/entropy/entropy_stm32.c [hunk 1]
```diff
@@ -103,6 +103,9 @@ static void configure_rng(void)
 {
 	RNG_TypeDef *rng = entropy_stm32_rng_data.rng;
 
+#ifdef STM32_CONDRST_SUPPORT
```
Comment (erwango) [inline drivers/entropy/entropy_stm32.c:106]: How is this flag defined?

Comment (FRASTM) [reply drivers/entropy/entropy_stm32.c:106]: the flag is defined by the presence of bit RNG_CR_CONDRST in the RNG CR of the peripheral

**Review by GeorgeCGV — COMMENTED** [review]
Shouldn't lines [106, 108]:
https://github.com/zephyrproject-rtos/zephyr/blob/d8065a5a24a2fa7915fba8d7d0df8a7d265f96fd/drivers/entropy/entropy_stm32.c#L106-L108

and [119, 123]:
https://github.com/zephyrproject-rtos/zephyr/blob/d8065a5a24a2fa7915fba8d7d0df8a7d265f96fd/drivers/entropy/entropy_stm32.c#L119-L123

be moved inside the `DT_INST_NODE_HAS_PROP(0, health_test_config)` check, around `LL_RNG_SetHealthConfig`?

**Comment by taltenbach** [comment]
When CONDRST is set, RNG is re-initialized, which adds a latency before entropy to be available. On single core MCUs, `configure_rng()` is done only at entropy driver initialization so this is fine. However, on multi-core MCUs such as STM32H747, `configure_rng()` is invoked for every new entropy generation process and it is probably desirable to avoid useless RNG re-initialization by checking first is RNG_HTCR is already set to the desired value.
Note that currently no STM32 MCUs supporting CONDRST are multi-core, but that might change in the future, leading to performance issues.

**Comment by FRASTM** [comment]
New version of the driver with the introduction of the `nist-config` property

**Comment by FRASTM** [comment]
>

**Comment by taltenbach** [comment]
> > On multi-core MCUs such as STM32H747, configure_rng() is invoked for every new entropy generation process and it might be worth checking if RNG_HTCR is already set to the desired value to avoid useless RNG re-initialization.
> 
> In this case, the configure_rng() is done by the acquire_rng(), and could be :
> 
> ```
> static void acquire_rng(void)
> {
> #if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_STM32H7_DUAL_CORE)
> 	/* Lock the RNG to prevent concurrent access */
> 	z_stm32_hsem_lock(CFG_HW_RNG_SEMID, HSEM_LOCK_WAIT_FOREVER);
> 	/* RNG configuration could have been changed by the other core */
> 	if (LL_RNG_GetHealthConfig(rng) != DT_INST_PROP(0, health_test_config)) {
> 		configure_rng();
> 	}
> #endif /* CONFIG_SOC_SERIES_STM32WBX || CONFIG_STM32H7_DUAL_CORE */
> }
> ```

This is not possible because `configure_rng()` does not only write RNG_HTCR and perform NIST-related configuration, it also enables the RNG and RNG IRQ, which could have been disabled by the other core. For example on STM32WB55, the M0 core disable the RNG after use.

File: drivers/entropy/entropy_stm32.c (hunk 1 above)
Comment (erwango) [reply drivers/entropy/entropy_stm32.c:106]: right, I've missed it. Txs

File: drivers/entropy/entropy_stm32.c [hunk 2]
```diff
@@ -103,17 +103,46 @@ static void configure_rng(void)
...
+		RNG_CR_RNG_CONFIG2 | RNG_CR_RNG_CONFIG3 | RNG_CR_ARDIS,
+		(uint32_t)(RNG_CR_CONDRST | DT_INST_PROP(0, nist_config)));
+#else /* RNG_CR_ARDIS */
+	MODIFY_REG(rng->CR,
+		RNG_CR_NISTC | RNG_CR_CLKDIV | RNG_CR_RNG_CONFIG1 |
+		RNG_CR_RNG_CONFIG2 | RNG_CR_RNG_CONFIG3,
+		(uint32_t)(RNG_CR_CONDRST | DT_INST_PROP(0, nist_config)));
+#endif /* RNG_CR_ARDIS */
+#else /* nist_config */
+	LL_RNG_EnableCondReset(rng);
```
Comment (GeorgeCGV) [inline drivers/entropy/entropy_stm32.c:127]: `LL_RNG_EnableCondReset(rng)` is executed only if `#if DT_INST_NODE_HAS_PROP(0, nist_config)`.
Is it then correct to always do `LL_RNG_DisableCondReset(rng);` (_lines [141, 144]_) even if `nist_config` is not present?

**Review by mbolivar-nordic — COMMENTED** [review]
No objections from me

**Review by ceolin — DISMISSED** [review]

**Comment by erwango** [comment]
> > > On multi-core MCUs such as STM32H747, configure_rng() is invoked for every new entropy generation process and it might be worth checking if RNG_HTCR is already set to the desired value to avoid useless RNG re-initialization.
> > 
> > 
> > In this case, the configure_rng() is done by the acquire_rng(), and could be :
> > ```
> > static void acquire_rng(void)
> > {
> > #if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_STM32H7_DUAL_CORE)
> > 	/* Lock the RNG to prevent concurrent access */
> > 	z_stm32_hsem_lock(CFG_HW_RNG_SEMID, HSEM_LOCK_WAIT_FOREVER);
> > 	/* RNG configuration could have been changed by the other core */
> > 	if (LL_RNG_GetHealthConfig(rng) != DT_INST_PROP(0, health_test_config)) {
> > 		configure_rng();
> > 	}
> > #endif /* CONFIG_SOC_SERIES_STM32WBX || CONFIG_STM32H7_DUAL_CORE */
> > }
> > ```
> 
> This is not possible because `configure_rng()` does not only write RNG_HTCR and perform NIST-related configuration, it also enables the RNG and RNG IRQ, which could have been disabled by the other core. For example on STM32WB55, the M0 core disables the RNG after use.
> 
> This also assumes the other core won't change NIST-related configuration (in RNG_CR) without also modifying RNG_HTCR, but I guess in any real world scenario all cores in a MCU will use the exact same "NIST configuration", so that may not be actually an issue

@taltenbach so is it fine from this perspective ?

**Comment by taltenbach** [comment]
> > > > On multi-core MCUs such as STM32H747, configure_rng() is invoked for every new entropy generation process and it might be worth checking if RNG_HTCR is already set to the desired value to avoid useless RNG re-initialization.
> > > 
> > > 
> > > In this case, the configure_rng() is done by the acquire_rng(), and could be :
> > > ```
> > > static void acquire_rng(void)
> > > {
> > > #if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_STM32H7_DUAL_CORE)
> > > 	/* Lock the RNG to prevent concurrent access */
> > > 	z_stm32_hsem_lock(CFG_HW_RNG_SEMID, HSEM_LOCK_WAIT_FOREVER);
> > > 	/* RNG configuration could have been changed by the other core */
> > > 	if (LL_RNG_GetHealthConfig(rng) != DT_INST_PROP(0, health_test_config)) {
> > > 		configure_rng();
> > > 	}
> > > #endif /* CONFIG_SOC_SERIES_STM32WBX || CONFIG_STM32H7_DUAL_CORE */
> > > }
> > > ```
> > 
> > 
> > This is not possible because `configure_rng()` does not only write RNG_HTCR and perform NIST-related configuration, it also enables the RNG and RNG IRQ, which could have been disabled by the other core. For example on STM32WB55, the M0 core disables the RNG after use.
> > This also assumes the other core won't change NIST-related configuration (in RNG_CR) without also modifying RNG_HTCR, but I guess in any real world scenario all cores in a MCU will use the exact same "NIST configuration", so that may not be actually an issue
> 
> @taltenbach so is it fine from this perspective ?



> > > > On multi-core MCUs such as STM32H747, configure_rng() is invoked for every new entropy generation process and it might be worth checking if RNG_HTCR is already set to the desired value to avoid useless RNG re-initialization.
> > > 
> > > 
> > > In this case, the configure_rng() is done by the acquire_rng(), and could be :
> > > ```
> > > static void acquire_rng(void)
> > > {
> > > #if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_STM32H7_DUAL_CORE)
> > > 	/* Lock the RNG to prevent concurrent access */
> > > 	z_stm32_hsem_lock(CFG_HW_RNG_SEMID, HSEM_LOCK_WAIT_FOREVER);
> > > 	/* RNG configuration could have been changed by the other core */
> > > 	if (LL_RNG_GetHealthConfig(rng) != DT_INST_PROP(0, health_test_config)) {
> > > 		configure_rng();
> > > 	}
> > > #endif /* CONFIG_SOC_SERIES_STM32WBX || CONFIG_STM32H7_DUAL_CORE */
> > > }
> > > ```
> > 
> > 
> > This is not possible because `configure_rng()` does not only write RNG_HTCR and perform NIST-related configuration, it also enables the RNG and RNG IRQ, which could have been disabled by the other core. For example on STM32WB55, the M0 core disables the RNG after use.
> > This also assumes the other core won't change NIST-related configuration (in RNG_CR) without also modifying RNG_HTCR, but I guess in any real world scenario all cores in a MCU will use the exact same "NIST configuration", so that may not be actually an issue
> 
> @taltenbach so is it fine from this perspective ?

It is not in the sense the RNG is reconfigured even if the current configuration was already the proper one. A simple check in `configure_rng()` of the current `RNG_CR` and `RNG_HTCR` values would be sufficient to avoid that. But, as I said, since at present all STM32 MCUs supporting CONDRST are single-core, meaning that `configure_rng()` is only called once at startup, that is not a real issue at the moment, but might be in the future.

**Comment by FRASTM** [comment]
> > > > > On multi-core MCUs such as STM32H747, configure_rng() is invoked for every new entropy generation process and it might be worth checking if RNG_HTCR is already set to the desired value to avoid useless RNG re-initialization.
> > > > 
> > > > 
> > > > In this case, the configure_rng() is done by the acquire_rng(), and could be :
> > > > ```
> > > > static void acquire_rng(void)
> > > > {
> > > > #if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_STM32H7_DUAL_CORE)
> > > > 	/* Lock the RNG to prevent concurrent access */
> > > > 	z_stm32_hsem_lock(CFG_HW_RNG_SEMID, HSEM_LOCK_WAIT_FOREVER);
> > > > 	/* RNG configuration could have been changed by the other core */
> > > > 	if (LL_RNG_GetHealthConfig(rng) != DT_INST_PROP(0, health_test_config)) {
> > > > 		configure_rng();
> > > > 	}
> > > > #endif /* CONFIG_SOC_SERIES_STM32WBX || CONFIG_STM32H7_DUAL_CORE */
> > > > }
> > > > ```
> > > 
> > > 
> > > This is not possible because `configure_rng()` does not only write RNG_HTCR and perform NIST-related configuration, it also enables the RNG and RNG IRQ, which could have been disabled by the other core. For example on STM32WB55, the M0 core disables the RNG after use.
> > > This also assumes the other core won't change NIST-related configuration (in RNG_CR) without also modifying RNG_HTCR, but I guess in any real world scenario all cores in a MCU will use the exact same "NIST configuration", so that may not be actually an issue
> > 
> > 
> > @taltenbach so is it fine from this perspective ?
> 
> It is not in the sense the RNG is reconfigured even if the current configuration was already the proper one. A simple check in `configure_rng()` of the current `RNG_CR` and `RNG_HTCR` values would be sufficient to avoid that. But, as I said, since at present all STM32 MCUs supporting CONDRST are single-core, meaning that `configure_rng()` is only called once at startup, so that is not a real issue at the moment, but might be in the future.

 Do you expect acquire_rng() to check the LL_RNG_GetHealthConfig before going to configure_rng() as follows: 
```
static void acquire_rng(void)
{
#if defined(CONFIG_SOC_SERIES_STM32WBX) || defined(CONFIG_STM32H7_DUAL_CORE)
	/* Lock the RNG to prevent concurrent access */
	z_stm32_hsem_lock(CFG_HW_RNG_SEMID, HSEM_LOCK_WAIT_FOREVER);
	/* RNG configuration could have been changed by the other core */
	if (LL_RNG_GetHealthConfig(rng) != DT_INST_PROP(0, health_test_config)) {
		configure_rng();
	}
#endif /* CONFIG_SOC_SERIES_STM32WBX || CONFIG_STM32H7_DUAL_CORE */
}
```

**Comment by taltenbach** [comment]
For the reasons exposed above, this is not possible in particular because there is some code in `configure_rng()` that must be executed even if the value of RNG_HTCR is correct. I was thinking of something like the following. Note this is just a quick draft to clarify my idea, I didn't actually test the code.
```
static void configure_rng(void)
{
	RNG_TypeDef *rng = entropy_stm32_rng_data.rng;

#ifdef STM32_CONDRST_SUPPORT
	uint32_t desired_nist_cfg = DT_INST_PROP_OR(0, nist_config, 0U);
	uint32_t desired_htcr = DT_INST_PROP_OR(0, health_test_config, 0U);
	uint32_t cur_nist_cfg = 0U;
	uint32_t cur_htcr = 0U;

#if DT_INST_NODE_HAS_PROP(0, nist_config)
#if defined(RNG_CR_ARDIS)
	cur_nist_cfg = rng->CR & (RNG_CR_NISTC | RNG_CR_CLKDIV | RNG_CR_RNG_CONFIG1 |
				  RNG_CR_RNG_CONFIG2 | RNG_CR_RNG_CONFIG3 | RNG_CR_ARDIS);
#else /* RNG_CR_ARDIS */
	cur_nist_cfg = rng->CR & (RNG_CR_NISTC | RNG_CR_CLKDIV | RNG_CR_RNG_CONFIG1 |
				  RNG_CR_RNG_CONFIG2 | RNG_CR_RNG_CONFIG3);
#endif /* RNG_CR_ARDIS */
#endif /* nist_config */

#if DT_INST_NODE_HAS_PROP(0, health_test_config)
	cur_htcr = LL_RNG_GetHealthConfig(rng);
#endif /* health_test_config */

	if (cur_nist_cfg != desired_nist_cfg || cur_htcr != desired_htcr) {
		rng->CR = (rng->CR & ~cur_nist_cfg) | (desired_nist_cfg | RNG_CR_CONDRST);

#if DT_INST_NODE_HAS_PROP(0, health_test_config)
#if DT_INST_NODE_HAS_PROP(0, health_test_magic)
		LL_RNG_SetHealthConfig(rng, DT_INST_PROP(0, health_test_magic));
#endif /* health_test_magic */
		LL_RNG_SetHealthConfig(rng, desired_htcr);
#endif /* health_test_config */

		LL_RNG_DisableCondReset(rng);
		while (LL_RNG_IsEnabledCondReset(rng)) {
		}
	}
#endif /* STM32_CONDRST_SUPPORT */

	LL_RNG_Enabled(rng);
	LL_RNG_EnableIT(rng);
}
```

**Comment by FRASTM** [comment]
Put the sequence to write the RNG_HTCR  in the configure_rng() as exposed above
Tested with a `health-test-magic = <0x00009aae>; `property in the overlay of the stm32u575 nucleo board.

**Comment by FRASTM** [comment]
>

File: dts/arm/st/l5/stm32l5.dtsi [hunk 3]
```diff
@@ -413,6 +413,8 @@
 			health-test-config = <0xa2b3>;
 			status = "disabled";
 			label = "RNG";
+			health-test-magic = <0xf00d00>;
```
Comment (taltenbach) [inline dts/arm/st/l5/stm32l5.dtsi:417]: From the value I guess that should be `nist-config` instead of `health-test-magic`

File: dts/arm/st/l5/stm32l5.dtsi [hunk 4]
```diff
@@ -413,6 +413,8 @@
...
+			health-test-config = <0xa2b3>;
```
Comment (taltenbach) [inline dts/arm/st/l5/stm32l5.dtsi:418]: Duplicate

File: dts/arm/st/h7/stm32h7a3.dtsi [hunk 5]
```diff
@@ -47,6 +47,11 @@
 			label = "LTDC";
 			status = "disabled";
 		};
+
+		rng: rng@48021800 {
+			nist-config = <0xf00d00>;
+			health-test-magic = <0x72ac>;
```
Comment (taltenbach) [inline dts/arm/st/h7/stm32h7a3.dtsi:53]: The value of `health-test-magic` should be `0x17590abc`, `0x72ac` is the value of `health-test-config`, which seem to be missing

**Review by taltenbach — CHANGES_REQUESTED** [review]

File: dts/arm/st/u5/stm32u5.dtsi [hunk 6]
```diff
@@ -388,6 +388,8 @@
 			health-test-config = <0x9aae>;
 			status = "disabled";
 			label = "RNG";
+			nist-config = <0xf60d00>;
+			health-test-magic = <0x9aae>;
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply dts/arm/st/u5/stm32u5.dtsi:392]: but, The RM gives a RNG config table: 
[stm32u5_RNG.pdf](https://github.com/zephyrproject-rtos/zephyr/files/9081745/stm32u5_RNG.pdf)

**Comment by FRASTM** [comment]
The register magic number ` health-test-magic = <0x17590abc> `   is given by the RM of the stm32h7a3/b3 and the stm32l5x 
"When writing this register magic number 0x17590ABC must be written immediately before the indicated value"

There is no register magic number given for the stm32u5x.

File: dts/arm/st/h7/stm32h7a3.dtsi [hunk 7]
```diff
@@ -47,6 +47,11 @@
 			label = "LTDC";
 			status = "disabled";
 		};
+
+		rng: rng@48021800 {
+			nist-config = <0xf00d00>;
+			health-test-magic = <0x17590abc>;
```
Comment (taltenbach) [inline dts/arm/st/h7/stm32h7a3.dtsi:53]: `health-test-config` value still seem to be missing

File: dts/arm/st/l5/stm32l5.dtsi [hunk 8]
```diff
@@ -414,6 +414,8 @@
 			health-test-config = <0xa2b3>;
 			status = "disabled";
 			label = "RNG";
+			nist-config = <0xf00d00>;
+			health-test-magic = <0x17590abc>;
```
Comment (taltenbach) [inline dts/arm/st/l5/stm32l5.dtsi:418]: Duplicate: `health-test-magic` already set at line 413

**Review by taltenbach — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
rebase on bfb65b054cd8cdad4169be2fd6b79b200d22d593
add <nist-config>    <health-test-magic> <health-test-config>  properties on stm32u5 stm32l5 and stm32h7a3 on RNG node

**Review by taltenbach — DISMISSED** [review]

**Review by ceolin — DISMISSED** [review]

**Review by erwango — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
@FRASTM can you rebase this please?

**Comment by carlescufi** [comment]
@FRASTM please rebase

**Comment by FRASTM** [comment]
- rebase on 5897de1e535816247e309348cbe29760361a28b8
- fix conflict

**Review by erwango — DISMISSED** [review]

**Comment by erwango** [comment]
@ceolin would you mind re-approve following rebase ?

**Review by fabiobaltieri — DISMISSED** [review]

**Comment by FRASTM** [comment]
rebase on f3017aa787e75c77bb7deb9f4ae45d4b4e93fbc3

**Review by fabiobaltieri — APPROVED** [review]

**Review by erwango — APPROVED** [review]
