### PR TITLE
drivers: dma: stm32 dmamux accepts request ID =0 

### LINKED ISSUE #35219: tests: driver: dma test case loop_transfer fails on stm32 with dmamux
**Describe the bug**
When the stm32 has a dmamux, the request ID 0 is not accessible, causing a failure in the memory-to-memory testing.
The test cases `tests/drivers/dma/loop_transfer`  and `tests/drivers/dma/chan_blen_transfer` are failed
especially on nucleo_g474re, nucleo_wb55rg, nucleo_g071rb

**To Reproduce**
1. west build -p auto -b nucleo_g474re tests/drivers/dma/loop_transfer/

**Expected behavior**
test PASSED

**Logs and console output**
```
Running test suite dma_m2m_loop_test                                            
===================================================================             
START - test_dma_m2m_loop                                                       
DMA memory to memory transfer started on DMAMUX_1                               
Preparing DMA Controller                                                        
this platform do not support the dma channel                                    
Starting the transfer on channel 2 and waiting for 1 second                     
E: request ID 0 is not valid.                                                   
ERROR: transfer config (2)                                                      
                                                                                
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/dma/loop_transfer/src/e
                                                                                
 FAIL - test_dma_m2m_loop in 0.35 seconds                                       
===================================================================             
Test suite dma_m2m_loop_test failed.                                            
===================================================================             
PROJECT EXECUTION FAILED                                                        

```
**Environment (please complete the following information):**
 - Commit SHA f05ea6711a730c12dde2c6f8284c50438e992d66

### PR DESCRIPTION
**Pull request by FRASTM**
The DMAMUX request ID = 0 means Memory to Memory transfer.
So this NULL value must be allowed in the list of request IDs.
This will make tests/drivers/dma/loop_transfer pass

Signed-off-by: Francois Ramu francois.ramu@st.com

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/35219

### CODE REVIEW

**Comment by FRASTM** [comment]
Tested tests/drivers/sp/spi_loopback on nucleo_wb55rg, nucleo_g431rb, nucleo_l476rg boards

**Review by str4t0m — APPROVED** [review]
Thanks!

File: drivers/dma/dma_stm32.h [hunk 1]
```diff
@@ -44,14 +44,14 @@ struct dma_stm32_config {
 	struct dma_stm32_stream *streams;
 };
 
-#if defined(CONFIG_DMAMUX_STM32) || defined(CONFIG_DMA_STM32_V2)
+#if !defined(CONFIG_DMA_STM32_V1)
```
Comment (shlomow) [inline drivers/dma/dma_stm32.h:47]: I think there will be a problem with h7 socs. The dma controller is v1 but is has a dmamux. So it should start with 1

Comment (FRASTM) [reply drivers/dma/dma_stm32.h:47]: checking...

**Comment by FRASTM** [comment]
Pushed without  #34666

**Comment by FRASTM** [comment]
The dma of the stm32l0 has a similar configuration.
That was the purpose of the https://github.com/zephyrproject-rtos/zephyr/pull/34666 to adapt for any stm32 family.

**Review by MaureenHelm — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by avisconti — APPROVED** [review]
