### PR TITLE
Bluetooth: TBS: Clear pending notifications on unsub

### LINKED ISSUE #104511: Bluetooth: TBS: Flags are not cleared if client unsubscribes
### Describe the bug

The `struct tbs_flags` contains information about pending notifications and states for each client. The `_changed` flags for notifications are set only if a client is subscribed to changes, at the point in time where the change happens. 

_Technically_, however unlikely, a client may unsubscribe for changes. This can be determined by the `cfg_changed` functions like `current_calls_cfg_changed`. However in those functions, any pending changes are not cleared, which means that pending notifications in `notify_handler_cb` will continuously try to be sent, until the device re-subscribes or disconnects. Additionally, the `try_change_dialing_call_to_alerting` may never succeed due to this. 

The solution is probably to just cleared the `_changed` bits for that client when it unsubscribes. 

### Regression

- [ ] This is a regression.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by leon-xu-04**
If the client removes its subscription to any of the TBS characteristics at any time, the pending appropriate flags are now being cleared.

Fixes zephyrproject-rtos/zephyr#104511

### CODE REVIEW

File: subsys/bluetooth/audio/tbs.c [hunk 1]
```diff
@@ -422,22 +422,28 @@ static void set_value_changed_cb(struct bt_conn *conn, void *data)
...
-	/* We may schedule the same work multiple times, but that is OK as scheduling the same work
-	 * multiple times is a no-op
-	 */
-	err = k_work_schedule(&inst->notify_work, K_NO_WAIT);
-	__ASSERT(err >= 0, "Failed to schedule work: %d", err);
+		/* Check if all flags are cleared, and if so then cancel any pending k_work */
+		if (util_memeq(flags, &(struct tbs_flags){0}, sizeof(*flags))) {
+			(void)k_work_cancel_delayable(&mcs_inst.notify_work);
+		}
+	}
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c:457]: I realize that this was modelled after one of my PRs, but I do notice an issue:

The `tbs_flags` contains both bits for pending notifications, but also the `_dirty` which are related to reads. 

So the check here should ideally only check the `_changed` values and not the `_dirty` values. 

It's arguably OK as it's just a minor optimization, but if you can think of a way to easily check against all `_changed` values only, then that'd be better

**Review by Thalley — COMMENTED** [review]
Thanks - Changes are overall OK; I think you may have a copy-paste error ;) (and then there's a minor optimization for a check we should consider)

File: subsys/bluetooth/audio/tbs.c (hunk 1 above)
Comment (leon-xu-04) [reply subsys/bluetooth/audio/tbs.c:457]: Since both `_changed` and `_dirty` live in the same struct, couldn't find a clean way to do that without enumerating all `_changed` fields or refactoring the struct. Shall we just keep the current approach?

Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c:457]: I think the current approach is fine, but please do add a comment :) We might be able to split the flags into 2 substructs, but not 100% sure how that will affect memory size and performance

File: subsys/bluetooth/audio/tbs.c [hunk 2]
```diff
@@ -692,26 +698,83 @@ static void net_buf_put_uri_scheme_list(const struct tbs_inst *inst, struct net_
...
-static void set_call_state_changed_cb(struct tbs_flags *flags)
+static void set_call_state_changed_cb(struct tbs_flags *flags, bool set)
 {
 	if (flags->call_state_changed) {
 		LOG_DBG("pending notification replaced");
 	}
 
-	flags->call_state_changed = true;
+	flags->call_state_changed = set;
 	flags->call_state_dirty = true;
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: In the case that a client unsubscribes, the `_dirty` field should not be affected. 

I think we need to do something like
```suggestion
	flags->call_state_changed = set;
	if (set) {
		flags->call_state_dirty = true;
	}
```

This applies to all cases where a `_dirty` bit is involved

File: subsys/bluetooth/audio/tbs.c [hunk 3]
```diff
@@ -2832,11 +2935,7 @@ int bt_tbs_remote_incoming(uint8_t bearer_index, const char *to, const char *fro
 	return call->index;
 }
 
-static void set_bearer_provider_name_changed_cb(struct tbs_flags *flags)
-{
-	flags->bearer_provider_name_changed = true;
-	flags->bearer_provider_name_dirty = true;
-}
+
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Minor: We should only have a single empty line between functions IMO

**Review by Thalley — CHANGES_REQUESTED** [review]
Looks pretty good, but I think we need some additional handling for the `_dirty` bits

File: subsys/bluetooth/audio/tbs.c [hunk 4]
```diff
@@ -1054,9 +1117,15 @@ static ssize_t read_provider_name(struct bt_conn *conn, const struct bt_gatt_att
...
 {
-	const struct tbs_inst *inst = lookup_inst_by_attr(attr);
+	struct tbs_inst *inst = lookup_inst_by_attr(attr);
 
 	if (inst != NULL) {
+		/* Clear any pending notifications for any connections that unsubscribes */
+		if (value == 0U) {
+			set_value_changed(inst, set_bearer_provider_name_changed_cb,
+					  BT_UUID_TBS_PROVIDER_NAME);
+		}
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: It is a good point, but unfortunately the GATT API does not provide the connection pointer of whomever unsubscribes here, so we basically have to iterate on all connection (which probably rarely is above 1 anyhow), or we need to refactor a significant portion to handle the subscriptions directly here in tbs. 

I think the simplicity of the current approach is better than maybe saving a few cycles by a much more more complex alternative.

File: subsys/bluetooth/audio/tbs.c [hunk 5]
```diff
@@ -1986,13 +2109,61 @@ static ssize_t write_call_cp(struct bt_conn *conn, const struct bt_gatt_attr *at
...
+
+		if (err != 0) {
+			LOG_DBG("Failed to lock mutex");
+		} else {
+			if (inst->cp_ntf.pending &&
+			    !pending_cp_ntf_subscribed(inst, attr)) {
+				inst->cp_ntf.pending = false;
+			}
+
+			k_mutex_unlock(&inst->mutex);
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: @Hanliang-Xu This one should be fixed, otherwise I think the PR is good :)

File: subsys/bluetooth/audio/tbs.c [hunk 6]
```diff
@@ -1128,9 +1208,15 @@ static ssize_t read_provider_name(struct bt_conn *conn, const struct bt_gatt_att
...
 {
-	const struct tbs_inst *inst = lookup_inst_by_attr(attr);
+	struct tbs_inst *inst = lookup_inst_by_attr(attr);
 
 	if (inst != NULL) {
+		/* Clear any pending notifications for any connections that unsubscribes */
+		if (value == 0U) {
+			set_value_changed(inst, set_bearer_provider_name_changed_cb,
+					  BT_UUID_TBS_PROVIDER_NAME);
+		}
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: @Hanliang-Xu correct me if I"m wrong, but isn't the comment from Copilot here https://github.com/zephyrproject-rtos/zephyr/pull/104717/files#r2904126957 valid? 

If this callback is called, then we call 
```
set_value_changed(inst, set_bearer_provider_name_changed_cb, BT_UUID_TBS_PROVIDER_NAME);
```

but without locking the mutex for `inst`. I don't see any parts of `set_value_changed` nor `set_bearer_provider_name_changed_cb` take the mutex, so this may not be thread safe. 

I think we need to take the mutex in each of the `_cfg_changed` functions, don't we?

File: subsys/bluetooth/audio/tbs.c [hunk 7]
```diff
@@ -1986,13 +2110,59 @@ static ssize_t write_call_cp(struct bt_conn *conn, const struct bt_gatt_attr *at
...
+
+static bool pending_cp_ntf_subscribed(const struct tbs_inst *inst, const struct bt_gatt_attr *attr)
+{
+	struct pending_cp_ntf_subscribed_info info = {
+		.attr = attr,
+		.conn_index = inst->cp_ntf.conn_index,
+		.subscribed = false,
+	};
+
+	bt_conn_foreach(BT_CONN_TYPE_LE, pending_cp_ntf_subscribed_cb, &info);
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c:2156]: We do have `bt_conn_lookup_index` that would make this simpler, but it is not a public API so we shouldn't use it. 

I wonder if we should store the `bt_conn` pointer instead of `conn_index` in `struct cp_ntf` to avoid iterating on all connections to do this lookup, but not sure if that's actually beneficial. 

It would have been nice to just get the `bt_conn` of the device that unsubscribes as well, but I don't see any APIs for that either. 

So this is OK, and I'm not sure we have any better alternatives today

File: subsys/bluetooth/audio/tbs.c [hunk 8]
```diff
@@ -1126,11 +1206,31 @@ static ssize_t read_provider_name(struct bt_conn *conn, const struct bt_gatt_att
...
+	if (value == 0U) {
+		int err = k_mutex_lock(&inst->mutex, MUTEX_TIMEOUT);
+
+		if (err != 0) {
+			LOG_DBG("Failed to lock mutex");
+		} else {
+			set_value_changed(inst, value_cb, uuid);
+			err = k_mutex_unlock(&inst->mutex);
+			__ASSERT(err == 0, "Failed to unlock mutex: %d", err);
+		}
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c:1242]: This is OK for now. 

I think we may want to revisit how to lock mutexes in TBS: We probably should be able to lock with K_FOREVER, or at least a value large enough that if failing to lock, indicates a deadlock somewhere (in which case we can use asserts to cleanup the failure paths a bit

File: subsys/bluetooth/audio/tbs.c [hunk 9]
```diff
@@ -704,24 +713,95 @@ static void net_buf_put_uri_scheme_list(const struct tbs_inst *inst, struct net_
...
 	if (flags->call_state_changed) {
 		LOG_DBG("pending notification replaced");
 	}
 
-	flags->call_state_changed = true;
-	flags->call_state_dirty = true;
+	flags->call_state_changed = set;
+	if (set) {
+		flags->call_state_dirty = true;
+	}
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: This is a fair point @Hanliang-Xu ; the 

```c
	if (flags->call_state_changed) {
		LOG_DBG("pending notification replaced");
	}
```

parts should probably only be done if `set == true`, either by doing

```c
	if (set and flags->call_state_changed) {
		LOG_DBG("pending notification replaced");
	}
```

or by moving the code around to the newly added `if (set)`

**Review by Thalley — CHANGES_REQUESTED** [review]
A minor request w.r.t. the `LOG_DBG("pending notification replaced");` log statements, otherwise LGTM. Good job :)

**Review by Thalley — APPROVED** [review]

**Review by larsgk — APPROVED** [review]
