### PR TITLE
usb: Fix std iface/ep requests

### LINKED ISSUE #27964: usb: Standard requests are not filtered.
**Describe the bug**
Standard USB Requests shall not always be accepted by the device.
Refering to the USB 2.0 specification standard USB are divided into 3 depending on the recipient:
- device (always accepted)
- interface (accepted only if the device is in **Configured** state and the requested interface is valid - existing)
- endpoint (for control endpoints (0x81, 0x00) accepted in **Addressed** state, for other accepted only if the device is in **Configured** state and the requested endpoint is valid - existing)

**Logs and console output**
* Endpoint request for Endpoint 1 is accepted in **Addressed** state.
ep
* Interface request for Interface 1 is accepted in **Addressed** state.
if
* Interface request for not existing Interface 55 is accepted.
if2

**Expected behavior**
The device should accept only valid requests.

**Impact**
Possible data corruption.

### PR DESCRIPTION
**Pull request by eobalski**
This commits introduces check for standard interface and endpoint
requests. Not all requests shall be accepted. In particular those
which addresses not existing interfaces/endpoints should be STALLed.
This patch STALLes incorrect requests.

Signed-off-by: Emil Obalski <emil.obalski@nordicsemi.no>

Fixes: #27964

### CODE REVIEW

File: subsys/usb/usb_device.c [hunk 1]
```diff
@@ -792,6 +803,35 @@ static bool usb_handle_std_device_req(struct usb_setup_packet *setup,
...
+ *
+ * @return true if interface exists - valid
+ */
+static bool is_interface_valid(uint8_t interface)
+{
+	const uint8_t *p = (uint8_t *)usb_dev.descriptors;
+	const struct usb_if_descriptor *if_descr;
+
+	/* Search through descriptor for matching interface */
+	while (p[DESC_bLength] != 0U) {
```
Comment (jfischer-phytec-iot) [inline subsys/usb/usb_device.c:822]: That can be simplified, just check `setup->wIndex`(L853) against bNumInterfaces from [Configuration Descriptor](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/usb/usb_descriptor.c#L92)

File: subsys/usb/usb_device.c [hunk 2]
```diff
@@ -863,14 +941,21 @@ static bool usb_handle_std_endpoint_req(struct usb_setup_packet *setup,
 		break;
 
 	case REQ_CLEAR_FEATURE:
-		if (setup->wValue == FEA_ENDPOINT_HALT) {
-			/* clear HALT by unstalling */
-			LOG_INF("... EP clear halt %x", ep);
-			usb_dc_ep_clear_stall(ep);
-			if (usb_dev.status_callback) {
-				usb_dev.status_callback(USB_DC_CLEAR_HALT, &ep);
+		if (sys_le16_to_cpu(setup->wValue) == FEA_ENDPOINT_HALT) {
```
Comment (jfischer-phytec-iot) [inline subsys/usb/usb_device.c:944]: sys_le16_to_cpu() is not necessary here

File: subsys/usb/usb_device.c [hunk 3]
```diff
@@ -863,14 +941,21 @@ static bool usb_handle_std_endpoint_req(struct usb_setup_packet *setup,
...
+			/** This request is valid for Control Endpoints when
+			 * the device is not yet configured. For other
+			 * Endpoints the device must be configured.
+			 */
+			if (!(ep & ~USB_EP_DIR_MASK) ||
```
Comment (jfischer-phytec-iot) [inline subsys/usb/usb_device.c:949]: `if (USB_EP_GET_IDX(ep) == 0 || ...` is much easier to read.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: subsys/usb/usb_device.c (hunk 3 above)
Comment (emob-nordic) [reply subsys/usb/usb_device.c:949]: Yea, I forgot we have those macros. I will update this. Generally I made this fix for `REQ_CLEAR_FEATURE` but now I can see similar check is required for other Endpoint specific requests.

File: subsys/usb/usb_device.c (hunk 2 above)
Comment (emob-nordic) [reply subsys/usb/usb_device.c:944]: It was there. I didn't change that.

File: subsys/usb/usb_device.c (hunk 1 above)
Comment (emob-nordic) [reply subsys/usb/usb_device.c:822]: That's good point. I will test it.

File: subsys/usb/usb_device.c (hunk 2 above)
Comment (emob-nordic) [reply subsys/usb/usb_device.c:944]: Ahh sorry nvm... I had to add this by mistake when rebasing from older branches. I will remove that

File: subsys/usb/usb_device.c (hunk 1 above)
Comment (emob-nordic) [reply subsys/usb/usb_device.c:822]: Done.

File: subsys/usb/usb_device.c [hunk 4]
```diff
@@ -687,6 +687,17 @@ static bool usb_set_interface(uint8_t iface, uint8_t alt_setting)
...
 
+/**
+ * @brief Check if the device is in Configured state
+ *
+ * @return true if Configured, false otherwise.
+ */
+static bool is_device_configured(void)
+{
+	return (usb_dev.configured && usb_dev.configuration) ?
+		true : false;
```
Comment (anangl) [inline subsys/usb/usb_device.c:698]: The `? true : false` part is redundant.

File: subsys/usb/usb_device.c [hunk 5]
```diff
@@ -839,6 +891,38 @@ static bool usb_handle_std_interface_req(struct usb_setup_packet *setup,
...
+	size_t size = (__usb_data_end - __usb_data_start);
+
+	/* Check if its Endpoint 0 */
+	if (USB_EP_GET_IDX(ep) == 0) {
+		return true;
+	}
+
+	for (size_t i = 0; i < size; i++) {
+		struct usb_cfg_data *cfg = &__usb_data_start[i];
+		struct usb_ep_cfg_data *ep_data = cfg->endpoint;
```
Comment (anangl) [inline subsys/usb/usb_device.c:916]: Both these pointers can point to constant structures.

**Review by anangl — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]
