### PR TITLE
Bluetooth: Controller: Deinit ticker

### LINKED ISSUE #91428: soc_flash_nrf: flash_write timeout after bt_disable
### Describe the bug

With `CONFIG_SOC_FLASH_NRF_RADIO_SYNC_TICKER=y`, calling `flash_write()` after `bt_disable()` returns `-ETIMEDOUT`.

This is because the flash driver wants to sync with the BLE ticker (`nrf_flash_sync_is_required()` returns true), but the ticker is not being triggered because bluetooth is disabled.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Run the following sample on the NRF52:

```c
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/drivers/flash.h>
#include <zephyr/storage/flash_map.h>

#define TEST_PARTITION storage_partition

#define TEST_PARTITION_OFFSET FIXED_PARTITION_OFFSET(TEST_PARTITION)
#define TEST_PARTITION_DEVICE FIXED_PARTITION_DEVICE(TEST_PARTITION)

void main(void)
{
	const struct device *flash_dev = TEST_PARTITION_DEVICE;
	const uint32_t data = 0xdeadbeef;
	int err;

	bt_enable(NULL);
	bt_disable();

	printk("Writing to flash...\n");
	err = flash_write(flash_dev, TEST_PARTITION_OFFSET, &data, sizeof(data));
	printk("Result = %d\n", err);
}
```

### Relevant log output

```shell
Writing to flash...
Result = -116
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

Zephyr 4.1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by marcowidmer**
ticker_is_initialized() should only return true when the ticker is running (triggered regularly). Users like nrf_flash_sync_is_required() depend on this behavior.

When the bluetooth controller driver is closed, ll_deinit() calls lll_deinit(), which stops the ticker from being triggered. Also deinitialize the ticker to ensure that ticker_is_initialized() returns false.

Fixes #91428

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 1]
```diff
@@ -783,8 +783,18 @@ int ll_init(struct k_sem *sem_rx)
...
-	return lll_deinit();
+
+	err = lll_deinit();
+	if (err) {
+		return err;
+	}
+
+	ticker_deinit(TICKER_INSTANCE_ID_CTLR);
+
+	return 0;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull.c]:
```suggestion
	err = ticker_deinit(TICKER_INSTANCE_ID_CTLR);

	return err;
```

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 2]
```diff
@@ -3475,6 +3475,22 @@ uint8_t ticker_init(uint8_t instance_index, uint8_t count_node, void *node,
 	return TICKER_STATUS_SUCCESS;
 }
 
+/**
+ * @brief Deinitialize ticker instance
+ *
+ * @param instance_index Index of ticker instance
+ */
+void ticker_deinit(uint8_t instance_index)
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ticker/ticker.c]:
```suggestion
int ticker_deinit(uint8_t instance_index)
```

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 3]
```diff
@@ -3475,6 +3475,22 @@ uint8_t ticker_init(uint8_t instance_index, uint8_t count_node, void *node,
...
+{
+	struct ticker_instance *instance = &_instance[instance_index];
+
+	if (instance_index >= TICKER_INSTANCE_MAX) {
+		return;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ticker/ticker.c]:
```suggestion
		return -EINVAL;
```

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 4]
```diff
@@ -3475,6 +3475,22 @@ uint8_t ticker_init(uint8_t instance_index, uint8_t count_node, void *node,
...
+	}
+
+	memset(instance, 0, sizeof(*instance));
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ticker/ticker.c]:
```suggestion
	_instance[instance_index].count_node = 0U;
	
	return 0;
```

File: subsys/bluetooth/controller/ticker/ticker.h [hunk 5]
```diff
@@ -173,6 +173,7 @@ uint8_t ticker_init(uint8_t instance_index, uint8_t count_node, void *node,
 		     void *user_op, ticker_caller_id_get_cb_t caller_id_get_cb,
 		     ticker_sched_cb_t sched_cb,
 		     ticker_trigger_set_cb_t trigger_set_cb);
+void ticker_deinit(uint8_t instance_index);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ticker/ticker.h]:
```suggestion
int ticker_deinit(uint8_t instance_index);
```

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 6]
```diff
@@ -3475,6 +3475,22 @@ uint8_t ticker_init(uint8_t instance_index, uint8_t count_node, void *node,
...
+ * @param instance_index Index of ticker instance
+ */
+void ticker_deinit(uint8_t instance_index)
+{
+	struct ticker_instance *instance = &_instance[instance_index];
+
+	if (instance_index >= TICKER_INSTANCE_MAX) {
+		return;
+	}
+
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ticker/ticker.c:3496]:
```suggestion

	if (_instance[instance_index].ticker_id_head != TICKER_NULL) {
		return -EBUSY;
	}

```

**Review by cvinayak — CHANGES_REQUESTED** [review]

**Comment by marcowidmer** [comment]
@cvinayak Thanks for the feedback!

File: subsys/bluetooth/controller/ll_sw/ull.c [hunk 7]
```diff
@@ -783,8 +783,16 @@ int ll_init(struct k_sem *sem_rx)
...
+
 	ll_reset();
-	return lll_deinit();
+
+	err = lll_deinit();
+	if (err) {
+		return err;
+	}
+
+	return ticker_deinit(TICKER_INSTANCE_ID_CTLR);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull.c]:
```suggestion
	err = ticker_deinit(TICKER_INSTANCE_ID_CTLR);
	
	return err;
```

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 8]
```diff
@@ -3475,6 +3475,28 @@ uint8_t ticker_init(uint8_t instance_index, uint8_t count_node, void *node,
...
 }
 
+/**
+ * @brief Deinitialize ticker instance
+ *
+ * @param instance_index Index of ticker instance
+ */
+int ticker_deinit(uint8_t instance_index)
+{
+	struct ticker_instance *instance = &_instance[instance_index];
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ticker/ticker.c]:
```suggestion
	struct ticker_instance *instance;
```

File: subsys/bluetooth/controller/ticker/ticker.c [hunk 9]
```diff
@@ -3475,6 +3475,28 @@ uint8_t ticker_init(uint8_t instance_index, uint8_t count_node, void *node,
...
+
+	if (instance_index >= TICKER_INSTANCE_MAX) {
+		return -EINVAL;
+	}
+
+	if (instance->ticker_id_head != TICKER_NULL) {
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ticker/ticker.c:3493]:
```suggestion
	instance = &_instance[instance_index];
	if (instance->ticker_id_head != TICKER_NULL) {
```

**Review by cvinayak — COMMENTED** [review]
Minor nitpicking.

**Review by cvinayak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
