### PR TITLE
Bluetooth: controller: split: fixes DLE conformance tests

### LINKED ISSUE #22048: Failing LL.TS Data Length Update Tests (split)
**Description**
Failing LL.TS EBQ Tests for Data Length Update:
```
LL/CON/MAS/BV-74-C:
Master Data Length Update - Initiating Data Length Update Procedure; LE 1M PHY

LL/CON/MAS/BV-77-C:
Master Data Length Update - Initiating Data Length Update Procedure; LE 2M PHY

LL/CON/SLA/BV-131-C: 
Data Length Update - Retransmission During an Update

LL/CON/SLA/BV-78-C
Slave Data Length Update - Initiating Data Length Update Procedure; LE 1M PHY

LL/CON/SLA/BV-81-C:
Slave Data Length Update - Initiating Data Length Update Procedure; LE 2M PHY
```
**To Reproduce**
Run the listed LL.TS tests with EBQ and nRF52

**Expected behavior**
Tests should pass

**Impact**
Currently no practical impact, but qualification will fail

### PR DESCRIPTION
**Pull request by kruithofa**
For review by Vinayak and EBQ verification by Morten
EBQ run with CODED and 2M phy configured in without failures

Fixes #22048 except for LL/CON/SLA/BV-131-C
See https://github.com/EDTTool/EDTT/pull/12 for a fix for the EDTT

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 1]
```diff
@@ -3191,38 +3243,13 @@ static inline void event_len_prep(struct ll_conn *conn)
...
-#endif /* CONFIG_BT_CTLR_PHY_2M */
-#endif /* CONFIG_BT_CTLR_PHY */
-		}
-
+		dle_max_time_get(conn, &rx_time, &tx_time);
 		lr->max_rx_time = sys_cpu_to_le16(rx_time);
 		lr->max_tx_time = sys_cpu_to_le16(tx_time);
 
-
+#if defined(CONFIG_BT_CTLR_PHY)
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: revert this change, so that `conn->default_tx_time` is not changed and retry

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 2]
```diff
@@ -4494,35 +4521,30 @@ static inline int length_req_rsp_recv(struct ll_conn *conn, memq_link_t *link,
...
+		dle_max_time_get(conn, &max_rx_time, &max_tx_time);
+
 		/* use the minimal of our default_tx_time and
 		 * peer max_rx_time
 		 */
-		max_rx_time = sys_le16_to_cpu(lr->max_rx_time);
-		if (max_rx_time >= PKT_US(PDU_DC_PAYLOAD_SIZE_MIN, 0)) {
-			eff_tx_time = MIN(max_rx_time,
-					  conn->default_tx_time);
+		if (lr->max_rx_time >= PKT_US(PDU_DC_PAYLOAD_SIZE_MIN, 0)) {
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: put back the `sys_le16_to_cpu`

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 3]
```diff
@@ -4493,14 +4513,17 @@ static inline int length_req_rsp_recv(struct ll_conn *conn, memq_link_t *link,
 #if defined(CONFIG_BT_CTLR_PHY)
 		u16_t max_rx_time;
 		u16_t max_tx_time;
+		u16_t temp_rx, temp_tx;
+
+		dle_max_time_get(conn, &temp_rx, &temp_tx);
+		max_rx_time = sys_le16_to_cpu(temp_rx);
+		max_tx_time = sys_le16_to_cpu(temp_tx);
```
Comment (mtpr-ot) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: This looks incorrect. Why would you endianness-convert from LE, when value is provided by dle_max_time_get?

Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: as per suggestion from Vinayak; we were seeing some issues trying to resolve

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 4]
```diff
@@ -3127,6 +3127,76 @@ static inline void event_ping_prep(struct ll_conn *conn)
 }
 #endif /* CONFIG_BT_CTLR_LE_PING */
 
+static inline void dle_max_time_get(const struct ll_conn *conn,
+				    u16_t *max_rx_time, u16_t *max_tx_time)
+{
+	u32_t feature_coded_phy;
+	u32_t feature_phy_2m;
+	u16_t rx_time;
+	u16_t tx_time;
```
Comment (mtpr-ot) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: Both need to be initialized to zero, to avoid compiler warning

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 2 above)
Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Yes, these conversions must be applied to references to lr->max_xxxxx. Should probably be done by assigning a local variable

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 5]
```diff
@@ -4511,18 +4534,12 @@ static inline int length_req_rsp_recv(struct ll_conn *conn, memq_link_t *link,
 		/* use the minimal of our max supported and
 		 * peer max_tx_time
 		 */
-		max_tx_time = sys_le16_to_cpu(lr->max_tx_time);
-		if (max_tx_time >= PKT_US(PDU_DC_PAYLOAD_SIZE_MIN, 0)) {
+		if (lr->max_tx_time >= PKT_US(PDU_DC_PAYLOAD_SIZE_MIN, 0)) {
```
Comment (mtpr-ot) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: sys_le16_to_cpu

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 6]
```diff
@@ -4511,18 +4534,12 @@ static inline int length_req_rsp_recv(struct ll_conn *conn, memq_link_t *link,
...
+			eff_rx_time = MIN(lr->max_tx_time, max_rx_time);
```
Comment (mtpr-ot) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: sys_le16_to_cpu x 2 (or local var)

**Review by mtpr-ot — CHANGES_REQUESTED** [review]
Please update endianness handling as suggested.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 1 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Change implemented

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 6 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Introduced local variable

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 3 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: removed

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 2 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: introduced local vars

**Comment by kruithofa** [comment]
Shippable fails, requires an update to EDTT

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 4 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: initialization added

**Review by mtpr-ot — APPROVED** [review]
LGTM. EBQ tests pass at our end.

**Review by cvinayak — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
Looks fine, but we need to get Shippable passing before merging

**Comment by aescolar** [comment]
@kruithofa Please note that this PR seems to be quite behind master, 
I did a quick trial rebasing on top of master and referencing in the manifest to the EDTT PR, but a few tests seem to fail(?). You can see it here:
https://github.com/aescolar/zephyr/tree/alpi_kruithofa

**Review by aescolar — DISMISSED** [review]
Just to avoid accidental merges: Careful that it points to a west module PR
(anybody, feel free to dismiss whenever it does not anymore)
