### PR TITLE
drivers: nrf: Fix UART TX hanging when using both polling and async API.

### LINKED ISSUE #22264: drivers: serial: nrf_uart & nrf_uarte infinite hang
**Describe the bug**
Both drivers fail to properly mediate access to the underlying hardware when used in poll mode.
Both drivers (uart_nrfx_uart.c and uart_nrfx_uarte.c) in their poll_out implementations, immediately start modifying hardware registers, then busy-wait on a hardware register.

Once one thread starts sending and blocks, a second thread will go through the same motions and block on the same register. Given that they clear the register on success, only one will ever be unblocked, leaving the other stuck.

The simplest scenario in which this happens is when using the logging subsystem and printk in a thread.  When the TX's collide, the lower priority thread hangs. The uart_nrfx_uart.c variant I can only reproduce when trying to TX using the async api, even though the same issue appears to effect both drivers.

The issues only occurs when CONFIG_UART_ASYNC_API is enabled.

**To Reproduce**`

The simplest way to reproduce this issue is to smash the logger with log messages, and try and use printk. The easiest application for that is `samples/bluetooth/scan_adv`

**UART Variant**
proj.conf additions:
```
CONFIG_UART_ASYNC_API=y
CONFIG_BT_LOG_LEVEL_DBG=y
```
main.c additions:
```
#include <device.h>
#include <drivers/uart.h>
/* In the infinite loop */
u8_t test[8] = "TEST\n";
uart_tx(dev, test, 5, K_FOREVER);
```

**UARTE Variant**
proj.conf additions:
```
CONFIG_UART_ASYNC_API=y
CONFIG_BT_LOG_LEVEL_DBG=y
CONFIG_UART_0_NRF_UARTE=y
```
main.c additions:
```
/* In the infinite loop */
printk("TEST\n");
```
add nrf52840_pca10056.overlay
```
&uart0 {
	compatible = "nordic,nrf-uarte";
	status = "okay";
	current-speed = <115200>;
	tx-pin = <6>;
	rx-pin = <8>;
	rts-pin = <5>;
	cts-pin = <7>;
};
```

Compile and run:
```
west build -b nrf52840_pca10056 zephyr/samples/bluetooth/scan_adv
west flash
```
Open your serial program of choice, and the bluetooth log messages will typically stop the first time "TEST" prints.

**Expected behavior**
The logging thread should not infinitely hang.

**Impact**
Major problem, UART subsystem should not break on timing collisions.

**Screenshots or console output**
Example output of the time at which the logger hangs
```
[00:00:00.266,113] <dbg> bt_hci_core.bt_recv: buf 0x20003288 len 44
[00:00:00.266,113] <dbg> bt_hci_core.hci_event: event 0x3e
[00:00:00.266,113] <dbg> bt_hci_core.hci_le_meta_event: subevent 0x02
[00:00:00.266,143] <dbg> bt_hci_core.le_adv_report: Adv number of reports 1EST
TEST
TEST
TEST
TEST
TEST
```

**Environment (please complete the following information):**
 - Commit SHA: 5af54075703c248fae2bf69a50909bf2e3cc977e

### PR DESCRIPTION
**Pull request by Mierunski**
Fix UART TX hanging when using both polling and async API.

Signed-off-by: Mieszko Mierunski <mieszko.mierunski@nordicsemi.no>

fixes #22264

### CODE REVIEW

File: drivers/serial/uart_nrfx_uart.c [hunk 1]
```diff
@@ -229,6 +228,11 @@ static void uart_nrfx_poll_out(struct device *dev,
 	 * blue moon against hanging up the whole thread permanently
 	 */
 
+#ifdef CONFIG_UART_0_ASYNC
```
Comment (JordanYates) [inline drivers/serial/uart_nrfx_uart.c]: I don't think this fixes the core problem, which is that the condition listed in the comment is not actually applied.
'The UART API dictates that poll_out should wait for the transmitter to be empty before sending a character'
Given that UART doesn't have the TXSTARTED/TXSTOPPED events, perhaps polling until the TXDRDY interrupt is not enabled would work?

File: drivers/serial/uart_nrfx_uart.c [hunk 2]
```diff
@@ -229,6 +228,11 @@ static void uart_nrfx_poll_out(struct device *dev,
...
+	/* Disable TXDRDY interrupts, so that ISR doesn't clear TXDRDY event. */
+	nrf_uart_int_disable(uart0_addr, NRF_UART_INT_MASK_TXDRDY);
```
Comment (JordanYates) [inline drivers/serial/uart_nrfx_uart.c]: Disabling the interrupt will stop the thread locking up, at the expense of dropping any data remaining in the ASYNC send. I also don't think this fixes two threads calling poll_out at the same time, they just both disable the interrupt and still both loop on TXDRDY at the same time.

File: drivers/serial/uart_nrfx_uart.c (hunk 1 above)
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uart.c]: Problem here was that event was cleared in ISR instead of poll_out function. Condition in comment is applied and working.

File: drivers/serial/uart_nrfx_uart.c (hunk 2 above)
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uart.c]: Function is working fine with two threads calling poll_out at the same time, it is possible to lose some bytes but there is no other solution if we want to keep it lockless.
If writing from multiple contexts is desired, tty api should be used.
Not all data is dropped, it depends on timings but most of the data is sent out from async send.

Comment (JordanYates) [reply drivers/serial/uart_nrfx_uart.c]: As far as I can tell, there is no way to force the logger backend or printk to route through the TTY system. If this is true, there is no way to reliably send data via UART, as printk/logger can blurt over the tty'd TX at any point in time. I understand the desire to keep it lockless, but it seems to come at the cost of making UART unusable for data protocols, rather than purely debug output.

Comment (JordanYates) [reply drivers/serial/uart_nrfx_uart.c]: This doesn't seem to be the case for the other UART drivers I have scanned through, which have a dedicated TXBUSY register or similar.  If a lock is required to have this driver conform to the majority, that seems a worthy trade to me.

File: drivers/serial/uart_nrfx_uarte.c [hunk 3]
```diff
@@ -485,6 +483,12 @@ static int uarte_nrfx_tx(struct device *dev, const u8_t *buf, size_t len,
 	data->async->tx_buf = buf;
```
Comment (JordanYates) [inline drivers/serial/uart_nrfx_uarte.c]: There is still a chance of incorrect behavior here. 
If this function is pre-empted after the check above, but before these 2 lines run, the check is no longer valid.
Thread 2 could have started a TX, this function returns and overwrites data->async.
The original TX will never have the user callback called on.

Comment (nordic-krch) [reply drivers/serial/uart_nrfx_uarte.c]: yep, for that i would recommend `atomic_cas` something like:
`if (atomic_cas(&txbuf, NULL, buf)==false) return -EBUSY;`

File: drivers/serial/uart_nrfx_uart.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/serial/uart_nrfx_uart.c]: why not use same mechanism for business detection as in async call?
`if (atomic_cas(&txbuf, NULL, &c) == false) return;` to just skip poll out when async transfer is ongoing and make driver busy for that time. 

Evantually, we will convert to tty (console and logger) so dropping bytes on conflict should be accepted.

File: drivers/serial/uart_nrfx_uart.c [hunk 4]
```diff
@@ -242,10 +246,18 @@ static void uart_nrfx_poll_out(struct device *dev,
...
-	 * power.
-	 */
-	nrf_uart_task_trigger(uart0_addr, NRF_UART_TASK_STOPTX);
+#ifdef CONFIG_UART_0_ASYNC
+	if (uart0_cb.tx_buffer_length == 0) {
+#endif
+		/* Deactivate the transmitter so that it does not needlessly
+		 * consume power.
+		 */
+		nrf_uart_task_trigger(uart0_addr, NRF_UART_TASK_STOPTX);
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: Interrupt driven mode also needs the transmitter to stay active [as long as the TX interrupt is enabled](https://github.com/zephyrproject-rtos/zephyr/pull/22355/files#diff-24c27a01c8713b6b093dfd80f40883d0L745), so it seems that you should also use `device_busy_check(dev)` here (or introduce some flag) to handle that case.

File: drivers/serial/uart_nrfx_uarte.c [hunk 5]
```diff
@@ -915,33 +931,31 @@ static void uarte_nrfx_poll_out(struct device *dev, unsigned char c)
...
-		 * work when interrupted.
+		/* Use tx_size as lock, this way uarte_nrfx_tx will
+		 * return -EBUSY during poll_out.
 		 */
-		data->async->tx_size = 1;
-		nrf_uarte_int_disable(uarte,
-				      NRF_UARTE_INT_ENDTX_MASK |
-				      NRF_UARTE_INT_TXSTOPPED_MASK);
-	}
+		lock = &data->async->tx_size;
```
Comment (nordic-krch) [inline drivers/serial/uart_nrfx_uarte.c]: There is a chance that once transfer will be completed a new one will come. In that case, if in interrupt we overwrite length (*lock = 1).  Maybe we should lock immediately in while loop which is doing the check? Something like:
```
do {
  while(txbuf) {  uarte_nrfx_isr_async(dev); }
} while (atomic_cas(&lock, 0, 1) == false);
```

File: drivers/serial/uart_nrfx_uarte.c [hunk 6]
```diff
@@ -915,33 +931,31 @@ static void uarte_nrfx_poll_out(struct device *dev, unsigned char c)
...
+
+		while (atomic_cas((atomic_t *) lock,
+				(atomic_val_t) 0,
+				(atomic_val_t) 1) == false) {
+			/* k_sleep allows other threads to execute and finish
+			 * their transactions.
+			 */
+			k_sleep(1);
+			if (--safety_cnt == 0) {
+				break;
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uarte.c]: I guess it would be safer to return than to continue without obtaining the lock.

File: drivers/serial/uart_nrfx_uart.c [hunk 7]
```diff
@@ -209,26 +209,54 @@ static int uart_nrfx_poll_in(struct device *dev, unsigned char *c)
...
+		if (k_is_in_isr()) {
+			uart_nrfx_isr((void *) dev);
+		}
+	}
+	/* Use tx_buffer_length as lock, this way uart_nrfx_tx will
+	 * return -EBUSY during poll_out.
 	 */
+	lock = &uart0_cb.tx_buffer_length;
+#else
+	static atomic_val_t poll_out_lock;
```
[the remark this answers is not in the document]
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uart.c]: There is only single instance of UART. In UARTE there are locks per instance

File: drivers/serial/uart_nrfx_uart.c [hunk 8]
```diff
@@ -239,13 +267,17 @@ static void uart_nrfx_poll_out(struct device *dev,
 	nrf_uart_txd_set(uart0_addr, (u8_t)c);
 
 	/* Wait until the transmitter is ready, i.e. the character is sent. */
-	while (!event_txdrdy_check()) {
-	}
+	int res;
 
-	/* Deactivate the transmitter so that it does not needlessly consume
-	 * power.
+	NRFX_WAIT_FOR(event_txdrdy_check(), 1000, 1, res);
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uart.c]: I don't entirely get the idea behind this change. When can it happen that the transmission of the character does not finish?

File: drivers/serial/uart_nrfx_uart.c [hunk 9]
```diff
@@ -209,26 +209,54 @@ static int uart_nrfx_poll_in(struct device *dev, unsigned char *c)
...
+			/* k_sleep allows other threads to execute and finish
+			 * their transactions.
+			 */
+			k_sleep(1);
+			if (--safety_cnt == 0) {
+				break;
+			}
+		}
+	} else {
+		*lock = 1;
```
[the remark this answers is not in the document]
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uart.c]: Lock here is written so that uart_tx returns busy if called from interrupt context.
If another interrupt comes then it is possible that we will lose first character but further calls to poll_out will result in successful transmission

File: drivers/serial/uart_nrfx_uarte.c (hunk 5 above)
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uarte.c]: If a new one comes it will be handled normally, in worst case scenario we will lose first byte send by poll_out

File: drivers/serial/uart_nrfx_uarte.c (hunk 6 above)
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uarte.c]: We end up here if current thread is using poll out while lower priority thread is in middle of transaction. If we return here then successive poll outs from higher priority thread would be dropped, if we continue then we can lose first byte from higher priority thread. This point actually should never be reached as k_sleep will allow lower priority threads to execute and finish their operations. Safety counter was added just in case

File: drivers/serial/uart_nrfx_uart.c (hunk 8 above)
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uart.c]: There is very small risk that if asynchronous TX started in line 937 during poll out in interrupt and ended in lines 964-965 then asynchronous call will clear ENDTX event and result in hanging that poll_out in interrupt.

File: drivers/serial/uart_nrfx_uart.c [hunk 10]
```diff
@@ -209,26 +209,54 @@ static int uart_nrfx_poll_in(struct device *dev, unsigned char *c)
...
-	 * this introduces a rare yet possible race condition if the thread is
-	 * preempted between sending the byte and checking for completion.
-
-	 * Because of this race condition, the while loop has to be placed
-	 * after the write to TXD, and we can't wait for an empty transmitter
-	 * before writing. This is a trade-off between losing a byte once in a
-	 * blue moon against hanging up the whole thread permanently
+	atomic_t *lock;
+#ifdef CONFIG_UART_0_ASYNC
+	while (uart0_cb.tx_buffer) {
```
[the remark this answers is not in the document]
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uart.c]: fixed

**Review by nordic-krch — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Comment by Mierunski** [comment]
@JordanYates Please check if your issue is fixed

File: drivers/serial/uart_nrfx_uarte.c [hunk 11]
```diff
@@ -479,12 +478,20 @@ static int uarte_nrfx_tx(struct device *dev, const u8_t *buf, size_t len,
 		return -ENOTSUP;
 	}
 
-	if (data->async->tx_buf || data->async->tx_size) {
+	if (atomic_cas((atomic_t *) &data->async->tx_size,
```
Comment (JordanYates) [inline drivers/serial/uart_nrfx_uarte.c]: The atomic compare and set here is on async->tx_size , but the busy check in poll_out is on ansyc->tx_buf , so the pre-emption problem still exists.
1. Compare and set passes
2. Pre-empted
3. poll_out is called
4. Both threads think they are clear to use the hardware
I think you could just swap the check out to be on tx_buf, but I'm finding it hard to reason about the other ways tx_size is used.

**Comment by JordanYates** [comment]
I can confirm that the core problem is fixed, thanks @Mierunski 
There is just my comment on my pre-emptibility to resolve, and I am happy.

File: drivers/serial/uart_nrfx_uarte.c (hunk 11 above)
Comment (Mierunski) [reply drivers/serial/uart_nrfx_uarte.c]: It has been taken into account, poll_out also has lock on async->tx_size and it will be blocked there in described scenario. Reason for using both tx_buf and tx_size for locks is that tx_buf is set only with async transfers, this way if poll_out is called from interrupt context then async transfer can be finished when trying to lock tx_buf, while tx_size is locked only in thread context, so if during poll_out its pre-empted and poll_out is called then we can still send from interrupt context. Only risk is that first byte sent using poll_out from interrupt context can be lost.
As using blocking functions in interrupt context is bad practice I assume that it would most likely occur only in hardfault handler, we don't want to lose that information so we cannot simply ignore poll out.
Current solution allows for using both async and polling API from different contexts without queueing output at cost of possible losing single byte when switching to interrupt context.

Comment (JordanYates) [reply drivers/serial/uart_nrfx_uarte.c]: Is that the only time bytes should be lost now? I have observed the first character of my test print disappearing with the setup described in my issue.

Comment (Mierunski) [reply drivers/serial/uart_nrfx_uarte.c]: Note that logger uses some multi byte encodings, depending on terminal settings it may seem like some characters are lost when logger thread is preempted in multi byte enconding. I noticed it when using ansi encoding in terminal, but looking at raw data I haven't seen it, therefore its not a UART issue.

Comment (JordanYates) [reply drivers/serial/uart_nrfx_uarte.c]: As you say, the raw bytes are there. Issue appears when we preempt after the first byte of the color code escape sequence. Thanks for the explanation, everything looks good to me then.

**Comment by Mierunski** [comment]
@ioannisg ping
