### PR TITLE
drivers: ethernet: stm32: Set MDIO clock range after MAC reset

### LINKED ISSUE #99535: 4.3.0 : Issue with STM32 Ethernet and KSZ8081 Phy
### Describe the bug

Hello, I have a custom board based on an STM32F427 with an external phy Microchip KSZ8081RNA. Ethernet comms was working on 4.0.0-rc1. However, there was an issue with the assigned IP address being lost if the cable was removed temporarily. This appears to have been fixed in 4.1.0. The board words OK with this release. However, we decided to move to 4.2.0 or 4.3.0. We could get neither of these versions to work.

Focussing on 4.3.0, no matter what I do, I cannot get ethernet comms to work to a point where I can ping the board from a Linux machine.

It appears as though the link Auto-neg is failing. On closer inspection the Phy driver correctly writes to the ANAR Phy register (0x4). The link is expected to auto-neg to 100M, Full duplex. The value written is the same as the default hardware reset value 0x81E1.

Shortly after the correct value was written to the ANAR (0x81E1), the value was obseverved to change to 0xE0 without any write to the register. It appears that this is being caused by the MAC being reset by the ethernet driver whilst the PHY is running. The two drivers appear to be running in parallel and interfering with each other. Then with the ANAR incorrectly holding 0xE0 the PHY ends up thinking it's 100M half-duplex whilst the Laptop says it's 100M full on the other end of the same link. No comms are possible - such as pinging one end of the link from the other. If I comment out the section of code in the STM32 HAL V2 driver that resets the MAC (by writing a bit and waiting for it to clear), then the ANAR register retains the correct value and both ends agree on 100M full duplex. However, when I then add an IP address, I still cannot ping it - possibly due to the MAC reset code I've commented out.

I've attached the device tree and some diagnostic output from the console.

[output.txt](https://github.com/user-attachments/files/23592094/output.txt)

[zephyr.dts.txt](https://github.com/user-attachments/files/23592095/zephyr.dts.txt)

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by juickar**
Call HAL_ETH_SetMDIOClockRange to set back the MDIO clock range as it is set to 0 during the software reset.

### CODE REVIEW

**Review by maass-hamburg — DISMISSED** [review]

File: drivers/ethernet/eth_stm32_hal_v2.c [hunk 1]
```diff
@@ -615,6 +615,8 @@ int eth_stm32_hal_init(const struct device *dev)
 		return -EINVAL;
 	}
 
+	HAL_ETH_SetMDIOClockRange(heth);
```
Comment (etienne-lms) [inline drivers/ethernet/eth_stm32_hal_v2.c:623]: This seems needed only on F4 and F7 SoCs. For the others, `HAL_ETH_Init()` calls this HAL function after the software reset sequence.

**Review by etienne-lms — COMMENTED** [review]
cvwcvcxv

**Review by maass-hamburg — DISMISSED** [review]

File: drivers/ethernet/eth_stm32_hal_v2.c (hunk 1 above)
Comment (juickar) [reply drivers/ethernet/eth_stm32_hal_v2.c:623]: I've added an `#if defined` for those series around the call

**Review by erwango — DISMISSED** [review]

File: drivers/ethernet/eth_stm32_hal_v2.c (hunk 1 above)
Comment (mathieuchopstm) [reply drivers/ethernet/eth_stm32_hal_v2.c:623]: Nit: I would add a comment saying this is workaround for a HAL defect. But non-blocking.

**Review by mathieuchopstm — DISMISSED** [review]

**Review by maass-hamburg — APPROVED** [review]

**Review by mathieuchopstm — APPROVED** [review]

**Review by erwango — APPROVED** [review]
