### PR TITLE
sw_isr_table: Force align _isr_list_sname instances

### LINKED ISSUE #81254: Local ISR declaration parser can break when .intList input sections are padded to an alignment >4
**Describe the bug**

The local ISR declaration parser (`CONFIG_ISR_TABLES_LOCAL_DECLARATION=y`) issues incorrect errors about bad IRQ values if any extra padding is inserted by the linker between the `.irq_info` and `.intList` input sections in the `.intList` output section definition (in [intlist.ld](https://github.com/zephyrproject-rtos/zephyr/blob/65511eacf9d17bf22a6cf28c3ace467a86a159f5/include/zephyr/linker/intlist.ld#L36)). Currently, this can happen "naturally" when any opt level _besides_ `CONFIG_SIZE_OPTIMIZATIONS` is specified and we're building with a GCC-based toolchain for AArch64.

See "Additional context" for additional info/discussion on what I think is happening.

**To Reproduce**

This shouldn't be limited to just the one test, but this can be reproduced as below using the Zephyr SDK/Zephyr's tests:

`west twister -c -W -p qemu_cortex_a53 -s tests/kernel/interrupt/arch.shared_interrupt.lto -x=CONFIG_SPEED_OPTIMIZATIONS=y`

The build should fail (see "Logs and console output" for error).

**Expected behavior**

We shouldn't produce incorrect/unexpected errors about invalid IRQ numbers that the user did not specify.

**Impact**

Generally, I think any build will currently fail when the following are true:

1. A GCC-based toolchain is used to target AArch64
2. `CONFIG_ISR_TABLES_LOCAL_DECLARATION=y` is selected
3. An optimization level other than `-Os`/`CONFIG_SIZE_OPTIMIZATIONS` is used
4. `.intList` isn't coincidentally aligned on an 8-byte boundary (so the linker will add padding)

I think this should also impact some non-AArch64 targets (ex: RISC-V 64) if/when `ISR_TABLES_LOCAL_DECLARATION` is ported, but currently AArch64 is the only impacted target I think. 32bit Arm seems ok experimentally.

**Logs and console output**

`west twister -c -W -p qemu_cortex_a53 -s tests/kernel/interrupt/arch.shared_interrupt.lto -x=CONFIG_SPEED_OPTIMIZATIONS=y` produces the following error:

```
[119/122] Generating isr_tables.c, isr_tables_vt.ld, isr_tables_swi.ld
FAILED: zephyr/isr_tables.c zephyr/isr_tables_vt.ld zephyr/isr_tables_swi.ld /workdir/zephyr/twister-out/qemu_cortex_a53_qemu_cortex_a53/tests/kernel/interrupt/arch.shared_interrupt.lto/zephyr/isr_tables.c /workdir/zephyr/twister-out/qemu_cortex_a53_qemu_cortex_a53/tests/kernel/interrupt/arch.shared_interrupt.lto/zephyr/isr_tables_vt.ld /workdir/zephyr/twister-out/qemu_cortex_a53_qemu_cortex_a53/tests/kernel/interrupt/arch.shared_interrupt.lto/zephyr/isr_tables_swi.ld
cd /workdir/zephyr/twister-out/qemu_cortex_a53_qemu_cortex_a53/tests/kernel/interrupt/arch.shared_interrupt.lto/zephyr && /usr/bin/python3 /workdir/zephyr/scripts/build/gen_isr_tables.py --output-source isr_tables.c --linker-output-files isr_tables_vt.ld isr_tables_swi.ld --kernel /workdir/zephyr/twister-out/qemu_cortex_a53_qemu_cortex_a53/tests/kernel/interrupt/arch.shared_interrupt.lto/zephyr/zephyr_pre0.elf --intlist-section .intList --intlist-section intList --sw-isr-table
gen_isr_tables.py: error: IRQ 1903323438 (offset=0) exceeds the maximum of 219                                                                             
```
**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.8 (but, this should also be applicable to later and non-Zephyr-SDK versions of GCC as well)
 - Commit SHA or Version used: e646b7f3bb3828140bd7160570d0633bd186d156

**Additional context**

Using `west twister -c -W -p qemu_cortex_a53 -s tests/kernel/interrupt/arch.shared_interrupt.lto -x=CONFIG_SPEED_OPTIMIZATIONS=y` as an example, I think the problem is that GCC/ld currently add additional padding that the parser doesn't expect/know how to deal with. Relevant snippet from zephyr_pre0.map (note the `*fill*`):

```
.intList        0x00000000ffff8000      0x1a1
 *(SORT_BY_ALIGNMENT(.irq_info*))
 .irq_info      0x00000000ffff8000       0x14 /tmp/ccJNSHOl.ltrans1.ltrans.o
                0x00000000ffff8000                _iheader
 *(SORT_BY_ALIGNMENT(.intList*))
 *fill*         0x00000000ffff8014        0x4
 .intList       0x00000000ffff8018      0x189 /tmp/ccJNSHOl.ltrans1.ltrans.o
```

The `IDT_LIST` region starts at 0xffff8000 (from [linker.ld](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/arch/arm64/scripts/linker.ld)), `irq_info` is (reasonably) 20 bytes, and `.intList` is padded to an 8-byte boundary (so, a 4-byte fill is added). The parser seems to assume that the section will only be 4-byte aligned (or, that there won't be any padding more generally), so ends parsing the input incorrectly and produces unexpected values for IRQ numbers, etc. which leads to the failure.

IIUC, the fill is inserted by ld as GCC seems to increase the alignment of the `.intList` input sections here (/the structs within) to 8-bytes at all opt levels _besides_ `-Os` for AArch64. My understanding is that this is done intentionally by GCC, see [here](https://github.com/gcc-mirror/gcc/blob/e3de2962cbac3fc7f1d7c6d0205a62e68f3f4b3a/gcc/config/aarch64/aarch64.h#L124-L133) for AArch64.

Note that this isn't limited to AArch64--see [here](https://github.com/gcc-mirror/gcc/blob/e3de2962cbac3fc7f1d7c6d0205a62e68f3f4b3a/gcc/config/riscv/riscv.h#L242-L247) for RISC-V, for example. Experimentally, GCC seems willing to 8-byte align these sections for AArch64 and RISC-V 64, but 32bit Arm/RISC-V seem ok (4-byte aligned).

FWIW, it doesn't seem like clang/LLVM does this currently (though I suppose it could in the future).

### PR DESCRIPTION
**Pull request by jonathonpenix**
For some target and optimization level combinations (aarch64 and -O2, for example), GCC will over align _isr_list_sname instances. The local isr declaration parser doesn't expect the extra padding that may be introduced and will produce unexpected errors about bad IRQs (`error: IRQ 1903323438 (offset=0) exceeds the maximum of 42`, for example). Prevent this issue by forcing the expected alignment of _isr_list_sname.

Fixes #81254

### CODE REVIEW

File: include/zephyr/sw_isr_table.h [hunk 1]
```diff
@@ -247,7 +247,7 @@ extern struct z_shared_isr_table_entry z_shared_sw_isr_table[];
 
 #define _Z_ISR_DECLARE_DIRECT_C(irq, flags, func, counter)                                         \
 	_Z_ISR_DIRECT_TABLE_ENTRY(irq, func, _MK_IRQ_ELEMENT_SECTION(counter));                    \
-	static struct _isr_list_sname Z_GENERIC_SECTION(.intList)                                  \
+	static Z_DECL_ALIGN(struct _isr_list_sname) Z_GENERIC_SECTION(.intList)                    \
```
Comment (jonathonpenix) [inline include/zephyr/sw_isr_table.h:250]: Just as a note, that this specific usage is broken for AArch64 + GCC + -O2 isn't covered by the tests below and I think is a bit tricky to directly demonstrate given that AArch64 doesn't seem to implement `ARCH_IRQ_DIRECT_CONNECT` currently and (of the targets currently supported by the local isr declaration scheme) GCC only seems to over align here for aarch64 (it also seems to over align for ex: riscv64 though).

My understanding is that this instance should also be impacted in theory though, and if you ex: manually increase the alignment here for 32bit arm, you can observe the same failures in the parser, so hopefully it is ok to change this as well.

Please let me know if I should drop this change though or if there is a better way of testing this!

**Review by andyross — APPROVED** [review]
Looks safe, though I'm confused why this is actually fixing anythign?  Z_DECL_ALIGN just declares the type with alignment attribute with the alignment of... that type.  It **should** be a noop.

Is the problem maybe with padding and not alignment?  I hate these linker games every time the subject comes up.  Do we not declare the struct packed and manually pad it?

**Comment by jonathonpenix** [comment]
> Looks safe, though I'm confused why this is actually fixing anythign? Z_DECL_ALIGN just declares the type with alignment attribute with the alignment of... that type. It should be a noop.

IIUC, GCC may over-align the specific instance of the struct (to be 8 byte aligned in this case) but the `__alignof__(<the struct>)` is still 4 bytes.

As a slightly boiled-down example, see https://godbolt.org/z/h6o4TYqfx (where the -O2 version is 8 byte aligned) versus https://godbolt.org/z/dn984E5nT (where GCC respects the `aligned(__alignof__(struct))` so only 4 byte aligns the struct at -O2)

> Is the problem maybe with padding and not alignment?

I think that is right in that the padding is the real issue, but I believe the padding comes about due to the over alignment. My understanding is as follows (see https://github.com/zephyrproject-rtos/zephyr/issues/81254#issue-2650825336 for full context):

The IDT_LIST region starts at 0xffff8000 (from [linker.ld](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/arch/arm64/scripts/linker.ld)), irq_info is (reasonably) 20 bytes, and .intList is padded to an 8-byte boundary (so, a 4-byte fill is added). The parser seems to assume that the section will only be 4-byte aligned (or, that there won't be any padding more generally), so ends parsing the input incorrectly and produces unexpected values for IRQ numbers, etc. which leads to the failure.

> Do we not declare the struct packed and manually pad it?
I might be misunderstanding your suggestion here, but I don't think declaring the struct packed will fix this particular issue, see https://godbolt.org/z/zW7xProc5 (at -O2 it is still being 8 byte aligned)

**Review by peter-mitsis — APPROVED** [review]
