### PR TITLE
drivers: usb: udc: Add SAM USBHS driver

### LINKED ISSUE #74663: Port `usb_dc_sam_usbhs` to `USB_DEVICE_STACK_NEXT`
In order for the `USB_DEVICE_STACK_NEXT` to become the default, existing USB device drivers must be ported to it.
See #42066 for additional details.

Note that if this driver is not ported by Zephyr 4.0.0, this hardware will not work with the default USB stack in 4.0.0.

### PR DESCRIPTION
**Pull request by nandojve**
## Summary

  Add USB Device Controller (UDC) driver for SAM E70/S70/V70/V71 USBHS peripheral, enabling USB device_next stack support for these MCUs.

  - New UDC driver: `drivers/usb/udc/udc_sam_usbhs.c`
  - Supports High-Speed (480 Mbps) and Full-Speed (12 Mbps)
  - PIO-based transfers (DMA support planned for future)
  - USB-IF test mode support for compliance testing
  - Remote wakeup support

  ## Test Plan

  - [x] CDC ACM sample tested on sam_v71_xult
  - [x] Enumeration works on both HS and FS modes
  - [x] usbtest validation passed
  - [x] Data transfer bidirectional working

  Fixes: #74663

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
@nandojve Feel free to cherry-pick https://github.com/zephyrproject-rtos/zephyr/commit/c5e9ee01d1f01914a04d128c7c4cba6cae074acb (from https://github.com/henrikbrixandersen/zephyr/tree/pr_101731_canbardo) on top of your branch. This will aid me in verifying your changes.

**Comment by nandojve** [comment]
> @nandojve Feel free to cherry-pick [c5e9ee0](https://github.com/zephyrproject-rtos/zephyr/commit/c5e9ee01d1f01914a04d128c7c4cba6cae074acb) (from https://github.com/henrikbrixandersen/zephyr/tree/pr_101731_canbardo) on top of your branch. This will aid me in verifying your changes.

I'll pick it!
Thank you!

File: drivers/usb/udc/Kconfig.sam_usbhs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+if UDC_SAM_USBHS
+
+config UDC_SAM_USBHS_HS_SUPPORT
+	bool "High-Speed (480 Mbps) support"
+	select UDC_DRIVER_HAS_HIGH_SPEED_SUPPORT
+	default y
+	help
+	  Enable USB High-Speed (480 Mbps) support. When disabled,
+	  the driver operates in Full-Speed (12 Mbps) mode only.
```
Comment (henrikbrixandersen) [inline drivers/usb/udc/Kconfig.sam_usbhs]: How is this Kconfig symbol different than the already existing, common symbol `UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED`, which is user-selectable?

File: drivers/usb/udc/udc_sam_usbhs.c [hunk 2]
```diff
@@ -0,0 +1,1738 @@
...
+
+#include <zephyr/logging/log.h>
+LOG_MODULE_REGISTER(udc_sam_usbhs, CONFIG_UDC_DRIVER_LOG_LEVEL);
+
+/*
+ * USBHS RAM address - defined in SAM S7x headers but not SAM E7x/V7x
+ */
+#ifndef USBHS_RAM_ADDR
+#define USBHS_RAM_ADDR (0xA0100000)
+#endif
```
Comment (henrikbrixandersen) [inline drivers/usb/udc/udc_sam_usbhs.c]: This could be defined via the devicetree `reg` property using named registers instead.

File: drivers/usb/udc/udc_sam_usbhs.c [hunk 3]
```diff
@@ -0,0 +1,1738 @@
...
+		if (mps <= 128) {
+			return USBHS_EPSIZE_128;
+		} else if (mps <= 256) {
+			return USBHS_EPSIZE_256;
+		} else if (mps <= 512) {
+			return USBHS_EPSIZE_512;
+		}
+		return USBHS_EPSIZE_1024;
+	}
+}
```
Comment (henrikbrixandersen) [inline drivers/usb/udc/udc_sam_usbhs.c]: Could this be simplified into something like:

```
if (mps <= 64) {
    return USBHS_EPSIZE_64;
} else if (mps <= 128) {
    return USBHS_EPSIZE_128;
} else if (...) {
    ...
} ...
```

**Review by henrikbrixandersen — COMMENTED** [review]
Initial pass:

File: drivers/usb/udc/Kconfig.sam_usbhs (hunk 1 above)
Comment (nandojve) [reply drivers/usb/udc/Kconfig.sam_usbhs]: Fixed and documented.

File: drivers/usb/udc/udc_sam_usbhs.c (hunk 2 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbhs.c]: Fixed using DT_INST_REG_ADDR_BY_NAME(0, fifo)

File: drivers/usb/udc/udc_sam_usbhs.c (hunk 3 above)
Comment (nandojve) [reply drivers/usb/udc/udc_sam_usbhs.c]: Fixed using
```
	log2ceil_mps = 32 - __builtin_clz((MAX(ep_cfg->mps, 64) << 1) - 1) - 1;
	regval |= USBHS_DEVEPTCFG_EPSIZE(log2ceil_mps - 3);

```

**Review by henrikbrixandersen — DISMISSED** [review]

File: drivers/usb/udc/Kconfig.sam_usbhs [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+	depends on DT_HAS_ATMEL_SAM_USBHS_ENABLED
+	select PINCTRL
+	select EVENTS
+	select UDC_DRIVER_HAS_HIGH_SPEED_SUPPORT
+	help
+	  SAM E70/S70/V70/V71 family USBHS device controller driver.
+
+	  The driver support High-Speed (480 Mbps) and Full-Speed (12 Mbps)
+	  operation. High-Speed is the default one and can also be disabled
+	  globally via CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED=n or by
```
Comment (jfischer-no) [inline drivers/usb/udc/Kconfig.sam_usbhs]: Device behavior is the same but not the firmware. I had an example somewhere of how to fix it. I will come up with a detailed review next day.

Comment (henrikbrixandersen) [reply drivers/usb/udc/Kconfig.sam_usbhs]: Any hints on this would be great, thanks.

Comment (jfischer-no) [reply drivers/usb/udc/Kconfig.sam_usbhs]: Actually, there is no need to use the maximum-speed property in this driver. AFAIK, high-speed PHY is always available in these devices, and the driver does not support multiple instances (not sure if there are any SAMx7 devices with multiple controllers), therefore there is no need to use maximum-speed property. But if I am wrong and there is a reason, then maximum-speed property should not be optional. And for this driver high speed configuration could be done usual way mixing DT and Kconfig,

```
DT_SAM_HAS_HIGH_SPEED := $(dt_compat_any_has_prop,$(DT_COMPAT_ATMEL_SAM_USBHS),maximum-speed,high-speed)

config UDC_SAM_USBHS
	bool "SAM USBHS USB Device Controller driver"
	default y
	depends on DT_HAS_ATMEL_SAM_USBHS_ENABLED
	select PINCTRL
	select EVENTS
	select UDC_DRIVER_HAS_HIGH_SPEED_SUPPORT if $(DT_SAM_HAS_HIGH_SPEED)"
```

(I started to review it and hope to finish it until Monday.)

**Comment by nandojve** [comment]
Hi @jfischer-no ,

> (I started to review it and hope to finish it until Monday.)

Ahh, we both were waiting each other.

> Are you going to react somehow to my comment, https://github.com/zephyrproject-rtos/zephyr/pull/101731#discussion_r2721466649?

Yes, I'll I adjust.

File: drivers/usb/udc/Kconfig.sam_usbhs (hunk 4 above)
Comment (nandojve) [reply drivers/usb/udc/Kconfig.sam_usbhs]: Adapted Kconfig to be as suggested.

**Review by henrikbrixandersen — DISMISSED** [review]

File: drivers/usb/udc/Kconfig.sam_usbhs (hunk 4 above)
Comment (jfischer-no) [reply drivers/usb/udc/Kconfig.sam_usbhs]: But the Kconfig still mentions maximum-speed property.

Comment (nandojve) [reply drivers/usb/udc/Kconfig.sam_usbhs]: There is no mentioned about the KConfig option now.

**Review by henrikbrixandersen — DISMISSED** [review]

File: dts/bindings/usb/atmel,sam-usbhs.yaml [hunk 5]
```diff
@@ -1,9 +1,20 @@
...
 
 description: |
     Atmel SAM Family USB (USBHS) in device mode
 
+    The USBHS controller has two memory regions:
+    - "core": USBHS register block
+    - "fifo": Dual-Port RAM (DPRAM) for endpoint FIFOs
+
+    The SAM USBHS has 10 hardware endpoints (EP0-EP9). EP0 is the
+    bidirectional control endpoint. The remaining endpoints are
```
Comment (jfischer-no) [inline dts/bindings/usb/atmel,sam-usbhs.yaml]: There is nothing like "bidirectional control endpoint" in USB spec. I see it used more often, and it is really annoying. Please do not use it in the code or devicetree comments.

File: dts/bindings/usb/atmel,sam-usbhs.yaml [hunk 6]
```diff
@@ -13,9 +24,37 @@ include:
...
     required: true
 
   clocks:
     required: true
+
+  num-bidir-endpoints:
+    const: 1
+    description: |
+      Number of bidirectional endpoints. For SAM USBHS, only EP0 is truly
+      bidirectional. Non-EP0 endpoints are direction-constrained by hardware.
```
Comment (jfischer-no) [inline dts/bindings/usb/atmel,sam-usbhs.yaml]: You do not need this property, include usb-controller.yaml instead. A USB device must have control IN/OUT endpoints.

File: drivers/usb/udc/CMakeLists.txt [hunk 7]
```diff
@@ -22,3 +22,4 @@ zephyr_library_sources_ifdef(CONFIG_UDC_AMBIQ udc_ambiq.c)
 zephyr_library_sources_ifdef(CONFIG_UDC_RENESAS_RA udc_renesas_ra.c)
 zephyr_library_sources_ifdef(CONFIG_UDC_MAX32 udc_max32.c)
 zephyr_library_sources_ifdef(CONFIG_UDC_SAM0 udc_sam0.c)
+zephyr_library_sources_ifdef(CONFIG_UDC_SAM_USBHS udc_sam_usbhs.c)
```
Comment (jfischer-no) [inline drivers/usb/udc/CMakeLists.txt:26]: >Fixes: #74663

Please remove it from commit message.

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: dts/bindings/usb/atmel,sam-usbhs.yaml (hunk 5 above)
Comment (nandojve) [reply dts/bindings/usb/atmel,sam-usbhs.yaml]: dropped bidirectional word

File: dts/bindings/usb/atmel,sam-usbhs.yaml (hunk 6 above)
Comment (nandojve) [reply dts/bindings/usb/atmel,sam-usbhs.yaml]: dropped num-bidir-endpoints (num of bidirectional endpoints). Almost (if not) all drivers are using it include the driver you wrote for sam0.

File: drivers/usb/udc/CMakeLists.txt (hunk 7 above)
Comment (nandojve) [reply drivers/usb/udc/CMakeLists.txt:26]: This is how we link a issue to a PR. It is documented in [adding links](https://docs.zephyrproject.org/latest/contribute/guidelines.html#adding-links). This is Zephyr only and it is correct.

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
Retested with latest push on the `canbardo` board.

**Review by jfischer-no — APPROVED** [review]
