### PR TITLE
i2c: bitbang: fix SDA pin configuration

### LINKED ISSUE #27855: i2c bitbanging on nrf52840
Hi,
I am trying to use i2c_gpio (bitbanging) on nrf52840. I am unable to make it work yet! Did anyone test bitbanging i2c on nrf52840?

Following DT settings used.
```
     gpio_i2c0: gpio_i2c {                                                                                         
         compatible = "gpio-i2c";
         status = "okay";
         clock-frequency = <I2C_BITRATE_STANDARD>;
         sda-gpios = <&gpio0 26 (GPIO_OPEN_DRAIN)>;
         scl-gpios = <&gpio0 27 (GPIO_OPEN_DRAIN)>;
         label = "GPIO_I2C_0";
         #address-cells = <1>;
         #size-cells = <0>;
     }
```

### PR DESCRIPTION
**Pull request by pabigot**
The driver must be able to read from this pin as well as write to it.

Fixes #27855.

### CODE REVIEW

**Comment by pabigot** [comment]
File this under "how did this ever work?".

**Review by jfischer-no — APPROVED** [review]

File: drivers/i2c/i2c_gpio.c [hunk 1]
```diff
@@ -142,7 +142,7 @@ static int i2c_gpio_init(struct device *dev)
 	}
 
 	err = gpio_config(context->sda_gpio, config->sda_pin,
-			  config->sda_flags | GPIO_OUTPUT_HIGH);
+			  config->sda_flags | GPIO_INPUT | GPIO_OUTPUT_HIGH);
```
Comment (henrikbrixandersen) [inline drivers/i2c/i2c_gpio.c:145]: I suspect this will render the I2C GPIO bit banging driver useless on most GPIO controllers, since they fail configuration if both GPIO_INPUT and GPIO_OUTPUT are specified.

I tested the existing implementation on the FRDM-K64F using `PORT_PCR_ODE_MASK` pinmux configuration, which puts the given pin in open-drain mode. It's configured as an output, but the open drain configuration allows it to be pulled down - and that real value is read back.

One could argue, that the GPIO controller driver should allow GPIO_INPUT | GPIO_OUTPUT when the pin is configured as open-drain, but the GPIO controller driver has no easy way of knowing the pinmux configuration.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
We need to come up with a solution that doesn't break existing functionality (here: support for existing GPIO controllers/boards):

File: drivers/i2c/i2c_gpio.c (hunk 1 above)
Comment (pabigot) [reply drivers/i2c/i2c_gpio.c:145]: I've updated this so if configuring bidirectional fails it should fall back to the old way.

**Review by henrikbrixandersen — APPROVED** [review]
Thanks.
