### PR TITLE
test wdt_basic_api failed on nucleo_f746zg

### LINKED ISSUE #22257: test wdt_basic_api failed on nucleo_f746zg
**Describe the bug**
Test is failed and device keeps looping in first test functsion:
```
Running test suite wdt_basic_test
===================================================================
starting test - test_wdt
Testcase: test_wdt_no_callback
Waiting to restart MCU
Running test suite wdt_basic_test
===================================================================
starting test - test_wdt
Testcase: test_wdt_no_callback
Waiting to restart MCU
Running test suite wdt_basic_test
===================================================================
...
```

**To Reproduce**
`./scripts/sanitycheck -p nucleo_f746zg --device-serial /dev/ttyACM0 --device-testing -T tests/drivers/watchdog`

**Expected behavior**
Test pass

### PR DESCRIPTION
**Pull request by FRASTM**
This patches add a delay after setting the watchdog to wait for the register (Prescaler and Counter registers) to be updated and reload before leaving.
It modifies  the `iwdg_stm32_install_timeout` function of the `wdt_iwdg_stm32.c` 

Fixes  #22257

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

File: drivers/watchdog/wdt_iwdg_stm32.c [hunk 1]
```diff
@@ -126,6 +126,17 @@ static int iwdg_stm32_install_timeout(struct device *dev,
 	LL_IWDG_SetPrescaler(iwdg, prescaler);
 	LL_IWDG_SetReloadCounter(iwdg, reload);
 
+	/* Wait for the register to be updated */
+	while (LL_IWDG_IsReady(iwdg) != 0) {
+		/* Wait until WVU, RVU, PVU are reset before updating  */
```
Comment (erwango) [inline drivers/watchdog/wdt_iwdg_stm32.c]: I think it should be "Wait until WVU, RVU, PVU are **set** before updating"

**Review by erwango — CHANGES_REQUESTED** [review]
One minor comment.
Btw, is there a potential clean up to do in testcase.yaml file to extend testing  on more targets ? (or clean up unrequired tweaks on nucleo_l496 board)

**Comment by ioannisg** [comment]
@FRASTM will you fix this for the upcoming 2.2. release?

File: drivers/watchdog/wdt_iwdg_stm32.c (hunk 1 above)
Comment (FRASTM) [reply drivers/watchdog/wdt_iwdg_stm32.c]: Indeed, the loop waits for the LL_IWDG_IsReady function to return True, meaning that update is completed (The bits are set "to indicate that an update is ongoing")

**Comment by FRASTM** [comment]
There  is no need to wait for LL_IWDG_IsReady(iwdg)
before setting the Prescaler and the reload counter. The sequence to wait after writing to the registers that the update is complete.

**Comment by FRASTM** [comment]
There  is no need to wait for `LL_IWDG_IsReady(iwdg)`
before setting the Prescaler and the reload counter. The sequence to wait after writing to the registers that the update is complete.

**Review by erwango — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
