### PR TITLE
ipv6: improve compliance with RFC2460

### LINKED ISSUE #36593: Failing IPv6 Ready compliance (RFC 2460)
**Describe the bug**
Our product is required to comply with a subset of the IPv6 Ready program (only part of Section 1 for RFC 2460) due to some regulatory constraints. I saw some old closed tickets related to that topic (for example #2333 and #3316), and I know that some compliance testing was performed in the past using Maxwell Pro, but could not find any meaningful public information regarding the current state of the IPv6 stack.

To move forward, we prepared a certification firmware based on Zephyr 2.5.0 and submitted it to the certification lab. Unfortunately results were not great: we failed 16 of the 29 test cases.

**Next Steps**
I will look into addressing the failing cases. To that end, I have a couple of questions regarding that topic:

- Did I missed any public source of information regarding the current conformance state of the IPv6 stack?
- I am a bit surprised by the high number of failed cases and wonder if this could be due to some specifics of our certification firmware or the testing setup. But looking at #3316 they reported that only 13 of the 54 tests passed (in 2017). Are these number something to be expected?
- Is someone else also working on the IPv6 conformance topic ? If yes, it could be beneficial to collaborate together in order to speed up the progress, especially to setup the test environement.
- The old tickets refer to https://wiki.zephyrproject.org/view/Zephyr_IPv6_testing_with_TAHI which is no longer available. I could not find any snapshot in the Wayback Machine. Does someone have a way to retrieve its content, since I assume that it could be of interest for my own testing ?

I will look into setting up TAHI to replicate the tests done by the laboratory.

Any information / help / feedback would be appreciated.

### PR DESCRIPTION
**Pull request by vaussard**
The IPv6 stack does not pass some of the IPv6Ready compliance tests (see the tests specification: https://www.ipv6ready.org/docs/Core_Conformance_5_1_0.pdf). This pull request allows to address 18 of these failures from the "Group 2: Extension Headers and Options" and "Group 3: Fragmentation" subsets:
- Test v6LC.1.2.1: Next Header Zero 
- Test v6LC.1.2.3: Part A: Unrecognized Next Header in Extension Header (Multiple Values) 
- Test v6LC.1.2.3: Part B: Unexpected Next Header in Extension Header 
- Test v6LC.1.2.4: Part A: Destination Options Header precedes Fragment Header, Error from Destination Options Header 
- Test v6LC.1.2.4: Part B: Destination Options Header precedes Fragment Header, Error from Fragment Header 
- Test v6LC.1.2.4: Part C: Fragment Header precedes Destination Options Header, Error from Fragment Header 
- Test v6LC.1.2.4: Part D: Fragment Header precedes Destination Options Header, Error from Destination Options Header 
- Test v6LC.1.2.5: Part B: First Option has Most Significant Bits 00b, Next has Most Significant Bits 10b 
- Test v6LC.1.2.5: Part C: First Option has Most Significant Bits 00b, Next has Most Significant Bits 11b 
- Test v6LC.1.2.8: Part B: PadN Option 
- Test v6LC.1.2.8: Part E: Most Significant Bits 10b, unicast destination 
- Test v6LC.1.2.8: Part F: Most Significant Bits 11b, unicast destination 
- Test v6LC.1.3.1: Part A: All Fragments are Valid 
- Test v6LC.1.3.1: Part B: All Fragments are Valid, reverse order 
- Test v6LC.1.3.2: Part A: Time Elapsed Between Fragments less than Sixty Seconds 
- Test v6LC.1.3.2: Part B: Time Exceeded Before Last Fragments Arrive 
- Test v6LC.1.3.2: Part C: Time Exceeded (Global), Only First Fragment Received 
- Test v6LC.1.3.3: Fragment Header M-Bit Set, Payload Length Invalid 

See the individual commits for more details.

I tested using `samples/net/eth_native_posix/build` and a custom Python script to inject the test payloads. I did the following changes to the config in order to have a successful run (we could probably go with a lower CONFIG_NET_BUF_RX_COUNT):

```
CONFIG_NET_IPV6_FRAGMENT=y
CONFIG_NET_IPV6_FRAGMENT_MAX_COUNT=2
CONFIG_NET_IPV6_FRAGMENT_MAX_PKT=4
CONFIG_NET_IPV6_FRAGMENT_TIMEOUT=60
CONFIG_NET_BUF_RX_COUNT=30
```

I also executed `tests/net/ipv6/` and `tests/net/ipv6_fragment` on native_posix.

Fixes #36593

### CODE REVIEW

**Review by rlubos — APPROVED** [review]
This looks pretty neat, I have no objections.

File: subsys/net/ip/ipv6_fragment.c [hunk 1]
```diff
@@ -472,6 +472,15 @@ enum net_verdict net_ipv6_handle_fragment_hdr(struct net_pkt *pkt,
 	more = flag & 0x01;
 	net_pkt_set_ipv6_fragment_offset(pkt, flag & 0xfff8);
 
+	if (more && net_pkt_get_len(pkt) % 8) {
+		/* Fragment length is not multiple of 8, discard
+		 * the packet and send parameter problem error.
+		 */
+		net_icmpv6_send_error(pkt, NET_ICMPV6_PARAM_PROBLEM,
+				      NET_ICMPV6_PARAM_PROB_HEADER, 0x04);
```
Comment (jukkar) [inline subsys/net/ip/ipv6_fragment.c:508]: The original code had last parameter as 0 but you change it to 0x04, what the value means here? Could you add a comment and/or use a define (if it makes sense) for this magic number.

File: include/net/net_pkt.h [hunk 2]
```diff
@@ -225,7 +225,7 @@ struct net_pkt {
 	uint16_t ipv6_prev_hdr_start;
```
Comment (jukkar) [inline include/net/net_pkt.h:225]: In commit `net: ipv6_fragment: store M-bit in addition to the offset`, could you add more details what the M-bit means so something like
`also inspect the M-bit (More Fragment) of all received fragments.`

File: include/net/net_pkt.h [hunk 3]
```diff
@@ -225,7 +225,7 @@ struct net_pkt {
...
 
 #if defined(CONFIG_NET_IPV6_FRAGMENT)
-	uint16_t ipv6_fragment_offset;	/* Fragment offset of this packet */
+	uint16_t ipv6_fragment_flags;	/* Fragment offset and M flag of this packet */
```
Comment (jukkar) [inline include/net/net_pkt.h:228]: Also here I would suggest `Fragment offset and M (More Fragment) flag of this packet`

File: subsys/net/ip/ipv6_fragment.c [hunk 4]
```diff
@@ -365,39 +365,62 @@ void net_ipv6_frag_foreach(net_ipv6_frag_cb_t cb, void *user_data)
 }
```
Comment (jukkar) [inline subsys/net/ip/ipv6_fragment.c:370]: :+1: to the `net: ipv6_fragment: improve reassembly condition`, great fix. I just wonder if you could add unit tests to `tests/net/ipv6_fragment/src/main.c` to catch these issues.
Having unit tests for all the commits in this PR might be too much work, but we could have some tests at least for this commit. The fixes in this PR are great but they assume that the conformance tests are run periodically to catch any regressions in the IPv6 code. This assumption might be true but if we have at least some tests implemented under `tests/net/`, we could catch any regression(s) earlier.

File: subsys/net/ip/ipv6_fragment.c [hunk 5]
```diff
@@ -432,24 +432,23 @@ static int shift_packets(struct net_ipv6_reassembly *reass, int pos)
 			NET_DBG("Moving [%d] %p (offset 0x%x) to [%d]",
```
Comment (jukkar) [inline subsys/net/ip/ipv6_fragment.c:437]: The `net: ipv6_fragment: fix shift_packets() algorithm` is also a great candidate to create a unit test. It should be quite straight forward to unit test.

**Review by jukkar — COMMENTED** [review]
LGTM. We should add some unit tests for these in order to catch any regression in the IPv6 code. This way we do not rely on that someone runs the conformance tests periodically.

File: subsys/net/ip/ipv6_fragment.c (hunk 1 above)
Comment (vaussard) [reply subsys/net/ip/ipv6_fragment.c:508]: Indeed. 0x04 is the offset of the "Payload Length" field in the IPv6 header. I will add a comment.

File: include/net/net_pkt.h (hunk 2 above)
Comment (vaussard) [reply include/net/net_pkt.h:225]: sure

File: subsys/net/ip/ipv6_fragment.c (hunk 4 above)
Comment (vaussard) [reply subsys/net/ip/ipv6_fragment.c:370]: I will look into implementing some unit tests

**Comment by vaussard** [comment]
Thanks @jukkar I will address your comments

**Comment by pfalcon** [comment]
@vaussard:

> Thanks @jukkar I will address your comments

Any updates?

Also, this is pretty big PR. My usual suggestion is to split such into smaller parts, to have a more gradual merging progress. E.g., you could split a few more obvious ones, which hopefully can be merged soon.

**Comment by vaussard** [comment]
Thanks for the reminder @pfalcon 

I should have some time to rework this PR next week. I will see if I can put the most obvious fixes in a dedicated PR to speed up the merging.

File: include/net/net_pkt.h [hunk 6]
```diff
@@ -622,13 +622,17 @@ static inline void net_pkt_set_ipv6_fragment_start(struct net_pkt *pkt,
 
 static inline uint16_t net_pkt_ipv6_fragment_offset(struct net_pkt *pkt)
 {
-	return pkt->ipv6_fragment_offset;
+	return pkt->ipv6_fragment_flags & 0xfff8;
+}
+static inline uint8_t net_pkt_ipv6_fragment_more(struct net_pkt *pkt)
```
Comment (cfriedt) [inline include/net/net_pkt.h:627]: should this return bool rather than uint8_t?

**Comment by cfriedt** [comment]
@vaussard - any updates? Just minor comments from me but otherwise no blockers, so this could be merged any time.

File: subsys/net/ip/ipv6_fragment.c (hunk 1 above)
Comment (cfriedt) [reply subsys/net/ip/ipv6_fragment.c:508]: Maybe better to use a define of some kind rather than a magic number. If a define does not exist, please add it.

File: include/net/net_pkt.h (hunk 6 above)
Comment (vaussard) [reply include/net/net_pkt.h:627]: This returns the value of the "more" bit. But you are right that it is assigned to a bool variable, so returning a bool could make more sense.

File: include/net/net_pkt.h [hunk 7]
```diff
@@ -622,13 +622,17 @@ static inline void net_pkt_set_ipv6_fragment_start(struct net_pkt *pkt,
 
 static inline uint16_t net_pkt_ipv6_fragment_offset(struct net_pkt *pkt)
 {
-	return pkt->ipv6_fragment_offset;
+	return pkt->ipv6_fragment_flags & 0xfff8;
```
[the remark this answers is not in the document]
Comment (vaussard) [reply include/net/net_pkt.h:625]: I did not found a suitable define for the mask of the fragment offset. But it is probably possible to add a define in include/net/net_ip.h.
I see that this magic value is also used in tests/net/ipv6_fragment/src/main.c.

**Comment by vaussard** [comment]
> @vaussard - any updates? Just minor comments from me but otherwise no blockers, so this could be merged any time.

Hi @cfriedt thanks for the comments, I will address them now.

@jukkar suggested to write some unit tests (which I did not yet tackled sadly) and @pfalcon suggested to split this PR to ease the review. So maybe the best would be to keep some of the most obvious fixes in this PR to merge it now, and do a separate PR with some of the fragmentation fixes that need a unit test? What would you prefer?

File: subsys/net/ip/ipv6_fragment.c (hunk 1 above)
Comment (vaussard) [reply subsys/net/ip/ipv6_fragment.c]: I added a define in include/net/net_ip.h but I am not 100% sure if this is the right place.

File: include/net/net_pkt.h (hunk 2 above)
Comment (vaussard) [reply include/net/net_pkt.h:232]: done

File: include/net/net_pkt.h (hunk 3 above)
Comment (vaussard) [reply include/net/net_pkt.h]: done

File: include/net/net_pkt.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (vaussard) [reply include/net/net_pkt.h]: I added a define in include/net/net_ip.h but I am not 100% sure if this is the right place.

**Comment by vaussard** [comment]
Rebased and addressed most comments (except the new unit tests). I also re-run the TAHI tests covered by this PR.

**Comment by vaussard** [comment]
Sorry, I had to repush due to checkpatch failing caused by long lines.

**Review by cfriedt — APPROVED** [review]
