### PR TITLE
Bluetooth: Controller: nRF53x: Fix up ISO Rx Buffer size

### LINKED ISSUE #89736: Bluetooth: Controller: Missing CIS Established event with default ACL buffer size
**Describe the bug**
If `CONFIG_BT_BUF_ACL_RX_SIZE`/`CONFIG_BT_CTLR_DATA_LENGTH_MAX` is set to their default value of 27 then it seems that there's an issue with generating/providing the CIS Established event to the host. 

**To Reproduce**
1. Comment out `CONFIG_BT_BUF_ACL_RX_SIZE` and `CONFIG_BT_CTLR_DATA_LENGTH_MAX` in https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/hci_ipc/nrf5340_cpunet_iso-bt_ll_sw_split.conf
1. west build -b nrf5340_audio_dk/nrf5340/cpuapp --sysbuild samples/bluetooth/bap_unicast_client/ -- -DCONFIG_BT_ISO_LOG_LEVEL_DBG=y
2. west flash
3. west build -b nrf5340_audio_dk/nrf5340/cpuapp --sysbuild samples/bluetooth/bap_unicast_server/ -- -DCONFIG_BT_ISO_LOG_LEVEL_DBG=y
4. west flash
5. See unicast client having a CIS stuck in the connecting state

**Expected behavior**
Expect that the ACL buffer size does not affect the generation of the CIS established event / CIS establishment. 

**Impact**
A workaround is simply setting the value higher. At the time of reporting this, a minimum required value has not been determined, but at least setting 255/251 (the values configured by https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/hci_ipc/nrf5340_cpunet_iso-bt_ll_sw_split.conf works). 

**Logs and console output**
```
Connecting streams
[00:00:09.021,728] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x200078b4 iso 0x20006640 disconnected -> connecting
[00:00:09.372,314] <dbg> bt_iso: hci_le_cis_established: status 0x00  handle 7
[00:00:09.372,344] <dbg> bt_iso: store_cis_info: iso_chan 0x200078b4 tx 0x200078f8 rx 0x200078d8
[00:00:09.372,344] <dbg> bt_iso: bt_iso_connected: 0x20006640
[00:00:09.372,406] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x200078b4 iso 0x20006640 connecting -> connected
Audio Stream 0x20007478 connected
Audio Stream 0x20007428 connected
[00:00:09.372,985] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x20007914 iso 0x20006738 disconnected -> **connecting**
Audio Stream 0x20007428 started
```

**Environment (please complete the following information):**
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK
 - Commit SHA or Version used: f7a2b4e9136a37d0622e2c809b5599253209e90e

**Additional context**
The issue was found during some PTS testing, and a fix was done in https://github.com/zephyrproject-rtos/zephyr/pull/89680 for the BT Tester. In those cases connecting a single CIS fails, but in the samples we properly connect the first CIS, but not the second. This could indicate that only the last (or only if there's only a single CIS) fails to be established.

### PR DESCRIPTION
**Pull request by cvinayak**
Fix up the bus fault by not violating the MAXPACKETSIZE value range of NRF_CCM h/w peripheral.

Fix up relates to commit 920117922bc8 ("Bluetooth: Controller: nRF53x: Fix NRF_CCM MAXPACKETSIZE value").

Fixes #89736.

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 1]
```diff
@@ -2214,16 +2214,11 @@ static void *radio_ccm_ext_rx_pkt_set(struct ccm *cnf, uint8_t phy, uint8_t pdu_
...
-#define NRF_CCM_WORKAROUND_XXXX_MAXPACKETSIZE_EXTRA 1U
-
 	const uint8_t max_len = (NRF_RADIO->PCNF1 & RADIO_PCNF1_MAXLEN_Msk) >>
 				RADIO_PCNF1_MAXLEN_Pos;
 
 	/* MAXPACKETSIZE value 0x001B (27) - 0x00FB (251) bytes */
-	NRF_CCM->MAXPACKETSIZE =
-		MAX(MIN((max_len - 4U + NRF_CCM_WORKAROUND_XXXX_MAXPACKETSIZE_EXTRA), 0x00FB),
-		    0x001B);
+	NRF_CCM->MAXPACKETSIZE = MAX(MIN((max_len - 4U), 0x00FB), 0x001B);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Consider using `CLAMP`:
```suggestion
	NRF_CCM->MAXPACKETSIZE = CLAMP(max_len - 4U, 0x001B, 0x00FB);
```

The magic number `4` is not documented. 
The values 0x001B and 0x00FB are also used magic numbers. Suggest to use `BT_HCI_LE_MAX_TX_OCTETS_MIN` and `BT_HCI_LE_MAX_TX_OCTETS_MAX`:
```suggestion
	NRF_CCM->MAXPACKETSIZE = CLAMP(max_len - 4U, BT_HCI_LE_MAX_TX_OCTETS_MIN, BT_HCI_LE_MAX_TX_OCTETS_MAX);
```

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c [hunk 2]
```diff
@@ -2402,7 +2397,7 @@ static void *radio_ccm_ext_tx_pkt_set(struct ccm *cnf, uint8_t pdu_type, void *p
 				RADIO_PCNF1_MAXLEN_Pos;
 
 	/* MAXPACKETSIZE value 0x001B (27) - 0x00FB (251) bytes */
-	NRF_CCM->MAXPACKETSIZE = max_len - 4U;
+	NRF_CCM->MAXPACKETSIZE = MAX(MIN((max_len - 4U), 0x00FB), 0x001B);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Ditto

**Comment by Thalley** [comment]
@cvinayak the issue referenced by this PR (to be fixed) is already closed as fixed: https://github.com/zephyrproject-rtos/zephyr/issues/89736 

Is that intentional?

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Updated.

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: Updated.

**Comment by cvinayak** [comment]
> @cvinayak the issue referenced by this PR (to be fixed) is already closed as fixed: #89736
> 
> Is that intentional?

yes, intentional. The prior fix was incorrect (but sufficient to avoid memory corruptions by DMA).

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: @cvinayak Wouldn't it be better to use `BT_HCI_LE_MAX_TX_OCTETS_MIN` and `BT_HCI_LE_MAX_TX_OCTETS_MAX`?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c]: These value are nRF CCM limitations, an ISO PDU can be 1 to 251 bytes. https://docs.nordicsemi.com/bundle/ps_nrf52840/page/ccm.html#ariaid-title28

I could not find a define in MDK to use, nrfx too uses magic values, hence keeping it as-is to be consistent with product specification documentation and use in MDK.

https://github.com/zephyrproject-rtos/hal_nordic/blob/6e39d4f2b078afaebdb84875089486152fcacb9c/nrfx/hal/nrf_ccm.h#L1073-L1075

**Review by Thalley — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
