### PR TITLE
net: ip: Fix assertion failure when tcp_send_data() with zero length packet

### LINKED ISSUE #36578: net: ip: Assertion fails when tcp_send_data() with zero length packet
**Describe the bug**
When testing TCP stack, assertion fails as following:
```
ASSERTION FAIL [frag] @ /zephyr/zephyrmaster/zephyr/subsys/net/buf.c:640
@ /zephyr/zephyrmaster/zephyr/lib/os/assert.c:45
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x3d87e0 (tcp_work)
E: Halting system
```
The flow of this failure is:
```tcp_work thread``` -> tcp_resend_data() -> tcp_send_data()
```
{ 
        /* 1. send_data_totoal and unacked_len are all 0 in this case */
	len = 0 = MIN3(conn->send_data_total - conn->unacked_len,
		   conn->send_win - conn->unacked_len,
		   conn_mss(conn));

        /* 2. zero length packet (pkt->buffer=NULL) allocated */
	pkt = tcp_pkt_alloc(conn, len=0);
	ret = tcp_pkt_peek(pkt, conn->send_data, pos, len=0);

        /* 3. zero length packet passed to tcp_out_ext() */
	ret = tcp_out_ext(conn, PSH | ACK, pkt, conn->seq + conn->unacked_len);
}
```
-> tcp_out_ext() -> net_pkt_append_buffer(pkt, data->buffer=```NULL```) -> net_buf_frag_insert(..., buffer=```NULL```) -> _ASSERT_NO_MSG(frag) -> ```ASSERTION FAIL```

**To Solve**
Don't proceed if TCP resend length is zero.
```
	len = MIN3(conn->send_data_total - conn->unacked_len,
		   conn->send_win - conn->unacked_len,
		   conn_mss(conn));
	if (len == 0) {
		goto out;
	}
```

**Environment**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit 89212a7fbf5fcd8e4d661c016344ae4bf2d46f53

### PR DESCRIPTION
**Pull request by chyu313**
When tcp_send_data() is called to resend data, but there is no data
to resend, zero length packet is allocated and NULL net_buf is passed
to net_buf_frag_insert() in which assertion fails.

Fixes #36578

Signed-off-by: Chih Hung Yu <chyu313@gmail.com>

### CODE REVIEW

File: subsys/net/ip/tcp2.c [hunk 1]
```diff
@@ -925,6 +925,9 @@ static int tcp_send_data(struct tcp *conn)
 	len = MIN3(conn->send_data_total - conn->unacked_len,
 		   conn->send_win - conn->unacked_len,
 		   conn_mss(conn));
+	if (len == 0) {
+		goto out;
```
Comment (jukkar) [inline subsys/net/ip/tcp2.c:929]: Hmm, shouldn't we return <0 value in this case, now 0 value means in `tcp_resend_data()` that it will increase the retry counter but in this case there is nothing to send.

Comment (rlubos) [reply subsys/net/ip/tcp2.c:929]: I agree, plus I'd add a log message here, so that it's visible how often this occurs.

**Review by rlubos — COMMENTED** [review]
I wonder if there's a deeper synchronization issue in this. I. e. why was `tcp_resend_data()` called if there's no unacknowledged data? It seems as if `tcp_resend_data()` work was already processed by the workqueue while the ACK arrived. If so, it doesn't seem right to reschedule the wokr at the end of the `tcp_resend_data()`. Maybe we should use synchronous cancel on `send_data_timer` work instead, so that even if the work is already processed and rescheduled, it'd get cancelled anyway.

File: subsys/net/ip/tcp2.c (hunk 1 above)
Comment (chyu313) [reply subsys/net/ip/tcp2.c:929]: Is this OK?
```suggestion
		NET_ERR("conn: %p no data to send", conn);
		ret = -ENODATA;
		goto out;
```

Comment (rlubos) [reply subsys/net/ip/tcp2.c:929]: Fine by me

Comment (jukkar) [reply subsys/net/ip/tcp2.c:929]: IMHO `NET_DBG()` is enough here, this is not a very serious issue. Is there an easy way to trigger this condition, how are you testing this?

Comment (chyu313) [reply subsys/net/ip/tcp2.c:929]: 32 TCP clients running on host send data to 32 TCP echo server threads running on native posix, same test as in #32564.

Comment (chyu313) [reply subsys/net/ip/tcp2.c:929]: 2 TCP clients send data to 2 TCP echo server threads can trigger this condition. 
I add k_uptime_get() in log message to see how often this condition occurs for this test.
```
E: conn: 0x567eaef0 no data to send, k_uptime_get()=5400
E: conn: 0x567eaef0 no data to send, k_uptime_get()=7600
E: conn: 0x567eb414 no data to send, k_uptime_get()=8550
E: conn: 0x567eb414 no data to send, k_uptime_get()=20000
E: conn: 0x567eaef0 no data to send, k_uptime_get()=121700
E: conn: 0x567eaef0 no data to send, k_uptime_get()=152050
E: conn: 0x567eb414 no data to send, k_uptime_get()=243450
```

**Comment by chyu313** [comment]
> I wonder if there's a deeper synchronization issue in this. I. e. why was `tcp_resend_data()` called if there's no unacknowledged data?

To speed up the occurrence of this condition, I set ```tcp_rto = 50``` in tcp2.c.

To find out why tcp_resend_data() is called, I add debug message in the place where ```k_work_delayable_remaining_get(&conn->send_data_time)=0``` in tcp_in().
```
	if (!k_work_delayable_remaining_get(
		    &conn->send_data_timer)) {
		printk("%s: conn=%p send_data_total=%d unacked_len=%d send_timer.work.flags=0x%x(%s) uptime=%lld\n",
			__func__, conn, conn->send_data_total, conn->unacked_len, conn->send_data_timer.work.flags, 
			(conn->send_data_timer.work.flags & BIT(K_WORK_DELAYED_BIT)) ? "delayed" : 
			(conn->send_data_timer.work.flags & BIT(K_WORK_QUEUED_BIT)) ? "queued" : "", k_uptime_get());
		NET_DBG("conn: %p, Missing a subscription "
			"of the send_data queue timer", conn);
		break;
	}
```
Debug message when no data to send in tcp_send_data().
```
	len = MIN3(conn->send_data_total - conn->unacked_len,
		   conn->send_win - conn->unacked_len,
		   conn_mss(conn));
	if (len == 0) {
		printk("%s: conn=%p no data to send, thread='%s', uptime=%lld\n", __func__, conn, _current->name, k_uptime_get());
		ret = -ENODATA;
		goto out;
	}
```
The following is debug message printed in console. ```send_timer``` work has already been **_queued_** when ```k_work_delayable_remaining_get(&conn->send_data_time)=0```, and then the work is processed. The work is rescheduled again and again until the application calls zsock_send() to send new data and k_work_cancel_delayable() is called in tcp_in() when the ACK for the new data arrived.
```
tcp_in: conn=0x5689e9dc send_data_total=0 unacked_len=0 send_timer.work.flags=0x104(queued) uptime=4260
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=4260
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=4320
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=4380
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=4440
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=4500
tcp_in: conn=0x5689e9dc send_data_total=0 unacked_len=0 send_timer.work.flags=0x104(queued) uptime=4980
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=4980
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=5040
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=5100
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=5160
tcp_send_data: conn=0x5689e9dc no data to send, thread='tcp_work', uptime=5220
```

**Comment by rlubos** [comment]
@chyu313 Thank you for the detailed analysis.

> The following is debug message printed in console. send_timer work has already been queued when k_work_delayable_remaining_get(&conn->send_data_time)==0, and then the work is processed.

That confirms what I wrote earlier about the work item being already processed, thanks for checking.

> Then I make k_work_cancel_delayable() be called when k_work_delayable_remaining_get()==0, tcp_send_data() will not be called and "no data to send" condition will not occur.

Actually, that made me wonder whether the `k_work_delayable_remaining_get()` check at https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp2.c#L1840 is valid at all. Note that `0` can be returned also when the work is already submitted to the work_q (value > 0 would only be returned if the item is scheduled, but not yet submitted). It doesn't seem right that we prevent cancellation in that case.

> Should we solve this synchronization issue and discard this pull request?

I think that we still need the changes from this PR, regardless of the synchronization issues. A final corner case is when the work handler is already being processed by the work_q, in such case cancellation won't "abort" it. I think though, that a special attention should be put to the work rescheduling at https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp2.c#L1075 - when we detect that retransmission is no longer needed, it should be skipped I believe.

File: subsys/net/ip/tcp2.c [hunk 2]
```diff
@@ -1070,6 +1075,9 @@ static void tcp_resend_data(struct k_work *work)
 
 			goto out;
 		}
+	} else if (ret == -ENODATA) {
+		conn->data_mode = TCP_DATA_MODE_SEND;
+		goto out;
```
Comment (chyu313) [inline subsys/net/ip/tcp2.c:1080]: > when we detect that retransmission is no longer needed, it should be skipped I believe.

I add this code so that no more retransmission if no data to send.

The following is debug message after this patch is applied. tcp_send_data() is not repeatedly called when no data to send. 
```
tcp_in: conn=0x567e64b8 send_data_total=0 unacked_len=0 send_timer.work.flags=0x104(queued) uptime=4380
tcp_send_data: conn=0x567e64b8 no data to send, thread='tcp_work', uptime=4380
tcp_in: conn=0x567e69dc send_data_total=0 unacked_len=0 send_timer.work.flags=0x104(queued) uptime=4740
tcp_send_data: conn=0x567e69dc no data to send, thread='tcp_work', uptime=4740
```

File: subsys/net/ip/tcp2.c [hunk 3]
```diff
@@ -1070,6 +1075,9 @@ static void tcp_resend_data(struct k_work *work)
 
 			goto out;
 		}
+	} else if (ret == -ENODATA) {
+		conn->data_mode = TCP_DATA_MODE_SEND;
```
Comment (rlubos) [inline subsys/net/ip/tcp2.c:1079]: I just wonder if this is the right place to change the data_mode, or if this rather should be done in the TCP state machine.  This would be achieved if we removed the check at https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/ip/tcp2.c#L1840, which as I wrote earlier I don't think is correct. @jukkar I think you have the best insight into the TCP2 codebase, do you have an opinion on this?

Comment (jukkar) [reply subsys/net/ip/tcp2.c:1079]: That is a good question and I do not have clear answer to this. Tweaking/removing the check on line 1840 might be a good start for a fix. Sorry, but is difficult to give direct answer as there might be unseen consequences when changing the TCP code. So I would suggest we experiment with your suggestion before accepting the changes.

Comment (chyu313) [reply subsys/net/ip/tcp2.c:1079]: With https://github.com/zephyrproject-rtos/zephyr/commit/89212a7fbf5fcd8e4d661c016344ae4bf2d46f53 applying this patch, my test described in #32564 did not crash system and the test ran for 240 hours. If this patch is not applied, the NULL pointer access may occur with CONFIG_ASSERT=n.

Comment (rlubos) [reply subsys/net/ip/tcp2.c:1079]: Ok, I think I can accept the fix as it is then. given that you've put it through so severe testing and it actually helps with the problem.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
LGTM
