### PR TITLE
stm32: pwm driver enables complementary output for timer channel

### LINKED ISSUE #40657: Cannot enable secondary pwm out channels on stm32f3
**Describe the bug**
I face problems when trying to use the secondary pwm output channels on stm32f3_diso.
Inspecting the Pins shows no output, while primary channel is working.

**To Reproduce**
1. create an application using pwm output for stm32f3_disco rev E
2. use an overlay with the following content 
```
&pwm1 {
    pinctrl-0 = <&tim1_ch1_pa8 &tim1_ch2_pa9 &tim1_ch3_pa10 &tim1_ch4_pe14>;
    //pinctrl-0 = <&tim1_ch1n_pe8 &tim1_ch2n_pe10 &tim1_ch3n_pe12 &tim1_ch4_pe14>;
};
```
3. `west build --board=stm32f3_disco@E`
4. Flash and check PWM output
5. comment out first pinctrl line and uncomment second
6. Build and flash
7. Check PWM output on secondary pins -> not working

**Expected behavior**
The secondary pins should work the same way, the primary ones work.

Note: Inspecting the `TIM1_CCER` shows no difference, for both firmwares ( `0x1111` for both configurations,
while I expected `0x1444` for the second one, `x/xw 0x40012C20` in gdb)

**Environment (please complete the following information):**
 - OS: Linux, Manjaro
 - Toolchain: Zephyr SDK 0.13.1
 - Commit SHA: 503b7e6f9ff07c2d340cefb6ae970495373e0153

### PR DESCRIPTION
**Pull request by FRASTM**
with this PR, the complementary PWM output is enabled when the pin is choosen in the DTS of the target

Using a newly defined PWM_COMPLEMENTARY flag in the target board DTS as follows:
```
		red_pwm_led: red_pwm_led {
			pwms = <&pwm1 2 4 (PWM_POLARITY_NORMAL | PWM_COMPLEMENTARY)>;
		};
```

- At this time, only used by the stm32 mcus
- Does not impact the PWM input capture.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/40657

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
Tested on the nucleo_l4r5zi target where the PB 14 pin which is for the red Led is a output of a PWM signal from
```
-  Timer15 channel 1, when
-  		red_pwm_led: red_pwm_led {
			pwms = <&pwm15 1 4 PWM_POLARITY_NORMAL>;
		};
```

- or Timer 1 channel 2 N (complementary output), when 
```
- 		red_pwm_led: red_pwm_led {
			pwms = <&pwm1 2 4 PWM_POLARITY_NORMAL>;
		};
```

**Review by gmarull — CHANGES_REQUESTED** [review]
pinctrl information is not meant to be used by drivers directly. If you want PWM to enable complementary output, you should add an additional flag at the pwm node or, propose a new PWM flag. Then user is responsible to set pinctrl appropriately.

**Comment by erwango** [comment]
> pinctrl information is not meant to be used by drivers directly. If you want PWM to enable complementary output, you should add an additional flag at the pwm node or, propose a new PWM flag. Then user is responsible to set pinctrl appropriately.

IIUC this means that we should be able to identify a PWM channel to a pin.
For single channel PWM configuration this is fine, but what about multiple channel configuration, as for instance:
```
	pwm4: pwm {
		status = "okay";
		pinctrl-0 = <&tim4_ch1_pd12
			     &tim4_ch2n_pd13
			     &tim4_ch3n_pd14
			     &tim4_ch4_pd15>;
		pinctrl-names = "default";
	};
```
Does it mean that we can rely on the order of the pins established by the user in pins array ?
(Current work is anyway not sufficient to achieve this anyway as we miss channel to pin matching, but I'd like to understand what are the possibilities)

**Comment by gmarull** [comment]
One option would be to do something like this:

```
red_pwm_led: red_pwm_led {
    pwms = <&pwm12 1 4 (PWM_POLARITY_NORMAL | PWM_COMPLEMENTARY)>;
}; 
```

**Comment by gmarull** [comment]
Or, another option (not tested):

```
#define STM32_PWM_CH(ch) (ch)
#define STM32_PWM_CHN(ch) ((ch) << 3U)

red_pwm_led: red_pwm_led {
    /* use regular output */
    pwms = <&pwm12 STM32_PWM_CH(1) 4 PWM_POLARITY_NORMAL>;
}; 

red_pwm_led: red_pwm_led {
    /* use N output */
    pwms = <&pwm12 STM32_PWM_CHN(1) 4 PWM_POLARITY_NORMAL>;
}; 
```

`STM32_PWM_CHN` would add an _offset_ that indicates complementary output is used for channel 1 (up to 4 or 6 channels are available).

**Comment by FRASTM** [comment]
This option is clear and readable to me because it direcly goes to the pwm driver
```
red_pwm_led: red_pwm_led {
    pwms = <&pwm12 1 4 (PWM_POLARITY_NORMAL | PWM_COMPLEMENTARY)>;
}; 
```

**Comment by FRASTM** [comment]
new version without impact on the pinctrl but only the PWM driver.

**Comment by FRASTM** [comment]
splitting in 2 PR: one for the PWM API #42174
this one for using the #42174  with stm32 mcus

**Comment by FRASTM** [comment]
Note that testing tests/drivers/pwm/pwm_loopback/ requires 32-bit timers that do not have complementary outputs.

**Comment by FRASTM** [comment]
In case the PWM channel is already init'd, setting the polarity with LL_TIM_OC_SetPolarity depends on the complementary or not- complementary channel.

File: drivers/pwm/pwm_stm32.c [hunk 1]
```diff
@@ -103,6 +103,14 @@ static const uint32_t ch2ll[TIMER_MAX_CH] = {
 #endif
 };
 
+static const uint32_t ch2ll_n[TIMER_MAX_CH] = {
+	LL_TIM_CHANNEL_CH1N, LL_TIM_CHANNEL_CH2N,
+	LL_TIM_CHANNEL_CH3N, LL_TIM_CHANNEL_CH4,
```
Comment (ABOSTM) [inline drivers/pwm/pwm_stm32.c:108]: Depending on STM32 series, CH4 can have a complementary channel,like on STM32G4, U5, ...
or not, like STM32L4, ...
Maybe macro IS_TIM_COMPLEMENTARY_CHANNELS  could be used.

File: drivers/pwm/pwm_stm32.c [hunk 2]
```diff
@@ -270,9 +278,17 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
 		LL_TIM_OC_StructInit(&oc_init);
 
 		oc_init.OCMode = LL_TIM_OCMODE_PWM1;
-		oc_init.OCState = LL_TIM_OCSTATE_ENABLE;
+
```
Comment (ABOSTM) [inline drivers/pwm/pwm_stm32.c:281]: Few line above channel is defined like that 
`channel = ch2ll[pwm - 1u];`
it is then used in LL API like` LL_TIM_CC_DisableChannel()`, `LL_TIM_CC_IsEnabledChannel().`
But those API accept Complementary channel. So, is case of complementary, `ch2ll_n[]` should be used

File: drivers/pwm/pwm_stm32.c [hunk 3]
```diff
@@ -270,9 +278,17 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
...
+		/* the flags holds the PWM_COMPLEMENTARY information */
+		if ((flags & PWM_COMPLEMENTARY_MASK) == PWM_COMPLEMENTARY) {
```
Comment (ABOSTM) [inline drivers/pwm/pwm_stm32.c:283]: An error could be raised in case channel doesn't have complementary capability, but it is set in DTS.

**Review by ABOSTM — CHANGES_REQUESTED** [review]

File: drivers/pwm/pwm_stm32.c (hunk 3 above)
Comment (erwango) [reply drivers/pwm/pwm_stm32.c:283]: @ABOSTM This is not possible as is today and proposed pinctrl bondings evolutions to enable it were rejected by mainatainer. This is specified as a "user's responsibility" to provide correct pinctrl configuration.

Comment (gmarull) [reply drivers/pwm/pwm_stm32.c:283]: I guess capability is known, however, whether pin is correctly configured is not.

**Review by gmarull — COMMENTED** [review]
I think STM32 PWM bindings docs should be updated to explain how PWM nodes are expected to be configured and used.

File: drivers/pwm/pwm_stm32.c (hunk 3 above)
Comment (ABOSTM) [reply drivers/pwm/pwm_stm32.c:283]: I mean runtime error thanks to macro IS_TIM_COMPLEMENTARY_CHANNELS()

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
Blocking for now as it adds the same changes as is being discussed in #42174.

**Comment by FRASTM** [comment]
rebase
+ includes the LL_TIM_CHANNEL_CH4N  in the _ch2ll_n_ table when it exists ( stm32G474 for example)
+ warning at runtime when the channel has no complementary output but set by the DTS
+ use the complementary channel if needed in the LL_TIM_CC_DisableChannel and  LL_TIM_CC_IsEnabledChannel functions of the `pwm_stm32_pin_set`.

**Comment by FRASTM** [comment]
changing to a similar approach  as to that for GPIO in https://github.com/zephyrproject-rtos/zephyr/pull/39767
That is a specific  PWM_STM32_COMPLEMENTARY flag for STM32 devices instead of a generic one.

**Review by gmarull — CHANGES_REQUESTED** [review]

File: include/dt-bindings/pwm/stm32_pwm.h [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+/**
+ * @name PWM complementary flag for output pins
+ * This flag can be used with any of the `pwm_pin_set_*` API calls to indicate
+ * that the PWM signal has to be routed to the complementary output channel.
+ * This feature is only available on certain SoC families, refer to the
+ * binding's documentation for more details.
+ * @{
+ */
+/** PWM complementary output pin is enabled */
+#define PWM_STM32_COMPLEMENTARY	(1 << 1)
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply include/dt-bindings/pwm/stm32_pwm.h]: OK to change pwm_flags_t in commit 59d5ba3721148079e6aed1e8a32a10c83ab090ec

**Comment by FRASTM** [comment]
rebase
+ add commit 59d5ba3721148079e6aed1e8a32a10c83ab090ec to add 8bits to the pwm_flags_t  for soc specific flags

File: dts/bindings/pwm/st,stm32-pwm.yaml [hunk 5]
```diff
@@ -31,4 +31,5 @@ pwm-cells:
   - channel
 # period in terms of nanoseconds
   - period
+# set 'PWM_STM32_COMPLEMENTARY' flag if the complementary output is selected
```
Comment (gmarull) [inline dts/bindings/pwm/st,stm32-pwm.yaml:34]: note: this comment is not part of the docs, so maybe update the binding description with some examples (it's just `STM32 PWM` now). This way we'll have stuff rendered in docs automatically.

**Review by gmarull — DISMISSED** [review]
LGTM, one documentation suggestion.

**Review by gmarull — DISMISSED** [review]

File: drivers/pwm/pwm_stm32.c [hunk 6]
```diff
@@ -259,20 +287,49 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
...
+	/* in LL_TIM_CC_DisableChannel and LL_TIM_CC_IsEnabledChannel,
+	 * the channel param.could be the complementary one
+	 */
+	if ((flags & PWM_STM32_COMPLEMENTARY_MASK) == PWM_STM32_COMPLEMENTARY) {
+		is_channel = ch2ll_n[pwm - 1u];
+#if !defined(LL_TIM_CHANNEL_CH4N)
+		if (pwm >= 4) {
+#else
+		if (pwm > 4) {
+#endif /* LL_TIM_CHANNEL_CH4N */
```
Comment (erwango) [inline drivers/pwm/pwm_stm32.c:299]: Let's define a STM32_MAX_N_CHANNEL constant and use it here.

File: drivers/pwm/pwm_stm32.c [hunk 7]
```diff
@@ -259,20 +287,49 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
...
+			LOG_WRN("Channel %d has NO complementary output", pwm);
```
Comment (erwango) [inline drivers/pwm/pwm_stm32.c:300]: Should it be LOG_ERR ?

File: drivers/pwm/pwm_stm32.c [hunk 8]
```diff
@@ -259,20 +287,49 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
 
 	channel = ch2ll[pwm - 1u];
 
+	/* in LL_TIM_CC_DisableChannel and LL_TIM_CC_IsEnabledChannel,
+	 * the channel param.could be the complementary one
+	 */
+	if ((flags & PWM_STM32_COMPLEMENTARY_MASK) == PWM_STM32_COMPLEMENTARY) {
+		is_channel = ch2ll_n[pwm - 1u];
+#if !defined(LL_TIM_CHANNEL_CH4N)
+		if (pwm >= 4) {
```
Comment (erwango) [inline drivers/pwm/pwm_stm32.c:296]: Shouldn't the check be done before `is_channel = ch2ll_n[pwm - 1u];` ?

File: drivers/pwm/pwm_stm32.c [hunk 9]
```diff
@@ -227,6 +254,7 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
 	const struct pwm_stm32_config *cfg = dev->config;
 
 	uint32_t channel;
+	uint32_t is_channel; /* complementary output if used */
```
Comment (erwango) [inline drivers/pwm/pwm_stm32.c:257]: `is_channel` is not quite meaningful.
What about `channel_n_channel` ? (or anything better)

File: drivers/pwm/pwm_stm32.c [hunk 10]
```diff
@@ -259,20 +287,49 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
...
 	}
 
-	if (!LL_TIM_CC_IsEnabledChannel(cfg->timer, channel)) {
+	if (!LL_TIM_CC_IsEnabledChannel(cfg->timer, is_channel)) {
 		LL_TIM_OC_InitTypeDef oc_init;
 
 		LL_TIM_OC_StructInit(&oc_init);
 
 		oc_init.OCMode = LL_TIM_OCMODE_PWM1;
+#if defined(LL_TIM_CHANNEL_CH1N)
```
Comment (erwango) [inline drivers/pwm/pwm_stm32.c:317]: Break a line before #if defined and after #endif (not the other way round)

File: drivers/pwm/pwm_stm32.c [hunk 11]
```diff
@@ -283,17 +340,20 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
...
 #endif /* CONFIG_PWM_CAPTURE */
 
+		/* in LL_TIM_OC_Init, the channel is always the non-complementary */
 		if (LL_TIM_OC_Init(cfg->timer, channel, &oc_init) != SUCCESS) {
 			LOG_ERR("Could not initialize timer channel output");
 			return -EIO;
 		}
 
 		LL_TIM_EnableARRPreload(cfg->timer);
+		/* in LL_TIM_OC_EnablePreload, the channel.is always the non-complementary */
```
Comment (erwango) [inline drivers/pwm/pwm_stm32.c:350]: `channel is`

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/pwm/pwm_stm32.c (hunk 9 above)
Comment (FRASTM) [reply drivers/pwm/pwm_stm32.c:257]: proposal for `current_channel`

**Comment by FRASTM** [comment]
rebase on e8f93a915def87b9c7e1bce3323bec996d7863da
include the https://github.com/zephyrproject-rtos/zephyr/pull/42174
define STM32_MAX_N_CHANNEL
define a current_channel value

File: drivers/pwm/pwm_stm32.c (hunk 6 above)
Comment (FRASTM) [reply drivers/pwm/pwm_stm32.c]:
```
/** Maximum number of complemented timer channels. */
#define STM32_MAX_N_CHANNEL 4
```

**Comment by FRASTM** [comment]
rebase on 095001cdd12b100c1b89f91caf45fc17b357d2d2

**Comment by FRASTM** [comment]
using stm32Cube LL definition to detect the Max nb of timer channels, to define the table of complementary channels
Raise an error if PWM_STM32_COMPLEMENTARY flag is set for a non-existing channel.

**Review by ABOSTM — DISMISSED** [review]
LGTM

File: drivers/pwm/pwm_stm32.c [hunk 12]
```diff
@@ -103,6 +89,20 @@ static const uint32_t ch2ll[TIMER_MAX_CH] = {
 #endif
 };
 
+#if defined(LL_TIM_CHANNEL_CH1N)
```
Comment (erwango) [inline drivers/pwm/pwm_stm32.c:92]: What about moving this #ifdef inside the array, so that array exist but has empty length if LL_TIM_CHANNEL_CH1N is not defined?
This remove the need to use `#ifdef LL_TIM_CHANNEL_CH1N` later in `pwm_stm32_pin_set()'

File: dts/bindings/pwm/st,stm32-pwm.yaml [hunk 13]
```diff
@@ -26,9 +26,14 @@ properties:
 
     "#pwm-cells":
       const: 3
+      description: |
+        Number of items to expect in a PWM
+        - channel of the timer used for PWM
+        - period to set in ns
+        - flags : combination of standard flags like PWM_POLARITY_NORMAL
+        or specific flags like PWM_STM32_COMPLEMENTARY
```
Comment (erwango) [inline dts/bindings/pwm/st,stm32-pwm.yaml:34]: A code snippet would be a plus:
```
		red_pwm_led: red_pwm_led {
			pwms = <&pwm1 2 4 (PWM_POLARITY_NORMAL | PWM_STM32_COMPLEMENTARY)>;
		};
```

**Review by erwango — CHANGES_REQUESTED** [review]

File: dts/bindings/pwm/st,stm32-pwm.yaml (hunk 13 above)
Comment (FRASTM) [reply dts/bindings/pwm/st,stm32-pwm.yaml]: adding the example in the description

File: drivers/pwm/pwm_stm32.c (hunk 12 above)
Comment (FRASTM) [reply drivers/pwm/pwm_stm32.c]: done

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
Can #42174 be closed in favour of this PR?

**Review by erwango — APPROVED** [review]

**Review by gmarull — APPROVED** [review]
