### PR TITLE
bluetooth: shell: bt: Fix unchecked return value of bt_conn_get_info

### LINKED ISSUE #99975: [Coverity CID: 333394] Unchecked return value in subsys/bluetooth/host/shell/bt.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/main/subsys/bluetooth/host/shell/bt.c

Category: Error handling issues
Function: `remote_info_available`
Component: Bluetooth
CID: [333394](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=333394)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/shell/bt.c#L931

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=333394

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

Also see the related [Coverity documentation](https://docs.zephyrproject.org/latest/contributing/coverity.html) for more information.

### PR DESCRIPTION
**Pull request by moonlight83340**
Coverity (CID 333394) reported that the return
value of bt_conn_get_info() was not checked in
remote_info_available(), which could lead to use
of uninitialized data.

Fix this by checking the return value and aborting early in case of error, ensuring that the
connection info structure is valid before use.

Fix https://github.com/zephyrproject-rtos/zephyr/issues/99975

While at it I also fix the other Coverity on the same file :
Coverity (CID 525133) reported that the return
value of bt_conn_get_info() was not checked in
disconnected(), which could lead to use of
uninitialized data.

Fix https://github.com/zephyrproject-rtos/zephyr/issues/90903

### CODE REVIEW

File: subsys/bluetooth/host/shell/bt.c [hunk 1]
```diff
@@ -928,7 +928,10 @@ static void remote_info_available(struct bt_conn *conn,
 {
 	struct bt_conn_info info;
 
-	bt_conn_get_info(conn, &info);
+	if (bt_conn_get_info(conn, &info) < 0) {
+		bt_shell_error("Unable to get info: conn %p", conn);
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt.c]: Suggest to store the return code in a variable and add that to the `bt_shell_error`

File: subsys/bluetooth/host/shell/bt.c
Comment (moonlight83340) [inline subsys/bluetooth/host/shell/bt.c:4198]: Could we add the error code here too ?

Comment (moonlight83340) [inline subsys/bluetooth/host/shell/bt.c:3781]: We use sheel_print here should we used shell_error ?

Comment (moonlight83340) [inline subsys/bluetooth/host/shell/bt.c]: Also here we print conn but not the error

Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c]: @moonlight83340 I'll leave that up to you. You can decide to just fix this one minor place, but feel free to make the other places consistent :)

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/host/shell/bt.c [hunk 2]
```diff
@@ -819,6 +819,7 @@ static void disconnected_set_new_default_conn_cb(struct bt_conn *conn, void *use
 static void disconnected(struct bt_conn *conn, uint8_t reason)
 {
 	char addr[BT_ADDR_LE_STR_LEN];
+	int info_err;
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt.c]:
```suggestion
	int err;
```

For consistency consider just using `err` instead of `info_err`; easier to reuse for any other error handlers

**Review by Thalley — DISMISSED** [review]
No blockers, but a suggestion :)

File: subsys/bluetooth/host/shell/bt.c [hunk 3]
```diff
@@ -819,6 +821,7 @@ static void disconnected_set_new_default_conn_cb(struct bt_conn *conn, void *use
 static void disconnected(struct bt_conn *conn, uint8_t reason)
 {
 	char addr[BT_ADDR_LE_STR_LEN];
+	int err;
```
Comment (Thalley) [inline subsys/bluetooth/host/shell/bt.c]: You can move `err` to the `if` clause

**Review by Thalley — DISMISSED** [review]
I don't see any issues with this. One thing to consider is to use asserts instead of `if`s for error checking, as the function can only fail if provided with invalid input, which we should never do in the shell

File: subsys/bluetooth/host/shell/bt.c (hunk 3 above)
Comment (moonlight83340) [reply subsys/bluetooth/host/shell/bt.c]: In zephyr we tend to have every definition at the function start so I'm not sure if I should move this variable.

Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c]: > In zephyr we tend to have every definition at the function start so I'm not sure if I should move this variable.

I think the actual tendency is to define at the _scope_ start ;)

Comment (moonlight83340) [reply subsys/bluetooth/host/shell/bt.c]: So let me change this ^^

Comment (moonlight83340) [reply subsys/bluetooth/host/shell/bt.c]: Done, thank you !

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/host/shell/bt.c [hunk 4]
```diff
@@ -773,7 +773,7 @@ static void connected(struct bt_conn *conn, uint8_t err)
 
 	info_err = bt_conn_get_info(conn, &info);
 	if (info_err != 0) {
-		bt_shell_error("Failed to connection information: %d", info_err);
+		bt_shell_error("Unable to get info: conn %p Err: %d", conn, info_err);
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c]: I considered mentioning this too, but didn't feel like it was a blocker. If you can, it would be nice to have the consistency :)

**Comment by Thalley** [comment]
@moonlight83340 It needs a rebase :)

**Comment by moonlight83340** [comment]
> @moonlight83340 It needs a rebase :)

Just saw it, sorry !

File: subsys/bluetooth/host/shell/bt.c [hunk 5]
```diff
@@ -781,12 +783,19 @@ static void disconnected(struct bt_conn *conn, uint8_t reason)
...
-		/* If we are connected to other devices, set one of them as default */
-		bt_conn_foreach(info.type, disconnected_set_new_default_conn_cb, NULL);
+		if (err == 0) {
+			/* If we are connected to other devices, set one of them as default */
+			bt_conn_foreach(info.type, disconnected_set_new_default_conn_cb, NULL);
+		}
+
 		if (default_conn == NULL) {
 			bt_conn_foreach(conn_type, disconnected_set_new_default_conn_cb, NULL);
 		}
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c:801]: That is indeed a bug, but not related to this PR

**Review by Thalley — APPROVED** [review]
No objections, LGTM, thanks :)

File: subsys/bluetooth/host/shell/bt.c [hunk 6]
```diff
@@ -726,7 +726,7 @@ static void connected(struct bt_conn *conn, uint8_t err)
 
 	info_err = bt_conn_get_info(conn, &info);
 	if (info_err != 0) {
-		bt_shell_error("Failed to connection information: %d", info_err);
+		bt_shell_error("Unable to get info: conn %p (err %d)", conn, info_err);
```
Comment (jhedberg) [inline subsys/bluetooth/host/shell/bt.c:729]: Just as a general comment, logging pointer values isn't very useful for the user. Using `%s` and ` bt_conn_dst_str(conn)` would be better. I realize that's out of scope for this PR and something that likely needs fixing in a lot of places.

Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c:729]: I disagree: For debugging purposes, the stack mostly logs connections as pointers (instead of the address), so to follow the connection throughout the stack, the value of `conn` is more useful than the address. You do have a point that this isn't a debug log, and thus has less value

Comment (jhedberg) [reply subsys/bluetooth/host/shell/bt.c:729]: You're talking about "the developer". I used the term "the user" on purpose :)

Comment (Thalley) [reply subsys/bluetooth/host/shell/bt.c:729]: Indeed :D And since the shell is under `tests` and not a sample or application, I would expect that the user is always a developer ;P

Comment (moonlight83340) [reply subsys/bluetooth/host/shell/bt.c:729]: @jhedberg are you considering this as a blocker ?
Thanks for your reviews both of you guys !

Comment (jhedberg) [reply subsys/bluetooth/host/shell/bt.c:729]: > @jhedberg are you considering this as a blocker ?

What exactly? The comment about `%p`? Definitely not - that's something to be fixed (if it needs to be) completely separately.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/shell/bt.c (hunk 6 above)
Comment (moonlight83340) [reply subsys/bluetooth/host/shell/bt.c:729]: Yes, I was talking about the `%p` comment.
Thank you, for your review again 🙏
