### PR TITLE
lib: mempool: Fix issues in mempool allocator

### LINKED ISSUE #14504: mempool can return success if no memory was available
**Describe the bug**
We replicated a bug where assertion on data failed. Problem replicates randomly and rarely (I would say once per hour of operation). Quick investigation shown that application gets `0x4` from `k_malloc`. Quick look at the code shown that this is possible if `_sys_mem_pool_block_alloc` returns success but `block.data` is NULL.
Looking at `_sys_mem_pool_block_alloc` proved that this is possible as the loop that is allocating a block gives no guarantee of actually allocating (i.e. `data` can be NULL) but it is always returning zero.

As a bonus there is no lock taken when `level_empty` is called in the first loop so return from it can be invalid (it can be reported as nonempty when in fact it is). I am not 100% sure that giving a lock here would serve any purpose as in the end there is absolutely no guarantee what will be available when second loop of `_sys_mem_pool_block_alloc` is called.

**To Reproduce**
Allocate from various context close to no memory condition.

**Expected behavior**
`'k_malloc' should return NULL if no memory is available.

**Impact**
Showstopper

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
ncs zephyr `745326266d9c32ba3aa67d5af1f727059d9a88e3` (from `d9876be` upstream)

**Additional context**
N/A

### LINKED ISSUE #14508: mempool allocator can return with no allocation even if memory is available
**Describe the bug**
I was wondering if https://github.com/zephyrproject-rtos/zephyr/issues/14504 could happen if memory is actually available. I reviewed the code again and I think it can. This is theoretical scenario, I have not yet tried to replicate it.

The `_sys_mem_pool_block_alloc` has two loops. First is looking which level at which blocks are available (`free_l` and level at which we would like to make an allocation `alloc_l`). Second is allocating and if allocation is done in the higher level then it is splitting the allocated block.

Assume preconditions where no allocation was made and only the biggest block is available (i.e. only level 0 is non-empty). Assume we want to alloc small block from bottom level (anything but the biggest block actually).
Imagine a following race. Context A (e.g. thread) is traversing the first loop. As nothing was broken down yet it finds that the only non empty level (i.e. with free blocks) is level 0. It also finds a level at which it would like to make allocation which will be greater then zero and is not really important.
After finding two indexes but before context A can take a lock and do any allocation a high priority context B (e.g. interrupt) is scheduled and takes over the CPU. It does the same traverse as did context A and finds that only level 0 is non empty. It takes the lock and and enters the second loop. Only level 0 had non empty list of free blocks so it will loop once. Block allocation succeeds and data is not null and since we wanted smaller chunk it will be broken down filling in lists on higher levels. Note here that level zero had only one block so allocating it made the list empty. Context B is done and context A is scheduled back. It resumes just before traversing the second loop. It found that only level 0 has non empty list so it will loop only once. It tries to allocate but fails as list is empty (context B tool the only available element). As this was the only cycle loop finishes with nothing allocated. data is NULL and success is reported (check the other bug).

**To Reproduce**
See description

**Expected behavior**
Allocation should always give block if memory is available.

**Impact**
showstopper

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
ncs zephyr `745326266d9c32ba3aa67d5af1f727059d9a88e3` (from `d9876be` upstream)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pdunaj**
This commits fixes three issues:
Fixes: #14504
1. Allocator returning success even if allocation failed

Fixes: #14508
2. Allocator fails to allocate while memory is available
but was hidden by other context calling free.
3. Allocator fails to allocate while memory is available
but was moved to another level.

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

### CODE REVIEW

File: lib/os/mempool.c [hunk 1]
```diff
@@ -236,67 +231,72 @@ static void *block_break(struct sys_mem_pool_base *p, void *block, int l,
...
+		*data_p = NULL;
+		return -ENOMEM;
+	}
+
+	void *data = NULL;
+
+	unsigned int key = pool_irq_lock(p);
+
+	/* Try allocating the smallest block possible.
+	 * Search must be performed atomically to make sure block rearranging
```
Comment (andyross) [inline lib/os/mempool.c]: The existing design was intended to prevent exactly this circumstance, though.  Making the allocation fully atomic is a latency bug.

**Review by andyross — CHANGES_REQUESTED** [review]
I'm staring at this, and am not entirely convinced this is correct.  Can you share the exerciser code that triggers the issue in the linked bugs?  I think there may be something else going on.

The issue is for sure subtle, but we've been through here several times now and I'm almost certain the current design is correct.

**Comment by andyross** [comment]
(Sorry, put this comment in the wrong spot earlier):

Yeah, we can't do it this way. The fix effectively wraps the whole allocation in a lock, as I understand it. That's counter to the original design intent. Maybe try flagging the existence of a race somehow with a "last thread to enter allocator" state variable or something as a cue to retry?

**Comment by pdunaj** [comment]
Hi @andyross , if you check again you will notice that the amount of the code under the lock is not really increased. What was added is (essentially) checking if free list on n level is empty. And you need to do it under a lock anyway as otherwise content of the list may be broken. Costly operations of alloc and break are already under a lock.

Yes, there is an alternative. Each time allocator state is updated a token could be changed. Block allocator could take a token, do barrier, try allocating and in case there is nomem, grab the current token and if it changed do a retry. I was thinking about this solution but the main problem is that it is unbound. Second thing is that, as I written above, the change is bringing under a lock only checks which levels are empty (which is really cheap operation). The third thing is that such solutions are prone to bugs.

The current state is away from the original design already as locks were introduced to handle various races. Please review the code again - the number of operations added under the lock is really small.

File: lib/os/mempool.c (hunk 1 above)
Comment (pdunaj) [reply lib/os/mempool.c]: The only thing added is checking if level is empty, these are just few operations. Note that `block_alloc` will return immediately if level is empty. Only when there is block available on a level checked `block_alloc` will do something expensive.
So you will end up with once expensive `block_alloc` and few `block_break` (if needed) - both already under a lock.
I personally prefer that to unbound operation with repetitive retries.

File: lib/os/mempool.c [hunk 2]
```diff
@@ -236,67 +231,72 @@ static void *block_break(struct sys_mem_pool_base *p, void *block, int l,
...
+	 * on layers done by another context will not hide memory from us.
+	 */
+	int from_l;
+	for (from_l = alloc_l; from_l >= 0; from_l--) {
+		data = block_alloc(p, from_l, lsizes[from_l]);
```
Comment (andyross) [inline lib/os/mempool.c]: This is the latency bug: the old code was lockless here, but the new code can potentially call block_alloc() once for every level in the allocator before releasing the lock (for reference, a 32k heap of 16 byte blocks has 8 levels).  That's a lot of cycles added to worst case latency!

Comment (pdunaj) [reply lib/os/mempool.c]: I have made some measurements today to check the impact.
I write to GPIO just after lock is taken and just before lock released (not including the internal release/lock done on break). This should measure worst case scenario under the lock and show the additional time spent.

I noticed that previous organization of code gave slightly better timing so I stick with it (comments are not updated yet as there is no point if change is not approved).

I used logic analyzer with 25 MS/s so resolution should be ok.
Testing code does `k_malloc`/`k_free` of given size. As nothing is allocated from the heap before the test this is the worst case scenario where blocks will have to be broken down on higher levels.
Heap was configured as follows: 64B - 1024B (default config in our project). I can reconfigure it to have more levels but the pattern is visible so there may be no point.

This was performed on board with nrf52840.

```
size (B) |  base (us)  | change (us)
-------- | ----------- | -----------
      16 | 8.12 - 8.64 | 8.36 - 8.92
      64 | 5.00 - 5.52 | 5.12 - 5.72
     512 | 1.72 - 2.00 us | 1.72 - 2.08
```

The impact seems to be:
- none if block is available on level
- around 0.12 us per level (block alloc call finds level empty)

Cost of 2x gpio write should be around 0.8 us or so.

Cost of block allocation: around 1 us
Cost of single block break: around 3.2 us

I noticed that current code relax the lock after `block_break` which makes latency sum of both times. I moved the relax before break so now the maximum latency is max of block alloc and break times.
In proposed change we have N checks on level being empty added to normal `block_alloc` time. To have max latency on the same level as `block_break` number of levels would have to be around `(3.2 - 1)/0.12` that is around 18.

Comment (pdunaj) [reply lib/os/mempool.c]: I have increased heap and checked if timings are as expected on higher levels.
```
   level |   base (us)  |  change (us)
-------- | ------------ | ------------
       4 | 14.32 - 14.88 | 14.8 - 15.24
       3 | 11.2 - 11.76 | 11.6 -  12.04
       2 |  8.12 -  8.64 |  8.36 -  8.92
       1 |  5.00 -  5.52 |  5.12 -  5.72
       0 |  1.72 -  2.00 |  1.72 -  2.08
```
It seems to be scaling as expected.

**Comment by pdunaj** [comment]
FYI @pizi-nordic

File: lib/os/mempool.c (hunk 2 above)
Comment (pdunaj) [reply lib/os/mempool.c]: Hi @andyross , have you had a chance to look at the values? The worst case scenario is not increased and I would prefer to leave implementation as is to avoid further problems in this area.
If you are fine I will update the comments.

**Review by andyross — APPROVED** [review]
OK, the holding-the-lock-around-all-the-levels behavior that I thought was there isn't (or maybe you fixed it?).  This design still relaxes the lock at each level, so it seems clean to me.  As expressed here it looks ismorphic to the previous behavior, but with a much smaller window with which to race against other allocators (as I see it it's still possible for a racing free to land "below" the one here and technically add a block that could be returned, but as mentioned I'm not personally convinced that racy "busy memory" is a bug per se).

I'm cool with this.  Thanks.

**Comment by pdunaj** [comment]
thanks
