### PR TITLE
drivers: pwm_nrfx: Refactor pwm_set_cycles to fix on/off issues

### LINKED ISSUE #47854: Multiple blinking LED's cannot be turned off
I have a custom NRF52840 board with 8 LED's and I use pwm API led_on(), led_off, led_blink() etc, to turn them on, set brightness and blink and everything works fine except one case
When I have more than 1 LED's blinking I cannot turn them off
The reason is this block of code in SDK\zephyr\drivers\pwm\pwm_nrfx.c, function  pwm_period_check_and_set()

```c
/* If any other channel (other than the one being configured) is set up
     * with a non-zero pulse cycle, the period that is currently set cannot
     * be changed, as this would influence the output for this channel.
     */
    for (i = 0; i < NRF_PWM_CHANNEL_COUNT; ++i) {
        if (i != channel) {
            uint16_t channel_pulse_cycle =
                data->current[i]
                & PWM_NRFX_CH_PULSE_CYCLES_MASK;
            if (channel_pulse_cycle > 0) {
                LOG_ERR("Incompatible period.");
                return -EINVAL;
            }
        }
    }
```
When multiple LED's are blinking the expression evaluates to true and the code returns -EINVAL and the LED's are not turned off
If I comment out that code block I can turn off multiple blinking LED's 
It seems that the code should detect the case where LED's are be turned off i.e their brightness is set to zero and allow that

### PR DESCRIPTION
**Pull request by anangl**
This commits refactors implementation of the pwm_set_cycles function
to fix the following issues:
- when a channel was already set with a non-zero pulse width, setting
  cycles for another one required specifying a matching period value,
  even if that value was to be ignored anyway when the channel was to
  be set to constant inactive or active level; due to this limitation,
  it was not possible to e.g. use the LED driver API and turn off a LED
  while another one (within the same PWM instance) was blinking
- the above limitation also applied when a channel was set with a pulse
  width equal to period (duty 100%); even though such channel was not
  in fact using the PWM peripheral, other channels within the same PWM
  instance were forced to use the same period
- after a PWM generation was started for a channel, it was not possible
  to change its pulse width before two PWM periods passed (while it
  should be possible to change it after every period); this was caused
  by a looping mechanism that was unnecessarily activated in the PWM
  peripheral

Fixes #47854.

### CODE REVIEW

**Comment by anangl** [comment]
cc @FLATT-Dev

**Review by gmarull — APPROVED** [review]

File: drivers/pwm/pwm_nrfx.c [hunk 1]
```diff
@@ -31,36 +31,59 @@ struct pwm_nrfx_config {
...
 
-static int pwm_period_check_and_set(const struct pwm_nrfx_config *config,
-				    struct pwm_nrfx_data *data,
-				    uint32_t channel,
-				    uint32_t period_cycles)
+static bool channel_needs_pwm(uint32_t channel,
+			      const struct pwm_nrfx_data *data)
+{
+	uint16_t compare_value =
+		data->seq_values[channel] & PWM_NRFX_CH_COMPARE_MASK;
```
Comment (nordic-krch) [inline drivers/pwm/pwm_nrfx.c:45]: is `seq_values` being used only to determine if pwm is used? If yes then it would be simpler to store bit flags. Check would be faster, less ram, etc.

File: drivers/pwm/pwm_nrfx.c [hunk 2]
```diff
@@ -157,70 +149,82 @@ static int pwm_nrfx_set_cycles(const struct device *dev, uint32_t channel,
...
+	 * registers and drives its outputs accordingly.
+	 */
+	if (!needs_pwm && !any_other_channel_needs_pwm(channel, data)) {
+		/* Don't wait here for the peripheral to actually stop. Instead,
+		 * ensure it is stopped before starting the next playback.
 		 */
-		if (was_stopped) {
-			/* Wait until PWM will be stopped and then start the
-			 * sequence.
+		nrfx_pwm_stop(&config->pwm, false);
```
Comment (nordic-krch) [inline drivers/pwm/pwm_nrfx.c:207]: i wonder if we need to care about potential race condition here? What if there is a context switch here and another channel is set. In that case stop is initiated but `stop_requested` flag is not set. Second channel will not pend until pwm is stopped. What are the consequences?

File: drivers/pwm/pwm_nrfx.c (hunk 1 above)
Comment (anangl) [reply drivers/pwm/pwm_nrfx.c:45]: No, the values determine pulse widths for particular channels. See this part:
https://github.com/zephyrproject-rtos/zephyr/blob/89928afbe8ef0eb4a6a4c45146001f112c1ec800/drivers/pwm/pwm_nrfx.c#L168-L172

For channels that are set to constant inactive or active level we have here 0 or `PWM_NRFX_CH_COMPARE_MASK`, respectively, what means that such channel does not need to be driven by the PWM peripheral, and that's what the `channel_needs_pwm` function checks.

File: drivers/pwm/pwm_nrfx.c (hunk 2 above)
Comment (anangl) [reply drivers/pwm/pwm_nrfx.c:207]: In consequence, a playback request made before the PWM actually stopped would be ignored.
But I don't think we should bother. The driver is not (and never was) thread-safe anyway.

File: drivers/pwm/pwm_nrfx.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/pwm/pwm_nrfx.c:45]: i didn't notice that it's used by the nrfx driver by assigning `.seq.values.p_raw = pwm_nrfx_##idx##_data.seq_values,`
but still, maybe it would be worth to create `uint8_t` mask in the data structure (it would fit without increasing the size) and track use of pwm there. Check would be simplified to just mask against 0.

Comment (anangl) [reply drivers/pwm/pwm_nrfx.c:45]: I'm not convinced it would actually be an improvement. This information would need to be maintained in two places then. I still need to provide proper values in the `seq_values` array for those constant channels. Although they do not need the PWM peripheral, they will still be driven by it when the peripheral is required for any other channel.

Comment (nordic-krch) [reply drivers/pwm/pwm_nrfx.c:45]: i won't insist. Though, imo it would be. There is one if/else which would set/clear flags: https://github.com/zephyrproject-rtos/zephyr/blob/89928afbe8ef0eb4a6a4c45146001f112c1ec800/drivers/pwm/pwm_nrfx.c#L152 and then `any_other_channel_needs_pwm` become instant.

**Review by nordic-krch — APPROVED** [review]

File: drivers/pwm/pwm_nrfx.c (hunk 1 above)
Comment (anangl) [reply drivers/pwm/pwm_nrfx.c:45]: Okay, now I see it (a bit late, though :wink:). I'll improve this in a follow-up PR.

**Comment by fabiobaltieri** [comment]
Hey @anangl, I actually have a board with three normal polarity PWM channels on PWM0 that broke after this. :-)

Seems like the problem is related to the polarity, if you change this on an nrf52dk:

```
diff --git a/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832-pinctrl.dtsi b/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832-pinctrl.dtsi
index c859969e55..d2a3ec8b5d 100644
--- a/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832-pinctrl.dtsi
+++ b/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832-pinctrl.dtsi
@@ -56,7 +56,6 @@
        pwm0_default: pwm0_default {
                group1 {
                        psels = <NRF_PSEL(PWM_OUT0, 0, 17)>;
-                       nordic,invert;
                };
        };
 
diff --git a/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832.dts b/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832.dts
index dd72d7d62f..3e7e58735a 100644
--- a/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832.dts
+++ b/boards/arm/nrf52dk_nrf52832/nrf52dk_nrf52832.dts
@@ -47,7 +47,7 @@
        pwmleds {
                compatible = "pwm-leds";
                pwm_led0: pwm_led_0 {
-                       pwms = <&pwm0 0 PWM_MSEC(20) PWM_POLARITY_INVERTED>;
+                       pwms = <&pwm0 0 PWM_MSEC(20) PWM_POLARITY_NORMAL>;
                };
        };
````

And then run `samples/basic/fade_led`, the led does not fade. It works alright with the inverted polarity and by rolling back this patch. Could you look into it?

**Comment by anangl** [comment]
Indeed. I managed to mess it up. 🤦
Here's a fix: https://github.com/zephyrproject-rtos/zephyr/pull/48352.

File: drivers/pwm/pwm_nrfx.c (hunk 1 above)
Comment (anangl) [reply drivers/pwm/pwm_nrfx.c:45]: Addressed in #48353.
