### PR TITLE
drivers: haptics: drv2605 fix unchecked return value

### LINKED ISSUE #81983: [Coverity CID: 434532] Unchecked return value in drivers/haptics/drv2605.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/drivers/haptics/drv2605.c

Category: Error handling issues
Function: `drv2605_reset`
Component: Drivers
CID: [434532](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434532)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/drivers/haptics/drv2605.c#L501

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434532

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by jilaypandya**
return -EIO if i2c_read does not work as expected.

### CODE REVIEW

File: drivers/haptics/drv2605.c [hunk 1]
```diff
@@ -498,7 +498,9 @@ static int drv2605_reset(const struct device *dev)
 	k_msleep(100);
 
 	while (retries > 0) {
-		i2c_reg_read_byte_dt(&config->i2c, DRV2605_REG_MODE, &value);
+		if (i2c_reg_read_byte_dt(&config->i2c, DRV2605_REG_MODE, &value)) {
```
Comment (kartben) [inline drivers/haptics/drv2605.c:501]: Shouldn't this be consistent with how it's done at line 524?

File: drivers/haptics/drv2605.c [hunk 2]
```diff
@@ -498,7 +498,10 @@ static int drv2605_reset(const struct device *dev)
 	k_msleep(100);
 
 	while (retries > 0) {
-		i2c_reg_read_byte_dt(&config->i2c, DRV2605_REG_MODE, &value);
+		ret = i2c_reg_read_byte_dt(&config->i2c, DRV2605_REG_MODE, &value);
```
Comment (rriveramcrus) [inline drivers/haptics/drv2605.c:501]: IIRC this change will break the driver since what we are doing here is polling after a hardware reset until the part is awake and the control port is accessible.

There is a bug here however. `value` is uninitialized until there is a successful `i2c_reg_read_byte_dt`  call, so I think what we should do here is check the return from that call and only check `DRV2605_DEV_RESET` upon a successful transaction or retry otherwise

**Review by rriveramcrus — CHANGES_REQUESTED** [review]

File: drivers/haptics/drv2605.c (hunk 2 above)
Comment (jilaypandya) [reply drivers/haptics/drv2605.c:501]: so the solution would be:

```
retries--;
ret = i2c_reg_read_byte_dt(&config->i2c, DRV2605_REG_MODE, &value);
if(ret<0){
    continue;
}
```

Comment (rriveramcrus) [reply drivers/haptics/drv2605.c:501]: @jilaypandya, I like that solution.

**Review by rriveramcrus — APPROVED** [review]

**Review by kartben — APPROVED** [review]
