### PR TITLE
Bluetooth: Controller: Fix regression in Observer

### LINKED ISSUE #59672: Bluetooth: Controller: ASSERT when scanning
**Describe the bug**
When scanning using the BT shell, two different asserts were triggered: 
```
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c:503
```
and
```
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c:473
	lll_preempt_calc: Actual EVENT_OVERHEAD_START_US = 31555
```

**To Reproduce**
`bt scan on` when using the BT shell. 

**Expected behavior**
Expected to be able to scan without asserts. 

**Impact**
None

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/59107

Using the nRF5340 with the hci_rpmsg sample with nrf5340_cpunet_iso-bt_ll_sw_split.conf on the netcore and the audio shell on the appcore.

**Additional context**
Found during UPF.

### PR DESCRIPTION
**Pull request by cvinayak**
Fixes #59672.

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c [hunk 1]
```diff
@@ -1005,14 +990,52 @@ static void preempt(void *param)
 
 	/* Preemptor not in pipeline */
 	if (next->prepare_param.param != param) {
+		struct lll_event *next_next = NULL;
+		struct lll_event *e;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c:994]: Suggest to use `evt` instead of `e`

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c [hunk 2]
```diff
@@ -1005,14 +990,52 @@ static void preempt(void *param)
...
+		next->is_aborted = 1;
+		next->abort_cb(&next->prepare_param, next->prepare_param.param);
+
+		/* As the prepare queue has been refreshed due to the call of
+		 * abort_cb which invokes the lll_done, find the latest prepare
+		 */
+		idx = UINT8_MAX;
+		do {
+			next = ull_prepare_dequeue_iter(&idx);
+		} while (next && (next->is_aborted || next->is_resume));
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c:1033]: This seems to existing many places in the controller code. 

It seems to dequeue until `next` becomes NULL (queue empty?) or as long as the item is either aborted or `is_resume`. 

It appears to me that this could (should?) be put into a function something like `ull_prepare_dequeue_all_aborted` or something like that

File: subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h [hunk 3]
```diff
@@ -582,6 +582,7 @@ static inline void hal_radio_sw_switch_coded_tx_config_set(uint8_t ppi_en,
 				 BIT(HAL_SW_SWITCH_TIMER_S8_DISABLE_PPI));
 }
 
+#if defined(CONFIG_BT_CTLR_PHY_CODED) && defined(CONFIG_HAS_HW_NRF_RADIO_BLE_CODED)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h:585]: The issue that fixes; should we add a compile configuration for it in CI to avoid it happening again?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio_nrf5_dppi.h:585]: done

**Review by Thalley — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
