### PR TITLE
Bluetooth: hci: spi: Use edge sensitive interrupt and mutex fixes.

### LINKED ISSUE #59459: Bluetooth: hci: spi: host doesn't work on targets which do not support level triggered interrupts
**Bug Description**
With zephyr v3.4, an application implementing an HCI HOST will constantly fail on targets which do not support GPIO level-triggered interrupts. However, this was working with versions of Zephyr prior to 3.3.

This change from edge to level-triggered interrupts was introduced in the following PR #57427 which addresses issue #53980.

**Steps for Reproduction**
To replicate the issue, build a Bluetooth sample configure as a HCI HOST (i.e. with `CONFIG_BT_HCI=y`, `CONFIG_BT_SPI=y` and `CONFIG_BT_CTLR=n`) on a board that doesn't support level-triggered GPIO interrupts (e.g., any stm32 board, nucleo -f429zi in my particular instance).

The problem arises when the host can't configure the IRQ pin as a level-triggered interrupt via [`gpio_pin_interrupt_configure_dt(&irq_gpio, GPIO_INT_LEVEL_ACTIVE);` ](https://github.com/zephyrproject-rtos/zephyr/blob/356c8cbe63ae01b3ab438382639d25bb418a0213/drivers/bluetooth/hci/spi.c#L309).

The stm32 driver explicitly tells level-triggered interrupts are not supported [here](https://github.com/zephyrproject-rtos/zephyr/blob/732dd4843dc5c21f83f17d97bbafbfad8a3bf91a/drivers/gpio/gpio_stm32.c#L614).

**Expected Result**
HCI HOST should ideally be functional even with targets that don't support level-triggered interrupts.

**Consequences**
As it stands, the HCI HOST is incompatible with targets that don't support level-triggered interrupts.

**Environment Details:**
- Linux Fedora 37
- Zephyr v3.4.0
- Zephyr SDK 0.16.1

**Additional Information**
I imagine that only few targets support level-triggered interrupts.
Consequently, it might be more effective to design the HCI driver with the assumption that only edge-triggered interrupts are supported.

While I haven't yet formulated a resolution, I plan to think about it.

Edit:
I edited my message to highlight that this issue was introduced by version 3.4 of zephyr.

### PR DESCRIPTION
**Pull request by HoZHel**
Revert to edge sensitive interrupt. (Fixes #59459 )
Optimized BlueNRG-MS access.
Addressed issue for mutex access of SPI.
Fixed chip select active state for x_nucleo_idb05a1.
I also tested samples/bluetooth/beacon on 96b_carbon board and it works fine; however, without my modifications in spi.c file the application crashes since ST boards do not support level trigger interrupt.

### CODE REVIEW

**Comment by HoZHel** [comment]
@JordanYates I tried to fix the issue #59459 and tested on nucleo_l476rg with x_nucleo_idb05a1.
Everything looks good to me, but I did not test in any other platform. Could you please take a look and let me know about your opinion.
Moreover, would you please inform me regarding the platform you are using for testing changes.
This is my first pull request, and I set in draft state so that I can apply more changes.

File: drivers/bluetooth/hci/spi.c [hunk 1]
```diff
@@ -36,6 +36,7 @@ LOG_MODULE_REGISTER(bt_driver);
 /* Offsets */
 #define STATUS_HEADER_READY	0
 #define STATUS_HEADER_TOREAD	3
+#define STATUS_HEADER_TOWRITE	1
```
Comment (JordanYates) [inline drivers/bluetooth/hci/spi.c:39]: Where did this come from? Offset 1 in the HCI controller sample is `SANITY_CHECK`, nothing to do with writing.

File: boards/shields/x_nucleo_idb05a1/x_nucleo_idb05a1.overlay [hunk 2]
```diff
@@ -5,13 +5,14 @@
  */
 
 &arduino_spi {
-	cs-gpios = <&arduino_header 1 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;	      /* A1 */
+	cs-gpios = <&arduino_header 1 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>;	      /* A1 */
```
Comment (JordanYates) [inline boards/shields/x_nucleo_idb05a1/x_nucleo_idb05a1.overlay:8]: Looks fine, but should be a separate commit in the pull request.

File: drivers/bluetooth/hci/spi.c [hunk 3]
```diff
@@ -302,36 +287,44 @@ static void bt_spi_rx_thread(void)
...
 
-		/* Wait for SPI bus to be available */
-		k_sem_take(&sem_busy, K_FOREVER);
-
 		LOG_DBG("");
 
-		do {
+		/* On BlueNRG-MS, host is expected to read */
+		/* as long as IRQ pin is high */
+		while (irq_pin_high()) {
```
Comment (JordanYates) [inline drivers/bluetooth/hci/spi.c:304]: `irq_pin_high` is defined as `#define irq_pin_high(...) 0` when `!CONFIG_BT_SPI_BLUENRG`, so this code will now never run with other controllers.

File: drivers/bluetooth/hci/spi.c [hunk 4]
```diff
@@ -302,36 +287,44 @@ static void bt_spi_rx_thread(void)
...
 		/* Wait for interrupt pin to be active */
 		k_sem_take(&sem_request, K_FOREVER);
 
-		/* Wait for SPI bus to be available */
-		k_sem_take(&sem_busy, K_FOREVER);
-
 		LOG_DBG("");
 
-		do {
+		/* On BlueNRG-MS, host is expected to read */
```
Comment (carlescufi) [inline drivers/bluetooth/hci/spi.c:302]: This is a common driver. Please do not refer to specific implementations here, or then encapsulate them inside a Kconfig option that does not refer to the particular SoC

**Review by JordanYates — CHANGES_REQUESTED** [review]
Thanks for opening this PR and taking the time to try and fix this issue.
Can I please ask that you structure this PR as 3 commits:
1. revert my original commit that switched to level triggered interrupts
2. apply your proposed changes to the original state of the driver
3. apply your fix to the nucleo shield

This will make it easier to check the changes you are proposing, instead of having to mentally undo my original commit.

Personally I am using an in-house board that uses the in-tree [hci_spi](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/hci_spi) application on a nRF52832/nRF52840 as a Bluetooth controller to a nRF9160 main MCU.

I can't speak for the validity of the fix when using `CONFIG_BT_SPI_BLUENRG`, as that is not a controller that I have ever used or had access to.

File: drivers/bluetooth/hci/spi.c (hunk 4 above)
Comment (JordanYates) [reply drivers/bluetooth/hci/spi.c:302]: Can't fault @HoZHel for this, they've just moved this comment from elsewhere in the file :)
Personally I almost feel like the BlueNRG driver and the Zephyr driver should be separate implementations, its annoying to make the driver work for both.

File: drivers/bluetooth/hci/spi.c [hunk 5]
```diff
@@ -302,36 +287,44 @@ static void bt_spi_rx_thread(void)
 	uint8_t size = 0U;
 	int ret;
 	int len;
+	uint8_t success, is_irq_pin_high;
 
 	(void)memset(&txmsg, 0xFF, SPI_MAX_MSG_LEN);
-
+	/* Enable the interrupt line */
+	gpio_pin_interrupt_configure_dt(&irq_gpio, GPIO_INT_EDGE_TO_ACTIVE);
```
[the remark this answers is not in the document]
Comment (HoZHel) [reply drivers/bluetooth/hci/spi.c:294]: If the interrupt line is low, it will not be a problem since the interrupt is configured for rising edge.

File: boards/shields/x_nucleo_idb05a1/x_nucleo_idb05a1.overlay (hunk 2 above)
Comment (HoZHel) [reply boards/shields/x_nucleo_idb05a1/x_nucleo_idb05a1.overlay:8]: I agree.

File: drivers/bluetooth/hci/spi.c (hunk 3 above)
Comment (HoZHel) [reply drivers/bluetooth/hci/spi.c:304]: I think you are correct, and I will try to find another solution.

**Comment by JordanYates** [comment]
How did you revert my original commit? The recommended way is `git revert <COMMIT>`. It looks like you've missed some changes I had there.

**Comment by HoZHel** [comment]
> How did you revert my original commit? The recommended way is `git revert <COMMIT>`. It looks like you've missed some changes I had there.

I did a "soft" revert since I needed to add some other changes to keep the code functional, in particular SPI mutex fix. I also attached the diff file between 6b36e44887a695c0546dad2577cf383542a36123 (mine) and ca6c08f960d83265497af261c5eda2e782c47b26 (yours). Could you please check if you find something weird?
[diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/12080315/diff.txt)

**Comment by msmttchr** [comment]
> > How did you revert my original commit? The recommended way is `git revert <COMMIT>`. It looks like you've missed some changes I had there.
> 
> I did a "soft" revert since I needed to add some other changes to keep the code functional, in particular SPI mutex fix. I also attached the diff file between [6b36e44](https://github.com/zephyrproject-rtos/zephyr/commit/6b36e44887a695c0546dad2577cf383542a36123) (mine) and [ca6c08f](https://github.com/zephyrproject-rtos/zephyr/commit/ca6c08f960d83265497af261c5eda2e782c47b26) (yours). Could you please check if you find something weird? [diff.txt](https://github.com/zephyrproject-rtos/zephyr/files/12080315/diff.txt)

@JordanYates, for your convenience I have uploaded also the file result of `git revert -n ca6c08f960d83265497af261c5eda2e782c47b26` after fixing a conflict manually.
[spi.c.txt](https://github.com/zephyrproject-rtos/zephyr/files/12103515/spi.c.txt)

I think the changes of @HoZHel are correct. Also, when moving to edge sensitive, interrupts should be permanently enabled, so code to enable interrupt has been moved outside the main `while (true)` loop.
Possibly, interrupt enabling should be moved in `bt_spi_open` to make sure no edges are lost after device reset.

**Comment by carlescufi** [comment]
@JordanYates can you please take another look?

File: drivers/bluetooth/hci/spi.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (JordanYates) [reply drivers/bluetooth/hci/spi.c:291]: I should have said 'active' instead of low. If the line is already active at this point, the thread will block forever

**Review by JordanYates — CHANGES_REQUESTED** [review]
The conflict also needs to be fixed

**Review by erwango — COMMENTED** [review]
BlueNRG-MS is also enabled on following boards:
-disco_l475_iot1
-b_l4s5i_iot01a
-stm32l562e_dk
Can you check if they should also be updated ?

**Comment by HoZHel** [comment]
> BlueNRG-MS is also enabled on following boards: -disco_l475_iot1 -b_l4s5i_iot01a -stm32l562e_dk Can you check if they should also be updated ?

@erwango, I do not have these boards available for testing, but from code inspection, I have noticed the following:

- The dts does not include the recently added parameter `controller-data-delay-us`, this should be set to zero to optimize performance, but it is not strictly needed.
- The chip select should be active low for stm32l562e_dk [(code fragment)](https://github.com/zephyrproject-rtos/zephyr/blob/d22e08c067a5df1f5dd215e3c4e2e8f41c4484d1/boards/arm/stm32l562e_dk/stm32l562e_dk_common.dtsi#L114C1-L115C1).

If you would like to have these fixed, I would think to do it in a separate PR. Do you agree ?
Do you have any chance to test the code on these platforms on your side ?

**Comment by erwango** [comment]
> If you would like to have these fixed, I would think to do it in a separate PR. Do you agree ?

If not directly related to https://github.com/zephyrproject-rtos/zephyr/issues/59459, then it is fine to me.

> Do you have any chance to test the code on these platforms on your side ?

Yes, I'll be able to test.

**Comment by HoZHel** [comment]
> > If you would like to have these fixed, I would think to do it in a separate PR. Do you agree ?
> 
> If not directly related to #59459, then it is fine to me.
> 
Indeed the proposed changes are not related to #59459. I will try to open another PR for them.
> > Do you have any chance to test the code on these platforms on your side ?
> 
> Yes, I'll be able to test.

Thanks for your availability for testing. I will also try to get these boards in my office.

**Comment by erwango** [comment]
Reassigning to @jhedberg as most impact is in bluetooth subsystem

**Review by erwango — APPROVED** [review]
Approved for shield part.

**Comment by HoZHel** [comment]
> @HoZHel Can you fix issues reported in CI:

Done.

**Review by jhedberg — APPROVED** [review]

**Review by JordanYates — APPROVED** [review]
