### PR TITLE
serial: stm32: toggle UE when re-enabling RX DMA to handle U5/H5 errata

### LINKED ISSUE #101345: drivers: uart: stm32: Async API using DMA is broken if disable event occurs
### Describe the bug

On STM32H5 (and likely STM32U5) series MCUs using GPDMA, the UART async API fails to receive data after a disable/re-enable cycle. This affects scenarios where uart_rx_disable() is called (e.g., due to RX timeout with full buffer) followed by uart_rx_enable().

### Root Cause
The USART stops generating DMA receive requests after the DMAR bit in USART_CR3 has been cleared and re-set.

_Note: This appears to be an undocumented hardware issue. The STM32 errata sheets (ES0565 for STM32H5, ES0499 for STM32U5) document a similar issue for the DMAT bit (TX DMA) in section 2.16.2, but do not mention the DMAR bit (RX DMA). However, the same workaround (toggling UE before setting the DMA request bit) resolves the issue for DMAR as well._

### Impact
UART async API is unusable for long-running applications on STM32H5/U5 that need to handle RX timeouts
Affects any use case where RX needs to be restarted
Environment

### Regression

- [ ] This is a regression.

### Configure UART with async API and DMA on STM32H563

1. Start async RX with uart_rx_enable()
2. Wait for RX timeout or buffer full event which triggers uart_rx_disable()
3. Attempt to restart RX with uart_rx_enable()
4. Result: No data is received; USART stops generating DMA requests
5. Expected behavior
6. UART async RX should work correctly after disable/re-enable cycles.

### Relevant log output

Below is with some additional debug logging added

```shell
*** Using Zephyr OS build v4.1.0 ***
I: Starting bootloader
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Primary image: magic=good, swap_type=0x2, copy_done=0x1, image_ok=0x1
I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Bootloader chainload address offset: 0x8000
I: Image version: v0.0.0
I: Jumping to the first image slot

[00:00:00.151,000] <inf> phy_mii: PHY (0) ID 20000181
[00:00:00.151,000] <dbg> phy_mii: phy_mii_cfg_link: PHY (0) Starting MII PHY auto-negotiate sequence
[00:00:00.151,000] <dbg> eth_stm32_hal: eth_initialize: MAC 02:80:e1:2d:0e:13
[00:00:00.152,000] <inf> ais25ba: ctrl_1: 0
[00:00:00.152,000] <inf> ais25ba: ctrl_2: e1
[00:00:00.152,000] <inf> ais25ba: tdm_ctrl: 70
[00:00:00.152,000] <inf> ais25ba: ctrl_fs: 0
[00:00:00.161,000] <inf> TI_HDC30XX: Sensor ready
[00:00:00.162,000] <dbg> eth_stm32_hal: eth_stm32_hal_stop: Stopping ETH HAL driver
[00:00:00.162,000] <dbg> eth_stm32_hal: eth_stm32_hal_stop: HAL_ETH_Stop{_IT} returned error (Ethernet is already stopped)
[00:00:00.162,000] <wrn> net_if: You have 2 IPv4 net_if addresses but 3 network interfaces
[00:00:00.162,000] <wrn> net_if: Consider increasing CONFIG_NET_IF_MAX_IPV4_COUNT value.
*** Booting Zephyr OS build v4.3.0 ***
[00:00:00.163,000] <inf> shell_telnet: Telnet shell backend initialized
[00:00:00.163,000] <inf> pigweed:  Initiating application for pbb8663100_h563vi
[00:00:00.191,000] <inf> pigweed:  ADC device adc@42028000 configured channel 0
[00:00:00.191,000] <inf> pigweed:  ADC device adc@42028000 configured channel 15
[00:00:00.191,000] <inf> pigweed:  ADC device adc@42028000 configured channel 18
[00:00:00.191,000] <inf> pigweed:  ADC device adc@42028000 configured channel 10
[00:00:00.191,000] <inf> pigweed:  ADC device adc@42028000 configured channel 13
[00:00:00.191,000] <inf> pigweed:  ADC device adc@42028100 configured channel 3
[00:00:00.191,000] <inf> pigweed:  ADC device adc@42028000 configured channel 16
[00:00:00.195,000] <inf> pigweed: UART Baudrate = 1250000 bits/s
[00:00:00.251,000] <dbg> phy_mii: check_autonegotiation_completion: PHY (0) auto-negotiate sequence completed
[00:00:00.251,000] <inf> phy_mii: PHY (0) Link speed 100 Mb, full duplex
[00:00:00.251,000] <dbg> eth_stm32_hal: eth_stm32_hal_stop: Stopping ETH HAL driver
[00:00:00.251,000] <dbg> eth_stm32_hal: eth_stm32_hal_stop: HAL_ETH_Stop{_IT} returned error (Ethernet is already stopped)
[00:00:00.251,000] <dbg> eth_stm32_hal: eth_stm32_hal_start: Starting ETH HAL driver
[00:00:00.307,000] <inf> pigweed: DeviceInfo: Total uptime = 8400194 sec
[00:00:00.308,000] <inf> mcuboot_util: Image index: 0, Swap type: none
[00:00:00.327,000] <inf> phy_mii: PHY (0) is down
[00:00:00.327,000] <dbg> eth_stm32_hal: eth_stm32_hal_stop: Stopping ETH HAL driver
[00:00:00.382,000] <inf> pigweed:  Setting up USB-C port
[00:00:00.382,000] <inf> usbd_init: interface 0 alternate 0
[00:00:00.382,000] <inf> usbd_init:     ep 0x81 mps 0x0010 interface ep-bm 0x00020000
[00:00:00.382,000] <inf> usbd_init: interface 1 alternate 0
[00:00:00.382,000] <inf> usbd_init:     ep 0x82 mps 0x0040 interface ep-bm 0x00040000
[00:00:00.382,000] <inf> usbd_init:     ep 0x01 mps 0x0040 interface ep-bm 0x00040002
[00:00:00.382,000] <inf> usbd_init: Instance iface-bm 0x00000003 ep-bm 0x00060002
[00:00:00.382,000] <inf> usbd_init: Init class node 0x200028fc, descriptor length 66
[00:00:00.382,000] <inf> usbd_init: interface 2 alternate 0
[00:00:00.382,000] <inf> usbd_init:     ep 0x83 mps 0x0040 interface ep-bm 0x00080000
[00:00:00.382,000] <inf> usbd_init: interface 3 alternate 0
[00:00:00.382,000] <inf> usbd_init: interface 3 alternate 1
[00:00:00.382,000] <inf> usbd_init:     ep 0x84 mps 0x0040 interface ep-bm 0x00100000
[00:00:00.382,000] <inf> usbd_init:     ep 0x02 mps 0x0040 interface ep-bm 0x00100004
[00:00:00.382,000] <inf> usbd_init: Instance iface-bm 0x0000000c ep-bm 0x00180004
[00:00:00.382,000] <inf> usbd_init: Init class node 0x200029f8, descriptor length 85
[00:00:00.382,000] <inf> usbd_init: bNumInterfaces 4 wTotalLength 160
[00:00:00.382,000] <inf> usbd_init: FS bNumConfigurations 1
[00:00:00.382,000] <inf> pigweed:  CoAP client connecting
[00:00:00.439,000] <inf> pigweed: UdpListener Listening to 0.0.0.0:5683
[00:00:00.439,000] <inf> pigweed: UdpListener Listening to 0.0.0.0:5683
[00:00:00.449,000] <inf> pigweed:  Statically allocated CoAP data: 14164 B
[00:00:00.449,000] <inf> pigweed: TcpListener Listening to 0.0.0.0:502
[00:00:00.449,000] <inf> pigweed:  Application starting
[00:00:00.450,000] <inf> pigweed: NetworkInterface Setting default network interface to spe
[00:00:00.450,000] <inf> pigweed:  ModbusTCP server started
[00:00:00.450,000] <inf> pigweed: TaskMonitorManager: Starting Task Monitor thread
[00:00:00.450,000] <inf> pigweed:  Starting socket monitoring thread
[00:00:00.451,000] <inf> pigweed: Acceleration Starting accelerometer sampling
[00:00:00.451,000] <inf> uart_stm32: DMA RX: busy=1, pending_length=4096, dir=2
[00:00:00.451,000] <inf> uart_stm32: DMA RX config: src=0x40013824, dst=0x20011f68, size=4096, slot=21
[00:00:00.451,000] <inf> uart_stm32: async rx enabled
[00:00:00.451,000] <inf> pigweed: UART Receiving started (#1)
[00:00:00.798,000] <inf> uart_stm32: rx timeout
[00:00:00.798,000] <inf> uart_stm32: DMA RX before stop: busy=0, pending_length=0
[00:00:00.798,000] <wrn> uart_stm32: UART errors during disable: 0x1
[00:00:00.798,000] <inf> pigweed: UART RX disabled
[00:00:00.834,000] <inf> uart_stm32: DMA RX: busy=1, pending_length=4096, dir=2
[00:00:00.834,000] <inf> uart_stm32: DMA RX config: src=0x40013824, dst=0x20012f68, size=4096, slot=21
[00:00:00.834,000] <inf> uart_stm32: async rx enabled
[00:00:00.834,000] <inf> pigweed: UART Receiving started (#2)
[00:00:01.834,000] <inf> pigweed:  Stream timeout
[00:00:12.031,000] <wrn> uart_stm32: Overrun error occurred 1000000 times
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

OS: Zephyr RTOS (main branch / v4.3.0)
Board: STM32H563 (STM32H5 series)
Toolchain: ARM GCC
Relevant configs: CONFIG_UART_ASYNC_API=y, CONFIG_PM=y

### Additional Context

We did not see this issue on zephyr 4.1.0 but have identified the probable root cause being:

https://github.com/zephyrproject-rtos/zephyr/commit/ba35b4d076ad04866c767d1ed4305a873c8c2b73 where the DMAR bit is now set to 0 on Rx disable event which was not the previous case.

As mentioned above this seems to be undocumented hardware issue (similar to the known issue about DMAT).

I have made it work with below workaround:

```
static inline void uart_stm32_dma_rx_enable(const struct device *dev)
{
        const struct uart_stm32_config *config = dev->config;
        struct uart_stm32_data *data = dev->data;
        USART_TypeDef *usart = config->usart;

#ifdef CONFIG_UART_STM32U5_ERRATA_DMAT_AFFECTED
        /*
         * Workaround for STM32H5/U5: USART does not generate DMA requests 
         * after clearing/setting DMAR. This issue is not documented in the
         * errata but behaves similarly to the documented DMAT issue (ES0565
         * section 2.16.2). The same workaround applies: toggle UE (USART 
         * Enable) to reset the USART internal state machine before 
         * re-enabling DMAR.
         */
        LL_USART_Disable(usart);
        LL_USART_Enable(usart);
        /* Wait for USART to be ready after re-enable */
       while (!LL_USART_IsActiveFlag_TEACK(usart)) {
            /* Wait for transmit enable acknowledge */
        }
#endif /* CONFIG_UART_STM32U5_ERRATA_DMAT_AFFECTED */

        LL_USART_EnableDMAReq_RX(usart);
        data->dma_rx.enabled = true;
}
```

### PR DESCRIPTION
**Pull request by Majistor**
On STM32H5 / STM32U5 with GPDMA the USART can stop generating DMA RX requests after uart_rx_disable() clears DMAR and DMAR is later re-enabled. Toggling the USART enable (UE) before re-asserting DMAR resets the USART internal state machine and allows RX DMA requests to resume.

Fixes: #101345

### CODE REVIEW

**Review by djiatsaf-st — DISMISSED** [review]

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -1502,9 +1502,25 @@ static inline void uart_stm32_dma_rx_enable(const struct device *dev)
 {
 	const struct uart_stm32_config *config = dev->config;
 	struct uart_stm32_data *data = dev->data;
+	USART_TypeDef *usart = config->usart;
 
-	LL_USART_EnableDMAReq_RX(config->usart);
+#ifdef CONFIG_UART_STM32U5_ERRATA_DMAT_AFFECTED
+    /*
```
Comment (juickar) [inline drivers/serial/uart_stm32.c]: nit: align this comment block with the following lines

**Comment by Majistor** [comment]
> Note: It could be interesting to see if we could apply a similar workaround [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_stm32.c#L1484-L1499)

I did the same. Or may I have understood wrong

**Review by djiatsaf-st — DISMISSED** [review]

**Review by djiatsaf-st — COMMENTED** [review]
LGTM, just the signoff needs to be changed

**Comment by Majistor** [comment]
> @Majistor 
Hey! @erwango, I want to ask something off topic, but regarding Zephyr. Is this the right place for it?

**Comment by erwango** [comment]
@Majistor Can you rebase ? (this will hopefully get CI passed)

**Review by tpambor — APPROVED** [review]

**Comment by Majistor** [comment]
> @Majistor Can you rebase ? (this will hopefully get CI passed)

finished. sorry for the delay

**Comment by erwango** [comment]
@juickar Still good ?

**Review by juickar — APPROVED** [review]

**Review by erwango — APPROVED** [review]
