### PR TITLE
drivers: ethernet: eth_stm32_hal.c  ETH_MAC_config issue

### LINKED ISSUE #54409: ETH MAC config for STM32H7X and STM32_HAL_API_V2 too late and fails
**Describe the bug**
When trying to configure an STM32H743 for 10M/half duplex it was noticed that the device was still in 100M/Full duplex.
The lines changed were https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/ethernet/eth_stm32_hal.c#L1271

After adding a check of the return value of the call to `HAL_ETH_SetMACConfig()` it was noticed that it returned `HAL_ERROR`. The reason it was not noticed previously was that the return value was not checked and the device currently only runs 100M/full, which is default.

The cause of the call to fail is that the device is not  in `HAL_ETH_STATE_READY` as expected by `HAL_ETH_SetMACConfig()`, it is in state `HAL_ETH_STATE_BUSY` or `HAL_ETH_STATE_STARTED` (same numerical value for both states in ST HAL).

By ,in a hackiish way to test, extracting out the configuration step to a separate function and then call it before `HAL_ETH_Start()` or `HAL_ETH_Start_IT()` was called the interface started to work as expected.

My guess is that this bug has been around since STM32H7X support was added, since this was how it was even before `STM32_HAL_API_V2` was added.

**To Reproduce**
By checking the return value from `HAL_ETH_SetMACConfig()` it is easy to see that it fails.

**Expected behavior**
Checking for return values for potential errors. In this case, make other speeds and duplexes than 100M/Full to work. Also do configuration stage before starting Ethernet.

**Impact**
This is a show stopper (or at least major annoyance) for people using other than 100M/Full. I have spent weeks trying to find this. Also since we have new hardware and PHY there were many questions on where the error was.

**Logs and console output**
None specific. I suggest to add a check to the return value of the call to `HAL_ETH_SetMACConfig()`, and by adding a check for `!= HAL_OK` and then do a `LOG_ERR()` it should be fairly easy.

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain, Zephyr SDK 0.15.1
 - Zephyr Version tested 3.3.0-rc1, but bug is probably in older versions. I started in 3.2.0, where it failed as well.

**Additional context**
My take is that the  configuration for the `STM32H7X` and `HAL_API_V2` should be a part of the configuration for the other chips. The only important part is that this configuration happens before the Ethernet is started.

### PR DESCRIPTION
**Pull request by Desvauxm-st**
ETH MAC config for STM32H7X and STM32_HAL_API_V2
too late and fails #54409
call HAL_ETH_SetMACConfig before HAL_ETH_Start_IT() check the return of HAL_ETH_SetMACConfig()

Signed-off-by: Marc Desvaux <marc.desvaux-ext@st.com>

Fixes #54409

### CODE REVIEW

File: drivers/ethernet/eth_stm32_hal.c [hunk 1]
```diff
@@ -1224,6 +1224,24 @@ static int eth_initialize(const struct device *dev)
...
+	HAL_ETH_SetMDIOClockRange(heth);
+
+	/* @TODO: read duplex mode and speed from PHY and set it to ETH */
+
+	ETH_MACConfigTypeDef mac_config;
+
+	HAL_ETH_GetMACConfig(heth, &mac_config);
+	mac_config.DuplexMode = ETH_FULLDUPLEX_MODE;
+	mac_config.Speed = ETH_SPEED_100M;
+	HAL_StatusTypeDef status_SetMACConfig;
```
Comment (erwango) [inline drivers/ethernet/eth_stm32_hal.c:1238]: Please use camel_case.
Noe that `hal_ret` would be fine and is already declared.

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by erwango** [comment]
@Desvauxm-st Did you verify this is harmless on F4 devices ?

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
