### PR TITLE
Bluetooth: GATT: Fix not clearing stored data when unpairing

### LINKED ISSUE #22514: Bluetooth: gatt: CCC cfg not flushed if device was previously paired
**Describe the bug**
The CCC cfg is not freed/flushed when a paired device disconnects from the peripheral; however, the `ccc_cfg_changed()` callback of the descriptor gets called with `value = 0`. This leads to the CCC cfg buffer becoming full, the warning `bt_gatt: No space to store CCC cfg` to be raised, and no more subscriptions to be allowed.

While debugging, I confirmed that the CCC cfg array was indeed full of identical addresses with notifications active.

**To Reproduce**
1. Use examples `peripheral_hr` and `central_hr` and make them pair after subscription (I have only tested it using fixed passkey pairing and legacy oob pairing)
2. Make it such that the peripheral removes pairing information upon disconnection
3. Flash devices
4. Upon pairing complete, disconnect/reset the central
5. Repeat step 4 until `<wrn> bt_gatt: No space to store CCC cfg` is raised (For me it took 4 cycles on one project, and 2 cycles on another one)

**Expected behavior**
The connect - subscribe - disconnect cycle should have kept going perpetually

**Screenshots or console output**
```
*** Booting Zephyr OS build zephyr-v2.1.0-2046-g71dff17a3703  ***
Bluetooth initialized
Advertising successfully started
Passkey 12
Security changed level 4
Pairing Complete
Disconnected (reason 0x16)
Unpaired
<inf> hrs: HRS notifications disabled
........
Connected
<inf> hrs: HRS notifications enabled
Passkey 12
Security changed level 4
Pairing Complete
Disconnected (reason 0x16)
Unpaired!
<inf> hrs: HRS notifications disabled
Connected
<wrn> bt_gatt: No space to store CCC cfg
```

**Environment (please complete the following information):**
 - Platform NRF52 PCA10040
 - Current head of master d1fa27c42f7e61a327ee02bb36ea0445d4075a6f

Peripheral configuration:
```
CONFIG_BT=y
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_SMP=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_GATT_DIS=y
CONFIG_BT_GATT_DIS_PNP=n
CONFIG_BT_GATT_BAS=y
CONFIG_BT_GATT_HRS=y
CONFIG_BT_DEVICE_NAME="Zephyr Heartrate Sensor"
CONFIG_BT_DEVICE_APPEARANCE=833

CONFIG_BT_FIXED_PASSKEY=y
```

### PR DESCRIPTION
**Pull request by Vudentz**
GATT data shall not be considered conditional to BT_SETTINGS since
the data is stored in RAM it must also be cleared when unpairing.

Fixes #22514

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

**Comment by Vudentz** [comment]
@ivan98ams Give this a try, it should fix #22514

**Comment by ivan98ams** [comment]
Works for me!

**Comment by jhedberg** [comment]
@Vudentz I think there are several places where you can get rid of #ifdefs from around or inside static functions, by making sure the calls to those functions are protected by IS_ENABLED()

**Comment by joerchan** [comment]
@Vudentz Is it possible to split the commit into 2 commits? One for moving the functions inside the file, and one for the actual bug-fix. The diff is a bit hard to read at the moment.

**Comment by Vudentz** [comment]
> @Vudentz I think there are several places where you can get rid of #ifdefs from around or inside static functions, by making sure the calls to those functions are protected by IS_ENABLED()

This is now done, there were a few dependencies to variable declared only inside a #if defined so I needed to a little bit more than just replace #if by IS_ENABLED.

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -4473,3 +4348,154 @@ SETTINGS_STATIC_HANDLER_DEFINE(bt_hash, "bt/hash", NULL, db_hash_set,
...
+	if (err < 0) {
+		return err;
+	}
+
+	err = bt_gatt_clear_cf(id, addr);
+	if (err < 0) {
+		return err;
+	}
+
+	bt_gatt_clear_subscriptions(addr);
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: Why not put `if (IS_ENABLED(CONFIG_BT_GATT_CLIENT))` here instead of doing it inside the function definition. That way you don't need to indent so much code.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -4473,3 +4348,154 @@ SETTINGS_STATIC_HANDLER_DEFINE(bt_hash, "bt/hash", NULL, db_hash_set,
...
+
+	err = bt_gatt_clear_ccc(id, addr);
+	if (err < 0) {
+		return err;
+	}
+
+	err = sc_clear_by_addr(id, addr);
+	if (err < 0) {
+		return err;
+	}
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: You have pretty long `if (IS_ENABLED())` branches inside `bt_gatt_clear_ccc()` and `sc_clear_by_addr()`. Why not put the IS_ENABLED() here instead so you don't need to indent so much code?

File: subsys/bluetooth/host/gatt.c [hunk 3]
```diff
@@ -4473,3 +4348,154 @@ SETTINGS_STATIC_HANDLER_DEFINE(bt_hash, "bt/hash", NULL, db_hash_set,
...
+
+	err = bt_gatt_clear_cf(id, addr);
+	if (err < 0) {
+		return err;
+	}
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: Same here

File: subsys/bluetooth/host/gatt.c (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Right, I had it replacing the #if location but that indeed messes with identation a little too much.

**Review by jhedberg — CHANGES_REQUESTED** [review]
@Vudentz looks better, but I think you can move the IS_ENABLED() checks one call higher up to avoid indenting so much code.

**Comment by Vudentz** [comment]
> @Vudentz looks better, but I think you can move the IS_ENABLED() checks one call higher up to avoid indenting so much code.

Done.

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
@Vudentz please still fix the checkpatch warning regarding redundant return statement

**Comment by Vudentz** [comment]
> @Vudentz please still fix the checkpatch warning regarding redundant return statement

Done.

**Comment by Vudentz** [comment]
@chris-makaio Ive added a for dealing with #22539 as it is somewhat related though you were not using bt_unpair but a regular disconnect which still was not clearing thing properly.

File: subsys/bluetooth/host/gatt.c [hunk 4]
```diff
@@ -4473,3 +4355,154 @@ SETTINGS_STATIC_HANDLER_DEFINE(bt_hash, "bt/hash", NULL, db_hash_set,
...
+
+	if (IS_ENABLED(CONFIG_BT_SETTINGS)) {
+		char key[BT_SETTINGS_KEY_MAX];
+
+		if (id) {
+			char id_str[4];
+
+			u8_to_dec(id_str, sizeof(id_str), id);
+			bt_settings_encode_key(key, sizeof(key), "ccc",
+					       (bt_addr_le_t *)addr, id_str);
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: Unrelated to this PR, but it looks like `bt_settings_encode_key()` needs to be fixed to take a const address pointer

Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: Actually, I take that back. @Vudentz could you include the following patch as a new commit into this PR, and then fix up your current commit not to do the explicit casts:
```
diff --git a/subsys/bluetooth/host/settings.c b/subsys/bluetooth/host/settings.c
index a97bfe9bec..ea138efaf4 100644
--- a/subsys/bluetooth/host/settings.c
+++ b/subsys/bluetooth/host/settings.c
@@ -21,7 +21,7 @@
 
 #if defined(CONFIG_BT_SETTINGS_USE_PRINTK)
 void bt_settings_encode_key(char *path, size_t path_size, const char *subsys,
-                           bt_addr_le_t *addr, const char *key)
+                           const bt_addr_le_t *addr, const char *key)
 {
        if (key) {
                snprintk(path, path_size,
@@ -41,7 +41,7 @@ void bt_settings_encode_key(char *path, size_t path_size, const char *subsys,
 }
 #else
 void bt_settings_encode_key(char *path, size_t path_size, const char *subsys,
-                           bt_addr_le_t *addr, const char *key)
+                           const bt_addr_le_t *addr, const char *key)
 {
        size_t len = 3;
 
diff --git a/subsys/bluetooth/host/settings.h b/subsys/bluetooth/host/settings.h
index c918ad426c..e4854e437c 100644
--- a/subsys/bluetooth/host/settings.h
+++ b/subsys/bluetooth/host/settings.h
@@ -12,7 +12,7 @@
 
 /* Helpers for keys containing a bdaddr */
 void bt_settings_encode_key(char *path, size_t path_size, const char *subsys,
-                           bt_addr_le_t *addr, const char *key);
+                           const bt_addr_le_t *addr, const char *key);
 int bt_settings_decode_key(const char *key, bt_addr_le_t *addr);
 
 void bt_settings_save_id(void);
```

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 5]
```diff
@@ -2131,6 +2136,9 @@ static u8_t disconnected_cb(const struct bt_gatt_attr *attr, void *user_data)
 		} else {
 			/* Clear value if not paired */
 			if (!bt_addr_le_is_bonded(conn->id, &conn->le.dst)) {
+				if (ccc == &sc_ccc) {
+					sc_clear_by_conn(conn);
+				}
```
Comment (joerchan) [inline subsys/bluetooth/host/gatt.c]: style: blank line.

File: subsys/bluetooth/host/gatt.c [hunk 6]
```diff
@@ -2131,6 +2136,9 @@ static u8_t disconnected_cb(const struct bt_gatt_attr *attr, void *user_data)
 		} else {
 			/* Clear value if not paired */
 			if (!bt_addr_le_is_bonded(conn->id, &conn->le.dst)) {
+				if (ccc == &sc_ccc) {
```
Comment (joerchan) [inline subsys/bluetooth/host/gatt.c]: Good find!

File: subsys/bluetooth/host/gatt.c [hunk 7]
```diff
@@ -3693,7 +3693,6 @@ static void gatt_sub_remove(struct bt_conn *conn, struct gatt_sub *sub,
 			    sys_snode_t *prev,
 			    struct bt_gatt_subscribe_params *params)
 {
-	return;
```
Comment (joerchan) [inline subsys/bluetooth/host/gatt.c]: This could be squashed to the previous commit.

**Review by joerchan — COMMENTED** [review]
Looks good, got a few nitpicks.

Finding the second bug was good. I had a note about SC changed issue that i couldn't figure out what I meant anymore. So happy that you found it.

**Review by jhedberg — APPROVED** [review]

**Review by joerchan — APPROVED** [review]
