### PR TITLE
Bluetooth: Audio: Media - truncate strings for notification

### LINKED ISSUE #42090: Bluetooth: Audio: MCS BSIM notification length warning
**Describe the bug**
When running the mcs_mcc.h babblesim tests, it looks like the MTU isn't large to send the application data:

```
d_01: @00:00:19.081741  [00:00:19.081,726] <dbg> bt_mcs: media_proxy_sctrl_track_title_cb: Notifying track title: Interlude #1 (Song for Alison)
d_01: @00:00:19.081741  [00:00:19.081,726] <wrn> bt_att: No ATT channel for MTU 33
d_01: @00:00:19.081741  [00:00:19.081,726] <wrn> bt_gatt: No buffer available to send notification
d_01: @00:00:19.081741  [00:00:19.081,726] <dbg> bt_mcs: notify: Notification error: ENOTCONN (-107)
```

This also means that the remote side, i.e. the client, does not verify the song names in the tests. The server does also not have any GATT MTU requirements similar to the buffer count: 

```c
BUILD_ASSERT(CONFIG_BT_L2CAP_TX_BUF_COUNT >= 10, "Too few L2CAP buffers");
```

**To Reproduce**
Build and run the mcs_mcc.h test

**Expected behavior**
Pass without warnings or errors. 
The client should check for the name notifications
The `BT_MCS_TRACK_TITLE_MAX` should not be above the GATT MTU, or alternatively it should be truncated to fit the MTU when sending (ditto for the other titles). 

**Impact**
Annoyance at this point, but will be a significant issue when this starts to be used. 

**Logs and console output**
See above

**Environment (please complete the following information):**
 - Commit SHA or Version used: d51a67b7c098c8bb5479a7b87f05dc40fb76e065

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by asbjornsabo**
Truncate strings being notified to fit the ATT_MTU, to prevent
notifications from not being delivered due to being too long.

For now uses the minimum ATT_MTU, as the MCS does not yet track
connections.  (See https://github.com/zephyrproject-rtos/zephyr/issues/44176)

Signed-off-by: Asbjørn Sæbø <asbjorn.sabo@nordicsemi.no>

fixes https://github.com/zephyrproject-rtos/zephyr/issues/42090

### CODE REVIEW

File: subsys/bluetooth/audio/mcs.c [hunk 1]
```diff
@@ -808,6 +809,49 @@ static void notify(const struct bt_uuid *uuid, const void *data, uint16_t len)
...
+ * The string must be null-terminated.
+ */
+static void notify_string(const struct bt_uuid *uuid, const char *str)
+{
+	/* TODO:
+	 * This function will need to get the ATT_MTU to know what length to
+	 * truncate the string to.  But the ATT_MTU is per connection, and MCS
+	 * is not connection-aware yet.
+	 * For now: Truncate according to the default ATT_MTU, so that
+	 * notifications will go through
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/mcs.c:823]: I have a feeling this should be handled by the stack to send as much as it can depending on MTU.
So once `bt_gatt_notify_uuid` is called it should feed the buffer up to MTU and leave the client with the decision whether it wants to read the rest. Returning error is not sufficient since, the value should be notified anyway, and the Server has no power to exchange the MTU by itself

File: subsys/bluetooth/audio/mcs.c [hunk 2]
```diff
@@ -808,6 +809,49 @@ static void notify(const struct bt_uuid *uuid, const void *data, uint16_t len)
...
+	}
+
+	if (err) {
+		if (err == -ENOTCONN) {
+			BT_DBG("Notification error: ENOTCONN (%d)", err);
+		} else {
+			BT_ERR("Notification error: %d", err);
+		}
+	}
+}
```
Comment (Thalley) [inline subsys/bluetooth/audio/mcs.c:853]: Should be able to do something like this for something a bit shorter. 

```suggestion
	if (len > maxlen) {
		char trunc_str[maxlen + 1];
		
		/* Truncation requires a null-terminated string */
		utf8_lcpy(trunc_str, str, maxlen);
		
		notify(uuid, (void *)trunc_str, strlen(trunc_str));
	} else {
		notify(uuid, (void *)str, len);
	}
}
```

File: subsys/bluetooth/audio/mcs.c [hunk 3]
```diff
@@ -817,7 +861,7 @@ void media_proxy_sctrl_track_changed_cb(void)
 void media_proxy_sctrl_track_title_cb(const char *title)
 {
 	BT_DBG("Notifying track title: %s", log_strdup(title));
-	notify(BT_UUID_MCS_TRACK_TITLE, title, strlen(title));
+	notify_string(BT_UUID_MCS_TRACK_TITLE, title);
```
Comment (Thalley) [inline subsys/bluetooth/audio/mcs.c:864]: What about media player name?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/mcs.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/audio/mcs.c:823]: I disagree. I think it should be up to the individual service determine if a notification should be truncated or not. 

Furthermore, as this PR also demonstrates, we may not always want to naively truncate e.g. UTF8 encoded strings either, as that would essentially send improperly encoded strings.

Comment (asbjornsabo) [reply subsys/bluetooth/audio/mcs.c:823]: I think Emil is correct.  What to do with notifications may be service-specific, and we do not want to put that kind of information into the stack.
- service-specific information does not belong in the general stack
- it is complicated to get it there - the notify would also have to include some kind of type information

In this case, what is truncated is track titles (later also player names), and those can well serve their purpose even if truncated - they will typically just be shown to the user.

File: subsys/bluetooth/audio/mcs.c (hunk 2 above)
Comment (asbjornsabo) [reply subsys/bluetooth/audio/mcs.c:853]: Much better - thanks!
I guess you mean "maxlen + 1" also in the utf8_lcpy - the termination does not go on the air.

File: subsys/bluetooth/audio/mcs.c (hunk 3 above)
Comment (asbjornsabo) [reply subsys/bluetooth/audio/mcs.c:864]: I added a comment here: https://github.com/zephyrproject-rtos/zephyr/issues/41189

Comment (asbjornsabo) [reply subsys/bluetooth/audio/mcs.c:864]: Group titles and segment names are kept in the object, not as characteristics.

**Comment by asbjornsabo** [comment]
Updated according to comments

File: subsys/bluetooth/audio/mcs.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/audio/mcs.c]: Good catch :)

File: subsys/bluetooth/audio/mcs.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/audio/mcs.c:851]: I'm not see the aforementioned comment in https://github.com/zephyrproject-rtos/zephyr/issues/41189 :)

> Group titles and segment names are kept in the object, not as characteristics.

Not sure how that relates to the media player name - Can you elaborate?

**Comment by stephanosio** [comment]
Pull request re-opened to fix stuck CI (due to GitHub mishap)

File: subsys/bluetooth/audio/mcs.c (hunk 3 above)
Comment (asbjornsabo) [reply subsys/bluetooth/audio/mcs.c:851]: 1) It is a note in the description, not a comment
2) No relation - they are other strings, and I just wanted to show that they are not relevant for this PR.

File: tests/bluetooth/bsim_bt/bsim_test_audio/prj.conf [hunk 4]
```diff
@@ -62,6 +62,7 @@ CONFIG_MCTL_LOCAL_PLAYER_LOCAL_CONTROL=y
 CONFIG_MCTL_LOCAL_PLAYER_REMOTE_CONTROL=y
 CONFIG_MCTL_REMOTE_PLAYER_CONTROL=y
 CONFIG_MCTL_REMOTE_PLAYER_CONTROL_OBJECTS=y
+CONFIG_UTF8=y
```
[the remark this answers is not in the document]
Comment (asbjornsabo) [reply tests/bluetooth/bsim_bt/bsim_test_audio/prj.conf:65]: The UTF8 library with the copy/truncate functions used above does not build without it:
`zephyr_sources_ifdef(CONFIG_UTF8 utf8.c)`

File: subsys/bluetooth/audio/mcs.c (hunk 2 above)
Comment (asbjornsabo) [reply subsys/bluetooth/audio/mcs.c]: `sizeof()` is better, yes.  Changed.

File: tests/bluetooth/bsim_bt/bsim_test_audio/prj.conf (hunk 4 above)
[the remark this answers is not in the document]
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_audio/prj.conf:65]: I know :) 

But then MCS does also not build without `CONFIG_UTF8` being enabled. Should `CONFIG_BT_MCS` then no either `depends on` or `select` `CONFIG_UTF8`?

[the remark this answers is not in the document]
Comment (asbjornsabo) [reply tests/bluetooth/bsim_bt/bsim_test_audio/prj.conf:65]: Ah - now I understand the question. Yes, that makes sense.
Added to the commit.

File: subsys/bluetooth/audio/mcs.c [hunk 5]
```diff
@@ -808,6 +809,37 @@ static void notify(const struct bt_uuid *uuid, const void *data, uint16_t len)
...
+	 * truncate the string to.  But the ATT_MTU is per connection, and MCS
+	 * is not connection-aware yet.
+	 * For now: Truncate according to the default ATT_MTU, so that
+	 * notifications will go through
+	 */
+
+	/* TODO: Use bt_gatt_get_mtu() to find the ATT_MTU */
+	const uint16_t att_mtu = 23;
+	const uint16_t maxlen = att_mtu - 1 - 2; /* Subtract opcode and handle */
+	const uint16_t len = strlen(str);
```
Comment (Thalley) [inline subsys/bluetooth/audio/mcs.c:829]: Consider 

```suggestion
	const size_t len = strlen(str);
```

**Review by Thalley — APPROVED** [review]

File: subsys/bluetooth/audio/mcs.c (hunk 1 above)
Comment (MariuszSkamra) [reply subsys/bluetooth/audio/mcs.c:823]: OK, you're correct

**Review by MariuszSkamra — APPROVED** [review]
