### PR TITLE
drivers: intc: plic: fix the calculation of trig register

### LINKED ISSUE #62563: drivers: intc: plic: erroneous calculation of trig register
The address calculation of the `trig` register in the `intc_plic` shouldn't depend on the `PLIC_MAX_PRIO`, specifying the correct address offset in the DT using `riscv,trigger-reg-offset` should be all it takes.

### PR DESCRIPTION
**Pull request by ycsin**
`trig` register should be independent of the `riscv,max-priority` property.

This register is mentioned in:
- [telink datasheet](http://wiki.telink-semi.cn/doc/ds/DS-TLSR9518-E_Datasheet%20for%20Telink%20Multi-Standard%20Wireless%20SoC%20TLSR9518.pdf#page=107&zoom=100,70,76)
- [andes datasheet](http://www.andestech.com/wp-content/uploads/AX45MP-1C-Rev.-5.0.0-Datasheet.pdf)

### CODE REVIEW

File: drivers/interrupt_controller/intc_plic.c [hunk 1]
```diff
@@ -29,7 +29,7 @@
 #define PLIC_IRQS        (CONFIG_NUM_IRQS - CONFIG_2ND_LVL_ISR_TBL_OFFSET)
 #define PLIC_EN_SIZE     ((PLIC_IRQS >> 5) + 1)
 
-#define PLIC_EDGE_TRIG_TYPE   (PLIC_MAX_PRIO + DT_INST_PROP(0, riscv_trigger_reg_offset))
+#define PLIC_EDGE_TRIG_TYPE   DT_INST_PROP(0, riscv_trigger_reg_offset)
```
Comment (cfriedt) [inline drivers/interrupt_controller/intc_plic.c:32]: After looking at it in detail, I wondered how this even passed CI in the first place, and it seems to be that there is zero test coverage at the moment.

Good in a way (nothing was broken), but also bad in a way (interrupt controller code should be thoroughly tested).

@ycsin - please file a bug report, because this will need a backport to v3.4-branch and also please fix `riscv_plic_is_edge_irq()` in `drivers/interrupt_controller/intc_plic.c`.

IIRC, the correct version of that would be something like this:
```cpp
static int riscv_plic_is_edge_irq(uint32_t irq)
{
	if (IS_ENABLED(CONFIG_PLIC_SUPPORTS_EDGE_IRQ)) {
		volatile uint32_t *trig = (volatile uint32_t *)PLIC_REG + PLIC_EDGE_TRIG_TYPE;

		trig += (irq >> PLIC_EDGE_TRIG_SHIFT);
		return *trig & BIT(irq);
	}
	return 0;
}
```

Comment (cfriedt) [reply drivers/interrupt_controller/intc_plic.c:32]: I think this is a great example of why PLIC should be multi-instance. With that, we can add it to a `build_all` test relatively easily and permute config options in `testcase.yaml`. But multi-instance should come later.

And, honestly, even for drivers that are never intended to be multi-instance, I always recommend that devs do so anyway in order to avoid hard-coding instance numbers in macros, use proper data encapsulation, etc.

**Review by cfriedt — DISMISSED** [review]
I'm just going to approve for now. If anyone else feels ready to approve, it can be merged, but we should get an issue filed for the bug too.

**Comment by ycsin** [comment]
> we should get an issue filed for the bug too.

Done - #62563

File: drivers/interrupt_controller/intc_plic.c (hunk 1 above)
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c:32]: > And, honestly, even for drivers that are never intended to be multi-instance, I always recommend that devs do so anyway in order to avoid hard-coding instance numbers in macros, use proper data encapsulation, etc.

+1

**Comment by ycsin** [comment]
Added a build_all test for the `intc_plic`

If `CONFIG_PLIC_SUPPORTS_EDGE_IRQ` not set:

```c
// drivers.interrupt_controller.intc_plic.build/zephyr/include/generated/devicetree_generated.h
#define DT_N_S_soc_S_interrupt_controller_c000000_P_riscv_trigger_reg_offset 4224
```

If `CONFIG_PLIC_SUPPORTS_EDGE_IRQ` set:

```c
// drivers.interrupt_controller.intc_plic.edge.build/zephyr/include/generated/devicetree_generated.h
#define DT_N_S_soc_S_interrupt_controller_c000000_P_riscv_trigger_reg_offset 201330816
```

**Review by cfriedt — DISMISSED** [review]

File: tests/drivers/build_all/interrupt_controller/src/main.c [hunk 2]
```diff
@@ -0,0 +1,10 @@
+/*
+ * Copyright (c) 2012-2014 Wind River Systems, Inc.
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+int main(void)
+{
+	return 0;
```
Comment (cfriedt) [inline tests/drivers/build_all/interrupt_controller/src/main.c:9]: Could maybe add `BUILD_ASSERT()`s here to evaluate against DT

Comment (ycsin) [reply tests/drivers/build_all/interrupt_controller/src/main.c:19]: added above

**Comment by carlocaione** [comment]
I'm confused by this property. It is supposedly an offset (and indeed we are using `DT_INST_PROP` to get that) but then we are using it as an absolute register value in https://github.com/zephyrproject-rtos/zephyr/blob/f6a9fc12025264f010eee4200bb4fd34a6a07e22/drivers/interrupt_controller/intc_plic.c#L56-L59
(even without using any IO helper) ?

File: drivers/interrupt_controller/intc_plic.c [hunk 3]
```diff
@@ -29,7 +29,7 @@
 #define PLIC_IRQS        (CONFIG_NUM_IRQS - CONFIG_2ND_LVL_ISR_TBL_OFFSET)
 #define PLIC_EN_SIZE     ((PLIC_IRQS >> 5) + 1)
 
-#define PLIC_EDGE_TRIG_TYPE   (PLIC_MAX_PRIO + DT_INST_PROP(0, riscv_trigger_reg_offset))
```
Comment (ycsin) [inline drivers/interrupt_controller/intc_plic.c:32]: Maybe this `PLIC_MAX_PRIOR` should have been the base address instead?

Comment (cfriedt) [reply drivers/interrupt_controller/intc_plic.c:32]: http://www.andestech.com/wp-content/uploads/AX45MP-1C-Rev.-5.0.0-Datasheet.pdf

Looks like it's something like
`trig = base + n * sizeof(uint32_t) + n / BITS_PER_BYTE`, where `n = NHPOT(num_irqs)`.

Comment (cfriedt) [reply drivers/interrupt_controller/intc_plic.c:32]: Trigger configuration is mentioned in the PLIC spec, but it looks like the offset was omitted from the memory map.

https://github.com/riscv/riscv-plic-spec/blob/master/riscv-plic.adoc#memory-map

Comment (cfriedt) [reply drivers/interrupt_controller/intc_plic.c:32]: > Looks like it's something like `trig = base + n * sizeof(uint32_t) + n / BITS_PER_BYTE`, where `n = NHPOT(num_irqs)`.

I think my assumption about the offsets being based on the number of routed interrupts was wrong. E.g. https://bit.ly/3r5PDS4 only incorporates 63 of the possible 1023 and still uses an offset of 0x1080 (which makes sense in a lot of ways).

File: tests/drivers/build_all/interrupt_controller/boards/qemu_riscv32_trig.overlay [hunk 4]
```diff
@@ -0,0 +1,9 @@
+// SPDX-License-Identifier: Apache-2.0
+
+ /{
+	soc {
+		plic: interrupt-controller@c000000 {
+			riscv,trigger-reg-offset = < 0x0c001080 >;
```
Comment (ycsin) [inline tests/drivers/build_all/interrupt_controller/boards/qemu_riscv32_trig.overlay:6]:
```suggestion
			riscv,trigger-reg-offset = < 0x00001080 >;
```

**Comment by cfriedt** [comment]
> (even without using any IO helper) ?

Yep, better to use `sys_read32()` and `sys_write32()` to access the particular trigger register.

**Comment by cfriedt** [comment]
@carlocaione - @ycsin mentioned to me that the majority of the "best practice" code will be separate. This should be OK for now in order to provide a technically correct (albeit not ideal) implementation.

I think it's probably safe to merge, if it unblocks either #62481 or #62442, but we should review those with some scrutiny and agree on a solid approach.

**Review by cfriedt — APPROVED** [review]

**Review by carlocaione — APPROVED** [review]
