### PR TITLE
bluetooth: mesh: fix static oob auth padding

### LINKED ISSUE #52169: Mesh provisioning static OOB incorrect zero padding
https://github.com/zephyrproject-rtos/zephyr/blob/f98a240537f34da826f4dc6eb95f63b4e8bb845b/subsys/bluetooth/mesh/prov_device.c#L162

`
if (atomic_test_bit(bt_mesh_prov_link.flags, OOB_STATIC_KEY)) {
		memcpy(bt_mesh_prov_link.auth + 16 - bt_mesh_prov->static_val_len,
		       bt_mesh_prov->static_val, bt_mesh_prov->static_val_len);
		(void)memset(bt_mesh_prov_link.auth, 0,
			     sizeof(bt_mesh_prov_link.auth) - bt_mesh_prov->static_val_len);
	}
`

It appears the auth field for staticOOB has incorrect zero-padding. Per MeshPrf sec 5.4.2.4 a binary value 
shall be padded with zeros **after** the (variable length) array of octets, ie format shall be same as for alphanumeric string. 
Code currently follows numeric format where zeros are pre-pended.

### PR DESCRIPTION
**Pull request by m-alperen-sener**
The remaining bit should be zero if auth is shorter than PROV_AUTH_MAX_LEN and it should be trimmed by removing octets with indexes higher than PROV_AUTH_MAX_LEN.

### CODE REVIEW

File: subsys/bluetooth/mesh/provisioner.c [hunk 1]
```diff
@@ -751,17 +751,16 @@ int bt_mesh_auth_method_set_output(bt_mesh_output_action_t action, uint8_t size)
...
 	}
 
 	prov_set_method(AUTH_METHOD_STATIC, 0, 0);
 
-	memcpy(bt_mesh_prov_link.auth + tail_size, static_val,
-	       tail_size ? size : PROV_AUTH_MAX_LEN);
-	memset(bt_mesh_prov_link.auth, 0, tail_size);
+	memset(bt_mesh_prov_link.auth, 0, PROV_AUTH_MAX_LEN);
+	/* Trim the Auth if it is longer than required length */
+	memcpy(bt_mesh_prov_link.auth, static_val,
```
Comment (alxelax) [inline subsys/bluetooth/mesh/provisioner.c:762]: Wrong zero padding.

**Review by alxelax — CHANGES_REQUESTED** [review]
Wrong padding in general. Please take a look at spec. Binary Data for Authentication description. 
Also, I didn't get what was wrong in the previous implementation. Could you point why it doesn't work?

File: subsys/bluetooth/mesh/provisioner.c (hunk 1 above)
Comment (m-alperen-sener) [reply subsys/bluetooth/mesh/provisioner.c:762]: if we take the example in document:
--------------------------
lets:
PROV_AUTH_MAX_LEN=16
static_auth = [0x12, 0x34, 0x56]
size = 3

what used to happen
------------------------
with `tail_size = 13 // 16 - 3`
after
`memcpy(bt_mesh_prov_link.auth + tail_size, static_val, tail_size ? size : PROV_AUTH_MAX_LEN);`
bt_mesh_prov_link.auth = [X, X, X, X, X, X, X, X, X, X, X, X, X, X, 0x12, 0x34, 0x56]

and then
`memset(bt_mesh_prov_link.auth, 0, tail_size);`
bt_mesh_prov_link.auth = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x12, 0x34, 0x56]

So it works only if the size = PROV_AUTH_MAX_LEN since there is no padding

with the change:
----------------------
`memset(bt_mesh_prov_link.auth, 0, PROV_AUTH_MAX_LEN);` zero all values since we end up padding it with zeros anyway.
`memcpy(bt_mesh_prov_link.auth, static_val, size > PROV_AUTH_MAX_LEN ? PROV_AUTH_MAX_LEN : size);`
bt_mesh_prov_link.auth = [0x12, 0x34, 0x56, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

another case:
static_auth = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
size = 20
bt_mesh_prov_link.auth = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

Comment (alxelax) [reply subsys/bluetooth/mesh/provisioner.c:762]: > ## if we take the example in document:
> lets: PROV_AUTH_MAX_LEN=16 static_auth = [0x12, 0x34, 0x56] size = 3
> 
> ## what used to happen
> with `tail_size = 13 // 16 - 3` after `memcpy(bt_mesh_prov_link.auth + tail_size, static_val, tail_size ? size : PROV_AUTH_MAX_LEN);` bt_mesh_prov_link.auth = [X, X, X, X, X, X, X, X, X, X, X, X, X, X, 0x12, 0x34, 0x56]
> 
> and then `memset(bt_mesh_prov_link.auth, 0, tail_size);` bt_mesh_prov_link.auth = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x12, 0x34, 0x56]
> 

Isn't this how specification mandates?

> So it works only if the size = PROV_AUTH_MAX_LEN since there is no padding
> 

Didn't get this. What is changed if size 15, 14 etc to 1? 

> ## with the change:
> `memset(bt_mesh_prov_link.auth, 0, PROV_AUTH_MAX_LEN);` zero all values since we end up padding it with zeros anyway. `memcpy(bt_mesh_prov_link.auth, static_val, size > PROV_AUTH_MAX_LEN ? PROV_AUTH_MAX_LEN : size);` bt_mesh_prov_link.auth = [0x12, 0x34, 0x56, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
> 

Please take a look at specification 5.4.2.4 Authentication(especially samples). You did it in the opposite manner to what the specification says.

> another case: static_auth = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19] size = 20 bt_mesh_prov_link.auth = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

I'm pretty sure the current implementation does everything correctly. Oppositely, this PR breaks OOB static authentication completely.

Comment (alxelax) [reply subsys/bluetooth/mesh/provisioner.c:762]: Seems, @m-alperen-sener, you are right. It was already reported here once: https://github.com/zephyrproject-rtos/zephyr/issues/52169 and fixed here: https://github.com/zephyrproject-rtos/zephyr/pull/52255
but in some moment all these changes have been lost. Probably during Mesh-1.1 merge.

Comment (alxelax) [reply subsys/bluetooth/mesh/provisioner.c:762]: I guess, it is better to apply my previous changes first and then add your modifications. The current changes in the worst case make a copy up to 64 bytes (considering initial zeroing). 
In my previous PR, I refused it.

**Review by PavelVPV — APPROVED** [review]

**Review by alxelax — APPROVED** [review]
