### PR TITLE
drivers: dma: stm32u5: check stream busyness in dma_suspend

### LINKED ISSUE #103042: uart_stm32_async_tx_abort getting stuck when calling uart_tx_abort (due to race?)
### Describe the bug

When calling `uart_tx_abort` API with stm32u5 MCU, the call might get stuck forever into loop in `dma_stm32_suspend` waiting `SUSP` flag to be set. This one:

https://github.com/zephyrproject-rtos/zephyr/blob/935373e9186139f326bf07865f17d3925049a173/drivers/dma/dma_stm32u5.c#L660-L662

Backtrace:

Image

My application does the following:

1. In its own task, data is sent periodically using UART async API.
2. Other task sends message to the communication task asking communication to stop. The communication task then calls `uart_tx_abort` unconditionally to stop the current transfer.

Usually this works fine, but when this is repeated hundreds of times, then sometimes `dma_suspend` does not exit.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Intermittent – Occurs occasionally; hard to reproduce.

### Environment

Zephyr 4.3,
SDK 0.17.4,
stm32u585 based custom board.

### Additional Context

AI explanation (no guarantees of quality of it) is that this is due to a race situation. When DMA is idle just after completing tx, then writing the suspend register does not set the suspend flag:

Image

AI suggested fix is to remove the dma_suspend call completely:

Image

I tried that, and the function does not get into stuck anymore. I've been running the code for 12 hours without problems.

### PR DESCRIPTION
**Pull request by mkaranki**
Add additional business check to waiting SUSPF to be set so
that the loop cannot be executed forever when the dma stream
is idle.

When the stream is not busy, then there is nothing to suspend.
However, if suspend was attempted for an idle stream, then the
changed loop waited forever SUSPF to be set. This could have
happened at least when serial api tx_abort() is called with
stm32u5 and tx dma transfer becoming ready about the same time
the tx_abort() API is called.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/103042

### CODE REVIEW

**Review by djiatsaf-st — APPROVED** [review]

File: drivers/dma/dma_stm32u5.c [hunk 1]
```diff
@@ -659,7 +660,8 @@ static int dma_stm32_suspend(const struct device *dev, uint32_t id)
 	/* It's not enough to wait for the SUSPF bit with LL_DMA_IsActiveFlag_SUSP */
 	do {
 		k_busy_wait(800); /* A delay is needed (800us is valid) */
-	} while (LL_DMA_IsActiveFlag_SUSP(dma, dma_stm32_id_to_stream(id)) != 1);
+	} while (LL_DMA_IsActiveFlag_SUSP(dma, dma_stm32_id_to_stream(id)) != 1 &&
+			stream->busy == true);
```
Comment (mathieuchopstm) [inline drivers/dma/dma_stm32u5.c:664]: Wouldn't the following make more sense:
```c
if (stream->busy) {
    LL_DMA_SuspendChannel(dma, ...);
    do {
      ...
    } while (LL_DMA_IsActiveFlag_SUSP(...) != 1);
}

return 0;
```

Comment (mkaranki) [reply drivers/dma/dma_stm32u5.c:664]: > Wouldn't the following make more sense:
> 
> ```c
> if (stream->busy) {
>     LL_DMA_SuspendChannel(dma, ...);
>     do {
>       ...
>     } while (LL_DMA_IsActiveFlag_SUSP(...) != 1);
> }
> 
> return 0;
> ```
In my opinion no. `busy` flag (and dma channel state) might change by interrupt handler as no interrupts are disabled. If it is checked only once, there is a change that the interrupt happens just after checking it, and then we're in the same situation: trying to suspend an idle DMA channel and ending up into forever loop.

**Review by mathieuchopstm — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
