### PR TITLE
test: Relocate posix mqueue receive buffer

### LINKED ISSUE #60796: tests/posix/common/portability.posix.common.picolibc failing on MTL
**Describe the bug**
The following output has been observed ...

```
===================================================================
START - test_posix_mqueue
Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/mqueue.c:55: receiver_thread: (strcmp(rec_data, send_data) is true)
Error in data reception
FAIL - test_posix_mqueue in 0.002 seconds

```
Please also mention any information which could help others to understand
board: intel_adsp_ace15_mtpm

**Expected behavior**
There should not be any assertion failure.

### PR DESCRIPTION
**Pull request by peter-mitsis**
For platforms that select Kconfig option CONFIG_KERNEL_COHERENCE,
the receive buffer used in mq_timedreceive() must not be on the
stack. This is because the k_msgq that underlies the POSIX mqueue
will attempt to perform a direct to buffer copy from the sender
when there is a waiting reader.

Fixes #60796

### CODE REVIEW

**Comment by keith-packard** [comment]
This seems like a fairly significant semantic change to this API; can you explain in more detail why this particular platform doesn't allow cross-thread data copying?

**Comment by peter-mitsis** [comment]
@keith-packard Others can probably explain this better than I, but I shall attempt to give it a shot. Xtensa (or at the very least the Xtensa intel_adsp_xxx boards) is a cache incoherent architecture (see Kconfig option KERNEL_COHERENCE for a little more info). Why this particular design decision was made--I do not know.  But I do know that the thread stacks are in incoherent memory. The implication is that should one CPU update the contents of a thread's stack, then other CPUs are not guaranteed to see that change. For the test case that was failing, the intel_adsp_ace15_mtpm board had 3 CPUs--enough for both the sender and receiver threads to be executing simultaneously.

**Comment by keith-packard** [comment]
> @keith-packard Others can probably explain this better than I, but I shall attempt to give it a shot. Xtensa (or at the very least the Xtensa intel_adsp_xxx boards) is a cache incoherent architecture (see Kconfig option KERNEL_COHERENCE for a little more info). Why this particular design decision was made--I do not know. But I do know that the thread stacks are in incoherent memory. The implication is that should one CPU update the contents of a thread's stack, then other CPUs are not guaranteed to see that change. For the test case that was failing, the intel_adsp_ace15_mtpm board had 3 CPUs--enough for both the sender and receiver threads to be executing simultaneously.

Ok, the docs for `KERNEL_COHERENCE` say that stack-based parameters are not valid in this case. I'd suggest updating the commit message to reference that variable and associated documentation so its clear that the ABI difference is documented.

**Review by cfriedt — DISMISSED** [review]
cool - I'd like to avoid arch-specific workarounds if possible, but this is benign.

File: tests/posix/common/src/mqueue.c [hunk 1]
```diff
@@ -22,6 +22,7 @@ K_THREAD_STACK_ARRAY_DEFINE(stacks, N_THR, STACKSZ);
 
 char queue[16] = "server";
 char send_data[MESSAGE_SIZE] = "timed data send";
+char rec_data[MESSAGE_SIZE];
```
Comment (cfriedt) [inline tests/posix/common/src/mqueue.c:25]: > Ok, the docs for `KERNEL_COHERENCE` say that stack-based parameters are not valid in this case. I'd suggest updating the commit message to reference that variable and associated documentation so its clear that the ABI difference is documented.

If a respin happens, it might be good to add a 1-line comment referring to `KERNEL_COHERENCE` above this line for reference, and maybe mention that this could also be placed in stack memory if coherent memories are not required.

**Comment by peter-mitsis** [comment]
As recommended, I updated both the commit message and added a comment to precede the definition of the buffer `rec_data`.

File: tests/posix/common/src/mqueue.c (hunk 1 above)
Comment (keith-packard) [reply tests/posix/common/src/mqueue.c:34]: Looks great, thanks!

**Review by keith-packard — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
