### PR TITLE
net: coap: Parse option no longer crashes with no options to parse

### LINKED ISSUE #34463: LwM2M bootstrap DELETE operation not working
**Describe the bug**
When connecting to a bootstrap server which sends an empty DELETE frame, the LwM2M client responds with a [`COAP_RESPONSE_CODE_INTERNAL_ERROR`](https://github.com/zephyrproject-rtos/zephyr/blob/084a8b6bf4ca3c64bddc5b0c18f959352269c849/subsys/net/lib/lwm2m/lwm2m_engine.c#L3988). 

image
image

I believe that the handling for this case is actually [already supported in Zephyr](https://github.com/zephyrproject-rtos/zephyr/blob/084a8b6bf4ca3c64bddc5b0c18f959352269c849/subsys/net/lib/lwm2m/lwm2m_engine.c#L3930):
```
		case LWM2M_OP_DELETE:
#if defined(CONFIG_LWM2M_RD_CLIENT_SUPPORT_BOOTSTRAP)
			if (msg->ctx->bootstrap_mode) {
				r = bootstrap_delete(msg);
				break;
			}
#endif
			r = lwm2m_delete_handler(msg);
			break;
```
and this notion in [`bootstrap_delete()`](https://github.com/zephyrproject-rtos/zephyr/blob/084a8b6bf4ca3c64bddc5b0c18f959352269c849/subsys/net/lib/lwm2m/lwm2m_engine.c#L3578), compliant with the [LwM2M spec](http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf):
```
	/* DELETE all instances of a specific object or all object instances if
	 * not specified, excluding the following exceptions (according to the
	 * LwM2M specification v1.0.2, ch 5.2.7.5):
	 * - LwM2M Bootstrap-Server Account (Bootstrap Security object, ID 0)
	 * - Device object (ID 3)
	 */
```

However, the code is not reaching this handler for this CoAP DELETE message. It is breaking [here already](https://github.com/zephyrproject-rtos/zephyr/blob/084a8b6bf4ca3c64bddc5b0c18f959352269c849/subsys/net/lib/lwm2m/lwm2m_engine.c#L3646):
```
	r = coap_find_options(msg->in.in_cpkt, COAP_OPTION_URI_PATH, options,
			      ARRAY_SIZE(options));
	if (r < 0) {
		goto error;
	}
```

I don't mind being assigned this issue, I will probably push a Pull Request by friday.
However, I would like some input on this issue so that I can solve it neatly.

**To Reproduce**
1. Zephyr LwM2M client
2. Connect to a Bootstrap Server
3. Bootstrap server sends DELETE

**Expected behavior**
Behavior according to the [LwM2M spec](http://www.openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf), as also already noted in [`bootstrap_delete()`](https://github.com/zephyrproject-rtos/zephyr/blob/084a8b6bf4ca3c64bddc5b0c18f959352269c849/subsys/net/lib/lwm2m/lwm2m_engine.c#L3578).

**Impact**
Showstopper for communication with specific LwM2M services, like that of IoTerop.

### PR DESCRIPTION
**Pull request by MaikVermeulen**
parse_option() now first checks if there is actual data to parse,
returning 0 if there is none.

Fixes #34463.

Signed-off-by: Maik Vermeulen <maik.vermeulen@innotractor.com>

### CODE REVIEW

File: subsys/net/lib/coap/coap.c [hunk 1]
```diff
@@ -454,6 +454,11 @@ static int parse_option(uint8_t *data, uint16_t offset, uint16_t *pos,
...
 	int r;
 
+	/* Check if there are options to parse */
+	if (offset == max_len) {
+		return 0;
+	}
+
 	r = read_u8(data, offset, pos, max_len, &opt);
 	if (r < 0) {
 		return r;
```
Comment (mniestroj) [inline subsys/net/lib/coap/coap.c:464]: Actually this `read_u8()` should return `r == -EINVAL` when `offset == max_len`, in which case you can do `return 0;` instead of `return r;`. 

**But**, I don't think `parse_option()` should return 0 in case of **no parsed** message. Simply you no longer can distinguish between:
1) `parse_option()` that parsed option successfully and reached end of buffer (max_len),
2) `parse_option()` did not parse any option, because we were already at the end of buffer (offset == max_len).

So I think it is `coap_packet_parse()` and/or `coap_packet_parse()` that should be "fixed".

**Review by mniestroj — CHANGES_REQUESTED** [review]

File: subsys/net/lib/coap/coap.c (hunk 1 above)
Comment (MaikVermeulen) [reply subsys/net/lib/coap/coap.c:464]: I agree, `parse_option()` shouldn't be called when there is no payload to be parsed.
Upon further investigation of `coap_packet_parse()` and `coap_find_options()`, it seems that [`coap_packet_parse()` is actually already checking for this](https://github.com/zephyrproject-rtos/zephyr/blob/cfe0849072c81c1314f733babcc9a87340c5d595/subsys/net/lib/coap/coap.c#L592). `coap_find_options()`, does not. Please see my new commit.

File: subsys/net/lib/coap/coap.c [hunk 2]
```diff
@@ -621,6 +626,11 @@ int coap_packet_parse(struct coap_packet *cpkt, uint8_t *data, uint16_t len,
 int coap_find_options(const struct coap_packet *cpkt, uint16_t code,
 		      struct coap_option *options, uint16_t veclen)
 {
+	/* Check if there are options to parse */
+	if (cpkt->hdr_len == cpkt->max_len) {
+		return 0;
+	}
+
 	uint16_t opt_len;
```
Comment (rlubos) [inline subsys/net/lib/coap/coap.c:634]: Please keep the variable definitions on top.

File: subsys/net/lib/coap/coap.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/lib/coap/coap.c:464]: To be honest I already see some ambiguity in the `parse_option()` function and how `coap_find_options()` uses it. Correct me if I'm wrong (I've not run any tests, just analyzed the code) but consider two scenarios:
1. The packet being parsed have a set of options and no payload - an option is parsed on each iteration, on the final call the last option is parsed and `0` is returned.
2.  The packet being parsed have a set of options and a payload - an option is parsed on each iteration but the last one, on the final call the payload marker is detected and 0 returned, no option was parsed. If you look at the [`coap_find_options()`](https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/lib/coap/coap.c#L643) implementation, the option value is being checked anyway, which would hold some rubbish from the function perspective (well, whatever the `options` struct was initialized with).

I guess it's not something to be addressed in this PR (the change in `coap_find_options` looks fine for the issue reported) but we should likely leave an issue for this (if I'm correct of course).

File: subsys/net/lib/coap/coap.c [hunk 3]
```diff
@@ -454,6 +454,11 @@ static int parse_option(uint8_t *data, uint16_t offset, uint16_t *pos,
 	uint8_t opt;
 	int r;
 
+	/* Check if there are options to parse */
+	if (offset == max_len) {
```
Comment (rlubos) [inline subsys/net/lib/coap/coap.c:458]: Should we drop this change from the PR then?

File: subsys/net/lib/coap/coap.c (hunk 1 above)
Comment (MaikVermeulen) [reply subsys/net/lib/coap/coap.c]: > I guess it's not something to be addressed in this PR (the change in `coap_find_options` looks fine for the issue reported) but we should likely leave an issue for this (if I'm correct of course).

Doesn't the added check in this PR solve that second scenario? Unfortunately I can't budget more time for this at this moment. But I think the PR should indeed be fine for now.

Comment (rlubos) [reply subsys/net/lib/coap/coap.c]: I don't think so, the change in the PR fixes the case when there is no option/payload at all. The second scenario is about having both, options and payload in the packet. But yes, the PR looks good to me with regards to the issue it addresses.

**Review by rlubos — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
