### PR TITLE
samples: flash_shell: Fix overwriting return value

### LINKED ISSUE #27641: [Coverity CID :212142] Unused value in samples/drivers/flash_shell/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/66bd06a7d1f9e4682faafbc551046af695fa1060/samples/drivers/flash_shell/src/main.c#L368

Category: Code maintainability issues
Function: `do_write_unaligned`
Component: Samples
CID: [212142](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=212142)

Details:

```
362                          page_size);
363             }
364         }
365    
366         if (read_back) {
367             PR_SHELL(shell, "Reading back written bytes:\n");
>>>     CID 212142:  Code maintainability issues  (UNUSED_VALUE)
>>>     Assigning value from "do_read(shell, offset, len)" to "ret" here, but that stored value is overwritten before it can be used.
368             ret = do_read(shell, offset, len);
369         }
370    
371     free_buffers:
372         k_free(before_data);
373         k_free(after_data);
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #27642: [Coverity CID :212143] Unused value in samples/drivers/flash_shell/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/66bd06a7d1f9e4682faafbc551046af695fa1060/samples/drivers/flash_shell/src/main.c#L290

Category: Code maintainability issues
Function: `do_write_unaligned`
Component: Samples
CID: [212143](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=212143)

Details:

```
284    
285         before_data = k_malloc(page_size);
286         after_data = k_malloc(page_size);
287    
288         if (!before_data || !after_data) {
289             PR_ERROR(shell, "No heap memory for flash manipulation\n");
>>>     CID 212143:  Code maintainability issues  (UNUSED_VALUE)
>>>     Assigning value "-12" to "ret" here, but that stored value is overwritten before it can be used.
290             ret = -ENOMEM;
291             goto free_buffers;
292         }
293    
294         /* Stash useful data from the pages that will be affected. */
295         if (single_page_write) {
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by de-nordic**
Value of ret has been overwritten by flash_write_protection_set
before it could be returned from do_write_unaligned, which could
lead to reporting success when error code should have been returned.

Fixes zephyrproject-rtos#27641, Coverity-CID: 212142
Fixes zephyrproject-rtos#27642, Coverity-CID: 212143

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

File: samples/drivers/flash_shell/src/main.c [hunk 1]
```diff
@@ -372,11 +372,11 @@ static int do_write_unaligned(const struct shell *shell, off_t offset, uint8_t *
...
 
-	ret = flash_write_protection_set(flash_device, true);
-	if (ret) {
+	int ret1 = flash_write_protection_set(flash_device, true);
+	if (ret1) {
 		PR_ERROR(shell, "Failed to enable flash protection (err: %d)."
-				"\n", ret);
-		return ret;
+				"\n", ret1);
+		return ret1;
```
Comment (ceolin) [inline samples/drivers/flash_shell/src/main.c:379]: it seems that the error is meaningless, I mean, the check is just for something != 0. So you could re-use the variable `ret` and return a negative value later, another thing is that we don't declare variables ad-hoc. Though the fix is correct and avoid possible return 0 in case of error.

**Review by ceolin — APPROVED** [review]
