### PR TITLE
usb: device_next: respect bMaxPacketSize0 in control transfers

### LINKED ISSUE #79194: Function usbd_ep_ctrl_set_zlp() works incorrect for devices with MPS != 64
**Describe the bug**
For devices that have *EP0 MPS < 64* function `usbd_ep_ctrl_set_zlp()` will not
set zlp bit when all data was already sent and ZLP is required by host.

```c
static void usbd_ep_ctrl_set_zlp(struct usbd_context *const uds_ctx,
				 struct net_buf *const buf)
   ...
	if (setup->wLength > min_len && !(min_len % USB_CONTROL_EP_MPS)) { // !! Offending line
```
Definition of USB_CONTROL_EP_MPS is hardcoded this way
```c
#define USB_CONTROL_EP_MPS		64U
```

This was discovered during implementation #79184 of UDC driver for Smartbond #74662 .

Sample `samples/subsys/usb/mass` that triggers error since it generates 32 bytes long
descriptor.

It can also be triggered if other descriptors (like string descriptors) have length `8 * n`.

I think it can be also tested on other boards if MPS is artificially change to be 8 (this scenario was
tested on previous USB stack on STM32 devices that are capable to be configured
with EP0 MPS < 64.

**To Reproduce**

```sh
west build -b da1469x_dk_pro samples/subsys/usb/mass -DEXTRA_DTC_OVERLAY_FILE="ramdisk.overlay" -DCONFIG_APP_MSC_STORAGE_RAM=y -DCONF_FILE="usbd_next_prj.conf"
```

**Impact**

Devices with EP0 MPS < 64 will not work (This applies to Smartbond and some other device)

**Environment:**

 - OS: any
 - Commit SHA or Version used: 2815b6d710ad9c7ba25725ae34c402fc9153c427

### PR DESCRIPTION
**Pull request by jfischer-no**
Only the device operating at high speed has bMaxPacketSize0 set to 64
bytes, the device operating at other speeds may have a different value.
For full speed, use the value from the full speed descriptor.

Fixes: #79194

### CODE REVIEW

**Comment by kasjer** [comment]
Verified on Smartbond to work as advertised

File: subsys/usb/device_next/usbd_endpoint.c [hunk 1]
```diff
@@ -59,7 +59,20 @@ static void usbd_ep_ctrl_set_zlp(struct usbd_context *const uds_ctx,
 				 struct net_buf *const buf)
 {
 	struct usb_setup_packet *setup = usbd_get_setup_pkt(uds_ctx);
+	struct usb_device_descriptor *desc = uds_ctx->fs_desc;
 	size_t min_len = MIN(setup->wLength, buf->len);
+	uint8_t mps0 = 0;
```
Comment (tmon-nordic) [inline subsys/usb/device_next/usbd_endpoint.c:64]: Initializing to 0 leads to taking remainder from division by zero later on. This would only trigger in the asserts-disabled case. Not sure if it would be better to just default to `USB_CONTROL_EP_MPS` instead of `0` here.

**Review by tmon-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
