### PR TITLE
drivers: spi_nrfx_spim: Fixes related to 32 Mbps speed on nRF5340

### LINKED ISSUE #37221: nRF5340: SPIM4 invalid clock frequency selection
**Describe the bug**

The `spi_nrfx_spim` driver will set an invalid clock frequency on SPIM4 when a slave DTS binding supports a >=32MHz clock rate.
The nRF5340 only supports 32Mbps when the application core is running at 128Mhz, but this is not checked.

Clock rate selection is currently performed via the existence of the `SPIM_FREQUENCY_FREQUENCY_M32` define (Which does exist on nRF5340) and the value of `SPIM{X}_MAX_FREQUENCY`, which for SPIM4 is defined to 32.

**Expected behavior**

The SPI master should not configure itself into an invalid configuration.
The driver needs to take the current CPU clock rate into account when selecting the maximum SPI clock rate.

**Impact**

Board `.dts` files must manually limit affected peripherals to a bit rate of 16Mbps.

**Additional Context**

The datasheet specifies that the standard maximum bitrate is 16Mbps, but the HAL defines specify 8Mbps for SPI0-3.

### PR DESCRIPTION
**Pull request by anangl**
According to the nRF5340 PS, SPIM4 only supports 32 Mbps when the application core is running at 128 MHz. Drive configuration H0H1 must also be used for its pins for this speed.

Fixes #37221.

### CODE REVIEW

File: drivers/spi/spi_nrfx_spim.c [hunk 1]
```diff
@@ -143,14 +146,52 @@ static int configure(const struct device *dev,
...
-	freq = get_nrf_spim_frequency(MIN(spi_cfg->frequency,
-					  get_dev_config(dev)->max_freq));
+	spim_frequency = get_nrf_spim_frequency(MIN(spi_cfg->frequency,
+						    max_freq));
+
+#if defined(CONFIG_SOC_NRF5340_CPUAPP)
+	/* For 32 Mbps speed on nRF5340, drive configuration H0H1 must be used
+	 * (see the Pin assignments section in the nRF5340 PS).
+	 */
+	nrf_gpio_pin_drive_t drive = (spim_frequency == NRF_SPIM_FREQ_32M)
```
Comment (lairdjm) [inline drivers/spi/spi_nrfx_spim.c:167]: What if someone wants to use H1H0 on slower speeds?

**Review by nika-nordic — APPROVED** [review]

**Review by JordanYates — APPROVED** [review]

File: drivers/spi/spi_nrfx_spim.c (hunk 1 above)
Comment (JordanYates) [reply drivers/spi/spi_nrfx_spim.c:167]: I do have this open #34854, but it may need to be updated to do the init at this location instead of at driver init.

Comment (anangl) [reply drivers/spi/spi_nrfx_spim.c:167]: > What if someone wants to use H1H0 on slower speeds?

It is not supported now by the driver, so I actually don't know what I could do about it in this PR. Do you have any suggestion?

Comment (JordanYates) [inline drivers/spi/spi_nrfx_spim.c:167]: Just realised that the HAL drivers already perform this configuration in `nrfx_spim_init`

**Review by JordanYates — CHANGES_REQUESTED** [review]

**Comment by anangl** [comment]
Rebased.

File: drivers/spi/spi_nrfx_spim.c (hunk 1 above)
Comment (anangl) [reply drivers/spi/spi_nrfx_spim.c]: I'm sorry that it took me so long to get back to this one. I reworked the PR to take advantage of the pin configuration performed by the nrfx driver. Please take a look once again.

**Comment by carlescufi** [comment]
@gmarull can you approve if happy please?

File: drivers/spi/spi_nrfx_spim.c [hunk 2]
```diff
@@ -346,13 +339,14 @@ static int spim_nrfx_pm_control(const struct device *dev,
 
 	switch (action) {
 	case PM_DEVICE_ACTION_RESUME:
-		ret = init_spim(dev);
-		/* Force reconfiguration before next transfer */
-		data->ctx.config = NULL;
+		/* No action needed at this point, nrfx_spim_init() will be
+		 * called at configuration before the next transfer.
+		 */
```
Comment (gmarull) [inline drivers/spi/spi_nrfx_spim.c:344]: PM hooks are no longer doing what is expected, ie, put the device into operational state when resume is called. Why is this change required?

File: drivers/spi/spi_nrfx_spi.c [hunk 3]
```diff
@@ -286,13 +282,14 @@ static int spi_nrfx_pm_control(const struct device *dev,
 
 	switch (action) {
 	case PM_DEVICE_ACTION_RESUME:
-		ret = init_spi(dev);
-		/* Force reconfiguration before next transfer */
-		data->ctx.config = NULL;
+		/* No action needed at this point, nrfx_spi_init() will be
+		 * called at configuration before the next transfer.
+		 */
```
Comment (gmarull) [inline drivers/spi/spi_nrfx_spi.c:287]: same as previous comment

**Review by gmarull — COMMENTED** [review]
I only have one comment regarding PM.

File: drivers/spi/spi_nrfx_spim.c (hunk 2 above)
Comment (anangl) [reply drivers/spi/spi_nrfx_spim.c:344]: Previously, when resume was called, the device was brought to the state it was right after its initialization - it still needed to be reconfigured before the next transfer:
https://github.com/zephyrproject-rtos/zephyr/blob/7ccc1a41bc4c27c73bb03f01ed6b05491ba5872d/drivers/spi/spi_nrfx_spim.c#L336-L338
(at the device initialization, the nrfx driver was initialized with a default configuration, which was then altered accordingly when a transfer was requested). Now the difference is that the initialization of the device does not include the initialization of the nrfx driver - this is done when the device is configured right before a transfer is performed (only then we know the frequency, SPI mode, etc. that should be used), so there is no point in calling `nrfx_spim_init()` here and then, right before the next transfer, calling `nrfx_spim_uninit()` in order to be able to call `nrfx_spim_init()` again.
Alternatively, I would need to store the currently used nrfx driver configuration to be able to use it here in the call to `nrfx_spim_init()`. Then it would be not needed to reconfigure the device before the next transfer, provided it would be requested with the same configuration. But I'm not sure if it is worth spending more RAM just to achieve this possibility.

**Review by nika-nordic — APPROVED** [review]

**Comment by carlescufi** [comment]
@JordanYates please take another look

**Review by JordanYates — APPROVED** [review]
