### PR TITLE
Bluetooth: Controller: Implement bt_hci_driver::close

### LINKED ISSUE #3192: Shutting down BLE support
**_Reported by Geoff Gustafson:_**

Sorry if there's already been a request for this, I couldn't find it.

**Use case 1:**
I'd hope it would be possible to have a bt_disable function? For a single application, the use could be to be able to shut down the radio and everything and only occasionally turn it on when a user interacts with the device, or for a nightly sync or something. It seems that could save a lot of power?

In ZJS, we have an off-the-beaten path reason. We support loading different JavaScript apps sequentially with our "ashell" environment. So we prefer to cleanly release all resources / hardware we connected to in one application before starting the next. If one app used BT and the next didn't, we'd like to turn it off, and then turn it back on again if needed for another app. This is useful for development purposes.

Maybe this is nuts and we should just reboot in this case. :) I guess obviously it would add overhead.

(Imported from Jira ZEP-1741)

**Use case 2:**
I'm trying to find a way to turn off/disable bt functionality(i.e. like bt_disbale) and restart it later on, but it looks like no such of API has been provided. Any hints will be appreciated.

To Reproduce

Call bt_enable
Turn off hci controller
Power on hci controller
Trying to enable and use bt again
See error
In our case, we have a host and a controller, both of them are running zephyr with HCI H:4 and we want to cut off power of controller to save power sometime, then enable it again when needed. Then we found that we can't use any bt functionalities after re-powered HCI controller.

### PR DESCRIPTION
**Pull request by carlescufi**
The open source controller did not expose support for shutting it down
via the close() API in the HCI driver. Add support for it, which
completes the support for disabling and enabling the Bluetooth stack in
Zephyr.

Closes #3192.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/hci/hci_driver.c [hunk 1]
```diff
@@ -63,8 +63,8 @@
 
 #include "hci_internal.h"
 
-static K_SEM_DEFINE(sem_prio_recv, 0, K_SEM_MAX_LIMIT);
-static K_FIFO_DEFINE(recv_fifo);
+static struct k_sem sem_prio_recv;
+static struct k_fifo recv_fifo;
```
Comment (Thalley) [inline subsys/bluetooth/controller/hci/hci_driver.c:67]: Why were the static initializers removed in favor of `k_fifo_init` and `k_sem_init`?

**Review by ppryga-nordic — DISMISSED** [review]
LGTM

File: subsys/bluetooth/controller/hci/hci_driver.c [hunk 2]
```diff
@@ -734,13 +733,17 @@ static int hci_driver_open(void)
 
 	DEBUG_INIT();
 
+	k_fifo_init(&recv_fifo);
+	k_sem_init(&sem_prio_recv, 0, K_SEM_MAX_LIMIT);
+
 	err = ll_init(&sem_prio_recv);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/hci/hci_driver.c:739]: `lll_init()` requests LF clock on, multiple `open()` could accumulate the reference count in the clock_control driver?

Either `lll_init()` has to be moved outside of `open()` to be only at power on reset or introduce a `lll_deinit()` which is a combination of `lll_reset()` plus a new `lll_clock_deinit()`  so that LF clock request is released.

**Review by cvinayak — DISMISSED** [review]

File: subsys/bluetooth/controller/hci/hci_driver.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/controller/hci/hci_driver.c:739]: If something needs to be run just once, could they be put in `hci_driver_init`?

Comment (carlescufi) [reply subsys/bluetooth/controller/hci/hci_driver.c:739]: >Either lll_init() has to be moved outside of open() to be only at power on reset or introduce a lll_deinit() which is a combination of lll_reset() plus a new lll_clock_deinit() so that LF clock request is released.

If we did this, then `open()` would do nothing LL-related right?

Comment (cvinayak) [reply subsys/bluetooth/controller/hci/hci_driver.c:739]: > If we did this, then `open()` would do nothing LL-related right?

Yes, and calls to only `ll_reset()` will suffice inside the `close` interface.

File: subsys/bluetooth/controller/hci/hci_driver.c (hunk 1 above)
Comment (carlescufi) [reply subsys/bluetooth/controller/hci/hci_driver.c:67]: Initializing a FIFO makes it empty. Initializing a semaphore resets its count to 0. Since the HCI driver `close()` function can be called at any time, we do need to reset these structures every time `open()` is called (or once at boot and then every time `close()` is called.

>Does it work as intended if hci_driver_open is called multiple times? 

You are not supposed to call `open()` multiple times without calling `close()` first. But if you do that, this will make it work as intended, since we reset all the structs at that point.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c [hunk 3]
```diff
@@ -212,6 +212,28 @@ int lll_init(void)
...
+	}
+
+	/* Disable IRQs */
+	irq_disable(RADIO_IRQn);
+	irq_disable(RTC0_IRQn);
+	irq_disable(HAL_SWI_RADIO_IRQ);
+#if defined(CONFIG_BT_CTLR_LOW_LAT) || \
+	(CONFIG_BT_CTLR_ULL_HIGH_PRIO != CONFIG_BT_CTLR_ULL_LOW_PRIO)
+	irq_disable(HAL_SWI_JOB_IRQ);
+#endif
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c:232]: Isn't `HAL_SWI_JOB_IRQ` always defined? If so, then we can replace the `#if defined` with a `IS_ENABLED`

Comment (carlescufi) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c:232]: Yep, fine with that. @cvinayak you OK with this?

**Comment by cvinayak** [comment]
I get segmentation fault when using `bt_disable()` in a modified `samples/bluetooth/broadcaster` sample.

image

image

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c:232]: yes.

File: subsys/bluetooth/host/hci_core.c [hunk 4]
```diff
@@ -2455,7 +2445,7 @@ static void process_events(struct k_poll_event *ev, int count)
 
 static void hci_tx_thread(void *p1, void *p2, void *p3)
 {
-	static struct k_poll_event events[EV_COUNT] = {
+	struct k_poll_event events[EV_COUNT] = {
```
Comment (cvinayak) [inline subsys/bluetooth/host/hci_core.c:2448]: Not sure by how much the `hci_tx_thread`'s program stack size needs increase, if retaining the `static` does not fault, lets keep it back.

File: subsys/bluetooth/controller/ll_sw/openisa/lll/lll.c [hunk 5]
```diff
@@ -166,6 +166,20 @@ int lll_init(void)
 	return 0;
 }
 
+int lll_deinit(void)
+{
+	/* Disable IRQs */
+	irq_disable(LL_RADIO_IRQn);
+	irq_disable(LL_RTC0_IRQn);
+	irq_disable(HAL_SWI_RADIO_IRQ);
+#if defined(CONFIG_BT_CTLR_LOW_LAT) || \
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/openisa/lll/lll.c:175]: Use IS_ENABLE here too? (I have not checked if these are the correct IRQs for openisa port...)

File: subsys/bluetooth/host/hci_core.c [hunk 6]
```diff
@@ -3655,6 +3645,16 @@ int bt_enable(bt_ready_cb_t cb)
 
 	ready_cb = cb;
 
+	/* Give cmd_sem allowing to send first HCI_Reset cmd, the only
+	 * exception is if the controller requests to wait for an
+	 * initial Command Complete for NOP.
+	 */
+#if !defined(CONFIG_BT_WAIT_NOP)
```
Comment (cvinayak) [inline subsys/bluetooth/host/hci_core.c:3652]: Use IS_ENABLED here too...

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/hci_core.c (hunk 4 above)
Comment (carlescufi) [reply subsys/bluetooth/host/hci_core.c:2448]: Seems to work fine with the `static`, so I'm bringing it back.

File: subsys/bluetooth/controller/ll_sw/openisa/lll/lll.c (hunk 5 above)
Comment (carlescufi) [reply subsys/bluetooth/controller/ll_sw/openisa/lll/lll.c]: Fixed

File: subsys/bluetooth/host/hci_core.c (hunk 6 above)
Comment (carlescufi) [reply subsys/bluetooth/host/hci_core.c]: Fixed

**Comment by carlescufi** [comment]
@ppryga @Thalley @cvinayak please take another look

**Review by Thalley — APPROVED** [review]

**Review by asbjornsabo — APPROVED** [review]
LGTM

**Review by ppryga-nordic — APPROVED** [review]
LGTM

**Review by cvinayak — APPROVED** [review]
