### PR TITLE
Renesas: crc : Fix state management and locking

### LINKED ISSUE #98834: Renesas RA CRC: Incremental calculation (begin/update/finish) has state management and locking bugs
### Describe the bug

This issue concerns **state management**, **thread safety**, and **data correctness** within the Renesas RA CRC driver when performing **incremental calculations** (i.e., using the `begin`/`update`/`finish` API sequence).

The driver exhibited two primary defects:

1. **Semaphore Double-Release (Thread Safety Violation):**
  
  - The `crc_set_config` function prematurely called `crc_unlock(dev)` upon failure of `RP_CRC_Reconfigure`.
    
  - Since the calling function, `crc_renesas_ra_begin`, also calls `crc_unlock(dev)` when `crc_set_config` returns an error, this resulted in calling **`k_sem_give()` twice for a single `k_sem_take()`**.
    
  - This violated standard semaphore usage rules, leading to **corruption of the driver's thread safety** and potentially unexpected behavior in multi-threaded contexts.
    
2. **Inconsistent State Management on Error (Data Corruption Risk):**
  
  - Upon errors occurring during **`crc_set_config`** or **`crc_renesas_ra_update`**, the driver correctly cleared the state using `ctx->state = 0` but failed to reset the internal flag **`data->flag_crc_updated`**.
    
  - This flag remaining set could incorrectly cause a subsequent, new CRC calculation sequence to **use the corrupted previous intermediate result as its seed** instead of the user-provided seed value.
    
  - This leads to **incorrect CRC calculation results** following an error condition.

**Area**:	Renesas RA Drivers, CRC

### Regression

- [ ] This is a regression.

### Steps to reproduce

See the detailed description of the bugs above. The issues relate to error handling and state management in the incremental CRC calculation API sequence (begin/update/finish).

### Relevant log output

```shell

```

### Impact

Not sure

### Environment

Os: Windows WSL
Toolchain: Zephyr SDK
Driver: Renesas RA CRC Driver

### Additional Context

Fix Proposal is presented in the following PR : https://github.com/zephyrproject-rtos/zephyr/pull/98622

### PR DESCRIPTION
**Pull request by kaabia**
Fixes #98834

This PR resolves several critical issues concerning state management, thread safety, and data correctness when using the Renesas RA CRC driver for incremental calculations (i.e., using the `begin`/`update`/`finish` API sequence).

#### 1. Semaphore Double-Release

The `crc_set_config` function prematurely called `crc_unlock(dev)` upon failure of `RP_CRC_Reconfigure`. Since `crc_renesas_ra_begin` also calls `crc_unlock(dev)` when `crc_set_config` returns an error, this resulted in calling `k_sem_give()` twice for a single `k_sem_take()`. This violated semaphore usage rules and corrupted the driver's thread safety.

* **Fix:** Removed the `crc_unlock()` call from `crc_set_config`. The locking/unlocking is now strictly managed by `crc_renesas_ra_begin` and `crc_renesas_ra_finish`.

#### 2. Inconsistent State Management

Upon errors during `crc_set_config` or `crc_renesas_ra_update`, the driver cleared `ctx->state` but failed to reset the internal `data->flag_crc_updated` flag. This could cause a subsequent attempt to incorrectly use the corrupted previous result as a seed.

* **Fix:** Added `data->flag_crc_updated = false;` to all error paths to ensure the driver state is fully reset and a new sequence correctly starts from the user-provided seed.

### CODE REVIEW

File: drivers/crc/crc_renesas_ra.c [hunk 1]
```diff
@@ -158,10 +158,21 @@ static int crc_renesas_ra_update(const struct device *dev, struct crc_ctx *ctx,
...
+
+		/*
+		 * After the hardware calculation for CRC8 and CRC16,
+		 * ctx->result should be explicitly masked to the correct bit width
+		 */
+		if (ctx->type == CRC8) {
+			ctx->result &= 0xFF;
+		} else {
+			ctx->result &= 0xFFFF;
+		}
```
Comment (thenguyenyf) [inline drivers/crc/crc_renesas_ra.c]: Could you please share the sample and re-produce process for the issue you mentioned? The need for this update is quite strange because the masking is already done inside `R_CRC_Calculate`.

https://github.com/zephyrproject-rtos/hal_renesas/blob/main/drivers/ra/fsp/src/r_crc/r_crc.c#L373

Notes: `CRCDOR_BY` is 8 bits register

**Review by thenguyenyf — CHANGES_REQUESTED** [review]

File: drivers/crc/crc_renesas_ra.c (hunk 1 above)
Comment (kaabia) [reply drivers/crc/crc_renesas_ra.c]: Thank you for your detailed review! You are correct that the FSP's `crc_calculated_value_get` function returns a mathematically clean, zero-extended `uint32_t`.

The necessity for this mask lies in **enforcing Zephyr's state hygiene** and mitigating a potential, difficult-to-reproduce **memory pollution bug** at the boundary between the driver and the HAL.

### The Issue: Unsafe Memory Overwrite

The problem occurs when the clean 32-bit result is written via pointer back into the Zephyr context variable, `ctx->result`:


```C
// Assignment in the HAL: *calculatedValue is a pointer to ctx->result
*calculatedValue = crc_calculated_value_get(p_instance_ctrl);
```

In low-level embedded systems, relying on this single assignment to clear the full 32-bit memory location is risky if the destination variable (`ctx->result`) was previously dirty (e.g., $\text{0xDEADBEEF}$):

- The operation is **not guaranteed** to atomically overwrite all 32 bits, especially if the memory is not always aligned, or due to compiler optimization.
  
- If the write of the upper zero-bytes fails, the Zephyr context state becomes polluted (e.g., $\text{0xDEADBEA1}$), breaking the driver's contract that a $\text{CRC8}$ result must be $\le \text{0xFF}$.

### Conclusion: The Mask is a Defensive Guarantee

The explicit mask is a **defensive programming practice**. It is the only way for the Zephyr driver to guarantee the internal state is clean:

```C
// The fix: Guarantees a clean state regardless of HAL write behavior
ctx->result &= 0xFF;
```

This ensures the `ctx->result` is strictly $\le \text{0xFF}$, preventing a **memory pollution bug** that could affect external calls reading the final CRC value. I recommend keeping the modification for **driver robustness and integrity.**

**If you think that this is too defensive, we can simply discard it ^_^**

Comment (thenguyenyf) [reply drivers/crc/crc_renesas_ra.c]: Thank you for the explanation!

> In low-level embedded systems, relying on this single assignment to clear the full 32-bit memory location is risky if the destination variable (ctx->result) was previously dirty (e.g., 
0xDEADBEEF):

I spent the time to check with zephyr-sdk-0.17.4 on RA8M1, and it work well with all available compiler optimization levels. There is no case that the previous used `struct crc_ctx` by CRC32 calculation cause the memory pollution bug when input it again for a CRC8 calculation.

`ctx->result` should be 32-bit aligned because it is a 32-bit typedef member of `struct crc_ctx` (not a pointer to somewhere in the memory map).

So, in my opinion the defense guarantee is sufficient inside `crc_renesas_ra` → additional defense inside this driver is not necessary.

Comment (thenguyenyf) [reply drivers/crc/crc_renesas_ra.c]: @kaabia . After reverting this change, other update looks good to me.

**Review by thenguyenyf — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by thenguyenyf** [comment]
@kaabia . You might need to report an issue then link it in this PR if you want to have this update in v4.3.0, as I see that release team has mentioned it is required for a bug fix in RC2 https://github.com/zephyrproject-rtos/zephyr/pull/98602#issuecomment-3482207051

**Review by KhiemNguyenT — APPROVED** [review]
LGTM. Thanks.
