### PR TITLE
lib: acpi: fix for build error when acpi not enabled

### LINKED ISSUE #68467: ACPI: acpi.h header file generates invalid C-code when CONFIG_ACPI=n
**Describe the bug**
c-files that may not be 100% ACPI-related cannot unconditionally include the `include/zephyr/acpi/acpi.h` header file because it will contain invalid C-code if CONFIG_ACPI is disabled.

**Expected behavior**

acpi.h can be always be unconditionally included, allowing the use of e.g. `IS_ENABLED()` in the code.

**Impact**

Only 100% ACPI-related c-files may include the header file, or then the inclusion as well as any related code needs to be protected by #ifdef guards.

**Additional context**

The two problematic structs in acpi.h are these:
```c
struct acpi_irq_resource {
	uint32_t flags;
	union {
		uint16_t irq;
		uint16_t irqs[CONFIG_ACPI_IRQ_VECTOR_MAX];
	};
	uint8_t irq_vector_max;
};

struct acpi_mmio_resource {
	struct acpi_reg_base reg_base[CONFIG_ACPI_MMIO_ENTRIES_MAX];
	uint8_t mmio_max;
};
```

They're used by these APIs:
```c
int acpi_device_irq_get(struct acpi_dev *child_dev, struct acpi_irq_resource *irq_res);

int acpi_device_mmio_get(struct acpi_dev *child_dev, struct acpi_mmio_resource *mmio_res);
```

The Kconfig dependency could be removed by removing the arrays from the structs and changing the APIs so that the callers provide the array storage and the array sizes.

### PR DESCRIPTION
**Pull request by najumon1980**
Fix for acpi.h header file generates invalid C-code when CONFIG_ACPI=n

Fixes #68467

### CODE REVIEW

File: lib/acpi/acpi.c [hunk 1]
```diff
@@ -461,7 +461,6 @@ int acpi_device_irq_get(struct acpi_dev *child_dev, struct acpi_irq_resource *ir
 			return -ENOMEM;
 		}
 
-		memset(irq_res, 0, sizeof(struct acpi_irq_resource));
 		irq_res->irq_vector_max = res->Data.ExtendedIrq.InterruptCount;
```
Comment (jhedberg) [inline lib/acpi/acpi.c:464]: What do you do if `res->Data.ExtendedIrq.InterruptCount` is greater than `CONFIG_ACPI_IRQ_VECTOR_MAX`? Don't you get a buffer overrun in that case?

I think the simple solution (which wouldn't require API changes) would be for the caller to pass the array size through the initial values of `irq_vector_max` and `mmio_max` and then upon return these would contain the actual number of fetched elements.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: lib/acpi/acpi.c (hunk 1 above)
Comment (najumon1980) [reply lib/acpi/acpi.c:464]: updated

File: lib/acpi/acpi.c [hunk 2]
```diff
@@ -470,7 +469,7 @@ int acpi_device_irq_get(struct acpi_dev *child_dev, struct acpi_irq_resource *ir
 		irq_res->flags = arch_acpi_encode_irq_flags(res->Data.ExtendedIrq.Polarity,
 							    res->Data.ExtendedIrq.Triggering);
 	} else {
-		if (res->Data.Irq.InterruptCount > CONFIG_ACPI_IRQ_VECTOR_MAX) {
+		if (res->Data.Irq.InterruptCount > irq_res->irq_vector_max) {
 			return -ENOMEM;
 		}
```
Comment (jhedberg) [inline lib/acpi/acpi.c:474]: This is fine, but you're also missing the update of `irq_res->irq_vector_max` before returning from the function (to indicate how many entries were actually filled in). Maybe the variable should be `irq_vector_count`, since it's only a maximum when calling the function, but the actual count when returning.

File: lib/acpi/acpi_shell.c [hunk 3]
```diff
@@ -304,6 +307,8 @@ static int get_acpi_dev_resource(const struct shell *sh, size_t argc, char **arg
 			}
 		}
 
+		irq_res.irq_vector_max = CONFIG_ACPI_IRQ_VECTOR_MAX;
```
Comment (jhedberg) [inline lib/acpi/acpi_shell.c:310]: `ARRAY_SIZE(irqs)` is better, since it's then clear what array this relates to and the code will not break even if you change the size of the array to be derived from some other constant.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Some changes still needed. You're also completely missing the changes to `acpi_device_mmio_get()` - that function still assumes an array of `CONFIG_ACPI_MMIO_ENTRIES_MAX` size.

File: tests/lib/acpi/integration/src/main.c [hunk 4]
```diff
@@ -57,10 +59,12 @@ ZTEST(acpi, test_resource_enum)
 
 	zassert_not_null(dev, "Failed to get acpi device with given HID");
 
+	mmio_res.reg_base = reg_base;
 	ret = acpi_device_mmio_get(dev, &mmio_res);
 
 	zassert_ok(ret, "Failed to get MMIO resources");
 
+	irq_res.irqs = irqs;
 	ret = acpi_device_irq_get(dev, &irq_res);
```
Comment (jhedberg) [inline tests/lib/acpi/integration/src/main.c:68]: Aren't you missing the setting of the `*_max` values here? The `irq_res` and `mmio_res` variables are not currently initialised in this function, which would leave the ACPI function accessing uninitialised memory.

**Review by jhedberg — CHANGES_REQUESTED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by finikorg — APPROVED** [review]
