### PR TITLE
drivers: spi_ll_stm32: Enable SPI driver for F1 family

### LINKED ISSUE #1281: spi_ll_stm32 driver does not support stm32f1soc
when I compile the samples/hello_world with the stm32f103ze boards, Two errors appear：
error: ‘SPI_SR_FRE’ undeclared
error: ‘LL_SPI_PROTOCOL_MOTOROLA’ undeclared

### PR DESCRIPTION
**Pull request by ydamigos**
Enables SPI driver for STM32F1 SoCs.

Tested on olimexino_stm32 using spi_loopback test.

Fixes #1281 and #3850.

### CODE REVIEW

File: boards/arm/olimexino_stm32/olimexino_stm32_defconfig [hunk 1]
```diff
@@ -20,6 +20,15 @@ CONFIG_UART_CONSOLE=y
 CONFIG_I2C=y
 CONFIG_I2C_STM32_V1=y
 
+# enable SPI
+CONFIG_SPI=y
+CONFIG_SPI_STM32=y
+CONFIG_SPI_STM32_INTERRUPT=y
+CONFIG_SPI_1=y
+CONFIG_SPI_1_IRQ_PRI=10
+CONFIG_POLL=y
```
Comment (mbolivar) [inline boards/arm/olimexino_stm32/olimexino_stm32_defconfig]: How is that SPI related? If the interrupt driver requires CONFIG_POLL=y, maybe it should select it.

File: include/dt-bindings/pinctrl/stm32-pinctrlf1.h [hunk 2]
```diff
@@ -75,10 +75,17 @@
...
-#define STM32_PIN_USART_TX	(STM32_MODE_OUTPUT | STM32_CNF_ALT_FUNC | STM32_CNF_PUSH_PULL)
-#define STM32_PIN_USART_RX	(STM32_MODE_INPUT | STM32_CNF_IN_FLOAT)
-#define STM32_PIN_I2C		(STM32_MODE_OUTPUT | STM32_CNF_ALT_FUNC | STM32_CNF_OPEN_DRAIN)
-#define STM32_PIN_PWM		(STM32_MODE_OUTPUT | STM32_CNF_ALT_FUNC | STM32_CNF_PUSH_PULL)
-
+#define STM32_PIN_USART_TX		(STM32_MODE_OUTPUT | STM32_CNF_ALT_FUNC | STM32_CNF_PUSH_PULL)
+#define STM32_PIN_USART_RX		(STM32_MODE_INPUT | STM32_CNF_IN_FLOAT)
+#define STM32_PIN_I2C			(STM32_MODE_OUTPUT | STM32_CNF_ALT_FUNC | STM32_CNF_OPEN_DRAIN)
+#define STM32_PIN_PWM			(STM32_MODE_OUTPUT | STM32_CNF_ALT_FUNC | STM32_CNF_PUSH_PULL)
+#define STM32_PIN_SPI_MASTER_NSS	(STM32_MODE_INPUT | STM32_CNF_IN_FLOAT)
```
Comment (mbolivar) [inline include/dt-bindings/pinctrl/stm32-pinctrlf1.h]: Shouldn't master NSS be output push pull?

File: drivers/spi/spi_ll_stm32.c [hunk 3]
```diff
@@ -98,13 +97,19 @@ static void spi_stm32_shift_m(SPI_TypeDef *spi, struct spi_stm32_data *data)
 	if (SPI_WORD_SIZE_GET(data->ctx.config->operation) == 8) {
 		rx_frame = LL_SPI_ReceiveData8(spi);
 		if (spi_context_rx_on(&data->ctx)) {
-			UNALIGNED_PUT(rx_frame, (u8_t *)data->ctx.rx_buf);
+			if (data->ctx.rx_buf) {
+				UNALIGNED_PUT(rx_frame,
+					      (u8_t *)data->ctx.rx_buf);
+			}
 			spi_context_update_rx(&data->ctx, 1, 1);
```
Comment (mbolivar) [inline drivers/spi/spi_ll_stm32.c]: Why does this remain outside the new if statement, instead of moving inside? Similar questions below.

**Review by mbolivar — COMMENTED** [review]
Some questions

File: include/dt-bindings/pinctrl/stm32-pinctrlf1.h (hunk 2 above)
Comment (ydamigos) [reply include/dt-bindings/pinctrl/stm32-pinctrlf1.h]: According to RM0008 NSS can be configured as
```
Hardware master /slave -> Input floating/ Input pull-up / Input pull-down
Hardware master/ NSS output enabled -> Alternate function push-pull
Software -> Not used. Can be used as a GPIO
```
I just added the first option to support multi master bus.

File: drivers/spi/spi_ll_stm32.c (hunk 3 above)
Comment (ydamigos) [reply drivers/spi/spi_ll_stm32.c]: I thought it should but it broke spi_loopback test. If the spi_context_update_rx() is not called, it will never move to the second rx_buf.

File: boards/arm/olimexino_stm32/olimexino_stm32_defconfig (hunk 1 above)
Comment (ydamigos) [reply boards/arm/olimexino_stm32/olimexino_stm32_defconfig]: I just copy/paste some CONFIG_* from the spi_loopback prj.conf and forget to remove it. I will fix it.

File: drivers/spi/spi_ll_stm32.c (hunk 3 above)
Comment (ydamigos) [reply drivers/spi/spi_ll_stm32.c]: I propose to move `spi_context_update_rx()` inside if and push another commit which will substitute null rx_bufs with `dummy_rx_bufs` in spi_loopback test. How does that sound to you?

**Review by dbkinder — DISMISSED** [review]
+1 for docs

File: drivers/spi/spi_ll_stm32.c [hunk 4]
```diff
@@ -98,14 +97,20 @@ static void spi_stm32_shift_m(SPI_TypeDef *spi, struct spi_stm32_data *data)
 	if (SPI_WORD_SIZE_GET(data->ctx.config->operation) == 8) {
 		rx_frame = LL_SPI_ReceiveData8(spi);
 		if (spi_context_rx_on(&data->ctx)) {
-			UNALIGNED_PUT(rx_frame, (u8_t *)data->ctx.rx_buf);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c]: Why not using `&& data->ctx.rx_buf` as you did for tx?
It makes both change and code lighter.
I guess this is a leftover from initial commit. Latest code allows you to do it now.

File: drivers/spi/spi_ll_stm32.c [hunk 5]
```diff
@@ -98,14 +97,20 @@ static void spi_stm32_shift_m(SPI_TypeDef *spi, struct spi_stm32_data *data)
...
+			if (data->ctx.rx_buf) {
+				UNALIGNED_PUT(rx_frame,
+					      (u8_t *)data->ctx.rx_buf);
+				spi_context_update_rx(&data->ctx, 1, 1);
+			}
 		}
 	} else {
 		rx_frame = LL_SPI_ReceiveData16(spi);
 		if (spi_context_rx_on(&data->ctx)) {
-			UNALIGNED_PUT(rx_frame, (u16_t *)data->ctx.rx_buf);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c]: ditto

File: drivers/spi/spi_ll_stm32.c [hunk 6]
```diff
@@ -133,16 +138,20 @@ static void spi_stm32_shift_s(SPI_TypeDef *spi, struct spi_stm32_data *data)
 		if (SPI_WORD_SIZE_GET(data->ctx.config->operation) == 8) {
 			rx_frame = LL_SPI_ReceiveData8(spi);
 			if (spi_context_rx_on(&data->ctx)) {
-				UNALIGNED_PUT(rx_frame,
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c]: ditto

File: drivers/spi/spi_ll_stm32.c [hunk 7]
```diff
@@ -133,16 +138,20 @@ static void spi_stm32_shift_s(SPI_TypeDef *spi, struct spi_stm32_data *data)
...
+				if (data->ctx.rx_buf) {
+					UNALIGNED_PUT(rx_frame,
+						      (u8_t *)data->ctx.rx_buf);
+					spi_context_update_rx(&data->ctx, 1, 1);
+				}
 			}
 		} else {
 			rx_frame = LL_SPI_ReceiveData16(spi);
 			if (spi_context_rx_on(&data->ctx)) {
-				UNALIGNED_PUT(rx_frame,
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c]: ditto

File: include/dt-bindings/pinctrl/stm32-pinctrlf1.h (hunk 2 above)
Comment (erwango) [reply include/dt-bindings/pinctrl/stm32-pinctrlf1.h]: Since this part is a bit tricky, it might be worse adding some comments.
You could also provide definitions for NSS output enabled, even if not used.
It might help user to understand what he need.
Exact reference to User manual (§25.3.1: Slave select (NSS) pin management) would also help.

**Review by erwango — CHANGES_REQUESTED** [review]
Some minor comments otherwise looks good

File: drivers/spi/spi_ll_stm32.c (hunk 4 above)
Comment (ydamigos) [reply drivers/spi/spi_ll_stm32.c]: I'll fix it.

File: drivers/spi/spi_ll_stm32.c (hunk 5 above)
Comment (ydamigos) [reply drivers/spi/spi_ll_stm32.c]: I'll fix it.

File: drivers/spi/spi_ll_stm32.c (hunk 6 above)
Comment (ydamigos) [reply drivers/spi/spi_ll_stm32.c]: I'll fix it.

File: drivers/spi/spi_ll_stm32.c (hunk 7 above)
Comment (ydamigos) [reply drivers/spi/spi_ll_stm32.c]: I'll fix it.

File: include/dt-bindings/pinctrl/stm32-pinctrlf1.h [hunk 8]
```diff
@@ -75,10 +75,35 @@
...
+ *
+ * Software NSS management:
+ * - External NSS pin remains free for other application uses.
+ *
+ */
+
+/* Hardware master NSS output disabled */
+#define STM32_PIN_SPI_MASTER_NSS	(STM32_MODE_INPUT | STM32_CNF_IN_FLOAT)
+/* Hardware master NSS output enabled */
+#define STM32_PIN_SPI_MASTER_NSS_OE	(STM32_MODE_OUTPUT | STM32_CNF_ALT_FUNC | STM32_CNF_PUSH_PULL)
```
Comment (ydamigos) [inline include/dt-bindings/pinctrl/stm32-pinctrlf1.h]: @erwango Is this clear enough? STM32_PIN_SPI_MASTER_NSS_OUTPUT_ENABLED is too long.

File: drivers/spi/spi_ll_stm32.c (hunk 3 above)
Comment (mbolivar) [reply drivers/spi/spi_ll_stm32.c]: Interesting, so the .buf = NULL inside of the rx_bufs definitions (like in spi_rx_half_end()) in the spi_loopback test is breaking things, you mean?

If so, perhaps this is a bug in the SPI core? Haven't had time to look into it in detail, just to be clear.

Comment (ydamigos) [reply drivers/spi/spi_ll_stm32.c]: > Interesting, so the .buf = NULL inside of the rx_bufs definitions (like in spi_rx_half_end()) in the spi_loopback test is breaking things, you mean?

Yes, it causes bus error on some SoCs (e.g. stm32f103, stm32f334).

Comment (mbolivar) [reply drivers/spi/spi_ll_stm32.c]: Thank you for your response!

@tbursztyka, could the test possibly be structuring its buffers incorrectly from what you meant?

If not, perhaps this is a bug in the STM32 area.

**Comment by ydamigos** [comment]
recheck

**Comment by mbolivar** [comment]
(FTR, my questions on this PR are all addressed. Not adding a +1 as I haven't looked at it in detail)

**Comment by superna9999** [comment]
All this NULL buffers should be clarified, apart from that it's OK for me.

File: include/dt-bindings/pinctrl/stm32-pinctrlf1.h (hunk 8 above)
Comment (erwango) [reply include/dt-bindings/pinctrl/stm32-pinctrlf1.h]: Yes this is fine, thanks

**Comment by superna9999** [comment]
I'd like to have @tbursztyka review the changes around these NULL buffers check, the spi loopback test is running correctly on F0, L4 and F4.

**Comment by ydamigos** [comment]
@tbursztyka Could you have a look?

**Comment by miyatsu** [comment]
Is this PR tested after https://github.com/zephyrproject-rtos/zephyr/pull/5582 merged ?

**Comment by ydamigos** [comment]
No. It needs a rebase to take into account the changes in master branch, since PR #5582 was merged in master branch.

@galak Will you merge master branch to arm branch? Should I rebase the PR to master branch?

**Comment by ydamigos** [comment]
I rebased it and add SPI configuration using DT.

**Comment by ydamigos** [comment]
@erwango @superna9999 @tbursztyka @mbolivar I made some changes and dropped the commit which changed the NULL rx buffers in spi_loopback test. Could you please review the PR again?

**Review by superna9999 — DISMISSED** [review]
OK, it's better, now we can't have pointer issues

**Review by erwango — DISMISSED** [review]

File: drivers/spi/spi_ll_stm32.c [hunk 9]
```diff
@@ -57,17 +57,16 @@ static int spi_stm32_get_err(SPI_TypeDef *spi)
 
 static inline u16_t spi_stm32_next_tx(struct spi_stm32_data *data)
 {
-	u16_t tx_frame;
+	u16_t tx_frame = SPI_STM32_TX_NOP;
 
-	if (spi_context_tx_on(&data->ctx)) {
+	if (data->ctx.tx_buf) {
```
Comment (tbursztyka) [inline drivers/spi/spi_ll_stm32.c]: Check PR #5785 buf can be non-null, but if len is 0 we should not touch it.

So instead, use spi_context_tx_buf_on()

**Comment by ydamigos** [comment]
I updated to take into account PR #5785.
I added DNM flag because it should be merged after PR #5785.

**Review by erwango — DISMISSED** [review]

File: drivers/spi/spi_ll_stm32.c [hunk 10]
```diff
@@ -97,13 +96,13 @@ static void spi_stm32_shift_m(SPI_TypeDef *spi, struct spi_stm32_data *data)
 
 	if (SPI_WORD_SIZE_GET(data->ctx.config->operation) == 8) {
 		rx_frame = LL_SPI_ReceiveData8(spi);
-		if (spi_context_rx_on(&data->ctx)) {
+		if (spi_context_rx_buf_on(&data->ctx)) {
 			UNALIGNED_PUT(rx_frame, (u8_t *)data->ctx.rx_buf);
 			spi_context_update_rx(&data->ctx, 1, 1);
```
Comment (DWagenk) [inline drivers/spi/spi_ll_stm32.c]: it's not working if `spi_context_update_rx` is not called (hanging forever when rx buffer is NULL). 
compared this revision with the two versions below:

working (this PR up until about 1 hour ago, but without tbursztyka's API-changes) : 
```c
if (SPI_WORD_SIZE_GET(data->ctx.config->operation) == 8) {
	rx_frame = LL_SPI_ReceiveData8(spi);
	if (data->ctx.rx_buf) {
		UNALIGNED_PUT(rx_frame,
			      (u8_t *)data->ctx.rx_buf);
        }
	spi_context_update_rx(&data->ctx, 1, 1);
} else {
```
also working (my solution combining both versions above) : 
```c
if (SPI_WORD_SIZE_GET(data->ctx.config->operation) == 8) {
	rx_frame = LL_SPI_ReceiveData8(spi);
	if (spi_context_rx_buf_on(&data->ctx)) {
		UNALIGNED_PUT(rx_frame,
			      (u8_t *)data->ctx.rx_buf);
        }
	spi_context_update_rx(&data->ctx, 1, 1);
} else {
```

**Review by dwagenk — DISMISSED** [review]

**Comment by DWagenk** [comment]
it's not working for me. 
1. I added SPI conf to stm32f3_disco and experienced hard fault problems as described in issue #3850 when running spi loopback test.
2. Worked when I applied the patches from this pull request until the last update about 1 hour ago. 
3. updated to current code in this PR
4. it hangs forever (no hard fault anymore).
```
***** BOOTING ZEPHYR OS v1.10.99 - BUILD: Jan 23 2018 08:29:17 *****
[general] [INF] main: SPI test on buffers TX/RX 0x20001344/0x20000000
[general] [DBG] spi_async_call_cb: Polling...
[general] [INF] spi_complete_loop: Start
[general] [INF] spi_complete_loop: Passed
[general] [INF] spi_rx_half_start: Start
[general] [INF] spi_rx_half_start: Passed
[general] [INF] spi_rx_every_4: Start
```
--------------------
Problem seems to be, that `spi_context_update_rx` is not called when buffer is empty. See in code comment in my review

File: drivers/spi/spi_ll_stm32.c (hunk 10 above)
Comment (ydamigos) [reply drivers/spi/spi_ll_stm32.c]: You are right, I messed it up during a rebase.

**Comment by ydamigos** [comment]
@DWagenk Could you try it again? It should be fixed now.

**Comment by DWagenk** [comment]
@ydamigos it's working now. Thanks

File: ext/hal/st/stm32cube/CMakeLists.txt [hunk 11]
```diff
@@ -44,6 +44,7 @@ if(CONFIG_SOC_SERIES_STM32F1X)
   zephyr_sources(stm32f1xx/drivers/src/stm32f1xx_hal.c)
   zephyr_sources(stm32f1xx/drivers/src/stm32f1xx_hal_rcc.c)
   zephyr_sources_ifdef(CONFIG_CLOCK_CONTROL_STM32_CUBE stm32f1xx/drivers/src/stm32f1xx_ll_utils.c)
+  zephyr_sources_ifdef(CONFIG_SPI_STM32 stm32f1xx/drivers/src/stm32f1xx_ll_spi.c)
```
Comment (b0661) [inline ext/hal/st/stm32cube/CMakeLists.txt]: This is not necessary anymore after PR #4646 is merged. Works for me without.

**Comment by ydamigos** [comment]
I rebased it to resolve some conflicts.

File: ext/hal/st/stm32cube/CMakeLists.txt (hunk 11 above)
Comment (ydamigos) [reply ext/hal/st/stm32cube/CMakeLists.txt]: Fixed

**Comment by ydamigos** [comment]
Now that PR #5785 is merged, I rebased it against master and removed the DNM flag.

Please review it again.

**Review by erwango — APPROVED** [review]
Tested ok on nucleo_f103rb

**Review by tbursztyka — APPROVED** [review]

**Review by superna9999 — APPROVED** [review]

**Comment by galak** [comment]
@DWagenk still have issues with this?

**Review by galak — APPROVED** [review]

**Comment by DWagenk** [comment]
no, ydamigos solved those problems right away!

> DWagenk commented 9 days ago
 ydamigos it's working now. Thanks
