### PR TITLE
drivers: display: ls0xx: add support for serial VCOM inversion

### LINKED ISSUE #98271: drivers: display: ls0xx driver doesn't support serial VCOM inversion
### Describe the bug

I would classify this as an enhancement, not a bug, as the current behavior is documented in the example "[Sharp memory display generic shield](https://docs.zephyrproject.org/latest/boards/shields/ls0xx_generic/doc/index.html)", but @JarmouniA recommended opening the issue as a bug in #96396. 

The current `sharp,ls0xx` in-tree driver only supports driver-level management of inversion of the internal VCOM (common) voltage for devices where the `EXTCOMIN` pin is connected to a GPIO to toggle inversion of the VCOM voltage. The `ls0xx` panel series also support inverting the internal VCOM voltage by changing the SPI message.

There are a number of hobbyist-focused products and projects I am aware of that use these displays, and people frequently use them with Zephyr-based application firmware unaware of the risk of image retention and the possibility of long-term damage if they don't invert the VCOM voltage at regular intervals (sources vary as to minimum frequency of inversion, but no-longer-available Sharp application notes said 1 Hz, though this causes noticeable shifts at a 1-second interval which likely explains the higher rates in other documentation) to prevent electrolytic degradation.

While applications can send the inversion command with display updates, this would require many hobby-focused or generic applications to update – possibly when used with displays the authors never intended their project to be used with and by beginners without the required experience to modify the application to manage internal VCOM inversion.

Since the `sharp,ls0xx` driver already supports driver level management of internal VCOM inversion when using an `EXTCOMIN` GPIO, I believe that adding this support to the driver for serial (SPI) commands as well is a consistent and logical approach

In #96396 I have built upon the approach taken by @Nice11 in the now-closed as stale #50935. Testing `Nice11`'s approach I found that it leads to display artifacts when an otherwise-empty inversion command is sent in the middle of a display data update. I added a mutex to avoid this issue, and with thanks to @JarmouniA for explaining that a semaphore is more efficient as implemented in Zephyr, I switched this to a semaphore. The result is that inversion of internal VCOM (which is only visible when observed closely under bright light) can be slightly inconsistent if delayed awaiting a display update but there is no data corruption caused by the inversion commands. This is likely the best-case when managing VCOM inversion outside of the application sending display updates.

Next, while #50935 proposed making this the default if `EXTCOMIN` isn't configured, I've added new devicetree properties in recognition that while the above is far better than reduced contrast, image retention, or possible damage, the application is in the best position, where feasible, to manage these commands.

Therefore, no existing users who have already implemented application-level inversion in sync with their display update cycle will be impacted, though many existing users of this driver will be able to improve image quality and prevent display damage simply by setting these new properties.

Thanks to: 
- @JarmouniA for review of #96396 and information on Zephyr efficiency for mutexes vs semaphores
- @MickiusMousius for testing of my approach on additional hardware

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by galaxyeden**
The ls0xx display series require continuous VCOM inversion to prevent panel damage, this commit adds support for doing so over SPI (without EXTCOMIN connected), set via a new pair of devicetree properties so that this isn't a breaking change for anyone implementing this in their application already.

I've tested this on an nRF5340-based board with the LS013B7DH05, and others have tested parts of my work with other displays in the ls0xx line and with the nRF52840 work. 

This is based on the work that was started in the stale pull request #50935 and takes the same approach, however I ran into a few issues:
- The existing VCOM inversion stack overflowed
- That pull request is a breaking change for anyone already handling this in their application code
- There is no protection between display commands and display refreshes, so it would cause occasional image artifacts

Additionally, the addition of a mutex to cover commands and updates should improve this driver for all use cases so that one can't get image artifacts sending commands to the display.

I've tested this with EXTCOMIN to confirm it sends the signal as expected still and without any VCOM-related properties (the ones for EXTCOMIN and the ones I added for serial VCOM) to help ensure this is non-breaking for existing users.

If this moves forward, I will separately PR an update to the [Sharp memory display generic shield](https://docs.zephyrproject.org/latest/boards/shields/ls0xx_generic/doc/index.html) page to document the new devicetree options and that it is no longer the case that one must manage VCOM in software if they haven't connected EXTCOMIN.

Fixes #98271

### CODE REVIEW

**Comment by galaxyeden** [comment]
I'm currently working to make the linter happy, that force push was incorrect but another follows :)

**Comment by galaxyeden** [comment]
Sorry for the noise, I thought I had it - I'll get the linter setup locally I promise!

**Comment by galaxyeden** [comment]
Force pushed new commit with no changes to force a rerun in case the workflow just had a glitch getting the package it failed on last run.

**Comment by galaxyeden** [comment]
I'm stuck on a failure to get a dependency in the `twister-build-prep` workflow, any thoughts?

- Update – this is because my fork was based on the fork for a Zephyr application I'm working with and was outdated. 🫨 
- Update 2025-09-24 – I've removed the unused assignment and this should resolve the SonarQube issue so as long as nothing new comes up in CI/CD this is only awaiting review and your feedback. Please let me know any feedback you have for this or questions about the approach.

**Comment by kartben** [comment]
Thanks! A quick comment from my side: please do keep copyright notice mentioning original author, it looks like some of their code is still there in this PR (which is great!). You may also want to add them as coauthor in the commit message

File: drivers/display/ls0xx.c [hunk 1]
```diff
@@ -96,32 +70,82 @@ static int ls0xx_blanking_on(const struct device *dev)
...
+
+	while (1) {
+#if DT_INST_NODE_HAS_PROP(0, extcomin_gpios)
+		gpio_pin_toggle_dt(&config->extcomin_gpio);
+		k_usleep(3);
+		gpio_pin_toggle_dt(&config->extcomin_gpio);
+		k_msleep(1000 / DT_INST_PROP(0, extcomin_frequency));
+#elif DT_INST_PROP(0, serial_vcom_inversion)
+		/* Waits up to 240ms as if the screen isn't free by this point,
+		 *  multiple refresh cycles were likey missed
```
[the remark this answers is not in the document]
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: I'll correct this

File: drivers/display/ls0xx.c [hunk 2]
```diff
@@ -250,42 +274,44 @@ static int ls0xx_init(const struct device *dev)
...
+					    SPI_CS_ACTIVE_HIGH | SPI_HOLD_ON_CS | SPI_LOCK_ON,
+				    0),
 #if DT_INST_NODE_HAS_PROP(0, disp_en_gpios)
 	.disp_en_gpio = GPIO_DT_SPEC_INST_GET(0, disp_en_gpios),
 #endif
 #if DT_INST_NODE_HAS_PROP(0, extcomin_gpios)
 	.extcomin_gpio = GPIO_DT_SPEC_INST_GET(0, extcomin_gpios),
 #endif
+#if DT_INST_PROP(0, serial_vcom_inversion)
+	.serial_vcom_int = DT_INST_PROP_OR(0, serial_vcom_interval, LS0XX_MAX_VCOM_MSEC)
```
[the remark this answers is not in the document]
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: This does not cause a compilation error because it's the last item in the struct, but I also prefer trailing commas – this is a typo I didn't observe because it doesn't cause a compilation error, but I still agree with it and will change.

File: drivers/display/ls0xx.c [hunk 3]
```diff
@@ -250,42 +274,44 @@ static int ls0xx_init(const struct device *dev)
...
+#endif /* DT_INST_PROP(0, serial_vcom_inversion) */
 };
-
 static DEVICE_API(display, ls0xx_driver_api) = {
 	.blanking_on = ls0xx_blanking_on,
 	.blanking_off = ls0xx_blanking_off,
 	.write = ls0xx_write,
-	.clear = ls0xx_clear,
 	.get_capabilities = ls0xx_get_capabilities,
 	.set_pixel_format = ls0xx_set_pixel_format,
```
[the remark this answers is not in the document]
Comment (galaxyeden) [reply drivers/display/ls0xx.c:364]: I'm going to restore this at the end, not above, but this came from me working with an older version before the PR that added this, I thought I'd brought everything back, but I'd overlooked this.

File: drivers/display/ls0xx.c [hunk 4]
```diff
@@ -1,46 +1,32 @@
...
-#define LS0XX_BYTES_PER_LINE  ((LS0XX_PANEL_WIDTH / LS0XX_PIXELS_PER_BYTE) + 2)
-
-#define LS0XX_BIT_WRITECMD    0x01
-#define LS0XX_BIT_VCOM        0x02
-#define LS0XX_BIT_CLEAR       0x04
+#if DT_INST_PROP(0, serial_vcom_inversion)
+#define USE_VCOM_THREAD true
+#elif DT_INST_NODE_HAS_PROP(0, extcomin_gpios)
+#define USE_VCOM_THREAD true
+#endif /* DT_INST_PROP(0, serial_vcom_inversion) */
```
[the remark this answers is not in the document]
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: Sure, I kept these separate while testing and didn't merge, but consolidating is more readable.

**Comment by galaxyeden** [comment]
@kartben , thank you for your review. I've caught one regression and changed some style things Copilot noted and will force push in a moment.

For the approach started in #50935 , @NiceII didn't add a copyright line. Since this is not entirely mine and I continued their approach, I've changed the copyright addition (which I did to show it was no longer a 2020 file from one author) to add one for `The Zephyr Project Contributors` with 2025 instead of myself. This is my best reading of how to manage the mixed authorship. I will also provide them a coauthor credit and will force push in one minute.

**Comment by galaxyeden** [comment]
I have also updated the comments to use the shorter list of supported displays based on the [comment from MickiusMousius on Discord](https://discord.com/channels/720317445772017664/1075742162811105300/1400629202902057061)

**Comment by MickiusMousius** [comment]
Minor commentary here, I've done some testing of this update (under zephyr 3.5). Results below:

LS027B7DH01A - Works a treat, greatly improves contrast
LS013B7DH05 - Works a treat, noticeable improvement in contrast, bot as pronounced as above display type
LS011B7DH03 - Works well, some improvement in contrast but difference is marginal (display is much newer) 

I have observed that old displays improve contrast & have less power off ghosting after running with this update.

Display flickering is noticeable on LS013B7DH05 & LS027B7DH01A at anything less than 33ms refresh interval when viewed off axis. Using an interval of 17ms produces perfect results with excellent contrast.

There is no image corruption or apparent bus fighting.

Higher refresh rates do produce higher energy consumption, however this was testing to be 80uA in the worst case.

File: drivers/display/ls0xx.c [hunk 5]
```diff
@@ -1,46 +1,30 @@
 /*
  * Copyright (c) 2020 Rohit Gujarathi
+ * Copyright (c) 2025 The Zephyr Project Contributors
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c]:
```suggestion
 * SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
```

File: drivers/display/ls0xx.c [hunk 6]
```diff
@@ -1,46 +1,30 @@
...
  *
  * SPDX-License-Identifier: Apache-2.0
  */
 
-#define DT_DRV_COMPAT   sharp_ls0xx
+#define DT_DRV_COMPAT sharp_ls0xx
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c]: Please avoid mixing formatting changes with functional ones in the same commit, and avoid formatting changes completely if they are not required for CI.

File: drivers/display/ls0xx.c [hunk 7]
```diff
@@ -96,32 +68,82 @@ static int ls0xx_blanking_on(const struct device *dev)
...
 {
 	const struct ls0xx_config *config = dev->config;
-	uint8_t clear_cmd[2] = { LS0XX_BIT_CLEAR, 0 };
+	uint8_t clear_cmd[2] = {LS0XX_BIT_CLEAR, 0};
 	int err;
-
-	err = ls0xx_cmd(dev, clear_cmd, sizeof(clear_cmd));
+	if (k_mutex_lock(&ls0xx_spi_mutex, K_MSEC(240)) == 0) {
+		err = ls0xx_cmd(dev, clear_cmd, sizeof(clear_cmd));
+		k_usleep(374);
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c]: These sleep durations need to be defined as constants with meaningful names.

File: drivers/display/ls0xx.c [hunk 8]
```diff
@@ -50,25 +34,13 @@ struct ls0xx_config {
...
-	}
-}
-
-K_THREAD_STACK_DEFINE(vcom_toggle_stack, 256);
-struct k_thread vcom_toggle_thread;
-#endif
+/* This mutex is added to prevent display refreshes from being interrupted
+ * by commands mid-refresh
+ */
+K_MUTEX_DEFINE(ls0xx_spi_mutex);
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c]: A semaphore would do the job here.

**Review by JarmouniA — DISMISSED** [review]

File: drivers/display/ls0xx.c (hunk 8 above)
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: Thank you for your review @JarmouniA – why would a semaphore be preferable in this case? I used a mutex since it is a simple case of not wanting the bus to be accessed by the VCOM refresh thread while it is being accessed by the update display function. From a human perspective this is simpler to understand than a semaphore, but I'm not sure if I'm missing something in the efficiency of the resulting compiled code?

File: drivers/display/ls0xx.c (hunk 7 above)
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: I will do so! Thank you for pointing this out. These are also the values I tested with on a basis of "this is as long as seems reasonable to account for hardware" after a successful fix being a much lower value on the platforms I had. In truth I should define the end of command wait in ticks, not us, so I'll make some adjustments here and test again and they will be named!

File: drivers/display/ls0xx.c (hunk 6 above)
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: Okay, it seemed like a simple readability fix likely due to a typo or formatter error, but fully understood and I'll add the extra spaces back.

File: drivers/display/ls0xx.c (hunk 5 above)
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: Thank you for clarifying the best way to express this, I wasn't completely clear from my reading of the docs how to handle the case where the original file already had a year, I will update this.

File: drivers/display/ls0xx.c (hunk 8 above)
Comment (JarmouniA) [reply drivers/display/ls0xx.c]: Zephyr mutex has priority inherentence, which I don't think is needed here, and it is more costly than a semaphore.
https://docs.zephyrproject.org/latest/kernel/services/synchronization/mutexes.html#priority-inheritance

Comment (galaxyeden) [reply drivers/display/ls0xx.c]: Thanks @JarmouniA I'll get this changed and tested

**Comment by galaxyeden** [comment]
@JarmouniA thank you again for your review, that should be all of your comments addressed.

File: drivers/display/ls0xx.h
Comment (JarmouniA) [inline drivers/display/ls0xx.h:1]: A separate header file should not be needed.

File: dts/bindings/display/sharp,ls0xx.yaml [hunk 9]
```diff
@@ -45,3 +45,19 @@ properties:
...
+      Enable when EXTCOMIN is not configured and VCOM inversion is not
+      application-managed.
+
+  serial-vcom-interval:
+    type: int
+    description: Serial VCOM inversion interval
+
+      VCOM inversion interval in milliseconds. This value is used when
+      there is no EXTCOMIN configured and serial-vcom inversion is set.
+      If not configured, 1000ms will be used.
```
Comment (JarmouniA) [inline dts/bindings/display/sharp,ls0xx.yaml]: the default value should be defined here instead of in the driver.

File: drivers/display/ls0xx.c [hunk 10]
```diff
@@ -96,32 +68,82 @@ static int ls0xx_blanking_on(const struct device *dev)
...
+
+#if DT_INST_PROP(0, serial_vcom_inversion)
+	struct ls0xx_data *data = dev->data;
 
-	return spi_write_dt(&config->bus, &buf_set);
+	buf[0] |= data->vcom_state ? LS0XX_BIT_VCOM : 0;
+	data->vcom_state = !data->vcom_state;
+#endif /* DT_INST_PROP(0, serial_vcom_inversion) */
+	ret = spi_write_dt(&config->bus, &buf_set);
+	return ret;
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c]: `ret` is not needed

File: drivers/display/ls0xx.c [hunk 11]
```diff
@@ -96,32 +68,82 @@ static int ls0xx_blanking_on(const struct device *dev)
...
+
+K_THREAD_STACK_DEFINE(vcom_toggle_stack, 512);
+struct k_thread vcom_toggle_thread;
+#endif /* USE_VCOM_THREAD */
+
 static int ls0xx_clear(const struct device *dev)
 {
 	const struct ls0xx_config *config = dev->config;
-	uint8_t clear_cmd[2] = { LS0XX_BIT_CLEAR, 0 };
+	uint8_t clear_cmd[2] = {LS0XX_BIT_CLEAR, 0};
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c]: unrelated formatting change

File: drivers/display/ls0xx.c [hunk 12]
```diff
@@ -96,32 +68,82 @@ static int ls0xx_blanking_on(const struct device *dev)
...
+	if (k_sem_take(&ls0xx_bus_sem, K_MSEC(LS0XX_MAX_BUS_WAIT_MSEC)) == 0) {
+		err = ls0xx_cmd(dev, clear_cmd, sizeof(clear_cmd));
+	} else {
+		LOG_ERR("memory display semaphore not available - data");
+		err = -EBUSY;
+	}
+	k_sleep(K_TICKS(LS0XX_BUS_RETURN_DELAY_TICKS));
+	k_sem_give(&ls0xx_bus_sem);
 	spi_release_dt(&config->bus);
-
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c:114]: 0unrelated formatting change

File: drivers/display/ls0xx.c [hunk 13]
```diff
@@ -96,32 +68,82 @@ static int ls0xx_blanking_on(const struct device *dev)
...
 	return err;
 }
 
-static int ls0xx_update_display(const struct device *dev,
-				uint16_t start_line,
-				uint16_t num_lines,
+static int ls0xx_update_display(const struct device *dev, uint16_t start_line, uint16_t num_lines,
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c]: unrelated formatting change

**Review by JarmouniA — COMMENTED** [review]
I didn't point out all instances of unrelated formatting changes.

File: drivers/display/ls0xx.h
Comment (galaxyeden) [reply drivers/display/ls0xx.h:1]: I did this as it felt like the defines were getting a bit too long since I merged them back in. I think all of the rest came from running `clang-format` with the settings in Zephyr, I'll merge the headers back in and go through the other places `clang-format` changed.

File: dts/bindings/display/sharp,ls0xx.yaml (hunk 9 above)
Comment (galaxyeden) [reply dts/bindings/display/sharp,ls0xx.yaml]: #25164 led me to believe that using `default` was advised against, but I will change this per your request

File: drivers/display/ls0xx.c (hunk 10 above)
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: I think it's better to be aware of errors in this, but also that I should log an error if the return from the write is an error, thoughts? I'll also change it to `err` for consistency with other error code return values in the driver.

**Comment by galaxyeden** [comment]
> I didn't point out all instances of unrelated formatting changes.

These are addressed, most of them were what the `clang-format` output did with the `clang-format` settings defined in Zephyr.

File: drivers/display/ls0xx.c [hunk 14]
```diff
@@ -96,20 +102,77 @@ static int ls0xx_blanking_on(const struct device *dev)
 
 static int ls0xx_cmd(const struct device *dev, uint8_t *buf, uint8_t len)
 {
+	int err;
+
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c]:
```suggestion
```

File: drivers/display/ls0xx.c [hunk 15]
```diff
@@ -96,20 +102,77 @@ static int ls0xx_blanking_on(const struct device *dev)
...
+#endif /* USE_VCOM_THREAD */
+
 static int ls0xx_clear(const struct device *dev)
 {
 	const struct ls0xx_config *config = dev->config;
 	uint8_t clear_cmd[2] = { LS0XX_BIT_CLEAR, 0 };
 	int err;
-
-	err = ls0xx_cmd(dev, clear_cmd, sizeof(clear_cmd));
+	if (k_sem_take(&ls0xx_bus_sem, K_MSEC(LS0XX_MAX_BUS_WAIT_MSEC)) == 0) {
```
Comment (JarmouniA) [inline drivers/display/ls0xx.c:168]:
```suggestion

	if (k_sem_take(&ls0xx_bus_sem, K_MSEC(LS0XX_MAX_BUS_WAIT_MSEC)) == 0) {
```

Comment (galaxyeden) [reply drivers/display/ls0xx.c:168]: Done, will push shortly

File: drivers/display/ls0xx.c (hunk 14 above)
Comment (galaxyeden) [reply drivers/display/ls0xx.c]: Done

**Comment by galaxyeden** [comment]
@JarmouniA I've made the line spacing changes you requested

File: dts/bindings/display/sharp,ls0xx.yaml [hunk 16]
```diff
@@ -45,3 +45,22 @@ properties:
       The DISPLAY pin controls if the LCD displays memory contents or
       white screen. If defined, the pin will be set high during driver
       initialization. display blanking apis can be used to control it.
+
+  serial-vcom-inversion:
+    type: boolean
+    description: Send serial VCOM inversion commands
+
+      Driver creates a thread to send inversion commands over SPI.
```
Comment (JarmouniA) [inline dts/bindings/display/sharp,ls0xx.yaml]:
```suggestion
```

**Comment by JarmouniA** [comment]
Cc @everedero

File: dts/bindings/display/sharp,ls0xx.yaml (hunk 16 above)
Comment (galaxyeden) [reply dts/bindings/display/sharp,ls0xx.yaml]: This is reasonable as I can see the redundancy with the short description. I've deleted this line, rebased against current `main` as it has been a few weeks, and force-pushed.

I had written this with the redundancy to match other descriptions in the driver stylistically, for example the description for `extcomin-frequency`.

Comment (JarmouniA) [reply dts/bindings/display/sharp,ls0xx.yaml]: HW device's binding shouldn't be talking about software stuff.

**Review by JarmouniA — APPROVED** [review]

**Comment by galaxyeden** [comment]
@kartben I was wondering if you had a minute to look at this again? I know of quite a few implementations of this display on Zephyr devices that could lead to display damage, used with applications that don't implement this on the application level so I'm excited to see this addressed within Zephyr. Thank you for your time!

**Comment by JarmouniA** [comment]
@galaxyeden Could you file a bug issue describing what this PR is fixing? So that we may merge this in the stabilization period.

**Comment by galaxyeden** [comment]
> @galaxyeden Could you file a bug issue describing what this PR is fixing? So that we may merge this in the stabilization period.

@JarmouniA thanks, I've opened https://github.com/zephyrproject-rtos/zephyr/issues/98271

**Review by VynDragon — APPROVED** [review]
