### PR TITLE
kernel: sched: Use k_ticks_t in z_tick_sleep

### LINKED ISSUE #29066: kernel: k_sleep doesn't handle relative or absolute timeouts >INT_MAX
**Describe the bug**

The primary sleep function `z_tick_sleep` in `kernel/sched.c` does not respect the type of `k_ticks_t`, instead using `int32_t`.
There are two main consequences of this:

1. Sleeps of tick duration greater than `INT_MAX` will not behave properly.
2. Absolute timeouts fail after `INT_MAX` ticks (18 hours on nRF).

In the second case, timout.ticks will have some value less than `INT_MIN`. This becomes a postive number near `INT_MAX` after being cast to `int32_t`. The `Z_TICK_ABS` check in `z_add_timeout` fails, resulting in a sleep of approximately 18hrs being scheduled, instead of ~1 second.

**To Reproduce**

Initialize `curr_tick` in `kernel\timeout.c` to just before rollover:
```
static uint64_t curr_tick = INT32_MAX - 320000;
``` 
Modify the main loop of `samples\basic\blinky` to the following:
```
	int64_t timeout = k_uptime_get() + 1000;

	while (1) {
		k_sleep(K_TIMEOUT_ABS_MS(timeout));
		timeout += 1000;

		gpio_pin_set(dev, PIN, (int)led_is_on);
		led_is_on = !led_is_on;
	}
```
On NRF boards, the LED will stop blinking after ~10 seconds.

**Expected behavior**
Absolute timeouts (and large relative timeouts) should delay for the specified duration.

**Impact**
High priority/showstopper, I use absolute timeouts to mitigate drift in our main loop.
This bug means the watchdog is rebooting my application every 18 hours.

**Logs and console output**
By adding `printk("Ticks: %lld %lld\n", ticks, Z_TICK_ABS(ticks));` to `z_add_timeout`
```
Ticks: -2147324823 2147324821
Ticks: -2147357591 2147357589
Ticks: -2147390359 2147390357
Ticks: -2147423127 2147423125
Ticks: -2147455895 2147455893
Ticks: 2147478633 -2147478635
```

**Environment (please complete the following information):**
- Zephyr 2.4

### PR DESCRIPTION
**Pull request by ceolin**
z_tick_sleep was using int32_t what could cause a possible overflow
when converting from k_ticks_t.

Fixes #29066

### CODE REVIEW

**Comment by ceolin** [comment]
@andyross any idea how to exercise this issue ? I reproduced the problem hardcoding `curr_tick` to overflow, but this is not exposed at all.

File: kernel/sched.c [hunk 1]
```diff
@@ -1237,14 +1237,18 @@ static inline void z_vrfy_k_yield(void)
...
+static int32_t z_tick_sleep(k_ticks_t ticks)
 {
 #ifdef CONFIG_MULTITHREADING
 	uint32_t expected_wakeup_time;
 
 	__ASSERT(!arch_is_in_isr(), "");
 
-	LOG_DBG("thread %p for %d ticks", _current, ticks);
+#ifdef CONFIG_TIMEOUT_64BIT
+	LOG_DBG("thread %p for %lld ticks", _current, ticks);
```
Comment (JordanYates) [inline kernel/sched.c:1248]: This will select the correct format specifier independent of the system.
```suggestion
	LOG_DBG("thread %p for " PRId64 " ticks", _current, ticks);
```

File: kernel/sched.c [hunk 2]
```diff
@@ -1258,7 +1262,7 @@ static int32_t z_tick_sleep(int32_t ticks)
 	timeout = Z_TIMEOUT_TICKS(ticks);
 #else
 	ticks += _TICK_ALIGN;
-	timeout = (k_ticks_t) ticks;
+	timeout = ticks;
```
Comment (JordanYates) [inline kernel/sched.c:1265]: Should this also be `Z_TIMEOUT_TICKS` rather than casting the int to a struct

Comment (ceolin) [reply kernel/sched.c:1265]: yep, I missed that we had it to legacy api, just changing it. Thanks for pointing it out.

File: kernel/sched.c [hunk 3]
```diff
@@ -1237,14 +1238,18 @@ static inline void z_vrfy_k_yield(void)
...
+static int32_t z_tick_sleep(k_ticks_t ticks)
 {
 #ifdef CONFIG_MULTITHREADING
 	uint32_t expected_wakeup_time;
 
 	__ASSERT(!arch_is_in_isr(), "");
 
-	LOG_DBG("thread %p for %d ticks", _current, ticks);
+#ifdef CONFIG_TIMEOUT_64BIT
+	LOG_DBG("thread %p for %" PRId64 " ticks", _current, ticks);
```
Comment (JordanYates) [inline kernel/sched.c:1249]: I forgot that the logger API doesn't support 64bit values regardless of the format string.
The xtensa platform should probably be added back in, and this print excluded for 64bit?
Or perhaps print out the value mod 2**31 here.

Comment (ceolin) [reply kernel/sched.c:1249]: Sorry the whole logging subsystem does not support 64 bit or the problem is xtensa specific ? AFAIU the problem is in xtensa SDK, PRI*64 is not being properly defined there. If that is the case I think is fine just exclude the platform from the test. This problem is being addressed in the next SDK release AFAIK.

Comment (pabigot) [reply kernel/sched.c:1249]: The logging API doesn't support 64-bit values period.  https://github.com/zephyrproject-rtos/zephyr/issues/18351#issuecomment-522276594

Comment (ceolin) [reply kernel/sched.c]: Thanks ! Just logging it conditionally now.

**Comment by ceolin** [comment]
@andyross  could you take a look on it ?

File: kernel/sched.c [hunk 4]
```diff
@@ -1237,14 +1237,19 @@ static inline void z_vrfy_k_yield(void)
 #include <syscalls/k_yield_mrsh.c>
 #endif
 
-static int32_t z_tick_sleep(int32_t ticks)
+static int32_t z_tick_sleep(k_ticks_t ticks)
 {
 #ifdef CONFIG_MULTITHREADING
 	uint32_t expected_wakeup_time;
```
Comment (martinjaeger) [inline kernel/sched.c:1243]:
```suggestion
	uint32_t expected_wakeup_ticks;
```

**Review by martinjaeger — CHANGES_REQUESTED** [review]
We recently encountered this overflow issue in our application when using `k_sleep(K_TIMEOUT_ABS_MS(...));` and I was very happy to find this PR. Thanks for the fix.

I tested it over the weekend an can confirm that it works. Just got one suggestion for more clear variable naming, so that we don't confuse timeouts with ticks.

**Review by martinjaeger — APPROVED** [review]

File: kernel/sched.c [hunk 5]
```diff
@@ -1237,14 +1237,19 @@ static inline void z_vrfy_k_yield(void)
...
+	uint32_t expected_wakeup_ticks;
 
 	__ASSERT(!arch_is_in_isr(), "");
 
-	LOG_DBG("thread %p for %d ticks", _current, ticks);
+#ifndef CONFIG_TIMEOUT_64BIT
+	/* LOG subsys does not handle 64-bit values
+	 * https://github.com/zephyrproject-rtos/zephyr/issues/26246
+	 */
+	LOG_DBG("thread %p for %u ticks", _current, ticks);
```
Comment (andyross) [inline kernel/sched.c:1251]: Why bother with %u vs. %d?  Both are lossy in this circumstance.

**Review by andyross — APPROVED** [review]
Looks correct

**Review by pabigot — APPROVED** [review]

File: kernel/sched.c (hunk 2 above)
Comment (mniestroj) [reply kernel/sched.c]: The initial change was correct. There was no casting to structure, because modified line was executed when `CONFIG_LEGACY_TIMEOUT_API=y`.

Fix in #30842.

**Comment by kurddt** [comment]
@ceolin I ran into this issue. Do you think it's reasonably "safe" to apply 7a815d5d993d4ae71dd0a2ec54dc23235345934d on top of zephyr 2.4 ?
