### PR TITLE
Bluetooth: Host: Fix invalid pointer in bt_smp_pkey_ready

### LINKED ISSUE #18580: Bluetooth: Security fail on initial pairing
**Describe the bug**
Problem occurrs when connecting 2 Zephyr devices (central and peripheral). Devices are erased, then flashed. On first connection try, there are following errors in logs:

```
CENTRAL:
bt_hci_ecc: public key is not valid (ret -3)
bt_smp: Unexpected SMP code 0x04
```
```
PERIPHERAL:
bt_smp: reason 0x4
```
On next reconnection try, devices are able to pair properly and security level is set to 2 (everything works as expected).

**Expected behavior**
Initial pairing used to work wihout problems.

**Impact**
Problems when connecting 2 Zephyr devices using Bluetooth.

**Environment**
 - Zephyr SDK 0.10.1
 - Commit SHA: 882503f9130359125d6890ad7fe7e792abf751ba

**Additional context**

- Problem was not reproduced when connecting to peripheral with other (non Zephyr) central (tested with Windows 10).

### PR DESCRIPTION
**Pull request by joerchan**
The storage for the public key is pub_key in hci_core.c.
When the public key event is generated the public key is copied into
this buffer, but the pointer to the event storage of the key is given
in the public key ready callback (bt_smp_pkey_ready).
SMP expects that it is safe to assign a global pointer to this variable.
In smp_init bt_pub_key_get is used to get the pointer to the public key.
In both cases SMP assigns the le_sc_pub_key to the pointer given.
    
This creates an issue when bt_smp_pkey_ready callback occurs after
smp_init during pairing procedure, SMP will then have a pointer to an
event buffer that has been released and contains invalid data.
    
Fixes: #18580

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -3271,7 +3271,7 @@ static void le_pkey_complete(struct net_buf *buf)
 	}
 
 	for (cb = pub_key_cb; cb; cb = cb->_next) {
-		cb->func(evt->status ? NULL : evt->key);
+		cb->func(evt->status ? NULL : pub_key);
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: Actually, can you explain why evt->key is invalid? In the case that we got a zero status it should contain the valid new key. Could you also add this info to the commit message? (assuming I'm not missing something obvious here)

Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c]: Updated commit message and PR description.

Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c]: @joerchan that clarifies it, thanks!
