### PR TITLE
usb: usb_c: fix missing DPM notifications on PD attach and detach

### LINKED ISSUE #105687: usb_c: No DPM notification on port detach
## Summary

The USB-C stack does not notify the Device Policy Manager (DPM) when a port transitions from attached to unattached. This makes it impossible for an application to know when to reduce current consumption back to the default level after a detach event.

## Expected Behavior

A `usbc_policy_notify_t` notification should be sent to the DPM callback when the port detaches, allowing the application to respond (e.g. reduce current draw, disable power rails).

## Actual Behavior

No notification is sent to the DPM upon detach. The following sequence is observed when attaching and then detaching a PD charger:

```c
// Attach
[00:00:20.645,000] <inf> main: NOTIFY:POWER_ROLE_IS_SINK
[00:00:20.645,000] <inf> main: NOTIFY:NOT_PD_CONNECTED
[00:00:20.667,000] <inf> main: NOTIFY:POWER_CHANGE_3A0
[00:00:20.733,000] <inf> main: NOTIFY:SOURCE_CAPABILITIES_RECEIVED
[00:00:20.733,000] <inf> main: NOTIFY:PD_CONNECTED
[00:00:20.868,000] <inf> main: NOTIFY:TRANSITION_PS

// Detach
// No notifications to DPM
```

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Build and flash the `samples/subsys/usb_c/sink` sample to a board with a USB-C port and TCPC (e.g. `stm32g081b_eval`).
2. In `port0_notify()`, add a log for every `usbc_policy_notify_t` value so all notifications are visible on the serial console (or use the updated sink sample which already does this).
3. Open a serial terminal connected to the board.
4. Connect a PD charger. 
5. Disconnect the PD charger.

Observe: No notifications are printed. The DPM callback is never called on detach.

### Relevant log output

```shell
// Attach
[00:00:20.645,000] <inf> main: NOTIFY:POWER_ROLE_IS_SINK
[00:00:20.645,000] <inf> main: NOTIFY:NOT_PD_CONNECTED
[00:00:20.667,000] <inf> main: NOTIFY:POWER_CHANGE_3A0
[00:00:20.733,000] <inf> main: NOTIFY:SOURCE_CAPABILITIES_RECEIVED
[00:00:20.733,000] <inf> main: NOTIFY:PD_CONNECTED
[00:00:20.868,000] <inf> main: NOTIFY:TRANSITION_PS

// Detach
// No notifications to DPM
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ncadieux**
__Description:__

Fixes #105687

The USB-C stack was not notifying the Device Policy Manager (DPM) in several attach and detach scenarios when using a PD-capable port partner. The following identified issues are resolved by this PR: 

On SNK detach, `sink_power_sub_states()` which sends `POWER_CHANGE_0A0` is bypassed during an explicit PD contract. Additionally, `pe_suspend_entry()` did not notify `NOT_PD_CONNECTED` or clear the explicit contract flag when the Policy Engine was suspended due to a detach event.

- [x] Fix by notifying `POWER_CHANGE_0A0` in `tc_attached_snk_exit()`, and notifying `NOT_PD_CONNECTED` and clearing `PE_FLAGS_EXPLICIT_CONTRACT` in `pe_suspend_entry()`.

On SRC connect, `PD_CONNECTED` was not sent to the DPM after a PD Request was received from the attached sink.
- [x] Fix by notifying `PD_CONNECTED` in `pe_src_negotiate_capability_entry()`.

On PD capable SNK or SRC detach, `pe_suspend_entry()` did not clear the explicit contract flag. 
- [x] Fix by clearing `PE_FLAGS_EXPLICIT_CONTRACT` in `pe_suspend_entry()`.

__Validation__

Tested on `stm32g081b_eval` using the `samples/subsys/usb_c/drp` sample with `LOG_INF()` added for all DPM notification cases. The following four scenarios were validated:

PD Source Attach / Detach

```javascript
// Attach PD Source
main: NOTIFY:POWER_ROLE_IS_SINK
main: NOTIFY:NOT_PD_CONNECTED
main: NOTIFY:POWER_CHANGE_3A0
main: NOTIFY:SOURCE_CAPABILITIES_RECEIVED
main: NOTIFY:TRANSITION_PS
main: NOTIFY:PD_CONNECTED
// Detach PD Source
main: NOTIFY:NOT_PD_CONNECTED
main: NOTIFY:POWER_CHANGE_0A0
```

PD Sink Attach / Detach

```javascript
// Attach PD Sink
main: NOTIFY:POWER_ROLE_IS_SOURCE
main: NOTIFY:NOT_PD_CONNECTED
main: NOTIFY:TRANSITION_PS
main: NOTIFY:PD_CONNECTED
main: NOTIFY:MSG_NOT_SUPPORTED_RECEIVED
// Detach PD Sink
main: NOTIFY:NOT_PD_CONNECTED
```

Type-C Source Attach / Detach

```javascript
// Attach Type-C Source
main: NOTIFY:POWER_ROLE_IS_SINK
main: NOTIFY:NOT_PD_CONNECTED
main: NOTIFY:POWER_CHANGE_DEF
... (SinkWaitCap retries)
main: NOTIFY:PORT_PARTNER_NOT_RESPONSIVE
// Detach Type-C Source
main: NOTIFY:POWER_CHANGE_0A0
main: NOTIFY:NOT_PD_CONNECTED
main: NOTIFY:POWER_CHANGE_0A0
```

Type-C Sink Attach / Detach

```javascript
// Attach Type-C Sink
main: NOTIFY:POWER_ROLE_IS_SOURCE
main: NOTIFY:NOT_PD_CONNECTED
// Detach Type-C Sink
main: NOTIFY:NOT_PD_CONNECTED
```

### CODE REVIEW

File: subsys/usb/usb_c/usbc_pe_src_states.c [hunk 1]
```diff
@@ -268,6 +269,9 @@ void pe_src_negotiate_capability_entry(void *obj)
 	/* Get sink request */
 	pe->snk_request = *(uint32_t *)prl_rx->emsg.data;
 
+	/* Inform Device Policy Manager that we are PD Connected */
+	policy_notify(dev, PD_CONNECTED);
```
Comment (alexanderwachter) [inline subsys/usb/usb_c/usbc_pe_src_states.c]: Shouldn't this be under the valid request? Or is the pd also meant to be connected if the contract is not established?

**Review by alexanderwachter — COMMENTED** [review]
Thank for this fix. Just a minor comment

File: subsys/usb/usb_c/usbc_pe_src_states.c (hunk 1 above)
Comment (ncadieux) [reply subsys/usb/usb_c/usbc_pe_src_states.c]: The intention was to notify `PD_CONNECTED` when we know the port partner supports PD. This was consistent with the existing Sink mode behavior in `pe_snk_select_capability_entry()`, which notifies `PD_CONNECTED` after receiving the `Source_Capabilities` message but before the explicit contract is actually established. On the Source side, the symmetric point is when the `Request` is received from the Sink, which is the earliest point we know the Sink supports PD.

However, looking at the `PD_CONNECTED` definition in `usbc.h`, there is a contradiction between the current Sink implementation and the enum's documentation, which indicates `PD_CONNECTED` should only be used when an explicit contract is established:

```c
	/** A PD Explicit Contract is in place */
	PD_CONNECTED,
	/** No PD Explicit Contract is in place */
	NOT_PD_CONNECTED,
```

In my opinion, it makes more sense to follow the documentation and only notify `PD_CONNECTED` when an explicit contract is fully established. This ensures the DPM only initiates requests like Power Role Swap, Vconn Swap, and Data Role Swap when it is actually valid to do so.

I will amend the commit to update both `usbc_pe_snk_states.c` and `usbc_pe_src_states.c` so that `PD_CONNECTED` is strictly notified only when a new explicit contract is established.

**Review by alexanderwachter — DISMISSED** [review]

File: subsys/usb/usb_c/usbc_pe_src_states.c [hunk 2]
```diff
@@ -396,6 +393,26 @@ enum smf_state_result pe_src_ready_run(void *obj)
...
 	struct usbc_port_data *data = dev->data;
 	struct protocol_layer_rx_t *prl_rx = data->prl_rx;
+	struct protocol_layer_tx_t *prl_tx = data->prl_tx;
+
+	/*
+	 * Check if PS_RDY was successfully transmitted, which establishes
+	 * the explicit contract.
+	 */
+	if (atomic_test_and_clear_bit(pe->flags, PE_FLAGS_TX_COMPLETE)) {
+		if (prl_tx->msg_type == PD_CTRL_PS_RDY) {
```
Comment (keith-zephyr) [inline subsys/usb/usb_c/usbc_pe_src_states.c]: Please combine the if statements.

**Review by keith-zephyr — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]
