### PR TITLE
xtensa: mmu: add assertions and system halting point if there are not enough free L2 tables to be allocated

### LINKED ISSUE #101339: xtensa: ace 3.0: Unchecked error leads to exception
### Describe the bug

Allocation at https://github.com/zephyrproject-rtos/zephyr/blob/c3190d34aa912d39cd082db822f6ebb332806a2b/arch/xtensa/core/ptables.c#L1081 can fail, which then leads to an exception. The result should be checked and handled instead, at least with an assertion.

Further, if a new domain with a new L1 page table has been allocated with no mappings, then memory gets mapped so that that new domain is also updated, this line https://github.com/zephyrproject-rtos/zephyr/blob/c3190d34aa912d39cd082db822f6ebb332806a2b/arch/xtensa/core/ptables.c#L1072 will return `NULL` which then also will lead to an exception. When that is fixed by
```
@@ -1136,6 +1136,8 @@ static void dup_l2_table_if_needed(uint32_t *l1_table, uint32_t l1_pos)
 	uint32_t *l2_table, *src_l2_table;
 
 	src_l2_table = (uint32_t *)PTE_PPN_GET(l1_table[l1_pos]);
+	if (!src_l2_table)
+		return;
 
 	if (l2_page_tables_counter[l2_table_to_counter_pos(src_l2_table)] == 1) {
 		/* Only one user of L2 table, no need to duplicate. */
```
another exception occurs later when unmapping that memory

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dcpleung**
This adds some assertions when there are not enough free L2 page tables to be allocated. And adds system halting point after these assertions in case assertion is disabled via kconfigs.

Also adds debug logging on page table pool usage during de-/allocation so that there are some visual clues on whether there are enough tables in the pool.

Fixes #101339

### CODE REVIEW

File: arch/xtensa/core/ptables.c [hunk 1]
```diff
@@ -968,8 +968,14 @@ static uint32_t *dup_l2_table(uint32_t *src_l2_table, enum dup_action action)
 	uint32_t *l2_table;
 
 	l2_table = alloc_l2_table();
+
+	/* Duplicating L2 tables is a must-have and must-success operation.
+	 * If we are running out of free L2 tables to be allocated, we cannot
+	 * continue.
+	 */
+	__ASSERT_NO_MSG(l2_table != NULL);
```
Comment (lgirdwood) [inline arch/xtensa/core/ptables.c:976]: There may be occasion where this will be non fatal for the application. i.e. user request to allocate resources when there are no resources free should be survivable and allow user/upper level application to handle.

File: arch/xtensa/core/ptables.c [hunk 2]
```diff
@@ -407,6 +407,15 @@ static void map_memory_range(const uint32_t start, const uint32_t end,
 			__ASSERT(l2_table != NULL,
 				 "There is no l2 page table available to map 0x%08x\n", page);
 
+			if (l2_table == NULL) {
+				/* This function is called during boot. If this cannot
+				 * properly map all predefined memory regions, it is very
+				 * unlikely for anything to run correctly. So forcibly
+				 * halt the system in case assertion has been turned off.
+				 */
+				arch_system_halt(K_ERR_KERNEL_PANIC);
```
Comment (lgirdwood) [inline arch/xtensa/core/ptables.c:416]: I assume this will show as a panic in the logs ?

**Review by lgirdwood — COMMENTED** [review]
Just a few opens. @lyakh pls review

File: arch/xtensa/core/ptables.c (hunk 2 above)
Comment (lyakh) [reply arch/xtensa/core/ptables.c:416]: in principle `init_page_table()` below will trigger an exception anyway, but doesn't hurt having it explicit either

File: arch/xtensa/core/ptables.c (hunk 1 above)
Comment (dcpleung) [reply arch/xtensa/core/ptables.c:976]: Currently, it is not possible to recover fully as we do not have the mechanism to undo any changes to page tables up to the failure point. The already modified PTEs would not be reverted to previous states which may have security implications. So it is better to halt the system instead.

**Review by ceolin — APPROVED** [review]

File: arch/xtensa/core/ptables.c (hunk 2 above)
Comment (dcpleung) [reply arch/xtensa/core/ptables.c:416]: We can only reach this if you have assertion turned off. Besides, this is the last line of defense, and we usually should have bailed out earlier.

**Review by peter-mitsis — APPROVED** [review]

**Review by edersondisouza — APPROVED** [review]
