### PR TITLE
drivers: mcux_flexspi: Removing Logging Statements from FlexSPI driver

### LINKED ISSUE #39340: Shell FS sample halts with a usage fault error
**Describe the bug**
After flashing the shell filesystem example (samples/subsys/shell/fs) on an MIMXRT1064 evk, the example halts and prints a usage fault error. This bug reproduces on the latest version of the main branch, but not on v2.7.0-rc4. The bug first appears at commit 0a50ebed013e3fe2a31f94d8564b3292dc6d5fbd.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mimxrt1064_evk ../samples/subsys/shell/fs
3. make

**Expected behavior**
The UART shell should start and display the `uart:~$` prompt

**Logs and console output**
Here is what the console outputs after the usage fault:
```
*** Booting Zephyr OS build v2.7.99-84-g851cccb67efd  ***

[00:00:00.005,000] <err> os: ***** USAGE FAULT *****
[00:00:00.005,000] <err> os:   Illegal use of the EPSR 
[00:00:00.005,000] <err> os: r0/a1:  0x00000000  r1/a2:  0x70012550  r2/a3:  0x00000003
[00:00:00.005,000] <err> os: r3/a4:  0x00000000 r12/ip:  0xaaaaaaaa r14/lr:  0x70006e3f
[00:00:00.005,000] <err> os:  xpsr:  0x20000024
[00:00:00.005,000] <err> os: Faulting instruction address (r15/pc): 0x00000000
[00:00:00.005,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.005,000] <err> os: Fault during interrupt handling
[00:00:00.005,000] <err> os: Current thread: 0x80000430 (shell_uart)
[00:00:00.047,000] <err> os: Halting system
```

**Environment:**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit 0a50ebed013e3fe2a31f94d8564b3292dc6d5fbd

**Additional Context**
The issue appears to only occur in the filesystem shell example. It does not occur in other shell examples, and enabling the shell in the "hello world" example did not trigger the bug.

### LINKED ISSUE #40133: mimxrt1060-evk flash shell command causes shell deadlock
**Describe the bug**
After building and flashing smp_sv shell sample on mimxrt1060-evk the `flash` shell command causes a deadlock in the shell.

**To Reproduce**
Build and run smp-svr shell sample application.

**Expected behavior**
The correct flash shell command output:

<pre>
uart:~$ flash
flash: wrong parameter count
flash - Flash shell commands
Subcommands:
  erase  :[<device>] <page address> [<size>]
  read   :[<device>] <address> [<Dword count>]
  test   :[<device>] <address> <size> <repeat count>
  write  :[<device>] <address> <dword> [<dword>...]
</pre>

**Logs and console output**

<pre>
*** Booting Zephyr OS build v2.7.99-931-gf90b24536184  ***
I: Starting bootloader
I: Primary image: magic=good, swap_type=0x1, copy_done=0x3, image_ok=0x1
I: Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: primary slot
I: Swap type: none
I: Bootloader chainload address offset: 0x10000
I: Jumping to the first image slot
*** Booting Zephyr OS build v2.7.99-931-gf90b24536184  ***

uart:~$ flash

</pre>

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Toolchain Zephyr SDK 0.13.1
 - v2.7.99-931-gf90b24536184

**Additional context**
 Sometimes for unknown reasons, I was also getting kernel panic such as:

<pre>
uart:~$ flash
[00:00:05.980,000] <err> os: ***** USAGE FAULT *****
[00:00:05.980,000] <err> os:   Illegal use of the EPSR
[00:00:05.980,000] <err> os: r0/a1:  0x60029c60  r1/a2:  0x00000001  r2/a3:  0x80007ca4
[00:00:05.980,000] <err> os: r3/a4:  0x00000040 r12/ip:  0x00000000 r14/lr:  0x6001530b
[00:00:05.980,000] <err> os:  xpsr:  0x60000000
[00:00:05.980,000] <err> os: Faulting instruction address (r15/pc): 0x00000040
[00:00:05.980,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:05.980,000] <err> os: Current thread: 0x80002c28 (shell_uart)
[00:00:05.988,000] <err> os: Halting system
</pre>

### PR DESCRIPTION
**Pull request by danieldegrasse**
Program flow will behave in undefined ways if the ARM core in NXP  i.MXRT parts attempts to access the flash memory using XIP while the flexspi driver is writing to or reading from flash. The undefined behavior manifests in a variety of ways, such as in #39340, where a load from flexspi memory returns 0x0 (and the subsequent branch causes a usage fault), or in #40133, where the program loads a garbage memory address and branches to it.

The flexspi driver itself is relocated to ITCM at runtime using `zephyr_code_relocate` macros, but the driver makes calls to the logging subsystem, which is linked into XIP flash memory. The simplest solution I can see is to remove all logging statement from the flexspi driver. Alternatively, the logging subsystem (and any logging backends) could all be linked to ITCM, but this seems likely to end up introducing new errors, as any new logging subsystem would also need to be properly relocated to ITCM.

Fixes #40133
Fixes #39340

### CODE REVIEW

**Comment by Laczen** [comment]
@danieldegrasse, would it not be simpler to disable logging in case of XIP:
```
#include <logging/log.h>
#ifdef CONFIG_FLASH_MCUX_FLEXSPI_XIP
LOG_MODULE_REGISTER(flexspi_hyperflash, 0);
#else
LOG_MODULE_REGISTER(flexspi_hyperflash, CONFIG_FLASH_LOG_LEVEL);
#endif
```

**Comment by danieldegrasse** [comment]
@Laczen It would be simpler, thanks for the suggestion. I've switched the PR to use that approach.

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Quietly ignoring `CONFIG_FLASH_LOG_LEVEL` could cause confusion for someone debugging this driver, it would be better to override the default instead. Something like this in `soc/arm/nxp_imx/rt/Kconfig.defconfig.series`:
```
# Avoid RWW hazards
config FLASH_LOG_LEVEL
	default 0 if FLASH_MCUX_FLEXSPI_XIP
	depends on FLASH
```

**Comment by MaureenHelm** [comment]
And as an added safeguard, you may also want to add a build warning or error to the driver, in the event that someone sets `CONFIG_FLASH_LOG_LEVEL` in their prj.conf or at the command line:

```c
#if defined(FLASH_MCUX_FLEXSPI_XIP) && (CONFIG_FLASH_LOG_LEVEL > 0)
#warning "Enabling flash driver logging and XIP mode simultaneously can cause read-while-write hazards. This configuration is not recommended.
#endif
```

**Comment by de-nordic** [comment]
> 
> 
> And as an added safeguard, you may also want to add a build warning or error to the driver, in the event that someone sets `CONFIG_FLASH_LOG_LEVEL` in their prj.conf or at the command line:
> 
> ```c
> #if defined(FLASH_MCUX_FLEXSPI_XIP) && (CONFIG_FLASH_LOG_LEVEL > 0)
> #warning "Enabling flash driver logging and XIP mode simultaneously can cause read-while-write hazards. This configuration is not recommended.
> #endif
> ```

Maybe we should consider this an error that can be squashed by special Kconfig option, something like "FLASH_LOG_I_KNOW_FLEXSPI_MAY_BREAK_WITH_IT", so that user would have to acknowledge that this might be problem.

**Review by dleach02 — APPROVED** [review]

File: drivers/flash/flash_mcux_flexspi_hyperflash.c [hunk 1]
```diff
@@ -11,12 +11,25 @@
...
+	read-while-write hazards. This configuration is not recommended."
+#endif
+
 LOG_MODULE_REGISTER(flexspi_hyperflash, CONFIG_FLASH_LOG_LEVEL);
 
 #ifdef CONFIG_HAS_MCUX_CACHE
 #include <fsl_cache.h>
 #endif
 
+
```
Comment (bbilas) [inline drivers/flash/flash_mcux_flexspi_hyperflash.c:32]: It doesn't seem to be needed.

**Review by bbilas — APPROVED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Code changes look good, but the commit message doesn't match anymore. Can you update it to say that you're disabling logging under certain conditions, rather than removing logging altogether?

**Comment by danieldegrasse** [comment]
> 
> 
> Code changes look good, but the commit message doesn't match anymore. Can you update it to say that you're disabling logging under certain conditions, rather than removing logging altogether?

Fixed, sorry about that! Should have checked the commit message closer

**Review by MaureenHelm — APPROVED** [review]
>> Code changes look good, but the commit message doesn't match anymore. Can you update it to say that you're disabling logging under certain conditions, rather than removing logging altogether?
>
> Fixed, sorry about that! Should have checked the commit message closer

No problem. Thank you!
