### PR TITLE
Drivers: Bluetooth: H4: Use a semaphore to wake up HCI RX thread

### LINKED ISSUE #89879: Bluetooth: H4: Cannot receive data anymore after the command `bt scan on` executed
**Describe the bug**

The H4 cannot received data anymore after the command `bt scan on` executed if the log `<wrn> bt_driver: Failed to allocate, deferring to rx_thread` printed.

**To Reproduce**

1. Build the Bluetooth shell example.
2. Flash and run the example.
4. Input command `bt init` and `bt scan on`
5. After the log `<wrn> bt_driver: Failed to allocate, deferring to rx_thread` printed, no more adv data printed.
6. And if input `bt scan off`, the zephyr os will be halt.

**Expected behavior**

The command `bt scan on` should work normally.

**Impact**

**Logs and console output**

```
uart:~$ bt init
Bluetooth initialized
[00:00:07.755,000] <wrn> bt_hci_core: Num of Controller's ACL packets != ACL bt_conn_tx contexts (8 != 3)
[00:00:07.755,000] <wrn> bt_hci_core: Num of Controller's ISO packets != ISO bt_conn_tx contexts(16 != 1)
[00:00:07.764,000] <inf> bt_hci_core: HCI transport: H:4
uart:~$ bt scan on
Bluetooth active scan enabled
[DEVICE]: 1B:46:95:7D:37:39 (random), AD evt type 3, RSSI -77  C:0 S:0 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: D1:DB:0E:77:74:A0 (random), AD evt type 0, RSSI -89  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 5F:8D:02:1C:53:F6 (random), AD evt type 0, RSSI -81  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 6D:F4:38:2E:1B:89 (random), AD evt type 0, RSSI -75  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: D7:FE:F2:98:F4:2F (random), AD evt type 0, RSSI -75  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: D7:FE:F2:98:F4:2F (random), AD evt type 4, RSSI -75 JBL Tune 520BT-LE C:1 S:1 D:0 SR:1 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 4F:98:3F:62:02:9C (random), AD evt type 3, RSSI -88  C:0 S:0 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 35:FD:9A:CC:66:B1 (random), AD evt type 3, RSSI -92  C:0 S:0 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 5E:7F:4D:92:BF:CD (random), AD evt type 2, RSSI -80  C:0 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 76:55:75:E9:F4:09 (random), AD evt type 0, RSSI -75  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 76:55:75:E9:F4:09 (random), AD evt type 4, RSSI -75  C:1 S:1 D:0 SR:1 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 71:F8:2E:EF:9B:1A (random), AD evt type 0, RSSI -87  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 71:F8:2E:EF:9B:1A (random), AD evt type 4, RSSI -87  C:1 S:1 D:0 SR:1 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 62:45:FC:CA:81:8F (random), AD evt type 0, RSSI -62  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 62:45:FC:CA:81:8F (random), AD evt type 4, RSSI -62 LE-Bose QC Earbuds C:1 S:1 D:0 SR:1 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 60:BF:E5:A6:25:12 (random), AD evt type 0, RSSI -89  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: D7:1C:03:2B:80:1C (random), AD evt type 0, RSSI -90  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: D7:1C:03:2B:80:1C (random), AD evt type 4, RSSI -91 JBL TUNE520BT-LE C:1 S:1 D:0 SR:1 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[DEVICE]: 60:21:92:9B:63:E8 (random), AD evt type 0, RSSI -90  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[00:00:07.764,000] <inf> bt_hci_core: Identity: A0:CD:F3:77:F3:48 (public)
[00:00:07.764,000] <inf> bt_hci_core: HCI: version 5.4 (0x0d) revision 0x8300, manufacturer 0x0025
[00:00:07.764,000] <inf> bt_hci_core: LMP: version 5.4 (0x0d) subver 0x1015
[00:00:10.836,000] <wrn> bt_driver: Failed to allocate, deferring to rx_thread
uart:~$
uart:~$ bt scan off
ASSERTION FAIL [err == 0] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_core.c:463
        Controller unresponsive, command opcode 0x2042 timeout with err -11
[00:03:09.177,000] <err> os: r0/a1:  0x00000003  r1/a2:  0x00000002  r2/a3:  0x00000001
[00:03:09.177,000] <err> os: r3/a4:  0x00000003 r12/ip:  0x001cddba r14/lr:  0x3000de63
[00:03:09.177,000] <err> os:  xpsr:  0x01000000
[00:03:09.177,000] <err> os: Faulting instruction address (r15/pc): 0x3000de72
[00:03:09.177,000] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
[00:03:09.177,000] <err> os: Current thread: 0x20004af8 (shell_uart)
[00:03:09.208,000] <err> os: Halting system
```

**Environment (please complete the following information):**

 - OS: Windows
 - Toolchain Zephyr SDK
 - Commit SHA is 63f2fe9dd476eb24e90abc79650ab7b7247ad3a0

**Additional context**

I think rx_thread should be blocked at ["buf = k_fifo_get(&h4->rx.fifo, K_FOREVER);" ](https://github.com/zephyrproject-rtos/zephyr/blob/2a207879d121db203611f2c7d1a77c8226d1bf37/drivers/bluetooth/hci/h4.c#L260) after/when printing '<wrn> bt_driver: Failed to allocate, deferring to rx_thread'. This results in it not having a chance to execute the code https://github.com/zephyrproject-rtos/zephyr/blob/2a207879d121db203611f2c7d1a77c8226d1bf37/drivers/bluetooth/hci/h4.c#L245-L258

### PR DESCRIPTION
**Pull request by lylezhu2012**
There is an issue that the buffer cannot be allocated by the function `read_payload()` in UART ISR context. Then the UART RX will be disabled. The H4 driver hopes to get the receive buffer in the HCI RX thread and then open the UART RX again. However, there is a situation where the HCI RX thread is blocked in getting the received data buffer. However, since the UARt RX has been disabled, the HCI RX thread cannot get the received data buffer. Therefore, the RX thread is always blocked here, causing the Bluetooth host to not work properly.

Add a semaphore `rx.ready` to notify new received data buffer has been added to H4 RX queue.

Wait for the semaphore `rx.ready` instead of H4 RX queue in HCI RX thread.

Wake up the HCi RX thread when failing to allocate the RX buffer.

Fixes #89879.

### CODE REVIEW

File: drivers/bluetooth/hci/h4.c [hunk 1]
```diff
@@ -61,6 +61,8 @@ struct h4_data {
 	} tx;
 
 	bt_hci_recv_t recv;
+
+	struct k_sem active_sem;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/h4.c:65]: Since this is strictly related to rx, I think it'd be better to put it inside the rx struct. The name also needs some rethinking, since I don't think `active_sem` is clear enough. I'd have proposed something like `try_rx`, however when it's inside the rx struct this becomes a bit redundant: `hr->rx.try_rx`. Maybe "ready" would make sense? i.e. `k_sem_give(&h4->rx.ready);`?

File: drivers/bluetooth/hci/h4.c [hunk 2]
```diff
@@ -311,6 +315,7 @@ static inline void read_payload(const struct device *dev)
 
 			LOG_WRN("Failed to allocate, deferring to rx_thread");
 			uart_irq_rx_disable(cfg->uart);
+			k_sem_give(&h4->active_sem);
```
Comment (jhedberg) [inline drivers/bluetooth/hci/h4.c:318]: Since this is the key part of this PR, I think it deserves a code comment above this line. The important thing here (if I understand this correctly, is that since we're inside `read_payload()` it means that `h4->rx.have_hdr` must be true, so forcing the while loop in the RX thread to iterate once you force it into the `h4->rx.have_hdr && !h4->rx.buf` branch where it re-attempts allocating a buffer, right?

**Review by jhedberg — CHANGES_REQUESTED** [review]
Looks generally like a potentially correct solution, however a couple of things I'd change.

File: drivers/bluetooth/hci/h4.c (hunk 1 above)
Comment (lylezhu2012) [reply drivers/bluetooth/hci/h4.c:65]: Yes. `rx.ready` is more clear.

File: drivers/bluetooth/hci/h4.c (hunk 2 above)
Comment (lylezhu2012) [reply drivers/bluetooth/hci/h4.c:318]: > I think it deserves a code comment above this line.

Sure. I will update the PR. 

> so forcing the while loop in the RX thread to iterate once you force it into the `h4->rx.have_hdr && !h4->rx.buf` branch where it re-attempts allocating a buffer, right?

Right.

File: drivers/bluetooth/hci/h4.c [hunk 3]
```diff
@@ -37,6 +37,8 @@ struct h4_data {
 		struct net_buf *buf;
 		struct k_fifo   fifo;
 
+		struct k_sem ready;
```
Comment (jhedberg) [inline drivers/bluetooth/hci/h4.c:40]: Minor: please align `ready` the same way as other members of this structure (looks like that means 4 spaces, if I counted correctly).

File: drivers/bluetooth/hci/h4.c [hunk 4]
```diff
@@ -311,6 +315,17 @@ static inline void read_payload(const struct device *dev)
...
 			uart_irq_rx_disable(cfg->uart);
+			/*
+			 * At this time, HCI UART RX is turned off, which means that no new
+			 * received data buffer will be put into the RX FIFO. This will cause
+			 * `rx.ready` to not be modified. It will probably remain unchanged and
+			 * the count of `rx.ready` will probably be 0.
+			 *
+			 * Since it is uncertain whether the RX thread is blocked waiting for
+			 * `rx.ready`, give a semaphore to try to wake up the RX thread.
+			 * Then the RX buffer will be applied again in RX thread.
```
Comment (jhedberg) [inline drivers/bluetooth/hci/h4.c:326]: "applied again" seems unclear here. I guess you mean "Then there will be a renewed attempt at allocating an RX buffer in the RX thread"?

File: drivers/bluetooth/hci/h4.c (hunk 3 above)
Comment (lylezhu2012) [reply drivers/bluetooth/hci/h4.c]: Updated.

**Review by jhedberg — APPROVED** [review]

**Review by makeshi — APPROVED** [review]
