### PR TITLE
mgmt: fs_mgmt: clear lock before return

### LINKED ISSUE #66581: mcumgr fs_mgmt: Lock does not get released after callback returned MGMT_CB_ERROR_RC
**Describe the bug**
I tried to implement some filesystem access policies using the mcumgr mgmt callback mechanism. When the callback returns `MGMT_CB_ERROR_RC`(and `rc` set to some error code), the error code does get communicated as expected to the the mcumgr client. Any following filesystem operations through smp now fail, even those which should be allowed.

I work on a nRF52840 and use mcumgr SMP via BLE.

**To Reproduce**
1. Implement callback to limit filesystem access, as documented at <https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr_callbacks.html>
2. Do not allowed filesystem access via mcumgr client
3. Do allowed filesystem access via mcumgr client
4. Observe, that the filesystem access from step 3 fails

**Expected behavior**
I would expect the filesystem access from step 3 not to fail.

**Impact**
This makes the filesystem command group of mcumgr pretty unusable for me, as letting the callback return `MGMT_CB_ERROR_ERR` instead(and putting the error code into the group data) does not communicate the error code correctly to the mcumgr client.

**Additional context**
I think that the bug is at <https://github.com/zephyrproject-rtos/zephyr/blob/b83b9bede3bdc787615073a99463e6a00932318d/subsys/mgmt/mcumgr/grp/fs_mgmt/src/fs_mgmt.c#L257-L259> and <https://github.com/zephyrproject-rtos/zephyr/blob/b83b9bede3bdc787615073a99463e6a00932318d/subsys/mgmt/mcumgr/grp/fs_mgmt/src/fs_mgmt.c#L406-L408> where the lock `fs_mgmt_ctxt.lock_sem` is not cleared before returning from the functions. Clearing the lock before the return seems to solve the problem for me.

### PR DESCRIPTION
**Pull request by rvoell-gcx**
Not clearing that lock lead to the fs_mgmt commands being useless, after the mgmt callback returned `MGMT_CB_ERROR_RC` once, since the lock is now occupied and never cleared.

Fixes #66581

### CODE REVIEW

File: subsys/mgmt/mcumgr/grp/fs_mgmt/src/fs_mgmt.c [hunk 1]
```diff
@@ -338,6 +339,8 @@ static int fs_mgmt_file_download(struct smp_streamer *ctxt)
 
 end:
 	rc = (ok ? MGMT_ERR_EOK : MGMT_ERR_EMSGSIZE);
+
+unlock:
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/grp/fs_mgmt/src/fs_mgmt.c:343]: Seems that the label is only useful when CONFIG_MCUMGR_GRP_FS_FILE_ACCESS_HOOK=y and compiler does not like that. You need to find a way around that.

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Comment by gte1** [comment]
@de-nordic Can we get this fix into https://github.com/nrfconnect/sdk-zephyr soon ?

**Comment by nordicjm** [comment]
> @de-nordic Can we get this fix into https://github.com/nrfconnect/sdk-zephyr soon ?

It would come in with the next upmerge. You can submit it manually if you want if you follow the process, essentially cherry-picking with `git cherry-pick -x --edit <commit>` and putting `[nrf fromtree]` on the first line

**Comment by gte1** [comment]
I can wait for the next upmerge. Thanks.
