### PR TITLE
SPI: Do not disable SPI peripheral while switching DMA buffers

### LINKED ISSUE #28833: STM32: SPI DMA Driver - HW CS handling not compatible with spi_nor (Winbond W25Q)
**Describe the bug**
When spi_nor driver is sending command over SPI it uses two rx buffers and two tx buffers. In current implementation in function transceive_dma (spi_ll_stm32.c) SPI peripheral is turned off after each buffer finishes resulting in CS pin being pulled up between bytes send. Flash that I use (Winbond W25Q) after falling edge on CS expect command to be send therefore communication does not work. 

**To Reproduce**
1. Always reproducible when using spi_nor driver with spi_dma turned on and hardware slave select
CONFIG_SPI_NOR=y
CONFIG_SPI_STM32_USE_HW_SS=y
CONFIG_SPI_STM32_DMA=n

**Expected behavior**
CS not being pulled up when switching DMA for next buffer. This is how it behaves when software CS is used. 

**Impact**
Prevents SPI flash chips form being used with DMA

### PR DESCRIPTION
**Pull request by LuxLuthor**
Removed SPI peripheral disabling when switching DMA to another buffer. When using hardware chip select this would cause to stop driving CS pin when swhitching buffers. This is different (and wrong) than when used software CS.

Fixes #28833

Signed-off-by: Łukasz Mazur <lukasz.mazur@hidglobal.com>

### CODE REVIEW

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -729,8 +729,7 @@ static int transceive_dma(const struct device *dev,
 		/* wait until hardware is really ready */
 		while (LL_SPI_IsActiveFlag_BSY(spi) == 1) {
 		}
-
-		LL_SPI_Disable(spi);
```
Comment (tbursztyka) [inline drivers/spi/spi_ll_stm32.c:733]: Btw, aren't lines 689 to 691 superfluous? (At this stage, cs nor dma are enabled: the transaction has yet to start)

Comment (LuxLuthor) [reply drivers/spi/spi_ll_stm32.c:733]: Probably yes but this PR solves only HW CS problem. I don't know what was the idea of the original author.

**Review by tbursztyka — APPROVED** [review]
Just reformat your commit message so it fits whithin 72chars per line (something like that)

**Comment by lowlander** [comment]
@erwango Since this will need some actual testing on different boards (at least one without dmamux and one with) I will not be able to seriously review this until in the weekend.

**Comment by erwango** [comment]
> @erwango Since this will need some actual testing on different boards (at least one without dmamux and one with) I will not be able to seriously review this until in the weekend.

This is totally fine, thanks for your help in reviewing this!

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (lowlander) [reply drivers/spi/spi_ll_stm32.c:733]: I think that code ended up there after quit a bit of conversation in the PR that changed that code, I guess nobody had a use case/hardware that used HW CS :-/ I will test (but I won't have time until in the weekend) it on the boards I have, and if those all work I guess it should be OK.

**Comment by lowlander** [comment]
Tested with nucleo_L496zg, nucleo_l053r8, nucleo_f767zi, and l4r5zi (some boards need some not yet merged PRs) and all seem to still work fine with GPIO-CS. Tested the L4R5ZI with HW CS and it looked OK.

This is the CS signal without the fix.

spi_without_fix

And this with the fix.

spi_with_fix

**Review by lowlander — APPROVED** [review]

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (lowlander) [reply drivers/spi/spi_ll_stm32.c:733]: @tbursztyka a quick test shows that line 689 and 690 can be removed, but line 691 `LL_SPI_Disable(spi);` should be changed to `LL_SPI_Enable(spi);` and than line 713 can also be removed.

Comment (tbursztyka) [reply drivers/spi/spi_ll_stm32.c:733]: nice, can you make a pr?

Comment (lowlander) [reply drivers/spi/spi_ll_stm32.c:733]: @LuxLuthor could you add those changes mentioned by me to this PR, or do you want me to make a new combined PR with those changes and your fix ?

**Comment by erwango** [comment]
> "lowlander self-requested a review 1 hour ago"

@lowlander, having some doubts ?

**Comment by lowlander** [comment]
> > "lowlander self-requested a review 1 hour ago"
> 
> @lowlander, having some doubts ?

@erwango not about the fix, but if we want to do the little cleanup in this commit also, see the discussion in the code above.

File: drivers/spi/spi_ll_stm32.c (hunk 1 above)
Comment (lowlander) [reply drivers/spi/spi_ll_stm32.c:733]: @erwango the question was if cleanup the extra enable call in this PR, or if we make two "mini" PR's

Comment (erwango) [reply drivers/spi/spi_ll_stm32.c:733]: @lowlander @LuxLuthor, as long as this is done in 2 commits that are properly documented and current PR description is updated, this can be done here.

Comment (lowlander) [reply drivers/spi/spi_ll_stm32.c:733]: @erwango the fix is to remove the disable from the loop, so the enable in the loop makes no sense anymore, and can only be done one time before the loop. so those two changes belong in one (this) commit ? The removing of the dmadisable in front of the loop could be the second commit ?

Comment (LuxLuthor) [reply drivers/spi/spi_ll_stm32.c:733]: @erwango @lowlander, Yep, I will add these changes in this PR.

Comment (lowlander) [reply drivers/spi/spi_ll_stm32.c:733]: @erwango On the other hand maybe just merge this commit and make a cleanup PR, so @Luxluthor doesn't have to change this PR/commit ? I can make a new PR with the cleanup.

Comment (lowlander) [reply drivers/spi/spi_ll_stm32.c:733]: @erwango @tbursztyka should @luxluthor make one commit with removing the SPI disable/enable out of the loop and one removing the two dmadisables in front of the loop ?

**Review by gmarull — APPROVED** [review]
Haven't tested myself on HW, but changes LGTM. @lowlander thanks for the signal captures!

**Review by erwango — APPROVED** [review]
