### PR TITLE
ipc: static_vrings: Fix timeout management

### LINKED ISSUE #45934: ipc_service: nocopy tx buffer allocation works unexpectedly with RPMSG backend
**Describe the bug**
Target platform: nrf5340dk_nrf5340
Application: Internal tests that uses ipc_service with RPMSG backend.

`int ipc_service_get_tx_buffer(struct ipc_ept *ept, void **data, uint32_t *size, k_timeout_t wait)` can return after 15 seconds with NULL pointer when timeout is set to `K_FOREVER` when there is not possibility to allocates buffer due to shared memory being full. I would expect that this function should wait forever for free place for buffer if shared memory is full and function is called with `K_FOREVER` parameter.

The second issue is that the `ipc_service_get_tx_buffer` can only allocates buffer with fixed size of `RPMSG_BUFFER_SIZE - sizeof(struct rpmsg_hdr)` and currently there is not option other than adding build time definition to set `RPMSG_BUFFER_SIZE` to size different than 512 bytes. It would be good to have this parameter configurable at least from Kconfig during build time but the perfect solution would be to add possibility to allocate buffer which could contain a few continuous block of memory to fit data bigger than  `RPMSG_BUFFER_SIZE` because sometimes we need to allocate buffer just for few bytes but in other case it can be over 1Kb.

**To Reproduce**
Run any application that uses IPC with RPMSG backend and try to pass more data that can fit into a shared memory. For example buffers can be hold on the Rx remote side without being fired. When the shared memory will be full then allocation of the next Tx buffer will exit after 15 seconds setting the `data` pointer to the NULL.

**Expected behavior**
1. `int ipc_service_get_tx_buffer(struct ipc_ept *ept, void **data, uint32_t *size, k_timeout_t wait)` should wait forever for free place in shared memory when wait parameter is set to `K_FOREVER`.
2. Maximum  requested Tx buffer size should be configurable at least from the Kconfig. The perfect solutions would be buffer allocation where the place for data could be composed of several contiguous memory blocks if data doesn't fit into single block.

**Impact**
Implementation that use `int ipc_service_get_tx_buffer(struct ipc_ept *ept, void **data, uint32_t *size, k_timeout_t wait)` with wait time set to forever may failed unexpectedly if this function returns with NULL pointer due to shared memory being full.

It is not possible to sent more data than `RPMSG_BUFFER_SIZE - sizeof(struct rpmsg_hdr)` through IPC service with RPMSG when nocopy mechanism is used.

### PR DESCRIPTION
**Pull request by carlocaione**
The ipc_service_get_tx_buffer() has a timeout parameter that can be used
to wait a certain amount of time for a TX buffer to be available.

Unfortunately, for the static vrings backend, an asymmetry
between remote and host exists that makes the usage of this parameter
confusing when the user requests a buffer when no buffers are available
at that time.

When the remote endpoints requests a TX buffer specifying a certain
size and there are no TX buffers available, the function ignores the
parameter and ipc_service_get_tx_buffer() immediately returns -ENOMEM.

The same case on the host endpoint works correctly only when the
specified timeout is <= 15 seconds. All timeouts > 15 seconds simply
returns -EIO after 15 seconds.

This patch is reworking the timeout management trying to behave
correctly in all the cases.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/45934

### CODE REVIEW

File: subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c [hunk 1]
```diff
@@ -527,22 +528,24 @@ static int get_tx_buffer(const struct device *instance, void *token,
...
 
-	payload = rpmsg_get_tx_payload_buffer(&rpmsg_ept->ep, size, K_TIMEOUT_EQ(wait, K_FOREVER));
+	/*
+	 * OpenAMP doesn't really have the concept of forever but instead it
+	 * gives up after 15 seconds.  In that case, just keep retrying.
+	 */
+	do {
+		payload = rpmsg_get_tx_payload_buffer(&rpmsg_ept->ep, size,
+						      K_TIMEOUT_EQ(wait, K_FOREVER));
+	} while ((!payload) && K_TIMEOUT_EQ(wait, K_FOREVER));
```
Comment (hubertmis) [inline subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c:544]: How does it work for a remote endpoint? According to the PR description I guess we would enter busy loop. Is my understanding correct?

**Review by hubertmis — COMMENTED** [review]
Looks good.
With this retry mechanism it should be possible to support other timeout values than `_NOWAIT` and `_FOREVER`. But it's out of scope of this fix.

I would like to clarify function behavior for remote end before approving.

File: subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c (hunk 1 above)
Comment (arnopo) [reply subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c:544]: This loop is quite strange for me.
`K_TIMEOUT_EQ(wait, K_FOREVER) `return true if wait == K_FOREVER, else false, right?
In this case if user requests a time out of `x` milliseconds K_TIMEOUT_EQ will return false.

If the aim is to manage a busy loop with a timeout out, perhaps implementing a loop calling   `rpmsg_get_tx_payload_buffer` with wait set to false and  a `k_sleep` or a `k_yield` would be closer to the expected behavior.

Comment (KAGA164) [reply subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c:544]: This looks good to me also, compared to previous approach. It supports now `_NO_WAIT` and `_FOREVER` timeout values. For the  `_FOREVER` the `rpmsg_get_tx_payload_buffer` can block for 1 seconds and check if there is free buffer up to 15 times. The Zephyr ports uses `k_sleep` function to wait for buffer so this is not exactly busy loop because context switching can be done.

I like also the @arnopo proposition which would add possibility to request any timeout value, it can be done under this PR but I also can agree that we can approach it the another PR

File: subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c [hunk 2]
```diff
@@ -45,6 +45,9 @@ struct backend_data_t {
 	/* General */
 	unsigned int role;
 	atomic_t state;
+
+	/* TX buffer size */
+	int tx_buffer_size;
```
Comment (KAGA164) [inline subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c:50]: Does it necessary to have signed type for buffer size instead of for example `size_t` type ?

File: subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c (hunk 1 above)
Comment (hubertmis) [reply subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c:544]: > For the `_FOREVER` the `rpmsg_get_tx_payload_buffer` can block for 1 seconds and check if there is free buffer up to 15 times.

Does it work this way for both host and remote sides?

Comment (carlocaione) [reply subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c:544]: @hubertmis  

> How does it work for a remote endpoint? According to the PR description I guess we would enter busy loop. Is my understanding correct?

Why the behavior on the remote endpoint should be different? AFAICT there is no difference between host and remote.

@arnopo 

> In this case if user requests a time out of x milliseconds K_TIMEOUT_EQ will return false.

The user cannot request anything different from `_NO_WAIT` and `_FOREVER`, see: https://github.com/zephyrproject-rtos/zephyr/blob/f2e2bbd8642b47a18434f410e0813e24162252d6/subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c#L524-L527

> If the aim is to manage a busy loop with a timeout out, perhaps implementing a loop calling rpmsg_get_tx_payload_buffer with wait set to false and a k_sleep or a k_yield would be closer to the expected behavior.

I'm not trying to support a general timeout value in this PR.

@KAGA164 

> The Zephyr ports uses k_sleep function to wait for buffer so this is not exactly busy loop because context switching can be done here.

This is exactly it.

Comment (hubertmis) [reply subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c:544]: > Why the behavior on the remote endpoint should be different? AFAICT there is no difference between host and remote.

I must have misunderstood the commit message. Thanks for clarification.

**Review by hubertmis — APPROVED** [review]

File: subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c (hunk 1 above)
Comment (arnopo) [reply subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c:544]: > @arnopo
> 
> > In this case if user requests a time out of x milliseconds K_TIMEOUT_EQ will return false.
> 
> The user cannot request anything different from `_NO_WAIT` and `_FOREVER`, see:
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/f2e2bbd8642b47a18434f410e0813e24162252d6/subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c#L524-L527
> 
> > If the aim is to manage a busy loop with a timeout out, perhaps implementing a loop calling rpmsg_get_tx_payload_buffer with wait set to false and a k_sleep or a k_yield would be closer to the expected behavior.
> 
> I'm not trying to support a general timeout value in this PR.

clear now, thanks!

**Review by arnopo — APPROVED** [review]
LGTM
