### PR TITLE
tests: kernel: mutex: move race timeout test to mutex_api

### LINKED ISSUE #48056: Possible null pointer dereference after k_mutex_lock times out
**Describe the bug**

Assume thread A holds a mutex and thread B tries to lock it with a timeout, when that time comes up B gets unpended by z_thread_timeout and thus removed from the mutex's wait queue.

If however A unlocks this mutex before B being rescheduled again, the mutex->owner field will be set to null because B is not on the wait queue anymore. And when B finally gets resheduled again it will dereference the null pointer (mutex-owner) here

```
static bool adjust_owner_prio(struct k_mutex *mutex, int32_t new_prio)
{
	if (mutex->owner->base.prio != new_prio) {
```

as @peter-mitsis pointed out in #47906 , complete steps of one possible scenario are:

1. A low priority thread (Tlow) locks mutex A.
2. A high priority thread (Thigh) blocks on mutex A, boosting the priority of Tlow.
3. Thigh times out waiting for mutex A.
4. Before Thigh has a chance to execute, Tlow unlocks mutex A (which now has no owner) and drops its own priority.
5. Thigh now gets a chance to execute and finds that it timed out, and then enters the block of code to lower the priority of the thread that owns mutex A (now nobody).
6. Thigh tries to the dereference the owner of mutex A (which is nobody, and thus it is NULL). This leads to an exception.

**To Reproduce**

Use this test code as an app

```c
#include <kernel.h>
#include <sys/printk.h>

#define TIMEOUT_MS   	100
#define STACKSZ         8192

static struct k_mutex mutex;
static struct k_thread thread;

K_THREAD_STACK_DEFINE(stack, STACKSZ);

void test_thread(void *p1, void *p2, void *p3)
{
    ARG_UNUSED(p1);
    ARG_UNUSED(p2);
    ARG_UNUSED(p3);

    k_mutex_lock(&mutex, K_MSEC(TIMEOUT_MS));

    k_mutex_unlock(&mutex);
}

void main(void)
{
    k_mutex_init(&mutex);

    k_thread_create(&thread, stack, K_THREAD_STACK_SIZEOF(stack),
                    test_thread, NULL, NULL, NULL, 8, 0, K_NO_WAIT);

    k_mutex_lock(&mutex, K_FOREVER);

    k_sleep(K_MSEC(TIMEOUT_MS));

    k_mutex_unlock(&mutex);
}
```

`west build -b qemu_cortex_a53 path_to_the_above_app -t run # will data abort`

**Expected behavior**

Should not dereference a null pointer.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**

*** Booting Zephyr OS build 38de9b0156a8  ***
[00:00:00.000,000] <dbg> os: k_sched_unlock: scheduler unlocked (0x40017600:0)
[00:00:00.010,000] <dbg> os: setup_thread_stack: stack 0x4005fa40 for thread 0x40017000: obj_size=8192 buf_start=0x4005fa40  buf_size 8192 stack_ptr=0x40061a40
[00:00:00.010,000] <dbg> os: z_impl_k_mutex_lock: 0x40017600 took mutex 0x40017900, count: 1, orig prio: 0
[00:00:00.010,000] <dbg> os: z_impl_k_mutex_lock: adjusting prio up on mutex 0x40017900
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_unlock: mutex 0x40017900 lock_count: 1
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_unlock: new owner of mutex 0x40017900: (nil) (prio: -1000)
[00:00:00.120,000] <dbg> os: k_sched_unlock: scheduler unlocked (0x40017600:0)
main 40
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: on mutex 0x40017900 got_mutex value: -11
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: 0x40017000 got mutex 0x40017900 (y/n): y
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: 0x40017000 timeout on mutex 0x40017900
[00:00:00.120,000] <dbg> os: z_impl_k_mutex_lock: adjusting prio down on mutex 0x40017900
[00:00:00.120,000] <err> os: ELR_ELn: 0x0000000040006c30
[00:00:00.120,000] <err> os: ESR_ELn: 0x0000000096000006
[00:00:00.120,000] <err> os:   EC:  0x25 (Data Abort taken without a change in Exception level)
[00:00:00.120,000] <err> os:   IL:  0x1
[00:00:00.120,000] <err> os:   ISS: 0x6
[00:00:00.120,000] <err> os: FAR_ELn: 0x000000000000001a
[00:00:00.120,000] <err> os: TPIDRRO: 0x0100000040017978
[00:00:00.120,000] <err> os: x0:  0x0000000040017900  x1:  0x0000000000000000
[00:00:00.120,000] <err> os: x2:  0x0000000000000000  x3:  0x0000000000000000
[00:00:00.120,000] <err> os: x4:  0x0000000000000000  x5:  0x0000000000000003
[00:00:00.120,000] <err> os: x6:  0x000000000000000a  x7:  0x0000000000000000
[00:00:00.120,000] <err> os: x8:  0x000000000000002f  x9:  0x00000000ffffffff
[00:00:00.120,000] <err> os: x10: 0x0000000000000000  x11: 0x0000000000000000
[00:00:00.120,000] <err> os: x12: 0x0000000000000000  x13: 0x0000000000000000
[00:00:00.130,000] <err> os: x14: 0x0000000000000000  x15: 0x0000000000000000
[00:00:00.130,000] <err> os: x16: 0x0000000000000000  x17: 0x0000000000000000
[00:00:00.130,000] <err> os: x18: 0x0000000000000000  x30: 0x0000000040007204
[00:00:00.130,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.130,000] <err> os: Current thread: 0x40017000 (unknown)
[00:00:00.130,000] <err> os: Halting system

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: v2.7.2

### PR DESCRIPTION
**Pull request by cfriedt**
Previously, this change was added to `mutex_error_case`.

That worked fine in `main`, but once the change was backported to `v2.7-branch`, the test would fail because it *did not* cause a failure. The reason for that, was that the `mutex_error_case` suite has `CONFIG_ZTEST_FATAL_HOOK=y`.

With the newer ztest API, it allowed a separate suite to be used, allowing the test to pass (although it did not really fit in with the rest of the testsuite).

The solution is to simply merge it with the `mutex_api` suite which uses non-inverted success logic.

This change will also have to be cherry-picked for the backport in #49031.

Fixes #48056.

cc @yperess - not sure if this exposes any weird state in the new testsuite

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Comment by cfriedt** [comment]
Just a thought - would it be better here to revert the previous commit and simply use this one instead? That way there is less to backport.

File: tests/kernel/mutex/mutex_api/src/test_mutex_apis.c [hunk 1]
```diff
@@ -387,6 +387,52 @@ ZTEST_USER(mutex_api_1cpu, test_mutex_priority_inheritance)
...
+{
+	k_mutex_init(&mutex);
+
+	/* align to tick boundary */
+	k_sleep(K_TICKS(1));
+	k_thread_create(&tdata, tstack, K_THREAD_STACK_SIZEOF(tstack),
+			tThread_mutex_lock_should_fail, &mutex, NULL, NULL, 8,
+			K_USER | K_INHERIT_PERMS, K_NO_WAIT);
+
+	k_mutex_lock(&mutex, K_FOREVER);
```
Comment (peter-mitsis) [inline tests/kernel/mutex/mutex_api/src/test_mutex_apis.c:429]: Minor item: I would prefer to see that *k_mutex_lock()* is moved to before *k_thread_create()* is called. This makes it blatantly obvious to a reader that the mutex is locked before the helper thread executes. Otherwise anyone reading the code in the future has to expend additional energy/time verifying priorities, scheduling, and number of cpus involved to ensure that  it behaves as described.

Comment (peter-mitsis) [reply tests/kernel/mutex/mutex_api/src/test_mutex_apis.c:429]: Back up a moment ... isn't the priority of the running thread here a higher priority level than the created thread? If true, then the current thread gets the thread and when the created thread tries to take the semaphore, it would not lead to a case of priority inversion.

Thus, we should be doing ...

1. lock mutex
2. create helper thread at higher priority to current thread.

**Comment by cfriedt** [comment]
Since I'm responding this anyway to address @peter-mitsis suggestions, I think I will opt to revert the previous commit that add d the test in the wrong suite, because then a single Testcase can be backported a bit more cleanly.

@peter-mitsis @andyross - is that OK with both of you?

File: tests/kernel/mutex/mutex_api/src/test_mutex_apis.c [hunk 2]
```diff
@@ -387,6 +387,52 @@ ZTEST_USER(mutex_api_1cpu, test_mutex_priority_inheritance)
...
+
+	k_sleep(K_MSEC(TIMEOUT));
```
Comment (peter-mitsis) [inline tests/kernel/mutex/mutex_api/src/test_mutex_apis.c:431]: If priority inheritance is kicking in, then both the helper and the current thread should be at the same priority. They are both likely to wake on the same tick. The test as written is assuming that the current thread is going to be executed first. Such an assumption might not hold--it is highly dependent upon the implementation of the scheduler and which thread is got to the "head" of the ready queue first.

To work around this, I have two ideas...
1. If available, use an absolute timeout for both the helper and current thread to guarantee that both threads will expire on the same tick. 
2. Before the current thread sleeps, explicitly bump its priority even higher. This should help guarantee that it will always execute before the helper thread.

**Comment by peter-mitsis** [comment]
@cfriedt - I'm good with your proposal.

File: tests/kernel/mutex/mutex_api/src/test_mutex_apis.c (hunk 2 above)
Comment (cfriedt) [reply tests/kernel/mutex/mutex_api/src/test_mutex_apis.c:431]: @peter-mitsis - I could create an arbitrary absolute tick value in the current thread and pass that as a parameter to the helper thread.

One option is making that a Kconfig value local to the testsuite.

The main concern I have with that is that it could be another one of those racey values that we just have to keep increasing over time. Is there a happy medium between long-enough to allow the thread to start and short enough to not be considered "too long for a test"?

**Review by dcpleung — DISMISSED** [review]

**Comment by cfriedt** [comment]
@peter-mitsis, @dcpleung - please have another look. I believe this addresses all remaining concerns.

**Review by dcpleung — APPROVED** [review]

**Comment by cfriedt** [comment]
@peter-mitsis - can you approve?
Maybe @andyross ?

**Review by andyross — APPROVED** [review]
Makes sense.  Could maybe consider merging all those error_case tests too?

**Comment by cfriedt** [comment]
> Makes sense.  Could maybe consider merging all those error_case tests too?

Makes sense - I'll check to see what is missing.
