### PR TITLE
lib: posix: Fix pthread_attr_init() return code

### LINKED ISSUE #7480: pthread_attr_init( ) does not conform to POSIX specification
Currently `pthread_attr_init()` checks the content of the input pthread_attr.
Therefore if its input was not initialized before the call, the behavior of the function is unpredictable.
Note that the point of pthread_attr_init() is to actually initialize it after it was declared and before it is used.

The POSIX spec. for this function can be found here:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_attr_init.html

An appropriate behavior of the function would be to always copy into its input the init structure without checks. As the specification allows undefined behavior for `pthread_attr_init()` if the input had been initialized before hand.

Related: #7446

### PR DESCRIPTION
**Pull request by ramakrishnapallala**
pthread_attr_init() should not return EBUSY as per POSIX spec
so fixed this by return ENOMEM if the attr pointer is NULL.

Also fixed the attribute initialization logic by copying the
init_pthread_attrs to the attr.

Fixes #7480

Signed-off-by: Ramakrishna Pallala <ramakrishna.pallala@intel.com>

### CODE REVIEW

**Review by punitvara — APPROVED** [review]

File: lib/posix/pthread.c [hunk 1]
```diff
@@ -278,11 +278,11 @@ int pthread_setschedparam(pthread_t pthread, int policy,
 int pthread_attr_init(pthread_attr_t *attr)
 {
 
-	if (attr->initialized == true) {
-		return EBUSY;
+	if (attr == NULL) {
+		return ENOMEM;
```
Comment (aescolar-ot) [inline lib/posix/pthread.c]: I guess I would have expected an `EINVAL` in this case.

**Review by aescolar — APPROVED** [review]
Good enough for me.

File: lib/posix/pthread.c (hunk 1 above)
Comment (ramakrishnapallala) [reply lib/posix/pthread.c]: from spec: 
ENOMEM : Insufficient memory exists to initialize the thread attributes object.

Here i assumed the input attr has insufficient memory.
