### PR TITLE
net: tcp2: Fix pointer to local outside scope in th_get()

### LINKED ISSUE #25779: [Coverity CID :209942] Pointer to local outside scope in subsys/net/ip/tcp2.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/subsys/net/ip/tcp2.c

Category: Memory - illegal accesses
Function: `th_get`
Component: Networking
CID: [209942](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=209942)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by ozhuraki**
Fix Coverity CID :209942 Pointer to local outside scope.

Fixes #25779

### CODE REVIEW

File: subsys/net/ip/tcp2.c [hunk 1]
```diff
@@ -37,17 +37,18 @@ size_t (*tcp_recv_cb)(struct tcp *conn, struct net_pkt *pkt) = NULL;
 
 static struct tcphdr *th_get(struct net_pkt *pkt)
 {
-	NET_PKT_DATA_ACCESS_DEFINE(th_access, struct tcphdr);
```
Comment (jukkar) [inline subsys/net/ip/tcp2.c:40]: Hmm, not sure about this. If the header is split between two net_buf's, then this will not work as expected.
I think better would be to move the th_access to calling function, and then pass pointer to it here and use it here as is.

**Review by jukkar — CHANGES_REQUESTED** [review]
Please move the coverity cid to separate line on its own next to Fixes like this `Coverity-CID: 209942`

File: subsys/net/ip/tcp2.c (hunk 1 above)
Comment (ozhuraki) [reply subsys/net/ip/tcp2.c:40]: We do a check if the TCP header is contiguous with net_pkt_is_contiguous().

Do you think that the case that the TCP header is split is realistic?

Comment (jukkar) [reply subsys/net/ip/tcp2.c:40]: Well, difficult to say how realistic it is, probably not very. But anyway, the original code would work with split header but after the changes, the func would return NULL if that happens.

Comment (jukkar) [reply subsys/net/ip/tcp2.c:40]: Anyway, my point was that it is quite simple to make this work properly by just moving the th_access to calling function.

Comment (ozhuraki) [reply subsys/net/ip/tcp2.c:40]: Hmm, we call th_get() from multiple functions.

Comment (jukkar) [reply subsys/net/ip/tcp2.c:40]: Yes, that is unfortunate and causes many changes. We have spent lot of time to make sure that the networking code works if for some reason the IP/TCP/UDP header is split between two network packet. I do not wish that we start to slip from this goal even if it very unlikely that the header would be split between two net_bufs.

Comment (jukkar) [reply subsys/net/ip/tcp2.c:40]: This works but only if `net_buf->size >= sizeof(tcp_hdr)`. This is certainly the case atm so I suppose we can continue with this solution.

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
