### PR TITLE
Bluetooth: Mesh: fix access to uninitialized memory

### LINKED ISSUE #54824: BT: Mesh: Utilizes some not initialized variables
**Describe the bug**
The BT Mesh stack utilizes some not initialized variables that lead to some random packet content on air (and variable paths in the code execution).

The issue can be reproduced and pinpointed in simulation, compiling the BT mesh stack in the nrf52_bsim, and  running the simulated device in valgrind. Running the physical layer simulation twice, once normally and again in "check mode" will also pinpoint the differences in radio traffic.

This can be seen in the current head (81aaf4a365c2b627d264f451631f546d4dccb5f5) and also before that. It has likely always been there.

**To Reproduce**
1. In the zephyr root, run `WORK_DIR=${ZEPHYR_BASE}/bsim_bt_out tests/bluetooth/bsim_bt/compile.sh`
2. Hack the mesh script (`tests/bluetooth/bsim_bt/bsim_test_mesh/_mesh_test.sh`) as so to run the executable in valgrind:
```
diff --git a/tests/bluetooth/bsim_bt/bsim_test_mesh/_mesh_test.sh b/tests/bluetooth/bsim_bt/bsim_test_mesh/_mesh_test.sh
index 3c65a11124..34f35dfda8 100755
--- a/tests/bluetooth/bsim_bt/bsim_test_mesh/_mesh_test.sh
+++ b/tests/bluetooth/bsim_bt/bsim_test_mesh/_mesh_test.sh
@@ -20,7 +20,7 @@ function Execute(){
  compile it?)\e[39m"
     exit 1
   fi
-  timeout 300 $@ & process_ids+=( $! )
+  valgrind $@ & process_ids+=( $! )
}
```
3. in the Zephyr root run `tests/bluetooth/bsim_bt/bsim_test_mesh/tests_scripts/provision/pb_adv_reprovision.sh`
6. See warnings in console

**Expected behavior**
No valgrind warnings, deterministic (the same) packets on air each time.

**Impact**
A red flag about a potential serious issue.

**Logs and console output**
valgrind and bsim phy output until the first packet difference:
```
....
d_01: @00:00:00.987880  [00:00:00.987,854] <inf> mesh_prov: prov_node_added: Device 0x0002 provisioned
==440933== Thread 3:
==440933== Conditional jump or move depends on uninitialised value(s)
==440933==    at 0x812CBBC: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2297)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933== 
==440933== Conditional jump or move depends on uninitialised value(s)
==440933==    at 0x404AD51: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933== 
==440933== Conditional jump or move depends on uninitialised value(s)
==440933==    at 0x404AD57: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933== 
==440933== Conditional jump or move depends on uninitialised value(s)
==440933==    at 0x404AD62: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933== 
==440933== Conditional jump or move depends on uninitialised value(s)
==440933==    at 0x404ADB7: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933== 
==440933== Use of uninitialised value of size 4
==440933==    at 0x404AEB0: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933== 
==440933== Invalid read of size 1
==440933==    at 0x404AEB0: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933==  Address 0x9253c70 is on thread 8's stack
==440933==  864 bytes below stack pointer
==440933== 
==440933== Use of uninitialised value of size 4
==440933==    at 0x404AEB3: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933== 
==440933== Conditional jump or move depends on uninitialised value(s)
==440933==    at 0x404AEBB: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933== 
==440933== Invalid read of size 1
==440933==    at 0x404AEBB: memcpy (in /usr/libexec/valgrind/vgpreload_memcheck-x86-linux.so)
==440933==    by 0x816C8BC: net_buf_simple_add_mem (buf.c:782)
==440933==    by 0x812C925: mod_pub_va_set (cfg_cli.c:2274)
==440933==    by 0x812CC00: bt_mesh_cfg_cli_mod_pub_set (cfg_cli.c:2298)
==440933==    by 0x8062012: test_provisioner_pb_adv_reprovision (test_provision.c:573)
==440933==    by 0x8098988: bst_main (bstests_entry.c:218)
==440933==    by 0x804D285: _posix_zephyr_main (main.c:55)
==440933==    by 0x81863B2: bg_thread_main (init.c:330)
==440933==    by 0x807D12E: z_thread_entry (thread_entry.c:36)
==440933==    by 0x8096059: posix_thread_starter (posix_core.c:305)
==440933==    by 0x4201B90: start_thread (pthread_create.c:442)
==440933==    by 0x429C239: clone (clone.S:107)
==440933==  Address 0x9253c72 is on thread 8's stack
==440933==  862 bytes below stack pointer
==440933== 
p_2G4:  Comp: Device 1, Tx 157 differs
p_2G4:  Comp: Read:"1750378,1750754,2.000000,0x8E89BED6,16,0.000000,18446744073709551615,1751601,42,42 25 D7 BE 7E D8 96 19 1E 2A 0D 65 73 3E C0 4B BB 00 AA 5E 04 FF C2 1A DD 59 C1 B0 60 B1 0A 9F A9 68 CF 8F 0F 74 EA EA EA 07"
p_2G4:  Comp:      "1750378,1750754,2.000000,0x8E89BED6,16,0.000000,18446744073709551615,1751601,42,42 25 D7 BE 7E D8 96 19 1E 2A 0D 65 73 3E C0 4B BB 00 AA 5E 04 FF C2 1A 7D 43 3C B0 60 B1 0A 9F A9 68 CF 87 71 00 A1 6F 33 B1"
p_2G4:  Comp:                                                                                                                                                               ^
....
```

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 22.04
 - Toolchain: Host gcc (any version, any valgrind version, any bsim version for the last 5 years)
 - Commit SHA or Version used:81aaf4a365c2b627d264f451631f546d4dccb5f5

**Additional context**
#54823

### PR DESCRIPTION
**Pull request by alxelax**
Running bsim with Valgrind highlighted a couple of places where read access to uninitialized memory happens. Config client rewrites publication parameters with not initialized uuid pointer. Bitfields those are allocated on the stack keeps not used area uninitialized too.
Uninitialized area is stored in the persistent memory. PR fixes that.

Signed-off-by: Aleksandr Khromykh <aleksandr.khromykh@nordicsemi.no>

### CODE REVIEW

**Review by Andrewpini — APPROVED** [review]

File: subsys/bluetooth/mesh/rpl.c [hunk 1]
```diff
@@ -290,7 +290,7 @@ BT_MESH_SETTINGS_DEFINE(rpl, "RPL", rpl_set);
 
 static void store_rpl(struct bt_mesh_rpl *entry)
 {
-	struct rpl_val rpl;
+	struct rpl_val rpl = {0};
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/rpl.c:293]: Designated initializers could be used instead.

File: subsys/bluetooth/mesh/cfg_cli.c [hunk 2]
```diff
@@ -683,7 +683,12 @@ static int mod_pub_status(struct bt_mesh_model *model,
 		}
 
 		if (param->pub) {
-			*param->pub = pub;
+			param->pub->addr = pub.addr;
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/cfg_cli.c:686]: Or just set `pub.uuid` to `NULL` after line 659? Though here I'm uncertain if it is safer.

File: subsys/bluetooth/mesh/access.c [hunk 3]
```diff
@@ -1145,7 +1145,7 @@ static void store_pending_mod_sub(struct bt_mesh_model *mod, bool vnd)
 
 static void store_pending_mod_pub(struct bt_mesh_model *mod, bool vnd)
 {
-	struct mod_pub_val pub;
+	struct mod_pub_val pub = {0};
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/access.c:1148]: `pub.uuid = NULL` after line 1163?

**Review by PavelVPV — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/mesh/rpl.c (hunk 1 above)
Comment (alxelax) [reply subsys/bluetooth/mesh/rpl.c:293]: Designated initialization for unused part of bitfield?

Comment (PavelVPV) [reply subsys/bluetooth/mesh/rpl.c:293]: Perhaps the unused area should have a name to be initialized to 0 when using designated initializer:
```
struct rpl_val {
	uint32_t seq:24,
	      old_iv:1,
	      unused:7;
};
```

File: subsys/bluetooth/mesh/cfg_cli.c (hunk 2 above)
Comment (alxelax) [reply subsys/bluetooth/mesh/cfg_cli.c:686]: What if uuid has been already initialized before calling mesh API? bsim test does it here: https://github.com/nrfconnect/sdk-zephyr/blob/main/tests/bluetooth/bsim_bt/bsim_test_mesh/src/test_provision.c#L536
after that it initializes gotten publication being sure uuid is NULL: https://github.com/nrfconnect/sdk-zephyr/blob/main/tests/bluetooth/bsim_bt/bsim_test_mesh/src/test_provision.c#L573-L575
API description doesn't claim it is prohibited. Even more uuid pointer is not the part of config server publication frame.

File: subsys/bluetooth/mesh/access.c (hunk 3 above)
Comment (alxelax) [reply subsys/bluetooth/mesh/access.c:1148]: `struct mod_pub_val` doesn't have `uuid`. It is related to bitfileds `period_div` and `cred` and unused part of them

File: subsys/bluetooth/mesh/rpl.c (hunk 1 above)
Comment (alxelax) [reply subsys/bluetooth/mesh/rpl.c:293]: Perhaps, but Zephyr's mesh doesn't follow such design idea.

File: subsys/bluetooth/mesh/cfg_cli.c (hunk 2 above)
Comment (PavelVPV) [reply subsys/bluetooth/mesh/cfg_cli.c:686]: Ok, fair enough.

File: subsys/bluetooth/mesh/access.c (hunk 3 above)
Comment (PavelVPV) [reply subsys/bluetooth/mesh/access.c:1148]: https://github.com/zephyrproject-rtos/zephyr/pull/54823#discussion_r1106020761

File: subsys/bluetooth/mesh/rpl.c (hunk 1 above)
Comment (alxelax) [reply subsys/bluetooth/mesh/rpl.c:293]: I do not have objections. It is worth to do as a separate PR with redesigning all bitfields within ble mesh implementation to not mix bugfix and refactoring.

Comment (PavelVPV) [reply subsys/bluetooth/mesh/rpl.c:293]: It makes clear sense to do this here. You just need to add one bit fields that does nothing to but solves the issue.

**Review by PavelVPV — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
