### PR TITLE
soc: nxp: imx943: fix pm_mcore link failure when SCMI CPU helpers absent

### LINKED ISSUE #103992: imx943: pm_mcore.c causes link failure when NXP SCMI CPU domain helpers are not enabled (undefined scmi_nxp_cpu_* references)
## Describe the bug
Building for i.MX943 M33 can fail at link time with undefined references from `soc/nxp/imx/imx9/imx943/pm_mcore.c` to NXP SCMI CPU-domain helper APIs.

Example failing symbols (from `pm_state_before()/pm_state_set()/pm_state_exit_post_ops()`):
- `scmi_nxp_cpu_pd_lpm_set`
- `scmi_nxp_cpu_set_irq_mask`
- `scmi_nxp_cpu_sleep_mode_set`

The helpers are implemented in `drivers/firmware/scmi/nxp/cpu.c`, but that file is only built when `CONFIG_NXP_SCMI_CPU_DOMAIN_HELPERS=y` (which itself depends on `CONFIG_ARM_SCMI_NXP_VENDOR_EXTENSIONS` and `DT_HAS_NXP_SCMI_CPU_ENABLED`).

However `pm_mcore.c` is compiled when `CONFIG_SOC_IMX943_PM_MCORE=y` (default y when `PM` is enabled for i.MX943 M33/M7), even if the SCMI CPU helpers are not enabled. This leads to the undefined reference link failures.

Reference line in upstream:
https://github.com/zephyrproject-rtos/zephyr/blob/0bb9a469c1dbe1dfb825cd68a08fab8b70c3701e/soc/nxp/imx/imx9/imx943/pm_mcore.c#L139

## To Reproduce
Observed in CI/twister build:
- Test: `cpp.main.newlib.cxx_tests.new_delete`
- Zephyr version: `v4.3.0-5931-g8100484e5d43`
- Platform: `nxp_virtual/mimx94398/m33`

Linker error excerpt:
```
ld.bfd: zephyr/libzephyr.a(pm_mcore.c.obj): in function `pm_state_before':
.../soc/nxp/imx/imx9/imx943/pm_mcore.c:208: undefined reference to `scmi_nxp_cpu_pd_lpm_set'
.../pm_mcore.c:229: undefined reference to `scmi_nxp_cpu_set_irq_mask'
.../pm_mcore.c:280: undefined reference to `scmi_nxp_cpu_sleep_mode_set'
.../pm_mcore.c:304: undefined reference to `scmi_nxp_cpu_sleep_mode_set'
collect2: error: ld returned 1 exit status
```

## Expected behavior
Either:
1. `pm_mcore.c` is not built unless the required SCMI CPU helpers are enabled, **or**
2. `pm_mcore.c` is guarded so it does not reference these symbols when the helpers are not present.

## Proposed fix
In `soc/nxp/imx/imx9/imx943/Kconfig`, make `SOC_IMX943_PM_MCORE` depend on `NXP_SCMI_CPU_DOMAIN_HELPERS`.

Example:
```Kconfig
config SOC_IMX943_PM_MCORE
	bool "i.MX943 multi-core PM shared logic"
	default y
	depends on PM
	depends on SOC_MIMX94398_M33 || SOC_MIMX94398_M7_0 || SOC_MIMX94398_M7_1
	depends on NXP_SCMI_CPU_DOMAIN_HELPERS
```

This ensures the SoC PM implementation is only built when the implementation of `scmi_nxp_cpu_*` helpers is available.

## Additional context
- Definitions are in: `drivers/firmware/scmi/nxp/cpu.c`
- Built under: `CONFIG_NXP_SCMI_CPU_DOMAIN_HELPERS` (`drivers/firmware/scmi/nxp/CMakeLists.txt`)

## Environment
- Toolchain: zephyr-sdk 0.17.1-rc4 (arm-zephyr-eabi gcc 12.2.0)
- Host: Linux (Jenkins CI)
- version: https://github.com/zephyrproject-rtos/zephyr/commit/2fd6d9ad8d36918d98fd2747a9b4fb8f3c07c971

### PR DESCRIPTION
**Pull request by Jjateen**
# soc: nxp: imx943: fix pm_mcore link failure when SCMI CPU helpers absent

Closes #103992

`SOC_IMX943_PM_MCORE` defaulted to `y` with `CONFIG_PM=y` but had no
dependency on `NXP_SCMI_CPU_DOMAIN_HELPERS`, causing `pm_mcore.c` to
link against `scmi_nxp_cpu_*` symbols that were never built.

## Fix

- Add `depends on NXP_SCMI_CPU_DOMAIN_HELPERS` to `SOC_IMX943_PM_MCORE`
  in Kconfig so `pm_mcore.c` is only compiled with the full SCMI stack.
- Add no-op inline fallbacks for `pm_state_set()` and
  `pm_state_exit_post_ops()` in `include/zephyr/pm/pm.h` instead of a
  per-SoC stub file, so the PM subsystem always has a valid backend to
  link against. This scales to other platforms without duplication.

## Testing

`samples/hello_world` on `imx943_evk/mimx94398/m33` with `CONFIG_PM=y`
and `CONFIG_ARM_SCMI_NXP_VENDOR_EXTENSIONS=n`, SDK 0.17.1. Build
succeeds where it previously failed with undefined references.

### CODE REVIEW

File: soc/nxp/imx/imx9/imx943/Kconfig
Comment (dsseng) [inline soc/nxp/imx/imx9/imx943/Kconfig]: Extra tab before newline

```suggestion
	depends on NXP_SCMI_CPU_DOMAIN_HELPERS
```

**Review by dsseng — COMMENTED** [review]
nit

File: soc/nxp/imx/imx9/imx943/Kconfig [hunk 1]
```diff
@@ -58,7 +58,7 @@ config SOC_IMX943_PM_MCORE
 	default y
 	depends on PM
 	depends on SOC_MIMX94398_M33 || SOC_MIMX94398_M7_0 || SOC_MIMX94398_M7_1
-	depends on NXP_SCMI_CPU_DOMAIN_HELPERS	
+	depends on NXP_SCMI_CPU_DOMAIN_HELPERS
 	help
```
Comment (dbaluta) [inline soc/nxp/imx/imx9/imx943/Kconfig:62]: You need to squash this in the previous patch.

Comment (Jjateen) [reply soc/nxp/imx/imx9/imx943/Kconfig:62]: done

File: soc/nxp/imx/imx9/imx943/pm_mcore_stub.c
Comment (dbaluta) [inline soc/nxp/imx/imx9/imx943/pm_mcore_stub.c]: I don't think this scale's well. Are we supposed to implement this stub everytime we add a new platform?

Can all this function be move to include/zephyr/pm/pm.h as inline functions?

Comment (Jjateen) [reply soc/nxp/imx/imx9/imx943/pm_mcore_stub.c]: Good point, agreed. Moved the no-op fallbacks for `pm_state_set()` and `pm_state_exit_post_ops()` to `include/zephyr/pm/pm.h` as inline functions and dropped the stub file. Force-pushed.

File: include/zephyr/pm/pm.h [hunk 2]
```diff
@@ -172,7 +172,12 @@ void pm_system_resume(void);
  * @param state Power state.
  * @param substate_id Power substate id.
  */
-void pm_state_set(enum pm_state state, uint8_t substate_id);
+__weak void pm_state_set(enum pm_state state, uint8_t substate_id)
```
Comment (ZhaoxiangJin) [inline include/zephyr/pm/pm.h]: Why implement the default implementation in the header file? This causes a large number of redefinition problems when building cases in the tree.

**Review by ZhaoxiangJin — CHANGES_REQUESTED** [review]

File: include/zephyr/pm/pm.h (hunk 2 above)
Comment (Jjateen) [reply include/zephyr/pm/pm.h]: You're right, putting definitions in the header causes redefinition errors. However, the only alternative I see is a stub `.c` file — but @dbaluta flagged that a per-SoC stub doesn't scale and suggested moving it to `pm.h` instead (see [here](https://github.com/zephyrproject-rtos/zephyr/pull/105232#discussion_r292280266)).

Would a `pm_stub.c` under `subsys/pm/` with `__weak` no-op definitions work here? That way it's not per-platform and avoids the header definition issue. Happy to go that route if you both agree.

Comment (dbaluta) [reply include/zephyr/pm/pm.h]: > mentation in the header file? This causes a large number of redefinition problems when building cases in the tree.

The common practice for "stubs" is to have them as static inline functions in the headers. They won't cause redefinition errors.

What I still don't get is why do we need per platforms stub when they'll all have the same trivial empty function implementation.

Comment (ZhaoxiangJin) [reply include/zephyr/pm/pm.h]: I don't know what problem you encountered. Why do you need to add a per-SoC stub .c file?
In my opinion, we don't need to stub `pm_state_set` and `pm_state_exit_post_ops`. They should necessarily be implemented by the SoC, otherwise the SoC won't actually enter low power mode.

Comment (Jjateen) [reply include/zephyr/pm/pm.h]: The reason I added the stub was to fix this link failure that occurs when building with `CONFIG_PM=y` but `CONFIG_ARM_SCMI_NXP_VENDOR_EXTENSIONS=n`:

```
ld.bfd: zephyr/libzephyr.a(pm.c.obj): in function `pm_system_resume':
pm.c:125: undefined reference to `pm_state_exit_post_ops'
ld.bfd: zephyr/libzephyr.a(pm.c.obj): in function `pm_system_suspend':
pm.c:243: undefined reference to `pm_state_set'
```

Once `SOC_IMX943_PM_MCORE` is gated on `NXP_SCMI_CPU_DOMAIN_HELPERS`, `pm_mcore.c` (the only provider of these symbols in the imx943 SoC layer) is excluded, leaving them undefined. The PM subsystem still calls them unconditionally when `CONFIG_PM=y`.

I agree these should be real SoC implementations. Should the fix instead be to make `CONFIG_PM` depend on `SOC_IMX943_PM_MCORE` in `Kconfig.defconfig`, so PM cannot be enabled without the full SCMI stack? That would make this an invalid configuration by construction.

Comment (ZhaoxiangJin) [reply include/zephyr/pm/pm.h]: Personal understanding: when `CONFIG_PM=y` and `CONFIG_ARM_SCMI_NXP_VENDOR_EXTENSIONS=n`, we should give the user a build error. If we add stub operations and let pm execute the stub in this situation, it doesn't make much sense and may even produce abnormal behavior.

Comment (Jjateen) [reply include/zephyr/pm/pm.h]: Oh right, that makes sense. I was just trying to fix the build error and didn't think about it that way. Will drop the stub and gate it properly at the Kconfig level instead.

**Review by ZhaoxiangJin — APPROVED** [review]

**Review by nashif — APPROVED** [review]

File: soc/nxp/imx/imx9/imx943/Kconfig (hunk 1 above)
Comment (hakehuang) [reply soc/nxp/imx/imx9/imx943/Kconfig:62]: so the SOC_IMX943_PM_MCORE depends on a board level feature NXP_SCMI_CPU_DOMAIN_HELPERS?

Comment (Jjateen) [reply soc/nxp/imx/imx9/imx943/Kconfig:62]: No, `NXP_SCMI_CPU_DOMAIN_HELPERS` is not a board level symbol. It is defined in `drivers/firmware/scmi/nxp/Kconfig` and depends on `ARM_SCMI_NXP_VENDOR_EXTENSIONS` and `DT_HAS_NXP_SCMI_CPU_ENABLED`. It is a driver level feature that the SoC PM layer requires to function correctly, so the dependency makes sense here.

**Review by JiafeiPan — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]
