### PR TITLE
can: rework the table lookup code in can_dlc_to_bytes

### LINKED ISSUE #62701: Build warning when compiling can_dlc_to_bytes against picolibc
**Describe the bug**
Picolibc has some extra build time checks that result in a warning with the current `can_dlc_to_bytes` implementation:

`zephyrproject/zephyr/drivers/modem/hl7800.c:1786:74: warning: '%s' directive output may be truncated writing up to 53 bytes into a region of size 21 [-Wformat-truncation=]`

**To Reproduce**
`west build -p -b mg100 -T samples/net/telnet/sample.net.telnet`

**Expected behavior**
No warnings.

**Impact**
Potential build breakage if the build is setup to fail on warnings.

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Hi, fixing a warning that popped up with the switch to picolibc, guess that check was not there before for whatever reasons.

What do you think? Not in love with this solution myself to be honest, but adding a bunch of `#pragma GCC diagnostic ignored "-Warray-bounds"` around this does not sound great either.

---

Rework the can_dlc_to_bytes table lookup code in a way that allow the
compiler to guess the resulting output and somehow fix the build
warning:

zephyr/drivers/can/can_nxp_s32_canxl.c:757:9: warning:
'__builtin___memcpy_chk' forming offset [16, 71] is out of the bounds
[0, 16] of object 'frame' with type 'struct can_frame' [-Warray-bounds]
 757 | memcpy(frame->data, msg_data.data, can_dlc_to_bytes(frame->dlc));

where the compiler detects that frame->data is 8 bytes long but
can_dlc_to_bytes could return more than that.

Can be reproduced with:

west build -p -b s32z270dc2_rtu1_r52 \
	-T samples/net/sockets/can/sample.net.sockets.can.one_socket

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/62701

### CODE REVIEW

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]
We can't do that, sorry. The utility function needs to do the correct calculation regardless if CAN-FD is enabled or not.

**Comment by fabiobaltieri** [comment]
> We can't do that, sorry. The utility function needs to do the correct calculation regardless if CAN-FD is enabled or not.

Fair enough, how about this instead? Just added a MIN against the size of the buffer. This one I'm actually not completely ashamed of.

**Review by alexanderwachter — DISMISSED** [review]
Much better!

**Review by henrikbrixandersen — DISMISSED** [review]
Thanks!

**Comment by martinjaeger** [comment]
This would be another solution the compiler is happy with:

```C
static inline uint8_t can_dlc_to_bytes(uint8_t dlc)
{
	static const uint8_t dlc_table[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 12,
					    16, 20, 24, 32, 48, 64};

	return dlc_table[dlc > 0xF ? 16 : dlc];
}
```

**Comment by fabiobaltieri** [comment]
> This would be another solution the compiler is happy with:
> 
> ```c
> static inline uint8_t can_dlc_to_bytes(uint8_t dlc)
> {
> 	static const uint8_t dlc_table[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 12,
> 					    16, 20, 24, 32, 48, 64};
> 
> 	return dlc_table[dlc > 0xF ? 16 : dlc];
> }
> ```

Happy with either, I think @martinjaeger one is better though cause it would fix it on potentially any other driver doing a similar pattern. Can you open a PR with that? Happy to close this one for yours.

**Comment by martinjaeger** [comment]
> Happy with either, I think @martinjaeger one is better though cause it would fix it on potentially any other driver doing a similar pattern. Can you open a PR with that? Happy to close this one for yours.

Yes, it would be a more universal fix and maybe would save one additional comparison. Just take my suggestion and use it if you like. I don't mind.

**Review by martinjaeger — DISMISSED** [review]

**Comment by fabiobaltieri** [comment]
Re-redone using @martinjaeger suggestion.

Compilers are magic.

**Review by alexanderwachter — DISMISSED** [review]
A sizeof(dlc_table) instead of 0x0f and 16 would even be nicer

File: include/zephyr/drivers/can.h [hunk 1]
```diff
@@ -1360,7 +1360,7 @@ static inline uint8_t can_dlc_to_bytes(uint8_t dlc)
 	static const uint8_t dlc_table[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 12,
 					    16, 20, 24, 32, 48, 64};
 
-	return dlc > 0x0F ? 64 : dlc_table[dlc];
+	return dlc_table[dlc > 0xF ? 16 : dlc];
```
Comment (martinjaeger) [inline include/zephyr/drivers/can.h:1363]: Wait. Don't we only have 16 elements, so that `dlc_table[16]` would actually be out of bounds? Why does it not complain now? A little bit too late today... Maybe magic number should better be replaced with `sizeof` calculation.

Comment (alexanderwachter) [reply include/zephyr/drivers/can.h:1363]: dlc_table[MIN(dlc, sizeof(dlc_table) - 1)]

Comment (fabiobaltieri) [reply include/zephyr/drivers/can.h:1363]: I'm shocked.

**Review by martinjaeger — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
At least the fact that I did not tag this as "Trivial" makes me feel a bit better.

**Comment by henrikbrixandersen** [comment]
@fabiobaltieri Please open an issue for this so the bug fix can be backported.

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri Please open an issue for this so the bug fix can be backported.

Can we use https://github.com/zephyrproject-rtos/zephyr/issues/62612? It covers all three picolibc error I've found in the run.

**Comment by martinjaeger** [comment]
> Actually if you folks have any idea of what to do with the [2] in there... :-)

Got an idea. Will open a PR, but need to double-check first.

**Review by alexanderwachter — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@henrikbrixandersen can we merge this? Trying to get this in before the next weekly run (tomorrow)

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen can we merge this? Trying to get this in before the next weekly run (tomorrow)

Yes, but please open a separate issue for this and link it, as it also fixes the bug in the implementation. A separate issue would help in backporting the fix.

**Comment by fabiobaltieri** [comment]
> > @henrikbrixandersen can we merge this? Trying to get this in before the next weekly run (tomorrow)
> 
> Yes, but please open a separate issue for this and link it, as it also fixes the bug in the implementation. A separate issue would help in backporting the fix.

Cool with that: https://github.com/zephyrproject-rtos/zephyr/issues/62701

**Review by henrikbrixandersen — APPROVED** [review]
