### PR TITLE
drivers i2c I2C_DW:Fix I2C scan example

### LINKED ISSUE #70332: rpi_pico: I2C master not working
**Describe the bug**
When using the RPi Pico in a sample with I2C enabled (e.g: Shell sample with I2C commands), the i2c commands are unexpectedly blocking, not toggling the I2C lines and as a result not working.

I've tried the exact same sample with other boards (e.g: stm32g0br1e and nrf52840) and I can confirm the behavior is as expected. Which leads me to believe that it's not a sample-issue, rather a board/target-driver issue.

Before filing this issue, I've reached out over discord to see if others have seen it. @petejohanson has confirmed seeing this issue as well. Link: https://discord.com/channels/720317445772017664/938474761405726800/1218422579417583666

**To Reproduce**
1. Build Shell sample with I2C commands enabled: `west build -b rpi_pico samples/subsys/shell/shell_module -- -DCONFIG_I2C=y -DCONFIG_I2C_SHELL=y`.
2. Flash board (e.g: With `west flash` using J-Link or copying `zephyr.uf2` when the device presents as MSD device over USB.
3. Wire the I2C bus to have pull-ups on I2C0 SDA (P4) and SCL (P5).
4. Connect over UART (TX: P0, RX: P1), and issue a shell command to scan the I2C0 bus:`i2c scan i2c@40044000`.
5. See how the I2C scan command freezes indefinitely.

image

**Expected behavior**
The I2C scan command shouldn't be blocking indefinitely, and just go over each I2C address, and list whether there's a device present or not (e.g: See screenshot for a nRF52840DK with a BME280 on 0x77).

image

### PR DESCRIPTION
**Pull request by quic-DevJoshi**
Solves two similar issues listed below:

Issue 1: I2C scanner example for DesignWare hardware gets stuck indefenitely resulting in system hang up. This is because DW driver does not handle 0 byte transfer correctly which is the case for I2C scan example. Fixed it by overwriting the msg length to 1 if it is 0 and the buffer is not NULL.

Issue 2: Similarly, if the I2C pins are not pulled up (nothing connected to I2C pins), the DW hardware does not actually sending the data (assuming contention on the bus) hence not releasing the semaphore resulting in calling thread waiting forever. Fixed it by adding a timeout to k_sem_take call and return error if cannot successfully acquire it.

Fixes: #70332.

Micropython seems to tackle this issue by supporting zero length transfer through Soft I2C implementation. Since Zephyr doesn't currently support that this commit provides a temporary solution to unblock the I2C Scan example.

Link: [Micropython I2C workaround](https://github.com/micropython/micropython/blob/master/ports/rp2/machine_i2c.c#L158)

### CODE REVIEW

**Comment by teburd** [comment]
@ubieda does this happen to fix the rpi issue you ran into?

File: drivers/i2c/i2c_dw.c [hunk 1]
```diff
@@ -714,7 +720,12 @@ static int i2c_dw_transfer(const struct device *dev,
 		}
 
 		/* Wait for transfer to be done */
-		k_sem_take(&dw->device_sync_sem, K_FOREVER);
+		ret = k_sem_take(&dw->device_sync_sem, K_MSEC(CONFIG_I2C_DW_RW_TIMEOUT_MS));
+		if (ret != 0) {
+			write_intr_mask(DW_DISABLE_ALL_I2C_INT, reg_base);
+			value = read_clr_intr(reg_base);
+			break;
```
Comment (ubieda) [inline drivers/i2c/i2c_dw.c:727]: Suggestion: This seems duplicate of the code below. May we refactor both so we enforce DRY?
https://github.com/zephyrproject-rtos/zephyr/blob/cac70373aa81b9989905ac530b9773e4b748e409/drivers/i2c/i2c_dw.c#L346-L353.

**Review by ubieda — APPROVED** [review]
Thanks for submitting this PR! I've just confirmed it fixes the issue.

File: drivers/i2c/i2c_dw.c (hunk 1 above)
Comment (quic-DevJoshi) [reply drivers/i2c/i2c_dw.c:727]: Thanks for approval and suggestion. Does creating a static inline function to disable and clear all the I2C interrupts a good way to achieve DRY? Thanks!

Comment (ubieda) [reply drivers/i2c/i2c_dw.c:727]: Sounds good to me!

**Review by teburd — APPROVED** [review]
