### PR TITLE
 [Backport v2.7-branch] backport #65546: userspace: Additional checks in K_SYSCALL_MEMORY

### LINKED ISSUE #66775: [Coverity CID: 338153] Macro compares unsigned to 0 in subsys/rtio/rtio_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/rtio/rtio_handlers.c#L32

Category: Integer handling issues
Function: `rtio_vrfy_sqe`
Component: Other
CID: [338153](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=338153)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/rtio/rtio_handlers.c#L32

```
26       bool valid_sqe = true;
27     
28       switch (sqe->op) {
29       case RTIO_OP_NOP:
30               break;
31       case RTIO_OP_TX:
>>>     CID 338153:  Integer handling issues  (NO_EFFECT)
>>>     This greater-than-or-equal-to-zero comparison of an unsigned value is always true. "(*sqe).buf_len >= 0U".
32               valid_sqe &= K_SYSCALL_MEMORY(sqe->buf, sqe->buf_len, false);
33               break;
34       case RTIO_OP_RX:
35               if ((sqe->flags & RTIO_SQE_MEMPOOL_BUFFER) == 0) {
36                       valid_sqe &= K_SYSCALL_MEMORY(sqe->buf, sqe->buf_len, true);
37               }
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #69151: [Backport v2.7-branch] Failed to backport #65546
This issue was created automatically because the backport of #65546 to `v2.7-branch` failed.

The backport to `v2.7-branch` failed:
```
Auto-merging include/syscall_handler.h
CONFLICT (content): Merge conflict in include/syscall_handler.h
error: could not apply 899d4f997e... userspace: Additional checks in K_SYSCALL_MEMORY
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-v2.7-branch v2.7-branch
# Navigate to the new working tree
cd .worktrees/backport-v2.7-branch
# Create a new branch
git switch --create backport-65546-to-v2.7-branch
# Cherry-pick the merged commits of this pull request and resolve the conflicts
git cherry-pick -x 899d4f997e6eebd7e647beeb123dc5deb2821cc9
# Push it to GitHub
git push --set-upstream origin backport-65546-to-v2.7-branch
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-v2.7-branch
```
Then, create a pull request where the `base` branch is `v2.7-branch` and the `compare`/`head` branch is `backport-65546-to-v2.7-branch`.

### PR DESCRIPTION
**Pull request by ceolin**
Backport of #65546 for `v2.7-branch`.

Fixes #66775

### CODE REVIEW

File: include/sys/util.h [hunk 1]
```diff
@@ -61,6 +62,23 @@ extern "C" {
...
+ * This macro determines if a buffer identified by a starting address @a addr
+ * and length @a buflen spans a region of memory that goes beond the highest
+ * possible address (thereby resulting in a pointer overflow).
+ *
+ * @param addr Buffer starting address
+ * @param buflen Length of the buffer
+ *
+ * @return true if pointer overflow detected, false otherwise
+ */
+#define Z_DETECT_POINTER_OVERFLOW(addr, buflen)  \
```
Comment (d3zd3z) [inline include/sys/util.h:77]: I realize this is just a backport, but I think this check has an off-by-one. It kind of depends on whether we are trying to exclude a buffer that includes the last possible address. Realistically, this is not likely to be an address that is ever used because it would case enough other problems, that I don't see justification to change this.

**Review by d3zd3z — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Comment by cfriedt** [comment]
Assuming that the doc build failure is unrelated.
