### PR TITLE
drivers: i2c: Fix BFLB I2C again again

### LINKED ISSUE #102040: Recurrent compiler optimization related failure of BFLB I2C driver
### Describe the bug

When using the bouffalolab I2C driver, failings will appear and break the driver's functionality.

Facts list:

- Driver never has failed when using -DCONFIG_NO_OPTIMIZATIONS=y, this is related to optimization
- Failure propagates: the specific failure will appear out of the driver, such as with PR https://github.com/zephyrproject-rtos/zephyr/pull/100686, this subtle change will add or remove failure with the driver version https://github.com/zephyrproject-rtos/zephyr/commit/ae9f04b5562a823e7861652e0dc42c9fb5c0825c:
```c
static int ssd1306_write_bus_i2c(const struct device *dev, uint8_t *buf, size_t len, bool command)
{
    const struct ssd1306_config *config = dev->config;

    const uint8_t control =
        command ? SSD1306_CONTROL_ALL_BYTES_CMD : SSD1306_CONTROL_ALL_BYTES_DATA;
    static uint8_t tmp[SSD1306_I2C_CHUNK_SIZE + 1];
    int ret = 0;

    if (len == 0U) {
        return 0;
    }

    k_mutex_lock(&ssd1306_i2c_buffer_lock, K_FOREVER);

    size_t off = 0;

    while (off < len) {
        size_t this_len = MIN(SSD1306_I2C_CHUNK_SIZE, len - off);

        LOG_ERR("WHAT THE FUCK IS WRONG WITH YOU DUMBASS");

        tmp[0] = control;
        memcpy(&tmp[1], &buf[off], this_len);

        ret = i2c_write_dt(&config->bus.i2c, tmp, this_len + 1);
        if (ret < 0) {
            k_mutex_unlock(&ssd1306_i2c_buffer_lock);
            return ret;
        }

        off += this_len;
    }

    k_mutex_unlock(&ssd1306_i2c_buffer_lock);

    return ret;
}
``` 
This does not work
```c
static int ssd1306_write_bus_i2c(const struct device *dev, uint8_t *buf, size_t len, bool command)
{
    const struct ssd1306_config *config = dev->config;

    const uint8_t control =
        command ? SSD1306_CONTROL_ALL_BYTES_CMD : SSD1306_CONTROL_ALL_BYTES_DATA;
    static uint8_t tmp[SSD1306_I2C_CHUNK_SIZE + 1];
    int ret = 0;

    if (len == 0U) {
        return 0;
    }

    k_mutex_lock(&ssd1306_i2c_buffer_lock, K_FOREVER);

    size_t off = 0;

    while (off < len) {
        size_t this_len = MIN(SSD1306_I2C_CHUNK_SIZE, len - off);

        LOG_ERR("WHAT THE FUCK IS WRONG WITH YOU DUMBASS %d", this_len);

        tmp[0] = control;
        memcpy(&tmp[1], &buf[off], this_len);

        ret = i2c_write_dt(&config->bus.i2c, tmp, this_len + 1);
        if (ret < 0) {
            k_mutex_unlock(&ssd1306_i2c_buffer_lock);
            return ret;
        }

        off += this_len;
    }

    k_mutex_unlock(&ssd1306_i2c_buffer_lock);

    return ret;
}
```
This works.
- Failure may or may not show up depending on subtle conditions, see previous or https://github.com/zephyrproject-rtos/zephyr/pull/100686#issuecomment-3671350896 where switching the specific binding (and so a bit of code) changed the behavior of the driver completly
- This may be related to timepoints and timeouts, as changing calls to this areas significiantly affects the resulting behavior, and similar issues have been observed out of the I2C driver entirely: https://github.com/zephyrproject-rtos/zephyr/pull/101298#issuecomment-3680420110

### Regression

- [ ] This is a regression.

### Steps to reproduce

Switch between ssd1306 driver versions (current and PR mentionned) and see it starts failing for no reasons.

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- OS: Linux x86_64
- Toolchain: SDK 17.4
- Commits: various

### Additional Context

_No response_

## Mitigations:

- Fix with limits of current https://github.com/zephyrproject-rtos/zephyr/pull/102033
- Find some way to reliably test or identify root cause of issue.

### PR DESCRIPTION
**Pull request by VynDragon**
Maybe the last time? associated issue outlines details

### CODE REVIEW

**Review by josuah — APPROVED** [review]
Still puzzled to see this driver being affected by the compiler reordering everything.

Maybe there is some other bug somewhere, I remember you saying the disassembly was shuffling things a *lot* and that `volatile` everything was not a complete fix. But it could also be a compiler design choice or plain bug, so if this is possible to fix it at the driver level in the meantime it's good IMHO.

Context is, IIRC `Zephyr SDK 0.17.4`.

**Review by teburd — APPROVED** [review]

File: drivers/i2c/i2c_bflb.c [hunk 1]
```diff
@@ -408,7 +408,7 @@ static inline bool i2c_bflb_errored(const struct device *dev)
 	return (tmp & I2C_ARB_INT) != 0 || (tmp & I2C_FER_INT) != 0;
 }
 
-static inline int i2c_bflb_write(const struct device *dev, uint8_t *buf, uint8_t len)
```
Comment (JarmouniA) [inline drivers/i2c/i2c_bflb.c:411]: Functions of this size should not be inlined.

Comment (VynDragon) [reply drivers/i2c/i2c_bflb.c:411]: That is purely opinion (all hail our glorious savior `__attribute__((flatten))`), and had no effect on the issue except for missing the intended effect of flattening the unit into a single __no_optimization (timepoint var is one of the main offender at failing reordering here, however volatile only doesn't fix it as it doesnt make gcc recognize the way the function works, just forces it to update the value, at least from my observations).

Comment (JarmouniA) [reply drivers/i2c/i2c_bflb.c:411]: Ok I see it's called in 1 place only.

Comment (VynDragon) [reply drivers/i2c/i2c_bflb.c:411]: Yea, it could have been in the 'transceive' functions, but it's more readable like so
