### PR TITLE
Bluetooth: TBS: Fix Issues for Setting URI scheme for GTBS Bearer

### LINKED ISSUE #91576: Bluetooth: TBS: Cannot set URI scheme list for GTBS
### Describe the bug

The `bt_tbs_set_uri_scheme_list` function does not properly handle setting an URI scheme list for GTBS. This means that in case of using only GTBS, it's not possible to set any URI scheme, which shouldn't be the case. 

The function should use `inst_lookup_index(bearer_index)` instead of `&svc_insts[bearer_index];` and allow setting URI schemes specifically for the GTBS. 

Additionally the function should be updated so that instead of copying all URI scheme lists into `uri_scheme_buf` (which is only used for logging purposes?), the complete list, when notifying for GTBS, should be constructed dynamically similar to e.g. `bearer_list_current_calls_changed` and `read_current_calls`. 

### Regression

- [ ] This is a regression.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

Commit SHA: f8b70ee1794803e76b7db28c7eb06e475fc61667

### Additional Context

Found in https://github.com/zephyrproject-rtos/zephyr/pull/91547

### PR DESCRIPTION
**Pull request by nirav-agrawal**
- "bt_tbs_set_uri_scheme_list()" function does not set URI for GTBS instance. Using "inst_lookup_index()" fixes issue to find registered GTBS instance for provided bearer_index.
- "bt_tbs_set_uri_scheme_list()" function overrides URI scheme list with latest provided list. But the expectation is that it should keep previously added URI schemes and only update new scheme which are not part existing list. Code is updated to fix this.
- The same function uses net-buf to combine all URI schemes for all TBS bearer if current request is not for GTBS instance. Currently, the code only uses combined URI scheme list for logging purpose, and it is not used to send for URI Scheme notification to provide updated GTBS URI scheme to remote. Code is now updated to add dynamic buffer to add all TBS URI scheme list for GTBS instance and notify it similar to other functions to optimise memory usage.

Regards,
Nirav

fixes https://github.com/zephyrproject-rtos/zephyr/issues/91576

### CODE REVIEW

File: samples/bluetooth/tmap_central/src/ccp_call_control_server.c [hunk 1]
```diff
@@ -1,7 +1,7 @@
 /** @file
  *  @brief Bluetooth Call Control Profile (CCP) Server role.
  *
- *  Copyright 2023 NXP
+ *  Copyright 2023,2025 NXP
```
Comment (Thalley) [inline samples/bluetooth/tmap_central/src/ccp_call_control_server.c:4]:
```suggestion
 *  Copyright 2023-2025 NXP
```

I think this is the usual way of denoting this, but I'll leave it up to you as we don't really have any guidelines on this

File: subsys/bluetooth/audio/tbs.c [hunk 2]
```diff
@@ -628,6 +629,31 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+
+	net_buf_simple_add_mem(buf, inst->uri_scheme_list, strlen(inst->uri_scheme_list));
+
+	if (inst_is_gtbs(inst)) {
+		for (size_t i = 0; i < ARRAY_SIZE(svc_insts); i++) {
+			const size_t uri_len = strlen(svc_insts[i].uri_scheme_list);
+
+			if (buf->len + uri_len >= buf->size) {
+				LOG_WRN("Cannot fit all TBS instances in GTBS "
+					"URI scheme list");
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]:
```suggestion
				LOG_WRN("Cannot fit all TBS instances in GTBS URI scheme list");
```

File: subsys/bluetooth/audio/tbs.c [hunk 3]
```diff
@@ -2944,54 +2968,49 @@ int bt_tbs_set_uri_scheme_list(uint8_t bearer_index, const char **uri_list, uint
...
 	err = k_mutex_lock(&inst->mutex, K_NO_WAIT);
 	if (err != 0) {
 		LOG_DBG("Failed to lock mutex");
 		return -EBUSY;
 	}
 
+	if ((len + uri_len + 1) >= READ_BUF_SIZE) {
+		LOG_WRN("Cannot fit all URI scheme list");
+		return -ENOMEM;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: We already have a length check against `uri_scheme_list` (`CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH`). 

`CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH` is maximum 512, so we should be able to modify the `READ_BUF_SIZE` so that it takes `CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH` into account. Perhaps it needs to add something like `(CONFIG_BT_TBS_BEARER_COUNT * CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH + CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH)` to also "fit" the case of GTBS, where we union the values.

File: subsys/bluetooth/audio/tbs.c [hunk 4]
```diff
@@ -2944,54 +2968,49 @@ int bt_tbs_set_uri_scheme_list(uint8_t bearer_index, const char **uri_list, uint
...
+
 	/* Store final result */
-	(void)utf8_lcpy(inst->uri_scheme_list, uri_scheme_list, sizeof(inst->uri_scheme_list));
+	strcat(&inst->uri_scheme_list[uri_len++], ",");
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Why are we adding a `,` here?

File: subsys/bluetooth/audio/tbs.c [hunk 5]
```diff
@@ -793,8 +819,8 @@ static void notify_handler_cb(struct bt_conn *conn, void *data)
 	if (flags->bearer_uri_schemes_supported_list_changed) {
 		LOG_DBG("Notifying Bearer URI schemes supported list: %s", inst->uri_scheme_list);
 
-		err = notify(conn, BT_UUID_TBS_URI_LIST, inst->attrs, &inst->uri_scheme_list,
-			     strlen(inst->uri_scheme_list));
+		net_buf_put_uri_scheme_list(inst, &read_buf);
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c:856]: `read_uri_scheme_list` also needs to be updated to use `net_buf_put_uri_scheme_list` so we have the same behavior for notification as well as read requests

**Review by Thalley — CHANGES_REQUESTED** [review]
Looks pretty good - A few things needs to be fixed

File: samples/bluetooth/tmap_central/src/ccp_call_control_server.c (hunk 1 above)
Comment (nirav-agrawal) [reply samples/bluetooth/tmap_central/src/ccp_call_control_server.c:4]: Hi @Thalley, as per our copyright, if change in file made in continuation from previous year we can use "-" to provide range of years of support in continuation for specific file. but here there is no change in file during 2024 makes me to use ",".  I would prefer to use existing change. Thank you.

File: subsys/bluetooth/audio/tbs.c (hunk 3 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Hi @Thalley, sure I will update `READ_BUF_SIZE` as suggested. The reason having the length check here is, if "inst->uri_scheme_list" already has URI-scheme string, and new request to add more URI-scheme through this function surpasses max length of 30 would cause problem. 

The earlier length check at line 2971 is to ensure the input URI-scheme list fits in `uri_scheme_list` buffer, and here at line 2997 is to ensure `inst->uri_scheme_list` fits for list given in `uri_scheme_list`. If there is not enough space left in `inst->uri_scheme_list` to add new URI schemes, it issues `-ENOMEM` error. 

Please help if I have any wrong understanding. thank you :)

File: subsys/bluetooth/audio/tbs.c (hunk 4 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: This `,` is required to add new URI-scheme list with current URI-scheme list. 

For example, 
`static const char *uri_list[URI_LIST_LEN] = {"skype", "tel"};
bt_tbs_set_uri_scheme_list(0, uri_list, 2);`

In function, it prepares given URI list from string array to common string appending `,` at every unique URI-scheme as per line 2966. so, it would prepare like `"skype,tel"`, or keep only` "skype"` if `"tel"` is already present or vice-versa. 

Now, if `inst->uri_scheme_list` already contains some list like `"teams,xyz"`, it needs `,` to add new list so it can become `teams,xyz,skype,tel` as a new list. 

Regards,
Nirav

File: subsys/bluetooth/audio/tbs.c (hunk 5 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c:856]: updated now. thank you

File: subsys/bluetooth/audio/tbs.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: Hmm, the function is not intended to _add_ schemes, but set the schemes, so 

> Now, if inst->uri_scheme_list already contains some list like "teams,xyz", it needs , to add new list so it can become teams,xyz,skype,tel as a new list.

Should not become `teams,xyz,skype,tel` if called again with `"skype"` and `"tel"`, but should be come `skype,tel`

File: subsys/bluetooth/audio/tbs.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: See my comment from https://github.com/zephyrproject-rtos/zephyr/pull/91833#discussion_r2154560552 - The function shall not _add_ but only _set_ the values.

File: subsys/bluetooth/audio/tbs.c (hunk 4 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: oh, I see, it's my bad. I thought it should update the list. I will update as you suggested. thank you :)

Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Hi @Thalley, I updated the logic now to set the uri scheme. For my test I tried some possible combinations which works well with given logic. Please see below snapshot.
Request log is for new URI list requested through set function, the function checks all schemes if it really requires setting with new list or no. one possible scenario is, current list has `"abc", "xyz"` and requesting new list with` "xyz", "abc"`. here both schemes are already present in TBS instance but not following same order. so, function will detect it and will not raise any notify command for it. 

image

Please review and provide your comment. thank you.

File: subsys/bluetooth/audio/tbs.c (hunk 2 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: updated, thank you.

File: subsys/bluetooth/audio/tbs.c [hunk 6]
```diff
@@ -111,10 +112,10 @@ struct tbs_inst {
...
 static struct tbs_inst gtbs_inst;
 
-#define READ_BUF_SIZE                                                                              \
-	MAX(BT_ATT_MAX_ATTRIBUTE_LEN,                                                              \
-	    (CONFIG_BT_TBS_MAX_CALLS * sizeof(struct bt_tbs_current_call_item) *                   \
-	     (1U + ARRAY_SIZE(svc_insts))))
+#define READ_BUF_SIZE                                                                             \
+	MAX(BT_ATT_MAX_ATTRIBUTE_LEN,                                                             \
+	    (CONFIG_BT_TBS_BEARER_COUNT * CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH +                  \
+	     CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH))
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Hmm, I think this calculation need to take both the previous definition and the new `CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH` handling into account. 

So it probably should be something like

```suggestion
	    MAX((CONFIG_BT_TBS_MAX_CALLS * sizeof(struct bt_tbs_current_call_item) * \
	    (1U + ARRAY_SIZE(svc_insts))), \ 
	    (CONFIG_BT_TBS_BEARER_COUNT * CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH +                  \
	     CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH))
```

right?

File: subsys/bluetooth/audio/tbs.c [hunk 7]
```diff
@@ -628,6 +629,35 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+		for (size_t i = 0; i < ARRAY_SIZE(svc_insts); i++) {
+			const size_t uri_len = strlen(svc_insts[i].uri_scheme_list);
+
+			if (buf->len + uri_len >= buf->size) {
+				LOG_WRN("Cannot fit all TBS instances in GTBS URI scheme list");
+				break;
+			}
+
+			net_buf_simple_add_mem(buf, svc_insts[i].uri_scheme_list, uri_len);
+		}
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: If we have
GTBS = "tel"
TBS_1 = "skype"
TBS_2 = "fax"

Then the result here would become 
`telskypefax`, but should be `tel,skype,fax`. I think this is missing adding the `,` when concatenating the strings.

File: subsys/bluetooth/audio/tbs.c [hunk 8]
```diff
@@ -2921,39 +2926,44 @@ int bt_tbs_set_uri_scheme_list(uint8_t bearer_index, const char **uri_list, uint
...
-		/* Store list in temp list in case something goes wrong */
-		strcat(uri_scheme_list, uri_list[i]);
+			/* Store list in temp list in case something goes wrong */
+			strcat(uri_scheme_list, uri_list[i]);
+		}
 	}
 
-	if (strcmp(inst->uri_scheme_list, uri_scheme_list) == 0) {
-		/* identical; don't update or notify */
+	LOG_DBG("request to set uri prefix list %s", uri_scheme_list);
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]:
```suggestion
	LOG_DBG("Request to set uri prefix list %s", uri_scheme_list);
```

File: subsys/bluetooth/audio/tbs.c [hunk 9]
```diff
@@ -2964,34 +2974,16 @@ int bt_tbs_set_uri_scheme_list(uint8_t bearer_index, const char **uri_list, uint
 	}
 
 	/* Store final result */
-	(void)utf8_lcpy(inst->uri_scheme_list, uri_scheme_list, sizeof(inst->uri_scheme_list));
+	(void)utf8_lcpy(inst->uri_scheme_list, uri_scheme_list,
+			sizeof(inst->uri_scheme_list));
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]:
```suggestion
	(void)utf8_lcpy(inst->uri_scheme_list, uri_scheme_list, sizeof(inst->uri_scheme_list));
```

The line length in Zephyr is 100 :)

File: subsys/bluetooth/audio/tbs.c [hunk 10]
```diff
@@ -2921,39 +2926,44 @@ int bt_tbs_set_uri_scheme_list(uint8_t bearer_index, const char **uri_list, uint
...
+		}
 	}
 
-	if (strcmp(inst->uri_scheme_list, uri_scheme_list) == 0) {
-		/* identical; don't update or notify */
+	LOG_DBG("request to set uri prefix list %s", uri_scheme_list);
+
+	if ((len == 0) && (strlen(inst->uri_scheme_list) == strlen(uri_scheme_list))) {
+		/* no new uri-scheme added; don't update or notify */
+		LOG_DBG("All requested uri prefix are already in TBS uri-scheme list");
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c:2994]: I think this is interesting :) 

I don't think the TBS spec says anything about whether "skype,tel" and "tel,skype" are considered the same value, but I think it makes sense to treat it as the same value as you do here.

File: subsys/bluetooth/audio/tbs.c [hunk 11]
```diff
@@ -628,6 +629,35 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+	net_buf_simple_reset(buf);
+
+	/* For GTBS add all the URI scheme list the GTBS bearer has itself,
+	 * as well as all the other TBS bearers
+	 */
+
+	net_buf_simple_add_mem(buf, inst->uri_scheme_list, strlen(inst->uri_scheme_list));
+
+	if (inst_is_gtbs(inst)) {
+		for (size_t i = 0; i < ARRAY_SIZE(svc_insts); i++) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Do you think it makes sense to omit duplicates in the combined GTBS list? 

i.e. if 
GTBS = "tel"
TBS_1 = "skype"
TBS_2 = "skype,fax"

Should the final GTBS value be 
"tel,skype,skype,fax" or "tel,skype,fax"? 
The former may indicate that there are multiple TBS instances for "skype", but the latter is shorter. 

IIRC this is up to the implementation to decide

Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Yes, actually there is no point keeping duplicate entries in GTBS as there is no way to know which URI scheme belongs to which TBS from GTBS. It may be there to support general way of representing combined data to remote if some remote is not capable to run TBS client instances but need collective scheme run through server. I may be wrong though.  

I would try to work on this improvement in this PR, but if it takes longer than expected I would suggest having some improvement ticket and defer this activity under that to speed up current bug fix resolutions. I still have some more apps to validate as part of 4.2 timeline post that I would resume on this improvement. Let me know your thought. thank you :)

File: subsys/bluetooth/audio/tbs.c (hunk 7 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: oh, I missed that, thank you for this catch. :)

File: subsys/bluetooth/audio/tbs.c (hunk 6 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: agree, I will update the code as suggested. thank you :)

File: subsys/bluetooth/audio/tbs.c (hunk 11 above)
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: It would be an optimization at best, and fairly unlikely to be an issue, so I'm fine with deferring it.

File: subsys/bluetooth/audio/tbs.c [hunk 12]
```diff
@@ -2921,39 +2926,44 @@ int bt_tbs_set_uri_scheme_list(uint8_t bearer_index, const char **uri_list, uint
...
 			strcat(uri_scheme_list, ",");
 		}
 
 		len += strlen(uri_list[i]);
+
 		if (len > sizeof(uri_scheme_list) - 1) {
 			return -ENOMEM;
-		}
+		} else {
+			if (strstr(inst->uri_scheme_list, uri_list[i]) != NULL) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: `strstr` checks for substrings. This may actually cause an issue (however very unlikely). 

TBS refer to https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml for URI schemes, 

and `strstr` would treat e.g. `aaa` and `aaas` as the same, `ar`, `ari`, and `ark` as the same, `bl` and `blob` as the same, etc. 

So either the check should ensure that the check the entire URI (and not just check for substrings), or perhaps we should actually store the URI list as an array, rather than a single string, in the instances themselves. 

We could also just skip this check and consider "skype,tel" and "tel,skype" as 2 different values.

Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Hi @Thalley, I understand your point. I fixed it with current logic by doing exact match of URI prefix. I tested that logic and it worked fine. please review.

File: subsys/bluetooth/audio/tbs.c (hunk 11 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Hi @Thalley, I added the check to add only unique URI prefix in the list. please review. thank you.

File: subsys/bluetooth/audio/tbs.c [hunk 13]
```diff
@@ -111,10 +113,12 @@ struct tbs_inst {
...
-#define READ_BUF_SIZE                                                                              \
-	MAX(BT_ATT_MAX_ATTRIBUTE_LEN,                                                              \
-	    (CONFIG_BT_TBS_MAX_CALLS * sizeof(struct bt_tbs_current_call_item) *                   \
-	     (1U + ARRAY_SIZE(svc_insts))))
+#define READ_BUF_SIZE                                                                             \
+	MAX(BT_ATT_MAX_ATTRIBUTE_LEN,                                                             \
+	    MAX((CONFIG_BT_TBS_MAX_CALLS * sizeof(struct bt_tbs_current_call_item) *              \
+	    (1U + ARRAY_SIZE(svc_insts))),                                                        \
+	    (CONFIG_BT_TBS_BEARER_COUNT * CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH +                  \
+	     CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH)))
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: I think the identation here should be 

```suggestion
	    MAX((CONFIG_BT_TBS_MAX_CALLS * sizeof(struct bt_tbs_current_call_item) *              \
		(1U + ARRAY_SIZE(svc_insts))),                                                    \
		(CONFIG_BT_TBS_BEARER_COUNT * CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH +              \
		 CONFIG_BT_TBS_MAX_SCHEME_LIST_LENGTH)))
```

File: subsys/bluetooth/audio/tbs.c [hunk 14]
```diff
@@ -628,6 +632,54 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+					      !isalnum(*(uri_pos - 1))) &&
+					      (!isalnum(*(uri_pos + uri_len)))) {
+						uri_to_search = strtok(NULL, ",");
+						continue;
+					}
+				} else {
+					if ((buf->len + strlen(uri_to_search) + 1) >= buf->size) {
+						LOG_WRN("Cannot fit all TBS URI in GTBS URI list");
+						is_mem_avail = false;
+						break;
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Since you are using `is_mem_avail` to break the for loop, you could just do `return` here instead and remove the variable.

File: subsys/bluetooth/audio/tbs.c [hunk 15]
```diff
@@ -628,6 +632,54 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+{
+	net_buf_simple_reset(buf);
+
+	/* For GTBS add all the URI scheme list the GTBS bearer has itself,
+	 * as well as all the other TBS bearers
+	 */
+
+	net_buf_simple_add_mem(buf, inst->uri_scheme_list, strlen(inst->uri_scheme_list));
+
+	if (inst_is_gtbs(inst)) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]:
```suggestion
	net_buf_simple_add_mem(buf, inst->uri_scheme_list, strlen(inst->uri_scheme_list));

	/* For GTBS add all the URI scheme list the GTBS bearer has itself,
	 * as well as all the other TBS bearers
	 */
	if (inst_is_gtbs(inst)) {
```

File: subsys/bluetooth/audio/tbs.c [hunk 16]
```diff
@@ -628,6 +632,54 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+		char *uri_pos = NULL;
+		char *uri_to_search = NULL;
+		bool is_mem_avail = true;
+		size_t uri_len = 0;
+
+		for (size_t i = 0; i < ARRAY_SIZE(svc_insts) && is_mem_avail; i++) {
+			uri_to_search = strtok(svc_insts[i].uri_scheme_list, ",");
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: `net_buf_put_uri_scheme_list` may be called in either the BT RX thread (when a remote device is doing a read), or in the System workqueue thread (when we are handling pending notifications). 

`strtok` is not threadsafe, so if you wish to use that functionality, we need to use `strtok_r`. 

Alternatively, we need to ensure that `net_buf_put_uri_scheme_list` is only ever handled by a single thread. 

Additionally, `bt_tbs_set_uri_scheme_list` must not modify the `uri_scheme_list` of any instance while we are in `net_buf_put_uri_scheme_list`

File: subsys/bluetooth/audio/tbs.c [hunk 17]
```diff
@@ -628,6 +632,54 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+			/* append only unique URI prefix from all TBS instances in GTBS instance */
+			while (uri_to_search != NULL) {
+				uri_len = strlen(uri_to_search);
+				uri_pos = strstr((char *)buf->data, uri_to_search);
+				/* check for complete match of uri-prefix */
+				if (uri_pos != NULL) {
+					if ((uri_pos == (char *)buf->data ||
+					      !isalnum(*(uri_pos - 1))) &&
+					      (!isalnum(*(uri_pos + uri_len)))) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: What is the purpose of `isalnum`? Can't we assume that the URI schemes are already valid?

File: subsys/bluetooth/audio/tbs.c [hunk 18]
```diff
@@ -2920,40 +2947,50 @@ static void set_bearer_uri_schemes_supported_list_changed_cb(struct tbs_flags *f
...
+		} else {
+			uri_pos = strstr(inst->uri_scheme_list, uri_list[i]);
+			if (uri_pos != NULL) {
+				/* check for complete match of uri prefix */
+				if ((uri_pos == inst->uri_scheme_list ||
+				      !isalnum(*(uri_pos - 1))) &&
+				     (!isalnum(*(uri_pos + strlen(uri_list[i]))))) {
+					len -= strlen(uri_list[i]);
+				}
+			}
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Could we make this into a function that can also be used by `net_buf_put_uri_scheme_list`? 

Either way, I think the comment needs to be elaborated a bit; at least it's unclear to me how these lines check for a match

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/tbs.c (hunk 14 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: yes, thanks for your input. I will update.

File: subsys/bluetooth/audio/tbs.c (hunk 16 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Ok, I will update to threadsafe function call and ensure it does not change any scheme list value under `net_buf_put_uri_scheme_list`. thank you.

File: subsys/bluetooth/audio/tbs.c (hunk 17 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Hi @Thalley, 

As you have mentioned earlier that there can be URI prefix which would have something like, 
`"aaa and aaas as the same, ar, ari, and ark as the same, bl and blob as the same, etc."`

In previous change, "strstr" function could not identify exact match and provide entire substring value. If existing URI buffer has "aaas" and new request is for "aaa" it should be treated as new URI but "strstr()" finds "aaas" as it matches search substring "aaa" and could not find uniqueness of substring. 
 
To fix this issue, code is updated as below,

-  `"strstr()"` gives first position` "uri_pos"` of the searched substring in string buffer. If the position is not `NULL`, meaning there is substring found in given string. 
-  "`uri_pos`" pointer is now checked if it is same address with string buffer address. If yes, it means the substring is present at the start of the string and before that there is not any other string present.
- If "`uri_pos`" is not same as start address of searched string, it means searched substring is not present in start of string but anywhere in entire string. so, we need to check that searched substring must not have any alpha-numeric characters before it to ensure its uniqueness. Also, we need to validate that searched substring must not have any alpha-numeric characters post end of substring. 
- If complete match found, it means string buffer has exact URI prefix searched and can be skipped by continuing the next iteration.

I have validated the code and is works well in scenarios where URI prefix can be `"aaa", "aaas", "saaa"` like string where it is considering all as a unique URI and not a duplicate entry. 

Please let me know if you need to understand more. thank you :)

File: subsys/bluetooth/audio/tbs.c (hunk 16 above)
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: We may need to check if that is the case for some of the other values as well that follow the same pattern - I can't remember if they are thread safe or not :)

File: subsys/bluetooth/audio/tbs.c (hunk 17 above)
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: AFAIK `isalnum` returns true if the character is alphanumeric or not; it's specifically the use of `isalnum` that I'm not really understanding here :D

Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Hi @Thalley, yes, `isalnum` used to detect if current address consists of any alphanumeric character or no. 
I've used `isalnum` to check URI prefix pre and post substring (should be alpha or numeric char) to check if substring has any combinations like` "teltel" for "tel" or "skypee" for "skype" `tokens. using `isalnum` function, it detects that` "tel" `token has some alpha-numeric character `"t"` after token "tel" or has` "e" `char after token `"skype". `

I am considering here the substring may have alpha-numeric character around it (which are only few URI prefix). 
we can also check that end position of substring should always appended with either `NULL` or` ","` instead of `isalnum` check to find unique URI. and similar for checking starting position of substring with either string buffer address or` ",". `

I have updated PR as per your given comments. Let me know your inputs. thank you :)

Regards,
Nirav

File: subsys/bluetooth/audio/tbs.c (hunk 18 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Yes, added check in separate function now. thank you :)

Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: @Thalley, it seems like some twister builds are failing due to use of "strtok_r" function where some build might not add use minimal LIBC support or something different. I may not have correct resolution to fix this. need your inputs. thank you :)

Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: Hmm, yeah I see that. 

`strtok_r` should be allowed by https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#id19

As per https://docs.zephyrproject.org/latest/services/portability/posix/option_groups/index.html#posix-c-lang-support-r it seems that we need to enable `CONFIG_POSIX_C_LANG_SUPPORT_R` in order to use that. Can be enabled directly, or by enabling `CONFIG_POSIX_THREAD_SAFE_FUNCTIONS`. 

If we want to use strtok (instead of implementing something ourselves in TBS), I guess we need to either `select` one of the above when TBS is enabled, or have TBS `depend on` either of the above (generally `depends on` is preferred over `select`)

**Comment by Thalley** [comment]
@nirav-agrawal if we ensure that `net_buf_put_uri_scheme_list` is not called by more than 1 thread (which we should), then we can rely on `strtok` instead of `strtok_r`, as that function won't need to be threadsafe if the entire block is threadsafe, right?

**Comment by nirav-agrawal** [comment]
> @nirav-agrawal if we ensure that `net_buf_put_uri_scheme_list` is not called by more than 1 thread (which we should), then we can rely on `strtok` instead of `strtok_r`, as that function won't need to be threadsafe if the entire block is threadsafe, right?

Hi @Thalley, I could see that "`net_buf_put_uri_scheme_list`" would be called from two threads, one from worker_notify thread to send notification and other from thread responsible to serve char. read request (through bt-recv worker thread). It may be possible race condition here. I reverted `strtok_r` with `strtok`, and updated code with TBS instance mutex lock/unlock to access URI scheme list which may fix such race condition. To lock mutex per instance, I am not sure if we need to continue if mutex lock is not available for any instance and also what timeout we can use. Currently I have set it `K_NO_WAIT`. It needs your review. thank you :)

File: subsys/bluetooth/audio/tbs.c [hunk 19]
```diff
@@ -628,6 +632,73 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+	/* Below check is to avoid match for string like "aaa" with "aaas" or "saaa" string present
+	 * in uri_list.
+	 */
+
+	if ((uri_pos != NULL) && ((uri_pos == uri_list) || (!isalnum(*(uri_pos - 1)))) &&
+	    (!isalnum(*(uri_pos + uri_len)))) {
+		is_matched = true;
+	}
+
+	return is_matched;
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c:650]: Did you consider using `strtok` here as well, instead of the somewhat hard to read `if` statement? 

```suggestion
	/* Split URI list by comma */
	const char *uri = uri_list(str, ",");
	
	/* Check each URI in URI list if they are identical to uri_to_search */
	while (uri != NULL) {
		if (strcmp(uri, uri_to_search) == 0) {
			return false;
		}
	
		uri = strtok(NULL, ",");
	}
   
	return true;
```

Basically applying the same approach for each URI in `uri_list` as you do for `svc_insts[i].uri_scheme_list`

File: subsys/bluetooth/audio/tbs.c [hunk 20]
```diff
@@ -628,6 +632,73 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+
+	/* For GTBS add all the URI scheme list the GTBS bearer has itself, as well as all
+	 * the other TBS bearers
+	 */
+
+	if (inst_is_gtbs(inst)) {
+		char *uri_to_search = NULL;
+		int err = 0;
+
+		for (size_t i = 0; i < ARRAY_SIZE(svc_insts); i++) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]:
```suggestion

		for (size_t i = 0; i < ARRAY_SIZE(svc_insts); i++) {
			const char *uri_to_search;
			int err;
```

File: subsys/bluetooth/audio/tbs.c [hunk 21]
```diff
@@ -628,6 +632,73 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+{
+	net_buf_simple_reset(buf);
+
+	net_buf_simple_add_mem(buf, inst->uri_scheme_list, strlen(inst->uri_scheme_list));
+
+	/* For GTBS add all the URI scheme list the GTBS bearer has itself, as well as all
+	 * the other TBS bearers
+	 */
+
+	if (inst_is_gtbs(inst)) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Consider changing this to
```suggestion
	if (!inst_is_gtbs(inst)) {
		return;
	}
```

To avoid the additional indentation level below

File: subsys/bluetooth/audio/tbs.c [hunk 22]
```diff
@@ -628,6 +632,73 @@ static void net_buf_put_current_calls(const struct tbs_inst *inst, struct net_bu
...
+		char *uri_to_search = NULL;
+		int err = 0;
+
+		for (size_t i = 0; i < ARRAY_SIZE(svc_insts); i++) {
+			err = k_mutex_lock(&svc_insts[i].mutex, K_NO_WAIT);
+			if (err != 0) {
+				LOG_DBG("Failed to lock mutex");
+				continue;
+			}
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: I think it makes more sense to guard the entire call to `net_buf_put_uri_scheme_list` with the mutex. 

That is actually already being done in the `read_uri_scheme_list` and `notify_handler_cb`, so we are already pretty guarded. 

One place where it is a bit tricky (and that seems to apply for several other characteristics, is the cases where the GTBS contains the values of all other TBS. I think this is a generic issue that should probably be handled outside the scope of this PR. 

So since calls to `net_buf_put_uri_scheme_list` is already guarded by a mutex, I think we remove the locks from within the function again, and then design a solution that can be applied to all similar characteristics. Basically I think that when we are constructing the GTBS values, we need to take the mutex of all TBS instances at the same time, to avoid any changes to their values while we are building the complete value.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/tbs.c (hunk 22 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c]: Hi @Thalley, I understand your point. is it okay if we do implementation for protecting all tbs instances for characterises which require access to all tbs instance to prepare GTBS instance value outside of this PR as this PR is only targeted to fix unique URI constructing issue for GTBS?

In current PR, I can remove lock/unlock related calls from the function thought. 

Regards,
Nirav

File: subsys/bluetooth/audio/tbs.c (hunk 19 above)
Comment (nirav-agrawal) [reply subsys/bluetooth/audio/tbs.c:650]: Hi @Thalley, 
I have one concern with usage of `struct net_buf_simple *buf ` for string search related operations.  If we take some local character array and use that to prepare GTBS values, it will have more clean solution instead using net-buf instance. I am not sure if this is valid issue but need your help to understand

Would it be possible that `net_buf` instance which will be searched for string operation (e.g. `strstr`, `strtok`) which may have garbage values and may not have all zero or null terminator at correct place? 
I have this concern because I could see `net_buf_simple_reset()` function is only resetting `net_buf` instance but not clearing any data present in the buffer. If the data instance is not cleared before preparing GTBS URI values, it can mislead search operation due to present of garbage data (e.g. it may not have null-terminator, or have multiple "," as part of garbage content due to that search api may provide incorrect large token values).

Please advise your view on it :)

Regards,
Nirav

File: subsys/bluetooth/audio/tbs.c (hunk 22 above)
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c]: > is it okay if we do implementation for protecting all tbs instances for characterises which require access to all tbs instance to prepare GTBS instance value outside of this PR as this PR is only targeted to fix unique URI constructing issue for GTBS?

Yeah, I think we should do that in a follow-up PR. It needs to be done for several other characteristics as well, so let's have this PR focus on the URI schemes only :) (it's quite unlikely to be an issue anyhow)

File: subsys/bluetooth/audio/tbs.c (hunk 19 above)
Comment (Thalley) [reply subsys/bluetooth/audio/tbs.c:650]: I think I understand your concern, and that is valid. 

Doing operations like `net_buf_simple_add_mem(buf, inst->uri_scheme_list, strlen(inst->uri_scheme_list));` won't add NULL termination of the buffer. 

Adding the NULL terminator is a fairly simple matter, but there isn't a `net_buf_simple_add_str` to help correctly append strings to the list of URIs. 

In many ways, I think it would be simpler (although probably more memory intensive?) to use array of strings for storage, rather than storing them comma-separated. 

So I guess that's your point with using `isalnum`, right? That it helps determine the end of the non-NULL terminated "string"? 

Perhaps using `strcat` over `net_buf_simple_add_mem` and the manually increasing the buffer length could work?

**Review by Thalley — APPROVED** [review]

**Review by larsgk — APPROVED** [review]
