### PR TITLE
drivers: serial: nrfx_uarte: Add support to DMM  and data cache and other minor tweaks

### LINKED ISSUE #77060: Race Condition in uarte_nrfx_rx_disable Function
**Description of the Bug**
The function `uarte_nrfx_rx_disable` in `/sdk-zephyr/drivers/serial/uart_nrfx_uarte.c` assigns values to certain flags that are used to disable the RX in the ISR. However, `uarte_nrfx_rx_disable` is not safe when the RX is disabled in parallel within the ISR.

An edge case was encountered where, just before the application thread called `uarte_nrfx_rx_disable`, a UART framing error triggered an interrupt, which called `uarte_nrfx_rx_disable` in the ISR. During the execution of `uarte_nrfx_rx_disable` in the application thread - just before the RX disabling flags were set - the thread was interrupted by the ISR that disable the RX due to the UART framing error.

After returning to the application thread execution, the flags in `uarte_nrfx_rx_disable` were set again, but the ISR to disable RX was never happen. Consequently, it became impossible to re-enable RX due to the flags set in `uarte_nrfx_rx_disable`. The driver still waits for disable RX, even though it has already happened.

**To Reproduce**
1. Develop an application that experiences frequent UART framing errors.
2. Continuously start and stop reading data from the UART.

**Proposed Solution**
To prevent `uarte_nrfx_rx_disable` from being interrupted during its execution, interrupt locks should be added inside the function. This will ensure that the function cannot be preempted by an ISR while it is in progress.

Here’s how you could modify the function:
```
static int uarte_nrfx_rx_disable(const struct device *dev)
{
	struct uarte_nrfx_data *data = dev->data;
	NRF_UARTE_Type *uarte = get_uarte_instance(dev);
	unsigned int key = irq_lock();
	if (data->async->rx_buf == NULL) {
		irq_unlock(key);
		return -EFAULT;
	}
	if (data->async->rx_next_buf != NULL) {
		nrf_uarte_shorts_disable(uarte, NRF_UARTE_SHORT_ENDRX_STARTRX);
		nrf_uarte_event_clear(uarte, NRF_UARTE_EVENT_RXSTARTED);
	}
	k_timer_stop(&data->async->rx_timeout_timer);
	data->async->rx_enabled = false;
	data->async->discard_rx_fifo = true;
	nrf_uarte_task_trigger(uarte, NRF_UARTE_TASK_STOPRX);
	
	irq_unlock(key);
	return 0;
}
```

**Impact**
RX can no longer be activated.

**Environment**
OS: Linux
Toolchain: Zephyr SDK 0.16.3
Nordic Zephyr Version: 3.4.99-ncs1-1 (SHA 83980fe1679441be9b0e1db556a353f6118fe14f)

### PR DESCRIPTION
**Pull request by nordic-krch**
Add support for DMM and cache.
Add configurable magic word used for RX flush workaround.
Add workaround for lack of retention of the BAUDRATE register in UARTE120.
Add lock to uart_rx_disable.

Fixes #77060.

### CODE REVIEW

File: drivers/serial/uart_nrfx_uarte.c [hunk 1]
```diff
@@ -15,19 +15,28 @@
...
 #include <zephyr/sys/util.h>
 #include <zephyr/kernel.h>
+#include <zephyr/cache.h>
 #include <soc.h>
 #include <helpers/nrfx_gppi.h>
 #include <zephyr/linker/devicetree_regions.h>
 #include <zephyr/irq.h>
 #include <zephyr/logging/log.h>
 LOG_MODULE_REGISTER(uart_nrfx_uarte, CONFIG_UART_LOG_LEVEL);
+#ifdef CONFIG_HAS_NORDIC_DMM
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:25]: is this really needed? for legacy platforms these macros in question should evaluate to nothing/`0` : 
- https://github.com/zephyrproject-rtos/zephyr/blob/98e0e65069cf62297c4d03e0ad5b543374f5b735/soc/nordic/common/dmm.h#L61
- https://github.com/zephyrproject-rtos/zephyr/blob/98e0e65069cf62297c4d03e0ad5b543374f5b735/soc/nordic/common/dmm.h#L28

File: drivers/serial/uart_nrfx_uarte.c [hunk 2]
```diff
@@ -2227,11 +2376,15 @@ static int uarte_nrfx_pm_action(const struct device *dev,
...
 		.uarte_regs = _CONCAT(NRF_UARTE, idx),                         \
+		IF_ENABLED(CONFIG_HAS_NORDIC_DMM,			       \
+				(.mem_reg = DMM_DEV_TO_REG(UARTE(idx)),))      \
 		.flags =						       \
 			(IS_ENABLED(CONFIG_UART_##idx##_ENHANCED_POLL_OUT) ?   \
 				UARTE_CFG_FLAG_PPI_ENDTX : 0) |		       \
 			(IS_ENABLED(CONFIG_UART_##idx##_NRF_HW_ASYNC) ?        \
 				UARTE_CFG_FLAG_HW_BYTE_COUNTING : 0) |	       \
+			(!IS_ENABLED(CONFIG_HAS_NORDIC_DMM) ? 0 :	       \
+			  (UARTE_IS_CACHEABLE(idx) ? UARTE_CFG_FLAG_CACHEABLE : 0)) | \
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uarte.c:2387]: `UARTE_IS_CACHEABLE(idx)` evaluates to `false` when `!CONFIG_HAS_NORDIC_DMM`, so:
```suggestion
			(UARTE_IS_CACHEABLE(idx) ?			       \
				UARTE_CFG_FLAG_CACHEABLE : 0) |		       \
```

File: drivers/serial/uart_nrfx_uarte.c [hunk 3]
```diff
@@ -571,6 +621,10 @@ static void tx_start(const struct device *dev, const uint8_t *buf, size_t len)
 	}
 #endif
 
+	if (IS_ENABLED(UARTE_ANY_CACHE) && (config->flags & UARTE_CFG_FLAG_CACHEABLE)) {
+		sys_cache_data_flush_range((void *)buf, len);
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:625]: theoretically you could indiscriminately use `dmm_buffer_out_prepare` that would flush the cache for you and be transparent for the legacy targets. But I guess this could be purposefully omitted for performance reasons

File: drivers/serial/uart_nrfx_uarte.c [hunk 4]
```diff
@@ -877,6 +931,19 @@ static int uarte_nrfx_rx_enable(const struct device *dev, uint8_t *buf,
 		return -EBUSY;
 	}
 
+#ifdef CONFIG_HAS_NORDIC_DMM
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:934]: this could should compile fine for legacy targets as well - `dmm_buffer_in_prepare` is mocked for them: https://github.com/zephyrproject-rtos/zephyr/blob/98e0e65069cf62297c4d03e0ad5b543374f5b735/soc/nordic/common/dmm.h#L134

File: drivers/serial/uart_nrfx_uarte.c [hunk 5]
```diff
@@ -909,8 +976,18 @@ static int uarte_nrfx_rx_enable(const struct device *dev, uint8_t *buf,
 		if (async_rx->flush_cnt) {
 			int cpy_len = MIN(len, async_rx->flush_cnt);
 
+			if (IS_ENABLED(UARTE_ANY_CACHE) &&
+			    (cfg->flags & UARTE_CFG_FLAG_CACHEABLE)) {
+				sys_cache_data_invd_range(cfg->rx_flush_buf, cpy_len);
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:981]: I guess this shouldn't be covered by `dmm`, as this is a case in which both `rx_flush_buf` and `buf` are located in cacheable RAM and in fact we are "emulating" DMA copying data from the former to the latter ?

File: drivers/serial/uart_nrfx_uarte.c [hunk 6]
```diff
@@ -921,6 +998,11 @@ static int uarte_nrfx_rx_enable(const struct device *dev, uint8_t *buf,
 				async_rx->flush_cnt -= cpy_len;
 				memmove(cfg->rx_flush_buf, &cfg->rx_flush_buf[cpy_len],
 						async_rx->flush_cnt);
+				if (IS_ENABLED(UARTE_ANY_CACHE) &&
+				    (cfg->flags & UARTE_CFG_FLAG_CACHEABLE)) {
+					sys_cache_data_flush_range(cfg->rx_flush_buf,
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:1003]: as above - `dmm` shouldn't be used here as this is a shim-specific code maintaining `rx_flush_buf` that happens to be located in cached RAM, right ?

File: drivers/serial/uart_nrfx_uarte.c [hunk 7]
```diff
@@ -966,6 +1048,17 @@ static int uarte_nrfx_rx_buf_rsp(const struct device *dev, uint8_t *buf,
 	if (async_rx->buf == NULL) {
 		err = -EACCES;
 	} else if (async_rx->next_buf == NULL) {
+#ifdef CONFIG_HAS_NORDIC_DMM
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:1051]: as above - this could should compile fine for legacy targets as well - `dmm_buffer_in_prepare` is mocked for them: https://github.com/zephyrproject-rtos/zephyr/blob/98e0e65069cf62297c4d03e0ad5b543374f5b735/soc/nordic/common/dmm.h#L134

File: drivers/serial/uart_nrfx_uarte.c [hunk 8]
```diff
@@ -1235,6 +1334,15 @@ static void endrx_isr(const struct device *dev)
 	 */
 	const int rx_amount = nrf_uarte_rx_amount_get(uarte) + async_rx->flush_cnt;
 
+#ifdef CONFIG_HAS_NORDIC_DMM
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:1337]: as above - this could should compile fine for legacy targets as well - `dmm_buffer_in_release` is mocked for them

File: drivers/serial/uart_nrfx_uarte.c [hunk 9]
```diff
@@ -112,6 +137,10 @@ struct uarte_async_tx {
 
 struct uarte_async_rx {
 	struct k_timer timer;
+#ifdef CONFIG_HAS_NORDIC_DMM
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:140]: there are several comments regarding indiscriminate usage of `dmm` APIs everywhere VS small potential savings in state variables. If you find them valuable they can stay, I guess

File: drivers/serial/Kconfig.nrfx [hunk 10]
```diff
@@ -57,6 +57,16 @@ config UART_ASYNC_TX_CACHE_SIZE
 	  in RAM, because EasyDMA in UARTE peripherals can only transfer data
 	  from RAM.
 
+config UART_NRFX_UARTE_RX_FLUSH_MAGIC_BYTE
+	int "Byte used for RX FIFO flush workaround"
+	default 171
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx:62]: Was it intentional that now the default magic byte is different (0xAB) than previously used 0xAA?
And wouldn't a hexadecimal number be more natural here?

File: drivers/serial/uart_nrfx_uarte.c [hunk 11]
```diff
@@ -1633,6 +1766,10 @@ static int uarte_nrfx_poll_in(const struct device *dev, unsigned char *c)
 		return -1;
 	}
 
+	if (IS_ENABLED(UARTE_ANY_CACHE) && (config->flags & UARTE_CFG_FLAG_CACHEABLE)) {
+		sys_cache_data_invd_range(config->poll_in_byte, 1);
```
Comment (nika-nordic) [inline drivers/serial/uart_nrfx_uarte.c:1770]: `poll_in_byte` could be managed by `dmm` to avoid manual cache management in this case. `dmm_buffer_in_prepare` would need to be called before starting the receiver and `dm_buffer_in_release` on ENDRX. But again, this looks like special case as this single byte is used internally by shim while `dmm` was rather designed for user-provided buffers

**Review by nika-nordic — DISMISSED** [review]
Left some comments regarding `dmm` usage. It could be debated how widely it should be used in this shim, however rule of thumb is that `dmm` was designed for user-provided buffers, while UARTE shim has some internal buffers ( `rx_flush_buf`, `poll_in_byte` ) where `dmm` could be an overkill

File: drivers/serial/uart_nrfx_uarte.c [hunk 12]
```diff
@@ -2042,12 +2183,19 @@ static int uarte_nrfx_pm_action(const struct device *dev,
...
 		if (ret < 0) {
 			return ret;
 		}
 
 		nrf_uarte_enable(uarte);
+#if UARTE_BAUDRATE_RETENTION_WORKAROUND
+		nrf_uarte_baudrate_t baudrate = COND_CODE_1(CONFIG_UART_USE_RUNTIME_CONFIGURE,
+			(data->nrf_baudrate), (cfg->nrf_baudrate));
+
+		nrf_uarte_baudrate_set(get_uarte_instance(dev), baudrate);
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uarte.c:2197]: Why not just:
```suggestion
		nrf_uarte_baudrate_set(get_uarte_instance(dev),
			COND_CODE_1(CONFIG_UART_USE_RUNTIME_CONFIGURE,
				(data->nrf_baudrate), (cfg->nrf_baudrate)));
```
to avoid those extra braces?

File: drivers/serial/uart_nrfx_uarte.c (hunk 4 above)
Comment (nordic-krch) [reply drivers/serial/uart_nrfx_uarte.c:934]: im ifdefing because for dmm case there are additional fields in the data and config structure to hold user buffer (as it is different one than one used for DMA) and `mem_reg`. We could keep this for non-dmm cases and that would work but then its redundant so i preferred to ifdef it.

File: drivers/serial/Kconfig.nrfx [hunk 13]
```diff
@@ -57,6 +57,16 @@ config UART_ASYNC_TX_CACHE_SIZE
 	  in RAM, because EasyDMA in UARTE peripherals can only transfer data
 	  from RAM.
 
+config UART_NRFX_UARTE_RX_FLUSH_MAGIC_BYTE
+	int "Byte used for RX FIFO flush workaround"
+	default 170 # 0xAA
```
Comment (anangl) [inline drivers/serial/Kconfig.nrfx:62]: `default 0xAA` should also work.

**Review by anangl — DISMISSED** [review]

File: drivers/serial/Kconfig.nrfx (hunk 10 above)
Comment (nordic-krch) [reply drivers/serial/Kconfig.nrfx]: Yes, it was intentional, as BT guys asked to use something different than 0xAA because their tests were hitting an error due to 0xAA use. However, today I've got information from them that 0xAB is also not good. We will be looking for another solution to their issue so I get back here to 0xAA. I was not aware of `hex`. Changed to use that.

File: drivers/serial/uart_nrfx_uarte.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/serial/uart_nrfx_uarte.c]: removed.

**Comment by nordic-krch** [comment]
@anangl your comments applied.
@nika-nordic some comments applied. Due to resources usage I would stay with what we got regarding use of dmm where it is not needed.

**Review by anangl — DISMISSED** [review]

**Review by bjarki-andreasen — DISMISSED** [review]

**Comment by nordic-krch** [comment]
After including dmm.h unconditionally `nrf52_bsim` target compilation started to fail due to lack of `soc/nordic/common` include path. I've added it to bsim boards. @aescolar can you take a look if that is ok?

**Comment by aescolar** [comment]
> I've added it to bsim boards. @aescolar can you take a look if that is ok?

@nordic-krch I think that is fine

**Review by anangl — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by nika-nordic — APPROVED** [review]

**Review by aescolar — APPROVED** [review]
