### PR TITLE
coredump: ARM: Ensure sp in dump is set as gdb expects

### LINKED ISSUE #78788: Exception Stack Frames are not correct in coredumps
**Exception Stack Frames are not correct in coredumps**

The stack pointer in the Zephyr ARM Coredumps are imprecise due to an error in the stack offset calculation:
https://github.com/zephyrproject-rtos/zephyr/blob/c3438903d25c8cc9b06c9663f84ab6e37ec00673/arch/arm/core/cortex_m/fault.c#L1115-L1117

The stackpointer can't be calculated without EXC_RETURN. We don't have a reliable way to calculate it outside of the coredump handler.

I see we have an existing PR that would resolve this issue: PR #73189.

**To Reproduce**
With an ARM M4 MCU with FPU extension (e.g. nRF52833):
  1. have one thread doing floating point math
  2. have one thread that doesn't do floating point math
  3. grab a few coredumps
  4. unwind and symbolicate the coredumps, one will fail to unwind properly

**Expected behavior**
I expect the SP to be accurate :)

**Impact**
This prevents us from using upstream Zephyr.

**Interesting Docs**
 * [Exception Return Behavior](https://developer.arm.com/documentation/ddi0403/d/System-Level-Architecture/System-Level-Programmers--Model/ARMv7-M-exception-model/Exception-return-behavior?lang=en)
  * [Exception Stack Frames](https://developer.arm.com/documentation/107706/0100/Exceptions-and-interrupts-overview/Stack-frames)
   * [Stack Alignment](https://developer.arm.com/documentation/ddi0403/d/System-Level-Architecture/System-Level-Programmers--Model/ARMv7-M-exception-model/Stack-alignment-on-exception-entry?lang=en#:~:text=On%20an%20exception%20return%20when,performed%20on%20the%20exception%20entry)

### PR DESCRIPTION
**Pull request by mrkhldn**
Gdb is typically able to reconstruct the first two frames of the failing stack using the "pc" and "lr" registers. After that, (if the frame pointer is omitted) it appears to need the stack pointer (sp register) to point to the top of the stack before a fatal error occurred.

The ARM Cortex-M7 processor pushes registers r0-r3, r12, LR, {possibly FPU registers}, PC, SPSR onto the stack before entering the exception handler. We adjust the stack pointer back to the point before these registers were pushed for preservation in the dump.

During k_oops/k_panic, the sp wasn't stored in the core dump at all. Apply similar logic to store it when failures occur in that path.

### CODE REVIEW

**Comment by kartben** [comment]
@mrkhldn can you rebase to solve conflict?

File: arch/arm/core/cortex_m/fault.c [hunk 1]
```diff
@@ -1114,7 +1066,23 @@ void z_arm_fault(uint32_t msp, uint32_t psp, uint32_t exc_return,
 
 #ifdef CONFIG_DEBUG_COREDUMP
 	z_arm_coredump_fault_sp = POINTER_TO_UINT(esf);
-#endif
+#if defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
+	/* Gdb expects a stack pointer that does not include the exception stack frame in order to
+	 * unwind. So adjust the stack pointer accordingly.
+	 */
+	z_arm_coredump_fault_sp += sizeof(esf->basic);
```
Comment (ithinuel) [inline arch/arm/core/cortex_m/fault.c:1073]: Doesn't this also apply to Cortex-M0/+ and Cortex-M23 (Armv6-m and Armv8-m.baseline) ?

File: arch/arm/core/fatal.c [hunk 2]
```diff
@@ -101,15 +101,39 @@ void z_arm_fatal_error(unsigned int reason, const struct arch_esf *esf)
...
 	unsigned int reason = esf->basic.r0;
 
+#ifdef CONFIG_DEBUG_COREDUMP
+	z_arm_coredump_fault_sp = POINTER_TO_UINT(esf);
+
+#if defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
+	/* Gdb expects a stack pointer that does not include the exception stack frame in order to
+	 * unwind. So adjust the stack pointer accordingly.
+	 */
+	z_arm_coredump_fault_sp += sizeof(esf->basic);
```
Comment (ithinuel) [inline arch/arm/core/fatal.c:121]: ditto

File: arch/arm/core/cortex_m/fault.c (hunk 1 above)
Comment (mrkhldn) [reply arch/arm/core/cortex_m/fault.c:1073]: Yes, looks like you are right, I'll update

File: arch/arm/core/fatal.c (hunk 2 above)
Comment (mrkhldn) [reply arch/arm/core/fatal.c:121]: Updated here as well

**Comment by mrkhldn** [comment]
For reference, using the coredump_gdbserver.py script and connection from gdb to get the backtrace, before this change when using the output of the test at tests/subsys/debug/coredump_backends/debug.coredump.backends.logging:

(Wrong stack)
```
(gdb) bt
#0  dump_entry (p1=<optimized out>, p2=0x0 <cbvprintf_package>, p3=0x0 <cbvprintf_package>) at ~/zephyrproject/zephyr/tests/subsys/debug/coredump_backends/src/main.c:34
#1  0x00000e84 in z_arm_usage_fault ()
#2  0x00000e70 in z_arm_fault_init () at ~/zephyrproject/zephyr/arch/arm/core/cortex_m/fault.c:1196
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

And after this change:
(Expected stack)
```
(gdb) bt
#0  dump_entry (p1=<optimized out>, p2=0x0 <cbvprintf_package>, p3=0x0 <cbvprintf_package>) at ~/zephyrproject/zephyr/tests/subsys/debug/coredump_backends/src/main.c:34
#1  0x000008b0 in z_thread_entry (entry=0x3ad <dump_entry>, p1=0x0 <cbvprintf_package>, p2=0x0 <cbvprintf_package>, p3=0x0 <cbvprintf_package>)
    at ~/zephyrproject/zephyr/lib/os/thread_entry.c:48
#2  0x00000000 in ?? ()
```

**Review by ithinuel — DISMISSED** [review]

File: arch/arm/core/cortex_m/fault.c [hunk 3]
```diff
@@ -1114,7 +1066,23 @@ void z_arm_fault(uint32_t msp, uint32_t psp, uint32_t exc_return,
...
+	/* Assess whether thread had been using the FP registers and add size of additional
+	 * registers if necessary
+	 */
+	if ((exc_return & EXC_RETURN_STACK_FRAME_TYPE_STANDARD) ==
+			EXC_RETURN_STACK_FRAME_TYPE_EXTENDED) {
+		z_arm_coredump_fault_sp += sizeof(esf->fpu);
+	}
+#endif /* CONFIG_FPU && CONFIG_FPU_SHARING */
+#endif /* CONFIG_ARMV7_M_ARMV8_M_MAINLINE || CONFIG_ARMV6_M_ARMV8_M_BASELINE */
+#endif /* CONFIG_DEBUG_COREDUMP */
```
Comment (arbrauns) [inline arch/arm/core/cortex_m/fault.c:1085]: style: how about extracting all this into a `static inline` in `exception.h` so the whole ifdef mess doesn't have to be implemented in two places?

File: arch/arm/core/fatal.c [hunk 4]
```diff
@@ -101,15 +101,39 @@ void z_arm_fatal_error(unsigned int reason, const struct arch_esf *esf)
  *
  * @param esf exception frame
  * @param callee_regs Callee-saved registers (R4-R11)
+ * @param exc_return EXC_RETURN value present in LR after exception entry.
  */
-void z_do_kernel_oops(const struct arch_esf *esf, _callee_saved_t *callee_regs)
+void z_do_kernel_oops(const struct arch_esf *esf, _callee_saved_t *callee_regs, uint32_t exc_return)
```
Comment (arbrauns) [inline arch/arm/core/fatal.c:106]: In #76221 I [made sure](https://github.com/zephyrproject-rtos/zephyr/pull/76221/files#diff-81474c76b65788e3a74efda285096d1f735f501b8f898fc0892e9a6276e823b6R344-R346) Cortex-A/Cortex-R don't pass garbage here, but I don't know if that's really necessary.

File: arch/arm/include/cortex_m/exception.h [hunk 5]
```diff
@@ -39,6 +39,54 @@ extern volatile irq_offload_routine_t offload_routine;
...
+#define EXC_RETURN_CALLEE_STACK_Msk BIT(EXC_RETURN_CALLEE_STACK_Pos)
+#define EXC_RETURN_CALLEE_STACK_SKIPPED 0
+#define EXC_RETURN_CALLEE_STACK_DEFAULT EXC_RETURN_CALLEE_STACK_Msk
+/* bit[6]: Secure or Non-secure stack. Indicates whether a Secure or
+ * Non-secure stack is used to restore stack frame on exception return.
+ */
+#define EXC_RETURN_RETURN_STACK_Pos 6
+#define EXC_RETURN_RETURN_STACK_Msk BIT(EXC_RETURN_RETURN_STACK_Pos)
+#define EXC_RETURN_RETURN_STACK_Non_Secure 0
+#define EXC_RETURN_RETURN_STACK_Secure EXC_RETURN_RETURN_STACK_Msk
```
Comment (arbrauns) [inline arch/arm/include/cortex_m/exception.h:88]: Since this is only relevant for Cortex-M, maybe it should be put behind an `#if defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE) || defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE)` to avoid accidental misuse in Cortex-A/Cortex-R code.

File: arch/arm/core/fatal.c (hunk 4 above)
Comment (mrkhldn) [reply arch/arm/core/fatal.c:106]: Makes sense to me

File: arch/arm/include/cortex_m/exception.h (hunk 5 above)
Comment (mrkhldn) [reply arch/arm/include/cortex_m/exception.h:88]: The path to this include file is arch/arm/include/cortex_m/exception.h, so hopefully that's enough to make it clear that it's intended for Cortex-M

Comment (arbrauns) [reply arch/arm/include/cortex_m/exception.h:88]: Ah, I missed that, that's fine then.

**Review by ithinuel — DISMISSED** [review]

File: arch/arm/include/cortex_m/exception.h (hunk 5 above)
Comment (vbrzeski) [reply arch/arm/include/cortex_m/exception.h:88]: I think you also need to check xPSR bit 9 to see if the stack is padded an additional 4 bytes.

Comment (mrkhldn) [reply arch/arm/include/cortex_m/exception.h:88]: > I think you also need to check xPSR bit 9 to see if the stack is padded an additional 4 bytes.

Added, thanks

**Review by ithinuel — APPROVED** [review]

**Comment by ithinuel** [comment]
@vbrzeski would you mind checking if this resolved your issue and if so approve this PR please ?

**Comment by vbrzeski** [comment]
Thanks for adding the xPSR check! LGTM after clang-formatting the source code.

**Review by ycsin — APPROVED** [review]

**Comment by aescolar** [comment]
@mrkhldn this commit introduced a regression in main
https://github.com/zephyrproject-rtos/zephyr/actions/runs/11250552333/job/31279885750#step:11:1033

**Comment by aescolar** [comment]
@mrkhldn unfortunately this PR was reverted due to the introduced regression :( .
You are more than welcome to resubmit the PR with a fix so it also builds for M33 cores.

**Comment by mrkhldn** [comment]
Fixed the regression and re-submitted here https://github.com/zephyrproject-rtos/zephyr/pull/79622
