### PR TITLE
Bluetooth: Mesh: Fix out of bounds write

### LINKED ISSUE #78794: Buffer overflow / segfault in tests/bluetooth/mesh/brg/
**Describe the bug**
The test is segfaulting due to a buffer overflow.
`brg_tbl_compact()` is writing pass the array end with `j=CONFIG_BT_MESH_BRG_TABLE_ITEMS_MAX`

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=native_sim ../tests/bluetooth/mesh/brg/ -DCONFIG_ASAN=y
3. ninja
4. zephyr/zephyr.exe
5. See error

You can also build it without ASAN and just see the segfault, or run it with valgrind.

**Expected behavior**
No buffer overflow

**Impact**
Failing test

**Logs and console output**
```
*** Booting Zephyr OS build v3.7.0-3250-g654632ea1cbb ***
Running TESTSUITE bt_mesh_brg_cfg
===================================================================
START - test_basic_functionality_storage
*** buffer overflow detected ***: terminated
Aborted (core dumped)
```
```
*** Booting Zephyr OS build v3.7.0-3250-g654632ea1cbb ***
Running TESTSUITE bt_mesh_brg_cfg
===================================================================
START - test_basic_functionality_storage
=================================================================
==1046312==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0807c420 at pc 0x0804cb5b bp 0xf2bfeff8 sp 0xf2bfefe8
WRITE of size 8 at 0x0807c420 thread T4
    #0 0x804cb5a in memset 
    #1 0x804cb5a in brg_tbl_compact subsys/bluetooth/mesh/brg_cfg.c:46
    #2 0x804d5ef in bt_mesh_brg_cfg_tbl_remove subsys/bluetooth/mesh/brg_cfg.c:352
    #3 0x804b640 in bt_mesh_brg_cfg_test_basic_functionality_storage tests/bluetooth/mesh/brg/src/main.c:176
    #4 0x804b640 in _bt_mesh_brg_cfg_test_basic_functionality_storage_wrapper tests/bluetooth/mesh/brg/src/main.c:132
    #5 0x80545f9 in run_test_functions subsys/testsuite/ztest/src/ztest.c:328
    #6 0x80545f9 in test_cb subsys/testsuite/ztest/src/ztest.c:662
...
0x0807c420 is located 32 bytes before global variable 'logging_thread' defined in 'subsys/logging/log_core.c:960:17' (0x807c440) of size 112
0x0807c420 is located 0 bytes after global variable 'brg_tbl' defined in 'subsys/bluetooth/mesh/brg_cfg.c:24:35' (0x807c3a0) of size 128
```

**Environment (please complete the following information):**

 - OS: Linux, Ubuntu 24.04
 - Toolchain (e.g Zephyr SDK, ...): Host gcc 13
 - Commit SHA or Version used: main as of now

**Additional context**
Test introduced in #78400

### PR DESCRIPTION
**Pull request by Balaklaka**
Fix of the subnet bridging table function to only
compact the table if elements has been removed, and fixing the compact function to compact the table if several elemnts has been removed at the same time.

Fixes zephyrproject-rtos#78794

### CODE REVIEW

File: subsys/bluetooth/mesh/brg_cfg.c [hunk 1]
```diff
@@ -334,22 +344,22 @@ int bt_mesh_brg_cfg_tbl_remove(uint16_t net_idx1, uint16_t net_idx2, uint16_t ad
...
-				store = true;
-			}
+		if (!(brg_tbl[i].net_idx1 == net_idx1 && brg_tbl[i].net_idx2 == net_idx2)) {
+			continue;
+		}
+
+		if ((brg_tbl[i].addr1 == addr1 && brg_tbl[i].addr2 == addr2) ||
+		    (addr2 == BT_MESH_ADDR_UNASSIGNED && brg_tbl[i].addr1 == addr1) ||
+		    (addr1 == BT_MESH_ADDR_UNASSIGNED && brg_tbl[i].addr2 == addr2)) {
+			memset(&brg_tbl[i], 0, sizeof(brg_tbl[i]));
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/brg_cfg.c:354]: Same as above. Set `direction` to 0 instead of using `memset`.

File: subsys/bluetooth/mesh/brg_cfg.c [hunk 2]
```diff
@@ -36,15 +36,19 @@ static ATOMIC_DEFINE(brg_cfg_flags, BRG_CFG_FLAGS_COUNT);
 static void brg_tbl_compact(void)
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/brg_cfg.c:36]: A small optimization could be to pass a starting index to `brg_tbl_compact` since we know the first entry that was changed. Then `brg_tbl_compact` can start moving entries from the first removed one.

File: subsys/bluetooth/mesh/brg_cfg.c [hunk 3]
```diff
@@ -36,15 +36,19 @@ static ATOMIC_DEFINE(brg_cfg_flags, BRG_CFG_FLAGS_COUNT);
...
 {
 	int j = 0;
+	int k = 0;
 
-	for (int k = 0; k < bt_mesh_brg_cfg_row_cnt; k++) {
+	for (; k < bt_mesh_brg_cfg_row_cnt; k++) {
 		if (brg_tbl[k].direction != 0) {
 			brg_tbl[j] = brg_tbl[k];
 			j++;
 		}
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/brg_cfg.c:45]: Could be good to add `j != k` to avoid extra copy. Though this won't be needed if starting index is passed to `brg_tbl_compact`.
```suggestion
		if (brg_tbl[k].direction != 0) {
			if (j != k) {
				brg_tbl[j] = brg_tbl[k];
			}
			j++;
		}
```

**Review by PavelVPV — CHANGES_REQUESTED** [review]
Please add a unit test that covers a case where more than 1 entry is removed from the table by a single operation, in particularly:
- every second entry is removed
- full table, all entries except the first one are removed
- full table, all entries except the last one are removed
- full table, all entries are removed at once

File: subsys/bluetooth/mesh/brg_cfg.c (hunk 2 above)
Comment (omkar3141) [reply subsys/bluetooth/mesh/brg_cfg.c:36]: Considering bridging table entry is 8 byte long which is probably 8-10 cycles in memset, Performance gain here could be masked by a need to have extra code for extra variable in `brg_tbl_netkey_removed_evt()` and other removal functions to track the first removed entry, then pass it to this function. So, I think it is worth leaving this change as is.

Comment (PavelVPV) [reply subsys/bluetooth/mesh/brg_cfg.c:36]: https://godbolt.org/z/hjePerWYj

```
  ldr r3, [r7, #4]
  lsls r3, r3, #3
  ldr r2, .L8+4
  add r3, r3, r2
  movs r2, #8
  movs r1, #0
  mov r0, r3
  bl memset
```

According to my info it is up to 31 cycles. So, assigning a value to `direction` is definitely much less cycles. as well as storing first index (need one variable for this) and passing it to a function.

Comment (PavelVPV) [reply subsys/bluetooth/mesh/brg_cfg.c:36]: Skipping first entries allows bypassing this code where we know for sure that it is redundant: https://github.com/zephyrproject-rtos/zephyr/blob/fb6ac019fa9404f2c7862e2cfbe2103040b0e507/subsys/bluetooth/mesh/brg_cfg.c#L42-L45. It as you may see copies the same entry to itself including increment of `j`. To avoid this you need a single variable which you assign to a first index in `brg_tbl_netkey_removed_evt` and in `bt_mesh_brg_cfg_tbl_remove`.

If you for example remove the last, the 10th, entry of the table, this code will copy 9 entries to themselves including incrementing `j`, which is 36-40 cycles just for one entry, or 324-360 cycles for this example.

Comment (Balaklaka) [reply subsys/bluetooth/mesh/brg_cfg.c]: This is not a function that used a lot. Adding and removing entries will be done once in a while so adding this will to gain much in speed.

Comment (PavelVPV) [reply subsys/bluetooth/mesh/brg_cfg.c]: I gave rational reason why it should be done. Coping an object to itself is bad code and should be avoided. I gave examples when it matters. The overhead of storing single variable and passing it to a function is significantly less than overhead the current code creates.

Comment (Balaklaka) [reply subsys/bluetooth/mesh/brg_cfg.c]: Added the first entry, as it was not much extra code.

**Review by PavelVPV — APPROVED** [review]

**Comment by PavelVPV** [comment]
Bsim fix is merged now. You can rebase your branch to pass bsim tests.

**Review by alxelax — APPROVED** [review]
