### PR TITLE
drivers: usb: usb_dc_kinetis: reconfigure USB endpoint 0 after reset

### LINKED ISSUE #58407: USB DFU sample does not function on FRDM-K64F
**Describe the bug**
In the default configuration, `samples/subsys/dfu/usb` does not function on the FRDM-K64F board, nor any EVK I have tested that uses the Kinetis USB driver.

The USB dfu sample fails with the following message:
```
Opening DFU capable USB device...
ID 2fe3:0005
Run-time device DFU version 0110
Claiming USB DFU Runtime Interface...
Determining device status: state = appIDLE, status = 0
Device really in Runtime Mode, send DFU detach request...
Device will detach and reattach...
dfu-util: Lost device after RESET?
```

It is worth noting that setting `CONFIG_USB_DFU_WILL_DETACH=n` will allow the sample to function on a Linux based machine, but based on the content of c27d48c89ae67397139ee5b1a245505ed10b071f I believe that USB DFU mode would still fail with WinUSB. Furthermore, the default configuration for `samples/subsys/usb/dfu` enables this KConfig, so a user must debug the sample to determine why it is not functioning correctly on the K64F.

Please also mention any information which could help others to understand
the problem you're facing:
 - Target platform: `frdm-k64f`
 - DFU Utili `0.9` compiled from source at https://dfu-util.sourceforge.net/releases/ was used to reproduce the issue.
 - Issue has been bisected to c27d48c89ae67397139ee5b1a245505ed10b071f. Although the Kinetis USB driver implements `usb_dc_detach`, it seems that the implementation may not function correctly.

**To Reproduce**
1. `west build -p always -b frdm_k64f -d build_bl bootloader/mcuboot/boot/zephyr`
2. `west flash`
3. `west build -p always -b frdm_k64f samples/subsys/usb/dfu -DCONFIG_BOOTLOADER_MCUBOOT=y -DCONFIG_MCUBOOT_SIGNATURE_KEY_FILE=\"bootloader/mcuboot/root-rsa-2048.pem\"`
4. `west flash`
5. `sudo dfu-util -S "SERIAL_NUM" -U firmware.bin -a 0`

**Expected behavior**
`dfu-util` should correctly upload the firmware image that is currently stored on the device flash.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.15.0

### PR DESCRIPTION
**Pull request by danieldegrasse**
Per Kinetis USB reference manual, when USB reset interrupt is asserted, the driver should configure and enable the default USB control endpoint 0. Generally, when the reset interrupt is asserted, endpoint 0 is already configured so the driver only needs to reenable it.

However, when usb_dc_detach is called and the module is reset, all endpoint configuration will be reset. Thus, we need to manually configure USB endpoint 0 when a USB reset interrupt is received, or the USB driver will not function correctly after usb_dc_detach has been called.

Fixes #58407

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@jfischer-no Would appreciate any feedback you have on this fix- the specific behavior I see is that when the USB module is initialized and control endpoint 0 is configured, `USB0->ENDPOINT[0x0].ENDPT` is set to `0xd` (as expected, since this is a bidirectional control endpoint)

However, after `usb_dc_detach` is called, `USB0->ENDPOINT[0x0].ENDPT` is reset to `0x0`, likely due to the USB module being reset. Since the USB stack does not reconfigure endpoint 0 after a `USB_DC_RESET` event, I reconfigure the control endpoint in the `reenable_all_endpoints` function. This is similar to how the MCUX USB driver `usb_dc_mcux.c` handles a bus reset event.

**Review by jfischer-no — DISMISSED** [review]

File: drivers/usb/device/usb_dc_kinetis.c [hunk 1]
```diff
@@ -851,6 +850,15 @@ int usb_dc_ep_mps(const uint8_t ep)
...
 {
+	struct usb_dc_ep_cfg_data ep_cfg;
+
+	/* Reconfigure control endpoint 0 after a reset */
+	ep_cfg.ep_addr = USB_CONTROL_EP_OUT;
+	ep_cfg.ep_mps = USB_CONTROL_EP_MPS;
+	ep_cfg.ep_type = USB_DC_EP_CONTROL;
+	usb_dc_ep_configure(&ep_cfg);
+	ep_cfg.ep_addr = USB_CONTROL_EP_IN;
+	usb_dc_ep_configure(&ep_cfg);
```
Comment (jfischer-no) [inline drivers/usb/device/usb_dc_kinetis.c:861]: I do not remember the reason for the loop below, but you are right, all endpoints are reset, so actually it should be enough to call usb_dc_ep_configure() + usb_dc_enable() for USB_CONTROL_EP_OUT and USB_CONTROL_EP_IN. And rename reenable_all_endpoints(void) to reenable_control_endpoint(void).

**Review by tmon-nordic — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]
