### PR TITLE
drivers: video: fix null deref in video_get_csi_link_freq()

### LINKED ISSUE #91244: [Coverity CID: 525179] Explicit null dereferenced in drivers/video/video_common.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/fd6b05c81b86a1ffe465d56ded7b73a9fdb7f14b/drivers/video/video_common.c

Category: Null pointer dereferences
Function: `video_get_csi_link_freq`
Component: Drivers
CID: [525179](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=525179)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/fd6b05c81b86a1ffe465d56ded7b73a9fdb7f14b/drivers/video/video_common.c#L420

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=525179

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_FORWARD_NULL). ([CWE-476](http://cwe.mitre.org/data/definitions/476.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by sudarsan-22**
Add null and bounds checks before accessing int_menu[ctrl.val].

CID: 525179
Fixes: #91244

### CODE REVIEW

**Comment by sudarsan-22** [comment]
Hi everyone the CI error confirms that the CONFIG_LV_FONT_SOURCE_HAN_SANS_SC_16_CJK symbol is being referenced in tests/lib/gui/lvgl/prj.conf but is undefined, and the CI Kconfig check is treating it as an error.

To fix:
    Make sure the module or Kconfig file defining it is included and sourced.
    Or, remove the line from prj.conf if it's not applicable for that test.

File: drivers/video/video_common.c [hunk 1]
```diff
@@ -417,6 +417,10 @@ int64_t video_get_csi_link_freq(const struct device *dev, uint8_t bpp, uint8_t l
 		return -ERANGE;
 	}
 
+	if (!ctrl_query.int_menu || ctrl.val >= ctrl_query.max) {
```
Comment (ngphibang) [inline drivers/video/video_common.c]: `ctrl_query.max` does not exist. You mean `ctrl_query.range.max` ? BTW, this is already checked the line before

`if (ctrl_query.int_menu != NULL)` is sufficient I think

**Review by josuah — DISMISSED** [review]
The fix makes sense to me.
Much thank you for the help!

File: drivers/video/video_common.c [hunk 2]
```diff
@@ -417,6 +417,10 @@ int64_t video_get_csi_link_freq(const struct device *dev, uint8_t bpp, uint8_t l
 		return -ERANGE;
 	}
 
+	if (!ctrl_query.int_menu) {
```
Comment (avolmat-st) [inline drivers/video/video_common.c]: LGTM, but better prefer ctrl_query.int_menu == NULL as we now try to apply MISRA rules.

**Review by avolmat-st — CHANGES_REQUESTED** [review]

**Review by avolmat-st — APPROVED** [review]

**Review by josuah — APPROVED** [review]

**Review by ngphibang — APPROVED** [review]
