### PR TITLE
drivers: pwm: ledc: esp32c2: esp32c6: Fix clock frequency

### LINKED ISSUE #80879: pwm: ledc: esp32c6: Sample won't build
**Describe the bug**

After #80404 PWM sample won't build for esp32c6.

**To Reproduce**

```
west build -b esp32c6_devkitc tests/drivers/pwm/pwm_api/ -p
```

**Expected behavior**

Sample builds.

**Impact**

Unable to use LEDC PWM driver on the device.

**Logs and console output**

```
drivers/pwm/CMakeFiles/drivers__pwm.dir/pwm_led_esp32.c.obj -c /D/Embedded/zephyrproject/zephyr/drivers/pwm/pwm_led_esp32.c
/D/Embedded/zephyrproject/zephyr/drivers/pwm/pwm_led_esp32.c: In function 'pwm_led_esp32_calculate_max_resolution':
/D/Embedded/zephyrproject/zephyr/drivers/pwm/pwm_led_esp32.c:129:31: error: 'SCLK_CLK_FREQ' undeclared (first use in this function); did you mean 'CPU_CLK_FREQ'?
  129 |         uint64_t clock_freq = SCLK_CLK_FREQ;
  ```

### PR DESCRIPTION
**Pull request by raffarost**
After PR #80404 PWM LEDC won't build for ESP32C6, so fix is necessary.
Fix clock frequency for both devices.

Fixes #80879

### CODE REVIEW

**Review by wmrsouza — DISMISSED** [review]

File: drivers/pwm/pwm_led_esp32.c [hunk 1]
```diff
@@ -22,6 +22,17 @@
 #include <zephyr/logging/log.h>
 LOG_MODULE_REGISTER(pwm_ledc_esp32, CONFIG_PWM_LOG_LEVEL);
 
+#if SOC_LEDC_SUPPORT_APB_CLOCK
+#define CLOCK_SOURCE LEDC_APB_CLK
+#elif SOC_LEDC_SUPPORT_PLL_DIV_CLOCK
+#define CLOCK_SOURCE LEDC_SCLK
+#if defined(CONFIG_SOC_SERIES_ESP32C2)
```
Comment (sylvioalves) [inline drivers/pwm/pwm_led_esp32.c:29]: Would you add a blank line in here to split both definitions?

**Review by uLipe — APPROVED** [review]

**Review by sylvioalves — APPROVED** [review]

**Review by wmrsouza — APPROVED** [review]
