### PR TITLE
lib: updatehub: Fix out-of-bounds access and add flash_img_init return value check

### LINKED ISSUE #26992: [Coverity CID :210547] Unchecked return value in lib/updatehub/updatehub.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/476fc405e7/lib/updatehub/updatehub.c

Category: Error handling issues
Function: `install_update`
Component: Other
CID: [210547](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210547)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #26993: [Coverity CID :210593] Out-of-bounds access in lib/updatehub/updatehub.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/476fc405e7/lib/updatehub/updatehub.c

Category: Memory - corruptions
Function: `cleanup_connection`
Component: Other
CID: [210593](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210593)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by nandojve**
The flash_img_int return value is not checked for fail conditions. This can result on useless download attempts once image will not be properly recorded. Add return value check and on error execute default treatment.
Fixes #26992.

The struct pollfd context variable is not proper initialized and index is out-of-bounds. Adjusts index to be inside scope boundary.
Fixes #26993.

CC: @otavio

### CODE REVIEW

**Review by otavio — APPROVED** [review]

File: lib/updatehub/updatehub.c [hunk 1]
```diff
@@ -220,7 +220,7 @@ static void cleanup_connection(void)
 		LOG_ERR("Could not close the socket");
 	}
 
-	memset(&ctx.fds[1], 0, sizeof(ctx.fds[1]));
+	memset(&ctx.fds[0], 0, sizeof(ctx.fds[0]));
```
Comment (ceolin) [inline lib/updatehub/updatehub.c:223]: The case that you are fixing is not completely clear for me because this function is called from different contexts, but wouldn't be better (and more generic) if you iterate over the file descriptors and clean then ? e.g:

```
for (i = 0; i < ctx.nfds; i++) {
    memset(&ctx.fds[i], 0, sizeof(ctx.fds[i]));
}
```

Comment (nandojve) [reply lib/updatehub/updatehub.c]: Sure.

**Review by ceolin — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
