### PR TITLE
Fix rand32_ctr_drbg error handling

### LINKED ISSUE #29869: Missing error check of function entropy_get_entropy()
Hi,
As described in the project API documentation, function entropy_get_entropy() fills a buffer with entropy, returns 0 on success, and returns -ERRNO on error. However, as shown in the following code, a missing error check take places.
https://github.com/zephyrproject-rtos/zephyr/blob/577d588b3a108c34430b8fbaec9bb4f2a690b7fb/subsys/random/rand32_ctr_drbg.c#L133-L135

Furthermore, the return values of function entropy_get_entropy() from other call sites are all checked. See the following code which is from the same file, for example.
https://github.com/zephyrproject-rtos/zephyr/blob/577d588b3a108c34430b8fbaec9bb4f2a690b7fb/subsys/random/rand32_ctr_drbg.c#L85-L90

### PR DESCRIPTION
**Pull request by ceolin**
Address two issues in the error path of rand32_ctr_drbg:

- Release previously locked IRQ
- Check entropy_get_entropy error

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

File: subsys/random/rand32_ctr_drbg.c [hunk 1]
```diff
@@ -150,8 +151,8 @@ int z_impl_sys_csrand_get(void *dst, uint32_t outlen)
 	} else {
 		ret = -EIO;
 	}
-end:
 #endif
+end:
```
Comment (d3zd3z) [inline subsys/random/rand32_ctr_drbg.c:155]: Have you checked if this gives a warning about an unused label in the case where the label is present but the goto is not?

**Review by d3zd3z — APPROVED** [review]
