### PR TITLE
Bluetooth: Fix scan failed to start due to RPA timeout

### LINKED ISSUE #9463: bt_le_scan_start Fails with Error -5 after 128 scan start/stop cycles
I have a basic project that scans for 5 seconds, then stops for one second - then repeats forever.
After exactly 128 cycles, the 129th scan start (and all after that) fails with error code -5 (I think this is POSIX:       #define EIO 5		/* I/O error */).

Given the number of time it works (128) it seems like a resource or memory may have run out?

Here is the debug log (attached) showing the problem:   Any ideas what might be wrong & how to fix it? 

Thanks...

[Zephyr_Scan_Start_Stop_Error.txt](https://github.com/zephyrproject-rtos/zephyr/files/2292440/Zephyr_Scan_Start_Stop_Error.txt)

P.S.  Also at the end of this file is a fragment of debug I saw a couple of times earlier today during testing - showing a kernel error that occurred. It may be related or unrelated to the other problem??

Regards,
Declan

### PR DESCRIPTION
**Pull request by cvinayak**
Updating the Resolvable Private Address when advertising and
active scanning in progress fails and clears the RPA_VALID
flag; making the next bt_le_scan_start while continueing to
advertise to fail.

This is fixed by keeping the RPA_VALID flag remain set.
Stopping and starting active scanning to update RPA can be
implemented in a separate commit.

Fixes #9463.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@jhedberg  @carlescufi This PR is to get discussion around the issue, my changes may not be the best fix, feel free to suggest a better implementation.

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -403,13 +407,17 @@ static void rpa_timeout(struct k_work *work)
 	if (atomic_test_bit(bt_dev.flags, BT_DEV_ADVERTISING)) {
 		/* make sure new address is used */
 		set_advertise_enable(false);
-		le_set_private_addr(bt_dev.adv_id);
+		err |= le_set_private_addr(bt_dev.adv_id);
```
Comment (carlescufi) [inline subsys/bluetooth/host/hci_core.c]: why `|=` ? `err` is not changed before this line

Comment (cvinayak) [reply subsys/bluetooth/host/hci_core.c]: Just a habit, in case someone changes the order of the if statements. That said, the whole function could get a overhaul?

File: subsys/bluetooth/host/hci_core.c [hunk 2]
```diff
@@ -391,9 +391,13 @@ static int le_set_private_addr(u8_t id)
 
 static void rpa_timeout(struct k_work *work)
 {
+	int err = 0;
+	bool valid;
+
 	BT_DBG("");
 
 	/* Invalidate RPA */
+	valid = atomic_test_bit(bt_dev.flags, BT_DEV_RPA_VALID);
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: valid  = atomic_test_and_clear_bit(...);

File: subsys/bluetooth/host/hci_core.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c]: Yeah, this may need some rethinkin

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/hci_core.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c]: Also, this kind of `|=` stuff doesn't really work if you want to retain the specific error number. Normally if some function returns an error you'd jump to some `failed:` label without trying to call any more functions that may fail.

**Comment by carlescufi** [comment]
@jhedberg @joerchan can one of you take over this PR?

File: subsys/bluetooth/host/hci_core.c [hunk 3]
```diff
@@ -450,13 +453,24 @@ static void rpa_timeout(struct k_work *work)
...
+	}
+
+	/* If both advertising and scanning is active, le_set_private_addr
+	 * will fail. In this case, set back RPA_VALID so that if either of
+	 * advertising or scanning was restarted by application then
+	 * le_set_private_addr in the public API call path will not retry
+	 * set_random_address. This is needed so as to be able stop and restart
+	 * either role by applicaion after rpa_timeout.
+	 */
+	if (rpa_valid && (err_adv || err_scan)) {
```
Comment (carlescufi) [inline subsys/bluetooth/host/hci_core.c]: Do you need the `rpa_valid` condition here? If this function was invoked with `BT_DEV_RPA_VALID` set to 0, then both adv and scan will still try to set the private address, so why not set it in that case?

File: subsys/bluetooth/host/hci_core.c [hunk 4]
```diff
@@ -450,13 +453,24 @@ static void rpa_timeout(struct k_work *work)
...
-		le_set_private_addr(BT_ID_DEFAULT);
+		err_scan = le_set_private_addr(BT_ID_DEFAULT);
+	}
+
+	/* If both advertising and scanning is active, le_set_private_addr
+	 * will fail. In this case, set back RPA_VALID so that if either of
+	 * advertising or scanning was restarted by application then
+	 * le_set_private_addr in the public API call path will not retry
+	 * set_random_address. This is needed so as to be able stop and restart
+	 * either role by applicaion after rpa_timeout.
```
Comment (carlescufi) [inline subsys/bluetooth/host/hci_core.c]: typo: application

File: subsys/bluetooth/host/hci_core.c (hunk 3 above)
Comment (carlescufi) [reply subsys/bluetooth/host/hci_core.c]: My point there is that I don't think there is a case where you actually care about whether `BT_DEV_RPA_VALID` was 0 or 1. If the RPA timeout fires and there's roles running, you need to update the RPA, and if that fails because there's another role running then you need to set `BT_DEV_RPA_VALID` to 1. This would save an auto variable and a comparison

Comment (carlescufi) [reply subsys/bluetooth/host/hci_core.c]: @jhedberg do you agree with the above?

Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c]: @carlescufi yes, I do

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by joerchan — APPROVED** [review]
