### PR TITLE
boards: nxp: mimxrt595_evk: leave INPUTMUX and DMA clocks enabled

### LINKED ISSUE #86118: regression: tests/drivers/dma/chain_link_transfer fails on mimxrt595_evk
This DMA test fails on the board `mimxrt595_evk_cm33`.  This is a regression issue caused by [a9097c9c58e868bf3b0975bdf093036a0be80eac](https://github.com/zephyrproject-rtos/zephyr/pull/83459).  Calling `INPUTMUX_Deinit()` disables clocks needed for the DMA and INPUTMUX.

### PR DESCRIPTION
**Pull request by DerekSnell**
Calling INPUTMUX_Deinit() disables clocks to DMA and INPUTMUX, and causes issues with DMA.

Fixes #86118

### CODE REVIEW

**Review by dleach02 — APPROVED** [review]

File: boards/nxp/mimxrt595_evk/board.c [hunk 1]
```diff
@@ -352,7 +352,6 @@ static int mimxrt595_evk_init(void)
 	INPUTMUX_EnableSignal(INPUTMUX,
 			kINPUTMUX_I3c1TxToDmac1Ch31RequestEna, true);
 #endif /* dma1 */
-	INPUTMUX_Deinit(INPUTMUX);
```
Comment (hakehuang) [inline boards/nxp/mimxrt595_evk/board.c:355]: but remove this will cause more power consumption.

**Review by hakehuang — APPROVED** [review]
