### PR TITLE
net: lwm2m: Rework bootstrap DELETE operation

### LINKED ISSUE #29964: net: lwm2m: Correctly Support Bootstrap-Delete Operation
# Summary  
- `DELETE /` is implemented as `DELETE /0` 
- `DELETE /`and `DELETE /x` for x != 0 is not supported/implemented

# Background
Zephyr client should support bootstrap-delete according to the [specification](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-7-6-0-6176-Bootstrap-Delete-Operation).
Currently the support is only implementing partially and that part not according to the specification: 

- If the client is in bootstrap mode and bootstrap server sends a DELETE request without `Uri-Path` option, then bootstrap_delete will be executed ([wm2m_engine.c:3344](https://github.com/zephyrproject-rtos/zephyr/blob/7127f0a7420869876e425f514dedf6c1645269a5/subsys/net/lib/lwm2m/lwm2m_engine.c#L3344))
- `bootstrap_delete` deletes SECURITY instances > 0

Given `bootstrap_delete` is called when no uri option is set, the assumed contract of that method is that it should correspond to DELETE /  where `all Instances of all Objects in the LwM2M Client MUST be removed (except for the two cases mentioned above)` where `The two exceptions are the LwM2M Bootstrap-Server Account, potentially including an associated Instance of an OSCORE Object ID:21, and the single Instance of the mandatory Device Object (ID:3), which are not affected by any Delete operation.`

# Proposal
1. Fix: Adjust current code to delete all other object instances as well
2. Enhancement: Support both no `Uri-Path` header and empty `Uri-Path` header, and treat them the same way 
3. Enhancement: Support deletion of all instance of a particular object

## Side Note
Sending a `DELETE /x` request to the client in bootstrap mode is executed as `DELETE /x/0` (goes through regular delete request handler that does not check if uri path has length >=2 as it is not allowed by the spec outside of bootstrap, object and instance id must be set)

### PR DESCRIPTION
**Pull request by rlubos**
Rework the bootstrap DELETE operation, to support deletion of multiple
resources.

Current implementation had several oversimplifications, making it not
spec-compliant:
* DELETE `/` removed only Security object instances (!= 0)
* DELETE `/x` was handled as DELETE `/x/0`, therefore not removing all
  of the object instances.

Since the above is only supported during bootstrap and not regular
Device management, this functionality was implemented in the
`bootstrap_delete` function, which now will be called for all DELETE
operations initiated during bootstrap. The regular LwM2M DELETE handler
will only be called during regular Device management, as it has more
strict limitations on what can be deleted.

Additionally, handle empty URI Path option as `/`, therefore indicating
deletion of all resources.

Fixes #29964

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 1]
```diff
@@ -3282,21 +3290,75 @@ static int do_write_op(struct lwm2m_message *msg,
...
+
+	if (msg->path.level == 2) {
+		if (!bootstrap_delete_allowed(msg->path.obj_id,
+					      msg->path.obj_inst_id)) {
+			return -EPERM;
+		}
+
+		return lwm2m_delete_obj_inst(msg->path.obj_id,
+					     msg->path.obj_inst_id);
+
```
Comment (jukkar) [inline subsys/net/lib/lwm2m/lwm2m_engine.c:3337]: extra empty line can be removed

**Review by jukkar — APPROVED** [review]
LGTM, one small nit

**Review by nashif — APPROVED** [review]
