### PR TITLE
USB: drivers: usb_dc_stm32: Fix coverity issue

### LINKED ISSUE #16573: [Coverity CID :198874]Null pointer dereferences in /drivers/usb/device/usb_dc_stm32.c
Static code scan issues seen in File: /drivers/usb/device/usb_dc_stm32.c
 Category: Null pointer dereferences
 Function: HAL_PCD_DataInStageCallback
 Component: Drivers
 CID: 198874
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #16582: [Coverity CID :198865]Null pointer dereferences in /drivers/usb/device/usb_dc_stm32.c
Static code scan issues seen in File: /drivers/usb/device/usb_dc_stm32.c
 Category: Null pointer dereferences
 Function: HAL_PCD_SetupStageCallback
 Component: Drivers
 CID: 198865
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by finikorg**
Add __ASSERT() for coverity issue CID: 198874. Assert is used instead
of check since this is callback we get from stm32cube.

Fixes #16573
Fixes #16582

### CODE REVIEW

**Review by loicpoulain — APPROVED** [review]

**Review by jfischer-no — DISMISSED** [review]

File: drivers/usb/device/usb_dc_stm32.c [hunk 1]
```diff
@@ -963,6 +963,8 @@ void HAL_PCD_SetupStageCallback(PCD_HandleTypeDef *hpcd)
 	LOG_DBG("");
 
 	ep_state = usb_dc_stm32_get_ep_state(EP0_OUT); /* can't fail for ep0 */
+	__ASSERT(ep_state, "No corresponding ep_state for EP0");
```
Comment (nashif) [inline drivers/usb/device/usb_dc_stm32.c]: how does this fix the problem? if asserts are disabled we are back to square 1. Maybe I am missing something.

Comment (jfischer-phytec-iot) [reply drivers/usb/device/usb_dc_stm32.c]: indeed it is disabled by default, then why many drivers use it in the same way?

Comment (finikorg) [reply drivers/usb/device/usb_dc_stm32.c]: > how does this fix the problem? if asserts are disabled we are back to square 1. Maybe I am missing something.

Yes, I think this is bug with assert in Zephyr, in this situation we probably need some way to print error and panic and I do not know other way of doing this. 
PS: I actually think it "fixes" Coverity.

Comment (carlescufi) [reply drivers/usb/device/usb_dc_stm32.c]: `k_panic()` or `k_oops()` are an alternative

Comment (carlescufi) [reply drivers/usb/device/usb_dc_stm32.c]: @nashif this is a consistent pattern in  Zephyr. Instead of checking a return value, we rely on asserts and expect the user to run the code with asserts enabled in order to check for those cases.

**Review by carlescufi — APPROVED** [review]
