### PR TITLE
LE Audio: Broadcast source reconfig fix

### LINKED ISSUE #63285: LE Audio: bt_bap_broadcast_source_reconfig does not work for subset of streams
**Describe the bug**
The current implementation of bt_bap_broadcast_source_reconfig allows to only configure a subset of the streams in the broadcast source. However, since values like the SDU and RTN are part of the streams, and thus the parameters, then the function may only apply the QoS values from `struct bt_audio_codec_qos` to a subset of the streams.

For example if the source was created with 2 streams with e.g. SDU = 40, then the `bt_bap_broadcast_source_reconfig` would allow the application to update just one stream to use SDU = 30, which is not a valid thing to do in ISO. 

**To Reproduce**
N/A

**Expected behavior**
The function should not allow to set invalid values, like different SDU values for each stream. 
Either the function will need to require all streams in the BIG to be reconfigured, or it should update the other streams (that are not part of the reconfigure parameters) with the common values (such as the SDU, RTN, etc.). Effectively the param->qos should be applied to all streams in the BIG. 

**Impact**
If used in a specific way, it will break the broadcast source. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 1f3605de21ef1ace85ba4aeced725411c1ed8ef4

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/63285

### CODE REVIEW

File: tests/bluetooth/audio/bap_broadcast_source/src/main.c [hunk 1]
```diff
@@ -506,32 +514,100 @@ ZTEST_F(bap_broadcast_source_test_suite, test_broadcast_source_start_inval_doubl
...
 	struct bt_bap_broadcast_source_param *reconf_param = fixture->param;
-	struct bt_bap_stream *stream = reconf_param->params[0].params[0].stream;
+	const size_t subgroup_cnt = reconf_param->params_count;
 	int err;
 
 	printk("Creating broadcast source with %zu subgroups with %zu streams\n",
 	       reconf_param->params_count, fixture->stream_cnt);
 
 	err = bt_bap_broadcast_source_create(reconf_param, &fixture->source);
+	zassert_equal(0, err, "Unable to create broadcast source: err %d", err);
```
Comment (fredrikdanebjer) [inline tests/bluetooth/audio/bap_broadcast_source/src/main.c:527]: I'm just wondering if we aren't making test case `test_broadcast_source_create_delete` redundant here. Same goes in the next test case also.

I'm just wondering, if "create" fails, is it better that we are not testing (zassert) that functionality in other functions also, so to get a cleaner error log?

**Review by fredrikdanebjer — COMMENTED** [review]
Overall LGTM, I have one comment above

File: tests/bluetooth/audio/bap_broadcast_source/src/main.c (hunk 1 above)
Comment (fredrikdanebjer) [reply tests/bluetooth/audio/bap_broadcast_source/src/main.c:528]: I really dont think `test_broadcast_source_create_delete` should be removed, its a very clear test case imo. I was more leaning to whether we actually need to perform the assert after performing create in the other test cases. But as I think of it, if we dont, those will output irrelevant errors if it was "create" that failed. So I think it should stay as is also.

**Review by fredrikdanebjer — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
