### PR TITLE
driver: wdt: npcx: add WDT_OPT_PAUSE_HALTED_BY_DBG support.

### LINKED ISSUE #59596: npcx9m6f_evb: drivers/watchdog/wdt_basic_api/ failing
**Describe the bug**
Tests from drivers/watchdog/wdt_basic_api/ failing. There is no console output and timeout as a result.

**To Reproduce**
1. cd <path/to>zephyrproject/zephyr
2. source zephyr-env.sh
3. twister --device-testing --hardware-map <path/to>/map.yaml -T tests/drivers/watchdog/wdt_basic_api/ -vv

**Expected behavior**
The tests pass

**Impact**
annoyance

**Logs and console output**
-- runners.openocd: Flashing file: /home/ztest/zephyrproject/zephyr/twister-out/npcx9m6f_evb/tests/drivers/watchdog/wdt_basic_api/drivers.watchdog/zephyr/zephyr.npcx.hex

DEBUG   - Timed out while monitoring serial output on npcx9m6f_evb
DEBUG   - Expected suite names:['wdt_basic_test_suite']
DEBUG   - Detected suite names:['wdt_basic_test_suite']
DEBUG   - run status: npcx9m6f_evb/tests/drivers/watchdog/wdt_basic_api/drivers.watchdog failed
INFO    - 10/10 npcx9m6f_evb              tests/drivers/watchdog/wdt_basic_api/drivers.watchdog  FAILED Timeout (device 61.920s)

**Environment (please complete the following information):**
- OS: Linux
- Toolchain Zephyr SDK 16.0
- Commit: tested on the newest and older, always the same issue

### PR DESCRIPTION
**Pull request by MulinChao**
This CL adds WDT_OPT_PAUSE_HALTED_BY_DBG support to fix an issue running `tests/drivers/watchdog/wdt_basic_api/` test suite.

Fixes #59596
Attached the log after applying this PR.
```
Running TESTSUITE wdt_basic_test_suite
=======================================▒Running TESTSUITE wdt_basic_test_suite
===================================================================
START - test_wdt
Testcase: test_wdt_no_callback
Waiting to restart MCU
Running TESTSUITE wdt_basic_test_suite
===================================================================
START - test_wdt
Testcase: test_wdt_no_callback
Testcase passed
Testcase: test_wdt_callback_1
Waiting to restart MCU
Running TESTSUITE wdt_basic_test_suite
===================================================================
START - test_wdt
Testcase: test_wdt_callback_1
Testcase passed
Testcase: test_wdt_bad_window_max
 PASS - test_wdt in 0.008 seconds
===================================================================
TESTSUITE wdt_basic_test_suite succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [wdt_basic_test_suite]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.008 seconds
 - PASS - [wdt_basic_test_suite.test_wdt] duration = 0.008 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL
```

### CODE REVIEW

File: soc/arm/nuvoton_npcx/common/scfg.c [hunk 1]
```diff
@@ -129,6 +131,17 @@ void npcx_host_interface_sel(enum npcx_hif_type hif_type)
 	SET_FIELD(inst_scfg->DEVCNT, NPCX_DEVCNT_HIF_TYP_SEL_FIELD, hif_type);
 }
 
+void npcx_dbg_freeze_enable(bool enable)
+{
+	const uintptr_t dbg_base = npcx_scfg_cfg.base_dbg;
+
+	if (enable) {
+		NPCX_DBGFRZEN3(dbg_base) &= ~BIT(7);
```
Comment (fabiobaltieri) [inline soc/arm/nuvoton_npcx/common/scfg.c:139]: Could you add a `#define` for `7`? Looks like other bit fields have them.

File: drivers/watchdog/wdt_npcx.c [hunk 2]
```diff
@@ -227,9 +228,11 @@ static int wdt_npcx_setup(const struct device *dev, uint8_t options)
 		return -ENOTSUP;
 	}
 
+	/* Stall the WDT counter when halted by debugger */
 	if ((options & WDT_OPT_PAUSE_HALTED_BY_DBG) != 0) {
-		LOG_ERR("WDT_OPT_PAUSE_HALTED_BY_DBG is not supported");
-		return -ENOTSUP;
+		npcx_dbg_freeze_enable(1);
+	} else {
+		npcx_dbg_freeze_enable(0);
```
[the remark this answers is not in the document]
Comment (MulinChao) [reply drivers/watchdog/wdt_npcx.c]: Done.

File: soc/arm/nuvoton_npcx/common/scfg.c (hunk 1 above)
Comment (MulinChao) [reply soc/arm/nuvoton_npcx/common/scfg.c]: Done.

**Review by fabiobaltieri — APPROVED** [review]

**Review by keith-zephyr — APPROVED** [review]
