### PR TITLE
drivers: ioapic: fix the cast for the offset

### LINKED ISSUE #49803: I/O APIC Driver in Zephyr makes incorrect register access.
**Describe the bug**
The ioapic driver in the zephyr OS makes an incorrect access to the register offset of IOAPIC during the init process.
[https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/interrupt_controller/intc_ioapic.c](url)
line number : 466
The typecast to char causes the assembly language instruction movsbl to have a signed extension of the ebx register starting with register offset 0x80.

The dissassembly of the __IoApicSet routine:
`<html>
<body>

0000000000101d07 <__IoApicSet>:
--
101d07:    55                       push   %rbp
101d08:    48 89 e5                 mov    %rsp,%rbp
101d0b:    41 54                    push   %r12
101d0d:    41 89 f4                 mov    %esi,%r12d
101d10:    53                       push   %rbx
101d11:    89 fb                    mov    %edi,%ebx
101d13:    e8 8a 1f 00 00           callq  103ca2 <z_smp_global_lock>
101d18:    89 c7                    mov    %eax,%edi
101d1a:    48 8b 05 ef fc 48 00     mov    0x48fcef(%rip),%rax        # 591a10 <z_mmio_ram__ioapic_regs>
101d21:    0f be db                 movsbl %bl,%ebx
101d24:    89 18                    mov    %ebx,(%rax)
101d26:    44 89 60 10              mov    %r12d,0x10(%rax)
101d2a:    5b                       pop    %rbx
101d2b:    41 5c                    pop    %r12
101d2d:    5d                       pop    %rbp
101d2e:    e9 a4 1f 00 00           jmpq   103cd7 <z_smp_global_unlock>

</body>
</html>`

**Expected behavior**
No crash.

**Impact**
I/O APIC initialisation for register access after 0x80 is not executed correctly.

**Platform**
Intel x86 Elkhart Lake (ehl_crb)

**Bug Fix**
Removing the type cast to char in the __IoApicSet function helps to fix the bug. 
ioapic_zephyr_fix

### PR DESCRIPTION
**Pull request by enjiamai**
The cast for the offset variable will make incorrect register
 access when it is over 0x80. Change the char cast to unsigned
 char to fix it.

Fixes #49803.

Signed-off-by: Enjia Mai <enjia.mai@intel.com>

### CODE REVIEW

File: drivers/interrupt_controller/intc_ioapic.c [hunk 1]
```diff
@@ -438,7 +438,7 @@ static uint32_t __IoApicGet(int32_t offset)
 
 	key = irq_lock();
 
-	*((volatile uint32_t *) (IOAPIC_REG + IOAPIC_IND)) = (char)offset;
+	*((volatile uint32_t *) (IOAPIC_REG + IOAPIC_IND)) = offset;
```
Comment (stephanosio) [inline drivers/interrupt_controller/intc_ioapic.c:441]: If any, it should be casting to `unsigned char` here since the upper 24 bits of the `IOREGSEL` register are reserved (must be 0).

File: drivers/interrupt_controller/intc_ioapic.c [hunk 2]
```diff
@@ -108,8 +108,8 @@ __pinned_bss
 uint32_t ioapic_suspend_buf[SUSPEND_BITS_REQD / 32] = {0};
 #endif
 
-static uint32_t __IoApicGet(int32_t offset);
-static void __IoApicSet(int32_t offset, uint32_t value);
+static uint32_t __IoApicGet(uint32_t offset);
+static void __IoApicSet(uint32_t offset, uint32_t value);
```
Comment (stephanosio) [inline drivers/interrupt_controller/intc_ioapic.c:112]: all these `int32_t` to `uint32_t` type changes seem unnecessary.

**Review by stephanosio — CHANGES_REQUESTED** [review]

File: drivers/interrupt_controller/intc_ioapic.c (hunk 1 above)
Comment (enjiamai) [reply drivers/interrupt_controller/intc_ioapic.c]: Thanks for the review, Got it fixed!

File: drivers/interrupt_controller/intc_ioapic.c (hunk 2 above)
Comment (enjiamai) [reply drivers/interrupt_controller/intc_ioapic.c]: Ok, recovery the change here.

**Review by stephanosio — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by andyross — COMMENTED** [review]
Style whine, not worth a -1 but sort of a code smell thing:

This value is being assigned through a uint32_t pointer.  Why is the cast even there?  If there are high bits set in the "offset" value that should be masked off, then we should be explicit about that.  If there are not, casting to a type that doesn't match the rvalue seems like a bug to me (and it was!).

**Comment by enjiamai** [comment]
> This value is being assigned through a uint32_t pointer. Why is the cast even there? If there are high bits set in the "offset" value that should be masked off, then we should be explicit about that. If there are not, casting to a type that doesn't match the rvalue seems like a bug to me (and it was!).

Thanks for the review! @andyross  . I was also thinking to make the offset to uint32, will do it later.
