### PR TITLE
drivers: flash: mcxw: Clear cache after erase

### LINKED ISSUE #79838: tests: tests/drivers/flash/common: frdm_mcxw71: flash test failure
**Describe the bug**

flash common test failure.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
- frdm_mcxw71
 - What have you tried to diagnose or workaround this issue?
 - NA
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - NO

**To Reproduce**

scripts/twister -p frdm_mcxw71 -T tests/drivers/flash/common

**Expected behavior**
PASS

**Impact**

flash APIfunction

**Logs and console output**

```
*** Booting Zephyr OS build v3.7.0-4339-g1ec5ce05f9f8 ***
Running TESTSUITE flash_driver
===================================================================
START - test_flash_copy
Test will run on device memory-controller@20000
 PASS - test_flash_copy in 0.147 seconds
===================================================================
START - test_flash_erase
Test will run on device memory-controller@20000
i=0:	read_buf[i]=0	expected=255
i=1:	read_buf[i]=0	expected=255
i=2:	read_buf[i]=0	expected=255
i=3:	read_buf[i]=0	expected=255
i=4:	read_buf[i]=0	expected=255
i=5:	read_buf[i]=0	expected=255
i=6:	read_buf[i]=0	expected=255
i=7:	read_buf[i]=0	expected=255
i=8:	read_buf[i]=0	expected=255
i=9:	read_buf[i]=0	expected=255
i=10:	read_buf[i]=0	expected=255
i=11:	read_buf[i]=0	expected=255
i=12:	read_buf[i]=0	expected=255
i=13:	read_buf[i]=0	expected=255
i=14:	read_buf[i]=0	expected=255
i=15:	read_buf[i]=0	expected=255
i=16:	read_buf[i]=16	expected=255
i=17:	read_buf[i]=17	expected=255
i=18:	read_buf[i]=18	expected=255
i=19:	read_buf[i]=19	expected=255
i=20:	read_buf[i]=20	expected=255
i=21:	read_buf[i]=21	expected=255
i=22:	read_buf[i]=22	expected=255
i=23:	read_buf[i]=23	expected=255
i=24:	read_buf[i]=24	expected=255
i=25:	read_buf[i]=25	expected=255
i=26:	read_buf[i]=26	expected=255
i=27:	read_buf[i]=27	expected=255
i=28:	read_buf[i]=28	expected=255
i=29:	read_buf[i]=29	expected=255
i=30:	read_buf[i]=30	expected=255
i=31:	read_buf[i]=31	expected=255
i=32:	read_buf[i]=32	expected=255
i=33:	read_buf[i]=33	expected=255
i=34:	read_buf[i]=34	expected=255
i=35:	read_buf[i]=35	expected=255
i=36:	read_buf[i]=36	expected=255
i=37:	read_buf[i]=37	expected=255
i=38:	read_buf[i]=38	expected=255
i=39:	read_buf[i]=39	expected=255
i=40:	read_buf[i]=40	expected=255
i=41:	read_buf[i]=41	expected=255
i=42:	read_buf[i]=42	expected=255
i=43:	read_buf[i]=43	expected=255
i=44:	read_buf[i]=44	expected=255
i=45:	read_buf[i]=45	expected=255
i=46:	read_buf[i]=46	expected=255
i=47:	read_buf[i]=47	expected=255
i=48:	read_buf[i]=48	expected=255
i=49:	read_buf[i]=49	expected=255
i=50:	read_buf[i]=50	expected=255
i=51:	read_buf[i]=51	expected=255
i=52:	read_buf[i]=52	expected=255
i=53:	read_buf[i]=53	expected=255
i=54:	read_buf[i]=54	expected=255
i=55:	read_buf[i]=55	expected=255
i=56:	read_buf[i]=56	expected=255
i=57:	read_buf[i]=57	expected=255
i=58:	read_buf[i]=58	expected=255
i=59:	read_buf[i]=59	expected=255
i=60:	read_buf[i]=60	expected=255
i=61:	read_buf[i]=61	expected=255
i=62:	read_buf[i]=62	expected=255
i=63:	read_buf[i]=63	expected=255
i=64:	read_buf[i]=64	expected=255
i=65:	read_buf[i]=65	expected=255
i=66:	read_buf[i]=66	expected=255
i=67:	read_buf[i]=67	expected=255
i=68:	read_buf[i]=68	expected=255
i=69:	read_buf[i]=69	expected=255
i=70:	read_buf[i]=70	expected=255
i=71:	read_buf[i]=71	expected=255
i=72:	read_buf[i]=72	expected=255
i=73:	read_buf[i]=73	expected=255
i=74:	read_buf[i]=74	expected=255
i=75:	read_buf[i]=75	expected=255
i=76:	read_buf[i]=76	expected=255
i=77:	read_buf[i]=77	expected=255
i=78:	read_buf[i]=78	expected=255
i=79:	read_buf[i]=79	expected=255
i=80:	read_buf[i]=80	expected=255
i=81:	read_buf[i]=81	expected=255
i=82:	read_buf[i]=82	expected=255
i=83:	read_buf[i]=83	expected=255
i=84:	read_buf[i]=84	expected=255
i=85:	read_buf[i]=85	expected=255
i=86:	read_buf[i]=86	expected=255
i=87:	read_buf[i]=87	expected=255
i=88:	read_buf[i]=88	expected=255
i=89:	read_buf[i]=89	expected=255
i=90:	read_buf[i]=90	expected=255
i=91:	read_buf[i]=91	expected=255
i=92:	read_buf[i]=92	expected=255
i=93:	read_buf[i]=93	expected=255
i=94:	read_buf[i]=94	expected=255
i=95:	read_buf[i]=95	expected=255
i=96:	read_buf[i]=96	expected=255
i=97:	read_buf[i]=97	expected=255
i=98:	read_buf[i]=98	expected=255
i=99:	read_buf[i]=99	expected=255
i=100:	read_buf[i]=100	expected=255
i=101:	read_buf[i]=101	expected=255
i=102:	read_buf[i]=102	expected=255
i=103:	read_buf[i]=103	expected=255
i=104:	read_buf[i]=104	expected=255
i=105:	read_buf[i]=105	expected=255
i=106:	read_buf[i]=106	expected=255
i=107:	read_buf[i]=107	expected=255
i=108:	read_buf[i]=108	expected=255
i=109:	read_buf[i]=109	expected=255
i=110:	read_buf[i]=110	expected=255
i=111:	read_buf[i]=111	expected=255
i=112:	read_buf[i]=112	expected=255
i=113:	read_buf[i]=113	expected=255
i=114:	read_buf[i]=114	expected=255
i=115:	read_buf[i]=115	expected=255
i=116:	read_buf[i]=116	expected=255
i=117:	read_buf[i]=117	expected=255
i=118:	read_buf[i]=118	expected=255
i=119:	read_buf[i]=119	expected=255
i=120:	read_buf[i]=120	expected=255
i=121:	read_buf[i]=121	expected=255
i=122:	read_buf[i]=122	expected=255
i=123:	read_buf[i]=123	expected=255
i=124:	read_buf[i]=124	expected=255
i=125:	read_buf[i]=125	expected=255
i=126:	read_buf[i]=126	expected=255
i=127:	read_buf[i]=127	expected=255
i=128:	read_buf[i]=128	expected=255
i=129:	read_buf[i]=129	expected=255
i=130:	read_buf[i]=130	expected=255
i=131:	read_buf[i]=131	expected=255
i=132:	read_buf[i]=132	expected=255
i=133:	read_buf[i]=133	expected=255
i=134:	read_buf[i]=134	expected=255
i=135:	read_buf[i]=135	expected=255
i=136:	read_buf[i]=136	expected=255
i=137:	read_buf[i]=137	expected=255
i=138:	read_buf[i]=138	expected=255
i=139:	read_buf[i]=139	expected=255
i=140:	read_buf[i]=140	expected=255
i=141:	read_buf[i]=141	expected=255
i=142:	read_buf[i]=142	expected=255
i=143:	read_buf[i]=143	expected=255
i=144:	read_buf[i]=144	expected=255
i=145:	read_buf[i]=145	expected=255
i=146:	read_buf[i]=146	expected=255
i=147:	read_buf[i]=147	expected=255
i=148:	read_buf[i]=148	expected=255
i=149:	read_buf[i]=149	expected=255
i=150:	read_buf[i]=150	expected=255
i=151:	read_buf[i]=151	expected=255
i=152:	read_buf[i]=152	expected=255
i=153:	read_buf[i]=153	expected=255
i=154:	read_buf[i]=154	expected=255
i=155:	read_buf[i]=155	expected=255
i=156:	read_buf[i]=156	expected=255
i=157:	read_buf[i]=157	expected=255
i=158:	read_buf[i]=158	expected=255
i=159:	read_buf[i]=159	expected=255
i=160:	read_buf[i]=160	expected=255
i=161:	read_buf[i]=161	expected=255
i=162:	read_buf[i]=162	expected=255
i=163:	read_buf[i]=163	expected=255
i=164:	read_buf[i]=164	expected=255
i=165:	read_buf[i]=165	expected=255
i=166:	read_buf[i]=166	expected=255
i=167:	read_buf[i]=167	expected=255
i=168:	read_buf[i]=168	expected=255
i=169:	read_buf[i]=169	expected=255
i=170:	read_buf[i]=170	expected=255
i=171:	read_buf[i]=171	expected=255
i=172:	read_buf[i]=172	expected=255
i=173:	read_buf[i]=173	expected=255
i=174:	read_buf[i]=174	expected=255
i=175:	read_buf[i]=175	expected=255
i=176:	read_buf[i]=176	expected=255
i=177:	read_buf[i]=177	expected=255
i=178:	read_buf[i]=178	expected=255
i=179:	read_buf[i]=179	expected=255
i=180:	read_buf[i]=180	expected=255
i=181:	read_buf[i]=181	expected=255
i=182:	read_buf[i]=182	expected=255
i=183:	read_buf[i]=183	expected=255
i=184:	read_buf[i]=184	expected=255
i=185:	read_buf[i]=185	expected=255
i=186:	read_buf[i]=186	expected=255
i=187:	read_buf[i]=187	expected=255
i=188:	read_buf[i]=188	expected=255
i=189:	read_buf[i]=189	expected=255
i=190:	read_buf[i]=190	expected=255
i=191:	read_buf[i]=191	expected=255
i=192:	read_buf[i]=192	expected=255
i=193:	read_buf[i]=193	expected=255
i=194:	read_buf[i]=194	expected=255
i=195:	read_buf[i]=195	expected=255
i=196:	read_buf[i]=196	expected=255
i=197:	read_buf[i]=197	expected=255
i=198:	read_buf[i]=198	expected=255
i=199:	read_buf[i]=199	expected=255
i=200:	read_buf[i]=200	expected=255
i=201:	read_buf[i]=201	expected=255
i=202:	read_buf[i]=202	expected=255
i=203:	read_buf[i]=203	expected=255
i=204:	read_buf[i]=204	expected=255
i=205:	read_buf[i]=205	expected=255
i=206:	read_buf[i]=206	expected=255
i=207:	read_buf[i]=207	expected=255
i=208:	read_buf[i]=208	expected=255
i=209:	read_buf[i]=209	expected=255
i=210:	read_buf[i]=210	expected=255
i=211:	read_buf[i]=211	expected=255
i=212:	read_buf[i]=212	expected=255
i=213:	read_buf[i]=213	expected=255
i=214:	read_buf[i]=214	expected=255
i=215:	read_buf[i]=215	expected=255
i=216:	read_buf[i]=216	expected=255
i=217:	read_buf[i]=217	expected=255
i=218:	read_buf[i]=218	expected=255
i=219:	read_buf[i]=219	expected=255
i=220:	read_buf[i]=220	expected=255
i=221:	read_buf[i]=221	expected=255
i=222:	read_buf[i]=222	expected=255
i=223:	read_buf[i]=223	expected=255
i=224:	read_buf[i]=224	expected=255
i=225:	read_buf[i]=225	expected=255
i=226:	read_buf[i]=226	expected=255
i=227:	read_buf[i]=227	expected=255
i=228:	read_buf[i]=228	expected=255
i=229:	read_buf[i]=229	expected=255
i=230:	read_buf[i]=230	expected=255
i=231:	read_buf[i]=231	expected=255
i=232:	read_buf[i]=232	expected=255
i=233:	read_buf[i]=233	expected=255
i=234:	read_buf[i]=234	expected=255
i=235:	read_buf[i]=235	expected=255
i=236:	read_buf[i]=236	expected=255
i=237:	read_buf[i]=237	expected=255
i=238:	read_buf[i]=238	expected=255
i=239:	read_buf[i]=239	expected=255
i=240:	read_buf[i]=240	expected=255
i=241:	read_buf[i]=241	expected=255
i=242:	read_buf[i]=242	expected=255
i=243:	read_buf[i]=243	expected=255
i=244:	read_buf[i]=244	expected=255
i=245:	read_buf[i]=245	expected=255
i=246:	read_buf[i]=246	expected=255
i=247:	read_buf[i]=247	expected=255
i=248:	read_buf[i]=248	expected=255
i=249:	read_buf[i]=249	expected=255
i=250:	read_buf[i]=250	expected=255
i=251:	read_buf[i]=251	expected=255
i=252:	read_buf[i]=252	expected=255
i=253:	read_buf[i]=253	expected=255
i=254:	read_buf[i]=254	expected=255
i=255:	read_buf[i]=0	expected=255
i=256:	read_buf[i]=1	expected=255
i=257:	read_buf[i]=2	expected=255
i=258:	read_buf[i]=3	expected=255
i=259:	read_buf[i]=4	expected=255
i=260:	read_buf[i]=5	expected=255
i=261:	read_buf[i]=6	expected=255
i=262:	read_buf[i]=7	expected=255
i=263:	read_buf[i]=8	expected=255
i=264:	read_buf[i]=9	expected=255
i=265:	read_buf[i]=10	expected=255
i=266:	read_buf[i]=11	expected=255
i=267:	read_buf[i]=12	expected=255
i=268:	read_buf[i]=13	expected=255
i=269:	read_buf[i]=14	expected=255
i=270:	read_buf[i]=15	expected=255
i=271:	read_buf[i]=16	expected=255
i=272:	read_buf[i]=17	expected=255
i=273:	read_buf[i]=18	expected=255
i=274:	read_buf[i]=19	expected=255
i=275:	read_buf[i]=20	expected=255
i=276:	read_buf[i]=21	expected=255
i=277:	read_buf[i]=22	expected=255
i=278:	read_buf[i]=23	expected=255
i=279:	read_buf[i]=24	expected=255
i=280:	read_buf[i]=25	expected=255
i=281:	read_buf[i]=26	expected=255
i=282:	read_buf[i]=27	expected=255
i=283:	read_buf[i]=28	expected=255
i=284:	read_buf[i]=29	expected=255
i=285:	read_buf[i]=30	expected=255
i=286:	read_buf[i]=31	expected=255
i=287:	read_buf[i]=32	expected=255
i=288:	read_buf[i]=33	expected=255
i=289:	read_buf[i]=34	expected=255
i=290:	read_buf[i]=35	expected=255
i=291:	read_buf[i]=36	expected=255
i=292:	read_buf[i]=37	expected=255
i=293:	read_buf[i]=38	expected=255
i=294:	read_buf[i]=39	expected=255
i=295:	read_buf[i]=40	expected=255
i=296:	read_buf[i]=41	expected=255
i=297:	read_buf[i]=42	expected=255
i=298:	read_buf[i]=43	expected=255
i=299:	read_buf[i]=44	expected=255
i=300:	read_buf[i]=45	expected=255
i=301:	read_buf[i]=46	expected=255
i=302:	read_buf[i]=47	expected=255
i=303:	read_buf[i]=48	expected=255
i=304:	read_buf[i]=49	expected=255
i=305:	read_buf[i]=50	expected=255
i=306:	read_buf[i]=51	expected=255
i=307:	read_buf[i]=52	expected=255
i=308:	read_buf[i]=53	expected=255
i=309:	read_buf[i]=54	expected=255
i=310:	read_buf[i]=55	expected=255
i=311:	read_buf[i]=56	expected=255
i=312:	read_buf[i]=57	expected=255
i=313:	read_buf[i]=58	expected=255
i=314:	read_buf[i]=59	expected=255
i=315:	read_buf[i]=60	expected=255
i=316:	read_buf[i]=61	expected=255
i=317:	read_buf[i]=62	expected=255
i=318:	read_buf[i]=63	expected=255
i=319:	read_buf[i]=64	expected=255
i=320:	read_buf[i]=65	expected=255
i=321:	read_buf[i]=66	expected=255
i=322:	read_buf[i]=67	expected=255
i=323:	read_buf[i]=68	expected=255
i=324:	read_buf[i]=69	expected=255
i=325:	read_buf[i]=70	expected=255
i=326:	read_buf[i]=71	expected=255
i=327:	read_buf[i]=72	expected=255
i=328:	read_buf[i]=73	expected=255
i=329:	read_buf[i]=74	expected=255
i=330:	read_buf[i]=75	expected=255
i=331:	read_buf[i]=76	expected=255
i=332:	read_buf[i]=77	expected=255
i=333:	read_buf[i]=78	expected=255
i=334:	read_buf[i]=79	expected=255
i=335:	read_buf[i]=80	expected=255
i=336:	read_buf[i]=81	expected=255
i=337:	read_buf[i]=82	expected=255
i=338:	read_buf[i]=83	expected=255
i=339:	read_buf[i]=84	expected=255
i=340:	read_buf[i]=85	expected=255
i=341:	read_buf[i]=86	expected=255
i=342:	read_buf[i]=87	expected=255
i=343:	read_buf[i]=88	expected=255
i=344:	read_buf[i]=89	expected=255
i=345:	read_buf[i]=90	expected=255
i=346:	read_buf[i]=91	expected=255
i=347:	read_buf[i]=92	expected=255
i=348:	read_buf[i]=93	expected=255
i=349:	read_buf[i]=94	expected=255
i=350:	read_buf[i]=95	expected=255
i=351:	read_buf[i]=96	expected=255
i=352:	read_buf[i]=97	expected=255
i=353:	read_buf[i]=98	expected=255
i=354:	read_buf[i]=99	expected=255
i=355:	read_buf[i]=100	expected=255
i=356:	read_buf[i]=101	expected=255
i=357:	read_buf[i]=102	expected=255
i=358:	read_buf[i]=103	expected=255
i=359:	read_buf[i]=104	expected=255
i=360:	read_buf[i]=105	expected=255
i=361:	read_buf[i]=106	expected=255
i=362:	read_buf[i]=107	expected=255
i=363:	read_buf[i]=108	expected=255
i=364:	read_buf[i]=109	expected=255
i=365:	read_buf[i]=110	expected=255
i=366:	read_buf[i]=111	expected=255
i=367:	read_buf[i]=112	expected=255
i=368:	read_buf[i]=113	expected=255
i=369:	read_buf[i]=114	expected=255
i=370:	read_buf[i]=115	expected=255
i=371:	read_buf[i]=116	expected=255
i=372:	read_buf[i]=117	expected=255
i=373:	read_buf[i]=118	expected=255
i=374:	read_buf[i]=119	expected=255
i=375:	read_buf[i]=120	expected=255
i=376:	read_buf[i]=121	expected=255
i=377:	read_buf[i]=122	expected=255
i=378:	read_buf[i]=123	expected=255
i=379:	read_buf[i]=124	expected=255
i=380:	read_buf[i]=125	expected=255
i=381:	read_buf[i]=126	expected=255
i=382:	read_buf[i]=127	expected=255
i=383:	read_buf[i]=128	expected=255
i=384:	read_buf[i]=129	expected=255
i=385:	read_buf[i]=130	expected=255
i=386:	read_buf[i]=131	expected=255
i=387:	read_buf[i]=132	expected=255
i=388:	read_buf[i]=133	expected=255
i=389:	read_buf[i]=134	expected=255
i=390:	read_buf[i]=135	expected=255
i=391:	read_buf[i]=136	expected=255
i=392:	read_buf[i]=137	expected=255
i=393:	read_buf[i]=138	expected=255
i=394:	read_buf[i]=139	expected=255
i=395:	read_buf[i]=140	expected=255
i=396:	read_buf[i]=141	expected=255
i=397:	read_buf[i]=142	expected=255
i=398:	read_buf[i]=143	expected=255
i=399:	read_buf[i]=144	expected=255
i=400:	read_buf[i]=145	expected=255
i=401:	read_buf[i]=146	expected=255
i=402:	read_buf[i]=147	expected=255
i=403:	read_buf[i]=148	expected=255
i=404:	read_buf[i]=149	expected=255
i=405:	read_buf[i]=150	expected=255
i=406:	read_buf[i]=151	expected=255
i=407:	read_buf[i]=152	expected=255
i=408:	read_buf[i]=153	expected=255
i=409:	read_buf[i]=154	expected=255
i=410:	read_buf[i]=155	expected=255
i=411:	read_buf[i]=156	expected=255
i=412:	read_buf[i]=157	expected=255
i=413:	read_buf[i]=158	expected=255
i=414:	read_buf[i]=159	expected=255
i=415:	read_buf[i]=160	expected=255
i=416:	read_buf[i]=161	expected=255
i=417:	read_buf[i]=162	expected=255
i=418:	read_buf[i]=163	expected=255
i=419:	read_buf[i]=164	expected=255
i=420:	read_buf[i]=165	expected=255
i=421:	read_buf[i]=166	expected=255
i=422:	read_buf[i]=167	expected=255
i=423:	read_buf[i]=168	expected=255
i=424:	read_buf[i]=169	expected=255
i=425:	read_buf[i]=170	expected=255
i=426:	read_buf[i]=171	expected=255
i=427:	read_buf[i]=172	expected=255
i=428:	read_buf[i]=173	expected=255
i=429:	read_buf[i]=174	expected=255
i=430:	read_buf[i]=175	expected=255
i=431:	read_buf[i]=176	expected=255
i=432:	read_buf[i]=177	expected=255
i=433:	read_buf[i]=178	expected=255
i=434:	read_buf[i]=179	expected=255
i=435:	read_buf[i]=180	expected=255
i=436:	read_buf[i]=181	expected=255
i=437:	read_buf[i]=182	expected=255
i=438:	read_buf[i]=183	expected=255
i=439:	read_buf[i]=184	expected=255
i=440:	read_buf[i]=185	expected=255
i=441:	read_buf[i]=186	expected=255
i=442:	read_buf[i]=187	expected=255
i=443:	read_buf[i]=188	expected=255
i=444:	read_buf[i]=189	expected=255
i=445:	read_buf[i]=190	expected=255
i=446:	read_buf[i]=191	expected=255
i=447:	read_buf[i]=192	expected=255
i=448:	read_buf[i]=193	expected=255
i=449:	read_buf[i]=194	expected=255
i=450:	read_buf[i]=195	expected=255
i=451:	read_buf[i]=196	expected=255
i=452:	read_buf[i]=197	expected=255
i=453:	read_buf[i]=198	expected=255
i=454:	read_buf[i]=199	expected=255
i=455:	read_buf[i]=200	expected=255
i=456:	read_buf[i]=201	expected=255
i=457:	read_buf[i]=202	expected=255
i=458:	read_buf[i]=203	expected=255
i=459:	read_buf[i]=204	expected=255
i=460:	read_buf[i]=205	expected=255
i=461:	read_buf[i]=206	expected=255
i=462:	read_buf[i]=207	expected=255
i=463:	read_buf[i]=208	expected=255
i=464:	read_buf[i]=209	expected=255
i=465:	read_buf[i]=210	expected=255
i=466:	read_buf[i]=211	expected=255
i=467:	read_buf[i]=212	expected=255
i=468:	read_buf[i]=213	expected=255
i=469:	read_buf[i]=214	expected=255
i=470:	read_buf[i]=215	expected=255
i=471:	read_buf[i]=216	expected=255
i=472:	read_buf[i]=217	expected=255
i=473:	read_buf[i]=218	expected=255
i=474:	read_buf[i]=219	expected=255
i=475:	read_buf[i]=220	expected=255
i=476:	read_buf[i]=221	expected=255
i=477:	read_buf[i]=222	expected=255
i=478:	read_buf[i]=223	expected=255
i=479:	read_buf[i]=224	expected=255
i=480:	read_buf[i]=225	expected=255
i=481:	read_buf[i]=226	expected=255
i=482:	read_buf[i]=227	expected=255
i=483:	read_buf[i]=228	expected=255
i=484:	read_buf[i]=229	expected=255
i=485:	read_buf[i]=230	expected=255
i=486:	read_buf[i]=231	expected=255
i=487:	read_buf[i]=232	expected=255
i=488:	read_buf[i]=233	expected=255
i=489:	read_buf[i]=234	expected=255
i=490:	read_buf[i]=235	expected=255
i=491:	read_buf[i]=236	expected=255
i=492:	read_buf[i]=237	expected=255
i=493:	read_buf[i]=238	expected=255
i=494:	read_buf[i]=239	expected=255
i=495:	read_buf[i]=240	expected=255
i=496:	read_buf[i]=241	expected=255
i=497:	read_buf[i]=242	expected=255
i=498:	read_buf[i]=243	expected=255
i=499:	read_buf[i]=244	expected=255
i=500:	read_buf[i]=245	expected=255
i=501:	read_buf[i]=246	expected=255
i=502:	read_buf[i]=247	expected=255
i=503:	read_buf[i]=248	expected=255
i=504:	read_buf[i]=249	expected=255
i=505:	read_buf[i]=250	expected=255
i=506:	read_buf[i]=251	expected=255
i=507:	read_buf[i]=252	expected=255
i=508:	read_buf[i]=253	expected=255
i=509:	read_buf[i]=254	expected=255
i=511:	read_buf[i]=0	expected=255

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/flash/common/src/main.c:303: flash_driver_test_flash_erase: (comparison_result is false)
Write operation failed
 FAIL - test_flash_erase in 1.639 seconds
===================================================================
START - test_flash_fill
Test will run on device memory-controller@20000
 PASS - test_flash_fill in 0.076 seconds
===================================================================
START - test_flash_flatten
Test will run on device memory-controller@20000
 PASS - test_flash_flatten in 0.078 seconds
===================================================================
START - test_flash_page_layout
Test will run on device memory-controller@20000
start_offset=0xe0000	size=8192	index=112
page_count=128
 PASS - test_flash_page_layout in 0.012 seconds
===================================================================
START - test_read_unaligned_address
Test will run on device memory-controller@20000
 PASS - test_read_unaligned_address in 0.012 seconds
===================================================================
TESTSUITE flash_driver failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  83.33% [flash_driver]: pass = 5, fail = 1, skip = 0, total = 6 duration = 1.964 seconds
 - PASS - [flash_driver.test_flash_copy] duration = 0.147 seconds
 - FAIL - [flash_driver.test_flash_erase] duration = 1.639 seconds
 - PASS - [flash_driver.test_flash_fill] duration = 0.076 seconds
 - PASS - [flash_driver.test_flash_flatten] duration = 0.078 seconds
 - PASS - [flash_driver.test_flash_page_layout] duration = 0.012 seconds
 - PASS - [flash_driver.test_read_unaligned_address] duration = 0.012 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
RunID: b9d2fd38495e4328cdb2d204f674288e
PROJECT EXECUTION FAILED

```

**Environment (please complete the following information):**

 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.7.0-4339-g1ec5ce05f9f8

### PR DESCRIPTION
**Pull request by decsny**
Cache needs to be cleared after erase in order to read back erased values correctly.

Fixes #79838

### CODE REVIEW

**Review by danieldegrasse — DISMISSED** [review]

File: drivers/flash/soc_flash_mcux.c [hunk 1]
```diff
@@ -172,6 +172,20 @@ static int flash_mcux_erase(const struct device *dev, off_t offset,
...
+	const uint32_t mcxw_flash_cache_clear_bit = BIT(8);
+	const uint32_t mcxw_smscm_ocmdr0_reg_addr = 0x40015400;
+	volatile uint32_t *smscm_ocmdr0 = (volatile uint32_t *)mcxw_smscm_ocmdr0_reg_addr;
+	*smscm_ocmdr0 |= mcxw_flash_cache_clear_bit;
+	/* clear code cache */
+	const uint32_t mcxw_code_cache_clear_bit = BIT(0);
+	const uint32_t mcxw_mcm_cpcr2_reg_addr = 0xe0080034;
+	volatile uint32_t *mcm_cpcr2 = (volatile uint32_t *)mcxw_mcm_cpcr2_reg_addr;
+	*mcm_cpcr2 |= mcxw_code_cache_clear_bit;
+#endif
```
Comment (mmahadevan108) [inline drivers/flash/soc_flash_mcux.c:187]: Would you not need similar cache management code after writes? 
Also is it possible to invalidate a certain range instead of the whole cache?

Comment (decsny) [reply drivers/flash/soc_flash_mcux.c:187]: doesn't seem to be needed after writes since write goes through the cache, erase operation doesn't involve writing any data

and no, there is no way to clear a certain range as far as I can find

**Review by mmahadevan108 — DISMISSED** [review]

File: drivers/flash/soc_flash_mcux.c (hunk 1 above)
Comment (decsny) [reply drivers/flash/soc_flash_mcux.c]: i updated the PR to also put it after programs

**Review by dleach02 — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
