### PR TITLE
drivers: pinmux: esp32: Fix using gpio as IO at the same time.

### LINKED ISSUE #5650: i2c driver test on ESP32 fails with error
Using GPIO 25 as SCL and GPIO 26 as SDA (tried with other GPIO pins from default ones too) for the i2c module for ESP32, with a sensor GY271 fails with error 'FAILED TO CONFIGURE SENSOR'. However, passes with GPIO bit banging with ESP32. Hence, driver needs debugging.

Attached log below

### PR DESCRIPTION
**Pull request by iha**
Since PINMUX_INPUT_ENABLED == 1 and PINMUX_OUTPUT_ENABLED == 0,
we can not set a gpio port as input and output at the same time,

So we always set the gpio as input. Thus, the gpio can be used on
I2C drivers for example.

Signed-off-by: Vitor Massaru Iha <vitor@massaru.org>

Fixes #5650

### CODE REVIEW

File: drivers/pinmux/pinmux_esp32.c [hunk 1]
```diff
@@ -123,16 +123,19 @@ static int pinmux_input(struct device *dev, u32_t pin, u8_t func)
 	volatile u32_t *reg;
 	int r;
 
+	/* Since PINMUX_INPUT_ENABLED == 1 and PINMUX_OUTPUT_ENABLED == 0,
```
Comment (lpereira) [inline drivers/pinmux/pinmux_esp32.c]: What would happen if one wanted a pin to be used as output?

Comment (iha) [reply drivers/pinmux/pinmux_esp32.c]: I tested the gpio sample and it worked, but I'm not sure if there will be problems under other conditions. I'm going to try another approach to using pins as IO.

Comment (iha) [reply drivers/pinmux/pinmux_esp32.c]: Can I add the flags below so we can set the pin as IO and avoid the workaround? 

`#define GPIO_DIR_IN_OUT (1 << 18)` on _gpio.h_

`#define  PINMUX_INPUT_OUTPUT_ENABLED (0x2)` on _pinmux.h_

Comment (lpereira) [reply drivers/pinmux/pinmux_esp32.c]: I believe that API changes at this level requires some more input. We're reviewing a lot of our APIs, so it's good to have feedback like this. Please open an issue and link it to #5697.

**Review by lpereira — APPROVED** [review]
LGTM
