### PR TITLE
shell: Add TELNET backend

### LINKED ISSUE #12611: Shell does not support network backends
**Describe the bug**
I have created the example Telnet console application for the board FRDM-K64F under Windows. 
Although I get a connection to the board with a telnet client, but there are no inputs and outputs on the client possible.

**To Reproduce**
1. cd samples/net/telnet
2. mkdir build; cd build
4. cmake -GNinja -DBOARD=frdm_k64f ..
5. ninja
6. Put the result zephyr/zephyr.bin into the board
7. wait until dhcpv4 has finished
8. connect with a Telnet-client 

**Expected behavior**
Input/Output to the Shell via Telnet-console

**console output**
uart:~$ ***** Booting Zephyr OS zephyr-v1.13.0-2584-g8ec7c73d2e *****
[00:00:00.008,451] <inf> net_config.net_config_init: Initializing network
[00:00:00.008,474] <inf> net_config.setup_ipv4: IPv4 address: 10.0.0.62
[00:00:00.008,489] <inf> net_config.setup_dhcpv4: Running dhcpv4 client...
[00:00:06.021,795] <inf> net_dhcpv4.dhcpv4_handle_msg_ack: Received: 10.0.1.32
[00:00:06.021,829] <inf> net_config.ipv4_addr_add_handler: IPv4 address: 10.0.1.32
[00:00:06.021,832] <inf> net_config.ipv4_addr_add_handler: Lease time: 86400 seconds
[00:00:06.021,846] <inf> net_config.ipv4_addr_add_handler: Subnet: 255.255.254.0
[00:00:06.021,859] <inf> net_config.ipv4_addr_add_handler: Router: 10.0.0.254
[00:00:08.020,315] <dbg> net_telnet.telnet_setup_server: Telnet console enabled on AF_INET
[00:00:08.020,341] <inf> net_telnet.telnet_console_init: Telnet console initialized
[00:00:08.020,346] <inf> net_telnet_sample.main: Starting Telnet sample
[00:00:19.963,597] <dbg> net_telnet.telnet_accept: Telnet client connected (family AF_INET)

**Environment:**
 - OS: Windows
 - Toolchain: gccarmemb Version 7.3.1

### PR DESCRIPTION
**Pull request by rlubos**
Introduce new TELNET backend for shell module, based on the `telnet_console` driver. As the orignal code did not fit well with the shell API (it used `printk` and `line_fifo`), I've reused pieces of code and created a new shell backend with it.

As the old `telnet_console` is based on the deprecated `line_fifo` and is on longer used in Zephyr, so I took the liberty and removed it.

There is a little support for TELNET commands (just as in the original code), but I'm aware it's far from ideal.

Resolves #12611.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

File: subsys/shell/shell_telnet.c [hunk 1]
```diff
@@ -0,0 +1,493 @@
...
+			  int error,
+			  void *user_data)
+{
+	if (error) {
+		LOG_ERR("Error %d", error);
+		goto error;
+	}
+
+	if (sh_telnet->client_ctx) {
+		LOG_WRN("A telnet client is already in.");
```
Comment (jukkar) [inline subsys/shell/shell_telnet.c]: Warning sounds too much here, perhaps info is enough as we are just telling user that someone is already connected which does not sound a warning type of thing.

File: subsys/shell/Kconfig.backends [hunk 2]
```diff
@@ -167,6 +167,92 @@ source "subsys/logging/Kconfig.template.log_config"
 
 endif #SHELL_BACKEND_RTT
 
+config SHELL_BACKEND_TELNET
+	bool "Enable TELNET backend."
```
Comment (jukkar) [inline subsys/shell/Kconfig.backends]: Add here also dependency to
* TCP
* IPv4
* IPv6

Currently it is possible to configure system so that both IPv4 and IPv6 are disabled, so we need to cover that here.

File: subsys/shell/shell_telnet.c [hunk 3]
```diff
@@ -0,0 +1,493 @@
...
+
+	if (*ctx) {
+		net_context_put(*ctx);
+		*ctx = NULL;
+	}
+}
+
+static int telnet_init(void)
+{
+#ifdef CONFIG_NET_IPV4
```
Comment (jukkar) [inline subsys/shell/shell_telnet.c]: Hmm, github lost my comment here, weird. Writing it again:
Better would use IS_ENABLED() here like this
```
if (IS_ENABLED(CONFIG_NET_IPV4)) {
	struct sockaddr_in any_addr4 = {
		.sin_family = AF_INET,
		.sin_port = htons(TELNET_PORT),
		.sin_addr = INADDR_ANY_INIT
	};
	static struct net_context *ctx4;

	telnet_setup_server(&ctx4, AF_INET,
			    (struct sockaddr *)&any_addr4,
			    sizeof(any_addr4));
}
```
and same for IPv6

File: subsys/shell/shell_telnet.c (hunk 1 above)
Comment (pfalcon) [reply subsys/shell/shell_telnet.c]: > Warning sounds too much here

Well, depends. It may be a security feature too, if a (single) legitimate user tries to log in, and finds that someone else is logged in too.

File: subsys/shell/Kconfig.backends [hunk 4]
```diff
@@ -167,6 +167,92 @@ source "subsys/logging/Kconfig.template.log_config"
...
+
+config SHELL_BACKEND_TELNET_LOG_LEVEL_ERR
+	bool "Error"
+
+config SHELL_BACKEND_TELNET_LOG_LEVEL_NONE
+	bool "None"
+
+endchoice
+
+config SHELL_BACKEND_TELNET_LOG_LEVEL
```
Comment (nordic-krch) [inline subsys/shell/Kconfig.backends]: this could be renamed to `SHELL_TELNET_INIT_LOG_LEVEL` and `SHELL_BACKEND_TELNET_LOG_LEVEL_<lvl>` -> `SHELL_TELNET_INIT_LOG_LEVEL_<lvl>`. RTT is using that naming https://github.com/zephyrproject-rtos/zephyr/blob/766edd449d6c9b654ca49aa21390b9514e9e6aa6/subsys/shell/Kconfig.backends#L155 and serial could also be changed to use that since it's more descriptive.

File: subsys/shell/Kconfig.backends [hunk 5]
```diff
@@ -167,6 +167,92 @@ source "subsys/logging/Kconfig.template.log_config"
...
 endif #SHELL_BACKEND_RTT
 
+config SHELL_BACKEND_TELNET
+	bool "Enable TELNET backend."
+	help
+	  Enable TELNET backend.
+
+if SHELL_BACKEND_TELNET
+
+config SHELL_BACKEND_TELNET_PORT
```
Comment (nordic-krch) [inline subsys/shell/Kconfig.backends]: imo, you can change prefix to `SHELL_TELNET_<..>`.  It's rather clear that it's a backend. I know that serial has backend in the name but rtt does not so there is no consistency and i would prefer to remove `_BACKEND_` part from other backend in the future to make those defines shorter.

File: subsys/shell/shell_telnet.c [hunk 6]
```diff
@@ -0,0 +1,493 @@
...
+#ifdef CONFIG_SHELL_BACKEND_TELNET_SUPPORT_COMMAND
+
+static void telnet_command_send_reply(u8_t *msg, u16_t len)
+{
+	int err;
+
+	err = net_context_send(sh_telnet->client_ctx, msg, len, telnet_sent_cb,
+			       K_FOREVER, NULL);
+	if (err < 0) {
+		NET_ERR("Failed to send command %d, shutting down", err);
```
Comment (nordic-krch) [inline subsys/shell/shell_telnet.c]: use LOG_ERR. like in line 58.

File: subsys/shell/shell_telnet.c [hunk 7]
```diff
@@ -0,0 +1,493 @@
...
+static int enable(const struct shell_transport *transport, bool blocking)
+{
+	if (sh_telnet == NULL) {
+		return -ENODEV;
+	}
+
+	return 0;
+}
+
+static int write(const struct shell_transport *transport,
```
Comment (nordic-krch) [inline subsys/shell/shell_telnet.c]: is it possible that write will not handle requested length (`length != *cnt`)? If yes then i'm missing a place where TX_DONE event would be sent to the shell. If not all data is sent then shell will block and wait for signal generated from the context of TX_DONE event.

File: subsys/shell/shell_telnet.c [hunk 8]
```diff
@@ -0,0 +1,493 @@
...
+static int uninit(const struct shell_transport *transport)
+{
+	if (sh_telnet == NULL) {
+		return -ENODEV;
+	}
+
+	return 0;
+}
+
+static int enable(const struct shell_transport *transport, bool blocking)
```
Comment (nordic-krch) [inline subsys/shell/shell_telnet.c]: i see that `blocking` flag is not handled. Does telnet shell works in blocking way? does it require interrupts? if shell enables backend in `blocking` mode, it means that it will be used from any context (even highest priority interrupt). If backend requires context switching then on blocking set to true, backend should be closed.

Please consider that even in on hw platforms it may not be supported, it may be on emulated or native posix.

File: include/shell/shell_telnet.h [hunk 9]
```diff
@@ -0,0 +1,75 @@
...
+	 *  to send the shell prompt for instance.
+	 */
+	struct k_timer send_timer;
+
+	/** If set, no output is sent to the TELNET client. */
+	bool output_lock;
+};
+
+#define SHELL_TELNET_DEFINE(_name)					\
+	static struct shell_telnet _name##_shell_telnet;			\
```
Comment (nordic-krch) [inline include/shell/shell_telnet.h]: additional tab

File: subsys/shell/shell_telnet.c [hunk 10]
```diff
@@ -0,0 +1,493 @@
...
+	NET_PKT_DATA_ACCESS_CONTIGUOUS_DEFINE(cmd_access, u16_t);
+	struct telnet_simple_command *cmd;
+
+	cmd = (struct telnet_simple_command *)net_pkt_get_data(pkt,
+							       &cmd_access);
+	if (!cmd || cmd->iac != NVT_CMD_IAC) {
+		return false;
+	}
+
+#ifdef CONFIG_SHELL_BACKEND_TELNET_SUPPORT_COMMAND
```
Comment (nordic-krch) [inline subsys/shell/shell_telnet.c]: use IS_ENABLED() and you won't need `#ifdef` around function implementation as well.

**Review by nordic-krch — CHANGES_REQUESTED** [review]

File: subsys/shell/Kconfig.backends [hunk 11]
```diff
@@ -167,6 +167,92 @@ source "subsys/logging/Kconfig.template.log_config"
...
+	  to extend such support.
+
+module = SHELL_BACKEND_TELNET
+default-timeout = 100
+source "subsys/shell/Kconfig.template.shell_log_queue_timeout"
+
+default-size = 10
+source "subsys/shell/Kconfig.template.shell_log_queue_size"
+
+choice
```
[the remark this answers is not in the document]
Comment (rlubos) [reply subsys/shell/Kconfig.backends]: Just got a clarification from @nordic-krch - these are two separate configs.

The config we provide explicitly specifies the maximum level of logs that will be pushed through the specific backend. So for instance you can have DEBUG log level enabled globally and push these logs through UART, but have TELNET backend configured to pass only the WARNING level. Hopefully, it'll get cleaner after renaming it to `SHELL_TELNET_INIT_LOG_LEVEL` as suggested by @nordic-krch.

The config from the template is used just as in other modules, to specify what level of logs TELNET backend will produce.

File: subsys/shell/shell_telnet.c (hunk 7 above)
Comment (rlubos) [reply subsys/shell/shell_telnet.c]: This could happen in case of some error at the networking layer (e. g. connection got closed by peer). In that case, no further data will be sent anyway, so I guess we could drop them by setting `*cnt = length`.

Will add TX_DONE after data is sent/queued if that's needed.

File: subsys/shell/shell_telnet.c (hunk 8 above)
Comment (rlubos) [reply subsys/shell/shell_telnet.c]: It should not be an issue for TELNET. It does work in a blocking manner by default, but the actual processing of outgoing packets is handled by a separate thread, we do not wait for any IRQs here. In the worst case, we should run out of the network packet buffers and return an error, I don't expect any deadlock here.

**Comment by rlubos** [comment]
I've applied the changes requested and pushed the updated version.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by nordic-krch — APPROVED** [review]
