### PR TITLE
drivers: usb: nordic: Do not log an error if HFCLK is busy

### LINKED ISSUE #15145: USB HF clock stop fail
**Describe the bug**
Replicated with PCA20041 (probably will be replicated with anything else with nrf52840). Plug and unplug USB. Observe that sometimes we get `HF clock stop fail` with some error =16 or -69. 

**To Reproduce**
Plug/unplug the USB.

**Expected behavior**
HF clock must be stopped.

**Impact**
Showstopper as HF clock consumes power. Current consumption will increase from few uA to few hundreds uA.

**Screenshots or console output**
```
DUT USB OFF
WAITING FOR state:DISCONNECTED.
[00882599] <inf> ble_state: Disconnected from ce:2e:90:f8:63:ef (random) (reason 19)
[00882606] <inf> event_manager: e: ble_peer_event id=0x200025fc DISCONNECTED
[00882608] <inf> ble_adv: Advertising stopped
[00882608] <inf> ble_adv: Use fast advertising
[00882633] <inf> ble_adv: Advertising started
[00882633] <inf> hid_state: Subscriber 0x200025fc disconnected
[00882640] <inf> event_manager: e: led_event led_id:1 mode:BLINKING period:1000 color: < 150 0 0 >
[00890356] <err> usb_nrfx: HF clock stop fail: -16
[00890357] <inf> usb_state: USB HID disabled
[00890360] <inf> event_manager: e: hid_report_subscription_event MOUSE report notification disabled by 0x2000421e
[00890361] <inf> hid_state: Clear report data (0)
[00890363] <inf> event_manager: e: usb_state_event id:0x2000421e state:DISCONNECTED
```

**Environment (please complete the following information):**
 ncs zephyr: `0bf5263b0522bb5cfac84eefdfdee86dc2c67e3e` (upstream `d3bb3cf`)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pawelzadrozniak**
HFCLK may be requested for multiple modules, i.e. Bluetooth stack.
When any other module has requested HFCLK to run, the driver will
return -EBUSY on free attempt which is not an error - thie means
that free request has been processed, but someone else is still
requiring the clock to run. When all clock users free the clock,
is is then stopped to save power. Driver may also return -EAGAIN
when any other module is accesing the driver at the same time.
A proper reaction to -EAGAIN has been implemented here (wait and
try again).

Fixes: #15145

Signed-off-by: Paweł Zadrożniak <pawel.zadrozniak@nordicsemi.no>

### CODE REVIEW

**Review by masz-nordic — APPROVED** [review]
`attempts` could be a `#define` or even a Kconfig option instead of magic number.

File: drivers/usb/device/usb_dc_nrfx.c [hunk 1]
```diff
@@ -533,31 +533,49 @@ void usb_dc_nrfx_power_event_callback(nrf_power_event_t event)
...
+				ret = 0;
+			}
 		}
-		ret = clock_control_on(clock, (void *)blocking);
-	} else {
-		if (!clock_requested) {
-			/* Cancel the operation if clock has not
-			 * been requested by this driver before.
+		--attempts;
+		if (ret == -EAGAIN) {
```
Comment (pdunaj) [inline drivers/usb/device/usb_dc_nrfx.c]: I am not sure if there is a point in doing that. If thread that we wait for is of lower priority it will never run so the only case this code will cover is when two threads are of the same priority. Since it is not the most generic case I guess code could just return `-EAGAIN`.

**Comment by carlescufi** [comment]
@anangl can you review this one?

File: drivers/usb/device/usb_dc_nrfx.c (hunk 1 above)
Comment (carlescufi) [reply drivers/usb/device/usb_dc_nrfx.c]: Also, can't this function be called from ISR? If so I don't think we should be calling `k_yield()` from it.

Comment (pdunaj) [reply drivers/usb/device/usb_dc_nrfx.c]: I checked that this is called from places where mutex is taken so API wise nothing changes.

Comment (pawelzadrozniak) [reply drivers/usb/device/usb_dc_nrfx.c]: Looks like it's more complicated issue. Returning -EAGAIN to application (usb_disable() -> usb_dc_detach() -> hf_clock_enable(false, false) because of clock does not make sense to me.

IMO the clock driver should be heavily reworked. It has some pseudo-mutex (m16src_grd) and it's used by BT stuff which works out of OS context. If it's a OS driver using OS API then the is should use OS primitives (mutex) and deal with out-of-context stuff and dirty hacks internally. Btw. -EAGAIN is not event handled in BT - ll_sw/ctrl.c: mayfly_xtal_start().

It's out of context if this PR, so I'll leave is as it is (without -EAGAIN handling) until the clock management driver is dealt with.

**Review by anangl — COMMENTED** [review]
I agree that this `-EAGAIN` problem is not to be resolved here but in the clock control driver. But what worries me a bit, and is kind of related, is that `hf_clock_enable(false, ...)` is called from two places. Is this guaranteed that there won't be more attempts to stop the clock than there were request to start it?

**Review by carlescufi — APPROVED** [review]
