### PR TITLE
Bluetooth: Keys: Fix BT_KEYS_OVERWRITE_OLDEST logic for BT_MAX_CONN > 1

### LINKED ISSUE #35999: Unexpected Bluetooth disconnection and removal of bond
**Describe the bug**
When using BT_KEYS_OVERWRITE_OLDEST=y and BT_MAX_CONN > 1 a connected device (if it is deemed the oldest bond) can be disconnected and bond removed.

**To Reproduce**
Use kconfig options with Bluetooth peripheral sample and protect the BAS characteristic with `BT_GATT_PERM_READ_AUTHEN`:
```
CONFIG_BT=y
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_SMP=y
CONFIG_BT_SIGNING=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DIS=y
CONFIG_BT_ATT_PREPARE_COUNT=5
CONFIG_BT_BAS=y
CONFIG_BT_HRS=y
CONFIG_BT_PRIVACY=y
CONFIG_BT_DEVICE_NAME="Zephyr Peripheral Sample Long Name"
CONFIG_BT_DEVICE_APPEARANCE=833
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_NAME_MAX=65

CONFIG_BT_KEYS_OVERWRITE_OLDEST=y
CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y

CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=2
CONFIG_BT_KEYS_OVERWRITE_OLDEST=y
CONFIG_BT_KEYS_SAVE_AGING_COUNTER_ON_PAIRING=y
CONFIG_BT_FIXED_PASSKEY=y
```

Steps to reproduce:
1. Connect and bond device A
2. Connect and bond device B
3. (Note that device A will be oldest)
4. Disconnect device B
5. Connect and bond device C -> this will result in device A being disconnected and it's bond being overwritten
6. Try to reconnect device A and the bond will have to be made again to access protected characteristics

**Expected behavior**
At step 5 above although device A's bond is the oldest it is in use so should not be overwritten and instead device B's bond should be overwritten

**Impact**
Annoyance for end user

### PR DESCRIPTION
**Pull request by nwsetec**
When the Bluetooth stack is configured for CONFIG_BT_MAX_CONN > 1
the oldest key might currently be in use.  Fix the logic to ensure the
oldest key overwritten is from the set of keys currently not in use.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/35999

Signed-off-by: Faisal Saleem <faisal.saleem@setec.com.au>
Signed-off-by: Nick Ward <nick.ward@setec.com.au>

### CODE REVIEW

File: subsys/bluetooth/host/keys.c [hunk 1]
```diff
@@ -37,6 +39,36 @@ static struct bt_keys key_pool[CONFIG_BT_MAX_PAIRED];
...
+#if (CONFIG_BT_MAX_CONN > 1)
+static bool bt_key_is_not_in_use(uint8_t id)
+{
+	struct bt_conn *conn;
+	struct bt_keys *key;
+	bool not_in_use = true;
+	int i;
+
+	for (i = 0; i < CONFIG_BT_MAX_CONN; i++) {
+		conn = bt_conn_lookup_index(i);
```
Comment (jhedberg) [inline subsys/bluetooth/host/keys.c:52]: I think it'd be cleaner to use `bt_conn_foreach()` here and pass the callback a pointer to the bool.

File: subsys/bluetooth/host/keys.c [hunk 2]
```diff
@@ -62,17 +94,32 @@ struct bt_keys *bt_keys_get_addr(uint8_t id, const bt_addr_le_t *addr)
...
+		for (i = 0; i < ARRAY_SIZE(key_pool); i++) {
 			struct bt_keys *current = &key_pool[i];
-
-			if (current->aging_counter < oldest->aging_counter) {
-				oldest = current;
+			bool key_not_in_use = true;
+
+#if (CONFIG_BT_MAX_CONN > 1)
+			key_not_in_use = bt_key_is_not_in_use(i);
+#endif
```
Comment (jhedberg) [inline subsys/bluetooth/host/keys.c:106]: I don't think there's any need for the `#if ...` stuff here.  Instead, make the implementation of `bt_key_is_not_in_use()` always available and have it return `true` if MAX_CONN < 2. Then the above just becomes:
```
bool key_not_in_use = bt_key_is_not_in_use();`
```

File: subsys/bluetooth/host/keys.c [hunk 3]
```diff
@@ -37,6 +39,36 @@ static struct bt_keys key_pool[CONFIG_BT_MAX_PAIRED];
...
 static struct bt_keys *last_keys_updated;
+
+#if (CONFIG_BT_MAX_CONN > 1)
+static bool bt_key_is_not_in_use(uint8_t id)
+{
+	struct bt_conn *conn;
+	struct bt_keys *key;
+	bool not_in_use = true;
+	int i;
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/keys.c:50]: To help with ridding the code of preprocessor directives, just remove the `#if (CONFIG_BT_MAX_CONN > 1)` on the top and put this in the beginning of `bt_key_is_not_in_use()`:
```
if (CONFIG_BT_MAX_CONN < 2) {
        return true;
}
```

File: subsys/bluetooth/host/keys.c [hunk 4]
```diff
@@ -37,6 +39,36 @@ static struct bt_keys key_pool[CONFIG_BT_MAX_PAIRED];
 #if IS_ENABLED(CONFIG_BT_KEYS_OVERWRITE_OLDEST)
 static uint32_t aging_counter_val;
 static struct bt_keys *last_keys_updated;
+
+#if (CONFIG_BT_MAX_CONN > 1)
+static bool bt_key_is_not_in_use(uint8_t id)
```
Comment (jhedberg) [inline subsys/bluetooth/host/keys.c:44]: I'd remove the `bt_` prefix since this is a private function (seeing calls to bt_* makes me think I can find the definition in some header file).

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/keys.c (hunk 2 above)
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Done

File: subsys/bluetooth/host/keys.c (hunk 3 above)
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Done

File: subsys/bluetooth/host/keys.c (hunk 4 above)
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Done

**Comment by nwsetec** [comment]
@jhedberg thanks for reviewing so quick.  I've added a commit on top of the previous commit (to remove ASAP) to show the changes when using the `bt_conn_foreach` but unfortunately it didn't get rid of the `#if ...` use as I had to re-introduce it when building with `CONFIG_BT_MAX_CONN==1`to fix the warning that the foreach callback wasn't used.  I also had to create a struct to pass in the key id and to get the 'in use' bool state out.  All up line count went up by 4.   See what you think, I'm happy to go either way.

**Comment by jhedberg** [comment]
I think the core of the problem is `bt_keys.aging_counter` which is build-time conditional. Otherwise we could remove most (possibly all) ifdefs by converting the code to use `if (IS_ENABLED(...)) {` kind of constructs.

**Comment by jhedberg** [comment]
Just a follow-up not on IS_ENABLED() - when using that it's perfectly fine to have non-ifdefed static functions or variables which never get used in the end (because some Kconfig option is enabled or disabled). The compiler won't warn and they'll get stripped out of the binary. But as I said, we can't fully convert the code to follow this if there are dependencies to some build-time conditional struct members.

**Comment by nwsetec** [comment]
@jhedberg ok `#if ... ` use now removed and lines of code from beginning of pull request dropped by 3.  I'll repeat testing when I get a chance.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/Kconfig [hunk 5]
```diff
@@ -421,12 +421,15 @@ config BT_OOB_DATA_FIXED
...
 config BT_KEYS_OVERWRITE_OLDEST
-	bool "Overwrite oldest keys with new ones if key storage is full"
+	bool "Overwrite the oldest key if key storage is full"
 	help
 	  With this option enabled, if a pairing attempt occurs and the key storage
 	  is full, then the oldest keys in storage will be removed to free space
 	  for the new pairing keys.
 
+	  Note if CONFIG_BT_MAX_CONN > 1 then the logic is: overwrite the oldest
+	  key from the set of keys that are not currently in use.
```
[the remark this answers is not in the document]
Comment (nwsetec) [reply subsys/bluetooth/host/Kconfig]: Very true.  I've condensed the description further, hopefully more succinct now.

File: subsys/bluetooth/host/keys.c [hunk 6]
```diff
@@ -62,17 +95,28 @@ struct bt_keys *bt_keys_get_addr(uint8_t id, const bt_addr_le_t *addr)
...
+		struct bt_keys *oldest = NULL;
 		bt_addr_le_t oldest_addr;
 
-		for (i = 1; i < ARRAY_SIZE(key_pool); i++) {
+		for (i = 0; i < ARRAY_SIZE(key_pool); i++) {
 			struct bt_keys *current = &key_pool[i];
-
-			if (current->aging_counter < oldest->aging_counter) {
-				oldest = current;
+			bool key_in_use = (CONFIG_BT_MAX_CONN < 2) || key_is_in_use(i);
```
[the remark this answers is not in the document]
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Thanks, fixed.

File: subsys/bluetooth/host/keys.c [hunk 7]
```diff
@@ -62,17 +95,28 @@ struct bt_keys *bt_keys_get_addr(uint8_t id, const bt_addr_le_t *addr)
...
+
+			if (!key_in_use) {
+				if (oldest == NULL) {
+					oldest = current;
+				} else if (current->aging_counter < oldest->aging_counter) {
+					oldest = current;
+				}
```
[the remark this answers is not in the document]
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Done

File: subsys/bluetooth/host/keys.c [hunk 8]
```diff
@@ -62,17 +95,28 @@ struct bt_keys *bt_keys_get_addr(uint8_t id, const bt_addr_le_t *addr)
...
 
-		for (i = 1; i < ARRAY_SIZE(key_pool); i++) {
+		for (i = 0; i < ARRAY_SIZE(key_pool); i++) {
 			struct bt_keys *current = &key_pool[i];
-
-			if (current->aging_counter < oldest->aging_counter) {
-				oldest = current;
+			bool key_in_use = (CONFIG_BT_MAX_CONN < 2) || key_is_in_use(i);
+
+			if (!key_in_use) {
```
[the remark this answers is not in the document]
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Done

File: subsys/bluetooth/host/keys.c [hunk 9]
```diff
@@ -37,6 +39,37 @@ static struct bt_keys key_pool[CONFIG_BT_MAX_PAIRED];
...
+
+struct key_data {
+	bool in_use;
+	uint8_t id;
+};
+
+static void find_key_in_use(struct bt_conn *conn, void *data)
+{
+	struct key_data *kdata = (struct key_data *)data;
+	struct bt_keys *key;
```
[the remark this answers is not in the document]
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c:51]: Hmm, I left it as, although I can't find a reference to back it up, I thought the coding guidelines were to declare local variables at the top of function definitions.

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/keys.c:51]: You can leave as is; afaik we don't have any code guidelines for this, but some of the static code analysis tools we are looking into would probably require this at some point in the future

File: subsys/bluetooth/host/keys.c [hunk 10]
```diff
@@ -37,6 +39,37 @@ static struct bt_keys key_pool[CONFIG_BT_MAX_PAIRED];
...
+
+	if (conn->state == BT_CONN_CONNECTED) {
+		key = bt_keys_find_addr(conn->id, bt_conn_get_dst(conn));
+		if (key != NULL) {
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/keys.c]: Right; I have somehow read this a loop :D

File: subsys/bluetooth/host/keys.c [hunk 11]
```diff
@@ -62,17 +96,28 @@ struct bt_keys *bt_keys_get_addr(uint8_t id, const bt_addr_le_t *addr)
...
 #if IS_ENABLED(CONFIG_BT_KEYS_OVERWRITE_OLDEST)
 	if (first_free_slot == ARRAY_SIZE(key_pool)) {
-		struct bt_keys *oldest = &key_pool[0];
+		struct bt_keys *oldest = NULL;
 		bt_addr_le_t oldest_addr;
 
-		for (i = 1; i < ARRAY_SIZE(key_pool); i++) {
+		for (i = 0; i < ARRAY_SIZE(key_pool); i++) {
 			struct bt_keys *current = &key_pool[i];
+			bool key_in_use = (CONFIG_BT_MAX_CONN > 1) && key_is_in_use(i);
```
Comment (Thalley) [inline subsys/bluetooth/host/keys.c:104]: Hmm, if `CONFIG_BT_MAX_CONN == 1` then no keys can be in use. 

It's a bit difficult for me to fully understand if there are any side effect here, because I guess that if no keys are in use, then we possibly overwrite the key for the current connection. Is that safe to do?

Comment (nwsetec) [reply subsys/bluetooth/host/keys.c:104]: The logic is if `CONFIG_BT_MAX_CONN == 1` then the bonding device is the only connected device which means all available key storage slots (1 or more) are considered not in use (by a connected device).  Note if there was a key slot previously used by the bonding device that would have been detected before the code above runs.  See:
https://github.com/zephyrproject-rtos/zephyr/blob/21ac7efc5c2629ca74d657bf52b0ed0a4ff62209/subsys/bluetooth/host/keys.c#L87-L89

Comment (Thalley) [reply subsys/bluetooth/host/keys.c:104]: Alright :)

**Review by Thalley — APPROVED** [review]

**Comment by nwsetec** [comment]
@jhedberg FYI I repeated my tests and the fix is still working.

File: subsys/bluetooth/host/keys.c [hunk 12]
```diff
@@ -37,6 +39,38 @@ static struct bt_keys key_pool[CONFIG_BT_MAX_PAIRED];
...
 static struct bt_keys *last_keys_updated;
+
+struct key_data {
+	bool in_use;
+	uint8_t id;
+};
+
+static void find_key_in_use(struct bt_conn *conn, void *data)
+{
+	struct key_data *kdata = (struct key_data *)data;
```
Comment (jhedberg) [inline subsys/bluetooth/host/keys.c:50]: No need for the explicit type cast

File: subsys/bluetooth/host/keys.c [hunk 13]
```diff
@@ -37,6 +39,38 @@ static struct bt_keys key_pool[CONFIG_BT_MAX_PAIRED];
...
+	struct bt_keys *key;
+
+	if (conn->state == BT_CONN_CONNECTED) {
+		key = bt_keys_find_addr(conn->id, bt_conn_get_dst(conn));
+		if (key == NULL) {
+			return;
+		}
```
Comment (jhedberg) [inline subsys/bluetooth/host/keys.c:57]: really minor, but to keep consistent with other Bluetooth code: add an empty line after } unless the next line is also }

File: subsys/bluetooth/host/keys.c [hunk 14]
```diff
@@ -37,6 +39,38 @@ static struct bt_keys key_pool[CONFIG_BT_MAX_PAIRED];
...
+			kdata->in_use = true;
+			BT_DBG("Connected device %s is using key_pool[%d]",
+			       bt_addr_le_str(bt_conn_get_dst(conn)), kdata->id);
+		}
+	}
+}
+
+static bool key_is_in_use(uint8_t id)
+{
+	struct key_data kdata = {false, id};
```
Comment (jhedberg) [inline subsys/bluetooth/host/keys.c:68]: minor: space after { and before }

File: subsys/bluetooth/host/keys.c [hunk 15]
```diff
@@ -62,17 +96,28 @@ struct bt_keys *bt_keys_get_addr(uint8_t id, const bt_addr_le_t *addr)
...
 
-			if (current->aging_counter < oldest->aging_counter) {
+			if ((oldest == NULL) || (current->aging_counter < oldest->aging_counter)) {
 				oldest = current;
 			}
 		}
 
+		if (oldest == NULL) {
+			BT_DBG("unable to create keys for %s", bt_addr_le_str(addr));
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/keys.c:117]: minor: remove this empty line

**Review by jhedberg — COMMENTED** [review]
@nwsetec looks generally fine to me, thanks! Just a couple of quite minor style issues to sort out and then I'd be ready to merge this.

File: subsys/bluetooth/host/keys.c (hunk 12 above)
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Done

File: subsys/bluetooth/host/keys.c (hunk 13 above)
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c:57]: Done

File: subsys/bluetooth/host/keys.c (hunk 14 above)
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Done

File: subsys/bluetooth/host/keys.c (hunk 15 above)
Comment (nwsetec) [reply subsys/bluetooth/host/keys.c]: Done

**Review by jhedberg — APPROVED** [review]
