### PR TITLE
Bluetooth: Mesh: Fix coverity reports

### LINKED ISSUE #84693: [Coverity CID: 487743] Overflowed constant in subsys/bluetooth/mesh/proxy_msg.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/proxy_msg.c

Category: Integer handling issues
Function: `bt_mesh_proxy_msg_send`
Component: Bluetooth
CID: [487743](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487743)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/proxy_msg.c#L186

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487743

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #84697: [Coverity CID: 487737] Overflowed integer argument in subsys/bluetooth/mesh/delayable_msg.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/delayable_msg.c

Category: Insecure data handling
Function: `push_msg_from_delayable_msgs`
Component: Bluetooth
CID: [487737](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487737)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/delayable_msg.c#L185

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487737

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #84702: [Coverity CID: 487722] Overflowed constant in subsys/bluetooth/mesh/shell/cfg.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/shell/cfg.c

Category: Integer handling issues
Function: `mod_pub_set`
Component: Bluetooth
CID: [487722](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487722)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/shell/cfg.c#L1582

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487722

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #84749: [Coverity CID: 487648] Overflowed constant in subsys/bluetooth/mesh/shell/cfg.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/shell/cfg.c

Category: Integer handling issues
Function: `cmd_relay`
Component: Bluetooth
CID: [487648](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487648)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/shell/cfg.c#L511

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487648

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #84759: [Coverity CID: 487624] Overflowed constant in subsys/bluetooth/mesh/shell/cfg.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/shell/cfg.c

Category: Integer handling issues
Function: `cmd_net_transmit`
Component: Bluetooth
CID: [487624](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487624)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/shell/cfg.c#L468

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=487624

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #84804: [Coverity CID: 393090] Overflowed constant in subsys/bluetooth/mesh/pb_adv.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/pb_adv.c

Category: Integer handling issues
Function: `gen_prov_start`
Component: Bluetooth
CID: [393090](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=393090)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/f0d0264c057255c60e91e422406f47a7b87d8a8a/subsys/bluetooth/mesh/pb_adv.c#L640

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=393090

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INTEGER_OVERFLOW). ([CWE-190](http://cwe.mitre.org/data/definitions/190.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by PavelVPV**
This PR fixes Coverity reports.

Fixes #84804
Fixes #84759
Fixes #84749
Fixes #84702
Fixes #84693
Fixes #84697

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by m-alperen-sener — APPROVED** [review]

**Review by alxelax — APPROVED** [review]

**Review by michalpiekos — APPROVED** [review]

File: subsys/bluetooth/mesh/pb_adv.c [hunk 1]
```diff
@@ -637,7 +637,14 @@ static void gen_prov_start(struct prov_rx *rx, struct net_buf_simple *buf)
 
 	link.rx.last_seg = START_LAST_SEG(rx->gpc);
 
+	/* This (BIT(0) is set) can happen if we received a Transaction Continuation PDU, before
+	 * receiving a Transaction Start PDU (see `gen_prov_cont`). Now we received the Transaction
+	 * Start PDU and we can extract the last segment number. Knowing this, we check if
+	 * previously received segment exceeds the last segment number. If so, we reject the
+	 * Transaction Start PDU.
+	 */
```
Comment (omkar3141) [inline subsys/bluetooth/mesh/pb_adv.c:645]: Not exactly related to this, but I think this seems to be incorrect?

`{ gen_prov_start, true, 3 },`, shouldn't this be `{ gen_prov_start, true, 5 },`?

Comment (PavelVPV) [reply subsys/bluetooth/mesh/pb_adv.c:645]: Not 5, but 4, because `min_len` exludes first octet. But, the Data field is checked inside `gen_prov_start` probably for logging, so this seems ok:
https://github.com/zephyrproject-rtos/zephyr/blob/55d3deb030bf10198b675fe6ce2effe738f9c01b/subsys/bluetooth/mesh/pb_adv.c#L611-L615
