### PR TITLE
Bluetooth: Deprecate adv auto-resume

### LINKED ISSUE #72567: Bluetooth: Advertising resume functionality is broken
**Describe the bug**

1. This feature only works when using legacy advertising
2. This feature will attempt to change the random address while a scanner/initiator is running

The Bluetooth specification says that (when using legacy advertising) it is forbidden to update the random address whilst another role is running. 
That means we can't start a scanner while an advertiser is running or the opposite.

With the resume feature, it is very probable that the host attempts to re-start advertising while the scanner is already running.

**Proposed change**

We should deprecate that feature.
It has also been the source of many race-condition bugs (finding PRs left as exercise to the reader).

With the addition of the `recycled` callback, that feature is now implementable by the application itself.
https://github.com/zephyrproject-rtos/zephyr/blob/e32c2ee2968599e893172a0221bab7d4bde3632b/include/zephyr/bluetooth/conn.h#L1003-L1016

**Additional context**

- https://github.com/zephyrproject-rtos/zephyr/pull/72418
- https://github.com/zephyrproject-rtos/zephyr/pull/72404

image

### PR DESCRIPTION
**Pull request by alwa-nordic**
The host-based adv auto-resume function has both a problematic implementation and disagreement in the community around how it should behave. See the issue linked resolved below for details.

This patch makes the deprecation visible to the user. The user will be better served by a auto-resume tailored their applications use case, based on more primitive host API like `conn_cb.recycled`, which has obvious behavior that is unlikely to change.

Resolves: https://github.com/zephyrproject-rtos/zephyr/issues/72567

### CODE REVIEW

**Comment by alwa-nordic** [comment]
Last push fixes compliance check:

> <p> EMBEDDED_FUNCTION_NAME: Prefer using '"%s...", __func__' to using 'bt_le_adv_start', this function's name, in a string

File: include/zephyr/bluetooth/bluetooth.h [hunk 1]
```diff
@@ -908,9 +926,15 @@ struct bt_le_per_adv_param {
...
-				       BT_GAP_ADV_FAST_INT_MAX_2, NULL)
+/**
+ * @deprecated It is now mandatory to use @ref BT_LE_ADV_OPT_ONE_TIME
+ * for connectable advertising. Please use @ref BT_LE_ADV_CONN_ONE_TIME
+ * instead.
+ */
+#define BT_LE_ADV_CONN                                                                             \
+	BT_LE_ADV_PARAM(BT_LE_ADV_OPT_CONNECTABLE, BT_GAP_ADV_FAST_INT_MIN_2,                      \
+			BT_GAP_ADV_FAST_INT_MAX_2, NULL)                                           \
+	__DEPRECATED_MACRO
```
Comment (Thalley) [inline include/zephyr/bluetooth/bluetooth.h:937]: So what is the plan here? 
Are we 
A) Deprecating this macro and enforcing the use of `BT_LE_ADV_CONN_ONE_TIME` forever, or
B) Deprecating this macro, enforcing `BT_LE_ADV_CONN_ONE_TIME`, and then deprecate `BT_LE_ADV_CONN_ONE_TIME` later again? 

I assume A, just wanted to make sure.

File: subsys/bluetooth/host/adv.c [hunk 2]
```diff
@@ -1363,6 +1363,13 @@ int bt_le_adv_start(const struct bt_le_adv_param *param,
 	struct bt_le_ext_adv *adv = adv_get_legacy();
 	int err;
 
+	if (!(param->options & BT_LE_ADV_OPT_ONE_TIME) &&
+	    (param->options & BT_LE_ADV_OPT_CONNECTABLE) && !param->peer) {
+		LOG_WRN("Deprecation warning: %s BT_LE_ADV_OPT_CONNECTABLE without "
+			"BT_LE_ADV_OPT_ONE_TIME",
+			__func__);
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:1370]: Do we need runtime warnings after buildtime warnings?

Comment (alwa-nordic) [reply subsys/bluetooth/host/adv.c:1370]: The runtime warning is for apps that don't use `BT_LE_ADV_CONN`, but use a custom `bt_le_adv_param`.

File: include/zephyr/bluetooth/bluetooth.h (hunk 1 above)
Comment (alwa-nordic) [reply include/zephyr/bluetooth/bluetooth.h:937]: This has not been decided. Both scenarios start with this PR as it is.

Comment (alwa-nordic) [reply include/zephyr/bluetooth/bluetooth.h:937]: I too would like to avoid breaking our users twice. :+1: Though I'm not too worried about simple renames and other stuff that can be automated by a search-replace or a migration script.

I'm for solution A, but it's actually for different reason: I'm not too worried about the above if the tool-chain or automated tests yell at you if you forget. So failing to compile when there is a semantic difference is desired.

Reusing `BT_LE_ADV_CONN` *ever* introduces the hazard of old code compiling just fine, and even running apparently just fine at first, except eventually discovering that reconnect does not work.

And the symptom of error in this case is just that nothing happens, far removed from the ideal of a self-describing actionable error message. This kind of very late feedback makes our users less confident in upgrading.

I realize now that removing the runtime warning ever will have the same downside. Maybe we should go for deprecating `BT_LE_ADV_OPT_CONNECTABLE`, like I said in https://github.com/zephyrproject-rtos/zephyr/pull/73395#discussion_r1617302003?

We could argue that our users have to "execute" the migration guides one-by-one. :wink: And the lack of API guarantees and verification from Zephyr means any serious application developer should trust-but-verify-tm and have automated test for their applications for all use-cases.

This is becoming an essay. Sorry for the long. I'll table this for BT WG discussion on Thursday.

Comment (Thalley) [reply include/zephyr/bluetooth/bluetooth.h:937]: You make some good points. It's arguably better that they get compile errors, rather than some hard-to-track issue if it still compiles and runs. 

In that regard it is better to completely remove the macro in the future.

File: subsys/bluetooth/host/adv.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/host/adv.c:1370]: Your arguments from https://github.com/zephyrproject-rtos/zephyr/pull/73395#discussion_r1617674980 w.r.t. 

> Reusing BT_LE_ADV_CONN ever introduces the hazard of old code compiling just fine, and even running apparently just fine at first, except eventually discovering that reconnect does not work.

Also applies here IMO. If we want compile-time checks, we need to deprecate the macro and add a new one. 

Ideally all deprecation of macros such as what we do here, needs to follow the steps in https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#introducing-breaking-api-changes and the architecture group may have some opinions as well.

File: include/zephyr/bluetooth/bluetooth.h (hunk 1 above)
Comment (jori-nordic) [reply include/zephyr/bluetooth/bluetooth.h:937]: I'd def be in favor of just removing the macro and deprecating the `CONNECTABLE` option in favor of `ONE_TIME`.

**Review by jori-nordic — DISMISSED** [review]

**Review by carlescufi — COMMENTED** [review]
Bluetooth WG meeting:

- Agreement to dreprecate `BT_LE_ADV_OPT_CONNECTABLE` and `BT_LE_ADV_OPT_ONE_TIME` and introduce  a new `BT_LE_ADV_OPT_CONN` which combines the two deprecated options into a single one

**Review by carlescufi — DISMISSED** [review]
Add an entry in the migration guide

File: include/zephyr/bluetooth/bluetooth.h [hunk 3]
```diff
@@ -514,6 +514,13 @@ enum {
 	/**
 	 * @brief Advertise as connectable.
 	 *
+	 * @deprecated Use @ref BT_LE_ADV_OPT_CONN instead.
```
Comment (Thalley) [inline include/zephyr/bluetooth/bluetooth.h:517]: This will only mark it as deprecated in documentation, right? It won't generate any build-time warnings. 

Can we apply `__deprecated` to the deprecated enum values similar to https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/data/json.h#L36-L39 ?

**Review by jhedberg — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]

File: doc/releases/migration-guide-3.7.rst [hunk 4]
```diff
@@ -476,6 +476,50 @@ Bluetooth Host
...
+  There is no replacement for :code:`BT_LE_ADV_OPT_CONN` without
+
+
+The application need to include the device name explicitly. One
+  way to do it is by adding the following to the advertising data or scan response data passed to
+  the host:
+
+  .. code-block:: c
+
+   BT_DATA(BT_DATA_NAME_COMPLETE, CONFIG_BT_DEVICE_NAME, sizeof(CONFIG_BT_DEVICE_NAME) - 1)
```
Comment (Thalley) [inline doc/releases/migration-guide-3.7.rst:519]: Some indentation seems off here

File: doc/releases/migration-guide-3.7.rst [hunk 5]
```diff
@@ -476,6 +476,50 @@ Bluetooth Host
...
+  * If nothing was noted, the migration is completed at this step.
+
+  * The rest of the guide explains
+    how to implement advertiser restarting in the application. The exact behavior of the
+    Host-automatic resumption differs between Zephyr versions and the Controller in use, so it's not
+    viable to fully characterize it here. Instead the application developer is expected to adapt the
+    sketch layed out here to reflect the applications needs.
+
+
+  There is no replacement for :code:`BT_LE_ADV_OPT_CONN` without
```
Comment (Thalley) [inline doc/releases/migration-guide-3.7.rst:510]: Without what?

**Review by Thalley — CHANGES_REQUESTED** [review]
The migration guide needs another round

**Review by jori-nordic — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

File: doc/releases/migration-guide-4.0.rst [hunk 6]
```diff
@@ -162,6 +162,68 @@ Bluetooth Classic
...
+    * :code:`BT_LE_ADV_CONN`
+
+   New symbols:
+    * :code:`BT_LE_ADV_OPT_CONN`
+    * :code:`BT_LE_ADV_CONN_FAST_1`
+    * :code:`BT_LE_ADV_CONN_FAST_2`
+
+   `BT_LE_ADV_OPT_CONNECTABLE` is a combined instruction to make the
+   advertiser connectable and to enable automatic resumption. To disable
+   the automatic resumption, use `BT_LE_ADV_OPT_CONN`.
```
Comment (Thalley) [inline doc/releases/migration-guide-4.0.rst:182]:
```suggestion
   :code:`BT_LE_ADV_OPT_CONNECTABLE` is a combined instruction to make the
   advertiser connectable and to enable automatic resumption. To disable
   the automatic resumption, use :code:`BT_LE_ADV_OPT_CONN`.
```

File: doc/releases/migration-guide-4.0.rst [hunk 7]
```diff
@@ -162,6 +162,68 @@ Bluetooth Classic
...
+
+   Extended Advertising API with shorthands
+   =====================================
+
+   Extended Advertising API `bt_le_ext_adv_*` implicitly assume
+   `BT_LE_ADV_OPT_ONE_TIME` and never automatically resume advertising.
```
Comment (Thalley) [inline doc/releases/migration-guide-4.0.rst:188]:
```suggestion
   Extended Advertising API :code:`bt_le_ext_adv_*` implicitly assume
   :code:`BT_LE_ADV_OPT_ONE_TIME` and never automatically resume advertising.
```

Comment (Thalley) [reply doc/releases/migration-guide-4.0.rst:188]: Pretty sure you either have to do 
```
:code:`bt_whatever`
```
or

```
``bt_whatever``
```

to properly mark things as code

Comment (Thalley) [reply doc/releases/migration-guide-4.0.rst:188]: This also applies for several other places further below

File: doc/releases/migration-guide-4.0.rst [hunk 8]
```diff
@@ -162,6 +162,68 @@ Bluetooth Classic
...
+
+   * Replace all
+     - :code:`bt_le_ext_adv_update_param(..., BT_LE_ADV_CONN)`
+     + :code:`bt_le_ext_adv_update_param(..., BT_LE_ADV_FAST_2)`
+
+   Extended Advertising API with custom params
+   ========================================
+
+   You may have uses of `BT_LE_ADV_OPT_CONNECTABLE` in assignments to a
+   `struct bt_le_adv_param`. If your struct is never passed to
```
Comment (Thalley) [inline doc/releases/migration-guide-4.0.rst:204]:
```suggestion
   :c:struct:`bt_le_adv_param`. If your struct is never passed to
```

File: doc/releases/migration-guide-4.0.rst [hunk 9]
```diff
@@ -162,6 +162,68 @@ Bluetooth Classic
...
+   `bt_le_adv_start`, you should:
```
Comment (Thalley) [inline doc/releases/migration-guide-4.0.rst:205]:
```suggestion
   :c:func:`bt_le_adv_start`, you should:
```

File: doc/releases/migration-guide-4.0.rst [hunk 10]
```diff
@@ -162,6 +162,68 @@ Bluetooth Classic
...
+
+    * replace `BT_LE_ADV_OPT_CONNECTABLE` with `BT_LE_ADV_OPT_CONN`.
+    * remove `BT_LE_ADV_OPT_ONE_TIME`.
+
+   Legacy Advertising API not using automatic resumption
+   =====================================================
+
+   Any calls to `bt_le_adv_start` that use the combination
```
Comment (Thalley) [inline doc/releases/migration-guide-4.0.rst:213]:
```suggestion
   Any calls to :c:func:`bt_le_adv_start` that use the combination
```

File: tests/bsim/bluetooth/host/l2cap/stress/src/main.c [hunk 11]
```diff
@@ -316,7 +311,7 @@ static void test_peripheral_main(void)
 
 	LOG_DBG("Peripheral Bluetooth initialized.");
 	LOG_DBG("Connectable advertising...");
-	err = bt_le_adv_start(BT_LE_ADV_CONN_OT, NULL, 0, NULL, 0);
+	err = bt_le_adv_start(BT_LE_ADV_CONN_FAST_1, NULL, 0, NULL, 0);
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/l2cap/stress/src/main.c:314]:
```suggestion
	err = bt_le_adv_start(BT_LE_ADV_CONN_FAST_2, NULL, 0, NULL, 0);
```

File: tests/bsim/bluetooth/host/misc/hfc/src/main.c [hunk 12]
```diff
@@ -106,18 +106,14 @@ static void device_found(const bt_addr_le_t *addr, int8_t rssi, uint8_t type,
...
-
 static struct bt_conn *connect_as_peripheral(void)
 {
 	int err;
 	struct bt_conn *conn;
 
 	UNSET_FLAG(is_connected);
 
-	err = bt_le_adv_start(ADV_PARAM_SINGLE, NULL, 0, NULL, 0);
+	err = bt_le_adv_start(BT_LE_ADV_CONN_FAST_1, NULL, 0, NULL, 0);
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/misc/hfc/src/main.c:116]:
```suggestion
	err = bt_le_adv_start(BT_LE_ADV_CONN_FAST_2, NULL, 0, NULL, 0);
```

File: include/zephyr/bluetooth/bluetooth.h [hunk 13]
```diff
@@ -729,6 +762,26 @@ enum {
...
+	 * @note To continue advertising after a connection is created,
+	 * the application should listen for the @ref conn_cb.connected
+	 * event and start the advertising set again. Note that the
+	 * advertiser cannot be started when all connection objects are
+	 * in use. In that case, defer starting the advertiser until
+	 * @ref conn_cb.recycled. To continue after a disconnection,
+	 * listen for @ref conn_cb.recycled.
+
+	 */
+	BT_LE_ADV_OPT_CONN = BIT(0) | BIT(1),
```
Comment (Thalley) [inline include/zephyr/bluetooth/bluetooth.h:784]: Would it make sense to move this further up in the enum, so that the values are ordered?

File: subsys/bluetooth/host/adv.c [hunk 14]
```diff
@@ -392,7 +392,7 @@ static bool valid_adv_ext_param(const struct bt_le_adv_param *param)
 	    BT_DEV_FEAT_LE_EXT_ADV(bt_dev.le.features)) {
 		if (param->peer &&
 		    !(param->options & BT_LE_ADV_OPT_EXT_ADV) &&
-		    !(param->options & BT_LE_ADV_OPT_CONNECTABLE)) {
+		    !(param->options & _BT_LE_ADV_OPT_CONNECTABLE)) {
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:395]: Should we reject all API calls with the internal bits set?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/adv.c (hunk 14 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/adv.c:395]: Not possible the way I define the values. `_BT_LE_ADV_OPT_CONNECTABLE` has the same value as `BT_LE_ADV_OPT_CONNECTABLE`.

File: doc/releases/migration-guide-4.0.rst (hunk 7 above)
Comment (alwa-nordic) [reply doc/releases/migration-guide-4.0.rst:188]: https://docs.zephyrproject.org/latest/contribute/documentation/guidelines.html#content-highlighting

Guidelines say <code>``</code>.

File: subsys/bluetooth/host/adv.c (hunk 14 above)
Comment (Thalley) [reply subsys/bluetooth/host/adv.c:395]: Ah, right. Not much we can do there for now then I guess

File: doc/releases/migration-guide-4.0.rst (hunk 7 above)
Comment (Thalley) [reply doc/releases/migration-guide-4.0.rst:188]: > two backquotes: ``text`` for inline code samples.

Does "inline code samples" imply references for specific values like above? 

Ping @kartben

Comment (alwa-nordic) [reply doc/releases/migration-guide-4.0.rst]: Latest push uses correct [C domain references](https://www.sphinx-doc.org/en/master/usage/domains/c.html#cross-referencing-c-constructs).

**Review by jhedberg — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]
Nice work - Looking forward to getting this feature removed completely

**Review by ubieda — DISMISSED** [review]

**Review by theob-pro — DISMISSED** [review]

**Comment by jhedberg** [comment]
Added the DNM flag for now, until we have a consensus on how to proceed with #77775 since that may have an impact on this API.

**Comment by jori-nordic** [comment]
@jhedberg isn't it kind of moot if the API in question is being removed?

We are determined to remove auto-resume. 
We still have the deprecation period to iron out the kinks.

**Comment by jhedberg** [comment]
> @jhedberg isn't it kind of moot if the API in question is being removed?
> 
> We are determined to remove auto-resume. We still have the deprecation period to iron out the kinks.

You're probably right. I just wanted to pull the handbrake a little, in case it would have emerged from the discussion in the other PR that we actually don't want to deprecate/remove this feature.

**Review by Thalley — DISMISSED** [review]

**Review by jori-nordic — DISMISSED** [review]

File: tests/bsim/bluetooth/host/l2cap/multilink_peripheral/src/dut.c [hunk 15]
```diff
@@ -251,7 +251,7 @@ static void start_advertising(void)
 
 	LOG_DBG("starting advertiser");
 
-	err = bt_le_adv_start(BT_LE_ADV_CONN_ONE_TIME, ad, ARRAY_SIZE(ad), NULL, 0);
+	err = bt_le_adv_start(BT_LE_ADV_CONN_FAST_2, ad, ARRAY_SIZE(ad), NULL, 0);
```
Comment (Thalley) [inline tests/bsim/bluetooth/host/l2cap/multilink_peripheral/src/dut.c:254]: In other cases you've replace `BT_LE_ADV_CONN_ONE_TIME` with `BT_LE_ADV_CONN_FAST_1` - Why `BT_LE_ADV_CONN_FAST_2` here?

Comment (alwa-nordic) [reply tests/bsim/bluetooth/host/l2cap/multilink_peripheral/src/dut.c:254]: I don't have any preference for one over the other. I'll switch them all to `BT_LE_ADV_CONN_FAST_1` for consistency.

Comment (alwa-nordic) [reply tests/bsim/bluetooth/host/l2cap/multilink_peripheral/src/dut.c]: `BT_LE_ADV_CONN_ONE_TIME` uses the timings of `BT_LE_ADV_CONN_FAST_2`. So replacing `BT_LE_ADV_CONN_ONE_TIME` with `BT_LE_ADV_CONN_FAST_2` would be the refactor with no change. OTOH, `BT_LE_ADV_CONN_FAST_1` will potentially connect faster. I doubt the choice in the tests was made consciously, so I think we can use the faster one.

**Review by theob-pro — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
