### PR TITLE
soc: nordic: common: dmm: Fix memory utilization

### LINKED ISSUE #74404: tests: drivers: uart and spi fails on nrf54h20 - ASSERTION FAIL heap size is too small
**Describe the bug**
The tests:
- tests/drivers/spi/spi_controller_peripheral/drivers.spi.spi_4MHz
- tests/drivers/spi/spi_controller_peripheral/drivers.spi.spi_8MHz
- tests/drivers/spi/spi_controller_peripheral/drivers.spi.spi_mode0
- tests/drivers/spi/spi_controller_peripheral/drivers.spi.spi_mode1
- tests/drivers/spi/spi_controller_peripheral/drivers.spi.spi_mode2
- tests/drivers/spi/spi_controller_peripheral/drivers.spi.spi_mode3
-  tests/drivers/uart/uart_async_api/drivers.uart.async_api
-  tests/drivers/uart/uart_mix_fifo_poll/drivers.uart.uart_mix_poll_fifo
- tests/drivers/uart/uart_mix_fifo_poll/drivers.uart.uart_mix_poll_fifo_with_ppi

Observed for
- nrf54h20dk/nrf54h20/cpurad

**To Reproduce**
1. have nrf54h20dk/nrf54h20/cpurad connected
2. go to your zephyr dir
3. call ./scripts/twister -T tests/drivers/spi -p nrf54h20dk/nrf54h20/cpurad --device-testing --device-serial /dev/ttyACM1 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
tests/drivers/spi/spi_controller_peripheral/drivers.spi.spi_4MHz
```
ASSERTION FAIL [bytes > heap_footer_bytes(bytes)] @ ../../../../../../../../../../zephyr/zephyr/lib/heap/heap.c:498
heap size is too small
E: r0/a1:  0x00000004  r1/a2:  0x000001f2  r2/a3:  0x00000000
E: r3/a4:  0x00000004 r12/ip:  0x00000001 r14/lr:  0x0e0671fd
E:  xpsr:  0x29000000
E: Faulting instruction address (r15/pc): 0x0e06fd0a
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x23000588 (main)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.5
 - Commit SHA or Version used: v3.6.0-6442-g9265c823131e

### PR DESCRIPTION
**Pull request by nordic-krch**
DMM was enforcing cache line alignment all memory regions, including those which were not cacheable. Fixing it by using memory attribute from the device tree to determine if alignment needs to be applied.

Because of that memory usage was significantly increased because even 1 byte buffers (e.g. for uart_poll_out) was consuming 32 bytes (cache line size).

Fixes #74404.

### CODE REVIEW

File: soc/nordic/common/dmm.h [hunk 1]
```diff
@@ -35,7 +47,6 @@ extern "C" {
 #define DMM_DEV_TO_REG(node_id)					\
 	COND_CODE_1(DT_NODE_HAS_PROP(node_id, memory_regions),	\
 		((void *)DT_REG_ADDR(DT_PHANDLE(node_id, memory_regions))), (NULL))
-
```
Comment (nika-nordic) [inline soc/nordic/common/dmm.h:38]: nit: should stay I guess

**Review by nika-nordic — DISMISSED** [review]

**Review by hubertmis — DISMISSED** [review]

**Comment by nordic-krch** [comment]
@nika-nordic @hubertmis can you take another look? I moved checking of `CONFIG_DCACHE` to `DMM_IS_REG_CACHEABLE` so that it returns 0 if dcache is disabled.

I've also added one more commit which enables DMM only for cpurad and cpuapp. Cpuppr is not using DMM.

**Review by hubertmis — APPROVED** [review]

**Review by masz-nordic — APPROVED** [review]

**Comment by aescolar** [comment]
@nordic-krch should this be merged for 3.7? (if so, could you set the milestone)
