### PR TITLE
include: add missing kernel.h for lorawan subsys

### LINKED ISSUE #51194: samples/subsys/lorawan building failed
**Describe the bug**
Error raised on  `west build -p -b nucleo_wl55jc samples/subsys/lorawan/class_a/

Please also mention any information which could help others to understand
the problem you're facing:
 - platform :  nucleo_wl55jc
 -  following  commit a6a4400b8621bc618c60561c5bdd90b2e8ce09e0

**To Reproduce**
1. west build -p -b nucleo_wl55jc samples/subsys/lorawan/class_a/
2. See error

**Impact**
Ci failure on  testcase samples/subsys/lorawan/class_a/

**Logs and console output**
```
./include/zephyr/drivers/lora.h:132:43: warning: 'struct k_poll_signal' declared inside parameter list will not be visible outside of this definition or declaration
  132 |                                    struct k_poll_signal *async);
      |                                           ^~~~~~~~~~~~~
./include/zephyr/drivers/lora.h:142:30: error: unknown type name 'k_timeout_t'
  142 |                              k_timeout_t timeout, int16_t *rssi, int8_t *snr);
      |                              ^~~~~~~~~~~
/./include/zephyr/drivers/lora.h:166:9: error: unknown type name 'lora_api_recv'
  166 |         lora_api_recv recv;
      |            ^~~~~~~~~~~~~

``` 

**Environment (please complete the following information):**
 - OS: ubuntu 
 - Toolchain Zephyr SDK 0.15.1
 - Commit SHA b219b5cba721b43a2c4fe71f5845f0abc852e7f6

### PR DESCRIPTION
**Pull request by FRASTM**
Header lora.h and lorawan.c files make use of types defined in kernel.h :  including it to avoid undefined struct error

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/51194

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Review by stephanosio — DISMISSED** [review]

**Review by gmarull — DISMISSED** [review]

File: include/zephyr/drivers/lora.h [hunk 1]
```diff
@@ -15,6 +15,7 @@
  * @{
  */
 
+#include <zephyr/kernel.h>
 #include <zephyr/types.h>
```
Comment (JordanYates) [inline include/zephyr/drivers/lora.h:19]: `zephyr/types.h` could be removed with the addition of `zephyr/kernel.h`.

**Review by JordanYates — DISMISSED** [review]

File: include/zephyr/drivers/lora.h (hunk 1 above)
Comment (FRASTM) [reply include/zephyr/drivers/lora.h]: yes, removed

File: include/zephyr/drivers/lora.h [hunk 2]
```diff
@@ -15,7 +15,7 @@
  * @{
  */
 
-#include <zephyr/types.h>
```
Comment (gmarull) [inline include/zephyr/drivers/lora.h:18]: please include `<stdint.h>`

**Review by gmarull — CHANGES_REQUESTED** [review]

File: include/zephyr/drivers/lora.h (hunk 2 above)
Comment (JordanYates) [reply include/zephyr/drivers/lora.h:18]: Is this really required when it comes in with kernel.h?

Comment (gmarull) [reply include/zephyr/drivers/lora.h:18]: We're including `kernel.h` here for `k_poll_signal`/`k_timeout_t`. The fact that `kernel.h` includes `stdint.h` is an implementation detail. In fact, it doesn't include it directly but via `kernel_includes.h` -> `types.h`. Unfortunately, we expose many internals because we need static allocation. If Kernel devices one day to drop usage of `stdint.h`, `lora.h` users be in trouble.

Comment (gmarull) [reply include/zephyr/drivers/lora.h:18]: https://google.github.io/styleguide/cppguide.html#Include_What_You_Use
https://google.github.io/styleguide/cppguide.html#Self_contained_Headers

Comment (FRASTM) [reply include/zephyr/drivers/lora.h:18]: with `#include <stdint.h>` in the /include/zephyr/drivers/lora.h

**Review by gmarull — DISMISSED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by mniestroj — DISMISSED** [review]

**Review by martinjaeger — DISMISSED** [review]

**Review by Mani-Sadhasivam — DISMISSED** [review]

**Review by stephanosio — DISMISSED** [review]

**Comment by stephanosio** [comment]
CI was stuck. Rebased to retrigger it.

**Review by martinjaeger — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
