### PR TITLE
wifi: driver: esp32: fix reconnection issue

### LINKED ISSUE #33843: ESP32 example does not connect to WiFi
**Describe the bug**
When flashing the ESP32 example the log gets stuck and only returns `<err> net_arp: Gateway not set for iface 0x3ffb0110` on ESP32-WROOM-32

**To Reproduce**
in the samples/board/esp32/wifi_station example
Configure SSID and password
Run
`west build -p always -b esp32`
Run and check log
`west flash;minicom`

**Expected behavior**
ESP32 shoud connect to router. Below you see the ESP32 succeeding to connect, which sometimes happens, but most of the time it fails to connect.

```
inf> esp_event: WIFI_EVENT_STA_START                                                                                                                                   
I (2239) wifi:new:<11,2>, old:<1,1>, ap:<255,255>, sta:<11,2>, prof:1                                                                                                                      
I (2887) wifi:state: init -> auth (b0)                                                                                                                                                     
I (2894) wifi:state: auth -> assoc (0)                                                                                                                                                     
I (2902) wifi:state: assoc -> run (10)                                                                                                                                                     
I (3001) wifi:connected with Router 66, aid = 5, channel 11, 40D, bssid = aa:bb:cc:dd:ee:ff                                                                                                
I (3002) wifi:security: WPA2-PSK, phy: bgn, rssi: -77                                                                                                                                      
I (3003) wifi:pm start, type: 1                                                                                                                                                            
                                                                                                                                                                                           
I (3040) wifi:AP's beacon interval = 102400 us, DTIM period = 1                                                                                                                            
[00:00:03.007,000] <inf> esp_event: WIFI_EVENT_STA_CONNECTED                                                                                                                               
[00:00:05.910,000] <err> net_arp: Gateway not set for iface 0x3ffb0110                                                                                                                     
[00:00:08.879,000] <err> net_arp: Gateway not set for iface 0x3ffb0110                                                                                                                     
[00:00:09.392,000] <err> net_arp: Gateway not set for iface 0x3ffb0110                                                                                                                     
[00:00:11.952,000] <err> net_arp: Gateway not set for iface 0x3ffb0110                                                                                                                     
[00:00:17.380,000] <inf> net_dhcpv4: Received: 192.168.1.217                                                                                                                               
[00:00:17.380,000] <inf> esp32_wifi_sta: Your address: 192.168.1.217                                                                                                                       
[00:00:17.380,000] <inf> esp32_wifi_sta: Lease time: 86400 seconds                                                                                                                         
[00:00:17.380,000] <inf> esp32_wifi_sta: Subnet: 255.255.255.0                                                                                                                             
[00:00:17.380,000] <inf> esp32_wifi_sta: Router: 192.168.1.1
```

**Impact**
showstopper

**Logs and console output**
```
I (724) wifi:wifi driver task: 3ffb1ef0, prio:2, stack:3584, core=0                                                                                                                      
I (725) wifi:wifi firmware version: 1865b55                                                                                                                                                
I (725) wifi:wifi certification version: v7.0                                                                                                                                              
I (727) wifi:config NVS flash: disabled                                                                                                                                                    
I (730) wifi:config nano formating: disabled                                                                                                                                               
I (734) wifi:Init data frame dynamic rx buffer num: 32                                                                                                                                     
I (739) wifi:Init management frame dynamic rx buffer num: 32                                                                                                                               
I (744) wifi:Init management short buffer num: 32                                                                                                                                          
I (749) wifi:Init dynamic tx buffer num: 32                                                                                                                                                
I (753) wifi:Init static rx buffer size: 1600                                                                                                                                              
I (757) wifi:Init static rx buffer num: 10                                                                                                                                                 
I (761) wifi:Init dynamic rx buffer num: 32                                                                                                                                                
phy_version: 4500, 0cd6843, Sep 17 2020, 15:37:07, 0, 2                                                                                                                                    
I (890) wifi:mode : softAP (3c:61:05:30:01:89)                                                                                                                                             
I (891) wifi:Total power save buffer number: 16                                                                                                                                            
I (891) wifi:Init max length of beacon: 752/752                                                                                                                                            
I (896) wifi:Init max length of beacon: 752/752                                                                                                                                            
*** Booting Zephyr OS build zephyr-v2.5.0-1540-g63ca48a7a9b8  ***                                                                                                                          
I (906) wifi:mode : sta (3c:61:05:30:01:88)                                                                                                                                                
[00:00:00.911,000] <inf> esp_event: WIFI_EVENT_STA_START                                                                                                                                   
I (2238) wifi:new:<11,2>, old:<1,1>, ap:<255,255>, sta:<11,2>, prof:1                                                                                                                      
I (2885) wifi:state: init -> auth (b0)                                                                                                                                                     
I (2890) wifi:state: auth -> assoc (0)                                                                                                                                                     
I (2898) wifi:state: assoc -> run (10)                                                                                                                                                     
I (3027) wifi:connected with Router 66, aid = 5, channel 11, 40D, bssid = aa:bb:cc:dd:ee:ff                                                                                                
I (3027) wifi:security: WPA2-PSK, phy: bgn, rssi: -77                                                                                                                                      
I (3029) wifi:pm start, type: 1                                                                                                                                                            
                                                                                                                                                                                           
I (3082) wifi:AP's beacon interval = 102400 us, DTIM period = 1                                                                                                                            
[00:00:03.032,000] <inf> esp_event: WIFI_EVENT_STA_CONNECTED                                                                                                                               
[00:00:05.849,000] <err> net_arp: Gateway not set for iface 0x3ffb0110                                                                                                                     
[00:00:07.385,000] <err> net_arp: Gateway not set for iface 0x3ffb0110                                                                                                                     
[00:00:08.921,000] <err> net_arp: Gateway not set for iface 0x3ffb0110                                                                                                                     
...                                                                                                           
[00:03:42.330,000] <err> net_arp: Gateway not set for iface 0x3ffb0110
```

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Toolchain: espressif (esp-2020r3-8.4.0/xtensa-esp32-elf)
 - Commit: Zephyr version: 2.5.99


**Additional context**
I could not find any info on the error "gatway not set for iface", but I believe this error get trown by `iface = net_if_get_default();`

### PR DESCRIPTION
**Pull request by sylvioalves**
Device won't reconnect automatically even if
AP station is available. This fix adds the carrier event, indicating
that network is present again enabling DHCP bound event.
Also, internal wifi event callback  was added into wifi driver to enable proper
event handling.

Fixes #33843

### CODE REVIEW

File: drivers/wifi/esp32/src/esp_wifi_drv.c [hunk 1]
```diff
@@ -41,6 +41,24 @@ struct esp32_wifi_runtime {
 #endif
 };
 
+static void esp_wifi_event_task(void);
+
+K_MSGQ_DEFINE(esp_wifi_msgq, sizeof(system_event_t), 10, 4);
+K_THREAD_DEFINE(esp_wifi_event_tid, CONFIG_ESP32_WIFI_EVENT_TASK_STACK_SIZE,
+				esp_wifi_event_task, NULL, NULL, NULL,
+				CONFIG_ESP32_WIFI_EVENT_TASK_PRIO, 0, 0);
```
Comment (jukkar) [inline drivers/wifi/esp32/src/esp_wifi_drv.c:49]: Indentation is wrong (your tab size is probably not 8)

**Review by jukkar — APPROVED** [review]
LGTM, minor nit about the indentation. Was this meant to be applied to 2.6?

**Comment by sylvioalves** [comment]
> LGTM, minor nit about the indentation. Was this meant to be applied to 2.6?

If there is room for that, yes.

File: drivers/wifi/esp32/src/esp_wifi_drv.c [hunk 2]
```diff
@@ -92,18 +109,37 @@ static esp_err_t eth_esp32_rx(void *buffer, uint16_t len, void *eb)
...
-		net_if_up(esp32_wifi_iface);
-	} else {
-		net_if_down(esp32_wifi_iface);
+	int32_t event_id;
+
+	while (1) {
+		k_msgq_get(&esp_wifi_msgq, &event_id, K_FOREVER);
+
+		switch (event_id) {
+		case ESP32_WIFI_EVENT_STA_START:
```
Comment (mniestroj) [inline drivers/wifi/esp32/src/esp_wifi_drv.c:120]: `ESP32_WIFI_EVENT_STA_START` is introduced in subsequent commit, right? Seems that it breaks bisectability then.

Comment (sylvioalves) [reply drivers/wifi/esp32/src/esp_wifi_drv.c:120]: @mniestroj I squash the commits in other to avoid that.

**Review by mniestroj — APPROVED** [review]
