### PR TITLE
drivers: flash: sam0: Resolve write issues in the first row

### LINKED ISSUE #52309: SAM0 flash driver with page emulated enabled will not write data at 0 block
**Describe the bug**
I tried to port my program which updates bootloader from main program.
I discovered that program will not update in first page (for example offset 0-128)

Updates doesn't happen because code assumes that nobody will not write any data in first flash page.

**To Reproduce**
1. Use any SAM0 board for example C21N Xpro
2. Make program which changes flash in first page - for example 0 offset
3. Discover that nothing changes in flash

**Expected behavior**
Flash operation should work for all block/page even in 0 offset.

**Impact**
Flash driver

**Environment (please complete the following information):**
 - Any SAM0 board

### PR DESCRIPTION
**Pull request by attie-argentum**
Previously, while writing close to the start of flash (i.e: in the first row), the write was never committed - due to zero being used as the "empty buffer" marker.

This patch also incorporates some performance improvements, as well as observing any errors reported by `flash_sam0_commit()`.

Fixes #52309
Supersedes #51976

### CODE REVIEW

File: drivers/flash/flash_sam0.c [hunk 1]
```diff
@@ -244,25 +236,30 @@ static int flash_sam0_write(const struct device *dev, off_t offset,
 		return err;
 	}
 
+	if (len == 0) {
+		return 0;
+	}
+
```
Comment (Laczen) [inline drivers/flash/flash_sam0.c:242]: The `len == 0` check should not be required and gracefully handled by the writing routine. These checks are polluting the code and are a bad idea:
1. Trying to return quickly on a condition that should not appear is adding a comparison to all real writes,
2. Handling the write of `len == 0` as a normal write could enable detection that there is something wrong with the interface without doing a real write.

Comment (attie-argentum) [reply drivers/flash/flash_sam0.c:242]: I'd suggest that this _is_ the "_graceful_" handling of a zero-length write...

> Trying to return quickly on a condition that should not appear is adding a comparison to all real writes,

Its impact is incredibly minimal... but if others agree, I'll remove it.
I think the sensible alternative to an early return is for **_two_** guards - one around each `flash_sam0_write_protection()`.

> Handling the write of `len == 0` as a normal write could enable detection that there is something wrong with the interface without doing a real write.

You can't get much closer to the lower level calls than this - `flash_sam0_commit()` won't be called with `len == 0` anyway... and as above, it would be sensible to add more guards.

Comment (Laczen) [reply drivers/flash/flash_sam0.c:242]: @attie-argentum, what I mean by graceful handling is that whatever follows is not influenced by this check (and I think it is already handled, nothing will happen if the line is removed). There shouldn't be an "early return", why should there be, it is no error condition.

An extra guard is also not required, if the flash_sam0_write_protection would fail for a write of 0 this is interesting knowledge that could be usefull. It would allow using a write of zero length to verify if it can write. The same holds for trying to write outside of the region, it will return an error message.

Comment (attie-argentum) [reply drivers/flash/flash_sam0.c:242]: I'm not going to argue the point too hard - I'll remove the check if needs be...

I suppose I prefer to protect the hardware from bad users - i.e: the unnecessary "_unprotect_" &rarr; "_re-protect_" process that is incurred by a zero-length write, which would be detrimental to the device's lifespan if it's over-used...

If you're trying to write, why not just try to write? A zero-length write only checks that the start is in-range, not the whole target region, so it's of limited use (but `flash_sam0_valid_range()` is still called in this case).

The docs don't mention anything about zero-length writes ([link](https://docs.zephyrproject.org/3.2.0/hardware/peripherals/flash.html#c.flash_write)), and in this mode (with `SOC_FLASH_SAM0_EMULATE_BYTE_PAGES` defined), we're already doing a lot of hand-holding for the user...

In fact, other drives implement this check too! 🙃

https://github.com/zephyrproject-rtos/zephyr/blob/e5efa3dfffd8d3eba0ae4bb580c535dadacfc7f9/drivers/flash/flash_sam.c#L180-L182

https://github.com/zephyrproject-rtos/zephyr/blob/e5efa3dfffd8d3eba0ae4bb580c535dadacfc7f9/drivers/flash/flash_stm32.c#L220-L222

https://github.com/zephyrproject-rtos/zephyr/blob/e5efa3dfffd8d3eba0ae4bb580c535dadacfc7f9/drivers/flash/flash_gd32.c#L58-L60

Comment (Laczen) [reply drivers/flash/flash_sam0.c:242]: > I'm not going to argue the point too hard - I'll remove the check if needs be...
> 

Neither am I. 😀 

> I suppose I prefer to protect the hardware from bad users - i.e: the unnecessary "_unprotect_" → "_re-protect_" process that is incurred by a zero-length write, which would be detrimental to the device's lifespan if it's over-used...
>

That is a good reason, and should be the only reason to do this.
 
> In fact, other drives implement this check too! 🙃

I know, but this shouldn't stop you from trying to do better. 😀

Comment (attie-argentum) [reply drivers/flash/flash_sam0.c:242]: > but this shouldn't stop you from trying to do better

Now there's a controversial statement... I thought I was trying to do better 😜

... I'll let others chip in on the `len == 0` test, I hope that's okay.

**Review by Laczen — APPROVED** [review]

**Comment by Laczen** [comment]
@attie-argentum, you can forget about my remark over `len ==0`, it is exactly at the right place in code.

**Review by de-nordic — APPROVED** [review]

**Comment by carlescufi** [comment]
@nandojve can you please take a look?

**Review by nandojve — APPROVED** [review]
