### PR TITLE
sys: device_mmio: Add device_unmap

### LINKED ISSUE #103576: Virtual memory address leak using `devmem dump` shell command with `CONFIG_MMU=y`
### Describe the bug

When running a `devmem dump` shell command on a platform with `CONFIG_MMU` enabled, this calls `device_map` to remap a physical memory to a virtual one. However this is never unmapped.

https://github.com/zephyrproject-rtos/zephyr/blob/53efd4818c134b18dac432bacf0072d7f29b83f1/subsys/shell/modules/devmem_service.c#L43-L47

### Regression

- [ ] This is a regression.

### Steps to reproduce

```shell
$ west build -p -b qemu_cortex_a53 samples/subsys/shell/shell_module -t run

uart:~$ devmem dump -a 0 -s 100
Mapped 0x0 to 0x407fe000

407FE000: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........|
407FE010: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........|
407FE020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........|
407FE030: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........|
407FE040: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........|
407FE050: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |........ ........|
407FE060: 00 00 00 00                                      |....             |
```

### Relevant log output

```shell
Mapped 0x0 to 0x407fe000
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: Ubuntu 24.04
- Toolchain: Zephyr SDK 0.17.4
- Commit SHA: `main` on 53efd4818c134b18dac432bacf0072d7f29b83f1

### Additional Context

It would be desirable to have a `device_unmap` counterpart.

### PR DESCRIPTION
**Pull request by pdgendt**
Add a function that unmaps virtual memory obtained from `device_map`.

Update test and shell command that call into `device_map`.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/103576

### CODE REVIEW

File: include/zephyr/sys/device_mmio.h [hunk 1]
```diff
@@ -113,6 +113,25 @@ static inline void device_map(mm_reg_t *virt_addr, uintptr_t phys_addr,
...
+/**
+ * Un-set linear address for device MMIO access
+ *
+ * If the MMU is enabled, mappings can be removed from the page tables.
+ *
+ * @param virt_addr Linear address obtained from @ref device_map
+ * @param size Size of the MMIO region
+ */
+__boot_func
+static inline void device_unmap(mm_reg_t virt_addr, size_t size)
```
Comment (cfriedt) [inline include/zephyr/sys/device_mmio.h:126]: Nice - yeah, I was looking for this before and was surprised to not find it.

**Review by cfriedt — APPROVED** [review]
LGTM

**Review by ceolin — APPROVED** [review]

**Comment by dcpleung** [comment]
Just FYI...

IIRC, the original idea not to have an unmap function is simply that Zephyr does not have a mechanism to de-init a device or unload a driver.

**Review by dcpleung — APPROVED** [review]
