### PR TITLE
shell: fix possible negative indexing

### LINKED ISSUE #60808: shell_ops: access cmd_buf with index -1
Describe the bug
When we input Ctrl+W as the first character in a new command line, we may use -1 as the index to access cmd_buf[]
in [main/subsys/shell/shell_ops.c line 164](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/shell/shell_ops.c#L164C2-L164C60)

void z_shell_op_word_remove(const struct shell *sh)
{
	char *str = &sh->ctx->cmd_buff[sh->ctx->cmd_buff_pos - 1];
	char *str_start = &sh->ctx->cmd_buff[0];
	uint16_t chars_to_delete;

	/* Line must not be empty and cursor must not be at 0 to continue. */
	if ((sh->ctx->cmd_buff_len == 0) ||
	    (sh->ctx->cmd_buff_pos == 0)) {
		return;

Note:
case SHELL_VT100_ASCII_CTRL_W: /* CTRL + W */
sh->ctx->cmd_buff_pos will be 0 here, and result in str = &sh->ctx->cmd_buff[- 1];

Suggest str should be assigned after sh->ctx->cmd_buff_len is checked.

Please also mention any information which could help others to understand
the problem you're facing:

If ubsan compiler option is enabled, press Ctrl+W will result in error

What target platform are you using?
qemu_cortex_a53 . But we think the issue is for all platform.
What have you tried to diagnose or workaround this issue?
assign str after sh->ctx->cmd_buff_len is checked.

Expected behavior
Do not use -1 as the index when accessing cmd_buff in main/subsys/shell/shell_ops.c

### PR DESCRIPTION
**Pull request by jakub-uC**
Fixes #60808

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

File: subsys/shell/shell_ops.c [hunk 1]
```diff
@@ -161,16 +161,16 @@ void z_shell_op_cursor_word_move(const struct shell *sh, int16_t val)
...
-
 	/* Line must not be empty and cursor must not be at 0 to continue. */
 	if ((sh->ctx->cmd_buff_len == 0) ||
 	    (sh->ctx->cmd_buff_pos == 0)) {
 		return;
 	}
 
+	char *str = &sh->ctx->cmd_buff[sh->ctx->cmd_buff_pos - 1];
+	char *str_start = &sh->ctx->cmd_buff[0];
+	uint16_t chars_to_delete;
```
Comment (fabiobaltieri) [inline subsys/shell/shell_ops.c:172]: Is it ok to declare these mid way through the function outside of any control block? Can't recall if the coding style mention it but I don't see it done anywhere else in this file.
