### PR TITLE
libc: minimal: Implement abort().

### LINKED ISSUE #29541: CONFIG_THREAD_LOCAL_STORAGE=y build fails with ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb is one of the supported toolchains to build Zephyr (for ARM architecture). After https://github.com/zephyrproject-rtos/zephyr/pull/28982 was merged, and with CONFIG_THREAD_LOCAL_STORAGE enabled (which it is, for one sanitycheck configuration of tests/kernel/common), the build fails with:

```
[ 87%] Linking C executable app_smem_unaligned_prebuilt.elf
/home/buildslave/srv/toolchain/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: /home/buildslave/srv/toolchain/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7e-m/nofp/libgcc.a(emutls.o): in function `emutls_alloc':
emutls.c:(.text+0x5a): undefined reference to `abort'
/home/buildslave/srv/toolchain/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: /home/buildslave/srv/toolchain/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7e-m/nofp/libgcc.a(emutls.o): in function `__emutls_get_address':
emutls.c:(.text+0x7a): undefined reference to `abort'
collect2: error: ld returned 1 exit status
make[2]: *** [zephyr/app_smem_unaligned_prebuilt.elf] Error 1
make[1]: *** [zephyr/CMakeFiles/app_smem_unaligned_prebuilt.dir/all] Error 2
make: *** [all] Error 2

INFO    - /home/buildslave/srv/zephyr/master/gnuarmemb/frdm_k64f/frdm_k64f/tests/kernel/common/kernel.common.tls/build.log
```

Full build log: https://ci.linaro.org/job/zephyr-upstream/PLATFORM=frdm_k64f,ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb,label=docker-xenial-amd64-13/5680/console

### PR DESCRIPTION
**Pull request by pfalcon**
abort() is an important runtime function, oftentimes used to signal
abnormal execution conditions in generic applications. Worse, they
may be used under such circumstances in e.g. compiler support
libraries, in which case lack of implementation of this function
will lead to link error.

Fixes: #29541

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
abort() is documented (e.g. https://pubs.opengroup.org/onlinepubs/9699919799/functions/abort.html) as "generate an abnormal process abort". Note *process*, not *thread*. That's for this implementation, I chose to call k_fatal_halt(). The reason passed to it, K_ERR_KERNEL_PANIC, is however not faithful, it would be better to have K_ERR_APP_PANIC or K_ERR_APP_ABORT.

Example in action, using qemu_x86:

```
[QEMU] CPU: qemu32,+nx,+pae
SeaBIOS (version rel-1.12.1-0-ga5cab58-dirty-20200625_115407-9426dddc0a1f-zephyr
)
Booting from ROM..***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build zephyr-v2.4.0-984-g660ad9791bd0  (delayed boot 500ms) ***
abort()
zephyr/CMakeFiles/run.dir/build.make:57: recipe for target 'zephyr/CMakeFiles/run' failed
``` 

i.e. QEMU even auto-quits. Ideally, I'd expect a register/stack trace, as dumped in other cases, but apparently `k_fatal_halt(K_ERR_KERNEL_PANIC)` doesn't do it (or just sample config doesn't enable it, I quick-patched tests/kernel/common for test).

**Review by tyrantlizard77 — DISMISSED** [review]

File: lib/libc/minimal/source/stdlib/abort.c [hunk 1]
```diff
@@ -0,0 +1,14 @@
+/*
+ * Copyright (c) 2020 Linaro Limited
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <stdlib.h>
```
Comment (nashif) [inline lib/libc/minimal/source/stdlib/abort.c:7]: shouldn't this be declared in stdlib.h (./lib/libc/minimal/include/stdlib.h)

**Comment by andrewboie** [comment]
> I'd expect a register/stack trace, as dumped in other cases, but apparently

Use `k_panic()` instead.

File: lib/libc/minimal/source/stdlib/abort.c (hunk 1 above)
Comment (pfalcon) [reply lib/libc/minimal/source/stdlib/abort.c:7]: > shouldn't this be declared in stdlib.h

Ack, fixed.

**Comment by pfalcon** [comment]
> Use k_panic() instead.

Done.

**Review by nashif — APPROVED** [review]

**Review by galak — APPROVED** [review]
