### PR TITLE
Bluetooth: Host: direction: Fixing the bug to support 1us slot

### LINKED ISSUE #37305: Bluetooth Direction Finding Support of "AoA RX 1us"
**Describe the bug**
By running the "bluetooth direction finding example" in "AoA RX mode" as you can find in this link:
https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/direction_finding_connectionless_rx

Two different slot duration can be chosen. 2 micro second (us) and 1 micro second (us). By default it is set to 2 us and works fine, but when it has been set to 1 us, it returns "EINVAL" error. To change the default value (2us) to 1us, this line should be changed to 0x1:
https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/direction_finding_connectionless_rx/src/main.c#L247

The error is generated when it  tries to validate the arguments at this line:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/direction.c#L224

The above line return false when consequently is expanded to the below code, using the defined macros:
`((df_ant_info.switch_sample_rates) & BIT((BT_HCI_LE_1US_AOA_RX)))`  

The `BT_HCI_LE_1US_AOA_RX` itself is defined as `BIT(2)` as you can find here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/bluetooth/hci.h#L1614

So this "bit shift operation" has executed two times and is the source of the bug.

**To Reproduce**
Navigate to the "direction_finding_connectionless_rx" project and build it.
1. cd zephyr/samples/bluetooth/direction_finding_connectionless_rx/
2. Change the slot duration from 0x2 to 0x1: https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/direction_finding_connectionless_rx/src/main.c#L247
2. west build -b nrf52833dk_nrf52833
3. west flash
In addition to the receiver, a transmitter is needed too. Navigate to "direction_finding_connectionless_tx" project, build and flash it into another device.
1. cd zephyr/samples/bluetooth/direction_finding_connectionless_tx/
2. west build -b nrf52833dk_nrf52833
3. west flash

By opening a terminal to the receiver device, you will see the error as described in "Logs and console output" section.

**Expected behavior**
Enabling of receiving CTE should return without any error.

**Impact**
It is not possible to use the CTE based direction finding with 1us slots. Both 1us and 2us slots are defined and described by the Bluetooth SIG.

**Logs and console output**
Open a terminal connection to the receiver device, by rebooting the device, you will see this log which shows the program has started successfully:
`*** Booting Zephyr OS build v2.6.0-rc1-ncs1-3-g0944459b5b62  ***
Starting Connectionless Locator Demo
Bluetooth initialization...success
Scan callbacks register...success.
Periodic Advertising callbacks register...success.
Start scanning...success
`

Now turn on the transmitter, which send Bluetooth advertisement data to the receiver, at this time you will see the error:
`...
Waiting for periodic sync...
success. Periodic sync established.
Enable receiving of CTE...
failed (err -22)
Scan disable...Success.
...`

**Environment (please complete the following information):**
- OS: Linux
- Toolchain: nRF Connect SDK
- v2.6.0

**Additional context**

### PR DESCRIPTION
**Pull request by saleh-unikie**
There was an issue with receiving CTE packets when the time
slot has changed from 2us to 1us. After receiving the packets
when it tries to enable receiving of CTE, the validator
returns EINVAL error.

Source of the problem is "validate_cte_rx_params" function,
it calls DF_AOA_RX_1US_SUPPORT(df_ant_info.switch_sample_rates)
which is expanded to:
((df_ant_info.switch_sample_rates) & BIT((BT_HCI_LE_1US_AOA_RX)))

And due to definition of BT_HCI_LE_1US_AOA_RX in hci.h it will be:
((df_ant_info.switch_sample_rates) & BIT(BIT(2)))

So the BIT operation has executed two times.

Signed-off-by: Saleh Mehdikhani <saleh.mehdikhani@unikie.com>

### CODE REVIEW

**Comment by saleh-unikie** [comment]
Hi
The bug has reported in details in this issue:
https://github.com/zephyrproject-rtos/zephyr/issues/37305

File: subsys/bluetooth/host/direction.c [hunk 1]
```diff
@@ -40,7 +40,7 @@ static struct bt_le_df_ant_info df_ant_info;
 const static uint8_t df_dummy_switch_pattern[BT_HCI_LE_SWITCH_PATTERN_LEN_MIN] = { 0, 0 };
 #endif /* CONFIG_BT_DF_CONNECTIONLESS_CTE_RX */
 
-#define DF_SUPP_TEST(feat, n)                   ((feat) & BIT((n)))
+#define DF_SUPP_TEST(feat, n)                   ((feat) & (n))
```
Comment (ppryga) [inline subsys/bluetooth/host/direction.c:43]: I suggest to remove this macro.

File: subsys/bluetooth/host/direction.c [hunk 2]
```diff
@@ -40,7 +40,7 @@ static struct bt_le_df_ant_info df_ant_info;
...
 
 #define DF_AOD_TX_1US_SUPPORT(supp)             (DF_SUPP_TEST(supp, \
 						BT_HCI_LE_1US_AOD_TX))
```
Comment (ppryga) [inline subsys/bluetooth/host/direction.c:46]: Change all `DF_XXX_SUPPORT` macros this way:
```suggestion
#define DF_AOD_TX_1US_SUPPORT(supp)             ((supp) & BT_HCI_LE_1US_AOD_TX)
```

**Review by ppryga-nordic — CHANGES_REQUESTED** [review]
@saleh-unikie Thank you for spotting the bug and providing the PR to fix it.

I suggest to make the fix in a bit different way. 
`DF_SUPP_TEST` is not needed just to make bitwise `&` on two variables. 
Lest remove it and update macros that depend on it.

File: subsys/bluetooth/host/direction.c (hunk 2 above)
Comment (saleh-unikie) [reply subsys/bluetooth/host/direction.c]: Thanks for your suggest, yes! you are right. I modified the changes as you have suggested.

**Review by ppryga-nordic — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]

**Comment by cfriedt** [comment]
Fixes #37305
