### PR TITLE
Bluetooth: Host: Fix re-pairing across local ids

### LINKED ISSUE #22049: Bluetooth: IRK handling issue when using multiple local identities
**Describe the bug**
When using Bluetooth with multiple local identities, the IRK handling issues may occur.

**To Reproduce**
1) Use Zephyr Bluetooth peripheral with multiple local identities (A, B) and Central that uses IRK.
2) Connect and bond with Central on identity A.
3) Connect and bond with Central on identity B.
        You will see the following error log:
        `<err> bt_hci_core: Failed to add IRK to controller`
        The error log is observable also on every reboot.
        Failure is caused by trying to add the same IRK multiple times.
4) Reset one of the local identities (A or B) - the IRK will be removed from controller causing reconnection problem for second identity. After the reboot, the IRK's are reloaded and the device will be able to reconnect properly.

**Impact**
Error logs and possible reconection problems, when connecting given Central with multiple local identities of the same Zephyr device.
This affects the following use-cases:
Advertising using directed advertising when privacy is enabled.
Advertising using whitelist when peer is privacy-enabled.

**Environment**
 - Commit SHA: b413223a66ed9e857c67ee21d1e8be4768804dd1

**Additional context**
The problem replicates using various Link Layers.
The IRKs are currently not associated with local identities in the Bluetooth Controller.

### PR DESCRIPTION
**Pull request by alwa-nordic**
This PR prevents multiple bonds to the same peer with different local identities. This is not possible (at least without some complicated workarounds) due to limitations in the resolve list. Before this change, the host would accept multiple bonds, but the controller would fail to add all bonds to the resolve list. This inconsistency caused multiple issues.

This PR adds a new config "BT_ID_UNPAIR_MATCHING_BONDS" to give a behavior similar to re-bonding in this situation. When a bond is about to complete, this config will make the stack find any other bond with the same peer address (or IRK) and `bt_unpair` that bond before the event `pairing_complete`.

This PR adds Babblesim tests.

See the commit messages for more detail.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/22049

### CODE REVIEW

File: subsys/bluetooth/host/id.c [hunk 1]
```diff
@@ -788,13 +793,62 @@ void bt_id_pending_keys_update(void)
 	}
 }
 
+struct bt_rl_conflict {
+	struct bt_keys *candidate;
+	struct bt_keys *found;
+};
+
+/* The Controller Resolve List is constrained by 7.8.38 "LE Add Device To Resolving List command".
```
Comment (jori-nordic) [inline subsys/bluetooth/host/id.c:801]: reflow to 80col

File: subsys/bluetooth/host/id.c [hunk 2]
```diff
@@ -788,13 +793,62 @@ void bt_id_pending_keys_update(void)
...
+
 void bt_id_add(struct bt_keys *keys)
 {
 	struct bt_conn *conn;
 	int err;
 
 	BT_DBG("addr %s", bt_addr_le_str(&keys->addr));
 
+	__ASSERT_NO_MSG(keys != NULL);
+	__ASSERT_NO_MSG(!bt_id_find_conflict(keys).found);
```
Comment (jori-nordic) [inline subsys/bluetooth/host/id.c:850]: an assert for this seems pretty harsh. I would rather return an error code.

File: subsys/bluetooth/host/keys.c [hunk 3]
```diff
@@ -6,6 +6,7 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
+#include "zephyr/sys/__assert.h"
```
Comment (jori-nordic) [inline subsys/bluetooth/host/keys.c:9]: <>

File: subsys/bluetooth/host/keys.h [hunk 4]
```diff
@@ -6,6 +6,9 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
+#include "zephyr/bluetooth/addr.h"
+#include "zephyr/sys/util_macro.h"
```
Comment (jori-nordic) [inline subsys/bluetooth/host/keys.h:10]: <>

File: subsys/bluetooth/host/smp.c [hunk 5]
```diff
@@ -3928,6 +3930,38 @@ static uint8_t smp_ident_info(struct bt_smp *smp, struct net_buf *buf)
 	return 0;
 }
 
+/* For now, the SMP module makes the decision on behalf of the user to any
```
Comment (jori-nordic) [inline subsys/bluetooth/host/smp.c:3933]: missing `replace`, `overwrite` or `remove` ?

File: subsys/bluetooth/host/smp.c [hunk 6]
```diff
@@ -3995,7 +4029,10 @@ static uint8_t smp_ident_addr_info(struct bt_smp *smp, struct net_buf *buf)
 			}
 		}
 
-		bt_id_add(keys);
+		err = smp_id_add_unpair(smp, keys);
```
Comment (jori-nordic) [inline subsys/bluetooth/host/smp.c:4032]: should you also change https://github.com/zephyrproject-rtos/zephyr/blob/a4c046cd5a89a513483d164a17ec0e3178be07dc/subsys/bluetooth/host/smp.c#L4786 ?

File: subsys/bluetooth/host/smp.c [hunk 7]
```diff
@@ -3928,6 +3930,38 @@ static uint8_t smp_ident_info(struct bt_smp *smp, struct net_buf *buf)
 	return 0;
 }
 
+/* For now, the SMP module makes the decision on behalf of the user to any
+ * conflicting bond if the security level of the new bond is equal or better.
+ *
+ * This logic should be moved out to the application. But it requires new API.
+ */
+static uint8_t smp_id_add_unpair(struct bt_smp *smp, struct bt_keys *new_bond)
```
Comment (jori-nordic) [inline subsys/bluetooth/host/smp.c:3938]: I'd name that one `smp_id_add_replace`

**Review by jori-nordic — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/id.c (hunk 2 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/id.c:850]: I'm just documenting the assumption. It has always been there. Breaking this assumption was the source of this bug.

I did contemplate changing this function to "try add". But I don't think it's prettier. I suppose we would call it like in the following example?
```c
int err;
do {
    err = bt_id_add(new_bond);
    if (err == -EADDRINUSE) {
        bool allowed;
        int unpair_err;
	struct bt_keys conflict;

        BT_INFO("New bond conflict.");
	conflict = bt_id_find_conflict(new_bond);
        __ASSERT_NO_MSG(conflict);
        allowed = update_keys_check(smp, conflict.found);
        if (!allowed) {
            BT_WARN("Bond overwrite denied. Refusing new pairing.");
            return BT_SMP_ERR_AUTH_REQUIREMENTS;
        }
        BT_INFO("Bond overwrite permitted. Un-pairing old conflicting bond and finalizing new.");
        unpair_err = bt_unpair(conflict->id, &conflict->addr);
        __ASSERT_NO_MSG(!unpair_err);
    }
} while(err == -EADDRINUSE);
```

File: subsys/bluetooth/host/smp.c (hunk 6 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/smp.c:4032]: I think yes. At least it can't hurt. I'll see if I can make a bablesim test that fails there.

File: subsys/bluetooth/host/Kconfig [hunk 8]
```diff
@@ -466,6 +466,43 @@ config BT_SMP_ALLOW_UNAUTH_OVERWRITE
 	  to create a new bond the old bond has to be explicitly deleted with
 	  bt_unpair.
 
+config BT_ID_UNPAIR_MATCHING_BONDS
```
Comment (jori-nordic) [inline subsys/bluetooth/host/Kconfig:469]: Should we s/MATCHING/CONFLICTING since the API you have below uses this language?

File: subsys/bluetooth/host/id.c [hunk 9]
```diff
@@ -788,13 +792,70 @@ void bt_id_pending_keys_update(void)
...
+
 void bt_id_add(struct bt_keys *keys)
 {
 	struct bt_conn *conn;
 	int err;
 
 	BT_DBG("addr %s", bt_addr_le_str(&keys->addr));
 
+	__ASSERT_NO_MSG(keys != NULL);
+	__ASSERT_NO_MSG(!bt_id_find_conflict(keys));
```
Comment (jori-nordic) [inline subsys/bluetooth/host/id.c:857]: I think i'd rather log an error and exit. Don't wanna have an assert failing in the wild because of something we missed.
We can clean up the bonding procedure later.

File: subsys/bluetooth/host/smp.c (hunk 7 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/smp.c:3952]: bump

File: subsys/bluetooth/host/smp.c [hunk 10]
```diff
@@ -3928,6 +3949,48 @@ static uint8_t smp_ident_info(struct bt_smp *smp, struct net_buf *buf)
...
+		int unpair_err;
+
+		trust_ok = update_keys_check(smp, conflict);
+
+		if (!trust_ok) {
+			BT_WARN("Refusing new pairing. The old bond has more trust.");
+			return BT_SMP_ERR_AUTH_REQUIREMENTS;
+		}
+
+		BT_INFO("Bond replace permitted. Un-pairing old conflicting bond and finalizing new.");
```
Comment (jori-nordic) [inline subsys/bluetooth/host/smp.c:3983]: I think you can leave out. "Bond replace permitted.".

File: subsys/bluetooth/host/smp.c [hunk 11]
```diff
@@ -3928,6 +3949,48 @@ static uint8_t smp_ident_info(struct bt_smp *smp, struct net_buf *buf)
...
+	if (conflict) {
+		BT_INFO("New bond conflicts with a bond on id %d.", conflict->id);
+	}
+
+	if (conflict && !IS_ENABLED(BT_ID_UNPAIR_MATCHING_BONDS)){
+		BT_WARN("Refusing new pairing. The old bond must be unpaired first.");
+		return BT_SMP_ERR_AUTH_REQUIREMENTS;
+	}
+
+	if (conflict && IS_ENABLED(BT_ID_UNPAIR_MATCHING_BONDS)) {
```
Comment (jori-nordic) [inline subsys/bluetooth/host/smp.c:3972]: Are you sure you're exercising this branch in your test? I think it needs the `CONFIG_` prefix, I just used `IS_ENABLED` recently.

File: subsys/bluetooth/host/smp.c [hunk 12]
```diff
@@ -4739,14 +4805,34 @@ static void bt_smp_encrypt_change(struct bt_l2cap_chan *chan,
 		atomic_set_bit(smp->allowed_cmds, BT_SMP_CMD_SIGNING_INFO);
 	}
 
+	/* This is the latest point that is common for all code paths in the
```
Comment (jori-nordic) [inline subsys/bluetooth/host/smp.c:4808]: last point

File: subsys/bluetooth/host/smp.c [hunk 13]
```diff
@@ -4739,14 +4805,34 @@ static void bt_smp_encrypt_change(struct bt_l2cap_chan *chan,
...
+	 * pairing process (during which we still have the option to send
+	 * Pairing Failed). That makes it convenient to update the RL here. We
+	 * want to update the RL during the pairing process so that we can fail
+	 * it in case there is a conflict with an already-existing bond.
```
Comment (jori-nordic) [inline subsys/bluetooth/host/smp.c:4812]: s/already-//

**Review by jori-nordic — CHANGES_REQUESTED** [review]
some comments. Im a bit concerned that you have tests but they're not failing, they should be since the `IS_ENABLED()` call should not work.

File: subsys/bluetooth/host/Kconfig (hunk 8 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/Kconfig:469]: As discussed oob, I'll keep it as is.

**Comment by alwa-nordic** [comment]
> some comments. Im a bit concerned that you have tests but they're not failing, they should be since the `IS_ENABLED()` call should not work.

I fixed the IS_ENABLED. The test's were failing without the fix.

File: subsys/bluetooth/host/smp.c [hunk 14]
```diff
@@ -1984,6 +1985,14 @@ static int smp_error(struct bt_smp *smp, uint8_t reason)
...
 	struct bt_smp_pairing_fail *rsp;
 	struct net_buf *buf;
+	bool remote_already_completed;
+
+	/* By spec, SMP "pairing process" completes successfully when the last
+	 * key to distribute is acknowledged at link-layer.
+	 */
+	remote_already_completed = (atomic_test_bit(smp->flags, SMP_FLAG_KEYS_DISTR)
+	                            && !smp->local_dist
+				    && !smp->remote_dist);
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:1995]: Minor style issue: the line splits should happen right after `&&`, not right before it

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/smp.c [hunk 15]
```diff
@@ -3930,6 +3951,48 @@ static uint8_t smp_ident_info(struct bt_smp *smp, struct net_buf *buf)
...
+
+	/* Sanity check: It does not make sense to finalize a bond before we
+	 * have the remote identity.
+	 */
+	__ASSERT_NO_MSG(!(smp->remote_dist & BT_SMP_DIST_ID_KEY));
+
+	conflict = bt_id_find_conflict(new_bond);
+
+	if (conflict) {
+		BT_INFO("New bond conflicts with a bond on id %d.", conflict->id);
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:3966]: Seems like this and the other `BT_INFO()` in this function should instead be `BT_DBG()`?

File: include/zephyr/bluetooth/addr.h [hunk 16]
```diff
@@ -81,6 +81,14 @@ static inline int bt_addr_cmp(const bt_addr_t *a, const bt_addr_t *b)
 	return memcmp(a, b, sizeof(*a));
 }
 
+/** @brief Compare Bluetooth LE device addresses for equality.
+ */
+static inline bool bt_addr_le_eq(const bt_addr_le_t *a, const bt_addr_le_t *b)
+{
+	return ((a->type == b->type)
+	        && (memcmp(a->a.val, b->a.val, sizeof(a->a.val)) == 0));
```
Comment (jhedberg) [inline include/zephyr/bluetooth/addr.h:89]: Same thing here with the placement of `&&`

File: subsys/bluetooth/host/smp.c [hunk 17]
```diff
@@ -3930,6 +3951,48 @@ static uint8_t smp_ident_info(struct bt_smp *smp, struct net_buf *buf)
...
+{
+	struct bt_keys * conflict;
+
+	/* Sanity check: It does not make sense to finalize a bond before we
+	 * have the remote identity.
+	 */
+	__ASSERT_NO_MSG(!(smp->remote_dist & BT_SMP_DIST_ID_KEY));
+
+	conflict = bt_id_find_conflict(new_bond);
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:3964]: You can remove this line (generally: no empty line between assignment to a variable and testing for its value)

File: subsys/bluetooth/host/smp.c [hunk 18]
```diff
@@ -3930,6 +3951,48 @@ static uint8_t smp_ident_info(struct bt_smp *smp, struct net_buf *buf)
...
+		BT_WARN("Refusing new pairing. The old bond must be unpaired first.");
+		return BT_SMP_ERR_AUTH_REQUIREMENTS;
+	}
+
+	if (conflict && IS_ENABLED(CONFIG_BT_ID_UNPAIR_MATCHING_BONDS)) {
+		bool trust_ok;
+		int unpair_err;
+
+		trust_ok = update_keys_check(smp, conflict);
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:3979]: style: remote the empty line

File: include/zephyr/bluetooth/addr.h (hunk 16 above)
Comment (alwa-nordic) [reply include/zephyr/bluetooth/addr.h:89]: This will disappear when I rebase on https://github.com/zephyrproject-rtos/zephyr/pull/50361.

**Review by jhedberg — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]
