### PR TITLE
tests: drivers: flash: size to erase equals to size to write

### LINKED ISSUE #50149: tests: drivers: flash fails on nucleo_l152re because of wrong erase flash size
**Describe the bug**
When executing the tests/drivers/flash on the nucleo_l152re platform, it fails 

The page erase size is 256 so that test cannot write 512 bytes to flash correctly.

**To Reproduce**
1. west build -p auto -b nucleo_l152re tests/drivers/flash
2. west flash
3. See error

**Expected behavior**
Test PASSED 

**Impact**

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.1.0-4841-g4a702ea21ef8  ***                     
Running TESTSUITE flash_driver                                                        
===================================================================                   
START - test_read_unaligned_address                                                   
                                                                                      
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/flash/src/main.c:111: flash_)
Cannot write to flash                                                                 
 FAIL - test_read_unaligned_address in 0.227 seconds                                  
===================================================================                   
TESTSUITE flash_driver failed.                                                        
                                                                                      
------ TESTSUITE SUMMARY START ------                                                 
                                                                                      
SUITE FAIL -   0.00% [flash_driver]: pass = 0, fail = 1, skip = 0, total = 1 durations
 - FAIL - [flash_driver.test_read_unaligned_address] duration = 0.227 seconds         
                                                                                      
------ TESTSUITE SUMMARY END ------                                                   
                                                                                      
===================================================================                   
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: ubuntu
 - Toolchain : sdk 0.15.0
 - Commit SHA 4a702ea21ef82b301464551807358f8490951e45

### PR DESCRIPTION
**Pull request by FRASTM**
Need to erase as many bytes as the size to write.
In case the page_info.size is lower than the size to write,
the next write operation will fail.

This is the case when testing the tests/drivers/flash on the nucleo_l152re target platform
where the FLASH_PAGE_SIZE = 256 . When writing EXPECTED_SIZE = 512, the upper 256 bytes are not erased.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/50149

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
includes the https://github.com/zephyrproject-rtos/zephyr/pull/49967

**Comment by FRASTM** [comment]
CI failure on tests/drivers/flash/drivers.flash.stm32 (b_u585i_iot02a_ns:tests/drivers/flash/drivers.flash.stm32) with error
is fixed by PR https://github.com/zephyrproject-rtos/zephyr/pull/49967

**Comment by FRASTM** [comment]
CI requires https://github.com/zephyrproject-rtos/zephyr/pull/49967  to pass  b_u585i_iot02a_ns         tests/drivers/flash/drivers.flash.stm32

**Comment by mmahadevan108** [comment]
@FRASTM Can you rebase https://github.com/zephyrproject-rtos/zephyr/pull/49967 has been merged

**Comment by FRASTM** [comment]
rebase on 878edeb6ff190a713910a0e5cb9022704c5934a3

File: tests/drivers/flash/src/main.c [hunk 1]
```diff
@@ -93,7 +93,9 @@ static void *flash_driver_setup(void)
 	if (!is_buf_clear) {
 		/* erase page */
 		rc = flash_erase(flash_dev, page_info.start_offset,
-				 page_info.size);
+				 MAX(page_info.size, EXPECTED_SIZE));
+
+
```
Comment (erwango) [inline tests/drivers/flash/src/main.c:98]: Remove supplementary line

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: tests/drivers/flash/src/main.c [hunk 2]
```diff
@@ -93,7 +93,9 @@ static void *flash_driver_setup(void)
 	if (!is_buf_clear) {
 		/* erase page */
 		rc = flash_erase(flash_dev, page_info.start_offset,
-				 page_info.size);
+				 MAX(page_info.size, EXPECTED_SIZE));
```
Comment (nvlsianpu) [inline tests/drivers/flash/src/main.c:96]: This test was made with silent assumption that the flash page sizes >= EXPECTED_SIZE.

value used (based on `MAX(page_info.size, EXPECTED_SIZE)`) should be additionally aligned so it contains whole flash pages.

**Review by nvlsianpu — CHANGES_REQUESTED** [review]

File: tests/drivers/flash/src/main.c (hunk 2 above)
Comment (FRASTM) [reply tests/drivers/flash/src/main.c:96]: @nvlsianpu can you please clarify : do you mean aligning EXPECTED_SIZE with page_info.size ?

File: tests/drivers/flash/src/main.c (hunk 1 above)
Comment (FRASTM) [reply tests/drivers/flash/src/main.c]: removed

File: tests/drivers/flash/src/main.c (hunk 2 above)
Comment (nvlsianpu) [reply tests/drivers/flash/src/main.c:96]: aligned to the size of all pages to which EXPECTED_SIZE belongs, for instance:
```
{--------------------EXPECTED_SZIE----------------------}
{----page0----}{--page1---}{----------------page2---------------}
```
used erase size should be sum of these 3 pages.

Comment (FRASTM) [reply tests/drivers/flash/src/main.c:96]: Ok, 
with this sample, the page_size is fixed so the size to erase could simply be` int(EXPECTED_SIZE / page_info.size + 1)`

**Comment by fabiobaltieri** [comment]
@nvlsianpu can you follow up on this? (PR is marked for 3.2)

**Comment by mmahadevan108** [comment]
@FRASTM, I have deleted the 3.2 milestone. Please tag this for a future release.

**Comment by FRASTM** [comment]
rebase on 4fa2f6fdb29b2173c94fc3c9e4485e83817bffa8

**Comment by FRASTM** [comment]
rebase on b052143077a0e0258f4363c1c2c6eddff143c80b

**Comment by erwango** [comment]
@nvlsianpu, is that fine with you?

File: tests/drivers/flash/src/main.c [hunk 3]
```diff
@@ -91,9 +91,10 @@ static void *flash_driver_setup(void)
 	}
 
 	if (!is_buf_clear) {
-		/* erase page */
+		/* Erase a nb of pages aligned to the EXPECTED_SIZE */
 		rc = flash_erase(flash_dev, page_info.start_offset,
-				 page_info.size);
+				(page_info.size * (EXPECTED_SIZE / page_info.size + 1)));
```
Comment (de-nordic) [inline tests/drivers/flash/src/main.c:96]: I think that correct math is `(page_info.size * ((EXPECTED_SIZE + page_info.size - 1) / page_info.size)`

**Comment by FRASTM** [comment]
rebase on 6401682dd3092027e7c19039f3d46c893a9d413f
change calculation of the page_info.size

**Review by de-nordic — APPROVED** [review]

**Comment by de-nordic** [comment]
@erwango @nvlsianpu Please review.

**Review by erwango — APPROVED** [review]

**Comment by de-nordic** [comment]
@nashif Please merge when you have a moment. Thanks!

**Comment by fabiobaltieri** [comment]
> @nashif Please merge when you have a moment. Thanks!

Think you still need @nvlsianpu to approve.

File: tests/drivers/flash/src/main.c (hunk 2 above)
Comment (de-nordic) [reply tests/drivers/flash/src/main.c]: @nvlsianpu Can you take a look?

**Comment by de-nordic** [comment]
> > @nashif Please merge when you have a moment. Thanks!
> 
> Think you still need @nvlsianpu to approve.

Sorry, missed it. I will ping him.

**Review by gautierg-st — APPROVED** [review]

File: tests/drivers/flash/src/main.c (hunk 2 above)
Comment (nvlsianpu) [reply tests/drivers/flash/src/main.c]: my remarks were not applied correctly. Additional not needed flash page might be erased, also this assume all touched pages have same size.

I know that despite that this fix will work on every device - this is just test. Deficiencies can be fixed in the future if needed.

**Review by nvlsianpu — APPROVED** [review]
this fix has still some deficiencies, but let it go in,
