### PR TITLE
Bluetooth: Fix GATT race conditions

### LINKED ISSUE #54047: Bluetooth: Host: Invalid handling of Service Changed indication if GATT Service is registered after Bluetooth initialization and before settings load
**Describe the bug**
Registering GATT Service after Bluetooth is initialized, but before settings are loaded from non-volatile memory may lead to sending Service Changed indication to bonded peers even though the GATT database is actually not changed. 

**To Reproduce**
Selected sample must register GATT Service dynamically after Bluetooth is initialized, but before settings are loaded.
Use `samples/bluetooth/peripheral_hids_mouse` from https://github.com/nrfconnect/sdk-nrf repository.

1.` west build -b nrf52840dk_nrf52840 --pristine`
2. `west flash --erase`
3. Connect and bond with a Central.
4. Reboot the sample and reconnect with the Central.
   See the not needed Service Changed indication (either using Bluetooth sniffer or add additional logs).

The issue should replicate on any board.

**Expected behavior**
Service Changed should not be sent unless GATT database is actually changed.
To verify if the GATT database has changed, we shall wait until settings are loaded from non-volatile memory.

**Impact**
Sending unnecessary Service Changed indications.

I think that it could also make the GATT Client permanently change unaware.
Client marked as change unaware in `db_changed` called by `bt_gatt_service_register`.
Then `db_hash_process` could cancel the `sc_process` work without clearing the change-unaware state improperly set to a GATT Client.
The second issue case was not replicated locally by me.

**Logs and console output**

Below are the logs from running the sample.
I introduced additional logs (in bold) that are directly related to the SC indication handling and GATT database hash matching value read from settings.

*** Booting Zephyr OS build v3.2.99-ncs1-1522-g1a5051acc44c ***
Starting Bluetooth Peripheral HIDS mouse example
I: 8 Sectors of 4096 bytes
I: alloc wra: 0, fe8
I: dat.](7@J
I: 7b ba 2d 1b 10 ef d7 17 |{.-.....
I: 4d cb d8 5b             |M..[
I: HW Platform: Nordic Semiconductor (0x0002)
I: HW Variant: nRF52x (0x0002) 1077356637
I: No ID address. App must call settings_load()
I: Bluetooth initialized
I: Identity: E2:5anufacturer 0x0059
I: LMP: version 5.3 (0x0c) subver 0x122a
Regular advertising started
**E: SC process start 0x0001 end 0xffff**
**E: SC process start 0x0000 end 0x0000**
Connected 65:73:A4:04:A0:8C (random)
Regular advertising started
Passkey for 65:73:A4:04:A0:8C (random): 529859
Press Button 1 to confirm, Button 2 to reject.
Numeric Match, conn 0x20001d68
Security changed: 65:73:A4:04:A0:8C (random) level 4
Pairing completed: C4:93:D9:41:94:17 (public), bonded: 1
**E: stored SC for C4:93:D9:41:94:17 (public) (bt/sc/c493d94194170, 0x0000-0x0000)**

After reboot:

*** Booting Zephyr OS build v3.2.99-ncs1-1522-g1a5051acc44c ***
Starting Bluetooth Peripheral HIDS mouse example
I: 8 Sectors of 4096 bytes
I: alloc wra: 0, f80
I: data wra: 0, d4
I: SoftD 7 40 4a |.Y.](7@J
I: 7b ba 2d 1b 10 ef d7 17 |{.-.....
I: 4d cb d8 5b             |M..[
I: HW Platform: Nordic Semiconductor (0x0002)
I: HW Variant: nRF52x (0x0002)
I: Firmware: Standard Bluetooth controller (0x00) Version 18.42841 Build 1077356637
I: No ID address. App must
I: Identity: E2:59:1B:9F:37:58 (random)
I: HCI: version 5.3 (0x0c) revision 0x122a, manufacturer 0x0059
I: LMP: version 5.3 (0x0c) subver 0x122a
Direct advertising to C4:93:D9:41:94:17 (public) started
**E: SC process start 0x001b end 0x0032**
**E: Hash matches clear SC range changed**
**E: stored SC for C4:93:D9:41:94:17 (public) (bt/sc/c493d94194170, 0x001b-0x0032)**
**E: SC restore peer C4:93:D9:41:94:17 (public) start 0x001b end 0x0032**
Regular advertising started (public)
**E: stored SC for C4:93:D9:41:94:17 (public) (bt/sc/c493d94194170, 0x0000-0x0000)**
Security changed: C4:93:D9:41:94:17 (public) level 4

**Environment:**
Replicated with current main (`855cc65badf7f54fe8b5341dd0b3efb7f7370bd9`) of  https://github.com/nrfconnect/sdk-nrf.
Zephyr SDK 0.15.0.

### LINKED ISSUE #54773: Bluetooth: GATT: Possible race conditions related to GATT database hash calculation after settings load
**Describe the bug**
Right after settings are loaded, the initial `db_hash_process` call is delayed and moved to the Bluetooth long workqueue (handled in a low priority thread). That could trigger an edge case allowing for accessing GATT by previously bonded peers before the database hash is properly recalculated. For example, if GATT database changes during DFU, bonded peer may not be marked as change unaware in time (the peer could perform GATT operations even though the peer shall actually be marked as change unaware).

**Expected behavior**
Consider introducing synchronization mechanism to ensure that the `db_hash_process` is done before any GATT Client could access GATT Services. Maybe we could perform `db_hash_process` right in `db_hash_commit` callback context (instead of moving it to Bluetooth long workqueue context that has low priority). Thanks to that we would be sure that after settings load operation is completed, the GATT database hash is proper.

**Impact**
GATT Caching feature may not work correctly after DFU for previously bonded peers.

### PR DESCRIPTION
**Pull request by jori-nordic**
See commit messages.

Fixes #54047
Fixes #54773

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1675,6 +1680,13 @@ int bt_gatt_service_register(struct bt_gatt_service *svc)
 	__ASSERT(svc->attrs, "invalid parameters\n");
 	__ASSERT(svc->attr_count, "invalid parameters\n");
 
+	if (IS_ENABLED(CONFIG_BT_SETTINGS) &&
+	    atomic_get(&init) &&
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:1684]: Not exactly related to this PR, but it had completely flown past me that we have these rather unintuitive `init` and `service_init` variables in `gatt.c`. It seems they're essentially used as atomic boolean flags to track whether initialisation has been done or not. I think it make much more sense to convert both of them into a single atomic_t bitmask declared using `ATOMIC_DEFINE()`, and then instead of the `cas()` or `atomic_get()` calls, you'd have something like `if (atomic_test_and_set_bit(gatt_flags, GATT_INIT_DONE)) {` in `gatt_init()` and here above you'd have `atomic_test_bit(gatt_flags, GATT_INIT_DONE)` instead of the awkward `atomic_get(&init)`.

Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:1684]: yeah I also found that weird, I'll address it.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -84,8 +84,14 @@ static sys_slist_t callback_list;
...
-static atomic_t init;
-static atomic_t service_init;
+enum gatt_global_flags {
+	GATT_INITIALIZED,
+	GATT_SERVICE_INITIALIZED,
+
+	GATT_NUM_FLAGS,
+};
+
+ATOMIC_DEFINE(gatt_flags, GATT_NUM_FLAGS);
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:94]: I think `static ATOMIC_DEFINE(...` would be more appropriate, since the variable is limited to this c-file. Otherwise looks good, thanks!

**Review by jhedberg — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Review by alwa-nordic — DISMISSED** [review]

**Comment by carlescufi** [comment]
@jori-nordic please rebase

**Review by jhedberg — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Comment by jori-nordic** [comment]
@fredrikdanebjer what's stopping you from registering the services before `bt_init`? 

Ie, could you tell me more about why you want to do this in this specific spot/time.

**Comment by fredrikdanebjer** [comment]
@jori-nordic well in short, our architecture makes it problematic. Because of how we start things up and of how our resources becomes available, we prefer(need) to call 'bt_init' early.

So, basically what I'm wondering is whether it's feasible for us at all to look into making this change in gatt.c, or if it's a too big change. I thought that maybe you would know by heart if the gatt.c architecture would makes this suggestuon problematic.

The alternative is ofc. for us to change our system, which we know would require quite a bit of work. Possible, but undesired.

**Comment by jori-nordic** [comment]
Yeah I think this could be difficult to do right. A quick patch might be doable, but almost guaranteed to introduce bugs.
So we're kind of in the same situation, possible, but undesired.

_However_, if you're willing to make the change, we could accept it provided that there is enough test coverage (i.e. Babblesim test cases). 
These would be testing the previous race condition(s) + the functionality you're introducing, that is adding dyn services between `bt_init` and `settings_load`.

I don't know about your architecture, but it may turn out that it's simpler to change it than to make the stack change + the tests and going through the review process. Not trying to discourage you, just to make clear that this isn't a quick patch to gatt.c done in an afternoon.
