### PR TITLE
kernel: allow threads to sleep forever

### LINKED ISSUE #19748: k_sleep(K_FOREVER) behavior unexpected
> One side comment. During playing with k_sleep and negative numbers I've noticed that `k_sleep(K_FOREVER)` returns immediately. Is K_FOREVER intended to be used for `k_sleep`?

_Originally posted by @nordic-krch in https://github.com/zephyrproject-rtos/zephyr/pull/19591#issuecomment-540554331_

Since we had recently reached some consensus that `k_sleep` should use the standard timeout API it should support `K_FOREVER`.

If it does not a fix might be integrated with rework of `k_poll` since functionally `k_sleep` could be seen as `k_poll` with no events.   (The current implementation has asserts that at least one event is provided, but passing zero events works as expected when asserts are not enabled, which is the default condition.)

### PR DESCRIPTION
**Pull request by tyrantlizard77**
Previously, passing K_FOREVER to k_sleep()/k_usleep()
would return immediately.

Forever is a long time. Even if woken up at some point,
we still had forever to sleep, so return K_FOREVER in this
case.

Fixes: #19748

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

File: kernel/sched.c [hunk 1]
```diff
@@ -992,6 +997,11 @@ s32_t z_impl_k_usleep(int us)
 {
 	s32_t ticks;
 
+	if (us == K_FOREVER) {
```
Comment (pabigot) [inline kernel/sched.c]: This block needs to be removed.

File: tests/kernel/sleep/src/main.c [hunk 2]
```diff
@@ -235,11 +235,48 @@ void test_sleep(void)
...
 
+static void forever_thread_entry(void *p1, void *p2, void *p3)
+{
+	s32_t ret;
+
+	ret = k_sleep(K_FOREVER);
+	zassert_equal(ret, K_FOREVER, "unexpected return value");
+	k_sem_give(&test_thread_sem);
+
+	ret = k_usleep(K_FOREVER);
```
Comment (pabigot) [inline tests/kernel/sleep/src/main.c]: This part of the test should be removed.

**Review by pabigot — CHANGES_REQUESTED** [review]
Thanks for putting this together.

The changes to `k_usleep()` need to be removed.

The consensus opinion in timeout discussion was that `k_sleep()` should be changed from taking milliseconds to taking a timeout parameter, making it consistent with most other kernel operations that take a timeout.  Coccinelle scripting (`int_literal_to_timeout.cocci`) exists to ensures that integer literal parameters to it are converted to `K_MSEC()` calls (the script will be re-run to clean up the baseline during stabilization).  The notation for an unbounded timeout is `K_FOREVER`.

`k_usleep()` is documented as taking an integral value in microseconds.  Passing `K_FOREVER` will produce a type error in the future.  Its use for this function should be removed from documentation and validation.

The documentation change for `k_sleep()` in https://github.com/zephyrproject-rtos/zephyr/pull/20448/commits/99defbcc0017d975a9366f1cf3b7e72cf1c74249 should be incorporated, either in this PR or a subsequent one.

**Comment by andrewboie** [comment]
@pabigot OK, removed the handling for k_usleep().

**Review by pabigot — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Can't see what this would hurt
