### PR TITLE
arch: arm: fix mpu compiler warnings

### LINKED ISSUE #83448: Compiler warning about null-pointer exception detection on un-mapped flash areas when `CONFIG_NULL_POINTER_EXCEPTION_DETECTION_MPU=y` on `mimxrt685_evk/mimxrt685s/cm33`
**Describe the bug**

Following compiler warning occurs when I3C device with 9 byte of reg address to dts, and DCONFIG_NULL_POINTER_EXCEPTION_DETECTION_MPU=y.
_C:/repos/ADI-zephyr/zephyr/arch/arm/core/mpu/arm_mpu.c: In function 'z_arm_mpu_init':_
_C:/repos/ADI-zephyr/zephyr/arch/arm/core/mpu/arm_mpu.c:481:8: warning: integer constant is too large for its type_
  _481 |         (!DT_NULL_PAGE_DETECT_NODE_EXIST)_

- I3C device requires 9 byte of address according to i3c-device.yaml 
https://git.byronlathi.com/bslathi19/zephyr/-/blob/main/dts/bindings/i3c/i3c-device.yaml?ref_type=heads

**To Reproduce**

1. Build a board with M33 with DCONFIG_NULL_POINTER_EXCEPTION_DETECTION_MPU=y with a tests/*:
example:
west build -b mimxrt685_evk/mimxrt685s/cm33 .\tests\drivers\uart\uart_basic_api\ -p always -DCONFIG_NULL_POINTER_EXCEPTION_DETECTION_MPU=y
2. See the compiler warning:
_warning: integer constant is too large for its type
  481 |         (!DT_NULL_PAGE_DETECT_NODE_EXIST)_
  
**Expected behavior**

Compiler warning shall not occur.
**Impact**

CI/CD requires -Werror option, thus this fails CI/CD procedure in out-of-tree zephyr pipeline.
**Logs and console output**

**Environment (please complete the following information):**
 - Zephyr 4.00+ (macro DT_NULL_PAGE_DETECT_NODE_EXIST added [here](https://github.com/zephyrproject-rtos/zephyr/commit/f2e115cca374516cb9e2a5845d1e3b77b53a18c9#diff-c7c1d65647254c45a9882753a577c36e14758fd0fd77f689504cea5cc03d4a65R44) )
 - OS: all
 - Toolchain Zephyr SDK
 - Commit SHA or Version used

### PR DESCRIPTION
**Pull request by wearyzen**
What is the change?
 - Use a macro to search for "zephyr, memory-attr" in only those nodes that have the property "zephyr, memory-regions".
 - Fixes #83448.

Why is this needed?
 - Using `DT_REG_ADDR` inside `DT_FOREACH_STATUS_OKAY_NODE_VARGS` can lead to compiler warnings if a devicetree node has an addresses larger than 64bits. An example of such node is wm8904 i3c with 92 bit encoding addresses `audio_codec: wm8904@1a0000000000000000`. We can avoid this warning since this is not applicable for nodes that have the attribute "zephyr,memory-regions".

### CODE REVIEW

File: arch/arm/core/mpu/arm_mpu.c [hunk 1]
```diff
@@ -42,8 +42,8 @@ BUILD_ASSERT((DT_FOREACH_STATUS_OKAY_NODE_VARGS(
 	 (DT_REG_SIZE(node_id) >= CONFIG_CORTEX_M_NULL_POINTER_EXCEPTION_PAGE_SIZE)) ||
 
 #define DT_NULL_PAGE_DETECT_NODE_EXIST                                                             \
-	(DT_FOREACH_STATUS_OKAY_NODE_VARGS(NULL_PAGE_DETECT_NODE_FINDER, zephyr_memory_attr) false)
-
+	(DT_FOREACH_OKAY_VARGS_zephyr_memory_region(NULL_PAGE_DETECT_NODE_FINDER,                  \
```
Comment (decsny) [inline arch/arm/core/mpu/arm_mpu.c:45]: this is an implementation/intermediate function, technically not guaranteed to continue to exist as it is not an API defined thing, you should be using `DT_FOREACH_STATUS_OKAY_VARGS(zephyr_memory_region NULL_PAGE_DETECT_NODE_FINDER
```suggestion
	(DT_FOREACH_STATUS_OKAY_VARGS(zephyr_memory_region, NULL_PAGE_DETECT_NODE_FINDER, zephyr_memory_attr) false)
```

**Review by mbolivar — CHANGES_REQUESTED** [review]
Please don't use the generated macros in source code, that's an abstraction violation. See https://docs.zephyrproject.org/latest/build/dts/api-usage.html

**Comment by wearyzen** [comment]
I will have a look at the twister tests and the bring the PR back for review, putting it to draft.

**Review by mbolivar — APPROVED** [review]

**Review by kartben — APPROVED** [review]
