### PR TITLE
Bluetooth: controller: Ignore connections from same peer

### LINKED ISSUE #26172: Zephyr Master/Slave not conforming with Core Spec. 5.2 connection policies
**Describe the bug**
According to the Bluetooth Specification, Core 5.2, on any multiple incoming connection requests from a Master, the slave device shall ignore such requests if it is already in a connection with that Master.

Also, it is not allowed for a Master to initiate multiple connections to the same Slave on a released product.

See [1] and [2].

**To Reproduce**
It was reproduced by having a Master application issue two connection requests towards the same Zephyr Slave device.
Both devices had privacy enabled, using Private Resolvable Addressing.

**Expected behavior**
An initiator shall not send a connection request to an
advertiser it is already connected to.
If an advertiser receives a connection request from an initiator it is already
connected to, it shall ignore that request.

It seems that policies are not enforced - a Zephyr Master can connect multiple times to the same identified slave (currently only verified by code inspection) and a Zephyr slave can accept multiple connection requests from the same identified Master (reproduced/verified in practice).

Expected behavior would be that the Zephyr slave would ignore multiple connection indication packets from the same identified Master.

**Impact**
The currently allowed spec. violation causes a risk that a product based on the Zephyr project cannot be qualified if/when the qualification test suite from Bluetooth SIG would check for the compliance on these connection policies.

**Screenshots or console output**

**Environment (please complete the following information):**

**Additional context**

References

[1] [CS 5.2, Vol 6, Part B, 1.1.1 Permitted state and role combinations]

The Link Layer may optionally support multiple state machines. If it does
support multiple state machines, then any combination of states and roles may
be supported. In particular, the Link Layer is permitted to be in the Connection
State multiple times with any mix of Master Role and Slave Role. However, any
two devices shall not have more than one connection between them.

[2] [CS 5.2, Vol 6, Part B, 4.5 Connection state]

When two devices are in a connection, the two devices act in different roles. A
Link Layer in the Master Role is called a master. A Link Layer in the Slave Role
is called a slave. The master controls the timing of a connection event. A
connection event is a point of synchronization between the master and the
slave. There shall be only one connection, whether or not established, between
two LE device addresses. An initiator shall not send a connection request to an
advertiser it is already connected to.
If an advertiser receives a connection request from an initiator it is already
connected to, it shall ignore that request.

### PR DESCRIPTION
**Pull request by wopu-ot**
Ignore connection indications from peers that are already
connected. This is to bring the behavior of the controller in
accordance with [5.2, Vol 6, Part B, 4.5 Connection state]:
"If an advertiser receives a connection request from an initiator it
is already connected to, it shall ignore that request."

Signed-off-by: Wolfgang Puffitsch <wopu@demant.com>

Fixes #26172

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_slave.c [hunk 1]
```diff
@@ -77,6 +78,46 @@ void ull_slave_setup(memq_link_t *link, struct node_rx_hdr *rx,
...
+	} else {
+#else /* CONFIG_BT_CTLR_PRIVACY */
+	if (1) {
+#endif /* CONFIG_BT_CTLR_PRIVACY */
+		memcpy(peer_id_addr, peer_addr, BDADDR_SIZE);
+	}
+
+#if defined(CONFIG_BT_CTLR_IGNORE_SAME_PEER_CONN)
+	uint8_t own_addr_type = pdu_adv->rx_addr;
+	uint8_t *own_addr = ll_addr_get(own_addr_type, NULL);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_slave.c:102]: Why not use the `pdu_adv->connect_ind.adv_addr`?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_slave.c (hunk 1 above)
Comment (wopu-ot) [reply subsys/bluetooth/controller/ll_sw/ull_slave.c:102]: The intention is to ignore connections to the same identity; `pdu_adv->connect_ind.adv_addr` may be an RPA that is refreshed periodically without changing identity.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_slave.c:102]: My concern is regarding extended advertising where each advertising set has its own random address.

Comment (wopu-ot) [reply subsys/bluetooth/controller/ll_sw/ull_slave.c:102]: Good point. I will add a field to `ll_adv_set` to avoid races between different advertising sets.

File: subsys/bluetooth/controller/Kconfig [hunk 2]
```diff
@@ -372,6 +372,15 @@ config BT_CTLR_CONN_RSSI
...
 	  Enable connection RSSI measurement.
 
+config BT_CTLR_IGNORE_SAME_PEER_CONN
+	bool "Ignore connection requests from same peer"
+	default y
+	help
+	  Ignored connection requests from the same peer. While the
+	  Bluetooth specification does not allow multiple connections
+	  with the same peer, allowing such connections is useful
+	  while debugging multiple connections.
```
Comment (Thalley) [inline subsys/bluetooth/controller/Kconfig:382]: If the spec specifies a `shall` for this, why is it a Kconfig? Wouldn't disabling this cause the stack to be non-compliant?

File: subsys/bluetooth/controller/ll_sw/ull_filter.c [hunk 3]
```diff
@@ -1081,6 +1091,28 @@ static void filter_clear(struct lll_filter *filter)
...
+
+	for (handle = 0U; handle < CONFIG_BT_MAX_CONN; handle++) {
+		struct ll_conn *conn = ll_connected_get(handle);
+
+		/* The RPA of the connection matches the RPA that was just resolved */
+		if (conn &&
+		    conn->peer_addr_type < 2U &&
+		    !memcmp(conn->peer_addr, rl[rl_idx].curr_rpa.val, BDADDR_SIZE)) {
+			memcpy(conn->peer_addr, rl[rl_idx].id_addr.val,
+			       BDADDR_SIZE);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_filter.c:1108]: Minor: The maximum line length was recently increased to 100, so this can be on a single line

File: subsys/bluetooth/controller/ll_sw/ull_adv.c [hunk 4]
```diff
@@ -889,6 +889,13 @@ uint8_t ll_adv_enable(uint8_t enable)
 		conn->supervision_expire = 0;
 		conn->procedure_expire = 0;
 
+#if defined(CONFIG_BT_CTLR_IGNORE_SAME_PEER_CONN)
+		conn->own_addr_type = 0;
+		memset(conn->own_addr, 0xFF, sizeof(conn->own_addr));
+		conn->peer_addr_type = 0;
+		memset(conn->peer_addr, 0xFF, sizeof(conn->peer_addr));
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv.c:896]: What's the reasoning behind setting the addresses to 0xFFFFFF?

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/Kconfig (hunk 2 above)
Comment (wopu-ot) [reply subsys/bluetooth/controller/Kconfig:382]: This was suggested by @carlescufi https://github.com/zephyrproject-rtos/zephyr/issues/26172#issuecomment-644093770

File: subsys/bluetooth/controller/ll_sw/ull_adv.c (hunk 4 above)
Comment (wopu-ot) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:896]: 0xFFFFFF matches `BT_ADDR_NONE`, which I find slightly more intuitive than 0x000000, which would match `BT_ADDR_ANY`.

File: subsys/bluetooth/controller/Kconfig (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/controller/Kconfig:382]: I see. Then I would suggest only allowing it to be turned on for TEST/DEBUG builds, e.g. by only allowing it be be `n` if e.g. `BT_TESTING` is enabled. 

I don't think it's a good idea to intentionally allowing a non-spec compliant build without some sort of warning or making sure that whoever disables this is aware of the consequences.

File: subsys/bluetooth/controller/ll_sw/ull_adv.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:896]: I see. In the case that a literal value (in this case 0xFFFFFF) has a specific meaning (e.g. to be comparable with BT_ADDR_NONE), then I strongly suggest that we add a `#define` or similar for the value.

File: subsys/bluetooth/controller/Kconfig (hunk 2 above)
Comment (wopu-ot) [reply subsys/bluetooth/controller/Kconfig:382]: I could make it dependent on `BT_CTLR_ADVANCED_FEATURES`, though I believe I would have to flip the polarity (`...ALLOW...` instead of `...IGNORE...` and `!defined` instead of `defined`) to get the correct behavior if the former is not defined.

Comment (Thalley) [reply subsys/bluetooth/controller/Kconfig:382]: Alternatively we could add similar warnings to disabling this as we have when e.g. we enable SMP debug keys. See https://github.com/zephyrproject-rtos/zephyr/pull/26186/files

File: subsys/bluetooth/controller/ll_sw/ull_adv.c (hunk 4 above)
Comment (wopu-ot) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c]: Copying from `BT_ADDR_LE_NONE` now to make the meaning clearer.

File: subsys/bluetooth/controller/Kconfig (hunk 2 above)
Comment (wopu-ot) [reply subsys/bluetooth/controller/Kconfig]: I moved the user-controller flag it under `BT_CTLR_ADVANCED_FEATURES` and added a WARNING to the description. I also made the configuration now dependent on having more than one connection to not punish implementations that allow only a single connection anyway.

File: subsys/bluetooth/controller/Kconfig.ll_sw_split [hunk 5]
```diff
@@ -475,6 +475,18 @@ config BT_CTLR_CONN_RSSI_EVENT
...
+	bool "Allow connection requests from same peer"
+	depends on BT_MAX_CONN > 1
+	help
+	  Allow connection requests from the same peer. While the
+	  Bluetooth specification does not allow multiple connections
+	  with the same peer, allowing such connections is useful
+	  while debugging multiple connections.
+
+	  WARNING: This option enables behavior that violates the Bluetooth
+	  specification.
```
Comment (Thalley) [inline subsys/bluetooth/controller/Kconfig.ll_sw_split:488]: I would like @carlescufi input on whether this is enough, or if we also should add build warnings like was done for other such configurations in https://github.com/zephyrproject-rtos/zephyr/pull/26186

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 5 above)
Comment (wopu-ot) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:488]: > I would like @carlescufi input on whether this is enough, or if we also should add build warnings like was done for other such configurations in #26186

@carlescufi What is your take in this?

**Review by erbr-ot — APPROVED** [review]
LGTM

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 5 above)
Comment (Thalley) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:488]: @wopu-ot Is this something that is critical to get in? I can mark it as approved, and then we can consider adding additional warnings (if needed) afterwards in a separate PR.

**Review by Thalley — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]
quick-ack.
