### PR TITLE
STM32: drivers: i2c: make dma config field conditional

### LINKED ISSUE #94010: i2c_ll_stm32 does not tolerate i2c devices not using DMA when DMA is enabled
### Describe the bug

On the STM32, when trying to enable I2C DMA, I ran into an issue where I2C devices that do no have DMA will cause a compile error.

I have created a minimal reproducible example to help this along.

Additional Observations:
- This issue does not occur for UART
- If you only define a single DMA channel (i.e. only RX or only TX), the error also occurs

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Clone https://github.com/Lachlan-Frawley/zephyr-stm-i2c-dma-issue-minimal-repro
2. Run west build
3. Observe the compile error
4. Disable the i2c2 node
5. Run west build
6. Observe no compile error

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

OS: Linux
Toolchain: Zephyr SDK
Zephyr Commit: 9d0942beb55c7b387fee91d9465b4437a30ad60b

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kbidani**
This commit updates I2C_DMA_DATA_INIT() macro to use
IF_ENABLED(DT_INST_DMAS_HAS_NAME(...), (...)),
so that the DMA configuration field is only generated if the corresponding DMA property exists in the Device Tree. This prevents macro expansion errors and allows a mix of I2C peripherals with and without DMA support in the same build.

fixes #94010

### CODE REVIEW

File: drivers/i2c/i2c_ll_stm32.c [hunk 1]
```diff
@@ -496,7 +496,8 @@ void i2c_stm32_dma_rx_cb(const struct device *dma_dev, void *user_data,
 }
 
 #define I2C_DMA_DATA_INIT(index, dir, src, dest)						\
-	.dma_##dir##_cfg = {									\
+	IF_ENABLED(DT_INST_DMAS_HAS_NAME(index, dir),						\
+	(.dma_##dir##_cfg = {									\
```
Comment (etienne-lms) [inline drivers/i2c/i2c_ll_stm32.c]: Indentation:
```suggestion
		   (.dma_##dir##_cfg = {							\

File: drivers/i2c/i2c_ll_stm32.c [hunk 2]
```diff
@@ -511,7 +512,8 @@ void i2c_stm32_dma_rx_cb(const struct device *dma_dev, void *user_data,
 		.source_burst_length = 1,							\
 		.dest_burst_length = 1,								\
 		.dma_callback = i2c_stm32_dma_##dir##_cb,					\
-	},											\
+	}, \
+))
```
Comment (etienne-lms) [inline drivers/i2c/i2c_ll_stm32.c]: For consistency of indentation:
```suggestion
	},))

**Review by etienne-lms — COMMENTED** [review]
For consistency of the commit message header line of commits related to **i2c_ll_stm32.c**, I would suggest:
```patch
-STM32: drivers: i2c: make dma config field conditional on i2c
+drivers: i2c: stm32: make DMA config field conditional on I2C
```

Suggestion for the commit message body:
```patch
-This commit updates the macro to use
+This commit updates I2C_DMA_DATA_INIT() macro to use

**Review by erwango — APPROVED** [review]

**Review by etienne-lms — COMMENTED** [review]
Could you update the commit message header line to explicitly state it's about the STM32 driver? You can also remove the trailing `on I2C` words. E.g.:
```
drivers: i2c: stm32: make DMA config field conditional

**Review by gautierg-st — APPROVED** [review]
