### PR TITLE
Bluetooth: Host: Fix resource leak in bt_gatt_unsubscribe

### LINKED ISSUE #38688: bt_gatt_unsubscribe does not remove subscription from internal list/returning BT_GATT_ITER_STOP causes bt_gatt_subscribe to return -ENOMEM / -12
**Describe the bug**
If BT_GATT_ITER_STOP is returned from the [`bt_gatt_subscribe_params::notify` callback](https://github.com/zephyrproject-rtos/zephyr/blob/357ec64b36cd84ca87660407e67eb0cb1cfe932b/subsys/bluetooth/host/gatt.c#L2802), [`bt_gatt_unsubscribe` is called](https://github.com/zephyrproject-rtos/zephyr/blob/357ec64b36cd84ca87660407e67eb0cb1cfe932b/subsys/bluetooth/host/gatt.c#L4554) which does not clear the internal state of the notification subscription correctly.

Trying to create new subscriptions to different devices with `bt_gatt_subscribe` will eventually start returning -ENOMEM (-12) when the internal subscription list fills up.

**To Reproduce**
Using the code below, call `start_subscription` on more devices than (`CONFIG_BT_MAX_PAIRED` + `CONFIG_BT_MAX_CONN`).
```C
static bt_gatt_subscribe_params sub_params = { 0 };

static uint8_t on_notify_data(struct bt_conn *conn, struct bt_gatt_subscribe_params *params, const void *data, uint16_t length){
    return BT_GATT_ITER_STOP;
}

void start_subscription(bt_conn * conn){
  sub_params.notify = on_notify_data;
  sub_params.value_handle = ctx.handles.measurement_value;
  sub_params.ccc_handle = ctx.handles.measurement_cccd;
  sub_params.value = BT_GATT_CCC_NOTIFY;
  atomic_set_bit(sub_params.flags, BT_GATT_SUBSCRIBE_FLAG_VOLATILE);
  int err = bt_gatt_subscribe(ctx.conn, &sub_params);
  if (err == -ENOMEM) {
      //bug has happened
  }
}
```

**Expected behavior**

New subscriptions should not fail. 

`bt_gatt_unsubscribe` should set the internal states `gatt_sub::peer` when the subscription list is empty like what `gatt_sub_remove` does:
https://github.com/zephyrproject-rtos/zephyr/blob/357ec64b36cd84ca87660407e67eb0cb1cfe932b/subsys/bluetooth/host/gatt.c#L2715

**Impact**
In an environment where it is expected to enable subscriptions of many different peers over this devices lifetime, subscriptions will eventually fail and not allow any more subscriptions to be created.

**Environment (please complete the following information):**
NRF Sdk 1.6.1

**Additional context**
A temprary fix for this is to just to always return `BT_GATT_ITER_CONTINUE` from the `bt_gatt_subscribe_params::notify` callback and not call `bt_gatt_unsubscribe` anywhere.

### PR DESCRIPTION
**Pull request by alwa-nordic**
There are two simmilar functions for unsubscribing from GATT handles.

 - `gatt_sub_remove`, which is called on disconnect for every subscription
will free the `subscriptions` entry when the entry represents no
subscriptions.

 - `bt_gatt_unsubscribe`, called by the application, which forgets to
 free the `subscriptions` entry.

If all subscriptions grouped in a `subscriptions` entry are removed
using `bt_gatt_unsubscribe` before disconnect, there are no
subscriptions left to call `gatt_sub_remove` on. The `subscriptions`
entry is then never freed.

The above results in a resource leak of a `subscriptions` entry.

This fix makes explicit and enforces the invariant that there should not
be entries in `subscriptions` with an empty subscription list.

Fixes #38688

Signed-off-by: Aleksander Wasaznik <aleksander.wasaznik@nordicsemi.no>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Comment by alwa-nordic** [comment]
Pushed update adding use of `gatt_sub_free` and `gatt_sub_has_no_subscriptions` to `gatt_sub_remove`, because the check bsim-build complained that they were unused. Probably when `CONFIG_BT_GATT_CLIENT` is not set.

**Review by joerchan — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -4597,6 +4614,10 @@ int bt_gatt_unsubscribe(struct bt_conn *conn,
 		return -EINVAL;
 	}
 
+	if (gatt_sub_has_no_subscriptions(sub)) {
+		gatt_sub_free(sub);
+	}
+
 	if (has_subscription) {
```
Comment (Thalley) [inline subsys/bluetooth/host/gatt.c:4621]: `gatt_sub_has_no_subscriptions` and `has_subscription` has very similar names, but are implemented different. 

Do they share the same semantics? i.e. if `has_subscription == false` is `gatt_sub_has_no_subscriptions` always true, or vice versa?

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -2699,6 +2704,19 @@ bool bt_gatt_is_subscribed(struct bt_conn *conn,
 	return false;
 }
 
+static bool gatt_sub_has_no_subscriptions(struct gatt_sub *sub)
```
Comment (carlescufi) [inline subsys/bluetooth/host/gatt.c:2707]: I would rename this `gatt_sub_is_empty()` instead.

**Review by Thalley — APPROVED** [review]
