### PR TITLE
lib: add cbprintf capability

### LINKED ISSUE #29202: core kernel depends on minimal libc `z_prf()`
**Describe the bug**
Some dependencies have accumulated on the internal minimal libc function `z_prf()`, to the point where the function was moved out of minimal libc and into lib/os.

This is not good, lib/os now has two completely orthogonal printf()-like implementations that we will have to maintain in perpetuity, even if minimal libc is not used, and especially if we ever settle on a different third-party small-footprint C library and remove minimal libc entirely.

Any kernel subsystem dependency on `z_prf()` needs to use the `printk()` family of functions instead. If `printk()` needs to support some functionality that is only offered by `z_prf()` (like printing floating point values) add non-default Kconfigs against printk() code which adds this and has negligible footprint or stack space impact on users who don't enable it.

`z_prf()` itself needs to be moved back to minimal libc where it belongs.

### PR DESCRIPTION
**Pull request by pabigot**
This PR adds a C99 stdio value formatter capability named `cbprintf()` (plus related variants) where generated text is emitted through a callback.  This allows generation of arbitrarily long output without a buffer, functionality that is core to printk, logging, and other system and application needs.

The formatter supports most C99 specifications, excluding:
* %L[aefg] long double conversion
* wide character output

The new solution is derived from `z_prf()`, which had the most complete functionality available.  Format parsing has been reimplemented, while floating point conversion has been retained and enhanced.

Kconfig options allow disabling features like floating-point conversion if they are not necessary.

Benefits include:
* No more inconsistencies between printk, logging, and shell formatting capabilities.
* Reduced inconsistencies due to toolchain libc capabilities.
* Simplified (toolchain-independent) formatting feature selection via Kconfig.
* Core infrastructure can avoid duplication with libc printf by using cbprintf variants.
* Potentially a path to resolving #18351 and related issues, as the infrastructure can tell a caller the total size of arguments to the conversion string.
* Fixed bugs with several specifications.

Costs include:
* Applications that used only printk with no extra features consume more code space than the previous implementation.

Fixes #29202

### CODE REVIEW

**Review by nashif — APPROVED** [review]
LGTM, this is similar to what I was trying to do with just the moving things around :)

https://github.com/zephyrproject-rtos/zephyr/compare/master...nashif:zprf_vprintk?expand=1

**Review by tyrantlizard77 — APPROVED** [review]
this looks great.
I'm assuming stack usage for printk() is roughly like it was before? Passing CI result suggests to me that it does, but I thought I'd ask.

**Review by tyrantlizard77 — APPROVED** [review]
this looks great.
I'm assuming stack usage for printk() is roughly like it was before? Passing CI result suggests to me that it does, but I thought I'd ask.

**Review by tyrantlizard77 — APPROVED** [review]
this looks great.
I'm assuming stack usage for printk() is roughly like it was before? Passing CI result suggests to me that it does, but I thought I'd ask.

**Review by tyrantlizard77 — APPROVED** [review]
this looks great.
I'm assuming stack usage for printk() is roughly like it was before? Passing CI result suggests to me that it does, but I thought I'd ask.

**Comment by pabigot** [comment]
> this looks great.

Thanks!

> I'm assuming stack usage for printk() is roughly like it was before?

I expect it's a little larger compared to `z_vprintk`, but smaller for `z_prf()`, depending on how much the compiler could overlay the local variables.  I don't know of any easy way to get real data.

**Comment by npitre** [comment]
```
+/* We can't determine at build-time whether int is 64-bit, so assume
+ * it is.  If not the values are truncated at build time, and the str
+ * pointers will be updated during test initialization.
+ */
+static const unsigned int pfx_val = (unsigned int)0x7b6b5b4b3b2b1b0b;
```

In the Zephyr environment, an int is always 32 bits. Only a long will 
vary in width, and sizeof(long) is always equal to sizeof(void*). So the 
constant above will always be truncated.

**Review by carlescufi — CHANGES_REQUESTED** [review]
This looks great @pabigot, thank you.
The reason I am blocking this is that it increases the ROM footprint of `samples/hello_world` from 15760 to 16992 by default, although the only extra option enabled is `CBPRINTF_64BIT_SUPPORT`. Is there something we can do about this?

**Comment by pabigot** [comment]
> it increases the ROM footprint of `samples/hello_world` from 15760 to 16992 ... Is there something we can do about this?

Yeah, that's the fly in the ointment.  I've done a bunch of measurements, and tried different things, but have found nothing more that can be made optional without causing breakage (e.g. failing to correctly deduce the size of an argument that can't be converted, causing subsequent conversions to be corrupted).  Disabling 64-bit integer handling has no significant effect: the cost is all in handling C99 format specifications correctly.

Once you start adding logging and shell and other things that used to use two implementations the impact goes down.  At least one sensor sample I tried shrunk with this.  There's also some opportunity to eliminate existing dependencies on libc in Zephyr code, since this provides a replacement for `snprintf`.

The only candidate solution remaining is to have a Kconfig option that uses the old `z_vprintk()` implementation.  That's small, and would satisfy the needs of `hello_world` and anything that only uses `printk`, doesn't care about floating point, precision options, or decimal 64-bit values.

I'll take a look at what happens with that.

**Comment by npitre** [comment]
On Mon, 9 Nov 2020, Peter A. Bigot wrote:

> Yeah, that's the fly in the ointment.  I've done a bunch of measurements, and tried different things, but have found nothing more that can be made optional without causing breakage (e.g. failing to correctly deduce the size of an argument that can't be converted, causing subsequent conversions to be corrupted).  Disabling 64-bit integer handling has no significant effect: the cost is all in handling C99 format specifications correctly.

Did you try removing the double and long double from argument_value 
union in the case there is no float nor 64bit support? Some code might 
need to be #ifdef'd out in that case of course which isn't as pretty, 
but if the size reduction is significant then this might be worth it.

**Comment by npitre** [comment]
```
+#ifdef CONFIG_CBPRINTF_64BIT_SUPPORT
+/* The maximum defined standard integer type is 64 bits, so we assume
+ * that's the number of bits in uintmax_t.  Some toolchains might
+ * allow more, in which case the inconsistency needs to be
+ * resolved.
+ */
+typedef intmax_t sint_value_type;
+typedef uintmax_t uint_value_type;
+#define CONVERTED_INT_BUFLEN ((64U + 2U) / 3U)
```

If you're assuming a 64-bits width to size a buffer, then you should 
really define sint_value_type as an int64_t. If intmax_t is larger then 
it would only get truncated which is a benign "inconsistency". As it is, 
such inconsistency could get you a buffer overflow instead.

**Comment by pabigot** [comment]
@carlescufi There's now `CONFIG_CBPRINTF_NANO` which substitutes a nearly unmodified implementation of `z_vprintk` for the new one while retaining the new wrapper infrastructure (the old one didn't return the number of characters emitted, which is required).

This is opt-in, but if selected the size of `hello_world` is unchanged.

The unit test for `cbprintf` has, to the extent reasonable, been updated to verify existing behavior of the nano formatter.  It gets some things wrong, and there's a lot it doesn't handle.

Both the unit test and `kernel/common` pass locally with both full and nano formatters.  We'll see what CI thinks.  (I also have to fix some style issues that were grandfathered in with `z_vprintk`.

If this seems like the right way to move forward I'll squash nano support into the original commit.

**Comment by pabigot** [comment]
@npitre Responding here in a batch since there's no context from email (could you submit further comments through the github review UI?):

> In the Zephyr environment, an int is always 32 bits...

OK, but I want the test to be prepared for 64-bit integers.  It doesn't cost anything other than a compliance check failure (which  won't pass anyway).

> Did you try removing the double and long double from argument_value
> union in the case there is no float nor 64bit support?

No.  The fact that the formatter won't convert those types doesn't mean it won't have to pull them out of the argument list.  Removing them with ifdefs seems likely to create unmaintainable code and probably won't reduce code size since the code that would use them is already removed.

> If you're assuming a 64-bits width to size a buffer, then you should really define sint_value_type as an int64_t.

I had thought about that, but research suggested that the wording in the C18 standard prevents using a size larger than 64 bits for `intmax_t` (toolchains are free to go further with non-standard types like `__int128`, etc., but not use `intmax_t` for them).  I didn't see a compelling counter-argument so I stayed with the existing implementation.

**Comment by npitre** [comment]
On Mon, 9 Nov 2020, Peter A. Bigot wrote:

> @npitre Responding here in a batch since there's no context from email (could you submit further comments through the github review UI?):

Not really. I am blind and must rely on accessibility tools. The github 
web interface is a complete nightmare wrt accessibility. Things as 
simple as simply approving a RP is a real PITA. The review UI is just 
unusable. Same for the CI reports.

I did provide the context manually though. Didn't it come through?

> > In the Zephyr environment, an int is always 32 bits...

> OK, but I want the test to be prepared for 64-bit integers.  It doesn't cost anything other than a compliance check failure (which  won't pass anyway).

Just use a long then. Or better yet, int64_t.
You will never get a 64-bit integer to fit in an int.

> > Did you try removing the double and long double from argument_value
> > union in the case there is no float nor 64bit support?

> No.  The fact that the formatter won't convert those types doesn't mean it won't have to pull them out of the argument list.  Removing them with ifdefs seems likely to create unmaintainable code and probably won't reduce code size since the code that would use them is already removed.

Yeah, you're right. I was under the impression that the union was passed 
down to helpers, but it is not and its scope remains local. So the 
compiler is free to optimize it.

> > If you're assuming a 64-bits width to size a buffer, then you should really define sint_value_type as an int64_t.

> I had thought about that, but research suggested that the wording in the C18 standard prevents using a size larger than 64 bits for `intmax_t` (toolchains are free to go further with non-standard types like `__int128`, etc., but not use `intmax_t` for them).  I didn't see a compelling counter-argument so I stayed with the existing implementation.

The argument would be to avoid inconsistencies and confusion. If 
intmax_t can't be bigger than int64_t then it is clearer to just use 
that and dispense with the "some toolchains might allow more" comment.

**Comment by pabigot** [comment]
>  I did provide the context manually though. Didn't it come through?

It did, yes.

> > In the Zephyr environment, an int is always 32 bits... OK, but I want the test to be prepared for 64-bit integers. It doesn't cost anything other than a compliance check failure (which won't pass anyway).
> Just use a long then. Or better yet, int64_t. You will never get a 64-bit integer to fit in an int.

It can't be a long: the test relies on these values being `int` because they're paired with an unqualified `%x` specification.

The ILP64 model has 64-bit ints.  Given that some Zephyr applications seem to target odd architectures for video/sound processing I'd rather not make assumptions that this won't have to work on something unusual.

> > If you're assuming a 64-bits width to size a buffer, then you should really define sint_value_type as an int64_t. I had thought about that, but research suggested that the wording in the C18 standard prevents using a size larger than 64 bits for `intmax_t` (toolchains are free to go further with non-standard types like `__int128`, etc., but not use `intmax_t` for them). I didn't see a compelling counter-argument so I stayed with the existing implementation.
> The argument would be to avoid inconsistencies and confusion. If intmax_t can't be bigger than int64_t then it is clearer to just use that and dispense with the "some toolchains might allow more" comment.

But the `j` conversion specifier is documented to operate on `intmax_t` types, not `int64_t` types.  I think it's more important to use the types that are identified in the standard.

**Comment by npitre** [comment]
> > The argument would be to avoid inconsistencies and confusion. If intmax_t can't be bigger than int64_t then it is clearer to just use that and dispense with the "some toolchains might allow more" comment.

> But the `j` conversion specifier is documented to operate on `intmax_t` types, not `int64_t` types.  I think it's more important to use the types that are identified in the standard.

Well, in that case please add something like:

BUILD_ASSERT(sizeof(sint_value_type) == 8);

so that if the assumption in CONVERTED_INT_BUFLEN is no longer true then 
there won't be unnoticed buffer overflows.

**Comment by carlescufi** [comment]
> @carlescufi There's now `CONFIG_CBPRINTF_NANO` which substitutes a nearly unmodified implementation of `z_vprintk` for the new one while retaining the new wrapper infrastructure (the old one didn't return the number of characters emitted, which is required).
> 
> This is opt-in, but if selected the size of `hello_world` is unchanged.

This is good enough for me. I am now happy with this change.

**Review by carlescufi — APPROVED** [review]

**Comment by pabigot** [comment]
In the latest push I've squashed the nano option into the commit that introduces cbprintf.

I've also changed the way support for reduced space for integer value conversion is selected and implemented so that it no longer depends on a 64-bit assumption (though if intmax_t is larger than 64 bits a Kconfig value must be changed).

@npitre does this work for you?

**Comment by pabigot** [comment]
This adds `cb[v]snprintf()` as a substitute for `[v]snprintf()` to avoid pulling in libc formatting code when Zephyr modules need format-to-buffer capability.  With that name policy `cb[v]printf` should be substitutes for `[v]printf`, but those names are already used for the new API that takes the callback function and context.

I'm not a fan of trying to override standard library functions, so some options are:
* do not provide something that can replace `[v](sn)?printf()` using the internal cbprintf infrastructure;
* move the `cb` part of the substitute API to the end of the identifier, e.g. `printfcb("fmt", ...)` and `snprintfcb(buf,sz,fmt,...)`

I'm inclined to try the latter.

**Comment by pabigot** [comment]
> This is opt-in, but if selected the size of `hello_world` is unchanged.

While this was true when I wrote it, it's not exactly true now.  To use the former `v_printk()` to implement `cbsnprintf` it is necessary to adapt it to count the number of characters that would be emitted.  This increases the image size from 15738 to 15866.

If we make the `[v](sn)?printf` replacement functions optional most of that 128 bytes could probably be reclaimed.  I'll tackle that later.

**Comment by pabigot** [comment]
DNM to give me a chance for final tuning and documentation updates before the approvals let this get merged.

**Comment by npitre** [comment]
> I've also changed the way support for reduced space for integer value conversion is selected and implemented so that it no longer depends on a 64-bit assumption (though if intmax_t is larger than 64 bits a Kconfig value must be changed).

The CONFIG_CBPRINTF_UINTMAX_BITS doesn't bring anything right now. All 
architectures currently supported by Zephyr must have 64 here. It can't 
be smaller as it would trip the assertion to prevent buffer overflows, 
and making it larger is just a waste of stack space. The day 
sizeof(uintmax_t) is larger then something could be done about it. In 
the mean time this is just loading the config space for no value.

I understand why you created CONFIG_CBPRINTF_FULL_WIDTH but this saves 
only 15 bytes of stack. Is it worth it given that tight memory systems 
are more likely to use the nano code anyway?

Otherwise there is also the issue of overflowing pad0_pre_dp or 
pad0_post_dp. With any of the other width parameters, an overflow would 
simply create a misaligned display. in the pad0_pre_dp/pad0_post_dp case 
that would display the wrong numerical value. Unlikely of course but 
still. Maybe reverting to a canned exponent form in that case should be 
considered in that case.

In fact, can pad0_pre_dp and pad0_post_dp ever be non-zero at the same 
time? I think you could combine them and use a pre/post flag instead.

**Comment by pabigot** [comment]
The public libc-compatible functions have been renamed and made optional,
so NANO without them has no change in code size relative to pre-PR for
applications that use only printk.

A bug with `z_vprintfk` on LP64 has been fixed in NANO.

> The CONFIG_CBPRINTF_UINTMAX_BITS doesn't bring anything right now. All
> architectures currently supported by Zephyr must have 64 here. It can't
> be smaller as it would trip the assertion to prevent buffer overflows,
> and making it larger is just a waste of stack space. The day
> sizeof(uintmax_t) is larger then something could be done about it. In
> the mean time this is just loading the config space for no value.

I don't think it hurts anything and it does prepare for the day when
expectations turn out to be wrong.  Removing it would require a
constant 64 for a value that's dependent on intmax_t, which just
doesn't seem right.

> I understand why you created CONFIG_CBPRINTF_FULL_WIDTH but this
> saves only 15 bytes of stack. ... Otherwise there is also the issue
> of overflowing pad0_pre_dp or pad0_post_dp.

Yes, good point:  I hadn't considered the FP padding could overflow too.

I've:
* removed the FULL_WIDTH option;
* combined the former pad0_prefix (integer-only) , pad0_pre_dp, and
  pad0_post_dep values into one field pad0_value with a bit field to
  distinguish which of the floating point positions would use it;
* used unions because width and pad0_prefix have disjoint lifespans,
  as do prec and pad0_pre_exp.

I also moved the conversion specifier out of the bitfield to a char,
because it turns out the compiler's wise enough to use the leftover
bitfield space to store it anyway.  So the conversion specification
structure is three words (12 bytes on a I32 host).

Both these changes reduced code size.

**Comment by npitre** [comment]
> > The day sizeof(uintmax_t) is larger then something could be done about it. In the mean time this is just loading the config space for no value.

> I don't think it hurts anything and it does prepare for the day when expectations turn out to be wrong.

You added the assertion check to guard against false expectations and 
that's perfect.

I think that over engineering something just in case some day things are 
different does actually hurt. It would be simple enough to fix it if 
ever that day comes. In the mean time this is just unneeded cruft that 
will give unnecessary pause to everyone configuring their build as they 
can't do anything with it anyway.

> Removing it would require a constant 64 for a value that's dependent on intmax_t, which just doesn't seem right.

In practice it is right, and is likely to be right for quite a while. 
The assertion is there for when it won't be, and a comment should say 
so.  That's good enough for simplifying the config space which is a 
worthy goal.

If you really want to make things fall out automatically, the 
alternative could be:

```
#ifndef __INTMAX_WIDTH__
#define __INTMAX_WIDTH__ 64
#define __INTMAX_TYPE__ __INT64_TYPE__
#define __UINTMAX_TYPE__ __UINT64_TYPE__
#endif

[...]

typedef __INTMAX_TYPE__ intmax_t;
```

And then use `__INTMAX_WIDTH__` directly for `CONVERTED_INT_BUFLEN`.

So far, all the compilers I've seen do define `__INTMAX_TYPE__` and 
`__INTMAX_WIDTH__` already.

**Review by MaureenHelm — APPROVED** [review]

**Comment by npitre** [comment]
Also, if `CONVERTED_INT_BUFLEN` depends on some implicit and possibly 
variable value, it would be safer to do this instead:

```
#if CONVERTED_FP_BUFLEN >= CONVERTED_INT_BUFLEN
#define CONVERTED_BUFLEN CONVERTED_FP_BUFLEN
#else
#define CONVERTED_BUFLEN CONVERTED_INT_BUFLEN
#endif
```

You may safely drop the U qualifiers if the preprocessor doesn't 
like them as this is only used to size an array.

**Comment by npitre** [comment]
> It can't be a long: the test relies on these values being `int` because they're paired with an unqualified `%x` specification.

OK. Similar to one of my previous comment, you may know at compile time 
the width of an int at compile time. It is `__INT_WIDTH__`.

**Comment by pabigot** [comment]
> It is `__INT_WIDTH__`.

That's not in the standard.

**Comment by npitre** [comment]
> > It is `__INT_WIDTH__`.

> That's not in the standard.

That's in the Zephyr build environment sstandard.

There is provision for providing it when the compiler doesn't. See 
`include/toolchain/xcc_missing_defs.h` for example.

**Comment by pabigot** [comment]
@npitre I understand you would do this a different way.  I haven't seen a compelling argument that there's something clearly wrong with the way it's being done.  I don't feel that what you propose is a significant improvement that warrants introducing non-standard technologies or making assumptions about what future toolchains may provide or targets might require.

At this point I do not intend to change the way the integer buffer length is determined.  If you feel strongly, block this PR, and we can see what the codeowners decide should be done.

**Comment by npitre** [comment]
> At this point I do not intend to change the way the integer buffer length is determined.  If you feel strongly, block this PR, and we can see what the codeowners decide should be done.

Given that roughly 47% of the code in prf.c is actually mine, don't you 
think that my opinion should count a little?

I do object to CONFIG_CBPRINTF_UINTMAX_BITS.

I've provided you with 2 alterntives to it. Please be free to do it some 
other way if you don't like them.

**Review by nashif — CHANGES_REQUESTED** [review]
-1 until the discussion points are resolved, @npitre  is unable to 'request changes' on his own using the web UI.

**Comment by pabigot** [comment]
@npitre I think we were both still getting hung up on 64-bit as a special case.

I changed it to use sizeof(value_type) to calculate the maximum buffer length in `CBPRINTF_COMPLETE` which has a well-defined map from size to number of characters in the converted representation.

For nano I added a `BUILD_ASSERT`, since it uses a different formula that might not be correct for values other than 4 and 8.

So the Kconfig is no longer needed, nor is reliance on toolchain-specific constants.

Is it OK now?

**Comment by npitre** [comment]
> So the Kconfig is no longer needed, nor is reliance on toolchain-specific constants.

> Is it OK now?

Yes, thanks.

One last thing(tm)

I'd suggest this change:

```
 #ifdef CONFIG_CBPRINTF_FP_SUPPORT
-#define CONVERTED_BUFLEN CONVERTED_FP_BUFLEN
+#define CONVERTED_BUFLEN MAX(CONVERTED_FP_BUFLEN, CONVERTED_INT_BUFLEN)
 #else
 #define CONVERTED_BUFLEN CONVERTED_INT_BUFLEN
 #endif
```

This way you don't have to presume FP is bigger.

**Comment by npitre** [comment]
Also, it is unfortunate that the printk code implicitly zero-padded %p.
That is causing some tests to fail as this isn't the behavior the C lib
is expecting.

I think we should drop the implicit precision to be standard conformant
and fix those %p instances where that matters instead.

**Comment by pabigot** [comment]
> I'd suggest this change:
> +#define CONVERTED_BUFLEN MAX(CONVERTED_FP_BUFLEN, CONVERTED_INT_BUFLEN)

Good catch, done.

> Also, it is unfortunate that the printk code implicitly zero-padded %p.
> That is causing some tests to fail as this isn't the behavior the C lib
> is expecting.

Which tests?  What C library depends on the format?

The standard specifies that `%p` format is implementation-defined.  `z_prf` and `z_vprintk` differed (the latter zero-padded, the former did not).  I picked printk as the standard to follow, but I'm not bound to that.

I did add a Kconfig option to do `nil` instead of `0x0...0` but I'm not sure it's worth it, so I'm tempted to removing the feature.  I personally find it more visible, but it could break automated processing.

I'd be fine with removing the zero padding, with or without making it optional.

So, I'm soliciting feedback:
* Zero pad pointers to pointer width, strip leading zeros after `0x`, or make this controllable?
* Use `nil` for null pointers, or treat them as any other pointer value, or keep this controllable?

Absent strong contrary opinions I will:
* Unconditionally remove the leading zeros from pointers
* Remove the option to format null pointers as `nil`

**Comment by npitre** [comment]
> > Also, it is unfortunate that the printk code implicitly zero-padded %p. That is causing some tests to fail as this isn't the behavior the C lib is expecting.

> Which tests?

tests/lib/sprintf/

> What C library depends on the format?

It's rather that Newlib (used in some Zephyr configurations), glibc 
(used with the native_posix targets) and the minimal C lib (where this 
code comes from) all agreed on not having an implicit precision with %p.

> I'd be fine with removing the zero padding, with or without making it optional.

I'd lean towards removing it and not making that optional.
You still can add it to the string format when needed.

> I did add a Kconfig option to do `nil` instead of `0x0...0` but I'm not sure it's worth it, so I'm tempted to removing the feature.  I personally find it more visible, but it could break automated processing.

At least glibc does `(nil)`.

I'd suggest doing `0x0` with `%#p". This way both are available.

**Comment by andrewboie** [comment]
> Also, it is unfortunate that the printk code implicitly zero-padded %p. That is causing some tests to fail as this isn't the behavior the C lib is expecting. I think we should drop the implicit precision to be standard conformant and fix those %p instances where that matters instead.

`%p` seems to be an extension. The POSIX docs don't have anything to say about it that I can find:

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/printf.html
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap05.html#tag_05

If there's no actual standard for this perhaps we can leave this alone or update the test, I wouldn't treat current test behavior as necessarily binding without some concrete standard backing it. (which you should feel free to link if you have sources)

Absent a standard telling us otherwise, `%p` being zero padded is very handy for putting debug output in columns.

**Comment by npitre** [comment]
> I'd suggest doing `0x0` with `%#p". This way both are available.

In fact, `%#p` could combine both: `0x0`for NULL, and implicit precision 
to the pointer width.

**Comment by npitre** [comment]
> Absent a standard telling us otherwise, `%p` being zero padded is very handy for putting debug output in columns.

Would it make sense to mimick existing libs' behavior with `%p` and 
having the automatic padding with `%#p` ?

**Comment by pabigot** [comment]
> `%p` seems to be an extension. The POSIX docs don't have anything to say about it that I can find:

Those links are for the command-line utility, which doesn't support it.  https://en.cppreference.com/w/c/io/fprintf has the summary content; or you can get to the final draft standard from [wikipedia](https://en.wikipedia.org/wiki/C17_(C_standard_revision)#References) and look at section 7.21.6.

> If there's no actual standard for this perhaps we can leave this alone or update the test, I wouldn't treat current test behavior as necessarily binding without some concrete standard backing it. (which you should feel free to link if you have sources)

I'll update the minimal libc tests to include behavior with the nano variant.

> In fact, `%#p` could combine both: `0x0`for NULL, and implicit precision to the pointer width.

I'd considered that, but a nit-picky problem is that while the representation of `%p` is implementation defined, use of `%#p` is undefined behavior, which MISRA disallows by Rule 1.3 (I can't correlate from MISRA to C99 to determine what's required for this specific violation because my C99 draft doesn't have the violations numbered; it may be ignorable).

We could do `%p` being zero padded hex value for all pointers including null, then `%#p` being no-zero-padding and `nil` for null pointers.  Or vice-versa.  Is conforming to existing minimal libc behavior, or existing printk behavior, more desirable?

**Comment by andrewboie** [comment]
> > `%p` seems to be an extension. The POSIX docs don't have anything to say about it that I can find:
> 
> Those links are for the command-line utility, which doesn't support it. [en.cppreference.com/w/c/io/fprintf](https://en.cppreference.com/w/c/io/fprintf) has the summary content; or you can get to the final draft standard from [wikipedia](https://en.wikipedia.org/wiki/C17_(C_standard_revision)#References) and look at section 7.21.6.

Derp, thanks.
 
> We could do `%p` being zero padded hex value for all pointers including null, then `%#p` being no-zero-padding and `nil` for null pointers. Or vice-versa. Is conforming to existing minimal libc behavior, or existing printk behavior, more desirable?

I'm thinking if we change this to be more standards compliant, or at least more in line with what Linux libc does, that if this diverges from exiting printk() or minimal libc behavior, we just make the change and deal with the fallout.

In other words: I'd say any precedent established by Zephyr-specific stuff like `printk()`, minimal libc, or their associated tests should not prevent us from doing the right thing and aligning the behavior with established precedent outside of Zephyr, if that makes sense.

**Comment by andrewboie** [comment]
> Absent a standard telling us otherwise, `%p` being zero padded is very handy for putting debug output in columns.
> Would it make sense to mimick existing libs' behavior with `%p` and having the automatic padding with `%#p` ?

This approach is agreeable to me.

**Comment by pabigot** [comment]
> > Absent a standard telling us otherwise, `%p` being zero padded is very handy for putting debug output in columns.
> > Would it make sense to mimick existing libs' behavior with `%p` and having the automatic padding with `%#p` ?
> 
> This approach is agreeable to me.

Following gcc 9.3.0 on Ubuntu then `%p` will give `ptr 0x1234 (nil)`

Then as a Zephyr extension `%#p` will give `0x00001234` `0x00000000`, padded to the size of the pointer.

Of course `%#p` isn't undefined behavior because `cbprintf` isn't a standard library function, so this is fine.

I'll make it so in the next day or two.

**Comment by pabigot** [comment]
> > This approach is agreeable to me.
> 
> Following gcc 9.3.0 on Ubuntu then `%p` will give `ptr 0x1234 (nil)`
> 
> Then as a Zephyr extension `%#p` will give `0x00001234` `0x00000000`, padded to the size of the pointer.
> 
> Of course `%#p` isn't undefined behavior because `cbprintf` isn't a standard library function, so this is fine.

To clarify: I'll implement the above behavior only for `CBPRINTF_COMPLETE`, leaving `CBPRINTF_NANO` to do what it does now.

This is the only way to avoid increasing the code size when selecting nano, and even if we make pointer support the same the two will still be different for other format operations, so it doesn't seem worth doing.

**Comment by andrewboie** [comment]
It's probably from just not having enough coffee that I didn't notice this earlier. I actually have some reservations about introducing format code extensions.

>  having the automatic padding with %#p 

Are their alternatives to introducing non-standard format codes? For example this may result in warnings for APIs which use `__printf_like`

It might just be better to just do standard behavior, and if someone **really** wants their pointers printed in a special specific way for column formatting purposes they can do `0x%08lx` or whatever and cast their pointer to `uintptr_t`.

**Comment by npitre** [comment]
> >  having the automatic padding with %#p 

> Are their alternatives to introducing non-standard format codes? For example this may result in warnings for APIs which use `__printf_like`

You're right.

> It might just be better to just do standard behavior, and if someone **really** wants their pointers printed in a special specific way for column formatting purposes they can do `0x%08lx` or whatever and cast their pointer to `uintptr_t`.

Or just do `"%.8p"`.

Well, although glibc does handle `"%.8p", gcc still warns about it.

So yeah... `0x%08lx` or `%#.8lx` it shall be.

**Comment by pabigot** [comment]
cbprintf now consistently formats non-null `%p` as `0x1234`, no leading zeros.

Format of null pointers diverges: `COMPLETE` uses `(nil)` following Linux libc, while `NANO` uses `0x0` because detecting null and emitting `(nil)` increases memory significantly from the previous footprint.

`CBPRINTF_NULL_AS_NIL` has been removed.

When `MINIMAL_LIBC` is selected `CBPRINTF_NANO` selects `LIBC_SUBSTS` which causes a size increase, but this is required to correctly implement `s[n]printf()` (otherwise the number of characters that would have been written is not counted.)

 A warning call-out has been added to the documentation to note the limitations of C library functions when `MINIMAL_LIBC` is combined width `CBPRINTF_NANO`.  `tests/libc/sprintf` should now pass with that combination but this is a non-default configuration that requires manual checking with an overlay, and when used some tests are skipped because they verify unsupported functionality. 

Floating point formatting support is default-enabled with `FPU` is selected, as this seems to be the clue that floating point is desired by the application.

**Comment by npitre** [comment]
This looks fine to me.

> Format of null pointers diverges: `COMPLETE` uses `(nil)` following Linux libc, while `NANO` uses `0x0` because detecting null and emitting `(nil)` increases memory significantly from the previous footprint.

That much? I would have expected 10-15 bytes of text.

I'll try to come up with a good comment to replace the `/* Magically convert the base-2 exponent to a base-10exponent. */` eventually.

I can see potential for smallish code size reduction here and there but that'll be easier to test once this is merged.

@nashif you may turn that -1 on my behalf to +1.

File: tests/kernel/common/src/printk.c [hunk 1]
```diff
@@ -26,10 +25,21 @@ char *expected = "22 113 10000 32768 40000 22\n"
 		 "42 42   42       42\n"
 		 "42 42 0042 00000042\n"
 		 "255     42    abcdef        42\n"
-		 "ERR -1 ERR ffffffffffffffff\n"
+		 "68719476735 -1 18446744073709551615 ffffffffffffffff\n"
 ;
-#else
-
+#elif defined(CONFIG_CBPRINTF_COMPLETE)
+char *expected = "22 113 10000 32768 40000 %llu\n"
```
Comment (andrewboie) [inline tests/kernel/common/src/printk.c:31]: Think this needs some adjustment, based on CI results.

**Review by nashif — APPROVED** [review]

File: tests/unit/cbprintf/main.c [hunk 2]
```diff
@@ -0,0 +1,1056 @@
...
+
+#include "../../../lib/os/cbprintf.c"
+
+#if defined(CONFIG_CBPRINTF_COMPLETE)
+#include "../../../lib/os/cbprintf_complete.c"
+#elif defined(CONFIG_CBPRINTF_NANO)
+#include "../../../lib/os/cbprintf_nano.c"
+#endif
+
+/* We can't determine at build-time whether int is 64-bit, so assume
```
Comment (andrewboie) [inline tests/unit/cbprintf/main.c:98]: > We can't determine at build-time whether int is 64-bit, so assume

how about `BUILD_ASSERT(sizeof(int) < 8)`?

The below casting where you do stuff like
```
	static const unsigned int pfx_val = (unsigned int)0x7b6b5b4b3b2b1b0b;
```

Are you sure that this is defined behavior?
This is generating a CI lintian warning BTW

**Review by tyrantlizard77 — COMMENTED** [review]
Some of the lintian checks that are producing warnings are unavoidable, but I don't think we should use non-standard format codes:
```
-:4840: WARNING:PRINTF_L: %Ld is non-standard C, use %lld
#4840: FILE: tests/unit/cbprintf/main.c:443:
+	rc = rawprf("/%Ld/", max);
```
Please review all the failing lint checks.

printk test seems like it needs some minor adjustments as it's failing everywhere.

**Comment by pabigot** [comment]
> This looks fine to me.
> Format of null pointers diverges: `COMPLETE` uses `(nil)` following Linux libc, while `NANO` uses `0x0` because detecting null and emitting `(nil)` increases memory significantly from the previous footprint.
> That much? I would have expected 10-15 bytes of text.

That motivated me to try harder, and by refactoring a little it's only 12 bytes more.

**Comment by pabigot** [comment]
> > Format of null pointers diverges: `COMPLETE` uses `(nil)` following Linux libc, while `NANO` uses `0x0` because detecting null and emitting `(nil)` increases memory significantly from the previous footprint.
> That much? I would have expected 10-15 bytes of text.

That motivated me to try harder, and by refactoring a little it's only 12 bytes more.  So that difference has been removed: both `COMPLETE` and `NANO` format null pointers as `(nil)`.

File: tests/kernel/common/src/printk.c (hunk 1 above)
Comment (pabigot) [reply tests/kernel/common/src/printk.c:32]: Yes, I'd missed the change to the pointer format in that test.

File: tests/unit/cbprintf/main.c (hunk 2 above)
Comment (pabigot) [reply tests/unit/cbprintf/main.c:98]: I'm not trying to test whether sizeof(int) < 8, I'm trying to support sizeof(int) == 8, in the belief that someday somebody might want Zephyr to run on some DSP-like ILP64 system.

The diagnostic is

    WARNING:TYPECAST_INT_CONSTANT: Unnecessary typecast of c90 int constant

but in fact it is necessary to cast: if the cast is removed the assignment produces warnings that the 64-bit constant was truncated.

There's nothing wrong with the code (there's nothing wrong with the cast), it's just checkpatch making assumptions that aren't relevant in this special case.

Similarly the test is verifying that `%Ld` is properly handled by the converter: i.e. it is detected and passed through unchanged.  This again is checkpatch making assumptions that any string containing an invalid format specifier in any context must have been meant to be a format specifier:

```
-:4889: WARNING:PRINTF_L: %Ld is non-standard C, use %lld
#4889: FILE: tests/unit/cbprintf/main.c:445:
+	zassert_equal(strncmp("/%Ld/", buf, rc), 0, NULL);
```

Here it's complaining that it's being passed to `strncmp`.  checkpatch is wrong to complain about this.

If you prefer we can eliminate these complaints by (a) not being prepared to support ILP64, and/or (b) not testing handling of undefined format combinations.  But I'd rather just ignore checkpatch's whingeing.

**Comment by npitre** [comment]
> If you prefer we can eliminate these complaints by (a) not being prepared to support ILP64, and/or (b) not testing handling of undefined format combinations.  But I'd rather just ignore checkpatch's whingeing.

ILP64 should probably be considered only the day they're needed.

There are many more code instances where such considerations would be 
required. Better do that all at once in a unified way.

IMHO of course.

**Comment by andrewboie** [comment]
> If you prefer we can eliminate these complaints by (a) not being prepared to support ILP64, and/or (b) not testing handling of undefined format combinations. But I'd rather just ignore checkpatch's whingeing.
> ILP64 should probably be considered only the day they're needed. There are many more code instances where such considerations would be required. Better do that all at once in a unified way. IMHO of course.

I'm inclined to agree with @npitre here.
I also don't really care that much.

**Comment by pabigot** [comment]
> I also don't really care that much.

OK, since nobody objects strongly I'll leave it in.  The whole solution was designed to be ready for ILP64, and I'd rather not go through and take out everything that specifically supports it.

Compliance failures are known and explained; tests pass.  Anything else to do?
