### PR TITLE
eDMA loop sg mode and I2S LPUART driver

### LINKED ISSUE #70777: I2S MCUX on IMXRT1176 causes DMA error when TX and RX are used simultanously
I've been testing I2S MCUX on IMXRT1176 and come across a problem with using TX and RX channels at the same time(when used separately there is no problem). Proicessor seem to get stuck in handling dma_mcux_edma_error_irq_handler. When looked into dma registers I found out that at some point the TX channel (DMA 0 channel) got the DADDR changed into invalid but when I set the watchpoint on the address there is no break therefore it wasn't changed explicitly.

(gdb) c
Continuing.

Hardware watchpoint 4: *0x40071010

Old value = 1077952544
New value = 0
EDMA_TcdReset (tcd=tcd@entry=0x40071000) at /home/radekp/projects/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/edma/fsl_edma.c:459
459	    tcd->DLAST_SGA = 0U;
(gdb) x/16w 0x40071000
0x40071000:	0x00000000	0x00000000	0x00000000	0x00000000
0x40071010:	0x00000000	0x00000000	0x80000180	0x0372000a
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa5894	0x006c0002	0x80000200	0x03720012
(gdb) c
Continuing.

Hardware watchpoint 4: *0x40071010

Old value = 0
New value = 1077952544
0x3003ce9c in EDMA_InstallTCD (base=<optimized out>, channel=<optimized out>, tcd=0x80000140 <tcdpool>) at /home/radekp/projects/zephyrproject/modules/hal/nxp/mcux/mcux-sdk/drivers/edma/fsl_edma.c:101
101	    base->TCD[channel].DOFF          = tcd->DOFF;
(gdb) x/16w 0x40071000
0x40071000:	0x80aa6734	0x01010002	0x00000002	0x00000000
0x40071010:	0x40404020	0x00000000	0x00000000	0x00000000
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa5894	0x006c0002	0x80000200	0x03720012
(gdb) c
Continuing.

Breakpoint 1, dma_mcux_edma_reload (dev=0x3004c4b0 <__device_dts_ord_486>, channel=0, src=2158649424, dst=1077952544, size=1764) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:476
476		struct call_back *data = DEV_CHANNEL_DATA(dev, channel);
(gdb) x/16w 0x40071000
0x40071000:	0x80aa6734	0x01010002	0x00000002	0x00000000
0x40071010:	0x40404020	0x03720000	0x80000160	0x0372000a
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa5894	0x006c0002	0x80000200	0x03720012
(gdb) c
Continuing.

Breakpoint 1, dma_mcux_edma_reload (dev=0x3004c4b0 <__device_dts_ord_486>, channel=1, src=1077952672, dst=2158645896, size=1764) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:476
476		struct call_back *data = DEV_CHANNEL_DATA(dev, channel);
(gdb) x/16w 0x40071000
0x40071000:	0x80aa67a2	0x01010002	0x00000002	0x00000000
0x40071010:	0x40404020	0x033b0000	0x80000160	0x03720012
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa596c	0x03720002	0x800001e0	0x0372000a
(gdb) c
Continuing.

Breakpoint 1, dma_mcux_edma_reload (dev=0x3004c4b0 <__device_dts_ord_486>, channel=1, src=1077952672, dst=2158644132, size=1764) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:476
476		struct call_back *data = DEV_CHANNEL_DATA(dev, channel);
(gdb) x/16w 0x40071000
0x40071000:	0x80aa67b2	0x01010002	0x00000002	0x00000000
0x40071010:	0x40404020	0x03330000	0x80000160	0x03720012
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa596c	0x03720002	0x800001e0	0x03720012
(gdb) c
Continuing.

Breakpoint 2, dma_mcux_edma_irq_handler (dev=0x3004c4b0 <__device_dts_ord_486>, channel=0) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:191
191		uint32_t hw_channel = dma_mcux_edma_add_channel_gap(dev, channel);
(gdb) x/16w 0x40071000
0x40071000:	0x80aa605a	0x01010002	0x00000002	0x00000000
0x40071010:	0x40404020	0x036d0000	0x80000180	0x0372000a
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa5f7c	0x006a0002	0x800001e0	0x03720012
(gdb) c
Continuing.

Breakpoint 2, dma_mcux_edma_irq_handler (dev=0x3004c4b0 <__device_dts_ord_486>, channel=0) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:195
195			LOG_DBG("IRQ OCCURRED");
(gdb) x/16w 0x40071000
0x40071000:	0x80aa605e	0x01010002	0x00000002	0x00000000
0x40071010:	0x40404020	0x036b0000	0x80000180	0x0372000a
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa5f80	0x00680002	0x800001e0	0x03720012
(gdb) c
Continuing.

Breakpoint 2, dma_mcux_edma_irq_handler (dev=0x3004c4b0 <__device_dts_ord_486>, channel=1) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:191
191		uint32_t hw_channel = dma_mcux_edma_add_channel_gap(dev, channel);
(gdb) x/16w 0x40071000
0x40071000:	0x80aa6132	0x01010002	0x00000002	0x00000000
0x40071010:	0x40404020	0x03010000	0x80000180	0x0372000a
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa528c	0x03700002	0x80000200	0x03720012
(gdb) c
Continuing.

Breakpoint 2, dma_mcux_edma_irq_handler (dev=0x3004c4b0 <__device_dts_ord_486>, channel=1) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:195
195			LOG_DBG("IRQ OCCURRED");
(gdb) x/16w 0x40071000
0x40071000:	0x80aa6136	0x01010002	0x00000002	0x00000000
0x40071010:	0x40404020	0x02ff0000	0x80000180	0x0372000a
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa5290	0x036e0002	0x80000200	0x03720012
(gdb) c
Continuing.

Breakpoint 1, dma_mcux_edma_reload (dev=0x3004c4b0 <__device_dts_ord_486>, channel=1, src=1077952672, dst=2158651188, size=1764) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:476
476		struct call_back *data = DEV_CHANNEL_DATA(dev, channel);
(gdb) x/16w 0x40071000
0x40071000:	0x80aa616a	0x01010002	0x00000002	0x00000000
0x40071010:	**0x40404020**	0x02e50000	0x80000180	0x0372000a
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa52c4	0x03540002	0x80000200	0x03720012
(gdb) c
Continuing.

Breakpoint 2, dma_mcux_edma_irq_handler (dev=0x3004c4b0 <__device_dts_ord_486>, channel=0) at /home/radekp/projects/zephyrproject/zephyr/drivers/dma/dma_mcux_edma.c:191
191		uint32_t hw_channel = dma_mcux_edma_add_channel_gap(dev, channel);
(gdb) x/16w 0x40071000
0x40071000:	0x80aa6734	0x01010002	0x00000002	0x00000000
0x40071010:	**0xc04041a0**	0x03720000	0x80000180	0x0372008a
0x40071020:	0x404040a0	0x01010000	0x00000002	0x00000000
0x40071030:	0x80aa5894	0x006c0002	0x80000200	0x03720012
(gdb) 

After that line CPU is stuck on handling dma_mcux_edma_error_irq_handler

### LINKED ISSUE #78291: NXP: driver: nxp,kinetis-lpuart: Async API issues at high speed on imxrt1040 series
**Describe the bug**
Background in additional comments to keep this section short.

After chasing issues for a while we went back to basics and loaded up the `test/drivers/uart/uart_async_api` ZTEST to validate that the IMXRT1040's UART driver is operating well.
We configured it for 1,843,200 baud with loopback enabled on `lpuart8` (overlay based on IMXRT EVK overlays) and the test start crashing/failing, we found any baudrate higher then 1,000,000 would fail (see log in log section). 

At baud rates below 1 mega baud, the tests pass as expected (testing 460,800 & 700,000 both passed). I don't think the test is supposed to be baud rate sensitive but please tell me if this is normal and not indicative of a driver issue.

**To Reproduce**

1. Open `tests/drivers/uart/uart_async_api`
2. Add a relevant overlay for a imxrt10xx based board with a high baudrate and loopback enabled
3. Build and run the test on hardware

**Expected behavior**
Async and ISR based APIs to both work reliably at any supported baud rate, and the driver tests to pass at any supported baud rate.

**Impact**
This is preventing us from using the DMA with the IMXRTs UARTs which is causing various issues for us, our inter-processor UART links are unreliable on ISR based UART implementations owing to data overrun issues on data bursts. Additionally on our WS2812 UART based driver we are experiencing occasional LED glitches due to transmission hitching which occurs when the ISR can't keep up.

**Logs and console output**
Error:  
```
*** Booting Zephyr OS build v3.7.0-2556-g884a4e5a35f3 ***
Running TESTSUITE uart_async_chain_read
===================================================================
E: No buffers to release from RX DMA!
E: No buffers to release from RX DMA!
START - test_chained_read
E: Got error : -5

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:348: test_chained_read_callback: rx_data_idx + evt->data.rx.len <= sizeof(chained_cpy_buf) is false

ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/kernel/sched.c:1430
        aborting essential thread 0x20002908
E: r0/a1:  0x00000004  r1/a2:  0x00000596  r2/a3:  0x40184000
E: r3/a4:  0x00000004 r12/ip:  0x00000000 r14/lr:  0x60009aa7
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x6000bc44
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x20002908 (sysworkq)
E: Halting system

```

This error seems to imply the test received back more data when it sent implying there is extra bytes coming in or going out.

**Environment (please complete the following information):**

 - OS: Windows
 - Zephyr SDK
 - 884a4e5a35f3aabd804f74b9e6f31a25eda5be7c

**Additional Notes**
During testing of a larger system which uses high speed UARTs we had issues using the UART driver in async mode, after more testing we found that the IMXRT1040 UARTs do not behave reliably at speeds in excess of 400,000 baud. In our example we were driving Neopixels using a UART TX with signal inversion at 8,000,000 baud (which works out as 1 frame per bit on a WS2812B) and we were seeing on the bus the first few transmission bursts had all the data as zero, but when we stepped through the code the transmissions would come out uncorrupted.

### PR DESCRIPTION
**Pull request by Raymond0225**
This patch is addressing these issues:

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/58888
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/70777
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/78291

Tests done:
I2S speed test on RT1170 EVK
uart async api test on RT1170 EVK with bandrate 115200, 1000000 and 2000000bps

Note that:
Please set CONFIG_TEST_USERSPACE=n when you do test on RT1170 EVK or
you will get "write access denied" issue.  It is another issue not
related to LPUART and eDMA drivers.

### CODE REVIEW

**Comment by SynchronicIT** [comment]
For the LPUART driver, in our real-life application, we tested the proposed solution and noticed an instability. It depends on the TCD queue size. When a certain amount "x" of buffers is consumed and the next buffer should be used, the LPUART or DMA simply stops. 

CONFIG_DMA_TCD_QUEUE_SIZE=2 gave 4 working buffer updates 
CONFIG_DMA_TCD_QUEUE_SIZE=3 gave 5 working buffer updates 
CONFIG_DMA_TCD_QUEUE_SIZE=4 gave 1 working buffer updates (just the initial one..)
CONFIG_DMA_TCD_QUEUE_SIZE=5 gave 3 working buffer updates 
CONFIG_DMA_TCD_QUEUE_SIZE=6 gave 1 working buffer updates (just the initial one..)
CONFIG_DMA_TCD_QUEUE_SIZE=7 gave 2 working buffer updates
...
CONFIG_DMA_TCD_QUEUE_SIZE=16 gave 5 working buffer updates

And although it seems a bit random, I tried each value at least 5 times and every time exact the same amount, although the uart input was random (at 1mbit/s in this case). 

I hope this rings a bell...

**Comment by matt-wood-ct** [comment]
Possibly silly question, does a similar issue apply to the lpspi implementation? I've been having a lot of trouble getting that writing properly with dma too. In my case I'm seeing junk data coming out the spi when using it with dma channels configured

File: drivers/serial/uart_mcux_lpuart.c [hunk 1]
```diff
@@ -616,37 +616,22 @@ static int uart_mcux_lpuart_dma_replace_rx_buffer(const struct device *dev)
 	struct mcux_lpuart_data *data = (struct mcux_lpuart_data *)dev->data;
 	const struct mcux_lpuart_config *config = dev->config;
 	LPUART_Type *lpuart = config->base;
-	struct mcux_lpuart_rx_dma_params *rx_dma_params = &data->async.rx_dma_params;
+	// struct mcux_lpuart_rx_dma_params *rx_dma_params = &data->async.rx_dma_params;
```
Comment (hakehuang) [inline drivers/serial/uart_mcux_lpuart.c:619]: why remove this, yo actually change the rx_dma_params

File: drivers/serial/uart_mcux_lpuart.c [hunk 2]
```diff
@@ -873,6 +865,7 @@ static int mcux_lpuart_rx_buf_rsp(const struct device *dev, uint8_t *buf, size_t
 	assert(data->async.next_rx_buffer_len == 0);
 	data->async.next_rx_buffer = buf;
 	data->async.next_rx_buffer_len = len;
+    uart_mcux_lpuart_dma_replace_rx_buffer(dev);
```
Comment (hakehuang) [inline drivers/serial/uart_mcux_lpuart.c:868]: you code indent is wrong should be 8

File: drivers/serial/uart_mcux_lpuart.c [hunk 3]
```diff
@@ -616,37 +616,22 @@ static int uart_mcux_lpuart_dma_replace_rx_buffer(const struct device *dev)
...
-	rx_dma_params->offset = 0;
-	rx_dma_params->counter = 0;
-	data->async.next_rx_buffer = NULL;
-	data->async.next_rx_buffer_len = 0U;
 
 	const int success =
 		dma_reload(config->rx_dma_config.dma_dev, config->rx_dma_config.dma_channel,
-			   LPUART_GetDataRegisterAddress(lpuart), (uint32_t)rx_dma_params->buf,
-			   rx_dma_params->buf_len);
+			   LPUART_GetDataRegisterAddress(lpuart), (uint32_t)data->async.next_rx_buffer,
```
Comment (hakehuang) [inline drivers/serial/uart_mcux_lpuart.c:629]: you change the logic: here:
old:
dma_reload next buffer, request buffer update.
now:
request buffer update, so the next is replaced before use, and then you dma_reload the net buffer, which means the original next buffer is not used at all.

**Comment by DerekSnell** [comment]
Hi @Raymond0225 ,
I used your eDMA and I2S driver update to test on the FRDM-MCXN947 board.  This is based on the open PR [Add mcxn10 sai module support](https://github.com/zephyrproject-rtos/zephyr/pull/77534).  I had to modify your eDMA driver to support v4, and shared [my branch](https://github.com/nxp-upstream/zephyr/tree/eDMA_loop_SG_N947).  But the `i2s_speed` test passes on FRDM-MCXN947 board in this branch.

Thanks

File: drivers/serial/uart_mcux_lpuart.c (hunk 1 above)
Comment (Raymond0225) [reply drivers/serial/uart_mcux_lpuart.c:619]: I did not change it.  next_rx_buffer is a member of data->async

File: drivers/serial/uart_mcux_lpuart.c (hunk 3 above)
Comment (Raymond0225) [reply drivers/serial/uart_mcux_lpuart.c:629]: yes, I reverted part of the code in your last PR. it is because we have to remain buf/buf_len until DMA callback, at the same time, we need submit next_rx_buf to DMA.  The original logic (before your PR  https://github.com/zephyrproject-rtos/zephyr/pull/79325/files) works well. So I use it as before.

**Comment by Raymond0225** [comment]
> Hi @Raymond0225 , I used your eDMA and I2S driver update to test on the FRDM-MCXN947 board. This is based on the open PR [Add mcxn10 sai module support](https://github.com/zephyrproject-rtos/zephyr/pull/77534). I had to modify your eDMA driver to support v4, and shared [my branch](https://github.com/nxp-upstream/zephyr/tree/eDMA_loop_SG_N947). But the `i2s_speed` test passes on FRDM-MCXN947 board in this branch.
> 
> Thanks

thanks Derek.  I wrote the code for DMA V4 based on an old version. I will update the code based on your modifications.

**Comment by Raymond0225** [comment]
> For the LPUART driver, in our real-life application, we tested the proposed solution and noticed an instability. It depends on the TCD queue size. When a certain amount "x" of buffers is consumed and the next buffer should be used, the LPUART or DMA simply stops.
> 
> CONFIG_DMA_TCD_QUEUE_SIZE=2 gave 4 working buffer updates CONFIG_DMA_TCD_QUEUE_SIZE=3 gave 5 working buffer updates CONFIG_DMA_TCD_QUEUE_SIZE=4 gave 1 working buffer updates (just the initial one..) CONFIG_DMA_TCD_QUEUE_SIZE=5 gave 3 working buffer updates CONFIG_DMA_TCD_QUEUE_SIZE=6 gave 1 working buffer updates (just the initial one..) CONFIG_DMA_TCD_QUEUE_SIZE=7 gave 2 working buffer updates ... CONFIG_DMA_TCD_QUEUE_SIZE=16 gave 5 working buffer updates
> 
> And although it seems a bit random, I tried each value at least 5 times and every time exact the same amount, although the uart input was random (at 1mbit/s in this case).
> 
> CONFIG_DMA_TCD_QUEUE_SIZE=1 actually gave the most stable result, and it looks like your initializing more buffers than needed at: zephyr/drivers/dma/dma_mcux_edma.c:391 (the max queue size instead of the requested block_count...
> 
> I hope this rings a bell...

Thanks for your feedback. I don't understand what you said. I do use all TCDs and linked them together. Can you elaborate how to reproduce the "stops" issue you mentioned here?

File: drivers/serial/uart_mcux_lpuart.c (hunk 2 above)
Comment (Raymond0225) [reply drivers/serial/uart_mcux_lpuart.c:868]: thanks, I will reformat all the related indent and whitespaces.

**Comment by dleach02** [comment]
@Raymond0225 please clean up the file changes to remove the spaces at beginning of lines. The Zephyr coding standard is to use tabs.

**Comment by Raymond0225** [comment]
> @Raymond0225 please clean up the file changes to remove the spaces at beginning of lines. The Zephyr coding standard is to use tabs.

thanks. I am cleaning up the code, will update the PR later.

**Comment by SynchronicIT** [comment]
> Thanks for your feedback. I don't understand what you said. I do use all TCDs and linked them together. Can you elaborate how to reproduce the "stops" issue you mentioned here?

We are building a uart to usb bridge, similar to the usb example. As we need to switch both the DTR and baud rate in real-time, we're using the next-gen usb driver (and have made some fixes for it to make it more robust). 
To get the lowest latency, we are coupling the usb uart and physical uart in the irq and async callback functions. 
On other chipset's we used solely the fifo / irq method, but due to the small fifo on the RT1060, we need to use the async/dma. 

Concerning the Rx and TCDs: 
I'm feeding the physical uart now with a data set every 1[s] of 256 bytes at 1mbit and 2 mbit and provide the async driver with buffers of 2KB. If I use anything else than a single TCD by setting it in the config (which reflects the .block_count == 1) I do get several requests for new buffers and buffer release events. But after the mentioned number the requests and releases stop, but any irq from the DMA stops. The uart irq keeps on running (giving overflow errors of course). It reproduced very well for the numbers given, which suggests there is a good relationship. 
I don't have a simplified example to test it with, which makes it a bit difficult to hand it over. 

Concerning  the Tx side: 
Having the Tx side from a uart_fifo_irq (of the usb) directly towards the physical uart using the async. (thus not using a separate thread to handle the copy / forwarding with the goal to minimize the latency) The Tx Side of the async seems to be giving inconsistent data output, as with too much data, the uart output becomes 10 bits '0' ( a break instead of start - 8 bytes - stop). I've added atomic bits and I have a "uart_tx(..)" in the TX_READY event handling. I'm not sure if that is even allowed. 

Concerning  switching the baudrate: 
When switching the baud rate, the lpuart driver completely reinitializes the driver. In case the DMA is still active, re-enabling the rx dma (uart_rx(...)) fails as the DMA is still active. I added code to forcefully stop the DMA before calling the configure and restart the uart_rx dma. I see two problems. The baud-rate doesn't seem to switch properly (as the data is partially received (although the baudrate is a factor 4 lower), and the buffers are not flushed ( dma seems to continue where it was previously). 


Perhaps we could take this discussion offline / beyond this github issue / pull-request.

File: drivers/dma/dma_mcux_edma.c
Comment (mmahadevan108) [inline drivers/dma/dma_mcux_edma.c:1]: Please squash this commit with the earlier commit that changes this file.

**Comment by Raymond0225** [comment]
> > Thanks for your feedback. I don't understand what you said. I do use all TCDs and linked them together. Can you elaborate how to reproduce the "stops" issue you mentioned here?
> 
> We are building a uart to usb bridge, similar to the usb example. As we need to switch both the DTR and baud rate in real-time, we're using the next-gen usb driver (and have made some fixes for it to make it more robust). To get the lowest latency, we are coupling the usb uart and physical uart in the irq and async callback functions. On other chipset's we used solely the fifo / irq method, but due to the small fifo on the RT1060, we need to use the async/dma.
> 
> Concerning the Rx and TCDs: I'm feeding the physical uart now with a data set every 1[s] of 256 bytes at 1mbit and 2 mbit and provide the async driver with buffers of 2KB. If I use anything else than a single TCD by setting it in the config (which reflects the .block_count == 1) I do get several requests for new buffers and buffer release events. But after the mentioned number the requests and releases stop, but any irq from the DMA stops. The uart irq keeps on running (giving overflow errors of course). It reproduced very well for the numbers given, which suggests there is a good relationship. I don't have a simplified example to test it with, which makes it a bit difficult to hand it over.
> 
> Concerning the Tx side: Having the Tx side from a uart_fifo_irq (of the usb) directly towards the physical uart using the async. (thus not using a separate thread to handle the copy / forwarding with the goal to minimize the latency) The Tx Side of the async seems to be giving inconsistent data output, as with too much data, the uart output becomes 10 bits '0' ( a break instead of start - 8 bytes - stop). I've added atomic bits and I have a "uart_tx(..)" in the TX_READY event handling. I'm not sure if that is even allowed.
> 
> Concerning switching the baudrate: When switching the baud rate, the lpuart driver completely reinitializes the driver. In case the DMA is still active, re-enabling the rx dma (uart_rx(...)) fails as the DMA is still active. I added code to forcefully stop the DMA before calling the configure and restart the uart_rx dma. I see two problems. The baud-rate doesn't seem to switch properly (as the data is partially received (although the baudrate is a factor 4 lower), and the buffers are not flushed ( dma seems to continue where it was previously).
> 
> Perhaps we could take this discussion offline / beyond this github issue / pull-request.

thanks for your feedback. I suggest you have a look at the the test code of uart_async_api test case, there is a function "test_double_buffer" which may be close to your use case.  block_count is only valid during DMA configuration. I suggest you set it as 1. after that, each time when driver request user rx buffer, callback function will be triggered. Driver would not ask for new buffer until current rx buffer is filled fully. There may be multi rx ready event between 2 buf requests.

**Comment by SynchronicIT** [comment]
> thanks for your feedback. I suggest you have a look at the the test code of uart_async_api test case, there is a function "test_double_buffer" which may be close to your use case. block_count is only valid during DMA configuration. I suggest you set it as 1. after that, each time when driver request user rx buffer, callback function will be triggered. Driver would not ask for new buffer until current rx buffer is filled fully. There may be multi rx ready event between 2 buf requests. 2 TCDs usually is enough. It is not related to block_count. I suggest set block_count to 1 whatever how many TCD you set.


I've ran the proposed tests. The test succeeds  only when using the TCM regions for the buffers. Is this mandatory? 
If the baudrate is higher than 115200 the first tests fail. Also the tests only simulate ideal situation. (Only transmit when the Rx is handled completely). . During the tests i do see the error "No buffers to release from RX DMA!"
I'll update the buffers to reside in the TCM to see if that solves my challenges. 

Tx seems to be working now, by moving "uart_tx(..)" to a work task instead of directly in the callback. This is aparently not allowed. (perhaps something to add to the documentation)

Switching baudrate at runtime while DMA is active is still a challenge. Not sure what is actually failing (the dma buffers or the uart settings). Using the fifo api switching baudrate works well.

**Comment by hakehuang** [comment]
@Raymond0225 , I rebase you pr to the latest zephyr code. and test on mimxrt1170_evk_cm7 it fails as below log

scripts/twister --device-testing --device-serial /dev/ttyACM0 -T tests/drivers/uart/uart_async_api/

```
uart:~$ *** Booting Zephyr OS build (tainted) v4.0.0-rc1-15-g359a81e7db80 ***
Running TESTSUITE uart_async_chain_read
===================================================================
E: No buffers to release from RX DMA!
E: No buffers to release from RX DMA!
START - test_chained_read

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:355: test_chained_read_callback: rx_data_idx + evt->data.rx.len <= sizeof(chained_cpy_buf) is false

ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/kernel/sched.c:1393
        aborting essential thread 0x80002580
E: r0/a1:  0x00000004  r1/a2:  0x00000571  r2/a3:  0x4007c000
E: r3/a4:  0x00000004 r12/ip:  0x00000000 r14/lr:  0x3000a55b
E:  xpsr:  0x21000000
E: Faulting instruction address (r15/pc): 0x3000b858
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x80002580 (sysworkq)
E: Halting system

```

**Comment by DerekSnell** [comment]
Hi @SynchronicIT ,
> The test succeeds only when using the TCM regions for the buffers. Is this mandatory? 

The buffers used by the DMA need to be in non-cached memory, otherwise there may be a cache coherency issue.  The TCMs are not cached, which is one option for the buffers.  Another option is to use slower memories like external SDRAM or internal OCRAM, but the buffers need to be placed in a `nocache` region.  On the RT1xxx platform, the cache is only used by the CPU.  Other masters in the SOC like the DMA do not use the cache.  This can lead to a cache coherency issue where the DMA is reading/writing to the physical RAM, but the CPU is accessing the cache.

> Switching baudrate at runtime while DMA is active is still a challenge. 

Your use-case to dynamically change the baud rate is beyond the scope of this PR.  You can create a [GitHub Discussion](https://github.com/zephyrproject-rtos/zephyr/discussions) for that separate topic.

Thanks for your feedback with this PR.

File: drivers/i2s/i2s_mcux_sai.c
Comment (DerekSnell) [inline drivers/i2s/i2s_mcux_sai.c:1]: Hi @Raymond0225 ,
@hakehuang raised a great point offline.  The changes here to i2s_mcux_sai.c do not set the `cyclic` bit.  It appears this driver is not using the new loop SG feature in the eDMA driver.  Is that intended?

**Comment by Raymond0225** [comment]
> @Raymond0225 , I rebase you pr to the latest zephyr code. and test on mimxrt1170_evk_cm7 it fails as below log
> 
> scripts/twister --device-testing --device-serial /dev/ttyACM0 -T tests/drivers/uart/uart_async_api/
> 
> ```
> uart:~$ *** Booting Zephyr OS build (tainted) v4.0.0-rc1-15-g359a81e7db80 ***
> Running TESTSUITE uart_async_chain_read
> ===================================================================
> E: No buffers to release from RX DMA!
> E: No buffers to release from RX DMA!
> START - test_chained_read
> 
>     Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:355: test_chained_read_callback: rx_data_idx + evt->data.rx.len <= sizeof(chained_cpy_buf) is false
> 
> ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/kernel/sched.c:1393
>         aborting essential thread 0x80002580
> E: r0/a1:  0x00000004  r1/a2:  0x00000571  r2/a3:  0x4007c000
> E: r3/a4:  0x00000004 r12/ip:  0x00000000 r14/lr:  0x3000a55b
> E:  xpsr:  0x21000000
> E: Faulting instruction address (r15/pc): 0x3000b858
> E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
> E: Current thread: 0x80002580 (sysworkq)
> E: Halting system
> ```
> 
> last commit after rebase ''' commit 359a81e7db8074487a1d85bf059848a6e92bfac4 (HEAD -> pr_80584_edma_async) Author: Raymond [raymond.lei@nxp.com](mailto:raymond.lei@nxp.com) Date: Wed Oct 30 15:31:19 2024 -0500
> 
> ```
> drivers: dma: edma: Fix compile issue for eDMA V4
> 
> Some data structures are different between eDMA and eDMA V4, use
> different macros defined in SDK driver for each of them.
> Make indent/leading space modifications.
> 
> Signed-off-by: Raymond <raymond.lei@nxp.com>
> ```
> 
> '''

Thanks Hake. I got same error when I try to put TCD pool to DTCM. it is because some fields inside edma_tcd_t is not initialized.
I will fix it in the following commit.  I add a line "memset(&DEV_CFG(dev)->tcdpool[channel][i],0,sizeof(DEV_CFG(dev)->tcdpool[channel][i]));" during TCD pool initialization.

File: drivers/dma/dma_mcux_edma.c [hunk 4]
```diff
@@ -358,26 +374,93 @@ static int dma_mcux_edma_configure(const struct device *dev, uint32_t channel,
...
 
 	if (block_config->source_gather_en || block_config->dest_scatter_en) {
-		EDMA_InstallTCDMemory(p_handle, DEV_CFG(dev)->tcdpool[channel],
-				      CONFIG_DMA_TCD_QUEUE_SIZE);
+        if (config->cyclic) {
+		/* Loop SG mode */
+		data->transfer_settings.write_idx = 0;
+		data->transfer_settings.empty_tcds = CONFIG_DMA_TCD_QUEUE_SIZE;
+
+		EDMA_PrepareTransfer(
```
Comment (danieldegrasse) [inline drivers/dma/dma_mcux_edma.c:382]: I'm unclear why we prepare a transfer here, and then configure each TCD using it. It seems like we will overwrite the `SADDR`, `DADDR`, `CITER`, and `BITER` fields later on in the loop below. Why not just initialize the TCDs directly in that loop? We could set `DLAST_SGA` directly as well in the loop below, rather than calling `EDMA_TcdSetTransferConfig`

File: drivers/dma/dma_mcux_edma.c [hunk 5]
```diff
@@ -507,29 +614,119 @@ static int dma_mcux_edma_reload(const struct device *dev, uint32_t channel,
...
+#endif
+
+		/* Manaually stop DMA whatever it is running or already stopped(Automatically)
+		   Make sure the code between EDMA_DisableChannelRequest and EDMA_EnableChannelRequest is minimum.
+		*/
+		EDMA_DisableChannelRequest(DEV_BASE(dev),channel);
+#ifdef CONFIG_DMA_MCUX_EDMA
+		while(DEV_BASE(dev)->TCD[channel].CSR & DMA_CSR_ACTIVE_MASK)
+#elif (CONFIG_DMA_MCUX_EDMA_V3 || CONFIG_DMA_MCUX_EDMA_V4)
+		while(DEV_BASE(dev)->CH[channel].TCD_CSR & DMA_CH_CSR_ACTIVE_MASK)
```
Comment (danieldegrasse) [inline drivers/dma/dma_mcux_edma.c:655]: I'm not sure I'm following the logic here- why do we wait until the EDMA is not active here? The `dma_reload` function should simply queue a new buffer into the EDMA (which occurs above) then exit, right? There is no requirement to wait for the DMA to complete execution here.

It seems like at this point we should:
- clear the DREQ bit on the prior TCD, so the next TCD can be loaded
- check the next TCD address, and restart the DMA if `hw_id == sw_id` (as this indicates the TCD we just configured was loaded already, right?)
- otherwise, set the ESG bit to resolve the HW bug, and make sure the DREQ bit is set on the TCD we are queueing

I'm not clear why we need to disable channel requests or wait for the EDMA to be inactive. Shouldn't it be sufficient to configure the TCD, enable the EDMA to load the TCD, then perform the safety check to make sure the EDMA did not load an invalid TCD?

File: drivers/dma/dma_mcux_edma.c [hunk 6]
```diff
@@ -254,6 +266,9 @@ static int dma_mcux_edma_configure(const struct device *dev, uint32_t channel,
 	edma_transfer_type_t transfer_type;
 	unsigned int key;
 	int ret = 0;
+	edma_tcd_t *tcd = NULL;
+
+	tcd = &(DEV_CFG(dev)->tcdpool[channel][data->transfer_settings.write_idx]);
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:271]: no, we don't need initialize tcd here, this line is a typo, I will correct it. thanks

File: drivers/dma/dma_mcux_edma.c [hunk 7]
```diff
@@ -358,26 +374,93 @@ static int dma_mcux_edma_configure(const struct device *dev, uint32_t channel,
...
+
+			/* In some version of SDK driver, major interrupt is not enabled by default.*/
+			EDMA_TcdEnableInterrupts(&DEV_CFG(dev)->tcdpool[channel][i],kEDMA_MajorInterruptEnable);
+		}
+
+		/* Load valid transfer parameters */
+		while (block_config != NULL && data->transfer_settings.write_idx < CONFIG_DMA_TCD_QUEUE_SIZE) {
+
+			tcd = &(DEV_CFG(dev)->tcdpool[channel][data->transfer_settings.write_idx]);
+#if (CONFIG_DMA_MCUX_EDMA || CONFIG_DMA_MCUX_EDMA_V3)
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:406]: good idea, let me try to improve this part of code.

File: drivers/dma/dma_mcux_edma.c [hunk 8]
```diff
@@ -358,26 +374,93 @@ static int dma_mcux_edma_configure(const struct device *dev, uint32_t channel,
...
+			tcd->BITER = block_config->block_size/config->source_data_size;
+			tcd->CITER = block_config->block_size/config->source_data_size;
+			/*Enable auto stop for last transfer.*/
+			if (block_config->next_block == NULL) {
+				tcd->CSR |= DMA_CSR_DREQ(1U);
+			} else {
+				tcd->CSR &= ~DMA_CSR_DREQ(1U);
+			}
+#elif CONFIG_DMA_MCUX_EDMA_V4
+			EDMA_TCD_SADDR(tcd,kEDMA_EDMA4Flag) = block_config->source_address;
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:418]: Good idea

File: drivers/dma/dma_mcux_edma.c [hunk 9]
```diff
@@ -358,26 +374,93 @@ static int dma_mcux_edma_configure(const struct device *dev, uint32_t channel,
...
+			}
+#endif
+
+			data->transfer_settings.write_idx =
+				(data->transfer_settings.write_idx + 1)%CONFIG_DMA_TCD_QUEUE_SIZE;
+			data->transfer_settings.empty_tcds--;
+			block_config = block_config->next_block;
+
+
+		}
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:436]: good idea

File: drivers/dma/dma_mcux_edma.c [hunk 10]
```diff
@@ -492,10 +575,34 @@ static int dma_mcux_edma_resume(const struct device *dev, uint32_t channel)
 }
 
 
+static void dma_mcux_edma_update_hw_tcd(const struct device *dev, uint32_t channel,
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:578]: have done on new commit ,thanks for your suggestions.

File: drivers/dma/dma_mcux_edma.c [hunk 11]
```diff
@@ -507,29 +614,119 @@ static int dma_mcux_edma_reload(const struct device *dev, uint32_t channel,
...
-
-	const status_t submit_status =
+		/* Convert size into major loop count */
+		size = size/data->transfer_settings.dest_data_size;
+
+		/* Append the transfer normally */
+		tcd = &(DEV_CFG(dev)->tcdpool[channel][data->transfer_settings.write_idx]);
+		pre_tcd = &(DEV_CFG(dev)->tcdpool[channel][(data->transfer_settings.write_idx - 1)%CONFIG_DMA_TCD_QUEUE_SIZE]);
+#if (CONFIG_DMA_MCUX_EDMA || CONFIG_DMA_MCUX_EDMA_V3)
+		tcd->SADDR = src;
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:631]: done

File: drivers/dma/dma_mcux_edma.c [hunk 12]
```diff
@@ -507,29 +614,119 @@ static int dma_mcux_edma_reload(const struct device *dev, uint32_t channel,
...
+#elif (CONFIG_DMA_MCUX_EDMA_V3 || CONFIG_DMA_MCUX_EDMA_V4)
+		while(DEV_BASE(dev)->CH[channel].TCD_CSR & DMA_CH_CSR_ACTIVE_MASK)
+#endif
+		{
+			;
+		}
+
+		/* Use DLAST_SGA as the HW ID */
+		hw_id = EDMA_GetNextTCDAddress(DEV_EDMA_HANDLE(dev,channel));
+		if (data->transfer_settings.empty_tcds >= CONFIG_DMA_TCD_QUEUE_SIZE || hw_id == sw_id) {
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:663]: yes, I think >=  is better than == :)

File: drivers/dma/dma_mcux_edma.c (hunk 4 above)
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:382]: Just want to use this API in SDK driver instead of writing a new function.
yes, we can write a new function to do it as well.

File: drivers/dma/dma_mcux_edma.c (hunk 5 above)
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:655]: If we do not stop DMA during this "appending procedure", HW ID may change at any time, that is to say, we don't know exactly which TCD DMA is working on.  DMA may have finished all transfers, may be transferring the last one, may be transferring the others, all handling of these conditions are different.
By disable the channel request, we cut off the signal from the peripheral, no more transfer request. DMA stops after current burst finished. Why we wait for DMA to be inactive is because even we cut off the transfer request, there may be a burst transfer is on-going, DMA has its own internal buffer and logics. DMA may modify the same HW reg while CPU is trying to make a modification.

Comment (danieldegrasse) [reply drivers/dma/dma_mcux_edma.c:655]: Ok, that makes sense. Isn't there a risk here though of "drops" in transfers? For example with audio, wouldn't the DMA being inactive here manifest as a momentary pause in the I2S audio stream and therefore a pause in the audio from the codec?

Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:655]: Risk of "drops":
that's why we need make this part of code as short as possible. The longest path of code between EDMA_DisableChannelRequest and EDMA_EnableChannelRequest is in case DMA has finished all transfers and we need rewrite HW regs. Even in this case, all codes to execute are about 10 simple instructions(set value, comparing).  It should be very quick.  On RT1170, SAI has 16 bytes FIFO, given the sample rate: 44K, 2 bytes word, 2 channels, it takes about 90us to full the FIFO.  I think it is much far longer than the execution time of the critical code.

last TCD transfering:
In this case, hw_id should be current writing TCD address, we have code to handle this case:
				/* DMA is running on last transfer. HW has loaded the last one,
				 * we need ensure it's DREQ is cleared.
				 */
				EDMA_EnableAutoStopRequest(DEV_BASE(dev), channel, false);
				LOG_DBG("Last transfer.");_

File: drivers/dma/dma_mcux_edma.c
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:1]: thanks for your feedback. I am not familiar with git commands, I will try to it.

File: drivers/i2s/i2s_mcux_sai.c
Comment (Raymond0225) [reply drivers/i2s/i2s_mcux_sai.c:1]: No, I forgot to enable it. will fix it.

**Review by DerekSnell — CHANGES_REQUESTED** [review]
Hi @Raymond0225 ,
Thank you for all your hard work with these fixes.  

I am only blocking this to see your updates to i2s_mcux_sai.c with the loop SG support.

Otherwise, I see no issues with your updates.  I do think we can improve with comments to help understand how your eDMA driver works, and provided some comments for you to review.

Also, regarding this note in your commit message:
> please set CONFIG_TEST_USERSPACE=n when you do test on RT1170 EVK or
you will get "write access denied" issue.  It is another issue not related to LPUART and eDMA drivers.

It's good to include that detail in the PR description (and I see it is already there), so others are aware how to replicate your test.  But I would not include in the commit message.  Over time, that `CONFIG_TEST_USERSPACE=n` may no longer apply.

And for the PR description, I would point out the `CONFIG_TEST_USERSPACE=n` requirement is specifically for the uart_async_api test.  The drivers in this PR are not impacted by that Kconfig, but the test app for the LPUART driver will fail today with userspace enabled.

Thanks

File: drivers/dma/dma_mcux_edma.c [hunk 13]
```diff
@@ -358,26 +374,93 @@ static int dma_mcux_edma_configure(const struct device *dev, uint32_t channel,
...
+			block_config->block_size, transfer_type);
 
 			const status_t submit_status =
-				EDMA_SubmitTransfer(p_handle, &(data->transferConfig));
+			EDMA_SubmitTransfer(p_handle, &(data->transferConfig));
 			if (submit_status != kStatus_Success) {
-				LOG_ERR("Error submitting EDMA Transfer: 0x%x", submit_status);
-				ret = -EFAULT;
+			LOG_ERR("Error submitting EDMA Transfer: 0x%x", submit_status);
+			ret = -EFAULT;
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c]: These are modifications suggested by the check_compliance script, if i do not make the changes, it will fail the check.

File: drivers/i2s/i2s_mcux_sai.c
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/i2s/i2s_mcux_sai.c:1]: ok

File: drivers/dma/dma_mcux_edma.c [hunk 14]
```diff
@@ -181,7 +188,12 @@ static void nxp_edma_callback(edma_handle_t *handle, void *param, bool transferD
 
 	uint32_t channel = dma_mcux_edma_remove_channel_gap(data->dev, handle->channel);
 
-	if (transferDone) {
+    	if (data->transfer_settings.cyclic) {
+		data->transfer_settings.empty_tcds++;
+		/*In loop mode, DMA is always busy*/
+		data->busy = 1;
+		ret = DMA_STATUS_COMPLETE;
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c:224]: I think we should return "complete" instead of "block". Each time when callback is triggered , it indicate current transfer is completed.

File: drivers/dma/dma_mcux_edma.c [hunk 15]
```diff
@@ -507,29 +614,119 @@ static int dma_mcux_edma_reload(const struct device *dev, uint32_t channel,
...
+		*/
+		EDMA_DisableChannelRequest(DEV_BASE(dev),channel);
+#ifdef CONFIG_DMA_MCUX_EDMA
+		while(DEV_BASE(dev)->TCD[channel].CSR & DMA_CSR_ACTIVE_MASK)
+#elif (CONFIG_DMA_MCUX_EDMA_V3 || CONFIG_DMA_MCUX_EDMA_V4)
+		while(DEV_BASE(dev)->CH[channel].TCD_CSR & DMA_CH_CSR_ACTIVE_MASK)
+#endif
+		{
+			;
+		}
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/dma_mcux_edma.c]: I have submitted new implementation. It passed the compliance check. "while(xxx);" is not recommended by the compliance script.

**Comment by Raymond0225** [comment]
> Hi @Raymond0225 , Thank you for all your hard work with these fixes.
> 
> I am only blocking this to see your updates to i2s_mcux_sai.c with the loop SG support.
> 
> Otherwise, I see no issues with your updates. I do think we can improve with comments to help understand how your eDMA driver works, and provided some comments for you to review.
> 
> Also, regarding this note in your commit message:
> 
> > please set CONFIG_TEST_USERSPACE=n when you do test on RT1170 EVK or
> > you will get "write access denied" issue.  It is another issue not related to LPUART and eDMA drivers.
> 
> It's good to include that detail in the PR description (and I see it is already there), so others are aware how to replicate your test. But I would not include in the commit message. Over time, that `CONFIG_TEST_USERSPACE=n` may no longer apply.
> 
> And for the PR description, I would point out the `CONFIG_TEST_USERSPACE=n` requirement is specifically for the uart_async_api test. The drivers in this PR are not impacted by that Kconfig, but the test app for the LPUART driver will fail today with userspace enabled.
> 
> Thanks

@DerekSnell  Thanks for your comments. I submitted a commit to include all these modifications(only comments and copyright, no logic/function modifications).

File: drivers/dma/dma_mcux_edma.c [hunk 16]
```diff
@@ -357,26 +399,93 @@ static int dma_mcux_edma_configure(const struct device *dev, uint32_t channel,
...
-				LOG_ERR("Error submitting EDMA Transfer: 0x%x", submit_status);
-				ret = -EFAULT;
+			/* Init all TCDs with the para in transfer config and link them. */
+			for (int i = 0; i < CONFIG_DMA_TCD_QUEUE_SIZE; i++) {
+				EDMA_TcdSetTransferConfig(
+					&DEV_CFG(dev)->tcdpool[channel][i], &data->transferConfig,
+					&DEV_CFG(dev)->tcdpool[channel][(i + 1) %
+									CONFIG_DMA_TCD_QUEUE_SIZE]);
+
+				/* Enable Major interrupt.*/
```
Comment (DerekSnell) [inline drivers/dma/dma_mcux_edma.c:427]:
```suggestion
				/* Enable Major loop interrupt.*/
```

File: drivers/dma/dma_mcux_edma.c [hunk 17]
```diff
@@ -357,26 +399,93 @@ static int dma_mcux_edma_configure(const struct device *dev, uint32_t channel,
...
+				}
+
+				data->transfer_settings.write_idx =
+					(data->transfer_settings.write_idx + 1) %
+					CONFIG_DMA_TCD_QUEUE_SIZE;
+				data->transfer_settings.empty_tcds--;
+				block_config = block_config->next_block;
+			}
+
+			if (block_config && data->transfer_settings.empty_tcds == 0) {
```
Comment (DerekSnell) [inline drivers/dma/dma_mcux_edma.c:457]: Should this be:
```suggestion
			if ((block_config != NULL) &&
				(data->transfer_settings.empty_tcds == 0)) {
```

**Review by DerekSnell — CHANGES_REQUESTED** [review]
Much improved, @Raymond0225.  And easier to review now, thank you.

But it still needs a little work.

File: drivers/dma/Kconfig.mcux_edma [hunk 18]
```diff
@@ -44,6 +44,7 @@ config DMA_MCUX_TEST_SLOT_START
 
 config DMA_MCUX_USE_DTCM_FOR_DMA_DESCRIPTORS
 	bool "Use DTCM for DMA descriptors"
+	default y
```
[the remark this answers is not in the document]
Comment (Raymond0225) [reply drivers/dma/Kconfig.mcux_edma:47]: thanks, I am looking into this failure.

**Comment by hakehuang** [comment]
now this PR works on my boards with uart_async_api and edma tests. @Raymond0225  can you enable the i2s on mimxrt1170_evk board in this PR, so that I can run a test with this cyclic dma with i2s.

**Comment by Raymond0225** [comment]
> now this PR works on my boards with uart_async_api and edma tests. @Raymond0225 can you enable the i2s on mimxrt1170_evk board in this PR, so that I can run a test with this cyclic dma with i2s.

To run i2s_speed test on RT1170 EVK, you need HW reworks:

Board-specific details:

MIMXRT1170_EVK:
This board uses CONFIG_I2S_TEST_SEPARATE_DEVICES=y and connects two SAI peripherals by shorting
signals externally on the EVK.  These are the HW changes required to run this test:
	- Remove jumper J8 and resistor R78
	- Short BCLK J9-pin1  (SAI1_RX_BCLK)  to J66-pin1  (SAI4_TX_BCLK)
	- Short SYNC J9-pin5  (SAI1_RX_SYNC)  to J64-pin1  (SAI4_TX_SYNC)
	- Short Data J61-pin1 (SAI1_RX_DATA)  to J63-pin1  (SAI4_TX_DATA)

**Review by DerekSnell — APPROVED** [review]
Great work, @Raymond0225 .  Thanks for all your hard work with this.

File: drivers/dma/dma_mcux_edma.c [hunk 19]
```diff
@@ -507,29 +625,115 @@ static int dma_mcux_edma_reload(const struct device *dev, uint32_t channel,
...
+		}
+
+#ifdef CONFIG_DMA_MCUX_EDMA
+		/* It seems that there is HW issue which may cause ESG bit is cleared.
+		 * This is a workaround. Clear the DONE bit before setting ESG bit.
+		 */
+		EDMA_ClearChannelStatusFlags(DEV_BASE(dev), channel, kEDMA_DoneFlag);
+		EDMA_HW_TCD_CSR(dev, channel) |= DMA_CSR_ESG_MASK;
+#elif (CONFIG_DMA_MCUX_EDMA_V3 || CONFIG_DMA_MCUX_EDMA_V4)
+		/*We have not verified if this issue exist on V3/V4 HW, jut place a holder here. */
```
Comment (danieldegrasse) [inline drivers/dma/dma_mcux_edma.c:700]:
```suggestion
		/*We have not verified if this issue exist on V3/V4 HW, just place a holder here. */
```

**Review by danieldegrasse — APPROVED** [review]
A few minor (nonblocking) nits, overall change looks good to me though. Thanks for your work here!

**Review by dleach02 — APPROVED** [review]

**Comment by RadekPolyend** [comment]
This PR breaks SAI driver

**Comment by DerekSnell** [comment]
Hi @RadekPolyend ,
This PR was tested with the [i2s_speed test](https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/i2s/i2s_speed) on the MIMXRT1170-EVK board.  

Can you share more details how to replicate the issue you are seeing?  I recommend creating a new [Issue](https://github.com/zephyrproject-rtos/zephyr/issues/new/choose), and adding details there to replicate and understand the root cause.  You can link that issue to this PR.

Thanks for raising this.  Best regards

**Comment by RadekPolyend** [comment]
Ok but the test doesn't seem to assume the reload of the tx buffers after the start trigger, it just drains the buffers which were loaded before the trigger

**Comment by RadekPolyend** [comment]
https://github.com/zephyrproject-rtos/zephyr/issues/82470
