### PR TITLE
drivers: sensor: tmp108: fix coverity integer handling issue

### LINKED ISSUE #67965: [Coverity CID: 248434] Reliance on integer endianness in drivers/sensor/tmp108/tmp108.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/69522b8694e11a0597935169c7d5c0ece0309496/drivers/sensor/tmp108/tmp108.c

Category: Integer handling issues
Function: `tmp108_attr_get`
Component: Drivers
CID: [248434](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=248434)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/69522b8694e11a0597935169c7d5c0ece0309496/drivers/sensor/tmp108/tmp108.c#L175

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=248434

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_INCOMPATIBLE_CAST). ([CWE-188](http://cwe.mitre.org/data/definitions/188.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by avisconti**
Fix coverity integer handling issue (CWE-188).
Modifying a variable through a pointer of an incompatible type (other than unsigned char) can lead to unpredictable results.

Fix: #67965
Coverity-CID: 248434

### CODE REVIEW

**Review by bjarki-andreasen — DISMISSED** [review]

File: drivers/sensor/tmp108/tmp108.c [hunk 1]
```diff
@@ -174,7 +175,8 @@ static int tmp108_attr_get(const struct device *dev,
 	case SENSOR_ATTR_CONFIGURATION:
 		result =  tmp108_reg_read(dev,
 					  TI_TMP108_REG_CONF,
-					  (uint16_t *) &(val->val1));
+					  &tmp_val);
+		val->val1 = tmp_val;
```
Comment (fabiobaltieri) [inline drivers/sensor/tmp108/tmp108.c:179]: May be a good idea of adding a `val->val2 = 0;` while at it.

Comment (henrikbrixandersen) [reply drivers/sensor/tmp108/tmp108.c:179]: Agreed.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]

File: drivers/sensor/tmp108/tmp108.c (hunk 1 above)
Comment (avisconti) [reply drivers/sensor/tmp108/tmp108.c:179]: it makes sense

**Review by henrikbrixandersen — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
