### PR TITLE
Bluetooth: Controller: Fix assertion scheduling first BIG event and in window widening CIS event

### LINKED ISSUE #54642: Bluetooth: Controller: Assertion on disconnecting CIS and assertion on synchronizing to first encrypted BIS
**Describe the bug**
1. Disconnection due to supervision timeout of CIS connection causes the Controller to assert due to window widening overflowing into next subevent reception
2. Due to added CPU usage calculating crypto values before setting up BIS synchronization added additional overhead due to when BIS event get delayed causing Controller to assert. Synchronization for Second and there after BIS has no issues
3. Creating CIS connection other than ACL handle of 0 failed as the CIS'es acl_handle member variable was uninitialized

**To Reproduce**
1. mkdir build/hci_rpmg; cd build/hci_rpmsg
4. cmake -DBOARD=nrf5340_audio_dk_nrf5340_cpunet -DCONF_FILE=nrf5340_cpunet_iso-bt_ll_sw_split.conf
5. ninja
6. flash the controller to audio dk 's network core, build and flash a modified audio application that is compatible with Zephyr Controller (https://github.com/nrfconnect/sdk-nrf/pull/10018)

**Expected behavior**
1. Controller shall not assert on disconnection due to link loss
2. Controller shall not assert on establishing sync with first BIS
3. Creating CIS for ACL handles != 0 shall succeed

**Impact**
showstopper

**Logs and console output**
TBD

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used:  v3.3.0-rc1

**Additional context**
None

### PR DESCRIPTION
**Pull request by cvinayak**
Fix assertion due to delayed prepare of first BIG event when
supporting encryption. Crypto calculation introduce extra
processing delay causing the scheduling of first BIG event
to be delayed. Detect such delay and skip to next ISO
interval.

Relax radio_tmr_start_us() delayed start assertion when
window widening in progress.

Fix Controller assertion handler to lock IRQs and spinlock
on assertions.

Fix uninitialized CIS LLL structure member variables,
uninitialised CIS acl_handle causes HCI command disallowed
for acl_handle's other than 0x0000.
Initialize other variables like sn, nesn etc. when create
CIS control procedure is performed.

Fixes #54642.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 1]
```diff
@@ -696,6 +697,13 @@ uint8_t ull_central_iso_setup(uint16_t cis_handle,
 	cis->offset = cis_offset;
 	cis->central.instant = instant;
 	cis->lll.event_count = -1;
+	cis->lll.next_subevent = 0;
+	cis->lll.sn = 0;
+	cis->lll.nesn = 0;
+	cis->lll.cie = 0;
+	cis->lll.flushed = 0;
+	cis->lll.active = 0;
+	cis->lll.datapath_ready_rx = 0;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:706]: Should all these be `0U`?

File: subsys/bluetooth/controller/ll_sw/ull_peripheral_iso.c [hunk 2]
```diff
@@ -316,6 +309,13 @@ uint8_t ull_peripheral_iso_setup(struct pdu_data_llctrl_cis_ind *ind,
 	cis->offset = sys_get_le24(ind->cis_offset);
 	memcpy(cis->lll.access_addr, ind->aa, sizeof(ind->aa));
 	cis->lll.event_count = -1;
+	cis->lll.next_subevent = 0;
+	cis->lll.sn = 0;
+	cis->lll.nesn = 0;
+	cis->lll.cie = 0;
+	cis->lll.flushed = 0;
+	cis->lll.active = 0;
+	cis->lll.datapath_ready_rx = 0;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_peripheral_iso.c:318]: Ditto

File: subsys/bluetooth/controller/ll_sw/ull_sync_iso.c [hunk 3]
```diff
@@ -521,6 +524,22 @@ void ull_sync_iso_setup(struct ll_sync_iso_set *sync_iso,
...
+	ticks_threshold = ticker_ticks_now_get() +
+			  HAL_TICKER_US_TO_TICKS(EVENT_OVERHEAD_START_US);
+	ticks_diff = ticker_ticks_diff_get(ticks_expire, ticks_threshold);
+	if (ticks_diff & BIT(HAL_TICKER_CNTR_MSBIT)) {
+		sync_iso_offset_us += interval_us -
+			lll->window_widening_periodic_us;
+		lll->window_widening_event_us +=
+			lll->window_widening_periodic_us;
+		lll->payload_count += lll->bn;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_sync_iso.c:541]: Any risks of underflow or overflow on any of these?

**Review by Thalley — DISMISSED** [review]
Looks OK to me, with a few comments

**Review by kruithofa — DISMISSED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_sync_iso.c (hunk 3 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_sync_iso.c:541]: `ticks_*` are permited to underflow and overflow as it is free-running. `window_widening_periodic_us` is a fraction of `interval_us` hence would not lead to negative offset.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c [hunk 4]
```diff
@@ -522,19 +522,30 @@ static void isr_rx(void *param)
 	rssi_ready = radio_rssi_is_ready();
 	trx_cnt++;
 
+	/* initialize LLL context reference */
+	lll = param;
+
 	/* Save the AA captured for the first anchor point sync */
 	if (!radio_tmr_aa_restore()) {
+		struct lll_sync_iso_stream *stream;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_sync_iso.c:530]:
```suggestion
		const struct lll_sync_iso_stream *stream;
```

File: subsys/bluetooth/controller/ll_sw/ull_adv.c [hunk 5]
```diff
@@ -1509,8 +1511,11 @@ uint8_t ll_adv_enable(uint8_t enable)
 						EVENT_OVERHEAD_START_US +
 						(EVENT_TICKER_RES_MARGIN_US << 1));
 
+				ticks_slot_overhead =
+					ull_adv_sync_evt_init(adv, sync, NULL);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv.c:1515]:
```suggestion
				ticks_slot_overhead = ull_adv_sync_evt_init(adv, sync, NULL);
```

The TSC decided this week to remove the 80 character suggestion, so now we can (and should) use the 100 character limit instead.

File: subsys/bluetooth/controller/ll_sw/ull_adv_sync.c [hunk 6]
```diff
@@ -868,15 +880,28 @@ uint8_t ll_adv_sync_enable(uint8_t handle, uint8_t enable)
...
-			ticks_anchor_sync =
-				ticker_ticks_now_get() +
+			ticks_anchor_sync = ticker_ticks_now_get() +
 				HAL_TICKER_US_TO_TICKS(EVENT_OVERHEAD_START_US);
+
+#if defined(CONFIG_BT_CTLR_SCHED_ADVANCED)
+			err = ull_sched_adv_aux_sync_free_slot_get(
+							TICKER_USER_ID_THREAD,
+							sync->ull.ticks_slot,
+							&ticks_anchor_sync);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_sync.c:895]: err = ull_sched_adv_aux_sync_free_slot_get(TICKER_USER_ID_THREAD,
								   sync->ull.ticks_slot,
								   &ticks_anchor_sync);
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_sync.c [hunk 7]
```diff
@@ -1053,26 +1079,23 @@ uint32_t ull_adv_sync_time_get(const struct ll_adv_sync_set *sync,
...
 
 	ull_hdr_init(&sync->ull);
 
-	lll_sync = &sync->lll;
-	ter_pdu = lll_adv_sync_data_peek(lll_sync, NULL);
+	if (!pdu) {
+		const struct lll_adv_sync *lll_sync = &sync->lll;
 
-	time_us = ull_adv_sync_pdu_time_get(sync, ter_pdu);
+		pdu = lll_adv_sync_data_peek(lll_sync, NULL);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_sync.c:1095]: This could probably just be

```suggestion
		pdu = lll_adv_sync_data_peek(&sync->lll, NULL);
```

without loosing readability

File: subsys/bluetooth/controller/ll_sw/ull_adv_sync.c [hunk 8]
```diff
@@ -1888,7 +1924,7 @@ static inline uint16_t sync_handle_get(struct ll_adv_sync_set *sync)
 			     sizeof(struct ll_adv_sync_set));
 }
 
-static uint32_t ull_adv_sync_pdu_time_get(const struct ll_adv_sync_set *sync,
+static uint32_t sync_time_get(const struct ll_adv_sync_set *sync,
 					  const struct pdu_adv *pdu)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_sync.c:1928]: Fix indentation

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c [hunk 9]
```diff
@@ -504,7 +504,7 @@ uint8_t ll_cis_create_check(uint16_t cis_handle, uint16_t acl_handle)
 
 		/* Verify handle validity and association */
 		cis = ll_conn_iso_stream_get(cis_handle);
-		if (cis->lll.handle == cis_handle && cis->lll.acl_handle == acl_handle) {
+		if (cis->lll.handle == cis_handle) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_central_iso.c:507]: Just to make sure: The `handle`/`cis_handle` here are the connection handle, and not the CIS ID, right?

**Review by Thalley — CHANGES_REQUESTED** [review]
A few minor comments

File: subsys/bluetooth/controller/ll_sw/ull_adv_sync.c (hunk 8 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv_sync.c]: done

File: subsys/bluetooth/controller/ll_sw/ull_central_iso.c (hunk 9 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_central_iso.c:507]: these are connection handles, not CIS ID.

**Review by Thalley — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
