### PR TITLE
modules: acpica: Fix header inclusion issue

### LINKED ISSUE #62679: main CI broken: qemu_x86_64 fails to build on main
**Describe the bug**
Cannot build targetting qemu_x86_64 on main

**To Reproduce**
 - Trigger any PR CI which causes qemu_x86_64 to be built
 or
 - twister -p qemu_x86_64 
 or..

**Expected behavior**
No build failures

**Impact**
Main development blocked

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/6195415396/job/16820138218?pr=62675#step:13:8221

**Environment (please complete the following information):**
 - OS: Linux / CI 
 - Toolchain (e.g Zephyr SDK, ...): CI
 - Commit SHA or Version used: Main as of now: d42d14e392e70a846abe5baaceb849ef21a50584

**More info**
@carlescufi is looking into it
Suspect commit https://github.com/zephyrproject-rtos/zephyr/commit/79d0bf39b8402f2b59fbcad2860e2a25c270545e

### PR DESCRIPTION
**Pull request by carlescufi**
After 79d0bf39b8402f2b59fbcad2860e2a25c270545e was merged, the inclusion of `<zephyr/acpi/acpi.h>` with `CONFIG_ACPI=n` caused a build failure because `<acpica/source/include/acpi.h>` could no longer be included due to the inlcude path not being injected anymore.

Fix this by guarding the header so it includes nothing when `CONFIG_ACPI` is not set.

Fixes #62679.

### CODE REVIEW

**Comment by faloj** [comment]
Thank you

File: include/zephyr/acpi/acpi.h [hunk 1]
```diff
@@ -5,6 +5,7 @@
  */
 #ifndef ZEPHYR_INCLUDE_DRIVERS_ACPI_H_
 #define ZEPHYR_INCLUDE_DRIVERS_ACPI_H_
+#ifdef CONFIG_ACPI
```
Comment (gmarull) [inline include/zephyr/acpi/acpi.h:8]: shouldn't we just prevent the inclusion of this header if !defined CONFIG_ACPI?

Comment (fabiobaltieri) [reply include/zephyr/acpi/acpi.h:8]: Yeah that's what I was propsing as well, I think it's a better idea, just in case there's more headers to be added to the conditional.

Comment (gmarull) [reply include/zephyr/acpi/acpi.h:8]: actually https://github.com/zephyrproject-rtos/zephyr/pull/62682 is what I'd expect

Comment (carlescufi) [reply include/zephyr/acpi/acpi.h:8]: Sure, let me change that

Comment (carlescufi) [reply include/zephyr/acpi/acpi.h]: @gmarull @fabiobaltieri done

**Review by fabiobaltieri — APPROVED** [review]

File: include/zephyr/acpi/acpi.h (hunk 1 above)
Comment (carlescufi) [reply include/zephyr/acpi/acpi.h]: Note that the reason I did it this way is that @tejlmand considered it a better solution :)

**Review by gmarull — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by najumon1980 — APPROVED** [review]

**Comment by najumon1980** [comment]
Will revisit again all acpi code inclusion and provide update if required.
