### PR TITLE
usb: device_next: hid: fix Get Report buffer handling

### LINKED ISSUE #73457: usb: device_next: usbd_hid: HID get report does not work
**Describe the bug**
HID get report functionality does not work for USB next stack. `ioctl: Connection timed out` error is observed e.g. when host computer tries to get a HID feature report from device. Issue was replicated with an application developed outside of Zephyr, but the root cause is bug in the USB next stack.

**Expected behavior**
HID report get should work without problems.

**Impact**
A HID device using USB next stack cannot support HID report get.

**Environment (please complete the following information):**
Issue affects main branch (`c1400536548bb861c630f81d8aced864f1a85ca1`).

**Additional context**
Seems that incrementing data length of the buffer can be a workaround here: https://github.com/zephyrproject-rtos/zephyr/pull/73451.

### PR DESCRIPTION
**Pull request by jfischer-no**
After the get_report() callback, we need to determine how many bytes the HID device wrote to the report buffer. Use the callback return value to do this, and modify the net_buf data length value if get_report was successful.

Fixes: #73457

### CODE REVIEW

File: subsys/usb/device_next/class/usbd_hid.c [hunk 1]
```diff
@@ -231,25 +231,33 @@ static int handle_get_report(const struct device *dev,
...
-		errno = ops->get_report(dev, type, id, net_buf_tailroom(buf), buf->data);
+		ret = ops->get_report(dev, type, id, size, buf->data);
 		break;
 	default:
 		errno = -ENOTSUP;
 		break;
 	}
 
+	if (ret > 0) {
+		net_buf_add(buf, MIN(size, ret));
```
Comment (tmon-nordic) [inline subsys/usb/device_next/class/usbd_hid.c:256]: Should there be an assert here to check that `ret <= size`?

**Review by tmon-nordic — DISMISSED** [review]

**Review by MarekPieta — APPROVED** [review]
Confirmed the fix. Thank you!

File: subsys/usb/device_next/class/usbd_hid.c (hunk 1 above)
Comment (tmon-nordic) [reply subsys/usb/device_next/class/usbd_hid.c:256]: Host requesting more than report length is not what would be asserted here. When `ret <= size` is not fulfilled it means that application essentially wrote (or at least claimed to write) beyond the buffer.

File: subsys/usb/device_next/class/usbd_hid.c [hunk 2]
```diff
@@ -231,25 +231,34 @@ static int handle_get_report(const struct device *dev,
...
-		errno = ops->get_report(dev, type, id, net_buf_tailroom(buf), buf->data);
+		ret = ops->get_report(dev, type, id, size, buf->data);
 		break;
 	default:
 		errno = -ENOTSUP;
 		break;
 	}
 
+	if (ret > 0) {
+		__ASSERT(ret <= size, "The HID driver overwrote the buffer length");
```
Comment (tmon-nordic) [inline subsys/usb/device_next/class/usbd_hid.c:256]: The wording is rather misleading. The buffer length itself is not overwritten, but rather the data is written past the buffer end.

```suggestion
		__ASSERT(ret <= size, "Buffer overflow detected in HID driver");
```

**Review by tmon-nordic — CHANGES_REQUESTED** [review]

**Review by tmon-nordic — APPROVED** [review]

**Review by MarekPieta — APPROVED** [review]

**Review by nashif — APPROVED** [review]
