### PR TITLE
Fix cc32xx gpio driver to prevent spurious interrupts in gpio_basic_api test

### LINKED ISSUE #22847: Test gpio_basic_api hangs on cc3220sf_launchxl
**Describe the bug**
The test hangs in the middle of execution of test_gpio_deprecated:

```

OUT init a01, IN cfg 74000, cnt 2
PASS - test_gpio_callback_variants
===================================================================
starting test - test_gpio_deprecated
callback triggered: 1
INT cfg 50000, cnt 1
callback triggered: 1
INT cfg 30000, cnt 1
callback triggered: 1
callback triggered: 2
INT cfg 74000, cnt 2
```

**To Reproduce**
1. cd tests/drivers/gpio/gpio_basic_api
2. west build -b cc3220sf_launchxl -p
3. west flash

**Expected behavior**
The test should not hang

**Impact**
sanitycheck fails as a result.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.11.1
 - Commit SHA or Version used: 1736cb79c220f02e8a93c29f7c1ba3323aff17c1

### PR DESCRIPTION
**Pull request by vanti**
Analyzing #22847 has shown that spurious interrupts are observed when invoking test_callback for level-based interrupt type. The test hangs due to interrupts being repeatedly fired. This is fixed by performing the following:

- Avoid unnecessarily disabling gpio interrupts when firing registered callbacks. This is an issue because gpio_basic_api's test_deprecated test case attempts to disable interrupts on a pin under certain conditions by invoking gpio_pin_configure(), which has no effect given they get re-enabled as soon as the callbacks are done firing.

- Disable gpio interrupts prior to changing the interrupt type in gpio_cc32xx_pin_interrupt_configure(), in case interrupts were already enabled by previous test cases.

### CODE REVIEW

**Review by pabigot — APPROVED** [review]
This looks very good.

It does highlight that we didn't really take into account interaction between existing callbacks and changing the interrupt configuration.  Or at least document the state machine that should model the desired behavior across platforms.

File: drivers/gpio/gpio_cc32xx.c [hunk 1]
```diff
@@ -187,6 +187,12 @@ static int gpio_cc32xx_pin_interrupt_configure(struct device *port,
 				int_type = GPIO_LOW_LEVEL;
 			}
 		}
+		/*
+		 * disable interrupt prior to changing int type helps
+		 * prevent spurious interrupts observed when switching
+		 * to level-based
+		 */
+		MAP_GPIOIntDisable(port_base, (1 << pin));
```
Comment (mnkp) [inline drivers/gpio/gpio_cc32xx.c]: I propose to place the line at the top of the function, i.e. upon entry interrupts will be disabled. We can drop then the `else` statement.

Comment (vanti) [reply drivers/gpio/gpio_cc32xx.c]: I made the change. Thanks!

**Review by mnkp — APPROVED** [review]
