### PR TITLE
stm32f412 and stm32f413 have a 48MHz clock for SDMMC or USB

### LINKED ISSUE #78816: stm32f4 sdmmc sdio error clock is not 48MHz
**Describe the bug**
I'm trying to use the sdcard port of my stm32f412g-disco board.
For that, I enabled the sdmmc via a dts overlay and relevant CONFIGs and when mounting I'm getting an error:
```
<err> stm32_sdmmc: SDMMC Clock is not 48MHz (100000000)
```

When I add `CONFIG_SDMMC_STM32_CLOCK_CHECK=n`, everything works as expected.

I tried to enable the clk_hsi48 node, but it does not exist in the stm32f4 device tree.
Is it an error I should worry? Is my workaround the correct way to fix this error?

**To Reproduce**
My overlay:
```
&sdmmc1 {
    status = "okay";

    compatible = "st,stm32-sdmmc";
        pinctrl-0 = <&sdio_d0_pc8 &sdio_d1_pc9
                                 &sdio_d2_pc10 &sdio_d3_pc11
                                 &sdio_ck_pc12 &sdio_cmd_pd2>;
        cd-gpios = <&gpiod 3 GPIO_ACTIVE_LOW>;
        pinctrl-names = "default";
};
```
My prj.conf
```
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_SDMMC_STM32=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_MOUNT_MKFS=n
CONFIG_SDIO_STACK=y
```

I'm using zephyr 3.7 tag

**Expected behavior**
The fs_mount function should work with CONFIG_SDMMC_STM32_CLOCK_CHECK

### PR DESCRIPTION
**Pull request by FRASTM**
Add the clock configuration for the 48MHz for the stm32f412 or stm32f413 devices
Both have a clock 48MHz which source is PLL Q or PLL I2S Q 
This 48MHz clock is feeding the USB or RNG or SDMCC peripherals

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/78816

### CODE REVIEW

**Comment by FRASTM** [comment]
from the stm32f412 [refman](https://www.st.com/resource/en/reference_manual/rm0402-stm32f412-advanced-armbased-32bit-mcus-stmicroelectronics.pdf):

stm32f412_clock

File: drivers/clock_control/clock_stm32_ll_common.c [hunk 1]
```diff
@@ -215,6 +215,13 @@ int enabled_clock(uint32_t src_clk)
 		}
 		break;
 #endif /* STM32_SRC_PLL_R */
+#if defined(STM32_SRC_PLLI2S_Q)
+	case STM32_SRC_PLLI2S_Q:
+		if (!IS_ENABLED(STM32_PLLI2S_Q_ENABLED)) {
+			r = -ENOTSUP;
+		}
+		break;
+#endif /* STM32_SRC_PLLI2S_R */
```
Comment (tagunil) [inline drivers/clock_control/clock_stm32_ll_common.c:224]:
```suggestion
#endif /* STM32_SRC_PLLI2S_Q */
```

**Comment by FRASTM** [comment]
Adding a testcase for the 48MHz clock configuration

`west build -p auto -b stm32f412g_disco tests/drivers/clock_control/stm32_clock_configuration/stm32_common_devices/ -- -DDTC_OVERLAY_FILE="boards/f4_sdmmc48_pll.overlay"`

Tested on a **stm32f413h_disco**,
```
Running TESTSUITE stm32_common_devices_clocks
===================================================================
START - test_sdmmc_clk_config
SDMMC gating clock on
SDMMC domain clock configured
SDMMC sourced by PLLI2SQ at 48000000 Hz
SDMMC clock rate: 48000000 Hz
SDMMC gating clk off
 PASS - test_sdmmc_clk_config in 0.013 seconds
===================================================================
START - test_sysclk_freq
 PASS - test_sysclk_freq in 0.001 seconds
===================================================================
TESTSUITE stm32_common_devices_clocks succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [stm32_common_devices_clocks]: pass = 2, fail = 0, skip = 0, total = 2 duration = 0.014 seconds
 - PASS - [stm32_common_devices_clocks.test_sdmmc_clk_config] duration = 0.013 seconds                                                                                            
 - PASS - [stm32_common_devices_clocks.test_sysclk_freq] duration = 0.001 seconds                                                                                                 
                                                                                                                                                                                  
------ TESTSUITE SUMMARY END ------                                                                                                                                               
                                                                                                                                                                                  
===================================================================                                                                                                               
PROJECT EXECUTION SUCCESSFUL 
```

File: drivers/clock_control/clock_stm32_ll_common.c (hunk 1 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_common.c]: done

File: include/zephyr/dt-bindings/clock/stm32f410_clock.h [hunk 2]
```diff
@@ -6,6 +6,9 @@
 #ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_STM32F410_CLOCK_H_
 #define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_STM32F410_CLOCK_H_
 
+/* CLK48MHz sources */
+#define STM32_SRC_CK48	(STM32_SRC_PLLI2S_R + 1)
+
```
Comment (gautierg-st) [inline include/zephyr/dt-bindings/clock/stm32f410_clock.h:11]: This should be added in stm32f4_clock.h. With this single define in a different file, there is a great risk that it would be overlooked if any other clock sources are added in the future (PLLSAI for example).
There is no risk to have that define even for SoC that don't have this clock (just like F410 that doesn't have a PLLI2S but has the associated define).

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 3]
```diff
@@ -114,7 +114,16 @@ void config_plli2s(void)
 				       plli2sm(STM32_PLLI2S_M_DIVISOR),
 				       STM32_PLLI2S_N_MULTIPLIER,
 				       plli2sr(STM32_PLLI2S_R_DIVISOR));
+#if STM32_PLLI2S_Q_ENABLED
+	/* There is a Q divider on the PLLI2S to configure the PLL48CK */
+	LL_RCC_PLLI2S_ConfigDomain_48M(get_pll_source(),
+				       plli2sm(STM32_PLLI2S_M_DIVISOR),
+				       STM32_PLLI2S_N_MULTIPLIER,
+				       plli2sq(STM32_PLLI2S_Q_DIVISOR));
+#endif /* STM32_PLLI2S_Q_ENABLED */
```
Comment (gautierg-st) [inline drivers/clock_control/clock_stm32f2_f4_f7.c:123]: There is currently no configuration of main PLL Q channel. You should also add the LL_RCC_PLL_ConfigDomain_48M function in the config_pll_sysclock function.

File: include/zephyr/drivers/clock_control/stm32_clock_control.h [hunk 4]
```diff
@@ -428,6 +431,12 @@
 #define STM32_CKPER_ENABLED	1
 #endif
 
+#if DT_NODE_HAS_COMPAT_STATUS(DT_NODELABEL(clk48), st_stm32_clock_mux, okay)
+/* Assuming the 48MHz clock is 48MHz */
+#define STM32_CK48_ENABLED	1
+#define STM32_CK48_FREQ		48000000
```
Comment (gautierg-st) [inline include/zephyr/drivers/clock_control/stm32_clock_control.h:437]: Although it is named 48MHz clock, it can technically be another value so it would be safer to compute its value.
This computed value could then be used to throw an assert if not equal to 48MHz.

**Review by gautierg-st — CHANGES_REQUESTED** [review]

File: include/zephyr/drivers/clock_control/stm32_clock_control.h (hunk 4 above)
Comment (FRASTM) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h:437]: We can imagine a get_ck48_frequency() function to return the clock freq depending on the clock source (CK48MSEL )  of the PLL48 to be part of the stm32_clock_control_get_subsys_rate (get_rate). In this case I do not see any difference between the _dev_dt_clk_freq_ and the _dev_actual_clk_freq_   
--> actually there is no more _dev_dt_clk_freq_  (except if we add a clock-frequency property to the "st,stm32-clock-mux")

**Comment by FRASTM** [comment]
with new commit 7ffa15a5dbc6a87b3cd763511a2be6a66441afb2 to get the 48MHz freq

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 5]
```diff
@@ -50,6 +50,36 @@ uint32_t get_pllsrc_frequency(void)
...
+/**
+ * @brief calculate the CK48 frequency depending on its clock source
+ */
+__unused
+uint32_t get_ck48_frequency(void)
+{
+	if (LL_RCC_GetCK48MClockSource(LL_RCC_CK48M_CLKSOURCE) ==
+			LL_RCC_CK48M_CLKSOURCE_PLL) {
+		/* Get the PLL Q freq. No HAL macro for that */
+		return __LL_RCC_CALC_PLLCLK_48M_FREQ(HSE_VALUE,
```
Comment (gautierg-st) [inline drivers/clock_control/clock_stm32f2_f4_f7.c:63]: This supposes that HSE is used, but HSI could also be used as PLL source clock.
Function RCC_PLL_GetFreqDomain_48M could be used instead.

File: drivers/clock_control/clock_stm32f2_f4_f7.c [hunk 6]
```diff
@@ -50,6 +50,36 @@ uint32_t get_pllsrc_frequency(void)
...
+						LL_RCC_PLLI2S_GetDivider(),
+						LL_RCC_PLLI2S_GetN(),
+						LL_RCC_PLLI2S_GetQ()
+						);
+	} else if (LL_RCC_GetCK48MClockSource(LL_RCC_CK48M_CLKSOURCE) ==
+			LL_RCC_CK48M_CLKSOURCE_PLLI2S) {
+		/* Get the I2S PLL Q freq. No HAL macro for that */
+		return __LL_RCC_CALC_PLLI2S_48M_FREQ(HSE_VALUE,
```
Comment (gautierg-st) [inline drivers/clock_control/clock_stm32f2_f4_f7.c:71]: This supposes that HSE is used, but HSI could also be used as PLL source clock.
Function RCC_PLLI2S_GetFreqDomain_48M could be used instead.

**Review by gautierg-st — CHANGES_REQUESTED** [review]

File: drivers/clock_control/clock_stm32f2_f4_f7.c (hunk 6 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:71]: could it be LL_RCC_PLLI2S_GetMainSource ?

File: drivers/clock_control/clock_stm32f2_f4_f7.c (hunk 5 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:63]: could it be LL_RCC_PLL_GetMainSource

File: drivers/clock_control/clock_stm32f2_f4_f7.c (hunk 3 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32f2_f4_f7.c:171]: adding a LL_RCC_PLL_ConfigDomain_48M function in the config_pll_sysclock() function

**Comment by FRASTM** [comment]
rebase

**Review by gautierg-st — DISMISSED** [review]

**Review by gautierg-st — DISMISSED** [review]

File: dts/arm/st/f4/stm32f412.dtsi [hunk 7]
```diff
@@ -201,8 +207,7 @@
 		};
 
 		sdmmc1: sdmmc@40012c00 {
-			clocks = <&rcc STM32_CLOCK(APB2, 11U)>,
-				 <&rcc STM32_SRC_SYSCLK SDIO_SEL(1)>;
+			clocks = <&rcc STM32_CLOCK(APB2, 11U)>;
```
Comment (erwango) [inline dts/arm/st/f4/stm32f412.dtsi:210]:
```
			clocks = <&rcc STM32_CLOCK(APB2, 11U)>,
				 <&rcc STM32_SRC_48M SDIO_SEL(0)>;
```

File: dts/arm/st/f4/stm32f412.dtsi [hunk 8]
```diff
@@ -16,6 +16,12 @@
 			compatible = "st,stm32f411-plli2s-clock";
 			status = "disabled";
 		};
+
+		clk48: clk48 {
+			#clock-cells = <0>;
+			compatible = "st,stm32-clock-mux";
+			status = "disabled";
```
Comment (erwango) [inline dts/arm/st/f4/stm32f412.dtsi:23]: clocks = <&rcc STM32_SRC_PLL_Q CK48M_SEL(0)>;

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
adding the clock source default position for the CLK48MSEL and for the SDIOSEL

File: include/zephyr/drivers/clock_control/stm32_clock_control.h (hunk 4 above)
Comment (erwango) [inline include/zephyr/drivers/clock_control/stm32_clock_control.h:437]: Actually not used. Let remove

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: include/zephyr/drivers/clock_control/stm32_clock_control.h (hunk 4 above)
Comment (FRASTM) [reply include/zephyr/drivers/clock_control/stm32_clock_control.h]: removed

**Review by erwango — DISMISSED** [review]

**Review by marwaiehm-st — DISMISSED** [review]

**Review by gautierg-st — DISMISSED** [review]

File: tests/drivers/clock_control/stm32_clock_configuration/stm32_common_devices/testcase.yaml [hunk 9]
```diff
@@ -34,3 +34,6 @@ tests:
   drivers.clock.stm32_clock_configuration.common_device.f3.i2c1_hsi:
     extra_args: DTC_OVERLAY_FILE="boards/f3_i2c1_hsi.overlay"
     platform_allow: stm32f3_disco
+  drivers.clock.stm32_clock_configuration.common_device.f4.sdmmc_48:
+    extra_args: DTC_OVERLAY_FILE="boards/f4_sdmmc48_pll.overlay"
+    platform_allow: stm32f412g_disco nucleo_f412zg
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply tests/drivers/clock_control/stm32_clock_configuration/stm32_common_devices/testcase.yaml]: changing to 2 lines

**Review by gautierg-st — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by marwaiehm-st — APPROVED** [review]
