### PR TITLE
file system: storage: Fix the memory size output by adding brace for manipulating operator priority properly

### LINKED ISSUE #26266: Cast and shift operator priority issue may lead to wrong memory size result in fat_fs example
**Describe the bug**
In fat_fs example, if we choose a large size SD card to connect with, the result of memory size calculation coule be wrong due to the missing brace for manipulating operator priority.
E.g., if we run the example with a 16GB SDHC card, the print out memory size is 2799 MB which is wrong. 
This is because in this [line](https://github.com/zephyrproject-rtos/zephyr/blob/zephyr-v2.3.0/samples/subsys/fs/fat_fs/src/main.c#L62), we should do shift operation first, and then cast with uint32_t.
However, the current code will do cast first and then do shift, which may cause the result overflowed.

**To Reproduce**
1. Prepare a nRF52840-DK, and connect with a 16GB SD card
2. west build -b nrf52840dk_nrf52840 zephyr/samples/subsys/fs/fat_fs
3. west flash
4. check the "Memory Size" print out in serial terminal

**Expected behavior**
E.g. For my 16 GB SDHC card, the sector size is 512 KB, and the block count is 30898176.
The memory size should be 512 * 30898176 = 15819866112 bytes
Which is 15087 MB.
But since there's no brace in the issue line, the code will do cast first then shift.
So result is 2552 MB, which is wrong.

**Impact**
When using large size SD card (>4GB), the print memory size is wrong

**Additional context**
The fix could be 
```
-printk("Memory Size(MB) %u\n", (u32_t)memory_size_mb>>20);
+printk("Memory Size(MB) %u\n", (u32_t)(memory_size_mb>>20));
```

### PR DESCRIPTION
**Pull request by rick1082**
In fat_fs example, if we choose a large size SD card to connect with,
the result of memory size calculation coule be wrong due to the missing
brace for manipulating operator priority.

Fixes #26266.

Signed-off-by: Chung, Jui-Chou <jui-chou.chung@nordicsemi.no>

### CODE REVIEW

**Review by pabigot — APPROVED** [review]

**Review by nzmichaelh — APPROVED** [review]
LGTM

File: samples/subsys/fs/fat_fs/src/main.c [hunk 1]
```diff
@@ -59,7 +59,7 @@ void main(void)
 		printk("Sector size %u\n", block_size);
 
 		memory_size_mb = (uint64_t)block_count * block_size;
-		printk("Memory Size(MB) %u\n", (uint32_t)memory_size_mb>>20);
+		printk("Memory Size(MB) %u\n", (uint32_t)(memory_size_mb>>20));
```
Comment (stephanosio) [inline samples/subsys/fs/fat_fs/src/main.c:62]: It would be nice to fix the incorrect spacing while we are here.
```suggestion
		printk("Memory Size(MB) %u\n", (uint32_t)(memory_size_mb >> 20));
```

**Review by stephanosio — APPROVED** [review]
