### PR TITLE
drivers: pwm_nrfx: Fix the driver to allow changing period on the fly

### LINKED ISSUE #15323: blink_led sample does not work on most of the nRF boards
The issue was originally reported on slack (#general):
```
Aaron Tsui 9:15 AM, March 22nd
BTW, As the PWM_CLK lowest is 125khz(16M/128) and COUNTERTOP max is 0x7fff on nrf52, my understanding the nrf52 HW PWM longest period is about 262ms, cannot reach period as 1000ms. right?
@gaute this will cause failure on sample/blink_led, which need a 1000ms period.
```
Indeed, when trying to run this sample on any board with an nRF52 series SoC, which by default uses the HW PWM driver, one hits the following error:
```
PWM demo app-blink LED
pwm pin set fails
[00:00:00.008,544] <err> pwm_nrfx: Prescaler for period_cycles 16000000 not found.

[00:00:00.008,544] <err> pwm_nrfx: Incompatible period 16000000
```
Same happens for boards with nRF91 series SoCs.

For nRF52 the solution could be to use the nRF SW PWM driver, for nRF91 the driver is unavailable.

### PR DESCRIPTION
**Pull request by anangl**
Previously it was not possible to change the PWM period, even if only
a single channel was in use, without first stopping the peripheral,
i.e. setting pulse cycles for the channel to 0. This patch corrects
this behavior.

Fixes #15323.

### CODE REVIEW

File: drivers/pwm/pwm_nrfx.c [hunk 1]
```diff
@@ -170,29 +143,39 @@ static int pwm_nrfx_pin_set(struct device *dev, u32_t pwm,
...
+			return ret;
+		}
 	}
 
-	/* Check if pulse is bigger than period, fail if so */
+	/* Limit pulse cycles to period cycles (meaning 100% duty), bigger
+	 * values might not fit after prescaling into the 15-bit field that
+	 * is filled below.
+	 */
 	if (pulse_cycles > period_cycles) {
```
Comment (nordic-krch) [inline drivers/pwm/pwm_nrfx.c]: `pulse_cycles = MIN(pulse_cycles, period_cycles)`?

File: drivers/pwm/pwm_nrfx.c [hunk 2]
```diff
@@ -214,23 +197,28 @@ static int pwm_nrfx_pin_set(struct device *dev, u32_t pwm,
 		} else {
 			nrf_gpio_pin_set(pwm);
 		}
-	}
 
-	/* Check if all channels are off (duty 0% or 100%) */
-	if (!any_channel_active(data)) {
-		nrfx_pwm_stop(&config->pwm, false);
+		/* Check if any other channel is active. If not, stop PWM. */
```
Comment (nordic-krch) [inline drivers/pwm/pwm_nrfx.c]: imo, something that was previously here was better in terms of readability. I mean, encapsulating algorithm for checking if anything is active into a function.

Something like:
```
if (!any_channel_active(data)) {
   nrfx_pwm_stop(&config->pwm, false);
}
```

Comment (anangl) [reply drivers/pwm/pwm_nrfx.c]: Agreed. I'll restore `any_channel_active`.

Comment (anangl) [reply drivers/pwm/pwm_nrfx.c]: Extracted this part of code into `any_other_channel_is_active()`.

**Review by nordic-krch — APPROVED** [review]
lgtm

**Comment by carlescufi** [comment]
@Mierunski and @kl-cruz could you please review this PR?

**Review by kl-cruz — APPROVED** [review]
Looks good!

**Review by carlescufi — APPROVED** [review]
