### PR TITLE
kernel: pipe: if timeout is not K_NO_WAIT and >= min_xfer bytes transferred, then return immediately

### LINKED ISSUE #24485: kernel: pipe: should return if >= min_xfer bytes transferred and timeout is K_FOREVER
**Describe the bug**
The following code hangs indefinitely at `k_pipe_get()`, but it should not, according to [the documentation](https://docs.zephyrproject.org/latest/reference/kernel/data_passing/pipes.html):
```
unsigned char buf[64];
struct k_pipe p;
size_t bytes_written = 0;
size_t bytes_read = 0;
char rxbuf[32] = {};

k_pipe_init(&p, buf, sizeof(buf));

k_pipe_put(&p, "Hi!", 3, &bytes_written, 3 /* min_xfer */, K_FOREVER);
// wrote 3 bytes
printf("Wrote Hi!\n");

k_pipe_get(&p, rxbuf, sizeof(rxbuf), &bytes_read, 1 /* min_xfer */, K_FOREVER);
// bytes_read should equal 3
// k_pipe_get() should return immediately since min_xfer is 1
// but hangs indefinitely
printf("Read '%s'\n", rxbuf);
```
**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=qemu_cortex_m3
3. make

**Expected behavior**

As per [the documentation](https://docs.zephyrproject.org/latest/reference/kernel/data_passing/pipes.html)

> Data can be synchronously received from a pipe by a thread. If the specified minimum number of bytes can not be immediately satisfied, then the operation will either fail immediately or attempt to receive as many bytes as possible and then pend in the hope that the receive can be completed later. Accepted data is either copied from the pipe’s ring buffer or directly from the waiting sender(s).

Since "the specified minimum number of bytes can be immediately satisfied", the call to `k_pipe_get()` should return immediately.

**Impact**
This is a showstopper for me if I would like to continue using the k_pipe API.

**Screenshots or console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: cross-compile
 - Commit SHA or Version used: 2833d016aa0b747c5c6fdd363dea4a9ebda941eb

**Additional context**

I can make a PR. Have a patch for it already. I wonder though if `k_pipe_put()` has the same problem. Will investigate.

### PR DESCRIPTION
**Pull request by cfriedt**
If `timeout != K_NO_WAIT`, then return immediately when not all `bytes_to_read` / `bytes_to_write` have been transfered, but `>= min_xfer` have been transferred.

Fixes #24485

### CODE REVIEW

File: kernel/pipes.c [hunk 1]
```diff
@@ -528,7 +528,18 @@ int z_pipe_put_internal(struct k_pipe *pipe, struct k_pipe_async *async_desc,
 		return 0;
 	}
 
-	/* Not all data was copied. */
+	if (K_TIMEOUT_EQ(timeout, K_FOREVER) && num_bytes_written >= min_xfer) {
```
Comment (andyross) [inline kernel/pipes.c:531]: How about `if (!K_TIMEOUT_EQ(timeout, K_NO_WAIT))` instead?

**Review by andyross — CHANGES_REQUESTED** [review]
This looks correct to me.  My one complaint is that's special casing K_FOREVER when, as I see it, we should be treating the timeout symmetrically.  That is, our behavior is wrong for non-zero finite timeouts too, and we should fix that at the same time.  I'm pretty sure it's just the change to the conditional.

And we should probably add a test of this behavior too..

File: kernel/pipes.c (hunk 1 above)
Comment (cfriedt) [reply kernel/pipes.c:531]: That could work. Will update.

**Review by andyross — APPROVED** [review]
Looks great to me, thanks.

**Comment by cfriedt** [comment]
@andyross - any idea what is up with Shippable? It looks like some invalid memory accesses are happening, particularly in [case 4](https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/69843/4/console).

I'm also encountering something similar with [my implementation of socketpair(2)](https://github.com/cfriedt/zephyr/tree/issue/24366/syscall-for-socketpair-2) (which does not include this change).

AFAICT, I'm just using the `k_pipe` API as prescribed in my test cases here, as well as in the socketpair(2) implementation.

Does it seem like something else is up with `k_pipe` to you?

**Comment by cfriedt** [comment]
I've created another issue (#24642) that demonstrates the issue on master.

**Comment by cfriedt** [comment]
> I've created another issue (#24642) that demonstrates the issue on master.

Learned about `k_object_alloc()` in #24642 which explains a lot. Latest revision should work fine everywhere.

**Comment by andyross** [comment]
> In short - kernel objects cannot be stack allocated!

They can, but not in userspace threads.   Also there may be a mode coming soon for cache-incoherent multiprocessors where the local stack will be cached where IPC data will be placed in uncached regions by default.  But yeah, it's virtually always best to declare these things statically using the existing initializer macros.

**Comment by cfriedt** [comment]
> > In short - kernel objects cannot be stack allocated!
> 
> They can, but not in userspace threads. Also there may be a mode coming soon for cache-incoherent multiprocessors where the local stack will be cached where IPC data will be placed in uncached regions by default. But yeah, it's virtually always best to declare these things statically using the existing initializer macros.

Ah, I see.

**Comment by carlescufi** [comment]
@nashif this is timing out, should we merge directly?

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
close/reopen to kick CI again

**Comment by nashif** [comment]
@cfriedt  the timeout is related to your change, please see why

tests/benchmarks/app_kernel is hanging with native_posix...


```sanitycheck -p native_posix -T tests/benchmarks/app_kernel -vv```

**Comment by nashif** [comment]
or `west build -b native_posix tests/benchmarks/app_kernel -t run`

**Comment by carlescufi** [comment]
> or `west build -b native_posix tests/benchmarks/app_kernel -t run`

Same here, I just checked and the test hangs forever as well when using this PR vs master

**Comment by carlescufi** [comment]
On the other hand, the test you modified passes correctly:

```
$ west build -b native_posix tests/kernel/pipe/pipe -t run
-- west build: running target run
[0/1] cd /home/carles/src/zephyr/zephyr/build && /home/carles/src/zephyr/zephyr/build/zephyr/zephyr.exe
*** Booting Zephyr OS build zephyr-v2.2.0-1792-g0014aeac3212  ***
Running test suite test_pipe
===================================================================
starting test - test_pipe_on_single_elements
PASS - test_pipe_on_single_elements
===================================================================
starting test - test_pipe_on_multiple_elements
PASS - test_pipe_on_multiple_elements
===================================================================
starting test - test_pipe_forever_wait
PASS - test_pipe_forever_wait
===================================================================
starting test - test_pipe_timeout
PASS - test_pipe_timeout
===================================================================
starting test - test_pipe_get_on_empty_pipe
PASS - test_pipe_get_on_empty_pipe
===================================================================
starting test - test_pipe_forever_timeout
PASS - test_pipe_forever_timeout
===================================================================
starting test - test_pipe_get_timeout
PASS - test_pipe_get_timeout
===================================================================
starting test - test_pipe_get_invalid_size
PASS - test_pipe_get_invalid_size
===================================================================
starting test - test_pipe_get_min_xfer
PASS - test_pipe_get_min_xfer
===================================================================
starting test - test_pipe_put_min_xfer
PASS - test_pipe_put_min_xfer
===================================================================
Test suite test_pipe succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
```

**Comment by andyross** [comment]
To be clear: we've had a nontrivial number of situations where tests have been written to demand what seems like genuinely buggy behavior.  Ping me if you get stuck.  I promise I'm personally convinced this behavior is what we want.

**Comment by carlescufi** [comment]
@cfriedt it seems stuck in `k_pipe_put()`:

```
(gdb) info threads
  Id   Target Id                                   Frame
* 1    Thread 0xf7fcea40 (LWP 130276) "zephyr.exe" 0xf7fd2b49 in __kernel_vsyscall ()
  3    Thread 0xf72ffb40 (LWP 130281) "zephyr.exe" 0x5655a9bd in k_pipe_put (data=<optimized out>, timeout=..., min_xfer=0, bytes_written=0xf72ff218, bytes_to_write=8, pipe=0x565677c0 <PIPE_NOBUFF>)
    at zephyr/include/generated/syscalls/kernel.h:939
  4    Thread 0xf6afeb40 (LWP 130282) "zephyr.exe" 0xf7fd2b49 in __kernel_vsyscall ()
  5    Thread 0xf60ffb40 (LWP 130283) "zephyr.exe" 0xf7fd2b49 in __kernel_vsyscall ()
(gdb) thread 3
[Switching to thread 3 (Thread 0xf72ffb40 (LWP 130281))]
#0  0x5655a9bd in k_pipe_put (data=<optimized out>, timeout=..., min_xfer=0, bytes_written=0xf72ff218, bytes_to_write=8, pipe=0x565677c0 <PIPE_NOBUFF>) at zephyr/include/generated/syscalls/kernel.h:939
939             return z_impl_k_pipe_put(pipe, data, bytes_to_write, bytes_written, min_xfer, timeout);
(gdb) bt
#0  0x5655a9bd in k_pipe_put (data=<optimized out>, timeout=..., min_xfer=0, bytes_written=0xf72ff218, bytes_to_write=8, pipe=0x565677c0 <PIPE_NOBUFF>) at zephyr/include/generated/syscalls/kernel.h:939
#1  pipeput (pipe=0x565677c0 <PIPE_NOBUFF>, option=_1_TO_N, size=8, count=256, time=0xf72ff290) at /home/carles/src/zephyr/zephyr/tests/benchmarks/app_kernel/src/pipe_b.c:219
#2  0x5655ad6c in pipe_test () at /home/carles/src/zephyr/zephyr/tests/benchmarks/app_kernel/src/pipe_b.c:169
#3  0x5655a38c in zephyr_app_main () at /home/carles/src/zephyr/zephyr/tests/benchmarks/app_kernel/src/master.c:140
#4  0x5655e34b in bg_thread_main (unused1=0x0, unused2=0x0, unused3=0x0) at /home/carles/src/zephyr/zephyr/kernel/init.c:261
#5  0x5655ba5e in z_thread_entry (entry=0x5655e303 <bg_thread_main>, p1=0x0, p2=0x0, p3=0x0) at /home/carles/src/zephyr/zephyr/lib/os/thread_entry.c:29
#6  0x5655c47f in posix_thread_starter (arg=0x0) at /home/carles/src/zephyr/zephyr/arch/posix/core/posix_core.c:305
#7  0xf7e90695 in start_thread (arg=0xf72ffb40) at pthread_create.c:479
#8  0xf7da2a5a in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:108
```

**Comment by carlescufi** [comment]
> To be clear: we've had a nontrivial number of situations where tests have been written to demand what seems like genuinely buggy behavior. Ping me if you get stuck. I promise I'm personally convinced this behavior is what we want.

It might well be that this PR needs to come with a change to `tests/benchmarks/app_kernel` then.

**Comment by cfriedt** [comment]
Interesting - thanks for looking at this test case everyone. From the stack trace @carlescufi provided, it looks as though `min_xfer = 0`, which is a case I'd not considered.

If `K_FOREVER` is specified as the timeout, and `min_xfer = 0`, then the current patch will return if zero bytes have been written. However, for a blocking write, normally at least 1 byte must be transferred in order to justify returning early.

I think the fix is to just add the extra condition `&& min_xfer > 0` to the condition for both `k_pipe_put()`  and `k_pipe_get()`.

Let me update the PR.

**Comment by carlescufi** [comment]
@cfriedt still stuck: https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/70528/2/console
