### PR TITLE
sd: sd_ops: take card lock when issuing IOCTL command

### LINKED ISSUE #72368: sd: sd_ops: Data Race in `card_ioctl`
The function `card_ioctl` in `subsys/sd/sd_ops.c` calls `sdmmc_wait_ready`, which calls `sdhc_card_busy` without taking the `card->lock` mutex. This leads to a data-race on the lower layers (for example spi).

Problematic line: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/sd/sd_ops.c#L790

Suggested fix:

```diff
-   switch (cmd) {
-   case DISK_IOCTL_GET_SECTOR_COUNT:
-       (*(uint32_t *)buf) = card->block_count;
-       break;
-   case DISK_IOCTL_GET_SECTOR_SIZE:
-   case DISK_IOCTL_GET_ERASE_BLOCK_SZ:
-       (*(uint32_t *)buf) = card->block_size;
-       break;
-   case DISK_IOCTL_CTRL_SYNC:
-       /* Ensure card is not busy with data write.
-        * Note that SD stack does not support enabling caching, so
-        * cache flush is not required here
-        */
-       return sdmmc_wait_ready(card);
-   default:
-       return -ENOTSUP;
-   }
-   return 0;
+   int ret = 0;
+   ret = k_mutex_lock(&card->lock, K_MSEC(CONFIG_SD_DATA_TIMEOUT));
+   if (ret) {
+       LOG_WRN("Could not get SD card mutex");
+       return -EBUSY;
+   }
+   switch (cmd) {
+   case DISK_IOCTL_GET_SECTOR_COUNT:
+   (*(uint32_t *)buf) = card->block_count;
+       break;
+   case DISK_IOCTL_GET_SECTOR_SIZE:
+   case DISK_IOCTL_GET_ERASE_BLOCK_SZ:
+       (*(uint32_t *)buf) = card->block_size;
+       break;
+   case DISK_IOCTL_CTRL_SYNC:
+       /* Ensure card is not busy with data write.
+        * Note that SD stack does not support enabling caching, so
+        * cache flush is not required here
+        */
+       ret = sdmmc_wait_ready(card);
+       break;
+   default:
+       ret = -ENOTSUP;
+       break;
+   }
+   k_mutex_unlock(&card->lock);
+   return ret;

```

To reproduce: two threads concurrently accessing the sd-card. At least one of them issues `ioclt`s. For example filesystem.

Expected behavior: No data race. With a data race, anything is possible. Of the possible scenarios, crashes are the least problematic.

Severly impacts all applications with concurrent access to the sd-card, when at least one of them uses `ioctl`.

Similar mutex problem in same file: https://github.com/zephyrproject-rtos/zephyr/issues/72287

Let me know, if you need additional information.

### PR DESCRIPTION
**Pull request by danieldegrasse**
Take card lock when running IOCTL command, to avoid race conditions that could occur within the lower SDHC transfer implementations (as these will be called by sdmmc_wait_ready)

Fixes #72368

### CODE REVIEW

File: subsys/sd/sd_ops.c [hunk 1]
```diff
@@ -774,6 +774,13 @@ int card_write_blocks(struct sd_card *card, const uint8_t *wbuf, uint32_t start_
 /* IO Control handler for SD MMC */
 int card_ioctl(struct sd_card *card, uint8_t cmd, void *buf)
 {
+	int ret;
+
+	ret = k_mutex_lock(&card->lock, K_MSEC(CONFIG_SD_DATA_TIMEOUT));
+	if (ret) {
+		LOG_WRN("Could not get SD card mutex");
+		return -EBUSY;
```
Comment (decsny) [inline subsys/sd/sd_ops.c:782]: why not return ret? ebusy from mutex lock means returned without waiting

File: subsys/sd/sd_ops.c [hunk 2]
```diff
@@ -787,9 +794,10 @@ int card_ioctl(struct sd_card *card, uint8_t cmd, void *buf)
...
 		 * cache flush is not required here
 		 */
-		return sdmmc_wait_ready(card);
+		ret = sdmmc_wait_ready(card);
 	default:
-		return -ENOTSUP;
+		ret = -ENOTSUP;
 	}
+	k_mutex_unlock(&card->lock);
 	return 0;
```
Comment (decsny) [inline subsys/sd/sd_ops.c:802]: you changed from immediate return above to setting ret, but don't return ret, is this supposed to return ret

Comment (danieldegrasse) [reply subsys/sd/sd_ops.c:802]: Yes, will fix this

File: subsys/sd/sd_ops.c (hunk 1 above)
Comment (danieldegrasse) [reply subsys/sd/sd_ops.c:782]: sure, I'll make this change

**Review by decsny — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
