### PR TITLE
drivers: fix and optimization of arc timer

### LINKED ISSUE #25178: tests/kernel/sched/schedule_api failed on iotdk board.
**To Reproduce**
1. west build -b iotdk -p auto  tests/kernel/sched/schedule_api
2. west flash
3. See error

**Screenshots or console output**
*** Booting Zephyr OS build zephyr-v2.2.0-2667-g57671d97165f  ***
Running test suite threads_scheduling

starting test - test_bad_priorities
PASS - test_bad_priorities

starting test - test_priority_cooperative
PASS - test_priority_cooperative

starting test - test_priority_preemptible
PASS - test_priority_preemptible

starting test - test_yield_cooperative
PASS - test_yield_cooperative

starting test - test_sleep_cooperative
PASS - test_sleep_cooperative

starting test - test_slice_scheduling
ABCDEFGHI
ABCDEFGHI
A
**Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
B
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
C**
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
D
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
E
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
F
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
G
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
H
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
I
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/sched/schedule_api/src/test_slice_scheduling.c:61: thread_tslice: ((tdelta >= expected_slice_min) && (tdelta <= expected_slice_max) && (idx == thread_idx)) is false
FAIL - test_slice_scheduling

starting test - test_priority_scheduling
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
ABCDEFGHI
PASS - test_priority_scheduling

starting test - test_wakeup_expired_timer_thread
PASS - test_wakeup_expired_timer_thread

starting test - test_user_k_wakeup
PASS - test_user_k_wakeup

starting test - test_user_k_is_preempt
PASS - test_user_k_is_preempt

Test suite threads_scheduling failed.

PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain : zephyr-sdk-0.11.2
 - Commit ID: 57671d971

### LINKED ISSUE #25179: tests/kernel/timer/timer_api failed on iotdk board.
**To Reproduce**
1. west build -b iotdk -p auto tests/kernel/timer/timer_api/
2. west flash
3. See error

**Screenshots or console output**
*** Booting Zephyr OS build zephyr-v2.2.0-2667-g57671d97165f  ***
Running test suite timer_api

starting test - test_time_conversions
PASS - test_time_conversions

starting test - test_timer_duration_period
PASS - test_timer_duration_period

starting test - test_timer_period_0
PASS - test_timer_period_0

starting test - test_timer_expirefn_null
PASS - test_timer_expirefn_null

starting test - test_timer_periodicity
PASS - test_timer_periodicity

starting test - test_timer_status_get
PASS - test_timer_status_get

**starting test - test_timer_status_get_anytime
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:335: test_timer_status_get_anytime: k_timer_status_get(&status_anytime_timer) == 4 is false
FAIL - test_timer_status_get_anytime**

starting test - test_timer_status_sync
PASS - test_timer_status_sync

starting test - test_timer_k_define
PASS - test_timer_k_define

starting test - test_timer_user_data
PASS - test_timer_user_data

starting test - test_timer_remaining
PASS - test_timer_remaining

starting test - test_timeout_abs
PASS - test_timeout_abs

Test suite timer_api failed.

PROJECT EXECUTION FAILED

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.2
 - Commit ID: 57671d9716

### PR DESCRIPTION
**Pull request by vonhust**
For single core:
   the pulse triggered timer irq doesn't work for all targets. In
   iotdk, we found the clear of IP bit will clear int request
   when elapsed called in thread context. So come back to level
   triggered way, and use the sw triggered irq to remember the
   irq request which may be cleared in thread context with an
   exception that elapsed called in timer irq handler.

For SMP:
* still need to clear IP bit in timer irq handler

* last_time should be aligned to ticks, old code will miss some
  cycles, (curret_time - last_time) % CYC_PER_TICK

* in timeout set, the operations of timer aux regs require some cycles
  , use MIN_DELAY to guarantee this.

Code optimizations:
* rename overflow_cyc to overflow_cycles for better understanding
* use MIN macro to replace if .. else ..

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

Fixes #25178 
Fixes #25179

### CODE REVIEW

File: drivers/timer/arcv2_timer0.c [hunk 1]
```diff
@@ -90,10 +90,10 @@ static u32_t announced_cycles;
  * in elapsed() function, as well as in the updates to cycle_count.
  *
  * Note:
- * Each time cycle_count is updated with the value from overflow_cyc,
- * the overflow_cyc must be reset to zero.
+ * Each time cycle_count is updated with the value from overflow_cycles,
+ * the overflow_cycles must be reset to zero.
  */
-static volatile u32_t overflow_cyc;
+static volatile u32_t overflow_cycles;
```
Comment (abrodkin) [inline drivers/timer/arcv2_timer0.c:96]: Cannot we leave this variable rename out of this change? This hides important functional changes in between beautification changes.

File: drivers/timer/arcv2_timer0.c [hunk 2]
```diff
@@ -384,11 +394,7 @@ void z_clock_set_timeout(s32_t ticks, bool idle)
 		delay -= unannounced;
 		delay = MAX(delay, MIN_DELAY);
 
-		if (delay > MAX_CYCLES) {
-			last_load = MAX_CYCLES;
-		} else {
-			last_load = delay;
-		}
+		last_load = MIN(delay, MAX_CYCLES);
```
Comment (abrodkin) [inline drivers/timer/arcv2_timer0.c:397]: I'd suggest to move it to a separate change as well as it has nothing to do with the main reason for this patch - yet another subtle yet quite fundamental redesign of Timer IRQ handling for ARC.

File: drivers/timer/arcv2_timer0.c [hunk 3]
```diff
@@ -322,7 +331,8 @@ void z_clock_set_timeout(s32_t ticks, bool idle)
 	ticks = MIN(MAX_TICKS, ticks);
 
 	/* Desired delay in the future */
-	delay = (ticks == 0) ? CYC_PER_TICK : ticks * CYC_PER_TICK;
+	delay = ticks * CYC_PER_TICK;
```
Comment (abrodkin) [inline drivers/timer/arcv2_timer0.c:334]: Same here - it's a good move to use much more readable `MAX` macro but especially given we change a functionality here a little bit (move from `CYC_PER_TICK` to `MIN_DELAY` in one case) I'd prefer to have it as a separate commit with clear explanation on why we can do such a transition. From visible diff context here and existing commit message I cannot understand why that change is possible at all and if it doesn't break anything.

**Review by abrodkin — CHANGES_REQUESTED** [review]
1. May we have more precise explanation of what and why doesn't work on IoTDK as expected. Why do we see behavior which differs from other boards? Is that ARC EM version that has some (known?) specifics or it's ARC core configuration which leads to such a behavior? In any case I'd like to see a reference either to some documentation or bug-tracker entry which has a valid explanation of this phenomenon.
2. Please de-couple clean-up changes from real meat of this fix/change so we may focus on important changes.
3. Given yet another iteration of our timer driver rework maybe we start from design specification where we may capture known problems and explain how are we trying to get the ultimate implementation that just works? :)

File: drivers/timer/arcv2_timer0.c [hunk 4]
```diff
@@ -190,13 +190,22 @@ static u32_t elapsed(void)
...
-		overflow_cyc += last_load;
+		overflow_cycles += last_load;
 		/* clear the IP bit of the control register */
 		timer0_control_register_set(_ARC_V2_TMR_CTRL_NH |
 					    _ARC_V2_TMR_CTRL_IE);
+		/* use sw triggered irq to remember the timer irq request
+		 * which may be cleared by the above operation, if called in
+		 * timer irq, no such a need
+		 */
+		if (!z_arc_v2_irq_unit_is_in_isr() ||
```
Comment (ruuddw) [inline drivers/timer/arcv2_timer0.c:201]: I think it would be better to not call elapsed() in the timer ISR, but duplicate the relevant part of this code there. Makes things easier to understand and less complex (avoids this check that I can't oversee is always correct).

**Comment by carlescufi** [comment]
@vonhust will you address the review comments this week? This fixes to high-priority bugs so it's important that we get it merged.

File: drivers/timer/arcv2_timer0.c (hunk 4 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c:201]: good idea

File: drivers/timer/arcv2_timer0.c (hunk 3 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c]: already changed

**Comment by vonhust** [comment]
> 1. May we have more precise explanation of what and why doesn't work on IoTDK as expected. Why do we see behavior which differs from other boards? Is that ARC EM version that has some (known?) specifics or it's ARC core configuration which leads to such a behavior? In any case I'd like to see a reference either to some documentation or bug-tracker entry which has a valid explanation of this phenomenon.
> 2. Please de-couple clean-up changes from real meat of this fix/change so we may focus on important changes.
> 3. Given yet another iteration of our timer driver rework maybe we start from design specification where we may capture known problems and explain how are we trying to get the ultimate implementation that just works? :)

I already split this PR into 3 commits.  For the root cause why iotdk doesn't work,  i think  it depends on how it configured in Architect.

File: drivers/timer/arcv2_timer0.c (hunk 1 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c:96]: It's already in different commit

File: drivers/timer/arcv2_timer0.c (hunk 2 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c:409]: It's already in different commit

File: drivers/timer/arcv2_timer0.c (hunk 4 above)
Comment (vonhust) [reply drivers/timer/arcv2_timer0.c:201]: elapsed() may be called multiple in timer_int_handler, one is at the beginning,  others are called in z_clock_announce -> z_clock_set_timeout.

So better to handle it in elapsed()

**Comment by vonhust** [comment]
@ruuddw  @abrodkin ,  now the sanitycheck tests of iotdk are clean.  Let's get it merged to fix the high priority issues, to not block the release of Zephyr.

**Review by abrodkin — APPROVED** [review]
LGTM now, thanks.

**Review by carlescufi — APPROVED** [review]

File: drivers/timer/arcv2_timer0.c (hunk 4 above)
Comment (ruuddw) [reply drivers/timer/arcv2_timer0.c:201]: Understood. Still, I'm not sure this solution is robust, e.g. if another interrupt handler calls elapsed() (reading the timer to get a timestamp for the input data).
And, I'd like to know why the pulse interrupts don't work on IoTDK.
