### PR TITLE
stm32u5: fix incorrect flas write width

### LINKED ISSUE #60724: stm32u5: incorrect write width
**Describe the bug**

Hello. I am playing with a **nucleo_u575zi_q** and noticed that the flash driver did not matched the reference manual when writing. While the manual specifies that only quad-words (128 bits, see Sec. 7.3.7 "Flash main memory programming sequences") can be used, the driver uses double-words (64 bits). The `write-block-size` is also set to 16 in the device tree, but this parameters is hardcoded to 8 at a couple of places in the driver. I wrote a small test program (see below) to settle who was right and the manual seems correct.

I did a quick workaround (see https://github.com/zephyrproject-rtos/zephyr/commit/7bcb8ebf38d9612511b173bf509e486645ac7e80) and the test program worked as expected. However the L5 seems to be using a width of 64 bits when writing, so a better solution would be needed. Maybe it would be nice to take the `write-block-size` from the device tree to remove some of the hardcoded constants?

I can propose a better fix if I get some feedback on the desired way to fix this issue.

**To Reproduce**

See the test program here: https://github.com/zephyrproject-rtos/zephyr/commit/4821b3c65c29956aa3230d1c81bdf1c5c13e4045. It is writing 8-byte and 16-byte blocks of random data in reverse order and reads back to compare. Both flash banks are tested.

Result with master: writing blocks of 8 bytes is allowed, but the readback is either 0xff or wrong. Writing 16 bytes at a time failed in the 1st bank but worked in the 2nd bank (by luck?). Output (edited for brevity):
```
*** Booting Zephyr OS build zephyr-v3.4.0-1418-g502ecaeac59b ***
Write block size: 16

Testing offset 1040384, write size 8:
---
 - Writing 8 bytes at offset 24
 - Writing 8 bytes at offset 16
 - Writing 8 bytes at offset 8
 - Writing 8 bytes at offset 0
 -> Error [0] = 255 (expected 119)
 -> Error [1] = 255 (expected 233)
(...)
 -> Error [30] = 255 (expected 221)
 -> Error [31] = 255 (expected 193)
FAIL

Testing offset 2088960, write size 8:
---
 - Writing 8 bytes at offset 24
 - Writing 8 bytes at offset 16
 - Writing 8 bytes at offset 8
 - Writing 8 bytes at offset 0
 -> Error [0] = 76 (expected 92)
 -> Error [1] = 145 (expected 39)
(...)
 -> Error [30] = 225 (expected 12)
 -> Error [31] = 65 (expected 222)
FAIL

Testing offset 1040384, write size 16:
---
 - Writing 16 bytes at offset 16
 - Writing 16 bytes at offset 0
 -> Error [16] = 255 (expected 193)
 -> Error [17] = 255 (expected 65)
(...)
 -> Error [30] = 255 (expected 136)
 -> Error [31] = 255 (expected 228)
FAIL

Testing offset 2088960, write size 16:
---
 - Writing 16 bytes at offset 16
 - Writing 16 bytes at offset 0
PASS
```

Result with my workaround: writing blocks of 8 bytes returns an error. Writing 16 bytes at a time works in both banks. Output:
```
*** Booting Zephyr OS build zephyr-v3.4.0-1418-g502ecaeac59b ***  
Write block size: 16  
  
Testing offset 1040384, write size 8:  
---  
- Writing 8 bytes at offset 24  
-> Write error -22  
FAIL  
  
Testing offset 2088960, write size 8:  
---  
- Writing 8 bytes at offset 24  
-> Write error -22  
FAIL  
  
Testing offset 1040384, write size 16:  
---  
- Writing 16 bytes at offset 16  
- Writing 16 bytes at offset 0  
PASS  
  
Testing offset 2088960, write size 16:  
---  
- Writing 16 bytes at offset 16  
- Writing 16 bytes at offset 0  
PASS
```

### PR DESCRIPTION
**Pull request by vaussard**
This fixes #60724 and it was tested on the nucleo_u575zi_q using the test program mentioned in the ticket.

I loosely inspired myself from `write_qword()` in drivers/flash/flash_stm32wbax.c. But I see now that `write_ndwords()` from drivers/flash/flash_stm32h7x.c is maybe a better example.

Other drivers are hardcoding the write block size in `flash_stm32_valid_range()`, we could consider giving them the same treatment:
```
drivers/flash/flash_stm32f1x.c:173:     return (!write || (offset % 2 == 0 && len % 2 == 0U)) &&  
drivers/flash/flash_stm32g0x.c:53:      return (!write || (offset % 8 == 0 && len % 8 == 0)) &&  
drivers/flash/flash_stm32g4x.c:45:      return (!write || (offset % 8 == 0 && len % 8 == 0U)) &&  
drivers/flash/flash_stm32l4x.c:41:      return (!write || (offset % 8 == 0 && len % 8 == 0U)) &&  
drivers/flash/flash_stm32wbax.c:116:    return (!write || (offset % 16 == 0 && len % 16 == 0U)) &&  
drivers/flash/flash_stm32wbx.c:36:      return (!write || (offset % 8 == 0 && len % 8 == 0U)) &&
```

### CODE REVIEW

**Comment by vaussard** [comment]
Note sure why twister fails in tests/subsys/pm/device_driver_init/ ?
```
INFO    - 614/614 qemu_cortex_m3            tests/subsys/pm/device_driver_init/pm.device_driver_init.pm_device_runtime  FAILED Failed (qemu 2.018s)
INFO    - /__w/zephyr/zephyr/twister-out/qemu_cortex_m3/tests/subsys/pm/device_driver_init/pm.device_driver_init.pm_device_runtime/handler.log
ERROR   - I: test_reg is now ON
I: test_reg_chained is now ON
*** Booting Zephyr OS build zephyr-v3.4.0-1554-g61873fab2882 ***
Running TESTSUITE device_driver_init
===================================================================
START - test_demo

    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/pm/device_driver_init/src/main.c:38: device_driver_init_test_demo: (gpio_config not equal to ((1U << 17) | (1U << 19)))
Unexpected config
 FAIL - test_demo in 0.001 seconds
===================================================================
TESTSUITE device_driver_init failed.
```

**Comment by erwango** [comment]
> device_driver_init

@JordanYates Does this ring any bell ?

File: drivers/flash/flash_stm32l5x.c [hunk 1]
```diff
@@ -158,11 +158,13 @@ bool flash_stm32_valid_range(const struct device *dev, off_t offset,
...
 }
 
-static int write_dword(const struct device *dev, off_t offset, uint64_t val)
+static int write_words(const struct device *dev, off_t offset, const uint32_t *buff)
 {
 	FLASH_TypeDef *regs = FLASH_STM32_REGS(dev);
 	volatile uint32_t *flash = (uint32_t *)(offset
 						+ CONFIG_FLASH_BASE_ADDRESS);
+	bool full_zero;
+	unsigned int i;
```
Comment (erwango) [inline drivers/flash/flash_stm32l5x.c:167]: Why not int ?

File: drivers/flash/flash_stm32l5x.c [hunk 2]
```diff
@@ -178,16 +180,27 @@ static int write_dword(const struct device *dev, off_t offset, uint64_t val)
...
-		return -EIO;
+	full_zero = true;
+	for (i = 0; i < FLASH_STM32_WRITE_BLOCK_SIZE; i++) {
+		if (buff[i] != 0) {
+			full_zero = false;
+			break;
+		}
+	}
+	if (full_zero) {
+		for (unsigned int i = 0; i < FLASH_STM32_WRITE_BLOCK_SIZE; i++) {
```
Comment (erwango) [inline drivers/flash/flash_stm32l5x.c:198]:
```suggestion
		for (i = 0; i < FLASH_STM32_WRITE_BLOCK_SIZE; i++) {
```

File: drivers/flash/flash_stm32l5x.c [hunk 3]
```diff
@@ -197,8 +210,9 @@ static int write_dword(const struct device *dev, off_t offset, uint64_t val)
 	tmp = regs->NSCR;
 
 	/* Perform the data write operation at the desired memory address */
-	flash[0] = (uint32_t)val;
-	flash[1] = (uint32_t)(val >> 32);
+	for (unsigned int i = 0; i < FLASH_STM32_WRITE_BLOCK_SIZE; i++) {
```
Comment (erwango) [inline drivers/flash/flash_stm32l5x.c:213]:
```suggestion
	for (i = 0; i < FLASH_STM32_WRITE_BLOCK_SIZE; i++) {
```

File: drivers/flash/flash_stm32l5x.c [hunk 4]
```diff
@@ -178,16 +180,27 @@ static int write_dword(const struct device *dev, off_t offset, uint64_t val)
...
+	 * It is allowed to write only zeros over an already written dword / qword
 	 * See 6.3.7 in STM32L5 reference manual.
 	 * See 7.3.7 in STM32U5 reference manual.
+	 * See 7.3.5 in STM32H5 reference manual.
 	 */
-	if ((flash[0] != 0xFFFFFFFFUL ||
-	     flash[1] != 0xFFFFFFFFUL) && val != 0UL) {
-		LOG_ERR("Word at offs %ld not erased", (long)offset);
-		return -EIO;
+	full_zero = true;
```
Comment (erwango) [inline drivers/flash/flash_stm32l5x.c:190]: Can  you initialize it at declaration ?

**Comment by JordanYates** [comment]
> > device_driver_init
> 
> @JordanYates Does this ring any bell ?

Yes this was caused by a combination of premature merging of #60411 and the changes introduced by #60458.
Reverting that PR will fix this issue.

File: drivers/flash/flash_stm32l5x.c [hunk 5]
```diff
@@ -178,16 +180,27 @@ static int write_dword(const struct device *dev, off_t offset, uint64_t val)
...
+	for (i = 0; i < FLASH_STM32_WRITE_BLOCK_SIZE; i++) {
+		if (buff[i] != 0) {
+			full_zero = false;
+			break;
+		}
+	}
+	if (full_zero) {
```
Comment (erwango) [inline drivers/flash/flash_stm32l5x.c:197]: If I'm not mistaking, you're reverting the logic here.
It would be clearer to check:
- first: is the target zone not erased
- second: if not erased, verify that value is full_zeroes, error out if not the case.

**Review by erwango — CHANGES_REQUESTED** [review]
Thanks for this
Some comments, and ideally as you mentioned `flash_stm32_valid_range` couldbe extended to most series. What about defining as weak  in flash_stm32.h? so it could be used as is unless a specific function is added when required

File: drivers/flash/flash_stm32l5x.c (hunk 5 above)
Comment (vaussard) [reply drivers/flash/flash_stm32l5x.c:197]: Indeed it is reversed, but this is on purpose: the flash access is presumably much slower than a RAM access. So it is faster to check if the value is zero, and only then check the flash in the rare event that we write 0x00(...)00. In most cases, we can completely skip reading the flash. I can add a comment to make it more clear.

**Comment by vaussard** [comment]
> What about defining as weak in flash_stm32.h?

Sure this sounds good. Why not in flash_stm32.c ?

File: drivers/flash/flash_stm32l5x.c (hunk 5 above)
Comment (erwango) [reply drivers/flash/flash_stm32l5x.c:197]: ok, then you should test `if (!full_zero) {`

Comment (vaussard) [reply drivers/flash/flash_stm32l5x.c]: oh sure, sorry for this bug

**Comment by vaussard** [comment]
@erwango updated according to your suggestions. Ready for another review. Thanks!

**Review by erwango — APPROVED** [review]
That looks great.
Thanks @vaussard. Approving but blocking until we manage to perform HW tests.

**Comment by erwango** [comment]
Tested ok

**Comment by vaussard** [comment]
Many thanks @erwango.

**Review by FRASTM — APPROVED** [review]
