### PR TITLE
posix: eventfd: fix read deadlock and add test coverage

### LINKED ISSUE #58426: posix: eventfd: deadlock on blocking read
**Describe the bug**
The prototypical `eventfd()` pattern is to call `eventfd_read(fd, &val)` in one thread and call `eventfd_write(fd, val)` from another thread to "wake up" the read thread.

However, in Zephyr, this results in a deadlock.

The root cause is the fdtable lock [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/posix/sys/eventfd.h#L89).

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? any tier0 platform such as `qemu_x86_64`, `qemu_riscv64`, or `mps2_an385`
 - What have you tried to diagnose or workaround this issue? I wrote a testcase. The workaround is to use `poll()`, but that is a pain.
 - Is this a regression? No, it has always been a bug.

**To Reproduce**
1. check out https://github.com/zephyrproject-rtos/zephyr/pull/58406 (or `main` if merged)
2. apply the patch below
3. `west build -p auto -b qemu_riscv64 -t run tests/posix/eventfd`
4. Wait forever

This will also time out when run with twister, so alternatively, run
3. `twister -i -p qemu_riscv64 -T tests/posix/eventfd`

**Expected behavior**
The prototypical `eventfd()` behaviour should work as expected.

**Impact**
This is a showstopper for my particular use case

**Logs and console output**
```shell
*** Booting Zephyr OS build v3.4.0-rc1-29-g7d71aba0987a ***
Running TESTSUITE eventfd
===================================================================
START - test_overflow
 PASS - test_overflow in 0.002 seconds
===================================================================
START - test_poll_timeout
 PASS - test_poll_timeout in 0.509 seconds
===================================================================
START - test_read_nonblock
 PASS - test_read_nonblock in 0.001 seconds
===================================================================
START - test_read_then_write_block
... 
<hangs forever>
```

**Environment (please complete the following information):**
 - OS: macOS
 - Toolchain: Zephyr SDK v0.16.1
 - Commit SHA or Version used: 5f5b34793dc89a3ee5a33c566333760323e57fa0

**Additional context**
```patch
diff --git a/tests/posix/eventfd/src/blocking.c b/tests/posix/eventfd/src/blocking.c
index 5189cd9aba..2f474b05a3 100644
--- a/tests/posix/eventfd/src/blocking.c
+++ b/tests/posix/eventfd/src/blocking.c
@@ -74,3 +74,30 @@ ZTEST_F(eventfd, test_unset_poll_event_block)
 {
 	eventfd_poll_unset_common(fixture->fd);
 }
+
+K_THREAD_STACK_DEFINE(thread_stack, 1024);
+
+static void thread_fun(void *arg1, void *arg2, void *arg3)
+{
+	eventfd_t value;
+	struct eventfd_fixture *fixture = arg1;
+
+	zassert_ok(eventfd_read(fixture->fd, &value));
+	zassert_equal(value, 42);
+}
+
+ZTEST_F(eventfd, test_read_then_write_block)
+{
+	struct k_thread thread;
+
+	/* k_thread_stack_t *stack, size_t stack_size, k_thread_entry_t entry, void * p1, void * p2, void * p3, int prio, uint32_t options, k_timeout_t delay) */
+	k_thread_create(&thread, thread_stack, 1024, thread_fun, fixture, NULL, NULL, 0, 0, K_NO_WAIT);
+
+	k_msleep(100);
+
+	/* this write never occurs */
+	zassert_ok(eventfd_write(fixture->fd, 42));
+
+	/* unreachable code */
+	k_thread_join(&thread, K_FOREVER);
+}
```

A simple C++ app for Linux demonstrates prototypical behaviour working as expected
```cpp
#include <iostream>
#include <thread>

#include <sys/eventfd.h>
#include <unistd.h>

int main(int argc, char **argv)
{
  int efd = eventfd(0, 0);
  std::thread th([&]{
        eventfd_t val;
        eventfd_read(efd, &val);
        std::cout << "val is " << val << std::endl;
  });
  sleep(1);
  eventfd_write(efd, 42);
  th.join();
  return 0;
}
```
compile & run:
```shell
g++ -o eventfd-example eventfd-example.cpp
./eventfd-example
val is 42
```

### PR DESCRIPTION
**Pull request by cfriedt**
7 commits (please see each commit message for details)

* tests: posix: eventfd: use reopen in test_write_then_read (should have gone into #58406)
* lib: os: add `k_condvar` for each fdtable entry
* posix: eventfd: un-inline `eventfd_read()` and `eventfd_write()`
* posix: eventfd: revise locking, signaling, and allocation
* tests: posix: eventfd: blocking read-write test for deadlock bug
* posix: eventfd: deprecate non-public EFD macros
* tests: posix: eventfd: add stress test

Fixes #58426

Note: this improves non-blocking `eventfd` performance significantly.

I would suggest reading each commit individually with the exception of the eventfd revision.

For that one, it's probably easiest just to look at the end result [here](https://github.com/zephyrproject-rtos/zephyr/blob/5d67c8a8037d0c6b974cdc45ae2e779fae8a5c42/lib/posix/eventfd.c).

### CODE REVIEW

File: lib/posix/eventfd.c [hunk 1]
```diff
@@ -239,6 +134,170 @@ static int eventfd_ioctl_op(void *obj, unsigned int request, va_list args)
...
+		}
+
+		ret = k_mutex_unlock(lock);
+		__ASSERT(ret == 0, "k_mutex_unlock() failed: %d", ret);
+	}
+
+	return 0;
+}
+
+static ssize_t eventfd_write_op(void *obj, const void *buf, size_t sz)
```
Comment (cfriedt) [inline lib/posix/eventfd.c:227]: Needs to return the number of bytes written on success.

File: lib/posix/eventfd.c [hunk 2]
```diff
@@ -239,6 +134,170 @@ static int eventfd_ioctl_op(void *obj, unsigned int request, va_list args)
...
+	if (!z_get_obj_lock_and_cond(obj, &eventfd_fd_vtable, lock, cond)) {
+		__ASSERT(false, "z_get_obj_lock_and_cond() failed for previously validated fd");
+	}
+	__ASSERT_NO_MSG(*lock != NULL);
+	__ASSERT_NO_MSG(*cond != NULL);
+
+	return 0;
+}
+
+static ssize_t eventfd_read_op(void *obj, void *buf, size_t sz)
```
Comment (cfriedt) [inline lib/posix/eventfd.c:161]: Needs to return the number of bytes read on success, not 0

File: lib/posix/eventfd.c [hunk 3]
```diff
@@ -248,49 +307,56 @@ static const struct fd_op_vtable eventfd_fd_vtable = {
...
+	void *obj;
+
+	obj = z_get_fd_obj(fd, &eventfd_fd_vtable, EBADF);
+	if (obj == NULL) {
+		return -1;
 	}
-	k_poll_signal_raise(&efd->write_sig, 0);
 
-	z_finalize_fd(fd, efd, &eventfd_fd_vtable);
+	return eventfd_read_op(obj, value, sizeof(*value));
```
Comment (cfriedt) [inline lib/posix/eventfd.c:349]: Return 0 on success (i.e. if `eventfd_read_op()` reads `sizeof(*value)` bytes)

**Comment by cfriedt** [comment]
* added Meta copyright since `lib/posix/eventfd.c` was more or less a complete rewrite

**Comment by cfriedt** [comment]
This should probably be merged after #58743

**Comment by cfriedt** [comment]
Marking `DNM` for today.

I'm going to do another respin of this with special consideration given to the case where `O_NONBLOCK` is specified, but also taking into account some of the potential race conditions that could occur between threads attempting to access the same file descriptor - e.g. `poll()` vs `close()`.

**Review by andyross — DISMISSED** [review]
Looks good.  I didn't do a hugely deep dive into the synchronization strategy, but the description makes sense and the code seems to match.

**Comment by cfriedt** [comment]
I think that will do - PTAL @andyross, when you have a minute.

```shell
twister -i -p mps2_an385 -p qemu_riscv64 -p qemu_cortex_a53 -p qemu_x86_64 -p qemu_riscv64_smp -p qemu_cortex_a53_smp -T tests/posix/eventfd/
Renaming output directory to /home/cfriedt/zephyrproject/zephyr/twister-out.5
INFO    - Using Ninja..
INFO    - Zephyr version: v3.4.0-rc1-101-g5d67c8a8037d
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report /home/cfriedt/zephyrproject/zephyr/twister-out/testplan.json
INFO    - JOBS: 32
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete:    6/   6  100%  skipped:    0, failed:    0, error:    0
INFO    - 1 test scenarios (6 test instances) selected, 0 configurations skipped (0 by static filter, 0 at runtime).
INFO    - 6 of 6 test configurations passed (100.00%), 0 failed, 0 errored, 0 skipped with 0 warnings in 9.52 seconds
INFO    - In total 60 test cases were executed, 0 skipped on 6 out of total 573 platforms (1.05%)
INFO    - 6 test configurations executed on platforms, 0 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing JSON report /home/cfriedt/zephyrproject/zephyr/twister-out/twister.json
INFO    - Writing xunit report /home/cfriedt/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/cfriedt/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed
```

**Comment by cfriedt** [comment]
I would suggest reading each commit individually with the exception of the eventfd revision.

For that one, it's probably easiest just to look at the end result [here](https://github.com/zephyrproject-rtos/zephyr/blob/5d67c8a8037d0c6b974cdc45ae2e779fae8a5c42/lib/posix/eventfd.c).

File: lib/posix/eventfd.c [hunk 4]
```diff
@@ -246,51 +262,181 @@ static const struct fd_op_vtable eventfd_fd_vtable = {
...
+	__ASSERT(err == 0, "k_mutex_lock() failed: %d", err);
 
-	for (i = 0; i < ARRAY_SIZE(efds); ++i) {
-		if (!(efds[i].flags & EFD_IN_USE)) {
-			efd = &efds[i];
+	while (true) {
+		/* retake the spinlock */
+		key = k_spin_lock(&efd->lock);
+
+		ret = op(efd, buf);
```
Comment (jgl-meta) [inline lib/posix/eventfd.c:329]: How safe is it to allow a caller defined function to be called while holding the spin lock?

I guess it is somewhat moot since it is clearly necessary to lock here. Just asking for curiosity.

File: lib/posix/eventfd.c [hunk 5]
```diff
@@ -246,51 +262,181 @@ static const struct fd_op_vtable eventfd_fd_vtable = {
...
+	}
+
+	err = (int)z_get_obj_lock_and_cond(obj, &eventfd_fd_vtable, &lock, &cond);
+	__ASSERT((bool)err, "z_get_obj_lock_and_cond() failed");
+	__ASSERT_NO_MSG(lock != NULL);
+	__ASSERT_NO_MSG(cond != NULL);
+
+	/* do not hold a spinlock when taking a mutex */
+	k_spin_unlock(&efd->lock, key);
+	err = k_mutex_lock(lock, K_FOREVER);
```
Comment (jgl-meta) [inline lib/posix/eventfd.c:322]: I think these next few lines of code could lead to one of the classic examples for deadlock 

t1: unlock(a) lock(b) lock(a)

and if another thread tries to acquire both locks then:
t2: lock(a) lock(b)
= deadlock

Is this scenario possible here? 

That said I think it is clear that you have to give up the spin lock before trying to lock the mutex. Just curious if the scenario is possible.

File: lib/posix/eventfd.c [hunk 6]
```diff
@@ -246,51 +262,181 @@ static const struct fd_op_vtable eventfd_fd_vtable = {
...
+			goto unlock_mutex;
+		default:
+			/* some other error */
+			__ASSERT_NO_MSG(ret < 0);
+			errno = -ret;
+			ret = -1;
+			goto unlock_mutex;
 		}
+
+		/* do not hold a spinlock when taking a mutex */
```
Comment (jgl-meta) [inline lib/posix/eventfd.c:346]: nit: while waiting of a condition variable maybe would be better?

File: lib/posix/eventfd.c [hunk 7]
```diff
@@ -246,51 +262,181 @@ static const struct fd_op_vtable eventfd_fd_vtable = {
...
+	void *obj;
+
+	obj = z_get_fd_obj(fd, &eventfd_fd_vtable, EBADF);
+	if (obj == NULL) {
+		return -1;
+	}
+
+	ret = eventfd_rw_op(obj, &value, sizeof(eventfd_t), eventfd_write_locked);
+	__ASSERT_NO_MSG(ret == -1 || ret == sizeof(eventfd_t));
+	if (ret < 0) {
```
Comment (jgl-meta) [inline lib/posix/eventfd.c:437]: Is this superfluous? Does it have to be -1 can you just return ret?

**Review by jgl-meta — APPROVED** [review]
A few small questions and comments. But I don't think anything to hold this back for if it addresses the problem.

**Review by jgl-meta — DISMISSED** [review]
A few small questions and comments. But I don't think anything to hold this back for if it addresses the problem.

File: lib/posix/eventfd.c (hunk 4 above)
Comment (cfriedt) [reply lib/posix/eventfd.c:329]: This function is static and the only functions that are being passed in are `eventfd_read_locked()` and `eventfd_wrote_locked()`

File: lib/posix/eventfd.c (hunk 5 above)
Comment (cfriedt) [reply lib/posix/eventfd.c:322]: > Is this scenario possible here? 

I can see why you might think that based on your earlier question.

Since `op()` is only either `eventfd_read_locked()` or 
`eventfd_write_locked()` any threads executing those functions will never be stalled on anything, so you can ignore the inner spin lock / unlock.


What you're left with is just the outer muted lock / unlock, which is business as usual.

File: lib/posix/eventfd.c (hunk 6 above)
Comment (cfriedt) [reply lib/posix/eventfd.c:346]: You take the muted as part of waiting on the condition variable

File: lib/posix/eventfd.c (hunk 7 above)
Comment (cfriedt) [reply lib/posix/eventfd.c:437]: The return value needs to be either 0 or -1, but `ret` will be either -1 or `sizeof(eventfd_t)`.

Technically, I could have made a comparison against 0 as well, I just tend to prefer branching in the error case.

**Comment by cfriedt** [comment]
> A few small questions and comments. But I don't think anything to hold this back for if it addresses the problem.

Hehe.. it's definitely functional. I would guess that it's also reasonably fast too, especially in the nong-blocking case.

**Comment by cfriedt** [comment]
@andyross - you might be impressed by the performance improvement 😁 
@jgl-meta - PTAL
@keith-packard, @stephanosio - PTAL if you're interested as well

**Review by jgl-meta — APPROVED** [review]

**Review by jgl-meta — DISMISSED** [review]

**Comment by cfriedt** [comment]
Was rushing out the door and forgot to update the last commit. Stuck in horrible traffic right now 😭

**Comment by cfriedt** [comment]
With `-DCONFIG_ASSERT=n` even higher throughput.
```shell
START - test_stress
I: BOARD: qemu_riscv64_smp
I: TEST_DURATION_S: 5
I: UPDATE_INTERVAL_S: 1
I: avg: 135537 writes/s
I: avg: 135472 reads/s
 PASS - test_stress in 5.002 seconds
```

I'll see if I can produce a flame graph before and after these changes... could be tricky though given that `CONFIG_ARCH_POSIX` and `CONFIG_POSIX_API` are still mutually exclusive.

**Comment by cfriedt** [comment]
Remove logging from the testsuite, because it resulted in Compliance false positives.

**Comment by cfriedt** [comment]
Probably the best apples-to-apples performance comparison can be made with this, before and after the changeset.
```shell
west build -p auto -b qemu_riscv64_smp -t run tests/posix/eventfd/ -- -DCONFIG_TEST_EXTRA_QUIET=y -DCONFIG_ASSERT=n
```

Before:
```shell
START - test_stress
BOARD: qemu_riscv64_smp
TEST_DURATION_S: 5
UPDATE_INTERVAL_S: 1
avg: 11093 reads/s
avg: 11094 writes/s
 PASS - test_stress in 4.998 seconds
```

After:
```shell
START - test_stress
BOARD: qemu_riscv64_smp
TEST_DURATION_S: 5
UPDATE_INTERVAL_S: 1
avg: 101623 reads/s
avg: 101624 writes/s
 PASS - test_stress in 4.999 seconds
```

```shell
echo "101623/11093" | bc -l
9.16100243396736680789
```

So just under a 10x performance improvement at the end of the day.

**Review by jgl-meta — APPROVED** [review]

**Review by luchnikov — APPROVED** [review]

**Review by luchnikov — APPROVED** [review]

**Review by luchnikov — APPROVED** [review]

File: include/zephyr/sys/fdtable.h [hunk 8]
```diff
@@ -107,6 +107,24 @@ void *z_get_fd_obj(int fd, const struct fd_op_vtable *vtable, int err);
...
+ *        preventing concurrent descriptor access. The lock is not taken,
+ *        it is just returned for the caller to use if necessary. Pass NULL
+ *        if the lock is not needed by the caller.
+ * @param cond An optional pointer to a pointer variable to store the condition variable
+ *        to notify waiting threads in the case of concurrent descriptor access. Pass NULL
+ *        if the condition variable is not needed by the caller.
+ *
+ * @return `true` on success, `false` otherwise.
+ */
+bool z_get_obj_lock_and_cond(void *obj, const struct fd_op_vtable *vtable, struct k_mutex **lock,
```
Comment (nashif) [inline include/zephyr/sys/fdtable.h:125]: z_ is reserved for private functions and calls, this header is full of z_ call and it is a public API, we need to fix this at some point.

**Review by nashif — APPROVED** [review]

File: include/zephyr/sys/fdtable.h (hunk 8 above)
Comment (cfriedt) [reply include/zephyr/sys/fdtable.h:125]: cc @jgl-meta

Comment (cfriedt) [reply include/zephyr/sys/fdtable.h:125]: >  header is full of z_ call and it is a public API, we need to fix this at some point. 

@nashif - what do you think of "zvfs" or "zfdio"?

**Review by andyross — COMMENTED** [review]
Missed the +1 before it merged, but just for the record I can't see anything wrong with the synchronization.

File: tests/posix/eventfd/Kconfig [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+# SPDX-License-Identifier: Apache-2.0
+
+source "Kconfig.zephyr"
+
+config TEST_DURATION_S
+	int "Number of seconds to run the test"
+	range 1 21600
+	default 5
+	help
+	   Duration for the test, in seconds. The range has a reblatively high
```
Comment (cfriedt) [inline tests/posix/eventfd/Kconfig:12]: "reblatively" - never fails that there will be at least one typo 😅
