### PR TITLE
drivers: wifi: esp32: Fix AP-STA mode interface init order

### LINKED ISSUE #81744: Sample WiFi:apsta_mode didn't work with ESP32S3
**Describe the bug**
I am running a dual mode (AP and STA) function test with the ESP32S3. However, it encounters an issue on the DHCPV4 Server side.
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40378ca5
SPIWP:0xee
mode:DIO, clock div:2
load:0x3fc95ab0,len:0x3b40
load:0x40374000,len:0x11a90
SHA-256 comparison failed:
Calculated: e969b2232861ba27434428cd9a81d3779c983520abb3ef697b278bc2e40e97c2
Expected: 00000000f0a90000000000000000000000000000000000000000000000000000
Attempting to boot anyway...
entry 0x4037c7b0
I (100) boot: ESP Simple boot
I (100) boot: compile time Nov 22 2024 11:07:27
W (100) boot: Unicore bootloader
I (101) spi_flash: detected chip: gd
I (102) spi_flash: flash io: dio
W (105) spi_flash: Detected size(8192k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (121) boot: chip revision: v0.2
I (121) boot.esp32s3: Boot SPI Speed : 40MHz
I (124) boot.esp32s3: SPI Mode       : DIO
I (128) boot.esp32s3: SPI Flash Size : 8MB
I (132) boot: Enabling RNG early entropy source...
I (136) boot: DRAM: lma 0x00000020 vma 0x3fc95ab0 len 0x3b40   (15168)
I (143) boot: IRAM: lma 0x00003b68 vma 0x40374000 len 0x11a90  (72336)
I (149) boot: padd: lma 0x00015608 vma 0x00000000 len 0xa9f0   (43504)
I (155) boot: IMAP: lma 0x00020000 vma 0x42000000 len 0x4ff18  (327448)
I (162) boot: padd: lma 0x0006ff20 vma 0x00000000 len 0xd8     (216)
I (168) boot: DMAP: lma 0x00070000 vma 0x3c050000 len 0xc7b4   (51124)
I (174) boot: Image with 6 segments
I (177) boot: DROM segment: paddr=00070000h, vaddr=3c050000h, size=0C7C0h ( 51136) map
I (185) boot: IROM segment: paddr=00020000h, vaddr=42000000h, size=4FF16h (327446) map
I (228) heap_runtime: ESP heap runtime init at 0x3fcad628 size 240 kB.

[00:00:00.232,000] <inf> wifi_init: rx ba win: 6
[00:00:00.232,000] <inf> wifi_init: WiFi IRAM OP enabled
*** Booting Zephyr OS build v4.0.0 ***
[00:00:05.234,000] <inf> MAIN: Turning on AP Mode
[00:00:05.235,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: Started DHCPv4 server, address pool:
[00:00:05.235,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     0: 192.168.4.11
[00:00:05.235,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     1: 192.168.4.12
[00:00:05.235,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     2: 192.168.4.13
[00:00:05.235,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     3: 192.168.4.14
[00:00:05.235,000] <inf> MAIN: DHCPv4 server started...

[00:00:05.267,000] <err> esp32_wifi: Failed to send packet
[00:00:05.268,000] <err> esp32_wifi: Failed to send packet
[00:00:05.268,000] <err> esp32_wifi: Failed to send packet
[00:00:05.268,000] <err> esp32_wifi: Failed to send packet
[00:00:05.269,000] <inf> MAIN: AP Mode is enabled. Waiting for station to connect
[00:00:05.269,000] <inf> MAIN: Connecting to SSID: SSID

[00:00:05.271,000] <err> esp32_wifi: Failed to send packet
[00:00:05.272,000] <err> esp32_wifi: Failed to send packet
[00:00:05.272,000] <err> esp32_wifi: Failed to send packet
[00:00:05.272,000] <err> esp32_wifi: Failed to send packet
[00:00:05.273,000] <err> esp32_wifi: Wi-Fi not in station mode
[00:00:05.273,000] <inf> MAIN: Connected to SSID
[00:00:05.273,000] <err> MAIN: Unable to Connect to (SSID)
[00:00:06.269,000] <err> esp32_wifi: Failed to send packet
[00:00:06.273,000] <err> esp32_wifi: Failed to send packet
[00:00:07.269,000] <err> esp32_wifi: Failed to send packet
[00:00:07.273,000] <err> esp32_wifi: Failed to send packet
[00:00:10.239,000] <inf> MAIN: station: 42:31:98:67:F1:5D joined
[00:00:10.655,000] <err> esp32_wifi: Failed to send packet
[00:00:10.655,000] <dbg> net_dhcpv4_server: dhcpv4_handle_discover: DHCPv4 processing Discover - reserved 192.168.4.11
[00:00:11.657,000] <err> esp32_wifi: Failed to send packet
[00:00:11.663,000] <err> esp32_wifi: Failed to send packet
[00:00:11.663,000] <dbg> net_dhcpv4_server: dhcpv4_handle_discover: DHCPv4 processing Discover - reserved 192.168.4.11
[00:00:13.570,000] <err> esp32_wifi: Failed to send packet
[00:00:13.570,000] <dbg> net_dhcpv4_server: dhcpv4_handle_discover: DHCPv4 processing Discover - reserved 192.168.4.11
[00:00:17.620,000] <err> esp32_wifi: Failed to send packet
[00:00:17.620,000] <dbg> net_dhcpv4_server: dhcpv4_handle_discover: DHCPv4 processing Discover - reserved 192.168.4.11
[00:00:25.418,000] <err> esp32_wifi: Failed to send packet
[00:00:25.418,000] <dbg> net_dhcpv4_server: dhcpv4_handle_discover: DHCPv4 processing Discover - reserved 192.168.4.11
[00:00:28.503,000] <inf> MAIN: station: 42:31:98:67:F1:5D leave
[00:00:55.418,000] <dbg> net_dhcpv4_server: dhcpv4_server_timeout: Address 192.168.4.11 expired
[00:00:55.419,000] <dbg> net_dhcpv4_server: dhcpv4_server_timeout_recalc: No more addresses, canceling timer
```
**To Reproduce**
Simply build the settings example and run it:
```
west build -p always zephyr/samples/net/wifi/apsta_mode -b esp32s3_devkitm/esp32s3/procpu && west flash && west espressif monitor
```

**Expected behavior**
The ESP32S3 should create a connection with the SSID: ESP32-AP and allow connections (successfully assigning IP).

**Logs and console output**
I modified the error API `esp32_wifi_send` to get the error value. It return error (0x3007) 
```
#define ESP_ERR_WIFI_CONN              (ESP_ERR_WIFI_BASE + 7)   /*!< WiFi internal control block of station or soft-AP error */
```

**Impact**
Version v3.7.0 runs quite stable with the features of Access Point & DHCPV4 server. When upgrading to version v4.0.0, it encounters this issue, and I think it significantly affects programs that need to use the DHCPV4 server.

**Environment:**
 - OS: MacOS, Linux or Windows
 - Toolchain: Zephyr SDK v0.16.8
 - Zephyr v4.0.0

### LINKED ISSUE #83775: ESP32 Wifi driver call NULL callback when request scanning
**Describe the bug**

ESP32 Wifi driver call NULL callback after done scanning on STA interface and Enable CONFIG_ESP32_WIFI_AP_STA_MODE.
The issue happened in function: `scan_done_handler(void)` in esp_wifi_drv.c
This functions used the callback stored in its private data instead of the correct callback passed from `struct device` from upper layer.
```
out:
	/* report end of scan event */
	esp32_data.scan_cb(esp32_wifi_iface, 0, NULL);
	esp32_data.scan_cb = NULL;
```

**To Reproduce**
This is my example code, if changing to interface from net_if_get_wifi_sap(), this issue won't happen

```
	struct net_if *iface = net_if_get_wifi_sta();
	struct wifi_scan_params params = {
		0
	};
	params.max_bss_cnt = 10;
	params.bands = WIFI_FREQ_BAND_2_4_GHZ;
	params.scan_type = WIFI_SCAN_TYPE_ACTIVE;
	params.dwell_time_active = 10000;
	params.band_chan[0] = (struct wifi_band_channel){
							.band = WIFI_FREQ_BAND_2_4_GHZ, 
							.channel= 6
                               };
	printk("Request wifi scan:%d\n",net_mgmt(NET_REQUEST_WIFI_SCAN, iface, &params, sizeof(params)));
```

**Expected behavior**
Code runs without error

**Impact**

**Logs and console output**
This is the log output when it tries to call NULL callback
```
[00:00:06.000,000] <err> os: 
[00:00:06.003,000] <err> os:  mcause: 1, Instruction Access fault
[00:00:06.010,000] <err> os:   mtval: 0
[00:00:06.015,000] <err> os:      a0: 4082d810    t0: 40030dca
[00:00:06.021,000] <err> os:      a1: 00000000    t1: 00000000
[00:00:06.028,000] <err> os:      a2: 00000000    t2: 00000000
[00:00:06.034,000] <err> os:      a3: 60000000    t3: 00000000
[00:00:06.041,000] <err> os:      a4: 40839000    t4: aaaaaaaa
[00:00:06.047,000] <err> os:      a5: 00000000    t5: aaaaaaaa
[00:00:06.054,000] <err> os:      a6: 00000001    t6: aaaaaaaa
[00:00:06.060,000] <err> os:      a7: 00000010
[00:00:06.065,000] <err> os:      sp: 40833fd0
[00:00:06.070,000] <err> os:      ra: 4201c19a
[00:00:06.076,000] <err> os:    mepc: 00000000
[00:00:06.081,000] <err> os: mstatus: 00001880
[00:00:06.086,000] <err> os: 
[00:00:06.089,000] <err> os: call trace:
[00:00:06.094,000] <err> os:       0: sp: 40834040 ra: 4201d268
[00:00:06.101,000] <err> os:       1: sp: 40834060 ra: 420080ec
[00:00:06.107,000] <err> os:       2: sp: 40834070 ra: 4201e9fc
[00:00:06.114,000] <err> os:       3: sp: 40834080 ra: 42032302
[00:00:06.120,000] <err> os:       4: sp: 408340a0 ra: 42018013
[00:00:06.127,000] <err> os:       5: sp: 408340d0 ra: 42032592
[00:00:06.134,000] <err> os:       6: sp: 408340e0 ra: 420325b4
[00:00:06.140,000] <err> os:       7: sp: 40834110 ra: 42037914
[00:00:06.147,000] <err> os: 
[00:00:06.151,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:06.158,000] <err> os: Current thread: 0x4083a2a0 (wifi)
0x4083a2a0: ?? at ~/zephyrproject/modules/hal/espressif/zephyr/esp32c6/src/wifi/esp_wifi_adapter.c:70
```

**Environment (please complete the following information):**
Latest commit on main
ESP32C6 dev kit

**Additional context**

### PR DESCRIPTION
**Pull request by osmakari**
Wi-Fi AP-STA mode fails on ESP32 due to incorrect interface initialization. In AP-STA mode, esp32_wifi_init first sets the driver's AP interface, followed by the STA interface. However, the driver initializes them in reverse order, causing both to read incorrect device data and resulting in a "Wi-Fi not in station mode" error.
This fix handles STA and AP initialization in separate functions and checks for correct mode in esp32_wifi_status. Tested on a custom ESP32-S3-WROOM-1-N4R2 board, where both STA and AP can connect, send, and receive data.

Fixes: #81744
Fixes: #83775

### CODE REVIEW

**Comment by phb98-MS** [comment]
Sorry if i am misunderstanding this, i'm still new to Zephyr.

I checked your fix but still feel like this is not robust enough. What if someone, for whatever reason change the init order again. 
So my suggestion is the ap and sta iface should have different init function, that means 2 seperate `struct esp32_api`, you can point them to similar functions (for ex: `esp32_wifi_send`) and point other fp to different functions (for ex `esp32_wifi_init_ap` and `esp32_wifi_init_sta`) if needed.

**Comment by skryjapetr** [comment]
This PR should also solve https://github.com/zephyrproject-rtos/zephyr/issues/83775. 

I also would add this change (or something similar) in order to read corresponding status of AP or STA when the wifi is in AP+STA mode:
```diff
@@ -741,6 +741,14 @@ static int esp32_wifi_status(const struct device *dev, struct wifi_iface_status
 	status->mfp = WIFI_MFP_DISABLE;
 
 	if (esp_wifi_get_mode(&mode) == ESP_OK) {
+#if defined(CONFIG_ESP32_WIFI_AP_STA_MODE)
+		if (mode == ESP32_WIFI_MODE_APSTA && data == &esp32_data) {
+			mode = ESP32_WIFI_MODE_STA;
+		}
+		else if (mode == ESP32_WIFI_MODE_APSTA && data == &esp32_ap_sta_data) {
+			mode = ESP32_WIFI_MODE_AP;
+		}
+#endif
```

**Comment by osmakari** [comment]
@phb98-MS @skryjapetr Thanks for the suggestions. I made some changes, could you take a look?

File: drivers/wifi/esp32/src/esp_wifi_drv.c [hunk 1]
```diff
@@ -875,6 +876,31 @@ static void esp32_wifi_init(struct net_if *iface)
 	net_if_carrier_off(iface);
 }
 
+#if defined(CONFIG_ESP32_WIFI_AP_STA_MODE)
+static void esp32_wifi_init_ap(struct net_if *iface)
```
Comment (skryjapetr) [inline drivers/wifi/esp32/src/esp_wifi_drv.c:880]: remove white space at the end of this line please

**Review by skryjapetr — COMMENTED** [review]
Please update also the sample code `https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/net/wifi/apsta_mode/boards/esp32_devkitc_wroom_procpu.overlay`

The section
```
/ {
	wifi_ap: wifi_ap {
		compatible = "espressif,esp32-wifi";
		status = "okay";
	};
};
```

should not be required anymore.

I tried your changes on my project with ESP32C3 and it seems to work correctly.

**Review by skryjapetr — APPROVED** [review]

**Review by skryjapetr — APPROVED** [review]

**Comment by rodrigopex** [comment]
It did not work for me. I am using an esp32s3 custom board. I will try again later.

File: drivers/wifi/esp32/src/esp_wifi_drv.c [hunk 2]
```diff
@@ -939,6 +965,13 @@ static const struct net_wifi_mgmt_offload esp32_api = {
 	.wifi_iface.send = esp32_wifi_send,
 	.wifi_mgmt_api = &esp32_wifi_mgmt,
 };
+#if defined(CONFIG_ESP32_WIFI_AP_STA_MODE)
+static const struct net_wifi_mgmt_offload esp32_api_ap = {
+	.wifi_iface.iface_api.init	  = esp32_wifi_init_ap,
```
Comment (marekmatej) [inline drivers/wifi/esp32/src/esp_wifi_drv.c:970]: maybe remove those extra spaces

**Review by marekmatej — DISMISSED** [review]

**Review by wmrsouza — DISMISSED** [review]

**Comment by kartben** [comment]
ping @sylvioalves

File: samples/net/wifi/apsta_mode/boards/esp32_devkitc_wroom_procpu.overlay [hunk 3]
```diff
@@ -1,10 +1,3 @@
 &wifi {
 	status = "okay";
 };
-
-/ {
```
Comment (sylvioalves) [inline samples/net/wifi/apsta_mode/boards/esp32_devkitc_wroom_procpu.overlay:5]: Please, restore this otherwise it won't even build for `esp32_devkitc_wroom` board.

**Comment by sylvioalves** [comment]
@osmakari, thanks for updating the sample!

**Comment by sylvioalves** [comment]
@kartben Do we have room to add build tests for apsta sample within v4.1 release? If so I can submit it.

**Review by sylvioalves — APPROVED** [review]

**Comment by rodrigopex** [comment]
@sylvioalves, could you please check if it runs in some of your ESP32S3 boards? That is still not running on my custom ESP32S3 board. 
```console
*** Booting Zephyr OS build 15f089368d98 ***
[00:00:05.404,000] <inf> MAIN: Turning on AP Mode[00:00:05.405,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: Started DHCPv4 server, address pool:[00:00:05.405,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 0: 192.168.4.11
[00:00:05.405,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 1: 192.168.4.12
[00:00:05.405,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 2: 192.168.4.13
[00:00:05.405,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: 	 3: 192.168.4.14
[00:00:05.405,000] <inf> MAIN: DHCPv4 server started...

[00:00:05.433,000] <dbg> esp32_intc: esp_intr_alloc_intrstatus: Connected src 0 to int 3 (cpu 0)
[00:00:05.433,000] <dbg> esp32_intc: esp_intr_alloc_intrstatus: Connected src 2 to int 5 (cpu 0)
[00:00:05.435,000] <err> esp32_wifi: Failed to send packet
[00:00:05.435,000] <err> esp32_wifi: Failed to send packet
[00:00:05.436,000] <err> esp32_wifi: Failed to send packet
[00:00:05.436,000] <err> esp32_wifi: Failed to send packet
[00:00:05.436,000] <inf> MAIN: AP Mode is enabled. Waiting for station to connect
[00:00:05.436,000] <inf> MAIN: Connecting to SSID: SSID

[00:00:05.437,000] <inf> MAIN: AP Mode is disabled.
[00:00:05.438,000] <err> esp32_wifi: Failed to send packet
[00:00:05.438,000] <err> esp32_wifi: Failed to send packet
[00:00:05.438,000] <err> esp32_wifi: Failed to send packet
[00:00:05.438,000] <err> esp32_wifi: Failed to send packet
[00:00:06.438,000] <err> esp32_wifi: Failed to send packet
[00:00:07.439,000] <err> esp32_wifi: Failed to send packet
[00:00:07.849,000] <inf> MAIN: Disconnected from SSID

```

**Comment by osmakari** [comment]
@rodrigopex Are you sure you have `CONFIG_ESP32_WIFI_AP_STA_MODE` enabled? When I build without it I get:

CONFIG_ESP32_WIFI_AP_STA_MODE=n
```
[00:00:05.236,000] <inf> MAIN: Turning on AP Mode
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: Started DHCPv4 server, address pool:
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     0: 192.168.4.11
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     1: 192.168.4.12
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     2: 192.168.4.13
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     3: 192.168.4.14
[00:00:05.237,000] <inf> MAIN: DHCPv4 server started...

[00:00:05.276,000] <err> esp32_wifi: Failed to send packet
[00:00:05.277,000] <err> esp32_wifi: Failed to send packet
[00:00:05.277,000] <err> esp32_wifi: Failed to send packet
[00:00:05.277,000] <err> esp32_wifi: Failed to send packet
[00:00:05.277,000] <inf> MAIN: AP Mode is enabled. Waiting for station to connect
[00:00:05.278,000] <inf> MAIN: Connecting to SSID: MYSSID

[00:00:05.279,000] <inf> MAIN: AP Mode is disabled. <--- important  part
[00:00:05.281,000] <err> esp32_wifi: Failed to send packet
[00:00:05.282,000] <err> esp32_wifi: Failed to send packet
[00:00:05.282,000] <err> esp32_wifi: Failed to send packet
[00:00:05.282,000] <err> esp32_wifi: Failed to send packet
[00:00:06.283,000] <err> esp32_wifi: Failed to send packet
[00:00:17.183,000] <inf> net_dhcpv4: Received: 192.168.1.190
```

CONFIG_ESP32_WIFI_AP_STA_MODE=y
```
[00:00:05.236,000] <inf> MAIN: Turning on AP Mode
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start: Started DHCPv4 server, address pool:
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     0: 192.168.4.11
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     1: 192.168.4.12
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     2: 192.168.4.13
[00:00:05.237,000] <dbg> net_dhcpv4_server: net_dhcpv4_server_start:     3: 192.168.4.14
[00:00:05.237,000] <inf> MAIN: DHCPv4 server started...

[00:00:05.282,000] <err> esp32_wifi: Failed to send packet
[00:00:05.283,000] <err> esp32_wifi: Failed to send packet
[00:00:05.283,000] <err> esp32_wifi: Failed to send packet
[00:00:05.283,000] <err> esp32_wifi: Failed to send packet
[00:00:05.284,000] <inf> MAIN: AP Mode is enabled. Waiting for station to connect
[00:00:05.284,000] <inf> MAIN: Connecting to SSID: MYSSID

[00:00:05.287,000] <err> esp32_wifi: Failed to send packet
[00:00:05.287,000] <err> esp32_wifi: Failed to send packet
[00:00:05.287,000] <err> esp32_wifi: Failed to send packet
[00:00:05.288,000] <err> esp32_wifi: Failed to send packet
[00:00:06.285,000] <err> esp32_wifi: Failed to send packet
[00:00:06.288,000] <err> esp32_wifi: Failed to send packet
[00:00:07.286,000] <err> esp32_wifi: Failed to send packet
[00:00:07.288,000] <err> esp32_wifi: Failed to send packet
[00:00:21.750,000] <inf> net_dhcpv4: Received: 192.168.1.190
[00:00:21.751,000] <inf> MAIN: Connected to MYSSID
```

**Comment by rodrigopex** [comment]
> CONFIG_ESP32_WIFI_AP_STA_MODE

Yes, I have. I double-checked, and it did not work. Are you testing that on an esp32s3? Can anyone else try it? It could be a wrong custom configuration on my board.

**Review by marekmatej — APPROVED** [review]

**Review by wmrsouza — APPROVED** [review]
