### PR TITLE
avoid overflow of package length in log_msg

### LINKED ISSUE #75015: Logging long strings via printk kills the logging
**Describe the bug**
Logging a long string via `printk("%s\n", string)` kills the logging.

**To Reproduce**

main.c:

    #include <zephyr/logging/log.h>    
    #include <zephyr/kernel.h>
    
    LOG_MODULE_REGISTER(main, CONFIG_LOG_DEFAULT_LEVEL);
    
    static uint8_t test_data[2048 + 1];
    
    int main(void)
    {
        memset(test_data, 0x00, sizeof(test_data));
    
        for (size_t i = 0; i < sizeof(test_data) - 1; ++i) {
            test_data[i] = '0' + (i % 10);
        }
    
        LOG_INF("logging %i bytes", sizeof(test_data));
        printk("%s\n", test_data);
    
        while (true) {
            LOG_INF("still alive");
            k_sleep(K_SECONDS(1));
        }
    }

prj.conf:

    CONFIG_DEBUG_OPTIMIZATIONS=y
    CONFIG_LOG=y
    CONFIG_ASAN=y
    CONFIG_SHELL=y
    CONFIG_SHELL_BACKEND_SERIAL_LOG_MESSAGE_QUEUE_SIZE=8192
    CONFIG_LOG_BUFFER_SIZE=8192

Using `printk(test_data);` instead of `printk("%s\n", test_data);` avoids the issue. Therefore, I assume the root cause is somewhere within cbprintf.

**Expected behavior**
Continous "still alive" messages after the log entry with the long string.

**Impact**
Not huge, as I can avoid it with the workaround explained above.

**Environment**
Zephyr revision: v3.7.0-rc1-397-g7f8cc43a0b5e
nucleo_f746zg

### PR DESCRIPTION
**Pull request by benediktibk**
Check if the calculated package length exceeds the maximum possible value and cap it.
Fixes #75015

### CODE REVIEW

File: subsys/logging/log_msg.c [hunk 1]
```diff
@@ -358,6 +358,10 @@ void z_log_msg_runtime_vcreate(uint8_t domain_id, const void *source,
 		plen = 0;
 	}
 
+	if (plen >= (1 << Z_LOG_MSG_PACKAGE_BITS)) {
```
Comment (nordic-krch) [inline subsys/logging/log_msg.c:361]: I added it for static creation (https://github.com/zephyrproject-rtos/zephyr/blob/83fe779a4c36d910e853403af79e4b091b46ba1e/subsys/logging/log_msg.c#L307) but forgot to handle runtime. Can you apply same approach as it is there. It's better to drop that message. Decoding of incomplete message will fail anyway.

**Comment by benediktibk** [comment]
Looking promising with this change:

    [00:00:00.000,000] <inf> main: logging 1 bytes
    0
    [00:00:02.001,000] <inf> main: logging 2 bytes
    01
    [00:00:04.002,000] <inf> main: logging 4 bytes
    0123
    [00:00:06.002,000] <inf> main: logging 8 bytes
    01234567
    [00:00:08.003,000] <inf> main: logging 16 bytes
    0123456789012345
    [00:00:10.003,000] <inf> main: logging 32 bytes
    01234567890123456789012345678901
    [00:00:12.004,000] <inf> main: logging 64 bytes
    0123456789012345678901234567890123456789012345678901234567890123
    [00:00:14.005,000] <inf> main: logging 128 bytes
    01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567
    [00:00:16.005,000] <inf> main: logging 256 bytes
    0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
    [00:00:18.006,000] <inf> main: logging 512 bytes
    01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901
    [00:00:20.007,000] <inf> main: logging 1024 bytes
    0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123
    [00:00:22.008,000] <inf> main: logging 2048 bytes
    [00:00:22.008,000] <wrn> log: Message dropped because it exceeds size limitation (2047)
    [00:00:24.009,000] <inf> main: logging 4096 bytes
    [00:00:24.009,000] <wrn> log: Message dropped because it exceeds size limitation (2047)
    [00:00:26.011,000] <inf> main: logging 8192 bytes
    [00:00:26.011,000] <wrn> log: Message dropped because it exceeds size limitation (2047)
    [00:00:28.014,000] <inf> main: logging 16384 bytes
    [00:00:28.014,000] <wrn> log: Message dropped because it exceeds size limitation (2047)
    [00:00:30.019,000] <inf> main: logging 32768 bytes
    [00:00:30.019,000] <wrn> log: Message dropped because it exceeds size limitation (2047)
    [00:00:32.020,000] <inf> main: logging 1 bytes
    0
    [00:00:34.020,000] <inf> main: logging 2 bytes
    01
    [00:00:36.021,000] <inf> main: logging 4 bytes
    0123

**Review by dcpleung — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]
