### PR TITLE
posix: pthread: ensure pthread_key_delete() removes correct key

### LINKED ISSUE #65696: posix: pthreads: pthread_key_delete() always deletes key at offset 0
**Describe the bug**
Rather than deleting the key that is supplied as an argument, `pthread_key_delete()` always deletes they key at index 0.

This is obviously a bug

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? All
 - What have you tried to diagnose or workaround this issue? Inspected code. Wrote a test
 - Is this a regression? Yes. f1ececc682bc9f0f573d63c618364f129b544236

**To Reproduce**
1. Run the test in the linked PR without the fix
2. See error

**Expected behavior**
The correct `pthread_key_t` should be deleted

**Impact**
It seems as though there have been no major casualties.

**Logs and console output**
```shell
START - test_correct_key_is_deleted

    Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/key.c:246: posix_apis_test_correct_key_is_deleted: (key not equal to keys[j])
deleted key 80000000 instead of key 80000004
 FAIL - test_correct_key_is_deleted in 0.002 seconds
===================================================================
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.3
 - Commit SHA or Version used: 41b7c17ac4bd0198fc9bb3a0e55aa8d5e2fae96e

**Additional context**
Discovered while working on #59940 and #59941

### PR DESCRIPTION
**Pull request by cfriedt**
**Note: Compliance issue is a false positive (the `__unused` problem)**

Previously, `pthread_key_delete()` was only ever deleting key 0 rather than the key corresponding to the provided argument.

Fixes #65696

### CODE REVIEW

File: lib/posix/key.c [hunk 1]
```diff
@@ -120,6 +121,8 @@ int pthread_key_create(pthread_key_t *key,
  */
 int pthread_key_delete(pthread_key_t key)
 {
+	size_t bit;
+	__unused int ret;
```
Comment (ycsin) [inline lib/posix/key.c:125]: moving the `__unused` to the right can workaround the checkpatch, or maybe add `__unused` to the attribute list?

https://github.com/zephyrproject-rtos/zephyr/blob/69d62add980bcafa6d90b73920372390cc10ea7c/scripts/checkpatch.pl#L379-L405

**Review by ycsin — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

File: lib/posix/key.c (hunk 1 above)
Comment (fabiobaltieri) [reply lib/posix/key.c:125]: merged, good stuff
