### PR TITLE
drivers: udc: stm32: fix DOUT stage handling for `st_stm32_usb`

### LINKED ISSUE #83392: STM32 USB CDC ACM: Plug/Unplug and Baudrate Issues with usbd_next_prj.conf
Here the result of [PR](https://github.com/zephyrproject-rtos/zephyr/pull/80820) tests using samples/subsys/usb/cdc_acm with -DCONF_FILE=usbd_next_prj.conf and sent a lorem ipsum buffer of 1024 bytes several times.

In any case it fixes the assert issue reported here: https://github.com/zephyrproject-rtos/zephyr/issues/61464.

Screenshot from 2024-12-19 16-23-24

**Patch**
https://github.com/zephyrproject-rtos/zephyr/issues/76250 subsys/usb/device_next/class/usbd_cdc_acm.c
```c
@@ -458,11 +458,14 @@ static int usbd_cdc_acm_ctd(struct usbd_class_data *const c_data,
 		if (setup->wLength != len) {
 			errno = -ENOTSUP;
 			return 0;
 		}

-		memcpy(&data->line_coding, buf->data, len);
+		if (buf->data) {
+			printk("SET_LINE_CODING buf->data not null\n");
+			memcpy(&data->line_coding, buf->data, len);
+		}
 		cdc_acm_update_uart_cfg(data);
 		usbd_msg_pub_device(uds_ctx, USBD_MSG_CDC_ACM_LINE_CODING, dev);
 		return 0;

 	case SET_CONTROL_LINE_STATE:
``` 

dts updated
```shell
+
+zephyr_udc0: &usb {
+	pinctrl-0 = <&usb_dm_pa11 &usb_dp_pa12>;
+	pinctrl-names = "default";
+	status = "okay";
+};
``` 

- **nucleo_f303re**

Wrong Baudrate value reported: <inf> cdc_acm_echo: Baudrate 536885760.
With [patch](https://github.com/zephyrproject-rtos/zephyr/pull/80820#workaround-1) value is fixed (115200).
Seems same issue than https://github.com/zephyrproject-rtos/zephyr/issues/76250, no crash because the buf->data has a value but not a correct one.
Old stack also report a fixed baudrate.
[Assertion](https://github.com/zephyrproject-rtos/zephyr/pull/80820#assert-enabled) if CONFIG_ASSERT=y
[Plug/unplug](https://github.com/zephyrproject-rtos/zephyr/pull/80820#plugunplug) issue

- **Assert enabled**

log
```c
*** Booting Zephyr OS build v4.0.0-1636-gddeb51a89cfd ***
[00:00:00.001,000] <err> usbd_core: Failed to set default address after bus reset:
[00:00:00.001,000] <inf> cdc_acm_echo: USBD message: Bus reset:
[00:00:00.001,000] <inf> cdc_acm_echo: USBD message: Stack error:
[00:00:00.001,000] <inf> cdc_acm_echo: USB device support enabled:
[00:00:00.001,000] <inf> cdc_acm_echo: Wait for DTR:
[00:00:00.004,000] <inf> cdc_acm_echo: USBD message: Device suspended:
[00:00:00.112,000] <inf> cdc_acm_echo: USBD message: Device resumed:
[00:00:00.167,000] <inf> cdc_acm_echo: USBD message: Bus reset:
[00:00:00.281,000] <inf> cdc_acm_echo: USBD message: Bus reset:
[00:00:00.362,000] <inf> cdc_acm_echo: USBD message: New device configuration:
ASSERTION FAIL [net_buf_simple_tailroom(buf) >= len] @ WEST_TOPDIR/zephyr/lib/net_buf/buf_simple.c:62
[00:00:00.363,000] <err> os: r0/a1:  0x00000004  r1/a2:  0x0000003e  r2/a3:  0x00000005:
[00:00:00.363,000] <err> os: r3/a4:  0x00000004 r12/ip:  0x20003160 r14/lr:  0x08003b5d:
[00:00:00.363,000] <err> os:  xpsr:  0x01000000:
[00:00:00.363,000] <err> os: Faulting instruction address (r15/pc): 0x0800d228:
[00:00:00.363,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0:
[00:00:00.363,000] <err> os: Current thread: 0x20000f60 (unknown):
[00:00:00.444,000] <err> os: Halting system:
``` 

- **Plug/unplug**

Important

On linux, second plug produce this issue (re-enumeration):
On Windows, first plug (enumeration), means CDC port never created.

log
```c
[00:00:07.187,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.187,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.187,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.188,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.188,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.188,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.188,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.188,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.188,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.188,000] <err> udc: Failed to allocate net_buf 255
[00:00:07.188,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.188,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.188,000] <err> udc: Failed to allocate net_buf 255
[00:00:07.188,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.188,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.189,000] <err> udc: Failed to allocate net_buf 255
[00:00:07.189,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.189,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.189,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.189,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.189,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.189,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.189,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.189,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.190,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.190,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.190,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.193,000] <err> udc: Failed to allocate net_buf 0
[00:00:07.193,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.193,000] <err> usbd_ch9: Malformed setup packet
```

### PR DESCRIPTION
**Pull request by ndrs-pst**
In the device that has `DT_DRV_COMPAT` equal to `st_stm32_usb`, its behavior differs from `st_stm32_otghs` and `st_stm32_otgfs` due to the underlying `HAL_PCD_IRQHandler`.
As a result, calling `usbd_ctrl_feed_dout` for the DOUT stage is not compatible with the `st_stm32_usb` device.

Instead of calling `usbd_ctrl_feed_dout`, we still require flushing the TX FIFO to the host.
This is achieved by calling `HAL_PCD_EP_Receive` with `len` = `0`.

### CODE REVIEW

File: drivers/usb/udc/udc_stm32.c [hunk 1]
```diff
@@ -230,7 +238,11 @@ static int udc_stm32_tx(const struct device *dev, uint8_t ep,
 		/* Wait for an empty package from the host.
 		 * This also flushes the TX FIFO to the host.
 		 */
-		usbd_ctrl_feed_dout(dev, 0);
+		if (DT_HAS_COMPAT_STATUS_OKAY(st_stm32_usb)) {
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_stm32.c:241]: That is not future-proof, right way would be to store controller type in dev->config and check it here.

Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c:241]: Should the driver support multiple instance at some point?

Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c:241]: I did not ask for changes, I just made a comment and left it up to you. And I did something similar some time ago, where the drivers were a bit simpler, but still not able to support different instances.

**Review by erwango — APPROVED** [review]

**Review by marwaiehm-st — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Please remove `Fix #83392` from the commit message. Do not rebase!

**Comment by ndrs-pst** [comment]
Addressed it already. 🫡

**Review by jfischer-no — APPROVED** [review]
