### PR TITLE
tests: msgq: Fix uncheck return value of coverity scan

### LINKED ISSUE #31680: [Coverity CID :216795] Unchecked return value in tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f91e9fba51e5da46ee5c6822f8656713d74a6ecf/tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c#L408

Category: Error handling issues
Function: `test_msgq_empty`
Component: Tests
CID: [216795](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=216795)

Details:

```
402         /* since there is a thread is waiting for message, this queue
403          * can't be cleanup
404          */
405         ret = k_msgq_cleanup(&msgq1);
406         zassert_equal(ret, -EBUSY, NULL);
407         /* put a message to wake that getting thread */
>>>     CID 216795:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "k_msgq_put" without checking return value (as is done elsewhere 16 out of 18 times).
408         k_msgq_put(&msgq1, &data[0], K_NO_WAIT);
409         k_thread_abort(tid);
410     }
411    
412     /**
413      * @brief Put message to a full queue
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by enjiamai**
Add a return value check of message queue test cases, to fix
issue #31680, which is for CID :216795.

Fixes #31680 

Signed-off-by: Enjia Mai <enjiax.mai@intel.com>

### CODE REVIEW

File: tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c [hunk 1]
```diff
@@ -429,8 +432,9 @@ void test_msgq_full(void)
 	ret = k_sem_init(&end_sema, 0, 1);
 	zassert_equal(ret, 0, NULL);
 
-
 	k_msgq_put(&msgq1, &data[0], K_NO_WAIT);
```
Comment (nashif) [inline tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c:435]: need to capture ret here?

Comment (enjiamai) [reply tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c]: Oh, so sorry, miss it, thank so much for your correction.

**Review by nashif — APPROVED** [review]

File: tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c [hunk 2]
```diff
@@ -429,8 +432,9 @@ void test_msgq_full(void)
 	ret = k_sem_init(&end_sema, 0, 1);
 	zassert_equal(ret, 0, NULL);
 
+	ret = k_msgq_put(&msgq1, &data[0], K_NO_WAIT);
+	zassert_equal(ret, 0, NULL);
```
Comment (jenmwms) [inline tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c:436]: Can you please help me understand? This test is put message to a full queue, and should get a -ENOMSG if a timeout is set to K_NO_WAIT (from description). 

We init'd the msgq with size 1, so these lines here are to fill that buffer. Then the next part (k_thread_create) is what executes our test scenario of a thread putting more data on a full queue. Is my understanding correct, or close?

If so, how do we confirm the test scenario was handled properly? Would we not need a `zassert_equal(ret, -ENOMSG, NULL)`?

Comment (jenmwms) [reply tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c:436]: Considering this PR is to fix the unchecked return value, my clarification above should not block this PR.

**Review by jenmwms — APPROVED** [review]

File: tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c (hunk 2 above)
Comment (enjiamai) [reply tests/kernel/msgq/msgq_api/src/test_msgq_contexts.c:436]: @jenmwms thanks for your review and approval, this is indeed to fix the coverity issue. 

When it first k_msgq_put (see line 435),  if won't get a -ENOMSG because it is still not empty, (msgq->used == 0, msgq->max_msgs==1 ,  as long as  used < max, it will return 0.  see "kernel/msg_q.c" line 126, 148 please.

And your understanding is correct. If we keep calling  k_msgq_put again with K_NO_WAIT, we will get -ENOMSG. like you can see in the created thread (line 231).

Hope this answer you question, thanks!
