### PR TITLE
soc: stm32: SEGGER RTT requires some extra configuration

### LINKED ISSUE #34324: RTT is not working on STM32
**Describe the bug**
I would like to use logging RTT backend with Segger RTTViwer but it does not work. My Segger J-Link is not able to find the RTT control block. Using the same setup with another board (nRF52840dk) does work without any problem.

**To Reproduce**
1. Use Blinky sample as the base
2. use the following prj.conf
```
CONFIG_DEBUG=y

# RTT
CONFIG_USE_SEGGER_RTT=y

# console
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

# shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKENDS=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_PROMPT_UART="uart:~$ "

# logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_SHELL_LOG_BACKEND=n

CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=10
CONFIG_LOG_PROCESS_THREAD=y
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=500
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048
CONFIG_LOG_BUFFER_SIZE=1024
CONFIG_LOG_DETECT_MISSED_STRDUP=y
#LOG Maximum string define
CONFIG_LOG_STRDUP_MAX_STRING=100
CONFIG_LOG_STRDUP_BUF_COUNT=4
```

3. add LOG_xxx in main loop
```
void main(void)
{
	struct device *dev;
	bool led_is_on = true;
	int ret;

        printk("Blinky sample on board: %s\n", CONFIG_BOARD);

	dev = device_get_binding(LED0);
	if (dev == NULL) {
		return;
	}

	ret = gpio_pin_configure(dev, PIN, GPIO_OUTPUT_ACTIVE | FLAGS);
	if (ret < 0) {
		return;
	}

	while (1) {
                // printk("led: %d\n", led_is_on);
                // LOG_DBG("led: %d\n", led_is_on);
                LOG_INF("led: %d\n", led_is_on);
                // LOG_WRN("led: %d\n", led_is_on);
                // LOG_ERR("led: %d\n", led_is_on);
		gpio_pin_set(dev, PIN, (int)led_is_on);
		led_is_on = !led_is_on;
		k_msleep(SLEEP_TIME_MS);
	}
}
```
4. Build and flash the application to board nucleo_l476rg  successfully (the ST-Link on board was already replaced with JLink firmware)
5. Open JLinkRTTViewer and connect successfully with SWD, RTT Control Block select "Auto" or "Address" 0x20000920
```
.bss._SEGGER_RTT
                0x0000000020000920       0xa8 zephyr/libzephyr.a(SEGGER_RTT.c.obj)
                0x0000000020000920                _SEGGER_RTT
```
6. No log output in Terminal at all. 
7. I also use J-Mem, it connected ok, but all memory shows "00".
8. I tried on another board STM32F3 Discovery, the same problem.
9. I also tried to use a real J-Link Plus probe, it has the same problem.

**Expected behavior**
RTT logging should work to display in JLinkRTTViewer. Seems the memory is protected from being readout from SWD. The same program and settings works fine on nRF52840dk.

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: gnuarmemb gcc-arm-none-eabi-9-2019-q4-major
 - Commit SHA or Version used: 2.5-branch 6c2ae13e9a85f41dc421c206f28baf6eb71ba48e
 - JLink: SEGGER J-Link V6.98e

### PR DESCRIPTION
**Pull request by ABOSTM**
soc: stm32: SEGGER RTT requires some extra configuration

On some STM32 boards, for unclear reason,
RTT feature is working with realtime update only when
  * one of the DMA is clocked
and sometimes also
  * one of the DBGMCU bit STOP/STANDBY/SLEEP is set
 
Fixes #34324

### CODE REVIEW

File: soc/arm/st_stm32/common/soc_config.c [hunk 1]
```diff
@@ -30,6 +32,32 @@ static int st_stm32_common_config(const struct device *dev)
...
+#elif defined(LL_APB1_GRP2_PERIPH_DBGMCU)
+	LL_APB1_GRP2_EnableClock(LL_APB1_GRP2_PERIPH_DBGMCU);
+#elif defined(LL_APB2_GRP1_PERIPH_DBGMCU)
+	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_DBGMCU);
+#endif
+#if defined(CONFIG_SOC_SERIES_STM32H7X) || defined(CONFIG_SOC_SERIES_STM32MP1X)
+	HAL_EnableDBGSleepMode();
+#else
+	LL_DBGMCU_EnableDBGStopMode();
+#endif
```
Comment (erwango) [inline soc/arm/st_stm32/common/soc_config.c:60]: Should this be also under `#ifdef CONFIG_USE_SEGGER_RTT` ?

Comment (ABOSTM) [reply soc/arm/st_stm32/common/soc_config.c]: Yes. Done

File: soc/arm/st_stm32/common/soc_config.c [hunk 2]
```diff
@@ -30,6 +32,34 @@ static int st_stm32_common_config(const struct device *dev)
 	DBGMCU->CR |= DBGMCU_CR_TRACE_IOEN;
 #endif
 
+#if defined(CONFIG_USE_SEGGER_RTT)
+#if defined(__HAL_RCC_DMA1_CLK_ENABLE)
+	/* On some STM32 boards, for unclear reason,
+	 * RTT feature is working with realtime update only when
+	 *   - one of the DMA is clocked.
+	 * See https://github.com/zephyrproject-rtos/zephyr/issues/34324
+	 */
```
Comment (erwango) [inline soc/arm/st_stm32/common/soc_config.c:41]: Put the comment before `#if defined(__HAL_RCC_DMA1_CLK_ENABLE)`

File: soc/arm/st_stm32/common/soc_config.c [hunk 3]
```diff
@@ -30,6 +32,34 @@ static int st_stm32_common_config(const struct device *dev)
...
+	LL_APB1_GRP2_EnableClock(LL_APB1_GRP2_PERIPH_DBGMCU);
+#elif defined(LL_APB2_GRP1_PERIPH_DBGMCU)
+	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_DBGMCU);
+#endif /* LL_APB1_GRP1_PERIPH_DBGMCU */
+#if defined(CONFIG_SOC_SERIES_STM32H7X) || defined(CONFIG_SOC_SERIES_STM32MP1X)
+	HAL_EnableDBGSleepMode();
+#else
+	LL_DBGMCU_EnableDBGStopMode();
+#endif /* CONFIG_SOC_SERIES_STM32H7X || CONFIG_SOC_SERIES_STM32MP1X */
+#endif /* CONFIG_USE_SEGGER_RTT */
```
Comment (erwango) [inline soc/arm/st_stm32/common/soc_config.c:62]: Please break a line here

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: soc/arm/st_stm32/common/soc_config.c (hunk 2 above)
Comment (ABOSTM) [reply soc/arm/st_stm32/common/soc_config.c:40]: Done

File: soc/arm/st_stm32/common/soc_config.c (hunk 3 above)
Comment (ABOSTM) [reply soc/arm/st_stm32/common/soc_config.c:64]: Done

**Review by erwango — APPROVED** [review]

**Comment by ghlualven** [comment]
I tested on STM32L443VC, it's working perfectly. 
But when I tested on STM32L073VZ, the firmware logic running ok, but the MCU seems dead while RTT Viewer connected, after disconnected the MCU reseted automatically.

**Comment by erwango** [comment]
@ghlualven Thanks for this feedback.

> But when I tested on STM32L073VZ, the firmware logic running ok, but the MCU seems dead while RTT Viewer connected, after disconnected the MCU reseted automatically.

And can you tell us what is the behavior before this patch is applied ?

**Comment by ghlualven** [comment]
Before applied patch, the MCU will not dead while RTT Viewer connected (no log output of cause), the firmware logic run ok.

**Comment by ghlualven** [comment]
Before applied the patch, on STM32L073VZ board the firmware logic will run but the MCU stop working right after RTT connected. So this may not related to this patch, just another issue caused the RTT not working on STM32L073VZ.

**Comment by ABOSTM** [comment]
@ghlualven, I agree that RTT is still not working on L073.
I made a status of RTT functioning across stm32 series based on this patch:




Serie | Board | RTT status
-- | -- | --
F1 | nucleo_f103rb | OK
F2 | nucleo_f207zg | OK
F3 | nucleo_f303re | OK
F4 | nucleo_f429zi | OK
F7 | nucleo_f746zg | OK
G0 | nucleo_g071rb | OK
L4 | nucleo_l476rg | Ok
L5 | nucleo_l552re | OK
WB | nucleo_wb55rg | OK
  |   |  
L0 | nucleo_l073rz | KO
L1 | nucleo_l152re | KO
F0 | Nucleo_f091rc | KO

For other series, I could not test because I could not reflash stlink to jlink and I don't have specific mipi10 connector required on those borads to use my homemade Jlink.

Unfortunately, I could not understand why it fails on L0, L1, F0. And even worse, why MCU doesn't work properly when RTT connected for those series. I don't understand how RTT can prevent MCU to run properly. And hard to debug, as when debugger is attached then everything is working well (MCU + RTT).

My proposal is to merge this PR even there is still some non working series,
but at least, it fixes F1, L4 and F4 issues.

File: soc/arm/st_stm32/common/soc_config.c [hunk 4]
```diff
@@ -30,6 +32,37 @@ static int st_stm32_common_config(const struct device *dev)
...
+	LL_APB1_GRP2_EnableClock(LL_APB1_GRP2_PERIPH_DBGMCU);
+#elif defined(LL_APB2_GRP1_PERIPH_DBGMCU)
+	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_DBGMCU);
+#endif /* LL_APB1_GRP1_PERIPH_DBGMCU */
+
+#if defined(CONFIG_SOC_SERIES_STM32H7X) || defined(CONFIG_SOC_SERIES_STM32MP1X)
+	HAL_EnableDBGSleepMode();
+#else
+	LL_DBGMCU_EnableDBGStopMode();
+#endif /* CONFIG_SOC_SERIES_STM32H7X || CONFIG_SOC_SERIES_STM32MP1X */
```
Comment (erwango) [inline soc/arm/st_stm32/common/soc_config.c:62]: Is that still relevant with the list of series that:
- could not be tested
- still can't work with the patch

**Review by erwango — APPROVED** [review]

File: soc/arm/st_stm32/common/soc_config.c (hunk 4 above)
Comment (ABOSTM) [reply soc/arm/st_stm32/common/soc_config.c:62]: I prefer to kept it generic, even for series not tested or not functional,
it is thus valid for further series which may require this patch too.
And I don't think this patch could have negative impact on RTT.

**Review by FRASTM — APPROVED** [review]
