### PR TITLE
drivers: led: pca9633: add support for multiple devices

### LINKED ISSUE #40076: Driver led pca9633 does only use first device in devicetree
**Describe the bug**
If multiple pca9633 devices are defined in the devicetree, the driver only configures the first one.

**To Reproduce**
1. Use the sample project drivers/led/pca9633
2. Add dts overlay: ```&i2c0 {
	status = "okay";
	pca9633@60 {
		compatible = "nxp,pca9633";
		reg = <0x60>;
		label = "PCA9633_0";
	};
	pca9633@61 {
		compatible = "nxp,pca9633";
		reg = <0x61>;
		label = "PCA9633_1";
	};
}; ```

3. Compile
4. Run command in shell: "device list" observe only one instance of pca9633 defined.

**Expected behavior**
As pca9633 supports up to 128 devices on the same i2c bus I expect all of the defined pca9633 instances to be configured.

**Impact**
We are currently developing a prouct using zephyr 2.7 and several pca9633 for led control for horticulture. Missing support for multiple pca9633 are a showstopper for us.

### PR DESCRIPTION
**Pull request by daniel-nicolai-hansten**
PCA9633 only supports one device.
Rewrite of the driver to support multiple devices.
Fixes #40076

### CODE REVIEW

**Comment by Mani-Sadhasivam** [comment]
@daniel-nicolai-hansten Please rework the commit as per: https://docs.zephyrproject.org/latest/contribute/#commit-guidelines

File: drivers/led/pca9633.c [hunk 1]
```diff
@@ -43,15 +43,20 @@ LOG_MODULE_REGISTER(pca9633);
 
 #define PCA9633_MASK            0x03
 
-struct pca9633_data {
+struct pca9633_cfg {
 	const struct device *i2c;
```
Comment (bbilas) [inline drivers/led/pca9633.c:47]: While at it it would be worth converting this driver to use i2c_dt_spec.

Comment (daniel-nicolai-hansten) [reply drivers/led/pca9633.c:47]: Sure, do you have an example i can work from?

Comment (bbilas) [reply drivers/led/pca9633.c:47]: Here you go https://github.com/zephyrproject-rtos/zephyr/pull/39901

Comment (daniel-nicolai-hansten) [reply drivers/led/pca9633.c]: Updated the driver to use i2c_dt_spec

File: drivers/led/pca9633.c [hunk 2]
```diff
@@ -69,7 +69,7 @@ static int pca9633_led_blink(const struct device *dev, uint32_t led,
 	 *		GDC = ((time_on * 256) / period)
 	 */
 	gdc = delay_on * 256U / period;
-	if (i2c_reg_write_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_write_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:72]: It should be replaced by `i2c_reg_write_byte_dt`.

File: drivers/led/pca9633.c [hunk 3]
```diff
@@ -83,15 +83,15 @@ static int pca9633_led_blink(const struct device *dev, uint32_t led,
 	 *		GFRQ = ((period * 24 / 1000) - 1)
 	 */
 	gfrq = (period * 24U / 1000) - 1;
-	if (i2c_reg_write_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_write_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:86]: ditto

File: drivers/led/pca9633.c [hunk 4]
```diff
@@ -83,15 +83,15 @@ static int pca9633_led_blink(const struct device *dev, uint32_t led,
...
 			       PCA9633_GRPFREQ,
 			       gfrq)) {
 		LOG_ERR("LED reg write failed");
 		return -EIO;
 	}
 
 	/* Enable blinking mode */
-	if (i2c_reg_update_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_update_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:94]: It should be replaced by i2c_reg_update_byte_dt.

File: drivers/led/pca9633.c [hunk 5]
```diff
@@ -100,7 +100,7 @@ static int pca9633_led_blink(const struct device *dev, uint32_t led,
 	}
 
 	/* Select the GRPPWM source to drive the LED outpout */
-	if (i2c_reg_update_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_update_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:103]: ditto

File: drivers/led/pca9633.c [hunk 6]
```diff
@@ -125,15 +126,15 @@ static int pca9633_led_set_brightness(const struct device *dev, uint32_t led,
 
 	/* Set the LED brightness value */
 	val = (value * 255U) / dev_data->max_brightness;
-	if (i2c_reg_write_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_write_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:129]: It should be replaced by i2c_reg_write_byte_dt.

File: drivers/led/pca9633.c [hunk 7]
```diff
@@ -125,15 +126,15 @@ static int pca9633_led_set_brightness(const struct device *dev, uint32_t led,
...
 			       PCA9633_PWM_BASE + led,
 			       val)) {
 		LOG_ERR("LED reg write failed");
 		return -EIO;
 	}
 
 	/* Set the LED driver to be controlled through its PWMx register. */
-	if (i2c_reg_update_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_update_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:137]: It should be replaced by i2c_reg_update_byte_dt.

File: drivers/led/pca9633.c [hunk 8]
```diff
@@ -146,10 +147,10 @@ static int pca9633_led_set_brightness(const struct device *dev, uint32_t led,
 
 static inline int pca9633_led_on(const struct device *dev, uint32_t led)
 {
-	struct pca9633_data *data = dev->data;
+	const struct i2c_dt_spec *config = dev->config;
 
 	/* Set LED state to ON */
-	if (i2c_reg_update_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_update_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:153]: ditto

File: drivers/led/pca9633.c [hunk 9]
```diff
@@ -162,10 +163,10 @@ static inline int pca9633_led_on(const struct device *dev, uint32_t led)
 
 static inline int pca9633_led_off(const struct device *dev, uint32_t led)
 {
-	struct pca9633_data *data = dev->data;
+	const struct i2c_dt_spec *config = dev->config;
 
 	/* Set LED state to OFF */
-	if (i2c_reg_update_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_update_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:169]: ditto

File: drivers/led/pca9633.c [hunk 10]
```diff
@@ -178,17 +179,17 @@ static inline int pca9633_led_off(const struct device *dev, uint32_t led)
 
 static int pca9633_led_init(const struct device *dev)
 {
+	const struct i2c_dt_spec *config = dev->config;
 	struct pca9633_data *data = dev->data;
 	struct led_data *dev_data = &data->dev_data;
 
-	data->i2c = device_get_binding(DT_INST_BUS_LABEL(0));
-	if (data->i2c == NULL) {
+	if (config->bus == NULL) {
```
Comment (bbilas) [inline drivers/led/pca9633.c:186]: It should be done this way:

<pre>
if (!device_is_ready(config->bus.bus)) {
	LOG_ERR("I2C bus is not ready");
	return -ENODEV;
}
</pre>

File: drivers/led/pca9633.c [hunk 11]
```diff
@@ -178,17 +179,17 @@ static inline int pca9633_led_off(const struct device *dev, uint32_t led)
...
 		LOG_DBG("Failed to get I2C device");
 		return -EINVAL;
 	}
 
 	/* Take the LED driver out from Sleep mode. */
-	if (i2c_reg_update_byte(data->i2c, DT_INST_REG_ADDR(0),
+	if (i2c_reg_update_byte(config->bus, config->addr,
```
Comment (bbilas) [inline drivers/led/pca9633.c:192]: It should be replaced by i2c_reg_update_byte_dt.

File: drivers/led/pca9633.c [hunk 12]
```diff
@@ -204,16 +205,24 @@ static int pca9633_led_init(const struct device *dev)
...
 };
 
-DEVICE_DT_INST_DEFINE(0, &pca9633_led_init, NULL,
-		    &pca9633_led_data,
-		    NULL, POST_KERNEL, CONFIG_LED_INIT_PRIORITY,
-		    &pca9633_led_api);
+#define PCA9633_DEVICE(id) \
+	static const struct i2c_dt_spec pca9633_##id##_cfg = {	\
+		.bus = DEVICE_DT_GET(DT_INST_BUS(id)),		\
+		.addr     = DT_INST_REG_ADDR(id),			\
```
Comment (bbilas) [inline drivers/led/pca9633.c:218]: adrr member shouldn't be needed anymore in case of using the i2c_dt_spec struct.

**Review by bbilas — CHANGES_REQUESTED** [review]

File: drivers/led/pca9633.c [hunk 13]
```diff
@@ -204,16 +205,24 @@ static int pca9633_led_init(const struct device *dev)
...
 	.off = pca9633_led_off,
 };
 
-DEVICE_DT_INST_DEFINE(0, &pca9633_led_init, NULL,
-		    &pca9633_led_data,
-		    NULL, POST_KERNEL, CONFIG_LED_INIT_PRIORITY,
-		    &pca9633_led_api);
+#define PCA9633_DEVICE(id) \
+	static const struct i2c_dt_spec pca9633_##id##_cfg = {	\
+		.bus = DEVICE_DT_GET(DT_INST_BUS(id)),		\
```
Comment (bbilas) [inline drivers/led/pca9633.c:217]: There is a dedicated I2C_DT_SPEC_INST_GET macro for that.

File: drivers/led/pca9633.c [hunk 14]
```diff
@@ -204,16 +205,21 @@ static int pca9633_led_init(const struct device *dev)
...
 	.on = pca9633_led_on,
 	.off = pca9633_led_off,
 };
 
-DEVICE_DT_INST_DEFINE(0, &pca9633_led_init, NULL,
-		    &pca9633_led_data,
-		    NULL, POST_KERNEL, CONFIG_LED_INIT_PRIORITY,
-		    &pca9633_led_api);
+#define PCA9633_DEVICE(id) \
+	static const struct i2c_dt_spec pca9633_##id##_cfg = I2C_DT_SPEC_INST_GET(id);	\
```
Comment (gmarull) [inline drivers/led/pca9633.c:216]: please create a config struct that holds `i2c_dt_spec` (per convention)

**Review by gmarull — CHANGES_REQUESTED** [review]

File: drivers/led/pca9633.c [hunk 15]
```diff
@@ -204,16 +208,23 @@ static int pca9633_led_init(const struct device *dev)
...
 };
 
-DEVICE_DT_INST_DEFINE(0, &pca9633_led_init, NULL,
-		    &pca9633_led_data,
-		    NULL, POST_KERNEL, CONFIG_LED_INIT_PRIORITY,
-		    &pca9633_led_api);
+#define PCA9633_DEVICE(id) \
+	static const struct pca9633_cfg pca9633_##id##_cfg = {	\
+		.i2c = I2C_DT_SPEC_INST_GET(id)	\
+	};	\
```
Comment (gmarull) [inline drivers/led/pca9633.c:221]: please push backslashes to the same column, as others

File: drivers/led/pca9633.c [hunk 16]
```diff
@@ -43,15 +43,18 @@ LOG_MODULE_REGISTER(pca9633);
 
 #define PCA9633_MASK            0x03
 
+struct pca9633_cfg {
```
Comment (gmarull) [inline drivers/led/pca9633.c:46]: nit: `_config`?

**Review by gmarull — APPROVED** [review]

**Comment by daniel-nicolai-hansten** [comment]
Would it be possible to backport this to zephyr 2.7?

File: drivers/led/pca9633.c [hunk 17]
```diff
@@ -43,15 +43,18 @@ LOG_MODULE_REGISTER(pca9633);
 
 #define PCA9633_MASK            0x03
 
+struct pca9633_config {
+	struct i2c_dt_spec i2c;
+};
```
Comment (bbilas) [inline drivers/led/pca9633.c:48]: Missing newline.

**Review by bbilas — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
