### PR TITLE
tests: error_hook: skip test_catch_fatal_error for Armv8-R

### LINKED ISSUE #63268: tests/ztest/error_hook/testing.ztest.error_hook failing for s32z270dc2_r52 boards
**Describe the bug**
`tests/ztest/error_hook/testing.ztest.error_hook` is failing for `s32z270dc2_r52` boards.

**To Reproduce**
`west twister -p s32z270dc2_rtu0_r52@D -s tests/ztest/error_hook/testing.ztest.error_hook --device-testing --device-serial=/dev/ttyUSB0`

**Expected behavior**
The failed testcase cannot be supported in Armv8-R because trapping division by zero is not supported.

**Impact**
Bugfix for release.

**Logs and console output**
```
TART - test_catch_fatal_error
case type is 0
E: ***** DATA ABORT *****
E: Permission Fault @ 0x317a2d18
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x317a2d10 r12/ip:  0x317806f0 r14/lr:  0x31780820
E:  xpsr:  0x20000110
E: s[ 0]:  0x00000000  s[ 1]:  0x00000000  s[ 2]:  0x00000000  s[ 3]:  0x00000000
E: s[ 4]:  0x00000000  s[ 5]:  0x00000000  s[ 6]:  0x00000000  s[ 7]:  0x00000000
E: s[ 8]:  0x00000000  s[ 9]:  0x00000000  s[10]:  0x00000000  s[11]:  0x00000000
E: s[12]:  0x00000000  s[13]:  0x00000000  s[14]:  0x00000000  s[15]:  0x00000000
E: fpscr:  0x00000000
E: Faulting instruction address (r15/pc): 0x317802d0
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x317a2580 (unknown)
Caught system error -- reason 0 1
Fatal error expected as part of test case.
case type is 1
E: ***** PREFETCH ABORT *****
E: Permission Fault @ 0x317a3fd4
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x317a3fd4 r12/ip:  0x317806f0 r14/lr:  0x317802b0
E:  xpsr:  0x20000110
E: s[ 0]:  0x00000000  s[ 1]:  0x00000000  s[ 2]:  0x00000000  s[ 3]:  0x00000000
E: s[ 4]:  0x00000000  s[ 5]:  0x00000000  s[ 6]:  0x00000000  s[ 7]:  0x00000000
E: s[ 8]:  0x00000000  s[ 9]:  0x00000000  s[10]:  0x00000000  s[11]:  0x00000000
E: s[12]:  0x00000000  s[13]:  0x00000000  s[14]:  0x00000000  s[15]:  0x00000000
E: fpscr:  0x00000000
E: Faulting instruction address (r15/pc): 0x317a3fd4
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x317a2580 (unknown)
Caught system error -- reason 0 1
Fatal error expected as part of test case.
case type is 2
a is 0
FAIL - test_catch_fatal_error in 0.163 seconds
```

**Environment (please complete the following information):**
 - OS: Linux. Windows
 - Toolchain Zephyr SDK
 - Commit SHA 815e7a1e3434dd3be8eba60f64dfaf512bd59fc9

**Additional context**
NA

### PR DESCRIPTION
**Pull request by manuargue**
Skip `test_catch_fatal_error` test case for Armv8-R because divide by zero trapping is not supported on this architecture.

Fixes #63268

```
west twister -p s32z270dc2_rtu0_r52@D --device-testing --device-serial=/dev/ttyUSB0 -T tests/ztest/error_hook/
Renaming output directory to /home/user/zephyrproject/zephyr/twister-out.4
INFO    - Using Ninja..
INFO    - Zephyr version: zephyr-v3.4.0-4641-g0d2e235d4d4d
INFO    - Using 'zephyr' toolchain.
INFO    - Building initial testsuite list...
INFO    - Writing JSON report /home/user/zephyrproject/zephyr/twister-out/testplan.json

Device testing on:

| Platform              | ID   | Serial device   |
|-----------------------|------|-----------------|
| s32z270dc2_rtu0_r52@D |      | /dev/ttyUSB0    |

INFO    - JOBS: 8
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
INFO    - Total complete:    2/   2  100%  skipped:    0, failed:    0, error:    0
INFO    - 2 test scenarios (2 test instances) selected, 0 configurations skipped (0 by static filter, 0 at runtime).
INFO    - 2 of 2 test configurations passed (100.00%), 0 failed, 0 errored, 0 skipped with 0 warnings in 38.01 seconds
INFO    - In total 16 test cases were executed, 1 skipped on 1 out of total 623 platforms (0.16%)
INFO    - 2 test configurations executed on platforms, 0 test configurations were only built.

Hardware distribution summary:

| Board                 | ID   |   Counter |
|-----------------------|------|-----------|
| s32z270dc2_rtu0_r52@D |      |         2 |
INFO    - Saving reports...
INFO    - Writing JSON report /home/user/zephyrproject/zephyr/twister-out/twister.json
INFO    - Writing xunit report /home/user/zephyrproject/zephyr/twister-out/twister.xml...
INFO    - Writing xunit report /home/user/zephyrproject/zephyr/twister-out/twister_report.xml...
INFO    - Run completed
```

### CODE REVIEW

File: tests/ztest/error_hook/src/main.c [hunk 1]
```diff
@@ -115,14 +115,16 @@ __no_optimization static void trigger_fault_divide_zero(void)
...
  * which does not include a divide instruction, the test is skipped,
  * and there will be no hardware exception for that.
+ * For ARMv8-R, divide by zero trapping is not supported in hardware.
  */
 #if (defined(CONFIG_SOC_SERIES_MPS2) && defined(CONFIG_QEMU_TARGET)) || \
 	(defined(CONFIG_SOC_SERIES_MPS3) && defined(CONFIG_QEMU_TARGET)) || \
 	defined(CONFIG_BOARD_QEMU_CORTEX_A53) || defined(CONFIG_SOC_QEMU_ARC) || \
 	defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE) || \
 	defined(CONFIG_BOARD_QEMU_CORTEX_R5) || \
-	defined(CONFIG_BOARD_FVP_BASER_AEMV8R) || defined(CONFIG_BOARD_FVP_BASE_REVC_2XAEMV8A) || \
```
Comment (aaronemassey) [inline tests/ztest/error_hook/src/main.c:124]: Thanks for correcting`CONFIG_BOARD_FVP_BASER_AEMV8R` to `CONFIG_BOARD_FVP_BASER_AEMV8_R`

**Review by aaronemassey — APPROVED** [review]

**Review by hakehuang — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
