### PR TITLE
sensors: Add streaming APIs

### LINKED ISSUE #1387: lack of a performant sensor API
While Zephyr has a sensor data API, it only allows to solve very simple problems. The API does not support FIFO-model which is critical to achieve power savings on the main MCU. A user would have to reimplement his own FIFO- and timestamping capable API if they decide to use Zephyr, and this is non-trivial. Additionally API has limited means to define context where measurement is run. Running each measurement in own thread or circulating measurements via global thread is neither convenient nor efficient.

Existing sensor APIs: 
* [Android, Java](https://developer.android.com/guide/topics/sensors/sensors_overview)
* [Android, C](https://source.android.com/devices/sensors/sensor-stack)

### LINKED ISSUE #13718: Updated Sensor API
API meeting (@carlescufi):
  - Currently (for the next month, until 8th March) under discussion in this Google doc: https://docs.google.com/document/d/1UsElJJHRudeWXb-tYwXA6qt9gF6PH8wwS7PjhqO1MLI/edit#bookmark=id.jkiwnksvdslt

# Updated Sensor API

This issue is an attempt to start identifying improvements that can be made to the current sensor API in Zephyr, with the goal of defining a new API that will eventually replace the existing one.

A more formal proposal will be made in due time, but any weaknesses in the current API can be listed here, or requirements for a new API. 

The current proposals are based on existing issues and discussion during the weekly API call, and are subject to revision. They do no reflect definitive positions, rather a starting point to define a more flexible sensor architecture.

## Project Management

The overall sensor API project is [tracked here](https://github.com/zephyrproject-rtos/zephyr/projects/16).

#### Components (Issues, PRs)

The following issues or PRs are part of the overall sensor API project, and are used for tracking purposes:

- TODO

## Two-tier sensor data API (raw + SI)

- **Raw data** at the lowest level **(mandatory: channel 0, attribute 0)**:
  - Memory efficient (Two mandatory 32-bit values today)
  - Low latency
  - Higher processing burden in user land
- **Standardised SI-based data** at the higher-level **(mandatory: channel 0: attribute 1)**:
  - Higher per-sample memory use
  - Higher latency
  - Low user processing burden (standard SI units and scale, filtering, etc.)
  - Smarter event callbacks based on richer data filtering, etc.

Both tiers must be implemented in a valid sensor driver.

### Timestamp API

- Timestamping API for individual samples, required for DSP filters, logs, etc.
- An option should be provided to enable or disable this feature (memory constraint).

### Flexible Execution Context

- Allow execution context to be specified by user, with a goal of enabling
  a single thread or limited thread count for all sensor activity.

### Internal FIFO Management

- Sensor data is cached via a FIFO buffer associated with channel attributes 
- Allows more efficient resource usage, lower user-burden.
- FIFO should have watermark/threshold alert(s).
- An appropriate set of helper functions should be provided to filter and manipulate buffers.
- It should be possible to use one buffer across multiple attributes efficiently.

### Sensor Data

- Enable raw data for smallest footprint with higher user burden.
- Driver MUST implement raw->stdtype conversion function(s) or provide necessary converstion coefficients (via attributes, etc.)
- Determine sensible SI unit/scale per channel or sensor type
  - Should scale be adjustable at the KConfig level? Auto-scaling?
- Where possible, flag missed sample(s) event between reads.
- Optionally associate variable meta-data (die temp, etc.) with sample.
  - Memory an issue here
  - Seems like this should possible via attributes

> Current thinking is that all sensor data will be based on attribute records, with each **channel** in the sensor driver having appropriate attributes like `CHAN_ATTR_RAW_DATA` and `CHAN_ATTR_SI_DATA`. Each attribute is associated with an appropriate data type and payload.

### Channels

- Channels indicate a specific type of sensor data or information (ex. `CHAN_ACCEL_VECT`, and may have generic catch-all versions like `CHAN_LIGHT` as well as more narrowly defined subtypes like `CHAN_LIGHT_IR`).
- Allow multiple instances of a channel.
- Meta-data can be assigned to channels via **channel attributes**, for example you can associate a wavelength value or range to an instance of the `CHAN_LIGHT` channel via the `CHAN_ATTR_FREQUENCY` attribute.

### Attributes (Device + Channel)

A flexible, generic system is required here, though further discussion is
needed to define the initial attribute list.

Attributes will allow a high degree of flexibility, with only a minimal set of **mandatory** attribute required for basic drivers.

- [Current thinking](https://github.com/zephyrproject-rtos/zephyr/pull/14008#issuecomment-469055223) (subject to debate!) is that two types of attributes makes sense: device attributes, and channel attributes. Needs testing to validate of course.

### Triggers

Triggers are associate with channel attributes, and provide a mechanism to indicate how or when a channel attribute should be updated.

- Review and revise current overly-narrow list of trigger events.
- Use a singly-linked list of callbacks that can be traversed asynchronously,
  starting in the IRQ handler but with the blocking SPI/I2C/ADC calls
  elsewhere. An slist allows this to be dynamically adjusted at runtime.

### Events

- A callback based 'event' system might make debugging and characterisation easier by making it easy to defer error handling, and state tracking to the app level. For example, by having events fire and optionally subscribing to them via a generic callback, you can track conversion start and end events and see if there is a disparity (indicating conversion errors), etc.)

### Calibration API?

- Common API to calculate, load/store and apply calibration coefficients?

### Logging/Storage API?

- Centralised logging API for sensor data to make storing and off-loading
  sensor data at a later date easier? Persist data in a standard format to
  NVM, etc.?

### Device Simulation?

While perhaps not restricted to the sensor API, a design goal should be
enabling simulation of specific sensors when HW isn't available, or specific
edge cases are difficult to reproduce on real HW (to properly test algorithms
or application code that relies on sensor data).

- Allow a sensor driver to 'register' itself at a specific I2C address, and
  in a simulated environment when a generic I2C read/write request is made, the
  I2C handler can redirect the request to the simulated function in the driver.
- The following functions would be required for I2C sensors, for example:
  - Read request handler
  - Write request handler
  - Init function to register the simulated device with the generic I2C layer.

> For an example of this using I2C, see [mcu_sim_i2c.h](https://github.com/apache/mynewt-core/blob/master/hw/mcu/native/include/mcu/mcu_sim_i2c.h) from Apache
  Mynewt, and [tsl2591_sim.c](https://github.com/apache/mynewt-core/blob/master/hw/drivers/sensors/tsl2591/src/tsl2591_sim.c) for a partial implementation of
  this concept.

### Permissions API?

Is a permissions API required/useful/relevant? Should some level of control be put in place over, for example, being able to access raw or sensitive data?

- Perhaps an 8-bit value can be associated with a device or channel attribute with flags like `Read`
, `Write`, `Public`, `Private`, etc.?

### Firmware Management?

Certain classes of sensors today have user updatable firmware. It's worth at least considering some of the implications around this, and how to update sensors on deployed devices, even if it's a very manufacturer-specific requirement.

## Security Considerations

There are a number of critical security consideration to keep in mind when working with sensor data, and how it is exposed. For example, on devices with touch screens where a password may be entered, and where sensor data like accel/mag/gyro readings is publicly being streamed out, you can detect passwords based on the sensor data.

There should perhaps be some security mechanisms in situations like entering a password, where certain classes of sensors can be disabled to reduce the overall risk (disable the accel and gyro while the password screen is shown or while a keypad is being used for password or ID entry).

This fits into the permissions API idea to an extent, but is sufficiently different to merit individual consideration.

> The [W3 Generic Sensor API](https://www.w3.org/TR/generic-sensor/) highlights a number of security risks associated with sensors, and some suggestions on mitigating these risks. It's worth reading through for the numerous practical implications the document details.

> Discussion of accelerometer abuse in mobile devices: https://www.mysk.blog/2021/10/24/accelerometer-ios/

> Sensor rate limiting on Android as a security mitigation: https://developer.android.com/guide/topics/sensors/sensors_overview#sensors-rate-limiting

# Related Issues

#14008 : WIP: Sensor API Playground
#13455 : Improvements to `drivers/sensors` for light sensors
#1387 : Lack of a performant sensor API
#14245 : Sensor API channel definitions

# Existing APIs to consider

- [Linux IIO](https://01.org/linuxgraphics/gfx-docs/drm/driver-api/iio/index.html)
  - [Linux IIO standard attribute list](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-bus-iio)
- [W3 Generic Sensor API](https://www.w3.org/TR/generic-sensor/)
- [Android Sensor API and ContextHub](
https://android.googlesource.com/device/google/contexthub/)
  - Related Android Sensor API components:
    - [ISensors](https://source.android.com/reference/hidl/android/hardware/sensors/1.0/ISensors)
    - [ISensorManager](https://source.android.com/reference/hidl/android/frameworks/sensorservice/1.0/ISensorManager) 
    - [ContextHub](https://source.android.com/reference/hidl/android/hardware/contexthub/1.0/IContexthub)
    -  Channels, event, etc.: [sensors-base.h](https://android.googlesource.com/platform/hardware/libhardware/+/master/include/hardware/sensors-base.h)
    - Core structs like `sensors_event_t ` [sensors.h](https://android.googlesource.com/platform/hardware/libhardware/+/master/include/hardware/sensors.h)

> Context hub is intended to enable the use of additional co-processors for sensor data, and the interaction between context hub and the main kernel or sensor API might have some useful insights to consider.

### PR DESCRIPTION
**Pull request by yperess**
Introduce a streaming API that uses the same data path as the async API.

This includes features to the decoder:
* Checking if triggers are present

Adding streaming features built ontop of existing triggers:
* Adding 3 operations to be done on a trigger
  * include - include the data with the trigger information
  * nop - do nothing
  * drop - drop the data (flush)
* Add a new sensor_stream() API to mirror sensor_read() but add an
optional handler to be able to cancel the stream.

Fixes #1387 
Fixes #13718

### CODE REVIEW

File: include/zephyr/drivers/sensor.h [hunk 1]
```diff
@@ -246,6 +246,9 @@ enum sensor_trigger_type {
 
 	/** Trigger fires when no motion has been detected for a while. */
 	SENSOR_TRIG_STATIONARY,
+
+	SENSOR_TRIG_FIFO_THRESHOLD,
+	SENSOR_TRIG_FIFO_FULL,
```
Comment (asemjonovs) [inline include/zephyr/drivers/sensor.h:251]: Nit: Add comment

**Review by asemjonovs — DISMISSED** [review]

**Comment by teburd** [comment]
I'll try and look at this soon

**Comment by nashif** [comment]
@yperess  do we need to update the documnetaion with this new addition?

**Comment by yperess** [comment]
> @yperess  do we need to update the documnetaion with this new addition?

I'm holding off on the documentation to make sure it's stable before we start directing people to it. Though if you think there's a benefit to it I'm happy to do it and put a banner above for "experimental"

I have some changes in the pipe for the decoder (expected to be done late next week)

**Review by teburd — DISMISSED** [review]

File: include/zephyr/drivers/sensor.h (hunk 1 above)
Comment (yperess) [reply include/zephyr/drivers/sensor.h]: Done

**Comment by yperess** [comment]
@teburd and @asemjonovs when looking at the `Compare` the first force push was a rebase, the second adds the doxygen.

**Review by asemjonovs — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by yperess** [comment]
Had an issue when rebasing. I had to move the streaming logic out to a separate file.

**Review by asemjonovs — DISMISSED** [review]

File: drivers/sensor/sensor_shell.c [hunk 2]
```diff
@@ -349,21 +443,32 @@ static int cmd_get_sensor(const struct shell *sh, size_t argc, char *argv[])
...
+	ARG_UNUSED(b);
+	ARG_UNUSED(c);
+
+	while (true) {
+		sensor_processing_with_callback(&sensor_read_rtio,
+						sensor_shell_processing_callback);
+	}
+}
+K_THREAD_DEFINE(sensor_shell_processing_tid, CONFIG_SENSOR_SHELL_THREAD_STACK_SIZE,
+		sensor_shell_processing_entry_point, NULL, NULL, NULL, 0, 0, 0);
```
Comment (MaureenHelm) [inline drivers/sensor/sensor_shell.c:470]: I know this is useful for testing the new streaming feature, but there are other users of the sensor shell that don't want to take the memory hit. Can you please partition the sensor shell changes so the it can still be used with `CONFIG_SENSOR_ASYNC_API=n`?

File: include/zephyr/drivers/sensor.h [hunk 3]
```diff
@@ -246,6 +246,12 @@ enum sensor_trigger_type {
 
 	/** Trigger fires when no motion has been detected for a while. */
 	SENSOR_TRIG_STATIONARY,
+
+	/** Trigger fires when the FIFO threshold has been reached. */
+	SENSOR_TRIG_FIFO_THRESHOLD,
```
Comment (MaureenHelm) [inline include/zephyr/drivers/sensor.h:251]: Replace "threshold" with "watermark" to be consistent with the attribute enum?

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

File: drivers/sensor/sensor_shell.c (hunk 2 above)
Comment (yperess) [reply drivers/sensor/sensor_shell.c]: Done

File: include/zephyr/drivers/sensor.h (hunk 3 above)
Comment (yperess) [reply include/zephyr/drivers/sensor.h]: Done

**Comment by yperess** [comment]
Build error is caused by https://github.com/zephyrproject-rtos/zephyr/pull/60695

File: drivers/sensor/sensor_shell.c [hunk 4]
```diff
@@ -233,19 +263,43 @@ static int parse_sensor_value(const char *val_str, struct sensor_value *out)
...
-static void sensor_shell_processing_callback(int result, uint8_t *buf, uint32_t buf_len,
-					     void *userdata)
+void sensor_shell_processing_callback(int result, uint8_t *buf, uint32_t buf_len, void *userdata)
 {
+	static struct {
+		int64_t accumulator;
+		int8_t shift;
+		int count;
+		bool is_active;
+	} sample_stats[SENSOR_CHAN_COMMON_COUNT];
```
Comment (MaureenHelm) [inline drivers/sensor/sensor_shell.c:295]: This might be better done with the stats subsys

**Comment by lixuzha** [comment]
Hi @yperess,

I'm evaluating how to enable sensing subsys with stream api based on this pull request.
During the evaluation, I thought there might be some potential gaps in this PR. Could you please help check and comment?

1. Can ACCEL FIFO and GYRO FIFO be enabled separately? For example, when the user only wants to use the Accel function, turning off Gyro can save more power.

2. If an A/G combo sensor is upgraded with streaming API, can user enable accel with FIFO, while keep using gyro in polling mode?

**Comment by yperess** [comment]
> Hi @yperess,
> 
> I'm evaluating how to enable sensing subsys with stream api based on this pull request.
> During the evaluation, I thought there might be some potential gaps in this PR. Could you please help check and comment?
> 
> 1. Can ACCEL FIFO and GYRO FIFO be enabled separately? For example, when the user only wants to use the Accel function, turning off Gyro can save more power.

There's only 1 hardware FIFO usually. The inclusion depends on the sample rate. So by enabling the FIFO + setting an accelerometer ODR you're including the accelerometer in the FIFO. If you then set the ODR for the gyro, it'll be included too.

> 2. If an A/G combo sensor is upgraded with streaming API, can user enable accel with FIFO, while keep using gyro in polling mode?

You can always poll and get the latest sample. So the polling result should always be the same as the tail of the FIFO.

File: include/zephyr/drivers/sensor.h [hunk 5]
```diff
@@ -511,13 +528,38 @@ struct sensor_decoder_api {
...
+	}
 /*
  * Internal data structure used to store information about the IODevice for async reading and
  * streaming sensor data.
  */
 struct sensor_read_config {
 	const struct device *sensor;
-	enum sensor_channel *const channels;
+	const bool is_streaming;
+	union {
```
Comment (teburd) [inline include/zephyr/drivers/sensor.h:559]: I don't think this should be a union, the reader may wish to select channels and trigger sources independently, e.g. on data ready read the gyro x and y channels only

**Review by teburd — COMMENTED** [review]
Some notes on places that maybe are worth changing to account for something pointed out by @lixuzha (great eye!)

File: include/zephyr/drivers/sensor.h [hunk 6]
```diff
@@ -540,12 +582,24 @@ struct sensor_read_config {
...
 	static struct sensor_read_config __sensor_read_config_##name = {                           \
 		.sensor = DEVICE_DT_GET(dt_node),                                                  \
+		.is_streaming = false,                                                             \
 		.channels = __channel_array_##name,                                                \
 		.count = ARRAY_SIZE(__channel_array_##name),                                       \
 		.max = ARRAY_SIZE(__channel_array_##name),                                         \
 	};                                                                                         \
 	RTIO_IODEV_DEFINE(name, &__sensor_iodev_api, &__sensor_read_config_##name)
 
+#define SENSOR_DT_STREAM_IODEV(name, dt_node, ...)                                                 \
```
[the remark this answers is not in the document]
Comment (yperess) [reply include/zephyr/drivers/sensor.h:592]: Assumption: I think this isn't a super common thing (i.e. many sensors won't have this filter).

Overall, that feature sounds like we should be adding an attribute. This way the application can configure the FIFO to filter gyroscope data, and the steam request can focus on the when aspect. can you link a datasheet so I can see this filter?

[the remark this answers is not in the document]
Comment (teburd) [reply include/zephyr/drivers/sensor.h:592]: icm42688, icm20469, lsm6dso, bmi270 all support this sort of thing where you can select what goes in the fifo

**Comment by lixuzha** [comment]
> > Hi @yperess,
> > I'm evaluating how to enable sensing subsys with stream api based on this pull request.
> > During the evaluation, I thought there might be some potential gaps in this PR. Could you please help check and comment?
> > 
> > 1. Can ACCEL FIFO and GYRO FIFO be enabled separately? For example, when the user only wants to use the Accel function, turning off Gyro can save more power.
> 
> There's only 1 hardware FIFO usually. The inclusion depends on the sample rate. So by enabling the FIFO + setting an accelerometer ODR you're including the accelerometer in the FIFO. If you then set the ODR for the gyro, it'll be included too.
> 
From the code, looks like every time when sensor ODR is changed, the FIFO will need to be clean up and reset. 
Based on upper layer virtual sensor and application request, the sensing subsystem arbitration logic could change gyro ODR back and forth frequently, but in proposed design, gyro ODR change will have an impact to accel FIFO status, which does not look efficient and reasonable to me.

> > 2. If an A/G combo sensor is upgraded with streaming API, can user enable accel with FIFO, while keep using gyro in polling mode?
> 
> You can always poll and get the latest sample. So the polling result should always be the same as the tail of the FIFO.

The question is actually not about how to poll gyro data. My question is that: if I want to config accel in FIFO mode (suppose user wants to stream accel in extremely high ODR, and maximally leverage the FIFO), and config gyro in polling mode (with normal ODR), can I do it with current design?


Furthermore, suppose a user developed an application based on the new stream API for channel accel_x, y, z and gyro_x, y, z, with two separated sensors (bma280 + bmg160), then the user change his sensor BOM to a combo sensor (icm42688). In this case, does this user need to upgrade his application?

File: include/zephyr/drivers/sensor.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (yperess) [reply include/zephyr/drivers/sensor.h:592]: OK, found it in `FIFO_CONFIG1` for the icm42688, thanks. I still think this belongs more as an attribute than as a part of the read request no?

File: include/zephyr/drivers/sensor.h (hunk 5 above)
Comment (yperess) [reply include/zephyr/drivers/sensor.h:559]: I wanted to avoid adding things that would/could get confusing. For example, lets say my application wants to know about the `RESET_DONE_INT`. I would have to add it to the triggers in sensor.h, then I could set the stream to tell me about it. I wouldn't set any channels. Does that mean I want to turn off the FIFO?

The current design is such that the read configs are minimally intrusive. Setting filters like that which affect the configuration registers should be done via attributes. In your example specifically:
* If the application only cares about reading the gyro data they can set the accel ODR to 0Hz
* If the application wants to batch gyro and poll accel they can set the ODR for both and add a PR to add new attributes to configure the FIFO to exclude channels.

**Comment by yperess** [comment]
> From the code, looks like every time when sensor ODR is changed, the FIFO will need to be clean up and reset. Based on upper layer virtual sensor and application request, the sensing subsystem arbitration logic could change gyro ODR back and forth frequently, but in proposed design, gyro ODR change will have an impact to accel FIFO status, which does not look efficient and reasonable to me.

A few things on that,
1. I don't imagine the arbitrated configuration changing enough to make a difference
2. @teburd and I are working on a vertical decoder which will replace the one we have. This will mean that the sensor.h data representation will match 1:1 with that of the subsystem. i.e. the user can ask to decode all the frames of channel X. This allows us to move the structs like `sensing_sensor_three_axis_data` down one level to `sensor_three_axis_data` which will be the output of the decoder. This will include the timestamp and offset and will get rid of exactly what you're describing (having to flush the FIFO on configuration changes).

Hopefully the second point here helps.

> The question is actually not about how to poll gyro data. My question is that: if I want to config accel in FIFO mode (suppose user wants to stream accel in extremely high ODR, and maximally leverage the FIFO), and config gyro in polling mode (with normal ODR), can I do it with current design?

I'd like to consolidate these threads as it seems we talk about the same thing in 3 different places. Please continue this question on https://github.com/zephyrproject-rtos/zephyr/pull/60063#discussion_r1285059486. The short of it, send a PR to add this FIFO config as an attribute.
 
> Furthermore, suppose a user developed an application based on the new stream API for channel accel_x, y, z and gyro_x, y, z, with two separated sensors (bma280 + bmg160), then the user change his sensor BOM to a combo sensor (icm42688). In this case, does this user need to upgrade his application?

Yes, but that's exactly why we're building the subsystem. Every layer has it's own job. We can't expect the kernel level drivers to abstract these board layout choices. My advice to the developer would be to use the sensing subsystem. One of the advantages of pushing for the vertical decoder mentioned above is that the data representation will be the same for sensor.h and sensing.h. This means that once in and people are migrating their existing applications to use sensor.h's new API, they'll also have an easy time migrating to sensing.h.

File: include/zephyr/drivers/sensor.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (teburd) [reply include/zephyr/drivers/sensor.h:592]: I guess that's an interesting question here, what constitutes the stream options (sensor read config) vs sensor attributes. At the moment the poll interface lets you select channels and in this PR the stream interface lets you select which triggers but not which channels.

That seems a little strange I guess. I'm not opposed to making them attributes, but I guess if the goal is uniform interfaces for simplicity, it would make sense to allow the stream to also select which channels to read.

[the remark this answers is not in the document]
Comment (lixuzha) [reply include/zephyr/drivers/sensor.h:592]: I kind of agree with Tom.

**Comment by lixuzha** [comment]
> > Furthermore, suppose a user developed an application based on the new stream API for channel accel_x, y, z and gyro_x, y, z, with two separated sensors (bma280 + bmg160), then the user change his sensor BOM to a combo sensor (icm42688). In this case, does this user need to upgrade his application?
> 
> Yes, but that's exactly why we're building the subsystem. Every layer has it's own job. We can't expect the kernel level drivers to abstract these board layout choices. My advice to the developer would be to use the sensing subsystem. One of the advantages of pushing for the vertical decoder mentioned above is that the data representation will be the same for sensor.h and sensing.h. This means that once in and people are migrating their existing applications to use sensor.h's new API, they'll also have an easy time migrating to sensing.h.

Please be aware that sensing subsystem is optional module in Zephyr, and in above case, we are talking about the application directly uses sensor device driver without sensing subsystem. My understanding is that this should be the default case whenever we consider upgrading sensor device driver API, right?

File: include/zephyr/drivers/sensor.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (yperess) [reply include/zephyr/drivers/sensor.h:592]: The problem I'm having with specifying the channels in this request is ambiguity. Now, please note I'm very possibly wrong here, but the point I'm making is that it's possible to make the following assumption because that's what I would think.

If I were implementing a driver and I got a steam request for the watermark trigger and just accel (no gyro). I would assume that means I can turn off the gyro. Now, the discussion we're having says no, just remove it from the FIFO. But that's not really specified in the API and it's open for interpretation.

Alternatively, if we add a new attribute `SENSOR_ATTR_FIFO_ACCEL_ENABLE` and the same for gyro, then there's no confusion. The steam option just says enable these triggers and give me any associated data. You'll always get the triggers with the timestamp, and it gives you 3 options of what to do with the rest of the data:
* Discard / flush
* Ignore / do nothing
* Read

There's a very clear line between what the API is trying to do. Anything more, you need to call sensor_set_attr

**Comment by yperess** [comment]
> > Yes, but that's exactly why we're building the subsystem. Every layer has it's own job. We can't expect the kernel level drivers to abstract these board layout choices. My advice to the developer would be to use the sensing subsystem. One of the advantages of pushing for the vertical decoder mentioned above is that the data representation will be the same for sensor.h and sensing.h. This means that once in and people are migrating their existing applications to use sensor.h's new API, they'll also have an easy time migrating to sensing.h.
> 
> Please be aware that sensing subsystem is optional module in Zephyr, and in above case, we are talking about the application directly uses sensor device driver without sensing subsystem. My understanding is that this should be the default case whenever we consider upgrading sensor device driver API, right?

Right, that's inline with what I said. If the data representation of the kernel level drivers is the same though, then it's easy for developers to start off managing the sensors themselves and migrate to adding the subsystem when they want:
* Arbitration
* Multiplexing
* Virtual sensors

The idea is that the application logic that's handling the sensor data should require minimal changes when adding the subsystem. But this seems to be a discussion more for https://github.com/zephyrproject-rtos/zephyr/issues/36963

**Comment by KeHIntel** [comment]
> it's easy for developers to start off managing the sensors themselves and migrate to adding the subsystem when they want: Arbitration, Multiplexing, Virtual sensors

Hi, Yuval, you are definitely right that Zephyr application based on sensing subsystem with wrapper over streaming API should have no such problem, but **Lixu's question here is more focusing on streaming API itself**. 

Streaming API can be directly used by Zephyr application without sensing subsystem, we will need to consider impact to this kind of cases as well. I think current expectation is that when sensor channels have no change, sensor application should have no change, even sensor BOM is changed.

**Comment by nashif** [comment]
> Hi, Yuval, you are definitely right that Zephyr application based on sensing subsystem with wrapper over streaming API should have no such problem, but **Lixu's question here is more focusing on streaming API itself**.
> 
> Streaming API can be directly used by Zephyr application without sensing subsystem, we will need to consider impact to this kind of cases as well. I think current expectation is that when sensor channels have no change, sensor application should have no change, even sensor BOM is changed.

@yperess  can you please address the question above?

**Comment by yperess** [comment]
> > it's easy for developers to start off managing the sensors themselves and migrate to adding the subsystem when they want: Arbitration, Multiplexing, Virtual sensors
> 
> Hi, Yuval, you are definitely right that Zephyr application based on sensing subsystem with wrapper over streaming API should have no such problem, but **Lixu's question here is more focusing on streaming API itself**.
> 
> Streaming API can be directly used by Zephyr application without sensing subsystem, we will need to consider impact to this kind of cases as well. I think current expectation is that when sensor channels have no change, sensor application should have no change, even sensor BOM is changed.

I believe what I'm understanding is that the concern is that we shouldn't be taking into account the subsystem when designing the kernel drivers.

If that's correct, I'd say sure... maybe... but does it really matter? If the data representation is optimal for data processing, then it's the best representation. Regardless of where it is (subsystem or driver). If it's the best representation, then it belongs in both. The current representation of channels is overly restrictive. It assumes a single dimension per channel (with a few odd `XYZ` exceptions). I don't think this is necessary and I believe we can do better. In the new APIs (the async APIs) the channel is much more like a type. The type maps to a struct. Custom sensor types/channels in the application may define new structs as long as they provide a decoder along with it.

What does this look like? It might mean that a sensor can produce much more rich data. Things like a heatmap or a lidar scan even.

**Comment by KeHIntel** [comment]
> I believe what I'm understanding is that the concern is that we shouldn't be taking into account the subsystem when designing the kernel drivers.

I think so, this is today's default model to use sensor in Zephyr, and sensing subsystem is not fully merged. Any change to device driver API shall consider the default usage model at first place.
 
> If that's correct, I'd say sure... maybe... but does it really matter? 

It matters. My understanding is that Zephyr sensors has a market in low end IOT devices whose sensing requirements are simple, but memory/computation requirements are strict. I foresee that these devices will continue adopt the default model to use sensors, without sensing subsystem. They may adopt FIFO, as it brings a few benefits, so we have to consider them in this PR.

**Comment by yperess** [comment]
> > I believe what I'm understanding is that the concern is that we shouldn't be taking into account the subsystem when designing the kernel drivers.
> 
> I think so, this is today's default model to use sensor in Zephyr, and sensing subsystem is not fully merged. Any change to device driver API shall consider the default usage model at first place.
> 
> > If that's correct, I'd say sure... maybe... but does it really matter?
> 
> It matters. My understanding is that Zephyr sensors has a market in low end IOT devices whose sensing requirements are simple, but memory/computation requirements are strict. I foresee that these devices will continue adopt the default model to use sensors, without sensing subsystem. They may adopt FIFO, as it brings a few benefits, so we have to consider them in this PR.

Right but we're just talking about data representation here. I'm not saying they need to use the subsystem.

**Comment by KeHIntel** [comment]
> Right but we're just talking about data representation here. I'm not saying they need to use the subsystem.

I agree with your points on the data representation, your effort in driving FIFO streaming and vertical decoder are well appreciated. However, our comments on this PR is mainly about the modification of the sensor device driver API itself. With driver API today, an application can work with A/G combo sensor, as well as A/G separated sensor; however, with this PR, this will be broken, and I believe this shall be fixed before we merge this PR.

**Review by teburd — DISMISSED** [review]

File: include/zephyr/drivers/sensor.h [hunk 7]
```diff
@@ -567,12 +611,24 @@ struct sensor_read_config {
...
+	static enum sensor_trigger_type __trigger_array_##name[] = {__VA_ARGS__};                  \
+	static struct sensor_read_config __sensor_read_config_##name = {                           \
+		.sensor = DEVICE_DT_GET(dt_node),                                                  \
+		.is_streaming = true,                                                              \
+		.triggers = __trigger_array_##name,                                                \
```
Comment (lixuzha) [inline include/zephyr/drivers/sensor.h:626]: The type of `.triggers` is different form `__trigger_array_##name`.

Comment (yperess) [reply include/zephyr/drivers/sensor.h:626]: Thanks, forgot to update since the sensor shell I was using to test just allocated this by size without any values. Fixed.

**Review by teburd — DISMISSED** [review]

**Review by tristan-google — DISMISSED** [review]

**Comment by yperess** [comment]
> > Right but we're just talking about data representation here. I'm not saying they need to use the subsystem.
> 
> I agree with your points on the data representation, your effort in driving FIFO streaming and vertical decoder are well appreciated. However, our comments on this PR is mainly about the modification of the sensor device driver API itself. With driver API today, an application can work with A/G combo sensor, as well as A/G separated sensor; however, with this PR, this will be broken, and I believe this shall be fixed before we merge this PR.

Lets start off with the current fetch/get model. It's not a good one and there's a reason we want to move away from it. Here's a scenario:

1. Thread 1 calls fetch
    1. Driver caches the data
1. Thread 1 reads ACCEL from cache
2. Context switch
3. Thread 2 calls fetch
    1. Driver caches new data
4.   Context switch
5. Thread 1 reads GYRO (but there's no access to the data from step 1)

The async model that @teburd and I put together puts the data in the ownership of the caller so it looks more like

1. Thread 1 calls fetch
2. Driver allocates a buffer and reads into it, then gives ownership of the buffer to the caller
3. Thread 1 owns the buffer and can release it when it wants
4. Context switch
5. Thread 2 calls fetch
6. Driver repeats step 2 giving the buffer to thread 2
7. Context switch
8. Thread 1 can keep using the same buffer

In my demo that I sent out about the subsytem you can see that the model is that there's a sensor wrapper which is responsible for getting the data from the physical sensor. It's the wrapper that does the demuxing and decoding. Once the demuxing is done based on the original SQE(s), the decoded data is sent as CQE(s) which are handled by the subsystem and sent out via callbacks. Below is a simple example showing a one-shot request. This flow is even more critical in streaming APIs because you don't want the driver to own the data, the options are:
1. Driver owns the data and can't service any more requests until the clients are done
2. Driver supports owning _N_ data buffers simultaneously
3. We implement a shared pointer
4. We have the client own the memory once it's read by the driver <-- this is the approach the async APIs are using.

Sensors  overview - driver design

**Review by KeHIntel — CHANGES_REQUESTED** [review]
To my understanding, the nature of the sensor driver is to offer a common abstraction to the application, and hide the difference from datasheet details. FIFO config is a datasheet detail, it shouldn’t be exposed to the application from sensor driver.

There should always be separated RTIO FIFOs set up for separated type/channel of sensors. The motivation of combo sensor design from sensor vendors are mainly cost saving, Interleaving A/G into one FIFO is a specific HW design choice (and not applicable to all), it does not mean SW should follow.

Furthermore (1), before this PR, I believe a Zephyr application that consumes sensors only needs to care about sensor channel, and does not need to care about any sensor HW characteristics difference. If we approve this PR as is, this assumption will be broken.

Furthermore (2), as the 1st group of users of this API from sensing subsystem, we expect to use the streaming API in the same way for the case of single A/G combo sensor (with one FIFO) vs two standalone A/G sensors (with two FIFOs). I strongly request this PR to consider this requirement.

**Comment by yperess** [comment]
> To my understanding, the nature of the sensor driver is to offer a common abstraction to the application, and hide the difference from datasheet details. FIFO config is a datasheet detail, it shouldn’t be exposed to the application from sensor driver.

This API doesn't add any internal data sheet specifications. Users can set the batching using a time duration and the driver will convert that to a FIFO watermark. Is the concern that the triggers being added the `FIFO_WATERMARK` and `FIFO_FULL`? I'm happy to rename them to `BATCH_READY` and `SAMPLE_DROPPED` if you'd like.

> There should always be separated RTIO FIFOs set up for separated type/channel of sensors. The motivation of combo sensor design from sensor vendors are mainly cost saving, Interleaving A/G into one FIFO is a specific HW design choice (and not applicable to all), it does not mean SW should follow.

I get what you're saying, but I don't think it's a reasonable ask. The whole point of the RTIO integration and the async API was to be able to remove all the processing from the drivers. This makes it such that the sensor drivers no longer need to choose between a dedicate processing thread or the system work queue (both weren't great options). Instead, now reading the sensor (both one shot and FIFO) can be done in an interrupt context via the RTIO subsystem that @teburd created). The work of processing the data and splitting it up is left to the client via the `Decoder` API.

> Furthermore (1), before this PR, I believe a Zephyr application that consumes sensors only needs to care about sensor channel, and does not need to care about any sensor HW characteristics difference. If we approve this PR as is, this assumption will be broken.

This PR enables the application to request attributes for batching, if the driver doesn't support it, they'll get an error. This is no different from an application trying to read a channel that's not supported by a sensor currently. We're adding attributes and triggers which may or may not be available on a sensor.

> Furthermore (2), as the 1st group of users of this API from sensing subsystem, we expect to use the streaming API in the same way for the case of single A/G combo sensor (with one FIFO) vs two standalone A/G sensors (with two FIFOs). I strongly request this PR to consider this requirement.

I'm not sure I understand, I'll re-iterate what I understood and please correct me where I'm wrong:

#### Scenario 1
I have 1 sensor with interleaved accel/gyro in the FIFO. Reading this FIFO will give me both sensor types.

I think you're asking the driver to read the FIFO into a buffer, then allocate 2 more buffers and split the data up between the two. If so, this would require a lot of processing that we don't know that the application needs. It would require a processing thread again for every sensor which is what we're trying to move away from. 

#### Scenario 2
I have 2 sensors with separate FIFOs, one sensor provides acceleration and the other gyroscope.

In this case you read acceleration from sensor 0 and gyroscope readings from sensor 1 and there's no processing needed beyond decoding the data.

#### My take on this
Design principals of single responsibility are paramount when designing such a complex and long data pipeline. The sensor driver should not be doing any processing on the data which allows it to run all the reading commands in an interrupt context. It also saves us from doing potentially unnecessary memory copies. I think it's also not reasonable to say that you want to be able to read _JUST_ the accelerometer from scenario 1. Reading the FIFO will clear it, so you'd need to burn a lot of memory to accommodate a use which isn't guaranteed to be needed. Instead, we will provide the caller with the full buffer that was read and a Decoder which allows you to consume the accel and gyro samples independently from the driver. This model works across MCUs even where the decoding isn't done on the same core as the collection. Here' s my view on the responsibilities of the data pipeline stages:

* Driver - collect data and return it to the client
* Decoder - query the data to a format that's compatible with Zephyr's DSP subsystem
* Subsystem - provide support for multiple clients to the same sensor
* Virtual sensors - provide software solutions to sensors that don't physically exist

Adding processing to the driver will overlap the the responsibility of the Decoder.

**Comment by teburd** [comment]
I'd add there's maybe a few interesting devices to look at for sort of the extremes of this story. One is basically two devices (accel/gyro) combined into one physical package and register map. The other is a highly integrated sensor hub that interleaves *many* possible events into a single FIFO along with algorithm outputs.

| Device | FIFO(s) | Datasheet |
|--------|--------|--------|
| Bosch BMI085 | Accel FIFO, Gyro FIFO | [Datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmi085-ds001.pdf) |
| Bosch BHI260AP | Wake-Up FIFO, Non-Wake-Up FIFO, Status and Debug FIFO | [Datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bhi260ap-ds000.pdf) |

It's pretty easy to represent the BMI085 as two distinct devices with two struct device implementations. That's how Zephyr treats it today. Two distinct struct device's.

The second device with a highly integrated sensor hub, including event detection and fusion producing things like orientation vectors would be... incredibly difficult to split into multiple streams of independent data.

**Comment by yperess** [comment]
@teburd initial thoughts about both of those. They seem like the extreme cases (which I think was the point). The BMI085 not only has 2 separate FIFOs, but separate interrupts for accel/gyro data ready. The second sensor seems to also provide a lot of extra, I'll call them bells and whistles for now. The driver is suppose to cover the 90/10 rule IMO, the extras can be done via their own `bmi085.h` etc and expose these nuanced functionalities that are specific to the driver. Otherwise, we'd need to add a trigger for every channel and maybe even an index like we did with the decoder. Soon enough the API is just too complicated. I'll dive deeper into these tomorrow.

**Comment by teburd** [comment]
Going the opposite route in a thought experiment I had last night, muxing the FIFOs into a single stream seemed to play out reasonably well.

* Streams were already muxed, muxing the FIFOs doesn't change much
* Keeps the single iodev avoiding having to deal with device specifics around how many FIFOs it has
* The decoder still works in the above two bosch devices with multiple FIFOs if the identifier for which FIFO the data was read from is placed in the header just before the read data.

**Comment by KeHIntel** [comment]
> I'd add there's maybe a few interesting devices to look at for sort of the extremes of this story. One is basically two devices (accel/gyro) combined into one physical package and register map. The other is a highly integrated sensor hub that interleaves _many_ possible events into several FIFOs along with algorithm outputs.
> 
> Device	FIFO(s)	Datasheet
> Bosch BMI085	Accel FIFO, Gyro FIFO	[Datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmi085-ds001.pdf)
> Bosch BHI260AP	Wake-Up FIFO, Non-Wake-Up FIFO, Status and Debug FIFO	[Datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bhi260ap-ds000.pdf)

This is exactly the sensor datasheet difference I am talking about, it shouldn't be left to sensor application to handle.

> muxing the FIFOs into a single stream seemed to play out reasonably well.

This is fine to me, as long as the sensor HW detail on FIFO arrangement are hide beneath the streaming API, and no need application level to care, I am OK. Always muxing or always separated are both OK to me.

**Comment by teburd** [comment]
> > I'd add there's maybe a few interesting devices to look at for sort of the extremes of this story. One is basically two devices (accel/gyro) combined into one physical package and register map. The other is a highly integrated sensor hub that interleaves _many_ possible events into several FIFOs along with algorithm outputs.
> > Device	FIFO(s)	Datasheet
> > Bosch BMI085	Accel FIFO, Gyro FIFO	[Datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmi085-ds001.pdf)
> > Bosch BHI260AP	Wake-Up FIFO, Non-Wake-Up FIFO, Status and Debug FIFO	[Datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bhi260ap-ds000.pdf)
> 
> This is exactly the sensor datasheet difference I am talking about, it shouldn't be left to sensor application to handle.
> 
> > muxing the FIFOs into a single stream seemed to play out reasonably well.
> 
> This is fine to me, as long as the sensor HW detail on FIFO arrangement are hide beneath the streaming API, and no need application level to care, I am OK. Always muxing or always separated are both OK to me.

I agree dealing with multiple fifos is exposing the wrong thing.


It seems like the best route then is always muxing.

It sounds like we’ve found agreement then?

**Comment by KeHIntel** [comment]
> It seems like the best route then is always muxing.
> 
> It sounds like we’ve found agreement then?

It looks ok to always muxing in the case of combo sensor. However, if there are two standalone sensor, one for A, another for G. In such case, there are two separated sensor device drivers with two separated FIFOs, how can we achieve always muxing?

**Comment by yperess** [comment]
@teburd , @tristan-google will be upstreaming the bma422 driver which supports FIFO APIs on our end as the next target.

**Comment by yperess** [comment]
> > It seems like the best route then is always muxing.
> > It sounds like we’ve found agreement then?
> 
> It looks ok to always muxing in the case of combo sensor. However, if there are two standalone sensor, one for A, another for G. In such case, there are two separated sensor device drivers with two separated FIFOs, how can we achieve always muxing?

I'm not sure I follow, if you have 2 separate `struct device` objects then you won't mux the 2 streams. We will only mux the two if a single `struct device` has 2+ separate FIFOs.

**Comment by KeHIntel** [comment]
> > > It seems like the best route then is always muxing.
> > > It sounds like we’ve found agreement then?
> > 
> > It looks ok to always muxing in the case of combo sensor. However, if there are two standalone sensor, one for A, another for G. In such case, there are two separated sensor device drivers with two separated FIFOs, how can we achieve always muxing?
> 
> I'm not sure I follow, if you have 2 separate `struct device` objects then you won't mux the 2 streams. We will only mux the two if a single `struct device` has 2+ separate FIFOs.

From sensor driver development perspective, this might make sense; but from application perspective, what we want to achieve is to use common code for A/G sensor, no matter it is combo sensor with single FIFO, or multiple FIFOs, or individual sensors with separated FIFOs.

**Comment by yperess** [comment]
> > > > It seems like the best route then is always muxing.
> > > > It sounds like we’ve found agreement then?
> > > 
> > > 
> > > It looks ok to always muxing in the case of combo sensor. However, if there are two standalone sensor, one for A, another for G. In such case, there are two separated sensor device drivers with two separated FIFOs, how can we achieve always muxing?
> > 
> > 
> > I'm not sure I follow, if you have 2 separate `struct device` objects then you won't mux the 2 streams. We will only mux the two if a single `struct device` has 2+ separate FIFOs.
> 
> From sensor driver development perspective, this might make sense; but from application perspective, what we want to achieve is to use common code for A/G sensor, no matter it is combo sensor with single FIFO, or multiple FIFOs, or individual sensors with separated FIFOs.

I'm not sure how you'd achieve this if the sensors are in separate device structs. The thinking is that the drivers will provide **ALL** of their data, the decoder will allow you to demux as needed. If you want to have multiple clients, then the suggestion will be to use the subsystem which will own the demuxing and provide you with the ability to subscribe to a single sensor_info node (but that's beyond the scope for the kernel drivers).

**Comment by KeHIntel** [comment]
> > > > > It seems like the best route then is always muxing.
> > > > > It sounds like we’ve found agreement then?
> > > > 
> > > > 
> > > > It looks ok to always muxing in the case of combo sensor. However, if there are two standalone sensor, one for A, another for G. In such case, there are two separated sensor device drivers with two separated FIFOs, how can we achieve always muxing?
> > > 
> > > 
> > > I'm not sure I follow, if you have 2 separate `struct device` objects then you won't mux the 2 streams. We will only mux the two if a single `struct device` has 2+ separate FIFOs.
> > 
> > 
> > From sensor driver development perspective, this might make sense; but from application perspective, what we want to achieve is to use common code for A/G sensor, no matter it is combo sensor with single FIFO, or multiple FIFOs, or individual sensors with separated FIFOs.
> 
> I'm not sure how you'd achieve this if the sensors are in separate device structs. The thinking is that the drivers will provide **ALL** of their data, the decoder will allow you to demux as needed. If you want to have multiple clients, then the suggestion will be to use the subsystem which will own the demuxing and provide you with the ability to subscribe to a single sensor_info node (but that's beyond the scope for the kernel drivers).

Talked with Lixu, it looks OK to handle the combo vs individual sensor case in phy_3d_sensor_wrapper, if combo sensor always has muxing FIFO, and individual sensor always has separate FIFO.

File: include/zephyr/drivers/sensor.h [hunk 8]
```diff
@@ -567,12 +611,43 @@ struct sensor_read_config {
...
+ * int main(void) {
+ *   struct rtio_sqe *handle;
+ *   sensor_stream(&imu_stream, &rtio, NULL, &handle);
+ *   k_msleep(1000);
+ *   rtio_sqe_cancel(handle);
+ * }
+ * @endcode
+ */
+#define SENSOR_DT_STREAM_IODEV(name, dt_node, ...)                                                 \
+	static struct sensor_stream_trigger __trigger_array_##name[] = {__VA_ARGS__};              \
```
Comment (lixuzha) [inline include/zephyr/drivers/sensor.h:641]: Hi Yuval,

I met some problem when I integrated this PR. 
It would be better using _CONCAT instead of `##` when this macro is used by another macro.

Comment (yperess) [reply include/zephyr/drivers/sensor.h]: Done

Comment (lixuzha) [reply include/zephyr/drivers/sensor.h]: Thanks. Please also use `_CONCAT` in `SENSOR_DT_READ_IODEV`.

**Comment by yperess** [comment]
@MaureenHelm @KeHIntel @lixuzha can you re-review?

**Review by KeHIntel — DISMISSED** [review]

**Comment by lixuzha** [comment]
> @MaureenHelm @KeHIntel @lixuzha can you re-review?

Please also use `_CONCAT` in `SENSOR_DT_READ_IODEV`. Thanks.

**Review by teburd — APPROVED** [review]

**Review by lixuzha — APPROVED** [review]

**Review by KeHIntel — APPROVED** [review]

**Comment by yperess** [comment]
CI is blocked on https://github.com/zephyrproject-rtos/zephyr/pull/64881

**Comment by nashif** [comment]
> CI is blocked on #64881

can you rebase please?

**Comment by nashif** [comment]
> can you rebase please?

oh, it is passing already, why is this considered blocked

**Comment by kartben** [comment]
> > can you rebase please?
> 
> oh, it is passing already, why is this considered blocked

@MaureenHelm has requested changes - but it looks like they have been addressed.

**Review by MaureenHelm — APPROVED** [review]
