### PR TITLE
Bluetooth: controller: llcp: fixing tx buffer queue handling

### LINKED ISSUE #47104: Bluetooth: Controller: Errors in implementation of tx buffer queue mechanism
Errors were found in implementation of tx buffer allocation queue.

When configuring the system to use per connection pre allotted tx buffers, it was found that tracking number of allocated buffers common and per connection was flawed.
Also the updating of across connections/common allocated buffers in the event of disconnect was incorrect.

Fixed by #47097

### PR DESCRIPTION
**Pull request by erbr-ot**
Misc. fixups to get the tx buffer alloc mechanism to work as intended
On conn clean up re. disconnect, we need to update the common tx buffer alloc count.
The per conn alloc count needs to be updated even if we have no per conn pre allotted buffers, in order to be able to properly update the common count on disconnect
Unittest updated to properly confirm correct updates to tx buffer alloc counts, both common and per conn 

Fixes #47104

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 1]
```diff
@@ -51,7 +51,7 @@
 /* LLCP Allocations */
 #if defined(LLCP_TX_CTRL_BUF_QUEUE_ENABLE)
 sys_slist_t tx_buffer_wait_list;
-static uint8_t common_tx_buffer_alloc;
+uint8_t common_tx_buffer_alloc;
```
Comment (kruithofa) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c:54]: I prefer to leave this static, and create a helper function to access this variable when running unit tests, similar to the function 'ctx_buffers_free' in this file

**Review by kruithofa — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 1 above)
Comment (erbr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c]: Good idea - so done

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 2]
```diff
@@ -92,6 +92,22 @@ void llcp_proc_ctx_release(struct proc_ctx *ctx)
...
+void ull_cp_update_tx_buffer_queue(struct ll_conn *conn)
+{
+#if (CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM > 0)
+	if (conn->llcp.tx_buffer_alloc > CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM) {
+		common_tx_buffer_alloc -= (conn->llcp.tx_buffer_alloc -
+					   CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM);
+	}
+#else /* CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM > 0 */
+	common_tx_buffer_alloc -= conn->llcp.tx_buffer_alloc;
+#endif /* CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM > 0 */
```
Comment (kruithofa) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c:107]: I think we can get rid of the conditional compile as follows:
```suggestion
	if (conn->llcp.tx_buffer_alloc > CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM) {
		common_tx_buffer_alloc -= (conn->llcp.tx_buffer_alloc -
					   CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM);
```
when CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM > 0 this is the code in the '#if'-branch

when CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM = 0 the 'if' statement is always true and the code is equivalend to the '#else'-branch

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c [hunk 3]
```diff
@@ -506,15 +520,17 @@ void ull_llcp_init(struct ll_conn *conn)
...
-		common_tx_buffer_alloc--;
-	}
-	conn->llcp.tx_buffer_alloc--;
+		if (conn->llcp.tx_buffer_alloc > CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM) {
+			common_tx_buffer_alloc--;
+		}
 #else /* CONFIG_BT_CTLR_LLCP_PER_CONN_TX_CTRL_BUF_NUM > 0 */
-	ARG_UNUSED(conn);
-	common_tx_buffer_alloc--;
+		ARG_UNUSED(conn);
```
Comment (kruithofa) [inline subsys/bluetooth/controller/ll_sw/ull_llcp.c:529]: The argument conn is no longer unused, so the ARG_UNUSED should be removed here.
Also here we can remove the conditional compile similar to the function ull_cp_update_tx_buffer_queue

**Review by kruithofa — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_llcp.c (hunk 2 above)
Comment (erbr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_llcp.c:107]: Agree - thanks for noticing

**Review by kruithofa — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
