### PR TITLE
Bluetooth:host: Fix notify multiple issue

### LINKED ISSUE #40546: Bluetooh:host: GATT notify multiple feature not working properly
**Describe the bug**
GATT multiple notify feature is pushing notifications twice per handle. If there are 2 handles to notify, it creates 4 notifications in total. There is no proper workaround than ignoring unexpected notification.

**To Reproduce**
1. Prepare samples for peripheral and centrals by enabling CONFIG_BT_GATT_NOTIFY_MULTIPLE=y
2. Prepare a GATT service with characteristics to be notifiable.
2. Create a connection for 2 devices
3. Push notification using bt_gatt_notify_multiple() or bt_gatt_notify()

**Expected behavior**
Each call to notify APIs should create only one notification per handle

**Impact**
High

**Logs and console output**
GATT Server Logs: It looks it is sending both BT_ATT_OP_NOTIFY and BT_ATT_OP_NOTIFY_MULT after calling
bt_gatt_notify_multiple() once.

> [00:00:12.946,960] <dbg> bt_gatt.gatt_notify_mult: handle 0x0012 len 1
[00:00:12.947,021] <dbg> **bt_att.bt_att_chan_send: chan 0x2000f1d8 flags 1 code 0x23**
[00:00:12.947,021] <dbg> bt_att.chan_send: code 0x23
[00:00:12.947,204] <dbg> bt_gatt.gatt_notify: conn 0x20002010 handle 0x0012
[00:00:12.947,235] <dbg> **bt_att.bt_att_chan_send: chan 0x2000f1d8 flags 1 code 0x1b**
[00:00:12.947,235] <dbg> bt_att.chan_send: code 0x1b
[00:00:12.947,387] <dbg> bt_gatt.gatt_notify_mult: handle 0x0015 len 7
[00:00:12.947,479] <dbg> **bt_att.bt_att_chan_send: chan 0x2000f1d8 flags 1 code 0x23**
[00:00:12.947,479] <dbg> bt_att.chan_send: code 0x23
[00:00:13.010,681] <dbg> bt_att.att_rsp_sent: conn 0x20002010 chan 0x2000f1d8
[00:00:13.010,681] <dbg> bt_att.att_sent: conn 0x20002010 chan 0x2000f1e0
[00:00:13.010,681] <dbg> bt_att.bt_att_sent: chan 0x2000f1d8
[00:00:13.010,681] <dbg> bt_att.chan_rsp_sent: chan 0x2000f1d8
[00:00:13.010,711] <dbg> bt_att.chan_send: code 0x23
[00:00:13.010,742] <dbg> bt_att.att_sent: conn 0x20002010 chan 0x2000f1e0
[00:00:13.010,772] <dbg> bt_att.bt_att_sent: chan 0x2000f1d8
[00:00:13.087,738] <dbg> bt_gatt.gatt_notify: conn 0x20002010 handle 0x0015
[00:00:13.087,768] <dbg> **bt_att.bt_att_chan_send: chan 0x2000f1d8 flags 0 code 0x1b**
[00:00:13.087,768] <dbg> bt_att.chan_send: code 0x1b
[00:00:13.135,070] <dbg> bt_att.att_sent: conn 0x20002010 chan 0x2000f1e0
[00:00:13.135,101] <dbg> bt_att.bt_att_sent: chan 0x2000f1d8
[00:00:13.135,711] <dbg> bt_att.att_sent: conn 0x20002010 chan 0x2000f1e0
[00:00:13.135,711] <dbg> bt_att.bt_att_sent: chan 

**Environment:**
 - OS:  not matter
 - Toolchain: not matter
 - Commit: c68962e621fea73c2eba8c24f750202560f00791

**Additional context**
The problem happens due to doing regular notify activity after exclusive multiple notify actions. Please check [code](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/gatt.c#L1992) that it continues to process the regular (single) notify steps that causing double notification one with BT_ATT_OP_NOTIFY_MULT and another with BT_ATT_OP_NOTIFY.

### PR DESCRIPTION
**Pull request by ilhanates**
When multiple notify feature is enabled, notifications are pushed
twice. Host sends multiple notify with BT_ATT_OP_NOTIFY_MULT and
then continues to send regular notification with BT_ATT_OP_NOTIFY.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/40546

Signed-off-by: Ilhan Ates <ilhan.ates@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1990,7 +1990,7 @@ static int gatt_notify(struct bt_conn *conn, uint16_t handle,
 		int err;
 
 		err = gatt_notify_mult(conn, handle, params);
-		if (err && err != -ENOMEM) {
+		if (err != -ENOMEM) {
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:1993]: Why is ENOMEM treated specially and the code is allowed to continue until the end of this function?

Comment (ilhanates) [reply subsys/bluetooth/host/gatt.c:1993]: I thought it was done intentionally in case of buf allocation failed for multiple notify PDU which needs a bit more memory than regular notify. if fails with ENOMEM and success with regular notify below, it would differ:
- opcode would be 0x1b instead of 0x23
- notification pdu would not include "len" information

As side note, I see another issue that we always send one handle per BT_ATT_OP_NOTIFY_MULT which add supports for  putting different (Handle, Len, Value) in same PDU, so it make it more effective in such case that multiple characteristic needs to be notified in regular intervals. I will follow and discuss this further

Comment (carlescufi) [reply subsys/bluetooth/host/gatt.c:1993]: Let's just do this the simple way: `if(err) {`. I don't think it's worth retrying the allocation as they will allocate from the same pool.

Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c:1993]: @carlescufi actually even simpler: just `return gatt_notify_mult(conn, handle, params);` i.e. `err` goes away

**Review by jhedberg — APPROVED** [review]

**Review by Thalley — APPROVED** [review]
