### PR TITLE
soc: arm: stm32h7x mapping system memory region

### LINKED ISSUE #60449: STM32H7: Flash error flags are set spontaneously
**Describe the bug**
Summary: The RDSERR (secure error) and/or RDPERR (read protection error) flags of the flash status register are set from time to time.

We noticed this issue in our project because the bootloader API `mcuboot_swap_type()` would return something unexpected. Under the hood this function uses `flash_area_read()` which is provided by the STM32 flash driver. This one in turn checks the above mentioned error flags after execution which leads to a failure.

**To Reproduce**
From our project we extracted a sample to reproduce the issue. After quite some playing around we now have a minimal sample which does actually nothing except very short sleeps in the main thread. Before running the loop with sleeps the sample registers an interrupt to get notified if the mentioned flash error flags are set.

It can be found here: https://github.com/mjaun/zephyr/tree/flash_error/samples/flash_error

It reproduces the issue at least on the `nucleo_h743zi` board and also on the `nucleo_h743zi_minimal` board which is provided on the same branch and disable almost all drivers.

**Expected behavior**
1. Most importantly the flash errors should not occur
2. Additionally it might make sense to clear the flags before read/write operations

**Impact**
We have some workarounds in place, because the bootloader API might not work properly.

**Logs and console output**
Output from the mentioned sample:

```
*** Booting Zephyr OS build abae9b562b84 ***
ISR triggered: 5581 ms
FLASH_SR1: 0x01000000
FLASH_SR2: 0x00000000
ISR triggered: 50320 ms
FLASH_SR1: 0x01000000
FLASH_SR2: 0x00000000
ISR triggered: 95060 ms
FLASH_SR1: 0x01000000
FLASH_SR2: 0x00000000
ISR triggered: 139799 ms
FLASH_SR1: 0x01000000
FLASH_SR2: 0x00000000
ISR triggered: 184538 ms
FLASH_SR1: 0x01000000
FLASH_SR2: 0x00000000
```

The timings are always the same also across multiple devices. Note that the time between each occurrence is always almost the same. I observed the timings changing by modifying SYSCLK or also changing the application code. Some changes make the issue disappear (e.g. enabling CONFIG_LOG or CONFIG_DEBUG).

Currently I don't have a clue why these errors occur at all. Breaking in the ISR shows that the application is in idle thread.

**Environment (please complete the following information):**
- Zephyr v3.3.0 but also on main (8e40304)
- STM32H743ZI

### PR DESCRIPTION
**Pull request by FRASTM**
System memory declared by the MPU as 'Execute-Never' will inhibit the speculative fetch, preventing the RDSERR.

This is explained by the https://community.st.com/t5/stm32-mcu-products/spurious-rdperr-and-rdserr-when-all-protection-and-security/td-p/279852

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/60449

### CODE REVIEW

**Review by erwango — CHANGES_REQUESTED** [review]

File: soc/arm/st_stm32/stm32h7/mpu_regions.c [hunk 1]
```diff
@@ -13,6 +13,15 @@ static const struct arm_mpu_region mpu_regions[] = {
 					 REGION_FLASH_ATTR(REGION_FLASH_SIZE)),
 	MPU_REGION_ENTRY("SRAM", CONFIG_SRAM_BASE_ADDRESS,
 					 REGION_RAM_ATTR(REGION_SRAM_SIZE)),
+#ifdef CONFIG_SOC_SERIES_STM32H7X
+	/*
+	 * System memory declared as 'Execute-Never' inhibits the speculative fetch,
+	 * preventing the RDSERR
+	 */
+	MPU_REGION_ENTRY("SYSTEM", 0x1FF00000,
+					{ (NOT_EXEC | REGION_512K | NO_ACCESS_Msk) }),
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply soc/arm/st_stm32/stm32h7/mpu_regions.c:21]: I also tested with
```
	MPU_REGION_ENTRY("SYSTEM", 0x1FF00000,
					{ (STRONGLY_ORDERED_SHAREABLE | REGION_512K | FULL_ACCESS_Msk) }),
```
and it fixes the RDSERR as well

**Comment by FRASTM** [comment]
rebased on 85059866d5f4ea57ece549e84911682e3e33e9be
Change ATTRIBUTES to `(STRONGLY_ORDERED_SHAREABLE | REGION_512K | FULL_ACCESS_Msk)`

File: soc/arm/st_stm32/stm32h7/mpu_regions.c [hunk 2]
```diff
@@ -12,6 +12,15 @@ static const struct arm_mpu_region mpu_regions[] = {
...
 	MPU_REGION_ENTRY("SRAM", CONFIG_SRAM_BASE_ADDRESS,
 					 REGION_RAM_ATTR(REGION_SRAM_SIZE)),
+	/*
+	 * System memory declared as 'Execute-Never' inhibits the speculative fetch,
+	 * preventing the RDSERR
+	 */
+	MPU_REGION_ENTRY("SYSTEM", 0x1FF00000,
+					{ (STRONGLY_ORDERED_SHAREABLE |
+					REGION_512K |
+					FULL_ACCESS_Msk) }),
```
Comment (mjaun) [inline soc/arm/st_stm32/stm32h7/mpu_regions.c:22]: Wouldn't `MPU_RASR_XN_Msk | P_RW_U_NA_Msk`  instead of `FULL_ACCESS_Msk` be more appropriate? Then it would be the same as `REGION_RAM_ATTR` above. But generally `STRONGLY_ORDERED_SHAREABLE` solves all issues in our application.

Comment (FRASTM) [reply soc/arm/st_stm32/stm32h7/mpu_regions.c:22]: yes, this also removes the RDSERR (even if do not really catch the difference)

Comment (mjaun) [reply soc/arm/st_stm32/stm32h7/mpu_regions.c]: My understanding is that with `MPU_RASR_XN_Msk` we avoid to execute code from this region and with `P_RW_U_NA_Msk` we avoid that a user mode thread can access it. Both should not happen in my point of view and the configuration should therefore be a bit more secure.

**Review by mjaun — APPROVED** [review]
I can confirm that the proposed changes solves issue #60449 in the provided sample application as well as in our productive application.

**Comment by heinwessels** [comment]
Is there something blocking the PR from being merged?

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]
