### PR TITLE
Cortex-R Floating Point Support

### LINKED ISSUE #19979: Implement Cortex-R floating-point support
At the time of writing, ARM Cortex-R port does not support the use of hardware floating-point unit (VFP and NEON).

Considering common application scenarios for Cortex-R (real-time processing), it is imperative that hardware floating-point unit support is available for it; otherwise, practical usability of the Cortex-R port becomes questionable.

## Overview
An overview of the hardware floating-point unit for Cortex-R is as follows:

- Cortex-R4 and Cortex-R5
  - VFPv3-D16 may be optionally instantiated.
  - 16 double-precision registers are available (instead of 32 in full VFPv3).
  - Single-precision and double-precision operations are supported.
  - Half-precision operations are not supported.
  - Vector operations are not supported (software emulation is possible).
  - R5 may also optionally instantiate single-precision only VFPv3-D16.
- Cortex-R7 and Cortex-R8
  - VFPv3-D16-FP16 may be optionally instantiated.
  - Two variants of VFPv3-D16-FP16 are available: Optimised and Full.
  - Optimised variant implements only single-precision and half-precision operations.
  - Full variant implements single-precision, half-precision and double-precision operations.
  - Vector operations are not supported (software emulation is possible).
- Cortex-R52
  - VFPv3-FP16 or VFPv3-D16-FP16 must be instantiated.
  - Two variants are available: SP-only and Full Advanced SIMD.
  - SP-only variant
    - VFPv3-D16 (i.e. with 16 double-precision registers) is instantiated.
    - Half-precision and single-precision operations are supported.
  - Full Advanced SIMD variant
    - VFPv3 (i.e. with 32 double-precision registers) is instantiated.
    - NEON is instantiated.
    - Half-precision, single-precision, double-precision and vector operations are supported (with some optional subset specified by MVFR).

## Specifications

_ARM Cortex-R floating-point support feature shall:_

1. support Unshared FP registers mode and Shared FP registers mode.
    1. In both modes, the kernel shall initialise the FPU. In addition, all FP registers shall be initialised if DCLS (dual-redundant core lock-step) is configured.
    2. In Unshared FP registers mode, the kernel shall configure the FPU and leave it in operational state after booting.
    3. In Shared FP registers mode, all threads shall assume "FP disabled" state by default.

2. optionally support emulation of the VFP instructions that are unimplemented by hardware.

_ARM Cortex-R floating-point support feature, for Shared FP registers mode, shall:_

3. manage FP enable status at thread level, in conformance with the kernel FP interface.
    1. `K_FP_REGS` option shall be used to specify whether thread-wide floating-point support is enabled.
    2. `K_FP_REGS` option may be (re-)enabled only for the threads that were initially created with the same option.

4. disable FPU after a context switch and re-enable it upon exception.
    1. After a context switching occurs, FPU shall be disabled by setting FPEXC.EN=0.
    2. FPU shall be re-enabled after the first FP instruction that caused undefined instruction exception if and only if `K_FP_REGS` option is set for the thread.
    3. The first FP instruction that caused an undefined instruction exception shall be re-executed after setting FPEXC.EN=1.

5. store s0-s15 and FPSCR in exception stack frame and s16-s31 in thread context.
    1. s0-s15 and FPSCR shall be stored in the exception stack frame in order to allow the optional use of FP registers inside a nested interrupt handler.
    2. s16-s31 shall be preserved only for a thread context switch (and not for an exception entry).

6. implement lazy stacking of FP context.
    1. All context switching-capable exception handler routines shall save only the basic stack frame upon entry.
    2. s0-s15 shall be stored to the exception stack frame during a context switch if FPU is enabled; in which case, the thread being switched out shall be marked to indicate that FP context is saved.
    3. s0-s15 shall be restored if the thread being switched in is marked to contain an FP context.

7. preserve s16-s31 during context switch only when FPU is enabled.
    1. If FPU is enabled at the time of context switching, at least one FP instruction had been executed after the previous context switch and the FP context must preserved.
    2. FP context preservation of s16-s31 shall be implied by that of s0-s15.

## Note
- This feature will also be applicable to Cortex-A port when it is added in the future, as Cortex-R architecture is very similar to Cortex-A.
- Specification 3-ii should really apply to Cortex-M as well.

### PR DESCRIPTION
**Pull request by bbolen**
This PR adds support for the Cortex-R VFP unit.  It can also be used to enable floating point support for Cortex-A, though that is untested.  A couple of the basic ideas behind this PR:

1) Kconfig options are used to select the VFP options for the Cortex-R implemented in the SoC.  FPU/FPU_SHARING are still used to determine whether or not to pass the hard or soft float flags to the compiler.
2) The space for the floating point registers is always allocated on the process stack during context switches, but the registers are not saved unless necessary.

I pulled (and heavily modified) a couple of patches @stephanosio pointed me to a long time ago.  Let me know if you want me to change the author so that git blame won't implicate you if something goes wrong.

Closes #19979

### CODE REVIEW

**Review by peter-mitsis — DISMISSED** [review]

File: tests/kernel/fpu_sharing/generic/src/float_regs_arm_gcc.h [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /**
  * @file
- * @brief ARM Cortex-M4 GCC specific floating point register macros
+ * @brief ARM Cortex-M4/R4 GCC specific floating point register macros
```
Comment (stephanosio) [inline tests/kernel/fpu_sharing/generic/src/float_regs_arm_gcc.h:3]: This is no longer correct.

Let's just make it:
```
ARM GCC specific floating point register macros
```

File: tests/kernel/fpu_sharing/float_disable/src/k_float_disable.c [hunk 2]
```diff
@@ -148,7 +148,8 @@ void test_k_float_disable_syscall(void)
 #endif
 }
 
-#if defined(CONFIG_ARM) && defined(CONFIG_DYNAMIC_INTERRUPTS)
+#if defined(CONFIG_ARM) && defined(CONFIG_CPU_CORTEX_M) && \
+	defined(CONFIG_DYNAMIC_INTERRUPTS)
```
Comment (stephanosio) [inline tests/kernel/fpu_sharing/float_disable/src/k_float_disable.c:152]: > Cortex-R does not have an API for software to create a pending
interrupt like Cortex-M.  If we assume that the system is using a GIC
for the interrupt controller, it may be possible to create an ARM
specific API to generate an interrupt

It would be still useful to implement this testcase for `qemu_cortex_r5`, which uses the GICv1 as its interrupt controller.

Refer to the following for GIC-based interrupt generation:

https://github.com/zephyrproject-rtos/zephyr/blob/92f4db9fad1296a7e835f8dc167ce8aa8ea9657c/subsys/testsuite/include/interrupt_util.h#L73-L77

If you prefer to leave this to be done later, please add a `TODO: Implement GIC-based testcase.` here.

File: tests/kernel/fpu_sharing/generic/testcase.yaml [hunk 3]
```diff
@@ -21,21 +21,21 @@ tests:
     tags: fpu kernel
     timeout: 600
   kernel.fpu_sharing.generic.riscv32:
-    extra_args: PI_NUM_ITERATIONS=500
+    extra_args: PI_NUM_ITERATIONS=500 DISABLE_INT_TEST=1
```
Comment (stephanosio) [inline tests/kernel/fpu_sharing/generic/testcase.yaml:24]: What is the rationale behind disabling the timer testcase for these platforms?

File: arch/arm/core/aarch32/thread.c [hunk 4]
```diff
@@ -112,6 +112,13 @@ void arch_new_thread(struct k_thread *thread, k_thread_stack_t *stack,
 #endif /* CONFIG_COMPILER_ISA_THUMB2 */
 #endif /* CONFIG_CPU_CORTEX_M */
 
+#if defined(CONFIG_CPU_AARCH32_CORTEX_R) \
```
Comment (stephanosio) [inline arch/arm/core/aarch32/thread.c:115]: `!defined(CONFIG_CPU_CORTEX_M)` would make more sense in this case since this applies to both Cortex-A and Cortex-R.

**Review by stephanosio — CHANGES_REQUESTED** [review]
Looks ok in general.

Just a few comments.

File: tests/kernel/fpu_sharing/generic/src/float_regs_arm_gcc.h (hunk 1 above)
Comment (bbolen) [reply tests/kernel/fpu_sharing/generic/src/float_regs_arm_gcc.h]: done

File: arch/arm/core/aarch32/thread.c (hunk 4 above)
Comment (bbolen) [reply arch/arm/core/aarch32/thread.c]: done

File: tests/kernel/fpu_sharing/float_disable/src/k_float_disable.c (hunk 2 above)
Comment (bbolen) [reply tests/kernel/fpu_sharing/float_disable/src/k_float_disable.c]: Thanks.  I didn't realize that interface was there.  Updated the test.

File: tests/kernel/fpu_sharing/generic/testcase.yaml (hunk 3 above)
Comment (bbolen) [reply tests/kernel/fpu_sharing/generic/testcase.yaml:24]: Those particular platforms fail the test.  Unfortunately, I don't enough about these platforms to fix them myself.  I updated the commit message to note this.

File: arch/arm/Kconfig [hunk 5]
```diff
@@ -14,6 +14,203 @@ config CPU_CORTEX
 	help
 	  This option signifies the use of a CPU of the Cortex family.
 
+# Math coprocessor symbols; these should be selected by the CPU symbol to
```
Comment (povergoing) [inline arch/arm/Kconfig:17]: If it is better to move these VFP configs into a new Kconfig file? like Kconfig.vfp or something else

**Comment by povergoing** [comment]
Just wonder, these are only for v7r vfp, right?

**Comment by stephanosio** [comment]
> Just wonder, these are only for v7r vfp, right?

The original intention was to provide a set of "**unified** floating-point configurations" for all the ARM architecture variants -- that would be the "right thing to do" after all.

See the original PR: https://github.com/zephyrproject-rtos/zephyr/pull/23904#issue-589934192

**Comment by bbolen** [comment]
> > Just wonder, these are only for v7r vfp, right?
> 
> The original intention was to provide a set of "**unified** floating-point configurations" for all the ARM architecture variants -- that would be the "right thing to do" after all.
> 
> See the original PR: [#23904 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/23904#issue-589934192)

Yeah, I agree that changing the Cortex-M configuration would be the right thing to do.  I was scared to do that with this PR because it affects so many platforms and ould lead to a ton of regressions.  I can go back and look at adding it for this PR if you think it does belong here.

File: arch/arm/Kconfig (hunk 5 above)
Comment (bbolen) [reply arch/arm/Kconfig]: fixed

**Review by povergoing — DISMISSED** [review]

**Review by ibirnbaum — DISMISSED** [review]
LGTM, once this feature is integrated, I can have a go at extending this to the Cortex-A9. This is definitely a relevant feature for my work.

As a side note: this PR, like mine that initially integrated the Cortex-A(9) support or my pending attempt at USE_SWITCH support, understandably comes with a lot of CPU- and FPU-related #ifdefs. It's not quite as bad with the sources in arch/arm/core/aarch32/cortex_a_r, but the sources that at the time being are still shared among all ARMv7 CPUs, like isr_wrapper.S or swap_helper.S, from my point of view are by now borderline unreadable, as C-A/-R and C-M often differ significantly when it comes to the functionality provided by those sources. Anyone else in favor of one day splitting them up for C-A/-R and C-M in order to get significantly cleaner and more readable sources?

**Comment by povergoing** [comment]
> Anyone else in favor of one day splitting them up for C-A/-R and C-M in order to get significantly cleaner and more readable sources?

Good point. Actually, I am planning to split it. But I cannot finish it in a short time with limited bandwidth.

**Comment by microbuilder** [comment]
@ibirnbaum Splitting them definitely makes sense to me for maintainability.

**Comment by bbolen** [comment]
> @ibirnbaum Splitting them definitely makes sense to me for maintainability.

I'm definitely a +1 for splitting them.  I almost did it originally for the initial Cortex-R support, but being new to the project, I was trying to be as unobtrusive as possible.

**Comment by stephanosio** [comment]
> Anyone else in favor of one day splitting them up for C-A/-R and C-M in order to get significantly cleaner and more readable sources?

I was planning to do that while I was working on the Cortex-R stuff, but never got to do it. We should definitely do it at some point.

**Comment by stephanosio** [comment]
@povergoing FYI, this needs to be extended to `AARCH32_ARMV8_R` as well.

**Comment by microbuilder** [comment]
> I was planning to do that while I was working on the Cortex-R stuff, but never got to do it. We should definitely do it at some point.

Perhaps during the 3.2 cycle?

File: tests/kernel/fpu_sharing/generic/testcase.yaml (hunk 3 above)
Comment (stephanosio) [reply tests/kernel/fpu_sharing/generic/testcase.yaml:24]: Can you make 48b8439a0d4123d8abf83d08e170dbcc798e68cd a separate PR? This needs a more thorough review from the maintainers of all these platforms.

**Review by stephanosio — CHANGES_REQUESTED** [review]

**Comment by bbolen** [comment]
@stephanosio I created #45286 to review the new interleaved FPU test separately and fixed up the additional issues you pointed out.  Thanks.

**Review by stephanosio — APPROVED** [review]

**Review by microbuilder — APPROVED** [review]

**Comment by microbuilder** [comment]
Approved too soon, there are some compliance check issues, but should be easy to address.

**Comment by stephanosio** [comment]
> there are some compliance check issues

This warning can be ignored since typedef usage here is justified.

```
-:1022: WARNING:NEW_TYPEDEFS: do not add new typedefs
#1022: FILE: arch/arm/include/kernel_arch_data.h:48:
+typedef struct __fpu_sf _fpu_sf_t;
```

**Comment by povergoing** [comment]
> @julien-massot @povergoing FYI, this needs to be extended to `AARCH32_ARMV8_R` as well.

Yes, agreed. @SgrrZhf May take a look

**Review by povergoing — APPROVED** [review]
