### PR TITLE
drivers: gpio: stm32: Fix gpio_pin_get_config

### LINKED ISSUE #95113: gpio_pin_get_config for STM32 returns wrong flags value for input pins
### Describe the bug

For STM32WB55 we obtain wrong `flags` value from `gpio_pin_get_config` when it is called for input pins.
The returned value has both flags set: `GPIO_OUTPUT` and `GPIO_INPUT`.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Call `gpio_pin_get_config` for any pin configured (in DTS) as input.

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Linux
-  Tollchain: Zephyr 0.17.0
-  Zepyr 3.7

### Additional Context

Probably wrong code is:
```
	if (pin_cfg.out_state != 0) {
		flags |= GPIO_OUTPUT_HIGH;
	} else {
		flags |= GPIO_OUTPUT_LOW;
	}
```
and there should be instead:
```
	if (pin_cfg.out_state != 0) {
		flags |= GPIO_OUTPUT_INIT_HIGH;
	} else {
		flags |= GPIO_OUTPUT_INIT_LOW;
	}
```

### PR DESCRIPTION
**Pull request by kbidani**
This commit updates the function to only set output-related flags (GPIO_OUTPUT, GPIO_OUTPUT_INIT_HIGH, GPIO_OUTPUT_INIT_LOW) when the pin is actually configured as output. For input pins, only GPIO_INPUT and other relevant flags are set.

fixes: #95113

### CODE REVIEW

File: drivers/gpio/gpio_stm32.c [hunk 1]
```diff
@@ -126,6 +126,13 @@ static int gpio_stm32_pincfg_to_flags(struct gpio_stm32_pin pin_cfg,
 		if (pin_cfg.type == LL_GPIO_OUTPUT_OPENDRAIN) {
 			flags |= GPIO_OPEN_DRAIN;
 		}
+
+		if (pin_cfg.out_state != 0) {
+			flags |= GPIO_OUTPUT_INIT_HIGH;
+		} else {
+			flags |= GPIO_OUTPUT_INIT_LOW;
+		}
+
```
Comment (etienne-lms) [inline drivers/gpio/gpio_stm32.c]: Could remove this empty line.

**Review by etienne-lms — COMMENTED** [review]
Minor typo in commit message:
```patch
 This commit updates the function to only set output-related flags
-(GPIO_OUTPUT, GPIO_OUTPUT_INIT_HIGH, GPIO_OUTPUT_INIT_LOW) when the pin
+(GPIO_OUTPUT_INIT_HIGH, GPIO_OUTPUT_INIT_LOW) when the pin
 is actually configured as output. For input pins, only GPIO_INPUT and
 other relevant flags are set.
```
Otheerwise, LGTM.

File: drivers/gpio/gpio_stm32.c (hunk 1 above)
Comment (kbidani) [reply drivers/gpio/gpio_stm32.c]: Done. Thnx :)

**Review by etienne-lms — DISMISSED** [review]

File: drivers/gpio/gpio_stm32.c [hunk 2]
```diff
@@ -126,6 +126,12 @@ static int gpio_stm32_pincfg_to_flags(struct gpio_stm32_pin pin_cfg,
 		if (pin_cfg.type == LL_GPIO_OUTPUT_OPENDRAIN) {
 			flags |= GPIO_OPEN_DRAIN;
 		}
+
+		if (pin_cfg.out_state != 0) {
+			flags |= GPIO_OUTPUT_INIT_HIGH;
```
Comment (FRASTM) [inline drivers/gpio/gpio_stm32.c]: what about a more _positive_ test 
```
if (pin_cfg.out_state == 0) {
...
```

**Review by FRASTM — DISMISSED** [review]

File: drivers/gpio/gpio_stm32.c (hunk 2 above)
Comment (kbidani) [reply drivers/gpio/gpio_stm32.c]: Done.

**Review by etienne-lms — APPROVED** [review]

**Review by erwango — APPROVED** [review]
