### PR TITLE
drivers: ethernet: stm32: Fix the init call order

### LINKED ISSUE #96197: gPTP sample does not boot with NUCLEO-H563ZI
### Describe the bug

Hello,

currently I am testing gPTP with `samples/net/gptp` with the STM32 NUCLEO-H563ZI Board.  
With Zephyr 4.1 the board does boot up and prints out on the console, with Zephyr 4.2 it does not boot up.

### Regression

- [x] This is a regression.

### Steps to reproduce

Steps to reproduce with `4.1.0`:

1. `git checkout v4.1.0`
2. `west update`
3. `west packages pip --install`
4. `west build -p always -b nucleo_h563zi/stm32h563xx samples/net/gptp`
5. `west flash`

```
*** Booting Zephyr OS build v4.1.0 ***
[00:00:00.052,000] <inf> net_config: Initializing network
[00:00:00.052,000] <inf> net_config: Waiting interface 1 (0x20001328) to be up...
[00:00:00.054,000] <wrn> net_if: iface 0x20001328 is down
[00:00:01.056,000] <wrn> net_gptp: Reset Pdelay requests
[00:00:01.058,000] <wrn> net_if: iface 0x20001328 is down
[00:00:01.672,000] <inf> net_config: Interface 1 (0x20001328) coming up
[00:00:01.672,000] <inf> net_config: IPv4 address: 192.0.2.1
[00:00:01.773,000] <inf> net_config: IPv6 address: 2001:db8::1
[00:00:02.059,000] <wrn> net_gptp: Reset Pdelay requests
[00:00:03.064,000] <wrn> net_gptp: Reset Pdelay requests
[00:00:03.653,000] <inf> phy_mii: PHY (0) Link speed 100 Mb, full duplex
[00:00:04.067,000] <wrn> net_gptp: Reset Pdelay requests
```

Steps to reproduce with `4.2.0`:

1. `git checkout v4.2.0`
2. `west update`
3. `west packages pip --install`
4. `west build -p always -b nucleo_h563zi/stm32h563xx samples/net/gptp`
5. `west flash`

Does not even show the Boot-Message

### Relevant log output

Here the build log with 4.1:
```shell
west build -p always -b nucleo_h563zi/stm32h563xx external/zephyr/samples/net/gptp 
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/viephi29/repos/zprojects/external/zephyr/samples/net/gptp
-- CMake version: 3.31.6
-- Found Python3: /home/viephi29/repos/zprojects/.venv/bin/python3 (found suitable version "3.13.5", minimum required is "3.10") found components: Interpreter
-- Cache files will be written to: /home/viephi29/.cache/zephyr
-- Zephyr version: 4.1.0 (/home/viephi29/repos/zprojects/external/zephyr)
-- Found west (found suitable version "1.4.0", minimum required is "0.14.0")
-- Board: nucleo_h563zi, qualifiers: stm32h563xx
-- Found host-tools: zephyr 0.17.0 (/home/viephi29/.zephyr_ide/toolchains/zephyr-sdk-0.17.0)
-- Found toolchain: zephyr 0.17.0 (/home/viephi29/.zephyr_ide/toolchains/zephyr-sdk-0.17.0)
-- Found Dtc: /usr/bin/dtc (found suitable version "1.7.2", minimum required is "1.4.6")
-- Found BOARD.dts: /home/viephi29/repos/zprojects/external/zephyr/boards/st/nucleo_h563zi/nucleo_h563zi.dts
-- Generated zephyr.dts: /home/viephi29/repos/zprojects/build/zephyr/zephyr.dts
-- Generated pickled edt: /home/viephi29/repos/zprojects/build/zephyr/edt.pickle
-- Generated devicetree_generated.h: /home/viephi29/repos/zprojects/build/zephyr/include/generated/zephyr/devicetree_generated.h
-- Including generated dts.cmake file: /home/viephi29/repos/zprojects/build/zephyr/dts.cmake
Parsing /home/viephi29/repos/zprojects/external/zephyr/samples/net/gptp/Kconfig
Loaded configuration '/home/viephi29/repos/zprojects/external/zephyr/boards/st/nucleo_h563zi/nucleo_h563zi_defconfig'
Merged configuration '/home/viephi29/repos/zprojects/external/zephyr/samples/net/gptp/prj.conf'
Configuration saved to '/home/viephi29/repos/zprojects/build/zephyr/.config'
Kconfig header saved to '/home/viephi29/repos/zprojects/build/zephyr/include/generated/zephyr/autoconf.h'
-- Found GnuLd: /home/viephi29/.zephyr_ide/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/arm-zephyr-eabi/bin/ld.bfd (found version "2.38")
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/viephi29/.zephyr_ide/toolchains/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Using ccache: /usr/bin/ccache
-- Configuring done (2.6s)
-- Generating done (0.1s)
-- Build files have been written to: /home/viephi29/repos/zprojects/build
-- west build: building application
[1/274] Preparing syscall dependency handling

[2/274] Generating include/generated/zephyr/version.h
-- Zephyr version: 4.1.0 (/home/viephi29/repos/zprojects/external/zephyr), build: v4.1.0
[274/274] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      223296 B         2 MB     10.65%
             RAM:       80352 B       256 KB     30.65%
           SRAM1:          0 GB       256 KB      0.00%
           SRAM2:          0 GB        64 KB      0.00%
           SRAM3:          0 GB       320 KB      0.00%
        IDT_LIST:          0 GB        32 KB      0.00%
Generating files from /home/viephi29/repos/zprojects/build/zephyr/zephyr.elf for board: nucleo_h563zi
``` 

Here the build log with 4.2:
```shell
west build -p always -b nucleo_h563zi/stm32h563xx samples/net/gptp
-- west build: making build dir /home/viephi29/zephyrproject/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/viephi29/zephyrproject/zephyr/samples/net/gptp
-- CMake version: 3.31.6
-- Found Python3: /home/viephi29/zephyrproject/.venv/bin/python3 (found suitable version "3.13.5", minimum required is "3.10") found components: Interpreter
-- Cache files will be written to: /home/viephi29/.cache/zephyr
-- Zephyr version: 4.2.0 (/home/viephi29/zephyrproject/zephyr)
-- Found west (found suitable version "1.3.0", minimum required is "0.14.0")
-- Board: nucleo_h563zi, qualifiers: stm32h563xx
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.17.4 (/home/viephi29/zephyr-sdk-0.17.4)
-- Found toolchain: zephyr 0.17.4 (/home/viephi29/zephyr-sdk-0.17.4)
-- Found Dtc: /home/viephi29/zephyr-sdk-0.17.4/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.7.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/viephi29/zephyrproject/zephyr/boards/st/nucleo_h563zi/nucleo_h563zi.dts
-- Generated zephyr.dts: /home/viephi29/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated pickled edt: /home/viephi29/zephyrproject/zephyr/build/zephyr/edt.pickle
-- Generated devicetree_generated.h: /home/viephi29/zephyrproject/zephyr/build/zephyr/include/generated/zephyr/devicetree_generated.h
Parsing /home/viephi29/zephyrproject/zephyr/samples/net/gptp/Kconfig
Loaded configuration '/home/viephi29/zephyrproject/zephyr/boards/st/nucleo_h563zi/nucleo_h563zi_defconfig'
Merged configuration '/home/viephi29/zephyrproject/zephyr/samples/net/gptp/prj.conf'
Configuration saved to '/home/viephi29/zephyrproject/zephyr/build/zephyr/.config'
Kconfig header saved to '/home/viephi29/zephyrproject/zephyr/build/zephyr/include/generated/zephyr/autoconf.h'
-- Found GnuLd: /home/viephi29/zephyr-sdk-0.17.4/arm-zephyr-eabi/arm-zephyr-eabi/bin/ld.bfd (found version "2.38")
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/viephi29/zephyr-sdk-0.17.4/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Using ccache: /usr/bin/ccache
-- Found gen_kobject_list: /home/viephi29/zephyrproject/zephyr/scripts/build/gen_kobject_list.py
-- Configuring done (2.6s)
-- Generating done (0.1s)
-- Build files have been written to: /home/viephi29/zephyrproject/zephyr/build
-- west build: building application
[1/278] Preparing syscall dependency handling

[2/278] Generating include/generated/zephyr/version.h
-- Zephyr version: 4.2.0 (/home/viephi29/zephyrproject/zephyr), build: v4.2.0
[278/278] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      228876 B         2 MB     10.91%
             RAM:       80592 B       256 KB     30.74%
           SRAM1:          0 GB       256 KB      0.00%
           SRAM2:          0 GB        64 KB      0.00%
           SRAM3:          0 GB       320 KB      0.00%
        IDT_LIST:          0 GB        32 KB      0.00%
Generating files from /home/viephi29/zephyrproject/zephyr/build/zephyr/zephyr.elf for board: nucleo_h563zi
```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

- OS: Debian 13
- Toolchain: zephyr sdk 0.17.0 and 0.17.4
- Version 4.1.0 and 4.2.0
- STM32 NUCLEO-H563ZI Board

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by juickar**
Fix the init call order for V2 API to be able to configure PTP as PTP initialization happens before iface initialization.

Fixes #96197 

This solution is the equivalent to the one used in the main branch at this commit: [ca6e25a](https://github.com/zephyrproject-rtos/zephyr/commit/ca6e25a03fa), but it can't be directly applied in the v4.2 branch, as the Ethernet driver is not split between v1 and v2 yet in this version.

### CODE REVIEW

File: drivers/ethernet/eth_stm32_hal.c [hunk 1]
```diff
@@ -930,7 +992,13 @@ static int eth_initialize(const struct device *dev)
 	HAL_ETH_DMARxDescListInit(heth, dma_rx_desc_tab,
 		&dma_rx_buffer[0][0], ETH_RXBUFNB);
 
-#endif /* !CONFIG_ETH_STM32_HAL_API_V1 */
+#elif defined(CONFIG_ETH_STM32_HAL_API_V2)
+	/* This function requires the Ethernet interface to be
+	 * properly initialized. In auto-negotiation mode, it reads the speed
+	 * and duplex settings to configure the driver accordingly.
+	 */
```
Comment (maass-hamburg) [inline drivers/ethernet/eth_stm32_hal.c]: remove this comment, as it is wrong, since we switched to using the phy api completly

File: drivers/ethernet/eth_stm32_hal.c [hunk 2]
```diff
@@ -930,7 +992,13 @@ static int eth_initialize(const struct device *dev)
...
+	eth_init_api_v2(dev);
```
Comment (etienne-lms) [inline drivers/ethernet/eth_stm32_hal.c]: Could you test the return value?
By the way, would it make sense to move thee API_V1 also into a `eth_init_api_v1()` helper function?

**Review by etienne-lms — COMMENTED** [review]
Note there's an extra space char in your Signed-off-by tag (between your name and e-mail address) Compliance Checks CI test complains about.

File: drivers/ethernet/eth_stm32_hal.c (hunk 1 above)
Comment (juickar) [reply drivers/ethernet/eth_stm32_hal.c]: I removed the comment

File: drivers/ethernet/eth_stm32_hal.c (hunk 2 above)
Comment (juickar) [reply drivers/ethernet/eth_stm32_hal.c]: I added a check and moved the v1 init in its own function

File: drivers/ethernet/eth_stm32_hal.c [hunk 3]
```diff
@@ -930,7 +992,13 @@ static int eth_initialize(const struct device *dev)
 	HAL_ETH_DMARxDescListInit(heth, dma_rx_desc_tab,
 		&dma_rx_buffer[0][0], ETH_RXBUFNB);
 
-#endif /* !CONFIG_ETH_STM32_HAL_API_V1 */
+#elif defined(CONFIG_ETH_STM32_HAL_API_V2)
+	int ret = eth_init_api_v2(dev);
```
Comment (etienne-lms) [inline drivers/ethernet/eth_stm32_hal.c]: `int ret` is already defined at `eth_initialize()` entry.
```suggestion
	ret = eth_init_api_v2(dev);
```

Despite it's fixed in the next commit of this series, it should still be fixed in this commit to ensure build does not fail.

File: drivers/ethernet/eth_stm32_hal.c [hunk 4]
```diff
@@ -958,47 +996,17 @@ static int eth_initialize(const struct device *dev)
...
-	HAL_ETH_DMARxDescListInit(heth, dma_rx_desc_tab,
-		&dma_rx_buffer[0][0], ETH_RXBUFNB);
+	ret = 0;
 
+#if defined(CONFIG_ETH_STM32_HAL_API_V1)
+	ret = eth_init_api_v1(dev);
 #elif defined(CONFIG_ETH_STM32_HAL_API_V2)
-	int ret = eth_init_api_v2(dev);
+	ret = eth_init_api_v2(dev);
+#endif /* CONFIG_ETH_STM32_HAL_API_V1 */
```
Comment (etienne-lms) [inline drivers/ethernet/eth_stm32_hal.c:1007]: I would rather be in favor of:
```patch
-	ret = 0;
-
 #if defined(CONFIG_ETH_STM32_HAL_API_V1)
 	ret = eth_init_api_v1(dev);
 #elif defined(CONFIG_ETH_STM32_HAL_API_V2)
 	ret = eth_init_api_v2(dev);
+#else
+	ret = 0;
 #endif /* CONFIG_ETH_STM32_HAL_API_V1 */
 
 	if (ret != 0) {
 		return ret;
 	}
```
but it's rather a matter of taste.

File: drivers/ethernet/eth_stm32_hal.c [hunk 5]
```diff
@@ -851,7 +851,45 @@ static void RISAF_Config(void)
...
+									     : ETH_MODE_HALFDUPLEX;
+		heth->Init.Speed =
+			PHY_LINK_IS_SPEED_100M(state.speed) ? ETH_SPEED_100M : ETH_SPEED_10M;
+	}
+
+	hal_ret = HAL_ETH_Init(heth);
+	if (hal_ret == HAL_TIMEOUT) {
+		/* HAL Init time out. This could be linked to */
+		/* a recoverable error. Log the issue and continue */
+		/* driver initialisation */
```
Comment (etienne-lms) [inline drivers/ethernet/eth_stm32_hal.c]: By the way, I think it would be nice to fix the inline comment style:
```c
		/* HAL Init time out. This could be linked to
		 * a recoverable error. Log the issue and continue
		 * driver initialization.
		 */

Comment (etienne-lms) [reply drivers/ethernet/eth_stm32_hal.c]: (feel free to discard my comment if you prefer)

File: drivers/ethernet/eth_stm32_hal.c (hunk 3 above)
Comment (juickar) [reply drivers/ethernet/eth_stm32_hal.c]: fixed it :+1:

File: drivers/ethernet/eth_stm32_hal.c (hunk 5 above)
Comment (juickar) [reply drivers/ethernet/eth_stm32_hal.c]: I also fixed it in the v2 function

**Review by etienne-lms — APPROVED** [review]

File: drivers/ethernet/eth_stm32_hal.c [hunk 6]
```diff
@@ -897,41 +999,17 @@ static int eth_initialize(const struct device *dev)
...
-		phy_get_link_state(eth_stm32_phy_dev, &state);
-
-		heth->Init.DuplexMode = PHY_LINK_IS_FULL_DUPLEX(state.speed) ? ETH_MODE_FULLDUPLEX
-									     : ETH_MODE_HALFDUPLEX;
-		heth->Init.Speed =
-			PHY_LINK_IS_SPEED_100M(state.speed) ? ETH_SPEED_100M : ETH_SPEED_10M;
-	}
+	ret = eth_init_api_v1(dev);
+#elif defined(CONFIG_ETH_STM32_HAL_API_V2)
+	ret = eth_init_api_v2(dev);
```
Comment (maass-hamburg) [inline drivers/ethernet/eth_stm32_hal.c:1004]: could share a common function name

**Review by maass-hamburg — APPROVED** [review]
Little nit, but fine for a fix, that will only be applied to a past version and not to main.

**Comment by erwango** [comment]
@dkalowsk, @danieldegrasse FYI, this one is a bit specific as no backport possible.

**Review by erwango — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]
