### PR TITLE
Bluetooth: ISO: Remove TS size from SDU len check

### LINKED ISSUE #49629: Bluetooth: ISO Broadcast sample fails to send data on nRF5340
When the ISO broadcast/receive samples are run with the Packetcraft controller on the nRF5340, the samples are able to establish BIG sync but does not attempt to actually broadcast/receive any ISO-data.

Boards:
- arm/nrf5340dk_nrf5340
- arm/nrf5340dk_nrf5340

Samples:
- bluetooth/iso_broadcast
- bluetooth/iso_receive

Controller:
- https://github.com/nrfconnect/sdk-nrf/blob/main/applications/nrf5340_audio/bin/ble5-ctr-rpmsg_3301.hex

**To Reproduce**

Append to prj.conf of both samples:
```
CONFIG_BT_HCI_VS_EXT=n
CONFIG_BT_BUF_ACL_RX_SIZE=256
CONFIG_BT_BUF_ACL_TX_SIZE=256
CONFIG_BT_BUF_CMD_TX_SIZE=255
CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE=255
CONFIG_UART_0_NRF_TX_BUFFER_SIZE=1024
CONFIG_BT_ISO_TX_BUF_COUNT=255
CONFIG_BT_ISO_TX_MTU=496
CONFIG_BT_ISO_RX_MTU=496
```

1. west init zephyr
2. west update
3. west build -p auto -b nrf5340dk_nrf5340_cpuapp -d ./iso_broadcast_build -s ./zephyr/samples/bluetooth/iso_broadcast
4. west build -p auto -b nrf5340dk_nrf5340_cpuapp -d ./iso_receive_build -s ./zephyr/samples/bluetooth/iso_receive
5. Flash controller to NET-core and app.hex of sample to APP-core, broadcast on one devkit, receive on other.
6. Reset both devkits and observe debug logs from UART

**Expected behaviour**
Both samples establishing BIG sync, and broadcaster starts sending ISO packets to the received every 10ms. Every 60 seconds, the broadcast sample is expected to end the BIG sync, and re-establish it before continuing sending more data.

**Observed behaviour**
Both samples establishing sync, but broadcast sample fails with error -122 when trying to send the first packet with ISO data.

**Impact**
The sample is broken, and does not exercise the broadcast feature it is expected to demonstrate.

**Logs and console output**
Broadcast sample
```
*** Booting Zephyr OS build zephyr-v3.1.0-4326-g8195ea7ea0bf  ***
Starting ISO Broadcast Demo
Waiting for BIG complete...ISO Channel 0x20000120 connected
done.
Unable to broadcast data: -122[00:00:00.455,505] <inf> bt_hci_core: Identity: EA:28:08:2D:F7:24 (random)
[00:00:00.455,535] <inf> bt_hci_core: HCI: version 5.2 (0x0b) revision 0x0ce5, manufacturer 0x07e8
[00:00:00.455,566] <inf> bt_hci_core: LMP: version 5.2 (0x0b) subver 0x0ce5
```
Receive sample
```
*** Booting Zephyr OS build zephyr-v3.1.0-4326-g8195ea7ea0bf  ***
Starting Synchronized Receiver Demo
Get reference to LED device...done.
Configure GPIO pin...done.
Scan callbacks register...success.
Periodic Advertising callbacks register...Success.
Start scanning...success.
Start blinking LED...
Waiting for periodic advertising...
[DEVICE]: 3E:C2:53:A6:D6:7A (random), AD evt type 5, Tx Pwr: 127, RSSI -23 Test ISO Broadcaster C:0 S:0 D:0 SR:0 E:1 Prim: LE 1M, Secn: LE 2M, Interval: 0x0000 (0 ms), SID: 0
[DEVICE]: 3E:C2:53:A6:D6:7A (random), AD evt type 5, Tx Pwr: 127, RSSI -22 Test ISO Broadcaster C:0 S:0 D:0 SR:0 E:1 Prim: LE 1M, Secn: LE 2M, Interval: 0x03c0 (1200 ms), SID: 0
Found periodic advertising.
Stop scanning...success.
Creating Periodic Advertising Sync...success.
Waiting for periodic sync...
[DEVICE]: 3E:C2:53:A6:D6:7A (random), AD evt type 5, Tx Pwr: 127, RSSI -23 Test ISO Broadcaster C:0 S:0 D:0 SR:0 E:1 Prim: LE 1M, Secn: LE 2M, Interval: 0x03c0 (1200 ms), SID: 0
[DEVICE]: 3E:C2:53:A6:D6:7A (random), AD evt type 5, Tx Pwr: 127, RSSI -23 Test ISO Broadcaster C:0 S:0 D:0 SR:0 E:1 Prim: LE 1M, Secn: LE 2M, Interval: 0x03c0 (1200 ms), SID: 0
[00:00:00.456,207] <inf> bt_hci_core: Identity: D5:87:4E:A5:7D:6B (random)
[00:00:00.456,237] <inf> bt_hci_core: HCI: version 5.2 (0x0b) revision 0x0ce5, manufacturer 0x07e8
[00:00:00.456,268] <inf> bt_hci_core: LMP: version 5.2 (0x0b) subver 0x0ce5
[DEVICE]: 3E:C2:53:A6:D6:7A (random), AD evt type 5, Tx Pwr: 127, RSSI -23 Test ISO Broadcaster C:0 S:0 D:0 SR:0 E:1 Prim: LE 1M, Secn: LE 2M, Interval: 0x03c0 (1200 ms), SID: 0
[DEVICE]: 3E:C2:53:A6:D6:7A (random), AD evt type 5, Tx Pwr: 127, RSSI -23 Test ISO Broadcaster C:0 S:0 D:0 SR:0 E:1 Prim: LE 1M, Secn: LE 2M, Interval: 0x03c0 (1200 ms), SID: 0
PER_ADV_SYNC[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random) synced, Interval 0x03c0 (1200 ms), PHY LE 2M
Periodic sync established.
Waiting for BIG info...
PER_ADV_SYNC[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), tx_power 0, RSSI -23, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), sid 0x00, num_bis 1, nse 3, interval 0x0008 (10 ms), bn 1, pto 0, irc 3, max_pdu 4, sdu_interval 10000 us, max_sdu 4, phy LE 2M, without framing, not encrypted
Periodic sync established.
Create BIG Sync...
success.
Waiting for BIG sync...
ISO Channel 0x20000120 connected
PER_ADV_SYNC[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), tx_power 0, RSSI -23, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), sid 0x00, num_bis 1, nse 3, interval 0x0008 (10 ms), bn 1, pto 0, irc 3, max_pdu 4, sdu_interval 10000 us, max_sdu 4, phy LE 2M, without framing, not encrypted
BIG sync established.
Stop blinking LED.
Waiting for BIG sync lost...
PER_ADV_SYNC[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), tx_power 0, RSSI -23, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), sid 0x00, num_bis 1, nse 3, interval 0x0008 (10 ms), bn 1, pto 0, irc 3, max_pdu 4, sdu_interval 10000 us, max_sdu 4, phy LE 2M, without framing, not encrypted
PER_ADV_SYNC[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), tx_power 0, RSSI -23, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), sid 0x00, num_bis 1, nse 3, interval 0x0008 (10 ms), bn 1, pto 0, irc 3, max_pdu 4, sdu_interval 10000 us, max_sdu 4, phy LE 2M, without framing, not encrypted
PER_ADV_SYNC[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), tx_power 0, RSSI -23, CTE 0, data length 0, data: 
BIG INFO[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), sid 0x00, num_bis 1, nse 3, interval 0x0008 (10 ms), bn 1, pto 0, irc 3, max_pdu 4, sdu_interval 10000 us, max_sdu 4, phy LE 2M, without framing, not encrypted
PER_ADV_SYNC[0]: [DEVICE]: 3E:C2:53:A6:D6:7A (random), tx_power 0, RSSI -23, CTE 0, data length 0, data: 
...
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: GNU 10.3.0
 - Zephyr version: 3.1.99 (main @ 2022-08-29)

### PR DESCRIPTION
**Pull request by Thalley**
The timestamp is not part of the SDU, and should
thus not be used to get the maximum SDU size.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

fixes https://github.com/zephyrproject-rtos/zephyr/issues/49629

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]

**Comment by Thalley** [comment]
Found a similar issue in multiple samples, as well as one of the babblesim tests. 

Seeing how we need to deal with the ISO header, I can't help but to wonder if we can improve this somehow. 

Basically with the current API we have
1) Reserve 4-9 bytes based on different factors 
2) Add SDU size - 4/8 octets based on the timestamp parameter
3) Send data 

I wonder if we can do this better, without having to resort to copying data?

File: samples/bluetooth/iso_broadcast/src/main.c [hunk 1]
```diff
@@ -44,7 +44,7 @@ static struct bt_iso_chan_ops iso_ops = {
 };
 
 static struct bt_iso_chan_io_qos iso_tx_qos = {
-	.sdu = sizeof(uint32_t), /* bytes */
+	.sdu = BT_HCI_ISO_DATA_HDR_SIZE + (sizeof(uint32_t)), /* bytes */
```
Comment (cvinayak) [inline samples/bluetooth/iso_broadcast/src/main.c:47]: This does not seems correct in terms of the definition of `sdu`:
`/** Channel SDU. Maximum value is BT_ISO_MAX_SDU */`

and

https://github.com/zephyrproject-rtos/zephyr/blob/b8cdf9d0a6372ce72727ca3dc4fcc39fc9ec66d6/include/zephyr/bluetooth/iso.h#L66-L67

Why cant the required change be done internally instead of each samples?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: samples/bluetooth/iso_broadcast/src/main.c (hunk 1 above)
Comment (Thalley) [reply samples/bluetooth/iso_broadcast/src/main.c:47]: The ISO SDU contains the data header, so the 4/8 octets of data header is counted towards the SDU size. 

So the maximum SDU size is indeed 0xFFF, but the maximum data length in the SDU is 0xFFF - 4 or 8, depending on whether the timestamp is added. 

I would really like this to be handled internally, but I am unsure how to do that since the buffer where the SDU (including the timestamp) is allocated by the application.

File: samples/bluetooth/broadcast_audio_source/src/main.c [hunk 2]
```diff
@@ -63,7 +63,8 @@ static void stream_sent_cb(struct bt_audio_stream *stream)
 	}
 
 	net_buf_reserve(buf, BT_ISO_CHAN_SEND_RESERVE);
-	net_buf_add_mem(buf, mock_data, preset_16_2_1.qos.sdu);
+	net_buf_add_mem(buf, mock_data,
+			preset_16_2_1.qos.sdu - BT_HCI_ISO_DATA_HDR_SIZE);
```
Comment (Casper-Bonde-Bose) [inline samples/bluetooth/broadcast_audio_source/src/main.c:67]: I think this is wrong. (Of cause this app is just sending mock data, but it sends the wrong message to people using the sample to build an application.
QoS sdu size is the negotiated over-the-air max SDU size - which do not carry any HCI headers - hence there should be no need to reserve space for the header in the payload area of buf. That would mean you would need to setup the ISO link to be able to carry 128 octets to fit a 120 byte audio frame - hence wasting 8 bytes of air-time for each frame.
The buffers in the host needs to be allocated large enough to hold both the ISO max SDU as well as the HCI header, but the data path should not care about the HCI header when building the SDU.

**Review by Casper-Bonde-Bose — CHANGES_REQUESTED** [review]

File: samples/bluetooth/broadcast_audio_source/src/main.c (hunk 2 above)
Comment (Thalley) [reply samples/bluetooth/broadcast_audio_source/src/main.c:67]: Will update this PR to properly fix the issue. The PSN and TS should not be considered part of the SDU

**Review by Casper-Bonde-Bose — DISMISSED** [review]
LGTM

**Comment by stephanosio** [comment]
Rebased to fix CI failure

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/iso.c [hunk 3]
```diff
@@ -723,24 +723,6 @@ static uint16_t iso_chan_max_data_len(const struct bt_iso_chan *chan,
 	/* Update the max_data_len to take the max_controller_data_len into account */
 	max_data_len = MIN(max_data_len, max_controller_data_len);
 
-	/* Since this returns the maximum ISO data length size, we have to take
-	 * the header size into account, as that also needs to be inserted into
-	 * the SDU
-	 */
-	if (ts == BT_ISO_TIMESTAMP_NONE) {
```
Comment (Frodevan) [inline subsys/bluetooth/host/iso.c:730]: I seem to remember this was added to make sure a buffer was not overrun in an border-case EBQ test. Should the check be removed for both cases here, or just the case where ts != BT_ISO_TIMESTAMP_NONE?

Comment (Thalley) [reply subsys/bluetooth/host/iso.c:730]: The timestamp is not related to the SDU size (timestamp is part of the header, and not the SDU), so should just never have been added. 

If there's an issue with an EBQ tests without this, then the issue lies elsewhere

**Comment by Thalley** [comment]
Updated the PR to also revert the (now wrong) documentation for the send functions

**Review by MariuszSkamra — APPROVED** [review]

**Review by cvinayak — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
Merging since this was previously approved by the assignee.
