### PR TITLE
net: getaddrinfo: Query both IPv4 and IPv6 if hints is missing

### LINKED ISSUE #16453: sockets: getaddrinfo: AF_UNSPEC handling was recently broken
From https://github.com/zephyrproject-rtos/zephyr/pull/15210#issuecomment-496562532 :

> Hello @jukkar, you broke getaddrinfo() behavior with this patch (1897896e9739f93654430b172b7048134177a0a9). If it's passed AF_UNSPEC, it should resolve both IPv4 and IPv6 addresses. That's why the original code has 2 calls to dns_get_addr_info(). You replaced them with 1 call, so it can't work correctly.

### PR DESCRIPTION
**Pull request by jukkar**
We must query both IPv4 and IPv6 addresses if the hints parameter
is NULL i.e., user does not supply hints.

Fixes #16453

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by pfalcon** [comment]
> net: getaddrinfo: Query both IPv4 and IPv6 if hints is missing

Nitpick about commit message: fairly speaking, the matter should be that IPv4 and IPv6 should be both queried if hints has AF_UNSPEC address family (and that's default if hints is NULL at all).

File: subsys/net/lib/sockets/getaddrinfo.c [hunk 1]
```diff
@@ -226,6 +226,23 @@ int z_impl_z_zsock_getaddrinfo_internal(const char *host, const char *service,
 		st1 = DNS_EAI_SYSTEM;
 	}
 
+	if (family == AF_UNSPEC && IS_ENABLED(CONFIG_NET_IPV6)) {
```
Comment (pfalcon) [inline subsys/net/lib/sockets/getaddrinfo.c]: Would be nice to get a comment here what exactly happens here (i.e. that if family == AF_UNSPEC, we already have queried IPv4 case in the previous block).

File: subsys/net/lib/sockets/getaddrinfo.c [hunk 2]
```diff
@@ -105,7 +105,7 @@ static int exec_query(const char *host, int family,
 {
 	enum dns_query_type qtype = DNS_QUERY_TYPE_A;
 
-	if (IS_ENABLED(CONFIG_NET_IPV6) && family != AF_INET) {
+	if (IS_ENABLED(CONFIG_NET_IPV6) && family == AF_INET6) {
```
Comment (pfalcon) [inline subsys/net/lib/sockets/getaddrinfo.c]: Probably worth adding a comment, that for AF_UNSPEC case, we query IPv4 in this func.

**Review by pfalcon — COMMENTED** [review]
Thanks for picking this up. To avoid future confusion when working with this func, would be nice to add one, better both, of: a) code comments; b) testcase for this behavior.

As you know, I never insist on b), though that's a perfect example where we need this... (Again, not insisting.)

**Comment by jukkar** [comment]
Updated according to comments.

**Review by pfalcon — APPROVED** [review]
Thanks for the updates, looks great!

Removing platform_whitelist was a bit too brave and hits the same issue patch from @andrewboie hit earlier. Better to skip that change for now I guess.

**Comment by jukkar** [comment]
> Removing platform_whitelist was a bit too brave and hits the same issue patch from @andrewboie hit earlier. Better to skip that change for now I guess.

I have been removing the whitelists in various PRs. Created an issue yesterday for this one #16778

**Comment by jukkar** [comment]
Rebased against latest master.

**Comment by pfalcon** [comment]
As this no longer contains any changes not described in the topic of the PR, I'd suggest to merge it. (I guess @tbursztyka is on vacation, nor this is his known area of interest.)

**Comment by jukkar** [comment]
recheck
