### PR TITLE
Check if device is ready before taking interface up

### LINKED ISSUE #65423: net: Networking initialisation doesn't check device init status
**Describe the bug**
Zephyr has a framework to check if a device is ready i.e., successfully initialised and ready to use. But networking subsystem in the initialisation `net_init` doesn't propagate the network device initialisation errors (most functions in that path return `void`), so, even though a network device initialisation fails the check `device_is_ready(net_dev)` returns `ready`.

**To Reproduce**
1. Fake a failure in any network device init, note the return value is still void.
2. the `net_if_up` is still called (if auto start is set), and check for `device_is_ready()` it returns success.

**Expected behavior**
All network device errors should be propagated up.

**Impact**
As the standard API to check for readiness doesn't work, need to resort to custom checks.

**Logs and console output**
Screenshot of callstack during init.

image

**Additional context**
None.

### PR DESCRIPTION
**Pull request by jukkar**
Change the `net_if_up()` to check if the network device is ready or not. It if the device is not ready, then do not take the interface up as we cannot send or receive from the corresponding network interface anyway.

Fixes #65423

### CODE REVIEW

File: subsys/net/ip/net_if.c [hunk 1]
```diff
@@ -4360,12 +4365,23 @@ static void init_igmp(struct net_if *iface)
...
 
 	NET_DBG("iface %p", iface);
 
 	net_if_lock(iface);
 
+	/* If the device is not ready it is pointless trying to take it up. */
+	dev = net_if_get_device(iface);
+	NET_ASSERT(dev);
+
+	if (!device_is_ready(dev)) {
```
Comment (krish2718) [inline subsys/net/ip/net_if.c:4379]: As per the linked bug this would fail as `dev->state->init_res` won't be set to failure in case device fails, its only set to failure if `services_init` fails.

Comment (jukkar) [reply subsys/net/ip/net_if.c:4379]: Hmm, could you elaborate what is the use case because you mentioned in the issue specifically the `device_is_ready()` checks?

File: subsys/net/ip/net_if.c [hunk 2]
```diff
@@ -4295,6 +4295,11 @@ static void update_operational_state(struct net_if *iface)
 	enum net_if_oper_state prev_state = iface->if_dev->oper_state;
 	enum net_if_oper_state new_state = NET_IF_OPER_UNKNOWN;
 
+	if (!device_is_ready(net_if_get_device(iface))) {
+		new_state = NET_IF_OPER_LOWERLAYERDOWN;
+		goto exit;
+	}
+
```
Comment (rlubos) [inline subsys/net/ip/net_if.c:4302]: Wouldn't it make sense to move this check after `net_if_is_admin_up()`? I think that if the interface was not brought up (or failed trying to do so) it should remain in `NET_IF_OPER_DOWN` state, regardless of the underlying device status. Or maybe even this part is not needed after all, since currently the inteface won't be brought ADMIN UP in case the underlying device is not ready.

File: subsys/net/ip/net_if.c (hunk 1 above)
Comment (jukkar) [reply subsys/net/ip/net_if.c:4379]: Coming back to this PR and I have more comments.

> Usecase1: An application that works with two network interfaces can use `device_is_ready` check to select a working interface and switch to other.

The application should not investigate the device but the network interface status if it is interested if it can send something.

> 
> Usecase2: An application that tries to bring the network interface up and implements a recovery mechanism in case if it fails multiple times, using `device_is_ready` it can skip interface up and go straight to recovery or identify that device has failed using `device_is_ready` and does chip recovery. (Of course this can be implemented in many ways, but just an example).

Here too, it is better to do things in network interface level. If the network device has implemented `start()` and `stop()`  network API functions, then the driver can return relevant status code up in the stack when calling `net_if_up()` and `net_if_down()`

File: subsys/net/ip/net_if.c (hunk 2 above)
Comment (jukkar) [reply subsys/net/ip/net_if.c:4302]: Yes, I agree, I will move the check after admin up check.

File: subsys/net/ip/net_if.c [hunk 3]
```diff
@@ -4360,12 +4365,23 @@ static void init_igmp(struct net_if *iface)
...
+	/* If the device is not ready it is pointless trying to take it up. */
+	dev = net_if_get_device(iface);
+	NET_ASSERT(dev);
+
+	if (!device_is_ready(dev)) {
+		NET_DBG("Device %s (%p) is not ready", dev->name, dev);
+		status = -ENXIO;
+		goto out;
+	}
+
```
Comment (jukkar) [inline subsys/net/ip/net_if.c:4384]: After some more investigation, I am not sure if we should actually do this. If we return error at this point and not call device driver `start()` API function, then the device does not have a chance to try to take the device up.
Or we could move this check later in this function and only check the device readiness if the L2 does not implement the `enable()`, in which case the device does not have `start()` function what we could call.
WDYT?

Comment (rlubos) [reply subsys/net/ip/net_if.c:4384]: I think you're right, if the device is not ready, it should fail on `start()`

**Comment by jukkar** [comment]
I moved the state change down as suggested by @rlubos, the device oper state stays the same if the device is not ready.
Also the device readiness is only checked if the device does not provide start API function as then there is nothing we can do in network level. If the device has start() implemented, then it should try to make the device ready when `net_if_up()` is called.
I also noticed that the dummy L2 did not implement enable() API which felt wrong. Dummy L2 does not provide any L2 protocol, but that does not mean that the related device should not provide start/stop functionality.

File: subsys/net/ip/net_if.c [hunk 4]
```diff
@@ -4448,12 +4453,17 @@ static void init_igmp(struct net_if *iface)
...
 	int status = 0;
 
 	NET_DBG("iface %p", iface);
 
 	net_if_lock(iface);
 
+	/* If the device is not ready it is pointless trying to take it up. */
+	dev = net_if_get_device(iface);
+	NET_ASSERT(dev);
+
```
Comment (jukkar) [inline subsys/net/ip/net_if.c:4466]: Forgot to move this next to the `device_is_ready()` call, will send a new version that will do that.

**Review by rlubos — APPROVED** [review]

**Review by krish2718 — APPROVED** [review]
