### PR TITLE
drivers: mipi-dbi-spi: Fix initialization of GPIO CS

### LINKED ISSUE #97746: STM32F429I-DISC1 display not working
### Describe the bug

Platform: STM32F429I-DISC1

The display demo at `zephyr/samples/drivers/display` work with `v4.2.1`. I went through the `git bisect` and discovered that they stop working with commit 011a357db09118fa31ecb3a1986238e097cc7ed9.

Working: the rectangles appeared on my display.

Not working: the screen remained blank.

In both cases, the UART shell was still responsive.

### Regression

- [x] This is a regression.

### Steps to reproduce

`cd  zephyr/samples/drivers/display`
`west build -b stm32f429i_disc1 .`
`west flash`

### Relevant log output

```shell

```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

- OS: Arch Linux
- Toolchain: SDK 0.17.4
- Commit SHA: 011a357db09118fa31ecb3a1986238e097cc7ed9

### Additional Context

_No response_

### LINKED ISSUE #98029: display: blank display on st25dv
### Describe the bug

The display sample shows a blank screen instead of the 4-squares thing.
- Board: st25dv_mb1283_disco
- Tested with samples/drivers/display

Git bisect says it comes from commit 011a357db09118fa31ecb3a1986238e097cc7ed9 (drivers: mipi-dbi-spi: fix initialization of SPI CS).

### Regression

- [x] This is a regression.

### Steps to reproduce

west build -b st25dv_mb1283_disco -p always drivers/display/

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- Linux Mint
- Zephyr main

### Additional Context

If someone else has the same target:
- For some reason this target has to be power cycled to work correctly, reset button only does not work
- Also this board can only be flashed if reset button is released 2 seconds after "west flash", as per an old ST-Link tradition

### PR DESCRIPTION
**Pull request by jeremydick**
Access the correct node to get the SPI device GPIO CS. It comes from the parent spi-dev node, not the bus

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/97746
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/98029

### CODE REVIEW

File: include/zephyr/drivers/mipi_dbi.h [hunk 1]
```diff
@@ -41,6 +41,19 @@
 extern "C" {
 #endif
 
+/** @cond INTERNAL_HIDDEN */
+#define MIPI_DBI_SPI_DT(node_id)					\
```
Comment (JarmouniA) [inline include/zephyr/drivers/mipi_dbi.h]:
```suggestion
#define MIPI_DBI_DT_SPI_DEV(node_id)					\
```

**Comment by JarmouniA** [comment]
Cc @everedero

**Review by VynDragon — APPROVED** [review]

**Review by JarmouniA — APPROVED** [review]

**Comment by everedero** [comment]
Tested on the st25dv_mb1283_disco target, it works!

**Comment by smfelsher** [comment]
I can confirm that #98086 works with `samples/drivers/display`. I can also confirm that `samples/modules/lvlg/demos/` works with #98086.

Thank you all for your time and effort.
