### PR TITLE
drivers: uart stm32 flushing Rx register once the RXNE irq is enabled

### LINKED ISSUE #39703: stm32 uart testing fails on test_read_abort
The test case tests/drivers/uart/uart_async_api/  fails on several stm32 target boards  with a deadlock in the 
**START - test_read_abort**  sequence

The https://github.com/zephyrproject-rtos/zephyr/pull/37859   could be linked to that failure

**To Reproduce**
1. west build -p auto -b nucleo_g071rb tests/drivers/uart/uart_async_api/

**Expected behavior**
TEST passed

**Impact**
test campaign failure on:
   _tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, disco_l475_iot1
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, nucleo_f746zg
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, nucleo_g071rb
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, nucleo_g474re
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, stm32f3_disco_

**Logs and console output**
```
*** Booting Zephyr OS build v2.7.99-283-gd79d26f1ae1f  ***
Running test suite uart_async_test
===================================================================
START - test_single_read_setup
 PASS - test_single_read_setup in 0.1 seconds
===================================================================
START - test_single_read
 PASS - test_single_read in 0.403 seconds
===================================================================
START - test_chained_read_setup
 PASS - test_chained_read_setup in 0.1 seconds
===================================================================
START - test_chained_read
 PASS - test_chained_read in 0.269 seconds
===================================================================
START - test_double_buffer_setup
 PASS - test_double_buffer_setup in 0.1 seconds
===================================================================
START - test_double_buffer
 PASS - test_double_buffer in 3.420 seconds
===================================================================
START - test_read_abort_setup
 PASS - test_read_abort_setup in 0.1 seconds
===================================================================
START - test_read_abort
```

**Environment (please complete the following information):**
 - Commit SHA  (detected on  0162f4c67a9b3337736c41d7e6acb3e5904b1dbd)
 - test PASSED on release 2.7.0

**Additional context**

### PR DESCRIPTION
**Pull request by FRASTM**
When the "Read data register not empty" irq occurs,
this commit is cleaning the RXNE flag by flushing the RX register
since the Receive Data Reg. (USART_RDR) has not be read previously
This could be the case when aborting a Rx for example.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/39703

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

**Comment by erwango** [comment]
@manoj153 Can you review and formally approve if fine with you?

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -896,6 +896,9 @@ static void uart_stm32_isr(const struct device *dev)
 #ifdef CONFIG_PM
 		uart_stm32_pm_constraint_release(dev);
 #endif
+	} else if (LL_USART_IsEnabledIT_RXNE(UartInstance)) {
```
Comment (manoj153) [inline drivers/serial/uart_stm32.c:899]:
```suggestion
	} else if (LL_USART_IsActiveFlag_RXNE(UartInstance)) {
```
LGTM, but I wonder if `LL_USART_IsActiveFlag_RXNE()` will be more appropriate?  If I understand it correctly, we need to flush only when there this something inside HW FIFO

Comment (FRASTM) [reply drivers/serial/uart_stm32.c:899]: not wrong, If we reach this code of the uart_stm32_isr interrupt, maybe even better is to combine :
```
	} else if (LL_USART_IsEnabledIT_RXNE(UartInstance) &&
			  LL_USART_IsActiveFlag_RXNE(UartInstance)) {

```

Comment (manoj153) [reply drivers/serial/uart_stm32.c:899]: I concur.

Comment (FRASTM) [reply drivers/serial/uart_stm32.c]: done

**Review by erwango — APPROVED** [review]

**Review by manoj153 — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
