### PR TITLE
Bluetooth: host: Fix pairing failed when peer cannot establish required security

### LINKED ISSUE #31607: Bluetooth: host: bt_conn_auth_cb callbacks are not called when pairing to BLE 4.1 central in BT_SECURITY_L4 mode.
I'n using peripheral_lbs from Nordic nRF Connect SDK on nRF52840dk board.
I have Android phone Samsung Galaxy J1. It has BLE 4.1 only.

I've set secuirity level to BT_SECUIRITY_L4
```
static void connected(struct bt_conn *conn, uint8_t err)
{
    if (err) {
	printk("Connection failed (err %u)\n", err);
	return;
    }

    printk("Connected\n");

    int sec_result = bt_conn_set_security(conn, BT_SECURITY_L4);
    printk("Security level, err %d\n", sec_result);
          
    dk_set_led_on(CON_STATUS_LED);
}
```

On a smartphone I run nRFConnect app and try to pair with DK board.
Pairing fails because BLE 4.1 doesn't support LESC pairing (BT_SECURITY_L4) but

Board shows that the "secuirity_changed" callback called and then immediately "disconnected" callback.

```
Passkey for d0:1d:c1:85:77:9b (random): 786779
[00:00:12.933,227] [1;31m<err> bt_hci_core: Failed to set required security level
[00:00:12.941,314] [1;31m<err> bt_conn: not connected
[00:00:12.946,960] [1;31m<err> bt_conn: not connected
Security changed: d0:1d:c1:85:77:9b (random) level 3
Disconnected (reason 22)
```

**Expected behavior**
I expect bt_conn_auth callbacks like "cancel" or "pairing_failed" to be called but they are not.

**Workaround:**
Handle in-progress pairing as failed in disconnected callback if pairing_failed has not been called yet

### PR DESCRIPTION
**Pull request by joerchan**
This PR fixes the issue where the pairing failed callback was not called when the pairing procedure could not establish the required security level because the peer did not support it, either through pairing method not supporting MITM or LE Secure Connections.
In addition the failure of this pairing procedure could be terminated earlier, instead of doing this after the connection has been encrypted with weaker security keys that what was required.

Fixes: #31607

In addition the following issues was discovered and fixed in this PR:
- Fix pairing procedure not completed when disconnected during pairing, leaves a key entry.
- Fix missing encryption pending flag with LE SC Bond.
- Fix pairing failed and security changed callbacks called when receiving unexpected SMP PDUs.
- Fix wrong error code type passed to security changed, passed SMP error
code instead of HCI error code.

### CODE REVIEW

**Comment by jhedberg** [comment]
@joerchan you'll need to fix the Compliance check failure:
```
-:446: ERROR:SPACING: space required before the open parenthesis '('
24
#446: FILE: subsys/bluetooth/shell/bt.c:314:
25
+	switch(err) {
```

File: subsys/bluetooth/host/smp.c [hunk 1]
```diff
@@ -1813,6 +1811,26 @@ static void smp_reset(struct bt_smp *smp)
 	}
 }
 
+static uint8_t hci_err_get(enum bt_security_err err)
```
Comment (carlescufi) [inline subsys/bluetooth/host/smp.c:1814]: Why? What is the code path that makes you translate from a security error to an HCI one? This is the Host.

Comment (joerchan) [reply subsys/bluetooth/host/smp.c:1814]: It's more clear if you look at the commit: https://github.com/zephyrproject-rtos/zephyr/pull/32120/commits/2352ea33150e10e784622ed34937ec6543304098

**Review by trond-snekvik — APPROVED** [review]
I don't know these modules very well, but I can't see anything wrong here, so I'm approving.

File: subsys/bluetooth/host/smp.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/smp.c:1814]: So it's not an error originating from HCI, rather you're synthesising an HCI error code based on an SMP error which has been first translated into a `bt_security_err`? That sounds like lots of translations to me :)

Comment (jhedberg) [reply subsys/bluetooth/host/smp.c:1814]: My only concern with this is that when presented with an HCI error somewhere higher up in the API I'd immediately want to take a look at the HCI log, and not finding the corresponding error code there is likely to induce some head scratching :)

Comment (jhedberg) [reply subsys/bluetooth/host/smp.c:1814]: Completely unrelated to this PR, I wonder if it'd make sense to consider some abstracted error type that could encapsulate errors from multiple different domains: HCI, protocol (like SMP), internal (e.g. based on errno), etc. That way you wouldn't need to translate from one domain to another, rather the application could see in what domain and which layer the error originated from. This might even be a Zephyr-wide discussion since other subsystems may want it as well.

Comment (carlescufi) [reply subsys/bluetooth/host/smp.c:1814]: I think it might be a good idea if we did something like that, akin to the `k_timeout_t` we introduced in the kernel. But this is long-term.
In the meantime, is there not a way we can store the HCI error code?

Comment (joerchan) [reply subsys/bluetooth/host/smp.c:1814]: @jhedberg The bt_security_err is meant to do that, encapsulate the HCI and SMP, the problem is that the security_changed is raising the encrypt_change callback for the l2cap channels, which accepts HCI status code.
In order to update that we would have to update the encrypt change callback signature, which is part of the public API.
`void (*encrypt_change)(struct bt_l2cap_chan *chan, uint8_t hci_status);`

@carlescufi There is no place to store the HCI error code, since we are terminating the security during the pairing procedure, i.e this is happening in SMP.

**Review by jhedberg — APPROVED** [review]
I don't have the chance to test this, but assuming we'll look into the error abstraction in the future I think this is ok to go in.

**Comment by carlescufi** [comment]
@sjanc could you please take a look before we merge it?

**Review by carlescufi — APPROVED** [review]
