### PR TITLE
Bluetooth: ATT: lock scheduler when sending from user thread

### LINKED ISSUE #69737: Bluetooth: ATT: att_req_send_process() fails assert on pre-emptive thread
**Describe the bug**
I did a minor adjustment to llpm sample in NCS, so that it ends up sending write commands from both central and peripheral very often. If sample is run in noisy rf-environment, this assert is reproducible pretty quickly. within 5 min normaly.
Assert Im getting:
https://github.com/zephyrproject-rtos/zephyr/blob/72a17b6d887ef20b3cc08a25d8ea1d622792d57a/subsys/bluetooth/host/att.c#L822

 - What target platform are you using?
 NRF52840DK
 
- What have you tried to diagnose or workaround this issue?
I tried a quickfix by disabling shceduler like [this](https://github.com/martintv/sdk-zephyr/commit/209bbcd3995bb711f0911d4c0b3c4b0c2d3808d9) and assert in question does go away. But when I leave it running overnight (so takes longer to reproduce) I still get a different assert [__ASSERT_NO_MSG(req->func);](https://github.com/zephyrproject-rtos/zephyr/blob/72a17b6d887ef20b3cc08a25d8ea1d622792d57a/subsys/bluetooth/host/att.c#L821).

Hypothesis then is that it is the iterator in [att_req_send_process](https://github.com/zephyrproject-rtos/zephyr/blob/72a17b6d887ef20b3cc08a25d8ea1d622792d57a/subsys/bluetooth/host/att.c#L834), but I havent looked into it further.

**To Reproduce**
setup ncs enviormnet, checkout this
https://github.com/martintv/sdk-nrf/commits/reproducing_att_assert/
west build --pristine -b nrf52840dk_nrf52840 nrf/samples/bluetooth/llpm
west flash  <--- on two dks.

**Expected behavior**
Shouldn't assert

**Impact**
Possible corruption when asserts are disabled.
Application crash when asserts are enabled.

### PR DESCRIPTION
**Pull request by jori-nordic**
`att_req_send_process` is not thread safe.

In the case where the current context is pre-emptible (e.g. when a user sends something over GATT from the main thread):

The iterator in `att_req_send_process` can get interrupted mid-processing, breaking the logic and resulting in an assert/crash/data corruption.

This is a hotfix until we have a better solution or the host is refactored to avoid this problem.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/69737

### CODE REVIEW

File: subsys/bluetooth/host/att.c [hunk 1]
```diff
@@ -3868,8 +3868,11 @@ int bt_att_req_send(struct bt_conn *conn, struct bt_att_req *req)
 		return -ENOTCONN;
 	}
 
+	/* att_req_send_process is not thread-safe */
+	k_sched_lock();
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/att.c:3872]: I think we should include the above ENOTCONN check inside the scheduler lock. It also looks thread unsafe.

**Review by alwa-nordic — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/att.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/att.c:3872]: To be more clear: The `sys_slist_append` below should be atomic with the test above. Otherwise we risk appending to a disconnected att.

Comment (jori-nordic) [reply subsys/bluetooth/host/att.c]: thanks, I added that reason to the commit message too.

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/att.c [hunk 2]
```diff
@@ -3863,6 +3863,8 @@ int bt_att_req_send(struct bt_conn *conn, struct bt_att_req *req)
 	__ASSERT_NO_MSG(conn);
 	__ASSERT_NO_MSG(req);
 
+	k_sched_lock();
+
```
Comment (Thalley) [inline subsys/bluetooth/host/att.c:3867]: if 
```c
	att = att_get(conn);
	if (!att) {
		return -ENOTCONN;
	}
```

fails, don't we need to unlock the scheduler? 

E.g. we have similar code in GATT:

```c
	k_sched_lock();

	err = gatt_register(svc);
	if (err < 0) {
		k_sched_unlock();
		return err;
	}
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/att.c (hunk 2 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/att.c:3867]: c sux. that's all I have to say :p

**Review by Thalley — APPROVED** [review]

**Comment by jori-nordic** [comment]
I misunderstood the hotfix label, removed it

**Review by martintv — APPROVED** [review]
fails wihtout this within 10 seconds for me.
has run for 1.5hours now without asserting with this.

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
