### PR TITLE
drivers: sensor: bmi160: fix waiting time before reading CHIP_ID

### LINKED ISSUE #43794: BMI160 Driver: Waiting time between SPI activation and reading CHIP IP is too low
**Describe the bug**
When resetting the SoC (nrf52840) via jlink, BMI160 stops responding. The code blocks when the driver tries to read the CHIP ID register. I solved the issue by increasing the k_busy_wait from 100 to 200.

https://github.com/zephyrproject-rtos/zephyr/blob/565fc4d29c90e244cb16b5af05d5cc47d1edc059/drivers/sensor/bmi160/bmi160.c#L901

**To Reproduce**
1. west build -b nrf52840dk_nrf52840
2. JLinkRTTClient
3. JLinkExe
3.1. connect
3.2. r
3.3. g
4. See error on JLinkRTTClient

**Impact**
It induces the user to think there is some type of BMI160 misconfiguration issue.

**Environment:**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr SDK
 - Version: 2.7.0

### PR DESCRIPTION
**Pull request by diocorreia**
Value changed from 100ms to 150ms. Value was not enough upon softreset.

Fixes #43794

Signed-off-by: Diogo Correia <dcorreia@protonmail.com>

### CODE REVIEW

**Review by carlescufi — DISMISSED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
No objection to the change, but please document why you chose this value in the commit message.

File: drivers/sensor/bmi160/bmi160.c [hunk 1]
```diff
@@ -898,7 +898,7 @@ int bmi160_init(const struct device *dev)
 		return -EIO;
 	}
 
-	k_busy_wait(100);
+	k_busy_wait(150);
```
Comment (gmarull) [inline drivers/sensor/bmi160/bmi160.c:901]: please document constants, ideally add a definition with a docstring referencing why 150 and not e.g. 157.

**Review by gmarull — DISMISSED** [review]

**Review by avisconti — DISMISSED** [review]
LGTM
As reported by other reviewers it would be nice to add in the commit message in which DS section this value is reported (if it is). Otherwise it is ok like this.

**Comment by gmarull** [comment]
> @MaureenHelm @avisconti @gmarull The value was arbitrarily chosen and then decreased until it stopped working. Upon your justification request, I have read the official bosch driver. They attempt to read the value 3 times instead of waiting, maybe it could be a better approach than this one?

maybe

image

-

image

-

image

so a sleep of 10ms seems necessary?

**Comment by MaureenHelm** [comment]
> The value was arbitrarily chosen and then decreased until it stopped working. 

This is what I'd like to see in the commit message. I don't love that it's arbitrary, but it should at least be documented as such.

> Upon your justification request, I have read the official bosch driver. They attempt to read the value 3 times instead of waiting, maybe it could be a better approach than this one?

Not really

**Comment by PeachBug** [comment]
> > @MaureenHelm @avisconti @gmarull The value was arbitrarily chosen and then decreased until it stopped working. Upon your justification request, I have read the official bosch driver. They attempt to read the value 3 times instead of waiting, maybe it could be a better approach than this one?
> 
> maybe
> 
> image
> 
> 
> image
> 
> 
> image
> 
> so a sleep of 10ms seems necessary?

I thinks this refers only to the accelerometer and gyroscope on the chip and not the chip itself. In other words, I think this wouldn't be an issue for reading CHIP_ID.

**Comment by PeachBug** [comment]
> k_busy_wait(150) waits 150 microseconds not 150 milliseconds as the commit message reflects, not a huge deal but might be confusing to look at in the future

@teburd Sorry for that. The message was fixed.

**Comment by mbolivar-nordic** [comment]
@gmarull @MaureenHelm please take another look

**Comment by MaureenHelm** [comment]
Please fix the compliance check failure:
```
Error: See https://docs.zephyrproject.org/latest/contribute/#commit-guidelines for more details

aa2aab1580e505ceafc708515f6f3bcb742d7ef9: author email (Diogo Correia <diogo.correia@fraunhofer.pt>) needs to match one of the signed-off-by entries.
```

**Review by MaureenHelm — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
I've dismissed the -1 @gmarull since he is going to be out for a few weeks, and I don't want to block this PR. Ideally I think a source code comment in addition to the commit message would be better, but at least we can get the current value's description out of `git blame`
