### PR TITLE
soc: arm: imx_rt10xx: enable code cache during boot

### LINKED ISSUE #57349: Instruction Cache is disabled during boot of NXP i.MX RT10xx for specific configurations
**Describe the bug**

For a specific set of configurations, the instruction cache of i.MX RT10xx MCUs is disabled during boot resulting in significantly worse performance.

- Tested on mimxrt1064_evk but should be relevant to all i.MX RT10xx MCUs.
- The problem occurs if the configuration settings `CONFIG_INIT_ARCH_HW_AT_BOOT` (implied by `BOOTLOADER_MCUBOOT`) and `CONFIG_ARCH_CACHE` (default choice if `CONFIG_CACHE_MANAGEMENT` is enabled) are both enabled.
- the problem was introduced in commit 1ed776a218ad10b0aa9454b1a3f7517a0f3a63fb:
  - a call to `SCB_EnableICache()` was removed from `imxrt_init()` (zephyr\soc\arm\nxp_imx\rt\soc_rt10xx.c) and a call to `SystemInit()` was added to `z_arm_platform_init()`. 
  - `SystemInit()` does enable the instruction cache (also by calling `SCB_EnableICache()`).
  - If `CONFIG_INIT_ARCH_HW_AT_BOOT` is enabled, the function `z_arm_init_arch_hw_at_boot()` (arch\arm\core\aarch32\cortex_m\scb.c) is called after `z_arm_platform_init()` during the boot sequence in `z_arm_reset()` (arch\arm\core\aarch32\cortex_m\reset.S).
  - If `CONFIG_ARCH_CACHE` is enabled, `z_arm_init_arch_hw_at_boot()` disables the instruction cache.
  - `imxrt_init()` is called after `z_arm_init_arch_hw_at_boot()`, so previously to commit 1ed776a218ad10b0aa9454b1a3f7517a0f3a63fb, the instruction cache was enabled anyway.

As a workaround, I restored the call to  `SCB_EnableICache()` in `imxrt_init()`. This restored the expected behavior.

**To Reproduce**

The easiest way to reproduce this is to build the SMP Server Sample (https://docs.zephyrproject.org/latest/samples/subsys/mgmt/mcumgr/smp_svr/README.html#smp-svr-sample) with `CONFIG_CACHE_MANAGEMENT=y`.

Since the SMP server is not very complex, the performance loss is not easily noticable. The state of the instruction cache can be determined from the corresponding register (SystemControl(0xe000e000)->CCR.IR).

**Expected behavior**

Unless otherwise configured (`CONFIG_IMXRT1XXX_CODE_CACHE=n`), the instruction cache should be enabled.

**Impact**

A reasonably complex application (usually >90% idle according to thread statistics) is significanly slowed down without the instruction cache.

### PR DESCRIPTION
**Pull request by kt-peters**
For certain combinations of configuration parameters, z_arm_init_arch_hw_at_boot() disables the instruction cache. Make sure to re-enable it if required.

Fixes #57349

### CODE REVIEW

**Comment by nordicjm** [comment]
@carlocaione was there not a reason for this, something to do with bootloaders?

**Review by carlocaione — CHANGES_REQUESTED** [review]
I have two doubts about this:
- Why this is not using the cache API?
- If there is something wrong with `z_arm_init_arch_hw_at_boot` this must be fixed there and not carry a soc specific fix.

**Comment by kt-peters** [comment]
> I have two doubts about this:
> 
>     * Why this is not using the cache API?

- The problem occured for me with commit 1ed776a218ad10b0aa9454b1a3f7517a0f3a63fb, where a call to `SCB_EnableICache()` was removed. I assumed it would make sense to just restore the missing function call. 
- `SCB_DisableICache()` and `SCB_EnableDCache()` are called in the same function.

> 
>     * If there is something wrong with `z_arm_init_arch_hw_at_boot` this must be fixed there and not carry a soc specific fix.

I was considering this, but I'm honestly not sure if I fully understand the intention of this code:

```
#if defined(CONFIG_ARCH_CACHE)
#if defined(CONFIG_DCACHE)
	/* Reset D-Cache settings. If the D-Cache was enabled,
	 * SCB_DisableDCache() takes care of cleaning and invalidating it.
	 * If it was already disabled, just call SCB_InvalidateDCache() to
	 * reset it to a known clean state.
	 */
	if (SCB->CCR & SCB_CCR_DC_Msk) {
		sys_cache_data_disable();
	} else {
		sys_cache_data_invd_all();
	}
#endif /* CONFIG_DCACHE */

#if defined(CONFIG_ICACHE)
	/* Reset I-Cache settings. */
	sys_cache_instr_disable();
#endif /* CONFIG_ICACHE */
#endif /* CONFIG_ARCH_CACHE */
```

Currently, if `CONFIG_ARCH_CACHE` is enabled (which it is not by default), this results in both data cache and instruction cache being disabled after `z_arm_init_arch_hw_at_boot`. If the intention was for SOCs to re-enabled caching afterwards depending on the configuration, there appears to be nothing "wrong" with `z_arm_init_arch_hw_at_boot`. As a change in `z_arm_init_arch_hw_at_boot` would affect SOCs I'm neither familiar with nor able to test on, I'm a bit hesitant to touch that function.

**Comment by carlocaione** [comment]
@danieldegrasse did you mean to entirely remove `SCB_EnableICache()` in https://github.com/zephyrproject-rtos/zephyr/commit/1ed776a218ad10b0aa9454b1a3f7517a0f3a63fb or was it a mistake?

**Comment by danieldegrasse** [comment]
> @danieldegrasse did you mean to entirely remove SCB_EnableICache() in https://github.com/zephyrproject-rtos/zephyr/commit/1ed776a218ad10b0aa9454b1a3f7517a0f3a63fb or was it a mistake?

It was intentional, but I did not consider the possible interaction with the cache API, as that API is not enabled by default on this platform. I think this fix is a valid one though, there is no issue with enabling the ICACHE twice during boot.

> Why this is not using the cache API?

I don't think we need to use the cache API here- this code is specific to the RT10xx series, which only uses the SCB cache controller.

**Review by carlocaione — APPROVED** [review]
@danieldegrasse can you register your ACK as well?

File: soc/arm/nxp_imx/rt/soc_rt10xx.c [hunk 1]
```diff
@@ -292,6 +292,11 @@ static int imxrt_init(void)
 #ifndef CONFIG_IMXRT1XXX_CODE_CACHE
 	/* SystemInit enables code cache, disable it here */
 	SCB_DisableICache();
+#else
+	/* z_arm_init_arch_hw_at_boot() disables code cache if CONFIG_ARCH_CACHE is enabled,
+	 * enable it here.
```
Comment (iuliana-prodan) [inline soc/arm/nxp_imx/rt/soc_rt10xx.c:297]: My understanding from this comment is that we have to enable code cache _only_ if CONFIG_ARCH_CACHE is set.
Is this always set, or why don't we check for this config before doing SCB_EnableICache?

Also, should be done the same thing here: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/arm/nxp_imx/rt/soc_rt11xx.c#L659 ?

Comment (kt-peters) [reply soc/arm/nxp_imx/rt/soc_rt10xx.c:297]: > My understanding from this comment is that we have to enable code cache _only_ if CONFIG_ARCH_CACHE is set. Is this always set, or why don't we check for this config before doing SCB_EnableICache?

That is currently true. However, if anyone were to change `z_arm_init_arch_hw_at_boot` without considering what's happening here (that code affects all ARM SOCs, not only RT10xx), we might end up with a disabled instruction cache again.

As @danieldegrasse mentioned above, there is no harm in calling `SCB_EnableICache` when the instruction cache is enabled already, as the function first checks for that and just returns. On the other hand, if the instruction cache is not enabled at this point for any reason whatsoever, I want it to be enabled ASAP or my application is slowed down to a crawl again.

> Also, should be done the same thing here: https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/arm/nxp_imx/rt/soc_rt11xx.c#L659 ?

Unfortunately I don't have any RT11xx hardware to test this, but it looks to me like you are correct. I'm just not sure if I should add code that I can't test.

**Review by danieldegrasse — APPROVED** [review]

File: soc/arm/nxp_imx/rt/soc_rt10xx.c (hunk 1 above)
Comment (danieldegrasse) [reply soc/arm/nxp_imx/rt/soc_rt10xx.c:297]: > Also, should be done the same thing here: [main/soc/arm/nxp_imx/rt/soc_rt11xx.c#L659](https://github.com/zephyrproject-rtos/zephyr/blob/main/soc/arm/nxp_imx/rt/soc_rt11xx.c?rgh-link-date=2023-05-03T10%3A17%3A36Z#L659) ?

Yes, likely so. I'll open a PR with this fix, as I have an RT11xx available to verify it with

**Review by iuliana-prodan — APPROVED** [review]
