### PR TITLE
Bluetooth: controller: llcp: fix access to context after release

### LINKED ISSUE #48850: Bluetooth: LLCP: possible access to released control procedure context
**Describe the bug**
https://github.com/zephyrproject-rtos/zephyr/blob/f8031c7ab08c7b27a3a1949ae6bcad6f9d45dbeb/subsys/bluetooth/controller/ll_sw/ull_llcp_local.c#L390-L391
The link points to code that executes top LLCP state machine.

Just after `lr_act_run` there is an if statement that verifies `ctx->proc`. 
Unfortunately there is a possibility that the `ctx` is released during processing of `lr_act_run`.

Follow example execution path for DLE procedure: `ull_cp_run` -> `llcp_lr_run` -> `lr_execute_fsm` -> `lr_st_idle` -> `lr_act_run` -> `llcp_lp_comm_run` -> `lp_comm_execute_fsm` -> `lp_comm_st_idle` -> `lp_comm_send_req` -> `llcp_lr_complete` (if remote DLE is pending) ->  `lr_execute_fsm(conn, LR_EVT_COMPLETE, NULL);` -> `lr_st_idle` -> `lr_act_complete` (sets `ctx->done = 1U` -> returns to back to `lr_act_run` where at end `lr_check_done` releases the `ctx` -> returns to `lr_st_idle` where `ctx` is released and in the if statement there is use of it without checking if it is valid.

**Expected behavior**
As of now it looks like there is no problem during execution because contexts are allocated in static memory, hence release does not make the memory to be overwritten. Also contexts are not being allocated immediately. In future it may happen that the context is re-used and stored information overwritten. It may lead to unexpected behavior that may be hard to find.

There should be a verification when there is a possibility that contexts are released before they are used again.

**Impact**
Related only with refactored LLCPs.

### PR DESCRIPTION
**Pull request by kruithofa**
There is access to the procedure context after a potential release of the context, which (in theory) can lead to incorrect behaviour

There is no good way of testing this with a unittest without adding specal debug code to the ull_llcp_local module
After code-inspection no other location has been found with potential access after context release

fixes #48850

Signed-off-by: Andries Kruithof <andries.kruithof@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c [hunk 1]
```diff
@@ -382,13 +382,19 @@ static void lr_st_disconnect(struct ll_conn *conn, uint8_t evt, void *param)
 static void lr_st_idle(struct ll_conn *conn, uint8_t evt, void *param)
 {
 	struct proc_ctx *ctx;
+	enum llcp_proc curr_proc;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_local.c:385]:
```suggestion
```

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c [hunk 2]
```diff
@@ -382,13 +382,19 @@ static void lr_st_disconnect(struct ll_conn *conn, uint8_t evt, void *param)
...
 
 	switch (evt) {
 	case LR_EVT_RUN:
 		ctx = llcp_lr_peek(conn);
 		if (ctx) {
+			/*
+			 * since the call to lr_act_run may release the context we need to remember
+			 * which procedure we are running
+			 */
+			curr_proc = ctx->proc;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_local.c:395]:
```suggestion
			const enum llcp_proc curr_proc = ctx->proc;

```

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c [hunk 3]
```diff
@@ -382,13 +382,19 @@ static void lr_st_disconnect(struct ll_conn *conn, uint8_t evt, void *param)
...
 			lr_act_run(conn);
-			if (ctx->proc != PROC_TERMINATE) {
+			if (curr_proc != PROC_TERMINATE) {
 				lr_set_state(conn, LR_STATE_ACTIVE);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_local.c:398]: Would `lr_set_state` try to access any released context? Why I ask, `lr_act_run(conn)` has similar parameter signature of passing `conn` and accessing the `ctx` to release it.

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c (hunk 3 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_local.c:398]: I checked, lr_set_state does not access the ctx

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c (hunk 2 above)
Comment (kruithofa) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_local.c]: done

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_llcp_local.c]: I do not see the `const`, did you forget to push?

File: subsys/bluetooth/controller/ll_sw/ull_llcp_local.c [hunk 4]
```diff
@@ -387,8 +387,13 @@ static void lr_st_idle(struct ll_conn *conn, uint8_t evt, void *param)
 	case LR_EVT_RUN:
 		ctx = llcp_lr_peek(conn);
 		if (ctx) {
+			/*
+			 * since the call to lr_act_run may release the context we need to remember
+			 * which procedure we are running
+			 */
+			enum llcp_proc curr_proc = ctx->proc;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_local.c:394]:
```suggestion
			const enum llcp_proc curr_proc = ctx->proc;
```

**Review by cvinayak — APPROVED** [review]

**Review by thoh-ot — APPROVED** [review]
