### PR TITLE
Bluetooth: Host: Remove unnecessary #ifndef

### LINKED ISSUE #82550: Bluetooth: Host: Build failure when enabling `CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY`
**Describe the bug**

Building the Bluetooth Host with `CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY` enabled is failing.

**To Reproduce**

Build an application (e.g. `peripheral_hr`) with the following configuration:
```
CONFIG_BT=y
CONFIG_BT_SMP=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP_SC_PAIR_ONLY=n
CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY=y
```

### PR DESCRIPTION
**Pull request by theob-pro**
See commit messages for details.

Fix #82550

### CODE REVIEW

File: subsys/bluetooth/host/smp.c [hunk 1]
```diff
@@ -3685,6 +3685,10 @@ static void le_sc_oob_config_set(struct bt_smp *smp,
 
 	info->lesc.oob_config = oob_config;
 }
+#else
+
+void le_sc_oob_config_set(struct bt_smp *smp, struct bt_conn_oob_info *info);
```
Comment (jhedberg) [inline subsys/bluetooth/host/smp.c:3690]: Missing `static`. However, why are not instead moving the function definition to the right place and behind the right build-time conditionals (which match the conditionals of its usage)?

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/smp.c (hunk 1 above)
Comment (theob-pro) [reply subsys/bluetooth/host/smp.c:3690]: > Missing `static`.

We're getting the following warning when using `static`:
```
/home/thb1-local/zephyrproject/zephyr/subsys/bluetooth/host/smp.c:3690:13: error: ‘le_sc_oob_config_set’ used but never defined [-Werror]
 3690 | static void le_sc_oob_config_set(struct bt_smp *smp, struct bt_conn_oob_info *info);
      |             ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

> However, why are not instead moving the function definition to the right place and behind the right build-time conditionals (which match the conditionals of its usage)?

The use site doesn't have conditional compile. It relies on dead code elimination by the compiler to avoid a linker error.

Do you have a suggested solution?

Comment (jhedberg) [reply subsys/bluetooth/host/smp.c:3690]: Move the definition out so that it's not restricted by any build time conditions?

Comment (theob-pro) [reply subsys/bluetooth/host/smp.c:3690]: It seems that they have been added there: https://github.com/zephyrproject-rtos/zephyr/pull/74400
It seems they were needed

Comment (jhedberg) [reply subsys/bluetooth/host/smp.c:3690]: I did this quick change on top of your PR, and it seems to work fine:
```patch
diff --git a/subsys/bluetooth/host/smp.c b/subsys/bluetooth/host/smp.c
index c737f59e958..62028827ebf 100644
--- a/subsys/bluetooth/host/smp.c
+++ b/subsys/bluetooth/host/smp.c
@@ -3640,7 +3640,6 @@ static uint8_t sc_smp_check_confirm(struct bt_smp *smp)
 	return 0;
 }
 
-#ifndef CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY
 static bool le_sc_oob_data_req_check(struct bt_smp *smp)
 {
 	struct bt_smp_pairing *req = (struct bt_smp_pairing *)&smp->preq[1];
@@ -3685,11 +3684,6 @@ static void le_sc_oob_config_set(struct bt_smp *smp,
 
 	info->lesc.oob_config = oob_config;
 }
-#else
-
-void le_sc_oob_config_set(struct bt_smp *smp, struct bt_conn_oob_info *info);
-
-#endif /* CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY */
 
 static uint8_t smp_pairing_random(struct bt_smp *smp, struct net_buf *buf)
 {
@@ -4190,7 +4184,6 @@ static uint8_t smp_security_request(struct bt_smp *smp, struct net_buf *buf)
 }
 #endif /* CONFIG_BT_CENTRAL */
 
-#ifndef CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY
 static uint8_t generate_dhkey(struct bt_smp *smp)
 {
 	if (IS_ENABLED(CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY)) {
@@ -4232,12 +4225,6 @@ static uint8_t display_passkey(struct bt_smp *smp)
 
 	return 0;
 }
-#else
-
-uint8_t generate_dhkey(struct bt_smp *smp);
-uint8_t display_passkey(struct bt_smp *smp);
-
-#endif /* CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY */
 
 #if defined(CONFIG_BT_PERIPHERAL)
 static uint8_t smp_public_key_periph(struct bt_smp *smp)
```

Comment (jhedberg) [reply subsys/bluetooth/host/smp.c:3690]: > They have been added there: #74400 It seems they were needed

Seems like that PR was buggy, and the issue should have been solved in a different way. I wonder what configuration I should try with my proposed change above to verify that it's fine. It builds cleanly with your new test app, as well as with the default configuration for nrf52840dk with peripheral_hr and peripheral_sc_only.

Comment (alwa-nordic) [reply subsys/bluetooth/host/smp.c:3690]: If it works without the ifdefs then we should go for that.

**Review by jhedberg — APPROVED** [review]

File: tests/bluetooth/host_config_variants/testcase.yaml
Comment (Thalley) [inline tests/bluetooth/host_config_variants/testcase.yaml:1]: For LE Audio we've mostly used the shell for this purpose. Just building without linking may not show catch all issues. 

e.g.
```
// bar.c

#if defined(BAR)
int bar () { return 0; };
#endif
```

```
// foo.c
int bar();

int foo() {
    return bar();
}
```

```
// main.c

int main(void)
{
	return 0;
}
```

Will build fine when BAR=n, but

```
// main.c

int main(void)
{
	return foo();
}
```

Would give a linker issue. 

This test you added will work fine for compile issues, but AFAIK won't catch linker issues, right?

Comment (jhedberg) [reply tests/bluetooth/host_config_variants/testcase.yaml:1]: What's missing above is `if (IS_ENABLED(BAR)) {` before trying to call `bar()`. As long as you do that the right thing should happen both for compilation and linking. `IS_ENABLED()` can also be combined with static functions, i.e. as long as the function definition doesn't have build-time guards both the compiler and linker should be happy (the linker will strip out the function if it wasn't used).

**Review by alwa-nordic — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Comment by spanceac** [comment]
when I pushed https://github.com/zephyrproject-rtos/zephyr/pull/74400 I was testing with `CONFIG_BT_CENTRAL` enabled and unfortunately I didn't also test with `CONFIG_BT_PERIPHERAL`. So it's worth having a test with central role enabled

File: tests/bluetooth/host_config_variants/testcase.yaml [hunk 2]
```diff
@@ -0,0 +1,16 @@
+tests:
+  # Test that the Host builds with BT_SMP_OOB_LEGACY_PAIR_ONLY enabled
+  bluetooth.host_config_variants.config_bt_smp_oob_legacy_pair_only:
```
Comment (spanceac) [inline tests/bluetooth/host_config_variants/testcase.yaml:3]: My suggestion is to also add a test with
```
CONFIG_BT_CENTRAL=y
CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY=y
```
And for both peripheral and central tests add:
`CONFIG_COMPILER_OPT="-Werror"`
to ensure that the warnings are no longer there

Comment (theob-pro) [reply tests/bluetooth/host_config_variants/testcase.yaml:3]: Test are already build with warning as error. Please, if what I did is not enough, create an issue.

As pointed by @jhedberg I am not sure https://github.com/zephyrproject-rtos/zephyr/pull/74400 was the best way to go to fix the issue. Also it would have been nice to have a regression test added to avoid the current situation...
