### PR TITLE
mcumgr: smp: Fix NULL pointer reference

### LINKED ISSUE #37105: mcumgr: BUS FAULT when starting dfu with mcumgr CLI
**Describe the bug**
BUS FAULT after starting dfu over mcumgr CLI.

**To Reproduce**
The issue could be reproduced under following conditions:
1. Must have heavily loaded workqueue context
2. Perform update with mcumgr cli tool.

When the workqueue contex is overwhelmed its possible that smp_bt will try to allocate
many buffers for mcumgr. The pool contains 5 separate buffers.
If the backend fails to allocate the next buffer it should drop the packet and continue.
Currently udp/bt backends does not check if the buffer was allocated:
- https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/mcumgr/smp_udp.c#L123
- https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/mcumgr/smp_bt.c#L55

This may result in refering NULL pointer and in the end BUS FAULT.

Steps to reproduce the issue in Nordics NCS:
1. `cd applications/machine_learning/`
2. `west build -b thingy53_nrf5340_cpuapp`
3. `west flash`
4. Open JLinkRTTViewer and connect to the Thingy53 target. See logs.
5. . `mcumgr --conntype ble --connstring 'peer_name=EI Thingy53' image upload $ZEPHYR_BASE/../nrf/applications/machine_learning/build/zephyr/app_update.bin`
6. See:
```
[00:00:25.554,656] <err> os: ***** *BUS FAULT* *****
--
[00:00:25.554,687] <err> os: Precise data bus error
[00:00:25.554,687] <err> os: BFAR Address: 0xc
[00:00:25.554,687] <err> os: r0/a1: 0x000101fc r1/a2: 0x2000aa55 r2/a3: 0x00000100
[00:00:25.554,687] <err> os: r3/a4: 0x0000472d r12/ip: 0x0000fc00 r14/lr: 0x00031323
[00:00:25.554,718] <err> os: xpsr: 0x01100000
[00:00:25.554,718] <err> os: s[ 0]: 0x00000000 s[ 1]: 0x00000000 s[ 2]: 0x00000000 s[ 3]: 0x00000000
[00:00:25.554,748] <err> os: s[ 4]: 0x00000000 s[ 5]: 0x00000000 s[ 6]: 0x00000000 s[ 7]: 0x00000000
[00:00:25.554,748] <err> os: s[ 8]: 0x00000000 s[ 9]: 0x00000000 s[10]: 0x00000000 s[11]: 0x00000000
[00:00:25.554,748] <err> os: s[12]: 0x00000000 s[13]: 0x00000000 s[14]: 0x00000000 s[15]: 0x00000000
[00:00:25.554,748] <err> os: fpscr: 0x00000100
[00:00:25.554,779] <err> os: Faulting instruction address (r15/pc): 0x00031a94
[00:00:25.554,779] <err> os: >>> *ZEPHYR FATAL ERROR* 0: CPU exception on CPU 0
[00:00:25.554,779] <err> os: Current thread: 0x20001118 (unknown)
[00:00:26.051,025] <err> os: Halting system
```

**Additional context**
The origin of this issue is caused by SMP backend not checking if the mcumgr buffer allocation ended up with success.
If the buffer is not allocated the bt backend (used in the app) refers to a NULL pointer causing BUS FAULT.

SMP backends (udp/bt) does not provide a good recovery from state when
there is no buffer left in the pool for mcumgr frame.

The issue is fixed by https://github.com/zephyrproject-rtos/zephyr/pull/37081 for BT backend.
This is created to track the issue for UDP backend where the only thing i did in #37081 is `LOG_ERR`
together with dropped frame. Correctness of this behavior is not tested by me and should be verified.
For now i assume its better to at least print the error message and skip the frame rather than
get BUS FAULT.

### PR DESCRIPTION
**Pull request by eobalski**
SMP implementation across bt/udp does not check
if allocation of the buffer was successful.
If the buffer is not granted an error shall be
returned.

This patch fixes BUS FAULT issue when NULL
pointer is referenced.

The issue i was facing is BUS FAULT when there were no buffer chunks left in the pool.
Current implementation does not check if the buffer was allocated and refers the pointer no matter
what.
For more info, see: https://projecttools.nordicsemi.no/jira/browse/NCSDK-10509

Signed-off-by: Emil Obalski <emil.obalski@nordicsemi.no>

### CODE REVIEW

**Review by nvlsianpu — APPROVED** [review]

File: subsys/mgmt/mcumgr/smp_udp.c [hunk 1]
```diff
@@ -121,6 +121,9 @@ static void smp_udp_receive_thread(void *p1, void *p2, void *p3)
 
 			/* store sender address in user data for reply */
 			nb = mcumgr_buf_alloc();
+			if (!nb) {
+				continue;
+			}
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/smp_udp.c:126]: I am not sure whether it is ok, because this will be skipping some data, as continue will execute `recvfrom` , and then some buffer will be allocated and the `zephyr_smp_rx_req` will be called with some missing bytes in front, shouldn't here be at least some log?

File: subsys/mgmt/mcumgr/smp_bt.c [hunk 2]
```diff
@@ -53,6 +53,9 @@ static ssize_t smp_bt_chr_write(struct bt_conn *conn,
 	struct net_buf *nb;
 
 	nb = mcumgr_buf_alloc();
+	if (!nb) {
+		return -1;
+	}
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/smp_bt.c:58]: Could some error code be used here?

Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp_bt.c:58]: I left this intentionally to start this discussion. I totally agree `-1` is not what is good here but i saw similar thing here
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/mgmt/mcumgr/smp_bt.c#L169. I could change this in both places but wanted to discuss it earlier.
What do you think about including `<mgmt/mgmt.h>` and returning `-MGMT_ERR_ENOMEM` here and `-MGMT_ERR_EINVAL` at line 169.

File: subsys/mgmt/mcumgr/smp_udp.c (hunk 1 above)
Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp_udp.c:126]: Quite frankly i dont have much time i can spent on that and think about the correct solution so i thought its better to put anything than nothing here. I could add `LOG_ERR`, would that be okay?

File: subsys/mgmt/mcumgr/smp_bt.c (hunk 2 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_bt.c:58]: OK, `-MGMT_ERR_ENOMEM` should be fine

File: subsys/mgmt/mcumgr/smp_udp.c (hunk 1 above)
Comment (de-nordic) [reply subsys/mgmt/mcumgr/smp_udp.c:126]: Yes, but also add some note and if it would be possible, report issue in Zephyr so that we would not miss it an have a chance to discuss possible problems.

**Review by de-nordic — APPROVED** [review]
Thanks!

**Review by aunsbjerg — APPROVED** [review]
I'll take a look at the UDP part when I have more time, but for now, gracefully continuing is preferable over exceptions.

File: subsys/mgmt/mcumgr/smp.c [hunk 3]
```diff
@@ -117,6 +117,9 @@ zephyr_smp_split_frag(struct net_buf **nb, void *arg, uint16_t mtu)
 		frag = src;
 	} else {
 		frag = zephyr_smp_alloc_rsp(src, arg);
+		if (!frag) {
+			return NULL;
+		}
```
Comment (mniestroj) [inline subsys/mgmt/mcumgr/smp.c:122]: This prevents NULL dereference, but caller of `zephyr_smp_split_frag()` will then leak buffer:

https://github.com/zephyrproject-rtos/zephyr/blob/d00b37c8dd19d8e519baf20ed3b9ed1bdea28620/subsys/mgmt/mcumgr/smp.c#L185-L188

**Review by mniestroj — CHANGES_REQUESTED** [review]
There is a buffer leak as a consequence of fixed NULL pointer dereference, which should be fixed as well.

File: subsys/mgmt/mcumgr/smp.c (hunk 3 above)
Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp.c:122]: The point of this PR was not to fix everything within the smp implementation. For my use case i was getting bus faults which i want to fix. Im not maintainer of mcumgr. I could create an issue for that particular problem. Would that be okay?

Comment (mniestroj) [reply subsys/mgmt/mcumgr/smp.c:122]: I don't see much value of fixing a bus fault, when instead of **each** fixed bus fault you will end up with one buffer leaked. You are just changing one type of error (bus fault) to another one (buffer leak). It is questionable which type of error is worse, but IMO buffer leaks take more time to spot and fix than bus fault (which have a dedicated handler and nice error log on UART).

I think that those two are too closely related, so they should be fixed within single PR.

Comment (pdunaj) [reply subsys/mgmt/mcumgr/smp.c:122]: Bus fault prevents operation altogether so yes, it is easier to spot. With leak you can live as long as there is enough memory.
Anyway, let's try to understand the leak. @mniestroj , can you tell which buffer will leak exactly?

Comment (pdunaj) [reply subsys/mgmt/mcumgr/smp.c:122]: btw - where is unref done on netbuf? The function documentation refers to one being done (https://github.com/zephyrproject-rtos/zephyr/blob/d00b37c8dd19d8e519baf20ed3b9ed1bdea28620/subsys/mgmt/mcumgr/smp.c#L89).
It seems there are also other things in this file that could be cleaned up... anyway this is not the issue for this PR.

Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp.c:122]: I don't think im changing bus fault into buffer leak as smp_bt works just fine. From what i understand looking into the code very briefly. The only thing happening there would be not sending the response.

Here the response callback is initialized.
```
	int rc;

	streamer = (struct smp_streamer) {
		.mgmt_stmr = {
			.cfg = &zephyr_smp_cbor_cfg,
			.reader = &reader.r,
			.writer = &writer.enc,
			.cb_arg = zst,
		},
		.tx_rsp_cb = zephyr_smp_tx_rsp,
	};
```

Here used
```
        /* Send the response. */
        rc = streamer->tx_rsp_cb(streamer, rsp, streamer->mgmt_stmr.cb_arg);
        rsp = NULL;
        if (rc != 0) {
            break;
        }

        /* Trim processed request to free up space for subsequent responses. */
        mgmt_streamer_trim_front(&streamer->mgmt_stmr, req,
                                 smp_align4(req_hdr.nh_len));

        cmd_done_arg.err = MGMT_ERR_EOK;
        mgmt_evt(MGMT_EVT_OP_CMD_DONE, req_hdr.nh_group, req_hdr.nh_id,
                 &cmd_done_arg);
    }

    if (rc != 0 && valid_hdr) {
        smp_on_err(streamer, &req_hdr, req, rsp, rc);

        if (handler_found) {
            cmd_done_arg.err = rc;
            mgmt_evt(MGMT_EVT_OP_CMD_DONE, req_hdr.nh_group, req_hdr.nh_id,
                     &cmd_done_arg);
        }

        return rc;
    }
```

Seems like smp can handle that well.

Comment (mniestroj) [reply subsys/mgmt/mcumgr/smp.c:122]: > With leak you can live as long as there is enough memory.

There are only `CONFIG_MCUMGR_BUF_COUNT` (4 by default) buffers.

In `zephyr_smp_split_frag()` you do:
```
		frag = zephyr_smp_alloc_rsp(src, arg);
		if (!frag) {
			return NULL;
		}
```
and the caller (`zephyr_smp_tx_rsp()`) does following:
```
		frag = zephyr_smp_split_frag(&nb, zst, mtu);
		if (frag == NULL) {
			return MGMT_ERR_ENOMEM;
		}
```
If `zephyr_smp_alloc_rsp()` returned `NULL`, then `zephyr_smp_split_frag()` will also return NULL. The problem is, that then `MGMT_ERR_ENOMEM` is returned immediately and `nb` is not processed / consumed to the end. So we need to free `nb` in case `zephyr_smp_alloc_rsp()` and then `zephyr_smp_split_frag()` return NULL.

Normally `nb` is consumed by `rc = zst->zst_output(zst, frag);`. I think we should call `zephyr_smp_free_buf()` on `nb` in case of split error:
```
		frag = zephyr_smp_split_frag(&nb, zst, mtu);
		if (frag == NULL) {
			zephyr_smp_free_buf(nb);
			return MGMT_ERR_ENOMEM;
		}
```

Comment (pdunaj) [reply subsys/mgmt/mcumgr/smp.c:122]: thanks

Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp.c]: @mniestroj Updated with your suggestions, please have a look.

**Review by pdunaj — APPROVED** [review]

File: subsys/mgmt/mcumgr/smp_bt.c [hunk 4]
```diff
@@ -53,6 +54,9 @@ static ssize_t smp_bt_chr_write(struct bt_conn *conn,
 	struct net_buf *nb;
 
 	nb = mcumgr_buf_alloc();
+	if (!nb) {
+		return -MGMT_ERR_ENOMEM;
+	}
```
Comment (mniestroj) [inline subsys/mgmt/mcumgr/smp_bt.c:59]: I don't think this is right. We should return some error code that is understandable by BT GATT stack.

File: subsys/mgmt/mcumgr/smp.c [hunk 5]
```diff
@@ -117,6 +117,10 @@ zephyr_smp_split_frag(struct net_buf **nb, void *arg, uint16_t mtu)
 		frag = src;
 	} else {
 		frag = zephyr_smp_alloc_rsp(src, arg);
+		if (!frag) {
+			zephyr_smp_free_buf(src, arg);
+			return NULL;
+		}
```
Comment (mniestroj) [inline subsys/mgmt/mcumgr/smp.c:123]: I think that freeing `src` should be a responsibility of `zephyr_smp_split_frag()` caller. This is also what the example in `zephyr_smp_split_frag()` documentation says:
```
 * This function is expected to be called in a loop until the entire source
 * net_buf has been consumed.  For example:
 *
 *     struct net_buf *frag;
 *     struct net_buf *rsp;
 *     ...
 *     while (rsp != NULL) {
 *         frag = zephyr_smp_split_frag(&rsp, zst, get_mtu());
 *         if (frag == NULL) {
 *             net_buf_unref(nb);
 *             return SYS_ENOMEM;
 *         }
 *         send_packet(frag)
 *     }
```

**Review by mniestroj — CHANGES_REQUESTED** [review]

File: subsys/mgmt/mcumgr/smp_bt.c (hunk 4 above)
Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp_bt.c:59]:
``` suggestion
	if (!nb) {
		return BT_GATT_ERR(BT_ATT_ERR_WRITE_REQ_REJECTED);
	}
```
?

File: subsys/mgmt/mcumgr/smp.c (hunk 5 above)
Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp.c:123]: What should be fred here?

Comment (mniestroj) [reply subsys/mgmt/mcumgr/smp.c:123]: In `zephyr_smp_split_frag()` nothing should be freed, as it just fails to split message. The logic to free the whole message, if it cannot be split, should be caller responsibility.

Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp.c]: Changed

File: subsys/mgmt/mcumgr/smp_bt.c (hunk 4 above)
Comment (mniestroj) [reply subsys/mgmt/mcumgr/smp_bt.c]: It is definitely better. Would be great if somebody from BT could verify that this is the right error code to use.

Comment (mniestroj) [reply subsys/mgmt/mcumgr/smp_bt.c]: @Thalley suggestion on Slack was:
> Given the context I would probably return `BT_ATT_ERR_INSUFFICIENT_RESOURCES`

**Review by mniestroj — APPROVED** [review]
There is only minor comment about BT GATT error code. I am okay with other changes, thanks for that contribution!

File: subsys/mgmt/mcumgr/smp_bt.c (hunk 4 above)
Comment (emob-nordic) [reply subsys/mgmt/mcumgr/smp_bt.c]: Would update it, thanks!
