### PR TITLE
Bluetooth: Mesh: Fix solicitation PDU transmission dependency on proxy feature

### LINKED ISSUE #68726: Bluetooth: Mesh: Can't send solicitation PDU without enabling the Proxy server.
**Describe the bug**
When using the extended advertiser, the solicitation PDU can only be sent if `CONFIG_BT_MESH_GATT_SERVER` is disabled:
https://github.com/zephyrproject-rtos/zephyr/blob/cbc75f85042d2553cc28a37e20e68e04d53e024f/subsys/bluetooth/mesh/adv_ext.c#L295-L303

According to the MshPRTv1.1, the proxy solicitation feature has no dependency on the Proxy server.

**To Reproduce**
1. Enable `CONFIG_BT_MESH_PROXY_SOLICITATION` in the `mesh_shell` sample
2. Try to send a solicitation PDU using `mesh proxy solicit` shell command.

**Expected behavior**
The solicitation PDU is sent.

**Impact**
Requires an application to enable a feature (Proxy server) which it doesn't need.

### PR DESCRIPTION
**Pull request by PavelVPV**
If `CONFIG_BT_MESH_GATT_SERVER` is disabled or the advertising set doesn't support proxy adv, the solicitation PDU will not be sent. However, solicitation PDU transmission doesn't depend on the proxy feature of the device it sends. Therefore, solicatation PDU should be sent regradless of `CONFIG_BT_MESH_GATT_SERVER` option and advertiser tag.

Fixes #68726

### CODE REVIEW

File: subsys/bluetooth/mesh/adv_ext.c [hunk 1]
```diff
@@ -292,13 +292,13 @@ static void send_pending_adv(struct k_work *work)
 		}
 	}
 
-	if (!IS_ENABLED(CONFIG_BT_MESH_GATT_SERVER) ||
-	    !(ext_adv->tags & BT_MESH_ADV_TAG_BIT_PROXY)) {
+	if (IS_ENABLED(CONFIG_BT_MESH_PROXY_SOLICITATION) &&
```
Comment (alxelax) [inline subsys/bluetooth/mesh/adv_ext.c:295]: Could you elaborate what has been changed after shuffling the sequence of these two conditions? I didn't get.

Comment (PavelVPV) [reply subsys/bluetooth/mesh/adv_ext.c:295]: Git weirdly rendered the change. These 2 if statements were reordered.

**Review by alxelax — APPROVED** [review]

**Review by akredalen — APPROVED** [review]
