### PR TITLE
include: zephyr: sys: util: add common is_null_no_warn() utility function and use it to squelch warning with CONFIG_COMPILER_SAVE_TEMPS=y

### LINKED ISSUE #70390: Compiling tests/drivers/can/api shows warning
**Describe the bug**
When compiling CAN api test tests/drivers/can/api there's a warning message:

image

The issue only appears to happen when CONFIG_CAN_STATS=y

**To Reproduce**
1. west build -p -b mimxrt1064_evk tests/drivers/can/api/

**Expected behavior**
No warning messages.

**Environment (please complete the following information):**
 - Linux
 - Toolchain Zephyr-SDK 0.16.5
 - Commit SHA d921659d6a4ffa9d47896c23f9292c238c183d19 (origin/main)

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Some macros may need to check their arguments against NULL to support multiple use-cases, but NULL checks can generate warnings for a given use of those macros (where that particular argument can never be NULL).
    
This can happen if:
a) all macros are expanded (e.g. when using `CONFIG_COMPILER_SAVE_TEMPS=y`)
or
b) tracking of macro expansions are turned off (`-ftrack-macro-expansion=0`)
    
This warning can be circumvented by passing the argument to be checked to an inlined function for doing the NULL check. The compiler is still able to  optimize this out at a later stage.
    
Move the private `___is_null()` helper function introduced in d51f874158038b1bc3b087604971132ebaaeb0f8 to `include/zephyr/sys/utils.h` and rename it to `is_null_no_warn()` to facilitate reuse.

Use the function to squelch the warning in both `can.h` and `i2c.h`.

Fixes: #70390

### CODE REVIEW

**Review by yashi — APPROVED** [review]

**Review by talih0 — DISMISSED** [review]

**Comment by talih0** [comment]
only nit is that other functions in this file are using inline keyword, but the new one using ALWAYS_INLINE

File: include/zephyr/sys/util.h [hunk 1]
```diff
@@ -421,6 +421,16 @@ static inline bool is_power_of_two(unsigned int x)
 	return IS_POWER_OF_TWO(x);
 }
 
+/**
+ * @brief Is @p p equal to ``NULL``?
```
Comment (andyross) [inline include/zephyr/sys/util.h:425]: Can we add a comment here explaining that the point of this API is avoid compiler warnings when comparing values against build-time non-NULL values?  Otherwise folks like me are likely to come along and think "This is silly, let's remove it".

**Review by andyross — COMMENTED** [review]
Pedantic doc request to clarify the design intent.

Also: I buy that this resolves the warnings, but that seems fragile.  Certainly the compiler is allowed to see through the inline and issue the warning anyway.  Is there maybe a more official way of doing this?  Surely Linux must have hit this and decided on a paradigm to handle it, no?

File: include/zephyr/sys/util.h (hunk 1 above)
Comment (yashi) [reply include/zephyr/sys/util.h:425]: Given its potential widespread applicability, if we relocate this function to `sys/util.h`, we should consider renaming it to something more distinctive. This precaution helps avoid confusion and prevents the indiscriminate use of this function in every NULL check scenario.

How about:
- `check_null_macro_silence()`
- `is_null_no_warn_macro()`
- `check_null_quietly_in_macro()`

Comment (henrikbrixandersen) [reply include/zephyr/sys/util.h:425]: I'll add some additional documentation on the purpose of this.

Yes, perhaps renaming it would be a good idea too. How about `is_null_no_warn()`?

Comment (henrikbrixandersen) [reply include/zephyr/sys/util.h:425]: I have renamed the function to `is_null_no_warn()` and added more documentation. PTAL.

**Review by yashi — APPROVED** [review]

**Review by talih0 — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]
