### PR TITLE
drivers: regulator: Remove non-const usage of config struct

### LINKED ISSUE #41951: drivers: regulator: pmic: config used as non-const
**Describe the bug**

These drivers seem to treat device configuration as non-const. For example:

https://github.com/zephyrproject-rtos/zephyr/blob/7dac931e3662eb666cdabc3bf1759a7484249730/drivers/regulator/regulator_pmic.c#L292-L298

**To Reproduce**

1. Don't cast config to non-const (as it should be):
```
const struct regulator_config *config = dev->config;
```
2. Build a board that uses the driver

**Expected behavior**

Device driver should use `data` to store non-ROMable data.

**Impact**

Impacts https://github.com/zephyrproject-rtos/zephyr/pull/41918

**Logs and console output**

N/A

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA or Version used e8df8a579033be238beb774e4909d637da649f3a

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by danieldegrasse**
Config struct in pmic regulator driver was being used as a non-constant
value when an array defined at compile time was cast to a struct used at
runtime. Move this pointer to the data struct in pmic driver.

Also removes unnecessary NULL check in PMIC initialization function (since `device_is_ready` handles NULL devices correctly)

Fixes #41951

### CODE REVIEW

File: drivers/regulator/regulator_pmic.c [hunk 1]
```diff
@@ -286,14 +291,15 @@ static int disable_regulator(const struct device *dev)
...
 	/* Cast the voltage array set at compile time to the voltage range
 	 * struct
 	 */
-	config->voltages = (struct voltage_range *)config->voltage_array;
+	data->voltages = (struct voltage_range *)config->voltage_array;
 	/* Do the same cast for current limit ranges */
-	config->current_levels = (struct current_range *)config->current_array;
+	data->current_levels = (struct current_range *)config->current_array;
 	/* Check to verify we have a valid I2C device */
 	if (config->i2c_dev == NULL || !device_is_ready(config->i2c_dev)) {
```
Comment (gmarull) [inline drivers/regulator/regulator_pmic.c:304]: nit: not related, but NULL check here can be removed (device_is_ready supports NULL as an input)

**Review by gmarull — APPROVED** [review]
Thanks, LGTM

File: drivers/regulator/regulator_pmic.c (hunk 1 above)
Comment (danieldegrasse) [reply drivers/regulator/regulator_pmic.c]: Thanks for the heads up, I added a commit to this PR to fix that

**Review by mmahadevan108 — APPROVED** [review]
