### PR TITLE
drivers: spi: nxp_lpspi: Fix race condition in ISR

### LINKED ISSUE #89557: NXP LPSPI Async implementation very dodgy
**Describe the bug**
I'm on a custom imxrt1176 and noticed that LPSPI and tried to debug the experimental fpga_ice40 driver.

I realized that there's a very short `spi_write_dt` followed by quite a long `sp_write_dt`; and because the driver controls CS manually, it relies on the fact that `spi_write_dt` is blocking. It, however, did not seem to block for the second longer transfer.

I decided to do a code review of the driver combined with printf debugging and stumbled across multiple issues in `spi_nxp_lpspi.c`; to be specific, surrounding the `lpspi_isr` function:

- `lpspi_end_xfer(dev)` gets called when `spi_context_rx_len_left(ctx) == 0`, regardless of whether interrupts are still enabled or not. This can cause `lpspi_end_xfer` to be called multiple times during a single transfer, which preemptively flags the next future transfer as finished. Which is exactly what happened in my case.
  To be specific, the `RDIE` interrupt was still enabled. `RDIE` gets disabled in `lpspi_handle_rx_irq`, but no `RDF` interrupt happened yet.
- The interrupt handler calls `lpspi_end_xfer`, which in turn calls `lpspi_wait_tx_fifo_empty`. Is a blocking call inside of an ISR really intended?
- In `lpspi_end_xfer`, the `spi_context_complete` gets called **before** `lpspi_wait_tx_fifo_empty`. This means if `CONFIG_SPI_ASYNC` is on, the `spi_write` function returns **before** all bytes have physically been transmitted on the bus. Which is incompatible with the note `This function is synchronous.` on `spi_transceive, on which other drivers rely that, like in the ICE40 case, handle CS manually.

**Expected behavior**
- Interrupts return immediately without blocking
- The `lpspi_end_xfer` function only gets called once
- Once `spi_write` returns, the physical transfer on the bus is completed

**Impact**
Crashes, hangs, undefined behavior of peripherals

**Logs and console output**
If required, I can attempt to reproduce on an imxrt1176 dev board, but I don't have one on me right now.

**Environment (please complete the following information):**

 - OS: Windows
 - Toolchain: Zephyr SDK 0.17.0
 - Zephyr Git Hash: 8b1f06af052f465e7d7094a49764d6aba76b4655

### PR DESCRIPTION
**Pull request by Finomnis**
Fixes #89557.

The main architectural change is that the RX/TX halves of a transmission now signal that they are finished by disabling their interrupts.

This in turn will then be picked up further down in the ISR as the signal that the entire transmission is over.

The order of operations inside the `handle_tx_irq` had to be changed, so that the interrupt only gets disabled once both of those are fulfilled:
- no more TX data available
- physical transmission finished

Before, the IRQ got disabled while the physical transmission was not finished yet; for that to be a given we must be out of data **and** an active TX interrupt must exist. In the current code, it got disabled once we had no more data, but the TX interrupt wasn't set.

The second fix is that RX will be cleared and RX interrupts will be disabled every time we get an interrupt and we have no more data to send. Previously, this was only done if an RX interrupt was pending, which made it possible that the RX interrupts were still enabled at the end of the transmission.

### CODE REVIEW

**Comment by decsny** [comment]
@hakehuang please run full regression test on this PR

**Comment by Finomnis** [comment]
@decsny how do I do this and what hardware do I need?

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c [hunk 1]
```diff
@@ -253,6 +252,11 @@ static void lpspi_isr(const struct device *dev)
 		lpspi_handle_tx_irq(dev);
 	}
 
+	if (spi_context_rx_len_left(ctx) == 0) {
+		base->IER &= ~LPSPI_IER_RDIE_MASK;
+		base->CR |= LPSPI_CR_RRF_MASK; /* flush rx fifo */
+	}
```
Comment (decsny) [inline drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:258]: is it worth it to maybe introduce another uint8_t or something in the `struct lpspi_driver_data` to have some status flags for the transfer, to avoid the extra unnecessary peripheral bus accesses during the isr? also unrelated to this PR but the VERID major version indicating the old stalling behavior probably should be stored similarly instead of checked every isr

**Review by decsny — COMMENTED** [review]
please split into two commits, first the RX change then the TX change, and describe more clearly in the commit messages, most people will read that in the future rather than the PR description

**Comment by decsny** [comment]
> @decsny how do I do this and what hardware do I need?

I pinged Hake with that message, not directed at you. He has a hardware range to test on many different platforms

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c (hunk 1 above)
Comment (Finomnis) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:258]: Probably. Will look into it tomorrow. The biggest performance killer is probably the watermarks of zero, though.

**Comment by hakehuang** [comment]
> @hakehuang please run full regression test on this PR

@decsny , sure, will feedback once done

**Comment by hakehuang** [comment]
> > @hakehuang please run full regression test on this PR
> 
> @decsny ,  I run regression test on this PR, no issues found.

**Review by decsny — DISMISSED** [review]

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c (hunk 1 above)
Comment (Finomnis) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:258]: @decsny Question: What happens if the RX fifo does not get flushed regularly? Would the entire SPI device deadlock once the RX fifo is full and nobody empties it?

**Comment by Finomnis** [comment]
> please split into two commits, first the RX change then the TX change, and describe more clearly in the commit messages, most people will read that in the future rather than the PR description

I'm not sure how to split them, both changes are required to fix the problem. They all mesh together.

I can definitely write more detail into the commit message, though.

**Comment by Finomnis** [comment]
@decsny I added a lot of detail into the commit message. I hope it is good enough now.

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c (hunk 1 above)
Comment (Finomnis) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:258]: @decsny Yes, the answer is, the SPI device deadlocks if you don't clear the RX fifo regularly. Once it fills up, the transfer simply stops until you empty it. The fact that we disable the interrupts does not change anything; meaning, it was already being called repeatedly before this change.

**Comment by Finomnis** [comment]
Yah I think I'm at the point again where it can be merged once accepted :)

File: drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c (hunk 1 above)
Comment (decsny) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:258]: There is RXMSK bit but I don't want to mess with the masking bits, they have some unexpected effects

Comment (Finomnis) [reply drivers/spi/spi_nxp_lpspi/spi_nxp_lpspi.c:258]: As this is a bugfix PR, I'd not mix those two together. If needed, people can do optimization afterwards imo.

**Comment by Finomnis** [comment]
Bump

**Comment by Finomnis** [comment]
Bump again :) Sorry if I'm being stressful, but this is kind of being a blocker for us right now

**Comment by decsny** [comment]
> @decsny @mmahadevan108 @dleach02 Bump again :) Sorry if I'm being stressful, but this is kind of being a blocker for us right now

I can't merge it. 

Out of curiosity, why is it blocking you if you already fixed it? It needs to be in mainline ASAP for some reason?

**Comment by Finomnis** [comment]
@decsny Nah, you are right. It just feels wrong to base your product code on a temporary bugfix branch.

**Comment by Finomnis** [comment]
No changes, just rebased to newest main

**Comment by decsny** [comment]
> @decsny Nah, you are right. It just feels wrong to base your product code on a temporary bugfix branch.
> 
> I apologize and take back the urgency.

IMO you should not base the final product code on the unstable indev mainline either, it should be based on a stable release point with whatever cherry picked patches you need on top, but that's up to you

**Review by decsny — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
