### PR TITLE
Bluetooth: Host: Fix not sending Service Changed indication

### LINKED ISSUE #83178: Bluetooth GATT/SR/GAS/BV-01-C qualification test regression
**Describe the bug**
Bluetooth GATT qualification test regression after #82062 merge. This commit was indicated by git bisect as first bad commit and reverting it resolves the issue

**To Reproduce**
Execute GATT/SR/GAS/BV-01-C qualification test case with AutoPTS on nRF52

**Expected behavior**
Pass verdict

**Impact**
Bluetooth qualification is affected

### PR DESCRIPTION
**Pull request by sjanc**
gatt_unregister() clears handles if those were auto-assigned by host. This resulted in Service Changed indication not beding sent since call to sc_indicate() pass already cleared handles.

This was affecting GATT/SR/GAS/BV-01-C and GATT/SR/GAS/BV-07-C test cases.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/83178

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1743,10 +1743,18 @@ int bt_gatt_service_register(struct bt_gatt_service *svc)
...
+	uint16_t sc_end_handle;
 	int err;
 
 	__ASSERT(svc, "invalid parameters\n");
 
+	/* gatt_unregister() clears handles when those were auto-assigned
+	 * by host
+	 */
+	sc_start_handle = svc->attrs[0].handle;
+	sc_end_handle = svc->attrs[svc->attr_count - 1].handle;
```
Comment (Thalley) [inline subsys/bluetooth/host/gatt.c:1756]: Probably outside the scope of this PR, but we probably should verify that `svc->attrs != NULL` and that `svc->attr_count > 0` before doing these lines

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
This sounds like something we might want to backport e.g. to 4.0, however you'll then need to open a matching issue for it.

**Comment by jhedberg** [comment]
> This sounds like something we might want to backport e.g. to 4.0, however you'll then need to open a matching issue for it.

Hmm, I can see there's #83178 - is there a missing "Fixes ..." in the PR description for it?

**Comment by sjanc** [comment]
> This sounds like something we might want to backport e.g. to 4.0, however you'll then need to open a matching issue for it.

This regression was introduced post 4.0 release

**Review by alwa-nordic — APPROVED** [review]
