### PR TITLE
Bluetooth: shell: Fix uninitalized values for iso big create

### LINKED ISSUE #39857: [Coverity CID: 240234] Uninitialized scalar variable in subsys/bluetooth/shell/iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/c0fcd35531611bbe35376c62a9e50744d6904940/subsys/bluetooth/shell/iso.c

Category: Uninitialized variables
Function: `cmd_big_create`
Component: Bluetooth
CID: [240234](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=240234)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/c0fcd35531611bbe35376c62a9e50744d6904940/subsys/bluetooth/shell/iso.c#L436

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNINIT). ([CWE-457](http://cwe.mitre.org/data/definitions/457.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by Thalley**
A few values were not initialized when creating a
big in the iso shell.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

fixes https://github.com/zephyrproject-rtos/zephyr/issues/39857

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]

**Review by asbjornsabo — APPROVED** [review]
LGTM

File: subsys/bluetooth/shell/iso.c [hunk 1]
```diff
@@ -417,6 +417,8 @@ static int cmd_big_create(const struct shell *sh, size_t argc, char *argv[])
 	param.bis_channels = bis_channels;
 	param.num_bis = BIS_ISO_CHAN_COUNT;
 	param.encryption = false;
+	param.packing = BT_ISO_PACKING_SEQUENTIAL;
```
Comment (joerchan) [inline subsys/bluetooth/shell/iso.c:420]: In order to avoid the same problem when you add something else, maybe memset or initialize the entire struct to zero?
Would _INIT macros be helpful?

Comment (Thalley) [reply subsys/bluetooth/shell/iso.c:420]: I did consider the memset approach. I can add that if you like

Didn't consider the _INIT macro approach, but definitely something that could also make sense. 

Please let me know if you want either approach, or if this is good enough as is.

Comment (joerchan) [reply subsys/bluetooth/shell/iso.c:420]: This was just a suggestion. I'm fine with leaving it as is.

Comment (Thalley) [reply subsys/bluetooth/shell/iso.c:420]: I'll try to keep that in mind, and possibly add that later :)
