### PR TITLE
Bluetooth: Host: Add ISO tx check for LOG_WRN in le_init_iso

### LINKED ISSUE #68931: Bluetooth: ISO: Incorrect warning for ISO Sync Receiver
**Describe the bug**
If only the ISO sync receiver is enabled and the `BT_HCI_OP_LE_READ_BUFFER_SIZE_V2` command is not available, then that is not really an issue, as the buffers from `BT_HCI_OP_LE_READ_BUFFER_SIZE_V2` is only from host to controller, and the ISO Sync Receiver will never send ISO data. 

The warning in `le_init_iso` 
```
bt_hci_core: Read Buffer Size V2 command is not supported.No ISO buffers will be available
```

Should not be logged in this case. 

**To Reproduce**
Build and run https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/broadcast_audio_sink on an nRF52* board (including the BSIM board). and see the warning log.

**Expected behavior**
Expect no log. 

**Impact**
Minor

**Logs and console output**
See above

**Environment (please complete the following information):**
 - Commit SHA or Version used: e72ac4b0917e259ae7ddda2dee5e25c5ea6c0978

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
The warning should only apply for configurations where the device may actually send ISO data (e.g. not the ISO sync receiver).

fixes https://github.com/zephyrproject-rtos/zephyr/issues/68931

### CODE REVIEW

**Review by kruithofa — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -3266,8 +3266,10 @@ static int le_init_iso(void)
 
 		net_buf_unref(rsp);
 	} else if (IS_ENABLED(CONFIG_BT_CONN)) {
-		LOG_WRN("Read Buffer Size V2 command is not supported."
-			"No ISO buffers will be available");
+		if (IS_ENABLED(CONFIG_BT_ISO_UNICAST) || IS_ENABLED(CONFIG_BT_ISO_BROADCASTER)) {
```
Comment (jori-nordic) [inline subsys/bluetooth/host/hci_core.c:3269]: should we need a helper kconfig for TX? I see these two are in a bunch of places.

**Review by jori-nordic — APPROVED** [review]

File: subsys/bluetooth/host/hci_core.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/host/hci_core.c:3269]: I agreed, and I thought we actually had that, but I couldn't find it. On the bright side, I just did: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/Kconfig#L121-L125

I'll post an update

Comment (Thalley) [reply subsys/bluetooth/host/hci_core.c:3269]: https://github.com/zephyrproject-rtos/zephyr/pull/68968
