### PR TITLE
sys: util: cast input of KB() to size_t for large number

### LINKED ISSUE #27164: tests/lib/mem_alloc failed on up_squared board.
**To Reproduce**
1.  west build -b up_squared -p auto tests/lib/mem_alloc/  -DCONF_FILE=prj_newlib.conf
2.  west flash ~/up_squared.sh
3.  see error

**Logs and console output**
*** Booting Zephyr OS build zephyr-v2.3.0-1301-g469f53c21010  ***
Running test suite test_c_lib_dynamic_memalloc

START - test_malloc
ASSERTION FAIL [((partition->start + partition->size) <= (0 + 2147483648))] @ WEST_TOPDIR/zephyr/arch/x86/core/x86_mmu.c:1123
region at 02959000[18446744071518711808] end at ffffffff80000000 extends beyond system ram end 0x80000000
E: RAX: 0x0000000000000004 RBX: 0x0000000000d1bed8 RCX: 0x0000000000000001 RDX: 0x0000000000000046
E: RSI: 0x0000000000000463 RDI: 0x0000000000115279 RBP: 0x0000000000d1e000 RSP: 0x0000000002143dc8
E:  R8: 0x0000000000000001  R9: 0x0000000000000030 R10: 0x0000000000104731 R11: 0x0000000000000000
E: R12: 0x8000000000000007 R13: 0x0000000000d1e000 R14: 0x000000000000000c R15: 0x0000000000d1c400
E: RSP: 0x0000000002143dc8 RFLAGS: 0x0000000000000046 CS: 0x0018 CR3: 0x000000000011a000
E: RIP: 0x0000000000101d9f
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x0000000000d1cee0 (main)
E: Halting system

**Environment (please complete the following information):**
 - OS: fedora28
 - Toolchain: zephyr-sdk-0.11.4
 - Commit ID: 469f53c210

### PR DESCRIPTION
**Pull request by dcpleung**
Numbers in C macros are treated as signed integer. This causes
issues when using macro KB(x). If the result is larger than
(2^31 - 1), it is treated as a negative number downstream.
For example, the RAM size of up_squared is 2GB. The result of
KB(CONFIG_SRAM_SIZE) should be 2147483648, but due to being
casted as signed, the result is instead -2147483648. Any
calculations using this would be incorrectly. Fix it by
casting x in KB(x) to size_t first.

Fixes #27164

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

File: include/sys/util.h [hunk 1]
```diff
@@ -280,7 +280,11 @@ uint8_t u8_to_dec(char *buf, uint8_t buflen, uint8_t value);
 #endif /* !_ASMLANGUAGE */
 
 /** @brief Number of bytes in @p x kibibytes */
+#ifndef _LINKER
```
Comment (jukkar) [inline include/sys/util.h:283]: Why this ifdef, why not cast always to size_t?

Comment (dcpleung) [reply include/sys/util.h:283]: Linker scripts are also using this macro and they would fail with the cast.

Comment (jukkar) [reply include/sys/util.h:283]: Could this be documented here, it is not obvious why there is this check.
I have noticed that at least for me it is easier to read `#ifdef _LINKER` instead of the negated one, so I suggest the cases to be switched.

Comment (dcpleung) [reply include/sys/util.h]: Done

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
