### PR TITLE
net: dns: Allow using resolver and responder at the same time

### LINKED ISSUE #72553: mDNS Resolver and mDNS Responder cannot be used simultaneously due to both attempting to bind port 5353
**Describe the bug**
The Networking subsystem has support for mDNS, through the mDNS Resolver (part of more general DNS Resolver) and the mDNS Repsonder (specifically mDNS). Each of these work individually, but the two cannot be used together. This is due to both Resolver and Responder trying to bind the same port 5353 independently. Whichever one attempts the bind after the other (mDNS Responder) fails as the port is already in use.

It should be possible to enble the mDNS Resolver and mDNS Responder simultaneously.

- What target platform are you using?

  - Target platform is a custom board based on the STM32H723VGT6
 
- What have you tried to diagnose or workaround this issue?
  - Enabling logging for mDNS Responder (`CONFIG_MDNS_RESPONDER_LOG_LEVEL_DBG`) shows:
`<err> net_ctx: Port 5353 is in use!`
`<dbg> net_mdns_responder: bind_ctx: (main): Cannot bind to mDNS IPv4 port (-112)`

  - Debugging the networking subsystem shows that during initialisation:
    1) The DNS Resolver binds port 5353 (`dns_init_solver()` -> `dns_resolve_init_default()` -> `dns_resolve_init()` -> `dns_resolve_init_locked()` -> `net_context_bind()`)
    2) The mDNS Responder attempts to bind port 5353 (`mdns_responder_init()` -> `init_listener()` -> `bind_ctx()` -> `net_context_bind()`) but fails with `-EADDRINUSE` (112) as the port is already bound.

**To Reproduce**
1. `cd zephyrproject`
2. `west build -b <BOARD> -d build_mdns_sample zephyr/samples/net/mdns_responder/ -- -DCONFIG_DNS_RESOLVER=y -DCONFIG_MDNS_RESOLVER=y -DCONFIG_DNS_SERVER_IP_ADDRESSES=y -DCONFIG_CONSOLE=y -DCONFIG_LOG=y -DCONFIG_MDNS_RESPONDER_LOG_LEVEL_DBG=y` (plus any options needed for logging backend)
3. Flash target and run application

**Expected behavior**
mDNS Resolver and mDNS Responder should be able to co-exist. The port should probably only be bound once, with incoming traffic dispatched to Resolver or Responder handlers as appropriate, rather than the two subsystems existing independently and both attempting to bind the port.

**Impact**
Showstopper for applications requiring full mDNS functionality (Resolver and Responder)

**Logs and console output**
```
*** Booting Zephyr OS build v3.6.0 ***
[00:00:00.003,000] <inf> net_config: Initializing network
[00:00:00.003,000] <inf> net_config: IPv4 address: 192.0.2.1
[00:00:00.003,000] <dbg> net_mdns_responder: init_listener: (main): Setting mDNS listener to 1 interface
[00:00:00.006,000] <err> net_ctx: Port 5353 is in use!
[00:00:00.006,000] <dbg> net_mdns_responder: bind_ctx: (main): Cannot bind to mDNS IPv6 port (-112)
[00:00:00.006,000] <err> net_ctx: Port 5353 is in use!
[00:00:00.006,000] <dbg> net_mdns_responder: bind_ctx: (main): Cannot bind to mDNS IPv4 port (-112)
[00:00:00.006,000] <wrn> net_mdns_responder: Cannot start mDNS responder
```

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain Zephyr SDK v0.16.3
 - Commit SHA or Version used: Zephyr v3.6

### PR DESCRIPTION
**Pull request by jukkar**
This allows user to have both mDNS resolver and responder enabled at the same time.

Fixes #72553

### CODE REVIEW

**Comment by jukkar** [comment]
@besmarsh, I have a fix proposal for the mDNS resolver/responder co-existence issue you created. Would you be able to try it and report if it works for you or not?

**Comment by besmarsh** [comment]
> @besmarsh, I have a fix proposal for the mDNS resolver/responder co-existence issue you created. Would you be able to try it and report if it works for you or not?

For sure, I should be able to test it in the next couple of days.

File: subsys/net/lib/dns/dispatcher.c [hunk 1]
```diff
@@ -0,0 +1,304 @@
...
+		goto unlock;
+	}
+
+	addrlen = (family == AF_INET) ? sizeof(struct sockaddr_in) :
+		sizeof(struct sockaddr_in6);
+
+	dns_data = net_buf_alloc(&dns_msg_pool, dispatcher->buf_timeout);
+	if (!dns_data) {
+		ret = DNS_EAI_MEMORY;
+		goto free_buf;
```
Comment (rlubos) [inline subsys/net/lib/dns/dispatcher.c:148]: It's rather harmless given there's a pointer check under `free_buf`, but since the allocation failed we could jump directly to `unlock` label here.

File: subsys/net/lib/dns/dispatcher.c [hunk 2]
```diff
@@ -0,0 +1,304 @@
...
+					     addr, addrlen,
+					     dns_data, data_len);
+		} else if (dispatcher->pair) {
+			if (dispatcher->pair->type == DNS_SOCKET_RESPONDER) {
+				ret = dispatcher->pair->cb(dispatcher->pair->ctx, sock,
+							   addr, addrlen,
+							   dns_data, data_len);
+			} else {
+				/* The pair must be a resolver */
+				CHECKIF(dispatcher->pair->type != DNS_SOCKET_RESOLVER) {
```
Comment (rlubos) [inline subsys/net/lib/dns/dispatcher.c:70]: Perhaps we should also check for errors like this in `dns_dispatcher_register()`? So that you don't need the actual communication going on to figure out something is wrong.

**Review by rlubos — COMMENTED** [review]
Looks pretty good

File: subsys/net/lib/dns/dispatcher.c (hunk 2 above)
Comment (jukkar) [reply subsys/net/lib/dns/dispatcher.c:70]: Indeed, good point, will change this.

Comment (jukkar) [reply subsys/net/lib/dns/dispatcher.c:70]: Actually we already check in `dns_dispatcher_register()` that the dispatcher type is not the same, so this checkif is not really needed.

**Review by rlubos — DISMISSED** [review]

**Review by pdgendt — DISMISSED** [review]

**Comment by jukkar** [comment]
* While testing, I noticed an issue when wrong context was used in dispatcher callback

**Review by rlubos — DISMISSED** [review]

**Review by besmarsh — COMMENTED** [review]
Tested and confirmed to work with my custom application. I've left some minor code review comments. Thanks @jukkar for the quick turnaround on this fix!

File: subsys/net/lib/dns/mdns_responder.c [hunk 3]
```diff
@@ -845,32 +776,33 @@ static int init_listener(void)
...
+			v4_ctx[i].fds[j].fd = -1;
+		}
+
 		v4 = get_socket(AF_INET);
 		if (v4 < 0) {
-			NET_ERR("Cannot get %s socket out of %d. Max sockets is %d",
-				"IPv4", MAX_IPV4_IFACE_COUNT, CONFIG_NET_MAX_CONTEXTS);
+			NET_ERR("Cannot get %s socket (%d %s interfaces). Max sockets is %d",
+				"IPv4", MAX_IPV4_IFACE_COUNT,
+				"IPv4", CONFIG_NET_MAX_CONTEXTS);
```
[the remark this answers is not in the document]
Comment (jukkar) [reply subsys/net/lib/dns/mdns_responder.c:805]: Yes, we avoid having two string stored to flash by sharing the general format for it.

**Comment by jukkar** [comment]
* Updated according to comments

**Review by besmarsh — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
