### PR TITLE
drivers: gpio stm32 driver also get the pin state

### LINKED ISSUE #48007: tests: gpio driver fails in pin_get_config
**Describe the bug**
When running the testcase  tests/drivers/gpio/gpio_basic_api/ on various stm32 boards, the sequence pin_get_config fails because
flag set differs from flag get. 

At least  on the following target boards : stm32f3_disco,  nucleo_g474re, nucleo_g071rb,  nucleo l152r, nucleo_wl55jc  

During the gpio_stm32_config, the _flags_ is set with value  = 0xa0000                                                                                                                                    
During the gpio_stm32_get_config, the _flags_ is get at value = 0x20000b74 

Moreover it seems that :
- the `gpio_stm32_pincfg_to_flags` and `gpio_stm32_flags_to_conf`  functions have parameters that do not match exactly the 32bit values. (gpio_flags_t is of type uint32_t)
- LL_GPIO_GetPinPull, LL_GPIO_GetPinOutputType, LL_GPIO_GetPinMode  returned values are uint32_t assigned to unsigned int mode, otype, pupd
- When disabling the CONFIG_GPIO_GET_CONFIG (with CONFIG_GPIO_GET_CONFIG=n),  a compilation error occurs:
```
in function `gpio_pin_get_config':
/local/home/frq09495/zephyrproject/zephyr/build/zephyr/include/generated/syscalls/gpio.h:111: undefined reference to `z_impl_gpio_pin_get_config'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**To Reproduce**
1. west build -p auto  -b stm32f3_disco tests/drivers/gpio/gpio_basic_api
3. west flash

**Expected behavior**
test PASSED 

**Impact**
test campaign failure

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.1.0-2346-g5b5ccee821cf  ***
Running TESTSUITE gpio_basic_test
===================================================================
START - test_gpio_port
Validate device GPIOC
Check GPIOC output 6 connected to input 7
OUT 6 to IN 7 linkage works
- bits_physical
- pin_physical
- check_raw_output_levels
- check_logic_output_levels                                                                                                                     
- check_input_levels                                                                                                                            
- bits_logical                                                                                                                                  
- check_pulls                                                                                                                                   
                                                                                                                                                
    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:652: pin_get_config: (flags_set not equal to )
flags are different                                                                                                                             
 FAIL - test_gpio_port in 0.37 seconds
```


**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) ubuntu
 - Toolchain (e.g Zephyr SDK, ...) : zephyr-sdk-0.14.0
 - Commit SHA : 60271524087bb4382c8b4db0f2e17a87e4120065

**Additional context**
PR : https://github.com/zephyrproject-rtos/zephyr/pull/43225

### PR DESCRIPTION
**Pull request by FRASTM**
In the stm32 gpio driver, the gpio_stm32_get_config function
also returns the pin state HIGH or LOW) to match gpio_pin_get_config

The gpio_stm32_get_config function is modified to include the pin state HIGH/LOW  to the flags variable
This variable is of type gpio_flags_t.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/48007

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
Removing the CONFIG_GPIO_GET_CONFIG for the stm32F1 serie. The GPIO port structure of that serie has no pull up/down.
The pin_get_config() function will not give a correct config for the pin.
Actually the stm32CUbe functions  LL_GPIO_SetPinPull and LL_GPIO_GetPinPull  exist but are accessing the  (ODR)  Output register (instead of a Pull up/down since it does no exist !).

**Review by cfriedt — DISMISSED** [review]

**Comment by FRASTM** [comment]
Requires PR https://github.com/zephyrproject-rtos/zephyr/pull/47923 for check PASSED with twister tests/drivers/gpio/gpio_basic_api on nucleo_f103rb

**Comment by FRASTM** [comment]
rebase on 5897de1e535816247e309348cbe29760361a28b8

File: drivers/gpio/gpio_stm32.c [hunk 1]
```diff
@@ -579,12 +585,13 @@ static int gpio_stm32_get_config(const struct device *dev,
 	otype = LL_GPIO_GetPinOutputType(gpio, pin_ll);
 	pupd = LL_GPIO_GetPinPull(gpio, pin_ll);
 	mode = LL_GPIO_GetPinMode(gpio, pin_ll);
+	set = LL_GPIO_IsOutputPinSet(gpio, pin_ll);
```
Comment (erwango) [inline drivers/gpio/gpio_stm32.c]: Pin could be "set" on IDR as well. Please use something more explicit, like 'out_set', 'oset', 'output_set', ...

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/gpio/gpio_stm32.c (hunk 1 above)
Comment (FRASTM) [reply drivers/gpio/gpio_stm32.c]: using a structure instead

File: drivers/gpio/gpio_stm32.h [hunk 2]
```diff
@@ -206,6 +206,18 @@
...
 
+#ifdef CONFIG_GPIO_GET_CONFIG
+/**
+ * @brief structure of a GPIO pin (stm32 LL values) use to get the configuration
+ */
+struct gpio_stm32_pin {
+	unsigned int type; /* LL_GPIO_OUTPUT_PUSHPULL or LL_GPIO_OUTPUT_OPENDRAIN */
+	unsigned int pupd; /* LL_GPIO_PULL_NO or LL_GPIO_PULL_UP or LL_GPIO_PULL_DOWN */
+	unsigned int mode; /* LL_GPIO_MODE_INPUT or LL_GPIO_MODE_OUTPUT or other */
+	unsigned int state; /* 1 (high level) or 0 (low level) */
```
Comment (erwango) [inline drivers/gpio/gpio_stm32.h:217]:
```suggestion
	unsigned int out_state; /* 1 (high level) or 0 (low level) */
```
?

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/gpio/gpio_stm32.h (hunk 2 above)
Comment (FRASTM) [reply drivers/gpio/gpio_stm32.h]: change the name of the element in the `gpio_stm32_pin` structure

File: tests/drivers/gpio/gpio_basic_api/boards/nucleo_f103rb.conf [hunk 3]
```diff
@@ -0,0 +1 @@
+CONFIG_GPIO_GET_CONFIG=n
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply tests/drivers/gpio/gpio_basic_api/boards/nucleo_f103rb.conf:1]: The stm32f1 soc cannot force the CONFIG_GPIO_GET_CONFIG to 'n' through a kconfig
Could we then have  
```
#if defined( CONFIG_GPIO_GET_CONFIG) && defined(CONFIG_SOC_SERIES_STM32F1X)
#error stm32F1x does not support pin_get_config()
#endif
```

[the remark this answers is not in the document]
Comment (erwango) [reply tests/drivers/gpio/gpio_basic_api/boards/nucleo_f103rb.conf:1]: > The stm32f1 soc cannot force the CONFIG_GPIO_GET_CONFIG to 'n' through a kconfig Could we then have
> 
> ```
> #if defined( CONFIG_GPIO_GET_CONFIG) && defined(CONFIG_SOC_SERIES_STM32F1X)
> #error stm32F1x does not support pin_get_config()
> #endif
> ```

Generating an error is not required, see API implementation. Not supporting this API call is legit:
https://github.com/zephyrproject-rtos/zephyr/blob/352fde1271c568fa24cb48b4aed20f97b25945b1/include/zephyr/drivers/gpio.h#L881-L883
If not implemented, caller will get `-ENOSYS` as a result. This is ok.

**Comment by FRASTM** [comment]
add a flag CONFIG_SOC_SERIES_STM32F1X to avoid defining the pin_get_config function 
change the tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c  to handle the gpio_pin_get_config correctly

File: drivers/gpio/gpio_stm32.c [hunk 4]
```diff
@@ -657,7 +657,7 @@ static int gpio_stm32_manage_callback(const struct device *dev,
 
 static const struct gpio_driver_api gpio_stm32_driver = {
 	.pin_configure = gpio_stm32_config,
-#ifdef CONFIG_GPIO_GET_CONFIG
+#if defined(CONFIG_GPIO_GET_CONFIG) && !defined(CONFIG_SOC_SERIES_STM32F1X)
 	.pin_get_config = gpio_stm32_get_config,
 #endif /* CONFIG_GPIO_GET_CONFIG */
```
Comment (erwango) [inline drivers/gpio/gpio_stm32.c:662]: This would be better in a dedicated commit

**Comment by FRASTM** [comment]
adding a commit for stm32F1 serie : 168fbc8a22e38ebc7029277061eeb1cde5a8c24a

**Review by erwango — DISMISSED** [review]

**Review by erwango — APPROVED** [review]

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c [hunk 5]
```diff
@@ -644,7 +644,7 @@ static int pin_get_config(void)
 	zassert_equal(rc, 0, "pin configure failed");
 
 	rc = gpio_pin_get_config(dev, PIN_OUT, &flags_get);
-	if (rc == -ENOTSUP) {
+	if (rc == -ENOSYS) {
```
Comment (cfriedt) [inline tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:647]: I believe this should not be changed.

E.g. see
https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/drivers/gpio/gpio_get_direction/src/main.c#L43

**Review by cfriedt — DISMISSED** [review]

File: tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c (hunk 5 above)
Comment (erwango) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:647]: > I believe this should not be changed.
> 
> E.g. see https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/drivers/gpio/gpio_get_direction/src/main.c#L43

@cfriedt, it seems the line you're pointing is not in line with gpio header:
https://github.com/zephyrproject-rtos/zephyr/blob/6cfb18686e1c494d0011aec87bbf24ab530d3a34/include/zephyr/drivers/gpio.h#L881-L882

Comment (cfriedt) [reply tests/drivers/gpio/gpio_basic_api/src/test_gpio_port.c:647]: Oh weird - OK - can you make an additional commit to fix the test file that I pointed to? Thanks for pointing that out.

**Review by cfriedt — APPROVED** [review]
