### PR TITLE
kernel: userspace: aligned memory allocation for dynamic objects

### LINKED ISSUE #17893: dynamic threads don't work on x86 in some configurations
Dynamic threads are an optional userspace feature; if CONFIG_DYNAMIC_OBJECTS is enabled, a thread may call `k_object_alloc(K_OBJ_THREAD)` which returns a usable `struct k_thread` pointer. This pointer is no more than 4-byte aligned; Zephyr does not have a heap which allows returning aligned pointers.

On x86, thread->arch may have members which require alignment. Currently this happens if CONFIG_EAGER_FP_SHARING or CONFIG_LAZY_FP_SHARING is turned on, as thread->arch will then contain structs requiring alignment because they get passed to x86 CPU instructions to save/restore fp context. Threads that are instantiated statically will be aligned properly, but likely not if allocated dynamically, resulting in a CPU exception when context is attempted to be saved/restored.

A quick survey of arches reveals that only x86 threads have this problem.

We may need to find an alternate storage area. Floating point register stuff could possibly be stored in thread-local area, next to where we put errno; its contents are only significant when the thread is swapped out, and hence a user thread being able to touch this is not of concern.

### LINKED ISSUE #29589: Creating a k_thread and k_sem as runtime instantiated kernel object causes general protection fault
**Describe the bug**
When I try to create a `k_thread` and a `k_sem` using a runtime instantiated a kernel object in Userspace (CONFIG_USERSPACE and CONFIG_DYNAMIC_OBJECTS are enabled) Zephyr throws a General protection fault. I created a minimal reproducible example, but I can not figure out what I did wrong. The crash occurs when `k_thread_create` is called. However, it does not occur unless I create a `k_sem` object using `k_object_alloc(K_OBJ_SEM)` beforehand.

I only tried this on the up squared board, since qemu is stuck while booting.

**To Reproduce**
1. Download [Error_Minimal.zip](https://github.com/zephyrproject-rtos/zephyr/files/5446746/Error_Minimal.zip) and unzip
1. mkdir build; cd build
2. cmake -DBOARD=up_squared ..
3. make
4. run on up squared board

**Expected behavior**
Both Thread and Semaphore should be created and the thread should print a counter message every 250ms.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.4.0-1054-g1ae2b7cad9db  ***
created semaphore
[00:00:00.084,000] <err> os: General protection fault (code 0x0)
[00:00:00.084,000] <err> os: RAX: 0x0000000000000000 RBX: 0x00000000001141f8 RCX: 0x000000000000000c RDX: 0x000000000112f000
[00:00:00.084,000] <err> os: RSI: 0x000000000112f000 RDI: 0x00000000001141f8 RBP: 0x000000000112ffe8 RSP: 0x0000000001536e98
[00:00:00.084,000] <err> os:  R8: 0x00000000001141f8  R9: 0x000000000193a000 R10: 0x000000000010f280 R11: 0x000000000000001c
[00:00:00.084,000] <err> os: R12: 0x0000000000000000 R13: 0x0000000000000000 R14: 0x0000000000100212 R15: 0x0000000000000000
[00:00:00.084,000] <err> os: RSP: 0x0000000001536e98 RFLAGS: 0x0000000000010202 CS: 0x0018 CR3: 0x000000000193b000
[00:00:00.084,000] <err> os: RIP: 0x000000000000117f
[00:00:00.084,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.084,000] <err> os: Current thread: 0x0000000000113a80 (unknown)
[00:00:00.181,000] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
-  Board: Up Squared
 - Toolchain Zephyr SDK
 - Commit SHA: 1ae2b7cad9db8a429072c6ee6f1532c7944f74e4

**Additional context**
Here is the minimal example, so it is not required to download the zip to check the code:
```cpp
#include <zephyr.h>
#include <sys/printk.h>
#include <kernel.h>
#include <string.h>
#include <stdlib.h>

#define MY_STACK_SIZE 0x1000
#define MY_PRIORITY 5

K_THREAD_STACK_DEFINE(my_stack_area, MY_STACK_SIZE);

void my_entry_point(void* a, void* b, void* c) {
    int counter = 0;
    while (true) {
        printk("counter %i\n", counter);
        ++counter;
        k_msleep(250);
    }
}

void main(void)
{
    k_thread_system_pool_assign(k_current_get());
    struct k_sem* my_sem = (struct k_sem*)k_object_alloc(K_OBJ_SEM);

    if(NULL == my_sem){
        printk("failed allocating semaphore object\n");
        return;
    }
    k_sem_init(my_sem, 0, CONFIG_SEM_VALUE_MAX);
    printk("created semaphore\n");

    struct k_thread* my_thread = (struct k_thread*)k_object_alloc(K_OBJ_THREAD);

    if (NULL == my_thread){
        printk("failed allocating thread object\n");
        return;
    }
    k_thread_create(my_thread, my_stack_area,
                                 K_THREAD_STACK_SIZEOF(my_stack_area),
                                 my_entry_point,
                                 NULL, NULL, NULL,
                                 MY_PRIORITY,
                                 K_INHERIT_PERMS | K_USER,
                                 K_NO_WAIT);

    printk("created thread\n");
    k_sleep(K_FOREVER);
}
```

### LINKED ISSUE #29629: Creating a k_thread as runtime instantiated kernel object using k_malloc causes general protection fault
**Describe the bug**
When I try to create a `k_thread` using a runtime instantiated a kernel object in Kernel Mode using k_malloc Zephyr throws a General protection fault on thread creation. According to #29589 this should be possible. I tried the same using `k_calloc`, which causes the same error for me. Is there anything else that has to be done before calling `k_thread_create`?

I only tried this on the up squared board, since qemu is stuck while booting.

**To Reproduce**
1. Download [Error_Minimal.zip](https://github.com/zephyrproject-rtos/zephyr/files/5457087/Error_Minimal.zip) and unzip
1. mkdir build; cd build
2. cmake -DBOARD=up_squared ..
3. make
4. run on up squared board

**Expected behavior**
It should create the Thread without throwing a protection fault.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.4.0-1054-g1ae2b7cad9db  ***
allocated thread object
[00:00:00.018,000] <err> os: General protection fault (code 0x0)
[00:00:00.018,000] <err> os: RAX: 0x0000000000000000 RBX: 0x0000000000108db8 RCX: 0x0000000000100000 RDX: 0x0000000000d12ff8
[00:00:00.018,000] <err> os: RSI: 0x0000000000d12000 RDI: 0x0000000000108db8 RBP: 0x0000000000108db8 RSP: 0x0000000000d17f28
[00:00:00.018,000] <err> os:  R8: 0x0000000000000000  R9: 0x0000000000000000 R10: 0x0000000000000000 R11: 0x000000000000000f
[00:00:00.018,000] <err> os: R12: 0x0000000000d13000 R13: 0x0000000000000000 R14: 0x0000000000000000 R15: 0x0000000000000000
[00:00:00.018,000] <err> os: RSP: 0x0000000000d17f28 RFLAGS: 0x0000000000010206 CS: 0x0018 CR3: 0x0000000001124000
[00:00:00.018,000] <err> os: RIP: 0x000000000000117f
[00:00:00.018,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:00.018,000] <err> os: Current thread: 0x0000000000108900 (unknown)
[00:00:00.115,000] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: Linux
-  Board: Up Squared
 - Toolchain Zephyr SDK
 - Commit SHA: 1ae2b7cad9db8a429072c6ee6f1532c7944f74e4

**Additional context**
Here is the minimal example, so it is not required to download the zip to check the code:
```cpp
#include <zephyr.h>
#include <sys/printk.h>
#include <kernel.h>
#include <string.h>
#include <stdlib.h>

#define MY_STACK_SIZE 0x1000
#define MY_PRIORITY 5

K_THREAD_STACK_DEFINE(my_stack_area, MY_STACK_SIZE);

void my_entry_point(void* a, void* b, void* c) {
    int counter = 0;
    while (true) {
        printk("counter %i\n", counter);
        ++counter;
        k_msleep(250);
    }
}

void main(void)
{
    struct k_thread* my_thread = (struct k_thread*)k_malloc(sizeof(struct k_thread));

    if (NULL == my_thread){
        printk("failed allocating thread object\n");
        return;
    }

    printk("allocated thread object\n");

    k_thread_create(my_thread, my_stack_area,
                                 K_THREAD_STACK_SIZEOF(my_stack_area),
                                 my_entry_point,
                                 NULL, NULL, NULL,
                                 MY_PRIORITY,
                                 0,
                                 K_NO_WAIT);

    printk("created thread\n");
    k_sleep(K_FOREVER);
}
```

### PR DESCRIPTION
**Pull request by dcpleung**
This allows allocating dynamic kernel objects with memory alignment
requirements. The first candidate is for thread objects for x86
and x86_64 where saving/restoring SSE/FPU registers require strict
alignment.
    
Fixes #29589
Fixes #29629

### CODE REVIEW

File: kernel/userspace.c [hunk 1]
```diff
@@ -156,6 +156,50 @@ static size_t obj_size_get(enum k_objects otype)
 	return ret;
 }
 
+static size_t obj_align_get(enum k_objects otype)
+{
+	size_t ret;
+
+	switch (otype) {
+	case K_OBJ_THREAD:
+		if (IS_ENABLED(CONFIG_X86_64)) {
```
Comment (andrewboie) [inline kernel/userspace.c:165]: I don't want arch-specific stuff like this in the core kernel.

Define some optional ARCH_THREAD_OBJECT_ALIGNMENT in arch.h as needed and use that.

Comment (dcpleung) [reply kernel/userspace.c]: Updated to do what you suggested instead.

**Comment by cfriedt** [comment]
Looks like there is some potential conflict with #30363 which has been open for a while in preparation for dynamic pthtread stacks (#29029, which has been there for quite a long time too).

@dcpleung - I wonder if this ticket could focus more on dynamic kobject creation while #30363 could focus more on allocation.

Please let me know if you can think of a better alternative.

**Comment by dcpleung** [comment]
> Looks like there is some potential conflict with #30363 which has been open for a while in preparation for dynamic pthtread stacks (#29029, which has been there for quite a long time too).
> 
> @dcpleung - I wonder if this ticket could focus more on dynamic kobject creation while #30363 could focus more on allocation.
> 
> Please let me know if you can think of a better alternative.

Once your PR is merged, I can rebase this on top of your changes.

File: kernel/mempool.c [hunk 2]
```diff
@@ -8,7 +8,7 @@
 #include <string.h>
 #include <sys/math_extras.h>
 
-void *z_heap_malloc(struct k_heap *heap, size_t size)
+void *z_heap_aligned_malloc(struct k_heap *heap, size_t align, size_t size)
```
Comment (nashif) [inline kernel/mempool.c:11]: can we make this static?

Comment (dcpleung) [reply kernel/mempool.c:11]: Waiting for #30363 to be merged...

**Review by nashif — APPROVED** [review]

File: kernel/include/kernel_internal.h [hunk 3]
```diff
@@ -46,6 +46,22 @@ extern char *z_setup_new_thread(struct k_thread *new_thread,
...
+ * in this way should be freed with k_free().
+ *
+ * If called from an ISR, the k_malloc() system heap will be used if it exists.
+ *
+ * @param align Required memory alignment
+ * @param size Memory allocation size
+ * @return A pointer to the allocated memory, or NULL if there is insufficient
+ * RAM in the pool or there is no pool to draw memory from
+ */
+void *z_thread_aligned_malloc(size_t align, size_t size);
```
Comment (cfriedt) [inline kernel/include/kernel_internal.h:63]: It might be a bit more consistent to name it aligned_alloc rather than aligned_malloc, just for consistency.

File: kernel/mempool.c [hunk 4]
```diff
@@ -98,7 +93,7 @@ void k_thread_system_pool_assign(struct k_thread *thread)
 #define _SYSTEM_HEAP	NULL
 #endif
 
-void *z_thread_malloc(size_t size)
+void *z_thread_aligned_malloc(size_t align, size_t size)
```
Comment (cfriedt) [inline kernel/mempool.c:96]: It might be a bit more consistent to name it aligned_alloc rather than aligned_malloc, just for consistency.

File: include/sys/kobject.h [hunk 5]
```diff
@@ -267,12 +267,37 @@ __syscall void *k_object_alloc(enum k_objects otype);
...
+ * in the returned z_object's 'name' member) to k_object_free().
+ *
+ * @param size Size of the allocated object
+ * @return NULL on insufficient memory
+ * @return A pointer to the associated z_object that is installed in the
+ *	kernel object tables
+ */
+static inline struct z_object *z_dynamic_object_create(size_t size)
+{
+	return z_dynamic_object_aligned_create(1, size);
```
Comment (cfriedt) [inline include/sys/kobject.h:299]: I think elsewhere that `sizeof(void*)` is used in place of an unspecified alignment because it's a reasonable safe default alignment.

**Review by cfriedt — CHANGES_REQUESTED** [review]
Looks good - just a slight change request to have consistent naming. Are any additional tests required?

**Comment by npitre** [comment]
On Tue, 12 Jan 2021, Christopher Friedt wrote:

> +	return z_dynamic_object_aligned_create(1, size);

> I think elsewhere that `sizeof(void*)` is used in place of an unspecified alignment because it's a reasonable safe default alignment. 

Personally, I'd prefer using 0 when no particular alignment is 
necessary. The code will already take care to return memory with the 
minimum alignment for all basic types for a given platform in that case.

**Comment by dcpleung** [comment]
> On Tue, 12 Jan 2021, Christopher Friedt wrote: + return z_dynamic_object_aligned_create(1, size); I think elsewhere that `sizeof(void*)` is used in place of an unspecified alignment because it's a reasonable safe default alignment.
> Personally, I'd prefer using 0 when no particular alignment is necessary. The code will already take care to return memory with the minimum alignment for all basic types for a given platform in that case.

Hm... `sys_heap_aligned_alloc()` with alignment `0` simply calls `sys_heap_alloc()` which has no minimal alignment (AFAIK). So probably better to pass a value over.

**Comment by dcpleung** [comment]
> Looks good - just a slight change request to have consistent naming. Are any additional tests required?

Updated the naming and alignment value.

**Comment by npitre** [comment]
On Tue, 12 Jan 2021, Daniel Leung wrote:

> Hm... `sys_heap_aligned_alloc()` with alignment `0` simply calls `sys_heap_alloc()` which has no minimal alignment (AFAIK). So probably better to pass a value over.

It sure does. sys_heap_alloc() must have minimal alignment for the 
platform no matter what. And I know it does.

**Comment by dcpleung** [comment]
> On Tue, 12 Jan 2021, Daniel Leung wrote: Hm... `sys_heap_aligned_alloc()` with alignment `0` simply calls `sys_heap_alloc()` which has no minimal alignment (AFAIK). So probably better to pass a value over.
> It sure does. sys_heap_alloc() must have minimal alignment for the platform no matter what. And I know it does.

Changed the value to `0`. There is another issue where they reported the minimal alignment was 4, but I recalled it as 1, hence the confusion.

**Comment by npitre** [comment]
On Tue, 12 Jan 2021, Daniel Leung wrote:

> Changed the value to `0`. There is another issue where they reported the minimal alignment was 4, but I recalled it as 1, hence the confusion.

Thanks. There is a 1 in `z_thread_malloc()` that could be turned into a 0 as well for consistency.

**Comment by dcpleung** [comment]
> On Tue, 12 Jan 2021, Daniel Leung wrote: Changed the value to `0`. There is another issue where they reported the minimal alignment was 4, but I recalled it as 1, hence the confusion.
> Thanks. There is a 1 in `z_thread_malloc()` that could be turned into a 0 as well for consistency.

Changed that too.

**Review by jhedberg — APPROVED** [review]

**Review by npitre — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
Works for me
