### PR TITLE
drivers: nrf_rtc_timer: Fix handling of COMPARE events in set_alarm()

### LINKED ISSUE #54782: nrf_rtc_timer may not properly handle a timeout that is set in specific conditions
**Describe the bug**
While debugging #53613, specifically the `drivers.uart.uart_mix_poll_async_api` scenario, I noticed that sometimes the test  got "frozen" for a couple of minutes, then it continued and completed successfully. It turned out to be a problem in the nrf_rtc_timer driver. When there is a timeout scheduled and it is about to expire, and another timeout is set to replace the first one, it may happen that the driver fails to properly set the CC register for the second timeout and ignores the COMPARE event that comes from the first timeout (as a no longer valid one), and in consequence, the rescheduled timeout is handled with a delay of 512 seconds (after the timer overflows).

**To Reproduce**
It's quite hard to reproduce the problem with the test mentioned above, as the problem occurs there very seldom (usually the test fails due to another reason or passes successfully). I created a dedicated test case in the nrf_rtc_timer test that exposes the problem and I added it in a commit that is included in a PR that fixes this issue (see #54780).

**Impact**
Showstopper. Missed timeouts may influence kernel timers and scheduling of threads.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.15.1
 - Commit: 86bc8d4dcb66077d1c92f10b07b2f3ee8dc1feab

### PR DESCRIPTION
**Pull request by anangl**
This is a follow-up to commits https://github.com/zephyrproject-rtos/zephyr/commit/cf871aec645dc45503b20c2e7684a4babbc436dc and https://github.com/zephyrproject-rtos/zephyr/commit/205e684958ebea4d7f2a15d75b94aac880fb2390.

It turns out that the current implementation of the nrf_rtc_timer may still fail to properly handle a timeout if that timeout is set in very specific conditions - when a previously set timeout is about to expire. When that happens, the new timeout is handled 512 seconds later (when the system timer overflows) than it should be.

This PR adds an nrf_rtc_timer test case (`test_tight_rescheduling`) that exposes this problem. Another commit fixes it by adding examination of COMPARE events that appear during setting of the CC register value for a given timeout. The `set_absolute_alarm` function is also renamed to `set_alarm` to avoid confusion regarding what the function really does.

Fixes #54782.

### CODE REVIEW

**Review by stephanosio — APPROVED** [review]

File: drivers/timer/nrf_rtc_timer.c [hunk 1]
```diff
@@ -280,13 +280,28 @@ static void set_absolute_alarm(int32_t chan, uint32_t abs_val)
...
+			if (event_check(chan)) {
+				/* If the current counter value has not yet
+				 * reached the requested CC value, the event
+				 * must come from the previously set CC value
+				 * (the alarm is apparently rescheduled).
+				 * The event needs to be cleared then and the
+				 * loop needs to be continued.
+				 */
+				now = counter();
+				if (counter_sub(now, req_cc) > COUNTER_HALF_SPAN) {
```
Comment (nordic-krch) [inline drivers/timer/nrf_rtc_timer.c:298]: I am afraid that it will fail in the following scenario:
- event got set by previous setting
- `now` is read and it is still in the future so if is true
- before we clear the event ZLI occurs and during preemption req_cc is reached (so event would be set)
- cpu returns from preemption and clears the event.

**Review by nordic-krch — APPROVED** [review]
