### PR TITLE
net: ipv6: Fix ND packets validation on input 

### LINKED ISSUE #107900: net: ipv6: Neighbor Discovery packets validation is incorrect
### Describe the bug

Neighbor Discovery packet data validation (for RA, NS and NA packets) is incorrect, as long as ICMPv6 code field has a valid value, other checks are ignored.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

Reproduced with current main

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rlubos**
The checks validating RA, NS and NA packets content on input were not
correct - packets should be dropped in case any of those checks failed,
however current logic was invalid, causing other checks to be ignored as
long as the ICMPv6 code was correct (i. e. 0).

Add a few new tests covering this bug.

Fixes #107900

### CODE REVIEW

File: subsys/net/ip/ipv6_nbr.c [hunk 1]
```diff
@@ -1305,12 +1305,12 @@ static enum net_verdict handle_ns_input(struct net_icmp_ctx *ctx,
...
-			  sizeof(struct net_icmpv6_ns_hdr))) ||
-	    (ip_hdr->hop_limit != NET_IPV6_ND_HOP_LIMIT)) &&
-	    (net_ipv6_is_addr_mcast(&ns_tgt) &&
-	     icmp_hdr->code != 0U)) {
+	if ((length < (sizeof(struct net_ipv6_hdr) +
+		       sizeof(struct net_icmp_hdr) +
+		       sizeof(struct net_icmpv6_ns_hdr))) ||
+	    (ip_hdr->hop_limit != NET_IPV6_ND_HOP_LIMIT) ||
+	    net_ipv6_is_addr_mcast(&ns_tgt) ||
+	    (icmp_hdr->code != 0U)) {
```
Comment (pdgendt) [inline subsys/net/ip/ipv6_nbr.c]: Might be more helpful to split into different `if` checks for readability?

**Review by pdgendt — DISMISSED** [review]

File: subsys/net/ip/ipv6_nbr.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/ip/ipv6_nbr.c]: @pdgendt You mean something like:
```c
	if (length < (sizeof(struct net_ipv6_hdr) +
		      sizeof(struct net_icmp_hdr) +
		      sizeof(struct net_icmpv6_ns_hdr))) {
		goto drop;
	}

	if (ip_hdr->hop_limit != NET_IPV6_ND_HOP_LIMIT) {
		goto drop;
	}

	if (net_ipv6_is_addr_mcast(&ns_tgt)) {
		goto drop;
	}

	if (icmp_hdr->code != 0U) {
		goto drop;
	}

```
?

Comment (pdgendt) [reply subsys/net/ip/ipv6_nbr.c]: Yes

Comment (rlubos) [reply subsys/net/ip/ipv6_nbr.c]: Ok makes sense to me, will update.

**Review by pdgendt — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

File: tests/net/ipv6/src/main.c [hunk 2]
```diff
@@ -2576,4 +2578,125 @@ ZTEST(net_ipv6, test_z_privacy_extension_03_get_addr)
...
+	memset(&hdr.src, 0, sizeof(struct net_eth_addr));
+	memcpy(&hdr.dst, net_if_get_link_addr(net_pkt_iface(pkt))->addr,
+	       sizeof(struct net_eth_addr));
+
+	net_pkt_set_overwrite(pkt, false);
+
+	zassert_ok(net_pkt_write(pkt, &hdr, sizeof(struct net_eth_hdr)),
+		   "Failed to write L2 header");
+	zassert_ok(net_pkt_write(pkt, data, len),
+		   "Failed to write ND packet data");
```
[the remark this answers is not in the document]
Comment (rlubos) [reply tests/net/ipv6/src/main.c:2602]: > net_pkt_alloc_with_buffer() is given sizeof(struct net_eth_addr) + len

> Consider allocating enough for the entire frame (sizeof(struct net_eth_hdr) + len) 

Isn't it suggesting exactly what's currently done?

File: tests/net/ipv6/src/main.c [hunk 3]
```diff
@@ -2576,4 +2578,125 @@ ZTEST(net_ipv6, test_z_privacy_extension_03_get_addr)
...
+
+	/* Give the packet some time to propagate into the stack. */
+	k_msleep(10);
+
+	zassert_ok(net_mgmt(NET_REQUEST_STATS_GET_IPV6_ND, NULL, &ipv6_nd_after,
+			    sizeof(ipv6_nd_after)),
+		   "Failed to retrieve stats");
+
+	zassert_equal(ipv6_nd_before.drop + 1, ipv6_nd_after.drop,
+		      "ND packet drop count did not increase");
```
[the remark this answers is not in the document]
Comment (rlubos) [reply tests/net/ipv6/src/main.c]: I'll update this to monitor drop counter in a loop to give some more time on slower platforms, it could indeed turn out flaky over time...

**Review by pdgendt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
