### PR TITLE
sensors: voltage_divider: Reconfigure ADC for the channel to be used

### LINKED ISSUE #76732: "Voltage divider" sensor does not reconfigure ADC channels and only ever reads one channel
**Describe the bug**
Using multiple voltage divider, on different channels of the same ADC, it can be observed that only one channel is setup correctly and all following will use that channel as input regardless of their devicetree configuration.

This is happens because the `adc_channel_setup_dt()` function is only called in the `voltage_init()` function which will set the registers only once at boot and overriding what was set before.
Instead this has to happen before a `adc_read()` in the `fetch()` function to update the peripheral to the correct channel.

**To Reproduce**
- Using the Atmel SAMD21 XPlain board (`samd21_xpro`)
- Create an overlay file for it
```devicetree
/ {
	div1: v1 {
		compatible = "voltage-divider";
		io-channels = <&adc 0>;
		output-ohms = <1000>;
		full-ohms = <13000>;
	};

	div2: v2 {
		compatible = "voltage-divider";
		io-channels = <&adc 1>;
		output-ohms = <1000>;
		full-ohms = <13000>;
	};
};

&adc {
	status = "okay";
	gclk = <3>;
	prescaler = <4>;

	#address-cells = <1>;
	#size-cells = <0>;

	channel@0 {
		reg = <0>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
		zephyr,input-positive = <0>;
	};

	channel@1 {
		reg = <1>;
		zephyr,gain = "ADC_GAIN_1";
		zephyr,reference = "ADC_REF_INTERNAL";
		zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
		zephyr,resolution = <12>;
		zephyr,input-positive = <1>;
	};
};
```
- Have an app that reads both sensors
```c
const struct device *const dev_div1 = DEVICE_DT_GET(DT_NODELABEL(div1));
const struct device *const dev_div2 = DEVICE_DT_GET(DT_NODELABEL(div2);

// ...
struct sensor_value value;
sensor_sample_fetch(dev_div1);
sensor_channel_get(dev_div1, SENSOR_CHAN_VOLTAGE, &value);
LOG_INF("Divider 1 = %d (%d micro)V\n", voltage_value.value.val1,
			voltage_value.value.val2);

sensor_sample_fetch(dev_div2);
sensor_channel_get(dev_div2, SENSOR_CHAN_VOLTAGE, &value);
LOG_INF("Divider 2 = %d (%d micro)V\n", voltage_value.value.val1,
			voltage_value.value.val2);
```
- Apply different voltages to each channel
- Observe erroneous values on one channel (depending on which one gets instantiated last)

**Expected behavior**

**Impact**

Showstopper: Multiple voltage divider on the same ADC cannot be used and parallel usage of raw ADC APIs will give undefined results for the single divider instance.

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.8
 - Zephyr: edb71f0ba176edb96a1ffd212b2c0a5de09392bc

**Additional context**

### PR DESCRIPTION
**Pull request by guenzel-kinexon**
Some ADCs (e.g. SAM0) can only convert one channel at a time and therefore need to be reconfigured for every voltage divider prior to startin the conversion.

In the current implementation only one channel (whichever was initialized last) will be converted.

Fixes: #76732

### CODE REVIEW

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Please squash the fixup commit into the original commit

**Comment by guenzel-kinexon** [comment]
> Please squash the fixup commit into the original commit

done

File: drivers/sensor/voltage_divider/voltage.c [hunk 1]
```diff
@@ -171,7 +179,7 @@ static int voltage_init(const struct device *dev)
 	PM_DEVICE_DT_INST_DEFINE(inst, pm_action);                                                 \
                                                                                                    \
 	SENSOR_DEVICE_DT_INST_DEFINE(inst, &voltage_init, PM_DEVICE_DT_INST_GET(inst),             \
-			      &voltage_##inst##_data, &voltage_##inst##_config, POST_KERNEL,       \
-			      CONFIG_SENSOR_INIT_PRIORITY, &voltage_api);
+				     &voltage_##inst##_data, &voltage_##inst##_config,             \
+				     POST_KERNEL, CONFIG_SENSOR_INIT_PRIORITY, &voltage_api);
```
Comment (ubieda) [inline drivers/sensor/voltage_divider/voltage.c:183]: Non-related change, it seems.

File: drivers/sensor/voltage_divider/voltage.c [hunk 2]
```diff
@@ -74,8 +82,8 @@ static int get(const struct device *dev, enum sensor_channel chan, struct sensor
 	/* Note if full_ohms is not specified then unscaled voltage is returned */
 	(void)voltage_divider_scale_dt(&config->voltage, &v_mv);
 
-	LOG_DBG("%d of %d, %dmV, voltage:%dmV", data->raw,
-		(1 << data->sequence.resolution) - 1, raw_val, v_mv);
+	LOG_DBG("%d of %d, %dmV, voltage:%dmV", data->raw, (1 << data->sequence.resolution) - 1,
+		raw_val, v_mv);
```
Comment (ubieda) [inline drivers/sensor/voltage_divider/voltage.c:86]: Non-related change, it seems.

**Review by ubieda — DISMISSED** [review]
LGTM but please discard non-related changes.

**Comment by mmahadevan108** [comment]
@guenzel-kinexon Could you please rebase and help fix the merge conflict

**Comment by kartben** [comment]
@guenzel-kinexon friendly ping :)

File: drivers/sensor/voltage_divider/voltage.c (hunk 2 above)
Comment (guenzel-kinexon) [reply drivers/sensor/voltage_divider/voltage.c]: was done by the auto-formatter. Reverted the change

File: drivers/sensor/voltage_divider/voltage.c (hunk 1 above)
Comment (guenzel-kinexon) [reply drivers/sensor/voltage_divider/voltage.c]: was done by the auto-formatter. Reverted the change

**Comment by guenzel-kinexon** [comment]
friendly pong :)

Changes should be ok now.

**Comment by kartben** [comment]
@MaureenHelm please revisit

**Review by kartben — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
Not sure why the scancode check is failing.

@kartben I've been out for a couple of weeks, is this something you've seen recently that needs a rebase to resolve?

**Comment by kartben** [comment]
ya I was wondering the same -- CODEOWNERS recently got nuked but I'm not sure why it's even relevant since it's not touched by this PR. Just rebased to trigger the failing CI job since it was too old to be re-triggered manually.
