### PR TITLE
fs: Fix fs_diropen resource leak when invoked on fs_dir_t object in use

### LINKED ISSUE #31749: fs: fs_opendir can corrupt fs_dir_t object given via zdp parameter
The same issue raised in #29478 appears to also affect `fs_opendir()`, in that an in-use directory will be clobbered.

### PR DESCRIPTION
**Pull request by nvlsianpu**
The fs_dir_t_init() function has been added that should be used
for initialization of fs_dir_t structures before passing them
to fs_open and other functions.

fixes #31749

### CODE REVIEW

File: include/fs/fs_interface.h [hunk 1]
```diff
@@ -59,6 +59,8 @@ struct fs_file_t {
 /**
  * @brief Directory object representing an open directory
  *
+ * The object needs to be initialized with function fs_file_t_init().
```
Comment (de-nordic) [inline include/fs/fs_interface.h:62]: fs_dir_t_init

Comment (nvlsianpu) [reply include/fs/fs_interface.h]: fixed

File: include/fs/fs.h [hunk 2]
```diff
@@ -234,6 +234,20 @@ static inline void fs_file_t_init(struct fs_file_t *zfp)
 	*zfp = (struct fs_file_t){ 0 };
 }
 
+/**
+ * @brief Initialize fs_dir_t object
+ *
+ * Initialized the fs_dir_t object; the function needs to be invoked
```
Comment (pabigot) [inline include/fs/fs.h:240]: s/Initialized/Initializes/

**Review by pabigot — CHANGES_REQUESTED** [review]
One trivial spelling error.  OK to also update the one for `fs_file_t_init` which I missed somehow reviewing that PR.  Otherwise this looks good; thanks.

**Review by de-nordic — APPROVED** [review]
Looks OK. Thanks!

**Comment by nvlsianpu** [comment]
rebased onto newest master

**Comment by nvlsianpu** [comment]
@pabigot Typos were fixed.

**Review by pabigot — APPROVED** [review]
