### PR TITLE
drivers: flash: soc_mcux: Fix ram function permission issue

### LINKED ISSUE #98560: tests: tests/drivers/flash/common: kinetis with arm mpu : failed: Testsuite failed
### Describe the bug

- twr_kv58f220m

drivers.flash.common test is failed on v4.3.0-rc1

this is not a regression, it is not working always, and when checking the Kinetis issue I find this is because. the FTFx_DRIVER_IS_FLASH_RESIDENT is defined in modules/hal/nxp/mcux/mcux-sdk-ng/drivers/flash/fsl_ftfx_controller.c and the MPU does not give exec for the .bss in ram.

there are two issues here:

1. RAMFUNC definition
2. kv58 flash(FTFE) access control is not implement.

testcase path is tests/drivers/flash/common

### Regression

- [ ] This is a regression.

### Steps to reproduce

```
west build -b twr_kv58f220m tests/drivers/flash/common
west flash
```

the ram_config analysis found

│                       └── drivers                                                                64   0.59%  -
│                           └── flash                                                              64   0.59%  -
│                               └── fsl_ftfx_controller.c                                          64   0.59%  -
│                                   └── s_ftfxRunCommand                                           64   0.59%  0x200006c0 bss

this is in .bss

```
((.venv) ) ubuntu@zephyr-test-02:~/zephyrproject/zephyr$ west build -t ram_report
-- west build: running target ram_report
[0/1] cd /home/ubuntu/zephyrproject/zephyr/build && /home/ubuntu/zephyrproject/.venv/bin/pyth...u/zephyrproject/zephyr/build --workspace=/home/ubuntu/zephyrproject -d 99 --json ram.json ram
WARN: Symbol 'z_tls_current' section '' is not in RAM or ROM.
Path                                                                                             Size       %  Address    Section
==========================================================================================================================================
Root                                                                                            10829 100.00%  -
├── (hidden)                                                                                       -1  -0.01%  -
├── (no paths)                                                                                      0   0.00%  -
├── WORKSPACE                                                                                      76   0.70%  -
│   └── modules                                                                                    76   0.70%  -
│       └── hal                                                                                    76   0.70%  -
│           └── nxp                                                                                76   0.70%  -
│               └── mcux                                                                           76   0.70%  -
│                   ├── mcux-sdk                                                                   12   0.11%  -
│                   │   └── devices                                                                12   0.11%  -
│                   │       └── MKV58F24                                                           12   0.11%  -
│                   │           └── drivers                                                        12   0.11%  -
│                   │               └── fsl_clock.c                                                12   0.11%  -
│                   │                   ├── g_xtal0Freq                                             4   0.04%  0x200006bc bss
│                   │                   ├── s_fastIrcFreq                                           4   0.04%  0x20000024 datas
│                   │                   └── s_slowIrcFreq                                           4   0.04%  0x20000028 datas
│                   └── mcux-sdk-ng                                                                64   0.59%  -
│                       └── drivers                                                                64   0.59%  -
│                           └── flash                                                              64   0.59%  -
│                               └── fsl_ftfx_controller.c                                          64   0.59%  -
│                                   └── s_ftfxRunCommand                                           64   0.59%  0x200006c0 bss
└── ZEPHYR_BASE                                                                                 10754  99.31%  -
    ├── arch                                                                                       17   0.16%  -
    │   └── arm                                                                                    17   0.16%  -
    │       └── core                                                                               17   0.16%  -
    │           ├── mpu                                                                            13   0.12%  -
    │           │   ├── arm_core_mpu.c                                                             12   0.11%  -
    │           │   │   └── dynamic_regions.0                                                      12   0.11%  0x200005d8 bss
    │           │   └── arm_mpu.c                                                                   1   0.01%  -
    │           │       └── static_regions_num                                                      1   0.01%  0x2000073a bss
    │           └── tls.c                                                                           4   0.04%  -
    │               └── z_arm_tls_ptr                                                               4   0.04%  0x200005d4 bss
    ├── drivers                                                                                   252   2.33%  -
    │   ├── clock_control                                                                           4   0.04%  -
    │   │   ├── clock_control_mcux_mcg.c                                                            2   0.02%  -
    │   │   │   └── __devstate_dts_ord_61                                                           2   0.02%  0x2000003c device_states
    │   │   └── clock_control_mcux_sim.c                                                            2   0.02%  -
    │   │       └── __devstate_dts_ord_8                                                            2   0.02%  0x2000003e device_states
    │   ├── flash                                                                                 122   1.13%  -
    │   │   └── soc_flash_mcux.c                                                                  122   1.13%  -
    │   │       ├── __devstate_dts_ord_50                                                           2   0.02%  0x20000040 device_states
    │   │       └── flash_data                                                                    120   1.11%  0x200005fc bss
    │   ├── gpio                                                                                   70   0.65%  -
    │   │   └── gpio_mcux.c                                                                        70   0.65%  -
    │   │       ├── __devstate_dts_ord_10                                                           2   0.02%  0x2000004a device_states
    │   │       ├── __devstate_dts_ord_12                                                           2   0.02%  0x20000048 device_states
    │   │       ├── __devstate_dts_ord_14                                                           2   0.02%  0x20000042 device_states
    │   │       ├── __devstate_dts_ord_37                                                           2   0.02%  0x20000044 device_states
    │   │       ├── __devstate_dts_ord_58                                                           2   0.02%  0x20000046 device_states
    │   │       ├── gpio_mcux_port0_data                                                           12   0.11%  0x200006a4 bss
    │   │       ├── gpio_mcux_port1_data                                                           12   0.11%  0x20000698 bss
    │   │       ├── gpio_mcux_port2_data                                                           12   0.11%  0x2000068c bss
    │   │       ├── gpio_mcux_port3_data                                                           12   0.11%  0x20000680 bss
    │   │       └── gpio_mcux_port4_data                                                           12   0.11%  0x20000674 bss
    │   ├── pinctrl                                                                                10   0.09%  -
    │   │   └── pinctrl_nxp_port.c                                                                 10   0.09%  -
    │   │       ├── __devstate_dts_ord_11                                                           2   0.02%  0x20000052 device_states
    │   │       ├── __devstate_dts_ord_13                                                           2   0.02%  0x2000004c device_states
    │   │       ├── __devstate_dts_ord_36                                                           2   0.02%  0x2000004e device_states
    │   │       ├── __devstate_dts_ord_57                                                           2   0.02%  0x20000050 device_states
    │   │       └── __devstate_dts_ord_9                                                            2   0.02%  0x20000054 device_states
    │   ├── serial                                                                                 18   0.17%  -
    │   │   └── uart_mcux.c                                                                        18   0.17%  -
    │   │       ├── __devstate_dts_ord_44                                                           2   0.02%  0x20000056 device_states
    │   │       └── uart_mcux_0_data                                                               16   0.15%  0x20000014 datas
    │   └── timer                                                                                  28   0.26%  -
    │       └── cortex_m_systick.c                                                                 28   0.26%  -
    │           ├── announced_cycles                                                                8   0.07%  0x20000108 bss
    │           ├── cycle_count                                                                     8   0.07%  0x20000110 bss
    │           ├── last_load                                                                       4   0.04%  0x200006b4 bss
    │           ├── lock                                                                            4   0.04%  0x200006b8 bss
    │           └── overflow_cyc                                                                    4   0.04%  0x200006b0 bss
    ├── kernel                                                                                   5190  47.93%  -
    │   ├── init.c                                                                               4961  45.81%  -
    │   │   ├── _kernel                                                                            32   0.30%  0x20000700 bss
    │   │   ├── z_idle_stacks                                                                     384   3.55%  0x20002000 noinit
    │   │   ├── z_idle_threads                                                                    160   1.48%  0x20000118 bss
    │   │   ├── z_interrupt_stacks                                                               2112  19.50%  0x200017c0 noinit
    │   │   ├── z_main_stack                                                                     2112  19.50%  0x20002180 noinit
    │   │   ├── z_main_thread                                                                     160   1.48%  0x200001b8 bss
    │   │   └── z_sys_post_kernel                                                                   1   0.01%  0x2000073f bss
    │   ├── sched.c                                                                               164   1.51%  -
    │   │   ├── _sched_spinlock                                                                     4   0.04%  0x20000724 bss
    │   │   └── _thread_dummy                                                                     160   1.48%  0x20000258 bss
    │   ├── sem.c                                                                                   4   0.04%  -
    │   │   └── lock                                                                                4   0.04%  0x20000720 bss
    │   ├── timeout.c                                                                              24   0.22%  -
    │   │   ├── announce_remaining                                                                  4   0.04%  0x20000730 bss
    │   │   ├── curr_tick                                                                           8   0.07%  0x20000310 bss
    │   │   ├── timeout_list                                                                        8   0.07%  0x20000030 datas
    │   │   └── timeout_lock                                                                        4   0.04%  0x20000734 bss
    │   └── timeslicing.c                                                                          37   0.34%  -
    │       ├── pending_current                                                                     4   0.04%  0x20000728 bss
    │       ├── slice_expired                                                                       1   0.01%  0x20000740 bss
    │       ├── slice_max_prio                                                                      4   0.04%  0x2000072c bss
    │       ├── slice_ticks                                                                         4   0.04%  0x2000002c datas
    │       └── slice_timeouts                                                                     24   0.22%  0x200002f8 bss
    ├── lib                                                                                        68   0.63%  -
    │   ├── libc                                                                                   32   0.30%  -
    │   │   ├── common                                                                             12   0.11%  -
    │   │   │   └── source                                                                         12   0.11%  -
    │   │   │       └── stdlib                                                                     12   0.11%  -
    │   │   │           └── malloc.c                                                               12   0.11%  -
    │   │   │               └── z_malloc_heap                                                      12   0.11%  0x200005e8 bss
    │   │   └── picolibc                                                                           20   0.18%  -
    │   │       └── stdio.c                                                                        20   0.18%  -
    │   │           ├── __stdout                                                                   16   0.15%  0x20000004 datas
    │   │           └── _stdout_hook                                                                4   0.04%  0x200005e4 bss
    │   ├── os                                                                                     32   0.30%  -
    │   │   ├── clock.c                                                                            28   0.26%  -
    │   │   │   ├── rt_clock_offset                                                                16   0.15%  0x20000058 bss
    │   │   │   ├── rt_clock_offset_lock                                                            4   0.04%  0x200005d0 bss
    │   │   │   └── z_ztest_test_rule_clock_offset_reset_rule                                       8   0.07%  0x10006f64 ztest
    │   │   └── printk.c                                                                            4   0.04%  -
    │   │       └── _char_out                                                                       4   0.04%  0x20000000 datas
    │   └── utils                                                                                   4   0.04%  -
    │       └── last_section_id.c                                                                   4   0.04%  -
    │           └── last_id                                                                         4   0.04%  0x10009698 .last_section
    ├── soc                                                                                         8   0.07%  -
    │   └── nxp                                                                                     8   0.07%  -
    │       └── kinetis                                                                             8   0.07%  -
    │           └── kv5x                                                                            8   0.07%  -
    │               └── soc.c                                                                       8   0.07%  -
    │                   └── sim_config                                                              8   0.07%  0x10006fb4 tbss
    ├── subsys                                                                                   4333  40.01%  -
    │   └── testsuite                                                                            4333  40.01%  -
    │       ├── include                                                                             8   0.07%  -
    │       │   └── zephyr                                                                          8   0.07%  -
    │       │       └── tc_util.h                                                                   8   0.07%  -
    │       │           ├── tc_spend_time                                                           4   0.04%  0x200005f4 bss
    │       │           └── tc_start_time                                                           4   0.04%  0x200005f8 bss
    │       └── ztest                                                                            4325  39.94%  -
    │           └── src                                                                          4325  39.94%  -
    │               └── ztest.c                                                                  4325  39.94%  -
    │                   ├── cur_phase                                                               1   0.01%  0x20000038 datas
    │                   ├── current_test_failed_assumption                                          1   0.01%  0x2000073b bss
    │                   ├── failed_expectation                                                      1   0.01%  0x2000073e bss
    │                   ├── test_result                                                             1   0.01%  0x2000073c bss
    │                   ├── test_status                                                             1   0.01%  0x2000073d bss
    │                   ├── ztest_thread                                                          160   1.48%  0x20000068 bss
    │                   └── ztest_thread_stack                                                   4160  38.42%  0x20000780 noinit
    └── tests                                                                                     886   8.18%  -
        └── drivers                                                                               886   8.18%  -
            └── flash                                                                             886   8.18%  -
                └── common                                                                        886   8.18%  -
                    └── src                                                                       886   8.18%  -
                        └── main.c                                                                886   8.18%  -
                            ├── ebw_required                                                        1   0.01%  0x20000738 bss
                            ├── erase_value                                                         1   0.01%  0x20000739 bss
                            ├── expected                                                          512   4.73%  0x200003c4 bss
                            ├── page_info                                                          12   0.11%  0x200005c4 bss
                            ├── z_ztest_suite_node_stats_flash_driver                              12   0.11%  0x20000318 bss
                            ├── z_ztest_test_node_flash_driver                                     28   0.26%  0x10006ea8 ztest
                            ├── z_ztest_unit_test__flash_driver__test_flash_copy                   20   0.18%  0x10006ec4 ztest
                            ├── z_ztest_unit_test__flash_driver__test_flash_erase                  20   0.18%  0x10006ed8 ztest
                            ├── z_ztest_unit_test__flash_driver__test_flash_fill                   20   0.18%  0x10006eec ztest
                            ├── z_ztest_unit_test__flash_driver__test_flash_flatten                20   0.18%  0x10006f00 ztest
                            ├── z_ztest_unit_test__flash_driver__test_flash_page_layout            20   0.18%  0x10006f14 ztest
                            ├── z_ztest_unit_test__flash_driver__test_get_size                     20   0.18%  0x10006f28 ztest
                            ├── z_ztest_unit_test__flash_driver__test_read_unaligned_address       20   0.18%  0x10006f3c ztest
                            ├── z_ztest_unit_test__flash_driver__test_supply_gpios_control         20   0.18%  0x10006f50 ztest
                            ├── z_ztest_unit_test_stats_flash_driver_test_flash_copy               20   0.18%  0x20000324 bss
                            ├── z_ztest_unit_test_stats_flash_driver_test_flash_erase              20   0.18%  0x20000374 bss
                            ├── z_ztest_unit_test_stats_flash_driver_test_flash_fill               20   0.18%  0x2000039c bss
                            ├── z_ztest_unit_test_stats_flash_driver_test_flash_flatten            20   0.18%  0x20000388 bss
                            ├── z_ztest_unit_test_stats_flash_driver_test_flash_page_layout        20   0.18%  0x20000338 bss
                            ├── z_ztest_unit_test_stats_flash_driver_test_get_size                 20   0.18%  0x2000034c bss
                            ├── z_ztest_unit_test_stats_flash_driver_test_read_unaligned_address   20   0.18%  0x200003b0 bss
                            └── z_ztest_unit_test_stats_flash_driver_test_supply_gpios_control     20   0.18%  0x20000360 bss
==========================================================================================================================================
                                                                                                10829
```

### Relevant log output

```shell
*** Booting Zephyr OS build v4.3.0-rc1-122-gfb01c781b6c0 ***
Running TESTSUITE flash_driver
===================================================================
START - test_flash_copy
Test will run on device flash-controller@40020000
E: ***** MPU FAULT *****
E:   Instruction Access Violation
E: r0/a1:  0x40020000  r1/a2:  0x100e6000  r2/a3:  0x00001fff
E: r3/a4:  0x200006c1 r12/ip:  0x00000000 r14/lr:  0x1000366d
E:  xpsr:  0x01000000
E: Faulting instruction address (r15/pc): 0x200006c0
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x20000068 (test_flash_copy)
E: Halting system
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: ubuntu
- toolchain: Zephyr
- version: v4.3.0-rc1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zejiang0jason**
Add workaround for MCUXSDK FTFX driver when FTFx_DRIVER_IS_FLASH_RESIDENT is enabled.
The SDK places the run command function in data section which is not executable when Zephyr configures memory permissions. Implement a RAM function to replace the FTFX driver's run command function

Fixes: #98560

### CODE REVIEW

**Review by hakehuang — APPROVED** [review]

File: drivers/flash/soc_flash_mcux.c [hunk 1]
```diff
@@ -376,6 +393,15 @@ static int flash_mcux_init(const struct device *dev)
 
 	rc = FLASH_Init(&priv->config);
 
+#if defined(FTFx_DRIVER_IS_FLASH_RESIDENT) && FTFx_DRIVER_IS_FLASH_RESIDENT
+	/* MCUXSDK FTFX driver's commadAddr is an address to data (LSB = 0), but
+	 * (uint32_t)flash_ftfx_run_command is an address to code (LDB = 1), so
+	 * clear the LSB here.
+	 */
+	priv->config.ftfxConfig->runCmdFuncAddr.commadAddr =
+		((uint32_t)flash_ftfx_run_command) & ~0x01U;
```
Comment (mmahadevan108) [inline drivers/flash/soc_flash_mcux.c:402]: @zejiang0jason , I am confused by this code. Are you assigning this to be a function pointer?

Comment (zejiang0jason) [reply drivers/flash/soc_flash_mcux.c:402]: Hi @mmahadevan108 , MCUX SDK flash driver's `commandAddr` is an `uint32_t` type address:
https://github.com/nxp-mcuxpresso/mcuxsdk-core/blob/main/drivers/flash/fsl_ftfx_controller.h#L347.

Here `flash_ftfx_run_command` is a function address whose LSB is 1.
SDK flash driver's `commandAddr` assumes the LSB is 0, https://github.com/nxp-mcuxpresso/mcuxsdk-core/blob/main/drivers/flash/fsl_ftfx_controller.c#L1342. So need to clear LSB.

**Review by mmahadevan108 — APPROVED** [review]
