### PR TITLE
Bluetooth: controller: Fix ISO CI tests

### LINKED ISSUE #34009: [Coverity CID: 220532] Unrecoverable parse warning in subsys/bluetooth/controller/ll_sw/ull_peripheral_iso.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b86f7addae05add0db45d9b528854235fbb93a48/subsys/bluetooth/controller/ll_sw/ull_peripheral_iso.c#L19

Category: Parse warnings
Function: ``
Component: Bluetooth
CID: [220532](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=220532)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b86f7addae05add0db45d9b528854235fbb93a48/subsys/bluetooth/controller/ll_sw/ull_peripheral_iso.c#L19

```
13     #include "common/log.h"
14     #include "hal/debug.h"
15    
16     #include "util/memq.h"
17     #include "ticker/ticker.h"
18    
>>>     CID 220532:  Parse warnings  (PARSE_ERROR)
>>>     cannot open source file "conn_internal.h"
19     #include "conn_internal.h"
20     #include "hal/ticker.h"
21     #include "util/mayfly.h"
22    
23     #include "pdu.h"
24     #include "lll.h"
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by mtpr-ot**
Make bluetooth.init tests for nRF platform pass again by adding ULL/LLL
stub functions, and fixing minor compile issues.

Fixes #34009.

Signed-off-by: Morten Priess <mtpr@oticon.com>

### CODE REVIEW

**Review by cvinayak — APPROVED** [review]
quick-ack.

**Review by Thalley — APPROVED** [review]
LGTM

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn_iso.c [hunk 1]
```diff
@@ -0,0 +1,40 @@
+/*
+ * Copyright (c) 2018-2021 Nordic Semiconductor ASA
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn_iso.c:5]: The copyright is a bit fun, since this is technically added by Oticon/Demant rather than Nordic, but it makes more sense to have Nordic here in the Nordic LLL. 

Perhaps the year should just be 2021 though?

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn_iso.c:5]: I agree it's a bit odd. I'll put in whatever you like ;-)

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_conn_iso.c:5]: I think it makes the most sense to just have Nordic there, but please update it to just 2021 to better reflect when it was added.
