### PR TITLE
Fix SAADC pin configurations

### LINKED ISSUE #107119: nRF adc_channel_setup() returns -EINVAL for certain inputs
### Describe the bug

On Nordic boards such as nRF52840, `adc_channel_setup()` returns `-EINVAL` when `struct adc_channel_cfg` field `input_positive` contains certain values:

- `SAADC_CH_PSELP_PSELP_AnalogInput0` through `SAADC_CH_PSELP_PSELP_AnalogInput6` work as expected.
- `SAADC_CH_PSELP_PSELP_AnalogInput7` does not work.
- `SAADC_CH_PSELP_PSELP_VDD` does not work.
- `SAADC_CH_PSELP_PSELP_VDDHDIV5` does not work.

I've narrowed the issue down to this: <https://github.com/nordicsemi/nrfx/blob/aa83d4df8d5f41b591f23a8555794632afb3475d/drivers/src/nrfx_saadc_common.h#L86-L89>

- `SAADC_CH_PSELP_PSELP_AnalogInput7` has value 8, so it fails the condition.
- `SAADC_CH_PSELP_PSELP_VDD` and `SAADC_CH_PSELP_PSELP_VDDHDIV5` are not handled.

### Regression

- [x] This is a regression (previously worked on Zephyr 4.3)

### Relevant log output

```
[00:00:00.000,579] <err> adc_nrfx_saadc: Cannot configure channel 0: -22
```

### Steps to reproduce

This can be reproduced with code from `samples/boards/nordic/battery`, notably <https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/boards/nordic/battery/src/battery.c#L125-L130>.

### Impact

Currently unable to read affected analog pins without patching hal_nordic.

### Enviroment

Version: Zephyr 4.4.0 RC3

### PR DESCRIPTION
**Pull request by jaz1-nordic**
SAADC pin configuration need to be fixed after changes in NRFX driver

### CODE REVIEW

**Review by anangl — DISMISSED** [review]

**Review by nika-nordic — DISMISSED** [review]

File: drivers/sensor/seeed/grove/temperature_sensor.c [hunk 1]
```diff
@@ -102,7 +106,7 @@ static int gts_init(const struct device *dev)
 		.acquisition_time = ADC_ACQ_TIME_DEFAULT,
 		.channel_id = cfg->adc_channel,
 #ifdef CONFIG_ADC_NRFX_SAADC
-		.input_positive = SAADC_CH_PSELP_PSELP_AnalogInput0 + cfg->adc_channel,
+		.input_positive = NRFX_ANALOG_EXTERNAL_AIN0 + cfg->adc_channel,
```
Comment (xudongzheng) [inline drivers/sensor/seeed/grove/temperature_sensor.c]:
```suggestion
		.input_positive = cfg->adc_channel,
```

What about updating all the Nordic boards with `vbatt` to use constants from <https://github.com/zephyrproject-rtos/zephyr/blame/v4.4.0-rc3/include/zephyr/dt-bindings/adc/nrf-saadc.h#L10-L23>?

Instead of `&adc 0`, it can be `&adc NRF_SAADC_AIN0`. This eliminates the need for `input_positive` to be relative to `NRFX_ANALOG_EXTERNAL_AIN0` and `nrfx_saadc.h` is no longer needed.

This also makes constants like `NRF_SAADC_VDD` and `NRF_SAADC_VDDHDIV5` discoverable and easier to use.

I can also do this in a separate PR if there are no objections.

**Review by xudongzheng — CHANGES_REQUESTED** [review]

File: drivers/sensor/seeed/grove/temperature_sensor.c (hunk 1 above)
Comment (jaz1-nordic) [reply drivers/sensor/seeed/grove/temperature_sensor.c]: I have no objections to doing this in a separate PR. I'd be happy to review your changes when they're ready :)

**Review by nika-nordic — APPROVED** [review]

**Review by xudongzheng — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
