### PR TITLE
logging: Fix RTT log backend lagging if no host

### LINKED ISSUE #13424: Logger got recently slower
I've observed this issue originally with `echo_client` and `echo_server` samples, running on `nrf52840_pca10056`. So far, the logger module was able to print all logs that samples produced with no problem. Recently something changed, and the logger is no longer able to keep up with the network traffic and drops log messages heavily.

The issue can be easily reproduced in `shell_module` sample when runnning `log_test start demo` command. According to documentation, running this command will print log message every 200 ms. Even though it does not sound much, it is enough for the logger to start dropping logs.

```
[00:00:13.012,939] <inf> app: Timer expired.
[00:00:13.012,939] <inf> app_test: info message
[00:00:13.012,939] <wrn> app_test: warning message
[00:00:13.012,939] <err> app_test: err message
[00:00:13.212,524] <inf> app: Timer expired.
[00:00:13.212,524] <inf> app_test: info message
[00:00:13.212,524] <wrn> app_test: warning message
[00:00:13.212,524] <err> app_test: err message
--- 1 messages dropped ---
[00:00:13.412,109] <inf> app_test: info message
--- 3 messages dropped ---
[00:00:13.611,694] <inf> app_test: info message
[00:00:13.611,694] <wrn> app_test: warning message
--- 2 messages dropped ---
[00:00:13.811,279] <inf> app_test: info message
--- 3 messages dropped ---
[00:00:14.010,864] <inf> app_test: info message
[00:00:14.010,864] <wrn> app_test: warning message
--- 2 messages dropped ---
[00:00:14.210,449] <inf> app_test: info message
--- 3 messages dropped ---
[00:00:14.410,034] <inf> app_test: info message
[00:00:14.410,034] <wrn> app_test: warning message
```

### PR DESCRIPTION
**Pull request by nordic-krch**
In case it was detected that RTT host was not present
backend was still performing single sleep or busy wait
round before dropping data. That was degrading log
processing performance.

Fixes #13424.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

File: subsys/logging/log_backend_rtt.c [hunk 1]
```diff
@@ -185,7 +185,7 @@ static int data_out_block_mode(u8_t *data, size_t length, void *ctx)
 
 		if (ret) {
 			on_write(retry_cnt);
-		} else {
+		} else if (host_present) {
```
Comment (pizi-nordic) [inline subsys/logging/log_backend_rtt.c]: IMHO from time to time host presence should be rechecked.

Comment (nordic-krch) [reply subsys/logging/log_backend_rtt.c]: it will be. If `ret!=0` it means that host read the buffer and we were able to put some data to the buffer. In `on_write` `host_present` is set to true.

**Review by rlubos — APPROVED** [review]
Indeed it fixes #13424, thanks!

**Comment by nordic-krch** [comment]
@jarz-nordic @pizi-nordic ping

**Review by pizi-nordic — APPROVED** [review]

**Comment by nordic-krch** [comment]
@carlescufi could you merge it? @jarz-nordic is out of office so he will not review that.

**Review by carlescufi — APPROVED** [review]
