### PR TITLE
bluetooth: host: conn: Utilize conn_set_state in conn_destroy

### LINKED ISSUE #54542: Bluetooth pending tx packets assert on disable
**Describe the bug**
Fatal error (assert) on disabling Bluetooth when a pending transaction (notification).

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? **nRF52840 DK**
 - What have you tried to diagnose or workaround this issue? **not enable asserts or add delays before disabling Bluetooth** 
 - Is this a regression?  **no**

**To Reproduce**
1.checkout on  https://github.com/ktaborowski/sdk-zephyr/tree/zephyrproject-bt-notify-and-disconnect
2. cd zephyr/samples/bluetooth/peripheral
3.  west build -p -b nrf52840dk_nrf52840
4. Connect nRF52840 DK board (PCA10056)
5. west flash
6. Subscribe to notification e.g. with nRF Connect App

nrfconnect_1_connect
nrfconnect_2_service
nrfconnect_3_notifications

7. Wait a few seconds, device disconnects automatically 

**Expected behavior**
Device disconnects, no fault.

**Impact**
We are facing the same issues in more complex application (prepared dumb sample for easy reproduction).

**Logs and console output**
```
*** Booting Zephyr OS build v3.3.0-rc2-1-gdf764c604062 ***
[00:00:00.420,410] <inf> fs_nvs: nvs_mount: 8 Sectors of 4096 bytes
[00:00:00.420,410] <inf> fs_nvs: nvs_mount: alloc wra: 0, ee8
[00:00:00.420,440] <inf> fs_nvs: nvs_mount: data wra: 0, 124
[00:00:00.422,668] <inf> bt_hci_core: hci_vs_init: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.422,698] <inf> bt_hci_core: hci_vs_init: HW Variant: nRF52x (0x0002)
[00:00:00.422,729] <inf> bt_hci_core: hci_vs_init: Firmware: Standard Bluetooth controller (0x00) Version 3.3 Build 0
[00:00:00.423,217] <inf> bt_hci_core: bt_init: No ID address. App must call settings_load()
Bluetooth initialized
[00:00:00.423,950] <inf> bt_hci_core: bt_dev_show_info: Identity: D1:D1:AE:D1:FB:7C (random)
[00:00:00.423,980] <inf> bt_hci_core: bt_dev_show_info: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x05f1
[00:00:00.424,041] <inf> bt_hci_core: bt_dev_show_info: LMP: version 5.3 (0x0c) subver 0xffff
Advertising successfully started
Indicate VND attr 0x2d8e8 (UUID 12345678-1234-5678-1234-56789abcdef1)
Updated MTU: TX: 23 RX: 23 bytes
Connected
Connection countdown 9
[00:01:55.439,727] <wrn> bt_gatt: gatt_notify: Device is not subscribed to characteristic
Notify fail (err=-22)
Connection countdown 8
[00:01:56.439,941] <wrn> bt_gatt: gatt_notify: Device is not subscribed to characteristic
Notify fail (err=-22)
Connection countdown 7
[00:01:57.440,155] <wrn> bt_gatt: gatt_notify: Device is not subscribed to characteristic
Notify fail (err=-22)
Connection countdown 6
[00:01:58.440,399] <wrn> bt_gatt: gatt_notify: Device is not subscribed to characteristic
Notify fail (err=-22)
Connection countdown 5
Connection countdown 4
Connection countdown 3
Connection countdown 2
Connection countdown 1
Connection countdown 0
ASSERTION FAIL [sys_slist_is_empty(&conn->tx_pending)] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/conn.c:740
	Pending TX packets
[00:02:04.442,657] <err> os: esf_dump: r0/a1:  0x00000004  r1/a2:  0x000002e4  r2/a3:  0x00000003
[00:02:04.442,687] <err> os: esf_dump: r3/a4:  0x20000e28 r12/ip:  0x200063c4 r14/lr:  0x0000af15
[00:02:04.442,687] <err> os: esf_dump:  xpsr:  0x41000000
[00:02:04.442,718] <err> os: esf_dump: Faulting instruction address (r15/pc): 0x000286fa
[00:02:04.442,749] <err> os: z_fatal_error: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:02:04.442,810] <err> os: z_fatal_error: Current thread: 0x20001b08 (unknown)
[00:02:04.528,015] <err> os: k_sys_fatal_error_handler: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Toolchain btoolchain:
```
-- CMake version: 3.25.2
-- Found Python3: /usr/bin/python3.8 
-- Zephyr version: 3.3.0-rc2
-- Found west (found suitable version "0.12.0", minimum required is "0.7.1")
-- Board: nrf52840dk_nrf52840
-- Found toolchain: zephyr 0.15.1
```
 - Commit SHA or Version used:  https://github.com/ktaborowski/sdk-zephyr/tree/zephyrproject-bt-notify-and-disconnect commit `9ad92bca56c06018314ae30a5708a09a3e86444d` based on upstream tag `v3.3.0-rc2`

### PR DESCRIPTION
**Pull request by sean-madigan**
fixes https://github.com/zephyrproject-rtos/zephyr/issues/54542 , which highlighted a bug in bt_disable, where if you have pending tx packets for a connection and then call bt_disable, it will assert. 

Previously we would call conn_cleanup for all connections,
however this had multiple problems such as:
-Not destroying conn->tx_pending packets and causing an assert
-Calling conn_cleanup for connectable adv, triggering
disconnected callback

Now we will use bt_conn_set_state to manage the teardown of
connections correctly. First, if in connected or disconnecting,
set state to disconnect complete. Then for all states, set
state to disconnected. This will carry out proper cleanup
and teardown when required.

To do this, it was required to keep the tx_thread open as
this is used in disconnecting teardown, so this has been
moved to below the conn_cleanup_all call.

Signed-off-by: Sean Madigan <sean.madigan@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -750,8 +750,14 @@ static void conn_destroy(struct bt_conn *conn, void *data)
 	k_work_cancel_delayable(&conn->deferred_work);
 
 	conn->pending_no_cb = 0;
+	conn->tx_pending.head = NULL;
+	conn->tx_pending.tail = NULL;
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:754]: Alternatively we can call `sys_slist_init(conn->tx_pending)` which I guess does the same, but using the `slist` API

File: subsys/bluetooth/host/conn.c [hunk 2]
```diff
@@ -750,8 +750,14 @@ static void conn_destroy(struct bt_conn *conn, void *data)
...
 
-	conn_cleanup(conn);
+	if (conn->state == BT_CONN_CONNECTED ||
+		conn->state == BT_CONN_DISCONNECTING ||
+		conn->state == BT_CONN_DISCONNECT_COMPLETE) {
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:758]:
```suggestion
	if (conn->state == BT_CONN_CONNECTED ||
	    conn->state == BT_CONN_DISCONNECTING ||
	    conn->state == BT_CONN_DISCONNECT_COMPLETE) {
```

**Review by Thalley — DISMISSED** [review]

**Comment by Thalley** [comment]
@sean-madigan Have this been verified to fix the issue? 

If so, please add `fixes https://github.com/zephyrproject-rtos/zephyr/issues/54542` in the PR description

**Review by alwa-nordic — CHANGES_REQUESTED** [review]
The references in `conn->tx_pending` must be properly destroyed using `conn_tx_destroy` here. All callbacks shall be invoked as usual; this is a promise to higher layers.

If we generate a 'disconnected' event without a corresponding previous 'connected' event, then there must be a bug in the monster `bt_conn_set_state`.

File: subsys/bluetooth/host/conn.c [hunk 3]
```diff
@@ -747,11 +747,10 @@ static void conn_cleanup(struct bt_conn *conn)
 
 static void conn_destroy(struct bt_conn *conn, void *data)
 {
-	k_work_cancel_delayable(&conn->deferred_work);
-
-	conn->pending_no_cb = 0;
-
-	conn_cleanup(conn);
+	if (conn->state == BT_CONN_CONNECTED ||
+	    conn->state == BT_CONN_DISCONNECTING) {
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:751]: we don't need to handle the `connecting` states?

Comment (sean-madigan) [reply subsys/bluetooth/host/conn.c:751]: As `bt_conn_set_state` has handling for the state change `BT_CONN_CONNECTING->BT_CONN_DISCONNECTED` I thought this was a safe operation.

Comment (Thalley) [reply subsys/bluetooth/host/conn.c:751]: Hmm, looking at `bt_conn_set_state`, is there actually any reason why we don't unconditionally call `bt_conn_set_state(BT_CONN_DISCONNECT_COMPLETE)`?

Comment (sean-madigan) [reply subsys/bluetooth/host/conn.c:751]: As there is specific handling for changing state `BT_CONN_CONNECTING/BT_CONN_CONNECTING_ADV` etc to `BT_CONN_DISONNECTED`, whereas `BT_CONN_CONNECTED/BT_CONN_DISCONNECTING` are designed to go through `BT_CONN_DISCONNECT_COMPLETE`

**Review by Thalley — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
