### PR TITLE
Bluetooth: Host: SMP: Verify public key before usage

### LINKED ISSUE #80218: Bluetooth SMP LE SC should defer sending confirm after peer's Public Key is validated
**Describe the bug**
Currently SMP Confirm is send regardless if peer's public key is valid or not, as PK validation is done asynchronously when DHKeyCheck is computed. This results in SMP qualification failures for new TCRL 2024-2 tests which validate this behavior.

**To Reproduce**
Execute SM/CEN/KDU/BI-04-C qualification test case with AutoPTS.
SM/PER/KDU/BI-04-C is probably also affected but mentioned issue is not triggered by current setup (fails due to other issue).

**Expected behavior**
Test pass and IUT is not sending own confirm value if lower tester is using illegal Public Key.

**Impact**
Bluetooth qualification for Core 6.0 is affected.

**Additional context**
I looked at current SMP implementation and see two possible solution for this problem:
1) Add set of extra states and flags to delay confirm until PK is validated,  this is non-trivial as there is also user interaction involved and we already have set of flags that handle delayed DHKeyCheck.  Not sure if we should add more complexity into this.

2) Provide synchronous API in ecc.h that would allow for PK validation directly in PK rx handler (this would probably also fix SM/PER/KDU/BI-04-C as we would not hit test spec issue if rejected early). This would be similar to how debug key is checked.

 I'm more in favor of 2) but I'm not sure on how feasible it is eg. is PSA is used.

image

### PR DESCRIPTION
**Pull request by jhedberg**
Add a separate test for public key validity. This needs to be done synchronously so that we can respond with an early failure message to the peer device.

Fixes #80218

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr SM/PER/KDU/BI-04-C

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests (1)</summary>SM      SM/PER/KDU/BI-04-C              FAIL</details>

**Comment by jhedberg** [comment]
#AutoPTS run zephyr SM/PER/KDU/BI-04-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/82741#issuecomment-2528532867, board: nrf52, estimated start time: 17:16:14, test case count: 1, estimated duration: 0:00:34<details><summary>Test cases to be run</summary>SM/PER/KDU/BI-04-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests (1)</summary>SM      SM/PER/KDU/BI-04-C              PASS</details>

**Review by sjanc — DISMISSED** [review]

File: subsys/bluetooth/host/ecc.c [hunk 1]
```diff
@@ -39,6 +42,34 @@ bool bt_pub_key_is_debug(uint8_t *cmp_pub_key)
...
+
+	psa_set_key_type(&attr, PSA_KEY_TYPE_ECC_PUBLIC_KEY(PSA_ECC_FAMILY_SECP_R1));
+	psa_set_key_bits(&attr, 256);
+	psa_set_key_usage_flags(&attr, PSA_KEY_USAGE_DERIVE);
+	psa_set_key_algorithm(&attr, PSA_ALG_ECDH);
+
+	key_be[0] = 0x04;
+	sys_memcpy_swap(&key_be[1], key, BT_PUB_KEY_COORD_LEN);
+	sys_memcpy_swap(&key_be[1 + BT_PUB_KEY_COORD_LEN], &key[BT_PUB_KEY_COORD_LEN],
+			BT_PUB_KEY_COORD_LEN);
```
Comment (Thalley) [inline subsys/bluetooth/host/ecc.c:60]: As someone who isn't 100% familiar with this, what does `0x04` refer to? 

It seems that `key_be` contains both the public key, and some 1 octet header

File: subsys/bluetooth/host/ecc.h [hunk 2]
```diff
@@ -44,6 +44,16 @@ struct bt_pub_key_cb {
...
 
+/*  @brief Check if public key is valid.
+ *
+ *  Verify that the public key is valid, e.g. that its coordinates lie on the eliptic curve.
+ *
+ *  @param key The public key to validate.
+ *
+ *  @return True if the public key is valid.
+ */
+bool bt_pub_key_is_valid(const uint8_t *key);
```
Comment (Thalley) [inline subsys/bluetooth/host/ecc.h:55]: Suggest to define the size of the key. I assume it's a static size of 64 octets?

File: subsys/bluetooth/host/ecc.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/ecc.c:60]: https://github.com/zephyrproject-rtos/zephyr/blob/4488ed1a20a97007d451d2ac1f093c413c56e77a/subsys/bluetooth/host/hci_ecc.c#L124-L128

I didn't feel like duplicating that code comment, but I could add something short if you insist :)

Comment (jhedberg) [reply subsys/bluetooth/host/ecc.c:60]: And:
https://github.com/zephyrproject-rtos/zephyr/blob/4488ed1a20a97007d451d2ac1f093c413c56e77a/subsys/bluetooth/host/hci_ecc.c#L195-L198

Comment (jhedberg) [reply subsys/bluetooth/host/ecc.c:61]: I added a one line comment

File: subsys/bluetooth/host/ecc.h [hunk 3]
```diff
@@ -44,6 +44,16 @@ struct bt_pub_key_cb {
  */
 bool bt_pub_key_is_debug(uint8_t *cmp_pub_key);
 
+/*  @brief Check if public key is valid.
+ *
+ *  Verify that the public key is valid, e.g. that its coordinates lie on the eliptic curve.
+ *
+ *  @param key The public key to validate.
+ *
+ *  @return True if the public key is valid.
```
Comment (Thalley) [inline subsys/bluetooth/host/ecc.h:53]:
```suggestion
 *  @return true if the public key is valid.
```
Minor semantics :D

**Review by Thalley — APPROVED** [review]

**Review by sjanc — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Comment by kartben** [comment]
@jhedberg haven't looked closely but it looks like this *could* have been introducing the following test failures in main? https://github.com/zephyrproject-rtos/zephyr/actions/runs/12284474398/job/34280327763#step:11:1
Could you have a look? Thanks!

**Comment by jhedberg** [comment]
@kartben if a quick fix is required, the only solution I can offer is to remove this test case, since I'm not familiar with how these unit_testing tests are constructed and how/where the mocks are done. I can se that there's code under `tests/bluetooth/host/crypto` including `psa/crypto.h`, and some kind of mocks under `tests/bluetooth/host/crypto/mocks`, but I'm not sure how to translate this to what's needed under `tests/bluetooth/host/ecc` (which is where the failing tests are). @ahmedmoheb-nordic since you seem to be the author of these unit tests, could you please look into it? Thanks.

**Comment by jhedberg** [comment]
FWIW, I did try this:
```patch
diff --git a/tests/bluetooth/host/ecc/CMakeLists.txt b/tests/bluetooth/host/ecc/CMakeLists.txt
index 4f3af9f8160..939ee1b26f4 100644
--- a/tests/bluetooth/host/ecc/CMakeLists.txt
+++ b/tests/bluetooth/host/ecc/CMakeLists.txt
@@ -19,6 +19,7 @@ target_include_directories(mocks PUBLIC
   ${ZEPHYR_BASE}/subsys/bluetooth/host
   ${ZEPHYR_BASE}/tests/bluetooth/host
   ${ZEPHYR_BASE}/tests/bluetooth/host/ecc/mocks
+  ${ZEPHYR_MBEDTLS_MODULE_DIR}/include
 )
 
 target_link_libraries(mocks PRIVATE test_interface)
```

However, that still leaves some other build errors.

**Comment by jhedberg** [comment]
Short term solution to remove the problematic tests: #82924 

FWIW, while the missing include lookup path (mentioned in https://github.com/zephyrproject-rtos/zephyr/pull/82741#issuecomment-2538608571) should fix the issue introduced by this PR, it seems that there was other breakage already there before this PR (related to devicetree includes).
