### PR TITLE
llext: fix minor Coverity issue #434586

### LINKED ISSUE #81964: [Coverity CID: 434586] Uninitialized scalar variable in subsys/llext/llext_link.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/subsys/llext/llext_link.c

Category: Uninitialized variables
Function: `llext_link_plt`
Component: Other
CID: [434586](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434586)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/subsys/llext/llext_link.c

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434586

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNINIT). ([CWE-457](http://cwe.mitre.org/data/definitions/457.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by pillo79**
The check combination of "is zero" and then "less than zero" leaves open the theoretical possibility of  `llext_seek()` returning a positive value, which would cause the function to continue on with an uinitialized `rela`.

Checking for "not zero" has the same effect and covers all situations.

Fixes #81964.

### CODE REVIEW

File: subsys/llext/llext_link.c [hunk 1]
```diff
@@ -168,7 +168,7 @@ static void llext_link_plt(struct llext_loader *ldr, struct llext *ext, elf_shdr
 			ret = llext_read(ldr, &rela, sizeof(rela));
 		}
 
-		if (ret < 0) {
+		if (ret != 0) {
```
Comment (teburd) [inline subsys/llext/llext_link.c:171]: This just looks odd I have to say, but I get the reasoning

**Review by teburd — APPROVED** [review]

**Review by jilaypandya — APPROVED** [review]

File: subsys/llext/llext_link.c (hunk 1 above)
Comment (lyakh) [reply subsys/llext/llext_link.c:171]: @pillo79 is that allowed by the API? In fact shouldn't we move `llext_seek()` and friends from under `@cond ignore` and properly document them, thus specifying what they should return? If a function can only return 0 or a negative error, I think it's common to check `< 0` and `== 0` only, leaving impossible `> 0` uncovered
