### PR TITLE
subsys/fs: fix readdir misuse in FatFs and Zephyr wrapper

### LINKED ISSUE #19697: tests/subsys/fs/fat_fs_api uses unitialized variables
**Describe the bug**
valgrind detected issue in tests/subsys/fs/fat_fs_api
Using an unitialized variable in the filesystem code: fs_readdir (fs.c:264)

**To Reproduce**
1. mkdir build; cd build
2. cmake ../tests/subsys/fs/fat_fs_api/ -DBOARD=native_posix -GNinja 
3. ninja
4. valgrind zephyr/zephyr.exe

**Expected behavior**
No use of uninitialized variables

**Impact**
Unknown

**Screenshots or console output**
```
==9631== Memcheck, a memory error detector
==9631== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==9631== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==9631== Command: zephyr/zephyr.exe
==9631== 
I: Device flash_ctrl initialized
***** Booting Zephyr OS build zephyr-v2.0.0-1066-ga3bc87504c8d *****
Running test suite fat_fs_basic_test
===================================================================
starting test - test_fat_mount
PASS - test_fat_mount
===================================================================
starting test - test_fat_file

Open tests:
E: failed get file or dir stat (-2)
Creating new file /NAND:/testfile.txt
Opened file /NAND:/testfile.txt

Write tests:
Data written:"hello world!"

Data successfully written!

Sync tests:

Read tests:
Data read:"hello world!"

Data read matches data written

Truncate tests:

Testing shrink to 0 size
Testing write after truncating

Write tests:
Data written:"hello world!"

Data successfully written!
Original size of file = 12

Testing shrinking
File size after shrinking by 5 bytes = 7

Testing expanding
File size after expanding by 10 bytes = 17
Testing for zeroes in expanded region

Close tests:
Closed file /NAND:/testfile.txt

Delete tests:
E: failed get file or dir stat (-2)
File (/NAND:/testfile.txt) deleted successfully!
PASS - test_fat_file
===================================================================
starting test - test_fat_dir

mkdir tests:
E: failed get file or dir stat (-2)
Creating new dir /NAND:/testdir

Write tests:
Data written:"hello world!"

Data successfully written!
Created dir /NAND:/testdir!

lsdir tests:

Listing dir /NAND::
[DIR ] TESTDIR
==9631== Thread 2:
==9631== Conditional jump or move depends on uninitialised value(s)
==9631==    at 0x11114E: fs_readdir (fs.c:264)
==9631==    by 0x10CDE5: test_lsdir (test_fat_dir.c:83)
==9631==    by 0x10D106: test_fat_dir (test_fat_dir.c:162)
==9631==    by 0x111F40: run_test_functions (ztest.c:135)
==9631==    by 0x111F40: test_cb (ztest.c:271)
==9631==    by 0x10DFBB: z_thread_entry (thread_entry.c:29)
==9631==    by 0x10EE90: posix_thread_starter (posix_core.c:305)
==9631==    by 0x49683BC: start_thread (pthread_create.c:463)
==9631==    by 0x4A79E15: clone (clone.S:108)
==9631== 

lsdir tests:

Listing dir /NAND:/testdir:
[FILE] TESTFILE.TXT (size = 12)
==9631== Conditional jump or move depends on uninitialised value(s)
==9631==    at 0x11114E: fs_readdir (fs.c:264)
==9631==    by 0x10CDE5: test_lsdir (test_fat_dir.c:83)
==9631==    by 0x10D13C: test_fat_dir (test_fat_dir.c:163)
==9631==    by 0x111F40: run_test_functions (ztest.c:135)
==9631==    by 0x111F40: test_cb (ztest.c:271)
==9631==    by 0x10DFBB: z_thread_entry (thread_entry.c:29)
==9631==    by 0x10EE90: posix_thread_starter (posix_core.c:305)
==9631==    by 0x49683BC: start_thread (pthread_create.c:463)
==9631==    by 0x4A79E15: clone (clone.S:108)
==9631== 

rmdir tests:

Removing files and sub directories in /NAND:/testdir
Removing /NAND:/testdir/TESTFILE.TXT
==9631== Conditional jump or move depends on uninitialised value(s)
==9631==    at 0x11114E: fs_readdir (fs.c:264)
==9631==    by 0x10CECF: test_rmdir (test_fat_dir.c:126)
==9631==    by 0x10D16D: test_fat_dir (test_fat_dir.c:164)
==9631==    by 0x111F40: run_test_functions (ztest.c:135)
==9631==    by 0x111F40: test_cb (ztest.c:271)
==9631==    by 0x10DFBB: z_thread_entry (thread_entry.c:29)
==9631==    by 0x10EE90: posix_thread_starter (posix_core.c:305)
==9631==    by 0x49683BC: start_thread (pthread_create.c:463)
==9631==    by 0x4A79E15: clone (clone.S:108)
==9631== 
Removed dir /NAND:/testdir!

lsdir tests:

Listing dir /NAND::
==9631== Conditional jump or move depends on uninitialised value(s)
==9631==    at 0x11114E: fs_readdir (fs.c:264)
==9631==    by 0x10CDE5: test_lsdir (test_fat_dir.c:83)
==9631==    by 0x10D1A3: test_fat_dir (test_fat_dir.c:165)
==9631==    by 0x111F40: run_test_functions (ztest.c:135)
==9631==    by 0x111F40: test_cb (ztest.c:271)
==9631==    by 0x10DFBB: z_thread_entry (thread_entry.c:29)
==9631==    by 0x10EE90: posix_thread_starter (posix_core.c:305)
==9631==    by 0x49683BC: start_thread (pthread_create.c:463)
==9631==    by 0x4A79E15: clone (clone.S:108)
==9631== 
PASS - test_fat_dir
```

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 18.04)
 - Toolchain Host gcc
 - Commit SHA (todays master) a3bc87504c8d4e8946b8b8fd8c5ee13198f0f314

### PR DESCRIPTION
**Pull request by pabigot**
Two locations failed to properly handle detection of the end of available directory entries.

Fixes #19697.

### CODE REVIEW

**Review by aescolar — APPROVED** [review]
I'm certainly not an expert in the FAT fs code, but lacking a better reviewer I can approve.

**Review by carlescufi — APPROVED** [review]
LGTM

File: subsys/fs/fat_fs.c [hunk 1]
```diff
@@ -270,10 +270,12 @@ static int fatfs_readdir(struct fs_dir_t *zdp, struct fs_dirent *entry)
 
 	res = f_readdir(zdp->dirp, &fno);
 	if (res == FR_OK) {
-		entry->type = ((fno.fattrib & AM_DIR) ?
-			       FS_DIR_ENTRY_DIR : FS_DIR_ENTRY_FILE);
 		strcpy(entry->name, fno.fname);
```
Comment (nvlsianpu) [inline subsys/fs/fat_fs.c]: Does worth to use strncpy with FATFS_MAX_FILE_NAME?

Comment (pabigot) [reply subsys/fs/fat_fs.c]: The destination buffer is allocated to `MAX_FILE_NAME + 1` where `MAX_FILE_NAME` is either 12 or 256 depending on what filesystems are enabled.

`FATFS_MAX_FILE_NAME` is always 12.

The `FILINFO` struct source buffer will be either 13 or (if LFN is enabled) `1+_MAX_LFN` and it will always be NUL-terminated.

LFN is not enabled in the standard Zephyr FatFS configuration.

So, unless LFN is enabled (in which case this wrapper needs to be updated) IMO this is fine as it was originally.  If we switch to `strncpy` just for safety then we also have to handle the case where the copied value isn't NUL-terminated.

I'd rather leave it as is.

OK?

Comment (nvlsianpu) [reply subsys/fs/fat_fs.c]: ok

**Review by nvlsianpu — APPROVED** [review]
