### PR TITLE
boards: up_squared_adsp: fix mis-used logical operator

### LINKED ISSUE #22651: [Coverity CID :208198] Logical vs. bitwise operator in boards/xtensa/up_squared_adsp/bootloader/boot_loader.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/e089906b339aad4cd1b6589a3b6ce94782d93f54/boards/xtensa/up_squared_adsp/bootloader/boot_loader.c#L119

Category: Integer handling issues
Function: `lp_sram_init`
Component: Other
CID: [208198](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=208198)

Details:

```
113         shim_write(SHIM_LDOCTL, SHIM_LDOCTL_LPSRAM_LDO_ON);
114    
115         /* add some delay before writing power registers */
116         idelay(delay_count);
117    
118         lspgctl_value = shim_read(LSPGCTL);
>>>     CID 208198:  Integer handling issues  (CONSTANT_EXPRESSION_RESULT)
>>>     "lspgctl_value & 0U /* !((1 << 2) - 1) */" is always 0 regardless of the values of its operands. This occurs as an argument to a function call.
119         shim_write(LSPGCTL, lspgctl_value & !LPSRAM_MASK(0));
120    
121         /* add some delay before checking the status */
122         idelay(delay_count);
123    
124         /* query the power status of first part of LP memory */
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by dcpleung**
In the bootloader code, there is a mis-used logical operator
which should be bitwise operator. So fix it.

Fixes #22651
Coverity-CID: 208198

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

File: boards/xtensa/up_squared_adsp/bootloader/boot_loader.c [hunk 1]
```diff
@@ -116,7 +116,7 @@ static int32_t lp_sram_init(void)
 	idelay(delay_count);
 
 	lspgctl_value = shim_read(LSPGCTL);
-	shim_write(LSPGCTL, lspgctl_value & !LPSRAM_MASK(0));
+	shim_write(LSPGCTL, lspgctl_value & ~LPSRAM_MASK(0));
```
Comment (finikorg) [inline boards/xtensa/up_squared_adsp/bootloader/boot_loader.c]: Looks like parameter in the macro is never used, so it may be improved.

**Review by finikorg — APPROVED** [review]
