### PR TITLE
Various fixes for NIOS2 MAX10

### LINKED ISSUE #35694: No console output from NIOS2 Max10
**Describe the bug**
Nothing comes out of the console

**To Reproduce**
1. Build anything and flash

**Expected behavior**

Messages should come out on the console

**Impact**
Board unusable.

### PR DESCRIPTION
**Pull request by nashif**
﻿- nios2: max10: fix uart0 base register
- nios2: revert back to builtin sys_io functions
- boards: max10: fix function name in debug section

Fixes #35694

### CODE REVIEW

File: include/arch/nios2/asm_inline_gcc.h [hunk 1]
```diff
@@ -14,7 +14,49 @@
...
+}
+
+static ALWAYS_INLINE
+	void sys_write16(uint16_t data, mm_reg_t addr)
+{
+	sys_write32(data, addr);
+}
+
+static ALWAYS_INLINE
+	uint16_t sys_read16(mm_reg_t addr)
```
Comment (ceolin) [inline include/arch/nios2/asm_inline_gcc.h:55]: is this indentation correct ?

**Review by ceolin — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
