### PR TITLE
Bluetooth: ISO: Support bt_disable

### LINKED ISSUE #69742: Bluetooth: Fails to create BIG after bt_disable()
**Describe the bug**
Using bt_disable with active Broadcast ISO instance created and followed by bt_enable to create a new BIG instance fails.

Relates to: https://github.com/zephyrproject-rtos/zephyr/issues/59099
and
https://github.com/zephyrproject-rtos/zephyr/pull/69518

```
d_01: @00:00:25.317063  Bluetooth re-initializing...success.
d_01: @00:00:25.317783  Create advertising set...success.
d_01: @00:00:25.318623  Setting Periodic Advertising parameters...success.
d_01: @00:00:25.318623  Enable Periodic Advertising...success.
d_01: @00:00:25.319823  Start extended advertising...success.
d_01: @00:00:25.319823  Creating BIG...
d_01: @00:00:25.319823 ERROR: (WEST_TOPDIR/zephyr/tests/bsim/bluetooth/ll/bis/src/main.c:330): Could not create BIG: -12
d_01: @00:00:25.319823  The TESTCASE FAILED (test return code 2)
```
**To Reproduce**
Build and test the `tests/bsim/bluetooth/ll/bis` tests.

**Expected behavior**
Successful repeated success in creating BIG after each bt_disable-bt_enable interation.

**Impact**
showstopper

**Logs and console output**
Refer to bsim test failure here: https://github.com/zephyrproject-rtos/zephyr/actions/runs/8064362123/job/22028088345?pr=69518

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/69518/commits/53b94f2f56f3e4a5e7c7625264f2c31c43a67517

**Additional context**
NA

### PR DESCRIPTION
**Pull request by Thalley**
Add support for bt_disable in the ISO implementation. This involves clearing all information related to states in the controller, such as the BIGs and CIGs.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/69742

### CODE REVIEW

File: tests/bsim/bluetooth/host/iso/bis/src/bis_broadcaster.c [hunk 1]
```diff
@@ -0,0 +1,326 @@
...
+{
+	int err;
+
+	LOG_INF("Starting extended and periodic advertising");
+
+	/* Start extended advertising */
+	err = bt_le_ext_adv_start(adv, BT_LE_EXT_ADV_START_DEFAULT);
+	TEST_ASSERT(err == 0, "Failed to start extended advertising: %d", err);
+
+	/* FIXME: Temporary workaround to get around an assert in the controller */
```
Comment (jori-nordic) [inline tests/bsim/bluetooth/host/iso/bis/src/bis_broadcaster.c:179]: what's the assert? It would be nice to have an issue number in the comment.

File: tests/bsim/bluetooth/host/iso/bis/src/common.c [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+extern enum bst_result_t bst_result;
+
+void test_init(void)
+{
+	bst_result = In_progress;
+	bst_ticker_set_next_tick_absolute(WAIT_TIME);
+}
+
+void test_tick(bs_time_t HW_device_time)
```
Comment (jori-nordic) [inline tests/bsim/bluetooth/host/iso/bis/src/common.c:26]: I think you could use the `test_delete_f` callback instead (see https://github.com/jori-nordic/zephyr/blob/f2e3d3f951112ffec7f3a1a40bcf0c187dcae40e/tests/bsim/bluetooth/host/misc/sample_test/src/main.c#L18-L35).
Then you don't need `common.h` at all (since you won't need `test_init()` any more)

**Review by jori-nordic — DISMISSED** [review]

**Review by jhedberg — DISMISSED** [review]

**Review by jori-nordic — APPROVED** [review]
thanks

File: tests/bsim/bluetooth/host/iso/bis/src/common.c (hunk 2 above)
Comment (Thalley) [reply tests/bsim/bluetooth/host/iso/bis/src/common.c:26]: Hmm, looked into this. 

I would then either have to implement this function in each source file or still need the common files, so it doesn't really change anything in terms of files needed or structure. 

There is also the alternative that some tests are using where they keep the common functionality in `main.c` as the above and replace the header file with `extern` instead. Not sure if that is really better.

Comment (jori-nordic) [reply tests/bsim/bluetooth/host/iso/bis/src/common.c:26]: yeah it was just a nit, don't need to act on it.
For next time maybe :+1:

**Review by jhedberg — APPROVED** [review]
