### PR TITLE
drivers: timer: Use prescale_glitch_filter for prescale setting

### LINKED ISSUE #97833: tests: benchmark.kernel.footprints.pm: all NXP ke series build failure
### Describe the bug

- frdm_ke15z
- frdm_ke17z/ke17z512
- twr_ke18f

eb785ef63b75867f71624c16dafa787757ddc6d0 is the first bad commit
commit eb785ef63b75867f71624c16dafa787757ddc6d0
Author: Felix Wang <fei.wang_3@nxp.com>
Date:   Fri Aug 29 18:25:40 2025 +0800

    drivers: Counter: Fix LPTMR prescaler setting not work issue
    
    In current code, if timer-mode-sel is 0(Timer Counter Mode),
    bypass_prescaler_glitch will be 1, that makes prescaler setting
    be bypassed. But this setting is very useful, especially for
    long timing count.
    
    In this patch, we update prescale-glitch-filter default value to 0,
    to indicate prescaler and glitch filter are disabled, which comply
    the existing devices DTS setting (prescaler = 1).
    And if user sets prescale-glitch-filter properity other than 0,
    we should set bypass_prescaler_glitch to false to make prescaler work,
    and the clock frequence should be calculated with prescaler setting.
    
    Update prescaler field in dt-bindings to tell developer should use
    prescale-glitch-filter instead.
    
    Signed-off-by: Felix Wang <fei.wang_3@nxp.com>

### Regression

- [x] This is a regression.

### Steps to reproduce

```
west build -b frdm_ke15z tests/benchmarks/footprints -- -DCONF_FILE=prj_pm.conf
```

### Relevant log output

```shell
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/timer/mcux_lptmr_timer.c:45:25:
note: in expansion of macro 'TO_LPTMR_PRESCALER' 45 | #define LPTMR_PRESCALER TO_LPTMR_PRESCALER(DT_INST_PROP(0, prescaler)); | ^~~~~~~~~~~~~~~~~~/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/timer/mcux_lptmr_timer.c:
113:24: note: in expansion of macro 'LPTMR_PRESCALER' 113 | config.value = LPTMR_PRESCALER; | ^~~~~~~~~~~~~~~/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/timer/mcux_lptmr_timer.c:
37:44: note: each undeclared identifier is reported only once for each function it appears in 37 | #define TO_LPTMR_PRESCALER(val) _DO_CONCAT(LPTMR_PRESCALER_, val) | ^~~~~~~~~~~~~~~~/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/toolchain/common.h:
168:26: note: in definition of macro '_DO_CONCAT' 168 | #define _DO_CONCAT(x, y) x ## y | ^/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/timer/mcux_lptmr_timer.c:45:25: note: in expansion of macro 'TO_LPTMR_PRESCALER' 45 | #define LPTMR_PRESCALER TO_LPTMR_PRESCALER(DT_INST_PROP(0, prescaler)); | ^~~~~~~~~~~~~~~~~~/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/drivers/timer/mcux_lptmr_timer.c:
113:24: note: in expansion of macro 'LPTMR_PRESCALER' 113 | config.value = LPTMR_PRESCALER; | ^~~~~~~~~~~~~~~ninja: build stopped: subcommand failed.
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: ubuntu
- toolchain: Zephyr
- version: v4.2.0-6134-g6b8fcaeecf95

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by FelixWang47831**
In eb785ef, "prescaler" has been deprecated and
"prescale_glitch_filter" is used for prescaler setting.

This patch removes "prescaler" parameter in timer
driver and use "prescale_glitch_filter" to simplify code 
and fix build error caused by "precsaler" parameter.

### CODE REVIEW

**Comment by FelixWang47831** [comment]
This patch fixes #97833

File: drivers/timer/mcux_lptmr_timer.c [hunk 1]
```diff
@@ -17,33 +17,14 @@
...
 /* Prescaler clock mapping */
 #define TO_LPTMR_CLK_SEL(val) _DO_CONCAT(kLPTMR_PrescalerClock_, val)
 
 /* Devicetree properties */
 #define LPTMR_BASE ((LPTMR_Type *)(DT_INST_REG_ADDR(0)))
 #define LPTMR_CLK_SOURCE TO_LPTMR_CLK_SEL(DT_INST_PROP(0, clk_source));
-#define LPTMR_PRESCALER TO_LPTMR_PRESCALER(DT_INST_PROP(0, prescaler));
-#define LPTMR_BYPASS_PRESCALER DT_INST_PROP(0, prescaler) == 1
+#define LPTMR_PRESCALER BIT(DT_INST_PROP(0, prescale_glitch_filter));
+#define LPTMR_BYPASS_PRESCALER (DT_INST_PROP(n, prescale_glitch_filter) == 0)
```
Comment (hakehuang) [inline drivers/timer/mcux_lptmr_timer.c]: this revise the logic before, do you mean this?

Comment (FelixWang47831) [reply drivers/timer/mcux_lptmr_timer.c]: Yes, since "prescaler" has been marked deprecated in dts bindings.
"prescaler == 1", means the clock is not divided, in other words, prescaler is bypassed, equals "prescale_glitch_filter == 0".
And "prescaler" has been removed from devicetree file in this PR: https://github.com/zephyrproject-rtos/zephyr/pull/95263/commits/ed9c807816b5be4841dec59c281f74c342851e0d

Comment (hakehuang) [reply drivers/timer/mcux_lptmr_timer.c]: thanks @FelixWang47831 do you run any test against your changes? and in this case you just need
```suggest
#define LPTMR_PRESCALER BIT(DT_INST_PROP(n, prescale_glitch_filter, 0))
#define LPTMR_BYPASS_PRESCALER  (~LPTMR_PRESCALER)
```

Comment (FelixWang47831) [reply drivers/timer/mcux_lptmr_timer.c]: Hi @hakehuang Sorry there is a typo "DT_INST_PROP(n, prescale_glitch_filter)" should be "DT_INST_PROP(0, prescale_glitch_filter)", has been updated.

I have ran test below and test pass:
west build -b frdm_ke17z tests/benchmarks/footprints -- -DCONF_FILE=prj_pm.conf

```
*** Booting Zephyr OS build v4.2.0-6180-gf6c326150a3e ***
Hello from frdm_ke17z!

 PM device get state did not fail
PROJECT EXECUTION SUCCESSFUL
```

I think the line below can not work:
#define LPTMR_BYPASS_PRESCALER  (~LPTMR_PRESCALER)

When prescale_glitch_filter=2, LPTMR_PRESCALER = 1 << 2, LPTMR_BYPASS_PRESCALER = 0xFFFF_FFFB, in the code below, config.bypassPrescaler will be true, that's not what we want.

#if LPTMR_BYPASS_PRESCALER
	config.bypassPrescaler = true;
#else /* LPTMR_BYPASS_PRESCALER */
	config.bypassPrescaler = false;

Comment (hakehuang) [reply drivers/timer/mcux_lptmr_timer.c]: thanks for check, why it should be DT_INST_PROP(0, prescale_glitch_filter)? 
and what's more, we can change the code directly without  #else 
```
config.bypassPrescaler = !!LPTMR_PRESCALER;
```

Comment (FelixWang47831) [reply drivers/timer/mcux_lptmr_timer.c]: Just follow previous code, it was intended to use lptmr0 as timer.
This patch mainly focus on build issue fix. I'll check if we can improve it in future.

Comment (hakehuang) [reply drivers/timer/mcux_lptmr_timer.c]: > Just follow previous code, it was intended to use lptmr0 as timer.
> This patch mainly focus on build issue fix. I'll check if we can improve it in future.

I would suggest to fix it once here, it is not complex.

Comment (FelixWang47831) [reply drivers/timer/mcux_lptmr_timer.c]: Hi @hakehuang 
I have checked timer drivers from other vendor, they all get hardcode index instance, for example:
```
// Microchip
const int32_t z_sys_timer_irq_for_test = DT_INST_IRQN(0);

const static struct sam_pit64b_cfg pit64b_cfg = {
		.reg = (pit64b_registers_t *)DT_INST_REG_ADDR(0),
	};

```

```
// Nuvoton
static struct itim64_reg *const sys_tmr = (struct itim64_reg *)
					DT_INST_REG_ADDR_BY_NAME(0, sys_itim);
```

```
// nordic
#define RTC NRF_RTC1
BUILD_ASSERT(DT_NODE_HAS_STATUS(DT_NODELABEL(RTC_LABEL), disabled),
	     "Counter for RTC1 must be disabled");
```

```
// ST
#define LPTIM (LPTIM_TypeDef *) DT_INST_REG_ADDR(0)
```

```
// TI
#define TIMER_IRQ_NUM   DT_INST_IRQN(0)
#define TIMER_IRQ_PRIO  DT_INST_IRQ(0, priority)
```

I don't know the history, but it must have some reasons to do it.

Comment (hakehuang) [reply drivers/timer/mcux_lptmr_timer.c]: @henrikbrixandersen do you recall the reason why only implement lptmr0?

Comment (henrikbrixandersen) [reply drivers/timer/mcux_lptmr_timer.c]: I believe I originally implemented this driver for use on the KE1xF, which only has one instance.

Comment (FelixWang47831) [reply drivers/timer/mcux_lptmr_timer.c]: @hakehuang 
Unlike other device driver like adc or counter, which support multiple devices(the driver APIs pass device as parameters):
```
// counter
typedef int (*counter_api_start)(const struct device *dev);
```
```
// adc
typedef int (*adc_api_read)(const struct device *dev,
			    const struct adc_sequence *sequence);
```

timer driver API does not pass "device" parameter, which means developer must use a specific timer instance
```
// zephyr\include\zephyr\drivers\timer\system_timer.h
void sys_clock_set_timeout(int32_t ticks, bool idle);
```

```
// zephyr\drivers\timer\mcux_lptmr_timer.c
#define LPTMR_BASE ((LPTMR_Type *)(DT_INST_REG_ADDR(0)))

void sys_clock_set_timeout(int32_t ticks, bool idle)
{
	ARG_UNUSED(idle);

	if (idle && (ticks == K_TICKS_FOREVER)) {
		LPTMR_DisableInterrupts(LPTMR_BASE, kLPTMR_TimerInterruptEnable);
	}
}
```

Comment (hakehuang) [reply drivers/timer/mcux_lptmr_timer.c]: > timer driver API does not pass "device" parameter, which means developer must use a specific timer instance

Yes, there is only one timer can be selected as system timer. but not necessary a fixed `0`, Besides in multi-core cases, we have to define more. This can be defined in dts, and add by `zephyr,systimer`. I agree that this can be done late.

File: drivers/timer/mcux_lptmr_timer.c [hunk 2]
```diff
@@ -17,33 +17,14 @@
...
 /* Prescaler clock mapping */
 #define TO_LPTMR_CLK_SEL(val) _DO_CONCAT(kLPTMR_PrescalerClock_, val)
 
 /* Devicetree properties */
 #define LPTMR_BASE ((LPTMR_Type *)(DT_INST_REG_ADDR(0)))
 #define LPTMR_CLK_SOURCE TO_LPTMR_CLK_SEL(DT_INST_PROP(0, clk_source));
-#define LPTMR_PRESCALER TO_LPTMR_PRESCALER(DT_INST_PROP(0, prescaler));
-#define LPTMR_BYPASS_PRESCALER DT_INST_PROP(0, prescaler) == 1
+#define LPTMR_PRESCALER BIT(DT_INST_PROP(0, prescale_glitch_filter));
+#define LPTMR_BYPASS_PRESCALER (DT_INST_PROP(0, prescale_glitch_filter) == 0)
```
Comment (hakehuang) [inline drivers/timer/mcux_lptmr_timer.c]: LPTMR_BYPASS_PRESCALER can be replaced by  (!!LPTMR_PRESCALER ) 
so the if else macro is not needed.

Comment (FelixWang47831) [reply drivers/timer/mcux_lptmr_timer.c]: Fixed

**Review by hakehuang — APPROVED** [review]
regression test pass

**Review by dleach02 — APPROVED** [review]
