### PR TITLE
lib/libc/Kconfig: Fix libC depends with NATIVE_APPlICATION

### LINKED ISSUE #78427: tests/lib/c_lib/common/libraries.libc.common.minimal runs and fails in native_posix
**Describe the bug**
tests/lib/c_lib/common/libraries.libc.common.minimal is incorrectly filtered, runs and fails in native_posix

**To Reproduce**
1. twister -s tests/lib/c_lib/common/libraries.libc.common.minimal -p native_posix
2. see failure

**Expected behavior**
Test does not run (and therefore does not hang)

**Impact**
Failures in CI when this test is triggerd

**Logs and console output**
See hung test:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/10851581749/job/30115909238?pr=78390#step:12:1294

**Environment (please complete the following information):**

 - OS: CI, Linux Ubuntu 22.04
 - Toolchain (e.g Zephyr SDK, ...): gcc 11/12
 - Commit SHA or Version used: Main as of now 50b07f9480a49f2b489ade9dae98b91fc3f2a643

**Additional context**
The test started hanging after fe94d4354a7528aa3408970564941e2a2e8c7f74, but the incorrect filter issue has been present for a long while

### PR DESCRIPTION
**Pull request by aescolar**
NATIVE_APPlICATION (old native_posix) does not support bulding with the any other C library than the host libC (EXTERNAL_LIBC).

MINIMAL_LIBC_SUPPORTED defaulted to y always, and instead the depends was set in the LIBC_IMPLEMENTATION choice.
This lead to the right library selected, but an incorrectly set MINIMAL_LIBC_SUPPORTED.
Many tests filter based on MINIMAL_LIBC_SUPPORTED, so they were not filtered out appropriately.

Let's place the depends in the right place to avoid this problem. Also remove a redundant depends on for PICOLIBC and NEWLIB_LIBC which already have the dependency in their respective _SUPPORTED option.

Fixes #78427
@keith-packard I needed to cherry-pick your fix for that same test from your other PR, as it would otherwise also trigger here.

### CODE REVIEW

File: tests/lib/c_lib/common/src/main.c [hunk 1]
```diff
@@ -1166,6 +1166,9 @@ ZTEST(libc_common, test_time_ctime)
 	char buf[26] = {0};
 	time_t test1 = 1718260000;
 
+#ifdef CONFIG_NATIVE_LIBC
+	setenv("TZ", "UTC", 1);
```
Comment (cfriedt) [inline tests/lib/c_lib/common/src/main.c:1170]: LGTM - it might be helpful to have a comment here as to why this is needed (which IIRC, is because the Zephyr common libc `ctime_r()` implementation assumes UTC timezone, since timezone support is usually beyond the scope of most devices).

Comment (keith-packard) [reply tests/lib/c_lib/common/src/main.c:1170]: That's not completely accurate; newlib and picolibc both support timezones, but those depend on something actually setting the TZ environment variable within the runtime. CONFIG_NATIVE_LIBC is the right test because that's the only library which can inherit external system settings and find a non-UTC timezone.

File: lib/libc/Kconfig [hunk 2]
```diff
@@ -27,6 +27,7 @@ config FULL_LIBC_SUPPORTED
 
 config MINIMAL_LIBC_SUPPORTED
 	bool
+	depends on !NATIVE_APPLICATION
```
Comment (keith-packard) [inline lib/libc/Kconfig:30]: For symmetry, should we add this condition for `NEWLIB_LIBC_SUPPORTED` too?

File: lib/libc/Kconfig [hunk 3]
```diff
@@ -95,7 +94,6 @@ config PICOLIBC
 config NEWLIB_LIBC
 	bool "Newlib C library"
 	select COMMON_LIBC_ABORT
-	depends on !NATIVE_APPLICATION
```
Comment (keith-packard) [inline lib/libc/Kconfig:98]: Yeah, if you remove the condition here, you should add it to `NEWLIB_LIBC_SUPPORTED`.

**Review by keith-packard — CHANGES_REQUESTED** [review]
Need to add `depends on !NATIVE_APPLICATION` to `NEWLIB_LIBC_SUPPORTED`.

**Comment by keith-packard** [comment]
> Fixes #78427 @keith-packard I needed to cherry-pick your fix for that same test from your other PR, as it would otherwise also trigger here.

No worries; if this PR lands before #78354, I'll adapt. Thanks for the warning.

File: tests/lib/c_lib/common/src/main.c (hunk 1 above)
Comment (cfriedt) [reply tests/lib/c_lib/common/src/main.c:1170]: Oh wow - I guess that's something I haven't considered in embedded for a while 😅

File: lib/libc/Kconfig (hunk 3 above)
Comment (aescolar) [reply lib/libc/Kconfig:98]: Changed.
Though note we have `depends on "$(TOOLCHAIN_HAS_NEWLIB)" = "y"` which effectively excludes all builds with host tooling.

**Review by keith-packard — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
LGTM - I just re-ran the documentation job, because it looked like a false positive
