### PR TITLE
drivers: regulator/fixed: Add voltage getter to fix device never ready

### LINKED ISSUE #99339: regulator-fixed is never ready when min/max voltages are specified in DTS
### Describe the bug

`regulator-fixed` DTS bindings allow specifying min and max voltages: https://github.com/zephyrproject-rtos/zephyr/blob/5805685c326b8d7b6385c4ad910b22c9c762adcb/dts/bindings/regulator/regulator-fixed.yaml#L15-L16 
There are checks in place to ensure both min and max are defined and set to the same value. Presumably this fixed voltage can be useful to read in user space or display in the regulator shell.

However when min/max voltages are specified, **`device_is_ready()` always returns false**. 

### Regression

- [ ] This is a regression.

### Steps to reproduce

`app.overlay`
```dts
&{/} {
    dummy_regulator_1v8: reg-1v8 {
        status = "okay";
        compatible = "regulator-fixed";
        regulator-name = "VDD_1V8";
        regulator-min-microvolt = <1800000>;
        regulator-max-microvolt = <1800000>;
        enable-gpios = <&gpioa 1 GPIO_ACTIVE_HIGH>;
        regulator-boot-off;
    };
};
```

`main.c`

```c
#include <stdio.h>
#include <zephyr/kernel.h>

static const struct device *regulator_1v8 =
    DEVICE_DT_GET(DT_NODELABEL(dummy_regulator_1v8));

int main(void) {
  printf("Ready? %s\n", (device_is_ready(regulator_1v8) ? "Yes" : "No"));
  return 0;
}
```

But if you comment out the `regulator-min-microvolt` and `regulator-max-microvolt` properties, you get `Ready? Yes`

### Relevant log output

```shell
*** Booting Zephyr OS build v4.2.0 ***
Ready? No
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Linux
- Toolchain: 
- Commit: 413b789deb391d3a37d06b463288a5fe765ee57e (v4.2.0)

### Additional Context

This problem and possible solutions have started to be discussed here: https://github.com/zephyrproject-rtos/zephyr/discussions/73012

TL;DR:

- @GrygiriiS wonders if using `regulator_common_init()` makes sense in the context of `regulator-fixed`, given how much of it assumes a regulator's voltage can change.
- I'm wondering if a sufficient solution is to provide a voltage read function.

Tangential, but related: I can't build any of the regulator driver tests. Are these being maintained?

```console
$ cd <WORKSPACE>/zephyr/tests/drivers/regulator

$ ../../../scripts/twister --testsuite-root ./

ZEPHYR_BASE unset, using "<WORKSPACE>/zephyr"
INFO    - Using Ninja..
INFO    - Zephyr version: v4.2.0
INFO    - Using 'zephyr' toolchain.
INFO    - Selecting default platforms per testsuite scenario
INFO    - Building initial testsuite list...
INFO    - Writing JSON report <WORKSPACE>/zephyr/tests/drivers/regulator/twister-out/testplan.json
INFO    - JOBS: 6
INFO    - Adding tasks to the queue...
INFO    - Added initial list of jobs to queue
ERROR   - CMake build failure: <WORKSPACE>/zephyr/tests/drivers/regulator/voltage for mcx_n9xx_evk/mcxn947/cpu0
ERROR   - mcx_n9xx_evk/mcxn947/cpu0 tests/drivers/regulator/voltage/drivers.regulator.voltage.nxp ERROR: CMake build failure
ERROR   - see: <WORKSPACE>/zephyr/tests/drivers/regulator/twister-out/mcx_n9xx_evk_mcxn947_cpu0/zephyr/tests/drivers/regulator/voltage/drivers.regulator.voltage.nxp/build.log
   [...]
   [ all other board configs have CMake failures as well ]
   [...]
INFO    - Total complete:   11/  11  100%  built (not run):    0, filtered:   46, failed:    0, error:   11
INFO    - 6 test scenarios (57 configurations) selected, 46 configurations filtered (46 by static filter, 0 at runtime).
INFO    - 0 of 11 executed test configurations passed (0.00%), 0 built (not run), 0 failed, 11 errored, with no warnings in 13.12 seconds.
INFO    - 0 of 111 executed test cases passed (0.00%), 102 blocked, 9 errored on 9 out of total 1115 platforms (0.81%).
INFO    - 0 test configurations executed on platforms, 11 test configurations were only built.

```

[mcx_n9xx_evk_mcxn947_cpu0__zephyr__tests__drivers__regulator__voltage__drivers.regulator.voltage.nxp__build.log](https://github.com/user-attachments/files/23533274/mcx_n9xx_evk_mcxn947_cpu0__zephyr__tests__drivers__regulator__voltage__drivers.regulator.voltage.nxp__build.log)

### PR DESCRIPTION
**Pull request by edt-alex**
When regulator-min-microvolt and regulator-max-microvolt properties are provided in the devicetree node, a fixed regulator is never ready due to failed initialization in regulator_common_init().

At at commit 9463d9a51d9cb1094bf98ef437a39850a7b5705d regulator_common.c lines 68-71, if min or max voltages are set, then regulator_common_init() attempts to get the regulator's current voltage setting so that it might "Snap to closest interval value if out of range." However regulator-fixed has not implemented the regulator_get_voltage() api, so regulator_common_init() fails.

Adding an implementation for regulator_get_voltage() which returns min voltage, just like regulator_fixed_list_voltage() does, resolves this issue.

Fixes zephyrproject-rtos/zephyr#99339

### CODE REVIEW

File: drivers/regulator/regulator_fixed.c [hunk 1]
```diff
@@ -74,11 +74,20 @@ static int regulator_fixed_list_voltage(const struct device *dev,
 	return 0;
 }
 
+static int regulator_fixed_get_voltage(const struct device *dev, int32_t *volt_uv)
+{
+	if (regulator_common_get_min_voltage(dev, volt_uv) < 0) {
+		return -ENOTSUP;
+	}
+	return 0;
```
Comment (seov-nordic) [inline drivers/regulator/regulator_fixed.c]: just return the original error code?
```suggestion
	return regulator_common_get_min_voltage(dev, volt_uv);
```

Comment (edt-alex) [reply drivers/regulator/regulator_fixed.c]: Applied

**Review by seov-nordic — APPROVED** [review]

**Review by nandojve — APPROVED** [review]
