### PR TITLE
drivers: spi: Add optional delays to mcux dspi and lpspi drivers

### LINKED ISSUE #24939: LSPI of NXP i.MX RT timing delay issue
**Describe the bug**
1. Zephyr Can't update DBT/SCKPCS/PCSSCK to nxp_hal according to spi rate， cause spi transfer slow.
2. The delay time calculated by nxp_hal has an overflow problem，will casue no update  DBT/SCKPCS/PCSSCK,cause spi transfer slow.

I submitted 2 pr to solve these problems：
https://github.com/zephyrproject-rtos/hal_nxp/pull/36
https://github.com/zephyrproject-rtos/zephyr/pull/23918

### PR DESCRIPTION
**Pull request by MaureenHelm**
Adds optional device tree properties to set delays between spi chip
select assert/deassert and clock edges in the mcux dspi and lpspi
drivers. If these properties are not set, then the minimum supported
delays are used.

Verified that tests/drivers/spi/spi_loopback/ still passes on
mimxrt1050_evk (lpspi driver) and frdm_k64f (dspi driver).

~~Still need to verify delay timing with a scope.~~

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

Fixes #24939
Alternative to #23918

cc: @lgl88911

### CODE REVIEW

File: drivers/spi/spi_mcux_lpspi.c [hunk 1]
```diff
@@ -275,6 +282,8 @@ static const struct spi_driver_api spi_mcux_driver_api = {
 	.release = spi_mcux_release,
 };
 
+
+
```
Comment (nzmichaelh) [inline drivers/spi/spi_mcux_lpspi.c:286]: nit: three blank lines between macros

**Comment by nzmichaelh** [comment]
LGTM

File: drivers/spi/spi_mcux_lpspi.c (hunk 1 above)
Comment (MaureenHelm) [reply drivers/spi/spi_mcux_lpspi.c]: Thanks, fixed

**Comment by MaureenHelm** [comment]
Moving out of draft status now that I've been able to measure timing with a scope.

Before:
image

After:
image

**Comment by lgl88911** [comment]
@MaureenHelm 
Nice to see this modification, thanks!
I have a question：These delay configurations are not related to the SPI clock freq. When the SPI user set SPI freq by API and the time of unit clock is larger than the delay configurations , the HAL driver will handle this case. automatically calculated the minimum delay matching the clock be used?

**Comment by MaureenHelm** [comment]
> Nice to see this modification, thanks!

Can you confirm this fixes your problem?

> I have a question：These delay configurations are not related to the SPI clock freq. When the SPI user set SPI freq by API and the time of unit clock is larger than the delay configurations , the HAL driver will handle this case. automatically calculated the minimum delay matching the clock be used?

Yes

**Review by henrikbrixandersen — APPROVED** [review]
This looks like a good solution. Thank you.

**Review by agansari — APPROVED** [review]

**Comment by brycewilkins** [comment]
@MaureenHelm Is there a reason SPI driver `drivers/spi/spi_mcux_flexcomm.c` was not updated similarly for chip select delay options?

I'm using i.MX RT685 and `nxp,lpc-spi` binding (with above driver) but unable to delay the chip select assert/deassert from the clock edges.  A similar change to `drivers/spi/spi_mcux_flexcomm.c` as done in this PR would resolve the problem. Would you accept a patch for that?

**Comment by brycewilkins** [comment]
> > Is there a reason SPI driver `drivers/spi/spi_mcux_flexcomm.c` was not updated similarly for chip select delay options?
> 
> Not that I can remember. It may have been just an oversight.
> 
> cc @mmahadevan108

Created issue #40823 for tracking.  I will try putting together a patch.
