### PR TITLE
Bluetooth: Mesh: Fix publication period timestamp initialization

### LINKED ISSUE #17820: Mesh  bug report In access.c
hello everyone:
 When I first call bt_mesh_model_publish on access.c and do not use retransmission, the internal call to pub_send_cb.publish_send, the next_period function is executed, and the pub->period_start state is not initialized, which may cause a malfunction.

## Suggest：

* Add conditional judgments in bt_mesh_model_publish, for example:
```c
if(!pub->count)
{
    pub->period_start=k_uptime_get32();
}
```
* remove pub->period_start=k_uptime_get32 in mod_publish func.

### PR DESCRIPTION
**Pull request by jhedberg**
The period_start timestamp wasn't getting properly initialized in the
case that retransmission was not being used. In the case of
retransmission the timestamp was getting updated in the mod_publish()
delayed work callback. Add a send_start callback and do the
initialization there, since this covers both the retransmission as
well as the no-retransmission cases.

Fixes #17820

Signed-off-by: Johan Hedberg <johan.hedberg@intel.com>

### CODE REVIEW

**Comment by jhedberg** [comment]
@menglingao1997  FYI

**Comment by jhedberg** [comment]
Added DNM label for now, since I'm not sure this patch is completely correct. Looking at moving the code to an else-branch higher up, but then I might need to still initialise in two places.

**Comment by jhedberg** [comment]
Removed the DNM flag since I think I have now the right fix. I took advantage of the send_start callback which should cover all the scenarios (publishing both with and without retransmission)

**Comment by jhedberg** [comment]
@menglingao1997 could you take a look if this make sense? @trond-snekvik please have a look as well.

File: subsys/bluetooth/mesh/access.c [hunk 1]
```diff
@@ -147,7 +147,25 @@ static void publish_sent(int err, void *user_data)
...
+		BT_ERR("Failed to publish: err %d", err);
+		return;
+	}
+
+	/* pub->count == 0 means we're at the beginning of a new periood.
+	 * Initialize the timestamp for this.
+	 */
+	if (!mod->pub->count) {
+		mod->pub->period_start = k_uptime_get_32();
+	}
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/access.c]: > pub->count == 0 means we're at the beginning of a new periood.

Is this right? Wouldn't it be pub_transmit_count for the `count > 0` scenario, and 0 on the last packet in the publish?

Comment (jhedberg) [reply subsys/bluetooth/mesh/access.c]: @trond-snekvik ugh.. I think you're right. The beginning of the period should be the beginning of the first transmission, not the last one.

Comment (jhedberg) [reply subsys/bluetooth/mesh/access.c]: @trond-snekvik so we should be initialising period_start when count is equal to the configured retransmission count, right?

Comment (jhedberg) [reply subsys/bluetooth/mesh/access.c]: @trond-snekvik updated the PR, could you take another look?

**Comment by jhedberg** [comment]
Just a side comment: using the send_start callback like this gives us also a more accurate period calculation since we base it on the real beginning of transmission rather than the point where we queue the first packet to be sent (there could be other stuff in the queue, the OS could be busy doing something else, etc).

File: subsys/bluetooth/mesh/access.c (hunk 1 above)
Comment (trond-snekvik) [reply subsys/bluetooth/mesh/access.c]: This looks good to me. I like it much better than the initial version too, it never leaves period_start uninitialized 👍

**Review by trond-snekvik — APPROVED** [review]
