### PR TITLE
tests: counter: add current counter value into no_alarm test

### LINKED ISSUE #79574: `counter_start()` has undefined behaviour
`counter_start()` has undefined behaviour, which `test_valid_function_without_alarm` relies on. It assumes:

1. `counter_start()` starts at zero.
2. Calling `counter_start()` will restart a running counter to zero.

The documentation of the API doesn't define this one way or another, but for some drivers (e.g. drivers/counter/counter_rpi_pico_timer.c:counter_rpi_pico_timer_start) this isn't the case, and running `test_valid_function_without_alarm` against that driver will failure. I suspect other drivers will similarly fail.

I think at least the documentation of the API needs to define the expected behaviour, and driver(s) will need to be updated to match.

_Originally posted by @ajf58 in https://github.com/zephyrproject-rtos/zephyr/issues/76527#issuecomment-2400618165_

### PR DESCRIPTION
**Pull request by sylvioalves**
In the test scenario without alarms, it might
  be the case that counter is already running and
  it will not match the expected tick.
  This adds a tick offset into the expected value
  based on current counter reading.

Could fix #79574 considering the scenario where `counter_start()` do not reset the timer.

### CODE REVIEW

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 1]
```diff
@@ -722,6 +723,10 @@ static void test_valid_function_without_alarm(const struct device *dev)
 		ticks_expected = counter_get_top_value(dev) - ticks_expected;
 	}
 
+	/* counter might not start from 0, read current value */
+	counter_get_value(dev, &tick_current);
```
Comment (sylvioalves) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c:727]: Well, the `ticks_tol` won't be updated in this case.

**Review by uLipe — DISMISSED** [review]

**Comment by sylvioalves** [comment]
@CZKikin, would you confirm whether this approach works for you?

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 2]
```diff
@@ -722,6 +723,10 @@ static void test_valid_function_without_alarm(const struct device *dev)
 		ticks_expected = counter_get_top_value(dev) - ticks_expected;
 	}
 
+	/* counter might not start from 0, use current value as offset */
+	counter_get_value(dev, &tick_current);
+	ticks_expected += tick_current;
+
 	err = counter_start(dev);
```
Comment (ajf58) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c:730]: > will fail if the timer resets upon counter_start() call

I think the ordering could be changed to address this 
```suggestion
	err = counter_start(dev);
	/* counter might not start from 0, use current value as offset */
	counter_get_value(dev, &tick_current);
	ticks_expected += tick_current;
```
The new problem I've added is that there will be a number of ticks incremented after starting (so the upper bound for elapsed ticks might need to go up).

I'm happy with either way.

**Comment by ajf58** [comment]
LGTM, tested using a Raspberry Pi Pico 2.

**Review by nordic-krch — DISMISSED** [review]

File: tests/drivers/counter/counter_basic_api/src/test_counter.c (hunk 2 above)
Comment (sylvioalves) [reply tests/drivers/counter/counter_basic_api/src/test_counter.c:730]: This approach makes more sense. It will indeed solve the case where timer is reset. Will update.

**Review by wmrsouza — DISMISSED** [review]

**Review by wmrsouza — APPROVED** [review]

**Comment by ajf58** [comment]
I don't have enough permission to approve, but the latest version looks good to me.

**Review by nordic-krch — APPROVED** [review]

**Review by uLipe — APPROVED** [review]

**Comment by CZKikin** [comment]
> @CZKikin, would you confirm whether this approach works for you? (asking due to #76527).

I think it should be ok. I'll run the test on HW to be sure, but works for us.

**Review by raffarost — APPROVED** [review]
