### PR TITLE
drivers: flash_sam: fix flash_sam_write_page

### LINKED ISSUE #37515: drivers: flash_sam: Random failures when writing large amount of data to flash
**Describe the bug**
When writing large amount of data to flash with flash_sam driver occasionally some random locations are incorrectly programmed (contain random invalid data). When the bug manifests itself one can observe between 1 to 5 failures per 64 kB of programmed data. Every failure is a 4 byte word.

When programming the flash driver does not report any errors, even if as part of the programming sequence it performs Flash Error check, that is the WriteVerify test of the Flash memory is passing. Also comparing data written to flash, immediately after programming sequence has ended, with the input data reveals no issues. The errors become visible only after reboot or cache invalidate operation.

**To Reproduce**
Unfortunately the issue is not easy to reproduce. I was able to observe it when working on firmware update using MCUBoot and #mcu-tools/mcuboot/pull/949 PR (the official MCUboot version does not support Atmel SAM SoCs). The failure happened regularly when MCUboot was swapping images resulting in an error message "Image in the primary slot is not valid!". And occasionally when the application was writing data to the secondary slot. After reboot the MCUboot would log "Image in the secondary slot is not valid!" error message.

In addition the issue manifested itself only when logging with SWO backend was enabled.

**Expected behavior**
Correct data are reliably written to flash or flash driver should report an error.

**Impact**
Showstopper for production firmware.

**Environment**
 - OS: Linux
 - Toolchain: zephyr 0.12.4
 - Zephyr version: 2.6.0

### PR DESCRIPTION
**Pull request by mnkp**
According to Atmel SAM datasheet when writing data to the latch buffer
"32-bit words must be written continuously, in either ascending or
descending order. Writing the latch buffer in a random order is not
permitted." To enforce the requirement we need to call a memory barrier
instruction after copying every word of data to the latch buffer. In
the absensce of __DSB() call the ARM processor is free to change order
of AHB transfers. This has caused the driver to occasionally corrupt
data programmed in the flash.

Fixes #37515

### CODE REVIEW

**Review by aurel32 — COMMENTED** [review]
Good catch, it was not something easy.

The memory barrier looks good to me to ensure the data is written in the correct order. I have more concern with the cache clean operations, as I am not sure it ensures the write ordering. First of all, within a cache line, I am not sure in which order the cache write the words. In addition, if multiple lines are dirty, I am afraid the order in which they are written back is more or less random (well there is probably a logic, but not the one we want).

Looking at the datasheet, I have found this in section 11.1.5:
_When accessed by the Cortex-M7 processor for programming operations, the QSPI and internal Flash address spaces must be defined in the Cortex-M7 memory protection unit (MPU) with the attribute 'Device' or 'Strongly Ordered'. For fetch or read operations, the attribute ‘Normal memory’ must be set to benefit from the internal cache._

The MPU currently configures the flash region in writethrough mode (so I guess the cache clean operations are not necessary), but not in strongly ordered mode. I am not sure it is easy to reprogram the MPU during the flash programming, Therefore I wonder if disabling the D-Cache during the flash programming wouldn't be a better option. I do not think it would make a measurable performance difference, as the flash write operations are already a long operation.

File: drivers/flash/flash_sam.c [hunk 1]
```diff
@@ -142,10 +160,14 @@ static int flash_sam_write_page(const struct device *dev, off_t offset,
...
-		*dst++ = *src++;
+	for (int i = 0; i < len / sizeof(*src); i++) {
+		dst[i] = src[i];
+		/* Assure data are written to the latch buffer consecutively */
+		__DSB();
 	}
-	__DSB();
+
+	/* Assure cache coherency before flash write operation */
+	dcache_clean(dst, len);
```
Comment (stephanosio) [inline drivers/flash/flash_sam.c:170]: Is this really necessary?

From ["How to manage Cortex-M7 Cache Coherence on the Atmel SAM S70 / E70"]():
image

According to the application note above, the flash region is write-through by default (i.e. even when you do not explicitly configure the caching policy through MPU), so DSB should be enough.

**Comment by mnkp** [comment]
> Looking at the datasheet, I have found this in section 11.1.5:
> _When accessed by the Cortex-M7 processor for programming operations, the QSPI and internal Flash address spaces must be defined in the Cortex-M7 memory protection unit (MPU) with the attribute 'Device' or 'Strongly Ordered'. For fetch or read operations, the attribute ‘Normal memory’ must be set to benefit from the internal cache._

Good catch. I overlooked this paragraph. In any case from the functional point of view it should make no difference if we define memory region with the attribute 'Device' or 'Strongly Ordered' or use `__DSB()` instruction. The end effect should be the same.

> The MPU currently configures the flash region in writethrough mode (so I guess the cache clean operations are not necessary)

Yes, I'll remove the cache clean. I'm only not clear if (and how) I need to make sure that the memory is written before we trigger the flash write by  writing to EEFC_FCR register. Merely calling `__ISB()` is probably not good enough. Well, taking into account that this part has been working fine so far it may be best not to touch it.

File: drivers/flash/flash_sam.c (hunk 1 above)
Comment (mnkp) [reply drivers/flash/flash_sam.c]: Taking into account Write-Through, no Write-Allocate most likely not. I'll remove it.

**Review by aurel32 — APPROVED** [review]
LGTM

**Review by stephanosio — APPROVED** [review]

**Review by nandojve — APPROVED** [review]
