### PR TITLE
eth_nxp_enet_qos fixes on MCXN947

### LINKED ISSUE #86435: http_get sample with TLS fails on NXP FRDM-MCXN947
### Discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/86373

Sample fails with this command using Zephyr tag `v4.1.0-rc2`
```
west build -b frdm_mcxn947/mcxn947/cpu0 samples/net/sockets/http_get -- -DEXTRA_CONF_FILE="overlay-tls.conf"
```

console output:
```
---- Opened the serial port /dev/ttyACM1 ----
[00:00:00.605,000] <inf> phy_mii: PHY (0) ID 80008000
*** Booting Zephyr OS build v4.1.0-rc2-86-g384fe7a05d7d ***
[00:00:00.606,000] <wrn> net_sock_tls: No entropy device on the system, TLS communication is insecure!
[00:00:05.108,000] <wrn> net_dhcpv4: DHCP server provided more DNS servers than can be saved
[00:00:05.109,000] <inf> net_dhcpv4: Received: 10.5.1.157
[00:00:05.208,000] <inf> http_get: Preparing HTTP GET request for http://google.com:443/
[00:00:05.209,000] <inf> http_get: getaddrinfo status: 0
[00:00:05.209,000] <inf> http_get: addrinfo @0x300247a8: ai_family=1, ai_socktype=1, ai_protocol=6, sa_family=1, sin_port=1bb
[00:00:05.209,000] <inf> http_get: sock = 5
[00:00:05.209,000] <inf> http_get: Connecting to server...
[00:00:08.217,000] <err> net_sock_tls: TLS handshake error: -0x7200
[00:00:08.218,000] <err> http_get: Error: -1
exit
```
and
```
[00:00:10.429,000] net_sock_tls: TLS handshake error: -0x7300
[00:00:10.431,000] net_sock_tls: TLS handshake error: -0x7200
```
Those errors refer to :
```
/** A message could not be parsed due to a syntactic error. /
#define MBEDTLS_ERR_SSL_DECODE_ERROR -0x7300
/* An invalid SSL record was received. */
#define MBEDTLS_ERR_SSL_INVALID_RECORD -0x7200
```

### LINKED ISSUE #89581: MCXN947 socket network transfer content is wrong
**Describe the bug**

If I send 1KB of data to echo server demo on MCXN947 the board does not answer with the same content

**steps**

- compile eco demo
- west build --pristine -b frdm_mcxn947/mcxn947/cpu0  zephyr/samples/net/sockets/echo/
- telnet 192.168.10.2 4242
- copy paste the content of the file ( ~1000 0 characters)
- capture the network traffic with wireshark 

Below the packet going to the board (wireshare text dump)

[error_1.txt](https://github.com/user-attachments/files/20077033/error_1.txt)
[error_mnxn947.pcapng.txt](https://github.com/user-attachments/files/20077032/error_mnxn947.pcapng.txt)
[zeros.txt](https://github.com/user-attachments/files/20077034/zeros.txt)

 ```

No.     Time           Source                Destination           Protocol Length Info

      1 0.000000000    192.168.10.1          192.168.10.2          TCP      822    46770 → 4242 [ACK] Seq=1 Ack=1 Win=63984 Len=768

 

Frame 1: 822 bytes on wire (6576 bits), 822 bytes captured (6576 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03), Dst: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16)

Internet Protocol Version 4, Src: 192.168.10.1, Dst: 192.168.10.2

Transmission Control Protocol, Src Port: 46770, Dst Port: 4242, Seq: 1, Ack: 1, Len: 768

Data (768 bytes)

 

0000  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0010  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0020  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0030  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0040  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0050  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0060  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0070  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0080  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0090  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00a0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00b0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00c0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00d0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00e0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00f0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0100  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0110  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0120  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0130  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0140  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0150  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0160  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0170  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0180  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0190  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

01a0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

01b0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

01c0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

01d0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

01e0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

01f0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0200  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0210  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0220  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0230  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0240  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0250  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0260  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0270  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0280  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0290  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

02a0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

02b0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

02c0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

02d0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

02e0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

02f0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

 

No.     Time           Source                Destination           Protocol Length Info

      2 0.000146576    192.168.10.1          192.168.10.2          TCP      268    46770 → 4242 [PSH, ACK] Seq=769 Ack=1 Win=63984 Len=214

 

Frame 2: 268 bytes on wire (2144 bits), 268 bytes captured (2144 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03), Dst: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16)

Internet Protocol Version 4, Src: 192.168.10.1, Dst: 192.168.10.2

Transmission Control Protocol, Src Port: 46770, Dst Port: 4242, Seq: 769, Ack: 1, Len: 214

Data (214 bytes)

 

0000  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0010  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0020  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0030  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0040  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0050  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0060  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0070  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0080  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0090  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00a0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00b0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00c0  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

00d0  30 30 30 30 0d 0a                                 0000..

 

No.     Time           Source                Destination           Protocol Length Info

      3 0.012392744    192.168.10.2          192.168.10.1          TCP      182    4242 → 46770 [PSH, ACK] Seq=1 Ack=983 Win=682 Len=128

 

Frame 3: 182 bytes on wire (1456 bits), 182 bytes captured (1456 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16), Dst: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03)

Internet Protocol Version 4, Src: 192.168.10.2, Dst: 192.168.10.1

Transmission Control Protocol, Src Port: 4242, Dst Port: 46770, Seq: 1, Ack: 983, Len: 128

Data (128 bytes)

 

0000  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0010  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0020  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0030  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0040  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0050  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0060  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0070  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

 

No.     Time           Source                Destination           Protocol Length Info

      4 0.012511735    192.168.10.1          192.168.10.2          TCP      54     46770 → 4242 [ACK] Seq=983 Ack=129 Win=63984 Len=0

 

Frame 4: 54 bytes on wire (432 bits), 54 bytes captured (432 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03), Dst: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16)

Internet Protocol Version 4, Src: 192.168.10.1, Dst: 192.168.10.2

Transmission Control Protocol, Src Port: 46770, Dst Port: 4242, Seq: 983, Ack: 129, Len: 0

 

No.     Time           Source                Destination           Protocol Length Info

      5 0.012593469    192.168.10.2          192.168.10.1          TCP      60     4242 → 46770 [ACK] Seq=1 Ack=983 Win=810 Len=0

 

Frame 5: 60 bytes on wire (480 bits), 60 bytes captured (480 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16), Dst: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03)

Internet Protocol Version 4, Src: 192.168.10.2, Dst: 192.168.10.1

Transmission Control Protocol, Src Port: 4242, Dst Port: 46770, Seq: 1, Ack: 983, Len: 0

 

No.     Time           Source                Destination           Protocol Length Info

      6 0.012605980    192.168.10.1          192.168.10.2          TCP      54     [TCP Dup ACK 4#1] 46770 → 4242 [ACK] Seq=983 Ack=129 Win=63984 Len=0

 

Frame 6: 54 bytes on wire (432 bits), 54 bytes captured (432 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03), Dst: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16)

Internet Protocol Version 4, Src: 192.168.10.1, Dst: 192.168.10.2

Transmission Control Protocol, Src Port: 46770, Dst Port: 4242, Seq: 983, Ack: 129, Len: 0

 

No.     Time           Source                Destination           Protocol Length Info

      7 0.024506509    192.168.10.2          192.168.10.1          TCP      182    4242 → 46770 [PSH, ACK] Seq=129 Ack=983 Win=810 Len=128

 

Frame 7: 182 bytes on wire (1456 bits), 182 bytes captured (1456 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16), Dst: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03)

Internet Protocol Version 4, Src: 192.168.10.2, Dst: 192.168.10.1

Transmission Control Protocol, Src Port: 4242, Dst Port: 46770, Seq: 129, Ack: 983, Len: 128

Data (128 bytes)

 

0000  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0010  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0020  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0030  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0040  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0050  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0060  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0070  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

 

No.     Time           Source                Destination           Protocol Length Info

      8 0.024541129    192.168.10.1          192.168.10.2          TCP      54     46770 → 4242 [ACK] Seq=983 Ack=257 Win=63984 Len=0

 

Frame 8: 54 bytes on wire (432 bits), 54 bytes captured (432 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03), Dst: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16)

Internet Protocol Version 4, Src: 192.168.10.1, Dst: 192.168.10.2

Transmission Control Protocol, Src Port: 46770, Dst Port: 4242, Seq: 983, Ack: 257, Len: 0
```
 
**Wrong answered data below**

```
No.     Time           Source                Destination           Protocol Length Info

      9 0.032919052    192.168.10.2          192.168.10.1          TCP      182    4242 → 46770 [PSH, ACK] Seq=257 Ack=983 Win=938 Len=128

 

Frame 9: 182 bytes on wire (1456 bits), 182 bytes captured (1456 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16), Dst: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03)

Internet Protocol Version 4, Src: 192.168.10.2, Dst: 192.168.10.1

Transmission Control Protocol, Src Port: 4242, Dst Port: 46770, Seq: 257, Ack: 983, Len: 128

Data (128 bytes)

 

0000  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0010  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0020  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0030  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0040  30 30 30 30 30 30 30 30 30 30 ae 9a 22 97 c9 16   0000000000.."...

0050  3c 8c f8 ea 52 03 08 00 45 10 00 fe cc 38 40 00   <...R...E....8@.

0060  40 06 d8 5d c0 a8 0a 01 c0 a8 0a 02 b6 b2 10 92   @..]............

0070  85 ac 0d 0f f2 3b 43 b3 50 18 f9 f0 8e c4 00 00   .....;C.P.......

 

No.     Time           Source                Destination           Protocol Length Info

     10 0.032951024    192.168.10.1          192.168.10.2          TCP      54     46770 → 4242 [ACK] Seq=983 Ack=385 Win=63984 Len=0

 

Frame 10: 54 bytes on wire (432 bits), 54 bytes captured (432 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03), Dst: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16)

Internet Protocol Version 4, Src: 192.168.10.1, Dst: 192.168.10.2

Transmission Control Protocol, Src Port: 46770, Dst Port: 4242, Seq: 983, Ack: 385, Len: 0

 

No.     Time           Source                Destination           Protocol Length Info

     11 0.041357837    192.168.10.2          192.168.10.1          TCP      182    4242 → 46770 [PSH, ACK] Seq=385 Ack=983 Win=1066 Len=128

 

Frame 11: 182 bytes on wire (1456 bits), 182 bytes captured (1456 bits) on interface enx3c8cf8ea5203, id 0

Ethernet II, Src: ae:9a:22:97:c9:16 (ae:9a:22:97:c9:16), Dst: TRENDnet_ea:52:03 (3c:8c:f8:ea:52:03)

Internet Protocol Version 4, Src: 192.168.10.2, Dst: 192.168.10.1

Transmission Control Protocol, Src Port: 4242, Dst Port: 46770, Seq: 385, Ack: 983, Len: 128

Data (128 bytes)

 

0000  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0010  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0020  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0030  30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0000000000000000

0040  30 30 30 30 30 30 30 30 30 30 ae 9a 22 97 c9 16   0000000000.."...

0050  3c 8c f8 ea 52 03 08 00 45 10 00 28 cc 3a 40 00   <...R...E..(.:@.

0060  40 06 d9 31 c0 a8 0a 01 c0 a8 0a 02 b6 b2 10 92   @..1............

0070  85 ac 0d e5 f2 3b 44 33 50 10 f9 f0 8f 4a 00 00   .....;D3P....J..

 

``` 

On rw612 

the results is OK

 
```
xyz:~/siemens/os$ telnet 192.168.10.2 4242

Trying 192.168.10.2...

Connected to 192.168.10.2.

Escape character is '^]'.

frdm_rw612

frdm_rw612

00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Expected behavior**
the content answered should be the same

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK
 - V4.1.0

### PR DESCRIPTION
**Pull request by stanislav-poboril**
This PR fixes the following in ENET QoS driver:

- out of order processing of DMA-prepared buffers (previously started from index 0, now from the next position prepared by DMA in the ring of descriptors)
- receiving of frames split into multiple buffers (previously dropped, now net_pkt is composed of multiple buffers if frame is longer than single buffer size now and passed to network stack)
- increases the default configuration for number of buffers, so that at least 1 frame of maximum size can be received (from 4 to 16)

Together with https://github.com/zephyrproject-rtos/zephyr/pull/90181, it:

fixes #89581
fixes #86435

### CODE REVIEW

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 1]
```diff
@@ -226,47 +260,56 @@ static void eth_nxp_enet_qos_rx(struct k_work *work)
...
+			/* Propagate completed packet to network stack */
+			LOG_DBG("Receiving RX packet");
+			if (net_recv_data(data->iface, pkt)) {
+				LOG_ERR("RECV failed");
+				/* Quite a shame. */
+				/* error during processing, we continue with new allocated */
+				net_pkt_unref(pkt);
+				eth_stats_update_errors_rx(data->iface);
+			} else {
+				/* Record our glorious victory */
```
Comment (dleach02) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c]: lol

**Review by dleach02 — COMMENTED** [review]
lgtm... will await test confirmation before approval

**Review by hakehuang — DISMISSED** [review]
build pass

**Comment by groncarolonxp** [comment]
Tested on my side for https://github.com/zephyrproject-rtos/zephyr/issues/89581
Works OK :)

```
tito@nostromo:~$ telnet 192.168.10.2 4242
Trying 192.168.10.2...
Connected to 192.168.10.2.
Escape character is '^]'.
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

```

Thanks so much!
g.

**Review by butok — DISMISSED** [review]

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c [hunk 2]
```diff
@@ -24,6 +24,11 @@ LOG_MODULE_REGISTER(eth_nxp_enet_qos_mac, CONFIG_ETHERNET_LOG_LEVEL);
 #include "../eth.h"
 #include "nxp_enet_qos_priv.h"
 
+/* Verify configuration */
+#if ENET_QOS_RX_BUFFER_SIZE * NUM_RX_BUFDESC < ENET_QOS_MAX_NORMAL_FRAME_LEN
+#error ENET_QOS_RX_BUFFER_SIZE * NUM_RX_BUFDESC is not large enough to receive a full frame
+#endif
+
```
Comment (maass-hamburg) [inline drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c]: should be a `BUILD_ASSERT()` instead

**Review by maass-hamburg — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

File: drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c (hunk 2 above)
Comment (decsny) [reply drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c]: Why?

Comment (dleach02) [reply drivers/ethernet/eth_nxp_enet_qos/eth_nxp_enet_qos_mac.c]: there are almost 1600 usages of BUILD_ASSERT in the codebase which kind of makes it a standard. It also simplifies these three lines to one.
