### PR TITLE
drivers: nxp: flexspi: fix hyper flash hang issue

### LINKED ISSUE #90676: nxp: mimxrt1050-evk: stuck in FLEXSPI_TransferBlocking()
**Describe the bug**

There is a stuck for mimxrt1050-evk (hyperflash) in infinite loop in `flash_flexspi_hyperflash_write()=>flash_flexspi_hyperflash_wait_bus_busy()=>memc_flexspi_transfer()=>FLEXSPI_TransferBlocking()` line 953:

```
/* Wait until the IP command execution finishes */
    while (0UL == (base->INTR & FLEXSPI_INTR_IPCMDDONE_MASK))
    {
    }
```

**To Reproduce**
1. `west build -p always -b mimxrt1050_evk --sysbuild tests/boot/test_mcuboot`  
2. `west flash`  if the flash was erased before or `west flash --erase` (be sure that flashing configuration PR was 
applied https://github.com/zephyrproject-rtos/zephyr/pull/90658)
3. See infinite loop in `memc_flexspi_transfer()=>FLEXSPI_TransferBlocking()`

**Expected behavior**
No stuck in the the flash write function.

**Environment (please complete the following information):**

 - Commit SHA: 52f089af239bc9c5e1054de91a84429c0b60803b

### PR DESCRIPTION
**Pull request by Raymond0225**
CS hold time parameter is not correct which may cause bus fault randomly.
System hang during status register reading after flash progromming which is caused by parameter accessing in XIP mode.
Add dummy delay for READ command according the flash datasheet which is required for SDR mode.
Use FlexSPI internal divider for clock updating instead of register in CCM to avoid potential risk caused by flash access during clock updating procedure.

fix: https://github.com/zephyrproject-rtos/zephyr/issues/90676
replace this PR: https://github.com/zephyrproject-rtos/zephyr/pull/91518

### CODE REVIEW

**Comment by butok** [comment]
Hi @hakehuang, could you confirm/test it on mimxrt1050_evk.

**Comment by dleach02** [comment]
@Raymond0225 this part is also on the RT1060 and mimxrt1062_fmurt6 with the same value. Should they be changed as well?

**Comment by hakehuang** [comment]
> Hi @hakehuang, could you confirm/test it on mimxrt1050_evk.

Test pass
```
025-06-25 03:50:43,161 - twister - DEBUG - DEVICE: *** Booting MCUboot v2.1.0-rc1-310-g990b1fcb367e ***
2025-06-25 03:50:43,166 - twister - DEBUG - DEVICE: *** Using Zephyr OS build v4.1.0-6090-ga69d78eb265e ***
2025-06-25 03:50:43,168 - twister - DEBUG - DEVICE: I: Starting bootloader
2025-06-25 03:50:43,168 - twister - DEBUG - HARNESS:Console:EXPECTED(1/5):'I: Starting bootloader'
2025-06-25 03:50:43,175 - twister - DEBUG - DEVICE: I: Primary image: magic=good, swap_type=0x3, copy_done=0x1, image_ok=0x1
2025-06-25 03:50:43,181 - twister - DEBUG - DEVICE: I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
2025-06-25 03:50:43,183 - twister - DEBUG - DEVICE: I: Boot source: none
2025-06-25 03:50:43,187 - twister - DEBUG - DEVICE: W: Failed reading image headers; Image=0
2025-06-25 03:50:43,191 - twister - DEBUG - DEVICE: E: Image in the primary slot is not valid!
2025-06-25 03:50:43,194 - twister - DEBUG - DEVICE: E: Unable to find bootable image
2025-06-25 03:50:49,094 - twister - DEBUG - DEVICE: *** Booting MCUboot v2.1.0-rc1-310-g990b1fcb367e ***
2025-06-25 03:50:49,099 - twister - DEBUG - DEVICE: *** Using Zephyr OS build v4.1.0-6090-ga69d78eb265e ***
2025-06-25 03:50:49,101 - twister - DEBUG - DEVICE: I: Starting bootloader
2025-06-25 03:50:49,108 - twister - DEBUG - DEVICE: I: Primary image: magic=good, swap_type=0x3, copy_done=0x1, image_ok=0x1
2025-06-25 03:50:49,114 - twister - DEBUG - DEVICE: I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
2025-06-25 03:50:49,116 - twister - DEBUG - DEVICE: I: Boot source: none
2025-06-25 03:50:49,120 - twister - DEBUG - DEVICE: W: Failed reading image headers; Image=0
2025-06-25 03:50:49,123 - twister - DEBUG - DEVICE: E: Image in the primary slot is not valid!
2025-06-25 03:50:49,126 - twister - DEBUG - DEVICE: E: Unable to find bootable image
2025-06-25 03:50:54,508 - twister - DEBUG - DEVICE: *** Booting MCUboot v2.1.0-rc1-310-g990b1fcb367e ***
2025-06-25 03:50:54,513 - twister - DEBUG - DEVICE: *** Using Zephyr OS build v4.1.0-6090-ga69d78eb265e ***
2025-06-25 03:50:54,515 - twister - DEBUG - DEVICE: I: Starting bootloader
2025-06-25 03:50:54,522 - twister - DEBUG - DEVICE: I: Primary image: magic=good, swap_type=0x3, copy_done=0x1, image_ok=0x1
2025-06-25 03:50:54,528 - twister - DEBUG - DEVICE: I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
2025-06-25 03:50:54,530 - twister - DEBUG - DEVICE: I: Boot source: none
2025-06-25 03:50:54,533 - twister - DEBUG - DEVICE: I: Image index: 0, Swap type: none
2025-06-25 03:50:54,548 - twister - DEBUG - DEVICE: I: Bootloader chainload address offset: 0x40000
2025-06-25 03:50:54,550 - twister - DEBUG - DEVICE: I: Image version: v0.0.0
2025-06-25 03:50:54,553 - twister - DEBUG - DEVICE: I: Jumping to the first image slot
2025-06-25 03:50:54,558 - twister - DEBUG - DEVICE: *** Booting Zephyr OS build v4.1.0-6090-ga69d78eb265e ***
2025-06-25 03:50:54,563 - twister - DEBUG - DEVICE: Launching primary slot application on mimxrt1050_evk
2025-06-25 03:50:54,563 - twister - DEBUG - HARNESS:Console:EXPECTED(2/5):'Launching primary slot application on (.*)'
2025-06-25 03:50:54,586 - twister - DEBUG - DEVICE: Secondary application ready for swap, rebooting*** Booting MCUboot v2.1.0-rc1-310-g990b1fcb367e ***
2025-06-25 03:50:54,586 - twister - DEBUG - HARNESS:Console:EXPECTED(3/5):'Secondary application ready for swap, rebooting'
2025-06-25 03:50:54,591 - twister - DEBUG - DEVICE: *** Using Zephyr OS build v4.1.0-6090-ga69d78eb265e ***
2025-06-25 03:50:54,593 - twister - DEBUG - DEVICE: I: Starting bootloader
2025-06-25 03:50:54,599 - twister - DEBUG - DEVICE: I: Primary image: magic=good, swap_type=0x3, copy_done=0x1, image_ok=0x1
2025-06-25 03:50:54,606 - twister - DEBUG - DEVICE: I: Secondary image: magic=good, swap_type=0x3, copy_done=0x3, image_ok=0x1
2025-06-25 03:50:54,608 - twister - DEBUG - DEVICE: I: Boot source: none
2025-06-25 03:50:54,611 - twister - DEBUG - DEVICE: I: Image index: 0, Swap type: perm
2025-06-25 03:50:54,625 - twister - DEBUG - DEVICE: I: Starting swap using move algorithm.
2025-06-25 03:50:59,580 - twister - DEBUG - DEVICE: I: Bootloader chainload address offset: 0x40000
2025-06-25 03:50:59,585 - twister - DEBUG - DEVICE: I: Image version: v0.0.0
2025-06-25 03:50:59,586 - twister - DEBUG - DEVICE: I: Jumping to the first image slot
2025-06-25 03:50:59,591 - twister - DEBUG - DEVICE: *** Booting Zephyr OS build v4.1.0-6090-ga69d78eb265e ***
2025-06-25 03:50:59,595 - twister - DEBUG - DEVICE: Swapped application booted on mimxrt1050_evk
2025-06-25 03:50:59,595 - twister - DEBUG - HARNESS:Console:EXPECTED(5/5):'Swapped application booted on (.*)'
2025-06-25 03:50:59,635 - twister - DEBUG - Release DUT:mimxrt1050_evk/mimxrt1052/hyperflash, Id:0227000047784e4500119003d9170010e561000097969900, counter:1, failures:0
2025-06-25 03:50:59,635 - twister - DEBUG - run status: mimxrt1050_evk/mimxrt1052/hyperflash/zephyr/tests/boot/test_mcuboot/bootloader.mcuboot passed
```

**Comment by hakehuang** [comment]
> @Raymond0225 this part is also on the RT1060 and mimxrt1062_fmurt6 with the same value. Should they be changed as well?

according to our CI testing below platform fails

image

File: drivers/flash/flash_mcux_flexspi_hyperflash.c [hunk 1]
```diff
@@ -256,9 +269,9 @@ struct flash_flexspi_hyperflash_data {
 	struct flash_parameters flash_parameters;
 };
 
-static int flash_flexspi_hyperflash_wait_bus_busy(const struct device *dev)
+/* Make sure all parameters accessed by this function are in RAM when XIP is enabled. */
+static int flash_flexspi_hyperflash_wait_bus_busy(const struct flash_flexspi_hyperflash_data *data)
```
Comment (hakehuang) [inline drivers/flash/flash_mcux_flexspi_hyperflash.c:273]: dev->data is in ram, and I see you call flash_flexspi_hyperflash_wait_bus_busy with data = dev->data

**Review by butok — DISMISSED** [review]

**Comment by Raymond0225** [comment]
> @Raymond0225 this part is also on the RT1060 and mimxrt1062_fmurt6 with the same value. Should they be changed as well?

Good point, let me change them as well.

**Review by butok — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
