### PR TITLE
include: zephyr: net: Add NULL checks for phy API calls

### LINKED ISSUE #84146: Missing nullptr check for API call in "net/phy.h"
**Describe the bug**

The function `static inline int phy_link_callback_set(const struct device *dev, phy_callback_t callback,void *user_data)` claims to return the error code "-ENOTSUP" if the API call is not supported.

But the function misses a correspondung nullptr check.

**Current implementation:**
```
static inline int phy_link_callback_set(const struct device *dev, phy_callback_t callback,
					void *user_data)
{
	const struct ethphy_driver_api *api = (const struct ethphy_driver_api *)dev->api;

	return api->link_cb_set(dev, callback, user_data);
}
```

**Posseblie fix:**
```
static inline int phy_link_callback_set(const struct device *dev, phy_callback_t callback,
					void *user_data)
{
	const struct ethphy_driver_api *api = (const struct ethphy_driver_api *)dev->api;
        if (api->link_cb_set != NULL)
	    return api->link_cb_set(dev, callback, user_data);
        else
            return -ENOTSUP;
}
```

**To Reproduce**
1. Create a little sample application using a STM32 nucleo H7
2. Try to set a callback using `phy_link_callback_set`
3. Run your sample application

**Expected behavior**
The function returns -ENOTSUP indicating that the ehternet driver does not support that API call.

**Impact**
The sample application crashes with a memory/access violation.

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Windows with VsCode and WSL/docker
 - Toolchain Zephyr SDK

**Additional context**

### PR DESCRIPTION
**Pull request by sayoojkkarun**
Add missing NULL checks to the APIs in phy.h
Signed-off-by: Sayooj K Karun <sayooj@aerlync.com>

### CODE REVIEW

File: include/zephyr/net/phy.h [hunk 1]
```diff
@@ -209,6 +210,10 @@ static inline int phy_configure_link(const struct device *dev, enum phy_link_spe
 {
 	const struct ethphy_driver_api *api = (const struct ethphy_driver_api *)dev->api;
 
+	if (!api->cfg_link) {
```
Comment (maass-hamburg) [inline include/zephyr/net/phy.h:213]:
```suggestion
	if (api->cfg_link == NULL) {
```
explicit check for NULL, like in the other apis.

**Review by maass-hamburg — CHANGES_REQUESTED** [review]

**Review by pdgendt — DISMISSED** [review]

**Review by decsny — DISMISSED** [review]

**Review by maass-hamburg — DISMISSED** [review]

**Comment by sayooj-aerlync** [comment]
@maass-hamburg @pdgendt @decsny Added errno.h header because `west twister -p native_sim/native -T ./tests/drivers/build_all/ethernet/ -s net.ethernet.build.spi` was failing.

**Review by pdgendt — APPROVED** [review]

**Review by maass-hamburg — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by decsny — APPROVED** [review]
