### PR TITLE
k_thread_abort/join() rewrite & attendant fixes

### LINKED ISSUE #32467: x86_64: page fault with access violation error complaining supervisor thread not allowed to rwx
**To Reproduce**
1. west build -b up_squared -p auto tests/kernel/device
2. west flash ~/up_squared.sh
3. see error

**Logs and console output**
 Booting Zephyr OS build zephyr-v2.5.0-239-ge287fd7ab2fb  
Running test suite device

START - test_dummy_device_pm
SKIP - test_dummy_device_pm

START - test_build_suspend_device_list
SKIP - test_build_suspend_device_list

START - test_dummy_device
E: Page fault at address 0x158 (error code 0x0)
PASS - test_dummy_device
E: Linear address not present in page tables

**E: Access violation: supervisor thread not allowed to read**
START - test_enable_and_disable_automatic_idle_pm
E: PTE: not present
E: Page fault at address (nil) (error code 0x2)
E: Linear address not present in page tables
E: Access violation: supervisor thread not allowed to write
E: PTE: not present
E: RAX: 0x0000000000000000 RBX: 0x000000000011a280 RCX: 0x0000000000000001 RDX: 0x00000000000000ff
E: RSI: 0x000000000011ada0 RDI: 0x000000000011a280 RBP: 0x00000000017c4ea0 RSP: 0x00000000017c4e90
E:  R8: 0x0000000000000001  R9: 0x8000000000000006 R10: 0x0000000000105bb9 R11: 0x0000000000000000
E: R12: 0x000000000011a280 R13: 0x00000000017bd000 R14: 0x0000000000002000 R15: 0x0000000000105bb9
E: RSP: 0x00000000017c4e90 RFLAGS: 0x0000000000010086 CS: 0x0018 CR3: 0x0000000001dca000
E: RIP: 0x0000000000109676
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 1
E: Current thread: 0x11ada0 (main)
E: Halting system

**Environment (please complete the following information):**

 - Toolchain: zephyr-sdk-0.12.2
 - Commit ID: e287fd7ab2f

### PR DESCRIPTION
**Pull request by andyross**
Comparatively big series that reworks abort and join to fix some fundamental races on SMP (see #32344).   The new version is (heh) hopefully correct, but should absolutely be easier to review and reason about.  It definitely doesn't share the same misfeatures we saw earlier.

The early patches in the series are fixes to related bugs I stumbled on while working this mixed with refactoring needed for later changes.  Note that the abort rework itself is split into two patches for review, even though that technically breaks bisectability (there's a big warning to this effect).

### CODE REVIEW

**Comment by andyross** [comment]
And this isn't **quite** ready yet.  While it fixes the spurious abort problems, the modified timing has tripped over a different issue with timeslicing.  I hope to have a fix for that added to this series within a day; I see the root cause at least.

File: kernel/sched.c [hunk 1]
```diff
@@ -1426,6 +1436,124 @@ int k_thread_cpu_mask_disable(k_tid_t thread, int cpu)
...
+	}
+	k_spin_unlock(&sched_spinlock, key);
+}
+
+#if !defined(CONFIG_ARCH_HAS_THREAD_ABORT)
+void z_impl_k_thread_abort(struct k_thread *thread)
+{
+	z_thread_abort(thread);
+}
+#else
```
Comment (andyross) [inline kernel/sched.c:1531]: Just noticed this empty #else, which got leftover when I removed the stuff here in favor of modifying the arch layers.  Will fix.

**Comment by andyross** [comment]
OK, think I have it now (see the final timeslice fix which is the third from the last in the series; I wanted to keep the abort stuff last).  Starting my stress test locally to see if anything got missed or broken at the last minute, but I'm hopeful.

**Comment by andyross** [comment]
So, overnight stress on x86_64 showed that the msgq_api test is failing maybe 13% of the time in a loaded twister run.  This is a test that does a lot of racing aborts (it's one of the big offenders in the intermediate states in this PR), so it's likely it's showing some kind of remaining bug here.  I'll keep looking.  Other failures are happening randomly at the rate of one per ~20 test passes, and seem to be the kind of spurious thing we are used to on qemu due to timing interactions.  The msgq test seems to be the only one with a measurable failure rate on its own.

FWIW: that failure rate is still much, much better than what we have in tree.  So it's probably worth merging this anyway (and I guess opening a bug if so) pending whatever fix shows up for the msgq_api failures.

File: kernel/thread.c [hunk 2]
```diff
@@ -800,7 +800,7 @@ void z_init_thread_base(struct _thread_base *thread_base, int priority,
 		       uint32_t initial_state, unsigned int options)
 {
 	/* k_q_node is initialized upon first insertion in a list */
```
Comment (nashif) [inline kernel/thread.c:792]: unrelated to the change, what is `k_q_node`? seems to be some old craft

Comment (andyross) [reply kernel/thread.c:792]: It's called "qnode_dlist" or "qnode_rb" now (depending on the scheduler queue backend selected).  This deserves a rework.  Really the whole "thread_base" struct could go away and be folded into thread, the only user of it is the weird dummy thread trick in pipe and mailbox, and they could have their own separate API what they want.

File: tests/kernel/mem_protect/syscalls/prj.conf [hunk 3]
```diff
@@ -1,5 +1,5 @@
 CONFIG_ZTEST=y
 CONFIG_TEST_USERSPACE=y
 CONFIG_TIMESLICING=y
-CONFIG_TIMESLICE_SIZE=10
+CONFIG_TIMESLICE_SIZE=20
```
Comment (jharris-intel) [inline tests/kernel/mem_protect/syscalls/prj.conf:4]: Why the change? Working around lingering issues?

File: tests/kernel/workq/critical/src/main.c [hunk 4]
```diff
@@ -166,7 +166,7 @@ void regression_thread(void *arg1, void *arg2, void *arg3)
 		      "Unexpected value for <critical_var>");
 
 	TC_PRINT("Enable timeslicing at %u\n", k_uptime_get_32());
-	k_sched_time_slice_set(10, 10);
+	k_sched_time_slice_set(20, 10);
```
Comment (jharris-intel) [inline tests/kernel/workq/critical/src/main.c:169]: Minor: shouldn't this be pulled from .conf?

File: arch/posix/core/posix_core.c [hunk 5]
```diff
@@ -507,16 +507,11 @@ void z_impl_k_thread_abort(k_tid_t thread)
...
 
-		if (arch_is_in_isr()) {
-			z_thread_single_abort(thread);
-			return;
-		}
-
-		z_self_abort();
-		CODE_UNREACHABLE; /* LCOV_EXCL_LINE */
+		z_thread_abort(_current);
+		return;
```
[the remark this answers is not in the document]
Comment (andyross) [reply arch/posix/core/posix_core.c:511]: Actually yes, in interrupt context.  This is the native_posix implementation of k_thread_abort() and it will be called in all the same contexts the "official" one is.  But you're right, the ISR test is already covered above so it's silly to have the return here.

File: tests/kernel/mem_protect/syscalls/prj.conf (hunk 3 above)
Comment (andyross) [reply tests/kernel/mem_protect/syscalls/prj.conf:4]: This is the timeslicing fix.  There were tests that were asking for timeslices so small they couldn't be reliably scheduled by the timer driver, and a combination of recent changes to the timeslice layer (which for subtle reasons dropped integration some code that would elide the z_clock_set_timeout() call on imminent expirations) and more deterministic thread abort behavior meant that we were hitting the hang condition.

But really it's a bug in the tests.  Minimum timeslice size when CONFIG_TICKLESS_KERNEL is two ticks.  One won't work right (and now the kernel protects against it).

File: tests/kernel/workq/critical/src/main.c (hunk 4 above)
Comment (andyross) [reply tests/kernel/workq/critical/src/main.c:169]: Yes, but it wasn't before so it isn't now. :)  My personal feeling about having ugly code in the regression suite is that it's far more important that it stay there and run than experience churn that might hide bugs we'd otherwise detect.  Zephyr is expected to run bad code correctly too.

(Not like I'd reject a patch that cleaned up hardcoded timeslices or anything, just that it isn't my personal inclination to try to "clean up" tests at the same moment I'm trying to make them pass.)

**Comment by andyross** [comment]
OK new version up.  This adds two new fixes to address what I was seeing with msgq_api (and again it turns out that neither were related to abort per se and were just pre-existing bugs tickled by different timing):

The HPET driver had a workaround in its ISR for a bug in qemu where the clock can go backwards, but there was another edge case where the same glitch could (very rarely, but I did see it happen!) cause a bad timeout to be set due to a rollover condition.

The main bug was a simple thinko in the timeout code about which value to set as the timeout.  This turns out (due to the structure of how things work) to have been hidden in uniprocessor setups, but on SMP it's a real race.  This was the source of almost all the instability (and it took FOREVER to find, ugh...)

And... this might be it folks.  My build box is through 8 iterated twister runs on x86_64 with no failures reported at all.  I'll leave it running as long as possible to see if I can catch something failing.

**Review by dcpleung — APPROVED** [review]

File: include/kernel.h [hunk 6]
```diff
@@ -537,6 +539,17 @@ __syscall k_tid_t k_current_get(void);
  * released. It is the responsibility of the caller of this routine to ensure
  * all necessary cleanup is performed.
  *
+ * After k_thread_abort() returns, the thread is guaranteed not to be
+ * running or to become runnable anywhere on the system.  Normally
+ * this is done via blocking the caller (in the same manner as
+ * k_thread_join()), but in interrupt context on SMP systems the
+ * implementation is required to spin for threads that are running on
+ * other CPUs.  Note that as specified, this means that on SMP
```
Comment (jharris-intel) [inline include/kernel.h:547]: As a note for future development here, there is a way to deal with this, it's just not great.

(Not something to do in this PR though!)

(Namely, if you're in interrupt context and you are spinning waiting for a thread to be aborted, check to see if the thread you interrupted interrupted thread should be aborted, and if so handle it yourself. There are a bunch of ordering considerations, but that's the general gist of it.)

File: kernel/sched.c [hunk 7]
```diff
@@ -457,6 +447,25 @@ static void update_cache(int preempt_ok)
 #endif
 }
 
+static bool thread_active_elsewhere(struct k_thread *thread)
+{
+	/* True if the thread is currently running on another CPU.
```
Comment (jharris-intel) [inline kernel/sched.c:452]: I'm surprised threads don't have a "I'm running" flag.

(Then this could just be `thread_running(thread) && thread != _current`)

**Review by jharris-intel — APPROVED** [review]
The parts that I followed make sense.

(I honestly didn't take the time to follow all of the logic here, so take this with a grain of salt.)

**Review by jenmwms — APPROVED** [review]

File: include/kernel.h (hunk 6 above)
Comment (andyross) [reply include/kernel.h:547]: Yeah, in the general case that becomes a full graph search for cycles .   Real devices (not ones running Zephyr, but then you never know...) exist with hundreds of CPUs.  You'd need to be willing to search that graph while holding a global scheduler lock literally in the middle of a context switch.  In an "RTOS". :)

FWIW: I went digging to see what Linux does here, and the answer is actually it doesn't.  There's no accessible API I can find to kill a process from an interrupt at all.  You kill processes by sending them signals so the abort is always done from their own kernel stack.  So even having documented the deadlock, I think we're ahead of the game here.

File: kernel/sched.c (hunk 7 above)
Comment (andyross) [reply kernel/sched.c:452]: That would be the obvious way to implement this, yeah.  But it requires allocating another flag bit, and we're out of space at the moment.  I'm sensitive to impacting the size of the thread struct for non-SMP use cases.  Really this isn't a hard problem to solve, but on existing devices a quick array loop over 2-4 CPUs is fine for now.

File: drivers/timer/hpet.c [hunk 8]
```diff
@@ -138,10 +148,14 @@ int z_clock_driver_init(const struct device *device)
...
-	last_count = MAIN_COUNTER_REG;
+	last_count = counter();
+#ifdef GLITCHY_EMU
+	last_counter = last_count;
+	max_ticks -= 20;
+#endif
 
 	TIMER0_CONF_REG |= TCONF_INT_ENABLE;
-	TIMER0_COMPARATOR_REG = MAIN_COUNTER_REG + cyc_per_tick;
+	TIMER0_COMPARATOR_REG = counter() + cyc_per_tick;
```
[the remark this answers is not in the document]
Comment (andyross) [reply drivers/timer/hpet.c:158]: It's an atomic register and this is the initialization path against which it won't be racing.  So yeah, this is safe.

File: drivers/timer/hpet.c [hunk 9]
```diff
@@ -41,18 +41,41 @@ DEVICE_MMIO_TOPLEVEL_STATIC(hpet_regs, DT_DRV_INST(0));
 
 #define MIN_DELAY 1000
 
+/* The clock on Qemu in SMP has been observed going backwards.  This
```
[the remark this answers is not in the document]
Comment (andyross) [reply drivers/timer/hpet.c:44]: Without, we don't have it wired right now.  And yes, it's likely that this is specific to the realtime clock integration.  I never investigated, and actually had forgotten all about this workaround until I caught it misbehaving yesterday.

File: include/kernel.h (hunk 6 above)
Comment (jharris-intel) [reply include/kernel.h:547]: >Yeah, in the general case that becomes a full graph search for cycles .

Hmm. Perhaps we're thinking of something different here (or you've identified something I'm missing, which is entirely likely).

The check for "if the thread you interrupted should be aborted" is constant-time, assuming you check the thread's flag. No searching the graph with BigLock.

At a conceptual level:

1. Every time you go to abort a thread, you ensure that your target thread is marked as aborting before you drop into `join` (...which we already do).
2. If you're spinning in a join in interrupt context, and the interrupted thread is marked as aborting, handle that abort.

(The key here is that there _is_ an implicit graph search, but it's incremental and amortized across all of the `k_thread_abort` calls. See, the only way to _create_ the graph of aborting threads is with a call to `k_thread_abort` for each edge... and each node has flags. If you squint a lot this turns into graph labelling...)

(There are still problems here with e.g. aborting a thread that's holding a mutex I am well aware. But this at least solves the cycle-of-aborting-threads issue.)

Comment (andyross) [reply include/kernel.h:547]: Ah, got it.  I was talking about being able to detect the cycle of parallel aborts and return an error to a user who tries.

But you're right, being able to detect a newly aborted _current from within that spin loop would have the effect of breaking the cycle.  That's clever, I'll see what needs to be done, but yeah, maybe in a separate PR.

File: kernel/sched.c (hunk 7 above)
Comment (jharris-intel) [reply kernel/sched.c:452]: Hmm.

Looking at it, we could probably swap out a few of the boolean flags with a state enum instead - most of those flags are one-hot anyway.

But yes, this is fine for now I think.

****

This is _decidedly_ off-topic for this particular PR, but:

> Really this isn't a hard problem to solve, but on existing devices a quick array loop over 2-4 CPUs is fine for now.

My initial testing of Zephyr is showing the opposite, unfortunately. We're fairly bottlenecked on sched_lock in general. (E.g. 2 independent pairs of threads passing 2 semaphores back and forth on a 4-core system end up having _fewer_ total swaps per second than one pair of threads passing one semaphore back and forth.)

(I'm holding off on making a ticket for this until AArch64 SMP support is actually in trunk :-) . Correctness is a rather important prerequisite to performance.)

File: drivers/timer/hpet.c (hunk 8 above)
[the remark this answers is not in the document]
Comment (jharris-intel) [reply drivers/timer/hpet.c:158]: Thanks for the doublecheck!

> It's an atomic register

It's more the (non-atomic) `GLITCHY_EMU` workaround I was wondering about.

**Comment by andyross** [comment]
Came back to look at the stress log.  74 runs of "twister -p qemu_x86_64" with no failures.  I think this one is cooked for now.  Seeing rarer failures is going to need a more extensive rig.

File: kernel/sched.c (hunk 7 above)
Comment (andyross) [reply kernel/sched.c:452]: I'd love to look at that report when you're ready.  There's surely stuff we can do to relax contention.  But do at least recognize that k_sem is a VERY thin layer, code that does nothing but pass semaphore tokens back and forth is in some sense doing nothing **but** scheduling, so absent a change in the fundamentals you'd expect the Zephyr design to produce a constant amount of scheduling regardless of CPU count.

File: drivers/timer/hpet.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (jharris-intel) [reply drivers/timer/hpet.c:44]: > Without

That'd explain it then I think... You might try setting `-rtc clock=vm`.

I think you might be running into ntp updating the host time out from under you.

File: kernel/sched.c (hunk 7 above)
Comment (jharris-intel) [reply kernel/sched.c:452]: Yep, it's a rather fundamental design decision that bottlenecks us here unfortunately :-(

In general, the "sea of spinlocks" approach - although better than BigLock - still results in individual features being sequentially-bottlenecked. And when one of those features is "scheduling"...

What it means in practice is that it's not much better than BigLock if you're doing anything that can schedule (and practically all interaction with Zephyr can schedule...)

You can do a whole lot better with "sea of spinlocks + atomics for base scheduling"... at the expense of a whole lot of complexity and nondeterminism. Most RTOSes I've seen don't even attempt this approach - which makes sense in a number of ways - but also means that they tend to be unsuitable for some usecases. The difference between 200 cycles to context-switch when you have a budget of 2000 cycles / core / op and 2000 cycles to context-switch when you have a budget of 2000 cycles / core / op is the difference between "you can carefully use the RTOS" and "you can't use the RTOS", in a lot of ways.

I may end up having to reject Zephyr here, which is rather unfortunate.

I can make a ticket for context-switch performance now to start the discussion, if you'd like. Just know that it's based on a hacked-together branch with MrVan's AArch64 SMP changes, your abort rewrite, some "trivial" local optimizations (notably: changing spinlock release to a sequentially-consistent store instead of a CAS non-trivially improves the performance of the spinlock in contended situations), and some proprietary driver code (nothing that should directly affect this, however)...

**Review by nashif — APPROVED** [review]

File: kernel/include/ksched.h [hunk 10]
```diff
@@ -67,6 +67,7 @@ void z_ready_thread(struct k_thread *thread);
 void z_thread_single_abort(struct k_thread *thread);
 FUNC_NORETURN void z_self_abort(void);
 void z_requeue_current(struct k_thread *curr);
+struct k_thread *z_swap_next_thread(void);
```
Comment (lyakh) [inline kernel/include/ksched.h:68]: @andyross this commit broke the SMP sync example on UP2 - identified with bisect... So, currently it's broken on "master" But one of your patches from #32356 seems to fix this breakage again...

File: kernel/sched.c (hunk 7 above)
Comment (jharris-intel) [reply kernel/sched.c:452]: @andyross - I created #32686 with one of the contributing factors. The current spinlock has some rather terrible behavior under heavy contention (such as all cores hammering at sched_lock).

Comment (jharris-intel) [reply kernel/sched.c:452]: @andyross - I created #32708 with another one of the contributing factors. The current implementation of `k_current_get` is an unfortunate combination of "slow" and "called a lot".
