### PR TITLE
net: l2: ppp: Async-Control-Character-Map updated too early

### LINKED ISSUE #105291: net: l2: ppp: PPP negotiation fails against Linux PPPD without asyncmap 0xffffffff
### Describe the bug

When Zephyr's L2 PPP driver is used against PPPD implementation from Linux, it fails, unless option `asyncmap 0xffffffff` is specified.

When peer sends the Async-Control-Character-Map option on LCP
phase, Zephyr correctly responsed with Configure-Ack.
But the LCP negotiation phase have not been finnished yet,
so the remote end may not expect us to immediately
update the value.

This is seen when trying to use Zephyr's PPP stack against
PPPD from Linux, where default asyncmap option is zero.

### Regression

- [x] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell
Connect: ppp0 <--> /dev/ttyACM0
sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0x42717a60> <pcomp> <accomp>]
rcvd [LCP ConfReq id=0x1 <mru 1464> <asyncmap 0xffffffff>]
sent [LCP ConfAck id=0x1 <mru 1464> <asyncmap 0xffffffff>]
sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0x42717a60> <pcomp> <accomp>]
rcvd [LCP ConfRej id=0x1 <magic 0x42717a60> <pcomp> <accomp>]
sent [LCP ConfReq id=0x2 <asyncmap 0x0>]
sent [LCP ConfReq id=0x2 <asyncmap 0x0>]
sent [LCP ConfReq id=0x2 <asyncmap 0x0>]
sent [LCP ConfReq id=0x2 <asyncmap 0x0>]
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Linux
- 

### Additional Context

This looks like a regression when these two PRs are combined:
* https://github.com/zephyrproject-rtos/zephyr/pull/97963
* https://github.com/zephyrproject-rtos/zephyr/pull/89580

### PR DESCRIPTION
**Pull request by SeppoTakalo**
When peer sends the Async-Control-Character-Map option on LCP phase, Zephyr correctly responsed with Configure-Ack. But the LCP negotiation phase have not been finnished yet, so the remote end may not expect us to immediately update the value.

This is seen when trying to use Zephyr's PPP stack against PPPD from Linux, where default asyncmap option is zero.

```
Serial connection established.
using channel 104
Using interface ppp0
Connect: ppp0 <--> /dev/ttyACM0
sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0x42717a60> <pcomp> <accomp>]
rcvd [LCP ConfReq id=0x1 <mru 1464> <asyncmap 0xffffffff>]
sent [LCP ConfAck id=0x1 <mru 1464> <asyncmap 0xffffffff>]
sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0x42717a60> <pcomp> <accomp>]
rcvd [LCP ConfRej id=0x1 <magic 0x42717a60> <pcomp> <accomp>]
sent [LCP ConfReq id=0x2 <asyncmap 0x0>]
sent [LCP ConfReq id=0x2 <asyncmap 0x0>]
sent [LCP ConfReq id=0x2 <asyncmap 0x0>]
sent [LCP ConfReq id=0x2 <asyncmap 0x0>]
^CTerminating on signal 2
sent [LCP TermReq id=0x3 "User request"]
sent [LCP TermReq id=0x4 "User request"]
Connection terminated.
```

However, if we delay the update of the asyncmap to the network phase, it works just fine.

Fixes #105291

### CODE REVIEW

File: subsys/net/l2/ppp/ppp_l2.c [hunk 1]
```diff
@@ -354,6 +354,9 @@ uint32_t ppp_peer_async_control_character_map(struct net_if *iface)
 	__ASSERT(net_if_l2(iface) == &NET_L2_GET_NAME(PPP), "Not PPP L2");
 #endif /* !CONFIG_ZTEST */
 	ctx = net_if_l2_data(iface);
+	if (ctx->phase < PPP_NETWORK) {
+		return 0xffffffff;
+	}
```
Comment (rerickson1) [inline subsys/net/l2/ppp/ppp_l2.c:359]: Should there be a define for this value?
A comment explaining why here would be great.

Comment (SeppoTakalo) [reply subsys/net/l2/ppp/ppp_l2.c:359]: I'll add.

**Review by rerickson1 — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Review by JordanYates — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
