### PR TITLE
Bluetooth: TBS: clear pending GTBS notifications on disconnect

### LINKED ISSUE #104568: Bluetooth: TBS: GTBS does not clear pending notifications on disconnect
### Describe the bug

The `disconnected` callback in tbs.c does not handle anything related to GTBS: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/tbs.c#L352-L378

GTBS, like any TBS instance, should have its pending notifications cleared on disconnect. 

### Regression

- [ ] This is a regression.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

28e25ea1a76b0907f4ffc6a10a57d889522cd2dd

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Maxzuru**
Add missing notification clearing for the GTBS instance in the disconnected callback.

Fixes #104568

### CODE REVIEW

File: subsys/bluetooth/audio/tbs.c [hunk 1]
```diff
@@ -375,6 +375,28 @@ static void disconnected(struct bt_conn *conn, uint8_t reason)
 			__ASSERT(err == 0, "Failed to unlock mutex: %d", err);
 		}
 	}
+
+	/* Clear pending GTBS notifications */
+	const uint8_t conn_index = bt_conn_index(conn);
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: I would move this to the top of scope and use for both GTBS and TBS. It will be a single value :)

File: subsys/bluetooth/audio/tbs.c [hunk 2]
```diff
@@ -375,6 +375,28 @@ static void disconnected(struct bt_conn *conn, uint8_t reason)
...
+		/* In this case we still need to clear the data, so continue and hope for
+		 * the best
+		 */
+	}
+
+	if (gtbs_inst.cp_ntf.pending && conn_index == gtbs_inst.cp_ntf.conn_index) {
+		memset(&gtbs_inst.cp_ntf, 0, sizeof(gtbs_inst.cp_ntf));
+	}
+
+	memset(&gtbs_inst.flags[conn_index], 0, sizeof(gtbs_inst.flags[conn_index]));
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Minor: Our coding guidelines does require that we handle all return values, so this should have been

```suggestion
		(void)memset(&gtbs_inst.cp_ntf, 0, sizeof(gtbs_inst.cp_ntf));
	}

	(void)memset(&gtbs_inst.flags[conn_index], 0, sizeof(gtbs_inst.flags[conn_index]));
```

However given that this is not done right above, I can let these go through anyhow, but would be preferred if you add the `void` cast to follow our coding guidelines :)

File: subsys/bluetooth/audio/tbs.c [hunk 3]
```diff
@@ -375,6 +375,28 @@ static void disconnected(struct bt_conn *conn, uint8_t reason)
 			__ASSERT(err == 0, "Failed to unlock mutex: %d", err);
 		}
 	}
+
+	/* Clear pending GTBS notifications */
+	const uint8_t conn_index = bt_conn_index(conn);
+	int err = k_mutex_lock(&gtbs_inst.mutex, MUTEX_TIMEOUT);
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c]: Consider also declaring `err` at top of scope and then use that in the loop as well

**Review by Thalley — COMMENTED** [review]
No changes are absolutely needed, but would suggest these to be done

File: subsys/bluetooth/audio/tbs.c [hunk 4]
```diff
@@ -365,16 +365,38 @@ static void disconnected(struct bt_conn *conn, uint8_t reason)
...
 		if (err == 0) { /* if mutex was locked */
 			err = k_mutex_unlock(&svc_insts[i].mutex);
 			__ASSERT(err == 0, "Failed to unlock mutex: %d", err);
 		}
 	}
+
+	/* Clear pending GTBS notifications */
+	err = k_mutex_lock(&gtbs_inst.mutex, MUTEX_TIMEOUT);
+
+	if (err != 0) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/tbs.c:385]:
```suggestion
	err = k_mutex_lock(&gtbs_inst.mutex, MUTEX_TIMEOUT);
	if (err != 0) {
```

Minor

**Review by Thalley — DISMISSED** [review]
Thanks :)

**Review by Thalley — DISMISSED** [review]

**Review by larsgk — DISMISSED** [review]

**Comment by nashif** [comment]
@Maxzuru  please rebase

**Comment by Thalley** [comment]
> @Thalley Not sure if force-pushing triggers a notification, but the rebase dismissed the reviews. Content-wise nothing changed, I just resolved the merge conflict.

It does :)

**Review by Thalley — APPROVED** [review]

**Review by larsgk — APPROVED** [review]
