### PR TITLE
usb: handle endpoint-sized EP0 IN transactions

### LINKED ISSUE #15507: NRF52840: usb composite MSC + HID (with CONFIG_ENABLE_HID_INT_OUT_EP)
**Describe the bug**
Composite usb device MSC + HID does not work on Windows, the device does not complete the installation.
MSC can be either configured with either one of `CONFIG_DISK_ACCESS_RAM` or `CONFIG_DISK_ACCESS_FLASH`, HID has `CONFIG_ENABLE_HID_INT_OUT_EP=y` 

**To Reproduce**
1. git clone https://github.com/dmazzella/zephyr.git
2. cd zephyr/samples/subsys/usb/hid_w_out_ep-mass/
3. mkdir build && cd build
4. cmake -GNinja -DBOARD=nrf52840_pca10059 ..
5. ninja
6. flash zephyr.hex with Nrf Connect -> Programmer

**Expected behavior**
After writing the firmware using nRF Connect Programmer, I expect a composite  MSC + HID device (PCA10059) to be properly recognized. 
This is the case on Linux and macOS but on Windows 10 the USB composite device appears as _unknown device_.

**Impact**
Showstopper.

**Screenshots or console output**
56220817-6000ab80-6069-11e9-94cd-1c83c5b6e534
56220810-5d05bb00-6069-11e9-9e10-9b1e2b9f8410

**Environment (please complete the following information):**
 - OS:
    - Built on Windows 10 WSL, uname output `Linux dma-pc 4.4.0-17763-Microsoft #379-Microsoft x86_64 x86_64 x86_64 GNU/Linux`
    - Tested on Windows 10 - Version 1809 (build SO 17763.437)
 - Toolchain:
    - Zephyr version: 1.14.99
 - Commit SHA or Version used:
    - zephyrproject-rtos/zephyr 47b7c79e39365065876207d9f28593182cc40029

**Additional context**
I can try only with NRF52840 PCA10059

### PR DESCRIPTION
**Pull request by masz-nordic**
Fixes #15507

### CODE REVIEW

**Comment by masz-nordic** [comment]
@dmazzella @anddam Can you test whether this fixes the issue for you?

File: subsys/usb/usb_device.c [hunk 1]
```diff
@@ -233,12 +233,22 @@ static bool usb_handle_request(struct usb_setup_packet *setup,
...
+				    chunk, &chunk);
+	} else {
+		usb_dc_ep_write(USB_CONTROL_IN_EP0, usb_dev.data_buf,
+				chunk, &chunk);
+	}
+#else
+	usb_dc_ep_write(USB_CONTROL_IN_EP0, usb_dev.data_buf, chunk, &chunk);
+#endif
 	/*Always EP0 for control*/
-	usb_dc_ep_write(0x80, usb_dev.data_buf, chunk, &chunk);
```
Comment (finikorg) [inline subsys/usb/usb_device.c]: Cannot you just use `usb_dc_ep_write(0x80, NULL, 0, NULL)` ?

File: subsys/usb/usb_device.c [hunk 2]
```diff
@@ -233,12 +233,22 @@ static bool usb_handle_request(struct usb_setup_packet *setup,
  *
  * @return N/A
  */
-static void usb_data_to_host(void)
+static void usb_data_to_host(u16_t len)
 {
 	u32_t chunk = usb_dev.data_buf_residue;
 
+#if CONFIG_USB_NRF52840
```
Comment (finikorg) [inline subsys/usb/usb_device.c]: You need to be more specific, reel_board does not need this hack

File: subsys/usb/usb_device.c (hunk 1 above)
Comment (masz-nordic) [reply subsys/usb/usb_device.c]: No, this would result in ZLP only instead of 64B of descriptor + ZLP.

File: subsys/usb/usb_device.c (hunk 2 above)
Comment (masz-nordic) [reply subsys/usb/usb_device.c]: That's odd, there should be nothing board specific in this case. I will try to get hold of a reel_board and test it.

**Review by barsok — APPROVED** [review]

File: subsys/usb/usb_device.c (hunk 2 above)
Comment (finikorg) [reply subsys/usb/usb_device.c]: I also really do not like placing this code to common `usb_device.c`, any change this can be moved to device controller?

Comment (finikorg) [reply subsys/usb/usb_device.c]: reel_board

Comment (finikorg) [reply subsys/usb/usb_device.c]: For reel_board looks OK

File: include/drivers/usb/usb_dc.h [hunk 3]
```diff
@@ -308,6 +308,25 @@ int usb_dc_ep_flush(const u8_t ep);
...
+ *                       listed in the device configuration table
+ * @param[in]  data      Pointer to data to write
+ * @param[in]  data_len  Length of the data requested to write.
+ * @param[out] ret_bytes Bytes scheduled for transmission. This value
+ *                       may be NULL if the application expects all
+ *                       bytes to be written
+ *
+ * @return 0 on success, negative errno code on fail.
+ */
+int usb_dc_ep_write_zlp(const u8_t ep, const u8_t *const data,
```
Comment (finikorg) [inline include/drivers/usb/usb_dc.h]: we have already construction which is used for usb_transfer()
```			if (!(trans->flags & USB_TRANS_NO_ZLP)) {
				usb_write(ep, NULL, 0, NULL);
			}
```

File: drivers/usb/device/usb_dc_nrfx.c [hunk 4]
```diff
@@ -1619,13 +1619,15 @@ int usb_dc_ep_flush(const u8_t ep)
...
-		    const u32_t data_len, u32_t *const ret_bytes)
+static int usbd_ep_write(const u8_t ep, const u8_t *const data,
+			 const u32_t data_len, u32_t *const ret_bytes,
+			 bool zlp)
 {
 	LOG_DBG("ep_write: ep %d, len %d", ep, data_len);
 	struct nrf_usbd_ctx *ctx = get_usbd_ctx();
 	struct nrf_usbd_ep_ctx *ep_ctx;
 	u32_t bytes_to_copy;
+	u8_t flags = zlp ? NRFX_USBD_TRANSFER_ZLP_FLAG : 0;
```
Comment (finikorg) [inline drivers/usb/device/usb_dc_nrfx.c]: Cannot you use here something like?

```
flags = (ep == 0x80) && (data_len == 64) NRFX_USBD_TRANSFER_ZLP_FLAG : 0;
```

Comment (masz-nordic) [reply drivers/usb/device/usb_dc_nrfx.c]: No, because Windows expects a transfer without ZLP when `wLength == 64` and transfer with ZLP when `wLength > 64`.

Comment (finikorg) [reply drivers/usb/device/usb_dc_nrfx.c]: So in this case length is 64, so we do not send ZLP?

Comment (finikorg) [reply drivers/usb/device/usb_dc_nrfx.c]: OK, Windows asks length=255 despite we return 64 in the previous call, and it needs to know that this is the last packet, this can be the general case then.

Comment (masz-nordic) [reply drivers/usb/device/usb_dc_nrfx.c]: Basically this is what Windows expects:

| Descriptor length | wLength given by host |        ZLP?        |
|:-----------------:|:---------------------:|:------------------:|
|         64        |           64          |         :x:        |
|         64        |          255          | :heavy_check_mark: |

File: subsys/usb/usb_device.c (hunk 2 above)
Comment (masz-nordic) [reply subsys/usb/usb_device.c]: The issue exists on Windows only (7 & 10). I've tried reel_board and was able to reproduce it:

reel_board_zlp

File: subsys/usb/usb_device.c [hunk 5]
```diff
@@ -233,12 +233,22 @@ static bool usb_handle_request(struct usb_setup_packet *setup,
...
+	if ((chunk == USB_MAX_CTRL_MPS) && (len > USB_MAX_CTRL_MPS)) {
```
Comment (finikorg) [inline subsys/usb/usb_device.c]: If the chunk=64 but there are more data to be send it would send ZLP after first packet, should we check `usb_dev.data_buf_residue`

**Comment by masz-nordic** [comment]
@finikorg Thanks for pointing out an easier solution.

File: subsys/usb/usb_device.c [hunk 6]
```diff
@@ -233,14 +233,28 @@ static bool usb_handle_request(struct usb_setup_packet *setup,
...
 
 	/*Always EP0 for control*/
-	usb_dc_ep_write(0x80, usb_dev.data_buf, chunk, &chunk);
+	usb_dc_ep_write(USB_CONTROL_IN_EP0, usb_dev.data_buf, chunk, &chunk);
 	usb_dev.data_buf += chunk;
 	usb_dev.data_buf_residue -= chunk;
+
+	/*
+	 * Windows expects a ZLP after the last IN transaction that was
+	 * EP-sized if wLength was bigger than EP size.
```
Comment (finikorg) [inline subsys/usb/usb_device.c]: MPS - sized?

**Review by finikorg — APPROVED** [review]
LGTM with minor comment about EP-sized

File: subsys/usb/usb_device.c [hunk 7]
```diff
@@ -233,14 +233,28 @@ static bool usb_handle_request(struct usb_setup_packet *setup,
...
+	 */
+	if (!usb_dev.data_buf_residue && chunk == USB_MAX_CTRL_MPS
+	    && len > chunk) {
```
Comment (jfischer-phytec-iot) [inline subsys/usb/usb_device.c]: The comment above and the commit message are confusing and not correct. It seems there is a bug in our device stack. Please change the commit message and comment to something like the one from @finikorg "Send ZLP when host asks for the bigger length and the last chunk is wMaxPacketSize to indicate about the last packet.

See also:
_The Data stage of a control transfer from an endpoint to the host is complete when the endpoint does one of
the following:
• Has transferred exactly the amount of data specified during the Setup stage
• Transfers a packet with a payload size less than wMaxPacketSize or transfers a zero-length packet
(5.5.3 USB Specification Revision 2.0)_

_A control pipe may have a variable-length data phase in which the host requests more data than is contained
in the specified data structure ....... If the data structure is an exact multiple of wMaxPacketSize for the pipe, the function will return a zero-length packet to indicate the end of the Data stage. (8.5.3.2 USB Specification Revision 2.0)_

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: subsys/usb/usb_device.c (hunk 7 above)
Comment (finikorg) [reply subsys/usb/usb_device.c]: Agree here with @jfischer-phytec-iot

Comment (masz-nordic) [reply subsys/usb/usb_device.c]: Fixed

**Review by jfischer-no — APPROVED** [review]

**Comment by jfischer-phytec-iot** [comment]
I guess it should be backported to 1.14, @carlescufi @finikorg ?
