### PR TITLE
Bluetooth: Controller: Fix MIC failures, assertions and bus faults

### LINKED ISSUE #89736: Bluetooth: Controller: Missing CIS Established event with default ACL buffer size
**Describe the bug**
If `CONFIG_BT_BUF_ACL_RX_SIZE`/`CONFIG_BT_CTLR_DATA_LENGTH_MAX` is set to their default value of 27 then it seems that there's an issue with generating/providing the CIS Established event to the host. 

**To Reproduce**
1. Comment out `CONFIG_BT_BUF_ACL_RX_SIZE` and `CONFIG_BT_CTLR_DATA_LENGTH_MAX` in https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/hci_ipc/nrf5340_cpunet_iso-bt_ll_sw_split.conf
1. west build -b nrf5340_audio_dk/nrf5340/cpuapp --sysbuild samples/bluetooth/bap_unicast_client/ -- -DCONFIG_BT_ISO_LOG_LEVEL_DBG=y
2. west flash
3. west build -b nrf5340_audio_dk/nrf5340/cpuapp --sysbuild samples/bluetooth/bap_unicast_server/ -- -DCONFIG_BT_ISO_LOG_LEVEL_DBG=y
4. west flash
5. See unicast client having a CIS stuck in the connecting state

**Expected behavior**
Expect that the ACL buffer size does not affect the generation of the CIS established event / CIS establishment. 

**Impact**
A workaround is simply setting the value higher. At the time of reporting this, a minimum required value has not been determined, but at least setting 255/251 (the values configured by https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/bluetooth/hci_ipc/nrf5340_cpunet_iso-bt_ll_sw_split.conf works). 

**Logs and console output**
```
Connecting streams
[00:00:09.021,728] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x200078b4 iso 0x20006640 disconnected -> connecting
[00:00:09.372,314] <dbg> bt_iso: hci_le_cis_established: status 0x00  handle 7
[00:00:09.372,344] <dbg> bt_iso: store_cis_info: iso_chan 0x200078b4 tx 0x200078f8 rx 0x200078d8
[00:00:09.372,344] <dbg> bt_iso: bt_iso_connected: 0x20006640
[00:00:09.372,406] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x200078b4 iso 0x20006640 connecting -> connected
Audio Stream 0x20007478 connected
Audio Stream 0x20007428 connected
[00:00:09.372,985] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x20007914 iso 0x20006738 disconnected -> **connecting**
Audio Stream 0x20007428 started
```

**Environment (please complete the following information):**
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK
 - Commit SHA or Version used: f7a2b4e9136a37d0622e2c809b5599253209e90e

**Additional context**
The issue was found during some PTS testing, and a fix was done in https://github.com/zephyrproject-rtos/zephyr/pull/89680 for the BT Tester. In those cases connecting a single CIS fails, but in the samples we properly connect the first CIS, but not the second. This could indicate that only the last (or only if there's only a single CIS) fails to be established.

### PR DESCRIPTION
**Pull request by cvinayak**
Fix missing removal of redundant ISO Rx size in ACL Rx PDU
allocation size.

Related to commit https://github.com/zephyrproject-rtos/zephyr/commit/7c89f1fe9f2ed89b666dd9f7df0b95f94c7849be ("Bluetooth: controller:
Support for separate ISO RX data path").

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

Fixes #89736

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_conn_iso.c [hunk 1]
```diff
@@ -345,7 +345,7 @@ ull_conn_iso_lll_stream_sorted_get_by_group(struct lll_conn_iso_group *cig_lll,
 		cis = ll_conn_iso_stream_get(handle);
 
 		/* Match CIS contexts associated with the CIG */
-		if (cis->group == cig) {
+		if ((cis->group == cig) && cis->lll.active) {
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_conn_iso.c:348]: Since `cis->lll.active` is technically not a boolean, although treated as such, it does not really match our coding guidelines that require control statements like `if`s to use effective boolean expressions. 

It's just a mention, as I don't know if this is something that should/could be applied in the controller code, but our coding guide does _technically_ require this to be
```suggestion
		if ((cis->group == cig) && cis->lll.active == 1U) {
```

**Review by Thalley — DISMISSED** [review]
The PR fixes the issues I've seen/reported

**Review by Thalley — APPROVED** [review]

**Review by Tronil — APPROVED** [review]
Looks good to me
