### PR TITLE
drivers: use node IDs for DEVICE_MMIO.*_INIT

### LINKED ISSUE #26984: sys/device_mmio.h API design should accept generic DT node identifiers
**Describe the bug**

I'm calling this a bug since I think the API design has a very minor flaw that should be easy to fix. However, validity should be discussed and determined by @galak and @andrewboie. No hurt feelings if this just gets closed :smile: .

During a Slack discussion with @andrewboie, he pointed out the way the new device_mmio.h API uses devicetree instance numbers exclusively to get information out of the DT. There is nothing wrong with instance numbers and they are recommended for use whenever possible, but this is an API design problem because it's not always possible to get nodes by instance number; in some cases, drivers need to get node identifiers from node labels, for example. (This is described in gory detail in the DT HOWTOs page.)

I haven't looked at this code in detail, but I would suggest that `DEVICE_MMIO_ROM_INIT(instance)`  be renamed `DEVICE_MMIO_ROM_INST_INIT(instance)`. The renamed macro would be written in terms of a version of  `DEVICE_MMIO_ROM_INIT(node_id)` that takes a generic node identifier instead of an instance number.

So something like this (untested, just being concrete here):

```
#ifdef DEVICE_MMIO_IS_IN_RAM
/* ... */
#define Z_DEVICE_MMIO_ROM_INITIALIZER(node_id) \
        { \
                .phys_addr = DT_REG_ADDR(node_id), \
                .size = DT_REG_SIZE(node_id) \
        }
#else
/* ... */
#define Z_DEVICE_MMIO_ROM_INITIALIZER(node_id) \
        { \
                .addr = DT_REG_ADDR(node_id) \
        }
#endif

/* ... */

#define DEVICE_MMIO_ROM_INIT(node_id) Z_DEVICE_MMIO_ROM_INITIALIZER(node_id)
#define DEVICE_MMIO_ROM_INST_INIT(instance) DEVICE_MMIO_ROM_INIT(DT_DRV_INST(instance))
```

Or something like that. The point being that there should be a non-instance-number way to do the same thing.

**Expected behavior**

I expect that all APIs which use data from devicetree nodes should have some version that accepts arbitrary node identifiers, not just instance numbers.

### PR DESCRIPTION
**Pull request by tyrantlizard77**
There is nothing wrong with instance numbers and they are
recommended for use whenever possible, but this is an API
design problem because it's not always possible to get nodes
by instance number; in some cases, drivers need to get node
identifiers from node labels, for example.

Change these APIs (which are not yet in any Zephyr release)
to take node IDs instead of instance IDs.

Fixes: #26984

Signed-off-by: Andrew Boie <andrew.p.boie@intel.com>

### CODE REVIEW

File: include/sys/device_mmio.h [hunk 1]
```diff
@@ -218,27 +218,27 @@ struct z_device_mmio_rom {
...
  * }
  *
  * @see DEVICE_MMIO_ROM()
  *
- * @param instance DTS instance
+ * @param node_id DTS node_id
  */
-#define DEVICE_MMIO_ROM_INIT(instance) \
-	._mmio = Z_DEVICE_MMIO_ROM_INITIALIZER(instance)
+#define DEVICE_MMIO_ROM_INIT(node_id) \
```
Comment (mbolivar-nordic) [inline include/sys/device_mmio.h:240]: I guess you decided against adding a seaprate DEVICE_MMIO_ROM_INST_INIT(inst) to avoid the DT_DRV_INST boilerplate in the callers? No objections if you want to keep the API surface here smaller, but I had suggested that in the original issue to keep the typing down. Your call, of course.

**Review by mbolivar-nordic — APPROVED** [review]

File: include/sys/device_mmio.h (hunk 1 above)
Comment (andrewboie) [reply include/sys/device_mmio.h:240]: this file already has a lot of different macro variants in it, and I felt this would only save user typing a few characters.

**Review by pabigot — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
