### PR TITLE
[WIP] random: changed implementation of rand32_timer.c

### LINKED ISSUE #47908: tests/kernel/mem_protect/stack_random works unreliably and sporadically fails
The `tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random` works unreliably and sporadically fails after changes not related to it (ot the part of code which is tested by it).

The fail symptoms:

```
Running TESTSUITE stack_pointer_randomness
===================================================================
START - test_stack_pt_randomization
Test Stack pointer randomization
stack pointer changed 0 times out of 64 tests

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/mem_protect/stack_random/src/main.c:81: stack_pointer_randomness_test_stack_pt_randomization: (sp_changed equal to 0)
Stack pointer is not randomized
 FAIL - test_stack_pt_randomization in 0.15 seconds
===================================================================
TESTSUITE stack_pointer_randomness failed.
===================================================================
PROJECT EXECUTION FAILED
```

The test is checking the `CONFIG_STACK_POINTER_RANDOM` feature which should enable initial thread stack pointer randomization.

I've debugged the test and it appeared to be that thread stack pointer is actually **not randomized**, but any change to the code make test passing.

The test uses TEST_RANDOM_GENERATOR (which is known for low quality of random values provided) and when I've checked the values provided by it I've found that last byte of 'random' value is always the same:

```
427784e7
7e1251e7
b9ad1ee7
f547ebe7
30e2b8e7
```

And for stack randomization we shrink the random value (see random_offset function):
```
size_t fuzz = random_val % CONFIG_STACK_POINTER_RANDOM;
```

As `CONFIG_STACK_POINTER_RANDOM=64` the value we use for randomization is always the same (0x27).

The TEST_RANDOM_GENERATOR uses following algo to provide random values:

```
_rand32_counter += 1000000003U;

random_ret_val = k_cycle_get_32() + _rand32_counter;
```

As in the test we just continuously executing the same code in a loop, the differences between k_cycle_get_32() calls in TEST_RANDOM_GENERATOR are the same (0x2FD in this case) which cause the random returning values with identical last byte.

There were identical issues with `kernel.memory_protection.stack_random` with some hacks to TEST_RANDOM_GENERATOR:

https://github.com/zephyrproject-rtos/zephyr/pull/36996
https://github.com/zephyrproject-rtos/zephyr/pull/37499

But looks like we either need to significantly improve TEST_RANDOM_GENERATOR or make the test less vulnerable to such random issue or disable the test to avoid sporadic failures.

### PR DESCRIPTION
**Pull request by decsny**
Changes the implementation of rand32_timer.c because it was not generating sufficiently "random"-looking values on some platforms, the implementation is now a "psuedo-xoshiro"

Requesting comments

Fixes #47908

### CODE REVIEW

File: subsys/random/rand32_timer.c [hunk 1]
```diff
@@ -14,21 +14,47 @@
...
 
-#define _RAND32_INC 1000000003U
+static uint32_t state[4];
+
+static inline uint32_t rotl(const uint32_t x, int k)
+{
+	return (x << k) | (x >> (32 - k));
+}
+
+static int xoshiro128_init_state(const struct device *dev)
```
Comment (galak) [inline subsys/random/rand32_timer.c:34]: why not just initialize it when you declare it?  What's the point of this function?

Comment (decsny) [reply subsys/random/rand32_timer.c]: that was an artifact from when I was trying to do something else to get the initial state values, I have now changed it

File: subsys/random/rand32_timer.c [hunk 2]
```diff
@@ -14,21 +14,38 @@
...
 #if defined(__GNUC__)
 
-/*
- * Symbols used to ensure a rapid series of calls to random number generator
- * return different values.
- */
-static atomic_val_t _rand32_counter;
 
-#define _RAND32_INC 1000000003U
+static uint32_t state[4] = {0, 0x9b64c2b0, 0x86d3d2d4, 0xa00ae278};
```
Comment (galak) [inline subsys/random/rand32_timer.c:27]: Probably good to add a comment about where these magic numbers come from.

Comment (dleach02) [reply subsys/random/rand32_timer.c:27]: @galak, these are the same magic numbers found in xoshiro.c and from the comment they are just some pseudo random values

**Comment by dleach02** [comment]
@d3zd3z, @ceolin, @evgeniy-paltsev 

I asked @decsny to create this draft PR to show how we can shift the timer based RNG to leverage the xoshiro algorithm to hopefully avoid the problems seen with clipped RNG values. Please review and consider this.

And note that this is for testing and platforms that do not have a good entropy source which we already warn in the build flow.

File: subsys/random/rand32_timer.c [hunk 3]
```diff
@@ -14,21 +14,38 @@
  * provide a random number generator.
  */
```
Comment (dleach02) [inline subsys/random/rand32_timer.c:16]: @decsny, pull over the attribution information from the xoshiro code into this header

File: subsys/random/rand32_timer.c [hunk 4]
```diff
@@ -41,7 +58,7 @@ static atomic_val_t _rand32_counter;
...
 uint32_t z_impl_sys_rand32_get(void)
 {
-	return k_cycle_get_32() + atomic_add(&_rand32_counter, _RAND32_INC);
+	return k_cycle_get_32() + xoshiro128_next();
```
Comment (evgeniy-paltsev) [inline subsys/random/rand32_timer.c:61]: As we are now using the quality pseudo-random algorithm - let's drop this `k_cycle_get_32` which was used as an attempt of workaround the previous badly designed implementation.

Comment (d3zd3z) [reply subsys/random/rand32_timer.c:61]: Agree with @dleach02 here. It is import that we distinguish between "quality" of a pseudo-random algorithm for things like network timing backoffs and similar, and a cryptographic quality PRNG, which xoshiro128 is not.

File: subsys/random/rand32_timer.c [hunk 5]
```diff
@@ -14,21 +14,38 @@
...
+	const uint32_t result = rotl(state[0] + state[3], 7) + state[0];
+	const uint32_t t = state[1] << 9;
+
+	state[2] ^= state[0];
+	state[3] ^= state[1];
+	state[1] ^= state[2];
+	state[0] ^= state[3];
+
+	state[2] ^= t;
+	state[3] = rotl(state[3], 11);
```
Comment (evgeniy-paltsev) [inline subsys/random/rand32_timer.c:45]: I guess we want to add some locking here as we access to global data and we may call this from multiple treads. spinlock will suite perfectly fine.

File: subsys/random/rand32_timer.c (hunk 4 above)
Comment (evgeniy-paltsev) [reply subsys/random/rand32_timer.c:61]: > Agree with @dleach02 here. It is import that we distinguish between "quality" of a pseudo-random algorithm for things like network timing backoffs and similar

And I'm indeed talking about that :)

We already have multiple re-spins of rand32_timer which were trying to fix some situation when rand32_timer produce non random output (e.g see #37499) but we still have issues with it because of this k_cycle_get_32() addition - like in the current #47908 issue. It's not about cryptographic quality PRNG - it's about PRNG producing same value every call :)
Probably it' time to drop this k_cycle_get_32 call.

And as for naming - I guess it's fine to rename it to `rand32_test.c` as it anyway depends on `TEST_RANDOM_GENERATOR` option.

File: subsys/random/rand32_timer.c (hunk 5 above)
Comment (dleach02) [reply subsys/random/rand32_timer.c:45]: threads injecting here might actually help this test rng ;-)

**Review by dleach02 — APPROVED** [review]

**Comment by dleach02** [comment]
@d3zd3z @evgeniy-paltsev @galak @ceolin can you revisit this PR?

**Review by ceolin — APPROVED** [review]

**Review by evgeniy-paltsev — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
Still a WIP?

**Review by desowin — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
This is breaking `main`. I have opened a PR for reverting it for now: https://github.com/zephyrproject-rtos/zephyr/pull/53601
Perhaps this should have been rebased and tests rerun before merging?

**Comment by decsny** [comment]
yeah this was not ready to be merged, it was a month+ old branch....

**Comment by evgeniy-paltsev** [comment]
@decsny I'm wondering if you have any plans to rebase it and create new PR?

Thanks!
