### PR TITLE
lib: os: mempool: Fix unused return values from sys_mutex_lock calls

### LINKED ISSUE #25983: [Coverity CID :210682] Unchecked return value in lib/os/mempool.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/c61dfdc680615a1d636d1a676897815860ca4da5/lib/os/mempool.c#L329

Category: Error handling issues
Function: `sys_mem_pool_alloc`
Component: Other
CID: [210682](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210682)

Details:

```
323     void *sys_mem_pool_alloc(struct sys_mem_pool *p, size_t size)
324     {
325         struct sys_mem_pool_block *blk;
326         u32_t level, block;
327         char *ret;
328    
>>>     CID 210682:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "sys_mutex_lock" without checking return value (as is done elsewhere 17 out of 20 times).
329         sys_mutex_lock(&p->mutex, K_FOREVER);
330    
331         size += WB_UP(sizeof(struct sys_mem_pool_block));
332         if (z_sys_mem_pool_block_alloc(&p->base, size, &level, &block,
333                           (void **)&ret)) {
334             ret = NULL;
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #25984: [Coverity CID :210686] Unchecked return value in lib/os/mempool.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/c61dfdc680615a1d636d1a676897815860ca4da5/lib/os/mempool.c#L361

Category: Error handling issues
Function: `sys_mem_pool_free`
Component: Other
CID: [210686](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210686)

Details:

```
355         }
356    
357         ptr = (char *)ptr - WB_UP(sizeof(struct sys_mem_pool_block));
358         blk = (struct sys_mem_pool_block *)ptr;
359         p = blk->pool;
360    
>>>     CID 210686:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "sys_mutex_lock" without checking return value (as is done elsewhere 17 out of 20 times).
361         sys_mutex_lock(&p->mutex, K_FOREVER);
362         z_sys_mem_pool_block_free(&p->base, blk->level, blk->block);
363         sys_mutex_unlock(&p->mutex);
364     }
365    
366     size_t sys_mem_pool_try_expand_inplace(void *ptr, size_t requested_size)
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by laurenmurphyx64**
Fixes Coverity issues 210682 and 210686.

Fixes #25983
Fixes #25984

Signed-off-by: Lauren Murphy <lauren.murphy@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

File: lib/os/mempool.c [hunk 1]
```diff
@@ -328,8 +328,10 @@ void *sys_mem_pool_alloc(struct sys_mem_pool *p, size_t size)
 	struct sys_mem_pool_block *blk;
 	uint32_t level, block;
 	char *ret;
+	int err;
 
-	sys_mutex_lock(&p->mutex, K_FOREVER);
+	err = sys_mutex_lock(&p->mutex, K_FOREVER);
+	__ASSERT(err == 0, "sys_mutex_lock failed with %d", err);
```
Comment (nashif) [inline lib/os/mempool.c:334]: should consider using CHECKIF here:

```
err = sys_mutex_lock(&p->mutex, K_FOREVER);
CHECKIF(err != 0) {
	ret = NULL;
	goto out;
}
```
also, err as a variable name might be misleading, the function might return a non error return code, you could use ret but it is already used :)

Comment (laurenmurphyx64) [reply lib/os/mempool.c]: Changed both instances to use CHECKIF and changed variable names from err to lock_ret. Would that variable name be more clear?

**Review by dcpleung — APPROVED** [review]

File: lib/os/mempool.c [hunk 2]
```diff
@@ -328,8 +329,13 @@ void *sys_mem_pool_alloc(struct sys_mem_pool *p, size_t size)
 	struct sys_mem_pool_block *blk;
 	uint32_t level, block;
 	char *ret;
+	int lock_ret;
 
-	sys_mutex_lock(&p->mutex, K_FOREVER);
+	lock_ret = sys_mutex_lock(&p->mutex, K_FOREVER);
+	CHECKIF(lock_ret != 0) {
+		ret = NULL;
+		goto out;
```
Comment (ceolin) [inline lib/os/mempool.c:337]: you should return here and not jump to `out` to avoid call `sys_mutex_unlock` since the mutex was not locked.

File: lib/os/mempool.c [hunk 3]
```diff
@@ -361,8 +368,12 @@ void sys_mem_pool_free(void *ptr)
 	blk = (struct sys_mem_pool_block *)ptr;
 	p = blk->pool;
 
-	sys_mutex_lock(&p->mutex, K_FOREVER);
+	lock_ret = sys_mutex_lock(&p->mutex, K_FOREVER);
+	CHECKIF(lock_ret != 0) {
+		goto out;
```
Comment (ceolin) [inline lib/os/mempool.c:373]: the mutex was not locked, just return. There is no need to that label.

**Review by ceolin — CHANGES_REQUESTED** [review]
Please take a look in the comments, you need to change the error handling path imho.

File: lib/os/mempool.c (hunk 2 above)
Comment (laurenmurphyx64) [reply lib/os/mempool.c]: Changed goto to return NULL and changed the other goto to just return, could you take another look?

**Review by ceolin — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Oh, realize I never gave this a +1
