### PR TITLE
Bluetooth: controller: split: Fix check for control procedures request

### LINKED ISSUE #20781: peripheral_hr on VEGABoard disconnects from central_hr after BT_CONN_PARAM_UPDATE_TIMEOUT
**Describe the bug**
When running peripheral_hr on a VEGABoard, connected to a nrf52 central_hr, after 5s, the peripheral disconnects with error code 0x08 (timeout).

**To Reproduce**
1. cmake -Bbuild_vega -G"Eclipse CDT4 - Ninja" -DBOARD=rv32m1_vega_ri5cy -DCMAKE_REQUIRED_FLAGS=-Wl,-dT=/dev/null /work/zephyr/zephyr-source/samples/bluetooth/peripheral_hr
2. ninja -Cbuild_vega
3. deploy on VEGA Board

**Expected behavior**
The peripheral_hr is able to communicate endlessly with the central_hr

**Impact**
The VEGA SW LL disconnects after 5s (which is equal to BT_CONN_PARAM_UPDATE_TIMEOUT), and reconnects, which is a showstopper (unstable)

**Screenshots or console output**
**central_hr**:
***** Booting Zephyr OS build v2.1.0-rc1-151-g8125da91eb3c *****
Bluetooth initialized
Scanning successfully started
[DEVICE]: ed:8f:dd:77:f0:7a (random), AD evt type 0, AD data len 11, RSSI -21
[AD]: 1 data_len 1
[AD]: 3 data_len 6
Connected: ed:8f:dd:77:f0:7a (random)
[ATTRIBUTE] handle 25
[ATTRIBUTE] handle 26
[ATTRIBUTE] handle 28
[SUBSCRIBED]
[NOTIFICATION] data 0x200065f7 length 2
[00:00:00.066,000] <wrn> bt_hci_core: Vendor HCI extensions not available
[00:00:00.066,000] <inf> bt_hci_core: Identity: 00:60:37:07:6a:3e (public)
[00:00:00.066,000] <inf> bt_hci_core: HCI: version 4.2 (0x08) revision 0x000b, manufacturer 0x0025
[00:00:00.067,000] <inf> bt_hci_core: LMP: version 4.2 (0x08) subver 0x0123
[NOTIFICATION] data 0x200065f7 length 2
[NOTIFICATION] data 0x200065f7 length 2
[NOTIFICATION] data 0x200065f7 length 2
[NOTIFICATION] data 0x200065f7 length 2
[UNSUBSCRIBED]
Disconnected: ed:8f:dd:77:f0:7a (random) (reason 0x08)
[DEVICE]: ed:8f:dd:77:f0:7a (random), AD evt type 0, AD data len 11, RSSI -21
[AD]: 1 data_len 1
[AD]: 3 data_len 6
Connected: ed:8f:dd:77:f0:7a (random)
[ATTRIBUTE] handle 25
[ATTRIBUTE] handle 26
[ATTRIBUTE] handle 28
[SUBSCRIBED]
[NOTIFICATION] data 0x200065f7 length 2
[NOTIFICATION] data 0x200065f7 length 2
[NOTIFICATION] data 0x200065f7 length 2
[NOTIFICATION] data 0x200065f7 length 2
[NOTIFICATION] data 0x200065f7 length 2
[UNSUBSCRIBED]
Disconnected: ed:8f:dd:77:f0:7a (random) (reason 0x08)

**peripheral:**
***** Booting Zephyr OS build v2.1.0-rc1-171-g472efcd0f881 *****
Bluetooth initialized
Advertising successfully started
[00:00:00.020,000] <inf> bt_hci_core: HW Platform: reserved (0x0000)
[00:00:00.020,000] <inf> bt_hci_core: HW Variant: unknown (0x0000)
[00:00:00.020,000] <inf> bt_hci_core: Firmware: Standard Bluetooth controller (0x00) Version 2.1 Build 0
[00:00:00.030,000] <wrn> bt_hci_core: No static addresses stored in controller
[00:00:00.180,000] <inf> bt_hci_core: Identity: ed:8f:dd:77:f0:7a (random)
[00:00:00.180,000] <inf> bt_hci_core: HCI: version 5.1 (0x0a) revision 0x0000, manufacturer 0x05f1
[00:00:00.180,000] <inf> bt_hci_core: LMP: version 5.1 (0x0a) subver 0xffff
Connected
[00:00:06.890,000] <inf> hrs: HRS notifications enabled
Disconnected (reason 0x08)
Connected
[00:00:16.040,000] <inf> hrs: HRS notifications disabled
[00:00:16.390,000] <inf> hrs: HRS notifications enabled
Disconnected (reason 0x08)
Connected
[00:00:25.550,000] <inf> hrs: HRS notifications disabled
[00:00:25.900,000] <inf> hrs: HRS notifications enabled
Disconnected (reason 0x08)
Connected
[00:00:35.060,000] <inf> hrs: HRS notifications disabled
[00:00:35.410,000] <inf> hrs: HRS notifications enabled

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: VEGA OpenISA official toolchain
 - head/master

Reverting d1d603afc3558f31a4728d70179d1cb5d74890c5 Bluetooth: controller: split: Fix conn update to be cacheable seems to 'fix' it.

### PR DESCRIPTION
**Pull request by George-Stefan**
Remove wrong #ifdef that guarded the control procedures request check

Fixes #20781

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 1]
```diff
@@ -782,10 +781,8 @@ int ull_conn_llcp(struct ll_conn *conn, u32_t ticks_at_expire, u16_t lazy)
 
 		/* TODO: Optimize the checks below, maybe have common flag */
 
-		if (0) {
```
Comment (cristic-devel) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: This if (0) is related to the TODO above. Maybe you should not remove them until you fix the TODO

Comment (George-Stefan) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: > This if (0) is related to the TODO above. Maybe you should not remove them until you fix the TODO

@cvinayak ^^

Comment (joerchan) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: I don't think it is related to the TODO. The `if (0)` thing is used many places other than this.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 2]
```diff
@@ -769,7 +769,6 @@ int ull_conn_llcp(struct ll_conn *conn, u32_t ticks_at_expire, u16_t lazy)
 {
 	LL_ASSERT(conn->lll.handle != 0xFFFF);
 
-#if defined(CONFIG_BT_CTLR_CONN_PARAM_REQ) || defined(CONFIG_BT_CTLR_PHY)
```
Comment (cristic-devel) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: Why removing the configuration parameter instead of changing the Vega vendor to select it? For the Vega, this parameter is disabled.

Name: BT_CTLR_CONN_PARAM_REQ_SUPPORT
Type: bool
Value: n

Direct dependencies (=y):
     BT_HCI(=y)
  && BT(=y)

Symbols currently n-selecting this symbol (no effect):
  - BT_LL_SW_LEGACY
  - BT_LLL_VENDOR_NORDIC

Comment (George-Stefan) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: The check for conn update request was put under conn param req #ifdef which are unrelated

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: no, it is not related to TODO. Its safe to remove. It only made sense when the very first if clause too is conditionally compile-able. Here it is not the case.

**Review by cvinayak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
