### PR TITLE
modbus: support async modbus serial

### LINKED ISSUE #71767: modbus: crc mismatch due to missing rx bytes at high baud rates (460800)
**Notes**
I simplified the modbus RTU samples (server and client) to a few lines of code (see below) and I am running two nRF52840 development boards: one as server and one as client with serial rx and tx wires connected crosswise. 

The difference to the default samples is mainly increasing the baud rate and deleting the irrelevant coil read/write code.

**Describe the bug**
The problem I am experiencing is that some received bytes are missing, which leads to crc mismatch (<wrn> modbus_serial: Calculated CRC does not match received CRC). This however happens only when using a relatively high baud rate: 460800. With the default baud rate from the sample (19200) or even with 115200 I was not able to see this problem. 

The problem occurs almost all the time, especially with longer packets, but does also appear sometimes with smaller ones. In the edited samples attached, I am experiencing with 64 number of registers (128 bytes to be read). I am guessing it is a timing issue that interrupts are not being serviced as quickly as needed with this baud rate. 

This is not a hardware issue: I attached the serial lines to a logic decoder and I was able to see all the rx bytes as expected within the expected time. 

**To Reproduce**
1. build the zephyr/samples/subsys/modbus/rtu_server after replacing its main.c with the attached snippet and flash it to one development board
2. build the zephyr/samples/subsys/modbus/rtu_client after replacing its main.c with the attached snippet and flash it to the other development board
3. connect tx and rx lines of the two boards crosswise and connect their GNDs together with a third jumper wire, 

**Expected behavior**
Receive complete data (without bytes missing) and so without crc mismatch.

**Impact**
Showstopper for anyone who wants to use a high baud rate.

**Environment (please complete the following information):**
 - OS: (Linux Ubuntu)
 - Toolchain (Zephyr v3.2.0)

**Additional context**
pin setting is defined in the overlay file attched. 

[missing_bytes_minimal_examples.zip](https://github.com/zephyrproject-rtos/zephyr/files/15063195/missing_bytes_minimal_examples.zip)

### PR DESCRIPTION
**Pull request by lanwer50**
Support the use of async api in modbus_serial.c. Reason for this extension are crc mismatches happening due to rx data loss when using the interrupt driven api (default modbus implementation) at higher speeds and/or high cpu load. It is recommended to use the async api (implemented in this MR) along with hardware byte counting requiring a timer instance and one PPI channel to achieve a robust communication at high baudrates. A new Kconfig CONFIG_MODBUS_SERIAL_ASYNC_API to enable/disable this feature has been added. 

Fixes #71767

Signed-off-by: Anouar Raddaoui <a.raddaoui@smight.com>

### CODE REVIEW

File: subsys/modbus/Kconfig [hunk 1]
```diff
@@ -47,6 +47,13 @@ config MODBUS_SERIAL
 	imply UART_USE_RUNTIME_CONFIGURE
 	help
 	  Enable Modbus over serial line support.
+	  
+config MODBUS_SERIAL_ASYNC_API
+	depends on MODBUS_SERIAL
+    bool "Modbus over serial line with async api support"
+    default n
```
Comment (bjarki-trackunit) [inline subsys/modbus/Kconfig:54]: It also depends on `UART_ASYNC_API`, and `default n` is the default so it can be left out :)

Comment (lanwer50) [reply subsys/modbus/Kconfig]: Thanks for the feedback. Changes are done.

**Comment by MaureenHelm** [comment]
@jfischer-no please take a look

**Comment by kartben** [comment]
@jfischer-no can you please help review when you have time? Thanks!

File: subsys/modbus/modbus_serial.c [hunk 2]
```diff
@@ -592,11 +657,20 @@ int modbus_serial_init(struct modbus_context *ctx,
...
-	k_timer_init(&cfg->rtu_timer, rtu_tmr_handler, NULL);
-	k_timer_user_data_set(&cfg->rtu_timer, ctx);
+	if (IS_ENABLED(CONFIG_MODBUS_SERIAL_ASYNC_API)) {
+		int err = uart_callback_set(cfg->dev, uart_cb_async_handler, ctx);
+
+		if (err != 0) {
+			LOG_ERR("uart_callback_set returns error = %d", err);
+		}
+	} else {
+		uart_irq_callback_user_data_set(cfg->dev, uart_cb_handler, ctx);
```
Comment (jfischer-no) [inline subsys/modbus/modbus_serial.c:667]: Please check return value here as well.
```c
		err = uart_irq_callback_user_data_set(cfg->dev, uart_cb_handler, ctx);
		if (!err) {
			k_timer_init(&cfg->rtu_timer, rtu_tmr_handler, NULL);
			k_timer_user_data_set(&cfg->rtu_timer, ctx);
			modbus_serial_rx_on(ctx);
		}
```

File: subsys/modbus/modbus_serial.c [hunk 3]
```diff
@@ -592,11 +657,20 @@ int modbus_serial_init(struct modbus_context *ctx,
...
+		k_timer_init(&cfg->rtu_timer, rtu_tmr_handler, NULL);
+		k_timer_user_data_set(&cfg->rtu_timer, ctx);
+
+		modbus_serial_rx_on(ctx);
+	}
 
-	modbus_serial_rx_on(ctx);
 	LOG_INF("RTU timeout %u us", cfg->rtu_timeout);
 
 	return 0;
```
Comment (jfischer-no) [inline subsys/modbus/modbus_serial.c:676]: `return err;`

**Review by jfischer-no — CHANGES_REQUESTED** [review]
The ASYNC part is not tested, the default testing platform does not support ASYNC mode. I need to find some time to find out how to resolve it.

**Comment by lanwer50** [comment]
I would like to remove the "closed" label to adapt the changes suggested in the review.

File: subsys/modbus/modbus_serial.c [hunk 4]
```diff
@@ -37,14 +37,27 @@ static void modbus_serial_tx_on(struct modbus_context *ctx)
 		gpio_pin_set(cfg->de->port, cfg->de->pin, 1);
 	}
 
-	uart_irq_tx_enable(cfg->dev);
+	if (IS_ENABLED(CONFIG_MODBUS_SERIAL_ASYNC_API)) {
+		int err = uart_tx(cfg->dev, cfg->uart_buf, cfg->uart_buf_ctr, SYS_FOREVER_US);
+
+		if (err) {
```
[the remark this answers is not in the document]
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/modbus_serial.c [hunk 5]
```diff
@@ -37,14 +37,27 @@ static void modbus_serial_tx_on(struct modbus_context *ctx)
...
+			LOG_ERR("uart_tx returns error = %d", err);
```
[the remark this answers is not in the document]
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/modbus_serial.c [hunk 6]
```diff
@@ -37,14 +37,27 @@ static void modbus_serial_tx_on(struct modbus_context *ctx)
...
 static void modbus_serial_tx_off(struct modbus_context *ctx)
 {
 	struct modbus_serial_config *cfg = ctx->cfg;
 
-	uart_irq_tx_disable(cfg->dev);
+	if (IS_ENABLED(CONFIG_MODBUS_SERIAL_ASYNC_API)) {
+		/* Do nothing */
+	} else {
+		uart_irq_tx_disable(cfg->dev);
+	}
```
[the remark this answers is not in the document]
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/modbus_serial.c [hunk 7]
```diff
@@ -58,14 +71,31 @@ static void modbus_serial_rx_on(struct modbus_context *ctx)
...
+	if (IS_ENABLED(CONFIG_MODBUS_SERIAL_ASYNC_API)) {
+		/* Reset memory before receiving */
+		memset(cfg->uart_buf, 0, sizeof(cfg->uart_buf));
+
+		int err = uart_rx_enable(cfg->dev, cfg->uart_buf,
+				   sizeof(cfg->uart_buf), cfg->rtu_timeout);
+
+		if (err) {
+			LOG_ERR("uart_rx_enable returns error = %d", err);
+		}
```
[the remark this answers is not in the document]
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/modbus_serial.c [hunk 8]
```diff
@@ -401,6 +431,41 @@ static void uart_cb_handler(const struct device *dev, void *app_data)
...
+		k_work_submit(&ctx->server_work);
+		break;
+	case UART_TX_ABORTED:
+	case UART_RX_STOPPED:
+	case UART_RX_BUF_REQUEST:
+	case UART_RX_BUF_RELEASED:
+	case UART_RX_DISABLED:
+		/* Do nothing */
+		break;
+	}
```
[the remark this answers is not in the document]
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/modbus_serial.c [hunk 9]
```diff
@@ -592,11 +657,20 @@ int modbus_serial_init(struct modbus_context *ctx,
 	cfg->uart_buf_ctr = 0;
 	cfg->uart_buf_ptr = &cfg->uart_buf[0];
 
-	uart_irq_callback_user_data_set(cfg->dev, uart_cb_handler, ctx);
-	k_timer_init(&cfg->rtu_timer, rtu_tmr_handler, NULL);
-	k_timer_user_data_set(&cfg->rtu_timer, ctx);
+	if (IS_ENABLED(CONFIG_MODBUS_SERIAL_ASYNC_API)) {
+		int err = uart_callback_set(cfg->dev, uart_cb_async_handler, ctx);
```
[the remark this answers is not in the document]
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/modbus_serial.c [hunk 10]
```diff
@@ -592,11 +657,20 @@ int modbus_serial_init(struct modbus_context *ctx,
...
+
+		if (err != 0) {
+			LOG_ERR("uart_callback_set returns error = %d", err);
+		}
```
[the remark this answers is not in the document]
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/modbus_serial.c (hunk 2 above)
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/modbus_serial.c (hunk 3 above)
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Done

File: subsys/modbus/Kconfig [hunk 11]
```diff
@@ -48,6 +48,12 @@ config MODBUS_SERIAL
 	help
 	  Enable Modbus over serial line support.
 
+config MODBUS_SERIAL_ASYNC_API
+	depends on MODBUS_SERIAL && UART_ASYNC_API
+	bool "Modbus over serial line with async api support"
```
Comment (jfischer-no) [inline subsys/modbus/Kconfig]: bool "Modbus over serial line UART ASYNC API support"

File: subsys/modbus/Kconfig [hunk 12]
```diff
@@ -48,6 +48,12 @@ config MODBUS_SERIAL
...
+	help
+	  Enable Modbus Serial to use Async API.
```
Comment (jfischer-no) [inline subsys/modbus/Kconfig]: Maybe "Use UART ASYNC API for Modbus over serial line"?

File: subsys/modbus/modbus_serial.c [hunk 13]
```diff
@@ -37,14 +37,26 @@ static void modbus_serial_tx_on(struct modbus_context *ctx)
...
 }
 
 static void modbus_serial_tx_off(struct modbus_context *ctx)
 {
 	struct modbus_serial_config *cfg = ctx->cfg;
 
-	uart_irq_tx_disable(cfg->dev);
+	if (!IS_ENABLED(CONFIG_MODBUS_SERIAL_ASYNC_API)) {
+		uart_irq_tx_disable(cfg->dev);
+	}
```
Comment (jfischer-no) [inline subsys/modbus/modbus_serial.c:58]: Should be ASYNC TX explizitly aborted here (`uart_tx_abort()`)?

File: subsys/modbus/modbus_serial.c [hunk 14]
```diff
@@ -70,14 +82,30 @@ static void modbus_serial_rx_on(struct modbus_context *ctx)
 	}
 
 	atomic_set_bit(&ctx->state, MODBUS_STATE_RX_ENABLED);
-	uart_irq_rx_enable(cfg->dev);
+	if (IS_ENABLED(CONFIG_MODBUS_SERIAL_ASYNC_API)) {
+		int err;
+
+		memset(cfg->uart_buf, 0, sizeof(cfg->uart_buf));
```
Comment (jfischer-no) [inline subsys/modbus/modbus_serial.c]: Why is there memset()?

File: subsys/modbus/modbus_serial.c [hunk 15]
```diff
@@ -424,6 +452,40 @@ static void uart_cb_handler(const struct device *dev, void *app_data)
...
+		break;
+	case UART_RX_RDY:
+		cfg->uart_buf_ctr = evt->data.rx.len;
+		k_work_submit(&ctx->server_work);
+		break;
+	case UART_TX_ABORTED:
+	case UART_RX_STOPPED:
+	case UART_RX_BUF_REQUEST:
+	case UART_RX_BUF_RELEASED:
+	case UART_RX_DISABLED:
```
Comment (jfischer-no) [inline subsys/modbus/modbus_serial.c]:
```c
	case UART_TX_ABORTED:
		__fallthrough;
	case UART_RX_STOPPED:
		__fallthrough;
	case UART_RX_BUF_REQUEST:
		__fallthrough;
	case UART_RX_BUF_RELEASED:
		__fallthrough;
	case UART_RX_DISABLED:
```

File: subsys/modbus/Kconfig
Comment (jfischer-no) [inline subsys/modbus/Kconfig:1]: I think your commit message could be improved slightly. How about this?

```
modbus: support UART ASYNC API in modbus serial

Reason for this extension are CRC mismatches happening due to RX data
loss when using the interrupt driven API at higher speeds and/or high
CPU load. It is recommended to use the ASYNC API along with hardware
byte counting requiring a timer instance and one PPI channel to achieve
a robust communication at high baudrates on nRF platforms.
```

File: subsys/modbus/modbus_serial.c (hunk 14 above)
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c:88]: I think you're right, there is no need for it. I just tend to clean up buffers used before by tx. 
However, this should not be needed -> removed.

Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: I think you're right, there is no need for it. I just tend to clean up buffers used before by tx. 
However, this should not be needed -> removed.

File: subsys/modbus/modbus_serial.c (hunk 13 above)
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c:58]: I think not, However that's what I would expect the function to do when I read its name.

File: subsys/modbus/Kconfig (hunk 12 above)
Comment (lanwer50) [reply subsys/modbus/Kconfig]: Changed

File: subsys/modbus/Kconfig (hunk 11 above)
Comment (lanwer50) [reply subsys/modbus/Kconfig]: Changed

File: subsys/modbus/modbus_serial.c (hunk 15 above)
Comment (lanwer50) [reply subsys/modbus/modbus_serial.c]: Edited

File: subsys/modbus/Kconfig
Comment (lanwer50) [reply subsys/modbus/Kconfig:1]: Done

**Comment by lanwer50** [comment]
> The ASYNC part is not tested, the default testing platform does not support ASYNC mode. I need to find some time to find out how to resolve it.

@jfischer-no: I think the easiest way to test it out will be to use two nrf52840 dk_boards with the default modbus samples, one as client and the second board as server. Then, add the new Kconfig MODBUS_SERIAL_ASYNC_API to the prf.conf of the sample.

**Review by jfischer-no — APPROVED** [review]
Thanks

**Review by bjarki-andreasen — APPROVED** [review]

**Comment by kartben** [comment]
@lanwer50 when you have a chance, please make sure to add `CONFIG_MODBUS_SERIAL_ASYNC_API` to doc/releases/release-notes-4.3.rst - Thanks!
