### PR TITLE
drivers: i2s: stm32 sai: fix f4 clock source

### LINKED ISSUE #102470: stm32: i2s_stm32_sai: incorrect pitch at 44.1kHz unless SAI ClockSource is configured
### Summary
On STM32F429 (SAI1 Block B) using the `i2s_stm32_sai` driver, audio played at 44.1kHz has incorrect pitch (sounds higher, like playing at ~48kHz family). 

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Configure SAI1 Block B for I2S playback as master.
2. Set `cfg.frame_clk_freq = 44100` and play a 44.1kHz MP3/WAV stream.
3. Listen to the output.

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- SoC/Board: STM32F429 (SAI1 Block B)
- Zephyr version: v4.3.0-3078-g23892b038f6a
- Driver: drivers/i2s/i2s_stm32_sai.c
- Codec: WM8978 (I2S slave), STM32 SAI is master
- Audio format: 16-bit stereo I2S

### Additional Context

my dts
	clocks {
		plli2s: plli2s {
			compatible = "st,stm32f4-plli2s-clock";
			#clock-cells = <0>;
			mul-n = <271>;
			div-r = <2>;
			status = "okay";
		};
	};

&i2c1 {
    pinctrl-0 = <&i2c1_scl_pb6 &i2c1_sda_pb9>;
    pinctrl-names = "default";
    status = "okay";
    clock-frequency = <I2C_BITRATE_FAST>;

    gt911: gt911@5d {
        compatible = "goodix,gt911";
        reg = <0x5d>;
        irq-gpios = <&gpioh 7 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>;
		alt-addr = <0x14>;
    };

	wm8978: codec@1a {
		compatible = "wolfson,wm8978";
		reg = <0x1a>;

		out2-btl;           
		spk-boost-1p5x;    

		default-input = "mic-l";
		default-output = "hp-spk";   
    };
};

&sai1_b {
    status = "okay";
    pinctrl-0 = <&sai1_fs_b_pf9
                 &sai1_sck_b_pf8
                 &sai1_mclk_b_pf7
                 &sai1_sd_b_pf6>;
    pinctrl-names = "default";
    mclk-enable;
    mclk-divider = "div-256";
    clocks = <&rcc STM32_CLOCK(APB2, 22)>,
             <&rcc STM32_SRC_PLLI2S_R SAI1B_SEL(1)>;
    dma-names = "tx";
    dmas = <&dma2 5 0 (STM32_DMA_MODE_NORMAL | STM32_DMA_PRIORITY_HIGH |
                       STM32_DMA_16BITS) 0>;
	sai-clock-source = "plli2s";
};

### PR DESCRIPTION
**Pull request by gautierg-st**
For STM32F4, the SAI HAL writes into the RCC DCKCFGR register to set the clock source. To ensure that is conforms with what is declared in the device tree, the ClockSource field in the Init structure need to be correctly configured before calling HAL_SAI_InitProtocol.

Fixes #102470

### CODE REVIEW

**Review by mathieuchopstm — DISMISSED** [review]

File: drivers/i2s/i2s_stm32_sai.c [hunk 1]
```diff
@@ -492,6 +492,48 @@ static int i2s_stm32_sai_configure(const struct device *dev, enum i2s_dir dir,
...
+		break;
+#else /* STM32F413xx || STM32F423xx */
+	case STM32_SRC_PLLSAI_POST_Q:
+		hsai->Init.ClockSource = SAI_CLKSOURCE_PLLSAI;
+		break;
+
+	case STM32_SRC_PLLI2S_POST_Q:
+		hsai->Init.ClockSource = SAI_CLKSOURCE_PLLI2S;
+		break;
+#endif /* STM32F413xx || STM32F423xx*/
```
Comment (mathieuchopstm) [inline drivers/i2s/i2s_stm32_sai.c]:
```suggestion
#endif /* STM32F413xx || STM32F423xx */
```

**Review by mathieuchopstm — COMMENTED** [review]
nanoscopic nit

File: drivers/i2s/i2s_stm32_sai.c [hunk 2]
```diff
@@ -492,6 +492,48 @@ static int i2s_stm32_sai_configure(const struct device *dev, enum i2s_dir dir,
 		stream->master = false;
 	}
 
+#if defined(CONFIG_SOC_SERIES_STM32F4X)
```
Comment (erwango) [inline drivers/i2s/i2s_stm32_sai.c]: To keep the driver as "clean" as possible, and because we've managed to clean all other clock "hacks" occurrences, can you move this to a dedicated function so it appears clearly that's an exceptional deviation from other clocks handling?

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/i2s/i2s_stm32_sai.c (hunk 2 above)
Comment (gautierg-st) [reply drivers/i2s/i2s_stm32_sai.c]: Done

**Review by mathieuchopstm — APPROVED** [review]

**Review by erwango — APPROVED** [review]
Thanks
