### PR TITLE
drivers: usb: udc_stm32: Handle HAL callbacks on separate thread 

### LINKED ISSUE #61464: USB device stack (new and old) assertion on STM32
**Describe the bug**
When using the new and old USB device stack ECM class on STM32H7 the assertion is raised due to mutex usage within ISR.

**To Reproduce**
1. build USB device with ECM class for STM32 MCU with enabled asserts (_`CONFIG_ASSERT=y`_)
3. run against linux

**Expected behavior**
~The existing stack doesn't have this issue. Assuming the new stack shall not fail as well.~
It should work fine with `CONFIG_ASSERT=y`.

**Impact**
The new stack stops working.

**Logs and console output**
The "mutexes cannot be used inside ISRs" assertion happens within `udc_stm32_lock` that is called from `HAL_PCD_SetupStageCallback`.

```
#0  arch_system_halt (reason=4) at <workspace>/zephyr/kernel/fatal.c:32
#1  0x90077762 in k_sys_fatal_error_handler (reason=4, esf=0x240203a8 <z_interrupt_stacks+3496>) at <workspace>/zephyr/kernel/fatal.c:46
#2  0x90077988 in z_fatal_error (reason=4, esf=0x240203a8 <z_interrupt_stacks+3496>) at <workspace>/zephyr/kernel/fatal.c:131
#3  0x9008c3cc in z_arm_fatal_error (reason=4, esf=0x240203a8 <z_interrupt_stacks+3496>) at <workspace>/zephyr/arch/arm/core/aarch32/fatal.c:73
#4  0x9008c3ec in z_do_kernel_oops (esf=0x240203a8 <z_interrupt_stacks+3496>, callee_regs=0x2) at <workspace>/zephyr/arch/arm/core/aarch32/fatal.c:118
#5  0x90013e76 in _oops () at <workspace>/zephyr/arch/arm/core/aarch32\swap_helper.S:573
#6  <signal handler called>
#7  assert_post_action (file=0x900e0aa0 "WEST_TOPDIR/zephyr/kernel/mutex.c", line=101) at <workspace>/zephyr/lib/os/assert.c:44
#8  0x9007988a in z_impl_k_mutex_lock (mutex=0x240009ec <udc0_data+132>, timeout=...) at <workspace>/zephyr/kernel/mutex.c:101
#9  0x90098624 in k_mutex_lock (mutex=0x240009ec <udc0_data+132>, timeout=...) at <workspace>/<app>/zephyr/include/generated/syscalls/kernel.h:984
#10 0x900986a6 in udc_lock_internal (dev=0x900cb0d8 <__device_dts_ord_88>, timeout=...) at <workspace>/zephyr/drivers/usb/udc/udc_common.h:257
#11 0x90098704 in udc_stm32_lock (dev=0x900cb0d8 <__device_dts_ord_88>) at <workspace>/zephyr/drivers/usb/udc/udc_stm32.c:60
#12 0x90031564 in udc_ep_buf_alloc (dev=0x900cb0d8 <__device_dts_ord_88>, ep=0 '\000', size=8) at <workspace>/zephyr/drivers/usb/udc/udc_common.c:622
#13 0x90097ed8 in udc_ctrl_alloc (dev=0x900cb0d8 <__device_dts_ord_88>, ep=0 '\000', size=8) at <workspace>/zephyr/drivers/usb/udc/udc_common.c:646
#14 0x900322da in HAL_PCD_SetupStageCallback (hpcd=0x24003fa4 <udc0_priv>) at <workspace>/zephyr/drivers/usb/udc/udc_stm32.c:149
#15 0x900719f6 in PCD_EP_OutSetupPacket_int (hpcd=0x24003fa4 <udc0_priv>, epnum=0) at <workspace>/modules/hal/stm32/stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_pcd.c:2327
#16 0x900c3076 in HAL_PCD_IRQHandler (hpcd=0x24003fa4 <udc0_priv>) at <workspace>/modules/hal/stm32/stm32cube/stm32h7xx/drivers/src/stm32h7xx_hal_pcd.c:1140
#17 0x900988fa in udc_stm32_irq (dev=0x900cb0d8 <__device_dts_ord_88>) at <workspace>/zephyr/drivers/usb/udc/udc_stm32.c:361
#18 0x90013fc6 in _isr_wrapper () at <workspace>/zephyr/arch/arm/core/aarch32\isr_wrapper.S:264
```

**Environment:**
 - OS: irrelevant
 - Toolchain: gcc-arm-none-eabi-10.3-2021.07
 - Zephyr : [d9fe26](https://github.com/zephyrproject-rtos/zephyr/commit/d9fe261f8eae2ca8b999a35852024ecf2ec3dc2a)

Ping @loicpoulain

### PR DESCRIPTION
**Pull request by topisani**
All HAL callback handling is offloaded to a separate thread.
Tested on STM32H747 (arduino portenta) with the high speed controller.

This is an attempt at fixing https://github.com/zephyrproject-rtos/zephyr/issues/61464.
Marked as a draft, as i would at least like to do some minor stylistic cleanup before submitting, but if anyone could help test, I would appreciate it. As far as i can tell, no additional locking should be required, and no timing invariants are broken, but I could use some extra eyes on that as well.

Fixes: #61464 (UDC STM32 part)

### CODE REVIEW

**Comment by erwango** [comment]
A huge thanks. We'll for sure help testing on extended sample of series.

**Comment by GeorgeCGV** [comment]
Is it safe to enqueue a stack-allocated msg pointer?

Perhaps the event approach is safer. Given that the combined number of IN and OUT endpoints is typically less than 32 (_15 IN + 15 OUT_), a `k_event` could be used to notify about IN, OUT, or SETUP.

Additionally, this approach helps prevent potential message queue overflows that might result in missed event/message handling and supports ordered processing.

**Comment by topisani** [comment]
> Is it safe to enqueue a stack-allocated msg pointer?

Yes, it is copied into the ringbuffer.

> Perhaps the event approach is safer. Given that the combined number of IN and OUT endpoints is typically less than 32 (_15 IN + 15 OUT_), a `k_event` could be used to notify about IN, OUT, or SETUP.

Isnt it technically up to 16+16 endpoints including the control endpoint?

> Additionally, this approach helps prevent potential message queue overflows that might result in missed event/message handling and supports ordered processing.

While I agree about the message queue overflows, I don't see how k_event would support ordered processing? Thats mostly why I chose the msgq based approach, to make sure the events were processed in the order they arrived

**Comment by topisani** [comment]
> Not in a fifo way, but In the processing. I.e. process `setup` before `in` (_process `x` before `y`_).

Ah, I dont think this is what we would want though. All of these callbacks are triggered from the same IRQ, i.e. have the same priority, and should be processed in the order they arrived. It should maybe be considered how the ordering interdependency with the `udc_submit_event` processing could impact things, but i think that requires a deeper knowledge of the STM32 USB stack than I have. I would personally be ok to leave this up to testing too.

@erwango I will rebase this, but then I believe it is ready for testing. Is there anything else I can do to help the testing effort along?

**Comment by erwango** [comment]
@topisani It's failing on `disco_l475_iot1`. Before:
```
*** Booting Zephyr OS build v4.0.0-405-g2efc8598e39f ***
[00:00:00.010,000] <inf> cdc_acm_echo: USB device support enabled
[00:00:00.010,000] <inf> cdc_acm_echo: Wait for DTR
[00:00:25.413,000] <inf> cdc_acm_echo: USBD message: Device suspended
[00:00:25.568,000] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:25.683,000] <inf> cdc_acm_echo: USBD message: Bus reset
[00:00:25.760,000] <inf> cdc_acm_echo: USBD message: New device configuration
[00:00:25.761,000] <err> udc_stm32: ep 0x00 queue is empty
[00:00:25.761,000] <inf> cdc_acm_echo: USBD message: CDC ACM line coding
[00:00:25.761,000] <inf> cdc_acm_echo: Baudrate 9600
```
After:
```
*** Booting Zephyr OS build v4.0.0-409-g84574a1c389f ***
[00:00:00.010,000] <err> usbd_init: Failed to assign endpoint addresses
[00:00:00.010,000] <err> usbd_init: Failed to init HS configuration 1
[00:00:00.010,000] <err> usbd_sample_config: Failed to initialize device support
[00:00:00.010,000] <err> cdc_acm_echo: Failed to initialize USB device
[00:00:00.010,000] <err> cdc_acm_echo: Failed to enable USB
```

**Comment by topisani** [comment]
@erwango Alright, i believe this is my attempt at detecting USB HS support that fails. I have an l432 board i can test on, if that is the case, it should fail there as well

**Comment by topisani** [comment]
I could reproduce the issue on a nucleo_l432kc, and it appears to have been the HS detection. It now follows the maximum-speed dts prop, like in most of the other udc drivers.

**Comment by topisani** [comment]
Alright, i did some testing using `samples/subsys/usb/cdc_acm -DCONF_FILE=usbd_next_prj.conf` on the various boards i could find.
test: open the cdc_acm terminal, and type characteres. The device should echo each character back.

`nucleo_u575zi_q`: PASS
`stm32f469i_disco`: PASS
`stm32f769i_disco`: FAIL

I have also done a test on an arduino_portenta_h7 based custom board, that also failed. The common factor is that both boards use HS USB.

Checking with `main`, these boards also fail, so I think the current state is just that udc_stm32 does not correctly implement usbotg_hs. I will look at a fix separately from this PR.

**Comment by fpistm** [comment]
Hi @topisani 

I've started to test on my side, here my result using `samples/subsys/usb/cdc_acm`  with `-DCONF_FILE=usbd_next_prj.conf` and sent a lorem ipsum buffer of 1024 bytes several times.
| series| boards | controller | cdc_acm sample | plug/unplug |
| --- | --- | --- | --- | --- |
| F4 | nucleo_f429zi | st,stm32-otgfs | :white_check_mark: | :white_check_mark: |
| F7 | stm32f746g_disco | st,stm32-otgfs | :white_check_mark: | :white_check_mark: |
| H7 | nucleo_h723zg | st,stm32-otgfs | :white_check_mark: | :white_check_mark: |
| L4 | b_l4s5i_iot01a | st,stm32-otgfs | :white_check_mark: | :white_check_mark: |

I will continue tests and report here.

File: drivers/usb/udc/udc_stm32.c [hunk 1]
```diff
@@ -912,6 +913,7 @@ static const struct udc_stm32_config udc0_cfg = {
 	.pma_offset = USB_BTABLE_SIZE,
 	.ep0_mps = EP0_MPS,
 	.ep_mps = EP_MPS,
+	.speed_idx = DT_ENUM_IDX(DT_DRV_INST(0), maximum_speed),
```
Comment (fpistm) [inline drivers/usb/udc/udc_stm32.c:916]: maximum_speed property is not available from all DT.
In old driver, property is check before access it:
https://github.com/zephyrproject-rtos/zephyr/blob/c0be51df2fb83f2e772d74b73e10350662af12b8/drivers/usb/device/usb_dc_stm32.c#L70-L72

Comment (erwango) [reply drivers/usb/udc/udc_stm32.c:916]:
```suggestion
	.speed_idx = DT_ENUM_IDX_OR(DT_DRV_INST(0), maximum_speed, low-speed),
```

File: drivers/usb/udc/udc_stm32.c [hunk 2]
```diff
@@ -260,6 +243,28 @@ void HAL_PCD_DataOutStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
 {
 	uint32_t rx_count = HAL_PCD_EP_GetRxCount(hpcd, epnum);
 	struct udc_stm32_data *priv = hpcd2data(hpcd);
+	struct udc_stm32_msg msg = {
```
Comment (topisani) [inline drivers/usb/udc/udc_stm32.c:246]: I caught an issue where this check would trigger `ZLP expected` (only appeared on usbotg_hs), as multiple messages arriving before being handled would be merged. Storing the rx length in the msgq fixed this. It doubles the size of the messages, but I dont see a way around it. The cdc_acm test still fails on usbotg_hs.
https://github.com/zephyrproject-rtos/zephyr/blob/c0be51df2fb83f2e772d74b73e10350662af12b8/drivers/usb/udc/udc_common.c#L1058-L1064

Comment (erwango) [reply drivers/usb/udc/udc_stm32.c:246]: Nice! I think this could potentially fix a couple of issues seen by @fpistm (particularly on Windows). He'll only be able to answer on monday though.

> The cdc_acm test still fails on usbotg_hs.

Which board are you using for this test ?

Comment (topisani) [reply drivers/usb/udc/udc_stm32.c:246]: > Which board are you using for this test ?
Mainly testing using stm32f769i_disco, but i see the same on a portenta_h7. I may be able to test the fs interface on the h7 to verify that it only happens on hs, but the portenta is mounted in a custom board where its a bit more difficult to perform isolated tests.
Just to clarify: when running the cdc_acm sample, descriptors are exchanged without issue, but no characters are echoed back. I am currently doing some debugging with wireshark, i will report a separate issue once i have more context.

Comment (marwaiehm-st) [reply drivers/usb/udc/udc_stm32.c:246]: @topisani 
I experienced the same problem of characters not being echoed back with the stm32h747i_disco board, but it ran smoothly on the nucleo_h743zi board, which means it only occurs on HS.

Comment (topisani) [reply drivers/usb/udc/udc_stm32.c:246]: i have now also confirmed that it works on the usbotg_fs interface on stm32f769i_disco. This issue with HS also exists on main.

**Comment by topisani** [comment]
I found the usbotg_hs issue - porting this fix to udc helped: https://github.com/zephyrproject-rtos/zephyr/pull/62530
Like the original related issues and PRs, i cannot find an explanation as to why 160 works as a minimum, so i kept the comment that it was chosen through trial and error.

**Comment by dsch** [comment]
Thank you @topisani for your great work!

Is it also required to push request to `udc_ep_enqueue()` on the message queue?

Similar as in NRF driver: https://github.com/zephyrproject-rtos/zephyr/blob/6dafb5f4a9cbd7043989f986d1f5963c264d413e/drivers/usb/udc/udc_nrf.c#L584-L604

File: drivers/usb/udc/Kconfig.stm32 [hunk 3]
```diff
@@ -6,6 +6,7 @@ config UDC_STM32
 	depends on DT_HAS_ST_STM32_OTGFS_ENABLED \
 		|| DT_HAS_ST_STM32_OTGHS_ENABLED \
 		|| DT_HAS_ST_STM32_USB_ENABLED
+	depends on !USB_DC_STM32
```
[the remark this answers is not in the document]
Comment (topisani) [reply drivers/usb/udc/Kconfig.stm32:9]: It's also a bit specific to this driver though - at least theoretically it should be possible with multi-instance compatible controllers to use one with the new api, and one with the old. But the two stm32 drivers specifically cannot coexist because of the Hal callback definitions.

**Comment by topisani** [comment]
> Is it also required to push request to `udc_ep_enqueue()` on the message queue?

I considered it, but as far as I can tell it should be ok. I will take another look

File: drivers/usb/udc/Kconfig.stm32 (hunk 3 above)
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/usb/udc/Kconfig.stm32:9]: ok, Thanks. Fine for me then

**Review by erwango — DISMISSED** [review]

File: drivers/usb/udc/udc_stm32.c [hunk 4]
```diff
@@ -515,9 +515,9 @@ static void udc_stm32_mem_init(const struct device *dev)
 	}
 
 	/* The documentation is not clear at all about RX FiFo size requirement,
-	 * Allocate a minimum of 0x40 words, which seems to work reliably.
+	 * 160 has been selected through trial and error.
 	 */
-	words = MAX(0x40, cfg->ep_mps / 4);
+	words = MAX(160, cfg->ep_mps / 4);
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_stm32.c:520]: >On USB HS, the previous lower limit of 64 is too small, the value
160 has been chosen apparently through trial and error.

At a minimum, this value should be selected based on the controller type and capabilities, not "trial and error".

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/udc/udc_stm32.c [hunk 5]
```diff
@@ -123,6 +135,24 @@ void HAL_PCD_ResumeCallback(PCD_HandleTypeDef *hpcd)
...
 
+void HAL_PCD_SetupStageCallback(PCD_HandleTypeDef *hpcd)
+{
+	struct udc_stm32_data *priv = hpcd2data(hpcd);
+	struct udc_stm32_msg msg = {.kind = UDC_STM32_MSG_SETUP};
+	int err = k_msgq_put(&priv->msgq_data, &msg, K_NO_WAIT);
+
+	if (err < 0) {
+		LOG_ERR("UDC Message queue overrun");
+	}
```
[the remark this answers is not in the document]
Comment (topisani) [reply drivers/usb/udc/udc_stm32.c:147]: The driver specifically needs to handle separate RX callbacks individually. I dont see a way to do this using events, as multiple callbacks for one endpoint can occur between the handler thread running. I assume this is the reason why the udc_nrf driver also does it this way.

File: drivers/usb/udc/udc_stm32.c (hunk 4 above)
Comment (topisani) [reply drivers/usb/udc/udc_stm32.c:520]: See the discussion here: https://github.com/zephyrproject-rtos/zephyr/pull/62530
I've been digging through documentation and related issues from when this change was introduced on the old usb device driver, and i cannot seem to find any reason. This configuration is what worked in the old driver, which has been used a lot in practice. But maybe someone at ST can help settle where this value comes from (@erwango)?

Comment (erwango) [reply drivers/usb/udc/udc_stm32.c:520]: Unfortunately @Desvauxm-st left the company. So I don't have more information other than what is available in the PR. @marwaiehm-st maybe ?

Comment (marwaiehm-st) [reply drivers/usb/udc/udc_stm32.c:520]: Unfortunately, we tried to find a satisfactory explanation other than "this value works", but until now, we haven't found an explanation for why the minimum value of FIFO RX needs to be 160.

**Comment by fpistm** [comment]
Hi,
here the result of all my tests using `samples/subsys/usb/cdc_acm`  with `-DCONF_FILE=usbd_next_prj.conf` and sent a lorem ipsum buffer of 1024 bytes several times.

`In any case it fixes the assert issue reported here: #61464.`

| series| boards | controller | cdc_acm sample | plug/unplug | comment |
| --- | --- | --- | --- | --- | --- |
| F2 | nucleo_f207zg | st,stm32-otgfs | :green_circle: | :green_circle: | |
| F4 | nucleo_f429zi | st,stm32-otgfs | :green_circle: | :green_circle: | |
| F7 | stm32f746g_disco | st,stm32-otgfs | :green_circle: | :green_circle: | |
| H7 | nucleo_h723zg | st,stm32-otghs | :green_circle: | :green_circle: | |
| L4 | b_l4s5i_iot01a | st,stm32-otgfs | :green_circle: | :green_circle: | |
| U5 | nucleo_u575zi_q | st,stm32-otgfs | :green_circle: | :green_circle: | |
| F3 | nucleo_f303re (1)| st,stm32-usb | :orange_circle: | :red_circle: | [dts updated](#dts-updated). See [here](#nucleo_f303re) |
| G4 | nucleo_g431rb (1)| st,stm32-usb | :orange_circle: | :red_circle: | [dts updated](#dts-updated). Same status than [nucleo_f303re](#nucleo_f303re) except no patch needed to get a fixed baudrate value (115200) |
| H5 | nucleo_h563zi | st,stm32-usb | :orange_circle: using [patch](#workaround-1) | :red_circle: | Bus fault #76250. Fixed baudrate value reported (115200) using [patch](#workaround-1) |
| WB | nucleo_wb55rg | st,stm32-usb | :orange_circle: | :red_circle: | Same status than [nucleo_f303re](#nucleo_f303re). |

> [!NOTE]
> 1. shield used to add USB connector

##### Workaround 1
  * #76250 `subsys/usb/device_next/class/usbd_cdc_acm.c`
```patch
@@ -458,11 +458,14 @@ static int usbd_cdc_acm_ctd(struct usbd_class_data *const c_data,
 		if (setup->wLength != len) {
 			errno = -ENOTSUP;
 			return 0;
 		}

-		memcpy(&data->line_coding, buf->data, len);
+		if (buf->data) {
+			printk("SET_LINE_CODING buf->data not null\n");
+			memcpy(&data->line_coding, buf->data, len);
+		}
 		cdc_acm_update_uart_cfg(data);
 		usbd_msg_pub_device(uds_ctx, USBD_MSG_CDC_ACM_LINE_CODING, dev);
 		return 0;

 	case SET_CONTROL_LINE_STATE:
  ```

##### dts updated
```patch
+
+zephyr_udc0: &usb {
+	pinctrl-0 = <&usb_dm_pa11 &usb_dp_pa12>;
+	pinctrl-names = "default";
+	status = "okay";
+};
```

##### nucleo_f303re
 * Wrong Baudrate value reported: `<inf> cdc_acm_echo: Baudrate 536885760`.
 * With [patch](#workaround-1) value is fixed (115200).
   Seems same issue than #76250, no crash because the `buf->data` has a value but not a correct one.
   Old stack also report a fixed baudrate.
 * [Assertion](#assert-enabled) if `CONFIG_ASSERT=y`
 * [Plug/unplug](#plugunplug) issue


##### Assert enabled

<details>
  <summary>log</summary>

```log
*** Booting Zephyr OS build v4.0.0-1636-gddeb51a89cfd ***
[00:00:00.001,000] <err> usbd_core: Failed to set default address after bus reset:
[00:00:00.001,000] <inf> cdc_acm_echo: USBD message: Bus reset:
[00:00:00.001,000] <inf> cdc_acm_echo: USBD message: Stack error:
[00:00:00.001,000] <inf> cdc_acm_echo: USB device support enabled:
[00:00:00.001,000] <inf> cdc_acm_echo: Wait for DTR:
[00:00:00.004,000] <inf> cdc_acm_echo: USBD message: Device suspended:
[00:00:00.112,000] <inf> cdc_acm_echo: USBD message: Device resumed:
[00:00:00.167,000] <inf> cdc_acm_echo: USBD message: Bus reset:
[00:00:00.281,000] <inf> cdc_acm_echo: USBD message: Bus reset:
[00:00:00.362,000] <inf> cdc_acm_echo: USBD message: New device configuration:
ASSERTION FAIL [net_buf_simple_tailroom(buf) >= len] @ WEST_TOPDIR/zephyr/lib/net_buf/buf_simple.c:62
[00:00:00.363,000] <err> os: r0/a1:  0x00000004  r1/a2:  0x0000003e  r2/a3:  0x00000005:
[00:00:00.363,000] <err> os: r3/a4:  0x00000004 r12/ip:  0x20003160 r14/lr:  0x08003b5d:
[00:00:00.363,000] <err> os:  xpsr:  0x01000000:
[00:00:00.363,000] <err> os: Faulting instruction address (r15/pc): 0x0800d228:
[00:00:00.363,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0:
[00:00:00.363,000] <err> os: Current thread: 0x20000f60 (unknown):
[00:00:00.444,000] <err> os: Halting system:
```
</details>

#### Plug/unplug
> [!IMPORTANT]
> On linux, second plug produce this issue (re-enumeration):
> On Windows, first plug (enumeration), means CDC port never created.

<details>
  <summary>log</summary>

```log
[00:00:07.187,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.187,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.187,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.188,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.188,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.188,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.188,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.188,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.188,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.188,000] <err> udc: Failed to allocate net_buf 255
[00:00:07.188,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.188,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.188,000] <err> udc: Failed to allocate net_buf 255
[00:00:07.188,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.188,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.189,000] <err> udc: Failed to allocate net_buf 255
[00:00:07.189,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.189,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.189,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.189,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.189,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.189,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.189,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.189,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.190,000] <err> udc: Failed to allocate net_buf 2
[00:00:07.190,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.190,000] <err> usbd_ch9: Malformed setup packet
[00:00:07.193,000] <err> udc: Failed to allocate net_buf 0
[00:00:07.193,000] <err> usbd_ch9: Buffer for data|status is missing
[00:00:07.193,000] <err> usbd_ch9: Malformed setup packet
```

</details>

**Comment by erwango** [comment]
> here the result of all my tests using samples/subsys/usb/cdc_acm with -DCONF_FILE=usbd_next_prj.conf and sent a lorem ipsum buffer of 1024 bytes several times.

Thanks @fpistm. Hence to summarize, this PR actually fixes https://github.com/zephyrproject-rtos/zephyr/issues/61464, but some issues remain, likely all linked/close to #76250.

For clarity, I'll open a new issue to gather all this.

File: drivers/usb/udc/Kconfig.stm32 (hunk 3 above)
[the remark this answers is not in the document]
Comment (topisani) [reply drivers/usb/udc/Kconfig.stm32:9]: ok - would you recomend removing this check all together, or moving it into an #ifdef in the driver?

**Comment by topisani** [comment]
Addressed most review comments from @jfischer-no. For the remaining ones, I still need some clarification on how to proceed.

**Review by erwango — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Comment by erwango** [comment]
@jfischer-no PTAL

File: drivers/usb/udc/udc_stm32.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c]: No, nRF USBD driver does it this way because it was introduced before @tmon-nordic  figured out a better way to handle it in DWC2 driver.

File: drivers/usb/udc/udc_stm32.c [hunk 6]
```diff
@@ -259,6 +239,28 @@ void HAL_PCD_DataOutStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
...
+}
+
+void HAL_PCD_DataInStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
+{
+	struct udc_stm32_data *priv = hpcd2data(hpcd);
+	struct udc_stm32_msg msg = {.kind = UDC_STM32_MSG_DATA_IN, .ep = epnum};
+	int err = k_msgq_put(&priv->msgq_data, &msg, K_NO_WAIT);
+
+	if (err < 0) {
```
[the remark this answers is not in the document]
Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c:262]: Not addressed.

File: drivers/usb/udc/udc_stm32.c (hunk 4 above)
Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c:530]: I am okay with this value. But, "Calculating FIFO Size" is described in DWC2 Programming Guide, you should have access to this documentation internally. IIRC the FIFO calculation for the one other type is much simpler. Instead of continuing "trial and error" with this driver, STM32 controller should start using DWC2 controller and clean up this driver to be used with non-DWC2 type controller.

File: drivers/usb/udc/Kconfig.stm32 [hunk 7]
```diff
@@ -13,3 +13,25 @@ config UDC_STM32
...
+	default 8
+	help
+	  STM32 USB device controller driver thread priority.
+
+config UDC_STM32_MAX_QMESSAGES
+	int "STM32 UDC driver maximum number of ISR event messages"
+	range 4 64
+	default 8
+	help
+	  Maximum number of messages for handling of STM32 USBD ISR events.
```
Comment (jfischer-no) [inline drivers/usb/udc/Kconfig.stm32:37]: This pollutes the list.

Comment (jfischer-no) [inline drivers/usb/udc/Kconfig.stm32:37]: That should be

```Kconfig
	  STM32 USB device controller driver.

if UDC_STM32

config UDC_STM32_STACK_SIZE
	int "UDC controller driver internal thread stack size"
	default 512
	help
	  STM32 USB device controller driver internal thread stack size.

config UDC_STM32_THREAD_PRIORITY
	int "STM32 USB controller driver thread priority"
	default 8
	help
	  STM32 USB device controller driver thread priority.

config UDC_STM32_MAX_QMESSAGES
	int "STM32 UDC driver maximum number of ISR event messages"
	range 4 64
	default 8
	help
	  Maximum number of messages for handling of STM32 USBD ISR events.

endif
```

btw, this is quite trivial and easy to spot.

File: drivers/usb/udc/udc_stm32.c [hunk 8]
```diff
@@ -143,59 +175,7 @@ static int usbd_ctrl_feed_dout(const struct device *dev, const size_t length)
...
-void HAL_PCD_SOFCallback(PCD_HandleTypeDef *hpcd)
-{
-	struct udc_stm32_data *priv = hpcd2data(hpcd);
-
-	udc_submit_event(priv->dev, UDC_EVT_SOF, 0);
-}
-
-static int udc_stm32_tx(const struct device *dev, uint8_t ep,
-			struct net_buf *buf)
+static int udc_stm32_tx(const struct device *dev, uint8_t ep, struct net_buf *buf)
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_stm32.c:179]: Stray change.

File: drivers/usb/udc/udc_stm32.c [hunk 9]
```diff
@@ -263,6 +243,28 @@ void HAL_PCD_DataOutStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
 {
 	uint32_t rx_count = HAL_PCD_EP_GetRxCount(hpcd, epnum);
 	struct udc_stm32_data *priv = hpcd2data(hpcd);
+	struct udc_stm32_msg msg = {
+		.type = UDC_STM32_MSG_DATA_OUT, .ep = epnum, .rx_count = rx_count};
+	int err = k_msgq_put(&priv->msgq_data, &msg, K_NO_WAIT);
+
+	if (err < 0) {
+		LOG_ERR("UDC Message queue overrun");
+	}
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_stm32.c:253]: Use the usual style, use the usual style in UDC drivers, keep the style in this file. Do not hide the calls (they are not helpers like udc_get_private()). Do not introduce undefined behavior. Fix it everywhere.
```c
	struct udc_stm32_msg msg = {
		.type = UDC_STM32_MSG_DATA_OUT,
		.ep = epnum,
		.rx_count = rx_count,
	};
	int err;

	err = k_msgq_put(&priv->msgq_data, &msg, K_NO_WAIT);
	if (err != 0) {
		LOG_ERR("UDC Message queue overrun");
	}
```

File: drivers/usb/udc/udc_stm32.c (hunk 4 above)
Comment (topisani) [reply drivers/usb/udc/udc_stm32.c:530]: > STM32 controller should start using DWC2 controller and clean up this driver to be used with non-DWC2 type controller.

Is this a discussion we can track in a separate issue? Some consideration was made years ago (https://github.com/zephyrproject-rtos/zephyr/issues/4412), but it seems like an area where a decision should be made, and this PR seems like the wrong place to have that discussion.

File: drivers/usb/udc/udc_stm32.c [hunk 10]
```diff
@@ -263,6 +243,28 @@ void HAL_PCD_DataOutStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
...
+	struct udc_stm32_data *priv = hpcd2data(hpcd);
+	struct udc_stm32_msg msg = {.type = UDC_STM32_MSG_DATA_IN, .ep = epnum};
+	int err = k_msgq_put(&priv->msgq_data, &msg, K_NO_WAIT);
+
+	if (err < 0) {
+		LOG_ERR("UDC Message queue overrun");
+	}
+}
+
+static void priv_handle_msg_data_out(struct udc_stm32_data *priv, uint8_t epnum, uint16_t rx_count)
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_stm32.c:267]: What does `priv_` mean? It is static, it does not make it more private if it is prefixed with `priv_`. It is just confusing, please remove it.

**Comment by erwango** [comment]
@topisani Please rebase.

File: drivers/usb/udc/udc_stm32.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (topisani) [reply drivers/usb/udc/udc_stm32.c]: I can take a look at reimplementing it with that approach, if it is considered a blocker to getting this bug fixed. That means the development and testing effort already put into this issue have to be redone. Personally, I would prefer to get this bug fixed with an approach that is clearly acceptible, as it is still being used in udc_nrf, and also in a driver that in your opinion should be heavily reworked anyway.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/udc/udc_stm32.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c]: You do not need to change it here, but it is my duty to point out a possible better solution.

File: drivers/usb/udc/udc_stm32.c (hunk 4 above)
Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c:530]: No, this is the right place to make a comment about it and it is related to FIFO size calculation.

File: drivers/usb/udc/udc_stm32.c [hunk 11]
```diff
@@ -275,6 +256,33 @@ void HAL_PCD_DataOutStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
...
+	if (err != 0) {
+		LOG_ERR("UDC Message queue overrun");
+	}
+}
+
+void HAL_PCD_DataInStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
+{
+	struct udc_stm32_data *priv = hpcd2data(hpcd);
+	struct udc_stm32_msg msg = {.type = UDC_STM32_MSG_DATA_IN, .ep = epnum};
+	int err;
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_stm32.c:277]: Still not fixed
```c
	struct udc_stm32_msg msg = {
		.type = UDC_STM32_MSG_DATA_IN,
		.ep = epnum
	};
	int err;
```

**Review by jfischer-no — APPROVED** [review]

**Review by tmon-nordic — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Comment by ddavidebor** [comment]
A big thank you for this PR!
