### PR TITLE
Bluetooth: Controller: Fix Tx ISO SDUs dropped due to strict SN check

### LINKED ISSUE #58325: LE Audio: controller: Failed to send to sink ASE
In some of BAP/UCL/STR PTS test cases the IUT has to configure 1 SINK ASE to streaming state and send packets with random data. While testing Zephyr Host + Zephyr Controller setup some issue appear and only a first packet is received by controller of the PTS dongle. More over the packet has a random sequence number. Bluetooth Protocol Viewer logs:
[zephyr_BAP_UCL_STR_BV_033_C.cfa.txt](https://github.com/zephyrproject-rtos/zephyr/files/11576281/zephyr_BAP_UCL_STR_BV_033_C.cfa.txt)

I repeated tests for Zephyr Host + Packetcraft Controller setup and this works fine:
[packetcraft_BAP_UCL_STR_BV_033_C.cfa.txt](https://github.com/zephyrproject-rtos/zephyr/files/11576271/packetcraft_BAP_UCL_STR_BV_033_C.cfa.txt)

### Zephyr Host + Zephyr Controller setup:

In samples/bluetooth/hci_rpmsg, create bttester_hci_rpmsg_overlay.conf file with:
`echo CONFIG_BT_CTLR_CONN_ISO_LOW_LATENCY_POLICY=y > bttester_hci_rpmsg_overlay.conf`
(related issue #57088)

Build the controller with:
`west build -b nrf5340dk_nrf5340_cpunet -- -DOVERLAY_CONFIG='nrf5340_cpunet_iso-bt_ll_sw_split.conf;bttester_hci_rpmsg_overlay.conf' `

Flash the controller with:
`west flash --recover`

In zephyr/test/bluetooth/tester build the tester app:
`west build -b nrf5340dk_nrf5340_cpuapp . -- -DOVERLAY_CONFIG='overlay-le-audio.conf`

Flash the app with:
`west flash`

### Zephyr Host + Packetcraft Controller setup:
Download the controller binary:
https://github.com/nrfconnect/sdk-nrf/blob/v2.3.0/applications/nrf5340_audio/bin/ble5-ctr-rpmsg_3330.hex

and flash with:
`nrfjprog --program *.hex --chiperase --coprocessor CP_NETWORK -r`

Download this overlay:
[packetcraft-overlay-le-audio.txt](https://github.com/zephyrproject-rtos/zephyr/files/11576221/packetcraft-overlay-le-audio.txt)

and in zephyr/test/bluetooth/tester build the tester app:
`west build -b nrf5340dk_nrf5340_cpuapp . -- -DOVERLAY_CONFIG='packetcraft-overlay-le-audio.txt`

Flash the app with:
`west flash`

### PR DESCRIPTION
**Pull request by cvinayak**
Introduce a Kconfig BT_CTLR_ISOAL_SN_STRICT to relax the Tx
ISO Data SDUs being dropped due to strict check of sequence
numbers in ISOAL, i.e. dropped when ISO Data SDUs are
delayed from upper layer with respect to the current
payload number in the ISO radio events.

Relax Tx ISO SDUs being dropped in unicast audio client and
server samples when using the Zephyr Bluetooth Low Energy
Controller, i.e. Tx ISO SDUs dropped due to delayed ISO data
send calls in upper layer with respect to payload number in
the current ISO radio events in the Controller.

Add Zephyr Bluetooth Low Energy Controller overlay config for
the unicast audio client and server samples.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by cvinayak** [comment]
@niag-Oticon Hope the new Kconfig is acceptable as a workaround for applications that is not able keep the timings and provide stale ISO data (sequence numbers)

File: subsys/bluetooth/controller/Kconfig.ll_sw_split [hunk 1]
```diff
@@ -377,6 +377,19 @@ config BT_CTLR_SCAN_ENABLE_STRICT
 	  Enforce returning HCI Error Command Disallowed on enabling/disabling
 	  already enabled/disabled scanning.
 
+config BT_CTLR_ISOAL_SN_STRICT
+	bool "Enforce Strict Tx ISO Data Sequence Number use"
```
Comment (Thalley) [inline subsys/bluetooth/controller/Kconfig.ll_sw_split:381]:
```suggestion
config BT_CTLR_ISOAL_PSN_STRICT
	bool "Enforce Strict Tx ISO Data Packet Sequence Number use"
```

File: subsys/bluetooth/controller/Kconfig.ll_sw_split [hunk 2]
```diff
@@ -377,6 +377,19 @@ config BT_CTLR_SCAN_ENABLE_STRICT
...
+	depends on BT_CTLR_ADV_ISO || BT_CTLR_CONN_ISO
+	default y
+	help
+	  Enforce dropping stale Tx ISO Data SDUs from upper layer by checking
+	  the next expected Sequence Number maintained in ISOAL.
+
+	  This option may be used to relax the Tx ISO Data SDUs being dropped
+	  due to strict check of sequence numbers in ISOAL, i.e. dropped when
+	  ISO Data SDUs are delayed from upper layer with respect to the current
+	  payload number in the ISO radio events.
```
Comment (Thalley) [inline subsys/bluetooth/controller/Kconfig.ll_sw_split:391]: Maybe it should be mentioned that this only applies for ISO over HCI?

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:381]: Hmm, I see that the controller actually uses `sn` multiple places for this value, so perhaps we should just keep it as `SN`/`Sequence Number` rather than the full name of the field (Packet Sequence Number).

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split]: Done

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:381]: Keeping "sequence number" phrase as ISOAL specification uses this phrase (and does not use "packet sequence number"). `Packet_Sequence_Number` is only mentioned in the context of HCI ISO Data packets.

Comment (Thalley) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:381]: Correct, but the sequence number in ISOAL is the 1-bit value that is either 0 or 1, right? 

This Kconfig only applies to the packet sequence number that the host provides when sending over HCI, right? 

I am OK with using use sequence number

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:381]: > but the sequence number in ISOAL is the 1-bit value that is either 0 or 1, right?

This is a bit confusing in Spec, in ISOAL SDU sequence number is 16-bit to match the value `Packet_Sequence_Number` in HCI ISO Data packet. The other `SN` and `NESN` these are in the PDU header.

```
The sequence number shall be incremented for each SDU_Interval, whether or
not an SDU was received from the upper layer or included in reports sent to the
upper layer.
```

The Spec uses the term `upper layer`, hence is open to having other interfaces (not just HCI as the interface) for sending/receiving Tx ISO Data packets.

**Review by niag-Oticon — COMMENTED** [review]
Changes appear alright as long as the impact is understood.

File: subsys/bluetooth/controller/Kconfig.ll_sw_split (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/controller/Kconfig.ll_sw_split:381]: Okay so "sequence number" in ISOAL refer to any sequence number from upper layers (does that include vendor specific data paths?), and "packet sequence number" is only used for HCI. 

I'd argue that if this check is only for HCI ISO data packets, then it makes sense to use the term "packet sequence number", but if it is for any upper layer, then stick with "sequence number".

**Review by niag-Oticon — CHANGES_REQUESTED** [review]
Changes appear alright as long as the impact is understood.
I have some concerns that the current description does not fully capture the impact.
Also this should not be disabled for any qualification.

**Review by niag-Oticon — DISMISSED** [review]
Changes appear alright as long as the impact is understood.
This should not be disabled for any qualification.

File: samples/bluetooth/unicast_audio_client/src/main.c [hunk 3]
```diff
@@ -58,11 +58,23 @@ static K_SEM_DEFINE(sem_stream_qos, 0, ARRAY_SIZE(sinks) + ARRAY_SIZE(sources));
...
 		if (stream->ep == sinks[i].ep) {
-			return sinks[i].seq_num++;
+			seq_num = sinks[i].seq_num;
+
+#if defined(CONFIG_LIBLC3)
+			sinks[i].seq_num++;
+#else
+			sinks[i].seq_num += (AUDIO_DATA_TIMEOUT_US /
+					     codec_configuration.qos.interval);
+#endif
```
Comment (Thalley) [inline samples/bluetooth/unicast_audio_client/src/main.c:76]:
```suggestion
			if (IS_ENABLED(CONFIG_LIBLC3)) {
				sinks[i].seq_num++;
			} else {
				sinks[i].seq_num += (AUDIO_DATA_TIMEOUT_US /
						     codec_configuration.qos.interval);	
			}
```

**Comment by MariuszSkamra** [comment]
@cvinayak Why does the controller actually check the SeqNum and drop the packets instead of just sending it? Controller and Host are running in different clock domains, and there's always a drift.
So the controller cannot rely the SeqNum. I think that if there is packet on time, it shall be sent, if not ISO Null PDU shall be sent.

File: samples/bluetooth/unicast_audio_server/src/main.c [hunk 4]
```diff
@@ -69,11 +69,24 @@ static const struct bt_data ad[] = {
...
 		if (stream == &source_streams[i].stream) {
-			return source_streams[i].seq_num++;
+			seq_num = source_streams[i].seq_num;
+
+#if defined(CONFIG_LIBLC3)
+			source_streams[i].seq_num++;
+#else
+			source_streams[i].seq_num += (AUDIO_DATA_TIMEOUT_US /
+						      SDU_INTERVAL_US);
+#endif
```
Comment (Thalley) [inline samples/bluetooth/unicast_audio_server/src/main.c:88]:
```suggestion
			if (IS_ENABLED(CONFIG_LIBLC3)) {
				sinks[i].seq_num++;
			} else {
				sinks[i].seq_num += (AUDIO_DATA_TIMEOUT_US /
						     codec_configuration.qos.interval);	
			}
```

Comment (Thalley) [reply samples/bluetooth/unicast_audio_server/src/main.c:88]: Alternatively you can also do
```suggestion
			if (IS_ENABLED(CONFIG_LIBLC3)) {
				return sinks[i].seq_num++;
			} else {
				return sinks[i].seq_num += (AUDIO_DATA_TIMEOUT_US /
							    codec_configuration.qos.interval);	
			}
```

And remove the local variable again

File: samples/bluetooth/unicast_audio_server/src/main.c [hunk 5]
```diff
@@ -69,11 +69,24 @@ static const struct bt_data ad[] = {
 	BT_DATA(BT_DATA_SVC_DATA16, unicast_server_addata, ARRAY_SIZE(unicast_server_addata)),
 };
 
+#define AUDIO_DATA_TIMEOUT_US 1000000UL /* Send data every 1 second */
+#define SDU_INTERVAL_US       10000UL   /* 10 ms SDU interval */
+
 static uint16_t get_and_incr_seq_num(const struct bt_bap_stream *stream)
 {
+	uint16_t seq_num;
```
Comment (Thalley) [inline samples/bluetooth/unicast_audio_server/src/main.c:77]: See comment below, but in any case this can be move to the inner scope where it is used and returned

File: samples/bluetooth/unicast_audio_server/src/main.c [hunk 6]
```diff
@@ -214,7 +227,11 @@ static void audio_timer_timeout(struct k_work *work)
 		}
 	}
 
-	k_work_schedule(&audio_send_work, K_MSEC(1000U));
+#if defined(CONFIG_LIBLC3)
+	k_work_schedule(&audio_send_work, K_USEC(MAX_FRAME_DURATION_US));
+#else
+	k_work_schedule(&audio_send_work, K_USEC(AUDIO_DATA_TIMEOUT_US));
+#endif
```
Comment (Thalley) [inline samples/bluetooth/unicast_audio_server/src/main.c:234]: Ditto with using `IS_ENABLED`. 

If we want to do this correctly, we should use the `bt_codec_qos.interval` from the `lc3_qos` callback as the interval here. 

We already store the `max_sdu` size, so should be easy to store the interval as well

**Review by Thalley — CHANGES_REQUESTED** [review]

**Comment by cvinayak** [comment]
> @cvinayak Why does the controller actually check the SeqNum and drop the packets instead of just sending it? If controller and Host are running in different clock domains, and there's always a drift. So the controller cannot rely the SeqNum. I think that if there is packet on time, it shall be sent, if not ISO Null PDU shall be sent.

If the SDUs are not dropped, as @niag-Oticon mentions "creating skews in the received stream of SDUs" 

In the Spec:
```
The sequence number shall be incremented for each SDU_Interval, whether or
not an SDU was received from the upper layer or included in reports sent to the
upper layer.

The sequence number shall be 16 bits and shall be included in the
Packet_Sequence_Number parameter in HCI ISO Data Packets
```

Also, if the implement is known to drift then framed PDUs have to be used.

```
Framed PDUs shall be used when the requirements for using unframed PDUs
are not met. Framed PDUs support the aggregation of data from multiple SDUs
into a single PDU. The maximum allowed drift (MaxDrift) on the average timing
of SDU delivery shall not exceed 100 ppm from the configured value of
SDU_Interval.
```

File: samples/bluetooth/unicast_audio_client/src/main.c (hunk 3 above)
Comment (cvinayak) [reply samples/bluetooth/unicast_audio_client/src/main.c]: Done

File: samples/bluetooth/unicast_audio_server/src/main.c (hunk 5 above)
Comment (cvinayak) [reply samples/bluetooth/unicast_audio_server/src/main.c]: Done

File: samples/bluetooth/unicast_audio_server/src/main.c (hunk 4 above)
Comment (cvinayak) [reply samples/bluetooth/unicast_audio_server/src/main.c]: Updated.

File: samples/bluetooth/unicast_audio_server/src/main.c (hunk 6 above)
Comment (cvinayak) [reply samples/bluetooth/unicast_audio_server/src/main.c:235]: I am not familiar with the implementation of codec, if you provide suggested code I can include it in this PR. Or you are welcome to send a follow up PR.

No change done, as `MAX_FRAME_DURATION_US` is currently conditionally compiled hence not able to use `IS_ENABLED`

**Review by Thalley — DISMISSED** [review]

**Comment by cvinayak** [comment]
@Thalley rebased on resolve conflict, request your re-approval.

**Review by Thalley — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
