### PR TITLE
usb: device_next: uvc: fix ordering of frame interval

### LINKED ISSUE #101259: UVC sample failed on Windows
### Describe the bug

I run the uvc sample `samples/subsys/usb/uvc` and test failed on Windows.

Zephyr hash: e02a1b742ae
Build command:
```
west -v build \
-b numaker_pfm_m467 \
--snippet video-sw-generator \
zephyr/samples/subsys/usb/uvc
```

Per my check, I find two points which cause my failure.
First, `uvc_compare_frmival_desc` cannot handle the case like `ia=0x28b0a, ib=0xff676980`
 https://github.com/zephyrproject-rtos/zephyr/blob/235aa1aa7f7cff394fbbb217ff1eb924e228ff09/subsys/usb/device_next/class/usbd_uvc.c#L1499
Where the large `ib` comes from:
https://github.com/zephyrproject-rtos/zephyr/blob/235aa1aa7f7cff394fbbb217ff1eb924e228ff09/drivers/video/video_sw_generator.c#L435

Maybe this code can change to like:
```
return (ia > ib) ? 1 : (ia < ib) ? -1 : 0;
```

Second, there is description dependency conflict between `init_configuration_inst` and `usbd_class_init`:
  https://github.com/zephyrproject-rtos/zephyr/blob/235aa1aa7f7cff394fbbb217ff1eb924e228ff09/subsys/usb/device_next/usbd_init.c#L218-L229

`init_configuration_inst` relies on description being ready and does adjustment, for example, re-assign endpoint address. But for uvc, description is not yet ready until:
 https://github.com/zephyrproject-rtos/zephyr/blob/235aa1aa7f7cff394fbbb217ff1eb924e228ff09/subsys/usb/device_next/class/usbd_uvc.c#L1725-L1742

After fixing above two issue, I can run the uvc sample on Windows.

### Regression

- [ ] This is a regression.

### Steps to reproduce

N/A

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by josuah**
Fix the qsort comparison function that was hitting an integer underflow.

Some video sources such as `video-sw-generator` have `UINT32_MAX` for maximum frame interval (arbitrarily slow), which made the comparison underflow, which in turn lead to frame interval being listed in the wrong order, breaking Windows support.

Fixes #101259.

### CODE REVIEW

**Review by ccli8 — DISMISSED** [review]

**Review by tmon-nordic — DISMISSED** [review]

**Review by jfischer-no — DISMISSED** [review]

File: subsys/usb/device_next/class/usbd_uvc.c [hunk 1]
```diff
@@ -1496,7 +1496,13 @@ static int uvc_compare_frmival_desc(const void *const a, const void *const b)
...
 	memcpy(&ib, b, sizeof(uint32_t));
 
-	return ia - ib;
+	if (ia < ib) {
+		return -1;
+	}
+	if (ia > ib) {
+		return 1;
+	}
+	return 0;
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_uvc.c:1268]:
```c
	if (ia < ib) {
		return -1;
	}

	if (ia > ib) {
		return 1;
	}

	return 0;
```
?

**Review by tmon-nordic — DISMISSED** [review]

**Review by ccli8 — DISMISSED** [review]

File: subsys/usb/device_next/class/usbd_uvc.c (hunk 1 above)
Comment (josuah) [reply subsys/usb/device_next/class/usbd_uvc.c:1268]: Done, more readable version with extra newlines and rebased on `main`.

**Review by ccli8 — DISMISSED** [review]

**Review by jfischer-no — APPROVED** [review]

**Review by ccli8 — APPROVED** [review]
