### PR TITLE
xtensa: save/restore scompare1 during context switch

### LINKED ISSUE #21800: Xtensa doesn't save SCOMPARE1 register on context switch
Xtensa uses a somewhat odd two-instruction sequence for atomic operations.  You first write the SCOMPARE1 special register to the "old value" of the memory address, and then execute a S32C1I instruction to do a compare and swap with a new value if it hasn't changed.

I realized while thinking about the implications of #21771 that the SCOMPARE1 value is not saved by the context switch code.  This means that it's possible to take an interrupt between those two instructions, run some code that does more atomic stuff, and get the wrong value in the comparator register when the context is restored!

In practice, this doesn't actually break anything at the moment.  The only major user of atomic_cas() currently are in the spinlock code, which always uses a literal "0" for the old value.  (Also the sys_sem code uses it with arbitrary values, but that is a userspace abstraction we aren't AFAICT testing on xtensa currently).  So not a P1 bug, probably, but something we need to fix for sure. 

Context switch on xtensa needs to dump and restore SCOMPARE1.

### PR DESCRIPTION
**Pull request by dcpleung**
Xtensa uses two instructions to perform atomic compare-and-set
instruction: first the comparison register, then the actual
instruction to do compare-and-set. There is a potential that
context switching is performed before these two instructions.
A restored context may have the wrong value in the comparison
register. So we need to save and restore the comparison
register during context switching.

Fixes #21800

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

File: arch/xtensa/include/xtensa-asm2-context.h [hunk 1]
```diff
@@ -62,12 +64,25 @@
...
+#if XCHAL_HAVE_S32C1I
+#define BASE_SAVE_AREA_SIZE_SCOMPARE	4
+#else
+#define BASE_SAVE_AREA_SIZE_SCOMPARE	0
+#endif
+
+#define BASE_SAVE_AREA_SIZE \
+	(BASE_SAVE_AREA_SIZE_COMMON + \
+	 BASE_SAVE_AREA_SIZE_LOOPS + \
+	 BASE_SAVE_AREA_SIZE_SCOMPARE)
```
Comment (andyross) [inline arch/xtensa/include/xtensa-asm2-context.h]: Yeah, this is a better way to compute that size than a giant #if tree of configuraiton variants.

**Review by andyross — APPROVED** [review]
