### PR TITLE
kernel: sys_heap: Fix size_too_big() check

### LINKED ISSUE #90306: Heap allocation causes OS crash
**Describe the bug**

For a heap of size *n*, every `k_malloc` with size > *n* - 16 will result in an OS crash.
I could reproduce on both `qemu_x86` and `nrf52840dk/nrf52840` boards.

**To Reproduce**

Configure project with `CONFIG_HEAP_MEM_POOL_SIZE=2048` and in application call `k_malloc(2033)`.

**Expected behavior**

Even if there's not enough heap space for this allocation, the OS shouldn't crash.

**Impact**

**Logs and console output**

```
[00:00:00.306,854] <err> os: ***** BUS FAULT *****
[00:00:00.306,854] <err> os:   Precise data bus error
[00:00:00.306,884] <err> os:   BFAR Address: 0x2f9140b2
[00:00:00.306,915] <err> os: r0/a1:  0x20014080  r1/a2:  0x00000100  r2/a3:  0x00000008
[00:00:00.306,915] <err> os: r3/a4:  0x00000017 r12/ip:  0x0f900030 r14/lr:  0x00000003
[00:00:00.306,945] <err> os:  xpsr:  0x01000000
[00:00:00.306,945] <err> os: Faulting instruction address (r15/pc): 0x00009fc4
[00:00:00.306,976] <err> os: >>> ZEPHYR FATAL ERROR 25: Unknown error on CPU 0
[00:00:00.307,006] <err> os: Current thread: 0x20010748 (unknown)
[00:00:02.933,380] <err> os: Halting system
```
**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Version used: 4.1.99

**Additional context**

### PR DESCRIPTION
**Pull request by peter-mitsis**
Updates the heap code so that size_too_big() validates the actual number of bytes that will be subsequently be requested.

Fixes #90306

---

Updates:
* Elminates size_too_big() as it does not catch all overflow cases.
* Updates bytes_to_chunksz() so we do not overflow when converting bytes to chunks.
* Clamps return value of bytes_to_chunksz()

### CODE REVIEW

File: lib/heap/heap.c [hunk 1]
```diff
@@ -387,12 +387,13 @@ static bool inplace_realloc(struct sys_heap *heap, void *ptr, size_t bytes)
 {
 	struct z_heap *h = heap->heap;
 
-	if (size_too_big(h, bytes)) {
+	chunkid_t c = mem_to_chunkid(h, ptr);
+	size_t align_gap = (uint8_t *)ptr - (uint8_t *)chunk_mem(h, c);
```
Comment (andyross) [inline lib/heap/heap.c:392]: This bit doesn't look right.  That alignment gap reflects the space needed above the original block's start.  We're moving to a different area now with arbitrary chunk alignment, and the gap will be different.  There's no single "size that is too big", but I guess you could make a conservative guess by using the value from a pessimal alignment.

**Review by andyross — COMMENTED** [review]
Not quite understanding the root cause here?  Per docs, `size_too_big()` is just an optimization, it's checking the size of the allocation vs. the physical size of the heap to permit an early exit.  If it returns "false", then we **should** be simply going through the full allocation path and then failing normally after searching the relevant free lists.

So... sure, you can enhance it to be more sophisticated about what it rejects, but nothing we do here should be able to cause a corruption.  The worst failure should be an incorrect "true" response (i.e. an allocation failure) in circumstances where the heap could successfully allocate.

My fear is that this fix is masking a different bug.

File: lib/heap/heap.c (hunk 1 above)
Comment (peter-mitsis) [reply lib/heap/heap.c:392]: D'oh! I forgot a step--I should have been paying closer attention.

**Comment by peter-mitsis** [comment]
I previously forgot to include the chunk header bytes in the size_too_big() calculation.

As reported in #90306, there are corner cases where attempting to allocate too large a buffer can result in a crash instead of proper detection of too large of a request.

Imagine a heap of size 2048 and we want to k_malloc() 2033 bytes.

k_malloc(2033) → z_alloc_helper(2033).
z_alloc_helper(2033) → sys_heap_noalign_alloc(2037)

sys_heap_noalign_alloc() → size_too_big(2037)
  2037 / 8 = 254 rounded down.
  On the surface this is looks OK as it is less than the heap’s end_chunk (255)
But, bytes_to_chunksz(2037) internally adds chunk_header_bytes() which pushes the number of bytes being allocated from 2037 to 2041, and this is 255 chunks. As a result, when alloc_chunk(255) is called, we are calling it with an invalid input—one that leads to a crash.

So, size_too_big() needs to check the actual number of bytes that get allocated. Perhaps I overdid it on the caution in the math in the proposed changes, but I wanted to be sure that static analysis tools did not flag it for overflow (not that it is likely to occur in practice). Furthermore, since CHUNK_UNIT is defined as 8, the compiler ought to be smart enough to optimize the division and modulus operations into shifts and AND operations.

**Review by npitre — COMMENTED** [review]
The bug appears real but I think you're overdoing it a little.

Just to be sure, in `alloc_chunk()` there is a 
`CHECK(bi <= bucket_idx(h, h->end_chunk));` If enabled, this check 
should fail with your failure case. Can you confirm?
If so that's the actual issue: the size would be out of bounds for the
chunk bucket index.

We want the test in `size_too_big()` to be as cheap as possible.
So probably something simple like this ought to do it:

```
    return (bytes / CHUNK_UNIT) >= (h->end_chunk - 1);
```

**Comment by peter-mitsis** [comment]
@npitre - I can confirm that if that CHECK() is enabled, we hit it and it fails as expected.

My concern with your proposed `return (bytes / CHUNK_UNIT) >= (h->end_chunk - 1);` is that although it would guard against the straight k_malloc(2033) case previously described above, it would still be susceptible to the issue on another path where the alignment is user defined. That is, I expect that if someone were to use a heap of 2048 and attempt to request memory aligned to 32-bytes, we would get a similar type crash when trying to allocate 2005 bytes (or thereabout) and we are back to square one.

The more I think about it, the more I think that the better thing to do is to drop the early `size_too_big()` check and do a sanity check after `bytes_to_chunksz()` because the math to determine how much to allocate must be done either way.

**Comment by ljd42** [comment]
> @npitre - I can confirm that if that CHECK() is enabled, we hit it and it fails as expected.
> 
> My concern with your proposed `return (bytes / CHUNK_UNIT) >= (h->end_chunk - 1);` is that although it would guard against the straight k_malloc(2033) case previously described above, it would still be susceptible to the issue on another path where the alignment is user defined. That is, I expect that if someone were to use a heap of 2048 and attempt to request memory aligned to 32-bytes, we would get a similar type crash when trying to allocate 2005 bytes (or thereabout) and we are back to square one.

I confirm... `k_malloc(2009)` fails as before for HEAP_SIZE 2048 using  32-bytes alignments.

> The more I think about it, the more I think that the better thing to do is to drop the early `size_too_big()` check and do a sanity check after `bytes_to_chunksz()` because the math to determine how much to allocate must be done either way.

:+1:  
This would make the algorithm simpler to understand/maintain, I believe.

**Comment by npitre** [comment]
Oh damn, you're right. I completely failed to consider the aligning quantity.

In that case I'd suggest doing this:

```
diff --git a/lib/heap/heap.c b/lib/heap/heap.c
index 4f990f906a5..b76e46aa6db 100644
--- a/lib/heap/heap.c
+++ b/lib/heap/heap.c
@@ -213,7 +213,10 @@ static chunkid_t alloc_chunk(struct z_heap *h, chunksz_t sz)
 	int bi = bucket_idx(h, sz);
 	struct z_heap_bucket *b = &h->buckets[bi];
 
-	CHECK(bi <= bucket_idx(h, h->end_chunk));
+	if (sz >= h->end_chunk) {
+		/* This is more chunks than this heap contains. */
+		return 0;
+	}
 
 	/* First try a bounded count of items from the minimal bucket
 	 * size.  These may not fit, trying (e.g.) three means that
```

I wouldn't get rid of `size_too_big()` as it is cheap and it let us
dispense with addition overflow checks everywhere else.

**Comment by ljd42** [comment]
I obviously can't tell which options is best... But modulo  testing mistakes form my side, both proposals are functionally equivalent, and have no hole.

I have created a test for native_sim and native_sim/64 that systematically checks combination of heap_size, alloc_size (and align size when aligned heap is requested) and reports any hole/issue. ( The test in itself is rather straightforward, the challenge is finding all the holes without interrupting the test, and without too much 'white box' knowledge. ) 

Happy to discuss/provide this test, if you think it has some values.

**Comment by peter-mitsis** [comment]
size_too_big() is a decent approximation to eliminate most cases of overflow, but not all. It still breaks down at extremes with alignment--albeit extremes that we presently do not generally expect to occur. The following is admittedly contrived, but I have my 'let's break it hat' on.

Let the heap size be 3 GB and we call sys_heap_aligned_alloc() with the following constraints ...

- Let the requested alignment be to a 2 GB boundary.
- Let the requested number of bytes be 2.5 GB.
- size_t is 32 bits

We are going to see the following ...

1. size_too_big() is going to pass because 2.5 GB is less than the heap size.
2. bytes_to_chunksz(2.5 GB + 2 GB - 8 bytes) evaluates to bytes_to_chunksz(512 MB - 8 bytes).

Not only is there overflow, but it can appear to succeed when it should have failed.

**Comment by npitre** [comment]
> size_too_big() is a decent approximation to eliminate most cases of 
> overflow, but not all. It still breaks down at extremes with alignment

OK. Decidedly I'm dead set on a course where my brain simply can't remember
to consider alignment extras for more than 5 min.

So yeah... I like your latest patch except for the clamping inside
`bytes_to_chunksz()` which really looks odd. Please let's have
`bytes_to_chunksz()` simply convert bytes to chunks with no extra 
side effects. I like the way you avoid overflow issues so that's settled.
Then the test to decide if the allocation is too big should really live 
in `alloc_chunk()` and be what I suggested previously.

**Comment by peter-mitsis** [comment]
There is a reason why I did the clamping in bytes_to_chunksz().

The number of bytes is of type _size_t_ which depending upon platform is going to be either 32 or 64 bits, while the number of chunks is of type _chunksz_t_--always 32 bits. Consequently when _size_t_ is 64 bits, we could (in theory) get a number of chunks that can not be represented in 32 bits. Doing the clamping avoids that scenario. Perhaps a comment in the code is warranted to explain that.

**Review by npitre — APPROVED** [review]

**Comment by peter-mitsis** [comment]
I updated the comment explaining why clamping is done.

I did not do the early return in _alloc_chunk()_ as it is now just a special case of 'there is no single chunk large enough for the request' and so it will follow the existing won't fix. Although adding the early return ought to speed things up for the error case, I would expect it to simultaneously slow things down ever so slightly on the success path.  I took the option of favoring the success path. With that in mind, if reviewers would still prefer the early bail in _alloc_chunk()_, I will acquiesce. :)

**Review by andyross — APPROVED** [review]
This makes sense, thanks.  Definitely looks nicer without the semi-premature optimization in the too_big check.
