### PR TITLE
drivers: i3c: Fix NXP driver consuming a lot of CPU time

### LINKED ISSUE #91134: I3C MCUX Driver Transfer does busy waiting
### Describe the bug

When using the MCUX I3C controller with both I3C or I2C the transactions are consuming a lot of CPU time.

It seems to narrow down this line.
https://github.com/zephyrproject-rtos/zephyr/blob/d8b37753061a9e0ace95204eccddee1f4b4c477b/drivers/i3c/i3c_mcux.c#L964

In the function it says the following
https://github.com/zephyrproject-rtos/zephyr/blob/d8b37753061a9e0ace95204eccddee1f4b4c477b/drivers/i3c/i3c_mcux.c#L141-L145

But this is not the case we're using microseconds instead.

Suggestion is to use semaphore and then with `TXTRIG` register level to generate interrupts to signal FIFO can be filled.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- FRDM-MCXN947

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mmahadevan108**
The I3C and I2C transactions are consuming a lot of CPU time. The stated polling check was is not completed in sub-microseconds as is stated in the comment.
Added a 1usec sleep between probes of status register.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/91134

### CODE REVIEW

**Review by dleach02 — DISMISSED** [review]

File: drivers/i3c/i3c_mcux.c [hunk 1]
```diff
@@ -140,10 +139,9 @@ static int reg32_poll_timeout(volatile uint32_t *reg,
 {
 	/*
 	 * These polling checks are typically satisfied
-	 * quickly (some sub-microseconds) so no extra
-	 * delay between checks.
+	 * quickly. Add a small delay between checks
 	 */
-	if (!WAIT_FOR((sys_read32((mm_reg_t)reg) & mask) == match, timeout_us, /*nop*/)) {
+	if (!WAIT_FOR((sys_read32((mm_reg_t)reg) & mask) == match, timeout_us, k_usleep(1))) {
```
Comment (PetervdPerk-NXP) [inline drivers/i3c/i3c_mcux.c]: We're trading CPU load for latency, and technically it could happen with k_usleep() that FIFO buffer underflows.
I would recommend implementing this using interrupts instead removing the need for active polling.

Comment (mmahadevan108) [reply drivers/i3c/i3c_mcux.c]: @PetervdPerk-NXP , I have changed the implementation of the I3C driver to use interrupts, Please review and try on your system.

**Comment by dleach02** [comment]
@mmahadevan108 what do you want to do with this PR?

**Review by PetervdPerk-NXP — DISMISSED** [review]

**Review by PetervdPerk-NXP — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
