### PR TITLE
drivers: bluetooth: hci_spi: add missing gpio_dt_flags to spi_cs_config

### LINKED ISSUE #27280: drivers: bluetooth: hci: spi: CS DT config not working because CS gpio_dt_flags are not set in the spi_cs_config struct
**Describe the bug**
This bug was introduced in #26269 which adds gpio_dt_flags to configure CS active level from the device tree.
I noticed that my CS active level was always the same despite the change the device tree CS pin flags definition.

Having:
```c
&spi1 {
	compatible = "st,stm32-spi-fifo", "st,stm32-spi";
    	cs-gpios = <&gpioa 4 GPIO_ACTIVE_LOW>;
	status = "okay";

	bt-hci@0 {
		compatible = "zephyr,bt-hci-spi";
		reg = <0>;
		irq-gpios = <&gpiob 4 GPIO_ACTIVE_HIGH>;
	        reset-gpios = <&gpiof 12 GPIO_ACTIVE_LOW>;
	        spi-max-frequency = <312500>;
	        label = "HCI-SPI1";
	};
};
```
```c
&spi1 {
	compatible = "st,stm32-spi-fifo", "st,stm32-spi";
    	cs-gpios = <&gpioa 4 GPIO_ACTIVE_HIGH>;
	status = "okay";

	bt-hci@0 {
		compatible = "zephyr,bt-hci-spi";
		reg = <0>;
		irq-gpios = <&gpiob 4 GPIO_ACTIVE_HIGH>;
	        reset-gpios = <&gpiof 12 GPIO_ACTIVE_LOW>;
	        spi-max-frequency = <312500>;
	        label = "HCI-SPI1";
	};
};
```

Both produce Active HIGH configurations. I can only conclude that this code was not tested on a target which could have shown the problem.

**Reason**
The author forgot to fill up the new ```gpio_dt_flags``` declared in ```include/drivers/spi.h```: 
```c
struct spi_cs_control {
	struct device	*gpio_dev;
	uint32_t		gpio_pin;
	uint32_t		delay;
	gpio_pin_t		gpio_pin;
	gpio_dt_flags_t		gpio_dt_flags;
};
```
The fill up should occur in ```drivers/bluetooth/hci/spi.c```:

```c
static int configure_cs(void)
{
#ifdef GPIO_CS_PIN
	static struct spi_cs_control spi_conf_cs;

	spi_conf_cs.gpio_pin = GPIO_CS_PIN; /* <== This line was finished with a colon instead of semicolon*/
	spi_conf_cs.gpio_dev = device_get_binding(
		DT_INST_SPI_DEV_CS_GPIOS_LABEL(0));
	spi_conf_cs.gpio_dt_flags = GPIO_CS_FLAGS; /* <== This is the line that is missing */
	if (!spi_conf_cs.gpio_dev) {
		BT_ERR("Failed to initialize GPIO driver: %s",
		       DT_INST_SPI_DEV_CS_GPIOS_LABEL(0));
		return -EIO;
	}

	spi_conf.cs = &spi_conf_cs;
#endif /* GPIO_CS_PIN */

	return 0;
}
```

**To Reproduce**
1. flash a board with HOST using HCI SPI program and Software controlled CS gpio with Active low configuration
```
**board.overlay**
```c
&spi1 {
	compatible = "st,stm32-spi-fifo", "st,stm32-spi";
    	cs-gpios = <&gpioa 4 GPIO_ACTIVE_LOW>;
	status = "okay";

	bt-hci@0 {
		compatible = "zephyr,bt-hci-spi";
		reg = <0>;
		irq-gpios = <&gpiob 4 GPIO_ACTIVE_HIGH>;
	        reset-gpios = <&gpiof 12 GPIO_ACTIVE_LOW>;
	        spi-max-frequency = <312500>;
	        label = "HCI-SPI1";
	};
};
**prj.conf**
CONFIG_BT=y
CONFIG_BT_SPI=y
```
2. monitor the CS pin during SPI transceive
3. See that the actual CS level HIGH and not LOW

**Expected behavior**
GPIO_ACTIVE_HIGH should produce a HIGH level when ```spi_context_cs_control(&data->ctx, true);``` is called.
GPIO_ACTIVE_LOW should produce a LOW level when ```spi_context_cs_control(&data->ctx, true);``` is called.

**Impact**
All SPI transactions fail due to invalid CS level where CS active LOW level is recquired.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 64bits 
 - Toolchain (e.g Zephyr SDK, ...)
-  Patch: master
 - Board: nucleo_l4r5zi

### PR DESCRIPTION
**Pull request by lochej**
Fixes #27280 by adding the new gpio_dt_flags to the
HCI spi cs config.

Signed-off-by: Jeremy LOCHE <lochejeremy@gmail.com>

### CODE REVIEW

**Comment by carlescufi** [comment]
@anangl could you please take a look?

**Review by anangl — APPROVED** [review]

File: drivers/bluetooth/hci/spi.c [hunk 1]
```diff
@@ -258,9 +258,10 @@ static int configure_cs(void)
 #ifdef GPIO_CS_PIN
 	static struct spi_cs_control spi_conf_cs;
 
-	spi_conf_cs.gpio_pin = GPIO_CS_PIN,
+	spi_conf_cs.gpio_pin = GPIO_CS_PIN;
 	spi_conf_cs.gpio_dev = device_get_binding(
 		DT_INST_SPI_DEV_CS_GPIOS_LABEL(0));
+	spi_conf_cs.gpio_dt_flags = GPIO_CS_FLAGS;
```
Comment (joerchan) [inline drivers/bluetooth/hci/spi.c:264]: Move this above the assignment to gpio_dev, since the error check of that is below, now this line is squeezed in between those.

**Review by joerchan — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/spi.c (hunk 1 above)
Comment (lochej) [reply drivers/bluetooth/hci/spi.c]: Done ! 👍

**Review by joerchan — APPROVED** [review]
