### PR TITLE
tests: drivers: counter: Improve alarm capability detection

### LINKED ISSUE #100529: tests: drivers: frdm_mcxn947: drivers.counter.basic_api fails
### Describe the bug

Test drivers.counter.basic_api fails on frdm_mcxn947 after [commit ](https://github.com/zephyrproject-rtos/zephyr/commit/a3663c8c7fd)

### Regression

- [x] This is a regression.

### Steps to reproduce

twister -p frdm_mcxn947/mcxn947/cpu0 --device-testing --hardware-map map.yaml -s drivers.counter.basic_api

### Relevant log output

```shell
*** Booting Zephyr OS build v4.3.0-1638-gd14a547d4259 (delayed boot 500ms) ***
Running TESTSUITE counter_basic
===================================================================
START - test_all_channels
Testing ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Testing lptmr@4a000
Testing lptmr@4b000
 PASS - test_all_channels in 0.501 seconds
===================================================================
START - test_cancelled_alarm_does_not_expire
Skipped for ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Skipped for lptmr@4a000
Skipped for lptmr@4b000
 SKIP - test_cancelled_alarm_does_not_expire in 0.412 seconds
===================================================================
START - test_late_alarm
Skipped for ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Skipped for lptmr@4a000
Skipped for lptmr@4b000
 SKIP - test_late_alarm in 0.412 seconds
===================================================================
START - test_late_alarm_error
Skipped for ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Skipped for lptmr@4a000
Skipped for lptmr@4b000
 SKIP - test_late_alarm_error in 0.412 seconds
===================================================================
START - test_multiple_alarms
Testing ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Skipped for lptmr@4a000
Skipped for lptmr@4b000
 PASS - test_multiple_alarms in 0.466 seconds
===================================================================
START - test_set_top_value_with_alarm
Testing ctimer@c000
Testing mrt0_channel@0
I: "Started" MRT@0x50013000 channel 0 with default value 16777215
W: MRT@0x50013000 channel 0 received requested top value 3000000 which is smaller than current count 16026450
W: MRT channel resets upon stopping
Testing lptmr@4a000
Testing lptmr@4b000
 PASS - test_set_top_value_with_alarm in 0.862 seconds
===================================================================
START - test_short_relative_alarm
Skipped for ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Skipped for lptmr@4a000
Skipped for lptmr@4b000
 SKIP - test_short_relative_alarm in 0.415 seconds
===================================================================
START - test_single_shot_alarm_notop
Testing ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Testing lptmr@4a000

    Assertion failed at WEST_TOPDIR/zephyrproject/tests/drivers/counter/counter_basic_api/src/test_counter.c:481: test_single_shot_alarm_instance: (0 not equal to err)
lptmr@4a000: Counter set alarm failed (err: -134)
 FAIL - test_single_shot_alarm_notop in 0.300 seconds
===================================================================
START - test_single_shot_alarm_top
Testing ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Testing lptmr@4a000

    Assertion failed at WEST_TOPDIR/zephyrproject/tests/drivers/counter/counter_basic_api/src/test_counter.c:474: test_single_shot_alarm_instance: (-EINVAL not equal to err)
lptmr@4a000: Counter should return error because ticks exceeded the limit set alarm
 FAIL - test_single_shot_alarm_top in 0.304 seconds
===================================================================
START - test_valid_function_without_alarm
Testing ctimer@c000
Skipped for mrt0_channel@0
W: MRT channel resets upon stopping
Testing lptmr@4a000

    Assertion failed at WEST_TOPDIR/zephyrproject/tests/drivers/counter/counter_basic_api/src/test_counter.c:779: test_valid_function_without_alarm: (ticks not between ticks_expected > ticks_tol ? ticks_expected - ticks_tol : 0 and ticks_expected + ticks_tol inclusive)
lptmr@4a000: counter ticks not in tolerance
 FAIL - test_valid_function_without_alarm in 0.302 seconds
===================================================================
TESTSUITE counter_basic failed.
Running TESTSUITE counter_no_callback
===================================================================
START - test_set_top_value_without_alarm
Testing ctimer@c000
Testing mrt0_channel@0
I: "Started" MRT@0x50013000 channel 0 with default value 16777215
W: MRT@0x50013000 channel 0 received requested top value 3000000 which is smaller than current count 16023727
W: MRT channel resets upon stopping
Testing lptmr@4a000
Testing lptmr@4b000
 PASS - test_set_top_value_without_alarm in 0.447 seconds
===================================================================
TESTSUITE counter_no_callback succeeded

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  50.00% [counter_basic]: pass = 3, fail = 3, skip = 4, total = 10 duration = 4.386 seconds
 - PASS - [counter_basic.test_all_channels] duration = 0.501 seconds
 - SKIP - [counter_basic.test_cancelled_alarm_does_not_expire] duration = 0.412 seconds
 - SKIP - [counter_basic.test_late_alarm] duration = 0.412 seconds
 - SKIP - [counter_basic.test_late_alarm_error] duration = 0.412 seconds
 - PASS - [counter_basic.test_multiple_alarms] duration = 0.466 seconds
 - PASS - [counter_basic.test_set_top_value_with_alarm] duration = 0.862 seconds
 - SKIP - [counter_basic.test_short_relative_alarm] duration = 0.415 seconds
 - FAIL - [counter_basic.test_single_shot_alarm_notop] duration = 0.300 seconds
 - FAIL - [counter_basic.test_single_shot_alarm_top] duration = 0.304 seconds
 - FAIL - [counter_basic.test_valid_function_without_alarm] duration = 0.302 seconds
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

SDK: zephyr-sdk-0.17.4
Zephyr version:  v4.3.0-1638-gd14a547d4259
OS: Ubuntu 22.04

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ZhaoxiangJin**
- Add a self-contained alarm_capable() probe that starts the device, sets and cancels a 1-tick alarm, and stops the counter again. This treats -ENOTSUP as “not capable” and avoids leaving pending alarms.
- Switch single/multiple alarm capability checks to reuse alarm_capable(), preventing unsupported drivers from running alarm cases and reducing false failures.
- Ensure capability probing no longer leaves the driver running or with active alarms, preventing teardown/set_top_value failures in later tests.

fix https://github.com/zephyrproject-rtos/zephyr/issues/100529

### CODE REVIEW

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 1]
```diff
@@ -432,6 +432,54 @@ static void alarm_handler(const struct device *dev, uint8_t chan_id,
 	k_sem_give(&alarm_cnt_sem);
 }
 
+static bool alarm_capable(const struct device *dev)
+{
+	struct counter_alarm_cfg cfg = {
+		.flags = 0,
+		.ticks = 1U,
```
Comment (Holt-Sun) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: 1 is too small, cancel may return -ETIME/-EINVAL if the alarm already fired

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 2]
```diff
@@ -432,6 +432,54 @@ static void alarm_handler(const struct device *dev, uint8_t chan_id,
...
+		return false;
+	}
+
+	err = counter_set_channel_alarm(dev, 0, &cfg);
+	if (err == -ENOTSUP) {
+		goto out_stop;
+	}
+
+	if (err != 0) {
+		goto out_stop;
```
Comment (Holt-Sun) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: The "err == -ENOSETUP"  and "err != 0" duplicate.

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 3]
```diff
@@ -432,6 +432,54 @@ static void alarm_handler(const struct device *dev, uint8_t chan_id,
 	k_sem_give(&alarm_cnt_sem);
 }
 
+static bool alarm_capable(const struct device *dev)
+{
+	struct counter_alarm_cfg cfg = {
+		.flags = 0,
+		.ticks = 1U,
+		.callback = alarm_handler,
```
Comment (Holt-Sun) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: If the alarm fires before cancellation, alarm_handler() will call k_sem_give(&alarm_cnt_sem), potentially affecting later tests.


```suggestion
static void dummy_alarm_handler(const struct device *dev, uint8_t chan_id,
                                uint32_t ticks, void *user_data)
{
    /* Intentionally empty - capability probe only */
}

struct counter_alarm_cfg cfg = {
    .flags = 0,
    .ticks = 1U,
    .callback = dummy_alarm_handler, 
    .user_data = NULL,
};
```

**Review by Holt-Sun — CHANGES_REQUESTED** [review]

File: tests/drivers/counter/counter_basic_api/src/test_counter.c (hunk 1 above)
Comment (nordic-krch) [reply tests/drivers/counter/counter_basic_api/src/test_counter.c]: Use something like `counter_us_to_ticks(1000)` to get tick value that for sure will not expire before cancelling.

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 4]
```diff
@@ -432,6 +432,54 @@ static void alarm_handler(const struct device *dev, uint8_t chan_id,
...
+	bool started = false;
+
+	if (counter_get_num_of_channels(dev) < 1U) {
+		return false;
+	}
+
+	err = counter_start(dev);
+	if (err == 0) {
+		started = true;
+	} else if (err == -ENOTSUP) {
```
Comment (nordic-krch) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: single `err != 0` is enough

File: tests/drivers/counter/counter_basic_api/src/test_counter.c (hunk 1 above)
Comment (ZhaoxiangJin) [reply tests/drivers/counter/counter_basic_api/src/test_counter.c]: updated

File: tests/drivers/counter/counter_basic_api/src/test_counter.c (hunk 2 above)
Comment (ZhaoxiangJin) [reply tests/drivers/counter/counter_basic_api/src/test_counter.c]: updated

File: tests/drivers/counter/counter_basic_api/src/test_counter.c (hunk 3 above)
Comment (ZhaoxiangJin) [reply tests/drivers/counter/counter_basic_api/src/test_counter.c]: added new callback for this case

File: tests/drivers/counter/counter_basic_api/src/test_counter.c (hunk 4 above)
Comment (ZhaoxiangJin) [reply tests/drivers/counter/counter_basic_api/src/test_counter.c]: updated.

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 5]
```diff
@@ -432,6 +432,56 @@ static void alarm_handler(const struct device *dev, uint8_t chan_id,
...
+}
+
+/* Any non-zero error (including -ENOTSUP) is treated as "not supported",
+ * and only returns true when there are no errors throughout the entire process.
+ */
+static bool alarm_capable(const struct device *dev)
+{
+	struct counter_alarm_cfg cfg = {
+		.flags = 0,
+		.ticks = counter_us_to_ticks(dev, 1000),
```
Comment (Holt-Sun) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: This is 1 ms, on very low-frequency counters, this may round to 0 ticks, potentially causing immediate expiry or invalid request.

```suggestion
		.ticks = counter_us_to_ticks(dev, 1000),
		
		 /* Avoid zero-tick requests on very low-frequency counters */
         if (cfg.ticks == 0U) {
             cfg.ticks = 1U;
          }
```

**Review by Holt-Sun — CHANGES_REQUESTED** [review]

File: tests/drivers/counter/counter_basic_api/src/test_counter.c (hunk 5 above)
Comment (ZhaoxiangJin) [reply tests/drivers/counter/counter_basic_api/src/test_counter.c]: updated

**Review by Holt-Sun — APPROVED** [review]

**Comment by ZhaoxiangJin** [comment]
Hello @nordic-krch, please help to review, thanks.

**Review by nordic-krch — APPROVED** [review]
