### PR TITLE
Make dummy shell backend configurable

### LINKED ISSUE #32755: mcumgr: shell output gets truncated
**Describe the bug**
The mcumgr output from shell command gets truncated at predefined length, determined by buffer length.
Providing `shell help` as an example but the issue impacts all shell commands that return some output.

**To Reproduce**
1. Build
`west build -b nrf52840dk_nrf52840    zephyr/samples/subsys/mgmt/mcumgr/smp_svr    -t menuconfig --    -DOVERLAY_CONFIG='overlay-fs.conf;overlay-shell.conf'`
build and sign with your key
2. Flash to board and reset
3. Attempt to get help from shell
`mcumgr -t 1200 --conntype serial  --connstring dev=/dev/ttyACM0,baud=115200 shell exec help`
image

**Expected behavior**
Shell output does not get truncated:
image

**Impact**
Most shell commands that give output longer than fits in buffer unusable.

**Environment (please complete the following information):**
 - OS: Linux 5.4.0-65-generic x86_64
 - Toolchain zephyr-sdk 0.12
 - Zephyr 9df116ed0f6841fb9fbe1f804a5736622787f030

### PR DESCRIPTION
**Pull request by de-nordic**
The PR consists of two PRs:
-  **shell: Parametrize dummy shell buffer size**
 that introduces new Kconfig option `SHELL_BACKEND_DUMMY_BUF_SIZE`, enabling user to select number of characters the backend will be able to catch from an executed command;
- **mgmt/mcumgr: Info on `SHELL_BACKEND_DUMMY_BUF_SIZE` impact on mcumgr**
 that adds notes to Mcumgr Kconfig options, which area affected by introduction of `CONFIG_SHELL_BACKEND_DUMMY_BUF_SIZE`, how to properly set them.

Fixes: #32755

### CODE REVIEW

**Review by jakub-uC — APPROVED** [review]

File: subsys/shell/shell.c [hunk 1]
```diff
@@ -8,7 +8,9 @@
 #include <stdlib.h>
 #include <sys/atomic.h>
 #include <shell/shell.h>
+#if defined(CONFIG_SHELL_BACKEND_DUMMY)
```
Comment (nordic-krch) [inline subsys/shell/shell.c:11]: why this change is needed? API's shall not be ifdefed (https://docs.zephyrproject.org/latest/guides/coding_guidelines/index.html#rule-a-1-conditional-compilation) so ifdefing headers should not be needed as well.

Comment (de-nordic) [reply subsys/shell/shell.c:11]: This does not explicitly state so:`
>
>Do not conditionally compile function declarations _in header files_. Do not conditionally compile structure declarations _in header files_. You may conditionally exclude fields within structure definitions to avoid wasting memory when the feature they support is not enabled

It is nowhere there that the headers shall not be excluded, as far as I can tell  and all sentences are about ifdefs **within** header files.

There might be  implicit suggestion in rationale:
>
>Excluding declarations _from the header_ based on compile-time options may prevent their documentation from being generated. 

but it again says: **from the header**.

I can fix that by defining intermediate variable when `CONFIG_SHELL_BACKEND_DUMMY_BUF_SIZE` is not defined because the dummy backend has not been selected, if you prefer that way.

There is precedence in code where the headers are ifdefed, for example in `./bluetooth/controller/hci/hci_driver.c`
```
...
#include <drivers/bluetooth/hci_driver.h>

#ifdef CONFIG_CLOCK_CONTROL_NRF
#include <drivers/clock_control/nrf_clock_control.h>
#endif
...
```

or `./subsys/net/lib/lwm2m/lwm2m_engine.c`
```
...
#include <net/socket.h>
#if defined(CONFIG_LWM2M_DTLS_SUPPORT)
#include <net/tls_credentials.h>
#endif
#if defined(CONFIG_DNS_RESOLVER)
#include <net/dns_resolve.h>
#endif
...
```

Comment (nordic-krch) [reply subsys/shell/shell.c:11]: ah, ok. I see that buf size is not defined there. I will not block but personally i prefer to create ifdef.

**Review by nordic-krch — APPROVED** [review]
