### PR TITLE
Fix thread function signatures

### LINKED ISSUE #62637: Incorrect function signature for ADC data acquisition threads
Data acquisition threads for ADCs usually have the incorrect function signature. Examples are:

- https://github.com/zephyrproject-rtos/zephyr/blob/94cc1bf4551a933200f1f65777a19869264bc5bf/drivers/adc/adc_ads1119.c#L436
- https://github.com/zephyrproject-rtos/zephyr/blob/94cc1bf4551a933200f1f65777a19869264bc5bf/drivers/adc/adc_ads114s0x.c#L1066
- https://github.com/zephyrproject-rtos/zephyr/blob/94cc1bf4551a933200f1f65777a19869264bc5bf/drivers/adc/adc_ads1x1x.c#L540
- https://github.com/zephyrproject-rtos/zephyr/blob/94cc1bf4551a933200f1f65777a19869264bc5bf/drivers/adc/adc_ads7052.c#L222

They all have one parameter, but the thread entry function pointer is defined as:

    typedef void (*k_thread_entry_t)(void *p1, void *p2, void *p3);

Therefore these functions would corrupt the stack if they would return, which they luckily won't ever do.

I'm uncertain if this is intended, but I wanted to at least mentioned this imperfection.

### PR DESCRIPTION
**Pull request by benediktibk**
Fix the thread function signatures to match k_thread_entry_t. This won't make a real difference in most cases, as the threads won't return anyway. But theoretically this could cause a stack corruption.

Fixes #62637

### CODE REVIEW

**Comment by benediktibk** [comment]
So far I have not dealt with the unused arguments, as I am uncertain which is the current way to go. Mostly I have seen ARG_UNUSED, but in #26978 __unused is available and used as well.

There >100 other cases of this issue as well, this covers only zephyr/drivers/** by now.

**Comment by benediktibk** [comment]
@fabiobaltieri This is my proposal to fix #62637

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri This is my proposal to fix #62637

hey thanks, are you going to undraft it? It's green in CI...

**Comment by benediktibk** [comment]
> > @fabiobaltieri This is my proposal to fix #62637
> 
> hey thanks, are you going to undraft it? It's green in CI...

I would like to address first the unused arguments, and I am uncertain if ARG_UNUSED or __unused is the preferred approach?

On top of that I would then also go through the rest of the wrong thread function signatures, there are plenty left.

**Comment by fabiobaltieri** [comment]
> I would like to address first the unused arguments, and I am uncertain if ARG_UNUSED or __unused is the preferred approach?

I think `ARG_UNUSED` is for function arguments and `__unused` is for variables, or at least that's how they seem to be normally used here.

**Comment by benediktibk** [comment]
If I understood it correctly this should **not** classify as a tree wide change.
https://docs.zephyrproject.org/latest/contribute/guidelines.html#treewide-changes

**Comment by benediktibk** [comment]
This includes now all incorrect thread function signatures which I was able to find and also addresses the unused arguments.

File: samples/net/mqtt_sn_publisher/src/main.c [hunk 1]
```diff
@@ -107,9 +114,10 @@ int main(void)
 	k_thread_access_grant(k_current_get(), &run_app);
 	k_mem_domain_add_thread(&app_domain, k_current_get());
 
-	k_thread_user_mode_enter((k_thread_entry_t)start_client, NULL, NULL, NULL);
+	k_thread_user_mode_enter(start_client, &result, NULL, NULL);
```
Comment (peter-mitsis) [inline samples/net/mqtt_sn_publisher/src/main.c:117]: I may be wrong here, but I am suspicious of passing _&result_ for the user thread case as the memory to which it points may not be available to the user thread. If this suspicion is correct, then that would result in an exception.

My recommendation would be to pass _NULL_ for the user thread case and have a check in _start_client()_ to only write to _*result_ if _result_ is not _NULL_.

Comment (benediktibk) [reply samples/net/mqtt_sn_publisher/src/main.c:117]: I would rather skip the result completely, as it is only used for exit() later on. I don't really see the benefit of reporting something there.

File: samples/net/sockets/echo_client/src/echo-client.c [hunk 2]
```diff
@@ -327,10 +333,11 @@ int main(void)
 	k_thread_access_grant(k_current_get(), &run_app);
 	k_mem_domain_add_thread(&app_domain, k_current_get());
 
-	k_thread_user_mode_enter((k_thread_entry_t)start_client, NULL, NULL,
+	k_thread_user_mode_enter(start_client, &result, NULL,
```
Comment (peter-mitsis) [inline samples/net/sockets/echo_client/src/echo-client.c:336]: Similar comment here as with mqtt_sn_publisher. Since _result_ might not be accessible from user space, we should probably use _NULL_ for this case and update _start_client()_ as appropriate.

**Review by nandojve — DISMISSED** [review]
For drivers/ieee802154/rf2xx and drivers/wifi/eswifi only

File: samples/net/mqtt_sn_publisher/src/main.c (hunk 1 above)
Comment (cfriedt) [reply samples/net/mqtt_sn_publisher/src/main.c:117]: Yeah, this would definitely result in MPU / MMU exception.

**Review by ghost — COMMENTED** [review]
LGTM re ieee802154 drivers

**Review by rerickson1 — DISMISSED** [review]
Modem drivers look good.

File: samples/net/sockets/echo_client/src/echo-client.c (hunk 2 above)
Comment (benediktibk) [reply samples/net/sockets/echo_client/src/echo-client.c]: I'm handling this similarly to the mqtt_sn_publisher sample

File: samples/net/mqtt_sn_publisher/src/main.c (hunk 1 above)
Comment (benediktibk) [reply samples/net/mqtt_sn_publisher/src/main.c]: I removed the result completely, as I do not think it is really helpful. This way now the sample has the same exit code, no matter if CONFIG_USERSPACE is enabled or not.

**Review by peter-mitsis — DISMISSED** [review]
Looks good to me.

**Comment by glarsennordic** [comment]
conn_mgr changes look just fine to me as long as tests are passing (which they are)

**Review by ghost — COMMENTED** [review]
Re-ACK re ieee802154 subsys

**Comment by fabiobaltieri** [comment]
> I'm not reviewing because (presumably due to the 15-reviewer limit) my request for review was removed

Sorry I indeed cleared the list and added kernel and device model maintainers to work around the github limit, please don't read it as a "do not review", reviews from anyone are welcome. :-)

**Review by glarsennordic — DISMISSED** [review]

File: tests/kernel/smp/src/main.c [hunk 3]
```diff
@@ -1004,8 +1014,12 @@ static void inc_global_cnt(void *a, void *b, void *c)
 	}
 }
 
-static int run_concurrency(int type, void *func)
+static int run_concurrency(void *p1, void *p2, void *p3)
 {
+	ARG_UNUSED(p3);
+
+	int type = p1;
```
Comment (ceolin) [inline tests/kernel/smp/src/main.c:1021]: isn't this causing a warning ? you probably should use `POINTER_TO_INT(p1)`

File: tests/kernel/smp/src/main.c [hunk 4]
```diff
@@ -1004,8 +1014,12 @@ static void inc_global_cnt(void *a, void *b, void *c)
...
+	void *func = p2;
```
Comment (ceolin) [inline tests/kernel/smp/src/main.c:1022]: `k_thread_entry_t func = p2;` for the sake of clarity ?

File: samples/net/mqtt_sn_publisher/src/main.c [hunk 5]
```diff
@@ -107,9 +111,9 @@ int main(void)
 	k_thread_access_grant(k_current_get(), &run_app);
 	k_mem_domain_add_thread(&app_domain, k_current_get());
 
-	k_thread_user_mode_enter((k_thread_entry_t)start_client, NULL, NULL, NULL);
+	k_thread_user_mode_enter(start_client, NULL, NULL, NULL);
 #else
-	exit(start_client());
+	start_client(NULL, NULL, NULL);
```
Comment (ceolin) [inline samples/net/mqtt_sn_publisher/src/main.c:116]: is it right ? This change is beyond function signature change

File: samples/net/mqtt_sn_publisher/src/udp.c [hunk 6]
```diff
@@ -141,23 +141,26 @@ static void process_thread(void)
...
 
-int start_thread(void)
+void start_thread(void)
 {
 	int rc;
 #if defined(CONFIG_USERSPACE)
 	rc = k_mem_domain_add_thread(&app_domain, udp_thread_id);
 	if (rc < 0) {
-		return rc;
+		LOG_ERR("Failed: k_mem_domain_add_thread() %d", rc);
```
Comment (ceolin) [inline samples/net/mqtt_sn_publisher/src/udp.c:150]: shouldn't it return here ?

**Review by cfriedt — DISMISSED** [review]

**Review by nandojve — DISMISSED** [review]
Re-ACK drivers/ieee802154/rf2xx and drivers/wifi/eswifi

File: tests/kernel/smp/src/main.c (hunk 3 above)
Comment (benediktibk) [reply tests/kernel/smp/src/main.c]: done

File: tests/kernel/smp/src/main.c (hunk 4 above)
Comment (benediktibk) [reply tests/kernel/smp/src/main.c]: done

File: samples/net/mqtt_sn_publisher/src/udp.c (hunk 6 above)
Comment (benediktibk) [reply samples/net/mqtt_sn_publisher/src/udp.c:150]: nice catch, done

**Review by cfriedt — DISMISSED** [review]

File: tests/kernel/sleep/src/main.c [hunk 7]
```diff
@@ -171,8 +175,12 @@ static void irq_offload_isr(const void *arg)
 	k_wakeup((k_tid_t) arg);
 }
 
-static void helper_thread(int arg1, int arg2)
+static void helper_thread(void *p1, void *p2, void *p3)
 {
+	ARG_UNUSED(p3);
+
+	int arg1 = p1;
+	int arg2 = p2;
```
Comment (ceolin) [inline tests/kernel/sleep/src/main.c:183]: These will cause warnings, you have to cast. `POINTER_TO_INT(p1);`

Comment (ceolin) [reply tests/kernel/sleep/src/main.c:183]: please review other cases like this one.

Comment (cfriedt) [reply tests/kernel/sleep/src/main.c:183]: CI was definitely running with `-Werror` the last time I checked.

**Comment by benediktibk** [comment]
rebased to resolve merge conflicts

File: tests/kernel/sleep/src/main.c (hunk 7 above)
Comment (benediktibk) [reply tests/kernel/sleep/src/main.c]: I went through all the changes and I think I found all these occasions.

**Review by carlescufi — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
And this:
```
/__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:155:70: error: passing argument 4 of 'k_thread_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
  155 |         CREATE_PARTICIPANT_THREAD(metairq_thread_id, K_PRIO_COOP(0), metairq_thread);
      |                                                                      ^~~~~~~~~~~~~~
      |                                                                      |
      |                                                                      void (*)(void)
/__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:43:25: note: in definition of macro 'CREATE_PARTICIPANT_THREAD'
   43 |                         entry,                                                         \
      |                         ^~~~~
In file included from /__w/zephyr/zephyr/include/zephyr/kernel.h:6102,
                 from /__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:6:
/__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/kernel/sched/metairq/kernel.scheduler.metairq/zephyr/include/generated/syscalls/kernel.h:59:131: note: expected 'k_thread_entry_t' {aka 'void (*)(void *, void *, void *)'} but argument is of type 'void (*)(void)'
   59 | static inline k_tid_t k_thread_create(struct k_thread * new_thread, k_thread_stack_t * stack, size_t stack_size, k_thread_entry_t entry, void * p1, void * p2, void * p3, int prio, uint32_t options, k_timeout_t delay)
      |                                                                                                                  ~~~~~~~~~~~~~~~~~^~~~~
/__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:156:68: error: passing argument 4 of 'k_thread_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
  156 |         CREATE_PARTICIPANT_THREAD(coop_thread1_id, K_PRIO_COOP(1), coop_thread1);
      |                                                                    ^~~~~~~~~~~~
      |                                                                    |
      |                                                                    void (*)(void)
/__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:43:25: note: in definition of macro 'CREATE_PARTICIPANT_THREAD'
   43 |                         entry,                                                         \
      |                         ^~~~~
/__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/kernel/sched/metairq/kernel.scheduler.metairq/zephyr/include/generated/syscalls/kernel.h:59:131: note: expected 'k_thread_entry_t' {aka 'void (*)(void *, void *, void *)'} but argument is of type 'void (*)(void)'
   59 | static inline k_tid_t k_thread_create(struct k_thread * new_thread, k_thread_stack_t * stack, size_t stack_size, k_thread_entry_t entry, void * p1, void * p2, void * p3, int prio, uint32_t options, k_timeout_t delay)
      |                                                                                                                  ~~~~~~~~~~~~~~~~~^~~~~
/__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:157:68: error: passing argument 4 of 'k_thread_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
  157 |         CREATE_PARTICIPANT_THREAD(coop_thread2_id, K_PRIO_COOP(2), coop_thread2);
      |                                                                    ^~~~~~~~~~~~
      |                                                                    |
      |                                                                    void (*)(void)
/__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:43:25: note: in definition of macro 'CREATE_PARTICIPANT_THREAD'
   43 |                         entry,                                                         \
      |                         ^~~~~
```

**Comment by jhedberg** [comment]
@carlescufi considering the extent of breakage, maybe this should be reverted?

File: tests/kernel/mem_protect/stackprot/src/main.c [hunk 8]
```diff
@@ -129,7 +129,7 @@ ZTEST(stackprot, test_create_alt_thread)
 {
 	/* Start thread */
 	k_thread_create(&alt_thread_data, alt_thread_stack_area, STACKSIZE,
-			(k_thread_entry_t)alternate_thread, NULL, NULL, NULL,
+			alternate_thread, NULL, NULL, NULL,
```
[the remark this answers is not in the document]
Comment (fabiobaltieri) [reply tests/kernel/mem_protect/stackprot/src/main.c:132]: The PR CI and push CI run two different set of tests, and then the weekly run is a much wider set so even after the push and PR there may be some leftover warning.

[the remark this answers is not in the document]
Comment (benediktibk) [reply tests/kernel/mem_protect/stackprot/src/main.c:132]: In which case is the PR and the push CI run? These failures popped up in https://github.com/zephyrproject-rtos/zephyr/pull/64570, which I assume should run the same tests as this PR?

BTW, I'm already trying to fix it in https://github.com/zephyrproject-rtos/zephyr/pull/64579

[the remark this answers is not in the document]
Comment (fabiobaltieri) [reply tests/kernel/mem_protect/stackprot/src/main.c:132]: That's the workflow definition: https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/workflows/twister.yaml, there's a bunch of branches depending whether it's `push`, `pull_request_target` or `schedule`, the specific implementations are beyond me but the PR one does something based the modified files I think and the schedule one is a monster run with all possible combination I think (https://github.com/zephyrproject-rtos/zephyr/actions/workflows/twister.yaml?query=event%3Aschedule).
