### PR TITLE
logging: fix starvation caused by uncommitted message

### LINKED ISSUE #101401: logging: thread starvation for lower-priority producers
### Describe the bug

Due to the current implementation, if the logging thread is configured with a higher priority than other threads that produce log messages at a lower priority, there is a possibility that the logging thread can starve those lower-priority threads indefinitely.

In some scenarios, users may have expensive tasks that take a considerable amount of time to execute. In such cases, it is reasonable to increase the priority of the logging thread in order to observe log messages while those tasks are running.

It is important to note that this issue can only occur when there are also **higher-priority threads producing log messages**. The following scenario illustrates the problem.

* P(A) < P(L) < P(B)
* L is the logging thread
___

* **Thread A**
  Calls `z_log_msg_enqueue()` and reaches `msg_alloc()`, but is interrupted by Thread B, which has higher priority. The message has not yet been committed.

* **Thread B**
  Preempts Thread A, calls `z_log_msg_enqueue()`, and reaches `msg_commit()`, causing `z_log_msg_post_finalize()` to be called.

* **Thread L**
  Calls `z_impl_log_process()` and attempts to claim Thread A’s message. Since the message has not yet been committed, `z_log_msg_claim()` returns `NULL`.
  Next, `z_log_msg_pending()` is called and returns `true` because the message is still present in the buffer but not committed. At this point, an endless loop begins.

* **Thread L (repeats)**
  Calls `z_impl_log_process()` again, attempts to claim Thread A’s message, receives `NULL` from `z_log_msg_claim()`, and `z_log_msg_pending()` continues to return `true`.

* **And so on…**

---

From this point onward, the logging thread becomes stuck in a tight loop and prevents lower-priority threads from ever being scheduled, resulting in indefinite starvation.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Create a sample application with two log-producing threads: one running at a higher priority than the logging thread and one running at a lower priority. During execution, the logging thread eventually becomes stuck in an infinite loop.

### Relevant log output

```shell

```

### Impact

Intermittent – Occurs occasionally; hard to reproduce.

### Environment

N/A

### Additional Context

This problem was already reported in the following discussion #68289

### PR DESCRIPTION
**Pull request by lromeraj**
Fix a scenario where the logging thread can enter an infinite loop and starve lower-priority threads when encountering an uncommitted log message.

If a lower-priority thread is preempted before committing a log message, and a higher-priority thread triggers log processing, the logging thread may repeatedly attempt to claim the uncommitted message. Since the message is still pending but not committed, `z_log_msg_claim()` returns NULL while `z_log_msg_pending()` remains true, resulting in a livelock.

Update the log processing logic to avoid looping indefinitely on uncommitted messages, ensuring that lower-priority threads can resume and complete message allocation and commit.

Fixes #101401

### CODE REVIEW

**Review by nordic-krch — APPROVED** [review]

**Comment by lromeraj** [comment]
@nordic-krch @dcpleung Would it be possible to backport this to at least the `v4.3-branch`?

File: subsys/logging/log_core.c [hunk 1]
```diff
@@ -605,7 +605,7 @@ bool z_impl_log_process(void)
 		last_failure_report += CONFIG_LOG_FAILURE_REPORT_PERIOD;
 	}
 
-	return z_log_msg_pending();
+	return msg != NULL && z_log_msg_pending();
```
Comment (lromeraj) [inline subsys/logging/log_core.c:608]: @nordic-krch Do you think it would be helpful to add a comment here to clarify this condition?

Comment (nordic-krch) [reply subsys/logging/log_core.c:608]: it's fine.

**Comment by nordic-krch** [comment]
@lromeraj you need to fix the Sign-off in the commit message.

**Comment by lromeraj** [comment]
> @lromeraj you need to fix the Sign-off in the commit message.

@nordic-krch Done

**Review by dcpleung — APPROVED** [review]

**Comment by lromeraj** [comment]
@nordic-krch Who will approve the workflow to run, and when should we expect it to be approved?

**Comment by lromeraj** [comment]
@nordic-krch Do you know why this is failing now? I believe the commit signature is correct at this point.

**Review by nashif — APPROVED** [review]
