### PR TITLE
ethernet: eth_stellaris: data_len should not include header size

### LINKED ISSUE #13943: net: QEMU Ethernet drivers are flaky (seemingly after "net_buf" refactor)
Testing 3 qemu ethernet drivers we added in 1.14 timeframe with the idea to use them to test the IP stack better.

master: e731bdc81a3b2e2fdf498bccab9627b18fa38de6
sample: samples/net/sockets/dumb_http_server
test command on host: ab -n1000 http://192.0.2.1:8080/

1. BOARD=qemu_x86 OVERLAY=overlay-e1000.conf
Not a single request succeeds:
~~~
$ ab -n1000 http://192.0.2.1:8080/
...
Benchmarking 192.0.2.1 (be patient)
apr_socket_recv: Connection reset by peer (104)
~~~

On Zephyr console (after ~5 `ab` attempts):

~~~
Booting from ROM..***** Booting Zephyr OS zephyr-v1.13.0-5221-g8ecd348022f9 *****
[00:00:00.019,243] <inf> net_config: Initializing network
[00:00:00.021,990] <inf> net_config: IPv4 address: 192.0.2.1
Single-threaded dumb HTTP server waits for a connection on port 8080...
[00:00:59.445,932] <err> eth_e1000: Out of memory for received frame
~~~

2. BOARD=mps2_an385 OVERLAY=overlay-smsc911x.conf
Zephyr:
~~~
Connection #137 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #138 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #139 from 192.0.2.2
Connection from 192.0.2.2 closed
Connection #140 from 192.0.2.2
...(lockup, pings don't work)...
~~~

3. BOARD=qemu_cortex_m3 OVERLAY=overlay-qemu_cortex_m3_eth.conf
Build error:
~~~
[ 54%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/ethernet/eth_stellaris.c.obj
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/drivers/ethernet/eth_stellaris.c: In function 'eth_stellaris_stats':
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/drivers/ethernet/eth_stellaris.c:291:24: error: 'struct eth_stellaris_runtime' has no member named 'stats'
  return &(DEV_DATA(dev)->stats);
                        ^~
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/drivers/ethernet/eth_stellaris.c: At top level:
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/drivers/ethernet/eth_stellaris.c:349:2: error: unknown field 'get_stats' specified in initializer
  .get_stats = eth_stellaris_stats,
  ^
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/drivers/ethernet/eth_stellaris.c:349:15: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .get_stats = eth_stellaris_stats,
               ^~~~~~~~~~~~~~~~~~~
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/drivers/ethernet/eth_stellaris.c:349:15: note: (near initialization for 'eth_stellaris_apis.start')
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/drivers/ethernet/eth_stellaris.c: In function 'eth_stellaris_stats':
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/zephyr/drivers/ethernet/eth_stellaris.c:292:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
~~~

### PR DESCRIPTION
**Pull request by bravegnu**
As part of the ll_reserve refactoring effort, the packet length now
includes header size as well. Before the refactor, when the packet
length was written to the device, it did not include the header size,
which is the required value as per the LM3S6965 datasheet. After the
refactor the packet length includes the header size as well. The
header size has to subtracted from the packet length before writing to
the device.

Fixes #13943

Signed-off-by: Vijay Kumar B. <vijaykumar@zilogic.com>

### CODE REVIEW

**Comment by bravegnu** [comment]
Fixes issue with Stellaris Ethernet driver reported in #13943

File: drivers/ethernet/eth_stellaris.c [hunk 1]
```diff
@@ -65,10 +67,11 @@ static int eth_stellaris_send(struct device *dev, struct net_pkt *pkt)
...
 
 	/* Frame transmission
-	 * First two bytes are data_len for frame,
-	 * Initially send the data_len
+	 *
+	 * First two bytes is the length of the frame, exclusive of
+	 * the header length.
 	 */
-	data_len = net_pkt_get_len(pkt);
+	data_len = net_pkt_get_len(pkt) - HEADER_LEN;
```
Comment (jukkar) [inline drivers/ethernet/eth_stellaris.c]: Better would be `data_len = net_pkt_get_len(pkt) - sizeof(struct net_eth_hdr)`

File: drivers/ethernet/eth_stellaris.c [hunk 2]
```diff
@@ -18,6 +18,8 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME);
 #include <ethernet/eth_stats.h>
```
Comment (jukkar) [inline drivers/ethernet/eth_stellaris.c]: Please add `Fixes #13943` line to commit message.

**Review by jukkar — CHANGES_REQUESTED** [review]

File: drivers/ethernet/eth_stellaris.c (hunk 1 above)
Comment (bravegnu) [reply drivers/ethernet/eth_stellaris.c]: OK, fixed.

**Review by jukkar — APPROVED** [review]

**Review by nashif — APPROVED** [review]
