### PR TITLE
net: sockets: socketpair: fix socketpair coverity issues

### LINKED ISSUE #25727: [Coverity CID :210611] Logically dead code in subsys/net/lib/sockets/socketpair.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/subsys/net/lib/sockets/socketpair.c#L482

Category: Control flow issues
Function: `spair_write`
Component: Networking
CID: [210611](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210611)

Details:

```
476                     goto out;
477                 }
478    
479                 res = k_sem_take(&remote->sem, K_NO_WAIT);
480                 if (res < 0) {
481                     if (is_nonblock) {
>>>     CID 210611:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "*__errno_location() = -res;".
482                         errno = -res;
483                         res = -1;
484                         goto out;
485                     }
486                     res = k_sem_take(&remote->sem, K_FOREVER);
487                     if (res < 0) {
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #25731: [Coverity CID :210568] Argument cannot be negative in tests/net/socket/socketpair/src/test_socketpair_happy_path.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/tests/net/socket/socketpair/src/test_socketpair_happy_path.c

Category: Error handling issues
Function: `happy_path`
Component: Tests
CID: [210568](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210568)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #25736: [Coverity CID :210583] Unchecked return value from library in samples/net/sockets/socketpair/src/socketpair_example.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/samples/net/sockets/socketpair/src/socketpair_example.c

Category: Error handling issues
Function: `hello`
Component: Samples
CID: [210583](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210583)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #25737: [Coverity CID :210585] Unchecked return value in samples/net/sockets/socketpair/src/socketpair_example.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/samples/net/sockets/socketpair/src/socketpair_example.c

Category: Error handling issues
Function: `zephyr_app_main`
Component: Samples
CID: [210585](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210585)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #25780: [Coverity CID :210612] Negative array index read in samples/net/sockets/socketpair/src/socketpair_example.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/samples/net/sockets/socketpair/src/socketpair_example.c#L155

Category: Memory - illegal accesses
Function: `zephyr_app_main`
Component: Samples
CID: [210612](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210612)

Details:

```
149                 if ((fds[i].revents & POLLERR) != 0) {
150                     printf("fd: %d: error\n", fd);
151                 }
152    
153                 if ((fds[i].revents & POLLHUP) != 0) {
154                     printf("fd: %d: hung up\n", fd);
>>>     CID 210612:  Memory - illegal accesses  (NEGATIVE_RETURNS)
>>>     Using variable "idx" as an index to array "ctx".
155                     close(ctx[idx].spair[0]);
156                     printf("main: closed fd %d\n",
157                         ctx[idx].spair[0]);
158                     pthread_join(ctx[idx].thread, &unused);
159                     printf("joined %s\n", ctx[idx].name);
160                     ctx[idx].spair[0] = -1;
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #25788: [Coverity CID :210581] Dereference before null check in subsys/net/lib/sockets/socketpair.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/subsys/net/lib/sockets/socketpair.c

Category: Null pointer dereferences
Function: `spair_sendmsg`
Component: Networking
CID: [210581](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210581)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #25793: [Coverity CID :210561] Resource leak in tests/net/socket/socketpair/src/test_socketpair_unsupported_calls.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/tests/net/socket/socketpair/src/test_socketpair_unsupported_calls.c

Category: Resource leaks
Function: `test_socketpair_unsupported_calls`
Component: Tests
CID: [210561](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210561)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #25797: [Coverity CID :210607] Uninitialized scalar variable in tests/net/socket/socketpair/src/test_socketpair_happy_path.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/tests/net/socket/socketpair/src/test_socketpair_happy_path.c#L139

Category: Uninitialized variables
Function: `happy_path`
Component: Tests
CID: [210607](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210607)

Details:

```
133    
134             msghdr.msg_iov = &iovec;
135             msghdr.msg_iovlen = 1;
136             iovec.iov_base = (void *)expected_msg;
137             iovec.iov_len = expected_msg_len;
138    
>>>     CID 210607:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized value "msghdr". Field "msghdr.msg_name" is uninitialized when calling "sendmsg". [Note: The source code implementation of the function has been overridden by a builtin model.]
139             res = sendmsg(sv[i], &msghdr, 0);
140    
141             zassert_not_equal(res, -1, "sendmsg(2) failed: %d", errno);
142             actual_msg_len = res;
143             zassert_equal(actual_msg_len, expected_msg_len,
144                       "did not sendmsg entire message");
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by cfriedt**
I have no permissions to access the actual errors on coverity.com (error 401), but please let me know if this helps.

Fixes #25793
Fixes #25788
Fixes #25780
Fixes #25737
Fixes #25731 
Fixes #25736 
Fixes #25727 
Fixes #25797

### CODE REVIEW

**Review by jukkar — CHANGES_REQUESTED** [review]
Thanks for the fixes, they look good. We usually add the Coverity CID information to commits that fix these things.
Could you add to each commit this line before/after the "Fixes" line:
```
Coverity-CID: xxxx
```
so that we can find from git log whether a certain Coverity issue was fixed or not.

**Comment by cfriedt** [comment]
Should be good now. Does Coverity mention when a problem is fixed on GitHub? I'll keep an eye on it in any case.

**Comment by cfriedt** [comment]
@jukkar - should be good to go

**Comment by carlescufi** [comment]
> @pfalcon, @jukkar, @tbursztyka, @carlescufi - should be good to go

Thanks! waiting for the reviewers above to approve

**Review by jukkar — APPROVED** [review]

File: subsys/net/lib/sockets/socketpair.c [hunk 1]
```diff
@@ -476,19 +476,11 @@ static ssize_t spair_write(void *obj, const void *buffer, size_t count)
 				goto out;
 			}
 
-			res = k_sem_take(&remote->sem, K_NO_WAIT);
+			res = k_sem_take(&remote->sem, K_FOREVER);
```
Comment (pfalcon) [inline subsys/net/lib/sockets/socketpair.c:479]: It's Coverity in its case 210611 said that K_NO_WAIT here needs to be replaced in K_FOREVER, and called it all "dead code"? That seems want the commit message suggests, or I don't understand it.

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c [hunk 2]
```diff
@@ -115,10 +115,12 @@ static void happy_path(
 
 		memset(actual_msg, 0, sizeof(actual_msg));
 
+		len = 0;
 		res = recvfrom(sv[(!i) & 1], actual_msg, sizeof(actual_msg), 0,
 			NULL, &len);
 
 		zassert_not_equal(res, -1, "recvfrom(2) failed: %d", errno);
+		zassert_true(res >= 0, "recvfrom must return >= -1: %d", res);
```
Comment (stephanosio) [inline tests/net/socket/socketpair/src/test_socketpair_happy_path.c:123]:
```suggestion
		zassert_true(res >= 0, "recvfrom must return >= 0: %d", res);
```

File: subsys/net/lib/sockets/socketpair.c (hunk 1 above)
Comment (pabigot) [reply subsys/net/lib/sockets/socketpair.c:479]: Yeah, I'm not convinced this is right.  Coverity analyzed a path where this would be reached in a condition where `is_nonblock` is false (because if it wasn't it'd have jumped to `out`).  In that case the "check-no-wait, if fail check other things and if not fail wait forever" reduces to "wait forever".  I don't believe that path is the only path that reaches this point, and in others `is_nonblock` would be true.

I'd try removing that by factoring out the no-wait/check/wait-forever sequence, which appears at least twice in this function, to a separate function.  And I'd do that in a separate PR because it's messy.

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c [hunk 3]
```diff
@@ -119,6 +119,7 @@ static void happy_path(
 			NULL, &len);
 
 		zassert_not_equal(res, -1, "recvfrom(2) failed: %d", errno);
```
Comment (pabigot) [inline tests/net/socket/socketpair/src/test_socketpair_happy_path.c:122]: The original isn't quite redundant with the new check, but do you need both?  Why was `-1` special before?

Also: This can't be 210568, which is "Argument cannot be negative"

File: samples/net/sockets/socketpair/src/socketpair_example.c [hunk 4]
```diff
@@ -47,7 +47,12 @@ static const char *const names[] = {
 static void hello(int fd, const char *name)
 {
 	/* write(2) should be used after #25443 */
-	send(fd, name, strlen(name), 0);
+	int res = send(fd, name, strlen(name), 0);
```
Comment (pabigot) [inline samples/net/sockets/socketpair/src/socketpair_example.c:51]: This checks the return value as Coverity wants, but it's not a good example IMO because surely the failure should be returned to the caller and checked there.

Not blocking, net maintainers should weigh in.

File: samples/net/sockets/socketpair/src/socketpair_example.c [hunk 5]
```diff
@@ -110,8 +111,10 @@ int main(int argc, char *argv[])
 
 	for (i = 0; i < ARRAY_SIZE(ctx); ++i) {
 		ctx[i].name = (char *)names[i];
-		socketpair(AF_UNIX, SOCK_STREAM, 0, ctx[i].spair);
-		pthread_create(&ctx[i].thread, NULL, fun, &ctx[i]);
+		r = socketpair(AF_UNIX, SOCK_STREAM, 0, ctx[i].spair);
+		assert(r == 0);
```
Comment (pabigot) [inline samples/net/sockets/socketpair/src/socketpair_example.c:115]: This should probably be `__ASSERT_NO_MSG()`, which is the Zephyr way of doing this.

File: samples/net/sockets/socketpair/src/socketpair_example.c [hunk 6]
```diff
@@ -144,6 +144,10 @@ int main(int argc, char *argv[])
 
 			fd = fds[i].fd;
 			idx = fd_to_idx(fd, ctx, ARRAY_SIZE(ctx));
+			if (idx < 0) {
```
Comment (pabigot) [inline samples/net/sockets/socketpair/src/socketpair_example.c:147]: This might be 210612.  It's not 210585.

File: tests/net/socket/socketpair/src/test_socketpair_unsupported_calls.c [hunk 7]
```diff
@@ -58,6 +58,9 @@ void test_socketpair_unsupported_calls(void)
 			"listen should set errno to EINVAL");
 
 		res = accept(sv[i], (struct sockaddr *)&addr, &len);
```
Comment (pabigot) [inline tests/net/socket/socketpair/src/test_socketpair_unsupported_calls.c:60]: IMO we don't need to do this; it's test code, and if the accept() didn't fail it's fine to leak the descriptor.

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c [hunk 8]
```diff
@@ -115,6 +115,7 @@ static void happy_path(
 
 		memset(actual_msg, 0, sizeof(actual_msg));
 
+		len = 0;
```
Comment (pabigot) [inline tests/net/socket/socketpair/src/test_socketpair_happy_path.c:118]: A better fix would be to initialize the variable at its declaration up on line 48, as Coverity notes:
```
   	14. var_decl: Declaring variable len without initializer.
 48        socklen_t len;
```

**Review by pabigot — CHANGES_REQUESTED** [review]
Some of the associations between changes and Coverity IDs don't make sense.  Other comments need changes too; I think the ones that are optional note that.

**Comment by pfalcon** [comment]
> Some of the associations between changes and Coverity IDs don't make sense. Other comments need changes too; I think the ones that are optional note that.

Well, my primary attention is to the changes outside tests/ and samples/. Changes to those can be treated in more or less lax way, but for changes to the system functional code, would be nice to have clear and detailed commit messages.

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c (hunk 2 above)
Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:123]: Technically it can return -1 if there is an error. It should never return -2 etc though

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 5 above)
Comment (cfriedt) [reply samples/net/sockets/socketpair/src/socketpair_example.c:115]: Yeah, that won't work for the Makefile.posix way of building though.

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 6 above)
Comment (cfriedt) [reply samples/net/sockets/socketpair/src/socketpair_example.c:147]: I'll have another look soon.

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c (hunk 8 above)
Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:118]: Ah, ok. It is a loop though, so it should be initialized twice (once for each of the two iterations) before passing by reference.

File: tests/net/socket/socketpair/src/test_socketpair_unsupported_calls.c (hunk 7 above)
Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_unsupported_calls.c:60]: Ok. I wasn't sure if it was mandatory. Will have a look again soon

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c (hunk 3 above)
Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:122]: I'll have another look again shortly

File: subsys/net/lib/sockets/socketpair.c (hunk 1 above)
Comment (cfriedt) [reply subsys/net/lib/sockets/socketpair.c:479]: It's a bit confusing. I'll have another look soon

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c (hunk 8 above)
Comment (pabigot) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:118]: No; it's actually not used at all, because `src_addr` is NULL.  But Coverity doesn't know that, so we need to give it a value just once.

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 5 above)
Comment (pabigot) [reply samples/net/sockets/socketpair/src/socketpair_example.c:115]: Why not?  There are uses of Zephyr `__ASSERT()` in lib/posix.

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c (hunk 2 above)
Comment (stephanosio) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:123]: I thought you put `res >= 0` because you have `zassert_not_equal(res, -1, ...)` right above i.t

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 5 above)
Comment (cfriedt) [reply samples/net/sockets/socketpair/src/socketpair_example.c:115]: @pabigot, Makefile.posix is for running this sample code entirely without Zephyr as a native Linux (or BSD, or macOS) application. I.e. lib/posix is nonexistent.

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 6 above)
Comment (cfriedt) [reply samples/net/sockets/socketpair/src/socketpair_example.c:147]: Absolutely right. Thanks for catching that.

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 5 above)
Comment (cfriedt) [reply samples/net/sockets/socketpair/src/socketpair_example.c:115]: A possible alternative solution that doesn't use any asserts is to just use a goto to go to the end of the function. There is no resource cleanup, but again, it's just a sample application to illustrate usage.

Comment (pabigot) [reply samples/net/sockets/socketpair/src/socketpair_example.c:115]: Or, if you really don't care, use `(void)socketpair(...)`.

File: subsys/net/lib/sockets/socketpair.c (hunk 1 above)
Comment (cfriedt) [reply subsys/net/lib/sockets/socketpair.c:479]: @pabigot, @pfalcon - I think Coverity might actually be right in this case.

So the conditions that get is until this loop are 
1. `is_nonblock == false` (i.e. we *may* block)
1. `avail == 0` (i.e. no space to write, so we *will* block, hence `will_block == true`).

So for all intents and purposes, we are legitimately allowed to 
* wait for a signal on `&remote->read_signal` (which blocks)
* attempt to pull up the file object pointed to by the (integer) remote fd (which might be NULL, if it was deleted from under our noses)
* attempt to take a semaphore (which could take forever since we *may* block and in fact we *expect* to block)

If `avail > 0`, `will_block` is false, and a write will occur immediately (regardless of the value of `is_nonblock`), then we do not go into the loop.

However, there is a ticket open for a scenario that I had not initially checked for - which would be reading to or writing from a socket in ISR context (it sounds comical, but someone _might_ actually try to do that and doing so should always fail if the socket is blocking). That is issue #25417 which I'll get to when we're done here.

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c (hunk 8 above)
Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:118]: Except Coverity doesn't get that 😭 You & I do, of course. Reinitializing `len` before the function is called is technically more correct-ish, should mitigate the Coverity issue, and that's all I really care about.

File: tests/net/socket/socketpair/src/test_socketpair_happy_path.c (hunk 3 above)
Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:122]: The assert message is different. In the `!= -1` case, we print `errno`, and in the `>= -1` case, we're checking for valid range of the return. I could add comments to that effect if you think it's more clear.

Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:122]: @pabigot - It is actually 201568. The issue is that the length argument to `strncmp()` cannot be negative because it's implicitly cast to `size_t`. So, the additional assertion is there to specifically prevent that corner case).
If you prefer, I can combine the two assertions to check for `>= 0' and also print `errno`.

Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_happy_path.c:122]: The 80-character limit only leaves so much room for messages unfortunately. In Linux 100 is the new limit ;-)

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 5 above)
Comment (cfriedt) [reply samples/net/sockets/socketpair/src/socketpair_example.c:115]: I should probably care. Just remembered that `pthread_create()` requires a `pthread_attr_t` in Zephyr, so that needs to be modified anyway.

File: subsys/net/lib/sockets/socketpair.c (hunk 1 above)
Comment (pfalcon) [reply subsys/net/lib/sockets/socketpair.c:479]: @cfriedt: My concern, as I mentioned, is to have clear enough and detailed enough commit description. That's how I review stuff - read commit description, and compare with what code changes actually do. Any discrepancies aren't helpful. (And this review may happen now or in a year, when investigating some (un)related issue.)

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 5 above)
Comment (pfalcon) [reply samples/net/sockets/socketpair/src/socketpair_example.c:115]: I think assert() is fine here, and @cfriedt, thanks for providing Makefile.posix - that's the way we can ensure that we actually implement POSIX API portable across OSes. (Maybe one sweet day we'll be able to do the same for tests, but examples with Makefile.posix are the baseline to stick to.)

Comment (pfalcon) [reply samples/net/sockets/socketpair/src/socketpair_example.c:115]: @cfriedt: Also, FYI (not just for this code piece, but in general), there's an option of marking Coverity case as false positive. I myself don't remember practicing it much, but see e.g. @jukkar practicing it regularly (no implications meant). So, if somewhere your code is correct, but Coverity doesn't get it, you can comment on the initial ticket that it's a false positive (someone would need to propagate that back to Coverity UI).

File: tests/net/socket/socketpair/src/test_socketpair_unsupported_calls.c (hunk 7 above)
Comment (cfriedt) [reply tests/net/socket/socketpair/src/test_socketpair_unsupported_calls.c:60]: dropped the commit

File: samples/net/sockets/socketpair/src/socketpair_example.c (hunk 4 above)
Comment (cfriedt) [reply samples/net/sockets/socketpair/src/socketpair_example.c:61]: Since it's sample code, I'm mostly impartial here. I just thought it would might be useful to print an error message to notify the user who would, presumably, be watching.

**Comment by cfriedt** [comment]
> > Some of the associations between changes and Coverity IDs don't make sense. Other comments need changes too; I think the ones that are optional note that.
> 
> Well, my primary attention is to the changes outside tests/ and samples/. Changes to those can be treated in more or less lax way, but for changes to the system functional code, would be nice to have clear and detailed commit messages.

@pabigot, @pfalcon - I believe most of your concerns should be addressed. If there is anything else, please let me know.

File: subsys/net/lib/sockets/socketpair.c (hunk 1 above)
Comment (cfriedt) [reply subsys/net/lib/sockets/socketpair.c:479]: @pfalcon - commit message has been updated.

**Review by pabigot — APPROVED** [review]
