### PR TITLE
drivers: spi: stm32: Fix forever lock when configure failed

### LINKED ISSUE #38621: Drivers: spi: stm32: Transceive lock forever
**Describe the bug**
Transceive function lock forever when the SPI configuration failed

**To Reproduce**
A SPI device with a wrong baudrate must be set. For example
```
&spi1 {
	status = "okay";
	lmp90100: lmp90100@0 {
		compatible = "ti,lmp90100";
		reg = <0x0>;
		spi-max-frequency = <10>;
		....		
	};
};
```
The first transceive failed with: `Unsupported frequency 10Hz, max 8000000Hz, min 62500Hz`
The next transceive lock forever

### PR DESCRIPTION
**Pull request by jdascenzio**
On transceive, if the SPI configure failed, the SPI wasn't release.

Fixes #38621

### CODE REVIEW

**Comment by erwango** [comment]
@jdascenzio Would you mind creating and issue so the PR can be merged once approved?
(since we're in release stabilization period)

**Comment by jdascenzio** [comment]
> @jdascenzio Would you mind creating and issue so the PR can be merged once approved?
> (since we're in release stabilization period)

I created the issue: #38621

File: drivers/spi/spi_ll_stm32.c [hunk 1]
```diff
@@ -613,6 +613,7 @@ static int transceive(const struct device *dev,
 
 	ret = spi_stm32_configure(dev, config);
 	if (ret) {
+		spi_context_release(&data->ctx, ret);
```
Comment (erwango) [inline drivers/spi/spi_ll_stm32.c:616]: As `spi_context_release` is inlined, please use a goto instruction to avoid code increase.
Apply to the other case as well

**Review by erwango — CHANGES_REQUESTED** [review]

**Review by erwango — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

File: drivers/spi/spi_ll_stm32.c [hunk 2]
```diff
@@ -711,7 +712,7 @@ static int transceive_dma(const struct device *dev,
 
 	ret = spi_stm32_configure(dev, config);
 	if (ret != 0) {
-		return ret;
+		goto end;
```
Comment (FRASTM) [inline drivers/spi/spi_ll_stm32.c:715]: should also take this opportunity to align code ?
`	if (ret != 0) {`
vs
`	if (ret) {`

**Review by FRASTM — APPROVED** [review]
