### PR TITLE
Drivers: Counter: Added flag for counting up

### LINKED ISSUE #76785: timer_tmr_cmsdk_apb.c and timer_stmr_cmsdk_apb.c are missing counting up flag.
**Describe the bug**
Counter is counting up, but the counter_is_counting_up returns false, because of the missing flag.

**Expected behavior**
counter_is_counting_up should return true.

**Impact**
Every test that is running with --integration and tests this behavior will fail.

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

Counters are counting up, but do not have the COUNTER_CONFIG_INFO_COUNT_UP flag set.
OS: Linux, ms2_an835 on QEMU
Commit: eb35143, it's still on main

### PR DESCRIPTION
**Pull request by CZKikin**
Tmr and dtmr drivers were missing a flag which tells the counter_is_conting_up function that the counter is counting up. So I've added the flag

Fixes: #76785

### CODE REVIEW

**Comment by CZKikin** [comment]
Fixes #76785

File: drivers/counter/timer_dtmr_cmsdk_apb.c [hunk 1]
```diff
@@ -179,6 +179,7 @@ static int dtmr_cmsdk_apb_init(const struct device *dev)
 			.freq = 24000000U,				\
 			.flags = 0,					\
 			.channels = 0U,					\
+			.flags = COUNTER_CONFIG_INFO_COUNT_UP,		\
```
Comment (hakehuang) [inline drivers/counter/timer_dtmr_cmsdk_apb.c:182]: there is flags in line 180

File: drivers/counter/timer_tmr_cmsdk_apb.c [hunk 2]
```diff
@@ -175,6 +175,7 @@ static int tmr_cmsdk_apb_init(const struct device *dev)
 			.freq = 24000000U,				\
 			.flags = 0,					\
 			.channels = 0U,					\
+			.flags = COUNTER_CONFIG_INFO_COUNT_UP,		\
```
Comment (hakehuang) [inline drivers/counter/timer_tmr_cmsdk_apb.c:178]: already has flags in 176

**Comment by hakehuang** [comment]
the default is setting the counter to counting down by design, what is your test application and command line?

**Review by hakehuang — CHANGES_REQUESTED** [review]

**Comment by CZKikin** [comment]
@hakehuang 
obrazek
obrazek
I simply loop over the counter and print out the values. The counter is counting up. Iam letting it run in a ztest, there's no special configuration added.

**Comment by hakehuang** [comment]
> I simply loop over the counter and print out the values. The counter is counting up. Iam letting it run in a ztest, there's no special configuration added.

so set to count down is not supported, as the old setting?

**Review by hakehuang — COMMENTED** [review]
the clang format check issue I did not see it last time, what do yo changed?

**Comment by CZKikin** [comment]
> > I simply loop over the counter and print out the values. The counter is counting up. Iam letting it run in a ztest, there's no special configuration added.
> 
> so set to count down is not supported, as the old setting?

No, the counters are counting up, but there's a missing flag so the `counter_is_counting_up` function returns false.


> the clang format check issue I did not see it last time, what do yo changed?

I'll look at it.

**Comment by CZKikin** [comment]
> the clang format check issue I did not see it last time, what do yo changed?

I ran those files through clang-format and it did more than i thought... but the only change that matters s the one with flags.

**Comment by hakehuang** [comment]
> No, the counters are counting up, but there's a missing flag so the `counter_is_counting_up` function returns false.

I mean, if the counter can only count up, this setting shall be fixed in driver better by dts. Setting flags means it can UP/DOWN, can you clarify?

**Comment by CZKikin** [comment]
> > No, the counters are counting up, but there's a missing flag so the `counter_is_counting_up` function returns false.
> 
> I mean, if the counter can only count up, this setting shall be fixed in driver better by dts. Setting flags means it can UP/DOWN, can you clarify?

I did not find a way to configure the counter to count down. I think it was a typo. CI would not show this error because most of the testcases are skipped, and the PR draft here: #76527 would add a testcase that would catch this behavior.

**Comment by CZKikin** [comment]
Ok regarding [documentation](https://developer.arm.com/documentation/101107/0000/Programmers-model/Base-element/CMSDK-dual-timer?lang=en) the dtmr should count down. I've ran the tests and it fails. If I print out the counted values, the counter is still counting up. Either there's a problem with qemu or the counter is counting so fast the prints look like its counting up or it is counting up. For now i've removed the dtmr from PR, but i think that it should too have this flag.
obrazek

**Comment by hakehuang** [comment]
@ithinuel  do you known why the arm_cmsdk_timer and arm_cmsdk_dtimer are actually count up but spec says it is count down?

**Comment by ithinuel** [comment]
@hakehuang [`tmr_cmsdk_apb_get_value`](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/counter/timer_tmr_cmsdk_apb.c#L70-L71) does `load - value` so `counter_get_value` will return a value going up.

**Review by ithinuel — CHANGES_REQUESTED** [review]
Most of the changes here seem to be formatting related.

Would you mind either separating them as two commits or limiting the changes to the flag addition please?

**Comment by hakehuang** [comment]
LGTM, the format issue is not introduced by this PR, but enhanced CI check.

**Review by hakehuang — APPROVED** [review]
LGTM

**Review by ithinuel — APPROVED** [review]

**Comment by CZKikin** [comment]
@nordic-krch Can you confirm, that this is ok?

**Review by nordic-krch — APPROVED** [review]
