### PR TITLE
drivers: flash: stm32: Use correct driver compatible

### LINKED ISSUE #23997: flash sector erase fails on stm32l475
**Describe the bug**

 I am facing a similary problem with my disco_l475_iot1 board which has stm32l475 MCU. I am using mcuboot for updatehub app. I am not able to erase flash memory partition.

What have you tried to diagnose or workaround this issue?

flash_write_protection_set() works fine but flash_erase() inside mcuboot.c is not successful.
 I checked carefully all the partition sizes they are perfectly according to DTS file. Now I tried to see OPTCR register but could not find it.
Additionally I tried flash_shell app from zephyr to see if the erase is successful. but it also generated the problem with error code -5.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=disco_l475_iot1
3. make

**Expected behavior**

I should see successful erase and the method flash_erase should return 0 on successful return.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

I am working with updatehub app but not able to achieve that because of this error.

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

**Environment (please complete the following information):**
 - OS: (e.g. Linux,)
 - Toolchain (e.g Zephyr 2.2.99, SDK,0.11.2.)
 - commit- 1c79096559f5b95f7153cd6784459734c8bb76b9

**Additional context**

### PR DESCRIPTION
**Pull request by ABOSTM**
drivers: flash: stm32: Use correct driver compatible

Use valid stm32 flash driver compatibles instead of flash
area compatible.
For 'write_block_size' property, use reference to soc-nv-flash.

fixes #23997

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by nandojve** [comment]
@mtahirbutt @otavio

**Comment by rckTom** [comment]
This PR also fixes #24098, a cpu fault in flash_stm32_write_protection.

File: drivers/flash/flash_stm32.c [hunk 1]
```diff
@@ -6,10 +6,29 @@
...
+#define DT_DRV_COMPAT st_stm32f7_flash_controller
+#elif DT_HAS_NODE(DT_INST(0, st_stm32g0_flash_controller))
+#define DT_DRV_COMPAT st_stm32g0_flash_controller
+#elif DT_HAS_NODE(DT_INST(0, st_stm32g4_flash_controller))
+#define DT_DRV_COMPAT st_stm32g4_flash_controller
+#elif DT_HAS_NODE(DT_INST(0, st_stm32l4_flash_controller))
+#define DT_DRV_COMPAT st_stm32l4_flash_controller
+#elif DT_HAS_NODE(DT_INST(0, st_stm32wb_flash_controller))
+#define DT_DRV_COMPAT st_stm32wb_flash_controller
+#endif /* DT_HAS_NODE(DT_INST(0, st_stm32xx_flash_controller)) */
```
Comment (erwango) [inline drivers/flash/flash_stm32.c:30]: Would be nice to use a STM32 generic compatible along with the soc series specific ones to avoid this.
I've submitted https://github.com/zephyrproject-rtos/zephyr/issues/24113 for this purpose

**Review by erwango — APPROVED** [review]
