### PR TITLE
Fix CoAP coverity issues

### LINKED ISSUE #20880: [Coverity CID :205780] Integer handling issues in tests/net/lib/coap/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/net/lib/coap/src/main.c

Category: Integer handling issues
Function: `test_block1_response`
Component: Tests
CID: 205780

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20881: [Coverity CID :205786] Integer handling issues in tests/net/lib/coap/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/net/lib/coap/src/main.c

Category: Integer handling issues
Function: `test_block2_request`
Component: Tests
CID: 205786

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20882: [Coverity CID :205806] Integer handling issues in tests/net/lib/coap/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/net/lib/coap/src/main.c

Category: Integer handling issues
Function: `test_block1_request`
Component: Tests
CID: 205806

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20883: [Coverity CID :205808] Integer handling issues in tests/net/lib/coap/src/main.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/tests/net/lib/coap/src/main.c

Category: Integer handling issues
Function: `test_block2_response`
Component: Tests
CID: 205808

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### PR DESCRIPTION
**Pull request by rveerama1**
Fix unintended sign extension (SIGN_EXTENSION).

The result of "coap_block_size_to_bytes() * iter"
extending the sign type.

current variable from struct coap_block_context is size_t.
So store the result in current_block which is size_t
defined and compare it.

Fixes #20880
Fixes #20881
Fixes #20882
Fixes #20883

Coverity CID :205780
Coverity CID :205786
Coverity CID :205806
Coverity CID :205808

### CODE REVIEW

File: tests/net/lib/coap/src/main.c [hunk 1]
```diff
@@ -718,16 +719,18 @@ static int test_block1_request(struct coap_block_context *req_ctx, u8_t iter)
 
 	/* In last iteration "current" field not updated */
 	if (iter < 4) {
-		if (req_ctx->current !=
-		    coap_block_size_to_bytes(COAP_BLOCK_32) * iter) {
+		current_block = coap_block_size_to_bytes(COAP_BLOCK_32) * iter;
+
```
Comment (tbursztyka) [inline tests/net/lib/coap/src/main.c]: you could avoid the empty line before the if since if conditional statement is testing current_block (as everywhere below as well)

Comment (rveerama1) [reply tests/net/lib/coap/src/main.c]: ok

Comment (rveerama1) [reply tests/net/lib/coap/src/main.c]: Done. updated the PR.

**Review by tbursztyka — APPROVED** [review]

**Comment by rveerama1** [comment]
> FYI: It's not the `* iter` that's a problem (Coverity didn't complain about line 722), it's the conversion of `iter` from `u8_t` to `int` because it's an unsigned operand in an binary subtraction with `1` which is a signed operand with higher conversion rank (`int`). If you change the original to `(iter - 1U)` it should be fine because both operands are unsigned.

Thank you, I will update it.

**Review by nashif — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
