### PR TITLE
soc: nrf: basic power management for nrf53 and nrf91

### LINKED ISSUE #21318: CONFIG_SYS_POWER_MANAGEMENT Makes Build Fail for nRF5340 and nRF9160
The current implementation of `zephyr/subsys/power/device.c` breaks because of the following:

```
#if defined(CONFIG_SYS_POWER_MANAGEMENT)
...
/*
 * FIXME: Remove the conditional inclusion of
 * core_devices array once we enble the capability
 * to build the device list based on devices power
 * and clock domain dependencies.
 */
#if defined(CONFIG_SOC_SERIES_NRF52X) || defined(CONFIG_SOC_SERIES_NRF51X)
#define MAX_PM_DEVICES	15
#define NUM_CORE_DEVICES	4
#define MAX_DEV_NAME_LEN	16
static const char core_devices[NUM_CORE_DEVICES][MAX_DEV_NAME_LEN] = {
	"CLOCK_32K",
	"CLOCK_16M",
	"sys_clock",
	"UART_0",
};
#else
#error "Add SoC's core devices list for PM"
#endif
...
#endif /* defined(CONFIG_SYS_POWER_MANAGEMENT) */
```
The documentation describes that `SYS_POWER_MANAGEMENT` is dependent on `SOC_FAMILY_NRF` which is selected by `SOC_SERIES_NRF51X`, `SOC_SERIES_NRF52X`, `SOC_SERIES_NRF53X`, `SOC_SERIES_NRF91X`. Both of the soc_series symbols for the nRF53x and nRF91x select `HAS_SYS_POWER_STATE_DEEP_SLEEP_1` also which shows that the system power management functionality was intended to be compatible for both series.

I'm currently working on an extreme low-power iot device on the nRF5340 and this feature is necessary to reach the lowest power state without losing significant development time. I'd be happy to help via a pull request, but I am quite new to Zephyr and am not yet familiar enough to start modifying the codebase.

### PR DESCRIPTION
**Pull request by masz-nordic**
Only System OFF mode is supported. Based on nrf52 power management, but nrf53 and nrf91 use nrf_regulators HAL instead of nrf_power.

Fixes #21318

### CODE REVIEW

File: subsys/power/device.c [hunk 1]
```diff
@@ -22,7 +22,8 @@ LOG_MODULE_DECLARE(power);
  * to build the device list based on devices power
  * and clock domain dependencies.
  */
-#if defined(CONFIG_SOC_SERIES_NRF52X) || defined(CONFIG_SOC_SERIES_NRF51X)
+#if defined(CONFIG_SOC_SERIES_NRF52X) || defined(CONFIG_SOC_SERIES_NRF51X) \
```
Comment (kl-cruz) [inline subsys/power/device.c]: Can we change it to for example ```SOC_FAMILY_NRF``` ?
This line contains all supported Nordic's MCU families

Comment (masz-nordic) [reply subsys/power/device.c]: Apparently, regulator peripheral is available only from Application core in nRF5340.
So this could be either
`#if defined(SOC_FAMILY_NRF) && !defined(CONFIG_SOC_NRF5340_CPUNET)`
or 
`
#if defined(CONFIG_SOC_SERIES_NRF52X) || defined(CONFIG_SOC_SERIES_NRF51X) \
    || defined(CONFIG_SOC_SERIES_NRF5340_CPUAPP) || defined(CONFIG_SOC_SERIES_NRF91X)
`

Also, I think that `select HAS_SYS_POWER_STATE_DEEP_SLEEP_1` should be moved from `SOC_SERIES_NRF53X` to `SOC_SERIES_NRF5340_CPUAPP`.

Comment (anangl) [reply subsys/power/device.c]: > Apparently, regulator peripheral is available only from Application core in nRF5340.
> So this could be either
> `#if defined(SOC_FAMILY_NRF) && !defined(CONFIG_SOC_NRF5340_CPUNET)`

But this part of code is related to the device (not system) power management. The REGULATOR peripheral is not involved here, so there is no need to exclude the network core.

> Also, I think that `select HAS_SYS_POWER_STATE_DEEP_SLEEP_1` should be moved from `SOC_SERIES_NRF53X` to `SOC_SERIES_NRF5340_CPUAPP`.

I agree.

Comment (masz-nordic) [reply subsys/power/device.c]: Changed to `#if defined(SOC_FAMILY_NRF)` and moved `select HAS_SYS_POWER_STATE_DEEP_SLEEP_1`.

**Review by anangl — APPROVED** [review]

**Review by wentongwu — APPROVED** [review]

**Review by kl-cruz — APPROVED** [review]

**Comment by MarcianoPreciado** [comment]
@masz-nordic If it is true that the nrf_regulator is only available for the application core then the current changes need another modification. We need to move the `select HAS_SYS_POWER_STATE_DEEP_SLEEP_1` from Kconfig.soc to the Application core Kconfig seeing as the following code in power.c includes the regulator for both cores at the moment:
```
#ifdef CONFIG_HAS_SYS_POWER_STATE_DEEP_SLEEP_1
#include <hal/nrf_regulators.h>
#endif
```

**Comment by masz-nordic** [comment]
@MarcianoPreciado 
> We need to move the select HAS_SYS_POWER_STATE_DEEP_SLEEP_1 from Kconfig.soc to the Application core Kconfig

That is a part of this PR, see changes in nRF53 `Kconfig.series` and `Kconfig.soc`.

>It appears that the nrf5340 supports a "Core Force-off mode" in which the app core can force the network core off. This is likely the scope of another commit.

Correct, this is just basic power management, similar to nRF52. Controlling the network core from application core (see also https://github.com/zephyrproject-rtos/zephyr/blob/master/boards/arm/nrf5340_dk_nrf5340/nrf5340_cpunet_reset.c) should be done in a separate PR.

**Comment by masz-nordic** [comment]
@pabigot @ioannisg Can you review?

File: soc/arm/nordic_nrf/nrf53/power.c [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+#include <logging/log.h>
+LOG_MODULE_DECLARE(soc, CONFIG_SOC_LOG_LEVEL);
+
+/* Invoke Low Power/System Off specific Tasks */
+void sys_set_power_state(enum power_states state)
+{
+	switch (state) {
+#ifdef CONFIG_SYS_POWER_DEEP_SLEEP_STATES
+ #ifdef CONFIG_HAS_SYS_POWER_STATE_DEEP_SLEEP_1
```
Comment (pabigot) [inline soc/arm/nordic_nrf/nrf53/power.c]: I don't believe we generally indent preprocessor directives.

File: soc/arm/nordic_nrf/nrf91/power.c [hunk 3]
```diff
@@ -0,0 +1,52 @@
+/*
+ * Copyright (c) 2017 Intel Corporation.
+ * Copytight (c) 2019 Nordic Semiconductor ASA
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#include <zephyr.h>
+#include <power/power.h>
+#include <hal/nrf_regulators.h>
```
Comment (pabigot) [inline soc/arm/nordic_nrf/nrf91/power.c]: This file is identical to the one added for nrf53, except that this one doesn't conditionalize the include on `CONFIG_HAS_SYS_POWER_STATE_DEEP_SLEEP_1`.  It's also remarkably similar to nrf51 and nrf52, differing only in the include file and the spelling of `power_system_off`.  Could it perhaps be moved to a `soc/arm/nordic_nrf/common` directory to reduce the need to make changes in four files as the power management infrastructure starts to mature?

**Review by pabigot — COMMENTED** [review]
Well, this explains why `samples/boards/nrf/system_off` didn't link on nrf53 for me this morning....

I'd like to see whether the power file can be made common across the SOCs, but once that's discussed I think this should be easy to approve.

**Comment by jhedberg** [comment]
Any update on this PR? @masz-nordic did you see the latest feedback from @pabigot? @ioannisg have you had a look at this PR?

File: soc/arm/nordic_nrf/nrf53/power.c (hunk 2 above)
Comment (masz-nordic) [reply soc/arm/nordic_nrf/nrf53/power.c]: I left it like this to keep conistent with `nrf52/power.c`. Should I delete indents here and in `nrf52`?

File: soc/arm/nordic_nrf/nrf91/power.c (hunk 3 above)
Comment (masz-nordic) [reply soc/arm/nordic_nrf/nrf91/power.c]: Those files are almost identical now, but I have created separate ones to prepare for potential differences in power management's future implementation. As for now, they could be merged into one, I don't have a strong opinion on this.

File: soc/arm/nordic_nrf/nrf53/power.c (hunk 2 above)
Comment (pabigot) [reply soc/arm/nordic_nrf/nrf53/power.c]: No, let's leave that for some future progress toward #21392.  I'd rather have less noise with internal consistency, than partial steps toward project-wide consistency.  (There are 570 indented `#if*` statements in Zephyr, compared to 15289 that are not.)

File: soc/arm/nordic_nrf/nrf91/power.c (hunk 3 above)
Comment (pabigot) [reply soc/arm/nordic_nrf/nrf91/power.c]: OK.

**Review by pabigot — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]

File: soc/arm/nordic_nrf/nrf53/power.c (hunk 2 above)
Comment (ioannisg) [reply soc/arm/nordic_nrf/nrf53/power.c]: We should not indent preprocessor directives, that's true

**Comment by ioannisg** [comment]
Overall, I think this needs to be a common file for nrf SoCs, as @pabigot suggested
