### PR TITLE
drivers: wifi: esp32: connect to highest signal AP

### LINKED ISSUE #84488: ESP32 WiFi Channel Selection
**Describe the bug**
Using the default channel of `WIFI_CHANNEL_ANY`, I am seeing the station-mode connection being established on the 1st channel which happens to have the worst RSSI on this network.  Looking into the code, `esp_wifi_drv.c` correctly converts `WIFI_CHANNEL_ANY` to a value of 0 in `esp_wifi_set_config()`, so it seems that the first channel found is being used instead of the strongest.

**To Reproduce**
Use the wifi example app `samples/net/wifi/shell/` and issue the following commands which I did on an ESP32-S3 system:

```
uart> wifi scan
Scan requested

Num  | SSID                             (len) | Chan (Band)   | RSSI | Security        | BSSID             | MFP     
1    | IoT                              3     | 11   (2.4GHz) | -47  | WPA2-PSK        | xxxxxxxxxxxxxxxxx | Disable 
2    | IoT                              3     | 11   (2.4GHz) | -60  | WPA2-PSK        | xxxxxxxxxxxxxxxxx | Disable 
3    | IoT                              3     | 1    (2.4GHz) | -79  | WPA2-PSK        | xxxxxxxxxxxxxxxxx | Disable

uart> wifi status
Status: successful
==================
State: COMPLETED
Interface Mode: STATION
Link Mode: WIFI 4 (802.11n/HT)
SSID: IoT
BSSID: xxxxxxxxxxxxxxxxx
Band: 2.4GHz
Channel: 1
Security: WPA2-PSK
MFP: Disable
RSSI: -82
Beacon Interval: 3
DTIM: 0
TWT: Not supported
Current PHY rate : 0
```

**Expected behavior**
When `WIFI_CHANNEL_ANY` is specified the highest signal strength channel should be selected.

**Impact**
Poor performance and network drops in areas with multiple APs.  In my case, the AP on channel 1 was located 20m away and the AP on channel 11 was located 2m away and the ESP32-S3 always connected to channel 1 resulting in poor performance.

**Environment (please complete the following information):**
Zephyr 4.0 and main at commit hash 4ed85eec2b0f0f9a1e0a51b977050b86906d7ae8.

### PR DESCRIPTION
**Pull request by EricNRS**
The station-mode channel scan method is currently set to WIFI_FAST_SCAN which ignores the signal strength and connects to the first channel found which may result in poor WiFi bandwidth.

Change the scan mode to scan all channels and connect to the channel with the highest RSSI.

Fixes #84488

### CODE REVIEW

**Review by sylvioalves — DISMISSED** [review]

**Comment by wmrsouza** [comment]
Since WIFI_FAST_SCAN is also an option for wifi_config.sta.scan_method, would you mind providing a Kconfig parameter regardin to the preferred scan method  having WIFI_ALL_CHANNEL_SCAN as the default one?

**Comment by EricNRS** [comment]
> Since `WIFI_FAST_SCAN` is also an option for `wifi_config.sta.scan_method`, would you mind providing a Kconfig parameter regarding to the preferred scan method having `WIFI_ALL_CHANNEL_SCAN` as the default one?

Done, please take a look to see if the configuration item is as you expected.

**Review by wmrsouza — DISMISSED** [review]

**Review by raffarost — DISMISSED** [review]

**Review by MaochenWang1 — DISMISSED** [review]

**Review by jukkar — DISMISSED** [review]

**Review by marekmatej — COMMENTED** [review]
besides the nit LGTM

File: drivers/wifi/esp32/src/esp_wifi_drv.c [hunk 1]
```diff
@@ -568,6 +568,10 @@ static int esp32_wifi_connect(const struct device *dev,
 		return -EIO;
 	}
 
+#if defined(CONFIG_ESP32_WIFI_STA_SCAN_ALL)
+	wifi_config.sta.scan_method = WIFI_ALL_CHANNEL_SCAN;
```
Comment (sylvioalves) [inline drivers/wifi/esp32/src/esp_wifi_drv.c:572]: Enabling `WIFI_ALL_CHANNEL_SCAN` will guarantee scanning all as it says, however, it won't sort by signal strength. Adding `.sort_method` method to `WIFI_CONNECT_AP_BY_SIGNAL` would make sure that the selected AP is indeed the one with more RSSI. This suggestion is not blocking the PR though. LGTM

Comment (EricNRS) [reply drivers/wifi/esp32/src/esp_wifi_drv.c:572]: Yes, I had that in an early version of this patch, but `WIFI_CONNECT_AP_BY_SIGNAL` has a value of 0, so it is enabled by default.  Should I add it for completeness?

Comment (sylvioalves) [reply drivers/wifi/esp32/src/esp_wifi_drv.c:572]: If you can, please do. At least it makes it clear about its usage.

Comment (EricNRS) [reply drivers/wifi/esp32/src/esp_wifi_drv.c:572]: Fixed with the latest version.

File: drivers/wifi/esp32/Kconfig.esp32 [hunk 2]
```diff
@@ -54,6 +54,13 @@ config ESP32_WIFI_STA_RECONNECT
 	help
 	  Set auto WiFI reconnection when disconnected.
 
+config ESP32_WIFI_STA_SCAN_ALL
+	bool "Scan all available APs when connecting in station mode"
+	help
+	  When connecting in station mode, scan all channels and connect to the channel with the
+	  highest RSSI.  Without this, a fast scan is performed which connects to the first AP
```
[the remark this answers is not in the document]
Comment (EricNRS) [reply drivers/wifi/esp32/Kconfig.esp32]: Fixed with the latest version.

**Review by sylvioalves — APPROVED** [review]

**Review by wmrsouza — APPROVED** [review]

**Review by raffarost — APPROVED** [review]

**Review by uLipe — APPROVED** [review]
