### PR TITLE
kernel: fix k_sleep in no multi-threading mode

### LINKED ISSUE #81210: kernel: k_sleep bug in no multi-threading mode
**Describe the bug**
Bug in `k_sleep` implementation for no multi-threading mode.

Absolute value of timeout expiration was fed to the k_busy_wait() function instead of delta value. That caused bug like incrementing of sleep time in geometric progression (while actual function argument is constant) during program running.

**Suggested solution**
#80979

**To Reproduce**
1. Replace `hello_world` sample source with simple code:
```c
#include <zephyr/kernel.h>

int main (void)
{
	uint32_t new_ticks = 0;
	uint32_t old_ticks = sys_clock_tick_get_32();

	while (1) {
		k_sleep(K_MSEC(1000));
		new_ticks = sys_clock_tick_get_32();
		printf("%u\n", new_ticks - old_ticks);
		old_ticks = new_ticks;
	}

	return 0;
}
```
2. write `CONFIG_MULTITHREADING=n` flag in `prj.conf`
3. `cd zephyr`
4. `west build -b qemu-riscv64 samples/hello_world`
5. `west build -t run`
6. See, that waiting time between console outputs increases, even though constant value is passed into `k_sleep`

**Expected behavior**
Expected, that `k_sleep` will wait actual amount of time, specified in function argument

**Impact**
Programs start to sleep a lot of time, when compile for no multi-threading mode

**Logs and console output**
Output from qemu_riscv64:
```
100
200
400
800
...
```

**Environment (please complete the following information):**
- OS: Linux
- Toolchain: zephyr-sdk-0.16.1
- Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/commit/c3466b14d09b1e51b6ca472f3b3654e40cba12d8

**Additional context**
NA

### PR DESCRIPTION
**Pull request by KushnerovMikhail**
Fix k_sleep implementation for no multi-threading mode.
Fixes #81210

Absolute value of timeout expiration was fed to the k_busy_wait() function instead of delta value. That caused bug like incrementing of sleep time in geometric progression (while actual function argument is constant) during program running.

You can check it by simple program with `CONFIG_MULTITHREADING=n` option:
```c
#include <zephyr/kernel.h>

int main (void)
{
	uint32_t new_ticks = 0;
	uint32_t old_ticks = sys_clock_tick_get_32();

	while (1) {
		k_sleep(K_MSEC(1000));
		new_ticks = sys_clock_tick_get_32();
		printf("%u\n", new_ticks - old_ticks);
		old_ticks = new_ticks;
	}

	return 0;
}
```
Output from qemu_riscv64
Before fix:
100
200
400
800
...

After fix:
100
100
100
100
...

### CODE REVIEW

File: kernel/nothread.c [hunk 1]
```diff
@@ -37,12 +37,14 @@ int32_t z_impl_k_sleep(k_timeout_t timeout)
 
 	ticks = timeout.ticks;
 	if (Z_TICK_ABS(ticks) <= 0) {
-		expected_wakeup_ticks = ticks + sys_clock_tick_get_32();
+		/* ticks is delta timeout */
+		ticks_to_wait = ticks;
 	} else {
-		expected_wakeup_ticks = Z_TICK_ABS(ticks);
+		/* ticks is absolute timeout expiration */
+		ticks_to_wait = Z_TICK_ABS(ticks) - sys_clock_tick_get_32();
```
Comment (peter-mitsis) [inline kernel/nothread.c:44]: If we have already passed the absolute point in time (Z_TICKS_ABS(ticks) < sys_clock_tick_get_32()), we should set `ticks_to_wait` to 0, otherwise we are waiting when we should not be waiting.

**Review by cfriedt — APPROVED** [review]

**Review by npitre — APPROVED** [review]

**Review by peter-mitsis — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@peter-mitsis , is this a fix that is needed for the upcoming 4.0 release?

**Comment by peter-mitsis** [comment]
@mmahadevan108 - I think this would be worthwhile for 4.0.

**Comment by dkalowsk** [comment]
@KushnerovMikhail or @peter-mitsis can you please file an Issue so it can be tracked to a detail in the release-notes?

File: kernel/nothread.c [hunk 2]
```diff
@@ -37,12 +37,20 @@ int32_t z_impl_k_sleep(k_timeout_t timeout)
...
-		expected_wakeup_ticks = ticks + sys_clock_tick_get_32();
+		/* ticks is delta timeout */
+		ticks_to_wait = ticks;
 	} else {
-		expected_wakeup_ticks = Z_TICK_ABS(ticks);
+		/* ticks is absolute timeout expiration */
+		uint32_t curr_ticks = sys_clock_tick_get_32();
+
+		if (Z_TICK_ABS(ticks) > curr_ticks) {
+			ticks_to_wait = Z_TICK_ABS(ticks) - curr_ticks;
```
Comment (rruuaanng) [inline kernel/nothread.c:47]: Are they possible to be negative number?

(Just a question.)

**Review by rruuaanng — APPROVED** [review]

File: kernel/nothread.c (hunk 2 above)
Comment (KushnerovMikhail) [reply kernel/nothread.c:47]: Not really understand question.

If you talking about `Z_TICK_ABS(ticks)`, than it can. But negative values are caught by previous if.
If you talking about `ticks_to_wait`, I think there is no meaning in waiting negative time. So, I make it unsigned.
`sys_clock_tick_get_32()`, of course, can not be negative.

**Review by andyross — APPROVED** [review]

**Comment by mmahadevan108** [comment]
Moving the milestone to 4.1. Please add the `backport-v4.0` label if this is critical for 4.0
