### PR TITLE
net: ipv4: ARP message was sent instead of proper IPv4 message

### LINKED ISSUE #9348: samples: net: echo_client/echo_server does not work with IPv4 qemu_x86
It looks like `echo_server`/`echo_client` and probably other samples that use IPv4 does not work on `qemu_x86`. Bisecting showed up that https://github.com/zephyrproject-rtos/zephyr/commit/bab35512f87b3bc9804a3b90d489c911701cfae8 broke them. It kinda makes sense, because IPv6 communication works, while IPv4 is broken.

I'm not sure what exactly is wrong in ARP as I'm not familiar with the implementation, but perhaps someone more familiar with it could take a look.

### PR DESCRIPTION
**Pull request by jukkar**
The ethernet sending routing sent ARP message instead of the
actual IPv4 data message.

Fixes #9348

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Comment by mike-scott** [comment]
@jukkar Fixes ethernet communication on K64F as well.

**Review by pfalcon — DISMISSED** [review]
While I understand this fixes a breaking issue, I think it has too hasted a look and needs cleanup.

Optimization opportunity with the flag introduced is pointed out.

Commit message:

> The ethernet sending routing sent ARP message instead of the
actual IPv4 data message.

I don't see how this commit message describes what's done by the patch. Word "routing" is apparently wrong, I may imagine ethernet sending code path was meant instead (and not networking routing capability, CONFIG_NET_ROUTING).

If it fixes #9348, please add some description based on it.

Thanks.

**Comment by jukkar** [comment]
> Word "routing" is apparently wrong

Typo, it was meant to say "routine" :)

**Comment by jukkar** [comment]
Updated commit message. Using bit field instead of new variable in net_pkt struct.

File: subsys/net/l2/ethernet/ethernet.c [hunk 1]
```diff
@@ -431,7 +440,7 @@ static enum net_verdict ethernet_send(struct net_if *iface,
 		}
 
 		/* Trying to send ARP message so no need to setup it twice */
-		if (ntohs(NET_ETH_HDR(pkt)->type) != NET_ETH_PTYPE_ARP) {
```
Comment (pfalcon) [inline subsys/net/l2/ethernet/ethernet.c]: Thanks for the updates. Unfortunately, I still don't understand what's the problem, even after looking thru your changes and old code for ~10min. Is it the case that pkt can arrive here without Ethernet headers, so trying to access it (`NET_ETH_HDR(pkt)`) means accessing invalid data? It's hard to believe that, because line before this code https://github.com/zephyrproject-rtos/zephyr/pull/9350/files#diff-b7cca9bcea20a1b9bfe87f98f5e65feeL427 accesses NET_ETH_HDR(pkt) anyway.

Comment (jukkar) [reply subsys/net/l2/ethernet/ethernet.c]: IPv4 prepares ARP message and then sends it. The ethernet ARP routine should not try to prepare a new ARP message so that is the reason for the check in ethernet_send(). My earlier check was obviously wrong but for yet some unknown reason it worked ok for ping, I will investigate this ping issue separately.

Comment (pfalcon) [reply subsys/net/l2/ethernet/ethernet.c]: > IPv4 autoconf prepares ARP message and then sends it. The ethernet ARP routine should not try to prepare a new ARP message for this existing ARP msg

Compare this to what's written in the commit message:

> The ethernet sending routine sent a corrupted ARP packet instead
of the actual IPv4 packet.

Anyway, let me approve this if this fixes the matters.

**Review by pfalcon — APPROVED** [review]
Urgent fix, approving.

**Comment by pfalcon** [comment]
recheck

**Review by rlubos — APPROVED** [review]
Thank you for the quick fix!

Just verified the samples, works nicely again.

LGTM :+1:
