### PR TITLE
Bluetooth: GATT: Fix not parsing result of Read by Type

### LINKED ISSUE #16107: Using bt_gatt_read() with 'by_uuid' method returns 3 extra bytes
**Describe the bug**
Using bt_gatt_read() with 'by_uuid' method returns 3 extra unexpected bytes.  The extra bytes are at the beginning of the data pointed to by the *data parameter of the read callback function.  The three bytes are part of the struct bt_att_read_type_rsp, it is the len followed by handle + value list.

**To Reproduce**
Call bt_gatt_rd() similar to this:
	memcpy(&uuid, BT_UUID_GAP_DEVICE_NAME, sizeof(uuid));
	read_params.func = read_func_cb;
	read_params.handle_count = 0;
	read_params.by_uuid.start_handle = 1;
	read_params.by_uuid.end_handle = 0xffff;
	read_params.by_uuid.uuid = &uuid.uuid;
	bt_gatt_read(conn, &read_params);

**Expected behavior**
From the API documentation I would have expected to get just the octets from the characteristic UUID type. 

**Impact**
annoyance

### PR DESCRIPTION
**Pull request by Vudentz**
When using the procedure Read By Type the response may contain multiple
instances so it needs to be parsed properly. When dealing with long
values only the beggining will be read, for the remaining bytes the
application should issue another bt_gatt_read with offset so Read Blob
procedure is used as recommended by the spec:

BLUETOOTH CORE SPECIFICATION Version 5.1 | Vol 3, Part F page 2312:

The Read Blob Request would be used to read the remaining octets of a
long attribute value.

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

Fixes #16107

### CODE REVIEW

**Comment by jhedberg** [comment]
@Vudentz is this something to be backported to LTS (1.14.x)?

**Comment by Vudentz** [comment]
> @Vudentz is this something to be backported to LTS (1.14.x)?
> 
> If it is (which it seems like to me) it'll also need to have a corresponding issue opened for it.

I don't think we had read by UUID support at that point, it was introduced later on by @tedd-an

**Comment by tedd-an** [comment]
> I don't think we had read by UUID support at that point, it was introduced later on by @tedd-an

Yes, #15439 was merged after LTS release.

**Comment by jhedberg** [comment]
>> I don't think we had read by UUID support at that point, it was introduced later on by @tedd-an 

> Yes, #15439 was merged after LTS release.

Ok, I've removed the 1.14 tag.

**Comment by tedd-an** [comment]
FYI, I ran PTS GATT and no regression found.

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -2490,6 +2490,52 @@ int bt_gatt_discover(struct bt_conn *conn,
...
+
+		handle = sys_le16_to_cpu(data->handle);
+
+		/* Handle 0 is invalid */
+		if (!handle) {
+			BT_ERR("Invalid handle");
+			return;
+		}
+
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: minor: redundant empty line here

**Comment by carlescufi** [comment]
@Vudentz does this fix #16107?

**Comment by Vudentz** [comment]
> @Vudentz does this fix #16107?

Yep, will add to the patch.

**Comment by Vudentz** [comment]
@jhedberg anything pending here

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
> @jhedberg anything pending here

@Vudentz looks good to me. A second review would be nice though.

**Comment by Vudentz** [comment]
@joerchan or @carlescufi any chance to review this one?

**Review by carlescufi — APPROVED** [review]
LGTM
