### PR TITLE
driver: uart_npcx: Fix uart to use PM constrain

### LINKED ISSUE #40621: npcx uart driver uses device PM callback to block suspension
**Describe the bug**

The npcx UART driver is currently using the device PM callback to block suspension if the UART is transmitting, as shown below:

https://github.com/zephyrproject-rtos/zephyr/blob/5e035b0f4eb43df68313b401e0a71d2cdcd54d65/drivers/serial/uart_npcx.c#L441-L460

The device PM callback needs to be used only to suspend/resume devices. If the system cannot be suspended because UART is in a particular state, the `pm_constraint_set/release` API should be used.

**To Reproduce**

https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_npcx.c

**Expected behavior**

Device driver should prevent system suspension by using `pm_constraint_set/release` API.

**Impact**

PM API misuse, PM subsystem needs to account for such “special cases” when it should not.

**Logs and console output**

N/A

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: 5e035b0

**Additional context**

STM32 UART driver may be taken as an example: https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/serial/uart_stm32.c#L85

### PR DESCRIPTION
**Pull request by WealianLiao**
The device PM callback needs to be used only to suspend/resume devices.
If the system cannot be suspended because UART is in a particular
state, the pm_constraint_set/release API should be used. For NPCX UART,
the chip can't enter low power idle state until UART completes the data
transmission.
This commit changes NPCX UART to use pm_constraint_set/release & fixes
UART lost data from low power idle.

Fix #40621

### CODE REVIEW

File: drivers/serial/uart_npcx.c [hunk 1]
```diff
@@ -52,6 +56,26 @@ struct uart_npcx_data {
...
 	(struct uart_reg *)(DRV_CONFIG(dev)->uconf.base)
 
+#if defined(CONFIG_PM) && defined(CONFIG_UART_INTERRUPT_DRIVEN)
+static void uart_npcx_pm_constraint_set(const struct device *dev)
+{
+	struct uart_npcx_data *data = DRV_DATA(dev);
+
+	if (atomic_set(&data->pm_constraint_on, 1) == 0) {
+		pm_constraint_set(PM_STATE_SUSPEND_TO_IDLE);
+	}
```
Comment (gmarull) [inline drivers/serial/uart_npcx.c:66]: note: the PM constraint API uses ref counting, are you sure you need atomics here? If you call `pm_constraint_set` N times, the constraint won't be released after N other calls to `pm_constraint_release`.

Comment (WealianLiao) [reply drivers/serial/uart_npcx.c:66]: We use the constrain for UART transmission. pm_constraint_set() may be invoked when any UART transmission request. However, we couldn't know how much time invoking pm_constraint_set() if we didn't maintain a local counter when the complete transmission ISR. The pm_constraint_set() may be invoked several times before the complete ISR. So we use this to guarantee the set/release is compared.

**Review by gmarull — APPROVED** [review]

**Review by keith-zephyr — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
