### PR TITLE
Coverity fixes in logging and cbprintf

### LINKED ISSUE #38000: [Coverity CID: 238347] Negative array index read in tests/lib/cbprintf_package/src/test.inc
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/8c68a7a587b884fb12ee6a31658281b2f9929485/tests/lib/cbprintf_package/src/test.inc

Category: Memory - illegal accesses
Function: `test_cbprintf_rw_str_indexes`
Component: Tests
CID: [238347](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=238347)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/8c68a7a587b884fb12ee6a31658281b2f9929485/tests/lib/cbprintf_package/src/test.inc#L201

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.coverity.com/doc/en/cov_checker_ref.html#static_checker_NEGATIVE_RETURNS). ([CWE-129](http://cwe.mitre.org/data/definitions/129.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #38001: [Coverity CID: 238371] Negative array index read in tests/lib/cbprintf_package/src/test.inc
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/8c68a7a587b884fb12ee6a31658281b2f9929485/tests/lib/cbprintf_package/src/test.inc#L201

Category: Memory - illegal accesses
Function: `test_cbprintf_rw_str_indexes`
Component: Tests
CID: [238371](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=238371)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/8c68a7a587b884fb12ee6a31658281b2f9929485/tests/lib/cbprintf_package/src/test.inc#L201

```
195         zassert_equal(desc0->ro_str_cnt, 0, NULL);
196         zassert_equal(desc1->ro_str_cnt, 2, NULL);
197         zassert_equal(desc2->ro_str_cnt, 2, NULL);
198     
199         int *p = (int *)package1;
200     
201         str_idx = package1[len0];
202         addr = *(char **)&p[str_idx];
203         zassert_equal(addr, test_str, NULL);
204     
205         str_idx = package2[len0];
206         addr = *(char **)&p[str_idx];
```

For more information about the violation, check the [Coverity Reference](https://scan9.coverity.com/doc/en/cov_checker_ref.html#static_checker_NEGATIVE_RETURNS). ([CWE-129](http://cwe.mitre.org/data/definitions/129.html))

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #38123: [Coverity CID: 239584] Improper use of negative value in subsys/logging/log_msg2.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/fe2014ae1f4a7861771f86d500ac516fb5f59776/subsys/logging/log_msg2.c

Category: Integer handling issues
Function: `z_impl_z_log_msg2_runtime_vcreate`
Component: Other
CID: [239584](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=239584)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/fe2014ae1f4a7861771f86d500ac516fb5f59776/subsys/logging/log_msg2.c#L86

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.coverity.com/doc/en/cov_checker_ref.html#static_checker_NEGATIVE_RETURNS). ([CWE-394](http://cwe.mitre.org/data/definitions/394.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by nordic-krch**
Coverity fixes for issues reported in logging and cbprintf.

Fixes #38123.
Fixes #38001.
Fixes #38000.

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

File: subsys/logging/log_msg2.c [hunk 1]
```diff
@@ -83,7 +83,7 @@ void z_impl_z_log_msg2_runtime_vcreate(uint8_t domain_id, const void *source,
 	}
 
 	if (msg && fmt) {
-		plen = cbvprintf_package(msg->data, plen, 0, fmt, ap);
+		plen = cbvprintf_package(msg->data, (size_t)plen, 0, fmt, ap);
```
Comment (stephanosio) [inline subsys/logging/log_msg2.c:86]: https://github.com/zephyrproject-rtos/zephyr/blob/89408901a81e3c99608a953ee5cbfac835a5be3a/subsys/logging/log_msg2.c#L60

Instead of casting, it would be cleaner to declare `plen` as `size_t`.

Comment (nordic-krch) [reply subsys/logging/log_msg2.c:86]: the problem is that function `cbprintf_package` is used for calculating needed size (with null buffer) and for creating actual package. It returns `int`. Negative error code or needed size if positive so typical use is following:
```
int len = cbprintf_package(NULL, 0, 0, fmt, ...);
if (len < 0) {
  /*error*/
  return;
}

void *buf = alloc(len);

int len = cbprintf_package(buf, (size_t)len, 0, 0, fmt, ...);
```

If `cbprintf_package` would be changed to use `int` instead of `size_t` then still there would be conversion in cases like:
```
uint8_t buf[128];
int len = cbprintf_package(buf, sizeof(buf), fmt, ...);
```

**Review by cfriedt — APPROVED** [review]
