### PR TITLE
tests/kernel/pipe: fix uninitialized semaphore

### LINKED ISSUE #4366: memory corruption in test_pipe_api
There is some kind of horrible memory corruption going on in the pipe API test. I am not sure this is a problem in the test case, I think this may be a kernel bug.

To reproduce, apply the following patch:
```
diff --git a/tests/kernel/pipe/pipe_api/src/test_pipe_contexts.c b/tests/kernel/pipe/pipe_api/src/test_pipe_contexts.c
index cd665b532..c688aa468 100644
--- a/tests/kernel/pipe/pipe_api/src/test_pipe_contexts.c
+++ b/tests/kernel/pipe/pipe_api/src/test_pipe_contexts.c
@@ -30,8 +30,8 @@ K_PIPE_DEFINE(kpipe, PIPE_LEN, 4);
 static struct k_pipe pipe;
 
 static K_THREAD_STACK_DEFINE(tstack, STACK_SIZE);
-static struct k_thread tdata;
-static struct k_sem end_sema;
+struct k_thread tdata;
+struct k_sem end_sema;
 
 static void tpipe_put(struct k_pipe *ppipe)
 {
```

With tdata and end_sema in a different part of memory, I get a hard crash on any QEMU target I attempt with. You have to apply the patch to see this crash. q

This bug has been around for a while, it is not due to any recent activity, if I checkout the v1.9.0 tag and apply the above patch, I also get a crash.

What little investigation I did, it seems that the kernel's ready queue gets corrupted, and the system tries to swap in a bogus new value of _current, to something which is not a k_thread, and the stack pointer gets set to some garbage value (usually a NULL)

### PR DESCRIPTION
**Pull request by andyross**
The end_sema k_sem was only initialized on one of the several paths
that used it, leading to some crazy clobber-the-run-queue behavior
that was dependent on linkage order (see the linked bug) when end_sema
and the pipe object were made non-static..

Adding a k_sem_init() call fixes the corrupt issue, but really the
right thing is to use the DEFINE macro, so do that instead.  Note that
that the initializer changes the linkage order too (by putting the
semaphore in a separate segment), so... yeah, it's actually impossible
to prove that this patch in isolation resolves the issue seen without
manual validation.

Fixes #4366

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
We might not be out of the woods yet.

CI is reporting that test_pipe_block_put is now failing on Riscv32 and xtensa

**Comment by andyross** [comment]
Yeah, the other bug (AFAICT entirely unrelated to the scheduler mess to do with the semaphore) was a initialization bug in mem_pool.  This test uses a minimum block size of 4 bytes, which is smaller than the hard minimum in the allocator of 8.  A few other tests did that too, and got (correct) runtime failures.  But this one turns out to do an immediate free, so it always gets a "valid" buffer.  Except the buffer was allocated out of an invalid level of "4 byte blocks" which can't work.

File: include/kernel.h [hunk 1]
```diff
@@ -3550,6 +3550,11 @@ struct k_mem_pool {
 	_MPOOL_HAVE_LVL(maxsz, minsz, 14) +	\
 	_MPOOL_HAVE_LVL(maxsz, minsz, 15))
 
+#define _MPOOL_MINBLK sizeof(sys_dnode_t)
+
+#define _MPOOL_LVLS(max, min)		\
+	__MPOOL_LVLS((max), (min) >= _MPOOL_MINBLK ? (min) : _MPOOL_MINBLK)
```
Comment (andrewboie) [inline include/kernel.h]: At first glance I wonder if it might be better to fail an assertion or something, instead of just increasing the block size passed in.
You know the mem pool code far better than me though, so I defer to your opinion.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andrewboie** [comment]
checkpatch unhappy, rest of tests passing.
i don't know why it wants parens for parameters that just get passed as params to other macros/functions

```
-:10: ERROR:COMPLEX_MACRO: Macros with complex values should be enclosed in parentheses
#10: FILE: include/kernel.h:3535:
+#define __MPOOL_LVLS(maxsz, minsz)		\
 	(_MPOOL_HAVE_LVL(maxsz, minsz, 0) +	\
 	_MPOOL_HAVE_LVL(maxsz, minsz, 1) +	\
 	_MPOOL_HAVE_LVL(maxsz, minsz, 2) +	\

- total: 1 errors, 0 warnings, 37 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

Your patch has style problems, please review.

NOTE: Ignored message types: AVOID_EXTERNS BRACES CONFIG_EXPERIMENTAL CONST_STRUCT DATE_TIME FILE_PATH_CHANGES MINMAX NETWORKING_BLOCK_COMMENT_STYLE PRINTK_WITHOUT_KERN_LEVEL SPLIT_STRING VOLATILE

NOTE: If any of the errors are false positives, please report
      them to the maintainers.
```

**Comment by andyross** [comment]
Grr.... the syntax actually doesn't change.  Somehow this passed checkpatch once before.  Will update.

As far as checking: the API just allows you to specify a "minimum" block size.  It doesn't make promises about exactly how that would be aligned or padded or how many such blocks would be available (you specify the number of maximum-sized blocks instead).  It seems reasonable to allow users to specify whatever they want, they shouldn't have to be concerned with the internal "true minimum" that it gets padded up to.

**Comment by andyross** [comment]
Fixed the checkpatch whine.  Turns out checkpatch is smarter than I thought: it's fine with unparenthesized arguments as long as the macro is never **used** with a non-simple expression.  But when I made the argument a ?: expression (even a parenthesized one) it unmasked the warning.
