### PR TITLE
Only start the network interface during init if needed

### LINKED ISSUE #15477: Zephyr network stack will up the Ethernet interface after its driver initialized (regardless of actual status)
**Describe the bug**
During the Zephyr boot up, if the network interface does not connect any cable, network stack will still up every network interfaces.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=up_squared ../
3. make
4. boot up Zephyr without connecting network cable
5. perform network transaction

**Expected behavior**
During Zephyr boot up, network interface will only up when cable is connected and link is up.

**Impact**
Network application will start transaction where interface not yet up which cause failure and confusion.

**Screenshots or console output**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 14.04
 - Toolchain: Zephyr SDK v0.10.0
 - Commit SHA or Version used: b2a3e12d861a569c3c4cff2168d9165a626bbaee (1.14-rc3)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jukkar**
Fixes #15477

### CODE REVIEW

File: include/net/net_if.h [hunk 1]
```diff
@@ -179,6 +179,14 @@ enum net_if_flag {
 	/** Interface is in promiscuous mode */
 	NET_IF_PROMISC,
 
+	/** Do not start the interface immediately after initialization.
+	 * This requires that either the device driver or some other entity
+	 * will need to manually take the interface up when needed.
+	 * For example for Ethernet this will happen when the driver calls
+	 * the net_eth_carrier_on() function.
+	 */
+	NET_IF_NO_AUTO_START,
```
Comment (tbursztyka) [inline include/net/net_if.h]: To me this is an added feature and not the exact fix.

quoting the issue:

> boot up Zephyr without connecting network cable

It sounds like a driver/l2 issue where it enables the driver though the carrier is off which obviously should not happen. So fixing #15477 should be about this.

I am not against adding this net_if_no_auto_start though, but then its behavior could be that even carrier on would not put the if up

**Review by tbursztyka — CHANGES_REQUESTED** [review]

File: include/net/net_if.h (hunk 1 above)
Comment (jukkar) [reply include/net/net_if.h]: > boot up Zephyr without connecting network cable

We unconditionally turn the network interface up in `net_if_post_init()`. For Ethernet this is probably not the best idea as the Ethernet driver should turn on the carrier when cable is connected which will then turn on the network interface. If the application is listening the IFACE UP event, then there is weird issues in the system if the cable is not yet connected.

Comment (tbursztyka) [reply include/net/net_if.h]: yep, that's the problem. At init phase, driver should probably check on the carrier, and set it to off/on accordingly (but not through the usual functions, since these ones will call if_up/down).

Comment (jukkar) [reply include/net/net_if.h]: Yes, driver needs more work, this PR is not fixing anything in that front. We just allow driver to tell that network interface is not to be started automatically.

File: subsys/net/ip/net_if.c [hunk 2]
```diff
@@ -3154,6 +3154,8 @@ void net_if_post_init(void)
 
 	/* After TX is running, attempt to bring the interface up */
 	for (iface = __net_if_start; iface != __net_if_end; iface++) {
-		net_if_up(iface);
+		if (!net_if_flag_is_set(iface, NET_IF_NO_AUTO_START)) {
+			net_if_up(iface);
```
Comment (pfalcon) [inline subsys/net/ip/net_if.c]: Following up discussion in https://github.com/zephyrproject-rtos/zephyr/pull/15480/commits/dc115e6d20ca711c424cfc2fc90cfc9327349d0b#r275690049 , indeed, what if we make calling net_if_up(iface) a driver responsibility?

Comment (jukkar) [reply subsys/net/ip/net_if.c]: That is exactly what we are doing here by introducing this flag. I did not wanted to change the current functionality thou, so by default we still take the interface up. This could be changed in the future.

Comment (pfalcon) [reply subsys/net/ip/net_if.c]: I meant completely removing this "for" loop and making driver init routine call net_if_up(). I feel this this probably will lead to further sync issues between different network stack parts (a-la https://github.com/zephyrproject-rtos/zephyr/issues/13991). So, let me approve this.

**Review by pfalcon — APPROVED** [review]
Looks good as intermediate measure to address the issue.

File: subsys/net/ip/net_if.c (hunk 2 above)
Comment (tbursztyka) [reply subsys/net/ip/net_if.c]: driver should not drive the iface state (moreover when there can be more than 1 iface per-device on VLAN for instance). The issue is really about setting carrier off/on properly at init time.

Comment (mike-scott) [reply subsys/net/ip/net_if.c]: @tbursztyka How would a modem driver let the network stack know that connection was down?  Seems like drivers should have some input to their own interface state?

**Review by mike-scott — APPROVED** [review]
Changes seem good.

File: subsys/net/ip/net_if.c (hunk 2 above)
Comment (jukkar) [reply subsys/net/ip/net_if.c]: @mike-scott use `net_if_carrier_down()` or `net_if_down()` when the low level connection goes down, and then `net_if_up()` when it goes up. For example Ethernet has its own `net_eth_carrier_on()` and `net_eth_carrier_off()` that basically calls those functions.

Comment (mike-scott) [reply subsys/net/ip/net_if.c]: AH makes sense.  Driver manages the carrier status.  Thank you for the explanation.

**Comment by tbursztyka** [comment]
Since we are not in 1.14 bug fix anymore, I think #15477 should be properly fixed (eth driver setting carrier status at init level). We have time to address this nicely instead of this workaround. Plus the naming NET_IF_NO_AUTO_START is a bit misleading since plugging the cable will start the device.

**Comment by jukkar** [comment]
> Since we are not in 1.14 bug fix anymore, I think #15477 should be properly fixed (eth driver setting carrier status at init level). We have time to address this nicely instead of this workaround. Plus the naming NET_IF_NO_AUTO_START is a bit misleading since plugging the cable will start the device.

No sure what you mean by proper fix here. If the driver sets this flag, then net_if will not bring network interface up by default, so that driver can do it when it detects that the cable is connected. I do not understand what you mean by workaround in this context. The flag is just finely named in imho, it tells that the interface is not autostarted which is what correct in this case.

**Comment by mrfuchs** [comment]
The current drivers do not implement carrier detection (i.e. they are not making use of the net_eth_carrier_on/off functions), except for the MCUX Ethernet driver. A proper fix, as I understand it, means to fix this issue bottom-up, starting from the Ethernet drivers.

**Comment by jukkar** [comment]
> A proper fix, as I understand it, means to fix this issue bottom-up, starting from the Ethernet drivers.

As I wrote in my earlier comment, this PR was not meant to do any changes to Ethernet drivers, it just enables the driver to tell the net_if that the driver can handle the carrier detection itself. Separate PRs adding necessary support in drivers are needed. As always, patches are welcome of course.

**Comment by jukkar** [comment]
Removed the "Fixes" string from the commit message as this is not fully solving the original issue. Some code changes are needed in network drivers.

**Review by tbursztyka — APPROVED** [review]
