### PR TITLE
queue: k_queue_get: Fix NULL return

### LINKED ISSUE #4358: k_queue_poll returns NULL with K_FOREVER
When running with https://github.com/zephyrproject-rtos/zephyr/pull/4350, we still see instances on Cortex-M4 (nRF52832) where k_queue_poll returns NULL, traced down to sys_slist_get() returning NULL, something that should never happen. We can reproduce relatively easily, although it seems to be a race condition.

### PR DESCRIPTION
**Pull request by Vudentz**
k_queue_get shall never return NULL when timeout is K_FOREVER which can
happen when a higher priority thread cancel/take an item before the
waiting thread.

Fixes  #4358

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

File: kernel/queue.c [hunk 1]
```diff
@@ -207,19 +207,23 @@ static void *k_queue_poll(struct k_queue *queue, s32_t timeout)
 
 	event.state = K_POLL_STATE_NOT_READY;
 
-	err = k_poll(&event, 1, timeout);
-	if (err) {
-		return NULL;
-	}
+	do {
+		err = k_poll(&event, 1, timeout);
```
Comment (jhedberg) [inline kernel/queue.c]: I think you need to move the "event.state = K_POLL_STATE_NOT_READY;" into the loop so that it gets set every time before you call k_poll. That's at least how Ben instructed me to use the API when I originally took it into use in our Bluetooth code (which also calls it in a loop).

**Review by jhedberg — DISMISSED** [review]

File: kernel/queue.c (hunk 1 above)
Comment (carlescufi) [reply kernel/queue.c]: Agreed, as stated in here: https://www.zephyrproject.org/doc/kernel/other/polling.html#using-k-poll

File: kernel/queue.c [hunk 2]
```diff
@@ -207,19 +207,23 @@ static void *k_queue_poll(struct k_queue *queue, s32_t timeout)
...
+		__ASSERT_NO_MSG(event.state ==
+				K_POLL_STATE_FIFO_DATA_AVAILABLE);
+
+		/* sys_slist_* aren't threadsafe, so must be always protected by
+		 * irq_lock.
+		 */
+		key = irq_lock();
+		val = sys_slist_get(&queue->data_q);
+		irq_unlock(key);
+	} while(!val && timeout == K_FOREVER);
```
Comment (cvinayak) [inline kernel/queue.c]: Prefer a onetime if-clause to check timeout == K_FOREVER, avoids extra branch-instructions in a loop.

File: kernel/queue.c [hunk 3]
```diff
@@ -207,19 +207,23 @@ static void *k_queue_poll(struct k_queue *queue, s32_t timeout)
...
 
-	__ASSERT_NO_MSG(event.state == K_POLL_STATE_FIFO_DATA_AVAILABLE);
+		__ASSERT_NO_MSG(event.state ==
+				K_POLL_STATE_FIFO_DATA_AVAILABLE);
+
+		/* sys_slist_* aren't threadsafe, so must be always protected by
+		 * irq_lock.
+		 */
+		key = irq_lock();
+		val = sys_slist_get(&queue->data_q);
```
Comment (cvinayak) [inline kernel/queue.c]: if canceled, val will be NULL, does this satisfy the cancelled usecase?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: kernel/queue.c [hunk 4]
```diff
@@ -205,21 +205,25 @@ static void *k_queue_poll(struct k_queue *queue, s32_t timeout)
...
+		irq_unlock(key);
+	} while (!val && timeout == K_FOREVER);
```
Comment (cvinayak) [inline kernel/queue.c]: Can we have a if-clause outside loop to check timeout == K_FOREVER? This is to avoid branching in loop. Lesser CPU time.

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: kernel/queue.c (hunk 3 above)
Comment (carlescufi) [reply kernel/queue.c]: If cancelled won't k_poll() return -EINT?

Comment (Vudentz) [reply kernel/queue.c]: k_poll doesn't return -EINT, not sure if there is anything that returns EINT actually.

File: kernel/queue.c (hunk 4 above)
Comment (Vudentz) [reply kernel/queue.c]: Hmm where would you put it though? Btw, are you sure this would be optimized away by the compiler?

File: kernel/queue.c (hunk 3 above)
Comment (pfalcon) [reply kernel/queue.c]: Indeed, not sure how this would work with k_fifo_cancel_wait().

Comment (carlescufi) [reply kernel/queue.c]: So what do we expect to happen when k_fifo_cancel_wait() is called? we expect k_poll() to return err != 0?

File: kernel/queue.c (hunk 4 above)
Comment (carlescufi) [reply kernel/queue.c]: @Vudentz I think @cvinayak means an early check to iterate to avoid having to test for K_FOREVER in every iteration of the loop

File: kernel/queue.c (hunk 3 above)
Comment (pfalcon) [reply kernel/queue.c]: Well, we expect k_fifo_get() to return with NULL. How that is achieved is an implementation detail, but that case isn't handled by this patch.

Comment (Vudentz) [reply kernel/queue.c]: It is clearly not handling it, weird I thought we had a test for it, apparently not. It is probably because only the fifo tests are testing this which does not select CONFIG_POLL.

File: kernel/queue.c [hunk 5]
```diff
@@ -205,21 +203,25 @@ static void *k_queue_poll(struct k_queue *queue, s32_t timeout)
...
-	event.state = K_POLL_STATE_NOT_READY;
+	do {
+		event.state = K_POLL_STATE_NOT_READY;
 
-	err = k_poll(&event, 1, timeout);
-	if (err) {
-		return NULL;
-	}
+		err = k_poll(&event, 1, timeout);
+		if (err) {
```
Comment (cvinayak) [inline kernel/queue.c]: Are you missing the check for -EINVAL?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: kernel/queue.c (hunk 5 above)
Comment (carlescufi) [reply kernel/queue.c]: Does it matter? if it's any error you return NULL anyway?

Comment (cvinayak) [reply kernel/queue.c]: ah ok.

Comment (Vudentz) [reply kernel/queue.c]: Yep, any error here will cause it to return NULL which is what the user of k_queue_cancel_wait would expect according to its documentation.

**Review by carlescufi — APPROVED** [review]
This patch guarantees a non-NULL return value for k_queue_get(). Verified with testbench

**Comment by carlescufi** [comment]
@nashif @andrewboie @andyross this re-establishes the "queue contract" between kernel and application, returning always != NULL. We'd like to backport this to 1.9.2 in order to provide a stable 1.9.x build. Any comments appreciated.

File: kernel/poll.c [hunk 6]
```diff
@@ -292,7 +292,8 @@ static int _signal_poll_event(struct k_poll_event *event, u32_t state,
 
 	_unpend_thread(thread);
 	_abort_thread_timeout(thread);
-	_set_thread_return_value(thread, 0);
+	_set_thread_return_value(thread,
+				 state == K_POLL_STATE_NOT_READY ? -EINVAL : 0);
```
Comment (pfalcon) [inline kernel/poll.c]: Is EINVAL a good error here? It's meaning is "invalid *input* value" or "invalid value", there's nothing invalid in K_POLL_STATE_NOT_READY, it's just a special value to act upon. Previously, EINTR was mentioned, or we definitely use EAGAIN in somewhat similar contexts.

Comment (cvinayak) [reply kernel/poll.c]: Would -ECANCELED be more relevant?

File: kernel/queue.c (hunk 4 above)
Comment (cvinayak) [reply kernel/queue.c]: @Vudentz my suggested diff to current code in this PR: https://gist.github.com/cvinayak/9bb2e7dc5da943df926cf48c4df3d169

or plain code:
https://gist.github.com/cvinayak/5f5dfed8b018038f98c34e7f6b2f68c8

File: kernel/poll.c (hunk 6 above)
Comment (Vudentz) [reply kernel/poll.c]: Changed that to -EINTR, for whatever reason I thought that was not available on zephyr.

File: kernel/queue.c (hunk 4 above)
Comment (Vudentz) [reply kernel/queue.c]: @cvinayak Since the loop does actually contain a call that can sleep/pend I don't think we need such optimization since it is very unlikely we will get many NULLs in a row to cause a substantial difference.

**Comment by pfalcon** [comment]
Tested to not affect samples/net/sockets/dumb_http_server. (I'd like to do more testing with MicroPython before posting "approve" from my side.)

File: kernel/queue.c (hunk 4 above)
Comment (cvinayak) [reply kernel/queue.c]: @Vudentz its hard for me to see a while-condition with a variable that does not change inside the loop. There is always the possibility with the correct frequency of IRQ this loop can run for many iterations.

**Review by cvinayak — APPROVED** [review]

**Comment by carlescufi** [comment]
Retested on top of all 1.9.2 patches, no issues.

**Review by pfalcon — APPROVED** [review]
In addition to my previous comment, also tested with MicroPython networking sample apps: test_dl - works as expected; http_server - does have some issues (unlike the C code of dump_http_server), but they also happen without this patch, and I didn't notice any correlation between nature/frequency of the issues and presence/absence on this patch.

So, clear from my side.

**Review by tyrantlizard77 — APPROVED** [review]

File: kernel/queue.c (hunk 4 above)
Comment (andyross) [reply kernel/queue.c]: FWIW: the compiler will surely hoist that "timeout == K_FOREVER" out of the loop.  I guess we could check the assembly to be sure, but I don't see anything with this as written.  It's clear and relying on a compiler optimizer is something we always do anyway.

File: kernel/queue.c [hunk 7]
```diff
@@ -205,21 +205,25 @@ static void *k_queue_poll(struct k_queue *queue, s32_t timeout)
...
+			return NULL;
+		}
 
-	__ASSERT_NO_MSG(event.state == K_POLL_STATE_FIFO_DATA_AVAILABLE);
+		__ASSERT_NO_MSG(event.state ==
+				K_POLL_STATE_FIFO_DATA_AVAILABLE);
+
+		/* sys_slist_* aren't threadsafe, so must be always protected by
+		 * irq_lock.
```
Comment (andyross) [inline kernel/queue.c]: Not sure you really need this comment.  It's clear what is happening from the context.

**Review by andyross — CHANGES_REQUESTED** [review]
Can you explain why exactly this is happening?  This sounds like a bug to me.  It's true that in classic Unix a "system call interrupted" condition would produce behavior like this, but that's not the way k_poll() works.

And in any case, why wouldn't -EAGAIN be a better return value?

Basically EINTR is old-school unix voodoo, not something with a clear meaning to a modern system.

File: kernel/queue.c (hunk 7 above)
Comment (pfalcon) [reply kernel/queue.c]: That comment was added by me in the previous commit (this patch just moves it around). I doubt that it's "clear what is happening", because nobody was able to tell what's wrong in the original issue https://github.com/zephyrproject-rtos/zephyr/issues/4022 for 1.5 months.

**Review by andyross — APPROVED** [review]
OK, never mind.  I see where that EINTR is coming from in the future patch.  Honestly I think think you want EAGAIN here ("another thread cancelled it" is not what Unix meant by EINTR), but that's minor.

**Comment by pfalcon** [comment]
>  Honestly I think think you want EAGAIN here ("another thread cancelled it" is not what Unix meant by EINTR), but that's minor.

I'd +0.5 that. (I was just happy it didn't stay EINVAL as it was originally, but indeed, EINTR may spur some wrong associations in someone.)
