### PR TITLE
net: lib: wifi_credentials: Fix security type check while storing cre…

### LINKED ISSUE #88261: `wifi_credentials.c` security types is out of sync with `wifi.h`
**Describe the bug**
When you attempt to use the `wifi cred add` command with a newer wifi security type e.g. 10 (WPA_AUTO_PERSONAL) the command stores the credential correctly. However when you then try to auto connect you get this error:
```
<err> wifi_credentials: Requested WiFi credentials entry is corrupted
An error occurred when trying to load credentials for network "Testap". err: -71
```
This is because in  there is a fixed list of acceptable wifi security types inside the `wifi_credentials_get_by_ssid_personal_struct` function and this list does not align with `wifi_security_type`

**To Reproduce**
Wifi shell app with wifi credential manager turned on.

```
wifi cred add -s Testap -p password -k 10

wifi cred list
*error*

wifi cred auto_connect
*error*
```

**Expected behavior**
```
wifi cred add -s Testap -p password -k 10

wifi cred list
*valid list*

wifi cred auto_connect
connected
```

**Impact**
Wifi credential system not usable in main with otherwise supported security modes

**Environment (please complete the following information):**

 - OS: Ubuntu
 - Toolchain Zephyr SDK
 - 8f2f97ce320ae184e3b2f572436a3758580205fe

Related to [!86918](https://github.com/zephyrproject-rtos/zephyr/pull/86918) NCS merged wifi additions are not up to date with the current state of the `wifi_security_type` enum.

### PR DESCRIPTION
**Pull request by D-Triveni**
…dentials

Fix credential store corruption issue caused by missing security type checks. Add support for all valid security types to ensure credentials are parsed correctly.

Fixes #88261.

### CODE REVIEW

File: subsys/net/lib/wifi_credentials/wifi_credentials.c [hunk 1]
```diff
@@ -132,12 +133,14 @@ int wifi_credentials_get_by_ssid_personal_struct(const char *ssid, size_t ssid_l
...
 	}
 
-	if (buf->header.type != WIFI_SECURITY_TYPE_NONE &&
-	    buf->header.type != WIFI_SECURITY_TYPE_PSK &&
-	    buf->header.type != WIFI_SECURITY_TYPE_PSK_SHA256 &&
-	    buf->header.type != WIFI_SECURITY_TYPE_SAE &&
-	    buf->header.type != WIFI_SECURITY_TYPE_EAP_TLS &&
-	    buf->header.type != WIFI_SECURITY_TYPE_WPA_PSK) {
+	for (int security_type = 0; security_type <= WIFI_SECURITY_TYPE_MAX; security_type++) {
+		if (buf->header.type == security_type) {
```
Comment (rlubos) [inline subsys/net/lib/wifi_credentials/wifi_credentials.c:137]: Can't we just check if `buf->header.type < 0 || buf->header.type > WIFI_SECURITY_TYPE_MAX` instead of looping all of the integers in range?

Comment (D-Triveni) [reply subsys/net/lib/wifi_credentials/wifi_credentials.c]: Updated.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
