### PR TITLE
tests: bluetooth: tester: L2CAP ECFC tests fixes

### LINKED ISSUE #38938: Bluetooth tester application should be able return L2CAP ECFC credits on demand
**Describe the bug**
Some qualification tests require that IUT is capable on returning credits only on on-demand from upper tester.

**Impact**
Qualification tests are not passing consistently which is affecting BLE qualification.

### PR DESCRIPTION
**Pull request by sjanc**
Fixes #38938

### CODE REVIEW

File: tests/bluetooth/tester/src/l2cap.c [hunk 1]
```diff
@@ -404,6 +415,31 @@ static void listen(uint8_t *data, uint16_t len)
...
+	if (!chan->in_use) {
+		goto fail;
+	}
+
+	if (chan->nbuf && bt_l2cap_chan_recv_complete(&chan->le.chan,
+							chan->nbuf) < 0) {
+		goto fail;
+	}
+
+	chan->nbuf = NULL;
```
Comment (jhedberg) [inline tests/bluetooth/tester/src/l2cap.c:432]: How does the reference counting of this buffer work? I don't seen any usage of `net_buf_ref()` or `net_buf_unref()`?

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: tests/bluetooth/tester/src/l2cap.c (hunk 1 above)
Comment (sjanc) [reply tests/bluetooth/tester/src/l2cap.c:432]: My understanding was that returning -EINPROGRESS in recv callback give ownership to user and thus extra reffing is not needed cause it will be returned back to host via bt_l2cap_chan_recv_complete() call

I can add reffing it it is required but from quick look at shell sample it seems it is not needed.

Comment (jhedberg) [reply tests/bluetooth/tester/src/l2cap.c:432]: No need to add if it's all as intended, but I'd at least add code comments to explain why this is correct behaviour. What about the case when bt_l2cap_chan_recv_complete() fails and `chan->nbuf` remains set? When will it be freed?

Comment (sjanc) [reply tests/bluetooth/tester/src/l2cap.c:432]: hmm right, I'll clean it in disconnected callback

File: tests/bluetooth/tester/src/l2cap.c [hunk 2]
```diff
@@ -138,6 +155,8 @@ static struct channel *get_free_channel()
 		}
 
 		chan = &channels[i];
+
+		memset(chan, 0, sizeof(*chan));
```
Comment (Thalley) [inline tests/bluetooth/tester/src/l2cap.c:159]:
```suggestion
		(void)memset(chan, 0, sizeof(*chan));
```

File: tests/bluetooth/tester/src/l2cap.c [hunk 3]
```diff
@@ -404,6 +423,31 @@ static void listen(uint8_t *data, uint16_t len)
 		   BTP_STATUS_FAILED);
 }
 
+static void credits(uint8_t *data, uint16_t len)
+{
+	const struct l2cap_credits_cmd *cmd = (void *) data;
```
Comment (Thalley) [inline tests/bluetooth/tester/src/l2cap.c:428]:
```suggestion
	const struct l2cap_credits_cmd *cmd = (void *)data;
```

File: tests/bluetooth/tester/src/l2cap.c [hunk 4]
```diff
@@ -404,6 +423,31 @@ static void listen(uint8_t *data, uint16_t len)
...
+	struct channel *chan = &channels[cmd->chan_id];
+
+	if (!chan->in_use) {
+		goto fail;
+	}
+
+	if (chan->nbuf && bt_l2cap_chan_recv_complete(&chan->le.chan,
+							chan->nbuf) < 0) {
```
Comment (Thalley) [inline tests/bluetooth/tester/src/l2cap.c:436]:
```suggestion
	if (chan->nbuf && bt_l2cap_chan_recv_complete(&chan->le.chan,
						      chan->nbuf) < 0) {
```

Comment (sjanc) [reply tests/bluetooth/tester/src/l2cap.c:436]: will fix those,  but wonder why it wasn't catch by CI..

Comment (Thalley) [reply tests/bluetooth/tester/src/l2cap.c]: CI doesn't ensure that the indentation is "correct" only that tabs comes before spaces and never after.

**Comment by sjanc** [comment]
ping,  would be good to get this in before Friday so that it is part of weekend autopts run

**Review by carlescufi — APPROVED** [review]

File: tests/bluetooth/tester/src/l2cap.c [hunk 5]
```diff
@@ -58,6 +59,17 @@ static int recv_cb(struct bt_l2cap_chan *l2cap_chan, struct net_buf *buf)
 	tester_send(BTP_SERVICE_ID_L2CAP, L2CAP_EV_DATA_RECEIVED,
 		    CONTROLLER_INDEX, recv_cb_buf, sizeof(*ev) + buf->len);
 
+	/* TODO should be list but since currently only 1 credit is
+	 * supported we can keep it simpler for now
+	 */
+	if (!chan->nbuf) {
+		/* no need for extra ref, as when returning EINPROGRESS user
```
Comment (alwa-nordic) [inline tests/bluetooth/tester/src/l2cap.c:66]: That the ownership of the reference `buf` depends on the return value of this callback is such an unexpected contract. It's not documented on `struct bt_l2cap_chan_ops :: recv`. Are we sure that it's like this? Can you confirm, @joerchan? I would expect either that the reference `buf` is always moved or always borrowed into this function.

By "Moved", I mean caller gave away ownership by calling and never uses this copy of the reference again not free it and must assume it has already been `net_buf_unref`ed.

By "Borrowed" I mean caller assumes it has ownership of the reference when the control returns and this function has to copy the reference (i.e. by net_buf_ref) if it wants it to live beyond this function.

Comment (alwa-nordic) [inline tests/bluetooth/tester/src/l2cap.c:66]: I would avoid the word "user" here. Can we say "This function gains ownership of reference `buf` if it returns -EINPROGRESS.".

**Review by alwa-nordic — CHANGES_REQUESTED** [review]
I'm in the dark about what this code does, as I'm not familiar with tester. And so, I don't know what `credits()` and `recv_cb()` are meant to do, since they have no doc and have names that say where to use them, not what they do. I think we should have someone familiar with tester have a quick look.

There should probably be a comment "naming" (as if it was a function name) the new code in `recv_cb`.

File: tests/bluetooth/tester/src/l2cap.c (hunk 5 above)
Comment (sjanc) [reply tests/bluetooth/tester/src/l2cap.c:63]: It is quite clear to me. With EINPROGRESS netbuf needs to be returned either via bt_l2cap_chan_recv_complete() or with unref (eg upon disconnection).

File: tests/bluetooth/tester/src/l2cap.c [hunk 6]
```diff
@@ -58,6 +59,17 @@ static int recv_cb(struct bt_l2cap_chan *l2cap_chan, struct net_buf *buf)
 	tester_send(BTP_SERVICE_ID_L2CAP, L2CAP_EV_DATA_RECEIVED,
 		    CONTROLLER_INDEX, recv_cb_buf, sizeof(*ev) + buf->len);
 
+	/* TODO should be list but since currently only 1 credit is
```
[the remark this answers is not in the document]
Comment (sjanc) [reply tests/bluetooth/tester/src/l2cap.c]: static assert is not valid here since this requirement (1 credit) is handled in runtime (we return EINPROGRESS only once)

File: tests/bluetooth/tester/src/l2cap.c [hunk 7]
```diff
@@ -404,6 +423,31 @@ static void listen(uint8_t *data, uint16_t len)
...
+static void credits(uint8_t *data, uint16_t len)
+{
+	const struct l2cap_credits_cmd *cmd = (void *)data;
+	struct channel *chan = &channels[cmd->chan_id];
+
+	if (!chan->in_use) {
+		goto fail;
+	}
+
+	if (chan->nbuf && bt_l2cap_chan_recv_complete(&chan->le.chan,
```
[the remark this answers is not in the document]
Comment (sjanc) [reply tests/bluetooth/tester/src/l2cap.c]: OK

**Review by Thalley — APPROVED** [review]
My comments have been addressed

**Comment by sjanc** [comment]
#AutoPTS run L2CAP/ECFC

**Comment by carlescufi** [comment]
@jhedberg @alwa-nordic please revisit

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No regressions found.
No progresses found.

**Comment by sjanc** [comment]
fixes #38938 38938

**Review by jhedberg — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]
