### PR TITLE
drivers: usb_mcux: Fix disable and reset functions

### LINKED ISSUE #55595: ci: [test.device][mimxrt1060_evk] [usb.device.usb_disable] disable usb fail
**Describe the bug**
ssertion failed at WEST_TOPDIR/zephyr/tests/subsys/usb/device/src/main.c:96: device_usb_test_usb_disable: (usb_disable() not equal to TC_PASS)

Please also mention any information which could help others to understand
the problem you're facing:

in NXP RT10xx series usb.device.usb_disable keeps fails.

**To Reproduce**
cd tests/subsys/usb/device
west build -b mimxrt1060_evk
west flash --runner=pyocd

**Expected behavior**
test pass

**Impact**
use device disable function

**Logs and console output**

```
*** Booting Zephyr OS build zephyr-v3.3.0-853-g419dda3ed72d ***
Running TESTSUITE device_usb
===================================================================
D: lock usb_enable_lock mutex
D: Attached
D: set cb, ep: 0x81
D: unlock usb_enable_lock mutex
START - test_usb_dc_api
 PASS - test_usb_dc_api in 0.001 seconds
===================================================================
START - test_usb_dc_api_invalid
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
 PASS - test_usb_dc_api_invalid in 0.040 seconds
===================================================================
START - test_usb_dc_api_read_write
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
 PASS - test_usb_dc_api_read_write in 0.007 seconds
===================================================================
START - test_usb_deconfig
 PASS - test_usb_deconfig in 0.001 seconds
===================================================================
START - test_usb_disable
W: Device not attached
E: Failed to disable ep 0x00
E: Failed to disable endpoint 0x00

    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/usb/device/src/main.c:96: device_usb_test_usb_disable: (usb_disable() not equal to TC_PASS)
usb_disable() failed
 FAIL - test_usb_disable in 0.023 seconds
===================================================================
TESTSUITE device_usb failed.

------ TESTSUITE SUMMARY START ------

SUITE FAIL -  80.00% [device_usb]: pass = 4, fail = 1, skip = 0, total = 5 duration = 0.072 seconds
 - PASS - [device_usb.test_usb_dc_api] duration = 0.001 seconds
 - PASS - [device_usb.test_usb_dc_api_invalid] duration = 0.040 seconds
 - PASS - [device_usb.test_usb_dc_api_read_write] duration = 0.007 seconds
 - PASS - [device_usb.test_usb_deconfig] duration = 0.001 seconds
 - FAIL - [device_usb.test_usb_disable] duration = 0.023 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED

```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: zephyr-v3.3.0-853-g419dda3ed72d

**Additional context**
This cases fails since created

### PR DESCRIPTION
**Pull request by mmahadevan108**
1. Fix the reset function to reset correctly.
2. Ensure the controller handle is initialized before calling the SDK functions.

Fixes #55595

### CODE REVIEW

**Comment by dleach02** [comment]
@hakehuang can you regression test this to confirm it addresses the issue you submitted?

File: drivers/usb/device/usb_dc_mcux.c [hunk 1]
```diff
@@ -470,12 +467,14 @@ int usb_dc_ep_disable(const uint8_t ep)
 		return -EINVAL;
 	}
 
-	status = dev_state.dev_struct.controllerInterface->deviceCancel(
-						  dev_state.dev_struct.controllerHandle,
-						  ep);
-	if (kStatus_USB_Success != status) {
-		LOG_ERR("Failed to disable ep 0x%02x", ep);
-		return -EIO;
+	if (dev_state.dev_struct.controllerHandle != NULL) {
```
Comment (decsny) [inline drivers/usb/device/usb_dc_mcux.c:470]: just wondering why do we check for this here now?

**Review by decsny — APPROVED** [review]

**Comment by hakehuang** [comment]
> @hakehuang can you regression test this to confirm it addresses the issue you submitted?

fixed

```
*** Booting Zephyr OS build v3.4.0-rc1-96-g1b2679c8854d ***
Running TESTSUITE device_usb
===================================================================
D: lock usb_enable_lock mutex
D: Attached
D: set cb, ep: 0x81
D: unlock usb_enable_lock mutex
START - test_usb_dc_api
 PASS - test_usb_dc_api in 0.001 seconds
===================================================================
START - test_usb_dc_api_invalid
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
 PASS - test_usb_dc_api_invalid in 0.040 seconds
===================================================================
START - test_usb_dc_api_read_write
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
 PASS - test_usb_dc_api_read_write in 0.007 seconds
===================================================================
START - test_usb_deconfig
 PASS - test_usb_deconfig in 0.001 seconds
===================================================================
START - test_usb_disable
D: Detached
 PASS - test_usb_disable in 0.002 seconds
===================================================================
TESTSUITE device_usb succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [device_usb]: pass = 5, fail = 0, skip = 0, total = 5 duration = 0.051 seconds
 - PASS - [device_usb.test_usb_dc_api] duration = 0.001 seconds
 - PASS - [device_usb.test_usb_dc_api_invalid] duration = 0.040 seconds
 - PASS - [device_usb.test_usb_dc_api_read_write] duration = 0.007 seconds
 - PASS - [device_usb.test_usb_deconfig] duration = 0.001 seconds
 - PASS - [device_usb.test_usb_disable] duration = 0.002 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL

```

File: drivers/usb/device/usb_dc_mcux.c (hunk 1 above)
Comment (mmahadevan108) [reply drivers/usb/device/usb_dc_mcux.c:470]: The test is calling `usb_dc_ep_disable` before the endpoint is initialized which is a valid scenario.

**Review by tmon-nordic — APPROVED** [review]

**Comment by hakehuang** [comment]
@mmahadevan108 , although it is fixed in imxrt series, in RC3 regression test, I find this fix is not valid in lpc series. e.g. for lpcxpresso55s28 board, I get below error

```
*** Booting Zephyr OS build v3.4.0-rc3 ***
Running TESTSUITE device_usb
===================================================================
D: lock usb_enable_lock mutex
D: Attached
D: set cb, ep: 0x81
D: unlock usb_enable_lock mutex
START - test_usb_dc_api
PASS - test_usb_dc_api in 0.001 seconds
===================================================================
START - test_usb_dc_api_invalid
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
PASS - test_usb_dc_api_invalid in 0.040 seconds
===================================================================
START - test_usb_dc_api_read_write
E: Wrong endpoint index/address/direction
E: Wrong endpoint index/address
PASS - test_usb_dc_api_read_write in 0.007 seconds
===================================================================
START - test_usb_deconfig
PASS - test_usb_deconfig in 0.001 seconds
===================================================================
START - test_usb_disable
Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/usb/device/src/main.c:96: device_usb_test_usb_disable: (usb_disable() not equal to TC_PASS)
usb_disable() failed
FAIL - test_usb_disable in 0.016 seconds
===================================================================
TESTSUITE device_usb failed.
------ TESTSUITE SUMMARY START ------
SUITE FAIL -  80.00% [device_usb]: pass = 4, fail = 1, skip = 0, total = 5 duration = 0.065 seconds
- PASS - [device_usb.test_usb_dc_api] duration = 0.001 seconds
- PASS - [device_usb.test_usb_dc_api_invalid] duration = 0.040 seconds
- PASS - [device_usb.test_usb_dc_api_read_write] duration = 0.007 seconds
- PASS - [device_usb.test_usb_deconfig] duration = 0.001 seconds
- FAIL - [device_usb.test_usb_disable] duration = 0.016 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: f06239b56efb8323177180ca1ed4587f
PROJECT EXECUTION FAILED

```
