### PR TITLE
tests: kernel: work_queue_api: relax test to eliminate racy checks

### LINKED ISSUE #29329: tests: kernel.workqueue.api tests fail on multiple platforms
**Describe the bug**
Tests "work_submit_to_multipleq" and "work_resubmit_nowait_to_queue " from "tests/kernel/workq/work_queue_api" fail on nrf platforms (nrf52840dk_nrf52840, nrf52dk_nrf52832 and nrf9160dk_nrf9160)

**To Reproduce**
1. go to zephyr dir
2. call `./scripts/sanitycheck --hardware-map map.yml --device-testing -T tests/kernel/workq/work_queue_api/`
3. See error

**Expected behavior**
The tests pass

**Impact**
Not clear

**Logs and console output**

```
 START - test_work_submit_to_multipleq Assertion failed at CMAKE_SOURCE_DIR/src/main.c:277: twork_submit_multipleq: k_delayed_work_pending(&new_work) is false FAIL - test_work_submit_to_multipleq
 ```
and
```
START - test_work_resubmit_nowait_to_queue Assertion failed at CMAKE_SOURCE_DIR/src/main.c:357: twork_resubmit_nowait: k_work_pending(&delayed_work_sleepy.work) is true FAIL - test_work_resubmit_nowait_to_queue 
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr SDK v0.11.3
 - Zephyr version: zephyr-v2.4.0-685-g7e64fba9ed

### PR DESCRIPTION
**Pull request by pabigot**
We can't control ticks accurately enough to detect the transition
between on a queue and being handled, so relax the checks to make
things pass.

Fixes #29329

### CODE REVIEW

File: tests/kernel/workq/work_queue_api/src/main.c [hunk 1]
```diff
@@ -353,7 +355,9 @@ static void twork_resubmit_nowait(void *data)
 	zassert_true(k_work_pending(&delayed_work[1].work), NULL);
 
 	/* Release sleeper, check other two still pending */
-	k_usleep(1);
+	do {
+		k_usleep(1);
+	} while (k_work_pending(&delayed_work_sleepy.work));
```
Comment (andyross) [inline tests/kernel/workq/work_queue_api/src/main.c:360]: If this is trying to assume that the the "sleepy" item is definitely going to have executed after 1us in all configurations, then that's a test bug as it's sensitive to tick rate.  You probably want k_sleep(K_TICKS(1)) here instead.

Comment (pabigot) [reply tests/kernel/workq/work_queue_api/src/main.c:360]: Whether it's `k_sleep(K_TICKS(1))` or `k_usleep(1)` the first-submitted work item doesn't get processed until either 1 or 2 of these sleeps occur.  The preceding test abuses the API by reaching in and mutating the queue, so it may be that the thread is being caught in different states, one of which requires a second chance to run.

**Comment by PerMac** [comment]
The tests pass on nrf boards when checked-out on this PR.

**Comment by maksimmasalski** [comment]
+1 to Maciej.
The tests passes on the mec15xxevb_assy6853 (Microchip) board when checked-out on this PR too.

`INFO    - 1/1 mec15xxevb_assy6853       tests/kernel/workq/work_queue_api/kernel.workqueue.api PASSED (device 56.331s)`

**Review by maksimmasalski — APPROVED** [review]

**Review by nashif — APPROVED** [review]
