### PR TITLE
Bluetooth: Tests: Fix `bt_buf_get_evt` test

### LINKED ISSUE #55957: bluetooth.host.bt_buf_get_evt tests fail with host GCC 11
**Describe the bug**

The `bluetooth.host.bt_buf_get_evt` tests fail when building with the host GCC 11.3.

Note that these tests succeed when building with the host GCC 9.3, which is the default GCC version in Ubuntu 20.04 and currently used in the main CI.

**To Reproduce**

```
scripts/twister -v -N -p unit_testing -s tests/bluetooth/host/buf/bt_buf_get_evt/bluetooth.host.bt_buf_get_evt.hci_acl_flow_control
```

**Expected behavior**

Test passes.

**Impact**

Unable to successfully run these tests on Ubuntu 22.04, which comes with GCC 11.3 as the host compiler by default.

**Logs and console output**

```
ERROR   - Running TESTSUITE bt_buf_get_evt_cmd_type_returns_not_null
===================================================================
START - test_return_value_matches_bt_buf_get_cmd_complete_not_null
 PASS - test_return_value_matches_bt_buf_get_cmd_complete_not_null in 0.000 seconds
===================================================================
TESTSUITE bt_buf_get_evt_cmd_type_returns_not_null succeeded
Running TESTSUITE bt_buf_get_evt_cmd_type_returns_null
===================================================================
START - test_return_value_matches_bt_buf_get_cmd_complete_null
 PASS - test_return_value_matches_bt_buf_get_cmd_complete_null in 0.000 seconds
===================================================================
TESTSUITE bt_buf_get_evt_cmd_type_returns_null succeeded
Running TESTSUITE bt_buf_get_evt_default_events_returns_not_null
===================================================================
START - test_returns_not_null
 PASS - test_returns_not_null in 0.000 seconds
===================================================================
TESTSUITE bt_buf_get_evt_default_events_returns_not_null succeeded
Running TESTSUITE bt_buf_get_evt_default_events_returns_null
===================================================================
START - test_returns_null
 PASS - test_returns_null in 0.000 seconds
===================================================================
TESTSUITE bt_buf_get_evt_default_events_returns_null succeeded
Running TESTSUITE bt_buf_get_evt_num_completed_pkts_type
===================================================================
START - test_returns_not_null

    Assertion failed at /__w/zephyr-testing/zephyr-testing/tests/bluetooth/host/buf/mocks/net_buf_expects.c:19: expect_single_call_net_buf_alloc: (net_buf_alloc_fixed_fake.arg0_val not equal to pool)
'net_buf_alloc_fixed()' was called with incorrect 'pool' value
 at test function
 FAIL - test_returns_not_null in 0.000 seconds
===================================================================
START - test_returns_null
 PASS - test_returns_null in 0.000 seconds
===================================================================
TESTSUITE bt_buf_get_evt_num_completed_pkts_type failed.

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [bt_buf_get_evt_cmd_type_returns_not_null]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.000 seconds
 - PASS - [bt_buf_get_evt_cmd_type_returns_not_null.test_return_value_matches_bt_buf_get_cmd_complete_not_null] duration = 0.000 seconds

SUITE PASS - 100.00% [bt_buf_get_evt_cmd_type_returns_null]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.000 seconds
 - PASS - [bt_buf_get_evt_cmd_type_returns_null.test_return_value_matches_bt_buf_get_cmd_complete_null] duration = 0.000 seconds

SUITE PASS - 100.00% [bt_buf_get_evt_default_events_returns_not_null]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.000 seconds
 - PASS - [bt_buf_get_evt_default_events_returns_not_null.test_returns_not_null] duration = 0.000 seconds

SUITE PASS - 100.00% [bt_buf_get_evt_default_events_returns_null]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.000 seconds
 - PASS - [bt_buf_get_evt_default_events_returns_null.test_returns_null] duration = 0.000 seconds

SUITE FAIL -  50.00% [bt_buf_get_evt_num_completed_pkts_type]: pass = 1, fail = 1, skip = 0, total = 2 duration = 0.000 seconds
 - FAIL - [bt_buf_get_evt_num_completed_pkts_type.test_returns_not_null] duration = 0.000 seconds
 - PASS - [bt_buf_get_evt_num_completed_pkts_type.test_returns_null] duration = 0.000 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Toolchain: GCC 11.3.0
 - Commit SHA: 44a8b70cccafe312a1a091de48a5ba204dadd6bb

### PR DESCRIPTION
**Pull request by theob-pro**
Fix #55957. 

The `bt_buf_get_evt` test was using `net_buf` structures without allocating it properly.

### CODE REVIEW

**Review by alwa-nordic — DISMISSED** [review]

File: tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c [hunk 1]
```diff
@@ -92,14 +92,17 @@ static struct net_buf_pool *get_memory_pool(bool discardable)
  */
 ZTEST(bt_buf_get_evt_default_events_returns_not_null, test_returns_not_null)
 {
-	static struct net_buf expected_buf;
+#define USER_DATA_SIZE sizeof(struct bt_buf_data)
```
Comment (stephanosio) [inline tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c:95]: This is a rather strange place to define a macro, especially because its scope is not limited to this function.

Please move the macro definition to the top of the file, or make it `const size_t user_data_size = sizeof(struct bt_buf_data)` instead.

Comment (jori-nordic) [inline tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c:95]: you could instead define a static inline fn in `zephyr/tests/bluetooth/host/buf/mocks/buf_help_utils.h` to allocate a net_buf with a given size (and set the user_data_size).

**Review by jori-nordic — CHANGES_REQUESTED** [review]

File: tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c [hunk 2]
```diff
@@ -92,14 +92,17 @@ static struct net_buf_pool *get_memory_pool(bool discardable)
...
+	struct net_buf *expected_buf = alloca(sizeof(struct net_buf) + USER_DATA_SIZE);
```
Comment (stephanosio) [inline tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c:96]: Using `alloca` can potentially cause portability issues because it is not a standard function (not part of ISO C or even POSIX).

`alloca` or VLA should not even be necessary here since all size components are statically computable.

**Review by stephanosio — CHANGES_REQUESTED** [review]

File: tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c (hunk 2 above)
Comment (theob-pro) [reply tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c:96]: Thanks, we were not aware that `alloca` is non-standard.

> `alloca` or VLA should not even be necessary here since all size components are statically computable.

Can you elaborate on this? `struct net_buf` has a flexible array member. We are not sure how to legally instantiate this object without a `malloc`-like. I suppose putting it an an union with a char-array, or just type-pun an array will likely work. But is that legal?

Comment (stephanosio) [reply tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c:96]: Something like:

```c
char expected_buf_data[SIZE];
struct net_buf *expected_buf = (struct net_buf *)expected_buf_data;
```

> But is that legal?

Yes. Essentially, it is not any different from assigning the return value of `alloca`, which is `void *`, to `struct net_buf *`.

File: tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c [hunk 3]
```diff
@@ -92,14 +92,18 @@ static struct net_buf_pool *get_memory_pool(bool discardable)
  */
 ZTEST(bt_buf_get_evt_default_events_returns_not_null, test_returns_not_null)
 {
-	static struct net_buf expected_buf;
+	const size_t user_data_size = sizeof(struct bt_buf_data);
+	uint8_t expected_buf_data[user_data_size];
+	struct net_buf *expected_buf = (struct net_buf *)expected_buf_data;
```
Comment (jori-nordic) [inline tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c:97]: how does this work? you're casting a size 1 array to a struct net_buf (with much more than 1 byte).

**Review by jori-nordic — CHANGES_REQUESTED** [review]

File: tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c (hunk 3 above)
Comment (theob-pro) [reply tests/bluetooth/host/buf/bt_buf_get_evt/src/main.c:97]: I think I made a mistake. `expected_buf_data` should be `sizeof(struct net_buf) + user_data_size`.

**Review by jori-nordic — APPROVED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
