### PR TITLE
Bluetooth: Controller: Fix auxiliary scan stop assertion check

### LINKED ISSUE #50432: Bluetooth: Controller: Restarting BLE scanning not always working and sometimes crashes together with periodic. adv.
**Describe the bug**
There are 3 sub issues, all related to the same scenario hence I made one ticket. Write if you want it split.
1. Restarting scanning with `bt_le_scan_stop` followed by `bt_le_scan_start` sometimes fails. `bt_le_scan_start` returns success, but scanning either not started or just a few events are received before it stops reporting anything from controller (maybe similar to https://github.com/zephyrproject-rtos/zephyr/issues/49915). Doing an additional disable/enable when this happens makes it working again.
2. There is a crash in `Scan disable...ASSERTION FAIL [!aux->parent] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_scan.c:647` sometimes when calling `bt_le_scan_stop`
3. Sometimes `bt_le_scan_stop` returns -5 (I/O error) in the sample application, I don't think it should.
 
 - What target platform are you using? nRF52833, Zephyr 
 - Is this a regression? Not tested this scenario before.

**To Reproduce**
Have 10+ tags sending per. adv. with 7.5ms interval and CTE enabled. 
Build and flash the application below. Then wait... 

Application: 
[aoa_receiver_multiple-gh-50432.zip](https://github.com/zephyrproject-rtos/zephyr/files/9609288/aoa_receiver_multiple-gh-50432.zip)

Relevant configs (see attached application for more info):
```
CONFIG_BT_CTLR_ADVANCED_FEATURES=y
CONFIG_BT_CTLR_SCAN_AUX_SET=2

CONFIG_BT_CTLR_SYNC_PERIODIC_SKIP_ON_SCAN_AUX=y

CONFIG_BT_CTLR_SCAN_AUX_SYNC_RESERVE_MIN=n

CONFIG_BT_TICKER_LOW_LAT=n
CONFIG_BT_TICKER_PRIORITY_SET=n
CONFIG_BT_CTLR_SCAN_UNRESERVED=n # Scan only when radio is free.
```

**Expected behavior**
Scanning enable always works and no crash when scanning is turned off.

**Impact**
An application cannot know if there are no devices in the area or if `bt_le_scan_start` did not work.

**Logs and console output**
1. Log for scan enable not working:
```
...
Queued: 7 Synced: 4 Num err: 0/62
[00:00:03.413,879] <wrn> main: RESTARTING SCAN AND SYNC...
Scan disable...Success.
Start scanning...success
[00:00:03.617,706] <wrn> main: RESTARTED!
Scan is running...
Running...
TAGS:sync...,26,sync...,sync...,sync...,sync...,sync...,sync...,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,
Queued: 7 Synced: 1 Num err: 0/26
[00:00:04.618,286] <wrn> main: RESTARTING SCAN AND SYNC...
Scan disable...Success.
Scan is running...
Start scanning...success
[00:00:04.821,289] <wrn> main: RESTARTED!
Running...
TAGS:sync...,sync...,sync...,sync...,sync...,sync...,sync...,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,
Queued: 7 Synced: 0 Num err: 0/0
Running...
TAGS:sync...,sync...,sync...,sync...,sync...,sync...,sync...,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,
Queued: 7 Synced: 0 Num err: 0/0
... Nothing happens
```
2. Log for the crash:
```
...
Queued: 11 Synced: 6 Num err: 0/79
Running...
TAGS:18,sync...,sync...,0,20,sync...,12,19,20,sync...,20,sync...,12,14,11,sync...,sync...,sync...,sync...,sync...,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,
Queued: 10 Synced: 10 Num err: 0/146
[00:01:33.819,915] <wrn> main: RESTARTING SCAN AND SYNC...
Scan disable...Success.
Start scanning...success
[00:01:34.024,810] <wrn> main: RESTARTED!
Scan is running...
Running...
TAGS:sync...,sync...,sync...,sync...,28,sync...,sync...,sync...,1,sync...,sync...,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,
Queued: 9 Synced: 2 Num err: 0/29
Scan is running...
Running...
TAGS:9,18,sync...,7,54,sync...,20,sync...,13,sync...,sync...,1,sync...,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,
Queued: 6 Synced: 7 Num err: 0/122
Running...
TAGS:16,16,14,10,17,sync...,15,10,8,sync...,1,16,2,sync...,sync...,4,sync...,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,
Queued: 5 Synced: 12 Num err: 0/131
[00:01:37.027,923] <wrn> main: RESTARTING SCAN AND SYNC...
Scan disable...ASSERTION FAIL [!aux->parent] @ WEST_TOPDIR/zephyr/subsys/bluetooth/controller/ll_sw/ull_scan.c:647
[00:01:37.028,411] <err> os: r0/a1:  0x00000003  r1/a2:  0x00000005  r2/a3:  0x00000004
[00:01:37.028,411] <err> os: r3/a4:  0x00000287 r12/ip:  0x200027ac r14/lr:  0x0000da55
[00:01:37.028,442] <err> os:  xpsr:  0x41000000
[00:01:37.028,442] <err> os: Faulting instruction address (r15/pc): 0x0000da60
[00:01:37.028,472] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
[00:01:37.028,533] <err> os: Current thread: 0x20001c40 (BT TX)
[00:01:37.107,849] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: Zephyr 
 - Commit SHA or Version used: (main as of now) e1cb0845b49b6a4100c9e5558d37667b92f0d000 with  [894423e9aed34a394b97c995c33549513b0ac4a5](https://github.com/zephyrproject-rtos/zephyr/pull/50311)

### PR DESCRIPTION
**Pull request by cvinayak**
Use a local variable to assert check on auxiliary context's release.
Add missing volatile qualifier to the parent field of the auxiliary scan context.
Under race condition a released aux context can be allocated for reception of chain PDU of a periodic sync role, hence fix the assertion check to consider that the released context can be allocated to other roles.

Fixes #50432.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_scan_types.h [hunk 1]
```diff
@@ -43,7 +43,7 @@ struct ll_scan_aux_set {
 	struct lll_scan_aux lll;
 
 	/* lll_scan or lll_sync */
-	void *parent;
+	void *volatile parent;
```
Comment (fabiobaltieri) [inline subsys/bluetooth/controller/ll_sw/ull_scan_types.h:46]: Should this be `volatile void *parent`? I see this format used in another couple of places but it looks unusual to me, the vast majority of "volatile" uses in the code base use that first I think, and the pointer next to the variable name. Up to you really, I guess we have no standard, it just looks unusual to me.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_scan_types.h:46]: There is a difference in `volatile void *parent;` (or `void volatile *parent;`) here, `parent` points to an address whose content is volatile. Where as `void *volatile parent` here, content of `parent` is volatile (like  `parent` was modified in an ISR).

Comment (fabiobaltieri) [reply subsys/bluetooth/controller/ll_sw/ull_scan_types.h:46]: Ohh I see, makes sense, thanks for explaining.

File: subsys/bluetooth/controller/ll_sw/ull_scan.c [hunk 2]
```diff
@@ -639,12 +639,21 @@ uint8_t ull_scan_disable(uint8_t handle, struct ll_scan_set *scan)
...
 
-			LL_ASSERT(!aux->parent);
+			/* Use a local variable to assert on auxiliary context's
+			 * release.
+			 * Under race condition a released aux context can be
+			 * allocated for reception of chain PDU of a periodic
+			 * sync role.
+			 */
+			parent = aux->parent;
+			LL_ASSERT(!parent || (parent != aux_scan_lll));
```
Comment (ppryga-nordic) [inline subsys/bluetooth/controller/ll_sw/ull_scan.c:656]: Correct me if my understanding is wrong.
The part of assert condition `parent != aux_scan_lll` makes sure the auxiliary context was not re-used for other `scan` between call to `ull_scan_aux_stop(aux)` in line 644 and this assert, correct?
If that is true, are you sure it should assert here?

Comment (ppryga-nordic) [reply subsys/bluetooth/controller/ll_sw/ull_scan.c:656]: Ah yes. Thanks for detailed explanation.

**Review by ppryga-nordic — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
