### PR TITLE
Bluetooth: MCS: Remove the GATT include service when OTS is disabled

### LINKED ISSUE #105345: Bluetooth: MCS: Reading included services of MCS when CONFIG_BT_OTS=n fails
### Describe the bug

The `BT_MCS_SERVICE_DEFINITION` on https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/audio/mcs.c#L811 always has an include, regardless of `CONFIG_BT_OTS` is enabled, but should only have one if it includes `CONFIG_BT_OTS`. 

If `CONFIG_BT_OTS=n` and a GATT client reads the include, it fails (because the include is only properly configured when `CONFIG_BT_OTS=y` on the server. 

The weird thing is that it fails with an unknown ATT error code 0x16 as evident by the last Find By Type Request in the provided capture file. 

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

The fix should be fairly simple and just remove the `BT_GATT_INCLUDE_SERVICE` when `CONFIG_BT_OTS=n`, but it should also be investigated why the returned ATT error is 0x16 which is not a valid ATT error code.

### PR DESCRIPTION
**Pull request by vedantmalkar**
The BT_GATT_INCLUDE_SERVICE is always included in BT_MCS_SERVICE_DEFINITION even when CONFIG_BT_OTS=n, this fixes it such that it is only included when OTS is enabled.

Fixes zephyrproject-rtos#105345

### CODE REVIEW

File: subsys/bluetooth/audio/mcs.c [hunk 1]
```diff
@@ -868,17 +868,19 @@ static ssize_t read_content_ctrl_id(struct bt_conn *conn,
 		      BT_GATT_PERM_READ_ENCRYPT, \
 		      read_search_results_id, NULL, NULL), \
 	BT_AUDIO_CCC(search_results_id_cfg_changed),
+#define INCLUDE_SERVICE_IF_OTS BT_GATT_INCLUDE_SERVICE(NULL),
```
Comment (Thalley) [inline subsys/bluetooth/audio/mcs.c]:
```suggestion
#define INCLUDE_SERVICE_IF_OTS BT_GATT_INCLUDE_SERVICE(NULL), /* To be overwritten */
```

Minor: Would be nice to keep the comment

**Review by Thalley — DISMISSED** [review]

**Review by Thalley — APPROVED** [review]

**Review by sjanc — APPROVED** [review]
