### PR TITLE
lib: coap: Add coap_get_option_int public method

### LINKED ISSUE #25704: lib: updatehub: Corrupted updated when receiving CoAP duplicate packages
The updatehub library is not properly handling the case where the CoAP packages are duplicated and we end flashing a broken firmware on the device's storage.

The short term solution is to have an engine that handles these packages reception and ensures we handle the proper sequence of blocks.

### PR DESCRIPTION
**Pull request by nandojve**
Any CoAP implementation when use at least block transfer or is a server side need access some CoAP options as integer values. This add a method at public interface and defines for block wise operations to avoid code useless code duplication.

This refactor below files:
subsys/net/lib/lwm2m/lwm2m_engine.c
samples/net/sockets/coap_server/src/coap-server.c

The motivation is #25558 that needs same approach already implemented at sample and LWM2M.

### CODE REVIEW

**Comment by nandojve** [comment]
CC @otavio

File: include/net/coap.h [hunk 1]
```diff
@@ -147,6 +147,11 @@ enum coap_response_code {
```
Comment (jukkar) [inline include/net/coap.h:147]: Please change the commit subject of `lib: coap: ...` to `net: coap: ....` as we have typically named coap commits this way.

File: subsys/net/lib/lwm2m/lwm2m_engine.c [hunk 2]
```diff
@@ -142,10 +142,6 @@ static int sock_nfds;
 /* TODO: figure out what's correct value */
```
Comment (jukkar) [inline subsys/net/lib/lwm2m/lwm2m_engine.c:142]: For lwm2m commit, plase change the commit subject to `net: lwm2m: ...`

**Review by jukkar — COMMENTED** [review]
The changes look ok to me, couple of minor nits for commit subjects.

**Review by rlubos — APPROVED** [review]
LGTM, just please align with Jukka's comments.

File: subsys/net/lib/coap/coap.c [hunk 3]
```diff
@@ -1236,19 +1238,7 @@ void coap_pendings_clear(struct coap_pending *pendings, size_t len)
...
-	int r;
-
-	r = coap_find_options(cpkt, COAP_OPTION_OBSERVE, &option, count);
-	if (r <= 0) {
-		return -ENOENT;
-	}
-
-	return coap_option_value_to_int(&option);
-}
+#define get_observe_option(cpkt) get_option_int(cpkt, COAP_OPTION_OBSERVE)
```
Comment (otavio) [inline subsys/net/lib/coap/coap.c:1241]: There is no reason to keep old function name around. It is better to rework the code to use this new public method.

If desired, it can be done as another commit where old usage is reworked..

**Review by otavio — CHANGES_REQUESTED** [review]

File: subsys/net/lib/coap/coap.c (hunk 3 above)
Comment (nandojve) [reply subsys/net/lib/coap/coap.c]: Added d6a145b to make change clear.

**Review by otavio — APPROVED** [review]

**Review by mike-scott — APPROVED** [review]
LGTM

**Comment by jukkar** [comment]
@nandojve can you rebase the PR and resolve the conflicts?

**Comment by nandojve** [comment]
Rebased, chackpatch is not related with the change 'tests/kernel/lifo/lifo_usage'

**Review by jukkar — APPROVED** [review]
