### PR TITLE
modbus: fix support for floating point values

### LINKED ISSUE #68788: Modbus Holding/Input Register Read Float - Incorrect response byte size
**Describe the bug**
Using the Modbus server role, the input/holding register floating point read functions return an incorrect number of bytes. They return 64 bits (4 registers) instead of the 32 bits (2 registers) required for a 32-bit float.

A modbus client, when requesting a 32-bit float value, requests two 16-bit registers. Therefore, [`&ctx->rx_adu.data[2]`](https://github.com/zephyrproject-rtos/zephyr/blob/40b53d5d774705d27183aaa1e42f2f322250da10/subsys/modbus/modbus_server.c#L433) is `2`.

The Zephyr modbus library [then multiplies](https://github.com/zephyrproject-rtos/zephyr/blob/40b53d5d774705d27183aaa1e42f2f322250da10/subsys/modbus/modbus_server.c#L465) the number of registers (2) by the size of a float (32) and thinks it should return 64 bits. However, since the client only requested two 16-bit registers (32 bits), it gets an unexpected response size.

**To Reproduce**
1. Run a Zephyr modbus server, and enable `CONFIG_MODBUS_FP_EXTENSIONS`.
2. From a connected modbus client (in our case, an Automation Direct CM5-T7W), request a `float32` value from an address with value >= 5000.
3. See that the server tries to return 64 bits (4 registers) instead of the requested 2 registers (32 bits).

**Expected behavior**
When a 32-bit float is requested by a modbus client (two 16-bit registers), the modbus server should return 32 bits of data, not 64.

**Impact**
Showstopper. We cannot use the Zephyr modbus server with our Automation Direct CM5-T7W HMI, as we require the use of 32-bit floats.

**Environment (please complete the following information):**
OS: Windows 11
Toolchain: Zephyr 3.5.0

### PR DESCRIPTION
**Pull request by jfischer-no**
The Modbus protocol object types are either single-bit or 16-bit word. Other types are not defined in the specification. Types such as float are typically mapped to two 16-bit registers. Current implementaiton does not maps correctly to the 16-bit word addresses. On the client side, the implementation must take into account that the number of requested registers (Quantity of Registers) is double that of a "float" register.  The server side should not treat "Quantity of Registers" and "Byte count" differently for addresses reserved for floating values, only in the user callback the two 16-bit registers are mapped to a float value but still aligned to 16-bit register addresses.

Fixes: #68788

### CODE REVIEW

**Comment by maksjapan** [comment]
Hi, I've tested this fix on the modbus server side code, and it is working as desired. 
Not sure what I can help to move this forward, but would like to see this merged in the main branch soon!

File: subsys/modbus/modbus_server.c [hunk 1]
```diff
@@ -322,6 +322,15 @@ static bool mbs_fc03_hreg_read(struct modbus_context *ctx)
 	reg_addr = sys_get_be16(&ctx->rx_adu.data[0]);
 	reg_qty = sys_get_be16(&ctx->rx_adu.data[2]);
 
+	if (reg_qty == 0 || reg_qty > regs_limit) {
+		LOG_ERR("Number of registers limit exceeded");
```
Comment (fabiobaltieri) [inline subsys/modbus/modbus_server.c:326]: can you log `reg_qty` and `regs_limit` in the error?

File: subsys/modbus/modbus_server.c [hunk 2]
```diff
@@ -432,6 +433,15 @@ static bool mbs_fc04_inreg_read(struct modbus_context *ctx)
...
```
Comment (fabiobaltieri) [inline subsys/modbus/modbus_server.c:437]: same

**Review by bjarki-andreasen — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
