### PR TITLE
Bluetooth: Mesh: Encrypt friend packets on send

### LINKED ISSUE #18488: Bluetooth: Mesh: Friend queue message seqnum order
**Describe the bug**
The friend queue messages are encrypted when they're put into the queue.  This causes replay protection issues on the LPN if we get a friend control message we have to respond to: 

Friend subscription list add/remove messages should be responded to with a subscription list confirm message immediately, essentially skipping the queue. This functionality is correctly implemented in [`enqueue_sub_cfm`](https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/bluetooth/mesh/friend.c:434), but the enqueued messages from the friend node itself allocate their sequence numbers as they're added to the queue (in `bt_mesh_friend_enqueue_tx`). Later, when the LPN does a poll for enqueued messages, it'll reject the enqueued messages in the replay protection, as it already received a higher seqnum in the subscription list confirm message, that skipped the queue.

**To Reproduce**
1. Establish a friendship between an LPN and a friend node.
2. Enqueue one or more app level messages from the friend to the LPN.
3. Add a group subscription to the LPN, triggering a Friend subscription list add message
4. After the confirm is received from the friend, do an LPN poll. All the messages from the friend to the LPN should be rejected by the replay protection.

**Impact**
Unexpected communication breakdown between the Friend and the LPN. 

**Required changes**
To get around this, I believe the only viable solution is to store friend queue messages unencrypted, and only allocate sequence numbers and encrypt once we know the message will be sent without anything cutting the line (ie when we get a poll and that message is first in the queue).

### PR DESCRIPTION
**Pull request by trond-snekvik**
Stores friend queue packets unencrypted, removing any out-of-order
issues caused by seqnum allocation. Also moves as much of the metadata
storage as possible into the packet, allowing us to free up some bytes
of net_buf user data for friend packets.

Fixes #18488

Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/mesh/friend.c [hunk 1]
```diff
@@ -340,33 +313,62 @@ static struct net_buf *create_friend_pdu(struct bt_mesh_friend *frnd,
...
+		if (friend_cred_get(sub, frnd->lpn, &nid, &enc, &priv)) {
+			BT_ERR("friend_cred_get failed");
+			return -ENOENT;
+		}
 	}
 
-	if (bt_mesh_net_obfuscate(buf->data, info->iv_index, priv)) {
-		BT_ERR("Re-obfuscating failed");
-		goto failed;
+	u16_t src = ((buf->data[5] << 16) | (buf->data[6]));
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/friend.c]: `src = sys_get_be16(&buf->data[5]);`

Also, please move the variable declarations to the beginning of the scope (the function in this case). I don't think this is enforced by any Zephyr global coding style, but that's what we've followed in the stack. One benefit is that it's easier to assess the stack footprint of the function that way.

File: subsys/bluetooth/mesh/friend.c [hunk 2]
```diff
@@ -340,33 +313,62 @@ static struct net_buf *create_friend_pdu(struct bt_mesh_friend *frnd,
...
-		BT_ERR("Re-encrypting failed");
-		goto failed;
+	return buf;
+}
+
+static int encrypt_friend_pdu(struct bt_mesh_friend *frnd, struct net_buf *buf, bool master_cred)
+{
+	const u8_t *enc, *priv;
+	u8_t nid;
+
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/friend.c]: No need for this empty line, i.e. you can group all variable declarations together. Not a very strongly enforced style rule, but what I find to be most readable, is the "inverted x-mas tree" style, i.e. longest declarations first, meaning the subnet would go on top.

File: subsys/bluetooth/mesh/friend.c [hunk 3]
```diff
@@ -872,23 +879,39 @@ int bt_mesh_friend_req(struct bt_mesh_net_rx *rx, struct net_buf_simple *buf)
...
 }
 
+static bool is_seg(struct bt_mesh_friend_seg *seg, u16_t src, u16_t seq_zero)
+{
+	struct net_buf *buf = (void *)sys_slist_peek_head(&seg->queue);
+
+	if (!buf) {
+		return false;
+	}
+	struct net_buf_simple_state state;
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/friend.c]: Variable declaration to the beginning of the scope (the function in this case). Also, always empty line after `{` unless the next line is also a `{`.

File: subsys/bluetooth/mesh/friend.c [hunk 4]
```diff
@@ -340,33 +313,62 @@ static struct net_buf *create_friend_pdu(struct bt_mesh_friend *frnd,
...
+			BT_ERR("friend_cred_get failed");
+			return -ENOENT;
+		}
 	}
 
-	if (bt_mesh_net_obfuscate(buf->data, info->iv_index, priv)) {
-		BT_ERR("Re-obfuscating failed");
-		goto failed;
+	u16_t src = ((buf->data[5] << 16) | (buf->data[6]));
+	u32_t iv_index;
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/friend.c]: Variable declaration to the beginning of the scope.

File: subsys/bluetooth/mesh/friend.c [hunk 5]
```diff
@@ -872,23 +879,39 @@ int bt_mesh_friend_req(struct bt_mesh_net_rx *rx, struct net_buf_simple *buf)
...
+{
+	struct net_buf *buf = (void *)sys_slist_peek_head(&seg->queue);
+
+	if (!buf) {
+		return false;
+	}
+	struct net_buf_simple_state state;
+	net_buf_simple_save(&buf->b, &state);
+	net_buf_skip(buf, 5);   /* skip IVI, NID, CTL, TTL, SEQ */
+	u16_t buf_src = net_buf_pull_be16(buf);
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/friend.c]: Variable declaration to the beginning of the scope

File: subsys/bluetooth/mesh/friend.c [hunk 6]
```diff
@@ -872,23 +879,39 @@ int bt_mesh_friend_req(struct bt_mesh_net_rx *rx, struct net_buf_simple *buf)
...
+	net_buf_skip(buf, 3);   /* skip DST, OP/AID */
+	u16_t buf_seq_zero = ((net_buf_pull_be16(buf) >> 2) & TRANS_SEQ_ZERO_MASK);
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/friend.c]: Same here.

File: subsys/bluetooth/mesh/friend.c [hunk 7]
```diff
@@ -1057,6 +1078,42 @@ int bt_mesh_friend_init(void)
...
 
+static bool is_segack(struct net_buf *buf, u64_t *seqauth, u16_t src)
+{
+	if (buf->len != 16) {
+		return false;
+	}
+
+	bool found = false;
+
+	struct net_buf_simple_state state;
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/friend.c]: Both `found` and `state` declarations to the beginning of the function, preferably in the "inverted x-mas tree" style, i.e. `state` first.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Pretty much only minor coding style issues. Generally I don't disagree about your style (it's perfectly readable) but let's try to keep the style consistent across the Bluetooth subsystem. Other than that looks good to me.

**Review by jhedberg — APPROVED** [review]
