### PR TITLE
sys/cbprintf_internal.h: Silence spurious warnings with -save-temps

### LINKED ISSUE #51528: spurious warnings when EXTRA_CFLAGS=-save-temps=obj is passed
When `EXTRA_CFLAGS=-save-temps=obj` (as recommended by https://docs.zephyrproject.org/latest/build/dts/troubleshooting.html) is passed, many spurious warnings start showing up, sometimes followed by many extraneous newlines. These warnings are usually something like:
```
/zephyrproject/zephyr/lib/os/cbprintf_packaged.c: In function 'cbprintf_package_convert':
/zephyrproject/zephyr/lib/os/cbprintf_packaged.c:1003:2969: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
 1003 |                                 LOG_WRN("(unsigned) char * used for %%p argument. "
```

Please also mention any information which could help others to understand
the problem you're facing:
 - This showed up when I updated to v3.2.0. Was not present in v3.1.0.

**To Reproduce**
1. `west build --pristine -b arduino_due zephyr/samples/hello_world -- -DEXTRA_CFLAGS=-save-temps=obj`

**Expected behavior**
No warnings or errors.

**Impact**
Log and compile noise.

**Logs and console output**
```
-- west build: making build dir /home/user/zephyrproject/build pristine
-- west build: generating a build system
-- Application: /home/user/zephyrproject/zephyr/samples/hello_world
-- Found Python3: /usr/bin/python3.10 (found suitable exact version "3.10.8") found components: Interpreter 
-- Cache files will be written to: /home/user/.cache/zephyr
-- Zephyr version: 3.2.0 (/home/user/zephyrproject/zephyr)
-- Found west (found suitable version "0.14.0", minimum required is "0.7.1")
-- Board: arduino_due
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.15.1 (/home/user/opt/zephyr-sdk-0.15.1)
-- Found toolchain: zephyr 0.15.1 (/home/user/opt/zephyr-sdk-0.15.1)
-- Found Dtc: /home/user/opt/zephyr-sdk-0.15.1/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/user/zephyrproject/zephyr/boards/arm/arduino_due/arduino_due.dts
-- Generated zephyr.dts: /home/user/zephyrproject/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: /home/user/zephyrproject/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: /home/user/zephyrproject/build/zephyr/dts.cmake
Parsing /home/user/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/user/zephyrproject/zephyr/boards/arm/arduino_due/arduino_due_defconfig'
Merged configuration '/home/user/zephyrproject/zephyr/samples/hello_world/prj.conf'
Configuration saved to '/home/user/zephyrproject/build/zephyr/.config'
Kconfig header saved to '/home/user/zephyrproject/build/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/user/opt/zephyr-sdk-0.15.1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/zephyrproject/build
-- west build: building application
[1/145] Preparing syscall dependency handling

[2/145] Generating include/generated/version.h
-- Zephyr version: 3.2.0 (/home/user/zephyrproject/zephyr), build: zephyr-v3.2.0
[3/145] Generating misc/generated/syscalls_subdirs.trigger
[4/145] Generating misc/generated/syscalls.json, misc/generated/struct_tags.json
[5/145] Generating include/generated/driver-validation.h
[6/145] Generating include/generated/syscall_dispatch.c, include/generated/syscall_list.h
[7/145] Generating include/generated/kobj-types-enum.h, include/generated/otype-to-str.h, include/generated/otype-to-size.h
[8/145] Building C object zephyr/CMakeFiles/offsets.dir/arch/arm/core/offsets/offsets.c.obj
[9/145] Generating include/generated/offsets.h
[10/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc32_sw.c.obj
[11/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc32c_sw.c.obj
[12/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc7_sw.c.obj
[13/145] Generating linker_zephyr_pre0.cmd
[14/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf.c.obj
[15/145] Building ASM object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/cpu_idle.S.obj
[16/145] Building C object zephyr/CMakeFiles/zephyr.dir/misc/generated/configs.c.obj
[17/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/dec.c.obj
[18/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc16_sw.c.obj
[19/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc8_sw.c.obj
[20/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/multi_heap.c.obj
[21/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/hex.c.obj
[22/145] Building ASM object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/nmi_on_reset.S.obj
[23/145] Generating linker_zephyr_pre1.cmd
[24/145] Building ASM object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/swap_helper.S.obj
[25/145] Building ASM object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/isr_wrapper.S.obj
[26/145] Building C object zephyr/CMakeFiles/zephyr.dir/soc/arm/atmel_sam/common/soc_pmc.c.obj
[27/145] Building ASM object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/fault_s.S.obj
[28/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/thread_entry.c.obj
[29/145] Building C object zephyr/CMakeFiles/zephyr.dir/soc/arm/atmel_sam/common/soc_gpio.c.obj
[30/145] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/tracing/tracing_none.c.obj
[31/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/timeutil.c.obj
[32/145] Building C object zephyr/CMakeFiles/zephyr.dir/soc/arm/atmel_sam/sam3x/soc.c.obj
[33/145] Building C object zephyr/arch/common/CMakeFiles/arch__common.dir/sw_isr_common.c.obj
[34/145] Building C object zephyr/arch/common/CMakeFiles/isr_tables.dir/isr_tables.c.obj
[35/145] Building ASM object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/exc_exit.S.obj
[36/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/notify.c.obj
[37/145] Building ASM object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/reset.S.obj
[38/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/sem.c.obj
[39/145] Building ASM object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/vector_table.S.obj
[40/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/printk.c.obj
[41/145] Linking C static library zephyr/arch/common/libisr_tables.a
[42/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/assert.c.obj
[43/145] Building C object CMakeFiles/app.dir/src/main.c.obj
[44/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/fdtable.c.obj
[45/145] Generating ../../../include/generated/libc/minimal/strerror_table.h
[46/145] Building C object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/irq_manage.c.obj
[47/145] Building C object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/swap.c.obj
[48/145] Linking C static library zephyr/arch/common/libarch__common.a
[49/145] Building C object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/prep_c.c.obj
[50/145] Building C object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/nmi.c.obj
[51/145] Building C object zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj
[52/145] Building C object zephyr/soc/arm/common/cortex_m/CMakeFiles/soc__arm__common__cortex_m.dir/arm_mpu_regions.c.obj
[53/145] Building C object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/thread.c.obj
[54/145] Linking C static library app/libapp.a
[55/145] Building C object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/fpu.c.obj
[56/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/atoi.c.obj
[57/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/bitarray.c.obj
[58/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_complete.c.obj
[59/145] Building C object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/scb.c.obj
[60/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_packaged.c.obj
/home/user/zephyrproject/zephyr/lib/os/cbprintf_packaged.c: In function 'cbprintf_package_convert':
/home/user/zephyrproject/zephyr/lib/os/cbprintf_packaged.c:1003:2969: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
 1003 |                                 LOG_WRN("(unsigned) char * used for %%p argument. "
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^ 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/lib/os/cbprintf_packaged.c:17:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[61/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/heap-validate.c.obj
[62/145] Building C object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/irq_init.c.obj
[63/145] Building C object zephyr/arch/arch/arm/core/aarch32/mpu/CMakeFiles/arch__arm__core__aarch32__mpu.dir/arm_core_mpu.c.obj
[64/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/strtoul.c.obj
[65/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/bsearch.c.obj
[66/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/heap.c.obj
[67/145] Building C object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/thread_abort.c.obj
[68/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/strtol.c.obj
[69/145] Building C object zephyr/drivers/timer/CMakeFiles/drivers__timer.dir/sys_clock_init.c.obj
[70/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/strtoll.c.obj
[71/145] Building C object zephyr/arch/arch/arm/core/aarch32/CMakeFiles/arch__arm__core__aarch32.dir/fatal.c.obj
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/fatal.c: In function 'esf_dump':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/fatal.c:22:3857: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   22 |         LOG_ERR("r0/a1:  0x%08x  r1/a2:  0x%08x  r2/a3:  0x%08x",
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/arch/arm/core/aarch32/fatal.c:17:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/fatal.c:24:3857: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   24 |         LOG_ERR("r3/a4:  0x%08x r12/ip:  0x%08x r14/lr:  0x%08x",
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/fatal.c:26:2033: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   26 |         LOG_ERR(" xpsr:  0x%08x", esf->basic.xpsr);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/fatal.c:53:2033: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   53 |         LOG_ERR("Faulting instruction address (r15/pc): 0x%08x",
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[72/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/string/strerror.c.obj
[73/145] Building C object zephyr/drivers/console/CMakeFiles/drivers__console.dir/uart_console.c.obj
[74/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/onoff.c.obj
[75/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/string/strncasecmp.c.obj
[76/145] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/rb.c.obj
[77/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/string/strstr.c.obj
[78/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/strtoull.c.obj
[79/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/math/sqrtf.c.obj
[80/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/math/sqrt.c.obj
[81/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/abort.c.obj
[82/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/string/strspn.c.obj
[83/145] Linking C static library zephyr/soc/arm/common/cortex_m/libsoc__arm__common__cortex_m.a
[84/145] Building C object zephyr/drivers/pinctrl/CMakeFiles/drivers__pinctrl.dir/common.c.obj
[85/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/qsort.c.obj
[86/145] Building C object zephyr/drivers/serial/CMakeFiles/drivers__serial.dir/uart_sam.c.obj
[87/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdout/fprintf.c.obj
[88/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdout/sprintf.c.obj
[89/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/version.c.obj
[90/145] Linking C static library zephyr/arch/arch/arm/core/aarch32/libarch__arm__core__aarch32.a
[91/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/exit.c.obj
[92/145] Linking C static library zephyr/libzephyr.a
[93/145] Building C object zephyr/drivers/timer/CMakeFiles/drivers__timer.dir/cortex_m_systick.c.obj
[94/145] Linking C static library zephyr/drivers/serial/libdrivers__serial.a
[95/145] Linking C static library zephyr/drivers/console/libdrivers__console.a
[96/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdlib/malloc.c.obj
/home/user/zephyrproject/zephyr/lib/libc/minimal/source/stdlib/malloc.c: In function 'malloc':
/home/user/zephyrproject/zephyr/lib/libc/minimal/source/stdlib/malloc.c:103:1125: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  103 |         LOG_ERR("CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE is 0");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^ 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/lib/libc/minimal/source/stdlib/malloc.c:19:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[97/145] Linking C static library zephyr/drivers/timer/libdrivers__timer.a
[98/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/string/string.c.obj
[99/145] Building C object zephyr/drivers/watchdog/CMakeFiles/drivers__watchdog.dir/wdt_sam.c.obj
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c: In function 'wdt_sam_convert_timeout':
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c:74:2953: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   74 |                 LOG_ERR("Invalid timeout value allowed range:"
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^ 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c:26:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c: In function 'wdt_sam_setup':
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c:115:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  115 |                 LOG_ERR("No valid timeouts installed");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c: In function 'wdt_sam_install_timeout':
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c:150:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  150 |                 LOG_ERR("No more timeouts can be installed");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c:182:1141: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  182 |                         LOG_ERR("Invalid(NULL) ISR callback passed\n");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c:191:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  191 |                 LOG_DBG("Configuring reset CPU only mode\n");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/drivers/watchdog/wdt_sam.c:197:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  197 |                 LOG_ERR("Unsupported watchdog config Flag\n");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[100/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/banner.c.obj
[101/145] Building C object zephyr/drivers/pinctrl/CMakeFiles/drivers__pinctrl.dir/pinctrl_sam.c.obj
[102/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/errno.c.obj
[103/145] Building C object zephyr/arch/arch/arm/core/aarch32/mpu/CMakeFiles/arch__arm__core__aarch32__mpu.dir/arm_mpu.c.obj
In file included from /home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c:47:
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu_v7_internal.h: In function 'region_init':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu_v7_internal.h:50:3857: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   50 |         LOG_DBG("[%d] 0x%08x 0x%08x",
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c:15:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c: In function 'region_allocate_and_init':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c:64:2041: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   64 |                 LOG_ERR("Failed to allocate new MPU region %u\n", index);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c:68:2033: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   68 |         LOG_DBG("Program MPU region at index 0x%x", index);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c: In function 'mpu_configure_region':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c:84:2033: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   84 |         LOG_DBG("Configure MPU region at index 0x%x", index);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c: In function 'mpu_configure_regions':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c:120:2049: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  120 |                         LOG_ERR("Partition %u: sanity check failed.", i);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c: In function 'z_arm_mpu_init':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/mpu/arm_mpu.c:341:2033: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  341 |         LOG_DBG("total region count: %d", get_num_regions());
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[104/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/main_weak.c.obj
[105/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/stdout/stdout_console.c.obj
[106/145] Linking C static library zephyr/drivers/watchdog/libdrivers__watchdog.a
[107/145] Building C object zephyr/lib/libc/minimal/CMakeFiles/lib__libc__minimal.dir/source/time/gmtime.c.obj
[108/145] Linking C static library zephyr/drivers/pinctrl/libdrivers__pinctrl.a
[109/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/idle.c.obj
[110/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/kheap.c.obj
[111/145] Linking C static library zephyr/arch/arch/arm/core/aarch32/mpu/libarch__arm__core__aarch32__mpu.a
[112/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/system_work_q.c.obj
[113/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/init.c.obj
[114/145] Linking C static library zephyr/lib/libc/minimal/liblib__libc__minimal.a
[115/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mem_slab.c.obj
[116/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/device.c.obj
[117/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/condvar.c.obj
[118/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sem.c.obj
[119/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/stack.c.obj
[120/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/fatal.c.obj
/home/user/zephyrproject/zephyr/kernel/fatal.c: In function 'k_sys_fatal_error_handler':
/home/user/zephyrproject/zephyr/kernel/fatal.c:45:1125: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   45 |         LOG_ERR("Halting system");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^ 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_backend.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_ctrl.h:10,
                 from /home/user/zephyrproject/zephyr/kernel/fatal.c:13:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/fatal.c: In function 'z_fatal_error':
/home/user/zephyrproject/zephyr/kernel/fatal.c:109:3857: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  109 |         LOG_ERR(">>> ZEPHYR FATAL ERROR %d: %s on CPU %d", reason,
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/fatal.c:120:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  120 |                 LOG_ERR("Fault during interrupt handling\n");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/fatal.c:124:2945: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  124 |         LOG_ERR("Current thread: %p (%s)", thread,
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[121/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/xip.c.obj
[122/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/msg_q.c.obj
[123/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mempool.c.obj
[124/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mailbox.c.obj
[125/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/thread.c.obj
/home/user/zephyrproject/zephyr/kernel/thread.c: In function 'setup_thread_stack':
/home/user/zephyrproject/zephyr/kernel/thread.c:475: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  475 |         LOG_DBG("stack %p for thread %p: obj_size=%zu buf_start=%p "
      | 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/kernel/thread.c:31:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[126/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/queue.c.obj
[127/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/timer.c.obj
[128/145] Building C object zephyr/arch/arch/arm/core/aarch32/cortex_m/CMakeFiles/arch__arm__core__aarch32__cortex_m.dir/fault.c.obj
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c: In function 'mem_manage_fault':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:232:1125: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  232 |         PR_FAULT_INFO("***** MPU FAULT *****");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^ 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:19:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:235:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  235 |                 PR_FAULT_INFO("  Stacking error (context area might be"
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:239:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  239 |                 PR_FAULT_INFO("  Unstacking error");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:242:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  242 |                 PR_FAULT_INFO("  Data Access Violation");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:255:2049: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  255 |                         PR_EXC("  MMFAR Address: 0x%x", mmfar);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:263:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  263 |                 PR_FAULT_INFO("  Instruction Access Violation");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c: In function 'bus_fault':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:384:1125: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  384 |         PR_FAULT_INFO("***** BUS FAULT *****");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:387:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  387 |                 PR_FAULT_INFO("  Stacking error");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:390:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  390 |                 PR_FAULT_INFO("  Unstacking error");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:393:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  393 |                 PR_FAULT_INFO("  Precise data bus error");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:405:2049: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  405 |                         PR_EXC("  BFAR Address: 0x%x", bfar);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:413:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  413 |                 PR_FAULT_INFO("  Imprecise data bus error");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:416:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  416 |                 PR_FAULT_INFO("  Instruction bus error");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c: In function 'usage_fault':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:540:1125: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  540 |         PR_FAULT_INFO("***** USAGE FAULT *****");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:544:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  544 |                 PR_FAULT_INFO("  Division by zero");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:547:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  547 |                 PR_FAULT_INFO("  Unaligned memory access");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:565:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  565 |                 PR_FAULT_INFO("  No coprocessor instructions");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:568:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  568 |                 PR_FAULT_INFO("  Illegal load of EXC_RETURN into PC");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:571:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  571 |                 PR_FAULT_INFO("  Illegal use of the EPSR");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:574:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  574 |                 PR_FAULT_INFO("  Attempt to execute undefined instruction");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c: In function 'debug_monitor':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:633:1125: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  633 |         PR_FAULT_INFO(
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c: In function 'hard_fault':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:710:1125: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  710 |         PR_FAULT_INFO("***** HARD FAULT *****");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:732:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  732 |                 PR_EXC("  Bus fault on vector table read");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:734:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  734 |                 PR_EXC("  Debug event");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:736:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  736 |                 PR_EXC("  Fault escalation (see below)");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:738:2049: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  738 |                         PR_EXC("ARCH_EXCEPT with reason %x\n", esf->basic.r0);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c: In function 'reserved_exception':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:777:2945: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  777 |         PR_FAULT_INFO("***** %s %d) *****",
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c: In function 'get_esf':
/home/user/zephyrproject/zephyr/arch/arm/core/aarch32/cortex_m/fault.c:982:1133: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  982 |                 PR_EXC("SPSEL in thread mode does not indicate PSP");
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[129/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/timeout.c.obj
[130/145] Linking C static library zephyr/arch/arch/arm/core/aarch32/cortex_m/libarch__arm__core__aarch32__cortex_m.a
[131/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mutex.c.obj
/home/user/zephyrproject/zephyr/kernel/mutex.c: In function 'adjust_owner_prio':
/home/user/zephyrproject/zephyr/kernel/mutex.c:85: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
   85 |                 LOG_DBG("%p (ready (y/n): %c) prio changed to %d (was %d)",
      | 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/kernel/mutex.c:39:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/mutex.c: In function 'z_impl_k_mutex_lock':
/home/user/zephyrproject/zephyr/kernel/mutex.c:116: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  116 |                 LOG_DBG("%p took mutex %p, count: %d, orig prio: %d",
      | 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/mutex.c:140:2033: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  140 |         LOG_DBG("adjusting prio up on mutex %p", mutex);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/mutex.c:148:2945: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  148 |         LOG_DBG("on mutex %p got_mutex value: %d", mutex, got_mutex);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/mutex.c:150:3857: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  150 |         LOG_DBG("%p got mutex %p (y/n): %c", _current, mutex,
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/mutex.c:160:2945: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  160 |         LOG_DBG("%p timeout on mutex %p", _current, mutex);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/mutex.c:175:2041: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  175 |                 LOG_DBG("adjusting prio down on mutex %p", mutex);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/mutex.c: In function 'z_impl_k_mutex_unlock':
/home/user/zephyrproject/zephyr/kernel/mutex.c:231:2945: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  231 |         LOG_DBG("mutex %p lock_count: %d", mutex, mutex->lock_count);
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
/home/user/zephyrproject/zephyr/kernel/mutex.c:251:3857: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  251 |         LOG_DBG("new owner of mutex %p: %p (prio: %d)",
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[132/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/work.c.obj
[133/145] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sched.c.obj
/home/user/zephyrproject/zephyr/kernel/sched.c: In function 'k_sched_unlock':
/home/user/zephyrproject/zephyr/kernel/sched.c:989:2945: warning: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Waddress]
  989 |         LOG_DBG("scheduler unlocked (%p:%d)",
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ^ 
In file included from /home/user/zephyrproject/zephyr/include/zephyr/logging/log_core.h:9,
                 from /home/user/zephyrproject/zephyr/include/zephyr/logging/log.h:11,
                 from /home/user/zephyrproject/zephyr/kernel/sched.c:17:
/home/user/zephyrproject/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
   94 |         uint8_t data[];
      |                 ^~~~
[134/145] Linking C static library zephyr/kernel/libkernel.a
[135/145] Linking C executable zephyr/zephyr_pre0.elf

[136/145] Generating dev_handles.c
[137/145] Building C object zephyr/CMakeFiles/zephyr_pre1.dir/misc/empty_file.c.obj
[138/145] Building C object zephyr/CMakeFiles/zephyr_pre1.dir/dev_handles.c.obj
[139/145] Linking C executable zephyr/zephyr_pre1.elf

[140/145] Generating linker.cmd
[141/145] Generating isr_tables.c, isrList.bin
[142/145] Building C object zephyr/CMakeFiles/zephyr_final.dir/misc/empty_file.c.obj
[143/145] Building C object zephyr/CMakeFiles/zephyr_final.dir/isr_tables.c.obj
[144/145] Building C object zephyr/CMakeFiles/zephyr_final.dir/dev_handles.c.obj
[145/145] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:        9956 B       512 KB      1.90%
            SRAM:        3968 B        96 KB      4.04%
        IDT_LIST:          0 GB         2 KB      0.00%
```

**Environment (please complete the following information):**
 - OS: Arch linux
 - Zephyr SDK 0.15.1
 - tag v3.2.0

### PR DESCRIPTION
**Pull request by yashi**
Because `Z_CBPRINTF_STATIC_PACKAGE_GENERIC()`'s first argument can be a static memory location and we have `-Wall`, which implicitly enables `-Waddress`, we get the following warnings when you enable `EXTRA_CFLAGS=-save-temps=obj`.

    $ west build -b qemu_cortex_m3 samples/hello_world -- -DEXTRA_CFLAGS=-save-temps=obj
       :
       :
    zephyr-project/zephyr/kernel/fatal.c: In function 'k_sys_fatal_error_handler':
    zephyr-project/zephyr/kernel/fatal.c:45:1125: warning: the comparison will
    always evaluate as 'true' for the address of 'data' will never be NULL
    [-Waddress]
       45 |         LOG_ERR("Halting system");
          |
    In file included from zephyr-project/zephyr/include/zephyr/logging/log_backend.h:9,
                     from zephyr-project/zephyr/include/zephyr/logging/log_ctrl.h:10,
                     from zephyr-project/zephyr/kernel/fatal.c:13:
    zephyr-project/zephyr/include/zephyr/logging/log_msg.h:94:17: note: 'data' declared here
       94 |         uint8_t data[];
          |                 ^~~~

The reason why you don't see this warning without the flag is that GCC tracks tokens and suppress the warning if it's from a macro expansion.  You can disable this feature by adding `-ftrack-macro-expansion=0`:

    west build -b qemu_cortex_m3 samples/hello_world -- -DEXTRA_CFLAGS=-ftrack-macro-expansion=0

Because `-save-temps` generates `.i` files, all macros have been expanded and the information has already been lost.  All GCC sees at the compilation stage are the comparisons of static memory locations.

This commit replaces `buf != NULL` with a static inline function `___is_null()` to silence the compiler.  By passing a static memory location to a function, the compiler doesn't see the comparisons of a static memory locations against literal values.  But it's still able to optimize out in the later stage.

There is another way to silence it; By ignoring `-Waddress` with a pragma. But its effect is the macro wide and it's too wide IMHO.  Thus, I've decided to go with the inline function.

To add one more note: The name `___is_null()` is obviously too generic. But let's have it here until someone finds it problematic.

This closes #51528.

Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>

### CODE REVIEW

**Comment by yashi** [comment]
The error on the compliance Checks is related with #54270.

**Comment by mbolivar-nordic** [comment]
@yashi I tested this and it's working for me. Thank you for your fix. Could you please rebase the commit instead of having a merge commit in the pull request?

**Comment by yashi** [comment]
Ah, I've tested the girhub function(GUI button) but obviously it doesn't work the way I want.  Will fix tomorrow.

**Review by mbolivar-nordic — DISMISSED** [review]

File: include/zephyr/sys/cbprintf_internal.h [hunk 1]
```diff
@@ -382,6 +382,11 @@ do { \
 		 _name##_buf32)))
 #endif
 
+static inline bool ___is_null(void *p)
```
Comment (nordic-krch) [inline include/zephyr/sys/cbprintf_internal.h:385]: Can you add a comment explaining why this is needed?

Comment (yashi) [reply include/zephyr/sys/cbprintf_internal.h:388]: done

Comment (dcpleung) [reply include/zephyr/sys/cbprintf_internal.h:388]: I think it would be better to explain it in details instead of linking to a GitHub issue, as all the information would be in the code.

Also, if you are changing this again, could you do `ALWAYS_INLINE` instead of simply `inline`? This will restore old behavior during debugging with no optimizations.

Comment (yashi) [reply include/zephyr/sys/cbprintf_internal.h:388]: Do we really want to put all explanation in the code in this Git era?  You can just `git blame` to see the commit message.  Nobody put comments with its associated commit messages on every line we change.

Comment (dcpleung) [reply include/zephyr/sys/cbprintf_internal.h:388]: It doesn't have to be as detailed as the commit message. But a summary of that would be great. Besides, if this ever gets modified, `git blame` would not point to this commit.

Comment (yashi) [reply include/zephyr/sys/cbprintf_internal.h]: Done.

**Review by dcpleung — DISMISSED** [review]

**Review by mbolivar-nordic — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]
