### PR TITLE
shell: fix history feature

### LINKED ISSUE #10766: shell: Uncomfortable handling of "current editline" vs history
Here's how GNU readline, and a bunch of its workalines work:

1. Suppose you have some lines in the history buffer.
2. Now you start with an empty line with prompt.
3. You can press up arrow and go to previous command in history.
4. Then you can press down, and you'll get back to you empty line to type new things in!

Current Zephyr shell breaks down on step 4. You can't press down and get back to the current edit line. Suppose you types 50 or 80 char command and executed it. Then by accident you pressed up, and now you need to delete thru 50-80 chars to be able to type a new command. That's rather annoying.

Note that readline's behavior is more complex than the above, there's also:

5. You can actually start typing a new command, press up any number of times (find needed command, e.g. copy one of its arg to clipboard), then press down to get back to "current editline", and it will contain the content you already typed in, it won't be lost.

### PR DESCRIPTION
**Pull request by jakub-uC**
When user was typing a new command and next pressed an up arrow shell has displayed previously executed command. Next it was not possible to display currently edited command using a down arrow.

Fixes #10766.

Signed-off-by: Jakub Rzeszutko <jakub.rzeszutko@nordicsemi.no>

### CODE REVIEW

File: subsys/shell/shell.c [hunk 1]
```diff
@@ -786,18 +782,26 @@ static void shell_state_collect(const struct shell *shell)
```
Comment (nordic-krch) [inline subsys/shell/shell.c]: wouldn't it be possible to reduce number of history_exit calls in that case?
it should stay in history only in case of escape, \0 and metakey_handle. Maybe a flag history_exit (initialy true) and cleared in those particular cases and then `if(history_exit) history_mode_exit(shell)`. It will reduce code size with less function calls.

Comment (jarz-nordic) [reply subsys/shell/shell.c]: good point, I will update that

**Review by pfalcon — APPROVED** [review]
Behavior-wise, works as expected, thanks for the quick fix!!

Btw, noticed that history list is circular, i.e. after the last thing in the history, I don't stay on it, like readline does (at least by default), but get back to my edit line. Ok, let me stop to complain :-D.

**Comment by jarz-nordic** [comment]
I need to print this post, no one will believe me I was praised by @pfalcon ;)
Regarding circular list it was intentional and we like it, please don't ask to change it :)

**Review by jukkar — APPROVED** [review]
LGTM
