### PR TITLE
drivers: nrf_qspi_nor: Add support for S2B1 QER modes

### LINKED ISSUE #42333: Cannot write to qspi flash in adafruit feather nrf52840, device tree is wrong
**Describe the bug**
The qspi flash chip on the adafruit feather nrf52840 does not support the write mode supplied in the devicetree file, meaning that no writes are possible. This lead to interesting issues when trying to define a partition and use it for DFU.

Switching to SPI mode proved to be too slow, and caused out of memory issues when attempting a DFU due mcumgr getting data faster than the chip could erase. Working around that issue cause timeout errors because writes could be be completed within the hard coded 10 microsecond timeout.

Ideally one would use quad mode to interact with the chip, but as noted in a previous commit, this was not possible because the flash chip required quad mode to be enabled by setting bit 1 (second bit) in register 2. However, the nordic driver only supported enabling quad mode if the bit was 6 in register 1. While this seems to be the jedec standard (I don't have a copy of the spects to verify), this chip and possibly some others do not fully conform to this.

This leaves things in a state where it is impossible to use unless someone changes to timeout manually.

I have a pull request that I will link in the comments (chicken and egg with description of pr and issue) that addresses this by allowing a user to specify which bit corresponds to the QE bit in the device tree. It defaults to the current behavior, but the pull request also modifies the DT of the adafruit board to make the appropriate change.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 I developed against the board mentioned above on zephyr 2.7 and 3.0 master. The pull request is the code against 3.0
 - What have you tried to diagnose or workaround this issue?
I sort of covered this in the description, but this involved working through the DFU subsystem to discover the problem, leading me to the flash later, then going through the driver line by line in an editor and a debugger. I was able to make things work in SPI mode, by changing time out parameters in the nordic external module, but it was too slow to be of practical use, no one will wait 10s of minuets for a firmware upgrade. I made the changes to the zephyr source code driver to enable quad mode, and have it up and running on a live board. 

**To Reproduce**
Load a zephyr image with a partition on the flash configured and attempt to write to it.

**Expected behavior**
I expect to be able to write to the flash chip, and use it in conjunction with the DFU firmware, in quad mode

**Impact**
show stopper, as someone cant use the external flash as is.

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 Linux
 - Toolchain (e.g Zephyr SDK, ...)
 Zephyr 2.7, 3.0, sdk version 0.13.1
 - Commit SHA or Version used
Zephyr 2.7 - 8f539523b67036c4d238c3ab5e50a7a28da776b6, Zephyr 3.0 I'm not sure the exact hash, was head 2 days ago, but some merges have happened since then.

**Additional context**
A thanks to people on discord who helped point me at documentation et al on background so I could work through this issue.

### PR DESCRIPTION
**Pull request by zackcornelius**
Add support for S2B1v4 quad-enable-requirements. Tested with Winbond
W25Q128JV series and pp4o and read4io commands.

Fixes #42333.

Signed-off-by: Zack Cornelius <zcornelius@securityesys.com>

### CODE REVIEW

File: drivers/flash/nrf_qspi_nor.c [hunk 1]
```diff
@@ -397,6 +398,23 @@ static int qspi_rdsr(const struct device *dev)
 	return (ret < 0) ? ret : sr;
 }
 
+/* RDSR2 wrapper.  Negative value is error. */
+static int qspi_rdsr2(const struct device *dev)
+{
+	uint8_t sr = -1;
```
Comment (nvlsianpu) [inline drivers/flash/nrf_qspi_nor.c:404]: assignment of negative value to unsigned type.

File: drivers/flash/nrf_qspi_nor.c [hunk 2]
```diff
@@ -557,6 +576,49 @@ static int qspi_nrfx_configure(const struct device *dev)
...
+
+		uint8_t sr = (uint8_t)ret;
+		const uint8_t qe_mask = BIT(1); /* only S2B1 */
+		bool qe_state = ((sr & qe_mask) != 0U);
+
+		LOG_DBG("RDSR %02x QE %d need %d: %s", sr, qe_state, qe_value,
+			(qe_state != qe_value) ? "updating" : "no-change");
+
+		ret = 0;
+		if (qe_state != qe_value) {
```
Comment (nvlsianpu) [inline drivers/flash/nrf_qspi_nor.c:600]: Code for support S2B1V6 is very similar to SB1V4. It Looks like almost copy-pasted.
Can this be rewritten so common code will be used for both?

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
There was similar PR before #36567(even code is similar) https://github.com/zephyrproject-rtos/zephyr/pull/36567

File: drivers/flash/nrf_qspi_nor.c (hunk 2 above)
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c:600]: As far as I can tell, S2B1V4 and S2B1V6 are really the same method as far as we're concerned. I'll update this to work for both. I'll also update to address some of the comments on #36567

**Comment by carlescufi** [comment]
@nvlsianpu please take a look again

**Comment by carlescufi** [comment]
@natelust can you please verify if this indeed fixes #42333

**Comment by carlescufi** [comment]
@zackcornelius can you please squash the 3 commits together and make it  comply with our commit formatting rules

**Comment by natelust** [comment]
@carlescufi I am going to check this out, and build this for my board now, but looking at the code something seems wrong. At least for the GD25 chip on the Adafruit board. According to that manual, to write to the registers the chip uses 01H opcode, and expects 2 bytes following, one for status register 1 and register2. While it is possible it supports the alternative opcode (31H), this is not documented.

**Comment by natelust** [comment]
page 13 [here](https://cdn-shop.adafruit.com/product-files/4763/4763_GD25Q16CTIGR.pdf)

**Comment by natelust** [comment]
However, it does seem that this branch *DOES* work, so it seems like the chip does support the opcode, I am able to use the flash chip with; writetoc=pp40, readoc=read4o, quad-enable-requirements="S2B1v6".

It seems like I could have saved myself A LOT of time had I tried this all out just a bit later instead of last week. I would not have needed to pour over manuals about nor chips and qspi, but I guess learning about new stuff is always worth while. Thanks for having this patch ready, I will go close my pr.

**Comment by natelust** [comment]
If it is possible, can you update the Adafruit nrf52840 dev tree to use these values on this pull request?

**Comment by zackcornelius** [comment]
@natelust I updated the adafruit feather nrf52840 dts to use quad mode by default - Can you test with this updated branch and make sure I didn't break anything on that?

**Comment by natelust** [comment]
Unfortunately, I will not be back to my computer for a while, I will test when I am though, but I guess don't let me hold you up. Looking over this, the only difference from what my DT was is that I used S2B1v6, but looking at your code path, it should not make any difference. Thanks for adding that.

**Comment by natelust** [comment]
There does seem to be a weird white space issue going on though, but I cant be sure that is not just github rendering.

**Comment by legoabram** [comment]
I feel like I should chime in here. I'll just summarize the different modes according to [JEDEC](https://www.jedec.org/standards-documents/docs/jesd216b)(Page 40, or search `QER`):
```
S2B1v1		Read SR1 + SR2 via 05h, Write SR1 + SR2 via 01h (Writing Only SR1 Clears SR2)
S1B6		Read SR1 via 05h, Write SR1 via 01h
S2B7		Read SR2 via 3Fh, Write SR2 via 3Eh (Haven't seen this one yet)
S2B1v4		Same as S2B1v1, but doesn't clear SR2 when only SR1 is written
S2B1v5		Read SR2 via 35h, Write SR1 + SR2 via 01h
S2B1v6		Read SR2 via 35h, Write SR2 via 31h
```

Given what I've read, I do not think S2B1V4 is the correct mode for a W25Q128JV since the Read SR1 Command (01h) only returns SR1. Though, as far as I can tell, what you've implemented is S2B1v6 which is what this chip wants anyway.

@natelust I'm a little bit confused about how the branch managed to work for your chip which appears to use S2B1v5. Also, this doesn't appear to be consistent in the chip family since the gd25q16e is S2B1v5, but the gd25q128e I'm using is S2B1v6.

P.S. Sorry for going AWOL on my branch/pull-request. I didn't notice it had gotten comments on it after it had gone stale.

**Comment by zackcornelius** [comment]
@legoabram - I claimed my version is S2B1v4 because that's what the W25Q128JV reports in the BFP Table, so I had assumed that what the manual stated was indeed v4 (I now see that's definitely not consistent with JEDEC's spec)

Reading the datasheet for the gd25q16e, It actually looks like that might be S2B1v1? It claims that setting CS high after only writing 8 bits for opcode 0x01h will clear QE

I've requested a JEDEC account, and will attempt to update PR to attempt to support at least v5 / v1 (used by the gd25q16e) and v6 used by my W25Q128JV.

**Review by nvlsianpu — COMMENTED** [review]
@zackcornelius commanding unification looks fine on the firs glance.
I will review this in more details and comment.

**Comment by natelust** [comment]
@legoabram Yeah, I was surprised too either:
A) The chip is actually pretty forgiving or something just happened to work
B) I opened a fresh chip I had lying around to test this, its possible the QE bit happened to be set on this one. The last freshly opened one did not have it set, so I assumed new ones would not, but I guess that was a bad thing to assume when reporting that something was working, so I apologize for that.

@zackcornelius  I am going to try this latest patch, force the qe bit off, make sure working with the chip fails, and then test the chip again to see if it works. I'll let you know how it goes.

**Comment by natelust** [comment]
@legoabram @zackcornelius My guess is this board for whatever reason had the quad enable bit set before I even opened it. I forced the bit to 0, verified reads and writes were not working, and tested this patch completely fresh. This patch **does not** make the adafruit board work.

However, I think it is possible to incorporate some of the changes from my branch into this branch (using the existing JDEEC flag) to enable support for the AF board. I will have a go at this, but if you get to it before I do feel free to grab whatever from my closed PR you want.

**Comment by natelust** [comment]
I modified the code to work with my board and put a pull request to @zackcornelius branch, he can pull that in and it should show up here. Otherwise I can make a new PR, but this seemed easier to keep track of things.

**Comment by zackcornelius** [comment]
I've updated this code with (hopeful) support for QER modes 1, 4, 5, 6, based on some updates from @natelust 

@legoabram Can you review and see if what I ended up with seems to match the spec. I couldn't find a good reference for QER modes 1 and 4 as to how to read SR2, so I'm hoping this is right.

@natelust Can you test this updated code with your adafruit board? I'm not sure if v1 or v5 is correct for your board (I think it's 1, given that the datasheet says QER gets cleared on a write to just SR1)

@nvlsianpu I think this is ready for review again

**Review by nvlsianpu — COMMENTED** [review]
Code looks really nice.

Just one nip: adafruit_feather_nrf52840.dts change can be moved to separate commit.

@natelust Can you confirm whether it works for you?

File: drivers/flash/nrf_qspi_nor.c [hunk 3]
```diff
@@ -410,6 +428,69 @@ static int qspi_wait_while_writing(const struct device *dev)
...
+	int ret = 0;
+	uint8_t opcode = SPI_NOR_CMD_WRSR;
+	uint8_t length = 1;
+	uint8_t sr_array[2] = {0};
+
+	if (sr_num == 1) {
+		// Writing sr1 clears sr2. Need to read/modify/write both.
+		sr_array[0] = sr_val;
+		if (INST_0_QER == JESD216_DW15_QER_S2B1v1) {
+			ret = qspi_rdsr2(dev);
```
Comment (natelust) [inline drivers/flash/nrf_qspi_nor.c:442]: This is a bug, there is no `qspi_rdsr2` function declared. I think you mean `qspi_rdsr(dev, 2)` ?

**Comment by natelust** [comment]
@nvlsianpu Yes, this does work for me with my board. I did notice a bug for the code path for S2B1v1, as noted in a comment. It seems to just be a typo.

@zackcornelius Im not 100% positive but I think it is v5, that is what I have been testing, and that is what seems to work. I think v1 reverses byte order, I am going to go read the code 1 more time.

File: drivers/flash/nrf_qspi_nor.c (hunk 3 above)
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c:447]: Yep. Meant to include a qspi_rdsr2 wrapper inline (like rdsr) and it slipped out of the commit. Fixed now

**Comment by zackcornelius** [comment]
@natelust The only differences between the behavior of v1 and v5 are when writing sr1, v1 also writes sr2  (as the sr2 values will be cleared by writing), while v5 writes just sr1. The code path for writing sr2 stays the same between the 2. 

v1 and v5 are functionally identical right now though, since the only time we write to the status registers at all is just when setting QER (so there'd never be another write to sr1 anyway)

**Comment by zackcornelius** [comment]
@nvlsianpu I'll move the board config change to a different PR

**Comment by zackcornelius** [comment]
#42497 to enable QSPI quad-mode on the feather nrf52840

**Comment by natelust** [comment]
@zackcornelius Oh yes, I see. I was really only paying attention to things in context of enabling QE, but I see what you are saying (and what the code is doing) now.

**Comment by legoabram** [comment]
@zackcornelius My one hesitation is that the linux driver I linked makes reference to v1 and v4 not supporting the 35h command. (Which could make sense according to the wording of the QER bit documentation) But given that your chip explicitly declares itself as v4 in the BFP, but still supports the 35h command, I'm honestly not certain why that would be the case. To be certain, we'd almost have to cross-reference a lot of different chips with their commands, quirks, and the QER code they report... Which sounds like oodles of fun.

The big issue I see is that these docs typically don't include their BFP values, which makes it difficult to verify without buying the actual chips. Additionally, the lack of clear documentation of which mode a flash supports in the datasheet means that we will need to provide good documentation for what each mode does so that a user can reference their datasheet and determine which mode should work for their chip. Though, this should probably be done in a different pull request.

Otherwise, everything appears correct given what we know.

@natelust Seriously good catch on the QE bit already being set. That would have been rather confusing!

**Comment by zackcornelius** [comment]
@legoabram 

Could we make a note somewhere that v1 and v4 may need additional work if they don't work out of the box, as we've only been able to test v5/v6?

File: drivers/flash/nrf_qspi_nor.c [hunk 4]
```diff
@@ -506,60 +592,58 @@ static int qspi_nrfx_configure(const struct device *dev)
...
-		 *
-		 * Note build assert above ensures QER is S1B6.  Other
-		 * options require more logic.
-		 */
+		nrf_qspi_prot_conf_t const *prot_if =
+			&dev_config->nrfx_cfg.prot_if;
+		bool qe_value = (prot_if->writeoc == NRF_QSPI_WRITEOC_PP4IO) ||
+			(prot_if->writeoc == NRF_QSPI_WRITEOC_PP4O)  ||
+			(prot_if->readoc == NRF_QSPI_READOC_READ4IO) ||
+			(prot_if->readoc == NRF_QSPI_READOC_READ4O);
```
Comment (anangl) [inline drivers/flash/nrf_qspi_nor.c:608]: I think it would be better to keep the indentation here as it was, i.e.:
```
		bool qe_value = (prot_if->writeoc == NRF_QSPI_WRITEOC_PP4IO) ||
				(prot_if->writeoc == NRF_QSPI_WRITEOC_PP4O)  ||
				(prot_if->readoc == NRF_QSPI_READOC_READ4IO) ||
				(prot_if->readoc == NRF_QSPI_READOC_READ4O);
```

File: drivers/flash/nrf_qspi_nor.c [hunk 5]
```diff
@@ -410,6 +433,69 @@ static int qspi_wait_while_writing(const struct device *dev)
...
+		if (INST_0_QER == JESD216_DW15_QER_S2B1v1) {
+			ret = qspi_rdsr2(dev);
+			if (ret < 0) {
+				LOG_ERR("RDSR for WRSR failed: %d", ret);
+				return ret;
+			}
+			sr_array[1] = ret;
+			length = 2;
+		}
+	} else if (INST_0_QER == JESD216_DW15_QER_S2B1v1
```
Comment (anangl) [inline drivers/flash/nrf_qspi_nor.c:455]: This code assumes that `sr_num` is 2 at this point. There is no check for invalid values as in `qspi_rdsrX`. It would be nice to keep consistency in this regard.

Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c:459]: Agreed. Added a check for sr_num validity.

File: drivers/flash/nrf_qspi_nor.c (hunk 4 above)
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c]: Fixed.

File: drivers/flash/nrf_qspi_nor.c [hunk 6]
```diff
@@ -410,6 +433,69 @@ static int qspi_wait_while_writing(const struct device *dev)
...
+			|| INST_0_QER == JESD216_DW15_QER_S2B1v4
+			|| INST_0_QER == JESD216_DW15_QER_S2B1v5) {
+		// Writing sr2 requires writing sr1 as well
+		// Uses standard WRSR opcode
```
[the remark this answers is not in the document]
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c]: Fixed

File: drivers/flash/nrf_qspi_nor.c [hunk 7]
```diff
@@ -506,60 +592,58 @@ static int qspi_nrfx_configure(const struct device *dev)
...
-		bool qe_value = (prot_if->writeoc == NRF_QSPI_WRITEOC_PP4IO) ||
-				(prot_if->writeoc == NRF_QSPI_WRITEOC_PP4O)  ||
-				(prot_if->readoc == NRF_QSPI_READOC_READ4IO) ||
-				(prot_if->readoc == NRF_QSPI_READOC_READ4O);
-		const uint8_t qe_mask = BIT(6); /* only S1B6 */
 		bool qe_state = ((sr & qe_mask) != 0U);
 
 		LOG_DBG("RDSR %02x QE %d need %d: %s", sr, qe_state, qe_value,
-			(qe_state != qe_value) ? "updating" : "no-change");
+				(qe_state != qe_value) ? "updating" : "no-change");
```
[the remark this answers is not in the document]
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c]: Not sure what happened to change the indention on these. Fixed.

File: drivers/flash/nrf_qspi_nor.c [hunk 8]
```diff
@@ -410,6 +433,69 @@ static int qspi_wait_while_writing(const struct device *dev)
...
+{
+	int ret = 0;
+	uint8_t opcode = SPI_NOR_CMD_WRSR;
+	uint8_t length = 1;
+	uint8_t sr_array[2] = {0};
+
+	if (sr_num == 1) {
+		// Writing sr1 clears sr2. Need to read/modify/write both.
+		sr_array[0] = sr_val;
+		if (INST_0_QER == JESD216_DW15_QER_S2B1v1) {
```
[the remark this answers is not in the document]
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c]: Good catch.

**Comment by zackcornelius** [comment]
Compliance checks are flagging several comparisons between INST_0_QER and JESD216_DW15_QER_S2B1v6 (and similar) for needing the constant on the right side. In this case, both of these are constants, so I don't know if there's a resolution for those flags?

**Comment by anangl** [comment]
> Compliance checks are flagging several comparisons between INST_0_QER and JESD216_DW15_QER_S2B1v6 (and similar) for needing the constant on the right side. In this case, both of these are constants, so I don't know if there's a resolution for those flags?

Those warnings are false positives in this case and they will need to be ignored. There is actually nothing you can do in your code to get rid of them. But you can correct your commit message to address this error message:
```
6: UC4 Line exceeds max length (79>75): "S2B1v6 mode tested with Winbond W25Q128JV series and pp4o and read4io commands."
```

**Review by anangl — DISMISSED** [review]

**Review by nvlsianpu — DISMISSED** [review]

**Review by de-nordic — DISMISSED** [review]

**Comment by carlescufi** [comment]
@zackcornelius could you please shorten this line in the commit message body?

```
6: UC4 Line exceeds max length (79>75): "S2B1v6 mode tested with Winbond W25Q128JV series and pp4o and read4io commands."
```

**Comment by zackcornelius** [comment]
@anangl @carlescufi - Commit message fixed.

**Comment by natelust** [comment]
Any word on this getting merged? I hope to be able to work against the official repository soon.

**Comment by nvlsianpu** [comment]
> Any word on this getting merged? I hope to be able to work against the official repository soon.

This can be merged after 3.0.0 release will be finished.

**Review by nvlsianpu — DISMISSED** [review]

**Comment by natelust** [comment]
Thanks for the update, that's slightly disappointing, I had hoped since there was a bug in the adafruit board dts, this could be considered a bug fix, but I do understand not wanting to put in too large a change at the last minute.

**Review by anangl — DISMISSED** [review]

File: drivers/flash/nrf_qspi_nor.c [hunk 9]
```diff
@@ -410,6 +433,74 @@ static int qspi_wait_while_writing(const struct device *dev)
...
+	uint8_t length = 1;
+	uint8_t sr_array[2] = {0};
+
+	if (sr_num > 2 || sr_num == 0) {
+		return -EINVAL;
+	}
+
+	if (sr_num == 1) {
+		sr_array[0] = sr_val;
+		if (INST_0_QER == JESD216_DW15_QER_S2B1v1) {
```
Comment (carlescufi) [inline drivers/flash/nrf_qspi_nor.c:449]: @mbolivar-nordic @tejlmand @gmarull @nordic-krch do we need a macro for this, or is this the right way to go about it?

File: drivers/flash/nrf_qspi_nor.c [hunk 10]
```diff
@@ -381,22 +385,41 @@ static int qspi_send_cmd(const struct device *dev, const struct qspi_cmd *cmd,
 }
 
 /* RDSR wrapper.  Negative value is error. */
-static int qspi_rdsr(const struct device *dev)
+static int qspi_rdsrX(const struct device *dev, uint8_t sr_num)
```
Comment (gmarull) [inline drivers/flash/nrf_qspi_nor.c:388]: this doesn't follow guidelines: `only_lowercase_please`

File: drivers/flash/nrf_qspi_nor.c [hunk 11]
```diff
@@ -381,22 +385,41 @@ static int qspi_send_cmd(const struct device *dev, const struct qspi_cmd *cmd,
...
+/* RDSR wrapper.  Negative value is error. */
+static inline int qspi_rdsr(const struct device *dev)
+{
+	return qspi_rdsrX(dev, 1);
+}
+
+static inline int qspi_rdsr2(const struct device *dev)
+{
+	return qspi_rdsrX(dev, 2);
+}
```
Comment (gmarull) [inline drivers/flash/nrf_qspi_nor.c:421]: why do we need these wrappers? Can't we just have `qspi_rdsr` that takes sr_num?

File: drivers/flash/nrf_qspi_nor.c [hunk 12]
```diff
@@ -410,6 +433,74 @@ static int qspi_wait_while_writing(const struct device *dev)
...
+			LOG_ERR("RDSR for WRSR failed: %d", ret);
+			return ret;
+		}
+		sr_array[0] = ret;
+		length = 2;
+	} else if (INST_0_QER == JESD216_DW15_QER_S2B1v6) {
+		/* Writing sr2 uses a dedicated WRSR2 command */
+		sr_array[0] = sr_val;
+		opcode = SPI_NOR_CMD_WRSR2;
+	} else {
```
Comment (gmarull) [inline drivers/flash/nrf_qspi_nor.c:477]: all these "if/else" are based on constant comparison (because driver is not multi-instance and definitions are used directly -- ugly). So I think: just use `#ifdef` to select the right path to compile, or, use a macro to check for equality (like e.g. IS_ENABLED is used for constant checks).

**Review by gmarull — DISMISSED** [review]

File: drivers/flash/nrf_qspi_nor.c (hunk 12 above)
Comment (de-nordic) [reply drivers/flash/nrf_qspi_nor.c:477]: The first one to that, line 447 is against `sr_num` which is function parameter.

**Comment by carlescufi** [comment]
@zackcornelius could you please address the latest review comments and rebase the PR so we can merge it?

File: drivers/flash/nrf_qspi_nor.c (hunk 12 above)
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c]: I think I got something that's not uglier than it was, but moves these to compile times checks. @gmarull @de-nordic can you review?

File: drivers/flash/nrf_qspi_nor.c (hunk 11 above)
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c]: Agreed

File: drivers/flash/nrf_qspi_nor.c (hunk 10 above)
Comment (zackcornelius) [reply drivers/flash/nrf_qspi_nor.c]: Fixed. Also fixed qspi_wrsrX -> qspi_wrsr

File: drivers/flash/nrf_qspi_nor.c (hunk 9 above)
Comment (mbolivar-nordic) [reply drivers/flash/nrf_qspi_nor.c]: > @mbolivar-nordic @tejlmand @gmarull @nordic-krch do we need a macro for this, or is this the right way to go about it?

This seems okay for an explicitly single-instance driver.

File: drivers/flash/nrf_qspi_nor.c [hunk 13]
```diff
@@ -133,13 +133,28 @@ BUILD_ASSERT(DT_INST_PROP(0, cpol) == DT_INST_PROP(0, cpha),
...
 
-#define INST_0_QER _CONCAT(JESD216_DW15_QER_, \
+#define INST_0_QER _CONCAT(JESD216_DW15_QER_VAL_, \
 			   DT_STRING_TOKEN(DT_DRV_INST(0), \
 					   quad_enable_requirements))
 
-BUILD_ASSERT(((INST_0_QER == JESD216_DW15_QER_NONE)
-	      || (INST_0_QER == JESD216_DW15_QER_S1B6)),
-	     "Driver only supports NONE or S1B6 for quad-enable-requirements");
+#define SR1_WRITE_CLEARS_SR2 (INST_0_QER == JESD216_DW15_QER_VAL_S2B1v1)
```
Comment (de-nordic) [inline drivers/flash/nrf_qspi_nor.c:140]: Sorry but this will not pass this check: https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/checkpatch.pl#L4980 because this is still covered by second group in regex.
You would have to do extra thing like:
```
#define IS_EQUAL(x, y) ((x) == (y))
```

**Review by nvlsianpu — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
