### PR TITLE
drivers: rtc: minor fixes

### LINKED ISSUE #74540: RTC device driver bugs for PFC8563 and RV3028
**Describe the bug(s)**
The following issues where discovered by @jakubtopic
* The PCF8563 device driver doesn't validate the provided alarm time
* The PCF8563 device driver doesn't validate that the int GPIO exists where necessary
* The  RV3028 device driver is using an incorrect time mask

**To Reproduce**
N/A

**Expected behavior**
* The PCF8563 device driver should validate the provided alarm time
* The PCF8563 device driver should validate that the int GPIO exists where necessary
* The  RV3028 device driver should use the correct time mask

**Impact**
The bugs can lead to undefined behavior, including a NULL de reference.

### PR DESCRIPTION
**Pull request by jakubtopic**
Minor fixes in `pcf8563` and `rv3028`. See commit messages for details.

fixes: #74540

### CODE REVIEW

File: drivers/rtc/rtc_pcf8563.c [hunk 1]
```diff
@@ -219,6 +230,11 @@ static int pcf8563_alarm_set_time(const struct device *dev, uint16_t id, uint16_
 		return -EINVAL;
 	}
 
+	if (!rtc_utils_validate_rtc_time(timeptr, PCF8563_RTC_ALARM_TIME_MASK)) {
```
Comment (bjarki-trackunit) [inline drivers/rtc/rtc_pcf8563.c:233]: Only the fields set by the `mask` arg need to be validated :)
```
if (!rtc_utils_validate_rtc_time(timeptr, mask)) {
```

**Review by bjarki-andreasen — CHANGES_REQUESTED** [review]
Looks good :)

File: drivers/rtc/rtc_pcf8563.c (hunk 1 above)
Comment (jakubtopic) [reply drivers/rtc/rtc_pcf8563.c:233]: oops, my bad

**Review by bjarki-andreasen — APPROVED** [review]

**Review by cyliangtw — APPROVED** [review]
