### PR TITLE
drivers: ethernet: Fix nxp ethernet due to issue in ksz8081

### LINKED ISSUE #79965: net: mimxrt1170_evk_cm7: 100M: phy does not work well tx/rx timeout
**Describe the bug**

mimxrt1170_evk_cm7 100M enet does not work. tx/rx timeout

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - mimxrt1170_evk_cm7
 - What have you tried to diagnose or workaround this issue?
 - git bisect
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 
```
e9047431526e9a738a60f669a1a075b4656f8945 is the first bad commit
commit e9047431526e9a738a60f669a1a075b4656f8945
Author: Declan Snyder <declan.snyder@nxp.com>
Date:   Fri Oct 4 16:46:24 2024 -0500

    ethernet: phy_mc_ksz8081: Don't reset in cfg link

    No need to reset in cfg link, this was blocking system workqueue during
    phy callbacks that call cfg link, since this happens from monitor work
    handler which is in the system workqueue.

    Signed-off-by: Declan Snyder <declan.snyder@nxp.com>

 drivers/ethernet/phy/phy_microchip_ksz8081.c | 6 ------
 1 file changed, 6 deletions(-)

```

**To Reproduce**

```
west update
west build -b mimxrt1170_evk/mimxrt1176/cm7 samples/net/dhcpv4_client/ -p always
west flash --runner=linkserver --probe="JTAQCQAR"
```
console log
```
*** Booting Zephyr OS build v3.7.0-4110-ge9047431526e ***
[00:00:02.912,000] <inf> net_dhcpv4_client_sample: Run dhcpv4 client
[00:00:02.913,000] <inf> net_dhcpv4_client_sample: Start on ethernet: index=1
uart:~$ net iface

Interface eth0 (0x80000d60) (Ethernet) [1]
===================================
Link addr : 02:04:9F:8D:05:5C
MTU       : 1500
Flags     : AUTO_START,IPv4
Device    : ethernet (0x3001f650)
Ethernet capabilities supported:
        TX checksum offload
        RX checksum offload
        10 Mbits
        100 Mbits
        MAC address filtering
Ethernet PHY device: phy@0 (0x3001f63c)
Ethernet link speed: 100 Mbits full-duplex
IPv4 unicast addresses (max 1):
        <none>
IPv4 multicast addresses (max 2):
        224.0.0.1
IPv4 gateway : 0.0.0.0
DHCPv4 lease time : 0
DHCPv4 renew time : 0
DHCPv4 server     : 0.0.0.0
DHCPv4 requested  : 0.0.0.0
DHCPv4 state      : selecting
DHCPv4 attempts   : 1
uart:~$ net iface

Interface eth0 (0x80000d60) (Ethernet) [1]
===================================
Link addr : 02:04:9F:8D:05:5C
MTU       : 1500
Flags     : AUTO_START,IPv4
Device    : ethernet (0x3001f650)
Ethernet capabilities supported:
        TX checksum offload
        RX checksum offload
        10 Mbits
        100 Mbits
        MAC address filtering
Ethernet PHY device: phy@0 (0x3001f63c)
Ethernet link speed: 100 Mbits full-duplex
IPv4 unicast addresses (max 1):
        <none>
IPv4 multicast addresses (max 2):
        224.0.0.1
IPv4 gateway : 0.0.0.0
DHCPv4 lease time : 0
DHCPv4 renew time : 0
DHCPv4 server     : 0.0.0.0
DHCPv4 requested  : 0.0.0.0
DHCPv4 state      : selecting
DHCPv4 attempts   : 5

```

**Expected behavior**

```
[00:00:03.411,000] <inf> phy_mc_ksz8081: PHY 0 is up
[00:00:03.411,000] <inf> phy_mc_ksz8081: PHY (0) Link speed 100 Mb, full duplex

*** Booting Zephyr OS build v3.7.0-4109-gf90b1caae4f9 ***
[00:00:03.412,000] <inf> net_dhcpv4_client_sample: Run dhcpv4 client
[00:00:03.413,000] <inf> net_dhcpv4_client_sample: Start on ethernet: index=1
[00:00:11.423,000] <inf> net_dhcpv4: Received: 192.168.1.230
[00:00:11.423,000] <inf> net_dhcpv4_client_sample:    Address[1]: 192.168.1.230
[00:00:11.423,000] <inf> net_dhcpv4_client_sample:     Subnet[1]: 255.255.255.0
[00:00:11.423,000] <inf> net_dhcpv4_client_sample:     Router[1]: 192.168.1.1
[00:00:11.423,000] <inf> net_dhcpv4_client_sample: Lease time[1]: 43200 seconds

```

**Impact**

100M function

**Environment (please complete the following information):**

 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...): 0.17.0-rc1
 - Commit SHA or Version used: v3.7.0-4578-g829c03bcdca

**Additional context**

1G port is ok, mimxrt1060_evk is ok as well. this only happens on rt1170_evk 100M port

### PR DESCRIPTION
**Pull request by decsny**
Fixes #79965

Some things related to the reset of this phy are happening strangely and this PR addresses it, fixes NXP boards with this phy

### CODE REVIEW

**Review by rruuaanng — APPROVED** [review]

**Comment by hakehuang** [comment]
test pass with dhcp
```
uart:~$ net iface
Hostname: zephyr


Interface eth0 (0x80001610) (Ethernet) [1]
===================================
Link addr : 02:04:9F:1C:D0:CC
MTU       : 1500
Flags     : AUTO_START,IPv4,IPv6
Device    : ethernet (0x30034554)
Ethernet capabilities supported:
        10 Mbits
        100 Mbits
        MAC address filtering
Ethernet PHY device: phy@0 (0x30034540)
Ethernet link speed: 100 Mbits full-duplex
IPv6 unicast addresses (max 4):
        fe80::4:9fff:fe1c:d0cc autoconf preferred infinite
        fd9a:9616:b8e9:0:4:9fff:fe1c:d0cc autoconf preferred infinite
IPv6 multicast addresses (max 5):
        ff02::1
        ff02::1:ff1c:d0cc
IPv6 prefixes (max 2):
        fd9a:9616:b8e9::/64 infinite
IPv6 hop limit           : 64
IPv6 base reachable time : 30000
IPv6 reachable time      : 41881
IPv6 retransmit timer    : 0
IPv4 unicast addresses (max 1):
        192.168.1.115/255.255.255.0 DHCP preferred
IPv4 multicast addresses (max 2):
        224.0.0.1
IPv4 gateway : 192.168.1.1
DHCPv4 lease time : 43200
DHCPv4 renew time : 21600
DHCPv4 server     : 192.168.1.1
DHCPv4 requested  : 192.168.1.115
DHCPv4 state      : bound
DHCPv4 attempts   : 1
uart:~$ net ping 192.168.1.1
PING 192.168.1.1
28 bytes from 192.168.1.1 to 192.168.1.115: icmp_seq=1 ttl=64 time=0 ms
28 bytes from 192.168.1.1 to 192.168.1.115: icmp_seq=2 ttl=64 time=0 ms

```

**Review by hakehuang — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Comment by decsny** [comment]
need to test frdm_k64

**Comment by hakehuang** [comment]
> need to test frdm_k64

'''
Interface eth0 (0x20000518) (Ethernet) [1]
===================================
Link addr : 02:04:9F:80:25:62
MTU       : 1500
Flags     : AUTO_START,IPv4
Device    : ethernet (0x1b5f8)
Ethernet capabilities supported:
        TX checksum offload
        RX checksum offload
        10 Mbits
        100 Mbits
        MAC address filtering
Ethernet PHY device: phy@0 (0x1b5e4)
Ethernet link speed: 100 Mbits full-duplex
IPv4 unicast addresses (max 1):
        192.168.1.180/255.255.255.0 DHCP preferred
IPv4 multicast addresses (max 2):
        224.0.0.1
IPv4 gateway : 192.168.1.1
DHCPv4 lease time : 43200
DHCPv4 renew time : 21600
DHCPv4 server     : 192.168.1.1
DHCPv4 requested  : 192.168.1.180
DHCPv4 state      : bound
DHCPv4 attempts   : 1
uart:~$ net ping 192.168.1.1
PING 192.168.1.1
28 bytes from 192.168.1.1 to 192.168.1.180: icmp_seq=1 ttl=64 time=0 ms
28 bytes from 192.168.1.1 to 192.168.1.180: icmp_seq=2 ttl=64 time=0 ms

'''

**Review by dleach02 — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]

File: drivers/ethernet/phy/phy_microchip_ksz8081.c [hunk 1]
```diff
@@ -289,20 +293,27 @@ static int phy_mc_ksz8081_reset(const struct device *dev)
 		goto done;
 	}
 
-	/* Wait for 500 ms as specified by datasheet */
-	k_busy_wait(USEC_PER_MSEC * 500);
+	/* Wait for at least 500 us as specified by datasheet */
+	k_busy_wait(1000);
```
Comment (kartben) [inline drivers/ethernet/phy/phy_microchip_ksz8081.c:297]: wrong comment or wrong delay in code

File: drivers/ethernet/phy/phy_microchip_ksz8081.c [hunk 2]
```diff
@@ -289,20 +293,27 @@ static int phy_mc_ksz8081_reset(const struct device *dev)
...
 
 	/* Reset over */
 	ret = gpio_pin_set_dt(&config->reset_gpio, 1);
+
+	/* After deasserting reset, must wait at least 100 us to use programming interface */
+	k_busy_wait(200);
```
Comment (kartben) [inline drivers/ethernet/phy/phy_microchip_ksz8081.c:303]: wrong comment or wrong delay in code :)

**Review by kartben — DISMISSED** [review]

File: drivers/ethernet/phy/phy_microchip_ksz8081.c (hunk 1 above)
Comment (danieldegrasse) [reply drivers/ethernet/phy/phy_microchip_ksz8081.c:297]: I'm not clear how these are wrong- are you saying we should update the comment to something like so:

`/* Datasheet specifies a minimum delay of 500us. Wait 1000us to be safe */`

Comment (kartben) [reply drivers/ethernet/phy/phy_microchip_ksz8081.c:297]: ah -- yeah. Sorry. Both comments confused me for the reason you just described. I think it would be worth clarifying to indeed explain that "just" going with the datasheet recommendation isn't enough, otherwise I feel it can read as a typo. Will remove my block though -- sorry again for the noise!

Comment (danieldegrasse) [reply drivers/ethernet/phy/phy_microchip_ksz8081.c:297]: > ah -- yeah. Sorry. Both comments confused me for the reason you just described. I think it would be worth clarifying to indeed explain that "just" going with the datasheet recommendation isn't enough, otherwise I feel it can read as a typo. Will remove my block though -- sorry again for the noise!

No worries, if it doesn't make sense to someone seeing it for the first time then it should probably be changed :)

File: drivers/ethernet/phy/phy_microchip_ksz8081.c (hunk 2 above)
Comment (decsny) [reply drivers/ethernet/phy/phy_microchip_ksz8081.c:303]: yeah i just doubled the minimum time arbitrarily but on purpose
