### PR TITLE
samples: Bluetooth: remove dup pointer in broadcast_audio_sink

### LINKED ISSUE #63088: Only one receive state reference is needed in the broadcast_audio_sink sample
**Describe the bug**
In  _broadcast_audio_sink/main.c_ there are two _bt_bap_scan_delegator_recv_state_ pointers referencing the same address: 

```
static const struct bt_bap_scan_delegator_recv_state *sink_recv_state;
const struct bt_bap_scan_delegator_recv_state *broadcast_recv_state;
```
In function _pa_sync_req_cb()_, both these pointers get assigned the passed _recv_state_ parameter.

There should only be a need for one pointer here : `static const struct bt_bap_scan_delegator_recv_state *sink_recv_state`

**To Reproduce**
Code observation

**Expected behavior**
No effect on the application behaviour 

**Impact**
It will add confusion for other developers

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - OS: Windows 11
 - Zephyr main branch
 - Latest commit

### PR DESCRIPTION
**Pull request by kruithofa**
In the broadcast_audio_sink sample there are two pointers defined, both referencing the same address. We reduce this to one pointer

fixes #63088

Signed-off-by: Andries Kruithof <andries.kruithof@nordicsemi.no>

### CODE REVIEW

File: samples/bluetooth/broadcast_audio_sink/src/main.c [hunk 1]
```diff
@@ -40,7 +40,7 @@ static K_SEM_DEFINE(sem_bis_sync_requested, 0U, 1U);
 static K_SEM_DEFINE(sem_bis_synced, 0U, CONFIG_BT_BAP_BROADCAST_SNK_STREAM_COUNT);
 
 /* Sample assumes that we only have a single Scan Delegator receive state */
-static const struct bt_bap_scan_delegator_recv_state *sink_recv_state;
+static const struct bt_bap_scan_delegator_recv_state *past_req_recv_state;
```
Comment (Thalley) [inline samples/bluetooth/broadcast_audio_sink/src/main.c:43]: The changes are good, but I think the `past` part of the name is misleading: Isn't this also used to sync with a broadcast source without using PAST? 

Suggest to just rename it `pa_req_recv_state` or `req_recv_state`

**Review by Thalley — CHANGES_REQUESTED** [review]

File: samples/bluetooth/broadcast_audio_sink/src/main.c (hunk 1 above)
Comment (kruithofa) [reply samples/bluetooth/broadcast_audio_sink/src/main.c:43]: Yes, I was also unsure about the proper name. Will change into req_recv_state

**Review by Thalley — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
