### PR TITLE
drivers: entropy: fix native_posix driver for more than 3 byte requests

### LINKED ISSUE #83447: native_posix entropy driver produces very bad entropy for 64 bit targets
**Describe the bug**
The native_posix fake entropy driver produces bad entropy for requests of more than 3 bytes,
and specially for native_sim//64 builds.

The host random() provides a number between 0 and 2**31-1 (INT_MAX), so bit 32 was always 0.
So when filling a buffer with more than 3 bytes we would be filling each 4th byte with a byte which always had its MSbit as 0.

For LP64 native_sim//64 builds, this was even worse, as the driver had another bug where we assumed random() returned the whole long filled, and therefore all 4 upper bytes would be 0.

**To Reproduce**
N/A

**Expected behavior**
Buffers without too many 0s :)

**Impact**
For native_[sim,posix]//64 the entropy would be really bad when requesting more than 4 bytes

**Logs and console output**
N/A

**Environment (please complete the following information):**

 - OS: Linux (any)
 - Toolchain (e.g Zephyr SDK, ...): Any
 - Commit SHA or Version used: main da91dbdd528194c68e7bfea0029541f4335ed9b6

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by aescolar**
Fix the native_posix fake entropy driver for more than 3 byte requests, and specially for native_sim//64 builds.

The host random() provides a number between 0 and 2**31-1 (INT_MAX), so bit 32 was always 0.
So when filling a buffer with more than 3 bytes we would be filling each 4th byte with a byte which always had its MSbit as 0.

For LP64 native_sim//64 builds, this was even worse, as the driver had another bug where we assumed random() returned the whole long filled, and therefore all 4 upper bytes would be 0.

Fixes #83447

### CODE REVIEW

File: drivers/entropy/fake_entropy_native_posix.c [hunk 1]
```diff
@@ -35,18 +36,25 @@ static int entropy_native_posix_get_entropy(const struct device *dev,
...
+		bits_ready += 31;
 
-		size_t to_copy = MIN(length, sizeof(long int));
+		size_t to_copy = MIN(length, bits_ready / 8);
 
 		memcpy(buffer, &value, to_copy);
 		buffer += to_copy;
 		length -= to_copy;
+		value >>= to_copy * 8;
+		bits_ready -= to_copy * 8;
```
Comment (tomi-font) [inline drivers/entropy/fake_entropy_native_posix.c:57]: I find this a bit complicated. Why not just copy 3 bytes at a time at every loop iteration and dump the remaining 7 bits returned by the host random? I don't think we're concerned about performance to that point here?

**Review by tomi-font — COMMENTED** [review]
Literally fake entropy it is. :smile:

File: drivers/entropy/fake_entropy_native_posix.c (hunk 1 above)
Comment (aescolar) [reply drivers/entropy/fake_entropy_native_posix.c]: Fair enough :), I did overdo it indeed.

**Review by tomi-font — DISMISSED** [review]

**Review by tomi-font — APPROVED** [review]

**Review by JordanYates — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]

**Review by mniestroj — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
