### PR TITLE
sd: modify sdmmc_wait_ready to always decrement timeout

### LINKED ISSUE #65027: sd: sdmmc_wait_ready does not respect its timeout if the SD card is physically disconnected
**Describe the bug**
When using an SD card for storage using SPI, if the card is physically detached after successfully initializing, attempting to write to the card will not return an error, but never return from the SD subsystem.

The issue is caused by the change in commit 9a63abc where the function `sdmmc_wait_ready` in sd_ops.c is used to wait for the card to be ready after a failed write (in the card_write function). Before this, it would only check once using `sdmmc_read_status`, and return an error if it was not immediately ready.

The problem is that if the card is physically detached, sdmmc_wait_ready never returns.
```
/* Waits for SD card to be ready for data. Returns 0 if card is ready */
int sdmmc_wait_ready(struct sd_card *card)
{
    int ret, timeout = CONFIG_SD_DATA_TIMEOUT * 1000;
    bool busy = true;

    do {
        busy = sdhc_card_busy(card->sdhc);
        if (!busy) {
            /* Check card status */
            ret = sd_retry(sdmmc_read_status, card, CONFIG_SD_RETRY_COUNT);
            busy = (ret != 0);
        } else {
            /* Delay 125us before polling again */
            k_busy_wait(125);
            timeout -= 125;
        }
    } while (busy && (timeout > 0));
    return busy;
}
```
If the card is disconnected the SPI response is always 0xFF (pull-up resistors on data lines), and `sdhc_card_busy(card->sdhc)` therefore returns false, while `sd_retry(sdmmc_read_status, card, CONFIG_SD_RETRY_COUNT)` returns `-ETIMEDOUT` (since `sdmmc_read_status` always returns `SD_RETRY`). Therefore, timeout is never decremented, busy is always true when checked, and the loop runs forever.

I would suggest something like this as a fix:
```
/* Waits for SD card to be ready for data. Returns 0 if card is ready */
int sdmmc_wait_ready(struct sd_card *card)
{
    int ret, timeout = CONFIG_SD_DATA_TIMEOUT * 1000;

    do {
        if (!sdhc_card_busy(card->sdhc)) {
            /* Check card status */
            ret = sd_retry(sdmmc_read_status, card, CONFIG_SD_RETRY_COUNT);
            if (ret == 0) {
                return 0;
            }
        } 
        /* Delay 125us before polling again */
        k_busy_wait(125);
        timeout -= 125;
    } while (timeout > 0);
    return 1;
}
```

**To Reproduce**
1. Start an application with an SD card connected using SPI
2. (Optionally write successfully to the SD card as long as it is connected)
3. Disconnect the SD card
4. Attempt to write data to it, e.g. `fs_write` and `fs_sync`
5. Observe how `fs_sync` never returns

**Expected behavior**
sdmmc_wait_ready should time out, so that an error is returned from the file system functions if SD card access fails.

**Impact**
We will have to stay with an older version of Zephyr until this is fixed, as it significantly reduces the robustness of our application. When using an SD card for logging, this bug will block other backends.

**Environment (please complete the following information):**
 - nRF SDK 2.5.0 (Zephyr 3.4.99)

### PR DESCRIPTION
**Pull request by danieldegrasse**
As described in issue #65027, sdmmc_wait_ready can enter an infinite loop if the card is removed while waiting for it to report an idle status. Fix this by always decrementing the timeout in sdmmc_wait_ready, regardless of whether the SD card is busy.

Fixes #65027

### CODE REVIEW

File: subsys/sd/sd_ops.c [hunk 1]
```diff
@@ -63,21 +63,20 @@ int sdmmc_read_status(struct sd_card *card)
...
+				return 0;
+			}
 		}
-	} while (busy && (timeout > 0));
-	return busy;
+		/* Delay 125us before polling again */
+		k_busy_wait(125);
+		timeout -= 125;
+	} while (timeout > 0);
+	return 1;
```
[the remark this answers is not in the document]
Comment (danieldegrasse) [reply subsys/sd/sd_ops.c:79]: What about returning `-EBUSY`? The comment for `sdmmc_wait_ready` indicates it should return 0 if the card is ready (to indicate the wait succeeded).

[the remark this answers is not in the document]
Comment (danieldegrasse) [reply subsys/sd/sd_ops.c]: Change applied. I've also updated the timeout logic, so that the timeout duration is a bit closer to `CONFIG_SD_DATA_TIMEOUT` in the case where the card is detached.

File: subsys/sd/sd_ops.c [hunk 2]
```diff
@@ -63,21 +63,28 @@ int sdmmc_read_status(struct sd_card *card)
...
+				 * SD_CMD_TIMEOUT * SD_RETRY_COUNT * 1000
+				 */
+				timeout -= (CONFIG_SD_CMD_TIMEOUT *
+					    CONFIG_SD_RETRY_COUNT) * 1000;
+			}
 		}
-	} while (busy && (timeout > 0));
-	return busy;
+		/* Delay 125us before polling again */
+		k_busy_wait(125);
```
Comment (decsny) [inline subsys/sd/sd_ops.c:84]: should this be configurable

File: subsys/sd/sd_ops.c [hunk 3]
```diff
@@ -63,21 +63,28 @@ int sdmmc_read_status(struct sd_card *card)
...
+		timeout -= 125;
+	} while (timeout > 0);
```
Comment (decsny) [inline subsys/sd/sd_ops.c:86]: `CONFIG_SD_CMD_TIMEOUT` being greater than ~22 seconds with `CONFIG_SD_RETRY_COUNT` something like 100 could result in integer overflow in this code, I'm not sure if this is a reasonably expected scenario though, it seems a little ridiculous, but I'm just pointing this out.

Comment (decsny) [reply subsys/sd/sd_ops.c:86]: Just in case if you think it's an issue you could use [u32_add_overflow](https://docs.zephyrproject.org/latest/doxygen/html/group__math__extras.html#ga3f36aa272f5595d78c6e8219b2c4dbfb) from math_extras.h

Comment (danieldegrasse) [reply subsys/sd/sd_ops.c:86]:
```
$ west build -p always -b lpcxpresso55s69_cpu0 tests/drivers/disk/disk_access/ -DCONFIG_SD_CMD_TIMEOUT=22000 -DCONFIG_SD_RETRY_COUNT=10

[99/155] Building C object zephyr/subsys/sd/CMakeFiles/subsys__sd.dir/sd_ops.c.obj
/home/danieldegrasse/zephyr/zephyrproject/zephyr/subsys/sd/sd_ops.c: In function 'sdmmc_wait_ready':
/home/danieldegrasse/zephyr/zephyrproject/zephyr/subsys/sd/sd_ops.c:80:68: warning: integer overflow in expression of type 'int' results in '-2094967296' [-Woverflow]
   80 |                                             CONFIG_SD_RETRY_COUNT) * 1000;
```
Given that the compiler warns about it, I think we are ok to leave this as is.

File: subsys/sd/sd_ops.c (hunk 2 above)
Comment (danieldegrasse) [reply subsys/sd/sd_ops.c:84]: It could be but I don't think it's worth the extra Kconfig. Really this function is unlikely to wait exactly `CONFIG_SD_DATA_TIMEOUT` ms, because the actual delay will come down to how the SD host controller driver handles a slow card. The main goal here is simply that an SD card that is unresponsive (or dead) will timeout here, but a working but slow card will function

**Review by jfischer-no — APPROVED** [review]
"As described in issue #65027, sdmmc_wait_ready can enter an"
Would be nice to have issue URL instead of Github reference.

**Comment by danieldegrasse** [comment]
> "As described in issue https://github.com/zephyrproject-rtos/zephyr/issues/65027, sdmmc_wait_ready can enter an"
Would be nice to have issue URL instead of Github reference.

The github UI refuses to display it, but I've updated the commit to include the URL.

**Review by decsny — APPROVED** [review]
