### PR TITLE
Bluetooth: Controller: Fix BIG Create silently fail on RTN/SDU_interval

### LINKED ISSUE #46186: ISO Broadcaster fails silently on unsupported RTN/SDU_Interval combination
When a user selects a specific RTN/SDU_Interval combination in the ISO_BROADCAST sample, broacaster fails without an error message. The user doesn't know what has happened.

As @Thalley suggested, a short error message would be nice to have.

Note: tested on two nRF52840DK boards with the code of the following draft PR: https://github.com/zephyrproject-rtos/zephyr/pull/46187

Screenshot 2022-06-02 at 12 18 32 PM

### PR DESCRIPTION
**Pull request by cvinayak**
Fix BIG Create implementation from silently failing on
values of RTN and SDU_interval that lead to BIG events that
cannot be acheived when using sequential or interleaved
subevents by the Controller Implementation.

Fixes #46186.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_adv_iso.c [hunk 1]
```diff
@@ -259,6 +259,12 @@ uint8_t ll_big_create(uint8_t big_handle, uint8_t adv_handle, uint8_t num_bis,
 		lll_adv_iso->bis_spacing = lll_adv_iso->sub_interval;
 		latency_packing = lll_adv_iso->sub_interval * lll_adv_iso->nse *
 				  lll_adv_iso->num_bis;
+		if (latency_packing > sdu_interval) {
+			ll_rx_link_release(link_cmplt);
+			ll_rx_link_release(link_term);
+
+			return BT_HCI_ERR_INVALID_PARAM;
+		}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_iso.c:267]: Suggest to add empty line after ending curly bracket:
```suggestion
		}
		
```

Not sure if this is something that is commonly done in the controller, but at least it is in the host. Supposedly this increases readability :)

File: subsys/bluetooth/controller/ll_sw/ull_adv_iso.c [hunk 2]
```diff
@@ -268,6 +274,12 @@ uint8_t ll_big_create(uint8_t big_handle, uint8_t adv_handle, uint8_t num_bis,
 		uint32_t latency_packing;
 
 		latency_packing = lll_adv_iso->sub_interval * lll_adv_iso->nse;
+		if (latency_packing > sdu_interval) {
+			ll_rx_link_release(link_cmplt);
+			ll_rx_link_release(link_term);
+
+			return BT_HCI_ERR_INVALID_PARAM;
+		}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_iso.c:282]: Ditto

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_adv_iso.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv_iso.c:267]: Done

**Review by Thalley — DISMISSED** [review]
LGTM

File: subsys/bluetooth/controller/ll_sw/ull_adv_iso.c [hunk 3]
```diff
@@ -254,6 +254,12 @@ uint8_t ll_big_create(uint8_t big_handle, uint8_t adv_handle, uint8_t num_bis,
 	latency_pdu = max_latency * USEC_PER_MSEC * lll_adv_iso->bn / bn;
 	latency_packing = lll_adv_iso->sub_interval * lll_adv_iso->nse *
 			  lll_adv_iso->num_bis;
+	if (latency_packing > sdu_interval) {
+		ll_rx_link_release(link_cmplt);
+		ll_rx_link_release(link_term);
+
+		return BT_HCI_ERR_INVALID_PARAM;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_iso.c:262]: Can you add a comment about why we are releasing the link if the latency is larger than the SDU interval? I assume it's because that would be impossible to schedule?

**Review by Thalley — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
