### PR TITLE
posix: c_lib_ext: fnmatch: fix escape-oriented regression

### LINKED ISSUE #55186: posix: fnmatch: fix known bugs
**Describe the bug**
It appears as though the original `fnmatch()` implementation that was checked-in with 486b731b40717a16f619b07e5d58aaf7d5143e78 has bugs. This is not surprising since it was checked-in without any test coverage.

The actual failing cases are commented-out in `tests/lib/posix/common/src/fnmatch.c` (part of #55184)

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? N/A
 - What have you tried to diagnose or workaround this issue? Comment-out known failure modes in the test
 - Is this a regression? No, the bugs have always been present

**To Reproduce**
1. Uncomment failure modes in `tests/lib/posix/common/src/fnmatch.c`
2.`west build -p auto -b qemu_cortex_a53 -t run tests/posix/common/`
3. See error

**Expected behavior**
All test cases should pass, including known failure modes.

**Impact**
The shell has been using a buggy version of `fnmatch()` since approximately 2018.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.3.0-475-gec19849fec26 ***
Running TESTSUITE posix_apis
===================================================================
START - fnmatch

    Assertion failed at WEST_TOPDIR/zephyr/tests/posix/common/src/fnmatch.c:35: posix_apis_fnmatch: fnmatch("[[?*\\]", "\\", 0) is non-zero

 FAIL - fnmatch in 0.001 seconds
===================================================================
```

**Environment (please complete the following information):**
 - OS: Any
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK v0.15.2
 - Commit SHA or Version used: b83cf1f1ee244e48a22844be181fd6ae2366e2c1 but goes as far back as 486b731b40717a16f619b07e5d58aaf7d5143e78

**Additional context**
Noticed in the context of #55185

### PR DESCRIPTION
**Pull request by cfriedt**
A regression in 936d0278bdfa773390469aa102a3de004f355514 introduced a subtle bug in the way that escaped expressions were handled.

The regression originated with the assumption that test data (originally adapted from a 3rd-party testsuite) was correct when it was in fact flawed.

Specifically, `fnmatch("[[?*\\]", "\\", 0)` should fail (`FNM_NOMATCH`), since the "\\" sequence (a single backslash after compilation) escapes the following ']' character, thus leaving the bracket expression incomplete.

As @keith-packard  has pointed out, [pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_13_01](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_13_01), a bracket expression is only interpreted as a bracket expression, when a proper bracket expression is formed.

Therefore, the pattern is interpreted as the sequence `'['`, `'['`, `'?'`, `'*'`, `']'` and the call should return `FNM_NOMATCH` to indicate failure rather than 0 to indicate success.

Additionally, add support for POSIX character classes, as that was a blocking change request. Partial implementation and tests pulled in from #97400.

Fixes #55186

Verified that tests are compatible with glibc.

Rebased after #99451 was merged

### CODE REVIEW

**Comment by cfriedt** [comment]
It would seem that even the glibc agrees with the former interpretation (that there is an incomplete bracket expression).

A sample program I wrote to test
```cpp
#include <fnmatch.h>
#include <stdio.h>

int main()
{
  const char *pat = "[abc\\]";
  const char *in = "a";
  int ret;

  ret = fnmatch(pat, in, 0);
  if (ret == 0) {
    printf("fnmatch(\"%s\", \"%s\", 0) -> success!\n", pat, in);
  } else {
    printf("fnmatch(\"%s\", \"%s\", 0) -> failed! (%d)\n", pat, in, ret);
  }

  return ret;
}
```
produces the output below.
```shell
$ /tmp/blah 
fnmatch("[abc\]", "a", 0) -> failed! (1)
```

It fails as well with `FNM_NOMATCH` when `pat = "[[?*\\]"` and `in = "\\"`.

**Review by ycsin — DISMISSED** [review]

File: tests/posix/c_lib_ext/src/fnmatch.c
Comment (keith-packard) [inline tests/posix/c_lib_ext/src/fnmatch.c]: This test is incorrect. The first path component, `"a"`, matches `*[![:digit:]]*` as `'a'` is not a digit. The second path component, `"b"`, matches `[![:d-d]` because `'b'` is not `[`, not `:` and not any of the range `d-d`.

Comment (keith-packard) [inline tests/posix/c_lib_ext/src/fnmatch.c]: This test is also incorrect, again `"a"` matches `*[![:digit:]]*` while `"["` matches one of `[`, `:` or the range `d-d`.

I'd strongly prefer that the bugs in the Zephyr implementation be fixed before this series is merged; there's no particular reason to commit known-buggy code, especially as this function doesn't appear to be urgently in need of updates.

**Review by keith-packard — DISMISSED** [review]
Please fix the remaining bugs in the implementation and update the tests to conform with the spec.

**Comment by cfriedt** [comment]
The attached file can be used to verify that all of the tests in the testsuite are compatible with glibc as well.

```shell
gcc -o test-fnmatch-natively test-fnmatch-natively.c
./test-fnmatch-natively
```

[test-fnmatch-natively.c](https://github.com/user-attachments/files/23967609/test-fnmatch-natively.c)

Interestingly, the macOS libc is slightly incompatible.

```shell
test-fnmatch-natively.c:73: (fnmatch("[[?*\\]", "\\", 0)) failed (expected 1, actual 2)
test-fnmatch-natively.c:88: (fnmatch("[]?*\\]", "]", 0)) failed (expected 1, actual 0)
test-fnmatch-natively.c:115: ((fnmatch("[/b", "[/b", 0))) failed (expected 0, actual 2)
test-fnmatch-natively.c:138: ((fnmatch("*[![:digit:]]*/[![:d-d]", "a/b", 0x02))) failed (expected 0, actual 2)
test-fnmatch-natively.c:139: ((fnmatch("*[![:digit:]]*/[[:d-d]", "a/[", 0x02))) failed (expected 0, actual 2)
test-fnmatch-natively.c:140: (fnmatch("*[![:digit:]]*/[![:d-d]", "a/[", 0x02)) failed (expected 1, actual 2)
test-fnmatch-natively.c:189: (fnmatch("[[:foobarbaz:]]", "Z", 0)) failed (expected 1, actual 2)
```

File: lib/posix/c_lib_ext/fnmatch.c [hunk 1]
```diff
@@ -48,26 +53,121 @@
...
+	case FNM_CC5('a', 'l', 'n', 'u', 'm'):
+		ret = !isalnum(ch);
+		break;
+	case FNM_CC5('a', 'l', 'p', 'h', 'a'):
+		ret = !isalpha(ch);
+		break;
+	case FNM_CC5('b', 'l', 'a', 'n', 'k'):
+		ret = !isblank(ch);
+		break;
+	case FNM_CC5('c', 'n', 't', 'r', 'l'):
```
Comment (Spago123) [inline lib/posix/c_lib_ext/fnmatch.c:121]: These part, would be more readable if the cases were indented, but it is fine this way also

File: tests/posix/c_lib_ext/src/fnmatch.c
Comment (cfriedt) [reply tests/posix/c_lib_ext/src/fnmatch.c]: Fixed!

Comment (cfriedt) [reply tests/posix/c_lib_ext/src/fnmatch.c]: Fixed!

File: lib/posix/c_lib_ext/fnmatch.c (hunk 1 above)
Comment (cfriedt) [reply lib/posix/c_lib_ext/fnmatch.c:121]: I think this is the usual auto-formatting that's done with `clang-format`, so likely changing it would incur some compliance warnings. I'll leave it as is.

**Review by ycsin — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
