### PR TITLE
drivers: flash: flash_mcux_flexspi_nor: support reading SFDP for flash configuration

### LINKED ISSUE #55379: flash_mcux_flexspi_nor: incorrect enabling quad mode
**Describe the bug**
For enable quad mode `flash_mcux_flexspi_nor` driver [send](https://github.com/zephyrproject-rtos/zephyr/blob/69966dd452e5ebf9f057b393b1e5cdac9ea2034b/drivers/flash/flash_mcux_flexspi_nor.c#L340) value `0x40` to status register 1. It is valid value for **IS25WP064**, which is used in `mimxrt1064_evk` board, but for [Winbond **W25Q128JV**](https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&partNo=W25Q128JV) need set bit 2 in status register 2.

**Expected behavior**
Driver should select way to enable quad mode accordance vendor id. List of ways (vendors) should be extensible.

------

Later i will try to propose PR with fix. Please, give me comments.

### PR DESCRIPTION
**Pull request by danieldegrasse**
Support SFDP probe in flexspi nor driver. This probe will allow the
flash driver to dynamically configure quad spi flashes for 1-4-4 mode,
expanding the flash chips supported with this driver.

The following data is read from the SFDP header:
- quad enable method
- fast read command (1-4-4 is maximum supported)

This PR has been validated with the following Flash chips:
- IS25WP064
- W25Q512NWEIQ
- W25Q32JV

Fixes #55379
~Note: this PR currently depends on #61625~

### CODE REVIEW

**Review by de-nordic — DISMISSED** [review]

**Comment by danieldegrasse** [comment]
Rebased to fix merge conflicts

**Review by mmahadevan108 — APPROVED** [review]

**Comment by danieldegrasse** [comment]
@de-nordic can you revisit this PR when you get a chance?

File: drivers/flash/flash_mcux_flexspi_nor.c [hunk 1]
```diff
@@ -494,11 +459,583 @@ static void flash_flexspi_nor_pages_layout(const struct device *dev,
...
+	 * Update the FlexSPI with the config structure provided
+	 * from devicetree and the configured LUT
+	 */
+	ret = memc_flexspi_set_device_config(&data->controller, &data->config,
+					(uint32_t *)flexspi_lut,
+					FLEXSPI_INSTR_END * MEMC_FLEXSPI_CMD_PER_SEQ,
+					data->port);
+	if (ret < 0) {
+		return ret;
+	}
```
Comment (de-nordic) [inline drivers/flash/flash_mcux_flexspi_nor.c:1021]: At this point you leave the `irq_lock()` from line 945 in effect, is that correct?

Comment (danieldegrasse) [reply drivers/flash/flash_mcux_flexspi_nor.c:1021]: Yes, this is desired- if the flash configuration block cannot be programmed to the FlexSPI at this point (and we are running in execute in place mode) further execution of the init flow is likely impossible, as the FlexSPI won't be able to access flash. Therefore we return with the IRQ lock held, and drop into the `while 1` loop on line 1057. This is preferable to continuing execution, because it gives a developer a chance to debug the failure, while continuing the init flow would likely crash the chip.

**Review by de-nordic — APPROVED** [review]
