### PR TITLE
drivers: console: uart_console: avoid infinite loop in isr

### LINKED ISSUE #62999: drivers: console: uart_console: infinite loop in isr
**Describe the bug**

If the underlying uart tied to the uart console backend does not support interrupt mode for receive, then it enters an infinite loop, hanging the system.

This is due to incorrectly evaluating integer return values as boolean.

`uart_irq_update()`, `uart_irq_is_pending()`, and `uart_irq_rx_ready()` are all static inline functions that return an integer. In the case of an error (e.g. if the underlying uart API function pointer is `NULL`), then a negative value will be returned.

Since any non-zero integer (even negative error codes) are evaluated as `true`, the loop will continue infinitely.

The solution is to compare with integer values, instead of treating the function return value as if it were a `bool`.

https://github.com/zephyrproject-rtos/zephyr/blob/341590545ac80b7a2abd9902b7f10d577323ccde/drivers/console/uart_console.c#L449-L457

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? Qemu targets, currently
 - What have you tried to diagnose or workaround this issue? step-debugged
 - Is this a regression? Unsure
 - ...

**To Reproduce**
1. attempt to use the system console with a uart that does not support interrupt-driven receive and call something like `console_getline()` or `console_getchar()`
2. See error

**Expected behavior**
Read a line of input when using `console_getline()`. Read a character when using `console_getchar()`.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.1
 - Commit SHA or Version used: 4a8d6201279e83c792ecc0bd48fa7dfab65f2e62

**Additional context**
This is a possible duplicate of #60741 because it exhibits similar symptoms, but that was closed.

### PR DESCRIPTION
**Pull request by cfriedt**
Previously, the `uart_console_isr()` routine assumed that the return value of several uart API functions would only ever return the equivalent of a boolean value. The functions return integers in `[-N,0,1]` representing negative `errno` values, `false`, and `true`.

Since unary operations would either go to `true` or `false` and since any non-zero integer evaluates to `true`, even a return value of something like `-ENODEV` would evaluate to `true`.

Explicitly compare against the integer-equivalent value of the expected boolean output.

With this, in the case of errors, negative return values do not evaluate to `true`, and the infinite loop is avoided.

Fixes #62999

### CODE REVIEW

File: drivers/console/uart_console.c [hunk 1]
```diff
@@ -446,13 +446,13 @@ static void uart_console_isr(const struct device *unused, void *user_data)
 	ARG_UNUSED(user_data);
 	static uint8_t last_char = '\0';
 
-	while (uart_irq_update(uart_console_dev) &&
-	       uart_irq_is_pending(uart_console_dev)) {
+	while (uart_irq_update(uart_console_dev) == 1 &&
```
Comment (keith-packard) [inline drivers/console/uart_console.c:449]: Maybe check > 0 instead? Might be one less instruction...

**Review by keith-packard — DISMISSED** [review]
Looks like you found all of the uart API calls that weren't being used correctly.

File: drivers/console/uart_console.c (hunk 1 above)
Comment (cfriedt) [reply drivers/console/uart_console.c:449]: Yep - without any optimization, that saves 2 instructions on RISC-V.

**Comment by cfriedt** [comment]
* used `> 0` comparison instead of explicit `== 1` to save 2 instructions on RISC-V

**Comment by cfriedt** [comment]
The bot didn't seem to auto-assign reviewers, so I the old analog PRNG picked a few.

**Comment by cfriedt** [comment]
IIRC, we used to use macros for some of these APIs - I think it was just never the case that they would return negative values perhaps, and then they were converted to syscalls, etc.

File: drivers/console/uart_console.c [hunk 2]
```diff
@@ -446,13 +446,13 @@ static void uart_console_isr(const struct device *unused, void *user_data)
...
-	while (uart_irq_update(uart_console_dev) &&
-	       uart_irq_is_pending(uart_console_dev)) {
+	while (uart_irq_update(uart_console_dev) > 0 &&
+	       uart_irq_is_pending(uart_console_dev) > 0) {
 		static struct console_input *cmd;
 		uint8_t byte;
 		int rx;
 
-		if (!uart_irq_rx_ready(uart_console_dev)) {
+		if (uart_irq_rx_ready(uart_console_dev) == 0) {
```
Comment (keith-packard) [inline drivers/console/uart_console.c:455]: This doesn't look right -- if the rx_ready function returns failure, the isr should probably return. Probably need to check for three cases -- not ready (continue), failure (return), ready (read a byte).

**Review by keith-packard — CHANGES_REQUESTED** [review]
Check what to do when uart_irq_rx_ready returns an error.

File: drivers/console/uart_console.c (hunk 2 above)
Comment (cfriedt) [reply drivers/console/uart_console.c:455]: I can test it. The current code works though as well.

Note: The logic here isn't changed from before

Comment (keith-packard) [reply drivers/console/uart_console.c:455]: Yup, I realize you haven't changed how it works, but it sure looks like it was broken before :-)

Comment (cfriedt) [reply drivers/console/uart_console.c:455]: @dcpleung - I'm curious to know what you think in this case. The proposal is to change this conditional from
```cpp
		if (uart_irq_rx_ready(uart_console_dev) == 0
			/* formerly !uart_irq_rx_ready(uart_console_dev) */) {
  			continue;
		}
```
to this 
```cpp
		if (uart_irq_rx_ready(uart_console_dev) <= 0) {
			return;
		}
```

Twister / qemu tests work for me here with the latter, I'm just not 100% sure if it will work exactly the same on every target supported by Zephyr. And that logic goes all the way back to when the driver was first added.

Comment (keith-packard) [reply drivers/console/uart_console.c:455]: The old code looks like it was polling waiting for RX ready; you're proposing to have it simply bail if there's nothing pending instead of spinning. That seems like a pretty significant semantic change...

Comment (cfriedt) [reply drivers/console/uart_console.c:455]: > The old code looks like it was polling waiting for RX ready; you're proposing to have it simply bail if there's nothing pending instead of spinning. That seems like a pretty significant semantic change...

Ah, sorry - I misread your earlier message.

Comment (cfriedt) [reply drivers/console/uart_console.c:455]: @keith-packard - done!

**Review by keith-packard — APPROVED** [review]

**Review by ycsin — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
