### PR TITLE
stm32,i2c: Fix large I2C transactions

### LINKED ISSUE #43235: STM32 platform does not handle large i2c_write() correctly
**Describe the bug**
i2c_write() is generating extra starts at multiple of 255 bytes boundary for STM32 platform (v2).

For example, I have an array of data that's is 512 bytes, and I am writing that data to slave addr 0x5f.
uint8_t d[512];
i2c_write(dev, &d[0], 512, 0x5f); 

I am expecting to see: Start 5f/w d[0] .... d[511] Stop
Instead, I am seeing: start 5f/w d[0] .... d[254] Start 5f/w d[255] ... d[509] Start 5f/w d[510] d[511] Stop

I think the issue is in this section of code ```drivers/i2c/i2c_ll_stm32.c``` function ```i2c_stm32_transfer```
```
        while (num_msgs > 0) {
                uint8_t *next_msg_flags = NULL;

                if (num_msgs > 1) {
                        next = current + 1;
                        next_msg_flags = &(next->flags);
                }
                do {
                        uint32_t temp_len = current->len;
                        uint8_t tmp_msg_flags = current->flags & ~I2C_MSG_RESTART;
                        uint8_t tmp_next_msg_flags = next_msg_flags ?
                                                        *next_msg_flags : 0;

                        if (current->len > 255) {
                                current->len = 255U;
                                current->flags &= ~I2C_MSG_STOP;
                                if (next_msg_flags) {
                                        *next_msg_flags = current->flags &
                                                          ~I2C_MSG_RESTART;
                                }
                        }
                        if ((current->flags & I2C_MSG_RW_MASK) ==
                                                                I2C_MSG_WRITE) {
                                ret = stm32_i2c_msg_write(dev, current,
                                                          next_msg_flags,
                                                          slave);
                        } else {
                                ret = stm32_i2c_msg_read(dev, current,
                                                         next_msg_flags, slave);
                        }

                        if (ret < 0) {
                                goto exit;
                        }
                        if (next_msg_flags) {
                                *next_msg_flags = tmp_next_msg_flags;
                        }
                        current->buf += current->len;
                        current->flags = tmp_msg_flags;
                        current->len = temp_len - current->len;
                } while (current->len > 0);
                current++;
                num_msgs--;
        }
```
With i2c_write(), num_msgs = 1, and next_msg_flags will be NULL.
```
                                ret = stm32_i2c_msg_write(dev, current,
                                                          next_msg_flags,
                                                          slave);
````
Since next_msg_flags is NULL, ```LL_I2C_EnableReloadMode``` will not trigger in ```drivers/i2c/i2c_ll_stm32_v2.c``` function ```msg_init```, which is called by ```stm32_i2c_msg_write```.
And each time ```stm32_i2c_msg_write``` is called, a start condition is generated.

### PR DESCRIPTION
**Pull request by ft**
The stm32's I2C peripheral has a maximum transmission size. Larger transaction,
that I2C itself allows, can be achieved be using the peripheral's reload-mode.

In order to do that, st's low-lever drivers need to be informed accordingly.
The previous iteration of the code mishandled the next_msg_flags parameter,
causing the issue to manifest itself.

This refactors the inner loop of i2c_stm32_transfer() into its own function.
This passes the message parameter by value in order to be able to mutate its
state while keeping the original datum from the user intact during the entire
procedure.

Fixes #43235

Signed-off-by: Frank Terbeck <ft@bewatermyfriend.org>

### CODE REVIEW

**Comment by ft** [comment]
The coding style checker wasn't happy and I didn't realise commit message lines have a limit at 75 characters. Those should be fixed with the recent force-push. *fingers-crossed*

File: drivers/i2c/i2c_ll_stm32.c [hunk 1]
```diff
@@ -61,6 +61,56 @@ int i2c_stm32_runtime_configure(const struct device *dev, uint32_t config)
...
+	 * The last chunk of a transmission uses this function's next_msg_flags
+	 * parameter for its backend calls (_write/_read). Any previous chunks
+	 * use a copy of the current message's flags, with the STOP and RESTART
+	 * bits turned off. This will cause the backend to use reload-mode,
+	 * which will make the combination of all chunks to look like one big
+	 * transaction on the wire.
+	 */
+	const uint32_t i2c_stm32_maxchunk = 255U;
+	const uint8_t savedflags = msg.flags;
+	uint8_t combineflags =
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32.c:83]: Nit: saved_flags, combine_flags. Not blocking

**Review by erwango — DISMISSED** [review]
Minor comment, otherwise LGTM

File: drivers/i2c/i2c_ll_stm32.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (ft) [reply drivers/i2c/i2c_ll_stm32.c]: Fixed

Comment (ft) [reply drivers/i2c/i2c_ll_stm32.c]: And fixed

**Review by erwango — DISMISSED** [review]

**Review by ABOSTM — APPROVED** [review]

**Review by erwango — APPROVED** [review]
