### PR TITLE
net: tcp2: Mark tcphdr struct as packed

### LINKED ISSUE #31145: Litex-vexriscv address misaligned with dumb_http_server example
**Bug description**
On Arty-7 board when running the eth dumb_http_server with vexriscv core
I encountered the error with misaligned memory access.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=litex_vexriscv
3. make
The bitstream was generated with https://github.com/litex-hub/zephyr-on-litex-vexriscv

**Expected behavior**
After sending the HTTP request using curl I expected to see the returned page.
I have configured the network and run the following command  `curl http://192.168.2.4:8080`

**Logs and console output**
On arty board the following error occurs:
```
[00:00:08.810,000] <err> os: Exception cause Load address misaligned (4)
[00:00:08.810,000] <err> os: Faulting instruction address = 0x40010dec
[00:00:08.810,000] <err> os:   ra: 0x40010ddc  gp: 0xffffffff  tp: 0xffffffff  t0: 0x00000080
[00:00:08.810,000] <err> os:   t1: 0x4001c7c0  t2: 0xfffffff5  t3: 0xffffffff  t4: 0xffffffff
[00:00:08.810,000] <err> os:   t5: 0xffffffff  t6: 0xffffffff  a0: 0x40023392  a1: 0x00000000
[00:00:08.810,000] <err> os:   a2: 0x40022ed8  a3: 0x40023392  a4: 0x00000001  a5: 0x0000003c
[00:00:08.810,000] <err> os:   a6: 0x00000014  a7: 0x0000003c

[00:00:08.810,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:08.810,000] <err> os: Current thread: 0x4001c7c0 (unknown)
[00:00:08.810,000] <err> os: Halting system


```
The faulting instruction points to https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/ip/tcp2.c#L1269

The asm snippet code:
```
size_t tcp_options_len = th ? (th->th_off - 5) * 4 : 0;
40010de4:	00000993          	li	s3,0
40010de8:	fa0500e3          	beqz	a0,40010d88 <tcp_in+0x50>
40010dec:	00c52983          	lw	s3,12(a0)

```
As we can see we are loading the 32 bit from a misaligned address.
The value in `a0` register equals to `0x40023392` that can't be divided by 4.

The problem occurs since this commit: 70dae094ba2dd3e1f02684a8d673d434966b8b76
The commit introduces tcp_v2 implementation.
As we can see the problem is caused by `th_off` filed here: https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/net/ip/tcp2_priv.h#L126
The compiler generates the load word instruction instead of the load byte instruction.
I have tested it with other versions of gcc-riscv: 8.2.0 and clang-riscv from trunk.
And I'm quite sure this is correct behavior, cause the struct filed offset is aligned to 4 bytes.
The problem is that somewhere in the code the unaligned memory is cast to this struct.

**Environment:**
 - OS: Linux
 - Toolchain Zephyr SDK 0.11.4
 - Commit: 1c493b4a7706e9934949f8d23f8d8eddc7256200

**Additional context**
When changing `tx_off` to just `uint8_t` and getting rid of the bitfierlds the compiler generates:
```
40010dec:	00c52983          	lbu	s3,12(a0)
```
So this is one of the possible solutions the second is to assure that the memory is correctly aligned.

### PR DESCRIPTION
**Pull request by jukkar**
As the tcp header struct can be cast to unaligned memory, mark
it as packed and access fields using UNALIGNED_GET/PUT when
needed.

Fixes #31145

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

File: subsys/net/ip/tcp2_priv.h [hunk 1]
```diff
@@ -14,6 +14,11 @@
 
 #define th_seq(_x) ntohl(UNALIGNED_GET(&(_x)->th_seq))
 #define th_ack(_x) ntohl(UNALIGNED_GET(&(_x)->th_ack))
+#define th_flags(_x) UNALIGNED_GET(&(_x)->th_flags)
+#define th_off(_x) ((_x)->th_off)
+#define th_dport(_x) UNALIGNED_GET(&(_x)->th_dport)
+#define th_sport(_x) UNALIGNED_GET(&(_x)->th_sport)
+#define th_win(_x) UNALIGNED_GET(&(_x)->th_win)
```
Comment (mniestroj) [inline subsys/net/ip/tcp2_priv.h:21]: Would be nice to keep the same order as fields in `tcphdr`.

File: subsys/net/ip/tcp2.c [hunk 2]
```diff
@@ -689,16 +691,15 @@ static int tcp_header_add(struct tcp *conn, struct net_pkt *pkt, uint8_t flags,
...
-	th->th_sport = conn->src.sin.sin_port;
-	th->th_dport = conn->dst.sin.sin_port;
-
-	th->th_off = 5;
-	th->th_flags = flags;
-	th->th_win = htons(conn->recv_win);
-	th->th_seq = htonl(seq);
+	UNALIGNED_PUT(conn->src.sin.sin_port, &th->th_sport);
+	UNALIGNED_PUT(conn->dst.sin.sin_port, &th->th_dport);
+	th_off(th) = 5;
```
Comment (mniestroj) [inline subsys/net/ip/tcp2.c:696]: Not sure about that line. I assume `th_off()` getter is there to be in sync with other getters of `tcphdr`. However here this getter is used as it would return a reference, not a value. This would be wrong with all other getters.

File: subsys/net/ip/tcp2.c [hunk 3]
```diff
@@ -237,16 +237,18 @@ static const char *tcp_th(struct net_pkt *pkt)
...
-				"bogus th_off: %hu", (uint16_t)th->th_off);
+				"bogus th_off: %hu",
+				(uint16_t)th_off(th));
 		goto end;
 	}
 
 	len += snprintk(buf + len, BUF_SIZE - len,
-			"%s Seq=%u", tcp_flags(th->th_flags), th_seq(th));
+			"%s Seq=%u", tcp_flags(th_flags(th)),
+			th_seq(th));
```
Comment (mniestroj) [inline subsys/net/ip/tcp2.c:249]: This one doesn't need moving to next line. There are other places as well, that easily fit into 80 lines.

**Review by mniestroj — APPROVED** [review]
Looks good. Just minor comments.

**Review by tgorochowik — APPROVED** [review]
Tested this with @pawelsag and it does indeed fix #31145, thanks!
