### PR TITLE
drivers: ethernet: phy: use default speeds props on the other phys

### LINKED ISSUE #92281: eth_nxp_enet_mac failed with -120
### Describe the bug

I am using an overlay to set a set mac on the rt1170. It was working before commit 3d8196f41b38971c6dc837d908162da5f14e0ecf

### Regression

- [x] This is a regression.

### Steps to reproduce

1. Use the sample `hello_world` and replace the main by 
```c
#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(Main, LOG_LEVEL_INF);

#include <zephyr/kernel.h>
#include <stdio.h>

#include <zephyr/net/net_if.h>
#include <zephyr/net/net_core.h>
#include <zephyr/net/net_context.h>
#include <zephyr/net/net_mgmt.h>

#define DHCP_POLLING_MS (500)

static volatile bool ip_is_assigned = false;
static struct net_mgmt_event_callback mgmt_cb;
static struct net_dhcpv4_option_callback dhcp_cb;

static void start_dhcpv4_client(struct net_if *iface, void *user_data) {
        (void)(user_data);
        LOG_INF("Start interface %s: index=%d", net_if_get_device(iface)->name, net_if_get_by_iface(iface));
        net_dhcpv4_start(iface);
}

static void handler(struct net_mgmt_event_callback *cb, uint32_t mgmt_event, struct net_if *iface) {
        int i = 0;

        if (mgmt_event != NET_EVENT_IPV4_ADDR_ADD) {
                return;
        }

        for (i = 0; i < NET_IF_MAX_IPV4_ADDR; i++) {
                char buf[NET_IPV4_ADDR_LEN];

                if (iface->config.ip.ipv4->unicast[i].ipv4.addr_type != NET_ADDR_DHCP) {
                        continue;
                }

                LOG_INF("   Address[%d]: %s", net_if_get_by_iface(iface), net_addr_ntop(AF_INET, &iface->config.ip.ipv4->unicast[i].ipv4.address.in_addr, buf, sizeof(buf)));
                LOG_INF("    Subnet[%d]: %s", net_if_get_by_iface(iface), net_addr_ntop(AF_INET, &iface->config.ip.ipv4->unicast[i].netmask, buf, sizeof(buf)));
                LOG_INF("    Router[%d]: %s", net_if_get_by_iface(iface), net_addr_ntop(AF_INET, &iface->config.ip.ipv4->gw, buf, sizeof(buf)));
                LOG_INF("Lease time[%d]: %u seconds", net_if_get_by_iface(iface), iface->config.dhcpv4.lease_time);

                ip_is_assigned = true;
        }
}


int main(void)
{
        LOG_INF("NET initialization");

        // Initialize callbacks.
        net_mgmt_init_event_callback(&mgmt_cb, handler, NET_EVENT_IPV4_ADDR_ADD);
        net_mgmt_add_event_callback(&mgmt_cb);
        net_dhcpv4_add_option_callback(&dhcp_cb);
        // Start DHCP on all interfaces.
        net_if_foreach(start_dhcpv4_client, NULL);

        // Wait for IP assignment.
        while (!ip_is_assigned) {
                LOG_INF("Waiting for IP");
                k_sleep(K_MSEC(DHCP_POLLING_MS));
        }

        return 0;
}
```
2. Add the following to the prj.conf
```
CONFIG_NETWORKING=y
CONFIG_NET_LOG=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_IPV6=n
CONFIG_NET_IPV4=y
CONFIG_POSIX_API=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POLL_MAX=4
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV4_OPTION_CALLBACKS=y
CONFIG_NET_INTERFACE_NAME=y
CONFIG_NET_DEFAULT_IF_ETHERNET=y
CONFIG_NET_SOCKETS_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_DRIVERS=y
CONFIG_NET_LOOPBACK=y
CONFIG_POSIX_TIMERS=y
CONFIG_XOPEN_STREAMS=y
```
3. Create an overlay with the following content
```
&enet_mac {
         /delete-property/ zephyr,random-mac-address;
        local-mac-address = [your-mac];
};
```
4. Build with the following command `west build -p -b mimxrt1170_evk/mimxrt1176/cm7 -- -DDTC_OVERLAY_FILE=app.overlay`
5. Flash the rt1170

### Relevant log output

```shell
Error log:
[00:00:00.051,000] <inf> phy_mii: PHY (0) ID 1CC816
[00:00:00.053,000] <err> eth_nxp_enet_mac: phy_configure_link failed with error: -120
[00:00:00.054,000] <inf> eth_nxp_enet_mac: Link is down
[00:00:00.054,000] <err> eth_nxp_enet_mac: phy_configure_link failed with error: -120
*** Booting Zephyr OS build v4.1.0-7032-g3198db1b1229 ***
[00:00:00.055,000] <inf> Main: NET initialization
[00:00:00.055,000] <inf> Main: Start interface ethernet: index=1
[00:00:00.055,000] <inf> Main: Start interface lo: index=2
[00:00:00.055,000] <inf> Main: Waiting for IP
[00:00:00.555,000] <inf> Main: Waiting for IP
[00:00:01.055,000] <inf> Main: Waiting for IP
[00:00:01.555,000] <inf> Main: Waiting for IP
[00:00:02.055,000] <inf> Main: Waiting for IP
[00:00:02.555,000] <inf> Main: Waiting for IP
[00:00:03.056,000] <inf> Main: Waiting for IP
[00:00:03.155,000] <inf> phy_mii: PHY (0) Link speed 100 Mb, full duplex
[00:00:03.155,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:03.556,000] <inf> Main: Waiting for IP
[00:00:04.056,000] <inf> Main: Waiting for IP
[00:00:04.556,000] <inf> Main: Waiting for IP
[00:00:05.056,000] <inf> Main: Waiting for IP
[00:00:05.556,000] <inf> Main: Waiting for IP
[00:00:06.056,000] <inf> Main: Waiting for IP
[00:00:06.556,000] <inf> Main: Waiting for IP
[00:00:07.056,000] <inf> Main: Waiting for IP
[00:00:07.557,000] <inf> Main: Waiting for IP
[00:00:08.057,000] <inf> Main: Waiting for IP
--------------------------------------------------------------
Working log

[00:00:00.051,000] <inf> phy_mii: PHY (0) ID 1CC816
[00:00:00.054,000] <inf> eth_nxp_enet_mac: Link is down
*** Booting Zephyr OS build v4.1.0-5129-g05f71f3874d4 ***
[00:00:00.056,000] <inf> Main: NET initialization
[00:00:00.056,000] <inf> Main: Start interface ethernet: index=1
[00:00:00.056,000] <inf> Main: Start interface lo: index=2
[00:00:00.057,000] <inf> Main: Waiting for IP
[00:00:00.557,000] <inf> Main: Waiting for IP
[00:00:01.057,000] <inf> Main: Waiting for IP
[00:00:01.557,000] <inf> Main: Waiting for IP
[00:00:02.058,000] <inf> Main: Waiting for IP
[00:00:02.558,000] <inf> Main: Waiting for IP
[00:00:03.058,000] <inf> Main: Waiting for IP
[00:00:03.558,000] <inf> Main: Waiting for IP
[00:00:04.058,000] <inf> Main: Waiting for IP
[0Hello World! mimxrt1170_evk@B/mimxrt1176/cm7
0:00:04.558,000] <inf> Main: Waiting for IP
[00:00:05.058,000] <inf> Main: Waiting for IP
[00:00:05.456,000] <inf> phy_mii: PHY (0) Link speed 100 Mb, full duplex
[00:00:05.456,000] <inf> eth_nxp_enet_mac: Link is up
[00:00:05.459,000] <inf> net_dhcpv4: Received: 10.10.150.144
[00:00:05.459,000] <inf> Main:    Address[1]: 10.10.150.144
[00:00:05.459,000] <inf> Main:     Subnet[1]: 255.255.255.192
[00:00:05.459,000] <inf> Main:     Router[1]: 10.10.150.129
[00:00:05.459,000] <inf> Main: Lease time[1]: 36000 seconds
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- OS: Windows, Wsl (Ubuntu 24.02)
- Toolchain: Zephyr SDK 0.17
- Commit: 3198db1b12292cf072b69f06000e9e258e529358

### Additional Context

_No response_

### LINKED ISSUE #92399: <err> eth_nxp_enet_mac: phy_configure_link failed with error: -88
### Describe the bug

When a fixed link is configured, the `eth_nxp_enet` driver calls `ret = phy_configure_link(phy, speeds, 0);` (line 475), and it expects to receive `-ENOTSUP`. However, this behavior is likely broken after this [commit](https://github.com/zephyrproject-rtos/zephyr/commit/7505ef3f0425abbd482e20c44dff8d31c81845f4), because the `phy_configure_link` function now checks whether `DEVICE_API_GET(ethphy, dev)->cfg_link == NULL` and returns `-ENOSYS` instead. As a result, the driver's initialization fails, causing Ethernet to become non-functional.

### Regression

- [x] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell
<err> eth_nxp_enet_mac: phy_configure_link failed with error: -88
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by maass-hamburg**
use the default speeds dt prop introduced here https://github.com/zephyrproject-rtos/zephyr/pull/89210 for phy_mii also on the other phys.

### CODE REVIEW

File: drivers/ethernet/phy/phy_microchip_ksz8081.c [hunk 1]
```diff
@@ -24,6 +24,7 @@
 LOG_MODULE_REGISTER(LOG_MODULE_NAME);
 
 #include "phy_mii.h"
+#include "phy_common.h"
```
Comment (Vijayakannan) [inline drivers/ethernet/phy/phy_microchip_ksz8081.c]: phy_mii.h header also common for all phy drivers. Is it possible to use one header for common calls and common macros?

File: drivers/ethernet/phy/phy_microchip_ksz8081.c [hunk 2]
```diff
@@ -44,6 +45,7 @@ struct mc_ksz8081_config {
 	uint8_t addr;
 	const struct device *mdio_dev;
 	enum ksz8081_interface phy_iface;
+	enum phy_link_speed default_speeds;
```
Comment (Vijayakannan) [inline drivers/ethernet/phy/phy_microchip_ksz8081.c:47]: how about using conventional name supported_speeds or link_speeds?

Comment (maass-hamburg) [reply drivers/ethernet/phy/phy_microchip_ksz8081.c:47]: this is only used for configuring the phy on init, so these are the speeds that the phy will use by default, you can still configure the speeds later with `phy_configure_link()` and also set speeds that were not in default_speeds. By the way this is also how it is in phy_mii and this pr is extending it's functionality to the other phys

Comment (Vijayakannan) [reply drivers/ethernet/phy/phy_microchip_ksz8081.c:47]: > this is only used for configuring the phy on init, so these are the speeds that the phy will use by default, you can still configure the speeds later with `phy_configure_link()` and also set speeds that were not in default_speeds. By the way this is also how it is in phy_mii and this pr is extending it's functionality to the other phys

Sorry, I missed the reference to the phy_mii PR earlier. My rationale is as follows:

Currently, default_speeds is generated based on what the specific PHY driver defines in the device tree or YAML, and it is used as a parameter for phy_configure_link().

For example:
  default-speeds:
    default: ["10BASE Half-Duplex", "10BASE Full-Duplex", "100BASE Half-Duplex",
              "100BASE Full-Duplex"]

In practice, users or customers interpret these values as the supported speeds of the specific PHY. Referring to them as "default" is not ideal, as "default" suggests a fallback or initial value, rather than the complete set of speeds the PHY is capable of.

Comment (maass-hamburg) [reply drivers/ethernet/phy/phy_microchip_ksz8081.c:47]: if the user doesn't provide `default-speeds`, we will do auto negotiation with all supported speeds of the phy. That btw is also the default behavior of the phy (based on the registers) if we don't configure it.

also the phy_mii phy was doing phy_configure_link() with all supported speeds before https://github.com/zephyrproject-rtos/zephyr/pull/89210 and to preserve that behavior, these got set as the default, if the user didn't changed the prop in the dts.

**Comment by maass-hamburg** [comment]
rebased due to now merged ci fix

**Review by Vijayakannan — APPROVED** [review]

**Comment by maass-hamburg** [comment]
rebased to resolve confilicts

**Review by rruuaanng — DISMISSED** [review]
LGTM

**Review by rruuaanng — DISMISSED** [review]

**Comment by maass-hamburg** [comment]
ping @decsny @lmajewski @pdgendt @clamattia

**Review by ghost — COMMENTED** [review]
https://github.com/zephyrproject-rtos/zephyr/pull/91572/commits/f4e2b8d3527020eb05b55cff0beb2904402e2775 has duplicated `signed-off-by`.

Also consider a separate PR for https://github.com/zephyrproject-rtos/zephyr/pull/91572/commits/f4e2b8d3527020eb05b55cff0beb2904402e2775 and https://github.com/zephyrproject-rtos/zephyr/pull/91572/commits/e819c7663ff4bbed533f02b34ea08ab016835f3c . It is unrelated to `default speeds`.

**Comment by maass-hamburg** [comment]
> [f4e2b8d](https://github.com/zephyrproject-rtos/zephyr/commit/f4e2b8d3527020eb05b55cff0beb2904402e2775) has duplicated `signed-off-by`.
> 
> Also consider a separate PR for [f4e2b8d](https://github.com/zephyrproject-rtos/zephyr/commit/f4e2b8d3527020eb05b55cff0beb2904402e2775) and [e819c76](https://github.com/zephyrproject-rtos/zephyr/commit/e819c7663ff4bbed533f02b34ea08ab016835f3c) . It is unrelated to `default speeds`.

@clamattia https://github.com/zephyrproject-rtos/zephyr/pull/91726 contained the two commit too and it it now merged, so this PR no longer has these commits.

Rebased because of that and because there were confilcts.

**Review by ghost — APPROVED** [review]
Looks good as far as I can see.

**Review by pdgendt — APPROVED** [review]

**Review by rruuaanng — APPROVED** [review]
