### PR TITLE
drivers: flash: spi_nor: fix flash busy during init

### LINKED ISSUE #51713: drivers: flash: spi_nor: init fails when flash is busy
**Describe the bug**
The spi-nor flash device is automatically initialized during boot, but it does not check if the flash is busy with a write/erase operation. This can happen when a slow erase or page program operation starts before a soft-boot. The result is invalid responses from the flash because it will not decode many instruction when it's busy. Reading the JEDEC ID results in 0x00, 0x00, 0x00 instead of the actual JEDEC ID. So that is probably the most common error unless `CONFIG_SPI_NOR_SFDP_RUNTIME` is configured - then the next command will most likely fail instead.

Datasheet documentation for read JEDEC ID command

Command and response for read JEDEC ID when flash device is busy erasing

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
   - External flash (MX25R6435F) on the nRF9160 DK and nRF52840 DK (using spi instead of qspi).
 - What have you tried to diagnose or workaround this issue?
   - Yes, see #51662.

**To Reproduce**
Steps to reproduce the behavior on an nRF52840 DK:
1. cd samples/drivers/spi_flash
1. unzip [init-busy2.patch.zip](https://github.com/zephyrproject-rtos/zephyr/files/9887988/init-busy2.patch.zip)
  * Updated Oct. 28. to use spi-nor driver instead of nordic-qspi-nor driver
1. git apply init-busy.patch  # attached to this issue
1. enable CONFIG_FLASH_LOG_LEVEL_DBG=y
1. west build -b nrf52840dk_nrf52840
1. open a serial monitor application and connect to the nrf52840 DK
1. west flash
1. wait until you see «Test 1: Flash erase» (it will erase for ~17 seconds)
1. press reset button on the DK to reset during the erase operation
1. result: <err> spi_nor: Device id 00 00 00 does not match config c2 28 17

**Expected behavior**
I would expect the driver to wait until the device is ready or to reset the flash chip instead of failing. I don't know how to recover from this error other than reset the whole system.

**Impact**
It took quite some time to understand why the flash suddenly wouldn't report it's JEDEC id, but respond only zeroes instead of the actual JEDEC id. At first it seemed to fail at random, but later when working on erasing the whole flash (which can take several minutes), it was easier to understand why it was failing.

Handling this will be tricky to work around in the application. I'm not aware of a way to recover other than rebooting the system from the application code if the flash device is not ready. This will cause a reboot loop until the flash is ready. On the nRF9160, the modem will detect multiple ungraceful detaches from the cellular network and prevent the modem to attach to the network for some time.

**Logs and console output**
From the SPI flash sample described above (error is printed before Zephyr boot message because of immediate logging):

```
*** Booting Zephyr OS build zephyr-v3.2.0-987-g12c23aedd5dc  ***

MX25R64 SPI flash testing
==========================

Test 1: Flash erase
[00:00:00.253,723] <err> spi_nor: Device id 00 00 00 does not match config c2 28 17
*** Booting Zephyr OS build zephyr-v3.2.0-987-g12c23aedd5dc  ***
MX25R64: device not ready.
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephyr SDK
 - Commit SHA: a9b223b26b0f19b181e17097d401551c0e6f351c (main)

### PR DESCRIPTION
**Pull request by gregersrygg**
After a soft-reset of the host controller the flash device is not reset. This can cause the flash device to still be busy writing or erasing when the host controller boots and initializes the flash. The often results in errors and the flash device not being initialized.

This fix checks the WIP flag before initializing the flash device and waits until the flash device is ready.

The downside of this fix is that the flash device might be doing a very long operation. Like a chip erase. On some devices (MX25R6435F) this can take over 2 minutes. Because the flash is initialized before the application, there might be no log output before the flash is available. This can cause confusion when users don't know why the boot is very slow, but I think that is a better behaviour than the flash device not being initialized and potentially resetting the whole system multiple times until the device is ready.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/51713

### CODE REVIEW

**Comment by de-nordic** [comment]
Is it possible for you to:
 1) Report an issue for the problem within Zephyr
 2) Make this PR a fix for that issue
 3) Add release notes entry on the fix?

**Comment by gregersrygg** [comment]
@de-nordic I can do that. Will try to modify a sample that reproduces the problem first, which can be used in the issue description.

**Comment by de-nordic** [comment]
> @de-nordic I can do that. Will try to modify a sample that reproduces the problem first, which can be used in the issue description.

Thanks.

**Comment by gregersrygg** [comment]
Created the issue #51713 for this PR.

File: drivers/flash/spi_nor.c [hunk 1]
```diff
@@ -1024,8 +1024,12 @@ static int spi_nor_configure(const struct device *dev)
 		return -ENODEV;
 	}
 
-	/* Might be in DPD if system restarted without power cycle. */
-	exit_dpd(dev);
+	/* After a soft-reset the flash might still be busy writing/erasing or in DPD.
+	 * Exit DPD and wait until ready.
+	 */
+	acquire_device(dev);
+	spi_nor_wait_until_ready(dev);
```
Comment (anangl) [inline drivers/flash/spi_nor.c:1031]: When it is needed to wait for the flash, it would be nice to let the user know what is going on. MISO could be also constantly high, e.g. because of some wrong pin configuration. It would not be good to just silently wait here forever in such case.
How about something like:
```suggestion
	rc = spi_nor_rdsr(dev);
	if (rc > 0 && (rc & SPI_NOR_WIP_BIT)) {
		LOG_WRN("Waiting until flash is ready");
		spi_nor_wait_until_ready(dev);
	}
```

Comment (gregersrygg) [reply drivers/flash/spi_nor.c]: I've added your suggestions, but I wasn't able to configure the logging so the warning is output at the right time. With `CONFIG_LOG_MODE_DEFERRED` the warning isn't output until after the erasing is done, and with `CONFIG_LOG_MODE_IMMEDIATE` it looks like the warning is printed before `*** Booting Zephyr OS build zephyr-v3.2.0-...  ***`. Probably because of the mix of `printk` and `LOG_XXX`. Maybe I've configured the logging incorrectly?

```
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_FLASH_LOG_LEVEL_DBG=y
```

Comment (anangl) [reply drivers/flash/spi_nor.c]: Initialization of the driver is done before the banner is printed, so it is normal that for immediate logging you get the message before the banner.
For deferred logging, adding the following right after `LOG_WRN()` should help:
```
		while (LOG_PROCESS()) {
		}
```

**Review by de-nordic — CHANGES_REQUESTED** [review]
Please add `Fixes #51713` line to the commit message.

**Comment by de-nordic** [comment]
@anangl Can you take look again and comment?

**Review by anangl — DISMISSED** [review]

**Review by de-nordic — APPROVED** [review]

**Review by anangl — APPROVED** [review]
