### PR TITLE
pm: Fix state_force functionality

### LINKED ISSUE #41911: pm_power_state_force returns false after first call
**Describe the bug**
I modified the zephyr/samples/boards/stm32/power_mgmt/stm32wb_ble/src/main.c file and I changed "pure" call to pm_power_state_force for sometihing to allow visually detect problems witch switching to shutdown:
```C
        if (!pm_power_state_force(0u, (struct pm_state_info){PM_STATE_SOFT_OFF, 0, 0})) {
                printk("Cannot force SHUTDOWN!\n");
        }
        k_sleep(K_MSEC(5));
        printk("Not in SHUTDOWN!\n");
```
And unfortunately above condition is met and also "Not in SHUTDOWN!" is printed.

**To Reproduce**
1. Change code in zephyr/samples/boards/stm32/power_mgmt/stm32wb_ble/src/main.c as described above
2. west build -b nucleo_wb55rg
3. west flash
4. Both messages from code above can be observed.

**Expected behavior**
No messages from modified code should be visible and MCU should switch to SHUTDOWN mode..

**Impact**
showstopper

**Logs and console output**
```
*** Booting Zephyr OS build v2.7.99-3296-ge8df8a579033  ***
Starting Beacon Demo
Bluetooth initialized
Beacon started, advertising as 80:E1:26:08:24:BC (public)
Beacon stopped
Beacon started
Device shutdown
Cannot force SHUTDOWN!
Not in SHUTDOWN!
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.13.1
 - Commit SHA e8df8a579033be238beb774e4909d637da649f3a

**Additional context**
I observed that `z_power_states_forced` in pm.c is not equal 0 when `pm_power_state_force` is called **first** time.

### PR DESCRIPTION
**Pull request by ceolin**
The "state forced" flag has to be cleared with the scheduler locked,
otherwise the idle thread can be scheduled out without clear it and
the next call to force a state will fail.

With the forced flag been cleared with the kernel locked in the
suspend path, we need to clear it out when the suspend process fails.

This is mow done before jump to the end label because in the
successful path the flag is already cleared.

Fixes #41911

### CODE REVIEW

File: subsys/pm/pm.c [hunk 1]
```diff
@@ -203,7 +203,7 @@ bool pm_system_suspend(int32_t ticks)
 
 	SYS_PORT_TRACING_FUNC_ENTER(pm, system_suspend, ticks);
 
-	if (!atomic_test_and_set_bit(z_cpus_pm_state_forced, id)) {
+	if (!atomic_test_bit(z_cpus_pm_state_forced, id)) {
```
Comment (erwango) [inline subsys/pm/pm.c:206]: What about `atomic_test_and_clear_bit` ?

Comment (ceolin) [reply subsys/pm/pm.c:206]: Nope, it has to continue set until be used otherwise another thread can force a different state before it be used.

**Review by erwango — APPROVED** [review]

**Comment by erwango** [comment]
@r2r0 would you mind confirm it fixes the point and formally approve ?

**Comment by r2r0** [comment]
Thanks @ceolin - for me it works well.
Additionally I checked if there is really called `pm_power_state_set` with requested state and it does.

**Review by gmarull — APPROVED** [review]
