### PR TITLE
usb: device_next: fix typo in CDC ACM implementation

### LINKED ISSUE #75000: drivers: usb: cdc_acm: copy paste error in fifo size
[usbd_cdc_acm.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/device_next/class/usbd_cdc_acm.c) uses tx_fifo_size for rx and tx buffers. Since the documentation describes rx-fifo-size as well, it should be used for that buffer.

```
RING_BUF_DECLARE(cdc_acm_rb_rx_##n, DT_INST_PROP(n, tx_fifo_size));	\
RING_BUF_DECLARE(cdc_acm_rb_tx_##n, DT_INST_PROP(n, tx_fifo_size));	\
```

### PR DESCRIPTION
**Pull request by jfischer-no**
Check if another context is initialized and fix typo in CDC ACM implementation.

Fixes: #75000

### CODE REVIEW

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by tmon-nordic — APPROVED** [review]

File: subsys/usb/device_next/usbd_core.c [hunk 1]
```diff
@@ -193,7 +193,8 @@ static void usbd_thread(void *p1, void *p2, void *p3)
 		k_msgq_get(&usbd_msgq, &event, K_FOREVER);
 
 		STRUCT_SECTION_FOREACH(usbd_context, uds_ctx) {
-			if (uds_ctx->dev == event.dev) {
+			if (uds_ctx->dev == event.dev &&
+			    usbd_is_initialized(uds_ctx)) {
```
Comment (tmon-nordic) [inline subsys/usb/device_next/usbd_core.c:197]: Does anything actually prevent two separate context structures from being with the same underlying device? I think this might only be fixing the crash in some specific scenarios (only one context initialized) and not always.

I also don't quite like the fact that `usbd_is_initialized()` check is performed for every single message.

**Review by tmon-nordic — CHANGES_REQUESTED** [review]
On a second thought I don't quite like the context check. The CDC ACM is fine and should probably be moved to separate PR.

File: subsys/usb/device_next/usbd_core.c (hunk 1 above)
Comment (jfischer-no) [reply subsys/usb/device_next/usbd_core.c]: > Does anything actually prevent two separate context structures from being with the same underlying device?

No. e.g. Use case is the USB shell's own context.

>I think this might only be fixing the crash in some specific scenarios (only one context initialized) and not always.

Contexts with the same controller are mutually exclusive, only one controller/context can be initialized.

>I also don't quite like the fact that usbd_is_initialized() check is performed for every single message.

Dropped it, I will come up with another solution but not for v3.7.0.

**Review by tmon-nordic — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
