### PR TITLE
Bluetooth: BAP: QoS fixes

### LINKED ISSUE #110775: Bluetooth: BAP: unicast client dereferences NULL stream->qos when a QoS Configured notification arrives before the stream is added to a group
**Describe the bug**

`unicast_client_ep_qos_state()` in
`subsys/bluetooth/audio/bap_unicast_client.c` writes the incoming QoS fields
through `stream->qos`, but the only NULL check it performs is on `stream`
itself, not on `stream->qos`:

```c
stream = ep->stream;
if (stream == NULL) {
        LOG_ERR("No stream active for endpoint");
        return;
}
...
qos = net_buf_simple_pull_mem(buf, sizeof(*qos));
unicast_client_ep_qos_update(ep, qos);
ep->cig_id = qos->cig_id;
ep->cis_id = qos->cis_id;
(void)memcpy(&stream->qos->interval, ...);   /* stream->qos may be NULL */
stream->qos->framing = qos->framing;
stream->qos->phy     = qos->phy;
stream->qos->sdu     = sys_le16_to_cpu(qos->sdu);
...
```

`stream->qos` is populated **only** when the application adds the stream to a
unicast group (`unicast_group_add_stream()` does `stream->qos = qos;`). It is
not set by `bt_bap_stream_config()`, and `bt_bap_stream_detach()` does not reset
it. So between codec-configuring a stream and adding it to a group, the endpoint
has `ep->stream != NULL` while `stream->qos == NULL`.

The handler runs in response to an ASE status notification from the connected
ASCS server. The server can drive the ASE into the QoS Configured state while
the local endpoint is still only Codec Configured — the state dispatcher
explicitly allows the `Codec Configured -> QoS Configured` transition for both
SINK and SOURCE — which is exactly the window in which `stream->qos` is NULL.
When that notification arrives, the function writes the QoS fields starting at
`stream->qos->interval` (i.e. through a NULL pointer plus a field offset),
dereferencing NULL.

On a typical target this faults and brings down the LE Audio client; the bytes
written are taken from the notification payload. Because the values come from
the remote peer rather than local configuration, there is no validation that
`stream->qos` has been established before the writes occur.

(There is also a latent defect on the same lines: `sys_le24_to_cpu(qos->interval)`
returns a value but is passed where `memcpy` expects a source pointer — moot once
the NULL dereference is fixed, but it shows the write path was not exercised in
this state.)

**Expected behavior**

The QoS state handler must not write through `stream->qos` unless it is valid in
the current state. The QoS values received from the peer should be stored in
storage that is guaranteed to exist for the lifetime of the endpoint (the
endpoint's own embedded QoS), so that a QoS Configured notification received
before the stream has been added to a group is handled without dereferencing a
NULL pointer.

**Affected code**

`subsys/bluetooth/audio/bap_unicast_client.c` — `unicast_client_ep_qos_state()`.

### PR DESCRIPTION
**Pull request by Thalley**
Makes the use of QoS more consistent, reduce memory requirements and make it const/read-only where applicable.

Fixes: #110775

### CODE REVIEW

File: subsys/bluetooth/audio/bap_unicast_client.c [hunk 1]
```diff
@@ -1048,40 +1006,40 @@ static void unicast_client_ep_qos_state(struct bt_bap_ep *ep, struct net_buf_sim
...
-	stream->qos->rtn = qos->rtn;
-	stream->qos->latency = sys_le16_to_cpu(qos->latency);
-	(void)memcpy(&stream->qos->pd, sys_le24_to_cpu(qos->pd), sizeof(qos->pd));
+	(void)memcpy(&ep->qos.interval, sys_le24_to_cpu(qos->interval), sizeof(qos->interval));
+	ep->qos.framing = qos->framing;
+	ep->qos.phy = qos->phy;
+	ep->qos.sdu = sys_le16_to_cpu(qos->sdu);
+	ep->qos.rtn = qos->rtn;
+	ep->qos.latency = sys_le16_to_cpu(qos->latency);
+	(void)memcpy(&ep->qos.pd, sys_le24_to_cpu(qos->pd), sizeof(qos->pd));
```
Comment (sjanc) [inline subsys/bluetooth/audio/bap_unicast_client.c]: while not directly related to this commit,  this memcpy() looks a bit odd doesn't it?
shouldn't this be simply   `ep->qos.pd = sys_le24_to_cpu(qos->pd);` ?

**Review by sjanc — DISMISSED** [review]

File: subsys/bluetooth/audio/bap_unicast_client.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/audio/bap_unicast_client.c]: Same with the interval above :s Fixed both

**Review by sjanc — DISMISSED** [review]

**Review by sjanc — APPROVED** [review]

**Review by larsgk — APPROVED** [review]
