### PR TITLE
soc: nrf54h: gpd: use callback to fetch nrfs async result

### LINKED ISSUE #81057: soc: nrf54h: GPD service calls may stall
**Describe the bug**

nRF54H SoC GPD service may stall busy-looping for nRFS result

**To Reproduce**

Enable the service and use `nrf_gpd_request()` on a driver.

**Expected behavior**

Request succeeds

**Impact**

Blocker

**Logs and console output**

N/A

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA or Version used c3466b14d09b1e51b6ca472f3b3654e40cba12d8

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by gmarull**
Busy-waiting for the result of the nrfs service calls can stall, so let's use a callback that flags a semaphore instead. Since the API is supposed to be callable in the context of pre-kernel, fallback to busy-wait on that scenario.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/81057

### CODE REVIEW

File: soc/nordic/nrf54h/gpd/gpd.c [hunk 1]
```diff
@@ -181,11 +208,25 @@ int nrf_gpd_request(uint8_t id)
 		return -EIO;
 	}
 
-	sys_notify_init_spinwait(&client.notify);
+	if (k_is_pre_kernel()) {
+		sys_notify_init_spinwait(&client.notify);
+	} else {
+		sys_notify_init_callback(&client.notify, request_cb);
+		k_mutex_lock(&gpd_mgr->lock, K_FOREVER);
```
Comment (anangl) [inline soc/nordic/nrf54h/gpd/gpd.c:215]: The order should be reversed here, so that the mutex also protects the `client.notify` structure from modification while the request is in progress.

Comment (gmarull) [reply soc/nordic/nrf54h/gpd/gpd.c:215]: client is local to the call, no?

Comment (anangl) [reply soc/nordic/nrf54h/gpd/gpd.c:215]: ah, right, missed that

**Review by anangl — DISMISSED** [review]

File: soc/nordic/nrf54h/gpd/gpd.c [hunk 2]
```diff
@@ -181,11 +208,25 @@ int nrf_gpd_request(uint8_t id)
...
+	}
 
-	onoff_request(&gpd_mgr->mgr, &client);
+	ret = onoff_request(&gpd_mgr->mgr, &client);
+	if (ret < 0) {
+		return ret;
```
Comment (karstenkoenig) [inline soc/nordic/nrf54h/gpd/gpd.c:220]: Failure leaves the mutex locked in the pre_kernel flow

Comment (gmarull) [reply soc/nordic/nrf54h/gpd/gpd.c:220]: good catch

**Review by anangl — DISMISSED** [review]

File: soc/nordic/nrf54h/gpd/gpd.c [hunk 3]
```diff
@@ -181,11 +208,29 @@ int nrf_gpd_request(uint8_t id)
...
+		}
+	} else {
+		(void)k_sem_take(&gpd_mgr->sem, K_FOREVER);
+		ret = gpd_mgr->res;
+	}
 
-	while (sys_notify_fetch_result(&client.notify, &ret) == -EAGAIN) {
+unlock:
+	if (!k_is_pre_kernel()) {
+		k_mutex_unlock(&gpd_mgr->lock);
```
[the remark this answers is not in the document]
Comment (gmarull) [reply soc/nordic/nrf54h/gpd/gpd.c:233]: at this point, you're right

**Review by anangl — APPROVED** [review]

**Review by karstenkoenig — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@gmarull , we are only merging PR's that have an Issue linked to it. If this is needed for 4.0, kindly enter an Issue and link to this PR.

**Comment by gmarull** [comment]
> @gmarull , we are only merging PR's that have an Issue linked to it. If this is needed for 4.0, kindly enter an Issue and link to this PR.

@mmahadevan108 done
