### PR TITLE
drivers: clock_control: Enable LFSTARTED event for nrf5

### LINKED ISSUE #11780: Bluetooth: Mesh: initialisation delay after disabling CONFIG_BT_DEBUG_LOG
It is found that we have to have enable CONFIG_BT_DEBUG_LOG=y
then only Mesh initialization happens within second otherwise it takes around 10+ seconds. This bug has introduced after latest new logging subsystem.

**To Reproduce**
1) flash samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app in nRF52840_pca10056 
   with CONFIG_BT_DEBUG_LOG=n (it is by default disable as per current prj.conf)
2) Provision & configure it using nRFMesh App
3) Reset the Board & see device serial terminal

Here NODE takes 10+ seconds to print "Mesh initialized"

It will be good if we could avoid all type of DEBUG LOGs, so that we could avoid that 1 seconds delay as well as to improve the performance. DEBUG log is important only for development with actual product developers may want to disable it.

### PR DESCRIPTION
**Pull request by nordic-krch**
LFSTARTED interrupt was disabled so it was impossible to put CPU to
sleep and wake up on LF clock being ready. Bluetooth stack was
putting CPU to sleep expecting to be waken up on LFSTARTED event.
As it never occured CPU was waken up seconds later by different event
introducing mulitsecond startup delay.

Fixes #11780.
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Comment by jhedberg** [comment]
This seems to solve the "10 second delay" issue for me, however I still get a strange 2-3 second "hang" in the middle of the log output, usually in the middle of a line. It might e.g. look like the following for 2-3 seconds before completing the full output:
```
***** Booting Zephyr OS zephyr-v1.13.0-2351-g7c83195236 *****
Bluetooth initialized
Advertising successfully started
[00:00:00.017,517] <inf> bt_hci_core.hci_vs_init: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.017,547] <inf> bt_hci_core.hci_vs_init: HW Variant: nRF51x (0x0001)
[00:00:00.017,578] <inf> bt_hci_core.hci_vs_init: Firmware: Standard Bluetooth controller (0x00) Version 1.13 Build 99
[00:00:00.0
```

File: drivers/clock_control/nrf5_power_clock.c [hunk 1]
```diff
@@ -344,8 +345,12 @@ static void _power_clock_isr(void *arg)
 			 */
 			NRF_CLOCK->INTENCLR = CLOCK_INTENCLR_LFCLKSTARTED_Msk;
 
-			/* Start HF Clock */
-			ctto = 1;
+			/* Start HF Clock if LF RC is used. */
+			if (CLOCK_LFCLKSRCCOPY_SRC_RC ==
+			(NRF_CLOCK->LFCLKSRCCOPY & CLOCK_LFCLKSRCCOPY_SRC_Msk)
+			) {
```
Comment (jhedberg) [inline drivers/clock_control/nrf5_power_clock.c]: At least in Linux it is ok to break the 80 character rule when the alternative is hard-to-read code or violating some other coding style (like your `) {` on a separate line). So I'd do the split after == but then put the rest properly on the same line, even though it'll create a coding style warning (we can override that when merging).

Comment (nordic-krch) [reply drivers/clock_control/nrf5_power_clock.c]: ok

**Comment by cvinayak** [comment]
This fixes a regression from my earlier change 23c92100ac5. This PR looks good to me (aside the indentation needing correction). Hence, functional approval is granted from me (i need to be away, others can approve the PR).

**Review by jhedberg — APPROVED** [review]
Combined with #11838 things work quite well for me now. Only issue is the minor coding style thing I pointed out earlier. The "hang" I was seeing is simply due to the hci_ecc.c thread being higher priority and taking up a lot of CPU time.

**Comment by cvinayak** [comment]
Please fix the commit message to: Enable LFSTARTED event for nrf5

File: drivers/clock_control/nrf5_power_clock.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf5_power_clock.c]: done

**Comment by nordic-krch** [comment]
@jhedberg @cvinayak fixed coding and commit message.

**Review by cvinayak — APPROVED** [review]
Functionally LGTM. Style and commit message need changes.

**Review by carlescufi — APPROVED** [review]
