### PR TITLE
Tests kernel arm irq vector table fix

### LINKED ISSUE #13823: tests/kernel/arm_irq_vector_table: test case cannot quit displaying "isr 0 ran!"
**Describe the bug**
Test case did not quit. It kept displaying "isr 0 ran!" until it times out

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=nrf52_pca10040 -DARCH=arm 
3. make
4. make run

**Screenshots or console output**
```
***** delaying boot 1000ms (per build configuration) *****
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
...
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0
```

**Environment (please complete the following information):**
 - OS: fedora29
 - Toolchain : zephyr
 - Commit SHA or Version used: dd5ff3957ceece428e3465dd4e23fb926f61691c

### PR DESCRIPTION
**Pull request by ioannisg**
This PR does some minor refactoring of the arm_irq_vector_table test,
and provides the fixes so the test can successfully run in nRF platforms.

Fixes #13823 .

### CODE REVIEW

**Comment by ioannisg** [comment]
FYI @cinlyooi-intel

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by ioannisg** [comment]
@anangl could you review this? (Possibly, also, try executing the test for nrf52x platforms, to confirm the fix)

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 1]
```diff
@@ -10,6 +10,58 @@
...
+	"POWER_CLOCK_IRQn != 0. Consider rework manual vector table.");
+
+/* The customized solution for nRF52X-based platforms
+ * requires that the RTC1 IRQ line equals 17 and is larger
+ * than the CONFIG_NUM_IRQS.
+ */
+BUILD_ASSERT_MSG(RTC1_IRQn == 17,
+	 "RTC1_IRQn != 17. Consider rework manual vector table.");
+BUILD_ASSERT_MSG(RTC1_IRQn >= CONFIG_NUM_IRQS,
+	 "RTC1_IRQn < NUM_IRQs. Consider rework manual vector table.");
```
Comment (anangl) [inline tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: What is the point in doing this check? `CONFIG_NUM_IRQS` is not used at all when `CONFIG_SOC_SERIES_NRF52X` is defined. Same story for `CONFIG_SOC_SERIES_NRF91X`.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 2]
```diff
@@ -114,25 +156,39 @@ void test_arm_irq_vector_table(void)
...
+ *
+ * The same applies to the CLOCK Control peripheral, which may trigger
+ * IRQs that would need to be serviced.
  */
 void rtc1_nrf_isr(void);
+void _power_clock_isr(void);
 typedef void (*vth)(void); /* Vector Table Handler */
+#if defined(CONFIG_SOC_SERIES_NRF52X)
 vth __irq_vector_table _irq_vector_table[RTC1_IRQn + 1] = {
+	_power_clock_isr,
```
Comment (anangl) [inline tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Maybe it would be good to rename this function to `nrf_power_clock_isr` to emphasize that it is nRF-specific?

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 3]
```diff
@@ -10,6 +10,58 @@
...
+ * requires that the RTC1 IRQ line equals 21 and is larger
+ * than the CONFIG_NUM_IRQS.
+ */
+BUILD_ASSERT_MSG(RTC1_IRQn == 21,
+	 "RTC1_IRQn != 21. Consider rework manual vector table.");
+BUILD_ASSERT_MSG(RTC1_IRQn >= CONFIG_NUM_IRQS,
+	 "RTC1_IRQn < NUM_IRQs. Consider rework manual vector table.");
+
+#undef _ISR_OFFSET
+/* Interrupt lines 8-10 is the first set of consequtive interrupts implemented
```
Comment (anangl) [inline tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: consecutive

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 4]
```diff
@@ -114,25 +156,39 @@ void test_arm_irq_vector_table(void)
...
+#elif defined(CONFIG_SOC_SERIES_NRF91X)
+vth __irq_vector_table _irq_vector_table[RTC1_IRQn + 1] = {
+	0, 0, 0, 0, 0, _power_clock_isr, 0, 0,
+	isr0, isr1, isr2,
+	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
+	rtc1_nrf_isr
+};
+#endif
 #else
 typedef void (*vth)(void); /* Vector Table Handler */
```
Comment (anangl) [inline tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: This definition could be common for all SoCs.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 5]
```diff
@@ -114,25 +156,39 @@ void test_arm_irq_vector_table(void)
 
 }
 
-#if defined(CONFIG_SOC_SERIES_NRF52X)
+#if defined(CONFIG_SOC_SERIES_NRF52X) || defined(CONFIG_SOC_SERIES_NRF91X)
 /* nRF52X-based platforms employ a Hardware RTC peripheral
```
Comment (anangl) [inline tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: nRF52X- and nRF91X-based platforms

**Review by anangl — COMMENTED** [review]
Checked on nRF52832, nRF52840, and nRF9160. Works fine.
Some minor comments added.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 2 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Sure. then we need to rename it in the driver file, too.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 3 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: thanks

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 5 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: right, thanks.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 4 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: OK, fine

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 1 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Right. This macro reflects the number of ISRs we install, in our case, 3.
I see that it is not used throughout the whole test code, e.g. there are some for loops like:
`i = 0; i < 3; i++
`
i.e. the macro is not used. We can either use "3" in this build-time assert, or just try to use CONFIG_NUM_IRQS in all relevant places in the test code.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 5 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Fixing now

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 3 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Fixing now

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 2 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Fixing this now.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 4 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Fixing this now

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 1 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Fixed that: we are, now using CONFIG_NUM_IRQS throughout the test.

**Review by ioannisg — COMMENTED** [review]
Addressed your comments, @anangl , pls, revisit when possible.
Thanks.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 6]
```diff
@@ -75,36 +127,26 @@ void isr2(void)
...
 		      k_sem_take(&sem[1], K_NO_WAIT) ||
 		      k_sem_take(&sem[2], K_NO_WAIT)), NULL);
 
-	for (int ii = 0; ii < 3; ii++) {
+	for (int ii = 0; ii < CONFIG_NUM_IRQS; ii++) {
 #if defined(CONFIG_SOC_TI_LM3S6965_QEMU)
 		/* the QEMU does not simulate the
 		 * STIR register: this is a workaround
 		 */
 		NVIC_SetPendingIRQ(ii);
```
Comment (anangl) [inline tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: `_ISR_OFFSET + ` should be added here as well. Right now it is inconsistent with the loop enabling interrupts and setting their priorities. Although `_ISR_OFFSET` is `0` in this case, but...

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 7]
```diff
@@ -10,7 +10,59 @@
...
+	"POWER_CLOCK_IRQn != 0. Consider rework manual vector table.");
+
+/* The customized solution for nRF52X-based platforms
+ * requires that the RTC1 IRQ line equals 17 and is larger
+ * than the CONFIG_NUM_IRQS.
+ */
+BUILD_ASSERT_MSG(RTC1_IRQn == 17,
+	 "RTC1_IRQn != 17. Consider rework manual vector table.");
+BUILD_ASSERT_MSG(RTC1_IRQn >= CONFIG_NUM_IRQS,
+	 "RTC1_IRQn < NUM_IRQs. Consider rework manual vector table.");
```
Comment (anangl) [inline tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: I still see no point in checking this. You can set `NUM_IRQS` in Kconfig, but reasonable values for this option are <= 3. For higher ones, the test won't work anyway, although they can still pass this check.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 8]
```diff
@@ -10,7 +10,59 @@
...
+#undef _ISR_OFFSET
+/* Interrupt lines 8-10 is the first set of consecutive interrupts implemented
+ * in nRF9160 SOC.
+ */
+#define _ISR_OFFSET 8
+
+#endif /* CONFIG_SOC_SERIES_NRF52X */
+
+
+struct k_sem sem[CONFIG_NUM_IRQS];
```
Comment (anangl) [inline tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: The size of this array must be at least `3`, because of `sem[2]` accesses done below, for instance [here](https://github.com/zephyrproject-rtos/zephyr/pull/13903/files#diff-86ebba4ac9106b75b158163bc8c49e7bR140). Therefore, it cannot be `CONFIG_NUM_IRQS`, it should be kept at `3` as it was.

**Review by anangl — CHANGES_REQUESTED** [review]

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 6 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Added now. Yeah, it is a bit redundant for this platform, but, anyways...

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 8 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Reverted.

File: tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 7 above)
Comment (ioannisg) [reply tests/kernel/arm_irq_vector_table/src/arm_irq_vector_table.c]: Removed. I agree, not much sense on this one.

**Review by ioannisg — COMMENTED** [review]
Addressed your last round's comments, @anangl

**Review by anangl — APPROVED** [review]
