### PR TITLE
posix: timer: use async pthread cancellation

### LINKED ISSUE #67870: posix: timer: should use asynchronous cancellation.
**Describe the bug**

The `test_timer_overrun` test in `tests/posix/common/src/timer.c` was failing quite regularly for `nrf52_bsim` in CI. Ironically, it only did this after parts of `pthread.c` were **fixed**. Namely, respecting deferred vs asynchronous pthread cancelation.

Effectively, by not specifying to cancel the pthread asynchronously, it was allowed to continue running (detached, of course), and then after the sem was cleared in the next test, it tried to jump to `NULL` causing a segfault. Also, it might not be intuitive, but with POSIX threads, asynchronous cancellation means asynchronous w.r.t. cancellation points, and to _synchronously_ w.r.t. the calling thread.

There is some additional setup required for nrf52_bsim to test locally so most tests are skipped unless you go out of your way to set up dependencies.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `nrf52_bsim`
 - What have you tried to diagnose or workaround this issue? CI [here](https://github.com/zephyrproject-rtos/zephyr/actions/runs/7587603835/job/20668392712?pr=67223)
 - Is this a regression? No, but it could have been 😁 

**To Reproduce**
1. Visit [link](https://github.com/zephyrproject-rtos/zephyr/actions/runs/7587603835/job/20668392712?pr=67223)
2. See error

**Expected behavior**
The timer overrun test should succeed without segfaulting.

**Impact**
It's blocking a relatively high bugfix #67223

**Logs and console output**
```shell
d_00: @00:00:34.443970  ===================================================================
d_00: @00:00:34.443970  START - test_timer_overrun

INFO    - /__w/zephyr/zephyr/twister-out/nrf52_bsim/tests/posix/common/portability.posix.common.dynamic_stack/handler.log
INFO    - 685/685 nrf52_bsim                tests/posix/common/portability.posix.common  
```
https://github.com/zephyrproject-rtos/zephyr/actions/runs/7587603835/job/20668392712?pr=67223

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.4
 - Commit: in-branch (#67223) 

**Additional context**

### LINKED ISSUE #67874: posix: timer: unable to create a timer with CLOCK_REALTIME
**Describe the bug**
According to [the spec for `timer_create()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/timer_create.html)

> All implementations shall support a clock_id of `CLOCK_REALTIME`

However, currently, attempting to create a timer using that clock id results in -1 / `EINVAL`.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? Any
 - What have you tried to diagnose or workaround this issue? Looked at code
 - Is this a regression? Techniically no, but the bug was introduced in f603e603bbe60e78f070292b93d56fd98f6f9ab6 (where timers were added)

**To Reproduce**
1. Look at code
2. Compare with spec
3. See error

**Expected behavior**
Should be able to use `CLOCK_REALTIME` with `timer_create()`.

**Impact**
Without this fix, conformance is broken

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.16.4
 - Commit: f603e603bbe60e78f070292b93d56fd98f6f9ab6

**Additional context**

### PR DESCRIPTION
**Pull request by cfriedt**
Previously, Zephyr's POSIX API did not differentiate between deferred and asynchronous pthread cancellation. In fact all pthread cancellation was asynchronous. According to the spec, all pthreads should be created with deferred cancellation by default.

> [!NOTE]  
> `PTHREAD_CANCEL_ASYNCHRONOUS` means cancel asynchronously with respect to _cancellation points_ (synchronously with respect to  `pthread_cancel()`, which is perhaps unintuitive)

The POSIX timer relied on this non-standard convention.
    
Oddly, this change prevents what would have otherwise been a regression that _would have been caused by fixing_ pthread behaviour (in #67223).

We are effectively uncovering bugs which were probably always present in the pthread.c and timer.c implementations going back quite a few years.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/67870
Fixes #67874

Additionally:
* remove non-conformant error condition when using a clock other than `CLOCK_MONOTONIC`
* improve `struct sigevent` and `union sigval` alignment / padding

### CODE REVIEW

**Comment by cfriedt** [comment]
Screenshot 2024-01-20 at 10 14 01 AM

File: lib/posix/timer.c [hunk 1]
```diff
@@ -77,52 +110,89 @@ static void zephyr_timer_interrupt(struct k_timer *ztimer)
...
+		errno = EINVAL;
+		goto free_timer;
 	}
 
 	*timerid = (timer_t)timer;
+	goto out;
 
-	return 0;
+free_timer:
+	k_mem_slab_free(&posix_timer_slab, (void *)&timer);
```
Comment (jukkar) [inline lib/posix/timer.c:192]: Could we place the ret and errno setting here, so something like
```
free_timer:
    errno = ret;
    ret = -1;
    k_mem_slab_free();
```
This way you do not need to set ret and errno multiple times above.

Comment (cfriedt) [reply lib/posix/timer.c:192]: The issue is that assigning it will differ based on whether we are failing from a kernel API or a POSIX API (pthread APIs return `errno` unsigned, while `k_` APIs return `-errno`)

Comment (jukkar) [reply lib/posix/timer.c:192]: Ok, makes sense, never mind then.

**Review by jukkar — APPROVED** [review]

**Comment by cfriedt** [comment]
This is blocking https://github.com/zephyrproject-rtos/zephyr/pull/67223

**Review by ycsin — APPROVED** [review]
