### PR TITLE
drivers: usdhc: Fix bug with multiple writes failing

### LINKED ISSUE #39942: usdhc disk_usdhc_access_write busy fail
**Describe the bug**
disk_usdhc_access_write fail because CDIHB reports busy fail

**To Reproduce**
Test on rt1052, Zephyr V2.7.0 & V2.4.0
1. Test Code
```
	FILE *fp = fopen("/SD:/1", "w+");

	shell_print(shell, "fopen %x", fp);
	if (fp == NULL) {
		return 0;
	}

	ret = fseek(fp, 0, SEEK_END);
	shell_print(shell, "fseek END %d %s", ret, ret?strerror(errno):"");

	ret = ftell(fp);
	shell_print(shell, "file length ftell %d %s", ret, ret?strerror(errno):"");

	ret = fseek(fp, 0, SEEK_SET);
	shell_print(shell, "fseek START %d %s", ret, ret?strerror(errno):"");

	memset(patten_data, 0x5a, PATTEN_LENGTH);
	ret = fwrite(patten_data, 1, PATTEN_LENGTH, fp);
	shell_print(shell, "fwrite %d %s", ret, (ret<=0)?strerror(errno):"");

	memset(patten_data, 0xa5, PATTEN_LENGTH);
	ret = fwrite(patten_data, 1, PATTEN_LENGTH, fp);  // -> Write fail
        shell_print(shell, "fwrite %d %s", ret, (ret<=0)?strerror(errno):"");
```
2. conf
```
CONFIG_DISK_DRIVER_SDMMC=y

CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y

CONFIG_FS_FATFS_CODEPAGE=936
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_LFN_MODE_BSS=y
CONFIG_FS_FATFS_NUM_FILES=20
CONFIG_FS_FATFS_NUM_DIRS=20
```
3. make & run 
4.  fwrite will fail at the second time

**Additional context**
For unknown reasons, calling disk_usdhc_access_write continuously will check that the CDIHB field of the register PRES_STATE is 1 after the previous transfer is completed and before the next transfer. This phenomenon is more likely to occur. May be a SOC issue, and more  experiments are needed to confirm.
Below is a temporary patch:
https://github.com/madmachineio/zephyr/commit/5034b846dca14bade15da651928408df5d6a41d7

### PR DESCRIPTION
**Pull request by danieldegrasse**
The NXP USDHC driver will fail to write to an SD card if `disk_access_write` is called multiple times without a delay. This is due to the USDHC driver neglecting to wait for the SD card to be idle before attempting to send it new commands. 

This PR fixes that bug, and adds a test for disk drivers, in order to verify that multiple reads and writes work correctly.

Fixes #39942

### CODE REVIEW

File: tests/drivers/disk/src/main.c [hunk 1]
```diff
@@ -0,0 +1,219 @@
...
+ * WARNING: This test will overwrite data on any disk utilized. Do not run
+ * this test with an disk that has useful data
+ */
+
+#include <zephyr.h>
+#include <ztest.h>
+#include <storage/disk_access.h>
+#include <device.h>
+
+#if defined(CONFIG_SDMMC_USDHC)
```
Comment (jfischer-no) [inline tests/drivers/disk/src/main.c:17]: Please change it to:
```diff
diff --git a/tests/drivers/disk/src/main.c b/tests/drivers/disk/src/main.c
index b276b649085..f9bcbb7b99e 100644
--- a/tests/drivers/disk/src/main.c
+++ b/tests/drivers/disk/src/main.c
@@ -14,8 +14,10 @@
 #include <storage/disk_access.h>
 #include <device.h>
 
-#if defined(CONFIG_SDMMC_USDHC)
-#define DISK_NAME "SDMMC"
+#if IS_ENABLED(CONFIG_DISK_DRIVER_SDMMC)
+#define DISK_NAME CONFIG_SDMMC_VOLUME_NAME
+#elif IS_ENABLED(CONFIG_DISK_DRIVER_RAM)
+#define DISK_NAME CONFIG_DISK_RAM_VOLUME_NAME
 #else
 #error "No disk device defined, is your board supported?"
 #endif

```

regarding CONFIG_DISK_DRIVER_RAM, I tested your PR on top of https://github.com/zephyrproject-rtos/zephyr/pull/40611

File: tests/drivers/disk/prj.conf [hunk 2]
```diff
@@ -0,0 +1,3 @@
+CONFIG_TEST=y
+CONFIG_ZTEST=y
+CONFIG_DISK_ACCESS=y
```
Comment (jfischer-no) [inline tests/drivers/disk/prj.conf:3]: `+ CONFIG_DISK_DRIVER_SDMMC=y`

File: tests/drivers/disk/src/main.c [hunk 3]
```diff
@@ -0,0 +1,219 @@
...
+
+	/* Verify all 4 sector write sizes work */
+	test_sector_write(scratch_buf[0], scratch_buf[1], SECTOR_COUNT1);
+	test_sector_write(scratch_buf[0], scratch_buf[1], SECTOR_COUNT2);
+	test_sector_write(scratch_buf[0], scratch_buf[1], SECTOR_COUNT3);
+	test_sector_write(scratch_buf[0], scratch_buf[1], SECTOR_COUNT4);
+
+	/* Verify that multiple writes to the same location work */
+	i = 10;
+	while (i--) {
```
Comment (jfischer-no) [inline tests/drivers/disk/src/main.c:202]: `for (int i = 0; i < 10; i++) { ` ?

File: tests/drivers/disk/src/main.c [hunk 4]
```diff
@@ -0,0 +1,219 @@
...
+	test_sector_read(scratch_buf[0], SECTOR_COUNT2);
+	test_sector_read(scratch_buf[0], SECTOR_COUNT3);
+	test_sector_read(scratch_buf[0], SECTOR_COUNT4);
+
+	/* Verify that reading from the same location returns to same data */
+	memset(scratch_buf[0], 0, SECTOR_COUNT1 * disk_sector_size);
+	rc = read_sector(scratch_buf[0], 0, SECTOR_COUNT1);
+	zassert_equal(rc, 0, "Failed to read from disk");
+	i = 10;
+	while (i--) {
```
Comment (jfischer-no) [inline tests/drivers/disk/src/main.c:176]: `for (int i = 0; i < 10; i++) { ` ?

File: tests/drivers/disk/src/main.c [hunk 5]
```diff
@@ -0,0 +1,219 @@
...
+		/* Read from sector, and compare it to the first read */
+		memset(scratch_buf[1], 0xff, SECTOR_COUNT1 * disk_sector_size);
+		rc = read_sector(scratch_buf[1], 0, SECTOR_COUNT1);
+		zassert_equal(rc, 0, "Failed to read from disk at same sector location");
+		zassert_equal(memcmp(scratch_buf[1], scratch_buf[0],
```
Comment (jfischer-no) [inline tests/drivers/disk/src/main.c:181]:
```diff
diff --git a/tests/drivers/disk/src/main.c b/tests/drivers/disk/src/main.c
index b276b649085..c76af9cde5d 100644
--- a/tests/drivers/disk/src/main.c
+++ b/tests/drivers/disk/src/main.c
@@ -178,9 +178,9 @@ static void test_read(void)
                memset(scratch_buf[1], 0xff, SECTOR_COUNT1 * disk_sector_size);
                rc = read_sector(scratch_buf[1], 0, SECTOR_COUNT1);
                zassert_equal(rc, 0, "Failed to read from disk at same sector location");
-               zassert_equal(memcmp(scratch_buf[1], scratch_buf[0],
-                               SECTOR_COUNT1 * disk_sector_size), 0,
-                               "Multiple reads from same disk location did not return same data");
+               zassert_mem_equal(scratch_buf[1], scratch_buf[0],
+                                 SECTOR_COUNT1 * disk_sector_size,
+                                 "Multiple reads mismatch");
        }
 }
```

Please keep it short.

File: tests/drivers/disk/testcase.yaml [hunk 6]
```diff
@@ -0,0 +1,8 @@
+tests:
+  drivers.disk.usdhc:
```
Comment (jfischer-no) [inline tests/drivers/disk/testcase.yaml:2]: I guess `platform_allow` can be replaced by `filter: CONFIG_SDMMC_USDHC`

with https://github.com/zephyrproject-rtos/zephyr/pull/40611, you can add a test case for any platform:
```
  drivers.disk.ram:
    min_ram: 128
    tags: disk
    extra_configs:
        - CONFIG_DISK_DRIVER_RAM=y
...
```

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: tests/drivers/disk/prj.conf (hunk 2 above)
Comment (danieldegrasse) [reply tests/drivers/disk/prj.conf:3]: Should `CONFIG_DISK_DRIVER_SDMMC` be selected unconditionally, even when testing a RAM disk?

File: tests/drivers/disk/testcase.yaml (hunk 6 above)
Comment (danieldegrasse) [reply tests/drivers/disk/testcase.yaml:2]: Added this test case. I'm assuming #40611 is required to make this test pass, since it checks for out of bounds r/w?

File: tests/drivers/disk/prj.conf (hunk 2 above)
Comment (jfischer-no) [reply tests/drivers/disk/prj.conf:3]: I think one should be enabled per default, you PR is targeting SDMMC driver, I can add test case for ramdisk in #40611

File: tests/drivers/disk/src/main.c (hunk 5 above)
Comment (jfischer-no) [reply tests/drivers/disk/src/main.c:182]: you can use `zassert_mem_equal` instead of zassert_equal(memcmp())

```
+               zassert_mem_equal(scratch_buf[1], scratch_buf[0],
+                                 SECTOR_COUNT1 * disk_sector_size,
+                                 "Multiple reads mismatch");
```

Comment (danieldegrasse) [reply tests/drivers/disk/src/main.c]: fixed, sorry I missed that change before.

File: tests/drivers/disk/prj.conf (hunk 2 above)
Comment (danieldegrasse) [reply tests/drivers/disk/prj.conf:3]: Sounds good. `CONFIG_DISK_DRIVER_SDMMC` should be selected for the test in the latest push

File: tests/drivers/disk/testcase.yaml (hunk 6 above)
Comment (danieldegrasse) [reply tests/drivers/disk/testcase.yaml:2]: thanks for the heads up, updated the testcase.yaml file to use `filter: CONFIG_SDMMC_USDHC`

**Review by jfischer-no — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
