### PR TITLE
drivers: clock_control: nrf driver reimplementation

### LINKED ISSUE #12114: assertion using nRF5 power clock with BLE and nRF5 temp sensor
**Describe the bug**
When nRF5 temperature sensor is used during BLE communication, assertion is hit in `temp_nrf5_sample_fetch()` with `-EBUSY` error (_temp_nrf5.c_ line 54). Assertion is hit during `clock_control_off()` since both BLE controller and nRF Temperature uses the same nRF power clock. 

**To Reproduce**
1. Create sample BLE peripheral application with nRF temperature sensor. 
2. Poll the temperature sensor every 2 seconds.
3. Connect the sample BLE application with any peer
4. At some point assertion is hit as explained above.

**Expected behavior**
Assertion should not occur or if it occurs API documentation can give more information  

**Impact**
Even if this issue is minor this affects just the Debug build of our application and release build works fine. Hopefully there is no problem using BLE along with nRF temperature sensor in parallel.

**Environment (please complete the following information):**
 - Zephyr
 - nRF52840 board

### PR DESCRIPTION
**Pull request by nordic-krch**
Clock_control has been re-implemented to support new clock control API and calibration algorithm which optionally uses temperature sensor and skips calibration on no temperature change.

- Added new API implementation
- Added calibration algorithm (calibration support extracted to separate file)
- Added test suite
- Updated usage of clock _control API in nordic drivers, removed hacky usage of subsys parameter.

-----------
Fixes #12114

### CODE REVIEW

File: drivers/clock_control/nrf_power_clock.c [hunk 1]
```diff
@@ -12,269 +12,308 @@
...
+#define INT_MASK \
+	(NRF_CLOCK_INT_HF_STARTED_MASK | NRF_CLOCK_INT_LF_STARTED_MASK \
+	COND_CODE_1(CONFIG_USB_NRF52840, \
+		    (|NRF_POWER_INT_USBDETECTED_MASK | \
+		      NRF_POWER_INT_USBREMOVED_MASK | \
+		      NRF_POWER_INT_USBPWRRDY_MASK), ()))
 
-static int m16src_start(struct device *dev, clock_control_subsys_t sub_system)
+/* Function returns current interrupt priority or 0xff if in thread mode */
+static int z_arch_irq_current_prio(void)
```
Comment (aescolar) [inline drivers/clock_control/nrf_power_clock.c]: This function would seem quite out of place here. Shouldnt it be in arch/arm/core/irq_mange.c  or so?

**Review by aescolar — DISMISSED** [review]

File: drivers/clock_control/nrf_power_clock.c (hunk 1 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: yes, that was my forgotten intention. See #17301.

File: drivers/clock_control/nrf_power_clock.c [hunk 2]
```diff
@@ -9,272 +9,311 @@
...
+#define WRN(dev, ...) CLOCK_LOG(WRN, dev, __VA_ARGS__)
+#define INF(dev, ...) CLOCK_LOG(INF, dev, __VA_ARGS__)
+#define DBG(dev, ...) CLOCK_LOG(DBG, dev, __VA_ARGS__)
+
+/* returns true if clock stopping must be deferred due to active calibration. */
+typedef void (*nrf_clock_stop_handler_t)(struct device *dev);
+
+/* Clock instance structure */
+struct nrf_clock_control {
+	atomic_t ref;		/* Users counter */
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: Why is it defined as `atomic_t` when atomic API is not used for this field?

**Review by anangl — CHANGES_REQUESTED** [review]
Just some initial comments. I'll need some more time to dive into `nrf_power_clock.c`.

**Comment by aescolar** [comment]
@nordic-krch In https://github.com/aescolar/zephyr/tree/clock_control_calibration_fix  you have this branch with a couple of updates for simulation and rebased on top of #17301 . With it the nrf52_bsim works nicely

File: drivers/clock_control/nrf_clock_calibration.c [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+ */
+#include <sensor.h>
+#include <drivers/clock_control/nrf_clock_control.h>
+#include <drivers/clock_control.h>
+#include <nrf_clock.h>
+#include <logging/log.h>
+
+LOG_MODULE_DECLARE(clock_control, CONFIG_CLOCK_CONTROL_LOG_LEVEL);
+
+#define TEMP_SENSOR_NAME COND_CODE_1(TEMP_NRF5, (CONFIG_TEMP_NRF5_NAME), (NULL))
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: fixed

File: drivers/clock_control/nrf_clock_calibration.c [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+static void cal_hf_on_callback(struct device *dev, void *user_data);
+static struct clock_control_async_data cal_hf_on_data = {
+	.cb = cal_hf_on_callback
+};
+
+static struct device *hfclk_dev; /* Handler to hfclk device. */
+static struct device *temp_sensor; /* Handler to temperature sensor device. */
+
+static void measure_temperature(struct k_work *work);
+struct k_work temp_measure_work = {
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: fixed

File: drivers/clock_control/nrf_clock_calibration.c [hunk 5]
```diff
@@ -0,0 +1,191 @@
...
+
+/* Function reads from temperature sensor and converts to float. */
+static float get_temperature(void)
+{
+	struct sensor_value sensor_val;
+
+	sensor_sample_fetch(temp_sensor);
+	sensor_channel_get(temp_sensor, SENSOR_CHAN_DIE_TEMP, &sensor_val);
+
+	return sensor_value_to_float(&sensor_val);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: changed to work in 0,25 degree units. Also modified kconfig option to use same units which allows to chose fractional temperature diff that will trigger calibration.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 6]
```diff
@@ -0,0 +1,191 @@
...
+
+	if (cal_state == CAL_HFCLK_REQ) {
+		if ((CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP == 0) ||
+		    (IS_ENABLED(CONFIG_MULTITHREADING) == false) ||
+		    calib_skip_cnt == 0) {
+			start_calibration();
+		} else {
+			cal_state = CAL_TEMP_REQ;
+			k_work_submit_to_queue(&k_sys_work_q,
+					       &temp_measure_work);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: done

File: drivers/timer/nrf_rtc_timer.c [hunk 7]
```diff
@@ -85,7 +85,7 @@ int z_clock_driver_init(struct device *device)
 		return -1;
 	}
 
-	clock_control_on(clock, (void *)CLOCK_CONTROL_NRF_K32SRC);
+	clock_control_on(clock, 0);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/timer/nrf_rtc_timer.c]: done

File: ext/hal/nordic/drivers/nrf_radio_802154/platform/clock/nrf_802154_clock_zephyr.c [hunk 8]
```diff
@@ -63,8 +63,10 @@ void nrf_802154_clock_hfclk_start(void)
     clk_m16 = device_get_binding(DT_NORDIC_NRF_CLOCK_0_LABEL "_16M");
     __ASSERT_NO_MSG(clk_m16 != NULL);
 
-    clock_control_on(clk_m16, (void *)1); /* Blocking call. */
-
+    clock_control_on(clk_m16, NULL);
+    /* Block until clock is ready. */
+    while (clock_control_get_status(clk_m16, NULL) !=
+		CLOCK_CONTROL_STATUS_ON) {}
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply ext/hal/nordic/drivers/nrf_radio_802154/platform/clock/nrf_802154_clock_zephyr.c]: done

File: drivers/sensor/nrf5/temp_nrf5.c [hunk 9]
```diff
@@ -27,29 +27,32 @@ struct temp_nrf5_data {
...
 	if (chan != SENSOR_CHAN_ALL && chan != SENSOR_CHAN_DIE_TEMP) {
 		return -ENOTSUP;
 	}
 
-	/* The clock driver for nrf51 currently overloads the
-	 * subsystem parameter with a flag to indicate whether or not
-	 * it should block.
-	 */
-	r = clock_control_on(data->hfclk_dev, (void *)1);
+	r = clock_control_async_on(data->hfclk_dev, 0, &clk_data);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/sensor/nrf5/temp_nrf5.c]: done

File: drivers/sensor/nrf5/temp_nrf5.c [hunk 10]
```diff
@@ -27,29 +27,32 @@ struct temp_nrf5_data {
 	struct device *hfclk_dev;
 };
 
+void hfclk_on_callback(struct device *dev, void *user_data)
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/sensor/nrf5/temp_nrf5.c]: done

File: drivers/clock_control/nrf_power_clock.c [hunk 11]
```diff
@@ -9,272 +9,311 @@
...
 #include <sys/atomic.h>
 #include <device.h>
-#include <drivers/clock_control.h>
 #include <sys/__assert.h>
+#include <drivers/clock_control.h>
+#include <drivers/clock_control/nrf_clock_control.h>
 #include <nrf_clock.h>
-#if defined(CONFIG_USB) && defined(CONFIG_SOC_NRF52840)
+#include <logging/log.h>
+#if defined(CONFIG_USB_NRF52840) || NRF_POWER_HAS_POFCON
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: now nrf_power.h is always included.

File: drivers/clock_control/nrf_power_clock.c [hunk 12]
```diff
@@ -9,272 +9,311 @@
...
+};
 
-	/* If the clock is already started then just increment refcount.
-	 * If the start and stop don't happen in pairs, a rollover will
-	 * be caught and in that case system should assert.
-	 */
+#define INT_MASK \
+	(NRF_CLOCK_INT_HF_STARTED_MASK | NRF_CLOCK_INT_LF_STARTED_MASK \
+	COND_CODE_1(CONFIG_USB_NRF52840, \
+		    (|NRF_POWER_INT_USBDETECTED_MASK | \
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: drivers/clock_control/nrf_power_clock.c (hunk 2 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: changed to `s32_t`

**Review by anangl — CHANGES_REQUESTED** [review]

File: drivers/clock_control/nrf_power_clock.c [hunk 13]
```diff
@@ -9,272 +9,296 @@
...
-static int m16src_start(struct device *dev, clock_control_subsys_t sub_system)
-{
-	bool blocking;
-	u32_t imask;
-	u32_t stat;
+/* Clock instance static configuration */
+struct nrf_clock_control_config {
+	u32_t start_tsk;	/* Clock start task */
+	u32_t started_evt;	/* Clock started event */
+	u32_t stop_tsk;		/* Clock stop task */
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: Why not use dedicated types for these fields, i.e. `nrf_clock_task_t` and `nrf_clock_event_t`? These are offsets, so you would also save some memory here (if the compiler is allowed to use short enums). Place the `stop_handler` first to avoid padding in this case.

File: drivers/clock_control/nrf_power_clock.c [hunk 14]
```diff
@@ -9,272 +9,296 @@
...
+		async_data = CONTAINER_OF(node,
+				struct clock_control_async_data, node);
+		async_data->cb(dev, async_data->user_data);
+		node = sys_slist_get(&data->list);
 	}
+}
 
-	NRF_CLOCK->EVENTS_LFCLKSTARTED = 0;
+#if defined(CONFIG_USB_NRF52840) || NRF_POWER_HAS_POFCON
+static bool power_event_check_and_clean(u32_t evt, u32_t intmask)
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: By using `nrf_clock_event_t` for `evt` you could prevent such mistakes as the one with `nrf_clock_event_clear` below.

File: drivers/clock_control/nrf_power_clock.c [hunk 15]
```diff
@@ -9,272 +9,296 @@
...
 
-	m16src_grd = 1U;
+#if 0
+	__ASSERT_NO_MSG(z_arm_irq_current_prio() >
+			NVIC_GetPriority(nrfx_get_irq_number(NRF_CLOCK)));
+#endif
 
-	irq_unlock(imask);
+	if (data->ref > 0) {
+		return data->started ?
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: That's true but on the other hand one can question that result of get status is always volatile if someone that did not requested clock is checking it's state. Main purpose for having that function is to block until clock is ready. In that case if one requested clock then it will never be in `OFF` state.

I wouldn't like to complicate this function only to satisfy use case which will rather never occur. Maybe we should clarify `clock_control.h` the use case. Maybe we should even replace this function with something like `clock_control_wfo()` (wait for on)?

File: drivers/clock_control/nrf_power_clock.c [hunk 16]
```diff
@@ -9,272 +9,296 @@
...
+	int err = 0;
 
-		intenset = NRF_CLOCK->INTENSET;
-		nrf_clock_int_enable(NRF_CLOCK_INT_HF_STARTED_MASK);
+	data->ref--;
 
-		nrf_clock_task_trigger(NRF_CLOCK_TASK_HFCLKSTART);
+	if (data->ref == 0) {
+		DBG(dev, "Stopping");
+		sys_slist_init(&data->list);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: if clock was stopped before started then we need to clear the list. otherwise after starting again list will not be empty and unwanted callback may be called on next clock start.

[the remark this answers is not in the document]
Comment (anangl) [reply drivers/clock_control/nrf_power_clock.c]: > if clock was stopped before started then we need to clear the list

Right. I haven't thought about this case. It's not that obvious, so perhaps a short comment here would be a good thing?

File: drivers/clock_control/nrf_power_clock.c [hunk 17]
```diff
@@ -9,272 +9,311 @@
...
+#if defined(CONFIG_USB_NRF52840) || NRF_POWER_HAS_POFCON
+static bool power_event_check_and_clean(u32_t evt, u32_t intmask)
+{
+	bool ret = nrf_power_event_check(evt) &&
+			nrf_power_int_enable_check(intmask);
 
-		/* Set the Calibration Timer Initial Value */
-		NRF_CLOCK->CTIV = 16;	/* 4s in 0.25s units */
+	if (ret) {
+		nrf_clock_event_clear(evt);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: drivers/clock_control/nrf_power_clock.c [hunk 18]
```diff
@@ -286,197 +325,33 @@ static inline void power_event_cb(nrf_power_event_t event)
...
+	ARG_UNUSED(arg);
 
-	if (ctto) {
-		int err;
+	pof_isr();
 
-		NRF_CLOCK->EVENTS_CTTO = 0;
+	if (clock_event_check_and_clean(NRF_CLOCK_EVENT_HFCLKSTARTED,
+					NRF_CLOCK_INT_HF_STARTED_MASK)) {
+		struct device *hfclk_dev = &DEVICE_NAME_GET(clock_nrf5_m16src);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: drivers/clock_control/nrf_power_clock.c [hunk 19]
```diff
@@ -286,197 +310,33 @@ static inline void power_event_cb(nrf_power_event_t event)
...
-	}
-#endif /* NRF_CLOCK_HAS_CALIBRATION */
-
-#if defined(CONFIG_USB) && defined(CONFIG_SOC_NRF52840)
-	if (usb_detected) {
-		nrf_power_event_clear(NRF_POWER_EVENT_USBDETECTED);
-		power_event_cb(NRF_POWER_EVENT_USBDETECTED);
+	if (clock_event_check_and_clean(NRF_CLOCK_EVENT_LFCLKSTARTED,
+					NRF_CLOCK_INT_LF_STARTED_MASK)) {
+		clkstarted_handle(&DEVICE_NAME_GET(clock_nrf5_k32src));
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: drivers/clock_control/nrf_power_clock.c [hunk 20]
```diff
@@ -9,272 +9,296 @@
 #include <errno.h>
 #include <sys/atomic.h>
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: includes cleaned up.

File: drivers/clock_control/nrf_power_clock.c [hunk 21]
```diff
@@ -9,272 +9,296 @@
...
+	return ret;
+}
+
+static enum clock_control_status get_status(struct device *dev,
+					    clock_control_subsys_t sys)
+{
+	struct nrf_clock_control *data = dev->driver_data;
 
-	m16src_grd = 1U;
+#if 0
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: removed that temporarily

File: drivers/clock_control/nrf_clock_calibration.c [hunk 22]
```diff
@@ -0,0 +1,190 @@
...
+static void cal_hf_on_callback(struct device *dev, void *user_data);
+static struct clock_control_async_data cal_hf_on_data = {
+	.cb = cal_hf_on_callback
+};
+
+static struct device *hfclk_dev; /* Handler to hfclk device. */
+static struct device *temp_sensor; /* Handler to temperature sensor device. */
+
+static void measure_temperature(struct k_work *work);
+K_WORK_DEFINE(temp_measure_work, measure_temperature);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: added

File: drivers/clock_control/nrf_power_clock.c [hunk 23]
```diff
@@ -9,272 +9,296 @@
...
+}
 
-	ARG_UNUSED(sub_system);
+static void nrf_power_clock_isr(void *arg);
 
-	/* Test for started resource, if so, decrement reference and acquire
-	 * resource guard.
+static int clock_control_init(struct device *hfclk_dev)
+{
+	/* TODO: Initialization will be called twice, once for 32KHz and then
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: removed.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 24]
```diff
@@ -0,0 +1,190 @@
...
+					NRF_CLOCK_INT_DONE_MASK) == false) {
+		}
+	}
+
+	irq_unlock(key);
+}
+
+void nrf_clock_control_calibration_init(struct device *dev)
+{
+	/* errata 56 */
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: added errata description. in fact number here was wrong. fixed that.

File: drivers/clock_control/nrf_power_clock.c [hunk 25]
```diff
@@ -9,272 +9,296 @@
...
-
-	irq_unlock(imask);
-
-	/* re-entrancy and mult-context safe, and reference count is zero, */
-
-	nrf_clock_task_trigger(NRF_CLOCK_TASK_HFCLKSTOP);
-
-	/* release resource guard */
-	m16src_grd = 0U;
+	nrf_clock_int_enable(INT_MASK);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: drivers/clock_control/nrf_power_clock.c [hunk 26]
```diff
@@ -9,272 +9,296 @@
...
+#define DBG(dev, ...) CLOCK_LOG(DBG, dev, __VA_ARGS__)
+
+/* returns true if clock stopping must be deferred due to active calibration. */
+typedef void (*nrf_clock_stop_handler_t)(struct device *dev);
+
+/* Clock instance structure */
+struct nrf_clock_control {
+	s32_t ref;		/* Users counter */
+	sys_slist_t list;	/* List of users requesting callback */
+	bool started;		/* When set clock is started */
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: rephrased.

File: drivers/clock_control/nrf_power_clock.c [hunk 27]
```diff
@@ -9,272 +9,296 @@
...
+			     struct clock_control_async_data *data)
+{
+	const struct nrf_clock_control_config *config =
+						dev->config->config_info;
+	struct nrf_clock_control *clk_data = dev->driver_data;
+	int key = irq_lock();
+
+	switch (get_status(dev, sub_system)) {
+	case CLOCK_CONTROL_STATUS_ON:
+		irq_unlock(key);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: fixed.

File: drivers/clock_control/nrf_power_clock.c [hunk 28]
```diff
@@ -9,272 +9,296 @@
...
+		nrf_clock_event_clear(config->started_evt);
+		nrf_clock_task_trigger(config->start_tsk);
+		DBG(dev, "Triggered start task");
+		/* fall through */
+	case CLOCK_CONTROL_STATUS_STARTING:
+		/* if node is in the list it means that it is scheduled for
+		 * the second time.
+		 */
+		if (data) {
+			if (data->node.next) {
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: that was risky. added function for checking if element is in the list. not relying on that anymore.

File: drivers/clock_control/nrf_power_clock.c [hunk 29]
```diff
@@ -9,272 +9,296 @@
...
+{
+	const struct nrf_clock_control_config *config =
+						dev->config->config_info;
+	struct nrf_clock_control *clk_data = dev->driver_data;
+	int key = irq_lock();
+
+	switch (get_status(dev, sub_system)) {
+	case CLOCK_CONTROL_STATUS_ON:
+		irq_unlock(key);
+		if (data && data->cb) {
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: added assert to check that. In general `data->cb` cannot be NULL, if user does not want callback then `data` is NULL. If `data != NULL` then `data->cb != NULL`, too.

File: drivers/clock_control/nrf_power_clock.c (hunk 13 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: changed.

File: drivers/clock_control/nrf_power_clock.c (hunk 14 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: ack

File: drivers/clock_control/nrf_power_clock.c [hunk 30]
```diff
@@ -1,280 +1,327 @@
...
+			COND_CODE_0(NUM_VA_ARGS_LESS_1(__VA_ARGS__),\
+					(), (, GET_ARGS_LESS_1(__VA_ARGS__))))
+#define ERR(dev, ...) CLOCK_LOG(ERR, dev, __VA_ARGS__)
+#define WRN(dev, ...) CLOCK_LOG(WRN, dev, __VA_ARGS__)
+#define INF(dev, ...) CLOCK_LOG(INF, dev, __VA_ARGS__)
+#define DBG(dev, ...) CLOCK_LOG(DBG, dev, __VA_ARGS__)
+
+/* returns true if clock stopping or starting can be performed. If false then
+ * start/stop will be deferred and performed later on by handler owner.*/
+typedef bool (*nrf_clock_stop_handler_t)(struct device *dev);
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: The name of this type is no longer adequate, now that it is used also for checking if starting can be performed.

File: drivers/clock_control/nrf_power_clock.c [hunk 31]
```diff
@@ -1,280 +1,327 @@
...
+/* Clock instance static configuration */
+struct nrf_clock_control_config {
+	nrf_clock_stop_handler_t start_handler; /* Called before start */
+	nrf_clock_stop_handler_t stop_handler; /* Called before stop */
+	nrf_clock_task_t start_tsk;	/* Clock start task */
+	nrf_clock_event_t started_evt;	/* Clock started event */
+	nrf_clock_task_t stop_tsk;	/* Clock stop task */
+};
+
+#define INT_MASK \
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: No longer used.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 32]
```diff
@@ -0,0 +1,271 @@
...
+		cal_state = CAL_ACTIVE_OFF;
+		ret = false;
+		LOG_INF("Stop when calibration is active");
+	} else {
+		cal_state = CAL_OFF;
+	}
+
+	irq_unlock(key);
+
+	return false;
```
Comment (anangl) [inline drivers/clock_control/nrf_clock_calibration.c]: Is this really supposed to always return `false`?

File: drivers/clock_control/nrf_power_clock.c [hunk 33]
```diff
@@ -1,280 +1,327 @@
...
-static int m16src_stop(struct device *dev, clock_control_subsys_t sub_system)
-{
-	u32_t imask;
+			do_start =  (config->start_handler) ?
+					config->start_handler(dev) : true;
 
-	ARG_UNUSED(sub_system);
+			if (do_start) {
+				nrf_clock_event_clear(config->started_evt);
+				nrf_clock_task_trigger(config->start_tsk);
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: Where will this task be triggered in case `start_handler` returns `false`?

File: drivers/clock_control/nrf_power_clock.c (hunk 15 above)
[the remark this answers is not in the document]
Comment (anangl) [reply drivers/clock_control/nrf_power_clock.c]: What about changing it to:
```
if (data->started) {
	return CLOCK_CONTROL_STATUS_ON;
}
if (data->ref > 0) {
	return CLOCK_CONTROL_STATUS_STARTING;
}

return CLOCK_CONTROL_STATUS_OFF;
```

File: include/drivers/clock_control/nrf_clock_control.h [hunk 34]
```diff
@@ -61,4 +59,46 @@
...
+
+/**
+ * @brief Calibration interrupts handler
+ *
+ * Must be called from clock interrupt context.
+ */
+void nrf_clock_control_calibration_isr(void);
+
+/**
+ * @brief Stop calibration.
```
Comment (anangl) [inline include/drivers/clock_control/nrf_clock_control.h]: Invalid description.

File: include/drivers/clock_control/nrf_clock_control.h [hunk 35]
```diff
@@ -61,4 +59,46 @@
...
+ *
+ * Function called when LFCLK RC clock is being started. It starts calibration
```
Comment (anangl) [inline include/drivers/clock_control/nrf_clock_control.h]: ~~It starts calibration~~

File: include/drivers/clock_control/nrf_clock_control.h [hunk 36]
```diff
@@ -61,4 +59,46 @@
...
+ *
+ * @param dev LFCLK device.
+ *
+ * @retval true if clock can be started.
+ * @retval false if clock was not stopped due to ongoing calibration and don't
+ *	   need to be started again because it is still on.
```
Comment (anangl) [inline include/drivers/clock_control/nrf_clock_control.h]: Currently this is not entirely true. The function returns `false` when `cal_state == CAL_ACTIVE_OFF` and this means that the calibration is ongoing but after it completes, the clock will be stopped.

File: drivers/clock_control/nrf_power_clock.c [hunk 37]
```diff
@@ -1,280 +1,327 @@
...
+{
+	return clock_async_start(dev, sub_system, NULL);
+}
 
-	/* re-entrancy and mult-context safe, and reference count is zero, */
+static void nrf_power_clock_isr(void *arg);
 
-	nrf_clock_task_trigger(NRF_CLOCK_TASK_HFCLKSTOP);
+static int clock_control_init(struct device *hfclk_dev)
+{
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: `data->list` should be initialized here (and in `k32_dummy_init`).

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c [hunk 38]
```diff
@@ -0,0 +1,318 @@
...
+ * Test checks that callbacks are called after clock is started.
+ */
+static void clock_on_callback1(struct device *dev, void *user_data)
+{
+	bool *executed = (bool *)user_data;
+
+	*executed = true;
+}
+
+static void clock_on_callback2(struct device *dev, void *user_data)
```
Comment (anangl) [inline tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: No need for a second callback function when you are using different user data.

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c [hunk 39]
```diff
@@ -0,0 +1,318 @@
...
+		.cb = clock_on_callback1,
+		.user_data = &executed1
+	};
+
+	status = clock_control_get_status(dev, NULL);
+	zassert_equal(CLOCK_CONTROL_STATUS_OFF, status,
+			"%s: Unexpected status (%d)", dev_name, status);
+
+	/* lock to prevent clock interrupt for fast starting clocks.*/
+	key = irq_lock();
```
Comment (anangl) [inline tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: This will only prevent handling of the interrupt. If a clock starts fast enough, it can still generate the interrupt before `clock_control_off` is called. In such case the interrupt will be handled (and the callback executed) right after `irq_unlock`.

File: drivers/clock_control/nrf_power_clock.c (hunk 33 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: if start_handler returns false then it means that starting clock will be handled by module that provided handler. In that particular case start handler will returns false when it didn't yet stop the clock because calibration was ongoing. It will not call start because lfclk was not yet stopped (`CAL_ACTIVE_OFF` state).

File: drivers/clock_control/nrf_power_clock.c [hunk 40]
```diff
@@ -1,280 +1,327 @@
...
 	}
 
-	k32src_initialized = 1U;
+	nrf_clock_int_enable((NRF_CLOCK_INT_HF_STARTED_MASK |
+			      NRF_CLOCK_INT_LF_STARTED_MASK |
+			      COND_CODE_1(CONFIG_USB_NRF52840,
+				(NRF_POWER_INT_USBDETECTED_MASK |
+				NRF_POWER_INT_USBREMOVED_MASK |
+				NRF_POWER_INT_USBPWRRDY_MASK),
+				(0))));
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: Wouldn't such formatting:
```
	nrf_clock_int_enable(
		NRF_CLOCK_INT_HF_STARTED_MASK |
		NRF_CLOCK_INT_LF_STARTED_MASK |
		COND_CODE_1(CONFIG_USB_NRF52840,
			(NRF_POWER_INT_USBDETECTED_MASK |
			 NRF_POWER_INT_USBREMOVED_MASK |
			 NRF_POWER_INT_USBPWRRDY_MASK),
			(0)));
```
be a bit more readable?

File: drivers/clock_control/nrf_clock_calibration.c [hunk 41]
```diff
@@ -0,0 +1,258 @@
...
+	CAL_OFF,
+	CAL_IDLE,	/* Calibration timer active, waiting for expiration. */
+	CAL_HFCLK_REQ,	/* HFCLK XTAL requested. */
+	CAL_TEMP_REQ,	/* Temperature measurement requested. */
+	CAL_ACTIVE,	/* Ongoing calibration. */
+	CAL_ACTIVE_OFF /* Ongoing calibration, off requested. */
+};
+
+static enum nrf_cal_state cal_state; /* Calibration state. */
+static float prev_temperature; /* Previous temperature measurement. */
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: done

File: drivers/clock_control/nrf_clock_calibration.c [hunk 42]
```diff
@@ -0,0 +1,258 @@
...
+}
+
+/* Convert sensor value to 0.25'C units. */
+static inline s32_t sensor_value_to_temp_unit(struct sensor_value *val)
+{
+	return 4 * val->val1 + val->val2 / 250000;
+}
+
+/* Function reads from temperature sensor and converts to float. */
+static float get_temperature(void)
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: strange that there was no warning. fixed now.

File: drivers/clock_control/nrf_power_clock.c [hunk 43]
```diff
@@ -1,280 +1,327 @@
...
+	bool started;		/* Indicated that clock is started */
+};
 
-static int m16src_start(struct device *dev, clock_control_subsys_t sub_system)
+/* Clock instance static configuration */
+struct nrf_clock_control_config {
+	nrf_clock_stop_handler_t start_handler; /* Called before start */
+	nrf_clock_stop_handler_t stop_handler; /* Called before stop */
+	nrf_clock_task_t start_tsk;	/* Clock start task */
+	nrf_clock_event_t started_evt;	/* Clock started event */
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: there is this case when you are stopping the clock before it got started. Then during stopping clock may get started and started event is set. If it is not cleared after calling stop task then after leaving stop procedure interrupt will be generated as if clock started but it is already stopped.

One of the test case covers that so when i removed event clearing test was failing. Another way to workaround that would be to check actual register status in the interrupt. I think that clearing that event is simpler solution.

File: drivers/clock_control/nrf_power_clock.c (hunk 30 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: renamed to `nrf_clock_handler_t`

File: drivers/clock_control/nrf_power_clock.c (hunk 31 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: removed

File: drivers/clock_control/nrf_clock_calibration.c (hunk 32 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: no, fixed now.

File: drivers/clock_control/Kconfig.nrf [hunk 44]
```diff
@@ -47,14 +47,45 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+config CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION
+	bool
+	depends on !SOC_SERIES_NRF91X
+	default y if CLOCK_CONTROL_NRF_K32SRC_RC
+
+if CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION
+
+config CLOCK_CONTROL_NRF_CALIBRATION_PERIOD
+	int "Calibration opportunity period (in 250ms units)"
+	default 1
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/Kconfig.nrf]: done

File: drivers/clock_control/Kconfig.nrf [hunk 45]
```diff
@@ -47,14 +47,45 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+	help
+	  Periodically, temperature is measured. If temperature change exceeded
+	  CLOCK_CONTROL_NRF_CALIBRATION_TEMP_DIFF then calibration is started
+	  else it is skipped.
+
+config CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP
+	int "Maximum number of calibration skips"
+	default 4
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/Kconfig.nrf]: done

File: include/drivers/clock_control/nrf_clock_control.h (hunk 34 above)
Comment (nordic-krch) [reply include/drivers/clock_control/nrf_clock_control.h]: fixed

File: include/drivers/clock_control/nrf_clock_control.h (hunk 36 above)
Comment (nordic-krch) [reply include/drivers/clock_control/nrf_clock_control.h]: it's actually true (at least now). If before calibration is done, calibration state will be changed to `idle` then in calibration done event clock will not be stopped.

That was initial intention but due to bug in the function it was misbehaving.

File: drivers/clock_control/nrf_power_clock.c (hunk 37 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: drivers/clock_control/nrf_power_clock.c (hunk 40 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: done

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 39 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: that's why clearing started event after stopping the clock. Not sure how it will be done in other platforms but driver should ensure that interrupt will not be generated after stopping the clock before it got started.

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 38 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: done

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c [hunk 46]
```diff
@@ -0,0 +1,318 @@
...
+	err = clock_control_on(dev, NULL);
+	zassert_equal(0, err, "%s: Unexpected err (%d)", dev_name, err);
+
+	status = clock_control_get_status(dev, NULL);
+	zassert_equal(CLOCK_CONTROL_STATUS_STARTING, status,
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: removed locking and relaxed check:
just after starting expecting `starting` or `on` status, after busy for waiting startup time expecting `on`.

File: drivers/clock_control/nrf_power_clock.c (hunk 43 above)
[the remark this answers is not in the document]
Comment (anangl) [reply drivers/clock_control/nrf_power_clock.c]: I see. This clearing seems to be deserving a comment. It's not that obvious why the STARTED event is cleared right after the STOP task is triggered.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 47]
```diff
@@ -0,0 +1,272 @@
...
+	return ret;
+}
+
+bool nrf_clock_control_calibration_start(struct device *dev)
+{
+	bool ret;
+	int key = irq_lock();
+
+	cal_state = CAL_IDLE;
+	if (cal_state != CAL_ACTIVE_OFF) {
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: my bad. fixed.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 48]
```diff
@@ -0,0 +1,272 @@
...
+		}
+	}
+
+	if (clock_event_check_and_clean(NRF_CLOCK_EVENT_DONE,
+					NRF_CLOCK_INT_DONE_MASK)) {
+		LOG_DBG("Calibration done.");
+		on_cal_done();
+	}
+
+	if (/*NRF_CLOCK_INT_CTSTOPPED_MASK &&*/
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: fixed

File: drivers/clock_control/nrf_power_clock.c (hunk 43 above)
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: added comment.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 49]
```diff
@@ -0,0 +1,273 @@
...
+}
+
+void nrf_clock_control_calibration_init(struct device *dev)
+{
+	/* Errata 36: After watchdog timeout reset, CPU lockup reset, soft
+	 * reset, or pin reset EVENTS_DONE and EVENTS_CTTO are not reset.
+	 */
+	nrf_clock_event_clear(NRF_CLOCK_EVENT_DONE);
+	nrf_clock_event_clear(NRF_CLOCK_EVENT_CTTO);
+	nrf_clock_event_clear(NRF_CLOCK_EVENT_CTSTOPPED);
```
Comment (anangl) [inline drivers/clock_control/nrf_clock_calibration.c]: This should be inside `if (NRF_CLOCK_EVENT_CTSTOPPED) {}`.
It's not that harmful right not, as it clears `HFCLKSTARTED` if `CTSTOPPED` is not present, but...

Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: it's actually not needed. I've added it because i had some issues which turns out to be not related to that. forgot to remove it then. Removed now.

File: drivers/clock_control/nrf_power_clock.c [hunk 50]
```diff
@@ -1,280 +1,333 @@
...
+	if (power_event_check_and_clean(NRF_POWER_EVENT_USBREMOVED,
+					NRF_POWER_INT_USBREMOVED_MASK)) {
+		usb_dc_nrfx_power_event_callback(NRF_POWER_EVENT_USBREMOVED);
 	}
+#endif
 }
 
-#if defined(CONFIG_USB) && defined(CONFIG_SOC_NRF52840)
-static inline void power_event_cb(nrf_power_event_t event)
+static void pof_isr(void)
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: Do we actually need this? The `POFWARN` interrupt is not active, so this function actually does nothing but a little delay.

File: drivers/clock_control/nrf_power_clock.c [hunk 51]
```diff
@@ -286,197 +339,33 @@ static inline void power_event_cb(nrf_power_event_t event)
...
-			NRF_CLOCK->INTENCLR = CLOCK_INTENCLR_LFCLKSTARTED_Msk;
-
-#if NRF_CLOCK_HAS_CALIBRATION
-			/* Start HF Clock if LF RC is used. */
-			if ((NRF_CLOCK->LFCLKSRCCOPY & CLOCK_LFCLKSRCCOPY_SRC_Msk) ==
-			    CLOCK_LFCLKSRCCOPY_SRC_RC) {
-				ctto = 1U;
-			}
-#endif
+		if (!data->started) {
```
Comment (anangl) [inline drivers/clock_control/nrf_power_clock.c]: I think I already asked about this, but my question somehow got lost.
Is is done because of the anomaly 201? It should be commented properly then. Now it looks like a redundant check.

File: drivers/clock_control/nrf_power_clock.c (hunk 50 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: right, when POF support will be added then it makes sense. removed.

File: drivers/clock_control/nrf_power_clock.c (hunk 51 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_power_clock.c]: added comment about anomaly 201.

**Review by anangl — APPROVED** [review]

**Comment by nordic-krch** [comment]
@pizi-nordic @cvinayak @ioannisg anyone would find some time to do the review? @anangl did quite extensive one but we need another to get that in.

**Comment by ioannisg** [comment]
> 
> 
> @pizi-nordic @cvinayak @ioannisg anyone would find some time to do the review? @anangl did quite extensive one but we need another to get that in.

I think we should all review this; it is a major driver, affecting all systems in nRF platforms. I am going to do a pass; for now, I am a bit concerned whether this increases RAM usage... I saw, here, a ram-usage fix in one of nRF51 tests, and I started thinking about it. We should are to re-work the driver, we need to ensure this does not bring further overhead for the resource-constrained nrf51 SOC

File: drivers/clock_control/nrf_clock_calibration.c [hunk 52]
```diff
@@ -0,0 +1,272 @@
...
+	COND_CODE_1(CONFIG_TEMP_NRF5, (CONFIG_TEMP_NRF5_NAME), (NULL))
+
+/* Calibration state enum */
+enum nrf_cal_state {
+	CAL_OFF,
+	CAL_IDLE,	/* Calibration timer active, waiting for expiration. */
+	CAL_HFCLK_REQ,	/* HFCLK XTAL requested. */
+	CAL_TEMP_REQ,	/* Temperature measurement requested. */
+	CAL_ACTIVE,	/* Ongoing calibration. */
+	CAL_ACTIVE_OFF /* Ongoing calibration, off requested. */
```
Comment (pizi-nordic) [inline drivers/clock_control/nrf_clock_calibration.c]: Please align comments.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 53]
```diff
@@ -0,0 +1,272 @@
...
+static struct device *hfclk_dev; /* Handler to hfclk device. */
+static struct device *temp_sensor; /* Handler to temperature sensor device. */
+
+static void measure_temperature(struct k_work *work);
+static K_WORK_DEFINE(temp_measure_work, measure_temperature);
+
+static bool clock_event_check_and_clean(u32_t evt, u32_t intmask)
+{
+	bool ret = nrf_clock_event_check(evt) &&
+			nrf_clock_int_enable_check(intmask);
```
Comment (pizi-nordic) [inline drivers/clock_control/nrf_clock_calibration.c]: Why we care clearing event only if IRQ is enabled?

File: drivers/clock_control/nrf_clock_calibration.c [hunk 54]
```diff
@@ -0,0 +1,272 @@
...
+	nrf_clock_task_trigger(NRF_CLOCK_TASK_CTSTART);
+}
+
+/* Convert sensor value to 0.25'C units. */
+static inline s16_t sensor_value_to_temp_unit(struct sensor_value *val)
+{
+	return (s16_t)(4 * val->val1 + val->val2 / 250000);
+}
+
+/* Function reads from temperature sensor and converts to float. */
```
Comment (pizi-nordic) [inline drivers/clock_control/nrf_clock_calibration.c]: I do not see float in this function.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 55]
```diff
@@ -0,0 +1,272 @@
...
+
+	sensor_sample_fetch(temp_sensor);
+	sensor_channel_get(temp_sensor, SENSOR_CHAN_DIE_TEMP, &sensor_val);
+
+	return sensor_value_to_temp_unit(&sensor_val);
+}
+
+/* Function determines if calibration should be performed based on temperature
+ * measurement. Function is called from system work queue context. It is
+ * reading temperature from TEMP sensor and compares with last measurement.
```
Comment (pizi-nordic) [inline drivers/clock_control/nrf_clock_calibration.c]: You cannot use last measurement! This way you might never run the calibration if the temp changes slowly!

File: drivers/clock_control/nrf_clock_calibration.c [hunk 56]
```diff
@@ -0,0 +1,272 @@
...
+	diff = diff < 0 ? -diff : diff;
+	prev_temperature = temperature;
+
+	key = irq_lock();
+
+	if (cal_state != CAL_OFF) {
+		if (diff >= CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_TEMP_DIFF) {
+			start_calibration();
+		} else {
+			LOG_DBG("Calibration skipped - stable temperature.");
```
Comment (pizi-nordic) [inline drivers/clock_control/nrf_clock_calibration.c]: IMHO it might be a good idea to print the temperature difference here.

**Review by pizi-nordic — CHANGES_REQUESTED** [review]

File: tests/drivers/clock_control/clock_control_api/nrf_lfclk_rc.conf [hunk 57]
```diff
@@ -0,0 +1,2 @@
+CONFIG_ZTEST=y
+CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
```
Comment (pizi-nordic) [inline tests/drivers/clock_control/clock_control_api/nrf_lfclk_rc.conf]: No new line at the end of file.

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c [hunk 58]
```diff
@@ -0,0 +1,310 @@
...
+
+	err = clock_control_on(dev, NULL);
+	zassert_equal(0, err, "%s: Unexpected err (%d)", dev_name, err);
+
+	status = clock_control_get_status(dev, NULL);
+	zassert_true((status == CLOCK_CONTROL_STATUS_STARTING) ||
+			(status == CLOCK_CONTROL_STATUS_ON),
+			"%s: Unexpected status (%d)", dev_name, status);
+
+	k_busy_wait(startup_us*1.5);
```
Comment (pizi-nordic) [inline tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: Why you are using multiplier here? Aren't deadlines specified in the devices array?

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c [hunk 59]
```diff
@@ -0,0 +1,310 @@
...
+	zassert_equal(CLOCK_CONTROL_STATUS_OFF, status,
+			"%s: Unexpected status (%d)", dev_name, status);
+
+	for (int i = 0; i < users; i++) {
+		err = clock_control_on(dev, NULL);
+		zassert_equal(0, err, "%s: Unexpected err (%d)", dev_name, err);
+	}
+
+	status = clock_control_get_status(dev, NULL);
+	zassert_true(status != CLOCK_CONTROL_STATUS_OFF,
```
Comment (pizi-nordic) [inline tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: Could we specify here what we expect not what we not expect?

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c [hunk 60]
```diff
@@ -0,0 +1,310 @@
...
+			"%s: Unexpected status (%d)", dev_name, status);
+
+	for (int i = 0; i < users; i++) {
+		err = clock_control_off(dev, 0);
```
Comment (pizi-nordic) [inline tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: Could we also check what happen if there will be more off requests than on requests?

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c [hunk 61]
```diff
@@ -0,0 +1,310 @@
...
+
+	err = clock_control_async_on(dev, 0, &data2);
+	zassert_equal(0, err, "%s: Unexpected err (%d)", dev_name, err);
+
+	/* wait for clock started. */
+	k_busy_wait(startup_us*1.5);
+
+	zassert_true(executed1, "%s: Expected flag to be true", dev_name);
+	zassert_true(executed2, "%s: Expected flag to be true", dev_name);
+}
```
Comment (pizi-nordic) [inline tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: IMHO we should also check if the clocks are really on.

File: tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c [hunk 62]
```diff
@@ -0,0 +1,181 @@
...
+	int key;
+	u32_t cnt = 0;
+	u32_t max_cnt = 1000;
+
+	turn_off_clock(hfclk_dev);
+	turn_off_clock(lfclk_dev);
+
+	clock_control_on(lfclk_dev, NULL);
+
+	/* It may be required to restart CT. Allow that by 1ms without lock */
```
Comment (pizi-nordic) [inline tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c]: CT?

File: tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c [hunk 63]
```diff
@@ -0,0 +1,181 @@
...
+		k_busy_wait(1000);
+		cnt++;
+		if (cnt == max_cnt) {
+			irq_unlock(key);
+			clock_control_off(lfclk_dev, NULL);
+			zassert_true(false, "");
+		}
+	}
+
+	zassert_within(cnt, 250, 10, "Expected 250ms period");
```
Comment (pizi-nordic) [inline tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c]: Am I correct assuming that the first calibration will start 250ms after clock startup? If so, shouldn't we start calibration as early as possible in order to provide stable clock?

File: tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c [hunk 64]
```diff
@@ -0,0 +1,181 @@
...
+
+	irq_unlock(key);
+
+	while (clock_control_get_status(hfclk_dev, NULL)
+			!= CLOCK_CONTROL_STATUS_ON) {
```
Comment (pizi-nordic) [inline tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c]: In my opinion we always should specify what we waiting for.

File: drivers/clock_control/nrf_clock_calibration.c (hunk 53 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: why should we clean it always?

File: drivers/clock_control/nrf_clock_calibration.c (hunk 55 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: we might improve algorithm in the future, this is initial one. If temperature changes slowly then calibration will be forced after exceeding `CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP` skips.

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 58 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: I want to take into account potential unalignment or imprecision of k_busy_wait.

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 59 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: at this point clock might be `STARTING` or `ON`. It's hard to determine. If clock is starting fast then it may be on already.

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 61 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: It's hard to check that in generic way. Callback is the indicator

File: drivers/clock_control/nrf_clock_calibration.c (hunk 53 above)
Comment (pizi-nordic) [reply drivers/clock_control/nrf_clock_calibration.c]: Why we are cleaning event only when IRQ is enabled for it?

File: drivers/clock_control/nrf_clock_calibration.c (hunk 55 above)
Comment (pizi-nordic) [reply drivers/clock_control/nrf_clock_calibration.c]: So please set the limit for this variable CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP.
IMHO fixing the algorithm is not a big deal...

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 58 above)
Comment (pizi-nordic) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: k_busy_wait is pretty accurate. IMHO it would be better to pass the values from the table directly.

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 59 above)
Comment (pizi-nordic) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: So we should have `status == STARTING || status == ON`. This will be easier to read.

File: drivers/clock_control/Kconfig.nrf [hunk 65]
```diff
@@ -47,14 +47,47 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+	range 0 255
 	help
-	  Clock control driver will spin wait in CPU sleep until 32KHz
-	  crystal oscillator starts up. If not enabled, RC oscillator will
-	  initially start running and automatically switch to crystal when
-	  ready.
+	  Calibration is skipped when temperature change did not exceeded
+	  configured threshold. If number of consecutive skips reaches
+	  configured value then calibration is performed unconditionally. Set to
+	  0 to perform unconditional calibration periodically.
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/Kconfig.nrf]: done

File: drivers/clock_control/Kconfig.nrf [hunk 66]
```diff
@@ -47,14 +47,47 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+
+config CLOCK_CONTROL_NRF_CALIBRATION_TEMP_DIFF
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/Kconfig.nrf]: i've rephrased it, please take another look.

File: drivers/clock_control/nrf_clock_calibration.c (hunk 52 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: done

File: drivers/clock_control/nrf_clock_calibration.c (hunk 54 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: fixed

File: drivers/clock_control/nrf_clock_calibration.c (hunk 56 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: done

File: tests/drivers/clock_control/clock_control_api/nrf_lfclk_rc.conf (hunk 57 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/nrf_lfclk_rc.conf]: done

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 58 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: removed `1.5*` and trimmed startup times.

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 59 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: done

File: tests/drivers/clock_control/clock_control_api/src/test_clock_control.c (hunk 60 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/clock_control_api/src/test_clock_control.c]: added one more attempt expecting `-EALREADY`

File: tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c (hunk 62 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c]: replaced CT with calibration timer,

File: tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c (hunk 63 above)
Comment (nordic-krch) [reply tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c]: i've changed the behavior. first calibration is performed immediately after starting LF clock.

**Comment by nordic-krch** [comment]
@ioannisg 
> I am a bit concerned whether this increases RAM usage...

It's only couple of bytes and that brought your attention only because there was a test that was using 99,5% or RAM. There are dozens of places where ram is wasted. It's increased mainly when LF RC is used because of async data structure required (12 bytes).

File: drivers/clock_control/nrf_clock_calibration.c (hunk 55 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: @pizi-nordic please take a look. the diff is now calculated based on measurement done during last calibration.

File: drivers/clock_control/Kconfig.nrf [hunk 67]
```diff
@@ -47,14 +47,51 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+if CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION
+
+config CLOCK_CONTROL_NRF_CALIBRATION_PERIOD
+	int "Calibration opportunity period (in 250ms units)"
+	default 1
+	range 1 127
+	help
+	  Periodically, calibration action is performed. Action includes
+	  temperature measurement followed by clock calibration. Calibration may
+	  be skipped if temperature change (compared to previous measurement)
```
Comment (pizi-nordic) [inline drivers/clock_control/Kconfig.nrf]: ... compared to temperature of previous calibration ...

File: drivers/clock_control/Kconfig.nrf [hunk 68]
```diff
@@ -47,14 +47,51 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+	  configured threshold. If number of consecutive skips reaches
+	  configured value then calibration is performed unconditionally. Set to
+	  0 to perform calibration periodically regardless of temperature
+	  change.
+
+config CLOCK_CONTROL_NRF_CALIBRATION_TEMP_DIFF
+	int "Temperature change triggering calibration (in 0.25 degree units)"
+	default 2
+	help
+	  if temperature change between two consecutive measurements equals or
```
Comment (pizi-nordic) [inline drivers/clock_control/Kconfig.nrf]: ... since last calibration ...

**Review by pizi-nordic — COMMENTED** [review]
Please update description in order to describe current behaviour.

**Comment by nordic-krch** [comment]
Rebased.

@pabigot it's no longer blocked by #17301. 
@pizi-nordic long time ago you were soo close to approve, then vacation time came. Can you take another look?

File: drivers/clock_control/nrf_clock_calibration.c [hunk 69]
```diff
@@ -0,0 +1,279 @@
...
+	bool ret;
+	int key = irq_lock();
+
+	if (cal_state != CAL_ACTIVE_OFF) {
+		ret = true;
+	} else {
+		ret = false;
+	}
+
+	cal_state = CAL_IDLE;
```
Comment (pabigot) [inline drivers/clock_control/nrf_clock_calibration.c]: I don't have any faith that this unconditional setting of `cal_state` correctly maintains the state machine.  It could, if the call site does the necessary checking for other values, but the call site is in another source file and obscured by a couple layers of indirection through so it's not obvious.

I really think these functions should be private (see other comment).

File: drivers/clock_control/Kconfig.nrf [hunk 70]
```diff
@@ -47,14 +47,51 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+config CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION
+	bool
+	depends on !SOC_SERIES_NRF91X
+	default y if CLOCK_CONTROL_NRF_K32SRC_RC
+
+if CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION
+
+config CLOCK_CONTROL_NRF_CALIBRATION_PERIOD
+	int "Calibration opportunity period (in 250ms units)"
+	default 1
```
Comment (pabigot) [inline drivers/clock_control/Kconfig.nrf]: Why is the default 1?  Last I looked the recommended interval was 4 s to maintain accuracy required for Bluetooth.  (That was some time back, so maybe it does need to be done at 4 Hz now.)

File: drivers/clock_control/Kconfig.nrf [hunk 71]
```diff
@@ -47,14 +47,51 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+	int "Maximum number of calibration skips"
+	default 4
+	range 0 255
 	help
-	  Clock control driver will spin wait in CPU sleep until 32KHz
-	  crystal oscillator starts up. If not enabled, RC oscillator will
-	  initially start running and automatically switch to crystal when
-	  ready.
+	  Calibration is skipped when temperature change since last calibration
+	  did not exceeded configured threshold. If number of consecutive skips
```
Comment (pabigot) [inline drivers/clock_control/Kconfig.nrf]: "~did not exceeded~was less than"

Typo and edge case error (it isn't skipped when the change equaled the threshold).

File: drivers/clock_control/Kconfig.nrf [hunk 72]
```diff
@@ -47,14 +47,51 @@ config CLOCK_CONTROL_NRF_K32SRC_EXT_FULL_SWING
...
+	range 1 127
+	help
+	  Periodically, calibration action is performed. Action includes
+	  temperature measurement followed by clock calibration. Calibration may
+	  be skipped if temperature change (compared to measurement of previous
+	  calibration) did not exceeded CLOCK_CONTROL_NRF_CALIBRATION_TEMP_DIFF
+	  and number of consecutive skips did not exceeded
+	  CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP.
+
+config CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP
```
Comment (pabigot) [inline drivers/clock_control/Kconfig.nrf]: Do you really need this feature if the default CTIV is 16 (4 s) instead of 1 (0.25 s)?  I guess it does allow a maximum interval of 255*31.25 s, and allows rapid recalibration of the temperature changes at rates like 1 Cel / s but I'm not convinced the complexity of a two-level timeout counter is warranted.

**Review by pabigot — COMMENTED** [review]
A few comments.  The complexity of this is a bit more than I can comprehend right now.  If the calibration material was in the same source file as the code that invokes it, it'd be easier to be convinced that the state machine maintenance is correct.  Also some of my comments on CTIV are made in ignorance of what other Nordic infrastructure has done.  The two-level counter+skip approach seems far more complex than it needs to be, but if you're re-implementing a standard approach from NCS or SDK or nrfx then I guess it's OK.

As a future enhancement it would be nice to have the temperature monitor pulled out to a separate API that could be shared between RC calibration and ADC calibration.

**Review by joerchan — CHANGES_REQUESTED** [review]

**Review by pizi-nordic — APPROVED** [review]

File: drivers/clock_control/nrf_clock_calibration.c [hunk 73]
```diff
@@ -0,0 +1,279 @@
+/*
+ * Copyright (c) 2016-2019 Nordic Semiconductor ASA
+ * Copyright (c) 2016 Vinayak Kariappa Chettimada
```
[the remark this answers is not in the document]
Comment (ioannisg) [reply drivers/clock_control/nrf_clock_calibration.c]: Reason, here, may be that these contributions were done before Nordic was officially involved in Zephyr

[the remark this answers is not in the document]
Comment (ioannisg) [reply drivers/clock_control/nrf_clock_calibration.c]: I mean, the reason for individual copyright

File: drivers/clock_control/Kconfig.nrf (hunk 70 above)
Comment (nordic-krch) [reply drivers/clock_control/Kconfig.nrf]: shouldn't then CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP = 1? With 2 that would result in 12 seconds if no temp change.

File: drivers/clock_control/nrf_clock_calibration.c (hunk 73 above)
[the remark this answers is not in the document]
Comment (joerchan) [reply drivers/clock_control/nrf_clock_calibration.c]: @ioannisg This is a new file in this PR.

File: tests/bluetooth/mesh/microbit.conf [hunk 74]
```diff
@@ -50,3 +50,5 @@ CONFIG_BT_MESH_LABEL_COUNT=0
 #CONFIG_BT_MESH_DEBUG_CRYPTO=y
 #CONFIG_BT_MESH_DEBUG_ADV=y
 #CONFIG_BT_MESH_DEBUG_ACCESS=y
+
+CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP=0
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply tests/bluetooth/mesh/microbit.conf]: fixed commit message

File: drivers/clock_control/nrf_clock_calibration.c [hunk 75]
```diff
@@ -0,0 +1,279 @@
...
+ * reading temperature from TEMP sensor and compares with last measurement.
+ */
+static void measure_temperature(struct k_work *work)
+{
+	s16_t temperature;
+	s16_t diff;
+	int key;
+
+	temperature = get_temperature();
+	diff = temperature - prev_temperature;
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: done

File: drivers/clock_control/nrf_clock_calibration.c (hunk 69 above)
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: Function are somehow private now (see other comment)

File: drivers/clock_control/Kconfig.nrf (hunk 70 above)
Comment (nordic-krch) [reply drivers/clock_control/Kconfig.nrf]: applied defaults as suggested (but set CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP = 1 to achieve calibration every 8s when no temperature change).

File: drivers/clock_control/Kconfig.nrf (hunk 71 above)
Comment (nordic-krch) [reply drivers/clock_control/Kconfig.nrf]: fixed.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c [hunk 76]
```diff
@@ -319,9 +319,12 @@ int lll_clk_on_wait(void)
 	int err;
 
 	/* turn on radio clock in blocking mode. */
-	err = clock_control_on(lll.clk_hf, (void *)1);
-	if (!err || err == -EINPROGRESS) {
+	err = clock_control_on(lll.clk_hf, NULL);
+
+	while (clock_control_get_status(lll.clk_hf, NULL) !=
+			CLOCK_CONTROL_STATUS_ON) {
 		DEBUG_RADIO_XTAL(1);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c]: done

File: drivers/clock_control/nrf_clock_calibration.c [hunk 77]
```diff
@@ -0,0 +1,279 @@
...
+		 */
+		if (cal_state == CAL_IDLE) {
+			cal_state = CAL_HFCLK_REQ;
+			clock_control_async_on(hfclk_dev, 0, &cal_hf_on_data);
+		}
+	}
+
+	if (clock_event_check_and_clean(NRF_CLOCK_EVENT_DONE,
+					NRF_CLOCK_INT_DONE_MASK)) {
+		LOG_DBG("Calibration done.");
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: done

File: drivers/clock_control/nrf_clock_calibration.c [hunk 78]
```diff
@@ -0,0 +1,279 @@
...
+
+	if (CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_MAX_SKIP != 0) {
+		temp_sensor = device_get_binding(TEMP_SENSOR_NAME);
+	}
+
+	hfclk_dev = dev;
+}
+
+/* Start calibration assuming that HFCLK XTAL is on. */
+static void start_calibration(void)
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: Added `void z_nrf_clock_calibration_force_start(void);` function for `nrf_clock_control.h` (which is considered nordic specific but public). This call will trigger calibration immediately.

File: drivers/clock_control/nrf_clock_calibration.c (hunk 73 above)
[the remark this answers is not in the document]
Comment (ioannisg) [reply drivers/clock_control/nrf_clock_calibration.c]: @joerchan , it was a rather general answer ;) There are such files in the controller subsystem.

File: drivers/clock_control/nrf_clock_calibration.c [hunk 79]
```diff
@@ -0,0 +1,279 @@
...
+			start_calibration();
+		} else {
+			LOG_DBG("Calibration skipped due to stable temperature"
+				" (diff: %d in 0.25'C units).", diff);
+			to_idle();
+			calib_skip_cnt--;
+		}
+	}
+
+	irq_unlock(key);
```
[the remark this answers is not in the document]
Comment (nordic-krch) [reply drivers/clock_control/nrf_clock_calibration.c]: done

**Review by joerchan — APPROVED** [review]

**Comment by nordic-krch** [comment]
It's been out for 3 months. There are 3 approvals. @carlescufi @ioannisg can we merge this then unless someone plans to review it soon?

**Comment by aescolar** [comment]
For the record, I have no issue with this PR. The only file changed I own is perfectly fine. But as this is a Nordic only change, I do not believe I should approve it. I presume BT and USB maintainers would have a similar feeling as the BT and USB code changes are minor and circumstantial.

**Comment by ioannisg** [comment]
> It's been out for 3 months. There are 3 approvals. @carlescufi @ioannisg can we merge this then unless someone plans to review it soon?

I would appreciate if @pabigot could re-review once more (and approve if possible). I guess we can merge this afterwards ;)

**Review by pabigot — COMMENTED** [review]
My comments appear to have been addressed.  I haven't tested this or done an in-depth functional review so don't feel comfortable "approving" it, but I don't see any reason it should be kept out.

**Comment by martintv** [comment]
I haven't looked much at the code, this switch to zephyr is all new to me, so I am still confused. So so this is more a question than a suggestion.  After this PR we will still use the Calibration timer in the NRF_CLOCK peripheral right? how easy would it be to switch to using some other source for the periodic timer to drive the calibration state machine in zephyr world? we always wanted to do that in SoftDevice, but never did. The calibration timer in in NRF_CLOCK has some big awkward weaknesses, since some register can not be written withing the same 32khz clock cycle as some things happens. Another reason to stop using the calibration timer, is that we want to remove it from the chip, to save silicon, if sw could do without it.

**Comment by nordic-krch** [comment]
@martintv i don't see any obstacles. In the next step we can replace calibration timer with k_timer.

**Comment by nordic-krch** [comment]
@ioannisg see @pabigot comment. What then blocks as from merging it?

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg see @pabigot comment. What then blocks as from merging it?

Your description is still blocking this PR @nordic-krch. 
#17301 is not reviewed/merged. Please, advice

**Comment by nordic-krch** [comment]
@ioannisg i've updated description as this is no longer true. I don't use functionality which #17301 attempted to add.

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg i've updated description as this is no longer true. I don't use functionality which #17301 attempted to add.

OK, great, now this PR is not blocked-by-definition ;)
Could you rebase and run CI (PR hasn't been rebased for ~10 days, AFAICS)

**Comment by nordic-krch** [comment]
@ioannisg, done.

**Review by carlescufi — APPROVED** [review]
I tested the following:

- `central_hr` on nRF51 DK
- `peripheral` (complete with bonding and reconnection) on nRF51 DK
- `central_hr` on BBC micro:bit
- `peripheral_hr` on BBC micro:bit

**Comment by joerchan** [comment]
There is by default a lot of info lines being printed. Can we change the settings so that that doesn't happen?
```
[00:10:10.496,673] <inf> clock_control: CLOCK_16M: callback
[00:10:10.496,704] <inf> clock_control: CLOCK_16M: node 0x0000000
```

**Comment by carlescufi** [comment]
> There is by default a lot of info lines being printed. Can we change the settings so that that doesn't happen?
> 
> ```
> [00:10:10.496,673] <inf> clock_control: CLOCK_16M: callback
> [00:10:10.496,704] <inf> clock_control: CLOCK_16M: node 0x0000000
> ```
> 
> Tested connections using 2 nrf52840. and 500 PPM, works fine.

I saw that as well, I assumed this was my config but now that @joerchan also brings it up I think this is worth cleaning up. @nordic-krch could you please disable those by default?

**Comment by nordic-krch** [comment]
@carlescufi @joerchan removed those log calls.

@carlescufi I've reduced irq locking time. Additionally, i did measurement to check longest locking time in clock driver vs other lockings (used peripheral_hr sample for that). Clock locking is up to 1.4us while there are many many more longer lockings (up to 2.5ms which seems very odd). In general locking in clock is one of the shortest.

**Comment by carlescufi** [comment]
> @carlescufi @joerchan removed those log calls.
> 
> @carlescufi I've reduced irq locking time. Additionally, i did measurement to check longest locking time in clock driver vs other lockings (used peripheral_hr sample for that). Clock locking is up to 1.4us while there are many many more longer lockings (up to 2.5ms which seems very odd). In general locking in clock is one of the shortest.

Thank you @nordic-krch. I will merge this as soon as CI passes.
