### PR TITLE
Bluetooth: Mesh: LPN: Remove msg from cache on rejection

### LINKED ISSUE #17809: Bluetooth Mesh message cached too early when LPN
**Describe the bug**

When a device is operating as an LPN and polls its friend there is a small window in which it may receive messages from non-friends in the mesh as well as the response to the poll from its friend. The network layer will add any messages it receives to the network message cache, regardless of what credentials it is encrypted with (network or friend) and regardless of the current friendship state of the LPN. If a message is received that is ultimately destined for the LPN, but was not sent by the friend, the network layer will cache it and pass it onto the transport layer, where it will be rejected:

https://github.com/zephyrproject-rtos/zephyr/blob/bcd60189c2568bcb9e56df0af2d31d7bbd6a438a/subsys/bluetooth/mesh/transport.c#L1405-L1410

If one of the messages received in this fashion is ultimately destined for the LPN, it will get rejected by the network layer when the friend sends it to the LPN in response to a poll:

https://github.com/zephyrproject-rtos/zephyr/blob/bcd60189c2568bcb9e56df0af2d31d7bbd6a438a/subsys/bluetooth/mesh/net.c#L1000-L1003

When this happens the message is not forwarded onto to the transport layer and the state machine for handling the LPN behaviour will attempt to poll the friend a few more times (seemingly getting no response). After a few attempts it clears its friendship.

**To Reproduce**

I don't have an MWE, but I would expect to see this occur whenever an LPN is working in a mesh that has a reasonably high rate of traffic. In my case the LPN is sending a segmented message to a unicast address and the destination device responds with a single-segment segmented message almost immediately.

**Expected behavior**
Unfortunately I can't see how this scenario is meant to be handled in the spec. In fact there's not too much said at all about the Network Message Cache.

I would expect that, when an LPN has established friendship it simply ignores all messages received that are not encrypted with the friend credentials. This would prevent messages being added to the cache which are then subsequently ignored (but will need to be accepted later on).

**Screenshots or console output**
Apologies for the text-in-screenshot. It does at least preserve the colouring, which helps to interpret it. Note that this is the combined log from two devices (a friend node 'HUB' and an LPN 'SENSOR').

The key parts are the 'Ignoring unexpected message in Low Power mode' at 53:234,619. The friend receives this message and queues it up in buffer 0x20007ce8. At 53:815,673 the LPN rejects the message from the friend ('Duplicate found in Network Message Cache') that the friend just sent, which if you look two lines up was the one from buffer 0x20007ce8.

Screenshot from 2019-07-26 16-19-08
Screenshot from 2019-07-26 16-19-15

**Environment (please complete the following information):**
 - OS: Linux (Fedora 29)
 - Toolchain: gcc-arm-none-eabi-6-2017-q2-update
 - Commit SHA or Version used: 3bbcdc79d0f2682bd16af0a61ec632950a4d8f20

### PR DESCRIPTION
**Pull request by richardbarlow**
When in Low Power mode an LPN may receive messages sent by nodes other
than its friend during its brief receive window. These messages get
rejected by the transport layer. At some point in the future the LPN
will receive these messages from its friend, however they will have
already been added to the network message cache earlier.

When the transport layer rejects a message due to it being received from
a non-friend node while in Low Power mode it must be removed from the
network message cache so that it can be correctly received from its
friend in the future.

Fixes #17809

Signed-off-by: Rich Barlow <rich@bennellick.com>

### CODE REVIEW

**Review by jhedberg — CHANGES_REQUESTED** [review]
Thanks for the PR!

Instead of calculating the hash and iterating the cache a second time, wouldn't it be nicer to make this O(1) by just storing a pointer (or array index) to the cache entry so you have direct access to it from the new branch. If it doesn't complicate the code too much it might be worth it, especially with larger message cache sizes. It might be easiest to add the cache entry reference to `struct bt_mesh_net_rx` since that struct is accessible from both places you need it.

**Comment by richardbarlow** [comment]
I've removed the iteration on removal, but kept the check against the hash as a sanity check that we are removing the entry corresponding to the message. The hash function is very simple and computationally lightweight, so doesn't add a significant overhead. Also, this removal procedure only occurs in reasonably rare circumstances.

**Comment by jhedberg** [comment]
> I've removed the iteration on removal, but kept the check against the hash as a sanity check that we are removing the entry corresponding to the message. The hash function is very simple and computationally lightweight, so doesn't add a significant overhead. Also, this removal procedure only occurs in reasonably rare circumstances.

@richardbarlow I understand your reasoning, however all the `bt_mesh_net_recv()` calls happen from non-preemptible cooperative threads, meaning a race condition should not be possible. Furthermore, if a race was possible there are already windows of opportunity for it e.g. with the handling of `msg_cache_next`. Since the code is already (correctly so) assuming that races with the cache are not possible I'd prefer to keep it consistent to avoid "is this correct?" reactions from the casual reader. Another benefit you get is that you can then also do `msg_cache_next = rx->msg_cache_idx;` after clearing the entry, making sure the next received packet doesn't unnecessarily overwrite a valid entry in the cache. Since the clearing becomes just two lines of code (setting to 0 and restoring `msg_cache_next`) you'll probably also not need a new helper function anymore.

Could you also squash your commits into a single one since the second is essentially just fixing/improving the first one?

**Comment by jhedberg** [comment]
@richardbarlow btw, if you are still paranoid about the races we could potentially consider introducing asserts rather than checks which are always present. Note also that we ensure that the system workqueue (from where some `bt_mesh_net_recv()` calls happen  is always a cooperative priority through this in `subsys/bluetooth/Kconfig`:
```
# The Bluetooth subsystem requires the system workqueue to execute at
# a cooperative priority.
config SYSTEM_WORKQUEUE_PRIORITY
        range -256 -1
```

File: subsys/bluetooth/mesh/net.c [hunk 1]
```diff
@@ -132,17 +132,30 @@ static bool msg_cache_match(struct bt_mesh_net_rx *rx,
 
 	for (i = 0U; i < ARRAY_SIZE(msg_cache); i++) {
 		if (msg_cache[i] == hash) {
+			rx->msg_cache_idx = i;
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/net.c]: This is kind of unnecessary, since in this branch we return and say a match was found, i.e. no further processing of the packet happens.

File: subsys/bluetooth/mesh/net.h [hunk 2]
```diff
@@ -268,6 +268,7 @@ struct bt_mesh_net_rx {
 	       net_if:2,       /* Network interface */
 	       local_match:1,  /* Matched a local element */
 	       friend_match:1; /* Matched an LPN we're friends for */
+	u16_t  msg_cache_idx;  /* Index of entry in message cache */
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/net.h]: Unrelated to this PR, but potential future improvement work: this struct used to have more members originally and the `u8_t` bitfield made sense then. Now there's unnecessary padding, and we could actually move the fields into the preceding `u32_t` since the sequence number is a 24 bit value in practice. I'd then also just use `int` for the cache index since the struct doesn't become any bigger due to it and it will generate slightly more efficient code for 32 bit MCUs. Same goes for the functions iterating the cache, i.e. change `u16_t` to `int` in `net.c`. Additional bonus with this is getting rid of the `U` suffix from the likes of `0U` (something I rather dislike, but which is a MISRA-C requirement for assignments to unsigned integer variables).

File: subsys/bluetooth/mesh/net.c [hunk 3]
```diff
@@ -132,17 +132,30 @@ static bool msg_cache_match(struct bt_mesh_net_rx *rx,
...
 
 	return false;
 }
 
+static void msg_cache_remove(struct bt_mesh_net_rx *rx,
+			     struct net_buf_simple *pdu)
+{
+	u64_t hash = msg_hash(rx, pdu);
+	if (msg_cache[rx->msg_cache_idx] == hash) {
+		msg_cache[rx->msg_cache_idx] = 0;
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/net.c]: This needs to be `0U` actually since it's a `u64_t` (see my other comment regarding MISRA-C)

Comment (joerchan) [reply subsys/bluetooth/mesh/net.c]: `u64_t` is defined as `unsigned long long`, so it should be `0ULL`. Ideally we should have something like `UINT64_C` in zephyr to simplify this.

**Comment by jhedberg** [comment]
@richardbarlow this PR looks good to be merged, except for this one comment from @joerchan :

> u64_t is defined as unsigned long long, so it should be 0ULL. Ideally we should have something like UINT64_C in zephyr to simplify this.

could you fix that and then I can approve & merge?

**Comment by richardbarlow** [comment]
`ULL` change force pushed

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
