### PR TITLE
drivers: ethernet: fix coverity issue

### LINKED ISSUE #32927: [Coverity CID :219519] Unchecked return value in drivers/ethernet/eth_sam_gmac.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/drivers/ethernet/eth_sam_gmac.c

Category: Error handling issues
Function: `get_mac_addr_from_i2c_eeprom`
Component: Drivers
CID: [219519](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=219519)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/bd97359a5338b2542d19011b6d6aa1d8d1b9cc3f/drivers/ethernet/eth_sam_gmac.c#L1795

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by gudnimg**
If return value is negative (failed) then log the error with a
message.

Coverity-CID: 219519
Fixes #32927

Signed-off-by: Guðni Már Gilbert <gudni.m.g@gmail.com>

### CODE REVIEW

File: drivers/ethernet/eth_sam_gmac.c [hunk 1]
```diff
@@ -1792,9 +1792,14 @@ static void get_mac_addr_from_i2c_eeprom(uint8_t mac_addr[6])
 		return;
 	}
 
-	i2c_write_read(dev, CONFIG_ETH_SAM_GMAC_MAC_I2C_SLAVE_ADDRESS,
-		       &iaddr, CONFIG_ETH_SAM_GMAC_MAC_I2C_INT_ADDRESS_SIZE,
-		       mac_addr, 6);
+	int ret = i2c_write_read(dev, CONFIG_ETH_SAM_GMAC_MAC_I2C_SLAVE_ADDRESS,
```
Comment (jukkar) [inline drivers/ethernet/eth_sam_gmac.c:1795]: We try to introduce variables at the beginning of the block, so could you place the `int ret;` at the beginning of the function. Other than that, LGTM

File: drivers/ethernet/eth_sam_gmac.c [hunk 2]
```diff
@@ -1792,9 +1792,14 @@ static void get_mac_addr_from_i2c_eeprom(uint8_t mac_addr[6])
 		return;
```
Comment (jukkar) [inline drivers/ethernet/eth_sam_gmac.c:1792]: Almost forgot, please change the commit subject to `drivers: ethernet: gmac: Fix coverity issue`

Comment (GunZi200) [reply drivers/ethernet/eth_sam_gmac.c:1793]: Fixed 😄

File: drivers/ethernet/eth_sam_gmac.c (hunk 1 above)
Comment (GunZi200) [reply drivers/ethernet/eth_sam_gmac.c]: Fixed 😄

Comment (GunZi200) [reply drivers/ethernet/eth_sam_gmac.c]: @jukkar I wasn't sure if the order of the variables at the top of the function mattered. But I put `int ret` below `uint32_t`. I vaguely remember seeing this being an issue with some standard like MISRA but not sure.

**Review by jukkar — APPROVED** [review]
Thanks!

File: drivers/ethernet/eth_sam_gmac.c [hunk 3]
```diff
@@ -1785,16 +1785,22 @@ static void get_mac_addr_from_i2c_eeprom(uint8_t mac_addr[6])
...
 
-	i2c_write_read(dev, CONFIG_ETH_SAM_GMAC_MAC_I2C_SLAVE_ADDRESS,
-		       &iaddr, CONFIG_ETH_SAM_GMAC_MAC_I2C_INT_ADDRESS_SIZE,
-		       mac_addr, 6);
+	ret = i2c_write_read(dev, CONFIG_ETH_SAM_GMAC_MAC_I2C_SLAVE_ADDRESS,
+			   &iaddr, CONFIG_ETH_SAM_GMAC_MAC_I2C_INT_ADDRESS_SIZE,
+			   mac_addr, 6);
+
+	if (ret != 0) {
+		LOG_ERR("I2C: i2c_write_read() failed");
```
Comment (pfalcon) [inline drivers/ethernet/eth_sam_gmac.c:1801]: I wanted to give this comment with previous PR (regarding samples/*), but there it's not so important. But this driver can be used in production code, and if log an error at, let's make it be helpful for user/engineer to understand what's the problem. Something like "failed to read MAC addr" would ok (and that's optimized for code size, "failed to read MAC addr from EEPROM" would be better, but too long).

Comment (GunZi200) [reply drivers/ethernet/eth_sam_gmac.c]: @pfalcon I agree. I made the change. Let me know if you'd like to drop the `"I2C: "` part.

**Review by rlubos — APPROVED** [review]

**Review by pfalcon — APPROVED** [review]
