### PR TITLE
tests: sleep: Fix _TICK_ALIGN correction.

### LINKED ISSUE #8899: Failed test: kernel.common.timing.sleep on nrf52 (tests/kernel/sleep/kernel.common.timing)
```
***** delaying boot 1000ms (per build configuration) *****
***** Booting Zephyr OS 1.12.99 (delayed boot 1000ms) *****
Running test suite sleep
===================================================================
starting test - test_sleep
Kernel objects initialized
Test thread started: id = 0x200000e8
Helper thread started: id = 0x2000002c
Testing normal expiration of k_sleep()
FAIL - test_thread@108. *** k_sleep() slept for 998 ticks not 1000.

```

### PR DESCRIPTION
**Pull request by pizi-nordic**
This commit replaces _TICK_ALIGN correction in the test (which was based
on simple division), by more precise estimation utilizing __ticks_to_ms()
and _ms_to_ticks() functions.

This commit fixes #8899.

### CODE REVIEW

File: tests/kernel/sleep/src/main.c [hunk 1]
```diff
@@ -20,8 +20,9 @@
 #define TEST_THREAD_PRIORITY    -4
 #define HELPER_THREAD_PRIORITY  -10
 
-#define ONE_SECOND  (MSEC_PER_SEC)
-#define TICKS_PER_MS  (MSEC_PER_SEC / CONFIG_SYS_CLOCK_TICKS_PER_SEC)
+#define ONE_SECOND		(MSEC_PER_SEC)
```
Comment (andyross) [inline tests/kernel/sleep/src/main.c]: Nothing to do with this patch, but pet peeve: MSEC_PER_SEC is just silly to begin with.  SI number prefixes are an international standard that has been in regular use for over two hundred years.  Defining this as a constant is like defining "SKY_COLOR" to "BLUE".  It's what "milli" means.  We use preprocessor constants to abstract meaning that isn't obvious to the reader, not to move around the musical chairs of linguistic synonums.  And here this test isn't content to leave that alone, it has to do it twice!

File: tests/kernel/sleep/src/main.c [hunk 2]
```diff
@@ -101,16 +102,12 @@ static void test_thread(int arg1, int arg2)
...
-
-	/* FIXME: one tick less to account for
-	 * one  extra tick for _TICK_ALIGN in k_sleep
-	 */
-	k_sleep(ONE_SECOND - TICKS_PER_MS);
+	k_sleep(ONE_SECOND);
 	end_tick = k_uptime_get_32();
 
-	if (!sleep_time_valid(start_tick, end_tick, ONE_SECOND)) {
+	if (!sleep_time_valid(start_tick, end_tick, ONE_SECOND_ALIGNED)) {
```
Comment (andyross) [inline tests/kernel/sleep/src/main.c]: Again, not relevant to this review, but that kind of logic is racy in general.  Probably fine in this one test, but...

**Review by andyross — APPROVED** [review]
Looks clean.  Some grumpy whining about the existing test code, but nothing that you should be reponsible for fixing.

**Review by nashif — APPROVED** [review]
