### PR TITLE
boards: particle_boron: Initialize the board before the modem driver

### LINKED ISSUE #56883: Board init for particle_boron runs too late
**Describe the bug**
The `board_particle_boron_init()` function runs at init priority 99. It configures GPIOs that are needed for using the board's modem.

The board has a u-blox SARA modem that can be used with the `gsm_ppp.c` and `ublox-sara-r4.c` drivers. However, these by default have init priorities 42 and 80. They run before the board init has configured the GPIOs. 

**To Reproduce**
1. Use this overlay:
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_MODEM=y
CONFIG_MODEM_UBLOX_SARA=y
2. Build with `west build -b particle_boron samples/net/lwm2m_client/ -- -DOVERLAY_CONFIG=test.overlay`
3. Observe that the modem driver gets stuck at `Waiting for modem to respond`
4. Change the init priority for `board_particle_boron_init` to 41.
5. Observe that the modem driver no longer gets stuck.

**Expected behavior**
I expected the board init to run before the modem serial line is used.

**Impact**
The modem driver cannot communicate with the modem because the serial buffer (level shifter) is not powered on.

**Environment**
 - OS: Debian sid
 - Toolchain: crosscompiler
 - Commit SHA: e2d1fce6ca51807811e46f29e89c7ba4cf15df46

### PR DESCRIPTION
**Pull request by weinholt**
The board initialization must be done before the modem driver is started because the power to the modem serial line's level shifter is enabled here.

Fixes: #56883

### CODE REVIEW

File: boards/arm/particle_boron/board.c [hunk 1]
```diff
@@ -53,6 +53,7 @@ static int board_particle_boron_init(void)
 }
 
 /* needs to be done after GPIO driver init, which is at
- * POST_KERNEL:KERNEL_INIT_PRIORITY_DEFAULT.
+ * PRE_KERNEL_1:CONFIG_GPIO_INIT_PRIORITY, but before the
+ * modem driver (gsm_ppp or ublox-sara-r4).
  */
-SYS_INIT(board_particle_boron_init, POST_KERNEL, 99);
+SYS_INIT(board_particle_boron_init, POST_KERNEL, 41);
```
Comment (gmarull) [inline boards/arm/particle_boron/board.c:59]: let's not hardcode priorities like this, can you create a board level Kconfig option instead?

**Review by gmarull — CHANGES_REQUESTED** [review]

File: boards/arm/particle_boron/board.c (hunk 1 above)
Comment (gmarull) [reply boards/arm/particle_boron/board.c:59]: Btw, can't this be solved using `regulator-fixed`?

Comment (weinholt) [reply boards/arm/particle_boron/board.c:59]: > Btw, can't this be solved using `regulator-fixed`?

Sounds like a good idea, I will try it out.

Comment (weinholt) [reply boards/arm/particle_boron/board.c]: I ended up removing more lines than I added, so that's good.

However the magic number 41 showed up again in `CONFIG_REGULATOR_FIXED_INIT_PRIORITY=41`. There are two other boards where this is done similarly. The `thingy53_nrf5340` board uses `BUILD_ASSERT` to check that nobody breaks the init order, let me know if you want something similar here.

**Review by gmarull — APPROVED** [review]
lgtm, regarding init priorities, I think it is widely accepted that they are cumbersome, but unfortunately there's nothing better now.

**Review by anangl — APPROVED** [review]

**Comment by gmarull** [comment]
Hey, can you rebase PR?

**Review by MaureenHelm — APPROVED** [review]
