### PR TITLE
driver: i2c: i2c_dw: clear block mode on init

### LINKED ISSUE #98588: drivers: i2c: dw_i2c: i2c read time out on certain type of DW_I2C
### Describe the bug

The designware's i2c hardware supports blocking Master commands after reset:
Image

Image

Depending on the hardware configuration, the current DW_I2C driver might be unable to run any TX transaction.

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. Compile and run the i2c shell on device with `IC_TX_CMD_BLOCK_DEFAULT=1`
2. Perform a `i2c read ...` command
3. The command would fail due to timeout

### Relevant log output

```shell
N/A
```

### Impact

Showstopper – Prevents release or major functionality; system unusable.

### Environment

- Custom Toolchain
- Zephyr v3.7.0 (current `main` has the same issue)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ycsin**
Depending on the IP's `IC_TX_CMD_BLOCK_DEFAULT` parameter, we might have to clear the `TX_CMD_BLOCK` bit on init so that Master mode works.

Fixes #98588

### CODE REVIEW

File: drivers/i2c/i2c_dw.c [hunk 1]
```diff
@@ -1296,6 +1296,8 @@ static int i2c_dw_initialize(const struct device *dev)
 	uint32_t reg_base = get_regs(dev);
 
 	clear_bit_enable_en(reg_base);
+	/* depending on the IP configuration, we may have to disable block mode in master mode */
```
Comment (keith-zephyr) [inline drivers/i2c/i2c_dw.c]: Please use the inclusive term.
https://docs.zephyrproject.org/latest/contribute/coding_guidelines/index.html#rule-a-2-inclusive-language

Comment (ycsin) [reply drivers/i2c/i2c_dw.c]: Isn't it confusing that the all but one comment referred to master mode as 'master mode'..?

Comment (keith-zephyr) [reply drivers/i2c/i2c_dw.c]: I'd prefer you use `controller mode` here.  The common I2C header has switched to `I2C_MODE_CONTROLLER`, so this wouldn't be the first reference to `controller mode` in this driver.

Comment (ycsin) [reply drivers/i2c/i2c_dw.c]: I think it makes more sense to rename all these 'offensive' terms in a single commit so that we dont end up having 'master', 'controller' and 'I2C controller' in a single file, but well..

**Review by keith-zephyr — APPROVED** [review]

**Review by teburd — APPROVED** [review]
