### PR TITLE
Bluetooth: gatt: allow the CCCD to be in any location

### LINKED ISSUE #48880: BLE notifications on custom service not working anymore: <wrn> bt_gatt: Device is not subscribed to characteristic
**Describe the bug**
Using the nRF Connect App and the appended code, whenever I try to send a notification to all connections, an error is returned by `notify_cb`. It seems that this error originates by the change in https://github.com/zephyrproject-rtos/zephyr/pull/46136. When line 2251 in subsys/bluetooth/host/gatt.c is commented out, it works again.

**To Reproduce**
Using attached service

**Expected behavior**
Notifications are being send whenever a phone has subscribed to it using the nRF Connect App

**Logs and console output**
```
[00:01:21.360,839] <wrn> bt_gatt: Device is not subscribed to characteristic
```

**Environment (please complete the following information):**
 - OS: Linux
[rssi_service.zip](https://github.com/zephyrproject-rtos/zephyr/files/9301279/rssi_service.zip)

### PR DESCRIPTION
**Pull request by jori-nordic**
Per spec, the CCCD doesn't necessarily have to be located immediately after
the characteristic value. This commit fixes that assumption when checking
for subscriptions.

Fixes #48880.

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -3145,7 +3149,15 @@ bool bt_gatt_is_subscribed(struct bt_conn *conn,
 		__ASSERT(attr, "No more attributes\n");
 	}
 
-	/* Check if the attribute is the CCC Descriptor */
+	/* Find the CCC Descriptor */
+	while (bt_uuid_cmp(attr->uuid, BT_UUID_GATT_CCC) &&
+	       bt_uuid_cmp(attr->uuid, BT_UUID_GATT_CHRC)) {
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:3154]:
```suggestion
	while (bt_uuid_cmp(attr->uuid, BT_UUID_GATT_CCC) &&
	       /* But stop if we leave the current characteristic definition. */
	       bt_uuid_cmp(attr->uuid, BT_UUID_GATT_CHRC)) &&
	       bt_uuid_cmp(attr->uuid, BT_UUID_GATT_PRIMARY)) &&
	       bt_uuid_cmp(attr->uuid, BT_UUID_GATT_SECONDARY)) {
```

**Review by alwa-nordic — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:3154]: It would be great if you add test cases for a missing CCC with all the different ways to end a characteristic definition.

Comment (jori-nordic) [reply subsys/bluetooth/host/gatt.c:3154]: we can leave that to a future unit-test I think.

**Review by alwa-nordic — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Comment by carlescufi** [comment]
@alwa-nordic @jhedberg please take a look

**Review by jhedberg — DISMISSED** [review]

**Review by alwa-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
