### PR TITLE
cmsis_rtos_v1: decrease instances number in osThreadTerminate.

### LINKED ISSUE #37159: osThreadTerminate does not decrease the instances counter
**Describe the bug**
osThreadTerminate does not decrease the instances counter so when we create/terminate threads, the number of instances keep growing to the limit and we cannot create new threads even if we terminated them all.

**To Reproduce**
Create/terminate threads.

**Expected behavior**
We should be able to have as many threads as specified during the osThreadDef instanciation.

**Impact**
No more threads can be created.

**Logs and console output**
NA

**Environment (please complete the following information):**
Any

**Additional context**
Please find my patch attached.
[0003-Fix-CMSIS-threads-creation-removal.patch.gz](https://github.com/zephyrproject-rtos/zephyr/files/6867432/0003-Fix-CMSIS-threads-creation-removal.patch.gz)

### PR DESCRIPTION
**Pull request by chen-png**
osThreadTerminate doesn't decrease the instances number,
so when it gets to it's limit defined in osThreadDef,
even we use osThreadTerminate to kill a thread, we
can't use osThreadCreate to create thread any more.

So add an array into struct osThreadDef_t to indicate whether the
thread is used or not, then we can get the first available thread
by searching this array when creating a new thread, and update this
array to add a free thread when terminating a thread.

fix: #37159 

Signed-off-by: Chen Peng1 <peng1.chen@intel.com>

### CODE REVIEW

**Review by dcpleung — CHANGES_REQUESTED** [review]
This would not work correctly. `thread_def->instances` is being used as a index to `cm_thread` array when creating new thread in `osThreadCreate`. So if you create 5 threads (and max 5 threads), and decide to terminate thread #2 (== `cm_thread[2]`). When you create a new thread again, it will create a new thread object at `cm_thread[0]` since your code increment the `->instances`. This overwrites an active thread object.

See comments in https://github.com/zephyrproject-rtos/zephyr/issues/23062.

**Comment by chen-png** [comment]
> This would not work correctly. 

@dcpleung you are right, we can't only decrease the instances number, we need to find a way to reuse the thread objects and stack, otherwise, it will cause issues that a thread was used twice.

could you give some suggestions about how to solve this? I found that in #23062 you mentioned, it plans to use memory slab to manage thread objects and stack, is this ok for this? thanks.

**Comment by dcpleung** [comment]
Alternative to using memslab, maybe use a linked list of free instances? Grab one from the list when creating a new thread, and return a freed thread instance back to the list.

**Comment by chen-png** [comment]
hi @dcpleung could you take a look of this ? Based on your suggestions, I added a list to store unused instance.

File: subsys/portability/cmsis_rtos_v1/cmsis_thread.c [hunk 1]
```diff
@@ -164,6 +186,14 @@ osStatus osThreadTerminate(osThreadId thread_id)
 	}
 
 	k_thread_abort((k_tid_t)thread_id);
+
+	node  = (struct inst_node *)k_malloc(sizeof(struct inst_node));
```
Comment (dcpleung) [inline subsys/portability/cmsis_rtos_v1/cmsis_thread.c:190]: If the system runs out of memory, you will no longer be able to terminate a thread. That's why the original suggestion of using memslab. The number of instances is known at build time, so you can define a memslab with a large enough buffer. If you still want to use linked list, you will need to pre-allocate all the nodes.

File: subsys/portability/cmsis_rtos_v1/cmsis_thread.c [hunk 2]
```diff
@@ -29,6 +34,8 @@ static inline uint32_t cmsis_to_zephyr_priority(int32_t c_prio)
 
 static void zephyr_thread_wrapper(void *arg1, void *arg2, void *arg3)
 {
+	k_thread_custom_data_set(arg2);
```
Comment (dcpleung) [inline subsys/portability/cmsis_rtos_v1/cmsis_thread.c:37]: The application can set custom data and overrides this. So this cannot be used to store instance number.

File: subsys/portability/cmsis_rtos_v1/cmsis_thread.c [hunk 3]
```diff
@@ -179,3 +209,15 @@ osStatus osThreadYield(void)
 	k_yield();
 	return osOK;
 }
+
+osStatus osThreadInstListInit(const osThreadDef_t *thread_def)
```
Comment (dcpleung) [inline subsys/portability/cmsis_rtos_v1/cmsis_thread.c:213]: `osThread*` are CMSIS API which are pre-defined. Please rework to avoid adding new APIs.

**Review by dcpleung — CHANGES_REQUESTED** [review]

File: subsys/portability/cmsis_rtos_v1/cmsis_thread.c (hunk 1 above)
Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: hi @dcpleung I updated my code to use k_mem_slab to manage thread and stack, but when I ran  tests/subsys/portability/cmsis_rtos_v1/ on qemu_x86, it **met a stack overflow error, Could you help take a look of code**? I don't know why it reported this error, thanks.

> START - test_thread_apis
E: Page fault at address 0x137c98 (error code 0x3)
**E: Access violation: supervisor thread not allowed to write**
E: PTE: 0x137000 -> 0x0000000000137000: A D XD
E: RAX: 0x00000000001024bd RBX: 0x0000000000137c50 RCX: 0x0000000000000000 RDX: 0x8000000000137a61
E: RSI: 0x0000000000000000 RDI: 0x0000000000137c50 RBP: 0x000000000011a280 RSP: 0x000000000011a250
E:  R8: 0x0000000000000001  R9: 0x000000000013e9b8 R10: 0x0000000000000000 R11: 0x0000000000000000
E: R12: 0x0000000000138c48 R13: 0x0000000000000000 R14: 0x0000000000000000 R15: 0x0000000000105938
E: RSP: 0x000000000011a250 RFLAGS: 0x0000000000000206 CS: 0x0018 CR3: 0x0000000000142000
E: RIP: 0x00000000001057b2
E: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Current thread: 0x114200 (test_thread_apis)
E: Halting system

Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: I checked the thread_object_slabs and thread_stack_slabs, they were initialized successfully, and when running osThreadCreate, it could get an valid thread and stack from mem slab, but it always failed at k_thread_create.

Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: @dcpleung Could you tell me how to free the stack of specified thread in osThreadTerminate?
for the stack overflow error, I found the possible reason is that the thread stack must be defined using K_THREAD_STACK_DEFINE or K_THREAD_STACK_ARRAY_DEFINE when creating a thread, so I defined a thread stack array using macro, and used another function to invoke k_mem_slab_init to initialize my stack slabs, but I met another problem, I don't know how to free the stack of specified thread in osThreadTerminate

Comment (dcpleung) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: The thread stacks are defined with `osThreadDef()` so there is no need do allocation in `osThreadCreate()`. Remove the thread_stack_slab first and see how it goes.

Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: @dcpleung  yes, thread stacks are defined by K_THREAD_STACK_ARRAY_DEFINE in osThreadDef, but if I use this stack array, when I terminate a thread to create a new thread, I need to use another way to find an available stack space. So I decided to use mem slab to manage thread stack too.

Comment (dcpleung) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: That may be caused by kernel object permission. Please don't simply grant permission to those mem_slab as that would create security hole. This issue might need another approach.

Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: @dcpleung I found that the main problem is that when enabling HW_STACK_PROTECTION on x86, we will reserve a 4K stack size which will be used for stack overflow guard, it's with read-only access, but this space doesn't have been released when the thread exits, it's still existed with read-only, so if I want to return it to a mem slab, it will report a stack access error.
it's the old issue, see #29499

**Comment by chen-png** [comment]
@carlescufi @galak @MaureenHelm @nashif Could you help review this? thanks.

File: include/portability/cmsis_os.h [hunk 4]
```diff
@@ -163,15 +164,19 @@ typedef struct os_mailQ_cb *osMailQId;
...
+	uint32_t               instances;
+	/* stack size requirements in bytes; 0 is default stack size */
+	uint32_t               stacksize;
+	void                  *stack_mem;    /* pointer to array of stack memory */
+	struct k_thread       *cm_thread;    /* pointer to k_thread structure */
+	struct k_poll_signal *poll_signal;
+	struct k_poll_event   *poll_event;
+	int32_t            signal_results;
+	/* a bitarray used to indicate whther the thread is used or not, 0: unused, 1: used */
+	void                        *mask;
```
Comment (LeiW000) [inline include/portability/cmsis_os.h:179]: Is it better to rename it with "statusmask" ?

**Review by LeiW000 — CHANGES_REQUESTED** [review]

File: include/portability/cmsis_os.h (hunk 4 above)
Comment (chen-png) [reply include/portability/cmsis_os.h]: yes, I updated it to use status_mask.

**Review by LeiW000 — APPROVED** [review]

File: subsys/portability/cmsis_rtos_v1/cmsis_thread.c [hunk 5]
```diff
@@ -164,6 +175,20 @@ osStatus osThreadTerminate(osThreadId thread_id)
 	}
 
 	k_thread_abort((k_tid_t)thread_id);
+
+	/* get instance index according to thread stack start address */
+	osThreadDef_t *thread_def =
+		(osThreadDef_t *)(k_thread_custom_data_get());
```
Comment (dcpleung) [inline subsys/portability/cmsis_rtos_v1/cmsis_thread.c:181]: Custom data can be set outside of CMSIS via `k_thread_custom_data_set()`, which is a public API. Once that function is called, the `thread_def` pointer is no longer valid. So please find another way of retrieving this data. Also, please remove the `k_thread_custom_data_set()` above.

**Review by dcpleung — CHANGES_REQUESTED** [review]

File: subsys/portability/cmsis_rtos_v1/cmsis_thread.c (hunk 5 above)
Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c:181]: @dcpleung  yes, thanks for your point, I agree with you, we can't use custom_data of thread as the reference to terminate threads, because it will be easily changed and cause some issues. . i.e the osThreadTerminate(id1) doesn't work as expected in the code below, it tries to free id1 in the os_thread_def_thread2, this is incorrect.

> id1 = osThreadCreate(osThread(thread1), NULL);
> id2 = osThreadCreate(osThread(thread2), NULL);
> osThreadTerminate(id1)

but according to cmsis rtos doc, the osThreadTerminate API shall be consistent, so if I want to free a thread instance just by struct k_thread, the easiest way is to ****add a new configurable pointer variable into struct k_thread** using config like if enabling CONFIG_CMSIS_RTOS_V1, and make this variable point to it's source os_thread_def struct**, this method should work, but I am not sure whether this is an appropriate way, could you give some advice on this? thanks.

and for the k_thread_custom_data_set(), it was existed in osThreadCreate function of original code, because this was designed to find source os_thread_def of current thread in osSignalWait.

Comment (dcpleung) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c:181]: Hm... let's focus on getting the instance counter working first. For now, keep using custom data for now and file an enhancement issue on fixing it.

Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c:181]: @dcpleung  as I understand, I can release thread instance resource in osThreadTerminate for terminating those active threads, but threads can also be terminated by just returning from its thread function, then where should I release instance for them?

Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: I tried to add thread instance release operation into low level k_thread_abort function. because no matter whether a thread was terminated by other threads or returning from its thread function, they all should release its thread instance.

Comment (dcpleung) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: Hm... I think that's probably a good place to do clean up. Can you also add some tests for this scenairo?

Comment (chen-png) [reply subsys/portability/cmsis_rtos_v1/cmsis_thread.c]: @dcpleung yes, I added a test in existing "tests/subsys/portability/cmsis_rtos_v1/src/thread_instance.c" to verify this.
terminate a thread after thread instances get to its limit, then create a new thread and check whether the new thread could be created successfully and whether the thread instance address is the same as the terminated thread.

**Comment by chen-png** [comment]
I think we can ignore the CI compliance check failure.
the CI compliance check failure is due to that I want to keep same comment style in the file, so the code I changed used the same comment style as the rest of the file, but that comment style is not allowed by current CI check.

**Review by dcpleung — APPROVED** [review]
