### PR TITLE
Bluetooth: audio: Accept empty CCID list

### LINKED ISSUE #59666: LE Audio: Allow empty-len assigned number values with varies size
**Describe the bug**
Some LE Audio assigned numbers such as the CCID_List has a varies size, as it it `elem_cnt * elem_size` where `elem_cnt` may be 0. 

This issue is apparent in several tests, samples and may also appear in the stack. 

**To Reproduce**
N/A

**Expected behavior**
We should allow e.g. metadata with data_len = 0 for the data types with varies lenght. 

**Impact**
None

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 80a986f43890273bbd0bf4e2da903089b2d821b9

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by MariuszSkamra**
The CCID list can be empty, as the Assigned Numbers is not strict regarding it's minimum length.

Fixes: #59666

### CODE REVIEW

File: samples/bluetooth/hap_ha/src/bap_unicast_sr.c [hunk 1]
```diff
@@ -297,13 +297,8 @@ static bool valid_metadata_type(uint8_t type, uint8_t len)
...
 		return true;
-	case BT_AUDIO_METADATA_TYPE_CCID_LIST: /* 2 - 254 octets */
-		if (len < 2) {
-			return false;
-		}
-
-		return true;
-	case BT_AUDIO_METADATA_TYPE_PROGRAM_INFO: /* 0 - 255 octets */
+	case BT_AUDIO_METADATA_TYPE_CCID_LIST:
+\	case BT_AUDIO_METADATA_TYPE_PROGRAM_INFO: /* 0 - 255 octets */
```
Comment (pdgendt) [inline samples/bluetooth/hap_ha/src/bap_unicast_sr.c:301]:
```suggestion
	case BT_AUDIO_METADATA_TYPE_PROGRAM_INFO: /* 0 - 255 octets */
```

**Comment by Thalley** [comment]
@MariuszSkamra this fixes https://github.com/zephyrproject-rtos/zephyr/issues/59666 - Can you add it to the PR description? 

I was looking at the extended and vendor metadata as well. They are defined as 
image

While our checks are checking for `len < 1`. I think we can agree that the first octet shall always be present, but since the assigned numbers specifically mentions `Octet 2-254`, does that imply that the size of extended and vendor metadata shall be at least 1 (besides the type/company ID)? i.e. should the `len < 1` be `len < 2` for those?

**Comment by MariuszSkamra** [comment]
> While our checks are checking for `len < 1`. I think we can agree that the first octet shall always be present, but since the assigned numbers specifically mentions `Octet 2-254`, does that imply that the size of extended and vendor metadata shall be at least 1 (besides the type/company ID)? i.e. should the `len < 1` be `len < 2` for those?

That's tricky but I think at least `Extended Metadata Type`/`Company_ID` should be there meaning the `Value` should be at least 2 bytes. I'll send PR for that

**Review by Thalley — APPROVED** [review]

**Review by larsgk — APPROVED** [review]
