### PR TITLE
Fix LLDP packet format

### LINKED ISSUE #25184: lldp: lldp_send includes bug
Hi,

I am enable lldp in my env, after fixing the following bug it seem working
https://github.com/zephyrproject-rtos/zephyr/issues/25084

but while I am using optional lldp fields it isn't.

according to lldp_send:
> 	if (lldp->optional_du && lldp->optional_len) {
> 		if (!net_pkt_write(pkt, (u8_t *)lldp->optional_du,
> 				   lldp->optional_len)) {
> 			net_pkt_unref(pkt);
> 			ret = -ENOMEM;
> 			goto out;
> 		}
> 	}

why net_pkt_write with '!' before? if everything good net_pkt_write return 0.
if I remove the '!' it is working fine.

Environment:
    Zephyr SDK
    Commit SHA :6933248e0cb4f7af31e2bab5b39c594806ab53ac

Thanks,
Ehud

### PR DESCRIPTION
**Pull request by jukkar**
The LLDP net_pkt was not created as the code did not properly check the return value of net_pkt_write() call.

Fixes #25184

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]
stuff like that are never caught since we don't have lldp unit tests

**Comment by jukkar** [comment]
> stuff like that are never caught since we don't have lldp unit tests

Yep, the LLDP stuff was bitrotted. We could now have tests for it using the docker image that @pfl created. @laperie can you allocate some task for this?

File: samples/net/lldp/src/main.c [hunk 1]
```diff
@@ -188,8 +195,19 @@ static enum net_verdict parse_lldp(struct net_if *iface, struct net_pkt *pkt)
...
 {
-	if (init_vlan() < 0) {
-		LOG_ERR("Cannot setup VLAN");
+	enum ethernet_hw_caps caps;
+	int ret;
+
+	ret = init_vlan();
+	if (ret < 0) {
+		LOG_ERR("Cannot setup VLAN (%d)", ret);
+	}
```
Comment (pfl) [inline samples/net/lldp/src/main.c:204]: So if VLANs are not created, < 0 is returned, and it is enough to log an error? Even without VLANs verything is fine and the sample can work?

Comment (jukkar) [reply samples/net/lldp/src/main.c:204]: The VLANs are just optional here, the LLDP will work just fine without it. I just noticed that if VLANs are not supported by the eth driver (like in qemu_x86 and e1000), then there was a crash.

Comment (pfl) [reply samples/net/lldp/src/main.c:204]: Maybe only a warning could be logged instead in that case? In the code it looks like it was meant not to work, and the code reviewer is left wondering what was supposed to happen. The crash does not sound like a fun thing to encounter, either.

Comment (jukkar) [reply samples/net/lldp/src/main.c:204]: Sure, we can print warning. There is no crash after this commit.

**Review by pfl — APPROVED** [review]
