### PR TITLE
Bluetooth: PPCP: Fix not being able to disable configurations

### LINKED ISSUE #15017: Not able to set "0xFFFF No specific value" for GAP PPCP structured data
Currently, it is not possible to set the following parameters to "0xFFFF No specific value" 
CONFIG_BT_PERIPHERAL_PREF_MIN_INT
CONFIG_BT_PERIPHERAL_PREF_MAX_INT
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT
This is required as per the specification document, core v5.0, vol 3, part C, section 12.3 Peripheral preferred connection parameters characteristic.

### PR DESCRIPTION
**Pull request by Vudentz**
The spec allows to disable certain configurations with use of 0xffff,
to restrict the range that can be entered the value 0 is used instead.

As this still enables entering values in the invalid range, 1-5 for
min/max interval, this adds the necessary build checks to prevents
values within this range to be used and at same time check if min
interval is not bigger that max interval.

Fixes #15017

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

File: subsys/bluetooth/host/Kconfig [hunk 1]
```diff
@@ -436,12 +440,13 @@ config BT_PERIPHERAL_PREF_SLAVE_LATENCY
 config BT_PERIPHERAL_PREF_TIMEOUT
 	int "Peripheral preferred supervision timeout in 10ms units"
 	default 42
-	range 10 3200
+	range 0 3200
```
Comment (jhedberg) [inline subsys/bluetooth/host/Kconfig]: I think it'd have been better to change the maximum to 0xffff (the decimal equivalent) instead. That way you don't introduce any code size or runtime overhead (now your solution is adding an an extra branch to each assignment).

File: subsys/bluetooth/host/Kconfig [hunk 2]
```diff
@@ -436,12 +440,13 @@ config BT_PERIPHERAL_PREF_SLAVE_LATENCY
...
 	help
 	  It is up to user to provide valid timeout which pass required minimum
 	  value: in milliseconds it shall be larger than
 	  "(1+ Conn_Latency) * Conn_Interval_Max * 2"
 	  where Conn_Interval_Max is given in milliseconds.
+	  Value 0 disables this configuration.
```
Comment (jhedberg) [inline subsys/bluetooth/host/Kconfig]: I don't think this is accurate. The spec says "no specific value" which is different from "disabled"

File: subsys/bluetooth/host/gatt.c [hunk 3]
```diff
@@ -108,6 +108,14 @@ static ssize_t read_appearance(struct bt_conn *conn,
 }
 
 #if defined (CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS)
+/* This checks if the range entered is valid */
+BUILD_ASSERT(!(CONFIG_BT_PERIPHERAL_PREF_MIN_INT > 0 &&
+	     CONFIG_BT_PERIPHERAL_PREF_MIN_INT < 6));
+BUILD_ASSERT(!(CONFIG_BT_PERIPHERAL_PREF_MAX_INT > 0 &&
+	     CONFIG_BT_PERIPHERAL_PREF_MAX_INT < 6));
+BUILD_ASSERT(CONFIG_BT_PERIPHERAL_PREF_MIN_INT >
+	     CONFIG_BT_PERIPHERAL_PREF_MAX_INT);
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: This last BUILD_ASSERT will not work if both MIN and MAX are set to 0.

File: subsys/bluetooth/host/gatt.c [hunk 4]
```diff
@@ -118,10 +126,13 @@ static ssize_t read_ppcp(struct bt_conn *conn, const struct bt_gatt_attr *attr,
 		uint16_t timeout;
 	} ppcp;
 
-	ppcp.min_int = sys_cpu_to_le16(CONFIG_BT_PERIPHERAL_PREF_MIN_INT);
-	ppcp.max_int = sys_cpu_to_le16(CONFIG_BT_PERIPHERAL_PREF_MAX_INT);
+	ppcp.min_int = sys_cpu_to_le16(CONFIG_BT_PERIPHERAL_PREF_MIN_INT ? :
+				       0xffff);
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: Here's the code-size & runtime overhead I mentioned. If you just allow 0xffff directly in Kconfig you will only insure an overhead for build time but not runtime, and no code size overhead either. You might want to consider changing the Kconfig types from `int` to `hex` if you think it's unfriendly to require the user to specify the decimal value instead of 0xffff.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/Kconfig (hunk 1 above)
Comment (carlescufi) [reply subsys/bluetooth/host/Kconfig]: Is there a way to have multiple ranges in Kconfig? @ulfalizer. Eg:

```
range 0 3200
range 0xffff 0xffff
```

File: subsys/bluetooth/host/gatt.c (hunk 4 above)
Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: Follow-up: most likely the compiler will optimize away the never-taken branch, however I still think it's cleaner if right value comes straight from Kconfig

File: subsys/bluetooth/host/Kconfig (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/Kconfig]: That'd indeed be nice.

Comment (Vudentz) [reply subsys/bluetooth/host/Kconfig]: I though that would not be possible, only the last one will be used.

Comment (jhedberg) [reply subsys/bluetooth/host/Kconfig]: @Vudentz that's what I think as well, however it's a feature worth considering since we're in control of our Kconfig parser. Another possible syntax is to have multiple ranges in a single statement, e.g. `range 10 3200 0xffff 0xfff`. Btw that also gives the idea that we could have a flexible type that accepts both decimal and hex input rather than the current int/hex which only accept one or the other.

File: subsys/bluetooth/host/Kconfig (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/Kconfig]: I assume there is no difference in practice since that means the value is not going to be used, anyway I will use the exact working of the spec.

File: subsys/bluetooth/host/gatt.c (hunk 3 above)
Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Right, I could have fixed that with use of <= but I will change to the full range.

File: subsys/bluetooth/host/Kconfig (hunk 2 above)
Comment (jhedberg) [reply subsys/bluetooth/host/Kconfig]: @Vudentz I was talking here what the values mean to the GATT client that reads them, which is also what the GAP spec wording has in mind, I think. In that sense "use whatever value you want" is more intuitive than "this is disabled". If you look at this from a Kconfig description, then I can understand "disabled" a bit better since it means we're not requesting any specific value. Either way, I'd just stick to the spec wording to avoid confusing people.

**Comment by Vudentz** [comment]
@jhe I hope the last update address all the comments

**Review by carlescufi — APPROVED** [review]
Looks good, thanks

File: subsys/bluetooth/host/gatt.c (hunk 3 above)
Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: Actually this isn't quite right yet: you could have MIN_INT=65535 and then MAX_INT < MIN_INT. So the check should probably be `MIN_INT == 0xffff || MIN_INT <= MAX_INT`, right?

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 5]
```diff
@@ -108,6 +108,16 @@ static ssize_t read_appearance(struct bt_conn *conn,
 }
 
 #if defined (CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS)
+/* This checks if the range entered is valid */
+BUILD_ASSERT(!(CONFIG_BT_PERIPHERAL_PREF_MIN_INT > 3200 &&
+	     CONFIG_BT_PERIPHERAL_PREF_MIN_INT < 0xffff));
+BUILD_ASSERT(!(CONFIG_BT_PERIPHERAL_PREF_MAX_INT > 3200 &&
+	     CONFIG_BT_PERIPHERAL_PREF_MAX_INT < 0xffff));
+BUILD_ASSERT(!(CONFIG_BT_PERIPHERAL_PREF_TIMEOUT > 3200 &&
+	     CONFIG_BT_PERIPHERAL_PREF_MAX_INT < 0xffff));
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c]: Should this be `PREF_TIMEOUT < 0xffff`?

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 3 above)
Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Right, we still need to check for 0xffff separately.

File: subsys/bluetooth/host/gatt.c (hunk 5 above)
Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: @Vudentz did you see this comment? Seems like a copy-paste mistake to me

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/Kconfig [hunk 6]
```diff
@@ -421,12 +421,16 @@ if BT_GAP_PERIPHERAL_PREF_PARAMS
 config BT_PERIPHERAL_PREF_MIN_INT
 	int "Peripheral preferred minimum connection interval in 1.25ms units"
 	default 24
-	range 6 3200
+	range 6 65535
```
Comment (joerchan) [inline subsys/bluetooth/host/Kconfig]: Maybe add another config option, "SPECIFY PREF_MIN"? That way you can specify the value and have range validation, or it will be set to 0xffff?

Comment (Vudentz) [reply subsys/bluetooth/host/Kconfig]: Not sure I follow, or do you mean add a bool config option which enables specifying the value? It is possible to do something like that but Im not sure it is worth it since we would have to add another 3 config option to achieve something similar.

File: subsys/bluetooth/host/gatt.c (hunk 5 above)
Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: This should have been fixed in the latest version.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/Kconfig (hunk 6 above)
Comment (joerchan) [reply subsys/bluetooth/host/Kconfig]: Yes, that is what I meant. It might be a lot of options, but I think it makes it better.
