### PR TITLE
drivers: ethernet: eth_sam_gmac: Fix priority queues

### LINKED ISSUE #22890: IP networking does not work on ATSAME70 Rev. B
**Describe the bug**
IP networking does not work on ATSAME70 Rev. B SoC (tested on `sam_e70_xplained` populated with the Rev. B chip).

**To Reproduce**
1. Go to `samples/net/dhcpv4_client`
2. `mkdir build; cd build`
3. `cmake -GNinja -DBOARD=sam_e70_xplained`
4. `ninja flash`

**Screenshots or console output**
```
[00:00:00.000,000] <inf> i2c_sam_twihs: Device I2C_0 initialized
[00:00:00.001,000] <inf> eth_sam: MAC: fc:c2:3d:0b:c3:26
[00:00:00.001,000] <inf> eth_sam: Queue 0 activated
[00:00:00.001,000] <inf> eth_sam: Queue 1 set to idle
[00:00:00.001,000] <inf> eth_sam: Queue 2 set to idle
[00:00:00.001,000] <inf> eth_sam_phy: Soft Reset of ETH PHY
[00:00:00.091,000] <inf> eth_sam_phy: PHYID: 0x221561 at addr: 0
uart:~$ *** Booting Zephyr OS build v2.2.0-rc1-133-g1736cb79c220  ***
[00:00:02.446,000] <inf> eth_sam_phy: common abilities: speed 100 Mb, full duplex
[00:00:02.451,000] <inf> net_dhcpv4_client_sample: Run dhcpv4 client
uart:~$ net stats

Interface 0x20407640 (Ethernet) [1]
===================================
IPv4 recv      114      sent    5       drop    114     forwarded       0
IP vhlerr      0        hblener 0       lblener 0
IP fragerr     0        chkerr  0       protoer 0
ICMP recv      0        sent    0       drop    0
ICMP typeer    0        chkerr  0
UDP recv       0        sent    0       drop    110
UDP chkerr     0
Bytes received 43175
Bytes sent     0
Processing err 34
uart:~$ net iface

Interface 0x20407640 (Ethernet) [1]
===================================
Link addr : FC:C2:3D:0B:C3:26
MTU       : 1500
Ethernet capabilities supported:
        Virtual LAN
        10 Mbits
        100 Mbits
        Priority queues
IPv4 unicast addresses (max 1):
        <none>
IPv4 multicast addresses (max 1):
        <none>
DHCPv4 lease time : 0
DHCPv4 renew time : 0
DHCPv4 server     : 0.0.0.0
DHCPv4 requested  : 0.0.0.0
DHCPv4 state      : selecting
DHCPv4 attempts   : 3
```

Detailed debug log is available at the following address:
https://gist.github.com/stephanosio/c36e41ba3eecea1724079b8660c42284

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain: Zephyr SDK 0.11.1
 - Commit SHA: 1736cb79c220f02e8a93c29f7c1ba3323aff17c1

### LINKED ISSUE #23035: dhcpv4_client sample not working on sam e70
Hi All,
I flashed dhcpv4_client on SAM E70 and it is not getting any ip address from DHCP Server which is my router.

```
[00:00:00.000,000] <wrn> soc: CIDR mismatch: chip = 0xa1020e01 vs HAL = 0xa1020e00
[00:00:00.000,000] <inf> i2c_sam_twihs: Device I2C_0 initialized
[00:00:00.001,000] <inf> eth_sam: MAC: fc:c2:3d:0b:fc:c7
[00:00:00.001,000] <inf> eth_sam: Queue 0 activated
[00:00:00.001,000] <inf> eth_sam: Queue 1 set to idle
[00:00:00.001,000] <inf> eth_sam: Queue 2 set to idle
[00:00:00.001,000] <inf> eth_sam_phy: Soft Reset of ETH PHY
[00:00:00.091,000] <inf> eth_sam_phy: PHYID: 0x221561 at addr: 0
[00:00:00.091,000] <dbg> eth_sam_phy.phy_sam_gmac_auto_negotiate: Starting ETH PHY auto-negotiate sequence
uart:~$ *** Booting Zephyr OS build zephyr-v2.1.0-1382-gcf89ba33eae9  ***
[00:00:02.215,000] <dbg> eth_sam_phy.phy_sam_gmac_auto_negotiate: PHY auto-negotiate sequence completed
[00:00:02.225,000] <inf> eth_sam_phy: common abilities: speed 100 Mb, full duplex
[00:00:02.225,000] <dbg> net_dhcpv4.net_dhcpv4_init: (0x20400d10): 
[00:00:02.231,000] <inf> net_dhcpv4_client_sample: Run dhcpv4 client
[00:00:02.231,000] <dbg> net_dhcpv4.net_dhcpv4_start: (0x20400d10): iface 0x20407600 state=init
[00:00:02.231,000] <dbg> net_dhcpv4.net_dhcpv4_start: (0x20400d10): wait timeout=1s
[00:00:03.231,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x20400dc4): iface 0x20407600 state=init
[00:00:03.231,000] <dbg> net_dhcpv4.dhcpv4_enter_selecting: (0x20400dc4): enter state=selecting
[00:00:03.231,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x20400dc4): send discover xid=0x5df19e0a timeout=4s
[00:00:03.231,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x20400dc4): Waiting for 4s
[00:00:03.231,000] <dbg> eth_sam.eth_tx: ETH tx
[00:00:07.231,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x20400dc4): iface 0x20407600 state=selecting
[00:00:07.231,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x20400dc4): send discover xid=0x5df19e0b timeout=8s
[00:00:07.231,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x20400dc4): Waiting for 8s
[00:00:15.231,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x20400dc4): send discover xid=0x5df19e0c timeout=16s
[00:00:15.231,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x20400dc4): Waiting for 16s
[00:00:31.231,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x20400dc4): iface 0x20407600 state=selecting
[00:00:31.231,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x20400dc4): send discover xid=0x5df19e0d timeout=32s
[00:00:31.231,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x20400dc4): Waiting for 32s
[00:00:31.658,000] <dbg> eth_sam.queue0_isr: GMAC_ISR=0x00000002
[00:00:31.658,000] <dbg> eth_sam.queue0_isr: rx.w1=0x00004000, tail=0
[00:00:31.658,000] <dbg> eth_sam.frame_get: Frame complete: rx=0x204043a0, tail=2
[00:00:31.658,000] <dbg> eth_sam.eth_rx: ETH rx
[00:00:36.211,000] <dbg> eth_sam.queue0_isr: GMAC_ISR=0x00000002
[00:00:36.211,000] <dbg> eth_sam.queue0_isr: rx.w1=0x00004000, tail=2
[00:00:36.211,000] <dbg> eth_sam.frame_get: Frame complete: rx=0x204043a0, tail=4
[00:00:36.211,000] <dbg> eth_sam.eth_rx: ETH rx
[00:00:37.212,000] <dbg> eth_sam.queue0_isr: GMAC_ISR=0x00000002
[00:00:37.212,000] <dbg> eth_sam.queue0_isr: rx.w1=0x00004000, tail=4
[00:00:37.212,000] <dbg> eth_sam.frame_get: Frame complete: rx=0x204043a0, tail=6
[00:00:37.212,000] <dbg> eth_sam.eth_rx: ETH rx
[00:00:38.212,000] <dbg> eth_sam.queue0_isr: GMAC_ISR=0x00000002
[00:00:38.212,000] <dbg> eth_sam.queue0_isr: rx.w1=0x00004000, tail=6
[00:00:38.212,000] <dbg> eth_sam.frame_get: Frame complete: rx=0x204043a0, tail=8
[00:00:38.212,000] <dbg> eth_sam.eth_rx: ETH rx
[00:00:39.213,000] <dbg> eth_sam.queue0_isr: GMAC_ISR=0x00000002
[00:00:39.213,000] <dbg> eth_sam.queue0_isr: rx.w1=0x00004000, tail=8
[00:00:39.213,000] <dbg> eth_sam.frame_get: Frame complete: rx=0x204043a0, tail=10
[00:00:39.213,000] <dbg> eth_sam.eth_rx: ETH rx

```
It is only in discover stage and not coming out of it. Can anyone provide input on this, will be helpful

uart:~$ net iface show

```
Interface 0x20407600 (Ethernet) [1]
===================================
Link addr : FC:C2:3D:0B:FC:C7
MTU       : 1500
Ethernet capabilities supported:
        Virtual LAN
        10 Mbits
        100 Mbits
        Priority queues
IPv4 unicast addresses (max 1):
        <none>
IPv4 multicast addresses (max 1):
        <none>
DHCPv4 lease time : 0
DHCPv4 renew time : 0
DHCPv4 server     : 0.0.0.0
DHCPv4 requested  : 0.0.0.0
DHCPv4 state      : selecting
DHCPv4 attempts   : 6
uart:~$ 
```

### PR DESCRIPTION
**Pull request by nandojve**
The Atmel SAM SoC with ethernet port uses same GMAC driver. However, there are differences between SoC GMAC implementation. Some SoCs have priority queue and system can configure 0 up to 5, depending of SoC version. This update current GMAC driver adding missing definitions.

I already tested with SAM_V71_XULT using 6 queues [5 pri queues] with samples/net/telnet with DHCP. Ping is working OK using telnet terminal. It needs people to test SAME70[B]. I already tested SAM_V71_XULT as SAMV71**A** variation and seems to works well.

I added Kconfig rules to make sure user can only select proper queue size.

NOTE for SAM4E: Not yet supported.
NOTE for SAME70[B]: https://github.com/zephyrproject-rtos/hal_atmel/pull/7

This work is based on slack discussion this week and the start point was https://github.com/zephyrproject-rtos/zephyr/pull/12711.

This PR supersedes #12711 (closes #12711).

### CODE REVIEW

File: drivers/ethernet/eth_sam_gmac.c [hunk 1]
```diff
@@ -1299,6 +1350,15 @@ static int priority2queue(enum net_priority priority)
...
 		0, 0, 0, 0, 1, 1, 2, 2
+#endif
+#if CONFIG_ETH_SAM_GMAC_QUEUES == 4
+		0, 0, 0, 0, 1, 1, 2, 3
+#endif
+#if CONFIG_ETH_SAM_GMAC_QUEUES == 5
+		0, 0, 0, 0, 1, 2, 3, 4
+#endif
+#if CONFIG_ETH_SAM_GMAC_QUEUES == 6
+		0, 0, 0, 1, 2, 3, 4, 5
```
Comment (nandojve) [inline drivers/ethernet/eth_sam_gmac.c]: I'm not complete sure about this, just add what seems to be a good start.

File: drivers/ethernet/Kconfig.sam_gmac [hunk 2]
```diff
@@ -22,7 +22,12 @@ config ETH_SAM_GMAC_NAME
 config ETH_SAM_GMAC_QUEUES
 	int "Number of hardware TX and RX queues"
 	default 1
-	range 1 3
+	range 1 1 if SOC_SERIES_SAM4E
+	range 1 3 if !SOC_SERIES_SAM4E && \
+		     !SOC_ATMEL_SAME70_REVB && \
+		     !SOC_ATMEL_SAMV71_REVB
+	range 1 6 if SOC_ATMEL_SAME70_REVB || \
+		     SOC_ATMEL_SAMV71_REVB
```
Comment (galak) [inline drivers/ethernet/Kconfig.sam_gmac]: This seems like the kinda thing we should encode in the device tree.

Comment (stephanosio) [reply drivers/ethernet/Kconfig.sam_gmac]: @galak Agreed.

@nandojve On second thought, since not initialising all priority queues create DMA problems and this is therefore not really "configurable", device tree would be a better place for this to go in.

Comment (nandojve) [reply drivers/ethernet/Kconfig.sam_gmac]: > @nandojve On second thought, since not initialising all priority queues create DMA problems and this is therefore not really "configurable", device tree would be a better place for this to go in.

This configure the number of HW queues that app will use. The intention is save memory for small applications and it's a SW configuration.

The DMA problem was fixed by right definition on  **drivers/ethernet/eth_sam_gmac_priv.h** by @dgloeck. On top of it, I complemented to make sure devices with 1 queue will work too. Now, system initialize all queues always but properly select the active and inactive ones.

My intention was not create anything new, just fix! I'm open to do changes here if necessary.

Comment (nandojve) [reply drivers/ethernet/Kconfig.sam_gmac]: > This seems like the kinda thing we should encode in the device tree.

I'm not complete aware about DT power on Zephyr but my first thought was: we need diferentiate variations A from B, we will duplicate all DT definitions to add this entry, that entry will not be used for any code generation and we need that information on Kconfig. The user will not be allowed to change it and this will be a long path just to drop 3 range definitions that already uses symbols from Kconfig.

This is a WIP, so if we need to change it, we will do. In this particular case, I'll try to make sure we are on the right path because things are a little _gray_ for me if we need use DT here.

What is the best in this case, keep it or move to DT?

Comment (stephanosio) [reply drivers/ethernet/Kconfig.sam_gmac]: > The DMA problem was fixed by right definition on **drivers/ethernet/eth_sam_gmac_priv.h** by @dgloeck. On top of it, I complemented to make sure devices with 1 queue will work too. Now, system initialize all queues always but properly select the active and inactive ones.

In that case, this is indeed configurable and should stay as a Kconfig symbol.

Ideally, the device tree should specify the (maximum) number of queues supported in the hardware (i.e. `GMAC_QUEUE_NUM`), and the `ETH_SAM_GMAC_QUEUES` Kconfig symbol should specify the number of queues activated/used.

Noting that there is currently no GMAC definition in the dts for some reason, I suppose we could keep this Kconfig symbol with the emphasis that it refers to the "number of **active** hardware TX and RX queues," and add GMAC DT binding/instances later in a separate PR.

File: drivers/ethernet/Kconfig.sam_gmac [hunk 3]
```diff
@@ -22,7 +22,12 @@ config ETH_SAM_GMAC_NAME
 config ETH_SAM_GMAC_QUEUES
 	int "Number of hardware TX and RX queues"
```
Comment (stephanosio) [inline drivers/ethernet/Kconfig.sam_gmac]: This Kconfig symbol specifies the "Number of **active** hardware TX and RX queues".

The maximum number of hardware TX and RX queues supported should be specified in the device tree.

File: drivers/ethernet/Kconfig.sam_gmac (hunk 2 above)
Comment (stephanosio) [inline drivers/ethernet/Kconfig.sam_gmac]: When the DT adds the value for the maximum number of hardware TX and RX queues supported in the future, that value should be used to specify the range.

File: drivers/ethernet/eth_sam_gmac_priv.h [hunk 4]
```diff
@@ -31,7 +31,17 @@
...
 #define GMAC_DESC_ALIGNMENT               4
 /** Total number of queues supported by GMAC hardware module */
-#define GMAC_QUEUE_NO                     3
+#if defined(CONFIG_SOC_ATMEL_SAME70_REVB) || \
+	defined(CONFIG_SOC_ATMEL_SAMV71_REVB)
+#define GMAC_QUEUE_NUM                    6
+#elif !defined(CONFIG_SOC_SERIES_SAM4E)
+#define GMAC_QUEUE_NUM                    3
+#else
+#define GMAC_QUEUE_NUM                    1
```
Comment (stephanosio) [inline drivers/ethernet/eth_sam_gmac_priv.h]: This value should eventually be derived from the device tree.

File: drivers/ethernet/Kconfig.sam_gmac (hunk 2 above)
Comment (nandojve) [reply drivers/ethernet/Kconfig.sam_gmac]: Sounds perfect! May I suggest create a enhanced. So, we can step back think the best way to do it. Maybe can it be done for 2.3? So, we fix now but get compromisse to solve for next release. You can assign it to me. We don't need to be in rush let's just focus on bug fix.

What do you think?

Comment (stephanosio) [reply drivers/ethernet/Kconfig.sam_gmac]: @nandojve I have opened the issue #22997 for adding the GMAC device tree definition.

I agree that we should focus on the bugfix for now and try to get this PR in for 2.2.

**Comment by nandojve** [comment]
The work with queues is done! The remaining work related to DT will be addressed on #22997 and SAM4E fix and activation on #23031 just waiting this PR be merged.

**Review by stephanosio — APPROVED** [review]
Verified working on SAM E70 Rev. B.

**Review by MaureenHelm — APPROVED** [review]

File: drivers/ethernet/eth_sam_gmac_priv.h [hunk 5]
```diff
@@ -31,7 +31,19 @@
...
+#endif
+#define GMAC_QUEUE_PRI_NUM                (GMAC_QUEUE_NUM - 1)
+#if (GMAC_QUEUE_NUM > 1)
+BUILD_ASSERT_MSG(ARRAY_SIZE(GMAC->GMAC_TBQBAPQ) + 1 == GMAC_QUEUE_NUM,
+		 "GMAC_QUEUE_NUM doesn't match soc header");
+#endif
 /** Number of priority queues used */
 #define GMAC_PRIORITY_QUEUE_NO            (CONFIG_ETH_SAM_GMAC_QUEUES - 1)
```
Comment (mnkp) [inline drivers/ethernet/eth_sam_gmac_priv.h]: We renamed `GMAC_QUEUE_NO` to `GMAC_QUEUE_NUM`. We probably should also rename `GMAC_PRIORITY_QUEUE_NO` to `GMAC_PRIORITY_QUEUE_NUM`.

File: drivers/ethernet/eth_sam_gmac_priv.h [hunk 6]
```diff
@@ -142,11 +178,30 @@
...
 	GMAC_QUE_1,  /** Priority queue 1 */
 	GMAC_QUE_2,  /** Priority queue 2 */
+#endif
+#if defined(CONFIG_SOC_ATMEL_SAME70_REVB) || \
+	defined(CONFIG_SOC_ATMEL_SAMV71_REVB)
+	GMAC_QUE_3,  /** Priority queue 3 */
+	GMAC_QUE_4,  /** Priority queue 4 */
+	GMAC_QUE_5,  /** Priority queue 5 */
+#endif
 };
```
Comment (mnkp) [inline drivers/ethernet/eth_sam_gmac_priv.h]: This enum might have outlived its usefulness. The only place where it's used now is the initialization of `queue_list`, as in
```
	.que_idx = GMAC_QUE_3,
```
Here, an integer literal would be just as readable.

**Review by mnkp — CHANGES_REQUESTED** [review]
LGTM, I do have however some comments related to style.

File: drivers/ethernet/eth_sam_gmac_priv.h (hunk 5 above)
Comment (stephanosio) [reply drivers/ethernet/eth_sam_gmac_priv.h]: This naming scheme is quite confusing indeed.

`GMAC_QUEUE_NUM` and `GMAC_QUEUE_PRI_NUM` refer to "the number of (priority) queues supported in hardware", whereas `GMAC_PRIORITY_QUEUE_NO` refers to "the number of active/used (priority) queues."

I think we should just rename `GMAC_PRIORITY_QUEUE_NO` to something like `GMAC_ACTIVE_PRIORITY_QUEUE_NUM` and define `GMAC_ACTIVE_QUEUE_NUM` as `CONFIG_ETH_SAM_GMAC_QUEUES` and use that in place of it as well.

```
#define GMAC_QUEUE_NUM                    ...
#define GMAC_PRIORITY_QUEUE_NUM           (GMAC_QUEUE_NUM - 1)

#define GMAC_ACTIVE_QUEUE_NUM             CONFIG_ETH_SAM_GMAC_QUEUES 
#define GMAC_ACTIVE_PRIORITY_QUEUE_NUM    (GMAC_ACTIVE_QUEUE_NUM - 1)
```

File: drivers/ethernet/eth_sam_gmac.c [hunk 7]
```diff
@@ -75,49 +75,243 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME);
 /* RX descriptors list */
 static struct gmac_desc rx_desc_que0[MAIN_QUEUE_RX_DESC_COUNT]
 	__nocache __aligned(GMAC_DESC_ALIGNMENT);
+#if GMAC_QUEUE_NUM > 1
```
[the remark this answers is not in the document]
Comment (stephanosio) [reply drivers/ethernet/eth_sam_gmac.c]: I have already done this in #23045, but we should handle all queue number variations here (i.e. `GMAC_QUEUE_NUM` = 3, 5, 6).

Although such a device does not exist at this time (as far as we know, that is), there could be one in the future and the current implementation will cause an insane behaviour in that case).

File: drivers/ethernet/eth_sam_gmac.c [hunk 8]
```diff
@@ -75,49 +75,243 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME);
...
 static struct gmac_desc rx_desc_que1[PRIORITY_QUEUE1_RX_DESC_COUNT]
 	__nocache __aligned(GMAC_DESC_ALIGNMENT);
 static struct gmac_desc rx_desc_que2[PRIORITY_QUEUE2_RX_DESC_COUNT]
 	__nocache __aligned(GMAC_DESC_ALIGNMENT);
+#endif
+#if GMAC_QUEUE_NUM > 3
+static struct gmac_desc rx_desc_que3[PRIORITY_QUEUE3_RX_DESC_COUNT]
+	__nocache __aligned(GMAC_DESC_ALIGNMENT);
```
[the remark this answers is not in the document]
Comment (stephanosio) [reply drivers/ethernet/eth_sam_gmac.c]: I believe that is being addressed in #23031 (in particular, https://github.com/zephyrproject-rtos/zephyr/pull/23031/commits/5e4074aae800e5f277d7a205382aef3d2e7fbecb).

Since there is currently no SAM 4E GMAC support (without #23031), this should not be an issue as far as this PR (bugfix) is concerned.

File: drivers/ethernet/eth_sam_gmac.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (stephanosio) [reply drivers/ethernet/eth_sam_gmac.c]: One more thing: some declaration ifdefs use, "**total** queue count" and others use "**priority** queue count." I suppose this is because we only have "priority queue count" for the active.

Once we addressed the define naming issue (https://github.com/zephyrproject-rtos/zephyr/pull/22961/files#r383596823), we should use only one variant- preferably, the total queue count.

File: drivers/ethernet/eth_sam_gmac.c [hunk 9]
```diff
@@ -968,16 +1168,12 @@ static int nonpriority_queue_init(Gmac *gmac, struct gmac_queue *queue)
...
-		  /* Transmitter Checksum Generation Offload Enable */
-		| GMAC_DCFGR_TXCOEN
-		  /* Attempt to use INCR4 AHB bursts (Default) */
-		| GMAC_DCFGR_FBLDO_INCR4;
+		/* Receive Buffer Size (defined in multiples of 64 bytes) */
+		GMAC_DCFGR_DRBS(CONFIG_NET_BUF_DATA_SIZE >> 6) |
+		/* Attempt to use INCR4 AHB bursts (Default) */
+		GMAC_DCFGR_FBLDO_INCR4 |
+		/* DMA Queue Flags */
+		GMAC_DMA_QUEUE_FLAGS;
```
[the remark this answers is not in the document]
Comment (stephanosio) [reply drivers/ethernet/eth_sam_gmac.c]: I suppose this is SAM 4E-related change; in that case, it should be part of #23031- not this bugfix PR.

File: drivers/ethernet/eth_sam_gmac.c [hunk 10]
```diff
@@ -2050,6 +2201,85 @@ static struct eth_sam_dev_data eth0_data = {
 			}
 #endif
 #endif
+#endif
+#endif
+#if defined(CONFIG_SOC_ATMEL_SAME70_REVB) || \
+	defined(CONFIG_SOC_ATMEL_SAMV71_REVB)
```
[the remark this answers is not in the document]
Comment (stephanosio) [reply drivers/ethernet/eth_sam_gmac.c]: Same here, we should handle all queue count variations. I have already done that in #23045.
https://github.com/zephyrproject-rtos/zephyr/pull/23045/commits/e5698aaf84051458945e2a680162a2fa1cda913b#diff-4b92059fe54cca181f5572c19a36712cR2169

Once we fix the define names, we should use `GMAC_ACTIVE_QUEUE_NUM` (=`CONFIG_ETH_SAM_GMAC_QUEUES`) here as well.

File: drivers/ethernet/eth_sam_gmac.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac.c]: Add and "Co-authored-by: Stephanos Ioannidis <root@stephanos.io>"

File: drivers/ethernet/eth_sam_gmac.c [hunk 11]
```diff
@@ -991,100 +1187,6 @@ static int nonpriority_queue_init(Gmac *gmac, struct gmac_queue *queue)
...
-{
-	if (queue->que_idx == 0) {
-		return nonpriority_queue_init(gmac, queue);
-	} else if (queue->que_idx <= GMAC_PRIORITY_QUEUE_NO) {
-		return priority_queue_init(gmac, queue);
-	} else {
-		return priority_queue_init_as_idle(gmac, queue);
-	}
-}
-
```
[the remark this answers is not in the document]
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac.c]: The block was moved to allow drop many **defines** on code. As suggested, it was separated from others changes.

File: drivers/ethernet/eth_sam_gmac.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac.c]: It was dropped and will be added to #23031.

File: drivers/ethernet/eth_sam_gmac.c (hunk 10 above)
[the remark this answers is not in the document]
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac.c]: Add and "Co-authored-by: Stephanos Ioannidis root@stephanos.io"

File: drivers/ethernet/eth_sam_gmac_priv.h (hunk 5 above)
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac_priv.h]: Used @stephanosio suggestion.

File: drivers/ethernet/eth_sam_gmac_priv.h (hunk 6 above)
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac_priv.h]: I prefer keep queue_idx for now but removed all preprocessor definitions. There are places that uses GMAC_QUE_1 and GMAC_QUE_2 and maybe we need review it. I took liberty to add some GMAC_QUE_x uses. Anyway, if will be need drop it I will not complain.

File: drivers/ethernet/eth_sam_gmac.c (hunk 8 above)
[the remark this answers is not in the document]
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac.c]: I decided to move any non priority queue related change to #23031

File: drivers/ethernet/eth_sam_gmac.c [hunk 12]
```diff
@@ -857,12 +1071,10 @@ static int gmac_init(Gmac *gmac, u32_t gmac_ncfgr_val)
 
 	/* Disable all interrupts */
 	gmac->GMAC_IDR = UINT32_MAX;
-	gmac->GMAC_IDRPQ[GMAC_QUE_1 - 1] = UINT32_MAX;
-	gmac->GMAC_IDRPQ[GMAC_QUE_2 - 1] = UINT32_MAX;
 	/* Clear all interrupts */
 	(void)gmac->GMAC_ISR;
-	(void)gmac->GMAC_ISRPQ[GMAC_QUE_1 - 1];
-	(void)gmac->GMAC_ISRPQ[GMAC_QUE_2 - 1];
+	disable_all_queue_interrupt(gmac);
```
Comment (mnkp) [inline drivers/ethernet/eth_sam_gmac.c]: The name of the function should actually be `disable_all_priority_queue_interrupt` since 
```
	gmac->GMAC_IDR = UINT32_MAX;
	(void)gmac->GMAC_ISR;
```
is not included in `disable_all_queue_interrupt`.

File: drivers/ethernet/eth_sam_gmac.c [hunk 13]
```diff
@@ -75,49 +75,269 @@ LOG_MODULE_REGISTER(LOG_MODULE_NAME);
...
+		gmac->GMAC_RBQBAPQ[queue->que_idx - 1] =
+			(u32_t)queue->rx_desc_list.buf;
+	}
+}
+
+static inline void disable_all_queue_interrupt(Gmac *gmac)
+{
+	u32_t idx;
+
+	for (idx = GMAC_QUE_0; idx < GMAC_PRIORITY_QUEUE_NUM; idx++) {
```
Comment (mnkp) [inline drivers/ethernet/eth_sam_gmac.c]: We shouldn't use `GMAC_QUE_0` as it is not a priority queue. Better to simply use `0`.

**Review by mnkp — APPROVED** [review]
Sorry for the late review. I have two minor non-blocking comments. I won't be able to re-review the code in the next few days in case there are changes.

File: drivers/ethernet/eth_sam_gmac.c (hunk 12 above)
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac.c]: Fixed on 821170d

File: drivers/ethernet/eth_sam_gmac.c (hunk 13 above)
Comment (nandojve) [reply drivers/ethernet/eth_sam_gmac.c]: Good catch thank you! Fixed on 821170d!

**Comment by stephanosio** [comment]
@jhedberg Could we merge this for 2.2? Without this patch, the revision B SAM7 series devices (which all newly produced SAM7s are) cannot transmit Ethernet packets.

**Comment by jhedberg** [comment]
> @jhedberg Could we merge this for 2.2? Without this patch, the revision B SAM7 series devices (which all newly produced SAM7s are) cannot transmit Ethernet packets.

Could you explain first what's going on with the linked issues. Both of them are closed, so exactly what GitHub issue is this fixing?

**Comment by stephanosio** [comment]
> > @jhedberg Could we merge this for 2.2? Without this patch, the revision B SAM7 series devices (which all newly produced SAM7s are) cannot transmit Ethernet packets.
> 
> Could you explain first what's going on with the linked issues. Both of them are closed, so exactly what GitHub issue is this fixing?

@jhedberg Those issues should not have been closed, as the problem described there was not fixed (though both issues were more of a "question" that a proper "bug report").

This PR fixes the problem reported in #22890 and #23035.
