### PR TITLE
drivers: udc_nrf: submit UDC_EVT_VBUS_READ if VBUS is still present

### LINKED ISSUE #101420: USB next udc nrf shutdown
### Describe the bug

As the USB peripherals provides features to detect the USB bus and then enable the USB peripheral it's one of the ways to enable the USB device. The same approach is taken in Zephyrs samples for USB (if device provides such mechanism enable peripheral on VBUS notification).

On NRF5340 chip I have observed that the USB device does not get up after calling `usbd_disable()` and `usbd_shutdown()`.  ~~As I found out it is related to not cleaning the VBUSDETECT bit in the USBREGULATORE register.~~

The code checks if the chip has the possibility to detect the VBUS and waits for the notification while no notification is generated as the chip thinks the notification was given.

~~Cleaning provided bit was enough to get it working. After reenabling the device I assume that it has no configuration or any state from previous 'session'. To get it working without any modification it requires to manually call the `usbd_enable()`.~~

Looks like I have made some mess while working on that - the register I mentioned is RO, so the only working solution is to enable USB manually.

### Regression

- [ ] This is a regression.

### Steps to reproduce

The easiest way to reproduce is to use the hid-keyboard demo and the following lines right after calling the `sample_usbd_init_device`:
`usbd_disable(sample_usbd);usbd_shutdown(sample_usbd);
sample_usbd_init_device();`

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jfischer-no**
When the device is connected to the host, but the application shuts down and initialize USB device again, there will be no UDC_EVT_VBUS_READ event generated from USB VBUS regulator on nRF52840 and nRF5340 controller. We can track the state in the driver and resubmit the event just at the beginning of the initialization. If the device gets disconnected in between, there will be subsequent UDC_EVT_VBUS_REMOVED event. Perhaps it could also be solved in more generic way, but other controllers could behave differently. Also, it could be considered that the application should track the state of the VBUS.

Resolves: #101420

### CODE REVIEW

File: drivers/usb/udc/udc_nrf.c [hunk 1]
```diff
@@ -1474,6 +1475,7 @@ static void udc_nrf_power_handler(nrfx_power_usb_evt_t pwr_evt)
 	case NRFX_POWER_USB_EVT_DETECTED:
 		LOG_DBG("POWER event detected");
 		udc_submit_event(udc_nrf_dev, UDC_EVT_VBUS_READY, 0);
+		vbus_present = true;
```
Comment (josuah) [inline drivers/usb/udc/udc_nrf.c:1478]: I suppose this happens in IRQ, so it is not possible to be interrupted between these two lines, which means no concurrency issue.

**Review by josuah — APPROVED** [review]

File: drivers/usb/udc/udc_nrf.c [hunk 2]
```diff
@@ -1676,6 +1679,10 @@ static int udc_nrf_init(const struct device *dev)
 
 	hfxo_mgr = z_nrf_clock_control_get_onoff(cfg->clock);
 
+	if (vbus_present) {
```
Comment (tmon-nordic) [inline drivers/usb/udc/udc_nrf.c:1682]: There is no mechanism to clear `USBDETECTED` and `USBREMOVED` events in nrfx, therefore this duck-taped boolean variable is probably the only reasonable solution for the time being.

I believe the proper solution would be something like:
```pseudocode
	clear_event(USBREMOVED);
	if (nrfx_power_usbstatus_get() != NRFX_POWER_USB_STATE_DISCONNECTED) {
		udc_submit_event(udc_nrf_dev, UDC_EVT_VBUS_READY, 0);
		clear_event(USBDETECTED);
	}
```

Just checking `nrfx_power_usbstatus_get()` without clearing `USBREMOVED` and `USBDETECTED` events would result in double `UDC_EVT_VBUS_READY` submission.

**Review by tmon-nordic — APPROVED** [review]
