### PR TITLE
PM: Fix deadlock and documentation enhancements

### LINKED ISSUE #35480: pm: device_runtime: `pm_device_request` can block forever
**Describe the bug**

The core runtime power management function `pm_device_request` can hang forever with a small amount of bad luck.
The core actions taken by this function are:
```
	(void)k_work_schedule(&dev->pm->work, K_NO_WAIT);
	(void)k_condvar_wait(&dev->pm->condvar, &request_mutex, K_FOREVER);
```

The nuance is that the `condvar` API only unblocks threads that are currently blocked, there is no persistent state like `k_poll_signal`. What this means is that if the thread calling `pm_device_request ` is interrupted between the two function calls above, it is possible (and even likely, given that the system work queue runs at priority -1) that the submitted work item completes (calling `k_condvar_broadcast`) before the submitting thread blocks on the `condvar`. 

As a result, the original call to `pm_device_request` won't return (unless a second thread also runs `pm_device_request` on the same device at a later time).

**To Reproduce**
Simulate another thread interrupting the calling thread by updating `pm_device_request` to contain:
```
	(void)k_work_schedule(&dev->pm->work, K_NO_WAIT);
	k_sleep(K_SECONDS(1));
```
Build and run the device power management sample: `samples/subsys/pm/device_pm`
```
*** Booting Zephyr OS build v2.6.0-rc1-244-gaa78a6473b16  ***
Device PM sample app start
open()
parent resuming..

```
**Expected behavior**
The power management functions should be robust in the face of arbitrary interrupts and rescheduling.

**Environment (please complete the following information):**
 - Zephyr v2.6-rc1

### PR DESCRIPTION
**Pull request by ceolin**
merged https://github.com/zephyrproject-rtos/zephyr/pull/35315 and https://github.com/zephyrproject-rtos/zephyr/pull/35180

### CODE REVIEW

File: subsys/pm/device_runtime.c [hunk 1]
```diff
@@ -127,71 +128,93 @@ static int pm_device_request(const struct device *dev,
...
-		goto out;
+		(void)k_work_schedule(&dev->pm->work, K_NO_WAIT);
+		goto out_unlock;
 	}
 
-	k_mutex_init(&request_mutex);
-	k_mutex_lock(&request_mutex, K_FOREVER);
-	(void)k_condvar_wait(&dev->pm->condvar, &request_mutex, K_FOREVER);
-	k_mutex_unlock(&request_mutex);
+	pm_device_runtime_state_set(dev->pm);
```
Comment (nashif) [inline subsys/pm/device_runtime.c:160]: Setting the state should be based on the condition variable, so this line really needs to be after checking the condition.

File: subsys/pm/device_runtime.c [hunk 2]
```diff
@@ -127,71 +128,93 @@ static int pm_device_request(const struct device *dev,
...
+	(void)k_mutex_unlock(&dev->pm->lock);
```
Comment (nashif) [inline subsys/pm/device_runtime.c:161]: the unlock needs to be after calling wait(). You are mixing locking via a mutex with condition variables here.

File: subsys/pm/device_runtime.c [hunk 3]
```diff
@@ -127,71 +128,93 @@ static int pm_device_request(const struct device *dev,
...
+	pm_device_wait(dev, K_FOREVER);
```
Comment (nashif) [inline subsys/pm/device_runtime.c:162]: I would expand the contents of this function here less the mutex lock/unlock which we already have in place here.

File: subsys/pm/device_runtime.c [hunk 4]
```diff
@@ -127,71 +128,93 @@ static int pm_device_request(const struct device *dev,
...
 
 	/*
 	 * dev->pm->state was set in device_pm_callback(). As the device
 	 * may not have been properly changed to the target_state or another
 	 * thread we check it here before returning.
 	 */
-	ret = target_state == atomic_get(&dev->pm->state) ? 0 : -EIO;
+	(void)k_mutex_lock(&dev->pm->lock, K_FOREVER);
```
Comment (nashif) [inline subsys/pm/device_runtime.c:169]: there will not be a need for this additional lock, we are locked above, so basically it should end up like this:

```

	while ((k_work_delayable_is_pending(&dev->pm->work)) ||
		(dev->pm->state == PM_DEVICE_STATE_SUSPENDING) ||
		(dev->pm->state == PM_DEVICE_STATE_RESUMING)) {
		ret = k_condvar_wait(&dev->pm->condvar, &dev->pm->lock,
			       K_FOREVER);
		if (ret != 0) {
			break;
		}
	}
	pm_device_runtime_state_set(dev->pm);
	/*
	 * dev->pm->state was set in device_pm_callback(). As the device
	 * may not have been properly changed to the target_state or another
	 * thread we check it here before returning.
	 */
	ret = target_state == dev->pm->state ? 0 : -EIO;

out_unlock:
	(void)k_mutex_unlock(&dev->pm->lock);
```


The callback will be called synchronously, so the above should work.

File: subsys/pm/device_runtime.c [hunk 5]
```diff
@@ -127,71 +128,93 @@ static int pm_device_request(const struct device *dev,
...
 						  NULL, NULL);
 		}
-		ret = 0;
 		goto out;
 	}
 
-	(void)k_work_schedule(&dev->pm->work, K_NO_WAIT);
+	(void)k_mutex_lock(&dev->pm->lock, K_FOREVER);
+
+	if (!dev->pm->enable) {
```
Comment (nashif) [inline subsys/pm/device_runtime.c:136]: why does this need to be called with the lock? We could just move the lock below this block.

File: subsys/pm/device_runtime.c [hunk 6]
```diff
@@ -127,71 +128,93 @@ static int pm_device_request(const struct device *dev,
...
+		ret = -ENOTSUP;
+		goto out_unlock;
+	}
+
+	if (target_state == PM_DEVICE_STATE_ACTIVE) {
+		dev->pm->usage++;
+		if (dev->pm->usage < 0) {
```
Comment (nashif) [inline subsys/pm/device_runtime.c:143]: can you add some comments on this condition? When would the usage be negative after incrementing it?

File: subsys/pm/device_runtime.c [hunk 7]
```diff
@@ -127,71 +128,93 @@ static int pm_device_request(const struct device *dev,
...
 
-	(void)k_work_schedule(&dev->pm->work, K_NO_WAIT);
+	(void)k_mutex_lock(&dev->pm->lock, K_FOREVER);
+
+	if (!dev->pm->enable) {
+		ret = -ENOTSUP;
+		goto out_unlock;
+	}
+
+	if (target_state == PM_DEVICE_STATE_ACTIVE) {
```
Comment (nashif) [inline subsys/pm/device_runtime.c:141]: In the synchronous case, what are we increasing usage here and not after checking the condition below and at the same time we are changing the state..?

File: subsys/pm/device_runtime.c [hunk 8]
```diff
@@ -24,7 +24,9 @@ static void device_pm_callback(const struct device *dev,
 {
 	__ASSERT(retval == 0, "Device set power state failed");
 
-	atomic_set(&dev->pm->state, *state);
+	(void)k_mutex_lock(&dev->pm->lock, K_FOREVER);
+	dev->pm->state = *state;
+	(void)k_mutex_unlock(&dev->pm->lock);
```
Comment (nashif) [inline subsys/pm/device_runtime.c:29]: unlock after broadcast.

File: subsys/pm/device_runtime.c (hunk 1 above)
Comment (nashif) [inline subsys/pm/device_runtime.c:160]: everything here is going to be run synchronously, so we do not need to lock/unlock the mutex in both `pm_device_runtime_state_set` and the callback which will be covered by the existing mutex that was taken above.

**Review by nashif — CHANGES_REQUESTED** [review]

File: subsys/pm/device_runtime.c (hunk 4 above)
Comment (ceolin) [reply subsys/pm/device_runtime.c:169]: Ok, let be very clear. This **just** works because we are assuming that the device is doing it synchronous. That is a condition that  we are putting on devices

File: subsys/pm/device_runtime.c (hunk 5 above)
Comment (ceolin) [reply subsys/pm/device_runtime.c:136]: nope, if a different thread disables runtime pm ?

File: subsys/pm/device_runtime.c (hunk 1 above)
Comment (ceolin) [reply subsys/pm/device_runtime.c:160]: it does not to be fair. The state and the queue, that governs async ops, are protected by the mutex and not by the conditional variable. This code assumes that the device can do it asynchronously and because of that we need to wait after the operation (because only from the callback signal we will know that the operation finished). But, I saw the next comment and I got that this is coming from the assumption that devices do it synchronously.

File: subsys/pm/device_runtime.c (hunk 7 above)
Comment (ceolin) [reply subsys/pm/device_runtime.c:141]: which check below you are referring ?

File: subsys/pm/device_runtime.c (hunk 1 above)
Comment (ceolin) [reply subsys/pm/device_runtime.c:160]: pm_device_runtime_state_set is also used by the workqueue, that is why there is a mutex there, as mutex are re-entrant, it is not a problem lock() twice from the same thread (sync path).  Alos,v the callback was not assuming that would run synchronous. Again, in the end all requested changes are based on the assumption that devices do it synchronously.

File: subsys/pm/device_runtime.c (hunk 4 above)
Comment (ceolin) [reply subsys/pm/device_runtime.c:169]: if the device does it asynchronous we may return before the callback be called with a transitional state, RESUMING or SUSPENDING.

File: subsys/pm/device_runtime.c (hunk 8 above)
Comment (ceolin) [reply subsys/pm/device_runtime.c:29]: ok, assuming that this callback will be called by the device in `pm_device_state_set`, the mutex will be locked and not necessary here.

File: subsys/pm/device_runtime.c (hunk 6 above)
Comment (ceolin) [reply subsys/pm/device_runtime.c:143]: That is just because the old implementation was allowing the reference count gets negative due to unbalanced pm_device_put() calls. I just kept this behavior for now.

Comment (ceolin) [reply subsys/pm/device_runtime.c:143]: I think it is fine removing it here though. Just did it.

**Comment by ceolin** [comment]
@nashif  thanks for reviewing it.I think I've addressed the comments in the last two commits that I put on top of this pr. Can you look it again ?

**Review by nashif — APPROVED** [review]

**Review by gmarull — APPROVED** [review]

File: subsys/pm/device_runtime.c (hunk 4 above)
Comment (nashif) [reply subsys/pm/device_runtime.c]: async calls do not get here, they are now being handled by the workqueue. This is something that can be documented, a device driver might also choose not to call the callback at all, which another pitfall.

File: subsys/pm/device_runtime.c (hunk 1 above)
Comment (nashif) [reply subsys/pm/device_runtime.c:160]: agree about mutexes holding a count, but it is still another call that needs to be made which we could save. One more important point to note when we get to async, we can't use mutexes in async calls, mutexes can't be unlocked in ISR context.

File: subsys/pm/device_runtime.c (hunk 7 above)
Comment (nashif) [reply subsys/pm/device_runtime.c:137]: before calling `pm_device_runtime_state_set`

File: subsys/pm/device_runtime.c (hunk 6 above)
Comment (erwango) [reply subsys/pm/device_runtime.c]: I'm not clear on this part neither. Do you plan an update ?
