### PR TITLE
drivers: ethernet: stm32, sam, mcux: correctly set LAA bit

### LINKED ISSUE #16452: drivers: ethernet: stm32, sam, mcux: LAA bit not set
**Describe the bug**
Random generated MAC addresses flip the wrong bit for LAA.
The LAA bit is the second bit in the first OUI byte, not the last byte in the NIC specific part.
Generally all assigned addresses should have the LAA bit set when using the vendo's OUI not only random generated.

**Impact**
MAC address looks like it is UAA address but is LAA.

### PR DESCRIPTION
**Pull request by lowlander**
When randomly generating MAC addresses they will always be
locally administrated addresses, so the LAA bit should be set.
The LAA bit is the 2nd bit of the 1st byte of the MAC address
not the 2nd bit of the 4th byte.

Fixes:  #16452

### CODE REVIEW

File: drivers/ethernet/eth_mcux.c [hunk 1]
```diff
@@ -754,10 +754,11 @@ static void generate_mac(u8_t *mac_addr)
 
 	entropy = sys_rand32_get();
 
+	mac_addr[0] |= 0x02; /* force LAA bit */
+
 	mac_addr[3] = entropy >> 8;
 	mac_addr[4] = entropy >> 16;
-	/* Locally administered, unicast */
-	mac_addr[5] = ((entropy >> 0) & 0xfc) | 0x02;
+	mac_addr[5] = entropy >> 0;
```
Comment (jukkar) [inline drivers/ethernet/eth_mcux.c]: There is LAA bit set in CONFIG_ETH_MCUX_0_UNIQUE_MAC branch below, which sets it to [5] byte, we should probably fix that too in the same go.

**Review by erwango — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
