### PR TITLE
drivers: can: stm32h7: fix message RAM address calculations

### LINKED ISSUE #59624: CAN: STM32H7: can2 interface is not usable
**Describe the bug**
The can2 interface as defined in the STM32H7 device tree is not able to send or receive CAN frames.

I use a custom board, based on the STM32H743VI, with two CAN interfaces and have issues to make them work simultaneously.
I wrote a test program that sets up threads and messages queues, in the same way for each CAN interface (can1 and can2) so that any CAN frame received on one interface is sent back on the same interface while incrementing the first data byte of the payload.

The frames are in the extended format, and the receiving is handled with a filter that accepts all data frames in extended format, and uses a message queue.

Whether I connect the two interfaces together or use a setup with two boards, I always get the same result: can1 is able to send and receive CAN frames while can2 is not.

However, can2 works if I disable the can1 interface and alter the can2 interface definition in the STM32H7 device tree by replacing these two lines:
```
reg = <0x4000a400 0x400>, <0x4000ac00 0x6a0>;
bosch,mram-cfg = <0x350 28 8 3 3 0 3 3>;
```
with these two lines:
```
reg = <0x4000a400 0x400>, <0x4000ac00 0x350>;
bosch,mram-cfg = <0x0 28 8 3 3 0 3 3>;
```

This makes me think there could be an issue in the CAN driver related to the message RAM layout.

**To Reproduce**
- Set the can2 interface to okay in the STM32H7 device tree
- Build an app that receives all extended data frames on can2 and sends them back
- Connect the can2 interface to another working CAN interface that sends extended data frames, while making sure the bus speeds match on the two interfaces
- Observe that no CAN frame is received on CAN2

**Expected behavior**
can2 is able to send and receive CAN frames, while simultaneously using the can1 interface.

**Impact**
can2 is not usable on my board.

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Calculate the Bosch M_CAN Message RAM addresses relative to the Message RAM Base Address (MRBA), not the offset. Add `CAN_MCAN_DT_MRBA()` and `CAN_MCAN_DT_INST_MRBA()` helper macros.
    
Fixes: #59624

### CODE REVIEW

File: include/zephyr/drivers/can/can_mcan.h [hunk 1]
```diff
@@ -573,10 +573,22 @@
...
+ * @brief Get the Bosch M_CAN Message RAM address
+ *
+ * For devicetree nodes with dedicated Message RAM area defined via devicetree, this macro returns
+ * the address of the Message RAM, taking in the Message RAM offset into account.
+ *
+ * @param node_id node identifier
+ * @return the Bosch M_CAN Message RAM address
  */
 #define CAN_MCAN_DT_MRAM_ADDR(node_id)                                                             \
 	(mem_addr_t)(DT_REG_ADDR_BY_NAME(node_id, message_ram) + CAN_MCAN_DT_MRAM_OFFSET(node_id))
```
Comment (martinjaeger) [inline include/zephyr/drivers/can/can_mcan.h:594]: Maybe use the new macro here?

```suggestion
 	CAN_MCAN_DT_MRBA(node_id) + CAN_MCAN_DT_MRAM_OFFSET(node_id))
```

**Review by martinjaeger — DISMISSED** [review]

File: include/zephyr/drivers/can/can_mcan.h (hunk 1 above)
Comment (henrikbrixandersen) [reply include/zephyr/drivers/can/can_mcan.h]: Done.

**Review by martinjaeger — APPROVED** [review]

**Review by str4t0m — APPROVED** [review]

**Review by alexanderwachter — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
