### PR TITLE
Bluetooth: host: Support fragmented L2CAP header

### LINKED ISSUE #26900: Bluetooth: host: bt_conn_recv() assumes ACL data is >= 2 bytes
**Describe the bug**
An new `BT_ACL_START` fragment in `bt_conn_recv()` of less than 2 bytes will have unintended behavior.
The particular line of code with the problem is https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/host/conn.c#L1208:

```c
void bt_conn_recv(struct bt_conn *conn, struct net_buf *buf, uint8_t flags)
{
	struct bt_l2cap_hdr *hdr;
	uint16_t len;

	/* ... */

	switch (flags) {
	case BT_ACL_START:
		hdr = (void *)buf->data;
		len = sys_le16_to_cpu(hdr->len);  /* <== If (buf->len < 2), we read garbage from hdr->len */

	/* ... */
```

A link layer may choose to fragment an L2CAP PDU in any way it sees fit -- including fragmenting the first four bytes (the L2CAP header). I have seen this in the wild, where a Link Layer fragments a 24 byte ATT Read by Group Type Response into two packets (1 + 23 bytes). 

This behavior is tested in the LL/DFL/SLA/BV-02-C and LL/DFL/MAS/BV-02-C Link Layer conformance tests https://www.bluetooth.com/specifications/qualification-test-requirements/.

Here's a relevant section from the Bluetooth Core Specification v5.2, Vol. 3, Part A, section 1.4, table 1.1:

> A part of a PDU, as resulting from a fragmentation operation. Fragments are used only in the delivery of data to and from the lower layer. They are not used for peer-to-peer transportation. A fragment may be a Start or Continuation Fragment with respect to the L2CAP PDU. A fragment does not contain any protocol information beyond the PDU; the distinction of start and continuation fragments is transported by lower layer protocol provisions. Note: Start Fragments always either begin with the first octet of the Basic L2CAP header of a PDU or they have a length of zero (see [Vol 2] Part B, Section 6.6.2).

**Expected behavior**
The host stores the fragment and checks the length field as soon as it has received enough bytes for it to be valid (i.e., 2 bytes).

**Impact**
This will in worst case cause memory corruption, hard faults, buffer overflow attacks (?), etc. As the `conn->rx_len` effectively will be set as a combination of a value from a previously allocated buffer and the first byte in the new PDU.

**Environment (please complete the following information):**
 - Commit SHA or Version used: Current master (36707cd)

### PR DESCRIPTION
**Pull request by thomasstenersen**
Fixes: #26900.

A controller may fragment an L2CAP SDUs in any way it sees fit,
including fragmenting the L2CAP header. Likewise, the receiving
controller may send the fragmented header as ACL data to the host.

The Zephyr host assumed that a `BT_ACL_START` was at least 2 bytes long,
and consequently read the two-byte length field from the buffer without
length checks.

This commit allows the `BT_ACL_START` to be less than two bytes,
updating the `conn->rx_len` onces the `BT_ACL_CONT` with the remaining
part of the length field has been received.

Signed-off-by: Thomas Stenersen <thomas.stenersen@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -1204,14 +1204,36 @@ void bt_conn_recv(struct bt_conn *conn, struct net_buf *buf, uint8_t flags)
 	/* Check packet boundary flags */
 	switch (flags) {
 	case BT_ACL_START:
+		if (conn->rx) {
+			BT_ERR("Unexpected first L2CAP frame");
+			bt_conn_reset_rx_state(conn);
+		}
+
+		if (!buf->len) {
```
Comment (thomasstenersen) [inline subsys/bluetooth/host/conn.c:1212]: I'm a bit unsure whether it is allowed or not for the controller to send zero-length ACL data to the host. The other way is definitely allowed (and is tested in LL conformance tests). In any case, the host shouldn't misbehave if it does receive zero-length ACL data.

Comment (Vudentz) [reply subsys/bluetooth/host/conn.c:1212]: I guess 0 length is also possible, at least I don't see anything on the spec preventing that.

File: subsys/bluetooth/host/conn.c [hunk 2]
```diff
@@ -1223,13 +1245,33 @@ void bt_conn_recv(struct bt_conn *conn, struct net_buf *buf, uint8_t flags)
...
+			BT_DBG("Empty ACL_CONT");
+			net_buf_unref(buf);
+			return;
+		}
+
+		/* Have we received the full length field in the L2CAP header
+		 * yet?
+		 */
+		if (conn->rx->len < sizeof(uint16_t)) {
+			uint16_t len = (conn->rx->data[0] | buf->data[0] << 8);
```
Comment (Vudentz) [inline subsys/bluetooth/host/conn.c:1265]: Not following this one, we will need to keep appending data until there are at least 2 bytes since the start could have 0 bytes there could be necessary to have 2+ rounds to read the entire header if the controller send them one byte at time.

Comment (thomasstenersen) [reply subsys/bluetooth/host/conn.c:1265]: This logic is a bit convoluted, I agree. The possible scenarios are:

- 0-byte START => drop buffer on L1214.
- 1-byte START, 0-byte CONT => drop continuation fragment on L1257.
- 1-byte START, >=1-byte CONT => calculate the `conn->rx_len` as done here
- >1-byte START => Normal case

Any suggestions on how to make it clearer? We can at least move the check for empty buf outside the switch.

Comment (Vudentz) [reply subsys/bluetooth/host/conn.c:1265]: If we drop the buffer at L1214 that means the conn->rx won't be initialized so CONT will cause the Unexpected L2CAP continuation which I guess that needs fixing if we really intend to make this generic. I was actually thinking if it wouldn't be better to reassemble first, problem is there is no flag to indicate end of fragments like there is for ISO which means we need to reconstruct the length while parsing the fragments, perhaps we need to having a separate helper function that does the appending would be better here which we keep calling until there is enough data to set the rx_len.

Comment (thomasstenersen) [reply subsys/bluetooth/host/conn.c:1265]: Right, I see. I'll see if I can clean the logic up a bit.

Comment (thomasstenersen) [reply subsys/bluetooth/host/conn.c]: I added a suggested re-write in https://github.com/zephyrproject-rtos/zephyr/pull/27169/commits/145257454d3bcd17b206b182878aabebda5e6cc3. It should clean up the logic quite a bit.

Comment (thomasstenersen) [reply subsys/bluetooth/host/conn.c]: Did you have a look @Vudentz ? I removed the `[wip]` tag from the commit to let CI run, the commits can be squashed later.
https://github.com/zephyrproject-rtos/zephyr/pull/27169/commits/4adcaafe0b1ccb0bfc3f0968c47c0b7b8e0c9c01

**Comment by thomasstenersen** [comment]
@Vudentz will you get a chance to look at this one some time soon?

File: subsys/bluetooth/host/conn.c [hunk 3]
```diff
@@ -1006,17 +942,33 @@ void bt_conn_recv(struct bt_conn *conn, struct net_buf *buf, uint8_t flags)
...
+		/* Still not enough data recieved to retrieve the L2CAP header
+		 * length field.
+		 */
+		return;
+	}
 
-	if (sizeof(*hdr) + len != buf->len) {
-		BT_ERR("ACL len mismatch (%u != %u)", len, buf->len);
-		net_buf_unref(buf);
+	const struct bt_l2cap_hdr *hdr = (struct bt_l2cap_hdr *)conn->rx->data;
```
Comment (Vudentz) [inline subsys/bluetooth/host/conn.c:952]: Not a big fan of variable declaration in the middle of the function scope, also note that bt_l2cap_hdr contains the cid as well not just the len, so Id would suggest to just skip parsing the header and make bt_l2cap_recv do that using the whole buffer and if the header was not received (lenght <= 1) we should just drop.

File: subsys/bluetooth/host/conn.c [hunk 4]
```diff
@@ -903,40 +899,13 @@ void bt_conn_recv(struct bt_conn *conn, struct net_buf *buf, uint8_t flags)
...
-		BT_DBG("rx_len %u", conn->rx_len);
-		if (conn->rx_len) {
-			conn->rx = buf;
-			return;
-		}
+		BT_DBG("First, len %u final %u", buf->len,
+		       (buf->len < sizeof(uint16_t)) ?
+		       0 :
+		       sys_le16_to_cpu(
+			       ((struct bt_l2cap_hdr *)buf->data)->len));
```
Comment (Vudentz) [inline subsys/bluetooth/host/conn.c:906]: Actually it is just the length that should be read, not bt_l2cap_hdr, so this should probably be something like:

buf->len < sizeof(uint16_t) ? buf->len : sys_le16_to_cpu(buf->data);

Comment (thomasstenersen) [reply subsys/bluetooth/host/conn.c:906]: I originally did this, but changed it to make it clearer that it's the l2cap header length field we're retrieving. No problem switching it back though.

File: subsys/bluetooth/host/conn.c (hunk 3 above)
Comment (thomasstenersen) [reply subsys/bluetooth/host/conn.c:952]: Thanks for taking the time to do another review round 👍 

> note that bt_l2cap_hdr contains the cid as well not just the len, so Id would suggest to just skip parsing the header and make bt_l2cap_recv do that using the whole buffer and if the header was not received (lenght <= 1) we should just drop.

I don't understand what you're asking me to do here. I'm not touching the `cid`, only using the `struct bt_l2cap_hdr` for retrieving the length field and for its size when calculating the total length of the ACL data. We need to parse the length field to know when to propagate the buffer to L2CAP, right? You're not saying you want to split this responsibility of reassembling across here and L2CAP? If you don't like the fact that the `struct bt_l2cap_hdr` type is used, it is possible to do something like

```c
const uint16_t l2cap_len = sys_get_le16(buf->data);
const uint16_t acl_total_len = l2cap_len + sizeof(struct bt_l2cap_hdr);
```
Regarding 
> Not a big fan of variable declaration in the middle of the function scope

Note that we cannot retrieve this length until we know that `buf->len >= 2`, which is not the case at the beginning of the function. Using C89-style would then force us to drop the `const` qualifier to declare a variable that's only used 60+ lines below. If we do strictly follow C89-style, then that's fine, I can declare the variable at the top of the function.

File: subsys/bluetooth/host/conn.c [hunk 5]
```diff
@@ -964,17 +941,32 @@ void bt_conn_recv(struct bt_conn *conn, struct net_buf *buf, uint8_t flags)
...
+		/* Still not enough data recieved to retrieve the L2CAP header
+		 * length field.
+		 */
+		return;
+	}
 
-	if (sizeof(*hdr) + len != buf->len) {
-		BT_ERR("ACL len mismatch (%u != %u)", len, buf->len);
-		net_buf_unref(buf);
+	acl_total_len = sys_get_le16(buf->data) + sizeof(struct bt_l2cap_hdr);
```
Comment (joerchan) [inline subsys/bluetooth/host/conn.c:951]: buf is unref'ed, and length field could be split.
```suggestion
	acl_total_len = sys_get_le16(conn->rx->data) + sizeof(struct bt_l2cap_hdr);
```

**Review by joerchan — CHANGES_REQUESTED** [review]

**Review by joerchan — APPROVED** [review]

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]

**Comment by joerchan** [comment]
@Vudentz Has BT_ISO the same problem with a fragmented header?
