### PR TITLE
drivers: ethernet: phy: vsc8541: fix crash and add interrupt mode

### LINKED ISSUE #107575: drivers: ethernet: phy: vsc8541: exception while entering the monitor thread
### Describe the bug

Initialization and first entry to the monitor thread causes crash on iMXRT1176 MCU. The reason is an incorrectly initialized monitor thread with incorrectly declared thread stack. In current realization the basic `uint8_t` buffer is passed to the `k_thread_create` function, which is [prohibited](https://docs.zephyrproject.org/latest/kernel/services/threads/index.html#thread-stack-objects).

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- Toolchain: Zephyr SDK 1.0.1;
- Zephyr version: 4.4.0;
- MCU: iMXRT1176

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by RobbieKhan**
This pull request fixes and improves PHY driver for Microchip VSC8541 / VSC8531.

- Incorrectly initialized monitor thread, that previously leaded to exception, was replaced by monitor workqueue.
- Added interrupt mode, which effectively uses MDINT pin to catch link change events instead of periodic monitoring.

Fixes #107575.

### CODE REVIEW

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 1]
```diff
@@ -527,6 +484,175 @@ static DEVICE_API(ethphy, mc_vsc8541_phy_api) = {
...
+	}
+
+	ret = gpio_pin_interrupt_configure_dt(&config->interrupt_gpio, GPIO_INT_EDGE_TO_ACTIVE);
+	if (ret) {
+		return ret;
+	}
+
+skip_int_gpio:
+#else /* DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios) */
+	k_work_reschedule(&data->phy_monitor_work, K_NO_WAIT);
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c]: in phy_mc_vsc8541_cfg_link it is rescheduled again

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 2]
```diff
@@ -527,6 +484,175 @@ static DEVICE_API(ethphy, mc_vsc8541_phy_api) = {
...
+	ret = gpio_add_callback_dt(&config->interrupt_gpio, &data->gpio_callback);
+	if (ret) {
+		return ret;
+	}
+
+	ret = gpio_pin_interrupt_configure_dt(&config->interrupt_gpio, GPIO_INT_EDGE_TO_ACTIVE);
+	if (ret) {
+		return ret;
+	}
+
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c]: put this in a separate function

**Review by maass-hamburg — CHANGES_REQUESTED** [review]

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 2 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: @maass-hamburg, done

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 1 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: @maass-hamburg, you are right, thanks. Removed that.

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 3]
```diff
@@ -278,49 +271,47 @@ static int phy_mc_vsc8541_get_speed(const struct device *dev, struct phy_link_st
...
+	/* Stop monitor during reconfiguration */
+#if DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios)
+	if (!config->interrupt_gpio.port) {
+		k_work_cancel_delayable(&data->phy_monitor_work);
+	}
+#else /* DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios) */
+	k_work_cancel_delayable(&data->phy_monitor_work);
+#endif /* DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios) */
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c]:
```suggestion
	if (UTIL_OR(UTIL_NOT(DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios), (!config->interrupt_gpio.port)))) {
		k_work_cancel_delayable(&data->phy_monitor_work);
	}
```

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 4]
```diff
@@ -278,49 +271,47 @@ static int phy_mc_vsc8541_get_speed(const struct device *dev, struct phy_link_st
...
-		LOG_ERR("initialize failed");
-		return ret;
+	/* Start monitoring */
+#if DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios)
+	if (!config->interrupt_gpio.port) {
+		k_work_reschedule(&data->phy_monitor_work, K_MSEC(CONFIG_PHY_MONITOR_PERIOD));
 	}
+#else /* DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios) */
+	k_work_reschedule(&data->phy_monitor_work, K_MSEC(CONFIG_PHY_MONITOR_PERIOD));
+#endif /* DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios) */
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c]:
```suggestion
	if (UTIL_OR(UTIL_NOT(DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios), (!config->interrupt_gpio.port)))) {
		k_work_reschedule(&data->phy_monitor_work, K_MSEC(CONFIG_PHY_MONITOR_PERIOD));
}
```

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 5]
```diff
@@ -527,6 +486,185 @@ static DEVICE_API(ethphy, mc_vsc8541_phy_api) = {
...
+}
+
+static int phy_mc_vsc8541_init_interrupt(const struct device *dev)
+{
+	struct mc_vsc8541_data *data = dev->data;
+	const struct mc_vsc8541_config *config = dev->config;
+	uint16_t reg;
+	int ret;
+
+	if (NULL != config->interrupt_gpio.port) {
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c]:
```suggestion
	if (config->interrupt_gpio.port == NULL) {
		return 0
	}
```

invert the logic and return early

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 6]
```diff
@@ -527,6 +486,185 @@ static DEVICE_API(ethphy, mc_vsc8541_phy_api) = {
...
+	}
+
+	k_work_init_delayable(&data->phy_monitor_work, phy_mc_vsc8541_monitor_work_handler);
+
+#if DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios)
+	/* Initialize GPIO interrupt pin and configure PHY for interrupt mode */
+	ret = phy_mc_vsc8541_init_interrupt(dev);
+	if (ret) {
+		return ret;
+	}
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c]:
```suggestion
	if (ret < 0) {
		return ret;
	}
```

explicit checks

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 7]
```diff
@@ -527,6 +486,185 @@ static DEVICE_API(ethphy, mc_vsc8541_phy_api) = {
...
+		}
+	}
+
+#if DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios)
+	if (!config->interrupt_gpio.port) {
+		k_work_reschedule(&data->phy_monitor_work, K_MSEC(CONFIG_PHY_MONITOR_PERIOD));
+	}
+#else /* DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios) */
+	k_work_reschedule(&data->phy_monitor_work, K_MSEC(CONFIG_PHY_MONITOR_PERIOD));
+#endif /* DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios) */
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c]:
```suggestion
	if (UTIL_OR(UTIL_NOT(DT_ANY_INST_HAS_PROP_STATUS_OKAY(int_gpios), (!config->interrupt_gpio.port)))) {
		k_work_reschedule(&data->phy_monitor_work, K_MSEC(CONFIG_PHY_MONITOR_PERIOD));
	}
```

you might wanna make that a define

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 3 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: Done. Your proposal contains a typo, by the way, I have fixed it.

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 4 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: Done

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 6 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: Done. Applied to all other return codes checks as well

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 7 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: I wouldn't really put it into another wrap. To be honest, this implementation already not very human readable, I have spent a good half hour trying to figure out how it works and what it expands to.

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 5 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: Done

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 8]
```diff
@@ -278,49 +271,41 @@ static int phy_mc_vsc8541_get_speed(const struct device *dev, struct phy_link_st
...
+	struct mc_vsc8541_data *data = dev->data;
 	int ret;
 
+	/* Lock mutex */
+	ret = k_mutex_lock(&data->mutex, K_FOREVER);
+	if (ret < 0) {
+		LOG_ERR("phy mutex lock error");
+		return ret;
+	}
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c:285]: mutex with K_FOREVER don't fail, no need there to check

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 9]
```diff
@@ -441,7 +394,12 @@ static int phy_mc_vsc8541_read(const struct device *dev, uint16_t reg_addr, uint
 	/* mask out lower byte */
 	reg_addr &= 0x00ff;
 
-	k_mutex_lock(&dev_data->mutex, K_FOREVER);
+	/* Lock mutex */
+	ret = k_mutex_lock(&dev_data->mutex, K_FOREVER);
+	if (ret < 0) {
+		LOG_ERR("phy mutex lock error");
+		return ret;
+	}
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c:402]: revert, is unrelated

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 10]
```diff
@@ -527,6 +490,185 @@ static DEVICE_API(ethphy, mc_vsc8541_phy_api) = {
...
+	ret = k_mutex_lock(&data->mutex, K_FOREVER);
+	if (ret < 0) {
+		LOG_ERR("phy mutex lock error");
+		return ret;
+	}
+
+	/* Read/clear PHY interrupt status register */
+	ret = phy_mc_vsc8541_read(dev, PHY_REG_PAGE0_INT_STAT, &reg);
+	if (ret < 0) {
+		LOG_ERR("error reading phy (%d) interrupt status register", config->addr);
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c:511]: please use one generic log msg for fails. mdio write and read fails are pretty rare and often not related to the phy. it will either not work for all registers or for none. 

also no need for the `error:`. the severity/log level is normally already also printed by the log subsystem. keep them short.

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 11]
```diff
@@ -527,6 +490,185 @@ static DEVICE_API(ethphy, mc_vsc8541_phy_api) = {
...
+
+static int phy_mc_vsc8541_init_interrupt(const struct device *dev)
+{
+	struct mc_vsc8541_data *data = dev->data;
+	const struct mc_vsc8541_config *config = dev->config;
+	uint16_t reg;
+	int ret;
+
+	if (config->interrupt_gpio.port == NULL) {
+		LOG_WRN("the interrupt pin is unavailable, "
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c:541]: remove that, it should not be a warning. also it is only printed when there is one with irq and one without

**Review by maass-hamburg — CHANGES_REQUESTED** [review]
Also check https://docs.zephyrproject.org/latest/contribute/contributor_expectations.html#pr-requirements

put your fixes always in the original commits.
don't just add more commits, you need to rebase

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 8 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: Removed checks for every `k_mutex_lock`.

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 9 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: Same here.

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 10 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: In the end I have decided to completely remove these error messages, as they are not used anywhere else in the original driver version.
This piece of code was written based on another PHY driver, that log messages were dragged from there as well.

File: drivers/ethernet/phy/phy_microchip_vsc8541.c (hunk 11 above)
Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c]: Removed that warning.
Anyway I believe we could keep it, because they print warning when reset pin is unavailable.

File: drivers/ethernet/phy/phy_microchip_vsc8541.c [hunk 12]
```diff
@@ -527,6 +474,167 @@ static DEVICE_API(ethphy, mc_vsc8541_phy_api) = {
...
+			PHY_REG_PAGE0_INT_MASK_SPEED_CHANGE |
+			PHY_REG_PAGE0_INT_MASK_LINK_CHANGE |
+			PHY_REG_PAGE0_INT_MASK_FDX_CHANGE);
+		ret = phy_mc_vsc8541_write(dev, PHY_REG_PAGE0_INT_MASK, reg);
+		if (ret < 0) {
+			return ret;
+		}
+	} else {
+		return ret;
+	}
```
Comment (maass-hamburg) [inline drivers/ethernet/phy/phy_microchip_vsc8541.c:533]:
```suggestion
	ret = phy_mc_vsc8541_read(dev, PHY_REG_PAGE0_INT_MASK, &reg);
	if (ret < 0) {
		return ret;
	}

	reg |= (PHY_REG_PAGE0_INT_MASK_MDINT_EN |
		PHY_REG_PAGE0_INT_MASK_SPEED_CHANGE |
		PHY_REG_PAGE0_INT_MASK_LINK_CHANGE |
		PHY_REG_PAGE0_INT_MASK_FDX_CHANGE);
	ret = phy_mc_vsc8541_write(dev, PHY_REG_PAGE0_INT_MASK, reg);
	if (ret < 0) {
		return ret;
	}
```

Comment (RobbieKhan) [reply drivers/ethernet/phy/phy_microchip_vsc8541.c:533]: Done.

**Review by maass-hamburg — DISMISSED** [review]

**Comment by maass-hamburg** [comment]
@RobbieKhan you need to fix the compliance checks

**Comment by maass-hamburg** [comment]
@RobbieKhan still missing the commit description, just a title is not enough

**Comment by RobbieKhan** [comment]
> @RobbieKhan still missing the commit description, just a title is not enough

Understood, didn't know about that rule. I will add it now.

**Review by maass-hamburg — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
