### PR TITLE
drivers: uart: Make all API function available

### LINKED ISSUE #26801: UART API has ifdefs around API functions
**Describe the bug**
UART API has 2 optional, exclusive APIs: interrupt driven (`CONFIG_UART_INTERRUPT_DRIVEN` ) and later introduced asynchronous (`CONFIG_UART_ASYNC_API`). Both API's are ifdefed. That causes more ifdefs in the code which is using them. 

It is also not consistent with other optional API's, e.g. `k_poll` in kernel.

**Expected behavior**
API, even if not implemented, should not be ifdefed. It can be removed from the code using `IS_ENABLED` or any other compile time flags.

**Impact**
More dirty, harder to maintain code.

### PR DESCRIPTION
**Pull request by nordic-krch**
Conditional API was removed by preprocessor which violates zephyr
coding style. Removed ifdefs around conditional API.

See #26773 where coding style will explicitly state that API should be present at compile time.

Added `-ENOTSUP` error code to be returned by API which is disabled (whenever possible).

Fixes #26801.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

File: include/drivers/uart.h [hunk 1]
```diff
@@ -723,12 +748,14 @@ static inline int z_impl_uart_config_get(struct device *dev,
...
+#ifdef CONFIG_UART_INTERRUPT_DRIVEN
 	const struct uart_driver_api *api =
 		(const struct uart_driver_api *)dev->driver_api;
 
 	if (api->fifo_fill) {
 		return api->fifo_fill(dev, tx_data, size);
 	}
+#endif
 
 	return 0;
```
Comment (nzmichaelh) [inline include/drivers/uart.h:760]: Should this return -ENOTSUP?  I'm not sure.

Comment (nordic-krch) [reply include/drivers/uart.h:760]: this function does not return error code. It returns `Number of bytes sent.` I was wondering if it should assert here but lack of define is more or less the same as lack of function pointer in api struct and that returned 0.

**Review by ceolin — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by Mierunski — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Comment by tbursztyka** [comment]
That reminded me SPI has the same issue, fixed there: #26931

**Review by MaureenHelm — APPROVED** [review]
