### PR TITLE
Bluetooth: tester: Fixes for GCC 10.x

### LINKED ISSUE #28375: gcc 10.x compile warning/error for array subscript 0 is outside the bounds in tests/bluetooth/tester/src/gap.c
When building `tests/bluetooth/tester` on `qemu_x86` with gcc 10.2 we get:

```
/home/galak/git/zephyr/tests/bluetooth/tester/src/gap.c: In function 'tester_handle_gap':
/home/galak/git/zephyr/tests/bluetooth/tester/src/gap.c:278:35: error: array subscript 254 is outside the bounds of an interior zero-length array 'const uint8_t[0]' {aka 'const unsigned char[]'} [-Werror=zero-length-bounds]
  278 |   ad[adv_len].type = cmd->adv_data[i++];
      |                      ~~~~~~~~~~~~~^~~~~
In file included from /home/galak/git/zephyr/tests/bluetooth/tester/src/gap.c:25:
/home/galak/git/zephyr/tests/bluetooth/tester/src/bttester.h:157:10: note: while referencing 'adv_data'
  157 |  uint8_t adv_data[0];
      |          ^~~~~~~~
/home/galak/git/zephyr/tests/bluetooth/tester/src/gap.c:279:39: error: array subscript 255 is outside the bounds of an interior zero-length array 'const uint8_t[0]' {aka 'const unsigned char[]'} [-Werror=zero-length-bounds]
  279 |   ad[adv_len].data_len = cmd->adv_data[i++];
      |                          ~~~~~~~~~~~~~^~~~~
In file included from /home/galak/git/zephyr/tests/bluetooth/tester/src/gap.c:25:
/home/galak/git/zephyr/tests/bluetooth/tester/src/bttester.h:157:10: note: while referencing 'adv_data'
  157 |  uint8_t adv_data[0];
      |          ^~~~~~~~
/home/galak/git/zephyr/tests/bluetooth/tester/src/gap.c:280:22: error: array subscript 256 is outside the bounds of an interior zero-length array 'const uint8_t[0]' {aka 'const unsigned char[]'} [-Werror=zero-length-bounds]
  280 |   ad[adv_len].data = &cmd->adv_data[i];
      |                      ^~~~~~~~~~~~~~~~~
In file included from /home/galak/git/zephyr/tests/bluetooth/tester/src/gap.c:25:
/home/galak/git/zephyr/tests/bluetooth/tester/src/bttester.h:157:10: note: while referencing 'adv_data'
  157 |  uint8_t adv_data[0];
      |          ^~~~~~~~
cc1: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by carlescufi**
Fix the structures so that they are compliant with the stricter checks
of GCC 10.x, and at the same time correct a bug that was present in the
handling of the GAP Start Advertising BTP command.

Fixes #28375.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
Is it me or the handling of the GAP Advertising command was completely broken? Unless my understanding was incorrect:

https://github.com/intel/auto-pts/blob/master/doc/btp_spec.txt#L300

**Review by jhedberg — APPROVED** [review]

**Review by galak — APPROVED** [review]

File: tests/bluetooth/tester/src/bttester.h [hunk 1]
```diff
@@ -29,7 +29,7 @@ struct btp_hdr {
 	uint8_t  opcode;
 	uint8_t  index;
 	uint16_t len;
-	uint8_t  data[0];
+	uint8_t  data[];
```
Comment (galak) [inline tests/bluetooth/tester/src/bttester.h:32]: can we make this `uint8_t *`

File: tests/bluetooth/tester/src/bttester.h [hunk 2]
```diff
@@ -71,7 +71,7 @@ struct gap_read_supported_commands_rp {
 #define GAP_READ_CONTROLLER_INDEX_LIST	0x02
 struct gap_read_controller_index_list_rp {
 	uint8_t num;
-	uint8_t index[0];
+	uint8_t index[];
```
Comment (galak) [inline tests/bluetooth/tester/src/bttester.h:74]: seems like we can remove the [] here

**Review by galak — COMMENTED** [review]
Can most of these `uint8_t FOOO[]` be `uin8_t *FOO` instead?

**Comment by jhedberg** [comment]
> Can most of these uint8_t FOOO[] be uin8_t *FOO instead?

Not really. These are structs that describe data in a contiguous protocol buffer, and the buffer contains protocol data as it was received (i.e. we can't put pointers in there or such). `uint8_t foo[]` is just a helper to quickly get access to the position within the buffer where some variable-length data begins.

**Review by michal-narajowski — APPROVED** [review]

**Review by sjanc — APPROVED** [review]

**Review by MariuszSkamra — APPROVED** [review]

File: tests/bluetooth/tester/src/gap.c [hunk 3]
```diff
@@ -275,21 +275,21 @@ static void start_advertising(const uint8_t *data, uint16_t len)
...
-		ad[adv_len].data_len = cmd->adv_data[i++];
-		ad[adv_len].data = &cmd->adv_data[i];
+		ad[adv_len].type = cmd->adv_sr_data[i++];
+		ad[adv_len].data_len = cmd->adv_sr_data[i++];
+		ad[adv_len].data = &cmd->adv_sr_data[i];
 		i += ad[adv_len].data_len;
 	}
 
-	for (i = 0, sd_len = 0U; i < cmd->scan_rsp_len; sd_len++) {
+	for (sd_len = 0U; i < cmd->adv_data_len+cmd->scan_rsp_len; sd_len++) {
```
Comment (joerchan) [inline tests/bluetooth/tester/src/gap.c:284]: I think there are more problems in this function. The ad_len starts at 1, so adv_len should have +1 a couple of places.

`if ((adv_len + 1) >= ARRAY_SIZE(ad)) {` line 273

```
	if (bt_le_adv_start(adv_conn ? BT_LE_ADV_CONN : BT_LE_ADV_NCONN,
			    ad, adv_len + 1, sd_len ? sd : NULL, sd_len) < 0) {
```
line 299-300

**Review by joerchan — CHANGES_REQUESTED** [review]

**Review by joerchan — APPROVED** [review]
