### PR TITLE
drivers: flash: stm32h7: fix int/long int warnings

### LINKED ISSUE #31994: drivers: flash: stm32h7: fix int/long int warnings
Upon request, issue is created which describes what merge request https://github.com/zephyrproject-rtos/zephyr/pull/31919 fixes.

In short, %d in format string is used on long int, causing warnings.

@erwango

### PR DESCRIPTION
**Pull request by emillindq**
Changed lines were producing warnings. As elsewhere in this file, offset is type-casted (or not, depending on compiler) to long int, and then `%ld` is used in format string.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/31994

### CODE REVIEW

File: drivers/flash/flash_stm32h7x.c [hunk 1]
```diff
@@ -102,8 +102,8 @@ bool flash_stm32_valid_range(const struct device *dev, off_t offset,
 	if (write) {
 		if ((offset % FLASH_NB_32BITWORD_IN_FLASHWORD * 4) != 0) {
 			LOG_ERR("Write offset not aligned on flashword length. "
-				"Offset: 0x%x, flashword length: %d",
-				offset, FLASH_NB_32BITWORD_IN_FLASHWORD * 4);
+				"Offset: 0x%lx, flashword length: %d",
+				(long) offset, FLASH_NB_32BITWORD_IN_FLASHWORD * 4);
```
Comment (nvlsianpu) [inline drivers/flash/flash_stm32h7x.c:106]:
```suggestion
				(unsigned long) offset, FLASH_NB_32BITWORD_IN_FLASHWORD * 4);
```

**Review by nvlsianpu — APPROVED** [review]

**Comment by erwango** [comment]
@emillindq If you add a matching issue, we can get this merged in V2.5.0 (currently merge window is frozen and only idendentified bug fixes are getting merged)

**Review by erwango — APPROVED** [review]
