### PR TITLE
littlefs: fix return code on mount

### LINKED ISSUE #56378: fs_mount() don't translate littlefs return code when mount fails and no formatting is requested
**Describe the bug**
When invoking `fs_mount()` with littlefs as backend and passing the flag `FS_MOUNT_FLAG_NO_FORMAT`, if the mount fails, the littlefs return code it's passed directly to the application without being first translated into errno.

**To Reproduce**
In `tests/subsys/fs/littlefs:test_fs_mkfs`, the flash area is swept before calling `fs_mount()`, hence `lfs_mount()` will return `LFS_ERR_CORRUPT=84`, but it should be instead `EFAULT` (https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/fs/littlefs_fs.c#L102).

For example, to reproduce with `esp32` board (the board I have at hand right now):
`west build -p always -b esp32 tests/subsys/fs/littlefs`
For this board, is needed to create a DT overlay as follow:
```devicetree
/* tests/subsys/fs/littlefs/boards/esp32.overlay */

/delete-node/ &storage_partition;

&flash0 {
	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;
		small_partition: partition@250000 {
			label = "small";
			reg = < 0x250000 0x00010000 >;
		};
	};
};
```

**Expected behavior**
All littlefs return code are translated to errno before being passed to the application layer.

**Impact**
Wrong error code returned to application when FS is damaged/corrupted and `tests/subsys/fs/littlefs` failing

**Logs and console output**
```
... output omitted ...
START - test_fs_mkfs_simple_lfs
Clean /sml
Erasing 65536 (0x10000) bytes
Wiped flash area 4 for /sml
Mount with flag no format
I: LittleFS version 2.5, disk version 2.0
I: FS at flash-controller@3ff42000:0x250000 is 16 0x1000-byte blocks with 512 cycle
I: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
E: WEST_TOPDIR/modules/fs/littlefs/lfs.c:1234: Corrupted dir pair at {0x0, 0x1}
I: /sml mounted
E: fs mount error (-84)
    Assertion failed at WEST_TOPDIR/zephyr/tests/subsys/fs/common/test_fs_mkfs.c:29: test_fs_mkfs_simple: (ret not equal to -EILSEQ)
Expected EILSEQ got -84
 FAIL - test_fs_mkfs_simple_lfs in 0.218 seconds
... output omitted ...
TESTSUITE littlefs failed.
------ TESTSUITE SUMMARY START ------
SUITE FAIL -  92.86% [littlefs]: pass = 13, fail = 1, skip = 0, total = 14 duration = 3.965 seconds
 - PASS - [littlefs.test_fs_mkfs_custom] duration = 0.246 seconds
 - PASS - [littlefs.test_fs_mkfs_ops_lfs] duration = 0.417 seconds
 - FAIL - [littlefs.test_fs_mkfs_simple_lfs] duration = 0.218 seconds
 - PASS - [littlefs.test_fs_mount_flags] duration = 0.230 seconds
 - PASS - [littlefs.test_fs_open_flags_lfs] duration = 0.739 seconds
 - PASS - [littlefs.test_lfs_basic] duration = 0.535 seconds
 - PASS - [littlefs.test_lfs_dirops] duration = 1.103 seconds
 - PASS - [littlefs.test_lfs_perf] duration = 0.471 seconds
 - PASS - [littlefs.test_util_path_extend] duration = 0.001 seconds
 - PASS - [littlefs.test_util_path_extend_overrun] duration = 0.001 seconds
 - PASS - [littlefs.test_util_path_extend_up] duration = 0.001 seconds
 - PASS - [littlefs.test_util_path_init_base] duration = 0.001 seconds
 - PASS - [littlefs.test_util_path_init_extended] duration = 0.001 seconds
 - PASS - [littlefs.test_util_path_init_overrun] duration = 0.001 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux, Windows
 - Toolchain: Zephyr SDK 0.16.0
 - Commit SHA: 70f9acd9269b61b7311f9f8050d3b88832e8020f

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by manuargue**
When littlefs mount fails and there is no formatting requested, the return code must be translated to errno before being passed to the application layer.

Additionally, only log a warning that the FS will be formatted, when the system is not read-only.

Fixes #56378

### CODE REVIEW

**Review by de-nordic — CHANGES_REQUESTED** [review]
Some comments left.
Can you also report Bug for this, describing how LittleFS returns incorrect error code due to missing error translation?
Add one more commit with release notes entry describing how mount code for damaged file system changed.

**Comment by manuargue** [comment]
@de-nordic, thanks for the feedback. All comments addressed

File: subsys/fs/littlefs_fs.c [hunk 1]
```diff
@@ -853,27 +853,30 @@ static int littlefs_mount(struct fs_mount_t *mountp)
...
 	/* Mount it, formatting if needed. */
 	ret = lfs_mount(&fs->lfs, &fs->cfg);
-	if (ret < 0 &&
-	    (mountp->flags & FS_MOUNT_FLAG_NO_FORMAT) == 0) {
-		LOG_WRN("can't mount (LFS %d); formatting", ret);
-		if ((mountp->flags & FS_MOUNT_FLAG_READ_ONLY) == 0) {
-			ret = lfs_format(&fs->lfs, &fs->cfg);
+	if (ret < 0) {
+		if ((mountp->flags & FS_MOUNT_FLAG_NO_FORMAT) == 0) {
+			LOG_WRN("can't mount (LFS %d); formatting", ret);
```
[the remark this answers is not in the document]
Comment (manuargue) [reply subsys/fs/littlefs_fs.c:859]: I've added this update as well

File: doc/releases/release-notes-3.4.rst [hunk 2]
```diff
@@ -379,6 +379,8 @@ Libraries / Subsystems
 * File systems
 
   * Added :kconfig:option:`CONFIG_FS_FATFS_REENTRANT` to enable the FAT FS reentrant option.
+  * With LittleFS as backend, :c:func:`fs_mount` return code was changed to ``EFAULT`` when
```
Comment (de-nordic) [inline doc/releases/release-notes-3.4.rst:382]: "return code was corrected", you have fixed bug.

File: doc/releases/release-notes-3.4.rst [hunk 3]
```diff
@@ -379,6 +379,8 @@ Libraries / Subsystems
...
+    called with ``FS_MOUNT_FLAG_NO_FORMAT`` and the FS is damaged.
```
Comment (de-nordic) [inline doc/releases/release-notes-3.4.rst:383]: "and the FS is damaged." change this to something line "while designated LIttleFS area could not be mounted because it has not yet been mounted or required reformatting" ( avoid damaged).

**Review by de-nordic — COMMENTED** [review]
Minor fixes to release notes, otherwise looks OK

**Comment by manuargue** [comment]
> Minor fixes to release notes, otherwise looks OK

all right, updated notes as suggested.

**Review by de-nordic — APPROVED** [review]
Looks OK. Thanks!

**Review by carlescufi — APPROVED** [review]
