### PR TITLE
intel-adsp: fix ACE power-off assembly

### LINKED ISSUE #75700: Zephyr panic on system on system suspend on Intel ADSP ace20
**Describe the bug**
Regression seen with multiple Intel platforms with https://github.com/zephyrproject-rtos/zephyr/pull/75174

Zephyr panic show in host log in https://sof-ci.01.org/sofpr/PR9291/build6402/devicetest/index.html?model=LNLM_RVP_NOCODEC&testcase=check-capture-10sec

**To Reproduce**
Build Zephyr main with the PR, run a test that boots system and puts it to system suspend.
 
**Expected behavior**
No Zephyr panic.

**Impact**

**Logs and console output**

**Environment (please complete the following information):**
See versions and environment described in public CI run at https://sof-ci.01.org/sofpr/PR9291/build6402/devicetest/index.html

### PR DESCRIPTION
**Pull request by lyakh**
A recent commit fb53d2ef8dde ("ace: power: replace pseudo-assembly movi") contained a bug: the Xtensa "movi" assembly instruction must be written with the immediate argument already shifted left by 8, the compiler doesn't do that automatically. This still somehow worked on MTL but failed on LNL. Fix both occurrences.

Fixes: #75700

This is an alternative to reverting the offending commit as submitted in #75689

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
Test in https://github.com/thesofproject/sof/pull/9294 seems good, so this is better than the revert. Thanks @lyakh !

**Review by tmleman — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]

**Review by abonislawski — APPROVED** [review]

File: soc/intel/intel_adsp/ace/asm_memory_management.h [hunk 1]
```diff
@@ -38,7 +38,7 @@
 	movi \az, 0x2f5
 	slli \az, \az, 0xb
 	/* 8 * (\segment_index << 5) == (\segment_index << 5) << 3 == \segment_index << 8 */
-	addmi \az, \az, \segment_index
+	addmi \az, \az, \segment_index << 8
```
Comment (serhiy-katsyuba-intel) [inline soc/intel/intel_adsp/ace/asm_memory_management.h:41]: For ACE MAX_MEMORY_SEGMENTS == 1, so segment_index is always 0. And so this shift cannot affect the problem.

Comment (kv2019i) [reply soc/intel/intel_adsp/ace/asm_memory_management.h:41]: @serhiy-katsyuba-intel  Ack, the patch affects via LSPGCTL_HIGH which is also passed to addmi. So this change is to just correct all uses of addmi. @lyakh to confirm, but that's how I understood it

**Review by ceolin — APPROVED** [review]

File: soc/intel/intel_adsp/ace/asm_memory_management.h (hunk 1 above)
Comment (lyakh) [reply soc/intel/intel_adsp/ace/asm_memory_management.h:41]: correct. This is just a correctness fix, the real fix is the `LSPGCTL_HIGH` part

**Comment by marc-hb** [comment]
Still not completely fixed?
- https://github.com/thesofproject/sof/issues/9308
