### PR TITLE
Bluetooth: controller: Fix assert in RPA timeout for advertiser

### LINKED ISSUE #18092: Assert in BT controller on RPA timeout
Advertiser asserts when RPA timeout occurs and no entry in the resolving list exists for the peer.
This happens even when the peer address is an all zero address i.e no valid peer address.

**To Reproduce**
Affects:
CONFIG_BT_PRIVACY=y
CONFIG_BT_SETTINGS=y

1. west build -b nrf52840_pca10056 tests/bluetooth/shell
2. Attach board and open terminal
3. `west flash`
4. Terminal
```
bt init
bt advertise on
<wait for timeout>
```

**Impact**
System crash.

**Screenshots or console output**
```
uart:~$ bt advertise on
Advertising started
[00:00:29.463,104] <err> bt_ctlr_llsw_llfilter: assert: 'idx < ((long) (((int) sizeof(char[1 - 2 * !(!__d
[00:00:29.463,134] <err> os: r0/a1:  0x00000003  r1/a2:  0x20006f20  r2/a3:  0x00000000
[00:00:29.463,165] <err> os: r3/a4:  0x00000001 r12/ip:  0x20006ae0 r14/lr:  0x00006017
[00:00:29.463,165] <err> os:  xpsr:  0x41000000
[00:00:29.463,195] <err> os: Faulting instruction address (r15/pc): 0x0002010e
[00:00:29.463,195] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops
```

### PR DESCRIPTION
**Pull request by joerchan**
Fix assert in the RPA timeout when no resolving entry exists in the
resolving list, and the advertiser was requested to use a local IRK
to generate it's own address.

Fixes: #18092

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ll_filter.c [hunk 1]
```diff
@@ -567,6 +567,11 @@ static void rpa_adv_refresh(void)
 		return;
 	}
 
+	idx = ll_rl_find(ll_adv->id_addr_type, ll_adv->id_addr, NULL);
+	if (idx == FILTER_IDX_NONE) {
```
Comment (carlescufi) [inline subsys/bluetooth/controller/ll_sw/ll_filter.c]: Can you use the same check we use elsewhere? `if(idx >= ARRAY_SIZE())`...

**Review by carlescufi — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ll_filter.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/controller/ll_sw/ll_filter.c]: Yes. will do.

**Review by carlescufi — APPROVED** [review]

**Comment by cvinayak** [comment]
@carlescufi backport this?

**Comment by carlescufi** [comment]
> @carlescufi backport this?

Can you please include this in your Controller Conformance backport PR @cvinayak ?

**Comment by carlescufi** [comment]
@wopu-ot @thoh-ot @asmk-ot I will be merging this today since it's a pretty serious bug that we need to backport and deal with as soon as possible. We have developed the fix together with @joerchan and we are quite confident it is correct. If you have additional remarks please let us know and we'll deal with those post-merge.

**Comment by ioannisg** [comment]
> 
> 
> > @carlescufi backport this?
> 
> Can you please include this in your Controller Conformance backport PR @cvinayak ?

Does this mean we are not yet sure if this is to be back-ported @carlescufi ?

**Comment by carlescufi** [comment]
> > > @carlescufi backport this?
> > 
> > 
> > Can you please include this in your Controller Conformance backport PR @cvinayak ?
> 
> Does this mean we are not yet sure if this is to be back-ported @carlescufi ?

No, this means we need to backport it, and so it needs to be added to the PR

**Comment by ioannisg** [comment]
> 
> 
> > > > @carlescufi backport this?
> > > 
> > > 
> > > Can you please include this in your Controller Conformance backport PR @cvinayak ?
> > 
> > 
> > Does this mean we are not yet sure if this is to be back-ported @carlescufi ?
> 
> No, this means we need to backport it, and so it needs to be added to the PR

Then we don't need to label it as back-port.

**Comment by carlescufi** [comment]
> > > > > @carlescufi backport this?
> > > > 
> > > > 
> > > > Can you please include this in your Controller Conformance backport PR @cvinayak ?
> > > 
> > > 
> > > Does this mean we are not yet sure if this is to be back-ported @carlescufi ?
> > 
> > 
> > No, this means we need to backport it, and so it needs to be added to the PR
> 
> Then we don't need to label it as back-port.

That's right

**Comment by cvinayak** [comment]
> > > > > > @carlescufi backport this?
> > > > > 
> > > > > 
> > > > > Can you please include this in your Controller Conformance backport PR @cvinayak ?
> > > > 
> > > > 
> > > > Does this mean we are not yet sure if this is to be back-ported @carlescufi ?
> > > 
> > > 
> > > No, this means we need to backport it, and so it needs to be added to the PR
> > 
> > 
> > Then we don't need to label it as back-port.
> 
> That's right

Done. Added to https://github.com/zephyrproject-rtos/zephyr/pull/17720

**Comment by joerchan** [comment]
Backport included in #18122
