### PR TITLE
Bluetooth: Host: Fix bt_addr_from_str for str starting with ':'

### LINKED ISSUE #58504: [Coverity CID: 316114] Uninitialized scalar variable in subsys/bluetooth/shell/bt.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/dae79cefaabf63086946a48ccca4094f26f146c8/subsys/bluetooth/shell/bt.c

Category: Uninitialized variables
Function: `cmd_auto_conn`
Component: Bluetooth
CID: [316114](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=316114)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/dae79cefaabf63086946a48ccca4094f26f146c8/subsys/bluetooth/shell/bt.c#L2522

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.coverity.com/doc/en/cov_checker_ref.html#static_checker_UNINIT). ([CWE-457](http://cwe.mitre.org/data/definitions/457.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by alwa-nordic**
The previous implementation would read from `addr->val[0]` before it was initialized if the input string started with a colon ':'.

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/58504

### CODE REVIEW

**Comment by Thalley** [comment]
@alwa-nordic many of your issues have already been closed as duplicates. Should the duplicate be added here instead? 

@jhedberg It may be easier to follow what has been done vs what is a duplicate if you close the issues as "Closed as not planned" as that will make them appear with white rather than the purple "Fixed" color, so we can distinquish between what has been fixed and what is a duplicate or otherwise marked as something that shouldn't/ be/isn't fixed.

File: subsys/bluetooth/host/addr.c [hunk 1]
```diff
@@ -53,28 +53,30 @@ int bt_addr_le_create_static(bt_addr_le_t *addr)
 
 int bt_addr_from_str(const char *str, bt_addr_t *addr)
 {
-	int i, j;
-	uint8_t tmp;
+	const size_t strlen_addr = strlen("XX:XX:XX:XX:XX:XX");
```
Comment (jhedberg) [inline subsys/bluetooth/host/addr.c:56]: Does the strlen get evaluated at build time? If not, I’d consider using sizeof instead. We might also want to make these as public defines, if those don’t exist yet.

Comment (alwa-nordic) [reply subsys/bluetooth/host/addr.c:56]: > Does the strlen get evaluated at build time? If not, I’d consider using sizeof instead.

It's optimized away at any optimization level other than `-O0`, but it's not guaranteed.

Is the following what you suggest?

```suggestion
	const size_t strlen_addr = ARRAY_SIZE("XX:XX:XX:XX:XX:XX") - 1;
```

I prefer the following, keeping it simpler and just writing out the constant. The code has some tests now, so an error here should be caught.

```suggestion
	const size_t strlen_addr = 17; /* strlen("XX:XX:XX:XX:XX:XX") */
```

> We might also want to make these as public defines, if those don’t exist yet.

That could be nice, but then we have to decide what to name it :P. We already have `#define BT_ADDR_STR_LEN 18` in `addr.h`, but that counts the null-terminator.

**Comment by alwa-nordic** [comment]
> @alwa-nordic many of your issues have already been closed as duplicates. Should the duplicate be added here instead?

I don't understand what the last part means. Does GitHub have something like "Fixes as duplicate: #xxxxx"?

**Comment by alwa-nordic** [comment]
I'll remove the 'Fixes:' for the duplicate issues.

**Comment by Thalley** [comment]
> I don't understand what the last part means. Does GitHub have something like "Fixes as duplicate: #xxxxx"?

For Github issues, when you close them manually (like @jhedberg did), you can either click the standard "Close Issue" button: 
image

or you can expand the array and get "Close as not planned" which Github has defined to also encompass "duplicate"
image

When closing as "Close as not planned" the issue gets a different color indicating that nothing has been done to close the issue, which is the case for duplicates and false positives

File: subsys/bluetooth/host/addr.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/host/addr.c:56]: > That could be nice, but then we have to decide what to name it :P. We already have #define BT_ADDR_STR_LEN 18 in addr.h, but that counts the null-terminator.

It would be trivial to do 
```c
/* Subtract 1 as we don't parse the NULL terminator in this function */
const size_t strlen_addr = BT_ADDR_STR_LEN - 1;
```
though

File: subsys/bluetooth/host/addr.c [hunk 2]
```diff
@@ -53,28 +53,30 @@ int bt_addr_le_create_static(bt_addr_le_t *addr)
...
-	for (i = 5, j = 1; *str != '\0'; str++, j++) {
-		if (!(j % 3) && (*str != ':')) {
-			return -EINVAL;
-		} else if (*str == ':') {
-			i--;
-			continue;
-		}
+	for (size_t i = 0; i < strlen_addr; i++) {
+		int octet = i / 3; /* Count whole octets 'ab:' in 'ab:ab:ab:ab:ab:ab'. */
+		int digit = i % 3; /* Cycle over indexes in 'ab:'. */
```
Comment (Thalley) [inline subsys/bluetooth/host/addr.c:64]:
```suggestion
		const size_t octet = i / 3; /* Count whole octets 'ab:' in 'ab:ab:ab:ab:ab:ab'. */
		const size_t digit = i % 3; /* Cycle over indexes in 'ab:'. */
```

I would make these `const size_t` as they will not change and the source value for the calculations is also a `size_t` (`i`).

File: subsys/bluetooth/host/addr.c [hunk 3]
```diff
@@ -53,28 +53,30 @@ int bt_addr_le_create_static(bt_addr_le_t *addr)
...
 
-		addr->val[i] = addr->val[i] << 4;
+		if (digit == 0) {
+			/* `bt_addr_t` order is 'reversed canonical' aka 'on-air order'. */
+			size_t dst = 5 - octet;
```
Comment (Thalley) [inline subsys/bluetooth/host/addr.c:68]:
```suggestion
			const size_t dst = 5 - octet;
```

File: subsys/bluetooth/host/addr.c [hunk 4]
```diff
@@ -53,28 +53,30 @@ int bt_addr_le_create_static(bt_addr_le_t *addr)
...
 
-		if (char2hex(*str, &tmp) < 0) {
-			return -EINVAL;
+			if (!hex2bin(&str[i], 2, &addr->val[dst], 1)) {
+				return -EINVAL;
+			}
 		}
 
-		addr->val[i] |= tmp;
+		if (digit == 3) {
```
Comment (Thalley) [inline subsys/bluetooth/host/addr.c:75]:
```suggestion
		else if (digit == 3) {
```

File: tests/bluetooth/addr/src/test_bt_addr_from_str.c [hunk 5]
```diff
@@ -0,0 +1,154 @@
+/* Copyright (c) 2022 Nordic Semiconductor ASA
```
Comment (Thalley) [inline tests/bluetooth/addr/src/test_bt_addr_from_str.c:1]:
```suggestion
/* Copyright (c) 2023 Nordic Semiconductor ASA
```

File: tests/bluetooth/addr/src/test_bt_addr_from_str.c [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+#include <zephyr/ztest.h>
+
+ZTEST_SUITE(bt_addr_from_str, NULL, NULL, NULL, NULL, NULL);
+
+ZTEST(bt_addr_from_str, test_reject_empty_string)
+{
+	char *addr_str = "";
+	bt_addr_t a;
+
+	zassert_equal(bt_addr_from_str(addr_str, &a), -EINVAL);
```
Comment (Thalley) [inline tests/bluetooth/addr/src/test_bt_addr_from_str.c:15]: Nice idea with the tests. Perhaps, since these test explicitly for `-EINVAL`, we should add that as the only return value in the documentation of `bt_addr_from_str`? i.e. `@retval -EINVAL ...`

File: tests/bluetooth/addr/src/test_bt_addr_from_str.c
Comment (Thalley) [inline tests/bluetooth/addr/src/test_bt_addr_from_str.c:1]: Correct me if I am wrong, but do don't have any tests that tests for invalid characters, e.g. `aa:bb:cc:dd:ee:qq`

**Review by Thalley — CHANGES_REQUESTED** [review]

File: tests/bluetooth/addr/src/test_bt_addr_from_str.c
Comment (alwa-nordic) [reply tests/bluetooth/addr/src/test_bt_addr_from_str.c:1]: There is a basic one `test_reject_non_hex` that test `00:00:00:00:g0:00`.

Comment (Thalley) [reply tests/bluetooth/addr/src/test_bt_addr_from_str.c:1]: Sorry - Missed that one :D

File: subsys/bluetooth/host/addr.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/addr.c]: I got away from the problem here by replacing `strlen_addr = SOME_KNOWN_VALUE` with `len = strlen(str)`.

**Review by jhedberg — DISMISSED** [review]

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/addr.c [hunk 7]
```diff
@@ -53,28 +53,30 @@ int bt_addr_le_create_static(bt_addr_le_t *addr)
...
 
-	for (i = 5, j = 1; *str != '\0'; str++, j++) {
-		if (!(j % 3) && (*str != ':')) {
-			return -EINVAL;
-		} else if (*str == ':') {
-			i--;
-			continue;
-		}
+	for (size_t i = 0; i < len; i++) {
+		const size_t octet = i / 3; /* Count whole octets 'ab:' in 'ab:ab:ab:ab:ab:ab'. */
```
[the remark this answers is not in the document]
Comment (alwa-nordic) [reply subsys/bluetooth/host/addr.c:63]: Yeah, I'm struggling to find a good name here. It's not really a 'count' either, but the 'place'/'index' of the current octet.

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/addr.c:63]: `octet_index` may work as it is `0` for the first "ab:` and then `1` for the next `ab:`

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
