### PR TITLE
modules: segger: remove mutex locking

### LINKED ISSUE #79403: RTT: `LOG_PANIC` unable to be called in ISR's
**Describe the bug**

Calling `LOG_PANIC()` in an exception handler when RTT is the logging backend will deadlock due to triggering its own assertion. This is due to `SEGGER_RTT_LOCK` not being suitable for use in IRQ's:
https://github.com/zephyrproject-rtos/zephyr/blob/7773fe8dd60e9f86760c994090304a0577a1ad2f/modules/segger/SEGGER_RTT_zephyr.c#L35-L38

While mutex locking is explicitly not permitted in ISRs:
https://github.com/zephyrproject-rtos/zephyr/blob/7773fe8dd60e9f86760c994090304a0577a1ad2f/include/zephyr/kernel.h#L3066

**Expected behavior**

`LOG_PANIC` should never deadlock.

**Impact**

System lockup on exception unless a hardware watchdog that automatically reboots is enabled.

**Logs and console output**

image

### PR DESCRIPTION
**Pull request by JordanYates**
Remove mutex locking in favour of the standard IRQ locking mechanism. The primary problem with the mutex implementation is that mutex locking is forbidden in ISR's. This means that any logging from an interrupt context (e.g. LOG_PANIC in an exception handler), will itself trigger another assertion due its attempt to use a mutex.

Furthermore, mutexes are a relatively heavyweight locking scheme, which doesn't necessarily make sense in the context of extremely short locking periods that would be expected from RTT.

This change aligns Zephyr with the default RTT locking scheme, which uses interrupt masking to perform access control.

Resolves #79403.

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

File: modules/segger/SEGGER_RTT_zephyr.c [hunk 1]
```diff
@@ -9,41 +9,15 @@
...
- * Note that SEGGER uses same lock macros for both SEGGER_RTT_Write and
- * SEGGER_RTT_Read functions. Because of this we are not able generally
- * separate up and down access using two mutexes until SEGGER library fix
- * this.
- *
- * If sharing access cause performance problems, consider using another
- * non terminal buffers.
- */
-
 K_MUTEX_DEFINE(rtt_term_mutex);
```
Comment (henrikbrixandersen) [inline modules/segger/SEGGER_RTT_zephyr.c:12]: Is this mutex instance still used?

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by nordic-krch — DISMISSED** [review]

**Comment by JordanYates** [comment]
Updated with final SHA

**Review by henrikbrixandersen — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@dcpleung , can you help review

**Review by dcpleung — APPROVED** [review]
