### PR TITLE
Bluetooth: controller: Fix conn setup regression

### LINKED ISSUE #35955: Bluetooth: Controller: Regression in connection setup
An incorrect and redundant use of ticker user id ULL_LOW
instead of ULL_HIGH when setting up a connection using a
mayfly to disable LLL context. Also, the LLL context pointer
is invalid, where node rx is passed instead of LLL context.

This prevents connections from correctly establishing.

Regression introduced in commit 30f260d ("Bluetooth:
controller: Fix adv/scan context access post release").

### PR DESCRIPTION
**Pull request by cvinayak**
Fix incorrect and redundant use of ticker user id ULL_LOW
instead of ULL_HIGH when setting up a connection using a
mayfly to disable LLL context. Also, the LLL context pointer
is invalid, where node rx is passed instead of LLL context.

Use the ULL disabled callback when done event has not yet
been processed, or a direct connection setup in ULL_HIGH
context when ULL is already disabled (reference count is
zero) is sufficient.

Regression introduced in commit 30f260dfaaf7 ("Bluetooth:
controller: Fix adv/scan context access post release").

Fixes #35955.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 1]
```diff
@@ -847,23 +841,14 @@ void ull_conn_setup(memq_link_t *rx_link, struct node_rx_hdr *rx)
...
-
+		/* Setup connection in ULL disabled callback,
+		 * pass the node rx as disabled callback parameter.
+		 */
 		LL_ASSERT(!hdr->disabled_cb);
-		hdr->disabled_param = mfy.param;
+		hdr->disabled_param = rx;
 		hdr->disabled_cb = conn_setup_adv_scan_disabled_cb;
-
-		mfy.fp = lll_disable;
```
Comment (wopu-ot) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c:856]: The original code calls `lll_disable` via mayfly, while the new code does not call `lll_disable`. It is not obvious to my why that call is no longer necessary. Can you explain?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c:856]: Original call passed `mfy.param = rx` (incorrectly) when calling `lll_disable` which in theory is redundant, as `lll_disable` will not find a LLL context pointed to be `rx`. The connection was still established as ULL reference count reached zero due to `lll_done` being invoked in LLL context of advertiser  and scanner.

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c:856]: So the rationale is that because `lll_disable` was not called correctly before (had no consequence), and it still works without that, then we skip calling it altogether? Not sure it makes sense to me... `lll_disable` performs a whole lot of shutting down/aborting and resetting stuff in vendor LLL. Please elaborate.

Comment (mtpr-ot) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c:856]: I can add that our simulation tests pass with this PR, so with a background story on addition and removal of `lll_disable`, I can approve.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c:856]: ‘lll_disable’ call got redundant when flags were added (necessary) to gracefully handle race conditions when establishing connection. the implementation was incorrect anyway, doing nothing to abort any LLL in the pipeline due to incorrect context pointer passed.

Please provide your approval if there is no concerns on inspection and if internal tests pass.

**Review by mtpr-ot — APPROVED** [review]
LGTM
