### PR TITLE
net: http_client: Fix http_client_req() return value

### LINKED ISSUE #43829: http_client: http_client_req() returns incorrect number of bytes sent
The `http_client_req()` function is supposed to return the number of bytes sent to the server:
https://github.com/zephyrproject-rtos/zephyr/blob/main/include/net/http_client.h#L327

However, there is a bug in the implementation such that it generally returns something much larger. Each line of the headers is sent via one call to `http_send_data()`, the return value of which is added to the `total_sent` summation variable.
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/http/http_client.c#L529

However, `http_send_data()` doesn't typically return the number of bytes that were added in that particular invocation. Instead it copies the values into a local 192 byte buffer and returns the current position within that buffer.

For example, if I wanted to send:

            PATCH /v1/123456789abcd HTTP/1.1
            Host: xxxxxxxxxxxxxxxxxx.uc.r.appspot.com
            Content-Length: 34

Then the http_client sends 33+43+22==98 bytes of headers plus my 34 bytes of payload for a total of 132 bytes.

However the calls to `http_send_data()` will return 33, (33 + 43), and (33 + 43 + 22) respectively. This leads to `total_sent` being set to 207 by the time the headers have been sent, which causes an incorrect return value of 207+34==241 from `http_client_req()`.

### PR DESCRIPTION
**Pull request by rlubos**
http_client_req() was supposed to return the number of bytes sent as a
HTTP request. The return value was not riht however due to some bugs in
helper functions:
* http_send_data() returned the current buffer position istead of the
  number of bytes actually sent. This could result in counting the same
  data into the total request size several times. A helper variable was
  added to track how many bytes were actually sent to the network.
* http_flush_data() forwarded the return value of sendall() helper
  function. That function however did not return number of bytes sent,
  but 0 or a negative error code.

Additionally, change the return type of sendall() function - according
to standard the ssize_t type is only capable of holding -1 negative
value, but the function could return the full range of negative errno
values. Use int instead.

Fixes #43829

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
CC @ewalt1

**Review by jukkar — APPROVED** [review]

File: subsys/net/lib/http/http_client.c [hunk 1]
```diff
@@ -120,9 +121,16 @@ static int http_send_data(int sock, char *send_buf,
 
 static int http_flush_data(int sock, const char *send_buf, size_t send_buf_len)
```
Comment (ewalt1) [inline subsys/net/lib/http/http_client.c:122]: I'd suggest making this "size_t *send_buf_pos" so that it's consistent with http_send_data and you don't need to remember to zero it at each call site.

**Review by ewalt1 — APPROVED** [review]
Changes LGTM. Also tested and confirmed that I'm getting the expected values now.

Thanks for the quick fix!

**Review by carlescufi — APPROVED** [review]
