### PR TITLE
 samples: tests: Fix usb.audio.headset test

### LINKED ISSUE #32179: samples: tests: Tests from samples/subsys/usb/audio fail
**Describe the bug**
Tests from samples/subsys/usb/audio fail twister tests with timeout. It happens because the tests were not designed properly: there are no actual tests defined (no pass/fail conditions). 
 
**Impact**
Annoyance

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr SDK
 - Commit SHA or Version used v2.5.0-rc3-39-gd0be253081f5

### PR DESCRIPTION
**Pull request by PerMac**
samples: tests: Fix usb.audio.headset test
 
 The samples were failing twister test with a timeout because there were
no pass/fail criteria for them (nothing was tested). The fix adds
harness on console and some output that can be verified.

### CODE REVIEW

File: samples/subsys/usb/audio/headset/src/main.c [hunk 1]
```diff
@@ -70,11 +70,16 @@ void main(void)
...
+
 	usb_audio_register(hs_dev, &ops);
 
 	ret = usb_enable(NULL);
 	if (ret != 0) {
 		LOG_ERR("Failed to enable USB");
 		return;
 	}
+
+
```
Comment (jfischer-no) [inline samples/subsys/usb/audio/headset/src/main.c:83]: Please remove the one empty line.

Comment (PerMac) [reply samples/subsys/usb/audio/headset/src/main.c]: Done

**Review by jfischer-no — APPROVED** [review]

**Review by nashif — APPROVED** [review]
