### PR TITLE
drivers: clock_control: stm32f7 force flash latency with overdrive

### LINKED ISSUE #50853: STM32F7 series can't run at frequencies higher than 180MHz
**Describe the bug**

When configuring clock with a frequency higher than 180MHz the board is not able to start.
It hangs just after configuring the clock (`clock_stm32_ll_common.c:stm32_clock_control_init`).

By looking at the code :
`LL_SetFlashLatency` checks `LL_PWR_IsEnabledOverDriveMode` for frequencies higher than 180HMz.

Unfortunately overdrive mode is enable later in `set_up_plls`.

By calling `set_up_plls` before configuring the flash wait states I am able to boot the board correctly.

This as been tested on a custom board with stm32f723 (originally based on ST STM32F723E Discovery) running Zephyr 3.1
Any sample app built with stm32f7 board should have the bug.

**Expected behavior**
App should be able to run completely.

**Impact**
The board does not start.

**Environment (please complete the following information):**
 - OS: Unintu 1804
 - Toolchain Zephyr 0.14.2
 - Zephyr 3.1 (2ddd73feafd3316af2c547c34d6969bea637d5c6)

**Additional context**

Clock config in device tree:
```
&clk_hse {
	clock-frequency = <DT_FREQ_M(25)>;
	status = "okay";
};

&pll {
	div-m = <25>;
	mul-n = <432>;
	div-p = <2>;
	div-q = <9>;
	clocks = <&clk_hse>;
	status = "okay";
};

&rcc {
	clocks = <&pll>;
	clock-frequency = <DT_FREQ_M(216)>;
	ahb-prescaler = <1>;
	apb1-prescaler = <4>;
	apb2-prescaler = <2>;
};
```

### PR DESCRIPTION
**Pull request by FRASTM**
The Flash latency depends on the sysclock but also in case of the stm32F7 on the regulator overdrive mode. The overdrive must be set before the first LL_SetFlashLatency.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/50853

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

File: drivers/clock_control/clock_stm32_ll_common.c [hunk 1]
```diff
@@ -663,6 +649,20 @@ int stm32_clock_control_init(const struct device *dev)
 
 	new_flash_freq = RCC_CALC_FLASH_FREQ(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC,
 				      STM32_FLASH_PRESCALER);
+#if defined(STM32_PLL_ENABLED) && defined(CONFIG_SOC_SERIES_STM32F7X)
```
Comment (erwango) [inline drivers/clock_control/clock_stm32_ll_common.c:652]: Break a line before this.

**Review by erwango — CHANGES_REQUESTED** [review]
Otherwise LGTM

File: drivers/clock_control/clock_stm32_ll_common.c (hunk 1 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_common.c:653]: done

**Review by erwango — DISMISSED** [review]

File: drivers/clock_control/clock_stm32_ll_common.c [hunk 2]
```diff
@@ -664,6 +650,21 @@ int stm32_clock_control_init(const struct device *dev)
 	new_flash_freq = RCC_CALC_FLASH_FREQ(CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC,
 				      STM32_FLASH_PRESCALER);
 
+#if defined(STM32_PLL_ENABLED) && defined(CONFIG_SOC_SERIES_STM32F7X)
```
Comment (ABOSTM) [inline drivers/clock_control/clock_stm32_ll_common.c:653]: LGTM, but in order to ease future maintenance, I would have move this block (STM32_PLL_ENABLED && CONFIG_SOC_SERIES_STM32F7X) before FLASH_ACR_LATENCY block (to avoid imbrication of both compilation switches)

Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_common.c:653]: Yes, 
activation of the overdrive depends on the sys clock freq (whatever the latency but must be done before the latency setting)

**Comment by FRASTM** [comment]
moving the overdrive mode out of the control of the Flash Latency  (#if defined(FLASH_ACR_LATENCY)

**Review by erwango — APPROVED** [review]

**Comment by vgeneves** [comment]
Hi,

I did a bit more testing with this patch and I encountered a problem when trying to update my application using an old version of MCuboot.

To reproduce:
The board is initially flashed with Mcuboot (1.4) and an application based on Zephyr 1.14.
Note that in Zephyr 1.14 overdrive mode is not configured.
Update with an app built with Zephyr 3.2.

When booting:
Mcuboot (1.4) will configure the STM32 to use the PLL as clock source
And will handover to the application (Zephyr 3.2).
When configuring the clocks, the code below will loop forever:
```
LL_PWR_EnableOverDriveMode();
		while (LL_PWR_IsActiveFlag_OD() != 1) {
		/* Wait for OverDrive mode ready */
		}
		LL_PWR_EnableOverDriveSwitching();
		while (LL_PWR_IsActiveFlag_ODSW() != 1) {
		/* Wait for OverDrive switch ready */
		}
```
The reference manual (4.1.4 Voltage Regulator) recommend to switch to overdrive mode only when clocked from HSI or HSE.
Calling `stm32_clock_switch_to_hsi()` before configuring OVD Mode solved the problem (like for PLL configuration).

**Comment by FRASTM** [comment]
> 
> The reference manual (4.1.4 Voltage Regulator) recommend to switch to overdrive mode only when clocked from HSI or HSE. Calling `stm32_clock_switch_to_hsi()` before configuring OVD Mode solved the problem (like for PLL configuration).

If we follow this recommendation, we should see in the stm32_clock_control_init()

1. set_up_fixed_clock_sources()
2. enable overdrive
3. setFlash Latency
4. set_up_plls()

**Review by gautierg-st — APPROVED** [review]
