### PR TITLE
net_buf: make reference counts atomic

### LINKED ISSUE #106334: Thread-safety race condition in net_buf_unref
### Describe the bug

https://github.com/zephyrproject-rtos/zephyr/blob/main/lib/net_buf/buf.c#L460

Target Platform : NXP MCXN947 EVK

The net_buf_unref function lacks proper synchronization when 
decrementing the reference counter and clearing buffer fields. 

Specifically, buf->data and buf->frags are modified after the 
reference count reached zero, but without holding a lock. This 
created a TOCTOU (Time-of-Check to Time-of-Use) window where a 
preempted thread could attempt to write to a buffer that had 
already been destroyed and reallocated by another context, 
leading to memory corruption or a Use-After-Free (UAF)

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by npitre**
The two reference counts in the net_buf library — the per-header `buf->ref` and the per-data-block `*ref_count` byte at the start of each variable-data allocation — are manipulated with plain non-atomic C operators (`++`, `--`, `if (--rc)`).

The documented contract says otherwise. The Network Buffers chapter of the Zephyr docs (`doc/services/net_buf/index.rst`) describes `net_buf_ref()` / `net_buf_unref()` as self-synchronizing and explicitly endorses passing buffers across threads via `k_fifo`. There is no requirement for callers to hold a higher-level lock around ref/unref, and existing users (notably zbus's msg-subscriber path) rely on exactly that: a producer clones a buffer N times and hands the clones off to N subscriber threads via their FIFOs, after which the N+1 holders independently call `net_buf_unref()` with no surrounding lock.

With non-atomic decrement-and-test, two CPUs can concurrently observe the same prior value (e.g. 1), both decrement, and both conclude they were the last reference. The two data-pool variants have particularly nasty failure modes: in `heap_data_unref` the second `k_free()` dereferences the heap-hardening poison that just replaced the owning `struct k_heap *` and faults inside `k_spin_lock`; in `mem_pool_data_unref` the duplicate `k_heap_free()` corrupts heap metadata silently.

**Fix.** Use atomic operations on both reference counts.

The per-data-block refcount becomes `atomic_t` and fits inside the existing `GET_ALIGN(pool)` reservation (>= `sizeof(void *)`) at no memory cost.

The per-header `buf->ref` is overlaid in a union with the three adjacent `uint8_t` fields (`flags`, `pool_id`, `user_data_size`) and an `atomic_t ref_word` view of the same storage:

```c
union {
    atomic_t ref_word;
    struct {
        uint8_t ref;            // LSB of ref_word
        uint8_t flags;
        uint8_t pool_id;
        uint8_t user_data_size;
    };
};
```

Byte order is conditional on endianness so `ref` is always the LSB of `ref_word`. Net_buf internals do `atomic_inc/dec(&buf->ref_word)` and narrow the returned word value to `uint8_t` to extract the ref byte; because the ref count is bounded to 254 (already implicit in its `uint8_t` domain), the inc/dec only adjusts the LSB and the other three bytes stay untouched. Plain `uint8_t` reads of `buf->ref` from non-atomic call sites continue to work, so the change is transparent to the consumers that read it for diagnostics.

**Memory footprint.** `struct net_buf` does **not** grow on either 32-bit or 64-bit. Measured on `nrf52dk/nrf52832` running `samples/bluetooth/peripheral_hr`:

| Variant | RAM | `sizeof(struct net_buf)` |
|---|---|---|
| `main` (non-atomic) | 28 556 B | 24 |
| Plain `atomic_t ref` | 28 660 B (+104) | 28 |
| **This PR (union)** | **28 556 B (0)** | **24** |

**Relationship to #105792 / #106335 / #101067.** #101067 took the same `atomic_t` direction but was retired over the per-buf size growth — this PR avoids that via the byte/word union. #106335 wraps `pool->lock` around `buf->ref` in `net_buf_unref()`, which closes one race but does not address the per-data-block refcount in `mem_pool_data_unref()` / `heap_data_unref()` (see [comment](https://github.com/zephyrproject-rtos/zephyr/pull/106335#issuecomment-4337929098)). #105792 is the cleaner long-term shape; if/when `atomic_uchar_t` lands, `atomic_t ref_word` becomes `atomic_uchar_t ref` and the byte-aliasing union goes away.

**How we found it.** The race manifests reliably under FVP, where the FastModel's quantum-based execution model can schedule N threads to all reach the unref point in the same simulated moment. The zbus `msg_subscriber_dynamic_isolated` sample, which exchanges shared data buffers among 16+ subscribers running on 4 SMP cores, makes the use-after-free crash deterministic.

### CODE REVIEW

**Comment by jhedberg** [comment]
Looks like a duplicate of https://github.com/zephyrproject-rtos/zephyr/pull/101067 and https://github.com/zephyrproject-rtos/zephyr/pull/106335.

`atomic_t` was already tried in #101067, but the increased memory footprint lead to the exploration of C17 atomics usage (which offers 8-bit atomic variables). That seems to be taking quite a long time to get into the tree (see https://github.com/zephyrproject-rtos/zephyr/pull/105792) which led me to propose that the solution offered in #106335 might be the most practical one, at least in the short term (see https://github.com/zephyrproject-rtos/zephyr/pull/106335#issuecomment-4302395028)

**Comment by jhedberg** [comment]
To be clear: I'd love to be able to use `atomic_t` as in this PR, but there's some additional work to make sure we don't regress with memory constrained platforms. There are e.g. some 16k RAM ones where the Bluetooth configuration has been tuned to be within a few bytes of the maximum, so even the smallest footprint increase for net_buf would show up as build failures for those.

**Comment by jhedberg** [comment]
@namjoshiniks @dwyoung43 FYI

**Comment by npitre** [comment]
@jhedberg Thanks for the pointers to the prior work. I should address the concerns directly:

**On the memory footprint of `atomic_t ref`:** the latest revision uses a union that overlays the existing `flags`, `pool_id` and `user_data_size` bytes on the same 32-bit slot as the `atomic_t` view (`ref_word`). The byte-struct ordering is conditional on endianness so `ref` always lands at the LSB of `ref_word`; `atomic_inc/dec` only mutates that byte (since the count is bounded to 254, already implicit in its `uint8_t` domain), leaving the other three fields untouched.

Measured on `nrf52dk/nrf52832` running `samples/bluetooth/peripheral_hr` (ARM 32-bit, the constrained-BT class):

| Variant | RAM | `sizeof(struct net_buf)` |
|---|---|---|
| `main` (non-atomic) | 28 556 B | 24 |
| Plain `atomic_t ref` | 28 660 B (+104) | 28 |
| **This PR (union)** | **28 556 B (0)** | **24** |

So the size argument that retired #101067 doesn't apply here. On 64-bit, `atomic_t` is 8 bytes but the `struct net_buf` already had 4 bytes of alignment padding before its next 8-byte-aligned pointer field, so it doesn't grow there either.

**On scope vs #106335:** that PR wraps `pool->lock` around `buf->ref`, but it does not address the *per-data-block* refcount in `mem_pool_data_unref` / `heap_data_unref` (the byte at `data - GET_ALIGN`). That byte is exactly the race that produced the use-after-free crash we ran into on the Corstone-1000-A320 FVP — a CPU reads the owning `struct k_heap *` from the freed-and-poisoned block via `k_free`'s metadata word and faults inside `k_spin_lock`. This PR fixes both refcounts.

**On #105792:** completely agreed it is the cleaner long-term shape. If/when `atomic_uchar_t` lands, this code can be migrated trivially — `atomic_t ref_word` becomes `atomic_uchar_t ref` and the byte-aliasing union goes away. Until then, this PR is no worse for memory than the status quo, fixes a real SMP correctness bug we are tripping over today, and is small enough (3 files, ~140 lines) to revert or rework when the better foundation arrives.

I'd appreciate another look with the union footprint in mind.

**Comment by jhedberg** [comment]
@npitre impressive work, thanks! I'm not a big fan of the increased complexity, but I guess that's an acceptable solution until the new C atomics become available.

File: lib/net_buf/buf.c [hunk 1]
```diff
@@ -443,21 +452,32 @@ void net_buf_unref(struct net_buf *buf)
...
 			NET_BUF_ERR("%s():%d: buf %p double free", func, line,
 				    buf);
 #endif
 			return;
 		}
-		NET_BUF_DBG("buf %p ref %u pool_id %u frags %p", buf, buf->ref,
-			    buf->pool_id, buf->frags);
 
-		if (--buf->ref > 0) {
+		if (old_ref != 1) {
```
Comment (jhedberg) [inline lib/net_buf/buf.c:480]: I'm confused how this can work. Don't you at least need to mask out the upper 24 bits before treating `old_ref` as an refcount?

Comment (jhedberg) [reply lib/net_buf/buf.c:480]: Nevermind - it's an `uint8_t` so it's implicit. I think some static analyzers might want you to add an explicit cast in front of `atomic_dec()` however.

**Review by jhedberg — APPROVED** [review]

File: lib/net_buf/buf.c
Comment (lylezhu2012) [inline lib/net_buf/buf.c:125]: In original case, only first byte of the reserved memory space (the minimal size is `sizeof(void*)`) will be updated. 

But in the change, the size of memory space being modified is `sizeof(atomic_t)`. While the reserved memory size may be `sizeof(void *)`. 

If is there a case that the `sizeof(void *)` is less than the `sizeof(atomic_t )`? if yes, there is a potential risk of memory corruption.

File: lib/net_buf/buf.c [hunk 2]
```diff
@@ -443,21 +452,32 @@ void net_buf_unref(struct net_buf *buf)
...
+		 * free the buffer and we must not read it again. The
+		 * decrement is performed on `ref_word` (the atomic_t view of
+		 * the slot shared with flags/pool_id/user_data_size) and the
+		 * uint8_t narrowing extracts just the ref byte from the
+		 * returned prior word value.
+		 */
 		struct net_buf *frags = buf->frags;
+		__maybe_unused uint8_t pool_id = buf->pool_id;
 		struct net_buf_pool *pool;
+		uint8_t old_ref = atomic_dec(&buf->ref_word);
```
Comment (lylezhu2012) [inline lib/net_buf/buf.c:466]: Is there a potential risk of damaging other fields if the old ref is zero?

**Review by jukkar — APPROVED** [review]

File: lib/net_buf/buf.c
Comment (npitre) [reply lib/net_buf/buf.c:125]: On every Zephyr-supported ABI we have `sizeof(long) == sizeof(void *)` (ILP32 on 32-bit, LP64 on 64-bit), and `atomic_t` is a `long` — the `BUILD_ASSERT(sizeof(atomic_t) == sizeof(long))` near the top of `lib/net_buf/buf.c` documents that load-bearing assumption. For `sizeof(atomic_t) > sizeof(void *)` to happen, `atomic_t` would have to be redefined to `unsigned long long` / `uint64_t` on a 32-bit ABI, which isn't realistic; if anyone ever did that, the `BUILD_ASSERT` would fire long before the data-block reservation became too small, pointing them straight at the layout that has to be revisited.

File: lib/net_buf/buf.c (hunk 2 above)
Comment (npitre) [reply lib/net_buf/buf.c:466]: Yes — on `old_ref == 0` (a double-free), `atomic_dec` produces -1 and the borrow walks through the upper bytes, corrupting `flags` / `pool_id` / `user_data_size`. But by that point the caller has already done a more serious bug (two unrefs against one ref), and we're firmly in undefined-behavior territory regardless of how the refcount is implemented. The `__ASSERT(old_ref != 0, ...)` catches it in debug builds; in release the early-return prevents the actual `net_buf_destroy()` call, so the heap stays consistent and the buf header is now a leaked orphan rather than a vector for further damage. Defending the field corruption with a CAS loop that refuses to dec past 0 was considered, but it adds visible cost to the hot path for what's already a programming bug, and it doesn't make the underlying double-free any less of a problem.
