### PR TITLE
drivers: adc: siwx91x: Silabs siwx91x adc ref voltage support

### LINKED ISSUE #100211: soc: silabs: siwx91x: ADC driver returns constant 0 mV
### Describe the bug

ADC driver does not handle internal reference properly to calculate mV values.
adc_dt sample app gives constant 0 mV value. Raw value seems okay.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Take `siwx917_rb4338a.overlay` and `siwx917_rb4338a.conf` from `zephyr/tests/drivers/adc/adc_api/boards`

```
west build -p -b siwx917_rb4338a .\zephyr\samples\drivers\adc\adc_dt\ -d .\build\adc_dt
west flash -d .\build\adc_dt\
```

AGPIO_ULP1 and ADC_TOPGPIO_HP27 connected to GND:
```
ADC reading[98]:
- adc@24043800, channel 0: 2048 = 0 mV
- adc@24043800, channel 1: 2048 = 0 mV
ADC reading[99]:
- adc@24043800, channel 0: 2048 = 0 mV
- adc@24043800, channel 1: 2048 = 0 mV
```

and if both connected to 3.3V:
```
ADC reading[167]:
- adc@24043800, channel 0: 2029 = 0 mV
- adc@24043800, channel 1: 2031 = 0 mV
ADC reading[168]:
- adc@24043800, channel 0: 2028 = 0 mV
- adc@24043800, channel 1: 2028 = 0 mV
ADC reading[169]:
- adc@24043800, channel 0: 2028 = 0 mV
- adc@24043800, channel 1: 2029 = 0 mV
```

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by smalae**
1. Add ref_internal to the device API.
2. Instead of returning a converted ADC reading, return the
raw ADC sample. Conversion is left to the user based on
the selected ADC mode (single-ended or differential).
3. Add adc_dt support for siwx917_rb4338a

Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/100211

### CODE REVIEW

**Comment by smalae** [comment]
Bug fix for https://github.com/zephyrproject-rtos/zephyr/issues/100211

File: drivers/adc/adc_silabs_siwx91x.c [hunk 1]
```diff
@@ -378,13 +372,16 @@ static void adc_siwx91x_isr(const struct device *dev)
...
 
-static DEVICE_API(adc, adc_siwx91x_driver_api) = {
-	.channel_setup = adc_siwx91x_channel_setup,
-	.read = adc_siwx91x_read,
-};
+#define ADC_SIWX91X_DRIVER_API(inst)                                                               \
+	static DEVICE_API(adc, adc_siwx91x_driver_api_##inst) = {                                  \
+		.channel_setup = adc_siwx91x_channel_setup,                                        \
+		.read = adc_siwx91x_read,                                                          \
+		.ref_internal = DT_INST_PROP(inst, silabs_adc_ref_voltage),                        \
```
Comment (Martinhoff-maker) [inline drivers/adc/adc_silabs_siwx91x.c:379]: it feels like this info is duplicated now, we already have it in the adc_siwx91x_config struct? I think creating a one line function that give the value from the config struct rather than intruducing those instance to the device API is better.

**Review by Martinhoff-maker — COMMENTED** [review]
tested on rb4338a and working.

**Review by jerome-pouiller — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
