### PR TITLE
OSDP SC requires CSPRNG

### LINKED ISSUE #29113: Build failure with OSPD
**Describe the bug**
Sample `samples/subsys/mgmt/osdp` build is failed on all targets due to below error:
```
/home/buildslave/srv/toolchain/zephyr-sdk-0.11.4/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/9.2.0/../../../../arm-zephyr-eabi/bin/ld: subsys/mgmt/osdp/libsubsys__mgmt__osdp.a(osdp_common.c.obj): in function `sys_csrand_get':
/home/buildslave/srv/zephyr/master/zephyr/nucleo_f401re/nucleo_f401re/samples/subsys/mgmt/osdp/sample.mgmt.osdp/zephyr/include/generated/syscalls/rand32.h:60: undefined reference to `z_impl_sys_csrand_get'
```

**To Reproduce**
`sanitycheck -p nucleo_f401re -T samples/subsys/mgmt/osdp/`

**Expected behavior**
Should build

**Impact**
Break all CIs

### PR DESCRIPTION
**Pull request by ceolin**
- Make OSDP SC requires CSPRNG
- General fixes when OSDP SC is not enabled

Fixes #29113

### CODE REVIEW

File: subsys/mgmt/osdp/src/osdp_pd.c [hunk 1]
```diff
@@ -328,7 +328,10 @@ static void pd_decode_command(struct osdp_pd *pd, uint8_t *buf, int len)
 		ret = 0;
 		break;
 	case CMD_CHLNG:
-		tmp = OSDP_PD_CAP_COMMUNICATION_SECURITY;
+		/* Workaround for error: a label can only be part of a
+		 * statement and a declaration is not a statement */
+		;
```
Comment (cbsiddharth) [inline subsys/mgmt/osdp/src/osdp_pd.c:333]: Nice!

**Review by sidcha — APPROVED** [review]
LGTM, Thanks!

**Review by erwango — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
