### PR TITLE
drivers: auxdisplay: Fix several issues with jhd1313 driver

### LINKED ISSUE #59078: auxdisplay: jhd1313 driver does not compile
**Describe the bug**

On `main`, when I try to compile samples/drivers/auxdisplay against a JHD1313 auxdisplay, it does not compile.

**To Reproduce**

Here's my overlay:

```
&arduino_i2c {
	status = "okay";

	auxdisplay_0: auxdisplay@3e {
		compatible = "jhd,jhd1313";
		status = "okay";
		reg = <0x3E>;
		columns = <16>;
		rows = <2>;
	};

};
```

**Expected behavior**

Driver should compile a sample should work with JHD1313 displays.

**Logs and console output**

```

C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c: In function 'auxdisplay_jhd1313_cursor_position_set':
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c:128:30: error: 'config' undeclared (first use in this function); did you mean 'mpu_config'?
  128 |         return i2c_write_dt(&config->bus, data, 2);
      |                              ^~~~~~
      |                              mpu_config
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c:128:30: note: each undeclared identifier is reported only once for each function it appears in
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c: In function 'auxdisplay_jhd1313_display_on':
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c:312:56: error: 'config' undeclared (first use in this function); did you mean 'mpu_config'?
  312 |         return auxdisplay_jhd1313_update_display_state(config, data);
      |                                                        ^~~~~~
      |                                                        mpu_config
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c: In function 'auxdisplay_jhd1313_display_off':
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c:320:56: error: 'config' undeclared (first use in this function); did you mean 'mpu_config'?
  320 |         return auxdisplay_jhd1313_update_display_state(config, data);
      |                                                        ^~~~~~
      |                                                        mpu_config
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c: In function 'auxdisplay_jhd1313_cursor_position_set':
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c:129:1: warning: control reaches end of non-void function [-Wreturn-type]
  129 | }
      | ^
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c: In function 'auxdisplay_jhd1313_display_off':
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c:321:1: warning: control reaches end of non-void function [-Wreturn-type]
  321 | }
      | ^
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c: In function 'auxdisplay_jhd1313_display_on':
C:/Users/kartben/zephyrproject/zephyr/drivers/auxdisplay/auxdisplay_jhd1313.c:313:1: warning: control reaches end of non-void function [-Wreturn-type]
  313 | }
      | ^
[175/190] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sched.c.obj
````

### PR DESCRIPTION
**Pull request by kartben**
Fix for #59078. As the JHD1313 currently doesn't compile and is one of the few that were just added with the new AuxDisplay API, I believe it should be fixed for 3.4

Fixes #59078

/cc @jadonk

### CODE REVIEW

**Comment by kartben** [comment]
Added a couple more fixes, all being reasonably straightforward and hopefully contributing to a better first-time experience for first-time users of the new AuxDisplay API :)

File: drivers/auxdisplay/auxdisplay_jhd1313.c [hunk 1]
```diff
@@ -26,9 +26,9 @@ LOG_MODULE_REGISTER(auxdisplay_jhd1313, CONFIG_AUXDISPLAY_LOG_LEVEL);
 #define JHD1313_CS_RIGHT_SHIFT		(1 << 2)
 
 /* Defines for the JHD1313_CMD_INPUT_SET to change text direction */
-#define JHD1313_IS_SHIFT_INCREMENT	(1 << 1)
-#define JHD1313_IS_SHIFT_DECREMENT	(0 << 1)
-#define JHD1313_IS_ENTRY_LEFT		(1 << 0)
+#define JHD1313_IS_SHIFT_INCREMENT	(1 << 0)
```
Comment (thedjnK) [inline drivers/auxdisplay/auxdisplay_jhd1313.c:29]: These came from https://github.com/zephyrproject-rtos/zephyr/blob/028e0a3c8d75fc5e2027f54dbb5a55aadbb1c490/include/zephyr/drivers/misc/grove_lcd/grove_lcd.h#L82 which shows increment as `1 << 1` not `1 << 0`, same for entry values. Since I copied and pasted and do not have this display, are you sure the new values are correct?

File: drivers/auxdisplay/auxdisplay_jhd1313.c [hunk 2]
```diff
@@ -298,14 +299,15 @@ static int auxdisplay_jhd1313_initialize(const struct device *dev)
 	auxdisplay_jhd1313_reg_set(config->bus.bus, 0x08, 0xAA);
 
 	/* Now set the background colour to white */
-	LOG_DBG("Background set to off");
-	auxdisplay_jhd1313_backlight_set(dev, 0);
+	LOG_DBG("Background set to white");
+	auxdisplay_jhd1313_backlight_set(dev, 1);
```
Comment (thedjnK) [inline drivers/auxdisplay/auxdisplay_jhd1313.c:303]: @gmarull what are your thoughts on this? I don't know what this display looks like or if the text is readable with the background off, but I don't see why it should default to white (unless it's not readable) otherwise someone wanting a different default colour will have a flash of white until their application boots and they can set it to their desired colour

File: drivers/auxdisplay/auxdisplay_jhd1313.c (hunk 1 above)
Comment (kartben) [reply drivers/auxdisplay/auxdisplay_jhd1313.c:29]: Yes I've tested with an actual display. I took the values from https://github.com/Seeed-Studio/Grove_LCD_RGB_Backlight/blob/94758dfe5f68de1d40203b8922196e18a0ba9df3/rgb_lcd.h#L66-L69
Without this fix the text is backwards, i.e.
```
________________
___________OLLEH
```

BTW just realized that DECREMENT should probably be 0 << 0...

I agree this is confusing (and contradicts the datasheet, too) but all other drivers i could find on GitHub also have INCREMENT/DECREMENT on bit 0.

File: drivers/auxdisplay/auxdisplay_jhd1313.c (hunk 2 above)
Comment (kartben) [reply drivers/auxdisplay/auxdisplay_jhd1313.c:303]: Happy to set to black (it is pretty readable even with no backlight). The main reason I suggested the fix was to align with the code comment on the line before that mentioned white :)

File: drivers/auxdisplay/auxdisplay_jhd1313.c (hunk 1 above)
Comment (kartben) [reply drivers/auxdisplay/auxdisplay_jhd1313.c:29]: Now that I think about it, could it be that all the other drivers are wrong? As they swapped the two bits, they ended setting ENTRY_LEFT|DECREMENT for roman languages... but it should probably be ENTRY_LEFT|INCREMENT, which if I'm not mistaken would have the same result as my "fix". Thoughts?

Comment (nordicjm) [reply drivers/auxdisplay/auxdisplay_jhd1313.c:29]: For hd44780? https://lcd-linux.sourceforge.net/pdfdocs/hd44780.pdf
ID 0 = increment, ID 1 = decrement, S 1 = accompanies display shift, and the command has ID in bit 1 and S in bit 0, so the original bit positions to be valid

Comment (nordicjm) [reply drivers/auxdisplay/auxdisplay_jhd1313.c:29]: > 	/* Initialize to the default text direction for romance languages */
>	cmd = JHD1313_IS_ENTRY_LEFT | JHD1313_IS_SHIFT_DECREMENT;

This doesn't make sense doing decrement by default, no, should be increment.

Comment (kartben) [reply drivers/auxdisplay/auxdisplay_jhd1313.c:29]: Ya all the other drivers out there (all likely copy pasted from Seeed's original one, including this one) seem to have reproduced the same pattern, which in our case here is causing the bug since we have the right config flags where all the others had them reversed (also due to copy pasting, probably).

BTW this https://github.com/Seeed-Studio/Grove_LCD_RGB_Backlight/blob/master/rgb_lcd.cpp#L201-L211 looks wrong too and confirms the original inversion issue, as this should be using increment/decrement to reverse text flow, right?

Comment (nordicjm) [reply drivers/auxdisplay/auxdisplay_jhd1313.c:29]: Agreed, that is wrong, surprised no-one has picked it up their since the function is named "leftToRight" and the flag being set is "ENTRYLEFT" not "ENTRYRIGHT"

File: drivers/auxdisplay/auxdisplay_jhd1313.c (hunk 2 above)
Comment (kartben) [reply drivers/auxdisplay/auxdisplay_jhd1313.c]: addressed in latest push (only updated the comment that improperly indicated "white")

File: drivers/auxdisplay/auxdisplay_jhd1313.c (hunk 1 above)
Comment (kartben) [reply drivers/auxdisplay/auxdisplay_jhd1313.c]: OK, just pushed what I think should be the right fix. RIGHT/LEFT has no meaning in the context of the Input Set. It's instead: move/don't move the cursor based on whether SHIFT is set or not. Whether it will grow to the left or to the right will depend on if it's INCREMENTing or DECREMENTing.

**Review by nordicjm — APPROVED** [review]

**Review by nashif — APPROVED** [review]
