### PR TITLE
drivers: serial: nrfx_uarte: Fix power management

### LINKED ISSUE #31989: nrfx_uarte serial driver does not go to low power mode after setting off state
**Describe the bug**
It is expected that uart will be disabled after going to off state. Device should consume ~5uA when sleeping with uart disabled. However, power consumption is at 500uA. Same application but with nrfx_uart reaches 5uA.

**To Reproduce**
Modified `hello_world` can be used to show the issue.
prj.conf:
```
CONFIG_DEVICE_POWER_MANAGEMENT=y
CONFIG_SHELL=
```
nrf52840dk_nrf52840.overlay:
```
&uart0 {
	compatible = "nordic,nrf-uarte";
};
&uart1 {
	status = "disabled";
};
```
main.c:
```
#include <zephyr.h>
#include <sys/printk.h>
#include <device.h>
#include <shell/shell.h>

#define CONSOLE_LABEL DT_LABEL(DT_CHOSEN(zephyr_console))

static int cmd_sleep(const struct shell *shell, size_t argc,
				    char **argv)
{
	const struct device *cons = device_get_binding(CONSOLE_LABEL);

	shell_print(shell, "putting to sleep");
	k_msleep(100);
	device_set_power_state(cons, DEVICE_PM_OFF_STATE, NULL, NULL);
	k_msleep(3000);
	device_set_power_state(cons, DEVICE_PM_ACTIVE_STATE, NULL, NULL);
	shell_print(shell, "waken up");
	return 0;
}

SHELL_CMD_REGISTER(sleep, NULL, "Demo commands", cmd_sleep);

void main(void)
{
	printk("Hello World! %s\n", CONFIG_BOARD);
}
```

Typing `sleep` should result in 3 seconds of sleep with ~5uA consumption but it stays at 500uA. Changing compatible to `nordic,nrf-uart` results in 5uA sleep.

**Impact**
Device cannot reach low power.

### PR DESCRIPTION
**Pull request by nordic-krch**
Power consumption was still high after putting uarte device into off state.
It was caused by ENDRX interrupt that was triggered after calling STOPRX.
ENDRX event was called with 0 amount but interrupt got triggered and
fifo_read was starting RX again.

Added disabling RX interrupt before disabling UARTE and reenabling at
device activation.

Fixes #31989.
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

**Review by Mierunski — APPROVED** [review]

File: drivers/serial/uart_nrfx_uarte.c [hunk 1]
```diff
@@ -1580,6 +1592,19 @@ static void uarte_nrfx_set_power_state(const struct device *dev,
...
+#ifdef UARTE_INTERRUPT_DRIVEN
+			if (data->int_driven) {
+				if (nrf_uarte_int_enable_check(uarte,
+						NRF_UARTE_INT_ENDRX_MASK)) {
+					data->int_driven->rx_irq_enabled = true;
+					nrf_uarte_int_disable(uarte,
+						NRF_UARTE_INT_ENDRX_MASK);
+				} else {
+					data->int_driven->rx_irq_enabled =
+									false;
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uarte.c:1604]: Could we somehow avoid such crazy indentation? Maybe using something like:
```
				data->int_driven->rx_irq_enabled =
					nrf_uarte_int_enable_check(uarte
						NRF_UARTE_INT_ENDRX_MASK);
				if (data->int_driven->rx_irq_enabled) {
					nrf_uarte_int_disable(uarte,
						NRF_UARTE_INT_ENDRX_MASK);
				}
```

Comment (nordic-krch) [reply drivers/serial/uart_nrfx_uarte.c]: done

**Review by anangl — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
