### PR TITLE
lib/os/mempool: Fix corruption case with block splitting

### LINKED ISSUE #15279: mempool alignment might cause a memory block allocated twice
the alignment in mempool is #define _ALIGN4(n) ((((n)+3)/4)*4), it means the alignment might expand the size of the block. If max_sz is not the power of four such as 36, the size of second level is ((((36/4)+3)/4)*4) = 12. Function block_break breaks the big block into 4 small blocks and append the last 3 blocks into the free_list.The last block might overflow the big block because function block_fits can not avoid this overflow. The last small block and the next big block would contain a same memory.

1. max_sz = 36, n_max = 3
2. alloc a small block (size 12)
3. alloc a big block (size 36)
4. alloc 3 small block(size 12)

### PR DESCRIPTION
**Pull request by andyross**
The block_fits() predicate was borked.  It would check that a block
fits within the bounds of the whole heap.  But that's not enough:
because of alignment changes between levels the sub-blocks may be
adjusted forward.  It needs to fit inside the PARENT block that it was
split from.

What could happen at runtime is that the last subblocks of a
misaligned parent block would overlap memory from subsequent blocks,
or even run off the end of the heap.  That's bad.

Change the API of block_fits() a little so it can extract the parent
region and do this properly.

Fixes #15279.  Passes test introduced in #16728 to demonstrate what
seems like the same issue.

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

File: lib/os/mempool.c [hunk 1]
```diff
@@ -72,9 +72,16 @@ static size_t buf_size(struct sys_mem_pool_base *p)
...
 
-static bool block_fits(struct sys_mem_pool_base *p, void *block, size_t bsz)
+static bool block_fits(struct sys_mem_pool_base *p,
+		       int lvl, int bn, size_t *lsizes)
 {
-	return ((u8_t *)block + bsz - 1 - (u8_t *)p->buf) < buf_size(p);
+	int plvl = lvl - 1;
+	int pbn = bn / 4;
+	u8_t *block_end = (u8_t *)block_ptr(p, lsizes[lvl], bn) + lsizes[lvl];
+	size_t parent_sz = lvl == 0 ? buf_size(p) : lsizes[plvl];
```
Comment (andrewboie) [inline lib/os/mempool.c]: suggest parens around lvl == 0 for clarity.
same deal with following line.
or just use a regular if { } else { }. I had to blink at this a lot to correctly parse it.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by andyross** [comment]
Spread out formatting for clarity

**Comment by andyross** [comment]
One more tiny patch to address a buffer allocation bug @npitre pointed out (who I still can't seem to add as a reviewer, but who can surely just jump in).

**Comment by npitre** [comment]
On Thu, 20 Jun 2019, Andy Ross wrote:

> One more tiny patch to address a buffer allocation bug @npitre pointed out (who I still can't seem to add as a reviewer, but who can surely just jump in).

I agree with the first patch, the block_fits() one, for now at least.

I also agreed with the second patch in principle. Now that I've 
actually seen it I must retract that.

Your patch is not sufficient. You missed one header file. But more 
importantly, you are missing some small but again fundamental details.

Please consider #16996 where I provided the complete explanation.

**Comment by andyross** [comment]
Yank duplicated fix.  Rebase.

**Comment by npitre** [comment]
In case my opinion is still required, I approve this PR as it is.

Please someone merge this ASAP. The potential for weird bugs is real without it.
