### PR TITLE
Bluetooth: GATT: Fix assuming writes to CCC will always contain 2 bytes

### LINKED ISSUE #16734: Bluetooth: GATT: Writing 1 byte to a CCC access invalid memory
According to the spec it is valid to write less than attribute length:

BLUETOOTH CORE SPECIFICATION Version 5.1 | Vol 3, Part F
page 2320:

'If the attribute value has a fixed length and the Attribute Value
parameter length is less than or equal to the length of the attribute
value, the octets of the attribute value parameter length shall be
written; all other octets in this attribute value shall be
unchanged.'

So when writting just 1 byte to a CCC that would cause accessing invalid memory:

[00:02:13.530,000] <dbg> bt_gatt.bt_gatt_attr_write_ccc: handle 0x0015 value 16385
[00:02:13.530,000] <dbg> bt_gatt.gatt_ccc_changed: ccc 0x001510a4 value 0x4001

### PR DESCRIPTION
**Pull request by Vudentz**
Although unlikely it is possible that a remote may attempt to send just
1 byte as the write request allows to do that:

BLUETOOTH CORE SPECIFICATION Version 5.1 | Vol 3, Part F
page 2320:

  'If the attribute value has a fixed length and the Attribute Value
  parameter length is less than or equal to the length of the attribute
  value, the octets of the attribute value parameter length shall be
  written; all other octets in this attribute value shall be
  unchanged.'

Fixes #16734

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1205,7 +1205,9 @@ ssize_t bt_gatt_attr_write_ccc(struct bt_conn *conn,
 		return BT_GATT_ERR(BT_ATT_ERR_INVALID_ATTRIBUTE_LEN);
 	}
 
-	value = sys_get_le16(buf);
+	memset(&value, 0, sizeof(value));
+	memcpy(&value + offset, buf, len);
```
Comment (joerchan) [inline subsys/bluetooth/host/gatt.c]: This needs to be:
```mempy((u8_t *)&value + offset, buf, len);```

**Review by joerchan — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: I guess this function could just treat any non-zero offset as invalid and return BT_ATT_ERR_INVALID_OFFSET for that

Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: Same for `len == 0' actually (return BT_ATT_ERR_INVALID_ATTRIBUTE_LEN)

Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Yep, that sounds better indeed. It beats me why someone would send just one byte for a CCC though.

Comment (jhedberg) [reply subsys/bluetooth/host/gatt.c]: So something like:
```
if (offset > 0) {
        return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
}

if (!len || len > sizeof(u16_t)) {
        return BT_GATT_ERR(BT_ATT_ERR_INVALID_ATTRIBUTE_LEN);
}

if (len < sizeof(u16_t)) {
        value = *(u8_t *)buf;
} else {
        value = sys_get_le16(buf)
}
``` 

Thoughts?

Comment (joerchan) [reply subsys/bluetooth/host/gatt.c]: Yes, sounds good.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -1195,17 +1195,21 @@ ssize_t bt_gatt_attr_write_ccc(struct bt_conn *conn,
 {
 	struct _bt_gatt_ccc *ccc = attr->user_data;
 	struct bt_gatt_ccc_cfg *cfg;
-	u16_t value;
+	u16_t value = 0;
```
Comment (joerchan) [inline subsys/bluetooth/host/gatt.c]: Can remove the initialization. The value is always assigned.

**Review by joerchan — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Fixed.

**Review by jhedberg — APPROVED** [review]
