### PR TITLE
Boards qemu cortex m0 timer rework

### LINKED ISSUE #22955: tests/kernel/interrupt fails intermittently on qemu_cortex_m0
**Describe the bug**
```
starting test - test_nested_isr
isr0 running !!
isr0 execution completed !!

    Assertion failed at ZEPHYR_BASE/tests/kernel/interrupt/src/nested_irq.c:91: isr0: (new_val not equal to old_val)
Nested interrupt is not working

FAIL - test_nested_isr
```

I am baffled as to why CI is not failing due to this.

**To Reproduce**

I'm running

```
sanitycheck -T tests/kernel/interrupt/
```

**Expected behavior**
Test passes.

**Impact**
I don't know if this is a problem with the test or the Cortex-M0 implementation.

### PR DESCRIPTION
**Pull request by ioannisg**
QEMU Cortex-M0 Board includes a system timer driver implementation based on the nRF TIMER peripheral, because the RTC peripheral is not supported in QEMU.

In this PR we rework the timer driver, to reflect all recent changes made to the standard nrf RTC timer driver. Various issues with the driver are fixed - including a couple of hacks to make this work with QEMU.

As a result of this rework, we can now re-enable all tests that were currently disabled for cortex-m0 QEMU, namely,
- tests/kernel/common
-  tests/kernel/tickless
- tests/kernel/timer_api (this one was never enabled)

The rework also fixes the tests/kernel/interrupt test for qemu-cortex-m0

In addition to the above, the PR removes the ENTROPY_NRF_FORCE_ALT re-definition in the Board definition and adds a 'timer' label to the timer_api suite.

Fixes #22955 (@andrewboie pls, check)

### CODE REVIEW

File: boards/arm/qemu_cortex_m0/nrf_timer_timer.c [hunk 1]
```diff
@@ -15,10 +15,12 @@
 
 #define TIMER NRF_TIMER0
 
-#define COUNTER_MAX 0xffffffff
+#define COUNTER_MAX (0xFFFFFFFF)
```
Comment (nzmichaelh) [inline boards/arm/qemu_cortex_m0/nrf_timer_timer.c:18]: I'm new to Zephyr, but is there a style guide reason to put constants inside brackets?  If not, they add noise so please remove them.

File: boards/arm/qemu_cortex_m0/nrf_timer_timer.c [hunk 2]
```diff
@@ -31,41 +33,131 @@ static uint32_t counter_sub(uint32_t a, uint32_t b)
 
 static void set_comparator(uint32_t cyc)
 {
-	nrf_timer_cc_set(TIMER, 0, cyc & COUNTER_MAX);
+	nrf_timer_cc_set(TIMER, NRF_TIMER_CC_CHANNEL0, cyc & COUNTER_MAX);
+}
+
+static uint32_t get_comparator(void)
```
Comment (nzmichaelh) [inline boards/arm/qemu_cortex_m0/nrf_timer_timer.c:39]: optional: this function, and many others in this file, are only called once and do nothing but call another function.  Consider hoisting the call out and deleting these.

**Review by ioannisg — COMMENTED** [review]
@nzmichaelh appreciate your review on this PR.
Your comments are legitimate: the reason for the selected coding style on nrf_timer_timer.c is that I wanted the driver to look as identical as possible to nrf_rtc_timer.c driver (see `drivers/timer/nrf_rtc_timer.c`). I've picked that driver as the template, and modified only what was necessary to make the driver work with the TIMER peripheral instead of the RTC).

FYI nrf_rtc_timer.c is the main timer driver for Nordic platforms, while the driver I wrote is only for the QEMU target (that is based on an nRF51 SoC). So I'd rather keep the style of the qemu timer driver based on its template :) Guess it would be easier to later maintain it (i.e. following the developments on the main nrf timer driver)

File: boards/arm/qemu_cortex_m0/nrf_timer_timer.c (hunk 1 above)
Comment (ioannisg) [reply boards/arm/qemu_cortex_m0/nrf_timer_timer.c]: Removed now @nzmichaelh , thanks.

**Comment by ioannisg** [comment]
@nashif @andrewboie pls, take a look. Possibly you could run some testing as well :)
The PR fixes issues on Cortex-M0 QEMU and extends ARCH coverage on the timer-related tests, so I'd hope to get this in early in the 2.4 cycle.

**Comment by stephanosio** [comment]
> QEMU Cortex-M0 Board includes a system timer driver implementation based on the nRF TIMER peripheral, because the RTC peripheral is not supported in QEMU.

@ioannisg So I suppose this should not be necessary if we implement nRF RTC peripheral support in the QEMU?

File: boards/arm/qemu_cortex_m0/Kconfig.defconfig [hunk 3]
```diff
@@ -32,9 +32,6 @@ config SYS_CLOCK_HW_CYCLES_PER_SEC
 config SYS_CLOCK_TICKS_PER_SEC
 	default 100
 
-config ENTROPY_NRF_FORCE_ALT
-	default y
```
Comment (stephanosio) [inline boards/arm/qemu_cortex_m0/Kconfig.defconfig:36]: This is not a redefinition of the `ENTROPY_NRF_FORCE_ALT` Kconfig symbol, but a default configuration specification.

Note that `ENTROPY_NRF_FORCE_ALT` is not `default y` in `Kconfig.nrf5`.

**Review by stephanosio — CHANGES_REQUESTED** [review]

File: boards/arm/qemu_cortex_m0/Kconfig.defconfig (hunk 3 above)
Comment (ioannisg) [reply boards/arm/qemu_cortex_m0/Kconfig.defconfig:36]: > > QEMU Cortex-M0 Board includes a system timer driver implementation based on the nRF TIMER peripheral, because the RTC peripheral is not supported in QEMU.
> 
> @ioannisg So I suppose this should not be necessary if we implement nRF RTC peripheral support in the QEMU?

Correct.

**Comment by ioannisg** [comment]
> > QEMU Cortex-M0 Board includes a system timer driver implementation based on the nRF TIMER peripheral, because the RTC peripheral is not supported in QEMU.
> 
> @ioannisg So I suppose this should not be necessary if we implement nRF RTC peripheral support in the QEMU?



> > QEMU Cortex-M0 Board includes a system timer driver implementation based on the nRF TIMER peripheral, because the RTC peripheral is not supported in QEMU.
> 
> @ioannisg So I suppose this should not be necessary if we implement nRF RTC peripheral support in the QEMU?

Correct

File: boards/arm/qemu_cortex_m0/Kconfig.defconfig (hunk 3 above)
Comment (ioannisg) [reply boards/arm/qemu_cortex_m0/Kconfig.defconfig:36]: Yeap, I cleaned the commit message now, thanks @stephanosio

**Comment by ioannisg** [comment]
@stephanosio could you take another look?

@nashif @andrewboie ping for testing and review

File: boards/arm/qemu_cortex_m0/nrf_timer_timer.c (hunk 2 above)
Comment (andrewboie) [reply boards/arm/qemu_cortex_m0/nrf_timer_timer.c:39]: I imagine these were placed here for code clarity and with optimization level would just be inlined.

**Review by tyrantlizard77 — APPROVED** [review]
I tested this with good results. Not an expert on this HW but the code looks reasonable.

**Review by andyross — APPROVED** [review]
Timer logic all seems fine.  I have to admit I still don't understand the point of maintaining a driver exclusively for use by qemu (vs. just using Systick or whatever, which is a driver for real hardware that qemu happens to emulate).

**Comment by ioannisg** [comment]
> Timer logic all seems fine. I have to admit I still don't understand the point of maintaining a driver exclusively for use by qemu (vs. just using Systick or whatever, which is a driver for real hardware that qemu happens to emulate).

@andyross , in Cortex-M0 ARCHitecture the SysTick peripheral is optional and nRF51 (which is the SoC QEMU emulates) does not have it. So this was never an option. QEMU _should_ be supporting the nRF RTC peripheral; then we could just use the nRF RTC timer. But QEMU guys only chose to support the TIMER peripheral; hence, I had to write this driver myself. :( 

I think @stephanosio has implied that we could help QEMU to support RTC for nRF51 - then we could get rid of this driver. Could be future work!

**Review by stephanosio — APPROVED** [review]

**Comment by stephanosio** [comment]
> I think @stephanosio has implied that we could help QEMU to support RTC for nRF51 - then we could get rid of this driver. Could be future work!

I have quite a few ARM-related upstream QEMU patches that I have to revisit some time in the future. I might have a go at it when I do that later; after all, the nRF RTC peripheral looks simple enough.

**Comment by ioannisg** [comment]
> I have quite a few ARM-related upstream QEMU patches that I have to revisit some time in the future. I might have a go at it when I do that later; after all, the nRF RTC peripheral looks simple enough.

@stephanosio , the HAL API of the RTC is pretty much similar to TIMER (that's why it was rather easy for me to write the driver).
So I guess supporting RTC in QEMU should be straightforward. If you have any patch about this, share with me, and I could assist with reviewing and testing it. Thanks in advance.
