### PR TITLE
stm32: uart: fix non-LP UARTs with PM

### LINKED ISSUE #94036: stm32wle5: non-LP UART not working with stop2 mode
### Describe the bug

I'm working on a device based on the RAK3172 chip, it contains a STM32WLE5CC micro-controller. USART2 is used  (only in run mode and only in TX mode, no RX) but the following issues occur:

## REACK stays at the reset value

Reference document [RM0461 rev 10](https://www.st.com/resource/en/reference_manual/rm0461-stm32wlex-advanced-armbased-32bit-mcus-with-subghz-radio-solution-stmicroelectronics.pdf) §33.8.9: *If the USART does not support the wake-up from Stop feature, this bit is reserved and kept at reset value.*

`uart_stm32_suspend_setup()` infinitely waits for REACK to be set.

Would it safe to wait for `REACK` only if `wakeup_source` is true?

## Configuration lost during stop2

For now, `uart_stm32_pm_action()` calls `uart_stm32_init()` only when exiting standby mode:

```c
static int uart_stm32_pm_action(const struct device *dev,
			       enum pm_device_action action)
{
	const struct uart_stm32_config *config = dev->config;
	struct uart_stm32_data *data = dev->data;
	int err;


	switch (action) {
	case PM_DEVICE_ACTION_RESUME:
		/* ... */
		if ((IS_ENABLED(CONFIG_PM_S2RAM)) &&
			(!LL_USART_IsEnabled(config->usart))) {
			/* When exiting low power mode, check whether UART is enabled.
			 * If not, it means we are exiting Suspend to RAM mode (STM32
			 * Standby), and the driver needs to be reinitialized.
			 */
			uart_stm32_init(dev);
		}
		break;
	/* ... */
}
```

In my application, USART2 fails when resumed like this but works if `uart_stm32_init()` is called unconditionally.

How to update the `if` test to handle the case where the configuration is lost because of a stop2 mode on a non-LP UART? e.g.:

```c
if (((IS_ENABLED(CONFIG_PM_S2RAM)) && (!LL_USART_IsEnabled(config->usart))) ||
	(IS_WAKE_FROM_STOP2() && IS_NOT_LP(dev)))

```

## DMA unconditional init

In my application, USART2 uses the ASYNC API. When `uart_stm32_init()` is called on each resume, the DMA is also configured on each resume, which leads to the following error but the application works just fine:

```
[00:00:02.145,000] <err> dma_stm32: dma stream 1 is busy.
[00:00:02.145,000] <err> dmamux_stm32: cannot configure the dmamux.
[00:00:02.145,000] <err> uart_stm32: UART ERR: RX DMA config failed!
```

I wanted to add an `already_initialized` fiel d in the `uart_stm32_config` struct but it is always used as const.
Is there a way to add per-device runtime flags or to check whether the DMA is already initialized? 

It is also possible to de-init the DMA on suspend but it seems a bit wasteful.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Build and run the [test application](https://github.com/mickael868/zephyr_usart_stop2_test) With a way to see what happens on USART2 TX (PORTA2) and the LED (PORTA9).

The LED keeps blinking but USART2 stops emitting after few seconds.

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- OS: Linux
- Toolchain: SDK 0.17.1
- Zephyr: main (commit 7a8bd3dbe75)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mickael868**
When the system goes to STOP2 mode, non-LP USARTs loose their configuration. This patch tests if the USART Enable bit is reset on wake-up, and if so, it re-configures the registers.

Related to [this issue](https://github.com/zephyrproject-rtos/zephyr/issues/94036).

Tested on a STM32WLE5 target.

Also fix a typo.

### CODE REVIEW

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -2333,6 +2333,14 @@ static int uart_stm32_pm_action(const struct device *dev,
 			 */
 			uart_stm32_init(dev);
 		}
+
+		/* Non-LP UART peripherals loose their registers in STOP2 mode. */
+		else if (!LL_USART_IsEnabled(config->usart)) {
```
Comment (etienne-lms) [inline drivers/serial/uart_stm32.c]: Prefer:
```suggestion
		} else if (!LL_USART_IsEnabled(config->usart)) {
			/* Non-LP UART peripherals loose their registers in STOP2 mode */

**Review by etienne-lms — COMMENTED** [review]
Could you update the commit header line to a more standard one:
```patch
-stm32: uart: fix non-LP UARTs with PM
+drivers: serial: stm32: fix non-LP UARTs with PM
```

File: drivers/serial/uart_stm32.c (hunk 1 above)
Comment (mickael868) [reply drivers/serial/uart_stm32.c]: Thanks, done.

**Comment by mickael868** [comment]
The `if ()` block I added is similar to the existing block right above. Maybe we could merge both with something like:

```c

if (!LL_USART_IsEnabled(config->usart)){
    /* When exiting low power mode, check whether UART is enabled.
     * If not, it means that the peripheral configuration has been erased
     * by the low power mode.
     * Either do a full re-initialization after a Suspend to RAM mode (STM32
     * Standby), or simply configure the registers after a STOP2 mode.
     */
    if (IS_ENABLED(CONFIG_PM_S2RAM)){
        err = uart_stm32_init(dev);
    }

    else{
        err = uart_stm32_registers_configure(dev);
    }

    if (err < 0)
    {
        return err;
    }
}
```

**Comment by erwango** [comment]
> The if () block I added is similar to the existing block right above. Maybe we could merge both with something like:

That would be cleaner indeed, thanks.

**Comment by etienne-lms** [comment]
Agree with a (nitpicking) small change:
```patch
    if (IS_ENABLED(CONFIG_PM_S2RAM)){
        err = uart_stm32_init(dev);
-    }
-
-    else{
+    } else {
        err = uart_stm32_registers_configure(dev);
    }
```
Also add in the commit message that your change also reports possible `uart_stm32_init()` error status that was missing.

**Comment by etienne-lms** [comment]
~~@mickael868, please check compliance test review comments on coding style issues.~~
**(edited)** discard my comment :-)

**Review by etienne-lms — DISMISSED** [review]

File: drivers/serial/uart_stm32.c [hunk 2]
```diff
@@ -2318,20 +2316,28 @@ static int uart_stm32_pm_action(const struct device *dev,
 		}
 
 		/* Enable clock */
```
Comment (mathieuchopstm) [inline drivers/serial/uart_stm32.c]: Nit: while we're at it
```suggestion
		/* Enable bus clock */
```

File: drivers/serial/uart_stm32.c [hunk 3]
```diff
@@ -2318,20 +2316,28 @@ static int uart_stm32_pm_action(const struct device *dev,
...
-		if ((IS_ENABLED(CONFIG_PM_S2RAM)) &&
-			(!LL_USART_IsEnabled(config->usart))) {
+		if (!LL_USART_IsEnabled(config->usart)) {
 			/* When exiting low power mode, check whether UART is enabled.
-			 * If not, it means we are exiting Suspend to RAM mode (STM32
-			 * Standby), and the driver needs to be reinitialized.
+			 * If not, it means that the peripheral configuration has been erased
+			 * by the low power mode.
+			 * Either do a full re-initialization after a Suspend to RAM mode (STM32
+			 * Standby), or simply configure the registers after a STOP2 mode.
```
Comment (mathieuchopstm) [inline drivers/serial/uart_stm32.c]: I would prefer a more explicit documentation. Looking at STM32WL5 RefMan (+ some unrelated rewording), I propose:
```suggestion
			 * If not, it means the peripheral has been powered down
			 * by the low-power mode. If suspend-to-RAM is enabled,
			 * assume the entire SoC has been powered down and do a
			 * full re-initialization. Otherwise, assume that the
			 * low-power mode shut down power to the UART but not
			 * critical peripherals (CPU, GPIO, RCC), which means
			 * we only have to reconfigure this UART instance.
			 *
			 * STOP2 on STM32WLE5 is an example of such low-power mode.
```

**Review by etienne-lms — APPROVED** [review]

**Review by erwango — APPROVED** [review]
Non-blocking: Please avoid mixing functional changes and reformating in the same commit (next time).

**Review by mathieuchopstm — APPROVED** [review]
