### PR TITLE
net: wifi: shell: Avoid declaring variables after case statement

### LINKED ISSUE #70792: Wi-Fi: Compilation Errors
**Description**
The changes made to the Wi-fi shell it fails to compile(Add support to configure BSSID in Wi-Fi connect command #70024). This is a known issue with C case statements.

> /subsys/net/l2/wifi/wifi_shell.c:507:4: error: a label can only be part of a statement and a declaration is not a statement
>   507 |    long channel = strtol(optarg, &endptr, 10);

**Impact**
Showstopper

**Logs and console output**

> /subsys/net/l2/wifi/wifi_shell.c:507:4: error: a label can only be part of a statement and a declaration is not a statement
>   507 |    long channel = strtol(optarg, &endptr, 10);

**Additional context**
By adding an additional statement the compiler ignores that 'issue'
```
		case 'c': //Break Comment to resolve compile error
			long channel = strtol(optarg, &endptr, 10);
```

### PR DESCRIPTION
**Pull request by jukkar**
Some compilers have trouble parsing variables directly after a case statement.

Fixes: #70792

### CODE REVIEW

File: subsys/net/l2/wifi/wifi_shell.c [hunk 1]
```diff
@@ -503,7 +503,7 @@ static int __wifi_args_to_params(const struct shell *sh, size_t argc, char *argv
 				PR_WARNING("Passphrase provided without security configuration\n");
 			}
 			break;
-		case 'c':
+		case 'c': {
```
Comment (WilliamGFish) [inline subsys/net/l2/wifi/wifi_shell.c:506]: Could simply add ; to force empty statement
`case 'c': ;`
or declare channel outside the case statement

**Review by WilliamGFish — CHANGES_REQUESTED** [review]
Compilation error

File: subsys/net/l2/wifi/wifi_shell.c (hunk 1 above)
Comment (jukkar) [reply subsys/net/l2/wifi/wifi_shell.c:506]: I think the comment you mentioned in the issue is good option then, having `;` itself you cause some confusion.

**Review by rlubos — DISMISSED** [review]

**Review by rlubos — APPROVED** [review]

**Review by krish2718 — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
