### PR TITLE
mgmt/mcumgr: Fix image erase returning improper error code on error

### LINKED ISSUE #50522: mgmt: mcumgr: img_mgmt: Failure of erase returns nothing
**Describe the bug**
In `subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt.c` is this code:
```
	ok = zcbor_map_decode_bulk(zsd, image_erase_decode,
		ARRAY_SIZE(image_erase_decode), &decoded) == 0;

	if (!ok) {
		return MGMT_ERR_EINVAL;
	}
...
	rc = img_mgmt_impl_erase_slot(slot);

	if (rc != 0) {
		img_mgmt_dfu_stopped();
	}

	if (rc == 0) {
		ok = zcbor_tstr_put_lit(zse, "rc")      &&
		     zcbor_int32_put(zse, 0);
	}

	return ok ? MGMT_ERR_EOK : MGMT_ERR_EMSGSIZE;
```
This code, should `img_mgmt_impl_erase_slot` return an error, will return an empty response to the mcumgr client, which is not valid

**Expected behavior**
The error code should be returned to the client

**Impact**
Showstopper as function is not within specification

**Environment (please complete the following information):**
 - Commit SHA or Version used: 55c4e06b35639d525d214cb3432740a489b7147f

### PR DESCRIPTION
**Pull request by de-nordic**
The img_mgmt_erase could return MGMT_ERR_EOK even when img_mgmt_impl_erase_slot failed.

Fixes #50522

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

File: subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt.c [hunk 1]
```diff
@@ -278,13 +278,10 @@ img_mgmt_erase(struct mgmt_ctxt *ctxt)
 		}
 	}
 
-	rc = img_mgmt_impl_erase_slot(slot);
-
-	if (rc != 0) {
+	if (img_mgmt_impl_erase_slot(slot) != 0) {
```
Comment (nordicjm) [inline subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt.c:281]: This should return the result code directly, e.g. for the code I'm working on this function can return busy

**Review by nordicjm — DISMISSED** [review]

File: subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt.c [hunk 2]
```diff
@@ -279,15 +279,13 @@ img_mgmt_erase(struct mgmt_ctxt *ctxt)
...
 		img_mgmt_dfu_stopped();
+		return rc;
 	}
 
-	if (rc == 0) {
-		ok = zcbor_tstr_put_lit(zse, "rc")      &&
-		     zcbor_int32_put(zse, 0);
-	}
+	ok = zcbor_tstr_put_lit(zse, "rc")      &&
+	     zcbor_int32_put(zse, 0);
```
Comment (fabiobaltieri) [inline subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt.c:288]: how about:

```c
if (zcbor_tstr_put_lit(zse, "rc") && zcbor_int32_put(zse, 0)) {
        return MGMT_ERR_EOK;
}
return MGMT_ERR_EMSGSIZE;
```

Comment (de-nordic) [reply subsys/mgmt/mcumgr/lib/cmd/img_mgmt/src/img_mgmt.c]: Yeah, will take it.

**Review by nordicjm — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]
