### PR TITLE
net: gptp: Use local port identity when forwarding sync messages

### LINKED ISSUE #68385: Wrong port indentity when forwarding sync messages
As defined in IEEE802.1AS-2020 ch. 10.2.12.2.1, the port identity of an MDSyncSend structure sent from a port shall be set to the port identity of the sending port according to and ch. 8.5.2.
Currently, when using a switched end device with multiple ports as shown below (Dev-B), forwarded sync messages (from Dev-A) will keep the port identity of the origin. Therefore, a slave connected to the switched end device (Dev-C) will not accept the sync messages.

<pre>
 ┌─────────┐                ┌─────────┐              ┌─────────┐
 │         │                │         │              │         │
 │  DEV-A  ├────────────────►  DEV-B  ├──────────────►  DEV-C  │
 │         │                │         │              │         │
 └─────────┘                └─────────┘              └─────────┘
</pre>

Within the PortSyncSyncSend state machine, the forwading ports identity should be copied as shown in the patch below before sending it to the MD layer.

```diff
git a/subsys/net/l2/ethernet/gptp/gptp_mi.c b/subsys/net/l2/ethernet/gptp/gptp_mi.c
index 03c8ee3ef0..8baef1b15d 100644
--- a/subsys/net/l2/ethernet/gptp/gptp_mi.c
+++ b/subsys/net/l2/ethernet/gptp/gptp_mi.c
@@ -560,6 +560,14 @@ static void gptp_mi_pss_send_state_machine(int port)
                k_timer_start(&state->half_sync_itv_timer, duration,
                              K_NO_WAIT);

+               /* sourcePortIdentity is set to the portIdentity of this
+                * PTP Port (see ch. 10.2.12.2.1 and 8.5.2). */
+               memcpy(&state->pss_sync_ptr->sync_info.src_port_id.clk_id,
+                       GPTP_DEFAULT_DS()->clk_id,
+                       GPTP_CLOCK_ID_LEN);
+               state->pss_sync_ptr->sync_info.src_port_id.port_number = port;
+
+
                gptp_mi_pss_send_md_sync_send(port);

                __fallthrough;
```

PR will follow.

`

### PR DESCRIPTION
**Pull request by mschappa**
As defined in IEEE802.1AS-2020 ch. 10.2.12.2.1, the port identity of an MDSyncSend structure sent from a port shall be set to the port identity of the sending port according to and ch. 8.5.2.

This commit replaces the port identity before forwarding a sync.

Fixes #68385

### CODE REVIEW

File: subsys/net/l2/ethernet/gptp/gptp_mi.c [hunk 1]
```diff
@@ -560,6 +560,15 @@ static void gptp_mi_pss_send_state_machine(int port)
 		k_timer_start(&state->half_sync_itv_timer, duration,
 			      K_NO_WAIT);
 
+		/* sourcePortIdentity is set to the portIdentity of this
+		 * PTP Port (see ch. 10.2.12.2.1and ch 8.5.2).
```
Comment (jukkar) [inline subsys/net/l2/ethernet/gptp/gptp_mi.c:564]: space missing before "and" word

**Review by jukkar — COMMENTED** [review]
LGTM, minor nit about the typo in the comment

File: subsys/net/l2/ethernet/gptp/gptp_mi.c (hunk 1 above)
Comment (mschappa) [reply subsys/net/l2/ethernet/gptp/gptp_mi.c]: Thx ... I updated the PR.

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
