### PR TITLE
shell: backends: uart: implement pm_device_runtime

### LINKED ISSUE #98680: Shell UART backend is unresponsive if PM device runtime is enabled
### Describe the bug

The uart shell backend becomes unresponsive if PM_DEVICE_RUNTIME is used with the uart device used by the backend.

The reason for this is that unlike the logging uart backend, the shell uart backend does not call pm_device_runtime_get()/put() on the uart device while its in use.

This issue will affect any target which has a UART driver which implements device power management, and does not self get/put itself for polling, async, and interrupt API calls, so most of them, including nordic nrf, nxp and stm32

### Regression

- [ ] This is a regression.

### Steps to reproduce

Run the following command
```
west build -p -b <target> zephyr/samples/hello_world/ -DCONFIG_SHELL=y -DCONFIG_PM_DEVICE=y -DCONFIG_PM_DEVICE_RUNTIME=y -DCONFIG_PM_DEVICE_RUNTIME_DEFAULT_ENABLE=y
```
for either of the following:
* nrf5l15dk/nrf54l15/cpuapp
* b_u585i_iot02a
* frdm_ke15z

### Relevant log output

```shell
*** Booting Zephyr OS build v4.3.0-rc1-161-g4d8645656178 ***
Hello World! b_u585i_iot02a/stm32u585xx
```

Relevant as no shell input is received and echoed back.

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

Debian 12
Zephyr revision is recent main: sha 0f5e03f1fcba4326baf4507c343f3609bf32c524

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bjarki-andreasen**
The UART device used by the backend needs to be gotten before use, and put after. In limited cases, device drivers call pm_device_runtime_get() as part of the call to uart_rx_enable(), this is not the case for polling, nor interrupt driven API calls for most if not all drivers, nor is that expected.

Implement pm_device_runtime calls in shell uart backend similar to the logging uart backend to support all uart drivers in all configurations.

fixes: #98680

### CODE REVIEW

**Review by ceolin — DISMISSED** [review]

File: subsys/shell/backends/shell_uart.c [hunk 1]
```diff
@@ -300,6 +302,11 @@ static int init(const struct shell_transport *transport,
 	k_fifo_init(&common->smp.buf_ready);
 #endif
 
+	ret = pm_device_runtime_get(common->dev);
+	if (ret) {
```
Comment (pdgendt) [inline subsys/shell/backends/shell_uart.c]:
```suggestion
	if (ret < 0) {
```

Comment (bjarki-andreasen) [reply subsys/shell/backends/shell_uart.c]: pm_device_runtime_get() only returns 0 or negative error code

Comment (bjarki-andreasen) [reply subsys/shell/backends/shell_uart.c]: updated anyway, it may be more readable with the < 0

**Review by pdgendt — APPROVED** [review]

**Comment by bjarki-andreasen** [comment]
ping @jakub-uC

**Review by jakub-uC — APPROVED** [review]

**Review by anangl — APPROVED** [review]
