### PR TITLE
net: lwm2m: Synchronized functions mutating the RD client's state

### LINKED ISSUE #37170: LwM2M lwm2m_rd_client_stop() not working when called during bootstrapping/registration
**Describe the bug**
When external logic calls `lwm2m_rd_client_stop()` while the client is already bootstrapping or registering, it often (not always) does not work:

```
[00:00:20.579,833] net_lwm2m_rd_client: Bootstrap started with endpoint 'urn:cust:ORBITZ-89882390000226837758' with client lifetime 0
[00:00:20.580,169] Modem: Found free socket: 0
[00:00:20.580,200] Modem: Socket created. <ID, FD> : <0, 1>
[00:00:21.073,059] net_lwm2m_rd_client: Stop LWM2M Client: urn:cust:ORBITZ-89882390000226837758
[00:00:21.170,623] Modem: Processing modem command: Socket open
[00:00:21.170,715] Modem: Sending: AT+QIOPEN=1,0,"UDP","10.113.2.99",5684,0,0
[00:00:21.310,760] Modem: Received response: OK
[00:00:21.310,791] Modem: Wait for socket open URC now
[00:00:21.310,821] Modem: Setting timeout for socket 0
[00:00:21.410,980] Modem: Received URC: +QIOPEN: 0,0
[00:00:21.688,903] <err> net_lwm2m_engine: Failed to send packet, err 9
[00:00:21.688,934] <err> net_lwm2m_rd_client: Error sending LWM2M packet (err:-9).
[00:00:21.688,934] <err> net_lwm2m_rd_client: Bootstrap registration err: -9
[00:00:21.789,154] Modem: Processing modem command: Socket close
[00:00:21.789,154] Modem: Closing socket: 0
[00:00:21.789,245] Modem: Sending: AT+QICLOSE=0,0
[00:00:21.911,590] Modem: Received response: OK
[00:00:21.911,621] Modem: Socket 0 closed
[00:00:21.911,621] Modem: Freeing socket 0
[00:00:22.189,239] net_lwm2m_rd_client: Bootstrap started with endpoint 'urn:cust:ORBITZ-89882390000226837758' with client lifetime 0
```

**To Reproduce**
See above log, but in short:
1. Use a Zephyr version akin to [Nordic sdk-zephyr v2.4.99-ncs2](https://github.com/nrfconnect/sdk-zephyr/tree/v2.4.99-ncs2) (I checked the more recent git history, but I don't see anything directly addressing this issue. Currently we can't update to the async socket version yet)
2. Start RD Client
3. Call `lwm2m_rd_client_stop()` while the RD client is still bootstrapping/registering (preferably ASAP)
4. Observe that bootstrapping/registration is restarted, I think due to `sm_do_network_error()`

**Expected behavior**
The RD client to stop completely (and remain so until explicitly started again)

**Impact**
Data communication where we do not expect and want it. More power consumption etc.

### PR DESCRIPTION
**Pull request by MaikVermeulen**
A mutex is used to syncrhonize the start, stop and service() functions of
the RD client. Previously it could happen that while service() was working
on e.g. bootstrapping, a stop() call by another thread would close the socket.
Then the bootstrapping process would detect it as a network error, and restart
the process.

Fixes #37170.

Signed-off-by: Maik Vermeulen maik.vermeulen@innotractor.com

### CODE REVIEW

File: subsys/net/lib/lwm2m/lwm2m_rd_client.c [hunk 1]
```diff
@@ -1040,11 +1048,15 @@ void lwm2m_rd_client_start(struct lwm2m_ctx *client_ctx, const char *ep_name,
 	strncpy(client.ep_name, ep_name, CLIENT_EP_LEN - 1);
 	client.ep_name[CLIENT_EP_LEN - 1] = '\0';
 	LOG_INF("Start LWM2M Client: %s", log_strdup(client.ep_name));
+
+	k_mutex_unlock(&client.mutex);
```
Comment (rlubos) [inline subsys/net/lib/lwm2m/lwm2m_rd_client.c:1052]: You should also unlock the mutex at early exit, at line 1038.

**Review by rlubos — COMMENTED** [review]
Looks good, just one issue spotted.

**Review by rlubos — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]
