### PR TITLE
Bluetooth: iso: make TX path service all connections

### LINKED ISSUE #74321: Bluetooth host: bt_conn_tx_processor() does not handle multiple ISO connections being ready correctly
**Describe the bug**
When multiple ISO payloads are generated at the same time (as in some BSim tests), only one of the connections are processed by `bt_conn_tx_processor()`. The other(s) are only processed after the next call to `bt_conn_data_ready()` - which is likely at the next ISO event, i.e. way too late.

The issue arises because tx_data_pull (iso_data_pull in this case) eventually returns NULL after the payload(s) for a particular ISO "connection" has been handled - and this causes bt_conn_tx_processor() to stop completely instead of re-launching itself via `bt_tx_irq_raise`.

This bug was introduced by PR #72090.

**To Reproduce**
Run BSim test cap_broadcast_ac_13.sh and look at the iso_data_pull trace output.

**Expected behavior**
All ISO payloads should get processed

**Impact**
Breaks multiple concurrent ISO streams (at the very least; ACL connections are probably impacted as well)

**Logs and console output**
Excerpt from a trace from PR #74244 (where this was found):
```
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_iso: bt_iso_chan_send: send-iso (no ts)�[0m
d_00: @00:00:01.387051  conn_iso_send conn 0x84e8c80 buf 0x85787a8 has_ts 0
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_iso: conn_iso_send: 0x85787a8 put on list�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_data_ready: DR�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_data_ready: already in list�[0m
d_00: @00:00:01.387051  broadcast_sent_cb Sent payload with seq_num: 183 on stream 0x84a3980
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: tx_notify: raise TX IRQ�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: tx_complete_work: conn 0x84e8d5c�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: tx_notify: conn 0x84e8d5c�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: tx_notify: tx 0x84d6f60 cb 0x81a1d6b user_data (nil)�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: tx_free: 0x84d6f60�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_iso: bt_iso_chan_send: send-iso (no ts)�[0m
d_00: @00:00:01.387051  conn_iso_send conn 0x84e8d5c buf 0x85787d0 has_ts 0
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_iso: conn_iso_send: 0x85787d0 put on list�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_data_ready: DR�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_data_ready: raised�[0m
d_00: @00:00:01.387051  broadcast_sent_cb Sent payload with seq_num: 183 on stream 0x84a39c4
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: tx_notify: raise TX IRQ�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_tx_processor: start�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: should_stop_tx: 0x84e8c80�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_tx_processor: processing conn 0x84e8c80�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_iso: iso_data_pull: conn 0x84e8c80 amount 255�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_iso: iso_data_pull: last frag, pop buf 0x8578780�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_tx_processor: pop: cb 0x81a1d6b userdata (nil)�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_tx_processor: TX process: conn 0x84e8c80 buf 0x8578780 (last)�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: send_buf: conn 0x84e8c80 buf 0x8578780 len 102 buf->len 102�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: conn_tx_alloc: 0x84d6f78�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: send_buf: move 0x8578780 ref in�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: get_data_frag: get-acl-frag: outside 0x8578780 window 0x857bbc0 size 102�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: send_buf: send frag: buf 0x8578780 len 102�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: send_buf: conn 0x84e8c80 buf 0x857bbc0 len 102 flags 0x02�[0m
d_00: @00:00:01.387051  hci_iso_handle BIS payload for source_hdl 0 (HCI handle 3) with ts: 1377899/1377899
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: frag_destroy: �[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_tx_processor: start�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: should_stop_tx: 0x84e8c80�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_tx_processor: processing conn 0x84e8c80�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_iso: iso_data_pull: conn 0x84e8c80 amount 255�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_iso: iso_data_pull: last frag, pop buf 0x85787a8�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_tx_processor: pop: cb 0x81a1d6b userdata (nil)�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: bt_conn_tx_processor: TX process: conn 0x84e8c80 buf 0x85787a8 (last)�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: send_buf: conn 0x84e8c80 buf 0x85787a8 len 102 buf->len 102�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: conn_tx_alloc: 0x84d6f84�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: send_buf: move 0x85787a8 ref in�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: get_data_frag: get-acl-frag: outside 0x85787a8 window 0x857bbc0 size 102�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: send_buf: send frag: buf 0x85787a8 len 102�[0m
d_00: @00:00:01.387051  [00:00:01.387,023] �[0m<dbg> bt_conn: send_buf: conn 0x84e8c80 buf 0x857bbc0 len 102 flags 0x02�[0m
d_00: @00:00:01.387051  hci_iso_handle BIS payload for source_hdl 0 (HCI handle 3) with ts: 1377899/1377899
```

**Environment (please complete the following information):**
 - OS: Linux (Debian 12)
 - Toolchain: Using Zephyr CI docker image 
 - Commit SHA: d45605e6a3dfe68e43207d15e3bfc003cbfaa72f

### PR DESCRIPTION
**Pull request by jori-nordic**
ISO connections that were in the TX queue were not getting serviced in time. This happens because `iso_data_pull()` returns `NULL` when that particular connection (`conn`) is done sending.

But it doesn't trigger the TX processor again to process other channels in the queue. This patch fixes that by calling `bt_tx_irq_raise()`.

We can't do this from `conn.c` as we don't know if the `NULL` returned is because the current channel is out of data or because it has data but it can't send it (e.g. the current buf is being "viewed" already).

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/74321

### CODE REVIEW

File: subsys/bluetooth/host/iso.c [hunk 1]
```diff
@@ -759,6 +762,9 @@ static struct net_buf *iso_data_pull(struct bt_conn *conn,
 		LOG_DBG("channel has been disconnected");
 		__ASSERT_NO_MSG(b == frag);
 
+		/* Service other connections */
+		bt_tx_irq_raise();
```
Comment (Thalley) [inline subsys/bluetooth/host/iso.c:766]: Do we need this in the `if (bt_buf_has_view(frag)) {` clause? 

It says it shouldn't happen, but wouldn't the same issue occur if that happens?

**Review by Thalley — APPROVED** [review]

**Review by theob-pro — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/iso.c (hunk 1 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/iso.c:766]: I haven't managed to exercise it yet, so I'm not sure.

**Comment by jori-nordic** [comment]
This is also an issue (to a lesser extent because of **A**CL) for L2CAP.

I'm making a test for it, but it's kinda hard to measure from the test code itself. I'll raise a PR for ACL today or tomorrow.

**Comment by jori-nordic** [comment]
L2CAP/ACL PR: https://github.com/zephyrproject-rtos/zephyr/pull/74401

**Review by jhedberg — APPROVED** [review]

**Review by alwa-nordic — COMMENTED** [review]
I think this is not a correct fix. See https://github.com/zephyrproject-rtos/zephyr/pull/74401#pullrequestreview-2127348239
