### PR TITLE
lib: os: cbprinf prevent circular includes

### LINKED ISSUE #36486: LOG2 - self referential macro
**Describe the bug**
Inside LOG2 in specific configuration the __ASSERT macro references to itself.

**To Reproduce**
- Use sample hello_world
- Prepare: code for any platform (like native_posix)
- Set:
    - LOG=y
    - LOG_MODE=LOG2_MODE_DEFERRED
    - LOG_PRINTK=y
    - ASSERT=y
    - CBPRINTF_STATIC_PACKAGE_CHECK_ALIGNMENT=y

**Expected behavior**
Code should compile

**Impact**
Hard to say - very specific configuration required. It should be corrected by does not seem to have really big impact. Disabling CBPRINTF_STATIC_PACKAGE_CHECK_ALIGNMENT would make the problem disappear.

**Logs and console output**
I would not include the console output. It is really easy to recreate.
You would see that there is a macro self referencing to itself:

__ASSERT -> __ASSERT_LOC -> __ASSERT_PRINT -> printk -> Z_LOG_PRINTK -> Z_LOG_MSG2_CREATE -> Z_LOG_MSG2_CREATE2 -> CBPRINTF_STATIC_PACKAGE -> Z_CBPRINTF_STATIC_PACKATE -> Z_CBPRINTF_STATIC_PACKAGE_GENERIC -> __ASSERT

### PR DESCRIPTION
**Pull request by nordic-krch**
When printk is redirected to logging (`CONFIG_LOG_PRINTK`) then `printk.h` includes `log_msg2.h` which includes `cbprintf_internal.h` which includes `__assert.h` which includes `printk.h`.

Fixing it by adding compile time switches for including and using asserts in cbprintf and forcing to not use them when `LOG_PRINTK` is set.

Fixes #36486.

### CODE REVIEW

File: include/sys/cbprintf_internal.h [hunk 1]
```diff
@@ -13,7 +13,10 @@
 #include <stdint.h>
 #include <toolchain.h>
 #include <sys/util.h>
+
+#if CONFIG_CBPRINTF_STATIC_PACKAGE_CHECK_ALIGNMENT
```
Comment (stephanosio) [inline include/sys/cbprintf_internal.h:17]:
```suggestion
#ifdef CONFIG_CBPRINTF_STATIC_PACKAGE_CHECK_ALIGNMENT
```

Comment (nordic-krch) [reply include/sys/cbprintf_internal.h]: done

**Review by dcpleung — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
