### PR TITLE
drivers: sensor: stm32 Vref sensor calibration on 12bit

### LINKED ISSUE #61368: STM32 b_u585i_iot02a, reading vrefint problem
*
**Describe the bug**
I tried sample, samples\sensor\soc_voltage.

**To Reproduce**
1. west build -p auto -b b_u585i_iot02a samples\sensor\soc_voltage
2. west flash
3. see error

**Expected behavior**
Should vref_1 be around 1,2 V ? ADC1 channel 0.

**Impact**
Minor

**Logs and console output**

*** Booting Zephyr OS build zephyr-v3.4.0-2226-g4cbb9d8f5f46 ***
Sensor voltage[vref_1]: 13.20 V
Sensor voltage[vbat_4]: 3.32 V

**Environment (please complete the following information):**
 - OS:Windows
 - Toolchain Zephyr SDK, 0.16.1
 - latest codes from github

**Additional context**

### PR DESCRIPTION
**Pull request by FRASTM**
The Calibration value of the VRef on stm32U5 is acquired on 14Bit by ADC1 and should be adjusted on 12bit becasue the resolution is 12bit in this stm32_vref driver.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/61368

Not evaluated against other stm32 series.

### CODE REVIEW

**Comment by FRASTM** [comment]
The regex in the samples/sensor/soc_voltage/sample.yaml does not detect correctly the error
PASSED if the console output is 
```
*** Booting Zephyr OS build zephyr-v3.4.0-2146-g24cd2ea1efd8 ***
Sensor voltage[vref_1]: 3.32 V
```

FAILED if the console output is 
```
*** Booting Zephyr OS build zephyr-v3.4.0-2146-g24cd2ea1efd8 ***
Sensor voltage[vref_1]: 13.29 V
```

PASSED if the console output is 
```
*** Booting Zephyr OS build zephyr-v3.4.0-2145-g29d07d6020eb ***
Sensor voltage[vref_1]: 13.29 V
Sensor voltage[vbat_4]: 3.30 V
```

**Review by gautierg-st — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by FRASTM** [comment]
> See my previous comment

stm32U5_adc_vrefint

Actually, The VREFINT Calibration value is measured by the ADC1 on 14bit and stored in the system memory.
In case VREF is read on channel 0 of the AD4 (on 12-bits), the CALIBRATIon value is still given by the system memory and is still a 14-bit value. That must be  converted to a 12-bit value as long as the stm32_vref.c is setting a 12bit resolution.
stm32_vref

**Review by gautierg-st — APPROVED** [review]
You're right, I misunderstood the way it works, sorry.
LGTM

File: drivers/sensor/stm32_vref/stm32_vref.c [hunk 1]
```diff
@@ -86,7 +86,16 @@ static int stm32_vref_channel_get(const struct device *dev, enum sensor_channel
...
+#if defined(CONFIG_SOC_SERIES_STM32U5X)
+	/*
+	 * The VREF CALIBRATION value is acquired on 14 bits
+	 * and the data acquired is on 12 bits
+	 * since the adc_sequence.resolution is 12
+	 */
+	vref = (cfg->cal_mv * (*cfg->cal_addr) >> 2) / data->raw;
+#else
 	vref = cfg->cal_mv * (*cfg->cal_addr) / data->raw;
+#endif /* CONFIG_SOC_SERIES_STM32H5X */
```
Comment (erwango) [inline drivers/sensor/stm32_vref/stm32_vref.c:98]: Is there a way to get this information from device tree (`resolution` property)

**Review by erwango — APPROVED** [review]
