### PR TITLE
toolchain: add GEN_ABSOLUTE_SYM_KCONFIG()

### LINKED ISSUE #31562: unexpected sign-extension in Kconfig linker symbols on 64-bit platforms
**Describe the bug**

Kconfig exposes all Kconfig values as linker symbols in the generated binary. On 64-bit platforms, it appears that if a 32-bit hex value is expressed in Kconfig with a 1 in the most significant bit, this gets sign-extended in the generated linker symbol, as if it were a negative value.

**To Reproduce**

```
diff --git a/boards/x86/up_squared/up_squared_defconfig b/boards/x86/up_squared/up_squared_defconfig
index 5e8005a539..aabd59afb4 100644
--- a/boards/x86/up_squared/up_squared_defconfig
+++ b/boards/x86/up_squared/up_squared_defconfig
@@ -11,3 +11,4 @@ CONFIG_UART_CONSOLE=y
 CONFIG_X2APIC=y
 CONFIG_SMP=y
 CONFIG_MP_NUM_CPUS=2
+CONFIG_KERNEL_VM_SIZE=0xC0000000
```

Do a build and examine the binary:

```
$ nm -n zephyr/zephyr.elf | grep VM_SIZE
ffffffffc0000000 A CONFIG_KERNEL_VM_SIZE
```

**Expected behavior**
`CONFIG_KERNEL_VM_SIZE` should be 0xC0000000 and not 0xffffffffc0000000 

**Impact**
Some build scripts examine the ELF binary to obtain Kconfig values, and will be working with incorrect data.
I *think* the scope of this problem is only these linker symbols, which is are not used by the kernel itself at runtime.

### PR DESCRIPTION
**Pull request by dcpleung**
This adds a new GEN_ABSOLUTE_SYM_KCONFIG() specifically for
generating absolute symbols in assembly for kconfig values.
This is needed as the existing GEN_ABSOLUTE_SYM() with
constraints in extended assembly parses the "value" as
signed 32-bit integers. An unsigned 32-bit integer with
MSB set results in a negative number in the final binary.
This also prevents integers larger than 32-bit. So this
new macro simply puts the value inline within the assembly
instrcution instead of having it as parameter.

Fixes #31562

Signed-off-by: Daniel Leung <daniel.leung@intel.com>

### CODE REVIEW

File: include/toolchain/gcc.h [hunk 1]
```diff
@@ -411,20 +411,35 @@ do {                                                                    \
 		",%B0"                              \
 		"\n\t.type\t" #name ",%%object" :  : "n"(~(value)))
 
+#define GEN_ABSOLUTE_SYM_KCONFIG(name, value)       \
```
Comment (galak) [inline include/toolchain/gcc.h:414]: Any reason not to just define this once?

Comment (galak) [reply include/toolchain/gcc.h:414]: nevermind, see the subtle diff in `object`

**Review by galak — DISMISSED** [review]
I don't think we should call this GEN_ABSOLUTE_SYM_KCONFIG, since its not a Kconfig issue, its more of a 32-bit v 64-bit issue.

We'd have the same issue if we did something like

#define FOOBAR 0x82341234
GEN_ABSOLUTE_SYM(FOOBAR, 1)

So seems like something like GEN_ABSOLUTE_64BIT_SYM or like that would be a better name.

File: include/toolchain/gcc.h [hunk 2]
```diff
@@ -411,20 +411,35 @@ do {                                                                    \
 		",%B0"                              \
```
Comment (galak) [inline include/toolchain/gcc.h:411]: We should add a comment about the sign extension that is happening in GEN_ABSOLUTE_SYM

**Comment by dcpleung** [comment]
The new macro only works if parameter `value` is an integer. It cannot take anything else, like `offsetof()`, as in how `GEN_OFFSET_SYM(S, M)` calls `GEN_ABSOLUTE_SYM(..., offsetsof(S, M))`. Therefore the new macro is suffixed with `_KCONFIG()` to signal its restricted usage.

File: include/toolchain/gcc.h (hunk 2 above)
Comment (dcpleung) [reply include/toolchain/gcc.h:428]: Added comment about `GEN_ABSOLUTE_SYM()` on accepted values, which really is dependent on architecture and toolchain.

**Comment by galak** [comment]
> I thought about using `GEN_ABSOLUTE_SYM_RAW()` or `GEN_ABSOLUTE_SYM_INLINE()`. Maybe those would be better?

What does the RAW and INLINE signify.  I'm not understand the subtle distinction here, so not exactly sure what I'd suggest as a naming convention.

**Comment by dcpleung** [comment]
> What does the RAW and INLINE signify. I'm not understand the subtle distinction here, so not exactly sure what I'd suggest as a naming convention.

RAW means its taking raw value (and not general expressions).
INLINE is that the value is embedded "inline" with assembly instead of being a parameter to the asm block.
However, these two names do not express clearly the differences between them and `GEN_ABSOLUTE_SYM()`. That's another reason why I chose to use KCONFIG suffix.

**Review by jenmwms — APPROVED** [review]
I tested this for up2 similar to how it was reported https://github.com/zephyrproject-rtos/zephyr/issues/31562. We get the expected behavior (resolves the issue). Build and examine the binary:

$ nm -n zephyr/zephyr.elf | grep VM_SIZE

before this patch - 
`ffffffffc0000000 A CONFIG_KERNEL_VM_SIZE`

after this patch - 
`00000000c0000000 A CONFIG_KERNEL_VM_SIZE`

Also, the sample application ran OK on UP2 hardware.

**Review by jhedberg — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Still not a fan of the names, but lets get this in as it fixes a bug.
