### PR TITLE
drivers: spi_rtio: Fix potential null pointer dereference

### LINKED ISSUE #90551: [Coverity CID: 516225] Dereference after null check in drivers/spi/spi_rtio.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/265cfb45a818f39cf03c3527b5d1b21027d3cac1/drivers/spi/spi_rtio.c

Category: Null pointer dereferences
Function: `spi_rtio_copy`
Component: Drivers
CID: [516225](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=516225)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/265cfb45a818f39cf03c3527b5d1b21027d3cac1/drivers/spi/spi_rtio.c#L195

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=516225

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_FORWARD_NULL). ([CWE-476](http://cwe.mitre.org/data/definitions/476.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by sudarsan-22**
Avoid accessing tx_bufs or rx_bufs when they are NULL by adding proper conditional checks before dereferencing. This addresses Coverity issue

CID 516225 (CWE-476).

### CODE REVIEW

**Comment by ljd42** [comment]
Fixes: #90551

**Review by teburd — DISMISSED** [review]
Thanks for fixing this

**Review by ubieda — DISMISSED** [review]
Thanks!

**Review by decsny — DISMISSED** [review]

**Review by tbursztyka — DISMISSED** [review]

File: drivers/spi/spi_rtio.c [hunk 1]
```diff
@@ -192,7 +192,7 @@ int spi_rtio_copy(struct rtio *r,
 		rx_len = rx_bufs->buffers[rx].len;
 	} else {
 		rx_buf = NULL;
-		rx_len = tx_bufs->buffers[tx].len;
+		rx_len = (tx_bufs && tx < tx_count) ? tx_bufs->buffers[tx].len : 0;
```
Comment (kartben) [inline drivers/spi/spi_rtio.c]: as per coding guidelines checking for null pointer should be explicit (expression should have boolean essential type)

```suggestion
		rx_len = (tx_bufs != NULL && tx < tx_count) ? tx_bufs->buffers[tx].len : 0;
```

Comment (sudarsan-22) [reply drivers/spi/spi_rtio.c]: got it ! thank for the review

**Review by kartben — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]
