### PR TITLE
Bluetooth: Controller: Fix Extended Advertising channel use

### LINKED ISSUE #35668: The channel selection of auxiliary advertisments in extended advertisments
Hi, is there any planned support for some heuristic functionality that would dynamically select channels for auxiliary advertisements? We found out that channel 0 is selected as the default for any extended advertising payloads which might be quite unreliable if there is a lot of inference on this particular channel.

Thanks,
Lukas

### PR DESCRIPTION
**Pull request by cvinayak**
Add implementation defined channel index in the auxiliary
pointer of the common extended payload format in the primary
channel PDUs and the same be used in the transmission of
auxiliary PDUs.

Fixes #35668.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h [hunk 1]
```diff
@@ -65,6 +65,26 @@ static inline struct pdu_adv *lll_adv_scan_rsp_peek(struct lll_adv *lll)
...
+	first = pdu->first;
+	if (first != pdu->last) {
+		first += 1U;
+		if (first == DOUBLE_BUFFER_SIZE) {
+			first = 0U;
+		}
+	}
+
+	return (void *)pdu->pdu[first];
+}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:81]: It's a bit confusing that the function peeks the `latest` and then we use a variable named `first` to return the `latest`.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h [hunk 2]
```diff
@@ -65,6 +65,26 @@ static inline struct pdu_adv *lll_adv_scan_rsp_peek(struct lll_adv *lll)
 	return (void *)lll->scan_rsp.pdu[lll->scan_rsp.last];
 }
 
+static inline struct pdu_adv *lll_adv_pdu_latest_peek(struct lll_adv_pdu *pdu)
+{
+	uint8_t first;
+
+	first = pdu->first;
+	if (first != pdu->last) {
+		first += 1U;
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:74]: Just curious: Is there a reason why you are using `+= 1U` instead of `first++`?

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h [hunk 3]
```diff
@@ -65,6 +65,26 @@ static inline struct pdu_adv *lll_adv_scan_rsp_peek(struct lll_adv *lll)
 	return (void *)lll->scan_rsp.pdu[lll->scan_rsp.last];
 }
 
+static inline struct pdu_adv *lll_adv_pdu_latest_peek(struct lll_adv_pdu *pdu)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:68]:
```suggestion
static inline struct pdu_adv *lll_adv_pdu_latest_peek(const struct lll_adv_pdu *pdu)
```

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h [hunk 4]
```diff
@@ -65,6 +65,26 @@ static inline struct pdu_adv *lll_adv_scan_rsp_peek(struct lll_adv *lll)
...
+		first += 1U;
+		if (first == DOUBLE_BUFFER_SIZE) {
+			first = 0U;
+		}
+	}
+
+	return (void *)pdu->pdu[first];
+}
+
+static inline struct pdu_adv *lll_adv_data_latest_peek(struct lll_adv *lll)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:83]:
```suggestion
static inline struct pdu_adv *lll_adv_data_latest_peek(const struct lll_adv *lll)
```

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h [hunk 5]
```diff
@@ -83,6 +103,12 @@ static inline struct pdu_adv *lll_adv_aux_data_peek(struct lll_adv_aux *lll)
 	return (void *)lll->data.pdu[lll->data.last];
 }
 
+static inline struct pdu_adv *
+lll_adv_aux_data_latest_peek(struct lll_adv_aux *lll)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:107]:
```suggestion
lll_adv_aux_data_latest_peek(const struct lll_adv_aux *lll)
```

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h [hunk 6]
```diff
@@ -139,6 +165,12 @@ static inline struct pdu_adv *lll_adv_sync_data_peek(struct lll_adv_sync *lll,
 	return (void *)lll->data.pdu[last];
 }
 
+static inline struct pdu_adv *
+lll_adv_sync_data_latest_peek(struct lll_adv_sync *lll)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:169]:
```suggestion
lll_adv_sync_data_latest_peek(const struct lll_adv_sync *lll)
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 7]
```diff
@@ -448,6 +441,53 @@ int ull_adv_aux_reset_finalize(void)
 	return 0;
 }
 
+uint8_t const *ull_adv_aux_random_addr_get(struct ll_adv_set const *const adv,
+					   uint8_t *const addr)
+{
+	if (addr) {
+		memcpy(addr, adv->rnd_addr, BDADDR_SIZE);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:448]:
```suggestion
		(void)memcpy(addr, adv->rnd_addr, BDADDR_SIZE);
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 8]
```diff
@@ -1060,12 +1116,13 @@ void ull_adv_aux_offset_get(struct ll_adv_set *adv)
 	LL_ASSERT(!ret);
 }
 
-struct pdu_adv_aux_ptr *ull_adv_aux_lll_offset_fill(uint32_t ticks_offset,
-						    uint32_t start_us,
-						    struct pdu_adv *pdu)
+struct pdu_adv_aux_ptr *ull_adv_aux_lll_offset_fill(struct lll_adv_aux *lll_aux,
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:1119]: `lll_aux` looks like it is unused in this function.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 9]
```diff
@@ -1085,18 +1139,18 @@ struct pdu_adv_aux_ptr *ull_adv_aux_lll_offset_fill(uint32_t ticks_offset,
...
 
-	aux = (void *)ptr;
+	aux_ptr = (void *)ptr;
 	offs = HAL_TICKER_TICKS_TO_US(ticks_offset) - start_us;
 	offs = offs / OFFS_UNIT_30_US;
 	if (!!(offs >> 13)) {
-		aux->offs = offs / (OFFS_UNIT_300_US / OFFS_UNIT_30_US);
-		aux->offs_units = 1U;
+		aux_ptr->offs = offs / (OFFS_UNIT_300_US / OFFS_UNIT_30_US);
+		aux_ptr->offs_units = 1U;
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:1147]:
```suggestion
		aux_ptr->offs_units = SCA_VALUE_50_PPM;
```

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 10]
```diff
@@ -1085,18 +1139,18 @@ struct pdu_adv_aux_ptr *ull_adv_aux_lll_offset_fill(uint32_t ticks_offset,
...
 	} else {
-		aux->offs = offs;
-		aux->offs_units = 0U;
+		aux_ptr->offs = offs;
+		aux_ptr->offs_units = 0U;
```
Comment (ppryga) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:1150]:
```suggestion
		aux_ptr->offs_units = SCA_VALUE_500_PPM;
```

**Review by ppryga-nordic — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:74]: > ;-) or `++first` (in C it does not matter, but following general conventions this is the version of incrementation that should be used in situations `x = x + 1`)

That's an old recommendation for old compilers though, right? 
IIRC a long time ago, `++i` and `i++` would result in different code, where `++i` would use one less register or something like that, but I think it's a long time since any reasonable compiler would do this.

Comment (ppryga) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:74]: Yes that is correct. I'm used to go for the pre-incrementation in situations like this.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:74]: The only different I think of, is the size of `first` which is `uint8_t`, and by using `first += 1U;` the compiler has the choice to use a byte instead of a word to add LSB of the registers. Use of unary operator makes sense when the variable is machine word size, in which case an inc instruction will be used.

```
    uint8_t x = 5;
    
    x = x + 1;
```

versus

```
    int i;
    
    i++;
```

But I am not sure, what actually the compiler is doing.

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 8 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:1119]: Good catch.

File: subsys/bluetooth/controller/ll_sw/ull_adv.c [hunk 11]
```diff
@@ -2709,7 +2709,7 @@ static const uint8_t *adva_update(struct ll_adv_set *adv, struct pdu_adv *pdu)
 		if (0) {
 #if defined(CONFIG_BT_CTLR_ADV_EXT)
 		} else if (ll_adv_cmds_is_ext() && pdu->tx_addr) {
-			own_id_addr = ll_adv_aux_random_addr_get(adv, NULL);
+			own_id_addr = ull_adv_aux_random_addr_get(adv, NULL);
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:2712]: hmmm, good point. This function tried to follow `ll_addr_get`, but looks like the memcpy part of the branch is unused in the source base. I will check uses of `ll_addr_get` too and make specific functions instead of the now redundant branching inside the functions.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h]: > first is the first valid (and currently used) PDU in the double buffer,

If that is the way you describe it, `first_valid` might have been a better choice of a name :) 

It isn't something that needs to be changed, but it is a interesting (and unconventional) naming

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h [hunk 12]
```diff
@@ -65,6 +65,28 @@ static inline struct pdu_adv *lll_adv_scan_rsp_peek(struct lll_adv *lll)
 	return (void *)lll->scan_rsp.pdu[lll->scan_rsp.last];
 }
 
+static inline struct pdu_adv *
+lll_adv_pdu_latest_peek(struct lll_adv_pdu const *const pdu)
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:69]: Isn't it more typical to have `const` as the first variable modifier, e.g. 
```suggestion
lll_adv_pdu_latest_peek(const struct lll_adv_pdu *const pdu)
```

This comment applies multiple places.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:69]: Both coding styles are permitted.

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:69]: They are, but I was just wondering if the suggestion from me is more in line with most other occurrences of `const` for the sake of being consistent in the code base.

File: subsys/bluetooth/controller/ll_sw/ull_adv.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (ppryga) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:2712]: Are you going to do that in this PR?

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 13]
```diff
@@ -81,8 +81,8 @@ uint8_t ll_adv_aux_random_addr_set(uint8_t handle, uint8_t const *const addr)
 	return 0;
 }
 
-uint8_t ll_adv_aux_ad_data_set(uint8_t handle, uint8_t op, uint8_t frag_pref, uint8_t len,
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:94]: This line isn't 100 characters though. 

80 is the recommendation, 100 is the max (which will be caught by CI afaik).

[the remark this answers is not in the document]
Comment (ppryga) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:94]: Yes it is just recommendation, so it is allowed to use longer line. 
What more Linux Kernel coding style does not enforce 100 characters either. It is a warning returned by kernel's checkpatch. Please see commit message in this PR: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bdc48fa11e46f867ea4d75fa59ee87a7f48be144.

What more I'm not asking to do a change, I'm just point that this kind of updates is optional and up to committer preferences.

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h (hunk 12 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:69]: > This comment applies multiple places.

This change applies repo wide, hence should be taken up in separate PR and with wider audience.

File: subsys/bluetooth/controller/ll_sw/ull_adv.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_adv.c:2712]: yes

File: subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h (hunk 12 above)
Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h:69]: > > This comment applies multiple places.
> 
> This change applies repo wide, hence should be taken up in separate PR and with wider audience.

Does that mean that the change you are introducing here in this PR should be moved to another PR, or are you suggesting that any revert of this would be done in a separate PR?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv_pdu.h]: I have moved out the `const` qualifier commit. Please re-review.

**Review by ppryga-nordic — COMMENTED** [review]
One nic-picking comment. Besides looks LGTM.

File: subsys/bluetooth/controller/ll_sw/ll_addr.c [hunk 14]
```diff
@@ -81,6 +60,31 @@ uint8_t ll_addr_set(uint8_t addr_type, uint8_t const *const bdaddr)
...
+{
+	uint8_t *addr;
+
+	addr = ll_addr_get(addr_type);
+	if (addr) {
+		memcpy(bdaddr, addr, BDADDR_SIZE);
+	}
+
+	return addr;
+}
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ll_addr.c:86]: Correct me if I am wrong, but this function seems to return the address, as well as store it in the `bdaddr` argument, effectively "returning" it twice. 

Is this by design? It's similar to the memcpy/memset functions, so it's not necessarily wrong, just making sure it is intentional.

File: subsys/bluetooth/controller/ll_sw/ll_addr.c [hunk 15]
```diff
@@ -81,6 +60,31 @@ uint8_t ll_addr_set(uint8_t addr_type, uint8_t const *const bdaddr)
...
+	return pub_addr;
+}
+
+uint8_t *ll_addr_read(uint8_t addr_type, uint8_t *const bdaddr)
+{
+	uint8_t *addr;
+
+	addr = ll_addr_get(addr_type);
+	if (addr) {
+		memcpy(bdaddr, addr, BDADDR_SIZE);
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/ll_addr.c:82]: Should we have an check or an ASSERT ensuring that `bdaddr` is non-NULL?

**Review by Thalley — APPROVED** [review]
All my comments that needed to be addressed have been. 

A few final comments, but otherwise LGTM

File: subsys/bluetooth/controller/ll_sw/ll_addr.c (hunk 15 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ll_addr.c:82]: As the parameter was passed by internal module caller (hci.c or ull_scan.c) a NULL can be avoided.

File: subsys/bluetooth/controller/ll_sw/ll_addr.c (hunk 14 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ll_addr.c:86]: yes, it is by design, was simpler to return a valid pointer or NULL, compared to returning a errno.

**Review by ppryga-nordic — APPROVED** [review]
LGTM
