### PR TITLE
arch: arc: enable divide zero exception

### LINKED ISSUE #33459: Divide zero exception is not enabled in ARC
STATUS32.DZ(bit 13) is the EV_DivZero exception enable bit.

DZ indicates whether the EV_DivZero exception is enabled on division by zero. When DZ is set to 1, any
attempt to execute a DIV, DIVU, REM, or REMU instruction, with a divisor of 0, raises an EV_DivZero
exception. When DZ is set to 0, a division by zero does not raise an exception. The DZ bit is ignored on write
and read as zero when there is no hardware divider configured, regardless of operating mode. The DZ bit is
cleared on interrupt or exception entry, and is restored on return from an interrupt or exception.

we need to enable it explicitly to enable divide zero exception, I‘d like to enable it in initial stage.

### PR DESCRIPTION
**Pull request by IRISZZW**
STATUS32.DZ(bit 13) is the EV_DivZero exception enable bit, and it's
not enabled by default. we need to set it explicitly to enable divide
zero exception on early boot and each thread's setup.

The DZ bit is ignored on write and read as zero when there is no
hardware division configured. So we can simply set DZ bit even if
there is no hardware division configured.

Fix: #33459

### CODE REVIEW

File: arch/arc/core/thread.c [hunk 1]
```diff
@@ -178,6 +178,7 @@ void arch_new_thread(struct k_thread *thread, k_thread_stack_t *stack,
 #ifdef CONFIG_ARC_USE_UNALIGNED_MEM_ACCESS
 	iframe->status32 |= _ARC_V2_STATUS32_AD;
 #endif
+	iframe->status32 |= _ARC_V2_STATUS32_DZ;
```
Comment (ruuddw) [inline arch/arc/core/thread.c:181]: Why not add this to the initial assignments above, as there is no conditional involved.

Comment (IRISZZW) [reply arch/arc/core/thread.c:181]: Like this ?

```
#ifdef CONFIG_USERSPACE
	/* enable US bit, US is read as zero in user mode. This will allow user
	 * mode sleep instructions, and it enables a form of denial-of-service
	 * attack by putting the processor in sleep mode, but since interrupt
	 * level/mask can't be set from user space that's not worse than
	 * executing a loop without yielding.
	 */
	iframe->status32 = _ARC_V2_STATUS32_US | _ARC_V2_STATUS32_DZ;
	if (is_user(thread)) {
		iframe->pc = (uint32_t)z_user_thread_entry_wrapper;
	} else {
		iframe->pc = (uint32_t)z_thread_entry_wrapper;
	}
#else
	iframe->status32 = _ARC_V2_STATUS32_DZ;
	iframe->pc = ((uint32_t)z_thread_entry_wrapper);
#endif /* CONFIG_USERSPACE */
```

Comment (ruuddw) [reply arch/arc/core/thread.c:181]: Yes, that's what I had in mind.

**Review by ruuddw — APPROVED** [review]

**Review by abrodkin — APPROVED** [review]

**Comment by evgeniy-paltsev** [comment]
@nashif do we have any politics in Zephyr about the minimum time before the pull request get merged?

I have significant notes about this, but it has been already merged :/
