### PR TITLE
arch/x86: Make irq_offload SMP-safe on x86_64

### LINKED ISSUE #72172: irq_offload on x86_64 isn't SMP-safe
The implementation of irq_offload() on x86_64 looks like this (see https://github.com/zephyrproject-rtos/zephyr/blob/main/arch/x86/core/intel64/irq_offload.c#L21)

```c
void arch_irq_offload(irq_offload_routine_t routine, const void *parameter)
{
	x86_irq_funcs[CONFIG_IRQ_OFFLOAD_VECTOR - IV_IRQS] = routine;
	x86_irq_args[CONFIG_IRQ_OFFLOAD_VECTOR - IV_IRQS] = parameter;
	__asm__ volatile("int %0" : : "i" (CONFIG_IRQ_OFFLOAD_VECTOR)
			  : "memory");
	x86_irq_funcs[CONFIG_IRQ_OFFLOAD_VECTOR - IV_IRQS] = NULL;
}
```

Note that storage for routine and parameter is static, not per-CPU.  That will race if you have two CPUs doing simultaneous irq_offload() calls.

This is exactly the architecture of the smp_abort test added in #72119 , and indeed it fails spuriously for me at about 3-5% frequency.  Adding logging, you can see that what happens is that the two ISRs get the same argument struct.

(A nice extra is that Peter's test turns out to be a good regression test for this sort of thing in the future)

### PR DESCRIPTION
**Pull request by edersondisouza**
The irq_offload mechanism was using the same entry of the IDT vector for all CPUs on SMP systems. This caused race conditions when two CPUs were doing irq_offload() calls.

This patch addresses that by adding one indirection layer: the irq_offload() now sets a per CPU entry with the routine and parameter to be run. Then a software interrupt is generated, and a default handler will do the appropriate dispatching.

Finally, test "kernel/smp_abort" is enabled for x86 as it should work now.

Fixes #72172.

### CODE REVIEW

File: arch/x86/core/intel64/irq_offload.c [hunk 1]
```diff
@@ -17,12 +17,32 @@
...
+}
 
 void arch_irq_offload(irq_offload_routine_t routine, const void *parameter)
 {
-	x86_irq_funcs[CONFIG_IRQ_OFFLOAD_VECTOR - IV_IRQS] = routine;
-	x86_irq_args[CONFIG_IRQ_OFFLOAD_VECTOR - IV_IRQS] = parameter;
+	int key = arch_irq_lock();
+	uint8_t cpu_id = _current_cpu->id;
+
+	x86_irq_funcs[CONFIG_IRQ_OFFLOAD_VECTOR - IV_IRQS] = dispatcher;
```
Comment (andyross) [inline arch/x86/core/intel64/irq_offload.c:37]: FWIW this bit is now invariant and you could set it up once in an initialization hook somewhere, or use a static interrupt.

File: arch/x86/core/intel64/irq_offload.c [hunk 2]
```diff
@@ -17,12 +17,32 @@
...
+
+	irq_offload_funcs[cpu_id] = routine;
+	irq_offload_args[cpu_id] = parameter;
+
 	__asm__ volatile("int %0" : : "i" (CONFIG_IRQ_OFFLOAD_VECTOR)
 			  : "memory");
-	x86_irq_funcs[CONFIG_IRQ_OFFLOAD_VECTOR - IV_IRQS] = NULL;
+
+	irq_offload_funcs[cpu_id] = NULL;
```
Comment (andyross) [inline arch/x86/core/intel64/irq_offload.c:45]: Seems like this isn't really needed unless you expect to handle spurious interrupts for some reason, which shouldn't ever happen as it's a dedicated IRQ.

**Review by andyross — DISMISSED** [review]
Seems clean.  Some optimization nitpicks

**Comment by edersondisouza** [comment]
v2:
  - Initialize vector only once;
  - Remove useless code.

**Review by peter-mitsis — APPROVED** [review]

**Review by andyross — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
