### PR TITLE
Fix possible NULL pointers de-references spotted in #23299

### LINKED ISSUE #23299: Some bugs or dead codes cased by possible NULL pointers
I have found some bugs cased by possible NULL pointers. Otherwise, if these pointers cannot be NULL, there will be some dead codes. But I think some of them may be NULL in some special cases.

1.
File: subsys/fb/cfb.c
Function: cfb_print
Code:
108	        const struct char_framebuffer *fb = &char_fb;
109          const struct cfb_font *fptr = &(fb->fonts[fb->font_idx]);
110
111	        if (!fb->fonts || !fb->buf) {
112		         return -1;
113	         }
Description: **fb->fronts** on line 111 cannot be NULL, or bug will occur on line 109 because a member of NULL pointer is accessed through **fb->fonts[fb->font_idx]**. 

2.
File: subsys/net/lib/coap/coap.c
Function: coap_packet_parse
Code:
547          if (options) {
548		          memset(options, 0, opt_num * sizeof(struct coap_option));
549	        }
                ...... ......
579	        while (1) {
580		           struct coap_option *option;
581
582		           option = num < opt_num ? &options[num++] : NULL;
Description: **options** on line 547 cannot be NULL, or bug will occur on line 582 because a member of NULL pointer is accessed through **options[num++]** 

3.
File: subsys/net/l2/ieee802154/ieee802154_mgmt.c
Function: ieee802154_scan
Code:
116   	ctx->scan_ctx = scan;
117  	ret = 0;
118
119  	ieee802154_filter_pan_id(iface, IEEE802154_BROADCAST_PAN_ID);
120
121  	if (ieee802154_start(iface)) {
122  		NET_DBG("Could not start device");
123  		ret = -EIO;
124  
125  		goto out;
126  	}
127 
128  	/* ToDo: For now, we assume we are on 2.4Ghz
129  	 * (device will have to export capabilities) */
130  	for (channel = 11U; channel <= 26U; channel++) {
131  		if (IEEE802154_IS_CHAN_UNSCANNED(scan->channel_set, channel)) {
132  			continue;
133  		}
134
135  		scan->channel = channel;
136  		NET_DBG("Scanning channel %u", channel);
137  		ieee802154_set_channel(iface, channel);
138 
139  		/* Active scan sends a beacon request */
140  		if (mgmt_request == NET_REQUEST_IEEE802154_ACTIVE_SCAN) {
141  			net_pkt_ref(pkt);
142  			net_pkt_frag_ref(pkt->buffer);
143
144  			ret = ieee802154_radio_send(iface, pkt, pkt->buffer);
145  			if (ret) {
146  				NET_DBG("Could not send Beacon Request (%d)",
147  					ret);
148  				net_pkt_unref(pkt);
149  
150  				break;
151  			}
152  		}
153 
154  		/* Context aware sleep */
155  		k_sleep(scan->duration);
156  
157  		if (!ctx->scan_ctx) {
158  			NET_DBG("Scan request cancelled");
159  			ret = -ECANCELED;
160 
161  			break;
162  		}
163  	}
Description: **ctx->scan_ctx** cannot be NULL. On line 116, **scan** is assigned to **ctx->scan_ctx**, so if **ctx->scan_ctx** is NULL, **scan** is NULL, too. But On line 155, a member is accesed through **scan->duration** when **k_sleep** is called, so **scan** cannot be NULL, or bug will occur.

4.
File: subsys/bluetooth/mesh/cfg_srv.c
Function: bt_mesh_friend_get
Code:
3419	BT_DBG("conf %p conf->frnd 0x%02x", conf, conf->frnd);
3420
3421	if (conf) {
3422		return conf->frnd;
3423	}
3424
3425	return BT_MESH_FRIEND_NOT_SUPPORTED;
Description: **conf** on line 3421 cannot be NULL, or bug will occur on line 3419 because a member of NULL pointer is accessed through **conf->frnd**.

### PR DESCRIPTION
**Pull request by ceolin**
Fix possible NULL pointers de-references spotted in #23299

This pr address issues 1 and 3. Issue for was already fixed in c97e1aafb124e1906c951721eb2e9bb2b8813a8b and issue 2 would be a problem only due bad API usage.

Fixes #23299

### CODE REVIEW

File: subsys/net/l2/ieee802154/ieee802154_mgmt.c [hunk 1]
```diff
@@ -152,9 +152,9 @@ static int ieee802154_scan(u32_t mgmt_request, struct net_if *iface,
 		}
 
 		/* Context aware sleep */
-		k_sleep(scan->duration);
-
-		if (!ctx->scan_ctx) {
+		if (ctx->scan_ctx) {
```
Comment (andrewboie) [inline subsys/net/l2/ieee802154/ieee802154_mgmt.c]: is `scan` always the same as `ctx->scan_ctx`? I notice that `scan` is itself a parameter to this function, it's a cast from the `data` parameter

**Comment by andrewboie** [comment]
also, please consider a more descriptive title to this PR rather than just a GH ID link

File: subsys/net/l2/ieee802154/ieee802154_mgmt.c (hunk 1 above)
Comment (ceolin) [reply subsys/net/l2/ieee802154/ieee802154_mgmt.c]: yes, it is assigned to ctx->scan_ctx in line 116.

**Review by tyrantlizard77 — APPROVED** [review]

File: subsys/fb/cfb.c [hunk 2]
```diff
@@ -106,12 +106,14 @@ static u8_t draw_char_vtmono(const struct char_framebuffer *fb,
...
 {
 	const struct char_framebuffer *fb = &char_fb;
-	const struct cfb_font *fptr = &(fb->fonts[fb->font_idx]);
+	const struct cfb_font *fptr;
 
 	if (!fb->fonts || !fb->buf) {
 		return -1;
 	}
 
+	fptr = = &(fb->fonts[fb->font_idx]);
```
Comment (jfischer-phytec-iot) [inline subsys/fb/cfb.c]: typo?

Comment (ceolin) [reply subsys/fb/cfb.c]: argh, thanks for spot it.

File: subsys/net/l2/ieee802154/ieee802154_mgmt.c (hunk 1 above)
Comment (jukkar) [reply subsys/net/l2/ieee802154/ieee802154_mgmt.c]: It looks like the `scan` parameter should never be NULL as then we would not be able to do a scan in the first place. So probably easiest solution is to check that in the beginning of the function and just return. @tbursztyka do you agree?

Comment (tbursztyka) [reply subsys/net/l2/ieee802154/ieee802154_mgmt.c]: Yes that's a wrong fix.

Just check scan value above (it's a cast of data pointer) after line 98. If NULL then return -EINVAL

**Review by jukkar — CHANGES_REQUESTED** [review]
Some changes needed to the ieee802154_mgmt commit.

File: subsys/net/l2/ieee802154/ieee802154_mgmt.c (hunk 1 above)
Comment (ceolin) [reply subsys/net/l2/ieee802154/ieee802154_mgmt.c]: ok, this change this function behaviour. Should then I remove the whole:
```
if (!ctx->scan_ctx) {
        NET_DBG("Scan request cancelled");
        ret = -ECANCELED;
	break;
}
```
Since `ctx->scan_ctx` is guaranteed not NULL ?

Comment (jukkar) [reply subsys/net/l2/ieee802154/ieee802154_mgmt.c]: The idea of the scan function is that user might cancel the scan while we are waiting results in line 155 k_sleep(). So if the scan is cancelled, the ctx->scan_ctx will be set to NULL by other thread and we notice it after the sleep is finished. This means that we must not remove this block.

Comment (ceolin) [reply subsys/net/l2/ieee802154/ieee802154_mgmt.c]: I see, will keep it.

**Review by jukkar — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
