### PR TITLE
tests: drivers: gpio: skip unsupported tests

### LINKED ISSUE #46917: frdm_k64f : failed to run tests/drivers/gpio/gpio_get_direction
**Describe the bug**
Two bugs here , in test_disconnect and test_input_output function , shows "gpio_pin_configure() failed: -134".
It seems that these two flags are not recognized: "GPIO_INPUT | GPIO_OUTPUT | GPIO_OUTPUT_INIT_LOW"  , "GPIO_DISCONNECTED" .

**To Reproduce**
1. source zephyr-env.sh
2. twister -p frdm_k64f --device-testing  --hardware-map map.yml -T tests/drivers/gpio/gpio_get_direction/ -vv
3. See error

or

2. west build -p always -b frdm_k64f tests/drivers/gpio/gpio_get_direction/
3. screen /dev/ttyACM0 115200
4. west flash
5. See error

**Expected behavior**
Test case should pass as expected.

**Impact**
The testsuite gpio_get_direction failed.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.1.0-812-g88ca3aca98c0  ***
Running TESTSUITE gpio_get_direction
===================================================================
START - test_disconnect
Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/gpio/gpio_get_direction/src/main.c:20: test_disconnect: (0 not equal to rv)
gpio_pin_configure() failed: -134
FAIL - test_disconnect in 0.15 seconds
===================================================================
START - test_input
PASS - test_input in 0.1 seconds
===================================================================
START - test_output
PASS - test_output in 0.1 seconds
===================================================================
START - test_input_output
Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/gpio/gpio_get_direction/src/main.c:92: test_input_output: (0 not equal to rv)
gpio_pin_configure() failed: -134
FAIL - test_input_output in 0.16 seconds
===================================================================
TESTSUITE gpio_get_direction failed.
===================================================================
RunID: c8e7e0ad19f305178da49e64f6b23b25
PROJECT EXECUTION FAILED
```
**Environment :**
OS: Linux
Toolchain Zephyr SDK 0.14.1
Commit SHA or Version: 88ca3aca98c0788e2c45db5c3fb9c8523293a8c0

### PR DESCRIPTION
**Pull request by cfriedt**
Some drivers may not support simultaneous input-output configuration or disconnect.

In such cases, the driver should return `-ENOTSUP` and the test should be skipped.

Fixes #46917

* Also update the suite to use the new ztest API
* Also correct error codes for related functions in `gpio.h`

### CODE REVIEW

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 1]
```diff
@@ -17,6 +17,11 @@ static void test_disconnect(void)
 	zassert_not_null(port, "device " TEST_DEV " not found");
 
 	rv = gpio_pin_configure(port, pin, flags);
+	if (rv == -ENOTSUP) {
```
Comment (yperess) [inline tests/drivers/gpio/gpio_get_direction/src/main.c:20]: Oh man, this would be a great candidate for #46961

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 2]
```diff
@@ -6,7 +6,7 @@
 
 #include "test_gpio_get_direction.h"
 
-static void test_disconnect(void)
+ZTEST(gpio_get_direction, test_disconnect)
```
Comment (yperess) [inline tests/drivers/gpio/gpio_get_direction/src/main.c:9]: Missing: `ZTEST_SUITE(gpio_get_direction, ...)`

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 3]
```diff
@@ -17,6 +17,11 @@ static void test_disconnect(void)
 	zassert_not_null(port, "device " TEST_DEV " not found");
```
Comment (yperess) [inline tests/drivers/gpio/gpio_get_direction/src/main.c:17]:
```
port = device_get_binding(TEST_DEV);
zassert_not_null(port, "device " TEST_DEV " not found");
```

Seems to be recurring, may I suggest (you can use zassert if you don't want to wait for the assume API, but then you should do the assert in the before function instead so it doesn't blow up your main thread):

```
struct gpio_get_direction_fixture {
  const struct device *port;
};

static void *gpio_get_direction_setup(void)
{
  static struct gpio_get_direction_fixture fixture;

  fixture.port = device_get_binding(TEST_DEV);
  zassume_not_null(port, "device " TEST_DEV " not found");

  return &fixture;
}

// Create the test suite and add the setup function
ZTEST_SUITE(gpio_get_direction, NULL, gpio_get_direction_setup, NULL, NULL, NULL);

// The _F tells it to use the fixture provided by the setup function
ZTEST_F(gpio_get_direction, test_disconnect)
{
  ...
  // Use fixture->port here
}
```

**Review by yperess — CHANGES_REQUESTED** [review]

File: tests/drivers/gpio/gpio_get_direction/src/main.c (hunk 2 above)
Comment (cfriedt) [reply tests/drivers/gpio/gpio_get_direction/src/main.c:9]: Weird - i distinctly remember adding that. Maybe I forgot to push

Comment (cfriedt) [reply tests/drivers/gpio/gpio_get_direction/src/main.c:11]: May have been lost because i reordered commits. Fixed!

**Comment by PerMac** [comment]
I tried this PR but the failure is still the same on nrf boards

**Comment by cfriedt** [comment]
> I tried this PR but the failure is still the same on nrf boards

@PerMac 
nRF boards do not yet support get direction, so that is expected.

Would be great if Nordic could add that support.

**Comment by PerMac** [comment]
I see, but then it means the test description in its yaml requires some extra filtering options, so boards without getting direction won't be picked up

File: tests/drivers/gpio/gpio_get_direction/src/main.c (hunk 3 above)
Comment (cfriedt) [reply tests/drivers/gpio/gpio_get_direction/src/main.c:26]: I'll change it when the zassume work is done. I can see that would be helpful here.

**Comment by cfriedt** [comment]
@PerMac - skipping test at runtime for now :P I think proper filtering would likely require adding a Kconfig until there is support everywhere (e.g. `CONFIG_GPIO_DRIVER_SUPPORTS_DIRECTION`) but that seems like it could be overkill.

**Review by yperess — DISMISSED** [review]

**Comment by cfriedt** [comment]
@yperess - need to re-approve due to force-push, sorry.

**Comment by PerMac** [comment]
TBH I am ambivalent about this solution. We will spend resources on our testing farm for building and executing a test, which in the end results only in skips. I can also imagine, that there is no other reasonable way for filtration in this case. If you'd managed to find a filtration option I'd appreciate it :)

**Comment by cfriedt** [comment]
> TBH I am ambivalent about this solution. We will spend resources on our testing farm for building and executing a test, which in the end results only in skips. I can also imagine, that there is no other reasonable way for filtration in this case. However, if you'd managed to find a filtration option I'd appreciate it :)

Ideally @anangl would be able to add support for `gpio_get_direction()` in #47030, and then the test would be useful on nRF as well.

**Comment by henrikbrixandersen** [comment]
> @PerMac - Ideally @anangl would be able to add support for `gpio_get_direction()` along with the fix for #47030, and then the test would be useful on nRF as well.

Had we included this test in the basic GPIO API test, and just skipped it for drivers not implementing this feature, the overhead would have been smaller.

**Comment by cfriedt** [comment]
> > @PerMac - Ideally @anangl would be able to add support for `gpio_get_direction()` along with the fix for #47030, and then the test would be useful on nRF as well.
> 
> Had we included this test in the basic GPIO API test, and just skipped it for drivers not implementing this feature, the overhead would have been smaller.

If (when?) all platforms implement `gpio_get_direction()`, then I think it would make sense to merge it to the basic api test, because at that point, it would be part of the basic api and not `[EXPERIMENTAL]`.

**Review by yperess — CHANGES_REQUESTED** [review]
One small nit

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 4]
```diff
@@ -6,108 +6,110 @@
...
+	gpio_flags_t flags;
+};
+
+static void *gpio_get_direction_setup(void)
+{
+	static struct gpio_get_direction_fixture fixture;
+
+	fixture.pin = TEST_PIN;
+	fixture.port = device_get_binding(TEST_DEV);
+	zassert_not_null(fixture.port, "device " TEST_DEV " not found");
```
[the remark this answers is not in the document]
Comment (cfriedt) [reply tests/drivers/gpio/gpio_get_direction/src/main.c:21]: Will change.

I guess that could work though if there were state for each test. A failed setup function could signal all tests to fail in O(1).

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 5]
```diff
@@ -6,108 +6,117 @@
...
+	fixture.pin = TEST_PIN;
+
+	return &fixture;
+}
+
+static void gpio_get_direction_before(void *arg)
+{
+	struct gpio_get_direction_fixture *fixture = (struct gpio_get_direction_fixture *)arg;
+
+	fixture->port = device_get_binding(TEST_DEV);
```
Comment (yperess) [inline tests/drivers/gpio/gpio_get_direction/src/main.c:28]: No need to make a change here, but generally speaking the call to `device_get_binding` can be made in the setup since you only need it once per suite, then the assert can be in the before since it can't go in the setup.

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 6]
```diff
@@ -6,108 +6,117 @@
...
-	port = device_get_binding(TEST_DEV);
-	zassert_not_null(port, "device " TEST_DEV " not found");
+	rv = gpio_pin_configure(fixture->port, fixture->pin, fixture->flags);
+	if (rv == -ENOTSUP) {
+		/* some drivers / gpio hw do not support disconnect */
+		ztest_test_skip();
+	}
 
-	rv = gpio_pin_configure(port, pin, flags);
 	zassert_equal(0, rv, "gpio_pin_configure() failed: %d", rv);
```
Comment (yperess) [inline tests/drivers/gpio/gpio_get_direction/src/main.c:42]: nit: can use `zassert_ok` here

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 7]
```diff
@@ -6,108 +6,117 @@
...
 	if (rv == -ENOSYS) {
+		/* gpio_pin_direction() is not supported in the driver */
 		ztest_test_skip();
 	}
 
 	zassert_equal(false, rv, "gpio_pin_is_input() failed: %d", rv);
 
-	rv = gpio_pin_is_output(port, pin);
+	rv = gpio_pin_is_output(fixture->port, fixture->pin);
 	zassert_equal(false, rv, "gpio_pin_is_output() failed: %d", rv);
```
Comment (yperess) [inline tests/drivers/gpio/gpio_get_direction/src/main.c:61]: nit: can use `zassert_ok` here

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 8]
```diff
@@ -6,108 +6,117 @@
...
 	if (rv == -ENOSYS) {
+		/* gpio_pin_direction() is not supported in the driver */
 		ztest_test_skip();
 	}
 
 	zassert_equal(true, rv, "gpio_pin_is_input() failed: %d", rv);
 
-	rv = gpio_pin_is_output(port, pin);
+	rv = gpio_pin_is_output(fixture->port, fixture->pin);
 	zassert_equal(false, rv, "gpio_pin_is_output() failed: %d", rv);
```
Comment (yperess) [inline tests/drivers/gpio/gpio_get_direction/src/main.c:80]: nit: can use `zassert_ok` here

**Review by yperess — DISMISSED** [review]

File: tests/drivers/gpio/gpio_get_direction/src/main.c [hunk 9]
```diff
@@ -6,108 +6,117 @@
...
-	zassert_not_null(port, "device " TEST_DEV " not found");
-
-	rv = gpio_pin_configure(port, pin, flags);
-	zassert_equal(0, rv, "gpio_pin_configure() failed: %d", rv);
+	common(fixture);
 
-	rv = gpio_pin_is_input(port, pin);
-	if (rv == -ENOSYS) {
+	rv = gpio_pin_is_input(fixture->port, fixture->pin);
+	if (rv == -ENOTSUP) {
```
Comment (anangl) [inline tests/drivers/gpio/gpio_get_direction/src/main.c:110]:
```suggestion
	if (rv == -ENOSYS) {
```

It looks like the description of `gpio_pin_is_input` needs to be corrected. It says: https://github.com/zephyrproject-rtos/zephyr/blob/3efce4c93938ebdd7d5d9b3ffdcd2b096490cea5/include/zephyr/drivers/gpio.h#L800-L803 while in `z_impl_gpio_port_get_direction` we've got: https://github.com/zephyrproject-rtos/zephyr/blob/3efce4c93938ebdd7d5d9b3ffdcd2b096490cea5/include/zephyr/drivers/gpio.h#L784-L785
Same story with `gpio_pin_is_output`.

**Review by anangl — CHANGES_REQUESTED** [review]

File: tests/drivers/gpio/gpio_get_direction/src/main.c (hunk 9 above)
Comment (cfriedt) [reply tests/drivers/gpio/gpio_get_direction/src/main.c:110]: Good catch - I'll fix that in my current PR.

File: tests/drivers/gpio/gpio_get_direction/src/main.c (hunk 5 above)
Comment (cfriedt) [reply tests/drivers/gpio/gpio_get_direction/src/main.c]: Fixed!

File: tests/drivers/gpio/gpio_get_direction/src/main.c (hunk 6 above)
Comment (cfriedt) [reply tests/drivers/gpio/gpio_get_direction/src/main.c]: Fixed!

**Review by anangl — DISMISSED** [review]

**Review by anangl — APPROVED** [review]

**Comment by cfriedt** [comment]
@yperess - please re-ack wyham

**Review by yperess — APPROVED** [review]
