### PR TITLE
fs: nvs: Fix handling of corrupt ate's in garbage collector

### LINKED ISSUE #26407: fs: nvs: Incorrect handling of corrupt ate's in nvs_gc
**Describe the bug**
This bug is related to how garbage collection in nvs handles ate's with incorrect crc8.

1. In `nvs_gc`, the crc8 of `close_ate` is not checked. This means that `close_ate.offset` could contain an offset that is larger than any valid ate in the sector. For example, there might be a valid ate at offset 0x100 but `close_ate.offset` is 0x200. If that is the case that value will not be moved and so it will be lost.

2. The crc8 of `gc_ate` is not checked before trying to find another ate with the same id. This means that if there is one ate with a unique id but with faulty crc8, the inner while(1)-loop will never stop since the break condition includes a check for a correct crc8.

**To Reproduce**
The easiest is probably to use the tests from the linked PR and run the test. Before applying the fix the test will get stuck in an infinite loop and time out. The other commit in the PR is a fix for the problem.

**Expected behavior**
I would expect nvs to be able to recover from corrupted sectors.

**Impact**
The impact is possible loss of data and an infinite loop when `nvs_gc` runs. This can happen at a write or at initialization.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Toolchain zephyr-sdk 0.11.1
 - Commit SHA: f221dfec2f

### PR DESCRIPTION
**Pull request by tsvehagen**
`nvs_gc` does not verify the crc8 of `close_ate` before using `close_ate.offset`.  This means that `close_ate.offset` could contain an offset that points beyond valid ate's in the sector. For example, there might be a valid ate at offset 0x100 but `close_ate.offset` is 0x200.  If that is the case that value will not be moved and so it will be lost.

Solve this by refactoring the recovery loop from `nvs_prev_ate` into `nvs_recover_last_ate` and use that function in `nvs_gc` if a corrupt close_ate is found.

The crc8 of `gc_ate` is not checked before trying to find another ate with the same id. If there are no valid ate with that id in the whole fs the inner `while(1)`-loop will never stop since the break condition includes a check for a correct crc8.

Solve this by skipping gc_ate's with an invalid crc8.

Fixes #26407

### CODE REVIEW

**Review by Laczen — APPROVED** [review]
Nice catch, thanks

**Comment by nvlsianpu** [comment]
@tsvehagen Thanks for detailed bug description.

**Review by nvlsianpu — APPROVED** [review]

File: subsys/fs/nvs/nvs.c [hunk 1]
```diff
@@ -529,12 +564,7 @@ static int nvs_gc(struct nvs_fs *fs)
 				return rc;
 			}
 		}
-
-		/* stop gc at end of the sector */
```
Comment (nvlsianpu) [inline subsys/fs/nvs/nvs.c:533]: this comment still describes well the loop termination case.
