### PR TITLE
Fix OpenThread commissioning

### LINKED ISSUE #6874: Not able to join OpenThread BorderRouter or a ot-ftd-cli network
Copied from Google groups:
Hmm, So I tried now using a NRF52840 as the joiner using the ot-ftd-cli firmware and using a Zephyr with joiner enabled.

The OT firmware works fine and there I get join success.

But with Zephyr I get a different EUI64 then on the ot-ftd-cli firmware as well as that it fails with NotFound:

So I enabled join using "wpanctl permit-join 7200" and "sudo wpanctl permit-join 7200", then I verify that the net is joinable
t> cmd scan[echo-client] [ERR] wait_reply: ␛[0;31mData packet not received␛[0m
[openthread] [INF] otPlatLog: -MAC-----: Dropping IPv6 UDP msg, len:213, chksum:5889, sec:yes, error:Drop, prio:low
[openthread] [INF] otPlatLog: -MAC-----: src: fdde:ad00:beef:0:0:0:0:1
[openthread] [INF] otPlatLog: -MAC-----: dst: fdde:ad00:beef:0:0:0:0:2

| J | Network Name     | Extended PAN     | PAN  | MAC Address      | Ch | dBm | LQI |
+---+------------------+------------------+------+------------------+----+-----+-----+
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "ActiveScan"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "ActiveScan"
ot> [openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[openthread] [DBG] otPlatLog: -MAC-----: Received frame from short address 0xe1d4
[openthread] [INF] otPlatLog: -MAC-----: Frame rx failed, error:UnknownNeighbor, len:28, seqnum:131, type:Beacon, src:0xe1d4, dst:None, sec:no, ackreq:no
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[openthread] [INF] otPlatLog: -MAC-----: Received Beacon, name:OpenThreadGuide, xpanid:dead1111dead2222, id:3 ver:2, joinable:yes, native:no
| 1 | OpenThreadGuide  | dead1111dead2222 | abcd | 52e7d3b0457aa2b6 | 13 | -39 |  54 |
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [INF] otPlatLog: -MAC-----: Sending Beacon Request
Done
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "ActiveScan"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping

# Start a join
ot> cmd joiner start J01NME
[openthread] [INF] otPlatLog: -MLE-----: Send Discovery Request (ff02:0:0:0:0:0:0:2)
Done
ot> [net] [INF] ot_state_changed_handler: State changed! Flags: 0x0000800b Current role: 0
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 CD CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXMM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[echo-client] [ERR] wait_reply: ␛[0;31mData packet not received␛[0m
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 CE CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXNM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 CF CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXOM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D0 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXPM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D1 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXQM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D2 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXRM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D3 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXSM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D4 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXTM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D5 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXUM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D6 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXVM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D7 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXWM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D8 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXXM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 D9 CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXYM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 DA CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AXZM+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 DB CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AX[M+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MAC-----: Request to start operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Starting operation "TransmitData"
[openthread] [DBG] otPlatLog: ==============================[TX len=035]===============================
[openthread] [DBG] otPlatLog: | 41 D8 DC CD AB FF FF 03 | 1E E3 DB 64 AA 14 37 7F | AX\M+....c[d*.7.
[openthread] [DBG] otPlatLog: | 3B 02 F0 4D 4C 4D 4C CD | 38 FF 10 1A 04 80 02 28 | ;.pMLMLM8......(
[openthread] [DBG] otPlatLog: | 00 4B F4 .. .. .. .. .. | .. .. .. .. .. .. .. .. | .Kt.............
[openthread] [DBG] otPlatLog: ------------------------------------------------------------------------
[openthread] [DBG] otPlatLog: -MAC-----: Finishing operation "TransmitData"
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[otPlat/radio] [DBG] otPlatRadioGetPromiscuous: PromiscuousMode=0
[openthread] [DBG] otPlatLog: -MAC-----: Idle mode: Radio sleeping
[openthread] [DBG] otPlatLog: -MESH-CP-: No joinable networks remaining to try
Join failed [NotFound]

### PR DESCRIPTION
**Pull request by rlubos**
Fixes #6874.

First commit bumps OT version to get fixes that enable valid Joiner ID handling and correct radio operation after `thread stop` command was called. It also contains changes in Zephyr port required to work with updated version.
Second commit provides a function to obtain channel that radio currently operates on. In result, device can join network discovered at any channel, not only the hardcoded one.

### CODE REVIEW

File: subsys/net/lib/openthread/platform/radio.c [hunk 1]
```diff
@@ -45,6 +47,7 @@ static struct device *radio_dev;
 static struct ieee802154_radio_api *radio_api;
 
 static s8_t tx_power;
+static u16_t channel;
```
Comment (tbursztyka) [inline subsys/net/lib/openthread/platform/radio.c]: It's not possible to store your own private data into otInstance? (just asking)

Because here it means OT must work only against 1 15.4 device. Is OT meant to run on N device on one board or?

Comment (rlubos) [reply subsys/net/lib/openthread/platform/radio.c]: > It's not possible to store your own private data into otInstance? (just asking)

Unfortuantely, there is no API to set private data per instance. `otInstance` is just a pointer to an object of class defined in OpenThread, so unless you modify OpenThread sources there is no option to store anything extra there.

> Because here it means OT must work only against 1 15.4 device. Is OT meant to run on N device on one board or?

I'm afraid that entire OT port is written in a single-instance manner (alarm, flash etc.). OT in general does not support multiple radio interfaces, it doesn't make much sense for me to run multiple OT instances on a single radio either. It perhaps could make sense to run multiple OpenThread instances if each had sepearate 15.4 radio, but is there acutally an use case for that? I don't know, are there any boards with multiple 15.4 interfaces? Anyway, supporting these would require to adjsut entire OT port, not only this part.

**Review by tbursztyka — APPROVED** [review]
Thanks for the precisions.

Fine by me!

**Review by jukkar — APPROVED** [review]
