### PR TITLE
wifi: Fix Wi-Fi NM registration issues

### LINKED ISSUE #75332: wifi_nm: New API `net_if_get_wifi_sta` isn't backwards compatible with `net_if_get_first_wifi`
**Describe the bug**
Newly added API `net_if_get_wifi_sta` expects the NMs to always register using the newly added `wifi_nm_register_mgd_type_iface`, but if an existing NM is using `wifi_nm_register_mgd_iface` then `type` isn't set and  `net_if_get_wifi_sta` returns NULL, but to aid backward compatibility, it should fallback to ` `net_if_get_first_wifi` in case type is unset.

**To Reproduce**
1. Configure WPA supplicant as a NM which still uses old API `wifi_nm_register_mgd_iface`.
2. I used NCS downstream driver
3. Try doing `wifi scan`, you will see a crash.

**Expected behavior**
The API should always return non-NULL if there is a Wi-Fi interface present.

**Impact**
Minor bug, but API behaviour changed.

**Logs and console output**
None

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: `v3.7.0-rc2`

**Additional context**
NA

### PR DESCRIPTION
**Pull request by krish2718**
Fixes #75332

### CODE REVIEW

File: modules/hostap/src/supp_main.c [hunk 1]
```diff
@@ -415,7 +415,8 @@ static void iface_cb(struct net_if *iface, void *user_data)
 		return;
 	}
 
-	if (wifi_nm_get_type_iface(iface) != (1 << WIFI_TYPE_STA)) {
+	if ((wifi_nm_get_type_iface(iface) == 0) ||
+	    (wifi_nm_get_type_iface(iface) != (1 << WIFI_TYPE_STA))) {
```
Comment (jukkar) [inline modules/hostap/src/supp_main.c]: Instead of duplicating this multiple times, why not make an inline function that hides the checks, so something like
```
static inline bool wifi_is_station(struct net_if *iface)
{
	if ((wifi_nm_get_type_iface(iface) == 0) ||
	    (wifi_nm_get_type_iface(iface) != (1 << WIFI_TYPE_STA))) {
		return true;
	}

	return false;
}
```

Comment (krish2718) [reply modules/hostap/src/supp_main.c]: The function `net_if_get_wifi_sta` itself is a wrapper for `is_sta`, so, just inlined it. But I can add this to the `wifi_nm` API and use that here.

Comment (krish2718) [reply modules/hostap/src/supp_main.c]: Re-thinking, want to keep the unset type separate from explicit STA/AP in the Wi-FI NM APIs, so, how about this?

```
diff --git a/subsys/net/ip/net_if.c b/subsys/net/ip/net_if.c
index fc4945174c0..9154c149ad9 100644
--- a/subsys/net/ip/net_if.c
+++ b/subsys/net/ip/net_if.c
@@ -5689,14 +5689,14 @@ struct net_if *net_if_get_wifi_sta(void)
        STRUCT_SECTION_FOREACH(net_if, iface) {
                if (net_if_is_wifi(iface)
 #ifdef CONFIG_WIFI_NM
-                       && ((wifi_nm_get_type_iface(iface) == 0) ||
-                           (wifi_nm_get_type_iface(iface) == (1 << WIFI_TYPE_STA)))
+                       && wifi_nm_iface_is_sta(iface)
 #endif
                        ) {
                        return iface;
                }
        }
-       return NULL;
+
+       return net_if_get_first_wifi();
 }
```

**Review by jukkar — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
