### PR TITLE
Bluetooth: host: Ignore failure to set passive scanner address

### LINKED ISSUE #25672: Bluetooth: Mesh: scan_start fails with synchronous bt_enable
The Bluetooth Mesh fails in the `bt_le_scan_start` call in adv.c because of NRPA, but only if the Bluetooth subsystem is initialized without a `ready` callback. 

This happens because the scan_start call uses the hci_core `BT_ADV_ENABLED` flag to check whether the advertiser is in progress, while the controller uses the ull_adv state:
When initializing the mesh subsystem, the adv thread is started. It calls `bt_le_adv_start`, which calls `set_le_adv_enable_legacy`. The HCI command is processed by the controller, which sets the adv structure in ull_adv.c. Then, the HCI command response is enqueued in hci_core.c, and the adv thread goes to sleep. Next, settings are loaded, which starts the mesh subsystem and the scanner. When calling `bt_le_scan_start` from adv.c's `bt_mesh_scan_enable`, hci_core.c checks whether the advertiser is running, using its local `BT_ADV_ENABLED` flag. This flag won't be set until the adv_enable HCI command response is processed. hci_core decides that the advertiser isn't running, and sets the NRPA, which fails, because in the controller, the advertiser is already started.

I'm not sure why this works if bt_enable is called with a callback, but I assume it's a thread priority thing. It also works if I enable `CONFIG_BT_DEBUG_HCI_CORE`, which suggests it's a yield or race condition issue.

Bisecting the issue, it appears first in 915c510a0a, which looks like it is changing some scheduling aspects of the controller.

**To Reproduce**

Change the mesh sample to call `bt_ready` from main after the call to `bt_enable`, instead of as a callback:

```C
void main(void)
{
	int err;

	printk("Initializing...\n");

	/* Initialize the Bluetooth Subsystem */
	err = bt_enable(NULL);
	if (err) {
		printk("Bluetooth init failed (err %d)\n", err);
		return;
	}

	bt_ready(0);
}
```

Then, provision and power cycle the device. It should immediately trigger the bug:

**Console log**

```
*** Booting Zephyr OS build v2.3.0-rc1-245-g451e559a22a4  ***
Initializing...
Bluetooth initialized
[00:00:00.008,819] <inf> fs_nvs: 2 Sectors of 4096 bytes
[00:00:00.Mesh initialized
008,819] <inf> fs_nvs: alloc wra: 0, f20
[00:00:00.008,819] <inf> fs_nvs: data wra: 0, 12c
[00:00:00.010,131] <inf> bt_hci_core: No ID address. App must call settings_load()
[00:00:00.257,507] <wrn> bt_hci_core: opcode 0x2005 status 0x0c
[00:00:00.257,507] <err> bt_mesh_adv: starting scan failed (err -5)
```

### PR DESCRIPTION
**Pull request by joerchan**
Ignore error when failing to set the passive scanner private address.
This can happen because in between the time we checked if the
advertiser was enabled and the time we execute the set random address
command the state of the advertiser could have changed in the
controller, and we only set the state once the command has completed
in the controller.

Fixes: #25672

Fix not setting NRPA before starting scanner.
Occurs with BT_PRIVACY=n and BT_EXT_ADV=y

### CODE REVIEW

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -4113,7 +4113,14 @@ static int le_scan_set_random_addr(bool active_scan, uint8_t *own_addr_type)
...
 			err = le_set_private_addr(BT_ID_DEFAULT);
 			if (err) {
-				return err;
+				if (active_scan ||
+				    (adv && !atomic_test_bit(adv->flags,
+							     BT_ADV_ENABLED))) {
+					return err;
+				} else {
+					BT_WARN("Ignore failure to set address "
+						"for passive scan");
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:4122]: Maybe log the error value as well?

Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c:4122]: And I'd use the form "Ignoring" rather than "Ignore"

File: subsys/bluetooth/host/hci_core.c [hunk 2]
```diff
@@ -4113,7 +4113,15 @@ static int le_scan_set_random_addr(bool active_scan, uint8_t *own_addr_type)
 		    adv && !atomic_test_bit(adv->flags, BT_ADV_ENABLED)) {
 			err = le_set_private_addr(BT_ID_DEFAULT);
 			if (err) {
-				return err;
+				if (active_scan ||
+				    (adv && !atomic_test_bit(adv->flags,
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:4117]: Sorry, another thing I noticed: the top level condition for the branch that the `le_set_private_addr()` call is in is already checking for `adv != NULL` so checking for it again seems redundant here?

Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c]: While processing this comment I realized that the above statement is wrong, there is an issue with the use of parenthesis.

I tested it with` west build -b native_posix tests/bluetooth/shell -- -DCONFIG_BT_PRIVACY=n -DCONFIG_BT_EXT_ADV=y`
Looking at the btmon there is no call te LE_Set_Random_Addr, before starting the scanner.
Added a fix, and now the NRPA is set.

I extracted it if-statement out to a helper function because repeating the same check was difficult at the indentation level.
The check should only be applied if the advertiser is using the random address, if the advertiser is using the LE_Set_Advertiser_Random_Address then this should not happen.

File: subsys/bluetooth/host/hci_core.c [hunk 3]
```diff
@@ -4083,6 +4083,21 @@ static void hci_cmd_status(struct net_buf *buf)
 }
 
 #if defined(CONFIG_BT_OBSERVER)
+static inline bool is_adv_using_rand_addr(void)
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c:4086]: I'd drop the `inline` here and let the compiler take care of it (it will most certainly inline it anyway). IMO it's only in cases where you do careful profiling after the fact and discover you get a significant benefit out of explicit inlining that it's justified to do so.

Comment (joerchan) [reply subsys/bluetooth/host/hci_core.c]: Agree, removed it.

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
