### PR TITLE
Bluetooth: BAP: Fix conn checks for bcast assistant notifications

### LINKED ISSUE #69136: [Coverity CID: 347167] Dereference after null check in subsys/bluetooth/audio/bap_broadcast_assistant.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/adeaa63bb71aba5c1732816df21f40d654e26cd4/subsys/bluetooth/audio/bap_broadcast_assistant.c

Category: Null pointer dereferences
Function: `notify_handler`
Component: Bluetooth
CID: [347167](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=347167)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/adeaa63bb71aba5c1732816df21f40d654e26cd4/subsys/bluetooth/audio/bap_broadcast_assistant.c#L380

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=347167

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_FORWARD_NULL). ([CWE-476](http://cwe.mitre.org/data/definitions/476.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by Thalley**
The notify handle in the BAP broadcast assistant did not handle conn == NULL properly, and neither did delayed_bap_read_handler.

Add better NULL checks, which also fixes a coverity issue.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/69136

### CODE REVIEW

**Review by kruithofa — DISMISSED** [review]

File: subsys/bluetooth/audio/bap_broadcast_assistant.c [hunk 1]
```diff
@@ -384,7 +384,9 @@ static void long_bap_read(struct bt_conn *conn, uint16_t handle)
 
 static void delayed_bap_read_handler(struct k_work *work)
 {
-	long_bap_read(broadcast_assistant.conn, broadcast_assistant.long_read_handle);
+	if (broadcast_assistant.conn != NULL) {
```
Comment (pin-zephyr) [inline subsys/bluetooth/audio/bap_broadcast_assistant.c:387]: can we move this check before task scheduling ?

**Review by pin-zephyr — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/bap_broadcast_assistant.c (hunk 1 above)
Comment (Thalley) [reply subsys/bluetooth/audio/bap_broadcast_assistant.c:387]: Not fully. 

The `broadcast_assistant.conn` may be accessed and modified by multiple thread I believe. 

We could move the check to `long_bap_read` if you prefer

Luckily there are significant effort going on to reduce the number of threads in BT, which should make it better in the future

Comment (pin-zephyr) [reply subsys/bluetooth/audio/bap_broadcast_assistant.c:387]: I did not describe clear enough.

I was thinking if we can move this check to the function long_bap_read()

just before 

err = k_work_reschedule(&broadcast_assistant.bap_read_work, ....);

which avoids a k_work_reschedule when broadcast_assistant.conn == NULL

Comment (Thalley) [reply subsys/bluetooth/audio/bap_broadcast_assistant.c:387]: We can move it to the function, yes, but it would need to be at the very top. 

It doesn't make sense to do anything in the function if `conn == NULL`, and similar it does not make sense to call the function when you know that `conn == NULL`, which is why I guarded the function call

Comment (pin-zephyr) [reply subsys/bluetooth/audio/bap_broadcast_assistant.c:387]: I thought we agree with the better solution if conn == NULL, long_bap_read()  will return at the very top instead of rescheduling the task ...  :-)

**Review by pin-zephyr — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
