### PR TITLE
intel_adsp: Fix corrupt fatal logs

### LINKED ISSUE #44145: Zephyr Panic dump garbled on Intel cAVS platforms
**Describe the bug**
When Zephyr hits a fatal error, the OS panic dump is not printed out correctly in many circumstances. This is happening regularly with multicore configurations and SOF application, in bugs like https://github.com/thesofproject/sof/issues/5556

**To Reproduce**
Aside https://github.com/thesofproject/sof/issues/5556 , no simple steps yet available. A simple panic test with a adsp smoke test is ok (output fine), so this does not happen in all cases.

**Expected behavior**
The panic dump is readable/parseable.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
A few example dumps (from use-case of above bug)

EXAMPLE1
```
--[00000000] <inf> main: SOF on intel_adsp_cavs25
[00000000] <inf> main: SOF initialized
555357: SHM: FW ABI 0x3015000 DBG ABI 0x5003000 tags SOF:v2.0-rc1-593-gb7aee6182a91-dirty zephyr:zephyr-v3.0.0-1016-g43f2c22e5efb src hash 0x61b977eb (ldc hash 0x61b977eb)
X000116[473]0 0<11e6r4r7>3 ] o<s:e rr >* * oFsA:T A L* *E XCCPEUP TI0O NE
 CCAUSE [9 0(01l1o6a4d7/3s]t o<ree rarl>i gnomse:n t )**
sxb[e020604181f6 4V7A3D]D R< er0rx>1 31o
::  ** [ PS0 01106x467036]2 0<rrr> [os:0 0 1*1*6 4 7 3 ]( IN<TLEVeErLr:> o0s :E XCM :* *  A0 0 UM:1 RI0NxGb:e02fe907  W OSEP: 1 OWB:0x6b eC0A6LbL6I6N0C : A2 2)
1x9e07[b7000
1] <e[rr>0 01o1s6:4 7 3*]*  < Ae4r r> s9:6 d4   *A*5   A8 0x100x1b e 0A297 428  A6 00xx3b e 0A67b 630 A100x 15
7 0x[9e0070b191060
0err>[ o0s0:1 1 6*4*7 3A]1 2 <e0rxr7>  A13 os:  ** LBE0Gx be0725c0 A14 0xbe01d080 LE0NxDb e072618 A15 0xb(en0i1ld)09
 9
A[00101061417634]7 3<] e<rre>r r>o s:o s :* * S>A>R>  ZEPHY0Rx 1FaAT
s0: CP[U e0x0c1e1p6t4i7o3n]  o<n eCrPrU>  0o
s: Current[ th0r0e1a1d6:4 74]0 x<9eer0r7>1 b8o8s :( uHnaklntoiwnng)
yystem
```

EXAMPLE2
```
�[00000000] <inf> main: SOF on intel_adsp_cavs25
[00000000] <inf> main: SOF initialized
584633: SHM: FW ABI 0x3015000 DBG ABI 0x5003000 tags SOF:v2.0-rc1-586-g8e85d0018c7e-dirty zephyr:zephyr-v3.0.0-1014-gfa7f5ad3686c src hash 0xef16be95 (ldc hash 0xef16be95)
[0[000039933775544]]  <<eerrrr>>  ooss::    ****  CFPAUT AL0  EEXXCCECPATUISOEN 
113 (lo[ad/0s0t3o9r3e7 5P4I]F  <daetrar >e rroosr:)
P **  [PC 00309x3b7e5042]6 4<b6e rVrA>D DRo s:0 x 3*0*  
0x606[20
b03937[54]0 0<3e9r3r7>5 4]o s<: r*r*>     (IoNsT:L EVE L*:*  A0 0 EXCM: 00 xUbMe:02feaf1   RSIPN G:0 WOE:0xbe016 bO6W6B0:  A2 6 CALLINC:0x92e)07

[[000309339735745]4 ]< e<rre>r r>o s:o s :* *  * *A 4  A8 (nil0)x 2 1Aa98 c  A5 0xbe060bx693e00 7Ab160d 4  A6 0x30 x 9Ae70 7b900 0Ax1115 
*  * *A 4  A8 (nil0)x 2 1Aa98 c  A5 0xbe060bx693e00 7Ab160d 4  A6 0x30 x 9Ae70 7b900 0Ax1115 
0x9e07b900
003[93705043]9 3<75e4r]r >< orsr:>   **o sA:1 2  ** 0LxB7E GA 13 0xb0ex0b1ed0078205 cL0E NAD1 4 0x0bxeb0e10d7029601 8L CAO1U5N T (nil)
orsr:>   **o sA:1 2  ** 0LxB7E GA 13 0xb0ex0b1ed0078205 cL0E NAD1 4 0x0bxeb0e10d7029601 8L CAO1U5N T (nil)
0xbe0264b0
H039[375040]3 9<37e5r4r]>  <oesr:r >  ** SAoRs : >>0>x 1ZaEP
uROR 0[: 0C0P3U9 3e7x5c4e]p t<ioenr ro>n  CoPsU:  0C
grrent th[ead0:0 39307x595e]0 7<1be8r8r >( uonsk:n oHwanl)tin
```

EXAMPLE3
```
[00000000] <inf> main: SOF on intel_adsp_cavs25
[00000000] <inf> main: SOF initialized
547963: SHM: FW ABI 0x3015000 DBG ABI 0x5003000 tags SOF:v2.0-rc1-586-g8e85d0018c7e-dirty zephyr:zephyr-v3.0.0-1014-gfa7f5ad3686c src hash 0xfc2445c4 (ldc hash 0xfc2445c4)
[0011733[80] 0<01e7r3r3>8 0]o s<: er r*>*  FoAsT:A L  E*X*C ECPPTUI 0 EXCOCNU
S
0E 28 (load prohibi[ted)0
D17338[0] <01733e8r0r]>  <oesr:r >  **o s :P C  **  PS 0xbe003xb6000eb2 0VA
0fff[f80
1173380][ <0e0r1r7>3 38o0s]:  < e*r*r >  @  o(sI:N  TL E*V*E L :/Am0 0E nXtC/M:0 sxb0e 0U2M3:ef1f 2R I NSGP:a g04 W0OxEb:0e10 6ObW8Bf:00 1 4A 2C 0AcLL0IxN9Ce:_027)22/
 chao0 [m eA0/3k80 v] 0<ehxe6rr>
ma n*e*/ p A[r4/ f033-zephyrsof/sof/zep001x7f3f3f8f0f]f 00<  Ae5r r> 0xocs :  A6  ** ( nAi8l )  A7 0xbe01d02x6f4f f fAf9f ff
hyr0/x.[.be00061b7933308 0A]1 1</src/incl err> os: 0x 9*e*0 7A21d24 0
u dAe1/4so 0[fx/1 0A0s151 c7h3308x09]e e07<d23ecr0url
>>e/ toa[ss:0 k0.17 3*3*8 0L]B E<h:94
Ge rr> os: 0 x*b*e 0S3AbR0 08 LEN0Dx 1e
3b016 [COU0N0T1 733800x]b e<02e3rfrf>0
0os: >>[> Z0E0P1H7Y3R3 8F0A]T A<L eErRrR>O R os0::  CurrCePnUt  etxhcreepatdi:o n on CPU 00x9e
7n)
```

**Environment (please complete the following information):**
 - OS: Zephyr, cAVS2.5 hardware
 - Toolchain: Zephyr SDK 0.13.1
 - Zephyr main commit b4dfdb5afb5e4e16d9207e79b0b542ee9d128067

**Additional context**
Workarounds tried:
 - CONFIG_PRINTK_SYNC=y

FYI @nashif @teburd @andyross

### PR DESCRIPTION
**Pull request by teburd**
Adds a lock around the logger backend for adsp and changes the buffer size to 80 to avoid 1 character a time writes to the trace buffer

fixes #44145

### CODE REVIEW

**Review by andyross — COMMENTED** [review]
I don't think this is the right level for this fix. We shouldn't have "normal" printk and logging racing ever, there's a CONFIG_LOG_PRINTK that should provide a compatible replacement if you need to use both APIs at once (it implements printk() via the logging backend), we shouldn't be mixing backends.

And the proof is that, if you look carefully, this lock added here doesn't actually protect anything. There's already a lock around the winstream, this is just a lock provided for the benefit of other subsystems.

**Comment by teburd** [comment]
Even with LOG_PRINTK=y there's garbled output in the example prior to this fix. Maybe not the  best way to fix this and I'm open to suggestions, but the fix does in fact solve a problem

**Comment by andyross** [comment]
Then maybe there's missing synchronization in the logging subsystem?

**Comment by teburd** [comment]
Possibly, the lock around winstream is fine (in trace_out.c) but it effectively is locking character at a time given the way printk works.

I don't disagree this isn't a pretty fix, marking DNM for now, but at least something of a solution (and perhaps a cause) is known now.

**Comment by teburd** [comment]
I believe I fully grok the issue(s) now and the commit message reflects all the races I found and how to avoid them, along with a lock around process() in particular avoiding the re-entrance and buffer trampling.

The output looks good.

**Comment by teburd** [comment]
There's potentially an alternative fix that involves putting a lock around the body of z_impl_log_process though I'm not sure of all the implications.

File: subsys/logging/log_backend_adsp.c [hunk 1]
```diff
@@ -10,6 +10,8 @@
 #include <logging/log_output.h>
 #include <logging/log_backend_std.h>
 
+struct k_spinlock lock;
```
Comment (nordic-krch) [inline subsys/logging/log_backend_adsp.c:13]: static

File: subsys/logging/log_backend_adsp.c [hunk 2]
```diff
@@ -20,12 +22,10 @@ static int char_out(uint8_t *data, size_t length, void *ctx)
 	return length;
 }
 
-/* Trace output goes in 64 byte chunks with a 4-byte header, no point
- * in buffering more than 60 bytes at a time
- */
-static uint8_t log_buf[60];
+/* No reason to buffer more, trace out is a buffer */
+static uint8_t log_buf[80];
```
Comment (nordic-krch) [inline subsys/logging/log_backend_adsp.c:26]: previously it was 60. Any reason for this change?

File: subsys/logging/log_backend_adsp.c [hunk 3]
```diff
@@ -20,12 +22,10 @@ static int char_out(uint8_t *data, size_t length, void *ctx)
...
 
-LOG_OUTPUT_DEFINE(log_output_adsp, char_out, log_buf, 1);
+LOG_OUTPUT_DEFINE(log_output_adsp, char_out, log_buf, 80);
```
Comment (nordic-krch) [inline subsys/logging/log_backend_adsp.c:28]: sizeof(log_buf) would avoid repeating the value.

File: subsys/logging/log_backend_adsp.c [hunk 4]
```diff
@@ -76,7 +81,11 @@ static void process(const struct log_backend *const backend,
 {
 	log_format_func_t log_output_func = log_format_func_t_get(log_format_current);
 
+	k_spinlock_key_t key = k_spin_lock(&lock);
```
Comment (nordic-krch) [inline subsys/logging/log_backend_adsp.c:84]: have you considered to put this lock in `char_out` around `intel_adsp_trace_out`. Here it will lock for significant amount of time in the lower priority thread (in case of deferred mode). Putting it in `char_out` may lead to some interleaving of data within the log message so there is a trade off.

**Review by kv2019i — COMMENTED** [review]
This seems to address the problem indeed! I did note following weird output when I had also https://github.com/zephyrproject-rtos/zephyr/pull/44529 included. It's still readable, but ordering is unexpected.

@nordic-krch  had good comments, but other than that, looks good to me.

Example log with the backtrace PR also included:
``
535816 zephyr_ll_scheduler_in[00000000] <inf> main: SOF initialized
it(): unsupported domain 2
3552786: SHM: FW ABI 0x3015000 DBG ABI 0x5003000 tags SOF:v2.0-rc1-696-gc9814111ab20-dirty zephyr:zephyr-v3.0.0-1972-g7994080741fb src hash 0x6311e5b4 (ldc hash 0x6311e5b4)
4165080 zephyr_ll_scheduler_init(): unsupported domain 2


Backtrace:0xBE0267B9:[00000030] <err> os:  ** FATAL EXCEPTION
0xBE0761C0 0xBE026A7F:0xBE07[00000030] <err> os:  ** CPU 2 EXCCAUSE 6 (divide by zero)
6210 0xBE02819A:0xBE076240 0x[00000030] <err> os:  **  PC 0xbe0267bc VADDR (nil)
BE0392D4:0xBE076280 0xB[00000030] <err> os:  **  PS 0x60320
E0396C3:0xBE0762A0 0xBE025604:0xBE0762D0 [00000030] <err> os:  **    (INTLEVEL:0 EXCM: 0 UM:1 RING:0 WOE:1 OWB:3 CALLINC:0x2)
BE01557E:0xBE076300 0xBE0137BC:0xBE076330 [00000030] <err> os:  **  A0 0xbe026a82  SP 0xbe0761c0  A2 0x60040000  A3 0x9e07
fc00

[00000030] <err> os:  **  A4 0xc  A5 0x1  A6 0x40000  A7 0xbe02a188
[00000030] <err> os:  **  A8 0xbe02678a  A9 0xbe0761a0 A10 0x9e084740 A11 (nil)
[00000030] <err> os:  ** A12 0x40000 A13 0x2 A14 0x9e07ef78 A15 0x9e07f00c
[00000030] <err> os:  ** LBEG 0xbe040108 LEND 0xbe040116 LCOUNT 0xbe026788
[00000030] <err> os:  ** SAR 0xf
[00000030] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 2
[00000030] <err> os: Current thread: 0x9e07e3b0 (unknown)
[00000030] <err> os: Halting system
``

File: subsys/logging/log_backend_adsp.c (hunk 4 above)
Comment (teburd) [reply subsys/logging/log_backend_adsp.c:84]: That was one of the problems being solved here, as on the intel_adsp with a fatal exception ISR being run on one cpu, the lower priority logger thread continues to run and trample the data.

I as debating if a lock should be placed in msg_process in log_core.c instead as it seems there's a race when panic mode and the log thread collide on SMP systems.

File: subsys/logging/log_backend_adsp.c (hunk 2 above)
Comment (teburd) [reply subsys/logging/log_backend_adsp.c]: I've added a comment and define, also using sizeof where appropriate

**Comment by teburd** [comment]
> This seems to address the problem indeed! I did note following weird output when I had also #44529 included. It's still readable, but ordering is unexpected.
> 
> @nordic-krch had good comments, but other than that, looks good to me.
> 
> Example log with the backtrace PR also included: `` 535816 zephyr_ll_scheduler_in[00000000] main: SOF initialized it(): unsupported domain 2 3552786: SHM: FW ABI 0x3015000 DBG ABI 0x5003000 tags SOF:v2.0-rc1-696-gc9814111ab20-dirty zephyr:zephyr-v3.0.0-1972-g7994080741fb src hash 0x6311e5b4 (ldc hash 0x6311e5b4) 4165080 zephyr_ll_scheduler_init(): unsupported domain 2
> 
> Backtrace:0xBE0267B9:[00000030] os: ** FATAL EXCEPTION 0xBE0761C0 0xBE026A7F:0xBE07[00000030] os: ** CPU 2 EXCCAUSE 6 (divide by zero) 6210 0xBE02819A:0xBE076240 0x[00000030] os: ** PC 0xbe0267bc VADDR (nil) BE0392D4:0xBE076280 0xB[00000030] os: ** PS 0x60320 E0396C3:0xBE0762A0 0xBE025604:0xBE0762D0 [00000030] os: ** (INTLEVEL:0 EXCM: 0 UM:1 RING:0 WOE:1 OWB:3 CALLINC:0x2) BE01557E:0xBE076300 0xBE0137BC:0xBE076330 [00000030] os: ** A0 0xbe026a82 SP 0xbe0761c0 A2 0x60040000 A3 0x9e07 fc00
> 
> [00000030] os: ** A4 0xc A5 0x1 A6 0x40000 A7 0xbe02a188 [00000030] os: ** A8 0xbe02678a A9 0xbe0761a0 A10 0x9e084740 A11 (nil) [00000030] os: ** A12 0x40000 A13 0x2 A14 0x9e07ef78 A15 0x9e07f00c [00000030] os: ** LBEG 0xbe040108 LEND 0xbe040116 LCOUNT 0xbe026788 [00000030] os: ** SAR 0xf [00000030] os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 2 [00000030] os: Current thread: 0x9e07e3b0 (unknown) [00000030] os: Halting system ``

I believe this is because printk is used to print the backtrace, which can lead to other issues. CONFIG_LOG_PRINTK=y should solve this.

**Review by andyross — DISMISSED** [review]
This version looks great to me.

**Review by dcpleung — DISMISSED** [review]

**Comment by andyross** [comment]
And right: per the discussion above, if there's desire to use printk() in application code alongside the logging macros, we almost certainly want to set CONFIG_LOG_PRINTK=y so that printk() is implemented in terms of logging.  Having both trace subsystems active at once is allowed, but really only useful for special purposes (e.g. you might be debugging one by using the other), and we don't want them interacting more than is absolutely required.  I think interleaving between the two seems acceptable to me given the obvious workaround.

**Comment by kv2019i** [comment]
@andyross wrote:
> And right: per the discussion above, if there's desire to use printk() in application code alongside the logging macros, we
> almost certainly want to set CONFIG_LOG_PRINTK=y so that printk() is implemented in terms of logging. Having both trace 

I can confirm this to be the case. With CONFIG_LOG_PRINTK (and this PR), the OS panic is clean including the backtrace. Submitted https://github.com/zephyrproject-rtos/zephyr/pull/44684 to enable this for SOF builds.

**Review by kv2019i — DISMISSED** [review]

**Review by laurenmurphyx64 — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Refresh vote

**Review by ceolin — APPROVED** [review]
