### PR TITLE
lib: updatehub: Fix getaddrinfo resource leak

### LINKED ISSUE #26994: [Coverity CID :210616] Resource leak in lib/updatehub/updatehub.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/476fc405e7/lib/updatehub/updatehub.c

Category: Resource leaks
Function: `start_coap_client`
Component: Other
CID: [210616](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=210616)

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by nandojve**
Add missing freeaddrinfo to fix memory leak.

Fixes #26994.

Signed-off-by: Gerson Fernando Budke <gerson.budke@ossystems.com.br>

### CODE REVIEW

**Comment by nandojve** [comment]
CC: @otavio

**Review by otavio — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

File: lib/updatehub/updatehub.c [hunk 1]
```diff
@@ -185,33 +185,41 @@ static bool start_coap_client(void)
...
 	}
 
 	prepare_fds();
 
-	return true;
+	ret = 0;
+
+error:
+	freeaddrinfo(addr);
+	addr = NULL;
```
Comment (ceolin) [inline lib/updatehub/updatehub.c:220]: why are you setting `addr` to NULL ? This variable is allocated in the stack and not used anymore.

File: lib/updatehub/updatehub.c [hunk 2]
```diff
@@ -185,33 +185,41 @@ static bool start_coap_client(void)
...
+
+	return (ret == 0) ? true : false;
```
Comment (ceolin) [inline lib/updatehub/updatehub.c:222]: Shouldn't you close the socket when returning false ? AFAIU you'll keep this socket open in a variable that is statically alloated

**Review by ceolin — COMMENTED** [review]
The fix itself is correct but it seems that you have to close the socket in your error path.

File: lib/updatehub/updatehub.c (hunk 1 above)
Comment (nandojve) [reply lib/updatehub/updatehub.c]: Removed.

File: lib/updatehub/updatehub.c (hunk 2 above)
Comment (nandojve) [reply lib/updatehub/updatehub.c:226]: Fixed.

File: lib/updatehub/updatehub.c [hunk 3]
```diff
@@ -185,44 +196,45 @@ static bool start_coap_client(void)
...
+	ret = 0;
+error:
+	freeaddrinfo(addr);
 
-static void cleanup_connection(void)
-{
-	if (close(ctx.sock) < 0) {
-		LOG_ERR("Could not close the socket");
+	if (ret > 0) {
+		cleanup_connection();
```
Comment (ceolin) [inline lib/updatehub/updatehub.c:234]: I don't think you need this extra function. `ctx.fds` is set only in `prepare_fds` that is not called in the error path.

File: lib/updatehub/updatehub.c [hunk 4]
```diff
@@ -146,6 +146,17 @@ is_compatible_hardware(struct resp_probe_some_boards *metadata_some_boards)
...
+{
+	if (close(ctx.sock) < 0) {
+		LOG_ERR("Could not close the socket");
+	}
+
+	memset(&ctx.fds[1], 0, sizeof(ctx.fds[1]));
+	ctx.nfds = 0;
+	ctx.sock = 0;
+}
+
```
Comment (jukkar) [inline lib/updatehub/updatehub.c:159]: Isn't this conflicting with #27223, do we need to have this change in this PR at all?

File: lib/updatehub/updatehub.c (hunk 3 above)
Comment (nandojve) [reply lib/updatehub/updatehub.c:234]: This is not a new extra function. I moved it up on code because is an internal without prototype. Since we added a for loop based on nfds and proper initialize nfds we can call cleanup_connection. This method will report an error if close is accessed without a valid socket. I think it is better keep only one way to close and clean the socket in this case.

File: lib/updatehub/updatehub.c (hunk 4 above)
Comment (nandojve) [reply lib/updatehub/updatehub.c]: The @27223 was already merged and it is safe now.

**Review by jukkar — APPROVED** [review]

**Review by ceolin — APPROVED** [review]
