### PR TITLE
mgmt: mcumgr: grp: img_mgmt: Fix not checking image upload size

### LINKED ISSUE #60899: mgmt: mcumgr: grp: img_mgmt: Upload does not bother to check slot size and silently stops responding
**Describe the bug**
It would appear that the size of an image is not checked against the size of the slot, this means an invalid image can be (partially) uploaded to a device, what actually happens is that there will be a point whereby the device responds OK with the next offset, then just stops responding entirely and does not even return an error.
The size of the upload is provided in the start packet so this should never occur.

**To Reproduce**
Upload image that is larger than a slot

**Expected behavior**
Upload to be rejected at the start with an error response

**Impact**
Showstopper

**Environment (please complete the following information):**
 - Commit SHA or Version used: b77d40d1fe4b2fd2bdcc4c640c4388b92999156a

### PR DESCRIPTION
**Pull request by nordicjm**
Fixes an issue whereby upload image size would not be checked in the first packet of an upload, which would allow an image to be uploaded until it reached the point of it being too large to fit anymore.

and

    mgmt: mcumgr: grp: img_mgmt: Fix not checking write bounds
    
    Fixes an issue whereby the data packets were not checked to ensure
    that the client has not attempted to write more data than the size
    that was provided in the original upload packet.

Fixes #60899

### CODE REVIEW

File: subsys/mgmt/mcumgr/grp/img_mgmt/src/zephyr_img_mgmt.c [hunk 1]
```diff
@@ -614,30 +616,35 @@ int img_mgmt_upload_inspect(const struct img_mgmt_upload_req *req,
...
-					rc);
-				return IMG_MGMT_RET_RC_FLASH_OPEN_FAILED;
-			}
+		/* Check that the area is of sufficient size to store the new image */
+		if (req->size > fa->fa_size) {
+			IMG_MGMT_UPLOAD_ACTION_SET_RC_RSN(action,
+				img_mgmt_err_str_image_too_large);
+			flash_area_close(fa);
+			LOG_ERR("Upload too large for slot: %u > %u", req->size, fa->fa_size);
+			return IMG_MGMT_RET_RC_INVALID_IMAGE_TOO_LARGE;
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/grp/img_mgmt/src/zephyr_img_mgmt.c:633]: This is good enough, although we probably need some boot API function to round down the size to actually available.
This will give us some problems because we are also able to upload already padded images.

**Review by de-nordic — DISMISSED** [review]

File: subsys/mgmt/mcumgr/grp/img_mgmt/src/zephyr_img_mgmt.c (hunk 1 above)
Comment (nordicjm) [reply subsys/mgmt/mcumgr/grp/img_mgmt/src/zephyr_img_mgmt.c:633]: For the application via MCUmgr this should not be a problem because the status is in the primary image slot which will be running (assuming swap using move mode)

**Review by de-nordic — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
