### PR TITLE
drivers: i2s_nrfx: Fix division by 0 in divider calculation

### LINKED ISSUE #70316: NRFX I2S Driver Bug -- division by zero
The NRF53 I2S driver fails with "division by zero" when user selects a 48Khz sampling frequency and an ACLK value of 11.2896. I haven't really researched the exact line, because I bypass clock division entirely, but the offending function is [find_suitable_clock].
Found it by mistake - obviously can't divide that 11.2896 by 48000, but there could be other combinations that yield similar results.

To reproduce, simply change the sampling frequency to 48000 in the i2s sample and run it.
The pdm peripheral uses a similar function, it's probably affected too.

(https://github.com/zephyrproject-rtos/zephyr/blob/20f747bb630b4ce9e84d5e3e7f525df19f33cc43/drivers/i2s/i2s_nrfx.c#L62)

### PR DESCRIPTION
**Pull request by barsok**
Skip cases which would result in division by 0 in clock calculation
Fixes #70316

### CODE REVIEW

File: drivers/i2s/i2s_nrfx.c [hunk 1]
```diff
@@ -113,6 +113,11 @@ static void find_suitable_clock(const struct i2s_nrfx_drv_cfg *drv_cfg,
 			uint32_t mck_factor =
 				(uint32_t)((requested_mck * 1048576ULL) /
 					   (src_freq + requested_mck / 2));
+
+			/* skip cases when mck_factor is too small for dividing */
+			if (mck_factor > 1048576) {
```
Comment (anangl) [inline drivers/i2s/i2s_nrfx.c:118]: I guess you meant "too big"

**Review by anangl — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

File: drivers/i2s/i2s_nrfx.c [hunk 2]
```diff
@@ -113,6 +113,11 @@ static void find_suitable_clock(const struct i2s_nrfx_drv_cfg *drv_cfg,
 			uint32_t mck_factor =
 				(uint32_t)((requested_mck * 1048576ULL) /
 					   (src_freq + requested_mck / 2));
+
+			/* skip cases when mck_factor is too big for dividing */
+			if (mck_factor > 1048576) {
```
Comment (masz-nordic) [inline drivers/i2s/i2s_nrfx.c:118]: How about making this magic number a define? Then it could be used here and in lines 114, 121.

Comment (barsok) [reply drivers/i2s/i2s_nrfx.c:118]: I wanted to avoid that as I would also need to include a macro to generate the "ULL" version of the constant; please let me know if you have suggestion how to do this in a way that does not clutter the code

Comment (barsok) [reply drivers/i2s/i2s_nrfx.c]: suggestion commited

**Review by masz-nordic — DISMISSED** [review]

**Review by kl-cruz — DISMISSED** [review]

File: drivers/i2s/i2s_nrfx.c [hunk 3]
```diff
@@ -110,10 +110,16 @@ static void find_suitable_clock(const struct i2s_nrfx_drv_cfg *drv_cfg,
 			 * f_actual = f_source /
 			 *            floor(1048576 * 4096 / MCKFREQ)
 			 */
+			 #define MCKCONST 1048576
```
[the remark this answers is not in the document]
Comment (nashif) [reply drivers/i2s/i2s_nrfx.c:113]: @barsok do you want to follow the suggestion above?

**Review by anangl — APPROVED** [review]

**Review by jaz1-nordic — APPROVED** [review]
