### PR TITLE
Bluetooth: controller: split: Fix for Tx Buffer Overflow error

### LINKED ISSUE #19490: Bluetooth: split: 'e' assert during disconnect
**Describe the bug**
When using the Split LL with Zephyr we occasionally observe crashes during different operations on master or slave side. Upon closer observation it looks like these asserts happen after a disconnect packet was sent. Reducing the maximum number of supported connecations does not fix this. Switching back to the legacy LL resolves this.

**To Reproduce**
Our ZTests connect to a peripheral and typically perform a couple of actions (e.g. GATT ops, pairing, L2CAP etc.). Then we disconnect and run the next test. I haven't found one specific test that always fails as the asserts appear to be happen randomly. 

**Expected behavior**
The stack should not crash.

**Impact**
showstopper

**Screenshots or console output**
```
[20:56:06:560] assert: 'e' failed␍␊
[20:56:06:571] [00:01:49.082,061] <0x1b>[1;31m<err> os: r0/a1: 0x00000003 r1/a2: 0x0000000a r2/a3: 0x00000001<0x1b>[0m␍␊
[20:56:06:571] [00:01:49.090,759] <0x1b>[1;31m<err> os: r3/a4: 0x0002e963 r12/ip: 0x00000008 r14/lr: 0x000197ef<0x1b>[0m␍␊
[20:56:06:579] [00:01:49.099,456] <0x1b>[1;31m<err> os: xpsr: 0x61000011<0x1b>[0m␍␊
[20:56:06:594] [00:01:49.104,705] <0x1b>[1;31m<err> os: Faulting instruction address (r15/pc): 0x000197fa<0x1b>[0m␍␊
[20:56:06:594] [00:01:49.112,609] <0x1b>[1;31m<err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops<0x1b>[0m␍␊
[20:56:06:600] [00:01:49.119,476] <0x1b>[1;31m<err> os: Current thread: 0x20001200 (BT ECC)<0x1b>[0m␍␊
[20:56:06:609] [00:01:49.126,190] <0x1b>[1;31m<err> os: Halting system<0x1b>[0m␍␊
```
grafik

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Kubuntu 18.04
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK 0.10.3
 - Commit SHA or Version used: 2051ad1

**Additional context**

### PR DESCRIPTION
**Pull request by cvinayak**
When more than one simultaneous connections are active,
transmitting data packets to peer, a termination causes
host to use the flushed pending number of completed packets
count for other active connections. This is on reception
of HCI disconnection complete event. But the controller has
not yet released any of the pending enqueued Tx buffers
which was happening after the disconnection event was
dispatched to HCI layer.

The fix here is to dispatch the disconnection complete event
from the LLL context after pending Tx buffers have been
flushed and the buffers get returned to Tx pool in the ULL
context. This way buffers are in the Tx pool before host
get to process the disconnection complete event.

Fixes #19490.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 1]
```diff
@@ -1506,12 +1506,18 @@ static inline void disable(u16_t handle)
...
+static void conn_cleanup(struct ll_conn *conn, u8_t reason)
 {
 	struct lll_conn *lll = &conn->lll;
 	struct node_rx_pdu *rx;
 	u32_t ticker_status;
 
+	/* Prepare the rx packet structure */
+	rx = (void *)&conn->llcp_terminate.node_rx;
+	rx->hdr.handle = conn->lll.handle;
+	rx->hdr.type = NODE_RX_TYPE_TERMINATE;
```
Comment (wopu-ot) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: It is not clear to me how the termination is propagated upwards from here. If the code in lines 1599ff is doing the propagation, maybe the respective code should be moved here to make it clearer?

**Review by wopu-ot — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 2]
```diff
@@ -1202,6 +1196,44 @@ void ull_conn_tx_demux(u8_t count)
...
+
+		/* point to self to indicate a control PDU mem alloc */
+		tx->next = tx;
+
+		if (0) {
+			struct pdu_data *p;
+
+			p = (void *)tx->pdu;
+			printk(" <<%u\n", p->llctrl.opcode);
+		}
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: oh!. Thanks for pointing out.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 3]
```diff
@@ -1202,6 +1196,44 @@ void ull_conn_tx_demux(u8_t count)
...
+			conn->tx_data = conn->tx_data->next;
+		}
+		conn->tx_head = conn->tx_head->next;
+
+		/* point to NULL to indicate a Data PDU mem alloc */
+		tx->next = NULL;
+
+		if (0) {
+			printk(" <<D\n");
+		}
```
[the remark this answers is not in the document]
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Thanks

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Only the termination structure is populated here, ULL context but enqueued in the LLL context in ```tx_lll_flush``` .The reason for population to void passing the ```reason``` and ```handle``` through the mayfly scheduling the tx_lll_flush.

Comment (wopu-ot) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Ok, that makes sense. Maybe you could add what you just wrote as comment to the code?

**Review by wopu-ot — COMMENTED** [review]
If you could add a comment to the code in ull_conn.c:1514 (Prepare the rx packet structure), I would be happy.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Will do.

**Review by wopu-ot — APPROVED** [review]
LGTM

**Review by carlescufi — APPROVED** [review]
