### PR TITLE
net: tcp: Make sure TCP context is dereferenced only once on network down

### LINKED ISSUE #101416: It seems tcp accept had some issue during link changes
### Describe the bug

When I was working on PR https://github.com/zephyrproject-rtos/zephyr/pull/101413, I found tcp accept had some issue during link changes.

When running mdns_responder example, if we hot plug the cable twice. There will be calltrace as below.
```
[00:01:01.761,000] <err> os: ***** HARD FAULT *****
[00:01:01.761,000] <err> os:   Bus fault on vector table read
[00:01:01.761,000] <err> os: r0/a1:  0xfefa125b  r1/a2:  0x00000000  r2/a3:  0x00000073
[00:01:01.761,000] <err> os: r3/a4:  0x1400e610 r12/ip:  0x38012a35 r14/lr:  0x1400b538
[00:01:01.761,000] <err> os:  xpsr:  0x1400bc00
[00:01:01.761,000] <err> os: Faulting instruction address (r15/pc): 0x1400b3dc
[00:01:01.762,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:01:01.762,000] <err> os: Current thread: 0x1400d860 (sysworkq)
[00:01:01.859,000] <err> os: Halting system

```

The reason is `sockets_inet.c` `zsock_accepted_cb` was releasing parent net_context twice.
I make a workaround but I think it's not proper fix as I don't understand the stack well.

```
diff --git a/subsys/net/ip/tcp.c b/subsys/net/ip/tcp.c
index d7ddae22828..6197c488ccb 100644
--- a/subsys/net/ip/tcp.c
+++ b/subsys/net/ip/tcp.c
@@ -4764,8 +4764,8 @@ static void close_tcp_conn(struct tcp *conn, void *user_data)
                net_tcp_put(context, true);
        } else {
                if (context->conn_handler) {
-                       net_conn_unregister(context->conn_handler);
-                       context->conn_handler = NULL;
+               //      net_conn_unregister(context->conn_handler);
+               //      context->conn_handler = NULL;
                }

                if (conn->accept_cb != NULL) {
diff --git a/subsys/net/lib/sockets/sockets_inet.c b/subsys/net/lib/sockets/sockets_inet.c
index ae47f2aba8a..9081aa71727 100644
--- a/subsys/net/lib/sockets/sockets_inet.c
+++ b/subsys/net/lib/sockets/sockets_inet.c
@@ -217,11 +217,11 @@ static void zsock_accepted_cb(struct net_context *new_ctx,

                (void)k_condvar_signal(&parent->cond.recv);
        } else if (status < 0) {
-               parent->user_data = INT_TO_POINTER(-status);
-               sock_set_error(parent);
+               //parent->user_data = INT_TO_POINTER(-status);
+               //sock_set_error(parent);

-               k_fifo_cancel_wait(&parent->recv_q);
-               (void)k_condvar_signal(&parent->cond.recv);
+               //k_fifo_cancel_wait(&parent->recv_q);
+               //(void)k_condvar_signal(&parent->cond.recv);
        }
 }

```

Hope someone can help.
Thanks.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rlubos**
* Fix a crash caused by listening TCP socket, when network interface went down twice **before** the application released the socket.
* Update `zsock_accept()` to report an error if the unerlying TCP context is no longer usable.
* Update the `mdns_responder` sample to restart the TCP echo server it implements in case of errors.

Fixes #101416

### CODE REVIEW

File: samples/net/mdns_responder/src/service.c [hunk 1]
```diff
@@ -151,4 +132,55 @@ void service(void)
...
+
+/* This is mainly here to bind to a port to get service advertisement
+ * to work.. but since we're already here we might as well do something
+ * useful.
+ */
+void service(void)
+{
+	int r = 0;
+
+	static struct sockaddr server_addr;
```
Comment (jukkar) [inline samples/net/mdns_responder/src/service.c]: In practice this works and the original code was using sockaddr, but we should change this to `sockaddr_storage`

**Review by jukkar — COMMENTED** [review]
Nice catch, just a minor nit for the mdns change.

File: samples/net/mdns_responder/src/service.c (hunk 1 above)
Comment (rlubos) [reply samples/net/mdns_responder/src/service.c]: True, updated

**Review by jukkar — APPROVED** [review]

**Review by pdgendt — APPROVED** [review]
