### PR TITLE
fs: Fix buffer overflow when LFN is enabled with FATFS

### LINKED ISSUE #25710: FS: Buffer Overflow when enabling Long File Names in FAT_FS and calling fs_stat
I found a bug with enabling Long File Name (LFN) and using FATFS. 

Performing `fs_stat` on a file with a filename larger than 12 characters long will cause a buffer overflow.

Where the overflow occurs:
https://github.com/zephyrproject-rtos/zephyr/blob/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/subsys/fs/fat_fs.c#L306

The struct defined with MAX_FILE_NAME
https://github.com/zephyrproject-rtos/zephyr/blob/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/include/fs/fs.h#L89-L93

MAX_FILE_NAME set to 12 when using LITTLEFS and not when LFN is enabled for FATFS
https://github.com/zephyrproject-rtos/zephyr/blob/4653b4e63f886a50ac7b72f8d47ba2950ab2dd0d/include/fs/fs_interface.h#L14-L18

I caught this issue when checking if a file existed on disk with the filename `2020-05-28-1346.log`

**To Reproduce**
1. Enable Long File Name support (i,e. `CONFIG_FS_FATFS_LFN=y` in `prj,conf`)
2. after mounting a filesystem, call `fs_stat("/SD:/some-long-file-name.txt", ...);`
3. build, targeting `native_posix`
4. See `*** buffer overflow detected ***: terminated` in the output when running `zephyer.exe`

**Expected behavior**
`fs_stat` will return with a result, typically `-ENOENT`.

**Impact**
Corrupted memory if there is no memory protection in place. 

**Screenshots or console output**
Output from gdb
```
(gdb) file zephyr/zephyr.exe
Reading symbols from zephyr/zephyr.exe...
(gdb) run
Starting program: /home/nzsmartie/Projects/smartbike/app/sanity-out/native_posix/processor.logger/zephyr/zephyr.exe

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0xf7c7eb40 (LWP 413479)]
[New Thread 0xf72ffb40 (LWP 413480)]
[New Thread 0xf6afeb40 (LWP 413481)]
*** Booting Zephyr OS build zephyr-v2.2.0  ***
[Thread 0xf7c7eb40 (LWP 413479) exited]
Running test suite logger_processor_test
===================================================================
starting test - test_logger_file
[New Thread 0xf7c7eb40 (LWP 413482)]
E: failed get file or dir stat (-2)
D: Successfully opened log file: /NAND:/SmartBike/Logs/2020-05-28-1340.log
*** buffer overflow detected ***: terminated

Thread 5 "zephyr.exe" received signal SIGABRT, Aborted.
[Switching to Thread 0xf7c7eb40 (LWP 413482)]
0xf7fd0b49 in __kernel_vsyscall ()
(gdb) backtrace
#0  0xf7fd0b49 in __kernel_vsyscall ()
#1  0xf7cb64c6 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7c9e3f7 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf7cfb4ac in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf7d9936c in __fortify_fail () from /lib/i386-linux-gnu/libc.so.6
#5  0xf7d97d7f in __chk_fail () from /lib/i386-linux-gnu/libc.so.6
#6  0xf7d97805 in __strcpy_chk () from /lib/i386-linux-gnu/libc.so.6
#7  0x5655e9b3 in strcpy (__src=0xf7c7deda "2020-05-28-1340.log",
    __dest=0xf7c7e054 "\b\001\353\367L\341\307", <incomplete sequence \367>)
    at /usr/include/bits/string_fortified.h:90
#8  fatfs_stat (mountp=0x5656c040 <test_mount>, path=0xf7c7e078 "/NAND:/SmartBike/Logs/2020-05-28-1340.log",
    entry=0xf7c7e050) at /home/nzsmartie/Projects/smartbike/zephyr/subsys/fs/fat_fs.c:306
#9  0x5655e60e in fs_stat (abs_path=<optimized out>, entry=0xf7c7e050)
    at /home/nzsmartie/Projects/smartbike/zephyr/subsys/fs/fs.c:459
#10 0x5655b0d3 in test_log_created ()
    at /home/nzsmartie/Projects/smartbike/app/tests/processor/logger/src/main.cpp:63
#11 0x5655b24b in test_logger_file ()
    at /home/nzsmartie/Projects/smartbike/app/tests/processor/logger/src/main.cpp:105
#12 0x5655f03a in run_test_functions (test=0x5656c000 <test_main::_logger_processor_test>)
    at /home/nzsmartie/Projects/smartbike/zephyr/subsys/testsuite/ztest/src/ztest.c:148
#13 test_cb (a=0x5656c000 <test_main::_logger_processor_test>, dummy2=0x0, dummy=0x0)
    at /home/nzsmartie/Projects/smartbike/zephyr/subsys/testsuite/ztest/src/ztest.c:281
#14 0x5655b948 in z_thread_entry (entry=0x5655f00a <test_cb>, p1=0x5656c000 <test_main::_logger_processor_test>,
    p2=0x0, p3=0x0) at /home/nzsmartie/Projects/smartbike/zephyr/lib/os/thread_entry.c:29
#15 0x5655c41b in posix_thread_starter (arg=0x2)
    at /home/nzsmartie/Projects/smartbike/zephyr/arch/posix/core/posix_core.c:305
#16 0xf7e77635 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#17 0xf7d8973a in clone () from /lib/i386-linux-gnu/libc.so.6
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK `v0.11.2`
 - Zephyr: `v2.2.0` (9518bd19b7a736bd649fa2fc8d8d52967c0b486f)

**Additional context**
~While reporting this issue. I attempted to modify `tests/subsys/fs/fat_fs_api` to reproduce the above issue with `CONFIG_FS_FATFS_LFN=y`. However, multiple compiler warnings came up revolving around the same problem.~ (This is due to me to trying to identify the issue, and is not observed in a clean pull of zephyr).
```
[ 11%] Building C object CMakeFiles/app.dir/src/test_fat_dir.c.obj
/home/nzsmartie/Projects/smartbike/zephyr/tests/subsys/fs/fat_fs_api/src/test_fat_dir.c: In function ‘test_rmdir’:
/home/nzsmartie/Projects/smartbike/zephyr/tests/subsys/fs/fat_fs_api/src/test_fat_dir.c:134:26: error: ‘%s’ directive writing up to 256 bytes into a region of size 65 [-Werror=format-overflow=]
  134 |   sprintf(file_path, "%s/%s", TEST_DIR, entry.name);
      |                          ^~             ~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from /home/nzsmartie/Projects/smartbike/zephyr/subsys/testsuite/ztest/include/ztest_assert.h:18,
                 from /home/nzsmartie/Projects/smartbike/zephyr/subsys/testsuite/ztest/include/ztest.h:59,
                 from /home/nzsmartie/Projects/smartbike/zephyr/tests/subsys/fs/fat_fs_api/src/test_fat.h:8,
                 from /home/nzsmartie/Projects/smartbike/zephyr/tests/subsys/fs/fat_fs_api/src/test_fat_dir.c:13:
/usr/include/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 16 and 272 bytes into a destination of size 80
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by NZSmartie**
This PR creates a test case for calling `fs_stat`, `fs_open` and `fs_close` on a file with a long file name. (though it does not exhaust the 255 length). This also includes the fix to resolve the buffer overflow observed in #25710. There is also a fix in an adjacent test case that used a hard coded path length of 80l.

fixes #25710

### CODE REVIEW

**Review by pabigot — CHANGES_REQUESTED** [review]
Looks good overall, one requested cleanup of the length detection logic.

**Comment by ceolin** [comment]
What @pabigot said makes sense. Nothing else from my side :)

File: include/fs/fs_interface.h [hunk 1]
```diff
@@ -13,6 +13,12 @@ extern "C" {
 
 #if defined(CONFIG_FILE_SYSTEM_LITTLEFS)
 #define MAX_FILE_NAME 256
+#elif defined(CONFIG_FS_FATFS_LFN)
```
[the remark this answers is not in the document]
Comment (NZSmartie) [reply include/fs/fs_interface.h]: I've opted to define `MAX_FILE_NAME` based on selected filesystem as per your example, but also added a fallback for when `MAX_FILE_NAME` isn't defined. to help improve readability.

File: include/fs/fs_interface.h [hunk 2]
```diff
@@ -13,7 +13,14 @@ extern "C" {
...
 #define MAX_FILE_NAME 256
-#else /* FAT_FS */
+#elif defined(CONFIG_FAT_FILESYSTEM_ELM)
+#if defined(CONFIG_FS_FATFS_LFN)
+#define MAX_FILE_NAME CONFIG_FS_FATFS_MAX_LFN
+#endif /* CONFIG_FS_FATFS_LFN */
+#endif /* filesystem selection */
+
+#ifndef MAX_FILE_NAME
+/* Fallback to SFN when no filesystem is explicitly selected */
```
Comment (pabigot) [inline include/fs/fs_interface.h:23]: This is not right.  If you have FatFS, but didn't pick LFN, you should get 8.3 SFN.  Not whatever default is provided when the file system isn't defined.  Please provide the fallback for `FAT_FILESYSTEM_ELM` within the branch for that filesystem.

If you want to add an `#else /* filesystem selection*/` that also defines `MAX_FILE_NAME` that'd be fine.  It's not necessary because the subsystem won't work in that case until #25883 is fixed, though.

Also the fix(es) should be squashed into the original commit that changed the definition.

**Review by pabigot — CHANGES_REQUESTED** [review]

File: include/fs/fs_interface.h (hunk 2 above)
Comment (NZSmartie) [reply include/fs/fs_interface.h:23]: Before I committed, I ran `$ZEPHYR_BASE/scripts/sanitycheck -T tests/subsys/fs/` with the following:
```c
#if defined(CONFIG_FILE_SYSTEM_LITTLEFS)
#define MAX_FILE_NAME 256
#elif defined(CONFIG_FAT_FILESYSTEM_ELM)
#if defined(CONFIG_FS_FATFS_LFN)
#define MAX_FILE_NAME CONFIG_FS_FATFS_MAX_LFN
#else
#define MAX_FILE_NAME 12 /* Uses 8.3 SFN */
#endif /* CONFIG_FS_FATFS_LFN */
#endif /* filesystem selection */
```

sanity check failed with the following:
```
INFO    - JOBS: 4
INFO    - Selecting default platforms per test case
INFO    - Building initial testcase list...
INFO    - 11 test configurations selected, 1981 configurations discarded due to filters.
INFO    - Adding tasks to the queue...

ERROR   - native_posix              tests/subsys/fs/fcb/filesystem.fcb                 FAILED: Build failure
ERROR   - see: /home/nzsmartie/Projects/zephyr/zephyr/sanity-out/native_posix/tests/subsys/fs/fcb/filesystem.fcb/build.log
INFO    - Total complete:    1/  11   9%  skipped:    0, failed:    1
ERROR   - qemu_x86                  tests/subsys/fs/nvs/filesystem.nvs                 FAILED: Build failure
ERROR   - see: /home/nzsmartie/Projects/zephyr/zephyr/sanity-out/qemu_x86/tests/subsys/fs/nvs/filesystem.nvs/build.log
INFO    - Total complete:   11/  11  100%  skipped:    0, failed:    2
INFO    - 9 of 11 tests passed (81.82%), 2 failed, 0 skipped with 0 warnings in 74.84 seconds
INFO    - In total 8 test cases were executed on 2 out of total 250 platforms (0.80%)
INFO    - 9 tests executed on platforms, 2 tests were only built.
```
The first build log contained:
```
[ 27%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/fdtable.c.obj
In file included from /home/nzsmartie/Projects/zephyr/zephyr/include/sys/fdtable.h:12,
                 from /home/nzsmartie/Projects/zephyr/zephyr/lib/os/fdtable.c:19:
/home/nzsmartie/Projects/zephyr/zephyr/include/fs/fs.h:91:12: error: ‘MAX_FILE_NAME’ undeclared here (not in a function)
   91 |  char name[MAX_FILE_NAME + 1];
```
while the second also contained:
```
[ 16%] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/fdtable.c.obj
In file included from /home/nzsmartie/Projects/zephyr/zephyr/include/sys/fdtable.h:12,
                 from /home/nzsmartie/Projects/zephyr/zephyr/lib/os/fdtable.c:19:
/home/nzsmartie/Projects/zephyr/zephyr/include/fs/fs.h:91:12: error: 'MAX_FILE_NAME' undeclared here (not in a function); did you mean 'MK_ISR_NAME'?
   91 |  char name[MAX_FILE_NAME + 1];
      |            ^~~~~~~~~~~~~
      |            MK_ISR_NAME
```

My intuition is to preserve the original behaviour of having `MAX_FILE_NAME` defined as `12` (8.3) since these testcases apper to use neither FatFS or LittleFS but still rely on `MAX_FILE_NAME`

By having the fallback `#ifndef`, i'm not repeating code and preserve readability.

Comment (NZSmartie) [reply include/fs/fs_interface.h:23]: I do agree with the squashing, and will do that once changes are approved

Comment (pabigot) [reply include/fs/fs_interface.h:23]: > By having the fallback `#ifndef`, i'm not repeating code and preserve readability.

No, you're not.  You're leaving the specification for `FILESYSTEM_FAT_ELM` incomplete, then using its unhandled case as a default when there are no file systems.  We may want to change the default for no-file-system to something else without breaking FatFS.

Please make the change as I requested.  It should look like this:
```
#if defined(CONFIG_FILE_SYSTEM_LITTLEFS)
#define MAX_FILE_NAME 256
#elif defined(CONFIG_FAT_FILESYSTEM_ELM)
#if defined(CONFIG_FS_FATFS_LFN)
#define MAX_FILE_NAME CONFIG_FS_FATFS_MAX_LFN
#else /* CONFIG_FS_FATFS_LFN */
#define MAX_FILE_NAME 12 /* Uses 8.3 SFN */
#endif /* CONFIG_FS_FATFS_LFN */
#else /* filesystem selection */
/* Use standard 8.3 when no filesystem is explicitly selected */
#define MAX_FILE_NAME 12
#endif /* filesystem selection */
```

Comment (pabigot) [reply include/fs/fs_interface.h:23]: You should squash first; it's not going to get approved as separate commits that need to be squashed.

Comment (NZSmartie) [reply include/fs/fs_interface.h]: That makes sense. Sorry for the delay on the update. Changes are pushed and thank you for your feedback!

**Review by pabigot — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]

**Comment by pabigot** [comment]
Close and re-open in attempt to kick buildkite into retesting.

**Comment by pabigot** [comment]
@NZSmartie Please rebase this on current master so the buildkite process can see a configuration that will actually work.
