### PR TITLE
drivers: i3c: common: Do not treat GETCAPS failure as error for 1.0 d…

### LINKED ISSUE #76519: Get I3C basic device fails for devices that do not support GETCAP
**Get I3C basic device fails for devices that do not support GETCAPS **

**To Reproduce**
1. cd samples/subsys/shell/shell_module 
2. west build -c -p always -b npcx4m8f_evb -- -DCONFIG_I3C_SHELL
3. Flash NPCX4 EVB
4. See error in driver initialization

**Expected behavior**
I3C devices that do not support GETCAPS should not fail initialization during get basic info

**Impact**

I3C 1.0 device initialization is incomplete

**Logs and console output**
image

### PR DESCRIPTION
**Pull request by albertofloyd**
If it's a I3C v1.0 device without any HDR modes do not treat as an error if GETCAPS gives no valid response.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/76519

### CODE REVIEW

File: drivers/i3c/i3c_common.c [hunk 1]
```diff
@@ -563,6 +563,7 @@ int i3c_device_basic_info_get(struct i3c_device_desc *target)
 		goto out;
 	}
 
+	ret = 0;
```
Comment (dcpleung) [inline drivers/i3c/i3c_common.c:566]: I think this should be moved into the `else` block above in line 562.

Comment (XenuIsWatching) [reply drivers/i3c/i3c_common.c:566]: yes, or an else block on 564

**Review by dcpleung — APPROVED** [review]

**Review by XenuIsWatching — APPROVED** [review]

File: drivers/i3c/i3c_common.c (hunk 1 above)
Comment (albertofloyd) [reply drivers/i3c/i3c_common.c]: changed
