### PR TITLE
Bluetooth: GATT: Remove all subscriptions for connection when unpairing

### LINKED ISSUE #21131: Bluetooth: host: Subscriptions not removed upon unpair
**Describe the bug**
When having a central being connected (and bonded) with one peripheral at a time, it's not possible to unpair and then reconnect/pair to a second device without allocating a `struct bt_gatt_subscribe_params` per connection.

**To Reproduce**
1. Configure a BLE central device with `CONFIG_SMP=y` and `CONFIG_BT_SETTINGS=y`
2. Connect and pair/bond with a peripheral
3. Enable notifications on a characteristic
4. Disconnect the peripheral and call `bt_unpair`
5. Try to connect and pair/bond with a second peripheral
6. Enable notifications on the same characteristic (same `struct bt_gatt_subscribe_params`)

**Expected behavior**
Subscriptions for a bonded device should be removed upon unpair, and  the `struct bt_gatt_subscribe_params` should allow re-use afterwards.

**Impact**
Increased code complexity and memory usage.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: gcc-arm-none-eabi-8-2019-q3-update
 - Commit v1.14.1

### PR DESCRIPTION
**Pull request by jsiverskog**
Make sure all subscriptions are removed when a connection is unpaired.

Fixes #21131

Signed-off-by: Jacob Siverskog <jacob@teenage.engineering>

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -4171,6 +4189,9 @@ int bt_gatt_clear(u8_t id, const bt_addr_le_t *addr)
 		return err;
 	}
 
+#if defined(CONFIG_BT_GATT_CLIENT)
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c]: Make this check interval to bt_gatt_clear_subscriptions so we don't have it in multiple places, the compiler will optimize it out if there is no code inside.

File: subsys/bluetooth/host/gatt.c [hunk 2]
```diff
@@ -2214,7 +2214,8 @@ static void gatt_subscription_remove(struct bt_conn *conn, sys_snode_t *prev,
 	/* Remove subscription from the list*/
 	sys_slist_remove(&subscriptions, prev, &params->node);
 
-	params->notify(conn, params, NULL, 0);
+	if (conn)
+		params->notify(conn, params, NULL, 0);
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c]: This one Im not really following, don't you want to notify that a subscription has been removed even if it is a result of unpair?

Comment (jsiverskog) [reply subsys/bluetooth/host/gatt.c]: `bt_gatt_clear` is called after `bt_conn_disconnect` (see `bt_unpair` in `hci_core.c`) - I guess that needs to be changed in order to fix this.

File: subsys/bluetooth/host/gatt.c (hunk 1 above)
Comment (jsiverskog) [reply subsys/bluetooth/host/gatt.c]: I pushed a new version now, is that how you meant?

File: subsys/bluetooth/host/gatt.c (hunk 2 above)
Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Id say we should indicate in the documentation that conn can be NULL since unpair don't require one so that we can remove the subscription even when disconnected.

Comment (jsiverskog) [reply subsys/bluetooth/host/gatt.c]: Fixed.

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by jhedberg — CHANGES_REQUESTED** [review]
Shouldn't you also handle the case when all pairings are requested to be cleared, i.e. when `bt_unpair()` ends up calling `bt_clear_all_pairings()? Or is that already covered?

**Comment by jsiverskog** [comment]
@jhedberg : That sounds reasonable. However, that requires larger changes, right? Possibly unrelated to this particular fix. No GATT cleanup is done when calling `bt_clear_all_pairings`. Can we instead of handling "unpair all" as a special case iterate over all paired addresses, doing the actions in `bt_unpair` on each?

**Comment by jhedberg** [comment]
@jsiverskog hmm, you're right - it seems like there's been a bug with clearing all GATT info. In that case it can be fixed independently. @Vudentz is this the right interpretation?

**Comment by jsiverskog** [comment]
@jhedberg @Vudentz : Something like this? https://github.com/zephyrproject-rtos/zephyr/pull/21141

**Comment by jhedberg** [comment]
@jsiverskog I just took a look at the existing master branch code, and bt_keys_clear_all() does call bt_gatt_clear() in its callback. So does the issue I raised even exist?

**Comment by jsiverskog** [comment]
@jhedberg: Right - no, then it doesn't look like an issue. The other MR should be considered a pure refactoring.

**Review by jhedberg — APPROVED** [review]

**Comment by carlescufi** [comment]
@joerchan are you happy with this?

**Comment by joerchan** [comment]
@jhedberg The issue is reported as affecting v1.14.1, should we perhaps backport it then?

**Review by joerchan — CHANGES_REQUESTED** [review]
Possible NULL pointer now that the notify function can give conn = NULL.

Seems to only affect the tester:
tests/bluetooth/tester/src/gatt.c::notify_func

**Comment by jsiverskog** [comment]
@joerchan : Thanks, fixed.

**Review by joerchan — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by jsiverskog** [comment]
What is the process with backporting, should I create another PR for that or who is responsible?

**Comment by jhedberg** [comment]
@jsiverskog normally the `backport v1.14-branch` label should take care of auto-creating a new PR against the `v1.14-branch` branch upon merging the original PR, but for some reason that didn't happen here (maybe the label was added only after merging). In that case you're free to submit a backport PR against the 1.14 branch. After that it needs to get the necessary approvals and be added to the "To do" column in https://github.com/zephyrproject-rtos/zephyr/projects/19. The last part is something I can take care of.
