### PR TITLE
Bluetooth: host: ensure ownership of conn on TX path

### LINKED ISSUE #75152: `bt_conn_tx_processor` does not use reference-counting
When upper layers want to send something, they add a `conn` object to a list. They do so by adding a node on `struct conn` rather than the object itself.

We forgot to increase the reference count of the connection object when doing so. This means that there can be a scenario where the conn object is destroyed and re-used while still being on the TX list/queue.

This is bad for obvious reasons.

To reproduce:
Run this test, observe failing assert that `conn->ref > 0`
https://github.com/jori-nordic/zephyr/blob/ce2e1f2b5f1f9b725d6f26b9bb493c0ffbad211e/tests/bsim/bluetooth/host/l2cap/multilink_peripheral/test_scripts/run.sh#L27

image

### PR DESCRIPTION
**Pull request by jori-nordic**
This is a bug-fix:

When upper layers want to send something, they add a `conn` object to a list. They do so by adding a node on `struct conn` rather than the object itself.

We forgot to increase the reference count of the connection object when doing so. This means that there can be a scenario where the conn object is destroyed and re-used while still being on the TX list/queue.

This is bad for obvious reasons.

This patch fixes that by:
- increasing the refcount when putting on the TX list
- decreasing the refcount *only* when popping off the TX list
- passing a new reference from `get_conn_ready` into `bt_conn_tx_processor`

Fixes #75152

### CODE REVIEW

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -804,6 +808,12 @@ void bt_conn_data_ready(struct bt_conn *conn)
 
 	/* The TX processor will call the `pull_cb` to get the buf */
 	if (!atomic_set(&conn->_conn_ready_lock, 1)) {
+		/* Attach a reference to the `bt_dev.le.conn_ready` list.
+		 *
+		 * This reference will be consumed when the conn is popped off
+		 * the list (in `get_conn_ready`).
+		 */
+		bt_conn_ref(conn);
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:816]: Suggest to add this to the "documentation" of the function, as it is otherwise not obvious.

File: subsys/bluetooth/host/conn.c [hunk 2]
```diff
@@ -984,8 +1003,12 @@ void bt_conn_tx_processor(void)
 
 	LOG_DBG("processing conn %p", conn);
 
+	/* Sanity-check: do we have ownership? */
+	__ASSERT_NO_MSG(conn->ref > 0);
```
Comment (Thalley) [inline subsys/bluetooth/host/conn.c:1007]: Shouldn't this be > 1 to _somewhat_ assert ownership? 

If the conn exists without any pending TX, then the ref count is still at least 1. 

It may even be 10 or 20, as the reference counter can be incremented anywhere by anyone. 

Not sure if this check is really useful

**Review by Thalley — CHANGES_REQUESTED** [review]
The issue being fixed refer to a test case that shows this issue. Wouldn't it make sense to also push the test here to verify?

**Comment by Thalley** [comment]
> The issue being fixed refer to a test case that shows this issue. Wouldn't it make sense to also push the test here to verify?

Just saw that you just pushed the test here: https://github.com/zephyrproject-rtos/zephyr/pull/75154

File: subsys/bluetooth/host/conn.c (hunk 2 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/conn.c:1007]: It was triggered without the fix in a bsim test (no PR for the test yet, I think). That means ref could be 1 here.

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/conn.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/host/conn.c:1007]: But if we take a reference at connection creation (which we do), and take a reference when we add it to the TX list, and then see the value 1 here, doesn't that imply a missing ref or too many unrefs somewhere? 

If it is 1 here, and we unref it later in this function, then we may end with a ref count of 0. 

But I guess that may actually happened if we are in the disconnected state? In which case, this check should be moved to the `if (conn->state != BT_CONN_CONNECTED) {` clause, or be something like 
```c
__ASSERT_NO_MSG(conn->ref >= conn->state == BT_CONN_CONNECTED ? 2 : 1);
```

File: subsys/bluetooth/host/conn.c [hunk 3]
```diff
@@ -1044,9 +1071,13 @@ void bt_conn_tx_processor(void)
 		destroy_and_callback(conn, buf, cb, ud);
 		bt_conn_disconnect(conn, BT_HCI_ERR_REMOTE_USER_TERM_CONN);
 
+		bt_conn_unref(conn);
 		return;
 	}
 
+	/* Also need to unref for the happy path */
+	bt_conn_unref(conn);
```
Comment (jhedberg) [inline subsys/bluetooth/host/conn.c:1079]: Maybe it'd be a bit cleaner to have something like this at the end of the function, assuming it's ok to swap `irq_raise()` and `unref()`:
```c
	bt_tx_irq_raise();
done:
	bt_conn_unref(conn);
}
```

And then `goto done;` in all the branches where you're needing to return from the function.

**Comment by jori-nordic** [comment]
> Wouldn't it make sense to also push the test here to verify

The test depends on a race condition. The version that triggers the assert is very in-development version and not pretty.
The cleaned-up version in the other PR doesn't trigger the assert, as it has a different scheduling pattern.

We have merged bugfixes in the past referencing a failing bsim test that was not merged (or in development).

File: subsys/bluetooth/host/conn.c (hunk 3 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/conn.c:1079]: should be ok to swap as this fn always runs from the same thread.

File: subsys/bluetooth/host/conn.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/host/conn.c:1007]: Sure, if it's too much to request to fix, we can postpone it. 

It is (IMO) similar to a function that validates that a value is less than 10 implemented as
```
/* Checks if @p val is less than 10 */
bool foo(int val)
{
    return val < 20;
}
```

It's arguably better than not having the check a all (as it will properly check values like `100`), but it also does not check the value correctly if there are false positives which I believe there is.

File: subsys/bluetooth/host/conn.c (hunk 3 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/conn.c]: done

File: subsys/bluetooth/host/conn.c (hunk 2 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/conn.c]: I just removed the assert. The compiler sees `{ }` in 99% cases anyways :)

**Review by alwa-nordic — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Comment by aescolar** [comment]
@jori-nordic Please note that priority labels are not used for PRs
https://docs.zephyrproject.org/latest/project/dev_env_and_tools.html#labels-applicable-to-issues-only

**Comment by jori-nordic** [comment]
Good to know, thanks!

**Comment by Thalley** [comment]
> @jori-nordic Please note that priority labels are not used for PRs https://docs.zephyrproject.org/latest/project/dev_env_and_tools.html#labels-applicable-to-issues-only

@aescolar that might need an update: The Zephyr bot automatically adds the `Release Notes` label to PRs :P

**Comment by aescolar** [comment]
> @aescolar that might need an update: The Zephyr bot automatically adds the Release Notes label to PRs :P

Yep, the release notes one is not correct in that list :)
The comment on the priority label is still relevant though. A PR is note merged faster or slower just because it has a priority label.

**Comment by jori-nordic** [comment]
Yeah my intuition was that it had to match the issue prio, that's why I added it.
