### PR TITLE
net: Fix net mgmt slist loop

### LINKED ISSUE #69825: net: mgmt: Infinite loop when same handler is added twice
**Describe the bug**
Network management doesn't detect and handle duplicate handlers causing infinite loop during the network initialisation.

**To Reproduce**
1. Use this branch https://github.com/krish2718/zephyr/commit/668103d6d3d0ab8ab0dc6376da5aa826efacccd3
2. `west board -p -b native_posix_64 tests/net/mgmt`
3. `./build/zephyr/zephyr.exe`
4. It hangs

**Expected behavior**
Test should pass.

**Impact**
`NET_CONFIG_AUTO_INIT + net_config_init_app + NET_DHCPV4` causes hang at boot as DHCPv4 registers duplicate handlers.

**Logs and console output**
Running the test on the Latest head should suffice.

**Additional context**
None

### PR DESCRIPTION
**Pull request by krish2718**
In case the same callback handler is added to the list twice, this can
result in a loop.
    
Fixes: #69825

### CODE REVIEW

File: tests/net/mgmt/src/mgmt.c [hunk 1]
```diff
@@ -423,4 +423,28 @@ ZTEST(mgmt_fn_test_suite, test_mgmt)
...
+{
+	struct net_mgmt_event_callback cb;
+
+	net_mgmt_init_event_callback(&cb, net_mgmt_event_handler, 0);
+	net_mgmt_add_event_callback(&cb);
+	net_mgmt_init_event_callback(&cb, net_mgmt_event_handler, 0);
+	net_mgmt_add_event_callback(&cb);
+
+	/* Wait for the callbacks to be processed */
+	k_sleep(K_MSEC(1000));
```
[the remark this answers is not in the document]
Comment (krish2718) [reply tests/net/mgmt/src/mgmt.c:444]: I tried 100 and it didn't work (test passed even with the bug), 500 and 1000 work, but just to make sure we catch the bug in all platforms used the highest 1000.

**Review by bjarki-andreasen — DISMISSED** [review]

**Comment by bjarki-trackunit** [comment]
The addition to prevent adding the same callback multiple times is appropriate, and the test suite does catch the bug, but I don't understand why?

This output is very odd to me
```
===================================================================
START - test_mgmt_duplicate_handler
        Throwing event 0xD7AB1234 0 times
 PASS - test_mgmt_duplicate_handler in 1.010 seconds
===================================================================
```
why is the thread throwing an event at all, and why 0 times?

File: tests/net/mgmt/src/mgmt.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (jukkar) [reply tests/net/mgmt/src/mgmt.c:444]: I would prefer that we remove the forced sleep and use a semaphore with a timeout here. The sem would be released in the callback, and if the semaphore timeouts (we need to check the return value), we can fail the test.
Waiting here always one second looks innocent, but these waits add up quickly when there are hundreds of tests that have sleeps in them, so lets try to avoid this here.

**Review by jukkar — CHANGES_REQUESTED** [review]
No issue with the change, but please switch the order of the commits. So first the actual fix, and then the test for it, doing it other way hurts bisectability.

File: tests/net/mgmt/src/mgmt.c [hunk 2]
```diff
@@ -423,4 +423,32 @@ ZTEST(mgmt_fn_test_suite, test_mgmt)
 		      "test_synchronous_event_listener failed");
 }
 
+K_SEM_DEFINE(wait_for_event_processing, 0, 1);
```
Comment (jukkar) [inline tests/net/mgmt/src/mgmt.c:426]: Please use `static K_SEM_DEFINED(...`
Also we could check that the callback is only called once, so I would add here
```
static int cb_call_count;
```

File: tests/net/mgmt/src/mgmt.c [hunk 3]
```diff
@@ -423,4 +423,32 @@ ZTEST(mgmt_fn_test_suite, test_mgmt)
...
+static void net_mgmt_event_handler(struct net_mgmt_event_callback *cb,
+				    uint32_t mgmt_event, struct net_if *iface)
+{
+	ARG_UNUSED(cb);
+	ARG_UNUSED(iface);
+	ARG_UNUSED(mgmt_event);
+
+	k_sem_give(&wait_for_event_processing);
```
Comment (jukkar) [inline tests/net/mgmt/src/mgmt.c:434]: and here
```
cb_call_count++;
```

File: tests/net/mgmt/src/mgmt.c [hunk 4]
```diff
@@ -423,4 +423,32 @@ ZTEST(mgmt_fn_test_suite, test_mgmt)
...
+	int ret;
+
+	net_mgmt_init_event_callback(&cb, net_mgmt_event_handler, 0);
+	net_mgmt_add_event_callback(&cb);
+	net_mgmt_init_event_callback(&cb, net_mgmt_event_handler, 0);
+	net_mgmt_add_event_callback(&cb);
+
+	ret = k_sem_take(&wait_for_event_processing, K_SECONDS(1));
+	zassert_equal(ret, -EAGAIN, "Event is not processed");
+
```
Comment (jukkar) [inline tests/net/mgmt/src/mgmt.c:449]: and then check the count
```
zassert_equal(cb_call_count, 1, "Too many calls to event callback");
```

File: tests/net/mgmt/src/mgmt.c [hunk 5]
```diff
@@ -423,4 +423,32 @@ ZTEST(mgmt_fn_test_suite, test_mgmt)
...
+	/* If we reach here, the test is successful */
+	zassert_true(true, NULL);
```
Comment (jukkar) [inline tests/net/mgmt/src/mgmt.c:451]: This is not needed, we do not need to check that test is ok, but only when it fails.

File: tests/net/mgmt/src/mgmt.c [hunk 6]
```diff
@@ -423,4 +423,32 @@ ZTEST(mgmt_fn_test_suite, test_mgmt)
...
+	struct net_mgmt_event_callback cb;
+	int ret;
+
+	net_mgmt_init_event_callback(&cb, net_mgmt_event_handler, 0);
+	net_mgmt_add_event_callback(&cb);
+	net_mgmt_init_event_callback(&cb, net_mgmt_event_handler, 0);
+	net_mgmt_add_event_callback(&cb);
+
+	ret = k_sem_take(&wait_for_event_processing, K_SECONDS(1));
+	zassert_equal(ret, -EAGAIN, "Event is not processed");
```
Comment (jukkar) [inline tests/net/mgmt/src/mgmt.c:448]: We need to make this properly, we are still waiting one second as the handler is never called. My idea was that we send an event (via system workq with a delay) before taking the semaphore, then wait until the handler releases the semaphore, all this probably takes milliseconds. The call count variable then makes sure that the callback is called exactly once regardless of how many callback handlers we have installed. Installing more than one callback is not possible but we can certainly verify that here.

Comment (krish2718) [reply tests/net/mgmt/src/mgmt.c:448]: We can directly call `net_mgmt_event_notify` as it just queues to the net_mgmt queue instead of system workq?

Comment (jukkar) [reply tests/net/mgmt/src/mgmt.c]: Yes, that should work too. I was worried about the scheduling, but it does not matter here as if the semaphore is released by the handler function before the `k_sem_take`, then we just do not wait there.

**Comment by jukkar** [comment]
We probably need to increase the size of `CONFIG_NET_MGMT_EVENT_STACK_SIZE` as the CI crashes now.

File: tests/net/mgmt/src/mgmt.c (hunk 6 above)
Comment (krish2718) [reply tests/net/mgmt/src/mgmt.c]: But `NET_MGMT_EVENT_THREAD` isn't enabled because of unsatisfied dependencies, there is a Kconfig warning too:

```
warning: NET_MGMT_EVENT_STACK_SIZE (defined at drivers/wifi/esp32/Kconfig.esp32:31,
subsys/net/ip/Kconfig.mgmt:58) was assigned the value '1024' but got the value ''. Check these
unsatisfied dependencies: ((WIFI_ESP32 && WIFI) || (NET_MGMT_EVENT_THREAD && NET_MGMT_EVENT &&
NETWORKING)) (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_NET_MGMT_EVENT_STACK_SIZE and/or look up
NET_MGMT_EVENT_STACK_SIZE in the menuconfig/guiconfig interface. The Application Development Primer,
Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual might be
helpful too.
```

Comment (krish2718) [reply tests/net/mgmt/src/mgmt.c]: Stopping the `thrower_thread` before the 2nd test seemed to work fine.

Comment (krish2718) [reply tests/net/mgmt/src/mgmt.c]: Two fixes:

1. Deleted the event callback in second test - passed net.workqueue
2. Increased the stack size for thrower thread - passed net.synchronouse

**Review by jukkar — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
