### PR TITLE
bluetooth: fix GATT service reregistering

### LINKED ISSUE #67377: Bluetooth: GATT: Unable to re-register GATT service
**Describe the bug**
If try to register a GATT service again after registering another GATT service, `bt_gatt_service_register()` returns `-EINVAL` here: https://github.com/zephyrproject-rtos/zephyr/blob/91841587d6fd3dd5975a595ee819f429487b1ec1/subsys/bluetooth/host/gatt.c#L1222-L1225

**To Reproduce**
1. Register service A using `bt_gatt_service_register()`
2. Unregister service A using `bt_gatt_service_unregister()`
3. Register service B using `bt_gatt_service_register()`
4. Register service A again using `bt_gatt_service_register()`

Example: https://github.com/zephyrproject-rtos/zephyr/commit/bd73ef768388e26150ae39c45040eaebb971ec76

**Expected behavior**
Both services are eventually registered successfully.

**Impact**
The `handle` field of each `bt_gatt_attr` struct needs to be cleared manually which is not mentioned anywhere.
https://github.com/zephyrproject-rtos/zephyr/blob/91841587d6fd3dd5975a595ee819f429487b1ec1/include/zephyr/bluetooth/gatt.h#L177-L178

### PR DESCRIPTION
**Pull request by akredalen**
* Fixed issue with reregistering of a GATT services.
* Added unit tests covering the GATT reregistering scenario.

Fixes #67377

### CODE REVIEW

File: include/zephyr/bluetooth/gatt.h [hunk 1]
```diff
@@ -296,8 +296,13 @@ struct bt_gatt_attr {
 	 *  satisfied before calling read() or write().
 	 *
 	 *  @sa bt_gatt_discover_func_t about this field.
+	 *
+	 *  @note The `_auto` flag in this bitfield indicates if the attribute handle was
+	 *  automatically assigned by the stack (1) or manually set by the application (0).
```
Comment (PavelVPV) [inline include/zephyr/bluetooth/gatt.h:301]:
```suggestion
	 *  automatically assigned by the stack (1) or manually set by the application (0). It must not be modified by the application.
```

File: tests/bluetooth/gatt/src/main.c [hunk 2]
```diff
@@ -142,6 +142,157 @@ ZTEST(test_gatt, test_gatt_unregister)
...
+		BT_GATT_CHARACTERISTIC(&test1_nfy_uuid.uuid, BT_GATT_CHRC_NOTIFY, BT_GATT_PERM_NONE,
+				       NULL, NULL, &nfy_enabled),
+		BT_GATT_CCC(test1_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),
+	};
+	struct bt_gatt_service local_test_svc = BT_GATT_SERVICE(local_test_attrs);
+	struct bt_gatt_service local_test1_svc = BT_GATT_SERVICE(local_test1_attrs);
+
+	for (int i = 0; i < 10; i++) {
+
+		/* Attempt to register service A */
```
Comment (PavelVPV) [inline tests/bluetooth/gatt/src/main.c:169]: (here and below) This comment is the same as the function name. Better to write the test procedure before the test function. Same for the other new tests.

File: tests/bluetooth/gatt/src/main.c [hunk 3]
```diff
@@ -142,6 +142,157 @@ ZTEST(test_gatt, test_gatt_unregister)
...
+		zassert_false(bt_gatt_service_register(&local_test_svc),
+			      "Test service A registration failed");
+
+		/* Attempt to unregister service A */
+		zassert_false(bt_gatt_service_unregister(&local_test_svc),
```
Comment (PavelVPV) [inline tests/bluetooth/gatt/src/main.c:174]: The registration function may at some point be rewritten in such a way that the test still passes, but the handles are not reset. Therefore it is better to check that all handles are zero-ed after unregistering the service. This will guarantee that we get exactly what we want.

File: tests/bluetooth/gatt/src/main.c [hunk 4]
```diff
@@ -142,6 +142,157 @@ ZTEST(test_gatt, test_gatt_unregister)
...
+	for (int j = 0; j < local_test1_svc.attr_count; j++) {
+		local_test1_svc.attrs[j].handle = 0x0200 + j;
+	}
+
+	/* Attempt to register service A */
+	zassert_false(bt_gatt_service_register(&local_test_svc),
+		      "Test service A registration failed");
+
+	/* Attempt to unregister service A */
+	zassert_false(bt_gatt_service_unregister(&local_test_svc),
```
Comment (PavelVPV) [inline tests/bluetooth/gatt/src/main.c:228]: Same comment as above, but here (and below) we should check that the handles are the same after unregistering as they were before registering the service. Otherwise, if it is zero-ed, the service will still be registered, but this won't be what we expect.

File: tests/bluetooth/gatt/src/main.c [hunk 5]
```diff
@@ -142,6 +142,157 @@ ZTEST(test_gatt, test_gatt_unregister)
...
+
+		BT_GATT_CHARACTERISTIC(&test1_nfy_uuid.uuid, BT_GATT_CHRC_NOTIFY, BT_GATT_PERM_NONE,
+				       NULL, NULL, &nfy_enabled),
+		BT_GATT_CCC(test1_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),
+	};
+	struct bt_gatt_service local_test_svc = BT_GATT_SERVICE(local_test_attrs);
+	struct bt_gatt_service local_test1_svc = BT_GATT_SERVICE(local_test1_attrs);
+
+	/* Pre-allocate handles for service A */
+	for (int j = 0; j < local_test_svc.attr_count; j++) {
```
Comment (PavelVPV) [inline tests/bluetooth/gatt/src/main.c:269]: It is better to name both services such that it is clear which one has pre-allocated handles and which one will get handles by the host.

File: tests/bluetooth/gatt/src/main.c [hunk 6]
```diff
@@ -142,6 +142,157 @@ ZTEST(test_gatt, test_gatt_unregister)
...
+		local_test_svc.attrs[j].handle = 0x0100 + j;
+	}
+
+	/* Attempt to register service A */
+	zassert_false(bt_gatt_service_register(&local_test_svc),
+		      "Test service A registration failed");
+
+	/* Attempt to unregister service A */
+	zassert_false(bt_gatt_service_unregister(&local_test_svc),
+		      "Test service A unregister failed");
```
Comment (PavelVPV) [inline tests/bluetooth/gatt/src/main.c:279]: Same as two comments above: check handles after calling `bt_gatt_service_unregister`.

**Review by PavelVPV — COMMENTED** [review]
Please add `Fixes #67377` to the commit message.

**Comment by jhedberg** [comment]
> Please add `Fixes #67377` to the commit message.

That should be in the PR description, not necessarily in the commit message (in fact, references like that in commit messages loose their meaning if the project ever moves to a different location or if someone looks at the commit history in some fork of upstream).

**Comment by PavelVPV** [comment]
> > Please add `Fixes #67377` to the commit message.
> 
> That should be in the PR description, not necessarily in the commit message (in fact, references like that in commit messages loose their meaning if the project ever moves to a different location or if someone looks at the commit history in some fork of upstream).

Ok, I just find it useful to myself at least when going through the git history through `git log`.

**Comment by jhedberg** [comment]
> Ok, I just find it useful to myself at least when going through the git history through `git log`.

Sure, which is why I wasn't trying to outright forbid it. However, GitHub doesn't look at commit messages when it links PRs and issues together, which is why it's important that the reference is at least in the PR description (a contributor might forget to update that if they just modify the commit message and push).

**Comment by PavelVPV** [comment]
> > Ok, I just find it useful to myself at least when going through the git history through `git log`.
> 
> Sure, which is why I wasn't trying to outright forbid it. However, GitHub doesn't look at commit messages when it links PRs and issues together, which is why it's important that the reference is at least in the PR description (a contributor might forget to update that if they just modify the commit message and push).

I see. Usually, when PR has a single commit, it content is put into the description. But yes, you are right, this should be in the PR description for GitHub to match the PR with the issue.

File: tests/bluetooth/gatt/src/main.c (hunk 3 above)
Comment (akredalen) [reply tests/bluetooth/gatt/src/main.c:174]: I removed this check because I thought it was a test of the unregister function, which should probably not be done inside this test. Should I still add the check here or should this be added to the test of the unregister function instead?

Comment (PavelVPV) [reply tests/bluetooth/gatt/src/main.c:174]: Yes, I think it makes sense to check handles here.

File: include/zephyr/bluetooth/gatt.h (hunk 1 above)
Comment (alwa-nordic) [reply include/zephyr/bluetooth/gatt.h:301]: I suggest adding `@internal` and saying it's private.

File: include/zephyr/bluetooth/gatt.h [hunk 7]
```diff
@@ -296,8 +296,13 @@ struct bt_gatt_attr {
...
+	 *
 	 */
-	uint16_t perm;
+	uint16_t perm: 15,
+		_auto: 1;
```
Comment (alwa-nordic) [inline include/zephyr/bluetooth/gatt.h:305]:
```suggestion
	uint16_t perm: 15;
	uint16_t _auto: 1;
```

File: subsys/bluetooth/host/gatt.c [hunk 8]
```diff
@@ -1727,6 +1729,13 @@ static int gatt_unregister(struct bt_gatt_service *svc)
 		if (is_host_managed_ccc(attr)) {
 			gatt_unregister_ccc(attr->user_data);
 		}
+
+		/* The stack should not clear any handles set by the user. */
+		if (attr->_auto) {
+			LOG_DBG("Pre-allocated handle 0x%04x was not clared.", attr->handle);
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:1735]: I think this message does not make sense. I suggest we remove it.

File: subsys/bluetooth/host/gatt.c [hunk 9]
```diff
@@ -1727,6 +1729,13 @@ static int gatt_unregister(struct bt_gatt_service *svc)
 		if (is_host_managed_ccc(attr)) {
 			gatt_unregister_ccc(attr->user_data);
 		}
+
+		/* The stack should not clear any handles set by the user. */
+		if (attr->_auto) {
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/gatt.c:1734]: Maybe we can change the name `_auto` to something more descriptive, so we don't need the comment here?

File: tests/bluetooth/gatt/src/main.c [hunk 10]
```diff
@@ -142,6 +142,157 @@ ZTEST(test_gatt, test_gatt_unregister)
...
+		BT_GATT_PRIMARY_SERVICE(&test1_uuid),
+
+		BT_GATT_CHARACTERISTIC(&test1_nfy_uuid.uuid, BT_GATT_CHRC_NOTIFY, BT_GATT_PERM_NONE,
+				       NULL, NULL, &nfy_enabled),
+		BT_GATT_CCC(test1_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),
+	};
+	struct bt_gatt_service local_test_svc = BT_GATT_SERVICE(local_test_attrs);
+	struct bt_gatt_service local_test1_svc = BT_GATT_SERVICE(local_test1_attrs);
+
+	for (int i = 0; i < 10; i++) {
```
Comment (alwa-nordic) [inline tests/bluetooth/gatt/src/main.c:167]: I think we should leave a clarifying comment here that `10` is an arbitrary choice (if indeed that's the authors intention), and that a single iteration was enough to trigger the original bug.

File: subsys/bluetooth/host/gatt.c (hunk 9 above)
Comment (akredalen) [reply subsys/bluetooth/host/gatt.c:1734]: Suggestions?

Comment (alwa-nordic) [reply subsys/bluetooth/host/gatt.c:1734]: Naming is hard :sweat: Something like the following?

- `managed_handle`
- `dynamic_handle`
- `automatic_handle`
- `stack_issued_handle`
- `auto_assigned_handle`
- `auto_generated_handle`

I like `auto_assigned_handle` best.

File: include/zephyr/bluetooth/gatt.h (hunk 7 above)
Comment (alwa-nordic) [reply include/zephyr/bluetooth/gatt.h:305]: Actually, `_auto` should be `bool _auto`. I edited my previous comment.

File: include/zephyr/bluetooth/gatt.h [hunk 11]
```diff
@@ -296,8 +296,14 @@ struct bt_gatt_attr {
...
 	 *  @sa bt_gatt_discover_func_t about this field.
+	 *
+	 *  @note The `_auto_assigned_handle` flag in this bitfield indicates if the attribute
+	 *  handle was automatically assigned by the stack (1) or manually set by the
+	 *  application (0).
+	 *  This flag must not be modified by the application.
 	 */
-	uint16_t perm;
+	uint16_t perm: 15;
+	uint16_t _auto_assigned_handle: 1;
```
Comment (Thalley) [inline include/zephyr/bluetooth/gatt.h:306]: @jhedberg correct me if I'm wrong, but I think we want to avoid bitfields in the public header? And prefer to use macros to get and set bits instead. 

IIRC the reasoning is that these type of bitfields may not work well with non-arm architectures, but unsure if we actually have that in writing anywhere in Zephyr

File: include/zephyr/bluetooth/gatt.h [hunk 12]
```diff
@@ -296,8 +296,14 @@ struct bt_gatt_attr {
 	 *  satisfied before calling read() or write().
 	 *
 	 *  @sa bt_gatt_discover_func_t about this field.
+	 *
+	 *  @note The `_auto_assigned_handle` flag in this bitfield indicates if the attribute
+	 *  handle was automatically assigned by the stack (1) or manually set by the
+	 *  application (0).
+	 *  This flag must not be modified by the application.
```
Comment (alwa-nordic) [inline include/zephyr/bluetooth/gatt.h:303]: This should be moved to a separate Doxygen comment for `_auto_assigned_handle`, and should include `@internal`.

**Review by alwa-nordic — CHANGES_REQUESTED** [review]

File: include/zephyr/bluetooth/gatt.h (hunk 11 above)
Comment (Thalley) [reply include/zephyr/bluetooth/gatt.h]: Okay. I'm pretty sure I've been asked to not use bitfields in the public header files, even for non-packed structs several times, and mostly for performance reasons since some architectures do not support it. 

Anyways, since we do not (AFAIK) have any coding guidelines on this, it's OK as is :)

File: include/zephyr/bluetooth/gatt.h (hunk 12 above)
Comment (Thalley) [reply include/zephyr/bluetooth/gatt.h:303]: `@internal` cannot be used to hide struct members from documentation. `@cond INTERNAL_HIDDEN` needs to be used for that purpose

File: tests/bluetooth/gatt/src/main.c [hunk 13]
```diff
@@ -142,6 +142,185 @@ ZTEST(test_gatt, test_gatt_unregister)
...
+			      "Test service A registration failed");
+
+		zassert_false(bt_gatt_service_unregister(&local_test_svc),
+			      "Test service A unregister failed");
+
+		/* Check that the handles are the same as before registering the service */
+		for (int j = 0; j < local_test_svc.attr_count; j++) {
+			zassert_equal(local_test_svc.attrs[j].handle, 0x0000,
+				      "Test service A handle not reset");
+		}
```
Comment (Thalley) [inline tests/bluetooth/gatt/src/main.c:186]: Shouldn't this loop exist before the first call to `bt_gatt_service_register(&local_test_svc)` as well? You refer to "before registering the service", but we do no verify that these are 0x0000 before registering the service

File: include/zephyr/bluetooth/gatt.h (hunk 12 above)
Comment (alwa-nordic) [reply include/zephyr/bluetooth/gatt.h]: I played around with this. It seems Doxygen will hide members that being with an underscore. It's the same effect as adding `@private`.

@akredalen, Since this field starts with an underscore, it's already private and there is no need to add anything. Sorry for the confusion.

Comment (Thalley) [reply include/zephyr/bluetooth/gatt.h]: @kartben can you confirm?

Comment (Thalley) [reply include/zephyr/bluetooth/gatt.h]: Seems correct, e.g. https://docs.zephyrproject.org/latest/doxygen/html/structbt__conn__cb.html does not show 

```
	/** @internal Internally used field for list handling */
	sys_snode_t _node;
```

Comment (akredalen) [reply include/zephyr/bluetooth/gatt.h]: So, remove current lines 302 and 311 then? @alwa-nordic All other text is ok as is?

**Review by alwa-nordic — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
