### PR TITLE
usb: hci: Handle Suspend->Resume events properly.

### LINKED ISSUE #28948: hci_usb: ACL transfer not restarted after USB Suspend - Resume
**Describe the bug**
hci_usb sample does not tolerate USB Suspend - Resume cycle. USB transfer for ACL data is not restarted after host has done Suspend - Resume to the device.

From USB debug logs we see that when host does Suspend, Zephyr cancels the pending transfer:
```
[00:00:16.481,414] <dbg> usb_transfer.usb_cancel_transfers: Cancel transfer for ep: 0x01
[00:00:16.481,414] <dbg> usb_bluetooth.bluetooth_status_cb: USB device suspended
[00:00:16.481,445] <dbg> usb_transfer.usb_transfer_work: Transfer cancelled or completed, ep 0x01
[00:00:16.481,475] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x01, status -72, size 0
```

Then on Resume, transfer is not started for ep 0x01:
```
[00:00:34.820,861] <dbg> usb_bluetooth.bluetooth_status_cb: USB device resumed
[00:00:34.934,204] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.934,234] <dbg> usb_device.custom_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.934,265] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_STATUS
[00:00:34.934,356] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:34.934,692] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.934,875] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.934,936] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.934,936] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.934,967] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.935,241] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.936,218] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.936,492] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.936,706] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
...
```

Then when connecting to another device through bluetoothctl, ACL data is dropped because there was no transfer.

`[00:01:48.974,243] <err> usb_transfer: RX data lost, no transfer`

**To Reproduce**
1. cd samples/bluetooth/hci_usb
2. west build -b west build -b nrf52840dk_nrf52840 && west flash
3. Start btmon in one terminal, bluetoothctl in another. Run both as root.
4. on bluetoothctl do:
 * power off (then wait more than 3 seconds)
 * power on
5. then scan and try to connect to any device
6. check btmon capture and see that after ACL Data TX `ATT: Exchange MTU Request` there is no `Number of Completed Packets` event and another device does not respond to the 

**Expected behavior**
I would expect Zephyr hci_usb firmware to tolerate USB suspend - resume. USB suspend - resume is done when doing power off - power on on Bluez.

**Impact**
Showstopper

**Logs and console output**
Full output of USB debug log:
```
*** Booting Zephyr OS build v2.4.0-rc2-361-ged7263bf6b91  **** Booting Zephyr OS build v2.4.0-rc2-361-ged7263bf6b91  ***
Bluetooth over USB sample
[00:00:00.251,464] <dbg> usb_descriptor.usb_get_device_descriptor: __usb_descriptor_start 0x20000654
[00:00:00.251,464] <dbg> usb_descriptor.usb_get_device_descriptor: __usb_descriptor_end 0x200006d3
[00:00:00.251,464] <dbg> usb_descriptor.usb_fix_descriptor: Configuration descriptor 0x20000666
[00:00:00.251,464] <dbg> usb_descriptor.usb_fix_descriptor: Interface descriptor 0x2000066f
[00:00:00.251,464] <dbg> usb_descriptor.usb_fix_descriptor: Endpoint descriptor 0x20000678
[00:00:00.251,495] <dbg> usb_descriptor.usb_validate_ep_cfg_data: Fixing EP address 81 -> 81
[00:00:00.251,495] <dbg> usb_descriptor.usb_validate_ep_cfg_data: endpoint 0x81
[00:00:00.251,495] <dbg> usb_descriptor.usb_fix_descriptor: Endpoint descriptor 0x2000067f
[00:00:00.251,495] <dbg> usb_descriptor.usb_validate_ep_cfg_data: Fixing EP address 2 -> 1
[00:00:00.251,495] <dbg> usb_descriptor.usb_validate_ep_cfg_data: endpoint 0x1
[00:00:00.251,525] <dbg> usb_descriptor.usb_fix_descriptor: Endpoint descriptor 0x20000686
[00:00:00.251,525] <dbg> usb_descriptor.usb_validate_ep_cfg_data: Fixing EP address 82 -> 82
[00:00:00.251,525] <dbg> usb_descriptor.usb_validate_ep_cfg_data: endpoint 0x82
[00:00:00.251,525] <dbg> usb_descriptor.usb_fix_descriptor: Now the wTotalLength is 39
[00:00:00.251,556] <dbg> usb_descriptor.ascii7_to_utf16le: idx_max 11, ascii_idx_max 5, buf 0x20000693
[00:00:00.251,556] <dbg> usb_descriptor.ascii7_to_utf16le: char R : 52, idx 5 -> 11
[00:00:00.251,556] <dbg> usb_descriptor.ascii7_to_utf16le: char Y : 59, idx 4 -> 9
[00:00:00.251,556] <dbg> usb_descriptor.ascii7_to_utf16le: char H : 48, idx 3 -> 7
[00:00:00.251,586] <dbg> usb_descriptor.ascii7_to_utf16le: char P : 50, idx 2 -> 5
[00:00:00.251,586] <dbg> usb_descriptor.ascii7_to_utf16le: char E : 45, idx 1 -> 3
[00:00:00.251,586] <dbg> usb_descriptor.ascii7_to_utf16le: char Z : 5a, idx 0 -> 1
[00:00:00.251,617] <dbg> usb_descriptor.ascii7_to_utf16le: idx_max 13, ascii_idx_max 6, buf 0x200006a1
[00:00:00.251,617] <dbg> usb_descriptor.ascii7_to_utf16le: char V : 56, idx 6 -> 13
[00:00:00.251,617] <dbg> usb_descriptor.ascii7_to_utf16le: char E : 45, idx 5 -> 11
[00:00:00.251,647] <dbg> usb_descriptor.ascii7_to_utf16le: char D : 44, idx 4 -> 9
[00:00:00.251,647] <dbg> usb_descriptor.ascii7_to_utf16le: char - : 2d, idx 3 -> 7
[00:00:00.251,647] <dbg> usb_descriptor.ascii7_to_utf16le: char B : 42, idx 2 -> 5
[00:00:00.251,678] <dbg> usb_descriptor.ascii7_to_utf16le: char S : 53, idx 1 -> 3
[00:00:00.251,678] <dbg> usb_descriptor.ascii7_to_utf16le: char U : 55, idx 0 -> 1
[00:00:00.251,678] <dbg> usb_descriptor: Serial Number
e1 9d cc 07 f1 ec 02 0a                          |........         
[00:00:00.251,708] <dbg> usb_descriptor.ascii7_to_utf16le: idx_max 31, ascii_idx_max 15, buf 0x200006b1
[00:00:00.251,708] <dbg> usb_descriptor.ascii7_to_utf16le: char A : 41, idx 15 -> 31
[00:00:00.251,739] <dbg> usb_descriptor.ascii7_to_utf16le: char 0 : 30, idx 14 -> 29
[00:00:00.251,739] <dbg> usb_descriptor.ascii7_to_utf16le: char 2 : 32, idx 13 -> 27
[00:00:00.251,739] <dbg> usb_descriptor.ascii7_to_utf16le: char 0 : 30, idx 12 -> 25
[00:00:00.251,770] <dbg> usb_descriptor.ascii7_to_utf16le: char C : 43, idx 11 -> 23
[00:00:00.251,770] <dbg> usb_descriptor.ascii7_to_utf16le: char E : 45, idx 10 -> 21
[00:00:00.251,770] <dbg> usb_descriptor.ascii7_to_utf16le: char 1 : 31, idx 9 -> 19
[00:00:00.251,770] <dbg> usb_descriptor.ascii7_to_utf16le: char F : 46, idx 8 -> 17
[00:00:00.251,800] <dbg> usb_descriptor.ascii7_to_utf16le: char 7 : 37, idx 7 -> 15
[00:00:00.251,800] <dbg> usb_descriptor.ascii7_to_utf16le: char 0 : 30, idx 6 -> 13
[00:00:00.251,800] <dbg> usb_descriptor.ascii7_to_utf16le: char C : 43, idx 5 -> 11
[00:00:00.251,831] <dbg> usb_descriptor.ascii7_to_utf16le: char C : 43, idx 4 -> 9
[00:00:00.251,831] <dbg> usb_descriptor.ascii7_to_utf16le: char D : 44, idx 3 -> 7
[00:00:00.251,831] <dbg> usb_descriptor.ascii7_to_utf16le: char 9 : 39, idx 2 -> 5
[00:00:00.251,861] <dbg> usb_descriptor.ascii7_to_utf16le: char 1 : 31, idx 1 -> 3
[00:00:00.251,861] <dbg> usb_descriptor.ascii7_to_utf16le: char E : 45, idx 0 -> 1
[00:00:00.257,263] <dbg> usb_bluetooth.bluetooth_init: Initialization
[00:00:00.257,446] <inf> bt_hci_raw: Bluetooth enabled in RAW mode
[00:00:00.257,476] <dbg> usb_bluetooth.hci_tx_thread: Start USB Bluetooth thread
[00:00:00.257,507] <dbg> usb_device.usb_enable: lock usb_enable_lock mutex
[00:00:00.257,995] <dbg> usb_device.composite_setup_ep_cb: set cb, ep: 0x81
[00:00:00.257,995] <dbg> usb_device.composite_setup_ep_cb: set cb, ep: 0x1
[00:00:00.257,995] <dbg> usb_device.composite_setup_ep_cb: set cb, ep: 0x82
[00:00:00.257,995] <dbg> usb_device.usb_enable: unlock usb_enable_lock mutex
[00:00:00.258,911] <dbg> usb_bluetooth.bluetooth_status_cb: USB device connected
[00:00:00.262,054] <dbg> usb_bluetooth.bluetooth_status_cb: USB device suspended
[00:00:00.401,153] <dbg> usb_bluetooth.bluetooth_status_cb: USB device resumed
[00:00:00.401,184] <dbg> usb_bluetooth.bluetooth_status_cb: USB device reset detected
[00:00:00.528,808] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.528,839] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0000
[00:00:00.528,839] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.528,961] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:00.529,083] <dbg> usb_bluetooth.bluetooth_status_cb: USB device reset detected
[00:00:00.676,727] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.676,757] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0000
[00:00:00.676,757] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.676,879] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:00.677,124] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.677,154] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0000
[00:00:00.677,154] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.677,154] <dbg> usb_device.usb_get_descriptor: Desc 600 not found!
[00:00:00.677,154] <dbg> usb_device.usb_handle_request: Handler Error 0
[00:00:00.677,185] <dbg> usb_device.usb_print_setup: Setup: bmRT 0x80, bR 0x06, wV 0x0600, wI 0x0000, wL 0x000a
[00:00:00.677,185] <dbg> usb_device.usb_handle_control_transfer: usb_handle_request failed
[00:00:00.677,490] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.677,520] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0000
[00:00:00.677,520] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.677,520] <dbg> usb_device.usb_get_descriptor: Desc 600 not found!
[00:00:00.677,520] <dbg> usb_device.usb_handle_request: Handler Error 0
[00:00:00.677,551] <dbg> usb_device.usb_print_setup: Setup: bmRT 0x80, bR 0x06, wV 0x0600, wI 0x0000, wL 0x000a
[00:00:00.677,551] <dbg> usb_device.usb_handle_control_transfer: usb_handle_request failed
[00:00:00.677,764] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.677,795] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0000
[00:00:00.677,795] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.677,795] <dbg> usb_device.usb_get_descriptor: Desc 600 not found!
[00:00:00.677,795] <dbg> usb_device.usb_handle_request: Handler Error 0
[00:00:00.677,825] <dbg> usb_device.usb_print_setup: Setup: bmRT 0x80, bR 0x06, wV 0x0600, wI 0x0000, wL 0x000a
[00:00:00.677,825] <dbg> usb_device.usb_handle_control_transfer: usb_handle_request failed
[00:00:00.678,039] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.678,070] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0000
[00:00:00.678,070] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.678,192] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:00.678,436] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.678,497] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0000
[00:00:00.678,497] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.678,649] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:00.678,924] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.678,955] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0000
[00:00:00.678,955] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.679,077] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:00.679,199] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.679,229] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0409
[00:00:00.679,260] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.679,351] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:00.679,565] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.679,626] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0409
[00:00:00.679,626] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.679,718] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:00.679,931] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.679,962] <dbg> usb_device.custom_handler: bRequest 0x06, wIndex 0x0409
[00:00:00.679,992] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_DESCRIPTOR
[00:00:00.680,114] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:00.681,671] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.681,701] <dbg> usb_device.custom_handler: bRequest 0x09, wIndex 0x0000
[00:00:00.681,701] <dbg> usb_device.usb_handle_std_device_req: REQ_SET_CONFIGURATION, conf 0x1
[00:00:00.681,701] <dbg> usb_device.set_endpoint: Set endpoint 0x81 type 3 MPS 64
[00:00:00.681,732] <dbg> usb_device.set_endpoint: Set endpoint 0x1 type 2 MPS 32
[00:00:00.681,762] <dbg> usb_device.set_endpoint: Set endpoint 0x82 type 2 MPS 32
[00:00:00.681,762] <dbg> usb_bluetooth.bluetooth_status_cb: USB device configured
[00:00:00.681,762] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x01, data 0x20003df7, dlen 32
[00:00:00.682,373] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.682,586] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.682,617] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.682,617] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.682,647] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.682,922] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.683,441] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.683,624] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.683,807] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.683,837] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.683,868] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.683,868] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.683,959] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.684,448] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.684,570] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.684,753] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.684,783] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.684,814] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.684,814] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.684,906] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.685,455] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.685,546] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.685,729] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.685,760] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.685,791] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.685,791] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.685,882] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 12
[00:00:00.686,462] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 12
[00:00:00.686,645] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.686,859] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.686,889] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.686,889] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.686,920] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.687,011] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 9
[00:00:00.687,438] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 9
[00:00:00.687,591] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.687,774] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.687,805] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.687,805] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.687,835] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.687,927] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.688,446] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.688,598] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.688,781] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.688,812] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.688,842] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.688,842] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.688,934] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.689,453] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.689,636] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.689,819] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.689,849] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.689,849] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.689,880] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.689,971] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 70
[00:00:00.691,467] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 70
[00:00:00.691,558] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.691,711] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.691,772] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.691,772] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:00.691,772] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.691,894] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.692,443] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.692,565] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.692,718] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.692,749] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.692,749] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:00.692,779] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.692,871] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.693,450] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.693,511] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.693,695] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.693,756] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.693,756] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.693,756] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.693,878] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:00.694,458] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:00.694,549] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.694,732] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.694,763] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.694,763] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.694,793] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.694,885] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:00.695,465] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:00.695,526] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.695,709] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.695,770] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.695,770] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.695,770] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.695,892] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.696,441] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.696,563] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.696,716] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.696,746] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.696,746] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.696,777] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.696,868] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:00.697,448] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:00.697,601] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.697,784] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.697,814] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.697,814] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.697,845] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.697,937] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.698,455] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.698,547] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.698,730] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.698,791] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.698,791] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.698,791] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.698,913] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.699,462] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.699,584] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.699,768] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.699,829] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.699,829] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.699,859] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.699,951] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 10
[00:00:00.700,439] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 10
[00:00:00.700,653] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.700,836] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.700,866] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.700,866] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:00.700,897] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.700,988] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.701,446] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.701,599] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.701,782] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.701,812] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.701,812] <dbg> usb_bluetooth.bluetooth_class_handler: len 7
[00:00:00.701,843] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.701,934] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.702,453] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.702,575] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.702,789] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.702,819] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.702,819] <dbg> usb_bluetooth.bluetooth_class_handler: len 6
[00:00:00.702,850] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.702,941] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.703,460] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.707,794] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.707,977] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.708,007] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.708,007] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.708,038] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.708,312] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.709,442] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.709,594] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.709,777] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.709,808] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.709,808] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.709,838] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.709,930] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.710,449] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.710,540] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.710,754] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.710,784] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.710,784] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.710,815] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.710,906] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.711,456] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.711,547] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.711,730] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.711,791] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.711,791] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.711,822] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.711,914] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 12
[00:00:00.712,463] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 12
[00:00:00.712,585] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.712,799] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.712,829] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.712,829] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.712,860] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.712,951] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 9
[00:00:00.713,439] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 9
[00:00:00.713,562] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.713,745] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.713,775] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.713,775] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.713,806] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.713,897] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.714,447] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.714,569] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.714,721] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.714,752] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.714,782] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.714,782] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.714,874] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.715,454] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.715,515] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.715,698] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.715,759] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.715,759] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.715,759] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.715,881] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 70
[00:00:00.717,468] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 70
[00:00:00.717,590] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.717,803] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.717,834] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.717,834] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:00.717,864] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.717,956] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.718,444] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.718,536] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.718,719] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.718,750] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.718,750] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:00.718,780] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.718,872] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.719,451] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.719,512] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.719,696] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.719,726] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.719,757] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.719,757] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.719,848] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:00.720,458] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:00.720,520] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.720,733] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.720,764] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.720,764] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.720,794] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.720,886] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:00.721,466] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:00.721,557] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.721,740] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.721,771] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.721,771] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.721,801] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.721,893] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.722,442] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.722,564] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.722,717] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.722,747] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.722,778] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.722,778] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.722,869] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:00.723,449] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:00.723,510] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.723,693] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.723,754] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.723,754] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.723,785] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.723,876] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.724,456] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.724,517] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.724,700] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.724,731] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.724,761] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.724,761] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.724,853] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:00.725,463] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:00.725,524] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.725,738] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.725,769] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.725,769] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:00.725,799] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.725,891] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 10
[00:00:00.726,440] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 10
[00:00:00.726,562] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.726,745] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.726,776] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.726,806] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:00.726,806] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.726,898] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.727,447] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.727,508] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.727,722] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.727,752] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.727,752] <dbg> usb_bluetooth.bluetooth_class_handler: len 7
[00:00:00.727,783] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.727,874] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.728,454] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.728,546] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.728,729] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.728,759] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.728,759] <dbg> usb_bluetooth.bluetooth_class_handler: len 6
[00:00:00.728,790] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.728,881] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.729,461] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:00.729,614] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:00.729,827] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:00.729,858] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:00.729,858] <dbg> usb_bluetooth.bluetooth_class_handler: len 35
[00:00:00.729,888] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:00.729,980] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:00.730,468] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:16.481,414] <dbg> usb_transfer.usb_cancel_transfers: Cancel transfer for ep: 0x01
[00:00:16.481,414] <dbg> usb_bluetooth.bluetooth_status_cb: USB device suspended
[00:00:16.481,445] <dbg> usb_transfer.usb_transfer_work: Transfer cancelled or completed, ep 0x01
[00:00:16.481,475] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x01, status -72, size 0
[00:00:34.820,861] <dbg> usb_bluetooth.bluetooth_status_cb: USB device resumed
[00:00:34.934,204] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.934,234] <dbg> usb_device.custom_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.934,265] <dbg> usb_device.usb_handle_std_device_req: REQ_GET_STATUS
[00:00:34.934,356] <dbg> usb_device.usb_handle_control_transfer: ep 0x80, status 0x02
[00:00:34.934,692] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.934,875] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.934,936] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.934,936] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.934,967] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.935,241] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.936,218] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.936,492] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.936,706] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.936,737] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.936,737] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.936,767] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.936,859] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:34.937,225] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:34.937,500] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.937,683] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.937,713] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.937,713] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.937,744] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.937,835] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:34.938,201] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:34.938,385] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.938,568] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.938,629] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.938,629] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.938,629] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.938,751] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 12
[00:00:34.939,208] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 12
[00:00:34.939,422] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.939,605] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.939,636] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.939,666] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.939,666] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.939,758] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 9
[00:00:34.940,216] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 9
[00:00:34.940,460] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.940,673] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.940,704] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.940,704] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.940,734] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.940,826] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:34.941,223] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:34.941,467] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.941,650] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.941,711] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.941,711] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.941,711] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.941,833] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:34.942,199] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:34.942,413] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.942,596] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.942,626] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.942,626] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.942,657] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.942,749] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 70
[00:00:34.944,213] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 70
[00:00:34.944,366] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.944,519] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.944,549] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.944,580] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:34.944,580] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.944,671] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.945,220] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.945,312] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.945,495] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.945,556] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.945,556] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:34.945,587] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.945,678] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.946,197] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.946,319] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.946,502] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.946,533] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.946,563] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.946,563] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.946,655] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:34.947,204] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:34.947,326] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.947,509] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.947,540] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.947,540] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.947,570] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.947,662] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:34.948,211] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:34.948,333] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.948,516] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.948,547] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.948,547] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.948,577] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.948,669] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.949,218] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.949,340] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.949,523] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.949,554] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.949,554] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.949,584] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.949,676] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 7
[00:00:34.950,195] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 7
[00:00:34.950,653] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.950,836] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.950,866] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.950,866] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.950,897] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.950,988] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.951,202] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.951,293] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.951,477] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.951,507] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.951,507] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.951,538] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.951,629] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:00:34.952,209] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:00:34.952,362] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.952,575] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.952,606] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.952,606] <dbg> usb_bluetooth.bluetooth_class_handler: len 3
[00:00:34.952,636] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.952,728] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 10
[00:00:34.953,216] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 10
[00:00:34.953,399] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.953,613] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.953,643] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.953,643] <dbg> usb_bluetooth.bluetooth_class_handler: len 11
[00:00:34.953,674] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.953,765] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.954,223] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.954,376] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.954,589] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.954,620] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.954,620] <dbg> usb_bluetooth.bluetooth_class_handler: len 7
[00:00:34.954,650] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.954,742] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.955,200] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.955,352] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.955,566] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.955,596] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.955,596] <dbg> usb_bluetooth.bluetooth_class_handler: len 6
[00:00:34.955,627] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.955,718] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.956,207] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.956,481] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.956,695] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.956,726] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.956,726] <dbg> usb_bluetooth.bluetooth_class_handler: len 35
[00:00:34.956,756] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.956,848] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.957,214] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:00:34.957,397] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:00:34.957,611] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:00:34.957,641] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:00:34.957,641] <dbg> usb_bluetooth.bluetooth_class_handler: len 35
[00:00:34.957,672] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:00:34.957,763] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:00:34.958,221] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.561,706] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:01:48.561,889] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:01:48.561,920] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:01:48.561,950] <dbg> usb_bluetooth.bluetooth_class_handler: len 9
[00:01:48.561,950] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:01:48.562,042] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:01:48.562,683] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.562,988] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:01:48.563,201] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:01:48.563,232] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:01:48.563,232] <dbg> usb_bluetooth.bluetooth_class_handler: len 10
[00:01:48.563,262] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:01:48.563,354] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:01:48.563,690] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.563,873] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:01:48.564,086] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:01:48.564,117] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:01:48.564,117] <dbg> usb_bluetooth.bluetooth_class_handler: len 10
[00:01:48.564,147] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:01:48.564,239] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:01:48.564,697] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.564,849] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:01:48.565,032] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:01:48.565,063] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:01:48.565,063] <dbg> usb_bluetooth.bluetooth_class_handler: len 5
[00:01:48.565,093] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:01:48.565,277] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:01:48.565,673] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.696,136] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 37
[00:01:48.696,716] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 37
[00:01:48.697,113] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:01:48.697,296] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:01:48.697,326] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:01:48.697,357] <dbg> usb_bluetooth.bluetooth_class_handler: len 5
[00:01:48.697,357] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:01:48.697,570] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:01:48.698,699] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.698,883] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:01:48.699,096] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:01:48.699,127] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:01:48.699,127] <dbg> usb_bluetooth.bluetooth_class_handler: len 28
[00:01:48.699,157] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:01:48.699,554] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:01:48.700,683] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.870,574] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 21
[00:01:48.871,704] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 21
[00:01:48.871,734] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f60e, dlen 6
[00:01:48.872,192] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:01:48.872,436] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:01:48.872,467] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:01:48.872,467] <dbg> usb_bluetooth.bluetooth_class_handler: len 5
[00:01:48.872,497] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:01:48.872,680] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.872,741] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:01:48.873,687] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:48.972,534] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 14
[00:01:48.972,717] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 14
[00:01:48.974,243] <err> usb_transfer: RX data lost, no transfer
[00:01:49.972,625] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x82, data 0x2000f5c1, dlen 20
[00:01:49.972,808] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x82, status 0, size 20
[00:01:49.973,236] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:01:49.973,419] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:01:49.973,449] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:01:49.973,449] <dbg> usb_bluetooth.bluetooth_class_handler: len 17
[00:01:49.973,480] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:01:49.973,571] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:01:49.974,670] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:01:50.320,404] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 12
[00:01:50.320,678] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 12
[00:02:20.982,696] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x00
[00:02:20.982,879] <dbg> usb_device.usb_handle_control_transfer: ep 0x00, status 0x01
[00:02:20.982,910] <dbg> usb_device.class_handler: bRequest 0x00, wIndex 0x0000
[00:02:20.982,910] <dbg> usb_bluetooth.bluetooth_class_handler: len 6
[00:02:20.982,940] <dbg> usb_device.usb_handle_control_transfer: >> usb_data_to_host(2)
[00:02:20.983,032] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:02:20.983,459] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6
[00:02:21.008,972] <dbg> usb_transfer.usb_transfer: Transfer start, ep 0x81, data 0x2000f5c1, dlen 6
[00:02:21.009,460] <dbg> usb_transfer.usb_transfer_work: Transfer done, ep 0x81, status 0, size 6                                                                    
```

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 20.04, kernel 5.4.0-48-generic
 - Toolchain Zephyr SDK
 - Commit SHA or Version used: Zephyr master ed7263bf6b91d4542573d2f44ed742a2acf542df. Also 2.2.1 is affected.

**Additional context**

See https://github.com/zephyrproject-rtos/zephyr/pull/28569 for proposed fix and discussion around it. The fix has been tested to work fine with Zephyr master.

### PR DESCRIPTION
**Pull request by eobalski**
USB bus might be suspended to save power. After the device
is Resumed from Suspended state there is a need to restart
OUT transfers for Endpoints used by HCI class. The transfers
shall be restarted only if the device was Resumed after Suspend
from Configured state. This patch applies the fix.

Fixes #28948

Reference: #26725

### CODE REVIEW

**Review by jfischer-no — APPROVED** [review]

File: subsys/usb/class/bluetooth.c [hunk 1]
```diff
@@ -204,38 +208,50 @@ static void bluetooth_status_cb(struct usb_cfg_data *cfg,
...
-		LOG_DBG("USB device configured");
-		/* Start reading */
-		acl_read_cb(bluetooth_ep_data[HCI_OUT_EP_IDX].ep_addr, 0, NULL);
+		LOG_DBG("Device configured");
+		if (!configured) {
+			/* Start reading */
+			acl_read_cb(bluetooth_ep_data[HCI_OUT_EP_IDX].ep_addr,
+				    0, NULL);
+		}
+		configured = true;
```
Comment (anangl) [inline subsys/usb/class/bluetooth.c:223]:
```suggestion
		if (!configured) {
			configured = true;
			/* Start reading */
			acl_read_cb(bluetooth_ep_data[HCI_OUT_EP_IDX].ep_addr,
				    0, NULL);
		}
```

**Review by anangl — APPROVED** [review]
