### PR TITLE
tests: drivers: counter: Fix coverity issues

### LINKED ISSUE #13839: [Coverity CID :190983]Incorrect expression in /tests/drivers/counter/counter_basic_api/src/test_counter.c
Static code scan issues seen in File: /tests/drivers/counter/counter_basic_api/src/test_counter.c
 Category: Incorrect expression
 Function: test_multiple_alarms_instance
 Component: Tests
 CID: 190983
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #13851: [Coverity CID :190967]Incorrect expression in /tests/drivers/counter/counter_basic_api/src/test_counter.c
Static code scan issues seen in File: /tests/drivers/counter/counter_basic_api/src/test_counter.c
 Category: Incorrect expression
 Function: test_single_shot_alarm_instance
 Component: Tests
 CID: 190967
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #13863: [Coverity CID :190952]Incorrect expression in /tests/drivers/counter/counter_basic_api/src/test_counter.c
Static code scan issues seen in File: /tests/drivers/counter/counter_basic_api/src/test_counter.c
 Category: Incorrect expression
 Function: test_set_top_value_with_alarm_instance
 Component: Tests
 CID: 190952
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### LINKED ISSUE #13876: [Coverity CID :190937]Incorrect expression in /tests/drivers/counter/counter_basic_api/src/test_counter.c
Static code scan issues seen in File: /tests/drivers/counter/counter_basic_api/src/test_counter.c
 Category: Incorrect expression
 Function: test_all_channels_instance
 Component: Tests
 CID: 190937
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

### PR DESCRIPTION
**Pull request by nordic-krch**
Apparently, casting was not enough for coverity. Adding temporary variable.

Issues 190937, 190952, 190967, 190983

Fixes #13876 
Fixes #13863 
Fixes #13851 
Fixes #13839 

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 1]
```diff
@@ -121,6 +121,7 @@ void test_set_top_value_with_alarm_instance(const char *dev_name)
 	int err;
 	u32_t cnt;
 	u32_t ticks;
+	u32_t tmp;
```
Comment (galak) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: can you rename tmp to tmp_top_cnt or something like that?

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 2]
```diff
@@ -168,6 +170,7 @@ void test_single_shot_alarm_instance(const char *dev_name, bool set_top)
 	struct device *dev;
 	int err;
 	u32_t ticks;
+	u32_t tmp;
```
Comment (galak) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: can you rename to tmp_alarm_cnt.

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 3]
```diff
@@ -266,6 +271,7 @@ void test_multiple_alarms_instance(const char *dev_name)
...
```
Comment (galak) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: rename to tmp_alarm_cnt.

File: tests/drivers/counter/counter_basic_api/src/test_counter.c [hunk 4]
```diff
@@ -330,6 +337,7 @@ void test_all_channels_instance(const char *str)
 	bool limit_reached = false;
 	struct counter_alarm_cfg alarm_cfgs;
 	u32_t ticks;
+	u32_t tmp;
```
Comment (galak) [inline tests/drivers/counter/counter_basic_api/src/test_counter.c]: rename to tmp_alarm_cnt

**Review by galak — CHANGES_REQUESTED** [review]
Rename tmp variables to be a bit more clear.

**Comment by nordic-krch** [comment]
@galak 
>Rename tmp variables to be a bit more clear.

done

**Review by galak — APPROVED** [review]
