### PR TITLE
drivers: wifi: esp_at: fix UDP socket setup

### LINKED ISSUE #75588: drivers: wifi: esp_at: outgoing UDP packets always use the same local port
**Describe the bug**
Outgoing UDP packets always use the same local port. Local UDP port number is currently hardcoded to be always the same as remote UDP port number.

As an example, when querying DNS server all the requests are sent to port `53` (default port for DNS over UDP). For all such requests `53` local port is used. This is against recommendations and is potentially a security issue. Instead, a random local UDP port should be chosen, to which DNS server will reply.

Another example is initiating DTLS connection (e.g. to Golioth service or some LwM2M server). This time during DTLS session initiation always the same UDP port will be used. Most servers will ignore any new subsequent DTLS session handshakes (besides the first one), since there are previous "active" DTLS sessions that are still maintained by server (and those need to timeout). The reason is that DTLS sessions are differentiated on the server side by "IP:PORT" pair, which is static (and it should not be).

**To Reproduce**
1. Build application with UDP / DTLS networking using ESP-AT as WiFi modem
2. Connect once
3. Disconnect
4. Next connect attempt fails due to same port reuse

**Expected behavior**
ESP-AT driver should not use the same local (outgoing) UDP port number as the one server is listening to.

**Impact**
Regression and showstopper on using UDP communication with Zephyr 3.7.0.

**Environment**
 - Commit SHA or Version used: `3.7.0-rc2`

### PR DESCRIPTION
**Pull request by mniestroj**
Right now `AT+CIPSTART` command is called with both "remote port" and "local port" being set to the same number. This means that for outgoing UDP traffic (e.g. when resolving DNS or when reaching out some application server with CoAP over UDP) always the same outgoing port is used. Such behavior is wrong, since by default a random outgoing port should be used.

Reusing the same port confuses server implementation that is reached out, since especially in context of DTLS over UDP, outgoing port defines TLS context/session to be used. Such servers often ignore TLS packets from new sessions (e.g. after device reboot) and result in failed DTLS connection attempts.

Commit dbf3d6e9110a ("drivers: esp_at: implement bind() and recvfrom() for UDP sockets") added support for "server-side listening" for incoming traffic on UDP sockets, which introduced broken behavior of using the same remote and local port.

In `esp_bind()` implementation assign newly intorduced `src` member, instead of reusing `dst`. Don't call `AT+CIPSTART` yet at this stage, as in case of connect() Zephyr syscall `esp_bind()` (via `bind_default()` helper function) is called implicitly to assign random generated local port, so remote port is yet to be assigned. Check in `esp_recv()` whether socket was already connected (i.e. esp_connect() was called) and if not, invoke `AT+CIPSTART` (via `_sock_connect()`) to start listening on "server-side" UDP socket.

This patch fixes broken behavior of always reusing the same local port for outgoing UDP traffic. Instead, randomly generated (by Zephyr net_context subsys) local port is used. Additionally `bind()` and `recvfrom()` implementation (to handle server-side UDP sockets) is improved, so that binding to `0.0.0.0` (on any interface) is possible.

Fixes: dbf3d6e9110a ("drivers: esp_at: implement bind() and recvfrom() for
  UDP sockets")
Fixes: 424ea9f5e42c ("drivers: wifi: esp_at: do not connect socket on
  bind(INADDR_ANY)")

FIxes: #75588

### CODE REVIEW

File: drivers/wifi/esp_at/esp_offload.c [hunk 1]
```diff
@@ -27,9 +27,13 @@ static int esp_listen(struct net_context *context, int backlog)
 
 static int _sock_connect(struct esp_data *dev, struct esp_socket *sock)
 {
-	char connect_msg[sizeof("AT+CIPSTART=000,\"TCP\",\"\",65535,7200") +
-			 NET_IPV4_ADDR_LEN];
-	char addr_str[NET_IPV4_ADDR_LEN];
+	char connect_msg[MAX(sizeof("AT+CIPSTART=000,\"TCP\",\"\",65535,7200") +
```
Comment (jukkar) [inline drivers/wifi/esp_at/esp_offload.c:30]: Why do we need to use MAX() here? Isn't the latter parameter always larger?

Comment (mniestroj) [reply drivers/wifi/esp_at/esp_offload.c:30]: Second parameter is larger, indeed. I just tried to make it explicit how we calculate length. I can leave just the second statement and get rid of MAX() if you prefer that.

Comment (jukkar) [reply drivers/wifi/esp_at/esp_offload.c:30]: No need to remove it if you did it on purpose, but perhaps a comment would help here to explain why the code looks like that.

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by jukkar** [comment]
@mniestroj should this go to 3.7 or can it wait 4.0?

**Comment by mniestroj** [comment]
@jukkar IMO this should go into 3.7. This fixes a regression introduced after 3.6 (dbf3d6e9110a396c56a00fc2e4b0acf615415503) and makes UDP client side communication (which was working in the driver for very long time) buggy and not behaving according to UDP/IP standards. The only alternative I see is reverting regression commit.
