### PR TITLE
Fixes for missing/bad bt_conn_ref and disconnect cleanups

### LINKED ISSUE #42680: Missing bt_conn_(un)ref for LE Audio and tests
**Describe the bug**
There's several places where LE Audio do not properly take a reference to a `bt_conn` ref when storing the pointer, both in the stack in the babblesim tests. 

**To Reproduce**
N/A

**Expected behavior**
When storing the pointer for later usage, `bt_conn_ref()` should be called, and likewise on disconnect `bt_conn_unref()` should be called and the stored pointer cleared. 

**Impact**
No issues found so far, but possible that this will cause issues. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 41a63f48fdc81636b1ed875c574d27aaf0b09bc9

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
For LE Audio there was some missing handling of bt_conn_ref as well as missing cleanup. 

For BSIM tests the connection pointer was not handled uniformly. 

There were also a few samples that had bad handling of bt_conn_ref. 

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/42680

### CODE REVIEW

File: tests/bluetooth/bsim_bt/bsim_test_audio/src/mcc_test.c [hunk 1]
```diff
@@ -570,11 +569,12 @@ static void connected(struct bt_conn *conn, uint8_t err)
 	bt_addr_le_to_str(bt_conn_get_dst(conn), addr, sizeof(addr));
 
 	if (err) {
+		bt_conn_unref(conn);
+		default_conn = NULL;
```
Comment (jhedberg) [inline tests/bluetooth/bsim_bt/bsim_test_audio/src/mcc_test.c:573]: It might be more appropriate to do `bt_conn_unref(default_conn)` since if I understand correctly that's the reference that you want to unref (and the assumption is that `conn == default_conn`).

File: tests/bluetooth/bsim_bt/bsim_test_audio/src/mics_client_test.c [hunk 2]
```diff
@@ -202,12 +201,13 @@ static void connected(struct bt_conn *conn, uint8_t err)
 	bt_addr_le_to_str(bt_conn_get_dst(conn), addr, sizeof(addr));
 
 	if (err != 0) {
+		bt_conn_unref(conn);
+		default_conn = NULL;
```
Comment (jhedberg) [inline tests/bluetooth/bsim_bt/bsim_test_audio/src/mics_client_test.c:205]: same here

File: tests/bluetooth/bsim_bt/bsim_test_audio/src/unicast_client_test.c [hunk 3]
```diff
@@ -174,15 +173,14 @@ static void connected(struct bt_conn *conn, uint8_t err)
 
 	if (err != 0) {
 		bt_conn_unref(conn);
```
Comment (jhedberg) [inline tests/bluetooth/bsim_bt/bsim_test_audio/src/unicast_client_test.c:175]: and here

File: tests/bluetooth/bsim_bt/bsim_test_audio/src/vcs_client_test.c [hunk 4]
```diff
@@ -276,11 +275,12 @@ static void connected(struct bt_conn *conn, uint8_t err)
 	bt_addr_le_to_str(bt_conn_get_dst(conn), addr, sizeof(addr));
 
 	if (err) {
+		bt_conn_unref(conn);
```
Comment (jhedberg) [inline tests/bluetooth/bsim_bt/bsim_test_audio/src/vcs_client_test.c:278]: and here

**Review by jhedberg — CHANGES_REQUESTED** [review]
Generally looks good, but it would be good to fix the pattern to always be:
```c
bt_conn_unref(x);
x = NULL;
```
since right now you have in some places:
```c
bt_conn_unref(x);
y = NULL;
```

**Review by jhedberg — DISMISSED** [review]

File: tests/bluetooth/bsim_bt/bsim_test_audio/src/unicast_client_test.c [hunk 5]
```diff
@@ -173,16 +172,15 @@ static void connected(struct bt_conn *conn, uint8_t err)
...
+		default_conn = NULL;
 
 		FAIL("Failed to connect to %s (%u)\n", addr, err);
 		return;
 	}
 
 	printk("Connected to %s\n", addr);
-	g_conn = conn;
-	SET_FLAG(flag_connected);
+	SET_FLAG(fladefault_connected);
```
Comment (Casper-Bonde-Bose) [inline tests/bluetooth/bsim_bt/bsim_test_audio/src/unicast_client_test.c:183]: Same

**Review by Casper-Bonde-Bose — DISMISSED** [review]
LGTM - a single wrong search-replace that needs correction it looks like :-)

File: tests/bluetooth/bsim_bt/bsim_test_audio/src/unicast_client_test.c [hunk 6]
```diff
@@ -17,12 +17,11 @@ extern enum bst_result_t bst_result;
 static struct bt_audio_stream g_streams[CONFIG_BT_AUDIO_UNICAST_CLIENT_ASE_SNK_COUNT];
 static struct bt_codec *g_remote_codecs[CONFIG_BT_AUDIO_UNICAST_CLIENT_PAC_COUNT];
 static struct bt_audio_ep *g_sinks[CONFIG_BT_AUDIO_UNICAST_CLIENT_ASE_SNK_COUNT];
-static struct bt_conn *g_conn;
 
 /* Mandatory support preset by both client and server */
 static struct bt_audio_lc3_preset preset_16_2_1 = BT_AUDIO_LC3_UNICAST_PRESET_16_2_1;
 
-CREATE_FLAG(flag_connected);
+CREATE_FLAG(fladefault_connected);
```
[the remark this answers is not in the document]
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_audio/src/unicast_client_test.c]: Bad search-and-replace indeed :D

**Review by Casper-Bonde-Bose — APPROVED** [review]
Approved with an optional comment.
There is still a few 
```
unref(x)
y=NULL
```

Like:
```
bt_conn_unref(conn);
vcs_inst->cli.conn = NULL;
```
It is not wrong as `conn` is a copy of `vcs_inst->cli.conn` but as jhedberg I would have preferred:
```
bt_conn_unref(vcs_inst->cli.conn );
vcs_inst->cli.conn = NULL;
```

**Comment by Thalley** [comment]
> Approved with an optional comment. There is still a few
> 
> ```
> unref(x)
> y=NULL
> ```
> 
> Like:
> 
> ```
> bt_conn_unref(conn);
> vcs_inst->cli.conn = NULL;
> ```
> 
> It is not wrong as `conn` is a copy of `vcs_inst->cli.conn` but as jhedberg I would have preferred:
> 
> ```
> bt_conn_unref(vcs_inst->cli.conn );
> vcs_inst->cli.conn = NULL;
> ```

I was unsure about this one too, since @jhedberg did not specify those in his review. In my opinion
```c
bt_conn_unref(conn);
vcs_inst->cli.conn = NULL;
```

is preferred over 

```c
bt_conn_unref(vcs_inst->cli.conn);
vcs_inst->cli.conn = NULL;
```

as you have 1 less dereference. I don't have a strong opinion though and am more than willing to change. @jhedberg Please advice if you wanted that to change too.

**Comment by Casper-Bonde-Bose** [comment]
> > Approved with an optional comment. There is still a few
> > ```
> > unref(x)
> > y=NULL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Like:
> > ```
> > bt_conn_unref(conn);
> > vcs_inst->cli.conn = NULL;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It is not wrong as `conn` is a copy of `vcs_inst->cli.conn` but as jhedberg I would have preferred:
> > ```
> > bt_conn_unref(vcs_inst->cli.conn );
> > vcs_inst->cli.conn = NULL;
> > ```
> 
> I was unsure about this one too, since @jhedberg did not specify those in his review. In my opinion
> 
> ```c
> bt_conn_unref(conn);
> vcs_inst->cli.conn = NULL;
> ```
> 
> is preferred over
> 
> ```c
> bt_conn_unref(vcs_inst->cli.conn);
> vcs_inst->cli.conn = NULL;
> ```
> 
> as you have 1 less dereference. I don't have a strong opinion though and am more than willing to change. @jhedberg Please advice if you wanted that to change too.

I assume the compiler will load vcs_inst->cli.conn into a register and keep it there for both the call and the assignment. Hence from a performance perspective it would be the same. But I'm fine with the current PR - reading jhedbergs comments again I see they refer only to the default_conn variable.

**Review by carlescufi — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
