### PR TITLE
drivers: gpio: mchp: Fix pin configure after disconnect

### LINKED ISSUE #33371: mec15xxevb_assy6853: tests/drivers/gpio/gpio_basic_api/ failed
**Describe the bug**
drivers.gpio.2pin.gpio_port in tests/drivers/gpio/gpio_basic_api/ failed. 

**To Reproduce**
1. west build -b mec15xxevb_assy6853 -p auto tests/drivers/gpio/gpio_basic_api/
2. west flash
3. see error

**Expected behavior**
Test suite should pass.

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.5.0-1160-gb8b8e8cd6b1a  ***
Running test suite gpio_basic_test
===================================================================
START - test_gpio_port
Validate device GPIO140_176
Check GPIO140_176 output 15 connected to input 14
FATAL output pin not wired to input pin? (out high => in low)
```

**Environment (please complete the following information):**
 - Linux Ubuntu 18.04.4 LTS
 - zephyr-v2.5.0-1160-gb8b8e8cd6b1a
 - Toolchain zephyr-sdk-0.12.3

### PR DESCRIPTION
**Pull request by scottwcpg**
GPIO driver properly disconnects a pin. On subsequent pin
configure calls the driver does not clear the GPIO pin's
power gate field resulting in the pin remaining disconnected.

Signed-off-by: Scott Worley <scott.worley@microchip.com>

### CODE REVIEW

**Comment by scottwcpg** [comment]
This PR addresses issue 33371

**Review by dcpleung — APPROVED** [review]

**Comment by albertofloyd** [comment]
My bad, that recent change broke test cases

File: drivers/gpio/gpio_mchp_xec.c [hunk 1]
```diff
@@ -137,9 +144,6 @@ static int gpio_xec_configure(const struct device *dev,
 		/* Already configured */
```
Comment (albertofloyd) [inline drivers/gpio/gpio_mchp_xec.c:144]: @scottwcpg Maybe worth removing elseif and else since not  doing anything anymore.

Comment (scottwcpg) [reply drivers/gpio/gpio_mchp_xec.c]: @albertofloyd Pushed rebase removing the empty else if and else.

**Review by albertofloyd — APPROVED** [review]
