### PR TITLE
Bluetooth: Host: Fix bt_disable() for IPC giving HCI Reset timeout

### LINKED ISSUE #76202: Bluetooth: bt_disable() creates HCI Reset Timeout when IPC driver is used
**Describe the bug**
When bt_disable() is called using the IPC driver, the HCI Reset command times out.
This is because the RX thread is already aborted, therefore not allowing the command complete to arrive.

**To Reproduce**
Build a Bluetooth app for nRF53 and set `CONFIG_BT_RECV_WORKQ_BT`. Call `bt_disable()`. Observe that HCI reset times out.

**Impact**
`bt_disable()` doesn't work.

**Environment (please complete the following information):**
Started happening after https://github.com/zephyrproject-rtos/zephyr/pull/72323, d0e75ab87c4b53d66008c941c38709a2fca9dbea.

### PR DESCRIPTION
**Pull request by rugeGerritsen**
Some HCI drivers issue HCI reset when disabling, like the IPC HCI driver. We need to keep the RX thread running to allow receiving the command complete.

This commit postpones aborting the RX thread until this is done. The issue happens started occuring after commit
d0e75ab87c4b53d66008c941c38709a2fca9dbea.

Fixes #76202.

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Comment by rugeGerritsen** [comment]
@jhedberg , should this go into the release?

**Comment by jhedberg** [comment]
> @jhedberg , should this go into the release?

If it can be justified that it's a release blocker, then yes.

@aescolar

**Comment by rugeGerritsen** [comment]
`bt_disable()` is broken right now, it was not before. IMO this should be a blocker. But I guess there are other inputs to this as well

**Comment by jhedberg** [comment]
> bt_disable() is broken right now, it was not before. IMO this should be a blocker. But I guess there are other inputs to this as well

Playing the devils advocate: it's not generally broken, rather for a specific subset of drivers (maybe only one?). I have nothing against this going in, but ultimately it's up to the release managers (or potentially the TSC).

**Comment by aescolar** [comment]
thanks @rugeGerritsen , I have nothing against this fix. One note though: Fixes can also come to 3.7 as backports after we release 3.7.0

**Review by jori-nordic — APPROVED** [review]

File: subsys/bluetooth/host/hci_core.c [hunk 1]
```diff
@@ -4353,6 +4348,11 @@ int bt_disable(void)
 		return err;
 	}
 
+#if defined(CONFIG_BT_RECV_WORKQ_BT)
+	/* Abort RX thread */
+	k_thread_abort(&bt_workq.thread);
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/hci_core.c:4353]: Should we drain the work queue before aborting the thread? Otherwise, moving the abort may have no effect, depending on system priorities.

Comment (alwa-nordic) [reply subsys/bluetooth/host/hci_core.c:4353]: We could also leave the thread instead of aborting it. An idle thread should not be a problem, right?

Comment (rugeGerritsen) [reply subsys/bluetooth/host/hci_core.c:4353]: We call `k_work_queue_init();` and `k_work_queue_start()` on `bt_enable()`, so it is probably better to cleanup all state.
I agree with you that we should consider doing a proper cleanup. But that I would leave out of the scope of this PR.

**Review by alwa-nordic — APPROVED** [review]

**Review by jori-nordic — APPROVED** [review]

File: subsys/bluetooth/host/hci_core.c (hunk 1 above)
Comment (jhedberg) [reply subsys/bluetooth/host/hci_core.c:4353]: > We call `k_work_queue_init();` and `k_work_queue_start()` on `bt_enable()`, so it is probably better to cleanup all state.
> 
> I agree with you that we should consider doing a proper cleanup. But that I would leave out of the scope of this PR.

I agree. The current version of this PR is simply reverting the functionality to what it used to be before the HCI API PR.

**Comment by Dunedubby** [comment]
Can this be backported to 3.6?

**Comment by aescolar** [comment]
@Dunedubby, note 3.6 support ended around 2 months ago
https://docs.zephyrproject.org/latest/releases/index.html#supported-releases
You may want to considering jumping to the LTS (3.7) or backporting this patch locally yourself.
CC @henrikbrixandersen @MaureenHelm
