### PR TITLE
Out of tree driver

### LINKED ISSUE #20140: CMake: syscall macro's are not generated for out of tree DTS_ROOT
**Describe the bug**
When using a custom device tree with:
```
west build -b <board name> -- -DDTS_ROOT=<path to dts root>
```
include files that are under the `DTS_ROOT/include` are not added to the syscall_macros list.

**To Reproduce**
1. Create a out of tree devicetree with a header that uses __syscall declarations.
2. Use above command to build
3. The build command shows the error:`#include <syscalls/your_header.h> no such file or directory`

**Expected behavior**
It should be possible to add header that uses __syscall declarations in a out of tree devicetree.

**Impact**
The behavior makes it impossible to use out of tree dts.

### PR DESCRIPTION
**Pull request by SebastianBoe**
Introduce the CMake variable SYSCALL_INCLUDE_DIRS to support
out-of-tree syscall declarations and add the sample 'out_of_tree_driver'
to demonstrate and test it.

This fixes https://github.com/zephyrproject-rtos/zephyr/issues/20140 , see the issue for the motivation.

### CODE REVIEW

File: samples/application_development/out_of_tree_driver/src/hello_world_driver.h [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+#define __HELLO_WORLD_DRIVER_H__
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+#include <device.h>
+
+/*
+ * This 'Hello World' driver has a 'print' syscall that prints the
```
Comment (mbolivar) [inline samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: I think adding this sample is a great idea, thanks for working on it.

Would it make sense to make the driver source code a separate module, to really make sure there's no special magic due to being inside the zephyr tree?

Comment (SebastianBoe) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: You mean using ZEPHYR_EXTRA_MODULES to point to a dir inside of the app dir, right?

Not an entry in west.yml?

Comment (mbolivar) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: I was asking about an entry in west.yml, yes.

Comment (SebastianBoe) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: Oh, I would not like to do that as I don't want to slow down normal west usage just for a sample.

Comment (mbolivar) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: OK, fair enough.

Would ZEPHYR_EXTRA_MODULES work for code that's nested inside the zephyr repository? It would be nice to make the sample work as closely as possible to how users will need to use it.

Comment (SebastianBoe) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: Yes

Comment (mbolivar) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: Ok, I think that would be nice, then.  But I don't think it should block the merge. (A comment describing how ZEPHYR_EXTRA_MODULES would not be needed if the user actually wants to make a truly out of tree driver would also be good in that case.)

Comment (mbolivar) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: > (A comment describing how ZEPHYR_EXTRA_MODULES would not be needed if the user actually wants to make a truly out of tree driver would also be good in that case.)

By the way, I saw a user on slack confused about duplicate items in their ZEPHYR_MODULES list (caused by adding some directories that were already in ZEPHYR_MODULES to their custom ZEPHYR_EXTRA_MODULES) led to errors.

Would it make sense for CMake to deduplicate this list? That would make it possible for users to copy/paste the sample code and ignore that comment.

Comment (SebastianBoe) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: It does make sense to deduplicate this list. A PR to this effect would be welcome.

Comment (SebastianBoe) [reply samples/application_development/out_of_tree_driver/src/hello_world_driver.h]: Organized the driver as a ZEPHYR_EXTRA_MODULE.

File: samples/application_development/out_of_tree_driver/CMakeLists.txt [hunk 2]
```diff
@@ -0,0 +1,19 @@
+# SPDX-License-Identifier: Apache-2.0
+
+list(APPEND ZEPHYR_EXTRA_MODULES
```
Comment (mbolivar) [inline samples/application_development/out_of_tree_driver/CMakeLists.txt]:
```suggestion
# For the sake of demonstration, we add the driver directory as a zephyr module
# by hand. If your driver is a project that's managed by west, you can remove this line.
list(APPEND ZEPHYR_EXTRA_MODULES
```

File: samples/application_development/out_of_tree_driver/hello_world_module/zephyr/Kconfig [hunk 3]
```diff
@@ -0,0 +1,5 @@
+# Copyright (c) 2019 Nordic Semiconductor
+# SPDX-License-Identifier: Apache-2.0
+
+config HELLO_WORLD_DRIVER
+	bool ""
```
Comment (mbolivar) [inline samples/application_development/out_of_tree_driver/hello_world_module/zephyr/Kconfig]:
```suggestion
	bool "Enable support for the demonstration out of tree driver"
```

**Review by mbolivar — COMMENTED** [review]
Seems sane to me. It would be good to know if @andrewboie agrees.

File: samples/application_development/out_of_tree_driver/CMakeLists.txt [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+  ${CMAKE_CURRENT_SOURCE_DIR}/hello_world_module
+  )
+
+cmake_minimum_required(VERSION 3.13.1)
+
+# Add an absolute directory path to the CMake variable
+# SYSCALL_INCLUDE_DIRS. This ensures that the syscall machinery will
+# be able to find the module's syscalls.
+list(APPEND SYSCALL_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/hello_world_module/zephyr)
```
Comment (andrewboie) [inline samples/application_development/out_of_tree_driver/CMakeLists.txt]: if we intend for apps to be adding stuff to SYSCALL_INCLUDE_DIRS maybe we should define a helper macro for doing so.

`zephyr_syscalls_add_include_directory(...path...)` or some such perhaps?

**Review by tyrantlizard77 — CHANGES_REQUESTED** [review]
code change looks ok to me, minor suggestion on adding a macro to make this easier to use.

however the documentation for system calls needs to be updated to mention this capability (doc/reference/usermode/syscalls.rst)

File: samples/application_development/out_of_tree_driver/CMakeLists.txt (hunk 4 above)
Comment (SebastianBoe) [reply samples/application_development/out_of_tree_driver/CMakeLists.txt]: Unfortunately, this function wouldn't be available as boilerplate is not sourced yet.

Setting variables before boilerplate.cmake and from CLI is well established so this should be OK.

Comment (SebastianBoe) [reply samples/application_development/out_of_tree_driver/CMakeLists.txt]: Will update docs

Comment (SebastianBoe) [reply samples/application_development/out_of_tree_driver/CMakeLists.txt]: docs updated

File: doc/reference/usermode/syscalls.rst [hunk 5]
```diff
@@ -88,6 +89,15 @@ bottom of ``include/sensor.h``:
 
     #include <syscalls/sensor.h>
 
+C prototype functions must be declared in one of the directories
+listed in the CMake variable ``SYSCALL_INCLUDE_DIRS``. This list
+always contains ``${ZEPHYR_BASE}/include``, but will also contain
+``APPLICATION_SOURCE_DIR`` when ``CONFIG_APPLICATION_DEFINED_SYSCALL``
+is set, or ``${ZEPHYR_BASE}/subsys/testsuite/ztest/include`` when
+``CONFIG_ZTEST`` is set. Or any other path that is added to the list
```
Comment (dbkinder) [inline doc/reference/usermode/syscalls.rst]: Let's not start a sentence with ``or``:
```
Additional paths can be added to the list through the CMake command line...
```

**Review by dbkinder — CHANGES_REQUESTED** [review]
Thanks for updating the syscalls doc, one suggested edit...

**Comment by SebastianBoe** [comment]
@andrewboie : The docs have been updated, but the macro was not added. Please re-assess your review.

**Comment by SebastianBoe** [comment]
@dbkinder : Thank you for the review, the feedback has been applied.

**Review by dbkinder — APPROVED** [review]
+1 for doc changes, thanks!

**Review by tejlmand — APPROVED** [review]

**Comment by SebastianBoe** [comment]
@andrewboie : Your NACK has been addressed, please review again.

**Review by tyrantlizard77 — APPROVED** [review]

**Comment by SebastianBoe** [comment]
@nashif : Ready to merge

**Comment by SebastianBoe** [comment]
@nashif : This is ready to be merged.

**Comment by SebastianBoe** [comment]
@carlescufi : This is ready to be merged

**Review by nashif — APPROVED** [review]
