### PR TITLE
drivers: dma: stm32: fixes spi_loopback on nucleo_wb55rg

### LINKED ISSUE #28184: tests: drivers: spi: spi_loopback: fails on board nucleo_wb55rg
**Describe the bug**
What have you tried to diagnose or workaround this issue?

**To Reproduce**
1. west -p auto -b nucleo_wb55rg tests/drivers/spi/spi_loopback  nucleo_wb55rg
2. west flash
3. See error

**Expected behavior**
test passed

**Logs and console output**
```
*** Booting Zephyr OS build v2.4.0-rc1-10-g4d3580d29735  ***
Running test suite test_spi
===================================================================
START - test_spi_loopback
I: SPI test on buffers TX/RX 0x20000000/0x200004f0
I: SPI test slow config
I: Start complete multiple
I: CS control inhibited (no GPIO device)
E: DMA callback channel 8 is not valid.
E: Code -5

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/spi/spi_loopback/src/spi.c:140: spi_complete_multiple: (ret is true)
SPI transceive failed
 FAIL - test_spi_loopback
===================================================================
Test suite test_spi failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Linux and Windows
 - Toolchain : Zephyr SD
 - Commit SHA:4d3580d29735bd3d3d7a89e7475ccd9e001cd818

### PR DESCRIPTION
**Pull request by ABOSTM**
2 commits:
* drivers: dma: dma_stm32: can't use device_get_binding() during init
* drivers: dma: dma_stm32_v2: typo in compilation switch

Fixes #28184

### CODE REVIEW

**Review by erwango — APPROVED** [review]

File: drivers/dma/dma_stm32.c [hunk 1]
```diff
@@ -594,8 +594,8 @@ static int dma_stm32_init(const struct device *dev)
 	config->config_irq(dev);
 
 #ifdef CONFIG_DMAMUX_STM32
-	int offset = ((dev == device_get_binding((const char *)"DMA_1"))
-			? 0 : config->max_streams);
+	int offset = (strncmp(dev->name, "DMA_1", 5)
```
Comment (pabigot) [inline drivers/dma/dma_stm32.c:597]: This is a little fragile, as the actual device name is from `DT_INST_LABEL(index)`.  If there's an instance-specific constraint on available streams that should probably come from devicetree.

**Review by pabigot — COMMENTED** [review]
Just a comment, not sure this is feasible (but it would be safer).

File: drivers/dma/dma_stm32.c (hunk 1 above)
Comment (erwango) [reply drivers/dma/dma_stm32.c:597]: I agree that getting this piece of info from dts would be safer (in a next iteration probably).
@FRASTM would it be possible to add a relationship between DMA_X and DMAMUX within dmamux node bindings ?

Comment (FRASTM) [reply drivers/dma/dma_stm32.c:597]: yes, 
adding a phandle array to the dmamux deviceTree named **dma-masters**

> dma-masters = <&dma1 &dma2>;


like the https://git.kernel.org/pub/scm/linux/kernel/git/devicetree/devicetree-rebasing.git/plain/Bindings/dma/dma-router.yaml

Comment (erwango) [reply drivers/dma/dma_stm32.c:597]: > yes, adding in a new further PR
> --> phandles to the dmamux deviceTree named **dma-masters**
> 
> > dma-masters = <&dma1 &dma2>;
> 
> like the https://git.kernel.org/pub/scm/linux/kernel/git/devicetree/devicetree-rebasing.git/plain/Bindings/dma/dma-router.yaml

Looks good to me.
Then, what do we do with current PR ?
@pabigot do we use current fix for 2.4.0 and wait V2.5.0 for the DT version?

Comment (pabigot) [reply drivers/dma/dma_stm32.c:597]: If you don't think it can be addressed immediately then I'm OK with this as long as somebody opens an issue to ensure the cleanup is done for the next release.  Let me know when that's done.

Comment (erwango) [reply drivers/dma/dma_stm32.c:597]: @pabigot a long term solution is being reviewed here: https://github.com/zephyrproject-rtos/zephyr/pull/28268.
This is not finalized yet.

**Review by pabigot — APPROVED** [review]
Approved based on the expectation of future integration of #28268 (not necessarily for 2.4.0)

**Review by MaureenHelm — APPROVED** [review]
