### PR TITLE
sensor: adxl345: Decoder-related bug-fixes

### LINKED ISSUE #84252: sensor: ADXL345 Decoder does not work
**Describe the bug**
The ADXL345 driver decoder does not work, due to various issues:
- Missing API `get_size_info()` that causes clients using it to crash (e.g: Sensor Shell).
- Non-streaming Decoder:
    - Data not expressed in `sensor_three_axis_data`, therefore not legible for clients.
    - decode_sample() returns zero on success (no data).
- Q-scale factor table with wrong scaling values, leading to incorrect readings.
- Non-streaming apps still have FIFO bit enabled, leading to getting samples up to 1-second old.

This seems to be present since the driver was introduced (v4.0.0 release)

**To Reproduce**
Build a sample with Sensor Shell enabled, with an ADXL345 and it will not work.

**Expected behavior**
ADXL345 works as expected.

### PR DESCRIPTION
**Pull request by ubieda**
### Description
This PR applies various fixes to the ADXL345 driver:
- Decoder:
	- Add `adxl345_get_size_info()` used, for instance, by the Sensor Shell.
	- Fix  `adxlXXX_decode_sample()` to use `sensor_three_axis_data`.
	- Fix Q-scale factor scaling tables, and add some description on the calculation rationale.
- Driver:
	- Disable Streaming by default so users do not need to worry about it unless explicitly interested in such functionality.
	- Only write FIFO_STREAMING config-bit if using FIFO, to suppress delay in sample acquisition for basic read/decode applications.

Fixes #84252 

### Testing
Run Shell sample with sensor commands on the ADXL345 (tested both for SPI and I2C). The following evidence is for I2C:
``` console
west build -b nrf52840dk/nrf52840 samples/subsys/shell/shell_module
```
- DTS Overlay (`samples/subsys/shell/shell_module/boards/nrf52840dk_nrf52840.overlay`)
``` device-tree
/ {
	aliases {
		accel0 = &adxl345;
	};
};

&arduino_i2c {
	status = "okay";
	
	adxl345: adxl345@53 {
		compatible = "adi,adxl345";
		reg = <0x53>;
		status = "okay";
		int2-gpios = <&gpio1 3 GPIO_ACTIVE_HIGH>;
	};
};
```
- Config Overlay (`samples/subsys/shell/shell_module/boards/nrf52840dk_nrf52840.conf`)
```
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_SENSOR_SHELL=y
```
- Sample Output:
``` console
uart:~$ sensor get adxl345@53 
channel type=3(accel_xyz) index=0 shift=7 num_samples=1 value=8177551269ns, (0.000000, -0.459686, 8.887274)
uart:~$ sensor get adxl345@53
channel type=3(accel_xyz) index=0 shift=7 num_samples=1 value=8825378417ns, (0.000000, -0.459686, 8.887274)
uart:~$ sensor get adxl345@53
channel type=3(accel_xyz) index=0 shift=7 num_samples=1 value=9273559570ns, (0.000000, -0.459686, 8.887274)
uart:~$ sensor get adxl345@53
channel type=3(accel_xyz) index=0 shift=7 num_samples=1 value=9713378906ns, (0.000000, -0.459686, 8.887274)
uart:~$ sensor get adxl345@53
channel type=3(accel_xyz) index=0 shift=7 num_samples=1 value=10129577636ns, (0.000000, -0.459686, 9.040503)
uart:~$ sensor get adxl345@53
channel type=3(accel_xyz) index=0 shift=7 num_samples=1 value=12177551269ns, (-1.532288, -0.612915, 9.346961)
uart:~$ sensor get adxl345@53
channel type=3(accel_xyz) index=0 shift=7 num_samples=1 value=12641601562ns, (1.685517, -6.129155, 4.137179)
uart:~$ 

```

### CODE REVIEW

File: drivers/sensor/adi/adxl345/adxl345_decoder.c [hunk 1]
```diff
@@ -208,17 +208,20 @@ static int adxl345_decode_sample(const struct adxl345_sample *data,
...
 
 	switch (chan_spec.chan_type) {
 	case SENSOR_CHAN_ACCEL_XYZ:
-		adxl345_accel_convert(out++, data->x);
-		adxl345_accel_convert(out++, data->y);
-		adxl345_accel_convert(out, data->z);
+		adxl345_accel_convert_q31(out->readings->x, data->x, data->selected_range, false);
+		adxl345_accel_convert_q31(out->readings->y, data->y, data->selected_range, false);
+		adxl345_accel_convert_q31(out->readings->z, data->z, data->selected_range, false);
 		break;
```
Comment (cfriedt) [inline drivers/sensor/adi/adxl345/adxl345_decoder.c:225]:
```suggestion
		adxl345_accel_convert_q31(&out->readings->x, data->x, data->selected_range, false);
		adxl345_accel_convert_q31(&out->readings->y, data->y, data->selected_range, false);
		adxl345_accel_convert_q31(&out->readings->z, data->z, data->selected_range, false);
		break;
```

**Comment by ubieda** [comment]
Just rebased. Need to create a GH issue to get this backported into 4.0.0

**Review by teburd — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Comment by laurensslats** [comment]
Tested and it works for me using the ADXL345.

**Comment by ubieda** [comment]
Created issue and added backport label

**Comment by cfriedt** [comment]
I also tested this on the `xiao_esp32c3` with `adxl343`

**Review by MaureenHelm — APPROVED** [review]
Thanks @ubieda !

I tested this out with the following and it looks good:
```
$ west build -p -b apard32690//m4 --shield pmod_acl samples/subsys/shell/shell_module/ -- -DCONFIG_SENSOR=y -DCONFIG_SENSOR_ASYNC_API=y -DCONFIG_SENSOR_SHELL=y
```

@dimitrije-lilic please take a look
