### PR TITLE
Bluetooth: buf: Put command complete/status in sync buf pool

### LINKED ISSUE #78223: Bluetooth: Assertion in bt_hci_evt_create() with scanning and extended advertising in progress
**Describe the bug**
Assertion in bt_hci_evt_create() with scanning and extended advertising in progress.

```
[2024-09-10 12:30:07.812] uart:~$ [DEVICE]: 7C:10:41:3A:2C:E2 (random), AD evt type 0, RSSI -96  C:1 S:1 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[2024-09-10 12:30:07.828] uart:~$ [DEVICE]: 68:72:C3:9A:1E:47 (public), AD evt type 3, RSSI -78  C:0 S:0 D:0 SR:0 E:0 Prim: LE 1M, Secn: No packets, Interval: 0x0000 (0 us), SID: 0xff
[2024-09-10 12:30:07.845] uart:~$ [DEVICE]: 50:7C:98:1D:BF:56 (random), AD evt type 0, RSSI -59  C:1 S:1 D:9  C:1 S:1 D:0 SR:0 E:0 Prim: ASSERTION FAIL [buf] @ WEST_TOPDIR/zephyr/subsys/bluetooth/host/hci_common.c:19
[2024-09-10 12:30:07.866] uart:~$ [00:45:10.745,148] <err> os: r0/a1:  0x00000003  r1/a2:  0x00000000  r2/a3:  0x200034f8
[2024-09-10 12:30:07.877] uart:~$ [00:45:10.745,156] <err> os: r3/a4:  0x00000003 r12/ip:  0x20003458 r14/lr:  0x00011309
[2024-09-10 12:30:07.889] uart:~$ [00:45:10.745,162] <err> os:  xpsr:  0x01000000
[2024-09-10 12:30:07.897] uart:~$ [00:45:10.745,167] <err> os: Faulting instruction address (r15/pc): 0x00011316
[2024-09-10 12:30:07.907] uart:~$ [00:45:10.745,188] <err> os: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
[2024-09-10 12:30:07.918] uart:~$ [00:45:10.745,209] <err> os: Current thread: 0x200034f8 (sysworkq)
[2024-09-10 12:30:07.927] uart:~$ [00:45:10.819,969] <err> os: Halting system
```

**To Reproduce**
1. mkdir -p build/shell; cd build/shell
2. cmake -GNinja -DBOARD=nrf54l15pdk/nrf54l15/cpuapp -DCONFIG_BT_CTLR_PHY_CODED=y ../../tests/bluetooth/shell
3. ninja
4. ninja flash
5. open terminal (ex, minicom -D /dev/ttyACM{n})
6. `bt init`
7. `bt adv-create conn-nscan ext-adv`
8. `bt adv-data 020933`
9. `bt adv-start`
10. `bt scan on coded`
11. Let the application run for a duration in multiples of 15 mins
12. The said assertion can be observed after 15/30/45/... mins when RPA expires

**Expected behavior**
Scanning and Extended/Legacy Advertising should continue for eternity without assertions.

**Impact**
Showstopper

**Logs and console output**
[hci_common_assert.txt](https://github.com/user-attachments/files/16944159/hci_common_assert.txt)

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.8
 - Commit SHA: a3f71f13bfb

**Additional context**
NA

### PR DESCRIPTION
**Pull request by jori-nordic**
Why is it ok to use the sync pool?

Because command complete/status is processed in prio: that means on the same stack as the `bt_recv()` call from the driver.

Why does it fix the issue?

Because the complete/status event goes into a pool that is guaranteed to have one free buffer any time `bt_recv()` is not executing.

Since the driver is the one calling bt_recv(), it (hopefully) will finish one `bt_recv()` before starting another one.

Fixes #78223

### CODE REVIEW

**Review by jhedberg — DISMISSED** [review]

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/buf.c [hunk 1]
```diff
@@ -100,9 +91,11 @@ struct net_buf *bt_buf_get_evt(uint8_t evt, bool discardable,
 	switch (evt) {
 #if defined(CONFIG_BT_CONN) || defined(CONFIG_BT_ISO)
 	case BT_HCI_EVT_NUM_COMPLETED_PACKETS:
+#endif /* CONFIG_BT_CONN || CONFIG_BT_ISO */
+	case BT_HCI_EVT_CMD_STATUS:
+	case BT_HCI_EVT_CMD_COMPLETE:
```
Comment (cvinayak) [inline subsys/bluetooth/host/buf.c:96]: BT Public APIs are callable from application's pre-emptive threads (main thread), does this change mandate that the HCI Driver's send interface (directly called from APIs) delegate the processing of HCI commands to a co-operative thread (previously the tx thread) to ensure the Controller's non-reentrant functions are not directly called from applications?

If the Controller's function is made re-entrant, then can there be a case where the Kernel switches contexts (time slice) between two threads that are calling APIs that lead to the HCI Driver's send interface (command buffer depth > 1) being invoked? In which case will a pool size of 1 be sufficient?

Example, a thread that is transmitting data, another thread that could issue HCI channel classification command or HCI vendor specific Tx Power command.

Can we instead ensure/reserve a buf for the command complete/status event before HCI Driver's send interface is invoked?

**Review by cvinayak — DISMISSED** [review]

**Comment by cvinayak** [comment]
Could you include your bsim test case in this PR that would cover the fix.

File: subsys/bluetooth/host/buf.c (hunk 1 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/buf.c:96]: > HCI Driver's send interface (directly called from APIs) delegate the processing of HCI commands to a co-operative thread

Already the case. The commands are all guaranteed to be sent through `bt_send()` on the system workqueue.

Comment (jori-nordic) [reply subsys/bluetooth/host/buf.c:96]: here: https://github.com/jori-nordic/zephyr/blob/c6fd58e73d7b7375b143e131e070087bb7ee8b55/subsys/bluetooth/host/hci_core.c#L4681-L4697

**Review by jhedberg — DISMISSED** [review]

File: subsys/bluetooth/host/buf.c [hunk 2]
```diff
@@ -41,9 +34,7 @@ LOG_MODULE_REGISTER(bt_buf, CONFIG_BT_LOG_LEVEL);
  * the HCI transport to fill buffers in parallel with `bt_recv`
  * consuming them.
  */
-#define SYNC_EVT_SIZE NUM_COMLETE_EVENT_SIZE
 NET_BUF_POOL_FIXED_DEFINE(sync_evt_pool, 1, SYNC_EVT_SIZE, sizeof(struct bt_buf_data), NULL);
```
Comment (cvinayak) [inline subsys/bluetooth/host/buf.c:37]:
```suggestion
NET_BUF_POOL_FIXED_DEFINE(sync_evt_pool, 1, BT_BUF_RX_SIZE, sizeof(struct bt_buf_data), NULL);
```

File: subsys/bluetooth/host/buf.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/host/buf.c:96]: > > HCI Driver's send interface (directly called from APIs) delegate the processing of HCI commands to a co-operative thread
> 
> Already the case. The commands are all guaranteed to be sent through `bt_send()` on the system workqueue.

Great, at one point I was concern that LL interface where called from pre-emptive thread.

How is the case handled when scan disable requires that an adv report be processed before command complete is generated? (cross over of command and event). API call from system workqueue would deadlock waiting for command complete?

@rugeGerritsen isn't it a similar scenario with the deadlock in receiving disconnection event when data is being sent from system workqueue execution context?

Will the solution be to disallow API calls from system workqueue execution context?

Comment (alwa-nordic) [reply subsys/bluetooth/host/buf.c:96]: > How is the case handled when scan disable requires that an adv report be processed before command complete is generated? (cross over of command and event). API call from system workqueue would deadlock waiting for command complete?

Adv reports blocking the event stream is described in https://github.com/zephyrproject-rtos/zephyr/issues/50786. I'll be submitting a separate fix for this.

Comment (jori-nordic) [reply subsys/bluetooth/host/buf.c:96]: @cvinayak regarding the re-entrancy of the LL, you could use something like the SDC, a simple 1-count semaphore: https://github.com/jori-nordic/sdk-nrf/blob/32b91a8fe62d6c2c86d076344c03cbb79f5e91b2/subsys/bluetooth/controller/hci_driver.c#L547-L552

File: subsys/bluetooth/host/buf.c (hunk 2 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/buf.c:37]: not quite, `BT_BUF_RX_SIZE` includes the ACL size too, which might be bigger than 255.

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/buf.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/host/buf.c:96]: > > How is the case handled when scan disable requires that an adv report be processed before command complete is generated? (cross over of command and event). API call from system workqueue would deadlock waiting for command complete?
> 
> Adv reports blocking the event stream is described in #50786. I'll be submitting a separate fix for this.

Thanks for reminding it, forgot that one.



> @cvinayak regarding the re-entrancy of the LL, you could use something like the SDC, a simple 1-count semaphore: https://github.com/jori-nordic/sdk-nrf/blob/32b91a8fe62d6c2c86d076344c03cbb79f5e91b2/subsys/bluetooth/controller/hci_driver.c#L547-L552

ok... will study the latest data flow path and analyse based on the fact now that system work queue is the highest priority (value -1) co-operative thread from which LL interfaces are directly called compared to earlier Tx thread (-7), and wherein Rx Prio being at (-6) in Zephyr Controller's hci driver that received command complete/status/num completes/disconnection complete.

Now that system work queue is handling command complete/status/num complete in sync pool, has disconnection complete been analysed for sync pool use?

No further action for this PR.

File: subsys/bluetooth/host/buf.c (hunk 2 above)
Comment (cvinayak) [reply subsys/bluetooth/host/buf.c:37]: Agreed.

**Comment by Thalley** [comment]
Should https://github.com/zephyrproject-rtos/zephyr/pull/78294 get merged before this, seeing as this builds on top of that?

File: subsys/bluetooth/host/buf.c (hunk 1 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/buf.c:96]: > Now that system work queue is handling command complete/status/num complete in sync pool, has disconnection complete been analysed for sync pool use?

Disconnect complete events cannot be put in the sync pool because their event buffers are retained beyond "prio" context. This has to be fixed first.

Comment (alwa-nordic) [reply subsys/bluetooth/host/buf.c:96]: > ok... will study the latest data flow path and analyse based on the fact now that system work queue is the highest priority (value -1) co-operative thread from which LL interfaces are directly called compared to earlier Tx thread (-7), and wherein Rx Prio being at (-6) in Zephyr Controller's hci driver that received command complete/status/num completes/disconnection complete.

Thanks :) I would prefer solutions that do no rely on thread priorities. If you see any issues, I think we should look into fixing it with explicit synchronization.

File: subsys/bluetooth/host/buf.c [hunk 3]
```diff
@@ -18,20 +18,13 @@
...
-
-#if defined(CONFIG_BT_CONN) || defined(CONFIG_BT_ISO)
-#define NUM_COMLETE_EVENT_SIZE BT_BUF_EVT_SIZE(                        \
-	sizeof(struct bt_hci_cp_host_num_completed_packets) +          \
-	MAX_EVENT_COUNT * sizeof(struct bt_hci_handle_count))
+/* Events have a length field of 1 byte. This size fits all events.
+ *
+ * It's true that we don't put all kinds of events there (yet), but already
+ * "command complete". The "command complete" event has an arbitrary payload (ie
+ * depends on which command).
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/buf.c:25]:
```suggestion
 * It's true that we don't put all kinds of events there (yet), but already
 * the command complete event has an arbitrary payload (ie. depends on command opcode).
```

**Comment by jori-nordic** [comment]
[53] whoops
image

will analyze tomorrow but from the other threads' backtraces it seems like the same deadlock.

**Comment by jori-nordic** [comment]
> will analyze tomorrow

Analyzed: This is exactly https://github.com/zephyrproject-rtos/zephyr/issues/50786 .
- There are a bunch of buffers on the netcore side, so it reads a whole lot of ext adv reports that it then tries to forward to appcore.
- appcore allocates, but without the `discardable` bit. so it waits that the host finishes processing the last ext adv report
- there is a command sent
- the ipc driver cannot know that there is an "important" event - the command response - way back in the queue
- both queues combined are so large, that blocking the host for 200ms on each report is enough to trigger the `HCI_CMD_TIMEOUT` (10s).

I verified that "just" increasing `HCI_CMD_TIMEOUT` makes the test pass. So it's not a deadlock, just a big-ass stall on the syswq and the IPC wq.

My suggestion is to merge this fix without the commit for testing on 53. And I will make another PR that adds testing on 53, and block that on the resolution of https://github.com/zephyrproject-rtos/zephyr/issues/50786

File: subsys/bluetooth/host/buf.c (hunk 3 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/buf.c]: slightly reworded

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/buf.c [hunk 4]
```diff
@@ -18,20 +18,12 @@
...
-#if defined(CONFIG_BT_CONN) || defined(CONFIG_BT_ISO)
-#define NUM_COMLETE_EVENT_SIZE BT_BUF_EVT_SIZE(                        \
-	sizeof(struct bt_hci_cp_host_num_completed_packets) +          \
-	MAX_EVENT_COUNT * sizeof(struct bt_hci_handle_count))
+/* Events have a length field of 1 byte. This size fits all events.
+ *
+ * It's true that we don't put all kinds of events there (yet). However, the
+ * command complete event has an arbitrary payload, depending on opcode.
+ */
+#define SYNC_EVT_SIZE (BT_BUF_RESERVE + BT_HCI_EVT_HDR_SIZE + 255)
```
Comment (Thalley) [inline subsys/bluetooth/host/buf.c:26]: Consider adding `MAX` somewhere in the name so that it's not confused with something like `CONFIG_BT_BUF_EVT_RX_SIZE` that is relative

**Review by Thalley — APPROVED** [review]
