### PR TITLE
Bt dev ready check

### LINKED ISSUE #21105: Bluetooth API called before finished initialization.
**Describe the bug**
Some Bluetooth API function does not check for if the bluetooth device has finished initialized. This can lead to undefined behavior as the stack is operating on uninitialized kernel objects and memory.

**To Reproduce**
Call public API functions before calling bt_enable, or directly after bt_enable when supplied a ready callback.
Affected APIs:
OOB API
Gatt Notification and Indication
HCI commands

**Expected behavior**
APIs should return error code consistent with the rest of the API.

**Impact**
Undefined behavior. Minor annoyance, application should be able to not end up in this situation.

### PR DESCRIPTION
**Pull request by joerchan**
Check that the bluetooth device has in fact been initialized before
continuing with public API calls. This could lead to crashes when using
state that has not yet been initialized.

Switch to using the synchronous bt_init call before starting the main
loop in the peripheral samples. This is to avoid sending notifications
before bluetooth has been properly initialized.

Fixes: #21105

### CODE REVIEW

**Comment by joerchan** [comment]
@jhedberg I intentionally skipped APIs that have check for `conn->state != CONNECTED`. But I'm not sure if that is a good decision or not.

File: samples/bluetooth/peripheral/src/main.c [hunk 1]
```diff
@@ -323,11 +320,12 @@ void main(void)
 {
 	int err;
 
-	err = bt_enable(bt_ready);
+	err = bt_enable();
```
Comment (jhedberg) [inline samples/bluetooth/peripheral/src/main.c]: This can't possibly compile since you're not changing the bt_enable API - it still has one parameter. I guess you intended to pass NULL here? Please always at least compile-test your changes 😉

File: samples/bluetooth/peripheral_esp/src/main.c [hunk 2]
```diff
@@ -437,11 +434,12 @@ void main(void)
 {
 	int err;
 
-	err = bt_enable(bt_ready);
+	err = bt_enable();
```
Comment (jhedberg) [inline samples/bluetooth/peripheral_esp/src/main.c]: Same here.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Do you want these for 2.1? I think that'd make sense. If so, please file an issue and reference it.

File: samples/bluetooth/peripheral/src/main.c (hunk 1 above)
Comment (joerchan) [reply samples/bluetooth/peripheral/src/main.c]: Sorry, I was being lazy and letting CI do it for me.

**Comment by joerchan** [comment]
@jhedberg Also the various register functions are fine to call before, but I'm wondering if we should still add the ready check or not.
For example `bt_conn_cb_register` `bt_conn_auth_cb_register` `bt_gatt_service_register` etc.

I can create an issue if you want it into the 2.1 release. It's a very easy workaround for this so I wouldn't consider it very important to put in.

File: samples/bluetooth/peripheral_ht/src/main.c [hunk 3]
```diff
@@ -108,11 +105,12 @@ void main(void)
 {
 	int err;
 
-	err = bt_enable(bt_ready);
+	err = bt_enable(NULL);
 	if (err) {
 		printk("Bluetooth init failed (err %d)\n", err);
 		return;
 	}
+	bt_ready();
```
Comment (jhedberg) [inline samples/bluetooth/peripheral_ht/src/main.c]: Please add an empty line after `{` (sorry for not pointing that out before)

File: tests/bluetooth/bsim_bt/bsim_test_app/src/test_connect2.c [hunk 4]
```diff
@@ -148,11 +148,12 @@ static void test_con2_main(void)
 	static int notify_count;
 	int err;
 
-	err = bt_enable(bt_ready);
+	err = bt_enable(NULL);
 	if (err) {
 		FAIL("Bluetooth init failed (err %d)\n", err);
 		return;
 	}
+	bt_ready();
```
Comment (jhedberg) [inline tests/bluetooth/bsim_bt/bsim_test_app/src/test_connect2.c]: Same here.

File: samples/bluetooth/peripheral_hr/src/main.c [hunk 5]
```diff
@@ -115,11 +112,12 @@ void main(void)
 {
 	int err;
 
-	err = bt_enable(bt_ready);
+	err = bt_enable(NULL);
 	if (err) {
 		printk("Bluetooth init failed (err %d)\n", err);
 		return;
 	}
+	bt_ready();
```
Comment (jhedberg) [inline samples/bluetooth/peripheral_hr/src/main.c]: Empty line after `}`. I think I understand your thinking though:"this ties strongly into the preceding lines", however the style we follow is empty line after `}` unless the next one is also `}` (or e.g. `#endif`).

**Review by jhedberg — CHANGES_REQUESTED** [review]
A couple of cosmetic coding-style fixes, sorry for not pointing them out earlier.

> Also the various register functions are fine to call before, but I'm wondering if we should still add the ready check or not.

I'm a little bit divided about this. They are just setting up internal state that's not related to the init. It would also not be nice to force the application to re-run these registrations once we've introduce a `bt_disable()` and you want to re-enable Bluetooth. So I'd let them stay as they are.

File: subsys/bluetooth/host/hci_core.h [hunk 6]
```diff
@@ -189,6 +189,11 @@ extern struct bt_dev bt_dev;
 extern const struct bt_conn_auth_cb *bt_auth;
 #endif /* CONFIG_BT_SMP || CONFIG_BT_BREDR */
 
+struct net_buf *hci_cmd_create(u16_t opcode, u8_t param_len);
+int hci_cmd_send(u16_t opcode, struct net_buf *buf);
+int hci_cmd_send_sync(u16_t opcode, struct net_buf *buf,
+				 struct net_buf **rsp);
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.h]: Minor: please align right after the `(` of the first line (i.e. tabs + 0-7 spaces)

File: subsys/bluetooth/host/hci_core.c [hunk 7]
```diff
@@ -4405,7 +4433,7 @@ static int read_ext_features(void)
 		cp = net_buf_add(buf, sizeof(*cp));
 		cp->page = i;
 
-		err = bt_hci_cmd_send_sync(BT_HCI_OP_READ_LOCAL_EXT_FEATURES,
+		err = hci_cmd_send_sync(BT_HCI_OP_READ_LOCAL_EXT_FEATURES,
 					   buf, &rsp);
```
Comment (jhedberg) [inline subsys/bluetooth/host/hci_core.c]: Seems like the alignment with `(` will be off since you're not adjusting the second line after making the first shorter. I won't comment on all similar places in this patch, but it seems there are several of them.

**Review by jhedberg — CHANGES_REQUESTED** [review]
Looks good, except for minor coding style stuff (split line alignment)

**Comment by carlescufi** [comment]
@jhedberg  can you take another look?

File: drivers/bluetooth/hci/spi.c [hunk 8]
```diff
@@ -291,7 +291,7 @@ static int bt_spi_send_aci_config_data_controller_mode(void)
 	/* Force BlueNRG-MS roles to Link Layer only mode */
 	param->value = BLUENRG_ACI_LL_MODE;
 
-	bt_hci_cmd_send(BLUENRG_ACI_WRITE_CONFIG_DATA, buf);
+	hci_cmd_send(BLUENRG_ACI_WRITE_CONFIG_DATA, buf);
```
Comment (jhedberg) [inline drivers/bluetooth/hci/spi.c]: I'm not following how this is supposed to work (at the same time I don't see CI failures so maybe I'm missing something): you're putting the declarations of `hci_cmd_create()` and `hci_cmd_send()` into the host-internal header file `hci_core.h` but I don't see the drivers including it anywhere? To be fair, they probably shouldn't, since that header file is supposed to only be used by code in `subsys/bluetooth/host/*`.

Originally, all these HCI APIs were strictly internal to the host, i.e. they were in `hci_core.h`. At some point we acknowledged the need to use them from drivers for various purposes (which is what you see here) and because of that we needed to open them up through `include/bluetooth/hci.h`. Unless I'm missing something this patch is reverting that? Also, since these are primarily for testing/hacking/debugging in the app, I'd question a bit the need to make "safe" versions of them. I guess it'd be good to have some more discussion around this.

If your intention is to get something still fixed for 2.1 (I have a feeling this might be the case since @carlescufi pinged me on this PR) I'd suggest to stick to strictly "critical" items, i.e. things which are known to be broken or confusing in existing code. Those will be easier to agree on and get merged.

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: drivers/bluetooth/hci/spi.c (hunk 8 above)
Comment (carlescufi) [reply drivers/bluetooth/hci/spi.c]: I am puzzled by this too. I built a sample for `96b_carbon` which uses `spi.c` and GCC doesn't emit a warning.

Comment (carlescufi) [reply drivers/bluetooth/hci/spi.c]: Ah wait, that's only for BlueNRG. Now I built another sample and I indeed get the error:

```
$ west build -b nucleo_wb55rg samples/bluetooth/beacon/
-- west build: build configuration:
       source directory: /home/carles/src/zephyr/zephyr/samples/bluetooth/beacon
       build directory: /home/carles/src/zephyr/zephyr/build (created)
       BOARD: nucleo_wb55rg (origin: command line)
-- west build: generating a build system
Zephyr version: 2.1.0
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.5", minimum required is "3.4")
-- Selected BOARD nucleo_wb55rg
-- Found west: /home/carles/.local/bin/west (found suitable version "0.6.3", minimum required is "0.6.0")
-- Loading /home/carles/src/zephyr/zephyr/boards/arm/nucleo_wb55rg/nucleo_wb55rg.dts as base
Devicetree configuration written to /home/carles/src/zephyr/zephyr/build/zephyr/include/generated/generated_dts_board.conf
Parsing Kconfig tree in /home/carles/src/zephyr/zephyr/Kconfig
Loaded configuration '/home/carles/src/zephyr/zephyr/boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig'
Merged configuration '/home/carles/src/zephyr/zephyr/samples/bluetooth/beacon/prj.conf'
Configuration saved to '/home/carles/src/zephyr/zephyr/build/zephyr/.config'
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /home/carles/bin/gcc-arm-none-eabi-8-2019-q3-update/bin/arm-none-eabi-gcc
-- Cache files will be written to: /home/carles/.cache/zephyr
-- Configuring done
-- Generating done
-- Build files have been written to: /home/carles/src/zephyr/zephyr/build
-- west build: building application
[1/154] Preparing syscall dependency handling

[58/154] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/bluetooth/hci/ipm_stm32wb.c.obj
/home/carles/src/zephyr/zephyr/drivers/bluetooth/hci/ipm_stm32wb.c: In function 'bt_ipm_set_addr':
/home/carles/src/zephyr/zephyr/drivers/bluetooth/hci/ipm_stm32wb.c:415:8: warning: implicit declaration of function 'hci_cmd_create'; did you mean 'bt_hci_cmd_create'? [-Wimplicit-function-declaration]
  buf = hci_cmd_create(ACI_HAL_WRITE_CONFIG_DATA, sizeof(*param));
        ^~~~~~~~~~~~~~
        bt_hci_cmd_create
/home/carles/src/zephyr/zephyr/drivers/bluetooth/hci/ipm_stm32wb.c:415:6: warning: assignment to 'struct net_buf *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  buf = hci_cmd_create(ACI_HAL_WRITE_CONFIG_DATA, sizeof(*param));
      ^
/home/carles/src/zephyr/zephyr/drivers/bluetooth/hci/ipm_stm32wb.c:431:8: warning: implicit declaration of function 'hci_cmd_send_sync'; did you mean 'bt_hci_cmd_send_sync'? [-Wimplicit-function-declaration]
  err = hci_cmd_send_sync(ACI_HAL_WRITE_CONFIG_DATA, buf, &rsp);
        ^~~~~~~~~~~~~~~~~
        bt_hci_cmd_send_sync
/home/carles/src/zephyr/zephyr/drivers/bluetooth/hci/ipm_stm32wb.c: In function 'bt_ipm_ble_init':
/home/carles/src/zephyr/zephyr/drivers/bluetooth/hci/ipm_stm32wb.c:457:6: warning: assignment to 'struct net_buf *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  buf = hci_cmd_create(ACI_WRITE_SET_TX_POWER_LEVEL, 3);
      ^
[149/154] Linking C executable zephyr/zephyr_prebuilt.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       38624 B       812 KB      4.65%
            SRAM:       11684 B        96 KB     11.89%
           SRAM1:         424 B        10 KB      4.14%
           SRAM2:        2440 B        20 KB     11.91%
        IDT_LIST:         152 B         2 KB      7.42%
[154/154] Linking C executable zephyr/zephyr.elf
```

Comment (joerchan) [reply drivers/bluetooth/hci/spi.c]: @jhedberg @carlescufi  Ok. I made the mistake of thinking that the drivers used the internal header file.

> Also, since these are primarily for testing/hacking/debugging in the app, I'd question a bit the need to make "safe" versions of them. I guess it'd be good to have some more discussion around this.

We are using this to send Vendor Specific HCI commands atleast, maybe it is not the right way? But for that reason I thought it appropriate to create a public version that checked the ready flag.

The HCI drivers cannot use this version however. Since they are called during hci driver open() the flag is not set.

I think we have these options:
1. Revert the commit
2. add hci_driver_cmd_ to hci_driver.h that gives access to the internal functions
3. Add different flag and use bt_hci_cmd_ in the drivers

Thoughs?

Comment (jhedberg) [reply drivers/bluetooth/hci/spi.c]: There are two technical pre-requisites for sending commands:

1. The host must have its structures & threads initialized
2. The HCI driver must have its HCI transport functional on some basic level

For the host, when drv->open() returns it is safe to assume that the transport has been set up, however as long as we're inside open() only the driver knows whether the transport is functional or not.

I'm not really a fan of adding more APIs unless we absolutely need to. To me your vendor extensions are kind of proprietary extensions of the host rather than a layer on top of it, i.e. they could potentially check the host's internal state, like the BT_DEV_READY flag, before calling the HCI APIs.

Comment (joerchan) [reply drivers/bluetooth/hci/spi.c]: @jhedberg Well I'd prefer not to check internal state. But I can use the bt_ready callback to set my own. So that can be handled.
Should I revert the commit then?

Comment (joerchan) [reply drivers/bluetooth/hci/spi.c]: @jhedberg @carlescufi Removed the HCI ready commit.

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
