### PR TITLE
Bluetooth: doc: Add warning for bt_data_parse

### LINKED ISSUE #47676: bt_data_parse is destructive without warning
**Describe the bug**
When calling bt_data_parse, the advertisement data that you pass to it gets destroyed. It get's passed as a net_buf_simple and the data is being removed by the function directly calling net_buf_simple_pull on the data. This makes it so the data becomes unusable in other parts of the function. I could not find any pointers in the documentation that this would render the ad pointer useless.

**To Reproduce**
1. Call bt_data_parse on a received advertisement.
2. Observe that now data is partially or fully missing in the advertisement data buffer.

**Expected behavior**
Either a warning in the documentation that data in the buffer passed will disappear, or that data in the buffer is preserved. Below the relevant documentation
https://docs.zephyrproject.org/latest/connectivity/bluetooth/api/gap.html?highlight=bt_data_parse#c.bt_data_parse

**Impact**
Annoyance, minor loss of development time.

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephyr SDK/nRF Connect SDK
 - Zephyr 3.0.99

### PR DESCRIPTION
**Pull request by jori-nordic**
The fact that the function consumed its argument was not clear previously.

Fixes #47676.

The alternative is to change the API to not consume the data, but as it's
an API change, I suggest we only add the warning.

Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>

### CODE REVIEW

**Comment by Thalley** [comment]
> The alternative is to change the API to not consume the data, but as it's an API change, I suggest we only add the warning.

The API isn't really changing if we just add `net_buf_simple_save(&buf->b, &state);` and `net_buf_simple_restore(&buf->b, &state);` at the beginning or end of the function IMO, but it will change the behavior slightly. 

Given that the current documentation does not state whether or not `bt_data_parse` modifies `ad`, I think we could get away with "fixing" it, rather than just adding the warning. 

We do have a few places in the stack where we actually assume that `bt_data_parse` consumes the data: 
```c
	/* Parse LTV entries */
	bt_data_parse(&ad, ascs_codec_config_store, codec);

	/* Check if all entries could be parsed */
	if (ad.len) {
```

but those are easily fixed I believe. 

The question is: Do we want `bt_data_parse` to consume the data or to be stateless?

**Comment by sjanc** [comment]
netbuf api is altering netbuf it operates on by "definition"
I'm fine with just adding a note and leave save/restore up to user if he wants to use that after calling bt_data_parse

**Review by carlescufi — APPROVED** [review]

**Comment by Thalley** [comment]
> netbuf api is altering netbuf it operates on by "definition" I'm fine with just adding a note and leave save/restore up to user if he wants to use that after calling bt_data_parse

This isn't a `netbuf` API though :) 

I am also fine with leaving the implementation as is and just document the behavior

**Review by sjanc — APPROVED** [review]

File: include/zephyr/bluetooth/bluetooth.h [hunk 1]
```diff
@@ -2049,6 +2049,9 @@ int bt_le_set_rpa_timeout(uint16_t new_rpa_timeout);
  * common scenario is to call this helper on the advertising data
  * received in the callback that was given to bt_le_scan_start().
  *
+ * @warning This helper function will consume `ad` when parsing. The user should
+ *          make a copy if the original data is to be used afterwards
```
Comment (Thalley) [inline include/zephyr/bluetooth/bluetooth.h:2053]: Maybe useful to add references to `net_buf_simple` APIs that can be used for this (clone or the save/restore).

**Review by alwa-nordic — APPROVED** [review]
