### PR TITLE
drivers: GPIO: Microchip: Fix GPIO interrupt enable spurious interrupt

### LINKED ISSUE #34879: mec15xxevb_assy6853: 2 GPIO test failures
**Describe the bug**
Multiple tests are failing on mec15xxevb_assy6853 board under tests/boards/mec15xxevb_assy6853/qspi/ ,  i2c_api/ and tests/drivers/gpio/gpio_api_1pin/

**To Reproduce**
1. twister --hardware-map ~/mec1.file --device-testing -T tests/boards/mec15xxevb_assy6853/qspi/ ,  i2c_api  and 
2. See error

**Expected behavior**
All the tests should pass

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.5.0-3177-gfaf68fb213bc  ***
Running test suite test_spi
===================================================================
START - test_spi_device
I: CS control inhibited (no GPIO device)
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/mec15xxevb_assy6853/qspi/src/main.c:94: test_spi_device: (jedec_id == W25Q128_JEDEC_ID is false)
JEDEC ID doesn't match
FAIL - test_spi_device in 0.20 seconds
===================================================================
START - test_spi_sector_erase
PASS - test_spi_sector_erase in 0.1 seconds
===================================================================
START - test_spi_single_write
PASS - test_spi_single_write in 0.1 seconds
===================================================================
START - test_spi_single_read
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/mec15xxevb_assy6853/qspi/src/main.c:273: test_spi_single_read: (memcmp(buffer_tx, safbuf2, BUF_SIZE) == 0 is false)
Buffer read data is different to write data
FAIL - test_spi_single_read in 0.20 seconds
===================================================================
START - test_spi_dual_read
I: CS control inhibited (no GPIO device)
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/mec15xxevb_assy6853/qspi/src/main.c:341: test_spi_dual_read: (memcmp(buffer_tx, safbuf2, BUF_SIZE) == 0 is false)
Buffer read data is different to write data
FAIL - test_spi_dual_read in 0.23 seconds
===================================================================
START - test_spi_quad_write
I: CS control inhibited (no GPIO device)
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/mec15xxevb_assy6853/qspi/src/main.c:449: test_spi_quad_write: ((spi_status2 & SPI_STATUS2_QE) == SPI_STATUS2_QE is false)
Enable QSPI mode failure
FAIL - test_spi_quad_write in 0.22 seconds
===================================================================
START - test_spi_quad_read
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/mec15xxevb_assy6853/qspi/src/main.c:579: test_spi_quad_read: (ret == 0 is false)
Receive fast read data spi_transceive failure: error -35
FAIL - test_spi_quad_read in 0.18 seconds
===================================================================
START - test_spi_octal_read
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/mec15xxevb_assy6853/qspi/src/main.c:645: test_spi_octal_read: (ret == 0 is false)
Send quad read address spi_transceive failure: error -35
FAIL - test_spi_octal_read in 0.30 seconds
===================================================================
Test suite test_spi failed.
===================================================================
PROJECT EXECUTION FAILED
```
```
DEBUG   - DEVICE: *** Booting Zephyr OS build zephyr-v2.5.0-2732-g5e1502e816d7  ***
DEBUG   - DEVICE: Running test suite i2c_test
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_i2c_pca95xx
DEBUG   - DEVICE: E: Write error: -60
DEBUG   - DEVICE:
DEBUG   - DEVICE: Assertion failed at WEST_TOPDIR/zephyr/tests/boards/mec15xxevb_assy6853/i2c_api/src/main.c:48: test_i2c_pca95xx: (ret == 0 is false)
DEBUG   - DEVICE: Failed to write data to i2c device
DEBUG   - DEVICE: FAIL - test_i2c_pca95xx in 0.28 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: Test suite i2c_test failed.
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: PROJECT EXECUTION FAILED
DEBUG   - run status: mec15xxevb_assy6853/tests/boards/mec15xxevb_assy6853/i2c_api/boards.mec15xxevb_assy6853.i2c failed
```
```
*** Booting Zephyr OS build zephyr-v2.5.0-2839-gb504f8b6a27b  ***
Running test suite gpio_api_1pin_test
===================================================================
START - test_gpio_pin_configure_push_pull
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_pin_configure_push_pull in 0.6 seconds
===================================================================
START - test_gpio_pin_configure_single_ended
Running test on port=GPIO140_176, pin=14
When configured as input test pin value is high
Open Source configuration or Pull Up pin bias is not supported
PASS - test_gpio_pin_configure_single_ended in 0.114 seconds
===================================================================
START - test_gpio_pin_set_get_raw
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_pin_set_get_raw in 0.7 seconds
===================================================================
START - test_gpio_pin_set_get
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_pin_set_get in 0.7 seconds
===================================================================
START - test_gpio_pin_set_get_active_high
Running test on port=GPIO140_176, pin=14
Step 1: Set logical, get logical and physical pin value
Step 2: Set physical, get logical and physical pin value
PASS - test_gpio_pin_set_get_active_high in 0.18 seconds
===================================================================
START - test_gpio_pin_set_get_active_low
Running test on port=GPIO140_176, pin=14
Step 1: Set logical, get logical and physical pin value
Step 2: Set physical, get logical and physical pin value
PASS - test_gpio_pin_set_get_active_low in 0.18 seconds
===================================================================
START - test_gpio_pin_toggle
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_pin_toggle in 0.5 seconds
===================================================================
START - test_gpio_port_set_masked_get_raw
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_port_set_masked_get_raw in 0.7 seconds
===================================================================
START - test_gpio_port_set_masked_get
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_port_set_masked_get in 0.7 seconds
===================================================================
START - test_gpio_port_set_masked_get_active_high
Running test on port=GPIO140_176, pin=14
Step 1: Set logical, get logical and physical port value
Step 2: Set physical, get logical and physical port value
PASS - test_gpio_port_set_masked_get_active_high in 0.20 seconds
===================================================================
START - test_gpio_port_set_masked_get_active_low
Running test on port=GPIO140_176, pin=14
Step 1: Set logical, get logical and physical port value
Step 2: Set physical, get logical and physical port value
PASS - test_gpio_port_set_masked_get_active_low in 0.20 seconds
===================================================================
START - test_gpio_port_set_bits_clear_bits_raw
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_port_set_bits_clear_bits_raw in 0.6 seconds
===================================================================
START - test_gpio_port_set_bits_clear_bits
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_port_set_bits_clear_bits in 0.6 seconds
===================================================================
START - test_gpio_port_set_clr_bits_raw
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_port_set_clr_bits_raw in 0.6 seconds
===================================================================
START - test_gpio_port_set_clr_bits
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_port_set_clr_bits in 0.5 seconds
===================================================================
START - test_gpio_port_toggle
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_port_toggle in 0.5 seconds
===================================================================
START - test_gpio_int_edge_rising
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_int_edge_rising in 0.9 seconds
===================================================================
START - test_gpio_int_edge_falling
Running test on port=GPIO140_176, pin=14
Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/gpio/gpio_api_1pin/src/test_pin_interrupt.c:97: test_gpio_pin_interrupt_edge: (cb_count not equal to cb_count_expected)
Test point 0: Pin interrupt triggered invalid number of times on rising/to active edge
FAIL - test_gpio_int_edge_falling in 0.27 seconds
===================================================================
START - test_gpio_int_edge_both
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_int_edge_both in 0.9 seconds
===================================================================
START - test_gpio_int_edge_to_active
Step 1: Configure pin as active high
Running test on port=GPIO140_176, pin=14
Step 2: Configure pin as active low
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_int_edge_to_active in 0.24 seconds
===================================================================
START - test_gpio_int_edge_to_inactive
Step 1: Configure pin as active high
Running test on port=GPIO140_176, pin=14
Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/gpio/gpio_api_1pin/src/test_pin_interrupt.c:97: test_gpio_pin_interrupt_edge: (cb_count not equal to cb_count_expected)
Test point 0: Pin interrupt triggered invalid number of times on rising/to active edge
FAIL - test_gpio_int_edge_to_inactive in 0.31 seconds
===================================================================
START - test_gpio_int_level_high
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_int_level_high in 0.9 seconds
===================================================================
START - test_gpio_int_level_low
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_int_level_low in 0.9 seconds
===================================================================
START - test_gpio_int_level_active
Step 1: Configure pin as active high
Running test on port=GPIO140_176, pin=14
Step 2: Configure pin as active low
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_int_level_active in 0.24 seconds
===================================================================
START - test_gpio_int_level_inactive
Step 1: Configure pin as active high
Running test on port=GPIO140_176, pin=14
Step 2: Configure pin as active low
Running test on port=GPIO140_176, pin=14
PASS - test_gpio_int_level_inactive in 0.24 seconds
===================================================================
START - test_gpio_pin_toggle_visual
Running test on port=GPIO140_176, pin=14
LED ON
LED OFF
LED ON
LED OFF
PASS - test_gpio_pin_toggle_visual in 6.7 seconds
===================================================================
Test suite gpio_api_1pin_test failed.
===================================================================
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
 - OS: Fedora 29
 - Toolchain: Zephyr SDK 12.4
 - Commit SHA: faf68fb213bc

**Additional context**
Tests were passing before, after bisecting tests started failing after this commit: 5e1502e816d7e33cf104ac526f6567f966b169f8

### PR DESCRIPTION
**Pull request by scottwcpg**
Microchip MEC GPIO hardware can trigger a spurious interrupt when
interrupt detection is set to edge mode especially falling edge mode.
Clearing the status immediately after enabling interrupt detection does
not work because the hardware takes a small number of AHB clocks to
set the status. After interrupt detection enable we spin for a small
number of cycles reading a hardware register to generate delay. By this
time the spurious status is present and cleared before enabling the
interrupt in the GIRQ.

Fixes #34879.

Signed-off-by: Scott Worley <scott.worley@microchip.com>

### CODE REVIEW

**Comment by scottwcpg** [comment]
Tested this fix for the gpio_api_1pin test on a MEC15xx EVB.

**Comment by maksimmasalski** [comment]
Interesting behavior, if to add to the mainline code line `printk("\nmask %d\n", mask);` test will pass too.
Like:
```
if (mode != GPIO_INT_MODE_DISABLED) {
		printk("\nmask %d\n", mask);

		/* We enable the interrupts in the EC aggregator so that the
		 * result can be forwarded to the ARM NVIC
		 */
```

But still, your fix works for mec15xxevb_assy6853 board under tests/boards/mec15xxevb_assy6853/qspi/ , i2c_api/ and tests/drivers/gpio/gpio_api_1pin/ that failed before.
I think your PR fixes #34879

**Review by maksimmasalski — APPROVED** [review]

File: drivers/gpio/gpio_mchp_xec.c [hunk 1]
```diff
@@ -213,6 +217,19 @@ static int gpio_xec_pin_interrupt_configure(const struct device *dev,
 	*current_pcr1 = (*current_pcr1 & ~mask) | pcr1;
 
 	if (mode != GPIO_INT_MODE_DISABLED) {
+		mask = 0u;
+		/* HW takes several clocks to stabilize when edge
+		 * detect is enabled.
+		 */
+		for (int i = 0; i < XEC_GPIO_EDGE_DLY_COUNT; i++) {
```
Comment (mnkp) [inline drivers/gpio/gpio_mchp_xec.c:224]: This looks indeed like a hardware bug. The other, much less likely cause would be the processor reordering access to device registers. The registers are normally placed in Device / Strongly-ordered memory region to guarantee the transaction order but maybe it's worth giving it a try and replacing the delay with a call to `__DMB()`?

Comment (scottwcpg) [reply drivers/gpio/gpio_mchp_xec.c]: @mnkp I tried replacing the loop with __DMB() in the PR and on the MEC172x GPIO driver.  It worked both places.  Updated the PR to use __DMB.

File: drivers/gpio/gpio_mchp_xec.c [hunk 2]
```diff
@@ -13,6 +13,10 @@
 
 #include "gpio_utils.h"
 
+#define XEC_GPIO_EDGE_DLY_COUNT		8
```
Comment (albertofloyd) [inline drivers/gpio/gpio_mchp_xec.c:16]: @scottwcpg I think you can remove debug aids in the final patch

**Comment by albertofloyd** [comment]
@scottwcpg could you elaborate on this change? 
Is this unmasked issues unmasked by test changes or is side-effect from HAL and pinmux updates?

**Comment by scottwcpg** [comment]
@albertofloyd I can cause the failure in the latest main branch my commenting out the work-around.  The edge interrupt test fails due to some HW issue in the MEC GPIO design.  It seems the HW takes time to register(set the GIRQ status bit) the false edge when edge mode is enabled.  Code runs faster and writes the GIRQ source register to clear the spurious status before the HW registers it.  The original delay loop I used or the suggested __DMB() instruction must allow enough time for the HW to set the spurious status before code attempts to clear it.  __DMB() is working on both MEC152x running at 48MHz and MEC172x running at 96MHz.

File: drivers/gpio/gpio_mchp_xec.c (hunk 1 above)
Comment (mnkp) [reply drivers/gpio/gpio_mchp_xec.c]: Interesting, I actually didn't expect `__DMB()` would work. GPIO and interrupt controller modules should be placed in Device / Strongly-ordered memory region. 

Such erroneous behavior could be caused by misconfigured MPU but MEC15xx EVB has Cortex M4, without MPU. So it does look like a hardware bug. @scottwcpg you work for Microchip, don't you? Could you check the documentation, contact hardware engineers and vefify which module is causing problems. If GPIO / interrupt controller registers are not placed in Device / Strongly-ordered memory region we're likely to have more bugs in the driver's code.

Comment (scottwcpg) [reply drivers/gpio/gpio_mchp_xec.c]: @mnkp I was also surprised by __DMB working especially on the MEC172x running at 96MHz.  All the Microchip peripherals are on AHB in the 0x4000_0000 to 0x4FFFF_FFFF range which is the "System Bus" in ARM terminology.  ARM docs state the write buffer is used for DCode and System bus.

**Comment by mnkp** [comment]
> The edge interrupt test fails due to some HW issue in the MEC GPIO design. It seems the HW takes time to register(set the GIRQ status bit) the false edge when edge mode is enabled. Code runs faster and writes the GIRQ source register to clear the spurious status before the HW registers it.

Since `__DMB()` is fixing the issue the likely root cause of the problem is different. ARM processors have a pipeline that can reorder AHB transactions performed by the processor. That is OK if we're writing/reading normal memory. If we're writing to two different memory locations and then continue with some other stuff it doesn't matter which memory location will be physically written first. The situation is very different if we access memory mapped peripherals. In this case order of the transactions matters. That's why all the peripheral registers are normally located in the so called Device / Strongly-ordered memory region. It seems like in case of this SoC at least one of the peripherals is not.

The only thing `__DMB()` does is to ensure that write to the register behind the following line of code
```
*current_pcr1 = (*current_pcr1 & ~mask) | pcr1;
```
happens before write to the register behind the following line of code
```
MCHP_GIRQ_SRC_CLR(config->girq_id, pin);
```
It can still, and likely is, be performed right away, one after another. That is `__DMB()` doesn't introduce a delay per se, just enforces the correct sequence of events.

If some of the peripherals are indeed not located in Device / Strongly-ordered memory region this is a serious issue and we're likely to see more bugs. Since we haven't seen those bugs so far probably there is something else in play but at the moment I don't see another explanation why `__DMB()` would fix the issues. In any case this problem should be investigated a bit deeper.

File: drivers/gpio/gpio_mchp_xec.c (hunk 2 above)
Comment (maksimmasalski) [reply drivers/gpio/gpio_mchp_xec.c:16]: @albertofloyd Where to find info about XEC_GPIO_EDGE_DLY_COUNT ?

**Comment by maksimmasalski** [comment]
@scottwcpg How you calculated value `0x40080150u` ?

**Comment by maksimmasalski** [comment]
@scottwcpg I tried to put instead of `__DMB()` other two barrier instructions in the Cortex-M3 like `__ISB()` and `__DSB() `. In both cases all tests passed successfully. Why necessary to use exactly `__DMB()`?
I found in Cortex M3 Guide that info:
<html>
<body>

DMB | Data Memory Barrier; ensures that all memory accesses are completed before new memory access is committed
-- | --
DSB | Data Synchronization Barrier; ensures that all memory accesses are completed before next instruction is executed
ISB | Instruction Synchronization Barrier; flushes the pipeline and ensures that all previous instructions are completed before executing new instructions


</body>
</html>

**Comment by mnkp** [comment]
> Why necessary to use exactly `__DMB()`?

`__DMB()` is the least intrusive of the three and does the job so there is no need for the more heavy weight options.

**Comment by mnkp** [comment]
@scottwcpg I've updated the PR description to state
```
Fixes #34879.
```
This is a standard way to link the PR with the issue. You may update the commit message. We place such line typically towards the end of the commit message.

File: drivers/gpio/gpio_mchp_xec.c (hunk 1 above)
Comment (ravinprv) [reply drivers/gpio/gpio_mchp_xec.c]: hi all, see below feedback from Hardware team at mchp.

1. mec52x and mec172x GPIO logic requires 2 synchronization stages + some extra clocks once an event is detected to clear out the internal logic. This will take ~8 system clock cycles (it can take less).
    we automatically disable clocking for gpio block when there’s no activity and then automatically re-enable clocks when the async detectors capture changes on the pin. This has few clocks delay.
2. It will always trigger an edge detect when turned on if the pin state is the level of the end condition (falling edge = pin state 0; rising edge = pin state 1). It will sometimes trigger an edge detect on any GPIO IRQ configuration change.
3.  dmb instruction has no impact as all ARM AHB accesses stall the processor until completed which gives a large delay between adjacent AHB accesses. 
4. above restriction are applicable only for GPIO block in mec152x device and mec172x device. We need to have delay between write to control register and clearing interrupt status register before enabling GPIO edge detection interrupt.

**Review by albertofloyd — APPROVED** [review]

**Review by yerabolu — COMMENTED** [review]
verified the fix on the microchip board and test passes.

**Review by yerabolu — APPROVED** [review]

File: drivers/gpio/gpio_mchp_xec.c (hunk 1 above)
Comment (mnkp) [reply drivers/gpio/gpio_mchp_xec.c]: Considering the above reply I believe we need to change the way the fix is implemented. Instead of using __DMB instruction go back to a loop which adds a short delay.

Comment (scottwcpg) [reply drivers/gpio/gpio_mchp_xec.c]: @mnkp I agree. Since the PR's for both chips have been merged. I will create a new PR updating both drivers to use the delay loop.
