### PR TITLE
drivers/nrf_qspi: fix devicetree opcode references 

### LINKED ISSUE #28635: nrf: qspi: devicetree opcode properties are ignored
#24378 changed the way a property that was accessed via its enum value was referenced, so the `readoc` property was checked as if it were named `readoc-enum`. The effect is that the devicetree readoc and writeoc properties are being ignored.

### PR DESCRIPTION
**Pull request by sw**
This makes the driver compile for nRF5340 and it seems to work, but I did not do extensive tests.

I am not at all confident in my understanding of the Devicetree, so I may have gotten something wrong.

To make the driver work on nRF5340, there are changes required to the DTS files:

```
	soc {
		peripheral@50000000 {
			qspi: qspi@2B000 {
				compatible = "nordic,nrf-qspi";
				#address-cells = <1>;
				#size-cells = <0>;
				reg = <0x2B000 0x1000>;
				interrupts = <43 1>;
				status = "disabled";
				label = "QSPI";
			};
		};
	};
```

```
&qspi {
	status = "okay";
	sck-pin = <17>;
	io-pins = <13>, <14>, <15>, <16>;
	csn-pins = <18>;
	mx25r64: mx25r6435f@0 {
		compatible = "nordic,qspi-nor";
		reg = <0>;
		writeoc = "pp4io";
		readoc = "read4io";
		sck-frequency = <8000000>;
		label = "MX25R64";
		jedec-id = [c2 28 17];
		size = <67108864>;
		has-be32k;
		has-dpd;
		t-enter-dpd = <10000>;
		t-exit-dpd = <35000>;
	};
};
```
And to Kconfig somewhere(?):
```
config SOC_NRF5340_CPUAPP
	select HAS_HW_NRF_QSPI
```
Again I'm not sure if I got this right. Can anyone from Nordic or a Devicetree expert try to implement this for nRF5340? Thanks.

Fixes  #28635

### CODE REVIEW

File: drivers/flash/nrf_qspi_nor.c [hunk 1]
```diff
@@ -189,7 +189,7 @@ static inline nrf_qspi_frequency_t get_nrf_qspi_prescaler(uint32_t frequency)
 	if (frequency < 2000000UL) {
 		ret = -EINVAL;
 	} else if (frequency >= 32000000UL) {
-		ret = NRF_QSPI_FREQ_32MDIV1;
+		ret = NRF_QSPI_FREQ_DIV1;
```
Comment (pabigot) [inline drivers/flash/nrf_qspi_nor.c:192]: Is this change necessary?  AFAICT 

    #define NRF_QSPI_FREQ_32MDIV1  NRF_QSPI_FREQ_DIV1

in the HAL.

File: drivers/flash/nrf_qspi_nor.c [hunk 2]
```diff
@@ -403,16 +403,16 @@ static inline void qspi_fill_init_struct(nrfx_qspi_config_t *initstruct)
 #endif
 
 	/* Configure Protocol interface */
-#if DT_INST_NODE_HAS_PROP(0, readoc_enum)
+#if DT_INST_NODE_HAS_PROP(0, readoc)
```
Comment (pabigot) [inline drivers/flash/nrf_qspi_nor.c:406]: OK, this change is absolutely necessary, and is a bug introduced by #24378 if it wasn't broken already.  The effect is that the devicetree `readoc` and `writeoc` properties are being ignored.

Possibly we should try to get this into 2.4.0.  @ioannisg @carlescufi

**Review by pabigot — COMMENTED** [review]
If the rename of the frequency isn't required I'd rather not have that changed.  If it is we should perhaps pull  out the other change.

File: drivers/flash/nrf_qspi_nor.c (hunk 2 above)
Comment (ioannisg) [reply drivers/flash/nrf_qspi_nor.c:406]: Will need a review from @nvlsianpu  ,right?

Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c:406]: Presumably.  Why doesn't github automatically add maintainers?  nvm.

File: drivers/flash/nrf_qspi_nor.c (hunk 1 above)
Comment (sw) [reply drivers/flash/nrf_qspi_nor.c:192]: This is only defined for NRF52_SERIES, not for nRF53. I understood this as a deprecated alias.

**Review by pabigot — APPROVED** [review]
Works on nRF52, and I've confirmed the in-tree version does ignore the opcode settings.

Thanks for finding this.

File: drivers/flash/nrf_qspi_nor.c (hunk 1 above)
Comment (sw) [reply drivers/flash/nrf_qspi_nor.c:192]: Looking at the clock tree on the nRF53, my change is likely wrong. It will compile on both nRF52 and nRF53, but give wrong dividers on the latter.

It seems that on nRF53, the QSPI is clocked from HFCLK192M which is by default divided by 4, so 48MHz.

get_nrf_qspi_prescaler would need to be adapted specifically for nRF53.

Comment (pabigot) [reply drivers/flash/nrf_qspi_nor.c:192]: OK.  Then please take that out, so we can at least fix the opcode issue.  We can address nRF53 support in 2.5.0.

**Review by pabigot — CHANGES_REQUESTED** [review]
Please squash the commits.  We don't need to see the add and then the remove.

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines
https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow

**Comment by pabigot** [comment]
> https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines
> https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow

Yes, the commit message should be something like:
```
drivers: nrf_qspi: fix devicetree opcode references

The condition used to detect presence of optional devicetree
properties that specify read and write opcodes was inadvertently
changed to something that will never be true.  Update the check and
the property extraction to restore the original behavior.
```
plus signed-off-by.

**Comment by sw** [comment]
Sorry about the mess, I was only working from the Github web interface.

**Comment by pabigot** [comment]
> Sorry about the mess, I was only working from the Github web interface.

OK.  One last change is the signed-off-by line required for compliance:

    git commit --amend -C HEAD -s
    git push +patch-1

or something like that.

**Review by pabigot — APPROVED** [review]

**Comment by pabigot** [comment]
@nvlsianpu please re-check

**Review by nvlsianpu — APPROVED** [review]
