### PR TITLE
net: context: Reset peer address on connect with AF_UNSPEC 

### LINKED ISSUE #94210: Connect: unable to disconnect a datagram socket
### Describe the bug

I am trying to disconnect a datagram socket the same way that is use on Linux (see [man connect](https://man7.org/linux/man-pages/man2/connect.2.html)) but I get the following error.
```
ASSERTION FAIL [addr->sa_family == net_context_get_family(context)] @ WEST_TOPDIR/zephyr/subsys/net/ip/net_context.c:1361
      Family mismatch 0 should be 1
```

### Regression

- [ ] This is a regression.

### Steps to reproduce

1. mkdir test; cd test
2. copy the following to src/mainc.
```
#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(Main, LOG_LEVEL_INF);

#include <zephyr/kernel.h>
#include <stdio.h>
#include <zephyr/posix/sys/socket.h>

int main() {
        int socket1 = socket(AF_INET, SOCK_DGRAM, 0);
        if (socket1 < 0) {
                LOG_ERR("Creation of socket 1 failed");
                return -1;
        }
        LOG_INF("Socket1 was successfully created");
        struct in_addr sin_addr;
        sin_addr.s_addr = 0;
        struct sockaddr_in addr_in;
        addr_in.sin_family = AF_INET;
        addr_in.sin_port = 4000;
        addr_in.sin_addr = sin_addr;

        int res = bind(socket1, &addr_in, sizeof(struct sockaddr_in));
        if (res < 0) {
                LOG_ERR("Binding socket1 failed with %d\n", res);
                return -1;
        }
        LOG_INF("Socket1 was successfully binded");
        int socket2 = socket(AF_INET, SOCK_DGRAM, 0);
        if (socket2 < 0) {
                LOG_ERR("Creation of socket 2 failed");
                return -1;
        }
        LOG_INF("Socket2 was succesfully created");
        addr_in.sin_port = 4001;

        res = bind(socket2, &addr_in, sizeof(struct sockaddr_in));
        if (res < 0) {
                LOG_ERR("Binding socket2 failed with %d\n", res);
                return -1;
        }
        LOG_INF("Socket2 was successfully binded");

        res = connect(socket1, &addr_in, sizeof(struct sockaddr_in));
        if (res < 0) {
                LOG_ERR("Socket1 wasn't able to connect");
                return -1;
        }
        LOG_INF("Socket1 was successfully connected");

        struct sockaddr disconnect;
        disconnect.sa_family = AF_UNSPEC;

        res = connect(socket1, &disconnect, sizeof(struct sockaddr));
        if (res < 0) {
                LOG_ERR("Socket1 failed to disconnect");
                return -1;
        }
        LOG_INF("Socket1 was successfully");
        return 0;
}
```
3. copy the following to CMakeLists.txt
```
cmake_minimum_required(VERSION 3.20.0)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(test)

target_sources(app PRIVATE src/main.c)
```
4. copy the following to prj.conf
```
CONFIG_NETWORKING=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_IPV4=y
CONFIG_POSIX_API=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_DRIVERS=y
CONFIG_NET_LOOPBACK=y
CONFIG_POSIX_TIMERS=y
CONFIG_XOPEN_STREAMS=y
CONFIG_NET_LOG=y
CONFIG_LOG=y
```
5. build and flash on your card

### Relevant log output

```shell
*** Booting Zephyr OS build v4.2.0-rc1-26-gb15404f99834 ***
[00:00:00.000,000] <inf> Main: Socket1 was successfully created
[00:00:00.000,000] <inf> Main: Socket1 was successfully binded
[00:00:00.000,000] <inf> Main: Socket2 was succesfully created
[00:00:00.000,000] <inf> Main: Socket2 was successfully binded
[00:00:00.000,000] <inf> Main: Socket1 was successfully connected
[00:00:00.000,000] <err> Main: Socket1 failed to disconnect
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: WSL (Ubuntu 24.02)
- SDK: Zephyr SDK 0.17.0
- Zephyr commit: b15404f998346c65952ffa42ca6f5194ec71065f

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rlubos**
As per POSIX (newer versions of the standard), for non-connection-mode sockets the peer address should be reset if AF_UNSPEC family type is provided to the connect() call:
  "If the sa_family member of address is AF_UNSPEC, the socket's peer address shall be reset."

Fix this, one minor issue found in connection layer related to peer address resetting, and add a test for this case.

Fixes #94210

### CODE REVIEW

File: subsys/net/ip/connection.c [hunk 1]
```diff
@@ -970,12 +970,12 @@ enum net_verdict net_conn_input(struct net_pkt *pkt,
 			/* Is the candidate connection matching the packet's TCP/UDP
 			 * address and port?
 			 */
-			if (net_sin(&conn->remote_addr)->sin_port &&
+			if ((conn->flags & NET_CONN_REMOTE_PORT_SPEC) &&
```
Comment (pdgendt) [inline subsys/net/ip/connection.c]:
```suggestion
			if ((conn->flags & NET_CONN_REMOTE_PORT_SPEC) != 0U &&
```

File: subsys/net/ip/connection.c [hunk 2]
```diff
@@ -970,12 +970,12 @@ enum net_verdict net_conn_input(struct net_pkt *pkt,
...
 			    net_sin(&conn->remote_addr)->sin_port != src_port) {
 				continue; /* wrong remote port */
 			}
 
-			if (net_sin(&conn->local_addr)->sin_port &&
+			if ((conn->flags & NET_CONN_LOCAL_PORT_SPEC) &&
```
Comment (pdgendt) [inline subsys/net/ip/connection.c]:
```suggestion
			if ((conn->flags & NET_CONN_LOCAL_PORT_SPEC) != 0U &&
```

**Review by pdgendt — DISMISSED** [review]
Some usual nits

File: subsys/net/ip/connection.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/ip/connection.c]: Thanks, fixed those two and others, and added mention of this MISRA alignment in commit msg.

**Review by pdgendt — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
