### PR TITLE
crypto: mbedtls_shim: Fix concurrency, leaks, and AEAD output

### LINKED ISSUE #98956: Crypto mbedTLS Shim: Critical concurrency, resource leak, and AEAD output bugs
### Describe the bug

This issue reports several critical bugs related to **thread safety, resource management, and correctness** in the mbedTLS crypto shim layer:

1. **Concurrency and Deadlock:**
  
  - **Mutex Leak:** The `mtls_sessions_lock` was **not reliably released** on failure paths in `mtls_get_unused_session_index`, creating a **deadlock risk** in multi-threaded environments.
    
  - **Unprotected Flag:** The `in_use` flag was modified in free functions **without mutex protection**, leading to potential **race conditions**.
    
2. **Resource Leaks:**
  
  - **Setup Failure Leak:** Contexts were **not properly freed** in `mtls_session_setup()` when key initialization failed, resulting in memory/resource leaks.
    
  - **Incorrect Free Logic:** The `if/else` logic in `mtls_session_free()` was faulty, causing the **wrong context to be freed** or preventing cleanup entirely in certain scenarios.
    
3. **Cipher Integrity (AEAD):**
  
  - **Incorrect Plaintext Length:** Erroneous lines in the **CCM and GCM decryption functions** caused the plaintext output length to be **over-reported**, which can lead to buffer overruns or incorrect data handling by the calling application.

**Area:** Subsystems, Crypto, mbedTLS, Thread Safety

### Regression

- [ ] This is a regression.

### Steps to reproduce

The bugs are primarily logic errors in resource management and thread synchronization.

> **Write:**
> 
> 1. **Concurrency/Deadlock:** Analyze the error paths in `mtls_get_unused_session_index` and `mtls_session_free` to confirm inadequate mutex handling on failure or when updating the `in_use` flag. Run concurrent crypto operations to risk triggering a deadlock.
>   
> 2. **Resource Leaks:** Induce key initialization failure in `mtls_session_setup()` and verify that resources (like context structures) are not properly freed, leading to a resource leak.
>   
> 3. **AEAD Output:** Analyze the CCM and GCM decryption functions to identify the lines that incorrectly increment the output length, leading to an over-reported plaintext size.
>

### Relevant log output

```shell

```

### Impact

Not sure

### Environment

- **OS:** Windows WSL
  
- **Toolchain:** Zephyr SDK
  
- **Component:** `mbedtls_shim` (Crypto)

### Additional Context

Fix Proposal is presented in the following PR: #98710

### PR DESCRIPTION
**Pull request by kaabia**
Fixes <https://github.com/zephyrproject-rtos/zephyr/issues/98956>

This patch addresses critical bugs related to thread safety, resource
management, and correct AEAD behavior in the mbedTLS crypto shim.

1. Concurrency and Deadlock:
   - **Fix session mutex handling:** Ensure the `mtls_sessions_lock` is
     always released in `mtls_get_unused_session_index` on failure
     to prevent deadlocks.
   - **Protect `in_use` flag:** Added mutex protection when setting
     `in_use = false` in free functions.

2. Resource Leaks:
   - **Cleanup on setup failure:** Added calls to `mbedtls_*_free()`
     in `mtls_session_setup()` when key initialization fails.
   - **Free logic fix:** Corrected `if/else` structure in
     `mtls_session_free()` to ensure the correct context is freed.

3. Cipher Integrity:
   - **Fix AEAD output length:** Removed erroneous lines in CCM and GCM
     decryption functions that over-reported the plaintext length.
   - **Logging:** Corrected "encrypt" log messages to "decrypt."

### CODE REVIEW

File: drivers/crypto/crypto_mtls_shim.c [hunk 1]
```diff
@@ -450,14 +454,17 @@ static int mtls_session_free(const struct device *dev, struct cipher_ctx *ctx)
 
 	if (mtls_session->mode == CRYPTO_CIPHER_MODE_CCM) {
 		mbedtls_ccm_free(&mtls_session->mtls_ccm);
+	}
```
Comment (yvesll) [inline drivers/crypto/crypto_mtls_shim.c]: This may cause a compile error if gcm not enabled. And may I ask why separate the node check in two independent when gcm enabled?

Comment (kaabia) [reply drivers/crypto/crypto_mtls_shim.c]: You are absolutely right! Good catch, thank you.

Fixed !

**Review by yvesll — APPROVED** [review]
LGTM, please remeber to update the license header.

File: drivers/crypto/crypto_mtls_shim.c [hunk 2]
```diff
@@ -588,7 +594,9 @@ static int mtls_hash_session_free(const struct device *dev, struct hash_ctx *ctx
 	} else {
 		mbedtls_sha512_free(&mtls_session->mtls_sha512);
 	}
+	k_mutex_lock(&mtls_sessions_lock, K_FOREVER);
 	mtls_session->in_use = false;
+	k_mutex_unlock(&mtls_sessions_lock);
```
Comment (ceolin) [inline drivers/crypto/crypto_mtls_shim.c:599]: you are protecting `mtls_session->in_use` here but not doing it in `mtls_session_setup` error handling .. lines 376, 396 ...

**Review by ceolin — COMMENTED** [review]
Changes look good, just check the comment about error handling in `mtls_session_setup`

File: drivers/crypto/crypto_mtls_shim.c (hunk 2 above)
Comment (kaabia) [reply drivers/crypto/crypto_mtls_shim.c]: Good catch! I missed protecting those writes with the mutex in the error paths. I've now applied the lock/unlock around `mtls_sessions[ctx_idx].in_use = false` for consistency and thread safety.

Thank you for the detailed review!

**Comment by jhedberg** [comment]
@ceolin is this something that should be a blocker? I'm not really familiar with this area, however on a general level this looks like it could use splitting into multiple commits.

**Comment by cfriedt** [comment]
@ceolin - this will need your approval. It seems like it could be categorized as a release blocker. @valeriosetti - any thoughts?

**Comment by jhedberg** [comment]
@kaabia arguably this should be split up into three commits - one for each of your bulletpoints in the description

**Review by ceolin — DISMISSED** [review]

**Review by valeriosetti — CHANGES_REQUESTED** [review]
I only find one possible improvement. However being preexisting I can live with it if we say that this PR is mandatory for the 4.3 release.

File: drivers/crypto/crypto_mtls_shim.c [hunk 3]
```diff
@@ -372,7 +372,10 @@ static int mtls_session_setup(const struct device *dev,
 		if (ret) {
 			LOG_ERR("AES_ECB: failed at setkey (%d)", ret);
 			ctx->ops.block_crypt_hndlr = NULL;
+			k_mutex_lock(&mtls_sessions_lock, K_FOREVER);
 			mtls_sessions[ctx_idx].in_use = false;
+			k_mutex_unlock(&mtls_sessions_lock);
+			mbedtls_aes_free(aes_ctx);
```
Comment (valeriosetti) [inline drivers/crypto/crypto_mtls_shim.c]: Is it really required to have all these `mtls_sessions[ctx_idx].in_use = false;` in this function since it's already done in `mtls_session_free`?
For hashes the session is only freed in `mtls_hash_session_free`

Comment (valeriosetti) [reply drivers/crypto/crypto_mtls_shim.c]: @ceolin what do you think about this?

Comment (kaabia) [reply drivers/crypto/crypto_mtls_shim.c]: Hello @valeriosetti,
You are raising an interresting point!
Do you confirm that the mtls_*_session_free is called even when mtls_*_session_setup fails  and not only at the end of a successfull setup !

**Review by jhedberg — APPROVED** [review]

**Review by valeriosetti — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Review by yvesll — APPROVED** [review]
