### PR TITLE
dts: bindings: Fix NXP USB bindings

### LINKED ISSUE #50506: nxp,mcux-usbd devicetree binding issues
**Describe the bug**

The point of a  devicetree binding is to describe hardware and its initial configuration. We have carved out a few exceptions for driver-specific property names prefixed with `zephyr,`. However, we should not be designing devicetree bindings to cater to the software requirements of vendor HALs.

This USB device driver binding has a name that seems to specifically refer to the HAL itself, not the actual hardware. It also has problematic properties, such as `usb-controller-index`, added in 3a7c719fb45ea33f35a6464c8bbaa736ab6fc8cb.

**Expected behavior**

Devicetree bindings that reflect the hardware, not the software. Removal of this binding and replacement with individual bindings for the IP blocks in question, as many as needed. Removal of HAL-specific configuration properties.

### PR DESCRIPTION
**Pull request by decsny**
NXP USB bindings were combined into one binding and using a property corresponding to HAL enums which is improper use of devicetree. This PR takes an approach that is uglier in the driver but that is more in line with how DT should be used. 

Fixes #50506.

### CODE REVIEW

**Review by tmon-nordic — DISMISSED** [review]

File: drivers/usb/device/usb_dc_mcux.c [hunk 1]
```diff
@@ -68,7 +71,35 @@ static void usb_isr_handler(void);
...
 					(USB_EP_GET_DIR(ep) >> 7))
 #define NUM_OF_EP_MAX		(DT_INST_PROP(0, num_bidir_endpoints) * 2)
-#define CONTROLLER_ID		(DT_INST_ENUM_IDX(0, usb_controller_index))
+
+#define COUNT_INST(n) 1 +
+#define NUM_INSTS (DT_INST_FOREACH_STATUS_OKAY(COUNT_INST) 0)
+BUILD_ASSERT(NUM_INSTS <= 1, "Only one USB device supported");
+
+/* Controller ID is for HAL usage */
+#if defined(CONFIG_SOC_SERIES_IMX_RT5XX) || \
```
Comment (danieldegrasse) [inline drivers/usb/device/usb_dc_mcux.c:80]: For this SOC specific section- could we use an approach like this?

```
/* LPC3511 IP */
#ifdef CONFIG_USB_DC_NXP_LPCIP3511
#if DT_INST_ENUM_HAS_VALUE(0, maximum_speed, high_speed)
#define CONTROLLER_ID kUSB_ControllerLpcIp3511Hs0
#else
#define CONTROLLER_ID kUSB_ControllerLpcIp3511Hs0
#endif

/* EHCI IP */
#ifdef CONFIG_USB_DC_NXP_EHCI
#define CONTROLLER_ID kUSB_ControllerEhci##DT_INST_PROP(0, index)
#endif
```
Not sure what your thoughts on this are

Comment (decsny) [reply drivers/usb/device/usb_dc_mcux.c:80]: Introducing an index property defeats the purpose of solving the issue linked since we are once again putting things in DT to satisfy HAL enum names. Also we had a similar discussion on S32 PRs before and decided to avoid putting index numbers in DT to satisfy HAL arrays.

File: drivers/usb/device/usb_dc_mcux.c [hunk 2]
```diff
@@ -68,7 +71,35 @@ static void usb_isr_handler(void);
 #define EP_ABS_IDX(ep)		(USB_EP_GET_IDX(ep) * 2 + \
 					(USB_EP_GET_DIR(ep) >> 7))
 #define NUM_OF_EP_MAX		(DT_INST_PROP(0, num_bidir_endpoints) * 2)
-#define CONTROLLER_ID		(DT_INST_ENUM_IDX(0, usb_controller_index))
+
+#define COUNT_INST(n) 1 +
+#define NUM_INSTS (DT_INST_FOREACH_STATUS_OKAY(COUNT_INST) 0)
```
Comment (jfischer-no) [inline drivers/usb/device/usb_dc_mcux.c:76]: Why not use `DT_NUM_INST_STATUS_OKAY(compat)`?

Comment (decsny) [reply drivers/usb/device/usb_dc_mcux.c:76]: because my brain did not house this knowledge until now, thanks

File: dts/bindings/usb/nxp,lpcip3511.yaml [hunk 3]
```diff
@@ -0,0 +1,8 @@
+# Copyright 2023 NXP
+# SPDX-License-Identifier: Apache-2.0
+
+description: NXP EHCI USB device mode
```
Comment (mbolivar-ampere) [inline dts/bindings/usb/nxp,lpcip3511.yaml:4]: Copy/paste error

File: modules/hal_nxp/usb/usb_device_config.h [hunk 4]
```diff
@@ -39,7 +39,13 @@
 /* Whether device is self power. 1U supported, 0U not supported */
 #define USB_DEVICE_CONFIG_SELF_POWER (1U)
 
-#define DT_DRV_COMPAT nxp_mcux_usbd
+#if DT_HAS_COMPAT_STATUS_OKAY(nxp_lpcip3511)
```
Comment (mbolivar-ampere) [inline modules/hal_nxp/usb/usb_device_config.h:42]: I'm assuming you are absolutely sure it will always only ever be one or the other. If so, feel free to resolve this comment.

If not, can you add a BUILD_ASSERT that the devicetree does not have nodes with both compatibles in it, just to document the assumption?

Something like `BUILD_ASSERT(DT_NUM_INST_STATUS_OKAY(nxp_lpcip3511) + DT_NUM_INST_STATUS_OKAY(nxp_ehci), ...)`.

**Review by mbolivar-ampere — COMMENTED** [review]
Thanks for this cleanup. I noticed one typo and have one question. But this LGTM otherwise.

**Review by jfischer-no — APPROVED** [review]

File: drivers/usb/device/usb_dc_mcux.c (hunk 1 above)
Comment (danieldegrasse) [reply drivers/usb/device/usb_dc_mcux.c:79]: I don't like the solution, but I see a way we could avoid the SOC specific Kconfig definitions here without an index property- since the `CONTROLLER_ID` value is used at runtime, we could define a function to get the controller ID based on the base address of the controller.

Something like this:
```
/* Controller ID is for HAL usage */
/* LPC3511 IP */
#ifdef CONFIG_USB_DC_NXP_LPCIP3511
static usb_controller_index_t mcux_usb_controller_enum(void)
{
        return DT_INST_ENUM_HAS_VALUE(0, maximum_speed, high_speed) ?
                kUSB_ControllerLpcIp3511Hs0 :
                kUSB_ControllerLpcIp3511Fs0
}
#endif

/* EHCI IP */
#ifdef CONFIG_USB_DC_NXP_EHCI
static usb_controller_index_t mcux_usb_controller_enum(void)
{
/* This section is pulled from the MCUX SDK HAL driver for the ECHI, so the USBHS_BASE_ADDRS definition should
 * exist for any SOC with ECHI IP
 */
#if defined(USBHS_STACK_BASE_ADDRS)
        uint32_t base_addrs[] = USBHS_STACK_BASE_ADDRS;
#else
        uint32_t base_addrs[] = USBHS_BASE_ADDRS;
#endif
        return DT_INST_REG_ADDR(0) == base_addrs[0] ?
                kUSB_ControllerEhci0 :
                kUSB_ControllerEhci1;
}
#endif
```

We would then call `mcux_usb_controller_enum` in the `usb_dc_attach` function to get the controller ID value.

Comment (decsny) [reply drivers/usb/device/usb_dc_mcux.c:79]: It is a good idea but there is no guarantee that this pattern holds for future SOCs so I don't see the advantage of making this over-complicated. I would rather maintain just this list of things per SOC rather than do these gymnastics with every new great idea for an api change the HAL comes up with for every new release. For example, there could be an SOC with two instances of LPC3511 which this doesn't account for because there might be a case where only the index 1 is enabled. And there could be an SOC where the HAL adds yet another random name of the array like they have already done with USBHS_STACK_BASE_ADDRS vs USBHS_BASE_ADDRS. And sometimes the HAL puts a random 0 in the first index of USB_BASE_ADDRS which would break things. I don't think having the SOC ifdefs is really adding any more technical debt than this PR is solving, someone enabling an SOC already currently has to figure out which hal enum corresponds to the modules on the chip, the only difference is now putting it in this driver file instead of the devicetree.

If we really want a better solution it has to come from the SDK itself is my opinion. Either that or make the driver zephyr native as the usb_dc_kinetis is, but both of those things are outside the scope of this PR which is just a quick fix of the abuse of devicetree.

Comment (danieldegrasse) [reply drivers/usb/device/usb_dc_mcux.c:79]: > It is a good idea but there is no guarantee that this pattern holds for future SOCs so I don't see the advantage of making this over-complicated

I expect this pattern should hold for new SOCs unless the HAL driver itself is modified. The code in the ECHI HAL driver for determining the base address to use for the USB IP looks like this:
```
#if defined(USBHS_STACK_BASE_ADDRS)
    uint32_t ehci_base[] = USBHS_STACK_BASE_ADDRS;
#else
    uint32_t ehci_base[] = USBHS_BASE_ADDRS;
#endif
....
ehciState->registerBase = (USBHS_Type *)ehci_base[controllerId - (uint8_t)kUSB_ControllerEhci0];
```

So we *should* always be able to determine the correct controller ID from the base address with something like this:

```
#if defined(USBHS_STACK_BASE_ADDRS)
        uint32_t base_addrs[] = USBHS_STACK_BASE_ADDRS;
#else
        uint32_t base_addrs[] = USBHS_BASE_ADDRS;
#endif
for (uint8_t i = 0; i < ARRAY_SIZE(base_addrs); i++) {
	if (base_addrs[i] == DT_INST_REG_ADDR(0)) {
		return kUSB_ControllerEhci0 + i;
}
```

> And sometimes the HAL puts a random 0 in the first index of USB_BASE_ADDRS which would break things. 

If you look at the RT1052, which does this- the `USBHS_STACK_BASE_ADDRS` macro is also defined with the correct array for the ECHI driver. So I'm not sure this would be an issue, since we'd just use the `USBHS_STACK_BASE_ADDRS` definition.

The core thing I want to avoid here is a growing ladder of `#ifdef` blocks for each SOC NXP enables with this driver. Ideally a developer should be able to determine the type of IP block an SOC is using for USB, and the driver should compile and work with it.

Comment (decsny) [reply drivers/usb/device/usb_dc_mcux.c:79]: I have said why I disagree and my opinion has not changed. Additionally, you are proposing runtime overhead for something that can be determined at compile time. And as you are pointing out, trying to make this more and more generic just leads to more and more runtime overhead. I don't think there is any point to attempt to optimize this here with these complications when we know the most optimal fix is going to come from the SDK and remove the need from any of this. I'm not changing this in the PR.

Comment (danieldegrasse) [reply drivers/usb/device/usb_dc_mcux.c:79]: Understood. At the end of the day, this fixes the issue. I don't particularly like the approach, but I'm not going to block over it.

**Review by tmon-nordic — APPROVED** [review]
