### PR TITLE
tests/workq/work: KERNEL_COHERENCE fixups

### LINKED ISSUE #33898: intel_adsp_cavs15: running testcases failed tests/kernel/workq/work on adsp
**Describe the bug**
tests/kernel/workq/work run failed on adsp

**To Reproduce**
1. twister -p intel_adsp_cavs15 --device-testing -T tests/kernel/workq/work --west-flash="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh,/home/ztest/work/zephyrproject/modules/audio/sof/keys/otc_private_key.pem,/home/ztest/work/zephyrproject/modules/audio/sof/zephyr/ext/rimage/config,/home/ztest/work/zephyrproject/modules/audio/sof/zephyr/ext/rimage/build/rimage" --device-serial-pty="/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/adsplog.py,--no-history"
2. See error

**Expected behavior**
testcases can pass.

**Logs and console output**
START - test_smp_running_cancel
PASS - test_smp_running_cancel in 0.101 seconds
...................................................................................................................................................................................................................
START - test_drain_empty
PASS - test_drain_empty in 0.1 seconds
...................................................................................................................................................................................................................
START - test_1cpu_drain_wait
PASS - test_1cpu_drain_wait in 0.202 seconds
...................................................................................................................................................................................................................
START - test_1cpu_plugged_drain
PASS - test_1cpu_plugged_drain in 0.102 seconds
...................................................................................................................................................................................................................
START - test_1cpu_basic_schedule
PASS - test_1cpu_basic_schedule in 0.102 seconds
...................................................................................................................................................................................................................
**START - test_1cpu_basic_schedule_running
ASSERTION FAIL [arch_mem_coherent(to)] @ WEST_TOPDIR/zephyr/kernel/timeout.c:90
@ WEST_TOPDIR/zephyr/lib/os/assert.c:45**

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.12.3
 - Commit id: 59a3def7562e9b4608

### PR DESCRIPTION
**Pull request by andyross**
Shared data can't live on thread stacks if they are incoherent.  These
are all just per-test-case data, so make them static.

Fixes #33898

Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

### CODE REVIEW

File: tests/kernel/workq/work/src/main.c [hunk 1]
```diff
@@ -175,7 +175,7 @@ static void test_work_init(void)
 {
 	static K_WORK_DEFINE(fnstat, counter_handler);
 
-	struct k_work stack;
+	static struct k_work stack;
```
Comment (pabigot) [inline tests/kernel/workq/work/src/main.c:178]: The variable name should change since it isn't on the stack anymore.  Also this isn't a bug in itself, since the work item isn't used in anything other than the init function, so it could be left alone, perhaps with a comment just noting that work items can't be on the stack in non-coherent systems.

**Review by dcpleung — APPROVED** [review]

**Review by pabigot — APPROVED** [review]
Two of the changed uses aren't a problem, and arguably should either be reverted and a comment added, or the variable name changed to avoid confusing people.

The other is fixing a real bug; thanks.
