### PR TITLE
shell: Fix combo use of mandatory and optional raw arguments

### LINKED ISSUE #48380: shell: Mixing mandatory arguments w/ SHELL_OPT_ARG_RAW causes crash
**Describe the bug**
When using `SHELL_OPT_ARG_RAW` in the optional args field of the macro `SHELL_CMD_ARG_REGISTER`, the shell subsystem provides the handler an incorrect value of `argc` when the handler is executed. This occurs when using a mandatory argument value of >= 2 (1 means no mandatory arguments), and `SHELL_OPT_ARG_RAW` as the optional argument value. This issue can result in a out of bounds access of `argv` because `argc` indicates the wrong length.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - I found the issue on nrf9160_dk with the NS target, but can replicate on `qemu_x86_64` as well.
 - What have you tried to diagnose or workaround this issue?
 - This seems to be due to `cmd_lvl` being too high by the time `exec_cmd` is called. Since `cmd_lvl` is too high, the `argc` provided to the handler is as well.

**To Reproduce**
Steps to reproduce the behavior (with modifications as shown at bottom):
1. west build -b <BOARD_NAME> zephyr/samples/hello_world
2. Run build
3. In the console type `test_cmd` and hit enter

**Expected behavior**
Shell subsystem reports error that mandatory arguments are missing.

**Impact**
Has potential to crash system if application is relying on `argc` to be correct.

**Logs and console output**
Cases handled correctly:
```
uart:~$ test_cmd 1
cmd_raw: argc[2]
argv[0]: "test_cmd"

argv[1]: "1"

uart:~$ test_cmd 1 12341234512513456346
cmd_raw: argc[3]
argv[0]: "test_cmd"

argv[1]: "1"

argv[2]: "12341234512513456346"
```

Case handled incorrectly:
```
SeaBIOS (version rel-1.16.0-0-gd239552ce722-prebuilt.qemu.org)
Booting from ROM..*** Booting Zephyr OS build v2.7.99-ncs1-1  ***
Hello World! qemu_x86_64


uart:~$ test_cmd
cmd_raw: argc[2]
argv[0]: "test_cmd"

FAILED: zephyr/CMakeFiles/run_qemu /<path_to>/build/zephyr/CMakeFiles/run_qemu 
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain: Zephyr SDK v0.14.1
 - Commit SHA or Version used: b05b8ad63a (v2.7.99-ncs1-1)

**Additional context**
Here is my source code to replicate the issue:
```c
/*
 * Copyright (c) 2012-2014 Wind River Systems, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr.h>
#include <sys/printk.h>
#include <shell/shell.h>

#define CMD_NAME test_cmd

static int cmd_raw_arg(const struct shell *shell, size_t argc, char **argv)
{
	shell_print(shell, "cmd_raw: argc[%d]", argc);

	for (uint8_t i = 0; i < argc; i++) {
		shell_print(shell, "argv[%d]: \"%s\"\n", i, argv[i]);
	}

	return 0;
}

SHELL_CMD_ARG_REGISTER(CMD_NAME, NULL, "A test command", cmd_raw_arg, 2, SHELL_OPT_ARG_RAW);

void main(void)
{
	printk("Hello World! %s\n", CONFIG_BOARD);
}
```
Here is the additional Kconfigs in `prj.conf`:
```
CONFIG_SHELL=y
```

### PR DESCRIPTION
**Pull request by ejohnso49**
Fixes issue seen when using 1+ mandatory arguments with an optional argument using `SHELL_OPT_ARG_RAW`. Also adds tests to catch future issues.

Fixes #48380

### CODE REVIEW

**Comment by ejohnso49** [comment]
I will update the PR to incorporate the new test changes that were moved into `main`

File: tests/subsys/shell/shell/src/main.c [hunk 1]
```diff
@@ -373,6 +373,38 @@ static void test_raw_arg(void)
...
+	if (argc == 3 && strcmp(argv[2], RAW_ARG)) {
+		return -1;
+	}
+
+	return 0;
+}
+
+SHELL_CMD_ARG_REGISTER(CMD_MAND_OPT_RAW, NULL, NULL, cmd_mand_opt_raw, 2, SHELL_OPT_ARG_RAW);
+
+static void test_mand_opt_raw(void)
```
Comment (nordic-krch) [inline tests/subsys/shell/shell/src/main.c:401]: there is already a test with `SHELL_OPT_ARG_RAW` but with 1 mandatory argument (test_raw_arg). Can you merge those tests or rename somehow so they are similar (e.g. test_mand_1_opt_raw and test_mand_2_opt_raw).

Comment (ejohnso49) [reply tests/subsys/shell/shell/src/main.c]: I ended up keeping the two tests separate and named them following your suggestion: `test_mand_1_opt_raw` and `test_mand_2_opt_raw`

**Comment by ejohnso49** [comment]
Updated to use latest ztest macros and added cases for `select` usage

**Comment by nordic-krch** [comment]
you need to fix the coding guideline. Usually, we rename `shell` to `sh` (imo it's degrading code readability but needed to get CI green).

**Comment by ejohnso49** [comment]
> you need to fix the coding guideline. Usually, we rename `shell` to `sh` (imo it's degrading code readability but needed to get CI green).

Thank you for the pointer, I was really confused what was triggering that. I had trouble running `coccicheck` locally unfortunately

**Comment by carlescufi** [comment]
@jakub-uC  @nordic-krch could you please take a look?

**Review by nordic-krch — APPROVED** [review]

File: subsys/shell/shell.c [hunk 2]
```diff
@@ -782,8 +785,17 @@ static int execute(const struct shell *shell)
 		}
 	}
 
-	/* terminate arguments with NULL */
-	argv[cmd_lvl] = NULL;
```
Comment (Domino-Jachas) [inline subsys/shell/shell.c:786]: Do we need to remove this line?

Comment (jakub-uC) [inline subsys/shell/shell.c:786]: Do we need to remove this line?

Comment (jakub-uC) [reply subsys/shell/shell.c:786]: ahh, I missed that.
LGTM

**Review by jakub-uC — APPROVED** [review]
