### PR TITLE
drivers: timer: it8xxx2: fix the timer drift issue

### LINKED ISSUE #67474: it8xxx2_evb: kernel: tests/kernel/timer/timer_api/kernel.timer.tickless Failed
**Describe the bug**
During test run on it8xxx2_evb platform, there is a Fail test case: test_sleep_abs. This is output from git bisect:
7a5fcb8c60e2e6ba26704fabc28fe2d4e0106513 is the first bad commit
commit 7a5fcb8c60e2e6ba26704fabc28fe2d4e0106513
Author: Keith Packard
Date:   Tue Sep 12 23:51:33 2023 -0700

    libc/picolibc: Support 'long long' and 'minimal' printf variants

**To Reproduce**
1. cd <path/to>zephyrproject/zephyr
2. source zephyr-env.sh
3. twister -p it8xxx2_evb --device-testing --hardware-map <path/to>/map.yaml -T tests/kernel/timer/timer_api/ -v

**Expected behavior**
Test pass

**Impact**
annoyance

**Logs and console output**
START - test_sleep_abs
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:807: timer_api_test_sleep_abs: (late >= 0 && late <= MAX(2, k_us_to_ticks_ceil32(250)) is false)
expected wakeup at 157, got 160 (late 3)
FAIL - test_sleep_abs in 0.034 seconds
___________________________________________________
Other test cases pass:
PASS - [timer_api.test_time_conversions] duration = 0.643 seconds
PASS - [timer_api.test_timeout_abs] duration = 0.003 seconds
PASS - [timer_api.test_timer_duration_period] duration = 0.327 seconds
PASS - [timer_api.test_timer_expirefn_null] duration = 0.327 seconds
PASS - [timer_api.test_timer_k_define] duration = 0.703 seconds
PASS - [timer_api.test_timer_period_0] duration = 0.203 seconds
PASS - [timer_api.test_timer_period_k_forever] duration = 0.203 seconds
PASS - [timer_api.test_timer_periodicity] duration = 0.254 seconds
PASS - [timer_api.test_timer_remaining] duration = 0.052 seconds
PASS - [timer_api.test_timer_restart] duration = 0.277 seconds
PASS - [timer_api.test_timer_status_get] duration = 0.002 seconds
PASS - [timer_api.test_timer_status_get_anytime] duration = 0.327 seconds
PASS - [timer_api.test_timer_status_sync] duration = 0.355 seconds
PASS - [timer_api.test_timer_user_data] duration = 0.303 seconds

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 16.4

### PR DESCRIPTION
**Pull request by Chenhongren**
This commit enhances the accuracy of hardware cycle calculation before setting the IT8xxx2 event timer. The next target cycle is calculated by the last, elapsed, and expected timeout ticks. And then, the difference in hardware cycles between the target cycle and the current cycle is set into the event timer. This increased accuracy effectively resolves the clock drift issue.

Tested with:
west build -p always -b it8xxx2_evb tests/kernel/timer/timer_api -T kernel.timer.tickless
west build -p always -b it8xxx2_evb tests/kernel/timer/timer_behavior -T kernel.timer.timer

Fixes #67474 #67833

### CODE REVIEW

**Review by Dino-Li — APPROVED** [review]

**Comment by pkunieck** [comment]
Tests pass with those changes, checked for #67474

**Review by teburd — APPROVED** [review]

**Review by edersondisouza — APPROVED** [review]

File: drivers/timer/ite_it8xxx2_timer.c [hunk 1]
```diff
@@ -246,21 +251,26 @@ void sys_clock_set_timeout(int32_t ticks, bool idle)
...
+		 * as soon as possible, ideally no more than one system tick
+		 * in the future. So set event timer count to 1 HW tick.
 		 */
-		hw_cnt = MIN((ticks * HW_CNT_PER_SYS_TICK), EVENT_TIMER_MAX_CNT);
+		ticks = CLAMP(ticks, 1, (int32_t)EVEN_TIMER_MAX_CNT_SYS_TICK);
+
+		next_cycs = (last_ticks + last_elapsed + ticks) * HW_CNT_PER_SYS_TICK;
+		now = ~(IT8XXX2_EXT_CNTOX(FREE_RUN_TIMER));
+		if (unlikely(next_cycs <= now)) {
+			hw_cnt = 1;
```
Comment (andyross) [inline drivers/timer/ite_it8xxx2_timer.c:269]: Nitpick: expressing this as a CLAMP() instead of the likely-tagged branch is probably going to generate better code.  Even more so if you can roll the clamp into the ticks computation above.

Just in general the unlikely() construction tends to hurt and not help (both code and readability) if the blocks are tiny one-liners.  Let the branch predictor do its job.

Finally: does a clamp of 1 actually work?  Most timer hardware is based on an equality test in the counter and will drop interrupts if you try to set a deadline too close in the future, and in any case "1" is going to have aliasing bugs where it really lands in the register at a time when it should have been "0".  Some hardware does a proper comparator though, so maybe not necessary.
