### PR TITLE
Bluetooth: controller: split: Fix response to unexpected LL_FEATURE_RSP

### LINKED ISSUE #23494: Bluetooth: LL/PAC/SLA/BV-01-C fails if Slave-initiated Feature Exchange is disabled
**Describe the bug**
Bluetooth qualification test LL/PAC/SLA/BV-01-C fails if Slave-initiated Features Exchange is disabled (`CONFIG_BT_CTLR_SLAVE_FEAT_REQ=n`). This happens because the slave device with that configuration does not respond correctly to an unexpected LL_FEATURE_RSP.

**To Reproduce**
Run BLE qualification test LL/PAC/SLA/BV-01-C on a device configure with `CONFIG_BT_CTLR_SLAVE_FEAT_REQ=n` and Slave-initiated Features Exchange disabled in the ICS.

**Expected behavior**
All qualification tests pass

**Impact**
Cannot qualify BLE stack with Slave-initiated Features Exchange disabled. Enabling this entails also enabling Connection Parameter Request Procedure (these are for some reason tied together when selecting features), which is highly undesirable in our use case.

**Environment (please complete the following information):**
 - Zephyr 2.2

**Additional context**
A possible fix should ideally be back-ported to the 2.2 branch

### PR DESCRIPTION
**Pull request by wopu-ot**
Fix response to unexpected LL_FEATURE_RSP for the case that
BT_CTLR_SLAVE_FEAT_REQ is disabled. Fixes LL/PAC/SLA/BV-01 for such a
configuration.

Fixes #23494

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 1]
```diff
@@ -5407,7 +5407,9 @@ static inline int ctrl_rx(memq_link_t *link, struct node_rx_pdu **rx,
 #endif /* CONFIG_BT_CTLR_SLAVE_FEAT_REQ */
 
 	case PDU_DATA_LLCTRL_TYPE_FEATURE_RSP:
-		if (!pdu_len_cmp(PDU_DATA_LLCTRL_TYPE_FEATURE_RSP,
+		if ((!IS_ENABLED(CONFIG_BT_CTLR_SLAVE_FEAT_REQ) &&
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: Conditional compile the complete block and other associated code (`feature_rsp_recv`) with:
`#if defined(CONFIG_BT_CTLR_SLAVE_FEAT_REQ) || defined(CONFIG_BT_CENTRAL)`

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 1 above)
Comment (wopu-ot) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: That would not work in a configuration with `CONFIG_BT_CENTRAL=y`, `CONFIG_BT_PERIPHERAL=y`, and `CONFIG_BT_CTLR_SLAVE_FEAT_REQ=n` (i.e., where the same device can be master and slave).

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: if `CONFIG_BT_CTLR_SLAVE_FEAT_REQ=n` then only central role is to receive the `PDU_DATA_LLCTRL_TYPE_FEATURE_RSP`, and the `default` case will generate the unknown response in slave role.

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: I stand corrected. The original changes look good (where the same device can be master and slave, but not support slave feature req).

**Review by cvinayak — APPROVED** [review]

**Review by thoh-ot — APPROVED** [review]
