### PR TITLE
drivers: dma: stm32 disabling stream waits for disable

### LINKED ISSUE #54805: when invoke dma_stm32_disable_stream failed in interrupt callback, it will endless loop
In stm32f446rc uart async mode.

code:
https://github.com/zephyrproject-rtos/zephyr/blob/31c11a5dc02a121c659567eeadced7b51a22f3e7/drivers/dma/dma_stm32.c#L264

call stack:
uart_stm32_isr  ---->  uart_stm32_dma_rx_flush ---->  async_evt_rx_rdy ----> async_user_callback  ----> uart_rx_disable

sometimes  stm32_dma_disable_stream failed, the sleep called in interrupt handle, and it will stay in k_sleep.

### PR DESCRIPTION
**Pull request by FRASTM**
Add the loop to wait until the stream is really disable after disabling and also cleared the TCIF flag.
This is a specifity of the dma of type V1.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54805

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
also fixes the tests/drivers/uart/uart_async_api/ running on the nucleo_f429zi:
```
Running TESTSUITE uart_async_write_abort
===================================================================
START - test_write_abort

    Assertion failed at WEST_TOPDIR/zephyr/tests/drivers/uart/uart_async_api/src/test_uart_async.c:526: uart_async_write_abort_test_write_abort: (sent not equal to received)
Sent is not equal to received.
 FAIL - test_write_abort in 0.120 seconds
```

**Review by gautierg-st — DISMISSED** [review]

File: drivers/dma/dma_stm32_v1.c [hunk 1]
```diff
@@ -332,11 +332,11 @@ int stm32_dma_disable_stream(DMA_TypeDef *dma, uint32_t id)
...
 	LL_DMA_DisableStream(dma, dma_stm32_id_to_stream(id));
 
-	if (!LL_DMA_IsEnabledStream(dma, dma_stm32_id_to_stream(id))) {
-		return 0;
+	while (stm32_dma_is_enabled_stream(dma, id)) {
 	}
 
-	return -EAGAIN;
+	dma_stm32_clear_tc(dma, id);
+	return 0;
```
Comment (erwango) [inline drivers/dma/dma_stm32_v1.c:339]: Nit: Break a line.

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
Rebase on b91aa2e28c1004141e452dee8cc1d1a8712e7d35
Add a break line before return

**Review by erwango — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]
