### PR TITLE
Bluetooth: controller: split: Fix regression in privacy port

### LINKED ISSUE #22801: Bluetooth: Split LL: Reconnection problem
**Describe the bug**
Problem was replicated using Zephyr Bluetooth peripheral device. I switched to Zephyr SW Split LL (previously I used SW Legacy LL). If whitelisting is enabled, the Central is connecting and bonding, but it is unable to reconnect. The reconnection problem was not observed for SW Legacy LL.
When I disable the whitelisting, the reconnection works fine too.

**To Reproduce**
1. Use Peripheral device with Zephyr SW split LL.
2. Connect to host, after the disconnection Central is unable to reconnect.

**Environment:**
Zephyr commit SHA: 40175fd3bdc2771b688d67d6f29dcc7a574c30ed

### PR DESCRIPTION
**Pull request by cvinayak**
Fix regression due to addition of conditional compilations
while porting the privacy feature from legacy to split
controller.

Fixes #22801.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
@MarekPieta could you please test and report back?

**Comment by MarekPieta** [comment]
Reported issue is fixed, thank you.

File: subsys/bluetooth/controller/ll_sw/ull_filter.c [hunk 1]
```diff
@@ -480,7 +481,7 @@ void ull_filter_adv_update(u8_t adv_fp)
 	filter_clear(&rl_filter);
 
 	if (rl_enable &&
-	    IS_ENABLED(CONFIG_BT_OBSERVER) && !ull_scan_is_enabled(0)) {
+	    (!IS_ENABLED(CONFIG_BT_OBSERVER) || !ull_scan_is_enabled(0))) {
```
Comment (joerchan) [inline subsys/bluetooth/controller/ll_sw/ull_filter.c]: Personal opinion: I think !(IS_ENABLED(CONFIG_BT_OBSERVER) && ull_scan_is_enabled(0)) is easier to read and would have preferred it here.

**Review by joerchan — APPROVED** [review]

**Review by MarekPieta — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
