### PR TITLE
drivers: fpga_ice40: fix CS hack; fix `k_usleep` during spinlock

### LINKED ISSUE #99948: drivers: ice40_fpga: `k_usleep` while holding a spinlock
### Describe the bug

The [ICE40 FPGA driver]() uses spinlocks for synchronisation (most certainly a mistake).

https://github.com/zephyrproject-rtos/zephyr/blob/8c264d30ea1b5c218a2efd4288820814ff16f1e2/drivers/fpga/fpga_ice40_spi.c#L49

Further, it uses `k_usleep()` for its required delays.

https://github.com/zephyrproject-rtos/zephyr/blob/8c264d30ea1b5c218a2efd4288820814ff16f1e2/drivers/fpga/fpga_ice40_spi.c#L78

This in turn triggers: https://github.com/zephyrproject-rtos/zephyr/blob/8c264d30ea1b5c218a2efd4288820814ff16f1e2/kernel/include/kswap.h#L210

While it might be tempting to change that single `k_usleep()` to a `k_busy_wait()`, the issue is deeper: Almost all SPI drivers use `spi_context_wait_for_completion` which contains `k_sem_take`:

https://github.com/zephyrproject-rtos/zephyr/blob/8c264d30ea1b5c218a2efd4288820814ff16f1e2/drivers/spi/spi_context.h#L219

I understand that the spinlock was introduced because of the very strict timing requirements of the ICE40, but this `k_sem_take` makes almost all SPI peripheral drivers incompatible with the ICE40 driver.

### Regression

- [ ] This is a regression.

### Steps to reproduce

Load an FPGA using the `ice40_fpga` driver.

### Relevant log output

```shell
ASSERTION FAIL [arch_irq_unlocked(key) || _kernel.cpus[0].current->base.thread_state & (((1UL << (0))) | ((1UL << (3))))] @ WEST_TOPDIR/zephyr/kernel/include/kswap.h:210
        Context switching while holding lock!
[00:00:00.012,000] <err> os: r0/a1:  0x00000004  r1/a2:  0x000000d2  r2/a3:  0x00000007
[00:00:00.012,000] <err> os: r3/a4:  0x00000004 r12/ip:  0x0000007d r14/lr:  0x3809b257
[00:00:00.012,000] <err> os:  xpsr:  0x01000000
[00:00:00.012,000] <err> os: Faulting instruction address (r15/pc): 0x3802cd2c
[00:00:00.012,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:00.012,000] <err> os: Current thread: 0x203105d8 (main)
[00:00:00.012,000] <err> os: Halting system
```

### Impact

Minor - works when asserts disabled, but there's probably a reason for this assert

### Environment

Zephyr `4.3.0`
Zephyr SDK `0.17.4`
OS: Windows 11

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Finomnis**
Fixes #99948.

Two asserts were triggered in this module:
- Holding a spinlock while `k_usleep` triggers an assert in `k_swap`
- All gpio_set must be on valid pin configs, which the CS hack in this module breaks.

### CODE REVIEW

**Review by JarmouniA — COMMENTED** [review]
I believe the problem here is not in the spinlock usage, which is valid in my opinion since this driver could be used in multi-core setups, rather  in the `k_usleep` introduced in 2f6dff5 without taking into consideration the usage of spinlocks. The mistake went unnoticed because the triggered assert was added just recently.
https://docs.zephyrproject.org/latest/kernel/services/smp/smp.html#spinlocks

**Comment by Finomnis** [comment]
@JarmouniA Would you mind elaborating on spinlock vs mutex in this scenario? Why would one be picked over the other, what are the advantages/disadvantages?

The lock will be held during the entire 'load', which can be 50ms. During this entire time, nothing else on this chip can happen if you are in a spinlock, if I understand spinlocks correctly, because it completely prevents the scheduler from unscheduling the current thread.

I don't quite understand the rationale for this, because the underlying SPI could be DMA+Interrupt based. Is it really wise to hold a spinlock during a DMA transfer that might signal its termination with an interrupt?

File: drivers/fpga/fpga_ice40_common.h [hunk 1]
```diff
@@ -38,11 +38,11 @@
...
 	BUILD_ASSERT(DT_INST_PROP(inst, trailing_clocks) <= UINT8_MAX);                            \
-	                                                                                           \
+                                                                                                   \
 	static const struct fpga_ice40_config fpga_ice40_config_##inst = {                         \
-		.bus = SPI_DT_SPEC_INST_GET(inst,                                                  \
-					    SPI_OP_MODE_MASTER | SPI_MODE_CPOL | SPI_MODE_CPHA |   \
-						    SPI_WORD_SET(8) | SPI_TRANSFER_MSB),           \
+		.bus = SPI_DT_SPEC_INST_GET(inst, SPI_OP_MODE_MASTER | SPI_MODE_CPOL |             \
+							  SPI_MODE_CPHA | SPI_WORD_SET(8) |        \
+							  SPI_TRANSFER_MSB),                       \
```
Comment (cfriedt) [inline drivers/fpga/fpga_ice40_common.h:45]: It looks like there are some unrelated formatting changes. Can those be undone?

**Comment by cfriedt** [comment]
@Finomnis - I think the `k_usleep()` should be converted to a `k_busy_wait()`. That would definitely be an issue for spinlocks.

The reason that spinlocks were used originally was to avoid any scheduling latencies that a mutex might introduce that could affect the bit-bang interface, which is quite sensitive to timing issues.

We want to avoid the thread being rescheduled while loading the ice40 bitstream.

File: drivers/fpga/fpga_ice40_common.h (hunk 1 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_common.h:45]: I thought we have an official `.clang-format` file, should we not update old code?

**Comment by Finomnis** [comment]
@cfriedt Better like this?

File: drivers/fpga/fpga_ice40_spi.c [hunk 2]
```diff
@@ -33,21 +33,31 @@ static int fpga_ice40_load(const struct device *dev, uint32_t *image_ptr, uint32
...
 	 * as the configuration sequence requires this signal to be inactive
 	 * during the leading and trailing clock phase.
 	 */
-	bus.config.cs.gpio.port = NULL;
+	__ASSERT(bus.config.cs.cs_is_gpio, "driver only compatible with gpio based cs");
+	struct spi_cs_control previous_cs = bus.config.cs;
+
+	if (previous_cs.cs_is_gpio) {
+		bus.config.cs = (struct spi_cs_control){
+			.cs_is_gpio = false,
```
Comment (benediktibk) [inline drivers/fpga/fpga_ice40_spi.c:51]: Wouldn't it be sufficient to just set cs_is_gpio instead of the copy assignment? Or am I missing something here?

**Review by benediktibk — CHANGES_REQUESTED** [review]

File: drivers/fpga/fpga_ice40_spi.c (hunk 2 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c:51]: This is a `union`, setting `cs_is_gpio` changes which union type this struct gets interpreted as, so I think this is dangerous. The gpio id might get interpreted as a delay

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c:51]: @benediktibk Here: https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/drivers/spi.h#L244

Comment (benediktibk) [reply drivers/fpga/fpga_ice40_spi.c:51]: Now I get it, delay is also part of the "other" union. But besides that: delay is specified as us and the others as ns?

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c:51]: Oops

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c:51]: @benediktibk Should we even copy this? Or how is the required timing for the FPGA? Should we simply zero it?

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c:51]: If it has any effect in the first place ... I'm unsure. Probably SPI driver dependent. I'll copy it properly to keep the behaviour consistent to how it was before.

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c:51]: Fixed

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c:51]: But resetting it afterwards is pointless as the entire config is memcpy'd

**Comment by Finomnis** [comment]
Still getting this with the current state of the PR:

```
ASSERTION FAIL [arch_irq_unlocked(key) || _kernel.cpus[0].current->base.thread_state & (((1UL << (0))) | ((1UL << (3))))] @ WEST_TOPDIR/zephyr/kernel/include/kswap.h:210
        Context switching while holding lock!
[00:00:00.014,000] <err> os: r0/a1:  0x00000004  r1/a2:  0x000000d2  r2/a3:  0x00000003
[00:00:00.014,000] <err> os: r3/a4:  0x00000004 r12/ip:  0x00000087 r14/lr:  0x3809b583
[00:00:00.014,000] <err> os:  xpsr:  0x01000000
[00:00:00.014,000] <err> os: Faulting instruction address (r15/pc): 0x3802ccb0
[00:00:00.014,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:00.014,000] <err> os: Current thread: 0x20301f00 (main)
[00:00:00.037,000] <err> os: Halting system
```

**Comment by cfriedt** [comment]
Kconfig to select mutex or spinlock seems like maybe overkill.

I kind of wonder if there is a way to perform bitstream loading in a high priority or perhaps cooperative workqueue thread.

**Comment by cfriedt** [comment]
@Finomnis - you could theoretically use the system work queue, and I believe it's cooperative already.

File: drivers/fpga/fpga_ice40_bitbang.c [hunk 3]
```diff
@@ -115,27 +115,36 @@ static void fpga_ice40_spi_send_data(size_t delay, volatile gpio_port_pins_t *se
  *
  * https://www.latticesemi.com/~/media/LatticeSemi/Documents/Handbooks/iCE40FamilyHandbook.pdf
  */
-static int fpga_ice40_load(const struct device *dev, uint32_t *image_ptr, uint32_t img_size)
+static void fpga_ice40_load_handler(struct k_work *item)
 {
+	struct fpga_ice40_work_item *work_item =
+		CONTAINER_OF(item, struct fpga_ice40_work_item, work);
+	const struct device *dev = work_item->dev;
+	const uint32_t *image_ptr = work_item->image_ptr;
```
Comment (benediktibk) [inline drivers/fpga/fpga_ice40_bitbang.c]: If you remove the const here you get rid of the sonar cube complaint later. It also isn't const in the work item, so no real need to make it const.

**Review by benediktibk — APPROVED** [review]
I like the idea, but unfortunately I don't have the STM32 based hardware at the moment available to test it out. I hope to get my hands on it within the next few months, but right now I can only hope it won't break the fickle ICE40 loading procedure.

**Comment by Finomnis** [comment]
> I like the idea, but unfortunately I don't have the STM32 based hardware at the moment available to test it out. I hope to get my hands on it within the next few months, but right now I can only hope it won't break the fickle ICE40 loading procedure.

It's pretty broken already 🤷

File: drivers/fpga/fpga_ice40_bitbang.c (hunk 3 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_bitbang.c]: Fixed

**Review by benediktibk — APPROVED** [review]

File: drivers/fpga/fpga_ice40_common.c [hunk 4]
```diff
@@ -96,6 +94,15 @@ int fpga_ice40_init(const struct device *dev)
 {
 	int ret;
 	const struct fpga_ice40_config *config = dev->config;
+	struct fpga_ice40_data *data = dev->data;
+
+	data->loaded = false;
```
Comment (cfriedt) [inline drivers/fpga/fpga_ice40_common.c]: The `data` object should already be zero initialized, so you can drop these 4 lines.

File: drivers/fpga/fpga_ice40_spi.c [hunk 5]
```diff
@@ -138,32 +150,33 @@ static int fpga_ice40_load(const struct device *dev, uint32_t *image_ptr, uint32
...
+		goto cleanup;
 	}
 
 	ret = 0;
 	data->loaded = true;
 	fpga_ice40_crc_to_str(crc, data->info);
 	LOG_INF("Loaded image with CRC32 0x%08x", crc);
 
-unlock:
+cleanup:
```
Comment (cfriedt) [inline drivers/fpga/fpga_ice40_spi.c]: Changing this label isn't really needed and adds a number of unnecessary lines in this diff.

Can the label rename be undone?

I also see `img_size` being changed to `imag_size` in a number of places where it does not look necessary.

If the renames must stay in this change, can it be moved to a separate commit.

**Review by cfriedt — COMMENTED** [review]
Suggestions to move gratuitous renames to separate commit.

File: drivers/fpga/fpga_ice40_spi.c (hunk 5 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c]: Sure :) can do. Renamed it because it now does more than unlock

File: drivers/fpga/fpga_ice40_common.c (hunk 4 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_common.c]: I'm not sure if I follow; would you mind explaining where this initialization happens?

File: drivers/fpga/fpga_ice40_spi.c (hunk 5 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_spi.c]: Reverted renames.

**Review by benediktibk — APPROVED** [review]

File: drivers/fpga/fpga_ice40_common.c (hunk 4 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_common.c]: @cfriedt Is it being initialized somewhere? Or should I keep the lines?

**Review by JarmouniA — DISMISSED** [review]

File: drivers/fpga/fpga_ice40_common.c (hunk 4 above)
Comment (mathieuchopstm) [reply drivers/fpga/fpga_ice40_common.c]: I think @cfriedt refers to the fact that data is zero-initialized by default.

**Review by mathieuchopstm — COMMENTED** [review]
Agree with @cfriedt - some cosmetic changes are mixed with functional changes, which is not ideal. LGTM otherwise.

File: drivers/fpga/fpga_ice40_common.c (hunk 4 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_common.c]: @mathieuchopstm are static structs in C zero initialized if they don't have a `= {}` initializer? I thought they require that, otherwise they are just random data

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_common.c]: I guess you are right. Will update the code.

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_common.c]: Fixed.

File: drivers/fpga/fpga_ice40_bitbang.c [hunk 6]
```diff
@@ -115,27 +115,36 @@ static void fpga_ice40_spi_send_data(size_t delay, volatile gpio_port_pins_t *se
...
+
 	int ret;
 	uint32_t crc;
 	gpio_port_pins_t cs;
 	gpio_port_pins_t clk;
-	k_spinlock_key_t key;
 	gpio_port_pins_t pico;
 	gpio_port_pins_t creset;
+	struct k_spinlock spinlock;
+	k_spinlock_key_t spinlock_key;
```
Comment (mathieuchopstm) [inline drivers/fpga/fpga_ice40_bitbang.c]: `key` --> `spinlock_key`

File: drivers/fpga/fpga_ice40_bitbang.c [hunk 7]
```diff
@@ -145,12 +154,13 @@ static int fpga_ice40_load(const struct device *dev, uint32_t *image_ptr, uint32
 	creset = BIT(config->creset.pin);
 
 	/* crc check */
-	crc = crc32_ieee((uint8_t *)image_ptr, img_size);
+	crc = crc32_ieee((uint8_t *)image_ptr, image_size);
```
Comment (mathieuchopstm) [inline drivers/fpga/fpga_ice40_bitbang.c]: `img_size` --> `image_size`

**Review by mathieuchopstm — COMMENTED** [review]
> > Agree with @cfriedt - some cosmetic changes are mixed with functional changes, which is not ideal. LGTM otherwise.
> 
> @mathieuchopstm Would you mind pointing out which ones? I already reverted the changes @cfriedt was talking about.

These two renames caught my eyes (they generate noise in the diff):

File: drivers/fpga/fpga_ice40_bitbang.c (hunk 6 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_bitbang.c]: As I moved the spin lock in here I thought it's a good chance to name the "key" a little bit more descriptive. There's already a diff for all relevant lines in this change, so I thought why not. Was that wrong?

File: drivers/fpga/fpga_ice40_bitbang.c (hunk 7 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_bitbang.c]: That's technically a different variable. Should I name the new variable the same as the previous one to prevent the diff? I thought if I created a completely new variable I should maybe adjust the name to be consistent with `image_ptr`

File: drivers/fpga/fpga_ice40_bitbang.c (hunk 6 above)
Comment (mathieuchopstm) [reply drivers/fpga/fpga_ice40_bitbang.c]: It's not *wrong* but it does generate noise in the diff. Also, `key` is a very common name for such variables so I don't think the `spinlock_` prefix adds much value.

File: drivers/fpga/fpga_ice40_bitbang.c (hunk 7 above)
Comment (mathieuchopstm) [reply drivers/fpga/fpga_ice40_bitbang.c]: To be consistent with `image_ptr`, it should (arguably) be named `image_sz` rather than `image_size` 🙂 

I'd keep `image_sz`/`image_size` in the structure and `img_size` here to avoid noise in diff - again, not much value brought by the rename.

Comment (Finomnis) [reply drivers/fpga/fpga_ice40_bitbang.c]: Better?

File: drivers/fpga/fpga_ice40_bitbang.c (hunk 6 above)
Comment (Finomnis) [reply drivers/fpga/fpga_ice40_bitbang.c]: Better?

**Review by JarmouniA — APPROVED** [review]

**Review by mathieuchopstm — APPROVED** [review]

File: drivers/fpga/fpga_ice40_common.c (hunk 4 above)
Comment (mathieuchopstm) [reply drivers/fpga/fpga_ice40_common.c]: > @mathieuchopstm are static structs in C zero initialized if they don't have a `= {}` initializer? I thought they require that, otherwise they are just random data

This is only true for local variables, not globals.

**Review by cfriedt — APPROVED** [review]
