### PR TITLE
driver: timer: stm32_lptim: don't reset backup domain

### LINKED ISSUE #25895: driver: timer: stm32_lptim: backup domain is reset
**Describe the bug**
When the stm32 lptimer is used, the backup domain is reset.

**To Reproduce**
Enable the stm32 lptimer with: `CONFIG_STM32_LPTIM_TIMER=y`

**Impact**
The backup domain reset removes:
- RTC configuration
- backup registers
- RCC Backup domain control register

### PR DESCRIPTION
**Pull request by jdascenzio**
We don't need to reset backup domain to set LSE clock source.
It's dangerous to reset backup domain, it removes:
	- RTC configuration
	- backup registers
	- RCC Backup domain control register

fix  #25895

### CODE REVIEW

**Comment by erwango** [comment]
@jdascenzio can you raise and assiciated issue for this fix?
Since we're in the release period of v2.3.0, only buf fixes assicoated to an issue could be merged.

**Comment by jdascenzio** [comment]
close #25895

File: drivers/timer/stm32_lptim_timer.c [hunk 1]
```diff
@@ -110,8 +110,6 @@ int z_clock_driver_init(struct device *device)
 #endif /* LL_APB1_GRP1_PERIPH_PWR */
 	/* enable backup domain */
 	LL_PWR_EnableBkUpAccess();
```
Comment (FRASTM) [inline drivers/timer/stm32_lptim_timer.c:112]: Is power on the backup domain still required then ?

Comment (jdascenzio) [reply drivers/timer/stm32_lptim_timer.c:112]: Yes it's need to enable LSE clock (LSEON bit in RCC_BDCR which is protect by DBP bit)

**Review by FRASTM — APPROVED** [review]

**Review by erwango — APPROVED** [review]
