### PR TITLE
net: websocket: new receiving algorithm

### LINKED ISSUE #52327: websocket: websocket_recv_msg breaks when there is no data after header
If there is no data after the header and the message length is 0, the next packet will be incorrectly analyzed, because payload data will be expected instead of the header. I tested it on zephyr 2.7.2, nothing has changed in version 3.2.99.
https://github.com/zephyrproject-rtos/zephyr/blob/56664826b27c1b716483fbad35961450794c3089/subsys/net/lib/websocket/websocket.c#L847
I catch this error when I receive a ping message without payload data (for ping messages, payload data is not required [[RFC6455](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2)]).
I fixed it this way:
```c
if (ctx->tmp_buf_pos == 0) {
	/* No data after the header, let the caller call
		* this function again to get the payload.
		*/
	if (ctx->message_len == 0) {
		ctx->header_received = false;
		ctx->message_len = 0;
		ctx->message_type = 0;
		ctx->total_read = 0;
	}
	return -EAGAIN;
}
```

### PR DESCRIPTION
**Pull request by GrixaYrev**
`websocket_recv_msg()` is reworked with using fsm. Now the function return 0 when payload is empty, -ENOTCONN if socket close. Receiving empty ping and sending empty pong were added in tests.
Fixes #52327

### CODE REVIEW

File: subsys/net/lib/websocket/websocket.c [hunk 1]
```diff
@@ -818,178 +863,103 @@ int websocket_recv_msg(int ws_sock, uint8_t *buf, size_t buf_len,
...
-		ctx->total_read = 0;
+			if (ret == 0) {
+				/* Socket closed */
+				return -ENOTCONN;
+			}
 
-		memmove(ctx->tmp_buf, &ctx->tmp_buf[header_len],
-			ctx->tmp_buf_len - header_len);
-		ctx->tmp_buf_pos -= header_len;
+			ctx->tmp_buf_pos = ret;
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:907]: I think this variable name needs an update - it no longer represents currently processed data **position** but rather the length of the data within `tmp_buf`.

File: subsys/net/lib/websocket/websocket.c [hunk 2]
```diff
@@ -818,178 +863,103 @@ int websocket_recv_msg(int ws_sock, uint8_t *buf, size_t buf_len,
...
+		for (count = 0; count < ctx->tmp_buf_pos; count++) {
+			ret = websocket_parser_step(ctx, ctx->tmp_buf[count]);
+			if (ret != 0) {
+				return ret;
+			}
 
-		memcpy(ctx->tmp_buf, test_data->input_buf, input_len);
-		test_data->input_buf += input_len;
+			if ((ctx->parser_state == WEBSOCKET_PARSER_STATE_OPCODE)
+					|| (ctx->data_buf_count >= ctx->data_buf_size)) {
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:921]: Please fix the alignment.

File: subsys/net/lib/websocket/websocket.c [hunk 3]
```diff
@@ -818,178 +863,103 @@ int websocket_recv_msg(int ws_sock, uint8_t *buf, size_t buf_len,
...
 #endif /* CONFIG_NET_TEST */
 
-	/* If we have not received the websocket header yet, read it first */
-	if (!ctx->header_received) {
-#if defined(CONFIG_NET_TEST)
-		size_t input_len = MIN(ctx->tmp_buf_len - ctx->tmp_buf_pos,
-				       test_data->input_len);
+	ctx->data_buf_count = 0;
+	ctx->data_buf_size = buf_len;
+	ctx->data_buf = buf;
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:868]: I wonder if those really need to be a part of the `struct websocket_context` given they are re-initialized on each `websocket_recv_msg()` call. They could be local variables, the parser function could accept additional params.

File: subsys/net/lib/websocket/websocket.c [hunk 4]
```diff
@@ -715,94 +724,130 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
...
+			} else {
+				ctx->parser_remaining = ctx->message_len;
+				ctx->parser_state = WEBSOCKET_PARSER_STATE_PAYLOAD;
+			}
+		}
 		break;
-	case 0x0A00:
-		*message_type_flag |= WEBSOCKET_FLAG_PONG;
+	case WEBSOCKET_PARSER_STATE_PAYLOAD:
+		/* unreal condition, but check for safe */
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:808]: If it's not supposed to happen, then perhaps it'd be better to assert on `data_buf_count >= data_buf_size`?

File: subsys/net/lib/websocket/websocket.c [hunk 5]
```diff
@@ -715,94 +724,130 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
...
-			*mask_value = sys_get_be32(&buf[2 + len_len]);
-			*header_len += 4;
-		} else {
-			*masked = false;
-		}
-
-		return true;
+#if (LOG_LEVEL >= LOG_LEVEL_DBG)
+	if ((ctx->parser_state == WEBSOCKET_PARSER_STATE_PAYLOAD)
+			|| ((ctx->parser_state == WEBSOCKET_PARSER_STATE_OPCODE)
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:824]: Please fix the alignment.

File: subsys/net/lib/websocket/websocket.c [hunk 6]
```diff
@@ -715,94 +724,130 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
...
+				ctx->parser_state = WEBSOCKET_PARSER_STATE_PAYLOAD;
+			}
+		}
 		break;
-	case 0x0A00:
-		*message_type_flag |= WEBSOCKET_FLAG_PONG;
+	case WEBSOCKET_PARSER_STATE_PAYLOAD:
+		/* unreal condition, but check for safe */
+		if (ctx->data_buf_count < ctx->data_buf_size) {
+			ctx->data_buf[ctx->data_buf_count++] = data;
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:810]: I'd prefer a simple `data_len` instead of `data_buf_count`, IMO the latter is a bit enigmatic.

File: subsys/net/lib/websocket/websocket.c [hunk 7]
```diff
@@ -818,178 +863,103 @@ int websocket_recv_msg(int ws_sock, uint8_t *buf, size_t buf_len,
...
-			 */
-			return -EAGAIN;
+			NET_DBG("[%p] Received %d bytes", ctx, ret);
 		}
 
-		NET_DBG("There is %zd bytes of data", ctx->tmp_buf_pos);
-	}
-
-	/* Now read the whole payload or parts of it */
+		size_t count;
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:912]: Maybe `offset` would be more descriptive here? Also, the variable could be defined within `for()` (or moved at the beginning of the block).

File: subsys/net/lib/websocket/websocket.c [hunk 8]
```diff
@@ -715,94 +724,130 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
...
+				ctx->parser_state = WEBSOCKET_PARSER_STATE_OPCODE;
+			} else {
+				ctx->parser_remaining = ctx->message_len;
+				ctx->parser_state = WEBSOCKET_PARSER_STATE_PAYLOAD;
+			}
+		}
 		break;
-	case 0x0A00:
-		*message_type_flag |= WEBSOCKET_FLAG_PONG;
+	case WEBSOCKET_PARSER_STATE_PAYLOAD:
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:807]: Just a general note for discussion - I wonder if the payload processing could be optimized a bit, i. e. use memcpy instead of processing byte by byte.

File: include/zephyr/net/websocket.h [hunk 9]
```diff
@@ -166,7 +166,10 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
  *        The value is in milliseconds. Value SYS_FOREVER_MS means to wait
  *        forever.
  *
- * @return <0 if error, >=0 amount of bytes received
+ * @retval >=0 amount of bytes received.
+ * @retval -EAGAIN on timeout.
+ * @retval -ENOTCONN on socket close.
```
Comment (rlubos) [inline include/zephyr/net/websocket.h:171]: As we update the API, we should update the code that relied on the old, 0 on disconnect behaviour. I've identified two places:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/mqtt/mqtt_transport_websocket.c - should return 0 on `-ENOTCONN`
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/websocket/websocket.c#L1027 - same story

File: subsys/net/lib/websocket/websocket.c [hunk 10]
```diff
@@ -715,94 +724,130 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
...
-	struct test_data {
-		uint8_t *input_buf;
-		size_t input_len;
-		struct websocket_context *ctx;
-	};
+	if ((buf == NULL) || (buf_len == 0)) {
+		return -EINVAL;
+	}
 
+#if defined(CONFIG_NET_TEST)
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:850]: I'm not really a fan of this ifdef slicing the function with test code, perhaps we could change the approach later (not requesting change for this PR).

**Review by rlubos — COMMENTED** [review]
Thank you @GrixaYrev for the PR. I think the PR needs some tweaking here and there (see comments), but I see how the new websocket parsing approach should help with the both issues we're currently observing. Plus I find it a bit easier to follow than the previous solution.

File: subsys/net/lib/websocket/websocket.c [hunk 11]
```diff
@@ -818,178 +863,103 @@ int websocket_recv_msg(int ws_sock, uint8_t *buf, size_t buf_len,
...
-	/* If we have not received the websocket header yet, read it first */
-	if (!ctx->header_received) {
-#if defined(CONFIG_NET_TEST)
-		size_t input_len = MIN(ctx->tmp_buf_len - ctx->tmp_buf_pos,
-				       test_data->input_len);
+	ctx->data_buf_count = 0;
+	ctx->data_buf_size = buf_len;
+	ctx->data_buf = buf;
+
+	int exit_from_loop = false;
```
[the remark this answers is not in the document]
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c:870]: Ok, also i move `size_t count;` at the top of block `do { ... } while();`

File: subsys/net/lib/websocket/websocket.c (hunk 3 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c:868]: It is good idea, i add `struct websocket_payload_buffer`.

File: subsys/net/lib/websocket/websocket.c (hunk 4 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c:808]: Ok, i use `NET_ASSERT(payload->count < payload->size);`

File: subsys/net/lib/websocket/websocket.c (hunk 10 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c:850]: I completely agree with you! It is bad practice, but i think too many changes need for refuse it.

File: subsys/net/lib/websocket/websocket.c (hunk 2 above)
Comment (rlubos) [reply subsys/net/lib/websocket/websocket.c:921]: Typically, it's recommended to align with the opening bracket

File: subsys/net/lib/websocket/websocket.c (hunk 7 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c:912]: I think `parsed_count` shows sense of variable better. And i move it at the top of block.

File: subsys/net/lib/websocket/websocket.c (hunk 2 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c:921]: Like that?
```c
	if ((ctx->parser_state == WEBSOCKET_PARSER_STATE_OPCODE) ||
           (payload.count >= payload.size)) {
```
Or?
```c
	if ((ctx->parser_state == WEBSOCKET_PARSER_STATE_OPCODE) ||
            (payload.count >= payload.size)) {
```

Comment (rlubos) [reply subsys/net/lib/websocket/websocket.c:921]: > ```c
> 	if ((ctx->parser_state == WEBSOCKET_PARSER_STATE_OPCODE) ||
>             (payload.count >= payload.size)) {
> ```

This one

File: include/zephyr/net/websocket.h (hunk 9 above)
Comment (GrixaYrev) [reply include/zephyr/net/websocket.h:171]: ALso i found

https://github.com/zephyrproject-rtos/zephyr/blob/8bc094610c5dd69f6ba0085fb3fe7d18167164c9/samples/net/sockets/websocket_client/src/main.c#L204

File: subsys/net/lib/websocket/websocket.c (hunk 1 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c:907]: Rename `tmp_buf` to `recv_buf` and use `struct websocket_buffer` for `recv_buf` and `payload`.
```c
/**
 * Description of external buffers for payload and receiving
 */
struct websocket_buffer {
	/* external buffer */
	uint8_t *buf;
	/* size of external buffer */
	size_t size;
	/* data length in external buffer */
	size_t count;
}; 
```

File: subsys/net/lib/websocket/websocket.c (hunk 8 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c]: At first i thought it will be difficult, but i made this change.

File: subsys/net/lib/websocket/websocket.c (hunk 6 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c]: Now `struct websocket_buffer` is used.

File: subsys/net/lib/websocket/websocket.c (hunk 4 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c]: Using `memcpy()` eliminate this issue.

File: subsys/net/lib/websocket/websocket.c (hunk 3 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c]: Now `struct websocket_buffer` is used.

**Comment by GrixaYrev** [comment]
I have not check MQTT (only compile), so @jumo-sballing can You test please.

File: subsys/net/lib/websocket/websocket.c [hunk 12]
```diff
@@ -715,94 +724,157 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
...
+			memcpy(&payload->buf[payload->count],
+					&ctx->recv_buf.buf[parsed_count],
+					ready_to_copy);
+			parsed_count += ready_to_copy;
+			payload->count += ready_to_copy;
+			ctx->parser_remaining -= ready_to_copy;
+			if (ctx->parser_remaining == 0) {
+				ctx->parser_remaining = 0;
+				ctx->parser_state = WEBSOCKET_PARSER_STATE_OPCODE;
+			}
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket.c:849]: The loop is missing an exit condition when the application-provided buffer is filled out, something like:
```
			if (payload->count == payload->size) {
				break;
			}
```
I've hit the issue when testing the changes with MQTT - the MQTT library reads the data in small chunks when parsing the MQTT header. There was still data in the recv buffer, but as `free_in_payload_buf` evaluated to 0, the loop spinned endlessly as it could not consume all of the data from the recv buffer.

After fixing this issue, the implementation worked fine, both with TCP and TLS underneath.

File: subsys/net/lib/websocket/websocket_internal.h [hunk 13]
```diff
@@ -100,11 +119,28 @@ __net_socket struct websocket_context {
...
+
+		/** "tx" buffer data length */
+		size_t input_len;
+
+		/** "tx" buffer read (recv) position */
+		size_t input_pos;
+
+		/** external test context */
+		struct websocket_context *ctx;
+	};
```
Comment (rlubos) [inline subsys/net/lib/websocket/websocket_internal.h:141]: This structure doesn't need to be indented.

**Review by rlubos — COMMENTED** [review]
One issue with the loop, but otherwise it looks quite reasonable already. There are some formatting issues (most likely due to spaces count/tab mismatch) that could be fixed. Or, you could use `git-clang-format --commit HEAD~1` to do the formatting work for you.

File: subsys/net/lib/websocket/websocket_internal.h (hunk 13 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket_internal.h]: Fixes

File: subsys/net/lib/websocket/websocket.c [hunk 14]
```diff
@@ -715,94 +724,157 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
...
+			default:
+				return -EFAULT;
+			}
 
-	if (buf_len >= *header_len) {
-		if (value & 0x0080) {
-			*masked = true;
-			*mask_value = sys_get_be32(&buf[2 + len_len]);
-			*header_len += 4;
+	#if (LOG_LEVEL >= LOG_LEVEL_DBG)
```
[the remark this answers is not in the document]
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c]: Fixes

File: subsys/net/lib/websocket/websocket.c [hunk 15]
```diff
@@ -715,94 +724,157 @@ int websocket_send_msg(int ws_sock, const uint8_t *payload, size_t payload_len,
...
-		*message_length = len;
-	} else if (len == 126) {
-		len_len = 2;
-		*message_length = sys_get_be16(&buf[2]);
-	} else {
-		len_len = 8;
-		*message_length = sys_get_be64(&buf[2]);
-	}
+static int websocket_parse(struct websocket_context *ctx,
+						   struct websocket_buffer *payload)
```
[the remark this answers is not in the document]
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c]: Fixes, thank you for hint

File: subsys/net/lib/websocket/websocket.c (hunk 12 above)
Comment (GrixaYrev) [reply subsys/net/lib/websocket/websocket.c:848]: I added test `test_recv_in_small_buffer`, which reproduce this bug, then added checking you proposed.

File: subsys/net/lib/websocket/websocket.c (hunk 10 above)
Comment (jukkar) [reply subsys/net/lib/websocket/websocket.c:872]: I am the person who introduced this hack in the first place. I was very reluctant to do the testing like this but it was the simplest and easiest way at the time to do it as I did not had too much time to implement the testing part. And of course this technical dept easily sticks like a glue after the implementation.

File: subsys/net/lib/websocket/websocket.c (hunk 12 above)
Comment (rlubos) [reply subsys/net/lib/websocket/websocket.c:848]: Thanks

**Review by rlubos — APPROVED** [review]
I have no more comments, LGTM, thanks!

**Comment by rlubos** [comment]
Re-tested MQTT and it works just fine now.

**Review by jukkar — APPROVED** [review]

**Comment by rlubos** [comment]
> @rlubos Please help, tests failed, and i think some last commit in `main` is reason. Should i rebase my branch and restart tests and review at some time (after anybody has fixed tests), or the PR can be merged without it?

There indeed is some regression on `main`. Tests have to pass, I've reported the issue on Discord. There are actually two seemingly unrelated issues, one is being addressed already.
