### PR TITLE
Bluetooth: drivers: Sync bus types with BlueZ

### LINKED ISSUE #80984: Bluetooth: HCI bus types are out of sync with BlueZ
**Describe the bug**

Zephyr uses the same HCI bus type values as BlueZ, since these are mapped to the BTSnoop protocol, which in turn can be parsed with the BlueZ `btmon` tool.

**To Reproduce**

Look at:
- https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/lib/hci.h#n38
- https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/src/shared/btsnoop.h#n51
- https://git.kernel.org/pub/scm/bluetooth/bluetooth-next.git/tree/include/net/bluetooth/hci.h#n60

**Expected behavior**

These should be the same and have the same values as
https://github.com/zephyrproject-rtos/zephyr/blob/d4b7bf986c6a5ea0eedaf2d2b5e2a22567b1dac9/include/zephyr/drivers/bluetooth.h#L62-L73

**Impact**

Incorrect bus types reported with `btmon`

### PR DESCRIPTION
**Pull request by jhedberg**
The authoritative source of these values is BlueZ:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/lib/hci.h#n38

Update our values with the above. The IPM definiton doesn't exist in BlueZ, but should be added there to make sure we don't get out of sync again.

Fixes #80984

### CODE REVIEW

**Comment by jhedberg** [comment]
@Vudentz any chance you could help add the IPM definition to BlueZ? That way, if BlueZ extends this list, at least we don't use overlapping values. Likewise, if we ever need to extend it, we'll make sure to get the same addition to BlueZ as well.

**Review by alwa-nordic — DISMISSED** [review]

**Comment by alwa-nordic** [comment]
Should we add a code comment with a link to the authoritative source?

**Comment by jhedberg** [comment]
> Should we add a code comment with a link to the authoritative source?

I'm just not sure how to make that reference so that it stays up to date, besides simply saying "These values come from Linux/BlueZ". What makes the situation more confusing is that BlueZ has multiple places defining them. There's e.g. the following which seems to be out of date with the latest VirtIO addition (@Vudenz you might want to fix this):
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/src/shared/btsnoop.h#n51

The Linux kernel also has its own definitions, which could be seen as equally authoritative as the user space tree:
https://git.kernel.org/pub/scm/bluetooth/bluetooth-next.git/tree/include/net/bluetooth/hci.h#n60

File: include/zephyr/drivers/bluetooth.h [hunk 1]
```diff
@@ -69,7 +69,9 @@ enum bt_hci_bus {
 	BT_HCI_BUS_SDIO          = 6,
 	BT_HCI_BUS_SPI           = 7,
 	BT_HCI_BUS_I2C           = 8,
-	BT_HCI_BUS_IPM           = 9,
+	BT_HCI_BUS_SMD           = 9,
+	BT_HCI_BUS_VIRTIO        = 10,
+	BT_HCI_BUS_IPM           = 11,
```
Comment (carlescufi) [inline include/zephyr/drivers/bluetooth.h:74]: I would recommend instead using `IPC` instead of `IPM`, since `IPM` is a driver class in zephyr, but the subsystem used is the `IPC` one.

Comment (jhedberg) [reply include/zephyr/drivers/bluetooth.h:74]: I change it to IPC, but I also left IPM as an alias, since there are several DT bindings referring to it which I don't feel comfortable touching this close to the release.

**Review by alwa-nordic — DISMISSED** [review]

File: dts/bindings/bluetooth/bt-hci.yaml [hunk 2]
```diff
@@ -20,6 +20,7 @@ properties:
       - "spi"
       - "i2c"
       - "ipm"
```
Comment (alwa-nordic) [inline dts/bindings/bluetooth/bt-hci.yaml:22]: Would this be useful?

```suggestion
      - "ipm"  # Deprecated alias for "ipc"
```

Comment (jhedberg) [reply dts/bindings/bluetooth/bt-hci.yaml]: Done.

**Review by alwa-nordic — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]

**Comment by jhedberg** [comment]
@alwa-nordic @Thalley sorry, for the sake of completeness I realized "smd" and "virtio" need to be in the allowed DT property values as well, in case some future HCI driver/binding wants to use those. So you'll need to renew your approvals.

**Review by alwa-nordic — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Comment by Vudentz** [comment]
> > Should we add a code comment with a link to the authoritative source?
> 
> I'm just not sure how to make that reference so that it stays up to date, besides simply saying "These values come from Linux/BlueZ". What makes the situation more confusing is that BlueZ has multiple places defining them. There's e.g. the following which seems to be out of date with the latest VirtIO addition (@Vudenz you might want to fix this): https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/src/shared/btsnoop.h#n51
> 
> The Linux kernel also has its own definitions, which could be seen as equally authoritative as the user space tree: https://git.kernel.org/pub/scm/bluetooth/bluetooth-next.git/tree/include/net/bluetooth/hci.h#n60

I will update those value and add a reference to this issue so we crosscheck, Im also planning to add PCI(12) bus after IPC.
