### PR TITLE
subsys: usb: device_next: Fix unchecked return value in usbd_cdc_ecm

### LINKED ISSUE #90559: [Coverity CID: 489224] Unchecked return value in subsys/usb/device_next/class/usbd_cdc_ecm.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/265cfb45a818f39cf03c3527b5d1b21027d3cac1/subsys/usb/device_next/class/usbd_cdc_ecm.c

Category: Error handling issues
Function: `cdc_ecm_send`
Component: USB
CID: [489224](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=489224)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/265cfb45a818f39cf03c3527b5d1b21027d3cac1/subsys/usb/device_next/class/usbd_cdc_ecm.c#L526

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=489224

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CHECKED_RETURN). ([CWE-252](http://cwe.mitre.org/data/definitions/252.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by rruuaanng**
Fix unchecked return value scanned by Coverity.

Closes: #90559 #90561

### CODE REVIEW

File: subsys/usb/device_next/class/usbd_cdc_ecm.c [hunk 1]
```diff
@@ -523,7 +523,7 @@ static int cdc_ecm_send(const struct device *dev, struct net_pkt *const pkt)
 		udc_ep_buf_set_zlp(buf);
 	}
 
-	usbd_ep_enqueue(c_data, buf);
+	(void)usbd_ep_enqueue(c_data, buf);
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_cdc_ecm.c]: This is not the way to fix it.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: subsys/usb/device_next/class/usbd_cdc_ecm.c [hunk 2]
```diff
@@ -523,7 +525,15 @@ static int cdc_ecm_send(const struct device *dev, struct net_pkt *const pkt)
 		udc_ep_buf_set_zlp(buf);
 	}
 
-	usbd_ep_enqueue(c_data, buf);
+	ep = cdc_ecm_get_bulk_out(c_data);
+	ret = usbd_ep_enqueue(c_data, buf);
+	if (ret) {
+		LOG_ERR("Failed to enqueue net_buf for 0x%02x", ep);
+		k_sem_take(&data->sync_sem, K_FOREVER);
```
Comment (tmon-nordic) [inline subsys/usb/device_next/class/usbd_cdc_ecm.c]: This can lead to deadlock.

**Review by tmon-nordic — CHANGES_REQUESTED** [review]

File: subsys/usb/device_next/class/usbd_cdc_ecm.c (hunk 2 above)
Comment (rruuaanng) [reply subsys/usb/device_next/class/usbd_cdc_ecm.c]: Done.

File: subsys/usb/device_next/class/usbd_cdc_ecm.c [hunk 3]
```diff
@@ -523,7 +525,13 @@ static int cdc_ecm_send(const struct device *dev, struct net_pkt *const pkt)
 		udc_ep_buf_set_zlp(buf);
 	}
 
-	usbd_ep_enqueue(c_data, buf);
+	ep = cdc_ecm_get_bulk_out(c_data);
+	ret = usbd_ep_enqueue(c_data, buf);
+	if (ret) {
+		LOG_ERR("Failed to enqueue net_buf for 0x%02x", ep);
+		return ret;
```
Comment (tmon-nordic) [inline subsys/usb/device_next/class/usbd_cdc_ecm.c:533]: The buffer will leak.

File: subsys/usb/device_next/class/bt_hci.c [hunk 4]
```diff
@@ -189,7 +190,11 @@ static void bt_hci_tx_sync_in(struct usbd_class_data *const c_data,
 	}
 
 	net_buf_add_mem(buf, bt_buf->data, bt_buf->len);
-	usbd_ep_enqueue(c_data, buf);
+	ret = usbd_ep_enqueue(c_data, buf);
+	if (ret) {
+		LOG_ERR("Failed to enqueue net_buf for 0x%02x", ep);
```
Comment (tmon-nordic) [inline subsys/usb/device_next/class/bt_hci.c]: Code will most likely deadlock on waiting for `sync_sem`.

Comment (rruuaanng) [reply subsys/usb/device_next/class/bt_hci.c]: I think that when `ret` is non-zero, it should execute:
```
k_sem_take(&hci_data->sync_sem, K_FOREVER);
net_buf_unref(buf);
```
Before exiting, but you mentioned that a deadlock could occur. After I removed those statements, you still warned about a potential deadlock, which left me confused. Maybe I missed something?

Edit:

It seems that this part only logs a message, and everything else remains unchanged. :--)

Comment (tmon-nordic) [reply subsys/usb/device_next/class/bt_hci.c]: There are two files changed in this PR, the deadlock comment was about change in usbd_cdc_ecm.c.

File: subsys/usb/device_next/class/usbd_cdc_ecm.c [hunk 5]
```diff
@@ -523,7 +525,14 @@ static int cdc_ecm_send(const struct device *dev, struct net_pkt *const pkt)
 		udc_ep_buf_set_zlp(buf);
 	}
 
-	usbd_ep_enqueue(c_data, buf);
+	ep = cdc_ecm_get_bulk_out(c_data);
```
Comment (tmon-nordic) [inline subsys/usb/device_next/class/usbd_cdc_ecm.c]: The buffer is allocated a few lines above using `buf = cdc_ecm_buf_alloc(cdc_ecm_get_bulk_in(c_data));`. The log will incorrectly show out ep instead of in ep.

**Review by tmon-nordic — CHANGES_REQUESTED** [review]

**Comment by rruuaanng** [comment]
It looks like `bt_hci` has been done.

File: subsys/usb/device_next/class/usbd_cdc_ecm.c [hunk 6]
```diff
@@ -504,6 +506,7 @@ static int cdc_ecm_send(const struct device *dev, struct net_pkt *const pkt)
 		return -EACCES;
 	}
 
+	ep = cdc_ecm_get_bulk_out(c_data);
 	buf = cdc_ecm_buf_alloc(cdc_ecm_get_bulk_in(c_data));
```
Comment (jfischer-no) [inline subsys/usb/device_next/class/usbd_cdc_ecm.c]: It should be IN endpoint, like in the line below.

```suggestion
	ep = cdc_ecm_get_bulk_in(c_data);
	buf = cdc_ecm_buf_alloc(ep);
```

**Review by jfischer-no — APPROVED** [review]

**Review by tmon-nordic — APPROVED** [review]
