### PR TITLE
mgmt: mcumgr: transport: smp_bt: Fix deadlock on disconnect with data

### LINKED ISSUE #51594: mgmt: mcumgr: bt: thread freezes if device disconnects
**Describe the bug**
The smp thread will freeze if there a pending response to go out but the device has disconnected, this is caused by, despite the connection having been dropped, the connection index and MTU are still seemingly valid, presumably because the connection ref count is increased when the first message is received, therefore a check needs to be added to ensure that the connection is still valid before waiting for a semaphore.

**Impact**
Showstopper

**Environment (please complete the following information):**
 - Commit SHA or Version used: b8a957a0ebd955ed65b7f1e64c74dac794a37fb3

### PR DESCRIPTION
**Pull request by nordicjm**
This fixes an issue with the bluetooth transport whereby if a device drops the connection prior to receiving all the output data it could cause a deadlock.

Fixes #51594

### CODE REVIEW

File: subsys/mgmt/mcumgr/transport/smp_bt.c [hunk 1]
```diff
@@ -387,13 +387,30 @@ static int smp_bt_tx_pkt(struct net_buf *nb)
...
 	if (conn == NULL) {
 		rc = MGMT_ERR_ENOENT;
 		goto cleanup;
 	}
 
+	/* Verify that the device is connected, the necessity for this check is that the remote
+	 * device might have sent a command and disconnected before the command has been processed
+	 * completely, if this happens then the the connection details will still be valid due to
+	 * the incremented connection reference count, but the connection has actually been
+	 * dropped, this avoid waiting for a semaphore that will never be given and would
```
Comment (de-nordic) [inline subsys/mgmt/mcumgr/transport/smp_bt.c:402]: avoids?

File: doc/releases/release-notes-3.3.rst [hunk 2]
```diff
@@ -251,6 +251,9 @@ Libraries / Subsystems
     if the file exists. This can help work around an issue whereby logging is
     enabled and the command is sent on the same UART as the logging system, in
     which a filesystem error was emitted.
+  * A MCUMGR issue with Bluetooth transport that could cause a deadlock of the
```
Comment (de-nordic) [inline doc/releases/release-notes-3.3.rst:254]: I think correct name is `MCUmgr`.

**Review by de-nordic — DISMISSED** [review]
Looks OK, some comments left.

File: doc/releases/release-notes-3.3.rst (hunk 2 above)
Comment (nordicjm) [reply doc/releases/release-notes-3.3.rst]: Fixed

File: subsys/mgmt/mcumgr/transport/smp_bt.c (hunk 1 above)
Comment (nordicjm) [reply subsys/mgmt/mcumgr/transport/smp_bt.c]: Fixed

**Review by de-nordic — DISMISSED** [review]

**Review by carlescufi — DISMISSED** [review]

**Review by carlescufi — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]
