### PR TITLE
drivers: crypto: crypto_ataes132a fix memset undefined behavior

### LINKED ISSUE #81943: [Coverity CID: 434642] Out-of-bounds read in drivers/crypto/crypto_ataes132a.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/b1def7145fd/drivers/crypto/crypto_ataes132a.c#L629

Category: Memory - illegal accesses
Function: `ataes132a_aes_ecb_block`
Component: Drivers
CID: [434642](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434642)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/b1def7145fd/drivers/crypto/crypto_ataes132a.c#L629

```
623      k_sem_take(&data->device_sem, K_FOREVER);
624    
625      param_buffer[0] = 0x0;
626      param_buffer[1] = key_id;
627      param_buffer[2] = 0x0;
628      memcpy(param_buffer + 3, pkt->in_buf, buf_len);
>>>     CID 434642:  Memory - illegal accesses  (OVERRUN)
>>>     Overrunning array of 19 bytes at byte offset 19 by dereferencing pointer "param_buffer + 3 + buf_len". [Note: The source code implementation of the function has been overridden by a builtin model.]
629      (void)memset(param_buffer + 3 + buf_len, 0x0, 16 - buf_len);
630    
631      return_code = ataes132a_send_command(dev, ATAES_LEGACY_OP, 0x00,
632                                           param_buffer, buf_len + 3,
633                                           param_buffer, &out_len);
634    
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_OVERRUN). ([CWE-125](http://cwe.mitre.org/data/definitions/125.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=434642

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by ljd42**
Coverity reported a memory - illegal accesses when using memset in ataes132a_aes_ecb_block(). This can happen when the input block is exactly 16 bytes: memset(&param_buffer[19], 0x0, 0) is called. But this is an undefined behaviour in C even if size is 0, as &param_buffer[19] is an invalid pointer.

The fix consists of simply skipping memset() in this case, since there's nothing to zero out.

Coverity CID: 434642
Fixes: #81943

### CODE REVIEW

File: drivers/crypto/crypto_ataes132a.c [hunk 1]
```diff
@@ -634,7 +634,14 @@ int ataes132a_aes_ecb_block(const struct device *dev,
 	param_buffer[1] = key_id;
 	param_buffer[2] = 0x0;
 	memcpy(param_buffer + 3, pkt->in_buf, buf_len);
-	(void)memset(param_buffer + 3 + buf_len, 0x0, 16 - buf_len);
+	/* skip memset() if buf_len==16.
+	 * Indeed, calling memset(&param_buffer[19], 0x0, 0)
+	 * is an undefined behaviour in C as &param_buffer[19] is
+	 * an invalid pointer (even if size is 0).
+	 */
+	if (buf_len < 16) {
```
Comment (msalau) [inline drivers/crypto/crypto_ataes132a.c:642]: Wn`buf_len == 16` `memset()` is not skipped but the comment above tells otherwise.

I think this should fix it ⬇️:
```diff
-if (buf_len < 16) {
+if (buf_len <= 16) {
```

**Review by ceolin — APPROVED** [review]

**Review by kartben — APPROVED** [review]
