### PR TITLE
drivers: serial: nrf uarte: Fix for the RX byte counter

### LINKED ISSUE #33280: drivers: serial: nrf uarte: The application receives one more byte that was received over UART
**Describe the bug**
The application receives one more byte that was received, due to RX counter alignment upon ENDRX event.
In case of the following sequence of UART events:
 - UART_ENDRX
 - UART_RXRDY
 - TIMER_RXTIMEOUT

The application receives one more byte that was received, due to RX counter alignment upon ENDRX event.

**Expected behavior**
The application should receive the exact amount of bytes that was received by the UART peripheral.

**Impact**
This issue may break data transfers, that require at least two UART transmissions, with the delay between them.

**Environment:**
 - OS: Linux
 - Toolchain: NCS SDK
 - NCS v1.3.0

**Additional context**
The issue was found during Zigbee NCP serial transport development. It was mitigated by switching from `UART_ASYNC_API` to the `UART_INTERRUPT_DRIVEN` mode (https://github.com/nrfconnect/sdk-nrf/pull/2835).
After switching, a new way of reproducing the issue was not developed.

### PR DESCRIPTION
**Pull request by tomchy**
In case of the following sequence of UART events:
 - UART_ENDRX
 - UART_RXRDY
 - TIMER_RXTIMEOUT

The application receives one more byte that was received, due to RX counter alignment upon ENDRX event.

The proposed fix moves the RX byte counter alignment to the RX timeout event handler.

Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>

Fixes #33280.

### CODE REVIEW

File: drivers/serial/uart_nrfx_uarte.c [hunk 1]
```diff
@@ -931,6 +931,17 @@ static void rx_timeout(struct k_timer *timer)
 	int32_t len = data->async->rx_total_byte_cnt
 		    - data->async->rx_total_user_byte_cnt;
 
+	if (!hw_rx_counting_enabled(data) &&
+	    (len < 0)) {
+		/* Prevent too low value of rx_cnt.cnt which may occur due to
+		 * latencies in handling of the RXRDY interrupt. Because whole
+		 * buffer was filled we can be sure that rx_total_user_byte_cnt
+		 * is current total number of received bytes.
```
Comment (anangl) [inline drivers/serial/uart_nrfx_uarte.c:939]: The second sentence in this comment is a bit confusing in this context, as we don't handle a filled buffer here. I suggest to replace it with something like: "at this point, the number of received bytes is at least equal to what was reported to the user".

**Comment by anangl** [comment]
@tomchy I think this one can be taken out of draft.

File: drivers/serial/uart_nrfx_uarte.c (hunk 1 above)
Comment (tomchy) [reply drivers/serial/uart_nrfx_uarte.c]: Updated according to the suggestion.

**Review by anangl — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
