### PR TITLE
usb: device_next: fix Get Status request response

### LINKED ISSUE #85095: usb: device: next: USB_SREQ_GET_STATUS for USB_REQTYPE_RECIPIENT_DEVICE always reports D0 as "bus powered"
**Describe the bug**
According to Figure 9-4 in the "Universal Serial Bus Specification Revision 2.0" (usb_20.pdf), the USB device should return `D0=1` for self-powered devices, `D0=0` for bus powered devices upon `USB_SREQ_GET_STATUS` for `USB_REQTYPE_RECIPIENT_DEVICE`.

The "device_next" stack always reports `D0=0`, regardless of any attributes passed to `USBD_CONFIGURATION_DEFINE()` (and there is no way to change this status at run-time).

**To Reproduce**
1. `west build -b lpcxpresso55s16/lpc55s16 samples/subsys/usb/webusb-next/`
2. `west flash`
3. See mismatch when requesting device status via `lsusb`, below.

**Expected behavior**
Device status should report `D0` correctly.

**Impact**
Wrong device status reported.

**Logs and console output**
```
$ sudo lsusb -v -d 2fe3:000a|grep 'Powered'
      Self Powered
  (Bus Powered)
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 24.04
 - Toolchain: Zephyr SDK v0.17
 - Commit SHA: b5c5ba8c832b8ac01b03a8a26ba76a49438b6cc5

**Additional context**
- The function `sreq_get_status()` correctly reports `D1` indicating remote wakeup support but `D0` is not set. See https://github.com/zephyrproject-rtos/zephyr/blob/b5c5ba8c832b8ac01b03a8a26ba76a49438b6cc5/subsys/usb/device_next/usbd_ch9.c#L421
- The corresponding `usb_get_status()` function in the current stack sets `D0` based on the `CONFIG_USB_SELF_POWERED` Kconfig option. See https://github.com/zephyrproject-rtos/zephyr/blob/b5c5ba8c832b8ac01b03a8a26ba76a49438b6cc5/subsys/usb/device/usb_device.c#L432

### PR DESCRIPTION
**Pull request by jfischer-no**
Set the Self Powered field if the device is self-powered in the current configuration.
Fixes: #85095

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
Thanks, this brings the `device_next` stack on par with the existing USB device stack, however, it would be nice to be able to affect this status at runtime as well. According the USB 2.0 spec:

> The Self Powered field indicates whether the device is currently self-powered. If D0 is reset to zero, the
device is bus-powered. If D0 is set to one, the device is self-powered.

So a run-time API for the application to set whether the device is currently bus or self powered would be needed.

**Comment by jfischer-no** [comment]
> Thanks, this brings the `device_next` stack on par with the existing USB device stack, however, it would be nice to be able to affect this status at runtime as well. According the USB 2.0 spec:
> 
> > The Self Powered field indicates whether the device is currently self-powered. If D0 is reset to zero, the
> > device is bus-powered. If D0 is set to one, the device is self-powered.
> 
> So a run-time API for the application to set whether the device is currently bus or self powered would be needed.

You need to specify where at runtime, not sure if https://github.com/zephyrproject-rtos/zephyr/blob/b7cfa54c18374eeeec141326fcc7052c7d1078fc/include/zephyr/usb/usbd.h#L1172 is what you are asking for. But that is not related to this PR, this fixes a bug you reported, now you are asking for a feature.

File: subsys/usb/device_next/usbd_ch9.c [hunk 1]
```diff
@@ -394,6 +394,19 @@ static int std_request_to_device(struct usbd_context *const uds_ctx,
...
 }
 
+/* The device state must be verified before calling this function. */
+static bool cfg_is_self_powered(struct usbd_context *const uds_ctx)
+{
+	struct usb_cfg_descriptor *cfg_desc;
+	struct usbd_config_node *cfg_nd;
+
+	cfg_nd = usbd_config_get_current(uds_ctx);
+	__ASSERT(cfg_nd != NULL, "Device is not in a configured state");
```
Comment (tmon-nordic) [inline subsys/usb/device_next/usbd_ch9.c:404]: Get Status request is allowed when device is in Address state. This assert will fail if Get Status is called in Address state, which is invalid use of assert (assert should hit on programmer/code errors, not on rarely occurring perfectly fine requests).

**Review by tmon-nordic — CHANGES_REQUESTED** [review]

File: subsys/usb/device_next/usbd_ch9.c (hunk 1 above)
Comment (jfischer-no) [reply subsys/usb/device_next/usbd_ch9.c]: I actually missed that about the address state and was confused about how it was in the legacy stack, but we cannot do it that way.

**Review by tmon-nordic — APPROVED** [review]

**Comment by jfischer-no** [comment]
@henrikbrixandersen , please review, it fixes the bug you reported.

**Review by carlescufi — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
