### PR TITLE
tests: debug/coredump: Change to call k_panic() for ISH SoCs

### LINKED ISSUE #79698: it8xxx2_evb: debug.coredump.logging_backend Timeout
**Describe the bug**
Test debug.coredump.logging_backend timeout on it8xxx2_evb (also repro on intel_ish_5_4_1)

I did bisection and found a commit that breaks it: https://github.com/zephyrproject-rtos/zephyr/commit/3723493f60a10f17d8d117fb8288a75da20cdd74
If I change this line manualy (remove __no_optimization) in main.c, the test pass.

**To Reproduce**
```
twister -p it8xxx2_evb --device-testing --west-flash="<ITE_TOOL_PATH>" --device-serial=<DEV_SERIAL> -s tests/subsys/debug/coredump/debug.coredump.logging_backend -ll DEBUG
```

**Expected behavior**
Test should pass

**Logs and console output**
```
DEBUG   - DEVICE: *** Booting Zephyr OS build v3.7.0-4288-g4793e00ae803 (delayed boot 1ms) ***
DEBUG   - DEVICE: Coredump: it8xxx2_evb
DEBUG   - HARNESS:Console:EXPECTED(1/9):'Coredump: (.*)'
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK 0.16.8
 - Version : v3.7.0-4288-g4793e00ae803

### PR DESCRIPTION
**Pull request by kwd-doodling**
ISH SoCs have zero-address memory mapped to I2C0 controller. Coredump cannot be triggered by zero-address access.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/79698

### CODE REVIEW

File: tests/subsys/debug/coredump/src/main.c [hunk 1]
```diff
@@ -39,7 +39,8 @@ __no_optimization void func_3(uint32_t *addr)
 	defined(CONFIG_BOARD_LONGAN_NANO) || \
 	defined(CONFIG_BOARD_QEMU_XTENSA) || \
 	defined(CONFIG_BOARD_RISCV32_VIRTUAL) || \
-	defined(CONFIG_SOC_FAMILY_INTEL_ADSP)
+	defined(CONFIG_SOC_FAMILY_INTEL_ADSP) || \
+	defined(CONFIG_SOC_FAMILY_INTEL_ISH)
```
Comment (dcpleung) [inline tests/subsys/debug/coredump/src/main.c:43]: You can add the entry before the last one, so that there is no need to modify existing ones.

Comment (kwd-doodling) [reply tests/subsys/debug/coredump/src/main.c]: change already as suggested. thanks.

**Review by dcpleung — APPROVED** [review]

**Review by mrkhldn — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@nashif , can you help take a look at this PR.

**Review by nashif — APPROVED** [review]
