### PR TITLE
Bluetooth: Mesh: Fix lpn groups add when node reset

### LINKED ISSUE #24009: Bluetooth: Mesh: Friend node not cache ALL_Node Address or different app_idx
Set up there nodes, call publish node, friend node ,lpn node.

All node share single network key, but friend & lpn node with different application key, 
the lpn node has same application key will publish node.

when publish node periodic send model message with the dst = 0xffff, lpn node not receive all of them.

### LINKED ISSUE #24311: LPN not receiving any message from Friend node after LPN device reset
**Describe the bug**

I've added a Generic On-Off model in mesh_shell code to publish a message from Friend node to LPN node. it's working fine after provision and configuration 

Now if I reset the LPN node then  friendship get's established again but it doesn't receive any message from friend.

**To Reproduce**
1. git clone https://github.com/rhardik/reproduce-zephyr-issues.git
2. cd lpn-node-reset
3. comment the line `zephyr_library_sources_ifdef(CONFIG_BT_MESH_SHELL shell.c)`  from `zephyr/subsys/bluetooth/mesh/CMakeLists.txt`
4. compile friend and lpn code and flash the code to device
5. open serial terminal and press enter. you will see a shell  with $uart
6. Type command "mesh init" and then "mesh pb-gatt on" (for both device)
7. Open nRF mesh android app. Provision and then  
             - configure "generic on-off client" on Friend node  with publish address 0xc000
             - configure "generic on-ff server: LPN node with subscribe address 0xc000
8. Type command "mesh lpn on" in LPN terminal and "mesh friend on" in Friend terminal.
9. Now type command "mesh hello" on Friend terminal
   - After few seconds you should see "HHHHEEELLLLOOOO" string on LPN terminal.
10. Now reset LPN device then 
       - type command  "mesh init" and "mesh lpn on" in LPN terminal and 
       - type "mesh hello" command in Friend terminal 
and now it should print "HHHHEEELLLLOOOO" string on LPN terminal but it won't.

**Expected behavior**
After device reset also it should work.

**Impact**
showstopper

**Screenshots or console output**
Message sent by Friend node (working)
------------------------------
\`\`\`
:~$ mesh hello                                                                                                
[00:28:08.686,004] <dbg> bt_mesh_friend.bt_mesh_friend_match: LPN 0x0003 matched address 0xc000                   
[00:28:08.686,035] <dbg> bt_mesh_friend.bt_mesh_friend_enqueue_tx: net_idx 0x0000 dst 0xc000 src 0x0002           
[00:28:08.686,065] <dbg> bt_mesh_friend.friend_lpn_enqueue_tx: LPN 0x0003                                         
[00:28:08.686,096] <dbg> bt_mesh_friend.enqueue_friend_pdu: type 0                                                
[00:28:08.686,096] <dbg> bt_mesh_friend.friend_lpn_enqueue_tx: Queued message for LPN 0x0003                      
[00:28:09.059,539] <dbg> bt_mesh_friend.bt_mesh_friend_match: LPN 0x0003 matched address 0xc000                   
[00:28:09.059,539] <dbg> bt_mesh_friend.bt_mesh_friend_enqueue_tx: net_idx 0x0000 dst 0xc000 src 0x0002           
[00:28:09.059,570] <dbg> bt_mesh_friend.friend_lpn_enqueue_tx: LPN 0x0003                                         
[00:28:09.059,600] <dbg> bt_mesh_friend.enqueue_friend_pdu: type 0                                                
[00:28:09.059,600] <dbg> bt_mesh_friend.friend_lpn_enqueue_tx: Queued message for LPN 0x0003 
\`\`\`

Message received by LPN node
------------------------------
\`\`\`
uart:~$
HHHHEEELLLLOOOO                                                                                                   
[00:28:08.183,135] <dbg> bt_mesh_lpn.lpn_timeout: state: established                                              
[00:28:08.183,166] <dbg> bt_mesh_lpn.send_friend_poll: lpn->sent_req 0x00                                         
[00:28:08.184,356] <dbg> bt_mesh_lpn.req_sent: req 0x01 duration 90 err 0 state established                       
[00:28:08.184,387] <dbg> bt_mesh_lpn.lpn_set_state: established -> recv delay                                     
[00:28:08.274,475] <dbg> bt_mesh_lpn.lpn_timeout: state: recv delay                                               
[00:28:08.276,123] <dbg> bt_mesh_lpn.lpn_set_state: recv delay -> wait update                                     
[00:28:08.358,062] <dbg> bt_mesh_lpn.friend_response_received: lpn->sent_req 0x01                                 
[00:28:08.358,367] <dbg> bt_mesh_lpn.lpn_set_state: wait update -> established                                    
[00:28:08.358,367] <dbg> bt_mesh_lpn.bt_mesh_lpn_msg_received: Requesting more messages from Friend               
[00:28:08.358,367] <dbg> bt_mesh_lpn.send_friend_poll: lpn->sent_req 0x00                                         
[00:28:08.359,619] <dbg> bt_mesh_lpn.req_sent: req 0x01 duration 90 err 0 state established                       
[00:28:08.359,619] <dbg> bt_mesh_lpn.lpn_set_state: established -> recv delay                   
\`\`\`

Friend side logs when reset LPN
-----------------------------------------------------
\`\`\`
36:27.304,718] <dbg> bt_mesh_friend.friend_timeout: lpn 0x0003 send_last 0 last 0x20006584                    
[00:36:27.304,748] <wrn> bt_mesh_friend: Friendship lost with 0x0003                                              
[00:36:27.304,748] <dbg> bt_mesh_friend.friend_clear: LPN 0x0003  
\`\`\`

Friend logs when sending message to LPN (after LPN reboots)
--------------------------------------------------------------------------------------------
\`\`\`
uart:~$ mesh hello                                                                                                
[00:38:11.604,278] <dbg> bt_mesh_friend.bt_mesh_friend_match: No matching LPN for address 0xc000                  
[00:38:11.977,630] <dbg> bt_mesh_friend.bt_mesh_friend_match: No matching LPN for address 0xc000                  
[00:38:22.377,380] <dbg> bt_mesh_friend.bt_mesh_friend_match: No matching LPN for address 0x0002                  
[00:38:22.384,185] <dbg> bt_mesh_friend.bt_mesh_friend_find: net_idx 0x0000 lpn_addr 0x0003                       
[00:38:22.384,216] <dbg> bt_mesh_friend.bt_mesh_friend_poll: msg->fsn 0 frnd->fsn 1                               
[00:38:22.384,216] <dbg> bt_mesh_friend.friend_recv_delay: Waiting RecvDelay of 151 ms                            
[00:38:22.384,246] <dbg> bt_mesh_friend.encode_update: lpn 0x0003 md 0x00                                         
[00:38:22.384,246] <dbg> bt_mesh_friend.encode_friend_ctl: LPN 0x0003                                             
[00:38:22.384,307] <dbg> bt_mesh_friend.bt_mesh_friend_poll: Enqueued Friend Update to empty queue                
[00:38:22.535,278] <dbg> bt_mesh_friend.friend_timeout: lpn 0x0003 send_last 0 last 0x00000000                    
[00:38:22.535,308] <dbg> bt_mesh_friend.update_overwrite: Update Previous Friend Update MD 0x00 -> 0x00           
[00:38:22.535,430] <dbg> bt_mesh_friend.friend_timeout: Sending buf 0x20006584 from Friend Queue of LPN 0x0003    
[00:38:22.537,567] <dbg> bt_mesh_friend.buf_send_start: err 0                                                     
[00:38:22.598,693] <dbg> bt_mesh_friend.buf_send_end: err 0 
\`\`\`

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: a3fae2f153587c552623ad4940eb6e058aeec78f

### PR DESCRIPTION
**Pull request by LingaoM**
Add lpn groups when model sub restore after reset.

Add auto sub `ALL_NODE_ADDR` when provisioned.

Remove all groups when node unprovisoned.

Fixes: #24311
Fixes: #24009

Signed-off-by: Lingao Meng <mengabc1086@gmail.com>

### CODE REVIEW

**Review by jhedberg — CHANGES_REQUESTED** [review]
Please move the "all nodes" handling to a separate commit (still same PR though) since these are two distinct issues.

File: subsys/bluetooth/mesh/main.c [hunk 1]
```diff
@@ -123,6 +123,10 @@ int bt_mesh_provision(const u8_t net_key[16], u16_t net_idx,
 
 	memcpy(bt_mesh.dev_key, dev_key, 16);
 
+	if (IS_ENABLED(CONFIG_BT_MESH_LOW_POWER)) {
+		bt_mesh_lpn_group_add(BT_MESH_ADDR_ALL_NODES);
+	}
+
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/main.c:129]: IMO, this functionality should be compile time configurable. The working group made it opt-in for a reason, it's very easy to flood the friend queue with broadcast packets that might not be relevant for the LPN

Comment (jhedberg) [reply subsys/bluetooth/mesh/main.c:129]: Agreed, and I'd default to disabled for the new option (not just because it seems to be the safe choice but also to keep consistency with previous Zephyr versions).

Comment (jhedberg) [reply subsys/bluetooth/mesh/main.c:129]: An alternative would be to expose the group add/del functions as public API (and clearly document that they should only be used for special cases like this, whereas the stack takes automatically care of the rest). Thoughts?

Comment (jhedberg) [reply subsys/bluetooth/mesh/main.c:129]: Answering to myself: I'm mildly leaning toward the Kconfig since then the app can't mess around with what the stack manages automatically (e.g. remove groups that the stack had added, etc).

File: subsys/bluetooth/mesh/Kconfig [hunk 2]
```diff
@@ -413,6 +413,14 @@ config BT_MESH_LPN_GROUPS
 	default 8
 	help
 	  Maximum number of groups that the LPN can subscribe to.
+
+config BT_MESH_LPN_SUB_ALL_NODE_ADDR
+	bool "Automatically subscribe all node address"
+	default n
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/Kconfig:419]: `default n` is redundant, this line can be removed.

**Review by trond-snekvik — CHANGES_REQUESTED** [review]
Only one minor comment on the code changes, but please provide a proper commit title and body for your group recovery commit.

File: subsys/bluetooth/mesh/Kconfig [hunk 3]
```diff
@@ -413,6 +413,14 @@ config BT_MESH_LPN_GROUPS
 	default 8
 	help
 	  Maximum number of groups that the LPN can subscribe to.
+
+config BT_MESH_LPN_SUB_ALL_NODE_ADDR
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/Kconfig:417]: Call it `NODES` instead of `NODE` since that's how it is called in the spec

File: subsys/bluetooth/mesh/Kconfig [hunk 4]
```diff
@@ -413,6 +413,14 @@ config BT_MESH_LPN_GROUPS
...
+	bool "Automatically subscribe all node address"
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/Kconfig:418]: "nodes" here as well

**Review by jhedberg — APPROVED** [review]

**Review by trond-snekvik — APPROVED** [review]
