### PR TITLE
logging: syst: fix logging v2 with strings as arguments

### LINKED ISSUE #42462: logging: syst/v2: hang or crash if log contains string arguments
When using MIPI Sys-T output with v2 logging, the app may hang or crash if log messages contain string arguments. This is due to the string arguments in the valist being NULL, and the MIPI library is trying to deference the pointer to extract the strings for output.

To reproduce this, add a logging message with string arguments to `samples/subsys/logging/syst/`.

### PR DESCRIPTION
**Pull request by dcpleung**
The packaged string coming from logging subsys requires some
additional processing if there are string arguments.
These strings are actually embedded inside the package so
we need to replace the string pointers inside the argument
list so they actually point to those strings. Without this
extra step of processing, MIPI Sys-T's printf function would
process these arguments directly which may be NULL pointers
or invalid one pointing to somewhere. This adds the processing
so that log messages with string arguments can be outputted
correctly through MIPI.

### CODE REVIEW

File: subsys/logging/log_output_syst.c [hunk 1]
```diff
@@ -786,27 +786,97 @@ void log_output_msg2_syst_process(const struct log_output *output,
...
+		 * [sizeof(uint8_t *)]: Pointer to format string.
+		 *                      Can be NULL so needs further
+		 *                      processing.
+		 *
+		 * [sizeof(uint8_t *) * 2]: Start of arguments.
+		 *
+		 * [[0] * sizeof(uint32_t)]: Start of appended strings.
+		 */
+
+		uint8_t num_strings = data[1];
```
Comment (nordic-krch) [inline subsys/logging/log_output_syst.c:806]: This algorithm is already present in cbprintf https://github.com/zephyrproject-rtos/zephyr/blob/fdc25cd44c2b693aecff96d3dfcd0ee088d48d5b/lib/os/cbprintf_packaged.c#L602
but it is a part of formatting function. Seems like it would be worth to extract it and make public. Not sure what would be a good name for it. Something like `cbprintf_locate` or `cbrprintf_settle`?

It could be called by logging core before passing message to the backends.

File: samples/subsys/logging/syst/sample.yaml [hunk 2]
```diff
@@ -1,18 +1,36 @@
 sample:
   name: syst sample
 tests:
-  sample.logger.syst.v1:
-    platform_allow: mps2_an385 sam_e70_xplained
+  sample.logger.syst.v1.deferred:
+    extra_args: CONF_FILE=prj_v1_deferred.conf
```
Comment (nordic-krch) [inline samples/subsys/logging/syst/sample.yaml:5]: why not use `OVERLAY_CONFIG` here and keep all common stuff in `prj.conf`. Now there is a lot of redundancy in those config files.

File: subsys/logging/log_output_syst.c [hunk 3]
```diff
@@ -786,27 +786,97 @@ void log_output_msg2_syst_process(const struct log_output *output,
...
+				 * The output_buf contains the updated argument list.
+				 * So use this for output.
+				 */
+				output_buf = cb_buf;
+			}
+		}
 
-		fmt = ((char **)buf)[1];
-		buf += sizeof(char *) * 2;
+		if (output_buf != NULL) {
```
Comment (nordic-krch) [inline subsys/logging/log_output_syst.c:860]: There are corner cases for preparing va_list (xtensa, x86_64), see set of `cbprintf_via_va_list` functions: https://github.com/zephyrproject-rtos/zephyr/blob/fdc25cd44c2b693aecff96d3dfcd0ee088d48d5b/lib/os/cbprintf_packaged.c#L75

Given that maybe instead of `cbprintf_locate/settle` approach, it would be better to have something like `cbpprintf_external(ext_formatter func, void *ctx, void *packaged)` where external formatter would be function like `foo(void *ctx, const char *fmt, va_list ap)`.

File: samples/subsys/logging/syst/sample.yaml (hunk 2 above)
Comment (dcpleung) [reply samples/subsys/logging/syst/sample.yaml]: OVERLAY! That's the keyword I was looking for. Thanks. Updated.

File: subsys/logging/log_output_syst.c (hunk 3 above)
Comment (dcpleung) [reply subsys/logging/log_output_syst.c]: I have updated `cbprintf_packaged.c` to use external formatter. Hopefully this aligns with what you are suggesting.

**Review by npitre — APPROVED** [review]
OK but please fix the typo in .

**Review by nordic-krch — APPROVED** [review]
looks good.

**Review by MaureenHelm — APPROVED** [review]
