### PR TITLE
tracing: swap: bug fix and enhancement for ARC

### LINKED ISSUE #27771: iotdk: cpu_stats function doesn't work as expected
**Describe the bug**
cpu_stats profiling function doesn’t work as expected, it always report cpu usage 100 even if cpu in idle thread for a long time. It looks like the cpu_stats hooks does not have a chance to count the switch in of idle thread (stats_hw_tick.idle always 0). 

```
Hello World! iotdk
CPU usage: 100
CPU usage: 100
CPU usage: 100
CPU usage: 100
CPU usage: 100
```
It always report cpu usage 100%, and global variable stats_hw_tick.idle is 0, but I confirmed cpu can enter idle

**To Reproduce**
1. Use latest master c64e0ce923cde54415d203e447a1dc62894ed2b0
2. SDK 0.11.4
3. Go to samples/hello_world
4. Add to prj.conf configuration for turning on cpu_stats:
```
CONFIG_TRACING=y
CONFIG_TRACING_CPU_STATS=y
CONFIG_TRACING_CPU_STATS_LOG=y
```
5. west build -p -b iotdk samples/hello_world/
6. west flash
7. View the output

**Expected behavior**
When system idle, the cpu usage reported should not be always 100%
My expectation
```
Hello World! iotdk
CPU usage: 0
CPU usage: 0
CPU usage: 0
CPU usage: 0
CPU usage: 0
```

**Impact**
Wrong cpu_stats function execution on the arc board.

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS
 - Toolchain Zephyr SDK 0.11.4
 - Commit SHA c64e0ce923cde54415d203e447a1dc62894ed2b0

### PR DESCRIPTION
**Pull request by IRISZZW**
Describe in #27771 cpu_stats profiling function doesn’t work as expected. we need to do some fixes.

For regular context switch: 
move switched_in into the arch context switch assembly code, 
which will correctly record the switched_in information.

For irq context switch: 
add switched_in/switched_out for context switch in irq exit.

Fixes: #27771

### CODE REVIEW

File: kernel/include/kswap.h [hunk 1]
```diff
@@ -117,7 +117,7 @@ static ALWAYS_INLINE unsigned int do_swap(unsigned int key,
 		wait_for_switch(new_thread);
 		arch_switch(new_thread->switch_handle,
 			     &old_thread->switch_handle);
-		sys_trace_thread_switched_in();
+
```
Comment (IRISZZW) [inline kernel/include/kswap.h:120]: other architectures such as: x86, xtensa also need to add sys_trace_thread_switched_in() in its own arch_switch code.

**Review by IRISZZW — COMMENTED** [review]
https://github.com/zephyrproject-rtos/zephyr/blob/0617e1aebdffedeca441d4675e4fe3b674f43ab7/arch/xtensa/core/xtensa-asm2-util.S#L188
https://github.com/zephyrproject-rtos/zephyr/blob/0617e1aebdffedeca441d4675e4fe3b674f43ab7/arch/x86/core/intel64/locore.S#L289

**Review by nashif — APPROVED** [review]

File: kernel/include/kswap.h (hunk 1 above)
Comment (nashif) [reply kernel/include/kswap.h:120]: xtensa is already covered

**Review by dcpleung — APPROVED** [review]

**Comment by chen-png** [comment]
@IRISZZW  Could you backport this patch into 1.14 branch ? there were some conflicts with 1.14.
