### PR TITLE
Stm32 lptim fix

### LINKED ISSUE #25944: driver: timer: stm32_lptim: Extra ticks count
**Describe the bug**
Some ticks are counted additionally when a program sleeps for a short time.

**To Reproduce**
I have a test program which compare rtc and lptimer counter. Both work with LSE clock so I can monitor that the two counters are equal. It looks like this:
```
while (1) {
 /* Read rtc counter */
 ...
 /* Read lptimer counter */
 ...
 /* Compare rtc and lptimer counter*/
 ...
 for (int i=0; i < 4000; i++)                                                                                                                                                                                                
  k_sleep(K_TICKS(2));
}
```

### PR DESCRIPTION
**Pull request by jdascenzio**
I'm working again on the stm32 lptimer. I found some excess ticks count with the current lptimer implementation. I have a test program which compare rtc and lptimer counter. Both work with LSE clock so I can monitor that the two counters are equal. I created a new patch which seems to solve the problem for me. Are you ok with it?

fix #25944

### CODE REVIEW

**Comment by erwango** [comment]
@jdascenzio can you raise and issue, so it can be integrated in v2.3.0 if approved ?

**Review by aurel32 — APPROVED** [review]
The first commit is just theoretical due to #25952, however it is indeed correct. In addition it's better to busy wait for ARROK just before it's actually need as 1) it make the code easier to read 2) it can spare a few CPU cycles in some (rare ?) cases.

The second commit LGTM.

File: drivers/timer/stm32_lptim_timer.c [hunk 1]
```diff
@@ -227,15 +229,20 @@ void z_clock_set_timeout(s32_t ticks, bool idle)
...
+	/* If the autoreload interrupts are too close together,
+	 * it will be impossible to guarantee to set autoreload correctly:
+	 * we must have at least 2 clock cycle to have some times to set
+	 * new autoreload value.
 	 */
-	if (next_arr <= ((lp_time + 1) & LPTIM_TIMEBASE)) {
-		NVIC_SetPendingIRQ(LPTIM1_IRQn);
-		lptim_fired = 1;
+	else if (next_arr < 2) {
+		next_arr = 2;
```
Comment (FRASTM) [inline drivers/timer/stm32_lptim_timer.c:245]: BTW, if the guard value is at least 2 lptim clock cycles, could it be a kind of constant _LPTIM_GUARD_VALUE_
for each comparison here and at lines above.

**Comment by jdascenzio** [comment]
add LPTIM_GUARD_VALUE constant

**Review by FRASTM — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Comment by gmarull** [comment]
Isn't the second `else if` redundant? 

```c
	/* The new autoreload value must be LPTIM_GUARD_VALUE clock cycles
	 * after current lptim to make sure we don't miss
	 * an autoreload interrupt
	 */
	else if (next_arr < (lp_time + LPTIM_GUARD_VALUE)) {
		next_arr = lp_time + LPTIM_GUARD_VALUE;
	}

	/* If the autoreload interrupts are too close together,
	 * it will be impossible to guarantee to set autoreload correctly:
	 * we must have at least LPTIM_GUARD_VALUE clock cycles
	 * to have some times to set new autoreload value.
	 */
	else if (next_arr < LPTIM_GUARD_VALUE) {
		next_arr = LPTIM_GUARD_VALUE;
	}
```

```
------K-----K+y----------
______________/
     x < K + y
------K------------------
______/
 x < K

where K = LPTIM_GUARD_VALUE, y = lp_time, x = next_arr.
```
If first condition is not true, neither will be the second, as the first comparison is always against an equal or greater value.

**Review by gmarull — APPROVED** [review]
