### PR TITLE
arch: arm: cortex_m: fix incorrect conversion from ASM to C of cpu_idle operations.

### LINKED ISSUE #71552: samples: subsys: usb: mass: sample.usb.mass_flash_littlefs fails
**Describe the bug**
The test `sample.usb.mass_flash_littlefs` fails.

Observed for:
- `nrf52840dk/nrf52840`
- `nrf5340dk/nrf5340/cpuapp`

**To Reproduce**
1. have `nrf52840dk/nrf52840` connected
2. go to your zephyr dir
3. call `./scripts/twister -T samples/subsys/usb/mass -p nrf52840dk/nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
[00:00:00.396,270] <inf> flashdisk: Initialize device NAND
[00:00:00.396,270] <inf> flashdisk: offset 0, sector size 512, page size 4096, volume size 131072
Area 0 at 0x0 on mx25r6435f@0 for 131072 bytes
[00:00:00.396,514] <inf> littlefs: LittleFS version 2.8, disk version 2.1
[00:00:00.396,575] <inf> littlefs: FS at mx25r6435f@0:0x0 is 32 0x1000-byte blocks with 512 cycle
[00:00:00.396,575] <inf> littlefs: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
[00:00:00.396,667] <wrn> littlefs: can't mount (LFS -5); formatting
[00:00:00.396,697] <err> littlefs: format failed (LFS -5)
[00:00:00.396,697] <err> fs: fs mount error (-5)
[00:00:00.396,728] <err> main: Failed to mount filesystem
[00:00:00.396,789] <inf> main: The device is put in USB mass storage mode.

[00:00:00.396,789] <err> os: ***** HARD FAULT *****
[00:00:00.396,820] <err> os:   Fault escalation (see below)
[00:00:00.396,820] <err> os: ***** BUS FAULT *****
[00:00:00.396,820] <err> os:   Precise data bus error
[00:00:00.396,850] <err> os:   BFAR Address: 0x4bf00bd
[00:00:00.396,850] <err> os: r0/a1:  0x00000002  r1/a2:  0x00008026  r2/a3:  0x00000000
[00:00:00.396,881] <err> os: r3/a4:  0x04bf00bd r12/ip:  0x00007029 r14/lr:  0x00000d6b
[00:00:00.396,881] <err> os:  xpsr:  0x81000000
[00:00:00.396,881] <err> os: Faulting instruction address (r15/pc): 0x00000e5e
[00:00:00.396,911] <err> os: >>> ZEPHYR FATAL ERROR 25: Unknown error on CPU 0
[00:00:00.396,942] <err> os: Current thread: 0x20000af0 (unknown)
[00:00:01.957,427] <err> os: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.5
 - Commit SHA or Version used: `v3.6.0-2554-g2c8ea07b3498`

### LINKED ISSUE #71554: subsys: settings: file: settings.file.raw fails
**Describe the bug**
The test `settings.file.raw` fails.

Observed for:

- `nrf52840dk/nrf52840`
- `nrf5340dk/nrf5340/cpuapp`

**To Reproduce**
1. have `nrf52840dk/nrf52840` connected
2. go to your zephyr dir
3. call `./scripts/twister -T subsys/settings/file -p nrf52840dk/nrf52840 --device-testing --device-serial /dev/ttyACM0 -v --inline-logs`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
Running TESTSUITE settings_config
===================================================================
START - test_config_commit
PASS - test_config_commit in 0.001 seconds
===================================================================
START - test_config_empty_lookups
PASS - test_config_empty_lookups in 0.001 seconds
===================================================================
START - test_config_getset_int64
PASS - test_config_getset_int64 in 0.001 seconds
===================================================================
START - test_config_getset_int
PASS - test_config_getset_int in 0.001 seconds
===================================================================
START - test_config_getset_unknown
PASS - test_config_getset_unknown in 0.001 seconds
===================================================================
TESTSUITE settings_config succeeded
Running TESTSUITE settings_config_fs
===================================================================
Assumption failed at ../../../../../../../zephyr/tests/subsys/settings/file/src/settings_setup_littlefs.c:33: config_setup_fs: (rc == 0 is false)
erasing flash area [-5]
I: LittleFS version 2.8, disk version 2.1
I: FS at mx25r6435f@0:0x0 is 16 0x1000-byte blocks with 512 cycle
I: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
W: can't mount (LFS -5); formatting
E: format failed (LFS -5)
E: fs mount error (-5)
Assumption failed at ../../../../../../../zephyr/tests/subsys/settings/file/src/settings_setup_littlefs.c:36: config_setup_fs: (rc == 0 is false)
mounting littlefs [-5]
START - test_config_compress_file
SKIP - test_config_compress_file in 0.000 seconds
===================================================================
START - test_config_empty_file
SKIP - test_config_empty_file in 0.001 seconds
===================================================================
START - test_config_multiple_in_file
SKIP - test_config_multiple_in_file in 0.000 seconds
===================================================================
START - test_config_save_in_file
SKIP - test_config_save_in_file in 0.001 seconds
===================================================================
START - test_config_save_one_file
SKIP - test_config_save_one_file in 0.000 seconds
===================================================================
START - test_config_small_file
SKIP - test_config_small_file in 0.000 seconds
===================================================================
TESTSUITE settings_config_fs succeeded
------ TESTSUITE SUMMARY START ------
SUITE PASS - 100.00% [settings_config]: pass = 5, fail = 0, skip = 0, total = 5 duration = 0.005 seconds
- PASS - [settings_config.test_config_commit] duration = 0.001 seconds
- PASS - [settings_config.test_config_empty_lookups] duration = 0.001 seconds
- PASS - [settings_config.test_config_getset_int64] duration = 0.001 seconds
- PASS - [settings_config.test_config_getset_int] duration = 0.001 seconds
- PASS - [settings_config.test_config_getset_unknown] duration = 0.001 seconds
SUITE SKIP -   0.00% [settings_config_fs]: pass = 0, fail = 0, skip = 6, total = 6 duration = 0.002 seconds
- SKIP - [settings_config_fs.test_config_compress_file] duration = 0.000 seconds
- SKIP - [settings_config_fs.test_config_empty_file] duration = 0.001 seconds
- SKIP - [settings_config_fs.test_config_multiple_in_file] duration = 0.000 seconds
- SKIP - [settings_config_fs.test_config_save_in_file] duration = 0.001 seconds
- SKIP - [settings_config_fs.test_config_save_one_file] duration = 0.000 seconds
- SKIP - [settings_config_fs.test_config_small_file] duration = 0.000 seconds
------ TESTSUITE SUMMARY END ------
===================================================================
RunID: 693490c7707721c4913f0904f93984e0
PROJECT EXECUTION FAILED
```

**Environment (please complete the following information):**
- OS: Ubuntu 20.04.1 LTS
- Toolchain Zephyr SDK 0.16.5
- Commit SHA or Version used: `v3.6.0-2554-g2c8ea07b3498`

### LINKED ISSUE #71557: samples: drivers: spi_flash: sample.drivers.spi.flash fails
**Describe the bug**
The test `sample.drivers.spi.flash` fails.

Observed for:
- `nrf5340dk/nrf5340/cpuapp`
- `nrf5340dk/nrf5340/cpuapp/ns`

**To Reproduce**
1. have `nrf5340dk/nrf5340/cpuapp` connected
2. go to your zephyr dir
3. call `./scripts/twister -T samples/drivers/spi_flash -p nrf5340dk/nrf5340/cpuapp --device-testing --device-serial /dev/ttyACM1 -v --inline-logs`
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
*** Booting Zephyr OS build v3.6.0-2554-g2c8ea07b3498 ***
mx25r6435f@0 SPI flash testing
==========================
Perform test on single sector
Test 1: Flash erase
Flash erase failed! -5
Test 2: Flash write
Attempting to write 4 bytes
Flash write failed! -5
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.16.5
 - Commit SHA or Version used: `v3.6.0-2554-g2c8ea07b3498`

**Additional context**
`.conf` file is defined only for `nrf5340dk/nrf5340/cpuapp`.

### LINKED ISSUE #71596: Arm: Hard faults on nRF5340 and nRF52840 after #65071
**Describe the bug**
After https://github.com/zephyrproject-rtos/zephyr/pull/65071 got merged, running any Bluetooth application results in a hardfault on the nRF5340's application core. It also applies to all applications on the nRF52840 board. 

**To Reproduce**
Steps to reproduce the behavior for nRF5340:
1. Build and flash the [hci_ipc](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/hci_ipc) sample to the network core 
2. Build and flash the [peripheral](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/peripheral) sample to the application core
3. See error

Steps to reproduce the behavior for nRF52840:
1. Build and flash the [peripheral](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/peripheral) sample 
2. See error

**Expected behavior**
Expect samples to work

**Impact**
Blocks nearly all usage of the nRF5340 and nRF52840 boards

**Logs and console output**
```
*** Booting Zephyr OS build v3.6.0-2565-gb4eac67b8b2e ***
[00:00:00.423,309] <inf> fs_nvs: 6 Sectors of 4096 bytes
[00:00:00.423,309] <inf> fs_nvs: alloc wra: 0, fe8
[00:00:00.423,309] <inf> fs_nvs: data wra: 0, 0
[00:00:00.424,194] <err> bt_hci_driver: Endpoint binding failed with -11
[00:00:00.424,224] <err> bt_hci_core: HCI driver open failed (-11)
Bluetooth init failed (err -11)
[00:00:00.424,255] <err> os: ***** HARD FAULT *****
[00:00:00.424,255] <err> os:   Fault escalation (see below)
[00:00:00.424,285] <err> os: ***** BUS FAULT *****
[00:00:00.424,285] <err> os:   Precise data bus error
[00:00:00.424,285] <err> os:   BFAR Address: 0x0
[00:00:00.424,316] <err> os: r0/a1:  0x50000000  r1/a2:  0x00003ff0  r2/a3:  0x00000000
[00:00:00.424,316] <err> os: r3/a4:  0x00000005 r12/ip:  0x0000000c r14/lr:  0x0000152f
[00:00:00.424,316] <err> os:  xpsr:  0x89000000
[00:00:00.424,316] <err> os: Faulting instruction address (r15/pc): 0x000015e4
[00:00:00.424,346] <err> os: >>> ZEPHYR FATAL ERROR 25: Unknown error on CPU 0
[00:00:00.424,377] <err> os: Current thread: 0x200018b0 (main)
[00:00:00.535,034] <err> os: Halting system
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: b4eac67b8b2eee5381d58671fddb8ae9bf2a3989 but issue also appears with https://github.com/zephyrproject-rtos/zephyr/pull/71593

**Additional context**
Non Bluetooth samples are still working, such as the [hello_world](https://github.com/zephyrproject-rtos/zephyr) sample

### PR DESCRIPTION
**Pull request by ithinuel**
This mistake was introduced when converting from ASM to C.

The logic related to enterring sleep was swap.
Several irq masking/unmasking operations were also missing.

This change also restores the associated comment from the ASM source.

fixes https://github.com/zephyrproject-rtos/zephyr/issues/71596

### CODE REVIEW

**Comment by ithinuel** [comment]
@sjanc @gchwier @Thalley @nordic-piks I updated this PR with a fix to another discrepancy I saw in the `_atomic_` variant.

With this, the generated assembly is the same (modulo register allocation and some instruction optimizations).

I don’t have an NRF board at hand, would you mind giving it a try please?

**Comment by sjanc** [comment]
OK, updated PR seems to fix the issue for me,   I'll run few more tests that excise BT a bit more though

**Comment by gchwier** [comment]
It fixes also problems with tests from zephyr/tests/boot/with_mcumgr for nRF5340

**Review by Thalley — DISMISSED** [review]

**Comment by Thalley** [comment]
@ithinuel if this parses CI, we can consider marking it as a hotfix, as it's blocking a lot of things right now :D

**Review by sjanc — DISMISSED** [review]
bttester seems to work OK! thanks!

**Comment by nordic-piks** [comment]
For me tests are also working OK with this PR.

File: arch/arm/core/cortex_m/cpu_idle.c [hunk 1]
```diff
@@ -118,11 +118,21 @@ void arch_cpu_atomic_idle(unsigned int key)
...
+#endif
+
 	SLEEP_IF_ALLOWED(__WFE);
 
-	arch_irq_unlock(key);
+#if defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
+	__set_BASEPRI(key);
+	__ISB();
+#endif
+	__enable_irq();
```
Comment (anangl) [inline arch/arm/core/cortex_m/cpu_idle.c:137]: On platforms without BASEPRI, this will enable interrupts regardless of the `key` parameter value, and this is not what `k_cpu_atomic_idle()` is supposed to do: https://github.com/zephyrproject-rtos/zephyr/blob/6a42ede43b53ceffddeaa814b4bd99284c25240d/include/zephyr/kernel.h#L5863-L5864
I think you should use something like:
```suggestion
#if defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE)
	if (key != 0U) {
		return;
	}
#elif defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
	__set_BASEPRI(key);
	__ISB();
#endif
	__enable_irq();
```

**Review by anangl — CHANGES_REQUESTED** [review]

File: arch/arm/core/cortex_m/cpu_idle.c (hunk 1 above)
Comment (ithinuel) [reply arch/arm/core/cortex_m/cpu_idle.c:137]: Good point. This is ends up essentially being `arch_irq_unlock(key)` with an extra `__enable_irq();` for ARMV7_M and ARMV8_M_MAINLINE.

**Review by anangl — APPROVED** [review]

**Review by sjanc — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Comment by WilliamGFish** [comment]
Everything is working as before, there always an interesting reset issue between the 52840-REV1 and REV-2

Billy..
