### PR TITLE
Bluetooth: GATT: Unregister CCC when unregistering services

### LINKED ISSUE #26924: Bluetooth: Mesh: no space to store ccc cfg
**Describe the bug**
I will occasionally see the "no space to store ccc cfg" issue. The output to the console looks like this: 
image

When the "no space to store ccc cfg" issue does show up, the node becomes useless. It cannot open bearer anymore. Once I turn the node off then back on, however, the node acts normally again. 

**To Reproduce**
Quite difficult to reproduce but if I have 2 nodes and I play with the nrf provisioning app and unprovision and provision the nodes randomly and wait 10 minutes then repeat the process, I notice that the issue will show itself eventually.

**Expected behavior**

**Impact**
To me this is a show stopper because it results in the node becoming useless and I think it messes with the entire mesh network.

**Logs and console output**
My prj.conf file:
J-Link Log Viewer
#CONFIG_UART_CONSOLE=n
#CONFIG_HAS_SEGGER_RTT=y
#CONFIG_USE_SEGGER_RTT=y
#CONFIG_RTT_CONSOLE=y
#CONFIG_LOG_BACKEND_RTT=y
#CONFIG_LOG_STRDUP_BUF_COUNT=20
#CONFIG_LOG_STRDUP_MAX_STRING=80

#CONFIG_MAIN_STACK_SIZE=512
#CONFIG_BT_RX_STACK_SIZE=2048
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

#CONFIG_BT=y
#CONFIG_BT_OBSERVER=y
#CONFIG_BT_BROADCASTER=y
#CONFIG_BT_DEBUG_LOG=n
#CONFIG_BT_MESH_GATT_PROXY=y
#CONFIG_BT_PERIPHERAL=y
#CONFIG_BT_MESH_PB_GATT=y
#CONFIG_BT_MESH_PB_ADV=y
#CONFIG_BT_DEVICE_NAME="LIGHT"

#CONFIG_BT_MESH=y
#CONFIG_BT_MESH_APP_KEY_COUNT=1

#CONFIG_BT_SETTINGS=y
#CONFIG_FLASH=y
#CONFIG_FLASH_PAGE_LAYOUT=y
#CONFIG_FLASH_MAP=y
#CONFIG_FCB=y
#CONFIG_SETTINGS=y
#CONFIG_SETTINGS_FCB=y

#CONFIG_BT_DEBUG_LOG=y
#CONFIG_BT_MESH_DEBUG=y
#CONFIG_BT_MESH_DEBUG_ACCESS=y
#CONFIG_BT_MESH_DEBUG_MODEL=y
#CONFIG_BT_MESH_DEBUG_TRANS=y
#CONFIG_BT_MESH_DEBUG_NET=y
#CONFIG_BT_MESH_DEBUG_CRYPTO=n

PWM START
#CONFIG_PRINTK=y
CONFIG_PWM=y
#CONFIG_PWM_LOG_LEVEL_DBG=y

PWM END
#CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

#BT_CTLR=BT_CTLR_TX_PWR_PLUS_8

from prj.conf of mesh
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y

CONFIG_BT_OBSERVER=y
CONFIG_BT_CTLR_DUP_FILTER_LEN=0
CONFIG_BT_CTLR_LE_ENC=n
CONFIG_BT_DATA_LEN_UPDATE=n
CONFIG_BT_PHY_UPDATE=n
CONFIG_BT_CTLR_CHAN_SEL_2=n
CONFIG_BT_CTLR_MIN_USED_CHAN=n
CONFIG_BT_CTLR_PRIVACY=n

CONFIG_BT_PERIPHERAL=y

CONFIG_BT=y
CONFIG_BT_TINYCRYPT_ECC=y
CONFIG_BT_L2CAP_RX_MTU=69
CONFIG_BT_L2CAP_TX_MTU=69
CONFIG_BT_L2CAP_TX_BUF_COUNT=5

CONFIG_BT_MESH=y
CONFIG_BT_MESH_MODEL_EXTENSIONS=y
CONFIG_BT_MESH_RELAY=y
CONFIG_BT_MESH_FRIEND=y
CONFIG_BT_MESH_PB_GATT=y
CONFIG_BT_MESH_PB_ADV=y
CONFIG_BT_MESH_GATT_PROXY=y

#CONFIG_BT_MESH_LOW_POWER=y
#CONFIG_BT_MESH_LPN_SCAN_LATENCY=30
#CONFIG_BT_MESH_LPN_RECV_DELAY=40
#CONFIG_BT_MESH_LPN_POLL_TIMEOUT=300

CONFIG_BT_MESH_SUBNET_COUNT=2
CONFIG_BT_MESH_APP_KEY_COUNT=2
CONFIG_BT_MESH_MODEL_GROUP_COUNT=2
CONFIG_BT_MESH_LABEL_COUNT=3

CONFIG_BT_DEBUG_LOG=y

CONFIG_BT_MESH_DEBUG=y
#CONFIG_BT_MESH_DEBUG_PROV=y
CONFIG_BT_MESH_DEBUG_PROXY=y
#CONFIG_BT_MESH_DEBUG_BEACON=y
#CONFIG_BT_MESH_DEBUG_NET=y
#CONFIG_BT_MESH_DEBUG_TRANS=y
#CONFIG_BT_MESH_DEBUG_SETTINGS=y
#CONFIG_BT_MESH_DEBUG_LOW_POWER=y
#CONFIG_BT_MESH_DEBUG_FRIEND=y
#CONFIG_BT_MESH_DEBUG_MODEL=y
#CONFIG_BT_MESH_DEBUG_ACCESS=y
#CONFIG_BT_MESH_DEBUG_CRYPTO=y
#CONFIG_BT_MESH_DEBUG_ADV=y

UART STUFF FOR SENSOR
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_LOG_BACKEND_SWO=n
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_RING_BUFFER=y

#CONFIG_BT_MAX_PAIRED=1

**Environment (please complete the following information):**
MacOS

**Additional context**
Some stuff I've noticed includes:
 I reset node 1 and try to provision the sensor node and it gets stuck at trying to get composition data and my logs for node 2 tells me no space to store  ccc cfg. And literally node 2 is broken now so I need to turn off and back on and now I can get composition data. And now I can’t reset node 2 with my app. But if I reset the node 1 first then try to reset the node 2, I am able to reset.

### PR DESCRIPTION
**Pull request by joerchan**
Fix issue with bt_gatt_service_unregister not clearing CCC information.

If the service is unregistered while an unbonded peer is connected and
subscribed then this CCC would be restored again when registering the
service even if the peer is now disconnected.

If the service is unregistered with bonded peers CCCs stored in settings
then this value would never be cleared. If the service is registered
again then the peer would receive a service changed for this service,
but it's CCC value would still be enabled.

Fixes: #26924

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1114,6 +1114,56 @@ static void db_changed(void)
...
+
+		if (bt_addr_le_cmp(&cfg->peer, BT_ADDR_LE_ANY)) {
+			struct bt_conn *conn;
+			bool store = true;
+
+			conn = bt_conn_lookup_addr_le(cfg->id, &cfg->peer);
+			if (conn) {
+				if (conn->state == BT_CONN_CONNECTED) {
+#if defined(CONFIG_BT_SETTINGS_CCC_STORE_ON_WRITE)
+					gatt_ccc_conn_enqueue(conn);
```
Comment (Vudentz) [inline subsys/bluetooth/host/gatt.c:1132]: Do we really want to delay writing here? Imo since the CCC is no longer present on the database we should actually remove it immediately.

Note: We only use a delayed work because otherwise settings_save_one would be called from RX thread on bt_gatt_attr_write_ccc which should not be the case of bt_gatt_service_unregister.

Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:1132]: I thought it best since there might be other CCC write operations pending, or arriving afterwards, and this would avoid bt_gatt_settings_unregister from possibly being preempted by the k_delayed_work.

Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c:1132]: Operation arriving afterward would be discarded as the attribute no longer exists, for the existing/pending operations Id guess we should actually cancel them and not reschedule since we know at this point the CCC is gone nothing else should be able to access it.

Comment (joerchan) [reply subsys/bluetooth/host/gatt.c:1132]: I meant CCC operations on other characteristics, since multiple CCC operations might be bunched up into on e write operation. The characteristic is not in the list anymore, so it won't be accessible anynore

**Comment by xiongyihui** [comment]
This introduced a bug for bluetooth keyboards.
When a keyboard is reconnected to a host after disconnecting, CCC will not be set, so the keyboard will not response.
