### PR TITLE
drivers: can: common: Fix uninitializes sjw (CID 216784)

### LINKED ISSUE #31642: [Coverity CID :216784] Uninitialized scalar variable in drivers/can/can_common.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/f91e9fba51e5da46ee5c6822f8656713d74a6ecf/drivers/can/can_common.c#L219

Category: Uninitialized variables
Function: `can_calc_timing_int`
Component: Drivers
CID: [216784](https://scan9.coverity.com/reports.htm#v29726/p12996/mergedDefectId=216784)

Details:

```
213                 /* No prop_seg, seg1, seg2 combination possible */
214                 continue;
215             }
216    
217             if (sp_err < sp_err_min) {
218                 sp_err_min = sp_err;
>>>     CID 216784:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized value "tmp_res". Field "tmp_res.sjw" is uninitialized.
219                 *res = tmp_res;
220                 res->prescaler = (uint16_t)prescaler;
221                 if (sp_err == 0) {
222                     /* No better result than a perfect match*/
223                     break;
224                 }
```

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by alexanderwachter**
Fix Coverity CID 216784.
SJW was not initialized in the tmp_res, but got copied
to the result pointer, which overwrites the value.

Fixes #31642

### CODE REVIEW

**Comment by alexanderwachter** [comment]
Fix for #31642

File: drivers/can/can_common.c [hunk 1]
```diff
@@ -192,6 +192,8 @@ static int can_calc_timing_int(uint32_t core_clock, struct can_timing *res,
 	int sp_err;
 	struct can_timing tmp_res;
 
+	tmp_res.sjw = res->sjw;
```
Comment (pabigot) [inline drivers/can/can_common.c:195]: OK, I understand this a bit better now.  Why isn't the right fix:

    tmp_res = *res;

 so that the entire timing configuration that's updated in the loop has a defined state?

Comment (alexanderwachter) [reply drivers/can/can_common.c:195]: Because the rest is written in the update function. No need for initializing. The SJW is not updated because it is not an outcome of the algorithm. SJW gets written in the drivers afterward. However, not changing the SJW makes sense in case someone sets it before the algorithm is called.

Comment (alexanderwachter) [reply drivers/can/can_common.c:195]: Line 174-176

Comment (pabigot) [reply drivers/can/can_common.c:195]: Sure, I see that some fields are assigned in that, but without looking at the structure definition it's not clear that all of them are.  By assigning the entire structure you would reassure the reviewer/maintainer that *all* of it is at least as valid as the input, and that some future added field isn't going to get left uninitialized and also propagate to the caller.

Unless there's a clear motivation for not initializing the whole structure I'd really prefer this change.

**Review by pabigot — CHANGES_REQUESTED** [review]

File: drivers/can/can_common.c (hunk 1 above)
Comment (henrikbrixandersen) [reply drivers/can/can_common.c:195]: I tend to agree with @pabigot here. It will save us from encountering similar issues in the future if more fields are added to the struct.

**Comment by alexanderwachter** [comment]
Initialize the tmp_struct with a result is missleading. The passed *res is unitialized usually.
Only initializing sjw and copy the whole struct would be more efficient, I thought.
Only copying the relevant parts of the result now.

**Review by pabigot — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
