### PR TITLE
Fix DHCPv4 message interval

### LINKED ISSUE #29183: DHCPv4 retransmission interval gets too large
**Describe the bug**
The DHCP client does not limit the message retransmission interval. It increases to very high values (several years) and it would eventually be set to 0.

**To Reproduce**
1. Set `CONFIG_NET_LOG=y` and `CONFIG_NET_DHCPV4_LOG_LEVEL_DBG=y` in `samples/net/dhcpv4_client`
1. Compile and flash `samples/net/dhcpv4_client`
1. Connect the Ethernet cable (so that link is up) to a network without a DHCP server
1. Check the timeout values in the log messages

**Expected behavior**
The interval should never exceed 64 seconds as specified in [RFC 2131](https://tools.ietf.org/html/rfc2131) chapter 4.1.

**Impact**
In such situation the user must either unplug and replug the Ethernet cable or reboot to get an IP address.

**Logs and console output**
```
[00:00:23.337,000] <dbg> net_dhcpv4.net_dhcpv4_start: (0x2021d170): iface 0x20216078 state=init
[00:00:23.337,000] <dbg> net_dhcpv4.net_dhcpv4_start: (0x2021d170): wait timeout=3s
[00:00:26.338,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=init
[00:00:26.338,000] <dbg> net_dhcpv4.dhcpv4_enter_selecting: (0x2021db68): enter state=selecting
[00:00:26.338,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437ef timeout=4s
[00:00:26.338,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 4s
[00:00:30.338,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:00:30.338,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f0 timeout=8s
[00:00:30.338,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 8s
[00:00:38.338,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:00:38.338,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f1 timeout=16s
[00:00:38.338,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 16s
[00:00:54.338,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:00:54.338,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f2 timeout=32s
[00:00:54.339,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 32s
[00:01:26.339,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:01:26.339,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f3 timeout=64s
[00:01:26.339,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 64s
[00:02:30.339,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:02:30.339,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f4 timeout=128s
[00:02:30.339,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 128s
[00:04:38.339,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:04:38.339,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f5 timeout=256s
[00:04:38.339,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 256s
[00:08:54.340,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:08:54.340,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f6 timeout=512s
[00:08:54.340,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 512s
[00:17:26.340,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:17:26.340,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f7 timeout=1024s
[00:17:26.340,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 1024s
[00:34:30.340,000] <dbg> net_dhcpv4.dhcph4_manage_timers: (0x2021db68): iface 0x20216078 state=selecting
[00:34:30.340,000] <dbg> net_dhcpv4.dhcpv4_send_discover: (0x2021db68): send discover xid=0x1d9437f8 timeout=2048s
[00:34:30.340,000] <dbg> net_dhcpv4.dhcpv4_timeout: (0x2021db68): Waiting for 2048s
```

**Environment (please complete the following information):**
 - OS: Kubuntu 20.04
 - Toolchain SDK 0.11.4
 - v2.4.0

### PR DESCRIPTION
**Pull request by armandciejak**
Fixes #29183.

Also adds delay randomization as per [RFC 2131](https://tools.ietf.org/html/rfc2131) chapter 4.1.

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]

File: subsys/net/ip/dhcpv4.c [hunk 1]
```diff
@@ -287,6 +287,9 @@ static uint32_t dhcpv4_update_message_timeout(struct net_if_dhcpv4 *dhcpv4)
 		timeout = 64;
```
Comment (jukkar) [inline subsys/net/ip/dhcpv4.c:287]: In commit "net: ip: dhcpv4: Add randomization to message interval", could you add information about the RFC to the commit body, it would useful information here. So something like this
```
net: ip: dhcpv4: Add randomization to message interval

Add +1/-1 second randomization to the timeout as per RFC 2131 chapter 4.1.
```

Comment (armandciejak) [reply subsys/net/ip/dhcpv4.c:287]: I updated the commit message.

**Review by jukkar — APPROVED** [review]
