### PR TITLE
drivers: i2c: stm32 driver V2 new timing calculation

### LINKED ISSUE #55535: ST kit b_u585i_iot02a I2C clock frequency error
**Describe the bug**
I added HTS221 register reading to blinky. Measured clock speed was 110 KHz and this is a little bit too much. I checked clocking and PLL is used (msi-pll-mode). I also checked dividers and everything seemed OK to my eyes.

Is there a bug at clock configuration or maybe a clock calibration missing ?

**To Reproduce**
1. west build -p auto -b b_u585i_iot02a_ns samples\basic\blinky
2. west flash
3. boot and measure STMod+pin 7, I2C2_SCL
4. note that HTS221 is OK

**Expected behavior**
Freq should be max 100 KHz

**Impact**
Freq over I2C specification

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain (e.g Zephyr SDK, ...)
 - latest codes from github
[blink.zip](https://github.com/zephyrproject-rtos/zephyr/files/10909330/blink.zip)

### PR DESCRIPTION
**Pull request by FRASTM**
This PR is implementing a new formula to calculate the I2C timing value from the I2C clock source and the bit rate.
Algorithm coming from https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_STM/i2c_api.c

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/55535

Signed-off-by: Francois Ramu <francois.ramu@st.com>

### CODE REVIEW

**Comment by FRASTM** [comment]
stm32 I2C V2 FAST bitrate 
stm32 I2C V2 fast

stm32 I2C V2 STANDARD bitrate
stm32 I2C V2 standard

**Comment by FRASTM** [comment]
Fixing compilation errors

**Comment by FRASTM** [comment]
a second commit, to fix the compliance check warning and retrieve the original (correct) function

**Review by erwango — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by FRASTM** [comment]
Rebase, fix macro to get the same timing value
STANDARD : 0xb0c03e40
FAST : 0xc041090f

**Review by erwango — CHANGES_REQUESTED** [review]
Please cleanup second commit message.
Otherwsie LGTM

**Comment by FRASTM** [comment]
> Please cleanup second commit message. Otherwsie LGTM

done

**Review by gautierg-st — CHANGES_REQUESTED** [review]

**Review by erwango — CHANGES_REQUESTED** [review]
Before going further on this point.
Can we clarify why use of [`timings`](https://github.com/zephyrproject-rtos/zephyr/blame/8951bab7e741f3750532d4af68497b9af06a453c/dts/bindings/i2c/st%2Cstm32-i2c-v2.yaml#L23) property didn't help to solve #55535 ?
I'd like first to confirm using this property is not sufficient

**Review by erwango — CHANGES_REQUESTED** [review]
Since it consumes too much resources, timing computation algo cannot be included in "production" version of the driver.
See https://github.com/zephyrproject-rtos/zephyr/issues/55535#issuecomment-1733180182 for alternatives

**Comment by FRASTM** [comment]
Add a sample to calculate the I2C V2 timing value and then report to the I2C node in the Device Tree

The i2C V2 driver do not embed the timing calculation code. 
Only when the CONFIG_I2C_STM32_V2_TIMING=y is set by the samples/boards/stm32/i2c_V2_timing/  is the timing value output on the console.

Rebase on 68365d5b67057c8e960a5168c2cf99f4b8c457c1

File: drivers/i2c/i2c_ll_stm32.c [hunk 1]
```diff
@@ -43,26 +43,60 @@ LOG_MODULE_REGISTER(i2c_ll_stm32);
 #else
 #define STM32_I2C_DOMAIN_CLOCK_SUPPORT 0
 #endif
+int i2c_stm32_get_config(const struct device *dev, uint32_t *config)
+{
+	const struct i2c_stm32_config *cfg = dev->config;
+	struct i2c_stm32_data *data = dev->data;
+	struct i2c_config_timing *cfg_timings = (void *)config;
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32.c:50]: I don't think you're supposed to return an other structure than `i2c_stm32_config`.
See i2c.h:
```
 * @param dev_config Pointer to return bit-packed 32-bit value of
 * the I2C controller configuration.
```
It would be logical that the structure to return is the same than the one provided in `i2c_configure`.
Aim is to allow application to compare current and expected configuration:
```
 * i2c_get_config can return cached config or probe hardware, but it has to be
 * up to date with current configuration.
```
This is not a big issue as timing will also be part of this structure

File: drivers/i2c/i2c_ll_stm32.c [hunk 2]
```diff
@@ -43,26 +43,60 @@ LOG_MODULE_REGISTER(i2c_ll_stm32);
...
+			return -EIO;
+		}
+	} else {
+		if (clock_control_get_rate(DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE),
+					   (clock_control_subsys_t) &cfg->pclken[0],
+					   &i2c_clock) < 0) {
+			LOG_ERR("Failed call clock_control_get_rate(pclken[0])");
+			return -EIO;
+		}
+	}
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32.c:68]: Isn't i2c_clock already available in dev->config ?
If not , can it be ?

File: drivers/i2c/i2c_ll_stm32.h [hunk 3]
```diff
@@ -97,4 +98,11 @@ int i2c_stm32_target_register(const struct device *dev, struct i2c_target_config
 int i2c_stm32_target_unregister(const struct device *dev, struct i2c_target_config *config);
 #endif
 
+/* Get the I2C timing register to be reported by the i2c_stm32_get_config */
+#ifdef CONFIG_I2C_STM32_V1
+#define LL_I2C_GET_TIMING(instance) LL_I2C_ReadReg(instance, CCR)
+#else
+#define LL_I2C_GET_TIMING(instance) LL_I2C_ReadReg(instance, TIMINGR)
+#endif
```
Comment (erwango) [inline drivers/i2c/i2c_ll_stm32.h:106]: To remain consistent with current driver implementation, it would be required to use functions

**Review by erwango — CHANGES_REQUESTED** [review]
Only reviewed the driver part for now. Some polishing required but globally looks allright

File: drivers/i2c/i2c_ll_stm32.c (hunk 2 above)
Comment (FRASTM) [reply drivers/i2c/i2c_ll_stm32.c:68]: That was the question : 
i2c_config_timing  is included in the struct i2c_stm32_config but as a constant that cannot be set during the `i2c_stm32_runtime_configure()`

File: drivers/i2c/i2c_ll_stm32.h (hunk 3 above)
Comment (FRASTM) [reply drivers/i2c/i2c_ll_stm32.h:106]: do you mean 
```
#ifdef CONFIG_I2C_STM32_V1
	cfg_timings->timing_setting = LL_I2C_ReadReg(instance, CCR)
#else
	cfg_timings->timing_setting = LL_I2C_ReadReg(instance, TIMINGR)
#endif

```

Comment (erwango) [reply drivers/i2c/i2c_ll_stm32.h:106]: I mean proposing a function `stm32_i2c_get_timing` which will be implemented in `drivers/i2c/i2c_ll_stm32_v1.c` and `drivers/i2c/i2c_ll_stm32_v2.c` files

Comment (FRASTM) [reply drivers/i2c/i2c_ll_stm32.h:110]: Version with `struct i2c_config_timing current_timing`  to  store the current timing structure set by runtime config

File: drivers/i2c/i2c_ll_stm32.c (hunk 1 above)
Comment (FRASTM) [reply drivers/i2c/i2c_ll_stm32.c:49]: When the the i2C node Device Tree has no <timings> property (i2c_stm32_get_config has noi2c_config_timing and  n_timings == 0) 
Should we return  "(I2C_MODE_CONTROLLER | speed)" but in that case there is no simple way to retrieve the I2C V2 <timing> 32bit value

File: drivers/i2c/i2c_ll_stm32.c (hunk 2 above)
Comment (erwango) [reply drivers/i2c/i2c_ll_stm32.c]: Ok, good point, I get it now. I need to think about it indeed.

File: drivers/i2c/i2c_ll_stm32.h (hunk 3 above)
Comment (FRASTM) [reply drivers/i2c/i2c_ll_stm32.h]: Get_config : refer to https://github.com/zephyrproject-rtos/zephyr/pull/64422

**Comment by FRASTM** [comment]
Includes the https://github.com/zephyrproject-rtos/zephyr/pull/64422 
Change the sample

**Comment by FRASTM** [comment]
rebase on 482416db01e5b8d3e8b91c52bb9daa6eb3d8cddd
after merge of https://github.com/zephyrproject-rtos/zephyr/pull/64422

**Comment by FRASTM** [comment]
Running the samples/boards/stm32/i2c_config/ on the b_u585i_iot02a : 

```
*** Booting Zephyr OS build zephyr-v3.5.0-785-g6d149c663d59 ***
I2C timing value, report to the DTS :
timings = <160000000 I2C_BITRATE_FAST  0xC041090F>;
I2C config: I2C_BITRATE_FAST
```

**Comment by JiiZR** [comment]
I'am curious what happened to this merge request ? This will fix error https://github.com/zephyrproject-rtos/zephyr/issues/55535.

**Comment by teburd** [comment]
@erwango should have been assinged

File: samples/boards/stm32/i2c_config/README.rst [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+Sample Output
+=============
+When setting the b_u585i_iot02a.overlay to
+
+ .. code-block:: c
+
+    / {
+        aliases {
+                    i2c-0 = &i2c2;
+	 };
```
Comment (erwango) [inline samples/boards/stm32/i2c_config/README.rst:60]: Please fix indentation.

File: samples/boards/stm32/i2c_config/README.rst [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+In case of the I2C V2, the I2C peripheral of the STM32 microcontrollers have
+a TIMING register to write in order to generate the correct I2C clock signal.
+This value depends on the peripheral clock input and the I2C speed.
+The calculation of that TIMING value can be given by the `STM32CubeMX`_ application
+**or** by the present sample.
+
+Because the code sequence to calculate the I2C V2 TIMING value is heavy,
+the i2c_ll_stm32_v2.c driver should not embed it.
+That piece of code is activated by the CONFIG_I2C_STM32_V2_TIMING flag
+which must **not be set** except by this sample.
```
Comment (erwango) [inline samples/boards/stm32/i2c_config/README.rst:25]:
```suggestion
Because the code sequence to calculate the I2C V2 TIMING value is heavy,
it is not advised to enable it in production binary.
By enabling CONFIG_I2C_STM32_V2_TIMING flag, this sample allows to 
retrieve timing register configuration for the defined ``clock-frequency``.
User can then configure timing in his application by adapting the following dts
snippet with the output of this sample:
```

File: samples/boards/stm32/i2c_config/README.rst [hunk 6]
```diff
@@ -0,0 +1,78 @@
+.. _i2c_config:
+
+STM32 i2c_config
+################
```
Comment (erwango) [inline samples/boards/stm32/i2c_config/README.rst:4]: What about making this sample specific to timing V2 only ?
```suggestion
STM32 I2C V2 timings
####################
```

For V1, this sample doesn't add much value and this would simplify the sample configuration a bit.

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
rebase on 8100871856ff7394f9004457ade321d7fc3bf240
Renaming the samples"I2C timing"
Availability is I2C V2 only,  setting CONFIG_I2C_STM32_V2_TIMING=y in the prj.conf

File: samples/boards/stm32/i2c_config/README.rst (hunk 6 above)
Comment (FRASTM) [reply samples/boards/stm32/i2c_config/README.rst]: done

File: samples/boards/stm32/i2c_config/README.rst (hunk 5 above)
Comment (FRASTM) [reply samples/boards/stm32/i2c_config/README.rst]: done

File: samples/boards/stm32/i2c_config/README.rst (hunk 4 above)
Comment (FRASTM) [reply samples/boards/stm32/i2c_config/README.rst]: done

**Review by erwango — DISMISSED** [review]

**Comment by erwango** [comment]
@gautierg-st PTAL

**Review by gautierg-st — DISMISSED** [review]

File: samples/boards/stm32/i2c_timing/src/main.c [hunk 7]
```diff
@@ -0,0 +1,52 @@
+/*
+ * Copyright (c) 2023 STMicroelectronics
+ *
```
Comment (marwaiehm-st) [inline samples/boards/stm32/i2c_timing/src/main.c:3]: Copyright (c) 2024 STMicroelectronics

Comment (FRASTM) [reply samples/boards/stm32/i2c_timing/src/main.c:3]: this PR started last year, so 2023 was pertinent at that time,
should we really  update this comment since this is a "internal" sample

**Review by marwaiehm-st — APPROVED** [review]
LGTM

**Comment by teburd** [comment]
Needs CI fixes

**Review by erwango — DISMISSED** [review]

File: drivers/i2c/i2c_ll_stm32.c [hunk 8]
```diff
@@ -56,6 +56,23 @@ int i2c_stm32_get_config(const struct device *dev, uint32_t *config)
...
+	/* I2C BIT RATE */
+	if (data->current_timing.i2c_speed == 100000) {
+		printk(" I2C_BITRATE_STANDARD ");
+	} else if (data->current_timing.i2c_speed == 400000) {
+		printk(" I2C_BITRATE_FAST ");
+	} else if (data->current_timing.i2c_speed == 1000000) {
+		printk(" I2C_SPEED_FAST_PLUS ");
+	}
+
+	printk(" 0x%X>;\n", data->current_timing.timing_setting);
```
Comment (mathieuchopstm) [inline drivers/i2c/i2c_ll_stm32.c:73]: Maybe these `printk`s should be changed to `LOG_xxx`s instead?

**Review by ajarmouni-st — CHANGES_REQUESTED** [review]
change `printk` to `LOG_XXX` in driver code

**Comment by FRASTM** [comment]
rebase on 2efc447c1b41efd23447ea180731d673114f06d8
Version with **LOG_INF** instead of printk in the driver
 --> change the  sample.yaml
--> add the LOG_INF to the prj.conf
```
*** Booting Zephyr OS build v3.6.0-5746-ge94cfcf43a1c ***
[00:00:09.192,000] <inf> i2c_ll_stm32: I2C timing value, report to the DTS :
[00:00:09.192,000] <inf> i2c_ll_stm32: timings = <32000000 I2C_BITRATE_FAST 0xB01626>;
I2C freq. I2C_BITRATE_FAST
```

**Review by ajarmouni-st — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Review by mathieuchopstm — APPROVED** [review]

**Review by erwango — APPROVED** [review]
