### PR TITLE
arm: nxp: mpu: Consolidate k64 mpu regions

### LINKED ISSUE #7705: nxp_kinetis/k6x boot MPU regions are configured incorrectly
See arch/arm/nxp_kinetic/k6x/nxp_mpu_regions.c and also include/arch/arm/cortex_m/mpu/nxp_mpu.h

The problems are as follows:
* The REGION_* macros grant user mode access to things like I/O regions when it should not have access. By default, user mode should have read/execute access on wherever program text is stored (flash?) and *nowhere else*. Any other RAM access to user mode must be explicitly done via memory domains.
* We are wasting regions, we only have 12 with 4 used by the OS, consolidate regions that have the same underlying policy. I think we can get away with 3: a "background" map for the entire address space at lowest precedence which grants R/W access to supervisor mode only and should also be suitable for MMIO reguions, a region for flash, and a region for all of system RAM.

### PR DESCRIPTION
**Pull request by MaureenHelm**
Reduces the number of mpu regions statically reserved at boot time by
one, giving a total of five. We originally sought to reduce the total to
three: 1 background region with lowest precendence for supervisor r/w, 1
flash region, and 1 sram region. However, the nxp mpu hardware does not
give precedence to any region over another, and thus we cannot revoke
access from the background region with a higher priority region. This
means we cannot support hardware stack protection with a single
background region.

Instead, create two background regions that cover the entire address
space, except for sram.

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

Fixes #7705

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

File: arch/arm/soc/nxp_kinetis/k6x/nxp_mpu_regions.c [hunk 1]
```diff
@@ -6,46 +6,46 @@
...
-
 static struct nxp_mpu_region mpu_regions[] = {
 	/* Region 0 */
 	MPU_REGION_ENTRY("DEBUGGER_0",
 			 0,
 			 0xFFFFFFFF,
 			 REGION_DEBUG_ATTR),
+
+	/* The NXP MPU does not give precedence to memory regions like the ARM
+	 * MPU, which means that if one region grants access then another
```
Comment (ioannisg) [inline arch/arm/soc/nxp_kinetis/k6x/nxp_mpu_regions.c]: Strictly speaking, this is true for ARMv7-M MPU (not accurate for v8-M)

**Review by ioannisg — APPROVED** [review]
Looks ok; left one minor comment.
