### PR TITLE
net: mgmt: Use proper coop thread priority value

### LINKED ISSUE #32375: Networking stack crashes when run in cooperative scheduling mode only
**Describe the bug**

When networking stack is run in the cooperative scheduling mode only, enabled by setting `CONFIG_NUM_PREEMPT_PRIORITIES=0`, it crashes during the initialization.

In cooperative scheduling mode only any threads have to use priorities <= -2. Networking stack erroneously sets `CONFIG_NET_MGMT_EVENT_THREAD_PRIO` to `-1`. The change was introduced in f02fd197066f084c5b73e8cee5edd4a56670de3e.

**To Reproduce**

1. Run
```
west build -b sam_e70_xplained -- -DCONFIG_ASSERT=y -DCONFIG_NUM_PREEMPT_PRIORITIES=0 samples/net/sockets/echo
west flash
```
2. Check the terminal output, it will display
```
ASSERTION FAIL [((((prio)) == -1 && z_is_idle_thread_entry((entry))) || (((-1 - 1) >= ((-16 - 1))) && ((prio)) >= ((-16 - 1)) && ((prio)) <= (-1 - 1)))] @ WEST_TOPDIR/zephyr/kernel/thread.c:550
        invalid priority (-1); allowed range: -2 to -17
```

**Expected behavior**
The networking stack used to work when run in cooperative scheduling mode only.

**Environment**
 - Using toolchain: zephyr 0.12.2
 - Zephyr version: 2.5.0

### PR DESCRIPTION
**Pull request by jukkar**
If user sets CONFIG_NUM_PREEMPT_PRIORITIES=0, then the priority
of the net_mgmt thread will be -1 which is the same as idle thread.
This is will assert in kernel as then the minimum coop priority is -2
in this case. Remove the net_mgmt thread priority setting from
Kconfig file as it is low value and set the coop thread priority
the same way as other network threads are doing it.

Fixes #32375

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

File: subsys/net/ip/net_mgmt.c [hunk 1]
```diff
@@ -386,10 +386,17 @@ void net_mgmt_event_init(void)
...
+#define THREAD_PRIORITY K_PRIO_COOP(CONFIG_NUM_COOP_PRIORITIES - 1)
+#else
+#define THREAD_PRIORITY K_PRIO_PREEMPT(CONFIG_NUM_PREEMPT_PRIORITIES - 1)
+#endif
+
 	k_thread_create(&mgmt_thread_data, mgmt_stack,
 			K_KERNEL_STACK_SIZEOF(mgmt_stack),
 			(k_thread_entry_t)mgmt_thread, NULL, NULL, NULL,
-			CONFIG_NET_MGMT_EVENT_THREAD_PRIO, 0, K_NO_WAIT);
+			THREAD_PRIORITY, 0, K_NO_WAIT);
```
Comment (mnkp) [inline subsys/net/ip/net_mgmt.c:399]: There is a predefined `K_LOWEST_APPLICATION_THREAD_PRIO` in `include/kernel.h` which could be used here.

Comment (jukkar) [reply subsys/net/ip/net_mgmt.c:399]: I did this change same way as the other networking threads are done so not using this define. The name of the define talks about application and we have no applications here but a thread which is part of a subsystem. But it is certainly possible to use that define if needed, but I would do that change in a separate PR if we really want to do it.

Comment (mnkp) [reply subsys/net/ip/net_mgmt.c:399]: From the kernel perspective subsystem is an application. There is no thread priority range that is reserved for subsystems. So the name `K_LOWEST_APPLICATION_THREAD_PRIO` carries in fact the right meaning. Though I agree that seeing such a define in a networking stack might be confusing. From the user perspective subsystem is certainly not an application. Using the define was just a suggestion.
