### PR TITLE
Bluetooth: ATT: Queue buffers on bt_att_send

### LINKED ISSUE #16803: Deferred bt_conn_tx causes sysworkq deadlock
Mesh pb-gatt sends several GATT notifications in a row. It runs in system workqueue thread context, so that it is possible to cause deadlock after recent changes that deferred `bt_conn_tx` callback to system workqueue.

While sending several notifications in a row, `bt_att_send` takes `tx_sem`
```
int bt_att_send(struct bt_conn *conn, struct net_buf *buf, bt_conn_tx_cb_t cb,
		void *user_data)
{
...
	/* Don't use tx_sem if caller has set it own callback */
	if (!cb) {
		k_sem_take(&att->tx_sem, K_FOREVER);
		if (!att_is_connected(att)) {
			BT_WARN("Disconnected");
			k_sem_give(&att->tx_sem);
			return -ENOTCONN;
		}
	}
...
}
```
that is later given by `bt_conn_tx`.
```
static void att_pdu_sent(struct bt_conn *conn, void *user_data)
{
	struct bt_att *att = att_get(conn);

	BT_DBG("conn %p att %p", conn, att);

	k_sem_give(&att->tx_sem);
}
```
As a result running `bt_att_send` and `bt_conn_tx` from the same thread causes deadlock in ATT.

This regression was introduced with:
362497235df575586a049dd92216910c99e79094

### PR DESCRIPTION
**Pull request by Vudentz**
This prevents threads to block which may deadlock when system wq is
used.

Fixes #16803

Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>

### CODE REVIEW

File: subsys/bluetooth/host/att.c [hunk 1]
```diff
@@ -161,12 +162,50 @@ static void att_req_sent(struct bt_conn *conn, void *user_data)
...
 static void att_pdu_sent(struct bt_conn *conn, void *user_data)
 {
 	struct bt_att *att = att_get(conn);
+	struct net_buf *buf;
 
 	BT_DBG("conn %p att %p", conn, att);
 
+	/* Send more if queued */
+	while ((buf = net_buf_get(&att->tx_queue, K_NO_WAIT))) {
+		if (buf) {
```
Comment (jhedberg) [inline subsys/bluetooth/host/att.c]: This if statement looks redundant since the while-loop's condition guarantees that but will be non-NULL. The unconditional net_buf_unref at the bottom of the loop would make no sense either with this extra check.

File: subsys/bluetooth/host/att.c [hunk 2]
```diff
@@ -2071,6 +2114,8 @@ static void bt_att_connected(struct bt_l2cap_chan *chan)
 
 	BT_DBG("chan %p cid 0x%04x", ch, ch->tx.cid);
 
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/att.c]: Looks like a redundant empty line?

**Review by jhedberg — CHANGES_REQUESTED** [review]

**Review by MariuszSkamra — APPROVED** [review]
Tested against PTS, tests are passing now
1/1   MESH   MESH/NODE/MPS/BV-10-C   PASS            31.367                  
1/24   MESH   MESH/SR/PROX/BV-07-C   PASS            40.349                  
 2/24   MESH   MESH/SR/PROX/BV-03-C   PASS            61.059                  
 3/24   MESH   MESH/SR/PROX/BV-04-C   PASS            85.964                  
 4/24   MESH   MESH/SR/PROX/BV-09-C   PASS            85.413                  
 5/24   MESH   MESH/SR/PROX/BI-01-C   PASS            103.941                  
 6/24   MESH   MESH/SR/PROX/BV-05-C   PASS            76.619 
 1/10   MESH   MESH/SR/PROX/BV-01-C   PASS            49.869                  
 2/10   MESH   MESH/SR/MPXS/BV-03-C   PASS            45.046                  
 3/10   MESH   MESH/SR/MPXS/BV-08-C   PASS            56.308                  
 4/10   MESH   MESH/SR/MPXS/BV-07-C   PASS            62.019                  
 5/10   MESH   MESH/SR/MPXS/BV-09-C   PASS            56.473

**Review by jhedberg — APPROVED** [review]

**Comment by MariuszSkamra** [comment]
@Vudentz GATT Looks good. I did not tested all, because it takes some time but here's results from arbitrary chosen set 
 1/17   GATT   GATT/CL/GAC/BV-01-C   PASS            31.344                  
 2/17   GATT   GATT/CL/GAR/BI-01-C   PASS            29.933                  
 3/17   GATT   GATT/CL/GAR/BV-04-C   PASS            31.191                  
 4/17   GATT   GATT/CL/GAR/BI-16-C   PASS            30.834                  
 5/17   GATT   GATT/CL/GAR/BI-20-C   PASS            30.295                  
 6/17   GATT   GATT/CL/GAR/BV-06-C   PASS            33.962                  
 7/17   GATT   GATT/CL/GAW/BV-01-C   PASS            30.856                  
 8/17   GATT   GATT/CL/GAW/BI-02-C   PASS            30.762                  
 9/17   GATT   GATT/CL/GAW/BV-05-C   PASS            32.818                  
10/17   GATT   GATT/CL/GAW/BI-13-C   PASS            31.708                  
11/17   GATT   GATT/CL/GAN/BV-01-C   PASS            34.034                  
12/17   GATT   GATT/SR/GAD/BV-03-C   PASS            30.439                  
13/17   GATT   GATT/SR/GAR/BV-01-C   PASS            29.218                  
14/17   GATT   GATT/SR/GAR/BI-07-C   PASS            32.437                  
15/17   GATT   GATT/SR/GAW/BV-02-C   PASS            34.044                  
16/17   GATT   GATT/SR/GAW/BI-13-C   PASS            34.021                  
17/17   GATT   GATT/SR/GAW/BI-33-C   PASS            30.967

1/4   GATT   GATT/SR/GAN/BV-01-C   PASS            33.037                  
2/4   GATT   GATT/SR/GAI/BV-01-C   PASS            33.562                  
3/4   GATT   GATT/CL/GAI/BV-01-C   PASS            36.873 
4/4   GATT   GATT/CL/GAN/BV-01-C   PASS            35.942

**Comment by Vudentz** [comment]
@joerchan Looks like we need one more reviewer, can you do it?

**Comment by Vudentz** [comment]
@joerchan nevermind it was the checks that was still pending for some reason.

@jhedberg I guess we can merge this one.

**Comment by tedd-an** [comment]
> @Vudentz GATT Looks good. I did not tested all, because it takes some time but here's results from arbitrary chosen set
> 1/17 GATT GATT/CL/GAC/BV-01-C PASS 31.344
> 2/17 GATT GATT/CL/GAR/BI-01-C PASS 29.933
> 3/17 GATT GATT/CL/GAR/BV-04-C PASS 31.191
> 4/17 GATT GATT/CL/GAR/BI-16-C PASS 30.834
> 5/17 GATT GATT/CL/GAR/BI-20-C PASS 30.295
> 6/17 GATT GATT/CL/GAR/BV-06-C PASS 33.962
> 7/17 GATT GATT/CL/GAW/BV-01-C PASS 30.856
> 8/17 GATT GATT/CL/GAW/BI-02-C PASS 30.762
> 9/17 GATT GATT/CL/GAW/BV-05-C PASS 32.818
> 10/17 GATT GATT/CL/GAW/BI-13-C PASS 31.708
> 11/17 GATT GATT/CL/GAN/BV-01-C PASS 34.034
> 12/17 GATT GATT/SR/GAD/BV-03-C PASS 30.439
> 13/17 GATT GATT/SR/GAR/BV-01-C PASS 29.218
> 14/17 GATT GATT/SR/GAR/BI-07-C PASS 32.437
> 15/17 GATT GATT/SR/GAW/BV-02-C PASS 34.044
> 16/17 GATT GATT/SR/GAW/BI-13-C PASS 34.021
> 17/17 GATT GATT/SR/GAW/BI-33-C PASS 30.967
> 
> 1/4 GATT GATT/SR/GAN/BV-01-C PASS 33.037
> 2/4 GATT GATT/SR/GAI/BV-01-C PASS 33.562
> 3/4 GATT GATT/CL/GAI/BV-01-C PASS 36.873
> 4/4 GATT GATT/CL/GAN/BV-01-C PASS 35.942

@MariuszSkamra  Were you using QEMU or HW for testing?
I tried with reel_board and nrf52_pca10040 and most of GATT/GAP/MESH tests are failing.

**Comment by jhedberg** [comment]
> @MariuszSkamra Were you using QEMU or HW for testing?
> I tried with reel_board and nrf52_pca10040 and most of GATT/GAP/MESH tests are failing.

That'd indeed be important to know, since IIRC this issue was not originally observable on qemu but only on real hardware. To my understanding @MariuszSkamra is on holiday for the next two weeks, so hopefully one of his colleagues can answer. @sjanc any idea which HW @MariuszSkamra ran the tests on?

**Comment by Vudentz** [comment]
@tedd-an @MariuszSkamra if you guys happen to have any spare time Id like to run auto-pts with https://github.com/zephyrproject-rtos/zephyr/pull/16863 to check since we detect that deadlocks were still possible.
