### PR TITLE
tests/kernel/common: Fix test test_nop for ARMV7_M_ARMV8_M_MAINLINE

### LINKED ISSUE #35060: tests/kernel/common: test_nop failed on ARMV7_M_ARMV8_M_MAINLINE
**Describe the bug**
`test_nop` is reported failed on several `ARMV7_M_ARMV8_M_MAINLINE` platforms:
```
   tests/kernel/common/kernel.common, disco_l475_iot1
   tests/kernel/common/kernel.common.misra, disco_l475_iot1
   tests/kernel/common/kernel.common.nano64, disco_l475_iot1
   tests/kernel/common/kernel.common, nucleo_g474re
   tests/kernel/common/kernel.common.misra, nucleo_g474re
   tests/kernel/common/kernel.common.nano64, nucleo_g474re 
```

**To Reproduce**
`twister -T tests/kernel/common/ -p nucleo_g431rb --device-testing --device-serial /dev/ttyACM0`

**Expected behavior**
Test should be passed

**Additional context**
Cf https://github.com/zephyrproject-rtos/zephyr/pull/32728
Cf https://github.com/zephyrproject-rtos/zephyr/pull/35004

### PR DESCRIPTION
**Pull request by erwango**
Treat ARMV7_M_ARMV8_M_MAINLINE similarly to ARMV6_M_ARMV8_M_BASELINE
and add arch_nop() calls to test_nop function.
Additionally do 4 arch_nop calls in conformance to comment.

Fixes #35060

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by enjiamai — APPROVED** [review]
Thanks for fix this issue.

**Review by dcpleung — APPROVED** [review]

File: tests/kernel/common/src/irq_offload.c [hunk 1]
```diff
@@ -121,11 +121,13 @@ __no_optimization void test_nop(void)
 	/* do 2 nop instructions to cost cycles */
 	arch_nop();
 	arch_nop();
-#elif defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE)
+#elif defined(CONFIG_ARMV6_M_ARMV8_M_BASELINE) || \
+	defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
 	/* do 4 nop instructions to cost cycles */
```
Comment (galak) [inline tests/kernel/common/src/irq_offload.c:126]: Update the comment to say 5.  There's one arch_nop() before the ifdef.

Comment (erwango) [reply tests/kernel/common/src/irq_offload.c]: well.. depends on how you count :-).
Updated comments here and there to make things clear.

**Review by enjiamai — APPROVED** [review]
The change makes it looks more reasonable.

**Review by galak — APPROVED** [review]
