### PR TITLE
samples: subsys: logging: logger: Fix performance showcase

### LINKED ISSUE #21801: Logger sample's performance estimates are incorrect
**Describe the bug**

The performance_showcase() function in samples/subsys/logging/logger/src/main.c does not estimate performance correctly.

**To Reproduce**

1. build samples/subsys/logging/logger with the following additional kconfig fragment in thingy_52_immediate.overlay:

```
CONFIG_USE_SEGGER_RTT=y

# CONFIG_SHELL_BACKEND_RTT is not set

CONFIG_LOG=y
# CONFIG_LOG_BACKEND_SHOW_COLOR is not set
CONFIG_LOG_BACKEND_RTT=y

CONFIG_LOG_IMMEDIATE=y
```

e.g.

```
$ west build -b nrf52_pca20020 -- -DOVERLAY_CONFIG=thingy_52_immediate.overlay
```

2. flash board and open RTT console (e.g. using Segger Ozone to load the file onto Thingy:52 via an nRF52 DK)
3. observe the following line:

```
Estimated logging capabilities: 16384 messages/second
```
4. This is plainly incorrect, since the output appears on the screen very slowly (until https://github.com/zephyrproject-rtos/zephyr/pull/21644 is merged), and in immediate mode, that means the logging call takes a very long time to appear https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_LOG_IMMEDIATE.html#cmdoption-arg-config-log-immediate.

**Expected behavior**
Estimate should accurately reflect performance of logging subsystem in immediate mode.

**Impact**
Sample performance is not accurate.

**Environment (please complete the following information):**
 - Toolchain gnuarmemb 07/2018
 - 4e135d76a3

### PR DESCRIPTION
**Pull request by nordic-krch**
Sample tries to estimate maximum number of messages that can be
logged. It was using two system cycles and counting number of
messages logged in that window. It did not take into account the
fact that clock frequency may vary and logging speed also varies
(especially if LOG_IMMEDIATE is enabled). Presented results may
be faulty and misleading.

Fix is attempting to adjust window size to increase precision of
the measurement.

Fixes #21801 .

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

### CODE REVIEW

File: samples/subsys/logging/logger/src/main.c [hunk 1]
```diff
@@ -200,32 +207,61 @@ static void log_strdup_showcase(void)
...
+	do {
+		cnt = 0;
+		start_timestamp = timestamp_get();
 
-	while (start_timestamp == timestamp_get()) {
-#if (CONFIG_ARCH_POSIX)
-		k_busy_wait(100);
-#endif
-	}
+		while (start_timestamp == timestamp_get()) {
```
Comment (mbolivar) [inline samples/subsys/logging/logger/src/main.c]: I find the purpose of this uncommented logic hard to understand. Would you mind moving it out to a helper function with a clear name?

File: samples/subsys/logging/logger/src/main.c [hunk 2]
```diff
@@ -200,32 +207,61 @@ static void log_strdup_showcase(void)
...
-		current_timestamp = timestamp_get();
-#if (CONFIG_ARCH_POSIX)
-		k_busy_wait(100);
-#endif
-	} while (current_timestamp < (start_timestamp + window));
+		do {
+			LOG_INF("performance test - log message %d", cnt);
+			cnt++;
+			current_timestamp = timestamp_get();
+	#if (CONFIG_ARCH_POSIX)
```
Comment (mbolivar) [inline samples/subsys/logging/logger/src/main.c]: Why is POSIX getting special treatment here too? Is this a bug in the POSIX subsystem? Maybe we can just skip this part of the sample on POSIX instead of making it harder to understand for real boards.

**Comment by jhedberg** [comment]
@nordic-krch you have "Fixes #21644" in the description, but #21644 is is a PR and not an issue. Is it intentional or the reference is wrong?

**Comment by nordic-krch** [comment]
>  Is it intentional or the reference is wrong?

@jhedberg fixed.

File: samples/subsys/logging/logger/src/main.c (hunk 2 above)
Comment (nordic-krch) [reply samples/subsys/logging/logger/src/main.c]: found commit which added it: https://github.com/zephyrproject-rtos/zephyr/commit/169cab09029a12708d71e94c079cafd9d64d787c. Added commit comment as a comment there.

File: samples/subsys/logging/logger/src/main.c (hunk 1 above)
Comment (nordic-krch) [reply samples/subsys/logging/logger/src/main.c]: added helper function.

File: samples/subsys/logging/logger/src/main.c [hunk 3]
```diff
@@ -191,6 +191,32 @@ static void log_strdup_showcase(void)
...
 }
 
+static void wait_on_log_flushed(void)
+{
+	while (log_buffered_cnt()) {
+		k_sleep(K_MSEC(5));
+	}
+}
+
+/* Wait for the moment when timestmap value changes and return current time
```
Comment (mbolivar) [inline samples/subsys/logging/logger/src/main.c]:
```suggestion
/* Wait for the moment when timestamp value changes and return current time
```

File: samples/subsys/logging/logger/src/main.c [hunk 4]
```diff
@@ -191,6 +191,32 @@ static void log_strdup_showcase(void)
...
+ * stamp. In case of low frequency source we want to be at the edge.
+ */
+static u32_t timestamp_get_and_sync(void)
+{
+	u32_t start_timestamp = timestamp_get();
```
Comment (mbolivar) [inline samples/subsys/logging/logger/src/main.c]:
```suggestion
	u32_t start_timestamp = timestamp_get();
	u32_t cur_timestamp;
```

File: samples/subsys/logging/logger/src/main.c [hunk 5]
```diff
@@ -191,6 +191,32 @@ static void log_strdup_showcase(void)
...
+
+	while (start_timestamp == timestamp_get()) {
```
Comment (mbolivar) [inline samples/subsys/logging/logger/src/main.c]:
```suggestion
	while (start_timestamp == (cur_timestamp = timestamp_get())) {
```

File: samples/subsys/logging/logger/src/main.c [hunk 6]
```diff
@@ -191,6 +191,32 @@ static void log_strdup_showcase(void)
...
+#if (CONFIG_ARCH_POSIX)
+		/* In the POSIX arch, time does not pass inside infinite loops.
+		 * Add a small delay in each iteration of those loops
+		 */
+		k_busy_wait(100);
+#endif
+	}
+
+	return timestamp_get();
```
Comment (mbolivar) [inline samples/subsys/logging/logger/src/main.c]:
```suggestion
	return cur_timestamp;
```

The purpose of the proposed changes to these functions is to avoid another change in the timestamp on this line.

**Review by mbolivar — APPROVED** [review]
LGTM, just ignore me if the suggestions are no good.

File: samples/subsys/logging/logger/src/main.c (hunk 6 above)
Comment (nordic-krch) [reply samples/subsys/logging/logger/src/main.c]: thanks for suggestion, applied.

**Comment by nordic-krch** [comment]
@jakub-uC @nashif  any chance to take a look at that?

**Review by mbolivar-nordic — APPROVED** [review]
Adding a +1 again since the old one is from my personal account

File: samples/subsys/logging/logger/src/main.c [hunk 7]
```diff
@@ -200,32 +207,61 @@ static void log_strdup_showcase(void)
...
+		 * If less than half of limit is reached then it means that
+		 * window can be increased to improve precision.
+		 */
+		if (cnt >= limit) {
+			if (window >= 2) {
+				window /= 2;
+			} else {
+				break;
+			}
+		} else if (cnt < limit/2) {
```
Comment (sjg20) [inline samples/subsys/logging/logger/src/main.c:259]: space around /

**Review by sjg20 — APPROVED** [review]
