### PR TITLE
tests: Fix coherence of timeout spin lock

### LINKED ISSUE #51469: Intel CAVS: Failed in tests/kernel/spinlock
**Describe the bug**
On intel_adsp_cavs15/18/25 platform, tests/kernel/spinlock failed, because hang booting.
Bisect result: 6277386591415a5f4aaca448c921d3ff95d90394

**To Reproduce**
1. west build -p always -b intel_adsp_cavs15 tests/kernel/spinlock
2. west flash --remote-host=(ip address to DUT) --config-dir=/home/ztest/cavs/config/ --pty
3. see error

**Logs and console output**
```
Prefixing /home/ztest/zephyrproject/zephyr/build/zephyr/zephyr.ri with manifest /home/ztest/zephyrproject/zephyr/build/zephyr/zephyr.ri.xman
INFO:cavs-client:REMOTE HOST: 192.165.1.76 PORT: 10000
INFO:cavs-client:Uploading process
INFO:cavs-client:Sent:     download
INFO:cavs-client:Receive: download
INFO:cavs-client:filename:zephyr.ri.9b94539dd382233bc95a4efefb118d6a, size:90128, md5:af15c6449720225d87afc6d3ecb5c456
INFO:cavs-client:header size: 78
INFO:cavs-client:Sending...
INFO:cavs-client:Done Sending (90206).
INFO:cavs-client:RCK (success).
INFO:cavs-client:REMOTE HOST: 192.165.1.76 PORT: 9999
INFO:cavs-client:Monitor process
INFO:cavs-client:Sent:     start_log
INFO:cavs-client:Receive: start_log
INFO:cavs-client:Start to monitor log output...
--
*** Booting Zephyr OS build zephyr-v3.2.0-707-g9f652ea04a6d  ***

```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain - SDK 15.0
 - Commit SHA: 6277386591415a5f4aaca448c921d3ff95d90394

### PR DESCRIPTION
**Pull request by teburd**
Spin locks must be in coherent memory for cavs. Initially this variable was at the compilation unit scope but warnings about it being unused from a twister run lead me to move it to be in the ifdef scope in the function.

Move it back into the compilation units scope and wrap it in an ifdef to ensure its not labeled as unused.

Fixes #51469 

Signed-off-by: Tom Burdick <thomas.burdick@intel.com>

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

File: tests/kernel/spinlock/src/spinlock_error_case.c [hunk 1]
```diff
@@ -14,6 +14,11 @@ static struct k_spinlock lock;
 static struct k_spinlock mylock;
 static k_spinlock_key_t key;
 
+#ifdef CONFIG_SPIN_LOCK_TIME_LIMIT
+	static struct k_spinlock timeout_lock;
```
Comment (galak) [inline tests/kernel/spinlock/src/spinlock_error_case.c:18]: We should add a comment about this is global.

**Review by galak — CHANGES_REQUESTED** [review]
Add comment about this needs to be global

**Review by laurenmurphyx64 — DISMISSED** [review]

**Review by dcpleung — DISMISSED** [review]

**Comment by smrtos** [comment]
The `struct k_spinlock timeout_lock;` was placed on stack, it should be the mistake @andyross mentioned [here](https://github.com/zephyrproject-rtos/zephyr/issues/47300#issuecomment-1232318276).

**Comment by shuai1x** [comment]
I have tested it on CAVS. And it can fix the issue #https://github.com/zephyrproject-rtos/zephyr/issues/51469.

File: tests/kernel/spinlock/src/spinlock_error_case.c [hunk 2]
```diff
@@ -14,6 +14,12 @@ static struct k_spinlock lock;
 static struct k_spinlock mylock;
 static k_spinlock_key_t key;
 
+/* Needs to be allocated here for coherence */
```
Comment (galak) [inline tests/kernel/spinlock/src/spinlock_error_case.c:17]: This isn't sufficient.  The coherence issue is specific/unique to some systems and we need to state that.  For example, I'm guessing this works perfectly fine as is on a cortex-m0/m3/m4 system.

Comment (teburd) [reply tests/kernel/spinlock/src/spinlock_error_case.c:17]: I'm not sure I understand the issue here exactly. The comment should be added to all spin locks that they need to be global because KERNEL_COHERENCE dictates that and spin locks assert on it? Just this one particular spin lock because I made a mistake and CI doesn't run on our hardware? What are you looking for here, please be specific because to me the comment is sort of meaningless. It's a known, and assert on, attribute of this platform.

Comment (galak) [reply tests/kernel/spinlock/src/spinlock_error_case.c:17]: I'm looking for a comment that states something probably about xtensa memory regions and which ones are coherent.  On some ARM64 system that is fully coherent the old code would work.  So I'm saying the comment should explain why this needs can't just be a local variable.

Comment (teburd) [reply tests/kernel/spinlock/src/spinlock_error_case.c]: Done

**Review by laurenmurphyx64 — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Comment by laurenmurphyx64** [comment]
@andyross Really sorry, I'm new as a release manager so didn't realize we needed assignee approval to merge :grimacing: Please take a look and let me know if you have issues with this PR and we can make changes / I can find a way to revert
