### PR TITLE
x86: mmu: add ability for SoC to add MMU regions

### LINKED ISSUE #25319: MMU and USERSPACE not working on upsquared
**Describe the bug**
Enabling MMU and userspace on up_squared fails, nothing comes back on the console

**To Reproduce**

Enable MMU on up_squared...

**Expected behavior**
Userspace and mmu testcases should pass

### PR DESCRIPTION
**Pull request by dcpleung**
The SoCs usually have devices that are accessed through MMIO. This requires the corresponding regions to be marked readable and writable in the MMU or else accesses will result in page faults.

The UP Squared board is being used to make sure this works.

Fixes #25319

### CODE REVIEW

File: boards/x86/up_squared/Kconfig.defconfig [hunk 1]
```diff
@@ -11,4 +11,7 @@ config BUILD_OUTPUT_STRIPPED
 config APIC_TIMER
 	default y if !HPET_TIMER
 
+config X86_MMU_PAGE_POOL_PAGES
+	default 3072 if X86_MMU
```
Comment (jhedberg) [inline boards/x86/up_squared/Kconfig.defconfig:15]: When I boot my Up Squared I get: `Optimal CONFIG_X86_MMU_PAGE_POOL_PAGES 1033`

Comment (jhedberg) [reply boards/x86/up_squared/Kconfig.defconfig:15]: With this PR, that is

**Comment by jhedberg** [comment]
I can confirm that this PR seems to work fine with the MMU support enabled, at least with all apps I tried so far. I can also confirm that user space works (tried with `samples/userspace/prod_consumer`).

**Comment by jhedberg** [comment]
`samples/userspace/shared_mem` works as well

**Comment by nashif** [comment]
> `samples/userspace/shared_mem` works as well

need to run the whole suite I guess

File: boards/x86/up_squared/Kconfig.defconfig (hunk 1 above)
Comment (nashif) [reply boards/x86/up_squared/Kconfig.defconfig:15]: How much memory does you board have? I think this depends on the configuration, 2GB vs 4GB

Comment (dcpleung) [reply boards/x86/up_squared/Kconfig.defconfig:15]: This number depends on how much memory is marked by the MMU code, which is dependent on the app size. A large number should be enough to cover most apps.

File: arch/x86/core/x86_mmu.c [hunk 2]
```diff
@@ -817,6 +817,27 @@ static void add_mmu_region(struct x86_page_tables *ptables,
...
+void z_x86_add_mmu_region(uintptr_t addr, size_t size, u64_t flags,
+			  bool user_table)
+{
+	struct mmu_region rgn = {
+		.address = addr,
+		.size = size,
+		.flags = flags,
+	};
+
+	if (!user_table) {
```
Comment (andrewboie) [inline arch/x86/core/x86_mmu.c:830]: are you sure this is right?
the code in `z_x86_paging_init()` calls add_mmu_region() on z_x86_user_ptables unconditionally for all MMU_BOOT_REGIONS


```
	Z_STRUCT_SECTION_FOREACH(mmu_region, rgn) {
		add_mmu_region(&z_x86_kernel_ptables, rgn, false);			add_mmu_region(&z_x86_kernel_ptables, rgn, false);
#ifdef CONFIG_X86_KPTI	#ifdef CONFIG_X86_KPTI
		add_mmu_region(&z_x86_user_ptables, rgn, true);			add_mmu_region(&z_x86_user_ptables, rgn, true);
#endif	#endif
	}		}
```

Comment (dcpleung) [reply arch/x86/core/x86_mmu.c]: Fixed this one.

File: drivers/serial/uart_ns16550_port_x.h [hunk 3]
```diff
@@ -13,7 +13,11 @@
 static void irq_config_func_@NUM@(struct device *port);
 #endif
 
-static const struct uart_ns16550_device_config uart_ns16550_dev_cfg_@NUM@ = {
+static
+#ifndef UART_NS16550_PCIE_ENABLED
+const
+#endif
+struct uart_ns16550_device_config uart_ns16550_dev_cfg_@NUM@ = {
```
[the remark this answers is not in the document]
Comment (dcpleung) [reply drivers/serial/uart_ns16550_port_x.h:20]: This is what I am planning to do, but it requires some thinking first. Hence the "workaround".

[the remark this answers is not in the document]
Comment (dcpleung) [reply drivers/serial/uart_ns16550_port_x.h]: Fixed.

File: boards/x86/up_squared/Kconfig.board [hunk 4]
```diff
@@ -2,5 +2,10 @@
 # SPDX-License-Identifier: Apache-2.0
 
 config BOARD_UP_SQUARED
-	bool "UP Squared"
+	bool "UP Squared (x86)"
 	depends on SOC_APOLLO_LAKE
+
+config BOARD_UP_SQUARED_64
```
Comment (nashif) [inline boards/x86/up_squared/Kconfig.board:8]: I would make this board 64bit only, I do not think we should support 32bit by default.

Comment (andrewboie) [reply boards/x86/up_squared/Kconfig.board:8]: I think it would be good to eventually have two build targets, one 64bit and one for 32-bit HW testing since we have these on hand

Comment (andyross) [reply boards/x86/up_squared/Kconfig.board:8]: Split the difference and make the default "up_squared" board a 64 bit platform and have an "up_squared_32" for oddball uses?  I mostly agree with Anas that real applications on 64 bit CPUs are very rarely going to actually want to build a 32 bit target.

**Review by andyross — APPROVED** [review]
This all looks good to me.  Long term the policy of disallowing all MMIO memory by default is going to bite people doing board bringup again and again.  Maybe we need a layer like Linux has where drivers must all explicitly tell the kernel about their MMIO regions.  Then we could leave the page tables permissive (or leave paging disabled) during driver initialization and then abort (when CONFIG_ASSERT) when the final page tables don't match the registered regions.  The registration would then be a noop in production code.

File: boards/x86/up_squared/Kconfig.board (hunk 4 above)
Comment (jhedberg) [reply boards/x86/up_squared/Kconfig.board:8]: I was about to suggest the same (i.e. up_squared_32)

Comment (andrewboie) [reply boards/x86/up_squared/Kconfig.board:8]: this sounds good to me

**Comment by andrewboie** [comment]
>  Maybe we need a layer like Linux has where drivers must all explicitly tell the kernel about their MMIO regions.

Yes, agreed, for VM the drivers will additionally need to know their mappings so I'm looking at driver interfaces which could accomplish this efficiently for both MMU and MPU use-cases.

**Review by tyrantlizard77 — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

File: drivers/serial/uart_ns16550.c [hunk 5]
```diff
@@ -733,10 +821,13 @@ static void uart_ns16550_isr(void *arg)
 {
 	struct device *dev = arg;
 	struct uart_ns16550_dev_data_t * const dev_data = DEV_DATA(dev);
+	k_spinlock_key_t key = k_spin_lock(&dev_data->lock);
```
Comment (andyross) [inline drivers/serial/uart_ns16550.c:844]: Had some time to come back and look at this this morning.  Here is the deadlock: if the driver takes the lock before calling the registered handler, then the next uart action the handler does (for example: "try to read a byte") will deadlock, because the lock is already taken.

Just remove the locking from this spot, it's not needed.   Nothing is touching the hardware here, so there's nothing to protect.  Whatever the handler does already has its own locking.

**Comment by bwasim** [comment]
> Yes, agreed, for VM the drivers will additionally need to know their mappings so I'm looking at driver interfaces which could accomplish this efficiently for both MMU and MPU use-cases.

For targets that have an MMU, it should be the responsibility of the device driver to map / unmap the device memory space, something similar to `Mmap` function call in Linux (Ref: http://man7.org/linux/man-pages/man2/mmap.2.html).. 

However, the same cannot be easily done for MPU based targets as they have fixed number of regions in the hardware. For example, the Armv7-R MPU has 16 regions, and the Armv8-R has 24 regions in the hardware.

As the number of regions we want to map _may_ easily be more than regions supported in the hardware (for MPU), we'll have to support hot-swapping of the MPU regions for each implementation. Alternatively, for MPU, we can make the Mmap call a stub and make the BSP / SoC map all device memory in a single region at boot up (so no per-device mappings).. 

Though "hot swapping" of MPU regions is more flexible, it may be undesirable in some "real time" cases because the access to device that isn't mapped in the MPU will get a kernel exception and then the MPU in hardware will get re-programmed, which results in too much context switching.. For those cases, it probably makes more sense for MPU based targets to not support things like `Mmap` and just map all device memory in a single go.. This solution has its caveats also - Because all device memory is mapped by the kernel, dangling accesses to these memory won't be trapped / caught, leaving some bugs hidden.. But its simpler to implement and that's why I would prefer it..

**Comment by andrewboie** [comment]
> However, the same cannot be easily done for MPU based targets as they have fixed number of regions in the hardware. For example, the Armv7-R MPU has 16 regions, and the Armv8-R has 24 regions in the hardware.

@bwasim We don't need to map MPU regions in the MPU, supervisor mode can access them already and the caching properties should already be set (PRIVDEFENA bit on ARM, etc).

We have supported MPUs for some time and have not had to set regions for them and don't plan to.

> device memory space, something similar to Mmap function call in Linux

It would be a lot closer to `ioremap()`.

**Comment by andyross** [comment]
Am I right that the known uart failure was in tests/drivers/uart/uart_basic_api?  If so this bit fixes the problem for me when applied above this PR on up_squared (i.e. the new 64 bit MMU one, not the one in master):

```patch
diff --git a/drivers/serial/uart_ns16550.c b/drivers/serial/uart_ns16550.c
index c52643bb99..2098e7ee4b 100644
--- a/drivers/serial/uart_ns16550.c
+++ b/drivers/serial/uart_ns16550.c
@@ -841,13 +841,10 @@ static void uart_ns16550_isr(void *arg)
 {
        struct device *dev = arg;
        struct uart_ns16550_dev_data_t * const dev_data = DEV_DATA(dev);
-       k_spinlock_key_t key = k_spin_lock(&dev_data->lock);
 
        if (dev_data->cb) {
                dev_data->cb(dev_data->cb_data);
        }
-
-       k_spin_unlock(&dev_data->lock, key);
 }
 
 #endif /* CONFIG_UART_INTERRUPT_DRIVEN */
```

**Comment by nashif** [comment]
> Am I right that the known uart failure was in tests/drivers/uart/uart_basic_api? If so this bit fixes the problem for me when applied above this PR on up_squared (i.e. the new 64 bit MMU one, not the one in master):

yes, also my finding: https://github.com/zephyrproject-rtos/zephyr/pull/23693#discussion_r425886802

File: drivers/serial/uart_ns16550.c (hunk 5 above)
Comment (jenmwms) [reply drivers/serial/uart_ns16550.c:844]: > yes, also my finding: [#23693 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/23693#discussion_r425886802)

This has been removed/resolved in the latest commit to #23693. Thanks for the feedback!

File: boards/x86/up_squared/Kconfig.defconfig [hunk 6]
```diff
@@ -2,6 +2,26 @@
 
 if BOARD_UP_SQUARED
 
+config BOARD
+	default "up_squared_64"
```
Comment (nashif) [inline boards/x86/up_squared/Kconfig.defconfig:6]: this should be up_squared

File: boards/x86/up_squared/Kconfig.defconfig [hunk 7]
```diff
@@ -2,6 +2,26 @@
...
+config X86_MMU_PAGE_POOL_PAGES
+	default 3072 if X86_MMU
+
+endif # BOARD_UP_SQUARED
+
+
+if BOARD_UP_SQUARED_32
+
 config BOARD
 	default "up_squared"
```
Comment (nashif) [inline boards/x86/up_squared/Kconfig.defconfig:26]: and here it should be up_squared_32

**Review by nashif — CHANGES_REQUESTED** [review]

**Comment by jhedberg** [comment]
@dcpleung you'll need to rebase and fix the conflict since #25368 was merged

**Review by nashif — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
