### PR TITLE
drivers: espi: xec: Fix incorrect ACK to eSPI host about channel readiness

### LINKED ISSUE #27078: drivers: espi: mchp: Cannot perform multiple transactions over eSPI OOB channel
**Describe the bug**
Current eSPI sample code only perform a single Tx, Rx transaction over eSPI OOB channel
If sample code is extended to perform back-to-back transactions, only first trasnsaction succeds and timeout failure is report for rest of transactions.

**To Reproduce**
1. cd samples/drivers/espi/
2. west build -c -b mec1501modular_assy6885
3. Flash and power cycle

OOB Rx failed -60 is reported in multiple occasions,  despite some of the eSPI OOB transactions do go through in the eSPI bus.

**Expected behavior**
OOB Rx failure only when there is an actual failure.

**Impact**

### PR DESCRIPTION
**Pull request by albertofloyd**
eSPI slave driver should only indicate that a channel is ready after the eSPI master has enabled said channel.
However, this indication is incorrectly sent during eSPI reset even before channel renegotiation starts.

Perform only channel-specific interrupts enabling inside initialization functions.
Send Channel ready ack only after channel negotiation is received.
Add missing callbacks for channel events to notify client driver.

Fixes: #27078, #27079

### CODE REVIEW

File: drivers/espi/espi_mchp_xec.c [hunk 1]
```diff
@@ -861,22 +860,20 @@ static void espi_vwire_chanel_isr(struct device *dev)
...
 
 	status = ESPI_IO_VW_REGS->VW_EN_STS;
 
 	if (status & MCHP_ESPI_VW_EN_STS_RO) {
 		ESPI_IO_VW_REGS->VW_RDY = 1;
-
+		evt.evt_data = 1;
 		/* VW channel interrupt can disabled at this point */
 		MCHP_GIRQ_ENCLR(config->bus_girq_id) = MCHP_ESPI_VW_EN_GIRQ_VAL;
 		send_slave_bootdone(dev);
```
Comment (scottwcpg) [inline drivers/espi/espi_mchp_xec.c:874]: This assumes EC firmware has enabled SAF block.  Can Slave Boot Done VWires be sent upstream before the other channels are enabled by the master?

Comment (albertofloyd) [reply drivers/espi/espi_mchp_xec.c:874]: Yes, slave boot done can be send before OOB and Flash channel handshake is completed.
Regarding SAF block is enabled. Assumption is that is initialized prior to release RSM_RST, prior to eSPI reset de-asserted.

1) SAF enablement
2) RSM_RST released by eSPI slave
3) eSPI reset de-asserted by eSPI master
-- eSPI handshake takes place
4) eSPI VW channel enabled by master
5) eSPI VW channel ready indicated by slave
6) Slave boot done VW  by slave  
7) eSPI flash channel enabled by master
8) eSPI flash channel ready indicated by slave

Once that is said, to give major flexibility, I can extend the CONFIG_ESPI_AUTOMATIC_WARNING_ACKNOWLEDGE mechanism in a separate PR so app can decided if slave boot done is send by the driver in (6) or app can send it after (8).

Comment (scottwcpg) [reply drivers/espi/espi_mchp_xec.c:874]: Sounds good.

**Review by scottwcpg — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
