### PR TITLE
syscall: Fix static analysis compalins

### LINKED ISSUE #66786: [Coverity CID: 338129] Macro compares unsigned to 0 in drivers/entropy/entropy_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/entropy/entropy_handlers.c

Category: Integer handling issues
Function: `z_vrfy_entropy_get_entropy`
Component: Drivers
CID: [338129](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=338129)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/entropy/entropy_handlers.c#L15

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #66801: [Coverity CID: 338106] Macro compares unsigned to 0 in subsys/random/rand32_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/subsys/random/rand32_handlers.c

Category: Integer handling issues
Function: `z_vrfy_sys_rand_get`
Component: Other
CID: [338106](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=338106)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/random/rand32_handlers.c#L18

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #66835: [Coverity CID: 338024] Macro compares unsigned to 0 in drivers/sensor/sensor_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/sensor/sensor_handlers.c

Category: Integer handling issues
Function: `z_vrfy_sensor_channel_get`
Component: Drivers
CID: [338024](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=338024)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/sensor/sensor_handlers.c#L55

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #66837: [Coverity CID: 338020] Macro compares unsigned to 0 in drivers/can/can_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/can/can_handlers.c

Category: Integer handling issues
Function: `z_vrfy_can_get_state`
Component: Drivers
CID: [338020](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=338020)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/can/can_handlers.c#L226

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #66853: [Coverity CID: 316839] Macro compares unsigned to 0 in drivers/i2c/i2c_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/i2c/i2c_handlers.c

Category: Integer handling issues
Function: `z_vrfy_i2c_transfer`
Component: Drivers
CID: [316839](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=316839)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/i2c/i2c_handlers.c#L65

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #66854: [Coverity CID: 316835] Macro compares unsigned to 0 in drivers/fuel_gauge/fuel_gauge_syscall_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/fuel_gauge/fuel_gauge_syscall_handlers.c

Category: Integer handling issues
Function: `z_vrfy_fuel_gauge_get_buffer_prop`
Component: Drivers
CID: [316835](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=316835)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/fuel_gauge/fuel_gauge_syscall_handlers.c#L88

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #66855: [Coverity CID: 316826] Macro compares unsigned to 0 in drivers/i2c/i2c_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/i2c/i2c_handlers.c

Category: Integer handling issues
Function: `z_vrfy_i2c_get_config`
Component: Drivers
CID: [316826](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=316826)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/i2c/i2c_handlers.c#L23

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #66856: [Coverity CID: 316796] Macro compares unsigned to 0 in drivers/i2c/i2c_handlers.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/i2c/i2c_handlers.c

Category: Integer handling issues
Function: `copy_msgs_and_transfer`
Component: Drivers
CID: [316796](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=316796)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/i2c/i2c_handlers.c#L44

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NO_EFFECT). ([CWE-570](http://cwe.mitre.org/data/definitions/570.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### PR DESCRIPTION
**Pull request by ceolin**
Since K_SYSCALL_MEMORY can be called with signed/unsigned size types, if we check if size >= 0, static anlysis will complain about it when size in unsigned.

Fixes  #66856
Fixes  #66855
Fixes  #66854 
Fixes  #66853
Fixes  #66837
Fixes  #66835 
Fixes  #66801
Fixes  #66786

and many others similar issues

### CODE REVIEW

File: include/zephyr/internal/syscall_handler.h [hunk 1]
```diff
@@ -394,6 +394,20 @@ int k_usermode_string_copy(char *dst, const char *src, size_t maxlen);
  */
 #define K_SYSCALL_VERIFY(expr) K_SYSCALL_VERIFY_MSG(expr, #expr)
 
+/**
+ * @intenal @brief Macro to check if size is negative
```
Comment (nashif) [inline include/zephyr/internal/syscall_handler.h:398]: this is wrong, do not add @internal here.

Comment (ceolin) [reply include/zephyr/internal/syscall_handler.h:398]: when this should be used then ? Is there any particular case where `@internal` is valid ?

**Review by henrikbrixandersen — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]
