### PR TITLE
usb: device: class: rndis: correct packet reception

### LINKED ISSUE #54574: USB RNDIS Reception Issue(s)
**Describe the bug**

STM32H730VB with embedded USB FS PHY and enabled RNDIS is unstable and doesn't receive all incoming packets.

It feels like `static void rndis_bulk_out(uint8_t ep, enum usb_dc_ep_cb_status_code ep_status)` doesn't receive the complete packet and might corrupt it.

https://github.com/zephyrproject-rtos/zephyr/blob/802600da7b0396ee515ddf68abf69d95ba33ecf5/subsys/usb/device/class/netusb/function_rndis.c#L325-L341

It reads the number of available bytes and sets that as the expected packet length. If there are more than `CONFIG_RNDIS_BULK_EP_MPS` bytes, then we limit the length that we read to `CONFIG_RNDIS_BULK_EP_MPS`. A packet is allocated and filled with `CONFIG_RNDIS_BULK_EP_MPS` of bytes even when `usb_read` returned `len` that is more than `CONFIG_RNDIS_BULK_EP_MPS`. Therefore, when `len` is more than  `CONFIG_RNDIS_BULK_EP_MPS` we discard the data.
The next time the `rndis_bulk_out` is called again we also limit that to `CONFIG_RNDIS_BULK_EP_MPS` and add limited `len` to the packet again and subtract read bytes from the expected packet length.

I observe the following (_on the hardware I have_):

* 1st call to `rndis_bulk_out` with read `len` is 86:
   - The `len` gets limited to 64 (`CONFIG_RNDIS_BULK_EP_MPS=64`). A packet is allocated and filled with 64 bytes.
     The expected length gets set to `86 - 64 = 22`.
* 2nd call to `rndis_bulk_out` with read `len` is 86 (_1st usb_read_):
    - The `len` gets limited to 64 (`CONFIG_RNDIS_BULK_EP_MPS=64`). The packet is filled with additional 64 bytes.
      The expected length gets set to `22 - 64 = -42`.

As soon as the expected packet length is below 0 it is dropped/discarded:

https://github.com/zephyrproject-rtos/zephyr/blob/802600da7b0396ee515ddf68abf69d95ba33ecf5/subsys/usb/device/class/netusb/function_rndis.c#L425-L428

It seems that the current `rndis_bulk_out` implementation works only when received `len` from the 1st `usb_read` is below or equal to `CONFIG_RNDIS_BULK_EP_MPS`.

**Possible Fixes**
Probable fix is to allocate a packet and read the whole payload based on `DataLength` from `REMOTE_NDIS_PACKET_MSG`. Don't just chop and discard the data based on `CONFIG_RNDIS_BULK_EP_MPS`.

Things to consider:

> Each REMOTE_NDIS_PACKET_MSG message contains information about a single network data unit (_such as an Ethernet 802.3 frame_).

and 

> REMOTE_NDIS_PACKET_MSG message on the data channel might contain **multiple** packets. 

> All Windows RNDIS implementations support sending and receiving multiple
REMOTE_NDIS_PACKET_MSG messages in one bus transfer.

Considering:

https://github.com/zephyrproject-rtos/zephyr/blob/0744e42e2299015af339e1530527e5150c1c2621/subsys/usb/device/class/netusb/function_rndis.c#L502-L508

* `MaxPacketsPerTransfer` is 1 
* `MaxTransferSize` is 1558
* `PacketAlignmentFactor` is 0 (2<sup>0</sup>=1)

The `rndis_bulk_out` shall be able to receive transfer up to `1558` bytes (_inclusive_).

**To Reproduce**
1. Configure a project with networking and USB RNDIS for any STM32 USB with FS PHY that sets `CONFIG_RNDIS_BULK_EP_MPS` to `64` (_maybe the same can be observed with HS PHY with `CONFIG_RNDIS_BULK_EP_MPS <= 64`_).
2. Try to receive data on your device.
3. Observe issues when more than `CONFIG_RNDIS_BULK_EP_MPS` data is received within `rndis_bulk_out`.

**Expected behavior**
RNDIS device class shall receive complete packages.

**Impact**
Annoyance and showstopper depending on the RNDIS role and target hardware.

**Logs and console output**
It begins with:
> <wrn> usb_rndis: Limit read len 86 to MPS 64`

Eventually, other log messages might appear (_depending on the application and configured buffer sizes_):
> <err> usb_rndis: Cannot get free buffer
> <wrn> usb_rndis: Transmit response queue is not empty (repeats periodically)
> <wrn> usb_rndis: Notification is already sent

**Environment (please complete the following information):**
 - OS: Windows 10 22H2
 - Toolchain: gcc-arm-none-eabi-10.3-2021.07
 - Zephyr 3.3.0-rc2 https://github.com/zephyrproject-rtos/zephyr/commit/461a13c085de73aabdb5777247a96675472a73ad

**Additional context**
To make RNDIS work on Windows 10 the descriptors require modification so that the device is identified as "RNDIS over Ethernet" and Windows loads the correct driver, see:
* [Windows Driver Supported Classes](https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/supported-usb-classes)
* [USB-IF Defined Class Codes](https://www.usb.org/defined-class-codes)

IAD:
```
.bFunctionClass = USB_BCC_MISCELLANEOUS,
.bFunctionSubClass = 4,
.bFunctionProtocol = 1,
```
IF0:
```
.bInterfaceClass = USB_BCC_MISCELLANEOUS,
.bInterfaceSubClass = 4,
.bInterfaceProtocol = 1,
```

That is discussed in https://github.com/zephyrproject-rtos/zephyr/discussions/51765. I am not sure why https://github.com/zephyrproject-rtos/zephyr/pull/46454 was closed. Created #54611 for descriptors correction.

Furthermore, `CONFIG_USB_DEVICE_OS_DESC` and `CONFIG_USB_COMPOSITE_DEVICE` shall be enabled.

**Specification(s):**
* [RNDIS Specification](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/WinArchive/[MS-RNDIS].pdf)

### PR DESCRIPTION
**Pull request by GeorgeCGV**
Allows receive packets that are bigger than `CONFIG_RNDIS_BULK_EP_MPS`.

Considering:
* MaxPacketsPerTransfer is 1
* MaxTransferSize is 1558
* PacketAlignmentFactor is 0 (20=1)

The rndis_bulk_out shall be able to receive transfers up to 1558 bytes (inclusive).

Fixes #54574.

Tested on a custom board with STM32H730VB embedded USB FS PHY.
This PR is a crude fix and has to be tested on other targets as RNDIS somehow worked for them before.

### CODE REVIEW

**Review by tmon-nordic — DISMISSED** [review]
Tested on nRF52840 DK with:
`OVERLAY_CONFIG="overlay-netusb.conf" west build -b nrf52840dk_nrf52840 zephyr/samples/net/zperf -d build-zperf-usb -- -DCONFIG_USB_DEVICE_NETWORK_ECM=n -DCONFIG_USB_DEVICE_NETWORK_RNDIS=y`

The changes does not seem to affect it. The TCP tests work fine, however for UDP there is always 1 packet lost - but that happens both with and without this PR.

File: subsys/usb/device/class/netusb/function_rndis.c [hunk 1]
```diff
@@ -207,8 +207,13 @@ static struct __rndis {
...
 
-static uint8_t tx_buf[NET_ETH_MAX_FRAME_SIZE +
-				sizeof(struct rndis_payload_packet)];
+/**
+ * Assumes MaxPacketsPerTransfer of 1 and 802.2 (ethernet) medium.
+ */
+#define RNDIS_BUF_SIZE (NET_ETH_MAX_FRAME_SIZE + sizeof(struct rndis_payload_packet))
+
+static uint8_t tx_buf[RNDIS_BUF_SIZE];
+static uint8_t rx_buf[RNDIS_BUF_SIZE];
```
Comment (jfischer-no) [inline subsys/usb/device/class/netusb/function_rndis.c:216]: It is actually a waste of RAM. I have to think about it, it could be fixed more efficiently.

Comment (GeorgeCGV) [reply subsys/usb/device/class/netusb/function_rndis.c:216]: It is a crude fix.

If there is a better way then it might be applied to ECM as well:

https://github.com/zephyrproject-rtos/zephyr/blob/ab2b77219638c780294d6de622ae9784f7381180/subsys/usb/device/class/netusb/function_ecm.c#L31

**Comment by GeorgeCGV** [comment]
Added validation that incoming data doesn't exceed RX buffer size. Data and "in" packet are discarded in such case.

File: subsys/usb/device/class/netusb/function_rndis.c [hunk 2]
```diff
@@ -318,21 +323,20 @@ void rndis_clean(void)
...
 
 	usb_read(ep, NULL, 0, &len);
 
 	LOG_DBG("EP 0x%x status %d len %u", ep, ep_status, len);
 
-	if (len > CONFIG_RNDIS_BULK_EP_MPS) {
-		LOG_WRN("Limit read len %u to MPS %u", len,
-			CONFIG_RNDIS_BULK_EP_MPS);
-		len = CONFIG_RNDIS_BULK_EP_MPS;
+	if (len > ARRAY_SIZE(rx_buf)) {
```
Comment (jfischer-no) [inline subsys/usb/device/class/netusb/function_rndis.c:333]: Please do not use macros on simple arrays.
```c
if (len > sizeof(rx_buf)) {

```

File: subsys/usb/device/class/netusb/function_rndis.c (hunk 1 above)
Comment (jfischer-no) [reply subsys/usb/device/class/netusb/function_rndis.c:216]: ECM is different, here the code below is designed to handle it transaction by transaction, on the most platforms only the maximum of endpoint MPS will be used in rx_buf.
```c
if (net_pkt_write(rndis.in_pkt,
                  rx_buf + hdr_offset, len - hdr_offset)) {
```

Comment (jfischer-no) [reply subsys/usb/device/class/netusb/function_rndis.c:216]: Maybe add a REVISE note abor rx_buf definition that it could be optimized.

**Review by jfischer-no — APPROVED** [review]

**Review by tmon-nordic — APPROVED** [review]
