### PR TITLE
drivers: dma: stm32: add null callback checking

### LINKED ISSUE #97454: DMA: STM32: dma_stm32_configure does not check if a dma_callback is supplied
### Describe the bug

TLDR: The DMA driver for STM32 does a hard fault if the optional dma callback is not set.

[`dma_stm32_configure()`](https://github.com/zephyrproject-rtos/zephyr/blob/4b3cb736d5fb6de21b614c833a65a99700b61594/drivers/dma/dma_stm32.c#L271-L512) is basically like the following:

```c
DMA_STM32_EXPORT_API int dma_stm32_configure(const struct device *dev,
					     uint32_t id,
					     struct dma_config *config)
{
	const struct dma_stm32_config *dev_config = dev->config;
	DMA_TypeDef *dma = (DMA_TypeDef *)dev_config->base;
	LL_DMA_InitTypeDef DMA_InitStruct;
	struct dma_stm32_stream *stream;

	stream->dma_callback	= config->dma_callback;

... fill DMA_InitStruct based on config

	LL_DMA_Init(dma, dma_stm32_id_to_stream(id), &DMA_InitStruct);

	LL_DMA_EnableIT_TC(dma, dma_stm32_id_to_stream(id));

	/* Enable Half-Transfer irq if circular mode is enabled */
	if (stream->cyclic) {
		LL_DMA_EnableIT_HT(dma, dma_stm32_id_to_stream(id));
	}
...
```

The interrupt(s) for the dma channel get always activated, even if `config->dma_callback` is a `NULL`-Pointer.

The interrupt handler [`dma_stm32_irq_handler`](https://github.com/zephyrproject-rtos/zephyr/blob/4b3cb736d5fb6de21b614c833a65a99700b61594/drivers/dma/dma_stm32.c#L87C1-L144C1) always calls the dma callback function:

```c
static void dma_stm32_irq_handler(const struct device *dev, uint32_t id)
{
	const struct dma_stm32_config *config = dev->config;
	DMA_TypeDef *dma = (DMA_TypeDef *)(config->base);
	struct dma_stm32_stream *stream;
...
	if (stm32_dma_is_ht_irq_active(dma, id)) {
		stream->dma_callback(dev, stream->user_data, callback_arg, DMA_STATUS_BLOCK);

... more code and calls to stream->dma_callback() omitted
}
```

This leads to hard fault because the memory at 0x0 can not contain a valid callback function.

However, the [API doc states](https://docs.zephyrproject.org/latest/doxygen/html/structdma__config.html#a69110abc43227bd7df217c4e25bb964b) that `dma_config::dma_callback` is an "Optional callback for completion and error events". So it is valid to call `dma_stm32_configure()` without a dma callback and must not result in a hard fault or similar.

## Suggested change

Do not enable the interrupt(s) in `dma_stm32_configure()` if `config->dma_callback` is a `NULL`-Pointer.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- https://github.com/zephyrproject-rtos/zephyr/blob/4b3cb736d5fb6de21b614c833a65a99700b61594/drivers/dma/dma_stm32.c (current state of the main branch as writing this report)
- Zephyr v4.2.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ttwards**
drivers: dma: stm32: check for null dma_callback before enabling irqs

The STM32 DMA driver did not check if the optional dma_callback was set in dma_stm32_configure(). This could lead to a hard fault when an interrupt occurs and the callback is NULL, even though the API allows the callback to be omitted.

This patch modifies dma_stm32_configure() to enable transfer and half-transfer interrupts only if a valid dma_callback is supplied in config. This prevents NULL-function pointer dereference if callbacks are not used.

Fixes #97454

### CODE REVIEW

File: drivers/dma/dma_stm32.c [hunk 1]
```diff
@@ -117,7 +117,10 @@ static void dma_stm32_irq_handler(const struct device *dev, uint32_t id)
 		if (!stream->hal_override) {
 			dma_stm32_clear_ht(dma, id);
 		}
-		stream->dma_callback(dev, stream->user_data, callback_arg, DMA_STATUS_BLOCK);
+		if (stream->dma_callback) {
+			stream->dma_callback(dev, stream->user_data,
+				callback_arg, DMA_STATUS_BLOCK);
+		}
```
Comment (etienne-lms) [inline drivers/dma/dma_stm32.c]: Nitpicking on coding style here and below:
```suggestion
		if (stream->dma_callback != NULL) {
			stream->dma_callback(dev, stream->user_data,
					     callback_arg, DMA_STATUS_BLOCK);
		}

**Review by etienne-lms — COMMENTED** [review]
Nitpicking on coding guidelines, otherwise imeplementation LGTM.

Regarding the commit message, I think you should rephrase the last sentence that does not really describe the change IMHO.
My suggestion:
```patch
 drivers: dma: stm32: add null callback checking
 
-The STM32 DMA driver did not check if the optional dma_callback was set
+Fix the STM32 DMA driver did not check if the optional dma_callback was set
 in dma_stm32_configure(). This could lead to a hard fault when an
 interrupt occurs and the callback is NULL, even though the API allows
 the callback to be omitted.

-This patch modifies dma_stm32_configure() to enable transfer and
-half-transfer interrupts only if a valid dma_callback is supplied in
-config. This prevents NULL-function pointer dereference if callbacks
-are not used.
-
 Fixes: ...
 Signed-off-by: ...

**Review by AUtech-dev — COMMENTED** [review]
Thanks for the PR!
I can confirm that the current state fixes the hard fault.

However, I am a little bit concerned about the performance impact of the interrupts if the callback is not used:
The half transfer isr only clears the isr flag with `dma_stm32_clear_ht()` and does nothing more. Not requesting the interrupt at all (by not enabling it in `dma_stm32_configure`) would not change the system behavior but saves some cpu cycles - from my point of view.

In case of a cyclic dma tranfser (`stream->cyclic == true`) the transfer complete isr has the same behavior.

From my point of view this diff would improve performance:

```diff --git a/drivers/dma/dma_stm32.c b/drivers/dma/dma_stm32.c
--- a/drivers/dma/dma_stm32.c
+++ b/drivers/dma/dma_stm32.c
@@ -491,10 +501,13 @@
 	DMA_InitStruct.PeriphRequest = config->dma_slot;
 #endif
 	LL_DMA_Init(dma, dma_stm32_id_to_stream(id), &DMA_InitStruct);
 
-	LL_DMA_EnableIT_TC(dma, dma_stm32_id_to_stream(id));
+	/* Enable transfer complete isr if in non-cyclic mode or a callback is requested*/
+	if (!stream->cyclic || stream->dma_callback) {
+		LL_DMA_EnableIT_TC(dma, dma_stm32_id_to_stream(id));
+	}
 
-	/* Enable Half-Transfer irq if circular mode is enabled */
-	if (stream->cyclic) {
+	/* Enable Half-Transfer irq if circular mode is enabled and a callback is requested */
+	if (stream->cyclic && stream->dma_callback) {
 		LL_DMA_EnableIT_HT(dma, dma_stm32_id_to_stream(id));
 	}
```

Background: In my application I have a dma for RX and TX data with a quite fast timing and really need only one interrupt because both data paths are handled together.

**Review by AUtech-dev — APPROVED** [review]
Tested this on hardware (stm32u073Xc). Works fine.

File: drivers/dma/dma_stm32.c [hunk 2]
```diff
@@ -127,18 +128,25 @@ static void dma_stm32_irq_handler(const struct device *dev, uint32_t id)
...
+			stream->dma_callback(dev, stream->user_data,
+								 callback_arg, DMA_STATUS_COMPLETE);
+		}
 	} else if (stm32_dma_is_unexpected_irq_happened(dma, id)) {
 		LOG_ERR("Unexpected irq happened.");
-		stream->dma_callback(dev, stream->user_data,
-				     callback_arg, -EIO);
+		if (stream->dma_callback != NULL) {
+			stream->dma_callback(dev, stream->user_data,
+				    			 callback_arg, -EIO);
```
Comment (etienne-lms) [inline drivers/dma/dma_stm32.c]: @ttwards, note that tabulations are 8 space character wide in Zephyr.
CI compliance check also complains on mixes of tab and spaces here and there.

For info, C source files can use up to 100char/line so feel free to use this range without line escapes when applicable.

Comment (ttwards) [reply drivers/dma/dma_stm32.c]: I understand, but two callings of `stream->dma_callback` reach 100~110 chars.
Shoud I use tab only?

**Comment by erwango** [comment]
> From my point of view this diff would improve performance:

@AUtech-dev While related, this is a different topic. Please raise a dedicated PR to discuss about it.

File: drivers/dma/dma_stm32.c (hunk 2 above)
Comment (erwango) [reply drivers/dma/dma_stm32.c]: > Shoud I use tab only?

You should use tab (8-char long) as much as possible, then fine tune with spaces.

**Comment by etienne-lms** [comment]
> > From my point of view this diff would improve performance:
> 
> @AUtech-dev While related, this is a different topic. Please raise a dedicated PR to discuss about it.

@ttwards, that would mean you should revert the change proposed in https://github.com/zephyrproject-rtos/zephyr/pull/97475#pullrequestreview-3334096602 and only deal with testing callback pointers against NULL in this P-R, at least in this commit that is related to issue https://github.com/zephyrproject-rtos/zephyr/issues/97454.

If your also convinced the proposed optimization is fully valid and valuable, it would deserve a dedicated commit. Unless what, as @erwango said, let's address this optimization in a later P-R.

**Comment by AUtech-dev** [comment]
> > > From my point of view this diff would improve performance:
> >
> > @AUtech-dev While related, this is a different topic. Please raise a dedicated PR to discuss about it.
> 
> If your also convinced the proposed optimization is fully valid and valuable, it would deserve a dedicated commit. Unless what, as @erwango said, let's address this optimization in a later P-R.

I have opened https://github.com/zephyrproject-rtos/zephyr/pull/98057 for this optimization.

**Comment by erwango** [comment]
@ttwards Please rebase.

File: drivers/dma/dma_stm32.c [hunk 3]
```diff
@@ -117,7 +117,8 @@ static void dma_stm32_irq_handler(const struct device *dev, uint32_t id)
 		if (!stream->hal_override) {
 			dma_stm32_clear_ht(dma, id);
 		}
-		stream->dma_callback(dev, stream->user_data, callback_arg, DMA_STATUS_BLOCK);
+		stream->dma_callback(dev, stream->user_data,
+							 callback_arg, DMA_STATUS_BLOCK);
```
Comment (etienne-lms) [inline drivers/dma/dma_stm32.c]: Missed a change here?
```suggestion
		if (stream->dma_callback != NULL) {
			stream->dma_callback(dev, stream->user_data, callback_arg,
					     DMA_STATUS_BLOCK);
		}

File: drivers/dma/dma_stm32.c [hunk 4]
```diff
@@ -127,18 +128,25 @@ static void dma_stm32_irq_handler(const struct device *dev, uint32_t id)
 		if (!stream->hal_override) {
 			dma_stm32_clear_tc(dma, id);
 		}
-		stream->dma_callback(dev, stream->user_data, callback_arg, DMA_STATUS_COMPLETE);
+		if (stream->dma_callback != NULL) {
+			stream->dma_callback(dev, stream->user_data,
+								 callback_arg, DMA_STATUS_COMPLETE);
```
Comment (etienne-lms) [inline drivers/dma/dma_stm32.c]: Prefer standard indentation:
```suggestion
			stream->dma_callback(dev, stream->user_data, callback_arg,
					     DMA_STATUS_COMPLETE);

File: drivers/dma/dma_stm32.c (hunk 2 above)
Comment (etienne-lms) [reply drivers/dma/dma_stm32.c]: Here it fits in a single line:
```c
		if (stream->dma_callback != NULL) {
			stream->dma_callback(dev, stream->user_data, callback_arg, -EIO);
		}
```
Ditto bellow.

**Comment by ttwards** [comment]
Updated. Sorry it's a bit busy for me nowadays. Thank you a lot!!!

File: drivers/dma/dma_stm32.c [hunk 5]
```diff
@@ -127,18 +130,24 @@ static void dma_stm32_irq_handler(const struct device *dev, uint32_t id)
...
 	} else {
 		LOG_ERR("Transfer Error.");
 		stream->busy = false;
 		dma_stm32_dump_stream_irq(dev, id);
 		dma_stm32_clear_stream_irq(dev, id);
-		stream->dma_callback(dev, stream->user_data,
-				     callback_arg, -EIO);
+		if (stream->dma_callback != NULL) {
+			stream->dma_callback(dev, stream->user_data,
+				    			 callback_arg, -EIO);
```
Comment (etienne-lms) [inline drivers/dma/dma_stm32.c]: Sorry, the indentation is not very nice. Not a blocking issue but better to address IMHO:
```suggestion
			stream->dma_callback(dev, stream->user_data,
					     callback_arg, -EIO);
```
For all occurrences below, the expected indentation for 2nd line listing remaining arguments should be of 5 tabulations followed by 5 space characters.

**Review by FRASTM — DISMISSED** [review]

**Review by AUtech-dev — APPROVED** [review]

**Comment by etienne-lms** [comment]
@ttwards, you need to rebase tour patch.

**Comment by mathieuchopstm** [comment]
rebase on behalf of @ttwards + address comments by @etienne-lms

File: drivers/dma/dma_stm32.c [hunk 6]
```diff
@@ -127,26 +130,32 @@ static void dma_stm32_irq_handler(const struct device *dev, uint32_t id)
...
 		if (!stream->hal_override) {
 			LOG_ERR("Unexpected irq happened.");
 			stm32_dma_dump_stream_irq(dma, id);
 			stm32_dma_clear_stream_irq(dma, id);
+			if (stream->dma_callback != NULL) {
+				stream->dma_callback(dev, stream->user_data, callback_arg, -EIO);
+			}
 		}
-		stream->dma_callback(dev, stream->user_data,
-				     callback_arg, -EIO);
```
Comment (AUtech-dev) [inline drivers/dma/dma_stm32.c]: Why is the `stream->dma_callback()` call moved into the `if (!stream->hal_override)`? 
From my point of view this changes the behavior for the `strem->hal_override == true` path and removes all calls to the callback in this case.

Same below in the `else` branch.

Comment (mathieuchopstm) [reply drivers/dma/dma_stm32.c]: Ah, whoops, you're right. Mistake on my side when doing the rebase.

**Review by AUtech-dev — APPROVED** [review]

**Review by etienne-lms — APPROVED** [review]

**Comment by mathieuchopstm** [comment]
reassigning as @erwango is out of office and can't approve

**Review by gautierg-st — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]
