### PR TITLE
drivers: flash: Clarify parameter validation order

### LINKED ISSUE #87021: drivers: flash: flash_mcux_flexspi_nor incorrectly handles border case
**Describe the bug**

#84899 introduced input parameter checking for flash read operations.

The introduced check incorrectly handles the corner case where a read is performed of size 0 into a NULL array. The read fails with error code `-EINVAL`.

This introduces a difference between platforms when e.g. `nvs_read` is used to retrieve the size of an already stored element as reported in #86981.

**To Reproduce**

See #86981.

**Expected behavior**

No difference between platforms.

**Logs and console output**

See #86981.

**Environment (please complete the following information):**

See #86981.

### PR DESCRIPTION
**Pull request by dleach02**
Add some clarity on expected parameter validation order to have
consistency between implementations.

Update NXP flash drivers to align with parameter validation order

Fixes #87021

Signed-off-by: David Leach <david.leach@nxp.com>

### CODE REVIEW

File: drivers/flash/flash_mcux_flexspi_hyperflash.c [hunk 1]
```diff
@@ -395,6 +395,14 @@ static int flash_flexspi_hyperflash_read(const struct device *dev, off_t offset,
 {
 	struct flash_flexspi_hyperflash_data *data = dev->data;
 
+	if (len == 0) {
+		return 0;
+	}
+
+	if (!buffer) {
```
Comment (de-nordic) [inline drivers/flash/flash_mcux_flexspi_hyperflash.c:402]: Not compliant with Coding Guidelines, Zephyr rule 85 (https://gitlab.com/MISRA/MISRA-C/MISRA-C-2012/Example-Suite/-/blob/master/R_14_04.c), should be `buffer == NULL`.

Comment (de-nordic) [reply drivers/flash/flash_mcux_flexspi_hyperflash.c:402]: OK, now I see that the entire driver keeps that style, so the decision is on you.

**Review by de-nordic — APPROVED** [review]
One Coding Guidelines comment, otherwise looks OK.
Thanks for providing read callback documentation.

**Review by kartben — APPROVED** [review]

**Comment by dleach02** [comment]
To avoid losing the +1 I'm going to follow up this PR with a new one that will just align to the coding guideline @de-nordic pointed out.
