### PR TITLE
tests: arch: arm_irq_vector_table: Update to run on MXRT685

### LINKED ISSUE #35658: arch.interrupt.arm.irq_vector_table.arm_irq_vector_table: MPU FAULT Halting system for mximxrt685_evk_cm33
**Describe the bug**
irq_vector_table test hangs

**To Reproduce**
1. mkdir build; cd build
2. cmake -Dmimxrt685_evk_cm33 ..
3. make; make flash

**Expected behavior**
PASS

**Impact**
irq vector teable

**Logs and console output**

```
E: ***** MPU FAULT *****
E:   Instruction Access Violation
E: r0/a1:  0x180044b1  r1/a2:  0x00000000  r2/a3:  0x180044b1
E: r3/a4:  0x30180868 r12/ip:  0xa0000000 r14/lr:  0xfffffffd
E:  xpsr:  0x68000039
E: Faulting instruction address (r15/pc): 0xfb06fef6
E: &gt;&gt;&gt; ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
E: Fault during interrupt handling
E: Current thread: 0x30180218 (main)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v2.6.0-rc1-323-gae4fb20f6733

### PR DESCRIPTION
**Pull request by mmahadevan108**
Fixes #35658
Update the custom vector table to add the OS Event timer interrupt which is used on RT685 as the kernel system timer

### CODE REVIEW

**Review by hakehuang — APPROVED** [review]
this fixes works for me

File: tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 1]
```diff
@@ -230,6 +230,18 @@ vth __irq_vector_table _irq_vector_table[] = {
 	isr0, isr1, isr2, 0,
 	rtc_isr
 };
+#elif defined(CONFIG_SOC_SERIES_IMX_RT6XX)
+/* MXRT685 employs a OS Event timer to implement the Kernel system
+ * timer, instead of the ARM Cortex-M SysTick. Therefore, a pointer to
+ * the timer ISR needs to be added in the custom vector table to handle
+ * the timer "tick" interrupts.
+ */
+extern void mcux_lpc_ostick_isr(void);
```
Comment (bbolen) [inline tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c:239]: I'll put this out as a suggestion as others may disagree with the approach.  In mcux_os_timer.c I would leave mcux_lpc_ostick_isr alone and add
void test_mcux_lpc_ostick_isr(void)
{
    mcux_lpc_ostick_isr(NULL);
}

Then _irq_vector_table can reference test_mcux_lpc_ostick_isr().  This solves the problem where you are implicitly casting the "void *" to "void" with the extern declaration of mcux_lpc_ostick_isr here.

Comment (stephanosio) [reply tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c:239]: Unless it is absolutely necessary, we should not be adding test-related code to the driver itself; if any, `test_mcux_lpc_ostick_isr` should be implemented on the test-side (i.e. in `arm_irq_vector_table.c`).

File: tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 2]
```diff
@@ -230,6 +230,18 @@ vth __irq_vector_table _irq_vector_table[] = {
 	isr0, isr1, isr2, 0,
 	rtc_isr
 };
+#elif defined(CONFIG_SOC_SERIES_IMX_RT6XX)
```
Comment (MaureenHelm) [inline tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c:233]: I think this should be:
```
#elif defined(CONFIG_SOC_SERIES_IMX_RT6XX) && defined(CONFIG_MCUX_OS_TIMER)
```
To account for the possibility that someone switches back to SYSTICK.

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

File: tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 2 above)
Comment (mmahadevan108) [reply tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c]: Thank you. Done

**Review by MaureenHelm — APPROVED** [review]

**Comment by mmahadevan108** [comment]
Anything else needed for this PR?
