### PR TITLE
Bluetooth: BAP: Fix Scan delegator lookup

### LINKED ISSUE #95098: Bluetooth: BAP: Scan Delegator: Wrong checks for broadcast source duplication
### Describe the bug

The BAP Scan Delegator has the following lookup functions: 
```c
bass_lookup_src_id
bass_lookup_pa_sync
bass_lookup_addr
```

Where `bass_lookup_src_id` works as intended, but where the implementation and use of `bass_lookup_pa_sync` and `bass_lookup_addr` should instead use the definition of a duplicate source from the spec, which uses the address type, the broadcast ID and the SID. 

There is an exception where `bass_lookup_pa_sync` is used correctly, which is the `pa_terminated` callback, as we do not have the broadcast ID in that case to perform the "correct" lookup otherwise. 

The behavior of `bass_source_is_duplicate` is what should be used to lookup existing receive states in e.g. `bt_bap_scan_delegator_add_src`, instead of relying on the `param->addr`. 

The reasoning for this is that the `param->addr` can be an RPA, and as such the address on air may change (or we may resolve it if we have the IRK), making it a poor choice for any receive state comparison. 

### Regression

- [ ] This is a regression.

### Steps to reproduce

N/A

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

Sha: a8c8f7f2b81d0dcb5d5f48492723c457fc76af31

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Thalley**
fixes https://github.com/zephyrproject-rtos/zephyr/issues/95098

### CODE REVIEW

File: subsys/bluetooth/audio/bap_broadcast_sink.c [hunk 1]
```diff
@@ -1044,6 +1058,7 @@ int bt_bap_broadcast_sink_create(struct bt_le_per_adv_sync *pa_sync, uint32_t br
 {
 	const struct bt_bap_scan_delegator_recv_state *recv_state;
 	struct bt_bap_broadcast_sink *sink;
+	int err;
```
Comment (babrsn) [inline subsys/bluetooth/audio/bap_broadcast_sink.c]: Nit: might be better to move `int err;` to line 1107, where it’s used.

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 2]
```diff
@@ -653,6 +567,31 @@ static int scan_delegator_add_src(struct bt_conn *conn,
...
+		goto unlock_return;
+	}
+
+	broadcast_id = net_buf_simple_pull_le24(buf);
+
+	internal_state = bass_lookup_state(addr->type, adv_sid, broadcast_id);
+	if (internal_state != NULL) {
+		LOG_DBG("Adding addr type=0x%02X adv_sid=0x%02X and broadcast_id=0x%06X would "
+			"result in duplication",
+			addr->type, adv_sid, broadcast_id);
```
Comment (babrsn) [inline subsys/bluetooth/audio/bap_scan_delegator.c:588]: Indentation?

Comment (Thalley) [reply subsys/bluetooth/audio/bap_scan_delegator.c:588]: Can you elaborate? This is the indentation result from clang-format btw :)

File: subsys/bluetooth/audio/bap_scan_delegator.c [hunk 3]
```diff
@@ -653,6 +567,31 @@ static int scan_delegator_add_src(struct bt_conn *conn,
...
+	}
+
+	adv_sid = net_buf_simple_pull_u8(buf);
+	if (adv_sid > BT_GAP_SID_MAX) {
+		LOG_DBG("Invalid adv SID %u", adv_sid);
+		ret = BT_GATT_ERR(BT_ATT_ERR_VALUE_NOT_ALLOWED);
+		goto unlock_return;
+	}
+
+	broadcast_id = net_buf_simple_pull_le24(buf);
```
Comment (babrsn) [inline subsys/bluetooth/audio/bap_scan_delegator.c:582]: No need to check the broadcast_id validity (`broadcast_id != BT_BAP_INVALID_BROADCAST_ID`)?

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 2 above)
Comment (babrsn) [reply subsys/bluetooth/audio/bap_scan_delegator.c:588]: Uh, sorry, my bad (probably my editor...)!

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/audio/bap_scan_delegator.c:582]: No, there are no invalid broadcast ID values; we define BT_BAP_INVALID_BROADCAST_ID using the upper 8 bits of the 32-bit value we store it in for various reasons, but there are no invalid over-the-air invalid broadcast IDs in the 24 bits

File: subsys/bluetooth/audio/bap_scan_delegator.c (hunk 2 above)
Comment (Thalley) [reply subsys/bluetooth/audio/bap_scan_delegator.c:588]: IIRC, Github just changed the default tab size in the review panels from 8 to 4, so that's might what you are seeing :) You can set it to whatever you like https://docs.github.com/en/account-and-profile/how-tos/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/managing-your-tab-size-rendering-preference (but unfortunately it's a global setting, and not per-repository)

**Review by babrsn — APPROVED** [review]

**Review by ChangNice — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
