### PR TITLE
samples: drivers: led: pwm: Add fallback blink delay calculation

### LINKED ISSUE #77970: tests: pwm: led_pwm: pwm test fail
**Describe the bug**

led_pwm fails with `Increasing brightness gradually`

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
- [ ] mimxrt1060_evk
- [ ] frdm_kw41z
- [ ] mimxrt1170_evk/mimxrt1176/cm7
- [ ] twr_ke18f
- [ ] vmu_rt1170/mimxrt1176/cm7
- [ ] frdm_ke15z

 - What have you tried to diagnose or workaround this issue?
 - NA, this is test and driver support status issue
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - not a regression.

**To Reproduce**

scripts/twister -p mimxrt1060_evk -T samples/drivers/led_pwm

**Expected behavior**

test can pass

**Impact**

supporting for pwm features

**Logs and console output**

```
2024-09-03 03:50:09,713 - twister - DEBUG - Flash command: ['west', 'flash', '--skip-rebuild', '-d', '/home/shared/disk/nxp/mimxrt1060_evk/temp/mimxrt1060_evk_twister_test_only/twister-out/mimxrt1060_evk/samples/drivers/led_pwm/sample.drivers.led.led_pwm', '--runner', 'linkserver', '--probe=022900000582988000000000000000000000000097969905']
2024-09-03 03:50:16,171 - twister - DEBUG - DEVICE: *** Booting Zephyr OS build v3.7.0-1987-g1540bd7d4930 ***
2024-09-03 03:50:16,177 - twister - DEBUG - DEVICE: [00:00:00.005,000] [0m<inf> main: Testing LED 0 - no label[0m
2024-09-03 03:50:16,177 - twister - DEBUG - HARNESS:Console:EXPECTED(1/7):'Testing LED \d+'
2024-09-03 03:50:16,181 - twister - DEBUG - DEVICE: [00:00:00.010,000] [0m<inf> main:   Turned on[0m
2024-09-03 03:50:16,181 - twister - DEBUG - HARNESS:Console:EXPECTED(2/7):'Turned on'
2024-09-03 03:50:17,186 - twister - DEBUG - DEVICE: [00:00:01.015,000] [0m<inf> main:   Turned off[0m
2024-09-03 03:50:17,186 - twister - DEBUG - HARNESS:Console:EXPECTED(3/7):'Turned off'
2024-09-03 03:50:17,440 - twister - DEBUG - -- west flash: using runner linkserver
-- runners.linkserver: LinkServer: /usr/local/LinkServer/LinkServer, version v1.5.30

2024-09-03 03:50:18,192 - twister - DEBUG - DEVICE: [00:00:02.020,000] [0m<inf> main:   Increasing brightness gradually[0m
2024-09-03 03:50:18,192 - twister - DEBUG - HARNESS:Console:EXPECTED(4/7):'Increasing brightness gradually'
2024-09-03 03:50:20,221 - twister - DEBUG - DEVICE: [00:00:04.046,000] [1;31m<err> pwm_mcux: Too long period (234375), adjust pwm prescaler![0m
2024-09-03 03:50:20,225 - twister - DEBUG - DEVICE: [00:00:04.054,000] [1;31m<err> main: err=-22[0m
2024-09-03 03:50:20,231 - twister - DEBUG - DEVICE: [00:00:04.058,000] [0m<inf> main: Testing LED 0 - no label[0m
2024-09-03 03:50:20,235 - twister - DEBUG - DEVICE: [00:00:04.064,000] [0m<inf> main:   Turned on[0m
2024-09-03 03:50:21,240 - twister - DEBUG - DEVICE: [00:00:05.069,000] [0m<inf> main:   Turned off[0m
2024-09-03 03:50:22,246 - twister - DEBUG - DEVICE: [00:00:06.073,000] [0m<inf> main:   Increasing brightness gradually[0m
2024-09-03 03:50:24,274 - twister - DEBUG - DEVICE: [00:00:08.100,000] [1;31m<err> pwm_mcux: Too long period (234375), adjust pwm prescaler![0m
2024-09-03 03:50:24,279 - twister - DEBUG - DEVICE: [00:00:08.108,000] [1;31m<err> main: err=-22[0m
2024-09-03 03:50:24,284 - twister - DEBUG - DEVICE: [00:00:08.112,000] [0m<inf> main: Testing LED 0 - no label[0m
2024-09-03 03:50:24,289 - twister - DEBUG - DEVICE: [00:00:08.118,000] [0m<inf> main:   Turned on[0m
2024-09-03 03:50:25,293 - twister - DEBUG - DEVICE: [00:00:09.122,000] [0m<inf> main:   Turned off[0m
2024-09-03 03:50:26,300 - twister - DEBUG - DEVICE: [00:00:10.127,000] [0m<inf> main:   Increasing brightness gradually[0m
2024-09-03 03:50:28,328 - twister - DEBUG - DEVICE: [00:00:12.153,000] [1;31m<err> pwm_mcux: Too long period (234375), adjust pwm prescaler![0m
2024-09-03 03:50:28,332 - twister - DEBUG - DEVICE: [00:00:12.161,000] [1;31m<err> main: err=-22[0m
2024-09-03 03:50:28,338 - twister - DEBUG - DEVICE: [00:00:12.166,000] [0m<inf> main: Testing LED 0 - no label[0m
2024-09-03 03:50:28,342 - twister - DEBUG - DEVICE: [00:00:12.171,000] [0m<inf> main:   Turned on[0m
2024-09-03 03:50:29,347 - twister - DEBUG - DEVICE: [00:00:13.176,000] [0m<inf> main:   Turned off[0m
2024-09-03 03:50:30,353 - twister - DEBUG - DEVICE: [00:00:14.180,000] [0m<inf> main:   Increasing brightness gradually[0m
2024-09-03 03:50:32,381 - twister - DEBUG - DEVICE: [00:00:16.207,000] [1;31m<err> pwm_mcux: Too long period (234375), adjust pwm prescaler![0m
2024-09-03 03:50:32,386 - twister - DEBUG - DEVICE: [00:00:16.215,000] [1;31m<err> main: err=-22[0m
2024-09-03 03:50:32,391 - twister - DEBUG - DEVICE: [00:00:16.219,000] [0m<inf> main: Testing LED 0 - no label[0m
2024-09-03 03:50:32,396 - twister - DEBUG - DEVICE: [00:00:16.225,000] [0m<inf> main:   Turned on[0m
2024-09-03 03:50:33,400 - twister - DEBUG - DEVICE: [00:00:17.229,000] [0m<inf> main:   Turned off[0m
2024-09-03 03:50:34,407 - twister - DEBUG - DEVICE: [00:00:18.234,000] [0m<inf> main:   Increasing brightness gradually[0m
2024-09-03 03:50:36,435 - twister - DEBUG - DEVICE: [00:00:20.260,000] [1;31m<err> pwm_mcux: Too long period (234375), adjust pwm prescaler![0m
2024-09-03 03:50:36,439 - twister - DEBUG - DEVICE: [00:00:20.268,000] [1;31m<err> main: err=-22[0m
2024-09-03 03:50:36,445 - twister - DEBUG - DEVICE: [00:00:20.273,000] [0m<inf> main: Testing LED 0 - no label[0m
2024-09-03 03:50:36,450 - twister - DEBUG - DEVICE: [00:00:20.278,000] [0m<inf> main:   Turned on[0m
2024-09-03 03:50:37,440 - twister - DEBUG - Timed out while monitoring serial output on mimxrt1060_evk
```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.7.0-1987-g1540bd7d4930

### PR DESCRIPTION
**Pull request by FelixWang47831**
When CONFIG_BLINK_DELAY_SHORT or CONFIG_BLINK_DELAY_LONG exceed the timer's range, automatically calculate blink delays from the LED's PWM period defined in devicetree using configurable divisors.

Add led_periods_ns array to store PWM periods for each LED and new Kconfig options BLINK_DELAY_SHORT_LED_PERIOD_DIV and BLINK_DELAY_LONG_LED_PERIOD_DIV to control the calculation.

This ensures the LED PWM sample works on platforms with timer limitations by providing hardware-appropriate fallback delays.

### CODE REVIEW

File: samples/drivers/led/pwm/src/main.c [hunk 1]
```diff
@@ -80,31 +91,61 @@ static void run_led_test(const struct device *led_pwm, uint8_t led)
 	k_sleep(K_MSEC(1000));
 
 #if CONFIG_BLINK_DELAY_SHORT > 0
+	led_delay = CONFIG_BLINK_DELAY_SHORT;
```
Comment (Holt-Sun) [inline samples/drivers/led/pwm/src/main.c]: (uint32_t)CONFIG_BLINK_DELAY_SHORT, the same below.

Comment (FelixWang47831) [reply samples/drivers/led/pwm/src/main.c]: Fixed.

File: samples/drivers/led/pwm/src/main.c [hunk 2]
```diff
@@ -80,31 +91,61 @@ static void run_led_test(const struct device *led_pwm, uint8_t led)
...
+#if CONFIG_BLINK_DELAY_AUTO_FALLBACK && CONFIG_BLINK_DELAY_SHORT_LED_PERIOD_DIV > 0
+		LOG_INF("CONFIG_BLINK_DELAY_SHORT (%u ms) exceeds PWM capabilities for LED %u.",
+			led_delay, led);
+
+		led_delay = led_periods_ns[led] / 1000000 /
+			(uint32_t)CONFIG_BLINK_DELAY_SHORT_LED_PERIOD_DIV / 2;
+		/* Ensure minimum 1ms for visibility */
+		led_delay = MAX(1, led_delay);
+
+		LOG_INF("Auto-calculating delay: %u ms.", led_delay);
```
Comment (jeppenodgaard) [inline samples/drivers/led/pwm/src/main.c]:
```suggestion
		LOG_INF("Auto-calculated delay: %u ms.", led_delay);
```

File: samples/drivers/led/pwm/src/main.c [hunk 3]
```diff
@@ -80,31 +91,61 @@ static void run_led_test(const struct device *led_pwm, uint8_t led)
...
-			"on: " STRINGIFY(CONFIG_BLINK_DELAY_LONG) "  msec, "
-			"off: " STRINGIFY(CONFIG_BLINK_DELAY_LONG) " msec");
-	} else {
-		LOG_INF("  Blinking "
-			"on: " STRINGIFY(CONFIG_BLINK_DELAY_LONG) " msec, "
-			"off: " STRINGIFY(CONFIG_BLINK_DELAY_LONG) " msec");
+#if CONFIG_BLINK_DELAY_AUTO_FALLBACK && CONFIG_BLINK_DELAY_LONG_LED_PERIOD_DIV > 0
+		LOG_INF("CONFIG_BLINK_DELAY_LONG (%u ms) exceeds PWM capabilities for LED %u.",
+			led_delay, led);
+		led_delay = led_periods_ns[led] / 1000000 /
```
Comment (jeppenodgaard) [inline samples/drivers/led/pwm/src/main.c]: If you wrap these lines into a function they do not need to be duplicated, e.g.:

```c
int blink_delay_auto_fallback(const struct device *led_pwm, uint64_t period, uint32_t div)
{
		led_delay = period / 1000000 / div / 2;
		/* Ensure minimum 1ms for visibility */
		led_delay = MAX(1, led_delay);

		LOG_INF("Auto-calculated delay: %u ms.", led_delay);

		err = led_blink(led_pwm, led, led_delay, led_delay);
}
```

**Review by jeppenodgaard — COMMENTED** [review]
Thank you for fixing this - I like how the fix does not complicate the LED PWM driver.

File: samples/drivers/led/pwm/src/main.c (hunk 2 above)
Comment (FelixWang47831) [reply samples/drivers/led/pwm/src/main.c]: Fixed

File: samples/drivers/led/pwm/src/main.c (hunk 3 above)
Comment (FelixWang47831) [reply samples/drivers/led/pwm/src/main.c]: Done.

**Review by jeppenodgaard — DISMISSED** [review]
LGTM.
Nit: Consider formatting `LOG_INF` lines after `STRINGIFY` is no longer used to use 1-2 
lines instead of 3.

**Comment by FelixWang47831** [comment]
> LGTM. Nit: Consider formatting `LOG_INF` lines after `STRINGIFY` is no longer used to use 1-2 lines instead of 3.

Fixed.

**Review by Holt-Sun — DISMISSED** [review]

**Review by jeppenodgaard — DISMISSED** [review]

**Review by simonguinot — CHANGES_REQUESTED** [review]
Hi @FelixWang47831

Thanks for this patch. It looks reasonable to me.

Can you please fix README.rst ?

**Comment by FelixWang47831** [comment]
> Hi @FelixWang47831
> 
> Thanks for this patch. It looks reasonable to me.
> 
> Can you please fix README.rst ?

Updated.

**Review by simonguinot — APPROVED** [review]
Thanks !

**Review by ZhaoxiangJin — APPROVED** [review]

**Review by jeppenodgaard — APPROVED** [review]
