### PR TITLE
Bluetooth: host: adv: set the address in bt_le_adv_resume

### LINKED ISSUE #52059: Bluetooth: conn:  in multi role configuration incorrect adress is set after advertising resume
**Describe the bug**
Advertising resume in Host is limited operation in comparison to regular advertising enable operation. Limited in a way, there is no device address check/update before the advertising is resumed. When scanner is resumed and identity address is not used, Host uses NRPA address for a device when scanning. This address is different than static random address. When connection in peripheral role is disconnected, Host resumes advertising and continues use of address set by scan resume.
 
Now, assume that an application starts a connection in central role. Both functions `bt_le_create_conn_ext` and `bt_le_create_conn_legacy` call `bt_id_set_create_conn_own_addr`. The last one mentioned function attempts to change an address to static random address: https://github.com/zephyrproject-rtos/zephyr/blob/e104e031b7d3ddacd2b90527fff438fc4056b72a/subsys/bluetooth/host/id.c#L1519-L1528. Unfortunately that will not happen, because there is an advertising running and Controller returns error `BT_HCI_ERR_CMD_DISALLOWED` for Host command: `BT_HCI_OP_LE_SET_RANDOM_ADDRESS`.

It looks to me that, to fix the issue we need to run Bluetooth address setup before advertising is resumed. Unfortunately that would require storage of some information that are provided to Host when advertising is started by `bt_le_adv_start`.

**To Reproduce**
The issue may be reproduced according to steps in #50438.

**Expected behavior**
It should be possible to established a connection in central even though there is an advertising pending in the background.

**Impact**
Not sure how sever is the issue and what impact it has on end users.

**Additional context**
The issue was found during investigation of #50438.

### PR DESCRIPTION
**Pull request by jori-nordic**
Bluetooth: host: adv: set the address in bt_le_adv_resume

The address could have changed. The issue linked (and bsim test in previous
commit) shows a scenario where that could happen:

- we start scanning, host will use NRPA
- we start advertising, host will use identity address
- a device connects (as a central)
-> advertising resume fails for some unrelated reason
- another device connects (as a peripheral)
- the central device disconnects, we resume scanning
- the peripheral disconnects, the stack resumes advertising
-> but it mistakenly advertises using the NRPA set by the scanner

Fixes #52059 .

### CODE REVIEW

File: subsys/bluetooth/host/adv.c [hunk 1]
```diff
@@ -1469,6 +1485,17 @@ void bt_le_adv_resume(void)
 	if (IS_ENABLED(CONFIG_BT_PRIVACY) &&
 	    !atomic_test_bit(adv->flags, BT_ADV_USE_IDENTITY)) {
 		bt_id_set_adv_private_addr(adv);
+	} else {
+		uint8_t own_addr_type;
+		bool dir_adv = !bt_addr_le_eq(&adv->target_addr, BT_ADDR_LE_ANY);
+		uint32_t options = adv_get_options(adv);
+
+		/* Always set the address. Don't assume it has not changed. */
+		err = bt_id_set_adv_own_addr(adv, options, dir_adv, &own_addr_type);
```
Comment (jhedberg) [inline subsys/bluetooth/host/adv.c:1494]: Seems like some refactoring/redesign might be in order here, so that we avoid doing the conversions between `options` and `flags` back and forth. You're already passing `adv` to `bt_id_set_adv_own_addr()`, so it shouldn't be necessary to pass the options separately to it (same information in two places).

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/adv.c (hunk 1 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/adv.c:1494]: yep I thought the same, and actually started doing it. But then I figured it'd be better in a separate PR. The whole advertising module needs a big spring cleaning, that we're probably going to do this year.

**Review by jhedberg — DISMISSED** [review]

File: subsys/bluetooth/host/adv.c [hunk 2]
```diff
@@ -1437,6 +1437,25 @@ int bt_le_adv_stop(void)
 }
 
 #if defined(CONFIG_BT_PERIPHERAL)
+static uint32_t adv_get_options(struct bt_le_ext_adv *adv)
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:1440]:
```suggestion
static uint32_t adv_get_options(const struct bt_le_ext_adv *adv)
```

File: subsys/bluetooth/host/adv.c [hunk 3]
```diff
@@ -1469,6 +1488,17 @@ void bt_le_adv_resume(void)
 	if (IS_ENABLED(CONFIG_BT_PRIVACY) &&
 	    !atomic_test_bit(adv->flags, BT_ADV_USE_IDENTITY)) {
 		bt_id_set_adv_private_addr(adv);
+	} else {
+		uint8_t own_addr_type;
+		bool dir_adv = !bt_addr_le_eq(&adv->target_addr, BT_ADDR_LE_ANY);
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:1493]: Perhaps outside the scope of this PR: I think it would be nice to have this in a function or macro; it seems to just be implied that we use `BT_ADDR_LE_ANY` for nondirected advertising.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/prj.conf [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+CONFIG_BT_LOG_SNIFFER_INFO=y
+
+CONFIG_BT_AUTO_PHY_UPDATE=n
+CONFIG_BT_AUTO_DATA_LEN_UPDATE=n
+CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=n
+
+# Set to 3 to see the problem go away
+CONFIG_BT_MAX_CONN=2
+CONFIG_BT_MAX_PAIRED=2
+CONFIG_BT_ID_MAX=2
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/prj.conf:21]: Is the comment still valid? What problem is it referring to?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+		FAIL("Unexpected advertisement type.");
+	}
+
+	bt_addr_le_to_str(addr, addr_str, sizeof(addr_str));
+	printk("Got scan result, connecting.. dst %s, RSSI %d\n", addr_str, rssi);
+
+	err = bt_le_scan_stop();
+	ASSERT(!err, "Err bt_le_scan_stop %d", err);
+
+	struct bt_conn *conn;
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:92]: Suggest to declare variables at top of scope

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+{
+	int err;
+
+	err = bt_enable(NULL);
+	ASSERT(!err, "bt_enable failed.\n");
+}
+
+static bt_addr_le_t last_scanned_addr;
+
+static void scan_connect_to_first_result__device_found(const bt_addr_le_t *addr, int8_t rssi,
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:75]:
```suggestion
static void scan_connect_to_first_result_device_found(const bt_addr_le_t *addr, int8_t rssi,
```

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 7]
```diff
@@ -0,0 +1,179 @@
...
+void scan_connect_to_first_result(void)
+{
+	int err;
+
+	printk("start scanner\n");
+	err = bt_le_scan_start(BT_LE_SCAN_PASSIVE, scan_connect_to_first_result__device_found);
+	ASSERT(!err, "Err bt_le_scan_start %d", err);
+}
+
+static void scan_expect_same_address__device_found(const bt_addr_le_t *addr, int8_t rssi,
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:110]:
```suggestion
static void scan_expect_same_address_device_found(const bt_addr_le_t *addr, int8_t rssi,
```

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 8]
```diff
@@ -0,0 +1,179 @@
...
+	if (type != BT_HCI_ADV_IND && type != BT_HCI_ADV_DIRECT_IND) {
+		FAIL("Unexpected advertisement type.");
+	}
+
+	if (!bt_addr_le_eq(&last_scanned_addr, addr)) {
+		bt_addr_le_to_str(&last_scanned_addr, expected_addr_str, sizeof(expected_addr_str));
+		bt_addr_le_to_str(addr, addr_str, sizeof(addr_str));
+		FAIL("Expected advertiser with addr %s, got %s\n", expected_addr_str, addr_str);
+	}
+	PASS("Advertiser used correct address on resume\n");
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:126]:
```suggestion
	}
	
	PASS("Advertiser used correct address on resume\n");
```

Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:126]: Not a huge fan of doing `PASS` in a file called `utils`. IMO the test case implementation should be responsible for passing/failing tests.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 9]
```diff
@@ -0,0 +1,179 @@
...
+}
+
+void scan_expect_same_address(void)
+{
+	int err;
+
+	printk("start scanner\n");
+	err = bt_le_scan_start(BT_LE_SCAN_PASSIVE, scan_expect_same_address__device_found);
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:134]:
```suggestion
	err = bt_le_scan_start(BT_LE_SCAN_PASSIVE, scan_expect_same_address_device_found);
```

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 10]
```diff
@@ -0,0 +1,179 @@
...
+}
+
+static void disconnect_device(struct bt_conn *conn, void *data)
+{
+	int err;
+	struct bt_conn_info info;
+
+	bt_conn_get_info(conn, &info);
+
+	uint8_t role = *(uint8_t *)data;
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:145]: Suggest to declare variables at top of scope

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 11]
```diff
@@ -0,0 +1,179 @@
...
+
+	if (role != info.role) {
+		return;
+	}
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:149]: What is the purpose of this?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 12]
```diff
@@ -0,0 +1,179 @@
...
+
+	SET_FLAG(flag_is_connected);
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:151]: Why are we setting this flag here?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.h [hunk 13]
```diff
@@ -0,0 +1,78 @@
...
+
+#include "bs_tracing.h"
+#include "bs_types.h"
+#include "bstests.h"
+#include "time_machine.h"
+#include "zephyr/sys/__assert.h"
+
+#include <errno.h>
+#include <stddef.h>
+#include <stdint.h>
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.h:17]: These are included by `include <zephyr/types.h>` you have further down

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.h [hunk 14]
```diff
@@ -0,0 +1,78 @@
+/**
+ * Common functions and helpers for BSIM GATT tests
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.h:2]:
```suggestion
 * Common functions and helpers for BSIM adv tests
```

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.h [hunk 15]
```diff
@@ -0,0 +1,78 @@
...
+#include <zephyr/bluetooth/conn.h>
+#include <zephyr/bluetooth/gatt.h>
+#include <zephyr/bluetooth/hci.h>
+#include <zephyr/bluetooth/uuid.h>
+#include <zephyr/kernel.h>
+#include <zephyr/types.h>
+
+extern enum bst_result_t bst_result;
+
+#define DECLARE_FLAG(flag) extern atomic_t flag
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.h:29]:
```suggestion
#define DECLARE_EXTERN_FLAG(flag) extern atomic_t flag
```

Is this macro really needed/useful? Perhaps it's not a good idea to use external flags in the first place?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c [hunk 16]
```diff
@@ -0,0 +1,57 @@
...
+#include <stdint.h>
+
+#include <zephyr/bluetooth/bluetooth.h>
+
+void adv_new_ident(void)
+{
+	/* create a new identity:
+	 * the stack disallows connecting to the same peer twice
+	 */
+	int id_a = bt_id_create(NULL, NULL);
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:20]: Why do we need to connect to the same device in the first place? It should be trivial to add more devices to the test.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c [hunk 17]
```diff
@@ -0,0 +1,57 @@
...
+
+	ASSERT(id_a >= 0, "bt_id_create id_a failed (err %d)\n", id_a);
+	advertise_connectable(id_a, 0);
+}
+
+void central_procedure(void)
+{
+	bs_bt_utils_setup();
+	k_msleep(1000);
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:29]: Why is this sleep needed?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c [hunk 18]
```diff
@@ -0,0 +1,57 @@
...
+	k_sleep(K_SECONDS(5));
+
+	printk("disconnect central\n");
+	disconnect(BT_CONN_ROLE_CENTRAL);
+
+	/* DUT starts advertising again (with scanner's NRPA)
+	 * should give wrong address
+	 */
+	scan_expect_same_address();
+	k_sleep(K_SECONDS(1));
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:54]: Why is this sleep needed?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/main.c [hunk 19]
```diff
@@ -0,0 +1,39 @@
...
+	},
+	BSTEST_END_MARKER,
+};
+
+static struct bst_test_list *install(struct bst_test_list *tests)
+{
+	return bst_add_tests(tests, test_to_add);
+};
+
+bst_test_install_t test_installers[] = {install, NULL};
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/main.c:34]:
```suggestion
bst_test_install_t test_installers[] = { install, NULL };
```

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c [hunk 20]
```diff
@@ -0,0 +1,58 @@
...
+
+#include <stdint.h>
+#include <string.h>
+
+void peripheral_procedure(void)
+{
+	bs_bt_utils_setup();
+
+	printk("DUT start\n");
+	k_msleep(1000);
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:21]: Why is this sleep needed?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c [hunk 21]
```diff
@@ -0,0 +1,58 @@
...
+
+	/* start scanning (using NRPA) */
+	scan_connect_to_first_result();
+	k_msleep(100);
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:25]: Why is this sleep needed?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c [hunk 22]
```diff
@@ -0,0 +1,58 @@
...
+	advertise_connectable(0, 1);
+
+	wait_disconnected();
+	printk("DUT is central\n");
+	scan_connect_to_first_result();
+
+	wait_disconnected();
+	printk("DUT has no connections\n");
+
+	k_sleep(K_SECONDS(1));
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:55]: Why is this sleep needed?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/test_scripts/run_test.sh [hunk 23]
```diff
@@ -0,0 +1,44 @@
+#!/usr/bin/env bash
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/test_scripts/run_test.sh:1]: Since this shell scrip will be run by the `run_parallel.sh`, it would be better to give it a more descriptive name, especially since we now have multiple `run_test.sh` scripts.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/test_scripts/run_test.sh [hunk 24]
```diff
@@ -0,0 +1,44 @@
...
+cd ${BSIM_OUT_PATH}/bin
+
+Execute "$central_exe" \
+    -v=${verbosity_level} -s=${simulation_id} -d=0 -testid=central -RealEncryption=1
+
+Execute ./bs_2G4_phy_v1 -v=${verbosity_level} -s=${simulation_id} \
+    -D=2 -sim_length=60e6 $@
+
+Execute "$peripheral_exe" \
+    -v=${verbosity_level} -s=${simulation_id} -d=1 -testid=peripheral -RealEncryption=1
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/test_scripts/run_test.sh:35]:
```suggestion
Execute "$peripheral_exe" \
    -v=${verbosity_level} -s=${simulation_id} -d=1 -testid=peripheral -RealEncryption=1
    
Execute ./bs_2G4_phy_v1 -v=${verbosity_level} -s=${simulation_id} \
    -D=2 -sim_length=60e6 $@
```

Suggest to switch the order

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/adv.c (hunk 3 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/adv.c:1493]: Yeah that's the easiest way I thought of sensing this. The advertiser needs some refactoring, and we're going to do that this year. I'll add a macro though, it makes the code more readable.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/prj.conf (hunk 4 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/prj.conf:21]: It is now invalid. The first commit introduces a failing test (ie, the "problem"). If this is set to 3, then the test passes.
I'll remove it altogether.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 8 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:126]: yeah utils isn't really utils. I took the structure from `bsim_test_bond_overwrite_denied` because I liked that the test sequence itself (in central.c and peripheral.c) was very clear.
utils is the test case implementation really; the `central.c` and `peripheral.c` are just the abstract test sequence.
I can rename it to `common.c` if you prefer.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 11 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:149]: You can see where it's called. Since it's an iterator on all the connections, the test is interested in only disconnecting the conns where it has a specific role, eg. central or peripheral. This is my way of doing it.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 12 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:151]: because I cheat and don't have a flag per-connection. Since this fn waits until it is unset (in the disconnected callback), i have to set it again for the next iteration.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.h (hunk 15 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.h:29]: it is not indeed.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 16 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:20]: It is easier to coordinate two devices instead of three. We're only interested in making 3 connections, we don't really need 3 devices to reproduce a logic bug. Ideally, this would've been an unit test.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 17 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:29]: So the logs from bootup and HCI init are not interspersed with the logs from the test suite.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 18 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:54]: To leave some time for the scanner to get at least one report.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c (hunk 20 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:21]: same reason as central.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c (hunk 21 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:25]: so the stack has time to fully start up the scanner. Since the stack is a bit of a mess with all the different threads (and the wq) and whatnot, I prefer to give myself some room to be sure it has properly started before attempting to start the advertiser.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c (hunk 22 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:55]: so the advertiser has the time to re-start and send out a few packets after the disconnect has been fully handled. See https://github.com/zephyrproject-rtos/zephyr/pull/52940#discussion_r1049302068 .

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 8 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c]: It's more about having test PASS/FAIL criteria outside the test case implementation, rather than the naming. Renaming to `common` isn't going to help that. 

Having PASS/FAIL criteria outside the test case implementation, will make it harder to reuse for other test cases that may want to use the same common functions.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 11 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:150]: I see. Please add an in-code comment as to why it is here then :)

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 12 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:152]: I see. Please comment such non-obvious behavior :)

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 16 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:20]: If it is logic behavior, why we do need 2 connections in the first place? 

IMO it would be a better solution to do it "properly" with 2 actual connections to devices, rather than multiple connections to the same device, unless it is specifically needed to have multiple connections to the same device. I assume that whatever we are testing here are to verify that it works against multiple devices, right? The test case is better off simulating the actual scenario.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 17 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:29]: I'm not sure I follow. Is this just to have the logs more separated? 

IMO it would be much better to wait on some event, than a timer with a fairly arbitrary value (1000ms) in that case. 

At the very least such things should be documented/commented, but I don't really understand why you'd need the logs separated in the first place.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 18 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:54]: IMO it would be better to use a flag for this, and wait for the flag to be set. Arbitrary timer values such as this makes it much more difficult to follow the code, and to know why we are waiting.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c (hunk 21 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:25]: Starting scanning happens in the same thread. Once e.g. `bt_le_scan_start` returns you know that the device is in a scanning state. 

Generally I highly dislike using timers to ensure state correctness.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c (hunk 22 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:55]: I see. For advertising it is a bit more tricky to handle, as we don't get events in the host when advertising packets are sent. 

Two non-timing solutions:
1) Use the babblesim backchannel to sync between the central and peripheral, so that we instead of waiting for a timer, we wait for the central to have seen our advertisements
2) Simply remove; since we are not disabling Bluetooth after `PASS`ing, the peripheral should still continue advertising after ending this function. The `k_sleep` here is basically providing nothing IMO.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 8 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c]: as I said, I consider this file to be part of the test case implementation. It's just split off into its own file for clarity's sake.

I know we love huge files in zephyr, so I can definitely move back all the code into the same `central.c` or `peripheral.c` if we prefer that.

The second sentence is a bit disingenuous, since it's litteraly one line to remove. The chance the function will be re-used as-is is pretty slim, usually we need to make a small tweak, so removing _one_ PASS/FAIL line isn't the end of the world IMO.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 11 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:150]: will do

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 16 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:20]: You're right, I will edit it accordingly.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 17 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:29]: well it's just easier to parse. I highlighted in red what I don't care about in the test:
with the wait: 
image
without waiting
image

I can of course remove it if you don't like it.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 18 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c]: removed

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c (hunk 21 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:25]: so on real devices, I agree 100%. In bsim tests, which are deterministic (and where waiting is instant in CPU time) afaik, it doesn't matter as much IMO.
I tried it without the sleep, and it works as you said now. But I don't think the API gives any guarantees about the operation being synchronous, so the controller may decide to do it async in the future.

Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/peripheral.c:25]: > But I don't think the API gives any guarantees about the operation being synchronous, so the controller may decide to do it async in the future.

That is true. I don't believe our APIs actually say whether they are synchronous or asynchronous operations. It is, however, the host and not controller that makes e.g. `scan_start` sync by using `bt_hci_cmd_send_sync`. @jhedberg @alwa-nordic is this something we should describe in the API in some way?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 8 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c]: > as I said, I consider this file to be part of the test case implementation. It's just split off into its own file for clarity's sake.

The reason why it is in a common file, is specifically because you use it in with two test cases, right? You have the peripheral and central tests, which both use it (I realize that I have no been explicitly in saying that those are actually two different test implementations, but they should be considered as such with their own `test_id`s, etc.). 

Anyways, having PASS/FAIl scattered around in multiple files will make it much harder to debug in the future IMO.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c (hunk 17 above)
Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c:29]: Yeah, I see what you mean. 

This is caused by the logs being delayed (offloaded), and that the test uses `printk`.

Two possible (non-timer) solutions are
1) Use `CONFIG_LOG_MODE_IMMEDIATE` (may slightly affect the timing of the stack)
2) Use the logging system in the test

The same argument with wanting to separate the logs and the `printk` could be said for e.g. the shell implementation as well. Furthermore, adding a timer here, only helps this the init; any action you do in the test will have the same issue if you enabled any debug logging.

Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/central.c]: Yeah I just removed the wait. For debugging, we can always convert all the printk's to LOG_INFs. Don't need to address it now.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 8 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c]: That's a fair point. I added a comment in the DUT to signal that the PASS will come from the connected callback.
Then it's only FAIL that is sprinkled around, I just used it as an analogue to ASSERT, since that's what was being done when I initially copied this utils file. I can definitely change them to assert statements if you prefer.

Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c]: No, it's alright for now I think

File: subsys/bluetooth/host/adv.c [hunk 25]
```diff
@@ -1437,6 +1437,33 @@ int bt_le_adv_stop(void)
 }
 
 #if defined(CONFIG_BT_PERIPHERAL)
+static inline bool adv_is_directed(struct bt_le_ext_adv *adv)
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:1440]: Consider using this for the other places in `adv.c` where we are doing the `BT_ADDR_LE_ANY` comparison :)

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 26]
```diff
@@ -0,0 +1,220 @@
...
+ */
+
+#include "bs_bt_utils.h"
+#include "argparse.h"
+#include "bs_pc_backchannel.h"
+
+BUILD_ASSERT(CONFIG_BT_MAX_PAIRED >= 2, "CONFIG_BT_MAX_PAIRED is too small.");
+BUILD_ASSERT(CONFIG_BT_ID_MAX >= 2, "CONFIG_BT_ID_MAX is too small.");
+
+#define BS_SECONDS(dur_sec)    ((bs_time_t)dur_sec * 1000000)
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:14]:
```suggestion
#define BS_SECONDS(dur_sec)    ((bs_time_t)dur_sec * USEC_PER_SEC)
```

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 27]
```diff
@@ -0,0 +1,220 @@
...
+		FAIL("Unexpected advertisement type.");
+	}
+
+	bt_addr_le_to_str(addr, addr_str, sizeof(addr_str));
+	printk("Got scan result, connecting.. dst %s, RSSI %d\n", addr_str, rssi);
+
+	err = bt_le_scan_stop();
+	ASSERT(!err, "Err bt_le_scan_stop %d", err);
+
+	err = bt_conn_le_create(addr, BT_CONN_LE_CREATE_CONN, BT_LE_CONN_PARAM_DEFAULT, &conn);
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:95]: Consider making it this
```suggestion
	err = bt_conn_le_create(addr, BT_CONN_LE_CREATE_CONN, BT_LE_CONN_PARAM_DEFAULT, 
				&conn);
```
as 80 is the still the recommended maximum line length. I see a few other lines here and there that could be made to less than 80.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c [hunk 28]
```diff
@@ -0,0 +1,220 @@
...
+	if (!bt_addr_le_eq(&last_scanned_addr, addr)) {
+		bt_addr_le_to_str(&last_scanned_addr, expected_addr_str, sizeof(expected_addr_str));
+		bt_addr_le_to_str(addr, addr_str, sizeof(addr_str));
+		FAIL("Expected advertiser with addr %s, got %s\n", expected_addr_str, addr_str);
+	}
+
+	PASS("Advertiser used correct address on resume\n");
+}
+
+void scan_expect_same_address(void)
```
Comment (Thalley) [inline tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:131]: This seems to only be used by the central/tester. Could be a static function in `tester.c` if not used for anything else

Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:131]: The same seems to apply for multiple other functions. 

Can you please explain me why these have been moved to a common/util file, if they are not common nor used by anything but a single test/file?

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 27 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:95]: yeah. It would be great to have a different level than error in checkpatch. That way we could keep 80chars as the default, but still allow for the newer 100 (or is it 120) for select cases. I usually just run clang-format.

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 28 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:131]: They haven't been moved there, they have always been there.
They use state from the other common fns, specifically `flag_is_connected` and `last_scanned_addr`.

Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:131]: I could remove anything not bsim boilerplate from that file, but we'd have a bunch of duplication. The other issue is this 
```c
BT_CONN_CB_DEFINE(conn_callbacks) = {
	.connected = connected,
	.disconnected = disconnected,
};
```
Since it's the same exe being built for both testers & dut, the callbacks would be called twice on each device. A bunch of bsim tests have this problem actually.

Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:139]: Indeed. `BT_CONN_CB_DEFINE` may not be the right way for BSIM tests :)

Comment (Thalley) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:139]: > They haven't been moved there, they have always been there. They use state from the other common fns, specifically `flag_is_connected` and `last_scanned_addr`.

It's fine for now anyways :)

**Review by Thalley — APPROVED** [review]

File: tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c (hunk 28 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_adv_resume/src/bs_bt_utils.c:139]: > Indeed. `BT_CONN_CB_DEFINE` may not be the right way for BSIM tests :)

yeah it might be better to register at runtime in those cases. We are thinking of making a proper bsim test framework, with a template that can be re-used.

**Comment by jori-nordic** [comment]
@jhedberg could you re-approve?

**Review by jhedberg — APPROVED** [review]

**Review by ppryga-nordic — APPROVED** [review]
I didn't review tests. Besides that LGTM.
