### PR TITLE
soc: arm: nordic: fix GPIO pin forwarder initialization

### LINKED ISSUE #43476: tests: nrf: Output of nrf5340dk_nrf5340_cpuapp_ns not available
**Describe the bug**
Commit 81c48c3e684f1277b89e711b72366a5a676bc880 introduced a regression: with it an output of nrf5340dk_nrf5340_cpuapp_ns is no longer available and all tests fail on this platform.

**To Reproduce**
1. checkout on 81c48c3e684f1277b89e711b72366a5a676bc880 
2. west update
3. have nrf53 connected
4. run `zephyr/scripts/twister --testcase-root zephyr/tests/crypto/rand32/ --platform nrf5340dk_nrf5340_cpuapp_ns --device-serial /dev/ttyACM2 --device-testing --verbose --inline-logs --west-flash -v`
5. See error: no output, failed with timeout

**Expected behavior**
Output is given, tests pass.

**Impact**
Showstopper 

**Logs and console output**
No output available

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr sdk
 - Commit SHA or Version used 81c48c3e684f1277b89e711b72366a5a676bc880

### PR DESCRIPTION
**Pull request by jciupis**
nRF5340 application core should not attempt to pass control over any
pins to the nRF5340 network core if the latter is disabled.

This commit fixes https://github.com/zephyrproject-rtos/zephyr/issues/43476.

Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

### CODE REVIEW

File: soc/arm/nordic_nrf/nrf53/soc.c [hunk 1]
```diff
@@ -49,7 +49,8 @@ extern void z_arm_nmi_init(void);
 #endif
 
 #if (!defined(CONFIG_TRUSTED_EXECUTION_NONSECURE) || defined(CONFIG_BUILD_WITH_TFM)) && \
-	defined(CONFIG_SOC_NRF5340_CPUAPP) && DT_HAS_COMPAT_STATUS_OKAY(nordic_nrf_gpio_forwarder)
+	defined(CONFIG_SOC_NRF5340_CPUAPP) && DT_HAS_COMPAT_STATUS_OKAY(nordic_nrf_gpio_forwarder) \
+	&& defined(CONFIG_BOARD_ENABLE_CPUNET)
```
Comment (anangl) [inline soc/arm/nordic_nrf/nrf53/soc.c:53]: How about tidying this a bit and using a more logical order? I mean something like:
```
#if DT_HAS_COMPAT_STATUS_OKAY(nordic_nrf_gpio_forwarder) &&
	defined(CONFIG_BOARD_ENABLE_CPUNET) &&
	(!defined(CONFIG_TRUSTED_EXECUTION_NONSECURE) ||
	 defined(CONFIG_BUILD_WITH_TFM))
```
I omitted `defined(CONFIG_SOC_NRF5340_CPUAPP)` as it became redundant now.

**Review by anangl — DISMISSED** [review]
LGTM
But I don't actually see how it is related to #43476. Does it indeed fix the issue? EDIT: ah, it's built with TF-M then, I think I get the relation now.

**Comment by PerMac** [comment]
I can confirm that it fixes https://github.com/zephyrproject-rtos/zephyr/issues/43476

**Review by PerMac — DISMISSED** [review]

**Comment by jciupis** [comment]
@anangl the commit that introduced the regression described in #43476: https://github.com/zephyrproject-rtos/zephyr/commit/81c48c3e684f1277b89e711b72366a5a676bc880 accidentally enabled forwarding of UART pins to the network core in cases that had it disabled before. This PR aligns the behavior, so that pins are forwarded to the network core only when it is actually enabled.

However, as @joerchan has found out in parallel, even with this accidentally enabled forwarding, the expected outcome is different from what was observed in #43476. We're currently working on preparing a follow-up PR that will fix the wrong behavior that was brought to daylight when https://github.com/zephyrproject-rtos/zephyr/commit/81c48c3e684f1277b89e711b72366a5a676bc880 was merged.

**Review by anangl — APPROVED** [review]

**Review by PerMac — APPROVED** [review]

**Comment by PerMac** [comment]
@carlescufi Can you merge this one? It fixes a regression breaking nrf53_ns output. I run a test suite on this PR and with it nrf53_ns is again passing tests.
