### PR TITLE
gptp: fix endianness of correction field in sync follow up message

### LINKED ISSUE #42799: gptp correction field in sync follow up message does not have correct endianness
**Describe the bug**
When gptp prepare sync follow up message, endianness of correction does not get converted to network endianness. 

https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/l2/ethernet/gptp/gptp_md.c#L51-L54
Other filed in followup hdr get converted to network endian not correction_field.

**To Reproduce**
1. Run gptp
2. Set correction_field in follow up message to non-zero value
3. Monitor gptp follow up message in wireshark
4. Correction field value does not match expected value. Endianness is incorrect.

**Expected behavior**
a htonll should be called to convert correct_field to network endian (big endian).

**Impact**
Slave port receives followup message from master port can't calculate timestamp correctly due to incorrect correction_field in followup message

### PR DESCRIPTION
**Pull request by bibibibi89**
#42799 

When gptp prepare sync follow up message, endianness of correction does not get converted to network endianness

Signed-off-by: Lu Ding <lucasdinglu@gmail.com>

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
Please use `net: gptp: `prefix and add some body to the commit message.

File: subsys/net/l2/ethernet/gptp/gptp_md.c [hunk 1]
```diff
@@ -52,6 +52,7 @@ static void gptp_md_follow_up_prepare(struct net_pkt *pkt,
 	hdr->correction_field *= sync_send->rate_ratio;
 	hdr->correction_field += sync_send->follow_up_correction_field;
 	hdr->correction_field <<= 16;
+	hdr->correction_field = htons(hdr->correction_field);
```
Comment (jukkar) [inline subsys/net/l2/ethernet/gptp/gptp_md.c:55]: This is a 64 bit field, shouldn't we do `htonll` here?

Comment (bibibibi89) [reply subsys/net/l2/ethernet/gptp/gptp_md.c]: sorry. fixed.

**Review by jukkar — DISMISSED** [review]

**Review by rlubos — DISMISSED** [review]
You need to split commit message body in two lines (there's a char/line limit), but otherwise looks good.

**Review by dleach02 — DISMISSED** [review]

**Comment by carlescufi** [comment]
@bibibibi89 

You need to add an empty line between the commit title and body:

```
net: gptp: fix endianness of correction field in sync follow up message
<add an empty line here please>
correction field in sync follow up message must be converted from host
endianness to network endianness.
```

**Comment by bibibibi89** [comment]
Passed all checks. May I get some reviews? Thanks.

**Review by jukkar — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
