### PR TITLE
sensor: bq274xx: fix design energy calculation

### LINKED ISSUE #98146: sensor: bq274xx: Error in design energy calculation
### Describe the bug

The calculation of the design energy in the function  `bq274xx_gauge_configure` uses an hardcoded value of 3.7V all the time even if the design voltage parameter is different. I am currently working with a 3.85V and 590 mAh battery which design energy is 2272 Wh but this calculation is giving 2183 Wh.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mcunha-rsc**
In the function bq274xx_gauge_configure it was being used an hardcoded value of 3.7V instead of using the design voltage parameter defined in the device tree.

### CODE REVIEW

**Review by MaureenHelm — DISMISSED** [review]
Thanks for the fix!

**Review by ubieda — DISMISSED** [review]

File: drivers/sensor/ti/bq274xx/bq274xx.c [hunk 1]
```diff
@@ -418,7 +418,7 @@ static int bq274xx_gauge_configure(const struct device *dev)
 	}
 	regs = data->regs;
 
-	designenergy_mwh = (uint32_t)config->design_capacity * 37 / 10; /* x3.7 */
+	designenergy_mwh = (uint32_t)config->design_capacity * ((uint32_t)config->design_voltage) / 1000;
```
Comment (fabiobaltieri) [inline drivers/sensor/ti/bq274xx/bq274xx.c]: > drivers/sensor/ti/bq274xx/bq274xx.c:421  line length of 105 exceeds 100 columns

Need to wrap it. Also do you need the parenthesis around the casting?

File: drivers/sensor/ti/bq274xx/bq274xx.c [hunk 2]
```diff
@@ -418,7 +418,8 @@ static int bq274xx_gauge_configure(const struct device *dev)
 	}
 	regs = data->regs;
 
-	designenergy_mwh = (uint32_t)config->design_capacity * 37 / 10; /* x3.7 */
+	designenergy_mwh = (uint32_t)config->design_capacity *
+										((uint32_t)config->design_voltage) / 1000;
```
Comment (fabiobaltieri) [inline drivers/sensor/ti/bq274xx/bq274xx.c]: ok now that's like double the tabs they need to be :-) set your editor (and github, who sadly changed the default) to 8 spaces per tab

Comment (fabiobaltieri) [reply drivers/sensor/ti/bq274xx/bq274xx.c]: x

this is how it looks here with the settings normally used for zephyr code

**Review by fabiobaltieri — APPROVED** [review]

**Review by ubieda — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
