### PR TITLE
ztest: native_sim: fail instead of crashing on wrong arguments

### LINKED ISSUE #91655: ZTEST seg faults on native_sim when providing intuitive yet incorrect "-test=" param.
A built ZTEST executable crashes when providing an intuitive yet incorrect `"-test="` parameter.

I am building tests for the `native_sim` board. I have defined a `ZTEST_SUITE(TempTests, NULL, NULL, NULL, NULL, NULL);` and `ZTEST(TempTests, testTemp)` in a C/C++ file. If I build the executable, and then run it passing in the argument `--test="TempTests"`:

```bash
west build -b native_sim
./build/test/zephyr/zephyr.exe --test="TempTests"
```

The executable crashes with a segmentation fault:

```bash
*** Booting nRF Connect SDK v3.0.1-9eb5615da66b ***
*** Using Zephyr OS v4.0.99-77f865b8f8d0 ***
Running TESTSUITE TempTests
===================================================================
Segmentation fault (core dumped)
```

I realize `--test="TempTests"` is not correct syntax, and it should really be `--test="TempTests::*"` (changing it fixes the issue). But I argue that this is non-intuitive, many people would expect to be able to run an entire suite by just specifying `TempTests`. At least rather than seg faulting is should return an error.

If I use gdb to debug the issue:

```
 gdb --args ./build/test/zephyr/zephyr.exe --test="TempTests"
run
bt
Thread 3 "main" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf70ffac0 (LWP 431681)]
0xf7bd61eb in ?? () from /lib32/libc.so.6
(gdb) bt
#0  0xf7bd61eb in ?? () from /lib32/libc.so.6
#1  0x0804cda2 in z_ztest_testargs_contains (suite_name=suite_name@entry=0x80553aa "TempTests", 
    test_name=test_name@entry=0x80553b4 "testTemp")
    at /home/gbmhunter/personal/zephyr-cpp-toolkit/external/zephyr/subsys/testsuite/ztest/src/ztest_posix.c:166
#2  0x0804ce22 in z_ztest_should_test_run (suite=0x80553aa "TempTests", test=0x80553b4 "testTemp")
    at /home/gbmhunter/personal/zephyr-cpp-toolkit/external/zephyr/subsys/testsuite/ztest/src/ztest_posix.c:193
#3  0x0804c6c3 in z_ztest_run_test_suite_ptr (
    suite=suite@entry=0x805c438 <z_ztest_test_node_TempTests>, case_iter=case_iter@entry=1, 
    param=param@entry=0x0, suite_iter=1, shuffle=<optimized out>)
    at /home/gbmhunter/personal/zephyr-cpp-toolkit/external/zephyr/subsys/testsuite/ztest/src/ztest.c:878
```

It looks like `z_ztest_testargs_contains()` is causing the issue, likely due to assumptions about the string format which are not correct.

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell
 gdb --args ./build/test/zephyr/zephyr.exe --test="TempTests"
run
bt
Thread 3 "main" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf70ffac0 (LWP 431681)]
0xf7bd61eb in ?? () from /lib32/libc.so.6
(gdb) bt
#0  0xf7bd61eb in ?? () from /lib32/libc.so.6
#1  0x0804cda2 in z_ztest_testargs_contains (suite_name=suite_name@entry=0x80553aa "TempTests", 
    test_name=test_name@entry=0x80553b4 "testTemp")
    at /home/gbmhunter/personal/zephyr-cpp-toolkit/external/zephyr/subsys/testsuite/ztest/src/ztest_posix.c:166
#2  0x0804ce22 in z_ztest_should_test_run (suite=0x80553aa "TempTests", test=0x80553b4 "testTemp")
    at /home/gbmhunter/personal/zephyr-cpp-toolkit/external/zephyr/subsys/testsuite/ztest/src/ztest_posix.c:193
#3  0x0804c6c3 in z_ztest_run_test_suite_ptr (
    suite=suite@entry=0x805c438 <z_ztest_test_node_TempTests>, case_iter=case_iter@entry=1, 
    param=param@entry=0x0, suite_iter=1, shuffle=<optimized out>)
    at /home/gbmhunter/personal/zephyr-cpp-toolkit/external/zephyr/subsys/testsuite/ztest/src/ztest.c:878
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS (WSL, Ubuntu in Windows host)
- Zephyr version: `77f865b8f8d0cb3d19002bfe713e9dd46e6f71b7 (HEAD, tag: v4.0.99-ncs1-1)`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nashif**
Instead of crashing fail with a message when -test arguments is of
wrong format.

Fixes zephyrproject-rtos/zephyr#91655

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by aaronemassey — DISMISSED** [review]

File: subsys/testsuite/ztest/src/ztest_posix.c [hunk 1]
```diff
@@ -161,10 +162,18 @@ static bool z_ztest_testargs_contains(const char *suite_name, const char *test_n
 		suite_arg = strtok_r(suite_test_pair, ":", &last_arg);
 		test_arg = strtok_r(NULL, ":", &last_arg);
 
+		/* Validate format: must be test_suite::* or test_suite::test_case */
+		if (!suite_arg || !test_arg || strtok_r(NULL, ":", &last_arg) != NULL) {
+			/* Invalid format, report error and exit */
+			suite_test_pair = strtok_r(NULL, ",", &last_suite_test_pair);
+			nsi_print_error_and_exit(
+				"Invalid test argument format: '%s'. Expected 'suite::test' or 'suite::*'.\n",
+				suite_test_pair);
```
Comment (aescolar) [inline subsys/testsuite/ztest/src/ztest_posix.c]: Aren't you jumping to the next `suite_test_pair` here?
Meaning, shouldn't this just be:
```suggestion
			nsi_print_error_and_exit(
				"Invalid test argument format: '%s'. Expected 'suite::test' or 'suite::*'.\n",
				suite_test_pair);
```
or even
```suggestion
			nsi_print_error_and_exit(
				"Invalid test argument format '%s'. Expected a set of pairs like"
				"'suite::test' or 'suite::*', got instead '%s'.\n",
				test_args, suite_test_pair);
```

**Review by aescolar — COMMENTED** [review]
Thanks @nashif, but note the error msg seems to be printing the next pair though
i.e.
```
$ zephyr/zephyr.exe -test=a::b,banana,c::d
*** Booting Zephyr OS build v4.1.0-6079-g7388432edf83 ***
Invalid test argument format: 'c::d'. Expected 'suite::test' or 'suite::*'.
```

**Review by aescolar — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by gbmhunter** [comment]
Thanks for fixing this @nashif !
