### PR TITLE
tests: fix these tests when using EFI console output function as default

### LINKED ISSUE #45929: up_squared：failed to run test case tests/posix/common
**Describe the bug**
The test block on test_posix_rw_lock test case.

**To Reproduce**
1. source zephyr-env.sh
2. twister -p up_squared --device-testing --device-serial $serial_name -T tests/posix/common/ --west-flash=$HOME/$USER/up_squared_efi.sh -vv
3. See error
  or
  2. west build -p always -b up_squared tests/posix/common/
  3. screen /dev/ttyUP2 115200
  4. west flash $HOME/$USER/up_squared_efi.sh
  5. See error

**Expected behavior**
Test case should pass as expected.

**Impact**
The test case tests/posix/common seems to block.

**Logs and console output**
```
Running TESTSUITE posix_apis
===================================================================
START - test_posix_pthread_execution
Thread 0 starting with scheduling policy 0 & priority 15
Thread 1 starting with scheduling policy 0 & priority 15
Thread 2 starting with scheduling policy 0 & priority 15
Bounce test OK
Barrier test OK
 PASS - test_posix_pthread_execution in 0.521 seconds
===================================================================
START - test_posix_pthread_error_condition
 PASS - test_posix_pthread_error_condition in 0.1 seconds
===================================================================
START - test_posix_pthread_termination
Thread 0 starting with a priority of 4
Cancelling thread 0
Thread 1 starting with a priority of 3
Cancelling thread 1
Thread 1 could not be cancelled
Thread 2 starting with a priority of 2
Cancelling thread 2
Thread 3 starting with a priority of 1
Cancelling thread 3
Thread 3 could not be cancelled
 PASS - test_posix_pthread_termination in 1.16 seconds
===================================================================
START - test_posix_multiple_threads_single_key

Different threads set different values to same key:
thread 0: set value = 6210288 and retrieved value = 6210288
thread 1: set value = 6210736 and retrieved value = 6210736

 PASS - test_posix_multiple_threads_single_key in 0.18 seconds
===================================================================
START - test_posix_single_thread_multiple_keys

Single thread associates its value with different keys:
key 0: set value = 6211136 and retrieved value = 6211136
key 1: set value = 6211136 and retrieved value = 6211136

 PASS - test_posix_single_thread_multiple_keys in 0.18 seconds
===================================================================
START - test_posix_thread_attr_stacksize
 PASS - test_posix_thread_attr_stacksize in 0.1 seconds
===================================================================
START - test_posix_clock
POSIX clock APIs
POSIX clock APIs test done
 PASS - test_posix_clock in 2.5 seconds
===================================================================
START - test_posix_semaphore
 PASS - test_posix_semaphore in 2.305 seconds
===================================================================
START - test_posix_normal_mutex
mutex lock is taken
 PASS - test_posix_normal_mutex in 0.203 seconds
===================================================================
START - test_posix_recursive_mutex
recursive mutex lock is taken
 PASS - test_posix_recursive_mutex in 0.4 seconds
===================================================================
START - test_posix_mqueue
 PASS - test_posix_mqueue in 0.11 seconds
===================================================================
START - test_posix_realtime
 PASS - test_posix_realtime in 1.802 seconds
===================================================================
START - test_posix_timer
POSIX timer test
Timer fires every 0 secs and  100000000 nsecs
Time remaining to fire 0 secs and  899000000 nsecs
Handler Signal value :20 for 1 times
Handler Signal value :20 for 2 times
Handler Signal value :20 for 3 times
Handler Signal value :20 for 4 times
Handler Signal value :20 for 5 times
Handler Signal value :20 for 6 times
Handler Signal value :20 for 7 times
Handler Signal value :20 for 8 times
Handler Signal value :20 for 9 times
Handler Signal value :20 for 10 times
Handler Signal value :20 for 11 times
Handler Signal value :20 for 12 times
 PASS - test_posix_timer in 2.112 seconds
===================================================================
START - test_posix_rw_lock

main acquire WR lock and 3 threads acquire RD lock
Thread 2 sc
```

**Environment :**
OS: Linux,
Toolchain Zephyr SDK 0.14.1
Commit SHA or Version: 4cc5c56d8c4a4727bcfb6a49cdc2d6ffba39295f

### PR DESCRIPTION
**Pull request by enjiamai**
This PR try to fix some testcases when applying the UEFI console as default output （with UART_CONSOLE disable)

Category 1: Implemented the simplest driver to support EFI console:
- Add a minimal EFI console driver to support printf, fix following tests: 
tests/benchmarks/sys_kernel/ 
samples/application_development/external_lib/  
samples/posix/eventfd/
samples/userspace/hello_world_user/

- Implement a logging backend EFI console to fix following tests:  
samples/subsys/logging/syst
tests/subsys/logging/log_core_additional/
samples/subsys/logging/logger/

Category 2:  And there is a firmware bug that EFI console output call return with interrupt enabled. Though
there is a interrupt disabled solution that disable the interrupt right after EFI call, in some case
it the interrupt could happen during the EFI call context. If an interrupt was handled, a printk
call again will make it re-entries, or a swap might be happens.

- Not do prink in the interrupt context, and lock the scheduler during the EFI call.
samples/philosophers/
tests/kernel/interrupt/
tests/kernel/semaphore/sys_sem/
samples/kernel/metairq_dispatch/

- No tracing during switch in/out when using EFI console:
samples/subsys/tracing/

Fixes: #45929

### CODE REVIEW

File: drivers/console/efi_console.c [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+ * Hooks into the printk and fputc (for printf) modules.
+ */
+
+#include <stdio.h>
+#include <zephyr/device.h>
+#include <zephyr/init.h>
+#include <zephyr/sys/printk.h>
+
+
+#ifndef CONFIG_UART_CONSOLE
```
Comment (andyross) [inline drivers/console/efi_console.c:21]: If you're putting an entire file under an #if, it's best to just filter it out of the build using cmake instead.

**Review by andyross — DISMISSED** [review]
One nitpick, seems very reasonable.

File: subsys/tracing/user/tracing_user.c [hunk 2]
```diff
@@ -19,24 +19,30 @@ void __weak sys_trace_idle_user(void) {}
 
 void sys_trace_k_thread_switched_in(void)
 {
+/* FIXME: Limitation of the current x86 EFI cosnole implementation. */
+#if !defined(CONFIG_X86_EFI_CONSOLE) && !defined(CONFIG_UART_CONSOLE)
+
```
Comment (cfriedt) [inline subsys/tracing/user/tracing_user.c:24]: I wonder if it might be more appropriate to use `IS_ENABLED()` here as well as in the function below.

File: subsys/logging/Kconfig [hunk 3]
```diff
@@ -4,6 +4,7 @@
 menuconfig LOG
 	bool "Logging"
 	select PRINTK if USERSPACE
+	select UART_CONSOLE if X86_64
```
Comment (cfriedt) [inline subsys/logging/Kconfig:7]: There may be some use cases where it makes sense to not use this option.

File: lib/libc/Kconfig [hunk 4]
```diff
@@ -221,7 +221,7 @@ endif # MINIMAL_LIBC
 
 config STDOUT_CONSOLE
 	bool "Send stdout to console"
-	depends on CONSOLE_HAS_DRIVER
+	depends on CONSOLE_HAS_DRIVER || X86_EFI_CONSOLE
```
Comment (cfriedt) [inline lib/libc/Kconfig:224]: Seems like it would be better to select `CONSOLE_HAS_DRIVER` when `X86_EFI_CONSOLE` is chosen.

File: drivers/console/efi_console.c [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+
+#include <stdio.h>
+#include <zephyr/device.h>
+#include <zephyr/init.h>
+#include <zephyr/sys/printk.h>
+
+
+extern int efi_console_putchar(int c);
+
+#if defined(CONFIG_PRINTK) || defined(CONFIG_STDOUT_CONSOLE)
```
Comment (cfriedt) [inline drivers/console/efi_console.c:23]: I would suggest using
```cpp
if (IS_ENABLED(CONFIG_PRINTK) || defined(CONFIG_STDOUT_CONSOLE)
```
not 100% sure if this should be necessary though - is the conditional compile for `CONFIG_X86_EFI_CONSOLE` sufficient?

File: subsys/tracing/user/tracing_user.c (hunk 2 above)
Comment (enjiamai) [reply subsys/tracing/user/tracing_user.c:59]: I think IS_ENABLED() is not target for this scenario, most use in the "if( IS_ENABLE(CONFIG_xxx))" code, thanks.

File: subsys/logging/Kconfig (hunk 3 above)
Comment (enjiamai) [reply subsys/logging/Kconfig:7]: Good point, I am still trying narrow this down.

File: lib/libc/Kconfig (hunk 4 above)
Comment (enjiamai) [reply lib/libc/Kconfig]: Yes, you are right. And I found the problem, we don't need this anymore. Thanks for pointing this out!

File: drivers/console/efi_console.c (hunk 5 above)
Comment (enjiamai) [reply drivers/console/efi_console.c:23]: Same as the top comment about IS_ENABLED macro. Thanks for your review.

**Comment by enjiamai** [comment]
Hi @cfriedt , sorry for the late reply and think you very much for the review, could you please see my comments, thanks! :)

**Comment by enjiamai** [comment]
Not passing the CI due to:
```
549/644 mps2_an385   tests/net/tcp/net.tcp.no_recv_queue   FAILED Failed (qemu 4.528s)
```

File: subsys/logging/Kconfig (hunk 3 above)
Comment (enjiamai) [reply subsys/logging/Kconfig]: Got this fixed, thanks.

**Comment by enjiamai** [comment]
Hi @andyross and dear all, I made a workaround solution for the EFI console with interrupt enabled problem, (https://github.com/zephyrproject-rtos/zephyr/pull/46918/commits/2bb56b792dd368db3206722c62f9ad3cdbe8ed5e).  Could you please give some suggestion or correct me if I am wrong, thank you!

And I also made a simplest t console driver and logging backend for EFI console. @cfriedt  :)

**Review by cfriedt — DISMISSED** [review]
LGTM

File: subsys/logging/log_backend_efi_console.c [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <zephyr/logging/log_backend.h>
+#include <zephyr/logging/log_core.h>
+#include <zephyr/logging/log_output.h>
+#include <zephyr/logging/log_backend_std.h>
+#include <zephyr/logging/log.h>
+
+LOG_MODULE_REGISTER(log_efi);
```
Comment (andyross) [inline subsys/logging/log_backend_efi_console.c:13]: Not related to this PR, but I continue to be a little distressed at how much boilerplate is required for a log backend.

**Review by andyross — DISMISSED** [review]
Looks great to me.

File: subsys/logging/log_backend_efi_console.c (hunk 6 above)
Comment (enjiamai) [reply subsys/logging/log_backend_efi_console.c:11]: Reduced the unnecessary include file. Thanks.

**Comment by enjiamai** [comment]
Excuse me @andyross , @cfriedt , could you please help to re-approve / review again? thank you!

**Review by cfriedt — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
