### PR TITLE
net: lwm2m: Ensure string termination

### LINKED ISSUE #59196: LwM2M engine does not ensure NULL terminated strings
**LwM2M engine is inconsistent on handling strings**

When storing strings, using for example `lwm2m_set_string(path, "Hello");` only `strlen("Hello");` is set as a data size in the registry. When reading, there are few corner cases where data might end up coming out without NULL-terminator.

For example when reading exactly strlen characters, or less:
```c
char buf[] = "Hello World!";

/* Store only "Hello" */
lwm2m_set_string(&path, "Hello");

/* Request only strlen characters */
lwm2m_get_string(&path, buf, strlen("hello"));

/* Will output "Hello World!" as the read did not terminate the string */
printk("Buffer content: %.*s\n", sizeof(buf), buf);
```

Similarly, sometimes `lwm2m_get_res_buf()`  might be used to get content of the string buffer, without copying. This is dangerous as there might not be NUL terminator included.
```c
char *p;
uint16_t len;

/* Get pointer to internal buffer */
lwm2m_get_res_buf(&path, (void **)&p, NULL, &len, NULL);

/* Verify that it is NUL terminated string */
if (p[len - 1] == 0)  /* false */

if (p[len] == 0) /* True, but this is past the data length */
```

**To Reproduce**
1. See examples above

**Expected behavior**
When string data is stored into internal buffers, we must ensure that there is terminating character included (I believe this is already done in `lwm2m_set()`.
We should probably change the `struct lwm2m_engine_res_inst::data_len` to contain the terminating character, or document properly that is is missing from the length. Now dealing with opaque or string data requires extra effort.

**Impact**
Unsafe code when LwM2M engine and string data is handled.

### PR DESCRIPTION
**Pull request by SeppoTakalo**
When writing string data to resources which are string types, we should count in the terminating character into the data length.

Corner cases exist where LwM2M resource type is opaque but lwm2m_get_string() or lwm2m_set_string() are used to read/write the data. We must ensure string termination on those case, but terminating character must not be stored in the engine buffer or counted in the data length as this might be considered as part of the binary data.

Fixes #59196

### CODE REVIEW

File: subsys/net/lib/lwm2m/lwm2m_registry.c [hunk 1]
```diff
@@ -1229,12 +1246,18 @@ int lwm2m_engine_get_opaque(const char *pathstr, void *buf, uint16_t buflen)
...
 }
 
-int lwm2m_get_string(const struct lwm2m_obj_path *path, void *str, uint16_t strlen)
+int lwm2m_get_string(const struct lwm2m_obj_path *path, void *str, uint16_t buflen)
 {
-	return lwm2m_engine_get(path, str, strlen);
+	/* Ensure termination, in case resource is not a string type */
+	if (!is_string(path)) {
+		memset(str, 0, buflen);
+		buflen -= 1; /* Last teminator cannot be overwritten */
```
Comment (rlubos) [inline subsys/net/lib/lwm2m/lwm2m_registry.c:1254]:
```suggestion
		buflen -= 1; /* Last terminator cannot be overwritten */
```

**Review by rlubos — COMMENTED** [review]
Looks good, just one nit.

File: subsys/net/lib/lwm2m/lwm2m_registry.c (hunk 1 above)
Comment (SeppoTakalo) [reply subsys/net/lib/lwm2m/lwm2m_registry.c]: Fixed.

**Comment by SeppoTakalo** [comment]
Fixed the remarks and rebased.

**Review by carlescufi — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
