### PR TITLE
BAP broadcast assistant bsim test fix

### LINKED ISSUE #64195: BT: tests/bsim/bluetooth/audio/test_scripts/bap_broadcast_audio_assistant broken in main
**Describe the bug**
The BT Audio test 
tests/bsim/bluetooth/audio/test_scripts/bap_broadcast_audio_assistant
is broken in main, on an nrf52_bsim. It blocks CI.

**To Reproduce**
1. WORK_DIR=${ZEPHYR_BASE}/bsim_out  nice tests/bsim/bluetooth/audio/compile.sh 
2. tests/bsim/bluetooth/audio/test_scripts/bap_broadcast_audio_assistant
3. See error

**Expected behavior**
Passing testcase

**Impact**
Main development blocked when this test is triggered

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/6588609341/job/17901270642?pr=63803#step:12:137

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 22.04 / CI
 - Toolchain (e.g Zephyr SDK, ...): Host gcc (11 or 12)
 - Commit SHA or Version used: Main as of now 02deea0e806a40a33eb70edf4b810221c14a0cad

**Additional context**
The test was just introduced in https://github.com/zephyrproject-rtos/zephyr/commit/0e67c990cdb7ae4e4c90a474e7dc478c44a7d494

### PR DESCRIPTION
**Pull request by Thalley**
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/64195

### CODE REVIEW

File: tests/bsim/bluetooth/audio/src/common.c [hunk 1]
```diff
@@ -135,3 +140,181 @@ void test_init(void)
 	bst_ticker_set_next_tick_absolute(WAIT_TIME);
 	bst_result = In_progress;
 }
+
+#define SYNC_MSG_SIZE 1
+static int32_t dev_cnt;
+static uint backchannel_nums[255];
+static uint chan_cnt;
+static void register_more_cmd_args(void)
```
Comment (MariuszSkamra) [inline tests/bsim/bluetooth/audio/src/common.c:148]: missing empty line in between

File: tests/bsim/bluetooth/audio/src/common.c [hunk 2]
```diff
@@ -135,3 +140,181 @@ void test_init(void)
...
+		channel_id = (dev << 16) | self;
+	} else {
+		channel_id = (self << 16) | dev;
+	}
+
+	return channel_id;
+}
+
+/**
+ * @brief Set the up backchannels between each pair of device
```
Comment (MariuszSkamra) [inline tests/bsim/bluetooth/audio/src/common.c:190]: Set up the ...

File: tests/bsim/bluetooth/audio/src/common.c [hunk 3]
```diff
@@ -135,3 +140,181 @@ void test_init(void)
...
+		if (i != self) { /* skip ourselves*/
+			backchannel_nums[chan_cnt] = get_chan_num((uint16_t)i);
+			device_numbers[chan_cnt++] = i;
+		}
+	}
+
+	channels = bs_open_back_channel(self, device_numbers, backchannel_nums, chan_cnt);
+	__ASSERT_NO_MSG(channels != NULL);
+}
+NATIVE_TASK(setup_backchannels, PRE_BOOT_3, 100);
```
Comment (MariuszSkamra) [inline tests/bsim/bluetooth/audio/src/common.c:211]: Wouldn't it make sense to factor out this piece of code from `tests/bsim/bluetooth/host/att/long_read/testlib/bs_sync.c` instead of duplicating the code? Applies to `register_more_cmd_args` as well

**Review by MariuszSkamra — CHANGES_REQUESTED** [review]

File: tests/bsim/bluetooth/audio/src/common.c (hunk 3 above)
Comment (Thalley) [reply tests/bsim/bluetooth/audio/src/common.c:211]: This code is similar, but not identical. 

The code in `tests/bsim/bluetooth/host/att/long_read/testlib/bs_sync.c` sets up a single channel for all devices, where this sets up a channel per pair of devices. 

So for 3 devices, this sets up
Channel between dev 0 and dev 1
Channel between dev 0 and dev 2
Channel between dev 1 and dev 2

Comment (Thalley) [reply tests/bsim/bluetooth/audio/src/common.c:212]: Besides that, we have no current way of sharing code between BSIM tests - Currently they are considered separate, and something like this would be probably be placed in a common framework at some point.

**Review by MariuszSkamra — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
