### PR TITLE
Bluetooth: host: Wait for callback before clearing SC data

### LINKED ISSUE #40761: Bluetooth: host: Wait for the response callback before clearing Service Changed data
**Describe the bug**
We should wait for Service Changed indication confirmation before we clear data marking that indication should be sent to a given client. In worst scenario it's better to send the indication twice than not to send it at all (inconsistency of GATT information cached by client and GATT services provided by server could lead to strange issues).

**Expected behavior**
GATT Server should wait for Service Changed indication confirmation to ensure that it is received by the GATT Client.

**Impact**
If the GATT Client e.g. disconnects before the Service Changed Indication is confirmed, the indication may never be received by the Client.

### PR DESCRIPTION
**Pull request by MarekPieta**
The GATT Server should wait with clearing Service Changed indication configuration data until the response callback is called. Otherwise the indication may not be properly delivered to a given GATT Client.

Fixes: #40761

### CODE REVIEW

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -2482,11 +2482,22 @@ static void sc_restore_rsp(struct bt_conn *conn,
 	 * The client receives and confirms a Service Changed indication.
 	 */
 	cfg = find_cf_cfg(conn);
+
```
Comment (jhedberg) [inline subsys/bluetooth/host/gatt.c:2485]: Seems like an unrelated change? The general style in this subsystem is not to have an empty line between assignment to a variable and testing the variable’s value.

Comment (MarekPieta) [reply subsys/bluetooth/host/gatt.c]: Fixed

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
