### PR TITLE
drivers: stepper: step_dir: fix 87698

### LINKED ISSUE #87698: drivers:stepper Step-Dir Pin toggle Frequency to High
**Describe the bug**

The current step-dir implementation in `step_dir_stepper_common` toggles in single_edge mode the step pin twice as fast as it can. For some board and stepper controller combinations (for example Teensy 4.0 board with a TI drv8424 stepper controller) this causes the pin to be toggled to fast and thus erroneous behavior - e.g. the motor not stepping.

**To Reproduce**

1. Connect a `drv8424` stepper controller with a `Teensy 4.0` board and use the counter timing source (didn't test work queue timing)
2. Test the driver via the shell, using microstep resolution of `1` and a microstep interval of `5000000` - i.e. 200 steps/s
3. Observe the motor

**Expected behavior**

The motor should step correctly.

**Possible solutions**

One possible solution is to use a 50% duty cycle of the step signal - like the drv8424 driver before the step-dir generalization. This requires an internal doubling of the step signal frequency and step counting only on every second interrupt. In addition, the step signal needs to be explicitly set to low when stopping, possibly after a short delay after stopping the timing source. 
These changes are only needed for single_edge mode. dual_step mode can remain like it is.

That said, this is only one possible solution and I am interested if there are other ideas on how to solve this.

### PR DESCRIPTION
**Pull request by jilaypandya**
During testing with teensy 4.0 it was discoverd that toggling at high frequencies led to missed steps. 
As per the datasheets of step-dir drivers, an active edge needs to be maintained for a certain time period, for a step to be executed.

### CODE REVIEW

File: drivers/stepper/step_dir/step_dir_stepper_common.c [hunk 1]
```diff
@@ -8,9 +8,19 @@
 #include <zephyr/logging/log.h>
 LOG_MODULE_REGISTER(step_dir_stepper, CONFIG_STEPPER_LOG_LEVEL);
 
+static inline void step_pulse_timer_expiry_fn(struct k_timer *timer)
+{
+	struct step_dir_stepper_common_data *data =
+		CONTAINER_OF(timer, struct step_dir_stepper_common_data, step_pulse_timer);
+	const struct step_dir_stepper_common_config *config = data->dev->config;
+
+	gpio_pin_set_dt(&config->step_pin, 0);
```
Comment (dipakgmx) [inline drivers/stepper/step_dir/step_dir_stepper_common.c]: Not sure about setting the pin within a timer callback, since this is in ISR context. Could using a delayable work not be an option?

Comment (faxe1008) [inline drivers/stepper/step_dir/step_dir_stepper_common.c]: I'd use 'gpio_pin_toggle_dt` instead here.

File: dts/bindings/stepper/step-dir-timing.yaml [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+description: Step/Dir Control Signal Timing
+
+properties:
+  step-width-ns:
+    type: int
+    required: true
+    description: |
+      Total pulse width in nanoseconds for the step signal.
+      This is the total duration for which the step signal is asserted high and low.
```
Comment (faxe1008) [inline dts/bindings/stepper/step-dir-timing.yaml]: Not sure if the description is correct, this is what the timer effectively does:
image

File: drivers/stepper/step_dir/step_dir_stepper_common.c (hunk 1 above)
Comment (jilaypandya) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: with the counter approach, the `stepper_handle_timing_signal` is also getting called in ISR context. Would adding a task to a dedicated [workq](https://docs.zephyrproject.org/latest/kernel/services/threads/workqueue.html#how-to-use-workqueues) from the `stepper_handle_timing_signal` be the correct approach?

File: dts/bindings/stepper/step-dir-timing.yaml (hunk 2 above)
Comment (jilaypandya) [reply dts/bindings/stepper/step-dir-timing.yaml]: i'll adjust the description :)

File: drivers/stepper/step_dir/step_dir_stepper_common.c (hunk 1 above)
Comment (jilaypandya) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: This fn gets called only when `!config->dual_edge_step`.  I think it's okay to explicitly set the logic level to zero. Can we maybe use https://docs.zephyrproject.org/latest/doxygen/html/group__gpio__interface.html#gae28f0fa2576530083aa86d819d0d5cca in order to explicitly set the physical levels of the step_pin?

File: dts/bindings/stepper/step-dir-timing.yaml [hunk 3]
```diff
@@ -0,0 +1,12 @@
+# SPDX-FileCopyrightText: Copyright (c) 2025 Jilay Sandeep Pandya
+# SPDX-License-Identifier: Apache-2.0
+
+description: Step/Dir Control Signal Timing
+
+properties:
+  step-width-ns:
+    type: int
+    required: true
```
Comment (jbehrensnx) [inline dts/bindings/stepper/step-dir-timing.yaml]: I would have each stepper driver set a default value (e.g. 970 ns for the drv84xx series) and remove the required flag. The user should not need to know this value for basic usage. In addition, in the vast majority of use-cases, the value would not be changed from the driver specific value anyway.

That said, this should still be user configurable, as it is a speed limiter. It would be a good idea to mention this fact in the commit message and this PR, as it is a useful functional extension of the stepper api.

As a consequence of this, allowing the user to change this value in software might be a good idea, but that could be considered beyond the scope of this PR.

File: drivers/stepper/step_dir/step_dir_stepper_common.c [hunk 4]
```diff
@@ -265,6 +271,11 @@ int step_dir_stepper_common_set_microstep_interval(const struct device *dev,
 		return -EINVAL;
 	}
 
+	if (microstep_interval_ns < 2 * data->step_width_ns) {
```
Comment (jbehrensnx) [inline drivers/stepper/step_dir/step_dir_stepper_common.c]: Adjust, so that the check for dual-edge-mode is `microstep_interval_ns < data->step_width_ns` .

File: drivers/stepper/step_dir/step_dir_stepper_common.c (hunk 1 above)
Comment (jbehrensnx) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: I did some tests on a Nucleo WB55RG. The `k_timer` does not offer sufficient accuracy, at least when using a counter timing source. As a result, the delay function needs to use the same timing source as the main step function.

A toggling bool to check for pin high or pin low in combination with a if check in `stepper_handle_timing_signal` for setting the pin to low might work for this.

The delays from using a workqueue are as bad as using a `k_timer`. As a result, the gpio functions need to be called in an ISR context, despite the issues from doing this.

EDIT: To (hopefully) clarify my proposed solution for `!config->dual_edge_step`:
The timing source runs at half the step period (double the speed). A bool (or int) is used to alternate between 2 modes: the first mode toggles/sets to high the step pin and updates the position, while the second mode sets the step pin to low and stops the stepper if required.
However, there remains an issue with stopping a stepper before the min step delay has passed. The easiest solution would be for the `stop` function (and `move_by(0)`) to wait for the delay-time after the timing source is stopped to set the step-pin to low. If there are issues with calling a wait in these functions

**Review by jbehrensnx — CHANGES_REQUESTED** [review]

File: drivers/stepper/step_dir/step_dir_stepper_common.c (hunk 1 above)
Comment (faxe1008) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: @jbehrensnx 
+1 on the idea to simply half the step period and account for the delay-time when stopping.

**Comment by jilaypandya** [comment]
Ran 10 steps with 10ms microstep_interval

Without dual-edge-step:
image

With dual-edge-step:
image

File: drivers/stepper/step_dir/step_dir_stepper_common.h [hunk 5]
```diff
@@ -100,6 +101,7 @@ struct step_dir_stepper_common_data {
 #define STEP_DIR_STEPPER_DT_COMMON_DATA_INIT(node_id)                                              \
 	{                                                                                          \
 		.dev = DEVICE_DT_GET(node_id),                                                     \
+		.step_width_ns = DT_PROP(node_id, step_width_ns),                                  \
```
Comment (dipakgmx) [inline drivers/stepper/step_dir/step_dir_stepper_common.h]: Since this is constant, cant this be moved into the driver config?

**Review by mbolivar — DISMISSED** [review]
+1 is only for the bindings

File: drivers/stepper/step_dir/step_dir_stepper_common.h [hunk 6]
```diff
@@ -78,7 +80,7 @@ struct step_dir_stepper_common_data {
 	void *event_cb_user_data;
 
 	struct k_work_delayable stepper_dwork;
-
+	bool step_completed;
```
Comment (dipakgmx) [inline drivers/stepper/step_dir/step_dir_stepper_common.h]: This too needs to be an atomic variable

File: drivers/stepper/step_dir/step_dir_stepper_common.c [hunk 7]
```diff
@@ -335,8 +341,11 @@ int step_dir_stepper_common_run(const struct device *dev, const enum stepper_dir
 int step_dir_stepper_common_stop(const struct device *dev)
 {
 	const struct step_dir_stepper_common_config *config = dev->config;
+	struct step_dir_stepper_common_data *data = dev->data;
 	int ret;
 
+	k_sleep(K_NSEC(config->step_width_ns));
```
Comment (dipakgmx) [inline drivers/stepper/step_dir/step_dir_stepper_common.c]: If am not wrong, this is the user facing API. Any reason to wait here 20ns?

Comment (jilaypandya) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: > [faxe1008](https://github.com/faxe1008) [2 days ago](https://github.com/zephyrproject-rtos/zephyr/pull/95625#discussion_r2372119420)
@jbehrensnx
+1 on the idea to simply half the step period and account for the delay-time when stopping.

I have used k_sleep to introduce delay as of now as a placeholder, as a point for discussion.

## Rationale for this delay:
we have two kinds of step-dir drivers: 
1. tmc2209 - dual-edge-step (assuming for now that this is enabled)
    Upon Stop: no need to toggle step-pin
2. drv84xx - non-dual-edge-step
    Upon Stop: set step-pin to low (by toggling as of now)

Issue:
**stop is called before the minimum step width period has elapsed.**
1. tmc2209: a step will be actuated, since the step-pin maintains its level and at some point of time minimum step-width-ns will elapse, however, this step will not be recorded in the actual_position since timing_source_cb will not be called.
2. drv84xx: theoretically a step might not get actuated but this again depends on the tolerances of the driver and so on.

To circumvent the above mentioned issue, a delay is required so that:
1. last step will be actuated & recorded in actual position 
3. In case of drivers like drv84xx(non-dual-edge), step-pin is toggled to low.

File: drivers/stepper/step_dir/step_dir_stepper_common.h [hunk 8]
```diff
@@ -74,11 +77,12 @@ struct step_dir_stepper_common_data {
 	uint64_t microstep_interval_ns;
 	atomic_t actual_position;
 	atomic_t step_count;
+	atomic_t stop_stepper;
 	stepper_event_callback_t callback;
 	void *event_cb_user_data;
 
 	struct k_work_delayable stepper_dwork;
-
+	atomic_t step_completed;
```
Comment (dipakgmx) [inline drivers/stepper/step_dir/step_dir_stepper_common.h]: Nit: This could be further optimised by using a bit array.

```
enum {
	STEP_DIR_STEPPER_STEP_COMPLETED,
	STEP_DIR_STEPPER_STOPPED,
	...
	STEP_DIR_STEPPER_FLAG_NUM_FLAGS,
};

step_dir_stepper_common_data {
...
ATOMIC_DEFINE(flags, STEP_DIR_STEPPER_FLAG_NUM_FLAGS);
};

// Step complete for example
atomic_set_bit(dev->flags, STEP_DIR_STEPPER_STEP_COMPLETED);
```

File: drivers/stepper/step_dir/step_dir_stepper_common.c (hunk 7 above)
Comment (jilaypandya) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: I have reworked the stop function and removed the delay.

1. stop timing source.
2. trigger stop event.
3. toggle the step pin to low if required.

File: drivers/stepper/step_dir/step_dir_stepper_common.c [hunk 9]
```diff
@@ -159,13 +143,28 @@ static void velocity_mode_task(const struct device *dev)
...
 void stepper_handle_timing_signal(const struct device *dev)
 {
+	const struct step_dir_stepper_common_config *config = dev->config;
 	struct step_dir_stepper_common_data *data = dev->data;
+	int ret;
 
-	(void)step_dir_stepper_perform_step(dev);
-	if (data->direction == STEPPER_DIRECTION_POSITIVE) {
-		atomic_inc(&data->actual_position);
+	atomic_xor(&data->step_high, 1);
```
Comment (dipakgmx) [inline drivers/stepper/step_dir/step_dir_stepper_common.c]: Use `atomic_cas` here.

Comment (jilaypandya) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: Thanks. I have used atomic_cas in stepper_stop and reworked to xor and get operations in stepper_handle_timing_signal

File: dts/bindings/stepper/allegro/allegro,a4979.yaml [hunk 10]
```diff
@@ -25,8 +25,12 @@ compatible: "allegro,a4979"
 
 include:
   - name: stepper-controller.yaml
+  - name: step-dir-timing.yaml
 
 properties:
+  step-width-ns:
+    default: 1000
```
Comment (dipakgmx) [inline dts/bindings/stepper/allegro/allegro,a4979.yaml:32]:
```suggestion
    type: int
    default: 1000
```

**Review by dipakgmx — DISMISSED** [review]

**Review by faxe1008 — DISMISSED** [review]

**Comment by jilaypandya** [comment]
@jbehrensnx I think the requested changes have been addressed.

File: tests/drivers/stepper/stepper_api/Kconfig [hunk 11]
```diff
@@ -7,7 +7,7 @@ source "Kconfig.zephyr"
 
 config STEPPER_TEST_TIMING_TIMEOUT_TOLERANCE_PCT
 	int "Stepper timing tolerance percentage"
-	default 20
+	default 120
```
Comment (jbehrensnx) [inline tests/drivers/stepper/stepper_api/Kconfig]: Revert this. Only the work queue tests require the significantly increased tolerance, and theirs is set in the `testcase.yaml`

File: drivers/stepper/step_dir/step_dir_stepper_common.c [hunk 12]
```diff
@@ -335,15 +364,26 @@ int step_dir_stepper_common_run(const struct device *dev, const enum stepper_dir
...
+	struct step_dir_stepper_common_data *data = dev->data;
 	int ret;
 
 	ret = config->timing_source->stop(dev);
 	if (ret != 0) {
 		LOG_ERR("Failed to stop timing source: %d", ret);
 		return ret;
 	}
-
 	stepper_trigger_callback(dev, STEPPER_EVENT_STOPPED);
```
Comment (jbehrensnx) [inline drivers/stepper/step_dir/step_dir_stepper_common.c]: There needs to be a delay between stopping the timing source and triggering the callback of `step_width_ns` to ensure that the last step has been properly registered by the stepper. In addition, I would prefer, if the position is updated before the callback is triggered.

A `k_sleep` would be in my opinion sufficient for the required delay.
I am not sure, why you removed this delay, as it was there in a previous iteration (note that I didn't review said iteration, so I cant draw conclusions from context).

**Review by jbehrensnx — CHANGES_REQUESTED** [review]

File: tests/drivers/stepper/stepper_api/Kconfig (hunk 11 above)
Comment (jilaypandya) [reply tests/drivers/stepper/stepper_api/Kconfig]: fair enough

File: drivers/stepper/step_dir/step_dir_stepper_common.c (hunk 12 above)
Comment (jilaypandya) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: Triggering the callback after updating the position is a correct observation, thanks for that.

Putting an added wait using k_sleep, which most probably would not be even required in the first place is not a good idea, since the step-width-ns from my knowledge so far can range from 
1. 100ns (here you can safely assume that the step would have been executed) to
2.  few microseconds(there are edge cases possible where a step can be missed).

Again I would like to understand your use-case of stop function, because a stop expects the motor to be stopped asap and return the context for doing further actions.
One would want to stop the motor if an endstop is hit, but stopping the motor while it's in motion without properly ramping down can lead to some steps getting missed because of the inertia of drive attached to it. In addition, `get_actual_position` can not 100% gurantee for the missed steps. 

Please also have a look over here.
image

Comment (jbehrensnx) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: The use case is for the delay is indeed 2. The goal is to minimize missed steps. If the official statement is that `get_actual_position` doesn't guarantee the correct position in this case, then it does becomes easier and the delay is not necessary.

That said, in that case I would like it mentioned in the documentation in some form that `get_actual_position` can't make guarantees. If I missed that part somewhere, this is of course not necessary.

Comment (jilaypandya) [reply drivers/stepper/step_dir/step_dir_stepper_common.c]: Open Loop Systems cannot 100% guarantee the actual state. But yeah you are right, let's put this into documentation, to avoid confusion in the future.

File: include/zephyr/drivers/stepper.h [hunk 13]
```diff
@@ -354,7 +354,9 @@ static inline int z_impl_stepper_set_reference_position(const struct device *dev
 }
 
 /**
- * @brief Get the actual a.k.a reference position of the stepper
+ * @brief Get the actual step count for a given stepper.
+ * @details This function does not guarantee that the returned position is the exact current
+ * position. For precise positioning, encoders should be used in addition to the stepper driver.
```
Comment (jilaypandya) [inline include/zephyr/drivers/stepper.h:359]: @dipakgmx Could you revisit this part?

**Review by jbehrensnx — DISMISSED** [review]

File: include/zephyr/drivers/stepper.h (hunk 13 above)
Comment (dipakgmx) [reply include/zephyr/drivers/stepper.h:359]: Yeah, seem good. Would it be possible to change the `@details` to `@note`. I see the latter often.

Comment (jilaypandya) [reply include/zephyr/drivers/stepper.h:359]: done

**Review by dipakgmx — APPROVED** [review]

**Review by jbehrensnx — APPROVED** [review]

File: dts/bindings/stepper/allegro/allegro,a4979.yaml (hunk 10 above)
Comment (rruuaanng) [inline dts/bindings/stepper/allegro/allegro,a4979.yaml:32]: Please add a description of the default value.

File: dts/bindings/stepper/ti/ti,drv84xx.yaml [hunk 14]
```diff
@@ -31,8 +31,12 @@ compatible: "ti,drv84xx"
 
 include:
   - name: stepper-controller.yaml
+  - name: step-dir-timing.yaml
 
 properties:
+  step-width-ns:
+    default: 970
```
Comment (rruuaanng) [inline dts/bindings/stepper/ti/ti,drv84xx.yaml:38]: +1

File: dts/bindings/stepper/adi/adi,tmc2209.yaml [hunk 15]
```diff
@@ -19,8 +19,12 @@ compatible: "adi,tmc2209"
 
 include:
   - name: stepper-controller.yaml
+  - name: step-dir-timing.yaml
 
 properties:
+  step-width-ns:
+    default: 100
```
Comment (rruuaanng) [inline dts/bindings/stepper/adi/adi,tmc2209.yaml:26]: +1

File: dts/bindings/stepper/ti/ti,drv84xx.yaml (hunk 14 above)
Comment (dipakgmx) [reply dts/bindings/stepper/ti/ti,drv84xx.yaml:38]: Isn't this already described in the `step-dir-timing.yaml`?

**Review by faxe1008 — APPROVED** [review]
