### PR TITLE
tests: exception: riscv: run illegal instruction from text section

### LINKED ISSUE #49462: tests: tests/kernel/fatal/exception/ test case fail
**Describe the bug**
tests/kernel/fatal/exception/ failed in daily test.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? it8xxx2_evb
 - Is this a regression? Yes
   specific commit? 77e1e39cfff80c12ac3b0b1b802eee9e61ae79c4 
 - ...

**To Reproduce**
west build -p always -b it8xxx2_evb tests/kernel/fatal/exception/ -DCONFIG_STACK_SENTINEL=y -DCONFIG_TEST_HW_STACK_PROTECTION=n -DCONFIG_HW_STACK_PROTECTION=n -DCONFIG_ZTEST=y -DCONFIG_COVERAGE=n -DCONFIG_MP_NUM_CPUS=1 -DCONFIG_ZTEST_NEW_API=y
OR
twister  -p it8xxx2_evb --device-testing --west-flash="../../itetool/loader.sh" --device-serial=/dev/ttyUSB0 -T tests/kernel/fatal/exception/ -vv

**Expected behavior**
The test can pass

**Impact**
1 test case fail in daily test

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.1.0-3392-g77e1e39cfff8  (delayed boot 1ms) ***
Running TESTSUITE fatal_exception
===================================================================
START - test_fatal
test alt thread 1: generic CPU exception
E: Spurious interrupt detected! IRQ: 11
E: >>> ZEPHYR FATAL ERROR 1: Unhandled interrupt on CPU 0
E: Current thread: 0x80101048 (unknown)
Caught system error -- reason 1
Wrong crash type got 1 expected 0
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): Ubuntu20.04
 - Toolchain (e.g Zephyr SDK, ...) 0.14.1
 - Commit SHA or Version used: 77e1e39cfff80c12ac3b0b1b802eee9e61ae79c4

### PR DESCRIPTION
**Pull request by Dino-Li**
On the original implementation in entry_cpu_exception function,
an illegal instruction will be executed from RAM section to trigger
an exception.
Test result will fail on the SOC (eg. it81302) which executes code
in flash (text section).
This patch changes the test code to run illegal instruction from text
section.

fixes: #49462

Signed-off-by: Dino Li <Dino.Li@ite.com.tw>

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

File: tests/kernel/fatal/exception/src/main.c [hunk 1]
```diff
@@ -79,6 +79,9 @@ void entry_cpu_exception(void *p1, void *p2, void *p3)
 	__asm__ volatile ("trap");
 #elif defined(CONFIG_ARC)
 	__asm__ volatile ("swi");
+#elif defined(CONFIG_RISCV) && defined(CONFIG_XIP)
+	/* illegal instruction on RISCV */
+	__asm__ volatile (".long 0");
```
Comment (edersondisouza) [inline tests/kernel/fatal/exception/src/main.c:84]: It seems this is happily ignored by renode simulator for hifive1... maybe use another instruction, like `.word 0xffffffff` (like the `0x77777777` below)?
And I guess you then don't need the `CONFIG_XIP` check.

File: tests/kernel/fatal/exception/src/main.c [hunk 2]
```diff
@@ -79,6 +79,9 @@ void entry_cpu_exception(void *p1, void *p2, void *p3)
...
 #else
 	/* Triggers usage fault on ARM, illegal instruction on RISCV
```
Comment (edersondisouza) [inline tests/kernel/fatal/exception/src/main.c:86]: With no `CONFIG_XIP` check, then you need to update here to remove RISCV comment.

**Review by edersondisouza — CHANGES_REQUESTED** [review]
I also wonder if the overlap between `entry_cpu_exception` and `entry_cpu_exception_extend` doesn't warrant the complete exclusion of the first...

File: tests/kernel/fatal/exception/src/main.c (hunk 1 above)
Comment (Dino-Li) [reply tests/kernel/fatal/exception/src/main.c]: Done

File: tests/kernel/fatal/exception/src/main.c (hunk 2 above)
Comment (Dino-Li) [reply tests/kernel/fatal/exception/src/main.c]: Done

**Comment by Dino-Li** [comment]
> I also wonder if the overlap between `entry_cpu_exception` and `entry_cpu_exception_extend` doesn't warrant the complete exclusion of the first...

Please see comment in the commit.

**Comment by Dino-Li** [comment]
It seems that boards of hifive1 and m2gl025_miv are still not happy with this change.
Can't the ebreak instruction be used on those boards to raise exception?

**Comment by edersondisouza** [comment]
> It seems that boards of hifive1 and m2gl025_miv are still not happy with this change. Can't the ebreak instruction be used on those boards to raise exception?

Maybe they are expecting some debugger to take over - thus the timeout? I guess we have to stick to both tests simply using the same invalid instruction - that's already what happens on ARC, anyway.

**Comment by Dino-Li** [comment]
> > It seems that boards of hifive1 and m2gl025_miv are still not happy with this change. Can't the ebreak instruction be used on those boards to raise exception?
> 
> Maybe they are expecting some debugger to take over - thus the timeout? I guess we have to stick to both tests simply using the same invalid instruction - that's already what happens on ARC, anyway.

Done.

**Review by edersondisouza — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
