### PR TITLE
tests: gen_isr_table: Add barriers after triggering the irq

### LINKED ISSUE #9441: tests/kernel/gen_isr_table fails on mimxrt1050_evk
Tested on master commit 8cf8db3a73aa0658d728006e93d9ef5e0361a1b2, and tags v1.12.0, v1.11.0.
```
***** Booting Zephyr OS v1.12.0-1423-g8cf8db3 *****
starting test - Test gen_isr_tables
IRQ configuration (total lines 160):
isr1 isr=0x00000add irq=159
isr2 isr=0x00000b05 irq=158
Checking _irq_vector_table entry 159 for irq 159
triggering irq 159
isr1 ran
Checking _irq_vector_table entry 158 for irq 158
triggering irq 158
isr2 ran
interrupt 158 didn't run once, ran 1 times
FAIL - main
===================================================================
===================================================================
PROJECT EXECUTION FAILED
```

cc: @hakehuang

### PR DESCRIPTION
**Pull request by MaureenHelm**
Fixes the gen_isr_table kernel test on mimxrt1050_evk by using data and
instruction synchronization barriers instead of disabling compiler
optimization on arm platforms. According to [1] section 4.5, "if a
pended interrupt request needs to be recognized immediately after being
enabled in the NVIC, add a DSB instruction and then an ISB instruction"

[1] http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0321a/BIHJDAAE.html

Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

Fixes #9441

### CODE REVIEW

**Review by aurel32 — APPROVED** [review]
This patch makes sense, and fix the issue also on an STM32F7 board. This also shows that in the future we might need a barrier API, as I guess the issue might also affect other architectures at some point.

**Review by nashif — APPROVED** [review]

File: tests/kernel/gen_isr_table/src/main.c [hunk 1]
```diff
@@ -107,11 +108,16 @@ void isr4(void *param)
  * accesses to trigger_check around calls to trigger_irq.
  */
 __attribute__((optimize("-O0")))
```
Comment (hakehuang) [inline tests/kernel/gen_isr_table/src/main.c]: just afraid this may hide some issues. usually we can add instruction barrier  to the suspected code segment

**Comment by hakehuang** [comment]
check passed
