### PR TITLE
Le audio shell bis index

### LINKED ISSUE #70835: LE Audio: bap_broadcast_assistant add_pa_sync command igores BIS index parameter
**Describe the bug**
The `bap_broadcast_assistant add_pa_sync` command has optional parameters to set the BIS index that we want to remote side to sync to, but after setting it, it then parses the known BASE and override it with all the BIS indexes in the BASE. 

Ideally it would only use the BASE to verify the BIS indexes, so that the command can also be used to only tell the remote side to sync to PA without BIS. 

**To Reproduce**
N/A

**Expected behavior**
When calling `bap_broadcast_assistant add_pa_sync true 0x112233 0x02` it should only set the BIS index field to 0x02 and not to whatever is in the BASE. 

If setting e.g. `0x03` and the BASE only has a single BIS, then the command should be rejected. 

**Impact**
Minor

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 98aa10d6eab8df6938c0dc949bd12bc244bb52e1

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pin-zephyr**
When calling bap_broadcast_assistant add_pa_sync, it should only set the BIS index field as optional parameters and not to whatever is in the BASE.
    
If setting BIS index which the BASE does not support, then the command should be rejected.
    
This PR fixes https://github.com/zephyrproject-rtos/zephyr/issues/70835

### CODE REVIEW

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 1]
```diff
@@ -814,6 +815,16 @@ static inline bool add_pa_sync_base_subgroup_cb(const struct bt_bap_base_subgrou
...
 
+	/* use the BASE to verify the BIS indexes set by command */
+	if ((subgroup_param->bis_sync & bis_bitfield_req) != 0) {
+		subgroup_param->bis_sync = bis_bitfield_req;
+	} else if (bis_bitfield_req  != 0) {
+		shell_error(ctx_shell, "Cannot set BIS index 0x%06X when BASE only supports %d",
+			    bis_bitfield_req, subgroup_param->bis_sync);
+		/* command is rejected while not passing BASE verification */
+		return false;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:826]: I would move this check to `cmd_bap_broadcast_assistant_add_pa_sync` to keep it closer where it's used, and to avoid the global variable. 

The check is also not correct:
If `bis_bitfield_req` is `BIT(0) | BIT(1)` and `subgroup_param->bis_sync` only has `BIT(0)` then it passes the check, but attempts to sync to 2 BIS when the BASE only has a single

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 2]
```diff
@@ -869,7 +871,7 @@ static int cmd_bap_broadcast_assistant_add_pa_sync(const struct shell *sh,
 
 	param.broadcast_id = broadcast_id;
 
-	bis_bitfield_req = 0U;
+	uint32_t bis_bitfield_req = 0U;
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:874]: Please keep the declaration at it's original place. We generally always declare variables at top of scope

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 3]
```diff
@@ -900,6 +902,26 @@ static int cmd_bap_broadcast_assistant_add_pa_sync(const struct shell *sh,
 		}
 	}
 
+	/* use the BASE to verify the BIS indexes set by command */
+	for (size_t j = 0U; j < CONFIG_BT_BAP_BASS_MAX_SUBGROUPS; j++) {
+		if (bis_bitfield_req == 0) {
+			/* Not set the BIS indexes by command, use BASE directly */
+			break;
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:909]: That doesn't sound right. If the user does not want to sync to any BIS when issuing this command, we should respect that.

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 4]
```diff
@@ -900,6 +902,26 @@ static int cmd_bap_broadcast_assistant_add_pa_sync(const struct shell *sh,
...
+		} else if (subgroup_params[j].bis_sync == 0) {
+			/* The subgroup BIS index is not set, continue */
+			continue;
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:912]: Isn't this populated by the call to `bt_bap_base_foreach_subgroup`? Then it can never be 0

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 5]
```diff
@@ -900,6 +902,26 @@ static int cmd_bap_broadcast_assistant_add_pa_sync(const struct shell *sh,
...
+		} else if ((subgroup_params[j].bis_sync & bis_bitfield_req) != 0) {
+			subgroup_params[j].bis_sync = subgroup_params[j].bis_sync &
+						      bis_bitfield_req;
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:915]: I think this can be reduced to just
```suggestion
		subgroup_params[j].bis_sync &= bis_bitfield_req;
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c (hunk 3 above)
Comment (pin-zephyr) [reply subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:909]: in that case, subgroup_params from decoded BASE will be used directly

e.g  the command "bap_broadcast_assistant add_pa_sync true 0x0671C7"

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c (hunk 4 above)
Comment (pin-zephyr) [reply subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:913]: is there some restrictions on broadcast source to set subgroup's bis_sync to be 0 ?

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c (hunk 3 above)
Comment (Thalley) [reply subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:910]: Yeah but if I as a user do `bap_broadcast_assistant add_pa_sync true 0x0671C7 0x00` indicating that I do not want to sync to any BIS, then that's no longer possible, right?

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:913]: > is there some restrictions on broadcast source to set subgroup's bis_sync to be 0 ?

Yes, each subgroup has a least one BIS, and the BIS index cannot be 0.

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 6]
```diff
@@ -900,6 +903,22 @@ static int cmd_bap_broadcast_assistant_add_pa_sync(const struct shell *sh,
 		}
 	}
 
+	/* use the BASE to verify the BIS indexes set by command */
+	for (size_t j = 0U; j < param.num_subgroups; j++) {
+		if (bis_bitfield_req == 0) {
+			/* Not set the BIS indexes by command, use BASE directly */
+			break;
+		} else if ((subgroup_params[j].bis_sync & bis_bitfield_req) != 0) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:911]: For the `shell_error` below to make sense, we need to verify that the "sum" of the `bis_sync` contain at least all the bits in `bis_bitfield_req`.

For example if `bis_bitfield_req` has `BIT(0) | BIT(1) | BIT(2)` then this check won't return an error if the subgroups only have `BIT(0)` and `BIT(1)`. 

Unless we want to treat `bis_bitfield_req` as the "upper limit" rather than actual values.

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c (hunk 3 above)
Comment (pin-zephyr) [reply subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:910]: 0x00 is not valid index and not allowed to be used in shell command app, index should be within the range 0x01 and ox1F

Comment (Thalley) [reply subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:910]: My point is that a user should be able to use this command to only request a PA sync without BIS sync (which is indicated by the `bis_sync` value of 0)

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 7]
```diff
@@ -900,6 +903,23 @@ static int cmd_bap_broadcast_assistant_add_pa_sync(const struct shell *sh,
 		}
 	}
 
+	/* use the BASE to verify the BIS indexes set by command */
+	for (size_t j = 0U; j < param.num_subgroups; j++) {
+		if (bis_bitfield_req == 0) {
+			/* Request a PA sync without BIS sync */
+			subgroup_params[j].bis_sync = BT_BAP_BIS_SYNC_NO_PREF;
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:910]: `subgroup_params[j].bis_sync` should be `0`. `BT_BAP_BIS_SYNC_NO_PREF` indicated "No preference" and not "No sync"

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 8]
```diff
@@ -900,6 +903,23 @@ static int cmd_bap_broadcast_assistant_add_pa_sync(const struct shell *sh,
...
+		} else if ((subgroup_params[j].bis_sync & bis_bitfield_req) == bis_bitfield_req) {
+			/* bis_sync in BASE contains at least all the bits in bis_bitfield_req */
+			subgroup_params[j].bis_sync = bis_bitfield_req;
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:913]: If

`bis_bitfield_req` is `BIT(0) | BIT(1)` and `subgroup[0]` has `BIT(0)` and `subgroup[1]` has `BIT(1)` then the request is valid, but this check will fail because `BIT(0) & bis_bitfield_req) != bis_bitfield_req` when `bis_bitfield_req = BIT(0) | BIT(1)`.

The idea behind this check is valid, but you need to compare the total of all subgroup BIS indexes to `bis_bitfield_req`, and not the individual ones.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/shell/bap_broadcast_assistant.c [hunk 9]
```diff
@@ -900,6 +905,24 @@ static int cmd_bap_broadcast_assistant_add_pa_sync(const struct shell *sh,
...
 	}
 
+	/* use the BASE to verify the BIS indexes set by command */
+	for (size_t j = 0U; j < param.num_subgroups; j++) {
+		if (bis_bitfield_req == 0) {
+			/* Request a PA sync without BIS sync */
+			subgroup_params[j].bis_sync = 0;
+		} else {
+			subgroups_bis_sync |= subgroup_params[j].bis_sync;
+		}
```
Comment (Thalley) [inline subsys/bluetooth/audio/shell/bap_broadcast_assistant.c:915]: Isn't this missing? 

```suggestion
		} else {
			subgroups_bis_sync |= subgroup_params[j].bis_sync;
			subgroup_params[j].bis_sync &= bis_bitfield_req;
		}
```

Otherwise I don't see how else the `bis_bitfield_req` will affect the parameters

**Review by Thalley — CHANGES_REQUESTED** [review]

**Review by Thalley — APPROVED** [review]

**Review by larsgk — APPROVED** [review]
