### PR TITLE
net: connection: Unconditionally forward packets when handling packet sockets

### LINKED ISSUE #93245: net: connection: Packet sockets cause packets to drop
### Describe the bug

If `CONFIG_NET_SOCKETS_PACKET` is selected and a socket of type `AF_PACKET` and `SOCK_RAW` is open, then it consumes all packets without giving them a chances to be handled by `L2`. This includes all packets that should not be consumed in that why like `arp`, `icmp`, `lldp`, ... etc.

### Regression

- [ ] This is a regression.

### Steps to reproduce

(Seen based on code analysis).
Probably:
- `CONFIG_NET_SOCKETS_PACKET=y`
- open connection of type `AF_PACKET/SOCK_RAW`
- packets no longer reach handlers registered using `ETH_NET_L3_REGISTER` (`arp`, `lldp`, ...)

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

_No response_

### Additional Context

Fix is probably to unconditionally `NET_CONTINUE` packets at the time of inputting into connections of type `AF_PACKET`, `SOCK_RAW``, as the system can not know at that time if the packet is needed elsewhere.

### PR DESCRIPTION
**Pull request by ClaCodes**
When handling packets for inputing into raw-packet-sockets, unconditionally
forward them to upper layer, so that it can be handled by L2-handlers.

Based on: https://github.com/zephyrproject-rtos/zephyr/pull/93050
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/93245

### CODE REVIEW

File: subsys/net/ip/connection.c [hunk 1]
```diff
@@ -670,14 +670,6 @@ enum net_verdict net_conn_packet_input(struct net_pkt *pkt, uint16_t proto, enum
 			continue; /* wrong family */
 		}
 
-		if (conn->type == SOCK_DGRAM && type == SOCK_RAW) {
-			/* If DGRAM packet sockets are present, we shall continue
-			 * with this packet regardless the result.
-			 */
-			raw_pkt_continue = true;
-			continue; /* L2 not processed yet */
```
Comment (rlubos) [inline subsys/net/ip/connection.c:678]: I think we still need to `continue` here (skip this "connection") if the condition is satisfied? We don't want to report raw packets to datagram packet sockets.

File: subsys/net/ip/connection.c [hunk 2]
```diff
@@ -713,6 +705,11 @@ enum net_verdict net_conn_packet_input(struct net_pkt *pkt, uint16_t proto, enum
 
 	k_mutex_unlock(&conn_lock);
 
+	/* We shall continue with raw packets regardless the result. */
+	if (type == SOCK_RAW) {
+		raw_pkt_continue = true;
```
Comment (rlubos) [inline subsys/net/ip/connection.c]: To be honest, when working with packet sockets I found this `raw_pkt_continue` quite fishy and I'm tempted to suggest we should just get rid of it. It seems a bit odd that packet socket, which delivers packet clones anyway, makes a decission whether the net stack should proceed with packet processing or not, it seems quite error prone (as this example shows). 

Especially that with generalized L3 handling, it seems that the same issue will arise with packets delivered at the DGRA level. IMHO we should just return `NET_CONTINUE` here unconditionally and let the net stack decide how to proceed with the packet.

File: subsys/net/ip/connection.c (hunk 1 above)
Comment (ghost) [reply subsys/net/ip/connection.c:678]: Good catch.

File: subsys/net/ip/connection.c (hunk 2 above)
Comment (ghost) [reply subsys/net/ip/connection.c]: Fully agree.

Can we even make them return `void` instead of `NET_CONTINUE`?

Comment (rlubos) [reply subsys/net/ip/connection.c]: The API's internal so we could update the function signature too.

**Review by jukkar — CHANGES_REQUESTED** [review]
Setting -1 so that this is not merged accidentally. I am not able to do a proper review atm, but will return to this after returning from vacation.

File: subsys/net/l2/virtual/ipip/ipip.c [hunk 3]
```diff
@@ -374,7 +374,7 @@ static enum net_verdict interface_recv(struct net_if *iface,
 
 		net_pkt_cursor_restore(pkt, &hdr_start);
 
-		return net_ipv6_input(pkt, false);
+		return net_ipv6_input(pkt);
```
Comment (jukkar) [inline subsys/net/l2/virtual/ipip/ipip.c]: I think we should clear the loopback variable just in case before looping it back to ipv6. The pkt is the same one that we received in `net_ipv6_input()` so it might have the original value.

File: subsys/net/l2/virtual/ipip/ipip.c [hunk 4]
```diff
@@ -421,7 +421,7 @@ static enum net_verdict interface_recv(struct net_if *iface,
 
 		net_pkt_cursor_restore(pkt, &hdr_start);
 
-		return net_ipv4_input(pkt, false);
+		return net_ipv4_input(pkt);
```
Comment (jukkar) [inline subsys/net/l2/virtual/ipip/ipip.c]: ditto

**Comment by jukkar** [comment]
@ClaCodes I have some difficulty reviewing your PRs atm, I am seeing similar/same commits in various PRs which is super confusing. Could we decide to get for example this PR to shape and only after that concentrate to reviewing the other PRs?

**Comment by ClaCodes** [comment]
> @ClaCodes I have some difficulty reviewing your PRs atm, I am seeing similar/same commits in various PRs which is super confusing. Could we decide to get for example this PR to shape and only after that concentrate to reviewing the other PRs?

Thank you for the feedback. I actually got a bit confused myself. Yes, we can do it. I implemented your feedback.

Basically I have a stack of dependent changes, wich I wanted to have up for indiviual reviews. How should this be handled?

```
* C
* B
* A
* upstream/main
```
What I did:
- PR A->main
- PR B->main
- PR C->main

What should be done instead, if I believe, that `C` will be contentious but I hope for `A` and `B` to merge?

File: subsys/net/ip/connection.h [hunk 5]
```diff
@@ -191,10 +191,8 @@ int net_conn_update(struct net_conn_handle *handle,
  * @param proto LL protocol for the connection
  * @param type socket type
  *
- * @return NET_OK if the packet was consumed, NET_CONTINUE if the packet should
- * be processed further in the stack.
  */
-enum net_verdict net_conn_packet_input(struct net_pkt *pkt,
+void net_conn_packet_input(struct net_pkt *pkt,
 				       uint16_t proto,
 				       enum net_sock_type type);
```
Comment (rlubos) [inline subsys/net/ip/connection.h]: nit: Alignment

**Comment by jukkar** [comment]
> Basically I have a stack of dependent changes, wich I wanted to have up for indiviual reviews. How should this be handled?

This is a problem in github as it does not allow stacked PRs that depend on each other. For the features you are trying to implement here, lets go one by one so that we do not need to review same stuff in multiple PRs.

**Comment by jukkar** [comment]
@ClaCodes Sorry that this has been taking so long to review, lets try to speed things up. Could you update the code according to latest comments and rebase against latest upstream, then we can continue with the review.

**Comment by ClaCodes** [comment]
- fix nit
- rebase

**Comment by ClaCodes** [comment]
> @ClaCodes Sorry that this has been taking so long to review, lets try to speed things up. Could you update the code according to latest comments and rebase against latest upstream, then we can continue with the review.

@jukkar No problem, should be ready now.

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
