### PR TITLE
drivers: clock_control: siwx91x: Update QSPI clock source to INTF_PLL

### LINKED ISSUE #103391: QSPI external shared flash on the SiWx91x SoC is incorrectly clocked.
### Describe the bug

The QSPI external shared flash on SiWx91x SoC didn't run on the expected clock (INTPLL). It then run on the default clock which create bugs since the clock is too slow (40 Mhz instead of 80 Mhz).
Bug are multiple and variable since it's a shared flash with the network coprocessor (NWP).

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by smalae**
1. Update the QSPI clock source to INTF_PLL, doing this increases the QSPI peripheral clock from 40 MHz to 80 MHz. This improves flash access throughput and overall performance on siwx91x devices, as QSPI is used for external flash operations.
2. Fix DMA callback handling.
3. Reset FIFOs for NULL/short RX DMA transfers.
4. Use memfill for dummy SPI RX DMA transfers.
5. Reduce transfer duration scaling for test_spi_complete_multiple_timed test

### CODE REVIEW

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 1]
```diff
@@ -188,7 +188,7 @@ static int gspi_siwx91x_config(const struct device *dev, const struct spi_config
 }
 
 #ifdef CONFIG_SPI_SILABS_SIWX91X_GSPI_DMA
-static void gspi_siwx91x_dma_tx_callback(const struct device *dev, void *user_data,
+static void gspi_siwx91x_dma_callback(const struct device *dev, void *user_data,
 					 uint32_t channel, int status)
```
Comment (jhedberg) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: minor: please fix the alignment of the split line when the first line now becomes shorter

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 2]
```diff
@@ -347,6 +353,7 @@ static int gspi_siwx91x_prepare_dma_channel(const struct device *spi_dev,
 	struct gspi_siwx91x_data *data = spi_dev->data;
 	const uint8_t dfs = SPI_WORD_SIZE_GET(data->ctx.config->operation) / 8;
 	struct dma_block_config *desc;
+	uint8_t rx_null_buf = 0;
```
Comment (jhedberg) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: Why `uint8_t` instead of `bool`?

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 3]
```diff
@@ -433,6 +444,7 @@ static int gspi_siwx91x_transceive_dma(const struct device *dev, const struct sp
 	const struct device *dma_dev = data->dma_rx.dma_dev;
 	struct spi_context *ctx = &data->ctx;
 	size_t padded_transaction_size = gspi_siwx91x_longest_transfer_size(ctx);
+	uint8_t rx_null_buf = 0;
```
Comment (jhedberg) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: Same question

**Review by jhedberg — CHANGES_REQUESTED** [review]

File: drivers/clock_control/clock_control_silabs_siwx91x.c [hunk 4]
```diff
@@ -252,6 +257,10 @@ static int siwx91x_clock_init(const struct device *dev)
 	/* Use interface PLL at configured frequency as peripheral clock */
 	sl_si91x_clock_manager_set_pll_freq(INFT_PLL, INTF_PLL_FREQUENCY, PLL_REF_CLK_VAL_XTAL);
 
+	/* Increase QSPI clock speed to 80MHz from 40MHz */
+	RSI_CLK_QspiClkConfig(pCLK, QSPI_INTFPLLCLK, QSPI_SWALLO_DIS, QSPI_ODD_DIV_DIS,
+			      QSPI_DIV_FACTOR);
```
Comment (jerome-pouiller) [inline drivers/clock_control/clock_control_silabs_siwx91x.c]: `pCLK`, `QSPI_SWALLO_DIS`, `QSPI_ODD_DIV_DIS` and `QSPI_DIV_FACTOR` don't bring helpful information. They just add a level of indirection for the reader. Prefer:
```
    RSI_CLK_QspiClkConfig(M4CLK, QSPI_INTFPLLCLK, 0, 0, 1);
```

File: drivers/clock_control/clock_control_silabs_siwx91x.c [hunk 5]
```diff
@@ -252,6 +257,10 @@ static int siwx91x_clock_init(const struct device *dev)
 	/* Use interface PLL at configured frequency as peripheral clock */
 	sl_si91x_clock_manager_set_pll_freq(INFT_PLL, INTF_PLL_FREQUENCY, PLL_REF_CLK_VAL_XTAL);
 
+	/* Increase QSPI clock speed to 80MHz from 40MHz */
```
Comment (jerome-pouiller) [inline drivers/clock_control/clock_control_silabs_siwx91x.c]: If I understand right, the line below is mostly a clock source change (from XTAL to INTFPLL) rather than just a frequency configuration.

Not a big deal, but for atomicity, this commit should be placed at end (after the fixes that allow the clock migration).

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 6]
```diff
@@ -226,10 +227,15 @@ static int gspi_siwx91x_dma_config(const struct device *dev,
...
 		.dma_slot = channel->dma_slot,
-		.dma_callback = is_tx ? &gspi_siwx91x_dma_tx_callback : NULL,
 		.user_data = (void *)dev,
 	};
 
+	if ((rx_null_buf && is_tx) || (!is_tx && !rx_null_buf)) {
+		cfg.dma_callback = &gspi_siwx91x_dma_callback;
+	} else {
+		cfg.dma_callback = NULL;
+	}
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c:249]: `else` part is useless.

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 7]
```diff
@@ -226,10 +227,15 @@ static int gspi_siwx91x_dma_config(const struct device *dev,
 		.block_count = block_count,
 		.head_block = channel->dma_descriptors,
 		.dma_slot = channel->dma_slot,
-		.dma_callback = is_tx ? &gspi_siwx91x_dma_tx_callback : NULL,
 		.user_data = (void *)dev,
 	};
 
+	if ((rx_null_buf && is_tx) || (!is_tx && !rx_null_buf)) {
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: Such weird design deserve a comment:
```
/* Because of gpDMA bug, we have to register the callback on Rx DMA. However,
 * another bug in gpDMA forces to complete Rx DMA early when Rx buffer is NULL.
 * So, for this case, we have to rely on the Tx DMA.
 * Note, despite the complexity, ths dance works with non-buggy DMA (eg. uDMA).
 */
```
BTW, could you provide detail about the bug you find with the Tx callback? Is my understand of the Rx case is correct?

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 8]
```diff
@@ -213,7 +213,8 @@ static void gspi_siwx91x_dma_tx_callback(const struct device *dev, void *user_da
 
 static int gspi_siwx91x_dma_config(const struct device *dev,
 				   struct gspi_siwx91x_dma_channel *channel, uint32_t block_count,
-				   bool is_tx, uint8_t dfs, uint8_t burst_size)
+				   bool is_tx, uint8_t dfs, uint8_t burst_size,
+				   uint8_t rx_null_buf)
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: `rx_null_buf` is a negative logic. I suggest to invert it: `uint8_t rx_null_buf` -> `bool transaction_has_rx`. Then, we will be able to directly pass `data->ctx.rx_buf` as argument.

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 9]
```diff
@@ -502,6 +509,19 @@ static int gspi_siwx91x_transceive_dma(const struct device *dev, const struct sp
...
+		 * and may remain in the GSPI RX FIFO. Explicitly reset both RX and TX
+		 * FIFOs to flush any residual data, ensuring subsequent transfers
+		 * start with a clean FIFO state.
+		 */
+		cfg->reg->GSPI_FIFO_THRLD_b.RFIFO_RESET = 1;
+		cfg->reg->GSPI_FIFO_THRLD_b.WFIFO_RESET = 1;
+		cfg->reg->GSPI_FIFO_THRLD_b.RFIFO_RESET = 0;
+		cfg->reg->GSPI_FIFO_THRLD_b.WFIFO_RESET = 0;
+		rx_null_buf = 0;
+	}
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: This change looks racy. `spi_context_wait_for_completion()` does not block if `ctx->asynchronous` is set. So, we are resetting the FIFO while the transaction is in progress.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 7 above)
Comment (jerome-pouiller) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Another thing: we only manage the case where rx_buf is NULL, but the rx_buf can just be smaller than the tx_buf. In this case, the callback has also to be used on Tx, no?

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 1 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Updated

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 2 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: No specific reason — using bool makes more sense here. Updated accordingly.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 3 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: No specific reason — using bool makes more sense here. Updated accordingly.

File: drivers/clock_control/clock_control_silabs_siwx91x.c (hunk 4 above)
Comment (smalae) [reply drivers/clock_control/clock_control_silabs_siwx91x.c]: Done

File: drivers/clock_control/clock_control_silabs_siwx91x.c (hunk 5 above)
Comment (smalae) [reply drivers/clock_control/clock_control_silabs_siwx91x.c]: Agreed. I’ve reordered the commits and placed this change at the end, after the fixes that enable the clock migration.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 6 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c:249]: Agreed. I’ve removed the else block and initialized `.dma_callback` to NULL by default to ensure the local variable is always initialized.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 7 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: While debugging with a logic analyzer, I observed that when relying on the Tx DMA callback, the last byte of the transfer is sometimes missed. To avoid this, we rely on the Rx DMA callback, which ensures the transfer is completed only after the final byte has actually been received.

Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Also, handled the `rx_len < tx_len` condition

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 8 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: I prefer to keep the current logic since we also need to handle the additional case where `rx_len < tx_len`.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 9 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Agreed. This was racy for asynchronous transfers. I’ve updated the code to handle async transfers correctly

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 10]
```diff
@@ -357,9 +375,14 @@ static int gspi_siwx91x_prepare_dma_channel(const struct device *spi_dev,
 		return -ENOMEM;
 	}
 
+	if (data->ctx.rx_buf == NULL ||
+	    spi_context_total_rx_len(&data->ctx) < spi_context_total_tx_len(&data->ctx)) {
+		rx_null_buf = true;
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: So, `rx_null_buf` does not anymore reflect the case where Rx `buf == NULL`. We probably have to find a better name (`complete_on_tx_dma`, `trig_on_tx`, `use_tx_cb`?)

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 11]
```diff
@@ -514,6 +536,18 @@ static int gspi_siwx91x_transceive_dma(const struct device *dev, const struct sp
 		goto force_transaction_close;
 	}
 
+	if (rx_null_buf && !asynchronous) {
+		/* When a NULL RX buffer is used, RX data is not consumed by software
+		 * and may remain in the GSPI RX FIFO. Explicitly reset both RX and TX
+		 * FIFOs to flush any residual data, ensuring subsequent transfers
+		 * start with a clean FIFO state.
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: You mean we have to reset the fifo before the user access to the data, or is it only require for the subsequent transfers. In the latter case, what is the point of doing this after the transaction rather than before the transaction?

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 12]
```diff
@@ -485,9 +501,15 @@ static int gspi_siwx91x_transceive_dma(const struct device *dev, const struct sp
 		burst_size = gspi_siwx91x_burst_size(ctx);
 	}
 
-	cfg->reg->GSPI_FIFO_THRLD_b.RFIFO_RESET = 1;
-	cfg->reg->GSPI_FIFO_THRLD_b.WFIFO_RESET = 1;
-	cfg->reg->GSPI_FIFO_THRLD = 0;
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c:467]: If the previous transaction was `!rx_null_buf && !asynchronous`, the FIFO is not reset. Is it expected?

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 13]
```diff
@@ -514,6 +536,18 @@ static int gspi_siwx91x_transceive_dma(const struct device *dev, const struct sp
 		goto force_transaction_close;
 	}
 
+	if (rx_null_buf && !asynchronous) {
+		/* When a NULL RX buffer is used, RX data is not consumed by software
+		 * and may remain in the GSPI RX FIFO. Explicitly reset both RX and TX
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: In this code, `rx_null_buf` may mean `spi_context_total_rx_len(ctx) < spi_context_total_tx_len(ctx)`. In this case the RX data is consumed by software.

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 14]
```diff
@@ -514,6 +536,18 @@ static int gspi_siwx91x_transceive_dma(const struct device *dev, const struct sp
...
+		 * FIFOs to flush any residual data, ensuring subsequent transfers
+		 * start with a clean FIFO state.
+		 */
+		cfg->reg->GSPI_FIFO_THRLD_b.RFIFO_RESET = 1;
+		cfg->reg->GSPI_FIFO_THRLD_b.WFIFO_RESET = 1;
+		cfg->reg->GSPI_FIFO_THRLD_b.RFIFO_RESET = 0;
+		cfg->reg->GSPI_FIFO_THRLD_b.WFIFO_RESET = 0;
+	}
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: Won't be easier to unconditionally reset the FIFO in `gspi_siwx91x_dma_callback` (which is called whatever the value of `asynchronous`)

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 10 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Changed the name to `use_tx_cb`

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 11 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: When a FIFO reset is performed for each transaction, some residual data continues to flush out even after the reset sequence completes. As soon as the CS line is asserted to begin the actual transfer, this leftover data leaks into the bus and interferes with the intended data, resulting in corrupted or unexpected behavior.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 12 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c:467]: As mentioned above, I want to avoid unnecessary FIFO resets, as they interfere with the actual data transfer. Additionally, the condition `!rx_null_buf && !asynchronous` represents a generic transfer use case, and in this scenario, a FIFO reset should not be required.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 13 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Updated the comment and changes the name of `rx_null_buf` to `null_rx_present`

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 14 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: As mentioned earlier, I’ve already highlighted the risk associated with this approach

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 9 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Following this change, I’m observing unexpected behavior on brd4338a, while brd4342a continues to work as expected. I’m looking into the root cause.

Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: This issue is resolved by removing the FIFO reset performed in `gspi_siwx91x_config`. Now, the FIFO reset is applied only in the null_rx case.

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 15]
```diff
@@ -226,10 +227,26 @@ static int gspi_siwx91x_dma_config(const struct device *dev,
...
+	 * the final byte there is '\0'.
+	 *
+	 * However, there is another gpDMA bug where the Rx DMA completes early if
+	 * the Rx buffer is NULL. In that specific case, we must instead rely on
+	 * the Tx DMA callback to signal completion.
+	 *
+	 * Despite this conditional handling, the logic works correctly on
+	 * non-buggy DMA engines (for example, uDMA).
+	 */
+	if ((use_tx_cb && is_tx) || (!is_tx && !use_tx_cb)) {
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: `if (use_tx_cb == is_tx)`

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 16]
```diff
@@ -357,9 +375,14 @@ static int gspi_siwx91x_prepare_dma_channel(const struct device *spi_dev,
 		return -ENOMEM;
 	}
 
+	if (data->ctx.rx_buf == NULL ||
+	    spi_context_total_rx_len(&data->ctx) < spi_context_total_tx_len(&data->ctx)) {
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: I believe rx_count can be > 1 with the last buffer == NULL. In this case, data->ctx.rx_buf is not NULL, and `spi_context_total_rx_len(&data->ctx) == spi_context_total_tx_len(&data->ctx)`. I believe we have to check if the last buffer is NULL (maybe the case where both tx and rx arrays end with NULL also exist).

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 11 above)
Comment (jerome-pouiller) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: This seems to be racy. If understand, we need either:
  - a delay between the Fifo reset and the start of the transaction
  - reset the just after the transaction (without any delay)

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 14 above)
Comment (jerome-pouiller) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: hmm... If you change the condition in the callback in `if (channel == data->dma_tx.chan_nb)` and remove this one, you don't get the same results?

File: drivers/clock_control/clock_control_silabs_siwx91x.c [hunk 17]
```diff
@@ -252,6 +254,9 @@ static int siwx91x_clock_init(const struct device *dev)
...
+	RSI_CLK_QspiClkConfig(pCLK, QSPI_INTFPLLCLK, 0, 0, 1);
```
Comment (jerome-pouiller) [inline drivers/clock_control/clock_control_silabs_siwx91x.c]: You can save one level of indirection: `RSI_CLK_QspiClkConfig(M4CLK, QSPI_INTFPLLCLK, 0, 0, 1);`

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 15 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Updated

File: drivers/clock_control/clock_control_silabs_siwx91x.c (hunk 17 above)
Comment (smalae) [reply drivers/clock_control/clock_control_silabs_siwx91x.c]: Done

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 16 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: My understanding is that when rx_count > 1 and the last RX buffer is NULL, the effective total RX length becomes smaller than the TX length, which is what **test_spi_rx_half_start()** exercises. In that case, the condition based on total lengths should already catch the null RX tail.
For the case where both TX and RX end with NULL buffers, my understanding is that the final transfer is dropped during buffer setup, so those NULL buffers do not participate in the transaction.
Please let me know if I’m missing any corner cases here.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 11 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Yes, I observed the same behavior during testing. We need either a small delay between the FIFO reset and starting the transaction, or move the reset to just after the transaction completes.

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 14 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Yes, I tried that approach. In theory, changing the condition to if (channel == data->dma_tx.chan_nb) and removing the other check should not change the behavior. However, in practice, the reset done from the callback does not seem to work reliably, and the issue still reproduces.

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 18]
```diff
@@ -209,12 +210,14 @@ static void gspi_siwx91x_dma_tx_callback(const struct device *dev, void *user_da
 	spi_context_cs_control(instance_ctx, false);
 	spi_context_complete(instance_ctx, spi_dev, status);
 	pm_device_runtime_put_async(spi_dev, K_NO_WAIT);
+	data->use_tx_cb = false;
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: It is probably more consistent to place this in `gspi_siwx91x_prepare_dma_transaction()`.

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 19]
```diff
@@ -343,20 +369,24 @@ static int gspi_siwx91x_prepare_dma_channel(const struct device *spi_dev,
...
-	desc = gspi_siwx91x_fill_data_desc(cfg, channel->dma_descriptors, buffer, buffer_count,
+	desc = gspi_siwx91x_fill_data_desc(spi_dev, channel->dma_descriptors, buffer, buffer_count,
 					   padded_transaction_size, is_tx);
 	if (!desc) {
 		return -ENOMEM;
 	}
 
+	if (data->ctx.rx_buf == NULL ||
+	    spi_context_total_rx_len(&data->ctx) < spi_context_total_tx_len(&data->ctx)) {
+		data->use_tx_cb = true;
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: Is it still required since we change it `gspi_siwx91x_fill_data_desc()`?

File: drivers/spi/spi_silabs_siwx91x_gspi.c [hunk 20]
```diff
@@ -453,6 +453,21 @@ static int gspi_siwx91x_burst_size(struct spi_context *ctx)
 
 	return burst_len;
 }
+
+static void gspi_siwx91x_gspi_fifo_reset_sync(uint32_t frequency)
+{
+	int loops = CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC/frequency;
```
Comment (jerome-pouiller) [inline drivers/spi/spi_silabs_siwx91x_gspi.c]: Spaces around binary operator.

File: drivers/clock_control/clock_control_silabs_siwx91x.c (hunk 5 above)
Comment (jerome-pouiller) [reply drivers/clock_control/clock_control_silabs_siwx91x.c]: Could you fix the comment (we changing the clock source, not the frequency).

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 18 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Done

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 19 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Updated

File: drivers/spi/spi_silabs_siwx91x_gspi.c (hunk 20 above)
Comment (smalae) [reply drivers/spi/spi_silabs_siwx91x_gspi.c]: Updated

**Review by jerome-pouiller — APPROVED** [review]

**Review by jerome-pouiller — APPROVED** [review]

**Comment by smalae** [comment]
> @smalae I think having the right clock source for QSPI is important to backport to zephyr 4.3. I will take care of the bug ticket and the backport. But in order to have a clean process, please correct commit title and description, it is a change of clock source and not just an increase of the QSPI frequency. (as @jerome-pouiller mentioned)

@Martinhoff-maker , thanks for that. I updated them accordingly.

**Review by jhedberg — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]
