### PR TITLE
bluetooth: mesh: Fix composition data page 1

### LINKED ISSUE #63630: Bluetooth: Mesh: Composition Data Page 1 is encoded incorrectly
**Describe the bug**
When encoding vendor models in Composition Data Page 1 the index starts with the number of Sig models instantiated on the same element. Section 4.2.2.2, MshPRTv1.1:

```
- For a Vendor Model, the index is equal to the sum of the Number_S field value and an index of the 
model in the Vendor Models field of Composition Data Page 0 of the identified element. 
```

**Expected behavior**
We should add number of sig models instantiated on the same element when encoding vendor model index.

**Impact**
Qualification of Mesh Protocol v1.1

### PR DESCRIPTION
**Pull request by HaavardRei**
cfg_cli: Changed buffer length check in bt_mesh_comp_p1_elem_pull
to be able to pull small final elements.

access.c: Added offset to the model relation register for vendor
models to find correct model index for CDP1
Modified macros for determining if a model is a base- or extending model.

bsim: Adds bsim test to verify that CDP1 is
encoded and decoded correctly.

Fixes #63630

Signed-off-by: Håvard Reierstad <haavard.reierstad@nordicsemi.no>

### CODE REVIEW

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 1]
```diff
@@ -0,0 +1,517 @@
...
+	err = bt_mesh_cfg_cli_app_key_add(0, cfg.addr, 0, 0, app_key, &status);
+	if (err || status) {
+		FAIL("AppKey add failed (err %d, status %u)", err, status);
+		return;
+	}
+}
+
+static void verify_cdp1(struct bt_mesh_comp_p1_elem p1_elem,
+			struct bt_mesh_comp_p1_model_item mod_item,
+			struct bt_mesh_comp_p1_ext_item ext_item, struct net_buf_simple p1_dev_comp)
```
Comment (PavelVPV) [inline tests/bsim/bluetooth/mesh/src/test_cdp1.c:367]: It is too much to pass these structures by values:
```suggestion
static void verify_cdp1(struct bt_mesh_comp_p1_elem *p1_elem,
			struct bt_mesh_comp_p1_model_item *mod_item,
			struct bt_mesh_comp_p1_ext_item *ext_item, struct net_buf_simple *p1_dev_comp)
```

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 2]
```diff
@@ -0,0 +1,517 @@
...
+{
+	int elem_idx = 0;
+
+	while (bt_mesh_comp_p1_elem_pull(&p1_dev_comp, &p1_elem)) {
+		ASSERT_EQUAL(p1_elems[elem_idx].nsig, p1_elem.nsig);
+		ASSERT_EQUAL(p1_elems[elem_idx].nvnd, p1_elem.nvnd);
```
Comment (PavelVPV) [inline tests/bsim/bluetooth/mesh/src/test_cdp1.c:373]: The names are little bit confusing. Not clear which variables represent hardcoded values and what were retrieved through Configuration Client. I'd suggest use some prefix, like `test_` or `test_vector`.

File: subsys/bluetooth/mesh/cfg_cli.c [hunk 3]
```diff
@@ -2320,7 +2320,7 @@ struct bt_mesh_mod_id_vnd bt_mesh_comp_p0_elem_mod_vnd(struct bt_mesh_comp_p0_el
 struct bt_mesh_comp_p1_elem *bt_mesh_comp_p1_elem_pull(struct net_buf_simple *buf,
 						       struct bt_mesh_comp_p1_elem *elem)
 {
-	if (buf->len < 6) {
+	if (buf->len < 4) {
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/cfg_cli.c:2323]: If possible, could you move this change to a separate commit?

**Review by PavelVPV — CHANGES_REQUESTED** [review]

File: tests/bsim/bluetooth/mesh/tests_scripts/comp_data/cdp1_encode_decode.sh [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+# extensions requiring long and short formats, and correspondence between
+# a SIG and vendor model.
+#
+# Test procedure:
+# 0. Provisioning and setup.
+# 1. Configuration client requests the node's CDP1.
+# 2. The received CDP1 is compared to a hardcoded version.
+conf=prj_mesh1d1_conf
+RunTest mesh_cdp1_test \
+	cdp1_node_data_comparison
```
Comment (alxelax) [inline tests/bsim/bluetooth/mesh/tests_scripts/comp_data/cdp1_encode_decode.sh:18]: Just FYI
Seems parsing\composing tests are the first candidates for unit testing. No need to use bsim since no access to the media is required.

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 5]
```diff
@@ -0,0 +1,517 @@
...
+	}
+
+	err = bt_mesh_cfg_cli_app_key_add(0, cfg.addr, 0, 0, app_key, &status);
+	if (err || status) {
+		FAIL("AppKey add failed (err %d, status %u)", err, status);
+		return;
+	}
+}
+
+static void verify_cdp1(struct bt_mesh_comp_p1_elem p1_elem,
```
Comment (alxelax) [inline tests/bsim/bluetooth/mesh/src/test_cdp1.c:365]: Could you split this function into many simple ones? A lot of nesting levels.

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 6]
```diff
@@ -0,0 +1,517 @@
...
+
+static uint8_t app_key[16] = { 0xaa };
+static uint8_t net_key[16] = { 0xcc };
+
+static const struct bt_mesh_test_cfg node1_cfg = {
+	.addr = NODE_ADDR,
+	.dev_key = {0xaa},
+};
+
+static const struct bt_mesh_model_cb test_model1_cb = {
```
Comment (alxelax) [inline tests/bsim/bluetooth/mesh/src/test_cdp1.c:47]: A lot of copy-paste. Could you create a parametrized macro to create all necessary entities for one model?
Smth like:
```
#define MODEL_EXT(test_id_number) \
bt_mesh_model_extend(bt_mesh_model_find(&elems[0], test_id_number), model)

#define MODEL_NO_EXT  0

#define TEST_MODEL_DECLARE(number, ...) \
static const struct bt_mesh_model_cb test_model##number##_cb = { \
	.init = model##number##_init,    \
}; \
static const struct bt_mesh_model_op model_op##number##[] = { \
	BT_MESH_MODEL_OP_END, \
}; \
static int model##number##_init(struct bt_mesh_model *model) \
{ \
        ASSERT_OK(__VA_ARGS__); \
	return 0; \
}
```

**Review by alxelax — CHANGES_REQUESTED** [review]

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c (hunk 5 above)
Comment (alxelax) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c:365]: functions with meaningful names to understand what each loop checks.

**Review by akredalen — COMMENTED** [review]
Just providing some general feedback as there are already quite a few pending comments.

Good job adding the model relation offset for vendor models and updating the macros to handle model extensions correctly. Thanks! 🥇
Regarding the test, I agree with @alxelax that it would have been more suitable as a unit test, even though the JIRA task initially called for a Bsim test. I apologize for not catching this earlier. Before getting into potential ways of making the test more maintainable, should we consider making it into a unit test instead?

File: subsys/bluetooth/mesh/access.c [hunk 7]
```diff
@@ -91,17 +91,13 @@ static struct mod_relation mod_rel_list[MOD_REL_LIST_SIZE];
 		  mod_rel_list[(idx)].idx_ext == 0); \
 		 (idx)++)
 
-#define IS_MOD_BASE(mod, idx) \
+#define IS_MOD_BASE(mod, idx, offset) \
 	(mod_rel_list[(idx)].elem_base == (mod)->elem_idx && \
-	 mod_rel_list[(idx)].idx_base == (mod)->mod_idx &&   \
-	 !(mod_rel_list[(idx)].elem_ext != (mod)->elem_idx && \
-	   mod_rel_list[(idx)].idx_ext != (mod)->mod_idx))
+	 mod_rel_list[(idx)].idx_base == (mod)->mod_idx + offset)
```
[the remark this answers is not in the document]
Comment (HaavardRei) [reply subsys/bluetooth/mesh/access.c]: Updated!

File: subsys/bluetooth/mesh/access.c [hunk 8]
```diff
@@ -118,6 +114,20 @@ static const struct {
...
 };
 
+/* If the model is a vendor model, finds the number of SIG models in the element
+ * the model is present on to use as offset in the model relation list.
+ */
+static uint8_t get_sig_offset(struct bt_mesh_model *mod)
+{
+	const struct bt_mesh_elem *elem = bt_mesh_model_elem(mod);
+
+	if (bt_mesh_model_find(elem, mod->id)) {
```
[the remark this answers is not in the document]
Comment (HaavardRei) [reply subsys/bluetooth/mesh/access.c]: Changed to compare model pointers in the vnd_models array instead.

File: subsys/bluetooth/mesh/access.c [hunk 9]
```diff
@@ -91,17 +91,13 @@ static struct mod_relation mod_rel_list[MOD_REL_LIST_SIZE];
 		  mod_rel_list[(idx)].idx_ext == 0); \
 		 (idx)++)
 
-#define IS_MOD_BASE(mod, idx) \
+#define IS_MOD_BASE(mod, idx, offset) \
```
[the remark this answers is not in the document]
Comment (HaavardRei) [reply subsys/bluetooth/mesh/access.c:94]: After discussing in person with @PavelVPV , we came to the conclusion that keeping the offset would be more efficient, and fetching the offset directly from the composition where this is available. (I. e. not calling 'get_sig_offset' unless we need to get the offset by finding the element based on the model.)

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c (hunk 5 above)
Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Function is now split into multiple 'verify_' function specifying what is checked.

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c (hunk 6 above)
Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Made macros for declaring models. Thanks for the suggestion!

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 10]
```diff
@@ -0,0 +1,517 @@
...
+
+static int model6_init(struct bt_mesh_model *model)
+{
+	ASSERT_OK(bt_mesh_model_extend(model, bt_mesh_model_find(&elems[0], TEST_MODEL_ID_1)));
+	return 0;
+}
+
+static int model_vnd1_init(struct bt_mesh_model *model)
+{
+	ASSERT_OK(bt_mesh_model_correspond(
```
[the remark this answers is not in the document]
Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Done! Discovered a new bug when having both extend and correspond in the vendor model, which I fixed in the second commit.

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c (hunk 1 above)
Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Done!

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c (hunk 2 above)
Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Renamed in addition to splitting the verify function into smaller functions.

File: subsys/bluetooth/mesh/cfg_cli.c (hunk 3 above)
Comment (HaavardRei) [reply subsys/bluetooth/mesh/cfg_cli.c:2323]: Done!

**Comment by PavelVPV** [comment]
Looks very good. Just two minor requests regarding the commits:
- please elaborate a bit the change in the commit headline in https://github.com/zephyrproject-rtos/zephyr/pull/63379/commits/d5c97b818dff88a55435394ee5a3e3629cafb25c
- please start commit message with a verb (e.g. Implement/implement, or add/Add) in https://github.com/zephyrproject-rtos/zephyr/pull/63379/commits/5e06b2f8e4f383e63e82b92e1f3d804d6c8115ac

**Comment by PavelVPV** [comment]
@HaavardRei don't forget to resolve the conflicts.

**Review by PavelVPV — DISMISSED** [review]

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c (hunk 6 above)
Comment (alxelax) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: I'm pretty sure it is possible to put functions under macro to have less copy-paste code. However, this is much better than nothing.

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 11]
```diff
@@ -0,0 +1,430 @@
...
+
+static void provision_and_configure(struct bt_mesh_test_cfg cfg)
+{
+	int err;
+	uint8_t status;
+
+	err = bt_mesh_provision(net_key, 0, 0, 0, cfg.addr, cfg.dev_key);
+	if (err) {
+		FAIL("Provisioning failed (err %d)", err);
+		return;
```
Comment (alxelax) [inline tests/bsim/bluetooth/mesh/src/test_cdp1.c:299]: do not need `return` if there is `FAIL`. Here and below.

**Review by alxelax — COMMENTED** [review]
Looks much better. Need minor clean up. Please take a look at my comment.

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 12]
```diff
@@ -0,0 +1,430 @@
...
+			struct bt_mesh_comp_p1_ext_item *ext_item,
+			struct net_buf_simple *p1_dev_comp)
+{
+	int elem_idx = 0;
+
+	while (bt_mesh_comp_p1_elem_pull(p1_dev_comp, p1_elem)) {
+		ASSERT_EQUAL(test_p1_elems[elem_idx].nsig, p1_elem->nsig);
+		ASSERT_EQUAL(test_p1_elems[elem_idx].nvnd, p1_elem->nvnd);
+
+		int mod_idx, ext_mod_idx;
```
Comment (akredalen) [inline tests/bsim/bluetooth/mesh/src/test_cdp1.c:365]: I would declare the loop variables in the for-loop(s) instead to keep their reach limited to just within the loop. Just to be safe.
`for (int mod_idx = 0; mod_idx < p1_elem->nsig; mod_idx++) {`

**Review by akredalen — COMMENTED** [review]
Looks good! Just a couple of suggestions :)

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c (hunk 11 above)
Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Removed!

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 13]
```diff
@@ -0,0 +1,430 @@
...
+			     mod_item->cor_id);
+	}
+}
+
+static void verify_ext_item(struct bt_mesh_comp_p1_ext_item *ext_item, int elem_idx, int mod_idx,
+			    int offset)
+{
+	struct bt_mesh_comp_p1_ext_item *test_p1_ext_item;
+
+	if (elem_idx == 0 && (mod_idx + offset) == 3) {
```
[the remark this answers is not in the document]
Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Changed to switch case :)

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c (hunk 12 above)
Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Fixed!

File: tests/bsim/bluetooth/mesh/src/test_cdp1.c [hunk 14]
```diff
@@ -0,0 +1,433 @@
...
+		test_p1_ext_item = &test_p1_ext_mod3_mod4;
+		break;
+	case 5: /* elem_idx=0, mod_idx=0, offset = 5*/
+		test_p1_ext_item = &test_p1_ext_vnd1_mod1;
+		break;
+	case 400: /* elem_idx=4, mod_idx=0*/
+		test_p1_ext_item = &test_p1_ext_mod6_mod1;
+		break;
+	default:
+		return;
```
Comment (alxelax) [inline tests/bsim/bluetooth/mesh/src/test_cdp1.c:340]: Shouldn't be `FAIL` here instead of `return`?

Comment (HaavardRei) [reply tests/bsim/bluetooth/mesh/src/test_cdp1.c]: Agreed, changed to `FAIL`.

**Review by akredalen — DISMISSED** [review]

**Review by PavelVPV — DISMISSED** [review]

**Review by PavelVPV — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by akredalen — APPROVED** [review]

**Review by alxelax — APPROVED** [review]
