### PR TITLE
ztest: add a delay between tests

### LINKED ISSUE #50455: Intel CAVS15/25: tests/subsys/shell/shell failed with no console output
**Describe the bug**
On intel_adsp_cavs15/25 platform, tests/subsys/shell/shell failed.

Tried:
(1) Add extra delay between test functions, it will pass stably.
(2) Use HDA logging, it will fail sporadically.
Boards overlay:
```
CONFIG_DMA=y
CONFIG_ASSERT=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_ADSP=n
CONFIG_LOG_BACKEND_ADSP_HDA=y
CONFIG_LOG_BACKEND_ADSP_HDA_SIZE=8192
CONFIG_LOG_BACKEND_ADSP_HDA_PADDING=y
CONFIG_LOG_BACKEND_ADSP_HDA_CAVSTOOL=y
CONFIG_LOG_BACKEND_ADSP_HDA_FLUSH_TIME=100
CONFIG_XTENSA_ENABLE_BACKTRACE=n
CONFIG_LOG_PRINTK=y
```

**To Reproduce**
1. twister -W --hardware-map /home/ztest/cavs/cavs.map --device-testing -x=CONFIG_BOOT_DELAY=500 -T tests/subsys/shell/shell/ --no-skipped-report -vv
2. See error

**Logs and console output**
Using HDA logging fail sporadically:
```
DEBUG   - DEVICE: shell_execute_cmd(colors on): 0
DEBUG   - DEVICE: shell_execute_cmd(colors): -8
DEBUG   - DEVICE: shell_execute_cmd(shell colors on): 0
DEBUG   - DEVICE: PASS - test_set_root_cmd in 0.002 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_shell_fprintf
DEBUG   - DEVICE: PASS - test_shell_fprintf in 0.001 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_shell_module
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd): 0
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd -h): 1
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd --help): 1
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(test_shell_cmd dummy dummy): -22
DEBUG   - DEVICE: shell_execute_cmd(): -8
DEBUG   - DEVICE: shell_execute_cmd(not existing command): -8
DEBUG   - DEVICE: PASS - test_shell_module in 0.003 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_shell_wildcards_dynamic
DEBUG   - DEVICE: shell_execute_cmd(test_dynamic): 0
DEBUG   - DEVICE: shell_execute_cmd(test_dynamic d*): 1
DEBUG   - DEVICE: shell_execute_cmd(test_dynamic c*): 1
DEBUG   - DEVICE: shell_execute_cmd(test_dynamic d* c*): 2
DEBUG   - DEVICE: PASS - test_shell_wildcards_dynamic in 0.002 seconds
DEBUG   - DEVICE: ===================================================================
DEBUG   - DEVICE: START - test_shell_wildcards_static
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard): 0
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard argument_1): 1
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard argument?1): 1
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard argu?ent?1): 1
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard a*1): 1
DEBUG   - DEVICE: shell_execute_cmd(test_wildcard ar?u*1): 1
DEBUG   - Timed out while monitoring serial output on intel_adsp_cavs25
DEBUG   - Process /home/ztest/zephyrproject/zephyr/soc/xtensa/intel_adsp/tools/cavstool_client.py,-s,192.165.1.58,-l terminated outs: None errs None
DEBUG   - run status: intel_adsp_cavs25/tests/subsys/shell/shell/shell.core error
INFO    - 15/15 intel_adsp_cavs25         tests/subsys/shell/shell/shell.core                FAILED No Console Output(Timeout) (device 60.565s)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain - SDK 15.0

### PR DESCRIPTION
**Pull request by nashif**
Some testsuites dump lots of output very fast where some systems are not
able to capture the complete output from the tests. Add a slight delay
between each test in the suite.

Fixes #50455

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by stephanosio — DISMISSED** [review]

**Review by yperess — DISMISSED** [review]

**Review by henrikbrixandersen — DISMISSED** [review]

**Review by teburd — DISMISSED** [review]

**Comment by shuai1x** [comment]
I tested it on CAVS platform five times. And it would pass stably. So this PR will solve the issue of missing log.

**Review by chen-png — DISMISSED** [review]

File: subsys/testsuite/ztest/Kconfig [hunk 1]
```diff
@@ -22,6 +22,13 @@ config ZTEST_STACK_SIZE
 	default 2048 if COVERAGE_GCOV
 	default 1024
 
+config ZTEST_TEST_DELAY
```
Comment (fabiobaltieri) [inline subsys/testsuite/ztest/Kconfig:25]: How about ZTEST_TEST_DELAY_MS?

File: subsys/testsuite/ztest/src/ztest_new.c [hunk 2]
```diff
@@ -509,6 +509,9 @@ static int run_test(struct ztest_suite_node *suite, struct ztest_unit_test *test
 {
 	int ret = TC_PASS;
 
+#if CONFIG_ZTEST_TEST_DELAY_MS > 0
+	k_busy_wait(CONFIG_ZTEST_TEST_DELAY_MS * 1000);
```
Comment (fabiobaltieri) [inline subsys/testsuite/ztest/src/ztest_new.c:513]: Sorry just noticed this as well: should probably use `USEC_PER_MSEC` instead of `1000`.

**Review by fabiobaltieri — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
