### PR TITLE
drivers: counter: fix to allow LSE clock source for not F4 SoC

### LINKED ISSUE #15354: counter: stm32: Issue with LSE clock source selection
**Describe the bug**
Compilation issue in STM32 counter driver when LSE is the clock source and SoC is not F4.

cf #15351

### PR DESCRIPTION
**Pull request by GeorgeCGV**
Fixes the STM32 counter driver when LSE is the clock source and SoC is not F4.

Fixes #15354

### CODE REVIEW

File: drivers/counter/counter_ll_stm32_rtc.c [hunk 1]
```diff
@@ -275,7 +275,7 @@ static int rtc_stm32_init(struct device *dev)
 
 #else /* CONFIG_COUNTER_RTC_STM32_CLOCK_LSE */
 
-#ifndef(CONFIG_SOC_SERIES_STM32F4X)
+#ifndef CONFIG_SOC_SERIES_STM32F4X
```
Comment (erwango) [inline drivers/counter/counter_ll_stm32_rtc.c]: Should add !F1 and !F2 as well.

**Review by erwango — CHANGES_REQUESTED** [review]

File: drivers/counter/counter_ll_stm32_rtc.c (hunk 1 above)
Comment (GeorgeCGV) [reply drivers/counter/counter_ll_stm32_rtc.c]: Corrected.
Furthermore,  ```LL_RTC_EnableShadowRegBypass``` doesn't exist for F1 and F2 as well.
And overall the counter won't work for F2, as used ```LL_RTC_ALMA_Enable``` & ```LL_RTC_ALMA_Disable``` are not valid for F2. 
Unfortunately, I don't have F2 at hands to correct and validate F2.

File: drivers/counter/counter_ll_stm32_rtc.c [hunk 2]
```diff
@@ -302,7 +307,14 @@ static int rtc_stm32_init(struct device *dev)
 
 #ifdef RTC_CR_BYPSHAD
 	LL_RTC_DisableWriteProtection(RTC);
+
+#if !defined(CONFIG_SOC_SERIES_STM32F2X) &&	\
+	!defined(CONFIG_SOC_SERIES_STM32F1X)
+
 	LL_RTC_EnableShadowRegBypass(RTC);
+
+#endif /* !STM32F2X && !STM32F4X */
```
Comment (erwango) [inline drivers/counter/counter_ll_stm32_rtc.c]: #endif comment doesn't match the #if

File: drivers/counter/counter_ll_stm32_rtc.c [hunk 3]
```diff
@@ -275,10 +275,15 @@ static int rtc_stm32_init(struct device *dev)
 
 #else /* CONFIG_COUNTER_RTC_STM32_CLOCK_LSE */
 
-#ifndef(CONFIG_SOC_SERIES_STM32F4X)
+#if !defined(CONFIG_SOC_SERIES_STM32F4X) &&	\
+	!defined(CONFIG_SOC_SERIES_STM32F2X) &&	\
```
Comment (erwango) [inline drivers/counter/counter_ll_stm32_rtc.c]: Let's remove the F2, if F2 is not yet supported.
We'll add and issue to state driver should be ported on F2. It'll be less confusing.

**Review by erwango — CHANGES_REQUESTED** [review]
Txs for feedback. Let's not take F2 into account if not supported

File: drivers/counter/counter_ll_stm32_rtc.c (hunk 3 above)
Comment (GeorgeCGV) [reply drivers/counter/counter_ll_stm32_rtc.c]: Got it

Comment (GeorgeCGV) [reply drivers/counter/counter_ll_stm32_rtc.c]: Oh, I shall correct myself, not F2, but F1

**Review by erwango — CHANGES_REQUESTED** [review]
One last request, sorry for not asking earlier:
can you split in 2 commits ?
-F4 case
-F2 addition including LL_RTC_EnableShadowRegBypass handling
Thanks

**Comment by GeorgeCGV** [comment]
Removed F2 LL_RTC_EnableShadowRegBypass handling

**Review by erwango — APPROVED** [review]
