### PR TITLE
soc: nrf53: Change logging level of anomaly 160 message to DEBUG

### LINKED ISSUE #55212: tests: kernel: mem_protect: stack_random: kernel.memory_protection.stack_random fails
**Describe the bug**
The tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random fails

Observed for:
- nrf5340dk_nrf5340_cpunet

**To Reproduce**
1. have nrf5340dk_nrf5340_cpunet connected
2. go to your zephyr dir
3. call ./scripts/twister -T tests/kernel/mem_protect/stack_random -p nrf5340dk_nrf5340_cpunet --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
[2023-02-27T01:21:38.236Z] [0mERROR   - W: Anomaly 160 trigger conditions detected.[0m
[2023-02-27T01:21:38.236Z] [0m*** Booting Zephyr OS build zephyr-v3.3.0-472-gb2512d2f534e ***[0m
[2023-02-27T01:21:38.236Z] [0mRunning TESTSUITE stack_pointer_randomness[0m
[2023-02-27T01:21:38.236Z] [0m===================================================================[0m
[2023-02-27T01:21:38.236Z] [0mSTART - test_stack_pt_randomization[0m
[2023-02-27T01:21:38.236Z] [0mTest Stack pointer randomization[0m
[2023-02-27T01:21:38.236Z] [0mE: ***** HARD FAULT *****[0m
[2023-02-27T01:21:38.236Z] [0mE:   Fault escalation (see below)[0m
[2023-02-27T01:21:38.236Z] [0mE: ***** BUS FAULT *****[0m
[2023-02-27T01:21:38.236Z] [0mE:   Precise data bus error[0m
[2023-02-27T01:21:38.236Z] [0mE:   BFAR Address: 0x1edc8a83[0m
[2023-02-27T01:21:38.236Z] [0mE: r0/a1:  0xfc6f2f9e  r1/a2:  0xd0bcc16d  r2/a3:  0x0100675e[0m
[2023-02-27T01:21:38.236Z] [0mE: r3/a4:  0x61000000 r12/ip:  0x22320413 r14/lr:  0xea5b91e2[0m
[2023-02-27T01:21:38.236Z] [0mE:  xpsr:  0x01007400[0m
[2023-02-27T01:21:38.236Z] [0mE: Faulting instruction address (r15/pc): 0x1edc8a85[0m
[2023-02-27T01:21:38.236Z] [0mE: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0[0m
[2023-02-27T01:21:38.236Z] [0mE: Current thread: 0x21000220 (idle)[0m
[2023-02-27T01:21:38.236Z] [0mE: Halting system[0m
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.15.2
 - Commit SHA or Version used:  zephyr-v3.3.0-472-gb2512d2f534e

### LINKED ISSUE #55213: tests: lib: ringbuffer: libraries.ring_buffer fails
**Describe the bug**
The tests/lib/ringbuffer/libraries.ring_buffer fails

Observed for:
- nrf5340dk_nrf5340_cpunet

**To Reproduce**
1. have nrf5340dk_nrf5340_cpunet connected
2. go to your zephyr dir
3. call ./scripts/twister -T tests/lib/ringbuffer -p nrf5340dk_nrf5340_cpunet --device-testing --device-serial /dev/ttyACM0 -v --inline-logs
4. See console output with error

**Expected behavior**
Valid console output

**Impact**
Not clear

**Logs and console output**
```
[2023-02-25T00:53:37.137Z] [0mERROR   - E: ***** HARD FAULT *****[0m
[2023-02-25T00:53:37.137Z] [0mE:   Fault escalation (see below)[0m
[2023-02-25T00:53:37.137Z] [0mE: ***** BUS FAULT *****[0m
[2023-02-25T00:53:37.137Z] [0mE:   Precise data bus error[0m
[2023-02-25T00:53:37.137Z] [0mE:   BFAR Address: 0xfffffffe[0m
[2023-02-25T00:53:37.137Z] [0mE: r0/a1:  0x0100522d  r1/a2:  0x210037c9  r2/a3:  0x210037c8[0m
[2023-02-25T00:53:37.137Z] [0mE: r3/a4:  0x01009ac5 r12/ip:  0x21003848 r14/lr:  0x00000000[0m
[2023-02-25T00:53:37.137Z] [0mE:  xpsr:  0x21003600[0m
[2023-02-25T00:53:37.137Z] [0mE: Faulting instruction address (r15/pc): 0x00000000[0m
[2023-02-25T00:53:37.137Z] [0mE: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0[0m
[2023-02-25T00:53:37.137Z] [0mE: Current thread: 0x21000668 (idle)[0m
[2023-02-25T00:53:37.137Z] [0mE: Halting system[0m
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Toolchain Zephyr SDK 0.15.2
 - Commit SHA or Version used:  zephyr-v3.3.0-415-ga1e983fef049

### PR DESCRIPTION
**Pull request by anangl**
This is a follow-up to commit fe3b97a87f480eb473cd58cc1990a5845c2ca9c6.

This message should not be a warning, as it does not actually indicate that something potentially bad happened. On the contrary, it informs that conditions in which the anomaly 160 could occur were detected and the anomaly was prevented from occurring. There is no need for this message to appear in the default configuration (INFO level). In fact, the message would undesirably flood the console in some cases (like the kernel/mem_protect/stack_random test) and sometimes it would also require enlarging the stack of the idle thread (the function is called underneath k_cpu_idle()). Therefore, the logging level of this message is changed to DEBUG.

Fixes #55212.
Fixes #55213.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

File: soc/arm/nordic_nrf/nrf53/soc.c [hunk 1]
```diff
@@ -168,6 +161,24 @@ bool z_arm_on_enter_cpu_idle(void)
 
 	return true;
 }
+
+bool z_arm_on_enter_cpu_idle(void)
+{
+	bool ok_to_sleep = nrf53_anomaly_160_check();
+
+#if (LOG_LEVEL >= LOG_LEVEL_DBG)
```
Comment (nordic-krch) [inline soc/arm/nordic_nrf/nrf53/soc.c:169]: I don't think that you need this `#ifdef`. Tried to compile without and ROM/RAM is the same.

Comment (anangl) [reply soc/arm/nordic_nrf/nrf53/soc.c:169]: Yes. It looks like now, after moving the essential part of `z_arm_on_enter_cpu_idle()` to `nrf53_anomaly_160_check()`, gcc is able to optimize out the `suppress_message` variable when the message is not to be printed at all. It could not do it earlier, when the message handling was merged into the anomaly workaround code, so I added several such `#if`s. Then I reorganized the code a little to make it easier to read and I didn't check again the optimization.
But since this `#if` is not actually harmful and the code is quite clear, I'd rather keep it as it is now, just to not rely on optimization capabilities of compilers. Or do you foresee some issues that this `#if` may bring in the future?

**Review by nordic-krch — APPROVED** [review]

File: soc/arm/nordic_nrf/nrf53/soc.c (hunk 1 above)
Comment (nordic-krch) [reply soc/arm/nordic_nrf/nrf53/soc.c:169]: approved. I don't like ifdefs so if they can be avoided i'm all for it but i won't insist.
