### PR TITLE
tests: arm: sw_vector_table: enhance test configs for frdm_mcxa166

### LINKED ISSUE #92877: tests: tests/arch/arm/arm_irq_vector_table: frdm_mcxa166/mcxa166: failed: Timeout
**Describe the bug**
below case are failed
arch.arm.irq_vector_table.vector_table.arm_irq_vector_table

test is failed on v4.2.0-rc1-224-gb3ccee473ed6 on frdm_mcxa166/mcxa166
testcase path is tests/arch/arm/arm_irq_vector_table

see logs for details

**To Reproduce**
1. 
```
scripts/twister -p frdm_mcxa166/mcxa166  -T tests/arch/arm/arm_irq_vector_table -s arch.arm.irq_vector_table
```
or
```
# west twister -p frdm_mcxa166/mcxa166 -T tests/arch/arm/arm_irq_vector_table -s arch.arm.irq_vector_table
```
2. See error

```
Timeout
```

**Expected behavior**
test pass

**Impact**

**Logs and console output**

```
*** Booting Zephyr OS build v4.2.0-rc1-224-gb3ccee473ed6 ***
Running TESTSUITE arm_thread_swap
====================*** Booting Zephyr OS build v4.2.0-rc1-224-gb3ccee473ed6 ***
Running TESTSUITE vector_table
===================================================================
START - test_arm_irq_vector_table
Test Cortex-M IRQs installed directly in the vector table
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
isr0 ran!
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux ): posix
 - Toolchain (e.g Zephyr SDK): zephyr
 - Commit SHA or Version used: v4.2.0-rc1-224-gb3ccee473ed6

### PR DESCRIPTION
**Pull request by hakehuang**
irq 0 in frdm_mcxa166/276 are reserved can not used for testing. add a config to shift test irq, also add support for rt700

fixes: #92877, #92521

### CODE REVIEW

**Comment by hakehuang** [comment]
tests on frdm_mcxa166/frdm_mcxa276/mimxrt700_evk_cm33/mimxrt1180_evk_cm33
```
*** Booting Zephyr OS build v4.2.0-rc2-49-g732a3a5c6655 ***
Running TESTSUITE vector_table
===================================================================
START - test_arm_irq_vector_table
Test *** Booting Zephyr OS build v4.2.0-rc1-249-g2d939cac9283 ***
Running TESTSUITE vector_table
===================================================================
START - test_arm_irq_vector_table
Test Cortex-M IRQs installed directly in the vector table
isr0 ran!
isr1 ran!
isr2 ran!
 PASS - test_arm_irq_vector_table in 0.009 seconds
===================================================================
TESTSUITE vector_table succeeded

------ TESTSUITE SUMMARY START ------

SUITE PASS - 100.00% [vector_table]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.009 seconds
 - PASS - [vector_table.test_arm_irq_vector_table] duration = 0.009 seconds

------ TESTSUITE SUMMARY END ------

===================================================================
PROJECT EXECUTION SUCCESSFUL

```

File: tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 1]
```diff
@@ -13,7 +14,11 @@
  * Offset (starting from the beginning of the vector table)
  * of the location where the ISRs will be manually installed.
  */
+#ifndef CONFIG_ISR_OFFSET
 #define _ISR_OFFSET 0
+#else
+#define _ISR_OFFSET CONFIG_ISR_OFFSET
```
Comment (wearyzen) [inline tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c:17]: nit: its juts 3 boards so why not follow the [same approach](https://github.com/zephyrproject-rtos/zephyr/pull/92881/files#diff-e98d660a1f2482bf64b3af6ead5b2f77e0842498f12eeb906d3164c16dc3d9a4L17) as NORDIC?

Comment (hakehuang) [reply tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c:17]: @wearyzen you mean. 
https://github.com/zephyrproject-rtos/zephyr/blob/ce25bad2a5d491656986bd285a7adaf4db985da6/tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c#L154
there a two concerns for this:
1. NXP irq setting is not aligned over different soc series. there will be more and more variable in macros, which use a board config would be more clean.
2. I guess this would not be only NXP platform dedicated, other platform can apply the same logic without need to change the test source code.

File: tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 2]
```diff
@@ -242,7 +248,23 @@ const vth __irq_vector_table _irq_vector_table[] = {
...
-const vth __irq_vector_table _irq_vector_table[] = {isr0, isr1, isr2};
+
+#if defined(CONFIG_MCUX_OS_TIMER)
+extern void mcux_lpc_ostick_isr(void);
+#define TIMER_IRQ_NUM DT_IRQN(DT_INST(0, nxp_os_timer))
+#define TIMER_IRQ_HANDLER mcux_lpc_ostick_isr
+#define IRQ_VECTOR_TABLE_SIZE _ISR_OFFSET > TIMER_IRQ_NUM ? (_ISR_OFFSET + 3) : (TIMER_IRQ_NUM + 1)
+#else
+#define IRQ_VECTOR_TABLE_SIZE (_ISR_OFFSET + 3)
+#endif /* efined(CONFIG_MCUX_OS_TIMER)  */
```
Comment (JarmouniA) [inline tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c]:
```suggestion
#endif /* CONFIG_MCUX_OS_TIMER  */
```

File: tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c (hunk 1 above)
Comment (wearyzen) [reply tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c:17]: Not soc but using board macros CONFIG_BOARD_FRDM_MCXA166 CONFIG_BOARD_FRDM_MCXA276 BOARD_MIMXRT1180_EVK_MIMXRT1189_CM33 to define the _ISR_OFFSET and _irq_vector_table

but my comment was more of a nit to avoid the discrepancy in how the _ISR_OFFSET is being defined, I am ok with the current approach so nvm

File: tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c [hunk 3]
```diff
@@ -13,7 +14,11 @@
  * Offset (starting from the beginning of the vector table)
  * of the location where the ISRs will be manually installed.
  */
+#ifndef CONFIG_ISR_OFFSET
```
Comment (wearyzen) [inline tests/arch/arm/arm_irq_vector_table/src/arm_irq_vector_table.c]: CONFIG_ISR_OFFSET will always be defined so do we still need this?

**Review by wearyzen — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]
