### PR TITLE
drivers: sensor: meas: ms5837 supporting 02 and 30 variants via dt

### LINKED ISSUE #87870: MS5837 variant is not correctly chosen
**Describe the bug**
Both the MS5837-02BA01 and MS5837-30BA pressure sensors have the same id at Version PROM Word 0 programming register. For this reason the conversion of the pressure value for the 30BA is actually using the compensation function of the 02 variant instead of its own defined function giving erroneous pressure values. It is not possible to discriminate between the two variants during runtime.

A possible solution is to select the used variant via e.g. the compatibility property in dt.

**Expected behavior**
Conversions for both variants working as expected.

**Impact**
Pressure readings from the 30 variant are not usable.

### PR DESCRIPTION
**Pull request by ivanwagner**
This patch adds support via dt compatible property.

Fixes #87870

### CODE REVIEW

File: drivers/sensor/meas/ms5837/ms5837.c [hunk 1]
```diff
@@ -348,34 +348,26 @@ static int ms5837_init(const struct device *dev)
...
-	};										\
-											\
-	SENSOR_DEVICE_DT_INST_DEFINE(inst, ms5837_init, NULL,				\
-			      &ms5837_data_##inst, &ms5837_config_##inst, POST_KERNEL,	\
-			      CONFIG_SENSOR_INIT_PRIORITY, &ms5837_api_funcs);		\
-
-DT_INST_FOREACH_STATUS_OKAY(MS5837_DEFINE)
+#define MS5837_DEFINE(inst, type)                                                                  \
+	static struct ms5837_data ms5837_data_##inst = {                                           \
+		.comp_func = ms5837_compensate_##type                                              \
```
Comment (yperess) [inline drivers/sensor/meas/ms5837/ms5837.c:356]: If this is done statically (which I like a lot and is much better) it should go into the config not the data.

**Review by yperess — CHANGES_REQUESTED** [review]

File: drivers/sensor/meas/ms5837/ms5837.c (hunk 1 above)
Comment (ivanwagner) [reply drivers/sensor/meas/ms5837/ms5837.c]: Good point. I fixed it and pushed.

File: drivers/sensor/meas/ms5837/ms5837.c [hunk 2]
```diff
@@ -348,34 +349,25 @@ static int ms5837_init(const struct device *dev)
...
-											\
-	SENSOR_DEVICE_DT_INST_DEFINE(inst, ms5837_init, NULL,				\
-			      &ms5837_data_##inst, &ms5837_config_##inst, POST_KERNEL,	\
-			      CONFIG_SENSOR_INIT_PRIORITY, &ms5837_api_funcs);		\
-
-DT_INST_FOREACH_STATUS_OKAY(MS5837_DEFINE)
+#define MS5837_DEFINE(inst, type)                                                                  \
+	static struct ms5837_data ms5837_data_##inst;                                              \
+                                                                                                   \
+	static const struct ms5837_config ms5837_config_##inst = {                                 \
```
Comment (MaureenHelm) [inline drivers/sensor/meas/ms5837/ms5837.c:358]: These symbols need to include `type` in case there are instances of both compatibles in the devicetree.
```suggestion
	static struct ms5837_data ms5837_##type##_data_##inst;                                              \
                                                                                                   \
	static const struct ms5837_config ms5837_##type##_config_##inst = {                                 \
```

File: samples/sensor/ms5837/boards/nrf52840dk_nrf52840.overlay [hunk 3]
```diff
@@ -8,7 +8,7 @@
 	status = "okay";
 	clock-frequency = <I2C_BITRATE_STANDARD>;
 	ms5837@76 {
-		compatible = "meas,ms5837";
+		compatible = "meas,ms5837-02ba";
```
Comment (MaureenHelm) [inline samples/sensor/ms5837/boards/nrf52840dk_nrf52840.overlay:11]: Could you also add an instance of "meas,ms5837-30ba"?

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Thanks for the PR!

File: drivers/sensor/meas/ms5837/ms5837.c (hunk 2 above)
Comment (ivanwagner) [reply drivers/sensor/meas/ms5837/ms5837.c]: I added your suggestions and also adjusted the SENSOR_DEVICE_DT_INST_DEFINE call to the new names that include the type as well. Thank you.

File: samples/sensor/ms5837/boards/nrf52840dk_nrf52840.overlay (hunk 3 above)
Comment (ivanwagner) [reply samples/sensor/ms5837/boards/nrf52840dk_nrf52840.overlay:11]: I split everything in two distinct samples. It is unlikely that in a real-world application both sensors (used for different scopes) will be used on the same board at the same time.

**Review by yperess — DISMISSED** [review]

**Comment by ivanwagner** [comment]
I see that some checks are failing (twister tests). I am unable to reproduce it locally. Can anyone would be so kind to give me a hint on how to test this locally before I push further commits? Thank you.

**Comment by ivanwagner** [comment]
Ok now it looks good and checks have passed. @MaureenHelm can you take a look at it? Thank you very much

File: drivers/sensor/meas/ms5837/ms5837.c [hunk 4]
```diff
@@ -94,10 +95,14 @@ static void ms5837_compensate_30(const struct device *dev,
...
 	data->temperature -= Ti;
-	data->pressure =
-	    (((SENS * adc_pressure) / (1ll << 21)) - OFF) / (1ll << 13);
+	/* Result is in mbar * 10 but store result as mbar * 100 same as 02 sensor variant */
+	data->pressure = ((((SENS * adc_pressure) / (1ll << 21)) - OFF) / (1ll << 13)) * 10;
 }
 
+#endif
+
+#if DT_NODE_EXISTS(DT_INST(0, meas_ms5837_02ba))
```
Comment (MaureenHelm) [inline drivers/sensor/meas/ms5837/ms5837.c:104]: `DT_HAS_COMPAT_STATUS_OKAY`

File: samples/sensor/ms5837/boards/nrf52840dk_nrf52840.overlay (hunk 3 above)
Comment (ivanwagner) [reply samples/sensor/ms5837/boards/nrf52840dk_nrf52840.overlay]: No problem. I restored the samples as before and adjusted with the changes this patch provides.

File: drivers/sensor/meas/ms5837/ms5837.c [hunk 5]
```diff
@@ -45,6 +44,8 @@ static int ms5837_get_measurement(const struct device *dev, uint32_t *val,
 	return 0;
 }
 
+#if DT_NODE_EXISTS(DT_INST(0, meas_ms5837_30ba))
```
[the remark this answers is not in the document]
Comment (ivanwagner) [reply drivers/sensor/meas/ms5837/ms5837.c]: Ok done

**Review by yperess — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
Thanks!

**Comment by ivanwagner** [comment]
It is possible to backport this PR to v3.7-branch (backport-v3.7-branch)?

**Comment by kartben** [comment]
> It is possible to backport this PR to v3.7-branch (backport-v3.7-branch)?

As it stands, probably not IMO. It's actually a breaking change that this PR missed to document. Migration guide should be updated to indicate to people using the compatible that's been deleted and that will see their sensors just stop "lighting up" what they need to do. 
Would you be able to please send a follow-up PR to add the missing entry in the 4.2 migration guide? Thanks!

**Comment by ivanwagner** [comment]
Sure I will be happy to complete the migration guide for version 4.2. Can you point me to where should this be done? Regarding the breaking change, it's a breaking change as you say, what I miss is that people using versions prior to 3.7 (I should verify which one exactly) and upgrading to 3.7 (where I found the issue) won't realize that their sensor will measure different values (the bug I reported) without any warning. My change, even if breaking will avoid a successful compilation on 3.7 forcing the users to explicitly specify which sensor they are using. So in one way if it is left as it is, it will silently let a bug as this go through, on the other side it will force users to take action.
