### PR TITLE
drivers: counter: maxim_ds3231: Fix coverity issues

### LINKED ISSUE #59537: [Coverity CID: 321117] Use of 32-bit time_t in drivers/counter/maxim_ds3231.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c

Category: High impact quality
Function: `ds3231_counter_get_value`
Component: Drivers
CID: [321117](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=321117)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c#L767

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_Y2K38_SAFETY). ([CWE-197](http://cwe.mitre.org/data/definitions/197.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #59542: [Coverity CID: 321144] Use of 32-bit time_t in drivers/counter/maxim_ds3231.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c#L1227

Category: High impact quality
Function: `ds3231_counter_set_alarm`
Component: Drivers
CID: [321144](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=321144)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c

```
1229                     .user_data = alarm_cfg->user_data,
1230                     .flags = MAXIM_DS3231_ALARM_FLAGS_AUTODISABLE,
1231             };
1232     
1233             if (rc >= 0) {
1234                     data->counter_handler[id] = alarm_cfg->callback;
>>>     CID 321144:    (Y2K38_SAFETY)
>>>     A "time_t" value is stored in an integer with too few bits to accommodate it.  The expression "alarm.time" is cast to "uint32_t".
1235                     data->counter_ticks[id] = alarm.time;
1236                     rc = set_alarm(dev, id, &alarm);
1237             }
1238     
1239     out_locked:
1240             k_sem_give(&data->lock);
1221                     }
1222             } else {
1223                     when = alarm_cfg->ticks;
1224             }
1225     
1226             struct maxim_ds3231_alarm alarm = {
>>>     CID 321144:    (Y2K38_SAFETY)
>>>     A "time_t" value is stored in an integer with too few bits to accommodate it.  The expression "when" is cast to "uint32_t".
1227                     .time = (uint32_t)when,
1228                     .handler = counter_alarm_forwarder,
1229                     .user_data = alarm_cfg->user_data,
1230                     .flags = MAXIM_DS3231_ALARM_FLAGS_AUTODISABLE,
1231             };
1232     
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_Y2K38_SAFETY). ([CWE-197](http://cwe.mitre.org/data/definitions/197.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #59543: [Coverity CID: 321152] Use of 32-bit time_t in drivers/counter/maxim_ds3231.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c#L869

Category: High impact quality
Function: `sync_prep_write`
Component: Drivers
CID: [321152](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=321152)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c#L869

```
863      }
864      data->new_sp.rtc.tv_sec = when;
865      data->new_sp.rtc.tv_nsec = 0;
866     
867      data->sync_state = SYNCSM_FINISH_WRITE;
868      k_timer_start(&data->sync_timer, K_MSEC(rem_ms), K_NO_WAIT);
>>>     CID 321152:  High impact quality  (Y2K38_SAFETY)
>>>     A "time_t" value is stored in an integer with too few bits to accommodate it.  The expression "when" is cast to "uint32_t".
869      LOG_INF("sync %u in %u ms after %u", (uint32_t)when, rem_ms, syncclock);
870     }
871     
872     static void sync_finish_write(const struct device *dev)
873     {
874      struct ds3231_data *data = dev->data;
```

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_Y2K38_SAFETY). ([CWE-197](http://cwe.mitre.org/data/definitions/197.html))

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #59545: [Coverity CID: 321166] Use of 32-bit time_t in drivers/counter/maxim_ds3231.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c

Category: High impact quality
Function: `decode_rtc`
Component: Drivers
CID: [321166](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=321166)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c#L436

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_Y2K38_SAFETY). ([CWE-197](http://cwe.mitre.org/data/definitions/197.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### LINKED ISSUE #59546: [Coverity CID: 321183] Use of 32-bit time_t in drivers/counter/maxim_ds3231.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c

Category: High impact quality
Function: `sync_finish_write`
Component: Drivers
CID: [321183](https://scan9.scan.coverity.com/reports.htm#v29726/p12996/mergedDefectId=321183)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/ce3317d03e46e1a218af3e712383d9216c48a992/drivers/counter/maxim_ds3231.c#L917

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/reports.htm#v29271/p12996.

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_Y2K38_SAFETY). ([CWE-197](http://cwe.mitre.org/data/definitions/197.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the CODEOWNERS file.

### PR DESCRIPTION
**Pull request by ttmut**
maxim_ds3231 driver stores the current time in a 64-bit time_t variable before casting it to an unsigned 32-bit integer, resulting in CWE-197 numeric truncation violations. Since counter API cannot return 64-bit values, work around these violations by explicitly performing the truncations.

Fixes #59546
Fixes #59545
Fixes #59543
Fixes #59542
Fixes #59537

### CODE REVIEW

File: drivers/counter/maxim_ds3231.c [hunk 1]
```diff
@@ -417,10 +415,21 @@ static int encode_alarm(uint8_t *ap,
 	return 0;
 }
 
+static inline uint32_t time_t_to_ticks(time_t t)
+{
+	if (sizeof(t) == sizeof(int64_t)) {
+		if (t < 0) {
+			return ((t + UINT64_MAX + 1) & UINT32_MAX);
+		}
+	}
```
Comment (henrikbrixandersen) [inline drivers/counter/maxim_ds3231.c:424]: I must admit, that I do not understand the intent of the above code? Could you please explain it a bit, perhaps add a comment?

Comment (ttmut) [reply drivers/counter/maxim_ds3231.c:424]: Thanks for the feedback. I was trying to cast `time_t (int64_t)` to `uint32_t` without triggering truncation violations. Though I realize now that the addition is unnecessary and would probably cause integer overflow warnings. Apologies for the confusion.

**Review by henrikbrixandersen — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
