### PR TITLE
Fix support for Pi Pico and C11

### LINKED ISSUE #54190: RP2040 cannot be compiled with C11 enabled
**Describe the bug**
When compiling a project targeting RP2040 and C11 enabled, errors occur because both assert.h (from the std lib) and config_autogen.h (from zephyr) define `static_assert` as a macro, with the one in config_autogen not being guarded.

**To Reproduce**
1. Set C11 flag on any project (`set_property(TARGET tgt PROPERTY C_STANDARD 11)`)
2. mkdir build; cd build
3. cmake -DBOARD=rpi_pico
4. make
5. See error

**Expected behavior**
No compiler error

**Impact**
C11 cannot be used for RP2040 projects

**Environment (please complete the following information):**
 - OS: Linux and Windows
 - Toolchain: Zephyr SDK 0.15.0
 - Zephyr 3.1 (Still occurs in 3.2)

### PR DESCRIPTION
**Pull request by ThadHouse**
Currently if C11 or higher is enabled, many files fail to compile because they include assert.h and config_autogen.h, which define conflicting copies of static_assert. Disable the one in the hal if the other is found.

Closes https://github.com/zephyrproject-rtos/zephyr/issues/54190

Signed-off-by: Thad House <thadhouse1@gmail.com>

### CODE REVIEW

File: modules/hal_rpi_pico/pico/config_autogen.h [hunk 1]
```diff
@@ -22,7 +22,11 @@
  * BUILD_ASSERT is included through toolchain.h.
  */
 #include <zephyr/toolchain.h>
+#ifndef __cplusplus
+#ifndef static_assert
```
Comment (stephanosio) [inline modules/hal_rpi_pico/pico/config_autogen.h:26]: nested ifdefs should be avoided when possible.

```suggestion
#if !defined(__cplusplus) && !defined(static_assert)
```

**Review by stephanosio — COMMENTED** [review]
Technically, `static_assert` is only available in ~~C++98~~C++11 and above, and it is a keyword (i.e. not a macro) in C23, but encoding all these details here would be an overkill given that both C++98 and C23 are very niche use cases.

In the long term, we want to detect these compiler features during the configuration step in the build system and expose them to the code (e.g. `COMPILER_HAS_STATIC_ASSERT`)

**Comment by yonsch** [comment]
@ThadHouse Could you rebase and address the change request?

**Comment by klaasdannen** [comment]
@ThadHouse are you still working on this PR?

**Comment by ThadHouse** [comment]
Sorry, I've been busy. I'll work on getting it updated this weekend.

**Comment by yonsch** [comment]
@ThadHouse Ping?

**Comment by ThadHouse** [comment]
Sorry its taken so long, I was swapped with work. Just pushed against the newest main.

**Comment by cfriedt** [comment]
It would be really great if there were some information on how to reproduce the problem. From the way it's phrased, it really sounds like a bug, and probably should have been filed as one.

https://github.com/zephyrproject-rtos/zephyr/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by ThadHouse** [comment]
Ok. Created one

https://github.com/zephyrproject-rtos/zephyr/issues/54190

**Review by stephanosio — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]
