### PR TITLE
samples: mesh_badge: fix BT mesh provisioning error

### LINKED ISSUE #54198: reel board: Mesh badge demo fails to send BT Mesh message
**Describe the bug**
When flashing and setting up two reel boards with the mesh badge demo (samples/boards/reel-board/mesh_badge), sending a message via BT Mesh on button press fails with "Sending Failed!" on the reel board display.

Debug Log shows the error:
`[00:00:55.785,339] <err> bt_mesh_access: bt_mesh_model_send: Model not bound to AppKey 0x0000`

I am building the sample with the most recent main branch (5a62f2592f) and Zephyr SDK 0.16.0-beta1:
`west build -b reel_board_v2 samples/boards/reel_board/mesh_badge/ -p && west flash`

Connecting and sending the Name via the nRF-Connect works as described in the sample description. Just the BT Mesh send fails.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? 2x reel_board_v2
 - What have you tried to diagnose or workaround this issue?
 I have tried with v3.2.0 and v3.1.0. v3.2.0 seems broken as well, in v3.1.0 the demo works for me.
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
The behavior has been introduced in between Zephyr v3.1.0 and v3.2.0. I'm not sure how I can narrow it down further with a high effort.

**To Reproduce**
1. west build -b reel_board_v2 samples/boards/reel_board/mesh_badge/
2. west flash (for two reel boards)
3. Connect with the nRF Connect App as described and set up the name
4. Disconnect from the nRF Connect App
5. BT Mesh network got successfully created
6. Press the button 'a Button' on one of the boards

**Expected behavior**
The two boards should communicate with each other on a button press, showing the name of the sending board in the receiving boards display.

**Impact**
BT Mesh feature of the Demo does not work

**Logs and console output**
```
*** Booting Zephyr OS build v3.3.0-rc1-2-g5a62f2592ffe ***
Starting Board Demo
[00:00:00.879,760] <inf> fs_nvs: nvs_mount: 8 Sectors of 4096 bytes
[00:00:00.879,791] <inf> fs_nvs: nvs_mount: alloc wra: 0, ed8
[00:00:00.879,791] <inf> fs_nvs: nvs_mount: data wra: 0, 1b8
[00:00:00.884,368] <inf> bt_hci_core: hci_vs_init: HW Platform: Nordic Semiconductor (0x0002)
[00:00:00.884,399] <inf> bt_hci_core: hci_vs_init: HW Variant: nRF52x (0x0002)
[00:00:00.884,429] <inf> bt_hci_core: hci_vs_init: Firmware: Standard Bluetooth controller (0x00) Version 3.2 Build 99
[00:00:00.884,796] <inf> bt_hci_core: bt_init: No ID address. App must call settings_load()
Bluetooth initialized
Mesh initialized
[00:00:00.895,965] <inf> bt_hci_core: bt_dev_show_info: Identity: EB:7C:3B:78:30:F1 (random)
[00:00:00.895,996] <inf> bt_hci_core: bt_dev_show_info: HCI: version 5.3 (0x0c) revision 0x0000, manufacturer 0x05f1
[00:00:00.896,026] <inf> bt_hci_core: bt_dev_show_info: LMP: version 5.3 (0x0c) subver 0xffff
Already provisioned
Board started
Button pressed
Button released
[00:00:06.972,442] <err> bt_mesh_access: bt_mesh_model_send: Model not bound to AppKey 0x0000
motion!
```

**Environment:**
 - OS: Linux
 - Toolchain: Zephyr SDK 0.16.0-beta1
 - Commit SHA or Version used: 5a62f2592f

**Additional context**
-

### PR DESCRIPTION
**Pull request by jonas-rem**
The BT Mesh Configuration Client API is used in an asynchronous manner and the app key was not added before attempt binding it to mesh models. This caused the binding functions to fail and resulted in a fail when trying to to send mesh messages.

This commit registers a callback that is called when the app key is assigned. After this callback is called, the binding functions are called.

This PR fixes #54198 

Signed-off-by: Jonas Remmert <j.remmert@phytec.de>

### CODE REVIEW

**Review by jhedberg — CHANGES_REQUESTED** [review]
Thanks for finding the root cause and coming up with a fix proposal! A couple of thoughts:

- Note that printk() doesn’t automatically add a line terminator (new line character). You need to add that yourself. 
- Would it not have been simpler to make the call synchronous, by passing a non-NULL status pointer as the last parameter?

**Comment by PavelVPV** [comment]
> * Would it not have been simpler to make the call synchronous, by passing a non-NULL status pointer as the last parameter?

This won't work because underlying layers (transport sar and network loopback) run on the system workqueue. So what you get is a timeout error in the first call and after the timeout the messages will be processed.

File: samples/boards/reel_board/mesh_badge/src/mesh.c [hunk 1]
```diff
@@ -569,14 +609,20 @@ static void start_mesh(struct k_work *work)
...
 	err = provision_and_configure();
+
 	if (err < 0) {
-		board_show_text("Starting Mesh Failed", false,
-				K_SECONDS(2));
+		show_mesh_status(false, 0);
+	}
+}
+
+void show_mesh_status(bool mesh_started_ok, int addr)
```
Comment (PavelVPV) [inline samples/boards/reel_board/mesh_badge/src/mesh.c:618]: Could you please move this function up to its forward declaration? We try to avoid to avoid forward declaration unless it is impossible to avoid it.

And could you convert this function to static because it is only used in this file?

File: samples/boards/reel_board/mesh_badge/src/mesh.c [hunk 2]
```diff
@@ -76,7 +78,67 @@ BT_MESH_HB_CB_DEFINE(hb_cb) = {
...
+
+	/* Add model subscription */
+	err = bt_mesh_cfg_cli_mod_sub_add_vnd(NET_IDX, addr, addr, GROUP_ADDR,
+				    MOD_LF, BT_COMP_ID_LF, NULL);
+	if (err) {
+		printk("Failed to add subscription (err %d)", err);
+	}
+
+	err = bt_mesh_cfg_cli_mod_pub_set_vnd(NET_IDX, addr, addr, MOD_LF,
+			BT_COMP_ID_LF, &pub, NULL);
```
Comment (PavelVPV) [inline samples/boards/reel_board/mesh_badge/src/mesh.c:127]: Looks like this line and some other lines above are not aligned correctly.

File: samples/boards/reel_board/mesh_badge/src/mesh.c [hunk 3]
```diff
@@ -76,7 +78,67 @@ BT_MESH_HB_CB_DEFINE(hb_cb) = {
...
+		.period = BT_MESH_PUB_PERIOD_SEC(10),
+	};
+	int err;
+
+	/* Bind to vendor model */
+	err = bt_mesh_cfg_cli_mod_app_bind_vnd(NET_IDX, addr, addr, APP_IDX,
+				MOD_LF, BT_COMP_ID_LF, NULL);
+	if (err) {
+		printk("Failed to bind to vendor model (err %d)", err);
+	}
```
Comment (PavelVPV) [inline samples/boards/reel_board/mesh_badge/src/mesh.c:98]: Perhaps in case of failure, you could set some boolean variable to false and then pass it to `show_mesh_status`. The rest configuration could be omitted in this case:
```
	bool res = true;

	...

	if (err) {
		printk("Failed to bind to vendor model (err %d)", err);
		res = false;
		goto end;
	}

	...

	printk("Configuration complete\n");
end:
	show_mesh_status(res, addr);
```

**Review by PavelVPV — COMMENTED** [review]
Looks good. Since it is a self-configuration, the approach should work because most of the rest configuration messages are unsegmented (except model publication) and also don't depend on each other.

I just have a couple of stylish comments.

File: samples/boards/reel_board/mesh_badge/src/mesh.c [hunk 4]
```diff
@@ -76,7 +76,94 @@ BT_MESH_HB_CB_DEFINE(hb_cb) = {
...
+		printk("Failed to add subscription (err %d)\n", err);
+		err = false;
+		goto end;
+	}
+
+	err = bt_mesh_cfg_cli_mod_pub_set_vnd(NET_IDX, addr, addr, MOD_LF,
+				BT_COMP_ID_LF, &pub, NULL);
+	if (err) {
+		printk("Failed to set publication (err %d)\n", err);
+		err = false;
```
Comment (PavelVPV) [inline samples/boards/reel_board/mesh_badge/src/mesh.c:150]: No need to change `err`, `show_mesh_status` can be called like this: `show_mesh_status(err == 0, addr)`.

**Comment by jremmert-phytec-iot** [comment]
> Thanks for finding the root cause and coming up with a fix proposal! A couple of thoughts:
> 
> * Note that printk() doesn’t automatically add a line terminator (new line character). You need to add that yourself.
> * Would it not have been simpler to make the call synchronous, by passing a non-NULL status pointer as the last parameter?

@PavelVPV elaborated on both variants a) synchronous call from another thread context, b) using the callback,  in the linked issue. I thought b) is easier to understand and opted for it.

File: samples/boards/reel_board/mesh_badge/src/mesh.c (hunk 2 above)
Comment (jremmert-phytec-iot) [reply samples/boards/reel_board/mesh_badge/src/mesh.c]: fixed

File: samples/boards/reel_board/mesh_badge/src/mesh.c (hunk 4 above)
Comment (jremmert-phytec-iot) [reply samples/boards/reel_board/mesh_badge/src/mesh.c:150]: Oh, right, that is easier, will change.

**Review by PavelVPV — DISMISSED** [review]

**Review by Andrewpini — DISMISSED** [review]
LGTM 👍

**Review by jhedberg — DISMISSED** [review]

**Comment by jremmert-phytec-iot** [comment]
Rebased on current main.

**Review by PavelVPV — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
