### PR TITLE
USB: Coverity fixes

### LINKED ISSUE #20836: [Coverity CID :205776] Error handling issues in drivers/usb/device/usb_dc_native_posix.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/usb/device/usb_dc_native_posix.c

Category: Error handling issues
Function: `usb_dc_ep_write`
Component: Drivers
CID: 205776

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20837: [Coverity CID :205777] Error handling issues in drivers/usb/device/usb_dc_native_posix.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/usb/device/usb_dc_native_posix.c

Category: Error handling issues
Function: `usb_dc_ep_write`
Component: Drivers
CID: 205777

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20838: [Coverity CID :205790] Null pointer dereferences in drivers/usb/device/usb_dc_native_posix.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/usb/device/usb_dc_native_posix.c

Category: Null pointer dereferences
Function: `usb_dc_ep_read_wait`
Component: Drivers
CID: 205790

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20839: [Coverity CID :205813] Error handling issues in drivers/usb/device/usb_dc_native_posix.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/usb/device/usb_dc_native_posix.c

Category: Error handling issues
Function: `handle_usb_data`
Component: Drivers
CID: 205813

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20840: [Coverity CID :205821] Error handling issues in drivers/usb/device/usb_dc_native_posix.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/usb/device/usb_dc_native_posix.c

Category: Error handling issues
Function: `usbip_skip_setup`
Component: Drivers
CID: 205821

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20841: [Coverity CID :205839] Error handling issues in drivers/usb/device/usb_dc_native_posix.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/usb/device/usb_dc_native_posix.c

Category: Error handling issues
Function: `handle_usb_data`
Component: Drivers
CID: 205839

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### LINKED ISSUE #20842: [Coverity CID :205787] Memory - corruptions in drivers/usb/device/usb_dc_native_posix_adapt.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/master/drivers/usb/device/usb_dc_native_posix_adapt.c

Category: Memory - corruptions
Function: `handle_usbip_unlink`
Component: Drivers
CID: 205787

Please fix or provide comments in coverity using the link:

https://scan9.coverity.com/reports.htm#v32951/p12996.

### PR DESCRIPTION
**Pull request by finikorg**
Fixing coverity bugs

Fixes #20842
Fixes #20836
Fixes #20837
Fixes #20838
Fixes #20839
Fixes #20841
Fixes #20840

### CODE REVIEW

**Comment by ioannisg** [comment]
@emob-nordic can you review this USB-related coverity fixes?

**Comment by emob-nordic** [comment]
> @emob-nordic can you review this USB-related coverity fixes?

Yeah, sorry I missed the notification for it. Will do it today.

File: drivers/usb/device/usb_dc_native_posix_adapt.c [hunk 1]
```diff
@@ -211,13 +211,13 @@ static void handle_usbip_submit(int connfd, struct usbip_header *hdr)
...
 {
-	struct usbip_unlink *req = &hdr->u.unlink;
 	u64_t setup_padding;
 	int read;
 
 	LOG_DBG("");
 
-	read = recv(connfd, req, sizeof(hdr->u), 0);
+	/* Need to read the whole structure */
+	read = recv(connfd, &hdr->u, sizeof(hdr->u), 0);
```
Comment (jfischer-phytec-iot) [inline drivers/usb/device/usb_dc_native_posix_adapt.c]: It the padding (L227) still necessary?

File: drivers/usb/device/usb_dc_native_posix.c [hunk 2]
```diff
@@ -351,8 +351,13 @@ int usb_dc_ep_write(const u8_t ep, const u8_t *const data,
 	}
 
 	if (USBIP_EP_ADDR2IDX(ep) == 0) {
-		usbip_send_common(ep, data_len);
-		usbip_send(ep, data, data_len);
+		if (!usbip_send_common(ep, data_len)) {
```
Comment (jfischer-phytec-iot) [inline drivers/usb/device/usb_dc_native_posix.c]: It is confusing, I would not expect the function (usbip_send_common) return bool here, what is the benefit to have bool instead of int?

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/device/usb_dc_native_posix.c [hunk 3]
```diff
@@ -570,15 +572,20 @@ int handle_usb_data(struct usbip_header *hdr)
...
 
 		/* Send queued data */
-		usbip_send_common(ep, usbip_ctrl.in_ep_ctrl[ep_idx].buf_len);
-		usbip_send(ep, usbip_ctrl.in_ep_ctrl[ep_idx].buf,
-			   usbip_ctrl.in_ep_ctrl[ep_idx].buf_len);
+		if (!usbip_send_common(ep, buf_len)) {
+			return -EIO;
+		}
+
+		if (usbip_send(ep, usbip_ctrl.in_ep_ctrl[ep_idx].buf,
```
Comment (emob-nordic) [inline drivers/usb/device/usb_dc_native_posix.c]: I would consider adding `u8_t *buf = usbip_ctrl.in_ep_ctrl[ep_idx].buf;`

File: drivers/usb/device/usb_dc_native_posix_adapt.c [hunk 4]
```diff
@@ -223,10 +235,8 @@ static void handle_usbip_unlink(int connfd, struct usbip_header *hdr)
 		return;
 	}
 
-	/* Read also padding */
-	read = recv(connfd, &setup_padding, sizeof(setup_padding), 0);
-	if (read != sizeof(setup_padding)) {
-		LOG_ERR("recv() failed: %s", strerror(errno));
+	if (!usbip_skip_setup()) {
```
Comment (emob-nordic) [inline drivers/usb/device/usb_dc_native_posix_adapt.c]: Could You please provide explanation in commit message why skip is necessary here?

File: drivers/usb/device/usb_dc_native_posix_adapt.c (hunk 1 above)
Comment (finikorg) [reply drivers/usb/device/usb_dc_native_posix_adapt.c]: Yes, it is needed

File: drivers/usb/device/usb_dc_native_posix.c (hunk 2 above)
Comment (finikorg) [reply drivers/usb/device/usb_dc_native_posix.c]: We could return number of bytes written or -1 but we need to check that we wrote exact number of bytes. The true indicates that there is no error and exact packet size is sent.

**Comment by dleach02** [comment]
Can we use the 'Fixes #nnn' syntax in the description so the associated issues can automatically be flagged and closed when this PR is merged?

File: drivers/usb/device/usb_dc_native_posix_adapt.c (hunk 4 above)
Comment (finikorg) [reply drivers/usb/device/usb_dc_native_posix_adapt.c]: I added comment, /* Read USB setup, not handled */
I do not know what really should I add more, the function is self-describing.

File: drivers/usb/device/usb_dc_native_posix.c (hunk 3 above)
Comment (finikorg) [reply drivers/usb/device/usb_dc_native_posix.c]: done this way

**Review by jfischer-no — APPROVED** [review]

**Review by eobalski — APPROVED** [review]

**Review by pabigot — COMMENTED** [review]
~I see I never submitted this.  I won't block for this because hey, closing seven issues, but I do think somebody should go back early in 2.1 and clean this up.~   Never mind; this cropped up in a browser tab and I thought it was accurate, but it seems it isn't.   I haven't looked at the rest closely enough to approve or reject.

File: drivers/usb/device/usb_dc_native_posix.c (hunk 2 above)
Comment (pabigot) [reply drivers/usb/device/usb_dc_native_posix.c]: Never mind: I had missed the change to the signature.  It'd be nice if error codes associated with the underlying send could be preserved, but this isn't wrong.
