### PR TITLE
env: ignore unset var

### LINKED ISSUE #16227: Zephyr env: unset var in conditional activation
**Describe the bug**
When loading the Zephyr environment on Linux, a variable is unset in a conditional activation.

**To Reproduce**
1. set -eu
2. source ${ZEPHYR_GIT_ROOT}/zephyr-env.sh
3. zephyr-env.sh: line 15: ZSH_VERSION: unbound variable

**Expected behavior**
`-u` treats unset variables as an error when performing parameter expansion. There should be no error even if `-u` is set. 

**Environment (please complete the following information):**
 - Ubuntu 16.04.6 LTS (xenial)
 - Zephyr master branch, commit `fc3270d`

### PR DESCRIPTION
**Pull request by metc**
Ignore the ZSH_VERSION variable is unset or null when substituted.

This commit fixes #16227.
See https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion and https://ss64.com/bash/set.html for more details on this patch.

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

File: zephyr-env.sh [hunk 1]
```diff
@@ -12,7 +12,7 @@
 #
 # Note: The version of zsh need to be 5.0.6 or above. Any versions below
 # 5.0.6 maybe encoutner errors when sourcing this script.
-if [ -n "$ZSH_VERSION" ]; then
+if [ -n "${ZSH_VERSION-}" ]; then
```
Comment (mbolivar) [inline zephyr-env.sh]: Shouldn't this be `${ZSH_VERSION:-}`?

Comment (metc) [reply zephyr-env.sh]: I tested this with bash and zsh 5.1. According to Bash `man` page:
> Omitting the colon results in a test only for a parameter that is unset.

My commit message was not correct. I updated it and changed the code to check for null as well (safer variant).

**Review by mbolivar — APPROVED** [review]
