### PR TITLE
ARM: Cortex-M: Fixing Context Stacking Error Reporting

### LINKED ISSUE #25612: ARM: Cortex-M: CPU is not reporting Explicit MemManage Stacking Errors correctly
**Describe the bug**
Currently, Cortex-M has a bug in error reporting of Stacking Errors that are not, additionally, Data Access Violation Errors. The utility macro, `IS_MPU_GUARD_VIOLATION()`, implements the wrong logic wrt the input `fault_addr `(faulting address).

**To Reproduce**
To reproduce this, we need to trigger a Stacking error that is not, additionally, a MemManage Data Access Violation Error (to do that we need to make sure that the stack overflow occurs because the CPU tries to stack an exception frame and _exactly this operation_ results in overflow). The Cortex-M fault mechanism will **assert**, complaining that the Stacking error is not due to a stack overflow.
 
**Expected behavior**
We expect the Cortex-M Core fault handing mechanism to not Assert when parsing processor memory violation faults.

**Impact**
Medium severity. There is definitely an error in the fault handing logic. Stack overflows are never missed (so it is not a very critical bug), however, the processor Asserts inside the fault handler. Only affects ARMv7-M architecture with HW_STACK_PROTECTION enabled.

**Screenshots or console output**
See #25348 , this contains an error log showing the assert statement being hit.

**Additional context**
- Needs backporting to LTS.
- Needs test coverage

### PR DESCRIPTION
**Pull request by ioannisg**
- Fix the logic in IS_MPU_GUARD_VIOLATION macro
- Add a CortexM-specific test case to verify the behavior

Fixes #25612

### CODE REVIEW

**Review by tyrantlizard77 — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c [hunk 1]
```diff
@@ -165,6 +176,39 @@ void test_arm_interrupt(void)
...
+	/* Trigger an interrupt to cause the stacking error */
+	NVIC_ClearPendingIRQ(i);
+	NVIC_EnableIRQ(i);
+	NVIC_SetPendingIRQ(i);
+
+	/* Set test flag so the IRQ handler executes the appropriate case. */
+	test_flag = 4;
+
+	/* Manually set PSP almost at the bottom of the stack. An exception
+	 * entry will make PSP decent below the limit and into the MPU guard
```
Comment (stephanosio) [inline tests/arch/arm/arm_interrupt/src/arm_interrupt.c:199]:
```suggestion
	 * entry will make PSP descend below the limit and into the MPU guard
```

File: tests/arch/arm/arm_interrupt/README.txt [hunk 2]
```diff
@@ -6,9 +6,14 @@ Description:
 
 The first test verifies that we can handle system fault conditions
 while running in handler mode (i.e. in an ISR). Only for ARM
-Cortex-M targets. The test also verifies the behavior of the
-spurious interrupt handler, as well as the ARM spurious exception
-handler.
+Cortex-M targets. The test also verifies
+- the behavior of the spurious interrupt handler, as well as the
```
Comment (stephanosio) [inline tests/arch/arm/arm_interrupt/README.txt:10]:
```suggestion
Cortex-M targets.

The test also verifies:
- the behavior of the spurious interrupt handler, as well as the
```

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c [hunk 3]
```diff
@@ -165,6 +176,39 @@ void test_arm_interrupt(void)
 #endif
 #endif
 
+#if defined(CONFIG_HW_STACK_PROTECTION)
+	/*
+	 * Simulate a stacking error that is caused explicitly by the
+	 * exception entry context stacking, to verify that the CPU can
+	 * correctly report stacking  errors that are not also Data
```
Comment (stephanosio) [inline tests/arch/arm/arm_interrupt/src/arm_interrupt.c:183]:
```suggestion
	 * correctly report stacking errors that are not also Data
```

**Review by stephanosio — DISMISSED** [review]

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c [hunk 4]
```diff
@@ -165,6 +176,39 @@ void test_arm_interrupt(void)
...
+
+	__disable_irq();
+
+	/* Trigger an interrupt to cause the stacking error */
+	NVIC_ClearPendingIRQ(i);
+	NVIC_EnableIRQ(i);
+	NVIC_SetPendingIRQ(i);
+
+	/* Set test flag so the IRQ handler executes the appropriate case. */
+	test_flag = 4;
```
[the remark this answers is not in the document]
Comment (stephanosio) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c:196]: Ah, I see that `arm_isr_handler` does `test_flag++` at the top, so `test_flag = 4;` is correct.

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c (hunk 1 above)
Comment (ioannisg) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c:199]: will fix, thanks

File: tests/arch/arm/arm_interrupt/README.txt (hunk 2 above)
Comment (ioannisg) [reply tests/arch/arm/arm_interrupt/README.txt:10]: will apply this, too

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c (hunk 3 above)
Comment (ioannisg) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c:183]: ok

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (ioannisg) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c:196]: Yeah, this test starts getting a bit messy - I recognize it. Maybe I can re-write it for 2.4 release, to make it easier for people to read.

**Review by carlescufi — APPROVED** [review]

File: tests/arch/arm/arm_interrupt/src/arm_interrupt.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (MaureenHelm) [reply tests/arch/arm/arm_interrupt/src/arm_interrupt.c:196]: I had the same question initially too, before I saw the `test_flag++`
