### PR TITLE
arch: arm: mpu: Use temporary MPU mapping while reprogramming NXP MPU

### LINKED ISSUE #20595: tests/arch/arm/arm_thread_swap failed on frdm_k64f board.
**Describe the bug**
arch.arm.swap.common.no_optimizations and arch.arm.swap.common.fp_sharing.no_optimizations test cases failed on frdm_k64f board, there is nothing output int the handler.log.

**To Reproduce**
1. sanitycheck -p frdm_k64f --device-testing  --device-serial /dev/ttyACM0 
     -T tests/arch/arm/arm_thread_swap
2. See error and the handler.log

**Screenshots or console output**
sanitycheck -p frdm_k64f --device-testing  --device-serial /dev/ttyACM0 
 -T tests/arch/arm/arm_thread_swap
Renaming output directory to /home/ztest/work/zephyrproject/zephyr/sanity-out.2
JOBS: 40
Building initial testcase list...
4 test configurations selected, 0 configurations discarded due to filters.
Adding tasks to the queue...

frdm_k64f                 tests/arch/arm/arm_thread_swap/arch.arm.swap.common.no_optimizations FAILED: N/A

        see: sanity-out/frdm_k64f/tests/arch/arm/arm_thread_swap/arch.arm.swap.common.no_optimizations/handler.log
total complete:    2/   4  50%  skipped:    0, failed:    1
frdm_k64f                 tests/arch/arm/arm_thread_swap/arch.arm.swap.common.fp_sharing.no_optimizations FAILED: N/A

        see: sanity-out/frdm_k64f/tests/arch/arm/arm_thread_swap/arch.arm.swap.common.fp_sharing.no_optimizations/handler.log
total complete:    4/   4  100%  skipped:    0, failed:    2
2 of 4 tests passed (50.00%), 2 failed, 0 skipped with 0 warnings in 121.41 seconds
In total 4 test cases were executed on 1 out of total 212 platforms (0.47%)

Hardware distribution summary:

frdm_k64f (None): 4

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr-sdk-0.10.3
 - Commit ID: 02977563

### PR DESCRIPTION
**Pull request by dleach02**
Race conditions exist when remapping the NXP MPU. When writing the
start, end, or attribute registers of a MPU descriptor, the hardware
will automatically clear the region's valid bit. If that region gets
accessed before the code is able to set the valid bit, the core will
fault.

Issue #20595 revealled this problem with the code in region_init()
when the compiler options are set to no optimizations. The code
generated by the compiler put local variables on the stack and then
read those stack based variables when writing the MPU descriptor
registers. If that region mapped the stack a memory fault would occur.
Higher compiler optimizations would store these local variables in
CPU registers which avoided the memory access when programming the
MPU descriptor.

Because the NXP MPU uses a logic OR operation of the MPU descriptors,
the fix uses the last descriptor in the MPU hardware to remap all of
dynamic memory for access instead of the first of the dynamic memory
descriptors as was occuring before. This allows reprogramming of the
primary discriptor blocks without having a memory fault. After all
the dynamic memory blocks are mapped, the unused blocks will have
their valid bits cleared including this temporary one, if it wasn't
alread changed during the mapping of the current set.

Fixes #20595

Signed-off-by: David Leach <david.leach@nxp.com>

### CODE REVIEW

**Review by ioannisg — CHANGES_REQUESTED** [review]
Thanks so much @dleach02 for looking into this, I've been struggling with this failure for some time.
 I agree with the idea of the solution, but I have 2 comments, besides some minor style comments I 've left already.

1. I think it is great idea to use temporarily the last available region index to program all SRAM with the basic permissions, to prevent from transitive race condition issues while reprogramming. It is true that the last regions index will either be overwritten by the MPU re-programming or it will be cleared as unused.

2. However, you should probably _not_ skip re-initializing the `sram_region ` at line 339, you should just do region_init for both the sram_region and last-region-index.
The reason is that I don't like to **depend** on `mpu_sram_partitioning()` function to program the region at index `sram_region`, it feels too much error prone. I would rather see the sram_region to be reset at the beginning of mpu_configure_dynamic_regions, and later be re-adjusted to properly enforce a GUARD area.

3. I wonder, now, if you are going to do this, do we really need the irq_lock and unlock on lines 338-341? I.e. if we have the last region index programmed before resetting the sram_region, and since we have the OR rule, we probably don't need to lock/unlock. So I'd remove it (if it is not needed, better to remove it so we do not "hide" other potential race condition bugs that could be there but we just don't see them due to the irq locking)

**Comment by dleach02** [comment]
@ioannisg, I understand the concerns and had a similar conversation with @MaureenHelm. I'll make the change to be safe, but my observation is that the higher level code that is creating the new memory mappings for dynamic memory is creating a regions list that include the following:

- Thread memory domain(s)
- Thread stack
- stack guard

Now assuming every thread has a stack guard, this mapping would always split the RAM block up in the NXP implementation. So one question I have is do we have this situation where a thread doesn't have a stack guard while others do? If we can have the case where one request to z_arm_configure_dynamic_mpu_regions() doesn't include the stack guard then your concern is warranted.

I also note that with the current implementation, if we don't have stack guards enabled then mapping dynamic regions on each z_arm_pendsv() doesn't really impact the MPU mappings since all of RAM is already mapped at init and all the thread switching is doing now is the memory domain(s) and the thread stack, which are already mapped as part of the init.

I also have some other observations/questions around MPU usage in Zephyr but will bring them up in a different forum.

File: arch/arm/core/aarch32/cortex_m/mpu/nxp_mpu.c [hunk 1]
```diff
@@ -327,16 +327,32 @@ static int mpu_configure_dynamic_mpu_regions(const struct k_mem_partition
...
-	 * re-programming perform access in those areas.
+	 * To avoid the race condition a temporary descriptor is set to enable
+	 * access to all of memory before the call to mpu_configure_regions()
+	 * to configure the dynamic memory regions. After, the temporary
+	 * descriptor is invalidated if the mpu_configure_regions() didn't
+	 * overwrite it.
 	 */
 	key = irq_lock();
-	region_init(mpu_config.sram_region, (const struct nxp_mpu_region *)
+	/* Use last descripto region as temporary descriptor */
```
[the remark this answers is not in the document]
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/nxp_mpu.c]: ok

File: arch/arm/core/aarch32/cortex_m/mpu/nxp_mpu.c [hunk 2]
```diff
@@ -327,16 +327,32 @@ static int mpu_configure_dynamic_mpu_regions(const struct k_mem_partition
...
+	 * Programming the NXP MPU has to be done with care to avoid race
+	 * conditions that will cause memory faults. The NXP MPU is composed
+	 * of a number of memory region descriptors. The number of descriptors
+	 * varies depending on the SOC. Each descriptor has a start addr, end
+	 * addr, attribute, and valid. When the MPU is enabled, access to
+	 * memory space is checked for access protection errors through an
+	 * OR operation of all of the valid MPU descriptors.
+	 *
+	 * Writing the start/end/attribute descriptor register will clear the
+	 * valid bit for that discriptor. This presents a problem because if
```
[the remark this answers is not in the document]
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/nxp_mpu.c]: ok

**Comment by ioannisg** [comment]
@dleach02 
> the higher level code that is creating the new memory mappings for dynamic memory is creating a regions list that ...

This is absolutely correct

>Now assuming every thread has a stack guard, this mapping would always split the RAM block up in the NXP implementation. So one question I have is do we have this situation where a thread doesn't have a stack guard while others do? If we can have the case where one request to z_arm_configure_dynamic_mpu_regions() doesn't include the stack guard then your concern is warranted.

We can assume that when MPU_STACK_GUARD=y then all threads will have guards, that's correct.
I had a more careful look into the implementation of the `static int mpu_sram_partitioning()` and it seems that although the `sram_region `index is programmed, before the function returns, the contents of the `sram_region `are used _earlier_ in the function, to determine the `added_sram_region `and `adjusted_sram_region` struct contents, see for example
```
added_sram_region.end =
		mpu_config.mpu_regions[mpu_config.sram_region].end;
```

So I think this function expects the `sram_region `to have been re-set already. Therefore, it seems, now, to me that the change I requested is not only a matter of safe programming but actually needed. Please, take a look to double-check if my assumption is correct.

>I also note that with the current implementation, if we don't have stack guards enabled then mapping dynamic regions on each z_arm_pendsv() doesn't really impact the MPU mappings since all of RAM is already mapped at init and all the thread switching is doing now is the memory domain(s) and the thread stack, which are already mapped as part of the init.

No, this is not 100% accurate. We may have CONFIG_USERSPACE=y (user mode support) without MPU_STACK_GUARDS. In this scenario we still program memory domains and user thread stack at each pendSV (thread context switch).

> I also have some other observations/questions around MPU usage in Zephyr but will bring them up in a different forum.

Feel free to ask in the #arch_arm or #memory_protection slack channel :)

>Also, I'm not sure about your comment on removing the IRQ locks. They have been there for a long time for some reason so maybe we shouldn't touch that at this time?

Ok, so I have some memory that the irq_lock and irq_unlock, here, were added (maybe by @agansari or @MaureenHelm ) for the exact same reason; prevent IRQs from triggering while reprogramming the sram_region, i.e. address race-conditions due to IRQs firing asynchronously. Your findings seem to prove that under certain compiler optimization, even thread code execution can create a code-path that will find the MPU in a transitive/undefined state and create a fault (that's why you're temporarily programming the last region index). I believe that this re-programming will protect us even from IRQs firing; that's why I think it is worth trying to see if we can remove this temporary locking. If we can, i think it's good to do for 2 reasons
- performance
- stop hiding other possible bugs behind an irq locking

**Review by ioannisg — APPROVED** [review]
This is going to work, thanks @dleach02 , but i strongly recommend to try to see if we can remove the IRQ locking around lines 253-361.

**Comment by dleach02** [comment]
@ioannisg while I agree that we may not need the IRQ locking I'm hesitant in making that change in this PR. I think it is better to focus the PR on what I know is broken. I'm concerned that we would need some more focused testing around IRQ changes to ensure we don't break something by removing the IRQ locking.

I'll move my other discussions to the channels.

**Comment by ioannisg** [comment]
> @ioannisg while I agree that we may not need the IRQ locking I'm hesitant in making that change in this PR. I think it is better to focus the PR on what I know is broken. I'm concerned that we would need some more focused testing around IRQ changes to ensure we don't break something by removing the IRQ locking.
> 
> I'll move my other discussions to the channels.

Fine with me.

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c [hunk 3]
```diff
@@ -148,6 +148,20 @@ void z_arm_configure_dynamic_mpu_regions(struct k_thread *thread)
 	 * of the respective dynamic MPU regions to be programmed for
 	 * the given thread. The array of partitions (along with its
 	 * actual size) will be supplied to the underlying MPU driver.
+	 *
+	 * The drivers of what regions get configured are CONFIG_USERSPACE,
+	 * CONFIG_MPU_STACK_GUARD, and K_USER/supervisor threads.
+	 *
+	 * If CONFIG_USERSPACE then any Memory Domains associated with the
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:155]: better: CONFIG_USERSPACE=y, and adapt this, also, in more occurrences in the text
Alternatively: "if CONFIG_USERSPACE is defined..."

Comment (ioannisg) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:155]: Also: each thread is member of a single domain, so the correct wording is:
`...any application memory partitions associated with the thread get a defined region`

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c [hunk 4]
```diff
@@ -148,6 +148,20 @@ void z_arm_configure_dynamic_mpu_regions(struct k_thread *thread)
...
+	 * thread get a defined region.
+	 *
+	 * If CONFIG_USERSPACE and the thread is a K_USER thread the usermode
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:158]:
```suggestion
	 * If CONFIG_USERSPACE and the thread is a user thread, then a region is allocated for the user thread stack.
```

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c [hunk 5]
```diff
@@ -148,6 +148,20 @@ void z_arm_configure_dynamic_mpu_regions(struct k_thread *thread)
...
+	 * thread stack is defined a region.
+	 *
+	 * IF CONFIG_MPU_STACK_GUARD is defined the thread is a privilege
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:161]: ... **and** the thread is a supervisor thread

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c [hunk 6]
```diff
@@ -223,12 +242,19 @@ void z_arm_configure_dynamic_mpu_regions(struct k_thread *thread)
 
 #if defined(CONFIG_USERSPACE)
 	if (thread->arch.priv_stack_start) {
+		/* A K_USER thread has the stack guard protecting the privilege
+		 * stack and not on the usermode stack because the user mode
+		 * stack is already has its own defined memory region.
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:247]:
```suggestion
		 * stack already has its own defined memory region.
```

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c [hunk 7]
```diff
@@ -223,12 +242,19 @@ void z_arm_configure_dynamic_mpu_regions(struct k_thread *thread)
...
+		 */
 		guard_start = thread->arch.priv_stack_start - guard_size;
 
 		__ASSERT((uint32_t)&z_priv_stacks_ram_start <= guard_start,
-		"Guard start: (0x%x) below privilege stacks boundary: (0x%x)",
+		"Guard start: (0x%thread->stack_info.startx) below privilege stacks boundary: (0x%x)",
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:252]: This is probably not intended; revert?

**Review by ioannisg — CHANGES_REQUESTED** [review]
some comments on the added text

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 7 above)
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:252]: yeah... sorry

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 3 above)
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:155]: ok

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 4 above)
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:158]: Ok. But I kind of liked linking this to K_USER that is used in the thread creation

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c [hunk 8]
```diff
@@ -148,6 +148,20 @@ void z_arm_configure_dynamic_mpu_regions(struct k_thread *thread)
 	 * of the respective dynamic MPU regions to be programmed for
 	 * the given thread. The array of partitions (along with its
 	 * actual size) will be supplied to the underlying MPU driver.
+	 *
+	 * The drivers of what regions get configured are CONFIG_USERSPACE,
+	 * CONFIG_MPU_STACK_GUARD, and K_USER/supervisor threads.
+	 *
+	 * If CONFIG_USERSPACE then any Memory Domains associated with the
+	 * thread get a defined region.
```
Comment (andrewboie) [inline arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:156]: A memory domain is a collection of regions that the thread has access to, might be more precise to say that if the thread is a member of a memory domain, that any partitions defined within that domain get programmed to the MPU when the thread is context switched in.

**Review by tyrantlizard77 — COMMENTED** [review]
just a few comments, I don't envy you guys having to deal with the quirks of this MPU!

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 5 above)
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:161]: okay. But one inconsistency I ran across is that we use "priv_stack_start" in the name for the supervisor stack. Bugs me for some reason and part of the reason I changed up my language here.

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 7 above)
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c:252]: yep... clearly didn't compile before pushing.

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 8 above)
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c]: integrated some of this

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 5 above)
Comment (andrewboie) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c]: it's called that because it is used as the stack for temporary CPU privilege level elevations when handling syscalls from user mode.

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 6 above)
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c]: ok

File: arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c (hunk 5 above)
Comment (dleach02) [reply arch/arm/core/aarch32/cortex_m/mpu/arm_core_mpu.c]: thanks... was confusing to me when first looking at this but I understand now

**Review by tyrantlizard77 — APPROVED** [review]

**Review by ioannisg — APPROVED** [review]
