### PR TITLE
drivers: video: stm32_dcmipp: fixing driver initialization issue

### LINKED ISSUE #101219: video_stm32_dcmipp can't have other than pipe 0 configured if parallel interface is selected
### Describe the bug

There seems to be an issue (untested scenario), when pipe 1 or  2 is selected, thus 
`ret = HAL_DCMIPP_PARALLEL_SetConfig(&dcmipp->hdcmipp, &parallel_cfg);` gets called twice, as result failing during the second call
since driver is in `HAL_DCMIPP_STATE_READY` state already
The following WA works : 

```
diff --git a/drivers/video/video_stm32_dcmipp.c b/drivers/video/video_stm32_dcmipp.c
index da13d5d4aa9..99104192438 100644
--- a/drivers/video/video_stm32_dcmipp.c
+++ b/drivers/video/video_stm32_dcmipp.c
@@ -334,6 +334,12 @@ static int stm32_dcmipp_conf_parallel(const struct device *dev,
        parallel_cfg.ExtendedDataMode = DCMIPP_INTERFACE_8BITS;
        parallel_cfg.SynchroMode      = DCMIPP_SYNCHRO_HARDWARE;
 
+       if (dcmipp->hdcmipp.State == HAL_DCMIPP_STATE_READY) {
+               dcmipp->hdcmipp.State = HAL_DCMIPP_STATE_INIT;
+               LOG_WRN("DCMIPP Parallel interface already configured, WA applied");
+       }
+
+
        ret = HAL_DCMIPP_PARALLEL_SetConfig(&dcmipp->hdcmipp, &parallel_cfg);
        if (ret != HAL_OK) {
                LOG_ERR("Failed to configure DCMIPP Parallel interface");
```

### Regression

- [ ] This is a regression.

### Steps to reproduce

Configure stm32n6 dcmipp to have pipe 1 or 2 when parallel interface selected, observe driver failing to init

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by cornway**
when pipe 1 or 2 is selected and parallel bus is chosen HAL_DCMIPP_PARALLEL_SetConfig is failing, since it gets called twice and driver is already in HAL_DCMIPP_STATE_READY state

### CODE REVIEW

File: drivers/video/video_stm32_dcmipp.c [hunk 1]
```diff
@@ -356,8 +356,13 @@ static int stm32_dcmipp_conf_parallel(const struct device *dev,
...
 
-	hal_ret = HAL_DCMIPP_PARALLEL_SetConfig(&dcmipp->hdcmipp, &parallel_cfg);
-	if (hal_ret != HAL_OK) {
+	if (dcmipp->hdcmipp.State == HAL_DCMIPP_STATE_READY) {
+		dcmipp->hdcmipp.State = HAL_DCMIPP_STATE_INIT;
+		LOG_WRN("DCMIPP Parallel interface already configured, resetting it's state");
+	}
+
+	ret = HAL_DCMIPP_PARALLEL_SetConfig(&dcmipp->hdcmipp, &parallel_cfg);
+	if (ret != HAL_OK) {
```
Comment (avolmat-st) [inline drivers/video/video_stm32_dcmipp.c]: hal_ret variable is used here in order to indicate that this is a return value from the HAL_

File: drivers/video/video_stm32_dcmipp.c [hunk 2]
```diff
@@ -356,8 +356,13 @@ static int stm32_dcmipp_conf_parallel(const struct device *dev,
 	parallel_cfg.ExtendedDataMode = DCMIPP_INTERFACE_8BITS;
 	parallel_cfg.SynchroMode      = DCMIPP_SYNCHRO_HARDWARE;
 
-	hal_ret = HAL_DCMIPP_PARALLEL_SetConfig(&dcmipp->hdcmipp, &parallel_cfg);
-	if (hal_ret != HAL_OK) {
+	if (dcmipp->hdcmipp.State == HAL_DCMIPP_STATE_READY) {
+		dcmipp->hdcmipp.State = HAL_DCMIPP_STATE_INIT;
+		LOG_WRN("DCMIPP Parallel interface already configured, resetting it's state");
+	}
+
```
Comment (avolmat-st) [inline drivers/video/video_stm32_dcmipp.c]: It is known that the state is not going to be correct anyway, so I am not sure it is necessary to check the state before forcing the state. What about simply

```
dcmipp->hdcmipp.State = HAL_DCMIPP_STATE_INIT;
```
With maybe a comment on top of it explaining the reason why such state setting is necessary.

**Review by avolmat-st — CHANGES_REQUESTED** [review]
Thanks for the patch. Some minor points.

File: drivers/video/video_stm32_dcmipp.c (hunk 2 above)
Comment (avolmat-st) [reply drivers/video/video_stm32_dcmipp.c]: Thanks for the update.

What about removing this if statement and only keep the comment and State field setting as you did below ?
I don't think this check is really necessary.

Comment (cornway) [reply drivers/video/video_stm32_dcmipp.c]: Right, forgot to remove, let me fix that

**Review by avolmat-st — APPROVED** [review]
Thanks for the update. LGTM.

**Review by josuah — APPROVED** [review]

**Review by erwango — APPROVED** [review]
