### PR TITLE
Bluetooth: Host: Optimize hci buf alloc by calc actually require size

### LINKED ISSUE #37710: Bluetooth advert packet size is size of maximum packet not size of actual data
**Describe the bug**
Data is being added to an advert and scan response when Bluetooth advertising is starting on an nRF5340 with a single 128-bit UUID and short 25 character device name, this results in a packet of 259 bytes being sent to the network core even though the data is no-where near this long. The problem in the code, subsys\bluetooth\host\adv.c seems to be this:

```
/* Set legacy data using Extended Advertising HCI commands */
static int hci_set_ad_ext(struct bt_le_ext_adv *adv, uint16_t hci_op,
			  const struct bt_ad *ad, size_t ad_len)
{
	struct bt_hci_cp_le_set_ext_adv_data *set_data;
	struct net_buf *buf;
	int err;

	buf = bt_hci_cmd_create(hci_op, sizeof(*set_data));
	if (!buf) {
		return -ENOBUFS;
	}

	set_data = net_buf_add(buf, sizeof(*set_data));
	(void)memset(set_data, 0, sizeof(*set_data));

	err = set_data_add(set_data->data, BT_HCI_LE_EXT_ADV_FRAG_MAX_LEN,
			   ad, ad_len, &set_data->len);
	if (err) {
		net_buf_unref(buf);
		return err;
	}

	set_data->handle = adv->handle;
	set_data->op = BT_HCI_LE_EXT_ADV_OP_COMPLETE_DATA;
	set_data->frag_pref = BT_HCI_LE_EXT_ADV_FRAG_DISABLED;

	return bt_hci_cmd_send_sync(hci_op, buf, NULL);
}
```
Here, sizeof(*set_data) is 255 bytes and this full buffer is passed via HCI to the other side rather than the actual size of the data in the buffer

**Impact**
Annoyance, it can be worked around by allowing a larger buffer size on the network core application but is inefficient.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: GNU Arm Embedded Toolchain 10.3-2021.07
 - Commit SHA or Version used: nRF Connect SDK 1.6.1 which uses Zephyr 2.6

### PR DESCRIPTION
**Pull request by LingaoM**
By calculating the actual space required instead of using the maximum space, 
for `ad_stream`, add two related APIs for save and restore status to calculate the total space.

Fixes #37710

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

### CODE REVIEW

**Comment by Thalley** [comment]
I guess this fixes https://github.com/zephyrproject-rtos/zephyr/issues/37710

If we go down this road, should we not apply the same fix for periodic advertising as well?

File: subsys/bluetooth/host/adv.c [hunk 1]
```diff
@@ -524,27 +524,34 @@ static int hci_set_ad(uint16_t hci_op, const struct bt_ad *ad, size_t ad_len)
...
-
 	if (atomic_test_bit(adv->flags, BT_ADV_EXT_ADV)) {
 		max_data_size = BT_HCI_LE_EXT_ADV_FRAG_MAX_LEN;
 	} else {
 		max_data_size = BT_GAP_ADV_MAX_ADV_DATA_LEN;
 	}
 
+	if (total_len > max_data_size) {
+		return -EINVAL;
+	}
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:542]: Since we already check `if (total_len_bytes <= BT_HCI_LE_EXT_ADV_FRAG_MAX_LEN)` before calling this function, this check could be move into the non-ext `else` clause.

File: subsys/bluetooth/host/adv.c [hunk 2]
```diff
@@ -524,27 +524,34 @@ static int hci_set_ad(uint16_t hci_op, const struct bt_ad *ad, size_t ad_len)
...
+
+	max_data_size = total_len;
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:544]: Instead of overwriting `max_data_len`, could we set it to the "correct" value in the above `if` statement (`if (atomic_test_bit(adv->flags, BT_ADV_EXT_ADV))`) first time around? 

I think that's going to be more clear.

File: subsys/bluetooth/host/adv.c [hunk 3]
```diff
@@ -524,27 +524,34 @@ static int hci_set_ad(uint16_t hci_op, const struct bt_ad *ad, size_t ad_len)
...
+	total_len += offsetof(struct bt_hci_cp_le_set_ext_adv_data, data);
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:545]: I would actually prefer to create a new `const` variable which is something like
```c
const size_t cmd_size = total_len + offsetof(struct bt_hci_cp_le_set_ext_adv_data, data);
```

and use that instead of incrementing the `total_len`. `total_len` should then also become `total_data_len`. 

Alternative instead of using `offsetof` is to modify the struct from 
```c
struct bt_hci_cp_le_set_ext_adv_data {
	uint8_t  handle;
	uint8_t  op;
	uint8_t  frag_pref;
	uint8_t  len;
	uint8_t  data[251];
} __packed;
```
to
```c
struct bt_hci_cp_le_set_ext_adv_data {
	uint8_t  handle;
	uint8_t  op;
	uint8_t  frag_pref;
	uint8_t  len;
	uint8_t  data[0];
} __packed;
```
and then in all use cases when creating the cmd use something like
```c
bt_hci_cmd_create(BT_HCI_OP_LE_SET_EXT_ADV_DATA, sizeof(struct bt_hci_cp_le_set_ext_adv_data) + data_len; 
```

which we do for many other dynamic sized HCI commands.

**Review by Thalley — CHANGES_REQUESTED** [review]
It is a step in the right direction, but it feels half-way implemented. 

It handles only a specific case, but should probably be applied to periodic advertising as well, as well as optimizing when setting long data as well (e.g. if data is fragment in {50, 50, 5}, then the last will still send more bytes than needed).

File: subsys/bluetooth/host/adv.c (hunk 3 above)
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:554]: I prefer to use `offsetof`, because the latter needs to be changed at a larger point and has more uncertainty.

File: subsys/bluetooth/host/adv.c [hunk 4]
```diff
@@ -572,17 +581,26 @@ static int hci_set_adv_ext_fragmented(struct bt_le_ext_adv *adv, uint16_t hci_op
...
 		}
 
-		set_data = net_buf_add(buf, sizeof(*set_data));
+		set_data = net_buf_add(buf, cmd_size);
 
 		set_data->handle = adv->handle;
 		set_data->frag_pref = BT_HCI_LE_EXT_ADV_FRAG_ENABLED;
+
+		(void)memcpy(&stream, &backup, sizeof(stream));
+
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:603]: Hmm, so you are pretty much using `ad_stream_read` to get the data length, before creating the buffer, but in order to do that you had to refactor `ad_stream_read` and then also create a backup for the stream. 

In that case, I think a new function to simply get the data_len without having to complicate the `ad_stream_read` function as well as avoiding creating a backup would be a simpler and more clean solution.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/adv.c [hunk 5]
```diff
@@ -126,21 +126,30 @@ static uint8_t ad_stream_read(struct ad_stream *stream, uint8_t *buf, uint8_t bu
 		}
 
 		if (stream->current_ltv_offset == 0) {
-			buf[read_len] = current_ltv->data_len + 1;
+			if (buf) {
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/adv.c:129]: These changes need to be reflected in the function documentation.

File: subsys/bluetooth/host/adv.c [hunk 6]
```diff
@@ -572,17 +581,26 @@ static int hci_set_adv_ext_fragmented(struct bt_le_ext_adv *adv, uint16_t hci_op
 	while (!ad_stream_is_empty(&stream)) {
 		struct bt_hci_cp_le_set_ext_adv_data *set_data;
 		struct net_buf *buf;
+		size_t data_len, cmd_size;
 		int err;
 
-		buf = bt_hci_cmd_create(hci_op, sizeof(*set_data));
+		(void)memcpy(&backup, &stream, sizeof(stream));
+
+		data_len = ad_stream_read(&stream, NULL, sizeof(set_data->data));
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/adv.c:589]: I prefer that the copy `backup` is what is used up. It's more function-like then.

I think the stream copy and read must be a new API method `ad_stream_peek`. The fact `ad_stream` can be shallow-copied should be an implementation detail.

**Review by alwa-nordic — CHANGES_REQUESTED** [review]
The commit message also needs work. I suggest changing the subject line to "Optimize hci buf allocation by calculating `ad_stream` size". The commit message body could use some love as well :). Please also add an abstract of the changes / solution.

File: subsys/bluetooth/host/adv.c (hunk 4 above)
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:603]: I also prefer the view of @alwa-nordic , because the current implementation is still the simplest, and rewriting one is not necessarily better.

Comment (Thalley) [reply subsys/bluetooth/host/adv.c]: I like the idea that @alwa-nordic proposed, i.e. getting the total length in `ad_stream_new`. In that case, we should be able to avoid the save/restore functions, as well as the change to `ad_stream_read`, right?

Comment (LingaoM) [reply subsys/bluetooth/host/adv.c]: Please Review Again.

File: subsys/bluetooth/host/adv.c [hunk 7]
```diff
@@ -524,29 +535,29 @@ static int hci_set_ad(uint16_t hci_op, const struct bt_ad *ad, size_t ad_len)
...
-	if (atomic_test_bit(adv->flags, BT_ADV_EXT_ADV)) {
-		max_data_size = BT_HCI_LE_EXT_ADV_FRAG_MAX_LEN;
-	} else {
-		max_data_size = BT_GAP_ADV_MAX_ADV_DATA_LEN;
-	}
-
-	err = set_data_add_complete(set_data->data, max_data_size, ad, ad_len,
-				    &set_data->len);
+	err = set_data_add_complete(set_data->data, total_data_len,
+				    ad, ad_len, &set_data->len);
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:560]: Correct me if I am wrong, but won't `total_data_len` and `set_data->len` always be the same value after this call?

File: subsys/bluetooth/host/adv.c [hunk 8]
```diff
@@ -51,11 +51,21 @@ struct ad_stream {
...
 {
+	size_t len = 0;
+
 	(void)memset(stream, 0, sizeof(*stream));
 	stream->ad = ad;
 	stream->ad_len = ad_len;
+
+	for (int i = 0; i < ad_len; i++) {
+		for (int j = 0; j < ad[i].len; j++) {
+			len += ad[i].data[j].data_len + 2;
```
Comment (Thalley) [inline subsys/bluetooth/host/adv.c:64]: While it may be obvious to us (and right now), please add a comment stating that `+ 2` is from the LTV header (length and type).

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/adv.c (hunk 7 above)
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:559]: Yes, always same, so we can use `(void)set_data_add_complete`.

Good point.

File: subsys/bluetooth/host/adv.c [hunk 9]
```diff
@@ -629,7 +640,7 @@ static int hci_set_ad_ext(struct bt_le_ext_adv *adv, uint16_t hci_op,
 		/* If possible, set all data at once.
 		 * This allows us to update advertising data while advertising.
 		 */
-		return hci_set_adv_ext_complete(adv, hci_op, ad, ad_len);
+		return hci_set_adv_ext_complete(adv, hci_op, total_len_bytes, ad, ad_len);
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/adv.c:643]: This change is independent and should go in a separate commit. Maybe even a separate PR. It's easier for us reviewers when the PRs are kept small. (I know @Thalley asked for this in this PR, but personally I would prefer to review one change at a time.)

**Review by alwa-nordic — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/adv.c (hunk 9 above)
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:643]: I recommend using a separate commit instead of a separate pr.

File: subsys/bluetooth/host/adv.c (hunk 7 above)
Comment (Thalley) [reply subsys/bluetooth/host/adv.c]: > Yes, always same, so we can use `(void)set_data_add_complete`.
> 
> Good point.

How did you come to that conclusion? 

It does actually looks like that in the case of `BT_DATA_NAME_COMPLETE` that is shortened that they will not be equal. In that case, the calculated length is larger than &set_data->len. 

The case where shortening the name fails due to the size can still happen here, can't it?

**Review by alwa-nordic — DISMISSED** [review]

File: subsys/bluetooth/host/adv.c (hunk 7 above)
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c]: `if ((set_data_len + len + 2) > set_data_len_max) `

This judgment will also false, because we do same calculation for set_data_len_max before. Only problem is we can't change type to short_name，or we not need todo this, i think.

File: subsys/bluetooth/host/adv.c [hunk 10]
```diff
@@ -524,34 +535,29 @@ static int hci_set_ad(uint16_t hci_op, const struct bt_ad *ad, size_t ad_len)
...
-	int err;
-	uint8_t max_data_size;
+	const size_t cmd_size = total_data_len +
+				offsetof(struct bt_hci_cp_le_set_ext_adv_data, data);
 
-	buf = bt_hci_cmd_create(hci_op, sizeof(*set_data));
-	if (!buf) {
-		return -ENOBUFS;
+	if (!atomic_test_bit(adv->flags, BT_ADV_EXT_ADV) &&
+	    total_data_len > BT_GAP_ADV_MAX_ADV_DATA_LEN) {
```
Comment (LingaoM) [inline subsys/bluetooth/host/adv.c:546]: @Thalley and we already check this before.

So the length of advertising always can place and not need to shorten.

File: subsys/bluetooth/host/adv.c (hunk 7 above)
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:563]:
``` C
	/* Provide the opportunity to truncate the complete name */
	if (!atomic_test_bit(adv->flags, BT_ADV_EXT_ADV) &&
	    total_data_len > BT_GAP_ADV_MAX_ADV_DATA_LEN) {
		total_data_len = BT_GAP_ADV_MAX_ADV_DATA_LEN;
	}
```

Solved.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/adv.c [hunk 11]
```diff
@@ -49,13 +49,23 @@ struct ad_stream {
...
 static void ad_stream_new(struct ad_stream *stream, const struct bt_ad *ad, size_t ad_len)
 {
 	(void)memset(stream, 0, sizeof(*stream));
 	stream->ad = ad;
 	stream->ad_len = ad_len;
+
+	for (int i = 0; i < ad_len; i++) {
+		for (int j = 0; j < ad[i].len; j++) {
+			/* LTV length + type + value */
+			stream->remaining_size += ad[i].data[j].data_len + 2;
```
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:66]: remaining_size `uint16_t` max 65535, how can overflow?

File: subsys/bluetooth/host/adv.c [hunk 12]
```diff
@@ -146,6 +155,8 @@ static uint8_t ad_stream_read(struct ad_stream *stream, uint8_t *buf, uint8_t bu
 		}
 	}
 
+	stream->remaining_size -= read_len;
```
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:158]: `stream->remaining_size` represents the sum of all lengths, which is always greater than read_ Len, isn't it? I can't see it underflow

**Comment by Thalley** [comment]
> I guess this fixes #37710
> 
> If we go down this road, should we not apply the same fix for periodic advertising as well?

@LingaoM Can you please add the `fixes` keyword for the PR description to link it to this issue?

File: subsys/bluetooth/host/adv.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/adv.c:66]: since ad_len is a `size_t`, the application can technically attempt to set 22000 entries in the array, and if they are each 3 octets (length + type + 1 byte data) that will be a total of 66000 octets here, and that would cause an overflow, and `stream->remaining_size` will be `465`.

File: subsys/bluetooth/host/adv.c (hunk 12 above)
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/adv.c:158]: It should be indeed :) Unless we have an error somewhere. IMO it doesn't hurt to add an _ASSERT to verify that `stream->remaining-size > read_len`

[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:159]: Done :)

**Comment by LingaoM** [comment]
@Thalley @alwa-nordic @jhedberg If there is no problem, please approve

**Review by jhedberg — DISMISSED** [review]

File: subsys/bluetooth/host/adv.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:66]: Done

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/adv.c:66]: What is "done" here? I don't see any change

File: subsys/bluetooth/host/adv.c [hunk 13]
```diff
@@ -49,13 +49,23 @@ struct ad_stream {
 	 * The length and type are included in this offset.
 	 */
 	uint16_t current_ltv_offset;
+
+	/* The remaining size of total ad[i].data[j].data_len + 2 for LTV header */
+	size_t remaining_size;
```
Comment (LingaoM) [inline subsys/bluetooth/host/adv.c:54]: https://github.com/zephyrproject-rtos/zephyr/pull/43255/files#r817569322

Not and modified?

File: subsys/bluetooth/host/adv.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:66]: https://github.com/zephyrproject-rtos/zephyr/pull/43255/files#r822427197

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/adv.c:66]: I'm sorry, I don't fully understand your comment. 

My point is that you are here, without conditions, increasing a `size_t` value by looping over two other `size_t` values. Without any checks for `ad_len` or `ad[i].len` this can cause overflow.

[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:66]:
```suggestion
			please provide your modification
```

[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:66]: Now that the type of remaining_size  is already size_t, how can this possibly overflow?

[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:66]: According to your opinion, `current_ltv_offset` this parameter may still overflow, isn't it?

[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/host/adv.c:66]: If four bytes of space cannot represent the length of the total data, the use of the application layer is undoubtedly stupid.

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/host/adv.c:66]: > If four bytes of space cannot represent the length of the total data, the use of the application layer is undoubtedly stupid.

Right, and we should protect the stack against a buggy (or stupid) application. 

We know that the maximum advertising data can be 1650. 

I would suggest simply adding
```c
if (stream->remaining_size > BT_GAP_ADV_MAX_EXT_ADV_DATA_LEN) {
	/* return err */
}
```

Which not only guards against overflow, but also attempted spec violation.

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
