### PR TITLE
drivers: uart_ns16550: remove soc specific codes and bug fixes

### LINKED ISSUE #12652: UART console is showing garbage with driver uart_ns15560
**Describe the bug**
What have you tried to diagnose or workaround this issue?
 Removed the + 1 in the following line
               divisor = ((dev_cfg->sys_clk_freq / baud_rate) >> 4) + 1;
and characters are properly printed.

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD= "The board is not in the tree yet"
3. make

**Expected behavior**
Data is not properly printed in the UART console

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.
\\\
uart_bug

\\\
**Environment (please complete the following information):**

SHA:
               commit f0db0b8815a49c6bc5c489072199d38876298f8a
              Author: Wayne Ren <wei.ren@synopsys.com>
              Date:   Sun Nov 18 02:21:09 2018 +0800

### PR DESCRIPTION
**Pull request by vonhust**
* remove soc specific codes
* optimize the caculation of baudrate.
   the correct formula is 
        divisor =  (u32_t)(dev_cfg->sys_clk_freq / (16.0 * baud_rate) + 0.5)
  here a variant is used to replace the old one

Fixes #12652

Signed-off-by: Wayne Ren <wei.ren@synopsys.com>

### CODE REVIEW

File: drivers/serial/uart_ns16550.c [hunk 1]
```diff
@@ -255,7 +253,9 @@ static void set_baud_rate(struct device *dev, u32_t baud_rate)
 
 	if ((baud_rate != 0) && (dev_cfg->sys_clk_freq != 0)) {
 		/* calculate baud rate divisor */
-		divisor = ((dev_cfg->sys_clk_freq / baud_rate) >> 4) + 1;
+/* a variant of (u32_t)(dev_cfg->sys_clk_freq / (16.0 * baud_rate) + 0.5) */
```
[the remark this answers is not in the document]
Comment (vonhust) [reply drivers/serial/uart_ns16550.c]: done

File: drivers/serial/uart_ns16550.c [hunk 2]
```diff
@@ -254,8 +252,12 @@ static void set_baud_rate(struct device *dev, u32_t baud_rate)
 	u8_t lcr_cache;
 
 	if ((baud_rate != 0) && (dev_cfg->sys_clk_freq != 0)) {
-		/* calculate baud rate divisor */
-		divisor = ((dev_cfg->sys_clk_freq / baud_rate) >> 4) + 1;
+		/*
+		 * calculate baud rate divisor. a variant of
+		 * (u32_t)(dev_cfg->sys_clk_freq / (16.0 * baud_rate) + 0.5)
```
Comment (nashif) [inline drivers/serial/uart_ns16550.c]: where is this documented? Is this coming from some datasheet?

**Comment by nashif** [comment]
@franciscomunoz Can you try this fix on your HW?

**Comment by franciscomunoz** [comment]
@vonhust @nashif 

I tried #12087 just the uart portion  and so far so good!
image

**Review by nashif — APPROVED** [review]

File: drivers/serial/uart_ns16550.c (hunk 2 above)
Comment (vonhust) [reply drivers/serial/uart_ns16550.c]: a long long time when MCU is not so fast,  16 Mhz - 24 Mhz,  the formula is  sclk / (16.0  * baud_rate) + 0.5.  For recent devices, as freq is higher,  it's ok to use (sclk / baud_rate) >> 16.

Iotdk is a special case,  where sclk is just 16 Mhz,  if  16 M / 115200 / 16.0 =  8.68 , there will an error of 0.68 if choose 8,   0.32 if choose 9,  so the right vaule should be 9.  If choose 8, the baurdrate error is out of limit to cause garbage output.

**Review by pfalcon — APPROVED** [review]
