### PR TITLE
arch: arc: clear MPU regions before init it to fix tests exception and timeout

### LINKED ISSUE #28493: Sanitycheck on ARC em_starterkit_em7d has many tests timeout
**Describe the bug**
Sanitycheck tests keeps going timeout on em_starterkit_em7d target. 
take tests/kernel tests as example, first few tests are ok.
The first timeout is no-multithreading test, and all tests after mem_pool/sys_mem_pool test would be timeout. 

**To Reproduce**
`scripts/sanitychek -p em_starterkit_em7d -T tests/kernel --device-testing --device-serial /dev/ttyUSB1`

**Expected behavior**
Should pass all the tests

**Impact**
Unable to test em_starterkit_em7d

**Logs and console output**
```
scripts/sanitycheck -p em_starterkit_em7d -T tests/kernel --device-testing --device-serial /dev/ttyUSB1
ZEPHYR_BASE unset, using "/home/yuguo/Documents/zephyr"
INFO    - JOBS: 1
INFO    - Building initial testcase list...
INFO    - 106 test configurations selected, 16 configurations discarded due to filters.

Device testing on:

| Platform           | ID   | Serial device   |
|--------------------|------|-----------------|
| em_starterkit_em7d |      | /dev/ttyUSB1    |

INFO    - Adding tasks to the queue...
INFO    - Total complete:    9/  90  10%  skipped:    0, failed:    0
ERROR   - em_starterkit_em7d        tests/kernel/threads/no-multithreading/kernel.threads.no-multithreading FAILED: Timeout
ERROR   - see: /home/yuguo/Documents/zephyr/sanity-out/em_starterkit_em7d/tests/kernel/threads/no-multithreading/kernel.threads.no-multithreading/device.log
INFO    - Total complete:   15/  90  16%  skipped:    0, failed:    1
ERROR   - em_starterkit_em7d        tests/kernel/mem_pool/mem_pool_threadsafe/kernel.memory_pool.threadsafe.legacy FAILED: Timeout
ERROR   - see: /home/yuguo/Documents/zephyr/sanity-out/em_starterkit_em7d/tests/kernel/mem_pool/mem_pool_threadsafe/kernel.memory_pool.threadsafe.legacy/device.log
INFO    - Total complete:   16/  90  17%  skipped:    0, failed:    2
ERROR   - em_starterkit_em7d        tests/kernel/mem_pool/mem_pool_threadsafe/kernel.memory_pool.threadsafe FAILED: Timeout
ERROR   - see: /home/yuguo/Documents/zephyr/sanity-out/em_starterkit_em7d/tests/kernel/mem_pool/mem_pool_threadsafe/kernel.memory_pool.threadsafe/device.log
INFO    - Total complete:   17/  90  18%  skipped:    0, failed:    3
ERROR   - em_starterkit_em7d        tests/kernel/mem_pool/mem_pool_concept/kernel.memory_pool.concept.legacy FAILED: Timeout
ERROR   - see: /home/yuguo/Documents/zephyr/sanity-out/em_starterkit_em7d/tests/kernel/mem_pool/mem_pool_concept/kernel.memory_pool.concept.legacy/device.log
INFO    - Total complete:   18/  90  20%  skipped:    0, failed:    4
```

### PR DESCRIPTION
**Pull request by YuguoWH**
EMSK boards can't be reset between tests due to board hardware design. 
But MPU v3 assume that all the MPU registers has been reset to zero. 
During sanitycheck tests, MPU configs of previous test could pass to following tests and cause exceptions. 
This PR fixes this issue by adding MPU region reset. 
The issue was only found on MPU v3, so this fix does not apply to MPU v2.

Fixes #28493

### CODE REVIEW

File: arch/arc/core/mpu/arc_mpu_v3_internal.h [hunk 1]
```diff
@@ -845,6 +845,10 @@ static int arc_mpu_init(const struct device *arg)
 	/* Disable MPU */
 	arc_core_mpu_disable();
 
+	/* clear all the regions first */
```
Comment (abrodkin) [inline arch/arc/core/mpu/arc_mpu_v3_internal.h:848]: Please add your perfectly correct rationale in comments here so every reader of that code understands why do we do that. Though given we don't limit that fix-up to a particular board (which will add an extra `ifdef` which is not good) explain it in a more generic way (i.e. w/o mention of EMSK).

**Review by abrodkin — CHANGES_REQUESTED** [review]

File: arch/arc/core/mpu/arc_mpu_v3_internal.h (hunk 1 above)
Comment (YuguoWH) [reply arch/arc/core/mpu/arc_mpu_v3_internal.h]: Hi @abrodkin , thank you for the advice. Modified.

**Review by abrodkin — APPROVED** [review]

**Review by ruuddw — CHANGES_REQUESTED** [review]
The idea here is correct, but I think the solution can be improved:

mpu_disable() is performed and the existing init logic programs all regions -> not obvious why the initial zeroing is required/
The problem is that mpu_disable() doesn't actually disable the MPU (v3 cannot be disabled), but it is emulated by programming the default region. This ignores that there can be other regions programmed with access restrictions.
Simply clearing all regions in mpu_disable() isn't a solution, as mpu_disable should not destroy the regions state.
arc_mpu_init() is called reasonably early, but if the intent is to put the MPU in 'reset' state, I think it is better to do this in the very early reset code.

So, please either:

- move the MPU region clearing + programming the default region to allow all access to early init code (with a comment that it is for emulating some part of a HW reset when doing a soft 'reset')

- or add the region clearing to the mpu_disable() -> but this will require more changes: remove/change other calls to mpu_disable() that expect disable but with state of the regions kept.

Thanks,

Ruud.

File: arch/arc/core/reset.S [hunk 2]
```diff
@@ -121,6 +121,35 @@ invalidate_dcache:
...
 
+/*
+ * ARC Custom Initialization
+ * Force Reset MPU (v3) registers
+ * For some test scenarios, this is needed to apply additional configurations
+ */
+#if defined(CONFIG_ARC_CUSTOM_INIT)
+#if CONFIG_ARC_MPU_VER == 3
+	/* Set default reset value to _ARC_V2_MPU_EN */
+	mov_s r1, 0x400181C0
```
Comment (abrodkin) [inline arch/arc/core/reset.S:132]: Please don't use literals like that. Create a definition right here with meaningful name & comments.

File: arch/arc/core/reset.S [hunk 3]
```diff
@@ -121,6 +121,35 @@ invalidate_dcache:
 
 done_cache_invalidate:
 
+/*
+ * ARC Custom Initialization
+ * Force Reset MPU (v3) registers
+ * For some test scenarios, this is needed to apply additional configurations
```
Comment (ruuddw) [inline arch/arc/core/reset.S:127]: Suggest to change/clarify: "For scenarios where the board hardware is not reset in between tests, some settings need to be reset in software"

File: arch/arc/core/mpu/arc_mpu_v2_internal.h [hunk 4]
```diff
@@ -16,10 +16,6 @@
 #define AUX_MPU_RDP_ATTR_MASK (0x1FC)
 #define AUX_MPU_RDP_SIZE_MASK (0xE03)
 
-#define _ARC_V2_MPU_EN   (0x409)
```
Comment (abrodkin) [inline arch/arc/core/mpu/arc_mpu_v2_internal.h:19]: Cannot we move that non functional change to the separate commit (even if you prefer to include it in this PR)?

File: arch/arc/core/mpu/arc_mpu_v3_internal.h [hunk 5]
```diff
@@ -12,16 +12,6 @@
 
 #define AUX_MPU_RPER_ATTR_MASK (0x1FF)
 
-#define _ARC_V2_MPU_EN   (0x409)
```
Comment (abrodkin) [inline arch/arc/core/mpu/arc_mpu_v3_internal.h:15]: Ditto.

File: include/arch/arc/v2/aux_regs.h [hunk 6]
```diff
@@ -110,6 +110,17 @@
 #define _ARC_V2_FPU_DPFP1H 0x303
 #define _ARC_V2_FPU_DPFP2L 0x304
 #define _ARC_V2_FPU_DPFP2H 0x305
+#define _ARC_V2_MPU_EN 0x409
+#if CONFIG_ARC_MPU_VER == 2
```
Comment (ruuddw) [inline include/arch/arc/v2/aux_regs.h:114]: no need for conditional compilations here, the values all are different and we don't have conditions for other HW features like e.g. FPU.

File: arch/arc/core/reset.S (hunk 3 above)
Comment (abrodkin) [inline arch/arc/core/reset.S:127]: We're trying to mimic real "cold reset" with additional initialization.

**Review by abrodkin — CHANGES_REQUESTED** [review]

**Review by ruuddw — APPROVED** [review]
Just a few minor suggestions for improving.

File: include/arch/arc/v2/aux_regs.h [hunk 7]
```diff
@@ -110,6 +110,17 @@
...
+#define _ARC_V2_MPU_RDB0 0x422
+#define _ARC_V2_MPU_RDP0 0x423
+#define _ARC_V2_MPU_INDEX 0x448
+#define _ARC_V2_MPU_RSTART 0x449
+#define _ARC_V2_MPU_REND 0x44A
+#define _ARC_V2_MPU_RPER 0x44B
+#define _ARC_V2_MPU_PROBE 0x44C
+
+/* Default reset value for _ARC_V2_MPU_EN register */
+#define ARC_MPU_EN_RESET_VALUE 0x400181C0
```
Comment (YuguoWH) [inline include/arch/arc/v2/aux_regs.h:123]: Have some doubt here: I wish to put this in arc_mpu.h, but the header file is not included in assembly code.

Comment (abrodkin) [reply include/arch/arc/v2/aux_regs.h:123]: There's no need to move that default value which is used only one in 1 place into generic header. And that's what I meant in my initial commit - move that definition right in the place where it is used. It's OK to have it done that way:
```c
...
// This is very important definition used for XXX
#define MY_IMPORTNAT_DEFINITION 0x12345678
    super_secret_password = MY_IMPORTNAT_DEFINITION;
...
```

File: arch/arc/Kconfig [hunk 8]
```diff
@@ -328,4 +328,11 @@ config ARC_EXCEPTION_DEBUG
 	  and parameters, at a cost of code/data size for the human-readable
 	  strings.
 
+config ARC_CUSTOM_INIT
```
Comment (abrodkin) [inline arch/arc/Kconfig:331]: I really like that definition & help message!

File: arch/arc/core/reset.S [hunk 9]
```diff
@@ -121,6 +121,36 @@ invalidate_dcache:
 
 done_cache_invalidate:
 
+/*
+ * ARC Custom Initialization
+ * For scenarios where board hardware is not reset between tests,
+ * Some settings need to be reset by software.
```
Comment (abrodkin) [inline arch/arc/core/reset.S:127]: I'd prefer to not use a word "reset" because we don't reset anything here in a typical sense.. i.e. HW is not being re-initialized internally. Instead we return its settings to the default initial state trying to substitute normal HW reset sequence.

File: arch/arc/core/reset.S [hunk 10]
```diff
@@ -121,6 +121,36 @@ invalidate_dcache:
...
+ */
+#if defined(CONFIG_ARC_CUSTOM_INIT)
+	/* Software Reset MPU (v3) registers */
+#if CONFIG_ARC_MPU_VER == 3
+	/* Set default reset value to _ARC_V2_MPU_EN */
+	mov_s r1, ARC_MPU_EN_RESET_VALUE
```
Comment (abrodkin) [inline arch/arc/core/reset.S:133]: As I mentioned move its definition right here this way
```c
/* Default reset value for _ARC_V2_MPU_EN register */
#define ARC_MPU_EN_RESET_VALUE 0x400181C0

    /* Set default reset value to _ARC_V2_MPU_EN */
    mov_s r1, ARC_MPU_EN_RESET_VALUE
    sr r1, [_ARC_V2_MPU_EN]
```

File: arch/arc/core/reset.S [hunk 11]
```diff
@@ -121,6 +121,36 @@ invalidate_dcache:
...
+	sr r1, [_ARC_V2_MPU_EN]
+	/* Get MPU region numbers */
+	lr r3, [_ARC_V2_MPU_BUILD]
+	lsr_s r3, r3, 8
+	and r3, r3, 0xff
+	mov_s r1, 0
+	mov_s r2, 0
+	/* Reset all MPU regions by iterating index */
+mpu_software_reset:
```
Comment (abrodkin) [inline arch/arc/core/reset.S:142]: Here as well that `mpu_software_reset` label is a bit confusing.
Maybe something more functional like `mpu_regions_reset`?

**Review by abrodkin — CHANGES_REQUESTED** [review]
I'd suggest to rephrase "arch: arc: Add MPU software reset at early init stage" to something w/o mention of "software reset" as we cannot do any real reset with software, instead we just "return MPU settings to defaults".

**Review by abrodkin — APPROVED** [review]

**Review by ruuddw — APPROVED** [review]
Even better like this, thanks.

File: arch/arc/Kconfig [hunk 12]
```diff
@@ -328,4 +328,11 @@ config ARC_EXCEPTION_DEBUG
...
+	bool "Enable custom initialization code"
+	default n
```
Comment (ioannisg) [inline arch/arc/Kconfig:333]: Default n is not needed, here (it is default n, anyways), so it should be removed

**Comment by ioannisg** [comment]
This looks OK to me.
I just feel that eventually we need to make a decision whether Zephyr should really initialize every ARCH-level hardware once it is coming out of reset or it should keep relying on the parent image, e.g. a bootloader... Right now we are not consistent across architectures and platforms.

**Comment by abrodkin** [comment]
> This looks OK to me.
> I just feel that eventually we need to make a decision whether Zephyr should really initialize every ARCH-level hardware once it is coming out of reset or it should keep relying on the parent image, e.g. a bootloader... Right now we are not consistent across architectures and platforms.

So are there any similar hacks done for other boards/arches? I'm asking because IMHO it would be logical to use some unified ifdef for them so that we may:
1. Document it and use similarly across the board
2. Easier remove all that mess if we decide to rely solely on clean out-of-reset state

**Comment by ioannisg** [comment]
> So are there any similar hacks done for other boards/arches? I'm asking because IMHO it would be logical to use some unified ifdef for them so that we may:

> Document it and use similarly across the board
> Easier remove all that mess if we decide to rely solely on clean out-of-reset state

Yes, at least Cortex-M is doing similar things, everywhere in the system init code. 

I guess the Kconfig switch should be something like `config ARCH_INIT_HW_AT_BOOT` and should be used explicitly around code that initializes ARCH core hardware to its default values, if it were coming out of warm reset.

**Comment by ioannisg** [comment]
@abrodkin if you would like to open a GH ticket for this, I can fill it in with the information about ARM.

**Comment by YuguoWH** [comment]
Removed `default n` in Kconfig

**Comment by abrodkin** [comment]
@ioannisg see https://github.com/zephyrproject-rtos/zephyr/issues/28803
