### PR TITLE
tests: testsuite: add emulating send IPI in X2APIC mode

### LINKED ISSUE #42108: upsquared: isr_dynamic & isr_regular test is failing
Describe the bug
isr_dynamic & isr_regular test is failing on up_squared platform

To Reproduce

1. twister -p up_squared --device-testing --device-serial /dev/ttyUSB1 -T tests/kernel/interrupt/ --west-flash="$HOME/up_squared_efi.sh" -j 1 -vv
2. See error

Expected behavior
Tests should pass.

Logs and console output
```
*** Booting Zephyr OS build v2.7.99-3661-gd51a67b7c098  ***
Running test suite interrupt_feature
===================================================================
START - test_isr_dynamic
vector(48)
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/interrupt/src/dynamic_isr.c:108: test_isr_dynamic: (handler_has_run not equal to 1)
interrupt triggered but handler has not run(0)
FAIL - test_isr_dynamic in 0.20 seconds
===================================================================
START - test_nested_isr
SKIP - test_nested_isr in 0.1 seconds
===================================================================
START - test_prevent_interruption
locking interrupts
unlocking interrupts
timer fired
PASS - test_prevent_interruption in 2.6 seconds
===================================================================
START - test_isr_regular
irq(27)=vector(64)
irq(28)=vector(65)
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/interrupt/src/regular_isr.c:72: test_isr_regular: (reg_int_executed[0] == 1 && reg_int_executed[1] == 0 is false)
ISR1 should execute
FAIL - test_isr_regular in 0.23 seconds
===================================================================
START - test_isr_offload_job_multiple
PASS - test_isr_offload_job_multiple in 0.1 seconds
===================================================================
START - test_isr_offload_job_identi
PASS - test_isr_offload_job_identi in 0.1 seconds
===================================================================
START - test_isr_offload_job
vector(49)
PASS - test_isr_offload_job in 0.2 seconds
===================================================================
START - test_direct_interrupt
SKIP - test_direct_interrupt in 0.1 seconds
===================================================================
Test suite interrupt_feature failed.
===================================================================
PROJECT EXECUTION FAILED
```

Environment:

OS: Fedora
Toolchain: SDK 0.13.2
Commit SHA: d51a67b7c098

### PR DESCRIPTION
**Pull request by enjiamai**
We emulate the interrupt by sending the IPI to core itself by
the local APIC for x86 platfrom.

But in X2APIC mode, this no longer works. So we emulate the
interrupt the by writing the IA32_X2APIC_SELF_IPI MSR to send
IPI to the core itself via LOAPIC also. According to SDM vol.3
chapter 10.12.11.

Fixes #42108

Signed-off-by: Enjia Mai <enjia.mai@intel.com>

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Comment by enjiamai** [comment]
Hi @andyross , @tbursztyka , @jhedberg, could you please help on review this when you got a chance? Thanks!

**Review by jhedberg — DISMISSED** [review]

**Comment by andyross** [comment]
I forgot about this header.  Not opposed to this patch, but it seems like it's needless complexity.  The point to having interrupt triggers in the generic test suite is to get coverage of the portable/standard arch layer interrupt entry and exit.  We can do that on x86 with a synchronous INT instruction.

If we want coverage of the deeper IO-/x2/APIC/MSI/MSIx platform layers, then we probably want to have a platform test and not try to do it here.  There is similar madness in tests/kernel/context where our "portable" test does a giant #if tree trying to figure out what the timer IRQ number is.

**Comment by enjiamai** [comment]
Hi @andyross , after thinking this more, I think your point is reasonable. This is more general tests for interrupt, and if we just verify the interrupt trigger, using INT here is enough. The reason I change to use IPI is I also want to test irq_disable() and irq_lock(), but as you mentioned, this is more suitable to put in the tests/arch, either the regular_isr and direct_isr for x86. 

So I will try to make some change and move these tests into arch dependent tests, any further suggestion here? thanks!

File: subsys/testsuite/include/interrupt_util.h [hunk 1]
```diff
@@ -101,30 +101,47 @@ static inline void trigger_irq(int irq)
...
+ * the LOAPIC_ICR_IPI_TEST  0x00004000U means:
  * Delivery Mode: Fixed
  * Destination Mode: Physical
  * Level: Assert
  * Trigger Mode: Edge
  * Destination Shorthand: No Shorthand
  * Destination: depends on cpu_id
+ *
+ * In X2APIC mode, this no longer works. We emulate the
+ * interrupt the by writing the IA32_X2APIC_SELF_IPI MSR
```
Comment (tbursztyka) [inline subsys/testsuite/include/interrupt_util.h:121]: one "the" too many

File: subsys/testsuite/include/interrupt_util.h [hunk 2]
```diff
@@ -101,30 +101,47 @@ static inline void trigger_irq(int irq)
...
+#ifdef CONFIG_X2APIC
+#include <drivers/interrupt_controller/loapic.h>
+
+#define VECTOR_MASK 0xFF
+
+	x86_write_x2apic(LOAPIC_SELF_IPI, ((VECTOR_MASK & vector)));
+#else
+#include <sys/arch_interface.h>
+#define LOAPIC_ICR_IPI_TEST  0x00004000U
+
```
Comment (tbursztyka) [inline subsys/testsuite/include/interrupt_util.h:137]: include headers and define macros, out of the function.

**Review by tbursztyka — CHANGES_REQUESTED** [review]

File: subsys/testsuite/include/interrupt_util.h (hunk 2 above)
Comment (enjiamai) [reply subsys/testsuite/include/interrupt_util.h:139]: Ok, move it out of the function. Thanks!

**Comment by enjiamai** [comment]
Hi @tbursztyka , I have addressed your comments, could you please review it again? thanks!

**Comment by enjiamai** [comment]
Hi @andyross , maybe we can merge this first to address the #42108 first, then I will follow what you suggested, to clean up the interrupt tests, make this testsuite more generic and simple (just using INT to trigger interrupt), then move the arch-dependent portion to tests/arch(such as using IPI to test).  This will make thing easier, I prefer doing it this way, do you think that it ok? Thanks!

**Review by jhedberg — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]
