### PR TITLE
storage/stream_flash: Fix write_block_size too small

### LINKED ISSUE #76029: lpc55s69 flash block size issue
This https://github.com/zephyrproject-rtos/zephyr/pull/68658 by @de-nordic introduced a bug for the lpc55s69 flash block size.

```
struct stream_flash_ctx {
	uint8_t *buf; /* Write buffer */
	size_t buf_len; /* Length of write buffer */
	size_t buf_bytes; /* Number of bytes currently stored in write buf */
	const struct device *fdev; /* Flash device */
	size_t bytes_written; /* Number of bytes written to flash */
	size_t offset; /* Offset from base of flash device to write area */
	size_t available; /* Available bytes in write area */
	stream_flash_callback_t callback; /* Callback invoked after write op */
#ifdef CONFIG_STREAM_FLASH_ERASE
	off_t last_erased_page_start_offset; /* Last erased offset */
#endif
	uint8_t erase_value;
	uint8_t write_block_size;	/* Offset/size device write alignment */
};
```

**write_block_size** and **erase_value** are 512 bytes on the lpc55s69, @decsny can confirm this.

During the stream_flash_init call:

```
	ctx->write_block_size = params->write_block_size;

	if (buf_len % ctx->write_block_size) {
		LOG_ERR("Buffer size is not aligned to minimal write-block-size");
		return -EFAULT;
	}
```

Causes a hard fault since` ctx->write_block_size` ends up being zero.
In my view, this is a critical bug and needs to be addressed before the Zephyr 3.7.0 release.

Can we just modify it to be size_t?

### PR DESCRIPTION
**Pull request by de-nordic**
Fix for platforms with write-block-size >= 256 bytes.

Fixes #76029

**Rationale for 3.7.0 milestone**
This is the fix for bug that hard faults applications using stream flash on devices that have write-block-size >=256.

**Rationale for Release Blocker label**
The bug has been introduced during this release, somewhere in May, it is not worth letting it pass through release gates and fix it later.

### CODE REVIEW

**Comment by de-nordic** [comment]
FYI @guicnDell

**Review by henrikbrixandersen — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]

File: include/zephyr/storage/stream_flash.h [hunk 1]
```diff
@@ -65,8 +65,8 @@ struct stream_flash_ctx {
 #ifdef CONFIG_STREAM_FLASH_ERASE
 	off_t last_erased_page_start_offset; /* Last erased offset */
 #endif
+	size_t write_block_size;	/* Offset/size device write alignment */
 	uint8_t erase_value;
```
Comment (guicnDell) [inline include/zephyr/storage/stream_flash.h:69]: erase_value also needs to be size_t, this is from the zephyr/dts/arm/nxp/nxp_lpc55S6x_common.dtsi
image

Comment (nordicjm) [reply include/zephyr/storage/stream_flash.h:69]: erase value is the single byte of what the erased data is, it should be a single byte and is typically 0xff for flash

Comment (guicnDell) [reply include/zephyr/storage/stream_flash.h:69]: Yes, you are correct. Thank you, please ignore my comment.

**Review by guicnDell — APPROVED** [review]
