### PR TITLE
drivers: serial: rp2040: fix rpi pico address mapping

### LINKED ISSUE #54685: drivers: serial: rp2040: fix rpi pico address mapping
**Describe the bug**
From #54617 :
> Address map used for config item uart_dev and uart_regs is currently derived using the rpi hal macros uart0 and uart1 which map to the same register address as given in the reg property of the devicetree.
However, the sdk macro is generated using uart##idx which zephyr does not necessarily map to uart0 or uart1. This is, for example, the case when disabling uart0 with the devicetree status "disabled" and enabling uart1 for which then the idx==0 and not 1 which therefore maps to the wrong controller address space.

### PR DESCRIPTION
**Pull request by ramonaerne**
Address map used for config item `uart_dev` and `uart_regs` is currently derived using the rpi hal macros `uart0` and `uart1` which map to the same register address as given in the `reg` property of the devicetree.

However, the sdk macro is generated using `uart##idx` which zephyr does not necessarily map to uart0 or uart1. This is, for example, the case when disabling uart0 with the devicetree status "disabled" and enabling uart1 for which then the idx==0 and not 1 which therefore maps to the wrong controller address space.

This can simply be fixed by deriving the base address from `DT_INST_REG_ADDR(idx)` instead

Signed-off-by: Ramon Aerne <ramon.aerne@axelera.ai>

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54685

### CODE REVIEW

**Review by galak — DISMISSED** [review]

**Comment by ramonaerne** [comment]
@galak had to push again to fix name and commit message

File: drivers/serial/uart_rpi_pico.c [hunk 1]
```diff
@@ -402,8 +402,8 @@ static const struct uart_driver_api uart_rpi_driver_api = {
 	}									\
 										\
 	static const struct uart_rpi_config uart##idx##_rpi_config = {		\
-		.uart_dev = uart##idx,						\
-		.uart_regs = (uart_hw_t *)uart##idx,				\
+		.uart_dev = (uart_inst_t * const) DT_INST_REG_ADDR(idx),	\
```
Comment (yonsch) [inline drivers/serial/uart_rpi_pico.c:405]: Please remove the space between the cast and the DT macro:
```suggestion
		.uart_dev = (uart_inst_t * const)DT_INST_REG_ADDR(idx),	\
```

File: drivers/serial/uart_rpi_pico.c [hunk 2]
```diff
@@ -402,8 +402,8 @@ static const struct uart_driver_api uart_rpi_driver_api = {
...
+		.uart_regs = (uart_hw_t *const) DT_INST_REG_ADDR(idx),		\
```
Comment (yonsch) [inline drivers/serial/uart_rpi_pico.c:406]: checkpatch seems to be okay with both `(type * const)` and `(type *const)`, so choose one of them an apply to this line or the one above, to be consistent.

**Review by yonsch — CHANGES_REQUESTED** [review]
Thanks, just a few nitpicks

**Review by yonsch — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by fabiobaltieri** [comment]
@ramonaerne can you file an issue for this (if you want this to be merged before the v3.3 release).

**Review by galak — APPROVED** [review]

**Comment by yonsch** [comment]
@fabiobaltieri #54685
