### PR TITLE
drivers: intc: plic: set edge-triggered register address using compat

### LINKED ISSUE #64675: [riscv-privileged] PLIC is not compliant with the Spec
**Describe the bug**

RISC-V PLIC driver no more conforms to the Spec after the 8db1a5a, see https://github.com/zephyrproject-rtos/zephyr/pull/63273

Trigger Type register is not defined in the recent PLIC Spec and so is not compliant with RISC-V Privileged Standard: https://github.com/riscv/riscv-plic-spec/blob/master/riscv-plic-1.0.0.pdf
IMHO this is a miss in the Spec and it results in a situation when all the vendors who support Triggering type configuration implement it in a proprietary way, using the custom offsets and custom codes for the triggering types.

So until the Trigger Type becomes a standard, it would be nice if we leave a room for flexibility here: by default PLIC should be compliant with the Spec while the Trigger Type register could be optionally enabled  as an extension for particular platforms. 

**Environment**
Zephyr v3.5

* Page: `project/issues`
* Version: main
* SHA-1: 8db1a5add221b5e47ad4e01dfcb3b4064a8299f4

### PR DESCRIPTION
**Pull request by ycsin**
Define the edge-trigger register base address based on whether the PLIC node in the devicetree has an additional compatible that supports edge-triggered interrupt.

Limited the implementation to Andes NCEPLIC100 only, updated the devicetree binding of `andes_v5_ae350` accordingly.

**Caveat**: Per-instance trigger register address isn't supported, if one of the PLIC instances has `"andestech,plic"`, it assumes that all PLIC instances have the same type

Fixes #64675

### CODE REVIEW

**Comment by cfriedt** [comment]
please review @amr-sc

File: drivers/interrupt_controller/intc_plic.c [hunk 1]
```diff
@@ -39,7 +39,16 @@
...
  */
+#define PLIC_DRV_HAS_COMPAT(compat)                                                                \
+	DT_NODE_HAS_COMPAT(DT_COMPAT_GET_ANY_STATUS_OKAY(DT_DRV_COMPAT), compat)
+
+#if PLIC_DRV_HAS_COMPAT(andestech_plic)
+#define PLIC_REG_TRIG_TYPE_OFFSET 0x1080
+#elif PLIC_DRV_HAS_COMPAT(telink_plic)
 #define PLIC_REG_TRIG_TYPE_OFFSET 0x1080
+#else
+#define PLIC_REG_TRIG_TYPE_OFFSET 0 /* Not supported */
```
[the remark this answers is not in the document]
Comment (cfriedt) [reply drivers/interrupt_controller/intc_plic.c:50]: In the long run, it would still be ideal to get another rev of the plic spec, but design by committee can take time.

[the remark this answers is not in the document]
Comment (amr-sc) [reply drivers/interrupt_controller/intc_plic.c:50]: Hi @ycsin ,

It's up to you, but why not to make this register configurable via CONFIG option, e.g. like it was implemented before:
https://github.com/zephyrproject-rtos/zephyr/commit/8db1a5add221b5e47ad4e01dfcb3b4064a8299f4

Then the unsupported functionality would be compiled-out entirely, you wouldn't need to have a reserved offset value with special meaning, you wouldn't need to alter intc_plic.c every time new vendor supports this, etc.

[the remark this answers is not in the document]
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c]: > why not to make this register configurable via CONFIG option, e.g. like it was implemented before:
> [8db1a5a](https://github.com/zephyrproject-rtos/zephyr/commit/8db1a5add221b5e47ad4e01dfcb3b4064a8299f4)

I like to keep the `sifive,plic-1.0.0` to closely resembles that of Linux kernel. Kconfig should be used to configure the software instead of describing the hardware.

> you wouldn't need to alter intc_plic.c every time new vendor supports this, etc.

I actually prefer vendors to upstream their stuff, rather than keeping the configurations downstream in some repo somewhere.

File: drivers/interrupt_controller/intc_plic.c [hunk 2]
```diff
@@ -39,7 +40,17 @@
  * However, it is defined and supported by at least the Andes & Telink datasheet, and supported
  * in Linux's SiFive PLIC driver
  */
+#define PLIC_DRV_HAS_COMPAT(compat)                                                                \
+	DT_NODE_HAS_COMPAT(DT_COMPAT_GET_ANY_STATUS_OKAY(DT_DRV_COMPAT), compat)
+
+#if PLIC_DRV_HAS_COMPAT(andestech_plic)
+#define PLIC_REG_TRIG_TYPE_OFFSET 0x1080
```
Comment (cfriedt) [inline drivers/interrupt_controller/intc_plic.c:47]: From what I remember, it isn't just the offset, but the number of bits per interrupt line. Some plic designs have zero bits of configuration (fully static, cannot even read configuration), some have 1 bit (level-only), and some have several bits (edge / level, rising / falling / both).

That should cover most of the base cases.

**Comment by ycsin** [comment]
Pulling this back as draft as it has a commit from #65847, but feel free to review

File: drivers/interrupt_controller/intc_plic.c [hunk 3]
```diff
@@ -42,7 +42,19 @@
  * However, it is defined and supported by at least the Andes & Telink datasheet, and supported
  * in Linux's SiFive PLIC driver
  */
+#define PLIC_TRIG_LEVEL ~BIT(0)
+#define PLIC_TRIG_EDGE BIT(0)
```
Comment (cfriedt) [inline drivers/interrupt_controller/intc_plic.c:46]: This *should* work... 
```suggestion
#define PLIC_TRIG_LEVEL ~BIT64(0)
#define PLIC_TRIG_EDGE BIT64(0)
```

**Comment by cfriedt** [comment]
@fkokosinski - any general thoughts about this PR?

File: drivers/interrupt_controller/intc_plic.c (hunk 3 above)
Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c]: added (uint32_t) cast in the macro to fix build warning

File: drivers/interrupt_controller/intc_plic.c [hunk 4]
```diff
@@ -291,14 +308,14 @@ static void plic_irq_handler(const struct device *dev)
...
 	/*
-	 * For edge triggered interrupts, write to the claim_complete register
-	 * to indicate to the PLIC controller that the IRQ has been handled
+	 * For edge-triggered interrupts, write to the claim_complete register
+	 * here to indicate to the PLIC controller that the IRQ has been handled
 	 * for edge triggered interrupts.
 	 */
-	if (edge_irq != 0) {
+	if (trig_val == PLIC_TRIG_EDGE) {
 		sys_write32(local_irq, claim_complete_addr);
```
Comment (amr-sc) [inline drivers/interrupt_controller/intc_plic.c:319]: Why do we have different policies to report the IRQ handling completion for EDGE-triggered and LEVEL-triggered modes? Why one is reported earlier while the other one later?

**Review by cfriedt — DISMISSED** [review]
Looks fine to me, but we need @fkokosinski to ack as well.

Ideally we would have some verification on the platforms mentioned too.

File: drivers/interrupt_controller/intc_plic.c (hunk 4 above)
Comment (fkokosinski) [reply drivers/interrupt_controller/intc_plic.c:319]: Yeah, acking works exactly the same for edge/level irqs, so we should unify this while we're at it. Could you do it @ycsin? Thanks!

The rest LGTM

Comment (ycsin) [reply drivers/interrupt_controller/intc_plic.c:319]: Hey all, I had a look and that seems to be a workaround for Andes' NCEPLIC100, see https://github.com/torvalds/linux/commit/dd46337ca69662b6912bc230d393c4261d126b8f and the discussion [here](https://lore.kernel.org/linux-arm-kernel/CA+V-a8s80shYtUsJZSu7vz_S6ZXtxGkHVi5cgBWO9tr_n+XiJA@mail.gmail.com/t/)

Comment (amr-sc) [reply drivers/interrupt_controller/intc_plic.c:319]: Hi @ycsin, 

Interesting! Looks like Andes's PLIC has an issue?

From the thread you've shared:
```
> Is this a feature of this PLIC implementation? Or is that common to
> all PLICs?
>
I think it's a feature of this PLIC implementation and not common to all PLIC's.
```

I think making this WAR behavior default for all the vendors is very risky.

Comment (amr-sc) [reply drivers/interrupt_controller/intc_plic.c:319]: Just as a follow-up. Syntacore also has this Triggering Mode register, but since it is not standardized yet, we made it as extension for standard PLIC: https://github.com/syntacore/zephyr/blob/sc/main-3.5/soc/riscv/riscv-privileged/syntacore-scr/common/plic.c

I suppose that other vendors also have some differences in that non-standard functionality implementation and bringing this to a common PLIC driver which is intended to follow the Spec is a "thin ice" path

**Comment by ycsin** [comment]
can someone from Andes confirm that the nceplic100 is present on all types of cores supported by the upstream `andes_v5_ae350` platform please? cc @kevinwang821020 @jimmyzhe

**Comment by jimmyzhe** [comment]
Hi @ycsin, 

yes, currently `andes_v5_ae350` represents ae350 bitstream integrated with NCEPLIC100.
We also have some ae350 bitstreams integrated with standard CLIC instead of PLIC, but they do not yet support Zephyr upstream.

**Review by cfriedt — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]
