### PR TITLE
usb: cdc_acm: Fix tx false data drop logging

### LINKED ISSUE #75988: usb: cdc_acm.c Logging shows false data drop warning
Logging error in CDC ACM:

In cdc_acm_fifo_fill() :
```
if (wrote < len) {
	LOG_WRN("Ring buffer full, drop %zd bytes", len - wrote);
}
```

Wrote is given as return value. Wrote being smaller than len is totally fine. The data doesn't get dropped and can be sent later.
It looks like a copy paste from the RX function cdc_acm_read_cb() (where it is correct as received data needs to be buffered or gets dropped).

Impact is low as it only gives a false warning when logging. Also it needs big chunks of data to be sent to fill the buffer.

Environment:
Xubuntu Linux
Zephyr SDK
zephyr commit f6600040e41114b8737dee5d6ea8415e417434c8

### PR DESCRIPTION
**Pull request by metratec-mkoehler**
Fixes #75988

cdc_acm_fifo_fill() logged warnings about dropped data when they in fact just couldn't be sent (due to connection of filled buffer). Not being able to send (all) data is a valid behaviour and data isn't dropped. Return value shows how many data was accepted (which can be zero).

Logging will now instead only inform data can't be sent due to the respective issue (connection / buffer full).

### CODE REVIEW

File: subsys/usb/device/class/cdc_acm.c [hunk 1]
```diff
@@ -527,8 +527,7 @@ static int cdc_acm_fifo_fill(const struct device *dev,
 		dev_data, len, ring_buf_space_get(dev_data->tx_ringbuf));
 
 	if (!dev_data->configured || dev_data->suspended) {
-		LOG_WRN("Device not configured or suspended, drop %d bytes",
```
Comment (tmon-nordic) [inline subsys/usb/device/class/cdc_acm.c:530]: See https://github.com/zephyrproject-rtos/zephyr/pull/76171#discussion_r1687022631 for a discussion on why checking for suspended here might not be the best idea (it leads to autosuspend issues if device support Remote Wakeup).

File: subsys/usb/device/class/cdc_acm.c [hunk 2]
```diff
@@ -527,8 +527,7 @@ static int cdc_acm_fifo_fill(const struct device *dev,
...
-			len);
+		LOG_INF("Device suspended or not configured, can't send %d bytes", len);
```
Comment (jfischer-no) [inline subsys/usb/device/class/cdc_acm.c:530]: Maybe just
LOG_INF("Device suspended or not configured");

File: subsys/usb/device/class/cdc_acm.c [hunk 3]
```diff
@@ -538,7 +537,7 @@ static int cdc_acm_fifo_fill(const struct device *dev,
 	wrote = ring_buf_put(dev_data->tx_ringbuf, tx_data, len);
 	irq_unlock(lock);
 	if (wrote < len) {
-		LOG_WRN("Ring buffer full, drop %zd bytes", len - wrote);
+		LOG_INF("Ring buffer full, %zd bytes can't buffered just now", len - wrote);
```
Comment (jfischer-no) [inline subsys/usb/device/class/cdc_acm.c:540]: Perhaps this block,
```c
	if (wrote < len) {
		LOG_WRN("Ring buffer full, drop %zd bytes", len - wrote);
	}
```
can simply be removed or replaced with a 
`LOG_DBG("Wrote %zd bytes to TX ringbuffer", wrote);`

Comment (metratec-mkoehler) [reply subsys/usb/device/class/cdc_acm.c:540]: I like that. 
Proposing 
`LOG_DBG("Wrote` %zd of %zd bytes to TX ringbuffer", wrote, len);`
to have the full information in DBG mode (can see if buffer is full).

File: subsys/usb/device/class/cdc_acm.c [hunk 4]
```diff
@@ -527,8 +527,7 @@ static int cdc_acm_fifo_fill(const struct device *dev,
 		dev_data, len, ring_buf_space_get(dev_data->tx_ringbuf));
```
[the remark this answers is not in the document]
Comment (metratec-mkoehler) [reply subsys/usb/device/class/cdc_acm.c:527]: I missed that point in the guideline.
My bad.
Changed it.

**Review by tmon-nordic — DISMISSED** [review]

File: subsys/usb/device/class/cdc_acm.c [hunk 5]
```diff
@@ -537,9 +536,7 @@ static int cdc_acm_fifo_fill(const struct device *dev,
 	lock = irq_lock();
 	wrote = ring_buf_put(dev_data->tx_ringbuf, tx_data, len);
 	irq_unlock(lock);
-	if (wrote < len) {
-		LOG_WRN("Ring buffer full, drop %zd bytes", len - wrote);
-	}
+	LOG_DBG("Wrote %zd of %zd bytes to TX ringbuffer", wrote, len);
```
Comment (jfischer-no) [inline subsys/usb/device/class/cdc_acm.c:539]: len is just `int`, but `size_t` is unsigned.

LOG_DBG("Wrote %zu of %d bytes to TX ringbuffer", wrote, len);

**Review by jfischer-no — APPROVED** [review]

**Review by tmon-nordic — APPROVED** [review]
