### PR TITLE
tests: kernel: timer_api fails with CONFIG_STM32_LPTIM_TIMER

### LINKED ISSUE #20991: test_timer_duration_period fails with stm32 lptimer
When the LPTIMER is enabled, the kernel test timer/timer_api fails in the 
"test_timer_duration_period: tdata.expire_cnt == 4 is false"

**To Reproduce**

1. Enable the LPTIMER in the proj.conf :
CONFIG_STM32_LPTIM_TIMER=y
CONFIG_STM32_LPTIM_CLOCK_LSE=y
2. mkdir build; cd build
3. cmake -DBOARD=board\nucleo_l4r5zi
4. make
5. See error
"Assertion failed at ZEPHYR_BASE/tests/kernel/timer/timer_api/src/main.c:138: test_timer_duration_period: tdata.expire_cnt == 4 is false "

### PR DESCRIPTION
**Pull request by FRASTM**
Testing kernel/timer/timer_API with LPTIM on stm32L4R5
the test_timer_duration_period fails w"
test_timer_duration_period: tdata.expire_cnt == 4 is false"

- changed z_timer_cycle_get_32() function to have better value returned in nb of HW cycles
- changed the calculation for next timeout in case of short delay
- source LPTIM with LSE or LSI clock for better accuracy
- reduce tick freq per sec and adjust for a better divided value of
 LPTIM_CLOCK % CONFIG_SYS_CLOCK_TICKS_PER_SEC

Activation of the LPTIM remains an experimental feature to generate kernel timings.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/20991

### CODE REVIEW

**Comment by FRASTM** [comment]
If the irq has not yet been handled but the counter just resets after the roll-over we must add thi roll-ove value in the actual counter position

**Comment by FRASTM** [comment]
Changed the calculation of the nb of hw cycles which is returned by the **z_timer_cycle_get_32()** function in case of LSE clock.
In case of LSI clock the both methods works.

Remaining work:  set a timeout close to the current counter.

**Comment by FRASTM** [comment]
This version passed kernel test on nulceo_l4r5zi board with LPTIM timer running on LSI clock
Device testing on:
nucleo_l4r5zi (None) on /dev/ttyACM0
Adding tasks to the queue...
total complete:   82/  82  100%  skipped:    8, failed:    0
74 of 82 tests passed (100.00%), 0 failed, 8 skipped with 0 warnings in 2287.16 seconds
In total 93 test cases were executed on 1 out of total 213 platforms (0.47%)

**Comment by FRASTM** [comment]
as nucleo_wb55rg board has CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=32000000
a LPTIM clock source of LSI=32000 gives better accuracy in lptimer calculations

**Comment by FRASTM** [comment]
on nucleo_wb55rg and nucleo_l4r5zi boards:
test passed with  _west build -b nucleo_wb55rg tests/kernel/fatal_
test passed with  _west build -b nucleo_wb55rg tests/kernel/sched/schedule_api_
test passed with  _west build -b nucleo_wb55rg tests/kernel/timer/_

**Comment by FRASTM** [comment]
add change for nucleo_wb55rg board

**Comment by FRASTM** [comment]
in the `tests/kernel/critical`, the test case regression_thread  is calling `k_sched_time_slice_set()`
	TC_PRINT("Enable timeslicing at %u\n", k_uptime_get_32());
	k_sched_time_slice_set(10, 10);
However in case of **CONFIG_TIMESLICING=n** the `k_sched_time_slice_set`  is not defined.
by the `kernel/sched.c`
Is it correct ?

**Comment by FRASTM** [comment]
test with dummy `k_sched_time_slice_set()` function

File: boards/arm/nucleo_l4r5zi/nucleo_l4r5zi_defconfig [hunk 1]
```diff
@@ -12,6 +13,14 @@ CONFIG_SOC_STM32L4R5XX=y
 # 80MHz system clock in 'normal power' mode
 CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=80000000
 
+CONFIG_STM32_LPTIM_TIMER=y
+CONFIG_STM32_LPTIM_CLOCK_LSE=y
+CONFIG_STM32_LPTIM_CLOCK_LSI=n
+# CONFIG_DEBUG=y
+CONFIG_TICKLESS_KERNEL=y
+CONFIG_TIMESLICING=n
+CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
```
Comment (erwango) [inline boards/arm/nucleo_l4r5zi/nucleo_l4r5zi_defconfig]: Do not impact default board configuration.
LPTIM conditional configuration could be done in board Kconfig.defconfig, but not here

File: boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig [hunk 2]
```diff
@@ -3,6 +3,14 @@ CONFIG_SOC_STM32WB55XX=y
...
 CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=32000000
 
+CONFIG_STM32_LPTIM_TIMER=y
+CONFIG_STM32_LPTIM_CLOCK_LSE=y
+CONFIG_STM32_LPTIM_CLOCK_LSI=n
+# CONFIG_DEBUG=y
+CONFIG_TICKLESS_KERNEL=y
+CONFIG_TIMESLICING=n
+CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
+
```
Comment (erwango) [inline boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig]: Do not impact default board configuration.
LPTIM conditional configuration could be done in board Kconfig.defconfig, but not here

File: boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig [hunk 3]
```diff
@@ -3,6 +3,14 @@ CONFIG_SOC_STM32WB55XX=y
 # 32MHz system clock
 CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=32000000
 
+CONFIG_STM32_LPTIM_TIMER=y
+CONFIG_STM32_LPTIM_CLOCK_LSE=y
+CONFIG_STM32_LPTIM_CLOCK_LSI=n
+# CONFIG_DEBUG=y
+CONFIG_TICKLESS_KERNEL=y
+CONFIG_TIMESLICING=n
```
Comment (erwango) [inline boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig]: Can you elaborate why you're changing these 2 settings (as I guess this is not anecdotal)

**Review by erwango — CHANGES_REQUESTED** [review]

File: soc/arm/st_stm32/stm32l4/dts_fixup.h [hunk 4]
```diff
@@ -74,4 +74,11 @@
 #define DT_LPTIM_1_CLOCK_BITS	DT_ST_STM32_TIMERS_40007C00_CLOCK_BITS_0
 #define DT_LPTIM_1_CLOCK_BUS	DT_ST_STM32_TIMERS_40007C00_CLOCK_BUS_0
 
+#define DT_LPTIM_1_BASE_ADDRESS	DT_ST_STM32_TIMERS_40007C00_BASE_ADDRESS
```
Comment (erwango) [inline soc/arm/st_stm32/stm32l4/dts_fixup.h:77]: This commit is not needed (defines are already available)

File: boards/arm/nucleo_l4r5zi/nucleo_l4r5zi_defconfig [hunk 5]
```diff
@@ -55,3 +55,6 @@ CONFIG_UART_CONSOLE=y
 
 # Enable MPU
 CONFIG_ARM_MPU=y
+
+# Enable LPTimer
+CONFIG_STM32_LPTIM_TIMER=y
```
Comment (erwango) [inline boards/arm/nucleo_l4r5zi/nucleo_l4r5zi_defconfig:60]: LPTIM should not be enabled by default.
Rather, it should be enabled as new configuration in timer test suites

File: soc/arm/st_stm32/stm32wb/dts_fixup.h [hunk 6]
```diff
@@ -43,4 +43,11 @@
 #define DT_LPTIM_1_CLOCK_BITS	DT_ST_STM32_TIMERS_40007C00_CLOCK_BITS_0
 #define DT_LPTIM_1_CLOCK_BUS	DT_ST_STM32_TIMERS_40007C00_CLOCK_BUS_0
 
+#define DT_LPTIM_1_BASE_ADDRESS	DT_ST_STM32_TIMERS_40007C00_BASE_ADDRESS
```
Comment (erwango) [inline soc/arm/st_stm32/stm32wb/dts_fixup.h:46]: This commit is not needed (defines are already available)

File: boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig [hunk 7]
```diff
@@ -31,3 +31,6 @@ CONFIG_UART_CONSOLE=y
 
 # Enable MPU
 CONFIG_ARM_MPU=y
+
+# Enable LPTimer
+CONFIG_STM32_LPTIM_TIMER=y
```
Comment (erwango) [inline boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig:36]: LPTIM should not be enabled by default.

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by FRASTM** [comment]
removed useless constant definition in dts_fixup.h

File: soc/arm/st_stm32/common/Kconfig.defconfig.series [hunk 8]
```diff
@@ -12,6 +12,9 @@ config CORTEX_M_SYSTICK
 	default n if STM32_LPTIM_TIMER
 	default y if !STM32_LPTIM_TIMER
 
+config SYS_CLOCK_TICKS_PER_SEC
+	default 1024 if STM32_LPTIM_TIMER
```
Comment (erwango) [inline soc/arm/st_stm32/common/Kconfig.defconfig.series:16]: Does it depends also on LPTIM clock source  (LSI or LSE)?
In that case, following would be better:
```
	default 1024 if STM32_LPTIM_TIMER AND STM32_LPTIM_CLOCK_LSE

**Review by erwango — CHANGES_REQUESTED** [review]
New comment.
Also please review remaining comments

File: soc/arm/st_stm32/common/Kconfig.defconfig.series (hunk 8 above)
Comment (FRASTM) [reply soc/arm/st_stm32/common/Kconfig.defconfig.series:16]: or even better:
```
config SYS_CLOCK_TICKS_PER_SEC
	default 1000 if STM32_LPTIM_CLOCK_LSI
	default 1024 if STM32_LPTIM_CLOCK_LSE
	depends on STM32_LPTIM_TIMER 
```

Comment (erwango) [reply soc/arm/st_stm32/common/Kconfig.defconfig.series:16]: Indeed!

File: boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig (hunk 2 above)
Comment (FRASTM) [reply boards/arm/nucleo_wb55rg/nucleo_wb55rg_defconfig]: The config for STM32_LPTIM_CLOCK  is now fixed to LSE, 
the config for SYS_CLOCK_TICKS_PER_SEC is fixed 
for all socs 
in the soc/arm/st_stm32/common/Kconfig.defconfig.series

File: boards/arm/nucleo_l4r5zi/nucleo_l4r5zi_defconfig (hunk 1 above)
Comment (FRASTM) [reply boards/arm/nucleo_l4r5zi/nucleo_l4r5zi_defconfig]: Enabling the LPTIMer is done in the board with 
CONFIG_STM32_LPTIM_TIMER=y

**Comment by FRASTM** [comment]
fix checkpatch issues

**Comment by FRASTM** [comment]
changing the testcases tests/kernel/timer for , nucleo_l4r5zi and nucleo_wb55rg boards
with a special config taht enables the LPTIM
TICKS_PER_SEC is set to 1000 and LSE is selected as LPTIM clock source for this tests

File: tests/kernel/timer/timer_api/testcase.yaml [hunk 9]
```diff
@@ -7,3 +7,10 @@ tests:
     arch_exclude: riscv32 nios2 posix
     platform_exclude: qemu_x86_coverage qemu_cortex_m0
     tags: kernel userspace
+  kernel.timer.tickless.stm32:
+    filter: dt_compat_enabled("stm32,lptim")
+    platform_whitelist: nucleo_wb55rg, nucleo_l4r5zi
```
Comment (erwango) [inline tests/kernel/timer/timer_api/testcase.yaml:12]: platform white listing is not needed following check on compatible

File: tests/kernel/timer/timer_monotonic/testcase.yaml [hunk 10]
```diff
@@ -1,3 +1,9 @@
 tests:
   kernel.timer.monotonic:
     tags: timer
+  kernel.timer.stm32:
+    filter: dt_compat_enabled("stm32,lptim")
+    platform_whitelist: nucleo_wb55rg, nucleo_l4r5zi
```
Comment (erwango) [inline tests/kernel/timer/timer_monotonic/testcase.yaml:6]: platform white listing is not needed following check on compatible

File: tests/kernel/timer/timer_monotonic/testcase.yaml [hunk 11]
```diff
@@ -1,3 +1,9 @@
 tests:
   kernel.timer.monotonic:
     tags: timer
+  kernel.timer.stm32:
```
Comment (erwango) [inline tests/kernel/timer/timer_monotonic/testcase.yaml:4]: kernel.timer.monotonic.stm32

**Review by erwango — CHANGES_REQUESTED** [review]
Few additional comments

Also please review commit message for "soc: arm: stm32 common lptim freq and SYS_CLOCK accuracy"

File: tests/kernel/timer/timer_api/testcase.yaml (hunk 9 above)
Comment (FRASTM) [reply tests/kernel/timer/timer_api/testcase.yaml:12]: removing the    ` platform_whitelist: nucleo_wb55rg, nucleo_l4r5zi`

File: tests/kernel/timer/timer_monotonic/testcase.yaml (hunk 10 above)
Comment (FRASTM) [reply tests/kernel/timer/timer_monotonic/testcase.yaml:6]: removing the      `platform_whitelist: nucleo_wb55rg, nucleo_l4r5zi`

File: tests/kernel/timer/timer_monotonic/testcase.yaml (hunk 11 above)
Comment (FRASTM) [reply tests/kernel/timer/timer_monotonic/testcase.yaml:4]: changing this test to `kernel.timer.monotonic.stm32`

**Comment by FRASTM** [comment]
update after erwango's review

File: tests/kernel/timer/timer_api/testcase.yaml [hunk 12]
```diff
@@ -7,3 +7,15 @@ tests:
     arch_exclude: riscv32 nios2 posix
     platform_exclude: qemu_x86_coverage qemu_cortex_m0
     tags: kernel userspace
+  kernel.timer.tickless.stm32:
+    filter: dt_compat_enabled("stm32,lptim")
```
Comment (erwango) [inline tests/kernel/timer/timer_api/testcase.yaml:11]: This compatible does not actually exists (LPTIM1 compat is "st,stm32-timers").
But indeed a dedicated lptim compatible is required so we don't mix with other general purpose timers

**Review by erwango — CHANGES_REQUESTED** [review]
We now need a dedicated st,stm32-lptim compatible for LPTIM1

**Comment by FRASTM** [comment]
Add the PR  https://github.com/zephyrproject-rtos/zephyr/pull/25126 to help fixing the issue https://github.com/zephyrproject-rtos/zephyr/issues/20991

**Comment by FRASTM** [comment]
When the LPTIM is needed, the  
CONFIG_STM32_LPTIM_TIMER=y
must be set

**Comment by FRASTM** [comment]
Takes the https://github.com/zephyrproject-rtos/zephyr/pull/25126
Configures some tests/kernel   testcases to include the LPTIM feature
Add a DT for the stm32-lptim yaml

File: dts/bindings/timer/st,stm32-lptim.yaml [hunk 13]
```diff
@@ -0,0 +1,5 @@
+description: STM32 lptim
```
Comment (erwango) [inline dts/bindings/timer/st,stm32-lptim.yaml:1]: Please put the usual header:
```
# Copyright (c) 2020, STMicroelectronics
# SPDX-License-Identifier: Apache-2.0
```

File: soc/arm/st_stm32/common/Kconfig.defconfig.series [hunk 14]
```diff
@@ -22,6 +22,10 @@ config SYS_CLOCK_TICKS_PER_SEC
 	default 4096
 	depends on STM32_LPTIM_TIMER && STM32_LPTIM_CLOCK_LSE
 
+config TICKLESS_KERNEL
```
Comment (erwango) [inline soc/arm/st_stm32/common/Kconfig.defconfig.series:25]: This should not be need as STM32_LPTIM_TIMER is declared TICKLESS_CAPABLE, and TICKLESS_KERNEL is declared in the following way:
```
config TICKLESS_KERNEL
	bool "Tickless kernel"
	default y if TICKLESS_CAPABLE
```
So the only protection needed is a check in driver to return an error if not support which is also proposed in this PR.
I think we can remove this commit safely.

**Review by erwango — DISMISSED** [review]

File: tests/kernel/timer/timer_api/testcase.yaml (hunk 12 above)
Comment (FRASTM) [reply tests/kernel/timer/timer_api/testcase.yaml]: adding a new compatible  = "st,stm32-lptim  especially for lptim, which is itself 'timers" compatible (9416b3d7d1ef91a2c0a3fc826e3b40ea6404871f)

**Comment by FRASTM** [comment]
Testing on nucleo_wb55rg with CONFIG_STM32_LPTIM_CLOCK_LSE and CONFIG_SYS_CLOCK_TICKS_PER_SEC=4096
--> tests/kernel/timer and tests/kernel/early_sleep PASSED
--> tests/kernel/sched/schedule_api/ still fails if CONFIG_TIMESLICING=y

File: dts/bindings/timer/st,stm32-lptim.yaml (hunk 13 above)
Comment (FRASTM) [reply dts/bindings/timer/st,stm32-lptim.yaml:1]: added also in the dts/bindings/timer/st,stm32-timers.yaml

File: soc/arm/st_stm32/common/Kconfig.defconfig.series (hunk 14 above)
Comment (FRASTM) [reply soc/arm/st_stm32/common/Kconfig.defconfig.series:25]: removed

**Comment by erwango** [comment]
@jdascenzio would you mind review this PR ?
If you agree your commits would be merged as part of this PR.

File: drivers/timer/stm32_lptim_timer.c [hunk 15]
```diff
@@ -274,15 +310,30 @@ u32_t z_timer_cycle_get_32(void)
...
+
 	lp_time += accumulated_lptim_cnt;
 
+	/* convert lptim count in a nb of hw cycles with precision */
+#if defined(CONFIG_STM32_LPTIM_CLOCK_LSI)
+	u64_t ret = lp_time * ((sys_clock_hw_cycles_per_sec() / 1000)
+		/ (LPTIM_CLOCK / 1000));
+#else
+	u64_t ret = lp_time * (sys_clock_hw_cycles_per_sec() / LPTIM_CLOCK);
+#endif /* CONFIG_STM32_LPTIM_CLOCK_LSI */
```
Comment (jdascenzio) [inline drivers/timer/stm32_lptim_timer.c:333]: Why it's different for LSI?
Here, I think you want to do:
```u64_t ret = (lp_time * sys_clock_hw_cycles_per_sec()) / LPTIM_CLOCK;```

File: soc/arm/st_stm32/common/Kconfig.defconfig.series [hunk 16]
```diff
@@ -9,8 +9,18 @@ if SOC_FAMILY_STM32
...
+
+# set the tick per sec as a divider of the LPTIM clock source
+config SYS_CLOCK_TICKS_PER_SEC
+	default 4000
+	depends on STM32_LPTIM_TIMER && STM32_LPTIM_CLOCK_LSI
+
+# set the tick per sec as a divider of the LPTIM clock source
+config SYS_CLOCK_TICKS_PER_SEC
+	default 4096
+	depends on STM32_LPTIM_TIMER && STM32_LPTIM_CLOCK_LSE
```
Comment (jdascenzio) [inline soc/arm/st_stm32/common/Kconfig.defconfig.series:23]: Like @aurel32 said (https://github.com/zephyrproject-rtos/zephyr/pull/25126#issuecomment-627639520), it could be interesting to have 32768 here instead of 4096

File: drivers/timer/stm32_lptim_timer.c [hunk 17]
```diff
@@ -226,6 +235,16 @@ void z_clock_set_timeout(s32_t ticks, bool idle)
...
+
+	/* If we are close to the roll over of the ticker counter
+	 * change current tick so it can be compared with buffer.
+	 * If this event got outdated fire interrupt right now,
+	 * else schedule it normally.
+	 */
+	if (next_arr <= ((LL_LPTIM_GetCounter(LPTIM1) + 1) & LPTIM_TIMEBASE)) {
+		NVIC_SetPendingIRQ(LPTIM1_IRQn);
+		lptim_fired = 1;
+	}
```
Comment (jdascenzio) [inline drivers/timer/stm32_lptim_timer.c:247]: LPTIM1 current value must be read like this:
```
	while (lp_time != LL_LPTIM_GetCounter(LPTIM1)) {
		lp_time = LL_LPTIM_GetCounter(LPTIM1);
	}
```

File: drivers/timer/stm32_lptim_timer.c [hunk 18]
```diff
@@ -50,6 +51,13 @@ static void lptim_irq_handler(struct device *unused)
 		/* do not change ARR yet, z_clock_announce will do */
 		LL_LPTIM_ClearFLAG_ARRM(LPTIM1);
 
+		if (lptim_fired) {
+			lptim_fired = 0;
+#if defined(LPTIM_CR_COUNTRST)
+			LL_LPTIM_ResetCounter(LPTIM1);
+#endif
+		}
+
```
Comment (jdascenzio) [inline drivers/timer/stm32_lptim_timer.c:60]: When lptim_fired, I think that LL_LPTIM_IsActiveFlag_ARRM could be not set...

File: drivers/timer/stm32_lptim_timer.c [hunk 19]
```diff
@@ -251,12 +270,29 @@ u32_t z_clock_elapsed(void)
...
+	return (u32_t)(ret);
+#else
+	u64_t ret = (lp_time * CONFIG_SYS_CLOCK_TICKS_PER_SEC) / LPTIM_CLOCK;
+
+	return (u32_t)(ret);
+#endif /* CONFIG_STM32_LPTIM_CLOCK_LSI */
 
 	/* convert to ticks */
 	return z_ms_to_ticks(ret);
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/timer/stm32_lptim_timer.c:298]: correct

File: drivers/timer/stm32_lptim_timer.c [hunk 20]
```diff
@@ -251,12 +270,29 @@ u32_t z_clock_elapsed(void)
...
+#if defined(CONFIG_STM32_LPTIM_CLOCK_LSI)
+	u32_t ret = (lp_time * (CONFIG_SYS_CLOCK_TICKS_PER_SEC / 1000))
+		/ (LPTIM_CLOCK / 1000);
+
+	return (u32_t)(ret);
+#else
+	u64_t ret = (lp_time * CONFIG_SYS_CLOCK_TICKS_PER_SEC) / LPTIM_CLOCK;
+
+	return (u32_t)(ret);
+#endif /* CONFIG_STM32_LPTIM_CLOCK_LSI */
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/timer/stm32_lptim_timer.c:295]: just a question of type, which could be simplified with u64_t in all cases

File: soc/arm/st_stm32/common/Kconfig.defconfig.series (hunk 16 above)
Comment (FRASTM) [reply soc/arm/st_stm32/common/Kconfig.defconfig.series:23]: Yes, but this value of 32768 for TICKS_PER_SEC is too high and cannot pass the kernel/tests timers_api

Comment (FRASTM) [reply soc/arm/st_stm32/common/Kconfig.defconfig.series:23]: testing kernel/tests on nucleo_l4r5zi with
CONFIG_STM32_LPTIM_TIMER=y1
CONFIG_SYS_CLOCK_TICKS_PER_SEC=32768

**Comment by FRASTM** [comment]
running testcases  kernel/tests on nucleo_l4r5zi with
CONFIG_STM32_LPTIM_TIMER=y1
CONFIG_SYS_CLOCK_TICKS_PER_SEC=32768

File: drivers/timer/stm32_lptim_timer.c [hunk 21]
```diff
@@ -193,17 +193,8 @@ void z_clock_set_timeout(s32_t ticks, bool idle)
...
-		ticks = (ticks - 1);
-	}
-	/* maximise Tick to keep next_arr on 32bit values,
-	 * in anycase the ARR cannot exceed LPTIM_TIMEBASE
-	 */
-	if (ticks > (s32_t)0xFFFF) {
-		ticks = 0xFFFF;
-	}
+	ticks = (ticks == K_TICKS_FOREVER) ? LPTIM_TIMEBASE : ticks;
+	ticks = MAX(MIN(ticks - 1, (s32_t)LPTIM_TIMEBASE), 1);
```
[the remark this answers is not in the document]
Comment (FRASTM) [reply drivers/timer/stm32_lptim_timer.c:206]: correct, 
if TICKS ==  K_TICKS_FOREVER  lptim has been stopped just before.
Since the LL_LPTIM_Disable does not exist, the LPTIM clock is stopped.

File: drivers/timer/stm32_lptim_timer.c (hunk 15 above)
Comment (FRASTM) [reply drivers/timer/stm32_lptim_timer.c]: simplification to have the same return value in case of LSI or LSE

**Comment by FRASTM** [comment]
adding the https://github.com/zephyrproject-rtos/zephyr/pull/25412  in case of tests with CONFIG_TICKLESS_KERNEL=n
Test with nucleo_l4r5zi with LPTIM sourced by LSE and TICKS_PER_SEC=4096

**Comment by carlescufi** [comment]
@erwango could you take a look at this one?

**Comment by FRASTM** [comment]
Note that test/kernel/interrupt 
still few tests fail on l4r5zi with LSE clock source and TICKS_PER_SEC=4096
tests/kernel/common/kernel.common   
tests/kernel/sleep/   
tests/kernel/fifo/fifo_timeout/kernel.fifo.timeout

Note that tests/kernel/interrupt  could fail due to the irq pemption on lptim irq itself

**Comment by carlescufi** [comment]
@erwango @jdascenzio can we move this forward so we can get the fix in in time for 2.3.0? Thanks!

File: drivers/timer/stm32_lptim_timer.c (hunk 17 above)
Comment (FRASTM) [reply drivers/timer/stm32_lptim_timer.c:246]: changed LL_LPTIM_GetCounter  with lp_time value as this variable is already set.

**Comment by carlescufi** [comment]
@erwango can you take another look at the PR after @FRASTM pushed an update?

**Review by andyross — APPROVED** [review]
Late to this one, sorry.  I can't speak to the hardware obviously, but the timer logic all looks correct.

File: soc/arm/st_stm32/common/Kconfig.defconfig.series [hunk 22]
```diff
@@ -9,8 +9,16 @@ if SOC_FAMILY_STM32
...
+	default y
+	depends on !STM32_LPTIM_TIMER
+
+# set the tick per sec as a divider of the LPTIM clock source
+config SYS_CLOCK_TICKS_PER_SEC
+	default 4096 if STM32_LPTIM_TIMER && STM32_LPTIM_CLOCK_LSE
+
+# set the tick per sec as a divider of the LPTIM clock source
+config SYS_CLOCK_TICKS_PER_SEC
+	default 4000 if  STM32_LPTIM_TIMER && STM32_LPTIM_CLOCK_LSI
```
Comment (erwango) [inline soc/arm/st_stm32/common/Kconfig.defconfig.series:21]: Please make this as follows:
```
# set the tick per sec as a divider of the LPTIM clock source
config SYS_CLOCK_TICKS_PER_SEC
	default 4096 if STM32_LPTIM_TIMER && STM32_LPTIM_CLOCK_LSE
	default 4000 if STM32_LPTIM_TIMER && STM32_LPTIM_CLOCK_LSI
```

File: drivers/timer/Kconfig.stm32_lptim [hunk 23]
```diff
@@ -17,26 +17,26 @@ if STM32_LPTIM_TIMER
...
+	help
+	  Use LSI as LPTIM clock
+
 endchoice
 
 config STM32_LPTIM_CLOCK
 	int "LPTIM clock value"
-	default 32000 if STM32_LPTIM_CLOCK_LSI
 	default 32768 if STM32_LPTIM_CLOCK_LSE
+	default 32000 if STM32_LPTIM_CLOCK_LSI
```
Comment (erwango) [inline drivers/timer/Kconfig.stm32_lptim:35]: Not useful but ok

File: drivers/timer/Kconfig.stm32_lptim [hunk 24]
```diff
@@ -17,26 +17,26 @@ if STM32_LPTIM_TIMER
...
 
 config STM32_LPTIM_TIMEBASE
 	hex "LPTIM AutoReload value"
-	default 0xF9FF if STM32_LPTIM_CLOCK_LSI
 	default 0xFFFF if STM32_LPTIM_CLOCK_LSE
+	default 0xF9FF if STM32_LPTIM_CLOCK_LSI
```
Comment (erwango) [inline drivers/timer/Kconfig.stm32_lptim:40]: Not useful but ok

File: boards/arm/nucleo_l4r5zi/Kconfig.defconfig [hunk 25]
```diff
@@ -9,7 +9,7 @@ config BOARD
 	default "nucleo_l4r5zi"
 
 choice STM32_LPTIM_CLOCK
-	default STM32_LPTIM_CLOCK_LSI
+	default STM32_LPTIM_CLOCK_LSE
 	depends on STM32_LPTIM_TIMER
 endchoice
```
Comment (erwango) [inline boards/arm/nucleo_l4r5zi/Kconfig.defconfig:14]: I think we could completely remove this choice section.

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by erwango** [comment]
@jdascenzio, are you fine with the last changes ?

File: boards/arm/nucleo_l4r5zi/Kconfig.defconfig (hunk 25 above)
Comment (FRASTM) [reply boards/arm/nucleo_l4r5zi/Kconfig.defconfig:14]: yes, removed

**Comment by FRASTM** [comment]
change after @erwango 's review

File: drivers/timer/Kconfig.stm32_lptim (hunk 24 above)
Comment (FRASTM) [reply drivers/timer/Kconfig.stm32_lptim:40]: setting LSE in first position to have this as default ?

File: boards/arm/nucleo_l4r5zi/Kconfig.defconfig (hunk 25 above)
Comment (FRASTM) [reply boards/arm/nucleo_l4r5zi/Kconfig.defconfig]: yes, removed

File: dts/arm/st/l4/stm32l4.dtsi [hunk 26]
```diff
@@ -340,7 +340,7 @@
 		};
 
 		lptim1: timers@40007c00 {
-			compatible = "st,stm32-timers";
+			compatible = "st,stm32-lptim";
```
Comment (erwango) [inline dts/arm/st/l4/stm32l4.dtsi:343]: Can you fix this on stm32wb as well ?

File: drivers/timer/Kconfig.stm32_lptim (hunk 24 above)
Comment (erwango) [reply drivers/timer/Kconfig.stm32_lptim:40]: Position only matters for choice (like STM32_LPTIM_CLOCK) actually

**Review by erwango — CHANGES_REQUESTED** [review]
Few more tweaks and I'm good

**Comment by FRASTM** [comment]
rebase

File: drivers/timer/Kconfig.stm32_lptim [hunk 27]
```diff
@@ -4,8 +4,8 @@
 # SPDX-License-Identifier: Apache-2.0
 
 menuconfig STM32_LPTIM_TIMER
-	bool "STM32 Low Power Timer"
-	depends on (SOC_SERIES_STM32L4X || SOC_SERIES_STM32WBX)
+	bool "STM32 Low Power Timer [EXPERIMENTAL]"
+	depends on SOC_SERIES_STM32L4X && DEVICE_POWER_MANAGEMENT
```
Comment (aurel32) [inline drivers/timer/Kconfig.stm32_lptim:8]: Minor nitpick: I don't fully see the relation of why the LPTIM support needs to depend on DEVICE_POWER_MANAGEMENT.

**Review by aurel32 — APPROVED** [review]
Beside the minor nitpick, all looks good. I tested it on a Nucleo L432Kc board and I confirm the issue is fixed by this PR.

**Comment by aurel32** [comment]
Another comment: when setting `SYS_CLOCK_TICKS_PER_SEC=32768` (instead of 4096) with a LSI OSC, `test_timer_remaining` fails.

This seems to be a math issue in `k_busy_wait` and setting both `CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC` and `SYS_CLOCK_TICKS_PER_SEC` to 32768 (like done on the nRF52 series) just makes the issue to disappear.

**Comment by carlescufi** [comment]
@erwango please re-review

File: dts/arm/st/l4/stm32l4.dtsi (hunk 26 above)
Comment (FRASTM) [reply dts/arm/st/l4/stm32l4.dtsi:343]: yes

File: drivers/timer/Kconfig.stm32_lptim (hunk 27 above)
Comment (FRASTM) [reply drivers/timer/Kconfig.stm32_lptim:8]: My goal is to link lptim to low power mode. 
This let kernel timer unchanged for most of the usecase.
The lptim is able to preserve the kernel tick counter during low power sleep mode : only in this case is the lptim configured to keep the kernel timeout. 
Refering to  power: stm32l4: support of the Low Power Mode #19026

**Comment by FRASTM** [comment]
include lptim in  the stm32wbx series

**Review by erwango — APPROVED** [review]

File: drivers/timer/Kconfig.stm32_lptim (hunk 27 above)
Comment (aurel32) [reply drivers/timer/Kconfig.stm32_lptim]: Understood. In that case shouldn't it be `SYS_POWER_MANAGEMENT` instead of `DEVICE_POWER_MANAGEMENT`?
