### PR TITLE
Bluetooth: GATT: Fixes

### LINKED ISSUE #18547: Bluetooth: GATT: Fix using variable size storage for CCC
The BT_GATT_CCC API was introduced before settings existed so at point that was no other option then to leave up to the application to define a variable to store it, fast forward 2.0 and we now have the stack handling the storage on settings but still leaving the services to define it which may lead to problems since it must be defined with at least BT_GATT_CCC_MAX elements in order to properly adhere to the Bluetooth specification.

### PR DESCRIPTION
**Pull request by Vudentz**
Some small fixes to BT_GATT_CCC to actually the declare its storage internally and bt_gatt_indicate to allow indicating by UUID.

Fixes #18547 #18572

### CODE REVIEW

**Comment by jhedberg** [comment]
Does this need backporting?

**Comment by Vudentz** [comment]
> Does this need backporting?

Not really, there are in fact enhancements.

**Review by jhedberg — APPROVED** [review]

**Comment by nvlsianpu** [comment]
cc @rakons

**Review by trond-snekvik — APPROVED** [review]

File: subsys/bluetooth/host/gatt.c [hunk 1]
```diff
@@ -1634,18 +1638,37 @@ int bt_gatt_indicate(struct bt_conn *conn,
...
 	u16_t handle;
 
 	__ASSERT(params, "invalid parameters\n");
 	__ASSERT(params->attr, "invalid parameters\n");
 
-	handle = params->attr->handle ? : find_static_attr(params->attr);
+	attr = params->attr;
+
+	handle = attr->handle ? : find_static_attr(attr);
 	if (!handle) {
```
Comment (joerchan) [inline subsys/bluetooth/host/gatt.c]: It looks to me like the user still has to provide a valid `attr`? Or am I misunderstanding?

Comment (Vudentz) [reply subsys/bluetooth/host/gatt.c]: Yes, it is used as start location so it can either point to the start of its services, more likely, or handle 0x0001.

**Review by joerchan — APPROVED** [review]
