### PR TITLE
drivers: nrf: Fix values in UARTE async API callback.

### LINKED ISSUE #20000: Invalid callback parameters in drivers/serial/uart_nrfx_uarte.c (using async API)
**Describe the bug**

Data is received via the nRFx UARTE driver, using the experimental asynchronous API, with hardware counting enabled. As buffers fill up, new ones are requested by the driver using callbacks, and in our application we supply them in a round-robin fashion from a pre-allocated set. When some data has been received, the application is notified by means of a calllback (RX_RDY) with a buffer pointer, an offset, and a length.

Sometimes, these callback parameters are invalid. The length can become negative, and in subsequent callbacks the negative length has been accumulated into the offset, making it negative as well.

This happens when `rx_total_user_byte_cnt` becomes larger than `rx_total_byte_cnt`.

From what I can see, `rx_total_user_byte_cnt` correctly reflects the total number of bytes reported to the application. Thus, the error seems to be that `rx_total_byte_cnt` (total number of bytes received) may end up with a value that is too low.

**Additional information**

`rx_total_byte_cnt` is periodically sampled from a hardware counter configured to count RXDRDY events from the UARTE peripheral. These are the same events that drive the DMA channel. Callbacks to the application are generated in two places: From a timer interrupt, if the hardware counter has remained static for a specified amount of time, as well as from a DMA ENDRX handler, when the current buffer is full.

Note that when the last byte in a buffer is received, the ENDRX event is generated slightly later than the RXDRDY event. If the timer interrupt is triggered in that brief moment, there is a potential race condition. This may or may not be related to the observed bug.

**To Reproduce**

1. Configure thus: (We use timer 3, but this shouldn't matter)
```
CONFIG_UART_0_NRF_UARTE=y
CONFIG_UART_0_NRF_HW_ASYNC=y
CONFIG_UART_0_NRF_HW_ASYNC_TIMER=3
CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_UART_ASYNC_API=y
```

2. In the device tree:
```
&uart0 {
     compatible = "nordic,nrf-uarte";
     ...
}
```

3. Write an application that receives data, similar to `test_double_buffer()` in `zephyr/tests/drivers/uart/uart_async_api`. In the RX_RDY callback, log the offset and length parameters.

4. Build for some board, e.g. an nRF devkit.

5. Supply data over the UART. This should be a mixture of short and long packets, separated by pauses that are greater than the timeout specified in `rx_enable()`.

6. Observe error (negative parameters).

**Expected behavior**

The RX_RDY callbacks should report incoming bytes correctly, in order, with valid parameters.

**Impact**

This issue is stopping us from migrating an existing product from Nordic SDK + SoftDevice to Zephyr. We need to transition to Zephyr in order to deliver an important feature (which cannot be implemented using SoftDevice).

We cannot use the synchronous API for performance reasons.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: gcc-arm-none-eabi-7-2018-q2-update, ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
 - The bug is present both in Release 1.14.1 and in f79fbac101f8febb459acee577e9f6b76e00acc0 (Oct 17, 2019).

Note in particular that the bug exists after:
4a13041c38c848118181907e912878a42d16e36f drivers: uart: Fix incorrect len and offset in nrf UARTE async API.
and
f2bd628c5ad3a2570a63bb2138ff2e803ea5cd62 drivers: nrf: Fix RX timeout and ENDRX ISR handling.

Especially the former fix (4a13...) seems related, although in that case the system was not configured to use a hardware counter.

### PR DESCRIPTION
**Pull request by Mierunski**
There is possibility that endrx interrupt will be triggered in the
middle of timer interrupt responsible for UARTE timeout, this
patch handles this case.

Fixes #20000 

Signed-off-by: Mieszko Mierunski <mieszko.mierunski@nordicsemi.no>

### CODE REVIEW

**Comment by Mierunski** [comment]
FYI @linus-te

File: drivers/serial/uart_nrfx_uarte.c [hunk 1]
```diff
@@ -632,13 +632,13 @@ static void rx_timeout(struct k_timer *timer)
 	}
 
 	/* Check if there is data that was not sent to user yet */
-	if (data->async->rx_total_byte_cnt
-	    != data->async->rx_total_user_byte_cnt) {
+
+	u32_t len = data->async->rx_total_byte_cnt
```
Comment (nordic-krch) [inline drivers/serial/uart_nrfx_uarte.c]: shouldn't that be `s32_t`?
according to the issue report, it is possible that user_byte_cnt can be larger than total:

>This happens when rx_total_user_byte_cnt becomes larger than rx_total_byte_cnt.

**Review by nordic-krch — APPROVED** [review]

**Comment by ioannisg** [comment]
@linus-te could you check if this fixes your issue reported in #20000 ?

**Comment by linus-te** [comment]
Confirmed! This change seems to fix the problem.

**Review by MaureenHelm — APPROVED** [review]

**Comment by jsiverskog** [comment]
should this be backported to the v1.14 branch?
