### PR TITLE
Log backend for  x86_64 qemu

### LINKED ISSUE #17555: CONFIG_LOG doesn't work on x86_64 due to no working backends
Something seems to be broken with logging enabled on the x86_64 platform.

Steps to reproduce:

Modify tests/kernel/fatal/prj.conf and add CONFIG_LOG=y

Build and run the test on qemu_x86_64:

```
SeaBIOS (version rel-1.12.0-0-ga698c8995f-prebuilt.qemu.org)
Booting from ROM..Running test suite fatal
===================================================================
starting test - test_fatal
test alt thread 1: generic CPU exception
*** FATAL ERROR vector 6 code 0
***  RIP 8:0x1002f7 RSP 16:0x106d78 RFLAGS 0x202
***  RAX 0x1002f7 RCX 0x0 RDX 0x0 RSI 0x0 RDI 0x0
***  R8 0x0 R9 0x0 R10 0x0 R11 0x0
Caught system error -- reason 0
test alt thread 2: initiate kernel oops
*** FATAL ERROR vector 5 code 0
***  RIP 8:0x1003fe RSP 16:0x106d70 RFLAGS 0x2
***  RAX 0x1003ee RCX 0x0 RDX 0x0 RSI 0x0 RDI 0x0
***  R8 0x0 R9 0x0 R10 0x0 R11 0x0
Caught system error -- reason 2
test alt thread 3: initiate kernel panic
*** FATAL ERROR vector 5 code 0
***  RIP 8:0x1003b4 RSP 16:0x106d70 RFLAGS 0x2
***  RAX 0x1003a4 RCX 0x0 RDX 0x0 RSI 0x0 RDI 0x0
***  R8 0x0 R9 0x0 R10 0x0 R11 0x0
Caught system error -- reason 3
test alt thread 4: fail assertion
ASSERTION FAIL [0] @ ZEPHYR_BASE/tests/kernel/fatal/src/main.c:125
	intentionally failed assertion
*** FATAL ERROR vector 5 code 1016
***  RIP 8:0x100ece RSP 16:0x106d68 RFLAGS 0x202
***  RAX 0x104f1f RCX 0xa RDX 0x3f8 RSI 0x7d RDI 0x104eb8
***  R8 0xffffffff R9 0x0 R10 0x0 R11 0x0
Caught system error -- reason 3
PASS - test_fatal
===================================================================
Test suite fatal succeeded
===================================================================
PROJECT EXECUTION SUCCESSFUL
ASSERTION FAIL [log_backend_count_get() > 0] @ ZEPHYR_BASE/subsys/logging/log_core.c:829
*** FATAL ERROR vector 5 code 1016
***  RIP 8:0x100ece RSP 16:0x107068 RFLAGS 0x202
***  RAX 0x104efe RCX 0xa RDX 0x3f8 RSI 0x33d RDI 0x1050fc
***  R8 0xffffffff R9 0x0 R10 0x0 R11 0x0
Caught system error -- reason 3
```

It's not just this test either.

### PR DESCRIPTION
**Pull request by nordic-krch**
- Added log backend for x86_64 qemu
- Added `log_backend_std.h` with helper functions for simple backends
- Refactored simple logger backends to use functions (reduced code redundancy)

Fixes #17555.

If #17585 goes in before that it should be reverted in that PR.

### CODE REVIEW

**Review by masz-nordic — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by tyrantlizard77 — APPROVED** [review]

File: subsys/logging/log_backend_std.h [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+	}
+
+	if (IS_ENABLED(CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP)) {
+		flags |= LOG_OUTPUT_FLAG_FORMAT_TIMESTAMP;
+	}
+
+	log_output_msg_process(log_output, msg, flags);
+
+	log_msg_put(msg);
+
```
Comment (mnkp) [inline subsys/logging/log_backend_std.h]: Redundant empty line.

File: subsys/logging/log_backend_qemu_x86_64.c [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+}
+
+static char buf;
+LOG_OUTPUT_DEFINE(log_output, char_out, &buf, sizeof(buf));
+
+static void put(const struct log_backend *const backend,
+		struct log_msg *msg)
+{
+	log_backend_std_put(&log_output, 0, msg);
+
```
Comment (mnkp) [inline subsys/logging/log_backend_qemu_x86_64.c]: Redundant empty line.

File: subsys/logging/log_backend_qemu_x86_64.c [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+#include <stdio.h>
+#include <stddef.h>
+#include <logging/log_backend.h>
+#include <logging/log_msg.h>
+#include <logging/log_output.h>
+#include "log_backend_std.h"
+#include <../core/serial.h>
+
+static int char_out(u8_t *data, size_t length, void *ctx)
+{
```
Comment (mnkp) [inline subsys/logging/log_backend_qemu_x86_64.c]: `ARG_UNUSED(ctx);` ?

**Review by mnkp — COMMENTED** [review]
LGTM with minor comments.

File: subsys/logging/log_backend_std.h (hunk 1 above)
Comment (nordic-krch) [reply subsys/logging/log_backend_std.h]: done

File: subsys/logging/log_backend_qemu_x86_64.c (hunk 2 above)
Comment (nordic-krch) [reply subsys/logging/log_backend_qemu_x86_64.c]: done

File: subsys/logging/log_backend_qemu_x86_64.c (hunk 3 above)
Comment (nordic-krch) [reply subsys/logging/log_backend_qemu_x86_64.c]: done

**Review by ioannisg — COMMENTED** [review]
Looks ok, I left a question about a kconfig setting

**Review by carlescufi — APPROVED** [review]

File: subsys/logging/Kconfig [hunk 4]
```diff
@@ -362,6 +362,13 @@ config LOG_BACKEND_NATIVE_POSIX
 	help
 	  Enable backend in native_posix
 
+config LOG_BACKEND_QEMU_X86_64
+	bool "Enable QEMU x86_64 backend"
+	depends on BOARD_QEMU_X86_64
+	default y
```
[the remark this answers is not in the document]
Comment (carlescufi) [reply subsys/logging/Kconfig]: Because it's the default logger for BOARD_QEMU_X86_64. It will only be enabled if that board is selected

[the remark this answers is not in the document]
Comment (ioannisg) [reply subsys/logging/Kconfig]: Shouldn't we, then, just select this in the board definition?

[the remark this answers is not in the document]
Comment (carlescufi) [reply subsys/logging/Kconfig]: Actually it's a good point. I assume there's no default UART backend on x86_64, but maybe this should be:
default y if BOARD_QEMU_X86_64

[the remark this answers is not in the document]
Comment (ioannisg) [reply subsys/logging/Kconfig]: I believe anything that is board specific should be at least _selected_ at the board definition, rather than using default y. What is there are multiple backends for _64 in the future? Would we need to set this one to =n?

**Review by nashif — APPROVED** [review]

File: subsys/logging/Kconfig (hunk 4 above)
[the remark this answers is not in the document]
Comment (nordic-krch) [reply subsys/logging/Kconfig]: removed `default y` and moved setting it to  `qemu_x86_64_defconfig` file.

**Comment by andrewboie** [comment]
Build error is spurious, please push again
