### PR TITLE
mcux: flexcan: fixes the race condition

### LINKED ISSUE #52673: mcux: flexcan: forever waiting semaphore in can_send()
If you call the `can_send()` function from several **threads** with **different priorities** with the function arguments **timeout = K_FOREVER** and **callback = NULL**, then after a certain period of time, for some reason, the thread will endlessly wait for the semaphore.
**Updated**: Hang is not observed if threads have the same priority.

 - mimxrt1064_evk board
 - CAN baud rate 1Mbit/s
 - A thread with the highest priority hangs more often.

**To Reproduce**
`main.c`:
```c
#include <zephyr/drivers/can.h>
#include <zephyr/random/rand32.h>
#include <stdio.h>


#define THREAD_NUM 4
#define STATE_THREAD_STACK_SIZE 1024
K_KERNEL_STACK_ARRAY_DEFINE(state_stack, THREAD_NUM, STATE_THREAD_STACK_SIZE);
static struct k_thread state_thread_data[THREAD_NUM];

static int32_t threads_prior[THREAD_NUM] = {2, 4, 7, 2};

struct can_config
{
    uint8_t thr_n;
    uint8_t frame_count;
    uint32_t period;
    uint8_t prior;
};

static struct can_config can_cfg[THREAD_NUM];


void can_thread(void *arg1, void *arg2, void *arg3)
{
    const struct device *can_dev = (const struct device *)arg1;
    const struct can_config *cancfg = (const struct can_config *)arg2;

    int ret;
    struct can_frame frame = {
        .dlc = 8,
        .flags = CAN_FRAME_IDE,
        .id = 0xDEAD00 + cancfg->thr_n,
        .data = {0x00, cancfg->thr_n, cancfg->prior, 0xfa, 0x1e, 0x09, 0x37, 0xdb}
    };

    while(1)
    {
        for(uint8_t i = 0; i < cancfg->frame_count; i++)
        {
            frame.data[0] = i;
            ret = can_send(can_dev, &frame, K_FOREVER, NULL, NULL);
            if (ret != 0)
            {
                printf("CAN: Error: %d\n", ret);
                k_sleep(K_MSEC(1000));
            }
        }
        k_sleep(K_MSEC(cancfg->period));
    }
}

void main(void) 
{
    printf("\nFLEXCAN testing\n");
    printf(  "==================\n");

    const struct device *can_dev = DEVICE_DT_GET(DT_NODELABEL(flexcan2));

    if (!device_is_ready(can_dev)) {
        printf("CAN: Device %s not ready.\n", can_dev->name);
        return;
    }

    printf("device %s is ready\n", can_dev->name);

    int ret = can_start(can_dev);
    if (ret != 0) {
        printf("Error starting CAN controller [%d]\n", ret);
        return;
    }

    for (uint8_t i = 0; i < THREAD_NUM; i++)
    {
        uint32_t rand_num = sys_rand32_get();
        can_cfg[i].thr_n = i;
        can_cfg[i].frame_count = (rand_num & 0xFE) + 1;
        can_cfg[i].period = ((rand_num >> 8) & 0x7F) + 50;
        can_cfg[i].prior = threads_prior[i]; //((rand_num >> 15) & 0xF) + 1;

        printf("thread: %d, frame count: %3d, period: %3d, priority: %2d\n",
            can_cfg[i].thr_n, can_cfg[i].frame_count, can_cfg[i].period, can_cfg[i].prior);

        k_tid_t can_thr = k_thread_create(&state_thread_data[i],
                            state_stack[i],
                            K_THREAD_STACK_SIZEOF(state_stack[i]),
                            can_thread, can_dev, &can_cfg[i], NULL,
                            can_cfg[i].prior, 0,
                            K_NO_WAIT);

        if (!can_thr) {
            printf("ERROR spawning thread %d\n", 0);
            break;
        }
    }
}
```
`prj.conf`:
```
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_DEBUG=y
CONFIG_DEBUG_THREAD_INFO=y

CONFIG_MAIN_STACK_SIZE=16384
CONFIG_ISR_STACK_SIZE=16384
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=16384

CONFIG_HEAP_MEM_POOL_SIZE=32768

CONFIG_CAN=y
CONFIG_CAN_MCUX_FLEXCAN=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_ENTROPY_DEVICE_RANDOM_GENERATOR=y
```

**Environment:**
 - OS: Windows 10 Pro (21H2)
 - Toolchain Zephyr SDK
 - Zephyr version 3.2.99 (commit 21a6bb3d2da332e2a6e024a6e7e38ace1f08175f)

### PR DESCRIPTION
**Pull request by MikhailSiomin**
Since the FLEXCAN_TransferSendNonBlocking() function has read-modify-write operations on global resources, then if interrupts are enabled and/or if there is more than one thread with a different priority, threads with a lower priority can overwrite global resource changes made by higher priority threads.
Fixes #52673.

Signed-off-by: Mikhail Siomin <victorovich.01@mail.ru>

### CODE REVIEW

File: drivers/can/can_mcux_flexcan.c [hunk 1]
```diff
@@ -467,8 +469,12 @@ static int mcux_flexcan_send(const struct device *dev,
 	xfer.frame = &data->tx_cbs[alloc].frame;
 	xfer.mbIdx = ALLOC_IDX_TO_TXMB_IDX(alloc);
 	FLEXCAN_SetTxMbConfig(config->base, xfer.mbIdx, true);
+	k_mutex_lock(&data->tx_mutex, K_FOREVER);
+	irq_disable(config->irq_n);
```
Comment (alexanderwachter) [inline drivers/can/can_mcux_flexcan.c:473]: Did not check if there is a race condition, but a spin lock would we appropriate here instead if irq disable and a mutex.

**Review by alexanderwachter — CHANGES_REQUESTED** [review]

File: drivers/can/can_mcux_flexcan.c (hunk 1 above)
Comment (MikhailSiomin) [reply drivers/can/can_mcux_flexcan.c:473]: @alexanderwachter, my proposed solution affects only CAN interrupts and all threads working with CAN. If we use a spin lock, we will make all threads wait. The race condition can be seen for example [here](https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/mcux-sdk/drivers/flexcan/fsl_flexcan.h#L1676-L1679).

File: drivers/can/can_mcux_flexcan.c [hunk 2]
```diff
@@ -966,6 +973,7 @@ static const struct can_driver_api mcux_flexcan_driver_api = {
 		.irq_config_func = mcux_flexcan_irq_config_##id,	\
 		.phy = DEVICE_DT_GET_OR_NULL(DT_INST_PHANDLE(id, phys)),\
 		.max_bitrate = DT_INST_CAN_TRANSCEIVER_MAX_BITRATE(id, 1000000), \
+		.irq_n = DT_INST_IRQ_BY_NAME(id, common, irq), \
```
Comment (henrikbrixandersen) [inline drivers/can/can_mcux_flexcan.c:976]: Beware that the number of IRQs used depends on the SoC. Not all use the `common` IRQ, so this will not work across all supported SoCs.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]

File: drivers/can/can_mcux_flexcan.c (hunk 1 above)
Comment (alexanderwachter) [reply drivers/can/can_mcux_flexcan.c:473]: IRQ disable prevents any other thread to run too. How can the thread be interrupted if not from an irq?

Comment (alexanderwachter) [reply drivers/can/can_mcux_flexcan.c:473]: Ah. Now I see. You want to only disable the send irq?

Comment (MikhailSiomin) [reply drivers/can/can_mcux_flexcan.c]: I suggest disable all interrupts.

File: drivers/can/can_mcux_flexcan.c (hunk 2 above)
Comment (MikhailSiomin) [reply drivers/can/can_mcux_flexcan.c]: I tried to fix it in the next commit 2e89435f761f1f619589efbaf3a2c302e2a3d4da. I suggest to list all interrupt names in `interrupt-names` property and generate two additional functions to enable and disable interrupts.

Comment (henrikbrixandersen) [reply drivers/can/can_mcux_flexcan.c]: Thanks. I suggest squashing the two commits into one.

**Comment by dleach02** [comment]
@MikhailSiomin trying to catch up here on the root problem. 

I see the mutex around the TransferSendNonBlocking() function call but from the comments in the issue I'm trying to see where, or if, this should be fixed in the HAL.  You discuss the problems with the IMASK1 IMASK2 registers, did you capture a race between the FLEXCAN_WriteTxMb() and the enabling of the Mb interrupt?

**Comment by GrixaYrev** [comment]
@dleach02 let me join the conversation. It seems that `FLEXCAN_WriteTxMb()` work with separate data of single MB. In contrast `FLEXCAN_EnableMbInterrupts()` use share resource (**IMASK1** and **IMASK2** registers). 

Potential trouble:

1. Low priority thread read the register.
2. High priority thread (or IRQ) preemptive low priority thread.
3. High priority thread (or IRQ) change value of the register.
4. Low priority thread resume and write the register and overwrite change, high priority thread (or IRQ) has made.

As a result high priority thread can deadlock with endless waiting tx interrupt, and false rx interrupt can occur.
I face the problem and used temporary decision: 

- same priority for all thread, which send to CAN;
- modification interrupt handler. 

I do not sure it can be fix in HAL, because HAL don't know anything about threads.

**Comment by dleach02** [comment]
@GrixaYrev I do see how this could happen with the IMASK1/2. And given that this function is rom the bare metal routines of our HAL you are correct that they don't know about threads. 

@henrikbrixandersen, Not sure there is a fix in the HAL for this. The mutex @MikhailSiomin has might be the solution.

**Comment by GrixaYrev** [comment]
@dleach02 However, in bare-metal system IRQ can overwrite the register still. But i don't know solution, except requiring CAN IRQ disable around `FLEXCAN_TransferSendNonBlocking()` call. And around other functions, probably.

**Comment by dleach02** [comment]
@GrixaYrev can you highlight where the overwrite is in IRQ?

**Comment by GrixaYrev** [comment]
@dleach02 I did mistake, not IRQ overwrite, but IRQ changes can be overwrited:
`FLEXCAN_TransferHandleIRQ()`→
[L4498]`FLEXCAN_SubHandlerForDataTransfered()`→
[L4828]`FLEXCAN_TransferAbortReceive()`→
[L4041]`FLEXCAN_DisableMbInterrupts()`.
I not sure that it is reason of false rx interrupts, but i see potential problem here.

**Comment by MikhailSiomin** [comment]
@alexanderwachter, @henrikbrixandersen, I made the changes. What to do next?

**Comment by alexanderwachter** [comment]
Maybe a stupid question:
Isn't there a register where you can just disable the tx interrupt in the can controller?
For that you would only meed the register address of the controller.

**Comment by MikhailSiomin** [comment]
@alexanderwachter, It is necessary to turn off not only tx interrupt, but also rx and error interrupts.

**Comment by henrikbrixandersen** [comment]
> @alexanderwachter, It is necessary to turn off not only tx interrupt, but also rx and error interrupts.

Perhaps using `FLEXCAN_DisableInterrupts()` and `FLEXCAN_EnableInterrupts()` would be a cleaner solution? Then we wouldn't need to store the IRQ lines etc.

**Comment by alexanderwachter** [comment]
Are the IRQs latched and asserted when they are turned on again?

**Comment by MikhailSiomin** [comment]
FLEXCAN_EnableInterrupts() and FLEXCAN_DisableInterrupts() do not enable/disable tx interrupt, it enable/disable error interrupts. FLEXCAN_EnableMbInterrupts() and FLEXCAN_EnableMbInterrupts() allow enable/disable tx interrupts of given Message Buffers, but it will read-modify-write operations on global resources (IMASK1, IMASK2).

**Review by henrikbrixandersen — APPROVED** [review]

**Review by alexanderwachter — APPROVED** [review]
