### PR TITLE
bluetooth: controller: Set missing bits in supported list

### LINKED ISSUE #33324: Using bluetooth hci_usb sample, and set periodic adv enable, but bluez still shows no command supported
**Describe the bug**
Attempted to use the samples/bluetooth/hci_usb/ project with 
CONFIG_BT_EXT_ADV=y
CONFIG_BT_EXT_ADV_LEGACY_SUPPORT=y
CONFIG_BT_EXT_ADV_MAX_ADV_SET=4
CONFIG_BT_PER_ADV=y
CONFIG_BT_PER_ADV_SYNC=y

to run application over HCI over USB for on a NRF52840-DK. But still shows no periodic adv command supported as below:

>           Read Authenticated Payload Timeout (Octet 32 - Bit 4)
>           Write Authenticated Payload Timeout (Octet 32 - Bit 5)
>           LE Set Data Length (Octet 33 - Bit 6)
>           LE Read Suggested Default Data Length (Octet 33 - Bit 7)
>           LE Write Suggested Default Data Length (Octet 34 - Bit 0)
>           LE Add Device To Resolving List (Octet 34 - Bit 3)
>           LE Remove Device From Resolving List (Octet 34 - Bit 4)
>           LE Clear Resolving List (Octet 34 - Bit 5)
>           LE Read Resolving List Size (Octet 34 - Bit 6)
>           LE Set Address Resolution Enable (Octet 35 - Bit 1)
>           LE Set Resolvable Private Address Timeout (Octet 35 - Bit 2)
>           LE Read Maximum Data Length (Octet 35 - Bit 3)
>           LE Read PHY (Octet 35 - Bit 4)
>           LE Set Default PHY (Octet 35 - Bit 5)
>           LE Set PHY (Octet 35 - Bit 6)
>           LE Enhanced Receiver Test (Octet 35 - Bit 7)
>           LE Enhanced Transmitter Test (Octet 36 - Bit 0)
>           LE Set Advertising Set Random Address (Octet 36 - Bit 1)
>           LE Set Extended Advertising Parameters (Octet 36 - Bit 2)
>           LE Set Extended Advertising Data (Octet 36 - Bit 3)
>           LE Set Extended Scan Response Data (Octet 36 - Bit 4)
>           LE Set Extended Advertising Enable (Octet 36 - Bit 5)
>           LE Read Maximum Advertising Data Length (Octet 36 - Bit 6)
>           LE Read Number of Supported Advertising Sets (Octet 36 - Bit 7)
>           LE Remove Advertising Set (Octet 37 - Bit 0)
>           LE Clear Advertising Sets (Octet 37 - Bit 1)
>           LE Set Extended Scan Parameters (Octet 37 - Bit 5)
>           LE Set Extended Scan Enable (Octet 37 - Bit 6)
>           LE Extended Create Connection (Octet 37 - Bit 7)
>           LE Read Transmit Power (Octet 38 - Bit 7)
>           LE Set Privacy Mode (Octet 39 - Bit 2)
> 

**To Reproduce**

1. Build samples/bluetooth/hci_usb/ with CONFIG_BT_EXT_ADV=y, CONFIG_BT_PER_ADV=y and flash to board
2. using bluez "hcitool cmd 0x04 0x02" to get the supported HCI command
3. using bluez "btmon" to see the supported HCI command

**Expected behavior**
bytes37 bit2 ~ bit4, bytes38 bit0 ~ bit2 shall be set to 1

### PR DESCRIPTION
**Pull request by carlescufi**
A bunch of commands were missing from the bitmap in the Read Local
Supported Commands response. Add them accordingly.

Fixes #33324.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

File: subsys/bluetooth/controller/hci/hci.c [hunk 1]
```diff
@@ -682,12 +682,28 @@ static void read_supported_commands(struct net_buf *buf, struct net_buf **evt)
...
 	rp->commands[26] |= BIT(2) | BIT(3);
+
+#if defined(CONFIG_BT_CTLR_ADV_EXT)
+	/* LE Set Extended Scan Params, LE Set Extended Scan Enable */
+	rp->commands[37] |= BIT(5) | BIT(6);
+#if defined(CONFIG_BT_CTLR_SYNC_PERIODIC)
+	/* LE PA Create Sync, LE PA Create Sync Cancel, LE PA Terminate Sync */
+	rp->commands[38] |= BIT(0) | BIT(1) | BIT(2);
+	/* LE Set PA Receive Enable */
+	rp->commands[40] |= BIT(5);
```
Comment (cvinayak) [inline subsys/bluetooth/controller/hci/hci.c:703]:
```suggestion
```



This is not implemented in the controller, will return command disallowed.

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/hci/hci.c (hunk 1 above)
Comment (carlescufi) [reply subsys/bluetooth/controller/hci/hci.c:703]: But the actual stub is there in `hci.c`? So should we remove the stub, or leave the bit set and get the Host to handle it?

Comment (cvinayak) [reply subsys/bluetooth/controller/hci/hci.c:703]: Lets leave the bit set, and host can log the error when the command is used.

**Review by cvinayak — APPROVED** [review]

**Review by ppryga-nordic — APPROVED** [review]
