### PR TITLE
Bluetooth: Controller: Fix incorrect CIS payload count at CIS Estab

### LINKED ISSUE #83584: Bluetooth: Controller: ISO: CIS MIC errors commonly occur
**Describe the bug**
It has become a common occurrence to see MIC errors causing CIS disconnects (reason 0x3d (`BT_HCI_ERR_TERM_DUE_TO_MIC_FAIL`)) in various configurations. These are often found in the LE Audio tests. They occur with both unidirectional and bidirectional configurations and with both a single peripheral and multiple peripherals. 

**To Reproduce**
1. Apply https://github.com/zephyrproject-rtos/zephyr/pull/83539
2. Run https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/bsim/bluetooth/audio/compile.sh
3. Run any of the tests that disabled in that PR marked with "reason 0x3d"

**Expected behavior**
Expect to see no MIC errors when sending audio on a CIS on an encrypted ACL. 

**Impact**
Significant as it occurs often and seemingly not something that is fixable by the application. Causes CI issues. 

**Logs and console output**
Common log for these tests (look for `bt_iso_chan_disconnected: 0xXXXXXXXX, reason 0x3d`):
```
 d_00: @00:00:12.995916  Started stream 0x84ce7c0
d_00: @00:00:12.995916  [00:00:12.995,910] <inf> bap_stream_tx: Registered 0x84ce7c0 for TX
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_cap_initiator: bt_cap_initiator_started: cap_stream 0x84ce7c0
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_cap_initiator: update_proc_done_cnt: proc 1 subproc 5: 2/4
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_cap_initiator: bt_cap_initiator_started: Stream 0x84ce7c0 started (2/4 streams done)
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_stream: bt_bap_stream_start: stream 0x84ce920 ep 0x8537724
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_unicast_client: bt_bap_unicast_client_start: stream 0x84ce920
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_unicast_client: unicast_client_ep_start: ep 0x8537724 buf 0x8537d5c
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_unicast_client: unicast_client_ep_start: id 0x03
d_00: @00:00:12.995916  [00:00:12.995,910] <dbg> bt_bap_unicast_client: bt_bap_unicast_client_ep_send: conn 0x84fd340 ep 0x8537724 buf 0x8537d5c len 3
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_disconnected: 0x850dee0
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_chan_disconnected: 0x8535e60, reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x8535e60 iso 0x850dee0 connected -> disconnected
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_cleanup_acl: 0x850dee0
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_iso_disconnected: stream 0x84cf160 ep 0x852e448 state streaming reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_iso_disconnected: stream 0x84cf1b8 ep 0x852e7d8 state enabling reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_get_status: ep 0x852e448 id 0x01 state qos-configured
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_get_status_qos: dir sink codec id 0x06 interval 7500 framing 0x00 phy 0x02 rtn 1 latency 15 pd 10000
d_01: @00:00:13.006947  [00:00:13.006,927] <wrn> bt_conn: bt_conn_create_pdu_timeout: Timeout discarded. No blocking in syswq.
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: state_transition_work_handler: ase 0x852e444 ep 0x852e448 id 0x01 streaming -> qos-configured
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_disconnected: 0x850dfd0
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_chan_disconnected: 0x8535ef0, reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_chan_set_state_debug: chan 0x8535ef0 iso 0x850dfd0 connected -> disconnected
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_iso: bt_iso_cleanup_acl: 0x850dfd0
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_iso_disconnected: stream 0x84cf18c ep 0x852e610 state streaming reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_iso_disconnected: stream 0x84cf1e4 ep 0x852e9a0 state enabling reason 0x3d
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_get_status: ep 0x852e610 id 0x02 state qos-configured
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: ascs_ep_get_status_qos: dir sink codec id 0x06 interval 7500 framing 0x00 phy 0x02 rtn 1 latency 15 pd 10000
d_01: @00:00:13.006947  [00:00:13.006,927] <wrn> bt_conn: bt_conn_create_pdu_timeout: Timeout discarded. No blocking in syswq.
d_01: @00:00:13.006947  [00:00:13.006,927] <dbg> bt_ascs: state_transition_work_handler: ase 0x852e60c ep 0x852e610 id 0x02 streaming -> qos-configured
d_00: @00:00:13.013547  [00:00:13.013,519] <inf> bap_stream_tx: Stream 0x84ce7c0 sent 0 SDUs
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ascs_cp_write: conn 0x84fd340 attr 0x8490c28 buf 0x85acf0f len 3 op Receiver Start Ready (0x04)
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ascs_start: num_ases 1
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ascs_start: ase 0x03
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ase_start: ase 0x852e7d4
d_01: @00:00:13.065698  [00:00:13.065,673] <wrn> bt_ascs: ase_start: Start failed: CIS not connected: 0
d_01: @00:00:13.065698  [00:00:13.065,673] <dbg> bt_ascs: ascs_cp_rsp_add: id 0x03 code Invalid ASE State (0x04) reason None (0x00)
d_00: @00:00:13.066004  [00:00:13.065,979] <dbg> bt_bap_unicast_client: unicast_client_ep_notify: conn 0x84fd340 ep 0x853737c len 17
d_00: @00:00:13.066004  [00:00:13.065,979] <dbg> bt_cap_common: bt_cap_common_abort_proc: Aborting proc 1 with subproc 5 for 0x84fd340: -74
d_00: @00:00:13.066004  Stream 0x84ce660 stopped with reason 0x13
```

**Environment (please complete the following information):**
 - Commit SHA or Version used: https://github.com/zephyrproject-rtos/zephyr/pull/83539 (but also occurs for https://github.com/zephyrproject-rtos/zephyr/pull/81093). Both running on `b7b3449f482cd9fb736e3a79363d390fd648051d`

**Additional context**
See also https://github.com/zephyrproject-rtos/zephyr/actions/runs/12581046107/job/35064082709?pr=81093

### PR DESCRIPTION
**Pull request by cvinayak**
Fix incorrect payload count at CIS Establish due to existing
CIG event overlapping the ACL event at the instant when the
CIS gets the active flag set.

The overlapping CIG event picked up the new CIS that had its
active flag set in the current CIG event instead of at the
actual CIS offset which is in the next CIG event.

Fix incorrect CIS offset in use if instant is picked from
the peer sent CIS RSP PDU. Instead, keep the instant that
was sent in the CIS REQ PDU as the instant to send in the
CIS IND PDU.

This fixes CIS failed to be established when dissimilar
ACL and ISO intervals are in use.

Fix Peripheral CIS sorted by CIG implemenation to use CIS
offset stored in LLL context which is the correct offset
from the CIG anchor point. CIS offset in the ULL context
is the offset from the ACL anchor point at the time of
the CIS establishment.

Fix CIS event_count_prepare use missed as part of fixes
related to commit https://github.com/zephyrproject-rtos/zephyr/commit/be91cfedfb54f9022dc0aa02c577b57b35f887a4 ("Bluetooth: Controller: Fix
incorrect event_count when CIG overlaps").

Fixes #83584.

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/lll_conn_iso.h [hunk 1]
```diff
@@ -58,6 +58,7 @@ struct lll_conn_iso_stream {
 	uint8_t datapath_ready_rx:1;/* 1 if datapath for RX is ready */
 
 #if !defined(CONFIG_BT_CTLR_JIT_SCHEDULING)
+	uint8_t established:1;      /* 1 if CIS LLL is established */
```
Comment (Thalley) [inline subsys/bluetooth/controller/ll_sw/lll_conn_iso.h:61]: What is the difference between this and the `active` field? 

When are they different values? Can a CIS be established, but not active, or vice versa?

File: subsys/bluetooth/controller/ll_sw/ull_llcp_pdu.c [hunk 2]
```diff
@@ -901,8 +901,15 @@ void llcp_pdu_decode_cis_rsp(struct proc_ctx *ctx, struct pdu_data *pdu)
...
 
+	/* FIXME: We do not pick the instant from the response; if we do, then
+	 *        we need to calculate again a new offset because the ACL and
+	 *        ISO intervals can be dissimilar and hence will be a different
+	 *        CIS offset when sending the CIS_IND PDU at this instant.
+	 *
+
 	ctx->data.cis_create.conn_event_count =
 		sys_le16_to_cpu(pdu->llctrl.cis_rsp.conn_event_count);
+	 */
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_llcp_pdu.c:912]: @erbr-ot This change for the central to not pick the peripheral sent instant value is failing unit test; because `ull_central_iso_cis_offset_get()` is mocked to do nothing, leading to `conn_event_count` not being assigned the value to be verified.

Your review and ideas will be helpful here.

File: subsys/bluetooth/controller/ll_sw/lll_conn_iso.h (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/lll_conn_iso.h:61]: `active` flag is set by the ACL connection, and the new `established` flag will be set by the CIS connection "only" at the start of the CIG event. This way an `active` flag being set between CISes of a CIG be not picked up.

Comment (Thalley) [reply subsys/bluetooth/controller/ll_sw/lll_conn_iso.h:61]: Not sure I fully understand :)

A CIS is allocated/created with the `Set CIG Parameters` commands. Does this set any any of these bits? (This is before any ACL has been paired with it). 

The `Create CIS` command effectively binds a CIS to an ACL. I guess this is the one that sets the `active` field? 

When the CIS is successfully established, is that when the `established` field is set? 

If the above is correct, then it also always goes that `active` is true when `established` is true? Or is there a case, e.g. doing disconnection of the CIS, where `active == false` and `established == true`? 

The reason I'm asking about this, is that you have some places where you do e.g. `next_cis_lll->active && next_cis_lll->established`, which implies that both may need to be true, instead of just `established`

Could we expand the documentation of these fields a bit, because their current documentation does not really provide anything as they are basically just repeating the name of the field, and not when it is set/unset or what it represents.

**Review by Thalley — DISMISSED** [review]

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/87538#issuecomment-2755052718, board: nrf53, estimated start time: 17:40:32, test case count: 4, estimated duration: 0:15:52<details><summary>Test cases to be run</summary>BAP/UCL/STR/BV-535-C<br>BAP/UCL/STR/BV-523-C<br>BAP/USR/STR/BV-360-C<br>BAP/USR/STR/BV-380-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests (4)</summary>BAP     BAP/UCL/STR/BV-523-C            PASS<br>BAP     BAP/UCL/STR/BV-535-C            PASS<br>BAP     BAP/USR/STR/BV-360-C            PASS<br>BAP     BAP/USR/STR/BV-380-C            PASS</details>

**Comment by cvinayak** [comment]
@Tronil If there is no strong objections to the changes in this PR (i.e. conflicts or regressions possibly in your downstream), please provide your review/approval accordingly.

File: subsys/bluetooth/controller/ll_sw/lll_conn_iso.h [hunk 3]
```diff
@@ -58,6 +58,11 @@ struct lll_conn_iso_stream {
 	uint8_t datapath_ready_rx:1;/* 1 if datapath for RX is ready */
 
 #if !defined(CONFIG_BT_CTLR_JIT_SCHEDULING)
+	/* A CIS LLL is active and established in a CIG radio event when ACL instant has passed
+	 * which set the `active` flag and then when CIG event prepare has picked up the set
+	 * `active` flag.
+	 */
+	uint8_t established:1;
```
Comment (Tronil) [inline subsys/bluetooth/controller/ll_sw/lll_conn_iso.h:65]: If I understand the usage of this flag correctly it is basically used as an "was active when prepare was called". Naming it `established` is misleading since that has a very specific meaning in the BT spec; Wouldn't `active_prepare` work better (that seems like the usual naming convention)?

Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/lll_conn_iso.h:65]: agree.. how about just `cis->prepared` ?

Comment (Tronil) [reply subsys/bluetooth/controller/ll_sw/lll_conn_iso.h:65]: Makes sense :+1:

**Review by Thalley — APPROVED** [review]

**Review by Tronil — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
