### PR TITLE
lib: posix: Fix NULL pointer to strcmp in posix mqueue.

### LINKED ISSUE #86209: No check for NULL-pointer before passing it to strcmp in posix mqueue
**Describe the bug**
The name pointer is freed and set to NULL when a message queue is unlinked. The queue is not removed from the list of queues and when the list is iterated later the NULL pointer is passed to strcmp.

**To Reproduce**
1. Create first mqueue with mq_open
2. Unlink the first queue with mq_unlink
3. Create second mqueue with mq_open

**Expected behavior**
Second mqueue is created with out errors.

**Impact**
Fatal memory access error

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - 9b2fdace1d4c9686d43fbd8fad87b9620f576671

### PR DESCRIPTION
**Pull request by tervonenja**
When a queue has been unlinked but not removed the name pointer is set to NULL. The queue is still in the list when adding new queues and the name pointer is passed to strcmp.

Fixes #86209

### CODE REVIEW

**Comment by ycsin** [comment]
Hi @tervonenja , thanks for this PR, the fix LGTM!

Could you please:
1. Create a bug report for the issue, so that we can backport it to earlier releases, and
2. Create/update our tests to plug this hole, so that it won't happen again?

Cheers

**Comment by tervonenja** [comment]
Created issue #86209

**Comment by ycsin** [comment]
The CI is complaining that your commit body is > 75 char, changing it to something like this should work:
```
lib: posix: Fix NULL pointer to strcmp in posix mqueue

When a queue has been unlinked but not removed the name pointer is set to
NULL. The queue is still in the list when adding new queues and the name
pointer is passed to strcmp.

Signed-off-by: Jari Tervonen <jari.tervonen@nordicsemi.no>
```

File: tests/posix/xsi_realtime/src/mqueue.c [hunk 1]
```diff
@@ -271,3 +271,30 @@ ZTEST(xsi_realtime, test_mqueue_notify_errors)
...
+	const char *q1 = "q1";
+	const char *q2 = "q2";
+
+	mqd_t mqd1, mqd2;
+        struct mq_attr attrs = {
+                .mq_msgsize = MESSAGE_SIZE,
+                .mq_maxmsg = MESG_COUNT_PERMQ,
+        };
+
+	int32_t mode = 0777;
```
Comment (cfriedt) [inline tests/posix/xsi_realtime/src/mqueue.c:286]: Not a huge deal, but if you're updating the PR, might as well use a more conservative mode.

```suggestion
	int32_t mode = 0600;
```

**Review by cfriedt — DISMISSED** [review]
LGTM - thanks!

**Review by cfriedt — APPROVED** [review]

**Review by kartben — APPROVED** [review]
