### PR TITLE
logging: Change Z_LOG_MSG_STACK_CREATE() variable

### LINKED ISSUE #57089: Z_LOG_MSG_STACK_CREATE() variable "flags" hides that of caller
**Describe the bug**
The macro Z_LOG_MSG_STACK_CREATE() creates a local variable named "flags". Unfortunately, should someone invoke LOG_DBG() or LOG_ERR() and pass a parameter named "flags" (as is the case in kernel/mmu.c::z_phys_map()) then the macro's copy of the "flags" variable will override/occlude that of the caller.

Please also mention any information which could help others to understand
the problem you're facing:
This was found via Coverity.

**To Reproduce**
Inspect.

**Expected behavior**
The macro Z_LOG_MSG_STACK_CREATE() should probably not be using a common variable name such as "flags". I would recommend changing the name to have a leading underscore so that it becomes "_flags".

**Impact**
This is a minor issue. It only shows up in a couple of corner cases.

**Environment (please complete the following information):**
 - OS: Any
 - Toolchain: Zephyr SDK

### PR DESCRIPTION
**Pull request by peter-mitsis**
"flags" is a common variable name and is more likely to be passed to LOG_DBG() or LOG_ERR() as a parameter. Changing the name of the local variable created in Z_LOG_MSG_STACK_CREATE() from "flags" to "_options" make it less likely that someone will pass a parameter of that name to LOG_DBG() or LOG_ERR() and have that passed value occluded by the variable created in Z_LOG_MSG_STACK_CREATE.

Fixes #57089

### CODE REVIEW

**Review by galak — APPROVED** [review]

File: include/zephyr/logging/log_msg.h [hunk 1]
```diff
@@ -226,20 +226,20 @@ enum z_log_msg_mode {
 #define Z_LOG_MSG_STACK_CREATE(_cstr_cnt, _domain_id, _source, _level, _data, _dlen, ...) \
 do { \
 	int _plen; \
-	uint32_t flags = Z_LOG_MSG_CBPRINTF_FLAGS(_cstr_cnt) | \
-			 CBPRINTF_PACKAGE_ADD_RW_STR_POS; \
```
Comment (peter-mitsis) [inline include/zephyr/logging/log_msg.h:230]: Side note: Originally I tried using "_flags" instead of "_options". However, this led to build warnings stating that "_flags" was initialised but not used. That warning is thought to come from a separate instance of "_flags" elsewhere in the chain of macros that comprise LOG_DBG().

**Review by dcpleung — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]
