### PR TITLE
Bluetooth: Mesh: Add proxy send callback 

### LINKED ISSUE #36100: pb_gatt buf_send does not call callback
I am provisioning a BT Mesh device that is set up as a PB Gatt device. Provisioning is failing because the OOB input_complete message is never received when inputting an alphanumeric OOB value. The provisioner device times out after 60 seconds of not receiving the input_complete message. This is because the callback 'public_key_sent' is never called for PB Gatt devices when sending the public key. 

In commit 4cc8cb1c1513033e8aa6d9c1086456a062c9bc57 the 'public_key_sent' callback is added to manage flags to make sure that 'send_input_complete' isn't called before the public key is sent. The flag that specifies that the public key was sent never gets set and that flag is checked before calling 'send_input_complete()'. PB Gatt function 'buf_send' takes a callback as input but does nothing with it, causing the PUB_KEY_SENT flag to never get set.

To fix, 'buf_send' in pb_gatt.c should call the callback argument if one exists

This is a show stopper as I can not provision my PB Gatt device

### PR DESCRIPTION
**Pull request by LingaoM**
Zephyr Bluetooth Mesh did not check whether the proxy message
was actually sent out, so that the response message could
not be received during reset. It did not solve the status
callback of the proxy sending message, so a new problem was
introduced after PR(#28457) merged.

bt_mesh_prov_send(&buf, public_key_sent))

This PR will try to solve the above problem, and will fix
the problem due to thread competition, and PR(#26668) will
not be necessary.

Compared with PR(#30138), it no longer consumes extra RAM
space and supports synchronization of group addresses

This is a resubmission of PR(#32666)

Fixes #36100. 

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

### CODE REVIEW

File: subsys/bluetooth/mesh/adv_legacy.c [hunk 1]
```diff
@@ -94,10 +93,8 @@ static inline void adv_send(struct net_buf *buf)
 	k_sleep(K_MSEC(duration));
 
 	err = bt_le_adv_stop();
-	bt_mesh_adv_send_end(err, cb, cb_data);
 	if (err) {
 		BT_ERR("Stopping advertising failed: err %d", err);
-		return;
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/adv_legacy.c:100]: Not relevant

**Review by trond-snekvik — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/mesh/adv.c [hunk 2]
```diff
@@ -41,8 +41,15 @@ const uint8_t bt_mesh_adv_type[BT_MESH_ADV_TYPES] = {
 
 K_FIFO_DEFINE(bt_mesh_adv_queue);
 
+static void adv_buf_destroy(struct net_buf *buf)
+{
+	bt_mesh_adv_send_end(0, BT_MESH_ADV(buf));
+
+	net_buf_destroy(buf);
```
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv.c:48]: I'm a little worried about `BT_MESH_ADV(buf)->data` may be modified elsewhere.

Because of `send_end_cb` can be processed by app layer, and app layer may block the current process. If other processes apply for buffer at this time, `cb_data` may be overwrite?

File: subsys/bluetooth/mesh/adv.c [hunk 3]
```diff
@@ -41,8 +41,15 @@ const uint8_t bt_mesh_adv_type[BT_MESH_ADV_TYPES] = {
 
 K_FIFO_DEFINE(bt_mesh_adv_queue);
 
+static void adv_buf_destroy(struct net_buf *buf)
+{
+	bt_mesh_adv_send_end(0, BT_MESH_ADV(buf));
```
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv.c:46]: Great thinking.

File: subsys/bluetooth/mesh/adv.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv.c:48]: Yes, it's not the adv pointer that's passed, it's the content.

File: subsys/bluetooth/mesh/adv_ext.c [hunk 4]
```diff
@@ -140,12 +139,15 @@ static int buf_send(struct net_buf *buf)
...
+	adv.buf = buf;
 
 	err = adv_start(&adv_param, &start, &ad, 1, NULL, 0);
-	net_buf_unref(buf);
-	bt_mesh_adv_send_start(duration, err, adv.cb, adv.cb_data);
+
+	bt_mesh_adv_send_start(duration, err, BT_MESH_ADV(buf));
+
+	if (err) {
+		net_buf_unref(buf);
```
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv_ext.c:149]: Yes, it should be. Not just for function.

File: subsys/bluetooth/mesh/adv.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (trond-snekvik) [reply subsys/bluetooth/mesh/adv.c:48]: Yes, it would need to make a copy of the callback and context first, like this, for example:
```c
	struct bt_mesh_adv adv = *BT_MESH_ADV(buf);

	bt_mesh_adv_send_end(0, &adv);

	net_buf_destroy(buf);
```

File: subsys/bluetooth/mesh/adv_ext.c [hunk 5]
```diff
@@ -140,12 +142,13 @@ static int buf_send(struct net_buf *buf)
...
 
-	adv.cb = BT_MESH_ADV(buf)->cb;
-	adv.cb_data = BT_MESH_ADV(buf)->cb_data;
+	adv.buf = buf;
 
 	err = adv_start(&adv_param, &start, &ad, 1, NULL, 0);
+
+	bt_mesh_adv_send_start(duration, err, BT_MESH_ADV(buf));
+
 	net_buf_unref(buf);
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/adv_ext.c:151]: Personally, I would put this unref in the while loop, where it was acquired (from `net_buf_get`), but up to you. @jhedberg may feel stronger about this.

File: subsys/bluetooth/mesh/adv.h [hunk 6]
```diff
@@ -75,18 +77,22 @@ int bt_mesh_adv_start(const struct bt_le_adv_param *param, int32_t duration,
...
 {
-	if (cb && cb->start) {
-		cb->start(duration, err, cb_data);
+	if (adv->cb && adv->cb->start && !adv->started) {
+		adv->started = 1;
+		adv->cb->start(duration, err, adv->cb_data);
+
+		if (err) {
+			adv->cb = NULL;
+		}
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/adv.h:88]: Why not add `&& adv->started` to the `if` in `bt_mesh_adv_send_end` instead? It seems like it would be slightly easier to follow. This, and the `if (started)` in the destructor could be removed.

File: subsys/bluetooth/mesh/adv_ext.c [hunk 7]
```diff
@@ -235,7 +238,8 @@ static void adv_sent(struct bt_le_ext_adv *instance,
 	atomic_clear_bit(adv.flags, ADV_FLAG_ACTIVE);
 
 	if (!atomic_test_and_clear_bit(adv.flags, ADV_FLAG_PROXY)) {
-		bt_mesh_adv_send_end(0, adv.cb, adv.cb_data);
+		BT_MESH_ADV(adv.buf)->busy = 0U;
```
Comment (trond-snekvik) [inline subsys/bluetooth/mesh/adv_ext.c:241]: Perhaps this belongs in the destructor?

**Review by trond-snekvik — APPROVED** [review]
I have a couple of minor suggestions, but all in all, LGTM. There appears to be no leaks in either advertiser mode.

File: subsys/bluetooth/mesh/adv.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv.c]: Try to avoid call end if not started.
``` C
    if (adv.started) {
        bt_mesh_adv_send_end(0, BT_MESH_ADV(buf));
    }
```
And try avoid call end if failed to started:

``` C

    // in bt_mesh_adv_send_start
    if (err) {
        adv->cb = NULL;
    }
```

File: subsys/bluetooth/mesh/adv_ext.c (hunk 7 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv_ext.c:241]: Defer to destructor.

File: subsys/bluetooth/mesh/adv_ext.c [hunk 8]
```diff
@@ -166,6 +167,9 @@ static void send_pending_adv(struct k_work *work)
 
 		BT_MESH_ADV(buf)->busy = 0U;
 		err = buf_send(buf);
+
+		net_buf_unref(buf);
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/adv_ext.c:171]: This looks wrong to me since `buf_send()` doesn't call `net_buf_ref()`

File: subsys/bluetooth/mesh/adv_ext.c [hunk 9]
```diff
@@ -103,9 +102,12 @@ static int adv_start(const struct bt_le_adv_param *param,
 	if (err) {
 		BT_ERR("Advertising failed: err %d", err);
 		atomic_clear_bit(adv.flags, ADV_FLAG_ACTIVE);
+		return err;
 	}
 
-	return err;
+	net_buf_ref(adv.buf);
```
Comment (jhedberg) [inline subsys/bluetooth/mesh/adv_ext.c:108]: No code should ever call `net_buf_ref()` without storing the return value to a new pointer. See my other comment, i.e. the refcounting will need some redesign.

File: subsys/bluetooth/mesh/adv_ext.c (hunk 8 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv_ext.c:171]: Why `adv_start` cannot call `net_buf_ref`?

File: subsys/bluetooth/mesh/adv_ext.c (hunk 9 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv_ext.c:108]: @trond-snekvik Any opinion to this ?

File: subsys/bluetooth/mesh/adv_ext.c (hunk 8 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv_ext.c:169]: Is this to your taste?

Comment (jhedberg) [reply subsys/bluetooth/mesh/adv_ext.c:169]: Yes that makes more sense. And I hope it's more to your taste too: reference counting can be an ample source of bugs, so following some basic principles when using it makes the code more predictable and understandable.

**Comment by jhedberg** [comment]
@LingaoM looks generally good, but I'd suggest adding some more meat to the bones in the first commit message, since right now it's just repeating the short commit summary.

File: subsys/bluetooth/mesh/adv_ext.c (hunk 9 above)
Comment (trond-snekvik) [reply subsys/bluetooth/mesh/adv_ext.c]: I agree with @jhedberg :)

File: subsys/bluetooth/mesh/adv.h (hunk 6 above)
Comment (trond-snekvik) [reply subsys/bluetooth/mesh/adv.h:91]: There's no need for this if anymore

Comment (LingaoM) [reply subsys/bluetooth/mesh/adv.h:91]: We should deal with the error situation. What do you mean?

Comment (trond-snekvik) [reply subsys/bluetooth/mesh/adv.h:91]: Riiight, I see. I was thinking that the `started` flag should only be set if the advertising could actually be started, ie, it did not return an error. This works as well though, so I'll approve, and leave it to you :)

**Review by trond-snekvik — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/mesh/adv_legacy.c [hunk 10]
```diff
@@ -94,7 +93,6 @@ static inline void adv_send(struct net_buf *buf)
 	k_sleep(K_MSEC(duration));
 
 	err = bt_le_adv_stop();
-	bt_mesh_adv_send_end(err, cb, cb_data);
```
Comment (WilliamGFish) [inline subsys/bluetooth/mesh/adv_legacy.c:97]: The removal of this line holds the connection state open making the provisioner believe the radio is busy. When reinstated the changes work great and appear to speed up the entire provisioning process.

Simple change: bt_mesh_adv_send_end(err, BT_MESH_ADV(buf));

File: subsys/bluetooth/mesh/adv_ext.c [hunk 11]
```diff
@@ -235,7 +237,7 @@ static void adv_sent(struct bt_le_ext_adv *instance,
 	atomic_clear_bit(adv.flags, ADV_FLAG_ACTIVE);
 
 	if (!atomic_test_and_clear_bit(adv.flags, ADV_FLAG_PROXY)) {
-		bt_mesh_adv_send_end(0, adv.cb, adv.cb_data);
```
Comment (WilliamGFish) [inline subsys/bluetooth/mesh/adv_ext.c:238]: I think this line needs to be reinstated like:

bt_mesh_adv_send_end(0, adv);

As it seems to not inform the calling function it has release provisioning process.

**Review by WilliamGFish — COMMENTED** [review]
These changes work great if only provisioning a single device but causes "radio busy" errors when attempting to provision more than one node/device.
By reinstating bt_mesh_adv_send_end() function all appears to work

File: subsys/bluetooth/mesh/adv_legacy.c (hunk 10 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv_legacy.c:97]: All are postponed to: https://github.com/zephyrproject-rtos/zephyr/blob/7ba52d8f825b62009bb74c553905455b4988dcb0/subsys/bluetooth/mesh/adv.c#L50

File: subsys/bluetooth/mesh/adv_ext.c (hunk 11 above)
Comment (LingaoM) [reply subsys/bluetooth/mesh/adv_ext.c:238]: Also above.

File: subsys/bluetooth/mesh/adv_legacy.c (hunk 10 above)
Comment (WilliamGFish) [reply subsys/bluetooth/mesh/adv_legacy.c:97]: I see what you are trying to do but it does not close connections cleanly. If I put the implicate end calls back in it works fine.
