### PR TITLE
stm32h5 run application in external flash memory XIP

### LINKED ISSUE #87531: stm32h573i_dk can't boot from external flash with mcuboot
**Describe the bug:**

I'm trying to boot my application from the external ospi nor flash on the stm32h573i_dk board. My project ([MCUBOOT_EXT_Test.zip](https://github.com/user-attachments/files/19411028/MCUBOOT_EXT_Test.zip)) is based of the mcuboot sample. When I place the slot0 and slot1 partition in the internal flash everything works as expected, however when I place them in the external flash the code stops, when jumping to the application image. (As shown in the log below) At this point the MCU can't be accessed through the debugger (west attach or STM32CubeProgrammer), because it's in a locked up state.

**To Reproduce:**

I uploaded my project files as a zip. Build them with sysbuild and flash them to an stm32h573i_dk. And edit the board file (stm32h573i_dk.dts) in the zephyr folder, so the slot0 and slot1 partitions are placed in the ospi nor flash.

[MCUBOOT_EXT_Test.zip](https://github.com/user-attachments/files/19411028/MCUBOOT_EXT_Test.zip)

**CMake Warnings for mcuboot target:**
```
CMake Warning at C:/Users/xxxx/zephyrproject/zephyr/CMakeLists.txt:1011 (message):
  No SOURCES given to Zephyr library: ..__modules__hal__renesas__drivers

  Excluding target from build.


MCUBoot bootloader key file: C:/Users/xxxx/zephyrproject/bootloader/mcuboot/root-rsa-2048.pem
CMake Warning at CMakeLists.txt:367 (message):
  WARNING: Using default MCUboot signing key file, this file is for debug use
  only and is not secure!


CMake Warning at CMakeLists.txt:589 (message):
  Unable to determine erase size of slot0 or slot1 partition, setting to 1
  (this is probably wrong)


CMake Warning at CMakeLists.txt:594 (message):
  Unable to determine write size of slot0 or slot1 partition, setting to 8
  (this is probably wrong)
```

**CMake Warnings for main app target:**
```
warning: MCUBOOT_UPDATE_FOOTER_SIZE (defined at subsys/dfu/Kconfig:55) was assigned the value
'0x3031' but got the value ''. Check these unsatisfied dependencies: MCUBOOT_IMG_MANAGER (=n),
IMG_MANAGER (=n). See
http://docs.zephyrproject.org/latest/kconfig.html#CONFIG_MCUBOOT_UPDATE_FOOTER_SIZE and/or look up
MCUBOOT_UPDATE_FOOTER_SIZE in the menuconfig/guiconfig interface. The Application Development
Primer, Setting Configuration Values, and Kconfig - Tips and Best Practices sections of the manual
might be helpful too.

CMake Warning at C:/Users/xxxx/zephyrproject/zephyr/CMakeLists.txt:1011 (message):
  No SOURCES given to Zephyr library: ..__modules__hal__renesas__drivers

  Excluding target from build.


-- Including signing script: C:/Users/xxxx/zephyrproject/zephyr/cmake/mcuboot.cmake
CMake Warning at C:/Users/xxxx/zephyrproject/zephyr/cmake/mcuboot.cmake:71 (message):
  slot0_partition write block size devicetree parameter is missing, assuming
  write block size is 4
Call Stack (most recent call first):
  C:/Users/xxxx/zephyrproject/zephyr/cmake/mcuboot.cmake:245 (zephyr_mcuboot_tasks)
  C:/Users/xxxx/zephyrproject/zephyr/CMakeLists.txt:2053 (include)


```

**Logs and console output:**
```
D: Flash @0x8000000 initialized. BS: 16
D: Block 0: bs: 8192 count: 256
D: XSPI Init'd
D: Delay Block Init
D: Reset Mem (SPI/STR)
D: Status Match cb
D: Mem Ready (SPI/STR)
D: XSPI configuring Octo SPI mode
D: Status Match cb
D: Status Match cb
D: Status Match cb
D: Status Match cb
I: XSPI flash config is OCTO / DTR
I: Read SFDP from externalFlash
D: ospi-nor-flash@90000000: SFDP v 1.8 AP fd with 5 PH
D: PH0: ff00 rev 1.7: 20 DW @ 40
I: Read SFDP from externalFlash
D: ospi-nor-flash@90000000: 64 MiBy flash
D: Erase 4096 with 20
D: Erase 65536 with d8
D: Address width: 4 Bytes
D: Page size 256 bytes
D: Flash size 67108864 bytes
D: Using read mode: 0, instr: 0x0, dummy cycles: 0
D: Using write instr: 0x12ED
D: PH1: ff87 rev 1.1: 28 DW @ 90
D: layout page 256 not compatible with erase size 4096
D: erase size will be used as layout page size
D: layout 16384 x 4096 By pages
D: MemoryMap mode enabled
I: Memory-mapped NOR-flash at 0x90000000 (0x4000000 bytes)
*** Booting MCUboot  ***
*** Using Zephyr OS build 4.1.99 ***
I: Starting bootloader
D: Memory-mapped read from 0x90000000, len 32
D: Memory-mapped read from 0x9006a000, len 32
D: Memory-mapped read from 0x90069ff0, len 16
D: Memory-mapped read from 0x90069fc0, len 1
D: Memory-mapped read from 0x90069fd0, len 1
D: Memory-mapped read from 0x90069fe0, len 1
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
D: Memory-mapped read from 0x900d1ff0, len 16
D: Memory-mapped read from 0x900d1fc0, len 1
D: Memory-mapped read from 0x900d1fd0, len 1
D: Memory-mapped read from 0x900d1fe0, len 1
I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: none
D: Memory-mapped read from 0x90000000, len 32
D: Memory-mapped read from 0x9006a000, len 32
D: Memory-mapped read from 0x90069ff0, len 16
D: Memory-mapped read from 0x90069fc0, len 1
D: Memory-mapped read from 0x90069fd0, len 1
D: Memory-mapped read from 0x90069fe0, len 1
D: Memory-mapped read from 0x900d1ff0, len 16
D: Memory-mapped read from 0x900d1fc0, len 1
D: Memory-mapped read from 0x900d1fd0, len 1
D: Memory-mapped read from 0x900d1fe0, len 1
I: Image index: 0, Swap type: none
D: Memory-mapped read from 0x90000000, len 256
D: Memory-mapped read from 0x90000100, len 256
D: Memory-mapped read from 0x90000200, len 256
D: Memory-mapped read from 0x90000300, len 256
D: Memory-mapped read from 0x90000400, len 256
D: Memory-mapped read from 0x90000500, len 256
D: Memory-mapped read from 0x90000600, len 256
D: Memory-mapped read from 0x90000700, len 256
D: Memory-mapped read from 0x90000800, len 256
D: Memory-mapped read from 0x90000900, len 256
D: Memory-mapped read from 0x90000a00, len 256
D: Memory-mapped read from 0x90000b00, len 256
D: Memory-mapped read from 0x90000c00, len 256
D: Memory-mapped read from 0x90000d00, len 256
D: Memory-mapped read from 0x90000e00, len 256
D: Memory-mapped read from 0x90000f00, len 256
D: Memory-mapped read from 0x90001000, len 256
D: Memory-mapped read from 0x90001100, len 256
D: Memory-mapped read from 0x90001200, len 256
D: Memory-mapped read from 0x90001300, len 256
D: Memory-mapped read from 0x90001400, len 256
D: Memory-mapped read from 0x90001500, len 256
D: Memory-mapped read from 0x90001600, len 256
D: Memory-mapped read from 0x90001700, len 256
D: Memory-mapped read from 0x90001800, len 256
D: Memory-mapped read from 0x90001900, len 256
D: Memory-mapped read from 0x90001a00, len 256
D: Memory-mapped read from 0x90001b00, len 256
D: Memory-mapped read from 0x90001c00, len 256
D: Memory-mapped read from 0x90001d00, len 256
D: Memory-mapped read from 0x90001e00, len 256
D: Memory-mapped read from 0x90001f00, len 256
D: Memory-mapped read from 0x90002000, len 256
D: Memory-mapped read from 0x90002100, len 256
D: Memory-mapped read from 0x90002200, len 256
D: Memory-mapped read from 0x90002300, len 256
D: Memory-mapped read from 0x90002400, len 256
D: Memory-mapped read from 0x90002500, len 256
D: Memory-mapped read from 0x90002600, len 256
D: Memory-mapped read from 0x90002700, len 256
D: Memory-mapped read from 0x90002800, len 256
D: Memory-mapped read from 0x90002900, len 256
D: Memory-mapped read from 0x90002a00, len 256
D: Memory-mapped read from 0x90002b00, len 256
D: Memory-mapped read from 0x90002c00, len 256
D: Memory-mapped read from 0x90002d00, len 256
D: Memory-mapped read from 0x90002e00, len 256
D: Memory-mapped read from 0x90002f00, len 256
D: Memory-mapped read from 0x90003000, len 256
D: Memory-mapped read from 0x90003100, len 256
D: Memory-mapped read from 0x90003200, len 256
D: Memory-mapped read from 0x90003300, len 256
D: Memory-mapped read from 0x90003400, len 256
D: Memory-mapped read from 0x90003500, len 256
D: Memory-mapped read from 0x90003600, len 256
D: Memory-mapped read from 0x90003700, len 256
D: Memory-mapped read from 0x90003800, len 256
D: Memory-mapped read from 0x90003900, len 256
D: Memory-mapped read from 0x90003a00, len 256
D: Memory-mapped read from 0x90003b00, len 256
D: Memory-mapped read from 0x90003c00, len 256
D: Memory-mapped read from 0x90003d00, len 256
D: Memory-mapped read from 0x90003e00, len 256
D: Memory-mapped read from 0x90003f00, len 256
D: Memory-mapped read from 0x90004000, len 256
D: Memory-mapped read from 0x90004100, len 256
D: Memory-mapped read from 0x90004200, len 256
D: Memory-mapped read from 0x90004300, len 256
D: Memory-mapped read from 0x90004400, len 256
D: Memory-mapped read from 0x90004500, len 256
D: Memory-mapped read from 0x90004600, len 256
D: Memory-mapped read from 0x90004700, len 256
D: Memory-mapped read from 0x90004800, len 256
D: Memory-mapped read from 0x90004900, len 256
D: Memory-mapped read from 0x90004a00, len 256
D: Memory-mapped read from 0x90004b00, len 256
D: Memory-mapped read from 0x90004c00, len 256
D: Memory-mapped read from 0x90004d00, len 256
D: Memory-mapped read from 0x90004e00, len 256
D: Memory-mapped read from 0x90004f00, len 256
D: Memory-mapped read from 0x90005000, len 256
D: Memory-mapped read from 0x90005100, len 256
D: Memory-mapped read from 0x90005200, len 256
D: Memory-mapped read from 0x90005300, len 256
D: Memory-mapped read from 0x90005400, len 256
D: Memory-mapped read from 0x90005500, len 256
D: Memory-mapped read from 0x90005600, len 256
D: Memory-mapped read from 0x90005700, len 256
D: Memory-mapped read from 0x90005800, len 256
D: Memory-mapped read from 0x90005900, len 256
D: Memory-mapped read from 0x90005a00, len 256
D: Memory-mapped read from 0x90005b00, len 256
D: Memory-mapped read from 0x90005c00, len 256
D: Memory-mapped read from 0x90005d00, len 256
D: Memory-mapped read from 0x90005e00, len 256
D: Memory-mapped read from 0x90005f00, len 256
D: Memory-mapped read from 0x90006000, len 256
D: Memory-mapped read from 0x90006100, len 256
D: Memory-mapped read from 0x90006200, len 256
D: Memory-mapped read from 0x90006300, len 256
D: Memory-mapped read from 0x90006400, len 256
D: Memory-mapped read from 0x90006500, len 256
D: Memory-mapped read from 0x90006600, len 256
D: Memory-mapped read from 0x90006700, len 256
D: Memory-mapped read from 0x90006800, len 256
D: Memory-mapped read from 0x90006900, len 256
D: Memory-mapped read from 0x90006a00, len 256
D: Memory-mapped read from 0x90006b00, len 256
D: Memory-mapped read from 0x90006c00, len 256
D: Memory-mapped read from 0x90006d00, len 256
D: Memory-mapped read from 0x90006e00, len 50
D: Memory-mapped read from 0x90006e32, len 4
D: Memory-mapped read from 0x90006e36, len 4
D: Memory-mapped read from 0x90006e3a, len 32
D: Memory-mapped read from 0x90006e5a, len 4
D: Memory-mapped read from 0x90006e5e, len 32
D: Memory-mapped read from 0x90006e7e, len 4
D: Memory-mapped read from 0x90006e82, len 256
I: Bootloader chainload address offset: 0x0
I: Image version: v0.0.0
I: Jumping to the first image slot
D: Memory-mapped read from 0x90000400, len 8

```

**Environment (please complete the following information):**

 - OS: Windows 11
 - Toolchain: Zephyr SDK, CLion
 - Zephyr: 4.1.99

### PR DESCRIPTION
**Pull request by FRASTM**
the stm32h5 disco kit board can run an application in external flash

Requires the https://github.com/zephyrproject-rtos/zephyr/pull/88646 which removes the warning in the DTC

With this PR it enable the memorymapped mode on the external flash memory so that XIP is possible on the external NOR octoflash

Two samples are running in XIP on the external flash

samples/application_development/code_relocation_nocopy/
samples/boards/st/hello_world_xip/ built with mcu boot https://github.com/mcu-tools/mcuboot/pull/2323

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/87531

This PR completes the https://github.com/zephyrproject-rtos/zephyr/pull/88051  for the stm32h5 serie

### CODE REVIEW

**Comment by FRASTM** [comment]
west build -b stm32h573i_dk samples/application_development/code_relocation_nocopy/
west flash  : stm32cubeprogrammer runner is taking the external loader to download into the external NOR (0x90000000)
```
*** Booting Zephyr OS build v4.1.0-2350-g86df576c4134 ***
Address of main function 0x80005e1
Address of function_in_ext_flash 0x90000001
Address of var_ext_sram_data 0x200000a0 (10)
Address of function_in_sram 0x20000001
Address of var_sram_data 0x200000a4 (10)
Hello World! stm32h573i_dk
```

**Comment by FRASTM** [comment]
west build -p -b stm32h573i_dk samples/boards/st/hello_world_xip/ --sysbuild --     -DSB_CONFIG_BOOTLOADER_MCUBOOT=y

requires https://github.com/mcu-tools/mcuboot/pull/2154
download with stm32cubeprogrammer GUI
the build/mcuboot/zephyr/zephyr.bin at internal flash address 0x8000000
the build/hello_world_xip/zephyr/zephyr.signed.bin at external flash address 0x90000000

**Comment by FRASTM** [comment]
Define larger partition in the external NOR flash (consequently adjusting the SECTOR size for the mcu boot)

**Comment by FRASTM** [comment]
CI failure "invalid length for memory region EXTFLASH" given by the samples/application_development/code_relocation_nocopy/linker_arm_nocopy.ld

**Comment by tpambor** [comment]
See https://github.com/zephyrproject-rtos/zephyr/pull/88392 for a fix.

**Comment by FRASTM** [comment]
set the DNM mabel until the https://github.com/zephyrproject-rtos/zephyr/pull/88646 is merged

**Comment by FRASTM** [comment]
Adding the commit to retrieve the CONFIG_FLASH_BASE_ADDRESS from the DTS by the soc/st/stm32/Kconfig.defconfig

**Comment by FRASTM** [comment]
set the DNM mabel until the https://github.com/zephyrproject-rtos/zephyr/pull/88051 is merged

**Comment by FRASTM** [comment]
Adding the configuration to run 
`west build -p -b stm32h573i_dk samples/sysbuild/with_mcuboot/ --sysbuild`
on the target board.
Use the stm32CubeProgrammer to download 

1. build/mcuboot/zephyr/zephyr.bin in internal flash at 0x8000000
2. build/with_mcuboot/zephyr/zephyr.signed.bin in external flash at 0x90000000


```
*** Booting MCUboot v2.1.0-rc1-277-g5ba3b7962ee8 ***
*** Using Zephyr OS build v4.1.0-3467-g1fee1c88b558 ***
*** Booting Zephyr OS build v4.1.0-3467-g1fee1c88b558 ***
Address of sample 0x90000000
Hello sysbuild with mcuboot! stm32h573i_dk

```

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 1]
```diff
@@ -434,6 +434,21 @@ static int set_up_plls(void)
...
 
 #if defined(STM32_PLL_ENABLED)
+
+#if defined(CONFIG_STM32_MEMMAP) && defined(CONFIG_BOOTLOADER_MCUBOOT)
+	/*
+	 * Don't disable PLL during application initialization
+	 * that runs in memmap mode when (Q/O)SPI uses PLL
+	 * as its clock source.
+	 */
+#if defined(XSPI1) || defined(XSPI2)
```
Comment (erwango) [inline drivers/clock_control/clock_stm32_ll_h5.c]: Strangely, on H5 none of these are defined but instead, we can find OCTOSPI1/2 definition.
This being said, We can assume that at least one of both are available if `CONFIG_STM32_MEMMAP` is defined, so I think the whole condition can be removed.

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts [hunk 2]
```diff
@@ -22,9 +22,9 @@
 		zephyr,shell-uart = &usart1;
 		zephyr,sram = &sram1;
 		zephyr,flash = &flash0;
-		zephyr,code-partition = &slot0_partition;
```
Comment (erwango) [inline boards/st/stm32h573i_dk/stm32h573i_dk.dts]: This one can stay

File: boards/st/stm32h573i_dk/board.cmake [hunk 3]
```diff
@@ -1,7 +1,7 @@
 # SPDX-License-Identifier: Apache-2.0
 
 # keep first
-if(CONFIG_STM32_MEMMAP)
+if(CONFIG_STM32_MEMMAP OR (CONFIG_XIP AND CONFIG_BOOTLOADER_MCUBOOT))
```
Comment (erwango) [inline boards/st/stm32h573i_dk/board.cmake]: Can you clarify the case we're guarding against ?

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts [hunk 4]
```diff
@@ -299,27 +299,6 @@
...
-		scratch_partition: partition@e0000 {
-			label = "image-scratch";
-			reg = <0x000e0000 DT_SIZE_K(64)>;
-		};
-
-		/* Set 64KB of storage at the end of Bank1 */
-		storage_partition: partition@f0000 {
-			label = "storage";
-			reg = <0x000f0000 DT_SIZE_K(64)>;
-		};
```
Comment (erwango) [inline boards/st/stm32h573i_dk/stm32h573i_dk.dts]: Shouldn't we keep the storage partition on internal flash ? (avoid rww potential issues)

File: samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+
+/*
+ * Define the device, controller and partition to be the external memory
+ * for running the application in external NOR from MCUboot
+ */
+/ {
+	chosen {
+		zephyr,flash = &mx25lm51245;
+		zephyr,flash-controller = &mx25lm51245;
+		zephyr,code-partition = &slot0_partition;
```
Comment (erwango) [inline samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay]: I think this line can safely  be moved to board.dts

**Review by erwango — CHANGES_REQUESTED** [review]

**Comment by Jowllel** [comment]
Firstly. Thanks a lot for this fix. But when trying to enable CONFIG_FLASH in the hello_world_xip sample there's an xspi init error. Maybe because the flash is being reinitialized in the application? I think there should be a way to disable the flash initialisation when the using mcuboot, because to update the images CONFIG_FLASH needs to be enabled for the img_manager.

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts (hunk 2 above)
Comment (FRASTM) [reply boards/st/stm32h573i_dk/stm32h573i_dk.dts]: keeping this line

File: samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay (hunk 5 above)
Comment (FRASTM) [reply samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay]: yes

**Comment by FRASTM** [comment]
> Firstly. Thanks a lot for this fix. But when trying to enable CONFIG_FLASH in the hello_world_xip sample there's an xspi init error. Maybe because the flash is being reinitialized in the application? I think there should be a way to disable the flash initialisation when the using mcuboot, because to update the images CONFIG_FLASH needs to be enabled for the img_manager.

I tested again my hello_world_xip sample:
west build -p -b stm32h573i_dk samples/boards/st/hello_world_xip/ --sysbuild -DSB_CONFIG_BOOTLOADER_MCUBOOT=y


```
*** Booting MCUboot v2.1.0-rc1-315-ge3b8bd449b18 ***
*** Using Zephyr OS build v4.1.0-5079-g974edcd9c7ce ***
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: none
I: Image index: 0, Swap type: none
I: Bootloader chainload address offset: 0x0
I: Image version: v0.0.0
I: Jumping to the first image slot
*** Booting Zephyr OS build v4.1.0-5079-g974edcd9c7ce ***
Hello World! from external flash  stm32h573i_dk
--> PC at 0x9000092a
```

In the drivers/clock_control/clock_stm32_ll_h5.c, there is a sequence to avoid disabling the pll of the XSPI instance when this XSPI instance is in Memory Mapped mode (else you disable the clock of the peripheral you are executing)
And in the flash_stm32_xspi driver, there is a sequence to pass the flash_stm32_xspi_init when the xspi instance is executing in Memory Mapped mode.

File: drivers/clock_control/clock_stm32_ll_h5.c (hunk 1 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_h5.c]: removed

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts (hunk 4 above)
Comment (FRASTM) [reply boards/st/stm32h573i_dk/stm32h573i_dk.dts]: We can keep the storage partition in the internal flash (size could even be increased)
Then the external flash has no storage partition and we can adjust the partitions of the external flash up to 64K. However increasing the size of the slot0/1 partitions of the external flash (for example 24MB) could give a runtime error " `Failed reading sectors; BOOT_MAX_IMG_SECTORS=4096 - too small?`"

To avoid this, the ../bootloader/mcuboot/boot/zephyr/boards/stm32h573i_dk requires  CONFIG_BOOT_MAX_IMG_SECTORS=8192 or so

**Comment by FRASTM** [comment]
with comments addressed

**Comment by Jowllel** [comment]
Now I get this Error during compiling:

```C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c: In function 'set_up_plls':
C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c:444:13: warning: implicit declaration of function 'LL_RCC_GetOSPIClockSource'; did you mean 'LL_RCC_GetSPIClockSource'? [-Wimplicit-function-declaration]
  444 |         if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             LL_RCC_GetSPIClockSource
C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c:444:39: error: 'LL_RCC_OSPI_CLKSOURCE' undeclared (first use in this function); did you mean 'LL_RCC_SPI6_CLKSOURCE'?
  444 |         if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
      |                                       ^~~~~~~~~~~~~~~~~~~~~
      |                                       LL_RCC_SPI6_CLKSOURCE```

**Comment by FRASTM** [comment]
> Now I get this Error during compiling:
> 
> ```
> C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c:444:13: warning: implicit declaration of function 'LL_RCC_GetOSPIClockSource'; did you mean 'LL_RCC_GetSPIClockSource'? [-Wimplicit-function-declaration]
>   444 |         if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~
>       |             LL_RCC_GetSPIClockSource
> C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c:444:39: error: 'LL_RCC_OSPI_CLKSOURCE' undeclared (first use in this function); did you mean 'LL_RCC_SPI6_CLKSOURCE'?
>   444 |         if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
>       |                                       ^~~~~~~~~~~~~~~~~~~~~
>       |                                       LL_RCC_SPI6_CLKSOURCE```
> ```

hum, this comes after https://github.com/zephyrproject-rtos/zephyr/pull/88579#discussion_r2132115169
I'm going to test something else...

**Comment by Jowllel** [comment]
> > Now I get this Error during compiling:
> > ```
> > C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c:444:13: warning: implicit declaration of function 'LL_RCC_GetOSPIClockSource'; did you mean 'LL_RCC_GetSPIClockSource'? [-Wimplicit-function-declaration]
> >   444 |         if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
> >       |             ^~~~~~~~~~~~~~~~~~~~~~~~~
> >       |             LL_RCC_GetSPIClockSource
> > C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c:444:39: error: 'LL_RCC_OSPI_CLKSOURCE' undeclared (first use in this function); did you mean 'LL_RCC_SPI6_CLKSOURCE'?
> >   444 |         if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
> >       |                                       ^~~~~~~~~~~~~~~~~~~~~
> >       |                                       LL_RCC_SPI6_CLKSOURCE```
> > ```
> 
> hum, this comes after [#88579 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/88579#discussion_r2132115169) I'm going to test something else...

What do you mean with that. Is the problem on my side or in the current state of this PR?

**Comment by FRASTM** [comment]
> > > Now I get this Error during compiling:
> > > ```
> > > C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c:444:13: warning: implicit declaration of function 'LL_RCC_GetOSPIClockSource'; did you mean 'LL_RCC_GetSPIClockSource'? [-Wimplicit-function-declaration]
> > >   444 |         if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
> > >       |             ^~~~~~~~~~~~~~~~~~~~~~~~~
> > >       |             LL_RCC_GetSPIClockSource
> > > C:/Users/jschaller/zephyrproject/zephyr/drivers/clock_control/clock_stm32_ll_h5.c:444:39: error: 'LL_RCC_OSPI_CLKSOURCE' undeclared (first use in this function); did you mean 'LL_RCC_SPI6_CLKSOURCE'?
> > >   444 |         if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
> > >       |                                       ^~~~~~~~~~~~~~~~~~~~~
> > >       |                                       LL_RCC_SPI6_CLKSOURCE```
> > > ```
> > 
> > 
> > hum, this comes after [#88579 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/88579#discussion_r2132115169) I'm going to test something else...
> 
> What do you mean with that. Is the problem on my side or in the current state of this PR?

It has to be changed with 
`	if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
`
and 
`	if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL2R) {
`

I will proceed.

**Review by erwango — DISMISSED** [review]

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 6]
```diff
@@ -434,17 +434,23 @@ static int set_up_plls(void)
 #endif
 
 #if defined(STM32_PLL_ENABLED)
+
+#if defined(CONFIG_STM32_MEMMAP) && defined(CONFIG_BOOTLOADER_MCUBOOT)
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c]: Intentionally removing switching sysclk source to HSI?
If so, I think it should be mentioned in the commit message.
Also if so, can remove `clock_switch_to_hsi()` local helper function.

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 7]
```diff
@@ -434,17 +434,23 @@ static int set_up_plls(void)
...
 	 */
-	if (LL_RCC_GetSysClkSource() == LL_RCC_SYS_CLKSOURCE_STATUS_PLL1) {
-		clock_switch_to_hsi();
+	if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
+		LL_RCC_PLL1_Disable();
 	}
-
+	if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL2R) {
+		LL_RCC_PLL2_Disable();
+	}
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c]: The part related to PLL2 should go in `#if defined(STM32_PLL2_ENABLED)`/`#endif` condition instructions 50 lines below.

**Comment by Jowllel** [comment]
Thanks a lot the other problem is now solved. 
But the XSPI still throws an init error. (<err> flash_stm32_xspi: XSPI Init failed)
It seems that the clock for the XSPI isn't enabled on startup, so the flash driver tries to init the xspi again. (flash_stm32_xspi.c line 2055).

Or is this even the function you meant earlier, that bypasses the xspi init is MEMMAP is enabled? Because I find it a bit weird, that this functions throws an error when the init is bypassed. (line 2059)

File: drivers/clock_control/clock_stm32_ll_h5.c (hunk 6 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_h5.c]: switching the clock to HSI in case the pll1 is not the source clock of the xspi peripheral
--> `#else` part

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts [hunk 8]
```diff
@@ -406,9 +392,17 @@
...
 			#size-cells = <1>;
 
-			partition@0 {
-				label = "nor";
-				reg = <0x00000000 DT_SIZE_M(64)>;
+			slot0_partition: partition@0 {
+				label = "image-0";
+				reg = <0x00000000 DT_SIZE_M(16)>;
+			};
+			slot1_partition: partition@1000000 {
```
Comment (etienne-lms) [inline boards/st/stm32h573i_dk/stm32h573i_dk.dts:399]: add an empty line between subnodes.

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 9]
```diff
@@ -506,6 +517,16 @@ static int set_up_plls(void)
 #endif /* STM32_PLL_ENABLED */
 
 #if defined(STM32_PLL2_ENABLED)
+#if defined(CONFIG_STM32_MEMMAP) && defined(CONFIG_BOOTLOADER_MCUBOOT)
+	/*
+	 * If MEMMAP and MCUBOOT, then the OCTOSPI is necessarily also defined,
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c]: Compliance complains about the trailing space char at line end.

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 10]
```diff
@@ -434,6 +434,17 @@ static int set_up_plls(void)
...
 #if defined(STM32_PLL_ENABLED)
+
+#if defined(CONFIG_STM32_MEMMAP) && defined(CONFIG_BOOTLOADER_MCUBOOT)
+	/*
+	 * If MEMMAP and MCUBOOT, then the OCTOSPI is necessarily also defined,
+	 * don't disable PLL during application initialization that runs in memmap mode
+	 * when (Q/O)SPI uses PLL as its clock source but exit.
+	 */
+	if (LL_RCC_GetOSPIClockSource(LL_RCC_OSPI_CLKSOURCE) == LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
+		return 0;
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c]: I think returning now is not awaited. Maybe PLL2 and PLL3 are also to be enabled.
Implementation would maybe be simpler with 3 local helper functions: `set_up_pll1()`, `set_up_pll2()` and `set_up_pll3()`.

**Review by etienne-lms — CHANGES_REQUESTED** [review]

**Comment by Jowllel** [comment]
Since the latest commits my code gets stuck at:
```
I: Bootloader chainload address offset: 0x0
I: Image version: v1.0.0
I: Jumping to the first image slot
```

This also happens when I try to run the sysbuild with_mcuboot sample on the stm32h573i_dk board.

Additionally, I think the lines in the set_up_plls functions that detect if ospi uses the respective plls should look like this:
```
if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) == LL_RCC_OSPI_CLKSOURCE_PLL1Q)
```
instead of OSPIClockSource (These symbols don't exist)

**Comment by FRASTM** [comment]
> Since the latest commits my code gets stuck at:
> 
> ```
> I: Bootloader chainload address offset: 0x0
> I: Image version: v1.0.0
> I: Jumping to the first image slot
> ```
> 
> This also happens when I try to run the sysbuild with_mcuboot sample on the stm32h573i_dk board.
> 
> Additionally, I think the lines in the set_up_plls functions that detect if ospi uses the respective plls should look like this:
> 
> ```
> if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) == LL_RCC_OSPI_CLKSOURCE_PLL1Q)
> ```
> 
> instead of OSPIClockSource (These symbols don't exist)

Yes, I was preparing the branch for that and also matching with the https://github.com/mcu-tools/mcuboot/pull/2323
Fixing this now
Then I will prepare a new version including https://github.com/zephyrproject-rtos/zephyr/pull/88579#discussion_r2166136184

**Comment by FRASTM** [comment]
With `goto setup_pll;`   to avoid warnings at build ; to completes this PR, I propose to : 
- [ ]  set another PR   to split the pll clock for the stm32H5
- [ ] set another PR to support the stm32U5 series (st_stm32_ospi_nor compatible)

File: samples/boards/st/hello_world_xip/README.rst [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+west build -p always -b stm32h573i_dk samples/boards/st/hello_world_xip/ --sysbuild -- **-DSB_CONFIG_BOOTLOADER_MCUBOOT=y**
+west flash will Download the build/mcuboot/zephyr/zephyr.bin at internal flash address 0x08000000
+and the build/hello_world_xip/zephyr/zephyr.signed.bin at internal flash address 0x90000000 (chosen zephyr,code-partition)
+and executed on stm32h573i_dk as follows:
+
+.. zephyr-app-commands::
+   :zephyr-app: samples/boards/st/hello_world_xip
+   :host-os: unix
+   :board: stm32h573i_dk
+   :goals: run
```
Comment (etienne-lms) [inline samples/boards/st/hello_world_xip/README.rst]: Should add `:west-args --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y`?
and maybe remove the command line shown at line 28.

File: samples/boards/st/hello_world_xip/README.rst [hunk 12]
```diff
@@ -0,0 +1,65 @@
...
+
+Sample Output
+=============
+Code is executed in the external flash which has been configured in Memory Mapped mode
+by the mcuboot.
+
+
+.. code-block:: console
+
+    Hello World! from external flash b_u585i_iot02a
```
Comment (etienne-lms) [inline samples/boards/st/hello_world_xip/README.rst]: Is this first line expected?

File: samples/boards/st/hello_world_xip/src/main.c [hunk 13]
```diff
@@ -0,0 +1,58 @@
...
+	__ASM volatile ("MOV %0, PC\n" : "=r" (result));
+	return result;
+}
+
+int main(void)
+{
+	int ret;
+
+	printk("Hello World! from external flash  %s\n", CONFIG_BOARD);
+	printf("--> PC at 0x%x\n", __get_PC());
```
Comment (etienne-lms) [inline samples/boards/st/hello_world_xip/src/main.c]: Nitpicking: `printf()` vs `printk()`?

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 14]
```diff
@@ -501,12 +504,27 @@ static int set_up_plls(void)
...
 	while (LL_RCC_PLL1_IsReady() != 1U) {
 	}
+	goto setup_pll2;
 #else
 	/* Init PLL source to None */
 	LL_RCC_PLL1_SetSource(LL_RCC_PLL1SOURCE_NONE);
+	goto setup_pll2;
 #endif /* STM32_PLL_ENABLED */
-
+setup_pll2:
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c:551]: An empty line above would be welcome.
Ditto for `setup_pll3` branch label.

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts (hunk 8 above)
Comment (etienne-lms) [reply boards/st/stm32h573i_dk/stm32h573i_dk.dts:399]: ping

File: samples/boards/st/hello_world_xip/README.rst (hunk 11 above)
Comment (FRASTM) [reply samples/boards/st/hello_world_xip/README.rst]: done

File: samples/boards/st/hello_world_xip/src/main.c (hunk 13 above)
Comment (FRASTM) [reply samples/boards/st/hello_world_xip/src/main.c]: using "printf()"

File: drivers/clock_control/clock_stm32_ll_h5.c (hunk 14 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_h5.c:551]: done

File: samples/boards/st/hello_world_xip/README.rst (hunk 12 above)
Comment (FRASTM) [reply samples/boards/st/hello_world_xip/README.rst]: removed

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 15]
```diff
@@ -435,17 +435,21 @@ static int set_up_plls(void)
...
-	 * case we're currently running from the PLL we're about to
-	 * turn off and reconfigure.)
+	 * Don't disable PLL during application initialization
+	 * that runs in memmap mode when (Q/O)SPI uses PLL
+	 * as its clock source.
 	 */
-	if (LL_RCC_GetSysClkSource() == LL_RCC_SYS_CLKSOURCE_STATUS_PLL1) {
-		clock_switch_to_hsi();
+	if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) != LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
+		LL_RCC_PLL1_Disable();
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c]: We still need to switch to HSI IMHO.

See how this is handled in **clock_stm32_ll_h7.c**.

**Review by etienne-lms — CHANGES_REQUESTED** [review]

File: drivers/clock_control/clock_stm32_ll_h5.c (hunk 14 above)
Comment (etienne-lms) [reply drivers/clock_control/clock_stm32_ll_h5.c:551]: I meant:
```c
	(...)
#endif /* STM32_PLL_ENABLED */

setup_pll2:
	(...)
```

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 16]
```diff
@@ -554,11 +576,15 @@ static int set_up_plls(void)
...
+
+	goto setup_pll3;
 #else
 	/* Init PLL2 source to None */
 	LL_RCC_PLL2_SetSource(LL_RCC_PLL2SOURCE_NONE);
-#endif /* STM32_PLL2_ENABLED */
 
+	goto setup_pll3;
+#endif /* STM32_PLL2_ENABLED */
+setup_pll3:
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c]: ditto here;
```suggestion
#endif /* STM32_PLL2_ENABLED */

setup_pll3:

Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_h5.c]: new line added

**Comment by FRASTM** [comment]
I see the condition to "not disable the PLL if the OCTOSPI is clocked by the PLL" (CONFIG_STM32_MEMMAP  && CONFIG_BOOTLOADER_MCUBOOT) was wrong

1. when building the mcuboot, CONFIG_STM32_MEMMAP is set because the external octo flash is being configured in Memory Mapped mode, but CONFIG_BOOTLOADER_MCUBOOT is not set : in this case, the pll setup must be done at init
2. when building the application, CONFIG_STM32_MEMMAP is not set because the code is being executed from the external flash, the external octo flash is _already_ configured in Memory Mapped mode and must not be changed. The octospi is not supposed to be re-initialized, its source clock must not be changed, but CONFIG_BOOTLOADER_MCUBOOT is set : in this case the pll which sources the octospi clock must not be altered
I propose 
```
#if defined(CONFIG_BOOTLOADER_MCUBOOT)
	if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) == LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
		goto setup_pll2;
	}
#endif
	if (LL_RCC_GetSysClkSource() == LL_RCC_SYS_CLKSOURCE_STATUS_PLL1) {
		clock_switch_to_hsi();
	}

	LL_RCC_PLL1_Disable();
```

Ideally, we should find in zephyr a CONFIG flag to detect that it is running on the external flash after jumping from mcuboot. Could we consider this is CONFIG_BOOTLOADER_MCUBOOT

**Comment by JarmouniA** [comment]
> I see the condition to "not disable the PLL if the OCTOSPI is clocked by the PLL" (CONFIG_STM32_MEMMAP && CONFIG_BOOTLOADER_MCUBOOT) was wrong
> 
> 1. when building the mcuboot, CONFIG_STM32_MEMMAP is set because the external octo flash is being configured in Memory Mapped mode, but CONFIG_BOOTLOADER_MCUBOOT is not set : in this case, the pll setup must be done at init
> 2. when building the application, CONFIG_STM32_MEMMAP is not set because the code is being executed from the external flash, the external octo flash is _already_ configured in Memory Mapped mode and must not be changed. The octospi is not supposed to be re-initialized, its source clock must not be changed, but CONFIG_BOOTLOADER_MCUBOOT is set : in this case the pll which sources the octospi clock must not be altered

To detect that the Zephyr application being built is MCUboot, use CONFIG_MCUBOOT https://github.com/zephyrproject-rtos/zephyr/blob/4852719f98b3bac9c05196d9855d897f47e3c82f/modules/Kconfig.mcuboot#L11

> Ideally, we should find in zephyr a CONFIG flag to detect that it is running on the external flash after jumping from mcuboot. Could we consider this is CONFIG_BOOTLOADER_MCUBOOT 

That would be `CONFIG_BOOTLOADER_MCUBOOT && CONFIG_STM32_MEMMAP && CONFIG_XIP`

**Comment by FRASTM** [comment]
> > I see the condition to "not disable the PLL if the OCTOSPI is clocked by the PLL" (CONFIG_STM32_MEMMAP && CONFIG_BOOTLOADER_MCUBOOT) was wrong
> > 
> > 1. when building the mcuboot, CONFIG_STM32_MEMMAP is set because the external octo flash is being configured in Memory Mapped mode, but CONFIG_BOOTLOADER_MCUBOOT is not set : in this case, the pll setup must be done at init
> > 2. when building the application, CONFIG_STM32_MEMMAP is not set because the code is being executed from the external flash, the external octo flash is _already_ configured in Memory Mapped mode and must not be changed. The octospi is not supposed to be re-initialized, its source clock must not be changed, but CONFIG_BOOTLOADER_MCUBOOT is set : in this case the pll which sources the octospi clock must not be altered
> 
> To detect that the Zephyr application being built is MCUboot, use CONFIG_MCUBOOT
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/4852719f98b3bac9c05196d9855d897f47e3c82f/modules/Kconfig.mcuboot#L11
> 
> > Ideally, we should find in zephyr a CONFIG flag to detect that it is running on the external flash after jumping from mcuboot. Could we consider this is CONFIG_BOOTLOADER_MCUBOOT
> 
> That would be `CONFIG_BOOTLOADER_MCUBOOT && CONFIG_STM32_MEMMAP && CONFIG_XIP`

Not directly: the CONFIG_STM32_MEMMAP is for configuring the external xspi flash.Of course it is set when building the mcuboot. When building a zephyr application like samples/sysbuild/with_mcuboot or  samples/boards/st/hello_world_xip, there is no reason to have the xspi node enabled, there is no reason to have the CONFIG_STM32_MEMMAP set (see "depends on").

**Comment by JarmouniA** [comment]
> Not directly: the CONFIG_STM32_MEMMAP is for configuring the external xspi flash.Of course it is set when building the mcuboot. When building a zephyr application like samples/sysbuild/with_mcuboot or samples/boards/st/hello_world_xip, there is no reason to have the xspi node enabled, there is no reason to have the CONFIG_STM32_MEMMAP set (see "depends on").

Ah I missed this part. So I think a new symbol is needed that will be set for applications being executed in place from external Flash (there are already similar symbols used by other vendors).

**Comment by FRASTM** [comment]
> > Not directly: the CONFIG_STM32_MEMMAP is for configuring the external xspi flash.Of course it is set when building the mcuboot. When building a zephyr application like samples/sysbuild/with_mcuboot or samples/boards/st/hello_world_xip, there is no reason to have the xspi node enabled, there is no reason to have the CONFIG_STM32_MEMMAP set (see "depends on").
> 
> Ah I missed this part. So I think a new symbol is needed that will be set for applications being executed in place from external Flash (there are already similar symbols used by other vendors).

> executed in place

could you please point one as example ?

**Comment by JarmouniA** [comment]
> > Ah I missed this part. So I think a new symbol is needed that will be set for applications being executed in place from external Flash (there are already similar symbols used by other vendors).
> 
> executed in place
> could you please point one as example ?

https://github.com/zephyrproject-rtos/zephyr/blob/fdd02c5105d2a40cf6410cf89ccd22c43a48399e/soc/nxp/common/Kconfig.xspi_xip#L21

**Comment by Jowllel** [comment]
I just tested the hello_world_xip sample on the stm32h573i_dk board, and first it seems to work fine, as it doesn't throw any errors during compilation or running. But there still seems to be a problem (<err> flash_stm32_xspi: XSPI Init failed) with the flash reinitialization during application startup. This problem shows up when adding these lines to prj.conf:
```
CONFIG_FLASH=y
CONFIG_LOG=y
CONFIG_FLASH_LOG_LEVEL_ERR=y
```

But the flash API is used to update and control the images from the application. (Image Manager and similar)

Maybe it would be helpful to test whether the flash API works in the hello_world_xip sample...

Or does anyone have an idea, what needs to be fixed, so the external flash can be used from the application?

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 17]
```diff
@@ -435,7 +435,19 @@ static int set_up_plls(void)
 #endif
 
 #if defined(STM32_PLL_ENABLED)
+
+#if defined(CONFIG_BOOTLOADER_MCUBOOT)
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c]: I think we rather need a specific config switch (or DT property) to tell Zephur to not touch the PLL.
To be enabled when the Zephyr image executes from an external flash clocked with that PLL.

Comment (JarmouniA) [reply drivers/clock_control/clock_stm32_ll_h5.c]: > I think we rather need a specific config switch (or DT property) to tell Zephur to not touch the PLL. To be enabled when the Zephyr image executes from an external flash clocked with that PLL.

That's what is suggested here 
https://github.com/zephyrproject-rtos/zephyr/pull/88579#issuecomment-3032021862

**Comment by FRASTM** [comment]
> I just tested the hello_world_xip sample on the stm32h573i_dk board, and first it seems to work fine, as it doesn't throw any errors during compilation or running. But there still seems to be a problem ( flash_stm32_xspi: XSPI Init failed) with the flash reinitialization during application startup. This problem shows up when adding these lines to prj.conf:
> 
> ```
> CONFIG_FLASH=y
> CONFIG_LOG=y
> CONFIG_FLASH_LOG_LEVEL_ERR=y
> ```
> 
> But the flash API is used to update and control the images from the application. (Image Manager and similar)
> 
> Maybe it would be helpful to test whether the flash API works in the hello_world_xip sample...
> 
> Or does anyone have an idea, what needs to be fixed, so the external flash can be used from the application?

With this PR, the external flash is not for flash access other than XIP (in anycase this external NOR could be written during XiP). If you mean accessing to the external or even internal flash  during XiP in external NOR, that would be another PR, for sure.

File: drivers/clock_control/clock_stm32_ll_h5.c (hunk 17 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_h5.c]: I Agree. However don't you think this could be another PR since, originally, this one was for fixing the https://github.com/zephyrproject-rtos/zephyr/issues/87531

**Comment by Jowllel** [comment]
I just thought that the flash API problem belongs to this PR, because it's used by the mcuboot API and for the image manager. If the flash API doesn't work there's not a direct way to update the mcuboot images. So I think it's the same problem.
Or should I create a new Issue? (But then the Mcuboot only works partially in the zephyr version 4.2.0 when this PR is done.)

File: drivers/clock_control/clock_stm32_ll_h5.c (hunk 17 above)
Comment (FRASTM) [reply drivers/clock_control/clock_stm32_ll_h5.c]: I will 
1. introduce the new symbol  CONFIG_FLASH_STM32_XSPI_XIP  in _this PR_ for stm32h5
2. keep https://github.com/zephyrproject-rtos/zephyr/issues/92879  for updating the stm32h7 series with this KCONFIG

**Comment by FRASTM** [comment]
> Or should I create a new Issue?

Yes, please with the usecase being executed

File: samples/boards/st/hello_world_xip/README.rst [hunk 18]
```diff
@@ -0,0 +1,64 @@
...
+        zephyr,flash-controller = &mx25lm51245;
+    };
+
+
+Building and Running
+********************
+
+This application can be built with **sysbuild** and **SB_CONFIG_BOOTLOADER_MCUBOOT**
+West flash will Download the build/mcuboot/zephyr/zephyr.bin at internal flash address 0x08000000
+and the build/hello_world_xip/zephyr/zephyr.signed.bin at internal flash address 0x90000000 (chosen zephyr,code-partition)
```
Comment (erwango) [inline samples/boards/st/hello_world_xip/README.rst]: This is is the same that what is available with `samples/sysbuild/with_mcuboot` I'm not clear on what this new sample is bringing.

Comment (FRASTM) [reply samples/boards/st/hello_world_xip/README.rst]: yes, more or less
Removing this stm32 sample

**Comment by FRASTM** [comment]
introducing the symbol CONFIG_FLASH_STM32_XSPI_XIP  to identify the application being executed in place on the xspi flash, so that pll clock source of the xspi is not changed when booting that application from mcu boot

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts [hunk 19]
```diff
@@ -25,6 +25,7 @@
 		zephyr,code-partition = &slot0_partition;
 		zephyr,canbus = &fdcan1;
 		zephyr,display = &st7789v;
+		spi-flash0 = &mx25lm51245;
```
Comment (maass-hamburg) [inline boards/st/stm32h573i_dk/stm32h573i_dk.dts]: where is this being used? I didn't found the usage in tree.

Comment (FRASTM) [reply boards/st/stm32h573i_dk/stm32h573i_dk.dts]: that was more to keep similarity with some other boards with this kind of external nor flash devices mounted.

Comment (FRASTM) [reply boards/st/stm32h573i_dk/stm32h573i_dk.dts]: removed

**Comment by FRASTM** [comment]
- rebase on  Zephyr 4.2.0-rc2
- change the flash_stm32_xspi driver  to  control the xspi driver init : 


1.  depending on the `CONFIG_FLASH_STM32_XSPI_XIP` instead of `CONFIG_STM32_MEMMAP`
2.  check the clock_control_get_status: it  returns **CLOCK_CONTROL_STATUS_UNKNOWN** until the clock_stm32_ll_hr driver implements the stm32_clock_control_get_status API function

**Comment by FRASTM** [comment]
Add the get_status API function to the stm32h5 clock_control driver for the stm32h5 series (commit 6bfc93fa9d6263cb081fe4b217c95f521e88e96a)

Now the clock_control_get_status called by the flash_stm32_xspi driver during the driver initialization, returns CLOCK_CONTROL_STATUS_ON

File: samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay [hunk 20]
```diff
@@ -0,0 +1,16 @@
+/*
+ * Copyright (c) 2025 STMicroelectronics
+ *
+ * SPDX-License-Identifier: Apache-2.0
```
Comment (maass-hamburg) [inline samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay:4]: should probably also be added to the hawkbit sample, so the workaround of https://github.com/zephyrproject-rtos/zephyr/pull/92809 can be reversed

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts [hunk 21]
```diff
@@ -307,21 +307,6 @@
 			reg = <0x00000000 DT_SIZE_K(64)>;
```
Comment (maass-hamburg) [inline boards/st/stm32h573i_dk/stm32h573i_dk.dts:307]: maybe a good idea, to increase the mcuboot partition, now that the other space is no longer used

File: drivers/flash/flash_stm32_xspi.c [hunk 22]
```diff
@@ -2056,13 +2059,13 @@ static int flash_stm32_xspi_init(const struct device *dev)
 				     (clock_control_subsys_t) &dev_cfg->pclken)
 				     == CLOCK_CONTROL_STATUS_ON) {
 		if (stm32_xspi_is_memorymap(dev)) {
-			LOG_ERR("NOR init'd in MemMapped mode");
+			LOG_INF("NOR init'd in MemMapped mode");
```
Comment (JarmouniA) [inline drivers/flash/flash_stm32_xspi.c]: LOG_DBG

Comment (FRASTM) [reply drivers/flash/flash_stm32_xspi.c]: changed to LOG_DBG

File: soc/st/stm32/Kconfig.defconfig [hunk 23]
```diff
@@ -85,6 +85,13 @@ config FLASH_BASE_ADDRESS
 		if $(DT_FLASH_PARENT_IS_XSPI)
 	default $(dt_chosen_reg_addr_hex,$(DT_CHOSEN_Z_FLASH))
 
+# Allows the soc to safely initialize the clocks for the
+# xspi when planning to execute code in xspi Memory.
+# XIP is not set here and depends on each stm32 series (not set for stm32N6)
+config FLASH_STM32_XSPI_XIP
```
Comment (JarmouniA) [inline soc/st/stm32/Kconfig.defconfig]:
```suggestion
config STM32_APP_IN_XSPI_FLASH
```
The application residing in external Flash does not always mean it will be eXecuted in Place, that depends on the MCUboot mode used
https://github.com/mcu-tools/mcuboot/blob/9f209100336455c21f9f127f5bb9f2b5a394bb4f/boot/zephyr/Kconfig#L473
https://github.com/mcu-tools/mcuboot/blob/9f209100336455c21f9f127f5bb9f2b5a394bb4f/boot/zephyr/Kconfig#L464
https://github.com/mcu-tools/mcuboot/blob/9f209100336455c21f9f127f5bb9f2b5a394bb4f/boot/zephyr/Kconfig#L529

File: soc/st/stm32/Kconfig.defconfig [hunk 24]
```diff
@@ -85,6 +85,13 @@ config FLASH_BASE_ADDRESS
 		if $(DT_FLASH_PARENT_IS_XSPI)
 	default $(dt_chosen_reg_addr_hex,$(DT_CHOSEN_Z_FLASH))
 
+# Allows the soc to safely initialize the clocks for the
+# xspi when planning to execute code in xspi Memory.
+# XIP is not set here and depends on each stm32 series (not set for stm32N6)
```
Comment (JarmouniA) [inline soc/st/stm32/Kconfig.defconfig]:
```suggestion
# Allows the SoC clock driver to correctly initialize the 
# Q/O/XSPI controller clocks when the application is residing
# in external Flash and is chainloaded with MCUboot.
# Whether the app is eXecuted in Place (XiP) depends on the MCUboot mode used.
```

**Review by JarmouniA — CHANGES_REQUESTED** [review]

File: soc/st/stm32/Kconfig.defconfig (hunk 23 above)
Comment (erwango) [reply soc/st/stm32/Kconfig.defconfig]: Agreed, typically N6 actively supports both modes (XIP and RAMLOAD).
What about `STM32_APP_IN_EXT_MEM` to be sure we could reuse this flag for Q/OSPI ?

Comment (JarmouniA) [reply soc/st/stm32/Kconfig.defconfig]: EXT_FLASH would be better, to not confuse it with external RAM.

Comment (FRASTM) [reply soc/st/stm32/Kconfig.defconfig]: I see, I silly applied the NXP model  but **STM32_APP_IN_EXT_FLASH** sounds perfect

File: soc/st/stm32/Kconfig.defconfig (hunk 24 above)
Comment (FRASTM) [reply soc/st/stm32/Kconfig.defconfig]: comment changed as suggested

**Comment by FRASTM** [comment]
- changing the flag name to "CONFIG_STM32_APP_IN_EXT_FLASH" 
- rebase on main 7a8bd3dbe7528ff591a217b0dd81663c34a3c370
- revert the https://github.com/zephyrproject-rtos/zephyr/pull/92809 : CONFIG_BOOT_MAX_IMG_SECTORS is now 4096

File: soc/st/stm32/Kconfig.defconfig [hunk 25]
```diff
@@ -85,6 +85,14 @@ config FLASH_BASE_ADDRESS
 		if $(DT_FLASH_PARENT_IS_XSPI)
 	default $(dt_chosen_reg_addr_hex,$(DT_CHOSEN_Z_FLASH))
 
+# Allows the SoC clock driver to correctly initialize the
+# Q/O/XSPI controller clocks when the application is residing
+# in external Flash and is chainloaded with MCUboot.
+# Whether the app is eXecuted in Place (XiP) depends on the MCUboot mode used.
+config STM32_APP_IN_EXT_FLASH
```
Comment (etienne-lms) [inline soc/st/stm32/Kconfig.defconfig:88]: I think the config should be defined in **Kconfig** with the description in the `help` section.
This **Kconfig.defconfig** file would only set its default value.

File: samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay (hunk 20 above)
Comment (FRASTM) [reply samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay:4]: The CONFIG_BOOT_MAX_IMG_SECTORS is 4096, so yes  reverting

File: boards/st/stm32h573i_dk/stm32h573i_dk.dts (hunk 21 above)
Comment (FRASTM) [reply boards/st/stm32h573i_dk/stm32h573i_dk.dts:307]: Usually the boot partition is 64K, a next PR could resize but I am not sure this was the purpose here (mainly a bug fix)

File: drivers/flash/flash_stm32_xspi.c [hunk 26]
```diff
@@ -989,6 +979,19 @@ static int stm32_xspi_abort(const struct device *dev)
...
+
+#if defined(CONFIG_STM32_MEMMAP) || defined(CONFIG_STM32_APP_IN_EXT_FLASH)
+/* Function to return true if the octoflash is in MemoryMapped else false */
+static bool stm32_xspi_is_memorymap(const struct device *dev)
+{
+	struct flash_stm32_xspi_data *dev_data = dev->data;
+
+	return ((READ_BIT(dev_data->hxspi.Instance->CR,
+			  XSPI_CR_FMODE) == XSPI_CR_FMODE) ?
+			  true : false);
```
Comment (etienne-lms) [inline drivers/flash/flash_stm32_xspi.c]: By the way:
```suggestion
	return READ_BIT(dev_data->hxspi.Instance->CR, XSPI_CR_FMODE) == XSPI_CR_FMODE;

File: soc/st/stm32/Kconfig.defconfig (hunk 23 above)
Comment (JarmouniA) [reply soc/st/stm32/Kconfig.defconfig]: It's still not clear to me the relationship between `CONFIG_XIP` and the different MCUboot modes, does setting `CONFIG_XIP` in the app config override `CONFIG_SINGLE_APPLICATION_SLOT_RAM_LOAD` for example, or the opposite? @nordicjm could you please shed some light on this?
(this is in the context of MCUboot in internal Flash, & the app in external one)

**Review by etienne-lms — COMMENTED** [review]
For consistency, I would suggest to squash 2 commits and reorder some:
1. Commit *"soc: stm32: symbol for application XiP from xspi external memory"*;
2. A single commit that squashes:
  commit *"drivers: clock: stm32H5 clock control of the PLL in MemoryMapped mode"*
  and commit *"drivers: clock control of stm32 devices CONFIG external xspi flash"*;
3. Commit *"drivers: flash: stm32 xspi flash driver skip init when executing in place"*
4. Commit *"boards: arm: stm32h573 disco kit move partition to ext flash"*
5. Commit *"samples: sysbuild: with mcu_boot on the stm32h573i_dk"*
6. Commit *"Revert "samples: mgmt: hawkbit: force BOOT_MAX_IMG_SECTORS for stm32h573i_dk""*

IIUC commit *"drivers: clock control for stm32h5 driver implements control_get_status"* can be placed anywhere in this series.

For commit *"Revert "samples: mgmt: hawkbit: force BOOT_MAX_IMG_SECTORS for stm32h573i_dk""*, I think it would be nice  to add a few words in the commit message to exaplin why it's reverted. By the way, S-o-b tag is missing in that commit message.

File: samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay [hunk 27]
```diff
@@ -0,0 +1,16 @@
...
+ */
+
+/*
+ * Define the device, controller and partition to be the external memory
+ * for running the application in external NOR from MCUboot
+ */
+/ {
+	chosen {
+		zephyr,flash = &mx25lm51245;
```
Comment (maass-hamburg) [inline samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay:13]: maybe it would be better to use the gparent of the chosen zephyr,code-partition if USE_DT_CODE_PARTITION is enabled in general, as having this overlay needed when using a image with mcuboot.

Changes like:
```
diff --git a/soc/st/stm32/Kconfig.defconfig b/soc/st/stm32/Kconfig.defconfig
index aafb321151a..8544215e390 100644
--- a/soc/st/stm32/Kconfig.defconfig
+++ b/soc/st/stm32/Kconfig.defconfig
@@ -33,6 +33,13 @@ DT_CHOSEN_FLASH_NODE := $(dt_chosen_path,$(DT_CHOSEN_Z_FLASH))
 DT_CHOSEN_FLASH_PARENT := $(dt_node_parent,$(DT_CHOSEN_FLASH_NODE))
 DT_FLASH_PARENT_IS_XSPI := $(dt_node_has_compat,$(DT_CHOSEN_FLASH_PARENT),$(DT_COMPAT_XSPI))
 
+DT_CHOSEN_Z_CODE_PARTITION := zephyr,code-partition
+
+DT_CHOSEN_Z_CODE_PARTITION_NODE := $(dt_chosen_path,$(DT_CHOSEN_Z_CODE_PARTITION))
+DT_CHOSEN_Z_CODE_PARTITION_FLASH_NODE := $(dt_node_parent,$(dt_node_parent, $(DT_CHOSEN_Z_CODE_PARTITION_NODE)))
+DT_CHOSEN_Z_CODE_PARTITION_FLASH_PARENT := $(dt_node_parent,$(DT_CHOSEN_Z_CODE_PARTITION_FLASH_NODE))
+DT_CHOSEN_Z_CODE_PARTITION_FLASH_PARENT_IS_XSPI := $(dt_node_has_compat,$(DT_CHOSEN_Z_CODE_PARTITION_FLASH_PARENT),$(DT_COMPAT_XSPI))
+
 config SYS_CLOCK_HW_CYCLES_PER_SEC
 	default "$(DT_STM32_RCC_CLOCK_FREQ)" if "$(dt_nodelabel_enabled,rcc)"
 
@@ -81,6 +88,10 @@ config BUILD_WITH_TFM
 	default y if TRUSTED_EXECUTION_NONSECURE
 
 config FLASH_BASE_ADDRESS
+	default $(dt_node_reg_addr_hex,$(DT_CHOSEN_Z_CODE_PARTITION_FLASH_PARENT),1) \
+		if $(DT_CHOSEN_Z_CODE_PARTITION_FLASH_PARENT_IS_XSPI) && USE_DT_CODE_PARTITION
+	default $(dt_node_reg_addr_hex,$(DT_CHOSEN_Z_CODE_PARTITION_FLASH_NODE),1) \
+		if USE_DT_CODE_PARTITION
 	default $(dt_node_reg_addr_hex,$(DT_CHOSEN_FLASH_PARENT),1) \
 		if $(DT_FLASH_PARENT_IS_XSPI)
 	default $(dt_chosen_reg_addr_hex,$(DT_CHOSEN_Z_FLASH))
```

File: drivers/flash/flash_stm32_xspi.c (hunk 26 above)
Comment (FRASTM) [reply drivers/flash/flash_stm32_xspi.c]: done

File: samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay (hunk 27 above)
Comment (FRASTM) [reply samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay:13]: yes, but I am not sure this is the purpose of this PR fixing the issue for the 4.2.0 release

File: samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay (hunk 20 above)
Comment (maass-hamburg) [reply samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay:4]: this overlay should also be added to the hawkbit sample

File: samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay (hunk 27 above)
Comment (maass-hamburg) [reply samples/sysbuild/with_mcuboot/boards/stm32h573i_dk.overlay:13]: okay then in another PR

**Comment by FRASTM** [comment]
re-ordering commits as suggested

**Review by JarmouniA — DISMISSED** [review]
Thank you!

**Review by maass-hamburg — CHANGES_REQUESTED** [review]
the overlay file is also needed for the hawkbit sample

**Comment by FRASTM** [comment]
> the overlay file is also needed for the hawkbit sample

do you mean adding a  _samples/subsys/mgmt/hawkbit/boards/stm32h573i_dk.overlay_

```
/ {
	chosen {
		zephyr,flash = &mx25lm51245;
		zephyr,flash-controller = &mx25lm51245;
	};
};
```

**Comment by maass-hamburg** [comment]
> > the overlay file is also needed for the hawkbit sample
> 
> do you mean adding a _samples/subsys/mgmt/hawkbit/boards/stm32h573i_dk.overlay_
> 
> ```
> / {
> 	chosen {
> 		zephyr,flash = &mx25lm51245;
> 		zephyr,flash-controller = &mx25lm51245;
> 	};
> };
> ```

yes

**Comment by FRASTM** [comment]
with the samples/subsys/mgmt/hawkbit/boards/stm32h573i_dk.overlay   included

**Comment by FRASTM** [comment]
> > > the overlay file is also needed for the hawkbit sample
> > 
> > 
> > do you mean adding a _samples/subsys/mgmt/hawkbit/boards/stm32h573i_dk.overlay_
> > ```
> > / {
> > 	chosen {
> > 		zephyr,flash = &mx25lm51245;
> > 		zephyr,flash-controller = &mx25lm51245;
> > 	};
> > };
> > ```
> 
> yes

done

**Review by JarmouniA — APPROVED** [review]

**Review by maass-hamburg — APPROVED** [review]

File: soc/st/stm32/Kconfig [hunk 28]
```diff
@@ -104,4 +104,12 @@ config STM32_BACKUP_PROTECTION
 	  Enabled for SoCs for which access protection to backup domain
 	  resources needs to be explicitly handled.
 
+config STM32_APP_IN_EXT_FLASH
+	bool
+	help
+	  Allows the SoC clock driver to correctly initialize the
+	  Q/O/XSPI controller clocks when the application is residing
+	  in external Flash and is chainloaded with MCUboot.
+	  Whether the app is eXecuted in Place (XiP) depends on the MCUboot mode used.
```
Comment (etienne-lms) [inline soc/st/stm32/Kconfig:113]: Wrap line:
```suggestion
	  Whether the app is eXecuted in Place (XiP) depends on the
	  MCUboot mode used.
```

Actually, I would slightly rephrase the description:
```
	  Enable if Zephyr is executing in place from an external
	  flash which resources maybe be sensitive to reconfiguration,
	  e.g. on a xSPI device, its source clock must not be disabled.

File: soc/st/stm32/Kconfig [hunk 29]
```diff
@@ -104,4 +104,12 @@ config STM32_BACKUP_PROTECTION
 	  Enabled for SoCs for which access protection to backup domain
 	  resources needs to be explicitly handled.
 
+config STM32_APP_IN_EXT_FLASH
+	bool
```
Comment (etienne-lms) [inline soc/st/stm32/Kconfig:108]: `depends on XIP`?

File: drivers/clock_control/clock_stm32_ll_h5.c [hunk 30]
```diff
@@ -435,7 +435,19 @@ static int set_up_plls(void)
...
+	 * Don't disable PLL1 during application initialization
+	 * that runs on the external octospi flash (in memmap mode)
+	 * when (Q/O)SPI uses PLL1 as its clock source.
+	 */
+	if (LL_RCC_GetOCTOSPIClockSource(LL_RCC_OCTOSPI_CLKSOURCE) == LL_RCC_OSPI_CLKSOURCE_PLL1Q) {
+		goto setup_pll2;
+	}
+#endif /* CONFIG_STM32_APP_IN_EXT_FLASH */
 	/*
+	 * Case of chain-loaded applications:
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_h5.c:476]: Does this inline comment still apply?

**Review by etienne-lms — COMMENTED** [review]
Non-blocking comments:

1. Nitpicking in commit message for commit *"drivers: clock: stm32H5 clock control of the PLL in MemoryMapped mode"*.
```patch
-Do not disable the pll clock if it source the xspi and if the external
+Do not disable the PLL clock if it sources the XSIP and if the external
 flash is executing in Place. After mcuboot reset, the code is executed
 on the external flash, through the xspi.
-The CONFIG_STM32_APP_IN_EXT_FLASH tis set and will avoid re-config
+The CONFIG_STM32_APP_IN_EXT_FLASH is set and will avoid re-config
-of the pll which is sourcing the xspi peripheral. When excuting in Place
+of the PLL which is sourcing the XSPI peripheral. When executing in Place
-on this external NOR It must not disable its own clock source (PLL).
+on this external NOR, it must not disable its own clock source (PLL).
```
Or simplify:
```
Do not disable the PLL clock if it sources the XSIP and if the external
flash is executing in Place. CONFIG_STM32_APP_IN_EXT_FLASH 
provides this information.
```

2. In commit *"drivers: flash: stm32 xspi flash driver skip init when executing in place"*,
the below sentence in the commit message is no more true since the previous commit implements that API function:
> ... (stm32h5 has no clock_control_get_status API)

3. For commit *"Revert "samples: mgmt: hawkbit: force BOOT_MAX_IMG_SECTORS for stm32h573i_dk""*
This commit does more than reverting a commit. IMHO the commit message header line should not be *"Revert "samples: mgmt: ..."*.

3. Nitpicking on some commit message body: some terminal dots `.` are missing at end of sentences, see commits
*"drivers: flash: stm32 xspi flash driver skip init when executing in place"*,
*"boards: arm: stm32h573 disco kit move partition to ext flash"* and
*"samples: sysbuild: with mcu_boot on the stm32h573i_dk"*.

File: soc/st/stm32/Kconfig (hunk 29 above)
Comment (FRASTM) [reply soc/st/stm32/Kconfig:108]: no, because of the stm32N6 series

File: soc/st/stm32/Kconfig (hunk 28 above)
Comment (JarmouniA) [reply soc/st/stm32/Kconfig:113]: > Actually, I would slightly rephrase the description:
> 
> ```
> 	  Enable if Zephyr is executing in place from an external
> 	  flash which resources maybe be sensitive to reconfiguration,
> 	  e.g. on a xSPI device, its source clock must not be disabled.
> ```

The rephrasing is not correct, the option is not exclusive to XiP from external Flash. Plus `enable if.. ` would be misleading, the option is not supposed to be enabled by users.

File: soc/st/stm32/Kconfig (hunk 29 above)
Comment (etienne-lms) [reply soc/st/stm32/Kconfig:108]: On N6, if not XIP, the app does not execute in flash so maybe `CONFIG_STM32_APP_IN_EXT_FLASH` is not a good naming.

File: soc/st/stm32/Kconfig (hunk 28 above)
Comment (etienne-lms) [reply soc/st/stm32/Kconfig:113]: If XIP is not related, then it should maybe not be mentioned in the description.

I still find the description unclear. If xSPI specific, should it be named `CONFIG_STM32_APP_EXEC_XSPI`?

File: soc/st/stm32/Kconfig (hunk 29 above)
Comment (JarmouniA) [reply soc/st/stm32/Kconfig:108]: > so maybe CONFIG_STM32_APP_IN_EXT_FLASH is not a good naming.

No it is, see https://github.com/zephyrproject-rtos/zephyr/pull/88579#discussion_r2195205583

IN_EXT_FLASH means it is downloaded to external Flash, then it can either be eXecuted in Place or copied to RAM by MCUboot and executed there. What matters is that external Flash keeps working without interruption & stay in MemMapped mode when we jump from MCUboot to the app.

File: soc/st/stm32/Kconfig (hunk 28 above)
Comment (JarmouniA) [reply soc/st/stm32/Kconfig:113]: It's not XSPI specific.

File: soc/st/stm32/Kconfig (hunk 29 above)
Comment (etienne-lms) [reply soc/st/stm32/Kconfig:108]: OK thanks.

File: soc/st/stm32/Kconfig (hunk 28 above)
Comment (etienne-lms) [reply soc/st/stm32/Kconfig:113]: Ok, let's use `CONFIG_STM32_APP_IN_EXT_FLASH`. Maybe we'll refine the description later.

File: soc/st/stm32/Kconfig.defconfig (hunk 23 above)
Comment (nordicjm) [reply soc/st/stm32/Kconfig.defconfig]: you need to set the MCUboot mode which is independent of `CONFIG_XIP`

**Comment by FRASTM** [comment]
changes in some commit msg as recommended by @etienne-lms

**Review by etienne-lms — APPROVED** [review]

**Review by JarmouniA — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

File: soc/st/stm32/Kconfig [hunk 31]
```diff
@@ -104,4 +104,12 @@ config STM32_BACKUP_PROTECTION
...
+	help
+	  Allows the SoC clock driver to correctly initialize the
+	  Q/O/XSPI controller clocks when the application is residing
```
Comment (erwango) [inline soc/st/stm32/Kconfig:111]: So far, it only deals with XSPI. Q/O SPI will have to be updated to take it into account.

**Review by erwango — APPROVED** [review]
