### PR TITLE
arch: xtensa: Fix arch_is_in_isr() race condition

### LINKED ISSUE #92237: ace15_mtpm, ace20_lnl: kernel.multiprocessing.smp
### Describe the bug

Describe the bug
`intel_adsp/ace15_mtpm     kernel.multiprocessing.smp     FAILED Failed harness:'Testsuite failed'`

Expected behavior
Test should pass

### Regression

- [ ] This is a regression.

### Steps to reproduce

`twister -p intel_adsp/ace15_mtpm --device-testing --hardware-map HW_MAP -s tests/kernel/smp/kernel.multiprocessing.smp  -vv`

### Relevant log output

```shell
INFO:cavs-client:Start to monitor log output...
--
***** delaying boot 500ms (per build configuration) *****
*** Booting Zephyr OS build v4.1.0-6739-gc906d4a1039b (delayed boot 500ms) ***
Running TESTSUITE smp
===================================================================
START - test_coop_resched_threads
 PASS - test_coop_resched_threads in 0.051 seconds
===================================================================
START - test_coop_switch_in_abort
 PASS - test_coop_switch_in_abort in 0.201 seconds
===================================================================
START - test_cpu_id_threads
 PASS - test_cpu_id_threads in 1.001 seconds
===================================================================
START - test_fatal_on_smp
E:  **  A0 0xa0032b2c  SP 0xa0040cc0  A2 0x3  A3 0x4003f2d8
E:  **  A4 0xa00348f8  A5 0xa0042390  A6 0xa0040c90  A7 0x40046020
E:  **  A8 0  A9 0x40045fc0 A10 0x400451f0 A11 0x400451f0
E:  ** A12 0xa0038f24 A13 0xa0042370 A14 0 A15 0x1
E:  ** LBEG 0 LEND 0 LCOUNT 0
E:  ** SAR 0
E:  **  THREADPTR 0xa0040c90


Backtrace:0xa0032160:0xa0040cc0 0xa0032b29:0xa0040cd0 0xa0033d1b:0xa0040cf0 

E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 1
E: Current thread: 0x400451f0 (unknown)
E:  **  A0 0xa00332dd  SP 0xa0041380  A2 0x3  A3 0xa003c478
E:  **  A4 0xa003c06e  A5 0x32b  A6 0xa003cb8d  A7 0xa003c06e
E:  **  A8 0xa0032ab8  A9 0xa0041350 A10 0x927c00 A11 0x51[482](.../actions/runs/15892057412/job/44816290345#step:14:483)49
E:  ** A12 0x60020 A13 0 A14 0 A15 0
E:  ** LBEG 0xa00327a4 LEND 0xa00327af LCOUNT 0
E:  ** SAR 0x14
E:  **  THREADPTR 0x40045290


Backtrace:0xa0032160:0xa0041380 0xa00332da:0xa0041390 0xa00351b3:0xa00413d0 0xa0033d1b:0xa00413f0 

E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: 0x40045290 (test_fatal_on_smp)
 PASS - test_fatal_on_smp in 0.252 seconds
===================================================================
START - test_get_cpu
 PASS - test_get_cpu in 0.051 seconds
===================================================================
START - test_inc_concurrency
type 0: cnt 60000, spend 53 ms
type 1: cnt 60000, spend 2497 ms
type 2: cnt 60000, spend 2666 ms
 PASS - test_inc_concurrency in 5.215 seconds
===================================================================
START - test_preempt_resched_threads
 PASS - test_preempt_resched_threads in 0.512 seconds
===================================================================
START - test_sleep_threads
 PASS - test_sleep_threads in 1.001 seconds
===================================================================
START - test_smp_coop_threads
 PASS - test_smp_coop_threads in 0.563 seconds
===================================================================
START - test_smp_ipi
cpu num=3 PASS - test_smp_ipi in 0.301 seconds
===================================================================
START - test_smp_release_global_lock
 PASS - test_smp_release_global_lock in 0.021 seconds
===================================================================
START - test_smp_switch_torture
ASSERTION FAIL [!arch_is_in_isr()] @ WEST_TOPDIR/zephyr/kernel/poll.c:297
	
E:  ** FATAL EXCEPTION
E:  ** CPU 1 EXCCAUSE 63 (zephyr exception)
E:  **  PC 0xa0032163 VADDR 0
E:  **  PS 0x60020
E:  **    (INTLEVEL:0 EXCM: 0 UM:1 RING:0 WOE:1 OWB:0 CALLINC:2)
E:  **  A0 0xa0033d2c  SP 0xa003fce0  A2 0x4  A3 0x400458c0
E:  **  A4 0  A5 0x60020  A6 0x1  A7 0x4003f2d8
E:  **  A8 0x1  A9 0xa003fc60 A10 0x1 A11 0
E:  ** A12 0x400450d1 A13 0x25 A14 0x4 A15 0x1
E:  ** LBEG 0xa00327a4 LEND 0xa00327af LCOUNT 0
E:  ** SAR 0xc
E:  **  THREADPTR 0xa003fcd0


Backtrace:0xa0032160:0xa003fce0 0xa0033d29:0xa003fcf0 0xa003a956:0xa003fd10 0xa0032faa:0xa003fd50 0xa0033d1b:0xa003fd70 

E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 1
E: Current thread: 0x400450d0 (unknown)
wrong error reason
===================================================================
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: Linux
- Zephyr version: v4.1.0-6739-gc906d4a1039b
- Commit SHA: c906d4a1039b857b56556f00e4abf0eb9afc8e7e

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by peter-mitsis**
Fixes a flaw in the the Xtensa implementation of arch_is_in_isr() that could manifest on SMP systems. If the reading of the current CPU's nested interrupt count is not fully atomic on an SMP system, then an ill-timed context switch could occur leaving the caller reading the nested interrupt of a different CPU.

Fixes #92237.

Other architectures that support SMP have yet to be double checked for this implementation error. This fix should be back-ported to relevant versions.

### CODE REVIEW

File: arch/xtensa/include/kernel_arch_func.h [hunk 1]
```diff
@@ -278,7 +278,25 @@ static ALWAYS_INLINE void arch_cohere_stacks(struct k_thread *old_thread,
...
+	/*
+	 * Lock interrupts on SMP to ensure that the caller does not migrate
+	 * to another CPU before we get to read the nested field.
+	 */
+	unsigned int key;
+
+	key = arch_irq_lock();
+#endif
+
+	nested = arch_curr_cpu()->nested;
```
Comment (andyross) [inline arch/xtensa/include/kernel_arch_func.h:293]: Prefer `_current_cpu` for this pattern, which includes the lock and an assertion that interrupts are masked (because of exactly this bug condition: checking the CPU isn't enough to know you won't migrate before you use the info).  Obviously that's what we (I? guessing this is my code originally) should have done to start with.

**Review by andyross — COMMENTED** [review]
Nice catch.  Nitpick on the implementation.

**Comment by andyross** [comment]
> I? guessing this is my code originally

Nope!  I'm off the hook.  Looks like this goof dates back to the very first xtensa arch commit: https://github.com/zephyrproject-rtos/zephyr/blob/b78ceec452917aa00303623c2840a05f98d0115e/arch/xtensa/include/kernel_arch_func.h#L98

**Review by dcpleung — DISMISSED** [review]

**Comment by peter-mitsis** [comment]
@andyross - I made the switch to use _current_cpu.

**Review by dcpleung — APPROVED** [review]

**Review by dcpleung — CHANGES_REQUESTED** [review]
Wait... `_current_cpu` cannot be used here, as it asserts on `z_smp_cpu_mobile()` which calls `arch_is_in_isr()`. So infinite recursion...

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Oh, heh.  Well I guess not then; that probably explains why it wasn't used.  Looks great. :)
