### PR TITLE
drivers: usb: udc: stm32: dequeue OUT packets before submission

### LINKED ISSUE #102889: USB MSC regressions due to double-buffering
### Describe the bug

See also https://github.com/zephyrproject-rtos/zephyr/issues/94916#issuecomment-3790296277 and #94916

This may affect other vendors but I am unable to test due to lack of hardware.

More testing on different STM32 HW should be done as well - I will do it and update this message when time allows.

---

Commit 3c4b4e1ae22c01a1b4a12123db4e49038a8c78a6 introduced a "regression" in the Mass Storage Class when combined with the STM32 UDC driver:
* before the commit:
  * MSC I/O worked fine on Linux with some errors printed in `dmesg`
  * USB3CV `MSC Tests` suite mostly passed on Windows
    * crash when reaching `Command Set Test - Device Configured`
    * all prior tests passed
* after the commit:
  * MSC I/O works fine on Linux with no errors in `dmesg`
  * USB3CV `MSC Tests` suite no longer passes on Windows

---

Main problem: **commit 1243aba8e5a9565e761923a8f51c9a7273b32b6b** breaks MSC completely when combined with the STM32 UDC driver:
* MSC I/O not functional on Linux, errors in `dmesg`
* USB3CV `MSC Tests` error out due to timeout on Windows
  * whereas before, they would fail quickly

### Regression

- [ ] This is a regression.

### Steps to reproduce

Tested on `stm32f769i_disco`:
```
$ git checkout 81fd57078de4609d7ada72a037120f5e44d68021     # `main` as of writing
# revert usbd_msc.c to a non-broken revision
$ git revert --no-edit 152844a7e0f9edeb143cc8f865a23da7648968c0 7e11bc58172e0ae5804220e7f6e07a9c292c07df 1243aba8e5a9565e761923a8f51c9a7273b32b6b
$ west build ... && west flash
# try to access files on MSC: should work fine

# discard revert of commit that causes issues
$ git reset --hard HEAD~1
$ west build ... && west flash
# try to access files on MSC: should be broken
```

### Relevant log output

```shell

```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

- OS: Linux/Windows
- Toolchain: Zephyr SDK 0.17.4
- Commit SHA or version used: varies

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mathieuchopstm**
The `udc_submit_ep_event()` does not document this requirement, but the `net_buf` provided to it must have been removed from the driver's internal queue before submission. This wasn't noticed because the list node member of `net_buf` was untouched, but is now causing list corruption due to 5137439a47685e04b584eff973bc2090f48e7946 when multiple packets are enqueued.

Fix by always dequeuing buffers before submitting them to the UDC stack.

Fixes #102889

### CODE REVIEW

File: drivers/usb/udc/udc_stm32.c [hunk 1]
```diff
@@ -503,6 +503,7 @@ static void handle_msg_data_out(struct udc_stm32_data *priv, uint8_t epnum, uint
 		if (udc_ctrl_stage_is_status_out(dev)) {
 			/* s-in-status completed */
 			__ASSERT_NO_MSG(rx_count == 0);
+			(void)udc_buf_get(ep_cfg);  /* dequeue before submission */
```
Comment (tmon-nordic) [inline drivers/usb/udc/udc_stm32.c]: Instead of adding these `udc_buf_get()` calls here, why not replace `buf = udc_buf_peek(ep_cfg);` with `buf = udc_buf_get(ep_cfg);`?

By submitting the buffer, UDC loses the "ownership" and as such it must not have it stored anywhere.

Comment (mathieuchopstm) [reply drivers/usb/udc/udc_stm32.c]: The buffer is not always submitted - in L509~L524, we keep it enqueued and perform another RX from USB peripheral. When we do this, the buffer must remain at the head of the queue so we continue to append data to the specified buffer.

Another solution would be to always dequeue the buffer as you suggest, but store it in `struct net_buf *ongoing_ep0_out;` inside the driver data and keep appending to that until filled, but this is a much bigger change. Since I still have big rework PRs pending on this driver, I went for the minimal change (but I agree it's not super pretty).

**Comment by mathieuchopstm** [comment]
didn't mean to submit as draft but GitHub memorizes the last action taken...

**Review by tmon-nordic — DISMISSED** [review]

**Review by erwango — DISMISSED** [review]

File: drivers/usb/udc/udc_stm32.c (hunk 1 above)
Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c]: Current buffer "must remain at the head of the queue" until transfer is finished.

Comment (jfischer-no) [inline drivers/usb/udc/udc_stm32.c]: Why is there `(void)` and not just `buf =` like in other UDC drivers?
```c
			buf = udc_buf_get(ep_cfg);
```
Why is there `/* dequeue before submission */`, this is documented and there is no need for redundant comments. https://github.com/zephyrproject-rtos/zephyr/blob/7e84c87ed112ee4812583237cc98ccd7c3be6d19/drivers/usb/udc/udc_common.h#L82-L84

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/udc/udc_stm32.c (hunk 1 above)
Comment (mathieuchopstm) [reply drivers/usb/udc/udc_stm32.c]: > Why is there `(void)` and not just `buf =` like in other UDC drivers?
> 
> ```c
> 			buf = udc_buf_get(ep_cfg);
> ```

Because we already have a pointer to the buffer, we just need to dequeue it.

> Why is there `/* dequeue before submission */`, this is documented and there is no need for redundant comments.
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/7e84c87ed112ee4812583237cc98ccd7c3be6d19/drivers/usb/udc/udc_common.h#L82-L84

I prefer to make it obvious why `udc_buf_get()` needs to be called here, *especially* because the note is in `udc_buf_get()` rather than `udc_submit_ep_event()` where it would be more sensible IMO (or in both places, really)

Comment (mathieuchopstm) [reply drivers/usb/udc/udc_stm32.c]: So `Another solution` is not valid and my implementation is correct.

Comment (mathieuchopstm) [reply drivers/usb/udc/udc_stm32.c]: changed to `buf = udc_buf_get()` and reworded comments

Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c]: > I prefer to make it obvious why `udc_buf_get()` needs to be called here, _especially_ because the note is in `udc_buf_get()` rather than `udc_submit_ep_event()` where it would be more sensible IMO (or in both places, really)

I do not think so and I do not see any ambiguity. It does not seem like there are similar mistakes on other drivers (or new drivers).

**Review by jfischer-no — APPROVED** [review]

**Review by erwango — APPROVED** [review]
