### PR TITLE
Bluetooth: Audio: Fix initial Broadcast source values

### LINKED ISSUE #79189: Bluetooth: Audio:  BAP Broadcast Assistant fails on broadcast_id = 0x000000
**Describe the bug**
With a broadcast ID of 0x000000, the BAP Broadcast Assistant fails validity check for broadcast_id.

The issue seems that on reset, broadcast_id gets set to 0 and later comparison with a broadcast ID of 0x000000 then get's faulty detected as "already added".

**To Reproduce**
Add a broadcast source with broadcast ID 0x000000

**Expected behavior**
The broadcast source is added to the connected sink.

**Impact**
Although unlikely (1 of 2^24 combinations), broadcast ID = 0x000000 can't be added.

**Logs and console output**
N/A

**Suggested solution**
Assign a value higher than 0xFFFFFF (largest broadcast ID) to broadcast_id on reset.

### PR DESCRIPTION
**Pull request by larsgk**
If the Broadcast ID is initially set to 0x000000,
which is valid, comparison logic on add of an
actual Broadcast ID of 0x000000 fails.

Likewise for SID.

Moving INVALID_BROADCAST_ID define to bap.h

### CODE REVIEW

**Comment by larsgk** [comment]
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/79189

File: include/zephyr/bluetooth/audio/bap.h [hunk 1]
```diff
@@ -41,6 +41,8 @@
 extern "C" {
 #endif
 
+#define INVALID_BROADCAST_ID 0xFFFFFFFFU
+
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:45]: Needs doxygen documentation

**Review by Thalley — CHANGES_REQUESTED** [review]
The "fixes" part needs to be in the PR description, and not a comment

File: include/zephyr/bluetooth/audio/bap.h [hunk 2]
```diff
@@ -41,6 +41,11 @@
 extern "C" {
 #endif
 
+/**
+ * An invalid Broract ID
+ */
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:46]:
```suggestion
/** Invalid Broadcast ID */
```

File: include/zephyr/bluetooth/audio/bap.h [hunk 3]
```diff
@@ -41,6 +41,11 @@
 extern "C" {
 #endif
 
+/**
+ * An invalid Broadcast ID
+ */
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:46]:
```suggestion
/** An invalid Broadcast ID */
```

This can be on a single line

File: include/zephyr/bluetooth/audio/bap.h [hunk 4]
```diff
@@ -41,6 +41,11 @@
...
+#define INVALID_BROADCAST_ID 0xFFFFFFFFU
```
Comment (Thalley) [inline include/zephyr/bluetooth/audio/bap.h:47]:
```suggestion
#define BT_BAP_INVALID_BROADCAST_ID 0xFFFFFFFFU
```

Missing proper prefix

**Review by Thalley — CHANGES_REQUESTED** [review]

File: samples/bluetooth/pbp_public_broadcast_sink/src/main.c [hunk 5]
```diff
@@ -203,7 +202,7 @@ static bool scan_check_and_sync_broadcast(struct bt_data *data, void *user_data)
 		 * Continue parsing if Broadcast Audio Announcement Service
 		 * was not found.
 		 */
-		if (*broadcast_id == INVALID_BROADCAST_ID) {
+		if (*broadcast_id == BT_BAP_INVALID_BROADCAST_IDD_BROADCAST_ID) {
```
Comment (Thalley) [inline samples/bluetooth/pbp_public_broadcast_sink/src/main.c:205]: Search and replace gone wrong? :D

**Review by Thalley — CHANGES_REQUESTED** [review]

**Review by Thalley — APPROVED** [review]

**Review by niym-ot — APPROVED** [review]
