### PR TITLE
remove qemu's systick workaround

### LINKED ISSUE #18591: tests/kernel/fifo/fifo_timeout/kernel.fifo.timeout.poll fails to run on multiple ARM platforms
With commit: aed767a98c00bc11b5455fb60c3a3d8f0bda37c0

Running via:

`./scripts/sanitycheck -p frdm_kw41z --device-testing  --device-serial /dev/serial/by-id/usb-ARM_DAPLink_CMSIS-DAP_0201000028634e45000b5002673a0032a101000097969900-if01 -s tests/kernel/fifo/fifo_timeout/kernel.fifo.timeout.poll`

Get the following output:

```
***** Booting Zephyr OS build v2.0.0-rc1-173-gaed767a98c00 *****
Running test suite test_fifo_timeout
===================================================================
starting test - test_timeout_empty_fifo
PASS - test_timeout_empty_fifo
===================================================================
starting test - test_timeout_non_empty_fifo
PASS - test_timeout_non_empty_fifo
===================================================================
starting test - test_timeout_fifo_thread
PASS - test_timeout_fifo_thread
===================================================================
starting test - test_timeout_threads_pend_on_fifo
 thread (q order: 2, t/o: 0, fifo 0x20000008)
 thread (q order: 3, t/o: 10, fifo 0x20000008)
 thread (q order: 0, t/o: 20, fifo 0x20000008)
 thread (q order: 4, t/o: 30, fifo 0x20000008)
 thread (q order: 1, t/o: 40, fifo 0x20000008)
PASS - test_timeout_threads_pend_on_fifo
===================================================================
starting test - test_timeout_threads_pend_on_dual_fifos
 thread (q order: 0, t/o: 0, fifo 0x2000001c)
FAIL - test_multiple_threads_pending@188.  *** thread 3 woke up, expected 1

    Assertion failed at ZEPHYR_BASE/tests/kernel/fifo/fifo_timeout/src/main.c:467: test_timeout_threads_pend_on_dual_fifos: rv not equal to TC_PASS

FAIL - test_timeout_threads_pend_on_dual_fifos
===================================================================
starting test - test_timeout_threads_pend_fail_on_fifo
FAIL - test_multiple_threads_get_data@240.  *** thread 5 woke up, expected 0

    Assertion failed at ZEPHYR_BASE/tests/kernel/fifo/fifo_timeout/src/main.c:488: test_timeout_threads_pend_fail_on_fifo: rv not equal to TC_PASS


    Assertion failed at ZEPHYR_BASE/tests/kernel/fifo/fifo_timeout/src/main.c:131: test_thread_pend_and_timeout: packFATAL: ***** HARD FAULT *****
FATAL: r0/a1:  0x20000320  r1/a2:  0x00000000  r2/a3:  0x20003c94
FATAL: r3/a4:  0x00000000 r12/ip:  0x20000000 r14/lr:  0x00004697
FATAL:  xpsr:  0x6100000f
FATAL: Faulting instruction address (r15/pc): 0x00004296
FATAL: >>> ZEPHYR FATAL ERROR 0: CPU exception
FATAL: Current thread: 0x20000410 (unknown)
FATAL: Halting system

```

### PR DESCRIPTION
**Pull request by agansari**
Removed workarounds in systick driver as they prevent normal usage in TICKLESS systems. 
Set qemu parameter for MPS2 targets: -icount auto.
CONFIG_SOC_SERIES_MPS2 specific test workaround is removed to use systick drives as tickless.
test_sched_timeslice_reset - loosen tolerance for slow ticking systems.

Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>

### CODE REVIEW

**Comment by agansari** [comment]
@galak It's the opposite way around, both my MCU had 48MHz clocks, and CONFIG_SYS_CLOCK_TICKS_PER_SEC=10.000 as default tickless this means a CYC_PER_TICK=4800. Overflow condition was hardly reached and cycle count was always incremented regardless of overflow.

**Review by andyross — APPROVED** [review]
This looks safe and correct (one style/optimization nitpick).  I'm confused why you were seeing early interrupts though.  Under what circumstances will a CPU throw a timer interrupt if the COUNTFLAG bit is **not** set?!  Per documentation that should never happen, as I read it.

Is something else hooked to your timer interrupt on the affected platorms maybe?

File: drivers/timer/cortex_m_systick.c [hunk 1]
```diff
@@ -87,14 +87,16 @@ void z_clock_isr(void *arg)
 {
 	ARG_UNUSED(arg);
 	u32_t dticks;
+	u32_t bool_cnt_flag;
 
-	cycle_count += last_load;
+	bool_cnt_flag = (SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk); /* Reset overflow flag */
```
[the remark this answers is not in the document]
Comment (agansari) [reply drivers/timer/cortex_m_systick.c]: @pabigot i find #15487 as being a better solution to this issue, but as far as i know it has some issues on other boards, maybe that pull should be revisited @ioannisg

File: drivers/timer/cortex_m_systick.c [hunk 2]
```diff
@@ -87,14 +87,16 @@ void z_clock_isr(void *arg)
...
+	bool_cnt_flag >>= SysTick_CTRL_COUNTFLAG_Pos;
+	overflow_cyc = 0;
+
+	cycle_count += last_load * bool_cnt_flag;
```
[the remark this answers is not in the document]
Comment (agansari) [reply drivers/timer/cortex_m_systick.c]: Yes I've wrote it this way to avoid a jump condition, but it has no advantage in thumb code.

Will change it to a?b:c as in other places in this file.

**Comment by ioannisg** [comment]
We really need to do something with this - the fifo-timeout test is now failing for several ARM boards with Systick timer

**Comment by agansari** [comment]
> We really need to do something with this - the fifo-timeout test is now failing for several ARM boards with Systick timer

@ioannisg @galak @pabigot @andyross I've resolved part of the newer issues that it introduces, it starts to look a lot like #15487 and i think that should rather be merged as it's better comented.
The issue i'm still having is `tests/kernel/sched/schedule_api ` failing on MPS2 qemu.

**Comment by agansari** [comment]
@ioannisg @galak @pabigot @andyross fixed the timer's issues in qemu, patch should be good now.

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg @galak @pabigot @andyross fixed the timer's issues in qemu, patch should be good now.

Let's add a HW Block - and I am going to test this on whatever HW I have.
I think we need to be confident that this works on as many platforms as possible

**Comment by agansari** [comment]
Thank you @ioannisg

**Comment by ioannisg** [comment]
`tests/kernel/timer` (`timer_api `and `timer_monotonic`) are failing for `atsamr21_xpro`. The tests are passing on `sam_e70_xplained` board.

**Comment by ioannisg** [comment]
`tests/kernel/sched` is failing for `lpcxpresso54114_m4`.

**Comment by ioannisg** [comment]
All tests are passing on `frdm_k64f`

**Comment by agansari** [comment]
> `tests/kernel/sched` is failing for `lpcxpresso54114_m4`.

@ioannisg this is #18282, i have also observed this issue showed-up again. It's somewhat inconsistent, if i change test order, or add debug prints it disappears. Think we can reopen #18282 an continue debug from there.

File: drivers/timer/cortex_m_systick.c [hunk 3]
```diff
@@ -88,13 +88,18 @@ void z_clock_isr(void *arg)
...
 
+	elapsed();
+
+#if !IS_ENABLED(CONFIG_QEMU_TICKLESS_WORKAROUND)
+	cycle_count += overflow_cyc;
+#else
+	/* QEMU will send IRQ, but not sure about setting SysTick->CTRL */
 	cycle_count += last_load;
+#endif
+	overflow_cyc = 0;
```
Comment (pabigot) [inline drivers/timer/cortex_m_systick.c]: This isn't a new problem, but I'm concerned about a race condition here: this mutates `overflow_cyc` without holding the spinlock.  If a higher priority interrupt invokes `elapsed()` through any other function (like `z_clock_elapsed()` or `z_timer_cycle_get_32()` or `z_clock_set_timeout()`) information may be lost.

**Review by pabigot — DISMISSED** [review]
Noting what looks like a race condition.  If it isn't I'll switch to "approve" so we can get rc3 out.  @ioannisg

File: drivers/timer/cortex_m_systick.c (hunk 3 above)
Comment (agansari) [reply drivers/timer/cortex_m_systick.c]: @pabigot you are right, as all other uses of `elapsed()` are guarded by spinlocks, i've added an irq lock so no other ISR would also call `elapsed()`. 
I was debugging #18282 and what @andyross suggested (blocking multiple irq interrupts by using a busy wait). Looks like guarding the variable changes in `elapsed()` makes the behavior coherent.

File: drivers/timer/cortex_m_systick.c [hunk 4]
```diff
@@ -87,15 +87,17 @@ void z_clock_isr(void *arg)
...
 	dticks = (cycle_count - announced_cycles) / CYC_PER_TICK;
 	announced_cycles += dticks * CYC_PER_TICK;
 
-	overflow_cyc = SysTick->CTRL; /* Reset overflow flag */
-	overflow_cyc = 0U;
-
 	z_clock_announce(TICKLESS ? dticks : 1);
+
+	irq_unlock(key);
```
Comment (pabigot) [inline drivers/timer/cortex_m_systick.c]: I'm very certain you do **not** want the lock held during `z_clock_announce()` which can take arbitrarily long.   Move it before that call, please.

Comment (agansari) [reply drivers/timer/cortex_m_systick.c]: @pabigot thanks! pushed again.

**Review by pabigot — APPROVED** [review]
I don't have a hardware platform to test this, but by inspection it makes sense.

**Comment by ioannisg** [comment]
@agansari tests/kernel/timer/timer_api fails on frdm_k64f, AFAICS - can you check?

**Comment by ioannisg** [comment]
Fails also on sam_e70_xplained and atsamr21_xpro

**Comment by ioannisg** [comment]
I moved this to 2.1 since some test issues were not resolved in time for 2.0

**Comment by pabigot** [comment]
@ioannisg are the failures on real hardware?  tests/kernel/timer/timer_api passes on frdm_k64f for me with both default and tickless configurations.

I also looked at a couple of the shippable failures on mps2_an385 yesterday and they seem likely to be due to qemu per https://github.com/zephyrproject-rtos/zephyr/pull/18651#discussion_r319100694; they also worked on k64f hardware.  I don't have an385 hardware to check.

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg are the failures on real hardware? tests/kernel/timer/timer_api passes on frdm_k64f for me with both default and tickless configurations.
> 
> I also looked at a couple of the shippable failures on mps2_an385 yesterday and they seem likely to be due to qemu per [#18651 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/18651#discussion_r319100694); they also worked on k64f hardware. I don't have an385 hardware to check.

@pabigot thanks really for looking at this. So, it seems that @agansari also reports the test passing on frdm_k64f. But I see it constantly failing on mine. And also on the ATSAM boards I tested it.

@galak @nashif could you do some last minute testing here? E.g. try on a couple of SysTick ARM boards. Otherwise, I would say it's better to finalize this after 2.0 release.

**Comment by agansari** [comment]
Issue is still under debugging, there are sanity checks that still fail randomly: sched multiq and tickless concept on MPS2 qemu.
Can't test on atsam boards.

**Comment by wentongwu** [comment]
oh, just see you are enabling Qemu icount, Also I'm doing this work(see https://github.com/wentongwu/zephyr/tree/qemu and https://github.com/wentongwu/zephyr/tree/icount), I'm running stress test with "for i in 
 {1.. 100000}; do ./scripts/sanitycheck -p mps2_an385 -T tests/kernel/ --icount-shift 5 -v ; done" with branch https://github.com/wentongwu/zephyr/tree/icount

**Comment by agansari** [comment]
@wentongwu yes, i am aware of #14173 which is trying to remove icount. I had to use icount as qemu was unpredictable without it; the way systick was implemented in qemu was a workaround.

**Comment by wentongwu** [comment]
> @wentongwu yes, i am aware of #14173 which is trying to remove icount. I had to use icount as qemu was unpredictable without it; the way systick was implemented in qemu was a workaround.

Why you say “ #14173 which is trying to remove icount“?

**Comment by agansari** [comment]
> Why you say “ #14173 which is trying to remove icount“?

Sorry, wanted to say remove the workaround and enable icount

**Comment by wentongwu** [comment]
ok, Thanks. 
"the way systick was implemented in qemu was a workaround" could you please talk more about this? Actually I debug the systick in Qemu(armv7m_systick.c) with gdb for icount mode, at least for software emulation, I think it works. @agansari Thanks.

**Comment by agansari** [comment]
@wentongwu i have a problem with the following line of code:
`z_clock_announce(TICKLESS ? dticks : 1);`
with the workaround it always behaves as a tick based system, not a tickless one where it counts how far it got, it relies on interrupts and not the actual timer value. 
This is why i removed `CONFIG_QEMU_TICKLESS_WORKAROUND` from `TICKLESS `macro

**Comment by wentongwu** [comment]
> @wentongwu i have a problem with the following line of code:
> `z_clock_announce(TICKLESS ? dticks : 1);`
> with the workaround it always behaves as a tick based system, not a tickless one where it counts how far it got, it relies on interrupts and not the actual timer value.
> This is why i removed `CONFIG_QEMU_TICKLESS_WORKAROUND` from `TICKLESS `macro

Ok, Thanks, I will consider it. 
And I thought you found some bugs in Qemu for sysTick.

**Comment by carlescufi** [comment]
@galak please merge this if ready

**Comment by ioannisg** [comment]
> 
> 
> @galak please merge this if ready

@galak @carlescufi I don't this this is ready.
@agansari pls, advice.

**Comment by galak** [comment]
> @galak @carlescufi I don't this this is ready. Have we reviewed the tolerance introduced in the test?
> @agansari please, advice. :)

Need to re-test, not sure we've addressed the failing testcases that this caused.

**Comment by agansari** [comment]
@galak @carlescufi @ioannisg i am still investigating on MPS2 QEMU sched and tickless concept tests, so it's not ready to merge.
Can we have someone from atmel look at why it's failing on sam_e70_xplained/atsamr21_xpro? I don't have these boards.

**Review by pabigot — CHANGES_REQUESTED** [review]
I've compared this solution against #15487.

* The original problem with tests/kernel/fifo/fifo_timeout/prj_poll was reproduced on atsamd21_xpro on master d5633bc395b2bc8ce9f7685e8df9ead43deb20c3: it always fails
* I rebased this on master d5633bc395b2bc8ce9f7685e8df9ead43deb20c3
* tests/kernel/fifo/fifo_timeout/prj_poll passes reliably on atsamd21_xpro

However this PR incorporates other changes, one of which looks very wrong, and I'm still uncomfortable with the way this deals with the systick issue (see https://github.com/zephyrproject-rtos/zephyr/pull/18651#discussion_r317940005).

I propose that #15487 be re-reviewed and if no other concerns are discovered that it be merged.  The additional patches in this PR can then be checked to see if they're still relevant, and merged on their own merits.

File: tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c [hunk 5]
```diff
@@ -22,6 +22,15 @@ BUILD_ASSERT(NUM_THREAD <= MAX_NUM_THREAD);
 #define HALF_SLICE_SIZE_CYCLES \
 	((u64_t)(HALF_SLICE_SIZE) * sys_clock_hw_cycles_per_sec() / 1000)
 
+/* Task switch tolerance ... */
+#if CONFIG_SYS_CLOCK_TICKS_PER_SEC < 1000
```
[the remark this answers is not in the document]
Comment (agansari) [reply tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c]: @pabigot you are right, i reversed the condition.

**Comment by agansari** [comment]
@pabigot @ioannisg I agree to merging #15487 and then fixing the other issues related to QEMU and slow ticks/sec in this pull.

**Comment by ioannisg** [comment]
> 
> 
> @pabigot @ioannisg I agree to merging #15487 and then fixing the other issues related to QEMU and slow ticks/sec in this pull.

We cannot merge #15487 with QEMU failures; we need to resolve them somehow, or exclude the platforms from these tests. Ideally, we should find out if we can improve QEMU boards so the tests do not fail, or go ahead with your proposal of adding some slack in the error-prone tests, e.g. the scheduler

File: tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c [hunk 6]
```diff
@@ -19,8 +19,17 @@ BUILD_ASSERT(NUM_THREAD <= MAX_NUM_THREAD);
...
+#define HALF_SLICE_SIZE_CYCLES                                                 \
+	((u64_t)(HALF_SLICE_SIZE)*sys_clock_hw_cycles_per_sec() / 1000)
+
+/* Task switch tolerance ... */
+#if CONFIG_SYS_CLOCK_TICKS_PER_SEC >= 1000
+/* ... will not take more than 1 ms. */
+#define TASK_SWITCH_TOLERANCE (1)
+#else
+/* ... 1ms is faster than a tick, loosen tolerance to 1 tick */
+#define TASK_SWITCH_TOLERANCE (1000 / CONFIG_SYS_CLOCK_TICKS_PER_SEC)
```
Comment (pabigot) [inline tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c]: This is vulnerable to a repeated-truncation problem that's showed up multiple times in the past.  For example, if `CONFIG_SYS_CLOCK_TICKS_PER_SEC` is 256 the tolerance should be 3.90625 ms, but it'll be truncated to 3 ms.  In actual use durations of 256 ticks will appear to be either 3 or 4 ms long, averaging to the true value.

Below the tolerance is used to calculate both a lower bound and an upper bound, where it is again truncated.  The problem is that for the lower bound it's appropriate to subtract 3, but for the upper bound you must add 4.  If you only add 3 you get intermittent failures in the cases where the experienced duration maps to 4 ms.

This is exactly the sort of thing that #19591 will help with, by providing conversion functions that round in the direction necessary for the specific use, so in hopes that we get that unstuck and merged soon I'm ok with merging this as is, with a plan to replace the calculations with accurate ones once infrastructure is available to support that.

**Review by pabigot — APPROVED** [review]
An observation below, I don't think it should block this.

#15847 rebased on top of this passes all mps2_an385 tests/kernel checks\*.  Without this PR under it two fail consistently.

\* timer_api/kernel.timer  still fails intermittently but passes on a second try, unlike kernel/sched/schedule_api/kernel.sched.* which persistently fail without this.

File: tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c (hunk 6 above)
Comment (agansari) [reply tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c]: Thank you @pabigot and @ioannisg.
I changed the title and description to reflect the new purpose of this PR.

Should we have this PR merged and then add a new PR for mathematical rounding or would something like `ceiling_fraction` macro do the job in a new force push? @pabigot

Comment (pabigot) [reply tests/kernel/sched/schedule_api/src/test_sched_timeslice_reset.c]: Yes, I'd like this to go in as-is.  We're waiting on #19591 to provide `k_ticks_to_ms_ceil32()` API to help with the potential concern I identified.

**Review by ioannisg — APPROVED** [review]
This PR looks OK to me. I am happy that the workaround for MPS2 is removed. I ran all tests locally for mps2_an385 and mps2_an521; they all pass.

What is left to think about is whether more timing-sensitive tests require this kind of tolerance. I feel it is not only the sched tests; at least the timer_api and several benchmark tests are good candidates.

**Comment by ioannisg** [comment]
@andyross would you be able to take a look at the tolerance added to the kernel/sched tests?

Other than that, @nashif @MaureenHelm,  this is an ARM & ARM QEMU -only change, and looks merge-able to me
