### PR TITLE
soc/xtensa/intel_adsp: Fix IPC issues

### LINKED ISSUE #46426: Intel CAVS: Assertion failures on tests/boards/intel_adsp/smoke
**Describe the bug**
 Assertion failures in test_host_ipc & test_clock_calibrate under tests/boards/intel_adsp/smoke on all CAVS platforms.

**To Reproduce**
1. twister -W --hardware-map /home/ztest/cavs/cavs.map --device-testing -x=CONFIG_BOOT_DELAY=500 -T tests/boards/intel_adsp/smoke/ --no-skipped-report -vvvv
2. See error

**Logs and console output**
```
INFO:cavs-client:Monitor process
INFO:cavs-client:Sent:     start_log
INFO:cavs-client:Receive: start_log
INFO:cavs-client:Start to monitor log output...
--
***** delaying boot 500ms (per build configuration) *****
Running TESTSUITE intel_adsp
===================================================================
START - test_smp_boot_delay
Launch cpu1
PASS - test_smp_boot_delay in 0.21 seconds
===================================================================
START - test_cpu_halt
SKIP - test_cpu_halt in 0.1 seconds
===================================================================
START - test_post_boot_ipi
PASS - test_post_boot_ipi in 0.1 seconds
===================================================================
START - test_cpu_behavior
Per-CPU smoke test 0...
Cache behavior check
CCOUNT/WALCLK ratio 19.809
CPI = 2.499
Per-CPU smoke test 1...
Cache behavior check
CCOUNT/WALCLK ratio 19.797
CPI = 2.499
PASS - test_cpu_behavior in 0.1 seconds
===================================================================
START - test_host_ipc
Simple message send...
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/intel_adsp/smoke/src/hostipc.c:44: test_host_ipc: (i < 10000 is false)
timeout waiting for cavs_ipc_is_complete(CAVS_HOST_DEV)
FAIL - test_host_ipc in 0.503 seconds
===================================================================
START - test_clock_calibrate
Assertion failed at WEST_TOPDIR/zephyr/tests/boards/intel_adsp/smoke/src/hostipc.c:28: ipc_done: (done_flag is true)
done called unexpectedly
```
```
START - test_host_ipc
Simple message send...

Assertion failed at WEST_TOPDIR/zephyr/tests/boards/intel_adsp/smoke/src/hostipc.c:44: test_host_ipc: (i < 10000 is false)
timeout waiting for cavs_ipc_is_complete(CAVS_HOST_DEV)
FAIL - test_host_ipc in 0.503 seconds
```

**Environment (please complete the following information):**
 - OS: Fedora
 - Toolchain (e.g Zephyr SDK, ...) - SDK 14.1
 - Commit SHA: d84989a71827

### PR DESCRIPTION
**Pull request by edersondisouza**
Fixes that should bring a bit more stability to tests around host IPC.

Hopefully, fixes #46426

### CODE REVIEW

**Comment by edersondisouza** [comment]
v2: 
 - Also wait on the async path for marking a message as complete.

**Review by andyross — DISMISSED** [review]
Really frustrating how much fiddling is required here; 100us is a long time.  It implies that we don't really understand the contraints of the hardware behavior.   Presumably SOF gets away with this because its IPC protocol is mostly-async and doesn't try to bang things back and forth so quickly?

File: soc/xtensa/intel_adsp/common/cavs_ipc.c [hunk 1]
```diff
@@ -49,6 +49,7 @@ void z_cavs_ipc_isr(const void *devarg)
 
 		regs->tdr = CAVS_IPC_BUSY;
 		if (done && !IS_ENABLED(CONFIG_SOC_SERIES_INTEL_CAVS_V15)) {
+			k_busy_wait(100);
```
Comment (kv2019i) [inline soc/xtensa/intel_adsp/common/cavs_ipc.c:52]: I'm afraid this is way, way too long sleep. We have to run a gazillion tasks during every 1ms and IPCs can be sent at any time, so the IPC ISR simply needs to be fast.

File: soc/xtensa/intel_adsp/common/cavs_ipc.c [hunk 2]
```diff
@@ -97,6 +98,7 @@ void cavs_ipc_complete(const struct device *dev)
 {
 	const struct cavs_ipc_config *config = dev->config;
 
+	k_busy_wait(100);
```
Comment (kv2019i) [inline soc/xtensa/intel_adsp/common/cavs_ipc.c:101]: Ditto here.

**Review by kv2019i — CHANGES_REQUESTED** [review]
I'm afraid this change would make the IPC driver not fit for SOF use. We do have SOF IPC flood tests on SOF side that send IPCs at "maximum speed" and we've not hit this issue there, so there has to be some programming logic flaw between this and the SOF IPC driver.

File: soc/xtensa/intel_adsp/common/cavs_ipc.c (hunk 1 above)
Comment (kv2019i) [reply soc/xtensa/intel_adsp/common/cavs_ipc.c:52]: Looking at the differences to https://github.com/thesofproject/sof/blob/main/src/drivers/intel/cavs/ipc.c , at least masking of the BUSY irq is missing here (while the message is handled). Not likely to explain this case as the message is handled directly in the ISR, but at least one difference.

Comment (andyross) [reply soc/xtensa/intel_adsp/common/cavs_ipc.c:52]: It's possible that this is some secondary behavior related to the test that SOF doesn't do too.  Maybe it's turning around and spinning on the registers in a way that SOF doesn't, and putting the delay into the test might be sufficient?

The masking seems needless to me: this is the ISR, so the interrupt won't (can't) reentrantly fire until we return (absent the handler playing games with the interrupt level or other outrageous hacks).  And once the ISR returns, we know it's not latched anymore because we don't enter an infinite interrupt cycle.  Even if the hardware does fire one during the command contra the spec, it should look different in a way (a spurious new command) that this test should detect and fail on.  Certainly timing won't be able to fix that.

But masking is cheap, so no reason not to.

**Comment by edersondisouza** [comment]
> I'm afraid this change would make the IPC driver not fit for SOF use. We do have SOF IPC flood tests on SOF side that send IPCs at "maximum speed" and we've not hit this issue there, so there has to be some programming logic flaw between this and the SOF IPC driver.

I'm curious about how you define "maximum speed". How long does it take from the interrupt to clearing TDA?

**Comment by edersondisouza** [comment]
v3:
 - Instead of arbitrary waiting before marking some IPC as done from the DSP, acknowledge the DONE interrupt on the host side before processing IPC messages.

**Comment by edersondisouza** [comment]
@kv2019i and @andyross after a bit more digging, it seems some race was happening - can you check if my commit message - and solution - makes sense?

**Review by teburd — DISMISSED** [review]
This makes sense, looks like a nice fix. Please run against the hda and hda log tests as well, as those use IPC, if they don't work let me know

**Review by andyross — DISMISSED** [review]
Certainly I have no complaints if this works to fix the test without changes to the driver.

I'm a little confused on the theory of operation here.  In theory we should never be in a situation where both TDR (the flag that indicates an inbound command from the DSP) and IDA (the flag that indicates the DSP is done with the last command we sent) are both set, right?  The test is supposed to arrange things such that these don't overlap. 

Obviously changing the order can't be wrong, but I do worry this implies this means there's another race/misunderstanding (or just a timing issue) somewhere else in the test.

But regardless it's good to know the driver isn't broken :)

**Comment by yerabolu** [comment]
Verified the tests on cavs18 and cavs25, smoke test is passing without any issue.

**Review by dcpleung — DISMISSED** [review]

**Review by kv2019i — DISMISSED** [review]
Thanks @edersondisouza , this looks better!

**Review by nashif — CHANGES_REQUESTED** [review]
commit "tests/boards/intel_adsp/smoke: Ack local interrupt before processing IPC" is not on the test, it is soc specific, so please change the commit message.

**Comment by edersondisouza** [comment]
v4:
 - Fix commit message to properly reflect subsystem changed.

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Review by andyross — APPROVED** [review]
Refresh +1
