### PR TITLE
Accept unspecified src address if dst is broadcast

### LINKED ISSUE #45862: USB ECM/RNDIS Can't receive broadcast messages
**Describe the bug**
I can't receive udp broadcast messages when using usb ecm or usb rndis.

Board: blackpill: blackpill_f411ce

**To Reproduce**
Code used:

```
   struct sockaddr server_addr;
    memset(&server_addr, 0, sizeof(server_addr));
    net_sin(&server_addr)->sin_family = AF_INET;
    net_sin(&server_addr)->sin_port = htons(DHCP_SERVER_PORT);
    net_sin(&server_addr)->sin_addr.s_addr = htonl(INADDR_ANY);

    sock = zsock_socket(server_addr.sa_family, SOCK_DGRAM, IPPROTO_UDP);

	ret = zsock_bind(sock, &server_addr, sizeof(server_addr));
	if (ret < 0) {
		LOG_ERR("Failed to bind UDP socket: %d", errno);
		ret = -errno;
	}


```

**Expected behavior**
Broadcast packets should be received

**Impact**
Can't continue with the current feature

**Logs and console output**

I get this from the usb system:
[00:00:00.475,000] <inf> usb_ecm: len 0 req_type 0x21 req 0x43 enabled 1
[00:00:00.475,000] <inf> usb_ecm: Set Interface 0 Packet Filter 0x000c not supported
[00:00:00.525,000] <inf> usb_ecm: len 0 req_type 0x21 req 0x43 enabled 1
[00:00:00.525,000] <inf> usb_ecm: Set Interface 0 Packet Filter 0x000e not supported
[00:00:00.527,000] <inf> usb_ecm: len 0 req_type 0x21 req 0x43 enabled 1

I can see the dhcp packets being sent in wireshark

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA: Zephyr: 47850a301c419df5d01e2c5eef04ca05c48e33e1

**Additional context**
I am not sure if this is supposed to be supported and I am doing this the wrong way, missing some config option or the like. Or if the current usb system just doesn't support it.

### PR DESCRIPTION
**Pull request by Coi-l**
To be able to accept DHCP discover/request incoming packets the ip stack
neeeds to accept unspecified src addr if the destination is broadcast
address.

Signed-off-by: Olof Winge <olof@skyshaper.net>

### CODE REVIEW

**Comment by Coi-l** [comment]
Related issue: https://github.com/zephyrproject-rtos/zephyr/issues/45862

**Comment by rlubos** [comment]
So is it about DNS or DHCP? In the bug report your mention DHCP, and from the context I assume that's the case, but here DNS is mentioned.

Can you also elaborate a bit on the usecase? Zephyr only supports DHCP client at the moment, and in such case the soruce IP address shouldn't be empty - the OFFER/ACK sent by the server should containt the server IP address as a source. The scenario you describe (empty source IP sent to broadcast) is valid for packets sent by the client (DISCOVER/REQUEST), but since Zephyr does not support DHCP server functionality it's a bit unclear to me how does that affect you? Do you run some custom DHCP server implementation on top of Zephyr stack?

File: subsys/net/ip/ipv4.c [hunk 1]
```diff
@@ -278,7 +278,8 @@ enum net_verdict net_ipv4_input(struct net_pkt *pkt)
 		goto drop;
 	}
 
-	if (net_ipv4_is_addr_unspecified((struct in_addr *)hdr->src)) {
+	if (net_ipv4_is_addr_unspecified((struct in_addr *)hdr->src) &&
+		!net_ipv4_is_addr_bcast(net_pkt_iface(pkt), (struct in_addr *)hdr->dst)) {
```
Comment (rlubos) [inline subsys/net/ip/ipv4.c:282]:
```suggestion
	if (net_ipv4_is_addr_unspecified((struct in_addr *)hdr->src) &&
	    !net_ipv4_is_addr_bcast(net_pkt_iface(pkt), (struct in_addr *)hdr->dst)) {
```

**Review by rlubos — COMMENTED** [review]
Please add `net: ipv4: ` prefix to the commit title. And also clarify if you indeed meant DNS in the commit message.

**Comment by Coi-l** [comment]
> So is it about DNS or DHCP? In the bug report your mention DHCP, and from the context I assume that's the case, but here DNS is mentioned.
> 
> Can you also elaborate a bit on the usecase? Zephyr only supports DHCP client at the moment, and in such case the soruce IP address shouldn't be empty - the OFFER/ACK sent by the server should containt the server IP address as a source. The scenario you describe (empty source IP sent to broadcast) is valid for packets sent by the client (DISCOVER/REQUEST), but since Zephyr does not support DHCP server functionality it's a bit unclear to me how does that affect you? Do you run some custom DHCP server implementation on top of Zephyr stack?

This is about DHCP. I've built a DHCP server on top of Zephyr. I've also built a DNS server which is why I was messing them up in the commit message. I will adjust according to your comment.s

File: subsys/net/ip/ipv4.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/ip/ipv4.c:282]: Please fix this indentation.

**Comment by rlubos** [comment]
Just please squash the commits and were good as for me.

**Review by rlubos — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]
