### PR TITLE
drivers: serial: nrf: Fix is_pending handling

### LINKED ISSUE #7651: nRF5x console broken
The shell is currently broken on nRF5x devices.
It apparently happened with [this commit](https://github.com/zephyrproject-rtos/zephyr/pull/7431) but if I revert it I get garbage characters on the console.

CC @leodesigner

### PR DESCRIPTION
**Pull request by carlescufi**
In order to check whether an interrupt is pending for the driver user,
the driver itself needs to verify what interrupt paths are enabled (RX
and or TX) so that as not to return true misleadingly.

Fixes #7651

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
@leodesigner can you please check this fixes the issue? It does for me locally

**Comment by carlescufi** [comment]
CC @durub

**Review by anangl — APPROVED** [review]

**Comment by leodesigner** [comment]
@carlescufi Just compiled, I can confirm, now shell is functional again. Thanks.

**Comment by durub** [comment]
Good catch everyone! Sorry for not noticing it before the merge, I wasn't using the shell recently.

File: drivers/serial/uart_nrf5.c [hunk 1]
```diff
@@ -447,7 +447,12 @@ static void uart_nrf5_irq_err_disable(struct device *dev)
 /** Interrupt driven pending status function */
 static int uart_nrf5_irq_is_pending(struct device *dev)
 {
-	return (uart_nrf5_irq_tx_ready(dev) || uart_nrf5_irq_rx_ready(dev));
+	volatile struct _uart *uart = UART_STRUCT(dev);
+
+	return ((uart->INTENSET & UART_IRQ_MASK_TX) &&
```
Comment (pfalcon) [inline drivers/serial/uart_nrf5.c]: Probably has been worth to cache volatile uart->INTENSET in a local var to optimize this code a bit.

Comment (carlescufi) [reply drivers/serial/uart_nrf5.c]: Thiis has been rewritten in https://github.com/zephyrproject-rtos/zephyr/pull/7681, so might want to comment there instead
