### PR TITLE
Bluetooth: Tester: Send test data when entering streaming state 

### LINKED ISSUE #79059: BAP/USR/STR/BV-369-C test fails.
**Describe the bug**

The test BAP/USR/STR/BV-369-C fails. Looking at the traces, the ISO data being sent has payload 0, when it should instead be 40.

From my understanding, during the test procedure, PTS should send a MMI that would trigger hdl_wid_377. This would then in turn trigger the BTP_BAS_SEND callback in the tester app, which would fill up the ring buffer with the data. However, the MMI is not sent, and therefore the payload is 0. 
This lead to test failure.

Looking into the history of the test results reports:

- Test added: [week 33.7](https://lists.zephyrproject.org/g/Bluetooth-sig/message/1086?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3ACreated%2C%2Cautopts+test+session%2C20%2C2%2C160%2C100846836)
- Test regressed: [week 39.6](https://lists.zephyrproject.org/g/Bluetooth-sig/message/1133?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3ACreated%2C%2Cautopts+test+session%2C20%2C2%2C140%2C101672471)

The test has failed ever since. It was mistakenly marked to be related to the "[2nd CIS establishment issue](https://github.com/zephyrproject-rtos/zephyr/issues/60132)", but has now been corrected, as it is not affected by that issue.

**To Reproduce**

1. setup Zephyr environment and Auto PTS https://docs.zephyrproject.org/latest/connectivity/bluetooth/autopts/autopts-win10.html#setup-zephyr-project-for-windows
2. Build the auto pts tester app
3. Program the board
4. start the auto PTS server
5. Run the test case BAP/USR/STR/BV-369-C

**Expected behavior**

IUT starts CIS stream, PTS verifies its its content and test passes.

**Impact**

Zephyr Host conformance test fails. 

**Logs and console output**

PTS logs : [HERE](https://github.com/zephyrproject-rtos/bluetooth-qualification/tree/main/leaudio/autopts_report/pts_logs/BAP_USR_STR_BV_369_C_2024_10_13_05_40_33)
(EDIT: updated to latest Zephyr qualification run)

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used

**Additional context**

Toolchain Zephyr SDK
Zephyr Main - OS: Windows 10 
Commit SHA: eb98483769b5418969e25c87b2746cd5f05cc4cf

### PR DESCRIPTION
**Pull request by sjanc**
For now this seems to be required by PTS as there is not Upper Tester
action for this in Test Specification.

This is affecting few BAP/USR/STR qualifications tests

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/79059

### CODE REVIEW

**Comment by sjanc** [comment]
Fix https://github.com/zephyrproject-rtos/zephyr/issues/79059

**Comment by sjanc** [comment]
BAP/USR/STR/BV-365-C is stil failing, not sure yet why, other seem to pass

**Comment by Thalley** [comment]
> BAP/USR/STR/BV-365-C is stil failing, not sure yet why, other seem to pass

Maybe it's unhappy that the data length is not equal to the SDU size?

**Review by fredrikdanebjer — DISMISSED** [review]
Got a nice walkthrough from @MicImbriani.

Has BT-Sig been alerted on the tester not sending the test-cmd?

Im fine otherwise

File: tests/bluetooth/tester/src/audio/btp_bap_unicast.c [hunk 1]
```diff
@@ -626,6 +626,7 @@ static void stream_started(struct bt_bap_stream *stream)
 {
 	struct btp_bap_unicast_stream *u_stream = stream_bap_to_unicast(stream);
 	struct bt_bap_ep_info info;
+	const uint8_t test_data[5] = { 0x01, 0x02, 0x03, 0x04, 0x05 };
```
Comment (Thalley) [inline tests/bluetooth/tester/src/audio/btp_bap_unicast.c:629]: Since we configure the SDU size as a product if Octets_Per_Codec_Frame, Audio_Channel_Allocation and Codec_Frame_Blocks_Per_SDU, I think the size of the test data we send should present that. 

Sending e.g. 5 octets when we've configured the SDU size to be e.g. 40 is invalid behavior, which we arguably should not do. (Ideally the data would also be LC3 encoded, but I don't know if PTS cares about that).

**Review by Thalley — CHANGES_REQUESTED** [review]

File: tests/bluetooth/tester/src/audio/btp_bap_unicast.c (hunk 1 above)
Comment (MicImbriani) [reply tests/bluetooth/tester/src/audio/btp_bap_unicast.c:629]: I can see your reasoning, however the test specification does not require this. In fact, in some tests (BAP/USR/STR/BV-369-C) it even specifies that Null PDUs can be valid: "The IUT transmits CIS Data PDUs or CIS Null PDUs"

Comment (Thalley) [reply tests/bluetooth/tester/src/audio/btp_bap_unicast.c]: What the test specs expect/demand may not always be what PTS expects/demands :D I think there was a test case that failed due to not sending the right amount of octets which is of course sort of a PTS bug, but in some cases it's just easier (or at least faster) to make PTS happy than to wait for a PTS fix, especially since BAP requires this (even if the test spec does not specifically mention it).

**Comment by sjanc** [comment]
All BAP/USR/STR are passing now

**Review by Thalley — APPROVED** [review]

**Comment by sjanc** [comment]
Fixed MESH DFU->DFUM and MBT->MBTM,  no other changes
Apparently export is not yet fixed in Qualification Workspace

File: tests/bluetooth/tester/src/audio/btp_bap_unicast.c (hunk 1 above)
Comment (sjanc) [reply tests/bluetooth/tester/src/audio/btp_bap_unicast.c]: yeap, better to be compliant even if PTS is not validating it in all cases

**Review by niym-ot — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
