### PR TITLE
drivers: sensor: fcx_mldx5: Fix potential buffer overflow in UART frame

### LINKED ISSUE #92634: [Coverity CID: 363738] Copy into fixed size buffer in drivers/sensor/fcx_mldx5/fcx_mldx5.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/fd6b05c81b86a1ffe465d56ded7b73a9fdb7f14b/drivers/sensor/fcx_mldx5/fcx_mldx5.c

Category: Security best practices violations
Function: `fcx_mldx5_uart_send`
Component: Drivers
CID: [363738](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=363738)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/fd6b05c81b86a1ffe465d56ded7b73a9fdb7f14b/drivers/sensor/fcx_mldx5/fcx_mldx5.c#L239

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=363738

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_STRING_OVERFLOW). ([CWE-120](http://cwe.mitre.org/data/definitions/120.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

Also see the related [Coverity documentation](https://docs.zephyrproject.org/latest/contribute/guidelines.html#static-code-analysis) for more information.

### PR DESCRIPTION
**Pull request by sudarsan-22**
Fix Coverity issue CID 363738 (CWE-120): A potential buffer overflow could occur in fcx_mldx5_uart_send() due to unchecked memcpy() when copying command data into a fixed-size frame buffer.

This patch ensures that the length of the data being copied validated against the remaining buffer size to prevent overruns. Also replaces a redundant strlen() call with the precomputed cmd_data_len.

Fixes: #92634

### CODE REVIEW

File: drivers/sensor/fcx_mldx5/fcx_mldx5.c [hunk 1]
```diff
@@ -235,8 +235,14 @@ static void fcx_mldx5_uart_send(const struct device *dev, enum fcx_mldx5_cmd cmd
 
 	buf[FCX_MLDX5_STX_INDEX] = FCX_MLDX5_STX;
 	memcpy(&buf[FCX_MLDX5_CMD_INDEX], fcx_mldx5_cmds[cmd], FCX_MLDX5_CMD_LEN);
+
 	if (cmd_data_len != 0 && cmd_data_len == fcx_mldx5_cmds_data_len[cmd]) {
-		memcpy(&buf[FCX_MLDX5_DATA_INDEX], cmd_data, strlen(cmd_data));
+		if ((FCX_MLDX5_DATA_INDEX + cmd_data_len) <= FCX_MLDX5_MAX_FRAME_LEN) {
```
Comment (jeppenodgaard) [inline drivers/sensor/fcx_mldx5/fcx_mldx5.c:240]: `&& cmd_data_len == fcx_mldx5_cmds_data_len[cmd]` in the line above was an attempt to make Coverity stop complaining.

Since the largest value in that array is `5` (for now) that check should also prevent overflow.

I think this PR's length check is easier to understand and also future proof.
One length check should suffice so please remove the previous check.

**Review by jeppenodgaard — CHANGES_REQUESTED** [review]
This is the 3rd attempt to fix this Coverity issue:
 - https://github.com/zephyrproject-rtos/zephyr/pull/81178
 - https://github.com/zephyrproject-rtos/zephyr/pull/82447

This is the original issue: 
- https://github.com/zephyrproject-rtos/zephyr/issues/74761.

In theory overflow can happen if a future PR adds a command with too much data, so checking the length can make sense.

File: drivers/sensor/fcx_mldx5/fcx_mldx5.c (hunk 1 above)
Comment (sudarsan-22) [reply drivers/sensor/fcx_mldx5/fcx_mldx5.c:240]: Thanks for the feedback! I’ve removed the redundant check as suggested. The updated logic should be clearer and future-proof now. Let me know if anything else needs adjustment.

**Review by jeppenodgaard — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by JarmouniA — COMMENTED** [review]
@kartben @jeppenodgaard @MaureenHelm PR should be reverted, author Signed-off-by is missing complete last name
https://docs.zephyrproject.org/latest/contribute/guidelines.html#dco-sign-off

**Comment by kartben** [comment]
> @kartben @jeppenodgaard @MaureenHelm PR should be reverted, author Signed-off-by is missing complete last name
> https://docs.zephyrproject.org/latest/contribute/guidelines.html#dco-sign-off 

It is my understanding that it's a common practice in some regions in India that the full name is only single letter(s) so I don't really see an issue here. Don't forget that Zephyr is a global community :)

**Comment by sudarsan-22** [comment]
> > @kartben @jeppenodgaard @MaureenHelm PR should be reverted, author Signed-off-by is missing complete last name
> > https://docs.zephyrproject.org/latest/contribute/guidelines.html#dco-sign-off
> 
> It is my understanding that it's a common practice in some regions in India that the full name is only single letter(s) so I don't really see an issue here. Don't forget that Zephyr is a global community :)

Thank you for pointing @kartben @JarmouniA .
I'd like to clarify that "Sudarsan N" is my full legal name as per my government-issued documents.
It is a common naming convention in my region (India) to use an initial for the family

**Comment by JarmouniA** [comment]
> > > @kartben @jeppenodgaard @MaureenHelm PR should be reverted, author Signed-off-by is missing complete last name
> > > https://docs.zephyrproject.org/latest/contribute/guidelines.html#dco-sign-off
> > 
> > 
> > It is my understanding that it's a common practice in some regions in India that the full name is only single letter(s) so I don't really see an issue here. Don't forget that Zephyr is a global community :)
> 
> Thank you for pointing @kartben @JarmouniA . I'd like to clarify that "Sudarsan N" is my full legal name as per my government-issued documents. It is a common naming convention in my region (India) to use an initial for the family

Okey my mistake then, sorry for the noise.
