### PR TITLE
net: sockets: Fix SO_SNDTIMEO and SO_RCVBUF options

### LINKED ISSUE #55641: Socket Timeout Ignored
**Describe the bug**
Socket timeouts are ignored. BSD-socket timeouts are supported via `setsockopt` but the send timeout is ignored. Thus the application of an unknowing developer might hammer the socket with `send`-calls in a busy loop.

From a discussion with @rlubos in the discord it came out, that the likely reason might be https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/sockets/sockets.c#L672 . `send_check_and_wait` is supposed to wait for the timeout but immediately returns:
```
if (!K_TIMEOUT_EQ(timeout, K_FOREVER)) {
	goto out;
}
```
Instead the author might have intended:
```
if (K_TIMEOUT_EQ(timeout, K_NO_WAIT)) {
	goto out;
}
```

Additionally it would be nice to have a regression test for this.

This is likely linked to other issues related to socket send. For example civetweb's need for polling on the sockets.

### PR DESCRIPTION
**Pull request by rlubos**
SO_SNDTIMEO socket option did not configure TX timeout on a socket properly. When testing the fix, it turned out that also SO_SNDBUF/SO_RCVBUF socket options were broken, not modifying the unerlying TCP window sizes properly.

This PR fixes the above issues. First two commits address the problem with SO_RCVBUF and adds new tests that verify that TCP windows are affected properly when changing SO_RCVBUF/SO_SNDBUF. 

The remaining commits, fix the TX timeouts on a socket, if configured, and add tests that verify this functinoality.

Fixes #55641

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]
LGTM

File: subsys/net/ip/tcp.c [hunk 1]
```diff
@@ -2017,6 +2020,42 @@ static void tcp_out_of_order_data(struct tcp *conn, struct net_pkt *pkt,
...
+			conn->send_win = conn->send_win_max;
+		}
+
+		k_mutex_unlock(&conn->lock);
+	}
+
+	if (rcvbuf_opt > 0 && rcvbuf_opt != conn->recv_win_max) {
+		k_mutex_lock(&conn->lock, K_FOREVER);
+
+		conn->recv_win_max = rcvbuf_opt;
```
Comment (ssharks) [inline subsys/net/ip/tcp.c:2052]: I think this line has to be swapped with the line below, otherwise below (rcvbuf_opt - conn->recv_win_max), will always be 0.

File: subsys/net/ip/tcp.c [hunk 2]
```diff
@@ -748,8 +758,10 @@ static int tcp_update_recv_wnd(struct tcp *conn, int32_t delta)
 	bool short_win_after;
 
 	new_win = conn->recv_win + delta;
-	if (new_win < 0 || new_win > UINT16_MAX) {
```
Comment (ssharks) [inline subsys/net/ip/tcp.c:751]: Did you deliberately allowed the new_win below 0, did you experience an occurance of this? Did you thought of how to handle the fact that new_win can have a value bigger then UINT16_MAX, but the implementation does no window scaling, so has no means to notify the other end of the connection about this?

**Review by ssharks — COMMENTED** [review]
Looks like nice improvements, the issue you are addressing can explain some observations I did when playing with window sizes.
Nice work, please have a look at the listed review comments

File: subsys/net/ip/tcp.c (hunk 2 above)
Comment (rlubos) [reply subsys/net/ip/tcp.c:751]: > Did you deliberately allowed the new_win below 0, did you experience an occurance of this?

This is to cover the scenario when the application shrinks the max window when some communication is already ongoing. In this case, the new current new window size could fall below 0.
At the same time, if the application updates the window after consuming the data, immediately after shrinking the new window size could exceed the max window, hence extra check.

> Did you thought of how to handle the fact that new_win can have a value bigger then UINT16_MAX, but the implementation does no window scaling, so has no means to notify the other end of the connection about this?

Not sure I follow. `new_win` could not exceed UINT16_MAX, as `recv_win_max` is `uint16_t`, and we make sure not to exceed it just below.

File: subsys/net/ip/tcp.c (hunk 1 above)
Comment (rlubos) [reply subsys/net/ip/tcp.c:2052]: Good point, I've made some last minute changes and missed the fact it make no sense now. The current window was limited to `recv_win_max` anyway inside  `tcp_update_recv_wnd()` so the new test did not catch it. I'll restore the previous behaviour (calculate diff before updating `recv_win_max`.

File: subsys/net/ip/tcp.c (hunk 2 above)
Comment (ssharks) [reply subsys/net/ip/tcp.c:751]: > > Did you thought of how to handle the fact that new_win can have a value bigger then UINT16_MAX, but the implementation does no window scaling, so has no means to notify the other end of the connection about this?
> 
> Not sure I follow. `new_win` could not exceed UINT16_MAX, as `recv_win_max` is `uint16_t`, and we make sure not to exceed it just below.

The function tcp_update_recv_wnd is fed with an int32_t as well as the value new_win is. In current situation this could lead to an unexpected overflow when writing new_win to conn->recv_win. It might be worth looking at the origin code of this section

Comment (rlubos) [reply subsys/net/ip/tcp.c:751]: I may be missing something, but aren't the current checks enough to guarantee that `new_win` ends up within the `uint16_t` range?

Comment (ssharks) [reply subsys/net/ip/tcp.c:751]: You are right as recv_win_max is uint16_t this will be the limiting factor indeed, I did not spot this.

**Review by ssharks — APPROVED** [review]

**Review by jukkar — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
