### PR TITLE
drivers: pwm: pwm_stm32.c: enable ARR preload

### LINKED ISSUE #29446: pwm: stm32: output signal delayed
**Describe the bug**
I encountered this bug by using PWM (timer 3, channel 3) on a STM32F070 MCU. With the default prescaler configuration (10000), and when the PWM is configured to output a signal with a rather big period (around 100ms for example), then sometimes nothing happens... But after a delay (around 10 seconds), then the PWM signal is finally outputted correctly

**To Reproduce**

The following code should allow to reproduce the issue:
```
pwm_pin_set_usec(dev, pwm, 1000000, 500000, flags);
k_sleep(K_MSEC(5000));
pwm_pin_set_usec(dev, pwm, 100000, 50000, flags);
```

You should observe that the first PWM configuration is applied correctly. But the second one is delayed (of around 10 seconds). During that time no PWM signal is outputted on pin. The previous PWM period/pulse is not active anymore. And after the delay, the second PWM signal is finally outputted correctly.

**Expected behavior**
The PWM configuration should be applied without any delay.

**Impact**
Among other things this bug affects the driving of PWM LEDs. Sometimes the LED blinking effects are delayed. 

**Additional context**
It seems that decreasing the prescaler works around the issue. With a prescaler value set to 1000, I can't reproduce it anymore.

### PR DESCRIPTION
**Pull request by ABOSTM**
drivers: pwm: pwm_stm32.c: enable ARR preload

Enable ARR preload so that period or pulse updates are taken
into account synchronously with update event
(at the end of a ongoing period)
And thus avoid undetermined intermediate pulse.

Fixes #29446

Tested on Nucleo_f401re

### CODE REVIEW

**Comment by gmarull** [comment]
Seems like a duplicate of #29470 (or at least related)

**Review by gmarull — APPROVED** [review]
LGTM, this makes updates strictly synchronous to the update event.

As there was an already open PR trying to address the same observed issue, I think it would have been better to discuss the synchronous solution there to avoid 2 parallel PRs.

File: drivers/pwm/pwm_stm32.c [hunk 1]
```diff
@@ -228,13 +228,17 @@ static int pwm_stm32_pin_set(const struct device *dev, uint32_t pwm,
...
 		}
 
+		LL_TIM_EnableARRPreload(cfg->timer);
 		LL_TIM_OC_EnablePreload(cfg->timer, channel);
+		LL_TIM_SetAutoReload(cfg->timer, period_cycles - 1u);
+		LL_TIM_GenerateEvent_UPDATE(cfg->timer);
 	} else {
 		LL_TIM_OC_SetPolarity(cfg->timer, channel, get_polarity(flags));
 		set_timer_compare[pwm - 1u](cfg->timer, pulse_cycles);
+		LL_TIM_SetAutoReload(cfg->timer, period_cycles - 1u);
```
Comment (gmarull) [inline drivers/pwm/pwm_stm32.c:238]: Could it happen that written ARR is lower than the written pulse cycles in the previous line? Probably a marginal case, but I think it is still a possibility.

**Comment by simonguinot** [comment]
I confirm I can't reproduce the #29446 bug with this patch. Thanks.

**Review by simonguinot — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]
Looks good.

**Comment by ABOSTM** [comment]
> As there was an already open PR trying to address the same observed issue, I think it would have been better to discuss the synchronous solution there to avoid 2 parallel PRs.

Yes, but to start the discussion, I wanted to shared my proposal so I needed to open a new PR.
