### PR TITLE
boards: arm: Fix conditionalized pinmuxes for shared pin

### LINKED ISSUE #27473: RT1050/60/64-evk board user LED does not work
A recent change (572f440) added a condition that CONFIG_NET_L2_ETHERNET be true to initialize a set of GPIO port pins. One of the port pins is a shared pin between ENET and 'user LED' so without Ethernet being configured the user LED cannot be used.

### PR DESCRIPTION
**Pull request by dleach02**
A change was put in to conditionalize pinmuxes based on
Ethernet configuration but for the IMXRT1050/60/64-EVK
boards the USER_LED and ENET_RST share the same GPIO.
Samples like blinky would not work on these boards.

The change is to not conditionalize the shared pin.

fixes: #27473

Signed-off-by: David Leach <david.leach@nxp.com>

### CODE REVIEW

**Review by galak — APPROVED** [review]

File: boards/arm/mimxrt1050_evk/pinmux.c [hunk 1]
```diff
@@ -211,8 +211,10 @@ static int mimxrt1050_evk_init(struct device *dev)
 			    IOMUXC_SW_PAD_CTL_PAD_DSE(6));
 #endif
 
-#if DT_NODE_HAS_STATUS(DT_NODELABEL(enet), okay) && CONFIG_NET_L2_ETHERNET
+	/* Shared GPIO between USER_LED and ENET_RST */
 	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_09_GPIO1_IO09, 0U);
```
Comment (MaureenHelm) [inline boards/arm/mimxrt1050_evk/pinmux.c:215]: Need to fix the other reference to this pin in lines 121-132

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

**Comment by dleach02** [comment]
@MaureenHelm, are you okay with the way I changed this?

**Review by MaureenHelm — APPROVED** [review]
