### PR TITLE
Benchmark cleanup and new and generic timing API

### LINKED ISSUE #25458: Multiple issues with timing benchmark
**Describe the bug**

- New HW and timers are not supported resulting in wrong and bogus data
- Some features were dropped but we still have those listed as being benchmarked
- Need a general overhaul and cleanup after various kernel and device handling changes, i.e. new timeout APIs, 64bit support, SMP, etc.
- Need to enhance abstraction of architectures and timers

**To Reproduce**

Run timing_info on qemu_x86 and qemu_x86_64 and observe results.

**Expected behavior**
Consistant reporting  and easier pluggability of new hardware and features to be benchmarked

### PR DESCRIPTION
**Pull request by nashif**
Cleanup benchmark and remove code duplication for acquiring timestamps from different source. Make the timing functions generally available and overridable by SoC or boards. The APIs should serve other time sensitive features such as per thread accounting and tracing.

Remove EXECUTION_BENCHMARKING option which was dedicated for single test and polluted all arch and kernel code measuring data points that do not reflect reality. 
For low lever time measurements and tracing we will be using the tracing feature which happens to hit exactly the same spots.

This cleans up the code considerable.

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]

File: arch/arm/core/aarch32/timing.c [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+}
+
+uint64_t __weak timing_cycles_to_ns(uint64_t cycles)
+{
+	return (uint32_t)k_cyc_to_ns_floor64(cycles);
+}
+
+uint64_t __weak timing_cycles_to_ns_avg(uint64_t cycles, uint32_t count)
+{
+	return (uint32_t)timing_cycles_to_ns(cycles) / count;
```
Comment (andrewboie) [inline arch/arm/core/aarch32/timing.c:48]: would it make more sense to up-cast count to `uint64_t` here?

File: arch/arm/core/aarch32/timing.c [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+
+uint64_t __weak timing_freq_get(void)
+{
+	return sys_clock_hw_cycles_per_sec();
+}
+
+uint64_t __weak timing_cycles_to_ns(uint64_t cycles)
+{
+	return (uint32_t)k_cyc_to_ns_floor64(cycles);
```
Comment (andrewboie) [inline arch/arm/core/aarch32/timing.c:43]: why `uint32_t` cast?

File: arch/common/timing.c [hunk 3]
```diff
@@ -0,0 +1,53 @@
+/*
+ * Copyright (c) 2020 Intel Corporation.
```
Comment (andrewboie) [inline arch/common/timing.c:2]: Getting deja vu reading this code.
Then I realized we already have it in arch/arm.
Wouldn't it be better to just keep this file, and implemnnent any differences in the arch layer?

File: arch/nios2/core/timing.c [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+	  (IORD_ALTERA_AVALON_TIMER_PERIODL(TIMER_0_BASE))) -                  \
+	 ((uint32_t)val))
+
+#define TIMING_INFO_OS_GET_TIME()                                              \
+	(NIOS2_SUBTRACT_CLOCK_CYCLES(                                          \
+		((uint32_t)IORD_ALTERA_AVALON_TIMER_SNAPH(TIMER_0_BASE)        \
+		 << 16) |                                                      \
+		((uint32_t)IORD_ALTERA_AVALON_TIMER_SNAPL(TIMER_0_BASE))))
+
+void __weak timing_init(void)
```
Comment (andrewboie) [inline arch/nios2/core/timing.c:23]: what's the use-case for overriding these at the arch instead of common level?

File: arch/x86/core/ia32/intstub.S [hunk 5]
```diff
@@ -80,13 +84,13 @@ SECTION_FUNC(TEXT, _interrupt_enter)
...
-	pushl %edx
-	rdtsc
-	mov %eax, arch_timing_irq_start
-	mov %edx, arch_timing_irq_start+4
-	pop %edx
-	pop %eax
+	push	%eax
+	push	%edx
+
+	call	read_timer_start_of_isr
```
Comment (andrewboie) [inline arch/x86/core/ia32/intstub.S:90]: this is wrong, you have to push ALL caller-saved registers if you are calling into C code since we are at the beginning of the ISR code where nothing has been preserved yet.
the old code pushed only eax/edx because of how 'rdtsc' works.

File: arch/x86/core/ia32/swap.S [hunk 6]
```diff
@@ -65,27 +69,15 @@
...
-	* once done pop the values.
-	*/
-	push %eax
-	push %edx
-	rdtsc
-	mov %eax,arch_timing_swap_start
-	mov %edx,arch_timing_swap_start+4
-	pop %edx
-	pop %eax
+	push	%eax
```
Comment (andrewboie) [inline arch/x86/core/ia32/swap.S:74]: I know the old code was being used as a template, but it was written by someone who wasn't the sharpest tool in the shed.

the 32-bit SYS V ABI passes in arguments via the stack, so unless I'm missing something you don't need to preserve either eax or edx as neither of these caller-saved registers are used here

File: arch/x86/core/ia32/userspace.S [hunk 7]
```diff
@@ -375,16 +379,13 @@ SECTION_FUNC(TEXT, z_x86_userspace_enter)
...
-	* once done pop the values.
-	*/
-	push %eax
-	push %edx
-	rdtsc
-	mov %eax,arch_timing_enter_user_mode_end
-	mov %edx,arch_timing_enter_user_mode_end+4
-	pop %edx
-	pop %eax
+	push	%eax
```
Comment (andrewboie) [inline arch/x86/core/ia32/userspace.S:382]: i don't think these registers need to be preserved since right after this we just `iret`

File: arch/x86/core/intel64/locore.S [hunk 8]
```diff
@@ -288,7 +286,13 @@ mxcsr:	.long X86_MXCSR_SANE
 .globl z_x86_switch
 z_x86_switch:
 #ifdef CONFIG_EXECUTION_BENCHMARKING
-	read_tsc arch_timing_swap_start
+	push	%rax
```
Comment (andrewboie) [inline arch/x86/core/intel64/locore.S:289]: these regs are not in use

File: arch/x86/core/intel64/userspace.S [hunk 9]
```diff
@@ -326,16 +331,13 @@ z_x86_userspace_enter:
...
-	* once done pop the values.
-	*/
-	push %rax
-	push %rdx
-	rdtsc
-	mov %eax,arch_timing_enter_user_mode_end
-	mov %edx,arch_timing_enter_user_mode_end+4
-	pop %rdx
-	pop %rax
+	push	%rax
```
Comment (andrewboie) [inline arch/x86/core/intel64/userspace.S:334]: I don't think RAX needs preservation, note the 'movq' right below this.
RDX needs to be saved, it has the 'p2' argument

File: arch/x86/core/intel64/locore.S [hunk 10]
```diff
@@ -593,7 +597,13 @@ EXCEPT(Z_X86_OOPS_VECTOR);
 
 irq:
 #ifdef CONFIG_EXECUTION_BENCHMARKING
-	read_tsc arch_timing_irq_start
+	push	%rax
```
Comment (andrewboie) [inline arch/x86/core/intel64/locore.S:600]: All caller-saved regs must be saved before you call into C code here

File: arch/x86/timing.c [hunk 11]
```diff
@@ -0,0 +1,85 @@
...
+#include <timing/timing.h>
+
+static uint64_t tsc_freq;
+
+void timing_x86_init(void)
+{
+	uint32_t cyc_start = k_cycle_get_32();
+	uint64_t tsc_start = z_tsc_read();
+
+	k_busy_wait(10 * USEC_PER_MSEC);
```
Comment (andrewboie) [inline arch/x86/timing.c:19]: seems a fairly short timing loop, does this produce stable/accurate values on, say, and upsquared?

**Review by tyrantlizard77 — COMMENTED** [review]
the asm code for x86 has the odor of copypasta and needs more detailed attention for each and every place an instrumentation point occurs

**Comment by andrewboie** [comment]
Please, at least when testing this, hack qemu_x86 and qemu_x86_64 or create new targets to globally enable these instrumentation points to help catch issues with the assembly code changes

**Comment by dcpleung** [comment]
The `timing_info` benchmark is using these functions so code is actually being used.

File: arch/common/timing.c (hunk 3 above)
Comment (dcpleung) [reply arch/common/timing.c:2]: The idea is that this file is for architectures and SoCs without high resolution timers. So just get the values from the default timer driver. Arch code can override this, as in ARM (SysTick) and x86 (TSC). SoC code can also override these for their specific timers, e.g. NRF and MEC1501. This layering is a bit tricky. I am not sure if `__weak` alone can support this.

File: arch/x86/timing.c (hunk 11 above)
Comment (dcpleung) [reply arch/x86/timing.c:19]: Seems stable to me. The differences between different runs are in the kHz level.

**Review by dcpleung — COMMENTED** [review]
About the x86 assembly, they were being tesed with the benchmark apps. The push/pop pairs were added until the apps ran without crashing (e.g. push/pop of `rcx` in only one place but not others). We can add the other registers in there for sake of completion, if you insist.

**Review by tyrantlizard77 — DISMISSED** [review]
>  tesed with the benchmark apps. The push/pop pairs were added until the apps ran without crashing

All this says is you were getting lucky with the particular benchmark apps tested, or what the registers the compiler decided to use in the current implementation of the C functions and optimization level.

> We can add the other registers in there for sake of completion, if you insist.

You have to consider the register environment of each call site when you are calling C out of assembly code.
At interrupt entry, nothing has been saved. The registers are just whatever was present for the interrupted process. The ABI specifies that when you call into C code, the caller-saved registers are considered volatile and will be discarded, and it is fair game for the C code to do what it likes with them. This will corrupt the interrupted process.

Some CPUs will save register banks when taking interrupts or exceptions, but on x86 this doesn't happen. As these instrumentation points are added to the ASM code in other arches, it's critical to understand both the calling convention ABI and what the CPU does and does not do for you. x86 doesn't save anything in HW which is why the IRQ and exception entry and exit code is like it is.

This wiki page refers to these as "scratch" registers, "volatile" and "caller-saved" are synonyms.
https://wiki.osdev.org/System_V_ABI
https://en.wikipedia.org/wiki/X86_calling_conventions#Caller-saved_(volatile)_registers
https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI

Now in other spots in the ASM code, these caller-saved registers may be currently unused at the time the C code is called, in which case pushing/popping them is unnecessary overhead.

This instrumentation framework has to work for general-purpose applications. We must be rigorous about register state. I'm not being pedantic "for the sake of completion" here we really must do this.

File: arch/nios2/core/timing.c (hunk 4 above)
Comment (nashif) [reply arch/nios2/core/timing.c:23]: an architecture can either use the default and not provide its own or implement its own timing functions in a way that can be overridden by an SoC or a board or an application.

**Comment by nashif** [comment]
ok, was planning to get rid of the EXECUTION_BENCHMARKING mess in a later PR but I guess we can do it here and avoid having to change the code that will be dropped later anyways. Rationale for removing this:

```
    This code had one purpose only, feed timing information into a test and
    was not used by anything else. The custom trace points unfortunatly were
    not accurate and this test was delivering informatin that conflicted
    with other tests we have due to placement of such trace points in the
    architecture and kernel code.

    For such measurements we are planning to use the tracing functionality
    in a special mode that would be used for metrics without polluting the
    architecture and kernel code with additional tracing and timing code.

    Furthermore, much of the assembly code used had issues
```

We are now using latency_measure as a one stop test for measuring the metrics and remove the duplication and confusing and conflicting results both testing were providing.

File: arch/common/timing.c (hunk 3 above)
Comment (abrodkin) [reply arch/common/timing.c:2]: I might be nitpicking as on ARC default Timers (either ARC Timer0/1 or GFRC in SMP system) is synchronized with CPU clock which makes those timers pretty high-resolution (as least for measurements sake as we don't care about latency of 0.5 a cycle I guess). Or is there any benefit of having architecture- or SoC-specific implementation of these functions other than higher precision of the timer being used?

**Review by abrodkin — COMMENTED** [review]
That's a good one especially considering my earlier attempt to improve on one separate architecture here https://github.com/zephyrproject-rtos/zephyr/pull/18751.

Though what's now missing here (after removal of `timing_info`) is IRQ latency measurement which I guess hard to do in a completely generic manner. I mean this one:
```
2. Interrupt latency	
   Time taken from the start of the common interrupt handler till the actual ISR handler being called.
```
And back in the day we had a lengthly discussion on how to do it right and how important that might be.
Maybe @ruuddw has something to add on that as well?

**Comment by ruuddw** [comment]
Getting rid of EXECUTION_BENCHMARKING cleans up indeed.I don't think tracing covers all benchmark points yet, and not sure it will have the same (low) overhead. But for minimal overhead arch specific instrumentation and tricks would be needed: can be done ad-hoc for the use-cases where required (I expect mostly during development/optimization work). For other use-cases the tracing approach seem fine to me (e.g. performance regression testing).

**Review by ruuddw — APPROVED** [review]

**Review by scottwcpg — APPROVED** [review]
MCHP SoC hi-res. timer code looks OK.  NOTE: The basic timer will lose its clock in deep sleep. Users of the API should be aware it can't be used across deep sleep.

**Review by abrodkin — APPROVED** [review]

File: soc/arm/nordic_nrf/timing.c [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+#include <arch/arm/aarch32/arch.h>
+#include <kernel.h>
+#include <sys_clock.h>
+#include <timing/timing.h>
+#include <nrfx.h>
+
+#if defined(CONFIG_NRF_RTC_TIMER)
+
+
+#define CYCLES_PER_SEC (16000000 / (1 << NRF_TIMER2->PRESCALER))
```
Comment (ioannisg) [inline soc/arm/nordic_nrf/timing.c:16]: I think it's good to have a build-time assert here, since it is possible in the future to have nRF SoCs without a 3rd timer instance (TIMER2)

File: soc/arm/nordic_nrf/CMakeLists.txt [hunk 13]
```diff
@@ -6,3 +6,5 @@ zephyr_sources(
   validate_base_addresses.c
   validate_enabled_instances.c
   )
+
+zephyr_library_sources_ifdef(CONFIG_TIMING_FUNCTIONS timing.c)
```
[the remark this answers is not in the document]
Comment (nashif) [reply soc/arm/nordic_nrf/CMakeLists.txt:10]: right now this is a catchall for all nrf, if some SoCs have a different source, they will need to provide own implementation.

File: soc/arm/nordic_nrf/timing.c (hunk 12 above)
Comment (nashif) [reply soc/arm/nordic_nrf/timing.c:16]: right, that why the ifdef above, but for other time sources we will have other implementation of those functions.

File: soc/arm/nordic_nrf/timing.c [hunk 14]
```diff
@@ -0,0 +1,68 @@
...
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+#include <arch/arm/aarch32/arch.h>
+#include <kernel.h>
+#include <sys_clock.h>
+#include <timing/timing.h>
+#include <nrfx.h>
+
+#if defined(CONFIG_NRF_RTC_TIMER)
```
[the remark this answers is not in the document]
Comment (nashif) [reply soc/arm/nordic_nrf/timing.c:13]: in case you have some other timer, given that this file covers everything under nordic_nrf.. If this is not going to be the case, it can be removed.

File: soc/arm/nordic_nrf/CMakeLists.txt (hunk 13 above)
[the remark this answers is not in the document]
Comment (ioannisg) [reply soc/arm/nordic_nrf/CMakeLists.txt:10]: As I mentioned, Cortex-M SoCs (including some nRF) have DWT which could be used for calculations. So we would end up with two timing.c source files; we need to be able to select one of them. So this is OK for now, but might need to change.

File: arch/nios2/core/timing.c (hunk 4 above)
Comment (andrewboie) [reply arch/nios2/core/timing.c:23]: I think I see. I'm not sure if `__weak` is the best way to approach this as it's not completely clear to me if this will work with multiple layers of overrides. We might have to use a vtable or something instead even though it's a bit of extra overhead if we want it to be completely flexible.

File: arch/x86/core/ia32/swap.S [hunk 15]
```diff
@@ -65,30 +65,7 @@
...
-	rdtsc
-	mov %eax,arch_timing_swap_start
-	mov %edx,arch_timing_swap_start+4
-	pop %edx
-	pop %eax
-#endif
-
-
 #if defined(CONFIG_TRACING)
 	pushl	%eax
```
Comment (andrewboie) [inline arch/x86/core/ia32/swap.S:70]: I think the push/pop of EAX can be dropped here, sys_trace_thread_switched_out takes no arguments and we're not using it in this ASM code at the time it is called.

**Review by tyrantlizard77 — COMMENTED** [review]
Looking much better, thanks!

Noted one spot where I think we're pushing/popping EAX unnecessarily.

Not loving the use of `__weak` for multiple levels of overrides of timing functions. The one that gets used is (IIRC) the last one that the linker finds, which may or may not follow a kernel -> arch -> soc -> board hierarchy unless the makefiles are set up just right. This might be something where we could get bitten unless we're very careful. Is there another way?

**Comment by ioannisg** [comment]
I get this on nRF51, which does not seem right:

```
*** Booting Zephyr OS build zephyr-v2.3.0-2343-g2eb1c191cdba  ***
START - Time Measurement
Timing results: Clock frequency: 16 MHz
Average thread context switch using yield                   : 2148553 cycles , 134284608 ns
Average context switch time between threads (coop)          :       0 cycles ,       14 ns
Switch from ISR back to interrupted thread                  :     612 cycles ,    38250 ns
Time from ISR to executing a different thread               :     525 cycles ,    32812 ns
Time to create a thread (without start)                     :     287 cycles ,    17937 ns
Time to start a thread                                      :     445 cycles ,    27812 ns
Time to suspend a thread                                    :     508 cycles ,    31750 ns
Time to resume a thread                                     :     538 cycles ,    33625 ns
Time to abort a thread (not running)                        :     403 cycles ,    25187 ns
Average semaphore signal time                               : 4294945 cycles , 268434109 ns
Average semaphore test time                                 :       6 cycles ,      408 ns
Semaphore take time (context switch)                        :     589 cycles ,    36812 ns
Semaphore give time (context switch)                        :     690 cycles ,    43125 ns
Average time to lock a mutex                                :      36 cycles ,     2282 ns
Average time to unlock a mutex                              :      29 cycles ,     1843 ns
===================================================================
PROJECT EXECUTION SUCCESSFUL

```

@nashif @dcpleung if you have this board could you investigate?

**Review by ioannisg — CHANGES_REQUESTED** [review]
@nashif I see two issues with the code here:
1. the nRF timing.c does not work as-is for nRF51 because the nrF51 TIMER2 does not have a full-range bit-mode (only 8-bit and 16-bit modes are supported)
   - You could of course switch to using TIMER0 in the timing.c, but this may interfere with other thing on-board that use TIMER0, e.g. BLE controller). If we believe that TIMING_FUNCTIONS should be used for basic benchmrking, without enabling complext subsystems, that's fine to use this option.
   - Otherwise, you can keep TIMER2 but you need to do some little math around the calculations.

2. The second problem I see is that the average calculations are performed by
   - taking an initial timestamp,
   - running X number of iterations
   - taking an end timestamp
Any counter overflows will corrupt your measurements. And for example in nRF51, 16-bit counter will overflow quickly. I believe that we can fix this by storing the timestamps at every iteration and doing the
averaging at the end of the loop (or stgh similar)

**Comment by nashif** [comment]
> @nashif @dcpleung if you have this board could you investigate?

This issue existed in master already with nrf51 with latency_measure and other test using the original functions on top of RTC timer. I am not sure how I can fix those, so if you a suggestion, please go ahead, but I do not think they should block this PR. We could disable timeing api for this SoC until we have an appropriate implementation that works.

**Comment by nashif** [comment]
>     * You could of course switch to using TIMER0 in the timing.c, but this may interfere with other thing on-board that use TIMER0, e.g. BLE controller). If we believe that TIMING_FUNCTIONS should be used for basic benchmrking, without enabling complext subsystems, that's fine to use this option.

This is not going to be for benchmarking only, so we should avoid conflicts.

File: soc/arm/nordic_nrf/timing.c (hunk 12 above)
Comment (ioannisg) [reply soc/arm/nordic_nrf/timing.c:16]: > > @nashif @dcpleung if you have this board could you investigate?
> 
> This issue existed in master already with nrf51 with latency_measure and other test using the original functions on top of RTC timer. I am not sure how I can fix those, so if you a suggestion, please go ahead, but I do not think they should block this PR. We could disable timeing api for this SoC until we have an appropriate implementation that works.

I don't want to block this PR, but you should at least address the second point i made above (i.e. how to calculate the averages).

**Comment by andrewboie** [comment]
removed asm looks OK.

this one critical for 2.4? not quite convinced use of __weak in this way is the best idea for inheritance, we could get unpleasant surprises if the linker encounters the implementations in an order that doesn't correspond to the intended inheritance hierarchy

**Comment by nashif** [comment]
> this one critical for 2.4? not quite convinced use of __weak in this way is the best idea for inheritance, we could get unpleasant surprises if the linker encounters the implementations in an order that doesn't correspond to the intended inheritance hierarchy

Can't think of a better way to allow architectures variants, SoCs and boards to override a default implementation. We already do this for power management.

We need this for 2.4 because we have multiple users depending on this level of abstraction. The way it was implemented (as test code only) and the way we have been sourcing timestamp data for tracing, profiling has been inconsistent and misleading.

File: tests/benchmarks/latency_measure/src/thread_switch_yield.c [hunk 16]
```diff
@@ -79,8 +74,7 @@ void thread_switch_yield(void)
 	}
 
 	/* get the number of cycles it took to do the test */
-	TIMING_INFO_PRE_READ();
-	timestamp_end = TIMING_INFO_OS_GET_TIME();
+	timestamp_end = timing_counter_get();
```
Comment (ioannisg) [inline tests/benchmarks/latency_measure/src/thread_switch_yield.c:77]: the while loop may take long enough so the underlying cycles' counter infrastructure, which supplies measurements to timing_counter_get() may overflow and the timestamp_end - timestamp_start won't correspond to the elapsed time.

**Review by ioannisg — DISMISSED** [review]
Still needs to address the issues in the tests, with respect to how average timings are calculated.

File: soc/arm/nordic_nrf/timing.c (hunk 14 above)
[the remark this answers is not in the document]
Comment (ioannisg) [reply soc/arm/nordic_nrf/timing.c:13]: No, i think this makes no sense.

Being able to use the TIMER2 peripheral for timing measurements has nothing to do with whether NRF_RTC is used for timing. (You could use the SysTick for system timer and still be able to use TIMER2 for timing calculations in timing.c)

Corner case: qemu_cortex_m0 which uses the NRF_TIMER0 for system timer. But still TIMER2 is available for you here. So the #if defined(CONFIG_NRF_RTC_TIMER) is not useful and should be removed.

**Comment by andrewboie** [comment]
> Can't think of a better way to allow architectures variants, SoCs and boards to override a default implementation. We already do this for power management.

Let me ask this: let's consider the most complex case and say we have __weak implementations for some API at the core kernel, arch, soc, and board level.

What is in place to enforce this hierarchy ordering from the linker's perspective? I do not see it.

**Comment by nashif** [comment]
> What is in place to enforce this hierarchy ordering from the linker's perspective? I do not see it.

ok, makes sense. Need to think about another approach for this type of implementation. This probably will be the same problem with power management and needs fixing there as well.

**Comment by andrewboie** [comment]
> This probably will be the same problem with power management and needs fixing there as well.

I concur, I think if this doesn't maintain the expected ordering hierarchy, very nasty surprises could occur without an intuitive fix.

We might consider a vtable, like our driver model.

**Comment by nashif** [comment]
Using Kconfig for this now, removed __weak usage.

**Comment by nashif** [comment]
now also includes #27932

File: arch/common/timing.c (hunk 3 above)
Comment (nashif) [reply arch/common/timing.c:2]: @abrodkin  we will need an implementation of those functions for ARC based on the high res timer. Is this the same thing as in arch/arc/core/timestamp.c?

File: soc/arm/nordic_nrf/Kconfig.defconfig [hunk 17]
```diff
@@ -33,6 +33,11 @@ config SYS_POWER_MANAGEMENT
 config BUILD_OUTPUT_HEX
 	default y
 
+if !CORTEX_M_DWT
```
Comment (ioannisg) [inline soc/arm/nordic_nrf/Kconfig.defconfig:36]: Not sure if this is correct (i.e. we do not need the if !CORTEX_M_DWT:
The nRF SoCs _always have SOC_TIMING_FUNCTIONS and it should be default y.
The CMakeLists.txt , though, can make sure the ARCH (DWT) timing.c will be used, if present. Correct?

File: arch/arm/core/aarch32/cortex_m/CMakeLists.txt [hunk 18]
```diff
@@ -15,6 +15,16 @@ zephyr_library_sources(
 
 zephyr_library_sources_ifdef(CONFIG_DEBUG_COREDUMP coredump.c)
 
+if(CONFIG_ARCH_HAS_TIMING_FUNCTIONS AND
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/CMakeLists.txt:18]: I would remove this external if and _prioritize_ the ARCH-solution (DWT) if present, against SoC and Board.

File: arch/arm/core/aarch32/cortex_m/timing.c [hunk 19]
```diff
@@ -0,0 +1,168 @@
...
+		uint64_t dtsc = dwt_end - dwt_start;
+
+		dwt_frequency = (cyc_freq * dtsc) / dcyc;
+
+	}
+	return dwt_frequency;
+#endif /* CONFIG_SOC_FAMILY_NRF */
+}
+
+void __weak timing_init(void)
```
Comment (ioannisg) [inline arch/arm/core/aarch32/cortex_m/timing.c:124]: I guess these __weak attributes need to be removed, now.

File: soc/Kconfig [hunk 20]
```diff
@@ -41,3 +41,9 @@ config SOC_DEPRECATED_RELEASE
 	  the Zephyr release that the SoC configuration will be removed.
 	  When set, any build for that SoC will generate a clearly visible
 	  deprecation warning.
+
+config SOC_HAS_TIMING_FUNCTIONS
+	bool
+	help
+	  Should be selected if board provides custom method for retrieving
```
Comment (ioannisg) [inline soc/Kconfig:48]: SoC, not Board. Otherwise it is the same text as BOARD_HAS_TIMING_FUNCTIONS

File: soc/arm/nordic_nrf/timing.c (hunk 14 above)
[the remark this answers is not in the document]
Comment (ioannisg) [reply soc/arm/nordic_nrf/timing.c:13]: @nashif if you remove this #if defined(CONFIG_NRF_RTC_TIMER)
the example will compile for qemu_cortex_m0.

**Review by ioannisg — COMMENTED** [review]
Left some comments that should be fixed, but I think this PR could go in as is, provided the CI passes.
(I.e. the comments may be treated as implementation bugs and could be fixed later)

File: arch/common/timing.c (hunk 3 above)
Comment (ruuddw) [reply arch/common/timing.c:2]: Both arch/arc/core/timestamp.c and the timer driver arcv2_timer0.c use the timer0 that is part of the ARC core and runs at CPU clock frequency. Timestamp.c doesn't seem to take into account timer setting and wrapping in the timer driver, that is likely a problem.
Depending on ARC configuration, there can be a second timer, and 2 separate secure mode timers. There can be a counter as well, and for SMP a global counter.
Problem is that not all of these have to be present in in all ARC instances, ARC users choose a configuration. So we try to work with the minimum, though using more timers/counters would make implementations simpler.
