### PR TITLE
mm: common: reset mappings during simple mapping failures

### LINKED ISSUE #73121: Memory mapping functions can return error without clean up
**Describe the bug**
If asserts are disabled in a build, both generic and (probably derived from them) hardware-specific memory mapping functions like `sys_mm_drv_simple_map_region()`, `sys_mm_drv_map_region()`, `sys_mm_drv_simple_map_array()` can return in an error case without freeing resources, that they have been able to allocate.

**Expected behavior**
In failure cases functions should clean up resources, that they've managed to allocate before the failure.

**Impact**
In error cases can lead to resource exhaustion.

### PR DESCRIPTION
**Pull request by dcpleung**
For mapping operations in sys_mm_drv_simple_map_region() and sys_mm_drv_simple_map_array(), when there was an error with mapping any pages, it would simple return an error, leaving already mapped pages still mapped. This modifies the behavior where any failure during the whole mapping operation will unmap the already mapped pages.

This also modifies the remapping and moving functions to reset mappings when error is encountered.

Fixes #73121

### CODE REVIEW

**Comment by dcpleung** [comment]
@lyakh Do you have a way to test this?

**Comment by nashif** [comment]
@lyakh  can you please take a look?

File: drivers/mm/mm_drv_common.c [hunk 1]
```diff
@@ -310,38 +387,46 @@ int sys_mm_drv_simple_move_region(void *virt_old, size_t size,
 		uint8_t *va_new = (uint8_t *)virt_new + offset;
 		uintptr_t pa = phys_new + offset;
 		uint32_t flags;
-		int ret2;
```
Comment (lyakh) [inline drivers/mm/mm_drv_common.c:313]: can this function not simply be implemented as
```
map(new)
memcpy(new, old)
unmap(old)
```
? Or do we really need to support different flags per page?

**Review by lyakh — COMMENTED** [review]
some of these functions don't seem to have any real-life users, just tests. Weird...

**Comment by lyakh** [comment]
> @lyakh Do you have a way to test this?

I only see tests in tests/boards/intel_adsp/mm/src/main.c so maybe we could add a couple of failure cases there? Maybe using some invalid flags.

And yes, sorry, I have to review my GH notification settings :-/

**Comment by lgirdwood** [comment]
> > @lyakh Do you have a way to test this?
> 
> I only see tests in tests/boards/intel_adsp/mm/src/main.c so maybe we could add a couple of failure cases there? Maybe using some invalid flags.
> 
> And yes, sorry, I have to review my GH notification settings :-/

@dcpleung this could be tested by creating a SOF PR that points SOF west to this PR. Testing the error handling would need an additional patch in your SOF PR that did some usage of this API in SOF init code (the logs would show results if your test). ztest is not option yet as CI does not yet have infra in invoke or get results.

**Comment by dcpleung** [comment]
Does SOF CI test for memory leaks? The issue here is to avoid memory exhaustion. CI tests may not be long enough for the issue to surface.

File: drivers/mm/mm_drv_common.c [hunk 2]
```diff
@@ -224,48 +287,62 @@ int sys_mm_drv_simple_remap_region(void *virt_old, size_t size,
...
+			 * Note the offset is at the current failed address
+			 * which will not be included during unmapping.
+			 */
+			failure_mapping_reset(virt_new, offset);
+
+			goto unlock_out;
 		}
 	}
 
+	(void)unmap_locked(virt_old, size);
```
[the remark this answers is not in the document]
Comment (dcpleung) [reply drivers/mm/mm_drv_common.c:344]: Hardware should be able to map any number of virtual address to the same physical page.

If we cannot map the new region entirely, we need to roll back and remove any newly mapped addresses and also need to retain the old mappings. It is done this way because we do not have to re-map the old region. We "simply" remove the new mappings, and do not have to do rollback one by one. If the new mappings can be done entirely, we simply remove the whole old mapped region.

File: drivers/mm/mm_drv_common.c (hunk 1 above)
Comment (dcpleung) [reply drivers/mm/mm_drv_common.c:313]: It is more about preserving existing flags.

**Comment by lgirdwood** [comment]
> Does SOF CI test for memory leaks? The issue here is to avoid memory exhaustion. CI tests may not be long enough for the issue to surface.

Yes, Internal SOF CI does check for memory leaks and we can also schedule a stress test that can create/destroy multiple pipelines (which will alloc/free resources). @dcpleung can you create a test SOF PR that references this PR via a west update. This way we can do the Internal CI check and the stress test. Please reference me on the PR. Thanks.

**Comment by dcpleung** [comment]
SOF stress test does not indicate anything wrong with this. So this is good to go.

**Review by nashif — APPROVED** [review]

**Review by ceolin — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]
