### PR TITLE
tests/drivers/dma: loop_transfer: Use ztest harness

### LINKED ISSUE #31226: tests/drivers/dma/loop_transfer does not use ztest
**Describe the bug**
`tests/drivers/dma/loop_transfer` is implemented as a sample.
It does not use ztest harness and does not provide a verdict

**Expected behavior**
Either it should be reworked to provide a verdict uing ztest, either it should be moved to `samples/drivers`

### PR DESCRIPTION
**Pull request by erwango**
loop_transfer test was not using ztest framework as test harness.
Fix it.

Fixes: #31226
Replaces: #31352

### CODE REVIEW

File: tests/drivers/dma/loop_transfer/src/test_dma_loop.c [hunk 1]
```diff
@@ -1,17 +1,30 @@
 /* dma.c - DMA test source file */
 
 /*
- * Copyright (c) 2016 Intel Corporation.
+ * Copyright (c) 2021 Linaro Limited.
```
Comment (nashif) [inline tests/drivers/dma/loop_transfer/src/test_dma_loop.c:4]: You should not be replacing copyrights, just add yours on top.

**Review by nashif — CHANGES_REQUESTED** [review]

**Review by hakehuang — APPROVED** [review]

File: tests/drivers/dma/loop_transfer/src/test_dma_loop.c (hunk 1 above)
Comment (erwango) [reply tests/drivers/dma/loop_transfer/src/test_dma_loop.c:4]: Ho, right, sorry, I did it mechanically as this appeared to be a new file (?!!?), will fix.

Comment (erwango) [reply tests/drivers/dma/loop_transfer/src/test_dma_loop.c:4]: fixed

**Review by nashif — APPROVED** [review]
