### PR TITLE
Bluetooth: gatt: ccc changed cb after connection cb

### LINKED ISSUE #13316: Notification enabled before connection
**Describe the bug**
Bond peripheral device to Moto G5 (Android 8.1.0). Reboot device which will reconnect.
On the log I observe that before connection callback is received I get callback about notification being enabled. 

CCC changes are notified from channel ops callback called from `bt_l2cap_connected`. This last function is called from `bt_conn_set_state` on `BT_CONN_CONNECTED` state. Now note that `notify_connected` is called from the same place but after `bt_l2cap_connected`. This explains why information about callback is sent to application after information about notification being enabled.

**To Reproduce**
Described above.

**Impact**
Application does not know which connection ccc change relates to as there is no `conn` argument in the callback.

**Screenshots or console output**
```
[00009340] <inf> ble_adv: Advertising started
[00065351] <err> bt_hci_core: PDUNAJ enh_conn_complete 839
[00065355] <err> bt_hci_core: PDUNAJ enh_conn_complete 958 conn=0x20002554
[00065356] <err> bt_gatt: PDUNAJ bt_gatt_connected 2429 conn 0x20002554
[00065357] <err> bt_gatt: PDUNAJ connected_cb 1078
[00065357] <err> bt_gatt: PDUNAJ gatt_ccc_changed 644
[00065357] <err> ble_gatt_hids: PDUNAJ hids_input_report_ccc_changed 440
[00065358] <err> hids: PDUNAJ mouse_notif_handler 135
[00065358] <err> hids: PDUNAJ notif_handler 125
[00065358] <err> hids: PDUNAJ broadcast_subscription_change 72 conn=0x00000000
[00065359] <inf> hids: Notifications enabled
[00065359] <err> bt_gatt: PDUNAJ connected_cb 1078
[00065359] <err> bt_gatt: PDUNAJ gatt_ccc_changed 644
[00065360] <err> ble_gatt_hids: PDUNAJ hids_boot_mouse_inp_rep_ccc_changed 494
[00065360] <err> hids: PDUNAJ boot_mouse_notif_handler 142
[00065360] <err> hids: PDUNAJ notif_handler 125
[00065361] <err> bt_conn: PDUNAJ notify_connected 136 conn=0x20002554 cb=0x00003f01
[00065363] <inf> ble_state: Connected to 80:58:f8:56:19:ce (public)
[00065364] <inf> ble_state: Set security level
[00065368] <inf> event_manager: e: hid_report_subscription_event MOUSE report notification enabled by 0x00000000
[00065370] <inf> event_manager: e: ble_peer_event id=0x20002554 CONNECTED
```

**Environment (please complete the following information):**
ncs zephyr `236ec2d2553536835c76dff84adcb188309eaf90`
zephyr `dee63e20`

**Additional context**
I this it worked in the past... although I see no changes related to this done recently. Maybe something else changed or this was overlooked...

### PR DESCRIPTION
**Pull request by kapi-no**
Fixes #13316

Changed the order of Bluetooth callbacks. Now the connected callback is
received before CCC changed callbacks.

Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>

### CODE REVIEW

**Review by Vudentz — APPROVED** [review]
LGTM

**Review by jhedberg — APPROVED** [review]

**Comment by jhedberg** [comment]
@kapi-no could you update the PR with a proper reference to the github issue that it fixes? It's important to have these linked together (it also makes a stronger case for getting this merged for 1.14)

**Comment by kapi-no** [comment]
@jhedberg, I added a reference in the PR description

**Comment by pdunaj** [comment]
We need to reopen this one as we see problem with it.
@kapi-no when gatt is notified about connection error is not checked. It can happen that connection failed and in this case notification will still be sent. We observe that when direct advertised connection fails.

**Comment by Vudentz** [comment]
@pdunaj Would you guys provide a fix for this?

**Comment by pdunaj** [comment]
Hi @Vudentz , I guess so. Check for no error before notifying gatt should be enough I guess.

File: subsys/bluetooth/host/conn.c [hunk 1]
```diff
@@ -136,6 +137,8 @@ static void notify_connected(struct bt_conn *conn)
 			cb->connected(conn, conn->err);
 		}
 	}
+
```
Comment (Vudentz) [inline subsys/bluetooth/host/conn.c]: We should probably do something like:
if (!conn->err) {
    bt_gatt_connected(conn);
}
