### PR TITLE
LE Audio shell strtoX fixes

### LINKED ISSUE #54101: bluetooth: shell: Lots of checks of type (unsigned < 0) which is bogus
Unsigned cannot be less then zero so there is no need to check for it.

Example of checks:
https://github.com/zephyrproject-rtos/zephyr/blob/cf871aec645dc45503b20c2e7684a4babbc436dc/subsys/bluetooth/shell/bap_broadcast_assistant.c#L315-L316
 or
https://github.com/zephyrproject-rtos/zephyr/blob/cf871aec645dc45503b20c2e7684a4babbc436dc/subsys/bluetooth/shell/bap_broadcast_assistant.c#L321-L322

etc

### PR DESCRIPTION
**Pull request by Thalley**
Ensures that all `strtoX` calls are handled correctly, and moves to use the `shell_strtoX` functions 

Fixes most of the bugs reported in https://github.com/zephyrproject-rtos/zephyr/issues/54101

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54101

### CODE REVIEW

**Review by finikorg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/shell/vcp_vol_rend.c [hunk 1]
```diff
@@ -249,12 +249,19 @@ static int cmd_vcp_vol_rend_init(const struct shell *sh, size_t argc,
 static int cmd_vcp_vol_rend_volume_step(const struct shell *sh, size_t argc,
 					char **argv)
 {
-	int result;
-	int step = strtol(argv[1], NULL, 0);
+	unsigned long step;
+	int result = 0;
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/shell/vcp_vol_rend.c:253]: I disagree; I think it's better to just use the already defined value to keep the number of lines changed to a minimum.

File: subsys/bluetooth/shell/vcp_vol_rend.c [hunk 2]
```diff
@@ -429,24 +456,43 @@ static int cmd_vcp_vol_rend_vocs_location_get(const struct shell *sh,
...
-	result = bt_vocs_location_set(vcp_included.vocs[index],
-					  location);
+	location = shell_strtoul(argv[2], 0, &result);
+	if (result != 0) {
+		shell_error(sh, "Failed to parse location: %d", result);
+
+		return -ENOEXEC;
+	}
+
+	if (location > UINT32_MAX) {
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/shell/vcp_vol_rend.c:489]: Yes, perhaps that should have been a separate commit. Should I add another commit for that?

File: subsys/bluetooth/shell/vcp_vol_rend.c [hunk 3]
```diff
@@ -249,12 +249,19 @@ static int cmd_vcp_vol_rend_init(const struct shell *sh, size_t argc,
...
+	if (result != 0) {
+		shell_error(sh, "Failed to parse step: %d", result);
+
+		return -ENOEXEC;
+	}
+
+	if (step > UINT8_MAX) {
+		shell_error(sh, "Invalid step %lu", step);
 
-	if (step > UINT8_MAX || step == 0) {
```
[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/shell/vcp_vol_rend.c:255]: Nice catch - Thanks!

File: subsys/bluetooth/shell/vcp_vol_rend.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (finikorg) [reply subsys/bluetooth/shell/vcp_vol_rend.c:489]: Yes, I think

[the remark this answers is not in the document]
Comment (Thalley) [reply subsys/bluetooth/shell/vcp_vol_rend.c:489]: Added a commit to fix this in the PR

File: subsys/bluetooth/shell/bap_broadcast_assistant.c [hunk 4]
```diff
@@ -269,10 +270,13 @@ static int cmd_bap_broadcast_assistant_scan_start(const struct shell *sh,
...
 	if (argc > 1) {
-		start_scan = strtol(argv[1], NULL, 0);
+		result = 0;
+
+		start_scan = shell_strtobool(argv[1], 0, &result);
+		if (result != 0) {
+			shell_error(sh, "Could not parse start_scan: %d",
+				    result);
 
-		if (start_scan != 0 && start_scan != 1) {
```
Comment (finikorg) [inline subsys/bluetooth/shell/bap_broadcast_assistant.c:274]: `shell_strtobool` has different logic, at the end it converts `unsigned long` to `bool`, so any number > 0 is true, right?

**Review by finikorg — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/shell/bap_broadcast_assistant.c (hunk 4 above)
Comment (Thalley) [reply subsys/bluetooth/shell/bap_broadcast_assistant.c:274]: Right. I was unsure about whether I should just use `shell_strtobool` directly, or actually check if the value was > 1, but decided on the former, as just using `shell_strtobool` would be more consistent with other shell commands that use that.

Comment (finikorg) [reply subsys/bluetooth/shell/bap_broadcast_assistant.c:274]: OK, looks reasonable.

**Review by finikorg — DISMISSED** [review]
LGTM, although I would use the same error code `err` instead of `result`, etc.

**Comment by Thalley** [comment]
> LGTM, although I would use the same error code `err` instead of `result`, etc.

Making all the audio shell implementations more consistent can be postponed to a separate PR :)

File: subsys/bluetooth/shell/tbs.c [hunk 5]
```diff
@@ -402,30 +504,43 @@ static int cmd_tbs_set_bearer_technology(const struct shell *sh, size_t argc,
...
+			if (service_index > CONFIG_BT_TBS_BEARER_COUNT) {
+				shell_error(sh, "Invalid service_index: %lu",
 					    service_index);
 
 				return -ENOEXEC;
 			}
 		}
 	} else {
-		service_index = 0;
+		service_index = 0U;
```
Comment (MariuszSkamra) [inline subsys/bluetooth/shell/tbs.c:532]: Did you consider to factor out this repeated code to some helper function?

File: subsys/bluetooth/shell/tbs_client.c [hunk 6]
```diff
@@ -404,16 +550,26 @@ static int cmd_tbs_client_read_technology(const struct shell *sh, size_t argc,
...
+				return -ENOEXEC;
+			}
+
+			if (inst_index > UINT8_MAX) {
+				shell_error(sh, "Invalid index: %lu",
+					    inst_index);
+
 				return -ENOEXEC;
 			}
 		}
```
Comment (MariuszSkamra) [inline subsys/bluetooth/shell/tbs_client.c:575]: ditto

File: subsys/bluetooth/shell/vcp_vol_rend.c [hunk 7]
```diff
@@ -249,12 +249,19 @@ static int cmd_vcp_vol_rend_init(const struct shell *sh, size_t argc,
...
+	int result = 0;
+
+	step = shell_strtoul(argv[1], 0, &result);
+	if (result != 0) {
+		shell_error(sh, "Failed to parse step: %d", result);
+
+		return -ENOEXEC;
+	}
+
+	if (step > UINT8_MAX || step == 0U) {
```
Comment (MariuszSkamra) [inline subsys/bluetooth/shell/vcp_vol_rend.c:262]: You could use nice IN_RANGE macro as in other places :)

File: subsys/bluetooth/shell/vcp_vol_rend.c [hunk 8]
```diff
@@ -457,13 +503,33 @@ static int cmd_vcp_vol_rend_vocs_location_set(const struct shell *sh,
...
+	}
+
+	if (index >= vcp_included.vocs_cnt) {
+		shell_error(sh, "Index shall be less than %u, was %lu",
+			    vcp_included.vocs_cnt, index);
+
+		return -ENOEXEC;
+	}
+
+	offset = shell_strtoul(argv[2], 0, &result);
```
Comment (MariuszSkamra) [inline subsys/bluetooth/shell/vcp_vol_rend.c:529]:
```suggestion
	offset = shell_strtol(argv[2], 0, &result);
```

**Review by MariuszSkamra — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/shell/tbs.c (hunk 5 above)
Comment (Thalley) [reply subsys/bluetooth/shell/tbs.c:532]: I actually did :) It would make sense, but since this is a bugfixing PR, I'd rather keep the changes to a minimum. I suggest to do this in a separate PR.

**Comment by Thalley** [comment]
Thanks for the review @MariuszSkamra - I've reviewed this myself twice, but I guess you easily get blind when reviewing so many similar changes :D Nice that you caught that many errors

**Review by MariuszSkamra — DISMISSED** [review]
LGTM

**Comment by Thalley** [comment]
Found a few more with incorrect type

File: subsys/bluetooth/shell/tbs_client.c [hunk 9]
```diff
@@ -51,27 +53,44 @@ static int cmd_tbs_client_set_signal_strength_interval(const struct shell *sh,
...
+	int result = 0;
 
 	if (argc > 2) {
 		if (strcmp(argv[1], "gtbs") == 0) {
 			inst_index = BT_TBS_GTBS_INDEX;
 		} else {
-			inst_index = strtol(argv[1], NULL, 0);
-			if (inst_index < 0 || inst_index > UINT8_MAX) {
-				shell_error(sh, "Invalid index");
+			inst_index = shell_strtoul(argv[1], 0, &result);
```
Comment (kruithofa) [inline subsys/bluetooth/shell/tbs_client.c:64]: add a comment/TODO that this can be pulled out as a function since this code is repeated many times?

File: subsys/bluetooth/shell/vcp_vol_ctlr.c [hunk 10]
```diff
@@ -609,23 +646,38 @@ static int cmd_vcp_vol_ctlr_vocs_location_set(const struct shell *sh,
...
+	offset = shell_strtol(argv[2], 0, &result);
+	if (result != 0) {
+		shell_error(sh, "Failed to parse offset: %d", result);
+
 		return -ENOEXEC;
 	}
 
 	if (offset > BT_VOCS_MAX_OFFSET || offset < BT_VOCS_MIN_OFFSET) {
-		shell_error(sh, "Offset shall be %d-%d, was %d",
+		shell_error(sh, "Offset shall be %d-%d, was %ld",
```
Comment (kruithofa) [inline subsys/bluetooth/shell/vcp_vol_ctlr.c:680]: missed opportunity for using IN_RANGE

File: subsys/bluetooth/shell/vcp_vol_ctlr.c [hunk 11]
```diff
@@ -894,23 +1024,35 @@ static int cmd_vcp_vol_ctlr_aics_auto_input_gain_set(const struct shell *sh,
...
 
+	gain = shell_strtol(argv[2], 0, &result);
+	if (result != 0) {
+		shell_error(sh, "Could not parse gain: %d", result);
+		return -ENOEXEC;
+	}
+
 	if (gain > INT8_MAX || gain < INT8_MIN) {
-		shell_error(sh, "Offset shall be %d-%d, was %d",
+		shell_error(sh, "Gain shall be %d-%d, was %d",
```
Comment (kruithofa) [inline subsys/bluetooth/shell/vcp_vol_ctlr.c:1055]: use IN_RANGE?

**Review by kruithofa — CHANGES_REQUESTED** [review]

**Review by kruithofa — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
