### PR TITLE
drivers: Check errors on devices selected using dt macro

### LINKED ISSUE #20068: Application doesn't start when SHELL-UART is enabled and UART is not connected on STM32F0
**Describe the bug**
I am doing a project with the MCU **STM32F091RC** and whenever I enable SHELL-UART through `CONFIG_SHELL=y` in the **prj.conf** file, the application stops working.

The application I am testing is below, just printing a `Hello World` and blinking an LED. Note that I do not create shell commands. I've just enabled it in the **prj.conf** file.

```
/*
 * Copyright (c) 2012-2014 Wind River Systems, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <device.h>
#include <dfu/mcuboot.h>
#include <gpio.h>
#include <misc/printk.h>
#include <misc/reboot.h>
#include <zephyr.h>

#define LED_PORT DT_GPIO_LEDS_LED_GREEN_GPIO_CONTROLLER
#define LED DT_GPIO_LEDS_LED_GREEN_GPIO_PIN


void main(void)
{
    struct device *dev;
    u32_t led_value = 0;

    dev = device_get_binding(LED_PORT);
    /* Set LED pin as output */
    gpio_pin_configure(dev, LED, GPIO_DIR_OUT);

    while (1) {
        printk("Hello World! %s\n", CONFIG_BOARD);
        gpio_pin_write(dev, LED, led_value);
        led_value = !led_value;
        k_sleep(K_MSEC(200));
    }
}
```

The file **prj.conf** is like this:

```
CONFIG_PRINTK=y
CONFIG_SHELL=y
CONFIG_REBOOT=y
```

In the .**dts** file I have used this to choose UART console and shell:

``` 
chosen {
		zephyr,console = &usart2;
		zephyr,shell-uart = &usart2;
		zephyr,sram = &sram0;
		zephyr,flash = &flash0;
		zephyr,code-partition = &slot0_partition;
	};
```

I have uploaded the same code to **nRF52840_pca10056** board and everything works fine. Another board with **STM32F4** had the same result as the nRF board, application runs OK.

The only difference that breaks the normal execution of the application in the **STM32F0** is the change from `CONFIG_SHELL=y` to `CONFIG_SHELL=n`. It's like the application does not start and LED does not blink.

Does anyone have any idea on this?

### PR DESCRIPTION
**Pull request by erwango**
Some Kconfig defined devices may be defined using dt_chosen_label
function. Since there is no way to ensure a device enabled in dts
is also defined in Kconfig, it may happen that instance is not
actually defined.
In this case device_get_binding might return 0, leading to undefined
behavior in the function that calls it.
When not already done, systematically check return of function
device_get_binding on devices defined through dt_chosen_label macro.
Trigger ASSERT when required and return error when possible.

Fixes #20068

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

File: subsys/bluetooth/host/monitor.c [hunk 1]
```diff
@@ -328,6 +328,8 @@ static int bt_monitor_init(struct device *d)
 
 	monitor_dev = device_get_binding(CONFIG_BT_MONITOR_ON_DEV_NAME);
 
+	__ASSERT_NO_MSG(monitor_dev);
```
Comment (joerchan) [inline subsys/bluetooth/host/monitor.c]: If asserts are not enabled we would give monitor_dev to uart_irq_rx/tx_disable below. Maybe we should do the handling that you did in shell_uart.c in all places that you added the assert?

**Review by joerchan — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/host/monitor.c (hunk 1 above)
Comment (erwango) [reply subsys/bluetooth/host/monitor.c]: This was my initial intention, but in functions invoked in `SYS_INIT` macro (like current `bt_monitor_init`), returned values won't be checked AFAIU.

Comment (joerchan) [reply subsys/bluetooth/host/monitor.c]: That is strange, seems wierd to have return codes then. But the return would stop you from doing something harmful at least, it could be a null pointer write which would lead to MPU fault or other types of memory errors. And maybe somebody will check the return value in the future :)

Comment (erwango) [reply subsys/bluetooth/host/monitor.c]: > But the return would stop you from doing something harmful at least, it could be a null pointer write which would lead to MPU fault or other types of memory errors. 

I'd rather not do this as this would likely be easily caught by various code analysis scripts, so this would add support follow-up to this PR.

> And maybe somebody will check the return value in the future :)

Or... somebody will require these functions to be void :-)

Comment (joerchan) [reply subsys/bluetooth/host/monitor.c]: well I'm just skeptical since the ASSERT might not be enabled. And then the check would simply be skipped an the code continues, so we would end up in undefined behavior anyway.

**Review by joerchan — APPROVED** [review]

File: subsys/bluetooth/host/monitor.c (hunk 1 above)
Comment (erwango) [reply subsys/bluetooth/host/monitor.c]: I agree. ASSERT are disabled by default, but in case one started to debug this kind of things, enabling them would be one of the first step (was mine at least).
Anyway the real solution to this is solving Kconfig/dt desynchro and @galak is working on it.

File: subsys/shell/shell_uart.c [hunk 2]
```diff
@@ -274,6 +274,11 @@ static int enable_shell_uart(struct device *arg)
 		(CONFIG_SHELL_BACKEND_SERIAL_LOG_LEVEL > LOG_LEVEL_DBG) ?
 		CONFIG_LOG_MAX_LEVEL : CONFIG_SHELL_BACKEND_SERIAL_LOG_LEVEL;
 
+	if (dev == NULL) {
+		__ASSERT_NO_MSG(dev);
```
Comment (nashif) [inline subsys/shell/shell_uart.c]: having asserts and error checking in the same spot is not ideal IMO, you either assert on the whole thing or do error handling and propagation.

**Review by nashif — DISMISSED** [review]

File: subsys/shell/shell_uart.c (hunk 2 above)
Comment (erwango) [reply subsys/shell/shell_uart.c]: Agreed. Fixed, thanks for review!

**Review by jhedberg — APPROVED** [review]

**Comment by erwango** [comment]
@nashif updated

**Comment by erwango** [comment]
@nashif, can you review again ?

**Comment by joerchan** [comment]
@erwango Misspelled subsys? (susbsys). Anyway I don't think subsys should be in the title, so you could remove it.

**Comment by erwango** [comment]
Even if the initial issue which is dts/Kconfig device instance desynchro that was at the initiation of this issue cannot happen anymore due to recent changes, I think the check is sane and worth keeping.
If this does not go in v2.3.0, I'll close the point so we don't keep it eternally.

**Review by carlescufi — APPROVED** [review]
