### PR TITLE
Bluetooth: hci_nxp: Fix Unique ID offset when setting MAC address

### LINKED ISSUE #98951: Bluetooth HCI NXP: Low entropy and incorrect offset in MAC address generation from MCU Unique ID
### Describe the bug

This issue addresses two flaws in the `hci_nxp` driver's method for generating a local MAC address using the MCU's 16-byte Unique ID (UID):

1. **Low Entropy/Collision Risk:** The previous method used a **simple slice of 3 bytes** from the UID, resulting in poor randomization and a higher **risk of MAC address collision**.
  
2. **Offset Error:** The calculation used to determine the **starting point (offset)** for slicing those 3 bytes from the 16-byte UID was **incorrect**, leading to an invalid MAC address part.
  

This combination resulted in a potentially invalid or non-unique MAC address being used, impacting Bluetooth communication and device identification. The fix implements a **CRC-32 hash** over the full 16-byte UID to generate a robust, highly unique 3-byte local part.

**Area:** Drivers, Bluetooth, HCI, NXP

### Regression

- [ ] This is a regression.

### Steps to reproduce

The bug is a logic error verifiable via static code analysis.

> **Write:**
> 
> 1. Examine the MAC address generation logic in the `hci_nxp` driver's source code.
>   
> 2. The presence of direct slicing of 3 bytes from the UID and the flawed offset calculation confirms the underlying logic error and low entropy risk.
>   
> 3. The issue manifests when the driver attempts to initialize the Bluetooth MAC address, potentially resulting in an invalid or non-unique address.
>

### Relevant log output

```shell

```

### Impact

Not sure

### Environment

- **OS:** Windows WSL
  
- **Toolchain:** Zephyr SDK
  
- **Driver:** Bluetooth HCI NXP Driver (`hci_nxp`)

### Additional Context

Additional Context: Fix Proposal is presented in the following PR: #98623

### PR DESCRIPTION
**Pull request by kaabia**
Fixes <https://github.com/zephyrproject-rtos/zephyr/issues/98951>

The previous method for generating the local MAC address from the MCU's Unique ID (UID) by slicing 3 bytes had two issues:
- Low Entropy: Risk of address collision due to poor randomization from the sliced bytes.
- Offset Error: The calculation for the slice starting point was incorrect.

This patch implements a CRC-32 hash over the entire 16-byte UID. The lower 3 bytes of the resulting hash are used as the MAC address's local part.

This change ensures a robust, highly unique address, resolving both the technical offset error and the underlying entropy problem

### CODE REVIEW

**Comment by dleach02** [comment]
@yeaissa @axelnxp please review as you contributed this code

**Review by axelnxp — CHANGES_REQUESTED** [review]
> This ensures the last `BD_ADDR_UUID_PART_SIZE` (3) bytes of the MCU
> UID are used as intended.

@kaabia  So the UID is 16 bytes, and from our testing we've noticed that some bytes barely change between different parts. Right now we pick out the bytes that vary the most to generate the address - not ideal, but it works.

We've been thinking about using a CRC over all 16 bytes instead. This would mix the entire UID and give us better randomization for the address generation, which should help avoid collisions.

I need to block this PR for now while we check internally if the change still works. Or if you want to take a shot at implementing the CRC approach, that would be great too.

**Comment by kaabia** [comment]
> > This ensures the last `BD_ADDR_UUID_PART_SIZE` (3) bytes of the MCU
> > UID are used as intended.
> 
> @kaabia So the UID is 16 bytes, and from our testing we've noticed that some bytes barely change between different parts. Right now we pick out the bytes that vary the most to generate the address - not ideal, but it works.
> 
> We've been thinking about using a CRC over all 16 bytes instead. This would mix the entire UID and give us better randomization for the address generation, which should help avoid collisions.
> 
> I need to block this PR for now while we check internally if the change still works. Or if you want to take a shot at implementing the CRC approach, that would be great too.

Hi @axelnxp 
Thank you for the feedback on the UID entropy issue. I completely agree that slicing the UID is sub-optimal and poses a collision risk.

I went ahead and implemented the CRC approach you suggested.

**Changes Made:**
1. Replaced the UID slicing with a **CRC-32 hash** calculated over the entire 16-byte UID.
2. The resulting 24 bits (3 LSBs) of the CRC-32 value are now used as the local part of the MAC address.
3. This significantly improves entropy and guarantees much better randomization than the previous method.

I've updated the PR with this new logic and revised the commit message to reflect the change from a simple offset fix to the robust CRC-based implementation.

It's ready for your final review. Let me know if you have any further feedback!

Feel free to update the PR name as follow : Bluetooth: hci_nxp: Improve MAC address uniqueness using CRC-32 hash

**Review by axelnxp — CHANGES_REQUESTED** [review]
The driver needs to explicitly select the CRC subsys in Kconfig to resolve the dependency.
Otherwise, it doesn't build out of the box.
You can apply the following patch:

```
diff --git a/drivers/bluetooth/hci/Kconfig b/drivers/bluetooth/hci/Kconfig
index 21aeeb98ee2..6e83fc8cece 100644
--- a/drivers/bluetooth/hci/Kconfig
+++ b/drivers/bluetooth/hci/Kconfig
@@ -254,6 +254,7 @@ config BT_NXP
        default y
        depends on DT_HAS_NXP_HCI_BLE_ENABLED
        select BT_HCI_SETUP
+       select CRC if BT_HCI_SET_PUBLIC_ADDR
        help
          NXP HCI bluetooth interface
```

File: drivers/bluetooth/hci/hci_nxp.c [hunk 1]
```diff
@@ -188,12 +191,20 @@ static int bt_nxp_set_mac_address(const bt_addr_t *public_addr)
...
+			 * Initial CRC value is 0xFFFFFFFFU for maximum randomization
+			 */
+			unique_val_crc = crc32_ieee_update(HCI_BT_MAC_ADDR_CRC_SEED, uid, uuidLen);
+			/* Copy the lower 3 bytes (24 bits) of the CRC result */
+			memcpy((void *)bleDeviceAddress, (const void *)&unique_val_crc,
+					BD_ADDR_UUID_PART_SIZE);
+		} else {
+			LOG_ERR("UUID is empty, cannot generate address.");
+			return -EFAULT;
+        }
```
Comment (yeaissa) [inline drivers/bluetooth/hci/hci_nxp.c]: Missing tab, compliance check probably failing due to this.

Comment (kaabia) [reply drivers/bluetooth/hci/hci_nxp.c]: Good catch, thank you 
Done

**Comment by kaabia** [comment]
> The driver needs to explicitly select the CRC subsys in Kconfig to resolve the dependency. Otherwise, it doesn't build out of the box. You can apply the following patch:
> 
> ```
> diff --git a/drivers/bluetooth/hci/Kconfig b/drivers/bluetooth/hci/Kconfig
> index 21aeeb98ee2..6e83fc8cece 100644
> --- a/drivers/bluetooth/hci/Kconfig
> +++ b/drivers/bluetooth/hci/Kconfig
> @@ -254,6 +254,7 @@ config BT_NXP
>         default y
>         depends on DT_HAS_NXP_HCI_BLE_ENABLED
>         select BT_HCI_SETUP
> +       select CRC if BT_HCI_SET_PUBLIC_ADDR
>         help
>           NXP HCI bluetooth interface
> ```

Patch DONE !
Thanks you

**Review by axelnxp — APPROVED** [review]
Looks good, thanks for your patch!

**Review by yeaissa — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]

**Review by cfriedt — APPROVED** [review]

**Comment by cfriedt** [comment]
Added @axelnxp as co-assignee, since he has engaged already and is from NXP
