### PR TITLE
Bluetooth: Audio: Improve unicast client handling of CIG

### LINKED ISSUE #44307: LE Audio: unicast stream/ep or ACL disconnect reset should not terminate the CIG
**Describe the bug**
The CIG, or unicast group, is a group of streams and is not directly related to any connections. The current implementation terminates the CIG once `bt_audio_stream_reset` is called. 

On ACL disconnect we call `unicast_client_ep_reset` which calls `unicast_client_reset` which calls `bt_audio_stream_reset`. Resetting a stream only terminate the CIG. 

**To Reproduce**
N/A

**Expected behavior**
When ACL disconnects we should correctly reset the endpoint and detach the stream and endpoint. However the stream should remain intact, and the CIG/unicast group should not be changed. 

**Impact**
If there's a single group with multiple streams on multiple unicast servers, then if any of those connects, we attempt to terminate the group, even if there's multiple other streams active. The impact is currently just a bad log message, as a CIG cannot be terminated with active CIS. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Thalley**
The CIG was improperly handled by the unicast
client. It attempted to remove the CIG when an ACL
was disconnected, and did not properly use the
cig_reconfigure function.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

fixes https://github.com/zephyrproject-rtos/zephyr/issues/44307

### CODE REVIEW

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/audio/stream.c [hunk 1]
```diff
@@ -440,6 +429,36 @@ static int bt_audio_cig_create(struct bt_audio_unicast_group *group,
...
+		group->cis[cis_count++] = stream->iso;
+	}
+
+	param.num_cis = cis_count;
+	param.cis_channels = group->cis;
+	bt_audio_codec_qos_to_cig_param(&param, qos);
+
+	err = bt_iso_cig_reconfigure(group->cig, &param);
+	if (err != 0) {
+		BT_ERR("bt_iso_cig_create failed: %d", err);
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/stream.c:453]: BT_ERR("bt_iso_cig_reconfigure failed: %d", err);

File: subsys/bluetooth/audio/stream.c [hunk 2]
```diff
@@ -566,26 +585,19 @@ int bt_audio_stream_qos(struct bt_conn *conn,
...
-		if (qos->interval != group->qos->interval ||
-		    qos->latency != group->qos->latency ||
-		    qos->framing != group->qos->framing) {
-			BT_DBG("Cannot override group QoS values");
-			return -EINVAL;
+	/* Create or reconfigure the CIG */
+	if (group->cig == NULL) {
+		err = bt_audio_cig_create(group, qos);
+		if (err != 0) {
+			BT_DBG("bt_audio_cig_create failed: %d", err);
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/stream.c:592]: Should't this be BT_ERR?

File: subsys/bluetooth/audio/stream.c [hunk 3]
```diff
@@ -566,26 +585,19 @@ int bt_audio_stream_qos(struct bt_conn *conn,
...
+			return err;
+		}
+	} else {
+		err = bt_audio_cig_reconfigure(group, qos);
+		if (err != 0) {
+			BT_DBG("bt_audio_cig_reconfigure failed: %d", err);
```
Comment (MariuszSkamra) [inline subsys/bluetooth/audio/stream.c:598]: ditto

**Review by MariuszSkamra — APPROVED** [review]
LGTM, minor suggestions only
