### PR TITLE
drivers: display: sdl: Ensure task thread is run once on init

### LINKED ISSUE #88818: display: Writing too fast to SDL display with native_sim causes display to stay blank forever
**Describe the bug**
Writing too fast to SDL display with native_sim causes display to stay blank forever.
This is not a issue on device with a normal display.

**To Reproduce**
Attached file contains a app that reproduces the bug.
Uncommenting the sleep at the start, or adding `display_blanking_on(display_device);` before set format fixes the bug (display goes black instead of staying blank forever)

**Expected behavior**
Display goes black without the sleep.

**Impact**
Annoyance, trap if unknown.

**Environment (please complete the following information):**

 - OS: Arch linux latest
 - Toolchain: Zephyr SDK 17.0 and native toolchain
 - Commit 3c2d2a6ee586f2d72d7dbb553c6fa9cecf2d6fb1

[zephyr_sdl_native_sim_race.tar.gz](https://github.com/user-attachments/files/19821908/zephyr_sdl_native_sim_race.tar.gz)

### PR DESCRIPTION
**Pull request by faxe1008**
Adds a yield after creating the display thread to ensure that the thread is run once, executing the SDL init.

Resolves #88818

### CODE REVIEW

**Review by JarmouniA — APPROVED** [review]

File: drivers/display/display_sdl.c [hunk 1]
```diff
@@ -169,6 +171,9 @@ static int sdl_display_init(const struct device *dev)
 			K_KERNEL_STACK_SIZEOF(disp_data->sdl_thread_stack),
 			sdl_task_thread, (void *)dev, NULL, NULL,
 			CONFIG_SDL_DISPLAY_THREAD_PRIORITY, 0, K_NO_WAIT);
+	k_yield();
```
Comment (pdgendt) [inline drivers/display/display_sdl.c:174]: Is this yield still needed if you wait for the semaphore?

Comment (faxe1008) [reply drivers/display/display_sdl.c]: Fair point, not needed anymore.

**Review by pdgendt — APPROVED** [review]

File: drivers/display/Kconfig.sdl [hunk 2]
```diff
@@ -90,7 +90,7 @@ config SDL_DISPLAY_TRANSPARENCY_GRID_CELL_COLOR_2
 
 config SDL_DISPLAY_THREAD_PRIORITY
 	int "SDL display thread priority"
-	default NUM_PREEMPT_PRIORITIES
+	default MAIN_THREAD_PRIORITY
```
Comment (Finomnis) [inline drivers/display/Kconfig.sdl:93]: Is this still needed then? I would assume the other change should be sufficient

**Comment by Finomnis** [comment]
Looks good to me, if that fixes 88818

**Review by JarmouniA — APPROVED** [review]

**Review by VynDragon — APPROVED** [review]
