### PR TITLE
Sc timer pwm period bug fix

### LINKED ISSUE #55284: driver: pwm: sctimer: duty_cycle breaks on period length change.
**Describe the bug**
If the period length of a pwm signal changes, the driver
will assume that a new signal is to be used and creates 
an offset of the original duty cycle by 10% from the 
side effect of calling SCTIMER_SetupPwm for a signal 
that is already setup.

Environment: 
OS; Windows 10
cmake: 3.26.0

**To Reproduce**

1. mkdir build
2. west build -p always -b lpcxpresso55s69_cpu0 zephyr/tests/drivers/pwm/pwm_api
3. west flash

**Expected behavior**
Duty Cycle runs at 50% ->100% -> 0% ->50% ->100% -> 0%

**Impact**
Tests will break if the order is swapped starting at a pwm freq and 
switching the signal to a lower freq due to the way SCTIMER_SetUpPwm
sets up the pwm timers.

### PR DESCRIPTION
**Pull request by EmilioCBen**
Bug fix for #55284

If a user were to test a pwm signal with the pwm_api test it will succeed, 
however, if they were to change to ordering of the test to allow the nanosecond
test to run before the generic cycles test, the user will notice an inconsistency in
the pwm duty_cycle, this PR address this issue by testing for a change in duty
cycle as well as a change in period length before the driver suggests to create a
new pwm channel.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/55284

### CODE REVIEW

File: tests/drivers/pwm/pwm_api/src/test_pwm.c [hunk 1]
```diff
@@ -159,4 +159,5 @@ ZTEST_USER(pwm_basic, test_pwm_cycle)
 	/* Period : Pulse (64000 : 0), unit (cycle). Voltage : 0V */
 	zassert_true(test_task(DEFAULT_PWM_PORT, DEFAULT_PERIOD_CYCLE,
 				0, UNIT_CYCLES) == TC_PASS, NULL);
+	k_sleep(K_MSEC(1000));
```
Comment (henrikbrixandersen) [inline tests/drivers/pwm/pwm_api/src/test_pwm.c:162]: I do not understand why this is needed. Please elaborate a bit.

**Review by henrikbrixandersen — CHANGES_REQUESTED** [review]

File: tests/drivers/pwm/pwm_api/src/test_pwm.c (hunk 1 above)
Comment (danieldegrasse) [reply tests/drivers/pwm/pwm_api/src/test_pwm.c:162]: I think the issue here is that with the new ZTEST framework, the `test_pwm_cycle` test will run, and directly afterwards the `test_pwm_nsec` test will run. Without this delay, the 0% duty cycle signal will only show up for a moment before the PWM signal is reconfigured to 50% duty cycle at the start of `test_pwm_nsec`

File: drivers/pwm/pwm_mcux_sctimer.c [hunk 2]
```diff
@@ -76,7 +76,8 @@ static int mcux_sctimer_pwm_set_cycles(const struct device *dev,
 		return 0;
 	}
 
-	if (period_cycles != data->period_cycles[channel]) {
+	if (period_cycles != data->period_cycles[channel] &&
+	    duty_cycle != data->channel[channel].dutyCyclePercent) {
```
Comment (decsny) [inline drivers/pwm/pwm_mcux_sctimer.c:80]: could you check for pulse cycles here instead and have one less struct field access and achieve the same effect?

Comment (decsny) [reply drivers/pwm/pwm_mcux_sctimer.c:80]: on second glance, I guess period cycles is stored in the data struct but not pulse cycles...

**Review by dleach02 — APPROVED** [review]

**Review by henrikbrixandersen — APPROVED** [review]
