### PR TITLE
Bluetooth: BAP: Broadcast Source: Update stream codec config data

### LINKED ISSUE #71125: LE Audio: BAP broadcast source does not store level 3 information in codec configuration
**Describe the bug**
When creating a BAP broadcast source with `bt_bap_broadcast_source_create`, only the subgroup information is stored in the streams when calling `broadcast_source_setup_stream`, and the remaining BIS specific information (where location is typically stored), is not stored in the `stream->codec_cfg`, which it should. 

**To Reproduce**
N/A

**Expected behavior**
Expect the `stream->codec_cfg` to contain the information for the specific stream, which is a union of the Level 2 (subgroup) and Level 3 (BIS) data in the BASE. 

**Impact**
Annoyance as it's harder to use the existing codec configuration helper functions. 

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: cd2c7874b95eed7505620534b4b216ef42b7ce2b

**Additional context**
This is a similar issue as was fixed for the broadcast sink in https://github.com/zephyrproject-rtos/zephyr/pull/69342

### PR DESCRIPTION
**Pull request by niym-ot**
When creating a BAP broadcast source with bt_bap_broadcast_source_create, only the subgroup information is stored in the streams and the remaining BIS specific information is not stored in the stream->codec_cfg, which it should.
Fix is to store bis specific information also in stream codec config.

Fixes #71125

### CODE REVIEW

**Review by Thalley — CHANGES_REQUESTED** [review]
This won't work :(

The code looks good, but it has the issue that the merged result is stored in the subgroup codec configuration struct. 

This means that if you have something like 
subgroup channel allocation = `LEFT | RIGHT`
and BIS 1 channel allocation = `LEFT` and BIS 2 channel allocation = `RIGHT`, then the codec_cfg struct first contains `LEFT | RIGHT`, but after the first call to `update_codec_cfg_data` it is now just `LEFT` (because it's just being overridden) and after the second call the value is just `RIGHT`. 

The sideeffect of this is that now the subgroup channel allocation is RIGHT (and not `LEFT | RIGHT` as requested by the application), but what's worse is that both BIS 1 and BIS 2 are simply pointing to the subgroups codec_cfg, which means that they are also both just `RIGHT`. 

If you look at the similar changes I did for the broadcast sink in https://github.com/zephyrproject-rtos/zephyr/pull/69342, then you'll notice that I had to allocate a `codec_cfg` struct per stream in the broadcast sink. I think we need to do the same here: i.e. we need to be able to store `codec_cfg` _per_ stream, which currently isn't possible as we only get 1 `codec_cfg` per subgroup. 

The upside of storing it in the broadcast source struct, besides being able to fix the problem, is that we can make the parameters immutable, i.e. the application does not need to store the `params` for the lifetime of the broadcast source, and can't accidentally modify them without using the proper APIs. 

For the next iteration of this PR, I also suggest to add testing of this behavior, i.e. verify that the values set by each stream in the parameters are the same as if you get it from the `stream->codec_cfg` pointer.

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 1]
```diff
@@ -643,13 +643,64 @@ static enum bt_bap_ep_state broadcast_source_get_state(struct bt_bap_broadcast_s
...
+	int err;
+
+	err = bt_audio_codec_cfg_set_val(codec_cfg, data->type, data->data, data->data_len);
+	if (err < 0) {
+		LOG_DBG("Failed to set type %u with len %u in codec_cfg: %d", data->type,
+			data->data_len, err);
+
+		return false;
+	}
+	return true;
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:658]:
```suggestion
	}
	
	return true;
```

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 2]
```diff
@@ -643,13 +643,64 @@ static enum bt_bap_ep_state broadcast_source_get_state(struct bt_bap_broadcast_s
...
+				codec_cfg->data_len + stream_param->data_len,
+				sizeof(codec_cfg->data));
+
+			return -ENOMEM;
+		}
+
+		memcpy(&codec_cfg->data[codec_cfg->data_len], stream_param->data,
+		       stream_param->data_len);
+	}
+	return 0;
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:693]:
```suggestion
	}
	
	return 0;
```

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 3]
```diff
@@ -643,13 +643,64 @@ static enum bt_bap_ep_state broadcast_source_get_state(struct bt_bap_broadcast_s
...
+		    sizeof(codec_cfg->data)) {
+			LOG_DBG("Could not store BIS and subgroup config in codec_cfg (%u > %u)",
+				codec_cfg->data_len + stream_param->data_len,
+				sizeof(codec_cfg->data));
+
+			return -ENOMEM;
+		}
+
+		memcpy(&codec_cfg->data[codec_cfg->data_len], stream_param->data,
+		       stream_param->data_len);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:691]: I see that this is also a bug in the broadcast sink: We are neither here (or in the broadcast sink) increasing `codec_cfg->data_len` after appending them

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 4]
```diff
@@ -711,12 +762,32 @@ int bt_bap_broadcast_source_create(struct bt_bap_broadcast_source_param *param,
...
 			stream = stream_param->stream;
 
+			#if CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE > 0
+				if (bis_count >= BROADCAST_STREAM_CNT) {
+					LOG_DBG("Stream count %d exceeded", bis_count);
+					return -ENOMEM;
+				}
+				codec_cfg = &source->bis[bis_count].codec_cfg;
+				memcpy(codec_cfg, subgroup_param->codec_cfg,
+								sizeof(struct bt_audio_codec_cfg));
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:778]: Indentation is off here

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 5]
```diff
@@ -711,12 +762,32 @@ int bt_bap_broadcast_source_create(struct bt_bap_broadcast_source_param *param,
...
+				err = update_codec_cfg_data(codec_cfg, stream_param);
+
+				if (err != 0) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:781]:
```suggestion
				err = update_codec_cfg_data(codec_cfg, stream_param);
				if (err != 0) {
```

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 6]
```diff
@@ -711,12 +762,32 @@ int bt_bap_broadcast_source_create(struct bt_bap_broadcast_source_param *param,
...
+					LOG_DBG("codec config update failed [%zu]: %d", i, err);
+					broadcast_source_cleanup(source);
+					return err;
+				}
+				bis_count++;
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:786]:
```suggestion
					
					return err;
				}
				
				bis_count++;
```

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 7]
```diff
@@ -870,6 +943,23 @@ int bt_bap_broadcast_source_reconfig(struct bt_bap_broadcast_source *source,
 
 			stream_param = &subgroup_param->params[j];
 			stream = stream_param->stream;
+			#if CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE > 0
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:946]:
```suggestion
			if (CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE > 0)
```

All the data inside of this seems to be available even when `CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE` so we can just use a regular `if`, right?

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 8]
```diff
@@ -643,13 +643,64 @@ static enum bt_bap_ep_state broadcast_source_get_state(struct bt_bap_broadcast_s
...
+			LOG_DBG("Could not store BIS and subgroup config in codec_cfg (%u > %u)",
+				codec_cfg->data_len + stream_param->data_len,
+				sizeof(codec_cfg->data));
+
+			return -ENOMEM;
+		}
+
+		memcpy(&codec_cfg->data[codec_cfg->data_len], stream_param->data,
+		       stream_param->data_len);
+	}
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:692]: We probably need to guard this with `#if CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE > 0` right?

File: subsys/bluetooth/audio/bap_endpoint.h [hunk 9]
```diff
@@ -93,6 +98,7 @@ struct bt_bap_broadcast_source {
 #if CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE > 0
 	/* The codec specific configured data for each stream in the subgroup */
 	struct bt_audio_broadcast_stream_data stream_data[BROADCAST_STREAM_CNT];
+	struct bt_bap_broadcast_source_bis bis[BROADCAST_STREAM_CNT];
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_endpoint.h:101]:
```suggestion
	/* The codec specific configured data for each stream in the subgroup */
	struct bt_audio_broadcast_stream_data stream_data[BROADCAST_STREAM_CNT];
	/* The complete codec specific configured data for each stream in the subgroup. This contains both the subgroup and the BIS-specific data for each stream. */
	struct bt_bap_broadcast_source_bis bis[BROADCAST_STREAM_CNT];
```

File: subsys/bluetooth/audio/bap_endpoint.h [hunk 10]
```diff
@@ -73,6 +73,11 @@ struct bt_audio_broadcast_stream_data {
 	/** Codec Specific Data */
 	uint8_t data[CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE];
 };
+
+struct bt_bap_broadcast_source_bis {
+	/** Bis specific codec config */
+	struct bt_audio_codec_cfg codec_cfg;
+};
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_endpoint.h:80]: Given that this struct only contains a single field, we could probably omit the struct and just use `struct bt_audio_codec_cfg` in the below array, right?

File: subsys/bluetooth/audio/bap_endpoint.h (hunk 9 above)
Comment (Thalley) [inline subsys/bluetooth/audio/bap_endpoint.h:101]: `bt_audio_codec_cfg` may still contain metadata even if `CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE` so it's incorrectly guarded

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c [hunk 11]
```diff
@@ -37,6 +42,121 @@ static struct bt_bap_lc3_preset preset_16_1_1 = BT_BAP_LC3_BROADCAST_PRESET_16_1
...
+		cnt += chan_allocation & 1U;
+		chan_allocation >>= 1;
+	}
+
+	return cnt;
+}
+
+static void validate_stream_codec_cfg(const struct bt_bap_stream *stream)
+{
+	struct bt_audio_codec_cfg *codec_cfg = stream->codec_cfg;
```
Comment (Thalley) [inline tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:59]:
```suggestion
	const struct bt_audio_codec_cfg *codec_cfg = stream->codec_cfg;
```

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c [hunk 12]
```diff
@@ -37,6 +42,121 @@ static struct bt_bap_lc3_preset preset_16_1_1 = BT_BAP_LC3_BROADCAST_PRESET_16_1
...
+
+	while (chan_allocation != 0) {
+		cnt += chan_allocation & 1U;
+		chan_allocation >>= 1;
+	}
+
+	return cnt;
+}
+
+static void validate_stream_codec_cfg(const struct bt_bap_stream *stream)
```
Comment (Thalley) [inline tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:57]: This should arguably have been a unit test, rather than a BSIM test, but if it's too much effort to move, it is OK to keep

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c [hunk 13]
```diff
@@ -282,8 +403,8 @@ static int setup_extended_adv(struct bt_bap_broadcast_source *source, struct bt_
 static void test_broadcast_source_reconfig(struct bt_bap_broadcast_source *source)
 {
 	uint8_t bis_codec_data[] = {
-		BT_AUDIO_CODEC_DATA(BT_AUDIO_CODEC_CFG_FREQ,
-				    BT_BYTES_LIST_LE16(BT_AUDIO_CODEC_CFG_FREQ_16KHZ)),
+		BT_AUDIO_CODEC_DATA(BT_AUDIO_CODEC_CFG_CHAN_ALLOC,
+				    BT_BYTES_LIST_LE32(BT_AUDIO_LOCATION_FRONT_LEFT)),
```
Comment (Thalley) [inline tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:407]: Given that the preset also puts the FRONT_LEFT in the subgroup, this perhaps isn't the best way of testing it, as it would pass either way.

The BIS specific data should set a value that is either not set in the subgroup, or set a different value of the same type.

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c [hunk 14]
```diff
@@ -37,6 +42,121 @@ static struct bt_bap_lc3_preset preset_16_1_1 = BT_BAP_LC3_BROADCAST_PRESET_16_1
...
+		if (freq < 0) {
+			FAIL("Invalid frequency value: %d (%d)\n", ret, freq);
+
+			return;
+		}
+	} else {
+		FAIL("Could not get frequency: %d\n", ret);
+
+		return;
+	}
```
Comment (Thalley) [inline tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:80]: This should not only verify that a value is set (it's set even without your change), but also that it's set to the expected value. 

This applies to (nearly?) all of your tests here.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 15]
```diff
@@ -726,12 +780,32 @@ int bt_bap_broadcast_source_create(struct bt_bap_broadcast_source_param *param,
...
+			if (CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE > 0) {
+				if (bis_count >= BROADCAST_STREAM_CNT) {
+					LOG_DBG("Stream count %d exceeded", bis_count);
+					return -ENOMEM;
+				}
+				codec_cfg = &source->codec_cfg[bis_count];
+				memcpy(codec_cfg, subgroup_param->codec_cfg,
+				       sizeof(struct bt_audio_codec_cfg));
+				err = update_codec_cfg_data(codec_cfg, stream_param);
+				if (err != 0) {
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:798]:
```suggestion
				}
				
				codec_cfg = &source->codec_cfg[bis_count];
				memcpy(codec_cfg, subgroup_param->codec_cfg,
				       sizeof(struct bt_audio_codec_cfg));
				       
				err = update_codec_cfg_data(codec_cfg, stream_param);
				if (err != 0) {
```
Suggest to add some "air" around code blocks

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 16]
```diff
@@ -885,6 +961,24 @@ int bt_bap_broadcast_source_reconfig(struct bt_bap_broadcast_source *source,
...
 			stream = stream_param->stream;
+			if (CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE > 0) {
+				if (bis_count >= BROADCAST_STREAM_CNT) {
+					LOG_DBG("Stream count %d exceeded", bis_count);
+					return -ENOMEM;
+				}
+				codec_cfg = &source->codec_cfg[bis_count];
+				memcpy(codec_cfg, subgroup_param->codec_cfg,
+				       sizeof(struct bt_audio_codec_cfg));
+				err = update_codec_cfg_data(codec_cfg, stream_param);
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:972]:
```suggestion
				}
				
				codec_cfg = &source->codec_cfg[bis_count];
				memcpy(codec_cfg, subgroup_param->codec_cfg,
				       sizeof(struct bt_audio_codec_cfg));
				       
				err = update_codec_cfg_data(codec_cfg, stream_param);
```

Ditto

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 17]
```diff
@@ -885,6 +961,24 @@ int bt_bap_broadcast_source_reconfig(struct bt_bap_broadcast_source *source,
...
+
+				if (err != 0) {
+					LOG_DBG("codec config update failed [%zu]: %d", i, err);
+					broadcast_source_cleanup(source);
+					return err;
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:977]:
```suggestion
					LOG_DBG("codec config update failed [%zu]: %d", i, err);
					return err;
```

We should not cleanup the broadcast source if reconfiguration fails

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 18]
```diff
@@ -885,6 +961,24 @@ int bt_bap_broadcast_source_reconfig(struct bt_bap_broadcast_source *source,
 
 			stream_param = &subgroup_param->params[j];
 			stream = stream_param->stream;
+			if (CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE > 0) {
+				if (bis_count >= BROADCAST_STREAM_CNT) {
+					LOG_DBG("Stream count %d exceeded", bis_count);
+					return -ENOMEM;
+				}
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:968]: We are not adding new BIS in this function. Suggest to remove all uses of `bis_count` in this function

File: subsys/bluetooth/audio/bap_broadcast_source.c [hunk 19]
```diff
@@ -789,6 +863,8 @@ int bt_bap_broadcast_source_reconfig(struct bt_bap_broadcast_source *source,
 	enum bt_bap_ep_state broadcast_state;
 	struct bt_audio_codec_qos *qos;
 	size_t subgroup_cnt;
+	uint8_t bis_count;
+	int err;
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_broadcast_source.c:867]: The scope of `err` can and should be reduced

File: subsys/bluetooth/audio/bap_endpoint.h [hunk 20]
```diff
@@ -82,6 +82,7 @@ struct bt_audio_broadcast_stream_data {
 	/** Codec Specific Data */
 	uint8_t data[CONFIG_BT_AUDIO_CODEC_CFG_MAX_DATA_SIZE];
 };
+
```
Comment (Thalley) [inline subsys/bluetooth/audio/bap_endpoint.h:85]:
```suggestion
```

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c [hunk 21]
```diff
@@ -50,9 +55,135 @@ static struct bt_bap_lc3_preset preset_16_2_1 = BT_BAP_LC3_BROADCAST_PRESET_16_2
...
+{
+	uint8_t cnt = 0U;
+
+	while (chan_allocation != 0) {
+		cnt += chan_allocation & 1U;
+		chan_allocation >>= 1;
+	}
+
+	return cnt;
+}
```
Comment (Thalley) [inline tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:76]: This can be removed and the use can be replaced by `bt_audio_get_chan_count`

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c [hunk 22]
```diff
@@ -50,9 +55,135 @@ static struct bt_bap_lc3_preset preset_16_2_1 = BT_BAP_LC3_BROADCAST_PRESET_16_2
...
+
+static void validate_stream_codec_cfg(const struct bt_bap_stream *stream)
+{
+	const struct bt_audio_codec_cfg *codec_cfg = stream->codec_cfg;
+	const struct bt_audio_codec_cfg *exp_codec_cfg = &preset_16_1_1.codec_cfg;
```
Comment (Thalley) [inline tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:81]: I'm not following this. 

The whole point of this change is that the stream->codec_cfg can be different from the `preset_16_1_1.codec_cfg` which is only applied to the subgroup. 

I strongly suggest that you attempt to write the test first and have it fail, and then apply your fix, and then verify that the test passes. 

I heavily assume that without your patch, this test still passes. 

This is again something that would have been much easier to verify as a unit test ;)

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c [hunk 23]
```diff
@@ -297,10 +425,6 @@ static int setup_extended_adv(struct bt_bap_broadcast_source *source, struct bt_
 
 static void test_broadcast_source_reconfig(struct bt_bap_broadcast_source *source)
 {
-	uint8_t bis_codec_data[] = {
-		BT_AUDIO_CODEC_DATA(BT_AUDIO_CODEC_CFG_FREQ,
-				    BT_BYTES_LIST_LE16(BT_AUDIO_CODEC_CFG_FREQ_16KHZ)),
-	};
```
Comment (Thalley) [inline tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:303]: It is imperative that you set BIS specific data. 

These should definitely not be removed.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c (hunk 22 above)
Comment (niym-ot) [reply tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:69]: As discussed, bis specific data is contained in bis_codec_data and contains only channel info (BT_AUDIO_LOCATION_FRONT_CENTER).  So channel info is verified to be bis specific data.

static uint8_t bis_codec_data[] = {
	BT_AUDIO_CODEC_DATA(BT_AUDIO_CODEC_CFG_CHAN_ALLOC,
			    BT_BYTES_LIST_LE32(BT_AUDIO_LOCATION_FRONT_CENTER)),
};

Rest of the codec data is the subgroup codec data which is preset_16_1_1.codec_cfg

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c (hunk 23 above)
Comment (niym-ot) [reply tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:303]: BIS specific data is moved as global variable

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c (hunk 12 above)
Comment (niym-ot) [reply tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:66]: updated the existing unit test

File: tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c (hunk 22 above)
Comment (Thalley) [reply tests/bsim/bluetooth/audio/src/bap_broadcast_source_test.c:69]: I think it's the naming that throws me off here. You are setting 
```
exp_codec_cfg = &preset_16_1_1.codec_cfg;
```
and the `preset_16_1_1` is what we use for the subgroups. 

We specifically do not expect the values of the subgroup, but rather the merged result of the subgroup and the BIS, and thus calling the subgroup's codec config for `exp_codec_cfg` does not sound right

**Review by Thalley — APPROVED** [review]
The implementation looks good and it's nice that it gets tested. 

There are a few outstanding comments, but nothing that absolutely needs to be fixed

**Review by larsgk — APPROVED** [review]
