### PR TITLE
sca: Fix undefined behavior during preprocessing

### LINKED ISSUE #92082: undefined behavior in preprocessor macro usage
### Describe the bug

It is undefined behavior to use preprocessor directives inside macro invocations.

Example output by Cppcheck:
```
zephyr/include/zephyr/kernel/internal/mm.h:119:0: error: failed to expand '__ASSERT', it is invalid to use a preprocessor directive as macro parameter [preprocessorErrorDirective]
#if CONFIG_SRAM_BASE_ADDRESS != 0
^
zephyr/include/zephyr/kernel/internal/mm.h:119:1: error: failed to expand '__ASSERT', it is invalid to use a preprocessor directive as macro parameter [preprocessorErrorDirective]
#if CONFIG_SRAM_BASE_ADDRESS != 0
^
```

And the related code in mm.h is:
```
	__ASSERT(
#if CONFIG_SRAM_BASE_ADDRESS != 0
		 (addr >= CONFIG_SRAM_BASE_ADDRESS) &&
#endif /* CONFIG_SRAM_BASE_ADDRESS != 0 */
#if (CONFIG_SRAM_BASE_ADDRESS + (CONFIG_SRAM_SIZE * 1024UL)) != 0
		 (addr < (CONFIG_SRAM_BASE_ADDRESS +
			  (CONFIG_SRAM_SIZE * 1024UL))),
#else
		 false,
#endif /* (CONFIG_SRAM_BASE_ADDRESS + (CONFIG_SRAM_SIZE * 1024UL)) != 0 */
		 "physical address 0x%lx not in RAM",
		 (unsigned long)addr);
```

Quote from the C Standard, 6.10.5, paragraph 11 (ISO/IEC 9899:2024):

> The sequence of preprocessing tokens bounded by the outside-most matching parentheses forms the list of arguments for the function-like macro. The individual arguments within the list are separated by comma preprocessing tokens, but comma preprocessing tokens between matching inner parentheses do not separate arguments. **If there are sequences of preprocessing tokens within the list of arguments that would otherwise act as preprocessing directives, the behavior is undefined.**

### Regression

- [ ] This is a regression.

### Steps to reproduce

Cppcheck command:
```
nice cppcheck --project=build/compile_commands.json --library=zephyr --include=build/zephyr/include/generated/zephyr/autoconf.h --include=gcc-macros.h -D__cppcheck__ --suppress="normalCheckLevel*"
```

### Relevant log output

```shell

```

### Impact

Not sure

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by danmar**
Fixes #92082 

According to the C standard it is undefined behavior to use preprocessor directives inside macro invocations.

Cppcheck stops when it see this UB with an error message, and so this change will improve Cppcheck analysis.

This is a refactoring to fix UB, no logical change is intended

Signed-off-by: Daniel Marjamäki <daniel.marjamaki@cppchecksolutions.com>

### CODE REVIEW

**Comment by danmar** [comment]
This is inspired by #80961

**Comment by danmar** [comment]
There are several possible approaches to solve these UBs so feel free to suggest better solutions.

**Comment by cfriedt** [comment]
@danmar - can you please file an issue (bug),  copy-paste the error message into your bug report into the appropriate section, and then link this PR to that issue?

**Comment by danmar** [comment]
> @danmar - can you please file an issue (bug), copy-paste the error message into your bug report into the appropriate section, and then link this PR to that issue?

Thanks! Done.

File: include/zephyr/kernel/internal/mm.h [hunk 1]
```diff
@@ -44,6 +44,25 @@
 #define K_MEM_VIRT_OFFSET	0
 #endif /* CONFIG_MMU */
 
+#if CONFIG_SRAM_BASE_ADDRESS != 0
```
Comment (danmar) [inline include/zephyr/kernel/internal/mm.h:47]: Question: Is CONFIG_SRAM_BASE_ADDRESS and CONFIG_SRAM_SIZE always defined? If so I personally don't see why we have the #if at all. I assume any compiler can optimize comparisons that are always true/false.
If they are not always defined then the #if conditions looks weird (to me as an outsider).

Comment (peter-mitsis) [reply include/zephyr/kernel/internal/mm.h:47]: @danmar - I expect the #if is because of code analysis tools such as Coverity. I have observed in the past that they will flag things like CONFIG_XYZ >= 0 is always true, or something like that.

**Review by peter-mitsis — APPROVED** [review]

File: include/zephyr/kernel/internal/mm.h (hunk 1 above)
Comment (danmar) [reply include/zephyr/kernel/internal/mm.h:47]: Ah I understand, so then it makes sense to me to have this `#if`

**Review by andyross — APPROVED** [review]

**Comment by kartben** [comment]
@danmar please align author commit with sign-off entry
e.g. ` git commit --amend --no-edit --author="Daniel Marjamaki <daniel.marjamaki@cppchecksolutions.com>"` (or the other way around fix sign-off entry if you want to use your gmail address)

Then force push -- existing approvals will be kept since you're only changing commit message.
Thanks!

**Comment by danmar** [comment]
@kartben ok thanks fixed. hope it's fine now.
