### PR TITLE
drivers: clock_control:  stm32f3: Enable PWR clock to access BDCR

### LINKED ISSUE #56449: LSE enable problem on STM32F302RC
**Describe the bug**
I am looking to use the internal RTC of STM32F302RC and run the `alarm` sample inside `drivers/counter`. I have a custom board with STM32F302RC with an external Low Speed lock (LSE) of 32.768 KHz. When I run the sample the main function does not get called. I put the program into debug mode and found that it hangs in the following line of `set_up_fixed_clock_sources` function in file `clock_stm32_ll_common.c`
```
		while (!LL_PWR_IsEnabledBkUpAccess()) {
			/* Wait for Backup domain access */
		}
```

Below is the device tree of my custom board with LSE and RTC enabled:
```
/dts-v1/;
#include <st/f3/stm32f302Xc.dtsi>
#include <st/f3/stm32f302r(b-c)tx-pinctrl.dtsi>

/ {
	model = "TSCB STM32F302RC board";
	compatible = "rdt,tscb-f302rc";
	chosen {
		zephyr,console = &usart1;
		zephyr,shell-uart = &usart1;
		zephyr,sram = &sram0;
		zephyr,flash = &flash0;
	};
};

&clk_lse {
	status = "okay";
};

&clk_hse {
	clock-frequency = <DT_FREQ_M(12)>;
	status = "okay";
};
&pll {
	prediv = <1>;
	mul = <4>;
	clocks = <&clk_hse>;
	status = "okay";
};
&rcc {
	clocks = <&pll>;
	clock-frequency = <DT_FREQ_M(48)>;
	ahb-prescaler = <1>;
	apb1-prescaler = <2>;
	apb2-prescaler = <1>;
};

&i2c1 {
	pinctrl-0 = <&i2c1_scl_pb6 &i2c1_sda_pb7>;
	pinctrl-names = "default";
	status = "okay";
	clock-frequency = <I2C_BITRATE_FAST>;
};

&usart1 {
	pinctrl-0 = <&usart1_tx_pc4 &usart1_rx_pc5>;
	pinctrl-names = "default";
	current-speed = <115200>;
	status = "okay";
};

&rtc {
	clocks = <&rcc STM32_CLOCK_BUS_APB1 0x10000000>,
		 <&rcc STM32_SRC_LSE RTC_SEL(1)>;
	status = "okay";
};

zephyr_udc0: &usb {
	pinctrl-0 = <&usb_dm_pa11 &usb_dp_pa12>;
	pinctrl-names = "default";
	status = "okay";
};
```

I have tested the board by running a STM32CubeMX generated code with the same clock settings. The code runs properly with RTC set and get date/time functions. So it is not an hardware issue.

I have also tested the `alarm` sample with LSI clock. It runs properly.

**Expected behavior**
The LSE should get initialized and the alarm sample should run properly.

**Impact**
Showstopper. My end application requires an RTC with backup.

**Logs and console output**
None

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - ToolchainL zephyr-sdk-0.15.2
 - Zephyr Version used: v3.3.0-rc2-44-g461a13c085

What might be the problem here?

Thanks

### PR DESCRIPTION
**Pull request by erwango**
BDCR could be required for LSE or RTC for instance. Enable it here as for now, no sophisticated PM handling is available on F3 series.

Fixes #56449

### CODE REVIEW

File: drivers/clock_control/clock_stm32f0_f3.c [hunk 1]
```diff
@@ -145,6 +145,10 @@ uint32_t get_pllout_frequency(void)
 void config_enable_default_clocks(void)
 {
 #ifndef CONFIG_SOC_SERIES_STM32F3X
+
+	/* Enable PWR clock, required to access BCDR */
+	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);
```
Comment (FRASTM) [inline drivers/clock_control/clock_stm32f0_f3.c:150]: PR says to enable the PWR clock of the stm32f3, but `#ifndef CONFIG_SOC_SERIES_STM32F3X` at line 147 wil prevent this.

Comment (erwango) [reply drivers/clock_control/clock_stm32f0_f3.c:150]: Copy/paste issue. Will fix, thanks !

**Review by gautierg-st — DISMISSED** [review]

**Review by FRASTM — DISMISSED** [review]
Please, Fix typo (comment, title) as the register is named **BDCR** for Domain Control Register

**Comment by erwango** [comment]
> Please, Fix typo (comment, title) as the register is named BDCR for Domain Control Register

Fixed, txs

**Review by gautierg-st — APPROVED** [review]

**Review by FRASTM — APPROVED** [review]

**Comment by katyo** [comment]
@erwango Seems stm32f0 have same problem. Could you fix f0 too?

File: drivers/clock_control/clock_stm32f0_f3.c [hunk 2]
```diff
@@ -150,6 +150,9 @@ void config_enable_default_clocks(void)
 	LL_APB1_GRP2_EnableClock(LL_APB1_GRP2_PERIPH_SYSCFG);
 #endif
 #else
+	/* Enable PWR clock, required to access BDCR */
+	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);
+
```
Comment (katyo) [inline drivers/clock_control/clock_stm32f0_f3.c:155]: I simply moved it to beginning of function to get it works with stm32f072 too.

Comment (erwango) [reply drivers/clock_control/clock_stm32f0_f3.c:155]: Thanks @katyo. Would you mind contributing your fix ?
