### PR TITLE
modem: hl7800: Fix DNS resolver for all address families

### LINKED ISSUE #54674: modem: hl7800: DNS resolver does not start for IPv6 only
If configured for IPv6 only operation the DNS resolver fails to start because it is always expecting an IPv4 address.

### PR DESCRIPTION
**Pull request by rerickson1**
Fix DNS resolver config for IPv6 only setup.
Check validity of the DNS addresses before trying to configure the resolver.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/54674

### CODE REVIEW

File: drivers/modem/hl7800.c [hunk 1]
```diff
@@ -1829,17 +1829,40 @@ static void dns_work_cb(struct k_work *work)
...
+		ictx.dns_v6_string,
 #endif
-						       NULL };
+#ifdef CONFIG_NET_IPV4
+		ictx.dns_v4_string,
+#endif
+		NULL};
+
+#ifdef CONFIG_NET_IPV6
+	if (IS_ENABLED(CONFIG_NET_IPV6)) {
```
Comment (jukkar) [inline drivers/modem/hl7800.c:1844]: Why double check, the other one can be removed, preferably the `#ifdef` one

File: drivers/modem/hl7800.c [hunk 2]
```diff
@@ -1829,17 +1829,40 @@ static void dns_work_cb(struct k_work *work)
...
+						 &temp_addr);
+		if (!valid_address && IS_ENABLED(CONFIG_NET_IPV4)) {
+			/* IPv6 DNS string is not valid, replace it with IPv4 address and recheck */
+			strncpy(ictx.dns_v6_string, ictx.dns_v4_string, strlen(ictx.dns_v4_string));
+			valid_address = net_ipaddr_parse(ictx.dns_v6_string,
+							 strlen(ictx.dns_v6_string), &temp_addr);
+		}
+	} else
+#endif
+	{
```
Comment (jukkar) [inline drivers/modem/hl7800.c:1855]: So IPv4 is always enabled or why there is no IPv4 check here? Asking because you have a proper check in added code above.

File: drivers/modem/hl7800.c (hunk 1 above)
Comment (rerickson1) [reply drivers/modem/hl7800.c:1844]: Need to leave the #ifdef one because `dns_v6_string` is not available if no `CONFIG_NET_IPV6`. I will clean this up.

**Review by jukkar — DISMISSED** [review]
LGTM

**Review by rlubos — DISMISSED** [review]

**Review by ycsin — DISMISSED** [review]

**Comment by rerickson1** [comment]
Rebased to fix CI...

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
