### PR TITLE
stm32: clock control: fix on H7 + style edit

### LINKED ISSUE #22363: drivers: clock_control: clock_stm32_ll_h7.c Move Power Configuration code
I don't know why the power configuration code is in clock_stm32_ll_h7.c file. (Line number: 219)
In case of stm32h753, there is no SMPS function, so this code causes an error.
> #ifdef CONFIG_CLOCK_STM32_SYSCLK_SRC_PLL 

In case of stm32h753, there is no SMPS function, so this code causes an error.

In addition, I wonder why there is power configuration code in the clock source file.

### PR DESCRIPTION
**Pull request by erwango**
soc: stm32h7: Move PWR init code in soc init function
    
  Move PWR init code out of clock control driver and
  put SMPS related function under SMPS condition as it
  is not supported by all soc variants of the series.
    
Fixes #22363

Additionally:
Rework CONFIG_CLOCK_STM32_HSE_BYPASS related code to make
this part of the code more readable.
    
Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by erwango** [comment]
@mkainy, can you check this is fixing your issue?

File: drivers/clock_control/clock_stm32_ll_common.c [hunk 1]
```diff
@@ -376,11 +378,11 @@ static int stm32_clock_control_init(struct device *dev)
 	/* Enable HSE if not enabled */
 	if (LL_RCC_HSE_IsReady() != 1) {
 		/* Check if need to enable HSE bypass feature or not */
-#ifdef CONFIG_CLOCK_STM32_HSE_BYPASS
-		LL_RCC_HSE_EnableBypass();
-#else
-		LL_RCC_HSE_DisableBypass();
-#endif /* CONFIG_CLOCK_STM32_HSE_BYPASS */
+		if (IS_ENABLED(CONFIG_CLOCK_STM32_HSE_BYPASS) {
```
Comment (mkainy) [inline drivers/clock_control/clock_stm32_ll_common.c]: ")" Is missing. It will cause a compile error.

Comment (erwango) [reply drivers/clock_control/clock_stm32_ll_common.c]: Thanks!

File: soc/arm/st_stm32/stm32h7/soc_m7.c [hunk 2]
```diff
@@ -85,6 +85,15 @@ static int stm32h7_init(struct device *arg)
 	/* At reset, system core clock is set to 64 MHz from HSI */
 	SystemCoreClock = 64000000;
 
+	/* Power Configuration */
+#if SMPS
```
Comment (mkainy) [inline soc/arm/st_stm32/stm32h7/soc_m7.c]: The compile result is shown below.
soc_m7.c: 89: 9: error: #if with no expression #if SMPS

**Comment by erwango** [comment]
@mkainy Issues should be fixed now. Can you check this is working?

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
Will wait to see if @mkainy is able to test this out.

**Comment by mkainy** [comment]
I have confirmed that the code is performing properly.
