### PR TITLE
Bluetooth: controller: Fix TxAdd setting in auxiliary PDU

### LINKED ISSUE #28090: bluetooth: build error with extended advertising
When extended advertising is enabled without `CONFIG_BT_CTLR_PRIVACY=y` the following build error is produced:

```
/mnt/devel/zp/zephyr/subsys/bluetooth/controller/ll_sw/ull_adv_aux.c: In function 'ull_adv_aux_hdr_set_clear':
/mnt/devel/zp/zephyr/subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:502:25: error: 'struct ll_adv_set' has no member named 'own_addr_type'
  502 |   sec_pdu->tx_addr = adv->own_addr_type & 0x1;
```

Unless using extended advertising features **requires** `BT_CTLR_PRIVACY` by specification this should be fixed.  (I really hope it isn't required, because my use case is sensor beacons that are well-served with the default id from FICR, and very poorly served by ids that change.)

Reproducing code at: https://github.com/pabigot/zephyr/tree/issue/28090

### PR DESCRIPTION
**Pull request by andrzej-kaczmarek**
This fixes https://github.com/zephyrproject-rtos/zephyr/issues/28090

When controller is built with extended advertising support but without
LL Privacy build fails due to issue with code that sets TxAdd in aux
PDU:
```
.../ll_sw/ull_adv_aux.c: In function 'ull_adv_aux_hdr_set_clear':
.../ll_sw/ull_adv_aux.c:502:25: error: 'struct ll_adv_set' has no member named 'own_addr_type'
  502 |   sec_pdu->tx_addr = adv->own_addr_type & 0x1;
      |
```
We need own_addr_type value if an advertising set with aux but without
AD is created since we cannot get TxAdd value from other PDU.

ull_adv_aux_hdr_set_clear() can now be called with a flag to explicitly
set AdvA field and pass own_addr_type in 'value' parameter. This allows
to set proper TxAdd when creating new advertising set.

On aux updates, we use TxAdd from other PDU:
- if primary PDU has AdvA, we use TxAdd from that PDU
- if previous secundary PDU has AdvA, we use TxAdd from that PDU
In other case we just return an unpsecified error since this should not
happen in any valid scenario.

### CODE REVIEW

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c [hunk 1]
```diff
@@ -485,21 +489,25 @@ uint8_t ull_adv_aux_hdr_set_clear(struct ll_adv_set *adv,
...
-		/* Prepare to add AdvA in secondary PDU */
-		sec_hdr->adv_addr = 1;
+	sec_hdr->adv_addr = 1;
+	if (sec_hdr_add_fields & ULL_ADV_PDU_HDR_FIELD_ADVA) {
+		uint8_t own_addr_type = *(uint8_t *)value;
 
-		/* NOTE: AdvA is filled at enable */
+		sec_pdu->tx_addr = own_addr_type & 0x1;
+	} else if (pri_hdr_prev.adv_addr) {
+		pri_dptr_prev += BDADDR_SIZE;
```
Comment (cvinayak) [inline subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:504]: Should `pri_dptr_prev`  be incremented when setting addr type explicitly? Are there possibilities that there was an address in primary PDU, and explicit addr type would be set?

**Review by cvinayak — CHANGES_REQUESTED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_adv_aux.c (hunk 1 above)
Comment (andrzej-kaczmarek) [reply subsys/bluetooth/controller/ll_sw/ull_adv_aux.c:504]: ah right. we can have AdvA in prev primary and set own addr explicitly if we set parameters to change set from nconn-nscan to e.g. nconn-scan. will fix.

**Review by cvinayak — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]
