### PR TITLE
usb: cdc_acm: TX memory and performance improvements. Avoid ZLP transfer

### LINKED ISSUE #21713: CDC ACM USB class issue with high transfer rate and ZLP
**Describe the bug**
This issue is possibly linked to the following two issues: https://github.com/zephyrproject-rtos/zephyr/issues/20987 and https://github.com/zephyrproject-rtos/zephyr/issues/20250

Using an NRF52840  when sending data from the device to host  above 10kb/s continuously  - After a short time the console will show error messages of the form of:
<pre>
<wrn> usb_device: Failed to write endpoint buffer 0x82
<wrn> usb_device: Failed to write endpoint buffer 0x82
</pre>
The speed needed varies and it seems also to be related to the state of the host USB stack, as a restart of host sometimes removes the symptoms for a small period of time. When the issue is triggered data is lost, and counting bytes sent on the devices vs bytes received on the host you can see a mismatch with fewer bytes received on the host than sent from the device. 

Using the same fix as in https://github.com/zephyrproject-rtos/zephyr/issues/20250 (disable ZLP) the issue disappears and data is transferred correctly without any warnings in the log.
<pre>
diff --git a/subsys/usb/class/cdc_acm.c b/subsys/usb/class/cdc_acm.c
index 3f7082374d..0a3bcf25a4 100644
--- a/subsys/usb/class/cdc_acm.c
+++ b/subsys/usb/class/cdc_acm.c
@@ -303,7 +303,7 @@ static void tx_work_handler(struct k_work *work)
        LOG_DBG("Got %d bytes from ringbuffer send to ep %x", len, ep);
-       usb_transfer(ep, dev_data->tx_buf, len, USB_TRANS_WRITE,
+       usb_transfer(ep, dev_data->tx_buf, len, USB_TRANS_WRITE | USB_TRANS_NO_ZLP,
                     cdc_acm_write_cb, dev_data);
 }
</pre>

**To Reproduce**
1. Build the CDC-ACM example for an NRF52840 board (samples/subsys/usb/cdc_acm)
2. Send incrementing data as fast as you are allowed and watch the log output for failed to write endpoint buffer warnings.
3. Count increment on receiving end and see gaps in the transferred data

**Expected behavior**
All data sent from device should be received on the host

**Impact**
Data loss is basically a showstopper for our use, as this functions as a bridge interface for incoming data over a different link.

**Environment (please complete the following information):**
- OS: Linux (Ubuntu 18.04) 
- Toolchain: Zephyr SDK 0.10.3
- Commit: Latest zephyr master (currently https://github.com/zephyrproject-rtos/zephyr/commit/85a08da966e3a2c4e9d3012bcfd4e54c24b6003f for cdc_acm.c)

**Additional context**
Maybe it's worth investigating if there is something wonky with the ZLP handling in the USB stack as this is the second class where disabling ZLP appears to fix an issue.

### PR DESCRIPTION
**Pull request by aurel32**
Currently the cdc_acm implementation send data to the USB stack by
chunks of USB MPS. This has 2 drawbacks:
- when more data than USB MPS has to be sent, each chunk needs 2 packets
  due to the need of an extra ZLP;
- a temporary buffer of size USB MPS is needed.

This patch improves the memory consumption and performances by passing
the ring buffer directly to the USB stack. It only has a small
performance degradation when the ring buffer wraps and less than USB MPS
has to be sent.

Fixes #21713.

Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
> Currently the cdc_acm implementation send data to the USB stack by
> chunks of USB MPS. This has 2 drawbacks:
> 
>     * when more data than USB MPS has to be sent, each chunk needs 2 packets
>       due to the need of an extra ZLP;
> 
>     *

This not precise, usb_transfer adds ZLP when transfer length is multiple or equal endpoint MPS.

**Comment by aurel32** [comment]
> > Currently the cdc_acm implementation send data to the USB stack by
> > chunks of USB MPS. This has 2 drawbacks:
> > ```
> > * when more data than USB MPS has to be sent, each chunk needs 2 packets
> >   due to the need of an extra ZLP;
> > 
> > *
> > ```
> 
> This not precise, usb_transfer adds ZLP when transfer length is multiple or equal endpoint MPS.

Yes, in that case the USB CDC ACM code makes sure that what is passed to usb_transfer is less or equal to endpoint MPS. That's why an extra ZLP is added.

**Review by jfischer-no — CHANGES_REQUESTED** [review]
Thanks. I suggest to tweak the commit message to point to the issue with temporary tx_buf.

```
At higher throughput, the cdc_acm implementation
pass the data to usb_transfer() by a chunk of IN endpoint MPS.
This has 2 drawbacks:
- each transfer needs 2 packets due to the need of an extra ZLP
- a temporary buffer of size USB MPS is needed.
```

**Comment by jfischer-phytec-iot** [comment]
@carlescufi @emob-nordic That also allow to remove transfer of ZLP by setting CONFIG_USB_CDC_ACM_RINGBUF_SIZE lower than MPS of the IN endpoint. @aurel32 You could also add `Resolves: #21713` to the commit message.

**Comment by carlescufi** [comment]
@emob-nordic and @jfischer-phytec-iot have you tested this on multiple platforms?

**Comment by jfischer-phytec-iot** [comment]
> @emob-nordic and @jfischer-phytec-iot have you tested this on multiple platforms?

No, but that should not depend on a platform. I will do some test on hardware I have.

**Comment by aurel32** [comment]
> @carlescufi @emob-nordic That also allow to remove transfer of ZLP by setting CONFIG_USB_CDC_ACM_RINGBUF_SIZE lower than MPS of the IN endpoint (#21713 issue). 

I am not sure it's a good idea given that CONFIG_USB_CDC_ACM_RINGBUF_SIZE is the shared between both OUT and IN endpoints, and the same way CONFIG_CDC_ACM_BULK_EP_MPS is shared between both. If the ring buffer is smaller than MPS, and if the host send packets bigger than the ring buffer, they'll get partially dropped before the application has the time to consume them.

**Comment by jfischer-phytec-iot** [comment]
> > @carlescufi @emob-nordic That also allow to remove transfer of ZLP by setting CONFIG_USB_CDC_ACM_RINGBUF_SIZE lower than MPS of the IN endpoint (#21713 issue).
> 
> I am not sure it's a good idea given that CONFIG_USB_CDC_ACM_RINGBUF_SIZE is the shared between both OUT and IN endpoints, and the same way CONFIG_CDC_ACM_BULK_EP_MPS is shared between both. If the ring buffer is smaller than MPS, and if the host send packets bigger than the ring buffer, they'll get partially dropped before the application has the time to consume them.

Right, missed that. We could split it in CONFIG_USB_CDC_ACM_RX_RINGBUF_SIZE and CONFIG_USB_CDC_ACM_TX_RINGBUF_SIZE.
CONFIG_CDC_ACM_BULK_EP_MPS or other *_EP_MPS is an other issue that should be cleaned up because for e.g. bulk EP it is either FS and 64 bytes or HS and 512 bytes. I started to look at the high speed but the driver fix for my test device is for two months in review.

**Comment by aurel32** [comment]
> @carlescufi @emob-nordic That also allow to remove transfer of ZLP by setting CONFIG_USB_CDC_ACM_RINGBUF_SIZE lower than MPS of the IN endpoint (#21713 issue). @aurel32 You could also add `Resolves: #21713` to the commit message?

As discussed this is not a working solution. Instead I have just added an additional commit that reduces the length of the transfer by one byte in case in case there is an exact multiple of IN endpoint MPS in the ring buffer. This has no impact on the performances as this is still able to transfer multiple chunks of IN endpoint MPS, the difference being that the two last packets are of size (MPS-1, 1) instead of (MPS, 0). It's even possible that during the USB transfer the ring buffer is filled with additional bytes.

**Comment by emob-nordic** [comment]
I will have a deeper look today and perform some tests.

File: subsys/usb/class/cdc_acm.c [hunk 1]
```diff
@@ -301,6 +301,18 @@ static void tx_work_handler(struct k_work *work)
...
 
+	/*
+	 * Send less data to avoid having to send a zero-length packet. When
+	 * send a zero-length packet, the host or the application running on
+	 * the host may believe that there is no more data to be received
+	 * (i.e. the transaction has completed), hence not triggering another
+	 * IN transaction, and thus preventing any more data to be sent from
+	 * Zephyr to the Host.
+	 */
+	if (!(len % CONFIG_CDC_ACM_BULK_EP_MPS)) {
```
Comment (jfischer-phytec-iot) [inline subsys/usb/class/cdc_acm.c]: I think `len` should be checked for zero.

File: subsys/usb/class/cdc_acm.c [hunk 2]
```diff
@@ -301,6 +301,18 @@ static void tx_work_handler(struct k_work *work)
 	len = ring_buf_get_claim(dev_data->tx_ringbuf, &data,
 				 CONFIG_USB_CDC_ACM_RINGBUF_SIZE);
 
+	/*
+	 * Send less data to avoid having to send a zero-length packet. When
```
Comment (jfischer-phytec-iot) [inline subsys/usb/class/cdc_acm.c]: I suggest to avoid word "send" here, one could believe that it is possible to send data to the host like over Ethernet or UART.

~~Send less data to avoid having to send a zero-length packet. When
send a zero-length packet, the host or t~~he application running on
the host may believe that there is no more data to be received
(i.e. the transaction has completed), hence not triggering another
~~IN transaction, and thus preventing any more data to be sent from
Zephyr to the Host.~~

Transfer less data to avoid zero-length packet. The application running on
the host may conclude that there is no more data to be received
(i.e. the transaction has completed), hence not triggering another
I/O Request Packet (IRP).

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: subsys/usb/class/cdc_acm.c (hunk 1 above)
Comment (aurel32) [reply subsys/usb/class/cdc_acm.c]: I don't think this could actually happen, but I agree it's better to be safe than sorry. However should we just return from this function if it happens? From what I understand calling usb_transfer() with a length of 0 will send a ZLP, which is what we want to avoid. Note that this problem is not introduced by this PR, it was there also in the original code.

Comment (jfischer-phytec-iot) [reply subsys/usb/class/cdc_acm.c]: I think it should just return if len == 0. Agree, the issue was already there but you patch escalate it a little :-)

**Comment by aurel32** [comment]
@jfischer-phytec-iot I have just pushed a new version which check for a zero length and update the comments following your suggestion.

All that said I wonder if we could also simply claim (CDC_ACM_BUFFER_SIZE - 1) bytes from the ring buffer to make the code simpler and avoid sending a ZLP. This is slightly less efficient but with a 64-byte MPS, that's at most a difference of 1.5%.

**Review by jfischer-no — APPROVED** [review]

**Comment by jfischer-phytec-iot** [comment]
> All that said I wonder if we could also simply claim (CDC_ACM_BUFFER_SIZE - 1) bytes from the ring buffer to make the code simpler and avoid sending a ZLP. This is slightly less efficient but with a 64-byte MPS, that's at most a difference of 1.5%.

I am against that, there is no voodoo, the code is simple enough.
Thanks for the patches.

**Review by eobalski — APPROVED** [review]
Works fine for me.

**Comment by carlescufi** [comment]
@aurel32 this is no longer a bugfix so it will need to wait until the 2.3 merge window is open.

**Comment by jfischer-phytec-iot** [comment]
> @aurel32 this is no longer a bugfix so it will need to wait until the 2.3 merge window is open.

@jhedberg  @carlescufi This resolves the issue #21713 and I would like to see it in 2.2

**Comment by jhedberg** [comment]
> @jhedberg @carlescufi This resolves the issue #21713 and I would like to see it in 2.2

We'd need to add the TSC label to it and add it to the "Pending TSC approval" column of https://github.com/zephyrproject-rtos/zephyr/projects/27 in that case. It will then be voted upon in today's TSC call.

**Review by nvlsianpu — APPROVED** [review]
Tested along with mcuboot recovery DFU via usb cdc acm which was affected (by https://github.com/zephyrproject-rtos/zephyr/issues/21713). Patch fixes the issue I had.

**Comment by jfischer-phytec-iot** [comment]
> Tested along with mcuboot recovery DFU via usb cdc acm which was affected (by #21713). Patch fixes the issue I had.

@nvlsianpu could you report this issue in #21713 and change the label back to a bug, please?

**Review by finikorg — APPROVED** [review]
LGTM

**Comment by carlescufi** [comment]
@jhedberg turns out this actually fixes a real bug in the CDC ACM class. Please merge as part of 2.2.
