### PR TITLE
sensor: adxl3xx: Move run-time ODR changes from cfg to data

### LINKED ISSUE #83853: ADXL sensor drivers attempt to modify config struct at run-time
**Describe the bug**
Drivers for ADXL345 and ADXL372 attempt to modify the config struct when setting ODR attribute:
- ADXL345: https://github.com/zephyrproject-rtos/zephyr/blob/99a63a776980f855493ceb99036a5974a2b68fb5/drivers/sensor/adi/adxl345/adxl345.c#L260
- ADXL372: https://github.com/zephyrproject-rtos/zephyr/blob/99a63a776980f855493ceb99036a5974a2b68fb5/drivers/sensor/adi/adxl372/adxl372.c#L578

Since config struct is constant, modifying it triggers a fault.

This is present since 4.0.0:
- ADXL345: https://github.com/zephyrproject-rtos/zephyr/pull/80004
- ADXL372: https://github.com/zephyrproject-rtos/zephyr/pull/78941

**To Reproduce**

Build `samples/drivers/sensor/accel_polling` with either of these sensors, and it will crash, since this sample sets the ODR.

**Expected behavior**
Config struct is not modified at run-time.

### PR DESCRIPTION
**Pull request by ubieda**
`cfg` struct is constant and attempting to modify it triggers a fault. Instead, moved to `data`.

Fixes #83853

### CODE REVIEW

**Review by teburd — DISMISSED** [review]

**Review by ttmut — DISMISSED** [review]

**Comment by ubieda** [comment]
I'll change this PR based on feedback obtained in the issue: https://github.com/zephyrproject-rtos/zephyr/issues/83853#issuecomment-2587181708

File: drivers/sensor/adi/adxl345/adxl345.c [hunk 1]
```diff
@@ -229,7 +229,7 @@ static int adxl345_attr_set_odr(const struct device *dev,
 				const struct sensor_value *val)
 {
 	enum adxl345_odr odr;
-	struct adxl345_dev_config *cfg = (struct adxl345_dev_config *)dev->config;
+	struct adxl345_dev_data *data = dev->data;
```
Comment (glenn-andrews) [inline drivers/sensor/adi/adxl345/adxl345.c:232]: Does this need an explicit cast to `adxl372_dev_data`?

**Review by glenn-andrews — DISMISSED** [review]

**Comment by ubieda** [comment]
Fixed a typo on the `adxl372_data` struct. Should pass now

**Review by glenn-andrews — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]
Thanks @ubieda !
