### PR TITLE
subsys: l2: Properly terminate LCP state at modem side when closing down

### LINKED ISSUE #41627: PPP_L2 does not properly terminate the modem state machine when going down.
In ppp_l2, when an ppp connection is started by ppp_enable(ctx,true), it calls ppp_lcp->open, in the function start_ppp. There is no such stop_ppp function that calls ppp_lcp->close when ppp_enable(ctx,false)

Unless the modem itself closes the the connection, the LCP layer will not properly terminate and the modem stays in the data mode instead of in command mode. A proper ppp_lcp->close sequence in combination with ppp_lcp->down could fix this.

In the current situation there is a mismatch between the LCP state machine and modem state machine after a connection down.

To reproduce:
Use the GSM_PPP and see the modem not responding to AT commands after shutting down the PPP connection.

I'll try to create proper fix.

### PR DESCRIPTION
**Pull request by ssharks**
Takes the modem state machine by calling lcp_close instead of lcp_down
Using this method the LCP layer sends a TERMINATE_REQ to the modem and the
network interface is only taken down when the LCP layer has properly finished.
Moved the ppp_mgmt_raise_carrier_off_event and net_if_carrier_down
to lcp.c to avoid breaking the interface.
Tested on a real modem.

Fixes: zephyrproject-rtos#41627

Signed-off-by: Sjors Hettinga <s.a.hettinga@gmail.com>

### CODE REVIEW

File: subsys/net/l2/ppp/lcp.c [hunk 1]
```diff
@@ -206,6 +206,11 @@ static void lcp_finished(struct ppp_fsm *fsm)
 					       lcp.fsm);
 
 	ppp_link_terminated(ctx);
+
+	// take the remainder down
```
Comment (jukkar) [inline subsys/net/l2/ppp/lcp.c:210]: We do not use // comments in zephyr

File: subsys/net/l2/ppp/lcp.c [hunk 2]
```diff
@@ -206,6 +206,11 @@ static void lcp_finished(struct ppp_fsm *fsm)
 					       lcp.fsm);
```
Comment (jukkar) [inline subsys/net/l2/ppp/lcp.c:206]: Minor nit about the commit subject, no need to mention literal `subsys` there,
just do `net: ppp: Properly .....`

File: subsys/net/l2/ppp/ppp_l2.c [hunk 3]
```diff
@@ -284,11 +284,18 @@ static void carrier_on_off(struct k_work *work)
 		ppp_mgmt_raise_carrier_on_event(ctx->iface);
 		net_if_up(ctx->iface);
 	} else {
-		ppp_lower_down(ctx);
-		ppp_change_phase(ctx, PPP_DEAD);
+		if (ppp_lcp) {
+			ppp_lcp->close(ctx, "Shutdown");
+			// signaling for the carrier off event is done from the LCP callback
```
Comment (jukkar) [inline subsys/net/l2/ppp/ppp_l2.c:289]: Please use /* */ comments

**Comment by ssharks** [comment]
@jukkar Thanks for your quick feedback on style, Is there a way to run the style check offline, apart from the CI toolchain?
Could you also check the change for contents and way of implementing?

**Comment by jukkar** [comment]
> Could you also check the change for contents and way of implementing?

The change looks okeyish, unfortunately I have no way to test it atm. Lets see what other reviewers have to say.

File: subsys/net/l2/ppp/ppp_l2.c [hunk 4]
```diff
@@ -284,11 +284,18 @@ static void carrier_on_off(struct k_work *work)
 		ppp_mgmt_raise_carrier_on_event(ctx->iface);
 		net_if_up(ctx->iface);
 	} else {
-		ppp_lower_down(ctx);
-		ppp_change_phase(ctx, PPP_DEAD);
+		if (ppp_lcp) {
+			ppp_lcp->close(ctx, "Shutdown");
+			/* signaling for the carrier off event is done from the LCP callback */
+		} else {
+			if (ppp_lcp) {
```
Comment (ycsin) [inline subsys/net/l2/ppp/ppp_l2.c:291]: I think it will never enter this? If `ppp_lcp` exists it would enter the first `if` @ L287

**Review by ycsin — CHANGES_REQUESTED** [review]
I'm not familiar with the actual `ppp` stuff, how can I test this on a real modem? What should I expect w/ or w/o this PR?

File: subsys/net/l2/ppp/ppp_l2.c (hunk 4 above)
Comment (ssharks) [reply subsys/net/l2/ppp/ppp_l2.c:291]: The previous path took the LCP state machine down, without sending an actual terminate to the modem. This left the LCP state machine in the opened state at the modem side. In my case (without gsm_mux) this prevented it from answering to AT commands after closing down the connection.
In the new situation, the lcp_close function is called instead of the lcp_down, which sends out a TERMINATE_REQ to the modem, which it has to respond to with an TERMINATE_ACK. As the code shown here is called from a workqueue, we cannot wait for the TERMINATE_ACK to arrive and the final closing statements have been moved to the used callback function lcp_finished.
In this new situation the statements ppp_mgmt_raise_carrier_off_event(ctx->iface); and net_if_carrier_down(ctx->iface); are just delayed until the LCP connection has properly been terminated. Calling net_if_carrier_down earlier would prevent sending out LCP messages and properly terminating.

Comment (ssharks) [reply subsys/net/l2/ppp/ppp_l2.c:291]: Reading it I see your point, will fix it

**Comment by ssharks** [comment]
The previous path took the LCP state machine down, without sending an actual terminate to the modem. This left the LCP state machine in the opened state at the modem side. In my case (without gsm_mux) this prevented it from answering to AT commands after closing down the connection. This is how I verified functionality.
In the new situation, the lcp_close function is called instead of the lcp_down, which sends out a TERMINATE_REQ to the modem, which it has to respond to with an TERMINATE_ACK. As the code shown here is called from a workqueue, we cannot wait for the TERMINATE_ACK to arrive and the final closing statements have been moved to the used callback function lcp_finished.
In this new situation the statements ppp_mgmt_raise_carrier_off_event(ctx->iface); and net_if_carrier_down(ctx->iface); are just delayed until the LCP connection has properly been terminated. Calling net_if_carrier_down earlier would prevent sending out LCP messages and properly terminating.

**Comment by ssharks** [comment]
A new rebase of main, to so some unrelated build issues

**Comment by ycsin** [comment]
@ssharks I applied the changes of this PR manually to the [branch that I'm using](https://github.com/ycsin/zephyr) and the [modem](https://github.com/ycsin/zephyr/blob/new_develop/drivers/modem/gsm_ppp.c) failed to start after the first start/stop cycle:

First cycle:
```
[00:00:04.740,000] <inf> hw_manager: Starting modem
[00:00:04.740,000] <wrn> hw_manager: Disallowed from sleep
[00:00:04.741,000] <wrn> hw_manager: Started modem
[00:00:04.741,000] <wrn> location: modem is on
[00:00:04.741,000] <wrn> location: Waiting GNSS to be configured
[00:00:08.741,000] <wrn> telemetry: Telemetry locked FOTA
[00:00:08.742,000] <inf> telemetry_mqtt: Start OK
[00:00:16.090,000] <wrn> modem_gsm: Modem AT RDY
[00:00:20.343,000] <wrn> modem_gsm: Auto starting gnss configuration in 20 seconds
[00:00:21.358,000] <inf> modem_gsm: PPP channel 2 connected to GSM_1
[00:00:21.557,000] <inf> modem_gsm: Manufacturer: Quectel
[00:00:21.615,000] <inf> modem_gsm: Model: EC21
[00:00:21.674,000] <inf> modem_gsm: Revision: EC21EFAR06A06M4G
[00:00:21.733,000] <inf> modem_gsm: IMSI: 502195708537997
[00:00:21.793,000] <inf> modem_gsm: ICCID: <log_strdup alloc failed>
[00:00:21.853,000] <inf> modem_gsm: IMEI: <log_strdup alloc failed>
[00:00:22.018,000] <inf> net_ppp: Initializing PPP to use GSM_1
[00:00:22.025,000] <inf> modem_gsm: AT channel 1 connected to GSM_2
[00:00:23.284,000] <inf> telemetry_mqtt: Network connected
[00:00:23.284,000] <inf> timesync: Network connected
[00:00:23.284,000] <wrn> fota: Locking FOTA
...
Firmware will do its thing, then `gsm_ppp_stop` and cut off power to the modem when it doesn't require modem anymore.
...
```

Second cycle
```
...
some events happened and firmware need modem to send data.
....
[00:06:29.593,000] <inf> hw_manager: Starting modem
[00:06:29.593,000] <wrn> hw_manager: Disallowed from sleep
[00:06:29.593,000] <wrn> hw_manager: Started modem
[00:06:29.593,000] <wrn> location: modem is on
[00:06:29.593,000] <wrn> location: Transitioning to LOCATION_WAIT_READY
[00:06:29.593,000] <wrn> location: Requesting iface uart
[00:06:29.594,000] <wrn> location: Waiting GNSS to be configured
[00:06:29.594,000] <inf> telemetry_mqtt: Start OK
[00:06:41.031,000] <wrn> modem_gsm: Modem AT RDY
[00:06:45.197,000] <wrn> modem_gsm: Auto starting gnss configuration in 20 seconds
[00:06:47.112,000] <inf> modem_gsm: PPP channel 2 connected to GSM_1
[00:06:49.114,000] <err> modem_gsm: AT returned -116, retrying...
[00:06:50.114,000] <inf> modem_gsm: PPP channel 2 connected to GSM_1
[00:06:52.116,000] <err> modem_gsm: AT returned -116, retrying...
[00:06:53.117,000] <inf> modem_gsm: PPP channel 2 connected to GSM_1
[00:06:55.119,000] <err> modem_gsm: AT returned -116, retrying...
[00:06:56.119,000] <inf> modem_gsm: PPP channel 2 connected to GSM_1
[00:06:58.121,000] <err> modem_gsm: AT returned -116, retrying...
[00:06:59.122,000] <inf> modem_gsm: PPP channel 2 connected to GSM_1
[00:07:01.124,000] <err> modem_gsm: AT returned -116, retrying...
[00:07:02.124,000] <inf> modem_gsm: PPP channel 2 connected to GSM_1
[00:07:04.126,000] <err> modem_gsm: AT returned -116, retrying...
[00:07:05.126,000] <inf> modem_gsm: PPP channel 2 connected to GSM_1
[00:07:07.128,000] <err> modem_gsm: AT returned -116, retrying...
[00:07:29.594,000] <wrn> location: GNSS took too long to be ready
[00:07:29.594,000] <wrn> location: Transitioning to LOCATION_WAIT_TRIGGER
[00:07:29.594,000] <wrn> location: Waiting for trigger
```

File: subsys/net/l2/ppp/ppp_l2.c [hunk 5]
```diff
@@ -284,11 +284,15 @@ static void carrier_on_off(struct k_work *work)
 		ppp_mgmt_raise_carrier_on_event(ctx->iface);
 		net_if_up(ctx->iface);
 	} else {
-		ppp_lower_down(ctx);
-		ppp_change_phase(ctx, PPP_DEAD);
+		if (ppp_lcp) {
```
Comment (ycsin) [inline subsys/net/l2/ppp/ppp_l2.c:287]: If I change this part to:

```c
		if (ppp_lcp) {
			ppp_lcp->close(ctx, "Shutdown");
			/* signaling for the carrier off event is done from the LCP callback */
		}
		ppp_change_phase(ctx, PPP_DEAD);

		ppp_mgmt_raise_carrier_off_event(ctx->iface);
		net_if_carrier_down(ctx->iface);
```

then the modem is able to start during the second cycle.

I added `NET_WARN("lcp_finished");` to `lcp_finished` but the line is not printed, maybe `lcp_finished` didn't run for some reason?

Comment (ssharks) [reply subsys/net/l2/ppp/ppp_l2.c:287]: Thanks for looking into it. The challenge is that I have a different implementation of the layers on higher level (proprietary legacy). This makes it slightly different in behavior.

The problem you are dealing with it that you shutdown the modem too early. So it did not have time to finish the sequence. This means that your GSM MUX is not switched properly back to AT mode and it will never respond to AT mode.
In my shutdown sequence I call the ppps_close function, then wait for a semaphore. This semaphore is being raised when the NET_EVENT_IF_DOWN event comes from the net_mgmt_event_callback. This is only triggered by the net_if_carrier_down(ctx->iface); being called in the lcp_finished function. This way you allow the state machine to properly finish the terminate sequence before cutting the power. This will even be reached when the number of retries is exhausted.

With respect to your last suggestion. This will cancel the effect of the new changes will be cancelled. The ppp_lcp->close will put the packet in the TX queue, but by the time the queue is being severed after this function, the interface has been shut down, so no packet will be send and you will probably bump into the line: NET_WARN("iface %p is down", iface); in net_if.c

It obviously needs some more work to work with the stock example. Due to COVID I have no access to HW and debugger today. If you could point me to an example from the examples folder I can try to make it work on my HW.

Comment (ycsin) [reply subsys/net/l2/ppp/ppp_l2.c:287]: Indeed I turned off my modem too quickly, as sometimes it doesn't reply to the shutdown command/restart itself after shut down.

I don't really have an example, but a simple way to test it:

pseudo code:
```c
while (true) {
        enable_modem_power();
        gsm_ppp_start();
        k_msleep(60000);
        gsm_ppp_stop();
        disable_modem_power();
        k_msleep(20000);
}

Comment (ssharks) [reply subsys/net/l2/ppp/ppp_l2.c:287]: Just looking at the gsm_ppp_stop function, I think to make it work properly a semaphore construction should be between, to wait for the interface to be properly closed off (NET_EVENT_IF_DOWN) event:

`net_if_l2(iface)->enable(iface, false);`

and 

```
if (IS_ENABLED(CONFIG_GSM_MUX)) {
		/* Lower mux_enabled flag to trigger re-sending AT+CMUX etc */
		gsm->mux_enabled = false;

		if (gsm->ppp_dev) {
			uart_mux_disable(gsm->ppp_dev);
		}
	}
```

The ->enable(iface, false) triggers the close, but the gsm->mux_enabled = false; needs to be delayed for the FSM to finish its termination.

This construction introduces a dependency between the GSM_PPP driver and the NET_MGMT_EVENT. But on the other hand it enables someone to use the GSM_PPP driver out of the box.
An alternative is to poll for the interface to go down.

Comment (jukkar) [reply subsys/net/l2/ppp/ppp_l2.c:287]: > The ->enable(iface, false) triggers the close, but the gsm->mux_enabled = false; needs to be delayed for the FSM to finish its termination.

Indeed, good catch. @ssharks would you be able to send a fix for this?

Comment (ssharks) [reply subsys/net/l2/ppp/ppp_l2.c:287]: I can give it a try. It will be earliest next week as I need some HW to test this. Next the GSM_PPP driver is quite device specific at the moment, so I need to adjust it to the device I have as well.

Do you want to have it in a separate commit, i.e. separate pull request or how to send in these separate but somewhat related changes.

**Comment by ssharks** [comment]
@jukkar Sorry for the mess, but the second pull request is submitted

**Comment by rlubos** [comment]
Any update on this? @ycsin is your -1 still applicable?

**Comment by ycsin** [comment]
> Any update on this? @ycsin is your -1 still applicable?

Looks ok code-wise, don't have something to test.

**Review by ycsin — APPROVED** [review]
Having applied #42046 to my 2.7.0 RC3 branch, my modem is now able to start/stop normally after the first cycle with this PR.

** I turn off power to my modem directly, I didn't test the functional part of this PR.

**Review by jukkar — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
