### PR TITLE
drivers: serial: fix potential overflow in fifo_fill and fifo_read

### LINKED ISSUE #80599: a overflow loop may happens when `uart_stm32_fifo_read_visitor` .
the type of uint8_t for `num_tx` may overflow while `size` can be over 256, if the freq of cpu is relative low and uart baudrate is high, it may be stuck. the problem also appears in at least `uart_stm32_fifo_fill`.

**Describe the bug**

in zephyr/drivers/serial/uart_stm32.c, one of the function uart_stm32_fifo_read_visitor is:
```c
static int uart_stm32_fifo_read_visitor(const struct device *dev, void *rx_data, const int size,
					fifo_read_fn read_fn)
{
	const struct uart_stm32_config *config = dev->config;
	USART_TypeDef *usart = config->usart;
	uint8_t num_rx = 0U;

	while ((size - num_rx > 0) && LL_USART_IsActiveFlag_RXNE(usart)) {
		/* RXNE flag will be cleared upon read from DR|RDR register */

		read_fn(usart, rx_data, num_rx);
		num_rx++;

		/* Clear overrun error flag */
		if (LL_USART_IsActiveFlag_ORE(usart)) {
			LL_USART_ClearFlag_ORE(usart);
			/*
			 * On stm32 F4X, F1X, and F2X, the RXNE flag is affected (cleared) by
			 * the uart_err_check function call (on errors flags clearing)
			 */
		}
	}

	return num_rx;
}

```
**To Reproduce**

just use the uart_stm32.

**Expected behavior**

the overflow may happens in `uart_stm32_fifo_read_visitor` then `rxdata` will be wrong, and it will also cause more loops for uart read if size is large than 255.

**Impact**

bad data in rxdata, or loop in fifo_read

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: arm-gcc-none-eabi

### PR DESCRIPTION
**Pull request by ken4647**
try to fix issue #80599 , a error of type transform(?) in serial drivers. For `fifo_read` it may cause wrong read data if parameter `size` is over 255, while endless looping for `fifo_fill`, if uart is running faster than cpu.

Fixes #80599

### CODE REVIEW

**Comment by ycsin** [comment]
The patch looks fine but the your commit message doesn't meet our contribution guideline and the CI is going to fail, please take a look at https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

Basically, you need something like this
```
drivers: serial: fix problem for a possible overflow in serial fifo_fill or fifo_read | <- this title is too long, max is 72 char, current is 86

commit message line 1                                                     | <- each line should be 75 chars or less
commit message line 2                                                     | <- each line should be 75 chars or less
..                                                                        | <- each line should be 75 chars or less
commit message line n                                                     | <- each line should be 75 chars or less

Signed-off-by: John Doe <john@doe.com>
```

**Comment by ken4647** [comment]
> drivers: serial: fix potential overflow in fifo_fill and fifo_read

Thanks, I didn't notice the length. I have re-push my commit with new legal commit message.

**Comment by jhedberg** [comment]
@ken4647 you still need an actual body to the commit message. You could just put the PR description there. In addition to that you also need a Signed-off-by line (`git commit` will auto-generate that for you when you pass `-s` to it).

**Comment by ken4647** [comment]
> @ken4647 you still need an actual body to the commit message. You could just put the PR description there. In addition to that you also need a Signed-off-by line (`git commit` will auto-generate that for you when you pass `-s` to it).

Sorry, I noticed it yet. I will read the guideline seriously to avoid the mistake.

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -824,7 +824,7 @@ static int uart_stm32_fifo_fill_visitor(const struct device *dev, const void *tx
 {
```
Comment (gautierg-st) [inline drivers/serial/uart_stm32.c:824]: The typedef `fifo_fill_fn` takes a `uint8_t` for third parameter, but that should also be changed by an `int`, that impacts the functions `fifo_fill_with_u8` and `fifo_fill_with_u16` as well.

File: drivers/serial/uart_stm32.c [hunk 2]
```diff
@@ -873,7 +873,7 @@ static int uart_stm32_fifo_read_visitor(const struct device *dev, void *rx_data,
...
```
Comment (gautierg-st) [inline drivers/serial/uart_stm32.c:873]: The typedef `fifo_read_fn` takes a `uint8_t` for third parameter, but that should also be changed by an `int`, that impacts the functions `fifo_read_with_u8` and `fifo_read_with_u16` as well.

**Review by gautierg-st — CHANGES_REQUESTED** [review]
For STM32, some other functions are also impacted by this change and should be updated.
Note that I only reviewed the STM32 driver.

File: drivers/serial/uart_stm32.c (hunk 2 above)
Comment (ken4647) [reply drivers/serial/uart_stm32.c:873]: I have checked all codes related to the 15 serial drivers. There is only STM32's serial driver that has such impacts, while others are use the variable `num_tx` or `num_rx`  only as local variable, without transferring them to other codes.

**Review by gautierg-st — DISMISSED** [review]
LGTM for STM32

**Comment by ken4647** [comment]
The latest push is to eliminate the notices from CI for meeting the clang-format.

**Review by jhedberg — APPROVED** [review]

**Review by gautierg-st — APPROVED** [review]

**Review by soburi — APPROVED** [review]
LGTM for renesas_ra_sci.

**Review by duynguyenxa — APPROVED** [review]
LGTM for drivers/serial/uart_renesas_ra8_sci_b.c.

**Review by decsny — APPROVED** [review]

**Comment by mmahadevan108** [comment]
@dcpleung , can you help review

**Review by dcpleung — APPROVED** [review]

**Review by nandojve — APPROVED** [review]

**Review by danieldegrasse — APPROVED** [review]
