### PR TITLE
VCS/MICS compile fixes

### LINKED ISSUE #37024: Compile error if we only use VCS without VOCS and AICS
**Describe the bug**
There will be compile error if we only enabled the VCS through
```
CONFIG_BT_VCS=y
CONFIG_BT_VCS_CLIENT=y
```

**To Reproduce**
We can use "zephyr/samples/bluetooth/peripheral_hr" for replicating the issue
1. Add following configs in the prj.conf
```
CONFIG_BT_AUDIO=y
CONFIG_BT_VCS=y
CONFIG_BT_VCS_CLIENT=y
```
2. Compile the project through west 
```
west build -b nrf5340dk_nrf5340_cpuapp -p
```
3. And then we will the see the error log like
```
In file included from /home/rick/zephyr/subsys/bluetooth/audio/vcs_client.c:13:
/home/rick/zephyr/subsys/bluetooth/audio/vcs_client.c: In function 'bt_vcs_client_cb_register':
/home/rick/zephyr/subsys/bluetooth/audio/vcs_client.c:790:23: error: 'struct bt_vocs_cb' has no member named 'discover'
  790 |    CHECKIF(cb->vocs_cb.discover) {
      |                       ^
/home/rick/zephyr/include/sys/check.h:22:6: note: in definition of macro 'CHECKIF'
   22 |  if (expr)
      |      ^~~~
/home/rick/zephyr/subsys/bluetooth/audio/vcs_client.c:794:15: error: 'struct bt_vocs_cb' has no member named 'discover'
  794 |    cb->vocs_cb.discover = vocs_discover_cb;
      |               ^
In file included from /home/rick/zephyr/subsys/bluetooth/audio/vcs_client.c:13:
/home/rick/zephyr/subsys/bluetooth/audio/vcs_client.c:813:23: error: 'struct bt_aics_cb' has no member named 'discover'
  813 |    CHECKIF(cb->aics_cb.discover) {
      |                       ^
/home/rick/zephyr/include/sys/check.h:22:6: note: in definition of macro 'CHECKIF'
   22 |  if (expr)
      |      ^~~~
/home/rick/zephyr/subsys/bluetooth/audio/vcs_client.c:817:15: error: 'struct bt_aics_cb' has no member named 'discover'
  817 |    cb->aics_cb.discover = aics_discover_cb;
      |               ^
```

**Expected behavior**
There should be no issue for using only VCS without enabling the AICS and VOCS, which is the default setting if we only enabled ```CONFIG_BT_VCS```  and ```CONFIG_BT_VCS_CLIENT```

**Impact**
We won't be able to use the minimal configuration for VCS which without VOCS and AICS.

**Environment (please complete the following information):**
 - OS: Linux 64bits
 - Toolchain: GNU Arm Embed 10.2.1
 - Commit SHA: f3d9808012d24885b9e4051981ca5d5afe2e7b4a

### PR DESCRIPTION
**Pull request by Thalley**
Fix a few issues with compiling the VCS or MICS client without the AICS or VOCS client. 

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/37024

### CODE REVIEW

File: subsys/bluetooth/audio/vcs_client.c [hunk 1]
```diff
@@ -783,51 +787,53 @@ int bt_vcs_client_cb_register(struct bt_vcs_cb *cb)
 {
 	int i, j;
```
Comment (rick1082) [inline subsys/bluetooth/audio/vcs_client.c:788]: We will get compile warning "unused variable" for ```i``` and ```j``` if ```CONFIG_BT_VCS_CLIENT_VOCS``` is not defined.

File: subsys/bluetooth/audio/vcs_client.c [hunk 2]
```diff
@@ -783,51 +787,53 @@ int bt_vcs_client_cb_register(struct bt_vcs_cb *cb)
...
-			CHECKIF(cb->aics_cb.discover) {
-				BT_ERR("AICS discover callback shall not be set");
-				return -EINVAL;
+			if (vocs != NULL) {
+				bt_vocs_client_cb_register(vocs, vocs_cb);
 			}
-			cb->aics_cb.discover = aics_discover_cb;
+		}
+	}
+#endif /* CONFIG_BT_VCS_CLIENT_AICS */
```
Comment (asbjornsabo) [inline subsys/bluetooth/audio/vcs_client.c:812]: Wrong comment - should be BT_VCS_CLIENT_VOCS

File: subsys/bluetooth/audio/vcs_client.c [hunk 3]
```diff
@@ -783,51 +787,53 @@ int bt_vcs_client_cb_register(struct bt_vcs_cb *cb)
...
+	for (i = 0; i < ARRAY_SIZE(vcs_insts); i++) {
+		for (j = 0; j < ARRAY_SIZE(vcs_insts[i].cli.aics); j++) {
+			struct bt_aics *aics = vcs_insts[i].cli.aics[j];
+
+			if (aics != NULL) {
+				bt_aics_client_cb_register(aics, aics_cb);
 			}
 		}
 	}
+#endif /* CONFIG_BT_VCS_CLIENT_VOCS */
```
Comment (asbjornsabo) [inline subsys/bluetooth/audio/vcs_client.c:836]: Also wrong comment - should be AICS

File: subsys/bluetooth/audio/vcs_internal.h [hunk 4]
```diff
@@ -73,13 +76,18 @@ struct bt_vcs_server {
 	struct bt_vocs *vocs_insts[CONFIG_BT_VCS_VOCS_INSTANCE_COUNT];
 	struct bt_aics *aics_insts[CONFIG_BT_VCS_AICS_INSTANCE_COUNT];
 };
+#endif /* CONFIG_BT_VCS_CLIENT */
```
Comment (asbjornsabo) [inline subsys/bluetooth/audio/vcs_internal.h:79]: Wrong comment

File: subsys/bluetooth/audio/vcs_internal.h [hunk 5]
```diff
@@ -73,13 +76,18 @@ struct bt_vcs_server {
...
 
 /* Struct used as a common type for the api */
 struct bt_vcs {
 	bool client_instance;
 	union {
+#if defined(CONFIG_BT_VCS)
 		struct bt_vcs_server srv;
+#endif /* CONFIG_BT_VCS_CLIENT */
```
Comment (asbjornsabo) [inline subsys/bluetooth/audio/vcs_internal.h:87]: Wrong comment

**Review by asbjornsabo — CHANGES_REQUESTED** [review]
Some #endif comments must be corrected.  Otherwise, it seems OK.
Good that the compile tests have been added again, they are there to catch exactly these things.

**Comment by Thalley** [comment]
@asbjornsabo I guess it should in theory be possible to check the `#if` guards comments in CI with a simple script :)

**Review by rick1082 — APPROVED** [review]
Confirmed the issue has been solved, tested with sample project with simple VCS/VCS client configuration.
Thank for the help Emil.

**Review by asbjornsabo — APPROVED** [review]
LGTM

File: tests/bluetooth/shell/testcase.yaml [hunk 6]
```diff
@@ -28,3 +28,86 @@ tests:
     extra_args: CONFIG_BT_PRIVACY=n
     platform_allow: native_posix
     tags: bluetooth
+
+# Bluetooth Audio Compile validation tests
```
Comment (sylvioalves) [inline tests/bluetooth/shell/testcase.yaml:32]: Isn't it missing tag value in all this tests?

Comment (Thalley) [reply tests/bluetooth/shell/testcase.yaml:32]: Probably. Let me add those in a PR

Comment (Thalley) [reply tests/bluetooth/shell/testcase.yaml:32]: @sylvioalves https://github.com/zephyrproject-rtos/zephyr/pull/37093
