### PR TITLE
boards: cavs15: change the signing command in flash.sh

### LINKED ISSUE #31684: intel_adsp_cavs15: Cannot download firmware of kernel testcases
**Describe the bug**
Use west to flash zephyr image on ADSP failed

**To Reproduce**
1. west build -b intel_adsp_cavs15 tests/kernel/thread
2. west sign -t rimage -p ../modules/audio/sof/zephyr/ext/rimage/build/rimage -D ../modules/audio/sof/zephyr/ext/rimage/config/ -- -k ../modules/audio/sof/keys/otc_private_key.pem
3. west flash /home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/flash.sh /home/ztest/work/sof/rimage/keys/otc_private_key.pem

**Expected behavior**
Firmware load successful

**Logs and console output**
[5/6] cd /home/ztest/work/zephyrproject/zephyr/build/zephyr/cmake/flash && /usr/local/bin/cmake -E echo

-- west flash: using runner misc-flasher
Signing using default key
Signing for board intel_adsp_cavs15
Signing for SOC target apl using apl.toml
Signing with tool /usr/local/bin/rimage
**FATAL ERROR: Configuration not found**
/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/fw_loader.py -f /home/ztest/work/zephyrproject/zephyr/build/zephyr/zephyr.ri
Start firmware downloading...
Open HDA device: /dev/hda
Reset DSP...
Firmware Status Register (0xFFFFFFFF)
   Boot:   0xFFFFFF (UNKNOWN)
   Wait:   0x0F (UNKNOWN)
   Module: 0x07
   Error:  0x01
   IPC CMD  : 0xFFFFFFFF
   IPC LEN  : 0xFFFFFFFF
Booting up DSP...
Firmware Status Register (0x05000001)
   Boot:   0x000001 (INIT_DONE)
   Wait:   0x05 (DMA_BUFFER_FULL)
   Module: 0x00
   Error:  0x00
Downloading firmware...
Traceback (most recent call last):
  File "/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/fw_loader.py", line 81, in <module>
    main()
  File "/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/fw_loader.py", line 63, in main
    fw_loader.download_firmware(args.firmware)
  File "/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/lib/loader.py", line 187, in download_firmware
    sd = self.load_firmware(fw_file)
  File "/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/lib/loader.py", line 174, in load_firmware
    sd.buf.copy(data, len(data))
  File "/home/ztest/work/zephyrproject/zephyr/boards/xtensa/intel_adsp_cavs15/tools/lib/stream_desc.py", line 41, in copy
    self.buf[:] = data[:]
ValueError: Can only assign sequence of same size

**Environment** (please complete the following information):
OS: Fedora28
Toolchain: Zephyr-sdk-0.12.1
Commit ID: fc03bd2b863d543bd9

### PR DESCRIPTION
**Pull request by KangJianX**
Fixed [#31684](https://github.com/zephyrproject-rtos/zephyr/issues/31684)

Change the command that signing with rimage by flash script after
commitID:b553166a has been merged, that patch add a new option -D for
specify configuration, so update the command of this script.

Signed-off-by: Jian Kang <jianx.kang@intel.com>

### CODE REVIEW

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh [hunk 1]
```diff
@@ -5,14 +5,16 @@
 BUILD=$1
 FIRMWARE=${BUILD}/zephyr/zephyr.ri
 FLASHER=${ZEPHYR_BASE}/boards/xtensa/intel_adsp_cavs15/tools/fw_loader.py
+CONFIGURATION=${ZEPHYR_BASE}/../modules/audio/sof/zephyr/ext/rimage/config
+RIMAGE=${ZEPHYR_BASE}/../modules/audio/sof/zephyr/ext/rimage/build/rimage
```
Comment (lyakh) [inline boards/xtensa/intel_adsp_cavs15/tools/flash.sh:9]: is rimage built there automatically? That seems strange - west only builds everything in a separate directory, as far as I understand?

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh [hunk 2]
```diff
@@ -5,14 +5,16 @@
 BUILD=$1
 FIRMWARE=${BUILD}/zephyr/zephyr.ri
 FLASHER=${ZEPHYR_BASE}/boards/xtensa/intel_adsp_cavs15/tools/fw_loader.py
+CONFIGURATION=${ZEPHYR_BASE}/../modules/audio/sof/zephyr/ext/rimage/config
```
Comment (lyakh) [inline boards/xtensa/intel_adsp_cavs15/tools/flash.sh:8]: previously somebody commented, that hard-coding module paths isn't a good idea. Not sure though whether this is a similar case too, or whether it would be acceptable here.

**Review by lyakh — COMMENTED** [review]
Thanks for fixing! At least adding the "-D" parameter seems correct. Just need to figure out what a correct way of specifying the path would be. As for using rimage from the checked out snapshot. That would be good in general, but I'm not sure whether rimage gets automatically built by west?

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh (hunk 1 above)
Comment (KangJianX) [reply boards/xtensa/intel_adsp_cavs15/tools/flash.sh:9]: rimage build is not automatically, need build and install by ourselves, then we can use twister to run kernel tests.

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh (hunk 2 above)
Comment (KangJianX) [reply boards/xtensa/intel_adsp_cavs15/tools/flash.sh:8]: Yes, maybe we can get config by command line. I will change it later.

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh (hunk 1 above)
Comment (lyakh) [reply boards/xtensa/intel_adsp_cavs15/tools/flash.sh:9]: @KangJianX but then CI cannot use it, can it?

Comment (KangJianX) [reply boards/xtensa/intel_adsp_cavs15/tools/flash.sh:8]: What is your means that CI cannot use it?

Comment (lyakh) [reply boards/xtensa/intel_adsp_cavs15/tools/flash.sh:8]: @KangJianX I mean would you program CI to build rimage additionally?

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh [hunk 3]
```diff
@@ -5,15 +5,16 @@
 BUILD=$1
 FIRMWARE=${BUILD}/zephyr/zephyr.ri
 FLASHER=${ZEPHYR_BASE}/boards/xtensa/intel_adsp_cavs15/tools/fw_loader.py
+RIMAGE=${ZEPHYR_BASE}/../modules/audio/sof/zephyr/ext/rimage/build/rimage
```
Comment (nashif) [inline boards/xtensa/intel_adsp_cavs15/tools/flash.sh:8]: Not sure how this script is called and when, it will be safer if you just define an environment variable pointing to the location of rimage (whether it is locally installed, or part of sof tree or the sof module) and then use it in this script and keep it flexible and simple. Or you could enhance the script to accept more arguments, including the rimage location.

**Review by nashif — CHANGES_REQUESTED** [review]

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh (hunk 3 above)
Comment (KangJianX) [reply boards/xtensa/intel_adsp_cavs15/tools/flash.sh:8]: OK, I will add more arguments

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh (hunk 1 above)
Comment (KangJianX) [reply boards/xtensa/intel_adsp_cavs15/tools/flash.sh:8]: No, I won't build it additionally

File: boards/xtensa/intel_adsp_cavs15/tools/flash.sh (hunk 3 above)
Comment (KangJianX) [reply boards/xtensa/intel_adsp_cavs15/tools/flash.sh:8]: This script is called by west flash or when we use twister to run multiple tests.

**Review by nashif — APPROVED** [review]

**Review by dcpleung — APPROVED** [review]

**Comment by KangJianX** [comment]
@nashif Hi Anas, can this be merged now?
