### PR TITLE
drivers: clock: stm32: Move the MSI init after the LSE init

### LINKED ISSUE #96849: STM32 clocks: wrong order of initialization MSI and LSE
### Describe the bug

According to the STM32 Reference Manual "RM0394 - STM32L41xxx/42xxx/43xxx/44xxx/45xxx/46xxx advanced Arm®-based 32-bit MCUs" the MSI PLL has to be enabled after the LSE has been enabled and is ready:

> Bit 2 MSIPLLEN: MSI clock PLL enable
   Set and cleared by software to enable/ disable the PLL part of the MSI clock source.
   MSIPLLEN must be enabled after LSE is enabled (LSEON enabled) and ready (LSERDY set
   by hardware).There is a hardware protection to avoid enabling MSIPLLEN if LSE is not
   ready.
   This bit is cleared by hardware when LSE is disabled (LSEON = 0) or when the Clock
   Security System on LSE detects a LSE failure (refer to RCC_CSR register).
   0: MSI PLL OFF
   1: MSI PLL ON

However the STM32 clock driver in Zephyr `clock_stm32_ll_common.c` initializes MSI (including enabling MSI PLL) before enabling LSE (see function `set_up_fixed_clock_sources`).

On our board this causes MSIPLL to stay disabled.  As additional information, we are using a 32 kHz TCXO instead of a crystal, and therefore have to bypass the LSE oscillator (set `LSEBYP` to 1).

### Regression

- [ ] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Impact

UART sends corrupt data which makes communication with external ICs difficult.

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by juickar**
Moved the MSI init after the LSE init to respect the initialization flow of the MSI PLL mode that need LSE to be enabled and ready
see the [RM0394 - STM32L41xxx/42xxx/43xxx/44xxx/45xxx/46xxx advanced Arm®-based 32-bit MCUs](https://www.st.com/resource/en/reference_manual/rm0394-stm32l41xxx42xxx43xxx44xxx45xxx46xxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf)
>Bit 2 MSIPLLEN: MSI clock PLL enable
Set and cleared by software to enable/ disable the PLL part of the MSI clock source.
MSIPLLEN must be enabled after LSE is enabled (LSEON enabled) and ready (LSERDY set
by hardware).There is a hardware protection to avoid enabling MSIPLLEN if LSE is not
ready.
This bit is cleared by hardware when LSE is disabled (LSEON = 0) or when the Clock
Security System on LSE detects a LSE failure (refer to RCC_CSR register).
0: MSI PLL OFF
1: MSI PLL ON

Also added a check before enabling PLL Mode for MSI by making sure LSE is ready.

Fixes #96849

### CODE REVIEW

File: drivers/clock_control/clock_stm32_ll_common.c [hunk 1]
```diff
@@ -1002,6 +971,41 @@ static void set_up_fixed_clock_sources(void)
...
+
+#if defined(CONFIG_SOC_SERIES_STM32L0X) || defined(CONFIG_SOC_SERIES_STM32L1X)
+		LL_RCC_MSI_SetRange(STM32_MSI_RANGE << RCC_ICSCR_MSIRANGE_Pos);
+#else
+		LL_RCC_MSI_SetRange(STM32_MSI_RANGE << RCC_CR_MSIRANGE_Pos);
+#endif /* CONFIG_SOC_SERIES_STM32L0X || CONFIG_SOC_SERIES_STM32L1X */
+
+#if STM32_MSI_PLL_MODE
+		/* Check for LSE to be ready since its mandatory for MSI PLL mode */
+		while (LL_RCC_LSE_IsReady() != 1) {
```
Comment (etienne-lms) [inline drivers/clock_control/clock_stm32_ll_common.c]: I guess this means `STM32_LSE_ENABLED` should be set. If so, a build error would be welcome (and in that case, this loop is already implemented above).

If some SoC support LSE not being enabled by Zephyr because handled from another core, when it makes sense to test it is enabled (and ready). But in that case, maybe need some kind of timeout here to not blindly wait endlessly here.

**Review by etienne-lms — COMMENTED** [review]
Nitpicking: could you end the description sentence in the commit message body with a period `.`?

File: drivers/clock_control/clock_stm32_ll_common.c (hunk 1 above)
Comment (juickar) [reply drivers/clock_control/clock_stm32_ll_common.c]: I removed the loop and added a build error instead

**Review by erwango — APPROVED** [review]

File: drivers/clock_control/clock_stm32_ll_common.c [hunk 2]
```diff
@@ -1002,6 +971,37 @@ static void set_up_fixed_clock_sources(void)
 		z_stm32_hsem_unlock(CFG_HW_RCC_SEMID);
 	}
 
+#if defined(STM32_MSI_ENABLED)
```
Comment (mathieuchopstm) [inline drivers/clock_control/clock_stm32_ll_common.c:974]: Nit: add a comment about MSI needing to come after LSE due to PLL

**Review by mathieuchopstm — APPROVED** [review]
Non-blocking:
