### PR TITLE
LE Audio: Shell: Improvements for lc3_audio_send_data

### LINKED ISSUE #59614: LE Audio: Audio shell stops sending when there's a lot of ACL traffic
**Describe the bug**
When the audio shell is sending audio data via the `bap start_sine` command and there is significant ACL traffic (e.g. doing some GATT operations), then the remote device stops receiving data, even though no errors are reports by the stack. 

**To Reproduce**
Using the audio shell:

On the peripheral do:
1. bt init
2. bap init
3. mpl init
4. bt advertise on
5. 
on the central do
1. bt init
2. bap init3. 
4. bt connect <peripheral>
5. bap discover
6. cap_initiator discover
7. cap_initiator unicast-start sources 0
9. bap start_sine

Which should show the central sending and the peripheral receiving. 
Sometimes when the central does `mcc discover_mcs` the RX on the peripheral stops working. The central can do `bap stop_sine` and `bap start_sine` which makes it work again, which indicates that the CIS still works, and probably indicate an issue in the `start_sine` implementation. 

**Expected behavior**
Expect the TX to continue working even if there is other ACL traffic. 

**Impact**
Annoyance

**Logs and console output**
N/A

**Environment (please complete the following information):**
 - Commit SHA or Version used: 69f7fd9cb2759b0b68b78285dcd31bcfa03babd0

**Additional context**
Found during UPF but easy to reproduce in a near-silent environment.

### PR DESCRIPTION
**Pull request by Thalley**
See individual commit messages

fixes https://github.com/zephyrproject-rtos/zephyr/issues/59614

### CODE REVIEW

**Review by larsgk — APPROVED** [review]

File: subsys/bluetooth/audio/shell/bap.c [hunk 1]
```diff
@@ -305,44 +317,63 @@ static void lc3_audio_send_data(struct k_work *work)
...
-		shell_info(ctx_shell, "[%zu]: TX LC3: %zu\n",
-				lc3_sdu_cnt, tx_sdu_len);
+		shell_info(ctx_shell, "[%zu]: TX LC3: %zu (seq_num %u)", lc3_sdu_cnt, tx_sdu_len,
+			   seq_num);
 	}
+
 	lc3_sdu_cnt++;
+
+	/* If we have more buffers available, we reschedule the workqueue item immediately to
+	 * trigger antother encode + TX, but without blocking this call for too long
```
Comment (kruithofa) [inline subsys/bluetooth/audio/shell/bap.c:356]:
```suggestion
	 * trigger another encode + TX, but without blocking this call for too long
```

File: subsys/bluetooth/audio/shell/bap.c [hunk 2]
```diff
@@ -142,34 +142,50 @@ static bool initialized;
...
 
 	delta_us = k_ticks_to_us_near64((uint64_t)delta_ticks);
-	seq_num_incr = delta_us / interval_us;
-	next_seq_num = (seq_num_incr + seq_num);
+	/* Calculate the sequence number by dividing the stream uptime by the SDU interval */
+	seq_num = (uint16_t)(delta_us / interval_us);
+
+	/* In the case that we call this multiple times, we need to account for any sequence numbers
+	 * already allocated and send to the controller. Ensuring that the next PSN is 1 higher than
+	 * the last we allocated (assuming that we it was actually sent to the controller).
```
Comment (kruithofa) [inline subsys/bluetooth/audio/shell/bap.c:167]:
```suggestion
	 * the last we allocated (assuming that it was actually sent to the controller).
```

File: subsys/bluetooth/audio/shell/bap.c [hunk 3]
```diff
@@ -142,34 +142,50 @@ static bool initialized;
...
+	delta_ticks = uptime_ticks - sh_stream->connected_at_ticks;
 
 	delta_us = k_ticks_to_us_near64((uint64_t)delta_ticks);
-	seq_num_incr = delta_us / interval_us;
-	next_seq_num = (seq_num_incr + seq_num);
+	/* Calculate the sequence number by dividing the stream uptime by the SDU interval */
+	seq_num = (uint16_t)(delta_us / interval_us);
+
+	/* In the case that we call this multiple times, we need to account for any sequence numbers
+	 * already allocated and send to the controller. Ensuring that the next PSN is 1 higher than
```
Comment (kruithofa) [inline subsys/bluetooth/audio/shell/bap.c:166]:
```suggestion
	 * already allocated and sent to the controller. Ensuring that the next PSN is 1 higher than
```

**Review by kruithofa — APPROVED** [review]
LGTM
