### PR TITLE
Bluetooth: Settings: Fix generated identity not persistently stored.

### LINKED ISSUE #17880: Unable to re-connect to privacy enabled peer when using stack generated Identity
Fix an issue where the generated identity was not permanantly stored.
This resulted in being unable to reconnect after bonding when using
privacy, since a new local IRK was generated on reboot.

Affects:
CONFIG_BT_PRIVACY=y
CONFIG_BT_SETTINGS=y
Application does not call `bt_id_create`.

1. west build -b nrf52840_pca10056 tests/bluetooth/shell
2. Attach 2 boards, and open 2 terminals
3. west flash (both boards)
4. Peripheral terminal
```
bt init
bt bondable on
bt oob # (copy addr)
bt advertise on
```
5 Central terminal
```
bt init
bt bondable on
bt advertise on
bt connect <addr>
bt security 2
# This will print identity resolved, copy identity address
```
6. Reset both boards
7. Peripheral terminal
```
bt init
bt advertise on
```
8. Central terminal
```
bt init
bt connect <identity addr>
```

**Expected behavior**
Reconnecting to a bonded peripheral using privacy should work with it's identity address

**Impact**
Unable to reconnect using privacy. 

**Workaround**
Application must call `bt_id_create`

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit: 20ccdab445

### PR DESCRIPTION
**Pull request by joerchan**
Fix an issue where the generated identity was not permanantly stored.
This resulted in being unable to reconnect after bonding when using
privacy, since a new local IRK was generated on reboot.

When settings is enabled the application is responsible for loading
identities and possible creating it's own identities.
When settings_load is called and no identities has been created or found
in persistent storage a new identity will be created.
Since bt init has not been finalized bt_id_create will not make a call
to bt_settings_save_id. So we need to make sure that this identity will
be stored.

Fixes: #17880

### CODE REVIEW

File: subsys/bluetooth/host/settings.c [hunk 1]
```diff
@@ -215,6 +215,12 @@ static int commit(void)
 			BT_ERR("Unable to setup an identity address");
 			return err;
 		}
+
+		/* Make sure that the identity automatically generated by
+		 * bt_setup_id_addr is saved to persistent storage.
+		 * This only applies if settings_load was called without any
+		 * active identities in RAM. */
+		bt_settings_save_id();
```
Comment (Vudentz) [inline subsys/bluetooth/host/settings.c]: I recall @jhedberg saying there was some specific order to do this properly, or perhaps I missing something.

Comment (carlescufi) [reply subsys/bluetooth/host/settings.c]: Yes, that’s the point. This is being done only when resuming the bt_enable() sequence through the app calling settings_load(). The issue was that the default ID created by the stack was not being saved, which makes it very hard for apps to use privacy.

**Review by carlescufi — APPROVED** [review]

**Comment by pdunaj** [comment]
ping @pdunaj , @MarekPieta

File: subsys/bluetooth/host/settings.c (hunk 1 above)
Comment (joerchan) [reply subsys/bluetooth/host/settings.c]: The order of calling bt_id_create is documented to have a specific order.
The problem is however when bt_id_create is not called at all.
This default behavior is not working as I would expect it to be.

Consider these scenarios.

1# 1 id created, not stored, id will be restored (except it is not stored)
```
bt_enable
bt_settings_load
```
2#  - 2 ids created, not stored, ids will not be restored
```
bt_id_create
bt_id_create
bt_enable
bt_settings_load
```
3#  2 ids created, not stored, ids will be restored (except they are not stored)
```
bt_enable
bt_id_create
bt_id_create
bt_settings_load
```
4# 3 ids created, stored, ids will be restored
```
bt_enable
bt_settings_load
bt_id_create
bt_id_create
```
 ---

The current diff will change:
1# 1 id created, stored, id will be restored
```
bt_enable
bt_settings_load
```

I'm also wondering if 3# should be changed. The documentation for bt_id_create says:
```
 *  However,
 *  the new identity will only be stored persistently in flash when this API
 *  is used after bt_enable().
```
So either we need to change this behaviour as well, or update the documentation.

Comment (Vudentz) [reply subsys/bluetooth/host/settings.c]: Yep, I can't think of any reasons not to store in case of #1, that would break the stored bonding if we change the id on the next reboot.

Comment (joerchan) [reply subsys/bluetooth/host/settings.c]: This would fix 3# as well:

```
                        BT_ERR("Unable to setup an identity address");
                        return err;
                }
+       }
 
-               /* Make sure that the identity automatically generated by
-                * bt_setup_id_addr is saved to persistent storage.
-                * This only applies if settings_load was called without any
-                * active identities in RAM. */
+       /* Make sure that the identities created by bt_id_create after
+        * bt_enable is saved to persistent storage. */
+       if (!atomic_test_bit(bt_dev.flags, BT_DEV_PRESET_ID)) {
                bt_settings_save_id();
        }

```

Comment (carlescufi) [reply subsys/bluetooth/host/settings.c]: +1 to this

**Comment by carlescufi** [comment]
@Vudentz @MarekPieta please double-check this before we merge it

**Review by MarekPieta — APPROVED** [review]
LGTM, only found typos in commit message: `permanantly` -> `permanently`, `it's` -> `its`

**Review by Vudentz — APPROVED** [review]
LGTM

**Comment by ioannisg** [comment]
@carlescufi

**Comment by joerchan** [comment]
> LGTM, only found typos in commit message: `permanantly` -> `permanently`, `it's` -> `its`

Fixed, thanks

**Review by jhedberg — APPROVED** [review]
