### PR TITLE
drivers: can: common: fix sample point calculations

### LINKED ISSUE #55919: drivers: can: sample point calculation issues
**Describe the bug**

The `update_sampling_pnt()` function in `drivers/can/can_common.c` fails to include the CAN sync segment of 1 Tq in TS2 calculation when TS1 is clamped to its minimum value.

Furthermore, the function attempts to distribute TS1 evenly between the propagation segment and phase segment 1, but assumes that the propagation segment and the phase segment 1 have equal maximum values (which indeed is the case for all in-tree CAN controllers, but not a requirement). This can lead to calculated timings violating the driver maximum allowed value for `phase_seg1`.

**Expected behavior**
CAN timing calculation must be correct and respect timing parameter range limits.

**Impact**
Wrong timing calculation resulting in wrong bitrates.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr SDK
 - Commit SHA: 3e7205876cb5145d6630a7d1bcaf09945009f9f3

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
- Always include the SYNC segment of 1 time quanta when calculating ts1 and ts2.
- Respect the range limits of phase_seg1 when attempting to distribute ts1 between prop_seg and phase_seg1. Even distribution may not be possible if the allowed ranges of prop_seg and phase_seg1 are not equal.

Fixes: #55919

### CODE REVIEW

**Comment by martinjaeger** [comment]
I'm trying to wrap my head around it, but I'm having a hard time to understand what `ts`, `ts1` and `ts2` mean exactly. Some more documentation/comments for these internal functions would really be helpful, IMO.

Do you think you could add some explanatory comments or rename the variables to something more obvious to help with proper review? As far as I can see, `TS`, `TS1` and `TS2` are not typical unambiguous names used for CAN bit timing calculations.

**Comment by henrikbrixandersen** [comment]
> I'm trying to wrap my head around it, but I'm having a hard time to understand what `ts`, `ts1` and `ts2` mean exactly. Some more documentation/comments for these internal functions would really be helpful, IMO.
> 
> Do you think you could add some explanatory comments or rename the variables to something more obvious to help with proper review? As far as I can see, `TS`, `TS1` and `TS2` are not typical unambiguous names used for CAN bit timing calculations.

A fair request - I was also a bit lost trying to debug it. I want to follow up general clean-up/documentation PR for `can_common.c` but I have added documentation and renaming of variables for `update_sampling_pnt()` here.

**Review by martinjaeger — DISMISSED** [review]
Thanks for the additional documentation. Now I can understand it and could not spot any mistake.

File: drivers/can/can_common.c [hunk 1]
```diff
@@ -105,9 +105,17 @@ static int update_sampling_pnt(uint32_t ts, uint32_t sp, struct can_timing *res,
...
 	}
 
+	res->phase_seg2 = ts2;
+
+	/* Attempt to distribute ts1 evenly between prop_seq and phase_seg1 */
 	res->prop_seg = CLAMP(ts1 / 2, min->prop_seg, max->prop_seg);
 	res->phase_seg1 = ts1 - res->prop_seg;
-	res->phase_seg2 = ts2;
+
+	if (res->phase_seg1 > max->phase_seg1) {
```
Comment (str4t0m) [inline drivers/can/can_common.c:144]: Theoretically if `phase_seg1` would have a min value greater than the min value of `prop_seg` it could still lead to an invalid result for `phase_seg1`.

**Review by str4t0m — COMMENTED** [review]
Thanks for these Fixes and improved documentation.

File: drivers/can/can_common.c (hunk 1 above)
Comment (henrikbrixandersen) [reply drivers/can/can_common.c:144]: @str4t0m You are right, thank you for spotting this. I had somehow convinced myself this check was already covered by the clamping of the propagation segment, but clearly it isn't. I have update the code to also check the minimum boundary of `phase_seg1`.

**Review by str4t0m — APPROVED** [review]

**Review by martinjaeger — APPROVED** [review]
