### PR TITLE
Bluetooth: host: l2cap deadlock fix

### LINKED ISSUE #34600: Bluetooth: L2CAP: Deadlock when there are no free buffers while transmitting on multiple channels
**Describe the bug**
Transmitting many large SDUs as quickly as possible on multiple L2CAP channels quickly fills a lot of buffers. When no more segments can be queued to be transmitted because there are no more free buffers, or there are no more credits for the channel, queuing of segments is stopped. Whenever a previously queued segment has been transmitted, or more credits are received, segments are again being queued for transmission. If there are still no free buffers, queuing of segments is stopped again right away. If this happens when all segments that have previously been queued on the channel have already been transmitted, and there are no more credits to receive, queuing of segments is stopped indefinitely. 

**Expected behavior**
Queuing of segments continues when there are free buffers available.

**Impact**
Annoyance.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain (e.g Zephyr SDK, ...)
 - https://github.com/nrfconnect/sdk-zephyr/commit/6a1d340b632ec62f5abfb2e0c3e54838bbfd086e

**Additional context**
It is possible to work around this by having a high enough number of buffers (CONFIG_BT_L2CAP_TX_BUF_COUNT or CONFIG_BT_CONN_TX_MAX) that there are always buffers available when queuing of segments is restarted.

### PR DESCRIPTION
**Pull request by jori-nordic**
This combination of commits fixes the symptoms seen in #34600.
It also adds an multilink l2cap test to stress the host in case other bugs like this crop up.

Fixes #34600.

A note on the test:
As it is a special usage of the l2cap CoC API, the stack will throw a lot of errors, this is expected. 
We might want to downgrade those errors (in the near future) to be less scary, as no actual data loss is happening.

Expected errors/warnings:
```
d_00: @00:01:54.482920  [00:01:54.482,910] <wrn> bt_l2cap: No credits to transmit packet
d_00: @00:01:54.518763  [00:01:54.518,737] <err> bt_conn: Unable to allocate TX context
d_00: @00:01:54.518763  [00:01:54.518,737] <wrn> bt_l2cap: Unable to send seg -105
```

### CODE REVIEW

**Comment by jori-nordic** [comment]
whoops looks like I forgot to review the test, it's still littered with commented code and is missing the new alloc_seg callback. Adding DNM until I fix it.

File: subsys/bluetooth/host/l2cap.c [hunk 1]
```diff
@@ -1971,12 +1971,11 @@ static int l2cap_chan_le_send(struct bt_l2cap_le_chan *ch,
 		BT_WARN("Unable to send seg %d", err);
 		atomic_inc(&ch->tx.credits);
 
-		/* If the segment is not the original buffer release it since it
-		 * won't be needed anymore.
+		/* Release the segment, even if it is the original buf. the
+		 * caller of this function already holds a reference to this
+		 * buffer and l2cap_chan_le_send will get called again.
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/l2cap.c:2001]: Do I understand correctly?: `l2cap_chan_create_seg` returns an owned reference, if any. `bt_l2cap_send_cb`, if successful, moves the reference, but otherwise not. So, when it was not successful, we must still move the reference (into `net_buf_unref`) to avoid leaking it.

File: subsys/bluetooth/host/l2cap.c [hunk 2]
```diff
@@ -2265,6 +2266,12 @@ static void l2cap_chan_send_credits(struct bt_l2cap_le_chan *chan,
 		credits = chan->rx.init_credits;
 	}
 
+	/* Don't send back more than the initial amount. */
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/l2cap.c:2294]: Why? Is it not allowed by spec? This looks to me like a band-aid solution for some other problem in the stack. Why does it happen that we try to `l2cap_chan_send_credits` more credits than we should?

Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:2294]: Think the stack has this assumption, even if it's not in writing anywhere.

File: include/zephyr/bluetooth/l2cap.h [hunk 3]
```diff
@@ -279,6 +279,18 @@ struct bt_l2cap_chan_ops {
...
 
+	/** @brief Channel alloc_seg callback
+	 *
+	 *  If this callback is provided the channel will use it to allocate
+	 *  buffers to store segments. This avoids wasting big SDU buffers with
+	 *  potentially much smaller PDUs.
+	 *
+	 *  @param chan The channel requesting a buffer.
+	 *
+	 *  @return Allocated buffer.
```
Comment (alwa-nordic) [inline include/zephyr/bluetooth/l2cap.h:290]: .."Or NULL to fallback on the SDU allocator."? Or is this behavior unintentional? If it's unintentional, we should log an error.

Comment (jori-nordic) [reply include/zephyr/bluetooth/l2cap.h:290]: behavior is unintentional, I think we should log an error.

File: tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/common.c [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+		LOG_ERR("bs_open_back_channel failed!");
+	}
+}
+
+/* Call it to make peer to proceed.*/
+void device_sync_send(void)
+{
+	uint8_t msg[1] = "S";
+
+	bs_bc_send_msg(0, msg, sizeof(msg));
```
Comment (alwa-nordic) [inline tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/common.c:53]: This should be `ch[0]` instead of `0`.

File: tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/common.c [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+{
+	uint peer = CENTRAL_ID;
+
+	if (device_nbr == CENTRAL_ID) {
+		peer = PERIPHERAL_ID;
+	}
+
+	uint dev_nbrs[BACK_CHANNELS] = {peer};
+	uint channel_nbrs[BACK_CHANNELS] = {0};
+	uint *ch = bs_open_back_channel(device_nbr, dev_nbrs, channel_nbrs, BACK_CHANNELS);
```
Comment (alwa-nordic) [inline tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/common.c:41]: Shouldn't `BACK_CHANNELS` just be `ARRAY_SIZE(channel_nbrs)`?

File: tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/common.c [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+	if (bst_result != Passed) {
+		FAIL("test failed (not passed after %i seconds)\n", WAIT_SECONDS);
+	}
+}
+
+/* Call in init functions*/
+void device_sync_init(uint device_nbr)
+{
+	uint peer = CENTRAL_ID;
+
```
Comment (alwa-nordic) [inline tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/common.c:34]: I think it would be great to have an explicit assert `device_nbr == CENTRAL_ID || device_nbr == PERIPHERAL_ID`.

File: tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/common.c (hunk 5 above)
Comment (jori-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/common.c:41]: no idea, originally this was the l2cap ecred test that I hacked until I stressed the system enough for the bug to manifest itself. I think I can do away with the backchannels entirely, just relying on stack callbacks. As i said in another comment, the code is still very hacky, so don't think it makes sense to review the test part right now.

File: tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/main_l2cap_stress.c [hunk 7]
```diff
@@ -0,0 +1,487 @@
...
+static struct bt_l2cap_server test_l2cap_server = {
+	.accept = server_accept_cb
+};
+
+static int l2cap_server_register(bt_security_t sec_level)
+{
+	test_l2cap_server.psm = 0;
+	test_l2cap_server.sec_level = sec_level;
+
+	__ASSERT_NO_MSG(bt_l2cap_server_register(&test_l2cap_server) == 0);
```
Comment (alwa-nordic) [inline tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/main_l2cap_stress.c:200]: Don't put side effects in assert macros. :O

Comment (alwa-nordic) [reply tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/main_l2cap_stress.c:200]: Preempt: The day will come when we need to run babelsim tests with assertions disabled. And somebody may be tempted to copy this code into their application. I think it's reasonable that the babelsim tests double as samples in addition to tests.

**Comment by carlescufi** [comment]
@Vudentz a review from you would be appreciated for this PR

File: subsys/bluetooth/host/l2cap.c [hunk 8]
```diff
@@ -1881,7 +1894,11 @@ static void l2cap_chan_sdu_sent(struct bt_conn *conn, void *user_data, int err)
 		cb(conn, cb_user_data, 0);
 	}
 
+	/* Resume the current channel */
 	l2cap_chan_tx_resume(BT_L2CAP_LE_CHAN(chan));
```
[the remark this answers is not in the document]
Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:1906]: yeah it's to prioritize the current channel, I'll add a comment.

**Review by jhedberg — DISMISSED** [review]

File: include/zephyr/bluetooth/l2cap.h (hunk 3 above)
Comment (jori-nordic) [reply include/zephyr/bluetooth/l2cap.h:290]: I moved the check into an assert, lemme know if you don't like it.

The behavior will be that without asserts enabled (which you shouldn't do bc of the stack relying on it), segments will be allocated from the global pdu pool.

File: tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/main.c [hunk 9]
```diff
@@ -0,0 +1,443 @@
...
+static struct bt_l2cap_server test_l2cap_server = {
+	.accept = server_accept_cb
+};
+
+static int l2cap_server_register(bt_security_t sec_level)
+{
+	test_l2cap_server.psm = 0;
+	test_l2cap_server.sec_level = sec_level;
+
+	__ASSERT_NO_MSG(bt_l2cap_server_register(&test_l2cap_server) == 0);
```
Comment (jhedberg) [inline tests/bluetooth/bsim_bt/bsim_test_l2cap_stress/src/main.c:203]: Nack from me as well. Doesn't really matter if you're doing this intentionally or not - asserts containing code with side-effects is just generally a bad (and potentially dangerous) habit, and we shouldn't have such code anywhere. You never know who's going to be looking at it and decide to copy it for some other purpose. Btw, `__ASSERT_EVAL()` might be convenient here (not 100% sure).

**Review by jhedberg — CHANGES_REQUESTED** [review]

**Review by Vudentz — DISMISSED** [review]
LGTM

File: include/zephyr/bluetooth/l2cap.h (hunk 3 above)
Comment (jori-nordic) [reply include/zephyr/bluetooth/l2cap.h:291]: no, it's in the right place:
@alwa-nordic was saying that I had undocumented behavior where if the allocator cb returns NULL, the segment would tentatively be allocated from the same pool as the SDU.
I decided to make it mandatory to return a valid buffer, added a line to this comment and added an assert to verify that.

I have already changed the line with the assert in the bsim test, that's the one you both had problems with.

**Review by jhedberg — DISMISSED** [review]

**Comment by jori-nordic** [comment]
Sorry for the force-pushing @jhedberg I just noticed the checkpatch warnings.

**Review by alwa-nordic — DISMISSED** [review]

**Comment by jhedberg** [comment]
@jori-nordic no worries, I'll approve agains once everything is green. There's still a failure due to missing commit message body in one of the commits.

File: subsys/bluetooth/host/l2cap.c (hunk 2 above)
Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:2302]: yeah initially, the fix was on the caller side. I decided to put it here to gate it at the very last point, just in case I missed something in one of the other calls. 
We can revisit later.

Comment (hermabe) [reply subsys/bluetooth/host/l2cap.c:2302]: Isn't the number of credits we can give limited by the number of buffers available? We don't get any more buffers than the initial amount, so this change makes sense to me. But I may be misunderstanding something.

Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:2302]: yes exactly, this is the assumption. In the zephyr stack, the credits are an image of the number of the receive buffers. If they get out of sync, you're in trouble.

I think in nordic's softdevice, it was on the application to send the credits (public api), so it allowed the app to process the buffers before deciding to accept more. it also allowed user error if they sent too much credits. I'm not sure but maybe the number of buffers were runtime-configurable, hence that API.

As I said, i think in zephyr that doesn't make sense, as the number of buffers is fixed at compile time.

File: subsys/bluetooth/host/l2cap.c [hunk 10]
```diff
@@ -1971,12 +2004,11 @@ static int l2cap_chan_le_send(struct bt_l2cap_le_chan *ch,
 		BT_WARN("Unable to send seg %d", err);
 		atomic_inc(&ch->tx.credits);
 
-		/* If the segment is not the original buffer release it since it
-		 * won't be needed anymore.
+		/* Release the segment, even if it is the original buf, as
+		 * buffer ownership is not transferred when bt_l2cap_send_cb
+		 * returns an error.
```
Comment (alwa-nordic) [inline subsys/bluetooth/host/l2cap.c:2009]: I think this comment is still unnecessarily hard to understand. I don't see the need to refer to the "original buf". "Original buf" does not have an obvious meaning to the casual reader in this context. Imagine being new to the code.

Is is not better to say simply "bt_l2cap_send_cb would have taken the ownership of the reference in seg if it was successful. But the call returned an error, so we must get rid of the reference here."?

We can append the following to explain what is meant by owning references: "If a variable owning a reference falls out of scope, it is considered the source of a leak." But I think that is common concept in programming, so it does not need to be repeated.

Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:2009]: yep wording was from the previous comment. "original buf" -> huge SDU buffer that was passed by ref to the l2cap send API.
I'll reword it.

**Review by jhedberg — APPROVED** [review]

File: subsys/bluetooth/host/l2cap.c (hunk 2 above)
Comment (alwa-nordic) [reply subsys/bluetooth/host/l2cap.c:2303]: So we are the losing sync between the number of free buffers and the credits we send?~ Does the limit added here prevent the desync? Or is the sync already lost, and we are patching the symptom; that is some code calling `l2cap_chan_send_credits` with more credits than it is possible to have?

Comment (jori-nordic) [reply subsys/bluetooth/host/l2cap.c:2303]: yeah this code prevents the desync. There is some code callign l2cap_chan_send_credits with more credits than it is possible to have, yes. I figured I'd have the check in one place rather than two (or just the orig. caller and possibly leave another bug in if I didn't gate it here).
I can rummage thru my commits to find out where I originally put the limit if you so prefer. But i want to leave that one too.

**Review by carlescufi — APPROVED** [review]
