### PR TITLE
drivers: udc_dwc2: add Espressif pre-enable and shutdown hooks

### LINKED ISSUE #96679: samples:subsys:usb:webusb: esp32s3 after enabling spi ram, device configuration is not supported
### Describe the bug

Use esp32s3 chip.

https://github.com/zephyrproject-rtos/zephyr/pull/85600

### Regression

- [ ] This is a regression.

### Steps to reproduce

Edit `prj.conf` add `CONFIG_ESP_SPIRAM=y` and `CONFIG_SPIRAM_MODE_OCT=y`

`west build -b esp32s3_devkitm/esp32s3/procpu samples/subsys/usb/webusb`

Flash: 

`west flash`

### Relevant log output

**Before successful**:

```shell

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x2b (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fc8f5d0,len:0x22b8
load:0x40374000,len:0xb5c0
SHA-256 comparison failed:
Calculated: 28564cddd6ee50ea1e047a9cab985194199fa26f82a67a1435e35748202e229b
Expected: 0000000040270000000000000000000000000000000000000000000000000000
Attempting to boot anyway...
entry 0x4037a3d8
I (61) soc_init: ESP Simple boot
I (61) soc_init: compile time Sep 28 2025 23:18:02
W (62) soc_init: Unicore bootloader
I (62) soc_init: chip revision: v0.2
I (64) flash_init: Boot SPI Speed : 80MHz
I (68) flash_init: SPI Mode       : DIO
I (71) flash_init: SPI Flash Size : 8MB
I (75) boot: DRAM       : lma=00000020h vma=3fc8f5d0h size=022b8h (  8888)
I (81) boot: IRAM       : lma=000022e0h vma=40374000h size=0b5c0h ( 46528)
I (87) boot: IRAM       : lma=0000d8b8h vma=00000000h size=02740h ( 10048)
I (93) boot: IRAM       : lma=00010000h vma=42000000h size=0a848h ( 43080)
I (99) boot: IRAM       : lma=0001a850h vma=00000000h size=057a8h ( 22440)
I (105) boot: IRAM      : lma=00020000h vma=3c010000h size=02778h ( 10104)
I (112) boot: IROM      : lma=00010000h vma=42000000h size=0A846h ( 43078) map
I (118) boot: DROM      : lma=00020000h vma=3c010000h size=02780h ( 10112) map
I (136) boot: libc heap size 331 kB.
I (136) spi_flash: detected chip: gd
I (136) spi_flash: flash io: dio
W (136) spi_flash: Detected size(16384k) larger than the size in the binary image header(8192k). Using the size in the binary image header.
*** Booting Zephyr OS build v4.2.0-4553-g7fc8051b0f4b ***
[00:00:00.206,000] <wrn> udc_dwc2: Experimental DMA enabled
[00:00:00.248,000] <inf> main: USBD message: Bus reset
[00:00:00.426,000] <inf> main: USBD message: Bus reset
[00:00:00.502,000] <inf> sfunc: Configuration enabled
[00:00:00.502,000] <inf> main: USBD message: New device configuration
```

**After adding `CONFIG_ESP_SPIRAM=y` and `CONFIG_SPIRAM_MODE_OCT=y`**  :

```shell
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x2b (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fc8ff20,len:0x28ec
load:0x40374000,len:0xbf10
SHA-256 comparison failed:
Calculated: fe65b42fd69e11643ba8811c334d17024cac06bce22163e25881dfd065e0cce1
Expected: 00000000c0170000000000000000000000000000000000000000000000000000
Attempting to boot anyway...
entry 0x4037a528
I (64) soc_init: ESP Simple boot
I (64) soc_init: compile time Sep 28 2025 22:51:39
W (64) soc_init: Unicore bootloader
I (64) soc_init: chip revision: v0.2
I (66) flash_init: Boot SPI Speed : 80MHz
I (70) flash_init: SPI Mode       : DIO
I (74) flash_init: SPI Flash Size : 8MB
I (77) boot: DRAM       : lma=00000020h vma=3fc8ff20h size=028ech ( 10476)
I (83) boot: IRAM       : lma=00002914h vma=40374000h size=0bf10h ( 48912)
I (89) boot: IRAM       : lma=0000e838h vma=00000000h size=017c0h (  6080)
I (95) boot: IRAM       : lma=00010000h vma=42000000h size=0c2c8h ( 49864)
I (101) boot: IRAM      : lma=0001c2d0h vma=00000000h size=03d28h ( 15656)
I (108) boot: IRAM      : lma=00020000h vma=3c010000h size=02c7ch ( 11388)
I (114) boot: IROM      : lma=00010000h vma=42000000h size=0C2C6h ( 49862) map
I (120) boot: DROM      : lma=00020000h vma=3c010000h size=02C80h ( 11392) map
I (138) boot: libc heap size 326 kB.
I (138) spi_flash: detected chip: gd
I (138) spi_flash: flash io: dio
W (139) spi_flash: Detected size(16384k) larger than the size in the binary image header(8192k). Using the size in the binary image header.
I (149) octal_psram: vendor id    : 0x0d (AP)
I (153) octal_psram: dev id       : 0x02 (generation 3)
I (158) octal_psram: density      : 0x03 (64 Mbit)
I (162) octal_psram: good-die     : 0x01 (Pass)
I (166) octal_psram: Latency      : 0x01 (Fixed)
I (171) octal_psram: VCC          : 0x01 (3V)
I (175) octal_psram: SRF          : 0x01 (Fast Refresh)
I (180) octal_psram: BurstType    : 0x01 (Hybrid Wrap)
I (185) octal_psram: BurstLen     : 0x01 (32 Byte)
I (190) octal_psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (194) octal_psram: DriveStrength: 0x00 (1/1)
I (199) esp_psram: Found 8MB PSRAM device
I (202) esp_psram: Speed: 40MHz
I (936) esp_psram: SPI SRAM memory test OK
*** Booting Zephyr OS build v4.2.0-4553-g7fc8051b0f4b ***
[00:00:00.988,000] <wrn> udc_dwc2: Experimental DMA enabled
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

OS: Debian
SHA: 7fc8051b0f4b4299034fb110f821adeba3445368

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sylvioalves**
Ensure the USB clock is enabled before initializing the controller by invoking the pre_enable hook. This avoids initialization failures when the HAL has not yet configured the clock.

Fixes #96679

### CODE REVIEW

File: drivers/usb/udc/udc_dwc2_vendor_quirks.h [hunk 1]
```diff
@@ -685,7 +698,7 @@ static inline int esp32_usb_otg_enable_phy(struct phy_context_t *phy_ctx, bool e
 	static void udc_dwc2_irq_disable_func_##n(const struct device *dev)	\
 	{									\
 		esp_intr_disable(usb_otg_data_##n.int_handle);			\
-	}
+	};
```
Comment (tmon-nordic) [inline drivers/usb/udc/udc_dwc2_vendor_quirks.h]: Unnecessary `;`.

**Review by tmon-nordic — DISMISSED** [review]

**Review by raffarost — DISMISSED** [review]

**Review by tmon-nordic — DISMISSED** [review]

File: drivers/usb/udc/udc_dwc2_vendor_quirks.h [hunk 2]
```diff
@@ -607,24 +607,31 @@ static inline int esp32_usb_otg_init(const struct device *dev,
...
 
+	return 0;
+}
+
+static inline int esp32_usb_otg_enable_phy(struct phy_context_t *phy_ctx, bool enable)
+{
+	LOG_MODULE_DECLARE(udc_dwc2, CONFIG_UDC_DRIVER_LOG_LEVEL);
+
+	if (enable) {
+		usb_wrap_ll_enable_bus_clock(true);
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_dwc2_vendor_quirks.h]: The clock should be already enabled, https://github.com/zephyrproject-rtos/zephyr/pull/96694/files#diff-116d6f0a75d0467a47da6bfbaff86c07149ea2abb045939f82cfab9a2bb35073R612. Why do you need to call it a second time?

Comment (sylvioalves) [reply drivers/usb/udc/udc_dwc2_vendor_quirks.h]: Make sense. Fixed.

**Review by tmon-nordic — DISMISSED** [review]

File: drivers/usb/udc/udc_dwc2_vendor_quirks.h [hunk 3]
```diff
@@ -607,24 +607,29 @@ static inline int esp32_usb_otg_init(const struct device *dev,
...
+
+static inline int esp32_usb_otg_enable_phy(struct phy_context_t *phy_ctx, bool enable)
+{
+	LOG_MODULE_DECLARE(udc_dwc2, CONFIG_UDC_DRIVER_LOG_LEVEL);
+
+	if (enable) {
+		usb_wrap_ll_phy_enable_pad(phy_ctx->wrap_hal.dev, true);
 		LOG_DBG("PHY enabled");
 	} else {
-		usb_wrap_ll_enable_bus_clock(false);
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_dwc2_vendor_quirks.h:625]: Is it intended to never turn off the clock? Maybe you want to use shutdown quirk to disable it.

**Comment by sylvioalves** [comment]
@jfischer-no adding the `shutdown` hook was indeed needed, thanks.
That allows performing `tests/driver/udc`.

**Comment by tmon-nordic** [comment]
nitpick: the driver is usb_dwc2 not usb_dw2

File: drivers/usb/udc/udc_dwc2_vendor_quirks.h [hunk 4]
```diff
@@ -607,30 +607,42 @@ static inline int esp32_usb_otg_init(const struct device *dev,
 	return ret;
 }
 
-static inline int esp32_usb_otg_enable_phy(struct phy_context_t *phy_ctx, bool enable)
+static inline int esp32_usb_otg_enable_clk(struct phy_context_t *phy_ctx)
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_dwc2_vendor_quirks.h:610]: Can you please update to commit title to
`drivers: udc_dwc2: add Espressif pre-enable and shutdown hooks`
and
`drivers: udc_dwc2: increase stack size for ESP32-S3`

Some people use `drivers: usb: udc_foo_bar:` but that is IMO too verbose.

**Review by tmon-nordic — APPROVED** [review]

**Comment by sylvioalves** [comment]
@jfischer-no can you proceed with this? thanks.

**Review by raffarost — APPROVED** [review]

**Comment by sylvioalves** [comment]
@jfischer-no This is target to v4.3.0, would you check again?

**Review by jfischer-no — APPROVED** [review]
