### PR TITLE
Bluetooth: Mesh: Extended advertiser should build without relay

### LINKED ISSUE #43172: CONFIG_BT_MESH_ADV_EXT doesn't build without CONFIG_BT_MESH_RELAY
**Describe the bug**

Bluetooth Mesh using Extended advertising seems to have an incorrect compile-time dependency on  relay support.

**To Reproduce**
```
west build -b nrf52840dk_nrf52840 zephyr/samples/hello_world \
    -DCONFIG_BT=y \
    -DCONFIG_BT_BROADCASTER=y \
    -DCONFIG_BT_OBSERVER=y \
    -DCONFIG_BT_MESH=y \
    -DCONFIG_BT_EXT_ADV=y \
    -DCONFIG_BT_CTLR_ADV_EXT=y
```
The above command results in the following compiler error on the v3.0.0 tag:

```
/tmp/zephyrproject/zephyr/subsys/bluetooth/mesh/adv_ext.c:83:34: error: 'CONFIG_BT_MESH_RELAY_ADV_SETS' undeclared here (not in a function); did you mean 'CONFIG_BT_MESH_ADV_EXT'?
   83 | #define BT_MESH_ADV_COUNT   (1 + CONFIG_BT_MESH_RELAY_ADV_SETS)
```

### PR DESCRIPTION
**Pull request by trond-snekvik**
The extended advertiser would fail to build due to a missing kconfig
option dependency when relay was disabled.

Fixes #43172.

Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

### CODE REVIEW

**Review by LingaoM — APPROVED** [review]

**Review by PavelVPV — APPROVED** [review]

File: subsys/bluetooth/mesh/adv_ext.c [hunk 1]
```diff
@@ -26,6 +26,10 @@
 /* Convert from ms to 0.625ms units */
 #define ADV_INT_FAST_MS    20
 
+#ifndef CONFIG_BT_MESH_RELAY_ADV_SETS
+#define CONFIG_BT_MESH_RELAY_ADV_SETS 0
```
Comment (PavelVPV) [inline subsys/bluetooth/mesh/adv_ext.c:30]: Minor. I remember that not everyone is happy when `CONFIG_...`-type macros are redefined.

**Comment by carlescufi** [comment]
@jhedberg ping

File: subsys/bluetooth/mesh/adv_ext.c (hunk 1 above)
Comment (trond-snekvik) [reply subsys/bluetooth/mesh/adv_ext.c:30]: I believe this is a common pattern for when the kconfig symbol is blocked by a `depends on`, but we still need it around to build the stack. See for instance https://github.com/zephyrproject-rtos/zephyr/blob/e2edb3e405b6e8158bab068736af2e916d157ebc/subsys/logging/log_backend_rtt.c#L14-L34

Comment (PavelVPV) [reply subsys/bluetooth/mesh/adv_ext.c:30]: I had the opposite experience 😄 
https://github.com/zephyrproject-rtos/zephyr/pull/33477#discussion_r599478755

**Review by jhedberg — APPROVED** [review]
