### PR TITLE
drivers: pwm: mcux_pwm: Flex pwm channel x output support

### LINKED ISSUE #102254: pwm: mcux: Assert in `blinky_pwm` sample
### Describe the bug

Running the `blinky_pwm` sample with `CONFIG_ASSERT=y` on `mimxrt1064_evk` results in assertion. The Zephyr shim driver fetches the source clock frequency (IPG set to 150 MHz) and passes this to the HAL driver.

A calculation is done to get the PWM period, which needs to fit in a `uint16_t`, and this is where the assertion comes from (as the resulting value is 1171800).

I already opened https://github.com/zephyrproject-rtos/zephyr/pull/102234 and https://github.com/zephyrproject-rtos/hal_nxp/pull/659 to convert the assert into an error result, but this doesn't fix the root cause, which is that the assertion/error can't ever be prevented?

### Regression

- [ ] This is a regression.

### Steps to reproduce

```shell
west build -p -b mimxrt1064_evk samples/basic/blinky_pwm -- -DCONFIG_ASSERT=y
```

### Relevant log output

```shell
[00:00:00.000,000] <dbg> pwm_mcux: pwm_mcux_init: Set prescaler 128, reload mode 2
*** Booting Zephyr OS build v4.3.0-3768-gdd76aa4402d5 ***
PWM-based blinky
Calibrating for channel 0...
[00:00:00.017,000] <err> pwm_mcux: Too long period (1171875), adjust pwm prescaler!
[00:00:00.025,000] <err> pwm_mcux: Too long period (585937), adjust pwm prescaler!
[00:00:00.034,000] <err> pwm_mcux: Too long period (292968), adjust pwm prescaler!
[00:00:00.042,000] <err> pwm_mcux: Too long period (146484), adjust pwm prescaler!
[00:00:00.050,000] <err> pwm_mcux: Too long period (73242), adjust pwm prescaler!
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/lib/libc/picolibc/assert.c:27
[00:00:00.064,000] <err> os: r0/a1:  0x00000004  r1/a2:  0x0000001b  r2/a3:  0x00000000
[00:00:00.073,000] <err> os: r3/a4:  0x00000004 r12/ip:  0x7000456d r14/lr:  0x70004561
[00:00:00.082,000] <err> os:  xpsr:  0x01000000
[00:00:00.087,000] <err> os: Faulting instruction address (r15/pc): 0x700080d0
[00:00:00.095,000] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[00:00:00.103,000] <err> os: Current thread: 0x800000d8 (unknown)
[00:00:00.109,000] <err> os: Halting system
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: Ubuntu 24.04
- Toolchain: Zephyr SDK 0.17.4
- Commit: dd76aa4402d5eaad4e47bcd715f99d39679e9348

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by FelixWang47831**
1. Support PWM channel X(channel 3), verified on evkmimxrt1180, all 3 channels for a PWM submodule with 3 different duty cycle

image

2.Enable pwmleds nodes and examples for mcx_n5xx_evk/mcxn547/cpu0

### CODE REVIEW

**Comment by FelixWang47831** [comment]
This PR also fix the issue #98396

File: drivers/pwm/pwm_mcux.c [hunk 1]
```diff
@@ -79,21 +78,43 @@ static int mcux_pwm_set_cycles_internal(const struct device *dev, uint32_t chann
...
 				      &data->channel[channel], 1U,
-				      config->mode, 1U, clock_freq);
+				      config->mode, pwm_clk_freq, data->clock_freq);
 		if (status != kStatus_Success) {
 			LOG_ERR("Could not set up pwm");
 			return -ENOTSUP;
 		}
 
+		if (channel == 2) {
+			/* For channel A, if counter matches VAL2 or VAL 3, it change output status.
```
Comment (yvesll) [inline drivers/pwm/pwm_mcux.c]:
```suggestion
			/* For channel A, if counter matches VAL2 or VAL3, the output status changes.
```

[the remark this answers is not in the document]
Comment (FelixWang47831) [reply drivers/pwm/pwm_mcux.c]: Fixed

File: drivers/pwm/pwm_mcux.c [hunk 2]
```diff
@@ -79,21 +78,43 @@ static int mcux_pwm_set_cycles_internal(const struct device *dev, uint32_t chann
...
+			 * The VAL2 is set to 0, so the channel output is high at the beginning of
+			 * the period, then becomes low when counter matches VAL3 (pulse width).
+			 * For channel X, only VAL0 is for pulse width, so we need to handle channel
+			 * X polarity specially.
```
[the remark this answers is not in the document]
Comment (FelixWang47831) [reply drivers/pwm/pwm_mcux.c]: Fixed

File: drivers/pwm/pwm_mcux.c [hunk 3]
```diff
@@ -79,21 +78,43 @@ static int mcux_pwm_set_cycles_internal(const struct device *dev, uint32_t chann
...
+				config->base->SM[config->index].OCTRL |=
+					((uint16_t)1U << PWM_OCTRL_POLX_SHIFT);
+			} else {
+				config->base->SM[config->index].OCTRL &=
+					~((uint16_t)1U << PWM_OCTRL_POLX_SHIFT);
+			}
+		} else if (data->period_cycles[2] != 0U) {
+			/* While setting channel A/B, VAL0 is changed by PWM_SetDutycycleRegister,
+			 * which is called by PWM_SetupPwm. VAL0 controls channel X pulse. So we
+			 * need to recover it.
```
[the remark this answers is not in the document]
Comment (FelixWang47831) [reply drivers/pwm/pwm_mcux.c]: Fixed.

File: drivers/pwm/pwm_mcux.c (hunk 1 above)
Comment (FelixWang47831) [reply drivers/pwm/pwm_mcux.c]: Fixed

File: drivers/pwm/pwm_mcux.c [hunk 4]
```diff
@@ -79,21 +78,43 @@ static int mcux_pwm_set_cycles_internal(const struct device *dev, uint32_t chann
...
+			 */
+			config->base->SM[config->index].VAL0 = data->pulse_cycles[2];
```
[the remark this answers is not in the document]
Comment (FelixWang47831) [reply drivers/pwm/pwm_mcux.c:143]: The judge condition (data->period_cycles[2] != 0U) indicates that channel 2 was previously configured. That's why we need to recovery pulse setting here when configure channel 0/1.

File: drivers/pwm/pwm_mcux.c [hunk 5]
```diff
@@ -79,21 +78,45 @@ static int mcux_pwm_set_cycles_internal(const struct device *dev, uint32_t chann
 		 */
 		data->channel[channel].dutyCyclePercent = 0;
 		data->channel[channel].level = level;
+		data->pulse_cycles[channel] = pulse_cycles;
 
 		status = PWM_SetupPwm(config->base, config->index,
 				      &data->channel[channel], 1U,
-				      config->mode, 1U, clock_freq);
+				      config->mode, pwm_clk_freq, data->clock_freq);
```
Comment (Holt-Sun) [inline drivers/pwm/pwm_mcux.c:116]: Please double check the 5th parameter. It seems to be pwm output frequency instead of PWM clock.

**Comment by Holt-Sun** [comment]
The second commit message says mcx_n5xx_evk, but code update is mcx_nx4x_evk

**Comment by FelixWang47831** [comment]
> The second commit message says mcx_n5xx_evk, but code update is mcx_nx4x_evk

Yes, mcx_n**x**4x_evk is a common file for mcx_n5xx_evk and mcx_n9xx_evk. These two boards share same LED pins.

File: drivers/pwm/pwm_mcux.c (hunk 5 above)
Comment (FelixWang47831) [reply drivers/pwm/pwm_mcux.c:116]: The 5th parameter is PWM signal frequency in Hz. It's a dummy data here. 
We just use PWM_SetupPwm to initialize the PWM submodule.
The real PWM period and pulse is set by PWM_SetVALxValue directly to fix this issue: https://github.com/zephyrproject-rtos/zephyr/issues/59080.

The 5th parameter is change to pwm_clk_freq to fix https://github.com/zephyrproject-rtos/zephyr/issues/98396
Because 1Hz might be to long for a 16 bit timer with high frequency, it might lead to assert error in PWM_SetupPwm : https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/mcux-sdk-ng/drivers/pwm/fsl_pwm.c#L541

**Review by Holt-Sun — DISMISSED** [review]

File: drivers/pwm/pwm_mcux.c [hunk 6]
```diff
@@ -19,7 +19,7 @@
 
 LOG_MODULE_REGISTER(pwm_mcux, CONFIG_PWM_LOG_LEVEL);
 
-#define CHANNEL_COUNT 2
+#define CHANNEL_COUNT 3
```
Comment (lucien-nxp) [inline drivers/pwm/pwm_mcux.c:26]: One question here: why we need to define a fixed number here? I think different platforms exist different count number, right? Can we add a parameter in dts/kconfig, and get the value dynamically from dts/kconfig could be better.

Comment (FelixWang47831) [reply drivers/pwm/pwm_mcux.c:26]: It's a hardware design not configurable
image

**Review by lucien-nxp — APPROVED** [review]

**Review by pdgendt — DISMISSED** [review]
Tested on i.MX RT1064 EVK and fixes https://github.com/zephyrproject-rtos/zephyr/issues/102254

**Comment by Holt-Sun** [comment]
Add @zejiang0jason as assignee since he is one of NXP base SDK drivers maintainers.

**Review by zejiang0jason — DISMISSED** [review]

**Review by yvesll — DISMISSED** [review]

**Comment by FelixWang47831** [comment]
Rebase to fix conflicts, please help to review, thanks.

**Review by pdgendt — APPROVED** [review]

**Review by yvesll — APPROVED** [review]

**Review by Holt-Sun — APPROVED** [review]

**Review by zejiang0jason — APPROVED** [review]
