### PR TITLE
Drivers: MCUX ADC16: Correct buffer size calculation for multi-channel read sequences

### LINKED ISSUE #98953: Drivers: MCUX ADC16 buffer overflow risk with multi-channel sequences and options
### Describe the bug

This issue reports a critical **buffer overflow** vulnerability in the `mcux_adc16` driver's read function when handling **multi-channel sequences** that use `adc_sequence.options` (for extra samplings or continuous conversions).

- **Validation Flaw:** The driver's internal buffer size validation logic erroneously calculated the required size by considering only a **single channel** multiplied by the total number of samplings: `sizeof(uint16_t) * (extra_samplings + 1)`.
  
- **Neglected Channels:** This calculation **failed to account for the total number of channels** enabled in the `adc_sequence.channels` bitmask.
  
- **Impact:** If a sequence included multiple channels, the validation would incorrectly pass, and the subsequent ADC data read would attempt to write more data than the validated size, leading to a **buffer overflow** in the user-provided buffer.
  

**Area:** Drivers, ADC, NXP, MCUX

### Regression

- [ ] This is a regression.

### Steps to reproduce

The bug is a logic error in buffer size calculation.

> **Write:**
> 
> 1. Build an application using the `mcux_adc16` driver (e.g., on an NXP platform).
>   
> 2. Configure an `adc_sequence` to include **multiple channels** (e.g., bits 0 and 1 set in `sequence.channels`).
>   
> 3. Set `sequence.options` to enable **extra samplings** (e.g., `sequence.options.extra_samplings = 1`).
>   
> 4. Call `adc_read()` with a buffer sized only for a single channel's total samples.
>   
> 5. The driver's validation will **incorrectly pass**, but the subsequent ADC transfer will overflow the buffer because the actual required size includes the total number of channels (which was neglected in the validation check). The fix involves using `POPCOUNT(sequence->channels)` for correct calculation.
>

### Relevant log output

```shell

```

### Impact

Not sure

### Environment

- **OS:** Windows WSL
  
- **Toolchain:** Zephyr SDK
  
- **Driver:** MCUX ADC16 Driver

### Additional Context

Additional Context: Fix Proposal is presented in the following PR: #98611

### PR DESCRIPTION
**Pull request by kaabia**
Fixes <https://github.com/zephyrproject-rtos/zephyr/issues/98953>

drivers: adc: mcux_adc16: Fix buffer size validation for multi-channel sequences

The mcux_adc16 driver's read function fails to correctly validate the user-provided buffer size when `adc_sequence.options` are used (i.e., for extra samplings or continuous conversions).

The validation calculation erroneously considered only the size required for a single channel multiplied by the total number of samplings: `sizeof(uint16_t) * (extra_samplings + 1)`.

This neglects the total number of channels enabled in `adc_sequence.channels`, leading to a **buffer overflow** if the sequence includes multiple channels.

Fix this by using `POPCOUNT(sequence->channels)` to determine the correct number of channels and ensuring the buffer size is sufficient for all requested samples.

### CODE REVIEW

File: drivers/adc/adc_mcux_adc16.c [hunk 1]
```diff
@@ -247,10 +249,25 @@ static int start_read(const struct device *dev,
 		return -EINVAL;
 	}
 
+	size_t min_buffer_size = channels_count * sizeof(uint16_t);
```
Comment (JarmouniA) [inline drivers/adc/adc_mcux_adc16.c]: all declarations/definitions shall be at the function's start.

**Comment by decsny** [comment]
To get bug fixes merged for 4.3 release, the PR needs to be linked to a bug report issue

File: drivers/adc/adc_mcux_adc16.c (hunk 1 above)
Comment (decsny) [reply drivers/adc/adc_mcux_adc16.c]: is this a written rule somewhere? never heard of it

**Comment by dleach02** [comment]
@kaabia you need to have a valid "sign-off" in the commit message per Zephyr requirements:

- https://docs.zephyrproject.org/latest/contribute/guidelines.html#dco-sign-off

File: drivers/adc/adc_mcux_adc16.c (hunk 1 above)
Comment (kaabia) [reply drivers/adc/adc_mcux_adc16.c]: Great catch! Thanks for the review.
@decsny, i think to maintain consistency with the existing code, let's stick to the established pattern for variable declarations/definitions here, as that seems to be the current practice.

Comment (JarmouniA) [reply drivers/adc/adc_mcux_adc16.c]: > is this a written rule somewhere? never heard of it

Seems to be the convention, but couldn't find an immediate reference in docs.

**Comment by kaabia** [comment]
> @kaabia you need to have a valid "sign-off" in the commit message per Zephyr requirements:
> 
> * https://docs.zephyrproject.org/latest/contribute/guidelines.html#dco-sign-off

Done :)

**Comment by dleach02** [comment]
@kaabia I'm assuming there isn't an existing test case in the zephyr test suite to test for the condition you found?

@hakehuang can we regression test this on [frdm_mcxc242, frdm_mcxc444, frdm_k64f]

**Comment by hakehuang** [comment]
> > @hakehuang can we regression test this on [frdm_mcxc242, frdm_mcxc444, frdm_k64f]
> 
> Hi @dleach02 As far as i know, there is no existing test case for this condition in zephyr test suite

@kaabia , the `sequence` is passed in in adc_sequences, and I test it with multichannel which is OK, see https://github.com/zephyrproject-rtos/zephyr/pull/95056/files#diff-84bbca3b29f13ffaec9824d0b2d0ba8b7928973d9b6bccfa235ac2d60dfee064
I enabled 4 channels for frdm_mcxc444
https://github.com/zephyrproject-rtos/zephyr/pull/95056/files#diff-e3b1fc6cf3f0ecada37aee5a207eb4fb06ad7f7bd291124fe336f45bf4956fbb 

and the fixes here is to add protection on boundary check, assume application pass in a wrong size?

**Review by dleach02 — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]
