### PR TITLE
bluetooth: tester: audio: Add verification for bis stopping

### LINKED ISSUE #73411: LE Audio: Tester: Broadcast too eager to reconfigure
**Describe the bug**
In tests like `BAP/BSRC/SCC/BV-34-C` PTS requests us to reconfigure the broadcast source. This is currently done by calling 
1) btp_bap_broadcast_adv_stop
2) btp_bap_broadcast_source_stop
3) btp_bap_broadcast_source_setup

The issue is that bttester assume that the broadcast source goes into the `BT_BAP_EP_STATE_QOS_CONFIGURED` state immediately after calling `btp_bap_broadcast_source_stop`, and thus it calls `btp_bap_broadcast_source_setup` as soon as possible. In reality, the broadcast source does not enter the `BT_BAP_EP_STATE_QOS_CONFIGURED` state until the `HCI_LE_Terminate_BIG_Complete` event has been received by the controller. 

This makes this, and other similar tests, subject to timing and may fail on other controllers than the Zephyr one. 

**To Reproduce**
1. Run the `BAP/BSRC/SCC/BV-34-C` test with AutoPTS with the Soft Device controller

**Expected behavior**
When `btp_bap_broadcast_source_stop` is called, it should wait for the `HCI_LE_Terminate_BIG_Complete` event, which triggers the ISO disconnected function which triggers the `btp_bap_broadcast:stream_stopped` function. We should not attempt to call `btp_bap_broadcast_source_setup` before that has been called. 

This can be solved either in the bttester itself, or in the python scripts that instruct the bttester (by adding a disconnected event similar to `btp_send_bis_syced_ev`). 

**Impact**
Prevents several tests from passing on non-Zephyr controllers. 

**Logs and console output**
See attached files
[BAP_BSRC_SCC_BV-34-C_2024_05_27_16_14_30.log](https://github.com/zephyrproject-rtos/zephyr/files/15470720/BAP_BSRC_SCC_BV-34-C_2024_05_27_16_14_30.log)
[autopts-iutctl-zephyr.log](https://github.com/zephyrproject-rtos/zephyr/files/15470721/autopts-iutctl-zephyr.log)
[BAP_BSRC_SCC_BV-34-C_iutctl.log](https://github.com/zephyrproject-rtos/zephyr/files/15470722/BAP_BSRC_SCC_BV-34-C_iutctl.log)

**Environment (please complete the following information):**
 - Commit SHA or Version used: 64de50f05235e5e681810510edbf8694e2b6a482

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Frodevan**
Adds a semaphor to make sure the stream has properly been stopped by the
controller before returning from btp_bap_broadcast_source_stop.

fixes: https://github.com/zephyrproject-rtos/zephyr/issues/73411

### CODE REVIEW

File: tests/bluetooth/tester/src/audio/btp/btp_bap.h [hunk 1]
```diff
@@ -274,3 +274,11 @@ struct btp_bap_pa_sync_req_ev {
 	uint8_t past_avail;
 	uint16_t pa_interval;
 } __packed;
+
+#define BTP_BAP_EV_BIS_STOPPED			0x8b
+struct btp_bap_bis_stopped_ev {
+	bt_addr_le_t address;
+	uint8_t broadcast_id[BT_AUDIO_BROADCAST_ID_SIZE];
+	uint8_t bis_id;
+	uint8_t bis_stop_reason;
```
Comment (Thalley) [inline tests/bluetooth/tester/src/audio/btp/btp_bap.h:283]:
```suggestion
	uint8_t reason;
```

Minor suggestion: `bis_stop` is kind of implied by the name of this struct :)

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c [hunk 2]
```diff
@@ -125,15 +125,30 @@ static void stream_started(struct bt_bap_stream *stream)
...
 static void stream_stopped(struct bt_bap_stream *stream, uint8_t reason)
 {
 	struct btp_bap_broadcast_stream *b_stream = stream_bap_to_broadcast(stream);
 
 	LOG_DBG("Stopped stream %p with reason 0x%02X", stream, reason);
 
 	btp_bap_audio_stream_stopped(&b_stream->audio_stream);
-
 	b_stream->bis_synced = false;
+	broadcaster = &remote_broadcast_sources[b_stream->source_id];
```
Comment (Thalley) [inline tests/bluetooth/tester/src/audio/btp_bap_broadcast.c:149]: I think it's missing the variable declaration for `broadcaster`: 
```c
struct btp_bap_broadcast_remote_source *broadcaster;
```

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c [hunk 3]
```diff
@@ -125,15 +125,30 @@ static void stream_started(struct bt_bap_stream *stream)
 	btp_send_bis_syced_ev(&broadcaster->address, broadcaster->broadcast_id, b_stream->bis_id);
 }
 
+static void btp_send_bis_stopped_ev(const bt_addr_le_t *address, uint32_t broadcast_id,
+				  uint8_t bis_id, uint8_t reason)
```
Comment (Thalley) [inline tests/bluetooth/tester/src/audio/btp_bap_broadcast.c:129]:
```suggestion
static void btp_send_bis_stopped_ev(const bt_addr_le_t *address, uint32_t broadcast_id,
				    uint8_t bis_id, uint8_t reason)
```

**Review by Thalley — CHANGES_REQUESTED** [review]

File: tests/bluetooth/tester/src/audio/btp/btp_bap.h (hunk 1 above)
Comment (Frodevan) [reply tests/bluetooth/tester/src/audio/btp/btp_bap.h]: Allright, this is now changed.

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c (hunk 2 above)
Comment (Frodevan) [reply tests/bluetooth/tester/src/audio/btp_bap_broadcast.c:152]: Missed that one, thanks

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c (hunk 3 above)
Comment (Frodevan) [reply tests/bluetooth/tester/src/audio/btp_bap_broadcast.c]: Right, my editor uses a different standard indentation, but updated to look nice on git now.

Comment (Thalley) [reply tests/bluetooth/tester/src/audio/btp_bap_broadcast.c]: If your editor supports https://editorconfig.org/ then it's easy to ensure that it works with many projects out of the box :)

**Review by Thalley — DISMISSED** [review]

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c [hunk 4]
```diff
@@ -484,13 +487,22 @@ uint8_t btp_bap_broadcast_source_stop(const void *cmd, uint16_t cmd_len,
...
 
 		return BTP_STATUS_FAILED;
 	}
 
+	err = k_sem_take(&sem_bis_stopped, K_MSEC(2000));
+	if (err != 0) {
+		LOG_DBG("Timed out waiting to stop BIS stream");
+
+		return BTP_STATUS_FAILED;
+	}
```
Comment (Thalley) [inline tests/bluetooth/tester/src/audio/btp_bap_broadcast.c:504]: `stream_stopped` that gives `sem_bis_stopped` may be called multiple times. 

You should take the same number of semaphores as we have streams.

**Review by Thalley — CHANGES_REQUESTED** [review]

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c (hunk 4 above)
Comment (Frodevan) [reply tests/bluetooth/tester/src/audio/btp_bap_broadcast.c]: This should now be resolved, given bt_bap_broadcast_source_stop stops broadcast source streams only.

**Comment by sjanc** [comment]
#AutoPTS run zephyr BAP/BSRC/SCC/BV-34-C

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c [hunk 5]
```diff
@@ -484,13 +487,24 @@ uint8_t btp_bap_broadcast_source_stop(const void *cmd, uint16_t cmd_len,
...
+	k_sem_reset(&sem_stream_stopped);
+
 	err = bt_bap_broadcast_source_stop(source->bap_broadcast);
 	if (err != 0) {
 		LOG_DBG("Unable to stop broadcast source: %d", err);
 
 		return BTP_STATUS_FAILED;
 	}
 
+	for (int i = 0; i < ARRAY_SIZE(source->streams); i++) {
```
Comment (sjanc) [inline tests/bluetooth/tester/src/audio/btp_bap_broadcast.c:499]: this should check for actual number of streams, not max supported, shouldn't it?

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/zephyrproject-rtos/zephyr/pull/79329#issuecomment-2391187947, board: nrf53, estimated start time: 13:34:00, test case count: 1, estimated duration: 0:00:20<details><summary>Test cases to be run</summary>BAP/BSRC/SCC/BV-34-C</details>

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c (hunk 5 above)
Comment (Frodevan) [reply tests/bluetooth/tester/src/audio/btp_bap_broadcast.c:499]: Right, must this be done with stream->in_use, or is this number stored in the struct?

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests (1)</summary>BAP     BAP/BSRC/SCC/BV-34-C            PASS</details>

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c (hunk 5 above)
Comment (Thalley) [reply tests/bluetooth/tester/src/audio/btp_bap_broadcast.c:499]: > Right, must this be done by checking stream->in_use, or is this number stored somewhere in the source struct?

I don't think we currently store it anywhere, but it's pretty easy to just add a counter in the `struct btp_bap_broadcast_remote_source` so that we always know how many `sem_stream_stopped` we should expect if we ever start fewer than `ARRAY_SIZE(source->streams)` streams

@sjanc any input?

Comment (Thalley) [reply tests/bluetooth/tester/src/audio/btp_bap_broadcast.c]: `stream_stopped` will be called per stream, regardless of the number of subgroups

**Review by Thalley — DISMISSED** [review]
Looks OK to me. Not sure about the timeout of `2000` ms, but I'll leave that to @sjanc :)

**Comment by Frodevan** [comment]
My reasoning for the timeout is that I have not checked if there is a timeout for this call in Auto-PTS, so an infinite wait here has potentially far greater consequences for a (very long) test run than just an error-code returned during a test-case.

**Comment by sjanc** [comment]
AutoPTS has 2s timeout for BTP response (after that it assumes IUT is dead), so I suggest having 1s timeout here (it should be more than enough anyway)

**Comment by Frodevan** [comment]
Timeout adjusted

**Review by sjanc — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

File: tests/bluetooth/tester/src/audio/btp_bap_broadcast.c [hunk 6]
```diff
@@ -484,13 +489,24 @@ uint8_t btp_bap_broadcast_source_stop(const void *cmd, uint16_t cmd_len,
...
+
 	err = bt_bap_broadcast_source_stop(source->bap_broadcast);
 	if (err != 0) {
 		LOG_DBG("Unable to stop broadcast source: %d", err);
 
 		return BTP_STATUS_FAILED;
 	}
 
+	for (int i = 0; i < source->stream_count; i++) {
+		err = k_sem_take(&sem_stream_stopped, K_MSEC(1000));
```
[the remark this answers is not in the document]
Comment (sjanc) [reply tests/bluetooth/tester/src/audio/btp_bap_broadcast.c:502]: to be very strict that timeout should be for all semaphores,  but since this will indicate bug in stack I don't think it matter much and adding time tracking would be overkill :-)
