### PR TITLE
arch: arm: mpu: nxp: disable mpu before reprogramming

### LINKED ISSUE #13482: The frdm_k64f board resets itself periodically/A possible NXP MPU bug
**Describe the bug**
The `frdm_k64f` board seems to simply reset itself periodically, no error or fault is shown.
It happens more or less often depending on the sample and its configuration.

**To Reproduce**
I've found, that it is the easiest to reproduce this issue using the `samples/net/gptp` sample, with `NET_BUF_POOL_USAGE` and `NET_DEBUG_NET_PKT_ALLOC` enabled. In such configuration, the board resets itself almost instantly (like every second), here is a sample output:

```
uart:~$ ***** Booting Zephyr OS v1.14.0-rc1-251-gd079ce05c7 *****
                                                                
                                                                
[00:00:00.007,651] <inf> net_config: Initializing network       
[00:00:00.007,676] <inf> net_config: IPv4 address: 192.0.2.1    
[00:00:00.110,076] <inf> net_config: IPv6 address: fe80::204:9fff:fe36:bf62
[00:00:00.110,163] <inf> net_config: IPv6 address: fe80::204:9fff:fe36:bf62
uart:~$ ***** Booting Zephyr OS v1.14.0-rc1-251-gd079ce05c7 *****
                                                                
                                                                
[00:00:00.007,651] <inf> net_config: Initializing network       
[00:00:00.007,676] <inf> net_config: IPv4 address: 192.0.2.1    
[00:00:00.110,076] <inf> net_config: IPv6 address: fe80::204:9fff:fe36:bf62
[00:00:00.110,163] <inf> net_config: IPv6 address: fe80::204:9fff:fe36:bf62
uart:~$ ***** Booting Zephyr OS v1.14.0-rc1-251-gd079ce05c7 *****
                                                                
                                                                
[00:00:00.007,651] <inf> net_config: Initializing network       
[00:00:00.007,676] <inf> net_config: IPv4 address: 192.0.2.1    
[00:00:00.110,076] <inf> net_config: IPv6 address: fe80::204:9fff:fe36:bf62
[00:00:00.110,163] <inf> net_config: IPv6 address: fe80::204:9fff:fe36:bf62
uart:~$ ***** Booting Zephyr OS v1.14.0-rc1-251-gd079ce05c7 *****
                                                                
                                                                
[00:00:00.007,651] <inf> net_config: Initializing network       
[00:00:00.007,676] <inf> net_config: IPv4 address: 192.0.2.1    
[00:00:00.110,076] <inf> net_config: IPv6 address: fe80::204:9fff:fe36:bf62
[00:00:00.110,163] <inf> net_config: IPv6 address: fe80::204:9fff:fe36:bf62

(...)
```

It does happen with other configurations/samples too. Just less often. I think that the number of threads plays a significant role too.

Also note, that even though it is a networking sample, the Ethernet cable does not even have to be connected to reproduce this.

**Expected behavior**
The resets should not be happening.

**Environment (please complete the following information):**
 - OS: Linux
 - Zephyr SDK
 - Commit SHA: d079ce05c7

**Additional context**

I bisected the code, and found, that this PR is when it started: #12817.

Looking at what is different to what was happening earlier, is that the main MPU region mapping is deleted and re-created each time the dynamic regions are to be changed (so when a thread is created or switched) - it seems that earlier, the main MPU mapping for RAM was done just once and left unchanged.

Looking at what actually happens there, I've noticed that there are some spinlocks, but the interrupts are never disabled - shouldn't they be?

I've come with a following fix:
```
From fc5b87fb2dff32d4348725da1e22fd276acb2f81 Mon Sep 17 00:00:00 2001
From: Tomasz Gorochowik <tgorochowik@antmicro.com>
Date: Mon, 18 Feb 2019 16:08:01 +0100
Subject: [PATCH] arch: arm: mpu: Lock interrupts before re-mapping MPU

This fixes the issue with periodical resets of the frdm_k64f board.

Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>
---
 arch/arm/core/cortex_m/mpu/arm_core_mpu.c | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/arch/arm/core/cortex_m/mpu/arm_core_mpu.c b/arch/arm/core/cortex_m/mpu/arm_core_mpu.c
index 6ebedd1948..1e395c855f 100644
--- a/arch/arm/core/cortex_m/mpu/arm_core_mpu.c
+++ b/arch/arm/core/cortex_m/mpu/arm_core_mpu.c
@@ -130,6 +130,7 @@ void _arch_configure_dynamic_mpu_regions(struct k_thread *thread)
 	struct k_mem_partition dynamic_regions[_MAX_DYNAMIC_MPU_REGIONS_NUM];
 
 	u8_t region_num = 0;
+	int key;
 
 #if defined(CONFIG_USERSPACE)
 	/* Memory domain */
@@ -208,9 +209,13 @@ void _arch_configure_dynamic_mpu_regions(struct k_thread *thread)
 	region_num++;
 #endif /* CONFIG_MPU_STACK_GUARD */
 
+	key = irq_lock();
+
 	/* Configure the dynamic MPU regions */
 	arm_core_mpu_configure_dynamic_mpu_regions(dynamic_regions,
 		region_num);
+
+	irq_unlock(key);
 }
 
 #if defined(CONFIG_USERSPACE)
-- 
2.20.1
```

This seems to fully resolve the issue for me. However I am not sure if that is the correct approach to solving this issue and thus I decided to post it as an issue rather than a PR.

@ioannisg would you mind taking a look at this as the author of the PR I mentioned?

### PR DESCRIPTION
**Pull request by tgorochowik**
This is needed, because an interrupt can happen after the main/static
MPU region is disabled and before it is re-enabled.

This region gets implicitly disabled inside the _region_init call, when
its configuration registers changes:

```
  SYSMPU->WORD[index][0] = region_base;
  SYSMPU->WORD[index][1] = region_end;
  SYSMPU->WORD[index][2] = region_attr;
  SYSMPU->WORD[index][3] = SYSMPU_WORD_VLD_MASK;

```
The TRM says this about the WORD0, WORD1 and WORD2 registers:

>   Writes to this register clear the region descriptor’s valid bit
>   (RGDn_WORD3[VLD]).

And thus if an interrupt happens after writing to WORD0 and before
writing VLD to WORD3 again, the code executes with enabled and yet
misconfigured MPU.

Fixes #13482

Signed-off-by: Tomasz Gorochowik <tgorochowik@antmicro.com>

### CODE REVIEW

File: arch/arm/core/cortex_m/mpu/nxp_mpu.c [hunk 1]
```diff
@@ -328,8 +328,10 @@ static int _mpu_configure_dynamic_mpu_regions(const struct k_mem_partition
 	/* Reset MPU regions inside which dynamic memory regions may
 	 * be programmed.
 	 */
+	arm_core_mpu_disable();
```
Comment (ioannisg) [inline arch/arm/core/cortex_m/mpu/nxp_mpu.c]: Could you please, add a short comment, to elaborate why this disable/enable protection is needed here, and not in other invocations of region_init()?
For example:

Re-programming these regions will temporarily leave memory areas outside all MPU regions.
This might trigger memory faults if ISRs occurring during re-programming perform access in
those areas.

**Review by ioannisg — CHANGES_REQUESTED** [review]
Thanks for the patch!
Left a comment for being a bit more verbose on why this patch is needed.

File: arch/arm/core/cortex_m/mpu/nxp_mpu.c (hunk 1 above)
Comment (tgorochowik) [reply arch/arm/core/cortex_m/mpu/nxp_mpu.c]: Thanks! Just added the comment you suggested.

**Review by ioannisg — APPROVED** [review]
This looks ok to me. It adds some little run-time overhead (1 register write and 1 barrier instruction) before and after re-programming the SRAM MPU region at every context-switch, which has the lowest IRQ priority, anyways.
This should be acceptable, IMHO.

**Comment by ioannisg** [comment]
@MaureenHelm @agross-linaro , pls, take a quick look, as well.

**Comment by tgorochowik** [comment]
Pushed a typo fix in the commit message.

**Review by agross-oss — APPROVED** [review]

**Comment by tgorochowik** [comment]
(force-pushed without changes because CI seems to be stuck)
