### PR TITLE
uart_stm32: fix a dead lock on poll_out if it's called in interrupt

### LINKED ISSUE #40775: stm32: mutli-threading broken after #40173
**Describe the bug**
Following merge of #40173, some multi-threading use cases are not working anymore.
This change aimed at introducing a lock on uart tx in order to avoid conflicts between competitive calls to uart_poll and fifo_fill.
While it fixed the targeted issue, it introduced a regression in multi-thread use cases.

Regression can be observed with the following samples:
 samples/kernel/metairq_dispatch/sample.kernel.metairq_dispatch
samples/philosophers/sample.kernel.philosopher
samples/philosophers/sample.kernel.philosopher.fifos
samples/philosophers/sample.kernel.philosopher.lifos
samples/philosophers/sample.kernel.philosopher.same_prio
samples/philosophers/sample.kernel.philosopher.semaphores
samples/philosophers/sample.kernel.philosopher.stacks
samples/philosophers/sample.kernel.philosopher.static
samples/subsys/portability/cmsis_rtos_v1/philosophers/sample.portability.cmsis_rtos_v1.philosopher
and so on ...

**Logs and console output**
Info thread on `sample.kernel.philosopher`  reports the following:
```
0x08005100 in atomic_cas (new_value=1, old_value=0, target=0x20000020 <uart_stm32_data_0+8>) at /local/mcu/zephyrproject/zephyr/include/sys/atomic_builtin.h:40
40		return __atomic_compare_exchange_n(target, &old_value, new_value,
(gdb) info threads
  Id   Target Id                                                  Frame 
* 1    Thread 536871920 (Name: Philosopher 5, prio:-2,useropts:4) 0x08005100 in atomic_cas (new_value=1, old_value=0, target=0x20000020 <uart_stm32_data_0+8>)
    at /local/mcu/zephyrproject/zephyr/include/sys/atomic_builtin.h:40
Info : Getting thread 536871744 reg list
  2    Thread 536871744 (Name: Philosopher 4, prio:-1,useropts:4) 0x080013c0 in arch_irq_unlock (key=0)
    at /local/mcu/zephyrproject/zephyr/include/arch/arm/aarch32/asm_inline_gcc.h:95
Info : Getting thread 536871568 reg list
  3    Thread 536871568 (Name: Philosopher 3, prio:0,useropts:4)  0x080013c0 in arch_irq_unlock (key=0)
    at /local/mcu/zephyrproject/zephyr/include/arch/arm/aarch32/asm_inline_gcc.h:95
Info : Getting thread 536871392 reg list
  4    Thread 536871392 (Name: Philosopher 2, prio:1,useropts:4)  0x080013c0 in arch_irq_unlock (key=0)
    at /local/mcu/zephyrproject/zephyr/include/arch/arm/aarch32/asm_inline_gcc.h:95
Info : Getting thread 536871216 reg list
  5    Thread 536871216 (Name: Philosopher 1, prio:2,useropts:4)  0x080013c0 in arch_irq_unlock (key=0)
    at /local/mcu/zephyrproject/zephyr/include/arch/arm/aarch32/asm_inline_gcc.h:95
Info : Getting thread 536871040 reg list
  6    Thread 536871040 (Name: Philosopher 0, prio:3,useropts:4)  0x08005118 in LL_USART_IsActiveFlag_TXE (USARTx=0x40013800)
    at /local/mcu/zephyrproject/modules/hal/stm32/stm32cube/stm32l4xx/drivers/include/stm32l4xx_ll_usart.h:3161
Info : Getting thread 536872096 reg list
  7    Thread 536872096 (Name: idle 00, prio:40,useropts:1)       arch_cpu_idle () at /local/mcu/zephyrproject/zephyr/arch/arm/core/aarch32/cpu_idle.S:110
```

Philosopher 0 (prio:3) is preempted in `uart_stm32_poll_out` during TX (while waiting for flag TXE: `LL_USART_IsActiveFlag_TXE`), tx_lock is granted
Philosopher 5 (prio:-2) is running but stuck in `uart_stm32_poll_out`, waiting for `tx_lock` to be released, which won't happen as it is taken by lower prio thread.
-> Deadlock

**To Reproduce**
Run one of the above on any STM32 board

**Expected behavior**
These samples should be passed

**Impact**
Dead-lock situations in multi-threaded contexts

**Environment (please complete the following information):**
 - Toolchain: Zephyr SDK 0.13.1
 - Commit SHA: Starting d42cef17b06465393462210a224fdc5cc58b1490

### PR DESCRIPTION
**Pull request by jdascenzio**
If the function poll_out is called in an interrupt with a higher
priority than the usart priority, the function could lock forever. In
fact, the lock variable is never unset if the usart interrupt is no
longer called. So now, we don't use the lock variable if poll_out is
called in interrupt.

Fixes #40775

Signed-off-by: Julien D'ascenzio <julien.dascenzio@paratronic.fr>

### CODE REVIEW

**Comment by erwango** [comment]
@jdascenzio Thanks, though I think there's a wider issue to fix, cf https://github.com/zephyrproject-rtos/zephyr/issues/40775

**Review by erwango — CHANGES_REQUESTED** [review]
https://github.com/zephyrproject-rtos/zephyr/issues/40775 should be taken into account

**Comment by jdascenzio** [comment]
I modified the patch to fix #40775. I hope this commit is the last to fix competitive calls to fifo_fill and uart_poll!

**Comment by jdascenzio** [comment]
add lock to uart_stm32_irq_tx_enable and uart_stm32_irq_tx_disable to avoid race condition

File: drivers/serial/uart_stm32.c [hunk 1]
```diff
@@ -525,21 +525,25 @@ static void uart_stm32_poll_out(const struct device *dev,
...
 	USART_TypeDef *UartInstance = UART_STRUCT(dev);
+#ifdef CONFIG_PM
 	struct uart_stm32_data *data = DEV_DATA(dev);
+#endif
+	int key;
 
 	/* Wait for TXE flag to be raised */
 	while (1) {
-		if (atomic_cas(&data->tx_lock, 0, 1)) {
+		if (LL_USART_IsActiveFlag_TXE(UartInstance)) {
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:535]: Please add a comment on what you're doing here since this is not obvious.
The commit message explain why previous solution was not working, 
but we also need to understand why current code is correct.
For this in line comments would be great

**Review by erwango — CHANGES_REQUESTED** [review]
Some comments needed.
Meanwhile, I'm running broad tests and will keep you informed of the result

File: drivers/serial/uart_stm32.c (hunk 1 above)
Comment (jdascenzio) [reply drivers/serial/uart_stm32.c:539]: I have added comments which hopefully clarify the code

**Review by erwango — APPROVED** [review]
LGTM, and I confirm this fixes #40775

**Review by dcpleung — APPROVED** [review]

**Review by DariusBabrauskas — COMMENTED** [review]
It looks Ok

**Review by DariusBabrauskas — APPROVED** [review]

File: drivers/serial/uart_stm32.c [hunk 2]
```diff
@@ -525,21 +525,32 @@ static void uart_stm32_poll_out(const struct device *dev,
...
+	 */
 	while (1) {
-		if (atomic_cas(&data->tx_lock, 0, 1)) {
+		if (LL_USART_IsActiveFlag_TXE(UartInstance)) {
+			key = irq_lock();
 			if (LL_USART_IsActiveFlag_TXE(UartInstance)) {
 				break;
 			}
-			atomic_set(&data->tx_lock, 0);
+			irq_unlock(key);
```
Comment (DariusBabrauskas) [inline drivers/serial/uart_stm32.c:544]: if (!k_is_in_isr() && key == 0){			
			k_yield();//yield execution to another thread of the same or higher priority. Its better for software, but not output pretty (some symbols  from shell some from kprint)
		}

**Review by DariusBabrauskas — CHANGES_REQUESTED** [review]
It seems to me, that need yield task if we not interrupt mode, and not disabled interrupts (k==0).

File: drivers/serial/uart_stm32.c (hunk 2 above)
Comment (jdascenzio) [reply drivers/serial/uart_stm32.c:544]: ok, k_yield could be interesting to reduce some cpu usage. But, I don't understand why you want check key?

**Review by DariusBabrauskas — COMMENTED** [review]
I do some self test on my system (stm32L4A6, zephyr 2.5) and noticed that I lost bytes on  terminal :( .
Exmp.  in switch interrupts kprint("ZzzzZ");  . On terminal output I often see zzzZ[0m  or zzzZJ... . So I lost first Z, but at and I see strange symbols.  Log messages lost too. hmm.

File: drivers/serial/uart_stm32.c (hunk 2 above)
Comment (DariusBabrauskas) [reply drivers/serial/uart_stm32.c:544]: If key == 0 then  interrupts not disabled. So we can safe yield. I do not study  yield, when interrupts is disabled.

**Review by DariusBabrauskas — CHANGES_REQUESTED** [review]
I noticed that irq_lock and irq_unlock don't have DSB() operation.  Possible her is cause of problems.  I can manualy add DSB for test purpose.

**Comment by ycsin** [comment]
> I do some self test on my system (stm32L4A6, zephyr 2.5) and noticed that I lost bytes on terminal :( . Exmp. in switch interrupts kprint("ZzzzZ"); . On terminal output I often see zzzZ[0m or zzzZJ... . So I lost first Z, but at and I see strange symbols. Log messages lost too. hmm.

Do you have `CONFIG_PM` enabled in your build? It could be related to this issue #39220
The "strange bytes" (starts with `[` followed by `0m`/`J`/etc) are the control characters / color code for the shell.

**Comment by DariusBabrauskas** [comment]
> > I do some self test on my system (stm32L4A6, zephyr 2.5) and noticed that I lost bytes on terminal :( . Exmp. in switch interrupts kprint("ZzzzZ"); . On terminal output I often see zzzZ[0m or zzzZJ... . So I lost first Z, but at and I see strange symbols. Log messages lost too. hmm.
> 
> Do you have `CONFIG_PM` enabled in your build? It could be related to this issue #39220 The "strange bytes" (starts with `[` followed by `0m`/`J`/etc) are the control characters / color code for the shell.

Yes you right. Than you.

**Review by FRASTM — APPROVED** [review]

File: drivers/serial/uart_stm32.c [hunk 3]
```diff
@@ -525,21 +525,36 @@ static void uart_stm32_poll_out(const struct device *dev,
...
-	/* Wait for TXE flag to be raised */
+	/* Wait for TXE flag to be raised
+	 * When TXE flag is raised, we lock interrupts to prevent interrupts (notably that of usart)
+	 * or thread switch. Then, we can safely send our character. The character sent will be
+	 * interlaced with the characters potentially send with interrupt transmission API
+	 */
 	while (1) {
-		if (atomic_cas(&data->tx_lock, 0, 1)) {
+		if (LL_USART_IsActiveFlag_TXE(UartInstance)) {
+			key = irq_lock();
```
Comment (DariusBabrauskas) [inline drivers/serial/uart_stm32.c:540]: __DSB();

File: drivers/serial/uart_stm32.c [hunk 4]
```diff
@@ -525,21 +525,36 @@ static void uart_stm32_poll_out(const struct device *dev,
...
 			if (LL_USART_IsActiveFlag_TXE(UartInstance)) {
 				break;
 			}
-			atomic_set(&data->tx_lock, 0);
+			irq_unlock(key);
```
Comment (DariusBabrauskas) [inline drivers/serial/uart_stm32.c:544]: __DSB();

**Review by DariusBabrauskas — CHANGES_REQUESTED** [review]

File: drivers/serial/uart_stm32.c (hunk 3 above)
Comment (DariusBabrauskas) [reply drivers/serial/uart_stm32.c:540]: //My test show, that __DSB();   commands helped. No more lost first symbols!

**Review by DariusBabrauskas — CHANGES_REQUESTED** [review]
It seems to me, that need change uart_stm32_fifo_fill function too. Protection from nested interrupts .
```
static int uart_stm32_fifo_fill(const struct device *dev,
				  const uint8_t *tx_data,
				  int size)
{
	USART_TypeDef *UartInstance = UART_STRUCT(dev);
	uint8_t num_tx = 0U;
	int key;

	if(LL_USART_IsActiveFlag_TXE(UartInstance))
	{
		key = irq_lock();//prevent nested interrupts or thread switch
		__DSB();
		while ((size - num_tx > 0) && //only max 2 bytes sent at time - no latency, because first byte in shift register second hold in TXD register
			   LL_USART_IsActiveFlag_TXE(UartInstance)) {
			/* TXE flag will be cleared with byte write to DR|RDR register */

			/* Send a character (8bit , parity none) */
			LL_USART_TransmitData8(UartInstance, tx_data[num_tx++]);
		}
		irq_unlock(key);
		__DSB();
	}

	return num_tx;
}
```

**Comment by jdascenzio** [comment]
> It seems to me, that need change uart_stm32_fifo_fill function too. Protection from nested interrupts .
> 
> ```
> static int uart_stm32_fifo_fill(const struct device *dev,
> 				  const uint8_t *tx_data,
> 				  int size)
> {
> 	USART_TypeDef *UartInstance = UART_STRUCT(dev);
> 	uint8_t num_tx = 0U;
> 	int key;
> 
> 	if(LL_USART_IsActiveFlag_TXE(UartInstance))
> 	{
> 		key = irq_lock();//prevent nested interrupts or thread switch
> 		__DSB();
> 		while ((size - num_tx > 0) && //only max 2 bytes sent at time - no latency, because first byte in shift register second hold in TXD register
> 			   LL_USART_IsActiveFlag_TXE(UartInstance)) {
> 			/* TXE flag will be cleared with byte write to DR|RDR register */
> 
> 			/* Send a character (8bit , parity none) */
> 			LL_USART_TransmitData8(UartInstance, tx_data[num_tx++]);
> 		}
> 		irq_unlock(key);
> 		__DSB();
> 	}
> 
> 	return num_tx;
> }
> ```

You are right, it is necessary to protect here the reading of TXE flag.
However, I'm not familiar with memory/instruction barrier. But, if you say that there may be a problem with the order of the execution of the instructions (usage of DSB), after irq_[lock/unlock], then, the type of problem could happen every time these functions are used. It would then be perhaps more judicious to integrate this barrier directly in irq_[lock/unlock]....

**Comment by cfriedt** [comment]
Is this ready to merge yet @jdascenzio ? Will you be adding the `__DSB()` calls that @DariusBabrauskas asked for?

**Comment by erwango** [comment]
Setting DNM until the direction is clear.

**Comment by jdascenzio** [comment]
I added a lock in fifo_fill function.
For me, irq_lock already has an instruction barrier with isb:
```c
static ALWAYS_INLINE unsigned int arch_irq_lock(void)
{
 # .......

#elif defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
	unsigned int tmp;

	__asm__ volatile(
		"mov %1, %2;"
		"mrs %0, BASEPRI;"
		"msr BASEPRI_MAX, %1;"
		"isb;"
		: "=r"(key), "=r"(tmp)
		: "i"(_EXC_IRQ_DEFAULT_PRIO)
		: "memory");
```
@DariusBabrauskas, Don't you think that's enough?
The character that you were losing, was it not related to the forgotten lock in fifo_fill?

**Comment by DariusBabrauskas** [comment]
> I added a lock in fifo_fill function. For me, irq_lock already has an instruction barrier with isb:
> 
> ```c
> static ALWAYS_INLINE unsigned int arch_irq_lock(void)
> {
>  # .......
> 
> #elif defined(CONFIG_ARMV7_M_ARMV8_M_MAINLINE)
> 	unsigned int tmp;
> 
> 	__asm__ volatile(
> 		"mov %1, %2;"
> 		"mrs %0, BASEPRI;"
> 		"msr BASEPRI_MAX, %1;"
> 		"isb;"
> 		: "=r"(key), "=r"(tmp)
> 		: "i"(_EXC_IRQ_DEFAULT_PRIO)
> 		: "memory");
> ```
> 
> @DariusBabrauskas, Don't you think that's enough? The character that you were losing, was it not related to the forgotten lock in fifo_fill?
Possible lost symbols was terminal log problem, which try hide escape sequences. I enabled binary log then I see all symbols. No lost with dsb or without (fifo_fill was edited).
So maybe you are right,- isb is enought.
It seem too me, that dsb must be after isb. I see dsb after isb in others systems. This operatios are different.

**Comment by erwango** [comment]
Let's have a new round of review and test, considering the recent changes.

File: drivers/serial/uart_stm32.c [hunk 5]
```diff
@@ -615,6 +630,13 @@ static int uart_stm32_fifo_fill(const struct device *dev,
 {
 	USART_TypeDef *UartInstance = UART_STRUCT(dev);
 	uint8_t num_tx = 0U;
+	int key;
+
+	if (!LL_USART_IsActiveFlag_TXE(UartInstance))
+		return 0;
```
Comment (dcpleung) [inline drivers/serial/uart_stm32.c:636]: Needs brackets even for a one line statement.

**Review by dcpleung — CHANGES_REQUESTED** [review]
Just a minor one about brackets.

Have this been tested in actual hardware, with different scenarios?

File: drivers/serial/uart_stm32.c (hunk 5 above)
Comment (jdascenzio) [reply drivers/serial/uart_stm32.c]: I had the brackets

File: drivers/serial/uart_stm32.c [hunk 6]
```diff
@@ -652,30 +677,44 @@ static int uart_stm32_fifo_read(const struct device *dev, uint8_t *rx_data,
...
 
 static void uart_stm32_irq_tx_disable(const struct device *dev)
 {
 	USART_TypeDef *UartInstance = UART_STRUCT(dev);
+#ifdef CONFIG_PM
 	struct uart_stm32_data *data = DEV_DATA(dev);
+	int key;
 
-	LL_USART_DisableIT_TC(UartInstance);
+	key = irq_lock();
```
Comment (erwango) [inline drivers/serial/uart_stm32.c:705]: Is there a real reason to have a different behavior w/ and w/o PM ?

Comment (jdascenzio) [reply drivers/serial/uart_stm32.c:705]: Yes, these different behaviors are used to deal with pm_constraint to prevent suspension (see e3f4907efe6438a4b28f17167c58a2e25865c295)

**Review by dcpleung — APPROVED** [review]

**Review by DariusBabrauskas — APPROVED** [review]

**Comment by erwango** [comment]
@cfriedt This PR was tagged "Blocked: HW tests". It should not have been merged..
Hopefully the tests will be passed.

**Comment by cfriedt** [comment]
> @cfriedt This PR was tagged "Blocked: HW tests". It should not have been merged..
> Hopefully the tests will be passed.

Apologies @erwango - best to request changes so that it does not make it past filters.

**Comment by erwango** [comment]
@cfriedt Agree, but then, let's remove "Blocked: HW test", if it can be trusted.

**Comment by erwango** [comment]
Ok, tests are passed. At least the in tree ones. I trust @jdascenzio to test the PM ones

**Comment by jdascenzio** [comment]
No problems for me with CONFIG_PM. I don't lose any characters
